### ISSUE TITLE
Container gets ipv6 DNS servers but no ip address

### ISSUE THREAD

**Issue by jansauer** [docker/docker#10000]
I added ipv6 support to one of my coreos instances by supplying a additional ipv6 address, gateway and 2 dns servers with my cloud-config. After doing so my container get the ipv6 dns server but only a link-local address and are unable do reach a ipv6 address or resolve a hostname.

**Comment by shykes** [comment]
:tada: :balloon: :balloon:

**Comment by jfrazelle** [comment]
:100: 00

**Comment by jlhawn** [comment]
:tada: :whale:

(MULTIPLY :100:  :100: )

**Comment by cyphar** [comment]
:+1::shipit:
