### ISSUE TITLE
Tests required for IPv6

### ISSUE THREAD

**Issue by MalteJ** [docker/docker#10001]
We need some tests to ensure the [IPv6 implementation](https://github.com/docker/docker/pull/8947) is working as expected.

**Comment by emsi** [comment]
Please provide some instructions. I built 1.4.1-dev but it says flag provided but not defined: --ipv6.

**Comment by MalteJ** [comment]
@emsi you may download the compiled binary here: https://master.dockerproject.com/
and then put it to /usr/bin/docker

**Comment by emsi** [comment]
That's exactly what I did. I followed the the build instructions and it produced docker-1.4.1-devel:

```sh
root@emsi-docker:~/git/docker# docker version
Client version: 1.4.1-dev
Client API version: 1.16
Go version (client): go1.4
Git commit (client): de97839
OS/Arch (client): linux/amd64
Server version: 1.4.1-dev
Server API version: 1.16
Go version (server): go1.4
Git commit (server): de97839
```

which says:

```flag provided but not defined: --ipv6```

The source seems right:
```sh
root@emsi-docker:~/git/docker# grep EnableIPv6 daemon/config.go 
        EnableIPv6                  bool
        flag.BoolVar(&config.EnableIPv6, []string{"-ipv6"}, false, "Enable IPv6 networking")
```
Should I enable is somehow at build time?

**Comment by MalteJ** [comment]
You have to start Docker as a Daemon: `docker -d --ipv6 --fixed-cidr-v6=2001:db8::/64`

BTW: You are off-topic in this issue ;)
This issue is about creating unit tests for the IPv6 source code.
Feel free to create a new Issue with your specifiec problem :-)

**Comment by Tr4pSt3R** [comment]
@emsi and @MalteJ do you need help or support with this testing? I can help or collaborate with you guys on?

**Comment by MalteJ** [comment]
@Tr4pSt3R yeah, would be nice if I'd get some help creating the unit and integration tests. My time is a bit limited at the moment.

**Comment by Tr4pSt3R** [comment]
:+1: @simonswine LGTM (but have to admit, I haven't run it though.)
