### ISSUE TITLE
Throttling host disk I/O for the container error

### ISSUE THREAD

**Issue by hustcat** [docker/docker#10004]
I mount host disk directory as data volume for container:
```sh
# ls -lh /dev/sda4
brw-rw---- 1 root disk 8, 4 Sep 17 19:28 /dev/sda4
# mount   
/dev/sda4 on /data type ext3 (rw,noatime,acl,user_xattr)
...
# docker run -it --rm  --device=/dev/sda4 -v /data/vm1:/data centos:centos6 /bin/bash             
bash-4.1#
```
and I want throttling disk IO with cgroup, but I get some errors:
```sh
# docker ps
CONTAINER ID        IMAGE                     COMMAND                CREATED             STATUS              PORTS                    NAMES
ff375e466678        centos:centos6            "/bin/bash"            10 seconds ago      Up 8 seconds                                 furious_morse  
# echo "8:4 10485760" > /cgroup/blkio/docker/ff375e466678efc404dad4c642e9c11cb170cdf3a1919ba16619381f6a4ec62c/blkio.throttle.write_bps_device
-bash: echo: write error: No such device  #error
```
However, I can throttling devicemapper thin volume of container's rootfs:
```sh
# ls -lh /dev/mapper/docker-8\:1-701074-ff375e466678efc404dad4c642e9c11cb170cdf3a1919ba16619381f6a4ec62c 
lrwxrwxrwx 1 root root 7 Jan  9 18:45 /dev/mapper/docker-8:1-701074-ff375e466678efc404dad4c642e9c11cb170cdf3a1919ba16619381f6a4ec62c -> ../dm-7
#ls -lh /dev/dm-7 
brw-rw---- 1 root disk 253, 7 Jan  9 18:45 /dev/dm-7

# echo "253:7 10485760" > /cgroup/blkio/docker/ff375e466678efc404dad4c642e9c11cb170cdf3a1919ba16619381f6a4ec62c/blkio.throttle.write_bps_device  #success
```
Did someone came across this problem?

```sh
# docker --version
Docker version 1.3.1, build 4e9bbfa
# uname -a
Linux yinye 2.6.32-431.el6.x86_64
```

**Comment by xiaods** [comment]
Upgrade to 3.8, use cgroup.

**Comment by thaJeztah** [comment]
You can check the (kernel) requirements here: https://docs.docker.com/installation/binaries/#check-kernel-dependencies

Note that custom kernels (I *think* you're using a custom kernel) are not officially supported, it may work, but no promises whatsoever.

**Comment by hustcat** [comment]
@xiaods @thaJeztah thanks.I upgrade to 3.10, but still get some errors:

```sh
# echo "8:4 1048576" > blkio.throttle.write_bps_device 
-bash: echo: write error: Invalid argument

# echo "253:1 1048576" > blkio.throttle.write_bps_device  #OK

# uname -a
Linux TENCENT64.site 3.10.63-1.el6.elrepo.x86_64 #1 SMP Tue Dec 16 16:52:21 EST 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by xiaods** [comment]
first grasp major:minor value from /proc/partitions
then add throttle value to your cgroup settings. then restart your cgroup service. but first , custom kernel is not officially supported from community.

**Comment by hustcat** [comment]
I made a mistake. From [here](https://bitbucket.org/hustcat/kernel-2.6.32/src/3a681c756026cf28e4937c05414d5168106b5300/block/blk-cgroup.c?at=master#cl-774), we can found only device is surpported, partition is not surpported

**Comment by pankit** [comment]
Hi @hustcat : I am getting the same error on a ubuntu 14 hosted on a virtual box. I get this:

echo '8:1 1048576' > /sys/fs/cgroup/blkio/io-test/blkio.throttle.read_bps_device 
bash: echo: write error: Invalid argument

**Comment by pankit** [comment]
Nvrmind, just had to replace 8:1 with 8:0. worked!!
