### ISSUE TITLE
docs css issues

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#10007]
![2015-01-09-12-43-21_1920x1080](https://cloud.githubusercontent.com/assets/1445228/5686992/e120d1a2-97fc-11e4-994f-15ab1d486f0c.png)

**Comment by jfrazelle** [comment]
the header and hovering is all effed, chrome stable on linux

**Comment by thaJeztah** [comment]
@jfrazelle Which version is that? I did a quick check on browserstack, using Chrome 36. And those look okay;
http://www.browserstack.com/screenshots/50a560a2510d543124d008e4e0c73efb5d550871

Unfortunately they don't seem to have a Linux (at least not in the screenshot section)

**Comment by thaJeztah** [comment]
Oh wait, its when hovering only?

**Comment by jfrazelle** [comment]
Version 39.0.2171.95 (64-bit)

could be a linux only thing

**Comment by jfrazelle** [comment]
its there without hovering, but on hover the menu looks super fubar

**Comment by thaJeztah** [comment]
Just tested it on 39 and 40-dev OS X and it seemed to be okay. (also when hovering).

I can try other platforms on browserstack. Happy to debug, but unfortunately, don't have a Linux desktop around here. Maybe I should containerize Chrome :smile:

**Comment by jfrazelle** [comment]
![2015-01-09-13-27-22_1916x1041](https://cloud.githubusercontent.com/assets/1445228/5687563/f1428f16-9802-11e4-9543-5a643cf19463.png)

**Comment by jfrazelle** [comment]
ya but thats osx :D 
i can try and figure it out later haha I hate browsers

**Comment by thaJeztah** [comment]
The current CSS extensively uses a "float"; which is sometimes troublesome. Looking at your screenshot, it looks like the top menu is too wide, causing the the "log-in" / "sign-up" block to wrap.

I can reproduce if I change the width of `.navbar-static-top .container` to be less wide (around 860px)
 
I see some other weird stuff as well (the top-nav is included *twice* on the page, once hidden, once visible (depending on whether you're logged in or not). Guess that's by "design" but weird still.

**Comment by jfrazelle** [comment]
ya, hard to believe, but about three years ago or so I used to do some css
hahaha
I will see if I can take a swing at it

**Comment by thaJeztah** [comment]
Comparing screenshots, I think the problem lies in font-rendering; fonts on my machine are rendered less wide. Probably on your machine they are "just" narrow enough to make it work, but on hover, they cause the menu elements to wrap.

**Comment by thaJeztah** [comment]
![screen shot 2015-01-09 at 22 48 32](https://cloud.githubusercontent.com/assets/1804568/5687898/c11401a4-9851-11e4-9ad9-d01e354fce01.png)

**Comment by jfrazelle** [comment]
but that doesnt make sense as to how in the first screenshot the left is perfect, but the master build is broken on the right

**Comment by thaJeztah** [comment]
Erm, in noticed in the left one you're logged in, in the right one you're not.

**Comment by jfrazelle** [comment]
its literally only happening for me.... so closing lol

**Comment by thaJeztah** [comment]
Well, it was fun! Perhaps time to switch back to OS X? :smiley:

**Comment by jfrazelle** [comment]
hahaha NEVER! I will take my wonky header anyday :)

**Comment by thaJeztah** [comment]
Hehe, I know. Just too GUI minded myself, but can really admire people being able to vim. Perhaps should try it again some day, just couldn't get my head around it last time I tried.
