### ISSUE TITLE
Impossible to make docs

### ISSUE THREAD

**Issue by aanm** [docker/docker#10012]
Description of problem:
sudo make docs doesn't work

`docker version`:

Client version: 1.4.0
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 4595d4f/1.4.0
OS/Arch (client): linux/amd64
Server version: 1.4.0
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 4595d4f/1.4.0

`docker info`:

Containers: 14
Images: 41
Storage Driver: devicemapper
 Pool Name: docker-253:14-712-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 2.436 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 4.268 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.90 (2014-09-01)
Execution Driver: native-0.2
Kernel Version: 3.17.7-300.fc21.x86_64
Operating System: Fedora 21 (Twenty One)
CPUs: 4
Total Memory: 7.565 GiB
Name: am-laptop
ID: J63E:XS2T:XLRU:BZ5Y:7FNM:WVYU:JEST:PPG7:E4C5:C2NH:JWNN:Z3H6
Debug mode (server): false
Debug mode (client): true
Fds: 27
Goroutines: 27
EventsListeners: 0
Init SHA1: 4f60b930d8ebd3077449be75d2d014e97d35f6c9
Init Path: /usr/libexec/docker/dockerinit
Docker Root Dir: /var/lib/docker

`uname -a`:

Linux am-laptop 3.17.7-300.fc21.x86_64 #1 SMP Wed Dec 17 03:08:44 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):

How reproducible: Always

Steps to Reproduce:
1. git pull
2. sudo make docs

Actual Results:
git diff --name-status upstream/release..upstream/docs docs/ > docs/changed-files
fatal: ambiguous argument 'upstream/release..upstream/docs': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Makefile:86: recipe for target 'docs-build' failed
make: *** [docs-build] Error 128

Expected Results:

make: 'docs' is up to date. (Or similar)

Additional info:

**Comment by jfrazelle** [comment]
1. you dont have a remote name upstream
2. I fixed this in https://github.com/docker/docker/pull/10006
