### ISSUE TITLE
Proposal: Hostname in /etc/hosts pointing to the host

### ISSUE THREAD

**Issue by retog** [docker/docker#10023]
It would be handy if there would be an option that creates an entry in the /etc/hosts of the container to point to the host, i.e. to the ip of the default gateway (like the ip one can get with /sbin/ip route|awk '/default/ { print $3 }')

**Comment by apheleia** [comment]
What's wrong with `ip route`?
You could also run whatever service you want to contact inside another, linked container instead of your host. Then you can access those containers by hostname.

**Comment by retog** [comment]
Having a name would just be easier, say you want to configure the container to use the X-Server, the Pulseaudio sever or the printserver running on the host. Using ip route you might need to write some script that modify config files when the container is started, with an entry in /etc/hosts it would be easier. Of course you can argue that everything should be run in containers and so there should be no service at all on the host, but the perfect is the enemy of the good ;)

**Comment by icecrime** [comment]
This is something you should be able to achieve with `docker run --add-host host:ip`. I don't think we'd like to hardcode it though.

Let me know if that works for you and if we can close the issue.

**Comment by apheleia** [comment]
@retog you can also have a look at #1143 

one option mentioned there is:
- bind mount a socket file to access the service through that socket (e.g. `docker run -v /var/run/docker.sock:/var/run/docker.sock …`)

You could also build your own container with a start wrapper script that calls `exec` after adding the output of `/sbin/ip route|awk '/default/ { print $3 }'` to an environment variable or file (one possible file would even be `/etc/hosts`)

Anyways: #1143 has a long discussion if you're interested

**Comment by retog** [comment]
@icecrime the problem with this approach is how to know the ip. How do I know for example the ip of the default gateway in the container will be 172.17.42.1?

**Comment by retog** [comment]
@apheleia thanks for the pointers

What @elgalu suggets here: https://github.com/docker/docker/issues/1143#issuecomment-48400636 is almost exactly what this issue ask for. It seems that other are having the issue too and (having an option) to add an entry to /etc/hosts seems the easiest approach.

As for commit `5405008` see my comment above.

**Comment by icecrime** [comment]
@retog This is the IP of the bridge (`docker0` by default), so you do have it as soon as the daemon is started.

**Comment by jfrazelle** [comment]
@retog has your issue been solved, seems like there is a way to do it

**Comment by retog** [comment]
@icecrime ok so one have the dockerhost host with

    run --add-host=dockerhost:$( ifconfig docker0 | grep "inet addr" | sed -r "s/.*inet addr:([0-9.]*).*$/\1/")  -ti ubuntu ping -c2 dockerhost

it could certainly be done more elegantly.

**Comment by jfrazelle** [comment]
cool so i guess this can be a proposal for a more elegant solution ;)

**Comment by icecrime** [comment]
After discussions with other maintainers:
- This can be solved client-side without any code change
- If the extra complexity of fetching the bridge ip bothers you, you can launch your daemon with the `--bip` to **fix** the bridge ip

I'll hope you'll understand, and I'm closing this.

**Comment by ndeloof** [comment]
@icecrime `--add-host=dockerhost:$( ifconfig docker0 ...)` will only work if you run it from dockerhost, not from a remote client (typically when using boot2docker from a non-Linux system)

so there's no way so far to start docker container with some host set to point to docker0/host IP 
only alternative is to discover gateway IP from within container, which means software has to be customized to match docker deployment.

**Comment by atd** [comment]
@icecrime I ran into a similar problem using `docker-compose`. I don't know the host IP in advance, but I need it to point to the smtp server listening there :disappointed:

**Comment by atd** [comment]
If it helps for other people: I solved using the external smtp IP

**Comment by pavolloffay** [comment]
@atd +1
