### ISSUE TITLE
docker-proxy set's incorrect process name

### ISSUE THREAD

**Issue by jamercee** [docker/docker#10026]
We use net-snmp to monitor servers. One check we like is to confirm docker is running using the snmpd.conf `proc` directive ( http://www.net-snmp.org/docs/man/snmpd.conf.html). 

Example:

    # /etc/snmp/snmpd.conf
    proc docker  1  1

Net-snmp uses `/proc/PID/status` to read the list of process names running.  It correctly finds `docker` is running, but reports the incorrect count of processes as 2. This is because `docker-proxy` set it's process name to `docker`.

I'm not sure what the rationale is for this (or if this is even intentional) -- but I do not believe `docker-proxy` should change its name.

-----
    # ps ax|grep docker-proxy
    30339 ?        Sl     0:01 docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 8

    # head -1 /proc/30339/status
    Name:   docker

    # docker --version
    Docker version 1.3.2, build 39fa2fa/1.3.2

    # uname -a
    Linux hostname 2.6.32-504.1.3.el6.x86_64 #1 SMP Tue Nov 11 17:57:25 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

    # cat /etc/centos-release
    CentOS release 6.6 (Final)

**Comment by phemmer** [comment]
Actually it doesn't set its name to `docker` at all. If you look at `/proc/$pid/exe`, you'll see that the docker-proxy process is running from the same binary as docker is. If you look at arg0 (from `/proc/$pid/cmdline`), you'll see that the process actually changed its name to `docker-proxy`.

**Comment by jamercee** [comment]
Ah -- got it. I hadn't realized the relationship with `docker`. Actually -- I'm glad you clarified this, because I was going crazy trying to locate the `docker-proxy` cmd.  We'll just stck with checking for a count of two in snmpd, ex:

    # /etc/snmp/snmpd.conf
    proc docker 2 2
