### ISSUE TITLE
Feature to add links to running containers

### ISSUE THREAD

**Issue by sspreitzer** [docker/docker#10022]
I would be very happy to add links to running containers.
For example to cross link mysql containers for master to master replication.

Thank you for all your hard work!

**Comment by thaJeztah** [comment]
A lot of activity is going on for a complete revised networking model (including links) in Docker. Have a look here; https://github.com/docker/docker/issues/9983 

There are some existing feature requests for better links but they have been closed or depend on the new networking proposal (https://github.com/docker/docker/issues/2588, https://github.com/docker/docker/issues/7468, https://github.com/docker/docker/pull/8138)

I think it's best to watch progress on https://github.com/docker/docker/issues/9983.

**Comment by sspreitzer** [comment]
Thank you Sebastiaan. I will watch that Bug.

**Comment by thaJeztah** [comment]
You're welcome! Looking forward to dynamic links myself :smile:

**Comment by gdm85** [comment]
@sspreitzer as stated in @2588, I have added this feature here:

https://github.com/gdm85/docker-fw#two-ways-linking
