### ISSUE TITLE
Allow --insecure-registry at runtime for pull and push 

### ISSUE THREAD

**Issue by justinclayton** [docker/docker#10027]
This is an attempt to revisit the discussion regarding the decision to only add --insecure-registry as a daemon option instead of a runtime one. This had been discussed in #8887, and even though it was closed, the comments have still been coming in regularly expressing frustration at the poor user experience. It seems clear that general consensus is that this should be revisited. Please see #8887 for details and ideas.

**Comment by jonathanvaughn** [comment]
+1

**Comment by CleanCut** [comment]
Yes, pleeeease.

**Comment by cgp** [comment]
+1

**Comment by hlj** [comment]
+1

**Comment by ChiChou** [comment]
:+1:

**Comment by yousq** [comment]
+111111111

**Comment by tangr1** [comment]
+1

**Comment by triplesek** [comment]
+1

**Comment by toddbu** [comment]
+1

**Comment by tiborvass** [comment]
@justinclayton sorry but what does this issue bring compared to #8887 ? For me this is an exact duplicate.

**Comment by justinclayton** [comment]
@tiborvass I was mostly just trying to raise awareness of the several dozen +1s in #8887 that didn't seem to be getting any attention despite the obvious outcry. I'd be happy to continue this discussion over on #10719, but it appears that you've closed that as well.

**Comment by tiborvass** [comment]
@justinclayton I understand the concern, however all those +1s are heard. Doesn't mean we agree.
Like I suggested on the PR, I promise I'm bringing the issue up and have it reconsidered.

**Comment by justinclayton** [comment]
Thanks @tiborvass. While I'm still disappointed at the outcome, it really does help to know that the community is being heard. I'll try to stop being a nuisance. :-)

**Comment by sebadiaz** [comment]
+1

**Comment by olivierbayle** [comment]
+1
