### ISSUE TITLE
Building a Dockerfile that runs curl no longer prints curl progress in real time.  

### ISSUE THREAD

**Issue by mingfang** [docker/docker#10033]
A Dockerfile with the run instruction below no longer prints the curl progress in realtime.
The download still works and will print the status at the end.
```RUN curl -L https://github.com/GoogleCloudPlatform/kubernetes/releases/download/v0.8.0/kubernetes.tar.gz | tar zx"```
This appears to be a problem introduced in 1.4.1.

**Comment by JulianGindi** [comment]
I'm going to look into this...see if I can come up with a fix

**Comment by LK4D4** [comment]
Yeah, this is because we using `logs` instead of `attach` now :/

**Comment by JulianGindi** [comment]
@LK4D4 so this is expected behavior, or something worth fixing?

**Comment by jfrazelle** [comment]
i believe expected, but feel free to tell me why you what the progress bar, lots of people had complaints

**Comment by diffalot** [comment]
here's a quick solution that helped me out when waiting for a long task to finish.

from a script that my Dockerfile RUNs, I'm using `pv` to cat a large sqldump to mysql to prepare the database, so once that step runs, I just `docker attach` to the container that's running that build step, and my progress bar appears.

**Comment by monolar** [comment]
btw, `pv` has a flag `-f, --force              output even if standard error is not a terminal` which actually allows to watch the progress bar without using docker attach (nice to know that though)

**Comment by ErikEngerd** [comment]
There is a very simple fix for this which is to use the unbuffer command. 
Instead of using 'yum install pkg -y' you would use 'unbuffer yum install pkg -y'.

**Comment by diepes** [comment]
i found this looking for a reason i can't see progress in long running curl, inside k8s container.
Would be great if there was a progress option that just print's normal stderr updates every 10 sec. (To prove it is still working after 20min)
