### ISSUE TITLE
Error response from daemon: open  dockerenv: permission denied

### ISSUE THREAD

**Issue by qiyubing** [docker/docker#10035]
[root@vm-tables ~]# docker run -it redis:2.8
2015/01/12 11:12:53 Error response from daemon: open /var/lib/docker/aufs/mnt/16509bd5439a6dea1f5f8cf1a249c06d79c92f9c25364285672078326c501475-init/.dockerenv: permission denied

================
I run docker in vm of centos 6. And have updated the system.

title CentOS (3.10.5-3.el6.x86_64)
	root (hd0,0)
	kernel /vmlinuz-3.10.5-3.el6.x86_64 ro root=UUID=23bbdabe-5769-4d68-920c-68202804f3b3 rd_NO_LUKS rd_NO_LVM LANG=en_US.UTF-8 rd_NO_MD SYSFONT=latarcyrheb-sun16 crashkernel=auto  KEYBOARDTYPE=pc KEYTABLE=us rd_NO_DM rhgb quiet
	initrd /initramfs-3.10.5-3.el6.x86_64.img

**Comment by qiyubing** [comment]
[root@vm-tables ~]# chmod a+r /var/lib/docker/aufs/ -R

**Comment by phemmer** [comment]
See https://github.com/docker/docker/blob/master/docs/sources/installation/centos.md#kernel-support

Centos 6 ships with kernel 2.3.32. Kernel 3.10 is a custom kernel, and unsupported.

**Comment by qiyubing** [comment]
Downloading Packages:
docker-io-1.3.2-2.el6.x86_64.rpm                                                                                          | 4.3 MB     00:01     
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : docker-io-1.3.2-2.el6.x86_64                                                                                                  1/1 
  Verifying  : docker-io-1.3.2-2.el6.x86_64                                                                                                  1/1 

Installed:
  docker-io.x86_64 0:1.3.2-2.el6                                                                                                                 

Complete!

**Comment by qiyubing** [comment]
I've resolved the problem.The method as follow:

edit the file /etc/selinux/config，set two variables:    
SELINUX=disabled 
SELINUXTYPE=targeted
