### ISSUE TITLE
"Read-only file system" setting key "net.ipv4.ip_local_reserved_ports"

### ISSUE THREAD

**Issue by digambar15** [docker/docker#10039]
openstack@b7a6d576a51f devstack]$ sudo sysctl -w net.ipv4.ip_local_reserved_ports=35357,353583
error: "Read-only file system" setting key "net.ipv4.ip_local_reserved_ports"

Cannot reserve the port using sysctl command in the docker container.

**Comment by estesp** [comment]
Reserved ports were not added to per-network namespace sysctl until 2014-05-14 in Linux kernel mainline ( https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/net/ipv4/sysctl_net_ipv4.c?id=122ff243f5f104194750ecbc76d5946dd1eec934 ), which means the earliest Linux kernel release that would have this capability would be in the **3.15.x** range.  Until 15.04, Ubuntu won't have a kernel in the appropriate range, but Fedora 21 is already at/above a 3.16 kernel, I believe, so you potentially might be able to test this with Fedora and be able to write a value to `ip_local_reserved_ports`.

Docker can't do anything about this, as it is the kernel's responsibility to set up the network namespace and initialize the proc filesystem with the list of sysctl params allowed in net namespaces.

**Comment by jfrazelle** [comment]
closing as kernel issue.

**Comment by digambar15** [comment]
Yes, this is a kernel issue, I am not making process without this.
