### ISSUE TITLE
docker ps -a doesn't list container who removal failed

### ISSUE THREAD

**Issue by jarus** [docker/docker#10043]
After I tried to remove a ceph-osd container which creates some btrfs subvolumes in the container file system the removal of the container failed. 

```
core@core-03 ~ $ docker rm ceph-osd
Error response from daemon: Cannot destroy container 35dd46b1fdfb: Driver btrfs failed to remove root filesystem 35dd46b1fdfbaf283a35620748b60cb81929e36fb8afbdac174f92ce94ecd815: Failed to destroy btrfs snapshot: directory not empty
```

There is already a issue related to the removal of btrfs subvolumes: #4100 

Docker also removes the container from ``docker ps -a`` like the container was successfully removed. If you doesn't notice the error message of ``docker rm`` you have no chance to remove the probably big subvolume because you also lose the container id.

**Comment by dove-young** [comment]
Do you have a list of files in <code>/var/lib/docker/container</code>? Does those files still exist in that directory?

**Comment by jfrazelle** [comment]
closing as dup of https://github.com/docker/docker/issues/6746
