### ISSUE TITLE
`docker cp` does not cause a conflict when the archived directory structure replaces a directory with a file or vice versa

### ISSUE THREAD

**Issue by jlhawn** [docker/docker#10040]
Today the [`archive.Unpack()` function explicitly removes and replaces the original resource if they are not both directories.](https://github.com/docker/docker/blob/de9783980be2a7b3ca10eb8183ea5989acbd3e7e/pkg/archive/archive.go#L533)

**Comment by aanm** [comment]
Because of this I accidentally delete a project on my laptop, fortunately I had a backup.

**Comment by jlhawn** [comment]
this should be fixed by #13171

**Comment by aanm** [comment]
@jlhawn Awesome, thank you
