### ISSUE TITLE
docker exec does not properly add process to cgroups

### ISSUE THREAD

**Issue by tonistiigi** [docker/docker#10046]
reproducing:

`docker exec id cat /proc/self/cgroup`

Notice the values changing when you run this for many times.

Looking at the code the issue seems to be that when `nsenter-exec` starts there is a race between the parent adding `nsenter-exec` to appropriate `cgroups` and launching the user process. Only a subset of `cgroups` have been added before the fork(at least in my machine).

Any recommendations for the best way of solving this?

/cc @crosbymichael

```
> docker version
Client version: 1.4.1-dev
Client API version: 1.16
Go version (client): go1.4
Git commit (client): 43c5038
OS/Arch (client): linux/amd64
Server version: 1.4.1-dev
Server API version: 1.16
Go version (server): go1.4
Git commit (server): 43c5038
> docker info
Containers: 7
Images: 19
Storage Driver: aufs
 Root Dir: /home/vagrant/docker-dev-aufs/aufs
 Dirs: 33
Execution Driver: native-0.2
Kernel Version: 3.16.0-25-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 4
Total Memory: 993.4 MiB
Name: docker-vagrant
ID: QFMK:3C7H:CQ7V:ETRJ:ZK6G:Q366:ORM5:XQ4I:7RLY:M7B3:UXE3:LEQK
Debug mode (server): true
Debug mode (client): false
Fds: 30
Goroutines: 37
EventsListeners: 0
Init Path: /home/vagrant/bundles/338/1.4.1-dev/binary/docker
Docker Root Dir:  /home/vagrant/docker-dev-aufs
```

**Comment by crosbymichael** [comment]
I linked this to the libcontainer issue that we are working on

**Comment by dqminh** [comment]
Right, https://github.com/docker/libcontainer/pull/303 will solve this, it will also do more work (i.e. clean up orphan processes etc.. )

There's indeed a race currently when exec a new process and putting it inside the cgroup.  https://github.com/docker/libcontainer/pull/303 will trying to wait for the cgroup setup to be ready before   execing the process (https://github.com/docker/libcontainer/pull/303/files#r22840746)

**Comment by crosbymichael** [comment]
@dqminh do you think we can break up that PR into two parts to get it merged faster.  

1. Wait for exec process to be placed in the parent cgroup
2. Make the subcgroups

**Comment by dqminh** [comment]
@crosbymichael hmm yes, i think it probably make sense to merge that change first, since it fixes this bug immediately and does not really related to the other changes ( although the current behavior will be obsolete if we merge the subcgroup changes ).

I will try to write some integration test based on this issue and cherry-picked the relevant commit in libcontainer to a different PR.
