### ISSUE TITLE
upgrade docker without migration to other machine，how i do？

### ISSUE THREAD

**Issue by oxwangfeng** [docker/docker#10041]
i have a process running in docker， i want to upgrade the docker，but i don‘t want the process is dead，what can i do？

some one like start a upgrade docker on other machine，and running the same process，but i don't like this,because it would affect above application;i want running the process without migration to other machine；

**Comment by jfrazelle** [comment]
You can use restart policies so after upgrade the container is automatically restarted. Because docker controls all the processes of containers the container will need to stop in order to stop docker and upgrade. There is no current way to keep containers running while docker is not.
