### ISSUE TITLE
how i upgrade bootfs？

### ISSUE THREAD

**Issue by oxwangfeng** [docker/docker#10062]
when i upgrade docker，i want to upgrade bootfs for upgrade docker？who i do？

**Comment by xiaods** [comment]
bootfs is concepts, you can't touch it, docker will handle it.

**Comment by jfrazelle** [comment]
I do not understand what you mean by bootfs? is this in the image, is it /var/lib/docker, is it your storagedriver ex. aufs, btrfs, etc
