### ISSUE TITLE
Proposal: Arch dependent Docker file support for arch specific gccgo builds

### ISSUE THREAD

**Issue by ktraghavendra** [docker/docker#10063]
Gccgo build for non x86 arch may require changes to Dockerfile that makes docker build difficult from upstream for all archs.
To enable the build, one idea is to have
1.  Default directory for Dockerfile for the archs that do not need any changes (hack/arch/default)
2. Whichever archs need separate Dockerfile can have hack/arch/<myarch>/Dockerfile
3. Corresponding changes to Makefile to copy the Dockerfile from appropriate place.

Note: [ my early effort was to not move the current Dockerfile and give 
 docker build -t "$(DOCKER_IMAGE)"  <path-to-archspecific-dockerfile>
but above idea failed since built image will fail to have hack/dind wrapper

**Comment by duglin** [comment]
With the new -f option on "docker build" it might make a solution a bit easier

**Comment by ktraghavendra** [comment]
Thanks Doug, looking into that option

**Comment by ktraghavendra** [comment]
Thanks again. -f option made everything very easy now.
 I have the changes now in https://github.com/ktraghavendra/docker/commit/e8107ac885e5fc3be9ba77be004786ee4b7b7ebd .

**Comment by duglin** [comment]
Does your PR reference https://github.com/ktraghavendra/docker/commit/e8107ac885e5fc3be9ba77be004786ee4b7b7ebd ?  I think it still points to the old commit 7ed30bfadb322be6c0e777db3463e1213e1a1494

**Comment by ktraghavendra** [comment]
Hi Doug, Sorry for confusion, but 7ed30bf is the correct commit with updated changes of -f option 

(
https://github.com/ktraghavendra/docker/commit/e8107ac885e5fc3be9ba77be004786ee4b7b7ebd did not have issue number in the log message and it is updated now in https://github.com/ktraghavendra/docker/commit/7ed30bfadb322be6c0e777db3463e1213e1a1494, otherwise patch is same in both the commits )

**Comment by duglin** [comment]
Some of us were chatting about this the other day and one of the issues with having separate Dockerfiles for each arch is that its going to be a real pain to keep the common stuff in-sync between all of them.
Several options were discussed, including:
- some kind of INCLUDE command for Dockerfiles. While this might be a useful feature in general, for this situation it might not be that useful because of the number of arch-specific steps that are intertwined in the Dockerfile would mean a ton of INCLUDE statements all over the place - which felt awkward.
- define some sort of conditional logic (like an IF block) so that we can continue to use a single Dockerfile but have arch-specific sections clearly delineated. 
@brahmaroutu is working on a proposal and should have something soon to share.

**Comment by ktraghavendra** [comment]
Thanks for the update, I think that makes sense.
Thinking loud further,
 where should we have the cgo, gccgo builds ? (i.e., should we have gccgo built conditionally for non -golang archs) in Dockerfile or better to have prebuilt image available with gccgo.

**Comment by hqhq** [comment]
Any update on this?
@duglin If we use some sort of conditional logic, what should it be like for the arch specified base image? Should it be like:
```
if $ARCH = "ppc64" then
FROM ppc64/ubuntu:14.04
else if ...
```
Or should we use the same
`FROM ubuntu:14.04`
and let docker hub detect which arch the request comes from and return the specified image?

**Comment by hqhq** [comment]
@brahmaroutu Is there another proposal I can follow with?

**Comment by duglin** [comment]
@brahmaroutu can give you more information but I believe the current plans are to have unique Dockerfiles per arch.

**Comment by brahmaroutu** [comment]
@hqhq Please see my latest PR #17459 we are using separate Dockerfile for each ARCH.

**Comment by thaJeztah** [comment]
Do we need to keep this issue open? I think general consensus at this moment is to use separate Dockerfiles for different architectures

**Comment by ktraghavendra** [comment]
@thaJeztah Agree that we can close this.

**Comment by thaJeztah** [comment]
Thanks @ktraghavendra !
