### ISSUE TITLE
hosts file of linking container is not updated if linked container is re-created with same name

### ISSUE THREAD

**Issue by fibbs** [docker/docker#10066]
Lets assume the following situation: You have a haproxy container as a frontend that is linked to some backend application containers, serving the apps. If one RESTARTS an application container, it will get a new IP address and this address is automatically updated in the hosts file of the linking (haproxy) container. So far so good!

My problem is that if I have a new application version to deploy, I do a rm -f of the running application container and re-run the container with the same name but a possibly newer version of the image. In this case, the hosts file of the linking (haproxy) container does NOT get updated. 

From my point of view, this should be the case and would not cause any trouble: it is not possible to have several containers with the same name, even stopped or running, so one should consider a re-creation of a container with a name that is "linked" into another container as just the same as re-starting the container without a deletion. Thus, the hosts file of the linking container(s) should be updated as well.

Tested with docker version 1.4.1 and boot2docker on Mac

**Comment by freeella** [comment]
Would be good to have it working the same way in both situations.

**Comment by arnau** [comment]
:+1:  It' would simplify a lot composition.

**Comment by resouer** [comment]
That's not that simple, as Docker daemon setup parent-child relationship when --link is created, so as you are deleting a child, the parent is totally unknown of that. See https://github.com/docker/docker/issues/2733

I suggest you to solve that problem by using fig (or other *outside* tools) according to the issue above.

**Comment by cpuguy83** [comment]
Closing since this is mitigated by the new services API.
Basically you do something like `docker run -d --publish-service <name>`, and the name is published to the network (via dns, with a bridge network using /etc/hosts). When you create a new container publishing the same name, this is pushed out to all other containers.

This functionality can be seen as replacing `--links`.

**Comment by vanga** [comment]
@cpuguy83 which version of the docker will have this feature?
Thanks.

**Comment by cpuguy83** [comment]
@vanga: it's in the experimental branch since 1.7 was released.
