### ISSUE TITLE
Error mounting /dev/mapper something.

### ISSUE THREAD

**Issue by simonvc** [docker/docker#10067]
Stopped a container with Fig. Tried to restart it. Got:

Cannot start container ff7f76...17a4e4: Error getting container ff7f...e827
8017a4e4 from driver devicemapper: mkdir /var/lib/docker/devicemapper/mnt/ff7f76...7a4e4/rootfs: input/output error

Rebooted. now i get this trying to fig up

root@# fig up -d
Recreating iamdev_postgres_1...
Error mounting '/dev/mapper/docker-202:2-359...bc8-init' on '/var/lib/docker/devicemapper/mnt/bab1de5...dbc8-init': invalid argument

# docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8

Linux host.example.com 3.13.0-40-generic #69-Ubuntu SMP Thu Nov 13 17:53:56 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by simonvc** [comment]
This machine its totally borked. Removed /var/lib/docker/* and tried to fig build but it doesnt complete now. Its a VM on Softlayer.

**Comment by nathanleclaire** [comment]
Usually when I have had related issues in the past I have had to manually `umount` the directories it is complaining about in addition to removing `/var/lib/docker`.  Make sure you restart the Docker daemon too.

**Comment by simonvc** [comment]
After reading https://github.com/docker/docker/issues/4036 it appears this was an issue with docker not using AUFS (using device mapper instead.)

Installed aufs:

```
sudo apt-get install linux-image-extra-$(uname -r)
```

Removed docker, removed /var/lib/docker/*

```
apt-get remove lxc-docker
rm -rf /var/lib/docker/*
```

reinstalled docker latest:

```
curl -sSL https://get.docker.com/ubuntu/ | sudo sh
```

**Comment by simonvc** [comment]
Build and launch now works. Closing this ticket.

**Comment by RoelVdP** [comment]
Did you run out of space?

**Comment by simonvc** [comment]
@RoelVdP Nope, it appears that the softlayer VMs don't come with the linux-image-extra kernel modules so docker falls back to using devicemapper instead of aufs.

**Comment by Xat59** [comment]
@RoelVdP personnaly I ran out of space, then I extended my FS . After rebooting the container don't start with :
Error response from daemon: Cannot start container 78e461b4b85e: Error getting container 78e461b4b85ec399e0bc94bbfbce9d291b5b849aebba89e5f64f2ba8df384439 from driver devicemapper: Error mounting '/dev/mapper/docker-253:0-33661794-78e461b4b85ec399e0bc94bbfbce9d291b5b849aebba89e5f64f2ba8df384439' on '/var/lib/docker/devicemapper/mnt/78e461b4b85ec399e0bc94bbfbce9d291b5b849aebba89e5f64f2ba8df384439': invalid argument
Error: failed to start containers: [78e461b4b85e]

I tried to restart docker, reboot or umount /var/lib/docker/devicemapper/mnt/78e461b4b85ec399e0bc94bbfbce9d291b5b849aebba89e5f64f2ba8df384439 , unsuccessfully .

**Comment by RoelVdP** [comment]
@Xat59 :( hope the container was not too important/complex

**Comment by Xat59** [comment]
@RoelVdP it was not but this is not reassuring .
Is this problem unfixeable ?

Thank

**Comment by RoelVdP** [comment]
Hi @Xat59 no idea, sorry

**Comment by thaJeztah** [comment]
@Xat59 see https://github.com/docker/docker/pull/20786 to prevent it from happening

**Comment by zhaoying818** [comment]
I tried to restart docker, reboot or umount ,but it doesn't work.

**Comment by drekar** [comment]
`rm -rf /var/lib/docker/` worked for me.

**Comment by Spechal** [comment]
I ran into this issue on Fedora 25 after stopping my containers and rebooting.  Apparently aufs isn;t supported by Fedora so I installed fuionfs and removed the contents of /var/lib/docker ... after my images downloaded/built ... all is well.
