### ISSUE TITLE
docker container will die about every 30 minutes

### ISSUE THREAD

**Issue by holmes86** [docker/docker#10065]
I found one of containers will die about every 30 minutes. I got logs from container as follow:
lxc-start: cgroup_rmdir: failed to open /sys/fs/cgroup/blkio/lxc/336807cf502eb942728ab9d2fcb421770099dbe9ef66cab8d8fc50c0e36bc25c
lxc-start: cgroup_rmdir: failed to open /sys/fs/cgroup/devices/lxc/336807cf502eb942728ab9d2fcb421770099dbe9ef66cab8d8fc50c0e36bc25c
lxc-start: cgroup_rmdir: failed to open /sys/fs/cgroup/memory/lxc/336807cf502eb942728ab9d2fcb421770099dbe9ef66cab8d8fc50c0e36bc25c

And docker log:

Jan 13 12:08:00 a1-ops-docker240031.hz docker[2586]: [d8de7c22] +job log(die, 336807cf502eb942728ab9d2fcb421770099dbe9ef66cab8d8fc50c0e36bc25c, 5843b2
Jan 13 12:08:00 a1-ops-docker240031.hz docker[2586]: [d8de7c22] -job log(die, 336807cf502eb942728ab9d2fcb421770099dbe9ef66cab8d8fc50c0e36bc25c, 5843b2
Jan 13 12:08:00 a1-ops-docker240031.hz docker[2586]: [d8de7c22] +job release_interface(336807cf502eb942728ab9d2fcb421770099dbe9ef66cab8d8fc50c0e36bc25
Jan 13 12:08:00 a1-ops-docker240031.hz docker[2586]: [d8de7c22] -job release_interface(336807cf502eb942728ab9d2fcb421770099dbe9ef66cab8d8fc50c0e36bc25
Jan 13 12:08:10 a1-ops-docker240031.hz docker[2586]: [error] deviceset.go:782 Warning: error waiting for device 336807cf502eb942728ab9d2fcb421770099db
Jan 13 12:08:20 a1-ops-docker240031.hz docker[2586]: [error] driver.go:141 Warning: error unmounting device 336807cf502eb942728ab9d2fcb421770099dbe9ef

my docker environment info:
docker info
Containers: 42
Images: 208
Storage Driver: devicemapper
 Pool Name: docker-253:0-9570893-pool
 Pool Blocksize: 64 Kb
 Data file: /data/docker/devicemapper/devicemapper/data
 Metadata file: /data/docker/devicemapper/devicemapper/metadata
 Data Space Used: 54516.5 Mb
 Data Space Total: 102400.0 Mb
 Metadata Space Used: 39.5 Mb
 Metadata Space Total: 2048.0 Mb
Execution Driver: lxc-1.0.5
Kernel Version: 3.10.0-123.el7.x86_64
Operating System: CentOS Linux 7 (Core)

The other containers is working in normal. only this one has problem. I don't know what triggered this problem. How to handle this problem?

Thanks

**Comment by jfrazelle** [comment]
we recommend lxc-1.0.7, also have you tried with the natic execdriver

**Comment by holmes86** [comment]
OK. I will try  lxc-1.0.7, thanks.
I must be use some lxc feature, so I can not change to execdriver.

**Comment by jfrazelle** [comment]
let us know how it goes

**Comment by jfrazelle** [comment]
@holmes86 how did it go

**Comment by jfrazelle** [comment]
closing as stale, @holmes86 let me know if you are still seeing on 1.0.7

**Comment by antz29** [comment]
@jfrazelle I'm getting this with Docker 1.5 and the native-0.2 driver. I'm on CoreOS alpha.

```
Storage Driver: overlay
Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 3.19.3
Operating System: CoreOS 653.0.0
CPUs: 1
Total Memory: 2.943 GiB
Name: core-01
```

```
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.3.3
Git commit (client): a8a31ef-dirty
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.3.3
Git commit (server): a8a31ef-dirty
```
