### ISSUE TITLE
Tests are hanging if failing

### ISSUE THREAD

**Issue by LK4D4** [docker/docker#10074]
In #10014 was returned behavior which was hacked in #5890
We need to figure out how to fix it right way
ping @tianon and all bash-gods

**Comment by jfrazelle** [comment]
ughhhhhhh

**Comment by jfrazelle** [comment]
this makes sense then for the docker-py stuff

**Comment by tianon** [comment]
:toilet: EPIPHANY!1!one!!

I KNOW WHAT'S HAPPENING HERE!eleven!!

**Comment by jfrazelle** [comment]
yayyyyyyy!
