### ISSUE TITLE
Add support for user defined script to generate labels.

### ISSUE THREAD

**Issue by timothysc** [docker/docker#10083]
The idea here is piped|configs.

--labels=/usr/bin/generate_json_or_yml_nvp_thunk.sh |

This is nice because different folks could create their own script files to detect:

cluster/rack awareness
gpu capabilities
over provisioning mechanics ...

discussion can be found here: https://github.com/docker/swarm/issues/239

**Comment by tiborvass** [comment]
@timothysc Why not just do `docker -d $(generate_labels)` ?

I must say I dislike the weird `=|` syntax, that would be yet another thing to support.

**Comment by timothysc** [comment]
The syntax is pretty well defined, however I suppose you could also use `strike_exec`.  

It looks like you were implying variable substation above, where enabling execution output could eliminate (1:N) steps necessary to start the daemon, and easing automation for those who tend to enjoy concise packed statements.

FWIW this is not a new idea, and exists in several clustering & batch systems.

**Comment by tianon** [comment]
Can you provide a few examples of other popular systems that support this kind of thing (preferably with links to documentation that details how to use it and why it's supported)?  I'm with @tiborvass here; I don't see any benefit you can't get with the shell already today without any code changes.

**Comment by timothysc** [comment]
@vieux @tiborvass @tianon 

Most common reference is here: http://research.cs.wisc.edu/htcondor/manual/v8.3/3_3Configuration.html#SECTION00431400000000000000 

IIRC it was taken from other batch systems.  

The primary benefit is automation in large, heterogeneous, multi-department environments, labels become a mechanism for discovery, constraint matching, accounting, and limits.  

If you were to leverage envs, it can become quite messy if our set is large, and potentially non-conformant in the case where labels enable their own expression syntax, because then you need to "escape all the strings".

If docker is to provide facilities to enable higher order systems to leverage, then this would be useful.

**Comment by duglin** [comment]
@timothysc I'm not sure you're following what the other folks are saying.  You want to run a program and use the output as the input to the --label option.  They're saying you can do that via the shell today. The disagreement is just about the syntax, $(exe_name) vs exe_name |
We don't need to have docker re-invent what the shell already supports and people are used to.
I think we can close this.

**Comment by cpuguy83** [comment]
Closing since I think we all agree it's better to use shell substitution to handle this rather than building this handling in docker itself.
Thanks for the proposal!

**Comment by thaJeztah** [comment]
You can also use a `--labels-file` if that's more convenient.
