### ISSUE TITLE
rename to invalid name is losing its old name

### ISSUE THREAD

**Issue by crquan** [docker/docker#10081]
docker rename to an invalid name is losing its old name, I think the backend should check new name's validity before making any changes

```
$ docker ps
CONTAINER ID        IMAGE           COMMAND     CREATED  STATUS   PORTS    NAMES
3df7e2d463f9        debian   "/bin/bash"  15 minutes ago  Up 15 minutes     myname
$ docker rename myname new:invalid
Error response from daemon: Error when allocating new name: Invalid container
  name (new:invalid), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed
FATA[0000] Error: failed to rename container named myname 
$ docker rename myname newok
Error response from daemon: No such container: myname
FATA[0000] Error: failed to rename container named myname 
$ docker ps
CONTAINER ID        IMAGE           COMMAND     CREATED  STATUS   PORTS    NAMES
3df7e2d463f9        debian   "/bin/bash"  15 minutes ago  Up 15 minutes
$ docker rename 3df7e2d463f9 newokname
$ docker ps
CONTAINER ID        IMAGE           COMMAND     CREATED  STATUS   PORTS    NAMES
3df7e2d463f9        debian   "/bin/bash"  15 minutes ago  Up 15 minutes     newokname
```

**Comment by jfrazelle** [comment]
Thanks for testing and using master!! I have submitted a patch to fix this bug

**Comment by crquan** [comment]
@jfrazelle daemon.reserveName already has validation by calling validContainerNamePattern.MatchString; so your solution will call this MatchString twice in this rename path, that might be just a few extra cpu cycles, but is there any problem if we call daemon.reserveName first? then to let daemon.containerGraph.Delete old_name

**Comment by jfrazelle** [comment]
I thought of that too but I think it will cause problems, I can try it out

**Comment by jfrazelle** [comment]
Seems to be fine I guess since we are locking the container, I updated,
thanks!

**Comment by brahmaroutu** [comment]
@jfrazelle thanks, sorry about this.

**Comment by crquan** [comment]
I still think the new_name assignment need to be moved before daemon.containerGraph.Delete, if the containerGraph database has problems, it's ok to return an error, but should not affect the new_name assignment; see my commit 4ee72c7

```go
container.Name = new_name
```

**Comment by jfrazelle** [comment]
That would be a problem though if the name is already taken.

**Comment by jfrazelle** [comment]
jk ignore that last comment, I didn't see you were setting it after

**Comment by jfrazelle** [comment]
ok I updated, but if the graph fails, there is going to be a lot more
issues then this ;)
