### ISSUE TITLE
Device mapper "resource busy" on CentOS 6.6

### ISSUE THREAD

**Issue by zopyx** [docker/docker#10090]
Gartner is right. Docker is completely unusable in production. Best proof:

Trying to start a container once again fails

[ajung@dev1~]$ docker start c64662f04dde
Error response from daemon: Cannot start container c64662f04dde: Error getting container c64662f04ddeaed6c92ae28594061cc13f335ed59bab2b6de62e53c5d27af934 from driver devicemapper: Error mounting '/dev/mapper/docker-252:1-6602807-c64662f04ddeaed6c92ae28594061cc13f335ed59bab2b6de62e53c5d27af934' on '/var/lib/docker/devicemapper/mnt/c64662f04ddeaed6c92ae28594061cc13f335ed59bab2b6de62e53c5d27af934': device or resource busy
FATA[0013] Error: failed to start one or more containers 

Restarting the docker daemon does not help.

Trying to remove /var/lib/docker also does not work

[ajung@dev1~]$ sudo rm -fr /var/lib/docker/
rm: cannot remove `/var/lib/docker/devicemapper/mnt/6e17fadd1a6bf04f6d6b0309242b520c205acaf509f939aecb83bf46dcabeb9e': Device or resource busy
rm: cannot remove `/var/lib/docker/devicemapper/mnt/921e82585886e02e24a16fc379b13671d98154230f659035eaeecea7bbf902ee': Device or resource busy
rm: cannot remove `/var/lib/docker/devicemapper/mnt/c64662f04ddeaed6c92ae28594061cc13f335ed59bab2b6de62e53c5d27af934': Device or resource busy
rm: cannot remove `/var/lib/docker/devicemapper/mnt/5f3d4aa114eb51f4f5be93b8a3c6142e06b773e38fd546c2208946777a00e387': Device or resource busy
rm: cannot remove `/var/lib/docker/devicemapper/mnt/f375563cf9ca10560e11b63c1a81b2756e8676275e290ef27e543111c01a6d03': Device or resource busy
rm: cannot remove `/var/lib/docker/devicemapper/mnt/c17bda17697f524e966de37a739fd71a0e0aabbfb39332b9e3cd8624f6b2f8d2': Device or resource busy

'lsof' does not display any processes locking  the devicemapper.

Only a full reboot of the box is working.

Do you call this a stable infrastructure?

[ajung@dev1~]$ docker --version
Docker version 1.4.1, build 5bc2ff8

Distro is CentOS 6.6,

[ajung@dev1 ~]$ uname -r
2.6.32-504.3.3.el6.x86_64

**Comment by shykes** [comment]
Hi @zopyx this seems to be an issue specific to the devicemapper storage driver.

I'm copying @vbatts @unclejack @alexlarsson who know more on the topic.

**Comment by jfrazelle** [comment]
we [suggest using at least a 3.8 kernel](http://docs.docker.com/installation/binaries/) especially if you are going to be using docker in production.

**Comment by shykes** [comment]
@jfrazelle is right, your version of the kernel is not supported.

Have a nice day and try to be less of an asshole next time.

**Comment by zopyx** [comment]
What a tarded reply. Provide accurate information about aupported distros and kernels. State clearly that CentOS 6 is unsupported instead of letting people fail with Docker day by day. The ignorant asshole atttitude is on your side, tinkerers.

**Comment by unclejack** [comment]
@zopyx I'm sorry you're having problems with Docker and devicemapper. Those two problems are known and we're working on fixing them.

RHEL and CentOS are the only exceptions to the `3.8 is the absolute minimum for starting Docker rule`.

I'll provide more information in a few hours.

**Comment by tiborvass** [comment]
@zopyx We're happy to help, and we can make mistakes as well, but you started this issue in an attacking tone. Please refrain from continuing that, as it is unproductive and doesn't help solving the issue better/quicker. Thanks for your understanding

**Comment by vbatts** [comment]
@zopyx the "device or resource busy" has a number of things that can trigger it unfortunately. some of which are outside of docker itself. Please check out http://blog.hashbangbash.com/2014/11/docker-devicemapper-fix-for-device-or-resource-busy-ebusy/ and see if setting the docker daemon in a private mount namespace mitigates the issue for you.

Also, since you began `rm -r` the directory when it's in this state, you'll likely have to `umount /var/lib/docker/devicemapper/mnt/c64662f04ddeaed6c92ae28594061cc13f335ed59bab2b6de62e53c5d27af934` etc, and `umount /var/lib/docker/devicemapper` too, so you can rm

**Comment by zopyx** [comment]
The documentation

https://docs.docker.com/installation/centos/

 clearly states

To run Docker, you will need CentOS6 <http://www.centos.org/> or higher,
with a kernel version 2.6.32-431 or higher as this has specific kernel
fixes to allow Docker to run.

Please update your docs accordingly and say clear: CentOS 6.X is
unsupported. There is currently no way to run Docker on CentOS 6.X in a
reliable way.


2015-01-14 18:48 GMT+01:00 Vincent Batts <notifications@github.com>:

**Comment by vbatts** [comment]
@zopyx you've found the docs, though this issue is not exclusive to Centos6... see my prior comment.

**Comment by vbatts** [comment]
Closing this issue per our tracker for EBUSY related devicemapper errors https://github.com/docker/docker/issues/5684#issuecomment-69052334

**Comment by hdeadman** [comment]
For future people that come across this issue, I thought I would leave link to the documentation in Docker that explains why Puppet, Chef, etc can't update /etc/hosts, /etc/resolv.conf, & /etc/hostname in a container (at least not if they are doing an atomic rename that they would normally do). 

-- https://docs.docker.com/articles/networking/#dns

That documentation explains how those three files are special overlays managed by Docker as part of its networking support. Essentially your provisioning scripts ought to leave them alone and you can pass command-line arguments to docker to influence their contents. From the docs - 
> ... you should leave the files themselves alone and use the following Docker options instead.
