### ISSUE TITLE
docker attach hangs setting terminal state when attaching to container

### ISSUE THREAD

**Issue by acbodine** [docker/docker#10094]
Let's say I have a container such that:
```
docker@boot2docker:~$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
3a73e17af236        ubuntu:14.04        "/bin/bash"         2 seconds ago       Up 1 seconds                            modest_mcclintock
```

Then I attach to it:
```
docker@boot2docker:~$ docker attach modest_mcclintock

```

I press any key and I see:
```
docker@boot2docker:~$ docker attach modest_mcclintock
root@3a73e17af236:/# 
root@3a73e17af236:/# 
```

Shouldn't the first `root@3a73e17af236:/#` prompt be displayed when `docker attach` is run?

I can verify this isn't a `boot2docker` problem as I have seen similar behavior on Ubuntu 14.04

```
docker@boot2docker:~$ uname -a
Linux boot2docker 3.16.7-tinycore64 #1 SMP Tue Dec 16 23:03:39 UTC 2014 x86_64 GNU/Linux
```
```
docker@boot2docker:~$ docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
```

```
docker@boot2docker:~$ docker -D info
Containers: 1
Images: 53
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Dirs: 55
Execution Driver: native-0.2
Kernel Version: 3.16.7-tinycore64
Operating System: Boot2Docker 1.4.1 (TCL 5.4); master : 86f7ec8 - Tue Dec 16 23:11:29 UTC 2014
CPUs: 8
Total Memory: 1.961 GiB
Name: boot2docker
ID: CMKY:4CQL:L2XD:XDLJ:NFT3:R6HT:FVDW:JIJG:QFUO:IIQO:JK6I:7SAR
Debug mode (server): true
Debug mode (client): true
Fds: 11
Goroutines: 11
EventsListeners: 0
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
```

**Comment by acbodine** [comment]
I'm happy to submit a PR for this fix as well as it follows the workflow I looked into for #9860, if it is determined to be an issue.

**Comment by jfrazelle** [comment]
can you try on master? you can download binaries from master.dockerproject.com

**Comment by acbodine** [comment]
From the tip of master `7d80fd6ca6f26f37b5c19d95b53c7fb4faa22bd1` I'm seeing the same behavior

**Comment by jfrazelle** [comment]
why are you attaching to bash? I think that is intentional behavior if you want to execute more things inside the container use docker exec

**Comment by jfrazelle** [comment]
attach seems to be working fine for me on master with irssi and mutt

**Comment by acbodine** [comment]
ha - so this example was/is something I have been using to test other issues with being a long running process that won't die on me. Aside from that, you are right, it's not very practical. I noticed this behavior and wasn't sure if it was correct or not. It seems like when attaching the container's stdout isn't flushed to the cli until the cli provides data on the container's stdin in this case.

**Comment by jfrazelle** [comment]
so wdyt is this still an issue, sorry im confused :)

**Comment by jfrazelle** [comment]
sorry and hit wrong button

**Comment by jfrazelle** [comment]
ping @acbodine

**Comment by acbodine** [comment]
I meant to close this. Whoops.

**Comment by jfrazelle** [comment]
ah cool thanks!

**Comment by nabobnagari** [comment]
Docker Cant attach  Container where It has tomcat which i was running, For some reason if i pressed ctrl + c its Stopping  container In order to come out of the prompt

Observing : Docker 1.12.2
