### ISSUE TITLE
Docker gives out IP addresses already in use

### ISSUE THREAD

**Issue by damm** [docker/docker#10096]
Hi,

I am trying to get my Docker containers (in a datacenter) to be on a specific link and have it hand out IP addresses that are not in use. So docker is running like docker -d -b=br0

The subnets I have tried are below:

10.0.0.1/24
10.1.10.1/24
172.16.0.1/24

There is nothing special in my configuration my forward delay is 1 on the bridge (I used to set 9).

    Switches Involved.
        Cisco SG-300 24 port
        Cisco SG-200 24 port

Rapid STP is enabled so basically what happens is it flaps the ip between the ports assuming it. This makes it impossible to docker build on 2 servers at once (apt-get update usually fails)

I don't care what IP is given out; I just cannot be an IP address already in use.

**Comment by damm** [comment]
P.S. I opened this because #6561 was closed.  There was no traction on the ticket as apparently no one gives a crap that Docker is giving out IP Addresses that may be in use.

BTW, My apologizes if I seem irratated; I just find how #6561 was closed to be rude; and how the ticket was ignored for so long maybe a new ticket is required.

**Comment by LK4D4** [comment]
@damm Yup, not a problem. You know you can specify `--fixed-cidr` for docker to specify subnet which should be used for allocations.

**Comment by damm** [comment]
Oh I know there's work 'arounds' by configuring a bridge's CIDR to not collide with another hosts; but I still think we should check the IP is available for allocating it.

I've had false starts on containers (even with the default 172.17.0.0 subnet) because the IP was in use and Docker was unaware (typically an issue with the sqlite database being out of sync). 

> It's a bad user experience

**Comment by MalteJ** [comment]
I do not like the idea to have multiple unsynchronized databases that hold potentially conflicting IP address information.
I would prefer to have a central DHCP service or a distributed IP address database.
Let's see what https://github.com/docker/docker/issues/9983 brings.

**Comment by damm** [comment]
I don't think this is a matter of maintaining an 'IP Database'.  

Take for example how DHCP works; http://en.wikipedia.org/wiki/Dynamic_Host_Configuration_Protocol#Operation

Right now if you ```docker -b=br0 -d``` it will use the next ip available (using the cidr off of br0).  If that's already in use (configured locally; etc) your first container will fail to start (or it will takeover another device)
 
P.S. I think it would be really great if we stopped trying to implement DHCP without the safeguards DHCP provides (so a client can backdown from assuming an IP in use that DHCP is unaware of it being allocated) 

Lastly, if we tested the IP was in use; and rejected it and then handed out the next available I am sure _weave_ and _flannel_ would greatly benefit it.

Having to allocate unique subnets per Docker Host just to avoid this issue is quite a bummer.

**Comment by sitamet** [comment]
# I'm experiencing IP conflicts: two containers with same IP!

I'm running docker with default options:

```
docker info
Containers: 391
Images: 586
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1368
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-74-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 8
Total Memory: 62.89 GiB
```

1st docker inspect network settings:
```
    "NetworkSettings": {
        "Bridge": "",
        "SandboxID": "325d461067932cb180061cea19a9fd55f936433a8ed9bcdbff80880213fdd818",
        "HairpinMode": false,
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "Ports": {
            "3306/tcp": null
        },
        "SandboxKey": "/var/run/docker/netns/325d46106793",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null,
        "EndpointID": "4db1346b0504e49906fb0f9b5ecae4080fee2fbbdd8ac3560c77358e70e4dd72",
        "Gateway": "172.17.0.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "172.17.0.126",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "MacAddress": "02:42:ac:11:00:7e",
        "Networks": {
            "bridge": {
                "EndpointID": "4db1346b0504e49906fb0f9b5ecae4080fee2fbbdd8ac3560c77358e70e4dd72",
                "Gateway": "172.17.0.1",
                "IPAddress": "172.17.0.126",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "MacAddress": "02:42:ac:11:00:7e"
            }
        }
    }
```

second container:
```
    "NetworkSettings": {
        "Bridge": "",
        "SandboxID": "5acd6b64b7b97939f17bcf407be2bfb112e18cb0791ef2363044760c23fc0025",
        "HairpinMode": false,
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "Ports": {
            "443/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "443"
                }
            ],
            "80/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "80"
                }
            ]
        },
        "SandboxKey": "/var/run/docker/netns/5acd6b64b7b9",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null,
        "EndpointID": "2cace3c896fb303ef135e1e8cb6a99615e4f233e52896f5952c84fcf5d8fd9c8",
        "Gateway": "172.17.0.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "172.17.0.126",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "MacAddress": "02:42:ac:11:00:7e",
        "Networks": {
            "bridge": {
                "EndpointID": "2cace3c896fb303ef135e1e8cb6a99615e4f233e52896f5952c84fcf5d8fd9c8",
                "Gateway": "172.17.0.1",
                "IPAddress": "172.17.0.126",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "MacAddress": "02:42:ac:11:00:7e"
            }
        }
    }
```

**Comment by MalteJ** [comment]
@sitamet
Have you set the MAC addresses manually?

**Comment by thaJeztah** [comment]
@sitamet  I think that may be another issue, see https://github.com/docker/docker/issues/19086 and https://github.com/docker/docker/issues/18535#issuecomment-164494430, and will be resolved in 1.10

**Comment by sitamet** [comment]
@MalteJ 
Have you set the MAC addresses manually? ---> NOT

**Comment by sitamet** [comment]
Thanks @thaJeztah 
While waiting for 1.10 I'll try the workaround (a network db rebuild) @aboch comments here [18535#](https://github.com/docker/docker/issues/18535#issuecomment-164494430)

**Comment by LK4D4** [comment]
I think it's fixed now. Feel free to open new issues.

**Comment by damm** [comment]
The problem is (imo) that Docker defines it's networking components (and at the time) all the data was contained in a sqlite3 database.  Docker has removed that old sqlite3 database but unless you basically ping an ip to see if it's up (arping) this issue will always exist.

Shame as I wanted to bridge my networking (for the docker containers) over a private network so my containers (and non containers) could easily coexist.

Good luck and I hope this issue never comes back.
