### ISSUE TITLE
Quirk in CMD array form and cache invalidation

### ISSUE THREAD

**Issue by anentropic** [docker/docker#10097]
I had the following faulty line in my Dockerfile:

    CMD ["service postfix", "start"]

when I built the image I got this output:

```
...
Step 8 : CMD service postfix start
 ---> Running in 63d0a862b035
 ---> dd01b8e6bef6
```

then running the image I get the error, due to my mistake:

```
exec: "service postfix": executable file not found in $PATH2015/01/14 19:48:12 Error response from daemon: Cannot start container 04e2c942e31f583e36f1bcc5b8a88d608d08786a63454ea276612e4e5785f978: exec: "service postfix": executable file not found in $PATH
```

OK so far... but then I fix the mistake in my Dockerfile:

    CMD ["service", "postfix", "start"]

and build again:

```
...
Step 8 : CMD service postfix start
 ---> Using cache
 ---> dd01b8e6bef6
```

I didn't notice until I ran the image and got the error still... but basically `docker build` appears to have normalised the two directives `CMD ["service postfix", "start"]` and `CMD ["service", "postfix", "start"]` to the same value `CMD service postfix start`  ...resulting in reuse of cached layer

I had to do a `--no-cache` build to get it to work

**Comment by tiborvass** [comment]
@anentropic Which version of docker are you using?

**Comment by duglin** [comment]
I believe this is because the cache check is just a strcat of the args and then a strcmp against previous runs.  I'll try to work on/investigate this, should be easy but will blow away all existing caches with RUNs

**Comment by duglin** [comment]
Opened PR #10123 to address this
