### ISSUE TITLE
Could not remove images with no tag.

### ISSUE THREAD

**Issue by is-yangchen** [docker/docker#10115]
when a use the command " docker rmi `docker images -a -q` " to remove all images.
Some images are removed, while others which with no tag could not be removed.

log like below:
Error response from daemon: No such id: 329fc260da4b17f4eb7523ebcd10b17630899e93d59de4f22be5193042e97bc4
Error response from daemon: Conflict, f3e1c04b4463 wasn't deleted
Error response from daemon: Conflict, 60e86e66a09f wasn't deleted
Error response from daemon: Conflict, 60a420f265dd wasn't deleted

how could slove this?

**Comment by jfrazelle** [comment]
this was fixed with https://github.com/docker/docker/pull/9204 in 1.4

**Comment by is-yangchen** [comment]
Thanks！
