### ISSUE TITLE
Agent forwarding SSH_AUTH_SOCK not working

### ISSUE THREAD

**Issue by ronniestevens** [docker/docker#10116]
I am not able to get my ssh-agent forwarding to work. I'm perfectly able to assign my $SSH_AUTH_SOCK to a tmp socket-file, and set the apps SSH_AUTH_SOCK to this file. Ssh from within the app will not work however. 
Running lxc-docker-1.4.1 on ubuntu14.10 on Macbookpro6,2 and Imac14,2..

**Comment by cpuguy83** [comment]
Hello,

This isn't really a support forum.
Please see:
1. forums.docker.com
2. #docker-user mailing list
3. #docker on freenode.
4. https://gist.github.com/d11wtq/8699521 <-- various commands to use for forwarding the auth socket.
