### ISSUE TITLE
TTY error  when launching container from systemd

### ISSUE THREAD

**Issue by crosbymichael** [docker/docker#10121]
This patch has caused problems in my use case. I have a CoreOS cluster that I use for testing. I launch multiple docker containers using Fleet. Then I use the Docker API to send commands and read the output. https://docs.docker.com/reference/api/docker_remote_api_v1.14/#attach-to-a-container

This used to work fine, but now in Docker 1.4.1 the fleet service fails with the error `cannot enable tty mode on non tty input`. Below is an example service file that illustrates the issue.

```
[Unit]
Description=TestNode1

[Service]
TimeoutStartSec=5m
EnvironmentFile=/etc/environment
ExecStart=/usr/bin/docker run -it --name test1 --rm ubuntu:14.04 /bin/bash
ExecStop=/usr/bin/docker kill test1
```

The docker run command works fine if I run it manually, the problem is when trying to use Fleet. I am assuming systemd doesn't have a TTY or something and trips this error message.

**Comment by crosbymichael** [comment]
ref @jeffbaier

**Comment by jeffbaier** [comment]
> Sorry to hear that @jeffbaier. Can you tell us more about the use case? I don't really understand the meaning of launching /bin/bash without a tty.

I want to launch a container with a shell and then use the Docker API to attach to it's stdin and stdout. But I also want to launch a bunch of those containers across a CoreOS cluster using fleet. 

Is this just a problem with starting the containers using systemd? Would I get the same error if I was using swarm? Or if I just made an API call directly?

**Comment by cpuguy83** [comment]
Working around this, adding `StandardInput=tty-force` seems to work.

**Comment by cpuguy83** [comment]
Also, for this use case, why not instead use sshd (in a container) and connect directly to that?

**Comment by jeffbaier** [comment]
> Also, for this use case, why not instead use sshd (in a container) and connect directly to that?

I like attaching with the Docker API because it provides 'out of band' access. I can run a container with no networking and still access the shell.

**Comment by cpuguy83** [comment]
@jeffbaier Does the above work-around work for you?
It should go into your service section.

**Comment by jeffbaier** [comment]
@cpuguy83  Yes the work-around works, thank you very much. 

```
[Unit]
Description=TestNode1

[Service]
TimeoutStartSec=5m
StandardInput=tty-force
EnvironmentFile=/etc/environment
ExecStart=/usr/bin/docker run -it --name test1 --rm ubuntu:14.04 /bin/bash
ExecStop=/usr/bin/docker kill test1
```

**Comment by icecrime** [comment]
Nice @cpuguy83 :+1:

Does it mean we can close this issue? Do we have to suggest a documentation update somewhere?

**Comment by jeffbaier** [comment]
Yes I believe you can close this issue. This was really more of a CoreOS/fleet/systemd problem. It's possible users migrating to Docker 1.4.1 could get bit by it, since it worked before even if it wasn't configured correctly.

**Comment by phemmer** [comment]
Another solution which to me seems more appropriate is

    ExecStart=/bin/sh -c "exec docker wait $(docker run -itd --name test1 ubuntu:14.04 /bin/bash)"
    ExecStop=/usr/bin/docker rm -fv test1
