### ISSUE TITLE
Docker exec stderr output is not redirectable

### ISSUE THREAD

**Issue by RoelVdP** [docker/docker#10132]
```
$ sudo rm -f /tmp/tst1
$ sudo docker run -t --cidfile /tmp/tst1 centos:centos7 /bin/sleep 10000 & 2>&1 > out1  # <--- -t or no -t, same result
[3] 9919
$ sudo docker exec `cat /tmp/tst1` ls notexist.txt 2>&1 > out2
ls: cannot access notexist.txt: No such file or directory   # <--- this stderr output should not be here, but in out2 (or out1 ?)
$ ls -l out[12]
-rw-rw-r--. 1 roel roel 0 Jan 16 16:08 out1    # 0 bytes
-rw-rw-r--. 1 roel roel 0 Jan 16 16:08 out2
$ sudo docker exec `cat /tmp/tst1` ls > out3
$ ls -l out3
-rw-rw-r--. 1 roel roel 99 Jan 16 16:08 out3   # <--- contains ls of docker container, so stdout output redirection works
```

Also interesting (and potentially another bug) is this;

```
$ sudo rm -f /tmp/tst1
$ sudo docker run -i --cidfile /tmp/tst1 centos:centos7 /bin/sleep 10000 & 2>&1 > out1  # <--- notice the -i
[2] 10413
$ sudo docker exec `cat /tmp/tst1` ls notexist.txt 2>&1 > out2
ls: cannot access notexist.txt: No such file or directory

[2]+  Stopped                 sudo docker run -i --cidfile /tmp/tst1 centos:centos7 /bin/sleep 10000
   # <--- why did the container stop?
```

Tested on Docker version 1.4.1, build 5bc2ff8 | Centos 7.0.1406 x64

**Comment by phemmer** [comment]
You have an error in your shell syntax. You want `>out2 2>&1`, not `2>&1 >out2`.
Your current syntax is sending STDERR to STDOUT, and then sending STDOUT to `out2`, leaving STDERR pointed at the original STDOUT.

**Comment by RoelVdP** [comment]
$ ls nosuchfile 2>&1 >out
ls: cannot access nosuchfile: No such file or directory
$ cat out
$ ls nosuchfile >out 2>&1
$ cat out
ls: cannot access nosuchfile: No such file or directory

Doh! @phemmer Nice one/Thanks.

**Comment by RoelVdP** [comment]
So that resolved the first issue :)  The second is still a mystery;

[roel@localhost ~]$ sudo rm -f /tmp/tst1
[roel@localhost ~]$ sudo docker run -i --cidfile /tmp/tst1 centos:centos7 /bin/sleep 10000 & >out1 2>&1
[1] 17549
[roel@localhost ~]$ sudo docker exec `cat /tmp/tst1` ls notexist.txt >out2 2>&1

[1]+  Stopped                 sudo docker run -i --cidfile /tmp/tst1 centos:centos7 /bin/sleep 10000
[roel@localhost ~]$ cat out1
[roel@localhost ~]$ cat out2
ls: cannot access notexist.txt: No such file or directory

Why does the container stop?

**Comment by jfrazelle** [comment]
I think the > is resolving on your host not in the container

**Comment by jfrazelle** [comment]
if you want to run sleep as a detached process in the background use docker run -d, for detachted, using & is not going to work in this way because when PID 1 in a container dies, the container itself dies.

**Comment by jfrazelle** [comment]
Also this isn't really a support forum.
Please see:
1. forums.docker.com
2. #docker-user mailing list
3. #docker on freenode.

**Comment by RoelVdP** [comment]
@jfrazelle - I logged it here as I originally considered both issues a bug. For the second issue; is PID1 in the container not the sleep itself? If so, the issue still looks like a bug and the container should not die?

**Comment by RoelVdP** [comment]
@jfrazelle ?

**Comment by jfrazelle** [comment]
I reopened sorry about that

**Comment by RoelVdP** [comment]
No worries/thanks

**Comment by phemmer** [comment]
This one isn't a bug either. When you use `docker run -i`, that tells docker it needs to connect STDIN on the local end, to STDIN of the process in the container. However you're backgrounding the local client. Backgrounded programs cannot read STDIN. If they try to do so, they get sent a SIGSTOP. It's not the container that's stopping, it's your local client. "Stop" here does not mean "dead" either. You can get it back by using `fg`.

**Comment by RoelVdP** [comment]
Okay, I need to play around with this some more. Another project ongoing now. I can look at this later, will close ftm and re-open if I get stuck. 

@phemmer is there another way to do what I am doing? I want to be able to exec multiple commands and run the sleep just so the container stays active. This is for a packaging testing (on various OS'es) setup.

**Comment by cpuguy83** [comment]
@RoelVdP If you need to run multiple commands, can you fire up multiple execs instead of pushing it all into one?

**Comment by phemmer** [comment]
@RoelVdP It depends what exactly you're trying to do. If your container doesn't need to be interactive, start it with `-d`, not `-i`. This will start it, and then give you the container ID without retaining control of your TTY.

**Comment by RoelVdP** [comment]
@cpuguy83  Yes - am splitting all comments into single execs.
@phemmer I tried without -i but certain commands don't like it.

All I would like to is have a simple container to which I can sent simple arbitrary commands (like yum install, mysql connect etc. etc.) and capture the output of the same in a reliable fashion. Can this be done? So far the sleep (as main process) + exec's works best, but capturing the output is tricky.

**Comment by jfrazelle** [comment]
Hey so I think this is just a with understanding with how to use docker. For docker user support we recommend #docker on IRC freenode or https://groups.google.com/forum/#!forum/docker-user or forums.docker.com
