### ISSUE TITLE
API: image inspection doesn't return tags

### ISSUE THREAD

**Issue by baptistedonaux** [docker/docker#10139]
I use the Docker API, and when I run this request, the tags doesn't return.

```
GET /images/{id}/json
```

This information is given when I list all images.

What's the best practices to get image's tags information ?

**Comment by HuKeping** [comment]
try this
http://serverip:port/v1.16/images/json?filter=ubuntu

**Comment by baptistedonaux** [comment]
This solution works, but not sure that response give only one image.

Future, not interesting to add a similar feature ?

**Comment by VictorDenisov** [comment]
#dibs

**Comment by nhsiehgit** [comment]
Hi VictorDenisov,
Please remember to add a `closes` or `fixes` keyword once youve submitted your PR to help tracking fixes easier. Thanks!

**Comment by draghuram** [comment]
BTW, I found that in addition to "tags", there are two more fields that are missing from `GET /images/{id}/json` response. They are "RepoDigests" and "Labels". Would there be an interest to add them as well?
