### ISSUE TITLE
api: using  exec-create 

### ISSUE THREAD

**Issue by Boran** [docker/docker#10137]
HI,

I'd like to do the equivalent of the following via the API:
docker exec mycontainer  sh -c 'ls /var/www/html'

So found http://docs.docker.com/reference/api/docker_remote_api_v1.16/#exec-create and tried:
curl -X POST -H "Content-Type: application/json"  http://127.0.0.1:2375/containers/mycontainer/exec \
 -d '{ "AttachStdin":false,"AttachStdout":true,"AttachStderr":true, "Tty":false, "Cmd":["ls /var/www/html"] }'

but this gives back:
{"Id":"10ea294c854e75b5957e198e0b33c0ec7a9fe5e6742b739ed081c6f8081123d5"}

What next, is one then supposed to do a start? e.g.
curl -X POST -H "Content-Type: application/json"  http://127.0.0.1:2375/containers/10ea294c854e75b5957e198e0b33c0ec7a9fe5e6742b739ed081c6f8081123d5/start \
 -d '{ "Detach":false,"Tty":false}'

but that says "No such container".

**Comment by hacfi** [comment]
@Boran I think by the time you run curl the container already stopped. Please check `docker ps` if it’s still running. Your docker exec just shows the contents of /var/www/html and then the process is finished.

**Comment by Boran** [comment]
"Your docker exec just shows the contents of /var/www/html and then the process is finished".
Exactly, and I'm trying to do the same thing via the API.
Its unclear to me how to do "docker exec" via the API.

**Comment by cpuguy83** [comment]
@Boran https://docs.docker.com/reference/api/docker_remote_api_v1.16/#exec-start

Also, keep in mind, this is specifically for issues with Docker, for support see:
1. forums.docker.com
2. #docker-user mailing list
3. #docker on freenode


Going to close this since it is not an issue.

**Comment by hacfi** [comment]
@Boran The return value of `POST /containers/X/exec` is an exec instance id, not a container. You’re posting to the wrong url: it should be `/exec/X/start` and not `/containers/X/start`.
