### ISSUE TITLE
Empty/blank environment variable fowarding

### ISSUE THREAD

**Issue by pwaller** [docker/docker#10141]
`Docker 1.4.1`

-

If I do (with `API_URL` not set):

```
$ docker run -e API_URL -t -i ubuntu env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=bc8bf09fa178
TERM=xterm
API_URL=
HOME=/root
```

The behaviour I expected is that `API_URL` is set in the container only if it is set on the host. Instead, it is set to the empty string, which is not the same thing.

This is inconvenient as some software will take default configuration depending on whether the variable is set or not.

**Comment by duglin** [comment]
I have a fix for this but I'd like to confirm the net behavior we're all agreeing to:

env var FOO is not defined in my client env

docker run -e FOO ubuntu env  --> FOO is not present in container
docker run -e FOO= ubuntu env --> FOO is present but an empty string
docker run -e FOO=bar ubuntu env  --> FOO=bar
FOO=foo docker run -e FOO ubuntu env  --> FOO=foo
FOO=foo docker run -e FOO= ubuntu env --> FOO is present but an empty string
FOO=foo docker run -e FOO=bar ubuntu env  --> FOO=bar

Now, if FOO was present in the container by default, like HOSTNAME is, then "-e FOO" (if not defined on the client) would remove FOO from the container.  While, "-e FOO=..." would override FOO=... in the container.

Sound right?

@jfrazelle thoughts?

**Comment by pwaller** [comment]
@duglin I agree with your behaviour. :+1:

**Comment by cpuguy83** [comment]
What if instead it errored  out if FOO is not set?
I think _not_ having the var present in the container would be a type of problem someone might spend a non-insignificant amount of time trying to figure out.

**Comment by duglin** [comment]
@cpuguy83, I think @pwaller's comment about how some software might treat not having the env set as an invalid situation and asking them to conditionally put "-e FOO", or not, based on it being set is a lot to ask, IMO.  To me, "-e FOO" is basically asking for my local FOO's state to be copied into the container - which should include the "absence" state.

**Comment by pwaller** [comment]
Again I agree with @duglin.

**Comment by duglin** [comment]
Opened PR#10145
