### ISSUE TITLE
bind mount mkdir on create vs start is fun with folders in tmpfs

### ISSUE THREAD

**Issue by tianon** [docker/docker#10146]
So, I have an apt-cacher-ng container that has a bind mount of `-v /tmp/apt-cacher-ng:...` (and `/tmp` on my host is `tmpfs`).  When I `docker run` it, I use `--restart=always`, and it starts up swell (because `/create` does a `mkdir`).

Now, I reboot my machine and my apt-cacher-ng is gone and fails to start up unless I manually `mkdir /tmp/apt-cacher-ng` because we don't `mkdir` on `/start`, which is certainly confusing the first time you see it because `-v` generally does `mkdir` for bind mounts. :smile:

cc @cpuguy83

**Comment by cpuguy83** [comment]
I think this will be resolved by #10261
Not really the intent of the fix itself, but I think that will do it.
