### ISSUE TITLE
Make the DCO Jess-bot smarter

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#10157]
I'm happy to see the arrival of the Jess-bot to automatically give `DCO sign-off` instructions.

Unfortunately, those instructions won't work for people submitting PRs via the GitHub web-interface (https://github.com/docker/docker/pull/10156#issuecomment-70366175).

Would it be possible to make Jess-bot a bit smarter and have it detect if PRs come from a `patch-[1-9]` branch and give additional instructions?

**Comment by tianon** [comment]
+1, sounds pretty easy if she'd just share the sauce......

**Comment by thaJeztah** [comment]
Yes, would be nice! Every project could have their own personal Jess :smile:

**Comment by LK4D4** [comment]
@jfrazelle Also, probaly we should create other account for this :) Because bot atacking Jessie herself was pretty weird.

**Comment by jfrazelle** [comment]
This should be opened on github.com/jfrazelle/gh-patch-parser :)

**Comment by jfrazelle** [comment]
But I agree on all the above, I do not like attacking myself lol

**Comment by thaJeztah** [comment]
@jfrazelle do you want me to open an issue, or have you put it on your todo list?

**Comment by jfrazelle** [comment]
I will hopefully get some time to do it today but please open an issue so I
don't forget, sorry if this is making you jump through a hoop. Just don't
want to forget what was said here :)

**Comment by thaJeztah** [comment]
No prob! Will create an issue later on. Standing at a birthday party now 🎂

**Comment by tianon** [comment]
https://github.com/jfrazelle/gh-patch-parser/issues/1

**Comment by thaJeztah** [comment]
:+1: thanks Tianon
