### ISSUE TITLE
Docker emits "The image you are pulling has been verified" which is misleading

### ISSUE THREAD

**Issue by pwaller** [docker/docker#10158]
This issue deserves to be separate from #9719 and should focus on what to do about the messaging to users in the immediate term.

As a user of docker, I'm uncomfortable that docker is telling me that an image is verified when it seems that it is known that this doesn't currently provide strong guarantees. This has potential to damage trust in docker's messaging in general.

@kofalt suggested in #9719 that yanking this message until the problems are rectified is a reasonable course of action. I agree and have spoken to other users who agree. Has this been considered? Apologies if I just missed it.

/cc @titanous  @lmars

Useful reading:
https://titanous.com/posts/docker-insecurity
https://lwn.net/Articles/628343/

**Comment by thaJeztah** [comment]
@pwaller Will you also create a PR to make this change? Do you a suggestion for an alternative message? ("An *attempt* has been made..." sounds a bit lame). Perhaps "Pulling image in v2 format" or something.

**Comment by pwaller** [comment]
@thaJeztah done, see #10160.

**Comment by jlhawn** [comment]
Thanks @pwaller! I also want to mention that there has been a pending Pull Request for a few weeks now which does make this message meaningful: #9784, specifically this chunk: https://github.com/docker/docker/pull/9784/files#diff-7cbe4277b9a08ded689d34eaae37655eR485
which results in an error if the checksum of the layer does not match what was in the signed image manifest.

**Comment by pwaller** [comment]
@jlhawn looking forward to it :)

**Comment by jlhawn** [comment]
@pwaller #9784 was merged this morning and conflicts with your PR :(

**Comment by jfrazelle** [comment]
Closing now that we have https://github.com/docker/docker/pull/9784/files#diff-7cbe4277b9a08ded689d34eaae37655eR485, @pwaller let me know tho if you think this is insufficient in anyway

**Comment by thaJeztah** [comment]
The improved message looks fine, so agreed with closing this.

Thanks for taking the time, @pwaller!
