### ISSUE TITLE
[ipv6] IPv6Gateway not set

### ISSUE THREAD

**Issue by stefan-it** [docker/docker#10159]
Dear docker-users (espec. @MalteJ),

I build up the latest Docker version (*1.4.1-dev, build 4245952*) in order to test the latest *ipv6* functionality - and I need some help to get it working properly.

I'm not using any global ipv6 address (so I just added `--ipv6` to the docker daemon call). The following bridge is then configured:

```bash
3: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 56:84:7a:fe:97:99 brd ff:ff:ff:ff:ff:ff
    inet 172.17.42.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::5484:7aff:fefe:9799/64 scope link 
       valid_lft forever preferred_lft forever
    inet6 fe80::1/64 scope link
```

When I do a `docker inspect` on a running container, there's sadly no ipv6 gateway set:

```bash
"Bridge": "docker0",
        "Gateway": "172.17.42.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "172.17.0.2",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "fe80::42:acff:fe11:2",
        "LinkLocalIPv6PrefixLen": 64,
        "MacAddress": "02:42:ac:11:00:02",
        "PortMapping": null,
        "Ports": {}
```

As you can see ```IPv6Gateway``` is empty.

Is it possible to get it working without any `-fixed-cidr-v6` and "global" ipv6 configuration?

Thanks many in advance!

**Comment by MalteJ** [comment]
@stefan-it 
if your container has no global IPv6 address it only can communicate with other devices on the same ethernet link. Thus there is no need for a gateway because the traffic of a fe80::/64 address could not get routed anyway.

How do you want to use the IPv6 gateway?

**Comment by stefan-it** [comment]
I thought it would be very analogue to the ipv4 (where's a gateway/ip address properly set). Is it possible to get a normal `ping6 heise.de` working in my Docker container - at the moment there's no network connectivity for ipv6 in that container.

Thanks again for your help!

**Comment by MalteJ** [comment]
You need to have an IPv6 subnet routed to your host machine. From that subnet you can use addresses for your containers. We do not do NAT with IPv6 like we do with IPv4.

**Comment by MalteJ** [comment]
If your host's IPv6 address is configured via SLAAC it could be possible to use an NDP proxy to tell the other network devices that you serve the container's address, too. http://linux-ip.net/html/tools-ip-neighbor.html
I have not tried this and don't know if it works.

**Comment by stefan-it** [comment]
Thanks Malte! I will try it using a routed subnet :)

**Comment by MalteJ** [comment]
if you still have any questions, feel free to ask :)

**Comment by jfrazelle** [comment]
Thanks @MalteJ for being so responsive to these tickets :) it is greatly
appreciated

**Comment by stefan-it** [comment]
Hi @MalteJ (/cc @jfrazelle), 

I tried the ipv6 functionality now with a routed subnet (thankfully provided by my university) -> it works very well! Thanks for the great work!

**Comment by MalteJ** [comment]
@stefan-it nice to hear that! Are you here in Munich? TU? Uni? Saw the lrz ntp server in one of your configs ;)

**Comment by thomasschaeferm** [comment]
Which configs? Our [ntp](https://www.lrz.de/services/netzdienste/ntp/) servers are top secret! :-)
I also have to thank stefan-it.
(for patience he had)

**Comment by MalteJ** [comment]
@thomasschaeferm https://github.com/stefan-it/JiffyArch/commit/a3ef941a4e4409f565c7abc52e18f3837f27c6e4 :wink:
