### ISSUE TITLE
docker ps freeze on each command

### ISSUE THREAD

**Issue by jbouzekri** [docker/docker#10162]
Hi,

I followed the install guide and pull debian and mysql images using `docker pull debian` and `docker pull mysql`. Then I just run `docker run -d mysql` and everything freeze. Every docker command I run in every terminal just freeze.

I am working on a Ubuntu 14.04.1 LTS version.

Thanks in advance for any advice or tips to search where it went totally wrong.

**Comment by LK4D4** [comment]
@jbouzekri What version of docker do you use?

**Comment by jbouzekri** [comment]
Docker version 1.4.1, build 5bc2ff8

**Comment by jbouzekri** [comment]
I tried another image : the official ubuntu. When I run `sudo docker run -t -i ubuntu /bin/bash`, it freezes too. I never get back the prompt.

On another terminal, I launched docker ps but it freezes too. So I launched a strace docker ps. It seems it freezes when trying to read the /proc/self/mountinfo file. Would this strace be usefull ? Thanks in advance.

**Comment by jbouzekri** [comment]
Oups  just saw this page :  https://github.com/docker/docker/blob/master/CONTRIBUTING.md#reporting-issues, so I am adding the information asked : 

OS : Ubuntu 14.04.1 LTS

uname -a
`Linux maison-linux 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`

docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8

docker info 
Containers: 4
Images: 60
Storage Driver: aufs
 Root Dir: /media/data/Tools/docker/aufs
 Dirs: 68
Execution Driver: native-0.2
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 4
Total Memory: 15.61 GiB
Name: maison-linux
ID: YNRQ:F5KK:KBZH:REB3:GJBL:7HG5:OI2K:YEGN:SAGV:FJFO:EYGU:7QAZ
Debug mode (server): false
Debug mode (client): true
Fds: 10
Goroutines: 10
EventsListeners: 0
Init Path: /usr/bin/docker
Docker Root Dir: /media/data/Tools/docker
WARNING: No swap limit support

Thanks in advance

**Comment by jbouzekri** [comment]
I thought about trying to find the issue on my own but the development environment is in a docker container too and so I cannot make it start because of the same problem ... Infinite loop :(

**Comment by jbouzekri** [comment]
I thought about my issue and I tried to reinstall docker but this time I did not change the docker home folder. So all containers are in my / mount point (with a classic ext4 filesystem and mount configuration). Now, everything seems to work. I can run container and docker ps command at the same time without any freeze.

When I had my previous issue my docker folder was located in a ntfs-3g partition mounted with the following configuration : 

```
UUID=<my-uuid>	/media/data  ntfs-3g  defaults  0 0
```

So every container was run from this folder with a 777 permission. Any idea why it didn't work ?

Thanks in advance

**Comment by jbouzekri** [comment]
I close this issue because it was a hardware related one.

I assume it is because of ntfs-3g filesystem but I would have like an explanation as to why ...

Anyway thanks and for others with the same issue do not use your big windows ntfs filesystem where you instal games ... ;)

**Comment by thaJeztah** [comment]
> I assume it is because of ntfs-3g filesystem but I would have like an explanation as to why ...

@jfrazelle if this is the cause of this issue, I think a check should be added to detect ntfs-3g and output a warning. I think you're maintaining a list of "blacklisted" file systems?
