### ISSUE TITLE
ssh "docker login" crashes 

### ISSUE THREAD

**Issue by ferrislucas** [docker/docker#10168]
Description of problem:
When executing docker login though ssh, an exception is thrown.

`docker version`:
Client version: 1.3.3
Client API version: 1.15
Go version (client): go1.3.2
Git commit (client): 54d900a
OS/Arch (client): linux/amd64
Server version: 1.3.3
Server API version: 1.15
Go version (server): go1.3.2
Git commit (server): 54d900a

`docker info`:
Containers: 0
Images: 0
Storage Driver: btrfs
Execution Driver: native-0.2
Kernel Version: 3.17.8+
Operating System: CoreOS 522.5.0

`uname -a`:
Linux ip-172-31-26-41.ec2.internal 3.17.8+ #2 SMP Fri Jan 9 23:58:08 UTC 2015 x86_64 Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz GenuineIntel GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
This is happening on a c3.large EC2 instance running CoreOS 522.5.0

How reproducible:
Should be reliably reproduced using the steps below:

Steps to Reproduce:
1. Configure pem file authentication in ~/.ssh/config as test_host
Host test_host
  HostName x.x.x.x
  User core
  IdentityFile path/to/pem
2. Execute this: ssh test_host "docker login"
3. Enter any username

Actual Results:
Password: panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x6b3bb7]

goroutine 16 [running]:
runtime.panic(0xa67cc0, 0x1087673)
	/usr/lib/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/docker/docker/pkg/term.DisableEcho(0x0, 0x0, 0x0, 0x0)
	/build/amd64-usr/var/tmp/portage/app-emulation/docker-1.3.3-r1/work/docker-1.3.3/.gopath/src/github.com/docker/docker/pkg/term/term.go:75 +0x127
github.com/docker/docker/api/client.(*DockerCli).CmdLogin(0xc20811caa0, 0xc20800e020, 0x0, 0x0, 0x0, 0x0)
	/build/amd64-usr/var/tmp/portage/app-emulation/docker-1.3.3-r1/work/docker-1.3.3/.gopath/src/github.com/docker/docker/api/client/commands.go:289 +0xd98
reflect.callMethod(0xc2080c5bf0, 0xc2080e5c10)
	/usr/lib/go/src/pkg/reflect/value.go:761 +0x18b
reflect.methodValueCall(0xc20800e020, 0x0, 0x0, 0x1, 0xc2080c5bf0)
	/usr/lib/go/src/pkg/reflect/asm_amd64.s:26 +0x24
github.com/docker/docker/api/client.(*DockerCli).Cmd(0xc20811caa0, 0xc20800e010, 0x1, 0x1, 0x0, 0x0)
	/build/amd64-usr/var/tmp/portage/app-emulation/docker-1.3.3-r1/work/docker-1.3.3/.gopath/src/github.com/docker/docker/api/client/cli.go:76 +0x38e
main.main()
	/build/amd64-usr/var/tmp/portage/app-emulation/docker-1.3.3-r1/work/docker-1.3.3/docker/docker.go:106 +0x84c

goroutine 19 [finalizer wait]:
runtime.park(0x41c920, 0x10a1158, 0x108c989)
	/usr/lib/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x10a1158, 0x108c989)
	/usr/lib/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/usr/lib/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/usr/lib/go/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall]:
os/signal.loop()
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 17 [syscall]:
runtime.goexit()
	/usr/lib/go/src/pkg/runtime/proc.c:1445

Expected Results:
A prompt for password then email, resulting in a successful login assuming the credentials entered are valid.

Additional info:
I am ssh'ing from OSX 10.9.5

**Comment by cpuguy83** [comment]
This looks like it was fixed in 1.4 via https://github.com/docker/docker/commit/e6fd57b90bcdd3b0105fa5c7d17a64332f829ded

Can you test with?

**Comment by crosbymichael** [comment]
Yes, this was fixed by the referenced commit above.
