### ISSUE TITLE
How to build docker on i686 ubuntu 14.04 LTS?

### ISSUE THREAD

**Issue by sourav82** [docker/docker#10165]
I wanted to build docker on i686 Ubuntu 14.04 LTS but getting below errors -

Step 2 : RUN apt-get update && apt-get install -y apparmor aufs-tools automake btrfs-tools build-essential curl dpkg-sig git iptables libapparmor-dev libcap-dev libsqlite3-dev mercurial parallel python-mock python-pip python-websocket reprepro ruby1.9.1 ruby1.9.1-dev s3cmd=1.1.0* --no-install-recommends
 ---> Running in 9a960477ba0b
2015/01/18 07:32:29 exec format error
2015/01/17 23:32:30 The command [/bin/sh -c apt-get update && apt-get install -y apparmor aufs-tools automake btrfs-tools build-essential curl dpkg-sig git iptables libapparmor-dev libcap-dev libsqlite3-dev mercurial parallel python-mock python-pip python-websocket reprepro ruby1.9.1 ruby1.9.1-dev s3cmd=1.1.0* --no-install-recommends] returned a non-zero code: 1
make: *** [build] Error 1

Could you please let me know how to build docker on Ubuntu 14.04 32 bit?

Thanks & Regards,
Sourav

**Comment by is-yangchen** [comment]
You can have a look at this.
https://wiki.archlinux.org/index.php/Docker

I don't know if it helps...

**Comment by unclejack** [comment]
Docker doesn't support i686 right now. This needs quite a bit of work before it can happen.

Please use amd64 (x86_64) in the meantime. Please keep in mind that x86 images can be used on amd64.
