### ISSUE TITLE
"Unable to open the database file" / "no space left on device"

### ISSUE THREAD

**Issue by sebbacon** [docker/docker#10178]
This issue is about two versions of docker, and potentially should be two separate issues, but they seem related, so am reporting them as one for now.

Using docker 1.0.1, I found myself unable to create new containers:

    $ docker run -i -t myimage /bin/bash
    2015/01/19 08:40:59 Error response from daemon: Unable to open the database file: unable to open database file

The corresponding log lines were:

    2015/01/19 08:40:59 POST /v1.12/containers/create
    [56633361] +job create()
    Unable to open the database file: unable to open database file
    [56633361] -job create() = ERR (1)
    [error] server.go:1025 Error making handler: Unable to open the database file: unable to open database file
    [error] server.go:90 HTTP Error: statusCode=500 Unable to open the database file: unable to open database file

This would appear to be related to a disk issue yesterday evening (no space left on device):

    2015/01/18 20:30:09 POST /v1.12/containers/create
    [694aa85b] +job create()
    [error] mount.go:11 [warning]: couldn't run auplink before unmount: exec: "auplin
    k": executable file not found in $PATH
    symlink /proc/mounts /var/lib/docker/aufs/mnt/acb30424f6840a50b26d42cc37d31518050f850c54ba7bfdc3ba7c06ac9ea799-init/etc/mtab: no space left on device
    [694aa85b] -job create() = ERR (1)
    [error] server.go:1025 Error making handler: symlink /proc/mounts /var/lib/docker/aufs/mnt/acb30424f6840a50b26d42cc37d31518050f850c54ba7bfdc3ba7c06ac9ea799-init/etc/mtab: no space left on device
    [error] server.go:90 HTTP Error: statusCode=500 symlink /proc/mounts /var/lib/docker/aufs/mnt/acb30424f6840a50b26d42cc37

If I restarted the docker daemon, I saw the following:

    [56633361] -job init_networkdriver() = OK (0)
    Loading containers: ....<snip>....[error] daemon.go:338 Failed to load container acb30424f6840a50b26d42cc37d31518050f850c54ba7bfdc3ba7c06ac9ea799: open /var/lib/docker/containers/acb30424f6840a50b26d42cc37d31518050f850c54ba7bfdc3ba7c06ac9ea799/config.json: no such file or directory
    ....<snip>....[error] mount.go:11 [warning]: couldn't run auplink before unmount: exec: "auplink": executable file not found in $PATH
    ....<snip>....: done.
    [56633361.initserver()] Creating pidfile
        
As per the "no such file" message, the directory at ` /var/lib/docker/containers/acb30424f6840a50b26d42cc37d31518050f850c54ba7bfdc3ba7c06ac9ea799` was empty.

Upgrading to 1.4.1 results in a new issue, which is that I can't actually start the daemon at all, with the following in the log file:

    time="2015-01-19T08:55:03Z" level="info" msg="+job serveapi(tcp://0.0.0.0:4243, unix:///var/run/docker.sock)" 
    time="2015-01-19T08:55:03Z" level="fatal" msg="Unable to get the TempDir under /var/lib/docker: mkdir /var/lib/docker/tmp: no space left on device" 

However, according to `df` there is 7.6GB of space on `/var/lib/docker`.

I am now completely stuck as to how to continue. Under what circumstances would docker require more than 7.6GB of free space to start up?

**Comment by sebbacon** [comment]
OK, maybe this is related to something to do with my disk:

    # mkdir /var/lib/docker/tmp
    mkdir: cannot create directory `/var/lib/docker/tmp': No space left on device

Investigating further.

**Comment by cpuguy83** [comment]
Closing this for now since it doesn't seem to be a Docker issue.
If you do track down the error and it is docker related, please open a new issue.

Thanks!

**Comment by sebbacon** [comment]
This was not a docker issue. 

I had exhausted my supply of inodes:

    # df -i /var/lib/docker/
    Filesystem      Inodes   IUsed IFree IUse% Mounted on
    /dev/vdb1      6553600 6553600     0  100% /var/lib/docker

However, although this isn't a Docker issue, it is interesting how quickly I was able to exhaust inodes. Should it be mentioned somewhere in the documentation that sysadmins should consider large inode tables for docker + aufs setups? I don't see this anywhere.

**Comment by sebbacon** [comment]
I should add in case it helps anyone else that I was able to escape this situation by deleting the contents of `/var/lib/docker/containers`; this allowed Docker to start, and then I could do some housekeeping routines to free up more inodes (e.g. `docker rm` and `docker rmi`)

**Comment by sebbacon** [comment]
Finally, I suspect the cause of our inode exhaustion was that described in issue #9755
