### ISSUE TITLE
Proposal: use *run* options when i *build* image

### ISSUE THREAD

**Issue by krystism** [docker/docker#10171]
As we know, when we build images, some cached containers will be auto-created, so , I want to use some(not all)  *docker run* options, like *--net*,etc.  It's useful when sometimes i really want to expose my host network, for example, use my host's  */etc/hosts* rather than by dns server. I know some options can be set in /etc/default/docker.io, but that's global scope, i do not like that.

**Comment by dagelf** [comment]
Completely agree. Similar to https://github.com/docker/docker/issues/10199

**Comment by anandkumarpatel** [comment]
+1 very useful would also help wit solve  https://github.com/docker/docker/issues/10191

**Comment by aidanhs** [comment]
Related: I need to set --dns as part of docker build. I made the unfortunate mistake of thinking that `docker --dns=w.x.y.z build` would fix it, but apparently that only applies to the daemon.

**Comment by codyhanson** [comment]
+1 to the comment from @aidanhs. I have noticed that when Docker falls back to using a public DNS server (8.8.8.8), and that server is blocked on an internal network, `docker build` cannot run.

**Comment by thaJeztah** [comment]
@codyhanson If public DNS servers are blocked on your network, you should change the DNS settings for the daemon. See [Daemon DNS options](https://docs.docker.com/reference/commandline/cli/#daemon-dns-options) in the documentation.

**Comment by codyhanson** [comment]
@thaJeztah perfect! just what I was looking for. Somehow I missed that part of the docs.

**Comment by jfrazelle** [comment]
closing as dup of https://github.com/docker/docker/issues/1916 https://github.com/docker/docker/issues/4962 https://github.com/docker/docker/issues/10324 https://github.com/docker/docker/issues/10191
