### ISSUE TITLE
how can i change the value of /proc/sys/kernel/shmmax  in a container?

### ISSUE THREAD

**Issue by yousq** [docker/docker#10176]
I created an image based on the official images centos:6, but I  need a bigger /proc/sys/kernel/shmmax value. Is any one can help me to deal with the prompt: "/proc/sys/kernel/shmmax: Read-only file system" ??

**Comment by crosbymichael** [comment]
This is a settings that you will have to set on your host and it will be propagated to the containers.

**Comment by arthurbarr** [comment]
I haven't found this to be the case for shmmax.  If I set the value on the host (using sysctl) on Ubuntu 14.04 then it is *not* propagated to the container.  It works OK on boot2docker though.  What is it that controls this?  I can't find any documentation about this either.

**Comment by natea** [comment]
I'm having the same problem. I'm able to launch containers using boot2docker, and they have plenty of shared memory:

```
[root@a0411ca556df /]# cat /proc/sys/kernel/shmmax
18446744073692774399
```

But when I launch the same container on a normal Docker server (not boot2docker), then the shared memory is much smaller:

```
[root@a06b7e4b3f97 /]# cat /proc/sys/kernel/shmmax
33554432
```

I tried running these commands to change the shared memory setting on the host, hoping that it would propagate to the Docker containers, but it does not:

```
root@docker:/# echo "kernel.shmmax=2147483648" >> /etc/sysctl.conf
root@docker:/# sysctl -w kernel.shmmax=2147483648
kernel.shmmax = 2147483648
```

@crosbymichael any tips on where to make the shmmax setting on the host such that it propagates to the containers?

**Comment by arthurbarr** [comment]
I've tracked this down.  A [change](https://git.kernel.org/cgit/linux/kernel/git/mhocko/mm.git/commit/include/uapi/linux/shm.h?id=060028bac94bf60a65415d1d55a359c3a17d5c31
) went into Linux kernel V3.16 which fixes this.  Previously, the shared memory allocated to containers was hard-coded to 32 MB, and now it's set much higher.  boot2docker keeps pretty up-to-date on kernel versions, which is why it works there.  If you're not able to upgrade your kernel, then one alternative is to give your container access to the host's IPC namespace using the [`--ipc host`](http://docs.docker.com/reference/run/#ipc-settings) option on `docker run`.  This is a security risk as it breaks the isolation of your container, but it is an option.

**Comment by jeremyeder** [comment]
For future googlers, the patch referenced above is already in RHEL7.1, but I should say that I think this rather has to do with ULONG vs ULLONG...we're looking into it a bit more.

**Comment by zrml** [comment]
Hi guys:
Don't you think that reading from the host this value it's a risk? all containers will be able to allocate huge chunks of shmem. I'd prefer to have the option to handle this for each single container point of view even if my start-up script will have to invoke sysctl -w kernel.sh*=<figure>?
thanks

**Comment by kopax** [comment]
I really don't understand why this is closed, this is a major issue.

Without the `--ipc host`, host has it's own `ipcs -lm` value (default to 16MB on Debian Jessie). 

In 06/2016, there is still no way to get this configured in the container ?

**Comment by thaJeztah** [comment]
@kopax see this PR, which will be in the next release (docker 1.12); https://github.com/docker/docker/pull/19265

**Comment by kopax** [comment]
@thaJeztah Thanks, I am not familiar with docker's release cycle. Do you know approx when will be the 1.12 released ?

**Comment by thaJeztah** [comment]
@kopax somewhere after DockerCon; it's usually a two-month release cycle; may be slightly longer this time due to DockerCon being in the middle of that cycle (don't have the definitive release date yet); https://github.com/docker/docker/wiki

**Comment by zrml** [comment]
@thaJeztah Thanks for the link to the other PR. Looking forward to testing it...
