### ISSUE TITLE
add --dns flag on docker start (restrictive LANs)

### ISSUE THREAD

**Issue by pritambaral** [docker/docker#10177]
My institute LAN blocks all outgoing UDP and only select TCP traffic; only the internal DNS server is expected to be used. The internal DNS server's IP is served via DHCP, so all normal systems work normally.

But when docker decides to use `8.8.8.8` inside a container, that container now cannot use DNS.

One would say I could simply use the `--dns` option when creating a container. But that works only when *creating* a container.

I work from multiple locations, only one of them being the institute with the restrictive-LAN mentioned above. When I create a container with `docker run --dns` inside, stop the container, go out to another network, I cannot start the container with a different `--dns` again. I either have to create a new container, or manually edit `/etc/resolv.conf`.

My proposed solutions:

- Add an option to docker to proxy DNS by listening on the bridge IP. This has the advantage of being seamless. One does not have to manually switch dns entries when switching networks. The proxy should detect and handle changes in host's `/etc/resolv.conf`, of course; and/or
- Bring the `--dns` option to `docker start`

*I have the former working, in a private branch. I'm bringing this up partly so the design can be discussed with the core team.*

**Comment by MalteJ** [comment]
hmm, missing support of a `--dns` flag for `docker start` could be considered a bug.

@LK4D4 @jfrazelle how do you think about this?

**Comment by jfrazelle** [comment]
Well 1 thing that is cool on the master branch (and that will be in the release) is when you edit the resolv.conf on your host it automatically refreshes the one in the container, so i think that would be helpful here.

**Comment by jfrazelle** [comment]
here is some more information on that as well https://github.com/docker/docker/pull/9648

**Comment by pritambaral** [comment]
^ & ^^: That still does not address restrictive LANs.

**Comment by pritambaral** [comment]
^Especially when the host has an entry like `127.0.0.1` (e.g., for local caching of DNS)

**Comment by jfrazelle** [comment]
we could add the flag on start then

**Comment by fgimenez** [comment]
#dibs

**Comment by cpuguy83** [comment]
Wouldn't setting this at the daemon level (which is available today) resolve this?

**Comment by thaJeztah** [comment]
Not sure, if I read this part;

>When I create a container with docker run --dns inside, stop the container, go out to another network, I cannot start the container with a different --dns again. I either have to create a new container, or manually edit /etc/resolv.conf.

**Comment by cpuguy83** [comment]
But you can always restart the daemon with a new dns server.

**Comment by thaJeztah** [comment]
Also true. Not sure if restarting all containers is desirable in all cases of course.

**Comment by calavera** [comment]
We already support this flag in `docker run` and `docker create`. Setting that flag must happen at the `create` stage. Closing this as fixed:

```
docker git:(master) docker run --help | grep dns
--dns=[]                        Set custom DNS servers
--dns-opt=[]                    Set DNS options
--dns-search=[]                 Set custom DNS search domains
```
