### ISSUE TITLE
Spurious SIGTERM sent to containers upon API /start with (presumed) invalid HostConfig

### ISSUE THREAD

**Issue by gdm85** [docker/docker#10188]
I have been experiencing for long time an issue where upon host reboot, and without using a ``-restart`` policy for these containers, I have troubles at starting all (about 100) the containers second their dependency because some of them quit having received a SIGTERM.

The supervisord which acts as pid 1 in these containers reports:
```
2015-01-19 18:28:11,538 WARN received SIGTERM indicating exit request
```

#7414 hides problem like these, because eventually after many attempts I can manage to start them.

**Edit:** I think it's due to the way I call the API with HostConfig. Probably some HostConfig field is missing.

But again: any idea why a SIGTERM would be sent to pid 1 of containers if something was wrong in the HostConfig provided to ``/start`` ?

NOTE: there are not calls to ``/stop`` in the debug-enabled daemon log and there is no OOM kicking in.

docker version:
```
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
```

docker info
```
Containers: 95
Images: 1538
Storage Driver: btrfs
Execution Driver: native-0.2
Kernel Version: 3.13.0-44-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 18
Total Memory: 23.53 GiB
Debug mode (server): true
Debug mode (client): false
Fds: 593
Goroutines: 429
EventsListeners: 0
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker
```

**Comment by gdm85** [comment]
I found the issue, not related to docker.

Sorry for the noise :(

**Comment by drewhemm** [comment]
And the issue was?

**Comment by gdm85** [comment]
@drewhemm hard to remember... I think it was as simple as the host system running out of AIO handles, thus MySQL containers exiting (because they need AIO in default MySQL configuration)

**Comment by drewhemm** [comment]
Okay, as you say, not related to docker. I found my issue, I was running Puppet inside the container and inadvertently killing the process that was called by CMD, haha!
