### ISSUE TITLE
Docker installation documentation points to an Ubuntu repo that does not appear to exist

### ISSUE THREAD

**Issue by jpellman** [docker/docker#10185]
Hello Docker World,

I am attempting to install Docker on a machine running Ubuntu 14.04.  I've been following the instructions outlined in version 1.4 of the Docker Documentation (https://github.com/docker/docker/blob/master/docs/sources/installation/ubuntulinux.md) for installing the Docker-maintained package.  There's only one problem- after I add the Docker repo and update my package lists with apt, apt gives me the following message:

>W: Failed to fetch https://get.docker.com/ubuntu/dists/docker/main/binary-amd64/Packages  
>
>W: Failed to fetch https://get.docker.com/ubuntu/dists/docker/main/binary-i386/Packages  

I have tried browsing the package directories manually within my browser, and each time I get a 404 error.  Like the Mary Celeste in the Bermuda Triangle, the packages look to be lost.  Has the repo sailed to another port?

Best,
John Pellman

**Comment by jpellman** [comment]
Ah- looks to be related to this issue: 

https://github.com/docker/docker/issues/7422

**Comment by jpellman** [comment]
The solution seems to be to e-mail support@docker.com.

**Comment by anilrona2** [comment]
Any luck with that issue ?

**Comment by jfrazelle** [comment]
I would email support@docker.com

**Comment by jpellman** [comment]
^^ What she said.

Although if it helps, my solution was to re-install the certificate (even though it should have been in ca-certificates, and in fact has been in ca-certificates on other Ubuntu installations I've had).  Here's the URL for that:
https://www.geotrust.com/resources/root-certificates/
It should be root 5 (SHA256).

**Comment by anilrona2** [comment]
Well, I tried that and it did not work for me.
I will mail them and ask.
Thanks anyway for the help.

**Comment by duytonghai** [comment]
You can you `sudo nano /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/provisioners/docker/cap/debian/docker_install.rb`
And changing `http` to `https` in the sources.list.d/docker.list seems to fix the problem.
