### ISSUE TITLE
Feature: Allow `docker build` to be resource constrained by the caller

### ISSUE THREAD

**Issue by smarterclayton** [docker/docker#10191]
Currently the `docker build` process runs under the docker daemon's cgroup, which means it has access to potentially unlimited CPU, Memory, and Disk bandwidth.  We would like to be able to constrain a docker build to a limited set of resources (similar to containers being run via `docker run`).  While today `docker build` currently runs with fairly high privileges, as things like user namespaces are added we will be increasing the security to where ordinary system users will be able to docker build more frequently.  

I can think of two main user scenarios around constraining the resources a build can use:

1. I'm a user on the command line, and my administrator allows me to docker build on top of images that are not running as the root user.  My administrator would like my CPU, memory, and disk usage to be governed by the same limits as my normal user account.
2. I'm hosting docker builds for my company via an API, and I want to limit the resources that any individual build gets so that I can ensure aggressive or malicious builds don't cause the whole server to fall over.

The first use case would be that ideally docker build uses the cgroup the client PID is under to also run the build - resources are then shared between my session and the build, and are accounted for under my cgroup structure.

The second use case is a bit broader - the implementer of the hosting API might want to specify the exact cgroup based on attributes of the user, or simply have all docker builds default to a specific cgroup template.

There might be three increasing complexity features:

1. On daemon startup, provide a flag for a cgroup template (or other resource spec) which all docker builds should be contained under
2. Allow a cgroup or cgroup template (or resource spec) to be provided as an API argument on the build API, to limit the resources available for execution
3. Have the docker build CLI automatically send (or alternatively fetch via the unix socket credentials) the current cgroup of the CLI process (or default resource spec of the user calling the command) and use that as the default value to the daemon.

In our case, we're trying to host docker builds in a reasonably resource constrained fashion, and moreover, to do it from a container (which already has cgroup limits set).  We'd prefer for the build we run to inherit the limits of the caller so that it's easy to reason about the limits of the build (the "builder" container gets X CPU, so the docker build simply shares that).

Do others have a similar need or see the benefit in a feature like this in docker build?  We wanted to get feedback before pulling together a pull request.

**Comment by anandkumarpatel** [comment]
+1. I think it would also be great if we could pass in arguments to docker build which propagate to all the containers ran during the build. This would allow resource constraints as well as volumes/networking

**Comment by krystism** [comment]
+1. I'd like to expose my host network when i build image. #10171

**Comment by pdericson** [comment]
+1

I'm thinking in the context of a swarm cluster where you might be doing docker builds alongside running containers - being able to cap memory usage could be useful there.

**Comment by smarterclayton** [comment]
Or to prevent malicious builders from denying progress on other builders on a "build host"

**Comment by cpuguy83** [comment]
I've got this implemented for cpu/cpushares/mem/memswap, but need to wait until #10298 gets merged.

**Comment by termie** [comment]
+1

**Comment by smarterclayton** [comment]
This isn't really fully resolved - use case 1 requires a bit more than 11410 provides.  I think the limits added are valuable and a good start though.

**Comment by cpuguy83** [comment]
@smarterclayton I agree it's not fully resolved since you have two parts here, however:

Docker 1.6 will include the above mentioned resource constraints for `docker build`
Docker 1.6 also includes support for setting ulimits on containers, as well as setting default ulimits for all containers at the daemon level.
Does this provide sufficient resource restriction?

Setting default ulimits at the daemon level feels right... setting default memory/cpu/cpuset/swap at the daemon level feels... less right.... but I'm not sure.
One could intercept build requests and apply those resource constraints before sending to the daemon.
WDYT?

**Comment by smarterclayton** [comment]
Not disagreeing this is a good first step.  Inheriting cgroup (being a subordinate cgroup of the launching docker builder) was the valuable next step for us, because that would allow a much finer grained control over how builds run.  Essentially allowing the caller cgroup to be properly configured with the right settings for network, block, etc controls and having the build use a subset of that.  I'll update the issue to focus more on that.

Thanks for pushing this through though - I'm grateful. :)
