### ISSUE TITLE
docker builds are slow

### ISSUE THREAD

**Issue by zopyx** [docker/docker#10202]
docker builds are slow, very slow? why?

A simple docker command like 

RUN useradd -ms /bin/bash plone

takes on my system (CentOS 7, new box, fresh installation, enough CPU, enought memory) between 5 to 10 seconds.

A typical operation like "apt-get install" with some packages runs 5-10 times longer than on a normal system.

Why is this the case?

**Comment by thaJeztah** [comment]
Would you be able to add a bit more information about your system, as described here: https://github.com/docker/docker/blob/master/CONTRIBUTING.md#reporting-issues

**Comment by zopyx** [comment]
[ajung@localhost ~]$ uname -a
Linux localhost.localdomain 3.10.0-123.el7.x86_64 #1 SMP Mon Jun 30 12:09:22 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
[ajung@localhost ~]$ docker version
Client version: 1.3.2
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 39fa2fa/1.3.2
OS/Arch (client): linux/amd64
Server version: 1.3.2
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): 39fa2fa/1.3.2
[ajung@localhost ~]$ docker -D info
Containers: 5
Images: 126
Storage Driver: devicemapper
 Pool Name: docker-253:1-203062427-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 6.601 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 8.069 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.84-RHEL7 (2014-03-26)
Execution Driver: native-0.2
Kernel Version: 3.10.0-123.el7.x86_64
Operating System: CentOS Linux 7 (Core)
Debug mode (server): false
Debug mode (client): true
Fds: 24
Goroutines: 25
EventsListeners: 0
Init SHA1: c906504aa058139c1d0569ecd0aa5f462a73440f
Init Path: /usr/libexec/docker/dockerinit

The issue is unspecific to certain hardware or OS or network connection. Builds on various hosts that I used for testing Docker are that slow.

**Comment by LK4D4** [comment]
This probably was fixed by #9720, all drivers except aufs was affected. There was two very heavy goroutines which walked over old and new layers content.

**Comment by unclejack** [comment]
I'm going to close this in favor of #10161 as it has some numbers and some more bits of useful information.
