### ISSUE TITLE
Docker --help output too chatty

### ISSUE THREAD

**Issue by phemmer** [docker/docker#10214]
I frequently use `--help` as a quick lookup to find some option. With the current output, it's very hard to read.

For example, this is what `docker --help` looks like (other commands, such as `docker run --help` are no better):
![image](https://cloud.githubusercontent.com/assets/1826947/5812258/6304deb8-a034-11e4-94b0-f6304b78e198.png)
Many lines are wrapped, some lines are continued from the previous line, but indented. It's all rather messy and inconsistent. For example the `--fixed-cidr` line takes up 3 lines, the second one indented, the 3rd one wrapped. `--group` is the opposite, the 2nd line wrapped, and 3rd indented.
And my terminal is 100 characters wide, which I think is a fairly reasonable number. But even increasing the width, you have to get pretty wide before all the wrapping goes away.

I think we need to cut this output down. `--help` output is meant to be a very brief synopsis of the option. If the user needs more info, they should consult the documentation.
Prime example, the `--selinux-enabled` option mentions "SELinux does not presently support the BTRFS storage driver". Why is this in the `--help` output? If we listed all the known issues in the `--help` output, it'd rival the `zshall` man page.
With this, I think it would also be a good idea to decrease the width of the first column, so the synopsis of each option has more room.

**Comment by jfrazelle** [comment]
@bfirsh I feel like you may have some good opinions on this

**Comment by tiborvass** [comment]
@jfrazelle We could tabformat it.

**Comment by duglin** [comment]
I kind of like the idea of forcing all lines to fit within 80 chars (so it just one line per flag).
If people are ok with this I could work on a PR.

**Comment by cpuguy83** [comment]
We could do like git and instead show the man page for the particular command.

**Comment by phemmer** [comment]
> We could do like git and instead show the man page for the particular command

Please no. I personally hate this practice. When all I want is a quick reference, because I forgot if some flag has a dash in it or not (or whatever), I don't want to have to read through a man page.

**Comment by duglin** [comment]
I'd like to propose this:
```
Options:
  --api-enable-cors=false                Enable CORS headers in the remote API
  -b, --bridge=""                        Attach containers to a network bridge
  --bip=""                               Specify network bridge IP
  -D, --debug=false                      Enable debug mode
  -d, --daemon=false                     Enable daemon mode
  --dns=[]                               DNS server to use
  --dns-search=[]                        DNS search domains to use
  -e, --exec-driver="native"             Exec driver to use
  --fixed-cidr=""                        IPv4 subnet for fixed IPs
  -G, --group="docker"                   Group for the unix socket
  -g, --graph="/var/lib/docker"          Root of the Docker runtime
  -H, --host=[]                          Daemon socket(s) to use or connect to
  --icc=true                             Enable inter-container communication
  --insecure-registry=[]                 Enable insecure registry communication
  --ip=0.0.0.0                           Default IP when binding container ports
  --ip-forward=true                      Enable net.ipv4.ip_forward
  --ip-masq=true                         Enable IP masquerading
  --iptables=true                        Enable addition of iptables rules
  --mtu=0                                Set the containers network MTU
  -p, --pidfile="/var/run/docker.pid"    Path to use for daemon PID file
  --registry-mirror=[]                   Specify a preferred registry mirror
  -s, --storage-driver=""                Storage driver to use
  --selinux-enabled=false                Enable selinux support
  --storage-opt=[]                       Set storage driver options
  --tls=false                            Use TLS; implied by tls-verify flags
  --tlscacert="/root/.docker/ca.pem"     Trust certs signed only by this CA
  --tlscert="/root/.docker/cert.pem"     Path to TLS certificate file
  --tlskey="/root/.docker/key.pem"       Path to TLS key file
  --tlsverify=false                      Use TLS and verify the remote
  -v, --version=false                    Print version information and quit
```

One of the problems is that the real default values are used in the help text.  While this sounds like a cool thing to do, it means that those paths shown might actually be really long and could push things past 80 chars. I could also use static dummy values if people want.
Thoughts?  I can do a PR if people are ok with this first step.

**Comment by phemmer** [comment]
I think the most likely value that's going to change, and possibly get long, is the home directory path. Perhaps for these values, we can substitute in `~`.

E.G.:

        --tlscert=~/cert.pem

But otherwise I think your proposed output is good.

It might also be nice to add a test to ensure that future changes don't break the format.

**Comment by duglin** [comment]
Created https://github.com/docker/docker/pull/10547 to address this.
