### ISSUE TITLE
How to attach a PCI device to a container

### ISSUE THREAD

**Issue by balakrishna3283** [docker/docker#10217]
Hi,

I am trying to attach a Network device to the container. I am able to attach hdd device by providing --device=/dev/sdb argument for docker run

Similarly how do I attach a network device to a container?

Thanks in advance
Krishna

**Comment by unclejack** [comment]
@balakrishna3283 You can move network interfaces from the host to a container using https://github.com/jpetazzo/pipework.

There's going to be a new networking implementation which makes everything more flexible and will allow you to set up networking in a different way. This is currently being discussed as a proposal here: https://github.com/docker/docker/issues/9983

I'm going to close this issue now. Please feel free to comment on this issue if you have more questions.

**Comment by balakrishna3283** [comment]
Hi unclejack,

Thank you for quick reply.
