### ISSUE TITLE
Hub image name length < 3

### ISSUE THREAD

**Issue by devinrsmith** [docker/docker#10213]
```Shell      
$ docker pull dockerfile/go
Pulling repository dockerfile/go
FATA[0001] Could not reach any registry endpoint        
$ docker pull dockerfile/go
Pulling repository dockerfile/go
FATA[0000] Could not reach any registry endpoint        
$ docker pull dockerfile/go
Pulling repository dockerfile/go
a0f9d87c21c8: Error pulling image (latest) from dockerfile/go, Authentication is required. 
FATA[0000] Error pulling image (latest) from dockerfile/go, Authentication is required. 
$ docker pull dockerfile/go
Pulling repository dockerfile/go
a0f9d87c21c8: Error pulling image (latest) from dockerfile/go, Server error: Status 401 while fetching image layer (5aa9da73df5b1b35146b60b8a5e97805dd61e4b55e7925d8405919658b00ac97) b8a5e97805dd61e4b55e7925d8405919658b00ac97) 
53f858aaaf03: Download complete 
837339b91538: Download complete 
615c102e2290: Download complete 
b39b81afc8ca: Download complete 
5aa9da73df5b: Error pulling dependent layers 

Please login prior to pull:
Username: ^C
```

**Comment by jfrazelle** [comment]
OMG this happened to me too ping @kencochrane, hub changed it so images had
to be 3 chars long, I have one named t

**Comment by jfrazelle** [comment]
can you all change it so that it won't give a 401, I think @jlhawn was asking for this as well.

**Comment by jfrazelle** [comment]
Also @devinrsmith I would say for now, the official golang image should work https://registry.hub.docker.com/_/golang/

**Comment by devinrsmith** [comment]
Thanks @jfrazelle for the quick replies, I'll give golang a try. Still no fun when stuff that used to work doesn't work anymore! :O

**Comment by tianon** [comment]
UGH

**Comment by tianon** [comment]
Do we have a rationale for why this change was made?  I think we're talking about a non-trivial number of images broken here, so I'm not seeing a real good reason to do this.

**Comment by jfrazelle** [comment]
Yeah so when I reached out to the hub side (after the horror of thinking something was broken in docker) they said that when they changed it, it was NOT supposed to effect existing images. So I hope they are fixing it.

**Comment by jfrazelle** [comment]
Also I feel like we should be informed of these decisions in the future.

**Comment by tianon** [comment]
+1, but I'd still like to know the reason for the change (and I'm positive that I'm not alone), because two-letter image names per-user seems pretty harmless to me, especially since they already exist in the wild

**Comment by tianon** [comment]
It'd be especially great if a change like this weren't made without an accompanying change in Docker first, even if it's just a warning that the image name you've just created won't be supported if you try to push it, IMO.

**Comment by jfrazelle** [comment]
agreed

**Comment by jfrazelle** [comment]
and I love my 1 letter image

**Comment by fxdgear** [comment]
Sorry about the troubles :frowning:

We fixed the issue, if you're still having problems please let us know.

**Comment by tianon** [comment]
@fxdgear only trouble I'm having now is:

> Namespace (optional) and Repository Name: Enter a valid repository name.Ensure this value has at least 3 characters (it has 1).

:cry:

**Comment by kencochrane** [comment]
@tianon where are you seeing that?

**Comment by tianon** [comment]
On the create a new repo page while trying to create the perfectly harmless `tianon/a` :sheep:

**Comment by kencochrane** [comment]
@tianon ok, we didn't fix that one, we just fixed the issue where people couldn't pull repos they already had that were < 3 characters.

**Comment by tianon** [comment]
Right, I'm just being obtuse because this seems like an unnecessary change without any real explanation for the rationale behind it. :angel:

I very much appreciate the quick fix to existing repos! :heart:

**Comment by jfrazelle** [comment]
Closing, as this seems to be fixed for existing repos thanks all for the speedy fix
