### ISSUE TITLE
Docker cli ignores environment variable http_proxy

### ISSUE THREAD

**Issue by andreas-kupries** [docker/docker#10224]
When running a command like

    http_proxy=http://proxyhost:8080 curl ...

the logs of the proxy in question show that it got used.
On the other hand, when running

    http_proxy=http://proxyhost:8080 docker search foo

nothing is left in the proxy logs at all.
Looks like the client ignores the proxy setting and keeps talking directly to the registry|hub.

**Comment by thaJeztah** [comment]
Are you running the current "master" build? This PR was recently merged and should be in the next release; https://github.com/docker/docker/pull/9951

If you want to test the current "master" build, you can download these from master.dockerproject.com

**Comment by andreas-kupries** [comment]
I got the "latest" lxc-docker apt package yesterday, as per
https://docs.docker.com/installation/ubuntulinux/#docker-maintained-package-installation

"docker version" reports
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8

**Comment by thaJeztah** [comment]
The PR I referred to is not yet in that release, but will be in the upcoming 1.5 release. You can wait for that release, or try a master build from https//master.dockerproject.com. Note that the master builds are the current "development" versions; they are tested using the automated tests, but don't run them on production / important things, because they *can* contain bugs.

**Comment by andreas-kupries** [comment]
Thanks. Currently trying with the 141-dev version from master.dockerproject.com.

This one changes behaviour a bit. When I try
    http_proxy=http://localhost:8080  ./docker search a
I now get
    FATA[0000] Error response from daemon: 404 page not found

Whereas when I try
    http_proxy=http://localhost:8080 curl http://arxiv.org/abs/1412.7725
it works fine, returning the page in question. So, the proxy itself is fine, it seems.

(Side note: I am working within the root account here, to avoid docker from bailing on me in general due to no permission on its unix socket (/var/run/docker.sock), proxy or not)

**Comment by thaJeztah** [comment]
Thanks for testing; I just noted that some instructions were added to the documentation explaining this;

https://github.com/docker/docker/pull/10192/files

> If you happen to have a proxy configured with the `HTTP_PROXY` or `HTTPS_PROXY` environment variables but still want to communicate with the Docker daemon over its default `unix` domain socket, setting the `NO_PROXY` environment variable to the path of the socket (`/var/run/docker.sock`) is required.

**Comment by andreas-kupries** [comment]
Thank you. That gets rid of the 404 for me.
Yet I again still do not see proxy log data for the command

    http_proxy=http://localhost:8080 no_proxy=/var/run/docker.sock ./docker search a

Now I had a thought. Is the docker cli talking to the docker daemon and it is then the daemon(ized cli) which actually talks to the registry/hub to perform the search ?

That would explain what I see because while I have a proxy set on the cli, this is certainly not true for the daemon.  (I assume here that "search" is indeed a command talking to the hub, contrary to "images" which should be local).

It also means that I have set the proxy information somewhere else, i.e. where the daemon gets started. Time to read more documentation.

We can likely close this ticket now.

**Comment by andreas-kupries** [comment]
Confirmed. Stopped the daemon, then started my own, with the proxy properly set.
The operation now appears in the proxy logs.

**Comment by thaJeztah** [comment]
Great, was just about to respond that, yes, the *daemon* queries the registry; http://docs.master.dockerproject.com/reference/api/docker_remote_api_v1.17/#search-images

Thanks again for testing this new feature and good luck with your dockers!

(You should be able to close to issue, because you opened it, thanks!)
