### ISSUE TITLE
Port allocation is outside of configured ephemeral port range

### ISSUE THREAD

**Issue by miminar** [docker/docker#10220]
This is probably not an issue but I'd like to have a clear statement from someone with more insight.

Docker uses its own hardcoded port range for allocation of host's ports for published container ports. Its size limits the number of concurrently running containers with published ports (run with `-P` or `-p <containerPort>`). Currently it's 65535 - 49153 = 16384 (minus number of ports from this range used by other clients).

On linux there is an [ephemeral port range](http://www.ncftp.com/ncftpd/doc/misc/ephemeral_ports.html) configured with `/proc/sys/net/ipv4/ip_local_port_range` used for allocation of free ports to client' endpoints. Is there a reason, why this port range is not used for published container ports as well?

One customer expressed a concern about a sufficiency of this arbitrarily chosen range and the lack of its configurability (`/proc/sys/net/ipv4/ip_local_port_range` would be sufficient).

I have a patch that uses *ephemeral port range* for published ports. But I'm not sure, whether it is right to consider them equal. IMHO ports exported by containers belong to server-side services rather than short-term client end-points.

**Comment by tiborvass** [comment]
Ping @erikh @LK4D4 @crosbymichael @icecrime

**Comment by erikh** [comment]
+1. This should be simple to implement in the new driver, and is probably causing a number of people grief.

Please send a patch. :)

-Erik
