### ISSUE TITLE
Error message when pulling image with checksum failure

### ISSUE THREAD

**Issue by icecrime** [docker/docker#10256]
Here's what I did:

* Bring up a local v2 registry
* Pull the `busybox` official image
* Tag it and push it as `localhost:5000/icecrime/busybox:latest`
* Sneak into my registry storage and mess with one of the blobs
* Remove my `localhost:5000/icecrime/busybox:latest` and try pulling it again

Result is the following:

```
$ docker pull localhost:5000/icecrime/busybox:latest
latest: Pulling from localhost:5000/icecrime/busybox

511136ea3c5a: Pull complete
df7546f9f060: Pull complete
ea13149945cb: Verifying Checksum
4986bf8c1536: Download complete
Pulling repository localhost:5000/icecrime/busybox
FATA[0000] Error: image icecrime/busybox:latest not found
```

This is not very explicit for the user as the checksum failure is not forwarded down to the client. On the daemon side, my logs properly show:

    ERRO[0155] Error from V2 registry: image verification failed: checksum mismatch - expected "tarsum.v1+sha256:d43a7079c4dd020e9c65419c2eb6751ea49d6f7f9337edd895596cd5f7aa6369" but got "tarsum.v1+sha256:68bd7d314f68c513a8404be9ecaaac31606ad21ba0eca2c63828df796a7ad16a"

**Comment by jfrazelle** [comment]
um tarsum? what is triage for this hehehe

**Comment by jfrazelle** [comment]
ping @icecrime can you triage ;)

**Comment by clintonskitson** [comment]
PR #10256 submitted that should clear up the issue.  Happy Bday!


root@30f54983dc5d:/go/src/github.com/docker/docker# docker pull 192.168.59.103:5000/go1billion
latest: Pulling from 192.168.59.103:5000/go1billion
5e311d01aee6: Checksum problem 
30299bfeb4ca: Pulling fs layer 
c1ac36fdb878: Download complete, Checksum passed 
dca26a1cad75: Layer already being pulled by another client. Waiting. 
511136ea3c5a: Already exists 
FATA[0000] Image checksum failed

**Comment by LK4D4** [comment]
Looks like fixed. Can you confirm @aaronlehmann ?

**Comment by aaronlehmann** [comment]
Confirmed - the error message is now:

```
filesystem layer verification failed for digest sha256:778bc9e6d105c701b59760afce3e6ff0f50ae350f89b9a4da87425b6861a4c3f
```
