### ISSUE TITLE
Docker push in v1.4.1 doesn't work against private registry running behind nginx ssl proxy (with suggested config)

### ISSUE THREAD

**Issue by lsowen** [docker/docker#10258]
When pushing against a private registry (running v0.9.1), it fails with the following message:

```shell
FATA[0051] mux: variable "hcg-uwsgi" doesn't match, expected "^(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/){1,4}[a-z0-9]+(?:[._-][a-z0-9]+)*$" 
```

commands run:

```shell
docker tag hcg-uwsgi docker.example.com/hcg-uwsgi:latest
docker --debug=true push docker.example.com/hcg-uwsgi
````

The reason is because v1.4.1 attempts to hit ``https://docker.example.com/v2/``.  With the suggested nginx config (https://github.com/docker/docker-registry/blob/f96d5ec35a797953cee18a35410e5c0cd5394e56/contrib/nginx/nginx_1-3-9.conf#L30), this returns a 401 (unauthorized).

Forcing a 404 for the ``/v2/`` url makes docker v1.4.1 fallback to the ``/v1/`` restful endpoint, and everything works great.

Example:

```nginx
    location /v2/ {
        auth_basic off;
        return 404;
    }
```

Output of ``docker info``:

```shell
Containers: 22
Images: 120
Storage Driver: devicemapper
 Pool Name: docker-253:0-1194892-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 4.443 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 7.512 MB
 Metadata Space Total: 2.147 GB
 Udev Sync Supported: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.16.3-200.fc20.x86_64
Operating System: Fedora 20 (Heisenbug)
CPUs: 2
Total Memory: 1.955 GiB
Name: <redacted>
ID: <redacted>
```

**Comment by jlhawn** [comment]
I think this might be a duplicate of this issue: https://github.com/docker/docker/issues/10226

**Comment by jlhawn** [comment]
@lsowen can you confirm whether this issue still exists in the latest build of the master branch?

**Comment by lsowen** [comment]
@jlhawn do I have to build it myself, or is there somewhere to download it?  Or do you want me to test the v1.5.0-rc1 release?

**Comment by dmp42** [comment]
@lsowen using the RC should do it.

**Comment by lsowen** [comment]
I installed the v1.5.0 rc from https://test.docker.com/builds/Linux/x86_64/docker-1.5.0, and it looks like that does fix the issue.  It still tries to hit ``/v2/`` first, but handles receiving the HTTP 401 response correctly, and falls back to the ``/v1/`` endpoint.

Thanks for your help!
