### ISSUE TITLE
.dockerignore doesn't work when ADD all files

### ISSUE THREAD

**Issue by tobegit3hub** [docker/docker#10262]
We have add `.git` in `.dockerignore` but the container has added the `.git` files.

Related to https://github.com/tobegit3hub/pirate/issues/29 and http://stackoverflow.com/questions/28079872/how-to-add-all-files-directories-except-hidden-directory-like-git-in-dockerfile .

**Comment by duglin** [comment]
It appears to work for me.  Here are my steps:

mkdir .foo
echo foo > .foo/foo
echo .foo > .dockerignore
echo FROM ubuntu > Dockerfile
echo ADD . /tmp >> Dockerfile
echo RUN ls -la /tmp >> Dockerfile
docker build .

and it shows that .foo isn't in the /tmp dir.

If this isn't your scenario, can you show me the exact steps I need to take to reproduce it?

**Comment by tobegit3hub** [comment]
It should work because this is the meaning of `.dockerignore`. You can try `docker run -i -t  tobegit3hub/pirate /bin/bash` and you may find the .git files in `/go/src/github.com/tobegit3hub/pirate/`. But we actually add it in [.dockerignore](https://github.com/tobegit3hub/pirate/blob/master/.dockerignore#L1).

**Comment by LK4D4** [comment]
@duglin The problem can be in a way that hub builds images. Because for build endpoint in API it is possible to specify just git url in `remote` parameter, but client will clone this url before sending to daemon.
@tobegit3hub Could you pls try to build your image locally and check for `.git`?

**Comment by tobegit3hub** [comment]
Wow, it works and no `.git` in the container. @larrycai you can confirm this.

Thanks @LK4D4 and we should let others know about this although it's not a big deal.

**Comment by LK4D4** [comment]
@tobegit3hub Actually I think that it was fixed in master, by @duglin probably
