### ISSUE TITLE
docker build should allow for force download of dependent images

### ISSUE THREAD

**Issue by jchauncey** [docker/docker#10279]
So I have a java image I tagged jre8 that is hosted in our quay.io registry. A few days ago I had to update this image and I published a new version tagged again as jre8. When other teams at my company attempt to build their application image they get the old jre8 image instead of the new one since that is what exists on their CI server. 

It would be nice if we could pass in an argument (or use --no-cache) to force pull new dependent images during the build phase.

**Comment by cpuguy83** [comment]
On master build has a `--pull` flag, which will have it re-pull the FROM image for you.
This should be in 1.5, 1st week of February.

You can grab the master binary here: https://master.dockerproject.com

Closing since this is in!  Thanks for submitting!

**Comment by jchauncey** [comment]
hah! thats awesome thanks =)
