### ISSUE TITLE
docker documentation incorrectly indicates ability to set volumes with start command

### ISSUE THREAD

**Issue by shapiroj** [docker/docker#10278]
https://docs.docker.com/reference/commandline/cli/#create
"Note that volumes set by create may be over-ridden by options set with start."

It does not appear possible to set a volume option in the start command.

**Comment by cpuguy83** [comment]
@shapiroj This is a bug which, I believe, is fixed on master.

**Comment by SvenDowideit** [comment]
@cpuguy83 perhaps not:

```
docker@boot2docker:~/test$ docker start --help

Usage: docker start [OPTIONS] CONTAINER [CONTAINER...]

Restart a stopped container

  -a, --attach=false         Attach container's STDOUT and STDERR and forward al
l signals to the process
  --help=false               Print usage
  -i, --interactive=false    Attach container's STDIN
docker@boot2docker:~/test$ docker version
Client version: 1.5.0-rc3
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): c02092d
OS/Arch (client): linux/amd64
Server version: 1.5.0-rc3
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): c02092d
```

**Comment by cpuguy83** [comment]
@SvenDowideit The API start, not the CLI start :)

**Comment by tiborvass** [comment]
@cpuguy83 @SvenDowideit this is super confusing. What does `Note that volumes set by create may be over-ridden by options set with start` mean?

**Comment by cpuguy83** [comment]
It means that the api start lets you override existing volume settings.

**Comment by tiborvass** [comment]
@cpuguy83 except the documentation is about cli.

**Comment by cpuguy83** [comment]
Yes, someone asked me to put it in here I believe.

**Comment by tiborvass** [comment]
A sentence mentioning `start` in the cli docs, that does not clarify it's talking about the API, is very confusing.

**Comment by cpuguy83** [comment]
Here it is: #9519
