### ISSUE TITLE
Can't connect to index.docker.io

### ISSUE THREAD

**Issue by metakeule** [docker/docker#10287]
Description of problem:

Timeouts when trying to use docker registry

`docker version`:

     Client version: 1.3.3
     Client API version: 1.15
     Go version (client): go1.3.3
     Git commit (client): d344625
     OS/Arch (client): linux/amd64
     Server version: 1.3.3
     Server API version: 1.15
     Go version (server): go1.3.3
     Git commit (server): d344625

`docker info`:

     Containers: 7
     Images: 56
     Storage Driver: aufs
      Root Dir: /home/var/lib/docker/aufs
      Dirs: 71
     Execution Driver: native-0.2
     Kernel Version: 3.16.0-4-amd64
     Operating System: Debian GNU/Linux 8 (jessie)
     WARNING: No memory limit support
     WARNING: No swap limit support

`uname -a`:

      Linux tingpad 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt2-1 (2014-12-08) x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):

physical

How reproducible:

`docker login` results in `Post https://index.docker.io/v1/users/: dial tcp 54.224.119.89:443: i/o timeout`

`docker built -t ....` also results in https://index.docker.io/v1 timeouts.

Additional info:

Any access to `index.docker.io` results in a timeout (using no proxy). I wonder if the index
domain has changed and somehow docker still wants to use an old domain?

(can't ping 54.224.119.89 nor index.docker.io)

I am located in Germany.

Also tried docker 1.4.1 didn't also work. Had no problems with older versions of docker (1.1)

**Comment by tiborvass** [comment]
@metakeule Hi, sorry for the inconvenience! It's a known issue and you can follow the status at https://status.docker.com/

For future support on the Hub, please send an email to support@docker.com

Thanks!

**Comment by metakeule** [comment]
Was an issue with my dns server. Sorry for the hassle.

**Comment by shin-** [comment]
@tiborvass Separate issue.

It seems like your DNS cache is outdated. index.docker.io works fine

**Comment by tiborvass** [comment]
@shin- oh sorry about that! I also checked #docker IRC quickly and saw it mentioned. Must have been the builds then.
@metakeule glad you figured it out!
