### ISSUE TITLE
docker/pkg/system/meminfo_linux_test.go references deleted `units` package

### ISSUE THREAD

**Issue by jaytaylor** [docker/docker#10284]
docker/pkg/system/meminfo_linux_test.go references docker/pkg/units:

    "github.com/docker/docker/pkg/units"

https://github.com/docker/docker/blob/master/pkg/system/meminfo_linux_test.go#L7

But the `units` package not longer exists anywhere in docker master.

What is going on here?

**Comment by jfrazelle** [comment]
It lives https://github.com/docker/docker/tree/master/pkg/units

**Comment by jfrazelle** [comment]
So I think this must be however you are compiling :)

**Comment by jaytaylor** [comment]
Weird..something must have gone wrong when I `go get`ted https://github.com/fsouza/go-dockerclient.  I will close this.

Thanks for the quick response!
