### ISSUE TITLE
Local "latest" image is always overwritten by registry "latest" on pull

### ISSUE THREAD

**Issue by claesb** [docker/docker#10291]
If you push an image to docker hub with tag :latest. Then you make a small change and rebuild your image with :latest tag.
At this point I would assume my local repository has the latest version of :latest.
But if you now go ahead with a docker pull :latest the server will replace :latest in your local repository with the 'old' version from docker hub.

**Comment by thaJeztah** [comment]
@dmp42 thinking out loud here, but could this be related with the issues earlier today (docker registry automated builds creating the wrong tags?)

**Comment by dmp42** [comment]
@thaJeztah I'm not aware of today issues.
Now unless I'm mistaken, what is described here though admittedly confusing has been the default behavior forever - correct?

**Comment by thaJeztah** [comment]
@dmp42 oh, so sorry, I read the issue incorrect; I interpreted as "pull replaces local image with old *pushed* version, not the latest push"

I think this is the intended behavior yes; doing `docker pull` should pull the latest version from the registry (hub). The registry is considered the "truth" here; to make sure you have the latest version of (official) images, not a modified local version.

**Comment by claesb** [comment]
Ok then I know it is 'intended', but I still find it unintuitive. Other version control systems would object before overwriting local data with older data from server.

**Comment by thaJeztah** [comment]
Yes, I understand that; so basically, it should check if the local "created" time is more recent than the image on the registry, which could be problematic if time-zones between your local machine and the registry don't match and you're pulling an image that's not created on your local machine.

Note that `docker pull` will not *overwrite* your local image, it will "untag" it (i.e. remove the name and  `:latest` tag from the old image and put it on the new one)

For example; 

```bash
# Get the full Id of the old image;
$ docker inspect -f "{{ .Id }}" ubuntu:latest
# 5506de2b643be1e6febbf3b8a240760c6843244c41e12aa2f60ccbb7153d17f5

# Update the image;
$ docker pull ubuntu:latest

# Verify that the Id was changed after updating the image;
$ docker inspect -f "{{ .Id }}" ubuntu:latest
# b39b81afc8cae27d6fc7ea89584bad5e0ba792127597d02425eaee9f3aaaa462

# But the old image is still there. You need the Id though, to access it;
docker run --rm 5506de2b643be1e6febbf3b8a240760c6843244c41e12aa2f60ccbb7153d17f5 echo "hello world from the old image"
# hello world from the old image
```

**Comment by unclejack** [comment]
@claesb Here are some best practices tips for various workflows which help with having more predictable tags:
1. images built on the local host should not have the name of a repository you pull from (e.g. mycoolapp on the local server and example/mycoolapp when tagging for push), build locally to a tag and tag to the repo name only for pushing
2. if you want predictable tags for images kept locally, you can have multiple repositories to which you add images (e.g.: ubuntu:latest is the official images, you can pull it and tag it as ubuntu-production:27012015). If you also want these on the Hub or on a private registry, you can create your own repository to share the images in an environment.

There's a valid use case for pulling an image and overwriting the local ones: making sure everything is consistent with the remote server and not changed locally (e.g.: I want to be sure I've got ubuntu:latest and not something some tool accidentally tagged as `ubuntu:latest`).

We could also implement a flag for `docker pull` to ensure an image is pulled only if it's newer than the local image, but that needs a longer discussion.

**Comment by claesb** [comment]
This makes sense, good approaches @unclejack .

This was probably a corner case on my part, when on the subject of flags is there going to be a --pull flag on run to ensure a server check before starting?

**Comment by unclejack** [comment]
@claesb There isn't a `--pull` flag on run, but we've got one on `docker build`. I don't see why having one on run would hurt.

**Comment by jfrazelle** [comment]
since we already have a proposal for pull on run and it looks like your other issue was handled i think this can be closed see https://github.com/docker/docker/issues/10693

**Comment by orodbhen** [comment]
This all seems very good to use different tags locally when you're doing everything manually from the command line. But what about when you're scripting with the Python API? 

For example, I have a Python tool that runs our software in Docker, and checks for image updates before performing certain operations. It's supposed to use an image with a certain tag. So if I'm changing the image locally, and want to test it, I need to use a different tag. But my tool is looking for the original tag.

Sure, there are things I can do in my script to work around this, but this seem like very bizarre behavior to me, considering `docker pull` appears to be modeled after git. A lot of developers are going to find this behavior unexpected and awkward. In other words, it's a "gotcha." It's not what you would naturally expect after having used similar tools, e.g. git, rsync, etc. It goes against the whole idea of versioning and file differentials. 

I don't see any logical reason why overwriting something newer with something older should be the default. It should be something you force with a specific option flag.
