### ISSUE TITLE
Docker needs real bridge networking management

### ISSUE THREAD

**Issue by jberkus** [docker/docker#10307]
There are already quite a number of issues related to this (listed below), to the point where I'm creating a new meta-issue: we need a bridge management API and commands with clear functions and docs.  The way it stands today, either your Docker bridge networking works automatically or it doesn't work at all, and if it doesn't it's not fixable short of hacking the source.  

I recently experienced this at LinuxConf.AU using Docker 1.4.1.   While 172.* networks are not frequently used in the USA, they are the default for internal corporate networks in Australia, so Docker's bridge network conflicted with the conference network, preventing the Dockers I intended to do demos on from reaching the internet.  I then wasted an entire day trying to change the default bridge network to a different subnet -- with the help of a Linux networking expert -- without success.  While the --bid switch does allow you to change the bridge network, for example, containers you start don't recognize the change, and Docker doesn't actually set up the new bridge on the host (you have to do that entirely manually).   As you might imagine, this has been a significant inhibitor to Docker adoption in AU/NZ.

I could file a set of minor issues with each step of trying to fix the Docker bridge that failed, but that would be missing the point; the core issue is that Docker assumes that its default bridge setup will simply work, and no real management tools to change that network exist; if you have to change bridges, you have to graduate to Docker hacker first.  This is wrong.

Related issues:
https://github.com/docker/docker/issues/9986
https://github.com/docker/docker/issues/9729
https://github.com/docker/docker/issues/10096
https://github.com/docker/docker/issues/6442
https://github.com/docker/docker/issues/6155
https://github.com/docker/docker/issues/3909

**Comment by phemmer** [comment]
This works perfectly fine for me:

Here I have a host on a `172.17.0.0/16` network:
```
# ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:AC:11:00:26  
          inet addr:172.17.0.38  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST RUNNING  MTU:1500  Metric:1
          RX packets:5 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:418 (418.0 B)  TX bytes:508 (508.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

Now I start docker with `--bip`:
```
# docker -d --bip 192.168.0.1/16
INFO[0000] +job serveapi(unix:///var/run/docker.sock)   
INFO[0000] +job init_networkdriver()                    
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
INFO[0000] -job init_networkdriver() = OK (0)           
INFO[0000] Loading containers: start.                   

INFO[0000] Loading containers: done.                    
INFO[0000] docker daemon: 1.4.1 5bc2ff8; execdriver: native-0.2; graphdriver: btrfs 
INFO[0000] +job acceptconnections()                     
INFO[0000] -job acceptconnections() = OK (0)    
```

Now in another terminal I do `ifconfig`:
```
docker0   Link encap:Ethernet  HWaddr 56:84:7A:FE:97:99  
          inet addr:192.168.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

eth0      Link encap:Ethernet  HWaddr 02:42:AC:11:00:26  
          inet addr:172.17.0.38  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST RUNNING  MTU:1500  Metric:1
          RX packets:8 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:648 (648.0 B)  TX bytes:648 (648.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

`docker0` was automatically created.
Some tests to verify it works:
```
# docker run -ti busybox ifconfig eth0
eth0      Link encap:Ethernet  HWaddr 02:42:C0:A8:00:03  
          inet addr:192.168.0.3  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST  MTU:1500  Metric:1
          RX packets:1 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:90 (90.0 B)  TX bytes:90 (90.0 B)

# docker run -ti busybox ping -c 2 google.com
PING google.com (173.194.204.139): 56 data bytes
64 bytes from 173.194.204.139: seq=0 ttl=38 time=38.891 ms
64 bytes from 173.194.204.139: seq=1 ttl=38 time=43.370 ms

--- google.com ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 38.891/41.130/43.370 ms
```

**Comment by cpuguy83** [comment]
@jberkus Docker **_does_** setup the new bridge for you, but you have to manually remove any pre-existing the docker0 interface (like from the original time you spun up the docker daemon).
And you can also tell it to use an existing bridge.

**Comment by cpuguy83** [comment]
Also, I think we can close this issue given it's not adding (no offense!) to the existing networking proposals.

**Comment by jberkus** [comment]
I thought this was closed a while ago.  Not sure why it's still open.
