### ISSUE TITLE
Using a --pid=host container results in unstoppable container

### ISSUE THREAD

**Issue by sdake** [docker/docker#10303]
I have been working on a OpenStack Nova compute node container set.  It involves at the moment a nova-network container, and a nova-compute container.  The nova-compute container runs libvirt and nova-compute.  I probably will split these into separate containers at some point, if that would work.

I recently introduced the --pid=host flag to my start script for docker and it results in an unkillable container.  docker stop blocks permanently.  pressing ctrl-c on the docker cli process and running docker stop again result in errors about processes not found.

The worst part is processes in the original container are leaked into the operating system permanently.

To run this container for debugging, it is necessary to stop libvirt in your host OS (because the container will want  to run libvirt in your host OS).

The start command is here:
https://github.com/sdake/compute-upgrade/blob/master/tools/start-compute#L29

**Comment by sdake** [comment]
The full set of processes in the container
odd that virtlockd/libvirt has nova-compute as a parent
[root@minime cgroup]# ps -ef | grep 6597
root      6597   859  2 09:11 ?        00:00:00 /usr/bin/python /usr/bin/nova-compute
root      6760  6597  0 09:11 ?        00:00:00 /usr/sbin/virtlockd
root      6765  6597  0 09:11 ?        00:00:00 /usr/sbin/libvirtd
root      6900  6282  0 09:12 pts/0    00:00:00 grep --color=auto 6597

The full set of processes with docker as a parent
[root@minime cgroup]# ps -ef | grep 859
root       859     1  0 08:16 ?        00:00:00 /usr/bin/docker -d --selinux-enabled -H fd://
root      6542   859  0 09:11 ?        00:00:00 /usr/bin/python /usr/bin/nova-network
root      6597   859  0 09:11 ?        00:00:00 /usr/bin/python /usr/bin/nova-compute

After a docker stop operation on the nova-compute container (PID 6597) the state of the system is:
root      6765     1  0 09:11 ?        00:00:00 /usr/sbin/libvirtd
root      6760     1  0 09:11 ?        00:00:00 /usr/sbin/virtlockd

On a docker stop, the host system's systemd is reparenting libvirtd and virtlockd to PID 1 (systemd).  For some reason this is blocking docker stop from killing the processes.

**Comment by LK4D4** [comment]
@sdake Could you provide `docker version` and `docker info`. Also, do you use `docker exec`? Thanks!

**Comment by LK4D4** [comment]
I can confirm that this issue in latest master.

**Comment by LK4D4** [comment]
@sdake Hmmm, this is blocking docker stop because of container `cgroups`, which can't be deleted. Fun that I can't delete them even after docker stopped and libvirt killed.

**Comment by crosbymichael** [comment]
@sdake what happens if you run docker kill?

**Comment by sdake** [comment]
@crosbymichael 
slightly different behavior
[root@minime tools]# docker kill 1e332b49962f
Error response from daemon: Cannot kill container 1e332b49962f: no such process
FATA[0010] Error: failed to kill one or more containers 

processes still remain after kill:

[root@minime tools]# ps -ef | grep libvirt
root      1955     1  0 11:46 ?        00:00:00 /usr/sbin/libvirtd

**Comment by sdake** [comment]
This seems to fix it, but wouldn't work for the normal case where --pid=host is called I suspect.

Fedora's kernel is reparenting "faster" in some way to PID1 on process kill.  When the reparent happens, /proc/self/pid where pid is a child process in the container disappears from the pid address space because it has been reparented.  This causes the below code to fail to access key data and return errors, blocking the stop.  Workaround is to just access /proc/pid directly.

http://paste.fedoraproject.org/173764/43119142

**Comment by sdake** [comment]
Dan Walsh suggested a change such as:
http://paste.fedoraproject.org/173792/45803142

Which seems to fix the problem.  No idea why.

**Comment by jfrazelle** [comment]
Weird that it would come down to something with selinux?

**Comment by eparis** [comment]
I'm going to say "that patch is wrong".  Maybe it works around a problem, but it is wrong.  period full stop.  (And I'm the SELinux kernel and userspace libraries maintainer)

I'm starting to play with your reproducer...

**Comment by jfrazelle** [comment]
Awesome thanks so much for the feedback and help

**Comment by LK4D4** [comment]
We found something on our side actually. That `exec.Cmd.Wait` is not exiting with your start script + pid namespace even if process died and that's weird :/

**Comment by sdake** [comment]
@LK4D4 this is likely because libvirtd and virtlockd are still running in the system.  Wait will wait until those processes exit.

**Comment by LK4D4** [comment]
@sdake But why? And how can I kill them?

**Comment by sdake** [comment]
@eparis yup the fact that I don't understand why it seems to fix the problem is a clear sign we haven't found a root cause.

I did want to report I ran docker via strace -f with master and found that an ENOENT was returned during the stop operation via an open syscall directed at /proc/self/tasks/#/attr/exec which likely jammed up the rest of the stop operation.

**Comment by LK4D4** [comment]
Fun thing, Wait haging even after killing all processes in cgroup :) Seems like golang bug.

**Comment by sdake** [comment]
@LK4D4 I killed them via a ssh root shell into my machine - eg killall -15 libvirtd

**Comment by eparis** [comment]
adding some log messages, we never end up in killAllPids()   which I thought was supposed to happen

**Comment by crosbymichael** [comment]
We are tracking this down to something around:
https://github.com/golang/go/issues/7990

**Comment by jfrazelle** [comment]
The rabbit hole is deep with this one.

**Comment by sdake** [comment]
I have confirmed that Dan's cherrypicked repo of LK4D4's patch fixes the problem.

Thanks for the responsive attention!

Regards
-steve
