### ISSUE TITLE
Copied files contains ^M after each line

### ISSUE THREAD

**Issue by noonedoes** [docker/docker#10314]
docker version:
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8

using the COPY command, I defined the following file to be copied over to the container:

COPY /src/start $HOME/

The start file is a bash script and is fine on the creating filesystem.  When I VI the file, at the end of each line there is a ^M character.

#!/bin/bash^M
echo $HOSTNAME^M

This happens for individual files copied over and for entire directories.

**Comment by jfrazelle** [comment]
seems like your file might have some sort of non utf encoding in it or something?

**Comment by noonedoes** [comment]
Hello jfrazelle,

Thanks for the quick response.

When I VI the file from the ubuntu machine used to run the docker build command, I don't see anything extra characters within it.  When I run file -bi on the file, it comes back as:

text/x-shellscript; charset=us-ascii

Should it be something else?

**Comment by jfrazelle** [comment]
maybe you need to set utf encoding in the container?

**Comment by noonedoes** [comment]
Hello Jfrazelle,

Thanks for the help.  I resolved the issue.  The script was originally created on a windows system and uploaded to ubuntu.  I had to run dos2unix on the file and afterwards it resolved the issue.

Thanks for the assistance.

**Comment by jfrazelle** [comment]
Oh great good to hear :)
