### ISSUE TITLE
Pushing reports wrong size

### ISSUE THREAD

**Issue by dmp42** [docker/docker#10312]
Push reports total uploaded size to be bigger than the total size of the layer.

docker-1.5RC

![screen shot 2015-01-23 at 1 22 26 pm](https://cloud.githubusercontent.com/assets/332946/5882955/f546ccf2-a302-11e4-971e-c33764c4527a.png)

**Comment by icecrime** [comment]
Can we reproduce this with #10327? Is it related?

**Comment by dmcgowan** [comment]
Not related, the fix for this will be to do local file caching like V1 does.
