### ISSUE TITLE
Overlay does not work with zfs backed /var/lib/docker

### ISSUE THREAD

**Issue by cldfzn** [docker/docker#10313]
Seems to be the same issue as: #9820 

I know the resolution was to add a message, may want to also add a message for this scenario though I don't know how popular ZFS is on linux.

Containers: 0
Images: 5
Storage Driver: overlay
Execution Driver: native-0.2
Kernel Version: 3.18.2-2-ARCH
Operating System: Arch Linux
CPUs: 8
Total Memory: 23.55 GiB
ID: CFFY:XV6I:5J5P:7MAN:YGGK:E5T2:W23N:H72E:D43D:ZXCK:IUDI:BNI2
WARNING: No swap limit support

INFO[0113] -job pull(ubuntu, latest) = OK (0)
DEBU[0125] Calling POST /containers/create
INFO[0125] POST /v1.16/containers/create
INFO[0125] +job create()
invalid argument
INFO[0126] -job create() = ERR (1)
ERRO[0126] Handler for POST /containers/create returned error: invalid argument
ERRO[0126] HTTP Error: statusCode=500 invalid argument

**Comment by tianon** [comment]
Maybe we should consider doing whitelisting in these drivers instead.

**Comment by jfrazelle** [comment]
We had talked about the on the original PR #9834
