### ISSUE TITLE
[V2 Registry] Layers don't show as complete when pushing

### ISSUE THREAD

**Issue by nathanleclaire** [docker/docker#10325]
As requested, cc @icecrime @dmp42 

Steps to repro:

1. Push image with layers that are not present in the registry to V2 registry

Essentially, the output of "pushed" layers does not say as so.  They appear to hang at "full" even though they are done.  This is a regression.  Command seems to work and exit normally.

Screenshot soon

**Comment by nathanleclaire** [comment]
![screen shot 2015-01-23 at 3 40 02 pm](https://cloud.githubusercontent.com/assets/1476820/5884826/c65892b2-a317-11e4-9a1b-e05e137f5aa4.png)

**Comment by dmcgowan** [comment]
Caused by #10244, backing out the deferred progress reader close
