### ISSUE TITLE
Passing command-line arguments to the CMD?

### ISSUE THREAD

**Issue by rileylark** [docker/docker#10334]
For example, I'd like to pass `--prefix=/jenkins` to the `jenkins` container when I start it. Something like:

`docker run jenkins --prefix=/jenkins` would be awesome, but of course it would be hard to disambiguate between args meant for docker and args meant for jenkins.

@erikh and I discussed this briefly in IRC and he asked me to file this issue.

**Comment by erikh** [comment]
I was thinking we could use a classic unix idiom of `--` to signify the start of arguments without a CMD. This could only be processed if it were the first argument to RunConfig.Cmd (and similar if necessary)

Making these notes here so I know to tackle this ticket later. :)

**Comment by rileylark** [comment]
In a surprise twist, `docker run jenkins --prefix=/jenkins` actually works perfectly. Feel free to close @erikh
