### ISSUE TITLE
Notify / confirm before saving credentials

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#10338]
As discussed in https://github.com/docker/docker/issues/10318#issuecomment-71340996 and https://github.com/docker/docker/issues/10318#issuecomment-71378637

Docker currently stores user-credentials in a `.dockercfg` file without notifying the user, and without offering an option to *not* store the credentials. Registry V2 will use different mechanisms for authentication (token based / public key identity), but is not yet in place.

For the 1.5 release (I know it's in freeze); I suggest to (at least) notify users that their credentials will be stored. If possible, offering the user an option to *not* store the credentials.

As an example, this is what SVN will output;

```
ATTENTION! Your password for authentication realm:

http://domainname.com:80 “domainname.com”

can only be stored to disk unencrypted! You are advised to configure your system 
so that Subversion can store passwords encrypted, if possible. See the 
documentation for details. You can avoid future appearances of this warning by 
setting the value of the 'store-plaintext-passwords' option to either 'yes' 
or 'no' in '/root/.subversion/servers'.

Store password unencrypted (yes/no)? no
```

The warning should also mention *where* the credentials are stored, allowing users to remove the stored credentials afterwards.

An additional option was mentioned by @dmcgowan that I would like to be considered;

> Another possible short term solution is now that we have the public key identity of the client, we can use the key pair to encrypt the dockercfg file. It is worthy of a proposal.

**Comment by thaJeztah** [comment]
/ping @dmcgowan @dmp42 @icecrime @crosbymichael @shykes (and perhaps others)

**Comment by tiborvass** [comment]
I'm +1 for the little prompt, shouldn't be too hard and is low risk.

I'm -1 on encrypting the file for the 1.5 release: not enough time to test corner cases.

**Comment by ewindisch** [comment]
I believe better awareness of this issue is warranted and appropriate. I'm okay with a warning message.

**Comment by thaJeztah** [comment]
I mentioned the encryption for completeness, but agree that there's not enough time to test before the 1.5 release, unless this issue is reason enough to uphold 1.5.

Leaving out the encryption part wouldn't make docker any less secure than it is right now, other than that the original report may have attracted some attention.

One thing I'm not sure of; 
Is it actually possible to have the user *decide* whether or not the credentials should be stored? AFAIK, the credentials have the be sent with *each* request, so *not* storing them would make it impossible to push/pull an image (because that involves a number of requests), unless they are kept in memory.

If it's not possible to *not* store the credentials, then just a warning is the only option (for now).

**Comment by dmcgowan** [comment]
+1 for user messaging

Addressing the encryption portion, it would not be valuable for 1.5 anyway.  Until we get full support for an agent as @ewindisch mentioned in the original issue, there is no additional security added by encryption with the encryption key as vulnerable as the original file.

**Comment by icecrime** [comment]
Works for me :+1: Please add the PR to the 1.5.0 milestone when it's ready!

**Comment by thaJeztah** [comment]
Just for good measures;

- I reckon it will be just a *message*, no *yes/no* confirmation?
- @tiborvass will you create the PR? I'm not "there" yet coding in Go, and don't want to uphold the release :)

**Comment by acbodine** [comment]
Anyone working on this PR?

**Comment by thaJeztah** [comment]
@acbodine I don't think so, but perhaps @tiborvass is working on something, I saw something mentioned wrt login changes for 1.5.1 on IRC, but not sure that is related to this.

**Comment by tiborvass** [comment]
Sorry i forgot about this... :( I could do this for 1.5.1 unless @acbodine wants to take a stab at it. If you do so, let me know your IRC handle :)

**Comment by acbodine** [comment]
@tiborvass @thaJeztah I would be happy to do this. IRC handle is acbodine .... super original :)

**Comment by duglin** [comment]
I'm trying to understand this issue.  Why do we want to prompt the user?  Won't that kill doing this in a script?  At least forcing something like: `yes | docker ...`   
And as for a warning, I'd want the option to hide it behind a -q type of flag.
But, to be honest, I'm a bit confused as to why this is suddenly an issue?

**Comment by duglin** [comment]
Let me clarify, yes I understand that storing passwords in clear or base64 is bad.  But I'm not sure all of these warnings and prompts really does any good except annoy people even more.  Seems to me that waiting for the real solution (token/... stuff) would be better.  But I'm probably missing something.

**Comment by thaJeztah** [comment]
@duglin yes, a permanent solution is certainly prefered, however, because that is not possible directly and depends (afaik) on changes in the registry, *notifying* the user is a stopgap fix for the time being. Notifying the user enables them to take the appropriate actions, if desired.

As mentioned earlier, I don't know if a "prompt" `[Y/n]` is actually possible, so just a notification may be sufficient, and would be fine with me.

**Comment by duglin** [comment]
If we do end up with a warning, I would suggest that it include some advice about using "docker logout" to delete the file once they're done.

**Comment by thaJeztah** [comment]
> I would suggest that it include some advice about using "docker logout" to delete the file once they're done.

+1 yes, that would be good.

**Comment by fredlf** [comment]
Seems to me it might help to also strengthen the warning here: http://docs.docker.com/userguide/dockerrepos/#account-creation-and-login and to encourage the user to use `logout` if appropriate. What do you guys think?

**Comment by thaJeztah** [comment]
@fredlf there was some discussion about that in the PR; https://github.com/docker/docker/issues/10620 perhaps you are able to provide a proper message that clearly communicates the intent?

**Comment by a-rodin** [comment]
Shouldn't the warning be show _before_ the password is entered, not after?

Showing it before the password prompt would make it possible to the user to decide whether to enter the password or not in the first place. And right now the warning is shown after the password is stored and potentially compromised.

**Comment by KyleFromKitware** [comment]
> Shouldn't the warning be show _before_ the password is entered, not after?
> 
> Showing it before the password prompt would make it possible to the user to decide whether to enter the password or not in the first place. And right now the warning is shown after the password is stored and potentially compromised.

I wholeheartedly agree. I received the warning message, but by then it was too late - my password had already been stored in plaintext on my hard disk. I had to `shred` the file to undo the damage. If it had warned me *before* asking for my password, I could have avoided this situation.

Please consider fixing this warning for security-minded folks.
