### ISSUE TITLE
docker overlayfs support fails to load on kernels < linux 3.18-rc6 (eg. stock Ubuntu Trusty) even if overlayfs is present

### ISSUE THREAD

**Issue by wuxxin** [docker/docker#10353]
standard ubuntu trusty 14.04 has overlayfs support, with the standard 3.13 kernel and the utopic backport kernel 3.16 (which is available in trusty).

* affected:
  * Docker version 1.4.1, build "5bc2ff8" from https://get.docker.io/ubuntu
* change that caused the regression: 
  * Commit c57317893a743720a241ae328d1bdf7bd02b1fea (30 Nov 2014) changed the probing of overlayfs to overlay, which fails on kernels < 3.18 
* reproduction:
   * install standard ubuntu trusty, set docker to use overlay
* expected:
  * look for the running version of linux, and change name of overlayfs according to kernel version
    (overlayfs < 3.18-rc6 > overlay)
* rationale:
   * by supporting stock ubuntu  lts and stock kernels < 3.18 for testing docker on overlayfs, a lot of more people and machines are available for testing the overlay driver with docker.

```
#more /proc/version
Linux version 3.16.0-29-generic (buildd@brownie) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #39-Ubuntu SMP Tue Dec 16 20:54:13 UTC 2014

#modinfo overlayfs
filename:       /lib/modules/3.16.0-29-generic/kernel/fs/overlayfs/overlayfs.ko
alias:          fs-overlayfs
license:        GPL
description:    Overlay filesystem
author:         Miklos Szeredi <miklos@szeredi.hu>
srcversion:     FB5EA564A90C75C37614C6F
depends:        
intree:         Y
vermagic:       3.16.0-29-generic SMP mod_unload modversions 
signer:         Magrathea: Glacier signing key
sig_key:        33:94:AB:B0:79:A2:1B:E0:61:0B:29:4D:4D:01:C0:F6:61:BB:69:92
sig_hashalgo:   sha512

#modprobe overlayfs
#more /proc/filesystems | grep overlay
nodev   overlayfs

#docker --storage-driver=overlay -d
INFO[0000] +job serveapi(unix:///var/run/docker.sock)   
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
ERRO[0000] 'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded. 
FATA[0000] driver not supported
```

**Comment by jfrazelle** [comment]
So this is a 3.16 kernel with backports of overlayfs?

**Comment by jfrazelle** [comment]
If it is not, and has the old `overlayfs` support not `overlay` which was merged in 3.18 kernels, it is not supported because it does not have the full implementation of `overlay` which is why they (the kernel) changed the name from `overlayfs` to `overlay`

**Comment by tianon** [comment]
It looks like they've actually been bundling `overlayfs` since at least as far back as this ancient version:
```
linux (3.0.0-7.8) oneiric; urgency=low
```

http://changelogs.ubuntu.com/changelogs/pool/main/l/linux-lts-utopic/linux-lts-utopic_3.16.0-29.39~14.04.1/changelog

**Comment by wuxxin** [comment]
the change in name is more a cosmetic reason, but for docker and overlayfs, it worked until the change in name, because the whole overlayfs stuff was written and tested with the overlayfs not part of the kernel, so it just breaks because of the upcoming name change.

**Comment by jfrazelle** [comment]
`overlayfs` is the "legacy overlay filesystem"
`overlay` is the latest

We support `overlay`.

**Comment by wuxxin** [comment]
@jfrazelle thank you for your reasoning, i didn't mean to interfere on non technical reasons, i will try to backport the new overlay fs to the running old kernel.

**Comment by gdm85** [comment]
I am going to test Ubuntu's 3.16.0-29 and docker 1.4.1 (https://github.com/gdm85/docker/commit/6902cdbec63f1f19fc349677d44e54da0bc93fcc); I agree that the versions < 3.16 should be kept away, but it is not yet clear to me if Docker can't work with the most recent one.

**Comment by baptistedonaux** [comment]
@jfrazelle For Debian Jessie (current kernel 3.16), a backport must be released ?
