### ISSUE TITLE
Cannot create symlinks into Volume

### ISSUE THREAD

**Issue by deiga** [docker/docker#10350]
Hi,

I have a Dockerfile which is based on `dockerfile/nginx` and I try to make a symlink
`RUN ln -s /data/frontend/app /var/www/html/`

But the symlink never gets created. Then when I run the container I can manually create the symlink without problems.
I suspect that `/var/www/html/` being a VOLUME ahas something to do with it.

**Comment by phemmer** [comment]
Yes, this has to do with it being a volume. From [the documentation](https://docs.docker.com/userguide/dockervolumes/#data-volumes):

> Changes to a data volume will not be included when you update an image

If you want to do this, your best bet is going to be to create an ENTRYPOINT script which creates the symlink when the container starts.

**Comment by cpuguy83** [comment]
Also, note that `dockerfile/nginx` is not official at all.
The official nginx image is called simply `nginx` and is actually maintained by Nginx Inc.

**Comment by AnthonyWC** [comment]
I think it'd be a good idea to throw an error (something like Error: Attempt to write to read-only VOLUME) during Dockerfile build instead of the current failing silently behavior.

**Comment by cpuguy83** [comment]
@AnthonyWC It's tricky. And I have tried to fix it multiple times (e.g. by not applying volumes until a build is done), but none have worked out to everyone's satisfaction.
I do know that some people take advantage of these build-volumes as a sort of disk-cache that doesn't persist to the image.... I'm not sure if we can really "fix" it at this point.
