### ISSUE TITLE
How to set env without Dockerfile

### ISSUE THREAD

**Issue by WuLonghui** [docker/docker#10379]
Hi,
Want to create a image by `docker commit`, but how to set env in the image, I only find Dockerfile can do it, any oher way?

Thanks in advance!

**Comment by stefan-it** [comment]
Hi,

you can use the `-e` switch in the `docker run` command to specify one or multiple environment variables (in the container), see [this](https://docs.docker.com/reference/run/#env-environment-variables) reference for more information :)

Stefan

**Comment by phemmer** [comment]
Just an FYI, general "how to" are best suited for the mailing list: https://groups.google.com/forum/#!forum/docker-user
