### ISSUE TITLE
docker pull for 2 images stalls

### ISSUE THREAD

**Issue by bobrik** [docker/docker#10378]
Imagine you have really bad internet connection, like we do. 14kbps to docker hub is really painful.

Run `docker pull` for some image in one terminal:

```
web381 ~ # docker pull bobrik/collectd-elasticsearch
Pulling repository bobrik/collectd-elasticsearch
c080dd4d5ac2: Pulling dependent layers
511136ea3c5a: Download complete
5bc37dc2dfba: Downloading [>                                                  ]   528 kB/67.48 MB 33m9s
```

Then run `docker pull` for completely independent image with 0 common layers in another terminal:

```
web381 ~ # time docker pull busybox
Pulling repository busybox
4986bf8c1536: Pulling dependent layers
```

Boom, it stalls! Now you are in the situation when you have to wait for the first image to download and that could take infinite amount of time. Until first image is downloaded, you cannot run anything that is now downloaded. Literally anything if you run everything in docker.

I actually waited for `scratch` to download:

```
web381 ~ # time docker pull scratch
Pulling repository scratch
511136ea3c5a: Download complete
Status: Image is up to date for scratch:latest

real	10m19.058s
user	0m0.010s
sys	0m0.000s
```

Mesos would kill my task 10 times for timing out. Not only this task, but any new task on this host.

```
web381 ~ # docker info
Containers: 3
Images: 41
Storage Driver: devicemapper
 Pool Name: docker-9:127-28311623-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 1.913 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 2.929 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.88 (2014-08-05)
Execution Driver: native-0.2
Kernel Version: 3.14.18-gentoo
Operating System: Gentoo/Linux
CPUs: 8
Total Memory: 7.791 GiB
Name: web381
ID: ISFY:2KV4:6HPK:Y3MD:LUCF:HKZN:LIRA:75ZN:MC35:FKE2:TBT4:EI7E
```

**Comment by termie** [comment]
-subscribe-

**Comment by LK4D4** [comment]
@stevvooe @aaronlehmann @dmcgowan do you know if it's still an issue?

**Comment by aaronlehmann** [comment]
No, this shouldn't be an issue anymore.

**Comment by geoidesic** [comment]
It's still an issue for me. Docker stalls and won't complete and if you cancel the pull and try again then it is permanently stalled.
