### ISSUE TITLE
Unable to push image

### ISSUE THREAD

**Issue by shubhamrajvanshi** [docker/docker#10375]
I am unable to push an image to repository from my windows docker vm . Getting a fatal error.
![image](https://cloud.githubusercontent.com/assets/7224484/5913995/4a164680-a5a2-11e4-80cc-1c20df0ea493.png)
I am sorry if I followed a wrong step as I have just started to work on it.

**Comment by dmp42** [comment]
The dns server pointed here is misbehaving.
Check your DNS resolution settings and/or restart boot2docker.
