### ISSUE TITLE
Markdown rendering on docker hub swallows spaces

### ISSUE THREAD

**Issue by JensPiegsa** [docker/docker#10377]
The HTML rendering of Markdown on the *Docker Hub Registry* swallows the space characters around the double-quotes in the following README.md snippet:
<pre>
Backup a database dump to the current directory on the host:

```sh
echo "postgres123" | sudo docker run -i --rm --link ocdb:ocdb -v $PWD:/tmp postgres:8 sh -c 'pg_dump -h ocdb -p $OCDB_PORT_5432_TCP_PORT -U postgres -F tar -v openclinica > /tmp/ocdb_pg_dump_$(date +%Y-%m-%d_%H-%M-%S).tar'
```
</pre>

If you leave out the language hint for syntax highlighting (sh) no error occurs.

**Comment by tianon** [comment]
For several more fun examples:
- https://registry.hub.docker.com/u/tianon/rawdns/
- https://registry.hub.docker.com/u/yosifkit/hello-world/ (cc @yosifkit)

**Comment by jfrazelle** [comment]
Hi @JensPiegsa would you mind submitting this to support@docker.com, then it will go to the right hands of the people to fix it :) but thank you! I do agree this is pretty weird, but technically not a bug with anything in this repo. I hope you understand.

**Comment by JensPiegsa** [comment]
Delivered. :-)

**Comment by abn** [comment]
@jfrazelle this seems to be still unresolved, see https://registry.hub.docker.com/u/cloudrouter/odl-fedora/

**Comment by thaJeztah** [comment]
@abn Docker Hub is not open source and not maintained here on GitHub, that's why this issue was closed. You can report this issue via support@docker.com to open a ticket.

**Comment by abn** [comment]
@thaJeztah done! Thanks.
