### ISSUE TITLE
validate input tarball when doing import

### ISSUE THREAD

**Issue by TomasTomecek** [docker/docker#10385]
Today I've accidentally used `docker import` instead of `docker load`. You can probably imagine what that means. It took me quite some time to figure out what's going on. At first I thought my tarball is corrupted, but then I realized I'm using wrong command.

Do you think it would make sense if docker CLI tried to validate a content of the tarfile when doing `import`? And if it's not valid FHS then maybe warn user.

**Comment by unclejack** [comment]
@TomasTomecek IMO, all we could is attempt to detect whether the tarball is a tarball `docker load` would accept.

**Comment by TomasTomecek** [comment]
makes sense to me

**Comment by runcom** [comment]
I'll gladly work on this if it's ok for you.

`docker load` would accept a tarball in which a `repositories` json file is found, I think making `docker import` checks for some mandatory file (or directory structure as @TomasTomecek said) would be better to maintain the same interface (accept well formed tars only)

**Comment by p4tin** [comment]
@runcom @unclejack  - Is this issue closed now?

**Comment by thaJeztah** [comment]
@p4tin looking at the associated PR, that was closed without merging, so I don't think this is fixed.

Do you have plans to work on this?

**Comment by p4tin** [comment]
Yes

**Comment by p4tin** [comment]
#dibs

**Comment by thaJeztah** [comment]
@runcom let us know if you're still working on cleaning up you original PR (but I think you're working on a lot of other PRs :smile:)

@p4tin also be sure to check https://github.com/docker/docker/issues/11564, the discussion/review on that PR may contain useful information

**Comment by runcom** [comment]
@thaJeztah @p4tin I'm not working on it anymore, feel free to have a go on this :)

**Comment by unclejack** [comment]
@p4tin and anyone interested in working on this, please discuss the design on this issue first.

**Comment by p4tin** [comment]
@thaJeztah + @unclejack - there were 2 issues you pointed out that I will be looking into...  1) was that the read stream was exhausted by checking the type of tarball and 2) was that conpressed streams were not being handled.

1) For problem #1 - If I am not mistaken the requirement is to give user a notice that this stream maybe handled better by load or import depending on the files in the tarball, so I intend in returning a value from the load/import that indicates this fact and print it out to the user after the stream has been handled - this way if it was better handled by load or import the user is aware that he used the wrong command and can try again.

2) I think that if I used the way I want to do it in #1 then compressed/non-compressed is unimportant.

As I am a complete newbie to both go and docker of course any suggestions are extremely welcome.

**Comment by runcom** [comment]
@p4tin thanks for working on this, my first attemp had some hints from @unclejack too - you could keep in mind while developing. Firstly, it's not about handling "better" but handling at all, meaning docker importing a docker save'ed image won't work and give misleading results. Also, at the beginning my attemp was to save the imported tarball in a temp file so it can be read multiple times (not the best way but worked) meaning you can easly handle a first stream read to determine if the stream is ok and then use it in the import. As @unclejack said to me another problem is also to determine the compression before reading the tar header (at which I failed lol). All of this, IIRC, can be done without actually extracting the compressed stream also.

**Comment by p4tin** [comment]
@runcom - Are you saying that if I create a tar with export the import of that tar will not work - cause I just did that and it was ok - then I tried to "load" it and got an error: "FATA[0000] Error response from daemon: open /mnt/sda1/var/lib/docker/tmp/docker-import-936240994/repo/bin/json: no such file or directory "

**Comment by ripcurld00d** [comment]
#dibs - may I try?

The question is whether there is a defined and restricted file structure, which the tar file must have, in both cases (import and load)?

Thanks.

**Comment by ripcurld00d** [comment]
@thaJeztah please close this as we decided this is not going to happen any time soon. :wink:

**Comment by unclejack** [comment]
@ripcurld00d Thanks!
