### ISSUE TITLE
`docker run` ignores connection timout, waits forever

### ISSUE THREAD

**Issue by grahamc** [docker/docker#10387]
I'm running a remote docker client. The client runs on Snap-CI.com and connects to an HTTPS (not unix socket) daemon on my internal network. When I do `docker run myimage`, eventually the process I'm running stops outputting content for several seconds to a minute. The connection from the docker client to server times out, but the client continues to wait for more incoming data for the remainder of my 2 hour command run time window.

I am able / willing to help provide any more information necessary, and would appreciate any suggested workarounds.

`docker info`:

```
Containers: 2
Images: 77
Storage Driver: btrfs
 Build Version: Btrfs v3.17.1
 Library Version: 101
Execution Driver: native-0.2
Kernel Version: 3.18.1
Operating System: CoreOS 557.0.0
CPUs: 2
Total Memory: 7.341 GiB
Name: ip-.....compute.internal
ID: JLB7:5HTL:UFJP:XMMB:KOYV:WQV4:TOWH:NUSA:UTLF:UQSX:NGPC:3ZNU
```

Relevant strace segment:

```
epoll_wait(4, {}, 128, 0)               = 0
futex(0x12a1110, FUTEX_WAIT, 0, NULL)   = 0
clock_gettime(CLOCK_MONOTONIC, {220, 782838425}) = 0
clock_gettime(CLOCK_MONOTONIC, {220, 783917080}) = 0
clock_gettime(CLOCK_MONOTONIC, {220, 783975383}) = 0
epoll_wait(4, {}, 128, 0)               = 0
futex(0x12a01b8, FUTEX_WAKE, 1)         = 1
futex(0x7fc625a78f60, FUTEX_WAKE, 1)    = 1
clock_gettime(CLOCK_MONOTONIC, {220, 784130813}) = 0
futex(0xc208066570, FUTEX_WAKE, 1)      = 1
clock_gettime(CLOCK_MONOTONIC, {220, 784647654}) = 0
futex(0x7fc625a78f60, FUTEX_WAIT, 0, {60, 0}) = -1 ETIMEDOUT (Connection timed out)
clock_gettime(CLOCK_MONOTONIC, {280, 784930779}) = 0
futex(0x12a01b8, FUTEX_WAKE, 1)         = 1
clock_gettime(CLOCK_MONOTONIC, {280, 785054256}) = 0
futex(0xc208066570, FUTEX_WAKE, 1)      = 1
clock_gettime(CLOCK_MONOTONIC, {280, 785127325}) = 0
futex(0x7fc625a78f60, FUTEX_WAIT, 0, {60, 0}) = -1 ETIMEDOUT (Connection timed out)
clock_gettime(CLOCK_MONOTONIC, {340, 785383741}) = 0
futex(0x12a01b8, FUTEX_WAKE, 1)         = 1
futex(0xc208066570, FUTEX_WAKE, 1)      = 1
futex(0x12a01b8, FUTEX_WAKE, 1)         = 1
clock_gettime(CLOCK_MONOTONIC, {340, 786775459}) = 0
futex(0xc208066570, FUTEX_WAKE, 1)      = 1
clock_gettime(CLOCK_MONOTONIC, {340, 786862877}) = 0
futex(0x7fc625a78f60, FUTEX_WAIT, 0, {60, 0}) = -1 ETIMEDOUT (Connection timed out)
clock_gettime(CLOCK_MONOTONIC, {400, 787211261}) = 0
futex(0x12a01b8, FUTEX_WAKE, 1)         = 1
clock_gettime(CLOCK_MONOTONIC, {400, 787337113}) = 0
madvise(0xc2080b2000, 8192, MADV_DONTNEED) = 0
madvise(0xc2081a4000, 8192, MADV_DONTNEED) = 0
madvise(0xc208106000, 8192, MADV_DONTNEED) = 0
madvise(0xc20810c000, 8192, MADV_DONTNEED) = 0
madvise(0xc2081ae000, 8192, MADV_DONTNEED) = 0
madvise(0xc208100000, 8192, MADV_DONTNEED) = 0
madvise(0xc20811a000, 8192, MADV_DONTNEED) = 0
madvise(0xc2081b6000, 16384, MADV_DONTNEED) = 0
madvise(0xc2081a8000, 16384, MADV_DONTNEED) = 0
madvise(0xc20816e000, 24576, MADV_DONTNEED) = 0
madvise(0xc20814a000, 24576, MADV_DONTNEED) = 0
madvise(0xc2080d6000, 32768, MADV_DONTNEED) = 0
madvise(0xc2081f8000, 32768, MADV_DONTNEED) = 0
futex(0xc208066570, FUTEX_WAKE, 1)      = 1
clock_gettime(CLOCK_MONOTONIC, {400, 788114132}) = 0
futex(0x7fc625a78f60, FUTEX_WAIT, 0, {60, 0}
```

**Comment by estesp** [comment]
`docker run` is designed to wait until the command executed by the container exits. If you would prefer running the container in the background (meaning your run command will return immediately), you can do so with the `-d` flag to the run command.

If docker did not wait properly, then something like the following (which has no output at all) would never work:
```
docker run busybox /bin/sh -c 'sleep 300; exit 2'
```
Of course that's a very contrived example, but after "doing nothing" for 5 minutes, this exits with exit code 2, which may be something that triggers another action from the caller.  The fact that nothing happens for 5 minutes from an I/O perspective is not important in this case.

If I've misunderstood your issue, please let me know.

**Comment by grahamc** [comment]
Yes. As the strace clearly shows, the client's connection times out, but continues waiting for feedback. The process correctly logs the output to `docker log`. The symptom here is the container finishes running in 8 minutes, but the docker client runs for 2hrs, thinking it is waiting on more output, when in reality the container has long exited. This is a bug in the docker client not realizing the connection has timed out, it seems.

**Comment by estesp** [comment]
Just so I fully understand--what are the triggers for knowing that the container finished on the server side in 8 minutes (log info?), and what happened on the client side after 2 hours?  Did it exit "normally" back from your `docker run` invocation?  Error reported?  Thanks for the add'l info!

**Comment by grahamc** [comment]
On the client side which is running over HTTPS and failing, I'm running `docker run myimage`. I then log in to the server which is running the docker daemon itself and connect over a unix socket `docker logs mycontainer`. The container runs and exits after eight minutes, and it is correctly observed when watching over the unix socket.

After two hours, the task runner kills it assuming the process is hung. There is no indication that if the docker client were left to its own devices it would ever exit

**Comment by estesp** [comment]
I've reproduced this with a simple test container than randomly waits for > 1 min between outputting to stdout.  Reproducible with HTTP, so doesn't require HTTPS for repro.
