### ISSUE TITLE
invalid argument when trying to run docker with -g flag on a specific directory

### ISSUE THREAD

**Issue by 47bytes** [docker/docker#10380]
When I try to run docker with its root folder in /home/leo/devel/docker I get the folllowing:

    $ sudo docker -d -D -g /home/leo/devel/docker
    INFO[0000] +job serveapi(unix:///var/run/docker.sock)  
    FATA[0000] invalid argument

When I try to run it in  /home/leo/devel/blablabla it works as expected.  
The problem only exists when the docker root is /home/leo/devel/docker.  
There is no mention of /home/leo/devel/docker in `$ mount`. 
#docker @ freenode tried to help me with this very weird problem but without any solution.

I'm running `Docker version 1.4.1, build 5bc2ff8` 

Here are straces of the command:
`$ sudo strace docker -d -D -g /home/leo/devel/docker` http://pastebin.com/nwZta7mS .
`$ sudo strace docker -d -D -g /home/leo/devel/docker2`  http://pastebin.com/A0bhwZWy .

Someone in #docker noted that the error message raised does not come from docker but from the underlying FS but it would be worth it to open a ticket for this as it might be a good idea to catch the error and return a more comprehensible error message.  

I've stopped the docker daemon and removed `/var/lib/docker` & `/home/leo/.docker` & `/home/leo/devel/docker` without any changes (I've also tried turning it off and on again).

I'd appreciate any pointers for what might cause this to happen.

**Comment by duglin** [comment]
So the only difference between the two cases is that one dir ends with "docker" and the other ends with "blablabla" ?  The permissions on both dirs are the same?

**Comment by 47bytes** [comment]
UPDATE:

I resolved the issue. It seems to be a problem with eCryptfs and Docker.
After changing the docker root dir to a dir on the encrypted folder docker will work as expected but after rebooting the problem above exists.  

I resolved it creating a dedicated docker partition.

**Comment by cpuguy83** [comment]
Closed since the OP says issue is resolved.
