### ISSUE TITLE
Please increase the 30-character image repository name limitation

### ISSUE THREAD

**Issue by ncdc** [docker/docker#10392]
For OpenShift, we're interested in being able to have image repositories with names such as `sales-division-admin-templates/rhel-python-27-apache-24-mod-wsgi`. The current maximum number of characters allowed in an image repository name component is 30. Would it be possible to increase this value?

References:

- https://github.com/docker/docker/issues/10136
- https://github.com/docker/docker-registry/issues/901

**Comment by stevvooe** [comment]
:+1:

**Comment by dmp42** [comment]
+ let's make sure the validation rules are the same across systems.

cc @kencochrane @shin-

**Comment by thaJeztah** [comment]
^^ +1. Is there a check when *pulling* images as well? May be worth checking; thinking of older clients trying to pull an image from the Hub and not being able to do so.

**Comment by jfrazelle** [comment]
did we implement this

**Comment by ncdc** [comment]
@jfrazelle no, it hasn't been implemented to my knowledge

**Comment by dmp42** [comment]
Ping @shin- 
Where are we with the hub now? What are the limitation enforced?

**Comment by shin-** [comment]
Patched it recently to be consistent with the rules enforced with registry v2, so still 30 characters, and made sure it's enforced properly in all places. However, that also means making the change to something other than 30 should be pretty easy if we agree on a new value.

**Comment by stevvooe** [comment]
@shin- @dmp42 Currently, registry v2 limits the name component to 30 chars, but we should remove this restriction and limit to a total length. The hub can independently select limits for username/repo within this space. As far as the docker daemon is concerned, I have no opinions other than that it should follow the v2 constraints.

**Comment by ncdc** [comment]
FYI #11118 has been merged, and the corresponding PR for the v2 registry has as well.

**Comment by Sirupsen** [comment]
@ncdc this can be closed then?

**Comment by dmp42** [comment]
@Sirupsen I would say yes.

**Comment by p4tin** [comment]
Yes close as the PR #11118 was merged so this should be closed, as I was ready to pick it up
