### ISSUE TITLE
Directory removed between intermediate containers

### ISSUE THREAD

**Issue by corbinu** [docker/docker#10393]
I am trying to build a couchbase container how ever a directory keeps getting destroyed. I added a set of RUN command to add the directory manually. The mkdir works fine and I can touch a file in the dir in that container, but the following RUN for chmod says the directory does not exist. 

The relevant commands
```
RUN mkdir -p /opt/couchbase/var/lib/couchbase && touch /opt/couchbase/var/lib/couchbase/hold
RUN mkdir -p /opt/couchbase/var/lib/couchbase/logs && touch /opt/couchbase/var/lib/couchbase/hold
RUN chown -R couchbase /opt/couchbase/var/lib/couchbase
```

Outputs
```
chown: cannot access `/opt/couchbase/var/lib/couchbase'
```

The build on the docker registry
https://registry.hub.docker.com/u/corbinu/docker-couchbase/build_id/37372/code/btk8t76rka2uxpwwumtw5xl/

docker info reads
```
docker info                                                                                     [12:03:06]
Containers: 0
Images: 0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Dirs: 0
Execution Driver: native-0.2
Kernel Version: 3.16.7-tinycore64
Operating System: Boot2Docker 1.4.1 (TCL 5.4); master : 86f7ec8 - Tue Dec 16 23:11:29 UTC 2014
CPUs: 4
Total Memory: 3.866 GiB
Name: boot2docker
ID: UZC6:E4XS:WOOE:KPPM:7XKW:3R4F:DY2T:ZTAO:3JWQ:WMBI:4GN5:4QC6
Debug mode (server): true
Debug mode (client): false
Fds: 10
Goroutines: 11
EventsListeners: 0
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
```

**Comment by billsmith** [comment]
File operations behave in non-obvious ways when you use AUFS.  What happens if you move the chown command before that second mkdir?

**Comment by phemmer** [comment]
You have the following line in your Dockerfile:

> VOLUME /opt/couchbase/var

This is your issue

https://docs.docker.com/userguide/dockervolumes/#volume-def
> Changes to a data volume will not be included when you update an image

**Comment by corbinu** [comment]
@phemmer thanks
