### ISSUE TITLE
ENV declarations don't inherit values if declared on same line

### ISSUE THREAD

**Issue by n0coast** [docker/docker#10391]
Attempting to declare multiple variables that reference previously declared variables on one line doesn't seem to work, for example this declaration will create variables that contain strings instead of expanded variable definitions:

    ENV JAVA_VERSION=jdk1.7.0_75 \
        JAVA_HOME=/usr/$JAVA_VERSION \ 
        JAVA_BIN=$JAVA_HOME/bin \
        JRE_HOME=$JAVA_HOME/jre

After building a container with the above ENV declarations the environment will contain:

    JAVA_VERSION=jdk1.7.0_75
    JAVA_HOME='/usr/$JAVA_VERSION'
    JAVA_BIN='$JAVA_HOME/bin'
    JRE_HOME='$JAVA_HOME/jre'

Where I would expect those variables to have been expanded.

On the other hand creating variables using multiple ENV statements will work and variables will contain the expanded variables:

    ENV JAVA_VERSION jdk1.7.0_75
    ENV JAVA_HOME /usr/$JAVA_VERSION
    ENV JAVA_BIN $JAVA_HOME/bin
    ENV JRE_HOME $JAVA_HOME/jre

After building a container with the above ENV declarations the environment will contain:

    JAVA_VERSION=jdk1.7.0_75
    JAVA_HOME=/usr/jdk1.7.0_75
    JAVA_BIN=/usr/jdk1.7.0_75/bin
    JRE_HOME=/usr/jdk1.7.0_75/jre

It wasn't apparent in the documentation that this should or should not work, and the second method causes 3 extra intermediate containers to be built. As the statements are very similar it would be nice to have then behave similarly, or the difference be documented.

**Comment by duglin** [comment]
This is a cool one :-)

**Comment by duglin** [comment]
Opened PR https://github.com/docker/docker/pull/10431 for this.

**Comment by jfrazelle** [comment]
closing as dup of https://github.com/docker/docker/issues/8667
