### ISSUE TITLE
Feature request: docker ps should return full [docker run command]

### ISSUE THREAD

**Issue by netroby** [docker/docker#10407]
Feature request: docker ps should return full [docker run command]

For example, i run a docker container via 

```
docker run --name="devbox_web" -i -t -p 80:80 -v /home/domy/data/www/root:/wwwroot fedora/21 /bin/bash
```

the container running and up

and then , i check if it running normal

```
docker ps -a
```

could we return the booting command when showing the docker ps result?

such as display

```
docker run --name="devbox_web" -i -t -p 80:80 -v /home/domy/data/www/root:/wwwroot fedora/21 /bin/bash
```

it will be helpful if we want to find out what's the initialize command of the container.

**Comment by aanm** [comment]
@netroby 
Duplicate, see https://github.com/docker/docker/issues/8705
