### ISSUE TITLE
why docker dead

### ISSUE THREAD

**Issue by hanxy** [docker/docker#10410]
Today when i exectue "docker ps", "docker ps -a" or any commands of docker, docker is always dead status. for example:

I type "docker ps", no any info show and in dead status.

I try to kill all process but can't solve this problem

**Comment by HuKeping** [comment]
would you please put out  your log here, generally it will be on /var/log/upstart/docker.io.log

**Comment by crosbymichael** [comment]
@hanxy He are happy to help you with this but you need to provide more information when opening an issue.  You can refer to the information located [here](https://github.com/docker/docker/blob/master/CONTRIBUTING.md#reporting-issues) as a starting point for what we need to reproduce and help.

With the current information here there is nothing we can do at this time.  Feel free to use that issue template and open one with more information.

**Comment by hanxy** [comment]
@crosbymichael  
i can't provide more information, beacuse docker.log is not change
the phenomenon is that 
I execute all docker command,  stuck on screen but "docker -version". I must restart docker host and then normal exectue docker command
