### ISSUE TITLE
Docker Hub Automated build : "This image does not belong to the repository"

### ISSUE THREAD

**Issue by jeanblanchard** [docker/docker#10412]
I have an Automated build repository : https://registry.hub.docker.com/u/jeanblanchard/busybox-tomcat/ that builds 7 tags from 4 git branches.
Each time a build is triggered, one of those tags fails to push with the error `HTTP code 400 while uploading metadata: {"error": "This image does not belong to the repository"}`.
The build is otherwise successful. It is not always the same branch that fails, but exactly one fails each time.

It looks like issue #678, but that is a pretty old bug, so it may be completely unrelated.

PS: I am not sure this is the right place to report hub bugs, but I have not found a better place...

**Comment by crosbymichael** [comment]
@jeanblanchard For automated build support I think the best way, and also fastest is to contact support@docker.com and they will take care of your problem.

**Comment by jeanblanchard** [comment]
Retried today, and this time it worked (that's the 6th try with the same revisions)
Anyway I'll contact the docker.com support if I still have a problem next time I update the repo. Thanks @crosbymichael.

**Comment by crosbymichael** [comment]
@jeanblanchard no problem, thanks for responding so quickly

**Comment by JensErat** [comment]
I have the same issue with my [SOGo repository](https://registry.hub.docker.com/u/jenserat/sogo/). Also wrote an e-mail to supprt@docker.com.

**Comment by Stono** [comment]
Yeah I've got this too, also emailed

**Comment by samos123** [comment]
Same problem here: https://registry.hub.docker.com/u/samos123/drupal/build_id/13402/code/bbqwlrz7hpysfhdg6ntjbzn/

did support solve it for you guys?

**Comment by JensErat** [comment]
No, problem still persists and I did not even receive an answer.

**Comment by Stono** [comment]
It's resolved for me now.
