### ISSUE TITLE
docker export and load problems

### ISSUE THREAD

**Issue by sunshine69** [docker/docker#10429]
Hi everyone,

I got an error when doing a export and load. In the host A I do export

sudo  docker export content-web-kr | gzip - > content-web-kr.tgz

When it is done I scp the tar ball and load it in machine B

sudo docker load <  content-web-kr.tgz

In B it runs for a while and then print the error:

FATA[0159] Error: open /var/lib/docker/tmp/docker-import-937914018/repo/bin/json: no such file or directory

I did extract the tar ball in verify that there is no such file a directory. 

A is a centos 7 64 bit machine with docker Docker version 1.3.2, build 39fa2fa/1.3.2
B is a centos 6 64 bit - same version of docker

I tried when B is ubuntu 14.04 as well same errors. (Docker version 1.4.1, build 5bc2ff8).

**Comment by sunshine69** [comment]
I think while load failed but import works fine with exported tar ball. So for some reason the doco is not clear on that point - if you export a CT to a tar abll you need to use import rather than load. if you save an image to a tar ball then use load to restore.

So it might not be a bug at all

**Comment by hixichen** [comment]
tar cvf image.tar image/  
check the image  path.

it should be:
cd image/    
 tar cvf image.tar  ＊
