### ISSUE TITLE
registry: compute checksum on upload of an image

### ISSUE THREAD

**Issue by jlhawn** [docker/docker#10432]
To avoid the issue where imported image layers may have a different checksum when they are exported we should compute the layer checksum while uploading it and using that computed checksum in a second request to complete it (https://github.com/docker/distribution/blob/master/doc/SPEC.md#completed-upload)

related to https://github.com/docker/distribution/issues/112

**Comment by jfrazelle** [comment]
@icecrime Should we close if it's fixed

**Comment by jlhawn** [comment]
@jfrazelle I'll close it.
