### ISSUE TITLE
Ubuntu 14.04 Always fails to push to docker hub - Please help!?! - unhelpful error occurs FATA[XXXX]

### ISSUE THREAD

**Issue by snewhouse** [docker/docker#10437]
This is always the case for me...I get so far then a unhelpful error occurs FATA[XXXX]..always

I can build and push from my Mac, our Windows box and Amazon and google clouds, but never from my Ubuntu 14.04 machine.

Any help/suggestions would be great.

```{bash}

Sending image list
Pushing repository compbio/gentoo (1 tags)
511136ea3c5a: Image already pushed, skipping 
e3c4be0ef95d: Image already pushed, skipping 
95564adb61ab: Pushing [==================================================>] 754.1 MB/754.1 MB
FATA[0134]   

```

**Comment by phemmer** [comment]
your docker daemon logs might contain some more helpful information. I'm assuming you're using boot2docker, but I'm not sure where these logs are kept. Perhaps `/var/log/docker` (inside the boot2docker VM).
Also the usual `docker info` and `docker version` output is good to have.

**Comment by snewhouse** [comment]
Hi 
Thanks...info below

#### uname -a
Linux sjndell 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

#### docker info
Containers: 0
Images: 262
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 262
Execution Driver: native-0.2
Kernel Version: 3.13.0-44-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 8
Total Memory: 31.36 GiB
Name: sjndell
ID: A4OG:KBST:UEO7:EUYZ:PE4H:OJKR:BNPW:T62W:63E7:YKYX:BATM:STLC
Username: compbio
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support

#### docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8

**Comment by jfrazelle** [comment]
I think this is due to downtime with the hub but ping me here if otherwise
