### ISSUE TITLE
when docker use devmapper as storage driver，does it  thread safe for read and write Frequently ？

### ISSUE THREAD

**Issue by oxwangfeng** [docker/docker#10436]
when  docker use devmapper as storage driver，Frequently I read and write  to container for a lot of data at the same time，does it safe for thread？
thread unsafe would be happend？

**Comment by unclejack** [comment]
@oxwangfeng Yes, writing data to files in the containers should be thread safe.

Devicemapper has bugs which are being discussed on issues like #4036, but those are for container start/stop/restart and daemon restart.

I'll close this issue now since the question was answered.
