### ISSUE TITLE
Snappy package for latest release of docker

### ISSUE THREAD

**Issue by koyadume** [docker/docker#10438]
Last month Canonical released a flavor of ubuntu called snappy ubuntu but there are not much details available about this it. 

Yesterday I updated docker in a local VM running snappy ubuntu where ```docker --version``` command is reporting 1.3.3. I could not find any such version under docker release notes section. So not sure which version of docker it is referring to. Size of virtualbox image for snappy ubuntu is less than one third of virtualbox image size for ubuntu server. So I would like to use snappy ubuntu as docker host for my setup. Is there any documentation available from docker team which explains how to run latest version of docker on snappy ubuntu?

**Comment by cpuguy83** [comment]
@koyadume Canonical does all snappy packaging.  I believe they are also using a modified version of Docker due to some issues with snappy+docker's apparmor support.

So, in short, you are subject to what's available on the snappy repos.
