### ISSUE TITLE
Docker client requires write permission to $HOME

### ISSUE THREAD

**Issue by burke** [docker/docker#10442]
We run our weird custom docker builder with a non-writable `$HOME` out of coincidence more than anything, but this came up immediately after upgrading that node to `1.5.0`:

```
Jan 29 18:34:32.286:    + docker inspect --format=. registry.chi.shopify.io:80/base:1.3.5
Jan 29 18:34:32.297:    time="2015-01-29T18:34:32Z" level="fatal" msg="mkdir /u/apps/locutus/.docker: permission denied" 
```

It looks like the client initialization tries to force `${HOME}/.docker` into a state it likes, bailing if it can't. This doesn't seem necessary for most operations I'd be requesting.

**Comment by jfrazelle** [comment]
ping @dmcgowan
