### ISSUE TITLE
`test.docker.io` sometimes 502s

### ISSUE THREAD

**Issue by burke** [docker/docker#10447]
```
Err https://test.docker.io docker/main amd64 Packages
  HttpError502
Hit https://test.docker.io docker/main i386 Packages
Fetched 1,378 kB in 10s (127 kB/s)
W: Failed to fetch https://test.docker.io/ubuntu/dists/docker/main/binary-amd64/Packages  HttpError502
```

This is more of an IRC thing, but I don't really feel like opening IRC. Feel free to close this right away; I just figured I should tell someone. I've got a number of 502s while mucking around with this stuff today.

**Comment by jfrazelle** [comment]
@burke I am going to close I think it was a weird anomaly :D

**Comment by burke** [comment]
Works for me!
