### ISSUE TITLE
CentOS 6 Networking Issue: No route to host

### ISSUE THREAD

**Issue by aviddiviner** [docker/docker#10450]
Picked up a strange networking issue running Docker on CentOS 6.5. I set up a simple test for connectivity between my two containers:

```bash
# Listen with container 1
sudo docker run -it --rm --name cont1 -p 3333:3333 ubuntu /bin/bash -c "nc -l 3333"
# Try to connect from container 2
sudo docker run -it --rm --name cont2 ubuntu /bin/bash -c "nc -w 1 -v 172.17.42.1 3333"
```

Problem is, the second container always fails with this error:
`nc: connect to 172.17.42.1 port 3333 (tcp) failed: No route to host`

Even though my second container's routes look right:
```
% sudo docker run -it --rm --name cont2 ubuntu /bin/bash -c "route -n"
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 eth0
0.0.0.0         172.17.42.1     0.0.0.0         UG    0      0        0 eth0
```

And Docker is also started with proper defaults (`--icc=true --iptables=true`).
Also, IP forwarding works fine (`cat /proc/sys/net/ipv4/ip_forward` gives me `1`).

The weird part was that this was only broken on CentOS, but worked fine on my Ubuntu vagrant. So I dug into `iptables -L -n -v` to see what was up. It turns out CentOS has some strange defaults.

FORWARD rules looked good:
```
% iptables -S FORWARD
-P FORWARD ACCEPT
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
```

But the INPUT filter is messed up on CentOS:
```
% iptables -S INPUT
-P INPUT ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
```

So I fixed my problem in the end with a `iptables -I INPUT 4 -i docker0 -j ACCEPT`.

My question is; can we maybe have Docker put in a rule in the INPUT chain for you automagically like it does with the FORWARD chain when started with `--iptables=true`. Or at least check that the INPUT chain isn't set up in a way that would make connectivity impossible?

Basically, just make sure that `iptables -A INPUT -i docker0 -j ACCEPT` is up near the top of the chain.

Thanks for the awesome package. Oh, and I almost forgot:

```
% uname -a
Linux golem.vbox 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

% lsb_release -a
LSB Version:  :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: CentOS
Description:  CentOS release 6.5 (Final)
Release:  6.5
Codename: Final

% sudo docker version
Client version: 1.3.2
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 39fa2fa/1.3.2
OS/Arch (client): linux/amd64
Server version: 1.3.2
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): 39fa2fa/1.3.2
```

**Comment by jfrazelle** [comment]
you need to link the first container to the second
```
# Listen with container 1
sudo docker run -it --rm --name cont1 -p 3333:3333 ubuntu /bin/bash -c "nc -l 3333"
# Try to connect from container 2
sudo docker run -it --rm --link cont1:cont1 --name cont2 ubuntu /bin/bash -c "nc -w 1 -v  cont1 3333"
```

**Comment by kevana** [comment]
My understanding is that this is expected behavior and won't be changed, is that correct?

**Comment by easyrasta** [comment]
Same issue with iptables. Well in case of container arent on same machine, how to

**Comment by alrf** [comment]
The same issue on CentOS 6.5
