### ISSUE TITLE
Automating regular AUTHORS updates via project/generate-authors.sh

### ISSUE THREAD

**Issue by nealmcb** [docker/docker#10451]
`CONTRIBUTING.md` says *Please do not add yourself to the `AUTHORS` file, as it is regenerated regularly from the Git history.*   But it is unclear how that is supposed to happen.

As far as I can tell from #9187 and previous history, the `AUTHORS` file wasn't changed for release 1.3, and was changed for 1.4 due to that ad-hoc issue report.  It looks like 1.5 comes out soon.

Is there an automated script, or a documented process for generating new releases?  It should run `project/generate-authors.sh`.

And in the meantime, it should be run at the end of the release cycle by hand, and I suggest this issue be added to the 1.5 milestone.

**Comment by unclejack** [comment]
ping @tianon

**Comment by tiborvass** [comment]
I'm +1 for automating AUTHORS generation before release

**Comment by tianon** [comment]
I agree that this could/should be automated, although the results will have to be hand-vetted as well to see if we've had any new obvious duplicates crop up that need to be added to our `.mailmap`.

**Comment by nealmcb** [comment]
Based on the [conversation in my PR](https://github.com/docker/docker/pull/10590), we want a manual step to check for wrong addresses like <id>@users.noreply.github.com, or other likely problems, and update the .mailcap file.

I suggest that the project/generate-authors.sh script should at least look for that sort of thing, note duplicates in the name or email parts of the AUTHORS file, and provide some sort of advice / help on updating .mailcap.  Perhaps there is a nice script out there that we could grab?

The Docker release checklist is at project/RELEASE-CHECKLIST.md and it should suggest that this sort of AUTHORS update should happen at least once near the end of each release.

**Comment by nealmcb** [comment]
Hmm - now that I look at https://help.github.com/articles/keeping-your-email-address-private/ I see that <name>@users.noreply.github.com is actually recommended for use by authors that don't want their real addresses to be spammed.  So I'm wondering if it is proper that we have translated that form of address for 12 folks to actual email addresses in .mailmap.  And that also complicates the notion of automatically fixing them as "wrong addresses".
Did the folks that added those .mailmap entries check with the people involved about their preferences?

**Comment by tianon** [comment]
The only entries in ".mailmap" are the ones where people have multiple
commits with different names or email addresses.  If someone actually has a
valid non-noreply email address in a commit, that's the only reason we'd
overwrite that.

You can see this locally by removing the .mailmap file locally, and then
rerunning the "generate" script and browsing the diff (which should have a
large number of duplicates show up).

**Comment by nealmcb** [comment]
I'm trying to get at the intent of the contributor.

As I see it, anyone who ever submits a contribution with a noreply address has clearly taken steps to avoid sharing their real email with spammers or whoever.  If someone starts to do that after committing with a real email address, I assume they would prefer that the noreply address be used in the AUTHORS document.  That may also be true if they slip up from time to time and send in a commit that doesn't use their noreply.  But others may have given up on the anti-spam feature, or now want to take credit with their actual email address.

I guess we don't have any specific way for them to indicate their preference which is more clear and robust than simply telling them to edit the .mailcap file themselves.  For those that don't do that, my inclination would be for us to adopt a policy that a noreply address trumps others, rather than the other way around, so perhaps we should put a note to that effect in the .mailcap file et al.

For those currently in that ambiguous position, perhaps an email query would be in order, and it would certainly give us some real data.  But of course I want to avoid spamming them ;)

I'd love to know how other projects deal with this.

**Comment by nealmcb** [comment]
Unless something has changed, it still seems relevant to me.
