### ISSUE TITLE
Docker pause and unpause should accept multiple containers

### ISSUE THREAD

**Issue by amouat** [docker/docker#10457]
It seems strange to me that `docker rm`, `docker stop` and `docker start` all can take multiple containers as arguments, but `docker pause` and `docker unpause` only take take a single argument. Just for consistency it would be nice to change this.

Doesn't seem to be much work as it looks like there is a loop in place for processing multiple arguments, but it is only ever given exactly one argument:

https://github.com/docker/docker/blob/d748ec31d5f89f4cbe363ac9b38310906bf2a9e0/api/client/commands.go#L806

**Comment by duglin** [comment]
@amouat can't think of a reason - I'll take this one - should be easy - just need to write-up the testcases.

**Comment by aanm** [comment]
@duglin I'm already on it. I'm writing the tests
+

**Comment by duglin** [comment]
ok
