### ISSUE TITLE
--net=container should not require running container 

### ISSUE THREAD

**Issue by ibukanov** [docker/docker#10462]
Currently using --net=container:foo is problematic as it requires a running container. Thus it is not possible to restart the container foo and one has to be very careful with startup order to ensure that the container foo starts and initializes its network before running another container.

It would be nice if --net=container:foo would not require the foo running. Rather docker can create foo's network namespace and allow other containers to join it. When foo later starts, it would just join that network namespace. Similarly, when foo exits and starts again, it should join the original namespace if other container still use it rather than creating a new  one again.

As a workaround with the current docker one can use an extra container that just sleeps forever in its main process and all relevant containers join its network. However this still does not solve the ordering problem as now one has to ensure that this extra container properly starts up before the rest. In addition this just wastes resources.

**Comment by alexanderkjeldaas** [comment]
How do you propose that `foo`'s network namespace should be deleted?  To you propose that network namespaces should be created on demand and garbage collected with no owner?

**Comment by ibukanov** [comment]
@alexanderkjeldaas 

Yes, the network namespace should be created on demand and be destroyed when the last container that uses it is stopped. It will be nice if this can also be used no only with `--net=container:foo` but also with containers that uses `--link:foo`. This way it will be possible to start those containers without requiring that foo is running and restarting foo will be transparent with no changes in network setup.

**Comment by ibukanov** [comment]
@alexanderkjeldaas

An alternative to on-demand start is to allow to create network namespace the moment the container is created (or the docker daemon started) and keep the network namespace available until the container is destroyed. This will allow to create network-only containers similar to storage-only containers that provide volumes even when not running.

**Comment by jfrazelle** [comment]
I don't know if I agree with this. There would be a lot of garbage hanging around. It's much cleaner to handle on container stop and start. 
Why wouldn't you be able to start the container that you are trying to user for --net container.

**Comment by ibukanov** [comment]
@jfrazelle There are issues with a reliable restart of containers with all dependencies (if the --net container is restarted, then all related containersh should be restarted as well). See, for example, #7228 .

**Comment by temoto** [comment]
:+1: this would fix some of my docker configuration issues.

**Comment by thockin** [comment]
Wouldn't it be easier to just abdicate all of the responsibility and let orchestrators do their own thing, and just tell docker to join a particular namespace?

**Comment by thockin** [comment]
ditto for IPC, PID, User, etc etc

**Comment by runcom** [comment]
just my 2c.. I don't really understand why someone would initially run a container, then later run another with --net from the first one and finally require that the second container have to run without the first running and only get its net namespace.
I think running the second container with --net imply a strict dependency with the first container, thus I think the first container have always to be running before starting the second.
I also think that what is missing is some way to bring up container in the correct order if they are somehow linked (--net --ipc) (thought about this after #11777)

**Comment by thockin** [comment]
@runcom you're just missing the use case.  The "first" container only exists to hold the namespace. that several other containers share.  The fact that something has to be running to keep it open means that there's a risk - if that running process dies for any reason, all of the things that joined the net namespace are in jeopardy and have to be restarted.

If we could just hold a namespace open without a running process, there's nothing to crash == more reliable.

**Comment by jfrazelle** [comment]
I see this as a fine change if someone is willing to make it, we should however maybe warn the user since in the past the container had to be running they may not intend to hook it to a non-running container

**Comment by runcom** [comment]
@thockin got it now

**Comment by thockin** [comment]
@jfrazelle I imagined it would need some special flag, eg

```
$ docker run -d dockerfile/noop
123456789abcdef

$ docker run --net=container:123456789abcdef my/realjob
ERROR: container 123456789abcdef is not running (maybe you want to --pin-namespaces?)
```

vs

```
$ docker run -d --pin-namespaces dockerfile/noop
123456789abcdef

$ docker run --net=container:123456789abcdef my/realjob
8675309deadbeef
```

**Comment by jfrazelle** [comment]
ooo nice yeah

**Comment by runcom** [comment]
@thockin neat! Also, wouldn't "pinning" a namespace requires firstly to start a process, setns'ing the namespace and exiting while still holding a file descriptor to that ns (or bind mounting that namespace somewhere to have it active)? Are there any other way to just create a namespace without requiring firstly a pid to a process?

**Comment by thockin** [comment]
No, I think it has to be as you suggest.

**Comment by thockin** [comment]
The parallel is Volumes - they continue to exist and be usable after a
container has stopped running.

**Comment by runcom** [comment]
Yep.. it kinda sounds like a workaround to just init a container (maybe with a dummy init) just to get its namespaces to be used by some other containers. 
Also, if it's like I said before (I'm not really and totally sure) I think this requires support from libcontainer too (I mean the possibility to start a container just to setup it's namespaces, maybe bind mounting them somewhere and then immediately exit the container)

**Comment by thockin** [comment]
We just got --parent-cgroup, which side-steps the "model everything as a
container".  If we had --pid=ns:name, --net=ns:name, --ipc=ns:name we could
do "pinned" namespace management outside of docker.  I don't much care
which mode, I just want a solution :)

**Comment by runcom** [comment]
@thockin @ibukanov do you mind if I open a proper proposal with some examples of use cases, pro/cons, implementation, to have more feedbacks with the whole background of this thing?

**Comment by thockin** [comment]
Please @ me if you do - too many threads, important ones can get lost.

**Comment by runcom** [comment]
sure!

**Comment by thaJeztah** [comment]
I'm gonna close this because #12035 has been created to replace this one. Please continue the discussion on that issue/proposal.

(Feel free to ping me if this shouldn't be closed for some reason).
