### ISSUE TITLE
[docs]: runmetrics article is out of date

### ISSUE THREAD

**Issue by billsmith** [docker/docker#10463]
The "Finding the Cgroup for a Given Container" section of https://docs.docker.com/articles/runmetrics/ is out of date, at least for containers that do not use LXC.

Here is an example: "Putting everything together to look at the memory metrics for a Docker container, take a look at /sys/fs/cgroup/memory/lxc/<longid>/."  I don't use LXC.  On my Ubuntu 14.04 machine running Docker 1.4.1, the correct path is /sys/fs/cgroup/memory/docker/<longid>/.

**Comment by duglin** [comment]
@billsmith would you be willing to submit a PR to fix this?

**Comment by billsmith** [comment]
Yes, I'll do that.

**Comment by tombee** [comment]
This looks to be the same thing that's reported in #7866 :)

**Comment by thaJeztah** [comment]
Closing, because https://github.com/docker/docker/pull/15885 was merged
