### ISSUE TITLE
LXC: Cannot symlink to an absolute directory in the same layer and

### ISSUE THREAD

**Issue by ashahab-altiscale** [docker/docker#10466]
Steps to reproduce:
Start docker daemon with lxc driver.
```
$docker build -t img1 - << END_TEXT
FROM busybox
RUN mkdir /newDir
RUN ln -s /newDir /symlinkedDir
END_TEXT
```
Now run this image
```
$docker run -v /symlinkedDir/test img1 sh -c 'mount | grep -q /newDir/test' 
```

You'll get an error.

**Comment by icecrime** [comment]
As notified in our [deprecation notice](https://github.com/docker/docker/blob/d023d5a8a24c18e912162c2f4c724cfb21028301/docs/misc/deprecated.md#lxc-built-in-exec-driver), Docker 1.10.0 will drop support for the LXC exec driver (#17700).

Thank you for the report, I'm now closing this.
