### ISSUE TITLE
Debian family of official docker package is missing systemd service and socket file

### ISSUE THREAD

**Issue by dz0ny** [docker/docker#10496]
This is not critical but should be added sooner than later. First Ubuntu release that will (optinaly) use systemd is vivid and docker.io package for that release allready contains nesecery bits for systemd integration.

This are extracted from http://mirrors.kernel.org/ubuntu/pool/universe/d/docker.io/docker.io_1.3.3~dfsg1-2ubuntu2_amd64.deb

docker.service
```
[Unit]
Description=Docker Application Container Engine
Documentation=http://docs.docker.com
After=network.target docker.socket
Requires=docker.socket

[Service]
EnvironmentFile=-/etc/default/docker
ExecStart=/usr/bin/docker -d -H fd:// $DOCKER_OPTS
LimitNOFILE=1048576
LimitNPROC=1048576

[Install]
WantedBy=multi-user.target
```

docker.socket
```
[Unit]
Description=Docker Socket for the API
PartOf=docker.service

[Socket]
ListenStream=/var/run/docker.sock
SocketMode=0660
SocketUser=root
SocketGroup=docker

[Install]
WantedBy=sockets.target
```

**Comment by jfrazelle** [comment]
Does ubuntu support systemd tho?
We have our files in contrib/ that you can use for this. This is more of an issue for the ubuntu pacakgers, if I am not mistaken.

**Comment by jfrazelle** [comment]
I would file something here instead https://launchpad.net/ubuntu/+source/docker.io/+bugs
