### ISSUE TITLE
Executing different scripts during container creation and restart

### ISSUE THREAD

**Issue by koyadume** [docker/docker#10493]
Is it possible to execute different scripts during container creation and restart?

Basically I am trying to achieve cloud-init like behavior for a container. E.g. for a mysql container I would like to make sure that it executes a script, which creates and initializes a db, at the time of creating a container while server start script should be executed every time container is restarted. Another question is how does container know what script to execute when a container is stopped? In case of a mysql container I would like to execute ```service mysql stop``` command while stopping the container but I am not sure where it is specified.

**Comment by unclejack** [comment]
@koyadume You can easily do this by creating a script which touches a file on the first run and skips the initialization for the next runs if the file exists. This script would be the actual command you run whenever you run the container.

Hooks and scripts to be run when various events occur have been discussed before. Something like this should show up at some point, but it needs to be flexible to meet the requirements of more use cases.

I'm going to close this issue now. Please feel free to comment if you have any more questions.
