### ISSUE TITLE
Container in Ramdisk

### ISSUE THREAD

**Issue by davidak** [docker/docker#10490]
I use Docker for building Ubuntu-Packages.

To get better Disk-Performance i want to run the Container in a RAM-Disk without building special Images.

Something like `docker run -t -i --ram-disk ubuntu:14.04`

I can't find anything in the Docs: https://docs.docker.com/jsearch/?q=ramdisk

Maybe there is a way, since there is this issue https://github.com/docker/docker/pull/4519, if not is this a Feature-Request.

**Comment by jfrazelle** [comment]
You can set the enviornment variable `DOCKER_RAMDISK` and it will not use a pivotroot

**Comment by davidak** [comment]
i don't think that this is what i want.

i want to run a container completely in ram.

**Comment by thaJeztah** [comment]
Would starting the daemon with `docker -d -g /path/to/ramdisk` work? (see [Daemon storage driver options](https://docs.docker.com/reference/commandline/cli/#daemon-storage-driver-option)).

Highly experimental, and really don't know if that'd work. Also, *everything* will then be stored in the ram disk, images, volumes.

**Comment by davidak** [comment]
@jfrazelle thank you. that could be an option.

but it would be nice if that function would get implemented in docker to run one conainers volume in ram and save it to disk from time to time.
this workaround would help me with temporary containers for building packages.

**Comment by noizu** [comment]
This something I'm curious about as well. Since many containers are stateless just exposing the option to mount/copy the container image to ram before execution would give a huge speed boost to some jobs with out introducing the need worry about losing volatile memory. While opening the door to moving more complex io bound jobs to ram with some tools for backups/snapshots on persistent storage. 

My 2 cents anyway.

**Comment by noizu** [comment]
@davidak if your compile step is separate from your serve jobs you could run with a -v mount, copy, compile and then push to a data container. I'm trying to brainstorm a similar scenario so if you came up with a good solution I'd love to know what ultimately worked for you.

**Comment by vincentwoo** [comment]
@jfrazelle I think the core feature request of having images, etc live on a normal disk partition but containers run entirely on a ramdisk is a reasonable one. Our container latency is **very** highly correlated with write IOPS. I humbly request that this issue be reopened.

**Comment by cpuguy83** [comment]
If you want to write to ramdisk then mount a volume to the area you want to write to in the container that is a ram disk.
In addition you can use a volume plugin to help automate this for you.

**Comment by vincentwoo** [comment]
That's a very difficult proposition for us. Imagine you're running a PAAS where various customers are running a ton of short lived containers - we know that all of them would benefit from being on a ramdisk, but we can't tune each and every one of them to use a specific volume layout.

Docker lets us treat the rat's nest of modern linux systems as a black box, which lets us do a lot of nifty things, but one of the drawbacks is that we can't precisely know exactly what's happening inside all those containers all the time. This seems like an excellent opportunity to "just throw hardware at it".

**Comment by vincentwoo** [comment]
Actually, upon further research, it might be the case that tinkering with the kernel's dirty write settings might be a better way to go. I'll try to report back with my findings.

**Comment by EvanKrall** [comment]
I also see a lot of docker containers (e.g. code building containers) where IO performance is important for speed, and durability is not.

I would love to see some tunables for this (either the ability to run a container in ramdisk or to otherwise inform the kernel to prefer speed over durability).

@vincentwoo If you find settings that seem to work for you, can you post an update?

**Comment by vincentwoo** [comment]
I was unable to get the OS to play along in a noticeable way, even with dirty settings. I'm toying with trying to mount docker under tmpfs or ramfs, but I don't have anything exciting for you, yet.

**Comment by joelesalas** [comment]
@vincentwoo I'll try a similar experiment.

**Comment by leebenson** [comment]
any luck with your experiments? I'm in exactly the same boat - I have plenty of use cases where I care about speed more than durability.

**Comment by sroegner** [comment]
FWIW we have been using the (Fedora) default storage options but mounted an 80GB TMPFS for /var/lib/docker/devicemapper. We run Hadoop cluster containers in there for integration test targets and using TMPFS effectively cuts overall test runtime in half for us with quite reasonable stability. hth

**Comment by vincentwoo** [comment]
I ran into trouble trying to run overlayfs on top of tmpfs (I'm still not sure you actually *can*). Thanks for your tip!

**Comment by vincentwoo** [comment]
Yeah, tried again to run the entire OverlayFS on top of tmpfs in production, but Docker broke for mysterious reasons eventually. No idea why.

**Comment by kimble** [comment]
Shame that this issue is closed. We also have a lot of situations where speed trumps durability + memory is so cheap now it is a shame not being able to put it to use here.

**Comment by leebenson** [comment]
@kimble with Docker 1.10, you can pass a `--tmpfs` flag to your [run command](https://docs.docker.com/engine/reference/commandline/run/) to mount a ramdisk to your container.

Whilst it's not an entire disk in memory, it'll probably solve the majority of situations that call for temporary caches.

**Comment by bkeroackdsc** [comment]
In my case I want to **build** a container image entirely in RAM (ideally with ``/var/lib/docker`` on a ramdisk), which ``--tmpfs`` does not help at all with.

Please re-open, this is a valid use case.

**Comment by cpuguy83** [comment]
@bkeroackdsc You can already run /var/lib/docker in a ramdisk, but you have to set the  `DOCKER_RAMDISK` env var prior to starting the daemon.

**Comment by bkeroackdsc** [comment]
Oh, interesting. I didn't realize that. Thanks @cpuguy83 !

**Comment by choppsv1** [comment]
I also needed to find this issue to figure this out (it is working from initrd for me now after setting the environ var), but isn't there some way that docker could just detect that it is running with ramdisk as root and not do the pivot_root then? Or perhaps recover from pivot_root failure?

**Comment by NodeGuy** [comment]
I would also like to run some containers entirely in RAM but without all of `/var/lib/docker` in a RAM disk.  Please re-open this issue.

**Comment by frankh** [comment]
An example use-case this would be great for: building and pushing an image which will never be used locally - building on ramdisk would greatly speed it up and there's no need for persistance

**Comment by neolectron** [comment]
+1

**Comment by paralin** [comment]
+1 for sure

**Comment by FengLin-UBNT** [comment]
This is one way to use Ram Disk as docker image directory:
Add one dockerd configuration file: /etc/docker/daemon.json
In that file add these configueation:
```
{
    "graph": "/mnt/ramdisk/docker-imgs"
}
```
Then restart docker service.
The image will save in the ran disk /mnt/ramdisk/docker-imgs

**Comment by paralin** [comment]
That's not really a solution, ideally we would mount the containers upper dir in a ramdisk only.

**Comment by cpuguy83** [comment]
It's not a one shot command, but you can do `--tmpfs /some/write/path --tmpfs /some/other/write/path`

**Comment by paralin** [comment]
In that case loading files from the containers image would not be from RAM

**Comment by cpuguy83** [comment]
@paralin Loading the files wouldn't be from ram either if only the upper dir is tmpfs.

**Comment by paralin** [comment]
True. The main advantage (maybe disadvantage?) I guess of what I'm describing is that the entire container image would have to be in memory, so it's basically preloading everything into ram before starting the container. I suppose you could accomplish the same with mounting a ramfs to a path and then copying what is necessary into it. 

Is it possible to share ramfs between containers?

**Comment by cpuguy83** [comment]
@paralin This (loading the entire container image from mem) is not really feasible on a per-container basis as layers are shared between containers. In addition, depending on the storage driver used, even loaded libraries that are loaded into mem by separate containers can be shared.

So there could either (technically) be just the upper layer in a tmpfs or all images/containers can be in a tmpfs.

**Comment by Skybladev2** [comment]
So, if I understand correctly, specifying tmpfs as a root (`/`) results into that all I/O operations in a container will be performed in memory, but initial container loading will be from disk?

**Comment by cpuguy83** [comment]
If you are referring to doing this for a container, no this will not work.

**Comment by Skybladev2** [comment]
Oh, I get it. Tmpfs path is initially empty and there are no data from the container fs on startup. My bad.

**Comment by cguentherTUChemnitz** [comment]
Can someone help me configuring the following use case? I am running several containers in a default persistent way like the gitlab container and an traefik reverse proxy. On the same docker daemon i am running the gitlab-runner in docker execution mode, which starts internally a docker:dind to encapsulate docker build visibility of different build jobs. Nevertheless, the execution of the gitlab-runner and all containers it starts do not need any persistence. All results are pushed back to the main gitlab as build artifacts. Neverthless the performance impact is quite high, even when in the dind service an overlay2 storage is used. So my goal would be to run the gitlab-runner, the dind and all its encapsulated containers in tmpfs to speed up where the filesystem overlay is slowing down. Does anyone know how to achieve such an container specific tmpfs run environment?

**Comment by Lamaun** [comment]
@cguentherTUChemnitz 
I don't know if I understood this completly but maybe something like my project
https://github.com/lamaun/dockerRAM would do some of the work.

**Comment by lygstate** [comment]
@Lamaun  does your script are getting docker container are running in memory completely?

**Comment by Lamaun** [comment]
My script will put everything the docker snap installs into a tmp fs. If you don't mount anything to the docker container it will also be completely in the tmp fs.
The average docker container should be completely in memory.

**Comment by dgtlmoon** [comment]
The valid reason for doing this is that if you're running extremely IO intensive containers and don't want to burn out your SSD in just a year or so
