### ISSUE TITLE
exec: "time": executable file not found in $PATH

### ISSUE THREAD

**Issue by davidak** [docker/docker#10492]
```
imac:~ davidak$ docker run --rm -t -i ubuntu:14.04 time echo test
exec: "time": executable file not found in $PATHFATA[0000] Error response from daemon: Cannot start container eb691680085f3dc5b031d065d6b5425a609799f6561d93d72724594976556dbd: exec: "time": executable file not found in $PATH
```

i think this is a basic command that should work.

-----

docker version
-----
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): darwin/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8

docker info
---------------
Containers: 10
Images: 12
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Dirs: 32
Execution Driver: native-0.2
Kernel Version: 3.16.7-tinycore64
Operating System: Boot2Docker 1.4.1 (TCL 5.4); master : 86f7ec8 - Tue Dec 16 23:11:29 UTC 2014
CPUs: 8
Total Memory: 1.961 GiB
Name: boot2docker
ID: 4RTC:WSCW:Y44A:YHRX:NZVB:SPVE:AITO:VGRV:7QG3:CNIC:64LD:NFGL
Debug mode (server): true
Debug mode (client): true
Fds: 11
Goroutines: 13
EventsListeners: 0
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker

uname -a
-------------

Darwin imac.lan 10.8.0 Darwin Kernel Version 10.8.0: Tue Jun  7 16:33:36 PDT 2011; root:xnu-1504.15.3~1/RELEASE_I386 i386

Environment details (AWS, VirtualBox, physical, etc.): Mac Installer on OS X 10.6.8

**Comment by tianon** [comment]
`time` is a shell built-in, not a binary, even on my host (which is a fairly full-featured Gentoo box):
```console
$ which time
which: no time in (/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/4.8.3:/opt/android-sdk-update-manager/tools:/opt/android-sdk-update-manager/platform-tools:/usr/games/bin:/opt/vmware/bin)
```

If you instead run via `bash`, it should work:
```console
$ docker run --rm debian bash -c 'time sleep 1'

real	0m1.011s
user	0m0.000s
sys	0m0.001s
```

Alternatively, you can install package [`time`](https://packages.debian.org/jessie/time), which will provide `/usr/bin/time`: https://packages.debian.org/jessie/amd64/time/filelist

**Comment by davidak** [comment]
that solves the problem for me, thanks!
