### ISSUE TITLE
Use `exec` to deal with DVC backups

### ISSUE THREAD

**Issue by kojiromike** [docker/docker#10515]
[Managing data in containers](https://docs.docker.com/userguide/dockervolumes/) recommends using `--volumes-from` and a shared Docker volume container to handle backup and restore with commands like

```
$ sudo docker run --volumes-from dbdata -v $(pwd):/backup ubuntu tar cvf /backup/backup.tar /dbdata
$ sudo docker run -v /dbdata --name dbdata2 ubuntu /bin/bash
$ sudo docker run --volumes-from dbdata2 -v $(pwd):/backup busybox tar xvf /backup/backup.tar
```

But I would venture to say that `exec` is a more modern approach, and allows you to clean and speed up the backup pipeline significantly. To wit:

### Dump a directory to tar
```
$ sudo docker exec -i "$any_container" tar -cf- /target | tar -t
```

### Backup a directory from one container to another

```
$ sudo docker exec -i container_a tar -cf- /source_path | sudo docker exec -i container_b tar -C /dest_path -xf-
```

These approaches will work effectively with both Union and volume paths.

I'm happy to submit a pull request, but I wanted to bounce the idea around first because it would represent a significant change to the existing documentation.

**Comment by ClashTheBunny** [comment]
This is my preferred way of doing it.  I like being able to get to the files even if a user forgot to add "--volumes-from $container" (or, more likely, I forgot...).

**Comment by jfrazelle** [comment]
closing see the reason why in the roadmap https://github.com/docker/docker/blob/master/ROADMAP.md#21-docker-exec
