### ISSUE TITLE
Documentation on boolean flags is wrong

### ISSUE THREAD

**Issue by amouat** [docker/docker#10517]
The documentation on boolean flags at http://docs.docker.com/reference/commandline/cli/#boolean states "... specifying them will set the value to the opposite of the default value". *Thankfully*, this does not seem to be the case, or it would be extremely confusing in the case of default true flags.

For example the `--sig-proxy` flag for `docker run` defaults to true. However, the argument `--sig-proxy` does not turn off signal proxying in my tests, although `--sig-proxy=false` will. 

This is much more important in the case of `docker commit --pause`, which also defaults to true. I haven't managed to test it, but if it works as the documentation states then calling `docker commit --pause` would have the effect of *not* issuing a pause, surely not what the user expects.

Could someone:

 1) Confirm that default true flags are not toggled to false when specified
 2) Update the documentation to reflect this?

Incidentally, It took me a while to figure out what --sig-proxy does - some more docs would be nice (although the main factor here was probably my stupidity).

**Comment by amouat** [comment]
This is confusing enough that I wonder if it would be possible to deprecate any default true flags and change them to negatives. At the moment, the only values for the flags that make sense are `--sig-proxy=false` and `--pause=false`, which isn't very intuitive. Why don't we just create default false alternatives? i.e. `--no-sig-proxy` and `--no-pause`?

**Comment by SvenDowideit** [comment]
frustratingly, the `--no-preference=false` version is also very confusing - there's no really good answer to the dilemma.

I also suspect that documentation was written a very long time ago, so thank you for noting it, I'm re-writing it now.

**Comment by thaJeztah** [comment]
> frustratingly, the --no-preference=false version is also very confusing - there's no really good answer to the dilemma.

Then don't *document* that they accept a value (even thought they do); From an end-users perspective, the flag *itself* becomes the Boolean.

I think that's what I proposed in https://github.com/docker/docker/issues/9406, but it's been a while, lol

**Comment by SvenDowideit** [comment]
@thaJeztah yes, well mmm, that would be a code PR, which could not be merged for 1.5 now - whereas this one, being docs, can :)

**Comment by amouat** [comment]
@SvenDowideit I don't think the situation is unsalvageable :)

My recommendation would be:

 1) fix this issue in the docs and close it
 2) Implement #9406
 3) Deprecate all default true flags in favour of negative versions e.g. `--no-sig-proxy`

At that point I think things will be pretty clear and intuitive. You will still be able to pass `--version=false`, but I don't think this is a big problem as long as it isn't shown to users as the primary way to use to the flag. I can see point 3 being controversial though :(

Thanks for looking at this!

**Comment by thaJeztah** [comment]
> that would be a code PR, which could not be merged for 1.5 now 

Ah, yes, you [mentioned that](https://github.com/docker/docker/issues/9406#issuecomment-65013978) on the other PR. Looks like now I really need to start learning "Go".

@amouat +1, on those steps.

**Comment by amouat** [comment]
I just read the new documentation; it's *much* better. Good job!

I think this can be closed now, not sure if I should do it or leave it to you. If others agree, I'll open a new issue "Deprecate all default true flags in favour of negative versions", but I can see this being controversial!

**Comment by jfrazelle** [comment]
ok cool sgtm
