### ISSUE TITLE
hardcoded * as Access-Control-Allow-Origin value

### ISSUE THREAD

**Issue by alfonsodev** [docker/docker#10532]
Some implementations of CORS doesn't allow `*` as a value for Access-Control-Allow-Origin header.
Currently this  value is hardcoded [in line 1223 of server.go](https://github.com/docker/docker/blob/master/api/server/server.go#L1223)
Parameter --api-enable-cors  could be a string, instead of bool, allowing to pass an arbitrary value to "Access-Control-Allow-Origin" header falling back to `*` as default.

**Comment by resouer** [comment]
@alfonsodev I'd like to fix this. BTW, I suggest to keep "*" as default, as most of the users don't want to set CORS.
