### ISSUE TITLE
Running docker behind a proxy on openSuSE 13.2

### ISSUE THREAD

**Issue by leosaa** [docker/docker#10531]
Hi All,

I'd like to know how to configure docker behind a proxy server.

Thanks in advanced.

**Comment by unclejack** [comment]
Searching the issues for existing similar questions can be very useful: https://github.com/docker/docker/search?q=proxy&state=open&type=Issues&utf8=%E2%9C%93

This isn't a support forum for general questions. There are open issues related to proxies.

I'm going to close this issue as there are no actionable items. Please feel free to comment and discuss.
