### ISSUE TITLE
.dockerignore not used in context with compressed archive

### ISSUE THREAD

**Issue by jaredm4** [docker/docker#10536]
I have a compressed archive, foo.tar.gz. Inside the archive is the Dockerfile, .dockerignore, and supporting app files, etc. When using the archive as context, it seems that the ```.dockerignore``` is ignored.

Repro steps:
### Dockerfile
```
FROM ubuntu:14.04

ADD . /
```
### .dockerignore
```
bar
```
Then add two empty files, ```foo``` and ```bar```. Compress the folder to foo.tar.gz.
```
tar -czf /tmp/foo.tar.gz .
```
Now try to build with it as the context, and verify the contents.
```
$ docker build -t foo - < /tmp/foo.tar.gz
$ docker run -it --rm foo bash
# ls
Dockerfile  bar bin  boot  dev  etc  foo  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
```
You can see both bar and foo in there. Uncompress your archive, repeat steps but use the new dir as context, and bar won't be there.

Docker 1.4.1 w/ Boot2docker.

**Comment by cpuguy83** [comment]
Unless I'm mistaken, I think dockerignore was client only, meaning if you supply a context to the client, it will just upload that to the daemon, daemon wasn't handling it at all.

Can you test with master (or the 1.5 RC build?)

cc @duglin

**Comment by duglin** [comment]
Correct.  .dockerignore is _mainly_ used by the CLI.  The daemon will do a little bit of processing with it, but just to know whether it should remove the .dockerignore or the Dockerfile at the start of the build process.

**Comment by jaredm4** [comment]
Bummer.
