### ISSUE TITLE
[docs] typo on https://docs.docker.com/userguide/dockerlinks/

### ISSUE THREAD

**Issue by j0hnst0n** [docker/docker#10541]
https://docs.docker.com/userguide/dockerlinks/

there's a type-o here "/ets/hosts":

Note: Unlike host entries in the /ets/hosts file, IP addresses stored in the environment variables are not automatically updated if the source container is restarted. We recommend using the host entries in/etc/hosts to resolve the IP address of linked containers.

should be:

Note: Unlike host entries in the /etc/hosts file, IP addresses stored in the environment variables are not automatically updated if the source container is restarted. We recommend using the host entries in/etc/hosts to resolve the IP address of linked containers.

/CC @fredlf @SvenDowideit

**Comment by jfrazelle** [comment]
why don't you want to contribute to docker to fix this Scott :(
