### ISSUE TITLE
iptables -j LOG results in no messages

### ISSUE THREAD

**Issue by bukzor** [docker/docker#10540]
I've installed some iptables rules to a docker image, and while the DROP rules work fine, the LOG rules seem to do nothing. I realize that there's no syslog daemon running by default, but I've tried both rsyslog and syslog-ng, with no success. I can see other messages being written to /var/log/syslog, but none from iptables.

I raised this issue on freenode#docker. @aanm suggested that I should file a bug, after he reproduced the behavior.

**Comment by bukzor** [comment]
I've tried setting --privileged and --cap-add=all, with no result.

**Comment by phemmer** [comment]
The messages are written by the kernel. There is only one kernel, and it's going to write its logs to `/dev/kmsg` on the host.

**Comment by bukzor** [comment]
Shouldn't I see it in the host syslog at that point? I don't.

**Comment by bukzor** [comment]
I can 'echo ok > /dev/kmsg' and see 'ok' from dmesg in both host and container (due to the very elevated privileges I've enabled), but still no iptables logging.

**Comment by phemmer** [comment]
Sorry, misunderstood what you were saying. And you're right, they aren't showing up on the host. This isn't what I expected. Though this would be a kernel issue, not docker. Likely the network namespace is causing issues with the netfilter logger.

**Comment by bukzor** [comment]
I have very little clue how to take this forward from here.
Would you be willing to file a ticket for me?
Also, you'll be able to phrase it in a more believable way than I will.

**Comment by phemmer** [comment]
It's probably best to just shoot an email off to the netfilter mailing list. http://vger.kernel.org/vger-lists.html#netfilter

**Comment by phemmer** [comment]
Also, just as a side note. There have been a few proposals about adding kernel logging namespaces, but none of them have landed yet.
http://lwn.net/Articles/527342/
http://lwn.net/Articles/561271/
http://lwn.net/Articles/562389/

**Comment by jfrazelle** [comment]
@phemmer @bukzor seeing as this is kernel specific issue do you think we can close?

**Comment by ggovindan** [comment]
Hi, I am having to get the log messages of the iptables similar to @bukzor . Can someone please let me know if this is possible now? I am running docker 1.11.2. Thanks

**Comment by phillipp** [comment]
@ggovindan @bukzor I solved this with ulogd and a little trickery:

First, I made the namespace available on thr host: http://stackoverflow.com/questions/31265993/docker-networking-namespace-not-visible-in-ip-netns-list

Then I installed ulogd (on the host), but didn't start it. Then **you start ulogd with ip netns exec**:

```
ip netns exec [yournamespace] ulogd --daemon -c /etc/ulog.dconf --uid ulog
```
You may need to use different config files logging to different files so you don't lose log message, but I didn't test concurrency yet.

Then you add your iptables rules but **not with LOG but NFLOG target**:

```
ip netns exec [yournamespace] iptables -I OUTPUT -j NFLOG --nflog-prefix "FROM INSIDE "
```
et voilà!

**Comment by zx2c4** [comment]
```
echo 1 > /proc/sys/net/netfilter/nf_log_all_netns
```
