### ISSUE TITLE
Problems validating SSL certificate 

### ISSUE THREAD

**Issue by bitliner** [docker/docker#10554]
This happens to me only on AWS Ec2 instances.

Every time an app inside the container (or during building of the image) needs to setup an SSL connection, it fails (error is for example `SSL certificate problem: unable to get local issuer certificate`). For example: wordpress connecting to its plugin repository, pip install while building of the image, etc.

I usually install `ca-certificates` inside the image, but this does not solve the problem.

Am I the only one with this problem?

**Comment by tiborvass** [comment]
@bitliner can you please provide more information on your environment? `docker version`, `docker info`, `uname -a`, if possible the AMI ID too.

**Comment by bitliner** [comment]
**Ami ID**
 `ubuntu-trusty-14.04-amd64-server-20140927 (ami-f0b11187)`
**docker version**
```
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
``` 

**docker info**

```
Containers: 171
Images: 483
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 825
Execution Driver: native-0.2
Kernel Version: 3.13.0-36-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 4
Total Memory: 29.96 GiB
Name: ip-172-32-2-166
ID: E5EA:XLKE:4DPU:V5PJ:YVDS:J2KY:XCNR:AU4U:XR2D:II52:2TXA:WFUI
Username: bitliner
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support
```

**uname -a**
```
Linux ip-172-32-2-166 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by bitliner** [comment]
**Ami ID**
 `ubuntu-trusty-14.04-amd64-server-20140927 (ami-f0b11187)`
**docker version**
```
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
``` 

**docker info**

```
Containers: 171
Images: 483
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 825
Execution Driver: native-0.2
Kernel Version: 3.13.0-36-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 4
Total Memory: 29.96 GiB
Name: ip-172-32-2-166
ID: E5EA:XLKE:4DPU:V5PJ:YVDS:J2KY:XCNR:AU4U:XR2D:II52:2TXA:WFUI
Username: bitliner
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support
```

**uname -a**
```
Linux ip-172-32-2-166 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by tiborvass** [comment]
@bitliner I couldn't find your AMI, but I tried with `ubuntu-trusty-14.04-amd64-server-20150123 (ami-29ebb519)`

I tried with `docker run -it ubuntu`, did `apt-get install curl` inside the container, and then curl'd an HTTPS endpoint successfully.

Are you sure SSL works on the EC2 instance, outside of Docker?

**Comment by bitliner** [comment]
@tiborvass yes, SSL works on the EC2 instance outside of the container.
I was thinking it is the not updated kernel that causes the error, but I have still to reboot the machine to be sure of it. As soon as I will do it, I will let you know

**Comment by tiborvass** [comment]
@bitliner any update on this?

**Comment by bitliner** [comment]
Not yet. If I find enough time this week I will do it, otherwise the machine is not going to be available anymore since next week.

**Comment by cpuguy83** [comment]
I'm going to close this for now, but if you can provide some extra details please ping here and we can discuss.
Thanks!

**Comment by nafg** [comment]
+1, stuck on this for a while

**Comment by senj** [comment]
I'm having the same problem

**Comment by thaJeztah** [comment]
> Cert is only installed on host (but obviously found by container)

@senj how do you mean "obviously found by container"? If the cert is not present inside the container, it cannot use it

**Comment by senj** [comment]
yes, I installed it inside container and works now. Must have been some
not-updatet state.
Am 29.02.2016 12:43 nachm. schrieb "Sebastiaan van Stijn" <
notifications@github.com>:
