### ISSUE TITLE
[docs] docker login does not document semantics

### ISSUE THREAD

**Issue by alexanderkjeldaas** [docker/docker#10550]
The section on docker login does not explain where the "login state" is kept, or what can happen to lose the credentials.  For example, if the credentials are stored in a file, which file is updated?  Does resolving credentials depend on the UID of the current process, the $HOME variable (to find a dot-file), etc.

https://docs.docker.com/reference/commandline/cli/#login

**Comment by thaJeztah** [comment]
Also relates to https://github.com/docker/docker/issues/10338
