### ISSUE TITLE
Stuck at installing nginx image

### ISSUE THREAD

**Issue by ttback** [docker/docker#10559]
I am trying docker on the Mac and following the guide here: https://docs.docker.com/installation/mac/
When executing the `docker run --rm -i -t -p 80:80 nginx` after running `docker run hello-world`, it stuck for a very long time and I am not sure if it is normal. 

````
docker run --rm -i -t -p 80:80 nginx
Unable to find image 'nginx:latest' locally
nginx:latest: The image you are pulling has been verified
30d39e59ffe2: Pull complete
c90d655b99b2: Pull complete
d9ee0b8eeda7: Pull complete
3225d58a895a: Pull complete
224fea58b6cc: Pull complete
ef9d79968cc6: Pull complete
f22d05624ebc: Pull complete
117696d1464e: Pull complete
2ebe3e67fb76: Pull complete
ad82b43d6595: Pull complete
e90c322c3a1c: Pull complete
4b5657a3d162: Pull complete
511136ea3c5a: Already exists
Status: Downloaded newer image for nginx:latest
````
Stuck for 30 min

**Comment by jfrazelle** [comment]
Hi @ttback can you give the output of `docker version` and `docker info`. Also if you think this is more of a support issue and not a problem with docker, we suggest checking out #docker on IRC or https://forums.docker.com/

**Comment by ttback** [comment]
````
docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.4
Git commit (client): 5bc2ff8
OS/Arch (client): darwin/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
````


````
docker info
Containers: 16
Images: 45
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Dirs: 77
Execution Driver: native-0.2
Kernel Version: 3.16.7-tinycore64
Operating System: Boot2Docker 1.4.1 (TCL 5.4); master : 86f7ec8 - Tue Dec 16 23:11:29 UTC 2014
CPUs: 8
Total Memory: 1.961 GiB
Name: boot2docker
ID: 3MJV:WJ6X:TT37:TTDC:N2UP:V4MG:DDMQ:5MTU:HWLJ:FHWG:P34N:2ZDV
Debug mode (server): true
Debug mode (client): false
Fds: 11
Goroutines: 13
EventsListeners: 0
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
````

**Comment by jfrazelle** [comment]
I think this is correct there is no output but the container is running ;)
did you check docker ps in a new tab or open `boot2docker ip` on the port you exposed for nginx

**Comment by jfrazelle** [comment]
I'm going to close because I think this was a misunderstanding, but let me know if otherwise, also #docker on freenode is great for support for docker, the github issues are more for problems with docker itself
