### ISSUE TITLE
`docker.service` lacks the `--graph` option: docker won't run

### ISSUE THREAD

**Issue by jotrk** [docker/docker#10551]
Description of problem:

The supplied `docker.service` file from `docker/contrib/init/systemd` is missing
the `--graph` option. Without it, docker doesn't find the socket file from
`docker.socket` and refuses to run.

`docker version`:

Docker version 1.4.1, build 5bc2ff8

`docker info`:

Containers: 3
Images: 6
Storage Driver: devicemapper
 Pool Name: docker-0:15-20654789-pool
 Pool Blocksize: 65.54 kB
 Data file: /run/devicemapper/devicemapper/data
 Metadata file: /run/devicemapper/devicemapper/metadata
 Data Space Used: 3.714 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 3.035 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.92 (2014-11-28)
Execution Driver: native-0.2
Kernel Version: 3.15.2-1-ARCH
Operating System: Arch Linux
CPUs: 4
Total Memory: 7.688 GiB
Name: phobos
ID: KTL5:XAYG:2CV3:6GGC:5RNZ:37D4:KLNM:PJTN:ISR7:VGVI:A2ER:GPWZ
WARNING: No swap limit support

`uname -a`:

Linux phobos 3.15.2-1-ARCH #1 SMP PREEMPT Fri Jun 27 07:41:19 CEST 2014 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):

physical

How reproducible:

Always

Steps to Reproduce:
1. Install docker
2. Use `docker.service` and `docker.socket` from `docker/contrib/init/systemd` to run docker.
3. Docker won't run

Actual Results:

Docker is not running

Expected Results:

Docker should be up and running, listening on the fd from the `docker.socket` file

Additional info:

http://bugs.archlinux.org/task/43691

Fixing this is easy:

--- docker.service.orig 2014-12-19 15:28:47.000000000 +0100
+++ docker.service 2015-02-03 21:38:40.516301805 +0100
@@ -5,7 +5,7 @@
Requires=docker.socket

[Service]
-ExecStart=/usr/bin/docker -d -H fd://
+ExecStart=/usr/bin/docker -d -g /var/run -H fd://
LimitNOFILE=1048576
LimitNPROC=1048576

**Comment by resouer** [comment]
Sorry, but I can not reproduce this on coreos. And I think docker use docker.sock from /var/run, not from /var/lib/docker (the default graph dir). Have you verified this by yourself?

**Comment by unclejack** [comment]
@jotrk @resouer Please provide the output of the `mount` command on the systems where you're seeing these problems.

**Comment by jasonalmansor** [comment]
@jotrk while I've not had an issue with docker starting because of this, I think this would be the correct way to fix the docker.service file to allow for arguments to properly be added:

[Service]
EnvironmentFile=-/etc/sysconfig/docker
ExecStart=/usr/bin/docker -d -H fd:// $OPTIONS

then in /etc/sysconfig/docker:
OPTIONS=" "

**Comment by jotrk** [comment]
@unclejack 

    $ mount
    proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
    sys on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
    dev on /dev type devtmpfs (rw,nosuid,relatime,size=4027092k,nr_inodes=1006773,mode=755)
    run on /run type tmpfs (rw,nosuid,nodev,relatime,mode=755)
    /dev/mapper/vgphobos00-lvroot on / type ext4 (rw,relatime,discard,commit=360,data=ordered)
    securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
    tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=524288k)
    devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
    tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
    cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
    pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
    cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
    cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
    cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
    cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
    cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
    cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls)
    cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
    systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=22,pgrp=1,timeout=300,minproto=5,maxproto=5,direct)
    hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime)
    mqueue on /dev/mqueue type mqueue (rw,relatime)
    debugfs on /sys/kernel/debug type debugfs (rw,relatime)
    configfs on /sys/kernel/config type configfs (rw,relatime)
    tmpfs on /tmp type tmpfs (rw,nosuid,nodev,relatime)
    tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=806100k,mode=700,uid=1000,gid=100)
    binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
    run on /run/devicemapper type tmpfs (rw,nosuid,nodev,relatime,mode=755)

@resouer 
I tried running docker without systemd, and I had to specify the graph dir explicitely. (There's also no `docker.sock` in `/var/lib/docker`.

@jasonalmansor 
I don't know, the `docker.socket` file has `/var/run/docker.sock` already hardcoded. It's obviously different to the default graph path (`/var/lib/docker`). So, there are three options.
1) Overriding the default graph path directly in `docker.service`
2) Creating the socket in `/var/lib/docker` through `docker.socket`, which is probably non-standard for systemd (?)
3) Using your method and add additional complexity, which is imho not good for default config

**Comment by resouer** [comment]
mount info:

/dev/mapper/ubuntu--vg-root on / type ext4 (rw,errors=remount-ro)
proc on /proc type proc (rw,noexec,nosuid,nodev)
sysfs on /sys type sysfs (rw,noexec,nosuid,nodev)
none on /sys/fs/cgroup type tmpfs (rw)
none on /sys/fs/fuse/connections type fusectl (rw)
none on /sys/kernel/debug type debugfs (rw)
none on /sys/kernel/security type securityfs (rw)
udev on /dev type devtmpfs (rw,mode=0755)
devpts on /dev/pts type devpts (rw,noexec,nosuid,gid=5,mode=0620)
tmpfs on /run type tmpfs (rw,noexec,nosuid,size=10%,mode=0755)
none on /run/lock type tmpfs (rw,noexec,nosuid,nodev,size=5242880)
none on /run/shm type tmpfs (rw,nosuid,nodev)
none on /run/user type tmpfs (rw,noexec,nosuid,nodev,size=104857600,mode=0755)
none on /sys/fs/pstore type pstore (rw)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
/dev/sda1 on /boot type ext2 (rw)
systemd on /sys/fs/cgroup/systemd type cgroup (rw,noexec,nosuid,nodev,none,name=systemd)
vmware-vmblock on /run/vmblock-fuse type fuse.vmware-vmblock (rw,nosuid,nodev,default_permissions,allow_other)
gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,user=harryz)
proc on /home/harryz/Documents/workspace_docker/namespace/proc type proc (rw)

**Comment by phemmer** [comment]
I think there's a lot of confusion here.

* The graph directory has nothing to do with the socket docker listens on. The graph directory is where docker stores images and other data.
* The graph directory is controlled via `docker --graph`. The socket path is controlled via `docker --host`.
* The socket path defaults to `/var/run/docker.sock`.
* The socket provided by the `docker.socket` systemd unit is completely unrelated to the `docker --host` option as well. Systemd creates the socket file before docker is even running, and then passes docker an open file descriptor for the socket, upon which docker then starts listening. Meaning docker doesn't have to know the path of the socket file, or search for it.

**Comment by jotrk** [comment]
@phemmer

So what's my problem then?

    $ dir /var/run/docker.*
    -rw-r--r-- 1 root root   5  6. Feb 13:02 /var/run/docker.pid
    srw-rw---- 1 root docker 0  3. Feb 21:38 /var/run/docker.sock=

    $ su -g docker root -c "docker -d -H fd://*"
    INFO[0000] +job serveapi(fd://*)
    INFO[0000] Listening for HTTP on fd (*)
    FATA[0000] EOF

    $ su -g docker root -c "docker -d -H fd://"
    INFO[0000] +job serveapi(fd://)
    INFO[0000] Listening for HTTP on fd ()
    No sockets found
    INFO[0000] -job serveapi(fd://) = ERR (1)
    FATA[0000] No sockets found

    $ su -g docker root -c "docker -d -H unix:///var/run/docker.sock"
    INFO[0000] +job serveapi(unix:///var/run/docker.sock)
    FATA[0000] EOF

    $ su -g docker root -c "docker -d -g /var/run -H fd://"
    INFO[0000] +job serveapi(fd://)
    INFO[0000] +job init_networkdriver()
    INFO[0000] Listening for HTTP on fd ()
    No sockets found
    INFO[0000] -job serveapi(fd://) = ERR (1)
    FATA[0000] No sockets found

**Comment by phemmer** [comment]
As you saw, the `docker.service` systemd unit uses the following command to start docker:

    /usr/bin/docker -d -H fd://

Running this command by hand (`su -g docker root -c "-d -H fd://"`) is not the same as systemd running it. Going back to that bit in my comment earlier, "Systemd creates the socket file before docker is even running, and then passes docker an open file descriptor for the socket". When you start it by hand, this isn't happening. You're not passing it an open file descriptor.

However, running it as `docker -d -H unix:///var/run/docker.sock` *should* work. The simple `EOF` error message you're getting is extremely unhelpful :-( (not your fault, docker's fault).
You can try starting with `-D` to enable debug output, but I have a feeling this isn't going to provide much more information. At this point, someone more familiar with this portion of the code (the startup & initialization code) will probably need to step in.

**Comment by jotrk** [comment]
$ su -g docker root -c "docker -D -d -H unix:///var/run/docker.sock"
    INFO[0000] +job serveapi(unix:///var/run/docker.sock)
    INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
    DEBU[0000] Registering GET, /_ping
    DEBU[0000] Registering GET, /events
    DEBU[0000] Registering GET, /version
    DEBU[0000] Registering GET, /containers/{name:.*}/changes
    DEBU[0000] Registering GET, /images/viz
    DEBU[0000] Registering GET, /images/get
    DEBU[0000] Registering GET, /containers/ps
    DEBU[0000] Registering GET, /containers/json
    DEBU[0000] Registering GET, /containers/{name:.*}/top
    DEBU[0000] Registering GET, /containers/{name:.*}/attach/ws
    DEBU[0000] Registering GET, /images/search
    DEBU[0000] Registering GET, /images/{name:.*}/get
    DEBU[0000] Registering GET, /images/{name:.*}/history
    DEBU[0000] Registering GET, /containers/{name:.*}/export
    DEBU[0000] Registering GET, /containers/{name:.*}/json
    DEBU[0000] Registering GET, /exec/{id:.*}/json
    DEBU[0000] Registering GET, /info
    DEBU[0000] Registering GET, /images/json
    DEBU[0000] Registering GET, /images/{name:.*}/json
    DEBU[0000] Registering GET, /containers/{name:.*}/logs
    DEBU[0000] Registering POST, /containers/{name:.*}/unpause
    DEBU[0000] Registering POST, /containers/{name:.*}/restart
    DEBU[0000] Registering POST, /containers/{name:.*}/start
    DEBU[0000] Registering POST, /containers/{name:.*}/stop
    DEBU[0000] Registering POST, /containers/{name:.*}/wait
    DEBU[0000] Registering POST, /containers/{name:.*}/exec
    DEBU[0000] Registering POST, /images/create
    DEBU[0000] Registering POST, /images/{name:.*}/push
    DEBU[0000] Registering POST, /exec/{name:.*}/resize
    DEBU[0000] Registering POST, /containers/{name:.*}/kill
    DEBU[0000] Registering POST, /commit
    DEBU[0000] Registering POST, /build
    DEBU[0000] Registering POST, /containers/{name:.*}/pause
    DEBU[0000] Registering POST, /containers/{name:.*}/attach
    DEBU[0000] Registering POST, /exec/{name:.*}/start
    DEBU[0000] Registering POST, /auth
    DEBU[0000] Registering POST, /images/{name:.*}/tag
    DEBU[0000] Registering POST, /containers/{name:.*}/resize
    DEBU[0000] Registering POST, /containers/{name:.*}/copy
    DEBU[0000] Registering POST, /images/load
    DEBU[0000] Registering POST, /containers/create
    DEBU[0000] Registering DELETE, /images/{name:.*}
    DEBU[0000] Registering DELETE, /containers/{name:.*}
    DEBU[0000] Registering OPTIONS,
    DEBU[0000] docker group found. gid: 142
    DEBU[0000] Generated prefix: docker-254:1-286556
    DEBU[0000] Checking for existence of the pool 'docker-254:1-286556-pool'
    FATA[0000] EOF

[Here](http://pastebin.com/it9sfHku)'s an strace. The relevant portions are probably

    readlink("/proc/self/fd/5", 0xc20804e880, 128) = -1 ENOENT (No such file or directory)
    open("/var/lib/docker/devicemapper/devicemapper/json", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

**Comment by phemmer** [comment]
I don't know that the missing `json` is the cause of the issue. It might be handled gracefully. For example, if the file is missing, docker creates it. If it were the issue, I would expect the error to be `No such file or directory` (or similar), not `EOF`. But this is just theory based on typical application design. I haven't dived into the relevant code here.

**Comment by jotrk** [comment]
Hm, that's odd. Something must have gone awfully wrong after the installation. I moved `/var/lib/docker` out of the way and now everything works as advertised. Most likely just another case of PEBCAK. In that case I'd like to apologize to everyone for the noise. Otoh, I still don't know why docker wouldn't start right after the installation.

Anyway, is there still interest in this, or shall I close the issue?

**Comment by jfrazelle** [comment]
Hmm I think I am going to close but if someone else finds this and has the same problem feel free to ping me, also thanks @phemmer for being so responsive :)
