### ISSUE TITLE
Docker exits with success status after "Command not found" error

### ISSUE THREAD

**Issue by gfxmonk** [docker/docker#10579]
$ docker do-something-very-important >/dev/null 2>&1 && echo "yup, everything is fine!"
    yup, everything is fine!

This means that an automated process invoking docker won't know that something is wrong, and will probably fail for confusing reasons sometime later.

(I'm not actually sending my logs to /dev/null, that was for dramatic effect. But an error is no good if it's only discovered by manual inspection of logs.)

**Comment by duglin** [comment]
I believe this has been fixed. When I use the latest code I see this:
```
$docker foo
docker: 'foo' is not a docker command. See 'docker --help'.
$echo $?
1
```

**Comment by gfxmonk** [comment]
Ahh, my apologies - I'm using 1.4.1, and couldn't find any previous issues / PRs which fixed it since then. Thanks!
