### ISSUE TITLE
could not read file "...." permission denied on OpenSuse 13.1/regression in Docker 1.5.0

### ISSUE THREAD

**Issue by zopyx** [docker/docker#10582]
Building this Docker image

https://github.com/xml-director/xmldirector.plonecore/tree/master/docker/base

on OpenSuse 13.1 fails with a weird permission denied error although the file exists.

This happens with Docker 1.5.0 - perhaps a regression - however building the same image
on two other systems running Docker 1.5.0 on Ubuntu 14 works as expected.

jung@blackmoon2:~/src/xmldirector.plonecore/docker/base> who am i 
ajung    pts/0        2015-02-05 07:52 (:0)
ajung@blackmoon2:~/src/xmldirector.plonecore/docker/base> groups
users docker
ajung@blackmoon2:~/src/xmldirector.plonecore/docker/base> ls -la
total 12
drwx------ 1 ajung users   66 Feb  1 13:28 .
drwx------ 1 ajung users  114 Feb  1 13:28 ..
-rw------- 1 ajung users 1098 Feb  1 13:28 Dockerfile
-rw------- 1 ajung users  487 Feb  1 13:28 exist-setup.cmd
-rw------- 1 ajung users  237 Feb  1 13:28 Makefile
ajung@blackmoon2:~/src/xmldirector.plonecore/docker/base> make
docker build --no-cache=false -t zopyx/xmldirector-base .
Sending build context to Docker daemon  5.12 kB
Sending build context to Docker daemon 
Step 0 : FROM dockerfile/java:oracle-java7
 ---> 6f2d4b7c53a2
Step 1 : MAINTAINER Andreas Jung <info@zopyx.com>
 ---> Using cache
 ---> e67cca183e75
Step 2 : RUN apt-get update
 ---> Using cache
 ---> 3371ddf5b336
Step 3 : RUN apt-get install -y     python-virtualenv     python     curl expect     build-essential     libssl-dev     libxml2-dev     libxslt1-dev     libbz2-dev     zlib1g-dev     python-setuptools     python-dev     libjpeg62-dev     libreadline-gplv2-dev     python-imaging     wv     python-dev     libxml2-dev     libxslt1-dev     git-core
 ---> Using cache
 ---> 64a1066af0f3
Step 4 : RUN useradd -ms /bin/bash plone
 ---> Using cache
 ---> 0ad5d4d3beb6
Step 5 : USER plone
 ---> Using cache
 ---> cb7b294048fe
Step 6 : WORKDIR /home/plone
 ---> Using cache
 ---> ab060db59afc
Step 7 : RUN curl -LO http://downloads.sourceforge.net/exist/Stable/2.2/eXist-db-setup-2.2.jar
 ---> Using cache
 ---> e0870f14ff59
Step 8 : ADD exist-setup.cmd /home/plone/exist-setup.cmd
 ---> Using cache
 ---> dfe080d9cbc5
Step 9 : RUN expect -f exist-setup.cmd
 ---> Running in d48061a86bc4
couldn't read file "exist-setup.cmd": permission denied
INFO[0003] The command [/bin/sh -c expect -f exist-setup.cmd] returned a non-zero code: 1 
make: *** [build] Error 1

ajung@blackmoon2:~/src/xmldirector.plonecore/docker/base> docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): 5bf46a5
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): 5bf46a5
ajung@blackmoon2:~/src/xmldirector.plonecore/docker/base> docker -D info
Containers: 24
Images: 153
Storage Driver: btrfs
Execution Driver: native-0.2
Kernel Version: 3.11.10-25-desktop
Operating System: openSUSE 13.1 (Bottle) (x86_64) (containerized)
CPUs: 4
Total Memory: 7.503 GiB
Name: blackmoon2
ID: EOHW:JIIK:QDJ6:AGX4:ZEA5:FA7J:FYGV:RJYI:TPYV:4AEH:RAWG:BGTN
Debug mode (server): false
Debug mode (client): true
Fds: 12
Goroutines: 17
EventsListeners: 0
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker
Username: zopyx
Registry: [https://index.docker.io/v1/]

**Comment by phemmer** [comment]
What are the file permissions on `exist-setup.cmd` from the host? When you perform an `ADD`, the file owner and group are set to root (`0` really). Thus unless the file is readable by 'other', the user inside the container will not be able to read the file.

**Comment by zopyx** [comment]
The local file is only readable for the owner - this explains the behavior  - compared to the other machine where the file is readable for everyone due to a different umask  used while checking out the repos.

However this behavior of Docker is _stupid_. A Docker build must be repeatable and consistent. Depending on local filesystem permissions and carrying them forward into the Docker appears wild. On one side you care about local settings and in other cases the Dockerfile needs to care about permissions and owership using chmod + chown.

**Comment by calavera** [comment]
When you build an image, docker creates a copy of your file system. It's impossible to detect differences between two completely different machines unless you're explicit about permissions in your dockerfile.

We'll soon have user namespaces that will allow people to have full control of permissions inside containers. Check #12648 out, it's super interesting.

I'm closing this issue. Thanks for reaching out.
