### ISSUE TITLE
Docker Registry doesn't updated short description from README-short.txt

### ISSUE THREAD

**Issue by nerro** [docker/docker#10588]
Description of problem:
It's probably not a bug but a question. After adding the file `README-short.txt`, a short description in my repository on the official registry was not updated (I changed it manually).

GitHub Repo: https://github.com/nerro/docker-images/tree/master/base/wheezy
Docker Hub Registry Repo: https://registry.hub.docker.com/u/nerro/base
Docker Registry Build Id: https://registry.hub.docker.com/u/nerro/base/build_id/38195/code/bqrsktxejjzjtlmmrkeumjn

`docker version` from Docker Registry:

    Client version: 1.4.1
    Client API version: 1.16
    Go version (client): go1.3.3
    Git commit (client): 5bc2ff8
    OS/Arch (client): linux/amd64
    Server version: 1.4.1
    Server API version: 1.16
    Go version (server): go1.3.3
    Git commit (server): 5bc2ff8

**Comment by cpuguy83** [comment]
I'm pretty sure automated builds only pull in the README.md
README-short.txt is for official image repos (which are completely separate).

Any issues you have with DockerHub please send to support@docker.com

Closing since this isn't a docker issue.

**Comment by nerro** [comment]
Thanks for quickly response.

You are right with official image repos (https://docs.docker.com/docker-hub/official_repos/).

**Comment by wouterds** [comment]
It would make sense to have this for automated builds as well imho.
