### ISSUE TITLE
Default directory change fails - systemd seems to ignore docker.service modification

### ISSUE THREAD

**Issue by dlykissas** [docker/docker#10587]
TL;DR; I want the PULL-ed images and the containers on a separate partition but Docker does not respond to configuration.

I have changed the 'docker.service' file as per the instructions on 'https://docs.docker.com/articles/systemd/'. In my 'docker.service' I have added 'EnvironmentFile=-/srv/docker/docker.conf' under the '[Service]' section. In the '/srv/docker/docker.conf' file I have 'OPTIONS="--graph /srv/docker --storage btrfs'. In spite of these configuration changes, when I PULL an image it is not stored inside the '/srv/docker' directory. Any ideas why is this?

**Comment by unclejack** [comment]
@dlykissas Please provide the full config files - both the systemd unit and the docker.conf..

**Comment by dlykissas** [comment]
@unclejack Of course!

The 'docker.service' file is this: http://pastebin.com/vqT1Lc70
The 'docker.conf' file is this: http://pastebin.com/3SUtebgY

Thanks a lot for showing interest.

**Comment by phemmer** [comment]
There's one critical difference in the `.service` file mentioned in the documentation:

    ExecStart=/usr/bin/docker -d -H fd:// $OPTIONS

Note the `$OPTIONS` at the end of the line.

When you use `EnvironmentFile=-/srv/docker/docker.conf`, all you're doing is telling systemd to load environment variables from the specified file. Something has to use those environment variables, and the `$OPTIONS` variable isn't treated specially by the docker daemon.

**Comment by dlykissas** [comment]
@phemmer Will test and report back within the hour (with some luck).

**Comment by dlykissas** [comment]
@phemmer I replaced "ExecStart=/usr/bin/docker -d -H fd://" with "ExecStart=/usr/bin/docker -d -H fd:// $OPTIONS". This had no effect at all. The images are PULL-ed correctly but not stored in the directory specified by "docker.conf". Can you please point me to the exact correct syntax?

**Comment by dlykissas** [comment]
@phemmer I made the change you suggested.

The updated 'docker.service' file is this: http://pastebin.com/d8Y0FQQh
The updated 'docker.conf' file is this: http://pastebin.com/p11xJWnY

The daemon starts and PULLs images correctly. But, the issue is still present. Nothing is stored inside the '/srv/docker' directory.

**Comment by phemmer** [comment]
Your `docker.conf` is now invalid. Your first one was fine.

    OPTIONS="--graph /srv/docker --storage btrfs"

Not 

    $OPTIONS="--graph /srv/docker --storage btrfs"

**Comment by dlykissas** [comment]
First off, thanks to all for their contributions. The issue was with the command line options. In the docs for version 1.4 (the one I have) the argument for storage is given as:
```--storage btrfs```
In actuality, the correct syntax is:
```--storage-driver btrfs```
Now, I do not know why there is this discrepancy between the online docs and 'docker --help' (this is where the correct form is referenced). 
Again thanks to all, and I really hope the docs for this wonderful piece of S/W get fixed.
