### ISSUE TITLE
manifest: newManifest() does not call Close() on archive

### ISSUE THREAD

**Issue by rhvgoyal** [docker/docker#10593]
newManifest() can call into TarLayer() to get tar of a layer and that will return an archive. But once we are done, we never call archive.Close() on archive. That means any resources (like mounted device) by archive are not released. Which in turn lead to more problems later once somebody tries to delete a layer and device deletion fails as it is still mounted.

Fix this by calling Close() on archive once caller is done using the archive.

**Comment by crosbymichael** [comment]
#10596 was merged so tis can be closed
