### ISSUE TITLE
Issue with container's /etc/hosts file (it is empty for the container but not for the host) when you use VOLUME /etc in your Dockerfile

### ISSUE THREAD

**Issue by ctmnz** [docker/docker#10604]
My dockerfile:

FROM centos:centos6
VOLUME /etc
CMD /bin/bash

I build my docker image
$ docker build -t bugdemo .

I start db container, in order to link bugdemo's container to it.
$ docker run -ti -e MYSQL_ROOT_PASSWORD=pass -d --name db mysql

I start bugdemo's container 
$ docker run -ti -d --link db:db --name bugdemo bugdemo /bin/bash

$ docker attach bugdemo
$ cat /etc/hosts
$
(empty)

But....
CTRL+P+Q

$  docker inspect -f {{.HostsPath}} bugdemo
/var/lib/docker/containers/cd3b0857959a25a1eb05ba5939f071cfda6c4744897217e7eb63101af58d7124/hosts

$ cat /var/lib/docker/containers/cd3b0857959a25a1eb05ba5939f071cfda6c4744897217e7eb63101af58d7124/hosts

172.17.0.9      cd3b0857959a
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
127.0.0.1       localhost
172.17.0.7      db

I'm not quite sure if this is a bug or I shoot myself in the foot with 'volume /etc' line but reported it anyway :-)

**Comment by estesp** [comment]
Maybe it would be helpful to know what you were wanting to achieve with the `VOLUME /etc` directive in your Dockerfile.

Because the /etc/{hosts,resolv.conf,hostname} files are bind-mounted into your container at runtime, there is now a conflict between your bind-mounted VOLUME /etc and the single file mounts.. I didn't spend enough time to figure out if that could be corrected, but again, in a sense you are right that you shot yourself in the foot :) So, maybe start with what the `VOLUME` declaration was for and then we can figure out what the right next step is.

**Comment by ctmnz** [comment]
Oh... the buggy situation is result of our experimenting with Docker. I needed a quick way to check/change realtime configuration files in /etc in PHP + Apache container. When I started to use "VOLUME /etc" the container became unable to connect to linked mysql container with error "Host not found". When I made quick check of /etc/hosts file via host with "docker inspect -f {{.HostsPath}} bugdemo" and 'cat' the host file , the content was fine and there were a line for the linked mysql container. I started checking my application for errors, but none were found.  Then I checked the /etc/hosts in PHP+Apache container and it was empty. I decided to report it as a bug because checking the /etc/hosts file from the host and within the container gives us different content and it is possible to mislead when someone is debugging a problem.

**Comment by coolljt0725** [comment]
@estesp is right, the docker will mount `/etc/{hosts,resolv.conf,hostname}` to container first, and then mount the user specified volumes. In this case, `VOLUME /etc` will cover the   `/etc/{hosts,resolv.conf,hostname}` which are mounted first. I think create a volume `/etc` is not a good choice.

**Comment by ctmnz** [comment]
@coolljt0725 I agree with you. Yes, creating a volume /etc is not a good choice.

**Comment by coolljt0725** [comment]
@ctmnz  At some point, create a `/etc` volume may be reasonable just as you said "I needed a quick way to check/change realtime configuration files in /etc" , so I create PR #10615.
