### ISSUE TITLE
Strange volume permissions

### ISSUE THREAD

**Issue by jkubrynski** [docker/docker#10603]
I've exposed container volume using `-v` parameter providing host and container paths. I've the same uid and gid on the host as well as in the container. Situation with normal directories is OK, but there are some strange permission problems with exposed directory:
```
$ id  
uid=2000(docker) gid=2000(docker) groups=2000(docker)
$ ls -ln
total 2
drwxr-xr-x. 11 2000 2000 4096 Jan 26 22:49 app
drwxr-xr-x.  2 2000 2000   14 Feb  6 00:57 app-home
$ cd app-home
$ ls
ls: cannot open directory .: Permission denied
```

**Comment by estesp** [comment]
Is there a Dockerfile for your container?  Could you provide it here? Specifically I'm curious if `app-home` is created there (potentially owned by `root:root`), and then your -v bind-mounts over that?  There is a known AUFS bug about permission "loosening" of upper layers over lower layers, so `docker info` and `docker version` output would be helpful as well.

**Comment by jkubrynski** [comment]
app-home is created in my dockerfile and when I don't add -v to the run
command it's owned by proper user. After adding -v parameter with host and
container paths the problem occurs.
6 lut 2015 04:55 "Phil Estes" <notifications@github.com> napisał(a):

**Comment by cpuguy83** [comment]
@jkubrynski `docker info` would really help.
Are you using an selinux enabled host OS?

**Comment by jkubrynski** [comment]
Yes, selinux is enabled.

docker info output:
Storage Driver: devicemapper
 Pool Name: docker-253:1-135714102-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 4.915 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 5.128 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.84-RHEL7 (2014-03-26)
Execution Driver: native-0.2
Kernel Version: 3.10.0-123.13.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)

**Comment by cpuguy83** [comment]
@jkubrynski You need to set an selinux label for that host dir so the container can access it:
`chcon -Rt svirt_sandbox_file_t host_dir`

See #5910 for work being done to be able to set this up automatically through Docker.
