### ISSUE TITLE
docker bash autocompletion fails with 'unary operator expected '

### ISSUE THREAD

**Issue by hayderimran7** [docker/docker#10600]
I just installed docker.io on fresh ubuntu 14.04 environment, after adding my jenkins user to docker group, i tested docker commands and worked fine.
 I did a source the autocompletion script of docker.io for my convenience by doing :+1: 
` source /etc/bash_completion.d/docker.io `
but when tested the autocompletion, its throwing this error for me : 
```
jenkins@VPCSA290X:/home/jenkins$ docker im_get_comp_words_by_ref: command not found
bash: [: 1: unary operator expected
```
any help/suggestion appreciated in this ..

**Comment by jfrazelle** [comment]
does the ubuntu docker.io package use our bash completions I wonder, how
about you try replacing the one in their file with the one in
contrib/completions/bash/docker and see what happens?

**Comment by hayderimran7** [comment]
thanks its solved now.. the issue wasnt anything with autocompletion script . but a missing .bashrc file for my 'jenkins' user.
as someone in irc pointed, i had a missing .bashrc , now its working :)
thanks for help  !
