### ISSUE TITLE
CONFIG_OVERLAY_FS: missing

### ISSUE THREAD

**Issue by aerodame** [docker/docker#10626]
I've run the check-config.sh program (provided by @unclejack) on Debian 8.0, but have one final "missing" statement.  What does this error indicate and what is the recommended resolution?

**Comment by jfrazelle** [comment]
You do not need that to pass unless you intend on using the overlay fs.

**Comment by jfrazelle** [comment]
The overlay filesystem requires a kernel of 3.18 or higher
