### ISSUE TITLE
Help with supporting ARM 32-bit QuadCore Microservers

### ISSUE THREAD

**Issue by aerodame** [docker/docker#10627]
@shykes @kencochrane 
We are very keen on getting a cluster of Debian CuBox (i.MX6) microservers up and running with Docker.  These are probably the most power efficient Linux boxes on the planet that also can be configured to run a large SSD filesystem and up to 4GB of DRAM. 

Problem is they are all ARM A9 32-bit Linux machines with the following configuration...
uname -a
=> Linux cubox-i 3.14.14-cubox #1 SMP Thu Dec 18 13:19:43 CET 2014 armv7l armv7l armv7l GNU/Linux

Can you help direct to some specific instructions on how to cross compile Docker for operation on this platform? Something similar to what the Resin.io guys did for Raspberry PI, but for a much more powerful ARM A9 processor.  I followed @kencochrane and his Raspberry Pi attempt, but it seemed to hit a dead end where a cross compile of Docker is required.

Here's check-config.sh run against the 32-bit ARM Linux platform to determine what is missing?

Looks like everything is almost there (except for aufs and overlay) !

root@cubox-i:~# ./check-config.sh 
info: reading kernel config from /proc/config.gz ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_MACVLAN: enabled
- CONFIG_VETH: enabled
- CONFIG_BRIDGE: enabled
- CONFIG_NF_NAT_IPV4: enabled
- CONFIG_IP_NF_FILTER: enabled
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled
- CONFIG_NF_NAT: enabled
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_MEMCG_SWAP: enabled
- CONFIG_RESOURCE_COUNTERS: enabled
- CONFIG_CGROUP_PERF: enabled
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: missing
    - CONFIG_EXT4_FS_POSIX_ACL: enabled
    - CONFIG_EXT4_FS_SECURITY: enabled
  - "btrfs":
    - CONFIG_BTRFS_FS: enabled
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: enabled
    - CONFIG_DM_THIN_PROVISIONING: enabled
    - CONFIG_EXT4_FS: enabled
    - CONFIG_EXT4_FS_POSIX_ACL: enabled
    - CONFIG_EXT4_FS_SECURITY: enabled
  - "overlay":
    - CONFIG_OVERLAY_FS: missing

**Comment by djmaze** [comment]
If you are not settled on Debian, I can warmly recommend installing Arch Linux ARM instead, which includes the latest Docker version. It's running smooth for me on several ODROID servers (with btrfs). [The CuBox-i is also supported](http://archlinuxarm.org/platforms/armv7/freescale/cubox-i).

If you do not want to use Arch, having a look at the [PKGBUILD for the latest Docker version](https://github.com/archlinuxarm/PKGBUILDs/blob/master/community/docker/PKGBUILD), it seems that 1.5.0 does not need any ARM specific patches anymore. Which should be good news for people compiling on other distributions as well.

**Comment by crosbymichael** [comment]
Lets close this one and move the discussion to #9207.  gccgo is a way to build go with ARM support and I think you will find alot more help and discussion in that issue.  Thanks!
