### ISSUE TITLE
Proposal: Add -pull flag for docker run to re pull a existing img if newer exist befor running a container

### ISSUE THREAD

**Issue by frank-dspeed** [docker/docker#10639]
Hello as we know docker run will pull a image if it is not there lets expect the case we use no : version it will pull latest what is realy great but now expect the image has changed and not changed version or is still latest so docker will not repull that img if it is there. 

That is the point where this proposal hooks in we should add a flag like --repull to the run command to initate a pull (check for update) and then run the img that would help deploy and would maybe even be suggested by some users.

sure you can always do a script that does docker pull then docker run but a flag is maybe not wrong to what do you think=?

**Comment by thaJeztah** [comment]
+1;  `docker build --pull` was added in 1.4.1 (see https://github.com/docker/docker/pull/9281), this would do the same for `docker run`, which would be a nice addition.

**Comment by jfrazelle** [comment]
@tianon didn't you have something as a fix for this ;)

**Comment by tianon** [comment]
@jfrazelle you meanie :wink:

**Comment by jfrazelle** [comment]
Closing for @tianons proposal in 10693 :) super excited because I want this too

**Comment by thaJeztah** [comment]
LOL I had to actually look twice because the issue numbers have jus two digits swapped. Anyway this issue it is; https://github.com/docker/docker/issues/10693
