### ISSUE TITLE
Problems with understanding filtering of docker events

### ISSUE THREAD

**Issue by albers** [docker/docker#10645]
I'm curently working on bash completion for docker events.
Therefore I'm trying to understand the possible arguments for the _container_ and _image_ filters,
Please let me know whether my findings are misinterpretions or bugs.

Using the current development version of Docker, I found that **container filtering** only works if I use the full container ID, e.g.
> docker events -f container=230d1bd84ab8d3243866d7631c648bf7ef4c7340cdb408c8ec4762e36d46f29f

Neither abbreviated ID (as [documented](https://docs.docker.com/reference/commandline/cli/#events)) nor container names work, i.e. no events are reported.
Is this the way it should work? Then the documentation has to be adjusted.

edit: ~~I found no way to get an **image filter** working. Could anybody please supply me with a working example? The [documented](https://docs.docker.com/reference/commandline/cli/#events) example using image tags does not work for me. I also tried abbreviated and full image IDs.~~

**Comment by albers** [comment]
I retested against tag `v1.5.0-rc4` and found that filtering by image _does_ work as documented, i.e. using tags. Sorry for any confusion I might have created.

So my initial request can be rephrased to:
* Is it intended that container filtering does not work for abbreviated container IDs and names?
* Is it intended that image filtering does not work for full and abbreviated image IDs?

**Comment by tiborvass** [comment]
Confirmed.

@albers I personally don't see why we would make an exception for events filtering. For me this is a bug.

@LK4D4 do you know anything about this?

**Comment by LK4D4** [comment]
@tiborvass nope, IIRC that was implemented by @vieux

**Comment by brahmaroutu** [comment]
PR #10646 is fixing the bug and should be merged first, "User should be able to use shorted form of container id in the filter"
PR #10663 is a enhancement to the filtering logic. "User should be able to filter event using container name"
PR #10675 "Allow user to filter events using image name without the tag, ex: busybox instead of busybox:latest"

**Comment by albers** [comment]
Thanks @brahmaroutu for taking care of this!

**Comment by brahmaroutu** [comment]
@albers Thanks. I am wondering if we should also allow image id to filter upon. I changed the code to address issue with filtering by image name without the tag. I cannot see anyone using image id though?

**Comment by albers** [comment]
For general consistency I would expect both filters to accept long and short ID as well as name/tag.
So I'd really appreciate if you could also address this addition.

**Comment by albers** [comment]
Due to the work of @brahmaroutu, the filters now behave very intuitively. Bash completion was updated in #10896. So this can be closed.
