### ISSUE TITLE
docker run --env cannot set ENV variables

### ISSUE THREAD

**Issue by kirs** [docker/docker#10647]
`Docker version 1.0.1, build 990021a`

`sudo docker run -e FOO=123 mycontainer echo $FOO` is giving the blank output.
What am I doing wrong?

**Comment by kirs** [comment]
Actually the same happens with the basic ubuntu image:

```
sudo docker run -e FOO=BAR ubuntu echo $FOO
```

**Comment by thaJeztah** [comment]
I think what you're seeing there is your local shell trying to expand the `$FOO` env var, not the command inside the container.

You can try it this way;

    docker run -e FOO=BAR --rm ubuntu /bin/bash -c "echo \$FOO"

This section in the docs may contain some useful information as well; https://docs.docker.com/reference/run/#env-environment-variables

**Comment by kirs** [comment]
Thanks!
