### ISSUE TITLE
Proposal: Set environment variable containing IP address for each container 

### ISSUE THREAD

**Issue by razic** [docker/docker#10644]
I have a lot of containers that accept flags to bind their HTTP servers on specific hosts/ips and ports.

I can bind my HTTP server on 127.0.0.1 but I can't use that when reporting my IP address to other containers (for various reasons, Mesos, etc...). Can we set an environment variable for the currently running container?

**Comment by razic** [comment]
I guess you could always do this: `sh -c "echo $(awk 'NR==1{print $1}' /etc/hosts)"`

**Comment by crosbymichael** [comment]
Yes, there are various ways to get the ip address for the container.  In the default networking model you will have a veth named `eth0` that you can get the ipaddress from.
