### ISSUE TITLE
Set an Volume (-v) from external HD

### ISSUE THREAD

**Issue by marioidival** [docker/docker#10640]
Darwin MacBook-Air-de-Mario.local 14.1.0 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64

Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): darwin/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8

Containers: 2
Images: 4
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Dirs: 8
Execution Driver: native-0.2
Kernel Version: 3.16.7-tinycore64
Operating System: Boot2Docker 1.4.1 (TCL 5.4); master : 86f7ec8 - Tue Dec 16 23:11:29 UTC 2014
CPUs: 4
Total Memory: 1.961 GiB
Name: boot2docker
ID: B4NO:F3WP:OGQ2:VOOZ:IW6I:NZQE:5EUS:LWJ2:W4UH:5KNG:YLED:RFCX
Debug mode (server): true
Debug mode (client): true
Fds: 10
Goroutines: 11
EventsListeners: 0
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: marioidival
Registry: [https://index.docker.io/v1/]

Hello Everyone, I have a large mongodb database, 30Gb, and I use from External HD.
I try sharing the mongodb path from HD to a container. The folder in container is created, but files from mongodb not appears.

docker run --it --rm -v /Volumes/NAMEHD/mongoexternal/mongodb:/data/db base_dev:version001

Also, I try create a symbolic link and do not work too.

**Comment by tiborvass** [comment]
@marioidival Assuming you're using boot2docker on OS X, by default only the /Users folder is automatically shared with boot2docker via VirtualBox. You can set up custom mounts as described in https://github.com/boot2docker/boot2docker#virtualbox-guest-additions.

**Comment by marioidival** [comment]
Thanks @tiborvass but I can not do this ... :(

 mount -t vboxsf -o uid=1000,gid=50 /mongoexternal/ /Volumes/MAGADEXTERNO/mongodb_external


![captura de tela 2015-02-07 as 17 10 28](https://cloud.githubusercontent.com/assets/1129263/6093763/402cb7d2-aeec-11e4-80ad-a41e5d027e10.png)

**Comment by tiborvass** [comment]
Hmm, I'm not sure. Ping @tianon @SvenDowideit 

However if you don't mind, I'm gonna close this issue since it's not an issue in docker itself.
