### ISSUE TITLE
Image push failed  FATA[0299] Error pushing to registry: Put ?digest=tarsum.v1%2Bsha256%3Ae3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855: unsupported protocol scheme "" 

### ISSUE THREAD

**Issue by zopyx** [docker/docker#10656]
Pushing 

https://github.com/zopyx/docker-basex

fails:

ajung@demo:~/src/docker-basex$ docker push zopyx/basex-80

511136ea3c5a: Image push failed 
FATA[0299] Error pushing to registry: Put ?digest=tarsum.v1%2Bsha256%3Ae3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855: unsupported protocol scheme "" 
ajung@demo:~/src/docker-basex$ 
ajung@demo:~/src/docker-basex$ 
ajung@demo:~/src/docker-basex$ 
ajung@demo:~/src/docker-basex$ 
ajung@demo:~/src/docker-basex$ 
ajung@demo:~/src/docker-basex$ 
ajung@demo:~/src/docker-basex$ docker push zopyx/basex-80
^Cajung@demo:~/src/docker-basex$ docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): 5bf46a5
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): 5bf46a5
ajung@demo:~/src/docker-basex$ docker -D info
Containers: 4
Images: 872
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 880
Execution Driver: native-0.2
Kernel Version: 3.13.0-44-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 2
Total Memory: 5.829 GiB
Name: demo.xml-director.info
ID: LTA5:NIZF:ZRHM:V6GM:SPMV:GKDE:WKUN:NZC7:MYRF:IMHU:BZC3:G6NH
Debug mode (server): false
Debug mode (client): true
Fds: 37
Goroutines: 35
EventsListeners: 0
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker
Username: zopyx
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support

**Comment by estesp** [comment]
Can you try with the latest RC for 1.5.0? (see https://groups.google.com/d/msg/docker-dev/uXsaWFfYUgE/HKlSF_ucMBYJ )  The commit ID above looks like an earlier candidate that does not have the fix for push changes that came about during 1.5.0 release testing.

**Comment by zopyx** [comment]
1.5.0RC4 solved the problem
