### ISSUE TITLE
What's the precise meaning of the "die" event?

### ISSUE THREAD

**Issue by mountkin** [docker/docker#10654]
At first glance I thought "die" means the container stopped unexpectedly. 
But when I stop a container manually I see the "die" event followed by a "stop" event. I think the "die" event here is unnecessary.
I want to implement a web interface and need to show the user all the history events of the container, but with the current docker events API it seems that it's hard to distinguish "normally stop" from "unexpectedly stop".

**Comment by unclejack** [comment]
`die` means the container has stopped. `stop` means that the container was sent the stop signal and that the API call for stop was made.

You should probably look for both events. If a container dies without being stopped explicitly, then it stopped for another reason than being asked to `stop`.

**Comment by mountkin** [comment]
Thanks for your reply @unclejack 
After digging the code I found the ```stop``` event is emitted after the container is really stopped, not just when the API call was made.  I think when the ```stop``` event is received, we can safely say that the container is dead. Thus the ```die``` event seems like duplicated.

**Comment by jfrazelle** [comment]
you are more than welcome to open a PR with your changes

**Comment by mgood** [comment]
@mountkin yeah I had the same confusion about the "die" event, though removing that event when it's stopped would impact existing clients that expect it.

How about if there was a new event that was emitted after "die" for containers that unexpectedly terminated?

**Comment by patelrit** [comment]
+1 Sending 'die' event when container stops is somewhat confusing. Maybe using 'stopped' would be more appropriate. Indicating whether the container stopped because it was stopped by the user or died/stopped unexpectedly is extremely helpful for systems that monitor/manage containers.

**Comment by mgood** [comment]
#dibs, working on this for docker.party

**Comment by londoncalling** [comment]
#dibs

**Comment by thaJeztah** [comment]
@londoncalling you may need to check if this is still needed; the documentation now contains a state diagram; http://docs.docker.com/reference/api/docker_remote_api/#docker-events that may be sufficient.

(also see https://github.com/docker/docker/pull/15669 for more discussion around the events)


let us know what you think; if you think this can be closed, let us know as well :+1:

**Comment by londoncalling** [comment]
@thaJeztah , thanks for the clarification on the chain for both of these issues. The diagram looks great, but I'd like to check out with @moxiegirl whether each of the states in the diagram (http://docs.docker.com/reference/api/docker_remote_api/#docker-events) is defined/explained further anywhere in the API docs, and whether this might be useful. What do you guys think?

**Comment by moxiegirl** [comment]
`docker event stats site:docs.docker.com` in your browser bar will do a search of just our docs.  The SEARCH is on its way with the next UX which should be complete by End of this Year.

With that search, I'm not able to find good documentation around the states.  We need to do that.  The first step is an issue for tracking.  I''ll stop by to talk later.

**Comment by londoncalling** [comment]
@moxiegirl cool! 

@thaJeztah, it sounds like we can close this issue, then we'll open a new one to cover needed documentation around event states.

**Comment by thaJeztah** [comment]
Thanks for working on this, @londoncalling I'll close this issue, please continue the discussion in https://github.com/docker/docker/issues/17624

**Comment by buchdag** [comment]
@thaJeztah do you know where the state diagram you mentioned in https://github.com/moby/moby/issues/10654#issuecomment-152997786 can be found ?

I could not find it in the current documentation.
