### ISSUE TITLE
yum install missing files in container.

### ISSUE THREAD

**Issue by bear0330** [docker/docker#10650]
In container:
```
yum install -y epel-release
yum install -y http://iredmail.org/yum/rpms/7/cluebringer-2.0.14-4.el7.centos.noarch.rpm
```
After install, some files are missing: 
/usr/share/doc/cluebringer-2.0.14/
only have contrib directory, but it should be 
AUTHORS  ChangeLog  contrib  database  INSTALL  LICENSE  TODO  WISHLIST

This works under host.

**Comment by unclejack** [comment]
@bear0330 Please provide the full output of `docker info`, `docker version` and `uname -a`. We also need to know what image you were using (centos 6, centos 7, etc).

**Comment by bear0330** [comment]
docker info:
```
Containers: 1
Images: 42
Storage Driver: devicemapper
 Pool Name: docker-8:1-525579-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 1.653 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 2.871 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.84-RHEL7 (2014-03-26)
Execution Driver: native-0.2
Kernel Version: 3.10.0-123.20.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
```

docker version
```
Client version: 1.3.2
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 39fa2fa/1.3.2
OS/Arch (client): linux/amd64
Server version: 1.3.2
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): 39fa2fa/1.3.2
```

uname -a
```
Linux gicc-bearhu-1 3.10.0-123.20.1.el7.x86_64 #1 SMP Thu Jan 29 18:05:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

docker image:
centos                   centos7             8efe422e6104        4 weeks ago         224 MB

Procedure to reproduce that issue:
```
docker run -it --rm centos:centos7 /bin/bash
[root@dbf198a59f09 /]# yum install -y epel-release
[root@dbf198a59f09 /]# yum install -y http://iredmail.org/yum/rpms/7/cluebringer-2.0.14-4.el7.centos.noarch.rpm

[root@dbf198a59f09 /]# ls -l /usr/share/doc/cluebringer-2.0.14/
total 4
drwxr-xr-x. 3 root root 4096 Feb  9 10:50 contrib
```
The same procedure under my host (CentOS 7):
```
ls -l /usr/share/doc/cluebringer-2.0.14/
total 48
-rw-r--r--. 1 root root    63 Jul 27  2014 AUTHORS
-rw-r--r--. 1 root root  1956 Jul 27  2014 ChangeLog
drwxr-xr-x. 3 root root  4096 Feb  9 01:29 contrib
drwxr-xr-x. 2 root root  4096 Feb  9 01:29 database
-rw-r--r--. 1 root root  2343 Jul 27  2014 INSTALL
-rw-r--r--. 1 root root 17987 Jul 27  2014 LICENSE
-rw-r--r--. 1 root root  1767 Jul 27  2014 TODO
-rw-r--r--. 1 root root   140 Jul 27  2014 WISHLIST
```

Thanks.

**Comment by unclejack** [comment]
Ok, I can confirm this is indeed a problem. I wonder if it has something to do with xattrs.

ping @jperrin @vbatts

**Comment by jperrin** [comment]
This is a configuration issue. In order to help keep the size of the image down, there's a `tsflags=nodocs` configuration option that we drop into `/etc/yum.conf` on image build. This tells yum to not install docs files. If you remove that line and reinstall the package with yum, you should see the files as expected.

**Comment by unclejack** [comment]
@jperrin Perhaps this should be written down in the README of the CentOS images so that users know what to expect? Sometimes, figuring out what's a bug and what's configuration can be quite difficult.

**Comment by jperrin** [comment]
Sure. Can certainly add to the documentation. I'll try to have a PR for this today.

**Comment by ankushagarwal** [comment]
@unclejack : I see it documented here : https://github.com/docker-library/docs/tree/master/centos#package-documentation , can this issue be closed?

**Comment by thaJeztah** [comment]
Thanks, @ankushagarwal, I think this can be closed, yes (and, technically, it's not a "Docker" issue as well)
