### ISSUE TITLE
Proposal: Ceph volume support

### ISSUE THREAD

**Issue by dachary** [docker/docker#10661]
A Ceph (http://ceph.com/) volume could be implemented with something like ( see https://github.com/docker/docker/pull/8484 )

    docker volumes create --driver ceph --driver-opt foo=bar --name myimage rbd:image:/path/in/docker ...

which would map **rbd:image** via the Ceph kernel rbd driver ( http://ceph.com/docs/master/rbd/rbd-ko/ ) with

     rbd map image

mount it somewhere

    mount /dev/rbd0 /var/lib/docker/ceph/image

and then be used with

    docker ... --volume-from myimage/path/in/docker ...

It requires support for https://github.com/docker/docker/issues/7249 ( for instance https://github.com/cpuguy83/docker/commit/448a1b0c31943084edb6a867a44ccdec49fcf1f0 )

The Ceph volume driver could use https://github.com/noahdesu/go-ceph or the rbd command line.

This is different from Ceph volume storage ( https://github.com/docker/docker/issues/7249 ).

**Comment by cpuguy83** [comment]
Closing as this is now available via plugins. See a ceph plugin: https://github.com/contiv/volplugin
`docker volume create` would be handled by #14242 

Thanks!

**Comment by tobegit3hub** [comment]
It seems that https://github.com/AcalephStorage/docker-volume-ceph-rbd> and https://github.com/yp-engineering/rbd-docker-plugin are another options as rbd plugins :smiley:
