### ISSUE TITLE
Docker changes tag on get/set/delete when using an image named library/*

### ISSUE THREAD

**Issue by dmcgowan** [docker/docker#10666]
Issue:
Normalization was added to tags on set/get/delete which strips a prefix of "library/" before setting or getting the tag.  With this change "docker rmi" is unable to remove a tag for an existing image named "library/*" and "docker tag" will strip "library/" before saving.

Expectation:
While the library namespace is reserved for official images on the hub, the docker cli should not prevent creation of images with this prefix.

See 3 diffs starting at 
https://github.com/docker/docker/commit/568f86eb186731b907b659e4ec64bda21c2fe31d#diff-9459cc42eeb37e6b37bcb473ce0b3d21R178

ping @dkjer

**Comment by tianon** [comment]
I think this will prevent us from pushing the official images, since we have to create and push them as `library/...`.

`FATA[0000] You cannot push a "root" repository. Please rename your repository in <user>/<repo> (ex: stackbrew/docker-dev) `

**Comment by dmcgowan** [comment]
@tianon with the PR to fix this should also fix the logic for that fatal you are seeing. Previously the logic just required having two name components to push, now it is actually checking if IsOfficial which I don't think was not the intent of that check.

https://github.com/docker/docker/commit/568f86eb186731b907b659e4ec64bda21c2fe31d#diff-e728bf75e7a6536ac0e70b85f7aaf65aR1188

**Comment by tianon** [comment]
Ah, interesting.  Ok, so this'll just require updates to the way our push
script works, which is fine if that's the way this goes.

**Comment by dmcgowan** [comment]
@tianon how would your push scripts need to change? I think we should fix this regression in 1.5.1 assuming that everyone agrees it is a regression.

**Comment by tianon** [comment]
Ok, let's run through an example.  Imagine I'm going to push `debian:latest` -- here's how that flow works right now (reader's digest version):

1. `git clone ... && docker build -t debian:latest ...`
2. `docker tag debian:latest library/debian:latest`
3. `docker tag debian:latest stackbrew/debian:latest`

Then:

1. `docker push library/debian:latest`
2. `docker push stackbrew/debian:latest`

This can be changed to just do `docker push debian:latest` directly if that's the way this goes.

**Comment by dmcgowan** [comment]
Ok, I see what you are saying.  Even to support `docker push debian:latest` will require a code change, but I think the current flow you outlined is best.

**Comment by jfrazelle** [comment]
@dmcgowan can you triage :D

**Comment by cpuguy83** [comment]
This seems like it has been fixed.
Can we close?

**Comment by thaJeztah** [comment]
I'll close this, but ping if I closed by mistake
