### ISSUE TITLE
Proposal: Refactoring to compile Docker Daemon on Windows

### ISSUE THREAD

**Issue by jhowardmsft** [docker/docker#10662]
## Background

Following the Docker and Microsoft announcement in October 2014 (http://news.microsoft.com/2014/10/15/dockerpr/), and the recent PR https://github.com/docker/docker/pull/9113 for the port of the Docker client portion to Windows, this proposal is for the initial work necessary for the Docker daemon to compile on Windows.

## Problem Statement

The existing daemon code base does not compile cross-platform for Windows. This is largely due to a number of ‘Linuxisms’ and system calls which do not have matching Windows counterparts. 
Linux specific calls will be factored out by various techniques such as filename_Linux.go and filename_Windows.go; through use of runtime.GOOS conditions; and/or through build tags. 

A simple example of the type of factoring would be removing support of the Unix HTTP namespace on Windows (but keeping it on Linux). Windows would support the TCP HTTP namespace only.

In addition, dummy no-op drivers will be added for future support of Windows containers.

## Expectations

At the end of the series of PRs relating to this proposal, it is expected that the Docker Daemon will initialise and listen for requests on a TCP port on a Windows platform. It will be largely non-functional except for responding to “version” and “info”. 

The functionality of the Docker daemon on Linux platforms will be unchanged.

**Comment by ahmetalpbalkan** [comment]
Yaay! :clap: :tada: :bowtie:

**Comment by tiborvass** [comment]
@jhowardmsft I'm all for it! Let's aim 1.6 for the refactor.

**Comment by jfrazelle** [comment]
+1 All for this.

**Comment by ahmetalpbalkan** [comment]
Can we label this with `windows`?

**Comment by icecrime** [comment]
Yes! :+1:

Let us know how we can help. A function-level segregation using conditional compilation is indeed necessary, but maybe we'll find responsibilities along the way that justify adding whole new interfaces to cleanly separate implementations.

I'll share the link here for reference, but some ongoing work by @crosbymichael on libcontainer can help on the lower(est?) level aspect: docker/libcontainer#367.

**Comment by squillace** [comment]
happy.

**Comment by unclejack** [comment]
This proposal has been approved because many PRs for this work have been merged and there are still some open PRs which are doing this work. I'm going to close this because: 1) this has been approved, 2) it's work in progress, 3) there's nothing more to left approve and debate.

**Comment by Maxvien** [comment]
happy
