### ISSUE TITLE
How to add a new proposal as a pull request?

### ISSUE THREAD

**Issue by yeasy** [docker/docker#10677]
In the guideline at https://github.com/docker/docker/blob/master/CONTRIBUTING.md#design-and-cleanup-proposals, it says to add a proposal as a pull request, not an issue.
    However, when I try to create a pull request, seems it needs to compare two branches and pull one into the other, rather than let me add some proposal text.
    Anyone could give a more detailed guideline?
    Thanks a lot!

**Comment by SvenDowideit** [comment]
the intention is that you make a git branch of docker, then edit the existing documentation to show what you're thinking would be good to have, and then create the pull request using those proposed changes.

This way, reviewers can think about the user facing impact by reading that documentation change.

**Comment by yeasy** [comment]
Thanks SvenDowideit!
I try to find the documentation in the docker project, however, only find the docs/sources directories, and there's no kind of proposal docs.
Could you help indicate where I should put my proposal doc into?
Thanks a lot!
