### ISSUE TITLE
Docker headings using in consistent case

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#10673]
Our style guide states our headings should use sentence case but the implementation is inconsistent.  We should correct this. Also, menu's should match the case in the headings. Examples:

* https://docs.docker.com/
* https://docs.docker.com/userguide/dockerizing/
* https://docs.docker.com/installation/oracle/

I plan to do this one myself within the month sometime.

**Comment by RickWieman** [comment]
If you like, I can help you with this?

**Comment by moxiegirl** [comment]
@RickWieman Absolutely, feel free. Thank you. :-D

**Comment by RickWieman** [comment]
In that case: #dibs :sunglasses:
