### ISSUE TITLE
Docker 1.4.1 panics when starting container in docker/volumes/volume.go:78

### ISSUE THREAD

**Issue by discordianfish** [docker/docker#10685]
Hi,

just rebooted a Docker 1.4.1 host. On start it tried to start old containers which caused it to panic:

```
ESC[34mDEBUESC[0m[0004] Starting container 648be33493a1c2fcfa1b305bb69d5b7c8ae4fa4a6338e5b6634d26b9494a40e8 
ESC[34mINFOESC[0m[0004] +job allocate_interface(648be33493a1c2fcfa1b305bb69d5b7c8ae4fa4a6338e5b6634d26b9494a40e8) 
ESC[34mINFOESC[0m[0004] -job allocate_interface(648be33493a1c2fcfa1b305bb69d5b7c8ae4fa4a6338e5b6634d26b9494a40e8) = OK (0) 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x6c8024]

goroutine 24 [running]:
runtime.panic(0xbe5c40, 0x127da13)
        /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/docker/docker/volumes.(*Volume).RemoveContainer(0x0, 0xc20871a780, 0x40)
        /go/src/github.com/docker/docker/volumes/volume.go:78 +0x94
github.com/docker/docker/daemon.(*Mount).initialize(0xc208bfeea0, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/volumes.go:93 +0x1b3
github.com/docker/docker/daemon.(*Container).createVolumes(0xc2085ea340, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/volumes.go:69 +0xd6
github.com/docker/docker/daemon.(*Container).prepareVolumes(0xc2085ea340, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/volumes.go:48 +0x5e
github.com/docker/docker/daemon.(*Container).Start(0xc2085ea340, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/container.go:343 +0x28c
github.com/docker/docker/daemon.(*Daemon).restore(0xc2080d20b0, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/daemon.go:386 +0xf3a
github.com/docker/docker/daemon.NewDaemonFromDirectory(0x12a0700, 0xc2080d5340, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/daemon.go:924 +0x1ffa
github.com/docker/docker/daemon.NewDaemon(0x12a0700, 0xc2080d5340, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/daemon/daemon.go:719 +0x43
main.func·001()
        /go/src/github.com/docker/docker/docker/daemon.go:53 +0x46
created by main.mainDaemon
        /go/src/github.com/docker/docker/docker/daemon.go:76 +0x2e4

goroutine 16 [chan receive]:
github.com/docker/docker/api/server.ServeApi(0xc20804cc00, 0x7f30ed6417d8)
        /go/src/github.com/docker/docker/api/server/server.go:1573 +0x473
github.com/docker/docker/engine.(*Job).Run(0xc20804cc00, 0x0, 0x0)
        /go/src/github.com/docker/docker/engine/job.go:83 +0x837
main.mainDaemon()
        /go/src/github.com/docker/docker/docker/daemon.go:91 +0x568
main.main()
        /go/src/github.com/docker/docker/docker/docker.go:71 +0x3ff

...
```

This might or might not be related to this "creative" bind-mount:
```
   "Volumes" : {
      "/var/run/docker.sock" : "/run/docker.sock",
      "/host/proc/mounts" : "/proc/10453/mounts",
      "/host/sys/fs/cgroup" : "/sys/fs/cgroup"
   },
```

Which doesn't look right but shouldn't cause Docker to crash either.

**Comment by cpuguy83** [comment]
This, **I believe**, to be fixed in 1.5.0

But in looking at daemon/volumes there is an at line 93 (in 1.4.1) that `v` is not nil since (since it shouldn't be), but potentially could be if the container was created with pre 1.3 daemon.

Even though this is fixed (via other parts of the codebase), I'll add a nil check here as well.

**Comment by discordianfish** [comment]
@cpuguy83 How could the version in which a container was created affect the output of the stacktrace?
Maybe it's not really 1.4.1 but some rc which was us guaranteed to be the same as the release version. Anyways, here is the 'info' output to be sure:

```
.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
```

**Comment by cpuguy83** [comment]
@discordianfish Not the output of the stack trace, but the fact that in 1.3 we started storing/using state information about volumes and there were a couple of places where I messed up in migrating old (pre 1.3 daemon) volumes to the new format.

**Comment by discordianfish** [comment]
> The issue raised above is already resolved via other parts of the
> codebase, but adding this nil check just to make sure it's really not
> nil.

That sounds really messy. We should know when it can be nil and when not, and not check on random places.

**Comment by nkvoll** [comment]
Any progress on this? It seems pretty easy to get in this situation by specifying

    -v /proc/mounts:/host/proc/mounts:ro

as suggested by monitoring tools such as https://github.com/DataDog/docker-dd-agent. Running such a container in background will prevent docker from starting again until /var/lib/docker/containers/.../config.json has been edited by hand to remove the volume.

**Comment by nkvoll** [comment]
I'm currently considering what the effects will be to use ``-v /proc/1/mounts:...`` instead, as there will always be a pid 1, and that would get rid of the "dependency" the ``/proc/self``-symlink.
