### ISSUE TITLE
Can't remove containers (Docker hanging up)

### ISSUE THREAD

**Issue by MitchK** [docker/docker#10684]
Hi, we are experiencing this issue on different machines randomly but could not find any reason.

```
$ sudo docker stop <container id or name>
```
Does nothing, it just hangs itself up. (ctrl +c mandatory)

```
$ sudo docker rm -f <container id or name>
```
has the same issue.

```
$ sudo docker info
Containers: 1
Images: 171
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 173
Execution Driver: native-0.2
Kernel Version: 3.8.0-29-generic
Operating System: Ubuntu precise (12.04.5 LTS)
CPUs: 2
Total Memory: 3.855 GiB
Name: mo-d845afaf1
ID: THKM:JVKV:GBLP:MT37:H6QC:IVLI:ZFXZ:CU3Y:5MPE:ZYFY:TPNI:4Y7L
WARNING: No swap limit support
```

Relevant docker daemon log output:
```
INFO[4820] DELETE /v1.16/containers/xmake-connect-staging?force=1 
INFO[4820] +job rm(xmake-connect-staging)               
INFO[4830] Container 7c7dcd5c56da failed to exit within 10 seconds of kill - trying direct SIGKILL 
```

```
$ sudo docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                      NAMES
7c7dcd5c56da        fe3b05f3be86        "npm start"         3 hours ago         Up 6 minutes        127.0.0.1:3000->3000/tcp   xmake-connect-staging  
```

The container logs don't show any errors of my application. The container did start fine but is not accepting connections.

Rebooting the docker daemon or rebooting the whole machine only makes the container restart, but the problem persist. I can't get this thing killed.

Any ideas?

**Comment by MitchK** [comment]
The only thing that helped was
```
$ sudo apt-get purge lxc-docker
$ sudo apt-get autoremove --purge 
$ sudo apt-get install lxc-docker
````

Everything went back to normal. I'll keep you posted.

**Comment by jfrazelle** [comment]
hmmm what version of docker is this on, can you add the flag `-D` for debug to the daemon to see if anything weird happens

**Comment by LK4D4** [comment]
@MitchK this is possibly "not removed cgroups" bug, which was fixed in 1.5

**Comment by MitchK** [comment]
Hi, I'm on Docker 1.4.1.

I'll upgrade and see if the problem persists.

**Comment by jfrazelle** [comment]
@MitchK are you still seeing this problem

**Comment by jfrazelle** [comment]
closing as stale please ping me with exact steps to reproduce on the latest version and I will reopen

**Comment by carn1x** [comment]
Had this on Boot2docker / Docker 1.4.1. Working after upgrade to 1.6.0.

**Comment by dodekeract** [comment]
Same bug on `Docker version 17.12.1-ce, build 7390fc6`. The only noteworthy thing about my setup is that my root volume is a RAID 1 BTRFS across 2x 240GB SSDs. Everything else is as normal as it gets (Ubuntu, nearly nothing installed outside of docker).

**Comment by Anzim** [comment]
The same bug on 18.06.1-ce
C:\Users\azym\Documents\mp3>docker rm --force 0f1
hangs... Ctrl-C

C:\Users\azym\Documents\mp3>docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:34 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     false
