### ISSUE TITLE
debootstrap fails with Extra junk after value

### ISSUE THREAD

**Issue by jedahan** [docker/docker#10691]
When trying to run

    # sudo ../mkimage.sh -t jedahan/palmos debootstrap --arch=i386 sarge http://archive.debian.org/debian/

The custom [debootstrap /etc/apt/apt.conf.d/docker-clean](https://github.com/docker/docker/blob/master/contrib/mkimage/debootstrap#L72-L95) is giving me a set of language warnings, and one nasty error which I do not know how to fix:

    perl: warning: setting locale failed
    perl: warning: Falling back to the standard locale("C")

    ...snip...

    E: Syntax error in /etc/apt/apt.conf.d/docker-clean:12: Extra junk after value

**Comment by tianon** [comment]
Hmm, `sarge` is pretty old at this point, so it probably doesn't support some of the settings we're applying there. :disappointed:

I wonder if there's a way we could apply some intelligence to detect whether these settings even exist for the current version of APT before we apply them.

**Comment by jedahan** [comment]
using the regular debootstrap worked, more info https://registry.hub.docker.com/u/jedahan/palmos/

**Comment by jfrazelle** [comment]
looks to be resolved let me know if otherwise

**Comment by dabrain34** [comment]
I just open an issue with hardy https://github.com/moby/moby/issues/37020
