### ISSUE TITLE
Builds are so slow if I have more than 1 build running

### ISSUE THREAD

**Issue by prafulrana** [docker/docker#10692]
Guys - builds are too slow. Docker is serving no purpose to my team if I need to spin up a new instance per build, are you guys taking a look at this?

**Comment by jfrazelle** [comment]
can you give us the output of `docker version` and `docker info` a lot is dependent on your set up and we can't really debug by just knowing its "slow" ;)

**Comment by thaJeztah** [comment]
Possibly dup of https://github.com/docker/docker/issues/9656, which also has some statistics

**Comment by crosbymichael** [comment]
I'm going to close this in favor of #9656 as it contains more details.
