### ISSUE TITLE
ReadOnlyRootfs only recognized when passed in containers/create

### ISSUE THREAD

**Issue by shin-** [docker/docker#10695]
The `ReadOnlyRootfs` parameter, introduced in API 1.17, seems to only be taken into account when passed to the `containers/create` endpoint. The documentation, as well as the behavior of all other HostConfig parameters suggests that it should also be recognized when passed to the `containers/<id>/start` endpoint, but it doesn't look to be the case.

Let me know if you need more details about this particular issue. Happy to help in any way I can.

**Comment by LK4D4** [comment]
I dunno, in documentation there is no payload at all in `start` :) And I personally hate that we can pass HostConfig in `start`.

**Comment by shin-** [comment]
Be that as it may, [the docs suggest](http://docs.docker.com/reference/api/docker_remote_api/#whats-new) that it is possible. 

> `POST /containers/create` `POST /containers/(id)/start`
> New! (`ReadonlyRootfs`) can be passed in the host config to mount the container's root filesystem as read only.

If you guys want to disallow it as a first step to deprecating passing host config in start, so be it, but we need to adjust the docs accordingly and warn users about the impending deprecation.

**Comment by unclejack** [comment]
There's nothing more to do for this as the deprecation notice was added through https://github.com/docker/docker/pull/17799.
