### ISSUE TITLE
doc uses outdated commands

### ISSUE THREAD

**Issue by thomasschaeferm** [docker/docker#10701]
My issue is about that documentation:

http://docs.docker.com/v1.5/articles/networking/#ipv6

route -A inet6 add 2001:db8:0:2::/64 dev docker0

should be replaced by 
ip -6 route add 2001:db8:0:2::/64 dev docker0

ifconfig should be replaced by ip addr ; ip link

The first part correctly uses the doc-prefix 2001:db8::/32

But later 2002:: is used, this prefix is reserved for  6to4 and could confuse the reader.

I think it is also better to use 

sysctl net.ipv6.conf.eth0.accept_ra=2

instead of 

echo 2 > /proc/sys/net/ipv6/conf/eth0/accept_ra

to ipv6 itself, I tested only the first scenario

**Comment by thaJeztah** [comment]
@thomasschaeferm I see there's a pull-request opened to fix the issues you mentioned, perhaps you could have a look at those changes as well, to confirm they address the issues you mentioned here; you can find the PR here; https://github.com/docker/docker/issues/10751

**Comment by thomasschaeferm** [comment]
The first part is solved. 
But the prefixes...

I know IPv6-Adresses are long and 2001:db8::/32 may be a long string in some (svg)-images. 
But in my point of view it is a must be. Documentation should be recognised as documentation. And people who accidentally take over the examples without thinking should have a limited damage.


2001::/32 is teredo
2002::/32 is 6to4
2003::/19 is Deutsche Telekom

Please do not increment to 2004, this network is not assigned yet.

Also please don't use fc00:/7. This could people lead to have bad minds.

**Comment by thaJeztah** [comment]
Thanks for looking, @thomasschaeferm, because I'm no IPv6 myself, I'm going to politely

/ping @MalteJ and @estesp

**Comment by MalteJ** [comment]
@thomasschaeferm yes, you are right with all the points you have mentioned. 
Indeed I have used 2001, 2002, 2003 for space reasons. Yes, I am not happy with this, too. Probably this should be corrected.

**Comment by thaJeztah** [comment]
@MalteJ @estesp I think this issue can be closed now that https://github.com/docker/docker/issues/10751 is merged (GitHub didn't close it automatically for some reason)

**Comment by estesp** [comment]
Thanks, absolutely.  @thomasschaeferm let me know if you have any additional feedback on IPv6 documentation, but I believe all current comments are handled.
