### ISSUE TITLE
add flag to indicate blocking/non-blocking stats collection

### ISSUE THREAD

**Issue by mustafaakin** [docker/docker#10707]
While docker stats is extremely useful, when a container exits the stats continue to wait for input, the connection is not closed. If you try to connect to container stats, Daemon accepts the connection, however does not respond any messages, I believe the default behaviour should be:

1. If the stats was run before container started, and container stops & streaming stops, the stats Remote API, the connection should be closed.
2. If the stats was run after container ended, the connection should be closed with proper HTTP header.

Example of connecting to stats remote API after container has exited
``` 
$ curl -v http://localhost:4500/containers/00fa5e2f1767d611a8edb4c2b535b7f69e678dba72d999d03c5282dfb57b5b2b/stats
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 4500 (#0)
> GET /containers/00fa5e2f1767d611a8edb4c2b535b7f69e678dba72d999d03c5282dfb57b5b2b/stats HTTP/1.1
> User-Agent: curl/7.37.1
> Host: localhost:4500
> Accept: */*
> 
... nothing happens
```

**Comment by crosbymichael** [comment]
The default behavior is the way that it is so that things like when a container restarts, in your example, you will miss stats.  How would you solve getting stats on restart in your default situation?

**Comment by mustafaakin** [comment]
I understand the behavior now. So, now maybe we can add some flag to indicate initatie a blocking or non-blocking stats collection?

**Comment by cpuguy83** [comment]
@mustafaakin Is this satisfied by the new `--no-stream` option on the CLI? (also stream=false on the API)

**Comment by mustafaakin** [comment]
Yes, it reads one time stat and closes the connection.
