### ISSUE TITLE
How to migrate the whole docker (include images and containers) to another host

### ISSUE THREAD

**Issue by biboxie** [docker/docker#10702]
i wanna copy my images and containers to another host/machine,keeping all data like imageid and containerid

how to do it?

thanks

**Comment by jfrazelle** [comment]
I think this would be a great opportunity for an article added to the docs.

**Comment by jfrazelle** [comment]
But for a direct answer to your question I would use volumes for the staeful data you need then rsync it that over to the new host and start but honestly if you want more help with this then i would checkout #docker on irc or forums.docker.com, the github issues is for issues iwth docker only
