### ISSUE TITLE
Error response from daemon: Cannot destroy container pp.server: Driver aufs failed to remove root filesystem

### ISSUE THREAD

**Issue by zopyx** [docker/docker#10700]
I am receiving the following error in one third of nightly restarts of a container:

Error response from daemon: Cannot destroy container pp.server: Driver aufs failed to remove root filesystem
+a255eb811579f8c4e36889817f616ae3319d9f158ac729923ff22c7dae8ff95f: rename
+/var/lib/docker/aufs/mnt/a255eb811579f8c4e36889817f616ae3319d9f158ac729923ff22c7dae8ff95f
+/var/lib/docker/aufs/mnt/a255eb811579f8c4e36889817f616ae3319d9f158ac729923ff22c7dae8ff95f-removing: device or resource busy
time="2015-02-10T00:00:01+01:00" level="fatal" msg="Error: failed to remove one or more containers"
4ff89df9a893993c11843b6c5b2ba6d4c052a3c7ca0e46b2f982053c44b0b259+

dgho@neu:~/existdb$ docker info
Containers: 4
Images: 467
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 475
Execution Driver: native-0.2
Kernel Version: 3.13.0-32-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 12
Total Memory: 58.98 GiB
Name: neu
ID: NHZD:VRE3:X2ZW:QUFY:ZW65:5TRQ:LMH6:LJJB:C7WB:IBLF:JTGU:IN34
Username: zopyx
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support
dgho@neu:~/existdb$ docker -D version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

**Comment by cpuguy83** [comment]
Closing as dup of #9665

**Comment by zopyx** [comment]
And the solution? Are you saying that this error is a feature and that
there is no canonical way for solving this problem?

2015-02-11 14:40 GMT+01:00 Brian Goff <notifications@github.com>:

**Comment by cpuguy83** [comment]
It means there is already an open issue with this exact problem and we should move all discussion to that open issue.

**Comment by zopyx** [comment]
Sorry, was misreading that the other issue is still open.
