### ISSUE TITLE
Network TCP binding (-H) to inner network

### ISSUE THREAD

**Issue by andrefernandes** [docker/docker#10703]
Got a funny issue here:

OPTIONS="--selinux-enabled --bip=172.15.0.1/22 -H tcp://172.15.0.1:2375 -H unix:///var/run/docker.sock"

I am using --bip to change the default network (really have to in my case) and I am also trying to make docker listen on a TCP port - but only in the internal network. **I am accepting the risk of exposing the TCP to running containers** - in fact I want this.

The funny issue is that the "docker0" adapter (and thus the internal network's host IP) only gets created (post-boot) after docker daemon runs for the first time. I need to remove the "-H tcp://172.15.0.1:2375", start the daemon, stop the daemon, put the "-H ....." back and start the daemon again.

Maybe the binding should wait until the adapter docker0 is created?

**Comment by cpuguy83** [comment]
hmm... binding and bridge creation happen in two different goroutines.
Technically we could signal this... however we want the API to be available as quickly as possible, and waiting for device creation would slow this down.
It would be better to create your own bridge first to bind to. Or if you really really want to use `--bip` do as you are doing... start the daemon 2x.

I don't think it makes sense to slow down the API firing up for this.
Closing but feel free to ping here if you have any questions/concerns on this.
