### ISSUE TITLE
new /stats API endpoint is not fully defined

### ISSUE THREAD

**Issue by joshwilsdon** [docker/docker#10711]
The new /stats endpoint seems like a great idea. Unfortunately the way it is currently defined, there is no description of what the fields are or what values they can have. This seems like it will cause problems moving forward especially for porting docker to other platforms.

As far as I can tell, the new fields are defined based on their implementation which appears to be the cgroups statistics. This makes some sense on Linux with a specific version of the cgroups stats but if those stats ever changed or if you were porting docker to another platform this immediately becomes problematic.

In the same way that the /top data is currently different on other hosts and platforms (as described in #9232) this endpoint as it is, seems like it's going to cause a lot of problems for portability.

Is it possible for the next version of the API to at least define the fields? Ideally they'd have been defined as something implementation independent to start with but if that ship has sailed, at least defining the fields using the current cgroups names and listing what the possible keys and values are would be a huge step forward for portability.

**Comment by brahmaroutu** [comment]
I am also interested in this endpoint but looks like the request constantly pulls info(every 2 seconds?), why not implement a pull model where I can get a single set for each call then I can control my pull periods? 
For each of cpu and memory, I am only interested in current usage, max usage and the limits.
May be we should have a second endpoint ex:/stats2 that provides a simpler json like and allow pull type 
{timestamp:"2015-02-11T19:54:52.118834164Z",
   "cpu": {"usage": 106425827, "max_usage": 106425827,"percpu_usage":[70915764,35510063],"usage_in_kernelmode":50000000,"usage_in_usermode":40000000}
   "memory":{"usage":577536,"max_usage":3801088}
   "network":{"rx_bytes":648, "rx_packets":8, "rx_errors":0, "rx_dropped":0, "tx_bytes":648, "tx_packets":8, "tx_errors":0, "tx_dropped":0}
    "IO": [{"reads":  ,"writes": ,  }]
}

**Comment by crosbymichael** [comment]
Have you taken a look at the structs here: https://github.com/docker/docker/blob/master/api/stats/stats.go ?

**Comment by joshwilsdon** [comment]
@crosbymichael I had not. Are those considered stable then? Can those be added to the API documentation and the example fixed? The current API documentation for 1.17 is wrong if that .go file is what's supposed to be the API, as many of the fields listed in the example here:

https://docs.docker.com/reference/api/docker_remote_api_v1.17/#get-container-stats-based-on-resource-usage

are not also listed in that stats.go file and the vice versa. If the API is really supposed to be just what's in stats.go, this looks *much* better to me than what's in the documentation.

**Comment by crosbymichael** [comment]
@joshwilsdon yes, those are the stable API structs that are marshaled to JSON.

**Comment by joshwilsdon** [comment]
@crosbymichael ok, great. Thanks. Should I open a separate issue then for fixing the documentation or can this issue be repurposed for that?

**Comment by cpuguy83** [comment]
Closing since it seems like these are properly documented.
