### ISSUE TITLE
make targets don't run for Mac Users Out-of-the-box

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#10718]
I ran into a problem as did @jeffdm with the Makefile in a Mac OS X environment.  Running make binary or make cross did not actually output into the `bundles` directory.  The work around is to change the Makefile 

```
BINDDIR := $(if $(DOCKER_HOST),,bundles)
```
to

```
BINDDIR := bundles
```

Absent this, the Makefile seems to work but actually does nothing.  It might be dumping to the VM but even so painful when it can go locally (presumably) to the bundles subdir.  Any reason not to fix this?

**Comment by jfrazelle** [comment]
Ya so we had not changed this because https://github.com/docker/docker/pull/8779#issuecomment-62936109 ping @tianon I still am rather dubious to change it for that reason but I wonder if there is another way to tell the user is on a mac eeeee I dont know.

**Comment by moxiegirl** [comment]
So, I figured there would be good reason. Right now, I'm planning on fixing it in the docs because of the good reason. But better to speak up...ya never know.

Consider that Jeff also grinded on this for an hour  -- some percentage of Mac users will also do this.  So, if we don't fix the tooling, there will continue to be people with the problem because who reads docs? Only if you pay me to! hahhahahah

**Comment by tianon** [comment]
@jfrazelle I agree, I'm -1 on changing this back because remote hosts are also very much a thing even outside of boot2docker

I think updating the docs to explain that boot2docker users should use `make BINDDIR=bundles ...` would be more appropriate.

**Comment by moxiegirl** [comment]
I am happy to correct the current documentation.  Right now, the (official documentation)[ https://docs.docker.com/contributing/devenvironment/] says: 

-------
This will create the Docker binary in `./bundles/<version>-dev/binary/`. If you
do not see files in the `./bundles` directory in your host, your `BINDDIR`
setting is not set quite right. You want to run the following command: 
    
    $ make BINDDIR=. binary 

If you are on a non-Linux platform, e.g., OSX, you'll want to run `make cross`
or `make BINDDIR=. cross`.
-----

Which I doesn't work for me. I did the research with an actual developer who said his solution was to edit the Makefile and explicitly replace the line with:

```
BINDDIR := bundles
```
This puts what appears to be a working binary for me in bundles. I get this:

```
drwxr-xr-x  6 mary  staff       204 Feb 13 10:46 .
drwxr-xr-x  3 mary  staff       102 Feb 13 10:46 ..
lrwxr-xr-x  1 mary  staff        16 Feb 13 10:46 docker -> docker-1.5.0-dev
-rwxr-xr-x  1 mary  staff  15015145 Feb 13 10:46 docker-1.5.0-dev
-rw-r--r--  1 mary  staff        51 Feb 13 10:46 docker-1.5.0-dev.md5
-rw-r--r--  1 mary  staff        83 Feb 13 10:46 docker-1.5.0-dev.sha256
```
Unless there are some objections to this methodology, I plan on correcting the docs to have them edit the Makefile.

**Comment by tianon** [comment]
I definitely object to encouraging users to edit the Makefile when it
should already be accounting for exactly this use case, and would much
rather figure out why "make BINDDIR=bundles cross" doesn't do the exact
same thing as the change you're proposing we tell all our OSX users to make.

**Comment by moxiegirl** [comment]
@tianon Because editing the Makefile results in something appearing in the `bundles` directory. Whereas the solution you propose doesn't.   

```
docker run --rm -it --privileged -e BUILDFLAGS -e DOCKER_CLIENTONLY -e DOCKER_EXECDRIVER -e DOCKER_GRAPHDRIVER -e TESTDIRS -e TESTFLAGS -e TIMEOUT  "docker:master" hack/make.sh binary cross

---> Making bundle: binary (in bundles/1.5.0-dev/binary)
Created binary: /go/src/github.com/docker/docker/bundles/1.5.0-dev/binary/docker-1.5.0-dev

---> Making bundle: cross (in bundles/1.5.0-dev/cross)
Created symlinks: /go/src/github.com/docker/docker/bundles/1.5.0-dev/cross/linux/amd64/docker /go/src/github.com/docker/docker/bundles/1.5.0-dev/cross/linux/amd64/docker-1.5.0-dev /go/src/github.com/docker/docker/bundles/1.5.0-dev/cross/linux/amd64/docker-1.5.0-dev.md5 /go/src/github.com/docker/docker/bundles/1.5.0-dev/cross/linux/amd64/docker-1.5.0-dev.sha256
Created binary: /go/src/github.com/docker/docker/bundles/1.5.0-dev/cross/linux/386/docker-1.5.0-dev
Created binary: /go/src/github.com/docker/docker/bundles/1.5.0-dev/cross/linux/arm/docker-1.5.0-dev
Created binary: /go/src/github.com/docker/docker/bundles/1.5.0-dev/cross/darwin/amd64/docker-1.5.0-dev
Created binary: /go/src/github.com/docker/docker/bundles/1.5.0-dev/cross/darwin/386/docker-1.5.0-dev
Created binary: /go/src/github.com/docker/docker/bundles/1.5.0-dev/cross/freebsd/amd64/docker-1.5.0-dev
Created binary: /go/src/github.com/docker/docker/bundles/1.5.0-dev/cross/freebsd/386/docker-1.5.0-dev
Created binary: /go/src/github.com/docker/docker/bundles/1.5.0-dev/cross/freebsd/arm/docker-1.5.0-dev
Created binary: /go/src/github.com/docker/docker/bundles/1.5.0-dev/cross/windows/amd64/docker-1.5.0-dev.exe
Created binary: /go/src/github.com/docker/docker/bundles/1.5.0-dev/cross/windows/386/docker-1.5.0-dev.exe


mary at meepers in ~/repos/docker-mine on master
$ ls -al bundles
total 0
drwxr-xr-x   2 mary  staff    68 Feb 13 11:05 .
drwxr-xr-x  44 mary  staff  1496 Feb 13 11:04 ..
``

**Comment by tianon** [comment]
It's _supposed_ to; that's what I'm getting at -- so if it isn't working, let's debug that.

```console
$ make BINDDIR=bundles cross
 ...
$ find bundles
 ... a bunch of files should be listed here
```

**Comment by moxiegirl** [comment]
Cool. I'd love some help. Let me know how to I can make that happen. (I have had several folks give a hand and look at my environment so I'm not entirely like pulling this out of a hat.)

**Comment by moxiegirl** [comment]
OK, I worked through this with @tianon who solved the problem with his eyes. I was typing BINDIR and it is BIN**DD**IR which is embarrassing but hey I wasn't alone in this.  

@tianon gets big kudos for helping with this...thank you!

**Comment by tianon** [comment]
Indeed!  I'm prepping a patch right now to change this to `BIND_DIR` with a backwards-compatibility shim so we can get some maintainer opinions on it and hopefully put this particular typo to rest. :+1:
