### ISSUE TITLE
Can I have the Space total returned in Mb instead of GB

### ISSUE THREAD

**Issue by DesPenny** [docker/docker#10720]
Pool Name: docker-202:65-788438-pool
Pool Blocksize: 65.54 kB
Data file: /var/lib/docker/devicemapper/devicemapper/data
Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
Data Space Used: 2.14 GB
Data Space Total: 107.4 GB
Metadata Space Used: 4.796 MB
Metadata Space Total: 2.147 GB
Library Version: 1.02.89-RHEL6 (2014-09-01)

Hello Everyone,

I'm relatively new to docker so please bear with me. From the docker info above you can see that Metadata Space Used is in MB and the Metadata Space total is in GB. This is causing issues with a nagios monitoring script I'm using. I was wondering if its possible to have space standardised and have it returned in Mb before I start tinkering with the script.

Thanks in advance for any responses,

Des

**Comment by crosbymichael** [comment]
I think you should be able to curl the API endpoint and get the exact raw values if you are using monitoring tools.  I think this would be a more robust way to handle the information if you are able to do this.

**Comment by simonbeckett** [comment]
Looks like this is due to the use of humansize in the devicemapper driver...
````
 status := [][2]string{
        {"Pool Name", s.PoolName},
        {"Pool Blocksize", fmt.Sprintf("%s", units.HumanSize(float64(s.SectorSize)))},
        {"Backing Filesystem", backingFs},
        {"Data file", s.DataFile},
        {"Metadata file", s.MetadataFile},
        {"Data Space Used", fmt.Sprintf("%s", units.HumanSize(float64(s.Data.Used)))},
        {"Data Space Total", fmt.Sprintf("%s", units.HumanSize(float64(s.Data.Total)))},
        {"Data Space Available", fmt.Sprintf("%s", units.HumanSize(float64(s.Data.Available)))},
        {"Metadata Space Used", fmt.Sprintf("%s", units.HumanSize(float64(s.Metadata.Used)))},
        {"Metadata Space Total", fmt.Sprintf("%s", units.HumanSize(float64(s.Metadata.Total)))},
        {"Metadata Space Available", fmt.Sprintf("%s", units.HumanSize(float64(s.Metadata.Available)))},
        {"Udev Sync Supported", fmt.Sprintf("%v", s.UdevSyncSupported)},
````
I agree raw values, or at the very least a small common denominator is the way to go. If human friendly units are desired, then a switch can be used from the cli or client side conversion for any monitoring tasks.

**Comment by calavera** [comment]
As @crosbymichael pointed out, you should be able to get that data from the api. That's a more reliable output than the client, since the client perform transformations required to inform human about the daemon state.

I'm closing this issue. Thanks for reaching out.

**Comment by DesPenny** [comment]
@calavera @crosbymichael I just queried the api from the command line and as you can see it is returned in human readable form.

 echo -e "GET /info HTTP/1.0\r\n" | nc -U /var/run/docker.sock
HTTP/1.0 200 OK
Content-Type: application/json
Job-Name: info
Date: Mon, 04 May 2015 01:33:18 GMT
Content-Length: 1431

{"Containers":33,"Debug":0,"DockerRootDir":"/var/lib/docker","Driver":"devicemapper","DriverStatus":[["Pool Name","docker-202:65-788438-pool"],["Pool Blocksize","65.54 kB"],["Backing Filesystem","extfs"],["Data file","/dev/loop0"],["Metadata file","/dev/loop1"],["Data Space Used","18.09 GB"],["Data Space Total","107.4 GB"],["Metadata Space Used","40.1 MB"],["Metadata Space Total","2.147 GB"],["Udev Sync Supported","true"],["Data loop file","/var/lib/docker/devicemapper/devicemapper/data"],["Metadata loop file","/var/lib/docker/devicemapper/devicemapper/metadata"],["Library Version","1.02.89-RHEL6

**Comment by jsok** [comment]
Would it make sense to add a query param to `/info` to allow us to retrieve raw sizes? That way the API does the conversion, not the client.

e.g. `GET /info?raw_size=true` or `GET /info?human_size=true`, whichever is more natural.

**Comment by thaJeztah** [comment]
Ah, I see the problem here; basically, the "Status" is a free-form list of labels/values, that are driver-specific. For example, the [aufs driver](https://github.com/docker/docker/blob/fec6cd2eb988f77d7442fd8edd8cc864c87ae88b/daemon/graphdriver/aufs/aufs.go#L173-L181) returns completely different properties here.

I don't think we can really standardize that, because the "client" should not have knowledge about these driver-specific values (graph drivers can also be added as a plugin). Only thing I can think of, is to add an optional *third* string to each of the items in the DriverStatus list, which contains the "raw" value (as a string). The client wouldn't use that value, but other consumers of the API can possibly use it; with a **big** warning, that none of those properties are standardized / documented (it's really informational, and should normally be presented as-is), so it may break if (e.g.) someone decides to rename the label (the first string)
