### ISSUE TITLE
Can't update android sdk.

### ISSUE THREAD

**Issue by oldfeel** [docker/docker#10721]
root@61ec9dacde5f:~# android list sdk --all --no-https
Refresh Sources:
  Fetching http://dl-ssl.google.com/android/repository/addons_list-2.xml
  Fetched Add-ons List successfully
  Refresh Sources
  Fetching URL: http://dl-ssl.google.com/android/repository/repository-10.xml
Refresh Sources:
  Fetching URL: http://dl-ssl.google.com/android/repository/repository-10.xml
Packages available for installation or update: 0

**Comment by oldfeel** [comment]
Sorry, even in the real linux environment can not be updated. I think it's the android sdk Issue.

Close it, please.

**Comment by crosbymichael** [comment]
No problem, thanks for the update
