### ISSUE TITLE
Error "getting container by devicemapper" occurs when you try creating a container after restarting docker service.

### ISSUE THREAD

**Issue by sunyuan3** [docker/docker#10729]
Error "getting container" occurs when you try creating a container after restarting docker service.

environment: ubuntu14.04 64bit
commit 68b0ed54cb7ed9e4b66e8a9e0708577b32088de2

Steps to reproduce:
(1) service docker.io restart
(2) docker run -it ubuntu:latest /bin/bash

Notes: The problem isn't frequent. The probability is less than 10%.

log:
INFO[0001] Error getting container aa9f2ec9acebf555804a982caf01a034bf63a48280f781692a300c6a46388522 from driver devicemapper: open /dev/mapper/docker-8:2-396857-aa9f2ec9acebf555804a982caf01a034bf63a48280f781692a300c6a46388522: no such file or directory 

-----------------------------------------------------------

INFO[0016] Error getting container 630484d749d4c7d7fb19feccb6342017c11e9521e2d31c57456cf832da25b0ce from driver devicemapper: open /dev/mapper/docker-8:2-396857-630484d749d4c7d7fb19feccb6342017c11e9521e2d31c57456cf832da25b0ce: no such file or directory 
make: *** [build] Error 1
debug info:
^[[34mINFO^[[0m[0079] No non-localhost DNS nameservers are left in resolv.conf. Using default external servers : [nameserver 8.8.8.8 nameserver 8.8.4.4]
^[[34mDEBU^[[0m[0079] activateDeviceIfNeeded(630484d749d4c7d7fb19feccb6342017c11e9521e2d31c57456cf832da25b0ce)
^[[34mDEBU^[[0m[0079] libdevmapper(6): ioctl/libdm-iface.c:1750 (4) dm info docker-8:2-396857-630484d749d4c7d7fb19feccb6342017c11e9521e2d31c57456cf832da25b0ce  OF   [16384] (*1)
^[[34mINFO^[[0m[0079] +job release_interface(630484d749d4c7d7fb19feccb6342017c11e9521e2d31c57456cf832da25b0ce)
No network information to release for 630484d749d4c7d7fb19feccb6342017c11e9521e2d31c57456cf832da25b0ce
^[[34mINFO^[[0m[0079] -job release_interface(630484d749d4c7d7fb19feccb6342017c11e9521e2d31c57456cf832da25b0ce) = ERR (1)
^[[34mDEBU^[[0m[0079] [devmapper] UnmountDevice(hash=630484d749d4c7d7fb19feccb6342017c11e9521e2d31c57456cf832da25b0ce)
^[[34mDEBU^[[0m[0079] [devmapper] UnmountDevice(hash=630484d749d4c7d7fb19feccb6342017c11e9521e2d31c57456cf832da25b0ce) END
^[[31mERRO^[[0m[0079] Warning: error unmounting device 630484d749d4c7d7fb19feccb6342017c11e9521e2d31c57456cf832da25b0ce: UnmountDevice: device not-mounted id 630484d749d4c7d7fb19feccb6342017c11e9521e2d31c57456cf832da25b0ce
^[[34mDEBU^[[0m[0079] [devmapper] UnmountDevice(hash=630484d749d4c7d7fb19feccb6342017c11e9521e2d31c57456cf832da25b0ce)
^[[34mDEBU^[[0m[0079] [devmapper] UnmountDevice(hash=630484d749d4c7d7fb19feccb6342017c11e9521e2d31c57456cf832da25b0ce) END
^[[31mERRO^[[0m[0079] Warning: error unmounting device 630484d749d4c7d7fb19feccb6342017c11e9521e2d31c57456cf832da25b0ce: UnmountDevice: device not-mounted id 630484d749d4c7d7fb19feccb6342017c11e9521e2d31c57456cf832da25b0ce
Error getting container 630484d749d4c7d7fb19feccb6342017c11e9521e2d31c57456cf832da25b0ce from driver devicemapper: open /dev/mapper/docker-8:2-396857-630484d749d4c7d7fb19feccb6342017c11e9521e2d31c57456cf832da25b0ce: no such file or directory
^[[34mINFO^[[0m[0079] -job build() = ERR (1)
           
-----------------------------------------------------------

FATA[0001] Error response from daemon: Cannot start container fab2a5a481ffd81143d5ceb8eb593cb1ec8c7ad679911e43a863279fb1f5294c: Error getting container fab2a5a481ffd81143d5ceb8eb593cb1ec8c7ad679911e43a863279fb1f5294c from driver devicemapper: Error mounting '/dev/mapper/docker-8:2-396857-fab2a5a481ffd81143d5ceb8eb593cb1ec8c7ad679911e43a863279fb1f5294c' on '/home/s00318865/project/storage_docker/dockerlib/devicemapper/mnt/fab2a5a481ffd81143d5ceb8eb593cb1ec8c7ad679911e43a863279fb1f5294c': no such file or directory 

-----------------------------------------------------------

FATA[0001] Error response from daemon: Cannot start container f13d8fa61600a0dcd1bb50439431921d15db4a91ab801712ea4e5dc7e67695c3: Error getting container f13d8fa61600a0dcd1bb50439431921d15db4a91ab801712ea4e5dc7e67695c3 from driver devicemapper: Error mounting '/dev/mapper/docker-8:1-2367724-f13d8fa61600a0dcd1bb50439431921d15db4a91ab801712ea4e5dc7e67695c3' on '/var/lib/docker/devicemapper/mnt/f13d8fa61600a0dcd1bb50439431921d15db4a91ab801712ea4e5dc7e67695c3': no such file or directory

**Comment by sunyuan3** [comment]
root@p1:~# docker info 
Containers: 51
Images: 79
Storage Driver: devicemapper
 Pool Name: docker-8:2-396857-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 6.375 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 8.868 MB
 Metadata Space Total: 2.147 GB
 Udev Sync Supported: false
 Data loop file: /home/s00318865/project/storage_docker/dockerlib/devicemapper/devicemapper/data
 Metadata loop file: /home/s00318865/project/storage_docker/dockerlib/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.13.0-32-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 4
Total Memory: 3.543 GiB
Name: p1
ID: C2ZX:XU7A:6DDW:BSUP:CFNP:AY6K:IPU3:TKII:OSC2:4MXZ:GW4F:FQGJ
Debug mode (server): true
Debug mode (client): false
Fds: 21
Goroutines: 30
EventsListeners: 0
Init Path: /usr/bin/docker.io
Docker Root Dir: /home/s00318865/project/storage_docker/dockerlib
WARNING: No swap limit support
root@p1:~# 
root@p1:~# 
root@p1:~# 
root@p1:~# 
root@p1:~# 
root@p1:~# 
root@p1:~# docker version
Client version: 1.4.1-dev
Client API version: 1.17
Go version (client): go1.3.3
Git commit (client): 8617ea2-dirty
OS/Arch (client): linux/amd64
Server version: 1.4.1-dev
Server API version: 1.17
Go version (server): go1.3.3
Git commit (server): 8617ea2-dirty
root@p1:~# 
root@p1:~# 
root@p1:~# 
root@p1:~# 
root@p1:~# uname -a
Linux p1 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
root@p1:~#

**Comment by hqhq** [comment]
Hi,
This is a dup of https://github.com/docker/docker/issues/4036 , you can close this for now, and take your attention to that issue.
