### ISSUE TITLE
docker use nfs volume  in container with selinux  Permission denied

### ISSUE THREAD

**Issue by mk-qi** [docker/docker#10725]
[root@docker11100 ~]# docker info
Containers: 3
Images: 45
Storage Driver: devicemapper
 Pool Name: docker-253:2-8594970272-pool
 Pool Blocksize: 65.54 kB
 Data file: /data/dockerstorage/devicemapper/devicemapper/data
 Metadata file: /data/dockerstorage/devicemapper/devicemapper/metadata
 Data Space Used: 1.616 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 3.4 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.84-RHEL7 (2014-03-26)
Execution Driver: native-0.2
Kernel Version: 3.10.0-123.20.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)

[root@docker11100 ~]# cat /etc/fstab 
/dev/mapper/centos-root /                       xfs     defaults        1 1
UUID=e766d04a-5c78-4a87-a346-3c13be452d7d /boot                   xfs     defaults        1 2
/dev/mapper/centos-home /home                   xfs     defaults        1 2
/dev/mapper/centos-home /data                  xfs     defaults        1 2
/dev/mapper/centos-swap swap                    swap    defaults        0 0
192.168.2.62:/vol/samba         /opt/samba   nfs    defaults		 0 0

run  docker
 docker run --name=web08246 -h web08246 --add-host=web08246:127.0.0.1 -v /opt/samba/fanliweb:/opt/fanliweb   -itd   centos:centos  /bin/bash 

 
in container  with df 
192.168.2.62:/vol/samba/fanliweb on /opt/fanliweb type nfs (rw,relatime,vers=3,rsize=65536,wsize=65536,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.2.62,mountvers=3,mountport=4046,mountproto=udp,local_lock=none,addr=192.168.2.62)
192.168.2.62:/vol/samba/tuangouweb on /opt/webdata type nfs (rw,relatime,vers=3,rsize=65536,wsize=65536,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.2.62,mountvers=3,mountport=4046,mountproto=udp,local_lock=none,addr=192.168.2.62)

webdata]# ls
ls: cannot open directory .: Permission denied

**Comment by cpuguy83** [comment]
You probably need to do `chcon -Rt svirt_sandbox_file_t /path/to/volume`
If this fixes the problem please close the issue.

**Comment by mk-qi** [comment]
@cpuguy83   this is only  fix the local volume mount, but very much thanks  that  you attention to this issue,  and finally i solve the problem by the next steps, hope someone else could be helpd who with the same issue 

       systemctl stop docker;
       umount  /opt/samba;
edit fatab  with nfs mount options add 

       context="system_u:object_r:svirt_sandbox_file_t:s0"  
like below, if you have Multiple NFS Mounts,you may add  nosharecache options too(here I wasted a lot of time )  ref: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Security-Enhanced_Linux/sect-Security-Enhanced_Linux-Mounting_File_Systems-Multiple_NFS_Mounts.html

    192.168.2.62:/vol/samba         /opt/samba   nfs    defaults,context="system_u:object_r:svirt_sandbox_file_t:s0"		 0 0
    
    mount -a
   
    systemctl start docker;
