### ISSUE TITLE
Add NULL delimited output support

### ISSUE THREAD

**Issue by schmunk42** [docker/docker#10731]
Could we get something like `find [...] -print0` for `docker ps`, `docker images`, etc... 

like so `docker images -q0`

It would be handy for piping the output to `xargs`.

**Comment by phemmer** [comment]
I don't see why you would need this. Null delimited output is useful when space/newline delimited output doesn't work (the field values contain spaces/newlines). With `docker images -q` (and `docker ps -q`), the values will never contain a space.

**Comment by schmunk42** [comment]
But aren't they separated by newlines?

Basically I tried this ... listing all histories

```
docker images -q | xargs -d '\n' docker history {}
```

But without luck.

**Comment by phemmer** [comment]
That's because you're passing every matching image ID to the `docker history` command. It only supports showing the history of a single image.

    docker images -q | xargs -n 1 docker history

**Comment by schmunk42** [comment]
Thanks!
