### ISSUE TITLE
docker pull scratch failed

### ISSUE THREAD

**Issue by nerro** [docker/docker#10737]
Description of problem:

I cannot pull scratch docker image (pulling of other images works without problem).
Error looks like so:

    docker pull scratch
    Pulling repository scratch
    511136ea3c5a: Download complete
    FATA[0004] 'scratch' is a reserved name

`docker version`:

    Client version: 1.5.0
    Client API version: 1.17
    Go version (client): go1.4.1
    Git commit (client): a8a31ef
    OS/Arch (client): linux/amd64
    Server version: 1.5.0
    Server API version: 1.17
    Go version (server): go1.4.1
    Git commit (server): a8a31ef

`docker info`:

    Containers: 0
    Images: 3
    Storage Driver: devicemapper
     Pool Name: docker-8:17-1441793-pool
     Pool Blocksize: 65.54 kB
     Backing Filesystem: extfs
     Data file: /dev/loop0
     Metadata file: /dev/loop1
     Data Space Used: 415.9 MB
     Data Space Total: 107.4 GB
     Metadata Space Used: 860.2 kB
     Metadata Space Total: 2.147 GB
     Udev Sync Supported: true
     Data loop file: /var/lib/docker/devicemapper/devicemapper/data
     Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
     Library Version: 1.02.93 (2015-01-30)
    Execution Driver: native-0.2
    Kernel Version: 3.18.6-1-ARCH
    Operating System: Arch Linux
    CPUs: 4
    Total Memory: 3.864 GiB
    Name: messenger
    ID: GIJH:YU43:4SPA:TDYI:2TVH:BSRF:FKVP:GNWM:7QGD:64FH:TOCI:FGBB
    Username: nerro
    Registry: [https://index.docker.io/v1/]

`uname -a`:

    Linux messenger 3.18.6-1-ARCH #1 SMP PREEMPT Sat Feb 7 08:44:05 CET 2015 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
Archlinux is installed on VirtualBox.

How reproducible:
Fresh installation of docker 1.5.0

Steps to Reproduce:
1. docker pull scratch with fresh installed docker and no empty images

**Comment by cpuguy83** [comment]
`scratch` is a reserved name and not a real image anymore.
When you `FROM scratch` in a Dockerfile it no longer downloads an actual image layer (since it's just an empty fs anyway).

Is this presenting a particular problem? Why  are you trying to actually `pull` scratch?

**Comment by nerro** [comment]
Thanks for explaining. Actually it's not a problem. I like that all my images are tagged and I can see how peoples make their Dockerfiles (best practice learning etc.)

From my perspective => **closed**.


P.S. If `scratch` not a real image anymore, that means many official images will have less layers? E.g. `debian` had 3 layer and will have 2?

**Comment by cpuguy83** [comment]
Hmm, I suppose they would be, once their are built with a 1.5 docker daemon.

**Comment by wardi** [comment]
I was using this image for a data-only container. is there a new recommended image now?

**Comment by thaJeztah** [comment]
@wardi you can try the `tianon/true` image, which is 125 bytes (https://registry.hub.docker.com/u/tianon/true/)

or, if you're creating a data-container for a specific container (e.g. For your database container); use the *same image* as the container itself uses, but create it with a different command; using the same image multiple times doesn't cost any disk space.

**Comment by nerro** [comment]
@thaJeztah I agree with wardi and use the technique http://www.tech-d.net/2014/11/18/data-only-container-madness/ as best practice.

**Comment by thaJeztah** [comment]
@nerro exactly, I wanted to add a link to that article, but didn't have it at hand. For people *not* following that best practice (there could be valid reasons), I think the tianon/true comes closest to `scratch`, alternatively, create one yourself; `FROM scratch` in a Dockerfile should still work.

**Comment by wardi** [comment]
Thanks @thaJeztah, this just for the case where someone is using boot2docker and the host volumes are too slow/incompatible. Using the database image sounds fine while I wait a nicer storage solution for docker on windows+mac :-)

**Comment by EricLanduyt** [comment]
I was previously creating data containers this way:

    docker create --volume=/data --name data scratch ""

But now this is not working anymore. As suggested in the best practice, I can create from the same image as the application itself, but this application itself is created from java and so on... seems a bit fuzzy to me. Then I can create from tianon/true, but 'scratch' looked more clean when listing containers ...

**Comment by thaJeztah** [comment]
@EricLanduyt if you need a "scratch" image, you can create it;

```Dockerfile
FROM scratch
VOLUME /data
```

`docker build -t data .`, which produces;
```
REPOSITORY   TAG     IMAGE ID            CREATED             VIRTUAL SIZE
data         latest  77f133bce7ba        21 seconds ago      0 B
```

And you don't even need to define the volume;
```bash
docker create --name my-data data
```

**Comment by EricLanduyt** [comment]
@thaJeztah thank you for the trick !

**Comment by pikeas** [comment]
@nerro Consider the counterpoint in one of the comments on the article you linked: http://www.tech-d.net/2014/11/18/data-only-container-madness/#comment-1706806635

**Comment by pfortuna** [comment]
Instead of using the same image on the data-only container, I prefer this approach:
http://jdemarks.azurewebsites.net/2015/04/1083/

It's cleaner and when doing backups you don't have to remember there's other files there that you should exclude from backup.

**Comment by pfortuna** [comment]
Come to think about it, it seems too dangerous to use data-only volumes. If you need to remove it, the only reference to your data is lost and AFAIK there is no way you can recreate it. If this is not true, please do tell.

**Comment by thaJeztah** [comment]
Instead of an empty data-only container, just create a volume (`docker volume create ...`)
