### ISSUE TITLE
Bug (maybe): "*" statement doesn't work in combination with "docker run dpkg -i"

### ISSUE THREAD

**Issue by Vrakfall** [docker/docker#10735]
I'm not sure if this is a real bug or an intended behavior.
Anyway, this came down to me while trying to answer [this question on Stackoverflow](http://stackoverflow.com/questions/28456836/dockerfile-manual-install-of-deb-files/28478210#28478210).
It seems like the `*` doesn't work in combination with the `docker run somecontainer dpkg -i` command.

Let's take the freshly created `/debdir` directory as example. By typing `docker run somecontainer dpkg -i /debdir/*.deb` dpkg is trying to install a file called `*.deb` instead of installing all the `.deb` files contained in `/debdir`.

My workaround was to copy a `install.sh` file that I `chmod`ed ` +x` which runs the command and to use it as default command/entrypoint. I found this workaround after checking that the command worked ok in an interactive shell started in the container.

It doesn't look like being an intended behavior to me and if you want more information about the problem and my workaround example, please check [the question on Stackoverflow and my answer to it](http://stackoverflow.com/questions/28456836/dockerfile-manual-install-of-deb-files/28478210#28478210).

Thank you for reading.

P.S. : I reproduced the bug using Docker 1.4.1, didn't try with the 1.5.0 yet.

**Comment by phemmer** [comment]
`*` is a shell metacharacter. You need to invoke a shell for it to be expanded.

    docker run somecontainer sh -c 'dpkg -i /debdir/*.deb'

**Comment by Vrakfall** [comment]
Alright, that worked, thank you !

But now I'm wondering why I can use it with some other commands like `ls`.
`docker run debtest ls /*` does work, for example.

**Comment by phemmer** [comment]
The behavior is dependent upon the entrypoint script (if there is one).
If there's an entrypoint script, your `run` arguments get passed to it, and then it might be calling `eval` or `exec` to run them. Lots of variables. `sh -c ...` is the safest as it generally works with all implementations.

**Comment by Vrakfall** [comment]
I tried both commands on a fresh debian image, I don't think there's any entrypoint script.
Anyway, your tip will help me a lot in the future. Thanks a lot !

**Comment by cpuguy83** [comment]
Closing since it seems like this is resolved.

**Comment by phemmer** [comment]
> `docker run debtest ls /*` does work, for example.

Oh, this looks like it works, but it really doesn't. What's happening is that the expansion of `/*` is happening locally. So the actual command being passed to docker is

    docker run debtest ls /bin /dev /etc /lib ...

If you create a file on your local machine at `/`, something that doesn't exist in the container, you'll see that you get a `ls: cannot access /...` message from your command.

**Comment by Vrakfall** [comment]
Oh ok, now it's even clearer. ^^ I understand the full process of it from top to bottom. =P

Thanks again !
