### ISSUE TITLE
Exec format error : Cannot start container <id> : exec format error 

### ISSUE THREAD

**Issue by lkrishnamurthy** [docker/docker#10738]
I tried to create a docker image using a precise ubuntu base. I have a my startup script that looks like this but when I run this using docker run command I get the Exec format errors. Tried debugging this several time but no use. Anyway to look into docker event logs or turn on verbose to see what might be going wrong? 

If I comment out the CMD line in my DockerFile everything works fine. 

Here's the startup script called startup-stanbol.sh which has execute permission.

!/usr/bin/env bash
if [[ $1 = "-d" ]]; then
  while true; do sleep 1000; done
fi
if [[ $1 = "-bash" ]]; then
  echo "Using Bash"
  /bin/bash
fi
java -Xmx1g -jar org.apache.stanbol.launchers.stable-1.0.0-SNAPSHOT.jar -p 9080

**Comment by phemmer** [comment]
Your shebang is incorrect.
You need

    #!/usr/bin/env bash

Not

    !/usr/bin/env bash

(missing `#`)

**Comment by cpuguy83** [comment]
@lkrishnamurthy The problem seems to be the your declartion of bash at the top.

`!/usr/bin/env bash`
Should be: `#! /usr/bin/env bash`
And probably more appropriately `#!/bin/bash`

Closing, but lmk if this does not fix.

**Comment by lkrishnamurthy** [comment]
Thanks. That worked. Appreciate your quick response.
