### ISSUE TITLE
`docker run --link bogus:alias ...` fails but leaves a stopped container (and 'Name' is lost)

### ISSUE THREAD

**Issue by trentm** [docker/docker#10746]
Description of problem:

`docker run --link bogus:alias ...` (i.e. attempting to link to a non-existant
container) fails but leaves a stopped container. Also, the container 'name' is
lost.

```
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

$ sudo docker run -d -P --name web --link db:db training/webapp python app.py
FATA[0000] Error response from daemon: Could not get container for db
$ echo $?
1
$ docker ps -a
CONTAINER ID        IMAGE                    COMMAND             CREATED             STATUS              PORTS               NAMES
5c823f6d633b        training/webapp:latest   "python app.py"     3 seconds ago

$ docker inspect -f "{{ .HostConfig.Links }}" 5c823f6d633b
<no value>
```

Not also that in docker 1.5.0 the *Name* is not on the created container:

```
$ docker inspect -f "{{ .HostConfig.Links }}" web
Error: No such image or container: web
```

My *guess* is that it is a bug that the failure happens *after* the container
creation (or that the container is not cleaned up after hitting a create
failure). The `docker run` does not emit the created container Id, so it them
becomes a game to find the container that *was* created to clean up manually
afterwards.

`docker version`:

```
$ docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

`docker info`:

```
$ docker info
Containers: 1
Images: 29
Storage Driver: devicemapper
 Pool Name: docker-253:1-262158-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.079 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 2.179 MB
 Metadata Space Total: 2.147 GB
 Udev Sync Supported: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.13.0-36-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 1
Total Memory: 3.861 GiB
Name: ce02619e-ff66-4c4d-cc97-d973517bdc30
ID: KUPV:LPLJ:DLA3:FJNG:GQSR:LWUM:7I3P:AIX3:ZUD3:ILWV:43KD:FK4M
Username: trentm
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support
```

`uname -a`:

```
$ uname -a
Linux ce02619e-ff66-4c4d-cc97-d973517bdc30 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.):

This is a Ubuntu Trusty 14.04 KVM instance running on the Joyent cloud
with 4GiB RAM.

How reproducible:

Reproducible every time.

Steps to Reproduce:
1. `docker run --link bogus:alias busybox sleep 60`
2. `docker ps -a`

Actual Results:
- A stopped container is created.
- The name on the container is lost (in docker 1.5.0 only, in docker 1.4.1
  the name wasn't lost).

Expected Results:
- If there is a link failure in container creation, then don't create the
  container.
- Or, if the design choice is to create the container and leave it stopped,
  then document that behaviour and also emit the created container Id.

**Comment by thaJeztah** [comment]
I fully agree with your "expected results".

I tried to reproduce the "missing name" issue, but wasn't able to reproduce that part (tested on 1.5.0 on Ubuntu 14.04.1);

```bash
➜ ~ docker run --link bogus:alias busybox sleep 60                                                                                             
FATA[0000] Error response from daemon: Could not get container for bogus                                                                        
➜ ~ docker ps -a

CONTAINER ID        IMAGE                       COMMAND                CREATED                 PORTS     NAMES                                                                                                        
4452d7334331        busybox:latest              "sleep 60"             About a minute ago                suspicious_brattain

➜ ~ docker run --link bogus:alias --name web busybox sleep 60                                                                                
FATA[0000] Error response from daemon: Could not get container for bogus                                                                        
➜ ~ docker inspect -f "{{ .HostConfig.Links }}" web                                                                                            
<no value>

**Comment by estesp** [comment]
`docker run` is both a create and start operation from a Docker API perspective, so what you are seeing is the effect of a successful **create**, but a failed **start** due to the bogus link alias.  In that case the code does call a simple "cleanup" routine to unset any links and unmount, but the container itself (at least it's runtime config and layer config) is, as you noted, in the stopped state and not deleted.

As @thaJeztah noted, however, I'm not seeing any loss of the *name* parameter; it is shown in `docker ps -l` and I can `docker inspect` the *name* I set with `--name` in 1.5.0 official GA on Ubuntu 14.10.  Can you verify your test again and make sure you are seeing different behavior?

As to what Docker should do with this failure (and other failures during start) is a recent topic of discussion.  I've been looking at making delete more robust and checking the error paths to try and see what can be done.  In this specific case, given the link setup fails, and the stopped container config has been cleaned of any link details, there is no way to start the "bogus" container and then re-start your linked container--so I think in this case an argument for the docker daemon doing a full cleanup as if you never called `docker run` may be reasonable.

**Comment by fgsch** [comment]
Just to add, in my particular case the container is exposing some ports also. 
The ports are not exposed when it fails to link (expected) but restarting the container after ensuring the container it links to is running will not expose the ports either.

If the plan is to keep the container around after failure, I presume to be able to restart it after the situation is corrected, ports (if any) should be exposed as well.

**Comment by cpuguy83** [comment]
I think this can be closed since the naming issue is fixed.
It should not be expected for the link to actually work since links are specifically tied to a container ID not a name.
