### ISSUE TITLE
container with --restart=always fails to start at boot because of allocate_port()

### ISSUE THREAD

**Issue by jseun** [docker/docker#10749]
Hey!  I am running containers with docker 1.5.0 and it seems my freeipa-server does not start properly at boot.  I have to start it manually.

Docker says : bind: address already in use

However, I have no daemon running (nor installed) and bound to that port.  Note that a manual start succeed.

Container created with "docker run -d --restart=always --name freeipa-server -h host.local.domain -p 53:53/tcp -p 53:53/udp -p 80:80/tcp -p 443:443/tcp -p 389:389/tcp -p 636:636/tcp -p 88:88/tcp -p 88:88/udp -p 464:464/tcp -p 464:464/udp -p 123:123/udp -p 7389:7389/tcp -p 9443:9443/tcp -p 9444:9444/tcp -p 9445:9445/tcp -e PASSWORD=secret -v /srv/freeipa-server/root/:/root/ adelton/freeipa-server"

INFO[0001] +job allocate_interface(60f2157e52162b4a663766d407559e693ef870a5feb0194e8f11b142d63b224b) 
INFO[0001] -job allocate_interface(60f2157e52162b4a663766d407559e693ef870a5feb0194e8f11b142d63b224b) = OK (0) 
INFO[0001] +job allocate_port(60f2157e52162b4a663766d407559e693ef870a5feb0194e8f11b142d63b224b) 
INFO[0001] -job allocate_port(60f2157e52162b4a663766d407559e693ef870a5feb0194e8f11b142d63b224b) = OK (0) 
INFO[0001] +job allocate_port(60f2157e52162b4a663766d407559e693ef870a5feb0194e8f11b142d63b224b) 
INFO[0001] -job allocate_port(60f2157e52162b4a663766d407559e693ef870a5feb0194e8f11b142d63b224b) = OK (0) 
INFO[0001] +job allocate_port(60f2157e52162b4a663766d407559e693ef870a5feb0194e8f11b142d63b224b) 
INFO[0001] -job allocate_port(60f2157e52162b4a663766d407559e693ef870a5feb0194e8f11b142d63b224b) = OK (0) 
INFO[0001] +job allocate_port(60f2157e52162b4a663766d407559e693ef870a5feb0194e8f11b142d63b224b) 
INFO[0001] -job allocate_port(60f2157e52162b4a663766d407559e693ef870a5feb0194e8f11b142d63b224b) = OK (0) 
INFO[0001] +job allocate_port(60f2157e52162b4a663766d407559e693ef870a5feb0194e8f11b142d63b224b) 
INFO[0001] -job allocate_port(60f2157e52162b4a663766d407559e693ef870a5feb0194e8f11b142d63b224b) = OK (0) 
INFO[0001] +job allocate_port(60f2157e52162b4a663766d407559e693ef870a5feb0194e8f11b142d63b224b) 
[f423f9fe.allocate_port(60f2157e52162b4a663766d407559e693ef870a5feb0194e8f11b142d63b224b)] Failed to allocate and map port 123: Error starting userland proxy: listen udp 0.0.0.0:123: bind: address already in use
Error starting userland proxy: listen udp 0.0.0.0:123: bind: address already in use
INFO[0001] -job allocate_port(60f2157e52162b4a663766d407559e693ef870a5feb0194e8f11b142d63b224b) = ERR (1) 
INFO[0001] +job release_interface(60f2157e52162b4a663766d407559e693ef870a5feb0194e8f11b142d63b224b) 
INFO[0001] -job release_interface(60f2157e52162b4a663766d407559e693ef870a5feb0194e8f11b142d63b224b) = OK (0) 
INFO[0001] +job release_interface(60f2157e52162b4a663766d407559e693ef870a5feb0194e8f11b142d63b224b) 
INFO[0001] Unable to unmap port 0.0.0.0:464: port is not mapped 
INFO[0001] Unable to unmap port 0.0.0.0:53: port is not mapped 
INFO[0001] Unable to unmap port 0.0.0.0:53: port is not mapped 
INFO[0001] Unable to unmap port 0.0.0.0:636: port is not mapped 
INFO[0001] Unable to unmap port 0.0.0.0:88: port is not mapped 
INFO[0001] -job release_interface(60f2157e52162b4a663766d407559e693ef870a5feb0194e8f11b142d63b224b) = OK (0)

**Comment by jfrazelle** [comment]
are you sure nothing else is listening on that port

**Comment by jfrazelle** [comment]
ping @jseun

**Comment by jseun** [comment]
@jfrazelle, sorry for the delay.  I had no time to check further on this one but I am pretty sure there is no daemon listening on that port.  If I start the docker manually, it does succeed.

**Comment by jfrazelle** [comment]
can you give us the output of docker version and docker info

**Comment by jseun** [comment]
```
$ docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

$ docker info
Containers: 1
Images: 14
Storage Driver: btrfs
Execution Driver: native-0.2
Kernel Version: 3.16.0-30-generic
Operating System: Ubuntu 14.04 LTS
CPUs: 1
Total Memory: 3.859 GiB
Name: docker
ID: OSWD:SIZU:WPRJ:A2TF:A2AY:C7HV:YWDP:MHGC:4IOH:STKQ:QSCR:R7B3
```

**Comment by jfrazelle** [comment]
might be releated to https://github.com/docker/docker/issues/9047

**Comment by jseun** [comment]
Note that there is only one container on that machine.  Here's the output of netstat.

```
$ netstat -na
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN     
udp        0      0 0.0.0.0:63177           0.0.0.0:*                          
udp        0      0 0.0.0.0:68              0.0.0.0:*                          
udp6       0      0 :::4621                 :::*
```

**Comment by thaJeztah** [comment]
Is this still an issue with the current release? A lot has changed since docker 1.5 and the integration of libnetwork

**Comment by albers** [comment]
I also have problems with some containers and they still exist in Docker 1.8.2.

I was not able to track it down, though. There are some containers that never come up while others always start. The strange fact is that both categories of containers are started with identical `docker-compose.yml`s. These containers have links, and they are bound to virtual IP addresses of the host.

See https://github.com/docker/compose/issues/872.

So I can't give a reproducable example, and I'm not even sure if my issue is the same as reported here.

**Comment by thaJeztah** [comment]
Thanks @albers, I'll keep this one open, if you happen to run into that situation again, and are able to capture daemon logs, that would be appreciated

**Comment by albers** [comment]
@thaJeztah My issue is different: It only happens when I bind ports to a specific virtual host address. I get a different error message:
>Failed to start container d7334d7bc45f602727a17f146bc6291157af3ba27f74613f1414807b1283da04: failed to create endpoint trusting_spence on network bridge: Error starting userland proxy: listen tcp 10.0.81.0:80: bind: cannot assign requested address

It still occurs on Docker 1.9.1.
From my point of view, this issue can be closed.

**Comment by thaJeztah** [comment]
@albers thanks. Feel free to open a separate issue if you think it needs to be tracked (well, you know the drill, haha)

**Comment by albers** [comment]
@thaJeztah created #18826 :wink:

**Comment by thaJeztah** [comment]
Thanks @albers!
