### ISSUE TITLE
Proposal: Remove the hack/ directory and just use project/

### ISSUE THREAD

**Issue by jhowardmsft** [docker/docker#10741]
## Issue: hack/ symbolic link to project/ causes issues on Windows

When cloning the repo on Windows, as (for historical reasons) hack/ is now a symbolic link to project/, the symlink doesn’t get setup correctly. Windows git ends up treating hack as a 7 character file containing the word ‘project’, so it all starts going wrong quickly... In reality the hack/ directory (or symlink) is redundant.

There is a pretty messy workaround for git which is still error prone at http://stackoverflow.com/questions/5917249/git-symlinks-in-windows/16754068#16754068.

## Proposal

Looking at the build scripts, it seems just about everything is still referring to hack/. I think to make things easier going forward for supporting both Linux and Windows, the hack directory (or link as it is now) can be removed after files referring to hack/* are modified to their project/* equivalent.

I believe the list of files involved here from a first-pass scan is:

Docker/CHANGELOG.MD: 
Docker/Dockerfile
Docker/Makefile
Docker/builder/parser/testfiles/docker/Dockerfile
Docker/builder/parser/testfiles/docker/result
Docker/contrib/mkimage-debootstrap.sh
Docker/dockerversion/dockerversion.go
Docker/project/README.md
Docker/project/RELEASE-CHECKLIST.md
docker/project/dind
Docker/project/install.sh
Docker/project/make.sh
Docker/project/make/README.md
Docker/project/make/test-unit
Docker/project/release.sh
Docker/vendor/MAINTAINERS
Docker/vendor/src/github.com/docker/docker/hack/make/.validate

**Comment by tianon** [comment]
See also #10002 and especially https://github.com/docker/docker/issues/3502#issuecomment-63145996 for more details about why this is still here.  I don't disagree that it could use solving, but I don't think the solution is really as clear and well-agreed upon as just "update all the `hack/` references to `project/` and delete the symlink".

**Comment by icecrime** [comment]
Until the situation is agreed upon, I would be +1 for updating all `hack/` references to `project/` for the sake of clarifying the immediate situation.

@tianon You're the boss on this, I think it's should be your call to either pick one directory, or go for a fine-grained split (I can do the PR if that helps)!

Ping @jfrazelle @tibor @crosbymichael if you want to voice an opinion on this!

**Comment by jfrazelle** [comment]
what if we move all the scripts back to hack and remove the symlink, idk I
am all for whatever @tianon wants because he is the bash boss and these are
his babies ;)

**Comment by tianon** [comment]
I personally loved the hack name and the imaginative images that name
invokes, so I'm definitely +1 on bringing it back with just the scripts.
