### ISSUE TITLE
Docs need guidelines re: when to used linked vs when to use single container

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#10742]
https://docs.docker.com/userguide/dockerlinks/  and related should provide guidance on how or why a user would choose one method of creating container versus another (security, management, data).  Also, do we have general guidelines as to which we recommend as the "default" technique.

Corollary, it would be good if containers in the Hub follow the default technique to avoid confusing messages.

**Comment by MHBauer** [comment]
How does this change now that links are going away?

**Comment by moxiegirl** [comment]
@MHBauer It definitely has a lower priority.

**Comment by LK4D4** [comment]
Going to close this as it's not a priority at all.
