### ISSUE TITLE
rename incompletely implemented?

### ISSUE THREAD

**Issue by gubuntu** [docker/docker#10744]
Link a new container that has the same name as a container that has been renamed and the old container is referenced which means the link is using the old container ID instead of respecting the new container name. 

renamed database container: 
    docker rename DBContainerA DBContainerB
created a new database container with the same name as the original renamed container:
    docker run --name="DBContainerA" ...
created a new application container supposedly linking the new database container:
    docker run --name="AppContainer"  --link DBContainerA:myAlias ...

This doesn't work as expected because it's actually linking DBContainerB. It will only link DBContainerA if I link using the ID of the new DBContainerA. 

If this is intended behaviour it needs to be documented.

uname -a
Linux zapta04meta01 3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

docker info
Containers: 4
Images: 206
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 214
Execution Driver: native-0.2
Kernel Version: 3.13.0-45-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 4
Total Memory: 3.86 GiB
Name: zapta04meta01
ID: RLGL:LARG:JZ3P:RPN3:MRNC:7EIJ:232S:C2RU:REDN:3LOO:4Q2B:BSRP
WARNING: No swap limit support

**Comment by thaJeztah** [comment]
Thanks for reporting. Would you be able to provide a simple example to reproduce the steps you've taken? This may assist the maintainers to investigate. Also the output of `docker version`,  `docker info` and `uname -a` never hurt.

**Comment by cpuguy83** [comment]
I think this is pretty much expected since you can't start a new container (pre 1.5)  with the same name and have the links work either... is it intentionally this way? I'm not certain.

**Comment by brahmaroutu** [comment]
Rename only changes the name of the container. The container should still use the old id.

**Comment by coolljt0725** [comment]
@brahmaroutu is right, It's better to use a container ID to link rather than use the container name

**Comment by thaJeztah** [comment]
I think all answers above miss the issue;

> This doesn't work as expected because it's actually linking DBContainerB. It will only link DBContainerA if I link using the ID of the new DBContainerA.

If I read it correctly, the steps taken were (slightly reworded)

1. `docker run --name="my-db" database`
2. `docker rename my-db my-old-db`
3.  `docker run --name="my-db" database`
4. `docker run --link my-db:my-alias myApp`

And the `myApp` container ends up being linked to `my-old-db`, *not* `my-db`, even though the `myApp` container was created and started *after* the database-container was renamed.

I haven't had time to test this scenario and see if I could reproduce, but *if* this is indeed what's happening! this looks like a bug.

Possibly the IP-addresses aren't updated properly, because the old container still *exists*, but is only renamed?

**Comment by gubuntu** [comment]
@thaJeztah you have it spot on.

**Comment by brahmaroutu** [comment]
I tried this out and I see the my-alias is correctly mapping to the IP address of the my-db container created in the step 3. Please check /etc/hosts file in the container created in the step 4 and see if it is using the IP address for the container from step 3. @thaJeztah  is right, we do not use the name of the container to link.
@gubuntu Please check the ipaddresses and connection setting in your environment.

**Comment by cpuguy83** [comment]
I cannot repro this, here is my test case:
```bash
#!/bin/bash

docker run -d --name redis redis > /dev/null
docker rename redis redis_old > /dev/null
docker run -d --name redis redis > /dev/null
redis_ip=$(docker inspect -f '{{ .NetworkSettings.IPAddress }}' redis)
link_ip=$(docker run --link redis:db --rm busybox /bin/sh -c 'echo $DB_PORT_6379_TCP_ADDR')


[ "$redis_ip" == "$link_ip" ] || out=FAIL && \
  (
    # Remove the redis_old to make sure we are not talking to it
    docker rm -f redis_old > /dev/null
    docker run --rm --link redis:db busybox /bin/sh -c 'ping -c 1 db' > /dev/null
  )

if [ $? -gt 0 ]; then
  out=FAIL
else
  out=PASS
fi

docker rm -f redis > /dev/null

echo $out
[ "$out" == "FAIL" ] && exit 1


```

**Comment by thaJeztah** [comment]
@cpuguy83 I have also been trying to reproduce, and wasn't able to reproduce the problem so far.

Only thing left I wanted to try is;

1. create db container
2. create app-container, linking to db-container
3. rename db container to db-old
4. create *new* db-container
5. create *new* app container and link that to the *new* db-container

Wondering if the keeping the "old" app-container from step 2. around would somehow cause trouble.

**Comment by brahmaroutu** [comment]
@thaJeztah As mentioned above, I had my container from step 3 running and it did not cause any link issues.

**Comment by thaJeztah** [comment]
@brahmaroutu ah, yes.

In that case, I think this should be closed, unless @gubuntu is able to provide the exact steps to reproduce.

**Comment by thaJeztah** [comment]
@cpuguy83 I think this issue can be closed because we cannot reproduce?

**Comment by cpuguy83** [comment]
Closed since we don't have a reproducible case.
If you can provide a way for us to reproduce (exact steps... like Dockerfile + docker run commands) would be fantastic.

Thanks for the report!
