### ISSUE TITLE
Can't start any service in container with error: Failed to get D-Bus connection: No connection to service manager

### ISSUE THREAD

**Issue by baoxinru** [docker/docker#10758]
Hi, All

I installed docker image and build a image with the following Dockerfile.

---------------------------------------------------------------------------------------------------------------------------
 
#base image will be pulled from Docker Hub, see https://registry.hub.docker.com/_/centos/
FROM centos:centos7
 
#setup dependencies
RUN cd /etc/yum.repos.d &&\
    rm * &&\
    curl http://10.74.61.108/pub/ngvds/Internal-CentOS-7.repo > Internal-CentOS-7.repo &&\
    curl http://10.74.61.108/pub/ngvds/IPCDN-CentOS-7.repo > IPCDN-CentOS-7.repo
RUN yum makecache
RUN yum -y install net-tools wget zip unzip nano tar
 
#subsys directory is missing in centos7 docker container environment
RUN mkdir /var/lock/subsys
 
#install se node
RUN yum -y install ipcdn-se
 
#remove it so that nginfra will create a correct one
RUN rm -f /etc/cisco/ngvdsis/nginfra/startup.config
 
#setup sshd server so that we can ssh to our container se
RUN yum -y install openssh-server
RUN ssh-keygen -A
RUN echo "root:default" | chpasswd
 
#some work has to be done when the container is up rather than in dockerfile,
#so we create a shell script as the entry point of the image.
RUN wget ftp://10.74.61.154/pub2/project/docker/docker_entry.sh
RUN chmod +x docker_entry.sh
 
#run our entry point shell script when the container is up
CMD ["/docker_entry.sh"]
---------------------------------------------------------------------------------------------------------------------------

When I ssh to the container and run the command 'service xxx start', an error popped:

[root@docker-se-test ~]# service nginfra start
Redirecting to /bin/systemctl start  nginfra.service
/sbin/service: line 79: /bin/systemctl: No such file or directory

Actually, fakesystemd is installed in the container instead of systemd.

[root@docker-se-test ~]# rpm -qa|grep systemd
fakesystemd-1-17.el7.centos.noarch
systemd-libs-208-11.el7_0.6.x86_64
systemd-python-208-11.el7_0.6.x86_64
systemd-sysv-208-11.el7_0.6.x86_64

So I remove fakesystemd and install systemd with the command 'yum swap -- remove fakesystemd -- install systemd systemd-libs'. 

[root@docker-se-test ~]# rpm -qa|grep systemd
systemd-libs-208-11.el7_0.6.x86_64
systemd-208-11.el7_0.6.x86_64
systemd-python-208-11.el7_0.6.x86_64
systemd-sysv-208-11.el7_0.6.x86_64

But I still can't start the service:
[root@docker-se-test ~]# service nginfra start
Redirecting to /bin/systemctl start  nginfra.service
Failed to get D-Bus connection: No connection to service manager.

Does anyone ever meet and solve the issue?
[root@docker-se-test ~]# rpm -qa|grep dbus
dbus-python-1.1.1-9.el7.x86_64
dbus-1.6.12-8.el7.x86_64
dbus-glib-0.100-7.el7.x86_64
dbus-libs-1.6.12-8.el7.x86_64

Thanks

**Comment by jfrazelle** [comment]
Closing since this isn't really a docker issue.
For support please see #docker on IRC, the docker-user mailing list, or forums.docker.com
