### ISSUE TITLE
High CPU usage with agetty when running Fedora-based 7 container with /sbin/init

### ISSUE THREAD

**Issue by testn** [docker/docker#10756]
I noticed high CPU usage with agetty when running Fedora-based container with /sbin/init in privileged mode especially when there is an ssh session. agetty process seems to peg the CPU. 

I thought the issue was addressed previously as mentioned in https://bugzilla.redhat.com/show_bug.cgi?id=1046469 and https://github.com/docker/docker/issues/4040. However, I noticed a very similar issue occasionally with agetty. Does anyone else encounter a similar issue?

To reproduce, you need to start two Fedora based container in privileged mode. If you start only one in privileged mode, there will be no problem. 

It is reproducible on Docker 1.4.1 and 1.5.0

**Dockerfile**
```
FROM centos:centos7
RUN yum -y swap -- remove fakesystemd -- install systemd systemd-libs
CMD ["/usr/sbin/init"]
```

**Script**
```
docker build -t test .
docker run -d --privileged test
docker run -d --privileged test
```

**Comment by testn** [comment]
@tianon, I noticed a similar problem as what you have diagnosed in https://github.com/docker/docker/issues/4040

**Comment by cpuguy83** [comment]
@testn The other issue was resolved as issues with running in privileged + an init.
I don't think there's anything we can really do here other than what was discussed in #4040.

Closing this, but feel free to ping here if you'd like to discuss.
