### ISSUE TITLE
docker-1.3.2-4.el7.centos.x86_64 - using /var/run/docker.sock as a volume throws permission denied error

### ISSUE THREAD

**Issue by ranjanparth** [docker/docker#10761]
docker-1.3.2-4.el7.centos.x86_64 - using /var/run/docker.sock as a volume throws permission denied error

Inside the container

[root@localhost]# ls -la /var/run/
ls: cannot access /var/run/docker.sock: Permission denied
total 28
drwxr-xr-x.  8 root root 4096 Feb 13 06:22 .
drwxr-xr-x. 18 root root 4096 Feb 13 06:22 ..
drwxr-xr-x.  2 root root 4096 Jan 29 08:34 blkid
drwxr-xr-x.  2 root root 4096 Jun 17  2014 console
-??????????  ? ?    ?       ?            ? docker.sock
drwxr-xr-x.  2 root root 4096 Jun 17  2014 faillock
drwxr-xr-x.  2 root root 4096 Jan 29 08:36 lock
drwxrwxrwt.  2 root root   40 Feb 13 06:22 secrets
drwxr-xr-x.  2 root root 4096 Jun 17  2014 sepermit

**Comment by phemmer** [comment]
SELinux would be my first guess here. Do you have it enabled on the host?

**Comment by ranjanparth** [comment]
same issue seen with docker 1.5 as well

**Comment by ranjanparth** [comment]
Yes it was selinux, had to setenforce 0 and it seems to work now. Thanks!
