### ISSUE TITLE
Upgrade from lxc-docker 1.4.1 -> 1.5.0 breaks running containers

### ISSUE THREAD

**Issue by Ropes** [docker/docker#10769]
We had a running cluster of etcd in Docker containers across three hosts which were version 1.4.1 on Ubuntu 14.04 3.13.0-37-generic(old kernal might be to fault). Running on AWS.  We salted one of the servers, and caused installing of the `latest` lxc-docker package.

We then got alerted that the etcd container on that host had crashed.  Check the logs, etcd didn't log anything upon exit, it just a halted container. Attempted to start  the formerly running `etcd` container under the 1.5.0 Docker daemon and received the following error:
```
$ docker start etcd
Error response from daemon: Cannot start container etcd: Error getting container 51d67b7d21af58ba1aa8c574a753e901096df56f0fd915a175690234487582e2 from driver devicemapper: Error mounting '/dev/mapper/docker-202:1-792911-51d67b7d21af58ba1aa8c574a753e901096df56f0fd915a175690234487582e2' on '/var/lib/docker/devicemapper/mnt/51d67b7d21af58ba1aa8c574a753e901096df56f0fd915a175690234487582e2': device or resource busy
FATA[0000] Error: failed to start one or more containers 
```

Since we'd only lost one node of etcd, decided to delete the current container and start a new one since that error is rather terrifying.  However that failed as well:
```
$ docker rm etcd
Error response from daemon: Cannot destroy container etcd: Driver devicemapper failed to remove root filesystem 51d67b7d21af58ba1aa8c574a753e901096df56f0fd915a175690234487582e2: Device is Busy
FATA[0010] Error: failed to remove one or more containers 
```

Solution that worked for us:

1. Rolled back to lxc-docker-1.4.1
  * `apt-get remove lxc-docker`
  * ` apt-get install lxc-docker-1.4.1`
2. Restarted docker daemon
3. Able to purge/`rm` old container
4. Started new container (things working fine)

Attempted to reproduce in second environment but on a newer kernal:
```
Linux lyd5 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
The containers did not fail and go into an un-removable state.

Host which had the failure:
-----------------------------------------------
After reverting to back to 1.4.1, here's the host info for debugging if helpful:

docker version
```
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
```
docker -D info
```
Containers: 1
Images: 15
Storage Driver: devicemapper
 Pool Name: docker-202:1-792911-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 932.8 MB
 Data Space Total: 107.4 GB
 Metadata Space Used: 1.769 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.13.0-37-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 4
Total Memory: 14.69 GiB
Name: entrpc2
ID: IPQS:K5Y6:WOW6:M4DJ:TSBR:H6JK:ACME:N3OS:YUOJ:ZJFV:TWT3:LJZT
Debug mode (server): false
Debug mode (client): true
Fds: 18
Goroutines: 16
EventsListeners: 0
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker
Username: xxx
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support
```

uname -a  
```
Linux entrpc2 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

Lessons learned:
* Pin to `1.4.1` for the time being.
* **installing `latest` isn't safe**

**Comment by crosbymichael** [comment]
Is there a reason why your setup is using devicemapper and not aufs being on ubuntu?

**Comment by Ropes** [comment]
@crosbymichael because that was what the package setup by default. 

The switch from AUFS to devicemapper as default was before my time with Docker; [0.7](http://blog.docker.com/2013/11/docker-0-7-docker-now-runs-on-any-linux-distribution/#more-1596)

Has there been a reversal to AUFS being standard?  I haven't been able to find anything which seems to state there has been a flip back to AUFS..

**Comment by nicolasFlinois** [comment]
Same issue here !

**Comment by crosbymichael** [comment]
This looks to be fixed here #10860

Can you try the proposed solution and see if it fixes your case?

**Comment by ashahab-altiscale** [comment]
@jfrazelle They are running on native, so this is not an lxc-driver issue.

**Comment by jfrazelle** [comment]
whoops misread

**Comment by jfrazelle** [comment]
@Ropes can you try the solution in #10860

**Comment by Ropes** [comment]
Unfortunately we terminated all of the infrastructure which the original bug came from when we left AWS.  

For the hack day I booted a Ubuntu 14.04.2 VM and installed lxc-docker-1.4.1 then setup the same etcd container.  Upgrading to 1.5.0 did not cause the error we encountered before, so I'm going to close the issue(TTL 2 days) unless @nicolasFlinois can provide a means to reproduce what they encountered.

**Comment by nicolasFlinois** [comment]
I am gonna try to provide a scenario soon, or let you know if it is unreproducible from my side.

**Comment by dredknight** [comment]
Hello guys same issue happened on Centos 7.
The only difference is that there is no upgrade performed. Here it is how it goes.

Centos 7 + docker. test container was started and working.

One day I did a reboot of that VM and the container could not be started.
Here is the full error message:
[root@localhost ~]# docker start de10c8ba6692 
Error response from daemon: Cannot start container de10c8ba6692: Error getting container de10c8ba6692d23442d39158fa1c7ee3b26443ad85efb8f4c34b8bc95e3d305b from driver devicemapper: Error mounting '/dev/mapper/docker-253:1-17188168-de10c8ba6692d23442d39158fa1c7ee3b26443ad85efb8f4c34b8bc95e3d305b' on '/var/lib/docker/devicemapper/mnt/de10c8ba6692d23442d39158fa1c7ee3b26443ad85efb8f4c34b8bc95e3d305b': invalid argument
FATA[0000] Error: failed to start one or more containers

**Comment by fanne** [comment]
@dredknight the same issue to me,did you solve the problem?

**Comment by dredknight** [comment]
Yes I fixed it.
It is super dumb  thingy!

Check your timezone settings. After you fix them reboot and it all works !!

Cheers!

**Comment by thaJeztah** [comment]
I'm going to close this issue, because this is about quite old versions of docker and lack of activity here, but feel free to ping me here if you think this should be reopened
