### ISSUE TITLE
docker search for private image on docker hub

### ISSUE THREAD

**Issue by jmreicha** [docker/docker#10765]
I can't seem to find much about this issue, most of my results are returning info about privately hosted docker repositories.

Is there a way or would it be possible to add functionality to the `docker search` command for browsing images in a private repository hosted on docker hub?

**Comment by crosbymichael** [comment]
ping @dmp42

**Comment by dmp42** [comment]
That would be about the hub then, cc-ing @kencochrane @shin- 

@jmreicha I would also suggest that you open an issue on https://support.docker.com (since the hub support is there)

**Comment by jfrazelle** [comment]
for hub issues please email support@docker.com or open at forums.docker.com

**Comment by jmreicha** [comment]
@jfrazelle I sent an email to the above email address over a week ago and haven't received a response yet :(

**Comment by dmp42** [comment]
Closing then. Let me know how it goes with the support.

**Comment by dmp42** [comment]
Hi @jmreicha 

I checked with support and the last report they had from you is for a "Docker Hub Question" on Jul 11, 2014 19:10.

Though, there have been issues with DKIM depending on your mail provider, so, that might be the reason they did not receive your mail.

I would suggest you use the web form instead: https://support.docker.com 

Thanks!

**Comment by jmreicha** [comment]
@dmp42 thanks! I'll try the web form route.

I think something must be up with the emails because I sent a new email a few weeks ago.
