### ISSUE TITLE
Request: docker stats without any container should display all running containers

### ISSUE THREAD

**Issue by phemmer** [docker/docker#10772]
Similar to the behavior of the `top` utility, if no container is passed, it should show all containers. Since stopped containers are likely of no interest, I think it would be best to just show running containers.

**Comment by pskerrett** [comment]
It would be great, or at least allow a 'docker stats *'

Clunky workaround for now (I save it to my bash profile as alias docker-all-stats):

docker stats $(docker ps|grep -v "NAMES"|awk '{ print $NF }'|tr "\n" " ")

**Comment by phemmer** [comment]
I don't like `docker stats *` because 1) it requires you to quote the `*` or the shell will expand it, and 2) it implies that the command does globbing, when it doesn't.

**Comment by jfrazelle** [comment]
Yes I was about to say the same thing about shell and *

**Comment by phemmer** [comment]
Oh, and there's a much simpler version of that command as well:

    docker ps -q | xargs docker ps

**Comment by pskerrett** [comment]
True.. I guess 'docker stats -a' (or no flags at all) would be more appropriate.

**Comment by pskerrett** [comment]
That one doesn't work premmer, because stats is expecting all the containers to be on one line, and space delimited. Also, -q prints the container ID, but not the friendly name.

**Comment by phemmer** [comment]
Have you tried it?
To be accurate, `docker stats` expects the containers to be listed as arguments, not one line, or space delimited. This is what `xargs` does. `docker stats` also works with both IDs and names.

**Comment by pskerrett** [comment]
You are right about the arguments, but I originally came up with that so its possible to print out all containers using their names, instead of by ID. I have 12 or more containers on each host so trying to cross reference containerID with friendly name is a pain.

**Comment by mnuessler** [comment]
#dibs

**Comment by jmreicha** [comment]
+1

**Comment by Sirupsen** [comment]
Agree :+1:

**Comment by SamSaffron** [comment]
+1

**Comment by nhsiehgit** [comment]
@jfrazelle 

closed by https://github.com/docker/docker/issues/11763 ?

**Comment by SamSaffron** [comment]
no, that was just a dupe

**Comment by p1rox** [comment]
+1

**Comment by runcom** [comment]
+1 @mnuessler any update on this?

**Comment by mnuessler** [comment]
@runcom currently working on it..

**Comment by mnuessler** [comment]
Just want to give a short update on this: I got something working, but still need to provide a test. And I have two questions:
* Should `docker stats` display the ID or the name of the running containers? I assume the name would be more useful?
* If a container stops while stats is running, should the entry be removed from the displayed list?

**Comment by phemmer** [comment]
My own personal opinions:

I see value in both name and ID. Personally, I never use names. I use IDs everywhere. But I know others are the opposite. The only options I see to satisfy that would be to either show both, or a flag to control it.

Yes, container should be removed from the list.
The output you get while it is running should be the same output you get if you were to start it up again.

**Comment by p1rox** [comment]
I agree with @phemmer

**Comment by joost** [comment]
+1 (name and id / remove from list when stopped)

**Comment by thaJeztah** [comment]
@mnuessler do you have a status update?

If you're unsure about your implementation, it's no problem to create a PR with some "unpolished" things in it, because you will be able to discuss those issues during the design-review. Sometimes it helps to just create the PR so that the maintainers/reviewers have something to discuss.

And possibly, you'll learn some things or get inspiration in the process!

Just let us know, (also if you are unable to work on it) thanks in advance!

**Comment by DavidBadura** [comment]
+1

**Comment by terbooter** [comment]
+1

**Comment by runcom** [comment]
@mnuessler are you still working on this? If you need any help feel free to ping me here or on IRC

**Comment by dalanmiller** [comment]
:+1: to this, no other way currently to continuously display all running containers.

**Comment by SamSaffron** [comment]
please please please... 

```
docker stats `docker ps | awk '{print $NF}' | grep -v NAMES`
```

is gonna go in our bash rc file :)

**Comment by thaJeztah** [comment]
ping @mnuessler if you're still working on this.

@runcom perhaps you are interested in picking this up otherwise?

**Comment by runcom** [comment]
@thaJeztah I'm still working on this (though slowly for lack of time :()

**Comment by hbbio** [comment]
+1 for the feature (with `docker stats`, no `*`)

**Comment by shishir-a412ed** [comment]
@runcom any updates on this one ?

**Comment by iangkent** [comment]
+1 for docker stats that show container names in output instead of need to remember docker stats `docker ps | awk '{print $NF}' | grep -v NAMES`

**Comment by pydima** [comment]
#dibs

**Comment by thaJeztah** [comment]
PR for this is opened here; https://github.com/docker/docker/issues/16742

**Comment by tyurikov** [comment]
docker stats $(docker ps -aq) works ok for me.

**Comment by SamSaffron** [comment]
ok is a funny word ... you must love guids :)

**Comment by cboettig** [comment]
Well said @SamSaffron . me, i'd like to see container names when they have them.

**Comment by tyurikov** [comment]
@SamSaffron you caught me. :)
docker stats $(docker inspect -f "{{ .Name }}" $(docker ps -aq)) 
And I totally agree, it would be nice to have just "docker stats".

**Comment by sjevs** [comment]
You can also use simpler version:
```
docker stats `docker ps -q`
```

**Comment by thaJeztah** [comment]
@sjevs this feature was implemented in https://github.com/moby/moby/pull/16742 over two years ago, and is part of Docker 1.10 and up:

```
docker run -d --rm nginx:alpine
docker run -d --rm nginx:alpine

docker stats

CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
7f58203c7640        fervent_hopper      0.00%               1.836MiB / 1.952GiB   0.09%               578B / 0B           0B / 0B             2
fba8e312a88f        dreamy_pasteur      0.00%               1.922MiB / 1.952GiB   0.10%               758B / 0B           4.66MB / 0B         2

```
