### ISSUE TITLE
Proposal: App Container (appc) as a Runtime Option in the Docker Engine

### ISSUE THREAD

**Issue by philips** [docker/docker#10777]
The team behind [App Container](https://github.com/appc/spec) (appc) is seeking feedback on whether there are any modifications required to the spec to allow it to work natively in Docker. 

## Background

App Container (appc) is a specification for running applications in containers. We think App Container represents the next logical iteration in what a container image format, runtime engine, and discovery protocol should look like. Full details of the spec can be found in the [GitHub repo](github.com/appc/spec), in particular in the following two files:

- [SPEC](https://github.com/appc/spec/blob/master/SPEC.md) - contains the latest and complete version of the specification
- [README](https://github.com/appc/spec/blob/master/README.md) - contains background information on some of the motivations and principles of the project

appc is young but has already seen a variety of implementations well before it has reached 1.0 (stable) status. Before we call it 1.0, we are requesting feedback from the Docker community on what might need to be modified in the spec in order for it to be supported natively in Docker. If there are any issues with the spec preventing Docker from supporting it, we would like to discuss and address them now.

## Current Status

To test the compatibility of App Container and Docker, we have started to implement App Container Image and Image Discovery support into Docker itself. This work has already reached a functional state, which can be seen in the PR https://github.com/docker/docker/pull/10776
This should be considered somewhat experimental but we believe this prototype demonstrates that native support for appc within Docker is viable and worth pursuing.

## Future Work

There are a number of interesting features that could be brought into the Engine by exploring further integration with App Container. For example, a fully implemented version of the appc spec as part of the Docker Engine would "close out" these proposals with code:

- Labels/Tags of images: https://github.com/docker/docker/pull/9882 https://github.com/docker/docker/pull/8955
- Container Groups: https://github.com/docker/docker/issues/8781
- Container Identity: https://github.com/docker/docker/pull/9498 with [appc metadata service](https://github.com/appc/spec/blob/master/SPEC.md#app-container-metadata-service)
- Separation of transport and naming: https://github.com/docker/docker/issues/6805
- Consistent image IDs: https://github.com/docker/docker/issues/6959

Each of these topics (labels, container restarts, and container identity) is addressed and specified in the current v0.3.0 release of the spec. 

Another point of interest is that the appc spec goes beyond giving a container a static public identity but also attempts to give a cryptographic identity, similar to how a host has an SSH public key.

We look forward to discussing these ideas in depth, but want to gauge the level of interest before committing a lot of effort towards building these features into the Engine. As mentioned earlier, the ACI running PR https://github.com/docker/docker/pull/10776 is just the first step.

**Comment by philips** [comment]
As there are a lot of moving pieces to this proposal I have had several people suggest breaking it down into some smaller more detailed sections. One of the most obvious places to start is on the JSON schema for the image manifest.

Both the Docker and ACI format have a JSON object that describes the filesystem and how to run it. Things such as ENV variables, the executable to run and default resource constraints like max memory consumption are described in these JSON documents. 

Here are the major sections of the [ACI manifest](https://github.com/appc/spec/blob/master/SPEC.md#image-manifest) and [schema](https://github.com/appc/spec/blob/master/SPEC.md#image-manifest-schema), how it compares with the [Docker v1 manifest](https://github.com/docker/docker/blob/master/image/spec/v1.md) and how we might work together to make them both better:

### Manifest Sections

**image labels**

The first is the image identity via a set of labels including: os, arch and version. These are simple key/value pairs that the user specifies in configuration or on the command-line. For example an image might uniquely be identified by the string `example.com/app,arch=amd64,os=linux,version=0.1.0`.

The current Docker v1 image format does not have the concept of labels but a PR is open: https://github.com/docker/docker/pull/9882

I do think it is advantageous to give people the flexibility to let people run images based on these labels. For example today we only have the tag to run a docker image from:

`docker run app:v0.1.0`

But, for some folks there might be a more complex set of things they are looking for, for example:

`docker run app,channel=prod,passedQA=true`

**isolators**

The appc spec leaves the schema open to adding isolation options in the future. The spec tries to specify a number of both OS-specific and OS-agnostic resource constraints. For example `resource/cpu` is OS-agnostic and `linux/capabilities-retain-set`. 

The Docker v1 equivalent is a number of fields in the Config section such as Memory, MemorySwap, CPUShares, etc.

**note**: There are some upcoming changes to [the isolator schema](https://github.com/philips/spec/blob/isolators-as-objects/SPEC.md#isolators) to make it more flexible .

I think that being explicit where things are OS specific and OS-agnostic and letting users add their own isolators to the list are important properties. This idea would be useful in the next Docker image manifest particularly as more OSes are supported. Also, since the isolation options are in a list the runtime can warn the user that it cannot understand or does not have the ability to isolate the container in particular ways.

**ports**/**mount points**

Another thing we wanted was to give a user identifiable label to ports and volumes. For example if a service exposes something on 8081 it is difficult to know what that port is actually. So, in appc you can provide a name such as "health" or even "example.com/client".

The Docker v1 equivalent is ExposedPorts which has the protocol and port number but no user facing label on what that port might have on it. This holds true for the Volumes list in the manifest today too. You only know about paths, not an abstract name for that path like "logs" or "db".

**dependencies**

Background: The appc spec uses the DNS namespace for names: e.g. example.com/app. Even if `example.com/app` is mirrored on `aci-mirror.example.corp` the identity remains `example.com/app`. 

Similar to layers in the Docker v1 image format an ACI can have a list of "dependencies". An image can have an ordered dependency list such as `example.com/base`, `example.com/config2014`, etc.  The Docker v1 equivalent is "parent" which is a string ID of the parent image. This is an id like `abd4930acd...`.

The advantage of using a named image like appc does is  you don't assume that the dependent images come from the same "DNS name"/registry as the image you want to run. This feature may not be used a ton in practice but if you think about email it is sometimes handy that not everyone in the world uses an `@gmail.com` account.

### Working together

As the Docker v2 image format is still a work in progress (hey, so is appc) I think that we can work together to refine some of these ideas and add some of these features to the new manifest. The v1 format naturally evolved while Docker experienced very rapid growth which is a great problem to have. But, I think there is an opportunity to think through the v2 schema and take some of these concepts into mind and work together to create a shared schema.

**Comment by proppy** [comment]
If both project agree that convergence is desirable, I'd argue a better place to start would be the layout of rootfs (rather than the manifest).

I've been playing with a [hack](https://gist.github.com/proppy/20ca5dec630aafc1d35c) that shows that both format could be collocated in the same archive.

But it's still a waste that the content of the rootfs has to be duplicated into `layer.tar` (for docker) and an exploded `rootfs` sub-directory (for appc).

If both project converge on the same `rootfs` layout, it'd be trivial for container image authoring system to distribute portable images by shipping both manifests in the same archive, and if the discussion raised in this issue about converging the manifest evolve, the common parts could be consolidated in a common and extensible schema.

**Comment by duglin** [comment]
@philips what should we do with this? Were the smaller feature requests (PRs) opened up?  If not, and there's no plans to then perhaps we should close this?  If they were opened perhaps we can add links to them in here?

**Comment by cpuguy83** [comment]
Should this be closed in light of runC/OCF?
