### ISSUE TITLE
Docker stats --help usage does not indicate you can monitor multiple containers

### ISSUE THREAD

**Issue by phemmer** [docker/docker#10771]
Currently the `docker stats --help` output looks like this:

```
Usage: docker stats [OPTIONS] CONTAINER

Display a live stream of one or more containers' resource usage statistics

  --help=false       Print usage
```

When I look at this, it appears the command only supports monitoring a single container.
It should really be documented as:

```
Usage: docker stats [OPTIONS] CONTAINER [CONTAINER...]
```

**Comment by LK4D4** [comment]
@phemmer Yes, you're right, thanks!

**Comment by duglin** [comment]
actually, the way help works on that is kind of funky too - unless someone else is on it, I'll take it...

**Comment by duglin** [comment]
PR #10779 created

**Comment by pskerrett** [comment]
It should allow you to do a 'docker stats *' to show stats of running all containers (with friendly names, not docker IDs) . Kind of silly that is missing. 
A clunky work-around I've been using is:

docker stats $(docker ps|grep -v "NAMES"|awk '{ print $NF }'|tr "\\n" " ")

**Comment by duglin** [comment]
@pskerrett if you look at this issue: https://github.com/docker/docker/issues/10772  I think that's close to what you're looking for.
