### ISSUE TITLE
Unable to pull public image from Docker hub

### ISSUE THREAD

**Issue by knodir** [docker/docker#10789]
I have 3 public docker images in [Docker Hub](https://hub.docker.com/u/knodir/). One of them `knodir/click` does not show up when I do `sudo docker images search` on my local Ubuntu 14.04 machine, while two others show up. I can't pull that image either. When I do `sudo docker pull knodir/click` it gives error `FATA[0000] Tag lastest not found in repository knodir/click`. Is this a bug of Docker Hub?

**Comment by dmp42** [comment]
Hi.

Hub issues are handled by Docker's support: https://support.docker.com/

Now, if the image is private, did you do `docker login` before trying to pull?

**Comment by knodir** [comment]
It is a public image. I double checked after login; still get the same error. 

I reported this to the Docker support. Thanks for pointing to there!

**Comment by dmp42** [comment]
Mm, looking at https://registry.hub.docker.com/u/knodir/click/tags/manage/ it seems there is no tag there.
Did you push anything to that image?

**Comment by knodir** [comment]
Yes. First I did not add any tag since :latest is added by default (was so
in my other images). But after getting 'Tag latest was not found' error
message, I explicitly did `sudo docker push knodir/click:latest`. This did
not help either. I guess the tag I provide is being ignored during push.

**Comment by dmp42** [comment]
Ok, since no tags are showing on the hub website, I would assume a bug there. Let me know how it works with the support (or cc me over there).
