### ISSUE TITLE
debug should include timestamps

### ISSUE THREAD

**Issue by hickeng** [docker/docker#10791]
Follow up defect from https://github.com/docker/docker/issues/9700

I've never seen timestamps in docker's debug output and I run with debug almost all the time.
The format changed slightly with the shift to logrus but still no timestamps.

Sample output from today:
root@docker:/# docker-1.5.0-dev -v
Docker version 1.5.0-dev, build aa073ac
root@docker:/#
root@docker:/# docker-1.5.0-dev -d -D
INFO[0000] +job serveapi(unix:///var/run/docker.sock)
WARN[0000] graphdriver aufs selected. Warning: your graphdriver directory /var/lib/docker already contains data managed by other graphdrivers: devicemapper
DEBU[0000] Using graph driver aufs
DEBU[0000] Migrating existing containers
DEBU[0000] Creating images graph
DEBU[0000] Restored 45 elements
DEBU[0000] mkdir : no such file or directory
DEBU[0000] mkdir : no such file or directory
DEBU[0000] mkdir : no such file or directory
DEBU[0000] mkdir : no such file or directory
DEBU[0000] Creating repository list
DEBU[0000] Reloaded graph with 2 grants expiring at 2015-02-22 22:47:54.722420237 +0000 UTC
INFO[0000] +job init_networkdriver()
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
DEBU[0000] Registering POST, /auth
DEBU[0000] Registering POST, /build
DEBU[0000] Registering POST, /containers/{name:.*}/wait
DEBU[0000] Registering POST, /containers/{name:.*}/attach
DEBU[0000] Registering POST, /containers/{name:.*}/copy
DEBU[0000] Registering POST, /containers/{name:.*}/exec
DEBU[0000] Registering POST, /exec/{name:.*}/start
DEBU[0000] Registering POST, /commit
DEBU[0000] Registering POST, /images/create
DEBU[0000] Registering POST, /images/load
DEBU[0000] Registering POST, /images/{name:.*}/push
DEBU[0000] Registering POST, /images/{name:.*}/tag
DEBU[0000] Registering POST, /containers/{name:.*}/pause
DEBU[0000] Registering POST, /containers/{name:.*}/rename
DEBU[0000] Registering POST, /containers/{name:.*}/unpause
DEBU[0000] Registering POST, /containers/{name:.*}/restart
DEBU[0000] Registering POST, /exec/{name:.*}/resize
DEBU[0000] Registering POST, /containers/create
DEBU[0000] Registering POST, /containers/{name:.*}/kill
DEBU[0000] Registering POST, /containers/{name:.*}/start
DEBU[0000] Registering POST, /containers/{name:.*}/stop
DEBU[0000] Registering POST, /containers/{name:.*}/resize
DEBU[0000] Registering DELETE, /containers/{name:.*}
DEBU[0000] Registering DELETE, /images/{name:.*}

**Comment by jfrazelle** [comment]
If you log to a file not in a tty you get timestamps.
