### ISSUE TITLE
lxc-docker Docker pull problems: Certificate is valid for ...,  not index.docker.io

### ISSUE THREAD

**Issue by chmanie** [docker/docker#10802]
Since upgrading to docker 1.5.0 (lxc-docker) I am getting the following message when trying to pull an image:

```Get https://index.docker.io/v1/repositories/library/ubuntu/images: x509: certificate is valid for *.my-domain.com, my-domain.com, not index.docker.io```

Where my-domain.com is actually the domain for my server.

A ```curl https://index.docker.io/v1/repositories/library/ubuntu/images``` on the host system works just fine.

Did I do something wrong or is this a docker related issue?

**Comment by crosbymichael** [comment]
Do you use an internal proxy? 

ping @dmp42

**Comment by dmp42** [comment]
@chmanie docker daemon logs (preferably run in debug mode eg `docker -d -D`) would help here.
Indeed, maybe there is a proxy here?

**Comment by chmanie** [comment]
Thanks for joining in. These are the docker daemon logs:

```
DEBU[0007] Calling POST /images/create
INFO[0007] POST /v1.17/images/create?fromImage=ubuntu%3Alatest
INFO[0007] +job pull(ubuntu, latest)
INFO[0007] +job resolve_repository(ubuntu)
INFO[0007] -job resolve_repository(ubuntu) = OK (0)
DEBU[0007] pulling image from host "docker.io" with remote name "library/ubuntu"
DEBU[0007] pinging registry endpoint https://index.docker.io/v1/
DEBU[0007] attempting v1 ping for registry endpoint https://index.docker.io/v1/
INFO[0007] +job trust_update_base()
DEBU[0007] Fetched 1 base graphs at 2015-02-16 21:43:14.30456353 +0100 CET
INFO[0007] -job trust_update_base() = OK (0)
DEBU[0007] pulling v2 repository with local name "ubuntu"
DEBU[0007] pinging registry endpoint https://registry-1.docker.io/v2/
DEBU[0007] attempting v2 ping for registry endpoint https://registry-1.docker.io/v2/
DEBU[0007] hostDir: /etc/docker/certs.d/registry-1.docker.io
DEBU[0007] Reloaded graph with 2 grants expiring at 2015-02-22 22:47:54.722420237 +0000 UTC
ERRO[0007] Error from V2 registry: error getting registry endpoint: invalid registry endpoint https://registry-1.docker.io/v2/: Get https://registry-1.docker.io/v2/: x509: certificate is valid for *.xxx.de, xxx.de, not registry-1.docker.io. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry registry-1.docker.io` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/registry-1.docker.io/ca.crt
DEBU[0007] image does not exist on v2 registry, falling back to v1
DEBU[0007] pulling v1 repository with local name "ubuntu"
Pulling repository ubuntu
DEBU[0007] [registry] Calling GET https://index.docker.io/v1/repositories/library/ubuntu/images
DEBU[0007] https://index.docker.io/v1/repositories/library/ubuntu/images -- HEADERS: map[User-Agent:[docker/1.5.0 go/go1.4.1 git-commit/a8a31ef kernel/3.13.0-45-generic os/linux arch/amd64]]
DEBU[0007] hostDir: /etc/docker/certs.d/index.docker.io
Get https://index.docker.io/v1/repositories/library/ubuntu/images: x509: certificate is valid for *.xxx.de, xxx.de, not index.docker.io
INFO[0007] -job pull(ubuntu, latest) = ERR (1)
```

Client again errors this:
```
FATA[0000] Get https://index.docker.io/v1/repositories/library/ubuntu/images: x509: certificate is valid for *.xxx.de, xxx.de, not index.docker.io
```

Again, lxc-docker-1.4.1 is working just fine.

**Comment by dmp42** [comment]
What's in "*.xxx.de" ? Is this a domain under your control?

**Comment by chmanie** [comment]
Yes, I xxxed out the actual domain name. I am using a VM with subdomain of xxx.de.

**Comment by dmp42** [comment]
So, if this certificate is returned when your docker engine tries to reach `registry-1.docker.io`, it seems to indicate either (1) your docker daemon is using a proxy, or (2) your dns is locally modified to override registry-1.docker.io + index, or (3) something is wrong with the network bridge at the VM level.

It's a bit hard to tell without more details about your VM unfortunately.
Are you using boot2docker? Wha

**Comment by drieschel** [comment]
The network (bridge/router) setup of this vm should be okay.

**Comment by chmanie** [comment]
I'm on an ubuntu 14.04 system, not using any proxy or boot2docker. Just plain lxc-docker. It's very unlikely that the local DNS is modified in that particular way. I can't tell if the network bridge works the way it's supposed to be but I can ```curl https://registry-1.docker.io/v2/``` or ```curl https://registry-1.docker.io/v2/library/ubuntu/manifests/latest``` just fine, so it should be OK.

**Comment by dmp42** [comment]
@chmanie would you join on irc (#docker-distribution) so we can look into this/discuss it without github comments latency?
Ping me there (dmp42) or Derek (dmcg).

**Comment by jfrazelle** [comment]
@dmp42 did you all work this out?

**Comment by dmp42** [comment]
@jfrazelle #10863 is the diagnostic, while this one here describes some possible symptoms.

@chmanie I'm going to close this issue as a duplicate then, and let the other one to track progress. Let me know if you feel this should rather stay open.

**Comment by jfrazelle** [comment]
perfect thanks!
