### ISSUE TITLE
docker cp should be able write tar to stdout

### ISSUE THREAD

**Issue by ajf** [docker/docker#10805]
It looks like the API for Docker cp (`/containers/:id/copy`) natively writes tar format, but I don't see the ability to get the raw tar stream with the docker binary.  It would be great if `docker cp` (or a new command) would stream the tar format directly to stdout.  Similar to what `tar -cf - dir` would do.

We use docker to produce build artifacts that get uploaded to a continuous deployment system and it'd be great to just be able to do this `docker cp container:/output | curl -XPUT -d @- URL`

I see docker export, but that looks like it can only export the entire container.

**Comment by duglin** [comment]
@tiborvass @vieux thoughts? Seems fairly straight-forward.
Could be either `[HOSTPATH]` becomes optional or make it explicit via `-` like tar.

**Comment by cpuguy83** [comment]
+1 for - really easy to implement.

**Comment by duglin** [comment]
ok - one +1 is enough for me....  :-)

**Comment by duglin** [comment]
PR: https://github.com/docker/docker/pull/11177
