### ISSUE TITLE
Wrong MaximumRetryCount info when docker run with --restart=always .

### ISSUE THREAD

**Issue by sunyuan3** [docker/docker#10809]
docker run --restart=always ${image}:latest  /bin/bash -c "exit 9"
The container will restart automatically.

Wait 30 seconds.

docker inspect ${container_id} | grep MaximumRetryCount

log:
"MaximumRetryCount": 0,

MaximumRetryCount should be unlimited, not 0.

BTW, 
docker run --restart=no  ubuntu:latest  /bin/bash -c "exit 9"
docker inspect ${container_id} | grep MaximumRetryCount
log: "MaximumRetryCount": 0,
For docker with --restart=no, MaximumRetryCount should be 0.

**Comment by coolljt0725** [comment]
MaximumRetryCount is only work when the restart policy is `on-failure`, so if want check the restart policy of a container, you should check the RestartPolicy.Name, but not the RestartPolicy.MaximumRetryCount

**Comment by cpuguy83** [comment]
As @coolljt0725 said, it only applies to the `on-failure` policy at this time.
