### ISSUE TITLE
Cant pull images: Untar exit status 1 open /usr/share/man/man3/Archive::Extract.3pm.gz: invalid argument

### ISSUE THREAD

**Issue by brpaz** [docker/docker#10803]
I cant pull any image with docker.  I tried 3 different images and allways got the following error:

```
FATA[0087] Error pulling image (14.04) from ubuntu, Untar exit status 1 open /usr/share/man/man3/Archive::Extract.3pm.gz: invalid argument 
```

I tried running docker on debug mode, but it doesnt say anything usefull?
I am using Docker version 1.4.1, build 5bc2ff8 on LInux Mint 17.

Any tips?

**Comment by thaJeztah** [comment]
Would you be able to add the *exact* command you ran when running into this problem? Also the output of `docker info`, `docker --version` and `uname -a`.

Finally, to check if everything is in place for docker to run correctly, you can run this script; https://github.com/docker/docker/blob/master/contrib/check-config.sh

**Comment by brpaz** [comment]
Found the problem. I had symlinked ```/var/lib/docker``` to an NTFS partition. removed the symlink and it works.

**Comment by thaJeztah** [comment]
Glad you resolved it and thanks as well for the follow up!
