### ISSUE TITLE
Dockerfile case sensitive!

### ISSUE THREAD

**Issue by mohislm** [docker/docker#10807]
I noticed if I use lowercase filename (dockerfile), it the build command doesn't work. Some folks (like me) like to keep all file names lowercase (e.g. vagrantfile, gruntfile etc.) They Vagrant and Grunt they all work, but docker doesn't. Should we expect a release where the lowercased "dockerfile" works as well as the standard "Dockerfile"?

**Comment by duglin** [comment]
Try: `docker build -f dockerfile`

**Comment by mohislm** [comment]
That works for time being. But it would make more sense if you can add
support for the lowercased file.

On Sat, Feb 14, 2015 at 8:51 PM, Doug Davis <notifications@github.com>
wrote:

> Try: docker build -f dockerfile
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/10807#issuecomment-74400391>.
>



-- 
The most intelligent person is the one who remembers death most, and
prepares for it. (Prophet Muhammad PBUH)

**Comment by duglin** [comment]
guess we could do something similar to 'make' and look for: Dockerfile and then dockerfile (in that order).
Thoughts? @tiborvass @tianon @jfrazelle

**Comment by mohislm** [comment]
That works. I'd also suggest to see how the other guys did it (vagrant, Grunt, Gulp, Broccoli).

**Comment by thaJeztah** [comment]
So, if I understand correctly, both `Dockerfile` and `dockerfile` would be accepted, but **not** `DockerFile`, `DOckerfilE` etc, right?

*If* this is implemented, I think Docker should bail out if **both** `Dockerfile` *and* `dockerfile` exist in the directory, giving the user instructions to remove one of them.

**Comment by mohislm** [comment]
That's correct @thaJeztah.

**Comment by jfrazelle** [comment]
so I was playing around with Makefile to see, this is what I found:
1. if the file is named `makefile` it works
2. if both `makefile` and `Makefile` exist it uses `Makefile`
3. if the only file is `makeFile` it doesn't work


We should do this.

**Comment by jfrazelle** [comment]
but maybe @thaJeztah suggestion to remove one if the case is #2

**Comment by cpuguy83** [comment]
SGTM

**Comment by duglin** [comment]
not sure what people are agreeing to.  But following make's example, it does not error if both Makefile and makefile are present. For me it appears to use makefile.  From the man page:
```
If no -f option is  present, make  will  look for the makefiles GNUmakefile, makefile, 
and Makefile, in that order.
```
However, given our default is Dockerfile, not dockerfile, I would recommend: Dockerfile, dockerfile, in that order.
Thoughts?

**Comment by duglin** [comment]
I'll take this one if we decide to do it.

**Comment by cpuguy83** [comment]
@duglin, Sorry, I was `SGTM`ing @jfrazelle's original comment about following exactly make, as you have also suggested.

**Comment by jfrazelle** [comment]
@duglin yes I like that :D

**Comment by thaJeztah** [comment]
I'm not really sure there are "valid" cases where people *want* to have a file in both upper and lowercase, and it could be helpful if the user is (at least) notified that there *are* two files present. Might save some support questions as well ("docker doesn't pick up modifications in my Dockerfile").

I'm +1 on the order of finding the right file.

**Comment by cpuguy83** [comment]
@thaJeztah But yet we have case-sensitive filesystems :)

**Comment by thaJeztah** [comment]
@cpuguy83 psssht not so loud, the Windows guys may hear you! :smiley:

**Comment by ahmetalpbalkan** [comment]
@thaJeztah we're everywhere. haha. Most likely windows would accept `dockerfile` without `-f`. :joy:

**Comment by thaJeztah** [comment]
Yup, OS X is case-insensitive by default (and it's generally discouraged to run it case-sensitive). Possibly edge-case, but how does (e.g.) a SAMBA share handle situations where two files with different casing are present? Anything to keep in mind wrt Boot2Docker / VBox shares?

**Comment by tianon** [comment]
But at least with HFS+, it's properly case-preserving :wink:

**Comment by mohislm** [comment]
I see people are getting little off-tracked here from the original question. And the issue still remains unresolved. @thaJeztah, @tianon

FYI: OS X doesn't take "dockerfile" without -f @ahmetalpbalkan

Regardless of the file system, since docker started with "Dockerfile", let's keep it as default. So, the proposed order would be: (1) Dockerfile, (2) dockerfile. It will be unusual if someone has both files. But to support that, the "Dockerfile" will come to play instead of "dockerfile". There is no need for showing any message. Let's not sweat on that for now, and get this resolved faster.

**Comment by duglin** [comment]
yes that is my plan. Just working on dealing with the REST API side of it right now since that has some interesting quirks.

**Comment by duglin** [comment]
PR: https://github.com/docker/docker/pull/10858
