### ISSUE TITLE
Docker attach not responding

### ISSUE THREAD

**Issue by alihalabyah** [docker/docker#10814]
I have the following docker version: `Docker version 1.5.0-dev, build c33ac60`
Whenever i try to attach to a running container using this command `sudo docker attach 432b858cd529` nothing happens only waiting maybe it's stuck or something.

**Comment by alihalabyah** [comment]
I think this issue is happening on Ubuntu only, I tried it on Mac and things are alright!

**Comment by coolljt0725** [comment]
Have you start the container with `-i` ? If not, docker attach don't work,  you can run `docker inspect -f {{.Config.OpenStdin}} 432b858cd529`  to see if your container `432b858cd529` have start with `-i` or not

**Comment by alihalabyah** [comment]
@coolljt0725 Same thing with `-i`, any other suggestions?

**Comment by cpuguy83** [comment]
@alihalabyah What is running inside the container?
Attach attaches you to the stdout/stdin/stderr streams of the running process in the container.

**Comment by cpuguy83** [comment]
Closing due to lack of info.

If you can provide more details please update this issue.
Thanks!

**Comment by daixtrose** [comment]
Maybe Docker is simply not showing the prompt like in https://stackoverflow.com/questions/35573698/why-does-docker-attach-hang ?
