### ISSUE TITLE
Docker --rm does not work with tty mode 

### ISSUE THREAD

**Issue by shubhamrajvanshi** [docker/docker#10822]
When I try to run any container using --rm=true with --tty=true then even after stopping the container, the container still persists in boot2docker (not sure if it does so on linux machine too) when it should be gone as the container has stopped.

Image used: shubhamrajvanshi/mongo
command: docker run --rm=true -tty=true --name db mongo mongod

![image](https://cloud.githubusercontent.com/assets/7224484/6210608/2a6333fe-b586-11e4-9e8c-78722bf4995c.png)

Note: Image mongo is similar to shubhamrajvanshi/mongo just changed its name using tag command

**Comment by shubhamrajvanshi** [comment]
When I try to run any container using --rm=true with --tty=true then even after stopping the container, the container still persists in boot2docker (not sure if it does so on linux machine too) when it should be gone as the container has stopped.

Image used: shubhamrajvanshi/mongo
command: docker run --rm=true -tty=true --name db mongo mongod

![image](https://cloud.githubusercontent.com/assets/7224484/6210533/83d54270-b585-11e4-8c7f-fed18291b468.png)

Note: Image mongo is similar to shubhamrajvanshi/mongo just changed its name using tag command

**Comment by thaJeztah** [comment]
I think there are a number of issues with `--rm` not working consistently, and enhancement requests. Perhaps they should be looked at to see if there's an overlap;

A quick search; 
https://github.com/docker/docker/issues/6757, https://github.com/docker/docker/issues/7245, https://github.com/docker/docker/issues/10545, https://github.com/docker/docker/pull/10688 (pull request)

**Comment by cpuguy83** [comment]
I cannot repro on 1.5

**Comment by estesp** [comment]
There may also be a misunderstanding here of how `docker run --rm` operates; which may lead to some clarification in the docs if necessary.

When you pass `--rm` to the run command, it will add an API call to the daemon after the calls to create/start/attach.  This is why `-d` is incompatible with `--rm`--your docker run command must be active at the time of container exit for the deletion API to be called by your client.  In your case, I'm not sure how that is going to work unless you are running your mongod in the foreground, and when you force it to exit (Ctrl-C?) then the docker run command will handle the exit and call the `DELETE` container API.  If you run `docker stop`, then you have broken how `docker run --rm` works.

As an aside I spent a few hours late last week looking at the moving of `--rm` processing to the Docker daemon to get around these issues (as @thaJeztah noted, there are a lot of various issues around `--rm`), and let's just say it is a hard problem.  There will be no easy way to migrate the execution of remove-on-exit to the server side unless something like a mark-for-removal and garbage collector thread was added (IMHO).  I could be proved wrong, but at this point we are stuck with `--rm` heavily depending on your docker run command exiting properly and completely to get `--rm` to work properly.

**Comment by thaJeztah** [comment]
@estesp is there anything actionable here? Is this something that should be solved, or is it something that should be *documented*?

**Comment by estesp** [comment]
In this case, @cpuguy83 is actually correct that the handling of `CmdRun` in 1.5.0 and current master are correctly calling `DELETE` when docker stop is called on a container currently in an interactive `docker run`.  So, I believe this specific issue is no longer valid on the current released version of Docker.

@shubhamrajvanshi can you try your steps on the most recent Docker and let us know?

**Comment by shubhamrajvanshi** [comment]
Sure, I'll try this on weekend.

Thanks
Shubham Rajvanshi
669-300-8346

**Comment by estesp** [comment]
Have you had a chance to try this with either 1.5.0 release or the 1.6.0 rc builds?  I'm fairly sure currently `--rm` is working fairly well, with some known issues around error conditions.  Would be good to understand if there are still issues.  Thanks!

**Comment by cpuguy83** [comment]
Closing since there's been no response and we can't report.

**Comment by shubhamrajvanshi** [comment]
You can close it will test and get back to you. Sorry have been too busy with my School
