### ISSUE TITLE
FATA[0000] inappropriate ioctl for device  on Ubuntu 14.04.1

### ISSUE THREAD

**Issue by zopyx** [docker/docker#10826]
A new Ubuntu box with 

cat /etc/issue
Ubuntu 14.04.1 LTS \n \l

refuses to start Docker 1.5.0.

Running the daemon manually gives me this:

<pre>
 /usr/bin/docker -D -d
INFO[0000] +job serveapi(unix:///var/run/docker.sock)   
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
DEBU[0000] Registering GET, /events                     
DEBU[0000] Registering GET, /version                    
DEBU[0000] Registering GET, /images/json                
DEBU[0000] Registering GET, /images/get                 
DEBU[0000] Registering GET, /containers/{name:.*}/export 
DEBU[0000] Registering GET, /containers/{name:.*}/logs  
DEBU[0000] Registering GET, /containers/{name:.*}/stats 
DEBU[0000] Registering GET, /images/viz                 
DEBU[0000] Registering GET, /images/search              
DEBU[0000] Registering GET, /containers/ps              
DEBU[0000] Registering GET, /containers/json            
DEBU[0000] Registering GET, /containers/{name:.*}/json  
DEBU[0000] Registering GET, /containers/{name:.*}/attach/ws 
DEBU[0000] Registering GET, /_ping                      
DEBU[0000] Registering GET, /info                       
DEBU[0000] Registering GET, /images/{name:.*}/get       
DEBU[0000] Registering GET, /images/{name:.*}/history   
DEBU[0000] Registering GET, /images/{name:.*}/json      
DEBU[0000] Registering GET, /exec/{id:.*}/json          
DEBU[0000] Registering GET, /containers/{name:.*}/changes 
DEBU[0000] Registering GET, /containers/{name:.*}/top   
DEBU[0000] Registering POST, /commit                    
DEBU[0000] Registering POST, /images/load               
DEBU[0000] Registering POST, /images/{name:.*}/push     
DEBU[0000] Registering POST, /containers/{name:.*}/pause 
DEBU[0000] Registering POST, /containers/{name:.*}/restart 
DEBU[0000] Registering POST, /containers/{name:.*}/stop 
DEBU[0000] Registering POST, /build                     
DEBU[0000] Registering POST, /images/create             
DEBU[0000] Registering POST, /images/{name:.*}/tag      
DEBU[0000] Registering POST, /containers/create         
DEBU[0000] Registering POST, /containers/{name:.*}/resize 
DEBU[0000] Registering POST, /containers/{name:.*}/exec 
DEBU[0000] Registering POST, /exec/{name:.*}/start      
DEBU[0000] Registering POST, /containers/{name:.*}/unpause 
DEBU[0000] Registering POST, /containers/{name:.*}/wait 
DEBU[0000] Registering POST, /containers/{name:.*}/attach 
DEBU[0000] Registering POST, /auth                      
DEBU[0000] Registering POST, /containers/{name:.*}/kill 
DEBU[0000] Registering POST, /containers/{name:.*}/start 
DEBU[0000] Registering POST, /containers/{name:.*}/copy 
DEBU[0000] Registering POST, /exec/{name:.*}/resize     
DEBU[0000] Registering POST, /containers/{name:.*}/rename 
DEBU[0000] Registering DELETE, /containers/{name:.*}    
DEBU[0000] Registering DELETE, /images/{name:.*}        
DEBU[0000] Registering OPTIONS,                         
DEBU[0000] docker group found. gid: 999                 
DEBU[0000] libdevmapper(3): ioctl/libdm-iface.c:363 (-1) /dev/mapper/control: open failed: Operation not permitted 
DEBU[0000] libdevmapper(6): ioctl/libdm-iface.c:405 (0) <backtrace> 
DEBU[0000] libdevmapper(3): ioctl/libdm-iface.c:415 (-1) Failure to communicate with kernel device-mapper driver. 
DEBU[0000] libdevmapper(3): ioctl/libdm-iface.c:417 (-1) Check that device-mapper is available in the kernel. 
DEBU[0000] libdevmapper(6): ioctl/libdm-iface.c:1849 (0) <backtrace> 
DEBU[0000] libdevmapper(6): ioctl/libdm-iface.c:506 (0) <backtrace> 
DEBU[0000] libdevmapper(6): ioctl/libdm-iface.c:531 (0) <backtrace> 
DEBU[0000] libdevmapper(6): libdm-common.c:257 (0) <backtrace> 
DEBU[0000] Using graph driver vfs                       
DEBU[0000] Creating images graph                        
DEBU[0000] Restored 0 elements                          
DEBU[0000] Creating repository list                     
INFO[0000] +job init_networkdriver()                    
DEBU[0000] Creating bridge docker0 with network 172.17.42.1/16 
DEBU[0000] setting bridge mac address = true            
inappropriate ioctl for device
INFO[0000] -job init_networkdriver() = ERR (1)          
FATA[0000] inappropriate ioctl for device  
</pre>

<pre>
Docker Version:
docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
FATA[0000] Cannot connect to the Docker daemon. Is 'docker -d' running on this host? 
</pre>

<pre>
Kernel
 3.13.0-042stab104.1 #1 SMP Thu Jan 29 12:58:41 MSK 2015 x86_64 x86_64 x86_64 GNU/Linux
</pre>

cgroups is empty

```bash
cat /proc/cgroups 
#subsys_name    hierarchy       num_cgroups     enabled
```

So?

**Comment by cpuguy83** [comment]
Running as root?  Running docker in docker?

**Comment by zopyx** [comment]
Running as root inside a brand new virtual machine.

2015-02-16 18:40 GMT+01:00 Brian Goff <notifications@github.com>:

**Comment by estesp** [comment]
Looks like you are running an OpenVZ kernel and not the Ubuntu kernel?  Device mapper and/or AUFS don't appear to be built in or available in your kernel distribution.  If you try the default Ubuntu kernel for 14.04.1 you should find the Docker daemon running properly out of the box.

**Comment by zopyx** [comment]
This is a standard Ubuntu installation provided as default from our hoster

 cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"
NAME="Ubuntu"
VERSION="14.04.1 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.1 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 14.04.1 LTS
Release: 14.04
Codename: trusty

cat /proc/version
Linux version 3.13.0-042stab104.1 (root@kbuild-rh6-x64) (gcc version 4.4.6
20120305 (Red Hat 4.4.6-4) (GCC) ) #1 SMP Thu Jan 29 12:58:41 MSK 2015

2015-02-16 19:43 GMT+01:00 Phil Estes <notifications@github.com>:

**Comment by estesp** [comment]
Your hosting provider is replacing the Ubuntu kernel with what appears to be an OpenVZ kernel--here is the `/proc/version` from Ubuntu 14.04.1 official update stream:
```
Linux version 3.13.0-45-generic (buildd@phianna) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015
```

Given it's hard to know if that kernel has the right features for using Docker, maybe you can run this script and paste the output here?
https://github.com/docker/docker/blob/master/contrib/check-config.sh

**Comment by zopyx** [comment]
sh check-config.sh
sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
warning: /proc/config.gz does not exist, searching other paths for kernel
config...
error: cannot find kernel config
  try running this script again, specifying the kernel config:
    CONFIG=/path/to/kernel/.config check-config.sh or check-config.sh
/path/to/kernel/.config

Different Ubuntu box from the same hoster returns this:

 sh check-config.sh
warning: /proc/config.gz does not exist, searching other paths for kernel
config...
info: reading kernel config from /boot/config-3.13.0-32-generic ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_MACVLAN: enabled
- CONFIG_VETH: enabled
- CONFIG_BRIDGE: enabled
- CONFIG_NF_NAT_IPV4: enabled
- CONFIG_IP_NF_FILTER: enabled
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled
- CONFIG_NF_NAT: enabled
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_MEMCG_SWAP: enabled
- CONFIG_RESOURCE_COUNTERS: enabled
- CONFIG_CGROUP_PERF: enabled
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: enabled
    - CONFIG_EXT4_FS_POSIX_ACL: enabled
    - CONFIG_EXT4_FS_SECURITY: enabled
  - "btrfs":
    - CONFIG_BTRFS_FS: enabled
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: enabled
    - CONFIG_DM_THIN_PROVISIONING: enabled
    - CONFIG_EXT4_FS: enabled
    - CONFIG_EXT4_FS_POSIX_ACL: enabled
    - CONFIG_EXT4_FS_SECURITY: enabled
  - "overlay":
    - CONFIG_OVERLAY_FS: missing

*sigh*

2015-02-16 20:11 GMT+01:00 Phil Estes <notifications@github.com>:

**Comment by cpuguy83** [comment]
Yes, I agree.  This looks like an OpenVZ kernel: http://ahmed.amayem.com/checking-if-your-centos-system-is-original-or-a-virtualization-version-openvz/

**Comment by zopyx** [comment]
Yet another point for my case against Docker story. Thanks. Every day with
Docker shows me that it is broken technology.

2015-02-16 20:16 GMT+01:00 Brian Goff <notifications@github.com>:

**Comment by estesp** [comment]
I'm confused?  Your hosting provider seems to have provisioned a system that appears broken, especially when you compared it to another system that had a proper kernel config/setup.  Why is Docker at fault here?

**Comment by cpuguy83** [comment]
Closing this since it doesn't appear to be a Docker issue. Docker requires official kernels and OpenVZ changes significant pieces of the kernel that makes it incompatible with Docker.

If you have trouble getting this going on a normal kernel, please let us know!

**Comment by zopyx** [comment]
- bad error reporting
- highly depending on distro and kernels - not a single CentOS installation
from 6.5, 6.6 to 7.0 is reliably working

Docker stinks like smelly cheese. Rocket will smash you against the wall.

2015-02-16 20:19 GMT+01:00 Phil Estes <notifications@github.com>:
