### ISSUE TITLE
ENTRYPOINT shell command substitution

### ISSUE THREAD

**Issue by jduckles** [docker/docker#10827]
Using 

    Docker version 1.4.1, build 5bc2ff8

This fails ```ENTRYPOINT ["echo","$(hostname)"] ```
whereas this works: ```ENTRYPOINT ["echo", "`hostname`"]```

Shouldn't there be support for the more modern `$()` syntax?

**Comment by duglin** [comment]
This works in the latest version of Docker:
```
FROM ubuntu
ENTRYPOINT echo $(hostname)

$ docker build tmp
Sending build context to Docker daemon 97.28 kB
Sending build context to Docker daemon 
Step 0 : FROM ubuntu
 ---> b39b81afc8ca
Step 1 : RUN echo $(hostname)
 ---> Running in 721c916056ac
2338b11efbe1
 ---> abaa8fa1bfd6
Removing intermediate container 721c916056ac
Successfully built abaa8fa1bfd6
```
And then:
```
$ docker run test
87a90c317708
```
Please upgrade and if you still see an issue reopen it.
