### ISSUE TITLE
Command descriptions truncated in the documentation

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#10828]
This problem occurs on this page and possibly others:

(https://docs.docker.com/reference/commandline/cli/#run)

![image](https://cloud.githubusercontent.com/assets/1347209/6215401/2336bf86-b5b5-11e4-9f85-38c75eb41918.png)

**Comment by duglin** [comment]
On master things should not exceed 80 chars - can you try there?

**Comment by duglin** [comment]
hmm I take that back...

**Comment by duglin** [comment]
I'll try to fix this

**Comment by jfrazelle** [comment]
Can you not scroll right / left?

**Comment by duglin** [comment]
even if @moxiegirl can scroll, it needs to match the newer 80 char output.
There has got to be a better way to get these into the docs than manually copy-n-paste.
