### ISSUE TITLE
Proposal: Disable auto-genarated container names to ease cleanup

### ISSUE THREAD

**Issue by mikehaertl** [docker/docker#10839]
After working with docker for a while now, I constantly find myself cleaning up old containers. If you have 2 or 3 docker based projects, each with several containers this can become a big annoyance. You have to wade through 100s of containers and very carefully find those, which are no longer required.

There was a discussion about a clean command in #928 - but with no outcome. I think, one of the difficulties was to identify no longer needed containers. IMO the main difficulty is really, that each and every container has a name. If "throwaway" containers (`fig run ...`, `docker run ...`) wouldn't get a name by default, it would be very clear, which containers can be deleted safely.

**Comment by duglin** [comment]
What is your definition of a "throwaway" container?

**Comment by mikehaertl** [comment]
Those that are created when you run `docker run ...` or `docker-compose run ...` and forget to use the `--rm` option. For example, you're unsure about the exact contents of your freshly built image, so you do `docker run my-image ls -l /some/dir`.That's what I did pretty much when I started with docker and this created many orphaned containers.  It was always very hard to identify those abandoned containers. 

I'd even say, `--rm` should have been the default, but it's too late to change that now. Actually the real question to me is: What exactly is the advantage of auto-creating names? For me this only creates problems and is one of the reasons why docker felt so messy to me at the beginning. A new container here, many many new volumes there - and suddenly several GB of my harddrive are gone for no reason.

**Comment by duglin** [comment]
@mikehaertl thanks for the additional info.

@tiborvass the other day you were asking for an example of a case where there might be a config file option w/o a corresponding cmd line flag. I think the solution here, if we want to do anything, is a config file flag that means "if the user didn't specify --name or --rm on 'docker run' then add --rm=true automatically".  This will give the net effect of always removing the container _unless_ they gave it a name, or specifically asked for it to be kept around via --rm=false.  I'm not, yet, saying we should add this feature, but it did seem like an example of what you were looking for w.r.t. the config file discussion.

@mikehaertl would this type of feature solve your issue?

**Comment by mikehaertl** [comment]
@duglin Sounds good.

**Comment by tiborvass** [comment]
I doubt we could ever make `--rm` default to true. The rationale is that we don't want to lose data inadvertently, by default. It would have to be very explicit.

One long term solution would be CLI plugins. Short term you can wrap the docker CLI in a script that checks if run has --name passed to it, and insert --rm accordingly.

I'm not sure we would want to make the config file turing complete, and I'm not sure we would want to introduce a new variable specifically for this. That's my 2¢.

**Comment by mikehaertl** [comment]
So maybe we're back to the initial request then. What exactly is the purpose of those auto-generated names? Would it really hurt to ditch them?

**Comment by duglin** [comment]
@mikehaertl see https://github.com/docker/docker/issues/928#issuecomment-98232494  I don't think there's universal agreement as to how to identify transient/throw-away containers.

It seems to me the only way to really solve this is to change Docker's defaults - from "save everything" to "delete it unless asked not to".  And that's a pretty big change.

I'm still partial to the idea I mentioned in https://github.com/docker/docker/issues/10839#issuecomment-92340686 because it gives the user the control they may want w/o changing the default behavior of Docker.

ping @shykes @crosbymichael   any thoughts on this?  The proliferation of old containers (and images) could be an issue for people if they're not paying attention.

**Comment by cpuguy83** [comment]
Or you could use labels to differentiate.

**Comment by thaJeztah** [comment]
I agree with @cpuguy83 here. I think labels are a good feature that can be used to differentiate and puts the user in full control over what he/she considers a throwaway container.

I'm -1 on this proposal because I think the "name" should not get a double meaning and we already have features to achieve this (e.g. Labels)

**Comment by crosbymichael** [comment]
We cannot remove names from containers.  It will break so many things and docker will just not work without container names for most features.  

You need to use something like labels to filter on for deletion.

**Comment by abronan** [comment]
I also think using labels for filtering is a much better idea. At least this is what we want to support in Swarm, for example deleting all containers on one node or using a specified label (see docker/swarm#288). Although we were waiting for custom `ps` outputs to print those label using `ps` and have a consistent UI.

**Comment by thaJeztah** [comment]
@abronan looks like you're in luck then; https://github.com/docker/docker/pull/14699

**Comment by MHBauer** [comment]
This sounds pretty settled on not removing the names or changing the current behavior of using auto generated names.

**Comment by LK4D4** [comment]
@MHBauer You're right, it'll be more harm.
