### ISSUE TITLE
Interactive Shell. tty: Not a tty. Unable to use screen or tmux 

### ISSUE THREAD

**Issue by dbabits** [docker/docker#10842]
This was discussed extensively in issue #728, which was closed for some reason.
However, the issue is not resolved as of Docker v 1.3.3 (tty reports "not a tty")
Any idea?

**Comment by cpuguy83** [comment]
@dbabits Can you come onto IRC (freenode #docker), or maybe even better the docker-user mailing list?

People use tmux with Docker all the time so I'm sure there's probably a config issue at play here.

**Comment by dbabits** [comment]
@cpuguy83 , please see fresh issue #8755

**Comment by cpuguy83** [comment]
So this is with `docker exec`?
