### ISSUE TITLE
readme.md in bitbucket repo not showing in hub.docker

### ISSUE THREAD

**Issue by skwokmag** [docker/docker#10840]
Hi,

I have linked up my bitbucket repo with my hub.docker repo (magnetmessaging/mmx-standalone-dist-docker) for autobuild. The autobuild works great; however, the readme (/readme.md) is not showing. I suppose it should be shown automatically in the "Information" tab. Would you please let me know why?
Thank you.

skwok

**Comment by jfrazelle** [comment]
Hi,
The Github issues are for problems with docker itself, not hub. For hub
problems please email support@docker.com

**Comment by skwokmag** [comment]
Thanks.
