### ISSUE TITLE
Kernel upgrade on Ubuntu 14.04 + aufs drops back to devicemapper

### ISSUE THREAD

**Issue by mbentley** [docker/docker#10859]
If you utilize the `curl`able install script [install.sh](https://github.com/mbentley/docker/blob/master/project/install.sh) on Ubuntu 14.04 to install docker, it adds the `linux-image-extra-$(uname -r)` package for aufs support.  If a newer kernel package is available, installed, and then the system is rebooted, docker will fall back to devicemapper because we install `linux-image-extra-$(uname -r)` and not `linux-image-extra-virtual`.

Substituting `linux-image-extra-virtual` for `linux-image-extra-$(uname -r)` works fine but as a bit of a side effect, installing `linux-image-extra-virtual` will also cause a system to update to the latest available kernel package.  I am not sure if that would be a desirable result at all as it leaves the system in a state of the current kernel still not having aufs support until the system is rebooted.  Updating [line 128 of install.sh](https://github.com/mbentley/docker/blob/master/project/install.sh#L128) to `kern_extras="linux-image-extra-virtual linux-image-extra-$(uname -r)"` installs the `linux-image-extra-$(uname -r)` package for the current kernel **and** also installs it through the virtual package for the newer kernel that will be active after a reboot.

I did not include a PR to change this behavior as I wanted to fully understand what should be the expected result.  As it stands now, the current behavior of dropping from aufs to devicemapper upon kernel upgrade doesn't feel proper since you essentially lose anything that was running on the system previously.  Being able to keep the `linux-image-extra-` package up to update with the kernel via `apt-get dist-upgrade` seems like it would be the expected behavior.

**Comment by thaJeztah** [comment]
If you have the changes ready, creating a PR might work, sometimes people here find it easier to see actual code and discuss that.

Just speaking for myself, though 😊
