### ISSUE TITLE
Documentation seems to provide an incorrect example on adding hosts file entry for docker host

### ISSUE THREAD

**Issue by phillbarber** [docker/docker#10855]
An example is provided on this page

https://docs.docker.com/reference/commandline/cli/#adding-entries-to-a-container-hosts-file

...detailing how to add an entry in the docker container's hosts file to the docker host.

As far as I can see this actually injects the ip of the default gateway on the parent host which doesn't help.

Perhaps a better example would be to inject the ip of the docker0 interface as follows:

 $ docker run  --add-host=docker:`ip route show | grep docker0 | awk '{print \$9}'` --rm -it debian

**Comment by jfrazelle** [comment]
closed by https://github.com/docker/docker/pull/10902
