### ISSUE TITLE
DELETE is not RESTful enough

### ISSUE THREAD

**Issue by achanda** [docker/docker#10867]
According to the wikipedia example, DELETE on a resource with no parameters should delete all instances of that resource. Currently, it throws an error saying the null id could not be found:

```
cloudscaling@mngmt2:~> curl -X DELETE http://localhost:2375/images/
No such image:
cloudscaling@mngmt2:~> curl -X DELETE http://localhost:2375/containers/
No such container:
```

[Wiki] (http://en.wikipedia.org/wiki/Representational_state_transfer#Example)

**Comment by ebuildy** [comment]
Could be dangerous to delete all images like this, maybe something like:

    curl -X DELETE http://localhost:2375/images/_all

And print a help message at /images/.

**Comment by achanda** [comment]
Agreed that a  `_all` route might be a good way. The CLI uses the REST API to do tasks. Since the REST API does not allow this, the CLI won't. If this is implemented, it should be easy to make the CLI accept a `*` for image and container names. It might be a nice idea to print a "are you sure?" confirmation in the CLI>

**Comment by crosbymichael** [comment]
I think this sounds like a good idea to support, it would reduce the amount of request it takes to delete many images or containers. 

Lets see how everyone else feels.

ping @vieux @tiborvass

**Comment by duglin** [comment]
Would it make sense to just support wildcards and then "*" would get 'em all ?

**Comment by HuKeping** [comment]
Agree on a new endpoint for deleting all images/containers, just wonder if  `_all` is a good choice

**Comment by pmalmgren** [comment]
#dibs

**Comment by pmalmgren** [comment]
@achanda @crosbymichael  `busybox:latest`, `emptyfs` and all the images specified in the test setup files `hack/make/.ensure-images` and `hack/make/.ensure-frozen-images` get deleted when the delete all image test case is run, causing errors in other tests. Here are the tests which break:

```
FAIL: docker_cli_build_test.go:5549: DockerSuite.TestBuildRUNoneJSON
FAIL: docker_cli_build_unix_test.go:14: DockerSuite.TestBuildResourceConstraintsAreUsed
FAIL: docker_cli_run_test.go:1823: DockerSuite.TestRunCidFileCleanupIfEmpty
FAIL: docker_cli_save_load_test.go:107: DockerSuite.TestSaveImageId
FAIL: docker_cli_save_load_test.go:167: DockerSuite.TestSaveMultipleNames
FAIL: docker_cli_inspect_test.go:23: DockerSuite.TestInspectImage
FAIL: docker_cli_inspect_test.go:128: DockerSuite.TestInspectImageFilterInt
FAIL: docker_cli_inspect_test.go:168: DockerSuite.TestInspectImageGraphDriver
```

Do you think it would make sense, for now, to add a tag to the delete all images test case which ensures it won't be run with all of the other tests?

Also, would it also make sense to modify the above tests to somehow make sure that the images they use are available and if not, create them? Maybe this should already be happening in `integration-cli/check_test.go`. Thanks!

**Comment by calavera** [comment]
I'd rather not have any endpoint that removes things in bulk. They are source to great issues. I don't think we should implement this.

Unless other maintainers disagree, I'll close this issue with WON'T FIX in the next few days.

**Comment by thaJeztah** [comment]
@calavera are you against offering it as a CLI option, or also against implementing it in the API?

**Comment by calavera** [comment]
both. Users can remove all images with `docker images -q | xargs docker rmi -f`.

**Comment by thaJeztah** [comment]
@calavera yup, I always thought that'd be ok, but for many people it looks like that is causing issues, because it's racy; See this thread, and for example this comment (and some others before/after)    https://github.com/docker/docker/issues/928#issuecomment-146929432).
