### ISSUE TITLE
--restart=no should set HostContainer.RestartPolicy.Name to 'no'

### ISSUE THREAD

**Issue by joshwilsdon** [docker/docker#10874]
Currently in the payload to create if you pass:

```
--restart=no
```

to the docker client, it sends:

```
Hostconfig.
        "RestartPolicy": {
          "Name": "",
          "MaximumRetryCount": 0
        },
```

to the API. It seems like it would be much better to set Name: "no" here instead of empty string, because empty string is also used when no restart policy is set. It is useful to be able to distinguish between these two cases at the API level. Especially if the default is ever changed or if things like: #9678 or #8821 are implemented.

If new default behaviors are added around restart it would be useful to be able to have someone opt-out.

If for example the behavior were changed such that a host reboot or a docker daemon restart would try to bring the system back to where it was when it restarted, it would be useful for a user to have been able to have set "no" as their restart policy if they are running some application which would be harmed by booting on such a restart (eg. replicated pair which would then be out of date, etc).

Simply adding a 'no' when the user specifies `--restart=no` solves this problem because it's possible then to differentiate between someone who just wants whatever docker's default behavior happens to be and someone who definitely does not want their container to ever be automatically restarted.

**Comment by cpuguy83** [comment]
I'm not sure I understand.
Why would Docker set an undefined value for the restart policy?

**Comment by thaJeztah** [comment]
> Why would Docker set an undefined value for the restart policy?

(Well, it *does* set `MaximumRetryCount:0`, which also isn't specified.)

I think the docs are confusing here; according to [the docs](https://docs.docker.com/reference/commandline/cli/#run), valid options for `--restart` are `no | on-failure[:max-retry] | always`, but the *default* is `""`. Apparently, `""` and `no` are the same for CLI.

The [API docs](https://docs.docker.com/reference/api/docker_remote_api_v1.17/#create-a-container) doesn't mention "no" as a valid value for the API, so for the API, I think `""` is the right value for "no restart policy".

Perhaps the docs should be changed, showing `--restart=no` to show that "no" is the default value?

**Comment by crosbymichael** [comment]
**Proposed solution**:

The docker cli should set a default restart policy of `no` instead of `""` for the cli flag's default value.
