### ISSUE TITLE
Docker events stops sending events

### ISSUE THREAD

**Issue by smousa** [docker/docker#10879]
I don't have clear repro steps but I have a box that ran out of disk space and now it intermittently stops sending docker events when containers get created, destroyed, etc.  This is on docker 1.3.3 on CentOS 7.  Has anyone seen this before, or can give me advice on how I may be able to debug this issue?  The systemd logs don't provide any information beyond what kind of commands were called.

Also, I have tried uninstalling and reinstalling docker, but the issue recurs.

The current workaround is restarting the docker daemon.

**Comment by thaJeztah** [comment]
@smousa have you found a way to reproduce this? Also could you add the output of `docker version`, `docker info` and `uname -a`. Also, perhaps you can try if this problem is still present in the current version of Docker (1.5.0)

**Comment by MHBauer** [comment]
Any update? This issue seems stale.

**Comment by thaJeztah** [comment]
agreed, I'm closing this issue, happy to re-open with a reproducible case and running the current version of docker
