### ISSUE TITLE
Bug: Docker Stats is not showing the CPU % when the daemon runs on LXC Driver

### ISSUE THREAD

**Issue by kgrvamsi** [docker/docker#10876]
Problem:

I have installed docker 1.5 on a Rhel machine and installed the lxc drivers and made the docker daemon run as 

docker -d  --exec-driver=lxc

and afer that i started running two containers and made to run a simple dd command to check the memory and cpu utilization metrics from the docker stats

here are the commands

Container - test1

bash-4.2# dd if=/dev/zero of=upload_test bs=1M count=10000

Container - test2

bash-4.2# dd if=/dev/zero of=upload_test bs=1M count=10000

and when i check for the metrics here is the output
```
[root@ip-00-0-0-000 ec2-user]# docker stats test1
CONTAINER           CPU %               MEM USAGE/LIMIT     MEM %               NET I/O
test1                        0.00%                          0 B/0 B                 0.00%               0 B/0 B


[root@ip-00-0-0-000 ec2-user]# docker stats test2
CONTAINER           CPU %               MEM USAGE/LIMIT     MEM %               NET I/O
test2                        0.00%                          0 B/0 B                 0.00%               0 B/0 B
```
Docker stats only support for default libcontainer driver or even for lxc driver?

**Comment by cpuguy83** [comment]
@kgrvamsi #10498

**Comment by jfrazelle** [comment]
closed by https://github.com/docker/docker/pull/10498
