### ISSUE TITLE
Docker daemon won't start

### ISSUE THREAD

**Issue by bloody76** [docker/docker#10880]
Hi,

I am having some issues with starting docker, the daemon won't start and the output of docker -d -D is:

```
[debug] server.go:1390 docker group found. gid: 112
[debug] devmapper.go:545 [devmapper] removeDevice START
[debug] devmapper.go:558 [devmapper] removeDevice END
[debug] deviceset.go:842 [deviceset docker-9:2-408007] waitRemove(docker-9:2-408007-base)
[debug] deviceset.go:853 Waiting for removal of docker-9:2-408007-base: exists=0
[debug] deviceset.go:866 [deviceset docker-9:2-408007] waitRemove(docker-9:2-408007-base) END
[debug] deviceset.go:455 libdevmapper(3): ioctl/libdm-iface.c:1786 (-1) device-mapper: message ioctl on docker-9:2-408007-pool failed: Invalid argument
[debug] deviceset.go:735 Error deleting device: Error running deleteDevice dm_task_run failed
[debug] deviceset.go:672 Error device setupBaseImage: Error running deleteDevice dm_task_run failed
```

The context is that my disk runned out of space, so I copied my files from /var/lib/docker to a new place, let's say /home/newplace/docker. I also put in my /etc/default/docker file the following:

```
DOCKER_OPTS="-g /home/newplace/docker"
```

I have been trying many things but I don't see what can be the problem. I have looked after the metadata in docker/devicemapper/devicemapper/metadata with thin_check but no errors are coming out.

Do you have any idea of the problem ?

**Comment by phemmer** [comment]
What version of docker is this (output of `docker version`)? That output format is old. There have been a lot of devicemapper fixes in recent versions.

**Comment by bloody76** [comment]
Hi,

My docker version is 1.3.3 build d344625.

Is that outdated ?

**Comment by phemmer** [comment]
Not that much so. The logging format changed in 1.4.0, so I knew you were at least using something earlier than that, just wasn't sure by how much.
The only 2 things that spring to mind are:
1. Look for any zero-length files, and remove them.
2. Were all the devicemapper volumes unmounted when you did the copy? If not you could have copied across mounts, and this might be confusing docker.

**Comment by bloody76** [comment]
I am updating docker in order to get the last version,

1. Where should I look for those zero-length file ? In the docker folder ?
2. It might be possible yes, is there any ways to know if it really confused docker ?

**Comment by bloody76** [comment]
Ok, I updated to version 1.5.0, here is the new output of docker -d -D 

```
DEBU[0000] docker group found. gid: 112
DEBU[0000] libdevmapper(6): ioctl/libdm-iface.c:1750 (4) dm version   OF   [16384] (*1)
DEBU[0000] libdevmapper(6): ioctl/libdm-iface.c:1750 (4) dm version   OF   [16384] (*1)
WARN[0000] WARNING: Udev sync is not supported. This will lead to unexpected behavior, data loss and errors
DEBU[0000] devicemapper: udev sync support: false
DEBU[0000] Generated prefix: docker-9:2-408007
DEBU[0000] Checking for existence of the pool 'docker-9:2-408007-pool'
DEBU[0000] libdevmapper(6): ioctl/libdm-iface.c:1750 (4) dm info docker-9:2-408007-pool  OF   [16384] (*1)
DEBU[0000] libdevmapper(6): ioctl/libdm-iface.c:1750 (4) dm status docker-9:2-408007-pool  OF   [16384] (*1)
DEBU[0000] [deviceset] constructDeviceIdMap()
DEBU[0000] Loading data for file /var/lib/docker/devicemapper/metadata/base
DEBU[0000] Added deviceId=0 to DeviceIdMap
DEBU[0000] Loading data for file /var/lib/docker/devicemapper/metadata/transaction-metadata
DEBU[0000] Added deviceId=0 to DeviceIdMap
DEBU[0000] [deviceset] constructDeviceIdMap() END
DEBU[0000] Rolling back open transaction: TransactionId=2 hash= device_id=0
DEBU[0000] libdevmapper(6): ioctl/libdm-iface.c:1750 (4) dm message docker-9:2-408007-pool  OF  delete 0 [16384] (*1)
DEBU[0000] libdevmapper(3): ioctl/libdm-iface.c:1768 (-1) device-mapper: message ioctl on docker-9:2-408007-pool failed: Invalid argument
ERRO[0000] Warning: Unable to delete device: Error running DeleteDevice dm_task_run failed
DEBU[0000] Initializing base device-mapper thin volume
DEBU[0000] [devmapper] CreateDevice(poolName=/dev/mapper/docker-9:2-408007-pool, deviceId=1)
DEBU[0000] libdevmapper(6): ioctl/libdm-iface.c:1750 (4) dm message docker-9:2-408007-pool  OF  create_thin 1 [16384] (*1)
DEBU[0000] libdevmapper(3): ioctl/libdm-iface.c:1768 (-1) device-mapper: message ioctl on docker-9:2-408007-pool failed: Invalid argument
DEBU[0000] Error creating device: Error running CreateDevice dm_task_run failed
DEBU[0000] Error device setupBaseImage: Error running CreateDevice dm_task_run failed
FATA[0000] Error running CreateDevice dm_task_run failed
```

Is that helping in any ways ?

**Comment by bloody76** [comment]
Finaly, removing the zero-length files was the issue. The json file in trust folder was the problem ! Thank's so much !

**Comment by munkyboy** [comment]
FWIW, I ran into this exact issue (an empty `/var/lib/docker/trust/official.json`) after resizing my virtual disk using these instructions https://docs.docker.com/articles/b2d_volume_resize/

**Comment by rkpantangi** [comment]
That worked for me too. After deleting that empty official.json file, docker started.

**Comment by jcfigueiredo** [comment]
Thanks for that @all it helped me here a lot. 
Just so we don't stop on dealing with the symptoms and actually fix the problem, my issues with this start after trying to pull from an 'inexistent' registry. Like, I have .dockercfg in place, but my puppet script was try to run docker pull as a different user (not finding the right cfg file).

Did anyone else ran into this scenario?
