### ISSUE TITLE
Tab completion for container names

### ISSUE THREAD

**Issue by eloquii** [docker/docker#10885]
E.g. when running a Docker command like "docker top CONTAINER".  The container name is required, but must be typed in full.  When context requires a container name, tab-completion should be available.

I'm running under boot2docker on OSX.

**Comment by programmerq** [comment]
There is a bash completion script already in the repository: https://github.com/docker/docker/blob/master/contrib/completion/bash/docker

I just tried it out with osx + boot2docker and it seems to work quite well.

**Comment by albers** [comment]
Do you have bash completion installed? It seems to be not installed by default on a mac, see https://github.com/docker/fig/pull/639#issuecomment-68560400

**Comment by robforsythe** [comment]
Can we mark this as closed?

**Comment by cpuguy83** [comment]
Yep, closing. There's completion stuff for several shells.

**Comment by mbigras** [comment]
@programmerq how did you get tab completion for the container names to work? Did you simply run the bash script that you linked to? Did you pass it to the `docker` cli?

**Comment by programmerq** [comment]
@mbigras The bash completion script goes in the normal bash completion script directory. Take a look at the rpm spec for docker as an example:

https://github.com/docker/docker/blob/3167bb8629a70728daaae3637ef9fa63273bb458/hack/make/.build-rpm/docker-engine.spec#L166-L172

The exact location may vary on your distro.

The .deb, .rpm, docker-for-mac, docker toolbox, and other installation methods should include bash completion scripts out of the box.

**Comment by lnunno** [comment]
Completion script seems to be gone now, has it moved?

**Comment by albers** [comment]
The completions were moved to `docker/cli`, the new home of the `docker` sources.
