### ISSUE TITLE
Container rename does not enforce "/" prefix

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#10890]
If I do `docker run --name foo` and then `docker inspect`, the `Name` will be "/foo".  With the remote api if I do `.../rename?name=bar` and then call `docker inspect` the `Name` will be "bar" (with no leading /).  It seems that the daemon should just automatically prepend "/" if the client doesn't specify it.

**Comment by ibuildthecloud** [comment]
I think I was doing something wrong.  I'll reopen if this was really an issue.

**Comment by LK4D4** [comment]
@ibuildthecloud There are some discrepancies between cli and api in container naming.

**Comment by erjiang** [comment]
#10996 is possibly related to this.
