### ISSUE TITLE
Display full download progress on pull/push

### ISSUE THREAD

**Issue by Yajo** [docker/docker#10894]
When pulling an image, Docker shows little information about download progress:

    b6b7af41d3c1: Downloading 1.1 kB/1.605 kB

It's OK, but it only displays one amount of data per layer. From an user perspective, it would be better to have information about the download of all layers (to guess how much time will it take):

    b6b7af41d3c1: Downloading 1.605 kB/1.605 kB (Total 15.1 MB/425.1 MB)

**Comment by patelrit** [comment]
+1 Streaming the download progress in the API would be great!

**Comment by xiaods** [comment]
@Yajo current docker 1.5 have now feature:
b6718650e87e: Download complete 
493bab5fff45: Downloading [=>                                                 ] 1.579 MB/76.97 MB 1h10m17s
Because the docker images download layer by layer. so the download hint is focus on this layer's time span. Now it also provide a estimate timed, does it make sense on your concern?

**Comment by Yajo** [comment]
It's better than it was indeed, but it still lacks the remaining time of the full image download.

When starting a pull, docker could check which layers will it need and how big they are before actually starting to pull layer by layer. Then, based on the current download speed, try to predict the total remaining time and size.

**Comment by Slammamonichio** [comment]
+1 Streaming the download progress in the API would be great!

**Comment by LK4D4** [comment]
@aaronlehmann @tonistiigi Is this possible/easy to implement?

**Comment by tonistiigi** [comment]
@LK4D4 possible - yes, easy - no

**Comment by LK4D4** [comment]
I'm closing this as it has little interest recently. PR with such functionality will be gladly accepted.

**Comment by aaronbeall** [comment]
Is there any way to access this progress information programmatically, from NodeJS, or CLI? The `docker events` show a `pull` when the download is complete, but no progress along the way.

**Comment by thaJeztah** [comment]
The pull progress is part of the API response of the `POST /images/create` endpoint, but it's not returned as part of the events API

**Comment by aaronbeall** [comment]
@thaJeztah Thanks for the reply... so I'm using `docker-compose`, actually from a child process in a NodeJS/Electron app. I'm not calling `images/create` or `Dockerode.createImage` directly... does this mean there's no way to monitor the progress from `docker-compose`? When I call `docker-compose` I see the progress output like `[====>   ]`, but I can't seem to get that output through `stdout` in my NodeJS process.

**Comment by hron84** [comment]
@LK4D4 would it be possible to display a(n estimated) download speed to the download bar for the current layer?

**Comment by Mondonno** [comment]
Would love to see it in next release!
