### ISSUE TITLE
Ability for injection of custom metrics into container for access via Stats API

### ISSUE THREAD

**Issue by geekpete** [docker/docker#10892]
It would be great to be able to report metrics from an app to the container internally for those metrics to be accessible via the standard stats api interface external to the container.

**Comment by thaJeztah** [comment]
Thanks for creating this feature request.

Would you be able to describe your use-case a bit more in detail? I'm not really sure this is something that should be implemented. In general, apps inside a container shouldn't be aware *that* they are running inside a container (have any knowledge that they're running on docker).

With the current description there isn't enough information for the maintainers to decide whether this is something to implement or not, but with some more info, perhaps it is!

**Comment by geekpete** [comment]
I guess this is one convenience in exchange for another complexity.

The idea was instead of every app you deploy in a docker container having to know about different centralised logging/metrics systems, every app could instead just log their stats to the container itself. Making the app simpler than having to store config for an external endpoint and communicate out to log metrics in an external system.

But it means the app is then docker-specific (unless the stats framework becomes a wider container standard for more than just docker) in exchange for increasing complexity on the docker host server that would need to run an agent to harvest the stats from the docker daemon and feed it to the external collection system. Or the docker daemon could push the stats somewhere.

6 of one, half a dozen of the other.

So I'm not sure it would really make things easier overall, but might be easier for some people in some circumstances.

The other concern would be metrics data backlogging inside the docker stats framework, it would either have to throw data away or have some way to store the backlog somewhere. Probably not a wheel the docker team would want to be reinventing if existing stats collection systems have solved this already.

So in general, the option would allow more flexibility for people to collect stats locally for redistribution to centralised systems later, but it is definitely not without complexity and challenges. And if there's no huge call for this feature then the docker team's resources would be better spent elsewhere I'd guess.

I'm in favour for this ticket to be closed.

**Comment by thaJeztah** [comment]
Thanks for expanding on your initial thoughts. I agree that it would be nice to have something like that, but this is out of scope for docker itself. For non real-time statistics/metrics, you might be interested in https://github.com/docker/docker/pull/10568, which would give flexibility for consuming *logs* produced by containers.

You should be able to close this ticket (because you created it). Thanks!
