### ISSUE TITLE
Call for Participation - CIS Security Benchmark for Docker under development

### ISSUE THREAD

**Issue by praving5** [docker/docker#10905]
Dear Docker Users,

CIS has initiated a project to develop a security benchmark for Docker containers. So far, we have 30 recommendations completed, tested and well written. 38 are in draft and are being worked.

We need your participation to review and contribute as much as you can. All you need to do is a quick signup using your work email address.

To register to access the sources, please go here: benchmarks.cisecurity.org/register.   Enter the information requested.  Please note you must register using your work email address for validation purposes.  You will receive a validation request and once complete you will receive notice of your credentials.
Below are some next steps you may want to take once you have registered:
 
•        Log in to the collaboration site with the credentials you received then,
o   Click the Profile link in the upper right hand corner
o   Click the “Change Password” tab
o   Enter a new password
•        To join a consensus team, select Profile -> Options Button -> Manage Communities.

Once you join the community, go to Files section and watch the pinned video on how to work with site and contribute.

That's all. Looking forward to see you all. Get the work done so far here:
https://app.box.com/s/4dkjm3qh9c6za3tlpkc6e4bw0mhlti0w

Please let me know if you have questions around this.

Thanks and regards,
Pravin Goyal

**Comment by jfrazelle** [comment]
closing as spam sorry

**Comment by praving5** [comment]
This is not spam. This project is running full fledged. You at least need to download that pdf if you dont believe. Do not complain later own that CIS developed something of its own without involving Docker users and community. I would suggest opening it and allowing people to go through it and contribute.
