### ISSUE TITLE
docker search Unexpected status code 404

### ISSUE THREAD

**Issue by GittyHup** [docker/docker#10906]
I've setup a private docker registry with s3 backend. I can push and pull images to the registry. But, for some reason docker search is failing and I cannot find much information on that. Could anyone please shine some light on this? Also the registry is using S3 bucket as the backend.

    root@ip-10-232-1-128:~# docker search 10.232.1.123:5000/ubuntu
    INFO[0120] GET /v1.17/images/search?term=10.232.1.123%3A5000%2Fubuntu
    INFO[0120] +job search(10.232.1.123:5000/ubuntu)
    INFO[0120] +job resolve_repository(10.232.1.123:5000/ubuntu)
    INFO[0120] -job resolve_repository(10.232.1.123:5000/ubuntu) = OK (0)
    Unexpected status code 404
    INFO[0124] -job search(10.232.1.123:5000/ubuntu) = ERR (1)
    ERRO[0124] Handler for GET /images/search returned error: Unexpected status code 404
    ERRO[0124] HTTP Error: statusCode=500 Unexpected status code 404
    FATA[0004] Error response from daemon: Unexpected status code 404

In the docker-registry access.log:

    10.232.1.128 - - [19/Feb/2015:16:42:58 -0800] "GET /v2/ HTTP/1.1" 404 233 "-" "Go 1.1 package http"
    10.232.1.128 - - [19/Feb/2015:16:42:58 -0800] "GET /v1/_ping HTTP/1.1" 200 1637 "-" "Go 1.1 package http"
    10.232.1.128 - - [19/Feb/2015:16:42:58 -0800] "GET /v1/search?q=ubuntu HTTP/1.1" 404 233 "-" "docker/1.5.0 go/go1.4.1 git-commit/a8a31ef kernel/3.13.0-45-generic os/linux arch/amd64"

**Comment by dmp42** [comment]
Likely you haven't enabled the search module on your registry.

More about that in the documentation: https://github.com/docker/docker-registry#search-engine-options

If you are still having issues with the registry, please open a ticket over there (https://github.com/docker/docker-registry/issues/)
