### ISSUE TITLE
git import of a tarball produced with the -g switch fails with a fatal error with no descriptive text

### ISSUE THREAD

**Issue by cjashfor** [docker/docker#10907]
I'm running Docker 1.4.1 on Fedora 21
% docker -v
Docker version 1.4.1, build 5bc2ff8/1.4.1
% uname -r
3.18.3-201.fc21.x86_64

If I produce a simple (or complex) tarball on Linux, using tar's listed-incremental option:  -g <somefile>, and then import that resulting tarball using "docker import - testimage <  test.tar"  I get a fatal error, which has no descriptive error message:
% docker import - testimage < test.tar
FATA[0002] Error:                                       

You can reproduce this very simply:
mkdir -p ~/testdir/tardir
cd ~/testdir/tardir
tar -g ../incremental -cpf ../test.tar ./
cd ..
docker import - testimage < test.tar
The result is:
FATA[0002] Error:

Now, try the same thing again but without the "-g ../incremental" option:
rm -rf ~/testdir
mkdir -p ~/testdir/tardir
cd ~/testdir/tardir
tar -cpf ../test.tar ./
cd ..
docker import - testimage < test.tar

This results in creating an image.

My guess is that docker is failing to interpret the meta-data in the tar file for this newer GNU-format incremental-backup capability.

**Comment by cpuguy83** [comment]
Current error is: `Error response from daemon: ApplyLayer exit status 1 stdout:  stderr: Unhandled tar header type 68`

Go still does not handle this tar format, but certainly a better error.
I'm going to close this, but if you feel like this is still an issue please ping here and we can discuss.
Thanks!

**Comment by cjashfor** [comment]
That is a much better error message.  I think it's OK for now, thank you.  Someone may really want a fix later, but this at least gives them a clue as to what's going wrong.  It took me many hours to figure out it was the -g option that was causing the problem.
