### ISSUE TITLE
no space left on device

### ISSUE THREAD

**Issue by SimonWang2014** [docker/docker#10915]
I found when use Dockerfile to build a image, if the Dockerfile is large, the docker often occurs error -->   "no space left on device" , it turns that the inode has been used up, but the storage is enough, How to resolve?

**Comment by thaJeztah** [comment]
Based on just this information, this could be a duplicate of https://github.com/docker/docker/issues/9755,  https://github.com/docker/docker/issues/5900 or https://github.com/docker/docker/issues/10613

Would you be able to provide the output of `docker info`, `docker version` and `uname -a`?

**Comment by dmp42** [comment]
cc @crosbymichael

**Comment by jfrazelle** [comment]
closing as dup of  #5900 or #10613
