### ISSUE TITLE
Can't use the option -f <CustomDockerFileName>

### ISSUE THREAD

**Issue by AJNOURI** [docker/docker#10910]
> sudo docker version
> Client version: 1.5.0
> Client API version: 1.17
> Go version (client): go1.4.1
> Git commit (client): a8a31ef
> OS/Arch (client): linux/amd64
> Server version: 1.5.0
> Server API version: 1.17
> Go version (server): go1.4.1
> Git commit (server): a8a31ef

``` sudo cp Dockerfile sshd_dockerfile``` 

``` sudo docker build --help``` 
>
>Usage: docker build [OPTIONS] PATH | URL | -
>
>Build a new image from the source code at PATH
>
>  -f, --file=""        Name of the Dockerfile(Default is 'Dockerfile' at context root)
>  --force-rm=false     Always remove intermediate containers, even after unsuccessful builds
>  --help=false         Print usage
>   --no-cache=false     Do not use cache when building the image
>  --pull=false         Always attempt to pull a newer version of the image
>  -q, --quiet=false    Suppress the verbose output generated by the containers
>  --rm=true            Remove intermediate containers after a successful build
>  -t, --tag=""         Repository name (and optionally a tag) to be applied to the resulting image in case of success

``` sudo docker build -f sshd_dockerfile -t mysshdimage ```
> docker: "build" requires 1 argument. See 'docker build --help'.
 
``` sudo docker build --tag="mysshdimage" --file="sshd_dockerfile"``` 
> docker: "build" requires 1 argument. See 'docker build --help'.

``` sudo docker build --file="sshd_dockerfile"``` 
> docker: "build" requires 1 argument. See 'docker build --help'.

``` sudo docker build -f "sshd_dockerfile"``` 
> docker: "build" requires 1 argument. See 'docker build --help'.

```  sudo docker build -t  mysshdimage -f sshd_dockerfile``` 
> docker: "build" requires 1 argument. See 'docker build --help'.

The old format works file:
```  sudo docker build -t  mysshdimage .``` 
> Sending build context to Docker daemon  5.12 kB
> Sending build context to Docker daemon 
> Step 0 : FROM ubuntu:14.04
>  ---> 5ba9dab47459
> Step 1 : MAINTAINER Sven Dowideit <SvenDowideit@docker.com>
>  ---> Running in 01dcc78e394b
>  ---> bcd0ef7c6dde
> ...

**Comment by duglin** [comment]
When you look at your old format:
```
sudo docker build -t mysshdimage .
```
the `.` tells docker where your build context (files) are for the build.  You still need to give docker that information when you use the -f option.  So, try:
```
sudo docker build -t mysshdimage -f sshd_dockerfile .
```

**Comment by AJNOURI** [comment]
Thanks duglin. Indeed, it works:
```sudo docker build -t <tag> -f <custom_dockerfile> <file_location>```

**Comment by mosfet1kg** [comment]
For my case, the following command works..
sudo docker build -t <tag> -f <dockerfile> ./

**Comment by kiwenlau** [comment]
@mosfet1kg Thx. Add "./" works for me!
