### ISSUE TITLE
Proposal: Various `docker version` outputs

### ISSUE THREAD

**Issue by phemmer** [docker/docker#10934]
Right now the `docker version` output is rather inconsistent.

For example:
```
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.3
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.3
Git commit (server): a8a31ef
```

The first 2 lines are prefixed with "Client", but then the next 3 lines have "(client)" suffixed. Then the pattern repeats for the server lines. I think it would be better to use the same style for all the lines.

Some previews of what different formats might look like:

### 1 - prefix
```
Client version: 1.5.0
Client API version: 1.17
Client go version: go1.3
Client Git commit: a8a31ef
Client OS/Arch: linux/amd64
Server version: 1.5.0
Server API version: 1.17
Server Go version: go1.3
Server Git commit: a8a31ef
Server OS/Arch: linux/amd64
```

### 2 - suffix
```
Version (client): 1.5.0
API version (client): 1.17
Go version (client): go1.3
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Version (server): 1.5.0
API version (server): 1.17
Go version (server): go1.3
Git commit (server): a8a31ef
OS/Arch (server): linux/amd64
```

### 3 - sectioned
```
Client
  Version:     1.5.0
  API version: 1.17
  Go version:  go1.3
  Git commit:  a8a31ef
  OS/Arch:     linux/amd64
Server
  Version:     1.5.0
  API version: 1.17
  Go version:  go1.3
  Git commit:  a8a31ef
  OS/Arch:     linux/amd64
```

### 4 - tabular
```
              Client        Server
Version:      1.5.0         1.5.0
API version:  1.17          1.17
Go version:   go1.3         go1.3
Git commit:   a8a31ef       a8a31ef
OS/Arch:      linux/amd64   linux/amd64
```

Personally I vote for the tabular format. Followed by sectioned. Prefixing looks okish, but suffix is just messy.

**Comment by ahmetalpbalkan** [comment]
This command probably should have a `--json` parameter, otherwise changing this output would simply break any scripts depending on existing output format. Also `grep`pability is probably another concern. (1)(2) just is easier to grep. But +1 for (4).

**Comment by thaJeztah** [comment]
I like (3) visually, and that format would be useful if JSON is considered, i.e. `{Server: {Version:1.5.0,...}, Client: {}}`, but it wouldn't be useful for `grep`. If `grep` is desired, I like (1).

While discussing this; I think the output of "version" should be added to `docker info` as well. Right now, we have to ask users to include the output of both `docker version` and `docker info` when reporting issues; including it in `docker info` would make it easier for them to provide that.

**Comment by phemmer** [comment]
If grep/scripting is a concern, we should probably just add a `--format` option. The output would just be defined as a go text template, and `--format` would override the template. Then grep isn't needed at all.

**Comment by thaJeztah** [comment]
Agreed; the `--format` would be consistent with other commands. I think *all* suggestions are an improvements over the current output, so I'd be happy with any of them :)

**Comment by ahmetalpbalkan** [comment]
@phemmer also think about the error case where client can't reach to daemon. That probably cannot be handled nicely in (4).

**Comment by phemmer** [comment]
Why not? Just leave it blank, or put in a placeholder (such as `?` or `-`)

**Comment by aanm** [comment]
@phemmer Will you work on this?

**Comment by phemmer** [comment]
I might, but not sure. depends how much time I have after we reach consensus on what the output should look like (could be today, could be next month)

**Comment by achanda** [comment]
I believe it will be better to invert the tabular form. Most people read from left to right. So it might be easier for an user to read it.

**Comment by aanm** [comment]
@achanda how so?
First the values and then labels?

**Comment by achanda** [comment]
@aanm I mean this:

```
                  Version      API version      Go version      Git commit      OS/Arch
Client:           1.5.0          1.17              go1.3          a8a31ef     linux/amd64
Server:           1.5.0          1.17              go1.3          a8a31ef     linux/amd64
```

It might just be me, but I find this easier to read.

**Comment by aanm** [comment]
The only problem I see with it is it can reach >80 columns

**Comment by achanda** [comment]
Ah, I see. Agreed that this might be a problem if more columns are added later.

**Comment by icecrime** [comment]
My vote:
- (4) as a better human-readable output
- a new flag (`--json`?) providing a **true** computer-readable output

**Comment by aanm** [comment]
Why can't we have all options?

**Comment by icecrime** [comment]
@aanm Because we are the ones maintaining the code after it's merged.

**Comment by phemmer** [comment]
Closing since #14047 has been merged, and addresses the inconsistency issue.
#14186 has been opened to address the `--format` flag.
