### ISSUE TITLE
docker-commit causes a paused container to unpause

### ISSUE THREAD

**Issue by NonerKao** [docker/docker#10932]
1. docker pause <ID>; // I first pause a container
2. docker commit <ID> <some name>; //and then I commit that container to an image
3. that container start to work after being commited!

I have check the man page of docker-commit and docker-pause, 
but nothing related has been found.  Is this behavior right? 
I mean, does commit command intend to unpause a paused container or 
it is a unwilling side-effect?

The evironment is the newest 1.5.0-dev.
Any comments would be highly appreciated.

**Comment by NonerKao** [comment]
just some furthur investigation...

In daemon/commit.go line 35,
no matter what the status of that container is, 
the job.GetenvBool("pause") call always returns true.

In api/client/command.go line 1729,
what does the "0" means in v.Set("pause", "0")?

**Comment by coolljt0725** [comment]
I think this is a bug of docker. By default, docker commit will pause a container and unpause it after commit.  But I don't think docker commit unpause a mannul paused container is not a desired behavior
I think this is going to fix by #10935
