### ISSUE TITLE
docker fails trying to pull a non-existent layer

### ISSUE THREAD

**Issue by vgeshel** [docker/docker#10931]
I have an image in a private repo that was built from a Dockerfile of mine. When I try to pull this image, I get the following:

```sh
$ docker pull registry:5000/namespace/repo:165a91e03dd4ad57b770a6e307d771b3990fc84c
Pulling repository registry:5000/namespace/repo
327e2b286d35: Pulling dependent layers
1d205f9648bf: Download complete
29b86eaa13ae: Error pulling image (165a91e03dd4ad57b770a6e307d771b3990fc84c) from registry:5000/namespace/repo, lstat /var/lib/docker/overlay/5a9acc716f789798c5c3d93dd1a062652f7fe95b5827d96e484f3bc82b65eca3/root: no such file or directory ca3/root: no such file or directory
e78415e15dfe: Error pulling image (165a91e03dd4ad57b770a6e307d771b3990fc84c) from registry:5000/namespace/repo, Server error: 404 trying to fetch remote history for e78415e15dfe10ef2511136ea3c5a: Download complete
3b363fd9d7da: Download complete
607c5d1cca71: Download complete
f62feddc05dc: Download complete
8eaa4ff06b53: Download complete
6208e07d879f: Download complete
c20edc7e0d45: Download complete
...
FATA[0266] Error pulling image (165a91e03dd4ad57b770a6e307d771b3990fc84c) from registry:5000/namespace/repo, lstat /var/lib/docker/overlay/5a9acc716f789798c5c3d93dd1a062652f7fe95b5827d96e484f3bc82b65eca3/root: no such file or directory
```

I have tried building and pushing this image with docker 1.4.1 and 1.5 on ubuntu 14.04. I've tried pulling it with 1.4.1 and 1.5 on ubuntu 14.04 and CoreOS stable and beta. The error happens everywhere. The image built from this specific version of my project (a Clojure project) always has this problem: it is failing to fetch that same layer e78415e15dfe10ef2511136ea3c5a. Dozens of other images built from the same project with the same Dockerfile don't have this problem (I can pull and run their images just fine).

I have recursively gone through the /ancestry files of all the ancestors of my image and there is no reference to this mysterious missing layer anywhere, or any other dangling references.

I'm using the [Go docker registry](https://github.com/ooyala/go-docker-registry) as my private registry, with storage on S3, if that matters. This works fine for hundreds of other images.

I'd appreciate any insight into what's happening here... Thanks!

**Comment by dmp42** [comment]
Have you discussed this with go-docker-registry author?
Have you tried pushing this image and pulling it against the reference (Docker maintained) registry?

**Comment by vgeshel** [comment]
Thanks. I haven't tried either of these things. I'm pretty familiar with the go-docker-registry code and haven't been able to see anything wrong there. As far as I understand, it's docker, not the registry, that decides which layers to pull. Is that wrong?

**Comment by vgeshel** [comment]
I take that back... I've tried pushing this image to the reference registry and I'm not seeing the problem. So must be something in the private registry implementation after all. Thanks!
