### ISSUE TITLE
Please explain how to overlay volumes over an image

### ISSUE THREAD

**Issue by devurandom** [docker/docker#10947]
From [Managing Data in Containers](http://docs.docker.com/userguide/dockervolumes/) in the docs I gather that volumes will completely replace the contents of the directory in the container, just as mount does.

Is there a way to overlay them instead? My use case is having `/var` as a persistent volume to catch all write accesses. As applications usually require a certain directory layout, which they setup on install-time, I somehow need that as the basis for my volume and only record changes to files in the volume. This also needs to work for containers created from different dockerfiles. Thus I assume overlaying the volumes over the container image would be ideal.

**Comment by jfrazelle** [comment]
Ping @cpuguy83

**Comment by cpuguy83** [comment]
Hi, I'm not sure I understand.  Do you literally mean overlay (as in merge) a host path with a container path such as what might be done with overlay fs?

Docker does not support this directly, however you can create an overlay on the host and then mount that in.

Volumes do automatically copy data from the image to the host for "normal" volumes, ie volumes like `docker run -v /foo`, where as volumes created as such `docker run -v /host/path:/container/path` will not.

**Comment by thaJeztah** [comment]
ping @devurandom could you provide the information?

**Comment by devurandom** [comment]
@cpuguy83 Yes, I mean like overlayfs.

And you say that if I install (e.g.) cups into my containerA and then start it while mounting all volumes from containerB (one of them being /var), then all files from containerA in the respective path (i.e. /var) will be copied over to the volume of containerB?

What happens if you do that from multiple containersA1,A2,... and they have different files in (e.g.) /var?

**Comment by cpuguy83** [comment]
@devurandom Docker does bind-mounting, the files are mounted on top, and the originals are shadowed.

**Comment by devurandom** [comment]
So how do I solve my original issue? With e.g. `/var` and cups?

**Comment by thaJeztah** [comment]
I think you need to see what works best for you. From the top of my head, something like;

```Bash
# Create a data-only container and make a volume out of
# /var. All data inside /var is copied from the image
# to the volume
docker create -v /var --name=myvardata ubuntu

# Start your container, using volumes-from
# which will mount the volume that myvardata created
# into your container
docker run --volumes-from=myvardata ubuntu

```

Or, if you want to use a host-mount, you could create a container and copy out the files to your local file-system and use that as a bind-mounted volume. e.g.

```Bash
# temporarily create a container to act as a "template"
docker create -v /var --name=template ubuntu

# copy the "/var" directory out of the container to your local filesystem
mkdir volumes && docker cp template:/var volumes/

# just for showing that we're using the bind-mounted volume
echo "hello world" > volumes/var/hello-world

# no longer need this container. remove it *and* the volume it created
docker rm -v template

# run your container, using the exported "/var" directory as a bint-mounted volume
docker run -it --rm -v $(pwd)/volumes/var:/var ubuntu

# inside the container;
root@833b084ceaaa:/var# ls -la /var
total 48
drwxr-xr-x 11 root root   4096 Jul 22 10:00 .
drwxr-xr-x 32 root root   4096 Jul 22 10:01 ..
drwxr-xr-x  2 root root   4096 Apr 10  2014 backups
drwxr-xr-x  5 root root   4096 Jun 12 11:35 cache
-rw-r--r--  1 root root     12 Jul 22 10:00 hello-world
drwxr-xr-x 23 root root   4096 Jun 12 15:32 lib
drwxrwsr-x  2 root staff  4096 Apr 10  2014 local
lrwxrwxrwx  1 root root      9 Jun 12 11:34 lock -> /run/lock
drwxrwxr-x  5 root syslog 4096 Jun 12 11:35 log
drwxrwsr-x  2 root mail   4096 Jun 12 11:34 mail
drwxr-xr-x  2 root root   4096 Jun 12 11:34 opt
lrwxrwxrwx  1 root root      4 Jun 12 11:34 run -> /run
drwxr-xr-x  5 root root   4096 Jun 12 11:35 spool
drwxrwxrwt  2 root root   4096 Jun 12 11:35 tmp
```

**Comment by devurandom** [comment]
Volumes are reference counted, right? So instead of creating a data container with a `/var` volume, which I then mount into the application container, I could create an application container with a `/var` volume, which I then mount into a data container? And if I delete the app container, the `/var` volume will persist, because it is still used by the data container? So I can recreate the app container and mount the volume into it again?

**Comment by thaJeztah** [comment]
@devurandom yup, volumes are only removed if there are no more containers using it **and only** if the `-v` flag is used when calling `docker rm`. So `docker rm -v mycontainer` will remove the volume as well (unless it's referenced by another container)

**Comment by devurandom** [comment]
So I do not actually need a data container to "hold" the data? I would just create one application container and its volume would be persistent unless deleted explicitly? If necessary, I could even mount the volume into other application containers from there?

Back in the day I read that this scenario should use data containers. Is this information outdated? Or is there a different usecase for data containers?

**Comment by thaJeztah** [comment]
@devurandom Using data-only containers is no hard requirement, but it gives a clearer separation between consistent 'data' and your 'application'. In addition,
using a data-only container allows you to stop, remove and replace your application-container, without loosing a reference to the volume.

Using a bind-mounted volume is another solution to prevent loosing track of the volume (because "you" specify where the volume-data will be stored).

Having said the above, there's going to be a lot of improvements coming to volumes. Volume-drivers will be in the next release (they're currently available in the experimental builds), and there
will be top level commands to manage (create, rename, remove, export) volumes, without having to use a "data-only" container for that.
You can track progress on that in this issue: https://github.com/docker/docker/pull/14242

**Comment by devurandom** [comment]
Thanks!

**Comment by renewooller** [comment]
Back to the idea of overlaying volumes into a docker container, to solve this I'm considering installing aufs or similar into the image, mounting two volumes and then running the aufs command to overlay one into the other. My use case is having files that should really be shared between projects in order to provide code reuse, but that need to be in specific folders within each project due to the way a third party tool processes them. So ( in dev) each project would mount the project source code in one volume, mount the shared code in the other volume and run aufs within the docker file. Is there a better way to do this using existing docker features?

**Comment by dshulyak** [comment]
@thaJeztah Hi, can you please comment on the state of this problem? 

I am trying to mount directory from host system, lets say /etc/xxx with couple of config files, and i want to merge it with existing /etc/xxx on the image. I saw docker cp workaround, but maybe there is better alternatives?

Also, i will be grateful if you will point out which module handles host directory mounting.

**Comment by thaJeztah** [comment]
@dshulyak I don't think it's possible (easily) to use an "overlay" mount as a volume, but perhaps @cpuguy83 knows if it's possible.

**Comment by cpuguy83** [comment]
Not really possible, at least not easily.

**Comment by dshulyak** [comment]
@cpuguy83 Can you provide some ideas how it can be solved?

**Comment by manishjhawar** [comment]
Any volume plugin that can provide the original CoW/overlay requirement now that we have volume plugins?

**Comment by cpuguy83** [comment]
@manishjhawar Volume plugins do not have access to the the container's filesystem.
But the container FS is already CoW, so simply copying the files from the host to the container FS would work.

**Comment by Luc45** [comment]
> Or, if you want to use a host-mount, you could create a container and copy out the files to your local file-system and use that as a bind-mounted volume. e.g.

Isn't this just a bind volume with extra steps?
