### ISSUE TITLE
docker image fails on devicemapper

### ISSUE THREAD

**Issue by thedug** [docker/docker#10944]
time="2015-02-23T05:56:16Z" level="info" msg="Error getting container f921a053a51db43f12051e8608b6724f30bf3eb82df0efd33095ff0afa6ec403 from driver devicemapper: open /dev/mapper/docker-202:16-262147-f921a053a51db43f12051e8608b6724f30bf3eb82df0efd33095ff0afa6ec403: no such file or directory

**Comment by grunzwei-fresh** [comment]
getting this as well...

**Comment by grunzwei-fresh** [comment]
possible duplicate of https://github.com/docker/docker/issues/4036

**Comment by thedug** [comment]
Possibly but the repro steps there are different.

**Comment by jfrazelle** [comment]
You didn't give a way to reproduce.....

**Comment by jfrazelle** [comment]
We need docker version, docker info , uname -a

**Comment by jfrazelle** [comment]
closing as this seems to be a duplicate of several of these

**Comment by jfrazelle** [comment]
https://github.com/docker/docker/issues?q=is%3Aopen+is%3Aissue+label%3A%2Fsystem%2Fdevicemapper
