### ISSUE TITLE
A change was made to docker master that is blowing up builds on Fedora.

### ISSUE THREAD

**Issue by rhatdan** [docker/docker#10946]
<pre>
hack/make.sh dynbinary# WARNING! I don't seem to be running in the Docker container.
# The result of this command might be an incorrect build, and will not be
#   officially supported.
#
# Try this instead: make all
#
bundles/1.5.0-dev already exists. Removing.

---> Making bundle: dynbinary (in bundles/1.5.0-dev/dynbinary)
Created binary: /home/dwalsh/docker/src/github.com/docker/docker/bundles/1.5.0-dev/dynbinary/dockerinit-1.5.0-dev
# _/home/dwalsh/docker/src/github.com/docker/docker/docker
/usr/bin/ld: cannot find -lsqlite3
/usr/bin/ld: cannot find -ldevmapper
/var/tmp/go-link-jOAEET/000008.o: In function `_cgo_cea149ee3e00_Cfunc_getpwnam_r':
/usr/lib/golang/src/os/user/lookup_unix.go:75: warning: Using 'getpwnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/var/tmp/go-link-jOAEET/000008.o: In function `mygetpwuid_r':
/usr/lib/golang/src/os/user/lookup_unix.go:27: warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/var/tmp/go-link-jOAEET/000000.o: In function `_cgo_632c88804cec_C2func_getaddrinfo':
/usr/lib/golang/src/net/cgo_unix.go:55: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
collect2: error: ld returned 1 exit status
/usr/lib/golang/pkg/tool/linux_amd64/6l: running gcc failed: unsuccessful exit status 0x100
[Exit 1]
</pre>

**Comment by rhatdan** [comment]
It would be nice if we could just get rid lxc...

**Comment by lsm5** [comment]
I see this on ubuntu as well:

Created binary: /home/lsm5/repositories/github.com/docker/docker/bundles/1.5.0-dev/dynbinary/dockerinit-1.5.0-dev
# _/home/lsm5/repositories/github.com/docker/docker/docker
/usr/bin/ld: cannot find -ldevmapper
/var/tmp/go-link-5zNwSP/000007.o: In function `mygetpwuid_r':
/usr/share/go/src/pkg/os/user/lookup_unix.go:72: warning: Using 'getpwnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/var/tmp/go-link-5zNwSP/000007.o: In function `_cgo_bc43c179ae62_Cfunc_mygetpwuid_r':
/usr/share/go/src/pkg/os/user/lookup_unix.go:27: warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/var/tmp/go-link-5zNwSP/000001.o: In function `_cgo_14616c423265_Cfunc_freeaddrinfo':
/usr/share/go/src/pkg/net/cgo_unix.go:53: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
collect2: error: ld returned 1 exit status
/usr/lib/go/pkg/tool/linux_amd64/6l: running gcc failed: unsuccessful exit status 0x100

**Comment by inph** [comment]
This is because of recent changes to `project/make/dynbinary` to support gccgo's lack of -X flags.

Relevant issue: https://github.com/docker/docker/issues/9207#issuecomment-75578730

**Comment by jfrazelle** [comment]
fixed by https://github.com/docker/docker/pull/10951, @rhatdan lmk if I am wrong

**Comment by rhatdan** [comment]
LGTM
