### ISSUE TITLE
Move progress reader into separate /pkg dir

### ISSUE THREAD

**Issue by crosbymichael** [docker/docker#10959]
**Summary**: 

Currently there is code in `/utils/progressreader.go` to handle progress bar reporting and stats. This package is too big and there are little testing for these functions. 

**Proposed solution**:

Move the type into a new package inside the `/pkg` directory called `progressreader` and refactor the API into something cleaner.  A proposed api change could look something like:

```go
import "github.com/docker/docker/pkg/progressreader"

r := progressreader.New(progressreader.Config{
    In: reader,
    Out: writer,
    Formatter: sf,
    Size: size,
    NewLines: true,
    ID: id,
    Action: action,
})
defer r.Close()
// usage....
```

**Comment by LK4D4** [comment]
Maybe we can add support of multibars to https://github.com/cheggaaa/pb
I tried some day, but failed to find right sequence :) But that task probably not `white-belt`
