### ISSUE TITLE
Download all layers concurrently rather than serially

### ISSUE THREAD

**Issue by geekpete** [docker/docker#10956]
Is there any real reason the initial run of a docker container that requires the layers to be pulled down cannot pull all of those layers concurrently rather than one at a time?

Would be a fairly sizeable speed up in starting a fresh container.

**Comment by thaJeztah** [comment]
This has been asked before and (unfortunately) isn't possible. You can find an explanation here; https://github.com/docker/docker/issues/4709#issuecomment-39026151

**Comment by geekpete** [comment]
So no way to retrieve meta data from each layer quickly to identify all the layers to fetch, they're all sitting there on http/https waiting to be read.
Then fetch all layers simultaneously to a temporary location then slot them all together for registration in order at the end?

**Comment by thaJeztah** [comment]
I *think* something like that has been attempted, but didn't result in major speed gains, but I don't remember the exact details.

/ping @unclejack - has anything changed since last year, or is this still not possible? Will registry v2 improve the situation?

**Comment by dmp42** [comment]
In the v1 protocol, this is not feasible (layers are processed/extracted on the fly, so, the download must happen sequentially).
Furthermore, downloading "all layers to a temp location" might consume a lot of disk space (some images are gigabytes large).

Now, the v2 protocol does allow for that (with a sliding window of 5 simultaneous layers downloads, which you can see if you docker pull ubuntu or another official image).

**Comment by geekpete** [comment]
Perfect, good to see this has been improved.

Thanks.

**Comment by geekpete** [comment]
Is his issue is now officially solved in docker 1.6 with the improvements to the docker registry and docker engine code?

**Comment by thaJeztah** [comment]
@geekpete it should be; http://blog.docker.com/2015/04/faster-and-better-image-distribution-with-registry-2-0-and-engine-1-6/

Give it a try! Hope you'll enjoy it
