### ISSUE TITLE
Move pid file operations to /pkg/ dir

### ISSUE THREAD

**Issue by crosbymichael** [docker/docker#10958]
**Summary**: 

Currently there is code in `/utils/daemon.go` to handle pid file creation and removal.  This package is too big and there are little testing for these functions. 

**Proposed solution**:

Move the two functions for pid file creation and removal to a separate package in the `/pkg` directory called `pidfile`.  It would be a clean api if we used a type that could have the removal in a `defer` by the caller.

```go
import "github.com/docker/pkg/pidfile"

file, err := pidfile.New(path)
if err != nil {
// handle
}
defer file.Remove()
```

**Comment by RickWieman** [comment]
I would like to work on this. I don't have much experience with Go, but it seems like a nice improvement to begin with.
