### ISSUE TITLE
Delete unix sockets on daemon shutdown

### ISSUE THREAD

**Issue by tiborvass** [docker/docker#10969]
**Summary**: 

The daemon used to clean up its unix sockets after #6962 got merged, but there was a regression in #7317 and now it's not the case anymore.

**Proposed solution**:
Implement `removeUnixSockets` as a method on `Daemon` and call it during daemon shutdown.

**Comment by gewoonrik** [comment]
Sockets where moved out of Daemon in this commit:
https://github.com/docker/docker/commit/1d10c55aec891df609d36c90ee6c30adb24c16c4
shouldn't the removeUnixSockets be implemented somwhere else?
