### ISSUE TITLE
[integration-cli] [--net none] Fix TestPullImageOfficialNames

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#10967]
Fix TestPullImageOfficialNames so it will still be a functional test, but will pass when the test container has --net none.

Use the local registry in the container to pull an image. 

Error output when tests are run with --net none:
```
--- FAIL: TestPullImageOfficialNames (0.32s)
	docker_cli_pull_test.go:120: pulling the 'docker.io/hello-world' image from the registry has failed: exit status 1
	docker_cli_pull_test.go:120: pulling the 'index.docker.io/hello-world' image from the registry has failed: exit status 1
	docker_cli_pull_test.go:120: pulling the 'library/hello-world' image from the registry has failed: exit status 1
	docker_cli_pull_test.go:120: pulling the 'docker.io/library/hello-world' image from the registry has failed: exit status 1
	docker_cli_pull_test.go:120: pulling the 'index.docker.io/library/hello-world' image from the registry has failed: exit status 1

```

**Comment by brahmaroutu** [comment]
@jfrazelle I have renamed the test to use local registry and also changed code to load a saved registry image. Few issues - 1. Where do we download the registry image from(over 150MB, docker pull registry && docker save registry | gzip > integration-cli/registry.tar.gz)? 2. docker load takes time and starting the V1 registry server is slow and I had a sleep to make the test pass. 
Tried building the registry locally from source code and that is time consuming and have dependencies that may need network.
Please let me know your suggestions.

**Comment by ahmetalpbalkan** [comment]
might @tianon's #11119 help here?

**Comment by brahmaroutu** [comment]
@ahmetalpbalkan I have tries two path here, 1) download docker_registry v1 and then build like we do busybox, this  takes lots of time. 2) have saved image checked in into integration-cli (because we do not have network), the image is 150MB if it is zipped and github does not allow it to be checked in unless we split it. But at the same time I want to know if we really want to check this in.
    Once I have clarity I can issue PR.

**Comment by tianon** [comment]
> might @tianon's #11119 help here?

Yes, yes, yes -- we definitely do not want to check in the registry v1 code, but #11119 would let us download it directly from the Hub in a deterministic way as-is instead.
