### ISSUE TITLE
[integration-cli] [--net none] Fix TestSearchOnCentralRegistry

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#10968]
Fix TestSearchOnCentralRegistry so it will still be a functional test, but will pass when the test container has --net none.

Use the local registry in the container to pull an image. Change the name of the test to reflect it is no longer pulling from the central registry.

Error output when tests are run with --net none:

```
--- FAIL: TestSearchOnCentralRegistry (0.08s)
	docker_cli_search_test.go:14: failed to search on the central registry: time="2015-02-11T23:25:57Z" level="fatal" msg="Error response from daemon: Get https://index.docker.io/v1/search?q=busybox: dial tcp: lookup index.docker.io on 8.8.8.8:53: dial udp 8.8.8.8:53: network is unreachable" 
		, exit status 1
```

**Comment by grubernaut** [comment]
#dibs
