### ISSUE TITLE
Automated build creation needs UI to select a repo from a github org

### ISSUE THREAD

**Issue by rlister** [docker/docker#10960]
User `user` in both docker hub and github organization `org` wishes to create an automated build from `github.com/org/repo`, but the page at https://registry.hub.docker.com/builds/github/select/ only presents repo list from `github.com/user`, even though user has full access to `github.com/org`.

It is possible to hack this by selecting e.g. `github.com/user/repo` and then changing the page url `https://registry.hub.docker.com/builds/github/user/repo/` to `https://registry.hub.docker.com/builds/github/org/repo/`.

It would seem more reasonable for the initial build page to show all orgs and repo of which user is a member.

**Comment by thaJeztah** [comment]
Hello @rlister, since this is a feature request for the Docker Hub, could you create a feature request via http://support.docker.com or sending an email to support@docker.com?

Issues with Docker Hub are not handled through this issue tracker.

Thank you!

**Comment by rlister** [comment]
Emailed support, thanks.
