### ISSUE TITLE
Move TreeSize function to separate /pkg dir

### ISSUE THREAD

**Issue by crosbymichael** [docker/docker#10970]
**Summary**: 

Currently there is code in `/utils/utils_daemon.go` to handle getting the size of a directory specified by a path.  This `utils` package is too large and needs to be broken up.

**Proposed solution**:

Move the `TreeSize` function into a separate package inside `/pkg` called `directory`.  The build tag at the top of this file will need to be changed from `// +build daemon` to `// +build linux` as it uses `syscall.Stat_t` which is a linux only type.  Because of the new directory the function name can be changed to `Size`.

**Comment by MartijnDwars** [comment]
I'll start working on this.
