### ISSUE TITLE
Incorrect path docker/libcontainer/network

### ISSUE THREAD

**Issue by dwitzig** [docker/docker#10976]
Since this (https://github.com/docker/libcontainer/pull/367) merge in docker/libcontainer
the following paths are incorrect 
https://github.com/docker/docker/search?utf8=✓&q=%22github.com%2Fdocker%2Flibcontainer%2Fnetwork%22

**Comment by estesp** [comment]
Until the libcontainer:api branch is merged to libcontainer's master, and then the work is done in docker to use the new API, you won't see the changes in docker/docker repo--it currently vendors a specific git commit of libcontainer and is only updated at stable intervals when those features are ready to go into docker (see https://github.com/docker/docker/commit/fd2d45d7d465fe02f159f21389b92164dbb433d3 )
