### ISSUE TITLE
Concurrent docker pull, end of stream

### ISSUE THREAD

**Issue by florentvaldelievre** [docker/docker#10981]
Problem: The stream end on the second pull (tty2) even though it should return the same error as tty1
INFO:  The daemon has been setup as insecure en purpose in order to trigger an error

On a machine, i have two tty, 1 and 2. Try to launch these two commands almost at the same time.
On tty 1 I launch: docker pull registry2:5000/thumbor:4.7.0-37
````
FATA[0002] Error: Invalid registry endpoint https://registry2:5000/v1/: Get https://registry2:5000/v1/_ping: EOF. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry registry2:5000` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/registry2:5000/ca.crt
````
on tty 2, I launch: docker pull registry2:5000/thumbor:4.7.0-37
````
Repository registry2:5000/thumbor already being pulled by another client. Waiting.
````
However, it ends straight away. I was expecting to have the same error as tty1.

**Comment by jfrazelle** [comment]
@dmcgowan @dmp42 can you resolve

**Comment by dmp42** [comment]
@florentvaldelievre are you able to pull that image with just one docker pull?

Is this about having the same error when things go wrong like they do here? Or about allowing simultaneous pull of the same image?

**Comment by florentvaldelievre** [comment]
Actually, when docker daemon replies "Repository XXX already being pulled by another client. Waiting.", i was expecting to have some kind of queue mecanism for this request until a slot get free.

Example:
1)If we try to pull and there is already an existing pull of the same image:
=> "Repository XXX already being pulled by another client. Waiting." : Working as expected

2) When the first pull is finished and a slot is free, the pull request should get picked and attempt to download the image.

At the moment, it is waiting, and when a slot is free, it just quit the stream, without doing anything. 

You can easilly reproduce the problem:

tty1: docker pull busybox => Downloading
tty2: docker pull busybox => "Repository busybox already being pulled by another client. Waiting."

When tty1 finishes downloading the image, tty2 is just ending the stream

**Comment by jfrazelle** [comment]
closing as dup https://github.com/docker/docker/issues/8385
