### ISSUE TITLE
Question about apt-get in Debian base images

### ISSUE THREAD

**Issue by schmunk42** [docker/docker#10987]
I received this ticket https://github.com/phundament/docker/issues/3 in my project.

So I investigated the issue and saw this code and comments in the debian base image:

```
# Note that we do realize this isn't the ideal way to do this, and are always
# open to better suggestions (https://github.com/docker/docker/issues).
# Since Docker users using "RUN apt-get update && apt-get install -y ..." in
# their Dockerfiles don't go delete the lists files afterwards, we want them to
# be as small as possible on-disk, so we explicitly request "gz" versions and
# tell Apt to keep them gzipped on-disk.

# For comparison, an "apt-get update" layer without this on a pristine
# "debian:wheezy" base image was "29.88 MB", where with this it was only
# "8.273 MB".

Acquire::GzipIndexes "true";
Acquire::CompressionTypes::Order:: "gz";
# In Docker, we don't often need the "Translations" files, so we're just wasting
# time and space by downloading them, and this inhibits that.  For users that do
# need them, it's a simple matter to delete this file and "apt-get update". :)

Acquire::Languages "none";
```

What I didn't find was `RUN echo "Acquire::http {No-Cache=True;};" > /etc/apt/apt.conf.d/no-cache` - although it's discussed here: https://github.com/docker/docker/issues/824

My question is - do we don't need this, since it only adds an No-Cache header to APT http requests or is it missing or did I simply not find it?

**Comment by cpuguy83** [comment]
cc @tianon, ps there is a repo for the debian image here: docker-library/debian

**Comment by tianon** [comment]
The Debian image is generated via https://github.com/docker/docker/blob/d0bc3537d7cc7f152842c7d21c9eae85e0a95a4c/contrib/mkimage/debootstrap.  The PR/context you're looking for is #2038, which is where we removed `No-Cache=true` since it wasn't doing at all what we originally thought it was supposed to (and has more to do with proxies).

**Comment by schmunk42** [comment]
Thanks for your feedback, that made it clear to me.
