### ISSUE TITLE
docker 1.5.0 push returns EOF if no 'X-Registry-Auth' header is specified

### ISSUE THREAD

**Issue by jgangemi** [docker/docker#10983]
i'm using the docker-maven-plugin (https://github.com/rhuss/docker-maven-plugin) to push to a private, local test registry that doesn't require any authentication. if no `X-Registry-Auth` header is specified, the server returns an unhelpful EOF message which then requires some manual investigation to figure out why.

here are the relevant logs:

```
[DEBUG] http-outgoing-1 >> POST /v1.15/images/172.16.116.139%3A5000%2Fjgangemi%2Ftest-app/push?tag=0.0.13-SNAPSHOT HTTP/1.1
[DEBUG] http-outgoing-1 >> Accept: */*
[DEBUG] http-outgoing-1 >> Content-Type: application/json
[DEBUG] http-outgoing-1 >> Content-Length: 0
[DEBUG] http-outgoing-1 >> Host: 172.16.116.139:2375
[DEBUG] http-outgoing-1 >> Connection: Keep-Alive
[DEBUG] http-outgoing-1 >> User-Agent: Apache-HttpClient/4.3.6 (java 1.5)
[DEBUG] http-outgoing-1 >> Accept-Encoding: gzip,deflate
[DEBUG] http-outgoing-1 >> "POST /v1.15/images/172.16.116.139%3A5000%2Fjgangemi%2Ftest-app/push?tag=0.0.13-SNAPSHOT HTTP/1.1[\r][\n]"
[DEBUG] http-outgoing-1 >> "Accept: */*[\r][\n]"
[DEBUG] http-outgoing-1 >> "Content-Type: application/json[\r][\n]"
[DEBUG] http-outgoing-1 >> "Content-Length: 0[\r][\n]"
[DEBUG] http-outgoing-1 >> "Host: 172.16.116.139:2375[\r][\n]"
[DEBUG] http-outgoing-1 >> "Connection: Keep-Alive[\r][\n]"
[DEBUG] http-outgoing-1 >> "User-Agent: Apache-HttpClient/4.3.6 (java 1.5)[\r][\n]"
[DEBUG] http-outgoing-1 >> "Accept-Encoding: gzip,deflate[\r][\n]"
[DEBUG] http-outgoing-1 >> "[\r][\n]"
[DEBUG] http-outgoing-1 << "HTTP/1.1 500 Internal Server Error[\r][\n]"
[DEBUG] http-outgoing-1 << "Content-Type: text/plain; charset=utf-8[\r][\n]"
[DEBUG] http-outgoing-1 << "Date: Tue, 24 Feb 2015 16:24:17 GMT[\r][\n]"
[DEBUG] http-outgoing-1 << "Content-Length: 4[\r][\n]"
[DEBUG] http-outgoing-1 << "[\r][\n]"
[DEBUG] http-outgoing-1 << "EOF[\n]"
[DEBUG] http-outgoing-1 << HTTP/1.1 500 Internal Server Error
[DEBUG] http-outgoing-1 << Content-Type: text/plain; charset=utf-8
[DEBUG] http-outgoing-1 << Date: Tue, 24 Feb 2015 16:24:17 GMT
[DEBUG] http-outgoing-1 << Content-Length: 4
```

it would get great if a better error message could be returned in this case.

on a separate but related note, is there any harm in always sending the header w/ empty encoded values if the user doesn't specify any actual credentials?

**Comment by dmp42** [comment]
ping @dmcgowan

**Comment by dmcgowan** [comment]
The error messages to the registry don't seem to very informative much of the time, it can certainly be improved. For V2 we attempted to address this better as well as ensure there is proper debug logging on the deamon.  Can you send the daemon logs to see if anything informative is showing up while in Debug mode?  Run the daemon with `docker -d -D`.

**Comment by jgangemi** [comment]
this is the output from the docker daemon:
```
DEBU[0045] Calling POST /images/{name:.*}/push          
INFO[0045] POST /v1.15/images/172.16.116.139%3A5000%2Fjgangemi%2Ftest-app/push?tag=0.0.13-SNAPSHOT 
ERRO[0045] Handler for POST /images/{name:.*}/push returned error: EOF 
ERRO[0045] HTTP Error: statusCode=500 EOF               
```
please let me know if there is anything else i can provide.

also, what about the question i posed above? if i am attempting to push to a private repository, is there any harm in always sending the header w/ empty encoded values?

**Comment by HuKeping** [comment]
Two ways to get ride of this EOF:
1. push image with a X-Registry-Auth Header and no matter what it is. (X-Registry-Auth:123 is ok)
2. push image with a proper Body say, {"username":"docker"}. In this case u can success without the X-Registry-Auth.

The 2-way is to support for compatibility if there was no authConfig header.

Agree with @dmcgowan the error messages don't seem to very informative. I can update it if everyone is OK about that.

**Comment by HuKeping** [comment]
Given the API docs specify this difference 
http://docs.docker.com/reference/api/docker_remote_api_v1.5/#push-an-image-on-the-registry
v.s.
http://docs.docker.com/reference/api/docker_remote_api_v1.4/#push-an-image-on-the-registry

Since docs_v1.5 the X-Registry-Auth Header was recommend, should we remove the old behavior that populated AuthConfig from http-body now or still keep them but give out some more detail message when error happen?

**Comment by Magnuti** [comment]
At least with Azure Container Registry my error was caused by not having enabled admin in ACR. In the Azure portal the admin toggle says that
> "If enabled, you can use the registry name as username and admin user access key as password to docker login to your container registry."

Either set this manually in the Azure portal or set `admin_enabled = true` on the `azurerm_container_registry` resource in your `.tf` file.

<img width="574" alt="image" src="https://github.com/moby/moby/assets/43852515/7acec0de-7b25-42a1-bc8c-070baf93b3a0">
