### ISSUE TITLE
Boot2Docker Install/Uninstall Issues on Win8.1

### ISSUE THREAD

**Issue by BGaudreault** [docker/docker#10993]
Hi, does anyone have a suggestion on how to fix a Win8.1 install issue where the VM/daemon doesn't start?

I installed boot2docker on Windows 8.1, but then removed it (not all components were removed and it didn’t tell me "what" had to be manually removed or "where" to find a log!) and reinstalled it after rebooting so I could document the process for users.  Now I can’t get boot2docker to start like it did originally.  I see the line “Waiting for VM and Docker daemon to start…” and then I see another line that looks like “……………………………………………………………………………………………………………………………………………………ooooooooooooooooooo” which just keeps displaying more “o”’s and it has been doing this for >45min!

**Comment by thaJeztah** [comment]
Hi, @BGaudreault this issue tracker is for issues related to docker only, issues with Boot2Docker can be created in the issue tracker for Boot2Docker here; https://github.com/boot2docker/boot2docker

However, this looks more like a support question. Perhaps you can ask this question on IRC in the #docker or #boot2docker channel first? Thanks!
