### ISSUE TITLE
Docker on Windows/Windows Azure

### ISSUE THREAD

**Issue by ravi032** [docker/docker#11009]
I am new to docker and have some questions for docker related to Microsoft Windows technologies.

Can docker create a Windows OS container? Can I install IIS inside my Windows OS container?

Kindly reply me with yes or no.
If yes, then kindly explain to me how do I do it? Share some tutorial links etc.

**Comment by jfrazelle** [comment]
This is currently being worked on by the Windows team, see http://azure.microsoft.com/blog/2014/10/15/new-windows-server-containers-and-azure-support-for-docker/
