### ISSUE TITLE
Issue with using su error 'su - System error'

### ISSUE THREAD

**Issue by IevgenKabanets** [docker/docker#11015]
My setup is:

Host system is Ubuntu 14.04 (*Linux vamspacker01 3.13.0-32-generic-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux*) with **3.13.0-32-generic kernel**.

- Packer 0.7.5;
- Docker 1.3.3;
- Ubuntu 14.04 official image for Docker;

Whether I use Packer or not - issue is the same.

1 -> I run a new container of Ubuntu image, lets say this way:

*docker run -P -i -t -d --privileged=true --net=host --name="ubuntu_test" ubuntu:latest /bin/bash*

2 -> Then, if I need to change user:

*su postgres* --> I get

**su: System error**

Something alike was seen in here (https://github.com/docker/docker/issues/6345).

I'm not a guru of strace, that's why can't add anything more about troubleshooting, so just basics. 

Here's output:

*root@vamspacker01:~# docker -D info
Containers: 4
Images: 9
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 17
Execution Driver: native-0.2
Kernel Version: 3.13.0-32-generic
Operating System: Ubuntu 14.04.1 LTS
Debug mode (server): false
Debug mode (client): true
Fds: 26
Goroutines: 24
EventsListeners: 0
Init Path: /usr/bin/docker*

**Comment by jfrazelle** [comment]
Why are you using `su` to run it.

**Comment by jfrazelle** [comment]
If you want to run as a different user in a container I would suggest using USER in the dockerfile instead http://docs.docker.com/reference/builder/#user

**Comment by jfrazelle** [comment]
How are you creating the postgres user? Can you give exect steps to reproduce?

**Comment by IevgenKabanets** [comment]
Ok, 

*postgres* is created by installing PostgreSQL server.

I don't want to run as different user - I want possibility to *switch* users, for example.

Another example - Tomcat 7 init.d script. It uses su -c to launch startup.sh/shutdown.sh.

**Comment by jfrazelle** [comment]
closing as dup of https://github.com/docker/docker/issues/5899 sorry i didnt see this before

**Comment by BinitaBharati** [comment]
su command will work if you use Ubuntu Xenial instead of Trusty. I faced the same issue, and the eror went away, once I upgraded mu Ubuntu version to Xenial.
