### ISSUE TITLE
Makefile and make.sh don't have the same "targets" they should

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#11019]
**Summary**: Users can run `make test` but  have to run `make.sh binary cross test-unit test-integration test-integration-cli test-docker-py`. There might be other differences.

**Proposed solution**:

The `make.sh` command should accept arguments with the equvalent values to the make targets.  This should improve the UX and also reduce complexity in doc management. Win-win.

**Comment by jfrazelle** [comment]
wdym they do?

you can run `hack/make.sh any_of_the_things_` the makefile just holds the common ones

**Comment by cpuguy83** [comment]
@jfrazelle Can run `hack/make.sh test`

**Comment by jfrazelle** [comment]
oooo i misunderstood sorry

**Comment by jfrazelle** [comment]
I still dont know tho, I think that is abstracting it a bit too far, the makefile is the abstraction i like seeing via the makefile what is actually running

**Comment by cpuguy83** [comment]
The Makefile is the docker-based abstraction, make.sh is the shell level.

**Comment by moxiegirl** [comment]
So, I'm not sure everyone has Makefile experience. So, reading a Makefile to investigate the targets is a bit heavy duty.  

As a newb, I was told use `make` on local host and `project/make.sh` in my container.  So, I just assumed they would have equivalency --- I'm not sure that is an unexpected assumption.  

If the goal is to lower the bar for contributing, this would be a nice easy step.  Lots of shell scriptors out there so might be a cool lil task for the birthday.

**Comment by jfrazelle** [comment]
no totally as lot as we have both :D and the makefile shows exactly what is
being executed still :)

**Comment by jfrazelle** [comment]
closing because of the comment here https://github.com/docker/docker/pull/11742#issuecomment-94945973
