### ISSUE TITLE
Docker client does not handle HTTP 401 responses properly

### ISSUE THREAD

**Issue by g17** [docker/docker#11016]
# Context

I am running a private Docker registry ([h3nrik/simple-registry](https://registry.hub.docker.com/u/h3nrik/simple-registry/)). On top an nginx authentication proxy is running ([h3nrik/registry-ldap-auth](https://registry.hub.docker.com/u/h3nrik/registry-ldap-auth/)). That proxy enforces the username to match the image namespace when creating or deleting tags. That works so far without any problems.

# Problem description

When I now use the Docker client to push an image with a namespace that does not match the username the proxy returns an HTTP 401 response. But the client does not show any error message it just ends unexpectedly with a return code 1:

	$ docker push registry.local/invaliduser/myimage:latest
	The push refers to a repository [registry.local/invaliduser/myimage] (len: 1)
	Sending image list
	$ echo $?
	1

# Expectation

I would expect the client to display a proper error message because the [Docker Registry API specification](https://docs.docker.com/reference/api/registry_api/) explicitly lists a possible HTTP 401 error for those two requests (and also for others but these are the only ones that I have tested so far):

	DELETE /v1/repositories/(namespace)/(repository)/tags/(tag*)
	PUT /v1/repositories/(namespace)/(repository)/tags/(tag*)

# Environment

	$ docker info
	Containers: 1
	Images: 16
	Storage Driver: aufs
	 Root Dir: /mnt/sda1/var/lib/docker/aufs
	 Backing Filesystem: extfs
	 Dirs: 18
	Execution Driver: native-0.2
	Kernel Version: 3.18.5-tinycore64
	Operating System: Boot2Docker 1.5.0 (TCL 5.4); master : a66bce5 - Tue Feb 10 23:31:27 UTC 2015
	Debug mode (server): true
	Debug mode (client): false
	Fds: 19
	Goroutines: 21
	EventsListeners: 0
	Init Path: /usr/local/bin/docker

**Comment by duglin** [comment]
@g17 is this still an issue? When I tried it I do see a nice error message now but I may be doing it slightly differently than you

**Comment by g17** [comment]
@duglin It seems to be fixed with 1.6.0. Now I get a proper error message:

     Sending image list
     FATA[0003] Authentication is required.

**Comment by duglin** [comment]
cool - thanks for checking. Will close this issue.
