### ISSUE TITLE
Issue running RabbitMQ with Dockers. - incorrect file ownership on mounted volumes

### ISSUE THREAD

**Issue by bdastur** [docker/docker#11010]
Summary:
I am facing an issue currently when trying to run a RabbitMQ service within a docker container. The issue is related to the file ownership of  "erlang.cookie" file that rabbitmq-server creates.

This is how I start the container:
sudo docker run -p 5672:5672 -p 15672:15672 --volume=/var/lib/rabbitmq/:/var/lib/rabbitmq --volume=/dockers/rabbit:/dockers/rabbit/
--privileged=true --name=rdock --net=host e6ec78b4241f /dockers/rabbit/start.sh 

I am mounting the /var/lib/rabbitmq/ directory from the host, so that the cookie is accessible by other docker containers running rabbitmq service. This enables it to form a rabbitmq cluster.

The issue:
-----------------
What I see is that the ownership of the file is:
-r--------.  1  998 docker   20 Feb 24 16:00 .erlang.cookie
drwxr-xr-x.  2  998 docker   30 Feb 24 18:55 mnesia

The correct ownership should be:
-r--------.  1 rabbitmq rabbitmq     20 Feb 25 00:00 .erlang.cookie
drwxr-xr-x.  4 rabbitmq rabbitmq     85 Feb 25 00:54 mnesia

I saw similar threads, but most were discussing issues with OSX or VBOX mounted fs, not sure if this is a known issue and a duplicate, but with this behavior I cannot use dockers to create a rabbitmq cluster.

**Comment by alapidas** [comment]
This may have to do with the UID and GID of the rabbit user in the containers.  The process in the container is probably mutating those files and changing ownership.  Try starting bash in your bash in your rabbit container and see what UID and GID the rabbit user + group has.  I'd be willing to bet the GID is '20' and the UID matches your local docker user's UID.

**Comment by bdastur** [comment]
What I see is the following from the bash prompt within the rabbit container:
UID: 998, GID: 997
[root@gg34-3 ~]# docker exec -it rdock /bin/bash
[root@gg34-3 /]# 
[root@gg34-3 /]# id -u rabbitmq
998
[root@gg34-3 /]# id -g rabbitmq
997
[root@gg34-3 /]# 

You are correct, the rabbitmq-server will create the .erlang.cookie and mnesia directory in /var/lib/rabbitmq, and the correct ownership should be "rabbitmq:rabbitmq".

**Comment by alapidas** [comment]
From the perspective of the container, the ownership is correct.  If you have another rabbit process outside the container or in a different container that needs to use these files, then the UID and GID of the rabbit account needs to be the same everywhere.

**Comment by bdastur** [comment]
Thanks a lot for your insight. My "docker" group GID on host was overlapping with my "rabbitmq" group on the container, which was causing the problem. After chaning my "docker" group GID to something else, it works.
