### ISSUE TITLE
docker hello-world

### ISSUE THREAD

**Issue by kordless** [docker/docker#11022]
Several pages, including https://docs.docker.com/installation/mac/ mention running the following command:

    docker hello-world

This actually results in an error: 

    superman:~ kord$ docker hello-world
    Error: Command not found: hello-world

Might want to check the docs for that string and fix!

**Comment by jfrazelle** [comment]
this is fixed in the docs built from master you will see it in the main docs soon sorry about the inconvenience

**Comment by jfrazelle** [comment]
http://docs.master.dockerproject.com/installation/mac/
