### ISSUE TITLE
Proposal: Storage Interfaces for Docker

### ISSUE THREAD

**Issue by jvinod** [docker/docker#11020]
## Abstract

The intention of this proposal is to present a storage management API for Docker. This does not rework the internals of Docker but lays the groundwork for new storage primitives, Docker plugins, and alternate implementations by external storage providers. This aligns with spirit of treating storage as entities managed outside of containers as outlined in this wonderful PR  https://github.com/docker/docker/pull/8484.

This introduces a storage entity named "dVol" (Docker Volume) as a directly-addressable top-level entity. *dVols* have their own properties, such as class of service, size etc and are attached to containers as data volumes as well as *image* volumes. The nomenclature *dVol* is used to disambiguate with the current semantics of "Volumes", which is only applicable to data volumes in Docker. In its actual implementation, it may merge with the docker volumes.

This proposal identifies a set of functionality provided by dVol and specifies an API to be implemented by third party storage providers. It outlines usage from Docker CLI and graphdriver plugins, and specifies interactions with the scheduler, so that scheduling of containers is aware of storage requirements, 

The implementation of dVols could come from scale-out distributed block solution, direct attached disks, EBS in AWS, a distributed file system, or a local filesystem. A dVol driver implemented to manage local filesystem directories can ensure backward compatibility with existing use of docker volumes.

## Background and Motivation

Storage for docker *images* comes from a shared namespace in a single filesystem on the host. The lifetime of modifications to the image root fs is tied to the lifetime of the container. The visibility and accessibility is restricted to a single node, and a container is forced to use the format and features of the host.

Docker also give the ability to setup *data* volumes. These are directories within the namespace of a container that can be shared by other containers. These can be directories within the host filesystem that is mounted in the container namespace.  The lifetime of data volumes is that of the last container that references it. The visibility and accessibility is restricted to a single node.

This PR addresses the issue around decoupling a container's namespace from the local host's filesystem thereby allowing for 3rd party storage providers to provide alternate implementations for hosting a container's data and image.  Such an implementation may be local or remote, for example on a shared SAN or NAS.  This will pave the way for hosting stateful containers, and providing specialized storage services for stateful containers, such as tiering, caching services and snapshots.

## dVols

dVols are opaque entities, addressed by globally unique ID and tagged with user-defined labels. dVols provide storage for both data as well as image. They encapsulate underlying device composition (SSD/SATA) and geographic device location including data-center/rack/machine. They have initial capacities, possibly thin provisioned, max usage can be enforced and may optionally be resized. dVols implement storage operations such as snapshots, new dVols can be created from existing snapshots. You can enumerate dVols in the system and their associations to containers. You can enumerate snapshots by dVol ID or by tag. dVols have stats and can have alerts. All the storage operations are at the granularity of dVols and when dVols are associated with a container image, the storage operations are now at container granularity. 

At a high level, third party storage providers implementing dVols can enable:

* Fast Loading of container images
* Mobility for stateful containers
* HA and fault tolerance for data
* Storage operations (such as snapshots and clones) at container granularity
 

### API

``` go
type DVolDriver interface {

    // Create a new dVol for the specific DVolConfig.
    // Returns a system label that uniquely identifies the dVol in the system
    Create(locator DVolLocator, config DVolConfig) (dVolLabel SystemLabel, err error)

    // CreateFromSnap same as Create except that the dVol is initialized from a snapshot
    CreateFromSnap(locator DVolLocator, config DVolConfig, snapLabel SystemLabel) (dVolLabel SystemLabel, err error)

    // Attach dVol to the host.
    // On success the devicePath specifies location where the device is exported
    // Returns an error if the dVol is already attached or if dVolLabel doesn't exist
    Attach(dVolLabel SystemLabel) (devicePath string, err error)

    // Detach dVol from the host.
    // Returns an error if the dVol is not attached.
    Detach(dVolLabel SystemLabel) (err error)
    
    // Inspect dVol.
    Inspect(dVolLabel SystemLabel) (dVol DVol, err error)

    // Delete dVol.
    // This will return an error if there are any snaps associated with the dVol.
    Delete(dVolLabel SystemLabel) (err error)
    
    // Enumerate dVols that map to the dVolLocator. Locator fields may be regexp.
    // If locator fields are left blank, this will return all dVols.
    // If err is set to ErrEagain then the call should be retried with a zero cursor
    Enumerate(locator DVolLocator, cursor *Cursor, dVols []DVol) (count int, err error)

    // Snapshot specified dVol. IO to the underlying dVol must be quiesced before
    // calling this function.
    // On success, a system generated label is returned.
    Snapshot(dVolLabel SystemLabel, snapLabel string) (snap SystemLabel, err error)

    // SnapDelete deletes specified snapshot.
    SnapDelete(snapLabel SystemLabel) (err error)
    
    // SnapInspect inspect snapshot.
    SnapInspect(snapLabel SystemLabel) (snap DVolSnap, err error)

    // SnapEnumerate enumerate snaps for specified dVol
    // Count indicates the number of snaps populated.
    // If err is set to ErrEagain then the call should be retried with a zero cursor
    SnapEnumerate(locator DVolLocator, cursor *Cursor, snaps []DVolSnap) (count int, err error)
    
    // Stats Retrieve dVol stats
    Stats(dVolLabel SystemLabel) (stats DVolStats, err error)
    
    // Alerts Retrieve dVol alerts
    Alerts(dVolLabel SystemLabel) (stats DVolAlerts, err error)
}   
```
#### DVol Identfiers

SystemLabel is a system generated globally unique identifier for dVols and snapshots. 

#### DVol Locators
A DiskLocator is a user generated string identifying a dVol, these need not be unique and can be used in search/enumerate functions. This is typically the container imageid:label. This punts the management and mapping of container image dVols to the DVolDriver.

#### DVolConfig
This is the specification of the backing datastore. It contains the following fields:
* Size: Thinly provisioned size of the volume
* HALevel : An integer value specifying the number of nodes that are allowed to fail and yet data be available. A value of 0 implies that data is not erasure coded. Failure of a single node will lead to data unavailability.
* Tiering: A boolean value specifying if tiering is required across SSD/SATA
* DeviceComposition: specifies preference for SATA/SSD or a combination of both.
* CoS: A number between 1..9 specifying class of service relative to IO on other dVols
* Dedupe: A boolean value specifying if dedupe is to be enabled.

Based on feedback from this PR, we plan to submit a separate proposal for what a DVolConfig would look like and some suggestions on where this information could go.  We suspect that this would go with other information that a container would need, for example around networking properties

#### DVol

A runtime summary of DVol, gives information about hosts that contain the data, free space, and attached container. This information is used by scheduling and diagnosis/monitoring software. 

### Usage

The frontend for dVols management is an augmented version of 'docker volume' CLI in proposal https://github.com/docker/docker/pull/8484. The CLI would take an additional argument of --dvol-provider <port> that delegates storage management to an external provider. Once a dVol is attached on the host filesystem, it can then be mounted in the container's namespace.  This will also allow for a container to have its own filesystem that is separate from the host's filesystem.

In the case of container images, the creation/attach/detach of dVols is done via the graphdriver interface. A simple implementation uses the local filesystem for the container rootfs and the dVol becomes the uppermost writeable layer of the container filesystem. One way to achieve this is a modified version of the overlayfs driver that creates the dVol as the 'upper' layer. The lifetime of the dVol is not tied to the lifetime of the container. All the operations available via 'docker volume' is available on the container image dVol. 

### Scheduler Interaction

Schedulers cannot be storage agnostic, they are fundamentally interconnected and need to work together to ensure an optimal runtime environment. Here is why:

* Data locality: Ideally, containers should be scheduled to run on the same node where their data lives. dVols can be queried to list their underlying node and device topology to serve as predicates for container scheduling.

* Data containers: Containers sharing dVol need to be scheduled on the same machine. This restriction doesn't exist if the underlying dVol is implemented as a distributed filesystem.

* Inter-container IO resource management: Another input to the scheduler is learned IO patterns and workload inference. Armed with this information, the scheduler can distribute containers based on their workload for optimal distribution of IO across the aggregate spindles in the cluster while keeping the data access local.

The information above is inferred from a call to 'Inspect(dVolLabel SystemLabel)'

### Image Format

Information that goes into DVolConfig needs to come from somewhere. It can come from a higher level specification of what storage a container requires to run such as *docker compose* or from the image format or from both with compose overriding the image format. The proposal here is to include a DVolConfig specification in the image json including filesystem and blocksize preferences.  

### Backward compatibility

A dVol driver implementation that carves out volumes as directories in the local filesystem can provide an implementation that is  backward compatible to existing docker volume implementation.

### Future work

The proposal is a starting point and we hope clarity and details will emerge from a community discussion. One of the pending items is to group together containers for storage related operations:

* Container Links:
The storage driver or a higher entity needs to understand related containers.  This will allow for end users to apply storage actions on a set of related containers.  For example, the user can take a "compose" level snapshot, which will snap all containers in the same compose specification in a consistent state.  

### Reference implementation

Coming Soon!

**Comment by cpuguy83** [comment]
@jvinod So, can you take a look at https://github.com/cpuguy83/docker/blob/volume_drivers/volumes/volumedriver/driver.go

The idea here is to move the current implementation into drivers, and then we can add new drivers (ie, ceph, gluster, nfs, fuse, <whatever>).
The interface is not final (or even really tested, just a placeholder for something better at the moment)

This will be coupled with #8484 to provide a management interface.

**Comment by jvinod** [comment]
@cpuguy83 I took a look at that interface... I think the fundamental motivation is well aligned.

This PR is perhaps an evolution on your original PR and is a stab at defining a more comprehensive pluggable storage management interface with somewhat different semantics. It doesn't assume block or file as the underlying storage provider, and is designed from the point of view of an application's requirements of it's storage (DVolConfig).  Doing it this way allows a container to declare it's own filesystem, or apply operations such as snaps, clones etc at a container granularity.

By keeping this API at a volume or device management level allows for Docker remove itself from the underlying management of the bits.  For example having `Export` to return the volume data could be expensive and avoided by doing clones or snaps at a volume level and then attaching them to another container.  

The operations on the volume are defined from the point of view of a block/file agnostic semantics.  It is to be used for storage backends for both data and writeable image layer. It also captures dependencies with the scheduler and the image format.

**Comment by ajauch** [comment]
Two questions/comments:

1)  Why are you asking the user to specify the --dvol-provider?  Doesn't that break the platform agnostic nature of the current CLI?  It seems that this would require the user to understand what underlying platform provider they are using.  I would prefer a new CLI command that allows admins to configure the providers and map them to volumes.  Think about the way Cinder works.

2)  Again, looking at Cinder they have a way to pass optional meta-data to the backend.  Many storage platforms have an array of data services that they can provide.  There should be a way for advanced users to pass these preferences along to the back end by means of attaching custom meta-data to the transaction.  Something like the extra-spec in OpenStack would work nicely.

**Comment by cpuguy83** [comment]
Closing since this is handled by the plugin API and #14242 
Thanks!
