### ISSUE TITLE
Proposal: Docker should be aware of Dockerfile changes

### ISSUE THREAD

**Issue by aanm** [docker/docker#11024]
Is it possible to have docker being aware when the Dockerfile was changed?
For example, if I have a Dockerfile inside a directory I would like to at least be warned that the Dockerfile was changed for the docker container that I'm trying to run.
Time line example:
- Create a Dockerfile
- Build using `docker build something`
- Run that image creating a container called `foo`, by doing `docker run --name foo something`
- Change that Dockerfile
- Run the same image `docker run --name bar something` shows: "Warning: Dockerfile was changed the image `something` could be outdated", but the container is created no matter what.

**Comment by jfrazelle** [comment]
what about git?

**Comment by aanm** [comment]
@jfrazelle what does git does?

**Comment by duglin** [comment]
@aanm as far as I know there is no link from the image back to the Dockerfile so doing this isn't possible right now.  The only hack I can think of is to do it via a Makefile where the output of the 'docker build' step doesn't just create the image but also touches a file (perhaps even exports the image as a tar), then you can setup a Makefile dependency between that 'touched' file and your Dockerfile.

**Comment by aanm** [comment]
@duglin What about 
```go
if Dockerfile.isPresentAndBelongsToImageOfContainerToBeRun && 
Dockerfile.lastModifiedDate > container.creationDate
 return "Warning..."
```

Still "hacky" or a good solution?

**Comment by duglin** [comment]
Not sure how we would get the `Dockerfile.isPresentAndBelongsToImageOfContainerToBeRun` value.  We can't assume its in the current dir, nor can we even assume its called Dockerfile.  Plus, how do you know _that_ Dockerfile was used to build the image that's being run? There's no metadata linking the two

**Comment by aanm** [comment]
@duglin Ups, you're right. Somehow I thought a Dockerfile contained a name/reference or something.
Maybe in the future

**Comment by duglin** [comment]
@aanm yea its a non-trivial thing to solve because the name of the image is only provided on the `docker build` command, or on the `docker tag` command run after the image is created - nothing in the dockerfile itself.  Which makes sense since the same dockerfile could be used to make any number of images/names.

**Comment by unclejack** [comment]
@aanm This really sounds like something you'd want to implement as part of a tool which calls `docker build` when that's needed.

**Comment by thaJeztah** [comment]
@aanm given the discussion above, do you think this issue can be closed?

**Comment by aanm** [comment]
Yep, thanks for the feedback
