### ISSUE TITLE
Docker stop with timeout takes a lot longer than without a timeout

### ISSUE THREAD

**Issue by danbeaulieu** [docker/docker#11021]
If we use the stop endpoint with a timeout of any value it takes atleast an extra 5-10 seconds to return, where as ommitting the timeout parameter (implied 10 second timeout )results in a much quicker stop.

This behavior can be seen for all values of t.
 ```
# time curl -X POST http://localhost:4243/v1.17/containers/379710092b76/stop

real	0m0.818s
user	0m0.003s
sys	0m0.015s

# time curl -X POST http://localhost:4243/v1.17/containers/927b56ac95e9/stop?t=5

real	0m5.734s
user	0m0.004s
sys	0m0.014s

# time curl -X POST http://localhost:4243/v1.17/containers/630a78d883d6/stop?t=20

real	0m7.476s
user	0m0.000s
sys	0m0.011s
```

**Comment by duglin** [comment]
@danbeaulieu I just tried this and I think its been fixed - please give it a try.

**Comment by thaJeztah** [comment]
The current release candidates can be found here; for testing: https://github.com/docker/docker/pull/11635#issuecomment-92482581

**Comment by duglin** [comment]
@danbeaulieu I'm going to close this because I think its been fixed.  If not please reopen.
