### ISSUE TITLE
docker run command does not notify of incorrect mac-address parameter format

### ISSUE THREAD

**Issue by jstangroome** [docker/docker#11027]
if a `--mac-address` parameter is specified to `docker run` and the MAC address is not in the expected format (ie '02:03:04:05:06:07') the container is still started with a 'random' MAC address and there is no error or warning presented to the user.

Example with bad address format and no errors:

```
$ sudo docker run --rm -ti --mac-address=025e89898989 ubuntu:trusty /bin/bash
root@e84bd0c1bb2f:/# ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:ac:11:00:1d
```

Example with good address format and correct result:

```
$ sudo docker run --rm -ti --mac-address=02:5e:89:89:89:89 ubuntu:trusty /bin/bash
root@292bfe4eb7d1:/# ifconfig
eth0      Link encap:Ethernet  HWaddr 02:5e:89:89:89:89
```

Happens on Docker version 1.5.0, build a8a31ef

**Comment by jfrazelle** [comment]
Solution for solving this issue would be a regex to validate mac-address before running the container.

**Comment by coolljt0725** [comment]
maybe #11037 can fix this
