### ISSUE TITLE
Installation instructions should lead with cURL to ensure latest Docker release

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#11023]
**Summary**: 

Installation via a package manager such as `brew`, `apt-get`, etc. can cause customers to be behind the official Docker release; sometimes causes confusion.

**Proposed solution**:

via Eric:
[What Google does](https://cloud.google.com/compute/docs/gcutil/#install) is a good practice here. They provide something convenient as well as manual instructions. I think this is what we should do. We should provide this for each OS as an option for running the latest release, in addition to instructions for running the supported version for that OS. The difference in support levels and whom that support originates should be clear..

**Comment by thaJeztah** [comment]
+1, I think there also was talk about having more explicit "channels", e.g. "release", "nightly", "canary" (but that might be out of scope for this).

FYI, there are instructions on how to install the latest docker maintained release for *some* distro's; [Ubuntu - Docker-maintained Package Installation](https://docs.docker.com/installation/ubuntulinux/#docker-maintained-package-installation), [CentOS - Manual installation of latest Docker release](https://docs.docker.com/installation/centos/#manual-installation-of-latest-docker-release), but not for all.

**Comment by moxiegirl** [comment]
I'm gonna take this one.
