### ISSUE TITLE
make test fail-pid xxx is not a child of this shell

### ISSUE THREAD

**Issue by zenlinTechnofreak** [docker/docker#11033]
I got a fail when I make test of my docker,just like:
![maketest](https://cloud.githubusercontent.com/assets/9923237/6387882/8bb5c726-bdcd-11e4-99b9-9eacad2a39f1.png)

then I try,
TESTFLAGS='-v -run TestGetContainerStats' make test-integration-cli
It runs well and return success.

also  I have try TESTFLAGS='-test.run \^TestBuild\$' make test
and it return success also.

In this situatioin,is it a real issue?

my run environment:
Client version: 1.5.0-dev
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 309eec2
OS/Arch (client): linux/amd64
Server version: 1.5.0-dev
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 309eec2

image:ubuntu:14.04

thx.

**Comment by jfrazelle** [comment]
See the error fails on linuxcontailers.org, their site is either down or
you don't have access to the Internet

**Comment by jfrazelle** [comment]
Also you can always check https://jenkins.dockerproject.com/job/Docker%20Master/ to see if our tests are passing on master

**Comment by jfrazelle** [comment]
Oh you changed the image, the fail is coming from somewhere above the screenshot, scroll up

**Comment by jfrazelle** [comment]
Happy to help let me know if you don't see it

**Comment by zenlinTechnofreak** [comment]
Sorry to  jfrazelle , I was away for other personal things.
I am so sorry to tell u that I cannot get where I have changed the image, can u help me to find out it?
Thx.

**Comment by jfrazelle** [comment]
Ok so even tho the
```
FAIL
Coverage 70.9% of statements
```
is at the bottom there is a test above that (out of view of the screenshot) that is failing
it should look something like this
https://s3.j3ss.co/screenshots/2015-02-26-09-55-12_4480x1440.png

**Comment by zenlinTechnofreak** [comment]
OK,I see the log,but I remember I never change the image before I built it.
Anyway, I will try to download a new source, and rebuilt it again to find out it.
Any other better suggestion?
THX.

**Comment by jfrazelle** [comment]
hmm well if it continues to fail, let me know what test it is and I can
help debug why :)
