### ISSUE TITLE
docker stats cpu issue

### ISSUE THREAD

**Issue by blackfader** [docker/docker#11035]
this cpu use get cgroup value，if i edit CPU_CFS_QUOTA_US ,this value is not match.

ex : i edit CPU_CFS_QUOTA_US equivalently 4 cpu core ， this show：

CONTAINER           CPU %               MEM USAGE/LIMIT     MEM %               NET I/O
b77ab7a67c5f        403.19%             1.135 GiB/8 GiB     14.18%              0 B/0 B

**Comment by jfrazelle** [comment]
I think this is the intended functionality, we read the dichroic stats so if you write to the file then yes it will change the value
