### ISSUE TITLE
Using docker run with config file 

### ISSUE THREAD

**Issue by PositiveAlex** [docker/docker#11041]
Hey,
I thought it would be great if we can use docker run with config.yaml propertyfiles or anything like that.

I can preconfigure all container links, env variables and other things in normal readable/modifyable format.

Then just `docker run --script link_group.yml`

This could be very usefult to stay away of long attributes (and repeated operations when running several containers together) passed everytime to the container when we run it. 

But anyways, that's again just a thought to discuss.

Thank you for your attention.

**Comment by jfrazelle** [comment]
Checkout github.com/docker/fig

**Comment by PositiveAlex** [comment]
@jfrazelle thank you very much :)

**Comment by jfrazelle** [comment]
This has been discussed in detail here https://github.com/docker/docker/issues/9694
