### ISSUE TITLE
Can not push new repo from local

### ISSUE THREAD

**Issue by kharayo** [docker/docker#11052]
bash-3.2$ docker push vser/mojolite
The push refers to a repository [vser/mojolite] (len: 1)
Sending image list
FATA[0003] Error: Status 403 trying to push repository vser/mojolite: "Access Denied: Not allowed to create Repo at given location" 
bash-3.2$ docker info
Containers: 10
Images: 61
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 81
Execution Driver: native-0.2
Kernel Version: 3.18.5-tinycore64
Operating System: Boot2Docker 1.5.0 (TCL 5.4); master : a66bce5 - Tue Feb 10 23:31:27 UTC 2015
CPUs: 8
Total Memory: 1.961 GiB
Name: boot2docker
ID: VGZO:GIGI:AYBS:I2MI:H7OC:TBCL:OPBC:OIJ4:SCDX:OXUW:YRNM:DAJU
Debug mode (server): true
Debug mode (client): false
Fds: 11
Goroutines: 16
EventsListeners: 0
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: kharayo
Registry: [https://index.docker.io/v1/]
bash-3.2$ docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): darwin/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
bash-3.2$

**Comment by jfrazelle** [comment]
ping @dmcgowan @dmp42 is this a hub issue?

**Comment by dmp42** [comment]
Hub issue.

(just to check: @kharayo did you `docker login`?)

**Comment by kharayo** [comment]
Yes I did.
bash-3.2$ docker login
Username (kharayo): kharayo
Login Succeeded

It this because I did not create repo on hub?

**Comment by jfrazelle** [comment]
ok please email support@docker.com for hub issues, so sorry you are having
this issue, you should not have to create the repo first, this is a bug
they will help you with
