### ISSUE TITLE
Docker Registry API (v1) Client Library

### ISSUE THREAD

**Issue by bdehamer** [docker/docker#11050]
Client library for v1 of the Docker Registry API written in Go:
https://github.com/CenturyLinkLabs/docker-reg-client

For inclusion in documentation:
https://docs.docker.com/reference/api/registry_api_client_libraries/

**Comment by jfrazelle** [comment]
cool do you want to submit a PR to add it to the docs :)

**Comment by bdehamer** [comment]
Yeah, didn't realize the docs were PR'able :)  Just saw the instruction to log a bug. I'll submit a PR.

**Comment by jfrazelle** [comment]
oooo if you want you can even change the instruction to say you can open a
PR :)

**Comment by bdehamer** [comment]
Will do
