### ISSUE TITLE
Please provide a Glossary

### ISSUE THREAD

**Issue by guettli** [docker/docker#11057]
this shows me:

https://docs.docker.com/jsearch/?q=glossary

`Nothing found`

A glossary is important if you want to learn a new technology. 

It often helps the developers, too. 

Defining terms is important for human communication.

Please forgive me, if you have one, and I could not find it.

**Comment by estesp** [comment]
ping @moxiegirl - feedback on docs

**Comment by thaJeztah** [comment]
There's a placeholder document here; https://github.com/docker/docker/blob/master/docs/sources/terms.md

**Comment by thaJeztah** [comment]
Also, dup"-ish"/related to https://github.com/docker/docker/issues/8648

**Comment by moxiegirl** [comment]
@estesp Thanks for the ping.  I am finally getting my filters sorta sorted.  I think it might be start to add a page with a few starter terms before the partay.  That way people will feel emboldened to add.

**Comment by moxiegirl** [comment]
It turns out we have individual pages for glossary items.  These are located in the `docs/sources/terms` folder.  Users should add to that folder. One file per term they want to add.

We might want to revisit the implementation for this glossary/term information.

**Comment by heitortsergent** [comment]
@moxiegirl do you know why the content from terms is marked as hidden?

https://github.com/docker/docker/blob/master/docs/mkdocs.yml#L166

**Comment by ankushagarwal** [comment]
@heitortsergent : This commit by @SvenDowideit  marked them as hidden : ada86fc5b736d8b3209429c584384fd9974a148a

This is really a nice idea @guettli and I would like to take a stab at this @moxiegirl 
Have you started off with something or can I start from scratch using https://github.com/docker/docker/blob/master/docs/sources/terms.md as a starting point.

The Glossary page can have a one to two line description of each of the terms listed and link to a page with a more detailed description like [this](https://docs.docker.com/terms/layer/) and [this](https://docs.docker.com/terms/container/)

**Comment by ankushagarwal** [comment]
#dibs

I have started working on the first draft of the Glossary doc page here : https://github.com/ankushagarwal/docker/tree/glossary . It's a Work In Progress and I should have a PR ready in 24 hours

I am putting it under `Reference` section as that seemed the most appropriate place.

Here's a screenshot
![image](https://cloud.githubusercontent.com/assets/796949/6885153/79d6075c-d5c7-11e4-9557-e86750ab0c90.png)

CC : @SvenDowideit

**Comment by moxiegirl** [comment]
@ankushagarwal My apologies for coming to this ticket so late. I got swamped with another task. I'm building your fork now to checkout the glossary.  From your screen capture it looks like a fantastic job.  I'll ping you back shortly.  Thank you for this work.  A visible glossary was a request from another contributor so to have yet another contributor answer it so quickly is very cool.

**Comment by guettli** [comment]
thank you :-)

**Comment by ankushagarwal** [comment]
@guettli : You're welcome!
@moxiegirl : Shouldn't this be updated with my change : http://docs.master.dockerproject.com/
I thought it points to the latest commit

**Comment by moxiegirl** [comment]
@ankushagarwal We are looking into it...the build was recently tweaked around...I'll ping back this ticket when I know more.  Thanks for letting us know.

**Comment by moxiegirl** [comment]
ping @ankushagarwal you should be able to see it now.

**Comment by ankushagarwal** [comment]
Nice!

On Monday, March 30, 2015, moxiegirl <notifications@github.com> wrote:

> ping @ankushagarwal <https://github.com/ankushagarwal> you should be able
> to see it now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/11057#issuecomment-87822050>.
>


-- 
Ankush Agarwal
http://ankush.io
@ankushio <https://twitter.com/ankushio>

*There are 10 types of people in this world. Those who understand binary
and those who don't.*
