### ISSUE TITLE
Does ADD command should extract tar.gz archives ?

### ISSUE THREAD

**Issue by PositiveAlex** [docker/docker#11061]
Here's my dockerfile
 
  
   FROM localhost:5000/image
   
   MAINTAINER user
   
   RUN mkdir /server
   
   ADD server.tar.gz /server/
   ADD serverctl /server/
   ADD log4cxx.properties /
   
   WORKDIR /server
   
   RUN gunzip -c server.tar.gz | tar xvf -
   RUN rm -f server.tar.gz

Buliding this dockerfile ends up with the error 

Step 7 : RUN gunzip -c server.tar.gz | tar xvf -
 ---> Running in 8e6725b43242
gzip: server.tar.gz: No such file or directory
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
Removing intermediate container 8e6725b43242

**Comment by duglin** [comment]
Can you try this Dockerfile and see what happens?
```
FROM ubuntu
WORKDIR /tmp
RUN pwd
```

**Comment by PositiveAlex** [comment]
Hmm... that's effin fantastic. Seems like ADD command gunzips and untars the file itself

1. we are in /server dir (pwd answered)
2. we having list of files in this archive
3. in this folder i haven't the archive itself...

Step 2 : RUN mkdir /server
 ---> Running in a40e2246b63a
 ---> 28174b14ea14
Removing intermediate container a40e2246b63a
Step 3 : ADD server.tar.gz /server/
 ---> 13784a859909
Removing intermediate container a9732908b634
Step 4 : ADD serverctl /server/
 ---> 755d63f6e244
Removing intermediate container 90eaf19f8c6a
Step 5 : ADD log4cxx.properties /
 ---> 03eaf5caae5f
Removing intermediate container 87871003e05b
Step 6 : WORKDIR /server
 ---> Running in 597281f9cd3b
 ---> b99708da5541
Removing intermediate container 597281f9cd3b
Step 7 : RUN pwd
 ---> Running in 8303a1ebc9da
/server
 ---> 87013a732861
Removing intermediate container 8303a1ebc9da
Step 8 : RUN ls -la
 ---> Running in 5a83bccbefc8
total 16192
drwxr-xr-x 13 root root    4096 Feb 27 12:32 .
drwxr-xr-x 85 root root    4096 Feb 27 12:32 ..
-rwxrwxr-x  1  600  600  236032 Feb  9 10:36 xxxxxxxxxxx
drwxrwxr-x  2  600  600    4096 Feb  9 10:36 xxxxxxxxxxx
drwxrwxr-x  2  600  600    4096 Feb  9 10:36 xxxxxxxxxxx
drwxrwxr-x  2  600  600    4096 Feb  9 10:36 xxxxxxxxxxx
-rwxrw-r--  1  600  600    3671 Feb  9 10:36 xxxxxxxxxxx
-rwxrw-r--  1  600  600   50335 Feb  9 10:36 xxxxxxxxxxx
-rwxrw-r--  1  600  600     206 Feb  9 10:36 xxxxxxxxxxx
drwxrwxr-x  2  600  600    4096 Feb  9 10:36 xxxxxxxxxxx
-rwxrwxr-x  1  600  600  388568 Feb  9 10:36 xxxxxxxxxxx
-rwxrw-r--  1  600  600    1389 Feb  9 10:36 xxxxxxxxxxx
-rwxrw-r--  1  600  600   26488 Feb  9 10:36 xxxxxxxxxxx
-rwxrw-r--  1  600  600     493 Feb  9 10:36 xxxxxxxxxxx
-rwxrwxrwx  1 root root   48559 Feb 27 09:51 xxxxxxxxxxx
-rwxrwxr-x  1  600  600  106160 Feb  9 10:36 xxxxxxxxxxx
-rwxrwxr-x  1  600  600   11047 Feb  9 10:36 xxxxxxxxxxx
drwxrwxr-x  3  600  600   12288 Feb  9 10:36 xxxxxxxxxxx
-rwxrwxr-x  1  600  600  182776 Feb  9 10:36 xxxxxxxxxxx
drwxrwxr-x  2  600  600    4096 Feb  9 10:36 xxxxxxxxxxx
-rwxrwxr-x  1  600  600 1588328 Feb  9 10:36 xxxxxxxxxxx
-rwxrwxr-x  1  600  600 8956976 Feb  9 10:36 xxxxxxxxxxx
-rwxrwxr-x  1  600  600  751240 Feb  9 10:36 xxxxxxxxxxx
-rwxrwxr-x  1  600  600  639600 Feb  9 10:36 xxxxxxxxxxx
drwxrwxr-x  2  600  600    4096 Feb  9 10:36 xxxxxxxxxxx
-rwxrwxr-x  1  600  600   56104 Feb  9 10:36 xxxxxxxxxxx
-rwxrwxr-x  1  600  600  421120 Feb  9 10:36 xxxxxxxxxxx
-rwxrwxr-x  1  600  600   68856 Feb  9 10:36 xxxxxxxxxxx
-rwxrwxr-x  1  600  600  262392 Feb  9 10:36 xxxxxxxxxxx
drwxrwxr-x  2  600  600    4096 Feb  9 10:36 xxxxxxxxxxx
drwxrwxr-x  4  600  600    4096 Feb  9 10:36 xxxxxxxxxxx
drwxrwxr-x  2  600  600    4096 Feb  9 10:36 xxxxxxxxxxx
-rwxrwxr-x  1  600  600 2308016 Feb  9 10:36 xxxxxxxxxxx
-rwxrwxr-x  1  600  600   75224 Feb  9 10:36 xxxxxxxxxxx
drwxrwxr-x  3  600  600    4096 Feb  9 10:36 xxxxxxxxxxx
-rwxrwxr-x  1  600  600  283824 Feb  9 10:36 xxxxxxxxxxx
-rwxrw-r--  1  600  600    5481 Feb  9 10:36 xxxxxxxxxxx
 ---> 2cae7c25037f
Removing intermediate container 5a83bccbefc8
Step 9 : RUN gunzip -c server.tar.gz | tar xvf -
 ---> Running in 751c23cdd59b
gzip: server.tar.gz: No such file or directory
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
Removing intermediate container 751c23cdd59b
INFO[0006] The command [/bin/sh -c gunzip -c server.tar.gz | tar xvf -] returned a non-zero code: 2

**Comment by duglin** [comment]
Yep see https://docs.docker.com/reference/builder/#add  : 
> If <src> is a local tar archive in a recognized compression format (identity, gzip, bzip2 or xz) then it is unpacked as a directory.

Why this decision was made... I have no idea. Try using COPY instead, it doesn't have this magic processing.

**Comment by PositiveAlex** [comment]
Thank you

19:54, Пт, 27.02.2015, Doug Davis <notifications@github.com>:

**Comment by duglin** [comment]
I think we can close this one now.  If not, please reopen or let me know

**Comment by Nottt** [comment]
Sorry for asking it here, but googling isn't helping much and this appears on 1st page.

Does ADD automatically extract tar.gz if they are also a URL? From my testing it seems it doesn't, and isn't clear anywhere if it only works if it's a local tar.gz file.

My dockerfile:

```
ADD https://github.com/just-containers/s6-overlay/releases/download/v1.22.1.0/s6-overlay-amd64.tar.gz /
```

I'd expect to have everything there unpacked into `/` avoiding another RUN in my dockerfile

**Comment by thaJeztah** [comment]
`ADD` only extracts when adding from a local file; when adding from a remote location, files are not extracted

https://docs.docker.com/engine/reference/builder/#add

> If `<src>` is a _local_ tar archive in a recognized compression format (identity, gzip, bzip2 or xz) then it is unpacked as a directory. Resources from remote URLs are not decompressed.

**Comment by hipop** [comment]
> `ADD` only extracts when adding from a local file; when adding from a remote location, files are not extracted
> 
> https://docs.docker.com/engine/reference/builder/#add
> 
> > If `<src>` is a _local_ tar archive in a recognized compression format (identity, gzip, bzip2 or xz) then it is unpacked as a directory. Resources from remote URLs are not decompressed.

It's a terrible trait 😭

**Comment by ashthespy** [comment]
Didn't find much info, but when extracting the tar archive, `--preserve-permissions` doesn't seem to be used?
