### ISSUE TITLE
Redundent '/v2/' GET made when pushing an image to v2 registry

### ISSUE THREAD

**Issue by bmangold** [docker/docker#11067]
![screen shot 2015-02-26 at 17 18 31](https://cloud.githubusercontent.com/assets/3420507/6420006/2c917146-be77-11e4-8496-f039c5254314.png)

Expected : only one call to /v2/ to determine if there is v2 support
Actual : two calls made to /v2/

See image.... using Charles Proxy ... pushing an ubuntu:latest image to a non-SSL v2 instance

Docker 1.5 daemon (/etc/default/docker):
export http_proxy="http://localhost:8888/"
DOCKER_OPTS="$DOCKER_OPTS --insecure-registry=host:port"

Docker 1.5 client:
docker push host:port/path_component1/path_component2

**Comment by jfrazelle** [comment]
awesome thanks for finding this

**Comment by estesp** [comment]
The code is not checking for v2 support only; the first `GET /v2` is checking over SSL.  Stating that your daemon will allow an insecure connection to a specific registry doesn't mean that your registry couldn't support SSL, so the code checks that first, and then when that fails, falls back to non-SSL HTTP `GET /v2`.  I'm not sure this is an issue that needs resolution, but the registry folks can chime in if necessary @dmcgowan @dmp42

**Comment by dmp42** [comment]
*burn-insecure-crazy-dance-with-fire*

**Comment by bmangold** [comment]
@estesp The first call is HTTP.  The second call is HTTP.

In both (exactly the same thing for the request and the response)
Request:
GET /v2/ HTTP/1.1
Host: ec2-52-10-192-57.us-west-2.compute.amazonaws.com:80
User-Agent: Go 1.1 package http
Accept-Encoding: gzip

Response:
HTTP/1.1 200 OK
Server: Tengine/2.1.0
Date: Fri, 27 Feb 2015 21:13:09 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 2
Connection: keep-alive
Docker-Distribution-Api-Version: registry/2.0

{}

**Comment by cpjreynolds** [comment]
I'll work on this.

**Comment by estesp** [comment]
It might be worth checking master to verify this still happens.  There was a PR merged yesterday (#11424) which make sure to use the factory rather than a new HTTP connection for the ping--still not sure from the code how a double GET of /v2/ping is occurring, but glad someone has time to look into this!

**Comment by cpjreynolds** [comment]
Thanks for the heads up! I looked over the PR you linked and it appears as though none of the logic as to when requests are sent has changed, which would suggest the issue may still exist. I'll pull the new changes from master and try to replicate this, then go from there. Glad to help!

**Comment by dmp42** [comment]
@cpjreynolds you can probably get some good guidance from @dmcgowan on this (either here or on irc #docker-distribution).

**Comment by pydima** [comment]
#dibs

**Comment by pydima** [comment]
I cannot reproduce this bug, have only one request to /v2, probably it was fixed. Docker version is 1.8.2, build 0a8c2e3.

**Comment by bmangold** [comment]
@pydima did you use HTTP in all cases and inspect traffic through proxy ?

**Comment by pydima** [comment]
@bmangold Yeah. Here is a screenshot. 
![screen](https://cloud.githubusercontent.com/assets/5312367/10506331/eb007d1c-7316-11e5-9ef1-fe2681f6ad5d.png)

**Comment by bmangold** [comment]
Thanks so much @pydima!
