### ISSUE TITLE
Error downloading dependent layers; Error pulling image (tag1) from 10.0.0.1:9000/namespac1/redis, ApplyLayer exit status 1 unexpected EOF

### ISSUE THREAD

**Issue by Vish0007** [docker/docker#11079]
I am getting consistently this error while docker pull:
Any ideas what this could be?
I am trying pull the image from my private registry.

behavior is same for docker version 1.3.3 docker 1.4.x

docker pull 10.0.0.1:9000/namespace1/redis:tag1
Pulling repository 10.0.0.1:9000/namespace1/redis
c89063721e41: Error pulling image (tag1) from 10.0.0.1:9000/namespace1/redis, ApplyLayer exit status 1 unexpected EOF 
511136ea3c5a: Download complete 
5e66087f3ffe: Error downloading dependent layers 
2015/02/25 12:22:44 Error pulling image (tag1) from 10.0.0.1:9000/namespace1/redis, ApplyLayer exit status 1 unexpected EOF

Adding the logs.
docker info:
===========================
Containers: 10
Images:136
Storage Driver: btrfs
Execution Driver: native-0.2
Kernel Version: 3.17.2
Operating System: CoreOS 494.5.0

docker version:
===========================
1.3.3, build 5dc1c5a

docker debug logs:
===========================
docker -d -D --insecure-registry 10.0.0.1:9000
2015/02/25 14:41:30 docker daemon: 1.3.3 5dc1c5a; execdriver: native; graphdriver:
[229209be] +job serveapi(unix:///var/run/docker.sock)
[info] Listening for HTTP on unix (/var/run/docker.sock)
[debug] server.go:1300 Registering POST, /exec/{name:.}/resize
[debug] server.go:1300 Registering POST, /auth
[debug] server.go:1300 Registering POST, /exec/{name:.}/start
[debug] server.go:1300 Registering POST, /images/{name:.}/push
[debug] server.go:1300 Registering POST, /containers/{name:.}/start
[debug] server.go:1300 Registering POST, /images/create
[debug] server.go:1300 Registering POST, /images/load
[debug] server.go:1300 Registering POST, /containers/{name:.}/restart
[debug] server.go:1300 Registering POST, /containers/{name:.}/wait
[debug] server.go:1300 Registering POST, /containers/{name:.}/attach
[debug] server.go:1300 Registering POST, /containers/{name:.}/copy
[debug] server.go:1300 Registering POST, /containers/{name:.}/exec
[debug] server.go:1300 Registering POST, /build
[debug] server.go:1300 Registering POST, /containers/{name:.}/unpause
[debug] server.go:1300 Registering POST, /containers/create
[debug] daemon.go:798 Using graph driver btrfs
[debug] daemon.go:816 Creating images graph
[debug] graph.go:68 Restored 1 elements
[debug] daemon.go:832 Creating repository list
[229209be] +job init_networkdriver()
[debug] /sbin/iptables, [--wait -C POSTROUTING -t nat -s 172.17.42.1/16 ! -o docker0 -j MASQUERADE]
[debug] server.go:1300 Registering POST, /containers/{name:.}/kill
[debug] server.go:1300 Registering POST, /containers/{name:.}/pause
[debug] server.go:1300 Registering POST, /containers/{name:.}/stop
[debug] server.go:1300 Registering POST, /containers/{name:.}/resize
[debug] server.go:1300 Registering POST, /commit
[debug] server.go:1300 Registering POST, /images/{name:.}/tag
[debug] server.go:1300 Registering DELETE, /containers/{name:.}
[debug] server.go:1300 Registering DELETE, /images/{name:.}
[debug] server.go:1300 Registering OPTIONS,
[debug] server.go:1300 Registering GET, /containers/{name:.}/changes
[debug] server.go:1300 Registering GET, /containers/{name:.}/logs
[debug] server.go:1300 Registering GET, /images/search
[debug] server.go:1300 Registering GET, /containers/json
[debug] server.go:1300 Registering GET, /containers/{name:.}/export
[debug] server.go:1300 Registering GET, /containers/{name:.}/json
[debug] server.go:1300 Registering GET, /containers/{name:.}/attach/ws
[debug] server.go:1300 Registering GET, /info
[debug] /sbin/iptables, [--wait -D FORWARD -i docker0 -o docker0 -j DROP]
[debug] server.go:1300 Registering GET, /version
[debug] server.go:1300 Registering GET, /images/viz
[debug] server.go:1300 Registering GET, /containers/ps
[debug] server.go:1300 Registering GET, /containers/{name:.}/top
[debug] server.go:1300 Registering GET, /_ping
[debug] server.go:1300 Registering GET, /events
[debug] server.go:1300 Registering GET, /images/json
[debug] server.go:1300 Registering GET, /images/get
[debug] server.go:1300 Registering GET, /images/{name:.}/get
[debug] server.go:1300 Registering GET, /images/{name:.}/history
[debug] server.go:1300 Registering GET, /images/{name:.}/json
[debug] server.go:1390 docker group found. gid: 233
[debug] /sbin/iptables, [--wait -C FORWARD -i docker0 -o docker0 -j ACCEPT]
[debug] /sbin/iptables, [--wait -C FORWARD -i docker0 ! -o docker0 -j ACCEPT]
[debug] /sbin/iptables, [--wait -C FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT]
[debug] /sbin/iptables, [--wait -t nat -D PREROUTING -m addrtype --dst-type LOCAL -j DOCKER]
[debug] /sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER]
[debug] /sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL -j DOCKER]
[debug] /sbin/iptables, [--wait -t nat -D PREROUTING -j DOCKER]
[debug] /sbin/iptables, [--wait -t nat -D OUTPUT -j DOCKER]
[debug] /sbin/iptables, [--wait -t nat -F DOCKER]
[debug] /sbin/iptables, [--wait -t nat -X DOCKER]
[debug] /sbin/iptables, [--wait -t nat -N DOCKER]
[debug] /sbin/iptables, [--wait -t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER]
[debug] /sbin/iptables, [--wait -t nat -A OUTPUT -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER]
[229209be] -job init_networkdriver() = OK (0)
[debug] daemon.go:376 Restarting containers...
[229209be] +job acceptconnections()
[229209be] -job acceptconnections() = OK (0)

==>after docker pull.

[debug] http.go:162 http://10.0.0.1:9000/v1/images/511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158/json -- HEADERS: map[User-Agent:[docker/1.3.3 go/go1.3.2 git-commit/5dc1c5a kernel/3.17.2 os/linux arch/amd64]]
[debug] image.go:249 Json string: {{"id":"511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158","comment":"Imported from -","created":"2013-06-13T14:03:50.821769-07:00","container_config":{"Hostname":"","User":"","Memory":0,"MemorySwap":0,"CpuShares":0,"AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"PortSpecs":null,"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":null,"Cmd":null,"Dns":null,"Image":"","Volumes":null,"VolumesFrom":""},"docker_version":"0.4.0","architecture":"x86_64"}}
[debug] http.go:162 http://10.0.0.1:9000/v1/images/511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158/layer -- HEADERS: map[User-Agent:[docker/1.3.3 go/go1.3.2 git-commit/5dc1c5a kernel/3.17.2 os/linux arch/amd64]]
[debug] session.go:199 server doesn't support resume
[debug] fsdiff.go:123 Start untar layer
[debug] archive.go:103 [tar autodetect] n: [31 139 8 0 0 9 110 136 0 255]
[debug] fsdiff.go:127 Untar time: 0.028225024s
[debug] http.go:162 http://10.0.0.1:9000/v1/images/5e66087f3ffe002664507d225d07b6929843c3f0299f5335a70c1727c8833737/json -- HEADERS: map[User-Agent:[docker/1.3.3 go/go1.3.2 git-commit/5dc1c5a kernel/3.17.2 os/linux arch/amd64]]
[debug] image.go:249 Json string: {{"id":"5e66087f3ffe002664507d225d07b6929843c3f0299f5335a70c1727c8833737","parent":"511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158","created":"2014-04-24T16:17:20.039070823Z","container":"95699cec7d3e21037450e4a37a28aec83c51d060095ee57556ffb8578d50cf1d","container_config":{"Hostname":"95699cec7d3e","Domainname":"","User":"","Memory":0,"MemorySwap":0,"CpuShares":0,"AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"PortSpecs":null,"ExposedPorts":null,"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":["HOME=/","PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],"Cmd":["/bin/sh","-c","#(nop) ADD file:175959bb3b959f73e976d6dbb5d47d0498a6660fa8c9795a1e8ed8ca1aad1560 in /"],"Image":"511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158","Volumes":null,"WorkingDir":"","Entrypoint":null,"NetworkDisabled":false,"OnBuild":[]},"docker_version":"0.10.0","config":{"Hostname":"95699cec7d3e","Domainname":"","User":"","Memory":0,"MemorySwap":0,"CpuShares":0,"AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"PortSpecs":null,"ExposedPorts":null,"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":["HOME=/","PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],"Cmd":null,"Image":"511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158","Volumes":null,"WorkingDir":"","Entrypoint":null,"NetworkDisabled":false,"OnBuild":[]},"architecture":"amd64","os":"linux","Size":192477442}}
[debug] http.go:162 http://10.0.0.1:9000/v1/images/5e66087f3ffe002664507d225d07b6929843c3f0299f5335a70c1727c8833737/layer -- HEADERS: map[User-Agent:[docker/1.3.3 go/go1.3.2 git-commit/5dc1c5a kernel/3.17.2 os/linux arch/amd64]]
[debug] session.go:199 server doesn't support resume
[debug] fsdiff.go:123 Start untar layer
[debug] archive.go:103 [tar autodetect] n: [31 139 8 0 0 9 110 136 0 255]
Error pulling image (tag1) from 10.0.0.1:9000/namespace1/redis, ApplyLayer exit status 1 unexpected EOF
[229209be] -job pull(10.0.0.1:9000/montana/redis, tag1) = ERR (1)

**Comment by dmp42** [comment]
Thanks.

Can you:

 * test with the latest version (docker 1.5)

If it still does not work, please:

 * `curl -o checklayer.tar http://10.0.0.1:9000/v1/images/5e66087f3ffe002664507d225d07b6929843c3f0299f5335a70c1727c8833737/layer`
 * `file checklayer.tar`
 * try to manually untar `checklayer.tar` and see if that works

**Comment by Vish0007** [comment]
trying on docker1.5 does not help.
Also, i cannot upgrade to 1.5 due to technical restrictions. Only if it proves out to be problem with the docker version I can upgrade.

the url "http://10.0.0.1:9000/v1/images/5e66087f3ffe002664507d225d07b6929843c3f0299f5335a70c1727c8833737/layer" doesnot seem to be valid. My internal registry throws error:
{"error" : Missing namespace in request"}

Are you suspecting some problem with filesystem support for the image?

**Comment by dmp42** [comment]
Ok, can you copy your entire registry logs when trying to pull? (on gist or pastebin please)

**Comment by thaJeztah** [comment]
@Vish0007 are you still having this issue? Based on https://github.com/docker/docker/issues/11079#issuecomment-76866942 there's currently not enough information to resolve this.

**Comment by Vish0007** [comment]
I have these issues still.
But somehow cannot copy the registry logs here.

Whats  that you are suspecting it to be? I can check those.

Btw what was the problem fixed with docker 1.5 which could have caused this
issue?

Thanks.

**Comment by dmp42** [comment]
I can't "guess" without logs, sorry...

**Comment by starkovv** [comment]
+1

Got the similar error.

`docker pull eboraas/apache`

```
Mar 23 20:03:18 core-01 dockerd[715]: Error pulling image (latest) from eboraas/apache, ApplyLayer fork/exec /usr/bin/docker: cannot allocate memory stdout:  stderr:
Mar 23 20:03:18 core-01 dockerd[715]: time="2015-03-23T20:03:18Z" level="info" msg="-job pull(eboraas/apache, latest) = ERR (1)
```

**Comment by dmp42** [comment]
@starkovv your issue looks different. "Cannot allocate memory" smells like another issue indeed...

**Comment by starkovv** [comment]
This issue shows up on:
`VirtualBox 4.3.24` + `CoreOS stable (607.0.0)` + `Docker version 1.5.0, a8a31ef-dirty`.
and
`VirtualBox 4.3.26` + `CoreOS stable (607.0.0)` + `Docker version 1.5.0, a8a31ef-dirty`.
and
`VirtualBox 4.3.26` + `Linux 3.13.0-44-generic #73-Ubuntu x86_64 GNU/Linux` + `Docker 1.5.0, build a8a31ef`.

But it's ok on:
`VirtualBox 4.3.24` + `Linux 3.13.0-44-generic #73-Ubuntu x86_64 GNU/Linux` + `Docker 1.5.0, build a8a31ef`.

**Comment by dmp42** [comment]
You are clearly hitting systems limit here.

**Comment by starkovv** [comment]
How is it possible? Everything was fine. This issues start appear after I updated CoreOS and VirtualBox. Everything else have not changed.

**Comment by unclejack** [comment]
@starkovv +1 to what @dmp42 has said. You're running out of memory. How much RAM does each of those VM have?

**Comment by starkovv** [comment]
@unclejack CoreOS has 1G, Ubuntu has 512MB.

**Comment by unclejack** [comment]
@starkovv There you go. You should give those VMs at least 1 GB. 1.5 GB+ would be recommended. 512 MB is way too little memory. I also run out of memory with 768 MB of RAM, so you certainly want 1 GB+.

**Comment by starkovv** [comment]
Fixed.

Now CoreOS VM is given 2GB RAM.

Successfully tested on:
`VirtualBox 4.3.24` + `CoreOS stable (557.2.0)` + `Docker 1.4.1, build 5bc2ff8-dirty`
and
`VirtualBox 4.3.24` + `CoreOS stable (607.0.0)` + `Docker 1.5.0, a8a31ef-dirty`

Thank you @dmp42 and @unclejack

---

So is there some minimum requirements for memory and swap on Docker host?

**Comment by unclejack** [comment]
@starkov It depends on what you do on that system - what containers you've got running while pulling images, what kind of operations those VMs are doing (other than running those containers and so on).

**Comment by starkovv** [comment]
@unclejack say, is there kinda overheads for Docker daemon itself that needs to be addressed?

**Comment by Pablohn26** [comment]
Yesterday I had the same problem, the log show me the next: 
    Jun 21 05:03:58 pablo docker: Error pulling image (latest) from docker.io/eugeneware/docker-wordpress-nginx, ApplyLayer exit status 1 stdout:  stderr: unexpected EOF
    Jun 21 05:03:58 pablo docker: time="2015-06-21T05:03:58+02:00" level=info msg="-job pull(docker.io/eugeneware/docker-wordpress-nginx, latest) = ERR (1)"

I cannot reproduce it again because now it starts properly. 

CentOS 7.
2 GB of RAM. 
Docker version 1.6.0, build 8aae715/1.6.0

**Comment by christian-blades-cb** [comment]
I have the same issue today.

```
Jun 24 17:48:25 ip-172-29-34-129 env[29339]: 31f630c65071: Pulling fs layer
Jun 24 17:48:26 ip-172-29-34-129 env[29339]: 31f630c65071: Error downloading dependent layers
Jun 24 17:48:26 ip-172-29-34-129 env[29339]: a234d255409d: Error pulling image (latest) from christianbladescb/statsd-influxdb, endpoint: https://registry-1.docker.io/v1/, ApplyLayer fork/exec /usr/bin/docker: cannot allocate memory stdou
Jun 24 17:48:26 ip-172-29-34-129 env[29339]: a234d255409d: Error pulling image (latest) from christianbladescb/statsd-influxdb, ApplyLayer fork/exec /usr/bin/docker: cannot allocate memory stdout:  stderr:
Jun 24 17:48:26 ip-172-29-34-129 systemd[1]: statsd.service: control process exited, code=exited status=1
```

```
$ free -h
             total       used       free     shared    buffers     cached
Mem:          7.3G       5.2G       2.1G       2.5M       1.8M       1.7G
-/+ buffers/cache:       3.5G       3.8G
Swap:           0B         0B         0B
```

```
Docker version 1.6.2, build 7c8fca2-dirty

Containers: 64
Images: 368
Storage Driver: btrfs
 Build Version: Btrfs v3.17.1
 Library Version: 101
Execution Driver: native-0.2
Kernel Version: 4.0.5
Operating System: CoreOS 681.2.0
CPUs: 2
Total Memory: 7.341 GiB
```

Running in AWS on an m3.large
I have 22 active containers running on this node

**Comment by ruudud** [comment]
I just ran into similar error messages while pulling an image..
The root cause for me, was that I was out of inodes. So check that with `df -i`.

**Comment by LK4D4** [comment]
Those are all different issues and weren't reported again for a long time. Feel free to open new issues.
