### ISSUE TITLE
kernel.core_pattern Read-only file system

### ISSUE THREAD

**Issue by PositiveAlex** [docker/docker#11086]
Hey,
my program wants that I've set up the kernel.core_pattern variable and I've tried setting this by many ways. There's only one answer by the system: Read-only file system. 

My program checks this var by this command: 

`/sbin/sysctl -n kernel.core_pattern`

How can I change this to be able to run my program ?

I shouldn't change the starter script from a distribution, but I have to do it for now, meanwhile I'm still waiting for possible workarounds, thank you.

**Comment by jfrazelle** [comment]
have you tried running the container as --privileged

**Comment by jfrazelle** [comment]
we need the output of this information https://github.com/docker/docker/blob/master/CONTRIBUTING.md#reporting-issues

**Comment by PositiveAlex** [comment]
I'm sorry, Jess. 
I could change this using `--privileged` flag. Closing this issue.

**Comment by yselivonchyk** [comment]
Or `--cap-add=SYS_ADMIN` when privileged is not an option https://docs.docker.com/engine/reference/commandline/run/
