### ISSUE TITLE
Allow 'docker import' to load from local files

### ISSUE THREAD

**Issue by ewindisch** [docker/docker#11094]
The docker import mechanism allows loading from a pipe, but while this works, is not obvious to many users. Furthermore, not all users understand working with pipes.

Instead, users have reported attempting (and failing) to use a file:/// url.

**Comment by gcuisinier** [comment]
I'll work on this if possible

**Comment by gcuisinier** [comment]
First draft here : https://github.com/gcuisinier/docker/tree/11094-allow-import-from-file

**Comment by runcom** [comment]
I think it would be better to make `import` similar to `load` and import a tar from either STDIN with `docker import < export.tar` or with `--input` or `-i` flag with `docker import -i export.tar`

**Comment by VictorDenisov** [comment]
#dibs

**Comment by gcuisinier** [comment]
Indeed, having the two commands that work in the same way would probably be better.
I'll update the code in that direction

**Comment by nhsiehgit** [comment]
Hi @gcuisinier
Once you have your PR submitted, please remember to include the keywords `closes` or `fixes` to help tracking the fixes easier. Thanks!

**Comment by nhsiehgit** [comment]
Hi @gcuisinier
Once you have your PR submitted, please remember to include the keywords `closes` or `fixes` to help tracking the fixes easier. Thanks!

**Comment by gcuisinier** [comment]
@nhsiehgit Ok, I'll will not forget.
I'll try to propose the PR asap.

I wil propose two PR :
- first one with only support file:// URL
- second one by refactoring to be symmetric with docker load -i
