### ISSUE TITLE
set http/https proxy through command line.

### ISSUE THREAD

**Issue by is** [docker/docker#11093]
Http/https proxy is set through environment at
docker daemon starts, and can't be modified. 

In current statuation, i need set special proxy for pull/push 
action. so i hope i can set proxy server through cli pull/push
command.

**Comment by jfrazelle** [comment]
Well the daemon is what sets up the server, where we need the proxy command so resetting it would take restarting the daemon iirc, why can you not set the variable on daemon start?

**Comment by is** [comment]
In Mainland China, docker hub is hard to access directly.

In my network environment, i need set differents proxies for access 
docker hub and other docker image services which located in China.

I need often restart the docker deamon to change http proxy. it's very boring.
so i hope the feature, I can set the real proxy through client command line.

**Comment by xiaods** [comment]
don't need this proxy, use docker mirror can resolve it.  more details describe see here: https://github.com/docker/docker/blob/master/docs/sources/articles/registry_mirror.md

**Comment by is** [comment]
Yes, Docker registry mirror is good solution for enterprise level user. 
But for personal user, it is a little complex.

**Comment by xiaods** [comment]
hey is, it doesn't make sense. what is complex? in china region,  i found a site:  daocloud.io provide a registry mirror service, have a try. it is very easy usage for user.

**Comment by is** [comment]
I know the daocloud.io, It has 10G monthly quota limit.

**Comment by thaJeztah** [comment]
@xiaods @is I can see tips like that being valuable for people that have to deal with the GFW. Although I'm not sure if there's a good place for that somewhere in the documentation (an article? a mention in the FAQ?) could one of you write up something (e.g. "Using Docker behind the GFW")?

I'm not a docs maintainer, so it might be best to create a "proposal" issue first and see what the docs maintainers think of it, but again, it might be useful. :smile:

**Comment by HackToday** [comment]
so it not have progress for work with GFW ? only have to use VPN ?

**Comment by calavera** [comment]
@is @HackToday please, feel free to open a Pull Request with the code changes necessary to make this happen. We will be glad to assist you with guidance if you need help, but you might have more luck seeing this happening if you start a discussion with some code.

This might be as easier as adding the right options to [the pull command](https://github.com/docker/docker/blob/master/api/client/pull.go) and [the push command](https://github.com/docker/docker/blob/master/api/client/push.go)

**Comment by is** [comment]
@calavera To extend options on commandline client side is straightforward.
The operations is running on backend actually. docker's proxy suppoert
is based on golang runtime. I don't known where i can start. 

I'm sorry that I am not familiar on golang network programing.

**Comment by marccampbell** [comment]
#dibs

**Comment by coolljt0725** [comment]
I have done some work for adding `proxy` flag on pull a month ago https://github.com/coolljt0725/docker/tree/add_proxy_to_pull
it can work,
`docker pull --proxy http://9.1.0.228:3128 ubuntu`
 but it's not ready for opening a PR and I'm busy since then and have no much time to continue.
@marccampbell  You can take a look at my branch if you are interested -:)

**Comment by marccampbell** [comment]
@coolljt0725 thanks!

**Comment by LK4D4** [comment]
I think that daemon now respects environment variables. Feel free to open new issue if not.
