### ISSUE TITLE
stats endpoint 

### ISSUE THREAD

**Issue by leejansq** [docker/docker#11100]
stats endpoint 
why  unix socket don't Continuously receive stats info.
but tcp is not.

**Comment by cpuguy83** [comment]
Hi, I'm not sure I understand your issue, but as there should be no difference between unix socket or tcp socket for any endpoint.

Can you explain with a little more detail what issue you are having?

**Comment by leejansq** [comment]
thank you,this is my wrong;
the container  that I want to get stats info   is not started;so block the connection,and nothing return.

but as I think the docker api should return message <:the container is not started> substitute for to block the connection

**Comment by cpuguy83** [comment]
Ok, closing because this is intended behavior.
