### ISSUE TITLE
add bind mount to an already running container 

### ISSUE THREAD

**Issue by michaelneale** [docker/docker#11105]
As covered by @jpetazzo here: http://jpetazzo.github.io/2015/01/13/docker-mount-dynamic-volumes/

it is possible to create a bind mount after a container has launched - in a fairly occult way. Is a RFE for this to be a docker feature reasonable? Many times a new starter may wish to bind mount something in after the fact? (however, there is great power/responsibility etc).

**Comment by coolljt0725** [comment]
There are several issues on this, see #9849 #10975  #9915   PR #8348 #8826

**Comment by michaelneale** [comment]
closing as many duplicates. It is impossible to search for docker issues (in google at least) because of the endless hello-world examples.
