### ISSUE TITLE
docker rm needs a real -f argument

### ISSUE THREAD

**Issue by kswope** [docker/docker#11107]
In my script I delete a container by name, but if the container doesn't exsit docker rm returns an error and prints an error.

As far as I can tell, there is no way currently to check for the existence of a container since inspect looks at both containers and images.

I'm looking for either a reliable way to do a check for a container before rm, or for rm to have a similar switch to /usr/bin/rm, which allows it to silently fail with no error if the file doesn't exist.

Since -f is already taken, I suggest -q for suppress output and silently fail without error return code. 'i' could also work for ignore-fail

**Comment by ahmetalpbalkan** [comment]
@kswope you can probably do something like `docker rm -f foo; true` to unblock yourself. you can check the existence of container using `docker ps -aq | grep container_name`

This feature request is probably also valid for `rmi` command?

**Comment by thaJeztah** [comment]
looks like a dup of https://github.com/docker/docker/issues/10545

Is your use-case starting new containers and replace the existing one (if it exists)? If it is, these issues may have some overlap as well; https://github.com/docker/docker/issues/9253  https://github.com/docker/docker/issues/7245

**Comment by jfrazelle** [comment]
closing as dup of https://github.com/docker/docker/issues/10545
