### ISSUE TITLE
when is the 1.5.1 release due (related to issue #10599)

### ISSUE THREAD

**Issue by jgangemi** [docker/docker#11117]
i'm still suffering from issue #10599, which was fixed by #10601 but i am unable to determine if that made it in to the 1.5.0 release before it went out.

could someone clarify if #10601 made its way into the 1.5.0 release b/c i will need to open another issue for this b/c it still exists.

thanks!!

**Comment by jfrazelle** [comment]
It does not look like that commit was in 1.5.0, but you can download master binaries at master.dockerproject.com. Right now we do not have a date for 1.5.1 but 1.6.0 will be frozen on March 18, release scheduled for second week of april

**Comment by jgangemi** [comment]
great, thanks for the prompt response!
