### ISSUE TITLE
Documentation request: general storage-driver-guide

### ISSUE THREAD

**Issue by funkyfuture** [docker/docker#11110]
The documentation at https://docs.docker.com obviously lacks any discussion of the available storage-drivers which imo is essential to guide people to their docker-setup.

One lesson, i learned today, is that you cannot run containers with the btrfs-driver if the `/var/lib/docker`-path itself is a subvolume of a btrfs-tree. This directory must sit in the `default`-volume of a btrfs-volume.
And i think this should be covered in the documentation.

**Comment by yanana** [comment]
+1

**Comment by thaJeztah** [comment]
Yes, I think this is needed (think this came up, but I never got round to create an issue for it),

Couple of things that come in mind;
- Advantages/disadvantages of each driver
- Performance
- Stability
- Level of "support" in Docker (grades?)
- Known issues
- Requirements
- Incompatibility with underlying file systems

Some of the above bullets will be dependent on the *use case* (e.g. production, CI, *size* of containers, frequency of adding/removing containers etc.), but also the environment Docker is run on (linux distro, does AppArmor/SELinux affect drivers differently?)

The documentation should be useful for users to pick the best filesystem/storage-driver for *their* situation, without prior knowledge.

**advanced information**
It would be nice to add a section that describes the  more in-depth; a basic description of the technology each driver/filesystem uses.

Finally, some drivers are (by default) configured for "generic" use, but can be fine-tuned using options. It should be made clear that the defaults are not the *best* settings in most cases and contain information how to determin the best settings for a users specific situation (or links to external locations for more info)


An excellent article on this subject can be found here; http://developerblog.redhat.com/2014/09/30/overview-storage-scalability-docker/ by @jeremyeder I'm not sure if the content of that article is "public domain", but it might be worth asking permission to 
reproduce (parts of) that article (or perhaps he's willing to assist in writing). Of course the article should be verified against the current situation (it may be outdated now).

**Comment by LK4D4** [comment]
There is a lot of info under docs/userguide/storagedriver. Going to close this as solved.
