### ISSUE TITLE
Unmount container rootfs after successful launch

### ISSUE THREAD

**Issue by rhvgoyal** [docker/docker#11113]
Right now we keep container rootfs mounted (in /var/lib/docker/devmapper/mnt/<container_id>) after container launch and it is unmounted once container has exited.

But this creates problems of devices leaking into mount namespace of other containers. And that in turn does not allow container to exit or to be removed. We give up after 10 seconds in the process leaving behind active devices or unreclaimable space from thin pool.

Run following to see that a container thin device has leaked into another container.

- Run first container.
  docker run -ti fedora /bin/bash

- Run second container
  docker run -v /:/host -ti fedora /bin/bash

Now we have leaked first container's device into second container and first container can't be removed till second container exits.

I am about to post a patch series which unmounts the contianer after successful launch to fix this issue.

devicemapper driver right now activates/deactivates devices upon Get()/Put() calls (mount/unmount). But device can't be deactivated after container launch as same device is being used in container's namespace. 

Hence I have introduced two new calls to graph driver. Prepare() and Unprepare() and now these devices do the work of activating and deactivating devices. These calls are generic enough that
any graph driver can make use of these, if need be.

Prepare() is supposed to be called before Get() and Unprepare is supposed to be called after Put().

Once this is in place, now we can unmount the container rootfs from docker daemon's namespace
and deactivate the device after container has exited. Because container has exited we know that
device should not be used in any other mount namespace and deactivation should be successful.

**Comment by thaJeztah** [comment]
@rhvgoyal should both this issue and https://github.com/docker/docker/issues/10991 stay open, are they duplicates? I realise there are two approaches to solving it, but not sure if both issues should stay open (which can be confusing).

Happy to hear, thanks!

**Comment by rhvgoyal** [comment]
@thaJeztah 

May be we can close this issue and track all the issues related to devices leaking into another namespace using #10991

**Comment by thaJeztah** [comment]
@rhvgoyal sounds good; make sure you update the `closes #....` in your descriptions.


I'm closing this issue in favor of https://github.com/docker/docker/issues/10991, which describes the same problem. 

For everyone arriving here; please continue the discussion on that issue (https://github.com/docker/docker/issues/10991), or on the associated pull-request(s)
