### ISSUE TITLE
docker -d -h start daemon instead of showing help menu

### ISSUE THREAD

**Issue by shishir-a412ed** [docker/docker#11120]
The following starts the docker daemon instead of showing the help menu.

1) docker -d -h 
2) docker -d --help
3) docker -h -d 
4) docker --help -d
5) docker --daemon -h
6) docker --daemon --help
7) docker -h --daemon
8) docker --help --daemon.

Shishir

**Comment by jfrazelle** [comment]
duplicate https://github.com/docker/docker/issues/9677

**Comment by tiborvass** [comment]
@jfrazelle This is a different issue unfortunately :(

**Comment by jfrazelle** [comment]
:( can we fix both

**Comment by duglin** [comment]
I think we can close this one now.
