### ISSUE TITLE
docker build: allow to specify cache invalidation mechanism

### ISSUE THREAD

**Issue by Silex** [docker/docker#11130]
Hello,

Right now the caching mechanism seems to be "timestamp-based", e.g with the following Dockerfile:

``` dockerfile
from ubuntu:14.04
add . /srv/foo
```

A simple "touch Dockerfile" causes the cache to be invalidated. While I understand the reasoning behind it, this is kinda annoying because the contents of the file didn't change and in many cases you only care about the contents, not the modification time.

I suggest adding a new flag like this:

``` man 
--cache-strategy timestamp|sha1sum|md5sum

timestamp (default): use the modification time of the file (fast). Only cares about file timestamp.
sha1sum: use sha1sum to determinate if file has changed. Only cares about file contents.
md5sum: use md5sum to determinate if file has changed (slow). Only cares about file contents.
```

This change could also maybe include #9294 for debugging purposes.

**Comment by phemmer** [comment]
Dup of #4351

**Comment by thaJeztah** [comment]
@Silex thanks for reporting, but this is a duplicate of #4351. Could you close this to keep down the number of issues? You can continue the discussion on #4351. Thanks!

**Comment by Silex** [comment]
Alright, but I think my proposal is different than the one at #4351
