### ISSUE TITLE
Docker build fails with "invalid argument" on encfs

### ISSUE THREAD

**Issue by tgpfeiffer** [docker/docker#11132]
I tried moving my Docker directory to a directory in my $HOME, which is encfs-encrypted and therefore has a pretty short filename length limit (143 characters?). Most Docker commands that "do" something (i.e., docker build, docker run) fail at some point with "invalid argument". Moving the directory outside of encfs makes everything go fine. I wonder if there's a chance to solve that issue or give at least a better error message.

**Comment by coolljt0725** [comment]
what's your graph driver? Maybe you can provide `docker version` `docker info` `uname -a` and that we may can do more help

**Comment by tgpfeiffer** [comment]
$ uname -a
	Linux samsux 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

	$ sudo docker version
	Client version: 1.4.1
	Client API version: 1.16
	Go version (client): go1.3.3
	Git commit (client): 5bc2ff8
	OS/Arch (client): linux/amd64
	Server version: 1.4.1
	Server API version: 1.16
	Go version (server): go1.3.3
	Git commit (server): 5bc2ff8

	$ sudo docker info
	Containers: 18
	Images: 153
	Storage Driver: aufs
	 Root Dir: /home/docker/aufs
	 Dirs: 189
	Execution Driver: native-0.2
	Kernel Version: 3.13.0-37-generic
	Operating System: Ubuntu 14.04.2 LTS
	CPUs: 4
	Total Memory: 7.508 GiB
	Name: ***
	ID: ***
	WARNING: No swap limit support

Please note that /home/docker is outside of my encfs, where I am currently using it.

**Comment by cpuguy83** [comment]
I don't know that this can be fixed if this is a character size limit. But the error message can certainly be improved.

**Comment by unclejack** [comment]
We need to disallow aufs to be used on encfs or Docker on encfs entirely. Disabling aufs on encfs would solve the problem of not using aufs on top of encfs, but volumes would still have this problem. There's no point in giving the impression this works properly and error out later during a pull or during a similar operation.

The proper solution would be to forbid the use of an encfs fs path as a Docker directory and also blacklist it in aufs.

**Comment by cpuguy83** [comment]
btw, error messages have been updated so at least you know where the error is coming from and at what point :)

**Comment by cpuguy83** [comment]
Closing because encfs is not supported by the underlying CoW filesystems and docker will now error out if you try to use this configuration.
