### ISSUE TITLE
delete oauth document still alive on docs.docker.com

### ISSUE THREAD

**Issue by programmerq** [docker/docker#11136]
This information was intended to be taken down completely, but is still in the 1.0 doc tree: https://docs.docker.com/v1.0/reference/api/docker_io_oauth_api/

This could give the impression that it is still valid since the page itself is active, and not obviously marked as obsolete in any way.

See: https://github.com/docker/docker/pull/7193

**Comment by jfrazelle** [comment]
ping @SvenDowideit can you handle this

**Comment by jfrazelle** [comment]
also closing as dup of https://github.com/docker/docker/issues/7630
