### ISSUE TITLE
docker cp: notion of HOSTPATH

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/docker#11141]
```
$ docker cp --help

Usage: docker cp [OPTIONS] CONTAINER:PATH HOSTPATH

Copy files/folders from the PATH to the HOSTPATH

  --help=false       Print usage
```

This usage of HOSTPATH always strikes me as it's actually copying and extracting the files over where the Docker daemon host lives. (Isn't that what we usually refer to as "host"?) This sort of confuses me and there's not really a way to find out without trying out or reading more docs on docker.com. 

I'd love to propose rewriting this usage string with a less confusing one. Opinions?

**Comment by duglin** [comment]
would just using "local host" work since its copying it to where your CLI is running (I think) ?

**Comment by ahmetalpbalkan** [comment]
@duglin IDK "to the machine docker cp command is running" sounds more clear to me. :question:

**Comment by duglin** [comment]
@ahmetalpbalkan either is fine with me

**Comment by duglin** [comment]
Actually, if we don't want to touch the HOSTPATH in the usage line, perhaps "to the host running the docker cp command" ?

**Comment by duglin** [comment]
want me to take it?

**Comment by ahmetalpbalkan** [comment]
No I can do it I guess. Thx.
