### ISSUE TITLE
Proposal: New instruction ONCOMMIT for dockerfile

### ISSUE THREAD

**Issue by zepouet** [docker/docker#11158]
## USE CASE  
The `ONCOMMIT` instruction adds to the image a trigger instruction to be executed later on, when the container is commited. The trigger will be executed as if inserted immediately before the commit instruction, in the command line executable or api call.

Any command can be registered as a trigger for `ONCOMMIT`.
  
This `ONCOMMIT` instruction is useful to clean up, before commiting a container which will be used as a base image for other containers. For example, one can clean up logs files, remove specific environment variables, or delete any executable which may be customized with user-specific configuration.

## DETAILS 

For example, let us consider a HTTP webserver: Nginx. It will generate a lot of log files in a particular directory, and it might require a build script to be called before commit to clean up. You could simply call an exec command to run a shell script before commit, but that is inefficient, error-prone and difficult to update because it mixes shell scripts with container-specific behaviour.

The solution is to use `ONCOMMIT` to register instructions to be run later, during the next commit stage.

Here's how it works:
* When it encounters an `ONCOMMIT` instruction, the builder adds a trigger to the metadata of the image being built. The instruction does not otherwise affect the current build.
* At the end of the build, a list of all triggers is stored in the image manifest, under the key `OnCommit`. They can be inspected with the docker inspect command.
* Later the image may be used as a base for a new build, using the FROM instruction. The docker executable looks for `OnCommit` triggers, and executes them in the same order they were registered. If any of the triggers fails, the commit command is aborted which in turn causes the commit to fail. If all triggers succeed, the commit command completes and the process continues as usual.
* Triggers are not cleared from the final image after being executed. In other words they are inherited by "grand-children" commits.

For example you might add something like this:

> ONCOMMIT rm -rf /var/log/apache2/*
> ONCOMMIT rm -rf /software/tomcat8/logs/*
> ONCOMMIT /shell/clean-env.sh

> Dockerfile Examples
> Nginx
> https://github.com/dockerfile/nginx

```
# Pull base image.
FROM dockerfile/ubuntu

# Install Nginx.
RUN \
  add-apt-repository -y ppa:nginx/stable && \
  apt-get update && \
  apt-get install -y nginx && \
  rm -rf /var/lib/apt/lists/* && \
  echo "\ndaemon off;" >> /etc/nginx/nginx.conf && \
  chown -R www-data:www-data /var/lib/nginx

# Define mountable directories.
VOLUME ["/etc/nginx/sites-enabled", "/etc/nginx/certs", "/etc/nginx/conf.d"]

# Define working directory.
WORKDIR /etc/nginx

# Define default command.
CMD ["nginx"]

# Define triggered oncommit instruction
ONCOMMIT ["rm -rf /var/log/nginx", "rm -rf /var/www/html"]                                                 

# Expose ports.
EXPOSE 80
EXPOSE 443
```

Thanks you very much for reading this document.
I am looking forward to reading you.
Best regards,

Nicolas MULLER (@zepouet)

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.
