### ISSUE TITLE
resize docker container disk fail!

### ISSUE THREAD

**Issue by dl528888** [docker/docker#11153]
hi,i refer to http://jpetazzo.github.io/2014/01/29/docker-device-mapper-resize/,when i resize docker container disk,it is fail,pls help me.
My docker version is:
16:17:30 # docker version
Client version: 1.3.2
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 39fa2fa/1.3.2
OS/Arch (client): linux/amd64
Server version: 1.3.2
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): 39fa2fa/1.3.2
My docker info is:
Containers: 1
Images: 4
Storage Driver: devicemapper
 Pool Name: docker-8:3-3408905-pool
 Pool Blocksize: 524.3 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 944.2 MB
 Data Space Total: 536.9 GB
 Metadata Space Used: 1.04 MB
 Metadata Space Total: 8.59 GB
 Library Version: 1.02.84-RHEL7 (2014-03-26)
Execution Driver: native-0.2
Kernel Version: 3.10.0-123.el7.x86_64
Operating System: CentOS Linux 7 (Core)
My docker config is:
16:25:20 # cat /etc/sysconfig/docker
OPTIONS=-H fd:// --insecure-registry docker.ops-chukong.com:5000 --iptables=false --storage-opt dm.blocksize=512K  --storage-opt dm.loopdatasize=500G --storage-opt dm.loopmetadatasize=8G
i create and run docker container,it name is test1.and i resize this container disk from 10g to 20g.
before the change:
16:15:07 # dmsetup table /dev/mapper/docker-8\:3-3408905-8f99c3f825b13351b7a21802e4341cb669ae0e939c3ccc0f788edc5827065eaa
0 20971520 thin 253:0 6
after the change:
16:15:49 # echo $((20*1024*1024*1024/512))
41943040
root@docker-test2:/tmp
16:16:37 # echo "0 41943040 thin 253:0 6"|dmsetup load /dev/mapper/docker-8\:3-3408905-8f99c3f825b13351b7a21802e4341cb669ae0e939c3ccc0f788edc5827065eaa
root@docker-test2:/tmp
16:16:57 # dmsetup table /dev/mapper/docker-8\:3-3408905-8f99c3f825b13351b7a21802e4341cb669ae0e939c3ccc0f788edc5827065eaa
0 20971520 thin 253:0 6
root@docker-test2:/tmp
16:17:00 # dmsetup resume /dev/mapper/docker-8\:3-3408905-8f99c3f825b13351b7a21802e4341cb669ae0e939c3ccc0f788edc5827065eaa
root@docker-test2:/tmp
16:17:13 # dmsetup table /dev/mapper/docker-8\:3-3408905-8f99c3f825b13351b7a21802e4341cb669ae0e939c3ccc0f788edc5827065eaa
0 41943040 thin 253:0 6
root@docker-test2:/tmp
16:17:15 # resize2fs /dev/mapper/docker-8\:3-3408905-8f99c3f825b13351b7a21802e4341cb669ae0e939c3ccc0f788edc5827065eaa
resize2fs 1.42.9 (28-Dec-2013)
resize2fs: Device or resource busy while trying to open /dev/mapper/docker-8:3-3408905-8f99c3f825b13351b7a21802e4341cb669ae0e939c3ccc0f788edc5827065eaa
Couldn't find valid filesystem superblock.
so what is the problem?

**Comment by glaudiston** [comment]
I don't know how to help, but have you tried to use aufs istead of devicemapper ?

**Comment by dl528888** [comment]
thanks you for replay，I always use devicemapper.I found this problem is in
the centos 7,and it's ok in the centos 6.

2015-04-21 21:16 GMT+08:00 Glaudiston Gomes da Silva <
notifications@github.com>:

**Comment by thaJeztah** [comment]
Looking at the above, I don't think this is a bug in docker, so I'm going to close this issue, but feel to comment if you think I closed this by mistake.

**Comment by kriss9** [comment]
+1

**Comment by davidstack** [comment]
@dl528888  if you are use centos7,you can try:xfs_growfs /dev/mapper/docker-8:3-3408905-8f99c3f825b13351b7a21802e4341cb669ae0e939c3ccc0f788edc5827065eaa
