### ISSUE TITLE
[hub.docker.com] Infinitive loop

### ISSUE THREAD

**Issue by andytruong** [docker/docker#11164]
I got this error when access to https://hub.docker.com/repos/andytruong/

![](https://s3.amazonaws.com/f.cl.ly/items/2N1q291P3z0M2E1q0J1d/Screen%20Recording%202015-03-05%20at%2005.38%20AM.gif)

Thanks

**Comment by duglin** [comment]
do you allow cookies?  dunno if it matters but it might.

**Comment by thaJeztah** [comment]
@andytruong issues with the Docker Hub are not handled via this issue tracker, but can be reported via support@docker.com. Could you open a ticket there?

Thanks for taking the time to report this!
