### ISSUE TITLE
Docker 1.5.0 deb package installation fails sometimes

### ISSUE THREAD

**Issue by hacfi** [docker/docker#11167]
Installing docker on Travis CI I noticed that the debian package for version 1.5.0 is often failing. If you have a look at https://travis-ci.org/stage1/docker-php/builds you can see that the tests started failing often after build 299. There were some other issues with the Travis configuration but in many cases the Travis log ends with:

```sh
Setting up lxc-docker-1.5.0 (1.5.0) ...
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

If you have a look at https://travis-ci.org/stage1/docker-php/builds/53139790 and https://travis-ci.org/stage1/docker-php/builds/53140258 you can see that the issue is not limited to installing via apt-get but also running `dpkg -i`.

Are there any known issues with the deb package of 1.5.0?

**Comment by hacfi** [comment]
Just noticed I’m not the only one having this issue: https://github.com/moul/travis-docker/issues/4

**Comment by tiborvass** [comment]
@hacfi thanks for the report! I'm not sure what the error is. How could we have more information on the actual error?

Ping @tianon

**Comment by hacfi** [comment]
@tiborvass I only got those logs at the moment. I’m not very familiar with deb packages. How can I install them in debug mode or how can I provide more information?

**Comment by hacfi** [comment]
#9287 could be related

**Comment by hacfi** [comment]
Any ideas/hints? Can you provide a deb file without the changes made in #9287 so we can try if that’s causing the issue_

**Comment by ubiqtus** [comment]
I got hung up installing.  Once I ran apt-get install liberror-perl it worked.  Said something about it 'manually installed'

# apt-get install liberror-perl
Reading package lists... Done
Building dependency tree
Reading state information... Done
liberror-perl is already the newest version.
liberror-perl set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
2 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up lxc-docker-1.5.0 (1.5.0) ...
Setting up lxc-docker (1.5.0) ...


Hope it helps.

**Comment by hacfi** [comment]
@ubiqtus Thanks for the hint..will give that a try!

**Comment by tianon** [comment]
Fixed by #11945! :tada:

**Comment by meatballhat** [comment]
:clap: :tada: :metal: :smiley_cat:

**Comment by hacfi** [comment]
Yay..thanks @lmars

**Comment by lmars** [comment]
:smile:
