### ISSUE TITLE
Answer checking looks at the wrong line in tutorial step 1

### ISSUE THREAD

**Issue by davecuthbert** [docker/docker#11165]
The script that parses the command response matches the string 'tutorial' in the search summary line rather than searching for a matching entry in the containers line. 

The result is that a 'not found' message triggers the correct response popup from the tutorial even though the search failed (See screen shot)
![image](https://cloud.githubusercontent.com/assets/1139436/6496250/8438f122-c286-11e4-8723-4688ee404fc1.png)
.

**Comment by duglin** [comment]
@jfrazelle where's the right spot for this issue?  I don't think this is part of the docker/docker repo.

**Comment by jfrazelle** [comment]
please email support@docker.com
