### ISSUE TITLE
Fedora instructions has incorrect package name

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#11182]
### User Email thru feedback states problem

Florian via docker.com 
10:15 AM (2 hours ago)

to feedback 
Dear all,

First of all, Thank you for the installation instructions for docker on a Fedora system given here: https://docs.docker.com/installation/fedora/). 

I think, that there is a little mistake in the instructions for Fedora 21: The package from the official Fedora21 repository is still called docker-io, not docker.
For more information, see Fedora's packages website: https://apps.fedoraproject.org/packages/docker-io

With kind regards

**Comment by thaJeztah** [comment]
I think @lsm5 should be able to verify if this is correct :)

**Comment by RickWieman** [comment]
The package might still be called `docker-io`, but `docker` works as well:

```
$ sudo yum install docker
Loaded plugins: langpacks
Package docker-io-1.5.0-1.fc21.x86_64 already installed and latest version
Nothing to do
```

**Comment by lsm5** [comment]
what @RickWieman said. `docker` on f21 points to the real `docker-io` package. This is in preparation for future releases (f22 and up) where the `-io` will be dropped as well and there will only be a real `docker` package.

**Comment by thaJeztah** [comment]
@moxiegirl given the above information (thanks all!), I think this can be closed, or do you think it should be mentioned in the documentation? (it might only distract).

**Comment by moxiegirl** [comment]
@thaJeztah let's close this for now. We are in the process of standardizing the installation documentation and this shortly shouldn't be a problem. Thank you for your help clarifying the situation.
