### ISSUE TITLE
Warning: Mounting volumes containing files downloaded with Safari in OS X

### ISSUE THREAD

**Issue by alexisvincent** [docker/docker#11180]
I encountered an obscure error a few days ago and I felt compelled to publish it where it might help some people.

Here is the story.

For a while I've been facing permissions errors from within containers trying to access certain files and I couldn't work out why this was happening. It only affected files when mounting them to the container, not when added to the container. Further more, when executing a shell inside the container, the files existed and the user could write to the mounted directory.

This bugged me for weeks and I'd reverted to rebuilding the containers whenever I made a change. Strangely, when a friend of mine pulled the code from git and mounted the volume... it worked. I concluded this was an error on my personal machine.. However when he pushed new code it miraculously worked on my machine... 

After some inspection I noticed that the file downloaded with safari contained an extended attribute 'com.apple.quarentine'. Removing this made everything work again. And because git strips extended attributes before committing this is why 'git files' worked.

It turns out, when downloading files with Safari on OS X, OS X adds an attribute to refuse access to the file until it has been opened. Now this was causing OS X to refuse access when boot2docker wanted to access the files. SILENTLY. Yay. 

So if a warning could be given when mounting 'quarentined' files, it would be fantastic... And perhaps save others the wasted time figuring this out. 

Cool.

**Comment by thaJeztah** [comment]
Nice find! And thanks for looking into the cause!

**Comment by cpuguy83** [comment]
I think this is worth a docs mention.

**Comment by thaJeztah** [comment]
@cpuguy83 agreed. Wondering if this should be in the Docker or Boot2Docker docs. I'll have to test if this also affects docker directly (when the *build context* contains downloaded files), or only when accessing the files via VBox shared volumes.

@alexisvincent in your setup, does this only affect files that are used in a volume? Or also if they are *added* to an image (ie `COPY some-downloaded-file /dest/in/image`)?

**Comment by alexisvincent** [comment]
Only if they are mounted through VBox... Here are a few considerations:
- DockerMachine is probably the better place to send this.
- User will probably use docker or compose to mount, so if a message should be displayed it should be in those tools not docker-machine.
- I'm not sure how the other drivers respond to this (VMWare Fusion for instance...)

**Comment by thaJeztah** [comment]
Thanks for adding that information! Tough one, I *think* it's more useful in Boot2Docker than machine (machine also is used with other drivers), but yeah, a mention in machine docs could be useful

@SvenDowideit wdyt? Also, do you know if Fusion shows the same problem?

**Comment by alexisvincent** [comment]
Awesome. My guess is that it will. I can test it actually...
May take some time
