### ISSUE TITLE
docker pull fails on overlay storage, hard to reproduce

### ISSUE THREAD

**Issue by orzel** [docker/docker#11184]
I got several systems, whose common configuration is
* kernel 3.18.8
* go 1.4.x
* docker 1.5.0
* os : gentoo/amd64
* overlay storage over ext4 filesystem on a dedicated partition (/var/lib/docker)

On some of them, it works just great. On two of them, it fails with the same error : 

orzel@verdi /home/orzel% docker pull ubuntu
511136ea3c5a: Pull complete 
511136ea3c5a: Download complete 
fa4fd76b09ce: Error downloading dependent layers 
117ee323aaa9: Verifying Checksum 
2d24f826cb16: Download complete 
2d24f826cb16: Error pulling image (latest) from ubuntu, operation not supported 
FATA[0221] Error pulling image (latest) from ubuntu, operation not supported 

The relevant log is not very useful (to me):
...
time="2015-03-05T23:23:50+01:00" level="info" msg="+job trust_update_base()"
time="2015-03-05T23:23:50+01:00" level="info" msg="-job trust_update_base() = OK (0)"
time="2015-03-05T23:23:52+01:00" level="info" msg="+job trust_key_check(/library/ubuntu)"
time="2015-03-05T23:23:52+01:00" level="info" msg="-job trust_key_check(/library/ubuntu) = OK (0)"
time="2015-03-05T23:23:52+01:00" level="info" msg="Image manifest for ubuntu:latest has been verified"
time="2015-03-05T23:27:25+01:00" level="error" msg="Error from V2 registry: operation not supported"
Error pulling image (latest) from ubuntu, operation not supported
time="2015-03-05T23:27:31+01:00" level="info" msg="-job pull(ubuntu, latest) = ERR (1)"

On the failing servers, it's 100% reproducible. I tried starting from a clean (empty) /var/lib/docker, but this doesn't change anything.

I tried to understand the difference between the servers where it works and those, but i can't find any. If you have any suggestions.

On the failing servers, i can turn around the probleme by switching to the btrfs backend storage or the devmapper one. It works well then.

**Comment by orzel** [comment]
update : i got a third system with same configuration and same errors. I tried using kernel 3.19.1, but this doesn't solve the problem. Reminder : some other servers work well, with (it seems to me) the same software stack.

**Comment by cpuguy83** [comment]
@orzel Can you provide the output of `docker info` and `docker version`?
I'm willing to bet you are using RC1 of Docker 1.5

**Comment by orzel** [comment]
I don't think so. The Gentoo package name is quite unambiguous, "1.5.0". Here's the requested output : 

carmen ~ # docker info                                                                                                                                        
Containers: 0                                                                                                                                                 
Images: 2                                                                                                                                                     
Storage Driver: overlay                                                                                                                                       
 Backing Filesystem: extfs                                                                                                                                    
Execution Driver: native-0.2                                                                                                                                  
Kernel Version: 3.19.1                                                                                                                                        
Operating System: Gentoo/Linux                                                                                                                                
CPUs: 4                                                                                                                                                       
Total Memory: 3.789 GiB                                                                                                                                       
Name: carmen                                                                                                                                                  
ID: GWY4:JVMW:DXSE:CL6L:3ODO:2PR7:VBDY:DLRP:OJKK:UYHX:6BU7:K4HB                                                                                               
carmen ~ # docker version                                                                                                                                     
Client version: 1.5.0                                                                                                                                         
Client API version: 1.17                                                                                                                                      
Go version (client): go1.4.2                                                                                                                                  
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.2
Git commit (server): a8a31ef


Docker reports 'images. I guess that's part of the failling pull. "docker images" report lines like this one : 
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
<none>              <none>              37208f16715c        8 days ago          0 B

**Comment by orzel** [comment]
Ok, i've found out what the problem was.
I was missing CONFIG_EXT4_FS_SECURITY and CONFIG_EXT4_FS_POSIX_ACL in my kernel. This is not reported by check-config.sh in docker 1.5.0.

Actually, it's not the first time this script fails me. On one server, i couldn't user docker neither, the error was mentionning "cpuset". I've fixed the problem by adding CONFIG_CPUSETS to my kernel. This was NOT reported neither by check-config.sh.

This script is very useful indeed, but it would be great if it was more carefully maintained ;-)

**Comment by SvenDowideit** [comment]
This is a bit surprising - `contrib/check_config.sh` contains lines that `check_flags EXT4_FS_POSIX_ACL EXT4_FS_SECURITY | sed 's/^/  /'` and `CONFIG_CPUSETS` is also there.

**Comment by orzel** [comment]
Not here, in docker-1.5.0.tar.gz:contrib/check-config.sh i have nothing related to "CONFIG_CPUSETS" and the ext4 stuff is only tested for other storage backends. The overlay backend check for exactly one setting (OVERLAY_FS), no less, no more.
