### ISSUE TITLE
Proposal: Operational Intent - Drivers API

### ISSUE THREAD

**Issue by jainvipin** [docker/docker#11188]
## Proposal: Operational Intent - Drivers API

Authors: @jainvipin, @mapuri, @tgraf, and @dvorkinista

This document recommends the APIs used to implement the goal described in Operational Intent for Docker Deployment (#11187). The proposal is a work in progress and needs community input.

### Definitions 
* Driver: An entity that exposes the infrastructure capability and takes the scheduler and/or operational intent distribution to realize the operational intent.
* Capability: A smallest unit of a unique hardware or software feature that an application can leverage. The capabilities are exposed by the backend drivers e.g. network or storage extensions. Capabilities are also associated with the containers to allow the best match-making of needs vs. availability for a given operational intent 

The driver API proposed is expected to run on each node that is candidate for resource scheduling.

### Capability Structure

```
type Caps struct {
    Name        string
    Type        interface{}
    Value        interface{}
    GroupId    string
    OptionalData    string
}
````
The above structure can generically specify a variety of capabilities, that could then be acted upon by rest of the system generically. 

* Name is an string (arbitrary) that uniquely identifies a capability. It must be unique for a type of driver e.g. network driver, storage driver, or compute. It is also assumed that all drivers emit the capability uniformly. Please see the validation of the capabilities below.
* Type and Value are defined to be an generic interface, because it can be one of the following:
 1. Qualitative: These capabilities are supported or not supported by the drivers. i.e. the type is ‘bool’. For example a host can exhibit “vxlan-offload” capability, or “aes’ encryption capability, etc.
 2. Quantitative: These capabilities represent a value associated with the capability i.e. the type is ‘int’. For example a driver can expose network bandwidth of 10Gbps. The normalization of the values is done by drivers and validating the capabilities against the set described for a given deployment. It is the scheduler that will allow the allocation of quantitative resources in the system.
 3. Buckets: These capabilities represent a set of possible string values that a driver can support. For example a driver can expose a capability called “Priority” that can be “low”, “medium”, or “high”. Usually an application is assign one of the buckets.
* GroupId: arbitrary association of resource grouping. This could help share some of the resources between hosts because they belong to a specific group. For example, two hosts can share an external storage and expose the capability accordingly. An empty GroupId is valid in case an anticipated grouping is not desired.
* OptionalData: This is an optional metadata that driver wants to expose, not consumed by the scheduler, however can be used in variety of ways by scheduler, and other entities, that is outside the scope of this document.

For example, a network driver can advertise following capabilities:

```
        capsToPublish := []Caps{
        {
                Name: "vxlan-offload",
                Type: "qualitative",
                Value: "supported",
                GroupId: "",
                OptionalData: "",
        },
        {
                Name: "bandwidth",
                Type: "quantitative",
                Value: "10G",
                GroupId: "",
                OptionalData: "",
        },
        {
                Name: "qos",
                Type: "set",
                Value: []string{"low", "medium", "high"},
                GroupId: "",
                OptionalData: "",
        },
        {
                Name: "encryption",
                Type: "qualitative",
                Value: "not-supported",
                GroupId: "",
                OptionalData: "",
        }}
```

### Driver APIs
The proposed changes optionally extend the APIs defined in extensions drivers. For example [network drivers](#9983) can be extended as follows.

```
// The APIs below calls for extending driver APIs to allow for
// capabilities to be discovered and propagated

type Driver interface {

  //  Init - return various capabilities during driver initialization
  Init() ([]Caps, error)

  // Update - this event is triggered seldom, but possible if the host discovers a
  // resource availability or .its unavailability after Init was called. It however requires
  // a host level event to know that this API needs to be called to fetch newer capabilities
  FetchCapabilities() ([]Caps, error)

  // AddNetwork and DeleteNetwork to take in []Caps, which can be passed in 
  // either as ‘params’ in proposed APIs or a separate argument. This is TBD
  // The driver is expected to allocate the resources for the network and its endpoints
  // that were indiciated in the arguments by []Caps
  AddNetwork(netid string, params []string) error
  // OR
  AddNetwork(netid string, params []string, []Caps) error

}
```
Similar applicable changes can be assumed for storage and compute resource advertisement.

### Capability Validation
For quantitative and buckets type of capabilities the validation requires ensuring that the values fall within the allowed range (for a specific deployment). Ensuring consistency for drivers to publish the information is critical, but can be done with a consistent set of driver running within a cluster.

A validation schema can be thought of as an array of ‘network’, ‘storage’ and ‘compute’ capabilities that are a superset of the allowed/permitted capabilities.

### Scheduler use of capabilities

Depending on the type of capability, scheduler could make respective decisions without knowing the details of the capability:
- Qualitative Capability: it can help in yes/no type of decision for job placement, etc.
- Quantitative Capability: it can help keeping track of the capabilities and deducting them against the available pool for a given GroupId. The allocated value is communicated back to the driver to consume for a specific container that was allocated the resource
- Buckets Capability: Use it as a policy criteria to map the desired policy to available policies for a given capability

A validation schema can be thought off as an array of ‘network’, ‘storage’ and ‘compute’ capabilities that are a super-set of the allowed/permitted capabilities.

### Items to be discussed 
- Type of Capability: Qualitative, Quantitative, and Buckets may not represent all abstractions of capabilities and extending capabilities into arrays/sets and/or Maps may be needed for certain situations. Exploring specific use cases would help clarify how scheduler and rest of the system can consume them.
- Flatten out the Capability information: Most generically, structured data is not as friendly as opaque data, therefore it calls for flattening the capabilities structure. However doing this may jeopardize the scheduler function without knowing and parsing the details of capabilities. Note that transporting capabilities, when marshalled, is not structured and the arguably APIs can use marshalled data instead of using Caps structure. However, the structure would need to be understood by the scheduler.
- Explore storage-driver API functions as community discussions around that settles
- Explore if there is a generic way to feed in compute capabilities, which doesn’t have a extension drivers but nonetheless require generic representation. And so, who does it and how swarm backends consume them in a flexible way. This needs to be discussed.

**Comment by LK4D4** [comment]
plugins were implemented.
