### ISSUE TITLE
Record an updated video / screencast on how to install Docker on Windows

### ISSUE THREAD

**Issue by spf13** [docker/docker#11192]
While there is a video already on the installation page, it is silent and a bit out of date. The installation documentation could really benefit from a video which walked the user through how to install the latest Docker on Windows and had narration explaining what to do. 

The installation instructions for Windows are available at https://docs.docker.com/installation/windows/

While I don't have personal experience with it, I understand that ezvid is free software that works well to capture, narrate and upload screen casts. http://www.ezvid.com/

When complete please upload to Youtube under a Creative Commons license and submit a pull request to add the video to the installation documentation page.

**Comment by ahmetalpbalkan** [comment]
This can easily go out of date when we release Docker 1.6 with docker.exe (client) and provide Chocolatey distribution as well. @spf13 please feel free to assign me, I'll happily do once I finish those stuff.

**Comment by nebulae1** [comment]
#dibs

**Comment by ahmetalpbalkan** [comment]
@nebulae1 please do not #dibs this, with the 1.6 release the instructions will significantly change and we will have more than one distribution methods. (also you can see I dibs'ed above :smile:) @jessfraz to remove the party-related labels.

**Comment by nebulae1** [comment]
Ok... thought it would be a good one since I just completed the install...

**Comment by ahmetalpbalkan** [comment]
@nebulae1 we will be slightly changing the boot2docker installation process by installing docker.exe on windows and it will no longer put users ssh-ed into boot2docker VM.

it will be also usable through cmd.exe/powershell, therefore instructions are changing a lot. I will be updating documentation as well as shooting new videos for this as you can see referenced above. https://github.com/boot2docker/windows-installer/issues/80

Thanks.

**Comment by ahmetalpbalkan** [comment]
@spf13 ^ ?
