### ISSUE TITLE
Proposal: Add some feedback info when user run daemon with --selinux-enabled option

### ISSUE THREAD

**Issue by MabinGo** [docker/docker#11197]
The docs describes that "SELinux does not presently support the BTRFS storage driver". 
When i run Docker Daemon with command as follow, Docker Daemon is running successfuly,
    docker -d -s btrfs --selinux-enabled=true

I found the reason is that i have not config selinux, and function selinuxEnabled in sourcecode return false, so the error as follow was not implemented, the Docker Daemon goes on running.
    if selinuxEnabled() && config.EnableSelinuxSupport && driver.String() == "btrfs" {
		return nil, fmt.Errorf("SELinux is not supported with the BTRFS graph driver!")
    }

As above, in my opinion, maybe we can add some logs about selinuxEnabled return result to advoid  user misunderstand it.

Thanks.

[Docker info]
Containers: 0
Images: 108
Storage Driver: btrfs
Execution Driver: native-0.2
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04 LTS
CPUs: 4
Total Memory: 3.666 GiB
Name: mabin-PC
ID: JRLZ:LAQV:CT2Z:WLEF:CCEB:J24M:HY75:GBOK:Y3A5:6Y2B:OLM3:CKXZ
No Proxy: localhost,127.0.0.0/8,::1

**Comment by thaJeztah** [comment]
I think PR https://github.com/docker/docker/pull/11274 is created for this?
