### ISSUE TITLE
Explain the +x behavior when context packaged from Windows CLI

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/docker#11206]
We need docs to explain the by design behavior changed at #11148. Feel free to assign to me, although I'm not sure where to document this. Maybe ADD/COPY instructions in Dockerfile documentation would be nice. @tiborvass

**Comment by cpuguy83** [comment]
Is this done?

**Comment by ahmetalpbalkan** [comment]
Yep b

**Comment by christianbundy** [comment]
@ahmetalpbalkan Is there somewhere I can still find this? I wasn't able to find anything in `/docs/`. Thanks!
