### ISSUE TITLE
Docker pulls over port 443 failing

### ISSUE THREAD

**Issue by joedborg** [docker/docker#11201]
Behind a corporate proxy, that only allows port 80 out, docker pulls fail because they are refused port 443

```
$ docker pull fedora:latest
Pulling repository fedora
FATA[0000] Get https://index.docker.io/v1/repositories/library/fedora/images: dial tcp 162.242.195.84:443: connection refused 
```

Is there any workaround for this?

**Comment by cpuguy83** [comment]
No, all pulls must go over https, and the index only responds to 443 for this.
Really strange the corporate proxy doesn't allow 443... I'm sorry there isn't much help we can do here.

**Comment by joedborg** [comment]
Which is fine, but if I specify HTTPS_PROXY, shouldn't Docker respect this?
