### ISSUE TITLE
docker push to private registry requires unix user match docker user

### ISSUE THREAD

**Issue by theonlydavidlee** [docker/docker#11215]
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

I would expect that when I docker login to my private registry:
docker login -u {userName} -p {password} -e {email} https://{registryFqdn}

I should be able to perform docker push {regsitryFqdn}/{image} ; however I find that actually fails.

INFO[1062] POST /v1.17/auth                             
INFO[1062] +job auth()                                  
INFO[1062] +job resolve_index(https://rcdn6-vm67-9.cisco.com) 
INFO[1062] -job resolve_index(https://rcdn6-vm67-9.cisco.com) = OK (0) 
INFO[1062] successful registry login for endpoint https://rcdn6-vm67-9.cisco.com/v1/: Login Succeeded 
INFO[1062] -job auth() = OK (0)                         
INFO[1065] POST /v1.17/images/rcdn6-vm67-9.cisco.com/registry-test/push?tag= 
INFO[1065] +job push(rcdn6-vm67-9.cisco.com/registry-test) 
INFO[1065] +job resolve_repository(rcdn6-vm67-9.cisco.com/registry-test) 
INFO[1065] -job resolve_repository(rcdn6-vm67-9.cisco.com/registry-test) = OK (0) 
Error: Status 401 trying to push repository registry-test: <html>
<head><title>401 Authorization Required</title></head>
<body bgcolor="white">
<center><h1>401 Authorization Required</h1></center>
<hr><center>nginx/1.7.10</center>
</body>
</html>

INFO[1065] -job push(rcdn6-vm67-9.cisco.com/registry-test) = ERR (1) 

** UNLESS **

I am using the same user for the push as I did for the login.

Is this a limitation of nginx? or the docker push?  I was a little confused and couldn't find any clear information online.

My expectations:

whoami?  mrlee

mrlee> docker login -u testUser -p test123 -e test@test.com https://registry.com
mrlee> docker push registry.com/test

... but that fails

testUser> docker login  -u testUser -p test123 -e test@test.com https://registry.com
testUser> docker push registry.com/test

... this works, push is successful

**Comment by dmp42** [comment]
The unix user that you use (where the cli is ran) should have no relation whatsoever with the registry you communicate with (unless you are launching your nginx/registry on the same machine using the same user account?).

Unfortunately, it's hard to tell what's going on here without more details.

Would you be able to come on irc (#docker-distribution) for a faster exchange? Or provide (when things fail):

 * nginx logs
 * registry version and logs
 * docker daemon logs when run in debug mode (`docker -d -D`)

Thanks a lot.

**Comment by thaJeztah** [comment]
@theonlydavidlee @dmp42 have you been able to solve this issue on IRC? If so, could you close this issue (for housekeeping)? Thanks!

**Comment by dmp42** [comment]
@theonlydavidlee let me know if you fixed your issue, or are still looking for help.
You can rea

**Comment by dmp42** [comment]
@theonlydavidlee let me know if you fixed your issue, or are still looking for help.
You can reach out on irc or the forums for general user support.
