### ISSUE TITLE
Public Registry v1 API no longer returns 'Access-Control-Allow-Origin: *' header

### ISSUE THREAD

**Issue by blakelapierre** [docker/docker#11224]
As of a day or two ago, the public registry (https://registry.hub.docker.com/v1) API would return the HTTP header:

    Access-Control-Allow-Origin: *

As of a few hours ago, the header is no longer returned in responses from the API, breaking cross-origin access to the registry.

I haven't been able to find any announcements or anything in the commit logs regarding this change. Anyone know what happened and what needs to be done to restore the header?

**Comment by dmp42** [comment]
(cc @kencochrane @johncosta for reference)

@blakelapierre hub issues are handled by the support: https://support.docker.com

Can you file a ticket there? (I'm closing this, then, since there is nothing we can do from here)

Thanks a lot.

**Comment by blakelapierre** [comment]
I'll try there. I looked at the docker-registry repo, but after looking at the issues it sounds like Hub doesn't run off that code (at least not vanilla), even though it exposes the same/similar API.

Is it correct that the Hub is not an OSS project?

**Comment by thaJeztah** [comment]
@blakelapierre correct, the Docker Hub is not open source and not handled via the GitHub issue tracker. https://support.docker.com/ is the location for reporting issues with Docker Hub
