### ISSUE TITLE
DNS confused when switching WiFi networks

### ISSUE THREAD

**Issue by mcandre** [docker/docker#11220]
When I switched WiFi networks, `apt-get update` stopped working in my Ubuntu Docker container. Attempts to reach `archive.ubuntu.com` timed out.

As a mitigation, I ran `boot2docker restart` (MacBook Pro host). In the future, how can we improve networking so that Docker containers gracefully change with their hosts, for more mobile users?

For reference, I'm using the `ubuntu:12.04` image as a base.

**Comment by dmp42** [comment]
It seems this is a boot2docker issue - docker does update itself when resolv.conf changes.
Assuming I'm correct, I would suggest opening an issue over at https://github.com/boot2docker/boot2docker

**Comment by cpuguy83** [comment]
Hi, Docker 1.5 has a host `/etc/resolv.conf` watcher which automatically updates containers' `/etc/resolv.conf` files.

**Comment by mcandre** [comment]
I'm using Docker 1.5 and boot2docker 1.5, and somehow this problem still happens on my machine (MacBook Pro mid-2014).

**Comment by dmp42** [comment]
@mcandre Then this is a boot2docker (or even a vagrant bug).
Reporting your configuration and b2d versions over there will definitely help them.

**Comment by mcandre** [comment]
Good idea!

https://github.com/boot2docker/boot2docker/issues/776
