### ISSUE TITLE
"depth" function wanted

### ISSUE THREAD

**Issue by liuzheng712** [docker/docker#11226]
When I make DockerImg, I found the ALL Img file become bigger and bigger(The latest version may not be too big).
And then push it to the hub for share.
Until now it's works fine.
Then , when I pull it from the hub, I'll download all history of this docker Img make life.
Is any way like `git clone GITURL --depth 1` to get the latest Img file?
like `docker pull DOCKER --depth 1` to get the latest Img file

Thank EveryOne

**Comment by cpuguy83** [comment]
Hello, I think in practice this is really a dup of #6906
I'm closing this but if you feel I'm mistaken please post here.

**Comment by liuzheng712** [comment]
@cpuguy83 Thanks , before I create this issue , I didn't find similar one 
This issue you give me is what I want.
Really thank you
