### ISSUE TITLE
docker run chokes with many concurrent requests

### ISSUE THREAD

**Issue by mjsalinger** [docker/docker#11228]
I'm starting/stopping many docker containers in a short timeframe (hundreds/sec.)  Docker seems to choke on this and be able to process only one at a time, even on a large multicore machine.  There also seems to be a real slowdown in starting an individual container as more and more requests are made (so even though they appear to synchronously start, the individual start takes several seconds as opposed to the typical ~200-300ms).

**Comment by cpuguy83** [comment]
It may or may not help, but you can try starting docker with `GOMAXPROCS=<# of cores>`

**Comment by mjsalinger** [comment]
Thanks, I tried that but it did not really seem to help.

**Comment by thaJeztah** [comment]
@cpuguy83 could the graphdb (SQLite) also play a role here? Not sure, but could creating multiple containers concurrently lead to (e.g.) transactions block other processes? For example; this will get triggered (possibly multiple times) for each container being created; [pkg/graphdb/graphdb.go#L131](https://github.com/docker/docker/blob/f7a449f92b88ca2a3db2fb33abade8c25a19c390/pkg/graphdb/graphdb.go#L131) (called by  [daemon/daemon.go#L570](https://github.com/docker/docker/blob/2380004d30769e9abc2a975dc9f89d83cc459d5f/daemon/daemon.go#L570))

**Comment by unclejack** [comment]
Please provide the full output of `docker info`, `docker version` and `uname -a`.

**Comment by mjsalinger** [comment]
Docker Info
```
Containers: 0
Images: 137
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 3543
Execution Driver: native-0.2
Kernel Version: 3.13.0-45-generic
Operating System: Ubuntu precise (12.04.5 LTS)
CPUs: 16
Total Memory: 29.4 GiB
Name: aw-kinvey-mt-us1-kbl-42
ID: CIXL:7AZQ:WIYX:VKSR:U3DS:2PII:KAZV:BIRG:FGK7:FLJK:C7BX:ASKY
WARNING: No swap limit support
```

Docker Version
```
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

ulimit -a
```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 240390
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 240390
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Comment by mjsalinger** [comment]
Any insights?

**Comment by BlakeMesdag** [comment]
@mjsalinger have you tried using the overlayfs filesystem driver? It's only available on >= 3.18 kernels though.

**Comment by LK4D4** [comment]
@thaJeztah Yup, sqlite locks is longest in whole Docker. They x1000 times longer then second long.
@mjsalinger I'm glad that we have highload case now. I think we can improve concurrency a lot by removing `graphdb`, because we actually have no graphs.

**Comment by mjsalinger** [comment]
@BlakeMesdag I'll take a look at overlayfs. 

@LK4D4 Let me know if there's anything I can do to help - providing data, testing, etc...  Would love to see and help work towards improvements in this area.

**Comment by thaJeztah** [comment]
A first quick improvement in the graphdb could be to remove this; [graphdb.go#L141](https://github.com/docker/docker/blob/f7a449f92b88ca2a3db2fb33abade8c25a19c390/pkg/graphdb/graphdb.go#L141). I don't think it adds anything; inserting a duplicate id should already be handled by the primary key constraint in the database.

**Comment by LK4D4** [comment]
@thaJeztah You can try and measure :) There is profiling urls in docker which can be enabled with `DEBUG` environment variable.

**Comment by thaJeztah** [comment]
@lk4d4 ah! Didn't know that. I'm out of town until Monday, but that's nice to fiddle with :)

**Comment by mjsalinger** [comment]
@LK4D4 What is graphdb used for currently, and what would you envision replacing it with?

**Comment by Sirupsen** [comment]
Like @BlakeMesdag pointed out, your problem here is most likely with AUFS, not with the GraphDB (we haven't seen issues with the GraphDB). We had similar problems with BTRFS, but switching to Overlay completely fixed it for us.

**Comment by mjsalinger** [comment]
OverlayFS seems to have solved this issue.
