### ISSUE TITLE
Disable ncurses progress bar when not in a tty

### ISSUE THREAD

**Issue by mcandre** [docker/docker#11233]
As a Unix user, I want Docker to disable the ncurses-style progress bar output for `docker pull` and other subcommands when Docker is running in a non-tty context, so that I can pipe Docker commands to other programs, and run Docker commands in an Emacs dumb terminal, without the Docker output being mangled.

**Comment by dmp42** [comment]
Hello. That sounds like a duplicate of #3694
I'm closing this then - please scream if you feel this is not right :)
