### ISSUE TITLE
docs/base image not updated during make docs

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#11230]
I just noticed that `make docs` doesn't make sure that the latest image for the [docs/base](https://registry.hub.docker.com/u/docs/base/builds_history/147632/) image is pulled, causing http://docs.docker.com and http://docs.master.dockerproject.com to use an older version of the stylesheet(s).

I'm not sure if this is something to be fixed in the https://github.com/docker/docs-base (explicitly tagging releases) or in the Makefile (always perform a `docker pull`).

ping @SvenDowideit (I think)

**Comment by SvenDowideit** [comment]
if you make the Makefile do a `docker pull`, then you won't be able to make local changes to the docs-base image to test your changes to that project. explicitly tagging the docs-base repo won't help either, as we're building the image using automated builds.

I _think_ @jfrazelle has solved this for `docs.master.docker.com` in the build automation though.

**Comment by jfrazelle** [comment]
Yes has been solved for master builds but that's a different script

**Comment by thaJeztah** [comment]
@jfrazelle are you working on this?

**Comment by jfrazelle** [comment]
no should I be?

**Comment by thaJeztah** [comment]
@jfrazelle hm, reading that back that came out a bit demanding (sorry!). I was informing, because I wasn't sure *where* this needs to be fixed; Based on the discussion above I thought it was something to be fixed on the build/CI servers :smile:

Is the script that runs on docs.master.dockerproject.com in this repo? And is it possible to make the same fix for the "live" docs?

**Comment by jfrazelle** [comment]
that script is on a build server for live docs we could add it to the
makefile
