### ISSUE TITLE
Enhance --link to connect to host's networks, and rewire ports

### ISSUE THREAD

**Issue by dhbaird** [docker/docker#11247]
In #1143, @altaurog proposed a `--link-host` option, which I'd like to resurrect for consideration, to link to host ports, with port number rewiring. At the moment, Ambassador provides this ability, but requires forwarding through a proxy (socat). Here's an example concept for --link-host:

```
docker run --link-host hostip:hostport:aliasport[:hostport:aliasport:...]:alias
# where hostip is any routable IP from the host, or 127.0.0.1 for localhost
```

There is an alternative practice of using `--add-host=alias:$(hostip)`, but this practice doesn't address the port rewiring that could be required.

Thanks for your consideration.

**Comment by cades** [comment]
+1

**Comment by cusspvz** [comment]
+1

**Comment by lynchc** [comment]
+1

**Comment by chiavegatto** [comment]
+1

**Comment by thaJeztah** [comment]
Not sure if this is going to be part of that (yet), but with the 1.7 release, there will also be "experimental" builds, to allow testing future features.

With the integration of libnetwork in Docker 1.7, there's work in progress for a Network-API, see this pull request for what's being worked on; https://github.com/docker/docker/pull/13441

**Comment by thaJeztah** [comment]
I asked a maintainer of libnetwork if this scenario will be supported with the coming features and he added some additional information in a comment; https://github.com/docker/docker/pull/13441#issuecomment-105059157

**Comment by mavenugo** [comment]
Thanks @thaJeztah . I would recommend opening an issue in `libnetwork` & if there is enough interest, this feature can make it to appropriate drivers (inbuilt or external)

**Comment by LK4D4** [comment]
links is not a way to make containers talk to each other now.
