### ISSUE TITLE
Postgres contianer becomes a zombie after being terminated with `pg_ctl stop`

### ISSUE THREAD

**Issue by korya** [docker/docker#11243]
### Description of problem:
I'm running postgres using the official docker image `postgres`. After I try to stop the running container using `pg_ctl stop`, the container becomes a zombie: I can see it `docker ps` but I cannot remove it using `docker rm`. 

### `docker version`:
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8

### `docker info`:
Containers: 6
Images: 72
Storage Driver: aufs
 Root Dir: /mnt/sda/var/lib/docker/aufs
 Dirs: 84
Execution Driver: native-0.2
Kernel Version: 3.16.7-tinycore64
Operating System: Boot2Docker 1.4.1 (TCL 5.4); yungsang/boot2docker : 7683f7c - Sat Dec 20 05:05:14 UTC 2014
CPUs: 2
Total Memory: 1.938 GiB
Name: boot2docker
ID: 3O3R:VMPS:OQEI:GHL5:AUVZ:BS5F:3EAQ:ZAOD:PW3A:DRTZ:BBNY:MMDG
Debug mode (server): true
Debug mode (client): false
Fds: 23
Goroutines: 19
EventsListeners: 0
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda/var/lib/docker

### `uname -a`:
Linux boot2docker 3.16.7-tinycore64 #1 SMP Sat Dec 20 04:43:15 UTC 2014 x86_64 GNU/Linux

### Environment details (AWS, VirtualBox, physical, etc.):
Running in boot2docker environment from my mac.

### How reproducible:
For me the reproduction rate is 100%

### Steps to Reproduce:
1. `docker run -d --name zombie postgres`
2. `docker exec zombie gosu pg_ctl stop`
3. `docker rm -f zombie`

### Actual Results:
```
Error response from daemon: Cannot stop container 745eb59d61c8aaa45f916bedf9c320d8c994a29c269ba5e235f07ec8edd222a8: no such process
FATA[0000] Error: failed to stop one or more containers
```

### Expected Results:
The container is removed.

### Additional info:
Shutting down the container using `docker stop` or `docker kill` works as expected:
```
docker run -d --name ppp postgres
docker stop ppp # or docker kill ppp
docker rm -f ppp
```

**Comment by cpuguy83** [comment]
Hi, please try on Docker 1.5.0.
I'm pretty sure this is resolved there.
Closing since this should already be resolved, but if it's still an issue please post here.

Also note, you should use the `docker stop` or `docker kill -s <sig>` command to stop the foreground process of a container and not do this through `docker exec`

**Comment by korya** [comment]
Yes, I understand that using `docker stop` or `docker exec` is the best way to go.
But the scenario described here is definitely a bug. That's why I've reported it.

I'll try to reproduce with docker 1.5 once it is released.

**Comment by cpuguy83** [comment]
@korya Docker 1.5 has been out for a few weeks now :)

**Comment by korya** [comment]
These are great news! :)

I've just upgraded to 1.5 on my Ubuntu machine, and tried to reproduce the bug. Indeed it was fixed.
Now, I can even restart the container after it was `pg_ctl stop`-ed.
