### ISSUE TITLE
Docker pull doesn't run nicely in a virt-builder environment

### ISSUE THREAD

**Issue by purpleidea** [docker/docker#11241]
It's a bit tricky to get docker pull to run nicely in a virt-builder environment. For a single one shot pull command it would be nice to not require a daemon, or have it startup, run a command, and then exit.

If someone with some knowledge of the docker daemon internals could look at the upstream virt-builder bug and provide some recommendations going forward, this would be great.

https://bugzilla.redhat.com/show_bug.cgi?id=1195881

Thanks

**Comment by purpleidea** [comment]
In particular, see comment 4:

https://bugzilla.redhat.com/show_bug.cgi?id=1195881#c4

Suggesting that there could be a daemon bug and why.

**Comment by purpleidea** [comment]
@GordonTheTurtle still a bug.

**Comment by icecrime** [comment]
@purpleidea Thanks! After discussing with the team, it seems that there's no bug in the docker daemon here. I understand the issue my not be fully resolved, but it doesn't seem like a fix is required in this repository. I'll close this one, but feel free to file a new issue if a daemon-side issue is confirmed!
