### ISSUE TITLE
Proposal: docker ps output templates

### ISSUE THREAD

**Issue by schmunk42** [docker/docker#11249]
In many cases I'd need a slightly different output for `docker ps` and I'd like to do that with some kind of template...

eg. current output
```
5ec41e89cc27        nginx:1                      "nginx -g 'daemon of   20 hours ago        Up 20 hours         0.0.0.0:49163->443/tcp, 0.0.0.0:49164->80/tcp   playground_nginx_1  
```

with `--template=custom`
```
5ec41    nginx:1     Up 20 hours     49163->443/tcp, 49164->80/tcp   playground_nginx_1  
```

**Comment by thaJeztah** [comment]
Perhaps something like `docker ps --format="{{ go template}}"`?

**Comment by calavera** [comment]
This issue has been superseded by #12931. Follow that PR for the awesomeness :metal: 

Closing this issue.
