### ISSUE TITLE
Proposal: Default file permissions for when they don't exist (or are defaulted)

### ISSUE THREAD

**Issue by mitchcapper** [docker/docker#11246]
Recently I noticed a number of Dockerfiles I had broke, and in tracking it down it seems the recently file permission defaults have been changed (primarily around windows users).

I would purpose default file permissions when permissions are unknown (or too promiscuous if wanting to handle other bad actors) would be 644 or 755.

This is primarily talked about in issue #11047 and pull request #11148.   I think the primary intent was to:
A) Make sure files added from the windows CLI are executable by default
B) Try to make defaults more secure rather than less (many Windows commands that grab permissions get 666 by default)

To this end the code changes resulted in a mask of 711 applied to windows files by default, and the execute bit being manually set.
With the permissions most commonly being 666 this results on 600 and with the manual setting of the execute bit 700.

This prevents files from being world readable by default.  

Security is good, and I think this was in part argued as an improvement for security by default (as someone adding a private key will not have that key world writable).  There was also an example given that if someone set Windows ACLS to prevent all other users from accessing that file, they may have the expectation that carries over when the file is added to a container.

The issues I purpose with this code is:

*) Container files are not (by default) accessible by other containers.  Containers are generally expected not to be running multiple users inside one container (while fully possible I think is rarely done, and probably not often a use care for it).  This means the only benefit restrictive read permissions have on something in a container has is of very limited scope (and only one use case I believe). That case is if the container itself is dropping to another user.  Dropping to another user requires additional privileges and is not as secure as running the container as the user to start.

*) There is the obvious convenience factor this causes a problem for for example:
 FROM busybox
 RUN adduser -D bob
 ADD test.conf /tmp/
 USER bob
 CMD cat /tmp/test.conf

no longer works with this change on windows, an additional chmod is required.  In addition older AUFS drivers are not great on overlapping permissions/ownership (issue #6047).  

*) Sensitive files are generally regarded as best practice NOT to be committed into containers.  If this is the case, then the default benefit is reduced.

*) Net security is possibly degraded and not improved.   While file permissions are tighter on added/copied files and this would seem better, i think it will harm a far more important security feature of running containers as another user.   Most users by far run docker containers as root.  This can be seen as many of the most popular dockerfiles in the hub do not work out of the box if run as non-root.  While the security benefits of running a user (vs user dropping in the container) even with crap dropping can be debated, it is no doubt most secure not to run containers as root.  This change will make even more Dockerfiles broken for running as non-root. I think this is the wrong direction the project would want to be moving.

*) I think the assumption that users expect Windows ACLS to be honored in file transfers/copies is not common.  To start Windows ACLS are generally folder specific (files inherit from the folder, and often that folder from its parent).  That means if I copy a file to even another folder on a Windows machine that another user has access to they can generally read the file.  While this is certainly overridable (windows ACLS are certainly very granular).   In addition, short of copying a file using SMB to another windows host or another drive, none of the file transfer apps I have ever used have preserved windows ACLS.

I think this is critical to settle before the next freeze.  Projects should try to ever avoid changing defaults to be less secure, especially as drastic as this could be down the line.   If permissions go out as they are now,  so files added default to not being group/world readable users will expect that functionality going forward.  If it ends up being decided later on this was the wrong choice, and its better to have files readable by default its very hard to make this transition as you could cause people relying on the previous security to now be exposed.  Conversely while tightening security (if so desired) in the future may break apps (as it has here) it does not leave user data possibly vulnerable. 

I apologize this is not a PR I have not dived into much of the docker code yet so do not know exactly where this is set for everything.  I am not sure if PR #11148 touched everything or just effected archiving (as it primarily looks like the latter).  I would suggest this extends to files fetched from the web using ADD or COPY (however as I think that is already in 0.50 I am not sure that would be something people would move for).

**Comment by mitchcapper** [comment]
For an example dockerfiles like:
redis: https://github.com/docker-library/redis/blob/062335e0a8d20cab2041f25dfff2fbaf58544471/2.8/Dockerfile
registry: https://github.com/docker/docker-registry/blob/0.9.1/Dockerfile
go: https://github.com/docker-library/golang/blob/1a422afd7db928a821e97906ed27ed606e2f072a/1.3/Dockerfile
Jenkins: https://github.com/cloudbees/jenkins-ci.org-docker/blob/f313389f8ab728d7b4207da36804ea54415c830b/1.554.1/Dockerfile

(any just keep going down the list) will not work out of the box  as they use add/copy commands (without chmod afterwards) if built in windows when then running as a non-root user.

**Comment by thaJeztah** [comment]
I think we can get more flexibility once https://github.com/docker/docker/pull/9934 (and https://github.com/docker/docker/pull/10775) has been implemented. It would still require changes to the Dockerfile though, to make sure the right permissions are set for each `COPY` / `ADD`.

/cc @duglin

**Comment by mitchcapper** [comment]
Without a doubt adding those additional options are good, but I don't think a lot of Dockerfiles will use those by default.   Right now building on windows will not result in the same image as building on linux (and not just not the same but will not work as non-root in most cases).   In addition even users who are savvy enough to build their own dockerfiles for windows and understand the problem will add a chmod after virtually every add/copy command if they want to run as non-root.

While I don't know if the +x on every file is a great idea, (I don't think it can hurt however and should help insure compatibility).   The masking needs to be less strict for windows and comes at little security change.  I put together a small PR for this: #11395

**Comment by thaJeztah** [comment]
@mitchcapper I agree the current situation isn't ideal; there was some discussion around this and decided that this was the "least worst" solution because of the limitations on Windows, also with security issues in mind.

**Comment by mitchcapper** [comment]
Jeztah I just am not sure when a windows user would actually expect owner only permissions by default.  In addition that security only is ever better in a case when a container starts as root and drops to another user and that user should not be accessing that sensitive file (not supposed to be stored in a docker image anyway).   In any other situation there is no security benefit I can see.

Just my thoughts, for my use cases I can certainly work around the issue but I think it will leave the windows users, especially those who care most about security (so want to run containers not as root) at a disadvantage and with errors that are a bit harder to fix.

**Comment by ahmetalpbalkan** [comment]
Hi @mitchcapper, I haven't seen this since I wasn't mentioned.

I agree with your example Dockerfiles which do not build on Windows due to clearing of r/w bits of others/group and we discussed with this in the proposal/PR you brought up.

Honestly I don't expect people to build those complicated base image Dockerfiles in windows CLI initially and we had to make this trade-off in my proposal. This was the call back then, but it's most definitely not settled into stone.

The main argument was "windows people will not notice that private keys are 0755 by default". I don't see how this fix deals with that.

> Sensitive files are generally regarded as best practice NOT to be committed into containers.

I am not sure if this is the case. Many people do add secrets like private keys into the containers. Do we have data or consensus to back that?

> Net security is possibly degraded and not improved. [...]  Most users by far run docker containers as root. 

I don't think this is the case unless we have some data to back this statement. If a container gets compromised (i.e. say through web application), the private keys which belong to some other user will be easily readable by default and that's what exactly we addressed with #11047.

> I think this is critical to settle before the next freeze.

This is probably not really a blocker as users can almost always can `RUN chmod` to unblock themselves and we can fix this in the upcoming versions if we agree on this fix.

> Jeztah I just am not sure when a windows user would actually expect owner only permissions by default.

Again, we don't have data about this. And certainly we don't rely on Windows users' Linux knowledge and taking security measures by clearing others/groups bits here.

-o-o- 

I think we can most definitely reconsider this. That's why I'm suggesting to go release with what we have and keep this issue open. If we gain some user base on Windows and receive more complaints we can definitely reiterate for improvement. Thanks @mitchcapper, let's stay on top of this.

**Comment by mitchcapper** [comment]
>The main argument was "windows people will not notice that private keys are 0755 by default". I don't see how this fix deals with that.

This certainly doesn't fix that private keys added to a container would be 755 by default, I was just saying I don't think there are many transfer applications that preserve windows level ACL's(especially at a folder level) so I doubt users would expect docker to (so I think the expectation of a file added to a container would be read all).  I don't think any other container/vm/etc apps have this as the default behavior either (ie copying a file into VMware windows VM doesn't preserve the ACL's).
> I don't think this is the case unless we have some data to back this statement. If a container gets compromised (i.e. say through web application), the private keys which belong to some other user will be easily readable by default and that's what exactly we addressed with #11047.

I can't imagine most users aren't starting docker containers as root, given the fact that many of the popular images do not work out of the box as non root.    Most users are not running containers with multiple users inside one container (possible but given the default action of one process per container I think unlikely).  If they are running the container as root, that user can read all files by default.  If they run the container as another user, the private keys would have to be readable to that user.  This is only improving security if
A) They use many users in one container or
B) They run the container as root and the process drops to another user (more common).

> This is probably not really a blocker as users can almost always can  RUN chmod  to unblock themselves and we can fix this in the upcoming versions if we agree on this fix.

Yep not a blocker.  The reason I was pushing for a choice before hand was due the less than desired security practice of making things less secure by later versions.  Once this change rolls out if Bob writes a dockerfile adding a private key to a container and checks to make sure its only 600 (which under docker 0.6 it is so he doesn't add a chmod command).  If docker reverts its permissions to windows being user readable by default, and Bob then upgrades to docker 0.7 (or what have you) when they rebuild that container their file (that previously they verified was 600) is now not.

However if you don't have much user base then worse case you hurt a few users so it doesn't matter as much:)

**Comment by ahmetalpbalkan** [comment]
@mitchcapper is this resolved?

**Comment by thaJeztah** [comment]
Looks like it yes. I'm going to close this, because this should be resolved in https://github.com/docker/docker/pull/11395.
