### ISSUE TITLE
Problem caused by old vendor/src/xxx version

### ISSUE THREAD

**Issue by x1022as** [docker/docker#11252]
Hi, how often do docker update its vendor/src/xxx?
Recently, I am doing some further developing on logrus, and things go wrong because of the old version of vendor/src/github.com/Sirupsen/logrus. So can docker update logrus and other third-party applications? Thanks!
@tianon , @unclejack , @tiborvass , @jpetazzo

**Comment by tiborvass** [comment]
@x1022as What is the issue you're having with logrus?

**Comment by x1022as** [comment]
I am using logrus syslog hook for some practical trial, and logrus fails to transfer these logs to socket, latest logrus will do.
The issue I met is not the point, I just think new version of third-party application may be better.
