### ISSUE TITLE
Add a docs team to the Docker organization

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#11259]
@docker/owners Ben suggested adding a docs organziation to docker.  Looks like a majority of docs folks approve (over email). Members are:

@spf13 
@fredlf 
@SvenDowideit 
@jamtur01 

and myself as well please.

**Comment by thaJeztah** [comment]
Out of interest; is this purely an internal change, or does it bring changes to the way things work for the project; what is the different between an "organization" and the current ["subsystem"](https://github.com/docker/docker/blob/master/MAINTAINERS#L401)?

**Comment by fredlf** [comment]
@thaJeztah It changes nothing other than creating the equivalent of a mailing list.

**Comment by thaJeztah** [comment]
@fredlf :smile: thanks for explaining!

**Comment by chenhanxiao** [comment]
@moxiegirl 
Maybe I can help too :)

**Comment by moxiegirl** [comment]
@chenhanxiao Thank you for the offer Chen. This is just a PR to remind the repo owners to create a notification group for docs.  So, @docker/docs-owners will work.
