### ISSUE TITLE
Proposal: extend --volumes-from to allow aliasing

### ISSUE THREAD

**Issue by anentropic** [docker/docker#11261]
If, for example, I have two web app containers each exposing a volume like `/var/www/static`

...I can't currently do `--volumes-from` these on my web server container as the paths conflict

It needs a way to alias the imported volumes, like how it's possible to specify `HOST_PATH:CONTAINER_PATH` when defining a volume

one might also want to import only a specific volume, rather than all volumes

I realise syntax for this is going to be a bit tricky

It seems only solution currently for my particular case is to give each app container a unique volume path?

**Comment by thaJeztah** [comment]
Perhaps a "base-dir"/"prefix", e.g. `--volumes-from=some-container:/some/path`, which will mount all volumes from `some-container` inside the `/some/path` directory in the container.

**Comment by cpuguy83** [comment]
You can bind-mount the volume path from 1 container into another.

I think the desire is to not overload `--volumes-from` and instead provide a higher-level volume management where you can just import the volume you want.

See #8484

**Comment by anentropic** [comment]
@cpuguy83  ok I think what I need is all covered in #8484 as long as it also applies in Docker Compose yaml as well as `docker run` cli

Piecing together what's discussed in that issue, we'll be able to do:

`docker run --volumes-from <volume alias>:<mount point>[:<mode>]`

...where `<volume alias>` is _"a container name + volume mount path"_ ...and [as per the docs](https://docs.docker.com/reference/commandline/cli/) we can specify `--volumes-from` multiple times to add multiple volumes

Looks great!

**Comment by Hronom** [comment]
F*ck, sorry for my stupid question, is this functionality implemented or not? Can't find...

Can I mount specific volume from data container to specific directory in app container?

### Example
Create container with volume:
```
docker create -v /dbdata --name dbstore training/postgres /bin/true
```
Then run app container that get volumes from `dbstore` image:
```
docker run -d --volumes-from dbstore --name db1 training/postgres
```
How I can mount `/dbdata` volume in `/work/dbdata` instead of `/dbdata` in `db1` container?

Please help me.

**Comment by cpuguy83** [comment]
@Hronom You'd have to get the volume name that was generated for that volume and use that. Names can be found via `docker inspect`

**Comment by Hronom** [comment]
@cpuguy83 As far as I understand you talk about solution like described here http://stackoverflow.com/questions/23137544/how-to-map-volume-paths-using-dockers-volumes-from ?

Is there possible more right way for doing this? With composer support?

**Comment by cpuguy83** [comment]
@Hronom Nope, solution is incorrect.

Every volume gets a name. Volumes get created in a number of ways:

- `docker volume create` [generated name is output to stdout]
- `docker volume create --name important-data`
- `docker run -v /foo  ...` [generated name]
- `docker run -v important-data:/foo ...`

The names for these volumes is in the `docker inspect output` under `Mounts`.
The very last example (above) shows how to mount a named volume... If a name for the given volume doesn't exist, a new volume will be created.

Don't use `volumes-from`. It's pretty useless, especially if you don't need all the volumes from a particular container.

docker-compose accepts the same syntax as above.
