### ISSUE TITLE
Problem with COPY and a single line file without a newline terminator

### ISSUE THREAD

**Issue by davewv31** [docker/docker#11266]
I'm attempting to use COPY, and I think I ran a problem when using it. It's fairly strange. 

I created 4 different files. The problem I'm having is with singleline_nocr_intellijosx.txt. It's as it sounds - create a one line file, in IntelliJ, on OSX, without putting an explicit carriage return at the end. 

Portion of my Dockerfile
`COPY . /tmp/xx`

On  my host system: 

    $ wc *line*
     2  3 35 multiplelines_intellijosx.txt
     1  1 12 singleline_explitcr_intellijosx.txt
     0  1 11 singleline_nocr_intellijosx.txt
     1  1 12 singleline_nocr_vi.txt
     4  6 70 total

The contents of singleline_nocr_intellijosx.txt are not copied over in the docker container, but it is created. All the other files are both created and populated correctly.

**Comment by duglin** [comment]
hmm can't seem to reproduce this.  Can you share your no-cr file with me?

**Comment by davewv31** [comment]
Would, but can't reproduce it either. I have this feeling I was clobbering it myself (can't find it), so I'm going to close this unless I can reproduce.

**Comment by duglin** [comment]
works for me  :-)
