### ISSUE TITLE
Remote API version mismatch shouldn't be an HTTP 404

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/docker#11262]
(Low priority issue)
https://github.com/docker/docker/blob/2a8a2d24285b40cf450f10dcb174dbef50e276ad/api/server/server.go#L1268 

Currently we return `HTTP 404` if client's remote API version is `>` server's remote API version. I think we can find a better status code to explain this (even BadRequest, PreconditionFailed, NotAcceptable are better than NotFound)

**Comment by RickWieman** [comment]
I agree.
It would be a one-line code change though (if we agree on something, I can open a PR for that :blush: )

**Comment by runcom** [comment]
I think it should return a 409 Conflict (`http.StatusConflict`) to be exact.
Also I think this should require a version bump (maybe) because client relying on 404 error won't be able to check this anymore (but again, I don't really know exactly)

**Comment by ahmetalpbalkan** [comment]
Closing this for the sake of #15188.
