### ISSUE TITLE
about  to verify .dockercfg permission.

### ISSUE THREAD

**Issue by HuKeping** [docker/docker#11276]
Docker will save the config file with permission 0600.

If someone has changed the permission say, 777, it is available for other users. The issue would lead to a secure risk.

should we check for this?

**Comment by HammerOfThor** [comment]
Do you mean .dockercfg?  .dockercfg file's owner is root, only root or sudoer user can change his permission. If user have root privilege, no security mechanism can stop him now.

Another similar security risk is .dockercfg save the username and password in plain text (base64 coding is not encryption), if user can read from .dockercfg, he can easily get all user's password.
But it's lucky that only root can read it.
This issue will not be a problem, I think.

**Comment by HuKeping** [comment]
Agree
