### ISSUE TITLE
Docker requires access to registry-1.docker.io when using registry mirror

### ISSUE THREAD

**Issue by jerrykan** [docker/docker#11275]
I have set up a number of internal docker hosts that do not have access to the outside world but are configured using `--registry-mirror` to point to an internal registry.

Performing a docker pull `<image>` results in the following error

    Get https://index.docker.io/v1/repositories/library/<image>/images: dial tcp 162.242.195.84:443: connection refused

It seems as though docker is attempting to access index.docker.io instead of the internal registry.

If I try a similar set up on a docker host that does have access to the outside world images are pulled from the internal registry without a problem.

I would expect that if a registry mirror is being used then there should be no need to dial out to index.docker.io when all it should needs to do is connect to the internal registry. Is there a setting to stop docker trying to connect to index.docker.io when configured to use a registry mirror? If not, can docker be fixed so that it doesn't attempt to connect to index.docker.io if a registry mirror is configured.

**Comment by dmp42** [comment]
v1 mirroring does indeed require access to the index unfortunately.
Since v1 is in maintenance now, it's unlikely it will be fixed.

The new v2 protocol (see https://github.com/docker/distribution) should feature a better protocol, with no need for direct net access.

**Comment by cpuguy83** [comment]
Closing since this isn't a docker issue and is instead an issue with the V1 registry.

**Comment by dmp42** [comment]
@cpuguy83 it's an issue with docker (specifically, with the v1 protocol design) - not an issue with the registry.

**Comment by jerrykan** [comment]
So my take-away from this is that it is not currently supported in v1 and won't be, but it may be supported in v2 but currently isn't. So there is currently no way to have an internal host pull images from an internal registry if it doesn't have access to index.docker.io?

**Comment by dmp42** [comment]
Correct - unfortunately, there is currently no way to do this.

**Comment by cpuguy83** [comment]
Ok, so this is really a close #wontfix?

**Comment by dmp42** [comment]
@cpuguy83 I would say so, yes.
