### ISSUE TITLE
docker load clobbers the name of the existing image

### ISSUE THREAD

**Issue by shishir-a412ed** [docker/docker#11285]
Description of problem:
Given an image "foo:latest" with ID 1234 already in docker, docker load < foo.tar with ID 5678 (same name, different ID) clobbers the existing name (of ID 1234) to "<none>".  Since images are most often referenced by name, it's not a very nice thing to do w/o being documented or issuing a "Warning: image foo already exists, renaming to <none>".

Version-Release number of selected component (if applicable):
docker-1.4.1-12.el7.x86_64

How reproducible:
Minor prep. required.

Steps to Reproduce:
1. docker run --name foo rhel7 /bin/true
2. docker commit foo foobar
   (note image ID)
3. docker save foobar > foobar.tar
4. docker rm foo
5. docker rmi foobar
6. docker run --name bar rhel7 /bin/false
7. docker commit bar foobar
   (note image ID)
8. docker rm bar
9. docker load < foobar.tar
10. docker images

Actual results:
[root@dockertest ~]# docker images
REPOSITORY                         TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
foobar                             latest              17be95040cc3        13 seconds ago      147 MB
...cut...
[root@dockertest ~]# docker load < foobar.tar
[root@dockertest ~]# echo $?
0
[root@dockertest ~]# docker images
REPOSITORY                         TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
<none>                             <none>              17be95040cc3        29 seconds ago      147 MB
foobar                             latest              90e44769e068        2 minutes ago       147 MB

Expected results:
Allow the load, but issue "Warning: existing image will be renamed <none>"
-or-
Document this in a "note" in the docker load man page
-or-
Fail the load with a 'image foobar already exists'

Additional Info: Docker load creates a new image with {ID: 5678} but also clobbers the name of the existing image {ID: 1234}

**Comment by termie** [comment]
+1
