### ISSUE TITLE
SECURITY ISSUE: Docker --link exposes source containers environment

### ISSUE THREAD

**Issue by jamercee** [docker/docker#11284]
When linking containers, the target container has full access the source containers ENV settings. In some cases, this can expose sensitive information from the source.

For example, say you create a mysql container.

    docker run --name db -e MYSQL_ROOT_PASSWORD=password -d mysql

And now link this container, and inspect the environment

    docker run --rm -ti --link db:db debian
    # env | grep ^DB_ENV
    DB_ENV_MYSQL_ROOT_PASSWORD=password
    DB_ENV_MYSQL_VERSION=5.6.22
    DB_ENV_MYSQL_MAJOR=5.6

With a complete copy of the source container's environment, that target container now has a copy of the mysql root password. This is a major security hole! 

Any random code or module within the linked container could use the mysql root password to connect and wreak havoc. And if the mysql database is shared with multiple containers (say wordpress, joomla, docker, etc...), the havoc could be global across the entire ecosystem.

I've scrutinized the docs on linking containers
https://docs.docker.com/userguide/dockerlinks/#environment-variables. But it
does NOT describe this behavior (which is why I suspect this is a bug).

Obviously we could create an ENTRYPOINT script that we run in the target to sanitize the environment, but this would require that every container author would need to remember todo this. This opens the door to all sorts of mistakes.

-----
*Our setup*

    # uname -a
    Linux hostname 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt2-1~bpo70+1 (2014-12-08) x86_64 GNU/Linux

    # docker --version
    Docker version 1.4.1, build 5bc2ff8

**Comment by duglin** [comment]
This is a dup and was resolved (sort of) via: https://github.com/docker/docker/pull/11172

**Comment by jfrazelle** [comment]
Also in the future if you read the contribution guidelines security issues
go to security@docker.com NOT github issues. But seeing as this is known
and expressed in the docs it's fine.

**Comment by jamercee** [comment]
Can you point me to where this is documented? I scrutinized the two PR's AND the docs, and I see people talking about updating the docs, but for the life of me I can't see any reference to the fact that all environment variables are available in the target container.

**Comment by duglin** [comment]
See: https://github.com/docker/docker/pull/11172/files#diff-77bbbc90ae4435415f7a4f6007374f75R191

**Comment by jamercee** [comment]
Thanks

**Comment by vrastogi** [comment]
Ok, I see this is documented, but is there a way to do the linking behavior, i.e., exposing ports to the linking container, but without exposing the environment?

**Comment by thaJeztah** [comment]
@vrastogi in docker 1.9 you can use the new "network" feature. If you create a custom network and connect your containers to that (`--net=mynetwork` or `docker network connect mynetwork mycontainer`), then containers can reach each other by the name of the container. Only containers in the same network can reach each other.

It's not a full replacement for links yet, because currently there's no "alias" option (i.e. you can only reach another container by it's name), but that's being worked on, and hopefully finds its way in docker 1.10

**Comment by vrastogi** [comment]
@thaJeztah thanks, this is helpful to know.
