### ISSUE TITLE
devicemapper fails with "Device or resource busy"/"invalid argument" on pull 

### ISSUE THREAD

**Issue by FossiFoo** [docker/docker#11286]
Hi.

Contrary to other reports here, i can't even pull a single image into my docker without a failure. Fresh install, after "rm -rf /var/lib/docker/" & reboot.

Gentoo, docker 1.5.0, kernel 3.19.1

$ docker info
---

Containers: 0
Images: 0
Storage Driver: devicemapper
 Pool Name: docker-8:3-7063782-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 305.7 MB
 Data Space Total: 107.4 GB
 Metadata Space Used: 729.1 kB
 Metadata Space Total: 2.147 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.88 (2014-08-05)
Execution Driver: native-0.2
Kernel Version: 3.19.1
Operating System: Gentoo/Linux
CPUs: 8
Total Memory: -2.147e+09 B
Name: lsd
ID: QJJW:2A6K:IRLW:26PP:TYQU:CI5Z:T2LD:NG5L:2ZHH:UVDO:SIZS:RQAB
 
$ docker --version
---

Docker version 1.5.0, build a8a31ef
 
$ docker run ubuntu:14.04 /bin/echo 'Hello world'
---
Unable to find image 'ubuntu:14.04' locally
511136ea3c5a: Download complete
511136ea3c5a: Error downloading dependent layers
fa4fd76b09ce: Downloading 12.87 MB/197.2 MB 1m10s
117ee323aaa9: Verifying Checksum
2d24f826cb16: Download complete
2d24f826cb16: Error pulling image (14.04) from ubuntu, endpoint: https://registry-1.docker.io/v1/, Error mounting '/dev/mapper/docker-8:3-7063782-511136ea3c5a64f264b78b5433614aec563103b4d42d24f826cb16: Error pulling image (14.04) from ubuntu, Error mounting '/dev/mapper/docker-8:3-7063782-511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158' on '/var/lib/docker/devicemapper/mnt/511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158': invalid arFATA[0006] Error pulling image (14.04) from ubuntu, Error mounting '/dev/mapper/docker-8:3-7063782-511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158' on '/var/lib/docker/devicemapper/mnt/511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158': invalid argument

mount info:
---

cmewes@lsd ~ $ mount -v
/dev/sda3 on / type ext4 (rw,noatime,data=ordered)
devtmpfs on /dev type devtmpfs (rw,nosuid,relatime,size=10240k,nr_inodes=192628,mode=755)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /run type tmpfs (rw,nodev,relatime,size=1237072k,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
cgroup_root on /sys/fs/cgroup type tmpfs (rw,nosuid,nodev,noexec,relatime,size=10240k,mode=755)
openrc on /sys/fs/cgroup/openrc type cgroup (rw,nosuid,nodev,noexec,relatime,release_agent=/lib/rc/sh/cgroup-release-agent.sh,name=openrc)
cpu on /sys/fs/cgroup/cpu type cgroup (rw,nosuid,nodev,noexec,relatime,cpu)
cpuacct on /sys/fs/cgroup/cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpuacct)
memory on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
devices on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
freezer on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
perf_event on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
tmpfs on /var/tmp/portage type tmpfs (rw,relatime,mode=775,uid=250,gid=250)
/dev/sda3 on /var/lib/docker/devicemapper type ext4 (rw,noatime,data=ordered)

Debug log:
---

DEBU[0011] image does not exist on v2 registry, falling back to v1 
DEBU[0011] pulling v1 repository with local name "ubuntu" 
DEBU[0011] [registry] Calling GET https://index.docker.io/v1/repositories/library/ubuntu/images 
DEBU[0011] https://index.docker.io/v1/repositories/library/ubuntu/images -- HEADERS: map[User-Agent:[docker/1.5.0 go/go1.4.1 git-commit/a8a31ef kernel/3.19.1 os/linux arch/386]] 
DEBU[0011] hostDir: /etc/docker/certs.d/index.docker.io 
DEBU[0011] Retrieving the tag list                      
DEBU[0011] https://registry-1.docker.io/v1/repositories/library/ubuntu/tags -- HEADERS: map[User-Agent:[docker/1.5.0 go/go1.4.1 git-commit/a8a31ef kernel/3.19.1 os/linux arch/386]] 
DEBU[0011] hostDir: /etc/docker/certs.d/registry-1.docker.io 
DEBU[0012] Got status code 200 from https://registry-1.docker.io/v1/repositories/library/ubuntu/tags 
DEBU[0012] Registering tags                             
DEBU[0012] https://registry-1.docker.io/v1/images/2d24f826cb16146e2016ff349a8a33ed5830f3b938d45c0f82943f4ab8c097e7/ancestry -- HEADERS: map[User-Agent:[docker/1.5.0 go/go1.4.1 git-commit/a8a31ef kernel/3.19.1 os/linux arch/386]] 
DEBU[0012] hostDir: /etc/docker/certs.d/registry-1.docker.io 
DEBU[0013] Ancestry: ["2d24f826cb16146e2016ff349a8a33ed5830f3b938d45c0f82943f4ab8c097e7", "117ee323aaa9d1b136ea55e4421f4ce413dfc6c0cc6b2186dea6c88d93e1ad7c", "1c8294cc516082dfbb731f062806b76b82679ce38864dd87635f08869c993e45", "fa4fd76b09ce9b87bfdc96515f9a5dd5121c01cc996cf5379050d8e13d4a864b", "511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158"] 
DEBU[0013] https://registry-1.docker.io/v1/images/511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158/json -- HEADERS: map[User-Agent:[docker/1.5.0 go/go1.4.1 git-commit/a8a31ef kernel/3.19.1 os/linux arch/386]] 
DEBU[0013] hostDir: /etc/docker/certs.d/registry-1.docker.io 
DEBU[0013] https://registry-1.docker.io/v1/images/511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158/layer -- HEADERS: map[User-Agent:[docker/1.5.0 go/go1.4.1 git-commit/a8a31ef kernel/3.19.1 os/linux arch/386]] 
DEBU[0013] hostDir: /etc/docker/certs.d/registry-1.docker.io 
DEBU[0014] server supports resume                       
DEBU[0014] [deviceset] AddDevice() hash=511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158 basehash= 
DEBU[0014] libdevmapper(6): ioctl/libdm-iface.c:1755 (4) dm info docker-8:3-7063782-base  OF   [16384] (*1) 
DEBU[0014] libdevmapper(6): ioctl/libdm-iface.c:1755 (4) dm message docker-8:3-7063782-pool  OF  create_snap 5 1 [16384] (*1) 
DEBU[0014] registerDevice(5, 511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158) 
DEBU[0014] libdevmapper(6): ioctl/libdm-iface.c:1755 (4) dm message docker-8:3-7063782-pool  OF  set_transaction_id 7 8 [16384] (*1) 
DEBU[0014] [deviceset] AddDevice(hash=511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158 basehash=) END 
DEBU[0014] activateDeviceIfNeeded(511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158) 
DEBU[0014] libdevmapper(6): ioctl/libdm-iface.c:1755 (4) dm info docker-8:3-7063782-511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158  OF   [16384] (*1) 
DEBU[0014] libdevmapper(6): libdm-common.c:2304 (4) Udev cookie 0xd4de466 (semid 425984) created 
DEBU[0014] libdevmapper(6): libdm-common.c:2324 (4) Udev cookie 0xd4de466 (semid 425984) incremented to 1 
DEBU[0014] libdevmapper(6): libdm-common.c:2196 (4) Udev cookie 0xd4de466 (semid 425984) incremented to 2 
DEBU[0014] libdevmapper(6): libdm-common.c:2446 (4) Udev cookie 0xd4de466 (semid 425984) assigned to CREATE task(0) with flags         (0x0) 
DEBU[0014] libdevmapper(6): ioctl/libdm-iface.c:1755 (4) dm create docker-8:3-7063782-511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158  OF   [16384] (*1) 
DEBU[0014] libdevmapper(6): libdm-common.c:1393 (4) docker-8:3-7063782-511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158: Stacking NODE_ADD (254,1) 0:0 0600 [verify_udev] 
DEBU[0014] libdevmapper(6): ioctl/libdm-iface.c:1755 (4) dm reload docker-8:3-7063782-511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158  OF   [16384] (*1) 
DEBU[0014] libdevmapper(6): ioctl/libdm-iface.c:1755 (4) dm resume docker-8:3-7063782-511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158  OF   [16384] (*1) 
DEBU[0014] libdevmapper(6): libdm-common.c:2231 (4) Udev cookie 0xd4de466 (semid 425984) decremented to 1 
DEBU[0014] libdevmapper(6): libdm-common.c:2496 (4) Udev cookie 0xd4de466 (semid 425984) waiting for zero 
DEBU[0014] libdevmapper(6): libdm-common.c:2246 (4) Udev cookie 0xd4de466 (semid 425984) destroyed 
DEBU[0014] libdevmapper(6): libdm-common.c:1393 (4) docker-8:3-7063782-511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158: Processing NODE_ADD (254,1) 0:0 0600 [verify_udev] 
DEBU[0014] activateDeviceIfNeeded(511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158) 
DEBU[0014] libdevmapper(6): ioctl/libdm-iface.c:1755 (4) dm info docker-8:3-7063782-511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158  OF   [16384] (*1) 
DEBU[0014] libdevmapper(6): ioctl/libdm-iface.c:1755 (4) dm info docker-8:3-7063782-511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158  OF   [16384] (*1) 
DEBU[0014] [devmapper] RemoveDevice START(docker-8:3-7063782-511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158) 
DEBU[0014] libdevmapper(6): libdm-common.c:2304 (4) Udev cookie 0xd4d784b (semid 458752) created 
DEBU[0014] libdevmapper(6): libdm-common.c:2324 (4) Udev cookie 0xd4d784b (semid 458752) incremented to 1 
DEBU[0014] libdevmapper(6): libdm-common.c:2196 (4) Udev cookie 0xd4d784b (semid 458752) incremented to 2 
DEBU[0014] libdevmapper(6): libdm-common.c:2446 (4) Udev cookie 0xd4d784b (semid 458752) assigned to REMOVE task(2) with flags         (0x0) 
DEBU[0014] libdevmapper(6): ioctl/libdm-iface.c:1755 (4) dm remove docker-8:3-7063782-511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158  OF   [16384] (*1) 
DEBU[0014] libdevmapper(3): ioctl/libdm-iface.c:1773 (-1) device-mapper: remove ioctl on docker-8:3-7063782-511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158 failed: Device or resource busy 
DEBU[0014] libdevmapper(6): libdm-common.c:2231 (4) Udev cookie 0xd4d784b (semid 458752) decremented to 1 
DEBU[0014] libdevmapper(6): libdm-common.c:2231 (4) Udev cookie 0xd4d784b (semid 458752) decremented to 0 
DEBU[0014] libdevmapper(6): libdm-common.c:2496 (4) Udev cookie 0xd4d784b (semid 458752) waiting for zero 
DEBU[0014] libdevmapper(6): libdm-common.c:2246 (4) Udev cookie 0xd4d784b (semid 458752) destroyed 
DEBU[0014] [devmapper] RemoveDevice END(docker-8:3-7063782-511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158) 
DEBU[0014] [devmapper] RemoveDevice START(docker-8:3-7063782-511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158) 
DEBU[0014] libdevmapper(6): libdm-common.c:2304 (4) Udev cookie 0xd4d8fd3 (semid 491520) created 
DEBU[0014] libdevmapper(6): libdm-common.c:2324 (4) Udev cookie 0xd4d8fd3 (semid 491520) incremented to 1 
DEBU[0014] libdevmapper(6): libdm-common.c:2196 (4) Udev cookie 0xd4d8fd3 (semid 491520) incremented to 2 
DEBU[0014] libdevmapper(6): libdm-common.c:2446 (4) Udev cookie 0xd4d8fd3 (semid 491520) assigned to REMOVE task(2) with flags         (0x0) 
DEBU[0014] libdevmapper(6): ioctl/libdm-iface.c:1755 (4) dm remove docker-8:3-7063782-511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158  OF   [16384] (*1) 
DEBU[0014] libdevmapper(6): libdm-common.c:1396 (4) docker-8:3-7063782-511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158: Stacking NODE_DEL [verify_udev] 
DEBU[0014] libdevmapper(6): libdm-common.c:2231 (4) Udev cookie 0xd4d8fd3 (semid 491520) decremented to 0 
DEBU[0014] libdevmapper(6): libdm-common.c:2496 (4) Udev cookie 0xd4d8fd3 (semid 491520) waiting for zero 
DEBU[0014] libdevmapper(6): libdm-common.c:2246 (4) Udev cookie 0xd4d8fd3 (semid 491520) destroyed 
DEBU[0014] libdevmapper(6): libdm-common.c:1396 (4) docker-8:3-7063782-511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158: Processing NODE_DEL [verify_udev] 
DEBU[0014] [devmapper] RemoveDevice END(docker-8:3-7063782-511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158) 
DEBU[0014] [deviceset docker-8:3-7063782] waitRemove(docker-8:3-7063782-511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158) 
DEBU[0014] libdevmapper(6): ioctl/libdm-iface.c:1755 (4) dm info docker-8:3-7063782-511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158  OF   [16384] (*1) 
DEBU[0014] Waiting for removal of docker-8:3-7063782-511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158: exists=0 
DEBU[0014] [deviceset docker-8:3-7063782] waitRemove(docker-8:3-7063782-511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158) END 
DEBU[0014] libdevmapper(6): ioctl/libdm-iface.c:1755 (4) dm message docker-8:3-7063782-pool  OF  delete 5 [16384] (*1) 
DEBU[0014] unregisterDevice(5, 511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158) 
DEBU[0014] libdevmapper(6): ioctl/libdm-iface.c:1755 (4) dm message docker-8:3-7063782-pool  OF  set_transaction_id 8 9 [16384] (*1) 
Error pulling image (14.04) from ubuntu, Error mounting '/dev/mapper/docker-8:3-7063782-511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158' on '/var/lib/docker/devicemapper/mnt/511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158': invalid argument
INFO[0014] -job pull(ubuntu, 14.04) = ERR (1)           
DEBU[0043] Downloaded fa4fd76b09ce9b87bfdc96515f9a5dd5121c01cc996cf5379050d8e13d4a864b to tempfile /var/lib/docker/tmp/GetV2ImageBlob240521677

**Comment by FossiFoo** [comment]
I'm not using devicemapper anymore, but switched to btrfs, so i don't know if this is still in the current release.

**Comment by icecrime** [comment]
@FossiFoo Thanks for the heads-up. I'm tentatively closing this one as we didn't hear from anyone else.
