### ISSUE TITLE
why Jenkins not Drone.io

### ISSUE THREAD

**Issue by HuKeping** [docker/docker#11304]
I wonder what makes docker from drone to Jenkins, I googled it but didn't get much info :)

**Comment by jfrazelle** [comment]
Hi!
We switch because we were already using a fork to run docker in docker and
we needed the Dockerfile to actually be built for each PR. We also wanted
distributed builds and to test across matrices.

**Comment by jfrazelle** [comment]
See drone/drone#1

**Comment by HuKeping** [comment]
Ok, thanks.

**Comment by HuKeping** [comment]
Hi @jfrazelle ,What does the "test across matrices" mean? Different hosts? I can't understand your meanings. Any advantage from jenkins?

**Comment by jfrazelle** [comment]
Yes we get to test different operating systems and storage drivers as well
as exec drivers
