### ISSUE TITLE
Docker log for containers taking up huge disk space. Any existing workaround from docker level?

### ISSUE THREAD

**Issue by sourav82** [docker/docker#11308]
As docker stores the stdout and stderr logs from containers for "docker logs", sometimes it grows beyond GB. Is there any way from docker to manage the growth of the JSON log file for containers?

**Comment by x1022as** [comment]
docker is working on Logging drivers #10568, released with docker 1.6.

**Comment by cpuguy83** [comment]
@sourav82 If you don't care about the logs you can just `echo "" > /path/to/log.json`
If you do care, you can pause the container, copy-truncate, unpause.

With the above mentioned log drivers, the goal is to make the json logger be for development purposes only and recommend a more robust solution for production.
