### ISSUE TITLE
Refactor iptables package into a library using kernel apis

### ISSUE THREAD

**Issue by therealprologic** [docker/docker#11301]
Right now the code https://github.com/docker/docker/blob/f3aed2a2974bba4fdca947227d877bcc2c7d540b/pkg/iptables/iptables.go seems to manipulate netfilter rules via exec'ing an external process ``iptables`` on the system.

Would it be possible to turn this into a library removing the need to rely on an external tool and sub-process to manipulate the netfilter rules? Is anyone working on this or interested in this enhancement?

Is this something that more generic network drivers can/could solve?

**Comment by therealprologic** [comment]
https://github.com/porjo/gonft looks interesting as a way forward from exec'ing out to ``iptables``. As nftables itself however is still under development perhaps this would have to wait for a much later version of the Docker engine?

**Comment by cpuguy83** [comment]
Indeed. iptables is designed such that you pretty much have to exec the iptables binary.
Relevant: http://stackoverflow.com/questions/109553/how-can-i-programmatically-manage-iptables-rules-on-the-fly

Closing since this isn't exactly actionable... and probably won't be for quite some time.

**Comment by therealprologic** [comment]
Agreed but worth bringing up :)

**Comment by LK4D4** [comment]
Actually it is possible with netlink, but pretty difficult. Also I think we probably don't need so much iptables in docker :)

**Comment by therealprologic** [comment]
Reason I bring this up is I'm interested in getting Docker engine/daemon to run in an environment where there is no libc and therefore no ``iptables`` command on the host (*because it can't be compiled statically*).

**Comment by LK4D4** [comment]
@therealprologic Actually Iptables doing not very much work. Some I think can be replaced with routes, some just worked around. I think it's doable, and it would be great if someone do that :)

**Comment by therealprologic** [comment]
Hmmm :)
