### ISSUE TITLE
How to use docker with adsl?

### ISSUE THREAD

**Issue by Colstuwjx** [docker/docker#11318]
Hi, I'm new to docker, and be curious about the docker networking.

I want to build an ubuntu host, and run multiple docker containers, the point is that I want to use adsl  inner the container, and container could use adsl to get ip.

I'm confused about the docker networking model in this case, and wishes anyone could give any idea.
Thanks.

**Comment by cpuguy83** [comment]
Hi,

This isn't really the appropriate forum for user support.
Please see one of the following:

1) docker-user mailing list
2) #docker on freenode
3) forums.docker.com

**Comment by Colstuwjx** [comment]
Ok, Thanks.
