### ISSUE TITLE
Wrong error returned when passing incorrect  "Binds" creating container

### ISSUE THREAD

**Issue by sunyc** [docker/docker#11312]
Hi,

While using REST API (up to 1.17) , we found a issue where Docker would always returning 404 No Such image error despite the image being perfectly valid.

Spending hours trying to figure out what went wrong, I discovered that Docker is blindly returning "404 No Such Image" error for every error returned by daemon contained with "no such" string...  Then we discovered that our issue was that we were passing a incorrect “Binds" param that contains an invalid path,  It would be good to fix the issue and show the correct error instead.

Cheers.

**Comment by cpuguy83** [comment]
Closing since this is fixed on master.

Feel free to test: https://master.dockerproject.com/
If you find that's not the case, please ping here.

Thanks!
