### ISSUE TITLE
Mongodb running in docker with Replica 

### ISSUE THREAD

**Issue by hordemark** [docker/docker#11313]
When running mongodb in docker with Replica, then

<code>
mongo
rs.initiate({"_id" : "rs0", "version" : 1, "members" : [ { "_id" : 0, "host" : "$mongodb_ip:27017" } ]})
</code>

But when restart mongodb container, this container IP  will be changed, and mongod daemon falied with Replica, because of different IP  compare with first.

Is there is solution static ip with container or mongodb container can fix dynamic when starting.

**Comment by cpuguy83** [comment]
Hi, there are a number of networking solutions that can do this for you, but not included with Docker itself.

For testing I'd recommend checking on github.com/jpetazzo/pipework
