### ISSUE TITLE
docker rename prevents container from starting after daemon restart

### ISSUE THREAD

**Issue by mattva01** [docker/docker#11315]
**Simpler reproductions in following comments, leaving the original for posterity**
Steps to reproduce:
1. Create a Dockerfile with the following contents:
```
FROM busybox
VOLUME /test
```
and build it.
ex: `docker build -t mattva01/renamebug .`
2. Create a container based off that image 
`docker run -d --name rename1  mattva01/renamebug`
3. Rename it
`docker rename rename1 rename2`
4. Restart docker daemon
`sudo service docker restart`
5. Attempt to start container
`docker start rename2`

You'll get an error that looks like the following:
```
Error response from daemon: Cannot start container rename2: Cannot find child for /rename1
```

Docker version:
```
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

Docker info:
```
Containers: 8
Images: 170
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 186
Execution Driver: native-0.2
Kernel Version: 3.13.0-43-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 1
Total Memory: 490 MiB
Name: sandbox
ID: IS3O:JS5I:ERVJ:PNTV:FNON:NRCL:UNMV:LIKS:24ET:NCJK:N7SN:BBDL
WARNING: No swap limit support
Labels:
 provider=digitalocean
```

**Comment by cpuguy83** [comment]
Confirmed

**Comment by mattva01** [comment]
Sorry about that, I was dead tired and was convinced it required a volume for some reason. Do

**Comment by coolljt0725** [comment]
It was a bug, I also can reproduce with
<pre><code> docker run --name name1 busybox
 docker rename name1 name2
service docker.io stop
service docker.io start
docker start name2
</code></pre>

**Comment by itzg** [comment]
Is there a workaround to get a container "un-renamed" back into working order?

**Comment by cpuguy83** [comment]
Manually edit the json file and restart the daemon.

**Comment by itzg** [comment]
Thanks, @cpuguy83 . And for those, like me, that didn't know about the `config.json` behind the curtain: edit the "Name" property of `/var/lib/docker/containers/$CONTAINERID/config.json` to match the new name.
