### ISSUE TITLE
Extend docker logs "--tail" option to support an offset (or add new flag)

### ISSUE THREAD

**Issue by fabioy** [docker/docker#11337]
It'd be great if "docker logs" had an "offset" option. This would allow users/tools to continue fetching logs from a previously known place. The current "--tail" option is useful at times, but not for continual logging.

Two potential options: extend the set of arguments allowed in the "--tail" option, or add a new option to "logs", like --offset.

**Comment by RickWieman** [comment]
Sounds like a nice idea. However, is it also going to be useful/effective if you have billions of log lines (as an extreme example)?
It might be a better idea to fetch your logs by date for example.

**Comment by fabioy** [comment]
I think it depends on who's consuming the logs. The offset option may be a cheap way to get this going, especially for things like reconnect while doing a "--follow". It shouldn't be a significant addition to the current "--tail" logic, I think (see https://github.com/docker/docker/blob/e4a49ae1885a7f80e713d1d1fc852f6e4214dfe6/daemon/logs.go)

**Comment by cpuguy83** [comment]
`docker logs` now supports a `--since` which can be used to implement this outside of docker itself.
Closing as I think this satisfies the use-case.

Thanks!
