### ISSUE TITLE
Volumes on CentOS 7 mount with weird ownership (and can't be used because of it)

### ISSUE THREAD

**Issue by jdoliner** [docker/docker#11339]
Steps to reproduce:

```shell
[host]$ mkdir test_volume
[host]$ docker run -v `pwd`/test_volume:/test_volume -ti ubuntu bash
[docker]$ touch /test_volume/foo
touch: cannot touch '/test_volume/foo': Permission denied
[docker]$ ls -lh | grep test_volume
drwxrwxr-x.   2 1000 1000   16 Mar 12 00:17 test_volume
```

The problem seems to be that volumes get mounted with weird ownership. Is this expected behavior and I just don't understand what I'm doing or is this a bug?

**Comment by cpuguy83** [comment]
This is because of selinux. You need to set the labels on your volumes.

If you don't know much on selinux, here's a great intro guide: https://people.redhat.com/duffy/selinux/selinux-coloring-book_A4-Stapled.pdf

To set the required label, do: `chcon -Rt svirt_sandbox_file_t /path/to/volume`
