### ISSUE TITLE
Add description of docker cp STDOUT functionality to master

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#11338]
In the next release, docker cp will support the STDOUT to tar feature.  The feature is already on the master branch under development. Download, test, and document the feature against the master binary.

**Comment by duglin** [comment]
@moxiegirl there has got to be a better way to do this.  Isn't master supposed to always be correct within itself?  Couldn't a PR (with just the 1.5 doc edits) be merged directly into the 1.5 branch you guys are working on w/o rolling back edits to master?

**Comment by crosbymichael** [comment]
Closing this as well because of the comments in #11305

**Comment by moxiegirl** [comment]
@duglin I was trying to make this that PR.  I might be doing it wrong of course ---. :-P 

Just as an FYI, we do want to improve the workflow. The goal is automatically push live certain doc PRs on merge.  We just are in the middle of Bday work.
