### ISSUE TITLE
Please publish infrastructure tools (Machine, Compose …) on APT repo

### ISSUE THREAD

**Issue by xaibeha** [docker/docker#11347]
Description of problem:

New infrastructure tooling not available in APT repo for Ubuntu.

`docker version`:
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

`docker info`:
Containers: 1
Images: 201
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 203
Execution Driver: native-0.2
Kernel Version: 3.13.0-40-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 2
Total Memory: 7.767 GiB
Name: micro-0
ID: G54E:DG6B:6V2W:5475:W3RI:G5GT:YPJH:XK76:FGBP:V3HA:YFIA:QZL3
WARNING: No swap limit support

`uname -a`:
Linux micro-0 3.13.0-40-generic #69-Ubuntu SMP Thu Nov 13 17:53:56 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
physical

How reproducible:
deterministic

Steps to Reproduce:
1. `sudo aptitude update > /dev/null && grep '^Package: ' /var/lib/apt/lists/get.docker.io_ubuntu_dists_docker_main_binary-amd64_Packages  | grep -v lxc-docker`

Actual Results:
No lines displayed.

Expected Results:
Lines for machine, compose…

Additional info:
—

**Comment by RickWieman** [comment]
Have a look at #11279; I think this is closely related :wink:

**Comment by xaibeha** [comment]
Indeed, commented there.

**Comment by jfrazelle** [comment]
closing this as a duplicate so as to not fragment the conversation
