### ISSUE TITLE
docker push prints empty error info when http response body contains trailing '\n'

### ISSUE THREAD

**Issue by HammerOfThor** [docker/docker#11346]
when user tries to push image to registry, and docker registry/hub respond with http error info whose http body contains trailing '\n', docker client will print "FATA[0000]" with nothing more, it's supposed to print "FATA[0000]: HTTP Code: XXX"
ping @dmcgowan ...

**Comment by duglin** [comment]
I wonder if https://github.com/docker/docker/pull/10924 will fix this.

**Comment by thaJeztah** [comment]
@HammerOfThor I see #10924 was merged; are you able to check if this issue has been resolved on "master"?

**Comment by dmcgowan** [comment]
This issue is still relevant. It will keep a blank line from showing up at the end but still not the desired output when containing multilines. With an nginx error page I now end up with `FATA[0000] </html>` instead of `FATA[0000]`.
