### ISSUE TITLE
docker run with image tag matches incorrectly

### ISSUE THREAD

**Issue by slaupster** [docker/docker#11348]
With images like:

apache                         test                d920a0e5d724        24 hours ago        243 MB
apache                         blatestbla          d920a0e5d724        24 hours ago        243 MB
apache                         latest              d920a0e5d724        24 hours ago        243 MB

Doing this:
 docker run -ti apache:test bash

Results in:
a67030c8678a        base-ubuntu:latest                    "bash"

not the 'test' tagged version.

It seems that when matching the tag the algorithm starts at the end of the string and works backwards and breaks at first match rather than completing the match.  Changing the tag to prevent the match with laTEST fixes the problem.

**Comment by cpuguy83** [comment]
This looks like a dup of #11294 so I'll close this one.
