### ISSUE TITLE
How to Assign static IP's to each of the docker image when ever it is running?

### ISSUE THREAD

**Issue by Pratap6** [docker/docker#11352]
Hi,
I'm unable to assign static IP to each of my docker images when it is starting, please suggest me any approaches are there?.

please do the needful.

**Comment by cpuguy83** [comment]
@Pratap6 Hi, as stated in the other issue, this is not a support forum

For support, please see any of these:
1) docker-user mailing list
2) #docker on IRC
3) forums.docker.com

You can try out https://github.com/jpetazzo/pipework for doing more advanced networking within the container.

**Comment by Pratap6** [comment]
Ok Thank you @cpuguy83
