### ISSUE TITLE
Multiple sections for 'Pause' command in CommandLine Reference Docs

### ISSUE THREAD

**Issue by hayderimran7** [docker/docker#11358]
Hi, in the commandline reference docs, there are two identical sections of docker "pause" command. 
Source : https://docs.docker.com/reference/commandline/cli/#pause
The content of both sections is same, just pointing out the redundancy. 
The order of sections is : Pause > Port > Pause .
It might be useful to have just one section for a command :)

**Comment by LK4D4** [comment]
@hayderimran7 Wow, thanks!

**Comment by duglin** [comment]
this has been fixed - I just can't seem to find the PR right now, but if you look at master the dup section is gone

**Comment by cpuguy83** [comment]
Closing since it sounds like this is fixed, if not, please ping here, thanks!
