### ISSUE TITLE
Best practices for updating security patches for containers

### ISSUE THREAD

**Issue by sourav82** [docker/docker#11361]
I was wondering the best ways to update the containers with latest security patches. I tried first with apt-get upgrade in the CMD script so that when container starts, it upgrades it. But it is time consuming to start a container every time and may even break the container. Sometimes, the containers are long running and sometime short lived but how to make the containers always updated? Another alternative I could think to update the base images offline and push to registry and invalidate all the containers that uses that image, but this should be done as a workflow in scheduled manner.

Any ideas or best practices or references would be very helpful here.

**Comment by cpuguy83** [comment]
Yes, you should update base images, rebuild your images, then recreate your containers.
I generally keep all my images on DockerHub, those images are _always_ automated builds, which are linked to their base images. When the base image updates, my image is automatically rebuilt.

In cases where you can't take down your containers, you could `docker exec <container> /bin/sh -c 'apt-get update && apt-get install -y <updated package> --no-install-recommends`
