### ISSUE TITLE
Allows containers to connect to host local-only services such as databases

### ISSUE THREAD

**Issue by orzel** [docker/docker#11376]
Takes the following very common pattern : a server hosts a database (say mysql) and several web applications. Those webapp are .. well, webapps, and hence present huge security risks, especially if coded in php or ruby.
So we dockerize them. The user feels no need to dockerize the database, among other reasons because  there are other (undockerized) programs than webapps that connect to it.

The database is listening to 127.0.0.1:XXX (3306 for mysql).

With current docker (1.5.0), this setup up is not possible. Containers can not connect to the database. There are quite some people asking for this on internet (check stackoverflow, some blogs, and this tracker).

Common "solutions" involve either
* opening the database (0.0.0.0:PORT instead of 127.0.0.1:PORT), which is a no-go for some obvious reasons

* make the database listen to the interface docker0. This prevent other services to connect to the database, and is error-prone (the database must be started after docker). Moreover, mysql documentation explicitely mentions that it is not possible for mysql to connect to two interfaces (here docker0 and localhost). "solutions" mentionning the docker option "--add-host" fall in this category.

* using docker run option "--host=net" (my current favorite), which makes the container far less secure by NOT using network separation. This is a kinda tradeoff between using docker and not.

**Comment by cpuguy83** [comment]
I'm pretty sure this is fundamentally impossible without `--net=host`... but I'll leave to others smarter than I to confirm and close.

One other alternative would be to setup a veth pair and have mysql listen on that.

**Comment by orzel** [comment]
Err.. my understanding is that it's not currently possible. The ticket is about requesting this feature. The use case seems quite important, isn't it ?

**Comment by cpuguy83** [comment]
@orzel What I'm saying is it is technically impossible to do this.
Localhost on the host is local only. You can only share localhost's if you are in the same net namespace.
So you can either `--net=host` or you don't use localhost.

**Comment by orzel** [comment]
It's also "impossible" to connect the container's network stack with outside, but somehow docker manages to do it (i see something with "proxy" with netstat on the host).

**Comment by cpuguy83** [comment]
No, it's not impossible to connect the container's network stack, this is done via the bridge and some iptables natting.
But also, the host cannot connect to the container's localhost, and vice-versa. 

You can setup a proxy to proxy connections to localhost, but then that proxy would need to be listening on something not localhost... which defeats the purpose of having it on localhost.

**Comment by phemmer** [comment]
Aside from what cpuguy83 has said, unix domain sockets would both solve this issue, and give you a performance boost as well.

Databases, such as postgres & mysql, support listening on unix domain sockets instead of TCP sockets. The advantages here are that you can forward unix domain sockets into a container via a volume mount (`docker run -v`). Unix domain sockets are also faster than TCP sockets as they don't have to go through the normal network stack. Unix domain sockets are also more secure, as you can set permissions on the socket file, where as with binding to TCP 127.0.0.1, anyone with access to the box can connect.

**Comment by orzel** [comment]
I know very well what sockets are and i actually use them locally as well. I'm totally sold to sockets :-)
It's not always possible though (typically, i use some vserver that can't access it, but can connect to 127.0.0.1).
I hadn't thought about connecting to those from containers though, and that seems indeed a good idea. 
iiuc, you mean something like 
   docker run -v /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock (...)
right ?
Or maybe only using the directory, i'm not sure if docker can 'volume' mount a file of such kind (socket).

anyway, thanks for the hint.

**Comment by phemmer** [comment]
Docker can volume mount sockets without issue. However the one catch that would encourage using the directory. When the daemon listening on the socket restarts, it has to unlink and create a new socket. Thus if docker is sharing the named socket explicitly, it'll be sharing the old one. Thus it's better to share the directory in this case.

As for applications which only support domain sockets, I just throw `socat` into the image, and start it up in the background inside the container (having it listen on 127.0.0.1, and forward to the named socket).

**Comment by orzel** [comment]
@phemmer : this last post of you is VERY useful. You should consider adding this to some documentation somewhere or at least in a blog post. I will definitely (volume) share the directory instead of the socket. I didn't know about socat, this is something very useful to know about in this context.

Thanks a lot !

**Comment by cpuguy83** [comment]
@orzel https://docs.docker.com/userguide/dockervolumes/#mount-a-host-file-as-a-data-volume

I'm going to go ahead and close this one, let me know if you think there's something else we can do here.
Thanks!

**Comment by orzel** [comment]
er??? I know how to use both types of docker 'volumes'. That's not the point.
My point about documentation is that both excellent Phemmer's points should be added to the documentation.
1) use volumes to make the socket available in container, using a volume on the directory containing the socket instead of only the socket.
2) use socat to provide a localhost(127.0.0.1) tcp connection inside the host from a socket

Note that this solves my problem, but not all cases. Typically if a service is only available as tcp on the host, containers can't use it.

The request feature is about accessing local-only (127.0.0.1) tcp services on the host from containers, and is still valid (or isn't it?).

**Comment by cpuguy83** [comment]
@orzel I would say it's not valid since it is literally impossible to do this.
