### ISSUE TITLE
Turn on moderation for new users for docker-user

### ISSUE THREAD

**Issue by pnasrat** [docker/docker#11371]
Spam is becoming an issue on docker-user - this actively damages the value of the list and the community

https://groups.google.com/forum/#!topic/docker-user/axfrk9fa8oA

Not sure how often core team read docker-user so filing an issue to turn on new member moderation - https://support.google.com/groups/answer/2627595?hl=en

This would require regular commitment from the community manger/team to regularly check the queue.

**Comment by ripienaar** [comment]
It's common in other projects to give community members in other timezone rights to moderate posts and I've seen this work well.  I'd be happy to do so in the UK timezone.

**Comment by cpuguy83** [comment]
cc @spf13

**Comment by spf13** [comment]
Thanks for bringing this to our attention. We've been working on a better solution for our users that will not only help to keep spam out, but will also enable community members to take more ownership of the channel. In the meantime we should turn on new member moderation and clean this mess up.

**Comment by Batmat** [comment]
I generally really don't comment with just +1 comment, but I'll do an exception here. Many users (including me) have already asked on the ML that such spams be moderated, and the spammers be kicked, to no avail. Thanks a lot for cleaning this quickly.

As one of the last mails said, simple solution:
http://www.xaprb.com/blog/2009/09/13/stopping-spam-on-google-groups/

Thanks in advance

**Comment by Batmat** [comment]
It keeps coming. Please... Moreover almost always from the same ones...

**Comment by pnasrat** [comment]
@spf13 can you audit the list and ban the current spammers.

https://groups.google.com/d/msg/docker-user/YcKgXKuwKiw/5q9t2TVPS1wJ

**Comment by hgomez** [comment]
+1 to moderation

**Comment by spf13** [comment]
I actually don't have access, but I've already alerted the people that do and asked for access myself so I can take care of it. I anticipate it will happen soon.

**Comment by dexterddit** [comment]
+1 to moderation

**Comment by phemmer** [comment]
On the subject of the docker-user google group, how about that intro? My own personal opinion, but the thing is overly huge, and doesn't even belong there. It reads like a sales pitch for docker, but that's what the docker web site is for (docker.com). It also hasn't been updated in ages: the first line still references http://github.com/dotcloud/docker.
Can we just get rid of it, or scope it so that it's something relevant to the mailing list, such as what is on-topic, what should be a github issue, etc?

**Comment by spf13** [comment]
I'm now an admin. I've enabled moderation of new members and will work on the other suggestions here over the next few days.

**Comment by Batmat** [comment]
@spf13 Beware that there seems to be a lot of already registered users that are actually only spammers. I don't know if you monitor docker-user, but there was another spam 5 minutes ago with the title "Best ETL TESTING Training", and that's indeed not the first mail from that "krishnasuma234@gmail.com"

**Comment by spf13** [comment]
Thanks @Batmat. I've banned the ones I saw. I've also been trying to create a new "moderator" role that we will give out to a handful of community members so they can police this as well. Unfortunately Google Groups has a bug that seems to prevent me from creating any roles. It says it's saved, but then doesn't actually create it. I've tried a few times now.

**Comment by Batmat** [comment]
@spf13 sindhujareddy7892@gmail.com to ban, don't know if you saw it.
