### ISSUE TITLE
iptables flag and bip flag

### ISSUE THREAD

**Issue by sbpaul** [docker/docker#11372]
Hi,

Just short: please add iptables and bip flags to the manifests and templates.

best,
Dennis

**Comment by cpuguy83** [comment]
What manifests and templates?

**Comment by sbpaul** [comment]
Sorry i try again. I woul be great if the puppet module would add the way that i can set the iptables and bip parameters for the deamon on installing. its the same as the DNS etc things

**Comment by jfrazelle** [comment]
We don't have a puppet module in this repo

**Comment by sbpaul** [comment]
oh sorry close this my fault
