### ISSUE TITLE
RPM %post scripts are not executed after a "yum install" but marked as <defunct>

### ISSUE THREAD

**Issue by AndreiMuresan** [docker/docker#11386]
Hello! My docker experience is not very big, that's why I wanted to ask you guys for some advises.
I'm trying to build a docker image, the final result should be a Drupal site, but I encountered some issues during the interactive building.
I have a drupal content RPM that should basically pupulate the drupal DB and the Files folder, all of this being executed as a %post rpm script. The content rpm installation part is ok, but the %post scripts are not executed, resulting several <defunct> processes "running" inside the container. As I can see here https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/ this is the desired behavior, after the "yum install" process is ended all his children are marked as <defunct>.
Now the question is: Is there a workaround for this? What would be the best option to fix my issue?

**Comment by thaJeztah** [comment]
@AndreiMuresan the issue tracker is not really the right place for support questions. Could you close this issue and use one of the following;

- the `#docker` IRC channel on freenode
- [docker-user](https://groups.google.com/forum/#!forum/docker-user) on Google Groups
- [forums.docker.com](https://forums.docker.com)
- [StackOverflow](http://stackoverflow.com/search?q=docker)

Thanks!
