### ISSUE TITLE
TestPullVerified fails on Docker master branch

### ISSUE THREAD

**Issue by swernli** [docker/docker#11383]
Running the TestPullVerified test (as part of 'make test-integration-cli') fails on the current master branch because the expected string "The image you are pulling has been verified" does not appear.

**Comment by swernli** [comment]
This looks like it's an issue with running the test more than once.  Since change https://github.com/docker/docker/pull/10594 added the logic to only output the verification message if the image was actually downloaded, the test will fail the second time since the image already exists and is not downloaded again.

**Comment by swernli** [comment]
Here is the output I'm seeing (note the image is already present, so verified message is not shown):
--- FAIL: TestPullVerified (0.81s)
        docker_cli_pull_test.go:71: pulling a verified image failed. expected: The image you are pulling has been verified
                got: latest: Pulling from hello-world
                511136ea3c5a: Already exists
                31cbccb51277: Already exists
                e45a5af57b00: Already exists
                Status: Image is up to date for hello-world:latest
                , <nil>
FAIL

**Comment by dmcgowan** [comment]
This was caused by #11265, I will see if we can come up with an alternative way to test pulling verified images. `hello-world` is normally used for pull tests since it is the smallest image.

**Comment by swernli** [comment]
Would it be possible to rework the test such that it checks for the presence of the hello-world image and deletes it if it is already there?

**Comment by dmcgowan** [comment]
My first attempt to fix is by changing the tag for the frozen image such that `hello-world:latest` is always pulled. I am uncomfortable with removing a local image which was placed there by the frozen script since any subsequent tests are making an assumption about its presence and version.
