### ISSUE TITLE
sort docker stats

### ISSUE THREAD

**Issue by k3ck3c** [docker/docker#11398]
docker stats could be enhanced with a sort on any column, e.g. hit 2 -> sort by cpu usage, 5 -> sort by network I/O downloading, 6 -> sort by network I/O uoloading

**Comment by ottok** [comment]
Once https://github.com/docker/docker/pull/14950 is accepted it should be trivial to run something like below to get the job done

```sudo docker stats --no-stream $(sudo docker ps|grep -v "NAMES"|awk '{ print $NF }'|tr "\n" " ") | sort -k 7,9 -h```

**Comment by sammcj** [comment]
+1 this would be really great, I'm going to log another issue to be able to stream the stats to a CSV or similar simple output file for process / aggregation.

**Comment by thaJeztah** [comment]
I think this issue should be closed; there's been a PR to implement this; https://github.com/docker/docker/pull/18277, but was rejected. current consensus is to implement a `--format` flag, as this would be more consistent with other parts of docker.
