### ISSUE TITLE
FATA[0000] invalid symlink when copying a symlink with relative parent paths

### ISSUE THREAD

**Issue by mikehaertl** [docker/docker#11394]
```Dockerfile
FROM debian:jessie

RUN mkdir -p /tmp/test/subdir1 /tmp/test/subdir2 \
    && touch /tmp/test/subdir1/a \
    && cd /tmp/test/subdir2 && ln -s ../subdir1/a
```

```sh
$docker build -t symlink .
[...]

$ docker run --rm -ti symlink ls -l /tmp/test/subdir2
total 0
lrwxrwxrwx 1 root root 12 Mar 15 13:05 a -> ../subdir1/a

$ docker create --name test symlink
287d64308a8264cf46bdde93cd53dc85abbc107c363736df89c0f6498f83c87c

$ docker cp test:/tmp/test .
FATA[0000] invalid symlink "test/subdir2/a" -> "../subdir1/a"
```

Tested on a Linux host. There was a similar issue (#7296) but it was suggested there, that I should rather create a new issue as the other issue was windows related and thus a different problem than this here.

UPDATE: Fixed the `Dockerfile`.

**Comment by phemmer** [comment]
First, can you provide `docker version` and `docker info`? I cannot reproduce this issue.

Second, I don't think this will do what you expect it to do.
Each `RUN` line is executed in a completely new container (and thus shell). Commands like `cd` are shell commands that affect the running shell. So the next line is a new shell and the working directory is not preserved.
You want one of:

    RUN cd /tmp/test/subdir2 && ln -s ../subdir1/a

or

    RUN ln -s ../subdir1/a /tmp/test/subdir2/

or

    WORKDIR /tmp/test/subdir2
    RUN ln -s ../subdir1/a

**Comment by mikehaertl** [comment]
I've just used several `RUN` commands to make it easier to read, but you're right with the `cd` of course. I can still reproduce it with a combined `RUN`:

```Dockerfile
FROM debian:jessie

RUN mkdir -p /tmp/test/subdir1 /tmp/test/subdir2 \
    && touch /tmp/test/subdir1/a \
    && cd /tmp/test/subdir2 && ln -s ../subdir1/a
```

I came accross this problem, when I tried to copy the `vendor/` directory of a Yii2 installation from a container to the host and it failed. 

```
$ docker --version 
Docker version 1.5.0, build a8a31ef

$ docker info
Containers: 9
Images: 282
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 300
Execution Driver: native-0.2
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 4
Total Memory: 3.86 GiB
Name: Nilar
ID: L3TB:7VOR:ICI6:4BX4:IR63:OY2Q:OIR3:4JFL:OUWQ:ZENL:4SIJ:E4YM
Username: mikehaertl
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support
```

My OS is actually Linux Mint 17.1 (based on Ubuntu 14.04 LTS).

**Comment by icecrime** [comment]
Adding this to the 1.8.0 milestone: please refer to https://github.com/docker/docker/pull/11514#issuecomment-112740856 for more details.

**Comment by visualphoenix** [comment]
Can we get this moved back to 1.7.x?

**Comment by vdemeester** [comment]
@mikehaertl cannot repro on 1.8.0-dev (with the merge of #13171), could you confirm that ? (note there is a typo in your repro example — ``RUN cd …`` would do nothing, should be ``WORKDIR``).

**Comment by mikehaertl** [comment]
@vdemeester Could not test with latest dev version but the problem still exists in 1.7.1.

I've now fixed the `Dockerfile` example in the top comment and removed the `cd ..` parts.

**Comment by vdemeester** [comment]
@mikehaertl yeah this behavior/bug is still present in 1.7.1 for sure, but the ``docker cp`` refactor/rewrite fixes that (#13171) and will be present in 1.8.0.

**Comment by mikehaertl** [comment]
@vdemeester Ok, will test when 1.8.0 is out.

**Comment by vdemeester** [comment]
@mikehaertl perfect :wink: (you can try it out with the rc(s) if you have time/resources — I think rc1 is already out)

**Comment by thaJeztah** [comment]
1.8.0-rc3 is out and (hopefully) the final RC for the release. Details can be found here; https://github.com/docker/docker/releases/tag/v1.8.0-rc3

**Comment by mikehaertl** [comment]
I've tested with docker 1.8.1 and confirm: the bug is gone.

Thanks!

**Comment by thaJeztah** [comment]
Thanks for testing and confirming!

**Comment by rubenanapu** [comment]
This issue seems to be back again on `Docker version 18.09.7, build 2d0083d`

**Comment by thaJeztah** [comment]
@rubenanapu could you open a new issue with details and steps to reproduce?

FWIW, tried reproducing the reproduction steps on this issue on Docker 19.03.1, and wasn't able to reproduce the problem;

```bash
mkdir repro-11394 && cd repro-11394

docker build -t symlink -<<'EOF'
FROM debian:jessie

RUN mkdir -p /tmp/test/subdir1 /tmp/test/subdir2 \
    && touch /tmp/test/subdir1/a \
    && cd /tmp/test/subdir2 && ln -s ../subdir1/a
EOF
```

```bash
docker create --name test symlink
docker cp test:/tmp/test .

tree
.
└── test
    ├── subdir1
    │   └── a
    └── subdir2
        └── a -> ../subdir1/a

3 directories, 2 files
```
