### ISSUE TITLE
Docker does not check kernel's setting concerning bridge traffic filtering

### ISSUE THREAD

**Issue by miminar** [docker/docker#11404]
Kernel has several parameters controlling filtering of bridge traffic (viz [sysctl entries](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/networking/ip-sysctl.txt?id=v3.16#n1438)):

 - `net.bridge.bridge-nf-call-arptables` - pass bridged ARP traffic to arptables' FORWARD chain.
 - `net.bridge.bridge-nf-call-ip6tables` - pass bridged IPv4 traffic to iptables' chains.
 - `net.bridge.bridge-nf-call-iptables` - pass bridged IPv6 traffic to ip6tables' chains.
 - `net.bridge.bridge-nf-filter-vlan-tagged` - pass bridged vlan-tagged ARP/IP traffic to arptables/iptables.
 - `net.bridge.bridge-nf-filter-pppoe-tagged` - pass bridged pppoe-tagged IP/IPv6 traffic to {ip,ip6}tables.

Their default value on Fedora/RHEL systems is 0 (since [bug #512206](https://bugzilla.redhat.com/show_bug.cgi?id=512206)). Therefore, by default, iptables' rules do not affect bridge's traffic. Thus docker images are allowed to communicate regardless of `--icc=false` option by default on these distributions, which is quite surprising behavior.

Docker should check these parameters and refuse to start if inter-container communication is prohibited with `--icc` option and bridge traffic is not filtered by iptables' chains. It should be mentioned in documentation as well.

I assume that checking `net.bridge.bridge-nf-call-iptables != 0 && net.bridge.bridge-nf-call-ip6tables != 0` will be enough. I'm not sure about `net.bridge.bridge-nf-call-arptables` though.

I'll post PR concerning this issue later today.

**Comment by cpuguy83** [comment]
Closing since docker/libnetwork#336 was merged to resolve this.
