### ISSUE TITLE
docker history timestamp

### ISSUE THREAD

**Issue by techniq** [docker/docker#11413]
I was looking for a way to determine how long it was taking each of my layers to create/run so I thought I could look at the time each layer was created with `docker history some_image` but the field always shows a "humanize" timestamp such as `About an hour ago`.  Since my project's `docker build .` takes about 7 1/2 minutes, all of the layers show `About an hour ago` and thus are not helpful.  It would be nice if a flag could be passed for a normal ISO8601 timestamp

**Comment by hairyhenderson** [comment]
I was thinking the same thing recently... I think I'll take a stab at a PR for this.

**Comment by nathankunicki** [comment]
+kind/enhancement +exp/beginner

**Comment by nathankunicki** [comment]
#dibs

**Comment by hairyhenderson** [comment]
@nathankunicki - not too sure what #dibs means, but I already issued a PR for this a couple days ago... #11551 :)

**Comment by nathankunicki** [comment]
Ahh I didn't notice the pull request notification, sorry about that. :) Typically when someone starts working on an issue they put #dibs, which adds the "status/claimed" label so that it doesn't show up when filtering for issues (https://docs.docker.com/project/find-an-issue/).

**Comment by hairyhenderson** [comment]
Thanks for the tip, @nathankunicki - I'm pretty new to this process :)

**Comment by techniq** [comment]
:+1:
