### ISSUE TITLE
connecting to a volume container from a container (--volumes from) over remote API

### ISSUE THREAD

**Issue by amlwwalker** [docker/docker#11415]
I want to create a volume container and --voumes-from it using the remote API.
It works fine when I do all of this from the terminal
**Create**:
Creating S_ENABLED from the command line

    docker run -v /home/vagrant/docker/examples/sites-enabled/:/etc/nginx/sites-enabled --name S_ENABLED centos:7 true

Creating S_ENABLED from API:

    curl -X POST -H "Content-Type: application/json" -d '{ "Cmd": "true", "Volumes": {"/etc/nginx/sites-enabled": {}}, "Image":"centos:7"}' http://127.0.0.1:4243/containers/create?name=S_ENABLED

as I understand it the 

    "Volumes": {"/etc/nginx/sites-enabled": {}}
is the path INSIDE the container that is going to be bound to the S_ENABLED volume container.

**Start**:

    curl -X POST -H "Content-Type: application/json" -d '{ "Binds": ["/home/vagrant/docker/examples/sites-enabled/:/etc/nginx/sites-enabled:rw"] }' http://127.0.0.1:4243/containers/[id]/start

My understanding of the above is the Binds is the from:to:rw i.e from on the host, to in the container:[read/write permissions]

**create**
Creating nginxserver from the command line:

    docker run -d -p 80:80 --volumes-from S_ENABLED --name nginxserver nginx:latest

**create** nginx container, to do a Volumes-from I do:

    curl -X POST -H "Content-Type: application/json" -d '{"Image":"nginx:latest","VolumesFrom": ["S_ENABLED"] }' http://127.0.0.1:4243/containers/create?name=nginxserver

and to **start** it I do:

    curl -X POST -H "Content-Type: application/json" -d '{"PortBindings":{ "80/tcp": [{ "HostPort": "80" }] }}' http://127.0.0.1:4243/containers/ed12e72a8c57/start

I get no errors, however when I do:

    docker exec -it nginxserver bash

and navigate to `/etc/nginx/sites-enabled` the contents of the host location directory (/home/vagrant/docker/examples/sites-enabled/) is not shown, so either I am setting up the volume container incorrectly, or I am connecting to the volume container from nginxserver incorrectly. The documentation on this feels a bit sparse, could anyone advise me where i am going wrong?

Thanks

**Comment by cpuguy83** [comment]
VolumesFrom belongs in HostConfig.

**Comment by cpuguy83** [comment]
Closing since this seems like a misconfiguration.
Please ping if the above did not resolve the issue.

Thanks!
