### ISSUE TITLE
"NetworkMode": "none" failing for some containers on Docker API version 1.16

### ISSUE THREAD

**Issue by Symmetric** [docker/docker#11425]
I'm trying to create a container with --net=none using the REST API v1.16. The [API docs](https://docs.docker.com/reference/api/docker_remote_api_v1.16/), are unclear on whether this is supported over the REST API:

> NetworkMode - Sets the networking mode for the container. Supported values are: bridge, host, and container:<name|id>

Though I figure it must be, since the Docker-Client can set NetworkMode: "none".

I'm seeing weird results when I try to set this config parameter; here's the HostConfig from `docker inspect` on a container created via the REST API with ` "HostConfig": {"NetworkMode": "none"}` :
```
    "HostConfig": {
        ...
        "NetworkMode": "",
        ...
    },
```

The container is unexpectedly created with standard docker0 bridge network connectivity. A full gist of the POST to the docker.sock socket is [here](https://gist.github.com/Symmetric/c4d99a6b17019ebce62b), and the docker inspect output is [here](https://gist.github.com/Symmetric/545e601f16ea2740f04e), note the weird NetworkMode value, but fully populated NetworkSettings.

In comparison, the HostConfig for a container created with `docker run -dt --net=none busybox sh` looks like this:

```
    "HostConfig": {
        ...
        "NetworkMode": "none",
        ...
    },
```

But I've not been able to spot any differences in the raw unix socket messages.

Full docker version info:

```
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8/1.4.1
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8/1.4.1
```

**Comment by cpuguy83** [comment]
Closing as this is a bit dated.
The CLI uses the exact same rest API.
I would probably check and make sure you have set `application/json` for your content-type.

Feel free to ping on IRC if you are still having issues.
Thanks!
