### ISSUE TITLE
docker -p option not working?

### ISSUE THREAD

**Issue by tdoan1971** [docker/docker#11421]
I built a MySQL image on top of RHEL6.5 base. I can start the container with "bin/bash" shell and start MySQL service. I can use mysql client inside the container to query, etc.

However when I try to start MySQL container in the background and expose the port so that I can connect to the container remotely, I have the issue.
Here is the command: "docker run -d -p 3306:3306 --name mysql tdoan/mysql:v1", the error stated: " ... cannot start the container "long ID" (exit status 1)"
If I start the same command with out "-p 3306:3306", it works but the "docker ps" does not have the "Port" information and I could not connect to it via a remote mysql client.

Please help!
Thanks,

**Comment by vcent** [comment]
Just run: /etc/init.d/docker restart

**Comment by thaJeztah** [comment]
Could port 3306 already be in use by either another (stopped) container or a MySQL server running on the host itself?

You should be able to check if the container starts normally and if you are able to connect to it, using

`docker run -d -p 3306 --name mysql tdoan/mysql:v1`

Docker wil then assign a random port on the host for port 3306 of the container. The random port can be found in the output of `docker ps`

**Comment by fsamin** [comment]
I got the same problem, i was unable to start a container with any port mapping. 

I fixed the problem with
`DOCKER_OPTS="--iptables=false"`

**Comment by tdoan1971** [comment]
The -p option makes docker to call iptables to setup the open port in the host. Somehow my iptables returned error that made docker subsequently not start the container.
I restarted my firewall "service iptables restart" and also the docker daemon "service docker restart", the it works.
I have not tried fsamin's suggestion but I will keep it in mind.

Thanks all,
