### ISSUE TITLE
Force Read Only

### ISSUE THREAD

**Issue by UserTaken** [docker/docker#11439]
The recent addition of being able to run containers as read only can be useful so it'd be great if there are ways enforce it to run as read only everytime without having to specify during `docker run/create` such as in a Dockerfile or when creating images manually.

**Comment by cpuguy83** [comment]
Since read-only root fs is really a runtime configuration, we cannot force all users of a particular image to be read-only.
This would be better enforced at the in an authorization layer.

Closing since I believe this is an intended design decision.
