### ISSUE TITLE
ssh to tutum/centos container immediately closed on centos 6.6

### ISSUE THREAD

**Issue by llitfkitfk** [docker/docker#11434]
Host: centos6.6
Docker version: 1.4
container: tutum/centos

![c705def7-0fdb-4329-b6d1-00a8532257f6](https://cloud.githubusercontent.com/assets/2404785/6681663/2fe46b82-cca5-11e4-96bb-3c3aa4ff0dbe.jpg)

**Comment by unclejack** [comment]
Please provide the full output of `docker info`, `docker version` and `uname -a`.

**Comment by llitfkitfk** [comment]
![147a2bd7-58d2-4bec-8a45-4374df364bac](https://cloud.githubusercontent.com/assets/2404785/6701751/f7de8bb6-cd5b-11e4-8823-c1eee91b482b.jpeg)
![f862690c-3bbe-460b-a221-05f963bf8468](https://cloud.githubusercontent.com/assets/2404785/6701753/ffc7551a-cd5b-11e4-8b06-81ee8e6f3dec.jpeg)
![screen shot 2015-03-18 at 10 40 50 am](https://cloud.githubusercontent.com/assets/2404785/6701755/040ae09c-cd5c-11e4-9ba1-41ceeb912074.png)

**Comment by visualphoenix** [comment]
@llitfkitfk is this still an issue with more recent versions of docker?

**Comment by thaJeztah** [comment]
I'm going to close this issue, because this is on an old version of docker and this might already been solved in the current release, but feel free to comment here if you think I closed this by mistake.

**Comment by visualphoenix** [comment]
Makes sense.

On Mon, Jul 13, 2015 at 5:59 PM, Sebastiaan van Stijn <
notifications@github.com> wrote:

> I'm going to close this issue, because this is on an old version of docker
> and this might already been solved in the current release, but feel free to
> comment here if you think I closed this by mistake.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/11434#issuecomment-121074529>.
>



-- 
Raymond "VisualPhoenix" Barbiero
