### ISSUE TITLE
Docker pushing FATA[3717] FATA[3791]  

### ISSUE THREAD

**Issue by bomba1990** [docker/docker#11449]
Hi, i want to submit this issue, because i have all the day try to pushing a image to a private repository and it throw error. 

There is mi error:

```

mariano@mariano-laptop:/media/mariano/B2FE2042FE1FFD6B/bright/docker$ sudo docker push bomba1990/firefly
[sudo] password for mariano: 
The push refers to a repository [bomba1990/firefly] (len: 1)
Sending image list
Pushing repository bomba1990/firefly (1 tags)
511136ea3c5a: Image already pushed, skipping 
3b363fd9d7da: Image already pushed, skipping 
607c5d1cca71: Image already pushed, skipping 
f62feddc05dc: Image already pushed, skipping 
8eaa4ff06b53: Image already pushed, skipping 
b0f0f9a62374: Image already pushed, skipping 
c4490c63e30c: Pushing [=====================>                             ] 368.3 MB/872.1 MB 1h22m14s
FATA[3717] Failed to upload layer: Put https://cdn-registry-1.docker.io/v1/images/c4490c63e30c5efda8bbde5678b9746eed3553fef15cd1b37caf05b32026f968/layer: EOF 
mariano@mariano-laptop:/media/mariano/B2FE2042FE1FFD6B/bright/docker$ sudo docker push bomba1990/firefly
[sudo] password for mariano: 
The push refers to a repository [bomba1990/firefly] (len: 1)
Sending image list
Pushing repository bomba1990/firefly (1 tags)
511136ea3c5a: Image already pushed, skipping 
3b363fd9d7da: Image already pushed, skipping 
607c5d1cca71: Image already pushed, skipping 
f62feddc05dc: Image already pushed, skipping 
8eaa4ff06b53: Image already pushed, skipping 
b0f0f9a62374: Image already pushed, skipping 
c4490c63e30c: Pushing [==================================================>] 872.1 MB/872.1 MB
FATA[3791]  
```

**Comment by phemmer** [comment]
The docker daemon logs might have some better insight into the issue. Could you provide them for the timeframe surrounding the failed push?

**Comment by bomba1990** [comment]
Excume, but where i find those logs?

**Comment by phemmer** [comment]
It depends on your OS and the package you installed (how it configured the service).

2 likely locations are: `/var/log/docker.log` or if using systemd, `journalctl -u docker.service`.

**Comment by dmp42** [comment]
Hi @bomba1990 

Can you also copy the output of `docker version` and `docker info`?

Indeed, if you uplink is extremely slow (you mentioned 4 hours to upload the layer) there might be timeouts...

Thanks.

**Comment by bomba1990** [comment]
Version:
```
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
```

info:

```
Containers: 5
Images: 91
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 101
Execution Driver: native-0.2
Kernel Version: 3.11.0-12-generic
Operating System: Ubuntu 13.10
CPUs: 4
Total Memory: 2.866 GiB
Name: mariano-laptop
ID: ZHPQ:RWQU:KGA3:TQQ6:O6BM:WY2H:LTT2:A3WH:EIHE:YL6X:XEHJ:LUDK
Username: bomba1990
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support
```

**Comment by dmp42** [comment]
@bomba1990 ok thanks.

Do you have the daemon logs? (re https://github.com/docker/docker/issues/11449#issuecomment-82990533)

**Comment by unclejack** [comment]
The environment on which this issue was encountered had at least two major issues:
1. the distribution was an unsupported Ubuntu 13.10 which is no longer being updated, not for security or for bug fixes
2. the Docker version is pretty old now.

Please upgrade the OS to something supported (such as Ubuntu 14.04), install the latest Docker release and use the latest version of the registry.

I'll close this issue now because API changes have been made to the registry. Please feel free to comment if you run into this issue with the latest releases.
