### ISSUE TITLE
API retrieve exact cli command

### ISSUE THREAD

**Issue by asbjornenge** [docker/docker#11460]
Hi guys!

I'm having an issue where I'm trying to diff running containers against my configuration. Is there a way to determine Config variables passed via CLI vs. inherited from Dockerfile ... ? My current issue is that there are some ENVs specified in a Dockerfile (over which I have no control or insight) that are not in my configuration, but still show up in the API. And there are no way to determine which ENV came from where. Or is there? :stuck_out_tongue_closed_eyes: I've been using the *inspect* api.

It would be nice if I could accurately reproduce the cli command used to spawn the container.

**Comment by duglin** [comment]
You may be able to get what you want by doing a `docker inspect` on the container to get the base image used.  That inspect should also get you the list of env vars (list 1) that docker put into the container.  From that image name if you do a `docker inspect` on it you should then able to get the list of env vars from that image (list 2).  Then, I think, the list of env vars specified on the command line should be: list1 - list 2. 

Gonna close this if that's ok.  Also, I think I might be more appropriate to use the irc channel or google forum for questions. Github issues are more for bugs, feature request, PRs, etc...

**Comment by asbjornenge** [comment]
Thanks :+1:
