### ISSUE TITLE
Calculation of cpuPercent

### ISSUE THREAD

**Issue by jzy1688** [docker/docker#11463]
cpuPercent = (cpuDelta / systemDelta) * float64(len(v.CpuStats.CpuUsage.PercpuUsage)) * 100.0

when I run docker stats in cli, the "cpu %" sometimes exceeds 100% 

So my problem is 
  -why, in the formular, it is multiplied by the number of cpus? 
  -Is the CpuUsage.TotalUsage the sum of CpuUsage.PercpuUsage for each cpu ?

**Comment by phemmer** [comment]
The CPU percentage is cumulative for all the processes/threads inside the container. If you have multiple CPUs/cores, this number can exceed 100%.

See also #10733

**Comment by jzy1688** [comment]
Sorry for bother, but my doubt is also about why it is multiplied by the number of CPUs?

**Comment by unclejack** [comment]
@jzy1688 When taking a look at top for a process, you might sometimes see a value on the CPU usage field that's higher than 100%. A value of 150% means that it's using 100% of one core and 50% of another core. A system with 4 cores will have a maximum of 400% for the CPU usage when the process is able to run on multiple cores and it's able to scale to all those cores.

**Comment by jzy1688** [comment]
@unclejack thank you for the reply. i could understand what you said.  What I doubt is that in the formula CpuDelta is calculated by the values of total cpu usage  of the container at two different time and the total cup usage seems to be the sum of the cpu usage per core. Since we already add up the usage on each core, why should we still multiply the delta by the number of cpus
