### ISSUE TITLE
-p option issues

### ISSUE THREAD

**Issue by sgillis** [docker/docker#11467]
I am seeing different behavior depending on the base image, so I am not sure if this is an issue in Docker or somewhere else.

To reproduce the issue, start with setting up a container

    $ docker run -it -p 8888:9999 debian:wheezy
    # apt-get update && apt-get install -y netcat
    # netcat -l 9999

Then on the host machine

    $ telnet localhost 8888
    Trying 127.0.0.1...
    telnet: Unable to connect to remote host: Connection refused

When I set up the container with ubuntu

    $ docker run -it -p 8888:9999 ubuntu:14.04
    # apt-get update && apt-get install -y netcat
    # netcat -l 9999

I do get a connection with telnet on the host machine

    $ telnet localhost 8888
    Trying 127.0.0.1...
    Connected to localhost. 
    Escape character is '^]'.

Why is this behaving differently?

**Comment by duglin** [comment]
I'm pretty sure this is something within the debian image/container - like a firewall.
Try running the telnet command from within each container (telnet localhost 9999). For me, the ubuntu one worked, but debian didn't.  Which would seem to indicate that its not docker issue but something within the container.

**Comment by sgillis** [comment]
You're right, running it from within the container doesn't work either. So should I create an issue [here](https://github.com/tianon/docker-brew-debian)?

**Comment by duglin** [comment]
well,I'm not familiar enough with debian:wheezy, but is it that something is wrong with the image or just need to find the right command to disable the firewall?  assuming it is a firewall issue.

**Comment by duglin** [comment]
I'm gonna close this since I don't think its a docker issue

**Comment by caussourd** [comment]
@sgillis This explains why: http://superuser.com/questions/455875/why-is-nc-l-xxxx-not-opening-a-port
