### ISSUE TITLE
A hostname problem in productive environment.

### ISSUE THREAD

**Issue by baotiao** [docker/docker#11489]
The problem is after we set up and run the container. The container my change his hostname.
How do we know this problem?
We find this problem when we using puppet to send config file, we identify each container by his hostname. But at last we send to the container  with the wrong config file. The config file is the same as the other container in this host machine. 

My docker version is 1.4.1

**Comment by cpuguy83** [comment]
You can specify a custom hostname with `docker run --hostname <name>`.
Closing since this isn't really a Docker issue.

For questions/support, please see one of the following:

1) #docker on IRC
2) docker-user mailing list
3) forums.docker.com
