### ISSUE TITLE
Docker daemon crashed on centos 6.6

### ISSUE THREAD

**Issue by yourchanges** [docker/docker#11491]
ENV:

	[root@iZ230mfzclxZ ~]# cat /etc/redhat-release 
	CentOS release 6.6 (Final)
	[root@iZ230mfzclxZ ~]# uname -an
	Linux iZ230mfzclxZ 2.6.32-504.3.3.el6.x86_64 #1 SMP Wed Dec 17 01:55:02 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
	[root@iZ230mfzclxZ ~]# docker version
	Client version: 1.4.1
	Client API version: 1.16
	Go version (client): go1.3.3
	Git commit (client): 5bc2ff8/1.4.1
	OS/Arch (client): linux/amd64
	Server version: 1.4.1
	Server API version: 1.16
	Go version (server): go1.3.3
	Git commit (server): 5bc2ff8/1.4.1

And the /var/run/docker.pid un-removed automatically.

Detail logs:

	time="2015-03-18T17:26:10+08:00" level="info" msg="-job trust_key_check(/library/registry) = OK (0)" 
	time="2015-03-18T17:39:26+08:00" level="error" msg="Error from V2 registry: ApplyLayer exit status 1 unexpected EOF" 
	Error pulling image (latest) from registry, Failed to download json: Get https://registry-1.docker.io/v1/images/76b658ecb5644a4aca23b35de695803ad2e223da087d4f8015016021bd970169/json: dial tcp: lookup registry-1.docker.io: no such host
	time="2015-03-18T17:48:44+08:00" level="info" msg="-job pull(registry, latest) = ERR (1)" 
	panic: runtime error: invalid memory address or nil pointer dereference
	[signal 0xb code=0x1 addr=0x20 pc=0x700e3c]

	goroutine 218 [running]:
	runtime.panic(0xa9fc60, 0x10e2eb3)
		/usr/lib/golang/src/pkg/runtime/panic.c:279 +0xf5
	bufio.(*Writer).flush(0xc2087e2a00, 0x0, 0x0)
		/usr/lib/golang/src/pkg/bufio/bufio.go:530 +0xdc
	bufio.(*Writer).Flush(0xc2087e2a00, 0x0, 0x0)
		/usr/lib/golang/src/pkg/bufio/bufio.go:519 +0x39
	net/http.(*response).Flush(0xc20904a140)
		/usr/lib/golang/src/pkg/net/http/server.go:1023 +0x4c
	github.com/docker/docker/utils.(*WriteFlusher).Write(0xc209338c60, 0xc208e983c0, 0xd4, 0x13b, 0xd4, 0x0, 0x0)
		/builddir/build/BUILD/docker-1.4.1/_build/src/github.com/docker/docker/utils/utils.go:265 +0x142
	github.com/docker/docker/engine.(*Output).Write(0xc208b14740, 0xc208e983c0, 0xd4, 0x13b, 0x0, 0x0, 0x0)
		/builddir/build/BUILD/docker-1.4.1/_build/src/github.com/docker/docker/engine/streams.go:90 +0x183
	github.com/docker/docker/utils.(*WriteFlusher).Write(0xc208a80e40, 0xc208e983c0, 0xd4, 0x13b, 0x0, 0x0, 0x0)
		/builddir/build/BUILD/docker-1.4.1/_build/src/github.com/docker/docker/utils/utils.go:264 +0xf4
	github.com/docker/docker/utils.(*progressReader).Read(0xc208a73700, 0xc208704000, 0x8000, 0x8000, 0x4000, 0x0, 0x0)
		/builddir/build/BUILD/docker-1.4.1/_build/src/github.com/docker/docker/utils/progressreader.go:31 +0x2a9
	io.Copy(0x7f5e8df68440, 0xc20803ab48, 0x7f5e8df7a008, 0xc208a73700, 0x1825971, 0x0, 0x0)
		/usr/lib/golang/src/pkg/io/io.go:353 +0x1f3
	github.com/docker/docker/graph.func·008(0xc208842940, 0x0, 0x0)
		/builddir/build/BUILD/docker-1.4.1/_build/src/github.com/docker/docker/graph/pull.go:550 +0x93d
	github.com/docker/docker/graph.func·009(0xc208842940)
		/builddir/build/BUILD/docker-1.4.1/_build/src/github.com/docker/docker/graph/pull.go:567 +0x2e
	created by github.com/docker/docker/graph.(*TagStore).pullV2Tag
		/builddir/build/BUILD/docker-1.4.1/_build/src/github.com/docker/docker/graph/pull.go:568 +0x16ce

	goroutine 16 [chan receive, 50 minutes]:
	github.com/docker/docker/api/server.ServeApi(0xc20804cd80, 0x7f5e8df687b0)
		/builddir/build/BUILD/docker-1.4.1/_build/src/github.com/docker/docker/api/server/server.go:1573 +0x473
	github.com/docker/docker/engine.(*Job).Run(0xc20804cd80, 0x0, 0x0)
		/builddir/build/BUILD/docker-1.4.1/_build/src/github.com/docker/docker/engine/job.go:83 +0x837
	main.mainDaemon()
		/builddir/build/BUILD/docker-1.4.1/docker/daemon.go:91 +0x568
	main.main()
		/builddir/build/BUILD/docker-1.4.1/docker/docker.go:71 +0x3ff

**Comment by cpuguy83** [comment]
Seems like this was fixed by #10244, and is probably a dup of #10228 (which is a panic on push).

cc @stevvooe to confirm

**Comment by stevvooe** [comment]
@cpuguy83 Confirmed.

**Comment by cpuguy83** [comment]
Ok, closing this then.
