### ISSUE TITLE
I can’t login docker hub by command

### ISSUE THREAD

**Issue by shiratsu** [docker/docker#11490]
Hi,there.
I am starting to use docker.
So,i am proceeding to learn docker with following docker document.
http://docs.docker.com/userguide/dockerhub/

Then,i tryed to login docker hub by command.
I already create docker hub account.But I can't login docker hub by command.
If i try to login by command,this error produce.

```
% docker login
Username: xxxx
Password:
Email: xxxxxxx@yahoo.co.jp
FATA[0033] Error response from daemon: Server Error: Post https://index.docker.io/v1/users/: dial tcp: lookup index.docker.io on 203.141.128.33:53: read udp 203.141.128.33:53: i/o timeout
```
i seem i could not access.
How do i do?

**Comment by cpuguy83** [comment]
This looks like your system is no able to reach dockerhub.

**Comment by shiratsu** [comment]
Was it my network problem?
But i can connect internet.

And I am setting at .zshrc.
```
export DOCKER_TLS_VERIFY=1
export DOCKER_HOST=tcp://192.168.59.103:2376
export DOCKER_CERT_PATH=/Users/shiratsu/.boot2docker/certs/boot2docker-vm
```

What should i investigate this problem anything else?

**Comment by dmp42** [comment]
You have a DNS resolution issue.
Your DNS server is timeouting (203.141.128.33:53).

Boot2docker is notoriously inefficient at detecting network configuration changes.

Quick fix: restart boot2docker.

**Comment by shiratsu** [comment]
Thank you!
I resolved after restarting docker.

**Comment by sendalot** [comment]
I have two environments for docker.
1st one is at home where there's no proxy and things work fine.
2nd one is at work where I'm behind a proxy.
"docker login" works at home but not at work.

I get the following error. What can I do to get around?

[root@puppetmaster ~]# docker login
Username: slt
Password: 
Email: snd@gmail.com
FATA[0006] Error response from daemon: Server Error: Post https://index.docker.io/v1/users/: dial tcp 162.242.195.84:443: no route to host 
[root@puppetmaster ~]# service docker status
docker (pid  2421) is running.


Thanks.

**Comment by ebuildy** [comment]
Still having this issue in despite of multiple restarts ;-(

It's weird because I can ping index.docker.io fine, is ````docker login```` doing something special?

![Docker login tentative]
(https://secure.beemapp.me/view/e360eae6-193d-410f-94b0-16963a6222bd)

**Comment by dmp42** [comment]
@ebuildy I assume you are using boot2docker.

Have you restarted virtualbox?

**Comment by ebuildy** [comment]
Yes boot2docker (from Kimatic), and yes, restarted multiple time.

Why I can ping it but get a lookup error?

**Comment by dmp42** [comment]
@ebuildy can you `cat /etc/hosts`?

**Comment by erwindev** [comment]
Powering off boot2docker VM in VirtualBox and restarting boot2docker fix this issue for me.

**Comment by orangeudav** [comment]
can anybody show config.json example after success ended of docker login ?

**Comment by sheldonrampton** [comment]
I experienced an issue where after an unsuccessful attempt to login, I kept getting an "Error response from daemon...i/o timeout" error message similar to the one described here. The unsuccessful attempt to login occurred because my password contained an ampersand character which was evidently misinterpreted as a control character by the Linux command line. I therefore changed my password to something without an asterisk and atttempted to log in again, but I kept getting the error message described above. I was able to clear the error and log in by resetting boot2docker VM in VirtualBox and then relaunching Docker Quickstart Terminal.

**Comment by andy0983011** [comment]
In the Ubuntu/Linux Mint ,you may try this command "sudo docker.io login" to login docker.

**Comment by ihr** [comment]
On MacOS X the problem was fixed after  **docker-machine restart default**

**Comment by walterpinson** [comment]
The issue was resolved for me on Mac OSX after issuing `docker-machine restart default`, as well.

**Comment by albertlockett** [comment]
On Mac OSX I had to ssh into the boot2docker vm and add the hostname of the registry to the host file

`docker-machine ssh`

`sudo vi /etc/hosts`

After adding entry to the host file need to restart the docker daemon in the VM

`/etc/init.d/docker restart`

That resolved it for me

**Comment by hemanth7787** [comment]
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

**Comment by chrsalx** [comment]
**docker-machine restart default** worked for me on windows 10 as well.

**Comment by unitof** [comment]
In my case, embarrassingly, I just had to stop using my email address as my `Username`, even though `docker login` kept prompting me with my email address as the default username.

I think maybe the tray app allowed me to log in with email, but `docker login` only accepts usernames?
