### ISSUE TITLE
Containers sometimes displayed as running when they're not

### ISSUE THREAD

**Issue by ncdc** [docker/docker#11499]
Due to a race condition in `master` (the details of which @LK4D4 can fill in), I am frequently seeing containers listed in `docker ps` that are not actually running because they have terminated. Attempts to stop/kill/rm these containers fail with an error like this:

    Cannot stop container 1f6e29da01c6: active container for 1f6e29da01c6fd7900c1056c905f58c3cb1209f96d0427e220b5a0f155814bc2 does not exist

**Comment by LK4D4** [comment]
It is fixed in my branch https://github.com/LK4D4/docker/tree/replace_execdriver but it still lacks lxc support.

**Comment by estesp** [comment]
Does #11507 fix this? Seems like it should

**Comment by jfrazelle** [comment]
@ncdc can you try with master since that was merged, you can download at master.dockerproject.com

**Comment by ncdc** [comment]
Yes, although I don't have a reliable reproducer. It's more that if I have
the daemon up for a while and I'm creating a bunch of containers as part of
my normal workflow, eventually I run into this.

**Comment by jfrazelle** [comment]
ah I see

**Comment by ncdc** [comment]
Ok, I'm still seeing this with commit ded0ada, which I believe is newer than the fix in #11507 (commit 5a239c0 I think).

**Comment by LK4D4** [comment]
@ncdc Can you try master pls? Yesterday was merged fix for execdriver(actually execdriver did all wrong all that time :()

**Comment by ncdc** [comment]
@LK4D4 I just updated to the latest master and am testing now. It'll probably be a few hours before I can report anything.

**Comment by thaJeztah** [comment]
@ncdc have you been able to test this yet? Thanks in advance!

**Comment by ncdc** [comment]
I haven't seen the issue since I upgraded to master on 3/31.

**Comment by thaJeztah** [comment]
@ncdc do you think it's safe to close this issue, or would you prefer to have some more time testing? (We can always re-open)

**Comment by ncdc** [comment]
I'm fine closing it for now

**Comment by thaJeztah** [comment]
Great, thanks for testing this! If you encounter this again, feel free to ping me, and I'll re-open.
