### ISSUE TITLE
Add tip about filter proxy to Docker installation Guides

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#11500]
Add information for getting around key errors when installing Docker on Ubuntu and Debian 
-->
If your company is behind a filtering proxy, you may find the `apt-key` command fails for the Docker repo during installation. To work around this, add the key directly using the following:
 
`wget -qO- https://get.docker.com/gpg  | sudo apt-key add -`

**Comment by pmepablo** [comment]
Thanks very much!

**Comment by xiaods** [comment]
#dibs
