### ISSUE TITLE
"Weird" docker exec behavior when sending Interrupt to interactive CLI apps

### ISSUE THREAD

**Issue by fgrehm** [docker/docker#11503]
_Dunno if this is related to other `docker exec` + tty issues around, feel free to close it if it is!_

I use docker for developing Ruby on Rails apps and ever since I remember leveraging `docker exec` to spawn new `rails console` / `irb` / `guard` exec instances based on a running rails app container I noticed that when I `Ctrl+C` it ends up just killing the exec instance right away, but if I `docker exec bash` and run an `irb` session from there it works as expected (as in the process is not killed).

Asciicast that reproduce things in an easier way: https://asciinema.org/a/17848

If you need any additional information just LMK!

Environment info:

```
$ docker info
Containers: 5
Images: 238
Storage Driver: aufs
 Root Dir: /home/fabio/docker/aufs
 Backing Filesystem: extfs
 Dirs: 250
Execution Driver: native-0.2
Kernel Version: 3.16.0-25-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 4
Total Memory: 7.333 GiB
Name: babylon

$ docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

**Comment by cpuguy83** [comment]
I cannot repro this on Docker 1.8.
Please let me know if this is still a problem.
Closing.

**Comment by fgrehm** [comment]
Sorry for the HUGE delay but yeah, I just tried it again on 1.10.1 and it worked fine :beers:
