### ISSUE TITLE
Missing code example in docker rm reference guide

### ISSUE THREAD

**Issue by johnny-tu** [docker/docker#11527]
On the page https://docs.docker.com/reference/commandline/cli/#rm, in the RM command reference the following paragraph seems to be missing the command example

"This command will delete all stopped containers. The command docker ps -a -q will return all existing container IDs and pass them to the rm command which will delete them. Any running containers will not be deleted."

@moxiegirl

**Comment by moxiegirl** [comment]
+exp/beginner +kind/writing

**Comment by jfrazelle** [comment]
sorry i havent updated it yet

**Comment by nparker94** [comment]
#dibs
