### ISSUE TITLE
SSL expired https://get.docker.io/

### ISSUE THREAD

**Issue by sgarbesi** [docker/docker#11536]
Effectively breaking the vagrant docker provisioner amongst other things.

Looking to get this file securely in particular:
[https://get.docker.io/gpg]()

**Comment by cpuguy83** [comment]
Known issue and it's being worked on.
Please in the future send this info to support@docker.com

status.docker.com should be updated soon.

**Comment by sgarbesi** [comment]
@cpuguy83 Thanks for the update, and I will in the future.

**Comment by cpuguy83** [comment]
Thanks for the report!
