### ISSUE TITLE
Question: are volumes passed through command line argument mounted when entrypoint is executed?

### ISSUE THREAD

**Issue by olalonde** [docker/docker#11539]
I was wondering if my ENTRYPOINT command had access to volumes mountes with the `-v` flag when it is executed. I would like my entrypoint script to have different behaviour depending on if a file is present or not.

**Comment by duglin** [comment]
Yes the volume should be available to all processes within the container.

BTW, see https://docs.docker.com/faq/#where-can-i-find-more-answers   the mailing lists, or irc are usually a better place to ask questions. Github issues are usually for calling out problems not for asking questions.
