### ISSUE TITLE
x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by cinterloper** [docker/docker#11534]
https://index.docker.io/ has an expired SSL cert

**Comment by cinterloper** [comment]
# docker pull registry
Pulling repository registry
FATA[0000] Get https://index.docker.io/v1/repositories/library/registry/images: x509: certificate has expired or is not yet valid

**Comment by intlabs** [comment]
Can confirm :(

**Comment by chriskinsman** [comment]
Arggh.  Blocking

**Comment by st3wart** [comment]
Problem.

**Comment by tiborvass** [comment]
We are aware of the situation and are working on it as fast as we can. FYI for next time please send an email to support@docker.com, this github is about the open source project, not the Hub :) Thanks!

We'll be updating https://status.docker.com/ (as of now it still says all systems operational, but will get someone to update it very soon).

**Comment by bobbytables** [comment]
For anyone else that runs into this and stumbles across this page, this fixes it for me:

```sh
boot2docker ssh
sudo ntpclient -s -h pool.ntp.org
```

Hope this helps.

**Comment by endeepak** [comment]
+1 for @bobbytables solution. It worked for me on mac.

**Comment by lukabirsa** [comment]
+1 for @bobbytables solution. Worked for me.

**Comment by DyegoCosta** [comment]
+1 for @bobbytables solution :)))

**Comment by babybeasimple** [comment]
+1 for @bobbytables solution :)))

**Comment by roylanceMichael** [comment]
+1 for @bobbytables solution as well (btw, love the xkcd reference). This worked on Windows like a charm (which makes sense, as the VM for mac and windows is similar I believe)

**Comment by dzotokan** [comment]
Thanks, @bobbytables. Worked for me as well.

**Comment by resoliwan** [comment]
+1 for @bobbytables solution :)))

**Comment by sabya08** [comment]
+1 for @bobbytables  solution

**Comment by ruairiquinn** [comment]
Another +1 for @bobbytables solution

**Comment by pditommaso** [comment]
+1 for @bobbytables solution :clap:

**Comment by asampat3090** [comment]
:+1: for @bobbytables solution

**Comment by centerorbit** [comment]
I had a similar issue using the native Docker for Mac. It was giving me the same error.

@bobbytables solution implied that the clock drifted, and so the SSL connection could not be properly established. I've seen this before with VMs when the host computer is put to sleep, the VM time can drift from realtime.

Native Docker for Mac still has a VM, it's just a very thin Linux Hypervisor, yet still susceptible to clock drift. Simply restarting docker on the host machine fixed the problem.

**Comment by itsNikolay** [comment]
- MacOS users that still getting the issue, try to restart Docker:

<img width="192" alt="screenshot at nov 20 03-47-34" src="https://cloud.githubusercontent.com/assets/786577/20459491/229acb98-aed4-11e6-83a6-33654332de6f.png">

- For self signed certificates: 

Append `domain.crt` to `/etc/ssl/certs/ca-certificates.crt`
with `$ cat /certs/domain.crt > /etc/ssl/certs/ca-certificates.crt`
More information here: https://forums.docker.com/t/adding-self-signed-certificates/9761/18

**Comment by kvaps** [comment]
Hi, I got same error. But I found out where is problem.

If your system time is fine, try to flush your dns-server cache first.
If it have big (>512 bytes) cached answer, it can be problem for iterpret by go dns library.
See: https://github.com/golang/go/issues/21160
And if it can't get answer at first time, it will ask your search domain next time.

PS: I had same problem when I run `kubeadm init`:
```
unable to get URL "https://storage.googleapis.com/kubernetes-release/release/stable-1.7.txt": Get https://storage.googleapis.com/kubernetes-release/release/stable-1.7.txt: x509: certificate has expired or is not yet valid
```

**Comment by mostafaelsayyad** [comment]
if u r using centos then check machine date time, adjust it to the current time. 
this worked for me.

**Comment by viay** [comment]
@itsNikolay  Thanks. It worked for me

**Comment by dsw0214** [comment]
@mostafaelsayyad  Thanks. It worked for me

**Comment by jaakkouu** [comment]
> if u r using centos then check machine date time, adjust it to the current time.
> this worked for me.

This fixed my problem on CentOS 6
