### ISSUE TITLE
Docker keeps corrupting VirtualBox VM

### ISSUE THREAD

**Issue by Chocoloper** [docker/docker#11547]
I'm using docker inside a VirtualBox VM with Xubuntu 14.04.02 64bit, 4 cores, 4 GB ram and the newest version of docker installed by the docker.io script. My host system is Win7 64bit, 16 GB RAM, i7 3770 with right timings and no overclocking.

When I'm building many different Images my VM keeps crashing which causes data loss. Also I made an docker image which should run an all-in-one installation of openstack swift. After a few minutes the VM becomes unresponsive and needs to be closed which also caused data loss.

I made a github repository with a script which is logging my memory usage while building the docker image several times until it crashes after the 42th run. 

You can find the repository under https://github.com/Chocoloper/docker-crash. In the logs directory there are infos about the vm (info.log and VBox.log) and two logs of my last run of my script. There is the script.sh and my Dockerfile for swift to test the building process. And you can also just run the builded swift image.

On the whole I crashed my vm three times since i'm using docker, with two times complete loss of all the data inside my vm. I could reproduce those crashes like I described previously everytime I tested it!

**Comment by skarekrow** [comment]
I'm seeing a weird issue with your script on my VM as well. I'm running Arch Linux which is currently on kernel 3.19.2-1-ARCH. The VM has 2GB of RAM and a small 256M swap partition. I'm running this on a Windows 8.1 Host with 8GB of RAM and on a i7 2500k. Virtualbox is at version 4.3.26. Docker is using the overlay backend. 

After run 12 it starts saying ```INFO[0086] ApplyLayer exit status 1 stdout:  stderr: open /usr/share/doc/python-paste/docs/_sources/modules/debug.profile.txt: no space left on device``` and then ```INFO[0001] symlink ping.8.gz /var/lib/docker/overlay/54d143a0f873d757e0352c5b37d1b69a3e7a17ded29220958e2653ab185d2627/tmproot783659213/usr/share/man/man8/ping6.8.gz: no space left on device``` 
The disk still has 10GB+ of free space left. The host has over a TB of free space. At this point it started flying through the builds and failing eventually ending at 250 like the script says. I'm also seeing a ```overlayfs: failed to create directory /var/lib/docker/overlay/DIFFERENTUUIDS/work/work```

Hopefully this is helpful to you guys at all. My VM never fell though. Only used about 5MB of swap and the system had plenty of memory free during this.

**Comment by Chocoloper** [comment]
Hi Skarekrow! Thanks for testing it that fast and reproducing the same/a similiar problem. Could you please also run the container one time as it also crashed my vm after a few minutes of running. (The vm became unresponsive).

**Comment by cpuguy83** [comment]
Also what would be very helpful is the output of `docker info` and `docker version`

*note that `docker version` is different than `docker -v`

Thanks!

**Comment by Chocoloper** [comment]
This was the last one which had still a useable disc after failing (but with a loss of many files). All other vms root partitions were corrupted completely afterwards. 
<code>$ docker version </code>
<code>Client version: 1.5.0</code>
<code>Client API version: 1.17</code>
<code>Go version (client): go1.4.1</code>
<code>Git commit (client): a8a31ef</code>
<code>OS/Arch (client): linux/amd64</code>
<code>Server version: 1.5.0</code>
<code>Server API version: 1.17</code>
<code>Go version (server): go1.4.1</code>
<code>Git commit (server): a8a31ef</code>

<code>$ docker info</code>
<code>Containers: 412</code>
<code>Images: 624</code>
<code>Storage Driver: aufs</code>
<code> Root Dir: /var/lib/docker/aufs</code>
<code> Backing Filesystem: extfs</code>
<code> Dirs: 1462</code>
<code>Execution Driver: native-0.2</code>
<code>Kernel Version: 3.16.0-31-generic</code>
<code>Operating System: Ubuntu 14.04.2 LTS</code>
<code>CPUs: 4</code>
<code>Total Memory: 3.86 GiB</code>
<code>Name: TEST-VirtualBox</code>
<code>ID: IKOF:MAFW:YETE:7RCA:TYVU:2VKL:HOHW:SG3F:VUDV:PZO6:M4GC:55BZ</code>
<code>WARNING: No swap limit support</code>

**Comment by erikh** [comment]
Saw this last week on 1.4 and btrfs too, not sure if related or not.

-Erik

**Comment by skarekrow** [comment]
@cpuguy83  Sure, here's my info:
```$ docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

```$ docker info
Containers: 0
Images: 19
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 3.19.2-1-ARCH
Operating System: Arch Linux
CPUs: 1
Total Memory: 1.959 GiB
Name: arch_test
ID: SZDT:MB5Q:ISJS:K4N4:IXL2:5O23:O5XP:NGGJ:3OYA:L2AJ:PGK5:HCL6
```

@Chocoloper Did you run the image with ```-d```? I ran it with ```-d``` and no other argument. After about 8 minutes it completely used all the memory up. Lots of python instances from swift-object-auditor. My system did not crash but I killed it when it got to a load of 401.67 ;) I'm not experienced with swift so I cannot help identify what is going wrong with this image. But I don't suspect it is Docker's fault. I could be wrong though.

**Comment by Chocoloper** [comment]
@cpuguy83 I tried <code>-d</code> once but used <code>-it</code> the other times to read the log.
Using up all the ram seems possible but still it makes my whole vm unresponsive. I can't access the gui or any tty. Closing the vm will possibly harm (and has harmed) my root partition as it couldn't be unmounted.
We used swift (with another config) and other openstack services inside a vm on a xen server with 4gb ram and hadn't problems so far.
But really it seems to be much more stabile for you! I wouldn't mind any errors with docker when I wouldn't corrupt my whole harddisk! Maybe it's a problem with virtuallbox too? I just can guess atm.

**Comment by skarekrow** [comment]
@Chocoloper It does seem to be more stable for myself. I am using VirtualBox as well. What do you mean that closing the VM has harmed your root partition? Are you using raw disks with VirtualBox? Can you elaborate on the corruption of the harddisk. Are you saying that ext4 isn't recovering gracefully or something else?

**Comment by Chocoloper** [comment]
Everytime my vm is crashing through building many images/containers the root partition isn't unmounted. When the vm becomes unresponsive through running this swift container and I close the vm the root partition can't be unmounted too. I'm using ext4 with vhd-files. I already tried to use live versions with tools like fsck to repair it but I just ended up in initramfs.

**Comment by skarekrow** [comment]
Interesting. Hopefully someone figures out this issue!

**Comment by tj** [comment]
I'm getting out of space as well (only been using docker for a day).

I see https://docs.docker.com/articles/b2d_volume_resize but that's a pretty poor dev experience, no way we could get the entire team doing stuff like that without fumbling, but then that partially defeats the purpose of using it. Any nicer alternatives?

Info:

```
Containers: 140
Images: 326
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 620
Execution Driver: native-0.2
Kernel Version: 3.18.5-tinycore64
Operating System: Boot2Docker 1.5.0 (TCL 5.4); master : a66bce5 - Tue Feb 10 23:31:27 UTC 2015
CPUs: 8
Total Memory: 1.961 GiB
Name: boot2docker
ID: ETKY:QHEW:QR6D:HK7W:U5EP:SBGK:PDIU:22JP:LWDP:QL63:VNHE:ZCCE
Debug mode (server): true
Debug mode (client): false
Fds: 12
Goroutines: 15
EventsListeners: 0
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: tjholowaychuk
Registry: [https://index.docker.io/v1/]
```

**Comment by cpuguy83** [comment]
I'm going to close this as it looks like you are just consuming all the disk through successive runs of `docker build --no-cache`.
Certainly can expect some issues on the VM if there is no more space.

**Comment by Chocoloper** [comment]
Yeah you are maybe right. At the moment I delete all docker images/containers after like 20 builds and didn't had any more problems so far. But I also think that if Docker hasn't any space left it should stop and give me some errors like in the first post of skarekrow to prevent such failure.
Nevertheless thanks for your time investment.
