### ISSUE TITLE
Ctrl-C not working

### ISSUE THREAD

**Issue by olalonde** [docker/docker#11540]
I'm running docker with boot2docker on OS X and it seems I can't exit docker processes by typing `ctrl-c`.  Is that normal behaviour and if so, is there any way to kill the docker process without having to close my terminal?

**Comment by thaJeztah** [comment]
@olalonde that will really depend on the processes you're starting. However, this looks more like a support question; the GitHub issue tracker is not a support forum and meant for reporting bugs and feature requests.

Would you mind asking your question on the #docker IRC channel, https://forums.docker.com or https://groups.google.com/forum/#!forum/docker-user?
Thanks!

**Comment by olalonde** [comment]
Ok thanks.

**Comment by thaJeztah** [comment]
Thanks! If it still turns out to be a bug, feel free to open a new issue!
