### ISSUE TITLE
dockercfg login confusion with docker pull

### ISSUE THREAD

**Issue by ghost** [docker/docker#11549]
Description of problem:

If you log into a private docker registry and do a docker pull it fails in one case

docker login private-docker-registry.io:443 <- WORKS with docker pull
docker login https://private-docker-registry.io <- does NOT work with docker pull even though its in the dockercfg and really the samething.

`docker version`:
Docker version 1.5.0, build a8a31ef
Docker version 1.0.1, build 990021a

`docker info`:

`uname -a`:
Linux development-5096-8b1 3.16-0.bpo.2-amd64 #1 SMP Debian 3.16.3-2~bpo70+1 (2014-09-21) x86_64 GNU/Linux

Linux ip-172-31-37-255 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):

GCE
AWS

How reproducible:
Everytime

Steps to Reproduce:
1. docker login https://private-docker-registry.io
2. docker pull https://private-docker-registry.io/repo-name
3. fails

Actual Results:

docker login private-docker-registry.io:443 WORK
docker login https://private-docker-registry.io DOES NOT work

Expected Results:

update docker pull to work with https://

Additional info:

**Comment by softwaremisconduct** [comment]
Update to issue standard

**Comment by dmp42** [comment]
cc @stevvooe FYI

**Comment by dmcgowan** [comment]
> 2. docker pull https://private-docker-registry.io/repo-name

This is not a valid image name.  Pull is expecting an image name with the first element as the server name in the case of private registries.  The image name is a fully qualified name in this case, but not a URL. The distribution is clarifying this relationship to properly separate the transport from the fully qualified name. See https://github.com/docker/distribution/pull/179

These are the cases I would expect to work, can you try them out.  If they do not work please output your daemon debug logs (by running as `docker -d -D`) as well as client logs.
~~~
docker login private-docker-registry.io:443
docker pull private-docker-registry.io:443/repo-name
# AND
docker login https://private-docker-registry.io
docker pull private-docker-registry.io/repo-name
~~~

**Comment by LK4D4** [comment]
Going to close this because of inactivity. Feel free to open new issue.
