### ISSUE TITLE
docker pull shall show the size of dependent repositories

### ISSUE THREAD

**Issue by ScreamingDev** [docker/docker#11542]
Running `docker pull --some-option dockerfile/ubuntu-desktop` shall end up in a list of all repositories and their sizes.
The pull of this has to be confirmed.

Some pulls lead to not intended big downloads.

**Comment by denibertovic** [comment]
The main issue with this is that a pull would be be interactive then..which would potentially break a lot of automation scripts.

However, adding info about image size to the Hub web interface would be very helpful, for starters.

**Comment by thaJeztah** [comment]
> However, adding info about image size to the Hub web interface would be very helpful, for starters.

@denibertovic I agree, however, issues/feature requests for Docker Hub are not handled in this repository. Perhaps you can start a discussion on https://forums.docker.com/c/all-things-docker-hub or create a feature request through https://support.docker.com

**Comment by LK4D4** [comment]
@thaJeztah could you pls somehow create task for docker hub? I'm going to close this here.

**Comment by thaJeztah** [comment]
The Web interface now shows all sizes, so I don't think we need to open an issue there: https://hub.docker.com/r/library/ubuntu/tags/

<img width="1031" alt="screen shot 2016-09-15 at 00 39 18" src="https://cloud.githubusercontent.com/assets/1804568/18532532/ec2764de-7adc-11e6-8a6b-44e99fb4a12d.png">
