### ISSUE TITLE
Test the apt-cache-ng example

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#11556]
Test this example and ensure sit is still viable. File any issues you find as `writing` issues.

http://docs.docker.com/examples/apt-cacher-ng/

**Comment by rot26** [comment]
#dibs

**Comment by vdemeester** [comment]
@moxiegirl tried it out today. The example is still working and I think is viable. 

Few notes :
- Maybe we should add a tiny sentence on what is ``dockerhost`` (the ip or available hostname where the container is running).
- Maybe add a link to [tianon/apt-cacher-ng](https://registry.hub.docker.com/u/tianon/apt-cacher-ng/) for a more *robust* image.

@moxiegirl @thaJeztah what do you think ? :blush:

**Comment by moxiegirl** [comment]
@vdemeester That sounds like a good idea to me.  Feel free to take this on...I've removed the old claim.

**Comment by thaJeztah** [comment]
sgtm!

**Comment by vdemeester** [comment]
@moxiegirl ok I'll take this on real soon :smile_cat:

**Comment by moxiegirl** [comment]
@vdemeester no worries...your commentary will help anyone, including me, if they take this on. :-D

**Comment by pwaller** [comment]
I can't tell from looking at http://docs.docker.com/examples/apt-cacher-ng/ what `dockerhost` is. I'm even a docker developer but somehow missed this. There is this [huge thread](https://github.com/docker/docker/issues/1143) where a bajillion people all `:+1: dockerhost` but it was closed early on and there are still people asking for it. That was all I could quickly find.

**Comment by curtiszimmerman** [comment]
The `+1 dockerhost` in that thread are votes to have docker put an entry in container hosts file where `dockerhost` is set to the host's IP.

**Comment by pwaller** [comment]
Is that not the same thing as is being suggested in the apt-cacher-ng documentation? I thought it was, but I can't tell now.

**Comment by vdemeester** [comment]
@pwaller It is *kinda* the same thing on the apt-cacher-ng documentation ; but it's not described at all and the idea is not to setup anything to make *dockerhost* work magically. If anything, I would replace `dockerhost` with the ip to make sure it's not misunderstood (with an explanation on how to get the ip).

This is also why I added "add another example with add-host and/or links […]." suggestion :wink:.
