### ISSUE TITLE
Ensure graphics around docker and daemon have same basic look n feel

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#11552]
See images on these pages and make them all similar

* http://goo.gl/PkzAfP
  * http://docs.docker.com/installation/images/linux_docker_host.png
  * http://docs.docker.com/installation/images/mac_docker_host.png

* http://goo.gl/wxR2UL
  * http://docs.docker.com/article-img/architecture.svg

**Comment by nfirvine** [comment]
#dibs

**Comment by nfirvine** [comment]
Pull request above fixes the first part. :)

**Comment by nfirvine** [comment]
Fixed the second part in commit 57dd5a0152925ba5cd12dc82142d51471dd654dc
