### ISSUE TITLE
Test the Link via an Ambassador Container article

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#11559]
Test the article and ensure the process works as documented. File any issues a `writing` issues.

http://docs.docker.com/articles/ambassador_pattern_linking/

**Comment by cellpjs** [comment]
#dibs

**Comment by cellpjs** [comment]
Main example works as described. In "how it works", found some issues with mkimage-unittest.sh and created a pull request https://github.com/docker/docker/pull/11831
