### ISSUE TITLE
Test the Dockerizing a Riak Service example

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#11558]
Test the example and ensure it works as documented. File any issues a `writing` issues.

http://docs.docker.com/examples/running_riak_service/

**Comment by dekobon** [comment]
#dibs

**Comment by dekobon** [comment]
Riak repositories as listed in the Dockerfile are outdated. I'm putting together a working example of a Dockerfile for Riak. Stay tuned for a pull request.

**Comment by moxiegirl** [comment]
@dekobon wow, thank you! Looking forward to receiving it.
