### ISSUE TITLE
Test the "Process Management with CFEngine" article

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#11560]
Test the article and ensure the process works as documented. File any issues a `writing` issues.

https://docs.docker.com/engine/articles/cfengine_process_management/

**Comment by twitteried** [comment]
#dibs

**Comment by twitteried** [comment]
Documentation seems outdated. Issue opened here:

https://github.com/docker/docker/issues/11703

**Comment by fgimenez** [comment]
Can this be written as an e2e or integration test? Haven't seen any of those in the codebase, probably this is meant to be manual, right?

Thx,

**Comment by moxiegirl** [comment]
@fgimenez Eventually, we'd like any sample code in the documentation to be tested in an automated fashion.  That is a couple years out at the moment. In the mean time, we have to rely on manual testing.  

In any case, this issue is about testing the procedure as written which includes more than the actual code.

**Comment by zelahi** [comment]
I can further test this issue and would anyone like me to submit any automated test scripts that I would write for this?

**Comment by thaJeztah** [comment]
@zelahi also look at https://github.com/docker/docker/issues/11703, which is probably related.

Having scripts to automatically test the example would be cool, but not required to solve this issue (I think @SvenDowideit is also thinking about automating those).

So, just testing the examples, and (if needed) update the documentation is good enough, but if you have suggestions to automatically test the examples, that's always welcome :smile:

**Comment by zelahi** [comment]
sure, It might be better to have the tests as a separate project from the original docker project.   There could be an automated docker testing project, which automates the examples in the docs, then we can have those tests hook up to Jenkins and automate running those tests.  What do you guys think?

**Comment by moxiegirl** [comment]
@zelahi That pretty much describes the long term project we have.  If you want to contribute such a setup...that would be a nice contribution indeed.

**Comment by zelahi** [comment]
Sure, I don't have a Jenkins server I can contribute but I can figure out some more details and open up and issue with details of this project

**Comment by fgimenez** [comment]
> Sure, I don't have a Jenkins server I can contribute

@zelahi let me know if you need help with this, I have some spare infra and experience with Github pull request builder plugin

Cheers,

**Comment by SvenDowideit** [comment]
noice :)
