### ISSUE TITLE
Port mapping at runtime

### ISSUE THREAD

**Issue by elgs** [docker/docker#11561]
It seems it is only possible to do port mapping the first time a container is instantiated from an image with the command `docker run -it -p h_port0:c_port0 -p h_port1:c_port1 ubuntu bash`. Once the container is instantiated, it is no longer possible to update the port mapping. To be more flexible, is it possible to add the same `-p` option to the `docker start` command?

**Comment by vivekchopra** [comment]
+kind/enhancement

**Comment by brahmaroutu** [comment]
#dibs

**Comment by jiangjizhong** [comment]
That is what I just need.

**Comment by cpuguy83** [comment]
But if you are starting the container again... is it not completely trivial to create a new container with the correct configuration instead?

**Comment by elgs** [comment]
@cpuguy83 no, the way I used docker is more like the way I use a virtual machine. Most of my containers are stateful. Some of them even run mysql and its data files inside. I know I might be blamed this is not recommended one container one process way of using docker. But I also don't see a reason not use it like this. So depending on the way I use docker, specifying port mapping upon starting a container is useful to me.

**Comment by cpuguy83** [comment]
@elgs Really has nothing to do with one process per container.
The real issue is that you are saving state inside the container, which makes it impossible to replace the container... not to mention carries significant overhead due to the filesystem layering.

**Comment by elgs** [comment]
@cpuguy83, I don't think restarting a container will create new any new layers, would you correct me if I'm wrong. right, I knew a workaround after I configured my container, and when I feel comfortable with it, I commit it and reload it with port mapping in the Dockfile. But I think this is very rigid, and in case I made further changes to the container. I probably have to commit and reload it again, causing additional fs layers. So if I could do port mapping upon (re)starting a container, that would be very helpful and flexible.I understand all what I wish is based on the way I use docker as a virtual machine.

**Comment by cpuguy83** [comment]
@elgs So you are doing `docker commit` to commit your container state?

Please realize that there are a max number layers that are allowed, and that each layer provides additional overhead.
Instead you can store your container state in volumes, which run directly on the host FS (no extra overhead), and you can restore this state to a _new_ container rather than having to commit that data.

**Comment by elgs** [comment]
No, I haven't done that, yet, but I see it as a last resort, though I think it's ugly to do so. I understand I should put the data in the volumes, which is a clean way. But it's still very difficult to me to accept a stateless container concept, yet. Maybe my brain is deeply washed by the virtual machines.  @cpuguy83, I was wondering, do you think a container should really be stateless? And `docker start` should be really avoided? If this is the case, why?

**Comment by cpuguy83** [comment]
@elgs Because it allows you to swap out the container as needed, it allows you to put your data in the best location possible instead of storing it in the container FS (which is probably the least best place one could put it), and not have to give special privileges to the container to allow things like mount.

**Comment by elgs** [comment]
@cpuguy83 it `allows`, does not mean it 'enforces`, is it right? I understand volumes are great locations for putting data, but I don't think container is the worst (or least best) place to put data. It really depend on how one uses the containers. For people having a lot of machines to deploy, they probably wish to pack everything inside one box, instead of bothering to tune the application and data boxes separately. If avoiding the `-p` parameter on `docker start` is not too difficult technically, it actually is not a matter of `allows`, instead, it's a matter of `enforces`.

**Comment by elgs** [comment]
I'm very afraid docker is going to be gradually fading out. Yes, docker is great, but it just doesn't work the way users expected. Look at OpenVZ, it might not be great in how it is written, but it just does the work.

**Comment by LK4D4** [comment]
This issue is went off the track. Going to close it because docker networking changed drastically since.

**Comment by elgs** [comment]
Feel free to close it, because I found docker not usable and am no longer using it at all now. LXC and even OpenVZ are more usable.
