### ISSUE TITLE
Provide graphics for "Hello World"

### ISSUE THREAD

**Issue by spf13** [docker/docker#11562]
The hello world page in the user guide would strongly benefit from a few screenshots and other graphics to help the users.

http://docs.docker.com/userguide/dockerizing/

**Comment by ankushagarwal** [comment]
#dibs

**Comment by rrarunan** [comment]
@ankushagarwal when you do a PR, can you please add `fixes` or `closes` keyword to it? Thanks!

**Comment by zelahi** [comment]
If no one is taking this issue, could I work on it?

**Comment by cpuguy83** [comment]
@zelahi Go for it!

**Comment by fabioxgn** [comment]
Some animated gifs would be nice wouldn't it? At least for the hello world page.

![2015-10-02 15 34 29 728](https://cloud.githubusercontent.com/assets/1084729/10254629/57ff76da-691b-11e5-95a8-a2830fba8def.gif)

Off course a well recorded gif... :grimacing:

**Comment by thaJeztah** [comment]
https://asciinema.org as alternative to animated gifs possibly

**Comment by zelahi** [comment]
Thats a good idea.  Hmm maybe we can replace some of the old pictures with these animated gifs

**Comment by zelahi** [comment]
I added the gifs and submitted a pull request. I also updated the pull request with my sign-off.  Do I need to do anything else, or should I wait for it to get approved?

**Comment by thaJeztah** [comment]
@zelahi nope, that's it for now; now it needs to be reviewed, and at least *two* maintainers have to approve it by giving their "LGTM" (looks good to me). Thanks for contributing!

**Comment by zelahi** [comment]
#dibs, for now.  I want to still work on the gifs.  However I was running into a LinkResolver issue.  I wrote about it in the docker-dev google group.  I can post a link.  

On a side note, Thank you @thaJeztah  and @moxiegirl, and Sebastian for helping me.  I appreciate and look forward and hope I can contribute more =)

O btw if you guys wanted to take a look at the problem I was having when building the docs here is a link to it in the Google Groups:

https://groups.google.com/forum/#!topic/docker-dev/BD4jP7wTpLM

**Comment by thaJeztah** [comment]
@zelahi I just ran `make docs` and, although you get errors, the docs are actually built and running. You should make sure that your fork is updated with the latest changes from the docker repository though.

Please note that the URL for this page is changed in the new docs/tooling, and will be https://docs.docker.com/engine/userguide/dockerizing/

(`/engine/` being added to the URL)

**Comment by zelahi** [comment]
@thaJeztah , Thanks. I just added the gifs.  Let me know if the summary is unclear or if you need a better explanation.

**Comment by thaJeztah** [comment]
Closing because of https://github.com/docker/docker/pull/17163#issuecomment-149375972
