### ISSUE TITLE
docker daemon log - timestamp missing milli/nano seconds

### ISSUE THREAD

**Issue by c0rnflex** [docker/docker#11563]
The docker daemon (default /var/log/docker) is missing the trailing milli/nano seconds that exist in the "docker logs" command.

daemon:
time="2015-03-22T09:03:20Z" level="info" msg="-job container_inspect(c838886a2e3d) = OK (0)"

docker logs:
2015-03-18T15:47:55.649048237Z Wed, 18 Mar 2015 15:47:55 GMT

**Comment by programmerq** [comment]
+kind/enhancement

**Comment by scarletmeow** [comment]
+status/claimed

**Comment by Sirupsen** [comment]
Logrus v0.7.2 released with @scarletmeow's fix in https://github.com/Sirupsen/logrus/pull/158

**Comment by thaJeztah** [comment]
@scarletmeow I think this now needs another PR to update logrus; similar to this PR; https://github.com/docker/docker/pull/11553

**Comment by LK4D4** [comment]
@scarletmeow Do you wanna update logrus in docker?

**Comment by scarletmeow** [comment]
Yes, I'll work on a PR to do that.

**Comment by LK4D4** [comment]
@scarletmeow Thank you!
