### ISSUE TITLE
doc_style-guide.md was moved, but links remain unchanged in docs/README.md

### ISSUE THREAD

**Issue by southwolf** [docker/docker#11568]
In `docs/README.md` , the "Style guide" paragraph, "please see the style guide" links to `docs/sources/contributing/docs_style-guide.md`, but this document has been moved to `docs/sources/project/doc-style.md` in 8c575f2

**Comment by moxiegirl** [comment]
@southwolf Thanks for the PR. I actually had a PR pending that changed this entire document --- and fixed the error you pointed out.  I've merged that PR so recheck the file.

The result is, I'm going to close this PR without merging it as the problem no longer exists.  Thank you again!  Please bring your keen eyes to our birthday party! http://docker.party/
