### ISSUE TITLE
Files like hosts, resolve.conf, and hostname are read-write if --read-only is enabled.

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#11577]
**Problem**
 
Files like hosts, resolve.conf, and hostname are read-write if --read-only is enabled.
 
**Solution**
 
When running read-only containers, docker mounted files such as `/etc/hosts`, `/etc/resolv.conf`, and `/etc/hostname` should also be changed from their default read-write permissions to read-only.

**Comment by runcom** [comment]
@jfrazelle I'd love to undestand more about this :smile: but I'm stuck at tracing the `-read-only` flag lol

**Comment by LK4D4** [comment]
@runcom `ReadonlyRootfs` in hostconfig.
@crosbymichael do we really want this?

**Comment by runcom** [comment]
@LK4D4  traced hostconfig too and I first thought about appending `/etc/hosts` and the others to `ReadonlyPaths` found in https://github.com/docker/docker/blob/65f0ba42f5fa260d2b3b35fa22087f202058f29d/daemon/execdriver/native/template/default_template.go#L86
in this call https://github.com/docker/docker/blob/455a272aef4e109ce57c20f9ea224e4d4b32ece7/daemon/execdriver/driver.go

(I also found this definition to be duplicate https://github.com/docker/docker/blob/455a272aef4e109ce57c20f9ea224e4d4b32ece7/daemon/execdriver/driver.go#L176 and https://github.com/docker/docker/blob/455a272aef4e109ce57c20f9ea224e4d4b32ece7/daemon/execdriver/driver.go#L179)

or

add them after container initialization here:
https://github.com/docker/docker/blob/e1a0bff6b8aefdea341d01a75a0c7e9235cda421/daemon/execdriver/native/create.go
and here:
https://github.com/docker/docker/blob/0c2eb5ebfb118e1fcab84a8eb70dc8aee5a618ad/daemon/execdriver/lxc/driver.go

I'm not actually working on this right now, just wanted to undestand a little more the whole process..

**Comment by LK4D4** [comment]
@runcom Yeah, your idea makes sense. Let's wait for @crosbymichael before doing anything

**Comment by mauriyouth** [comment]
#dibs

**Comment by crosbymichael** [comment]
+1 go for it

**Comment by mauriyouth** [comment]
hello! here are my changes basically : https://github.com/mauriyouth/docker/blob/11577-fix-readonly/daemon/execdriver/driver.go#L181
but i'm getting a failing test https://github.com/docker/docker/blob/master/integration-cli/docker_cli_run_test.go#L3313. the error i'm getting is unable to mount /etc/hostname as readonly max retries reached, someone on @dqminh on irc told me it's mount returning EBUSY.https://github.com/docker/libcontainer/blob/master/rootfs_linux.go#L347
+status/help-wanted
thanks :)

**Comment by mauriyouth** [comment]
status/help-wanted

**Comment by runcom** [comment]
@mauriyouth as @dqminh told you on irc you should try to mount that files read only in setupMounts in daemon/volumes.go
Just check read-only flag is passed and change the Writable boolean accordingly

**Comment by tiborvass** [comment]
@mauriyouth are you still working on this?

**Comment by salmanbaset** [comment]
@mauriyouth please let us know so that we can update the fix.

**Comment by mauriyouth** [comment]
hi! sorry, i stopped working on it weeks ago. didn't get it to work, tried many ways...I have failing test, I can still try to report the errors I'm having. fill free to push you have a fix

**Comment by tiborvass** [comment]
@mauriyouth no worries, @runcom made a fix and he was nice enough to credit you as the author :)

**Comment by mauriyouth** [comment]
@runcom, thanks, very kind of you :) @tiborvass  thanks :)

**Comment by runcom** [comment]
No problem at all @mauriyouth!
