### ISSUE TITLE
Remove go1.2 support from pkg/pools

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#11576]
**Problem**
 
Remove go1.2 support from pkg/pools
 
**Solution**
 
Remove pkg/pools/pools_nopools.go and build tag from pkg/pools/pools.go and run tests to be sure that nothing is broken.

**Comment by unclejack** [comment]
@jfrazelle From what I know, that's needed for older versions of gccgo which don't have support for the pooling feature of Go. If that's no longer the case, we can remove it.

**Comment by adamjcook** [comment]
#dibs

**Comment by rrarunan** [comment]
@adamjcook when you do a PR, can you please add `fixes` or `closes` keyword to it? Thanks!

**Comment by adamjcook** [comment]
@rrarunan Yes, I will make sure to do this.

**Comment by unclejack** [comment]
@adamjcook Are you still interested in doing this?

**Comment by adamjcook** [comment]
@unclejack Yes, sorry, I started it last week and got held up with something. I will try to get on it tonight and I'll see how it goes. If I get held up again, I will reply.

**Comment by adamjcook** [comment]
@unclejack I am going to be forced to drop this at this time, unfortunately. I am having serious issues with the tests once `pkg/pools/pools_nopools.go` is removed and I feel that I will need some substantial time to familiarize myself with the Docker internals before moving forward.

**Comment by LK4D4** [comment]
@adamjcook No worries.

**Comment by WiseTrem** [comment]
#dibs
