### ISSUE TITLE
pkg/truncindex - Documentation

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#11578]
**Problem**
 
pkg/truncindex - Documentation
 
**Solution**
 
All things in the `pkg/` subdirectories are meant to be general purpose packages to be reused outside of Docker. The `truncindex` package provides a general 'index tree', used by Docker in order to be able to reference containers by only a few unambiguous characters of their id.
 
However, to be easily reused by another application, this package needs documentation. Add a README.md file in `pkg/truncindex/` explaining the purpose of the package, and comment exported functions and types to make it easy to use.

**Comment by cybersiddhu** [comment]
#dibs

**Comment by rrarunan** [comment]
@cybersiddhu when you do a PR, can you please add `fixes` or `closes` keyword to it? Thanks!

**Comment by ankushagarwal** [comment]
https://github.com/docker/docker/issues/14756 tracks `golint-ing` of all packages which includes Documentation of exported functions and types. We can probably close this in sight of that.

**Comment by thaJeztah** [comment]
Thanks Ankush! closing as fixed by https://github.com/docker/docker/pull/14759
