### ISSUE TITLE
Develop tool to convert a virtual disk image to a docker image

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#11575]
**Problem**
 
Develop tool to convert a virtual disk image to a docker image
 
**Solution**
 
Use a tool like qemu-nbd (or equivalent) to mount a virtual disk, extract
 the filesystem, and convert that into a single large docker image.  Bonus
 points for allowing the user to specify a base image to start with
 that's "close" to the original OS image and then ensure the single delta
 image contains only the changes and not the entire disk content.

**Comment by maximkulkin** [comment]
#dibs
