### ISSUE TITLE
pkg/sysinfo/ - Document exported functions and types

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#11582]
**Problem**
 
pkg/sysinfo/ - Document exported functions and types
 
**Solution**
 
The `/pkg/sysinfo` package lacks a proper readme and documentation for for exported functions and types.
Please add a proper readme with the package description and comments on exported methods so things like
godoc are properly populated.  You can see the package located here: https://github.com/docker/docker/tree/master/pkg/sysinfo

**Comment by EricR** [comment]
#dibs
