### ISSUE TITLE
pkg/stdcopy - Test coverage

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#11584]
**Problem**
 
pkg/stdcopy - Test coverage
 
**Solution**
 
The `pkg/stdcopy` is heavily used today for interactive sessions with a container, but is not covered by any test.
 
Improve test coverage on the `pkg/stdcopy` package. You can use the following commands to measure progress:
 
    cd pkg/stdcopy
    go test -cover -coverprofile /dev/stderr 2>&1 >/dev/null | go tool cover -func /dev/stdin

**Comment by ericsperano** [comment]
#dibs

**Comment by rrarunan** [comment]
@ericsperano when you do a PR, can you please add `fixes` or `closes` keyword to it? Thanks!

**Comment by vdemeester** [comment]
I'll be working on this as no news from @ericsperano .

**Comment by fgimenez** [comment]
#dibs

**Comment by thaJeztah** [comment]
@fgimenez I see you referenced this issue; are you working on a PR? Feel free to ask for assistance in the #docker-dev IRC channel if needed :+1: 

@vdemeester what's the overall status on this?

**Comment by fgimenez** [comment]
@thaJeztah yes, #16581 it is :) let me know if anything else is needed

**Comment by thaJeztah** [comment]
thanks @fgimenez the PR itself didn't show up here, I'll add a comment there. I'm not a reviewer in this area, but I'm sure @vdemeester can have a look when he has time.

**Comment by vdemeester** [comment]
@thaJeztah checked real quick, and :

```bash
λ go test -cover                                                                                                                                      
PASS
coverage: 100.0% of statements
ok      _/home/vincent/src/docker/docker/pkg/stdcopy    0.004s
```

So once #16581 is merged (good work @fgimenez !), we'll be able to close this one. I'll review the PR :wink:
