### ISSUE TITLE
pkg/signal/ - Document exported functions and types

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#11585]
**Problem**
 
pkg/signal/ - Document exported functions and types
 
**Solution**
 
The `/pkg/signal` package lacks a proper readme and documentation for for exported functions and types.
Please add a proper readme with the package description and comments on exported methods so things like
godoc are properly populated.  You can see the package located here: https://github.com/docker/docker/tree/master/pkg/signal

**Comment by ankushagarwal** [comment]
https://github.com/docker/docker/issues/14756 tracks `golint-ing` of all packages which includes Documentation of exported functions and types. We can probably close this in sight of that.

**Comment by thaJeztah** [comment]
yup, closing as fixed by https://github.com/docker/docker/pull/14759
