### ISSUE TITLE
pkg/pools - Test coverage

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#11588]
**Problem**
 
pkg/pools - Test coverage
 
**Solution**
 
The `pkg/pools` package is used by Docker archive management, yet the package has no test coverage.
 
Improve test coverage on the `pkg/pools` package. You can use the following commands to measure progress:
 
    cd pkg/pools
    go test -cover -coverprofile /dev/stderr 2>&1 >/dev/null | go tool cover -func /dev/stdin

**Comment by ericsperano** [comment]
#dibs

**Comment by yestin** [comment]
#dibs
