### ISSUE TITLE
pkg/networkfs/resolvconf - Document exported functions and types

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#11589]
**Problem**
 
pkg/networkfs/resolvconf - Document exported functions and types
 
**Solution**
 
The `pkg/networkfs/resolvconf` package is used for `/etc/resolv.conf` file manipulation in Docker networking code. It is meant to be reused by other applications, however it lacks documentation.
 
Add a README.md to the package, and code comments to the package's exported symbols.

**Comment by arthurbarr** [comment]
#dibs
