### ISSUE TITLE
pkg/system - Document exported functions and types

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#11581]
**Problem**
 
pkg/system - Document exported functions and types
 
**Solution**
 
The `pkg/system` package is used for portable low level functions throughout Docker code. It is meant to be reused by other applications, however it lacks documentation.
 
Add a README.md to the package, and code comments to the package's exported symbols.

**Comment by ahmetalpbalkan** [comment]
@jfrazelle I think we now have Godoc in this pkg (#11952). it's just missing a README but do we really need that?
