### ISSUE TITLE
pkg/fileutils - Refactor package

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#11598]
**Problem**
 
pkg/fileutils - Refactor package
 
**Solution**
 
The `pkg/fileutils` package is a single function package, without any tests or README.md. The goal of `pkg/` being to offer first-class packages for other projects to use, this one doesn't fit.
 
We need to either:
- Find other potential candidates from Docker to make it into this package, cover with tests, and add a README.md
- Remove the package as a whole and move the function to a different location (to be defined)

**Comment by dselans** [comment]
#dibs

**Comment by rrarunan** [comment]
@dselans when you do a PR, can you please add `fixes` or `closes` keyword to it? Thanks!

**Comment by vdemeester** [comment]
@jfrazelle I think this issue has changed a bit since then. There is more code in ``pkg/fileutils`` and one tests. I'll do a PR for adding coverage (as not sign from @dselans).

I did a quick ``grep`` on the use of ``fileutils`` and this is the result. I think adding test coverage should fix this one, right ?

```grep
build.go:170:		keepThem1, _ := fileutils.Matches(".dockerignore", excludes)
build.go:171:		keepThem2, _ := fileutils.Matches(*dockerfileName, excludes)
evaluator.go:249:	if rm, _ := fileutils.Matches(".dockerignore", excludes); rm == true {
evaluator.go:253:	if rm, _ := fileutils.Matches(b.dockerfileName, excludes); rm == true 
daemon.go:798:	realTmp, err := fileutils.ReadSymlinkedDirectory(tmp)
daemon.go:809:		realRoot, err = fileutils.ReadSymlinkedDirectory(config.Root)
daemon.go:934:		if _, err := fileutils.CopyFile(sysInitPath, localCopy); err != nil {
info.go:70:		NFd:                fileutils.GetTotalUsedFds(),
z_final_test.go:11:	t.Logf("File Descriptors: %d, Goroutines: %d", fileutils.GetTotalUsedFds(), runtime.NumGoroutine())
runtime_test.go:123:	startFds, startGoroutines = fileutils.GetTotalUsedFds(), runtime.NumGoroutine()
archive.go:444:					skip, err = fileutils.Matches(relFilePath, options.ExcludePatterns)
```
