### ISSUE TITLE
Missing documentation in API client

### ISSUE THREAD

**Issue by icecrime** [docker/docker#11593]
**Problem**
 
Document `DockerCli` struct and `NewDockerCli` function in `api/client/cli.go`.
 
**Solution**
 
Write godoc-style comments which describe idea of DockerCli(each Cmd... method represents cli command) and NewDockerCli parameters. Examples of such comments can be found in golang standard library golang.org/pkg/.

**Comment by xamyzhao** [comment]
#dibs

**Comment by rrarunan** [comment]
@xamyzhao when you do a PR, can you please add `fixes` or `closes` keyword to it? Thanks!

**Comment by xamyzhao** [comment]
@rrarunan I removed my dibs on this issue -- I don't have time to work on it at the moment. Sorry about the delay! I thought Gordon would take care of it.

**Comment by icecrime** [comment]
Removed the `status/claimed` label.

**Comment by buddhamagnet** [comment]
#dibs
