### ISSUE TITLE
pkg/ioutils - Test coverage

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#11595]
**Problem**
 
pkg/ioutils - Test coverage
 
**Solution**
 
The `pkg/ioutils` package is used at multiple places in the Docker daemon, yet  the package test coverage could be improved (it's 51% at the time of filing this issue).
 
Improve test coverage on the `pkg/ioutils` package. You can use the following commands to measure progress:
 
    cd pkg/ioutils
    go test -cover -coverprofile /dev/stderr 2>&1 >/dev/null | go tool cover -func /dev/stdin

**Comment by clnperez** [comment]
#dibs

**Comment by clnperez** [comment]
Sorry, but I haven't found the time to get to this. We should probably remove the claimed status so someone else can take a crack at it.

**Comment by duglin** [comment]
@cinperez done

**Comment by pkuorange** [comment]
#dibs
