### ISSUE TITLE
pkg/common - Refactor package

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#11599]
**Problem**
 
pkg/common - Refactor package
 
**Solution**
 
The `pkg/common` package holds only two functions, is badly named, and has no clear responsibility.
 
We need to refactor this package to either:
- Give it a proper name, README.md, and responsibility of its own
- Remove it and move its function somewhere more appropriate (to be defined)

**Comment by runcom** [comment]
I'd rename it in `pkg/random` (`random.go`, `random_test.go` and a short `README.md`)
Rename `RandomString` in `GenerateRandomString` (same as `GenerateRandomID`)
Move `TruncateID` in `pkg/truncindex`
WDYT?

**Comment by runcom** [comment]
#dibs
