### ISSUE TITLE
pkg/mount/ - Document exported functions and types

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#11594]
**Problem**
 
pkg/mount/ - Document exported functions and types
 
**Solution**
 
The `/pkg/mount` package lacks a proper readme and documentation for for exported functions and types.
Please add a proper readme with the package description and comments on exported methods so things like
godoc are properly populated.  You can see the package located here: https://github.com/docker/docker/tree/master/pkg/mount

**Comment by jamiehannaford** [comment]
#dibs

**Comment by jamiehannaford** [comment]
@jfrazelle This can be closed now I think

**Comment by cpuguy83** [comment]
Sweet, thanks!
