### ISSUE TITLE
pkg/httputils - Test coverage

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#11597]
**Problem**
 
pkg/httputils - Test coverage
 
**Solution**
 
The `pkg/httputils` is used today as a mean to resume layer pulls, but is not covered by any test.
 
Improve test coverage on the `pkg/httputils` package. You can use the following commands to measure progress:
 
    cd pkg/httputils
    go test -cover -coverprofile /dev/stderr 2>&1 >/dev/null | go tool cover -func /dev/stdin

**Comment by 4gh** [comment]
The PR really only adds tests to see if the downloaded data is the same as one in the test server it sets up.

I guess that's already better than nothing, but it would be nice to have a test that checks the resume function. I'm not really sure how to do this. The test server should simulate a drop in the connection some time in the string, I guess. Any hints?
