### ISSUE TITLE
The builtins.Register function is undocumented

### ISSUE THREAD

**Issue by icecrime** [docker/docker#11590]
**Problem**
 
Document `builtins.Register`
 
**Solution**
 
Write godoc-style docstring form Register function in `builtins/builtins.go`.

**Comment by asymmetric** [comment]
[This](https://github.com/docker/docker/blob/master/builtins/builtins.go) is where it's at.

**Comment by Jamestown** [comment]
#dibs

**Comment by rrarunan** [comment]
@Jamestown when you do a PR, can you please add `fixes` or `closes` keyword to it? Thanks!

**Comment by wonderflow** [comment]
Builtins is going to be moved , document is no need. #11620

**Comment by icecrime** [comment]
Makes sense (and this has been claimed 21 days ago without activity so I guess it's done).
