### ISSUE TITLE
pkg/networkfs/etchosts - Document exported functions and types

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#11592]
**Problem**
 
pkg/networkfs/etchosts - Document exported functions and types
 
**Solution**
 
The `pkg/networkfs/etchosts` package is used for `/etc/hosts` file manipulation in Docker networking code. It is meant to be reused by other applications, however it lacks documentation.
 
Add a README.md to the package, and code comments to the package's exported symbols.

**Comment by jasonrichardsmith** [comment]
#dibs

**Comment by vdemeester** [comment]
According to this https://github.com/docker/docker/pull/12428 and https://github.com/docker/docker/issues/11673, this one might be *closeable* :wink:.
