### ISSUE TITLE
docker trust logs are lacking and can be verbose and not useful.

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#11608]
**Problem**
 
The docker trust logs are lacking and can be verbose and not useful.
 
**Solution**
 
Review the logging calls in https://github.com/docker/docker/tree/master/trust and use our standard log package `github.com/Sirupsen/logrus` to make meaningful log messages.
 
It could be helpful to remove all existing log calls and then go through and log meaning requests, warnings, errors, and debug messages for the API.

**Comment by MHBauer** [comment]
Trust is [gone](https://github.com/docker/docker/commit/cba4bbad4f0e03d782a22f57d653d3109bca0208).
