### ISSUE TITLE
The api route postAuth does not have a structured response type

### ISSUE THREAD

**Issue by crosbymichael** [docker/docker#11607]
**Problem**
 
The api route postAuth does not have a structured response type
 
**Solution**
 
Create a struct type in the `/api/types/types.go` file that specifies the response of the `postAuth` function in
`/api/server/server.go` and use that type to encode the response on the server side and decode into that struct
on the client side of the api in `/api/client/commands.go`.

**Comment by runcom** [comment]
#dibs
