### ISSUE TITLE
docker registry logs are lacking and can be verbose and not useful

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#11609]
**Problem**
 
The docker registry logs are lacking and can be verbose and not useful.
 
**Solution**
 
Review the logging calls in https://github.com/docker/docker/tree/master/registry and use our standard log package `github.com/Sirupsen/logrus` to make meaningful log messages.
 
It could be helpful to remove all existing log calls and then go through and log meaning requests, warnings, errors, and debug messages for the API.

**Comment by stevvooe** [comment]
Could you provide further examples of the issues with registry logging? We are already using `github.com/Sirupsen/logrus` as of docker/distribution#151. Also, they are not primarily meant to be human readable, as is the theme of the logrus package. Perhaps, adding tools for reading logs would be helpful.

**Comment by stevvooe** [comment]
@jfrazelle Just read the link more carefully: agreed, this is a problem with the registry package. Should we hold off on this until we integrate the v2 client from docker/distribution?

**Comment by jfrazelle** [comment]
op sorry we can close these were party issues so i wasnt the original author ;)
