### ISSUE TITLE
docker volumes logs are lacking and can be verbose and not useful

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#11606]
**Problem**
 
The docker volumes logs are lacking and can be verbose and not useful.
 
**Solution**
 
Review the logging calls in https://github.com/docker/docker/tree/master/volumes and use our standard log package `github.com/Sirupsen/logrus` to make meaningful log messages.
 
It could be helpful to remove all existing log calls and then go through and log meaning requests, warnings, errors, and debug messages for the API.

**Comment by cpuguy83** [comment]
Closing as this is not relevant anymore.
