### ISSUE TITLE
pkg/chrootarchive - Test coverage

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#11601]
**Problem**
 
pkg/chrootarchive - Test coverage
 
**Solution**
 
The `pkg/chrootarchive` package is an essential piece of Docker security, yet the package test coverage could be improved (it's 40% at the time of filing this issue).
 
Improve test coverage on the `pkg/chrootarchive` package. You can use the following commands to measure progress:
 
    cd pkg/chrootarchive
    go test -cover -coverprofile /dev/stderr 2>&1 >/dev/null | go tool cover -func /dev/stdin

**Comment by yestin** [comment]
#dibs
