### ISSUE TITLE
Missing documentation in API client

### ISSUE THREAD

**Issue by icecrime** [docker/docker#11600]
**Problem**
 
Document `DockerCli` methods or make them private function in `api/client/cli.go`.
 
**Solution**
 
Make methods not used outside package private, document remained public methods in godoc-style.

**Comment by robzhu** [comment]
#dibs

**Comment by rrarunan** [comment]
@robzhu when you do a PR, can you please add `fixes` or `closes` keyword to it? Thanks!

**Comment by vdemeester** [comment]
According to https://godoc.org/github.com/docker/docker/api/client#DockerCli, is this one closed or does it still need work ?

**Comment by thaJeztah** [comment]
ping @icecrime do you still think additional changes are require?

(thanks, @vdemeester)

**Comment by icecrime** [comment]
Sounds good! Thanks,
