### ISSUE TITLE
pkg/archive - Test coverage

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#11603]
**Problem**
 
pkg/archive - Test coverage
 
**Solution**
 
The `pkg/archive` package is an essential piece of Docker image management, yet the package test coverage could be vastly improved (it's 57% today).
 
Improve test coverage on the `pkg/archive` package. You can use the following commands to measure progress:
 
    cd pkg/archive
    go test -cover -coverprofile /dev/stderr 2>&1 >/dev/null | go tool cover -func /dev/stdin

**Comment by dbhaskaran** [comment]
#dibs

**Comment by rrarunan** [comment]
@dbhaskaran when you do a PR, can you please add `fixes` or `closes` keyword to it? Thanks!

**Comment by vdemeester** [comment]
no news from @dbhaskaran, I'll be working on it as well.

@jfrazelle Is it better to provide several PR with small addition (to tests) or a big one that kinda fix it ? Is there an overall goal for the coverage ? (something like each "module" like pkg/archive should have at least 75% of coverage)

**Comment by jfrazelle** [comment]
smaller will get faster feedback and review, because its less strain at first glance but you could do one with logical commits, showing smaller changes, up to you :)

**Comment by vdemeester** [comment]
@crosbymichael Not sur it has to close already, there is still some stuff to test. Any way I'll make more pull request based on this one ;). My goal is a coverage at 75% at least.
