### ISSUE TITLE
Listenbuffer package does not have a README or docs for the type.

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#11604]
**Problem**
 
Listenbuffer package does not have a README or docs for the type.
 
**Solution**
 
The listenbuffer is a way to accept incomming connections and block using the kernels queue until the process is ready to accept.  This package needs documentation to make it a standalone package that others can use along with comments on the exported methods and types so that it works on godoc.

**Comment by Sirupsen** [comment]
#dibs

**Comment by Sirupsen** [comment]
Needs tests too :)

**Comment by cpuguy83** [comment]
Closed by #11735
