### ISSUE TITLE
The list images API endpoint does not use structured responses for versions less than 1.17.

### ISSUE THREAD

**Issue by crosbymichael** [docker/docker#11615]
**Problem**
 
The list images API endpoint does not use structured responses for versions less than 1.17.
 
**Solution**
 
Around line 284 of `/api/server/server.go` an engine table is created to the api response for api versions less than 1.17.
We need to create a struct with the fields and json tags for the 1.17 response that can be populated and returned to the client.
In the current client code docker's CLI will not consume this so it only needs to be created and used on the server
side.  The struct can be created in `/api/types/types.go`.

**Comment by jamshid** [comment]
#dibs

**Comment by rrarunan** [comment]
@jfrazelle Fix is in PR #11674 . Needs closing.

**Comment by rrarunan** [comment]
@jamshid when you do a PR, can you please add `fixes` or `closes` keyword to it? Thanks!

**Comment by jamshid** [comment]
Yes, thanks, I will finish it by Sunday. #dibs

**Comment by runcom** [comment]
closed by #12184
