### ISSUE TITLE
The docker networkdriver logs are lacking and can be verbose and not useful.

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#11614]
**Problem**
 
The docker networkdriver logs are lacking and can be verbose and not useful.
 
**Solution**
 
Review the logging calls in https://github.com/docker/docker/tree/master/networkdriver and use our standard log package `github.com/Sirupsen/logrus` to make meaningful log messages.
 
It could be helpful to remove all existing log calls and then go through and log meaning requests, warnings, errors, and debug messages for the API.

**Comment by jmzwcn** [comment]
Hi @jfrazelle , do you mean https://github.com/docker/docker/tree/master/daemon/networkdriver?

**Comment by jmzwcn** [comment]
#dibs

**Comment by jmzwcn** [comment]
this issue still exits? refer to ##11618

**Comment by vdemeester** [comment]
@jfrazelle https://github.com/docker/docker/tree/master/networkdriver doesn't exists anymore, I think this issue can be closed.

**Comment by LK4D4** [comment]
Closing
