### ISSUE TITLE
api/client - The code for all cli commands are in one file

### ISSUE THREAD

**Issue by crosbymichael** [docker/docker#11610]
**Problem**
 
api/client - Break down commands in multiple files
 
**Solution**
 
The `api/client/commands.go` file hold the code for every Docker client command, which makes up for 2700+ lines!
 
Break this down into one dedicated file per subcommand (e.g., `docker push` related code in `api/client/push.go`). Note that the m"main function" for each subcommand is easily found as it is always named `CmdName` (e.g., `CmdPush`) in this file.

**Comment by joeygibson** [comment]
#dibs
