### ISSUE TITLE
Remove ErrDockerfileEmpty from builder/evaluator.go

### ISSUE THREAD

**Issue by icecrime** [docker/docker#11611]
**Problem**
 
Remove `ErrDockerfileEmpty` from `builder/evaluator.go`.
 
**Solution**
 
We return non-hardcoded errors all over the package, so it makes sense instead of `ErrDockerfileEmpty` return error with file name/path like in other places.

**Comment by runcom** [comment]
#dibs

**Comment by runcom** [comment]
@icecrime can be closed

**Comment by icecrime** [comment]
That was fast :p
