### ISSUE TITLE
The container wait API endpoint does not use structured responses.

### ISSUE THREAD

**Issue by crosbymichael** [docker/docker#11616]
**Problem**
 
The container wait API endpoint does not use structured responses.
 
**Solution**
 
Create a struct with json tags for the `postContainersWait` api endpoint and use it to encode and decode the json response
.  Implement the client code to decode the response into this type and place it in the `api/types/types.go` file.

**Comment by diogogmt** [comment]
I would like to tackle this ticket as part of the docker.party event.

@crosbymichael would you be able to provide some mentor guidance?

* Which docs do you recommend for setting up docker in a dev environment?
* Is there any other json struct I can use as a baseline for the postContainersWait endpoint?
* What would be the process to test and validate the patch?

Cheers

**Comment by duglin** [comment]
Hi,  
1 - See https://docs.docker.com/project/software-required/
2- See https://github.com/docker/docker/blob/master/api/types/types.go and https://github.com/docker/docker/blob/master/api/server/server.go#L742 for a sample
3 - step 1 should walk you thru the testing process, but in short if you do "make test" it should run all of the testcases for you.

**Comment by diogogmt** [comment]
Thanks @duglin that should help me get started.

**Comment by parknicker** [comment]
#dibs @randomcanary

**Comment by rrarunan** [comment]
@jfrazelle This issue needs closing.
