### ISSUE TITLE
The container exec create API endpoint does not use structured responses.

### ISSUE THREAD

**Issue by crosbymichael** [docker/docker#11613]
**Problem**
 
The container exec create API endpoint does not use structured responses.
 
**Solution**
 
Implement a struct in `/api/types/types.go` for the response of the `postContainerExecCreate` api endpoint
that can be used to encode the result on the server and decode the response on the client.  Changes implementing this
type will need to be done in `/api/server/server.go` and for the client in `/api/client/commands.go`.

**Comment by runcom** [comment]
#dibs
