### ISSUE TITLE
Refactor ipallocator package to not use global state. 

### ISSUE THREAD

**Issue by crosbymichael** [docker/docker#11624]
**Problem**
 
The package `daemon/networkdriver/ipallocator` uses global state for ip address allocation.
 
**Solution**
 
The `ipallocator` used by Docker to assign IP addresses to starting containers stores its state in the global scope (see the `allocatedIPs` var in `ipallocator.go`).
 
Refactor the package to avoid using global state, for example by providing a `func New() &IPAlocator` call where `IPAllocator` would hold the entire state.

**Comment by calavera** [comment]
#dibs :grimacing:
