### ISSUE TITLE
Document the relationship between --memory and --memory-swap

### ISSUE THREAD

**Issue by crosbymichael** [docker/docker#11629]
**Problem**
 
There are two flags --memory and --memory-swap and the interaction between both of them is unclear in the documentation
 
**Solution**
 
Add documentation for using --memory and --memory-swap together and how they relate and interact with each other.  i.e. does the memory limit have to be larger or smaller than the swap limit?

**Comment by roberttaylor426** [comment]
Some examples would also be helpful.

**Comment by thaJeztah** [comment]
There's partial documentation in run reference; https://github.com/docker/docker/blob/master/docs/sources/reference/run.md

But it can use some practical examples

**Comment by hqhq** [comment]
Sorry didn't do this at the first time, I add some examples in https://github.com/docker/docker/pull/11694, see if we can fix this issue.

**Comment by zacharybrady** [comment]
#dibs

**Comment by thaJeztah** [comment]
@zacharybrady I think this is already handled in https://github.com/docker/docker/issues/11694

@hqhq should this issue be closed, or is there still work to do?

**Comment by hqhq** [comment]
@thaJeztah Yes, I think this issue should be closed now, I'll dibs it next time :)

**Comment by thaJeztah** [comment]
/ping @jfrazelle this issue is resolved by https://github.com/docker/docker/pull/11694 (see above)

**Comment by jfrazelle** [comment]
Thanks
