### ISSUE TITLE
Docker lacks documentation on what the defaults mounts that are added for network files.

### ISSUE THREAD

**Issue by crosbymichael** [docker/docker#11627]
**Problem**
 
Docker lacks documentation on what the defaults mounts that are added for network files.
 
**Solution**
 
Document the docker provided mounts for things like `/etc/hosts`, `/etc/hostname`, and `/etc/resolv.conf` that docker automatically sets up and bind mounts into containers as read-write as the default container profile.

**Comment by jasonrichardsmith** [comment]
+writing

**Comment by jasonrichardsmith** [comment]
#dibs
