### ISSUE TITLE
Add libcontainer's container spec to documentation website.

### ISSUE THREAD

**Issue by crosbymichael** [docker/docker#11628]
**Problem**
 
Libcontainer has information about how a container is created and what is in the default profile.  This is not documented in the docs.docker.com site.
 
**Solution**
 
Format and more the informatin from the document at https://github.com/docker/libcontainer/blob/master/SPEC.md into the docs.docker.com site so that this information is easier to find and understand what goes into making the container.

**Comment by erriapo** [comment]
#dibs

**Comment by rrarunan** [comment]
@erriapo when you do a PR, can you please add `fixes` or `closes` keyword to it? Thanks!

**Comment by crosbymichael** [comment]
Going to close this while the OCP project is working on a container specification that docker will honor.
