### ISSUE TITLE
builtins - Move functions out of this package and remove the package

### ISSUE THREAD

**Issue by crosbymichael** [docker/docker#11620]
**Problem**
 
builtins - Refactor this package out
 
**Solution**
 
The `builtins/` package at the root of the repository has no clear utility and responsibility.
 
Refactor the code to move these functions out and suppress the `builtins/` subdirectory.

**Comment by ctate** [comment]
working on this per docker.party #dibs

**Comment by rrarunan** [comment]
@ctate when you PRs, can you please add `fixes` or `closes` keyword to it? Thanks!

**Comment by studiotate** [comment]
@rrarunan will do!

**Comment by ctate** [comment]
@rrarunan will do!

**Comment by wonderflow** [comment]
@ctate  Did you finish it now? Hope to know where will you add these functions in builtins.

**Comment by thaJeztah** [comment]
@ctate could you let us know if you're still planning to work on this. If not, no problem, then someone else can do it, just leave a comment to let us know :)

**Comment by runcom** [comment]
@thaJeztah sorry but this was just done here https://github.com/docker/docker/pull/12486 and already merged :(

**Comment by thaJeztah** [comment]
@runcom thanks! There's so much refactoring going on at the moment that it's hard to keep track :smiley:


I'll close this, because this should be resolved by https://github.com/docker/docker/pull/12486
