### ISSUE TITLE
Document use cases for --net host feature.

### ISSUE THREAD

**Issue by crosbymichael** [docker/docker#11630]
**Problem**
 
There is little documentation around the --net host feature and use cases
 
**Solution**
 
Document different use cases such as running a load balancer or nginx frontend with --net host in order to have the best possible performance

**Comment by VictorDenisov** [comment]
+status/claimed

**Comment by ankushagarwal** [comment]
#dibs

**Comment by rrarunan** [comment]
@ankushagarwal when you do a PR, can you please add `fixes` or `closes` keyword to it? Thanks!

**Comment by ankushagarwal** [comment]
@crosbymichael 
1. Is this the place where you intended the documentation to go or was it docs/sources/articles/networking.md ?
2. I wanted to be concise. Is this paragraph too less?

**Comment by moxiegirl** [comment]
@ankushagarwal I'm the writer on the open source team. Emphasize completeness over conciseness.  We can always trim but adding missing information is difficult.  You can add should add examples of the flag to here:

https://docs.docker.com/reference/run/#network-settings

If you see an opportunity to add it to networking.md you can also do that.  However, nothing beats examples in the reference!
