### ISSUE TITLE
Using btrfs with docker on SLES12

### ISSUE THREAD

**Issue by Pensu** [docker/docker#11633]
So, I am using btrfs with docker on SLES12 and getting exec format error. Here is my docker info:

linux-pohb:/home/peeyush # docker info
Containers: 9
Images: 1
Storage Driver: btrfs
 Build Version: Btrfs v3.16+20140829
 Library Version: 101
Execution Driver: native-0.2
Kernel Version: 3.12.28-4-default
Operating System: SUSE Linux Enterprise Server 12
CPUs: 1
Total Memory: 1.722 GiB
Name: linux-pohb
ID: IHKP:MGXP:QOQP:MPYH:2SO2:NUNM:FTVN:2EZO:JAJL:LSFX:S7UD:DIJW
WARNING: No swap limit support

I am running docker with option "-s btrfs"

linux-pohb:/home/peeyush/docker.bld/src/github.com/docker/docker/bundles/1.5.0/dyngccgo # ./docker -d --iptables=false -s btrfs -g /var/lib/docker
time="2015-03-23T11:24:59+05:30" level="info" msg="+job serveapi(unix:///var/run/docker.sock)" 
time="2015-03-23T11:24:59+05:30" level="info" msg="Listening for HTTP on unix (/var/run/docker.sock)" 
time="2015-03-23T11:24:59+05:30" level="info" msg="+job init_networkdriver()" 
time="2015-03-23T11:24:59+05:30" level="info" msg="-job init_networkdriver() = OK (0)" 
time="2015-03-23T11:25:00+05:30" level="info" msg="WARNING: Your kernel does not support cgroup swap limit." 
time="2015-03-23T11:25:00+05:30" level="info" msg="Loading containers: start." 
................
time="2015-03-23T11:25:00+05:30" level="info" msg="Loading containers: done." 
time="2015-03-23T11:25:00+05:30" level="info" msg="docker daemon: 1.5.0 b34e0cd; execdriver: native-0.2; graphdriver: btrfs" 

And, yeah, I am using gccgo! Now whenever I try to run a container, I get an execution format error.

linux-pohb:/home/peeyush # docker run learn/tutorial echo "hello world"
Unable to find image 'learn/tutorial:latest' locally
Pulling repository learn/tutorial
8dbd9e392a96: Download complete 
Status: Downloaded newer image for learn/tutorial:latest
exec format errortime="2015-03-23T11:26:32+05:30" level="fatal" msg="Error response from daemon: Cannot start container a24eff21f6cd64a58dba30a239e60fbc4ce43badb3af70caea13e97f17417779: exec format error" 

As far as I know btrfs is supported. What exactly am I doing wrong here?

**Comment by unclejack** [comment]
This looks like a gccgo problem related to the init. /cc @brahmaroutu

**Comment by brahmaroutu** [comment]
@Pensu Can you share the details on how you are building with gccgo? 

/cc @inatatsu @laboger

**Comment by Pensu** [comment]
@brahmaroutu I erased everything and built it from scratch, everything is working fine. Not sure what was the error, but for now, it's working. Thanks!
