### ISSUE TITLE
Document the flow for creating official images and the steps needed.

### ISSUE THREAD

**Issue by crosbymichael** [docker/docker#11631]
**Problem**
 
There are no clear documentation on what it takes to create an official image.
 
**Solution**
 
Document the steps to create and submit a new official image to the correct repositories.  @tianon can be a source for information on what needs to happen and what is expected.

**Comment by md5** [comment]
What about this doc? https://github.com/docker/docker/blob/master/docs/sources/docker-hub/official_repos.md

**Comment by thaJeztah** [comment]
I think what's missing is mainly some process-related information;

- What counts as an official image? (ie, if I am the author of an open-source project, can I submit it as an official image?)
- Is there some kind of approval proces?
- *Who* is allowed to submit (and maintain) an official image? e.g., can I submit a "Microsoft Windows" image, even if I'm not affiliated with Microsoft?
- After submitting, how much time is required for me to maintain the image? What does Docker expect from me as a maintainer?

**Comment by tianon** [comment]
I think @psftw is working on some updates to this, actually.

**Comment by psftw** [comment]
Better late than never. https://github.com/docker/docker/pull/12644

I'm also going to take a look at the `docker-library/official-images` documentation next to see if I can't address some FAQs about the requirements there.
