### ISSUE TITLE
unexpected end of JSON input

### ISSUE THREAD

**Issue by balboah** [docker/docker#11638]
On multiple occasions I have hit this error:

```
Mar 23 08:37:40 ip-10-0-3-20.eu-west-1.compute.internal dockerd[29586]: time="2015-03-23T08:37:40Z" level="info" msg="-job create(dpi) = ERR (1)"
Mar 23 08:37:40 ip-10-0-3-20.eu-west-1.compute.internal dockerd[29586]: time="2015-03-23T08:37:40Z" level="error" msg="Handler for POST /containers/create returned error: unexpected end of JSON input"
```

It might be triggered by too much disk IO. But should it have to be manually cleaned up to make it work again?

**Comment by SimplicityGuy** [comment]
@balboah can you provide a bit more information? the docker version would be useful:
```bash
docker version
```
and if you have any steps to reproduce this. Perhaps there's a Dockerfile that you can point to in this issue to help reproduce it.

**Comment by balboah** [comment]
Reproducing it is probably doing stdout logging in a while loop to make it log too much things while having a limited disk IO (amazon ec2 default EBS for example). Another related problem was the ever growing output buffers in docker daemon that you fixed recently.
