### ISSUE TITLE
Docker doesn't binds ports if HostPort value is a integer

### ISSUE THREAD

**Issue by y3ti** [docker/docker#11645]
Hi,

I have a problem with a docker. I create new container via docker rest-like api.

```
$ cat body
{
  "Image": "postgres:latest",
  "HostConfig":{
    "PublishAllPorts":true,
    "VolumesFrom": ["postgresql_01_data"],
    "PortBindings": {
      "5432/tcp": [
        {"HostPort":5432}
      ]
    }
  }
}

$ curl -X POST -d @body -H "Content-Type: application/json" http://X.X.X.X:2375/containers/create
```
When `HostPort` value is a integer docker doesn't bind port (when i pass value as a string all works fine).
Docker doesn't return any warning or error message. 
When value is integer then even `VolumesFrom` doesn't work too.

```
# docker -v
Docker version 1.5.0, build a8a31ef

# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.10
Release:	14.10
Codename:	utopic

# # uname -a
Linux ****** 3.14.32-xxxx-grs-ipv6-64 #1 SMP Sat Feb 7 11:35:27 CET 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by estesp** [comment]
It must be a string as that is how it is represented in the JSON->container config marshalling to Go types. There have been other issues where this was discussed and confirmed it must be a string.  As far as the error/warning reporting, we can look into whether a better flow of JSON validation errors can end up back at the caller in this situation.

**Comment by y3ti** [comment]
Ok, thank you for response. Now i understand.
