### ISSUE TITLE
Is docker supported in redhat 6.5?

### ISSUE THREAD

**Issue by sagiegurari** [docker/docker#11643]
I see in docker docs, installation notes for redhat 6.5:
https://docs.docker.com/installation/rhel/#red-hat-enterprise-linux-6.5-installation

And everything works for me, however,

1. When starting the docker daemon i see 
INFO[0000] WARNING: You are running linux kernel version 2.6.32-504.el6.x86_64, which might be unstable running docker. Please upgrade your kernel to 3.8.0.

2. In the offical redhat pages that list all of the redhat base images, I see redhat 6.5 but it states it should run on redhat 7
https://access.redhat.com/search/#/container-images
From the page:
```
This platform image provides a minimal runtime to build, run and deploy Red Hat Enterprise Linux 6.5 applications as a container on a Red Hat Enterprise Linux 7 and Red Hat Enterprise Linux 7 Atomic host.
```

So i'm not sure if I can take docker to production on top of redhat 6.5.
Any official answer would be appreciated, thanks.

**Comment by cpuguy83** [comment]
Yes, RHEL 6.5 is supported but...

1) Make sure you are always on the latest RHEL 2.6.32 kernel
2) You must **not** use the statically built Docker binary (this is true for all devmapper installations).

**Comment by sagiegurari** [comment]
thanks
