### ISSUE TITLE
Support For EC2 instances.

### ISSUE THREAD

**Issue by jainishshah17** [docker/docker#11661]
Please add support which can allow user to login to EC2 instance to deploy Docker containers. By which we can login to EC2 using SSH and deploy and manage containers there.

**Comment by jfrazelle** [comment]
have you seen docker/machine?

**Comment by jainishshah17** [comment]
will take look thank you

**Comment by Piste** [comment]
you can run sudo yum install docker -y in Amazon Linux on an EC2.
