### ISSUE TITLE
`Failed to upload layer` to docker hub

### ISSUE THREAD

**Issue by fommil** [docker/docker#11677]
I am trying to upload an image to a private docker hub repo, but get this

```
5297b7baddb7: Pushing [============>                                      ] 1.342 GB/5.386 GB 43m24s
2015/03/24 00:43:10 Failed to upload layer: Put https://cdn-registry-1.docker.io/v1/images/5297b7baddb7892d985240b35d7cf6cec88da7f7ca5e4a43f28903eb779f3304/layer: EOF
```

there are reports that the timeout needs to be increased: https://github.com/docker/docker-registry/issues/121 https://github.com/docker/docker-registry/issues/118 but I'm not in charge of the registry so I don't believe I can change the timeouts.

**Comment by vivekchopra** [comment]
Could you provide additional information, such as 
* the output of docker version
* the output of docker info
* the output of uname -a
* host distribution and version ( ubuntu 14.04, RHEL, fedora 21 )
Also, could you do a "-D" and send the debug output?

+kind/bug

**Comment by fommil** [comment]
this worked second time, but since you asked.

```
Client version: 1.3.3
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): d344625
OS/Arch (client): linux/amd64
Server version: 1.3.3
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): d344625
```

```
Containers: 4
Images: 69
Storage Driver: aufs
 Root Dir: /mnt/archive/docker/aufs
 Dirs: 77
Execution Driver: native-0.2
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
Username: fommil
Registry: [https://index.docker.io/v1/]
WARNING: No memory limit support
WARNING: No swap limit support
```

```
Linux Samskara 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt7-1 (2015-03-01) x86_64 GNU/Linux
```

Running Debian Jessie, with 100MiB internet connection (uploading at a poor 20MiB).
