### ISSUE TITLE
explicitly talk about /etc/default/docker

### ISSUE THREAD

**Issue by lukereimer** [docker/docker#11676]
References to editing the `DOCKER_OPTS` in the `/etc/default/docker` file seem to be sprinkled throughout the documentation, but never explicitly stated or explained. Also everywhere it is referenced it specifies Ubuntu, but I believe it is also true for CentOS.

**Comment by lukereimer** [comment]
+kind/writing

**Comment by resouer** [comment]
#dibs We're writing a PR to solve this.

**Comment by rrarunan** [comment]
@resouer Can you please use `fixes` or `closes` keyword instead of `Fix` as you have in some of your PRs. Thanks!

**Comment by resouer** [comment]
@rrarunan got it. Thanks for reminding!

**Comment by vdemeester** [comment]
Seems like it should be closed (PR merged)

**Comment by runcom** [comment]
Thanks @vdemeester
