### ISSUE TITLE
Docker on AIX?

### ISSUE THREAD

**Issue by resouer** [docker/docker#11680]
Is there any way we can bring Docker on AIX datacenter? 

Our team are trying to start a transformation inside a traditional "big" company, but it seems AIX is an obstacle we should pass!

**Comment by adilroot** [comment]
I think you can use linux on power as lpar, a possible scenario is to use AIX (PowerVM or powerVC) to manage hardware and linux lpars to manage docker.

**Comment by programmerq** [comment]
+kind/feature

**Comment by unclejack** [comment]
@duglin Can you respond to this issue after you get an answer regarding Docker support for AIX, please? Thanks!

**Comment by aixdevguy** [comment]
Hi resouer,

Exited to see you have interest in Docker support for AIX. This is something we are exploring and would like to know more about what type of applications you would be interested to have packaged and deployed via Docker on AIX. The container technology on AIX is workload partitions (WPARs). Is your team currently using WPARs as a lightweight virtualization construct for multiple isolated workloads within an OS instance?

**Comment by duglin** [comment]
@resouer any thoughts on @aixdevguy's question?

**Comment by resouer** [comment]
@aixdevguy Sorry for a late response ... And I think you can imagine, most of the applications in this case are based on WebSphere Application Server. I'm very interested in WPARs as you mentioned, do you have more details about that?

**Comment by zrml** [comment]
News on this? Or is the described way (LPAR on Power with Linux) the only option?
thank you

**Comment by aixdevguy** [comment]
Following up on above, IBM is still evaluating the potential of supporting Docker with AIX in the future. An important part of the study is understanding what types of applications Power and AIX customers would want to see dockerized. If there is a sufficient collection of software stacks that would be made available, that drives a more interesting case to bring Docker support to AIX. Docker is already been ported Linux on Power.

**Comment by zrml** [comment]
thanks; make sense

**Comment by duglin** [comment]
I think this issue can be closed now.  If anyone disagrees please let me know.

**Comment by truthadjustr** [comment]
I like to comment a very important use case that I did not notice being mentioned above. Bringing-in latest stuff into AIX like python/numpy/scikit/panda etc via a docker mechanism which can closely communicate with the host AIX applications. The docker container instance can become like a "stargate" to a remote rabbitmq and other linux friends. IS THIS NOT VERY OBVIOUS?

**Comment by CodyKurtz** [comment]
I'd love to see IBM Integration Bus and IBM MQ running in docker containers. It would be great if we could bring up a set of queue managers with an iib node, using docker compose on AIX.
