### ISSUE TITLE
User Guide / Using Docker / "Removing Our Web Application Container" Grammatical Error

### ISSUE THREAD

**Issue by mjang** [docker/docker#11683]
In the following section: http://docs.docker.com/userguide/usingdocker/#removing-our-web-application-container

second paragraph: 

What's happened? -> What happened?

**Comment by matthewkmayer** [comment]
The contraction of "what has happened" is correct, but "What happened" might be smoother.

**Comment by mjang** [comment]
I've never seen "what has" contracted to "what's".
