### ISSUE TITLE
Docker-Machine : can't create a VM

### ISSUE THREAD

**Issue by christiprez** [docker/docker#11704]
Hello,

I am trying to use Docker-Machine but I cannot create a machine. Here is the error I am getting : 
ERRO[0036] Error creating machine: exit status 1
WARN[0036] You will want to check the provider to make sure the machine and associated resources were properly removed.

I am using a VM on VirtualBox with Centos7. 
 uname -a ==> 
Linux localhost.localdomain 3.10.0-123.20.1.el7.x86_64 #1 SMP Thu Jan 29 18:05:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

docker version ==> 
Client version: 1.3.2
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 39fa2fa/1.3.2
OS/Arch (client): linux/amd64
2015/03/24 10:17:23 Get http:///var/run/docker.sock/v1.15/version: dial unix /var/run/docker.sock: no such file or directory

Any idea how to resolve the issue ?

**Comment by estesp** [comment]
Hey @christiprez, you should open this issue in the https://github.com/docker/machine repository, as that will get attention from the machine team.  Also, you might check their issue list in case someone else has similar problems? https://github.com/docker/machine/issues

**Comment by christiprez** [comment]
Thanks estesp
