### ISSUE TITLE
Update "Process Management with CFEngine"  Article to run Under Docker 1.50

### ISSUE THREAD

**Issue by twitteried** [docker/docker#11703]
Dockerfile appears broken and outdated. Running "wget -qO- http://cfengine.com/pub/gpg.key | apt-key add - " returns a 403. 

https://github.com/docker/docker/blob/b64558907139911b86d846de70ab859504cc45a2/docs/sources/articles/cfengine_process_management.md

Link to article with error: https://docs.docker.com/engine/articles/cfengine_process_management/

**Comment by moxiegirl** [comment]
@twitteried Thanks for the test work @twitteried.  Good job. I'll tweak this issue description and create a new issue for someone to fix the article.  That fix should close #11560 and #11703

**Comment by twitteried** [comment]
@moxiegirl - No problem. I'll try to set aside some time to test more things this week.

**Comment by moxiegirl** [comment]
@twitteried thank you, that would be cool.

**Comment by zacharybrady** [comment]
#dibs

**Comment by rrarunan** [comment]
@jfrazelle Can you help update this issue?

**Comment by jfrazelle** [comment]
@moxiegirl what is the status here is this an issue?

**Comment by moxiegirl** [comment]
@jfrazelle It looked like the original tester was going to pick this up and then didn't have time.  I'll pull off the claimed status.  Not sure why it is on there I see no dibs hit.

**Comment by zelahi** [comment]
So from my understanding this is a doc issue, and the document needs to be updated, but does the link need to be updated

**Comment by thaJeztah** [comment]
@zelahi yes, I think this is a docs issue, if I understand correctly, @twitteried tested the docs (https://github.com/docker/docker/issues/11560) and discovered that there were some errors when testing the docs. If you can fix those, that'd be great.

**Comment by zelahi** [comment]
In regards to the wget issue, I was unable to reproduce the issue.  I believe I got passed it okay.  So I ran the docker build command and saved the output to a file.  I attached the output to show and here is a small snippet that I believe shows this is not an issue:

Step 3 : RUN wget -qO- http://cfengine.com/pub/gpg.key | apt-key add -
 ---> Running in 32a880977d1c
OK

That was from the output when I ran the docker build command listed on the doc.  I saved my output to a text file and attached it here.  

I do think there is a different issue that is not related to the wget error here.  But I can open up a new bug for that one

[test_results.txt](https://github.com/docker/docker/files/56413/test_results.txt)

Incase you want to see the other issue I am running into when building this, the line here describes it: 
The method driver /usr/lib/apt/methods/https could not be found.

**Comment by zelahi** [comment]
ping @thaJeztah, @moxiegirl

**Comment by thaJeztah** [comment]
@zelahi I was able to fix that error by adding `apt-transport-https`, i.e.,

    RUN apt-get update && apt-get install -y apt-transport-https wget lsb-release unzip ca-certificates

However, then I got;

```
Err http://cfengine.com trusty/main amd64 Packages
  HttpError403
W: Failed to fetch http://cfengine.com/pub/apt/dists/trusty/main/binary-amd64/Packages  HttpError403

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

So probably the Dockerfile needs an update. I don't have experience with cfengine, but perhaps you can have a look at the install instructions; https://docs.cfengine.com/docs/3.5/getting-started-installation-installing-community.html
