### ISSUE TITLE
pkg/stringutils - remove RandomString function

### ISSUE THREAD

**Issue by runcom** [docker/docker#11721]
As the title says, `RandomString` from `pkg/stringutil` shouldn't be used anymore. Code relying on this function should call `GenerateRandomID` from `pkg/stringid` instead.
Discussion here: https://github.com/docker/docker/pull/11710#issuecomment-85611085
@LK4D4

**Comment by reteptilian** [comment]
#dibs

**Comment by rrarunan** [comment]
@reteptilian when you do a PR, can you please add `fixes` or `closes` keyword to it? Thanks!

**Comment by reteptilian** [comment]
Ok sure!

**Comment by reteptilian** [comment]
Hi runcom (or anybody):  

I am a new contributor and have a couple questions:

Do you want me to rip out the RandomString function from the code?  Or just remove all the calls to it but leave the function definition in place?

If we rip it out there won't be any tests left in stringutils_test.go.  Should I just remove that file?  Or, if you like, I could make new tests for GenerateRandomAlphaOnlyString and GenerateRandomAsciiString.

Thanks!

**Comment by runcom** [comment]
@reteptilian yes, rip out `GenerateRandomString` and refactor code accordingly using `stringid.GenerateRandomID`.
Read more here: https://github.com/docker/docker/pull/11710#issuecomment-85611085

Also about the tests, make new tests for `GenerateRandomAlphaOnlyString` and `GenerateRandomAsciiString`

@LK4D4 is it ok?

**Comment by LK4D4** [comment]
@runcom Ok for me. Thanks!
