### ISSUE TITLE
Volume initialize() code invalid 

### ISSUE THREAD

**Issue by crosbymichael** [docker/docker#11725]
**Problem**

The code in https://github.com/docker/docker/blob/master/volumes/volume.go#L93 is incorrect.  It only hits the inner side of the `if` block if the error is not nil and it's an is not exist error.  Any other error type is ignored and the code just goes along.

**Solution**

Fix the logic to only mkdirall when the error is not exist and return the error for any other error type.

**Comment by runcom** [comment]
#dibs
