### ISSUE TITLE
Error 500 on /containers/json with bad values for parameters

### ISSUE THREAD

**Issue by matrixise** [docker/docker#11739]
When I use undefined for before or since, I get this error 500, but normally it has to be a 400 "bad parameter"

```
> 2015/03/25 08:03:46.978712  length=154 from=0 to=153
GET /containers/json?quiet=false&all=false&latest=false&since=undefined&before=undefined&limit=-1 HTTP/1.1\r
User-Agent: hackney/1.0.6\r
Host: localhost\r
\r
< 2015/03/25 08:03:46.980826  length=187 from=0 to=186
HTTP/1.1 500 Internal Server Error\r
Content-Type: text/plain; charset=utf-8\r
Date: Sun, 22 Mar 2015 07:54:17 GMT\r
Content-Length: 51\r
\r
Could not find container with name or id undefined
```

Please, could you check ?

Thank you

**Comment by stresler** [comment]
I can't seem to recreate this issue, that works just fine on my localhost. 

However, looking at the code in that section of the API I do see some backward compatibility blocks. Can you confirm which version of Dockerd you are running when getting these results?

**Comment by matrixise** [comment]
with this version on Ubuntu : 
```
Docker version 1.5.0, build a8a31ef
```
on 
```
root@docker:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty
root@docker:~#
```

**Comment by estesp** [comment]
This is currently working properly on master:
```
$ GET /containers/json -q 'quiet=false&all=false&latest=false&since=undefined&before=undefined&limit=-1'

< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< Date: Sun, 12 Apr 2015 02:46:20 GMT
< Content-Length: 22

no such id: undefined
```
I believe this problem is resolved; any issue with closing this?

**Comment by matrixise** [comment]
do you have the commit ? thanks

**Comment by estesp** [comment]
Most likely this change to the overall flow of `daemon.Get()` from all APIs: 34c804a139cc086e9fa6d3f99442f083b6d5e1e7

The specific file changes that would have affected the HTTP status code is here: https://github.com/docker/docker/commit/34c804a139cc086e9fa6d3f99442f083b6d5e1e7#diff-9320049615863c9b6ab00c749bbb2f09

The server response triggers off the language "no such" in error responses, and the prior test didn't contain the "no such" language, which defaulted an error response to HTTP 500.

**Comment by runcom** [comment]
@matrixise I'm going to close this since it's already solved in master as @estesp pointed out, feel free to comment if you still have problem with this
