### ISSUE TITLE
pull EOF error crashes running instances

### ISSUE THREAD

**Issue by jagan-veeraraghavan** [docker/docker#11746]
`docker version`
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.3.3
Git commit (client): a8a31ef-dirty
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.3.3
Git commit (server): a8a31ef-dirty

`uname -a`
Linux stanza 3.18.6 #2 SMP Sat Feb 28 02:23:04 UTC 2015 x86_64 Intel(R) Xeon(R) CPU E5-2630L v2 @ 2.40GHz GenuineIntel GNU/Linux

`docker info`
Containers: 4
Images: 59
Storage Driver: btrfs
 Build Version: Btrfs v3.17.1
 Library Version: 101
Execution Driver: native-0.2
Kernel Version: 3.18.6
Operating System: CoreOS 607.0.0
CPUs: 1
Total Memory: 494.1 MiB
Name: stanza
ID: MRWF:DKVZ:3C2C:ES4E:LF6D:PNSS:N2PQ:ZVO7:QCJE:7O3O:SAYE:BNF5
Debug mode (server): false
Debug mode (client): true
Fds: 19
Goroutines: 22
EventsListeners: 0
Init SHA1: 30c93967bdc3634b6036e1a76fd547bbe171b264
Init Path: /usr/libexec/docker/dockerinit
Docker Root Dir: /var/lib/docker

`Environment`: Digitalocean CoreOS

Steps to Reproduce:
1. docker pull eboraas/apache-php
2.
3.

Actual Results:
Pulling repository eboraas/apache-php
eeee0dbbfc5b: Pulling image (latest) from eboraas/apache-php, endpoint: https://registry-1.docker.io/v1/ 
FATA[0017] unexpected EOF  

All running docker instances are terminated

Expected Results:
Running instances should not terminate, when pull command fails.

**Comment by cpuguy83** [comment]
Hmmm, are you sure there wasn't a panic or something?

**Comment by LK4D4** [comment]
@cpuguy83 Looks like panic and we had similar before.
ping @stevvooe

**Comment by jagan-veeraraghavan** [comment]
What does panic mean?. I am a docker newbie.

**Comment by cpuguy83** [comment]
It means the docker daemon itself crashed, and likely your init system just restarted it

**Comment by Piste** [comment]
+kind/bug

**Comment by dmp42** [comment]
@jagan-veeraraghavan can you copy your docker daemon logs? (preferably in debug mode)

**Comment by unclejack** [comment]
Is this still a problem for anyone when using the latest Docker version?

**Comment by stevvooe** [comment]
Closing this since the version is extremely old and we have no backtrace to analyze. This part of the code has also changed quite a bit since the 1.5 release, so the same panic bugs aren't likely to be present.

If my evaluation is incorrect, please re-open with a trace.
