### ISSUE TITLE
Documentation: Add reference information on capabilities which can be added/dropped

### ISSUE THREAD

**Issue by estesp** [docker/docker#11752]
Currently the documentation notes that "*In addition to `--privileged`, the operator can have fine grain control over the capabilities using `--cap-add` and `--cap-drop`. By default, Docker has a default list of capabilities that are kept.*" (ref: https://github.com/docker/docker/blame/master/docs/sources/reference/run.md#L632-L636)

However, at that point a few examples are given, but no information is provided on what that list of capabilities are, making it hard for users to search/find what those capabilities and, specifically, their names, are.

The current capabilities list in Docker is here: https://github.com/docker/docker/blob/master/daemon/execdriver/utils.go

They can be mapped to these additional descriptions here: http://linux.die.net/man/7/capabilities

Potentially a table might be a nice way to list this information if we agree that's how we want to display, or if we want an external pointer that may be reasonable as well.  The docs team may have guidance here (ping @SvenDowideit @moxiegirl @fredlf @jamtur01)

**Comment by resouer** [comment]
#dibs We're writing a cap table in a  PR to solve this.

**Comment by rrarunan** [comment]
@resouer Please remember to add this issue also to the `fixes` or `closes` keyword so, this issue can be tracked cleanly. Thanks!
