### ISSUE TITLE
Add documentation on new `--ulimit` and `--default-ulimit` support

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#11754]
Support for setting ulimits for containers was added with #9437, but has a couple of quirks (like `as` ulimit not being supported) and could use some extra docs love.

**Comment by resouer** [comment]
#dibs We're writing a PR to solve this.

**Comment by vdemeester** [comment]
Seems like it sholud be closed (PR merged)

**Comment by md5** [comment]
This doesn't appear to be documented at https://docs.docker.com/reference/run/

Which PR added docs for `--ulimit`?

**Comment by thaJeztah** [comment]
@md5 ulimits are documented in https://github.com/docker/docker/blob/master/docs/reference/commandline/run.md (or https://docs.docker.com/reference/commandline/run/), could probably still use some improvement

**Comment by md5** [comment]
Why on Earth do both https://docs.docker.com/reference/run/ and https://docs.docker.com/reference/commandline/run/ exist? When I search for "docker run", the first of these links is the one that comes up first.

**Comment by thaJeztah** [comment]
@md5 I don't know the history, but I suspect it was created because previously, **all** CLI commands were on a single page, which made it really unwieldy. It's on the list to improve though :+1:

**Comment by thaJeztah** [comment]
(Reference/run should be the more in-depth documentation, but there's quite some detail added to /CommandLine/Run over time)
