### ISSUE TITLE
docker volumes-from is resulting in unstoppable container that can't be docker rm'ed.

### ISSUE THREAD

**Issue by sdake** [docker/docker#11760]
I am developing OpenStack deployed via Docker Containers in a project called Kolla (http://launchpad.net/kolla).

This system uses docker-compose to create docker containers.  After multiple start/stop operations, containers become leaked and both can't be killed or rmed.  The container has actually exited but docker thinks it is still alive.

The containers leaked access data volumes.

To reproduce:
Run through https://github.com/stackforge/kolla/blob/master/docs/developer-env.md
run tools/start
run tools/stop
run tools/start

eventually docker-compose will leak a superpowered container and deadlock on start waiting for the superpowered container to exit.

For debug info see:
https://github.com/docker/compose/issues/812

**Comment by LK4D4** [comment]
This is master-only problem. Seems like there is some race in code.
It is fixed in https://github.com/LK4D4/docker/tree/replace_execdriver but I don't know how exactly.

**Comment by jfrazelle** [comment]
removing from milestone then, phew

**Comment by sdake** [comment]
@jfrazelle 

This not not just a master only problem.  This exists in docker 1.6.0-rc2 distributed by Docker Inc.  It does seem fixed by the execdriver branch, however, that branch introduces an restart:always regression.

http://ur1.ca/k2niz -> http://paste.fedoraproject.org/205557/83143214

See end where the container that uses a data container can't be rm'ed even with -f.
[sdake@minime-02 kolla]$ docker -v
Docker version 1.6.0-rc2, build c5ee149

**Comment by jfrazelle** [comment]
can we come up with an integration test for this?

**Comment by sdake** [comment]
Reliable reproducer

while [ 1 ]; do
    sudo docker-compose -f mariadb.yml up -d
    sleep 8
    sudo docker-compose -f mariadb.yml stop
done

get mariadb.yml from here:
https://github.com/stackforge/kolla/blob/master/compose/mariadb.yml

Note this seems to cause failure on stop which is a bit different then the bug report indicates (where recreate of compose fails because docker goes out to lunch on the container).  docker-compose stop has a timeout, docker-compose start does not, so if start deadlocks, you will see the original behavior of this test case.

Logs:
stop failure shell:
http://paste.fedoraproject.org/205610/37135142
daemon shell:
http://paste.fedoraproject.org/205609/83712914

@cpuguy83 indicated he was using a smaller image and it took him ~50 iterations.  It takes about 3-6 iterations with these larger images.

**Comment by jfrazelle** [comment]
awesome thanks so much!

**Comment by jfrazelle** [comment]
how long does it take to reproduce im trying on my bump_v1.6.0 branch now and not seeing it

**Comment by jfrazelle** [comment]
the while loop has been successfully ran 20+ times

**Comment by jfrazelle** [comment]
it's still going and I havent seen anything... I was also using the docker-compose rc2

**Comment by sdake** [comment]
It took 50 tries for @cpuguy83 to reproduce.  I am using 1.6.0-rc2 built by Docker, Inc.  It takes me about 3-5 tries on Fedora 21.  @lk4d4 mentioned he merged some bug fixes in rc3 which (could have possibly fixed it?)  If you can provide me a binary of your version, I'll test on my machine and see if its machine dependent or fixed in your version.

I am compile-docker impaired :)

**Comment by cpuguy83** [comment]
I have not repro'd

**Comment by sdake** [comment]
@cpuguy83 oh I thought you indicated you were able to reproduce it.  My apologies.

**Comment by jfrazelle** [comment]
I will give you a binary :D

**Comment by jfrazelle** [comment]
http://jesss.s3.amazonaws.com/docker/1.6.0-rc2bump/docker-1.6.0-rc2

**Comment by sdake** [comment]
@jfrazelle the version you provided does not reproduce with my reproducer above with 1 hour of runtime looping.  I'm trying out the full kolla stack now to see if that version also works.  Will report back.

**Comment by sdake** [comment]
@jfrazelle the version you provided works great with Kolla master.  It stops and starts in a cycle without any of the problems I've seen in the past.  Thanks for all the great work on fixing these race bugs folks!

**Comment by jfrazelle** [comment]
yay! so good to hear :)
