### ISSUE TITLE
No way to limit memory for docker build

### ISSUE THREAD

**Issue by jamesyli** [docker/docker#11767]
docker run has a --memory option, but build has not.

If I have an instruction of "RUN foo" in my Dockerfile, it looks docker spins up an intermediate container to run the 'foo' script. But there is no way to limit memory (or ulimit resources in general) for the intermediate container.

**Comment by cpuguy83** [comment]
Closing since this does exist on master and will be included in 1.6, along with all the other cgroup options.

Also ulimits, though ulimits would have to be set at the daemon level for defaults (as opposed to `docker run` which you can customize the ulimits).

**Comment by jamesyli** [comment]
@cpuguy83 thanks, look forward to 1.6! 
Is that documented anywhere?

**Comment by cpuguy83** [comment]
Yes, it's in the master docs (which are all under /docs in the repo)

**Comment by thaJeztah** [comment]
They can also be viewed at http://docs.master.dockerproject.com
