### ISSUE TITLE
/etc/hosts contains Docker-assigned IP address even with --net='none'

### ISSUE THREAD

**Issue by jbemmel** [docker/docker#11765]
When I run a Docker container using --net='none' ( to use my own network plumbing ), /etc/hosts of the container looks something like this:

root@hostname:/# cat /etc/hosts
172.17.0.167	hostname
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters

The '172.17.0.167' IP address is invalid in this context, "127.0.1.1" would be a better value to use

**Comment by LK4D4** [comment]
@jbemmel What version of docker do you use and how you run your container? On my machine:
```
docker run --net=none busybox cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

**Comment by hughdbrown** [comment]
I can replicate this with docker 1.5.1

    % docker run -ti ubuntu /bin/bash                         
    root@a1a55eefd19f:/# cat /etc/hosts
    172.17.0.2	a1a55eefd19f
    127.0.0.1	localhost
    ::1	localhost ip6-localhost ip6-loopback
    fe00::0	ip6-localnet
    ff00::0	ip6-mcastprefix
    ff02::1	ip6-allnodes
    ff02::2	ip6-allrouters
    root@a1a55eefd19f:/# 
    
    % docker --version 
    Docker version 1.5.0, build a8a31ef
    
    % uname -a
    Linux hughdbrown-XPS-15-9530 3.18.7-031807-generic #201502110759 SMP Wed Feb 11 08:01:01 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by coolljt0725** [comment]
@hughdbrown  In your case, it is a desired behavior because you use `--net=bridge` by default. I think the issue is that when use `--net=none`, `/etc/hosts` still contains Docker-assigned IP address. Can you reproduce by useing `--net=none`?

**Comment by hughdbrown** [comment]
@coolljt0725 I think you saw my report before I noticed that I had omitted `--net=none`. I updated before you posted, and yes I have confirmed it does not do that with `--net=none` and `--net='none'`.

**Comment by jbemmel** [comment]
root@c4h4:~# docker --version
Docker version 1.0.1, build 990021a
root@c4h4:~# docker run -it --net=none ubuntu /bin/bash
root@08b1a5f06b4f:/# cat /etc/hosts
172.17.0.168 08b1a5f06b4f
127.0.0.1 localhost
::1 localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

This is on Ubuntu 14.04, I installed the standard docker.io package

**Comment by LK4D4** [comment]
@jbemmel Seems like there was bug in 1.0.1 and now it's fixed. Pls, update your docker. I think that docker.io package is not supported. Here instructions for installation https://docs.docker.com/installation/ubuntulinux/#installing-docker-on-ubuntu
