### ISSUE TITLE
docker stats all

### ISSUE THREAD

**Issue by SamSaffron** [docker/docker#11763]
There needs to be a cleaner way to get docker stats for all running containers from the cli. 

```
docker stats `docker ps | awk '{print $NF}' | grep -v NAMES`
```

is just way too much to type. 

simplest is to just have `docker stats` provide stats for all running containers instead of usage

**Comment by programmerq** [comment]
+kind/feature

**Comment by Sirupsen** [comment]
Already reported in https://github.com/docker/docker/issues/10772
