### ISSUE TITLE
Update contributor guide with Windows-specific instructions

### ISSUE THREAD

**Issue by xamyzhao** [docker/docker#11780]
"Configure Git for contributing" section does not mention where to configure git in Windows.

**Comment by xamyzhao** [comment]
+writing +beginner

**Comment by xamyzhao** [comment]
#dibs

**Comment by xamyzhao** [comment]
+exp/beginner +kind/writing

**Comment by moxiegirl** [comment]
@xamyzhao Huge thank you.

**Comment by spf13** [comment]
Contributed in PR #11781
