### ISSUE TITLE
Update hack/make.sh output to reference a bundle named "binary" instead of "ubuntu" in the Contributor Guide

### ISSUE THREAD

**Issue by amylindburg** [docker/docker#11785]
On the [Work with a development container] (http://docs.docker.com/project/set-up-dev-env/) page (from the Contributor Guide), the output from running `hack/make.sh binary` needs to be updated to reference `binary` instead of `ubuntu`. 

Currently, the output is:

```
---> Making bundle: ubuntu (in bundles/1.5.0-dev/ubuntu)
Created package {:path=>"lxc-docker-1.5.0-dev_1.5.0~dev~git20150223.181106.0.1ab0d23_amd64.deb"}
Created package {:path=>"lxc-docker_1.5.0~dev~git20150223.181106.0.1ab0d23_amd64.deb"}
```

Rather, it should be something akin to:

```
---> Making bundle: binary (in bundles/1.5.0-dev/binary)
Created binary: /go/src/github.com/docker/docker/bundles/1.5.0-dev/binary/docker-1.5.0-dev
```

**Comment by programmerq** [comment]
+kind/writing

**Comment by voltaic** [comment]
#dibs

**Comment by rrarunan** [comment]
Closing issue, since #11846 fixes this and has been merged.

**Comment by vdemeester** [comment]
Yep, this one should be closed too :wink:
