### ISSUE TITLE
Typo in instructions to cd to root of repo

### ISSUE THREAD

**Issue by amylindburg** [docker/docker#11792]
In the [Run tests and test documentation ](http://docs.docker.com/project/test-and-docs/) in the Contribution Guide -- in the **Build and test the documentation** section, Step 1:

Changing to the root of your `docker-fork` repo is instructed as:

`$ cd ~/repos/dry-run-test`

Rather, it should be:

`$ cd ~/repos/docker-fork`

**Comment by amylindburg** [comment]
#dibs

**Comment by rrarunan** [comment]
@amylindburg when you do a PR, can you please add the `fixes` or `closes` keyword to it? Thanks!
