### ISSUE TITLE
In Contributor Guide, fetch instruction produces error

### ISSUE THREAD

**Issue by amylindburg** [docker/docker#11796]
In the Contributor Guide on the [Find and claim an issue](http://docs.docker.com/project/find-an-issue/) page, Step 5, you are instructed to fetch all the changes from the `upstream/master` branch:

`$ git fetch upstream/master`

This produces an error: `fatal: 'upstream/master' does not appear to be a git repository`

Rather, you should be fetching from the upstream remote:

`$ git fetch upstream`

This works!

```
remote: Counting objects: 1388, done.
remote: Compressing objects: 100% (512/512), done.
remote: Total 1388 (delta 486), reused 209 (delta 209), pack-reused 667
Receiving objects: 100% (1388/1388), 1.12 MiB | 872.00 KiB/s, done.
Resolving deltas: 100% (679/679), done.
```

**Comment by RickWieman** [comment]
Hmm, it might be confusing, but the right instruction is already there:

> Fetch all the changes from the `upstream/master` branch.
> ```
$ git fetch upstream
...
```

**Comment by kytrinyx** [comment]
#dibs

`upstream/master` is the local copy of the upstream master branch, `upstream master` refers to the `master` branch on the remote `upstream` repository.

There's some confusion about this in the docs, I'll take a stab at clarifying.

**Comment by kytrinyx** [comment]
oops, race condition :)
