### ISSUE TITLE
Error: Command not found: create

### ISSUE THREAD

**Issue by krmaxwell** [docker/docker#11797]
I'm trying to learn how to persist data from a container (the application is a web scraper I've written). When I follow the [instructions in the user guide](https://docs.docker.com/userguide/dockervolumes/#creating-and-mounting-a-data-volume-container), docker gives me an error message:

```
$ sudo docker create -v /archive --name archive maltrieve
Error: Command not found: create
Error: Command not found: -v
Usage: docker [OPTIONS] COMMAND [arg...]
 -H=[unix:///var/run/docker.sock]: tcp://host:port to bind/connect to or unix://path/to/socket to use
```

This system runs Ubuntu 14.04 LTS.
```
$ sudo docker version
Client version: 1.0.1
Client API version: 1.12
Go version (client): go1.2.1
Git commit (client): 990021a
Server version: 1.0.1
Server API version: 1.12
Go version (server): go1.2.1
Git commit (server): 990021a
```

**Comment by Mongey** [comment]
Looks like you are using an older version of docker; v1.0.1. The `create` command was added in docker [v1.3.0.](https://github.com/docker/docker/blob/master/CHANGELOG.md#130-2014-10-14)

You can find instructions [here](https://github.com/docker/docker/issues/9697#issuecomment-67232206) to upgrade your version of docker to the latest version.

**Comment by krmaxwell** [comment]
Thanks, that worked great!
