### ISSUE TITLE
sometimes docker container doesn't be exit status, but the proccess of container is killed.

### ISSUE THREAD

**Issue by cc272309126** [docker/docker#11809]
Hi
I have found that sometimes  container doesn't be exit status, when the entry proccess of container is killed.
I can reproduce by next steps, not every times.
1. git clone docker.git from github.
2. make binary
3. ctrl+c when some steps in make binary.
4. docker ps, some container is still be seen.
5. use docker inspect xxx to gain the Pid.
6. ps -elf | grep Pid, we will found that the pid is killed.

some logs,it is picure.
![test](https://cloud.githubusercontent.com/assets/1488006/6844927/7097284e-d3ea-11e4-88c3-25819b3e7854.png)

**Comment by cpuguy83** [comment]
This is most likely because you exited out of a running build.
Up until recently you could not actually cancel a build, so the build would continue on in the background, creating/removing more containers.

Closing.
If you can provide a repro case we can re-visit.
Thanks!
