### ISSUE TITLE
Use a top default registry when pushing unqualified repository

### ISSUE THREAD

**Issue by miminar** [docker/docker#11817]
This is based on issues #11815 and #11816.

### Use case
As an enterprise user interacting with multiple private registries with little or no need for a public registry, I'd like to be able to push unqualified repository to one of my private registries.

So when I execute:

    $ docker push precious/app

it will be pushed to my default registry specified in configuration.

### Requirements
- Allow to specify a default registry used for push of any unqualified repository.

### Proposal
Use the first item in the list of default registries as a receiver of unqualified repositories during push command.

**Comment by dmp42** [comment]
Closing for the same reason as #11816 
Having that ability will definitely happen, but we need image signing first to guarantee this will not let ISV fragment the image namespace.
