### ISSUE TITLE
Allow user to block particular registries for certain operations

### ISSUE THREAD

**Issue by miminar** [docker/docker#11819]
This is an extension of issue #11815.

### Use Case
As an enterprise administrator, I'd like be able to tell Docker daemon to block particular registries. Public registries in particular. Since our company builds mostly images for private use, I'd like to prevent our developers from accidentally pushing images to public registries.

### Requirements
- Docker daemon recognizes a list of registries blocked for pushes.
- Docker daemon can be given a list of registries blocked for pulls.
- Docker daemon actually blocks access to specified registries.
- User is informed that his operation failed due to registry being blocked.

### Proposal
Using a configuration schema from #11815. Let's extend it with a new registry property:

- `policy` with possible values:

 1. one of following strings:  `allow`, `ask`, `block`
 2. a map for fine-grained specicication with possible keyes: `push`, `pull`,
    `search` having the same choices (`allow`, `ask`, `block`)

Default value would be `allow`.

`ask` would make Docker client ask the user for a confirmation before an execution. I don't find it necessery to ask before a pull or search it should be recognized only by a push operation. In other cases it would map to `allow`. Affected commands (push) shall receive additional flag `-f --force` that would suppress the confirmation.

#### Examples

Ask for a confirmation when pushing to public registry, allow everything else:

    public:
        policy:
            push: ask

    redhat:
        index: registry.access.stage.redhat.com

Same as above:

    public:
        policy: ask

    redhat:
        index: registry.access.stage.redhat.com

Block public registry completely:

    public:
        policy: block

    redhat:
        index: registry.access.stage.redhat.com

Block all not configured registries (but allow for searching):

    defaults:
        policy:
            push: block
            pull: block

    private:
        policy: allow
        index: my.private.registry.ltd

    redhat:
        policy: allow
        index: registry.access.stage.redhat.com

Try to push to a public registry with `ask` policy:

    $ docker push docker.io/user/app
    Do you really want to push to docker.io registry? [Y/n]: Y
    ...

**Comment by dmp42** [comment]
Same comments as for the other issues.

**Comment by pbc** [comment]
@miminar have you got any temporary solution to this problem for Linux and / or Mac OSX users ?

**Comment by cpuguy83** [comment]
@pbc Seems simple enough with the right firewall rules.

**Comment by pbc** [comment]
@cpuguy83 I am looking for something that would support both linux and mac osx , and be relatively simple to do by a junior dev.

my first thought was to ask them to modify /etc/hosts and block few most common registries but the problem is that I would like to allow them to pull any images they need but prevent them from accidental pushing.

my second thought was to look into firewall setups but firewalls on mac an linux differ and I would need to script this for them

third approach would be to ask them to install the same firewall on both systems because on mac osx the default firewall is disabled so it wouldn't collide with anything

fourth approach would be to modify something related to docker tools and this way get the desired result but my knowledge of this ecosystem is not deep enough yet so I don't quite know what to tweak and where.

if anyone with more docker experience than me (only 2 weeks) has any suggestions then I am all ears

**Comment by cpuguy83** [comment]
@pbc There would be no reason to support OSX, the daemon pushes/pulls, not the client. Daemon only runs on Linux.

**Comment by pbc** [comment]
@cpuguy83 ok, that simplifies things. I will go with the second approach then. thank you.

**Comment by LK4D4** [comment]
I think this is task for firewall, indeed.

**Comment by jsengla** [comment]
The firewall is NOT a suitable place to implement this feature request, and I believe this ticket should be re-opened.
Please reconsider.  Read the request again slowly if necessary, so you can see how your answer does not indeed provide the solution required and in fact will (a) sever community involvement with hard restrictions and/or (b) puts the onus on networking admins to follow a moving target of an API to block access with no user-visible message related to their actual 'error'.

Also, look at Red Hat's '--block-registry' flag.  It can be done, it has been done, the PRs have been sent, and Docker's refusal to implement it has resulted in the project being substantially forked, and is a primary reason throughout enterprise why their fork (which also prioritizes their registry above Docker Hub) is chosen.  That's pretty terrible for the community.  

People (enterprise corporations and government entities) have been begging for the capabilities offered by Red Hat's '--add-registry' and '--block-registry' for years.  Neither DNS spoofing nor firewall lockdowns suffice as a solution.  Isn't it about time you stop summarily rejecting everyone begging for these features?  It's your hard-coded default registry that most needs to be blocked - and preferably in a way that makes it still an option to override that block (to interact/pull/push/contribute with the community) at various levels of OS/institutional/environmental access privileges.  Ignoring a real need while requiring that we take drastic steps like this is how you invoke drastic and lasting damage on the community.  Please stop.

**Comment by valdiz777** [comment]
The real truth that is missing here is that docker, Inc want to vendor lock users to the docker central hub or one of there private clouds.

**Comment by justinbarrick** [comment]
I *urge* you to stop ignoring the community on this issue. This is a major need for any enterprise or corporation.

You can't use a firewall to solve this issue without blocking the entire internet and whitelisting only your registry, but this does not work, if, for example my containers are using host networking.

Even if it were true that a firewall is the right place for this, defense in depth is important and a firewall is not sufficient to provide this.

**Comment by ahharu** [comment]
This is a bummer

**Comment by cpuguy83** [comment]
Docker supports authorization plugins which is well suited to handle this case.
There is even a generic authz plugin for Open Policy Agent: https://github.com/open-policy-agent/opa-docker-authz

**Comment by christophermclellan** [comment]
Hello - I realise this is an incredibly belated message given this thread was created ~7 years ago ! Are there any Docker Business customers here that would be interested to try out our upcoming Registry Access Mgmt feature (currently in closed beta), which I believe fits the use cases set out in the original post. 

Thanks,

Chris

**Comment by jakobkolb** [comment]
I am currently setting up a CI/CD environment for a government agency and am looking for a way to achieve exactly this: Restricting users to pull images from one internal registry while being able to pull other packages from other sources. While the Registry Access Mgmt feature is interesting for us for users dev environments, it does not help us to secure CI/CD where docker is used via the cli. Since this has been an issue for a long time, I am curious to know whether people have found good workarounds or if they just ditched docker and used e.g. OpenShift
