### ISSUE TITLE
Add `--cgroup-parent` option to `docker build`

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#11822]
The `--cgroup-parent` was recently added to `docker run` and `docker create`, would be great to have this available in `docker build` as well.

**Comment by ctiwald** [comment]
#dibs

**Comment by jbarbier** [comment]
Hey @ctiwald I am on it. It's done. Sry I did not comment before.

**Comment by ctiwald** [comment]
No worries.

**Comment by jbarbier** [comment]
Hey @ctiwald Do you think you can help me with tests on this? Never done it before. 
https://github.com/docker/docker/pull/11844

**Comment by duglin** [comment]
@jbarbier Look at integration-cli/docker_cli_build_test.go, in particular TestBuildResourceConstraintsAreUsed() - that is probably a good example to follow or modify.
