### ISSUE TITLE
Support authentication to additional registries

### ISSUE THREAD

**Issue by miminar** [docker/docker#11820]
Extends and complements issues #11815, #11816 and #11817.

### Use Case
As an enterprise user interacting with multiple private registries, I'd like to be able to authenticate against them when I do a pull or a search against them. It works as expected when I pull fully qualified repository name. However, it is impossible to do when pulling unqualified image.

#### Example
Suppose Docker daemon is configured with one additional private secured registry `registry.my.org` hosting at least `custom/app` repository.

    $ cat registries.yml:
    my:
        index: registry.my.org

Then issuing following pull.

    $ docker pull registry.my.org/custom/app

Will ask user for a username/password and will pull the app if correct. However

    $ docker pull another/app
    
Fails unless `another/app` is in public registry. The reasons is that it's the client who stores given credentials and sends them to daemon when working with particular registry. In this case, however, client does not know, which registry will be contacted.

### Requirements
- Docker daemon can authenticate against any additional registry during `pull`, `search` and `push` commands.
- Allow to cache credentials in Docker daemon - at least in memory.

### Proposal
Make daemon return index name of currently queried registry together with 401 HTTP status code. Add a parameter `continueWith` to `POST /images/create` query accepting an index name from a list of default registries. Make daemon continue to query default registries starting with the one specified in `continueWith`.

Additionally allow Docker daemon to cache credentials. Extend the configuration schema with a new registry boolean property `cache_credentials` defaulting to `false`. Keep credentails only in memory for now. Persistent storage could be a subject of another proposal.

#### Example

    public:
        policy: ask

    internal:
        cache_credentials: true

**Comment by programmerq** [comment]
+kind/proposal

**Comment by dmp42** [comment]
Closing for the same reason pointed out earlier.

In a shell: the ability to override the meaning of an unqualified name can not happen without trust.

Furthermore, we already support authentication to fully qualified registries, so, this issue is really about saving keystrokes and not about adding an actual feature / value to the user.
