### ISSUE TITLE
api/client/stats.go: Replace fmt.Fprint* with io.WriteString

### ISSUE THREAD

**Issue by LK4D4** [docker/docker#11825]
in `printHeader` closure. Don't forget to add `\n` where `Fprintln` was used.
This will fix vet warning about format string and also seems like right thing here.

**Comment by ankushagarwal** [comment]
#dibs

**Comment by ankushagarwal** [comment]
@LK4D4 : How can I reproduce this warning?

**Comment by LK4D4** [comment]
@ankushagarwal:
go vet $(go list ./... | grep -v vendor)

**Comment by LK4D4** [comment]
@ankushagarwal What status here?

**Comment by rrarunan** [comment]
@ankushagarwal When you do a PR, can you please add `fixes` or `closes` keyword to it? Thanks!

**Comment by ankushagarwal** [comment]
@rrarunan  Sure
@LK4D4  Will submit a PR in the next 6 hours.
