### ISSUE TITLE
Fix vet warning in devicemapper

### ISSUE THREAD

**Issue by LK4D4** [docker/docker#11828]
Warning is:
```
pkg/devicemapper/devmapper_wrapper.go:234: possible misuse of unsafe.Pointer
```
Idea is to replace `uintptr` in whole call chain with `unsafe.Pointer` and then in `GetStatus` in `pkg/devicemapper/devmapper.go` replace `task.GetNextTarget(0)` with `
task.GetNextTarget(unsafe.Pointer(nil))`.

**Comment by NinjaTrappeur** [comment]
#dibs

**Comment by LK4D4** [comment]
@NinjaTrappeur What status here?

**Comment by NinjaTrappeur** [comment]
I made the modifications in the code, since it is my first contribution and I am a Go rookie, I am reading more about docker's testing environment. I'll tell you more in 1 or 2 hours :)

**Comment by rrarunan** [comment]
@NinjaTrappeur when you do a PR, can you please add `fixes` or `closes` keyword to it? Thanks!
