### ISSUE TITLE
Proposal: chance of defining a link as "name" instead of "name:alias" when name and alias are the same

### ISSUE THREAD

**Issue by adrianhurt** [docker/docker#11824]
I've seen it's already supported in Docker Compose ([here](https://docs.docker.com/compose/yml/#links)). I think it's more simple and readable.

Example:
```
link: ["mysql", "elasticsearch"]
```
instead of
```
link: ["mysql:mysql", "elasticsearch:elasticsearch"]
```

**Comment by adrianhurt** [comment]
Sorry, I wanted to say:
```
--link mysql --link elasticsearch
```
instead of
```
--link mysql:mysql --link elasticsearch:elasticsearch
```

**Comment by Piste** [comment]
+kind/enhancement

**Comment by runcom** [comment]
I like this, personally I find very annoying not deducing the link doesn't have an alias if it's not in name:alias form, at least in the cli (api's another matter), let's just hear from others if this is something Docker wants/needs

**Comment by duglin** [comment]
Seems like a nice usability thing

**Comment by runcom** [comment]
@duglin yup but I've come across this comment https://github.com/michaelsauter/crane/pull/169#issuecomment-86264726 that made me think this would be an issue. Honestly I think what said in that comment would not happen anytime soon and we don't have to worry about that, if we really want to change that syntax there are far more place to be worried about

**Comment by duglin** [comment]
@runcom if in the future --link changes so that it doesn't mean what it does today then I would think a new --flag should be defined for that instead. 

Are you asking if we should change both the CLI and API?  I like consistency, so unless we can think of a reason why the API shouldn't support this I'm inclined to think we should change it there too.

**Comment by runcom** [comment]
Just asking I like consistency too and totally agree with you, thought maybe someone thinks api could be left with that format for some weird reason (like some people doesn't even know docker as api and see it like a pro-user feature to use and won't bother in term of usability)

**Comment by adrianhurt** [comment]
I think it's very logical and easy to implement.

@runcom, I understand the opinion that is said in that comment for crane situation, because it depends on Docker's cli. But here, that you decide the future of Docker, and assuming that in Docker Compose it's already supported, I suppose there shouldn't be a problem.

**Comment by runcom** [comment]
alright, I'm gonna make the pull request then and see there if it will be ok

**Comment by adrianhurt** [comment]
Thanks!
