### ISSUE TITLE
Improve output in docker ps for containers with a lot of port bindings

### ISSUE THREAD

**Issue by awsmsrc** [docker/docker#11833]
A container with a lot of port bindings ruins the output of docker ps

The two possible solutions are to show ranges in a more succinct manner or change the output formatting so one row doesnt affect the others

Or truncate the output

This has potential issues/side affects for people who are parsing this output

thoughts?

![screen shot 2015-03-26 at 12 30 43 pm](https://cloud.githubusercontent.com/assets/994907/6855306/462dda7a-d3b4-11e4-95ab-f02106ef5b70.png)

**Comment by programmerq** [comment]
This issue was addressed in this PR: https://github.com/docker/docker/pull/10339

**Comment by awsmsrc** [comment]
ok cool, any idea when that will be getting released?
