### ISSUE TITLE
Report: Docker + VirtualBox causes CPU stalls

### ISSUE THREAD

**Issue by mbentley** [docker/docker#11838]
Description of problem:  Unable to run a docker container and a VirtualBox VM at the same time on Debian Wheezy or Jessie

My initial guess would be that this is a VirtualBox bug but I can't yet rule out that it isn't something with Docker either.

`docker version`:
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

`docker info`:
Containers: 1
Images: 3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 5
Execution Driver: native-0.2
Kernel Version: 3.16.0-0.bpo.4-amd64
Operating System: Debian GNU/Linux 7 (wheezy)
CPUs: 4
Total Memory: 3.784 GiB
Name: lilith
ID: QYHD:WQSW:RQAV:AZWV:XWRF:HQJ6:QR6O:GY35:SYKC:P23H:P7R6:O4X7
Debug mode (server): false
Debug mode (client): true
Fds: 11
Goroutines: 14
EventsListeners: 0
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker

`uname -a`:
Linux lilith 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt4-3~bpo70+1 (2015-02-12) x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):  Reproduced on laptop and desktop

VirtualBox Version (from the Oracle apt repo)
```
# VBoxHeadless --version
Oracle VM VirtualBox Headless Interface 4.3.26
(C) 2008-2015 Oracle Corporation
All rights reserved.

4.3.26r98988
```

How reproducible:  Run a docker container and then start a VirtualBox VM (has to be this order; can't have another VirtualBox VM already running before running first docker container)

Steps to Reproduce:
1. Perform a base debian wheezy install from a netinst ISO
2. Install the latest `linux-image-amd64` package from wheezy backports (3.16.63); this is also reproducible using kernel version 3.2.0
3. Install VirtualBox using the Oracle apt repo
4. Install docker:
	`curl -sSL https://get.docker.com | sh`
5. Run any docker container:
	`docker run -d debian:jessie sleep infinity`
6. Start a VirtualBox VM:
	`VBoxManage startvm testbox --type headless`
7. System locks up; only happens when a docker container is running first and not the other way around
```
INFO: rcu_sched self-detected stall on CPU { 1}  (t=5250 jiffies g=3017 c=3016 q=803)
BUG: soft lockup - CPU#1 stuck for 22s! [sshd:3743]
BUG: soft lockup - CPU#2 stuck for 22s! [irq/55-iwlwifi:680]
BUG: soft lockup - CPU#3 stuck for 22s! [kworker/3:0:4116]

BUG: soft lockup - CPU#1 stuck for 22s! [sshd:3743]
BUG: soft lockup - CPU#2 stuck for 22s! [irq/55-iwlwifi:680]
BUG: soft lockup - CPU#3 stuck for 22s! [kworker/3:0:4116]
```

Actual Results:  CPU stalls lock up the system; has to hard reboot to get it back to a working state

Expected Results:  Docker container and VirtualBox VM work together as expected

Additional info:  I've been able to reproduce this on a few other machines as well and is reproducible reliably if further info is needed for debugging.

```
info: reading kernel config from /boot/config-3.16.0-0.bpo.4-amd64 ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MACVLAN: enabled
- CONFIG_VETH: enabled
- CONFIG_BRIDGE: enabled
- CONFIG_NF_NAT_IPV4: enabled
- CONFIG_IP_NF_FILTER: enabled
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled
- CONFIG_NF_NAT: enabled
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_MEMCG_SWAP: enabled
- CONFIG_RESOURCE_COUNTERS: enabled
- CONFIG_CGROUP_PERF: enabled
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: enabled
    - CONFIG_EXT4_FS_POSIX_ACL: enabled
    - CONFIG_EXT4_FS_SECURITY: enabled
  - "btrfs":
    - CONFIG_BTRFS_FS: enabled
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: enabled
    - CONFIG_DM_THIN_PROVISIONING: enabled
    - CONFIG_EXT4_FS: enabled
    - CONFIG_EXT4_FS_POSIX_ACL: enabled
    - CONFIG_EXT4_FS_SECURITY: enabled
  - "overlay":
    - CONFIG_OVERLAY_FS: missing
    - CONFIG_EXT4_FS_SECURITY: enabled
    - CONFIG_EXT4_FS_POSIX_ACL: enabledinfo: reading kernel config from /boot/config-3.16.0-0.bpo.4-amd64 ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MACVLAN: enabled
- CONFIG_VETH: enabled
- CONFIG_BRIDGE: enabled
- CONFIG_NF_NAT_IPV4: enabled
- CONFIG_IP_NF_FILTER: enabled
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled
- CONFIG_NF_NAT: enabled
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_MEMCG_SWAP: enabled
- CONFIG_RESOURCE_COUNTERS: enabled
- CONFIG_CGROUP_PERF: enabled
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: enabled
    - CONFIG_EXT4_FS_POSIX_ACL: enabled
    - CONFIG_EXT4_FS_SECURITY: enabled
  - "btrfs":
    - CONFIG_BTRFS_FS: enabled
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: enabled
    - CONFIG_DM_THIN_PROVISIONING: enabled
    - CONFIG_EXT4_FS: enabled
    - CONFIG_EXT4_FS_POSIX_ACL: enabled
    - CONFIG_EXT4_FS_SECURITY: enabled
  - "overlay":
    - CONFIG_OVERLAY_FS: missing
    - CONFIG_EXT4_FS_SECURITY: enabled
    - CONFIG_EXT4_FS_POSIX_ACL: enabled
```

**Comment by ituaijagbone** [comment]
+exp/beginner
+kind/usercase

**Comment by mbentley** [comment]
I've updated the above information with the appropriate version information of VirtualBox as I am sure that would be helpful.  I'm installing VirtualBox from the Oracle apt repos.

**Comment by jfrazelle** [comment]
whats your bios config look like

**Comment by jfrazelle** [comment]
pretty sure this might be a dup of https://github.com/docker/docker/issues/10031

**Comment by mbentley** [comment]
All virtualization extensions are enabled; and yes it most definitely does look to be a duplicate of #10031

**Comment by jfrazelle** [comment]
so im going to close this one then so we dont fragment the convo
