### ISSUE TITLE
Explain how to generate man pages for Mac OSX

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#11835]
Or docker/docs/README.md should include information for how to get the Man pages in Mac OSX.

http://stackoverflow.com/questions/26368263/how-to-install-docker-man-pages-on-mac-os

**Comment by miwest929** [comment]
#dibs

**Comment by rrarunan** [comment]
@miwest929 when you do a PR, can you please add `fixes` or `closes` keyword to it? Thanks!

**Comment by miwest929** [comment]
@rrarunan Will do. I'm hoping to have that PR out by tomorrow.

**Comment by miwest929** [comment]
PR out: https://github.com/docker/docker/pull/11880
