### ISSUE TITLE
Misleading error message when client and server API version mismatch

### ISSUE THREAD

**Issue by 3rwww1** [docker/docker#11836]
For instance:    
    erwan@laptop:~/Projects/docker/machine$ script/build
    FATA[0000] Error: client and server don't have same version (client : 1.18, server: 1.17)
    erwan@laptop:~/Projects/docker/machine$ docker --version
    Docker version 1.5.0-dev, build 6a43d71

This message is a bit misleading. The missing keyword here seems to be "API version" :)

**Comment by lobatt** [comment]
+exp/beginner

**Comment by lobatt** [comment]
#dibs
