### ISSUE TITLE
Adding a new IP to a present interface destroys the networking of containers.

### ISSUE THREAD

**Issue by AlessandroEmm** [docker/docker#11837]
Hey there

I currently run into the problem that as soon as I add another IP Address to my present physical interface (where all my containers bind to) I cannot connect to any docker mapped port anymore. It seems to kill the NAT halfway because even locally initiated connections to the containers IP do get timeouts or answers with a lot of delay remote connections from other hosts stop working all together.

To illustrate my situation a bit more:

I'd like to add another IP to this interface:

2: mgm0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:21:5e:c8:ce:98 brd ff:ff:ff:ff:ff:ff
    inet 172.20.1.253/16 brd 172.20.255.255 scope global mgm0
       valid_lft forever preferred_lft forever

Through the cmd

ip addr add 172.20.1.250/16 dev mgm0

as soon as I issue this command all the docker containers that we're bound to mgm0 are not reachable anymore although the NAT rules look alright, still:

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  172.17.0.0/16        0.0.0.0/0           
MASQUERADE  tcp  --  172.17.0.2           172.17.0.2           tcp dpt:3306

Chain DOCKER (2 references)
target     prot opt source               destination         
DNAT       tcp  --  0.0.0.0/0            127.0.0.1            tcp dpt:3306 to:172.17.0.2:3306
DNAT       tcp  --  0.0.0.0/0            172.20.1.253         tcp dpt:3306 to:172.17.0.2:3306
DNAT       tcp  --  0.0.0.0/0            172.20.1.250         tcp dpt:3306 to:172.17.0.2:3306

Am I running into a limitation or am I just doing it wrong?

Thanks! 
Alessandro

**Comment by LK4D4** [comment]
@AlessandroEmm Thanks for report. I think I encountered such thing too.

**Comment by ituaijagbone** [comment]
+exp/beginner
+kind/question

**Comment by discordianfish** [comment]
I don't think that exp/beginner nor kind/question are the correct tags for this.

**Comment by discordianfish** [comment]
@AlessandroEmm Just tried to reproduce but couldn't:

```
$ docker run -p 2342:2342 ubuntu python3 -m http.server 2342
$ curl localhost:2342 # works
$ ip addr add 1.2.3.4 dev wlan0 # my only physical interface
$ curl localhost:2342 # still works
```

Same results when adding an IP to docker0.
Could you provide some more details on your setup? Preferably assume a system with just let say eth0 configured and describe the steps you took to configure your network (create bridges etc).

**Comment by AlessandroEmm** [comment]
@discordianfish 

I've been binding the docker containers port to the first IP of wlan0 in your example and not localhost.

While i run into this problem on the physical servers I currently fail to reproduce it on my local boot2docker instance. :-1:

**Comment by AlessandroEmm** [comment]
Its also weird that i can't access the outside world anymore from inside the docker container. The only thing still working is the ping to the host. Am I missing some masquerading rule or something?

**Comment by discordianfish** [comment]
This sounds familiar, we had some issues with containers not able to talk to the outside on systems where we add/remove IPs from the interface.
@icecrime: This is a really severe issue for us, can you look into (escalating) this?

**Comment by discordianfish** [comment]
@avinson You did some testing of our haproxy container back then, right? Did you see any similar issues? The symptoms sound familiar..

**Comment by dave-tucker** [comment]
@AlessandroEmm 
> I currently run into the problem that as soon as I add another IP Address to my present physical interface (where all my containers bind to) I cannot connect to any docker mapped port anymore.

Are you running the daemon with `--ip YOUR_ADDRESS_HERE` or is it defaulting to `0.0.0.0`
This can be verified with `docker ps`:

```
PORTS                                 
0.0.0.0:8080->80/tcp
```
I've been unsuccessful trying to replicate with boot2docker, I'll try a VM with a single external interface next. 

@discordianfish re: containers not being able to talk to outside systems, which interface were you adding/removing IP's from? Have you had any luck trying to recreate the issue?

**Comment by LK4D4** [comment]
@mrjana @mavenugo @aboch @sanimej do you know if this was fixed?

**Comment by sanimej** [comment]
@AlessandroEmm This is a old issue. I am not able to recreate it with latest master. Please try it out with 1.12.1 and if you still see the problem feel free to reopen the issue..

````
start a container and verify the published port is reached from outside.
vagrant@net-2:~$ docker run -it --rm --name c1 -p 192.168.33.12:80:80 nginx

192.168.33.13 - - [16/Sep/2016:00:07:00 +0000] "GET / HTTP/1.1" 200 612 "-" "curl/7.38.0" "-"

add a secondary IP to the interface..

sudo ip addr add dev eth1 192.168.33.45/24

3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:86:7b:ec brd ff:ff:ff:ff:ff:ff
    inet 192.168.33.12/24 brd 192.168.33.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet 192.168.33.45/24 scope global secondary eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe86:7bec/64 scope link 
       valid_lft forever preferred_lft forever

try the service again from the remote host..


192.168.33.13 - - [16/Sep/2016:00:07:21 +0000] "GET / HTTP/1.1" 200 612 "-" "curl/7.38.0" "-"
````
