### ISSUE TITLE
[1.6rc2] docker build output on OSX build context output off by one line

### ISSUE THREAD

**Issue by nathanleclaire** [docker/docker#11849]
Easiest to demonstrate visually:
![screen shot 2015-03-26 at 6 33 22 pm](https://cloud.githubusercontent.com/assets/1476820/6860553/15c09b10-d3e7-11e4-9dbe-d532c462ae95.png)

Steps to reproduce:

1. Run Docker daemon in boot2docker VM with 1.6rc2 binary, use 1.6rc2 client binary to run `docker build .` (cached build) from OSX.

Expected: Build context line does not overlap with "Step 0" line
Actual: Build context line _does_ overlap with "Step 0" line

**Comment by thaJeztah** [comment]
@jfrazelle should this be on the 1.6 milestone?

**Comment by jfrazelle** [comment]
ping @dmcgowan

**Comment by dmcgowan** [comment]
Not my area of expertise but I bisected down to this commit https://github.com/docker/docker/commit/12b278d3540bc32699e8c2197b556188fd98b77b

I will see if I can get a PR to fix this.

**Comment by jfrazelle** [comment]
whoa nice thanks!
