### ISSUE TITLE
daemon.Attach refactoring

### ISSUE THREAD

**Issue by mattetti** [docker/docker#11854]
https://github.com/docker/docker/blob/master/daemon/attach.go

* The `Attach` function in the `daemon` package is exported but not used anywhere else than within the package itself.
* The `Attach` function takes a very long list of arguments which could/should be simplified
* The `Attach` function uses `promise.Go` when it could just execute its body and wait on the waitgroup since that's how it's being used in the package anyway.

**Comment by cpuguy83** [comment]
+8,000,000

**Comment by jfrazelle** [comment]
do it do it do it, we also have a special place in our hearts for those who
can change things in attach without knocking down all the dominoes

**Comment by LK4D4** [comment]
@mattetti It used in builder/internals.go btw. But you're right it's awful.

**Comment by mattetti** [comment]
@LK4D4 is it cool if I were to refactor the code so we have a cleaner exported API only used by `builder/internals.go`, can we also safely assume that nobody is using these libs directly?

**Comment by jfrazelle** [comment]
Drone has a kinda copy pasted version of this attach but it's from a few
releases ago, make me wanna pull my hair out

**Comment by jfrazelle** [comment]
I would say if someone is relying on this they should switch to whatever
better version you have in mind

**Comment by mattetti** [comment]
Great, thanks @jfrazelle I'll try to find some time to do some cleanup, the scope of this task is quite limited so it should be doable :)

**Comment by cpuguy83** [comment]
@mattetti famous last words.

**Comment by mattetti** [comment]
Cleanest API I could come up with so far:

```func (daemon *Daemon) Attach(cont *daemon.Container, stdin io.ReadCloser, stdout, stderr io.Writer) error {}```

Instead of having a bunch of conditions everywhere, I would like to use `ioutil.Discard` when we don't care about a writer, is that cool?

Finally, is the lack of tests around attach due to the difficulty of writing such tests, or am I missing something?

I can't seem to run the tests (or build the package), because I can't figure out how to generate this package: `cannot find package "github.com/docker/docker/autogen/dockerversion"`
I guess I'm supposed to run my dev env inside docker which I didn't do :(

**Comment by jfrazelle** [comment]
Ya we have some auto generated files so people can use gcc go, we used to
use compile time variables but I digress, the easiest way to build docker
is inside docker with our makefile and hack scripts. There is documentation
on building on docs.docker.com but brief overview

make shell

Pops you into a shell inside the dev container

Make binary

Makes a binary and it's locally in your bundles folder

Make test-unit

Runs unit tests and so on and so forth

**Comment by jfrazelle** [comment]
You can build it locally but it's requires a lot of packages for static
linking various things and unless you are running on linux you can't really
build a real binary without them (btrfs-tools, aufs-tools, libapparmor, etc
etc)

**Comment by jfrazelle** [comment]
Also sorry we test a lot of things with integration-cli tests which shell
out to docker. Those are in the integration-cli for theres a file w attach
in the name

You run those tests w

make test-integration-cli


You can run a single test w

TESTFLAGS='-run TestAttach' make test-integration-cli

**Comment by mattetti** [comment]
Thanks @jfrazelle super useful, I got the tests to run and I get how they work now. How do you guys setup your dev env tho, I use vim and I have a bunch of tools checking that the package compiles on save, run `goimport` etc.., because the pkg doesn't compile locally, I can't use all these tools. Do you setup a dev env inside a container and mount the shared source code?  Sorry for the newbie questions, I feel that I should know that already :(

**Comment by jfrazelle** [comment]
Nah these are great questions, we were actually all comparing our
environments the other day.

Personally I use vim locally with vim-go, and go imports in save. But I
don't have anything fancy as far as compile on save, maybe somebody else
some secret sauce.

**Comment by jfrazelle** [comment]
If you wanna get really fancy I bet if you edit the makefile docker run to
include -v $HOME/.vimrc:/root/.vimrc:ro -v $HOME/.vim:/root/.vim:ro

Then make shell, and apt-get install vim, there's about a 99% chance all
your plugins work

**Comment by aneshas** [comment]
Hey guys, so are we supposed to consider this issue as claimed?

**Comment by LK4D4** [comment]
ping @mattetti 
Are you working on this?

**Comment by mattetti** [comment]
Feel free to take this issue, I started working on it, but my free time is so limited that I don't want to block anyone interested in refactoring this code.

**Comment by aneshas** [comment]
Thanks, I'll "have a GO" then :smile: 
#dibs

**Comment by runcom** [comment]
@aneshas any update on this? :)

**Comment by aneshas** [comment]
Hey, sorry, I've been busy lately, totally forgot I claimed this issue, I'm sorry. Someone else can take it, I apologise once again

**Comment by runcom** [comment]
thanks! I'll take it then!

**Comment by vdemeester** [comment]
@runcom any update :wink: ?

**Comment by runcom** [comment]
Been doing other things sorry for this :/ would you have this a go?

**Comment by vdemeester** [comment]
@runcom I've added this in my "To look list" but I think we should remove the status/claimed for now then :wink:

**Comment by calavera** [comment]
This has been hugely cleaned up. Closing as fixed.
