### ISSUE TITLE
Volume and symbolic links in 1.6.0-rc2

### ISSUE THREAD

**Issue by ggtools** [docker/docker#11862]
`<mylife>`
I accidentally discover through docker-compose trying to give access to `/var/run/docker.sock` from inside a container
`</mylife>`

## Environment

Docker is running on Ubuntu 14.04 using the default aufs storage driver.

The goal is to create a volume in a directory which is actually a symbolic link. I use the `/var/run` directory which is a symlink to `/run` in Ubuntu 14.04

The test command will be:

    docker run --rm -ti --volume /var/run/gordon ubuntu /bin/bash

If `/var/run/gordon` does not exist on the host, the command is working find on both 1.5.0 and 1.6.0-rc2.

Now if I create a file on the host:

    sudo touch /var/run/gordon
    docker run --rm -ti --volume /var/run/gordon ubuntu /bin/bash

In 1.5.0 everything is going smoothly and a `/var/run/gordon` directory is created inside the container.

In 1.6.0-rc2, the container's creation is failing with the following error message:

    FATA[0000] Error response from daemon: file exists at %!s(MISSING), can't create volume there

The issue does not happen if I'm using `--volume /run/gordon`

**Comment by coolljt0725** [comment]
@ggtools  What cause this error is that `/var/run` is a  symlink to `/run` in ubuntu rootfs, when doing `parseVolumeMountConfig`( which will cause this error),  the container has not create a mount namespace  and `/var/run` in container's rootfs will link the host's `/run`, so the error happened. I trying to fix this.
