### ISSUE TITLE
Can I hide exposed port in base image of Dockerfile?

### ISSUE THREAD

**Issue by allencloud** [docker/docker#11864]
Hi, All,

Here is my situation. I have a base_image of BASE1, and it is built form Dockerfile1. In Dockerfile1, there is two exposed ports(port1 and port2)with EXPOSE.

Now I hope to build an image named NEWIMAGE from Dockerfile2, in Dockerfile2 there is FROM BASE1. 

Can I hide port2 and just leave port1 when building Dockerfile2?

If I could, how to write my Dockerfile2 to hide port2?

**Comment by duglin** [comment]
Not yet but there's a PR to "unset" things from a base image: https://github.com/docker/docker/pull/8177
