### ISSUE TITLE
Allow additional configuration to be loaded from /etc/sysconfig/docker.d files

### ISSUE THREAD

**Issue by rothgar** [docker/docker#11874]
If the `/etc/sysconfig/docker` file is managed by a configuration management system then it does not allow individual configuration of options. Ideally we could set some default options that a user can append their own options to.

```
OPTIONS=--selinux-enabled
```

and then another user can extend those options with configuration in the docker.d folder

```
OPTIONS=-H fd://127.0.0.1
```

The options can then be combined at runtime without needing additional config management changes to the system. The daemon in the above example would be started with `docker -d --selinux-enabled -H fd://127.0.0.1`

**Comment by phemmer** [comment]
If your CMS is fully controlling `/etc/sysconfig/docker`, and doesn't support controlling individual lines in the file, then you can always have your CMS use `/etc/sysconfig/docker.d`.

Meaning have your CMS create `/etc/sysconfig/docker` as:

```
for file in /etc/sysconfig/docker.d/*; do
 [ -f "$file" ] && . "$file"
done
```

&nbsp;

In my own personal opinion, if your CMS is breaking your ability to configure docker, I don't think it's docker's responsibility to fix the situation.

**Comment by rothgar** [comment]
Why not just have that functionality built into the default config? Many other services use .d folders not because something needs "fixing" but because it makes the service more flexible and provides more options for configuration.
That also doesn't solve the problem of combining options if two separate files declare `OPTIONS`. It can be fixed by declaring each file with `OPTIONS=${OPTIONS} --some-option` which might be fine but I think better variable loading could be included.
