### ISSUE TITLE
API feature request: Include tags in image search results

### ISSUE THREAD

**Issue by terminalmage** [docker/docker#11903]
http://docs.docker.com/reference/api/docker_remote_api_v1.17/#search-images

Apologies if there is an open issue for this already, I searched but did not find one.

**Comment by xiaods** [comment]
Proposal result:

 HTTP/1.1 200 OK
    Content-Type: application/json

    [
            {
                "description": "",
                "is_official": false,
                "is_automated": false,
                "name": "wma55/u1210sshd",
                "star_count": 0,
                "tags": ["v1", "v2"]
            },
            {
                "description": "",
                "is_official": false,
                "is_automated": false,
                "name": "jdswinbank/sshd",
                "star_count": 0,
                 "tags": ["v1", "v2", "latest"]
            },
            {
                "description": "",
                "is_official": false,
                "is_automated": false,
                "name": "vgauthier/sshd",
                "star_count": 0,
                "tags": ["new_tag", "latest"]
            }
    ...
    ]

**Comment by xiaods** [comment]
Proposal result:

 HTTP/1.1 200 OK
    Content-Type: application/json

    [
            {
                "description": "",
                "is_official": false,
                "is_automated": false,
                "name": "wma55/u1210sshd",
                "star_count": 0,
                "tags": ["v1", "v2"]
            },
            {
                "description": "",
                "is_official": false,
                "is_automated": false,
                "name": "jdswinbank/sshd",
                "star_count": 0,
                 "tags": ["v1", "v2", "latest"]
            },
            {
                "description": "",
                "is_official": false,
                "is_automated": false,
                "name": "vgauthier/sshd",
                "star_count": 0,
                "tags": ["new_tag", "latest"]
            }
    ...
    ]

**Comment by noseglid** [comment]
I would love to see this implemented! There is an [endpoint on the docker registry](https://docs.docker.com/v1.6/reference/api/registry_api/#list-repository-tags). Usable via curl: `curl "https://registry.hub.docker.com/v1/repositories/ubuntu/tags"`

**Comment by runcom** [comment]
that's on registry v1, I believe this would be a good fit after v2 has search capability as well

**Comment by thaJeztah** [comment]
This is roughly a duplicate of https://github.com/docker/docker/issues/17238, which is more recent, but has more discussion. I'll close this issue for housekeeping, please continue the discussion on that issue
