### ISSUE TITLE
32bit program run error in 32bit container

### ISSUE THREAD

**Issue by zhaozww** [docker/docker#11902]
I use docker run a container in a fedora 64 bit systems(docker 1.5), and 32-bit libc libraries have been installed in the container (because i want to run a 32-bit program in the container), the program run normally on the host system，but when running in the container, the program report memset_sse2_rp error, bus error core dump, later I installed on the docker (32 bit) in ubuntu32 system, and then run the program in the new container, the above error is also, please help analysis.

Create the shared memory
Bus error (core dumped)

**Comment by zhaozww** [comment]
the program run in fedora 64bit,

root@localhost net]# ./dev0
------------------------------------------->
VPORT 1.0 start...
------------------------------------------->
Create the shared memory
INFO :Socket: id=0, localip=7f000001:50000, destip=7f000001:64889 [udp_client]
INFO :Socket: id=1, localip=7f000001:50001, destip=7f000001:64970 [udp_client]
INFO :Socket: id=2, localip=7f000001:50002, destip=7f000001:3149 [udp_client]
VPORT_Resource_Init ok.
VPORT_Hal_Drv_Init ok.
VPORT_Hal_Drv_Init ok.


the program run in 32bit container,
root@7d3f1cfe77be:/var/net# ./dev0
------------------------------------------->
VPORT 1.0 start...
------------------------------------------->
Create the shared memory
Bus error (core dumped)

**Comment by zhaozww** [comment]
use gdb in container,
------------------------------------------->
VPORT 1.0 start...
------------------------------------------->
Create the shared memory

Program received signal SIGBUS, Bus error.
__memset_sse2_rep () at ../sysdeps/i386/i686/multiarch/memset-sse2-rep.S:325
325	../sysdeps/i386/i686/multiarch/memset-sse2-rep.S: No such file or directory.

**Comment by Silex** [comment]
Maybe related, but I found out that using gdb inside a docker container on a binary built with `-m32` silently fails (I can set the breakpoints and everything but they're never hit).

It works if I use the `--privileged` flag on the container tho.

**Comment by cpuguy83** [comment]
Yes, this is probably an issue with restricted permissions in the container.
Try with --privileged and see if it works.
If it does, you need to tweak what capabilities are available to the container (and close the issue).
