### ISSUE TITLE
RHEL 7 Installation documentation is misleading for EC2 instances

### ISSUE THREAD

**Issue by pdevine** [docker/docker#11910]
On https://docs.docker.com/installation/rhel/ it's mentioned that you can use the command:

    $ sudo subscription-manager repos --enable=rhel-7-server-extras-rpms

however, this doesn't work by default on RHEL 7 EC2 instances.  Instead, you need to modify the file:

    /etc/yum.repos.d/redhat-rhui.repo

and modify the "[rhui-REGION-rhel-server-extras]" section to include "enabled=1".

**Comment by ankushagarwal** [comment]
I verified this on a AWS EC2 instance. By default the RHEL 7 EC2 instances are **unregistered**.
If the system is unregistered, `sudo subscription-manager repos --enable=rhel-7-server-extras-rpms` will not work and will fail.

You do not need to manually edit the .repo file, you can use the `yum-config-manager` tool to enable repos.

In this case, that would be `yum-config-manager --enable rhui-REGION-rhel-server-extras`. `yum-config-manager` will edit the repo file and set enabled=1 too, but it is the recommended interface to enable/disable repos.

@moxiegirl : I can update the docs for this

**Comment by pdevine** [comment]
Cool!  Maybe the yum-config-manager tool should be called out instead of subscription-manager so that way it would work regardless of whether you're registered or not.  I'm assuming yum-config-manager will work in all instances.

**Comment by ankushagarwal** [comment]
It probably should work, but I have no way to verify that since RHEL is licensed OS and I don't have access to it outside the EC2 AWS instance which I just spun up.

**Comment by moxiegirl** [comment]
@ankushagarwal I can verify it on our end.  We are planning on standardizing our installation documentation.  Ubuntu is done. If you want to try to bring RHEL into the fold here is the PR that explains the general plan: https://github.com/docker/docker/pull/11355

**Comment by pdevine** [comment]
Do you guys want to change the docs to include "yum-config-manager --enable rhui-REGION-rhel-server-extras" at least for ec2 instances?  I think it'll work in both places, and I've tested it out with ec2.

Seems like an easy fix and we can close the issue.

**Comment by pdevine** [comment]
Verified that the docs are fixed.
