### ISSUE TITLE
permission denied on /etc/docker for non-root client of docker API on ubuntu

### ISSUE THREAD

**Issue by kdvolder** [docker/docker#11927]
Ubuntu 12.04. I installed docker as per the instructions here: 
https://docs.docker.com/installation/ubuntulinux/

Then I added my user to the 'docker' unix group so as to be able to run docker commands without 'sudo'.

Then I ran into this problem:
https://github.com/pivotal-cf-experimental/lattice-cli/issues/15

Someone diagnosed my problem as an issue caused by permissions on /etc/docker which do not allow non-root user access. They beleave that this is a problem in the docker apt package that should probably be fixed. So I'm reporting it here.

**Comment by cpuguy83** [comment]
Are you still able to reproduce?

**Comment by thaJeztah** [comment]
@kdvolder I'm closing this issue for now, but feel free to comment here if you're still able to reproduce this, then I'll reopen

**Comment by markpollack** [comment]
I get the same issue with ubuntu 14.04 and docker 1.7.1 (setup so I can run docker w/o sudo). 
Lattice 0.2.7 - 

`$ ltc create lattice-app cloudfoundry/lattice-app
Error fetching image metadata: open /etc/docker/certs.d/index.docker.io: permission denied`


 `sudo chmod 755 /etc/docker` as a workaround fixed the issue.

**Comment by nicovillanueva** [comment]
+1 to this issue

    ~/devel/apps/lattice
    $> ltc create lattice-app cloudfoundry/lattice-app
    Error fetching image metadata: open /etc/docker/certs.d/index.docker.io: permission denied

    ~/devel/apps/lattice
    $> sudo chmod 755 /etc/docker

    ~/devel/apps/lattice
    $> ltc create lattice-app cloudfoundry/lattice-app
    No port specified, image metadata did not contain exposed ports. Defaulting to 8080.
    [... success...]
