### ISSUE TITLE
Proposal:  expand dockerfile command "ENV" to be able to unset environment variables

### ISSUE THREAD

**Issue by liusdu** [docker/docker#11922]
### problem on unsetting  environment variables

 In Dockerfile,  we use "ENV" command to export environment variables. But we can not unset variables.  While in linux shell  we can do that  using "export -n" or "unset". It is very inconvenient. Think about below:
 * variables while useful duiring image-building but useless when finishing. (such as https_proxy).  So I think we need this improvement.

*  number of en variables  can only grow

### RFC thoughts to solve this.
Allow ENV to allow one argument.  Look at these cases:
* ENV VAR 1  \#set VAR to 1
* ENV VAR    \#unset VAR
* ENV VAR=1 \#set VAR to 1
* ENV VAR= \#unset VAR

RFC patches you can see here ##11921
### Lable
We can expend lable command just as what ENV does.

**Comment by thaJeztah** [comment]
I think this is a dup of https://github.com/docker/docker/issues/3465, which is implemented in https://github.com/docker/docker/pull/8177

Unfortunately it didn't make it in the 1.6 release, but is scheduled for docker 1.7

**Comment by erikh** [comment]
Yes, I prefer this approach over the proposed one here. Sorry.

-Erik

**Comment by liusdu** [comment]
Yes, I have not seen it . I will cose this issue

**Comment by thaJeztah** [comment]
@liusdu thanks! Thanks you for your contribution (even though it won't be merged). I fully agree that something like this is needed, so hope that https://github.com/docker/docker/pull/8177 will be merged soon.

Please don't let this stop you from contributing to the project; it is really appreciated!
