### ISSUE TITLE
Pid displayed as float with CLI's docker inspect --format

### ISSUE THREAD

**Issue by gdm85** [docker/docker#11924]
```
$ docker inspect --format "{{.State.Pid}}" my-container
1.107555e+06
```

The same goes for the State object itself:
```
docker inspect --format "{{.State}}" my-container
map[Pid:1.107555e+06 Restarting:false StartedAt:2015-03-30T13:39:26.745577644Z Error: ExitCode:0 FinishedAt:0001-01-01T00:00:00Z OOMKilled:false Paused:false Running:true]
```

Although the Pid number is correctly displayed as ``1107555`` when ``--format`` is not being used.

**Comment by duglin** [comment]
I believe https://github.com/docker/docker/pull/11839 will fix this.

**Comment by gdm85** [comment]
It seems to be a feature of [Go templates](http://golang.org/pkg/text/template/). A lengthy workaround:
``docker inspect --format '{{printf "%.0f" .State.Pid}}' $CID``

@duglin but in runconfig.State I still see Pid as an int?

**Comment by duglin** [comment]
@gdm85 yep but Go is funky about it when reading it into an 'interface'

**Comment by gdm85** [comment]
@duglin doesn't seem to fix the issue. Will report on PR #11839

Closing as dup of #11641

**Comment by duglin** [comment]
@gdm85 ok thanks for testing it and moving the conversation over to #11839
