### ISSUE TITLE
restart: always deadlocks docker daemon

### ISSUE THREAD

**Issue by sdake** [docker/docker#11940]
It appears a lock is leaked in the restart: always case when used with docker compose.  My container is designed to restart.  The container I am using is the keystone container which has a dependency on mariadb.  If mariadb is not started, keystone will continuously restart until the db is available.  This causes commands like docker ps and  docker logs to lock for long periods waiting for the restart timeout period to conclude.

My guess is a lock is held while the timer is ticking on whether a process is successfully started or not.  running docker ps blocks for double each time (as the restart:always case doubles the timer from 100msec to 200msec etc).

My docker-compose YML is:
https://github.com/stackforge/kolla/blob/master/compose/keystone.yml

after a successful sudo docker ps completes (container up less then a second reported by docker compose) I run:
time sudo docker ps:
The result is:
3 m 24 seconds

**Comment by jfrazelle** [comment]
is this with the rc or with master

**Comment by jfrazelle** [comment]
my guess is probably both, i will try to reproduce

**Comment by sdake** [comment]
@jfrazelle this test case was actually documented with the execdriver branch, which could have been the cause of the problem.  I seem to recall the same problem with master however as the kolla community constantly complains about wanting to remove restart:always from the docker-compose files - which I am having a hard time defending because of this problem.  Not all of them are running the execdriver branch.

**Comment by jfrazelle** [comment]
hmmm so is it a compose specific issue?

**Comment by LK4D4** [comment]
Should be easy fix. Someone need just to reproduce it and then we can find deadlock with my `github.com/docker/LK4D4/debugmutex`

**Comment by jfrazelle** [comment]
maybe they are starting in the wrong order or something

**Comment by jfrazelle** [comment]
ah nice

**Comment by jfrazelle** [comment]
also just to be sure pinging @aanand @bfirsh

**Comment by sdake** [comment]
@jfrazelle I highly doubt this is a docker-compose issue.  I suspect if you ran the correct docker cli with that one container, it would cause the problem.  Consider a scenario where mariadb for whaever reason (database corrupt) fails to start repeateadly, this keystone container will also fail repeatidly.

To sum up the issue if you have a container that exits quickly with restart:always, the docker ps command time run length will double each time the container restarts :)

**Comment by jfrazelle** [comment]
yeah so I do that a lot on my prod server, actually just the other day when
i migrated it I forgot to start the linking container and I never hit a
deadlock, but I'm trying to reproduce through the cli

**Comment by sdake** [comment]
@jfrazelle note docker 1.5.0 does not exhibit this issue:
[sdake@minime-02 compose]$ sudo docker -v
Docker version 1.5.0, build a8a31ef/1.5.0

trying rc next.

**Comment by jfrazelle** [comment]
Thanks so much

**Comment by sdake** [comment]
@jfrazelle this is not apparent in rc2 from test.docker.io.   I think this is a bug in lk4d4's execdriver branch.  Apologies for the noise.  Closing for now.

**Comment by jfrazelle** [comment]
Thanks so much for testing!
