### ISSUE TITLE
Proposal:Enable docker load specify URL

### ISSUE THREAD

**Issue by Fangfenghua** [docker/docker#11951]
Now docker load cmd load a tar archive on STDIN, that's must copy the file to the node where the docker running. If the docker load can load file from a URL,then we can avoid copy the tar archive to the node where docker running.It't would look like:
   docker load -i http://$ip/test.tar

**Comment by jfrazelle** [comment]
ping @ewindisch @NathanMcCauley @diogomonica seems a bit inseceure kinda like a curl | bash idk

(took me like 5 min to find all your names)

**Comment by dmp42** [comment]
Even with that feature, the data would have to be copied over, right?

If I understand well, this feature is barely about saving a few keystrokes (eg: it does `wget http://$ip/test.tar && docker load -i test.tar && rm test.tar`).

Getting it to work right is a full-time burden (authentication, redirects, etc), and it does add orthogonal functionality to maintain.

Overall, I'm -1 on this - but obviously this is an open-ended discussion...

**Comment by diogomonica** [comment]
I think the user expectation of `docker load` usage is "I got an image from a trustworthy source and I want to load it". This means that they probably transferred the image using ssh, sftp or other secure methods of transport.

Allowing over the network loading via an insecure resource is giving users another way of doing the wrong thing, and changing the expectation of load.

I'm also -1 on this proposal.

**Comment by ewindisch** [comment]
The problem with the current behavior is that a client must download a tar, and then send it to the server which may not be local. I could see this being a problem for some users.

However, best practices at the moment, given that we have no internal integrity checks on the images output from 'docker save' would suggest users check signatures or hashes on these images out-of-band. That isn't possible if the daemon downloads the images directly.

I think it would be reasonable to reconsider this following improvements to the image format....

Until then: -1

**Comment by xiaods** [comment]
curl | bash is can perfect archive this request. I am not found any benefit with user experience.  @Fangfenghua could you please have a rethink on this context and give more reasonable information here. it will help the proposal can get some support feedback.

**Comment by neolace** [comment]
Is this still a requirement, which by looking at the comments, aren't well received?

**Comment by xiaods** [comment]
-1

**Comment by thaJeztah** [comment]
Thanks for proposing this, @Fangfenghua however, there are multiple maintainers against this, so I'll close this issue.
