### ISSUE TITLE
docker run -i never exits if spawned by other process for reading / writing using pipe

### ISSUE THREAD

**Issue by detomastah** [docker/docker#11957]
Description of problem:

When interacting with docker container through popen, the dockerized process hangs. The process is visible in system process list `ps aux | grep docker`, but `docker ps` shows that it exited.
When I pass something onto `stdin`, the process exits. The problem is easily reproducible, I tried on Docker 1.4.1 and 1.5.0 and result was the same. Scroll down to see the example code how to reproduce it.

`docker version`:

```
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

`docker info`:

```
Containers: 26
Images: 143
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 216
Execution Driver: native-0.2
Kernel Version: 3.13.0-43-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 4
Total Memory: 7.633 GiB
Name: lukasz-ThinkPad-T420
ID: LKJ2:DWR4:JPLK:6TCQ:JZ4K:CQWB:PIGH:PFM4:FAFI:OTHH:QESL:OIFC
WARNING: No swap limit support
```

`uname -a`: 

`Linux lukasz-ThinkPad-T420 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`

Environment details: physical, Ubuntu 14.04

How reproducible:

Create test.rb file with following code:

```ruby
command = 'docker run -i ubuntu /bin/ls'

in_r, in_w = IO.pipe
out_r, out_w = IO.pipe
err_r, err_w = IO.pipe

in_w.sync = true

pid = spawn(
  command,
  in: in_r,
  out: out_w,
  err: err_w
)

[in_r, out_w, err_w].each {|io| io.close }

puts "One: #{pid}"

Process.waitpid(pid)

puts "Two"
```

Then run:

`ruby test.rb`

Actual Results:

You will see that it never exits, never returns "Two". Dockerized `/bin/ls` process is still running but running `docker ps --all` shows that container immediately exited. If you remove `-i` flag is starts to work as expected but communication with process is lost.

Expected Results:

`ruby test.rb` should exit immediately returning "Two"

**Comment by y3ti** [comment]
I have got the same problem.

**Comment by vdemeester** [comment]
But if you run it with ``-it`` instead of just ``-i`` it works as expected.

**Comment by vdemeester** [comment]
I'm not a ruby expert but :

> The write end of the pipe has its sync mode set automatically such that Ruby does not buffer writes; the read end will block until the write end has been closed for writing

As long as you don't close the input, it won't close the read, and thus the /bin/ls process will still be there..

And in the script, you never close the ``in_w``. If you close it (telling that you don't have anything more to say to the process) it will work as expected.

The following code will work (closing ``in_w`` instead of ``in_r``).

```ruby
command = 'docker run -i ubuntu /bin/ls'

in_r, in_w = IO.pipe
out_r, out_w = IO.pipe
err_r, err_w = IO.pipe

in_w.sync = true

pid = spawn(
  command,
  in: in_r,
  out: out_w,
  err: err_w
)

[in_w, out_w, err_w].each {|io| io.close }

puts "One: #{pid}"

Process.waitpid(pid)

puts "Two"
```

The only thing weird in your case, is that docker ps doesn't say the container is still running, but the process is ; so it might be a bug or something to document.

**Comment by detomastah** [comment]
@vdemeester Thanks for response! Unfortunately you are closing ability to write to `stdin` of the running process - it works, but this way you are essentially running it without `-i`. Running it with `-it` does not work for every command (for example `mruby`) - you'll get error: `cannot enable tty mode for non-tty input`

**Comment by detomastah** [comment]
I managed to do what I wanted, but only after I wrapped my program in 'real' pseudo terminal with disabled echo.

**Comment by vdemeester** [comment]
Let's try to label it, so it gets more "views" and opinions

+kind/bug
+status/0-needs-triage

**Comment by vdemeester** [comment]
+kind/bug
+status/0-needs-triage

**Comment by cpuguy83** [comment]
I'm not sure that this is a bug.
When `-i` is set, the client does a hijack. The hijack will block until we receive an EOF (or any error) from stdin.
https://github.com/docker/docker/blob/master/api/client/hijack.go#L228
When stdin is a TTY the client will not block waiting for stdin: https://github.com/docker/docker/blob/master/api/client/hijack.go#L250-L255

@vdemeester WDYT? I think we can close this.

**Comment by cpuguy83** [comment]
Actually, I take that back, this is a bug. Let me see how difficult it is to fix.

**Comment by vdemeester** [comment]
@cpuguy83 yeah I was more thinking it's a bug :sweat_smile:

**Comment by cpuguy83** [comment]
Looking closer, this looks like the same bug as others where you have to type some input for the client to actually exit with stdin open.
