### ISSUE TITLE
fix TestRunCreateVolumesInSymlinkDir so works on lxc

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#11964]
test from https://github.com/docker/docker/pull/11934 should pass on lxc and not be skipped, was an implementation detail of the test iteslf

**Comment by icecrime** [comment]
As notified in our [deprecation notice](https://github.com/docker/docker/blob/d023d5a8a24c18e912162c2f4c724cfb21028301/docs/misc/deprecated.md#lxc-built-in-exec-driver), Docker 1.10.0 will drop support for the LXC exec driver (#17700).

Thank you for the report, I'm now closing this.
