### ISSUE TITLE
Proposal: forward container log to specified url

### ISSUE THREAD

**Issue by x1022as** [docker/docker#11979]
Now logging driver is done and syslog added. And sometimes forwarding log to remote url is required.

Can daemon send container log to specified url through syslog, just like #9513 did. It should not be too much complex with syslog.Dial()

Maybe a new argument is needed, like `--log-driver-opt`. We can use this with following format:
    `--log-driver-opt url,tag,prior`: to specify url, tag and priority. 
    `--log-driver-opt url`, `--log-driver-opt ,tag`, `--log-driver-opt ,,prior` ...: to specify one parameter and leave the others default.

**Comment by gdm85** [comment]
Wouldn't be best if this was kept outside the scope of Docker? Maybe it could fit into a specific logging driver, or even in early post-processing.

**Comment by cpuguy83** [comment]
I believe #11485 implements `--log-opt`, which could be used.
And I agree, being able to specify a remote syslog would be nice.

**Comment by LK4D4** [comment]
@cpuguy83 Yup, we need use `--log-opt` for configuring syslog.

**Comment by x1022as** [comment]
@cpuguy83 thanks, #11485 is about log rollover, and the --log-opt fomat is great.

@LK4D4 do you have any plans for syslog log-opt? Is it under developing?

**Comment by calavera** [comment]
We already added a `syslog-address` option to the driver. Closing this as done.

https://github.com/docker/docker/blob/master/daemon/logger/syslog/syslog.go#L69
