### ISSUE TITLE
Jenkins build test for trailing whitespaces in docs

### ISSUE THREAD

**Issue by ankushagarwal** [docker/docker#11977]
We should probably not allow trailing whitespaces in docs files, especially in *.md files. Simple find/grep inside the docs/ directory should be able to reveal trailing whitespaces. Better yet, enforce this globally. No trailing whitespaces in any *.md file in the entire repository.

**Comment by ankushagarwal** [comment]
#11976 currently removes trailing whitespaces from the complete docs/ directory

**Comment by ankushagarwal** [comment]
+exp/expert

**Comment by ankushagarwal** [comment]
Just learnt that some trailing spaces can be a part of the markdown syntax

> When you do want to insert a `<br />` break tag using Markdown, you end a line with two or more spaces, then type return

**Comment by duglin** [comment]
What's the status of this?  Should we close it given the previous comment?

**Comment by ankushagarwal** [comment]
Yes, I think we can close this. I could not find any set of rules dictating how .md files should be written/formatted.
