### ISSUE TITLE
Add go vet check

### ISSUE THREAD

**Issue by LK4D4** [docker/docker#11970]
Add `go vet` check. You need to create `hack/make/validate-vet` script and add it to `hack/make.sh`.

**Comment by thaJeztah** [comment]
@robertabbott are you working on this? If you are, let me know, then I mark this issue "claimed"

**Comment by robertabbott** [comment]
Hi @thaJeztah. I am working on it. I think the change is nearly ready to go. The only thing I'm not sure about is whether I need to add the vet tool to the vendor directory

**Comment by LK4D4** [comment]
@robertabbott I think it is enough to get it in `Dockerfile` like we do for `cover`.

**Comment by thaJeztah** [comment]
Hi @robertabbott no problem, I just added the "claimed" status, to prevent others from working on it. Just create the PR when you think you're ready. And awesome that you're working on it :+1:
