### ISSUE TITLE
docker-compose and passwords from environment

### ISSUE THREAD

**Issue by ctmnz** [docker/docker#11983]
I was experimenting with docker-compose and I saw something a little bit disturbing in my output of phpinfo() function:  LAMPDB_1_ENV_MYSQL_ROOT_PASSWORD	lamppass

my docker-compose.yml:

lampapp:
  build: .
  ports:
    - "8000:80"
  links:
    - lampdb
    - lampmemcache
  volumes:
    - /var/
lampdb:
  image: "mysql:5"
  volumes:
    - ./mysql:/etc/mysql/conf.d
  environment:
    - MYSQL_ROOT_PASSWORD=lamppass
lampmemcache:
  image: "memcached"

I know that it is set by 'environment:' but my question: Is it O.K. (I think it is not) any application from my 'composed' docker infrastructure to see set passwords from the installation process ?

**Comment by ctmnz** [comment]
Opz. This is for docker/compose not for docker/docker. Closing here, reporting at docker/compose

**Comment by thaJeztah** [comment]
@ctmnz actually, this is a behavior of docker (not docker-compose). You can find a warning about this in the user-guide; https://docs.docker.com/userguide/dockerlinks/#environment-variables

> **Warning: ** It is important to understand that all environment variables originating from Docker within a container are made available to any container that links to it. This could have serious security implications if sensitive data is stored in them.

**Comment by ctmnz** [comment]
Thanks for the elaboration @thaJeztah
