### ISSUE TITLE
Unable to login to docker from command line - Ubuntu

### ISSUE THREAD

**Issue by vivganes** [docker/docker#11989]
Error seen after "sudo docker login":
Post http:///var/run/docker.sock/v1.17/auth: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS? 

vivek@gvivek-gsu-hyd:~$ uname -a
Linux gvivek-gsu-hyd 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

I have logged out and logged in after installing docker using steps at http://docs.docker.com/installation/ubuntulinux/

Could you please help me in getting docker to run?

**Comment by marcelloromani** [comment]
`/var/run/docker.sock: no such file or directory.`

It could be a problem related to docker daemon not automatically starting under certain Ubuntu versions. See #12002 for an example.

Which version of Ubuntu are you running?
`cat /etc/lsb-release `

Is the daemon running?
`sudo service docker status`

**Comment by dustinkirkland** [comment]
'Twas exactly my problem.  Fixed with 'sudo service docker start'.  A more meaningful error message would be nice.

**Comment by cpuguy83** [comment]
Closing since there's no response, and also seems pretty apparent that docker is not started.
