### ISSUE TITLE
无法下载镜像

### ISSUE THREAD

**Issue by kys1230** [docker/docker#11986]
可能是之前做了错误操作
我把/dev/mapper/docker-253:0-262992-pool 这个文件删除掉了. 现在没法恢复了..请问有什么办法么

[root@localhost ~]# docker pull centos
centos:latest: The image you are pulling has been verified
511136ea3c5a: Download complete 
511136ea3c5a: Error downloading dependent layers 
5b12ef8fd570: Download complete 
5c5681003a50: Pulling fs layer 
2b8d6139a545: Error pulling image (latest) from centos, Driver devicemapper failed to create image rootfs 511136ea3c5a64f264b78b5433614aec563FATA[0017] Error pulling image (latest) from centos, Driver devicemapper failed to create image rootfs 511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158: Can't set task name /dev/mapper/docker-253:0-262992-pool

**Comment by unclejack** [comment]
@vbatts Wasn't this `can't set task name` error fixed? This looks like an old version of Docker.

**Comment by kys1230** [comment]
这个docker是通过epel安装的docker-io 
[root@localhost ~]# docker --version
Docker version 1.4.1, build 5bc2ff8/1.4.1

**Comment by vbatts** [comment]
@kys1230 is it possible to test with a newer version of docker, like 1.5?

**Comment by kys1230** [comment]
@vbatts 我更换了docker 1.5.0 还是有这个问题
INFO[0000] docker daemon: 1.5.0 a8a31ef; execdriver: native-0.2; graphdriver: devicemapper 
INFO[0000] +job acceptconnections()                     
INFO[0000] -job acceptconnections() = OK (0)            
INFO[0017] POST /v1.16/images/create?fromImage=centos%3Alatest 
INFO[0017] +job pull(centos, latest)                    
INFO[0017] +job resolve_repository(centos)              
INFO[0017] -job resolve_repository(centos) = OK (0)     
INFO[0017] +job trust_update_base()                     
INFO[0018] -job trust_update_base() = OK (0)            
INFO[0021] +job trust_key_check(/library/centos)        
INFO[0021] -job trust_key_check(/library/centos) = OK (0) 
INFO[0021] Image manifest for centos:latest has been verified 
ERRO[0024] Error from V2 registry: Driver devicemapper failed to create image rootfs 511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158: Can't set task name /dev/mapper/docker-253:0-262992-pool 
Error pulling image (latest) from centos, Driver devicemapper failed to create image rootfs 511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158: Can't set task name /dev/mapper/docker-253:0-262992-pool
INFO[0034] -job pull(centos, latest) = ERR (1)

**Comment by kys1230** [comment]
[root@localhost ~]# cat /etc/redhat-release 
CentOS release 6.4 (Final)
[root@localhost ~]# uname -a
Linux localhost.localdomain 2.6.32-358.el6.x86_64 #1 SMP Fri Feb 22 00:31:26 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

**Comment by unclejack** [comment]
@kys1230 Please update your system using `yum update` and `reboot` after.

**Comment by kys1230** [comment]
@unclejack Thank you very much in accordance with the you said problem is solved
