### ISSUE TITLE
new feature: add --dns option to build

### ISSUE THREAD

**Issue by kryton** [docker/docker#12000]
docker build seems to create a internal container and 'runs' things in them.
sadly there is no way to adjust the container settings to use a custom DNS so in my case it can't resolve an internal hostname to do a git pull from.

any chance of adding this as an option to the 'build' side?

Thanks!

**Comment by coolljt0725** [comment]
@kryton  For your use case, an alternative way is to set your dns when start the docker daemon with `docker -d  --dns=x.x.x.x`, this will add the `dns=x.x.x.x` to all your container include the internal container on building.  But this is not a good way since it will affect all the container.
I think add `--dns` option to build is resonable

**Comment by gdm85** [comment]
I think dup of my old #5779, there is a workaround there but feel free to keep it open if you have new arguments for this feature request.

**Comment by thaJeztah** [comment]
@gdm85 ah, thanks. For reference, workaround is explained here https://github.com/docker/docker/issues/5779#issuecomment-59946467

@kryton will the hints here help you solve your use-case, or do you prefer to keep it open?

**Comment by kryton** [comment]
Hi Stin.
I have a work-around in place, by altering dns in other places..

On Mon, Apr 13, 2015 at 6:25 PM, Sebastiaan van Stijn <
notifications@github.com> wrote:

> @gdm85 <https://github.com/gdm85> ah, thanks. For reference, workaround
> is explained here #5779 (comment)
> <https://github.com/docker/docker/issues/5779#issuecomment-59946467>
>
> @kryton <https://github.com/kryton> will the hints here help you solve
> your use-case, or do you prefer to keep it open?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/12000#issuecomment-92532094>.
>



-- 
Ian Holsman
ian@holsman.com.au
PH: + 61-3-9028 8133 / +1-(425) 998-7083

**Comment by thaJeztah** [comment]
@kryton do you want this issue to stay "open", or should it be closed?
