### ISSUE TITLE
Can docker restore a container using data volume replicated?

### ISSUE THREAD

**Issue by allencloud** [docker/docker#12019]
As we know, docker will store data in data volume on the host when using mongo, mysql or some other data storage images.

If we back up the data volume of mysql on host , and now the docker node is unrecoverable down, can we start a mysql container just using the previous data volume?

I think it is reasonable to have this kind of ability.

Thanks.

**Comment by unclejack** [comment]
@allencloud Yes, you can do that if you don't store data outside of the volume (like database server configuration and so on).

I'll close this since volumes are going to be improved and this was a question. Please feel free to continue the discussion.
