### ISSUE TITLE
1.6 + DIND + Pid Host == Container Serial Killer

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#12015]
I've been troubleshooting this issue for a bit and managed to get a small test case for it.  Basically if you are running Docker as PID 1 (for example Docker in Docker) and you use `--pid=host`, it will fail.  I don't really know why though.  I have confirmed that this does work in Docker 1.5 just fine.  You can see in the script below that if you uncomment the line that downloads the current Docker, and run it, everything works.

What seems to happen is that when Docker launches the container PID, which is a reexec of Docker itself to the "initializer" that process just dies immediately.  Something is very quickly killing the process.  What or how I don't know.  You can see in the Docker daemon output `level=warning msg="signal: killed"`.  This is getting returned from https://github.com/docker/docker/blob/b9be50b578f86e858113b9c334e1748e15b63263/vendor/src/github.com/docker/libcontainer/container_linux.go#L102.  I've put printf statements all through out the initializer code and basically it's not even getting into the main process really.

I changed the Docker code and made it so that it always passed NEWPID to the clone flags and then things worked.  Which is obviously a stupid change, but the point being that its the mere absence of NEWPID on the clone flags that is causing this issue.  Now that I have a smaller test case I'll probably continue to debug this, but please help me because this one is just odd to me.  Does docker have some signal handler that is accidentally getting triggered and then it just kills the container??

Again, this only happens when Docker is PID 1.  If you change the script below and remove "exec", everything will work just fine.

Test case below:

```bash
#!/bin/bash

curl https://test.docker.com/builds/Linux/x86_64/docker-1.6.0-rc2 > docker
#curl https://get.docker.com/builds/Linux/x86_64/docker-latest > docker

cat > docker.sh << "EOF"
#!/bin/bash
mkdir -p /sys/fs/cgroup
mount -t tmpfs none /sys/fs/cgroup

for i in perf_event net_cls freezer devices blkio memory cpuacct cpu cpuset; do
mkdir -p /sys/fs/cgroup/$i
    mount -t cgroup -o $i none /sys/fs/cgroup/$i
done

exec docker -d -s overlay -H 0.0.0.0:1234
EOF

cat > Dockerfile << "EOF"
FROM debian:jessie
RUN apt-get update && apt-get install -y iptables
RUN apt-get install -y ca-certificates
COPY docker /usr/bin/docker
COPY docker.sh /docker.sh
CMD ["/docker.sh"]
EOF

chmod +x docker docker.sh
docker build -t test .
docker run --privileged -p 1234:1234 test &
sleep 2 # because 2 is better than 1

docker rm -f test
docker -H 0.0.0.0:1234 run -i --pid=host busybox echo please work

```

**Comment by ibuildthecloud** [comment]
https://www.youtube.com/v/aEQw79tKm6I&start=39&end=48

@jfrazelle @icecrime I think this should be in 1.6

@LK4D4 @crosbymichael please help :)

Like batman, I need a light I can shine in the sky and then the core Docker team comes running to the rescue.

**Comment by LK4D4** [comment]
@ibuildthecloud Thank you very much for reproduction case. I'll try to fix tomorrow.

**Comment by icecrime** [comment]
![](https://i.imgflip.com/jnqn1.jpg)

**Comment by jfrazelle** [comment]
omg this image

**Comment by crosbymichael** [comment]
DARREN!!!!

**Comment by thaJeztah** [comment]
Is it a bird? Is it a plain? :smile:

@ibuildthecloud (you probably tried this, but..) I see the repro-case is on 1.6-rc2; rc3 was also released yesterday, not sure if anything was changed in that that resolves this?

**Comment by jfrazelle** [comment]
nah its still there

**Comment by thaJeztah** [comment]
Thanks @jfrazelle ...just stating the obvious; ya never know

**Comment by crosbymichael** [comment]
@ibuildthecloud what's yo kernel version?
