### ISSUE TITLE
docker search gives no route to host

### ISSUE THREAD

**Issue by sainath14** [docker/docker#12013]
if i do docker search ubuntu, i get the following

DEBU[7156] Calling GET /images/search                   
INFO[7156] GET /v1.17/images/search?term=ubuntu         
INFO[7156] +job search(ubuntu)                          
INFO[7156] +job resolve_repository(ubuntu)              
INFO[7156] -job resolve_repository(ubuntu) = OK (0)     
DEBU[7156] pinging registry endpoint https://index.docker.io/v1/ 
DEBU[7156] attempting v1 ping for registry endpoint https://index.docker.io/v1/ 
DEBU[7156] Index server: https://index.docker.io/v1/    
DEBU[7156] https://index.docker.io/v1/search?q=ubuntu -- HEADERS: map[User-Agent:[docker/1.5.0 go/go1.4.1 git-commit/833c62e kernel/3.19.2-rancher os/linux arch/amd64]] 
DEBU[7156] hostDir: /etc/docker/certs.d/index.docker.io 
Get https://index.docker.io/v1/search?q=ubuntu: dial tcp 162.242.195.84:443: no route to host
INFO[7174] -job search(ubuntu) = ERR (1)                
ERRO[7174] Handler for GET /images/search returned error: Get https://index.docker.io/v1/search?q=ubuntu: dial tcp 162.242.195.84:443: no route to host 
ERRO[7174] HTTP Error: statusCode=500 Get https://index.docker.io/v1/search?q=ubuntu: dial tcp 162.242.195.84:443: no route to host 
FATA[0018] Error response from daemon: Get https://index.docker.io/v1/search?q=ubuntu: dial tcp 162.242.195.84:443: no route to host

**Comment by Pensu** [comment]
Can you ping index.docker.io? May be, there is some issue with your internet connection.

**Comment by allencloud** [comment]
There may be something wrong with own  route

**Comment by sainath14** [comment]
i was able to do nslookup on index.docker.io and it returns the IP

**Comment by dmp42** [comment]
You have issues with your network.
Try to `curl https://162.242.195.84/` from where your docker daemon lives.

**Comment by anroots** [comment]
Happening for me, too.

```
$ docker search ubuntu                             
FATA[0000] Error response from daemon: Get https://index.docker.io/v1/search?q=ubuntu: dial tcp 162.242.195.84:443: no route to host
```

I'm behind a proxy.

```
$ env | grep proxy
no_proxy=localhost,docker-registry.local,/var/run/docker.sock
https_proxy=http://proxy.local:3128
socks_proxy=socks://proxy.local:3128/
http_proxy=http://proxy.local:3128
```

`/etc/default/docker` contains the following:

```
DOCKER_OPTS="--dns 192.168.0.252 --dns 192.168.0.253 --dns 8.8.8.8 --dns 8.8.4.4"
 
export http_proxy='http://proxy.local:3128'
export https_proxy=$http_proxy
export no_proxy="docker-registry.local"
```

Curl from the terminal works.

```
$ curl https://index.docker.io/v1/search\?q\=ubuntu
```

**Comment by sainath14** [comment]
In my case, this is inconsistent. It works fine all of a sudden.
Is this the issue with connecting to docker registry?
