### ISSUE TITLE
Make /tmp really temporary

### ISSUE THREAD

**Issue by mingfang** [docker/docker#12014]
Building images sometimes leaves scratch files in the /tmp directory.
In addition sometimes I need to ADD my project's source code during a build, but I don't want the source to remain after the build.
By making /tmp temporary, then I can do simply ADD src /tmp/src.

**Comment by phemmer** [comment]
I think #10310 accomplishes what you're after.

**Comment by mingfang** [comment]
That sounds more sophisticated then what I need.
I just wanted /tmp to behave "normal"; /tmp on Linux do not survive a reboot.
The ability to ADD src there for building is just an additional benefit.

**Comment by phemmer** [comment]
On my distro, `/tmp` does survive a reboot. This would not be "normal" from my perspective.
Also, if `/tmp` is made to not survive outside the container, this wouldn't work for builds. During builds, each command in the `Dockerfile` is its own container. Thus the data would be gone on the next command.

**Comment by mingfang** [comment]
Based on the comments here I'm closing this issue.
I also created a new issue to specifically address the ability to avoid source code to end up in a layer, https://github.com/docker/docker/issues/12169
