### ISSUE TITLE
Online docs for working on an issue have a typo in git fetch command

### ISSUE THREAD

**Issue by reteptilian** [docker/docker#12028]
Description of problem:

http://docs.docker.com/project/work-issue/#pull-and-rebase-frequently has a typo in the fetch command.

It says to:

$ git fetch upstream/master

This command does not work.  The slash should be a space.

**Comment by duglin** [comment]
@reteptilian good catch - will fix

**Comment by duglin** [comment]
It looks like this has been fixed: https://github.com/docker/docker/blob/master/docs/sources/project/work-issue.md   just not visible yet on the web site.  But thanks for being so thorough!

**Comment by reteptilian** [comment]
ok thanks @duglin!  Next time I'll know to check the sources on github ...
