### ISSUE TITLE
Docker Build Documentation Needs Update

### ISSUE THREAD

**Issue by amouat** [docker/docker#12021]
The documentation on the build command at:

https://docs.docker.com/reference/commandline/cli/#build

Doesn't mention `-f`. 

Not sure if this is the right place to mention documentation problems, please let me know if there's a different place for those.

**Comment by duglin** [comment]
If you look at the latest version of the docs: https://github.com/docker/docker/blob/master/docs/sources/reference/commandline/cli.md  you'll see `-f` mentioned. Not sure how long it will be before the web site is updated though.  @moxiegirl perhaps you know?

Closing this as I think its resolved - just need an estimate on when the site will be refreshed.

**Comment by amouat** [comment]
Cool, sorry for wasting your time. I'll check the source version next time.

**Comment by thaJeztah** [comment]
@amouat there's also http://docs.master.dockerproject.com, which always has the current "master" of the documentation.
