### ISSUE TITLE
Document the fact that SIGINT/control-C doesn't usually kill a container

### ISSUE THREAD

**Issue by bboreham** [docker/docker#12022]
For the reasons discussed at #3793, the signal will be passed to the container but in many cases it won't actually terminate because it is running as PID 1.

I could not find any mention of this in any of the documentation for `-sig-proxy`, `docker kill`, etc., which is where I looked to try to understand why it wasn't working for me.

https://bugzilla.redhat.com/show_bug.cgi?id=1189865 has a nice example to experiment with.

**Comment by thaJeztah** [comment]
Hi, @bboreham did you have something in mind (where to add it in the docs)? Perhaps you are willing to contribute a pull-request?

/cc @moxiegirl (for docs)
