### ISSUE TITLE
docker exec command not executing in sh file

### ISSUE THREAD

**Issue by ramprakash-ravi** [docker/docker#12024]
When running below command in command line(terminal) this gets executed fine:

$sudo docker exec -it 5570dc09b58 bash

But same results with : FATA[0000] cannot enable tty mode on non tty input Error when running in a shell script file.

**Comment by phemmer** [comment]
The message is fairly clear. You can't enable TTY input mode if docker doesn't have a TTY.
I'm not sure exactly what you're trying to accomplish, but you probably want to remove the `-i`. If not, can you please provide more information (context) about what you're trying to do (e.g. the end goal, the exact command you're running, etc)?

**Comment by ramprakash-ravi** [comment]
@phemmer 

I am trying to execute the above command to move to the currently running container root path. I have removed -i and executed. Kindly let me know how to run that as a cron job? What will be the path for running the cron job.

**Comment by thaJeztah** [comment]
I'm gonna close this issue, because there's currently not enough information to act on. Feel free to "ping" me if you have more information and think this should be reopened.

Also, https://github.com/docker/docker/issues/8755 may contain some useful information
