### ISSUE TITLE
Is there more details about Docker networking plugin

### ISSUE THREAD

**Issue by fmzhen** [docker/docker#12030]
The network function of Docker is not perfect.There are some demands not be met. For example

1. The container’s IP is not fixed, it will change if the container restart.
2. We can't assign a specific IP/Gateway to a container, or get an IP from DHCP server.
3. Multi-host networking、Multi-tenant 、OVS、QoS/ACL and other advanced features are not supported.

There also are some PRs to solve these problems,like #7436 #5829 . However they were all rejected. 

Finally, it is said that Plugin architecture will provide a powerful way to extend Docker's Networking functionality. However, in addition to the #9983, there are no more information about networking plugin.According to the #9983 ,many things (API、flags、service discovery) are not  determined.And people also have some  questions on that proposal.

I have a strong wish to make a contribution to Docker's networking. However, #9983 and the repository docker/docker-network have not updated for a long time. So is there more detailed information about the docker networking plugin to instruct me how to do it?

**Comment by thaJeztah** [comment]
I think there's a proposal being prepared currently for a Docker plugin system (including network plugins) by a workgroup consisting of people from Docker and various representatives in the "Docker ecosphere".

Possibly @cpuguy83 is able to provide more information on that.

Also, this may be of interest to you (in case you missed the announcement);

http://blog.docker.com/2015/03/socketplane-excited-to-be-joining-docker-to-collaborate-with-networking-ecosystem/

**Comment by duglin** [comment]
I'm going to close this as there's not anything actionable from this that we can do.  For questions like this I would suggest asking on the mailing list or IRC.
