### ISSUE TITLE
Miscellenous devicemapper graphdriver cleanup

### ISSUE THREAD

**Issue by rhvgoyal** [docker/docker#12032]
There are some issues I noticed in devicemapper graph driver.

- libdm logging is too verbose when daemon is running in debug mode. If a device can't be deleted too many messages are pushed into journal and one can not figure out what's going on.

- Usage of "defer UdevWait(cookie)" is buggy.

- I think waitRemove() and waitClose() functions are unnecessary.

- If device removal fails, we retry every 10ms for up to 10 seconds. That's 1000 retries. Sounds a lot. Trying probably every 100ms is better.

**Comment by vdemeester** [comment]
According to  #12033 this one might be closeable too :wink:

**Comment by thaJeztah** [comment]
Thanks @vdemeester looks like I'm lagging behind since my vacation :)
