### ISSUE TITLE
Fix logDone format

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#12042]
drives me nuts... fix the integration tests here so `rmi - suff` some are `rmi- stuff`

we need a space between the `-`

```
[PASSED]: rmi- container using image while rmi, should not remove image name
[PASSED]: rmi - tag,rmi- tagging the same images multiple times then removing t
[PASSED]: rmi - delete tag with existing containers
[PASSED]: rmi - force delete with existing containers
[PASSED]: rmi - delete a image which its dependency tagged to multiple reposito
[PASSED]: rmi- blank image name
```

**Comment by estesp** [comment]
@kostickm - this looks like a good one if you don't mind taking it.  Otherwise we can "un-claim" it if you find another starting point!

**Comment by thaJeztah** [comment]
@kostickm are you planning on giving this a go? (Which would be awesome), otherwise let us know, then we can "un-claim" it :)

**Comment by plentz** [comment]
btw, if @kostickm doesn't want it, I want to call dibs :)

**Comment by thaJeztah** [comment]
@plentz I'd say; go for it! if you want to start contributing on docker (which is awesome). Make sure you mention `closes #12042` in the description (not the title) of your pull-request.

@kostickm let us know if you're still looking for something to work on, I'm sure there are other simple issues to get you started.

**Comment by duglin** [comment]
@thaJeztah let's give @kostickm a little more time to speak up - will push on this today.

**Comment by thaJeztah** [comment]
Alright, @plentz, want to hold of with your PR? (Sorry for this)

**Comment by kostickm** [comment]
Yep I am planning on working through it today! Sorry for the delay.

**Comment by kostickm** [comment]
#dibs

**Comment by plentz** [comment]
@thaJeztah no problem, I will take another one ;)
