### ISSUE TITLE
Docker info number of containers is perhaps misleading

### ISSUE THREAD

**Issue by aetherical** [docker/docker#12045]
`docker info` returns the count of containers (ps -a), not the current number of running containers (ps). This could be considered misleading, particularly if using swarm to get information about the servers in the swarm.

I think that there is value in the number, but perhaps something as simple as documenting what info returns would alleviate the potential for misleading users.

I'd be happy to  add a description of what info returns to the docs if people think that's the best decision.

Thanks!

**Comment by duglin** [comment]
It might be good to have `docker info` return the number of containers as: `4/8` - showing there are 8 total, but only 4 running.

**Comment by aetherical** [comment]
@duglin I think that's a good idea; I wonder if it will break any existing programs (that are parsing info).

**Comment by duglin** [comment]
probably  :-)  but I've heard conflicting statements about whether its ok to change the output from our CLI. Will need @crosbymichael to weigh in here.

**Comment by abronan** [comment]
I opened a proposal in #15639 before stumbling upon this issue, my bad..

The output is more complex though and I also like @duglin's proposal on the short `X/Y` output.

Might not be useful to track this proposal in two separate issues, @aetherical really sorry about this but are you OK with closing this one and continue the discussion in #15639? This should help getting this under the radar.

**Comment by aetherical** [comment]
Yes, sounds good.
