### ISSUE TITLE
Error in the last example of userguide/dockervolumes

### ISSUE THREAD

**Issue by eluck** [docker/docker#12052]
In the last example of [userguide/dockervolumes](http://docs.docker.com/userguide/dockervolumes/) we want to restore backed up data into a `dbdata2` container:

```
sudo docker run -v /dbdata --name dbdata2 ubuntu /bin/bash
sudo docker run --volumes-from dbdata2 -v $(pwd):/backup busybox tar xvf /backup/backup.tar
```

This snippet has 2 issues:

1. If we dig into the logic of the snippet, we'll see that restored data should get into `/dbdata` directory of `dbdata2` container. Instead the data is left in `/` directory of a temporary container. The second line should like this:

  ```
  sudo docker run --volumes-from dbdata2 -v $(pwd):/backup busybox cd /dbdata && tar xvf /backup/backup.tar
  ```
  (Added `cd /dbdata && `)

2. As it was previously stated in the userguide, we'd like to use the same base containers for most operations to reduce network and disk usage. So that in the second line `busybox` should be replaced by `ubuntu`. Though considering the size of busybox this may be not a very serious issue :smile:.

**Comment by thaJeztah** [comment]
Closing, because https://github.com/docker/docker/issues/12054 was merged.

Thanks @eluck!
