### ISSUE TITLE
ADD does not respect WORKDIR directive in Dockerfile

### ISSUE THREAD

**Issue by zrml** [docker/docker#12056]
in my Dockerfile I do:
--
VOLUME /distrib
WORKDIR /distrib
ADD my_file.tar.gz .
ADD install-manifest.sh .  
--
the above last steps consistently fails with: "install-manifest.sh: not a directory"
Considerations: 
the ADD tar.gz is OK. Why shoudl it be?
I am indeed passing a second argument to my second ADD: it's the dot at the end which should respect the previous WORKDIR /distrib command.

do we have a problem here or is it me not understanding WORKDIR?

thank you very much for your time.
--

the solution is to "hardcode" /distrib/       # and don't forget the last forward slash! :)

**Comment by duglin** [comment]
The issue isn't WORKDIR but instead your ADD.  If you look at the docs at: https://docs.docker.com/reference/builder/#add  you'll see that the destination must end with a / if you don't want it to treat the '.' as a file. Make it `ADD myfile.tar.gz ./` and I think it should work.

**Comment by zrml** [comment]
@duglin: you stand correct. Indeed it work. Thank you.
