### ISSUE TITLE
compression during docker push

### ISSUE THREAD

**Issue by fommil** [docker/docker#12053]
I have a virtual image in my docker image of about 6GB and I am pretty sure that docker push is **not** using wire compression when uploading it to the docker hub because it is *really* slow. Tests with uploading the same file (but compressed) in the container are much faster. I'm pretty sure the increased upload times are causing me more `EOF` pain than normal (transient failures to push due to I/O error).

Once uploaded, pulling seems to be using compression ok because the layer size is reported to be much smaller than its real contents.

Some related tickets:

* https://github.com/docker/docker/issues/1266
* https://github.com/docker/docker/issues/194

**Comment by cpuguy83** [comment]
@fommil Please see #11869 which was merged for 1.6
All V2 registry pushes should be compressed.

**Comment by fommil** [comment]
oh, awesome!
