### ISSUE TITLE
/etc/hosts in one container doesn’t update if linked container restarts

### ISSUE THREAD

**Issue by stapelberg** [docker/docker#12067]
On https://docs.docker.com/userguide/dockerlinks/#updating-the-etchosts-file I can read:

> If you restart the source container, the linked containers /etc/hosts files will be automatically updated with the source container's new IP address, allowing linked communication to continue.

However, I cannot get this to work. I’m setting up a container named “target”:

```
$ docker run --rm -t -i --entrypoint=/bin/bash --name target debian:wheezy
root@0262e58b36a7:/# ip -4 a s dev eth0
128: eth0: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP 
    inet 172.17.0.63/16 scope global eth0
       valid_lft forever preferred_lft forever
```

And then, in another terminal, I’m creating another container which is linked to “target”:

```
$ docker run --rm --link target:target -t -i --entrypoint=/bin/bash debian:wheezy
root@f754f6367d8c:/# cat /etc/hosts
172.17.0.64	f754f6367d8c
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.63	target
root@f754f6367d8c:/# ping target
PING target (172.17.0.63): 48 data bytes
56 bytes from 172.17.0.63: icmp_seq=0 ttl=64 time=0.117 ms
^C--- target ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.117/0.117/0.117/0.000 ms
```

Okay, this worked as expected. Now let’s destroy “target” and start it up again:

```
root@0262e58b36a7:/# exit
exit
 $ docker run --rm -t -i --entrypoint=/bin/bash --name target debian:wheezy
root@4169f06d1b93:/# ip -4 a s dev eth0
132: eth0: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP 
    inet 172.17.0.65/16 scope global eth0
       valid_lft forever preferred_lft forever
root@4169f06d1b93:/# 
```

But, contrary to what the docs say, `/etc/hosts` is not updated and networking broke:

```
root@f754f6367d8c:/# cat /etc/hosts
172.17.0.64	f754f6367d8c
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.63	target
root@f754f6367d8c:/# ping target
PING target (172.17.0.63): 48 data bytes
^C--- target ping statistics ---
2 packets transmitted, 0 packets received, 100% packet loss
```

What am I doing wrong?

This is on Fedora 21 with docker version:
```
$ docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.3.3
Git commit (client): a8a31ef/1.5.0
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.3.3
Git commit (server): a8a31ef/1.5.0
```

**Comment by LK4D4** [comment]
@stapelberg If you destroy container - link will be lost. It updates IP only on restarts.

**Comment by stapelberg** [comment]
@LK4D4 Ugh, okay. Maybe this could be pointed out more clearly in the documentation. Could we also turn this into a feature request for making links persist across destroying/recreating a container, i.e. making the link only depend on the name?

**Comment by smitec** [comment]
+1 for links being name related, especially as names are forced to be unique. I wrote a workaround that edits `/etc/hosts` manually in the mean time. https://github.com/smitec/docker-hotswap

**Comment by thaJeztah** [comment]
I think this is a dup of https://github.com/docker/docker/issues/10066 (and others). Links will be replaced by the new networking system, which can currently be found in the experimental builds, and offer far more flexibility. "services" will replace the existing "links" (also see https://github.com/docker/docker/issues/10066#issuecomment-123548512))

A detailed description of the new networking features can be found here; https://github.com/docker/docker/blob/master/experimental/networking.md


I'm going to close this issue for that reason, but feel free to comment here after I've closed.
