### ISSUE TITLE
Carry -- Update to Joyent Install Doc #11687

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#12062]
I'm gong to pick this up after the release...also...I'm not sure how this fits with the recent commentary coming in on Joyent installation.

**Comment by fredlf** [comment]
I guess checking in with @shykes is in order!

**Comment by LK4D4** [comment]
@thaJeztah should this be closed?

**Comment by vdemeester** [comment]
Pretty sure we do, the `joyent.md` file doesn't exists anymore :sweat_smile:
