### ISSUE TITLE
Automatically created host directories for mounts take permissions for daemon umask

### ISSUE THREAD

**Issue by abierbaum** [docker/docker#12061]
This was a bit of a surprise for me but may be the way it is expected to work.  If you use docker run to start a container with a volume mount to a host directory that doesn't exist, docker will create it automatically.  The surprising part is that this directory is created with the permissions and ownership of the docker daemon.  (ie. not of the account currently running the docker command)

For example:

```
~# id
uid=0(root) gid=0(root) groups=0(root)
~# umask
0022
~# pwd
/root
~# ls -al
drwx------ 12 root root 4096 Oct 16 11:33 .
drwxr-xr-x 27 root root 4096 Mar  9 19:19 ..
~# docker run --rm -v /root/first_dir:/mnt ubuntu date
Fri Apr  3 19:03:28 UTC 2015
~# ls -al
drwx------ 13 root root 4096 Apr  3 14:03 .
drwxr-xr-x 27 root root 4096 Mar  9 19:19 ..
drwxr-xr-x  2 root root 4096 Apr  3 14:03 first_dir
~# umask 077
~# docker run --rm -v /root/second_dir:/mnt ubuntu date
Fri Apr  3 19:03:53 UTC 2015
~# ls -al
total 68
drwx------ 14 root root 4096 Apr  3 14:03 .
drwxr-xr-x 27 root root 4096 Mar  9 19:19 ..
drwxr-xr-x  2 root root 4096 Apr  3 14:03 first_dir
drwxr-xr-x  2 root root 4096 Apr  3 14:03 second_dir
``` 

That this means is that if you want to set the permissions of the host directory, you must created it explicitly before running docker.  Not sure if this should be changed, but it may be useful to allow users to pass an option to docker run to set the permissions (and ownership?) of the host directory that docker is creating for them.

**Comment by cpuguy83** [comment]
This is 100% expected, the only thing I can think of changing is if Docker is actually creating the dir, it might auto-populate the dir with content from the container and set ownership based on that.

**Comment by thaJeztah** [comment]
Hi, @abierbaum I'm going to close this issue as this is expected behavior. There is an existing feature request for specifying uid/gid on volumes here; https://github.com/docker/docker/issues/7198. Please continue the discussion on https://github.com/docker/docker/issues/7198, thanks!
