### ISSUE TITLE
Proposal: docker exec should work in "stopped" container

### ISSUE THREAD

**Issue by thefallentree** [docker/docker#12077]
Often in the time that I found I very much want the ability to get a shell in a "stopped" container , because I need to view the files, do some changes etc.  

Currently I don't' think there is a easy way to do it, other than going to /var/lib/docker/aufs/mnt directly.

Thanks

**Comment by dreamcat4** [comment]
+1

Yes, and without creating a new container, or changing the CMD/ENTRYPOINT.

**Comment by LK4D4** [comment]
In current design it is impossible, because actually container doesn't exits when it stopped. All namespaces and cgroups created only when container starts.

**Comment by grange74** [comment]
@LK4D4 while i think this was a good idea, since it is unlikely to be implemented anytime soon due to requiring major design changes, can i suggest closing this issue?
(via [codetriage](http://www.codetriage.com/docker/docker))

**Comment by thefallentree** [comment]
I realize the goal can be simplified to just automatically chroot to the containers file system. is that achievable?

**Comment by LK4D4** [comment]
@thefallentree Seems like super-hacky solution, which violates all other docker ideas. You can do chroot yourself without docker, of course.

**Comment by jfrazelle** [comment]
closing see the reason why in the roadmap https://github.com/docker/docker/blob/master/ROADMAP.md#21-docker-exec
