### ISSUE TITLE
setting /etc/hostname in --net="host" 

### ISSUE THREAD

**Issue by thefallentree** [docker/docker#12076]
Hi,

I found that when running in --net="host" mode, I can't use --hostname or even manually mounting/modify the /etc/hostname in the container to have it show the cotainer ID.

I undertsand that --net=“host' defines a mode that the netwokring will be 100% same as host, but could there be a mode of --net="custom" ? to allow more customization of the container environment (without needing to be 1 of the 2 extremes)

Thanks

**Comment by xiaods** [comment]
@sunyc  could you please provide more context in this request. because hostname is relative with network infrastructure,  it don't make sense with two hostname in host mode in my option.

**Comment by sunyc** [comment]
@xiaods 

I guess it depends on what exactly your definition is for "host" mode.

For me, and my pretty simple use case, I think host mode literally means no-proxy, sharing port mode. Now, I would like to still have a different hostname inside the container.

Obviously, I'm not trying to convince you to change the definition of host mode, or to add a new mode, I merely ask for a "custom" mode that allow mix-in of different fetaures that I want for the networking stack.

Cheers.

**Comment by cpuguy83** [comment]
@sunyc host mode literally means sharing the host's net namespace.

What is your use-case exactly?
Today you can certainly customize the container networking, but it must be totally out-of-process from Docker using tools like pipework or weave.

**Comment by sunyc** [comment]
I just want to have my process running without proxy (exposing ports
directly), yet still have a unique /etc/hostname so I / my app can easily
distinguish itself.

**Comment by cpuguy83** [comment]
You can still expose ports directly, it's just a matter of connecting to the bridge interface in the container.

**Comment by sunyc** [comment]
I don't understand what that means, can you elaborate?

**Comment by cpuguy83** [comment]
Each container gets it's own network interface, this can be setup so it's reachable from outside the host with the right routing.

Alternatively you can add a macvlan interface using pipework with an IP that's available form outside the host.

**Comment by sunyc** [comment]
How is that easier than  just allow changing /etc/hostname while using
--net="host" ?

**Comment by cpuguy83** [comment]
I suppose this might work if we automatically create a new UTS namespace when --net=host and --hostname are passed in?

cc @crosbymichael

**Comment by sunyc** [comment]
The point is, I may also need to customize /etc/resolv.conf,   having
--net=host or --net=bridge is the 2 extreme , I think more customization
should be allowed, that I can just pick what i need at the moment...

**Comment by ibuildthecloud** [comment]
@sunyc With `--net=host` you can run `hostname foo` to set the hostname to foo.    You probably need NET_ADMIN capability to change it. #12185 will actually make that not possible in the future.

**Comment by jheiss** [comment]
@ibuildthecloud is correct that you can set the hostname in the container using with hostname command if the container was run with `--net=host --cap-add=SYS_ADMIN`. Note that the capability you need is SYS_ADMIN, not NET_ADMIN, per sethostname(2).

The consensus in #12185 looks to have been that `--hostname` should be allowed with `--net=host` since the default with --net=host remains that a new UTS namespace is created.

**Comment by jheiss** [comment]
Anyone have any thoughts about `--hostname` and `--net=container`? My first instinct is that `--hostname` should remain forbidden in that case, but @umitanuki left a comment on the bottom of #5857 suggesting that it be allowed.

**Comment by thomasthebaker** [comment]
Unless I've misunderstood what the fix is for, this doesn't appear to work.

I'm using Docker version 1.12.1, build 6f9534c on OSX. Running the same container turning host networking on and off appears to stop the --hostname argument from working:

$ docker run -ti --entrypoint=/bin/bash --hostname=foo local/foo:latest
[root@foo /]# cat /etc/hostname
foo

$ docker run -ti --entrypoint=/bin/bash --hostname=foo --net=host local/foo:latest
[root@moby /]# cat /etc/hostname
moby

**Comment by justincormack** [comment]
Hostname is not dependent on net namespace but on uts namespace. You can set the docker host hostname iwth `docker run --uts=host --cap-add sys_admin alpine hostname  test`

**Comment by thomasthebaker** [comment]
Ah ok, I just misunderstood what was going on.  Thanks for the quick response and explanation.
