### ISSUE TITLE
hub.docker.com - Repeated login redirects

### ISSUE THREAD

**Issue by gprasant** [docker/docker#12082]
What : Log in on hub.docker.com
Browser : Safari (v8.0.3)

## Steps
1. Go to https://hub.docker.com/account/login/ and enter uname / password and Log in. 
1. You are now on the hub.docker.com home page. 
1. Search for some package (nginx) in the search bar on top left. 

## Observed
1. You are redirected to the login page ( url : https://hub.docker.com/account/login/?next=/api/v1.1/o/authorize/%3Fscope%3Dprofile_read%2Bprofile_write%2Bemail_read%2Bemail_write%2Bchange_password%2Bevents_read%2Bevents_write%26state%3DIGavk2zb9DD1nxFYvEDOsvMsVziYxyTF%26redirect_uri%3Dhttps%253A%252F%252Fregistry.hub.docker.com%252Faccount%252Fdockerio_auth_complete%252F%26response_type%3Dcode%26client_id%3DLnEql_y.%25211%253DBcvbXhonHqRd4KY2z6xg7uT2m%2540iuX%26q%3Dnginx) 

## Expected

User should be shown the autocomplete and when he/she selects one, he/she should land on the nginx page on docker https://registry.hub.docker.com/u/library/nginx/

**Comment by jfrazelle** [comment]
Bugs about the hub need to be posted to support@docker.com or
forums.docker.com
