### ISSUE TITLE
kill command log a kill event even if the container is not running

### ISSUE THREAD

**Issue by runcom** [docker/docker#12083]
I noticed that killing a container if it exists but it's not running generate a kill event and just print the container id to stdout like everything went ok.
I don't know if it's the desired behaviour but to me it shouldn't generate that event if the container was not running. It's weird that if you try to kill an nonexistent container it gives error and, instead, it all goes well if the container is not running. What do you think?
This happens only if no signal is passed or it's a SIGKILL (event for killing a container with another signal it's not logged to events at all)

**Comment by runcom** [comment]
@ehazlett why is this labeled question? ^.^

**Comment by ehazlett** [comment]
thanks @runcom.  i tend to agree with you that a kill event to a stopped container should not generate the event.  

i labeled "question" as it needs a response for whether or not to show an event for a kill to a stopped container.

**Comment by ehazlett** [comment]
@tiborvass thoughts?

**Comment by runcom** [comment]
@ehazlett thanks! I removed the comment because I later read again and it indeed sounded like a question with WDYT

**Comment by ehazlett** [comment]
no problem!  thanks for clarifying :)
