### ISSUE TITLE
Docker Docs : Add information about configuring the docker daemon after installation

### ISSUE THREAD

**Issue by ankushagarwal** [docker/docker#12088]
All the [Installation docs](https://docs.docker.com/installation/) cover how to install docker in detail, but none of them talk about configuring the docker daemon after the installation.

There should be a short section in there describing the config process. For example, in Ubuntu, the daemon can be configured by adding options in `/etc/default/docker` and in CentOS/RHEL, the daemon can be configured by editing `/etc/sysconfig/docker`

There is [one article](https://docs.docker.com/articles/systemd/) which covers this, but it is very specific. It would be nice to have a short config article after every installation step for various Operating Systems

**Comment by ankushagarwal** [comment]
+exp/proficient
+kind/writing

**Comment by thaJeztah** [comment]
There's also the [Command line reference](https://docs.docker.com/reference/commandline/cli/#daemon) section as well, detailing the options.

Adding a section to each operating system will make it difficult to keep those in sync, but perhaps @moxiegirl has some thoughts on it?

**Comment by ankushagarwal** [comment]
@thaJeztah 
1) I was not referring to the details of the options, but documenting where to add these options.
2) It is as hard as keeping installation docs for each OS in sync. Most of the time, it just needs to list a file where options can be configured, which usually does not change for a OS, which is not hard.

**Comment by thaJeztah** [comment]
> I was not referring to the details of the options, but documenting where to add these options.

Oh, sorry, was a bit soon replying, I thought you wanted to explain the individual daemon options as well, so :+1:

**Comment by moxiegirl** [comment]
@ankushagarwal We have a goal to simplify our installation documentation.  We want to standardize on the Docker's own installation mechanism rather than documenting OS-specific package managers.  Adding information into each installation about configuring the docker service would introduce more complexity.  Not every user that is installing Docker is going to want to go straight toward configuring the service either --- maybe they are just installing it and trying it out.

I **do** think we need information on configuring the service.  How about for now we add a explicit link to the article we do have and then improve that article.  Ideally, we might have "tip sheets" for administering Docker on different OS.

Thoughts?

**Comment by ankushagarwal** [comment]
@moxiegirl : Rather than linking to the article (which is currently relevant only for CentOS running systemd, and it is already linked from the CentOS installation page [here](http://docs.master.dockerproject.com/installation/centos/#custom-daemon-options)), I would suggest adding a small section [here](http://docs.master.dockerproject.com/installation/ubuntulinux/#optional-configurations-for-docker-on-ubuntu). 

There are beginners, but then are are a lot of very advances users who want to install docker on a production box for instance. They care a lot about configuring the software they are installing. I feel that it should be harmless to add a couple of lines in the Optional Configuration Section stating where is the config file for configuring their docker daemon.

**Comment by ankushagarwal** [comment]
Or adding an Advanced section/Configuration section to the docs, as I feel that it would be very useful for people who are trying to install docker in more sophisticated environments.

**Comment by moxiegirl** [comment]
@ankushagarwal Let's add an advance section to the docs for now if you are cool with that. We actually need to have more around administrating docker.  This would be a nice addition.

**Comment by ankushagarwal** [comment]
I can add an `Advance` section to some of the installation docs sometime this week

**Comment by moxiegirl** [comment]
@ankushagarwal The advanced section should be added to this document: https://docs.docker.com/articles/systemd/ not to the installation documentation.

**Comment by thaJeztah** [comment]
The problem here is that not all distros use systemd, so configuring the daemon will be different.

**Comment by moxiegirl** [comment]
@thaJeztah  It is possible to write a section in a single document that illustrates setting this across multiple distros. That is what we are asking for in this case.  I've certainly written them in the past.  So have others:

http://blog.frd.mn/how-to-set-up-proper-startstop-services-ubuntu-debian-mac-windows/

**Comment by thaJeztah** [comment]
@moxiegirl :+1:

**Comment by ankushagarwal** [comment]
:+1:
