### ISSUE TITLE
--rm for docker stop 

### ISSUE THREAD

**Issue by zrml** [docker/docker#12091]
I'd like to be able to remove the container from the "dormant container list" (docker ps -a or -l) as I stop them. It'd be quicker when testing & trying things out.
so just like we have
docker run or build  --rm

I'd like to have
docker stop --rm

thanks

**Comment by unclejack** [comment]
There's `docker rm -f` already which accomplishes this.

Since this was a request for a feature which exists already, I'm going to close this issue. Please feel free to comment.

**Comment by zrml** [comment]
@unclejack: Thank you for cleaning up my redundant post (#12094). I had trouble with my ADSL so I ended up re-submitting it as I could not find it (in the mean time called the ISP provider for the issues etc. etc.). Apologies for this.
--

On the actual issue:  'm aware that I have the command
docker rm -f

My issue is slightly more subtle.
I do work with the: 
docker stop (because I trap SIGTERM) and bring down cleanly the database.
but THEN
I have to run 
docker rm
which as you can appreciate is another command and a pain to be perfectly honest when -if we had the flag available as suggested, would eliminate my complain and that of others and allow us to work more efficiently.
The --rm is available for build and run;
WHY should it not be available for stop?

DO you really think this in an un-reasonable request?
@runcom liked it and I'm sure others working in an iteration/agile/rebuild & test the quality of the container type environment would appreciate it.

Could we re-open this issue then?

**Comment by unclejack** [comment]
The only adequate thing to do would be to add a flag like `-s, --signal=KILL Signal to send to the container` to `docker rm` to use it together with `docker rm -f` so that clean shutdown is possible.

The `docker stop` command has nothing to do with container removal and adding `--rm` to `docker stop` isn't going to happen.

The simplest solution today would be to issue `docker kill -s TERM` and `docker rm`.

**Comment by runcom** [comment]
@unclejack may I work on what you proposed or it's just in doing by someone else?

**Comment by unclejack** [comment]
@runcom Please feel free to go ahead.

**Comment by zrml** [comment]
@unclejack I think we are not understanding each  other as I'm looking from a user ability and standardisation (other commands have the option)

Allow me to expand please:

When I run docker stop, if nobody trap it, it waits for 10 seconds and issues a SIGKILL so you flag -s does not have any meaning anyway an could be potentially confusing at least when you document it.
If I trap it (which I do, to run a shutdown) then I don't know exactly what happens. I guess you don't go into the 10 sec timeout and just make the container dormant.
All I'm saying is that -in order to be consistent, you'd be offering an extra consistent-same-name flag 
which would just do what we've all come to expect from such flags (rm, rmi). It should not be difficult to implement it in Go with the defer command. 
Alternatively I'd have to remember that when I use stop the flag is called -s. Why? Please let's keep the KISS principle

I think that this request still make sense; it is consistent to what you're offering with other commands (--rm, rmi) and does not introduce yet another flag to remember.
I understand your comment that stop has nothing to do with container removal. But then, by the same logic, shouldn't run be the same? Why do you have a run --rm=true?
Unless of course I'm missing something...

thank you for an attentive consideration.

**Comment by zrml** [comment]
@unclejack I think we are not understanding each other here :)
I'm looking at it from a user consistency point of you.

Please allow me to expand.

At the moment the stop command -if un-trapped, sends a straight SIGKILL after 10 seconds to the container so adding a -s flag could potentially be just confusing, at least when documenting it.
If one traps it (and runs an orderly app shutdown inside the container) then I presume there is no SIGKILL sent and you make the container dormant.

My argument is about consistency between the various command. Whys should I remember the -s flag for the stop?
I understand you statement that the stop has nothing to with container removal, but by the same logic, don't you think this should apply to the run command? 
Why do we have something that has nothing to do with run flags (mem, cpu etc.) but think about the "afterlife" of the container? Flexibility it's my guessed answer.
Therefore, why can we not have the same flexibility & consistency (rm, rmi) vs inventing a new flag?
I would like to see Docker adhere to the KISS principle.
It should not be difficult to implement with Go defer or whatever.

Unless I'm missing something (possible!) I think my request still holds some value.
