### ISSUE TITLE
docker top --rm enhancement

### ISSUE THREAD

**Issue by zrml** [docker/docker#12094]
I'd like to be able to remove the container from the "dormant container list" (docker ps -a or -l) as I stop them. It'd be quicker when testing & trying things out.
so just like we have
docker run --rm

I'd like to have
docker stop --rm

**Comment by runcom** [comment]
I like this +1! I'm always trying things out with `-d` and then I'm always there stopping and deleting them in two commands. I'll also gladly work on this if it's something docker may implement.

**Comment by runcom** [comment]
#12098

**Comment by unclejack** [comment]
@zrml As you've been told on #12091, `docker rm -f` accomplishes the exact same thing - it stops a running container and removes it immediately.

I'm going to close this issue now because this feature exists already.
