### ISSUE TITLE
why app always make zombie processing in docker

### ISSUE THREAD

**Issue by rfyiamcool** [docker/docker#12096]
why app always make zombie processing in docker?

ps aux

root     10300 77.6  0.0 170008 45640 ?        R    07:09   0:02 master: extractor
root     10305 87.0  0.0 169224 44612 ?        R    07:09   0:01 master: extractor

**Comment by Xe** [comment]
http://en.wikipedia.org/wiki/Zombie_process may help you understand what is going on

**Comment by cpuguy83** [comment]
If you spin up processes in a container processes in your container and don't wait for do a `waitpid` on them, it will create a zombie.
You can handle this by either calling `waitpid` on your sub-processes, or by using a real init inside your container as pid 1... either way though, you should be using `waitpid` when spinning up a sub-process.

**Comment by Xe** [comment]
for a one-step fix: http://phusion.github.io/baseimage-docker/
