### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by Jaanki** [docker/docker#12106]
Hi
I have just installed docker using
    wget -qO- https://get.docker.com/ | sh 
on Ubuntu 14.04.
    $ sudo docker version
    Client version: 1.5.0
    Client API version: 1.17
    Go version (client): go1.4.1
    Git commit (client): a8a31ef
    OS/Arch (client): linux/amd64
    Server version: 1.5.0
    Server API version: 1.17
    Go version (server): go1.4.1
    Git commit (server): a8a31ef

search or pull requests give connection reset by peer error.

    $ sudo docker search ubuntu
    Error response from daemon: Get https://index.docker.io/v1/search?q=ubuntu: read tcp 162.242.195.84:443: connection reset by peer

I googled and added 162.242.195.84 *.docker.io to /etc/hosts file, restarted docker daemon yet the error is still there. 
I can ping 162.242.195.84. curl https://index.docker.io/v1/search?q=ubuntu replies with the image information.

**Summary**: unable to search images; connection reset by peer

**Proposed solution**:

try again to see if was perhaps a network blip.  if not, troubleshoot network access.

**Comment by ehazlett** [comment]
@Jaanki sorry you are having issues!  this appears to be network related.  would you mind trying again (removing your local `/etc/hosts` entries) and see if the issue persists? 

if the issue continues, could you run a traceroute to see where it is getting hung up?

**Comment by Jaanki** [comment]
Hi
Tried again with following two changes. Error persists.
1. /etc/hosts
#127.0.0.1	     localhost
127.0.1.1	            controller_1
162.242.195.84  *.docker.io

/etc/hosts
127.0.0.1	              localhost
127.0.1.1	              controller_1
#162.242.195.84  *.docker.io

$ traceroute 162.242.195.84
traceroute to 162.242.195.84 (162.242.195.84), 30 hops max, 60 byte packets
 1  Private IP
 2  Private IP
 3  14.140.152.41 (14.140.152.41)  7.895 ms  7.916 ms  8.124 ms
 4  115.114.76.226 (115.114.76.226)  7.896 ms  8.324 ms  8.313 ms
 5  172.29.211.217 (172.29.211.217)  37.438 ms  37.466 ms  37.448 ms
 6  180.87.38.5 (180.87.38.5)  31.049 ms *  34.051 ms
 7  80.231.217.17 (80.231.217.17)  154.483 ms  152.450 ms  147.844 ms
 8  80.231.217.6 (80.231.217.6)  159.410 ms  155.441 ms  151.094 ms
 9  80.231.154.17 (80.231.154.17)  148.884 ms  145.564 ms  148.857 ms
10  80.231.153.66 (80.231.153.66)  145.776 ms  150.025 ms  155.585 ms
11  4.69.146.219 (4.69.146.219)  224.610 ms  224.460 ms  224.564 ms
12  4.69.146.219 (4.69.146.219)  229.826 ms  232.963 ms  231.105 ms
13  4.31.104.6 (4.31.104.6)  241.899 ms  244.964 ms  257.881 ms
14  * 10.25.2.71 (10.25.2.71)  245.044 ms *
15  69.20.2.169 (69.20.2.169)  242.169 ms  241.601 ms 69.20.2.165 (69.20.2.165)  237.891 ms
16  69.20.2.99 (69.20.2.99)  229.433 ms 69.20.2.97 (69.20.2.97)  233.723 ms  230.685 ms
17  69.20.3.113 (69.20.3.113)  222.696 ms 69.20.3.117 (69.20.3.117)  237.485 ms 69.20.3.113 (69.20.3.113)  233.269 ms
18  *.docker.io (162.242.195.84)  226.329 ms  239.706 ms  236.447 ms

This happens when I am using search and pull commands from Office network. At home, I dont face these issues and everything works smoothly.

**Comment by Pensu** [comment]
I get timeout error sometime in the same manner.  http://stackoverflow.com/questions/28884488/cannot-download-docker-image-from-repository

**Comment by nerdalert** [comment]
Hi Jaanki, might be worth comparing the latency between your home network and office network. The latency on the trace route you pasted is on the high side. Also comparing a speed test online between the two sites may help narrow it down and have data to escalate to your provider about. I chime in as I can have some slow Inet access at times and empathize with you :)
Regards,

**Comment by Jaanki** [comment]
Speed in the office would definitely be higher than the wi-fi I use at home. Could this be because in office I am behind a firewall?

**Comment by cpuguy83** [comment]
Thanks for the report, however I'm going to close as this doesn't look like an issue.
If you are still having problems, please see #docker on IRC, the docker-user mailing list, or forums.docker.com

Thanks!
