### ISSUE TITLE
Meet some problem for the first time

### ISSUE THREAD

**Issue by arcticlion** [docker/docker#12104]
root@vpn:~# docker run hello-world
FATA[0000] Cannot connect to the Docker daemon. Is 'docker -d' running on this host? 
root@vpn:~# docker -d
INFO[0000] +job serveapi(unix:///var/run/docker.sock)   
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
INFO[0000] +job init_networkdriver()                    
INFO[0000] -job init_networkdriver() = OK (0)           
INFO[0000] WARNING: Your kernel does not support cgroup swap limit. 
INFO[0000] Loading containers: start.                   

INFO[0000] Loading containers: done.                    
INFO[0000] docker daemon: 1.5.0 a8a31ef; execdriver: native-0.2; graphdriver: aufs 
INFO[0000] +job acceptconnections()                     
INFO[0000] -job acceptconnections() = OK (0)

**Comment by runcom** [comment]
@arcticlion could you add more information about the problem you are experiencing? Seems like you tried to run docker without the daemon started, then you started it and then....?

**Comment by arcticlion** [comment]
@runcom 

OS is Ubuntu 14.04

root@vpn:~# uname -r
3.13.0-37-generic

First, I get the latest Docker package.

    wget -qO- https://get.docker.com/ | sh

Then
```
root@vpn:~# ps aux | grep docker
root     16731  0.0  0.1  11756   932 pts/3    S+   19:35   0:00 grep --color=auto docker
root@vpn:~# docker run hello-world
FATA[0000] Cannot connect to the Docker daemon. Is 'docker -d' running on this host? 
```

**Comment by runcom** [comment]
@arcticlion from your ps aux output docker is not running at all. Try running service docker start before trying to run hello-world

**Comment by arcticlion** [comment]
@runcom 
```
root@vpn:~#  service docker start
docker start/running, process 17131
root@vpn:~# ps aux | grep docker
root     17131  0.6  1.6 125176  8284 ?        Ssl  19:50   0:00 /usr/bin/docke -d
root     17171  0.0  0.1  11756   936 pts/3    S+   19:50   0:00 grep --color=auto docker
root@vpn:~# docker run hello-world
Unable to find image 'hello-world:latest' locally
511136ea3c5a: Pull complete 
31cbccb51277: Pull complete 
e45a5af57b00: Pull complete 
hello-world:latest: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Status: Downloaded newer image for hello-world:latest
Hello from Docker.
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (Assuming it was not already locally available.)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

For more examples and ideas, visit:
 http://docs.docker.com/userguide/
root@vpn:~# docker run -it ubuntu bash
Unable to find image 'ubuntu:latest' locally
f3c84ac3a053: Downloading 7.994 MB/197.2 MB 13m38s
a1a958a24818: Verifying Checksum 
9fec74352904: Verifying Checksum 
d0955f21bf24: Download complete 
511136ea3c5a: Already exists 
```

**Comment by runcom** [comment]
@arcticlion perfect, it's working then, even if I don't understand why the docker daemon was not started after the installation

**Comment by arcticlion** [comment]
@runcom 

Is normal?

```
root@vpn:~# docker run -it ubuntu bash
Unable to find image 'ubuntu:latest' locally
f3c84ac3a053: Pull complete 
f3c84ac3a053: Download complete 
a1a958a24818: Download complete 
9fec74352904: Download complete 
d0955f21bf24: Download complete 
511136ea3c5a: Download complete 
Status: Downloaded newer image for ubuntu:latest
root@0d63996a58d8:/# docker run hello-world
bash: docker: command not found
```

**Comment by runcom** [comment]
@arcticlion yes, you are inside a container, you haven't docker installed there.

**Comment by arcticlion** [comment]
@runcom I understand what docker is little by little. I continue to read official document. Thank you for your help.

**Comment by vdemeester** [comment]
@arcticlion you might wanna close this issue then ;)
