### ISSUE TITLE
direct-lvm thin-pool fails to format/recognize filesystem type

### ISSUE THREAD

**Issue by therealromster** [docker/docker#12101]
I have just moved from direct-lvm using two different logical volumes to a thin-pool logical volume. And then this fails.

I am using :
```
$ docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.3.3
Git commit (client): a8a31eff10
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.3.3
Git commit (server): a8a31eff10

$ sudo /sbin/lvm version
  LVM version:     2.02.118(2) (2015-03-24)
  Library version: 1.02.95 (2015-03-24)
  Driver version:  4.29.0

$ uname -r
3.19.3
```

My thin-pool volume:

```
$ sudo /sbin/lvs
  LV               VG   Attr       LSize    Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  docker_thin_data data twi-a-tz--  100.00g             0.00   0.03                            
```

My docker.conf:

```
#DOCKER_OPTS="-d -p /var/run/docker.pid --storage-opt dm.basesize=50G --storage-opt dm.datadev=/dev/data/data --storage-opt dm.metadatadev=/dev/data/metadata"

DOCKER_OPTS="-d -p /var/run/docker.pid --storage-opt dm.basesize=50G --storage-opt dm.thinpooldev=/dev/mapper/data-docker_thin_data"

```

Example docker usage:
```
$ docker pull crux
511136ea3c5a: Download complete 
511136ea3c5a: Error downloading dependent layers 
12c799be149e: Downloading 4.833 MB/325 MB 10m42s
adc2a241090c: Error pulling image (latest) from crux, endpoint: https://registryadc2a241090c: Error pulling image (latest) from crux, Unknown filesystem type on /dev/mapper/docker-8:33-3858741-511136ea3c5a64f264b78b5433614aec563103b4d4702f3FATA[0015] Error pulling image (latest) from crux, Unknown filesystem type on /dev/mapper/docker-8:33-3858741-511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158 
```

Now when i was using
```
--storage-opt dm.datadev=/dev/data/data --storage-opt dm.metadatadev=/dev/data/metadata
```
It was working but I want to move the thin-pool stuff purely to the logical volume manager.

**Comment by therealromster** [comment]
I found the cause I did not rm anything in /var/lib/docker/ I was not even aware of this directory in crux linux, as it's not mentioned in

```
prt-get cat docker .footprint
```

I'll see if I can get at least a empty directory for that $PKG/var/lib/docker so I am aware of it. I would love to know which file is responsible for the back end storage layout, and why changing the options and it is not smart to realize this.

**Comment by vbatts** [comment]
so, this issue is not that the options are ignored, but rather a feature request that the defaults would not give more clear indication of prior layout vs. options provided?

**Comment by rhvgoyal** [comment]
So this is not a devicemapper issue at all then?

**Comment by rhvgoyal** [comment]
Can we either close the bug or remove the devicemapper label in that case.

**Comment by vbatts** [comment]
@therealromster perhaps you can open a request for the documentation that `prt-get` is fetching?

@thaJeztah where would documentation best go, to clarify that "changing storage driver parameters may require a clean slate of /var/lib/docker"?

I'm going to close this issue for now, as it's not so much a devicemapper issue, but potential documentation.

**Comment by rhvgoyal** [comment]
@vbatts 

Can we store the storage driver being used in "/var/lib/docker" and don't allow user to change storage
driver. Only way to change driver would be to move /var/lib/docker/ somehwere else and that should force a clean state?

**Comment by rhvgoyal** [comment]
IOW, once instance of /var/lib/docker will container data only for one graphdriver. If somebody wants to play with multiple storage driers, setup a fresh /var/lib/docker from scratch. And software will enforce it.

**Comment by vbatts** [comment]
@rhvgoyal in this situation, it's more that a storage driver will need to preserve its prior configuration, so if a flag changes (i.e. thinpooldev) then it can bail or similar.

docker already will make some automatic assumptions to use a prior storage driver when it is "guessing" which driver to use. This is more about configurations within the driver itself.

**Comment by rhvgoyal** [comment]
@vbatts 

Not allowing certain change of configuration with-in driver sounds good. Like one can not change thin pool without creating a fresh /var/lib/docker.

**Comment by vbatts** [comment]
k. i've opened https://github.com/docker/docker/issues/13807 the conversation can continue there
