### ISSUE TITLE
Rename TestStartSilentAttach to TestStartAttachSilent

### ISSUE THREAD

**Issue by LK4D4** [docker/docker#12119]
So I can run `TESTFLAGS="TestStartAttach" integration-cli` and get Attach for Start tested.

**Comment by joeygibson** [comment]
This seems like a really simple rename. Is there something more to this that I'm missing? Renaming this function results in four functions that begin with TestStartAttach, so does setting TESTFLAGS="TestStartAttach" get all that start with that?

And did you mean `TESTFLAGS="TestStartAttach" make test-integration-cli`?

**Comment by kostickm** [comment]
@joeygibson are you going to create a PR for this one? If not I'm happy to take it.

**Comment by joeygibson** [comment]
I didn't actually do any work on it, since I was waiting for an answer to my question. If you are confident that you understand the issue, go ahead and take it.

**Comment by kostickm** [comment]
@joeygibson Okay thanks! I think I have it figured out.

**Comment by kostickm** [comment]
#dibs

**Comment by runcom** [comment]
And yes @joeygibson, running that with something like `TestStartAttach` will run all functions in tests which begins with `TestStartAttach`. Just to clarify :)

**Comment by joeygibson** [comment]
That's what I thought, but when I made the change and tried to run the tests, it said something like it couldn't find a test suite with that name (I'm not at the computer where my source is). I just looked at @kostickm's commit, and that was the same thing I did. (I know I said I didn't do any work, but I meant I had not commit anything or taken it further.)
