### ISSUE TITLE
Installing docker 1.5 via curl on Debian Jessie (RC1 or RC2) results in docker daemon not starting after reboot

### ISSUE THREAD

**Issue by kwolcott-vendini** [docker/docker#12114]
When I install Docker v1.5 via the curl method "curl -sSL https://get.docker.com/ | sh" as advised at "https://docs.docker.com/installation/debian/#debian-wheezystable-7x-64-bit" for Debian Jessie (RC1 or RC2) rather than for Debian Wheezy, the docker daemon does not automatically start on reboot.

Please fix.

Thanks,
Ken Wolcott
(kwolcott@vendini.com)

**Comment by jfrazelle** [comment]
You need to systemctl enable docker, for it to automatically start on boot

On Mon, Apr 6, 2015 at 5:36 PM, Kenneth A. Wolcott <notifications@github.com

**Comment by kwolcott-vendini** [comment]
Thank you for the tip but shouldn't that step be performed by the installation of Docker?

**Comment by jfrazelle** [comment]
ping @moxiegirl we may want to add this to the docs, but users of systemd are mostly used to this, but regardless. You must `systemctl enable docker` to tell systemd you allow it to automatically be started on reboot

**Comment by jfrazelle** [comment]
@kwolcott-vendini no it should not, this is a decision the user must make. It's not fair for us to automatically do it, if the user does not want that to happen

**Comment by kwolcott-vendini** [comment]
I see.  I would think that if someone wanted to install docker that they would want the daemon to be auto-started.  I reluctantly accept this conclusion.

**Comment by kwolcott-vendini** [comment]
Please do add this to the docs.  So, the docker daemon is automatically started for Ubuntu, but not for Debian.  Seems inconsistent.

**Comment by moxiegirl** [comment]
@kwolcott-vendini You might want to jump on #12088 which is related to this.  IOW, we do intend to discuss it.
