### ISSUE TITLE
TestPullVerified failing on jenkins for windows

### ISSUE THREAD

**Issue by LK4D4** [docker/docker#12126]
Because windows build is one of PR-builds, it is pretty bad.
ping @jfrazelle @dmcgowan 
We can just skip it if nobody knows how to fix it.

**Comment by jfrazelle** [comment]
is this because of the upgrades to hub :/ why does this keep happening

**Comment by Mashimiao** [comment]
I have made a PR #12016. it seems fixing the same problem with this issue.

**Comment by LK4D4** [comment]
I don't understand fix :) Also why fail non-deterministic? ping @dmcgowan

**Comment by ahmetalpbalkan** [comment]
+1 on @LK4D4, why is this non-deterministic? Do we sometimes hit a non-v1 registry?

**Comment by thaJeztah** [comment]
For reference, the test is now temporarily skipped; see https://github.com/docker/docker/pull/12468

**Comment by LK4D4** [comment]
@thaJeztah super. I think it is proper fix.

**Comment by thaJeztah** [comment]
I'm not sure what the proper fix is, but now that I still have some logs containing the error, I copied the output, in case it's useful.

This is the output of failures on Janky:

```
--- FAIL: TestPullVerified (3.99s)
	docker_cli_pull_test.go:71: pulling a verified image failed. expected: The image you are pulling has been verified
		got: latest: Pulling from hello-world
		511136ea3c5a: Already exists
		31cbccb51277: Already exists
		e45a5af57b00: Already exists
		e45a5af57b00: Already exists
		Digest: sha256:55642409e2c6e441d34db2383620461a9513c54e6b7ab029faf28365ea8c6643
		Status: Downloaded newer image for hello-world:latest
		, <nil>
```

And on Windows:

```
--- FAIL: TestPullVerified (11.21s)
	docker_cli_pull_test.go:71: pulling a verified image failed. expected: The image you are pulling has been verified
		got: Pulling repository hello-world
		e45a5af57b00: Pulling image (latest) from hello-world
		e45a5af57b00: Pulling image (latest) from hello-world, endpoint: https://registry-1.docker.io/v1/
		e45a5af57b00: Pulling dependent layers
		511136ea3c5a: Download complete
		31cbccb51277: Download complete
		e45a5af57b00: Download complete
		e45a5af57b00: Download complete
		Status: Image is up to date for hello-world:latest
		, <nil>
```

Could it make a difference if the image is already present locally or not, up-to-date or not? Should the image be removed at the start of the test?

**Comment by dmcgowan** [comment]
The test will indeed fail if the image already exists locally.  The tests which might cause a pull of hello-world:latest should be cleaning up afterwards, there does seem to be edge cases though where the image is left around.  The second cause appears to be a lack of hitting v2, haven't seen any daemon side logs to give a cue as to why v2 failed.

**Comment by thaJeztah** [comment]
@dmcgowan do the test servers keep the daemon logs around, or are they cleaned up?

I copied these from this PR: https://github.com/docker/docker/pull/12416. (http://jenkins.dockerproject.com/job/Windows-PRs/2961/console
and http://jenkins.dockerproject.com/job/Docker-PRs/5991/console)

**Comment by runcom** [comment]
This test was removed in https://github.com/docker/docker/pull/16039
closing
