### ISSUE TITLE
Docker installer halts on existing configuration file

### ISSUE THREAD

**Issue by ruphin** [docker/docker#12124]
Description of problem:
When installing Docker on a platform using apt-get packaging and a `/etc/default/docker` configuration file is already present, the installer interrupts on a query on what to do about this file. This is a problem for automated installations where a custom bridge IP is desired.

Editing the config file and restarting the daemon after the installation is not an option due to #8696.

This query should either be skipped by default, or at least an option to skip it should be provided. 

Given that the installer already attempts to skip interaction with `DEBIAN_FRONTEND=noninteractive` I think the default choice of keeping existing configuration file should be honored. To do this, the apt-get command in the installer needs an additional option `-o Dpkg::Options::=--force-confdef`. I can provide a pull request with this change.

Steps to Reproduce:
1. `echo DOCKER_OPTS=\"--bip=192.168.1.5/24\" > /etc/default/docker`
2. `wget -qO- https://get.docker.com/ | sh`

Actual Results:
Installer is interrupted with the following query:
```
Configuration file '/etc/default/docker'
==> File on system created by you or by a script.
==> File also in package provided by package maintainer.

What would you like to do about it ?  Your options are:
Y or I  : install the package maintainer's version
N or O  : keep your currently-installed version
  D     : show the differences between the versions
  Z     : background this process to examine the 

The default action is to keep your current version.
*** docker (Y/I/N/O/D/Z) [default=N] ?
```

Expected Results:
Installer completes without interruptions

**Comment by ruphin** [comment]
This installation method workaround is currently available for those having the same issue:

```
wget -qO- https://get.docker.com/ > ./install_docker

sed -i '/$sh_c '\''sleep 3; apt-get update; apt-get install -y -q lxc-docker'\''/c\$sh_c '\''sleep 3; apt-get update; apt-get install -o Dpkg::Options::=--force-confdef -y -q lxc-docker'\''' ./install_docker

sh ./install_docker
```

**Comment by cpuguy83** [comment]
Does `debconf-set-selections` not work?

**Comment by ruphin** [comment]
I am not familiar with that tool, and looking at documentation it is not clear to me how to use it in this case. Can you produce an example on how to use it to resolve this issue?

**Comment by cpuguy83** [comment]
I see this is not a prompt from the actual package but by apt itself.

**Comment by cpuguy83** [comment]
I think this is something you should handle before calling the installer and should not be part of the main install script.

ping @tianon

**Comment by ruphin** [comment]
The only option to configure it beforehand is to override the global dpkg settings as outlined here: http://debian-handbook.info/browse/stable/sect.package-meta-information.html#sidebar.questions-conffiles
However, you would have to return it to the default afterward, i.e. there is no way to configure it for the docker installer only.

But it all really comes down to if you want the install script to respect the existing `/etc/default/docker` config file or not. Given the following arguments it makes sense to me to leave the existing config in place by default:
 - The config file installed by the package is empty, it holds no essential configuration for Docker to work.
 - When docker is uninstalled it nicely cleans up the config file as well, so the only situation where a config file exists when running the install script is if someone explicitly placed it there.

A default can be set by adding either `-o Dpkg::Options::=--force-confold` or `-o Dpkg::Options::=--force-confnew` to the apt-get install command in the install script.

Another option would be for the install script to look for a certain ENV variable that signals what behaviour is desired, and leave the default as-is if this variable is not set, but this adds additional complexity to the install script, and a 'hidden' configuration option that needs to be documented. I don't think this is a good option, and setting a sane default is a better choice.

I can create a pull request with either solution.

**Comment by tianon** [comment]
I don't necessarily see either option as a sane general default -- that's the reason APT stops to ask; each user is going to have a different reason for why they have a preexisting `/etc/default/docker`, and if we assume we know what that reason is, we risk breaking their customizations.

**Comment by ruphin** [comment]
Wouldn't you agree that the only reason for there to be a preexisting `/etc/default/docker` is to have that file there? I can't imagine a situation where someone (or something) makes this file to have it blanked by the installer.

One issue with leaving existing files in place is that unexperienced users can run into issues when installing Docker doesn't work the way they expect it to because the config file is wrong somehow. However, the config file is properly removed when uninstalling Docker through `apt-get remove`, so chances of unexperienced users accidentally having a wrong config file is minimal. They would have to manipulate the config file in the first place, then uninstall docker in a non-standard way, and then run the install script. Even if this highly unlikely scenario would occur, it can still be repaired easily with a reinstall through `apt-get remove lxc-docker && wget -qO- https://get.docker.com/ | sh`.

My usecase is that I need automated docker installs that use a custom subnet. For now I can run my automated installers with the workaround posted above, or with a custom install script extracted from the docker installer, but if you ever change the install script or method in the future my installers may break.

If you have a solution for the situation I described other than patching the installer (e.g. #8696) , this issue can be closed for me.

**Comment by tianon** [comment]
If you know your target platform already, I would actually recommend *not*
to use the "curl" installation script, and just follow the "manual"
instructions instead, since the installation script is just a thin layer
around APT or Yum with some very naive platform detection in front.

**Comment by cpuguy83** [comment]
Is this still an issue with the new debs?
I'm not sure what to do here or if we are ok changing behavior?

**Comment by thaJeztah** [comment]
We're in the process of phasing out the get.docker.com install script in favor of manually adding the repos; https://github.com/docker/docker/pull/16662, and I would recommend using those steps in your automated script (customizing it to your needs).

I'm closing this issue, because I don't think this is something we will/can fix, because the script cannot make these decisions without knowing the intent of the user.
