### ISSUE TITLE
API doc for container create "Binds" argument incorrect, and error message confusing

### ISSUE THREAD

**Issue by hugoduncan** [docker/docker#12128]
The api doc for the [`Binds` argument](https://docs.docker.com/reference/api/docker_remote_api_v1.17/#create-a-container) is incorrect.  When creating a new volume, the volume should not appear in "Binds".  The [implementation](https://github.com/docker/docker/blob/master/daemon/volumes.go#L225) explicity checks for a string with two or three components separated by ":".

Moreover, the resulting error message is "Invalid volume specification", which is confusing, as it doesn't mention the `Binds` argument at all.

**Comment by cpuguy83** [comment]
The docs look exactly right, Though a little confusing in the 2nd sentence of the description.

**Comment by hugoduncan** [comment]
In particular "of the form container_path (to create a new volume for the container), ..." seems wrong, as specifying such a value results in the "Invalid volume specification" error.
