### ISSUE TITLE
docker daemon docs incorrectly portrayed examples

### ISSUE THREAD

**Issue by vbatts** [docker/docker#12122]
the docs that end up here --> http://docs.docker.com/reference/commandline/cli/#daemon

since the commit 29d01b7, now the examples for running the daemon have a PS1 command prompt of `$` which indicates a non-privileged user. Though correctly marking the command prompt with `#` which indicates root user, would make them appear as comments. 

We should find a markdown way to show the prompt for a `#` PS1 to be normal, or add back `sudo` for the `docker -d` type examples.

/cc @moxiegirl @thaJeztah @SvenDowideit

**Comment by moxiegirl** [comment]
@vbatts So, if I su to root on an ubuntu instance I get this:

`root@ip-172-31-34-181:/home/ubuntu#`

So, what do you think of using something like that rather than a plain old `#`

**Comment by thaJeztah** [comment]
It's a tough one; we want the shell examples to be as "generic" and "copy-pasteable" as possible; to much info before the actual command will make it more difficult to read (and people might copy it and execute it)

Perhaps `root@docker-host:~# echo foo` might work; the obvious advantage that it's more clear that it's ran as root (for those unaware of the `#/$` differences)

Otoh, if this is the only location where this has to be actually executed as root (and not, for example, a user in the docker group). `sudo` might be better?

**Comment by moxiegirl** [comment]
@thaJeztah If they copy the prompt, the paste won't work regardless. :-P

Otoh, yes, adding `sudo` for specific cases like this does make sense.  Point in case, I didn't pull the `sudo` from the installation docs.

**Comment by thaJeztah** [comment]
@moxiegirl yes better copy-pasteable has been talked about in the past, perhaps after switching to another engine for docs? I'll keep this in mind as well, will look around if I can find good libraries for that.

> Point in case, I didn't pull the sudo from the installation docs.

When @vbatts mentioned this on IRC, the removal of sudo sprang in mind (but I didn't check), and it could well be that this has been there all along. Overall I don't think the incorrect prompt is a *major* issue, but it needs to be fixed at some point.

For the time being, adding `sudo` might be the easiest solution.

**Comment by LK4D4** [comment]
ping @thaJeztah
