### ISSUE TITLE
docker image delete problem

### ISSUE THREAD

**Issue by hangyan** [docker/docker#12135]
The days I was study on the docker source code,mainly about the deleting of images.I think I  found some problems,and I will explain in examples:

Image `ubuntu:14.11`(just for test) and `ubuntu:14.12`  have the same image id:
![screen shot 2015-04-07 at 4 31 20 pm](https://cloud.githubusercontent.com/assets/3939015/7019531/935de748-dd43-11e4-888a-449cdfdf3295.png)

Start a container from image `ubuntu:14.11`:
![screen shot 2015-04-07 at 4 32 48 pm](https://cloud.githubusercontent.com/assets/3939015/7019552/cc457742-dd43-11e4-9880-6a81d0541ad2.png)

Delete image with it's short id :
![screen shot 2015-04-07 at 4 35 05 pm](https://cloud.githubusercontent.com/assets/3939015/7019588/1cb33f98-dd44-11e4-8895-b32fc071986d.png)

no errors while the container is still running

ENV:
ubuntu:14.04, docker 1.5.0 ,driver:aufs

**Comment by thaJeztah** [comment]
Is this solving the same issue as https://github.com/docker/docker/pull/11058 ?

**Comment by vdemeester** [comment]
Not sure but it seems to be related at least.

**Comment by hangyan** [comment]
@thaJeztah  @vdemeester  it's related,but not the same problem. #11058 is focused on one image id mapped to multiple repos(like `ubuntu:14.04` and `ubuntu-test:14.04`) ,in this situation, when run `docker rmi [-f] <image id>`,docker will only untagged one repo at one time. This issue is focused on one image id mapped to one repo and multiple tags(like `ubuntu:14.04` and `ubuntu:14.10`),when run `docker rmi [-f] <image id>`,it will skipped container checking and just delete the image.With multiple repos,i don't know the current actions is correct or not,but with one repo and multiple tags,i think this is not right.

**Comment by jfrazelle** [comment]
I cannot recreate this with 1.6.0 or master
