### ISSUE TITLE
docker build --privileged

### ISSUE THREAD

**Issue by zrml** [docker/docker#12138]
Albeit scary as flag we need to consider it or allow for some other options or tricks.
I am in the condition that I cannot install (via the docker build command/Dosckerfile) any software that requires more than the meagre 32MB of shmmax segment size that linux comes with as default value.

sysctl -w kernel.shmmax=536870912 fails with the "Read-only file system" error

Doing all these builds by hand it's insane.
Waiting for kernel 3.16 (that is: containers able to use the host settings) is crazy too, IMO, because that would mean that ALL containers on that host can go up to xyz-GB of shmmax potentially jeopardising the host. That is another big risk.

There must be a way you allow us to tune parameters and run with the --privileged mode from within the Dockerfile. It is the user responsibility to handle its security.

This is a major show-stopper and other people have commented negatively on this or are looking for alternatives (what though VMs?) :-(

Please, pretty please, help us

**Comment by cpuguy83** [comment]
dup of #1916

**Comment by zrml** [comment]
@cpuguy83 Thank you!

**Comment by sedwards** [comment]
This is needed for installing the older JDK 1.6 packages as well under CentOS as its RPMs attempt to register is binmft_misc which fails without running under --privileged.

Dockerbuild is a non-stater for building containers with it.

To replicate

FROM Centos5.11
RUN yum intall -y jre-1.6.0_29-fcs
