### ISSUE TITLE
A very strange issue with bash#sleep command

### ISSUE THREAD

**Issue by ttrifonov** [docker/docker#12137]
I have a very *strange* issue with Docker. I'm using CoreOS 607.0.0 on Azure, then I start a container(let's call it the host container) with mounting docker sock "-v /var/run/docker.sock:/var/run/docker.sock". Then I start a bash script on that container, that runs a new container(the client container). The new container fires a script on boot that tries to establish SSL connection to external machine.

What happens: I want the host container to wait for few seconds until the client container connects and exchange some data with the external machine. So I add "sleep 10" after `docker run` in the host container. Unfortunately, the client container takes 5-6 sec to exchange data with the external machine. If I remove the `sleep 10` line from the bash script on the host container, the client container connects for 2-3 seconds. It seems that there is a kind of I/O blocking that delays the data transfer from the client container to the external machine when the host container is in "sleep" mode.

And the other funny part is that I have the exact same version of CoreOS machine, again in Azure, where this problem doesn't seem to appear. The only difference that I can see so far is that the current CoreOS machine uses overlay FS, while the other uses BTRFS for storage... 

I don't even know what to look at for debugging the issue...

**Comment by thaJeztah** [comment]
Could this be related to https://github.com/docker/docker/issues/12080?
