### ISSUE TITLE
Proposal: Images should be able to specify what environment variables they need to run

### ISSUE THREAD

**Issue by bfirsh** [docker/docker#12142]
Images often require environment variable configuration to run (passwords, API keys, etc) and there is currently no way for image to require that environment variable to be set at runtime.

I am proposing that we add a way for images to require an environment variable to be set at runtime, without setting a value. For example:

`Dockerfile`
```
FROM python:2.7
ADD . /code
WORKDIR /code
RUN pip install -r requirements.txt
ENV MAILGUN_API_KEY
CMD python app.py
```

Then when running this image:

```
$ docker build -t myapp .
$ docker run myapp
This image requires the MAILGUN_API_KEY environment variable to be set. Please set it with the -e option.
$ docker run -e MAILGUN_API_KEY=abc123 myapp
...
```

This is somewhat analogous to being able to set `EXPOSE` or `VOLUME` in an image without a specific port or volume on the host. This is also a variation on a number of previous ideas (#7247, #8272).

## Background

More generally, I'm thinking of ways that images can better define their various inputs and outputs. Images can currently `EXPOSE` ports as output, specify `VOLUME` as an input/output, etc, but there is no way of requiring configuration as input.

**Comment by aanm** [comment]
Can't "myapp" return an error and terminates the container in case MAILGUN_API_KEY isn't defined?

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.
