### ISSUE TITLE
Fix fail message in TestRunDeviceDirectory

### ISSUE THREAD

**Issue by LK4D4** [docker/docker#12146]
In second check it says that "timer" is expected, but expected is "seq"

**Comment by jfrazelle** [comment]
Shoot that's probably dependent on the host machine is it only failing on
certain machines

**Comment by LK4D4** [comment]
@jfrazelle Yes, it failing only if you have no `seq` device. But issue about wrong fail message in that case.

**Comment by jfrazelle** [comment]
Totally gotcha I'll leave for someone new ;)

**Comment by kostickm** [comment]
#dibs
