### ISSUE TITLE
Failed to allocate port if the static port conflicted with the container's previous dynamic port

### ISSUE THREAD

**Issue by dqminh** [docker/docker#12148]
When user allocates a static port mapping that happens to be conflicted with the mapping that Docker's going to allocate to the same container, the port allocation will fail. This is another variation of #7158 

Steps to reproduce:
```
docker git:master ❯ sudo service docker restart
docker stop/waiting
docker start/running, process 19816
docker git:master ❯ cat /proc/sys/net/ipv4/ip_local_port_range
32768   61000
# now tries to map port 80 dynamically and port 8080 statically to the beginning of the port range
# the first request will fail
docker git:master ❯ docker run -P -p 80 -p 32768:8080 -d busybox top
6315c5cb8192e6d414065c73967605eccf48c1976c4c541a9e8afb6af0fd8aad
FATA[0000] Error response from daemon: Cannot start container 6315c5cb8192e6d414065c73967605eccf48c1976c4c541a9e8afb6af0fd8aad:
Bind for 0.0.0.0:32768 failed: port is already allocated
# second request will succeed
docker git:master ❯ docker run -P -p 80 -p 32768:8080 -d busybox top
b483e0742d2893f2fdff9492fe25ac028d9f9647cc2184dbc1a8c6804adb39c1
```

My docker version:
```
docker git:master ❯ docker version
Client version: 1.5.0-dev
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 9ede3f9
OS/Arch (client): linux/amd64
Server version: 1.5.0-dev
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 9ede3f9
OS/Arch (server): linux/amd64
```

cc @tiborvass

**Comment by tiborvass** [comment]
Could reproduce on 1.6.0-rc5

**Comment by LK4D4** [comment]
I'm not sure why we adding this to milestone, because this was here forever and we have talk about it. If you use static binding from dynamic port range - you can fail some day. Only good can be to forbid static ports from that range.

**Comment by citywander** [comment]
Port conflict is reproduced easily in1.5, so we have to retry again and again to start.It's so weird we start container in the same vm. But the issue is random.

**Comment by jfrazelle** [comment]
removing from milestone as this has been around awhile afaict but let me know otherwise

**Comment by dqminh** [comment]
@LK4D4 hmm i I think it should be safe to use the reserved port range since the port allocator can handle them properly. The bug here is that we hand in the static port too late, so if it uses the port in dynamic range, it can conflict with previously allocated dynamic port of the same container. I posted a fix that always allocates static ports before dynamic ports.

@jfrazelle yes i think this is not a regresssion, only a bug fix. afaik this has always been there.
