### ISSUE TITLE
Windows CLI: Clearing issues in bash prompt

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/docker#12153]
One of the console clearing problems in Windows CLI ANSI emulation package. 

Repro steps:
1. `docker run --rm -it ubuntu bash`
2. Type `0123456789`
3. Hit left arrow key 5 times
4. Hit delete key (fn+backspace on mac) 3 times
5. while you delete, the chars ahead of cursor doesn't get deleted.
6. If you press delete one time you'll end up with **012349**6789 (6789 not cleared)
7. If you hit delete _a few more times_ it eventually cleans and screen says **01234**

cc: @brendandixon @icecrime 

![](http://cl.ly/image/2W3c200b1C3m/Screen%20Recording%202015-04-07%20at%2012.38%20PM.gif)

**Comment by cpuguy83** [comment]
Is this still a problem?

**Comment by brendandixon** [comment]
@ahmetalpbalkan Did Gabe's changes correct this?

**Comment by ahmetalpbalkan** [comment]
I think so. We can close.
