### ISSUE TITLE
"docker run --rm=true" doesn't stop containers when ssh/net connection drops

### ISSUE THREAD

**Issue by neurogenesis** [docker/docker#12157]
When launching an interactive container (like a gateway shell or rails console), the container is not stopped if the ssh/network connection is terminated.

There are probably cases both for and against leaving the container running, but if the user wants a persistent container they should use the -d option or launch "docker run --rm" from within screen/tmux.

If the containers aren't stopped & removed by default, this can cause a proliferation of running docker containers.

**Comment by jfrazelle** [comment]
there are a few other issues about making docker run --rm a daemon function
instead and it is something we definitely want, but this is a duplicate

**Comment by jfrazelle** [comment]
There is #6757, #3968 <--- is the one

**Comment by neurogenesis** [comment]
Hi @jfrazelle / @estesp, i took a look at all open --rm issues and didn't see one that addressed the network connection issue. I didn't really see an open issue that was suitable to add my issue to. If this one is being closed, which one should I comment on to ensure this gets addressed?

Smilar threads:

#3968 - short lived, problem with storage driver
#6003 - --rm does not work with -d (different issue, closed)
#6688 - facilitate running docker on something like coreos+fleet
#6757 - container started with --rm isn't removed after start failure (unrelated)
#10545 - rm --rm and -d (keeps getting closed without being fixed)
#10822 - Docker --rm does not work with tty mode (this looks like a duplicate of #6003)

I gather from the comments that the issue comes down to either client-side API call not being invoked when the shell terminates (terminate / quit signal handling prevents that code path from being executed).

My concern is that the other issues call out different problems and, if fixed, won't necessarily address this issue. For example: #6688 might be the closest, but adding a flag at launch time to promise to stop & remove the container after a set time is server-side (docker daemon) functionality and unrelated to handling the termination of "docker run".

One way the containers could be cleaned up is if "docker run", when invoked with --rm=true, creates a socket connection to the docker server. When the docker daemon sees the client close the socket  connection, it terminates the container. This could possibly address some of the other open issues as well (#3968, #6757, #10822, with the exception of the device mapper problems).

**Comment by jfrazelle** [comment]
i think you just focusing a bit too hard on the network thing, what needs to be fixed is the rm needs to be handed on the daemon side, that way if the connection is dropped the daemon will still do it which i think #3968 covers

**Comment by jfrazelle** [comment]
ugh i guess this comment https://github.com/docker/docker/issues/3968#issuecomment-39033477 I see what you mean

**Comment by jfrazelle** [comment]
I'm changing the info on #6757 to cover everything

**Comment by jfrazelle** [comment]
btw https://github.com/docker/docker/pull/11570 fixed the first step of #6757

**Comment by pwaller** [comment]
@jfrazelle I still think this issue is not covered by any open issue that I can find. Is there an issue which covers moving --rm to daemon side? #6757 was fixed by making it so that under the fail-to-create case the container is deleted server side, but as I understand it, does nothing for all of the other cases (such as the one originally stated in this issue).

Also, this is a real rats nest of long issues with lots of separate problems/solutions thrown in. I think docker could do with a clean proposal issue which outlines just moving the `docker run --rm` functionality server-side.

**Comment by jfrazelle** [comment]
Reopened :)

**Comment by estesp** [comment]
I don't disagree that `--rm` on the server side is a better solution for this problem in general.  However, as I think has been mentioned elsewhere in other issues/PRs around this topic, `--rm` on the daemon side is a **hard problem**.  I've generated patches in a branch and played with lots of potential implementations, but unless we move to a garbage collection-like model, there is no point in the direct flow of `docker run` to do the `rm` exactly at the point of process exit without causing lots of collateral damage to other functions (logging, event notification).

I believe lazy GC will have to be implemented with a Go routine on some cycle, with a GC short-circuit for situations where a new container is started in the duration between GC cycles with the same name as an `--rm`ed container.  At least that's what comes to mind as far as a solution that doesn't break monitor exit/logging/event functionality that isn't quite ready for a container struct to drop from existence immediately after PID exit.

**Comment by duglin** [comment]
Just FYI - we do have a GC cleanup for exec commands ( see https://github.com/docker/docker/blob/master/daemon/exec.go#L279 ) so if we did want to we could expand this to containers.

**Comment by neurogenesis** [comment]
@duglin @estesp , please forgive my ignorance of both go and docker code-base. Am I correct in assuming the real issue here is that normal UNIX signal handling doesn't work as expected for an interactive TTY? Normally a cascade of SIGTERM signals would be issued if the parent TTY is closed (whatever the reason, but in this particular case from an abnormally terminated ssh session to the "docker run" client command). It seems like there's a disconnect between docker client and docker daemon. Is there no way to pass signals through to the docker container in tty mode?

I've been playing around with signal traps from the calling end in wrapper shell scripts, but no matter what execution and trap handling is stalled until the docker container exits (a trap received while executing "docker run" isn't processed until the command exits). When SIGTERM is sent to the ssh shell or wrapper script, the docker run client does exit, but the SIGTERM is never processed by docker daemon in a way that handles the spawned container. Is there a particular reason the SIGTERM/QUIT/KILL/EXIT can't be interpreted by docker run to tell docker daemon to terminate the container?

It looks like that was called out at one point, but closed due to risk of signaling regression problems.

#7567 - Enable signal proxying with TTY

Short of fixing the signaling problem, which doesn't seem likely in the near future, can additional metadata be stored by docker daemon? If something like parent PID of the interactive shell that invoked "docker run" could be returned by "docker inspect", it would allow users to handle cleanup of these containers ourselves. But right now there doesn't seem to be a way to connect the two (pstree from ssh with active "docker run -it" doesn't map to a container process id and the reverse by lookup of the containers PID (via docker inspect) doesn't map to the invoking shell. If additional metadata was available, it would be easier to identify orphaned containers.

Only thing I can think of as a work-around is kind of ugly (naming the containers with PIDs in a shell wrapper). Can you think of a better way to handle this in the short-term?

**Comment by pwaller** [comment]
@neurogenesis 

> Am I correct in assuming the real issue here is that normal UNIX signal handling doesn't work as expected for an interactive TTY?

I don't see the relationship between your post and the issue at hand. This is specifically about deleting images when the client exits. Whereas, you seem to be talking about signalling the container when the client is signalled, as far as I can tell. Image deletion is relatively unrelated to POSIX signals and containers in this context.

**Comment by neurogenesis** [comment]
@pwaller  When a socket or ssh timeout occurs, the process of the ssh login will be sent a signal to terminate. This signal will be passed down through children processes to ensure they are cleaned up as well. With docker this functionality seems to stop at the process that called "docker run". The expected behavior is that the "docker run" process (started with interactive+tty) should issue a terminating signal to the container's init / PID1 (or via docker daemon with docker signal).

If containers are used for interactive CLI work (remote DB consoles, rails consoles, etc.), then inevitably they will accumulate on hosts until manually stopped. Otherwise they will run for weeks consuming memory and potentially CPU. The problem with reaping / garbage collecting the containers is that it's difficult to distinguish between a container that still has a parent ssh/tty connection or not (since no metadata returned by the container identifies the parent PID of the calling "docker run" command).

**Comment by cpuguy83** [comment]
@neurogenesis This is precisely what happens unless I'm misunderstanding you.
The docker CLI will act as a signal proxy when attached to the container.

**Comment by pwaller** [comment]
One example is SIGKILL, where the docker client process doesn't receive the message or have a chance to do cleanup. That's one reason that this issue has discussed moving the image cleanup to the server side. The server can then detect the client has gone away if it loses the connection to the client ("the socket is closed").

**Comment by neurogenesis** [comment]
@cpuguy83 ... the issue is that signal proxy doesn't apply when tty is used. see the following two links:

#7567 - Enable signal proxying with TTY
https://github.com/docker/docker/issues/5547

The text currently says this only works for non-TTY, and appears to have been updated here:

https://github.com/jfrazelle/docker/commit/8b1c935822497278f23f659ac08e5262d204ce59#diff-e728bf75e7a6536ac0e70b85f7aaf65aR1942

**Comment by pwaller** [comment]
@neurogenesis apologies, I didn't see that you started this issue! I thought that this issue was specifically tracking `--rm`, which I still perceive as a different issue from signal proxying, since `--rm` is not a property of the running process but something the daemon needs to arrange when the client goes away.

**Comment by neurogenesis** [comment]
correct. separate issue from the signaling issue, but related in terms of expected behavior and convention of passing signals on session connection termination. ideally it would be solved in such a way that normal signaling cascaded from the ssh session that initiated "docker run", by passing along the SIGHUP and asking dockerd to stop & remove the container.
