### ISSUE TITLE
Windows CLI: Ctrl+C terminates attached session

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/docker#12158]
This is a regression. Sending kill signal to the Linux process (like `top`) while attached to a container (either with `attach`/`exec` or `run -i -t`) from Windows CLI terminates the docker.exe.

It used to terminate only the process being executed and was going back to the shell prompt. 

Repro:

1. Use windows CLI to run `docker run -it ubuntu bash`, you get bash prompt.
2. Hit Ctrl+C
3. docker.exe exited. You're now in cmd.exe prompt.

cc: @brendandixon @icecrime

**Comment by jfrazelle** [comment]
closed by #12283
