### ISSUE TITLE
O_DIRECT is NOT supported by rootfs file system of Docker container on Ubuntu 14.04

### ISSUE THREAD

**Issue by wzymaster** [docker/docker#12170]
I have written the below demo C program to run on root file system within a Docker on Docker Engine with Ubuntu and CentOS respectively : 

```C
#include <unistd.h>
#include <fcntl.h>
#include <iostream>
#include <errno.h>

using namespace std;

int main(void)
{
    int filedesc = open("testfile.txt", O_CREAT | O_DIRECT);
    if (filedesc < 0) {
    std::cout << "fail with errno: " << errno << std::endl;
        return -1;
    }
   else
   {
     std::cout << "success !" << std::endl;
   }
    return 0;
}
```
For Docker Engine with Ubuntu 14 : 
```shell
root@83dbe21d0c04:/# ./test
fail with errno: 22
```
For Docker Engine with CentOS 6.6 :  
```shell
[root@03cd6b22dfeb /]# ./test
success !
```

My further investigation indicates that rootfs file system of Docker container on Ubuntu 14 doesn't support O_DIRECT in open() call, but it works fine on CentOS.

Is it a known bug ? 

Here is docker version in my test : 
```Docker version 1.5.0, build a8a31ef```

**Comment by unclejack** [comment]
This problem was indeed known: #8119. It has been fixed by #10534.

It works just fine on CentOS/RHEL/Fedora because devicemapper is used by default there. Ubuntu usually uses aufs and that's why you were seeing different behavior.

I'm going to close this issue now because the problem has been solved and the upcoming 1.6.0 release has the fix.

**Comment by wzymaster** [comment]
@unclejack  do you have an estimated release date of 1.6.0 ?  Or you have pre-release binary for my testing ?

**Comment by thaJeztah** [comment]
@wzymaster current release candidates can be found here: https://github.com/docker/docker/pull/11635#issuecomment-90205104

Current *master* builds can always be downloaded from https://master.dockerproject.com

**Comment by wzymaster** [comment]
@thaJeztah @unclejack  thanks for your quick reply.  In fact, I observe the exact same problem on Boot2Docker on my Mackbook and window machine.  So 1.6.0 release will address them as well ?

**Comment by unclejack** [comment]
@wzymaster Yes, boot2docker 1.6.0 and Docker 1.6.0 will both have the fix for this problem.
