### ISSUE TITLE
Building Docker docs fails due to missing extends.md configuration (from compose)

### ISSUE THREAD

**Issue by draghuram** [docker/docker#12186]
Bulding Docker docs (`make docs`) fails with the following error:

<pre>
The page "compose/yml.md" contained a hyperlink to "compose/extends.md" which is not listed in the "pages" configuration.
</pre>

Since `extends.md` is new, an entry for it should be added in `docs/mkdocs.yml`.

**Comment by thaJeztah** [comment]
Thanks for reporting @draghuram! Looks like this commit added the new document in compose;
https://github.com/docker/compose/commit/f3f7f000fec841a62cc1849462f851230614af85

/ping @moxiegirl @aanand does this have to be done manually in the `docs/mkdocs.yml` *here* or is there some script that pulls changes in?

**Comment by moxiegirl** [comment]
@thaJeztah I'm working this today.  There are a couple of things wrong with the Makefile.

**Comment by draghuram** [comment]
I can build the docs now but can't see the new content from `extends.md` any where. Is that what is expected? I guess I am not clear how compose's docs are being pulled into docker docs.

**Comment by moxiegirl** [comment]
@draghuram The extends material was released before it was ready.  You can view that work on:

http://docs.master.dockerproject.com/compose/yml/

Or by pointing the docs/Dockerfile to pull `master` from the compose docs

**Comment by draghuram** [comment]
Got it, thanks.
