### ISSUE TITLE
integration-cli: Tests using sleep can timeout too early - change to "top" instead

### ISSUE THREAD

**Issue by twhiteman** [docker/docker#12188]
There is a lot of testing code that is using "docker run busybox sleep N", where N is usually one of (2, 10, 20), with a subsequent docker call to test something on this container (like docker ps or docker exec .. ping).

The problem with this is that in certain environments, the docker sleep process may have ended before the test can finish, resulting in a test failure (unexpected output).

I'd like to increase the sleep time (perhaps to 1000 - and perhaps storing it as a constant somewhere), so that it avoids the slow environment situation and runs the tests correctly.

Does anyone have an issue with such a change?

**Comment by LK4D4** [comment]
@twhiteman It is better to switch it to `top` then. And use more deterministic way to stop containers.
I don't remember any issues about this.
