### ISSUE TITLE
Socket mount not recognised inside container on Centos 7

### ISSUE THREAD

**Issue by manics** [docker/docker#12182]
If a host socket is mounted inside a container it is treated as a normal file:

```
[root@localhost ~]# ls -l /run/docker.sock
srw-rw----. 1 root root 0 Apr  8 12:38 /run/docker.sock
```

```
[root@localhost ~]# docker run -it --privileged -v /run/docker.sock:/run/docker.sock --rm centos ls -l /run/docker.sock
-rw-rw----. 1 root root 0 Apr  8 11:38 /run/docker.sock
```

If instead the parent directory is mounted the socket is recognised:

```
[root@localhost ~]# docker run -it --privileged -v /run:/run --rm centos ls -l /run/docker.sock
srw-rw----. 1 root root 0 Apr  8 11:38 /run/docker.sock
```

System details:
```
[root@localhost ~]# cat /etc/centos-release
CentOS Linux release 7.0.1406 (Core)
[root@localhost ~]# rpm -q docker
docker-1.5.0-28.el7.centos.x86_64
```

**Comment by thaJeztah** [comment]
Could you add the output of `docker version` and `docker -D info`?

**Comment by manics** [comment]
```
[root@localhost ~]# docker version
Client version: 1.5.0-dev
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): fc0329b/1.5.0
OS/Arch (client): linux/amd64
Server version: 1.5.0-dev
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): fc0329b/1.5.0
OS/Arch (server): linux/amd64
```
```
[root@localhost ~]# docker -D info
Containers: 5
Images: 4
Storage Driver: devicemapper
 Pool Name: docker-253:1-35004805-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 571.9 MB
 Data Space Total: 107.4 GB
 Data Space Available: 15.35 GB
 Metadata Space Used: 1.163 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Kernel Version: 3.10.0-123.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 1.798 GiB
Name: localhost.localdomain
ID: HTNG:3YY2:556P:HP4O:IICY:U7FD:D5HN:IJOG:FMSB:MZAM:VV4L:VFQC
Debug mode (server): false
Debug mode (client): true
Fds: 14
Goroutines: 19
EventsListeners: 0
Init SHA1: 44ce8da602aa9c0742d0e96931735b9117670b36
Init Path: /usr/libexec/docker/dockerinit
Docker Root Dir: /var/lib/docker
```

**Comment by thaJeztah** [comment]
Thanks, this looks to be a RHEL-recompiled docker build, which is not maintained by Docker.

There are some issues with that version; see this thread / comment: https://github.com/docker/compose/issues/424#issuecomment-90689698

You can track progress on that issue at the Redhat issue tracker at https://bugzilla.redhat.com/show_bug.cgi?id=1209625

I'm think this should be closed, because this is probably a bug in a version of docker not maintained here, but I'll ask @lsm5, to be sure

/ping @lsm5

**Comment by cpuguy83** [comment]
Can you try this with the 1.6 RC? You can grab that here: https://github.com/docker/docker/pull/11635#issuecomment-90205104

**Comment by manics** [comment]
Works with docker-1.6.0-rc5, thanks.

**Comment by lsm5** [comment]
@manics @thaJeztah going by git commit, that's the one available by default in CentOS extras and it's being worked on as pointed in the RH bz.

Please see http://wiki.centos.org/Cloud/Docker for the CentOS virt SIG repo in which I include `docker` separately from RHEL and it only includes vanilla docker. It's still on 1.5.0, I'll update that to 1.6.0 rc asap. There's a `docker-master` in there as well which gets updated more often. `docker-master` uses the docker master branch (+ RH patches sometimes).

**Comment by jfrazelle** [comment]
@lsm5 the binary I am getting from virt7-testing has the RH patches it is *not* vanilla docker

**Comment by lsm5** [comment]
@jfrazelle are we talking about this one: http://cbs.centos.org/koji/buildinfo?buildID=682 . Let me know what `rpm -qi docker` says for your system.
