### ISSUE TITLE
Add a way to "APPEND" to a file from within a Dockefile

### ISSUE THREAD

**Issue by orzel** [docker/docker#12193]
You will agree that creating a docker image is mostly about starting from another one and add to it. We can already ADD (and COPY, this is already quite confusing), which append new files to the image.

What I think is a very common pattern is the following : we need to 'adjust' a previously existing configuration file. This would be done by appending a shunk of configuration at the end of this file. Typical stuff would be
* add new configuration options ("AAA=xxx")
* append to existing variables ("PATH="/new/shiny/software/just/installed:${PATH}")

Some software allows configuration files to be splitted inside a ".d" directory, and that would solves the problem here, but not all of them can be used this way.

The current solution I have is something along:
```
COPY files/myconfig.append /tmp/
RUN cat /tmp/myconfig.append >> /etc/portage/make.conf  && rm -f /tmp/myconfig.append
```
But it's far from ideal. It's cumbersome, but my main concern with it is that it creates a useless commit with temporary data (delete just the step after).

My ideal new Dockefile command would hence be: 
```
APPEND localfile /path/to/config/file/in/image
```

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.

**Comment by augnustin** [comment]
@jessfraz your link is broken. Any idea where it lies now?

Or maybe the situation has changed since 2015 and as Moby came along?

If not, shouldn't there be a possibility to add features to the builder by registering plugins or something? It feels very dangerous and quite short-sighted to prevent this from being extended.

That said, I completely :+1: @orzel need, feels awkward to `COPY + RUN >> && rm`...

**Comment by juanmirocks** [comment]
I agree an `APPEND` instruction would be handy sometimes.

[The best way to append a temporary file](https://stackoverflow.com/questions/77846702/dockerfile-append-concat-to-a-file-from-a-temporary-source) is using a `RUN` bind mount, like:

```dockerfile
RUN --mount=type=bind,source=myfile,target=/tmp/myfile \
    cat /tmp/myfile >> /some/path
```

**Comment by orzel** [comment]
At least it's a one-liner, even if convoluted, and it removes the useless in-between commit. Great workaround !
