### ISSUE TITLE
lsblk hangs when multiple containers query a volume in parallel

### ISSUE THREAD

**Issue by indygreg** [docker/docker#12192]
I'm encountering a weird issue where `lsblk` hangs when reads occur in parallel from multiple containers.

STR:

1. Install Docker with default settings on Ubuntu 14.04.2 (devicemapper, 1.5)
2. `$ docker pull centos:centos6`
3. `$ docker create -v /volume --name shared centos:centos6 /bin/bash`
4. Figure out the device ID for the shared volume
   `$ docker run -it --rm --volumes-from shared centos:centos6 /bin/bash
   `$ grep /etc/resolv.conf /etc/mtab | awk '{print $1}'`
   `/dev/disk/by-uuid/ed3195b9-d1ef-476b-9c64-882718e58aeb`
5. Spawn multiple containers that concurrently start a container with this shared volume and run `lsblk` on it.
6. `docker ps` and `ps faux` will show that `lsblk` is hung in 2 or more containers.

For spawning multiple containers in parallel, I wrote a dead simple shell script:

> docker run -i --rm --volumes-from shared centos:centos6 \
>  /bin/lsblk -ln --output UUID /dev/disk/by-uuid/ed3195b9-d1ef-476b-9c64-882718e58aeb &
> docker run -i --rm --volumes-from shared centos:centos6 \
>  /bin/lsblk -ln --output UUID /dev/disk/by-uuid/ed3195b9-d1ef-476b-9c64-882718e58aeb &
> docker run -i --rm --volumes-from shared centos:centos6 \
>  /bin/lsblk -ln --output UUID /dev/disk/by-uuid/ed3195b9-d1ef-476b-9c64-882718e58aeb &
> docker run -i --rm --volumes-from shared centos:centos6 \
>  /bin/lsblk -ln --output UUID /dev/disk/by-uuid/ed3195b9-d1ef-476b-9c64-882718e58aeb &
> docker run -i --rm --volumes-from shared centos:centos6 \
>  /bin/lsblk -ln --output UUID /dev/disk/by-uuid/ed3195b9-d1ef-476b-9c64-882718e58aeb &

Note: I'm not able to reproduce with `run -d`. I suspect there is a race condition and the extra lag introduced by `-d` makes it go away.

The `/dev/disk/by-uuid/*` path doesn't exist in the running container. If you run a container standalone, `lsblk` will tell you this immediately:

> $ docker run -i --rm --volumes-from shared centos:centos6 /bin/lsblk -ln --output UUID /dev/disk/by-uuid/ed3195b9-d1ef-476b-9c64-882718e58aeb
> lsblk: /dev/disk/by-uuid/ed3195b9-d1ef-476b-9c64-882718e58aeb: not a block device

FWIW, I was able to reproduce this issue by running Ansible in containers that were started concurrently. As part of Ansible's fact discovery, it iterates devices listed in `/etc/mtab` and does an `lsblk` on them. This discovery was timing out after 10s. The reproduce case above seems to be the simplest approximation of Ansible's behavior that can reliably trigger the issue.

**Comment by indygreg** [comment]
I have two Ubuntu setups I use on my Mac: vanilla server install via Virtualbox and a Vagrant-based install (also on Virtualbox). Strangely, the problem doesn't seem to be occurring on the direct Virtualbox install: only the install via Vagrant is wonky. The plot thickens.

**Comment by unclejack** [comment]
@indygreg Please provide the output of `docker info` and `docker version` from both VMs.

**Comment by indygreg** [comment]
Working:

$ docker info
Containers: 24
Images: 164
Storage Driver: devicemapper
 Pool Name: docker-252:0-2102814-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.873 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 9.077 MB
 Metadata Space Total: 2.147 GB
 Udev Sync Supported: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.13.0-48-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 8
Total Memory: 3.86 GiB
Name: ubuntu-gps-test
ID: NZWF:C76P:6ZCT:UHQ6:2FVR:SNZK:6D35:YZ5Z:2SZC:VH4U:3AUV:KVFR
WARNING: No swap limit support

Not working:
$ docker info
Containers: 13
Images: 182
Storage Driver: devicemapper
 Pool Name: docker-8:1-1056972-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.337 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 8.798 MB
 Metadata Space Total: 2.147 GB
 Udev Sync Supported: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.13.0-33-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 1.955 GiB
Name: vagrant-ubuntu-trusty-64
ID: X2KF:ICFZ:AJPM:VW4F:CCZJ:7TJ6:R7ZL:4NAA:2ELY:F4IU:KJDE:B2W6
WARNING: No swap limit support

**Comment by indygreg** [comment]
I updated the kernel on my failing VM to 3.13.0-49-generic and I can't reproduce the issue any more. Could I be looking at a kernel bug?

**Comment by unclejack** [comment]
@indygreg Yes, there were known bugs in all kernels up to 3.13.0-37 regarding data corruption and some other problems.

**Comment by indygreg** [comment]
I guess I'll close this issue then.
