### ISSUE TITLE
Docker goes crazy if local file system space runs out

### ISSUE THREAD

**Issue by saadfarooq** [docker/docker#12195]
While building a docker container, if the space of the file system runs out, docker crashes. That is expected. 
However, even when more space is created after this, docker does not work at all. Following are examples response from the system after the running out of space crash.

    -bash-4.1$ docker images
    REPOSITORY                     TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
    <none>                         <none>              7dd470ee64c3        8 weeks ago         647.4 MB
    <none>                         <none>              807510011e97        4 months ago        214.7 MB
    <none>                         <none>              ad3593a35fc7        5 months ago        613.3 MB
    java                           7                   255aa3fc408a        5 months ago        613.3 MB
    <none>                         <none>              8f118367086c        5 months ago        215.6 MB
    <none>                         <none>              22093c35d77b        5 months ago        197.8 MB
    <none>                         <none>              30868777f275        5 months ago        116.1 MB
    <none>                         <none>              02da98fbd44a        6 months ago        235.6 MB
    tiagoboldt/sharelatex-docker   latest              e3497f009d3e        7 months ago        4.921 GB
    orchardup/postgresql           9.3                 74666475d860        8 months ago        491.4 MB
    orchardup/postgresql           9.1                 0dd0ff9187a7        8 months ago        331.9 MB
    orchardup/postgresql           latest              837be9974ea2        8 months ago        488.6 MB
    <none>                         <none>              36e732ca2610        9 months ago        458.7 MB
    <none>                         <none>              5796a7edb16b        9 months ago        101.1 MB
    <none>                         <none>              47dd6d11a49f        9 months ago        98.54 MB
    <none>                         <none>              209ea56fda6d        9 months ago        180.3 MB
    <none>                         <none>              039246b48a54        10 months ago       1.094 GB
    <none>                         <none>              6cfa4d1f33fb        11 months ago       0 B
    tiagoboldt/sharelatex-docker   sharelatex          92633a1a669a        13 months ago       4.583 GB

    -bash-4.1$ docker images -aq | xargs docker rmi
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce
    Error response from daemon: No such id: 0baf5c828bac0fb6284fd43bcb3be1626eb399491aa7801bb4618739cc3923ce    

And running any new container after that does this: 

    -bash-4.1$ docker run -it ubuntu bash
    Unable to find image 'ubuntu' locally
    Pulling repository ubuntu
    d0955f21bf24: Error pulling image (latest) from ubuntu, Driver devicemapper failed to create image rootfs f3c84ac3a0533f691c9fea4cc2ceaaf43baec22bf8d6a479e069f6d814be9b86: Error running DeviceCreate (createSnapDevice) dm_task_run failed reate (createSnapDevice) dm_task_run failed
    f3c84ac3a053: Error downloading dependent layers
    2015/04/08 16:58:22 Error pulling image (latest) from ubuntu, Driver devicemapper failed to create image rootfs f3c84ac3a0533f691c9fea4cc2ceaaf43baec22bf8d6a479e069f6d814be9b86: Error running DeviceCreate (createSnapDevice) dm_task_run failed

**Comment by jfrazelle** [comment]
is this on aws or something? how did you scale the drive, was
/var/lib/docker left in tact, because it looks like something got corrupted

**Comment by saadfarooq** [comment]
Nothing elastic. It's an RHEL VM. I just ran `docker images -aq | xargs docker rmi` to make space the first time it crashed saying it was out of space. It cleared some images which created the space and then barfed, I believe, the same Error response as above (I'm 89% sure it was the same message).

**Comment by jfrazelle** [comment]
can you give us docker info and docker version and let us know if its still a problem with latest

**Comment by saadfarooq** [comment]
Sorry for the delay. The docker version is older (I think 1.3, I'll confirm in a bit). 
Do you expect this to be fixed in later versions?? I found another issue that indicated the issue was caused by older kernel so we upgraded to RHEL 7 but that didn't help.

**Comment by cpuguy83** [comment]
@saadfarooq Most likely, lots and lots and lots of improvements to devicemapper since 1.3
I'm going to close for now, but if you can repro on the latest docker version, please ping here and we can re-open.
