### ISSUE TITLE
Proposal: detect invalid --log-driver on daemon start, noplogger

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/docker#12213]
If I start a daemon like `docker -d --log-driver=bazinga` it just starts fine but the container creation fails. I think that's a bad idea and daemon shouldn't start in the first place.

We defer the check until the container creation, and we have no factories for building Logger objects. (We just have a simple switch/case.

We also use `nil` in case of `--log-driver=none`. IMO that's a bad idea and can easily lead to null reference panics. I'm planning to refactor that as well into a `noplogger` package with [null object pattern](https://en.wikipedia.org/wiki/Null_Object_pattern).

LMK if you have any objections asap. @LK4D4 @crosbymichael 
Followup to #7195, #10568.

**Comment by LK4D4** [comment]
@ahmetalpbalkan Bazinga is definetely a bug. Factory would be nice(not sure how to implement it). I prefer nil over null-object-pattern.

**Comment by cpuguy83** [comment]
Closing as this is fixed.
