### ISSUE TITLE
Docker API issues

### ISSUE THREAD

**Issue by YanXiaoping** [docker/docker#12216]
I have several issues about Docker API.(I asked the question on stackoverflow/docker user group, but was suggested to create a issue here)
What I want to achieve:
I have a  distributed application, which I plan to containerize. I would run it in multi containers on multi hosts. 
My APP internal function needs events about the state changes of containers.
I'd like to avoid container orchestrator locked in, as I can't predict what orchetrator will my customer use.

Issues:
1. I tried the API run "curl http://10.69.117.136:4243/events" in my shell, when I stop a container on this host, noting is capatured (no output on shell). Is there something wrong in my way of using the API? (However, "curl http://10.69.117.136:4243/events?since=1374067924" works )

2. I want to have group of containers as a single object (a funcational unit), and I'd like to know the state of this object (like running, exited etc.). In K8s this object is pod. but if possible, I would like to use docker native service to avoid locked in.
Is there such object in docker, or coming in some future?

3. It was mentioned here (http://blog.docker.com/tag/libswarm/) libswarm will help to avoid vendor solution locked-in. But it seems to me that libswarm has been renamed to swarm, and swarm itself is an alternative of orchestrator (for example, I can run k8s + docker or swarm + docker, right?). so there will no standard cluster level API?

4. Is there detailed specification of container (or possibly group of containers) state?
The best I can find is issue 12164: https://github.com/docker/docker/issues/12164

**Comment by ahmetalpbalkan** [comment]
@YanXiaoping thanks for the questions. I would post these questions separately on https://groups.google.com/forum/#!forum/docker-user . It is just an easier way to discuss and get more attention to your questions. Usually less people look at the issues periodically.

**Comment by thaJeztah** [comment]
Hi, @YanXiaoping I'm going to close this issue, because the GitHub is intended for tracking bugs and feature requests, which this is not.

Feel free to comment after closing, but (as Ahmet suggested), Google groups, https://forums.docker.com or the #docker IRC channel are better suited for questions.

**Comment by YanXiaoping** [comment]
@thaJeztah, I think my first question can be potentially bug, and my last three questions relates to feature more or less.
Could I get some comment here?
(I asked on docker-user, but didn't get comments
 https://groups.google.com/forum/#!topic/docker-user/X47NS4uOb4U )

**Comment by thaJeztah** [comment]
@YanXiaoping the first question is because the `/events`endpoint (*without* `?since=`) is streaming the events in real-time, which requires a slightly different usage of curl.

These should probably give you what you're expecting (I've used the IP-address and port you used in your question);

```console
curl --dump-header - --no-buffer http://10.69.117.136:4243/events
```
or

```console
curl --no-buffer http://10.69.117.136:4243/events
```

Then in a separate shell;

```console
docker run --rm -it busybox echo foo
```

**Comment by YanXiaoping** [comment]
@thaJeztah , yes that works, thank you for your kind help.

**Comment by thaJeztah** [comment]
> edit: I have had read "Monitor Docker's events" before asking, I didn't get the hint behind the "real time stream".

If you have ideas how that part of the documentation can be improved (perhaps a practical example); we're open to suggestions. Feel free to create a pull-request!

**Comment by YanXiaoping** [comment]
@thaJeztah 
As this is about curl command syntax, I will not create pull-request for it.
Thank you.
