### ISSUE TITLE
docs: Missing documentation for logging drivers

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/docker#12211]
Docker 1.6 is shipping with configurable logging drivers support however they're not documented well (or I can't seem to find).

#### In the CLI reference ([master](http://docs.master.dockerproject.com/reference/commandline/cli/)) we only have these:

> daemon parameters: 
![image](https://cloud.githubusercontent.com/assets/159209/7057791/a924e088-de0e-11e4-8071-4565b4003658.png)

> Docker run paramerers:
![image](https://cloud.githubusercontent.com/assets/159209/7057786/96e609b0-de0e-11e4-926f-e3bca765f185.png)

> Docker create parameters : 
![image](https://cloud.githubusercontent.com/assets/159209/7057799/b3a66c02-de0e-11e4-88d8-dc918f679472.png)

#### In the Remote API 1.18 docs ([master](http://docs.master.dockerproject.com/reference/api/docker_remote_api_v1.18/)) we only have

> `LogConfig` documentation (not to mention broken markup syntax)

![image](https://cloud.githubusercontent.com/assets/159209/7057808/e81bbef6-de0e-11e4-80f7-0f8194000c13.png)

> Example usage

![image](https://cloud.githubusercontent.com/assets/159209/7057813/f6d68fb6-de0e-11e4-945c-a496b34e68c6.png)

#### Problem 

By looking at those docs I have no idea how I can configure a logging driver. Also the `--log-opt` is not clear to me in the sense what the argument format should look like.

The `Config`  map is free form and very vague. We should have some examples here in those docs if we expect people to use these.

I couldn't figure out what config possibly could be without reading the daemon source code.

cc: @thaJeztah @LK4D4 
relevant: #4934

**Comment by ahmetalpbalkan** [comment]
I realized the Config map  (`runconfig.LogConfig.Config`) is currently not being used anywhere. I guess we keep it as extension point in the future drivers. So it might be ok to keep the documentation as is but at least it'd be great to say something like "this is currently not used" or not document at all.

**Comment by shazow** [comment]
Also would be nice if the syslog output format was documented, ideally with an example configuration for capturing it properly using rsyslog or such.

**Comment by ahmetalpbalkan** [comment]
@shazow nice point. +1

**Comment by shazow** [comment]
This is the most sensible rsyslog config I've been able to come up with:

```
# Split out 0123456789abc out of docker/0123456789abc[123456]
$template DockerLogs,"/var/log/docker/%syslogtag:7:19%.log"

:syslogtag,startswith,"docker/" ?DockerLogs
```

**Comment by LK4D4** [comment]
@shazow Super! Thank you.

**Comment by jfgreen** [comment]
Syslog driver is a really great addition in 1.6. However, it would be useful to have an option for the container names to be logged instead of or along side the abbreviated ids. Maybe this option could be exposed through the currently unused Logconfig.

I guess for now it's possible to have some sort of rsyslog plugin that does this.

**Comment by thaJeztah** [comment]
True; for now, only ID is supported, but this will most likely be configurable in a next release

**Comment by jfgreen** [comment]
@thaJeztah Good to hear. Thanks!

**Comment by shazow** [comment]
> However, it would be useful to have an option for the container names to be logged instead of or along side the abbreviated ids.

+1. Right now I have a script which builds a dir of symlinks to log files based on name -> id. Would be nice if I could just write the logs directly based on the container name. Also this would let me easily persist logs for the same name/type across container rebuilds.

**Comment by LK4D4** [comment]
@shazow we're working on `log-opts` which allow you to tag containers in syslog for example.

**Comment by shazow** [comment]
@LK4D4 Yea I saw that, should do the trick but will be a bit annoying to specify the name in yet another parameter.

Ideally I'd love to be able to set a docker-wide log-driver/log-opts default, and have a "tag with the container name" option.

**Comment by mahnunchik** [comment]
+1

**Comment by ahmetalpbalkan** [comment]
Ping on this issue...
I think this documentation topic is still missing. I could not come across any page that explains what each `--log-driver` does and what `--log-opts` it takes.

**Comment by thaJeztah** [comment]
@ahmetalpbalkan please have a look at https://github.com/docker/docker/tree/master/docs/reference/logging, and at this PR: https://github.com/docker/docker/pull/15102 (which is just a start)

**Comment by ahmetalpbalkan** [comment]
@thaJeztah This is cool, I hope we can have them at docs.docker.com, soon. :) Feel free to close this anytime.

**Comment by thaJeztah** [comment]
@ahmetalpbalkan Thanks. Looking at that docs,  I don't think the section is linked in the menu yet, and it looks like http://docs.master.dockerproject.org isn't really up to date. @moxiegirl do you know what the current status is on http://docs.master.dockerproject.org, because I don't think it is up to date?

**Comment by moxiegirl** [comment]
@ahmetalpbalkan @thaJeztah Master is lagging I'm sure at the moment. I'll look into it.
