### ISSUE TITLE
Curl install script doesn't install aufs support on Ubuntu 12.04

### ISSUE THREAD

**Issue by mbentley** [docker/docker#12219]
Updates in #10859 might prevent docker with aufs support to be installed on Ubuntu 12.04 as a standard default kernel is `3.2.*-virtual` instead of `*-generic`.  I'll add support to enable the curl install script to also check for `-virtual` kernels which are supported by `linux-image-extra-virtual`.  This can be seen on test.docker.com as this hasn't been released yet.

**Comment by jfrazelle** [comment]
well a 3.2 kernel is also pretty meh and actually not supported just FYI

https://docs.docker.com/installation/ubuntulinux/

> Docker requires a 64-bit installation regardless of your Ubuntu version. Additionally, your kernel must be 3.10 at minimum. The latest 3.10 minor version or a newer maintained version are also acceptable.

**Comment by mbentley** [comment]
Valid point.  Thanks!
