### ISSUE TITLE
Bug: /info endpoint doesn't return LoggingDriver in 1.6

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/docker#12229]
In `1.6.0-rc5` I can confirm that `/info` endpoint does not return any `LoggingDriver` (the field is just missing).

### Repro steps.

1. Start docker daemon with `sudo docker -d -H unix:// -H 0.0.0.0:4243`
2. `curl http://localhost/info | grep LoggingDriver`
3. Shows nothing, supposed to show `"LoggingDriver" : "json-file"`.

This is a bug since this field was documented in Remote API docs and CLI outputs for Docker 1.6 docs.

Also reproes even though you explicitly add `--log-driver=json-file` to the daemon arguments.

### Fix

My change #12226 fixes this. I can't exactly tell how it does. I didn't investigate it thoroughly. It just improves handling of logging driver types and their lifecycle.

cc: @LK4D4 @crosbymichael

**Comment by ahmetalpbalkan** [comment]
Added test #12231 to verify this is the case but apparently this doesn't occur in test environment.

In my `ps` output I see docker started as:

    docker -d --log-driver=json-file -H unix:// -H tcp://0.0.0.0:4243

however `curl`/`docker info` doesn't return any logging driver info to me for some reason. 

```sh
$ docker -v
Docker version 1.6.0-rc5, build fc4825d
```

**Comment by jfrazelle** [comment]
That patch was added after the fact I believe so I think it is only in
master

**Comment by jfrazelle** [comment]
confirmed, only in master

**Comment by jfrazelle** [comment]
so I think this is fine it works on master

**Comment by ahmetalpbalkan** [comment]
@jfrazelle are we cherrypicking to release for the next rc?

**Comment by jfrazelle** [comment]
nope I do not think its necessary, it was an added "nice to have" but not
essential or fixing a bug

**Comment by ahmetalpbalkan** [comment]
@jfrazelle hmm then we need to remove it from the docs and cherry pick into the 1.6 docs release so that it wont mention this field.

**Comment by jfrazelle** [comment]
It's not in the docs on my branch :), this is why I also don't cherry pick
docs commits

**Comment by jfrazelle** [comment]
sooooo closing
