### ISSUE TITLE
Docker should include a formal grammar for Dockerfile

### ISSUE THREAD

**Issue by achanda** [docker/docker#12221]
Why is this necessary?

1. This would enable any developer to use that to generate a parser in any language. The current parser is in written in Go, it's difficult to port it to other languages. 
2. Though the Dockerfile syntax is simple enough for hand parsing, having a specified grammar will help in avoiding confusion as the sytax evolves.

**Comment by vdemeester** [comment]
+kind/proposal

**Comment by lexlapax** [comment]
+request
Would be happy to work towards a BNF spec for Dockerfile.
I'm working on a programmatic Dockerfile generator in python (parsing would be the next step/parallel step).. a formalized spec would help forward compatibility (though, not necessary)

**Comment by duglin** [comment]
I'm not against the idea of including a BNF but I do have concerns that this will be more than a little difficult since our parsing isn't consistent. For example, for historical reasons, we have different parsers for certain commands, and trying to encapsulate these differences in a formal grammar will not be trivial. 
Just a heads up :-)

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.

**Comment by PavelSosin-320** [comment]
Maybe, it is fantastic, but AST + DOM + DOM API can help to generate code from the GUI tools. It is the most efficient way to produce working code by non-pro developers in the application area. These people make most of the applications in the enterprise area.
