### ISSUE TITLE
Mounting files from within image to serve from Nginx - Rails app

### ISSUE THREAD

**Issue by vmatekole** [docker/docker#12230]
FROM rails:4.2.0
COPY . /apps
WORKDIR /apps/oklahoma
# Install configured gems
RUN bundle install
RUN  \
    #Setup migrations from rails
    bundle exec rake railties:install:migrations
VOLUME ["/apps/oklahoma/public","/apps/oklahoma/log"]
EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0"]

I have the above image with static files in /apps/oklahoma/public. When the volume is mounted these files are not available. I have attempted to mount using 'data only container model' too, to no avail. I have only managed to mount files from host to container not container to host. These files are required for serving via nginx that must be able to access these files from host. 

Currently, I have to deploy these files separately to host in addition to the image.

**Comment by cpuguy83** [comment]
Hi, 

Please ask these kinds of questions in the docker-user mailing list or #docker on IRC.
For some reading on volumes which will probably show you why it's not working as you expect, see: http://container42.com/2014/11/03/docker-indepth-volumes/
