### ISSUE TITLE
Bug?: delete image across different graph-driver

### ISSUE THREAD

**Issue by x1022as** [docker/docker#12233]
Not sure if this is a bug or it's just designed to be like this.

ubuntu 14.10 & docker-1.5.0-dev

1) set aufs as storage-driver, and have busybox image locally:
```bash
euler@euler:~$ docker info
...
Storage Driver: aufs
...

euler@euler:~$ docker pull busybox
Pulling repository busybox
4986bf8c1536: Download complete 
511136ea3c5a: Download complete 
df7546f9f060: Download complete 
ea13149945cb: Download complete 
Status: Downloaded newer image for busybox:latest
euler@euler:~$ docker images | grep busybox
busybox           latest              4986bf8c1536        3 months ago        2.433 MB
```

2) change storage-driver to devicemapper. It has no images first, pull busybox and rmi it immediately
```bash
euler@euler:~$ docker info
...
Storage Driver: devicemapper
...

euler@euler:~$ docker images | grep busybox
euler@euler:~$ docker pull busybox
Pulling repository busybox
4986bf8c1536: Download complete 
511136ea3c5a: Download complete 
df7546f9f060: Download complete 
ea13149945cb: Download complete 
Status: Downloaded newer image for busybox:latest
euler@euler:~$ docker images | grep busybox
busybox   latest              4986bf8c1536        3 months ago        2.43 MB
euler@euler:~$ docker rmi  4986bf8c1536
Untagged: busybox:latest
Deleted: 4986bf8c15363d1c5d15512d5266f8777bfba4974ac56e3270e7760f6f0a8125
Deleted: ea13149945cb6b1e746bf28032f02e9b5a793523481a0a18645fc77ad53c4ea2
Deleted: df7546f9f060a2268024c8a230d8639878585defcc1bc6f79d2728a13957871b
Deleted: 511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158
euler@euler:~$ docker images | grep busybox
```

3) restart docker daemon, and set to aufs again
```bash
euler@euler:~$ docker info
...
Storage Driver: aufs
...
euler@euler:~$ docker images | grep busybox
euler@euler:~$ 
```
busybox image is gone, while all other images are still there. 

docker run with these survival images will fall across `FATA[0000] Error response from daemon: could not find image: no such id: 511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158` 
maybe because his layer was removed along with the `rmi busybox` in devicemapper. another `docker pull` will solve this.

I think the root cause of this is that devicemapper and aufs share the same `/var/lib/docker/graph`, maybe new subdirs like `/var/lib/docker/graph/aufs` and `/var/lib/docker/graph/devicemapper` will work fine.

**Comment by xiaods** [comment]
we need more evidence to confirm the root cause.
