### ISSUE TITLE
Allow optional switch to disable injection of env variables in target of linked container

### ISSUE THREAD

**Issue by sriddell** [docker/docker#12236]
It would be helpful in some instances when linking containers to be able to specify that the env variables in the source container, as well as the additional ones Docker injects (such as <alias>_PORT) should not be injected into the target.

We have hit situations where the <alias>_PORT Docker automatically injects into a target container conflicts with env variables our application is looking for in a different format.

**Comment by cpuguy83** [comment]
I don't see why the actual ip/port env vars could ever cause a problem with another app, but certainly +1 on disabling at least the propagation of env vars from the linked container.

**Comment by sriddell** [comment]
Well, in my particular case, I have a linked container with an alias of 'sidekick'.  The target container is an app that wants to find a 'sidekick' but isn't designed to assume it's available via a linked container, so it supports env variables SIDEKICK_HOST and SIDEKICK_PORT to override the default behavior (expecting the sidekick to be a linked container).

So when I run in default mode, and Docker injects SIDEKICK_PORT as tcp://sidekick:3000, and my app expect SIDEKICK_PORT to be purely numerical, it breaks.  That's why I'd like the option to turn them all off.

However, it's not a huge deal  - I changed the env vars on my side, but from I guess a 'purity' standpoint, I would like to be able to use linked containers with the assurance that the only env variables in a target container are ones that I have explicitly defined via the Docker file or runtime switches.  Or maybe have any env vars injected via link be prefixed with "DOCKER_" to minimize the change of collision and make it clear these were injected by Docker linking?

**Comment by runcom** [comment]
I'll have a look this weekend and eventually come up with a proposal pull request #dibs

**Comment by runcom** [comment]
@sriddell what you are trying to do is easly accomplished by setting an alias when you run your app container with `--link containeridorname:ALIAS` to avoid collision of env vars. 
So, instead of changing env vars names on your app side you could do:
```bash
#this exposes SIDEKICK_PORT=tcp://sidekick:3000 to container yourapp below
docker run --name sidekick -d -p 3000:3000 ubuntu sleep 300
#this just exposes SIDEKICK_PORT=3000 and SIDEKICKAPP_PORT=tcp://sidekick:3000
docker run --name yourapp --link sidekick:sidekickapp -e SIDEKICK_PORT=3000 -ti ubuntu bash
```
output from yourapp container:
```bash
root@1d50ee8da8d1:/# echo $SIDEKICK_PORT
3000
root@1d50ee8da8d1:/# echo $SIDEKICKAPP_PORT
tcp://172.17.0.1:300
```

**Comment by runcom** [comment]
@sriddell do you still have issues with this? Have you tried using alias insted as I wrote above?

**Comment by calavera** [comment]
Thanks for the clear explanation @runcom. There is a more bigger discussion about security in env variables, but I'm going to close this issue for now, since it's not the place to have that discussion.
