### ISSUE TITLE
move all integration tests to integration-cli so we can remove finally

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#12255]
all the tests in integration/ need to be converted to integration-cli/ so we can get rid of those tests once and for all.

**Comment by runcom** [comment]
I also noticed most of the scenarios are just covered by integration-cli itself and in integration there were only the job mechanism tests

**Comment by brahmaroutu** [comment]
#dibs

**Comment by jfrazelle** [comment]
also kinda related to https://github.com/docker/docker/issues/12151
