### ISSUE TITLE
Output from docker exec -it on remote daemon truncated

### ISSUE THREAD

**Issue by nathanleclaire** [docker/docker#12258]
I'm getting some erratic behavior running a command like `docker exec -it <ID> cat /file.conf` on a remote daemon.

My setup: Digital Ocean droplet created with `docker-machine`, daemon configured to accept connections over TLS.

```console
$ docker info
Containers: 28
Images: 67
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 123
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-40-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 1
Total Memory: 490 MiB
Name: droplet
ID: G5EI:7YSA:JBWN:VAQB:QPEN:SSFJ:CLYG:IGTA:TZVI:XHYY:IKBZ:5YNO
Username: nathanleclaire
Registry: [https://index.docker.io/v1/]
Labels:
 provider=digitalocean

$ docker version
Client version: 1.6.0-rc4
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): e2e39fc
OS/Arch (client): darwin/amd64
Server version: 1.6.0-rc5
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): fc4825d
OS/Arch (server): linux/amd64

$ ./docker-machine_darwin-amd64 ssh droplet -- uname -a
Linux droplet 3.13.0-40-generic #69-Ubuntu SMP Thu Nov 13 17:53:56 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

I have an [interlock](https://github.com/ehazlett/interlock) container running with the following command:

```console
$ docker run -d -p 80:8080 -e HAPROXY_PROXY_BACKEND_OVERRIDE_ADDRESS=127.0.0.1 -v /var/run/docker.sock:/var/run/docker.sock ehazlett/interlock --plugin haproxy start
```

The issue is that when I do `docker exec -it <ID> cat /proxy.conf` to see the configuration, oftentimes the output I get back is truncated.

It should look something like this:

```
# managed by interlock
global

    maxconn 2048
    pidfile /proxy.pid

defaults
    mode http
    retries 3
    option redispatch
    option httplog
    option dontlognull
    option http-server-close
    option forwardfor
    timeout connect 5000
    timeout client 10000
    timeout server 10000

frontend http-default
    bind *:80

    monitor-uri /haproxy?monitor
    stats realm Stats
    stats auth stats:interlock
    stats enable
    stats uri /haproxy?stats
    stats refresh 5s
```

Instead it will frequently seem to drop the output in the middle, leaving something like this as the only output:

```
# managed by interlock
global

    maxconn 2048
    pidfile /proxy.pid

defaults
    mode http
    retries 3
    option redispatch
    option httplog
    option dontlognull
    option http-server-close
    option forwardfor
    timeout connect 5000
    timeout client 10000
    timeout server 10000

frontend http-default
    bind *:80

    monitor-uri /haproxy?monitor%
```

Without the `-it` flags (just `docker exec <ID> cat /proxy.conf`) everything seems to work reliably and always produce the correct output.

**Comment by jfrazelle** [comment]
could it be the terrible wifi at the office.....

**Comment by nathanleclaire** [comment]
I don't think it's related to WiFi in particular: I have a wired connection (frequently turning WiFi off completely) and that wouldn't really explain how the command without `-it` consistently works but the command with `-it` consistently produces truncated output.

**Comment by jfrazelle** [comment]
ah ok just making sure, wishing for a miracle lol

**Comment by nathanleclaire** [comment]
:D I hear ya

**Comment by nathanleclaire** [comment]
Update on this : I'm getting the same behavior with `-H unix:///var/run/docker.sock` when SSH'ed into the server

**Comment by jfrazelle** [comment]
that is weird

**Comment by phemmer** [comment]
Could be completely unrelated, but docker compose also has missing output issues when TTY mode is enabled (https://github.com/docker/compose/issues/1229).
Smells like there might be a common issue.

**Comment by jfrazelle** [comment]
trying this now

**Comment by jfrazelle** [comment]
I get the whole thing :(

**Comment by LK4D4** [comment]
Maybe missing flush in terminal. I recently learned that `Close` not flushes files.

**Comment by nathanleclaire** [comment]
OK I can't dupe this on another server so I'll close... Sorry for the noise, I'll re-open if I can come up with something reproducible.

**Comment by jfrazelle** [comment]
wait im so curious please ping me

**Comment by gravityrail** [comment]
I'm definitely seeing the same truncated output issue running "docker-compose run (hostname) cat somefile.txt", also on digitalocean. Would love to hear a fix.
