### ISSUE TITLE
Downloads/pulls count using API v2

### ISSUE THREAD

**Issue by nazar-pc** [docker/docker#12268]
Is there any way to get information about downloads/pulls count using v2 of docker register API, like https://registry.hub.docker.com/v2/repositories/mashape/docker-kong/stars/count/ for stars?
Needed for https://github.com/badges/shields/issues/415 and would be nice to have it in general.

**Comment by dmp42** [comment]
Docker HUB feature requests should be sent directly to https://support.docker.com

The registry API itself has a notification system (that is used by the hub to produce metrics), but what you ask for here is rather a Hub API access to said metrics.

Let me know how this goes.

**Comment by alexellis** [comment]
@dmp42 can I comment on this thread? I'm looking for some pull counts on Raspberry Pi derivative images for a Docker Captain talk. Do you know who to get in touch with?

**Comment by dmp42** [comment]
Hey @alexellis 

If what you are interested in is a new feature request on Hub/Cloud feature, then I would suggest reaching out to support indeed.

Otherwise, if what you want is just one-time ad-hoc data, can you touch base with @ManoMarks ?

I'll also give a ping to the "captains' majors" ;)
