### ISSUE TITLE
COPY *.somefile.conf makes dockerd *crash* during docker build

### ISSUE THREAD

**Issue by jedi4ever** [docker/docker#12267]
A simple Dockerfile:

```COPY *.somefile.conf somefile.conf```

makes my dockerd (1.5.0 , boot2docker) crash consistently

**Comment by duglin** [comment]
I can't seem to reproduce this. Can you share a full dockerfile that shows it?
Is the target (somefile.conf) a dir?  What files in your build context end with .somefile.conf ?

**Comment by jedi4ever** [comment]
@duglin sorry a bit more context:

the filename of the file is exactly `*.somefile.conf` , so a literal star is part of the filename

**Comment by duglin** [comment]
@jedi4ever good one! :-)  I'll take a look at it today

**Comment by duglin** [comment]
PR #12278 fixes this

**Comment by jedi4ever** [comment]
thx @duglin !

**Comment by duglin** [comment]
thanks for reporting it!
