### ISSUE TITLE
'docker pull scratch' does nothing sane

### ISSUE THREAD

**Issue by mmdriley** [docker/docker#12281]
Begin with an empty image store: `docker rmi -f $(docker images -q)`
Then try this: `docker pull scratch`

This worked in versions <= 1.5.

In version 1.5, the result is:
```
$ docker pull scratch
Pulling repository scratch
511136ea3c5a: Download complete 
FATA[0003] 'scratch' is a reserved name 
```

Note that Docker *does* go to the trouble of pulling an image.

After which this is the state of the image store:
```
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
<none>              <none>              511136ea3c5a        22 months ago       0 B
```

The image is downloaded but remains anonymous.

[This commit](https://github.com/docker/docker/commit/8936789919c5c8004f346f44a3452d1521818b60) started treating `scratch` as a "special case". Reasonable discussions can be had about whether or not that was a good idea, but the behavior of `docker pull scratch` is clearly incorrect. Either the command should be rejected before the image is downloaded or the command should run to completion successfully.

**Comment by resouer** [comment]
#dibs we'd like to have a look into this

**Comment by thaJeztah** [comment]
Thanks, @resouer. Don't forget to include `closes #12281` in the description of your pull-request.

**Comment by dalanlan** [comment]
That is odd indeed. 
From where i stand, it's better to reject the `pull` request of the client from the very beginning.Tell me if u have any objection. 
@thaJeztah @dmcgowan

**Comment by dalanlan** [comment]
@WIZARD-CXY
