### ISSUE TITLE
HTTP_PROXY setting breaks socket-based cli connections

### ISSUE THREAD

**Issue by ewindisch** [docker/docker#12298]
If the HTTP_PROXY setting is set, socket-based connections fail:

```
$ HTTP_PROXY=bob \
  DOCKER_HOST=unix:///var/run/docker.sock \
  docker ps
FATA[0000] Error response from daemon: 404 page not found
```

Whereas the following works fine:

```
$ DOCKER_HOST=unix:///var/run/docker.sock \
   docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

**Comment by thaJeztah** [comment]
Is this on the current 1.6-rc? Because I think I remember some change being made recently to prevent http_proxy being applied to the socket. Will have to look up the PR

**Comment by thaJeztah** [comment]
Found it; https://github.com/docker/docker/pull/10739

**Comment by thaJeztah** [comment]
Just tested this, and I'm unable to reproduce this on `1.6-rc4`.

@ewindisch this should be fixed in 1.6. Perhaps you are able to test this with the current release-candidate, they can be found here; https://github.com/docker/docker/pull/11635#issuecomment-90205104

**Comment by ewindisch** [comment]
Yes, sorry, my mistake!

**Comment by thaJeztah** [comment]
No problem, thanks for confirming!
