### ISSUE TITLE
pkg/stdcopy NewStdWriter function has wrong doc comment

### ISSUE THREAD

**Issue by runcom** [docker/docker#12316]
`pkg/stdcopy` `NewStdWriter` function has wrong doc comment, `utils` is not correct, should be `stdcopy`
https://github.com/docker/docker/blob/master/pkg/stdcopy/stdcopy.go#L55

**Comment by runcom** [comment]
@thaJeztah could you add exp/beginner to this please? :)

**Comment by xiaods** [comment]
#dibs

**Comment by cpuguy83** [comment]
Closed by #12326
