### ISSUE TITLE
Error while doing import for a redhat base image

### ISSUE THREAD

**Issue by sagiegurari** [docker/docker#12311]
I created a base image tar file from one of our redhat machines.
I than took that tar to another redhat machine on which i have docker installation and i ran import but it fails.

I took the import command from the docker docs:
`
cat ./rhel64.tar | sudo docker import - exampleimagelocal:new
`

and the error i'm getting:
`
FATA[0051] Error: Driver devicemapper failed to create image rootfs 9d40582502573f5f4e34475fe6d0ae39cb4442f6ad493d7130161698dbc5bcf8: Error running DeviceCreate (createSnapDevice) dm_task_run failed
`

Docker info:
Containers: 0
Images: 0
Storage Driver: devicemapper
 Pool Name: docker-8:2-920680-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 0 B
 Data Space Total: 107.4 GB
 Metadata Space Used: 577.5 kB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: native-0.2
Kernel Version: 2.6.32-504.el6.x86_64
Operating System: <unknown>
CPUs: 2
Total Memory: 3.743 GiB

**Comment by sagiegurari** [comment]
sorry, seems I had an issue with my installation of docker and it got corrupted.
I did uninstall, removed the entire /var/lib/docker and install again and it worked.

**Comment by thaJeztah** [comment]
No problem, thanks for reporting back and closing; much appreciated!
