### ISSUE TITLE
Interactive container hangs when executing from a Java Application

### ISSUE THREAD

**Issue by dbremmen** [docker/docker#12319]
Hi!

I'm trying to execute an interactive container from a Java Application (I'm building an online free Java compiler). But for some reason the termination signal is not received and the Java application thinks that the program continues running (Docker version 1.5.0, build a8a31ef)
The attached code hangs on the process.waitFor(). But if I remove the -i flag the program runs ok
Maybe this issue is related to this other fixed before -> https://github.com/docker/docker/issues/6509
I need the program to run with the -i flag due that I want to execute interactive Java programs inside the docker container. Also I tried with the -t flag but Java does not provide a TTY so it fails to execute.

One thing that I cannot figure out is why the docker command works from the command line but no from the java application, maybe the difference is that I have a TTY when I execute the command from the command line

<pre>
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;

public class Test {
	
	public static void main(String[] args) throws Exception {
		Process process = Runtime.getRuntime().exec("sudo docker run -i ubuntu ls");
		int returnCode = process.waitFor();
		System.out.println("returnCode: " + returnCode);
		System.out.println("output: " + output(process.getInputStream()));
	}
	
	private static String output(InputStream inputStream) throws IOException {
		StringBuilder sb = new StringBuilder();
		BufferedReader br = null;
		try {
			br = new BufferedReader(new InputStreamReader(inputStream));
			String line = null;
			while ((line = br.readLine()) != null) {
				sb.append(line + System.getProperty("line.separator"));
			}
		} finally {
			br.close();
		}
		return sb.toString();
	}
}
</pre>

**Comment by vdemeester** [comment]
Seems like it might be related to #11957 :(

**Comment by cpuguy83** [comment]
I'm not sure that this is a bug.
When `-i` is set, the client does a hijack. The hijack will block until we receive an EOF (or any error) from stdin.
https://github.com/docker/docker/blob/master/api/client/hijack.go#L228
When stdin is a TTY the client will not block waiting for stdin: https://github.com/docker/docker/blob/master/api/client/hijack.go#L250-L255

@vdemeester WDYT? I think we can close this.

**Comment by cpuguy83** [comment]
Actually, I take that back, this is a bug. Let me see how difficult it is to fix.
