### ISSUE TITLE
Add detection for F2FS and JFS backing filesystem

### ISSUE THREAD

**Issue by UserTaken** [docker/docker#12324]
I've been testing the somewhat recently merged OverlayFS on a variety of filesystems when I noticed that `docker info` only recognizes `Ext2/3/4` and `ReiserFS`. Using `XFS`, `F2FS`, or `JFS` will result in `Backing Filesystem: <unknown>` although Docker seems to still works as normal as far as I can tell.

```
$ docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

**Comment by thaJeztah** [comment]
Detection for XFS was recently added in https://github.com/docker/docker/commit/dd56fa190695a969673f6f663cd5fe78b7c22787#diff-eb198973865e44ce0284717e90818e60, Not sure about F2FS (I see this reference in docker 1.5 https://github.com/docker/docker/blob/v1.5.0/daemon/graphdriver/driver.go#L27 but I could be wrong there; not sure if that is for F2FS)

Are you able to test this on a 1.6 release candidate? They can be found here; https://github.com/docker/docker/pull/11635#issuecomment-90205104

**Comment by thaJeztah** [comment]
> although Docker seems to still works as normal as far as I can tell.

Almost forgot to mention that part; Docker showing `<Unkown>` should be harmless; checking the underlying filesystem is used to warn for *known* incompatible combinations; outputting them as part of `docker info` is a nice extra, and can help debugging issues.

**Comment by estesp** [comment]
correct, it's probably good to add more known filesystems, but won't actually impact Docker runtime at all. We can add f2fs and jfs logging to backing filesystems.

**Comment by thaJeztah** [comment]
I updated the title, so that the "hunt for finding the correct magic bits" can start :)

**Comment by kostickm** [comment]
#dibs

**Comment by thaJeztah** [comment]
That was quick, thanks @kostickm!

**Comment by kostickm** [comment]
No problem :) @thaJeztah

**Comment by thaJeztah** [comment]
@UserTaken I reopened the issue, it will be closed automatically once #12345 is merged :)

**Comment by thaJeztah** [comment]
@UserTaken the PR was merged, which means this will be part of the 1.7 release (1.6 is just around the corner, so probably too late for that).

If you're adventurous and want to test it (**not** on a production / critical machine!), you can download the latest build from https://master.dockerproject.com

**Comment by UserTaken** [comment]
@thaJeztah I compiled the Docker binary and XFS, F2FS, JFS are all being recognized :)

**Comment by thaJeztah** [comment]
Thanks for testing @UserTaken, good to hear it's all working.
