### ISSUE TITLE
Removed Container starts automatic after time?

### ISSUE THREAD

**Issue by diezcode** [docker/docker#12323]
Hi,
Ich have a Problem with the docker containers. I stop a container and remove them. After a time the container starts alone and runs. Why? I have removed that container.

sudo docker stop
sudo docker rm

**Comment by ehazlett** [comment]
@diezcode thanks for the report.  would you mind adding the version of Docker you are using and the command and args you started the container with?

**Comment by diezcode** [comment]
In wich Path are the docker Container saved?

**Comment by cpuguy83** [comment]
@diezcode Do you have something in an init config (like upstart/systemd/sysvinit) that could be creating these containers, or some other tool?

We really need more information here.

Closing due to a lack of information after requested (and not likely to be a docker issue).
