### ISSUE TITLE
docker login fails from CLI when password contains URI character

### ISSUE THREAD

**Issue by sjoerdmulder** [docker/docker#12332]
Got locked-out of my account when trying to login with CLI and a password that looked something like:
```
docker login -e "myemail@example.org" -u "myuser" -p "f%xqN&PT"
```
When changing my password in the web interface to a variant without the special charaters like `%` and `&` i can login.

**Comment by thaJeztah** [comment]
@sjoerdmulder can you add the output of `docker version`?

**Comment by Mashimiao** [comment]
I tested with master, and logined success with special characters.

**Comment by sjoerdmulder** [comment]
```
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

**Comment by HuKeping** [comment]
test with "h%32@1.com" and passed.

**Comment by aaronlehmann** [comment]
@sjoerdmulder, are you still able to reproduce this? If so, what docker version are you running?

**Comment by sjoerdmulder** [comment]
Nope, i have retested this with version 1.7.1 with a password containing `#€!@&` chars. 
```
Login Succeeded
```
