### ISSUE TITLE
check statusCode from sockRequest

### ISSUE THREAD

**Issue by runcom** [docker/docker#12335]
`sockRequest` from ` integration-cli/docker_utills.go` now returns `http.Response.StatusCode` as its first return value. https://github.com/docker/docker/blob/master/integration-cli/docker_utils.go#L301

It would be great if response's status code it's checked where it makes sense
some examples to look for:
https://github.com/docker/docker/blob/master/integration-cli/docker_api_containers_test.go#L32

**Comment by ahmetalpbalkan** [comment]
#dibs

**Comment by ahmetalpbalkan** [comment]
@runcom `sockRequest` already includes the status code in the returned error message, however there are some test cases that do checks like `strings.Contains(err.Error(), "201 Accepted")`, I'm cleaning up those with the new status code retval.

**Comment by runcom** [comment]
Yes I've seen that too, also I don't super like the fact that it's raising the error if code is not 200, should be error if something went wrong with the request (at least 500+ are server errors that can make sense to die with)  , wdyt?

**Comment by ahmetalpbalkan** [comment]
@runcom my rule of thumb for defining success is generally `statusCode/100 != 2` :)

However in this case this allows us to catch cases where someone changes an existing endpoint's success response previously defined as `200 OK` to `201 Accepted` (or something else). This may break some clients (and thus back-compat in Remote API). Let's keep it.

**Comment by runcom** [comment]
Yes maybe I expressed my thought wrongly, I totally agree with your changes and I was referring for the 200/201 fact, maybe I don't recall correctly and what I said is just done :)
