### ISSUE TITLE
Cron within container does not run

### ISSUE THREAD

**Issue by amamut** [docker/docker#12336]
I have an image built with ubuntu:14.04 which has some cron job which trigger. When I run the container locally, on Ubuntu 14.04 machine, cron jobs trigger just fine. But when the container is run on a Google Cloud VM running CoreOS 607.0.0 cron jobs do not trigger at all. Container says that cron service is running but the log does not display any run logs.

Any help is appreciated

**Comment by unclejack** [comment]
@amamut Some actual commands, Dockerfiles involved, step by step instructions would help and  output from `docker info`, and `docker version`. There's no way to help without all the bits of information.

**Comment by jdmarshall** [comment]
Err, I thought this was a known issue?  Docker doesn't run initd, and therefore cron doesn't work.

Has that changed in recent builds?  I thought fixing this was still on the roadmap for later.

(If all else fails, phusion's baseimage-docker has a workaround for this, but it bends the Docker philosophy considerably to do it)

**Comment by amamut** [comment]
I figured out the issue. I just created an entrypoint starting cron && apache. Problem was that I was separating the 2 and cron wasn't running.

Seems to be working now. Thanks!
