### ISSUE TITLE
docker rmi tries to delete tagged parents and throws error 

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [docker/docker#12339]
Description of problem:

I'm experiencing the issue described here: https://bugzilla.redhat.com/show_bug.cgi?id=1097884

Basically, when having one image (hash aaa) with 2 different tag names (a1:latest and a2:latest), and creating a new image (hash bbb) based on that one, if I try to remove the new image I get this error: `Error response from daemon: Conflict, cannot delete image aaa because it is tagged in multiple repositories, use -f to force`.

`docker version`:
```
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

`docker info`:
```
Containers: 1
Images: 59
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 61
Execution Driver: native-0.2
Kernel Version: 3.13.0-37-generic
Operating System: Ubuntu precise (12.04.5 LTS)
CPUs: 8
Total Memory: 23.54 GiB
Name: eu-101
ID: 2EUQ:AEZP:RMRE:QGI6:SL4P:TAKA:3XA7:DC5U:ILXR:TLT4:3WEV:IKHI
Debug mode (server): false
Debug mode (client): true
Fds: 11
Goroutines: 14
EventsListeners: 0
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker
WARNING: No swap limit support
```

`uname -a`:
```
Linux eu-101 3.13.0-37-generic #64~precise1-Ubuntu SMP Wed Sep 24 21:37:11 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.):
Physical

How reproducible:
Almost always, but it seems to be some timing issue involved too, as described in the linked issue.

Steps to Reproduce:
See https://bugzilla.redhat.com/show_bug.cgi?id=1097884#c10

Actual Results:
Error reported, exit status != 0 even when the image is properly removed (which breaks scripts expecting exit status of 0).

Expected Results:
Image removed without any errors

**Comment by coolljt0725** [comment]
@leandro-lucarella-sociomantic This is fixed by https://github.com/docker/docker/pull/11011, can you try the master?

**Comment by cpuguy83** [comment]
Closing as this is resolved.
