### ISSUE TITLE
Contributor Guide git push after rebase needs -f

### ISSUE THREAD

**Issue by bboreham** [docker/docker#12337]
The last `git push` at the bottom of https://docs.docker.com/project/work-issue/#pull-and-rebase-frequently will fail, I think, unless it has `-f` added.

This is because the tip of the current branch will not match the remote repository, so Git will reject the update.

**Comment by thaJeztah** [comment]
Yes, sounds correct, well spotted! Are you willing to make a pull-request?

**Comment by thaJeztah** [comment]
Oh, and if you *are* planning a PR; please check if there isn't an existing issue covering this (I know there were some recently)

**Comment by draghuram** [comment]
I too found the missing "force" option when I had to update my PR recently. @bboreham, I can submit the change if you don't want to.

**Comment by bboreham** [comment]
@draghuram, you appear to have found a different issue, so I did my own PR.

@thaJeztah, I have searched for this in previous issues, but 'git' and 'push' are rather common terms so I cannot guarantee it.  #12252 is in the same file, on a different line.

**Comment by thaJeztah** [comment]
@bboreham I know, it's difficult to search those. You're probably fine :smile:
