### ISSUE TITLE
All docker containers exit with `FATA[2426] unexpected EOF`

### ISSUE THREAD

**Issue by AntouanK** [docker/docker#12330]
I have a CoreOS machine, running 10 containers.
Most of them are microservices with io.js/express ( there's also a MongoDB and a REDIS db ).
I noticed a couple of times all of them exited together(!).
Here's `docker ps -a` after the "crash"
![screen shot 2015-04-13 at 12 24 56](https://cloud.githubusercontent.com/assets/4569111/7114767/70362a34-e1d8-11e4-9e25-6b2faba01aa5.png)

And here's `docker logs -ft entry-layer` terminated from the crash
![screen shot 2015-04-13 at 12 25 16](https://cloud.githubusercontent.com/assets/4569111/7114770/83771414-e1d8-11e4-9974-83a8f630c903.png)
( note: if I try to print the logs again, I don't see that error code, which is not helpful. I wouldn't see that error if I didn't have that terminal running, right? Is there another way to catch it? )

Where is this error coming from? I mean it has to be docker related, since it makes all the containers to crash somehow... Or is it related with CoreOS?
Any idea where to see the error codes and debug it somehow?

Thanks.

**Comment by phemmer** [comment]
Smells like your box is running out of memory and the kernel is killing things trying to get some back.

Try logging into the box and running `dmesg`. Look for out of memory alerts (search for the text `Out of memory`).

**Comment by phemmer** [comment]
Oh, and if you're using coreos, it's also possible the box is doing it's automatic upgrade. Check `uptime` on the box to see if it's rebooted. Also check `journalctl -u docker.service` to see if the docker daemon is being restarted for some other reason.

**Comment by AntouanK** [comment]
@phemmer Sounds like you found it.
```shell
[1777343.640585]  [<ffffffff81141d2f>] out_of_memory+0x4bf/0x4f0
[1777343.959234] Out of memory: Kill process 19062 (node) score 235 or sacrifice child
```

So should I limit the memory on each container? or do I just increase the RAM in my VM?

Thanks.

**Comment by AntouanK** [comment]
Also, how can I see how much memory each container asks for?
Is that still not provided somehow? ( http://stackoverflow.com/questions/18956063/memory-usage-of-docker-containers )

**Comment by cpuguy83** [comment]
@AntouanK If prod, always setup RAM/CPU limits for your containers :)

You can see what individual processes are using in the container with `docker top <container>`
You can see the overall cpu/mem/net usage via `docker stats <container>`

**Comment by AntouanK** [comment]
Of course there is a `stats` command... 
https://docs.docker.com/reference/commandline/cli/#stats
I should check the CLI first...
Thanks @cpuguy83

**Comment by cpuguy83** [comment]
Are we good to close this issue?

**Comment by AntouanK** [comment]
Yeah. Thanks for the help...

**Comment by cpuguy83** [comment]
The status codes you see from `docker ps` are from the application in the container, not Docker,
Is that what you're referring to?

**Comment by AntouanK** [comment]
@cpuguy83 Well, those `FATAL[0000]` type of errors are from Docker, right?
Check the screenshots above to see what I mean.

**Comment by phemmer** [comment]
Yes, but they're from the docker client. The OOM killer likely killed the docker daemon on the remote host, so your docker client dumped that EOF error because it lost the connection.

**Comment by AntouanK** [comment]
Yeah, sounds like it. My current issue is completely solved.
I'm saying, just for future reference, is there a list somewhere to see that error code `2426` refers to for example?

**Comment by cpuguy83** [comment]
I'm pretty sure that's a timecode or something from the logger.
