### ISSUE TITLE
Fix vet warning in pkg/chrootarchive/archive.go

### ISSUE THREAD

**Issue by LK4D4** [docker/docker#12343]
```
pkg/chrootarchive/archive.go:99: arg output for printf verb %s of wrong type: bytes.Buffer
```
This can be done by replacing `var output bytes.Buffer` with `output := bytes.NewBuffer(nil)` and removing `&` below. Or with adding `String()` method call to `output` in error.
sorry @estesp . I was wrong :)

**Comment by estesp** [comment]
ha.. I can't believe it! You have never been wrong in my history of knowing you!! :)  But I will forgive you this time :)

**Comment by thaJeztah** [comment]
!m @LK4D4 :smile:

**Comment by kostickm** [comment]
#dibs
