### ISSUE TITLE
integration-cli dockerCmd function doesn't return error

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#12355]
In `integration-cli/docker_utils.go` is a function used in many many places in the integration-cli tests called `dockerCmd`.

This functions signature is: `func dockerCmd(t *testing.T, args ...string) (string, int, error)`
However, `error` is never returned since it fails out the test with: `t.Fatalf("%q failed with errors: %s, %v", strings.Join(args, " "), out, err)` if there is an error.

Then any code calling this function is also doing a redundant check for this non-existent error.

The error from the return on `dockerCmd` should be removed and all calling code updated to reflect that.

**Comment by xiaohui** [comment]
I will try. #dips

**Comment by thaJeztah** [comment]
@xiaohui you might want to check with @robertabbott. it looks like he's working on this (but he didn't "claim" the issue)

**Comment by robertabbott** [comment]
@thaJeztah, @xiaohui  I am working on it, but I can yield this issue since i didn't follow the protocol. Now i get the claiming system. Sorry

**Comment by thaJeztah** [comment]
I'll leave it up to you both :smile:

**Comment by xiaohui** [comment]
@robertabbott first comer, first contribute, you could continue do it :-)

**Comment by robertabbott** [comment]
@xiaohui Thanks. I'll make sure to officially claim it next time.

**Comment by thaJeztah** [comment]
Thanks both!
