### ISSUE TITLE
make build failed because fmp

### ISSUE THREAD

**Issue by Mashimiao** [docker/docker#12359]
$ docker version
Client version: 1.5.0-dev
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 11c01d9-dirty
OS/Arch (client): linux/amd64
Server version: 1.5.0-dev
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 11c01d9-dirty
OS/Arch (server): linux/amd64
When I used 'sudo make build', I got the following error message:
ERROR:  Could not find a valid gem 'fpm' (= 1.3.2) in any repository

**Comment by jfrazelle** [comment]
Can you give the full output, also docker info

**Comment by Mashimiao** [comment]
$ docker version
Client version: 1.5.0-dev
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 2616c8e-dirty
OS/Arch (client): linux/amd64
Server version: 1.5.0-dev
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 2616c8e-dirty
OS/Arch (server): linux/amd64
[mashimiao@G08FNSTD121139 docker]$ docker info
Containers: 4
Images: 50
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.3-200.fc21.x86_64
Operating System: Fedora 21 (Twenty One)
CPUs: 4
Total Memory: 7.651 GiB
Name: G08FNSTD121139
ID: L7FA:TYOX:UBYN:YIGG:IOU2:BVSN:MVB6:NMSW:GB3C:XZIO:XIZS:PI7X
Username: mashimiao
Registry: [https://index.docker.io/v1/]

**Comment by jfrazelle** [comment]
pretty sure something is wrong with your clone because it should be fpm not
fmp

**Comment by Mashimiao** [comment]
Step 22 : RUN http_proxy="http://10.167.225.56:8123" gem install --no-rdoc --no-ri fpm --version 1.3.2
 ---> Running in ad3d684f4f64
ERROR:  Could not find a valid gem 'fpm' (= 1.3.2) in any repository
ERROR:  Possible alternatives: fpm

**Comment by Mashimiao** [comment]
I think maybe my network setting cause this issue.
It sometimes fails but sometimes works

**Comment by thaJeztah** [comment]
@Mashimiao so, this issue can be closed?

**Comment by Mashimiao** [comment]
Yes, Thanks

**Comment by thaJeztah** [comment]
Thanks! And good to hear it is resolved for you
