### ISSUE TITLE
Containers can not connect after docker update

### ISSUE THREAD

**Issue by ali-bugdayci** [docker/docker#12364]
After I updated the docker, my containers can not connect to remote host:

```
# d run -i -t busybox wget google.com
Connecting to google.com (216.58.209.14:80)
wget: can't connect to remote host (216.58.209.14): Connection refused
```

At first I thought it was a networking problem, but after 
* purging all the docker packages 
* removing the docker bridge:
``` 
  ip link set dev docker0 down
  brctl delbr docker0
```
* installing the latest one

I still get the error. The container can ping, so it shouldn't be a networking problem:

```
# d run -i -t busybox ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=51 time=18.099 ms
```

My host computer can wget :
```
# wget google.com
--2015-04-14 11:09:56--  http://google.com/
Resolving google.com (google.com)... 216.58.209.14, 2a00:1450:4017:803::200e
```

But my container can not still wget. My ifconfig is:

```
docker0   Link encap:Ethernet  HWaddr 56:84:7a:fe:97:99  
          inet addr:172.17.42.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::5484:7aff:fefe:9799/64 Scope:Link
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:35 errors:0 dropped:0 overruns:0 frame:0
          TX packets:54 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:2116 (2.1 KB)  TX bytes:7552 (7.5 KB)
```

Some config that you might be necessary: 

```
 /etc/resolv.conf 
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 127.0.0.1

-------------------

# uname -a
Linux bor-asus4 3.8.0-39-generic #57~precise1-Ubuntu SMP Tue Apr 1 20:04:50 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

-------------------

# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04 LTS
Release:        14.04
Codename:       trusty

-------------------

# d -v
Docker version 1.5.0, build a8a31ef
```

Any comments on how I can connect from the containers is highly appreciated!!!

**Comment by LK4D4** [comment]
Actually I experiencing such problems too. In different situations, for example up wifi interface in addition to ethernet, new bridge etc.
@ali-bugdayci You can try to flush your iptables rules and restart docker.

**Comment by mavenugo** [comment]
@ali-bugdayci Can you pls check if this is is related to : #11407 (comment)

**Comment by thaJeztah** [comment]
ping @ali-bugdayci is this still an issue, also, did you check the comment that @mavenugo linked to?

**Comment by ali-bugdayci** [comment]
Hi,

thanks for the update. I switced PC so I do not see this error anymore. I am closing it for the timebeing.

**Comment by thaJeztah** [comment]
Thanks @ali-bugdayci !
