### ISSUE TITLE
Docker file ADD with URL should using cache without download

### ISSUE THREAD

**Issue by feiyang21687** [docker/docker#12361]
We have a Dockerfile like below:

```
...
ADD https://dl.bintray.com/mitchellh/consul/0.5.0_linux_amd64.zip /tmp/consul.zip
...
```

And docker will download consul.zip every time, and check whether to use cache:

```
Step 2 : ADD https://dl.bintray.com/mitchellh/consul/0.5.0_linux_amd64.zip /tmp/consul.zip
Downloading [==================================================>]  4.67 MB/4.67 MB
 ---> Using cache
 ---> 34992f807865
```

Why not just check the URL first to decide whether to use cache, that will save build time. 

I know the remote zip file will be changed, but there has clear cache ability of docker build, so I think it's not a problem.

**Comment by vdemeester** [comment]
I think it's documented, or at least it should. It's kind of a design decision, because some servers do not respect the Cache/Expire & co HTTP headers. How would you decided to use cache or not without checking these headers ?

**Comment by duglin** [comment]
yea this has been discussed before. See this comment/issue:  https://github.com/docker/docker/issues/3672#issuecomment-63335989
Closing for now

**Comment by feiyang21687** [comment]
I check the source code ```docker/builder/internals.go```

```calcCopyInfo``` do the actual download and hash calc:

```
247: 		ci.hash = origPath // default to this but can change
...
338:		ci.hash = tarSum.Sum(nil)
```

And the immediate image is like this, which records ```tarsum+sha256:${hash}```

```
76db7611922b0844b471deece86ed7511afe0ee292712ff2b929f7370b45dac3   42 hours ago        /bin/sh -c #(nop) ADD tarsum+sha256:7f661c42f46b302d16a2a880f9a9b17a85d6f3c80dd6baaa56be8c2026f56564 in /tmp/consul.zip    4.67 MB
```

the ```probeCache``` function will lookup the image with the same hash value.

Why not delete ```ci.hash = tarSum.Sum(nil)```, in order to keep the hash value is origPath, and  ```probCache``` before do actual downloading.

**Comment by duglin** [comment]
@feiyang21687 I'm not following.  We can't do the hash calculation until we download it.

**Comment by feiyang21687** [comment]
@duglin I know, but why not just only use ```path``` as hash, so we can check the image cache before downloading.

**Comment by duglin** [comment]
@feiyang21687 for the same reason we don't just look at the Last-Modified HTTP header - see: https://github.com/docker/docker/issues/3672#issuecomment-63335989
The decision was made to, basically, not trust things like the URL or timestamps, and instead actually check the data itself to make sure nothing has changed.
@erikh I assume you're still in that mode of thinking, right?

**Comment by erikh** [comment]
Aye, although a sum of the first n bytes would probably be sufficient for moderate sizes of n.

-Erik

**Comment by daald** [comment]
@feiyang21687. I just found this thread because I wanted to know how `ADD <url>` works. And it's good that it checks the content. If you don't care about the contents, you can simply do a `RUN wget <url>` or `RUN curl <url>` (which only hashes the commandline = url).
But there are reasons where people need a file hash. For example I can use `ADD http://debianmirror/dists/jessie/Release /tmp/tmpfile` to make sure that the docker cache is only used if the debian mirror didn't change.

**Comment by kingces95** [comment]
Why not add an option to ADD like `ADD [--cache] <url>` that allows the author to indicate the stability of the url?
