### ISSUE TITLE
Remove sprious `fmt.Printf` from test

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#12378]
In `integration-cli/docker_cli_exec_test.go` in `TestExecWithPrivileged` there is a spurious `fmt.Printf` that should be removed.

**Comment by coolljt0725** [comment]
sorry this  spurious `fmt.Printf` is caused by me, I use it for
local testing and forget to remove it when I push to github.
I just realize this today and thank god, it has been fixed.
Thank you all.

**Comment by thaJeztah** [comment]
No worries, @coolljt0725 the maintainers also should have spotted this when reviewing, just blame them 😇

**Comment by jfrazelle** [comment]
also we are all human :)
