### ISSUE TITLE
$HOME set to / instead of user home directory...

### ISSUE THREAD

**Issue by totobgycs** [docker/docker#12389]
...when runing [totobgycs/archjava](https://hub.docker.com/u/totobgycs/archjava/), an Archlinux image on a Linux Mint host.

`docker version`:

```
Client version: 1.0.1
Client API version: 1.12
Go version (client): go1.2.1
Git commit (client): 990021a
Server version: 1.0.1
Server API version: 1.12
Go version (server): go1.2.1
Git commit (server): 990021a
```
`docker info`:

```
Containers: 13
Images: 117
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 143
Execution Driver: native-0.2
Kernel Version: 3.13.0-24-generic
Username: totobgycs
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support
```

`uname -a`:

```
Linux osiris 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
Environment details (AWS, VirtualBox, physical, etc.):
Host is a physical machine

How reproducible:

```
docker run -it -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix:ro totobgycs/archjava /bin/bash -c 'echo $HOME'
```

Actual Results:

```
/
```

Expected Results:

```
/home/eclipse
```

Additional info:

The user is eclipse in the image. When runing the same image on an Archlinux host, the HOME is set as expected to /home/eclipse.

`uname -a` for the Archlinux:

```
Linux docker 3.19.2-1-ARCH #1 SMP PREEMPT Wed Mar 18 16:21:02 CET 2015 x86_64 GNU/Linux
```

**Comment by cpuguy83** [comment]
This is likely because you are on an older docker version.
Can you try with a more recent version of Docker?

**Comment by totobgycs** [comment]
Thanks. With version 1.5 works good.

**Comment by tersmitten** [comment]
I have the same problem:

```
# sudo docker run -i -t ubuntu:10.04 /bin/bash -c 'echo $HOME';
/
```

```
# sudo docker run -i -t ubuntu:12.04 /bin/bash -c 'echo $HOME';
/root
```

Is this a docker or image issue?

I'm using `Docker version 1.7.0, build 0baf609`
