### ISSUE TITLE
hack/install.sh should encourage installation of linux-image-generic on Ubuntu

### ISSUE THREAD

**Issue by z0u** [docker/docker#12386]
I installed Docker on Ubuntu 14.04 under OpenStack using the [standard install script][is], built some images and then started some containers. Then I ran a `dist-upgrade` on the host, which installed a new kernel version, and rebooted. When the machine came back up, all my containers and images were missing.

I think this is because the `aufs` kernel module was missing from the new kernel. I don't know for sure, because in the process of debugging this I deleted the stuff in `/var/lib/docker`. Oops :)

I think the reason this happened is:

- The installation script installs the `linux-image-extra...` package specific to the currently-running kernel.
- The OpenStack Ubuntu image doesn't come with `linux-image-generic` installed; it has `linux-image-virtual`, which does not depend on the `-extra` package.
- When I ran the upgrade, the kernel was upgraded but the `-extra` package was not, meaning the `aufs` driver went missing.

Perhaps the install script should show a warning if the `linux-image-generic` package is not installed?

`docker version`:
```
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

`docker info`:
```
Containers: 0
Images: 29
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 29
Execution Driver: native-0.2
Kernel Version: 3.13.0-49-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 4
Total Memory: 7.798 GiB
Name: foo
ID: bar
WARNING: No swap limit support
```

`uname -a`:
```
Linux foo 3.13.0-49-generic #83-Ubuntu SMP Fri Apr 10 20:11:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

[is]: https://get.docker.com/

**Comment by thaJeztah** [comment]
Thanks for reporting this, @z0u. We recently made some improvements in this area (see https://github.com/docker/docker/pull/11999). Docker will now scan which driver(s) was/were previously used and produce an error if that driver is no longer supported on your system.

I *think* that change didn't make it in docker 1.6, but will be in docker 1.7.

/cc @vbatts @tianon

**Comment by tianon** [comment]
I believe #10860 is definitely relevant here. :+1:

**Comment by z0u** [comment]
Thanks @thaJeztah, that sounds like a good solution.

Thanks @tianon. FWIW, installing `linux-image-generic` didn't change the kernel that was installed on my OpenStack instance.

**Comment by cpuguy83** [comment]
Closing since #10860 was merged which contains the warning.
