### ISSUE TITLE
Ubuntu upgrade instruction is not working.

### ISSUE THREAD

**Issue by chakrit** [docker/docker#12395]
On [ubuntu installation guide](https://docs.docker.com/installation/ubuntulinux/) page, at the bottom:

![2015-04-15 at 4 12 pm](https://cloud.githubusercontent.com/assets/45545/7155598/310304dc-e38a-11e4-9be9-54d64760d38e.png)

On an up-to-date Ubuntu system (14.04) the commands produces the following output:

```
root@ubuntu# wget -N https://get.docker.com/ | sh
--2015-04-15 05:13:05--  https://get.docker.com/
Resolving get.docker.com (get.docker.com)... 162.242.195.82
Connecting to get.docker.com (get.docker.com)|162.242.195.82|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6715 (6.6K) [text/plain]
Saving to: ‘index.html’

100%[===================================================================================================================================>] 6,715       --.-K/s   in 0s      

2015-04-15 05:13:07 (274 MB/s) - ‘index.html’ saved [6715/6715]
```

Where `index.html` contains the standard docker run script. Trying to forcibly run this script, prints a warning:

```
root@ubuntu# cat index.html | sh
Warning: "docker" or "lxc-docker" command appears to already exist.
Please ensure that you do not already have docker installed.
You may press Ctrl+C now to abort this process and rectify this situation.
+ sleep 20
^C
```

But of course since we're upgrading, `docker` and `lxc-docker` must already be installed. So what is the right way to proceed in this case? I think docs should be fixed.

**Comment by chakrit** [comment]
From reading the script, I think the right away to upgrade is to execute:

```
apt-get upgrade lxc-docker
```

Is that right?

**Comment by runcom** [comment]
@chakrit to upgrade docker un ubuntu you just sudo apt-get update && sudo apt-get upgrade (dist-upgrade also)

**Comment by draghuram** [comment]
Note that the actual upgrade command is

    $ wget -N -q0- https://get.docker.com/ | sh

This has been fixed in #12100.

**Comment by thaJeztah** [comment]
@chakrit I'm going to close this issue because I think the question was answered. The docs have been fixed in #12100. Those changes haven't been pushed to the website yet, but can be seen here https://docs.master.dockerproject.com/installation/ubuntulinux/#upgrade-docker

Feel free to continue the discussion after closing. Thanks!

**Comment by blitzd** [comment]
@thaJeztah the command on that page results in:

Warning: "docker" or "lxc-docker" command appears to already exist.
Please ensure that you do not already have docker installed.
You may press Ctrl+C now to abort this process and rectify this situation.
+ sleep 20

...the bit about not having docker already installed would seem to clash with the idea that this is a command to upgrade docker.

**Comment by thaJeztah** [comment]
thanks, @blitzd, I'm gonna call in a help-line here, because I currently don't have access to a computer to check;

@tianon @jfrazelle is the documented upgrade process the correct one? I agree the warning is confusing.

**Comment by tianon** [comment]
Using "get.docker.com" to upgrade is not unprecedented or unusual, but if
"docker" already exists and you didn't get it from our package, it could
cause trouble, which is the reason for the warning.  I'd be personally +1
to updating the warning to mention that if you installed using "
get.docker.com" previously and you're just upgrading now that the warning
is safe to ignore.

**Comment by thaJeztah** [comment]
thanks, @tianon, sounds reasonable. Could you do me one more favor and create an issue for that (typing on phone and such :D)
