### ISSUE TITLE
Can't determine Memory limits/usage from inside a container

### ISSUE THREAD

**Issue by jonquark** [docker/docker#12394]
When running e.g. an in-memory database inside a container it would be incredibly useful to be able to monitor memory usage and limits from inside the container in order to prioritize and cap certain classes of memory usage in low memory situations.

I'm aware there are some hacky work arounds (are there any I'm missing?):

1) Give the container access to /proc/self/cgroup as a volume:
 docker run -v /sys/fs/cgroup:/sys/fs/cgroup -it --name groupmeminfo -m 4g  fedora:latest /bin/bash

Then in the container I can see the limit and our usage:
bash-4.3# more /proc/self/cgroup | grep memory
4:memory:/system.slice/docker-898b44c4a066d2dc6343c21d8a5b7c6a77079367d23bcde8c88be0eb204d3a1e.scope
bash-4.3#  more /sys/fs/cgroup/memory/system.slice/docker-898b44c4a066d2dc6343c21d8a5b7c6a77079367d23bcde8c88be0eb204d3a1e.scope/memory.limit_in_bytes
4294967296
bash-4.3# more /sys/fs/cgroup/memory/system.slice/docker-898b44c4a066d2dc6343c21d8a5b7c6a77079367d23bcde8c88be0eb204d3a1e.scope/memory.usage_in_bytes
5013504

2) If the container is privileged you can mount the cgroup information:
mount -n -t cgroup -o memory cgroup /tmp/memory

But a more straight forward mechanism that didn't represent a security risk and didn't require extra complexity in running the container would be really handy.

**Comment by hqhq** [comment]
There is an experimenting here: https://github.com/docker/libcontainer/pull/528

**Comment by jonquark** [comment]
@hqhq  Thanks for the info, that (or an outcome to docker/docker#8427  which I found via your link) would address this.

**Comment by cpuguy83** [comment]
Closing since docker now mounts the cgroup into the container.

**Comment by Starefossen** [comment]
@cpuguy83 which version of Docker is this available from?

**Comment by cpuguy83** [comment]
@Starefossen This will be in docker 1.8.

**Comment by Starefossen** [comment]
Thanks 😄
