### ISSUE TITLE
Create unique user ID for increased security

### ISSUE THREAD

**Issue by wernight** [docker/docker#12392]
Following the best practice that you should not run as **root** inside the container, comes also the fact that a user ID (let's say 1000) may be mapped to user `foo` outside the container, as `bar` inside the container. This means that even though you'd want the container to access only `bar` data (either added during a build or mounted volume), it might also access `foo` data if it breaks outside the container (isn't it?).

One hacky solution would be to create a user inside the container with a **random ID**, but ideally we'd want to user inside the container to be **unique among the system**.

    # Random number in [200, 899] to avoid common uid:
    $ useradd --system --uid $((RANDOM % 700 + 200)) --shell /usr/sbin/nologin bar

Using this hack only works in many cases if one hardcodes the result else mounting writable for that user might get tricky.

I haven't seen this problem even being discussed so far. Is there a reason for it? Am I missing some security feature already in place?

**Comment by cpuguy83** [comment]
@wernight This wold be handled by support for user namespaces.
Please see gh11253

Closing this one, but if you feel like this doesn't address your concern, feel free to ping here.

**Comment by thaJeztah** [comment]
Adding the link to the user namespaces proposal; https://github.com/docker/docker/pull/11253

**Comment by wernight** [comment]
Thanks :)
