### ISSUE TITLE
Docker stop  can not stop a container with "restart policy ="always"" 

### ISSUE THREAD

**Issue by sunyc** [docker/docker#12397]
Well, it will just loop infinitely without clear indication.

I think docker stop should detect such container and warn the user.

**Comment by coolljt0725** [comment]
But how to stop a container with "restart=always" ?

**Comment by sunyc** [comment]
Docker kill apparently does the trick.

**Comment by cpuguy83** [comment]
`docker stop` should be stopping the container regardless of restart policy.
Can you provide output of `docker version` and `docker info`?

**Comment by sunyc** [comment]
docker 1.5 on ubuntu 14.04

**Comment by cpuguy83** [comment]
@sunyc Please paste the output of running those commands.

**Comment by sunyc** [comment]
I'm unable to reproduce it,  will reopen if did.
