### ISSUE TITLE
Docker Daemon need to check if the image is update-to-date version

### ISSUE THREAD

**Issue by allencloud** [docker/docker#12408]
Hi,

I found that image ubuntu:14.04 on differenet host both from Docker Hub has different image layer. And the two images indeedly are pull at different period of time.

So I think the image ubuntu:14.04 got updated on Docker Hub.

Such kind of case can cause some compitile issues when using base image.

Is there any necessary to add an API for Docker Daemon to check whether the base image is the same as one on Docker Hub?

**Comment by thaJeztah** [comment]
To make sure you're using the latest image when building an image, you can use `docker build --pull`, which was added in https://github.com/docker/docker/pull/9281

Does that solve your use case?

**Comment by cpuguy83** [comment]
I believe you can also reference images by immutable hashes now (or at least you'll be able to in 1.6).

**Comment by thaJeztah** [comment]
Ah, think you're right, will look up the feature request for that (was it merged already?)

I think it only works on a registry v2

**Comment by thaJeztah** [comment]
Proposal https://github.com/docker/docker/issues/10740 and implementation here https://github.com/docker/docker/pull/11109 :+1:

**Comment by unclejack** [comment]
PR #11109 has been merged to allow pulling an image by ID. `docker build --pull` makes it possible to build using the latest version of the image all the time.

I'll close this issue as the question was answered. Please feel free to comment.
