### ISSUE TITLE
It should be possible to distinguish between --restart=no and not specifying a restart policy

### ISSUE THREAD

**Issue by joshwilsdon** [docker/docker#12413]
With #10874 I wanted to make sure that the client sent an explicit `no` when you use `--restart=no`, unfortunately in "fixing" this issue the "fix" on that issue also changed the default value from `--restart=""` to `--restart="no"` which undoes all the advantage of having `--restart=no` pass through `RestartPolicy: "no"`. It means that we're once again in a situation where:

```
docker run -it ubuntu
```

and:

```
docker run --restart=no -it ubuntu
```

cannot be distinguished at the server. Previously they could not be distinguished because they would both show up to the API as `RestartPolicy: ""`. I filed #10874 with the intention that the first case continue to result in `RestartPolicy: ""` and the second case result in `RestartPolicy: "no"` so that they could be distinguished.

Unfortunately the change that was actually pushed instead means that in both cases the API will see `RestartPolicy: "no"` and they're still indistinguishable.

**Comment by trentm** [comment]
What would others thing of a configurable restart policy for the Docker daemon. Similar to
other daemon config vars: https://docs.docker.com/reference/commandline/cli/#daemon

Then change `docker run/create` to NOT specify a value for restart policy by
default. IOW, an empty value to the Remote API means "use the daemon's
configured default value".

**Comment by gdm85** [comment]
I have noticed this also when using API calls to retrieve/restore container configuration.

However, in my opinion, the default should be "no" and **always** enforced, with an empty value being an error (or eventually always normalized to "no", for legacy reasons).

The idea of *daemon's configured default* value would make it harder to get information about a container lifecycle by just using API calls, since you'd have to query the daemon options too to get the full picture.

**Comment by trentm** [comment]
@gdm85 Understood. The situation @joshwilsdon  and I are thinking about is allowing there to eventually be a way for a Docker *host* to restart (e.g. for upgrade or whatever) and know whether some of the containers it was hosting should be restarted when it comes back up.

Specifically we're working on [sdc-docker](https://github.com/joyent/sdc-docker), where the Docker engine is the whole DC and containers are running on separate physical servers in the data center. The question is what to do with the containers on a given server when that server reboots (e.g. for maintenance, OS upgrade, whatever)? In this case it would be nice to differentiate between:

```
docker run --restart no ...       # definitely don't restart the container, even on server reboot
docker run ...      # didn't specify restart policy, the Docker engine could consider restarting its containers on server reboot
```

**Comment by gdm85** [comment]
I think this ticket is a dup of #9319, which in turn is marked as a dup of #9678 ([my comment there](https://github.com/docker/docker/issues/9678#issuecomment-71102191).

The possibly fixing proposal is #8821, on that one I could agree and would also nicely cover your case (see [my comment there](https://github.com/docker/docker/issues/8821#issuecomment-60780486)).

Please also note that a desirable behaviour (in opposition to PR #11235) would instead be to default to ``daemon`` option.

Related:
* #11008
* #10874

**Comment by gdm85** [comment]
I guess this is fixed now because you have to always specify an explicit restart policy?

**Comment by icecrime** [comment]
I believe that's the case indeed, thanks @gdm85!
