### ISSUE TITLE
boot2docker setup: make test fails in test TestInitializeCannotStatPathFileNameTooLong

### ISSUE THREAD

**Issue by rustogi** [docker/docker#12410]
Description of problem:

make test fails with 
--- FAIL: TestInitializeCannotStatPathFileNameTooLong (0.00s)
        volume_test.go:56: Expected to get ENAMETOOLONG error, got stat ivZgXsMAvLAYitpGtstNvMXsAaAVBmToJKPxJVufDWaiBQQslaOhPAoEuIjbVkMcmDgJgkfobtzfZolRdQoaheGbhjnxzkvihGxbmnSySnAbwimRPMFxrJcxuiwsQaQgChZshHzNRRAxQyfPepZcKWmcFjtXQoFCyMIPPsIMJXvKipMxgPXeROmvaabKYFjnJYVHzmliRDpvIHgazZEtFKXBBjWHZQbzsFFcXUvVYRolrzHDJqzmagfkxzxKWjGwshQrEbbVLsmHcgMxevSjaIIqigrpoahVQcrNLFssLHoQ: protocol error

Test environment:

On a mac (OS X 10.9.5) using boot2docker (1.5.0) and docker (1.5.0 - came with boot2docker). 
In the build docker container running in Virtualbox

`docker version`:

Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): darwin/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

`docker info`:

Containers: 2
Images: 46
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 50
Execution Driver: native-0.2
Kernel Version: 3.18.5-tinycore64
Operating System: Boot2Docker 1.5.0 (TCL 5.4); master : a66bce5 - Tue Feb 10 23:31:27 UTC 2015
CPUs: 8
Total Memory: 1.961 GiB
Name: boot2docker
ID: 3M76:UYVC:AQ6C:VPU4:L3LE:KJOM:QRBH:RLII:JCQO:7HV4:L3XD:7EDO
Debug mode (server): true
Debug mode (client): false
Fds: 20
Goroutines: 29
EventsListeners: 0
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker

`uname -a`:

Darwin xxxxxxxxx 13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; xxxxxxxx/RELEASE_X86_64 x86_64

Environment details (AWS, VirtualBox, physical, etc.):

VirtualBox (boot2docker): uname -a

Linux boot2docker 3.18.5-tinycore64 #1 SMP Sun Feb 1 06:02:30 UTC 2015 x86_64 GNU/Linux

How reproducible:

Every time

Steps to Reproduce:
1. Setup development environment on Mac OS X using boot2docker as per https://docs.docker.com/project/set-up-dev-env/
2. Start the docker container using (no changes yet in dry-run-test branch)
docker run --privileged --rm -ti -v `pwd`:/go/src/github.com/docker/docker dry-run-test /bin/bash
3. Run basic unit test using
hack/make.sh dynbinary binary cross test-unit

Actual Results:

+ go test -test.timeout=30m github.com/docker/docker/volumes
--- FAIL: TestInitializeCannotStatPathFileNameTooLong (0.00s)
        volume_test.go:53: Expected to get ENAMETOOLONG error, got stat EyCwAvvNYrBMvsDjqaaNMWKtmedHadMhXxIGiLNmuq\
jnMtJMNocxiicSnfzNJyscOJzzHHCybsUClNSkDSDtZVLKfuYuyokRuXfgZLIkVypeSfpAgxiTLWJDVyAJboesBvYYtWOXotYQqNcEXgfrVNGXPHJI\
jnyBRHjqScGvCbVuvynkwAXWubzjSSRitIwlktUbKSyBRuPaXsnZFmJaOHqMLxsVrHEFSAwUkpVxpdSvtPFBHTCvhIzmdahHxdertyaUJQGHtIkIBz\
UTCfdNGNqydbufaVhAospgpLgarxQi: protocol error
FAIL

Expected Results:

The test TestInitializeCannotStatPathFileNameTooLong expects that the os.Stat returns ErrNotExist
when given a long path name. Instead is returns "protocol error"

Additional info:

It appears os.Stat returns "protocol error" rather than ErrNotExist because something is different in the 
stat system call behavior in the following kernel that is running in VirtualBox VM.

Linux boot2docker 3.18.5-tinycore64 #1 SMP Sun Feb 1 06:02:30 UTC 2015 x86_64 GNU/Linux

So is this a boot2docker issue or docker issue - my guess is that it is docker issue in the test code itself - volumes/volume_test.go - since it is assuming stat will fail with only "file name too long" error.

**Comment by runcom** [comment]
seems like a VM issue https://www.virtualbox.org/ticket/11976
(I'm replying because I wrote that test)

**Comment by jfrazelle** [comment]
lol that ticket

**Comment by runcom** [comment]
@jfrazelle something known?

**Comment by jfrazelle** [comment]
no I just had never seen something like before... super weird

**Comment by runcom** [comment]
I can change the test to check for another error instead of ENAMETOOLONG but I think the "propagation" error they talk about in the issue still remains

**Comment by rustogi** [comment]
@runcom tx for the quick reply. Just wondering the issue reported there is several months old, so how did other folks using boot2docker not run into this - unless boot2docker just recently moved to the Linux kernel with this issue.

I think it would be great to perhaps relax the check on specific expected error string in volume_test.go.

**Comment by runcom** [comment]
mm not sure about this, checking ENAMETOOLONG was just a check to get an error different from ENOENT IIRC but without the check string yes it's different but no control

**Comment by rustogi** [comment]
@runcom I am tempted to say that if you don't like relaxing the check then the other option is to maybe check for both "protocol error" and ENAMETOOLONG but that does not seem right either without understanding why is "protocol error" occurring. 

Just wondering if other folks running boot2docker see this error.

**Comment by runcom** [comment]
I think that protocol error is an upstream issue that has to be solved upstream and I shouldn't rely on that, just thinking..

**Comment by rustogi** [comment]
@runcom If this is a temporary issue then the other possibility is can you just check that the error is not ErrNotExist

**Comment by runcom** [comment]
@rustogi good point, I'll do that then if @jfrazelle is ok with this

**Comment by runcom** [comment]
This can be closed (wrong  format for autoclose sorry)

**Comment by thaJeztah** [comment]
Thanks @runcom ! "260 chars should be enough for anybody" 😂

This issue was resolved in https://github.com/docker/docker/issues/12412
