### ISSUE TITLE
apt-get uninstall vs purge for lxc-docker

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/docker#12418]
```
$ apt-get -h
...
Commands:
   ...
   remove - Remove packages
   purge  - Remove packages and config files
   ...
```

By definition I would expect `purge` to remove `/etc/default/docker` (and maybe `~/.docker` as well) but it doesn't. Is there a historical decision behind this behavior? 

Should this be fixed to remote configs on purge as well?

**Comment by jfrazelle** [comment]
ping @tianon but I do believe this is intended behavior say for example I install something else w configs the configs stick around as they are user settings

**Comment by jfrazelle** [comment]
/s/configs/user settings, it's actually for this reason I install everything on my computer in containers because I prefer a real nuke

**Comment by ahmetalpbalkan** [comment]
@jfrazelle but that's what debian/ubuntu users would expect from a `purge` and we're not doing it.

**Comment by RickWieman** [comment]
I agree on the `/etc/default/docker` part, but I don't on the `~/.docker` one. See for example [this post](http://askubuntu.com/a/231568); `apt-get purge` should never remove anything from the user's home directory, it only removes system-wide configuration files.

**Comment by ahmetalpbalkan** [comment]
@RickWieman makes sense.

**Comment by tianon** [comment]
In theory, this should already be happening, but since we roll our `.deb` files by hand, it's hard to say for sure.  With the debs created by #12111, this should actually work properly, since that's building our debs the same way the distributions themselves do.

**Comment by jfrazelle** [comment]
I think it won't remove it if the user has edited tho

**Comment by pdevine** [comment]
I can't reproduce this.
```ubuntu@xxxxxx:~$ dpkg -l | grep docker
ii  lxc-docker                          1.6.0                            amd64        Linux container runtime
ii  lxc-docker-1.6.0                    1.6.0                            amd64        Linux container runtime
ubuntu@xxxxxx:~$ vi /etc/default/
acpid          bsdmainutils   cron           devpts         grub.d/        keyboard       ntfs-3g        rcS            ssh
apport         console-setup  cryptdisks     docker         halt           locale         ntpdate        rsync          ufw
aufs           crda           dbus           grub           irqbalance     nss            pollinate      rsyslog        useradd
ubuntu@xxxxxx:~$ sudo vi /etc/default/docker 
ubuntu@xxxxxx:~$ sudo apt-get purge lxc-docker lxc-docker-1.6.0
[...]
ubuntu@xxxxxx:~$ ls -l /etc/default/dock*
ls: cannot access /etc/default/dock*: No such file or directory
```

It seems like everything is working as we'd expect it.  Also, if you look through hack/make/ubuntu, it lists /etc/default/docker as a config file in lxc-docker-1.6.0, which is also correct.

**Comment by ahmetalpbalkan** [comment]
Sounds good then
