### ISSUE TITLE
--insecure-registry flag doesn't work

### ISSUE THREAD

**Issue by jdoliner** [docker/docker#12420]
I'm trying to pull from a local registry that I'm running in a CoreOS cluster. When I do a pull I get the following errors message:

```shell
docker --insecure-registry registry.host pull registry.host/image
FATA[0004] Error: v1 ping attempt failed with error: Get https://registry.host/v1/_ping: EOF. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry registry.host` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/registry.host
```

It wants me to add `--insecure-registry` to the daemon's arguments even though I've already added it to the commands arguments. Why doesn't this work? I don't want to have to restart the docker daemon to use this registry, until recently I didn't have to do anything at all to get this to work.

**Comment by thaJeztah** [comment]
I'm going to close this, as I think this is a duplicated of https://github.com/docker/docker/issues/8887

Please continue the discussion on https://github.com/docker/docker/issues/8887, but feel free to add a comment here after closing.

**Comment by jdoliner** [comment]
That's a very unsatisfying response.

I have a behavior that was working fine a few version ago, now it's broken and the solution is for me to pitch in on a 100 comment long thread that seems to be mostly Docker engineers not fixing a problem that a bunch of people have and/or not merging pull requests that would fix the problem.

**Comment by thaJeztah** [comment]
@jdoliner apologies if me closing your issue felt harsh; I'm not taking a position here whether this should or should not be implemented, just trying to keep the discussion on a single location.

I'm full aware this is a much discussed issue! Don't hesitate to have your voice heard on the linked issue (and the related pull request(s)).

Hope you can understand my reasoning. We *do* appreciate your feedback, both positive and negative!
