### ISSUE TITLE
Ubuntu installation guide should include starting the docker daemon

### ISSUE THREAD

**Issue by gabesullice** [docker/docker#12427]
Following the steps verbatim ends in an error, there should be a step prior to `docker run hello-world` about starting the docker daemon.

**Comment by vdemeester** [comment]
Well, by default the daemon will be started at the end of the installation (by dpkg & stuff). If it's not the case, it might be a non-default configuration. It should be mentionned that in the case it's not working, verify that the service is started, but it shouldn't be a "must do".

**Comment by moxiegirl** [comment]
@gabesullice I tested the installation when I rewrote this page. A daemon start wasn't required.  Are you finding that is when you test? What are the steps you are following? I'd like to duplicate it.

**Comment by gabesullice** [comment]
Couldn't reproduce. Closing. Don't know what happened.

**Comment by moxiegirl** [comment]
@gabesullice Thank you for the issue, the additional testing, and the follow through to close the issue.  Much appreciated.
