### ISSUE TITLE
check statusCode from sockRequest and sockRequestRaw

### ISSUE THREAD

**Issue by LK4D4** [docker/docker#12449]
There are still a lot of unchecked statuses.

**Comment by kostickm** [comment]
#dibs

**Comment by ahmetalpbalkan** [comment]
@LK4D4 hmm when I took a stab at it, I pretty much fixed cases where we did `err.Error().Contains("201 Accepted")` etc.

In other cases, tests already return a nice error message containing the statusCode. Can you show some examples?

**Comment by kostickm** [comment]
@ahmetalpbalkan There are multiple tests where nothing is done with the status code, such as in
integration-cli/docker_api_resize_test.go for TestResizeApiResponse:

_, _, err = sockRequest("POST", endpoint, nil)
if err != nil {
        t.Fatalf("resize Request failed %v", err)
}

Where we only check if the error is not nil, but not that the status returned is what we expect. At least that's the changes I have been making.

**Comment by ahmetalpbalkan** [comment]
@LK4D4 @kostickm yes that `err` definitely contains status code (check `sockRequest` method). You don't need to use `statusCode` if it's already printed to screen with `t.Fatalf` :smile:

**Comment by ahmetalpbalkan** [comment]
@kostickm in most tests we expect `HTTP 200` and that's already being checked in `sockRequest` as well. If you try to check all calls for HTTP 200, you will just increase redundancy/repetition in the code.

**Comment by kostickm** [comment]
@ahmetalpbalkan Ah thank you! Didn't realize that. @LK4D4 I guess I'm not sure which status need checked then?

**Comment by LK4D4** [comment]
we should remove check from `socketRaw`. It is wrong to expect always `200`.

**Comment by runcom** [comment]
@LK4D4 @ahmetalpbalkan I'm starting not to like the method itself. I mean err should be returned if something went wrong with the request not if the request went ok and status was not 200. What I think would be ok for this  method is to return an error if something went wrong with the request itself and then return the status code to later inspect it because it's not a request (socket) error having a 500+ or 400+. I think because most expect 200 is not a valid point to include "valid" status code in a general "request" error

**Comment by ahmetalpbalkan** [comment]
@LK4D4 Hmm then let's pass sockRequest (or whoever check == 200) the status(es) we expect as a function parameter.

@runcom anything `status >= 400` means an error unless we are intentionally inducing the error (by doing some faulty operation and expecting it to fail with some status code). my suggestion above solves that problem.

**Comment by runcom** [comment]
@ahmetalpbalkan 400 is not a socket error (I think) 400 is a successfull request and server replied 400

**Comment by runcom** [comment]
if the method is sockRequest I expect to get an error only on connection timeout for instance, not on 400+.. 400+ errors for example can even carry a body to be later inspected

**Comment by LK4D4** [comment]
Yeah, I don't like that func too. Doing too much.

**Comment by ahmetalpbalkan** [comment]
@runcom aware. what I'm saying is, for convenience those methods are programmed to evaluate semantics of status code because most docker calls return 200 OK. but for sanity, we must change and specify expected set of status codes in each call to sockRequest IMO.

**Comment by runcom** [comment]
@ahmetalpbalkan could be but isn't simpler to just return it and the caller will check it? I mean, as @LK4D4 this function is doing to many things, let's put the check outside that function. Otherwise it will be called `sockRequestAndCheckStatusCode` lol

**Comment by runcom** [comment]
I don't get the relation with doing a "sockRequest" and checking its status code (from the request). I still assume the caller should do the check for more control

**Comment by kostickm** [comment]
@ahmetalpbalkan @runcom @LK4D4 Are we in agreement to remove the 200 check from sockRequestRaw and do the status check from the test then?

**Comment by ahmetalpbalkan** [comment]
I think doing the check in the test will reduce duplication. Why don't we pass valid status codes to sockRequest and let it do the check and raise the error. 

Otherwise you will say t.Fatalf("unexpected status: %d") probably 362526482 times in the tests :-) 

Instead if we call sockRequest(url, 200) it will return us an error if it doesnt match. Remember sockRequest is a convenience method in test package. Let it bring some convenicence :-)

**Comment by runcom** [comment]
@ahmetalpbalkan let's change its name then :smile_cat:

**Comment by LK4D4** [comment]
I don't see any convenience in concealing test logic somewhere apart from test. For write new test you'll need to read code of that function to understand what's going on with `status` argument and why we passing it. With checks in tests you can just copy-paste another test and see how we check codes.
I'm not a fan of DRY and event less fan of DRY in tests.

**Comment by ahmetalpbalkan** [comment]
I am coming from a culture where DRY is not appreciated an in fact I'm told I should never go to sleep if I wrote duplicate code today :-) so I guess I'll leave it up to you folks but I can't guarantee I wont send a PR if I don't like it :P

**Comment by cpuguy83** [comment]
Or with you could pass in the expected status code into sockRequest and it can check it properly.
I always always always have to do something special with this error.

Doing as above helps to remove some boiler plate from the actual tests.

**Comment by runcom** [comment]
still don't like a method named `sockRequest` that does the check for status code (even in test) but alright
