### ISSUE TITLE
Defaulting to OverlayFS

### ISSUE THREAD

**Issue by UserTaken** [docker/docker#12440]
By default Docker uses AUFS as the Storage Driver whenever available. When using a kernel that does not support AUFS but does support OverlayFS (3.18+), what do you think about Docker defaulting to that instead of devicemapper?

**Comment by unclejack** [comment]
This change is going to be made after the problems with overlay are fixed.

Please look at: https://github.com/docker/docker/issues?q=is%3Aopen+is%3Aissue+label%3A%2Fsystem%2Foverlay

**Comment by UserTaken** [comment]
@unclejack Good to hear that defaulting to OverlayFS is already planned. I've been following the CoreOS project and when I heard that they switched from BTRFS to OverlayFS, I too am starting to use OverlayFS on all my machines with kernel 3.18+. `label:/system/overlay` doesn't look as bad as `label:/system/devicemapper` and 2 issues are in the milestone for 1.7.0
