### ISSUE TITLE
run -d behaviour with Python apps - "print" / stdout not working

### ISSUE THREAD

**Issue by jpdus** [docker/docker#12447]
First posted at [StackOverflow](http://stackoverflow.com/questions/29663459/python-app-does-not-print-anything-when-running-detached-in-docker) but now I think this could be a bug in docker:

I have a Python (2.7) app which is started in my dockerfile:

    CMD ["python","main.py"]

*main.py* prints some strings when it is started and goes into a loop afterwards:

    print "App started"
    while True:
        time.sleep(1)

As long as I start the container with the -it flag, everything works as expected:

    $ docker run --name=myapp -it myappimage
    > App started

And I can see the same output via logs later:

    $ docker logs myapp
    > App started

If I try to run the same container with the -d flag, the container seems to start normally, but I can't see any output:

    $ docker run --name=myapp -d myappimage
    > b82db1120fee5f92c80000f30f6bdc84e068bafa32738ab7adb47e641b19b4d1
    $ docker logs myapp
    $ (empty)

But the container still seems to run;

    $ docker ps
    Container Status ...
    myapp     up 4 minutes ... 

Attach does not display anything either:

    $ docker attach --sig-proxy=false myapp
    (working, no output)

I thought it could be a problem with stdout when running detached, but even printing to stderr does not work:

    from __future__ import print_function
    print("App started", file=sys.stderr)

does not work either.

Docker version:

    Client version: 1.5.0
    Client API version: 1.17
    Go version (client): go1.4.2
    Git commit (client): a8a31ef
    OS/Arch (client): linux/arm
    Server version: 1.5.0
    Server API version: 1.17
    Go version (server): go1.4.2
    Git commit (server): a8a31ef

**Comment by ahmetalpbalkan** [comment]
Hi @jpdus.

`docker attach` supposed to subscribe to contents of stdout/stderr streams **after you attach** (in real time). It's not supposed to show you earlier output, by design (for that you can use `docker logs`).

If you modify your code to:

```py
import time

print("App started")
i = 0
while True:
    print("I'm actually alive: {0}".format(i))
    time.sleep(1)
    i += 1 
```

you will see:

```
docker attach --sig-proxy=false 45609a0b6a6db86551fc6743c52bee4d265e70977f9cf10f9c300c14d429f59a
I'm actually alive: 8
I'm actually alive: 9
I'm actually alive: 10
I'm actually alive: 11
I'm actually alive: 12
...
(exit with ctrl+c)
```

so it's actually working as expected.

Another point is you want to make sure you start python with unbuffered output option:

    CMD ["python", "-u", "main.py"]

otherwise it'll take longer for any output to be flushed to stdout.

Another proof of `docker attach` actually works as expected is, `docker run -i -t` is basically `docker create+run+attach`. :smile:

**Comment by jpdus** [comment]
Thanks for the reply @ahmetalpbalkan. 

This is not working for me, that's why I included  that the '''docker logs''' output is empty as well (and that's the main point of the issue). 

Thanks for the tip with unbuffered output, I will try it  but I doubt that this is the solution (as the output is very small in my case)

**Comment by ahmetalpbalkan** [comment]
interesting. can you please try with this dockerfile. I cannot reproduce it:

```
FROM python
COPY main.py .
CMD python -u main.py
```

if this doesn't work either, can you please try adding `-t` parameter to `docker run`?

**Comment by ahmetalpbalkan** [comment]
@jpdus I can tell one thing for sure, without `python -u` I see nothing in `docker logs`/`docker attach` (not even `App started` line).

**Comment by jpdus** [comment]
@ahmetalpbalkan ok, thanks, good to know - so far I thought that -u only matters if you use a pipe or exchange significant amounts of data via stdout. 
Im currently on the road but will try it out later  - many thanks and sorry for filing an issue prematurely!

**Comment by thaJeztah** [comment]
> many thanks and sorry for filing an issue prematurely!

@jpdus no worries! You took the right approach, asking on StackOverflow first and an exemplary description of your problem. I wish all users did this :)

If you can report back if you were able to resolve your issue with the hints above, that would be much appreciated, thanks!

**Comment by jpdus** [comment]
CMD python -u main.py

does in fact solve the problem, many thanks @ahmetalpbalkan !

**Comment by thaJeztah** [comment]
Great! Thanks for reporting back, @jpdus

**Comment by pencilcheck** [comment]
The unbuffered options indeed saved the day. Thanks!

**Comment by Symmetric** [comment]
For posterity, I'd like to note that I hit this issue running a Django app in a Docker container, and `-u` did not make a difference, but the `-t` flag to `docker run` did (even though I'm also using `-d`).

**Comment by piiteraq** [comment]
@ahmetalpbalkan - Thanks Ahmet, you were right: turning of buffering solved the problem.

**Comment by dieeasy** [comment]
Stumbled upon this one as I had the same issue but after some thought looks to me the right way to have timely output from a python app inside a daemonized docker container would be to use python's _logging_ module.

From a simple test I used to shed some light:
- print is indeed buffered and `docker logs` will eventually give you that output, just after enough of it will have piled up
- executing the same script with `python -u` gives instant output as said above
- `import logging` + `logging.warning("text")` gives the expected result even without `-u`

Note: I used python3.5 but that should not make any difference.

**Comment by valentin-krasontovitsch** [comment]
Just in case that anybody comes here through googling, like I just did - I was experiencing the same problem, with a **ruby** app, using the `Logger` class, and with both json-file and gelf logging drivers. The solution is the equivalent of the python thing - add the line

```
$stdout.sync = true
```

somewhere in your code to deactivate buffering of stdout (stderr is not buffered).

Background seems to be that the underlying C libraries / calls line buffer stdout if the receiving end is interactive / a terminal, and use full buffering if it's not, which can lead to problems...

**Comment by x00158589** [comment]
how about the detached container? How to get to print out? CMD ["python", "-u", "main.py"] works and the printing is appearing on the screen when the terminal is occupied by the running container. 
Is it possible to get the print out when the container run with the key -d: docker run -it -d myappimage?

**Comment by valentin-krasontovitsch** [comment]
@x00158589 you should be able to get the output of a detached container through logs, using `docker logs [YOUR_CONTAINER_ID]` or using the container name, of course.
