### ISSUE TITLE
how get docker registry2.0 source code?

### ISSUE THREAD

**Issue by blackfader** [docker/docker#12473]
how get docker registry2.0 source code?

**Comment by DieterReuter** [comment]
@blackfader just look here https://github.com/docker/distribution

**Comment by thaJeztah** [comment]
Correct, the registry 2.0 source code is in the https://github.com/docker/distribution repository.

**Comment by blackfader** [comment]
thinks

**Comment by blackfader** [comment]
and registry2.0 now support proxy or cache model？
