### ISSUE TITLE
[1.7.0-dev][graphdriver] prior storage driver "devicemapper" failed: driver not supported 

### ISSUE THREAD

**Issue by jpopelka** [docker/docker#12479]
Running docker-1.7.0-dev from up-to-date git repo fails on Fedora 22 (kernel-4.0.0-1.fc22.x86_64) with:

$ ./docker-1.7.0-dev -d -D
DEBU[0000] waiting for daemon to initialize
ERRO[0000] Udev sync is not supported. This will lead to unexpected behavior, data loss and errors. For more information, see https://docs.docker.com/reference/commandline/cli/#daemon-storage-driver-option
ERRO[0000] [graphdriver] prior storage driver "devicemapper" failed: driver not supported
INFO[0000] +job serveapi(unix:///var/run/docker.sock)
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
DEBU[0000] Registering DELETE, /containers/{name:.*}
DEBU[0000] Registering DELETE, /images/{name:.*} 
DEBU[0000] Registering OPTIONS,
DEBU[0000] Registering GET, /containers/{name:.*}/changes
DEBU[0000] Registering GET, /containers/{name:.*}/logs
DEBU[0000] Registering GET, /exec/{id:.*}/json
DEBU[0000] Registering GET, /containers/{name:.*}/attach/ws
DEBU[0000] Registering GET, /images/search
DEBU[0000] Registering GET, /containers/json
DEBU[0000] Registering GET, /containers/{name:.*}/export
DEBU[0000] Registering GET, /containers/{name:.*}/json
DEBU[0000] Registering GET, /containers/{name:.*}/top
DEBU[0000] Registering GET, /containers/{name:.*}/stats
DEBU[0000] Registering GET, /info
DEBU[0000] Registering GET, /version
DEBU[0000] Registering GET, /images/viz
DEBU[0000] Registering GET, /containers/ps
DEBU[0000] Registering GET, /images/{name:.*}/get
DEBU[0000] Registering GET, /images/{name:.*}/history
DEBU[0000] Registering GET, /images/{name:.*}/json
DEBU[0000] Registering GET, /_ping
DEBU[0000] Registering GET, /events
DEBU[0000] Registering GET, /images/json
DEBU[0000] Registering GET, /images/get
DEBU[0000] Registering POST, /containers/{name:.*}/copy
DEBU[0000] Registering POST, /containers/{name:.*}/exec
DEBU[0000] Registering POST, /exec/{name:.*}/start
DEBU[0000] Registering POST, /auth
DEBU[0000] Registering POST, /build
DEBU[0000] Registering POST, /containers/{name:.*}/wait
DEBU[0000] Registering POST, /containers/{name:.*}/attach
DEBU[0000] Registering POST, /images/{name:.*}/tag
DEBU[0000] Registering POST, /containers/{name:.*}/pause
DEBU[0000] Registering POST, /containers/{name:.*}/rename
DEBU[0000] Registering POST, /commit
DEBU[0000] Registering POST, /images/create
DEBU[0000] Registering POST, /images/load
DEBU[0000] Registering POST, /images/{name:.*}/push
DEBU[0000] Registering POST, /containers/{name:.*}/unpause
DEBU[0000] Registering POST, /containers/{name:.*}/restart
DEBU[0000] Registering POST, /exec/{name:.*}/resize
DEBU[0000] Registering POST, /containers/{name:.*}/resize
DEBU[0000] Registering POST, /containers/create
DEBU[0000] Registering POST, /containers/{name:.*}/kill
DEBU[0000] Registering POST, /containers/{name:.*}/start
DEBU[0000] Registering POST, /containers/{name:.*}/stop
DEBU[0000] docker group found. gid: 1001
FATA[0000] Shutting down daemon due to errors: error intializing graphdriver: driver not supported

1.6.0 runs OK:
$ docker -d -D
DEBU[0000] waiting for daemon to initialize
INFO[0000] +job serveapi(unix:///var/run/docker.sock)
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
DEBU[0000] Registering GET, /containers/{name:.*}/changes
...
DEBU[0000] Registering DELETE, /images/{name:.*}
DEBU[0000] Registering OPTIONS,
DEBU[0000] docker group found. gid: 1001
DEBU[0000] libdevmapper(6): ioctl/libdm-iface.c:1795 (4) dm version   OF   [16384] (*1)
DEBU[0000] devicemapper: udev sync support: true
DEBU[0000] Generated prefix: docker-253:22-524289
DEBU[0000] Checking for existence of the pool 'docker-253:22-524289-pool'
DEBU[0000] libdevmapper(6): ioctl/libdm-iface.c:1795 (4) dm info docker-253:22-524289-pool  OF   [16384] (*1)
DEBU[0000] [deviceset] constructDeviceIdMap()
DEBU[0000] Loading data for file /var/lib/docker/devicemapper/metadata/00a0c78eeb6d81442efcd1d7c02e8b141745e3a06f1ee3458e1bae628e0067d3
...
DEBU[0000] Added deviceId=409 to DeviceIdMap
DEBU[0000] Loading data for file /var/lib/docker/devicemapper/metadata/transaction-metadata
DEBU[0000] Added deviceId=659 to DeviceIdMap
DEBU[0000] [deviceset] constructDeviceIdMap() END
DEBU[0000] Using graph driver devicemapper
DEBU[0000] Creating images graph
DEBU[0000] Restored 103 elements
DEBU[0000] Error restoring volume: Volume exists: ee38a6a63aaefed30d3b26fb31151f5fb9bf93c7e8a7bc6514d621746735e33f
DEBU[0000] Creating repository list
DEBU[0000] Reloaded graph with 3 grants expiring at 2017-03-22 19:04:46.713978458 +0000 UTC
INFO[0000] +job init_networkdriver()
...

**Comment by jfrazelle** [comment]
Because you are running the static binary, this is expected and working
correctly

**Comment by jfrazelle** [comment]
See https://github.com/docker/docker/pull/11412

**Comment by rickyzhang82** [comment]
How to work make it run again in Fedora 22?

**Comment by jfrazelle** [comment]
add  -s graphdriver_you_want_to_use to daemon options

**Comment by rickyzhang82** [comment]
I think it knows its devicemapper. 

One thing I don't follow is that why it mention dynamic binary in the comment. Why is it related to udev sync bug and docker binary?

**Comment by jfrazelle** [comment]
oh ya you need a dynamic binary not a static one

**Comment by rickyzhang82** [comment]
But why?

**Comment by rickyzhang82** [comment]
Forget why. But how to compile it in dynamic binary? I find one (http://sickbits.net/build-a-dynamically-linked-docker/) online. But it doesn't work in FC21.

Are there official document? dynbuild is not included in Makefile. Is it OK to do the following:

diff --git a/Makefile b/Makefile
index d139602..a3ba0a8 100644
--- a/Makefile
+++ b/Makefile
@@ -44,6 +44,9 @@ all: build
 binary: build
        $(DOCKER_RUN_DOCKER) hack/make.sh binary
 
+dynbinary: build
+       $(DOCKER_RUN_DOCKER) hack/make.sh dynbinary
+
 cross: build
        $(DOCKER_RUN_DOCKER) hack/make.sh binary cross

**Comment by rickyzhang82** [comment]
I build one by hacking Makefile.

But there is showstopper. 

[root@gtx ~]# ldd /usr/bin/docker
	linux-vdso.so.1 =>  (0x00007ffe6edfa000)
	libapparmor.so.1 => not found
	libpthread.so.0 => /lib64/libpthread.so.0 (0x0000003c32e00000)
	libsqlite3.so.0 => /lib64/libsqlite3.so.0 (0x000000315be00000)
	libdevmapper.so.1.02 => /lib64/libdevmapper.so.1.02 (0x0000003c51600000)
	libc.so.6 => /lib64/libc.so.6 (0x0000003c32600000)
	/lib64/ld-linux-x86-64.so.2 (0x0000003c32200000)
	libdl.so.2 => /lib64/libdl.so.2 (0x0000003c33200000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x0000003c34600000)
	libsepol.so.1 => /lib64/libsepol.so.1 (0x0000003c4b400000)
	libudev.so.1 => /lib64/libudev.so.1 (0x0000003c46000000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x0000003c33e00000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x0000003c33a00000)
	librt.so.1 => /lib64/librt.so.1 (0x0000003c35200000)
	libdw.so.1 => /lib64/libdw.so.1 (0x0000003c42400000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x0000003c34200000)
	libelf.so.1 => /lib64/libelf.so.1 (0x0000003c42000000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x0000003c35600000)
	libz.so.1 => /lib64/libz.so.1 (0x0000003c33600000)

Read Apparmor website. It requires kernel recompile in Centos and Fedora.

**Comment by coolljt0725** [comment]
@rickyzhang82  try to this, remove apparmor form BUILDTAGS
<pre><code>diff --git a/Dockerfile b/Dockerfile
index 9b6a79b..44f6c70 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -150,7 +150,7 @@ RUN useradd --create-home --gid docker unprivilegeduser

 VOLUME /var/lib/docker
 WORKDIR /go/src/github.com/docker/docker
-ENV DOCKER_BUILDTAGS apparmor selinux
+ENV DOCKER_BUILDTAGS selinux
</code></pre>

**Comment by rickyzhang82** [comment]
@coolljt0725 Thanks! It works now.

BTW, do you know why it has to compile in dynamic binary to resolve udev race condition?

**Comment by coolljt0725** [comment]
@rickyzhang82  There is a long story here #4036
