### ISSUE TITLE
"docker inspect" can't reach the image JSON when there is a same name container running.

### ISSUE THREAD

**Issue by shishir-a412ed** [docker/docker#12483]
Description of problem:
When there is a image named, for instance "rhel7" and a container is also has the same name, then "docker inspect rhel7" only shows containers json, the command can't reach the image's scope. 

Version-Release number of selected component (if applicable):
docker-1.6.0-2.el7.x86_64

How reproducible:
100%

Steps to Reproduce:
1.
# docker images
REPOSITORY                                    TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
registry.access.redhat.com/rhel7              latest              10acc31def5d        10 weeks ago        154.1 MB

#docker run --name rhel7 rhel7 /bin/bash
# docker ps -a
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS                   PORTS               NAMES
d4ac50753fe4        rhel7:latest        "/bin/bash"            2 hours ago         Exited (0) 2 hours ago                       rhel7            

2.
#docker inspect rhel7
Debug log:(reach the container, then return)
DEBU[0026] Calling GET /containers/json                 
INFO[0026] GET /v1.18/containers/json?all=1             
INFO[0026] +job containers()                            
INFO[0026] -job containers() = OK (0)                   
DEBU[0064] Calling GET /containers/{name:.*}/json       
INFO[0064] GET /v1.18/containers/rhel7/json             
INFO[0064] +job container_inspect(rhel7)                
INFO[0064] -job container_inspect(rhel7) = OK (0) 

Otherwise, after delete the container,
(fail to find the container then continue to reach the image and return

DEBU[0106] Calling GET /containers/{name:.*}/json       
INFO[0106] GET /v1.18/containers/rhel7/json             
INFO[0106] +job container_inspect(rhel7)                
no such id: rhel7
INFO[0106] -job container_inspect(rhel7) = ERR (1)      
ERRO[0106] Handler for GET /containers/{name:.*}/json returned error: no such id: rhel7 
ERRO[0106] HTTP Error: statusCode=404 no such id: rhel7 
DEBU[0106] Calling GET /images/{name:.*}/json           
INFO[0106] GET /v1.18/images/rhel7/json                 
INFO[0106] +job image_inspect(rhel7)                    
INFO[0106] -job image_inspect(rhel7) = OK (0)

**Comment by shishir-a412ed** [comment]
I have verified this, container JSON is shadowing the image JSON, while the container is running.

I did the following:

1) sudo docker run -it --name=rhel7 rhel7 /bin/bash
2) sudo docker inspect rhel7 {shows the container JSON}
3) Exit container
4) sudo docker inspect rhel7 {shows the image JSON}

Container JSON: http://pastebin.test.redhat.com/277034
Image JSON: http://pastebin.test.redhat.com/277031

Shishir

**Comment by cpuguy83** [comment]
Yeah, this is expected on the CLI.
You should be able to call the API and get the output.

**Comment by shishir-a412ed** [comment]
@cpuguy83 I feel end user using the CLI should atleast have the option to select between `image JSON` and `container JSON`, if there be a conflicting name situation like this. He cannot write code to call the API.

How about an `--image=true` flag in `docker inspect` command to unshadow the image JSON while the container {with the same name} is still running ?

**Comment by thaJeztah** [comment]
I'm -1 on adding a `--image=true` flag; I think it's messy.

Why not use `docker inspect <imageid>`?

**Comment by rhatdan** [comment]
@thaJeztah Wouldn't it be difficult to get the imageid for a novice docker user.

Do you think 

docker inspect $(docker inspect --format='{{.Config.Image}}') rhel7 

is simpler?


docker inspect fedora | grep

**Comment by thaJeztah** [comment]
@rhatdan No I definitely don't think that is simpler. I agree that this can be improved, but I don't like doing this through a flag. 

(However, beginning users should be able to copy/paste the image-ID from the output of `docker images rhel7`)

My ideal would be to have a consistent UX for each type of "entity" (see https://github.com/docker/docker/issues/8829), in this case; `docker images inspect <name | ID>`, docker containers inspect <name | ID>)

Shorthand commands should be present for most used commands and to keep the current UX; meaning that `docker [containers] inspect <name | ID>`.

Just my personal idea and nothing set in stone.

**Comment by rhatdan** [comment]
docker images --inspect IMAGEID.

**Comment by shishir-a412ed** [comment]
This is what `docker inspect --help` says.
'Return low-level information on a container or image'. Since this  command applies to both container and images, the user should be given the flexibility to choose between the two.

I have opened up a PR with an alternate solution. ( @rhatdan is +1 for this). What do you guys think ?
1) -i / --image-only: User can choose to only see image JSON's
2) -c/ --container-only: User can choose to only see container JSON's
3) no flags passed, existing behaviour prevails.

Shishir
