### ISSUE TITLE
Overlay FS "invalid argument" issues with Centos 7

### ISSUE THREAD

**Issue by stevendborrelli** [docker/docker#12488]
Trying the tech preview of Olverlay FS on Centos 7.1. About half the containers I try to run end up having this issue:

```
$docker run -it  ubuntu /bin/bash
FATA[0000] Error response from daemon: mkdir /var/lib/docker/overlay/36de2cb1cd7cec0f4ca96550a8829341d0f3ad4d711bc6b484038f15b27d0bc7-init/merged/dev/shm: invalid argument 
```

```
$docker info

Containers: 10
Images: 65
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 3.10.0-229.1.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 3.703 GiB
Name: drone-01.novalocal
ID: PKLX:QAOU:XUF2:CPKK:5DEN:LQYH:HSVO:XTGQ:APAF:3PWM:G5U5:U
```

```
rpm -q docker
docker-1.5.0-28.el7.centos.x86_64
```

**Comment by stevendborrelli** [comment]
Opened a bug with Centos: http://bugs.centos.org/view.php?id=8493

**Comment by etehtsea** [comment]
As far as I know overlayfs supported from kernel version 3.18+.

**Comment by stevendborrelli** [comment]
@etehtsea it was added to the RHEL/Centos 7.1 kernel as a technology preview: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.1_Release_Notes/chap-Red_Hat_Enterprise_Linux-7.1_Release_Notes-File_Systems.html

**Comment by calavera** [comment]
I believe this issue is duplicated, please check #10294. I'm going to close it, but feel free to reopen it that's not correct.
