### ISSUE TITLE
docs.docker.com doesn't enforce secure connection

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#12498]
The docs website is accessible via http://docs.docker.com and doesn't automatically redirect to https://docs.docker.com

Given that the site is accessible via `https://`, I think it should enforce a secure connection.

**Comment by ewindisch** [comment]
It redirects locally, but because we do or did have HSTS enforcing the redirect. Seems that new browsers aren't enforcing redirects for this URL.

**Comment by cpuguy83** [comment]
:( still not redirecting

**Comment by thaJeztah** [comment]
Moved to https://github.com/docker/docs.docker.com/issues/86
