### ISSUE TITLE
Remove dead code from daemon/daemon.go

### ISSUE THREAD

**Issue by LK4D4** [docker/docker#12492]
In `*Daemon.register`:
```
			var err error
			cmd.ProcessConfig.Process, err = os.FindProcess(existingPid)
			if err != nil {
				logrus.Debugf("cannot find existing process for %d", existingPid)
			}
```
is dead code. We can rely on `container.Pid` without process start time anyway for killing processes.

**Comment by toliaqat** [comment]
I would like to work on it.

**Comment by LK4D4** [comment]
@toliaqat Ok, it's yours.

**Comment by LK4D4** [comment]
@toliaqat Next time you can just post comment `#dibs` and it will be claimed.

**Comment by LK4D4** [comment]
@toliaqat What's status here? Wanna give it to someone else?

**Comment by jmzwcn** [comment]
#dibs Let me try again.
