### ISSUE TITLE
CONFIG_IA32_EMULATION problems

### ISSUE THREAD

**Issue by glaudiston** [docker/docker#12504]
Hi, 
I have a custom linuxfromscratch(pure x86_64), and I did installed docker with success... but yesterday, I did a kernel rebuid (version 3.19.3) with a:
    CONFIG_IA32_EMULATION=y
If do not set it, all works fine, but, If builded with it, when the docker daemon starts, my host system freezes, and saddly appears that only magic sysrq+b works.
The last thing printed by the docker daemon are the IPTABLES. (screenshot in https://plus.google.com/108815571963742519633/posts/BnSdrboa5TT )
After some tests, I just rebuild the kernel without the CONFIG_IA32_EMULATION and all works again.

My intent was to execute 32bit elf binaries inside a containter with ia32-libs (that I don't have in host pure 64)

Anyone more has this issue?﻿

**Comment by thaJeztah** [comment]
Hi @glaudiston thanks for asking, however, the issue tracker is not really intended for support questions (it's for tracking bugs and feature requests).

I'm going to close this issue for that reason, but you'll be able to comment on it after that.

I *do* think it's an interesting question and there are some [existing issues/discussions ](https://github.com/docker/docker/issues?utf8=✓&q=is%3Aissue+32+in%3Atitle+) on 32-bit support (both for running docker *itself* and for running 32-bit *containers*).

I think https://forums.docker.com, https://groups.google.com/forum/#!forum/docker-user or the #docker IRC channel are more suitable locations for asking this question.

Thanks for asking, and again, feel free to comment after closing

**Comment by glaudiston** [comment]
Regardless 32bit support, the simple fact is that docker halts my entire system. For me it's clear to be a docker "bug". and it's the reason that I'm asking for "support"... I'm really in the wrong place ?
