### ISSUE TITLE
docker start -a <containerID>

### ISSUE THREAD

**Issue by WYSIATI** [docker/docker#12525]
After typing `docker start -a <containerID>`, I can enter bash shell, but it does not respond to any command, I have to use <CTRL+C> to quit the shell.

OS: Mac OSX 10.10.3

Docker version:
```
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): darwin/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64
```

Boot2docker version: 
```
Boot2Docker-cli version: v1.6.0
Git commit: 9894ae9
```

**Comment by coolljt0725** [comment]
@WYSIATI  You have to start the container with `i` if you want enter bash shell, `-i` will attach the stdin, `-a` just attach `stdout` and `stderr`, but this also need you with `-it` on container creation.

**Comment by WYSIATI** [comment]
@coolljt0725 it worked for me, thank you!
