### ISSUE TITLE
Display wrong number of VIRTUAL SIZE on 32 bit OS

### ISSUE THREAD

**Issue by dlintw** [docker/docker#12526]
$ docker pull dlin/stlinux24-sh4-glibc (That's about 4GB)

$ docker images
REPOSITORY                 TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
dlin/stlinux24-sh4-glibc   latest              c7657d5d3264        2 days ago          -2.217e+08 B
32bit/debian               jessie              e31bfc2a061e        5 months ago        272 MB

**Comment by icecrime** [comment]
We don't currently support 32bits OS, so I'll close this one.
