### ISSUE TITLE
Eliminate json.Marshal in volumes/volume.go

### ISSUE THREAD

**Issue by LK4D4** [docker/docker#12531]
Should be replaced with `json.NewEncoder(...).Encode`.

**Comment by hqhq** [comment]
#dibs

**Comment by ankushagarwal** [comment]
Hey @hqhq, I've already pushed a change for this

**Comment by hqhq** [comment]
OK, go ahead please, you should claim it before you do next time :)

**Comment by ankushagarwal** [comment]
Really sorry about that. I will use #dibs next time.
