### ISSUE TITLE
remove go1.3.3 support

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#12549]
this was added for go1.3.3 support but we no longer need, https://github.com/docker/docker/blob/master/pkg/requestdecorator/requestdecorator_test.go#L10

there are other instances places as well. finding them all would be great but some would be awesome.

**Comment by fntlnz** [comment]
#dibs

**Comment by tianon** [comment]
This will also mean updating "project/PACKAGERS.md" and commenting out the
"GOFMT_VERSION" section of the Dockerfile (which installs the older gofmt
binary).

**Comment by fntlnz** [comment]
@tianon Thank you for the hint!

**Comment by fntlnz** [comment]
@jfrazelle I have not found any evidence of other places where that workaround is still present.

I need some time to figure out and explore the Docker code base to find things like the one you reported.

Any suggestions?

**Comment by jfrazelle** [comment]
no worries, just that instance is fine then :)

**Comment by runcom** [comment]
`grep -rin "1\.3"`, `grep -rin "go 1\.3"`, `grep -rin "1\.3\.3"`, `grep -rin "go 1\.3\.3"` can be useful to look around just to get some clues @fntlnz :)

**Comment by fntlnz** [comment]
@runcom No new evidences from there, thank you for your hint :)
