### ISSUE TITLE
docker daemon reads /proc/mounts only when started

### ISSUE THREAD

**Issue by rafal-prasal** [docker/docker#12544]
The problem is that if something was mounted after docker daemon was started then docker does not recognize the directory as a mountpoint and treats it as normal directory. In other words performs write operation not on a mountpoint, but underneath it, so normally in the HOST you won't see your data until you actually umount.

**How to reproduce**
1. Docker Daemon is already running in a system
2. mkdir -p /tmp/testing /tmp/testing_mount
3. mount -obind /tmp/testing /tmp/testing_mount
4. docker run -t -i -v /tmp/testing_mount:/tmp/testing_mount/ centos:6 /bin/bash
5. touch /tmp/testing_mount/a 

**Test**
1. when on HOST you do `ls -l /tmp/testing_mount/a` it will end with error
2. when on HOST you firstly `umount /tmp/testing_mount` then \1 will show you the file

**FIX:** should be to rescan mountpoints whenever docker run/start is used so container will deal with those properly or signal handler to rescan the mountpoints or do it synchrounously every 1s.

Thank you in advance.

**Comment by cpuguy83** [comment]
What host OS are you using?
Can you provide output of `docker info` and `docker version`?

**Comment by rafal-prasal** [comment]
basically it is Centos7 with downloaded the latest available version of docker.

$ uname -a 
Linux gdnshp64 3.10.0-123.20.1.el7.x86_64 #1 SMP Thu Jan 29 18:05:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ docker --version
Docker version 1.7.0-dev, build b7950b7

$ docker info
Containers: 8
Images: 5
Storage Driver: btrfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-123.20.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 24
Total Memory: 11.57 GiB
Name: gdnshp64
ID: 4DXD:NNSO:3NRB:N6JA:R6TB:2WI3:6TEB:RKFJ:BRL5:HE4M:AYKV:2KJN

**Comment by cpuguy83** [comment]
I'm assuming you are using systemd to init Docker?
What does your unit file look like?

**Comment by rafal-prasal** [comment]
# cat /etc/sysconfig/docker
OPTIONS=--selinux-enabled -H fd:// -g /docker --bridge br0

# cat /usr/lib/systemd/system/docker.service
[Unit]
Description=Docker Application Container Engine
Documentation=http://docs.docker.com
After=network.target docker.socket
Requires=docker.socket

[Service]
Type=notify
EnvironmentFile=-/etc/sysconfig/docker
EnvironmentFile=-/etc/sysconfig/docker-storage
ExecStart=/usr/bin/docker -d $OPTIONS $DOCKER_STORAGE_OPTIONS
LimitNOFILE=1048576
LimitNPROC=1048576
MountFlags=private

[Install]
WantedBy=multi-user.target

**Comment by cpuguy83** [comment]
I believe the issue you are seeing is due to `MountFlags=private`
I believe the correct setting would be `MountFlags=slave`... but don't quote me on that.

**Comment by rafal-prasal** [comment]
Thank you for your input. it seems that it solves my case... however as it is quite late in Poland I would like to test it further tomorrow morning.

Thank you.

**Comment by rafal-prasal** [comment]
I did some additional checks and it seems to work properly with setting MountFlags=slave. 

docker-1.5 rpm from http://mirror.centos.org/centos/7/extras/x86_64/Packages/ seems to be good as well as it has this fix built in already.
