### ISSUE TITLE
Docker feature mounting volumes from host might be broken

### ISSUE THREAD

**Issue by andrewmilkowski** [docker/docker#12550]
environment

[amilkowski@localhost ~]$ uname -a
Linux localhost.localdomain 3.10.0-229.1.2.el7.x86_64 #1 SMP Thu Mar 26 09:10:25 CDT 2015 x86_64 x86_64 x86_64 GNU/Linux
[amilkowski@localhost ~]$ docker -v
Docker version 1.5.0-dev, build fc0329b/1.5.0

running:

Scientific Linux release 7.1 (Nitrogen)
cpe:/o:redhat:enterprise_linux:7.1:ga

which really is Centos 7

trying to do neo4j docker from https://github.com/kbastani/docker-neo4j

1.  docker pull kbastani/docker-neo4j
2.  docker run -d -p 7474:7474 -v /home/amilkowski/data:/opt/data --name graphdb kbastani/docker-neo4j

container exists..

[amilkowski@localhost ~]$ sudo docker run -d -p 7474:7474 -v /home/amilkowski/data:/opt/data --name graphdb kbastani/docker-neo4j
2b2d38d3cfa1519f17fe896f37e6f66a743895f5ddabf099bba1ac3eff16ed8d
[amilkowski@localhost ~]$ sudo docker ps -a
CONTAINER ID        IMAGE                          COMMAND                CREATED             STATUS                              PORTS               NAMES
2b2d38d3cfa1        kbastani/docker-neo4j:latest   "/etc/bootstrap.sh -   3 seconds ago       Exited (0) Less than a second ago                       graphdb             
[amilkowski@localhost ~]$ 

IF I remove host to container mount override container runs (-v /home/amilkowski/data:/opt/data) below

so it does look like the feature of docker "mounting volumes from host" might be broken.. (ref. http://docs.docker.com/userguide/dockervolumes/)

[amilkowski@localhost ~]$ sudo docker ps -a
CONTAINER ID        IMAGE                          COMMAND                CREATED             STATUS              PORTS                              NAMES
26e3d3bcd81d        kbastani/docker-neo4j:latest   "/etc/bootstrap.sh -   4 seconds ago       Up 3 seconds        1337/tcp, 0.0.0.0:7474->7474/tcp   graphdb

:

**Comment by cpuguy83** [comment]
Not broken, the version of docker you are using is built from a pre-release... basically whatever happened to be on master the day RedHat built it ( + their patches ).

You'll need to get an actual release version of docker.
Please see http://wiki.centos.org/Cloud/Docker and the bit about the `virt7-testing` repo.

**Comment by andrewmilkowski** [comment]
acknowledged! will take that route and repeat the test! appreciate such a fast response, it is sort of a blocker for me (mounting host > container) ultra useful.. speak soon

**Comment by andrewmilkowski** [comment]
attempting this docker release next:

[root@localhost yum.repos.d]# docker -v
Docker version 1.6.0-rc7, build bc73604/1.6.0

**Comment by andrewmilkowski** [comment]
same problem... @cpuguy83  should I manually build Docker from release:

https://github.com/docker/docker/releases/tag/v1.6.0

using instruction:

https://docs.docker.com/installation/binaries/

or don't even bother with Centos 7 ? thanks....

docker run -d -p 7474:7474 -v /home/amilkowski/data:/opt/data --name graphdb kbastani/docker-neo4j
aba4cc652b15b133e13f68ee9801b25fe103683bab81de73d289af683a21d722
[root@localhost ~]# sudo docker ps -a
CONTAINER ID        IMAGE                          COMMAND                CREATED             STATUS                     PORTS               NAMES
aba4cc652b15        kbastani/docker-neo4j:latest   "/etc/bootstrap.sh -   10 seconds ago      Exited (0) 7 seconds ago

**Comment by cpuguy83** [comment]
You might also need to look at your SELinux labels.
`chcon -Rt svirt_sandbox_file_t /path/to/volume`

**Comment by andrewmilkowski** [comment]
works like a charm.. sorry for bother.. should have checked security... first.. disabled SELINUX for now just to keep going appreciate you landing help with this! awesome.. powerful all this especially volume sharing/override...

[root@localhost ~]# sudo docker ps -a
CONTAINER ID        IMAGE                          COMMAND                CREATED             STATUS              PORTS                              NAMES
715011acf8a9        kbastani/docker-neo4j:latest   "/etc/bootstrap.sh -   9 seconds ago       Up 8 seconds        1337/tcp, 0.0.0.0:7474->7474/tcp   graphdb
