### ISSUE TITLE
spelling error in the ulimits documentatiion

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#12553]
http://docs.docker.com/reference/commandline/cli/#default-ulimits

inheritted > inherited

**Comment by buddhamagnet** [comment]
#dibs

**Comment by buddhamagnet** [comment]
This looks like it's already been fixed?

Found another one in ```docker_cli_run_test.go``` however.

**Comment by moxiegirl** [comment]
closing for reason mentioned by @buddhamagnet --- thanks for the check and the grep!
