### ISSUE TITLE
file exists at %!s(MISSING), can't create volume there

### ISSUE THREAD

**Issue by dinuschen** [docker/docker#12584]
I use wurstmeister's image to run multiple kafka brokers in docker. Operations see http://wurstmeister.github.io/kafka-docker/.
But failed:
file exists at %!s(MISSING), can't create volume there

I wan't to kown why and how to solve it.

(Cent OS 7, kernal 3.10.0-229.el7.x86_64
docker 1.5.0
docker-compose 1.1.0)

**Comment by coolljt0725** [comment]
I think this is fixed by https://github.com/docker/docker/pull/11934 , can you try docker 1.6.0?

**Comment by calavera** [comment]
I'm going to close this issue since it looks like #11934 solved the problem. Please, feel free to reopen it if you find it again with a newer version of Docker.
