### ISSUE TITLE
Unable to list docker images after sudden reboot

### ISSUE THREAD

**Issue by aku163** [docker/docker#12585]
May be its a duplicate thread, but I am totally stuck with the issue. 

docker daemon got started post reboot of machine. But when I do 'docker images' command, it returns nothing except the header part.

docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE

How can I get that back?

**Comment by SimonWang2014** [comment]
You can enter the docker image file to check if the images exist, if none ,you just to download again

**Comment by aku163** [comment]
Thanks Simon. I got the images remounted and started the services. Got my breath back :)
