### ISSUE TITLE
docker exec run under the user when container was created

### ISSUE THREAD

**Issue by tonicbupt** [docker/docker#12591]
I wanna use macvlan to manage my network between containers and then I have to run `ip link addr add 10.1.1.1/16 dev veth` in container,  of course this requires root, but my container runs under its own user like `2001`, so I am wondering if `docker exec` can be run in root mode as an option.

**Comment by coolljt0725** [comment]
@tonicbupt  yes, `docker exec` can be run in root mode as an option. see #12025

**Comment by tonicbupt** [comment]
@coolljt0725 bravo! so I can wait the next release! thanks!
@CMGS your agent can now get rid of `nsenter`
