### ISSUE TITLE
Problem with -v shared folders in 1.6

### ISSUE THREAD

**Issue by dmenne** [docker/docker#12590]
System: Window 7/64

With:
``` 
Boot2Docker version 1.5.0, build master : a66bce5 - Tue Feb 10 23:31:27 UTC 2015 

docker run \
  -v /c/Users/Dieter/Documents/Gastrobase:/home/shiny/Gastrobase \
  hello-world
```

is a valid command. This is a simplified and function-less test version, see below for the "real" one. Note that /Dieter is a valid user, please replace for testing.

With 
```
$ docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): windows/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64

```

I could not find out how to define the path in -v; I tried several of the variants mentioned in the docs of 1.5 on shared folders.

```  
$ docker run \
>   -v /c/Users/Dieter/Documents/Gastrobase:/home/shiny/Gastrobase \
>   hello-world
invalid value "c:\\Users\\Dieter\\Documents\\Gastrobase;C:\\Program Files (x86)\\Git\\home\\shiny\\Gastrobase" for flag -v: \Users\Dieter\Documents\Ga
strobase;C:\Program Files (x86)\Git\home\shiny\Gastrobase is not an absolute path
See 'c:\Program Files\Boot2Docker for Windows\docker.exe run --help'.
```

---- Real application -------------  

```
docker run --restart=always --name gastrobase -d -p 3838:3838 \
  -v /c/Users/Dieter/Documents/Gastrobase:/home/shiny/Gastrobase \
  dmenne/gastro-docker


Dieter@DIETERPC ~
$ docker run --restart=always --name gastrobase -d -p 3838:3838 \
>   -v /c/Users/Dieter/Documents/Gastrobase:/home/shiny/Gastrobase \
>   dmenne/gastro-docker
invalid value "c:\\Users\\Dieter\\Documents\\Gastrobase;C:\\Program Files (x86)\\Git\\home\\shiny\\Gastrobase" for flag -v: \Users\Dieter\Documents\Ga
strobase;C:\Program Files (x86)\Git\home\shiny\Gastrobase is not an absolute path
See 'c:\Program Files\Boot2Docker for Windows\docker.exe run --help'.

````

**Comment by jfrazelle** [comment]
I don't understand how this could be a regression when there was never a
docker client version you could run on windows before.

**Comment by dmenne** [comment]
Maybe I should change the title to "Boot2Docker". And the -v parameter has the same --help documentation as before.

**Comment by calavera** [comment]
I don't think this is an issue parsing volumes in Docker, not really related to Boot2Docker itself. The volume path validation assumes that there is only one `:` in the string to separated host and container paths. In windows, that's not true.

See https://github.com/docker/docker/blob/master/opts/opts.go#L150

This test should expose the issue:

```diff
diff --git c/integration-cli/docker_cli_run_windows_test.go i/integration-cli/docker_cli_run_windows_test.go
new file mode 100644
index 0000000..53c69d6
--- /dev/null
+++ i/integration-cli/docker_cli_run_windows_test.go
@@ -0,0 +1,26 @@
+// +build windows
+
+package main
+
+import (
+       "fmt"
+       "io/ioutil"
+       "os"
+       "os/exec"
+
+       "github.com/docker/docker/vendor/src/github.com/go-check/check"
+)
+
+// Test that creating a container with a volume doesn't crash. See #12590
+func (s *DockerSuite) TestRunCreateVolumeAbsoluteWindowsPath(c *check.C) {
+       tmpDir, err := ioutil.TempDir("", "docker-test-container")
+       if err != nil {
+               c.Fatal(err)
+       }
+
+       defer os.RemoveAll(tmpDir)
+       cmd := exec.Command(dockerBinary, "run", "-v", fmt.Sprintf("%s:/tmp/docker-test-container", tmpDir), "busybox", "true")
+       if _, err := runCommand(cmd); err != nil {
+               c.Fatal(err)
+       }
+}
```

**Comment by ahmetalpbalkan** [comment]
@calavera you're passing a windows path to -v in your test. That's not supported. Currently both parts of the -v should be unix paths because Docker engine is running on Linux.

**Comment by ahmetalpbalkan** [comment]
@dmenne

If you're using git bash on windows, msysgit converts paths like /c/users to c:\users (not something you want because the path inside the boot2docker VM is /c/Users)

Try surrounding -v value with single quotes like: 

    ... -v '/c/Users:/path' ...

On cmd.exe/powershell you shouldn't be having this problem. Does this solve the issue?

**Comment by calavera** [comment]
that makes sense, thanks @ahmetalpbalkan.

**Comment by dmenne** [comment]
I had tried the ' ' before, but the error message is the same in all cases:

```
invalid value "c:\\Users\\Dieter\\Documents\\Gastrobase;C:\\Program Files (x86)\\Git\\home\\shiny\\Gastrobase" for flag -v: \Users\Dieter\Documents\Gastrobase;C:\Program Files (x86)\Git\home\shiny\Gastrobase is not an absolute path
```
Check the error message: for reasons I do not understand, the current msysgit path is appended to the evaluated value: 'C:\\Program Files (x86)\\Git\\home\\shiny\\Gastrobase'.

**Comment by ahmetalpbalkan** [comment]
@dmenne I think it's happening just because of the weird path interpretation of msysgit. In -v we separate paths with :, and : is also used as drive letter separator (as in c:\) and that's why I think it's getting confused.

I'd just try turning that feature off if possible in msys window or try stuff like

    ... -v 'path1:'path2' ...

But that shouldn't be really an issue on windows consoles.

**Comment by dmenne** [comment]
```-v 'path1:'path2' ```

I assume it's a typo, both paths should be in ''? I have tried both version with the same result, i.e. 'path1:path2' and 'path1':'path2'.

"Should not be an issue on windows consoles": But most people will use the default Boot2Docker console, I assume. And <blush>: I could not get the Windows consoles to work because of the dreaded TLS. I must have missed something in the docs.

**Comment by ahmetalpbalkan** [comment]
@dmenne you're right. I'll take a look to make it better on msys. In order to make it work in Windows consoles, run "boot2docker shellinit" and paste the output to your console and it should work exactly the same as it was in b2d window.

**Comment by dmenne** [comment]
Confirmed. Everything works without errors in Powershell and cmd. 
Thanks. Nevertheless, a fix for the msys-bug would be nice.

**Comment by brettp** [comment]
A hacky workaround for mysys is to use double leading slashes on the path:
```
docker run -v //c/Users/brettp/app:/app
```

**Comment by dmenne** [comment]
Krr... I thought I had tried that variant, but possible only with backslashes. Does not look hacky, but quite ok and works. Thank's for sharing. Could we put that into the docs of shared folders?

**Comment by ahmetalpbalkan** [comment]
@brettp looks nice to me heh.

**Comment by lwlsonjlg** [comment]
Yes ... that works ... why?

lwilson@LENOVO-LAPTOP ~
$ docker run ubuntu:14.04 //bin/echo 'Hello world'
Hello world

lwilson@LENOVO-LAPTOP ~
$

**Comment by lwlsonjlg** [comment]
sorry ... that last comment was for #13741

**Comment by jakob-grabner** [comment]
For everyone who still has a problem with mounting a folder on Windows. Make sure your drive letter is lowercase.

` docker run -i -t -v /c/Users/Jakob/src:/mnt some_container`

**Comment by udoless** [comment]
docker run -v //c/Users/brettp/app:/app  
Worked!

**Comment by dmenne** [comment]
Everyone reading this thread and the partially conflicting answers should be aware that it covers versions 1.6 to 1.9, and several issues have been resolved and came up new on the way. Currently, with Kitematic, things work without problems for me.
To avoid further confusion: Please add your boot2docker version when posting here.

**Comment by ericis** [comment]
I had this issue and the double slash prefix to the host path fixed it for me.

System: Windows 10 Enterprise x64
Docker Toolbox: Docker v1.9.1, Docker Machine v0.5.5

*Using the "Docker Quickstart Terminal" that runs MINGW64

**Comment by kumarharsh** [comment]
I'm trying to run:

```
docker run -u postgres --net host -v /`pwd`/file.sql://tmp/setup.sql --rm postgres:9.4 psql -h localhost -U postgres -f //tmp/setup.sql my_db;
```

which is giving me an error:

```
psql:/tmp/setup.sql:0: could not read from input file: Is a directory
```

I tried investigating the matter, by running `bash` inside the container:

```
docker run -it -u postgres --net host -v /`pwd`/file.sql://tmp/setup.sql --rm postgres:9.4 bash
```

and then I `ls -l`-ed the `/tmp` directory, and sure enough, it shows the `setup.sql` as a **directory**!

Any help?

**Comment by kumarharsh** [comment]
I figured out why the previous bug was happening: It was because my `pwd` was in `D:\` drive, and `D:\` drive is not mounted by default. To mount it, follow the instructions here: http://stackoverflow.com/a/32030385/630170

Now, the issue is that using git / msys2's bash makes it impossible to mount the D:\ volumes using either of these:

#### (with leading slash)

```
docker run ... -v //d/Workspace/000_init.sql:/tmp/file --rm cat /tmp/file
```
which gives this error: `cat: C:/Users/usr/AppData/Local/Temp/file: No such file or directory`

or 

#### (without leading slash) or (with single quotes) or (with double quotes)
```
docker run ... -v /d/Workspace/000_init.sql:/tmp/file --rm cat /tmp/file
```
which gives this error:

```
invalid value "D:\\Workspace\\000_init.sql;C:\\Users\\usr\\AppData\\Local\\Temp\\file" for flag -v: bad mode specified: \Users\usr\AppData\Local\Temp\file
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.
```

**Comment by kumarharsh** [comment]
To complete the solution, I just wrote a small powershell script to do the task which my makefile was trying to do. Seems to be the only way for now.

**Comment by krishna81m** [comment]
This hack seems to work like a charm if you have downgraded to 1.9 from the AUFS issues in 1.9.1
```
docker create -v //c/Users/myuser:/myuser --name data hello-world
winpty docker run -it --rm --volumes-from data ubuntu
```

**Comment by mzvast** [comment]
double // before win path works for me,thanks a lot:)

**Comment by alexeenka** [comment]
I have the same problem on my Windows 7, thanks for thread, i find a solution. In my case following works:

docker run -it --rm -v '//c/Users/user/!prj:/home/jenkins/prj' profile_name bash

**Comment by webguywalker** [comment]
> double `//` before win path works for me,thanks a lot:)
:+1:

**Comment by datumgeek** [comment]
just wanted to chime in and say how awesome this fix is !!!! :1st_place_medal:

**Comment by kumarharsh** [comment]
Update: I threw out the powershell script I was using earlier, and fixed the problem in the Makefile itself. I just exported `MSYS_NO_PATHCONV=1` for any tasks which used linux-style paths or using ``pwd``.

example:

```Makefile
.PHONY: init
init: export MSYS_NO_PATHCONV=1 # stop path conversion for msys in windows
init: ## Initialize a database
				docker run -u postgres --net host -v `pwd`/schemas/sql/postgres.sql:/tmp/setup.sql --rm postgres:9.5 psql -h localhost -U postgres -f /tmp/setup.sql code_db
```

Ref: https://github.com/git-for-windows/msys2-runtime/pull/11

**Comment by gauravshindolkar** [comment]
Can someone help me with below command? I am  quite new to docker and performing the Swarm Project of the [voting app](https://docs.docker.com/swarm/swarm_at_scale/deploy-infra/#task-3-add-the-load-balancer) that docker documentation has. Now I am on a windows machine and after reading this thread tried to modify my commands to below, however it fails.

Command 1:
`docker run -P -d -ti -v nginx:/etc/conf -v /var/lib/boot2docker:/var/lib/boot2docker:ro -v /var/run/docker.sock:/var/run/docker.sock -v //d/Docker/docker-voting-app/config/config.toml:/etc/config.toml --name interlock ehazlett/interlock:1.0.1 -D run -c /etc/config.toml`

Command 2:
`docker run -P -d -ti -v nginx:/etc/conf -v /var/lib/boot2docker:/var/lib/boot2docker:ro -v /var/run/docker.sock:/var/run/docker.sock -v %cd%/config.toml:/etc/config.toml --name interlock ehazlett/interlock:1.0.1 -D run -c /etc/config.toml`

error
```
time="2017-06-11T12:43:38+05:30" level=info msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"
docker: Error response from daemon: invalid bind mount spec "D:\\Docker\\docker-voting-app\\config/config.toml:/etc/config.toml": invalid mode: /etc/config.toml.
See 'docker run --help'.
```


Tried this in powershell and on default CMD but no luck. Still getting below error in docker logs.

```
PS C:\Users\Gaurav> docker logs interlock
time="2017-06-11T12:34:42+05:30" level=info msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"
INFO[0000] interlock 1.0.1 (000291d)
DEBU[0000] loading config from: /etc/config.toml
FATA[0000] read /etc/config.toml: is a directory
```

**Docker Version:** 
```
> docker version
time="2017-06-11T12:41:26+05:30" level=info msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 21:43:09 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by thaJeztah** [comment]
@gauravshindolkar Please keep in mind that the GitHub issue tracker is not intended as a general support forum, but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

**Comment by kumarharsh** [comment]
@gauravshindolkar read my solution just above your comment.

**Comment by chen-xin** [comment]
@kumarharsh thank you. I fixed this by creating an bash script:
```
#!/bin/bash
export MSYS_NO_PATHCONV=1
docker run --rm \
-v mynamedvol:/data \
-v $PWD/data:/backup \
alpine \
sh "tar zcvf /backup/mybackup.tar.gz /data"
```

**Comment by dhan2vijay** [comment]
invalid bind mount spec "c:\\users\\admin.wsd027\\documents\\visual studio 2015\\Projects\\aspnetcorec1\\src\\aspnetcorec1:/app:rw": invalid volume specification i am just getting this issue can some one please help me out

**Comment by hugokoka** [comment]
I solved it!

Add a volume:

docker run -d -v my-named-volume:C:\MyNamedVolume testimage:latest

Mount a host directory:

docker run -d -v C:\Temp\123:C:\My\Shared\Dir testimage:latest

**Comment by mattcbaker** [comment]
If anyone is interested, I dug into this problem and came up with a few solutions [here](https://mattcbaker.com/post/mounting-window-dir-docker/).

Some solutions:
1. Use `MSYS_NO_PATHCONV` to disable POSIX -> Windows path conversions.
1. Pass the command off to the Windows shell.
1. Something else?
