### ISSUE TITLE
Remove error check

### ISSUE THREAD

**Issue by runcom** [docker/docker#12607]
Assignment, error check (and return) at https://github.com/docker/docker/blob/master/api/server/server.go#L947-950 should be removed.

Implement `intValue` in https://github.com/docker/docker/blob/master/api/server/form.go (following how `int64Value` is implemented to return 0 on error) and use it directly in the call to `ContainerRestart` at https://github.com/docker/docker/blob/master/api/server/server.go#L952 like `intValue(r.Form.Get("t"))`

**Comment by calavera** [comment]
You can use `int64Value` from https://github.com/docker/docker/blob/master/api/server/form.go#L14 or add another helper for int values there to be consistent.

**Comment by runcom** [comment]
sure, this was meant as a beginner issue @calavera, I may add `intValue` then

**Comment by calavera** [comment]
yeah, I just wanted to mention that we already have those there, so we're consistent :smile:

**Comment by runcom** [comment]
@calavera yup, I'm thinking to update this issue to include `intValue` implementation along with this to entirely remove the error checking/ignoring here

**Comment by calavera** [comment]
sounds great!

**Comment by runcom** [comment]
updated

**Comment by runcom** [comment]
@LK4D4 @calavera could we add label exp/beginner or exp/proficient here?

**Comment by adcaes** [comment]
#dibs
