### ISSUE TITLE
better introductory material

### ISSUE THREAD

**Issue by ccorcos** [docker/docker#12608]
hey there, I'm totally new to Docker but I've heard so much about it that I figured I'd give it a shot.

I checked this out on the website: https://www.docker.com/tryit/

I must say, I have a lot of questions after going through this tutorial. Before I move on and find answers to all my questions, I thought I'd leave them here to improve the tutorial.

---

There seems to be some concept of an image and a container which are different things, but I have no idea what the difference is so I'm just going to call everything a container.

We download `learn/tutorial`. We run an echo command through it. Then we install ping though it. My understanding is that ping was installed in the `learn/tutorial` container. But then what's the difference between `docker ps` and `docker ps -l`? We then commit this "change" to learn/ping -- I'm assuming this is analogous to creating a new branch from learn/tutorial. I could have just as easily committed back to learn/tutorial?

---

Anyways, I hope those questions make sense. I think it would help to give some git analogies in there. No need to answer all the questions -- I can figure  it out. I just figured getting these questions out could improve the "try it" experience.

**Comment by thaJeztah** [comment]
Thanks for the feedback, @ccorcos! Getting feedback like this from someone that still has a "fresh" look at the documentation (and Docker in general) can be very useful.

I'm going to include @moxiegirl here, perhaps she has some thoughts on improving this part of the docs.

Note that we may close this issue at some point, don't see that as "down voting" your report, but just to keep the number of issues on our issue tracker down, we *will* take your feedback into account! :smile:

**Comment by ccorcos** [comment]
Definitely. Feel free to close it whenever you feel.

**Comment by RickWieman** [comment]
Nice issue!

The notion of containers and images (and their differences) also got me puzzling the first time I started using Docker, so I don't think you're the first one, nor the last one. I think it should be one of the things that has to be clear as one of the first things, as everything is built up around those concepts.

**Comment by calavera** [comment]
Lots of things have happened in a year with documentation. Closing this, thanks!
