### ISSUE TITLE
Dockerfiles grammar

### ISSUE THREAD

**Issue by fntlnz** [docker/docker#12610]
Dockerfiles have their own syntax and right now the main parsing logic and AST related things have been implemented in `builder/parser/parser.go`. I think that there has been made a pretty good job but I thought that the same thing can be accomplished with a context free grammar that can be converted into a LR parser written in go.
This would make the parser more readable and would help a lot in debugging and maintaining/adding new features thanks to the fact that it would need a half of the actual code and as its simplicity can give a real help creating the AST.

What do you think?

**Comment by jfrazelle** [comment]
see https://github.com/docker/docker/issues/12221

**Comment by jfrazelle** [comment]
closing as duplicate

**Comment by jfrazelle** [comment]
the conversation can continue there :)
