### ISSUE TITLE
docker create container error  chance  happen

### ISSUE THREAD

**Issue by blackfader** [docker/docker#12618]
I use docker 1.6.0，filesystem devicemapper。

docker create container print error accidental。
error:
INFO[0017] Error getting container 8eb4136bed3eb55b85dc2f0025aca0ff965bdae4f9593621290455c4989de5dc from driver devicemapper: Error mounting '/dev/mapper/docker-253:1-1445533-8eb4136bed3eb55b85dc2f0025aca0ff965bdae4f9593621290455c4989de5dc' on '/usr/local/docker/devicemapper/mnt/8eb4136bed3eb55b85dc2f0025aca0ff965bdae4f9593621290455c4989de5dc': no such file or directory

docker storage

DOCKER_STORAGE_OPTIONS="--storage-opt dm.basesize=20G --storage-opt dm.loopdatasize=1000G --storage-opt dm.loopmetadatasize=12G"

docker version

Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64

docker info

Containers: 1
Images: 16
Storage Driver: devicemapper
 Pool Name: docker-253:1-1445533-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 902.8 MB
 Data Space Total: 1.074 TB
 Data Space Available: 1.073 TB
 Metadata Space Used: 5.857 MB
 Metadata Space Total: 12.88 GB
 Metadata Space Available: 12.88 GB
 Udev Sync Supported: false
 Data loop file: /usr/local/docker/devicemapper/devicemapper/data
 Metadata loop file: /usr/local/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.12.35-100.el6.x86_64
Operating System: <unknown>
CPUs: 24
Total Memory: 63.01 GiB
Name: w-app07.add.bjdt.qihoo.net
ID: AOMN:IGAR:U7R3:FRVN:RRRC:NF5H:NBWN:TFYS:35AG:K4FQ:NOVA:7C3U

**Comment by blackfader** [comment]
any body here?

**Comment by coolljt0725** [comment]
you must with `Udev Sync Supported: false` to use `devicemaper` see #4036

**Comment by unclejack** [comment]
As @coolljt0725 has stated above, this is indeed related to devicemapper and should be fixed by using dynamically linked Docker binaries.
