### ISSUE TITLE
windows lolcat (term issue)

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#12612]
in cmd.exe

if I run 
```
docker run --rm -it jess/nerdy bash
contianer-shell# figlet hi | lolcat
```
it doenst work

**Comment by ahmetalpbalkan** [comment]
This is similar to `supertest2014/nyan`. Unfortunately we can't map 256 colors from xterm to 16 colors well but I bet we could've done better.

What I see on cmd.exe

![image](https://cloud.githubusercontent.com/assets/159209/7283879/7722466c-e8ee-11e4-80c6-3cee99917bc5.png)

On OS X:
![image](https://cloud.githubusercontent.com/assets/159209/7283887/8a704156-e8ee-11e4-9bb3-3501022bbd7e.png)

@jfrazelle are you seeing something totally different than this?

**Comment by jfrazelle** [comment]
ahhhh yeah i see i can close then

On Wed, Apr 22, 2015 at 12:54 PM, Ahmet Alp Balkan <notifications@github.com
