### ISSUE TITLE
cpuPercent in API

### ISSUE THREAD

**Issue by gomex** [docker/docker#12620]
We don't have cpuPercent to get through the API[1]. We already have this information here[2], but that data can't be get throught API. Can you please add this request in next version of API?

I can get this information about docker stats command, but I can't do that through API :(

[1] - https://docs.docker.com/reference/api/docker_remote_api_v1.18/
[2] - https://github.com/docker/docker/blob/4a25c5d25bad693f9e79a810d87f9103769f918c/api/client/stats.go

**Comment by cpuguy83** [comment]
@gomex the CLI talks to the API (same API you use).
```json
 "cpu_stats" : {
    "cpu_usage" : {
       "percpu_usage" : [
          16970827,
          1839451,
          7107380,
          10571290
       ],
       "usage_in_usermode" : 10000000,
       "total_usage" : 36488948,
       "usage_in_kernelmode" : 20000000
    },
    "system_cpu_usage" : 20091722000000000,
    "throttling_data" : {}
 }
```

Closing since this information is available.
