### ISSUE TITLE
Security disclosures shouldn't be sent clear-text over email?

### ISSUE THREAD

**Issue by knutole** [docker/docker#12639]
Should perhaps encourage users to disclose security bugs with PGP? Not everyone is a-ok with Uncle Sam picking up disclosures before anyone else. 

`#justsayin`

**Comment by thaJeztah** [comment]
In an ideal world, yes. However, I don't think we should make things too difficult for people to disclose them. It's already a challenge to have people disclose security issues the right way (I've seen some issues appear here on GitHub)

/cc @ewindisch

**Comment by knutole** [comment]
Yeah, I understand your point. It's certainly more important not to post directly to GitHub than to use PGP. It would be nice to have an easily available key for those that are willing and capable of using it, though. That would at least be a road-sign pointing in the direction of an ideal world.

**Comment by jfrazelle** [comment]
ping @ewindisch @diogomonica @NathanMcCauley

**Comment by jfrazelle** [comment]
i love pgp hehehe just saying

#strongSetRepresent

**Comment by diogomonica** [comment]
I think PGP in this particular use-case is more trouble than it's worth.

**Comment by ewindisch** [comment]
It might be nice in a perfect world, but it would be difficult for us to implement for a vulnerability management team. We'd need to share a private key (not very private) and deal with having the interface to such a system support PGP... or have an MTA-in-the-middle doing decryption (in which case we'd need it to sign the plaintext so we could locally verify it...)

That said, as nice as all that would be, it *would* be lot of trouble.

**Comment by diogomonica** [comment]
We're not going to do this. Please close.
