### ISSUE TITLE
link error message was hard to read

### ISSUE THREAD

**Issue by paulweb515** [docker/docker#12638]
I had a container I had started up with `--name=original_node --expose=5858,8081`.  When I started up a second container with `--name=link_node --link=original_node:pwnode ` I got an error message about TLS:

<pre>
FATA[0001] Post http:///var/run/docker.sock/v1.16/containers/6f14a062cd1589d2c40238ec04042f54c7092702bad1a8ec977099aa3addfa67/start: EOF. Are you trying to connect to a TLS-enabled daemon without TLS? 
</pre>

After adding `-D` to the docker daemon, the log shows the error that caused the link_node container to fail to start:

<pre>
time="2015-04-21T13:17:57-04:00" level="info" msg="POST /v1.16/containers/link_node/start"
time="2015-04-21T13:17:57-04:00" level="info" msg="+job start(link_node)"
time="2015-04-21T13:17:57-04:00" level="info" msg="+job allocate_interface(7e964d6133695f07fab007cfdd39924af6386545254bac47b6fdda7fb7f020d9)"
time="2015-04-21T13:17:57-04:00" level="info" msg="-job allocate_interface(7e964d6133695f07fab007cfdd39924af6386545254bac47b6fdda7fb7f020d9) = OK (0)"
time="2015-04-21T13:17:57-04:00" level="info" msg="+job link(-I)"
time="2015-04-21T13:17:57-04:00" level="info" msg="-job link(-I)"
time="2015-04-21T13:17:57-04:00" level="info" msg="-job start(link_node)"
2015/04/21 13:17:57 http: panic serving @: strconv.ParseUint: parsing "5858,8081": invalid syntax
goroutine 365 [running]:
net/http.func·011()
        /usr/lib/golang/src/pkg/net/http/server.go:1100 +0xb7
runtime.panic(0xa38a20, 0xc20afd65d0)
        /usr/lib/golang/src/pkg/runtime/panic.c:248 +0x18d
github.com/docker/docker/nat.Port.Int(0xc2085881f0, 0xd, 0xc2085881fa)
        /builddir/build/BUILD/docker-1.4.1/_build/src/github.com/docker/docker/nat/nat.go:57 +0x98
github.com/docker/docker/daemon/networkdriver/bridge.LinkContainers(0xc20b000d00, 0x7f3d7c95b8c8)
        /builddir/build/BUILD/docker-1.4.1/_build/src/github.com/docker/docker/daemon/networkdriver/bridge/driver.go:515 +0x222
github.com/docker/docker/engine.(*Job).Run(0xc20b000d00, 0x0, 0x0)
        /builddir/build/BUILD/docker-1.4.1/_build/src/github.com/docker/docker/engine/job.go:83 +0x837
github.com/docker/docker/links.(*Link).toggle(0xc20ae76460, 0xb1b7a0, 0x2, 0x961a00, 0x0, 0x0)
        /builddir/build/BUILD/docker-1.4.1/_build/src/github.com/docker/docker/links/links.go:169 +0x288
github.com/docker/docker/links.(*Link).Enable(0xc20ae76460, 0x0, 0x0)
        /builddir/build/BUILD/docker-1.4.1/_build/src/github.com/docker/docker/links/links.go:141 +0x52
github.com/docker/docker/daemon.(*Container).setupLinkedContainers(0xc2089556c0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /builddir/build/BUILD/docker-1.4.1/_build/src/github.com/docker/docker/daemon/container.go:1128 +0x55a
github.com/docker/docker/daemon.(*Container).Start(0xc2089556c0, 0x0, 0x0)
        /builddir/build/BUILD/docker-1.4.1/_build/src/github.com/docker/docker/daemon/container.go:346 +0x2db
github.com/docker/docker/daemon.(*Daemon).ContainerStart(0xc208055550, 0xc20b000a80, 0x1)
        /builddir/build/BUILD/docker-1.4.1/_build/src/github.com/docker/docker/daemon/start.go:38 +0x38b
github.com/docker/docker/daemon.*Daemon.ContainerStart·fm(0xc20b000a80, 0x7f3d7c95b8c8)
        /builddir/build/BUILD/docker-1.4.1/_build/src/github.com/docker/docker/daemon/daemon.go:124 +0x30
github.com/docker/docker/engine.(*Job).Run(0xc20b000a80, 0x0, 0x0)
        /builddir/build/BUILD/docker-1.4.1/_build/src/github.com/docker/docker/engine/job.go:83 +0x837
github.com/docker/docker/api/server.postContainersStart(0xc208094840, 0xc2089d58c7, 0x4, 0x7f3d7c967ea8, 0xc20afa4640, 0xc208b3cc30, 0xc2089d5950, 0x0, 0x0)
        /builddir/build/BUILD/docker-1.4.1/_build/src/github.com/docker/docker/api/server/server.go:801 +0x1ba
github.com/docker/docker/api/server.func·002(0x7f3d7c967ea8, 0xc20afa4640, 0xc208b3cc30)
        /builddir/build/BUILD/docker-1.4.1/_build/src/github.com/docker/docker/api/server/server.go:1219 +0x810
net/http.HandlerFunc.ServeHTTP(0xc20805ff00, 0x7f3d7c967ea8, 0xc20afa4640, 0xc208b3cc30)
        /usr/lib/golang/src/pkg/net/http/server.go:1235 +0x40
github.com/gorilla/mux.(*Router).ServeHTTP(0xc2080f3360, 0x7f3d7c967ea8, 0xc20afa4640, 0xc208b3cc30)
        /builddir/build/BUILD/docker-1.4.1/vendor/src/github.com/gorilla/mux/mux.go:98 +0x297
net/http.serverHandler.ServeHTTP(0xc208005740, 0x7f3d7c967ea8, 0xc20afa4640, 0xc208b3cc30)
        /usr/lib/golang/src/pkg/net/http/server.go:1673 +0x19f
net/http.(*conn).serve(0xc20b000a00)
        /usr/lib/golang/src/pkg/net/http/server.go:1174 +0xa7e
created by net/http.(*Server).Serve
        /usr/lib/golang/src/pkg/net/http/server.go:1721 +0x313
time="2015-04-21T13:19:44-04:00" level="info" msg="POST /v1.16/containers/link_node/stop?t=10"
time="2015-04-21T13:19:44-04:00" level="info" msg="+job stop(link_node)"
</pre>

Starting original_node with `--expose=5858 --expose=8081` allowed the second container to start.  It was suggested the error message could be improved.

**Comment by calavera** [comment]
#dibs

**Comment by calavera** [comment]
Hi @paulweb515,

It looks like this problem has been solved already in more modern versions of docker. Docker 1.6 gives you a more readable error when the exposed port cannot be parsed, check it out:

![1 zsh 2015-04-22 13-00-48](https://cloud.githubusercontent.com/assets/1050/7284080/ed3db240-e8ef-11e4-970e-bb5820e8da19.png)

Do you mind to close this issue?

**Comment by paulweb515** [comment]
Already fixed.  Thanks.
