### ISSUE TITLE
Docker commands freeze, not executed

### ISSUE THREAD

**Issue by jl-montes** [docker/docker#12643]
On rare occasions I've noticed a system will appear to have a docker freeze/hang when issuing docker commands.

You can run 'docker' alone and see usage info/verbiage on stdout, but if you issue any docker commands stdout freezes/hangs infinitely until the user issues a CTRL-C to exit

Examples:
docker ps
docker images
docker run ......

O/S: CoreOS 494.5.0
Docker Version:
Client version: 1.3.3
Client API version: 1.15
Go version (client): go1.3.2
Git commit (client): 5dc1c5a

**Comment by knutole** [comment]
I get the same sometimes during builds, it just hangs and won't continue. `Ctrl-C` and re-build will run fine. Got this on both 1.5 and 1.6.

**Comment by cpuguy83** [comment]
Seems like two different issues.
@jl-montes Sounds like there is either a deadlock or a command running that hasn't released the lock for some reason.
In any case, this is against a _really_ old version of docker.

I'm going to close this, but please ping if you are still having problems with docker 1.8.
Thanks!
