### ISSUE TITLE
DockerSuite.TestEventsFilterContainer too long

### ISSUE THREAD

**Issue by LK4D4** [docker/docker#12660]
`DockerSuite.TestEventsFilterContainer` takes 10 seconds to run. This is weird because from code it should be fast.
You need to investigate what's going on. First ideas is not use `waitInspect`, but just inspect to find name, but it is still weird, because error from `waitInspect` is not checked.

**Comment by DarianAnjuhal** [comment]
#dibs

I am new and try to do my first issue..

**Comment by runcom** [comment]
@LK4D4 should this be closed because of #12754 is merged?

**Comment by LK4D4** [comment]
@runcom Thanks!
