### ISSUE TITLE
Docker Command Substitution

### ISSUE THREAD

**Issue by UserTaken** [docker/docker#12676]
Command substitution as in `docker stats $(docker ps -q)` works with `start`, `stop`, `kill`, `restart`, `rm`, `stats`, `pause`, and `unpause`. So I'm wondering if there's a reason to why the same thing doesn't work with `top`, `logs`, `port`, `inspect`? As a workaround I have been using `for i in $(docker ps -q); do echo -e "\n$i"; docker top $i; done`. Something else is that there's a arugment to `ps` to only prints the container ID. Wouldn't an argument to print only container name work just as well?

**Comment by phemmer** [comment]
If you look at the help usage of each of the commands (`top`, `logs`, etc), you'll see why:
```
# docker top --help

Usage: docker top [OPTIONS] CONTAINER [ps OPTIONS]
```

Notice how the command takes options after the container specifier. There's no way to differentiate between multiple containers, or a single container with multiple options.

For example:

```
docker top 01 ef
```

`01` is the first 2 digits of the container ID, and `ef` is the options. If this were to allow multiple containers, there would be no way to tell if `ef` should be options, or container ID.

**Comment by UserTaken** [comment]
@phemmer `ps -q` print perfect strings of 12 digit low case alphanumeric characters so I would think they could be one way to differentiate between multiple containers and options. `logs` does not take any options after the container specifier so why does `docker logs $(docker ps -q)` not work?

**Comment by cpuguy83** [comment]
@UserTaken Can you open a new issue if you still want this feature for concatenating logs from multiple containers via the CLI?

Closing this one as @phemmer explained, these other options take extra arguments after the container name and can't handle multiple containers.
