### ISSUE TITLE
Why docker build duplicates git clone logic 

### ISSUE THREAD

**Issue by dalanlan** [docker/docker#12670]
quick question
Why does `docker build` duplicate `git clone` logic in src code? Any difference?

https://github.com/docker/docker/blob/master/api/client/build.go#L109
https://github.com/docker/docker/blob/master/builder/job.go#L116

**Comment by phemmer** [comment]
That uses `git clone`, not duplicates the logic.
As for why: https://docs.docker.com/reference/commandline/cli/#build

> The URL parameter can specify the location of a Git repository; in this case, the repository is the context. The Git repository is recursively cloned with its submodules.

**Comment by dalanlan** [comment]
Let me try to make myself more clear. Why is `git clone` called separately by client and server, since context has been sent to server already.

**Comment by duglin** [comment]
That's an interesting question.
@tiborvass @erikh do you know why we don't just send the github URL to the daemon and let it do the clone?

**Comment by LK4D4** [comment]
@duglin I think idea was that sever can have no git or internet.

**Comment by tianon** [comment]
It was also backwards compatibility.  It was originally in the server, but
in the server we're running as root and don't have the user's "~/.ssh" so
couldn't clone private repos.  When it moved to the client to fix this, the
server still needed to be able to clone, since it had been doing so
previously.

**Comment by duglin** [comment]
Does this mean that the daemon support for git URLs is (sort of) deprecated?

**Comment by tianon** [comment]
Only if it's gated based on older API versions. :+1:

**Comment by calavera** [comment]
I'm working on that git stuff in #12502, good timing to remove duplicity.

**Comment by calavera** [comment]
Fixed in #12502
