### ISSUE TITLE
Docker processes lingering around

### ISSUE THREAD

**Issue by noteed** [docker/docker#12684]
Using docker 1.5, I have noticed that I have a lot of `/usr/bin/docker -d -H fd://` listed by `htop` but not by `ps ax`. All containers removed (i.e. `docker ps -a` returns nothing). I think the list is growing whenever I use `docker exec -d`. (I don't know if the `-d` is important or not.)

```
> docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.3.3
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.3.3
Git commit (server): a8a31ef
```

**Comment by vdemeester** [comment]
If you use the Tree view mode and the "Use different color for thread" you would see these are just thread for the main docker engine process. I don't think there is anything wrong here..

**Comment by noteed** [comment]
Yes, I thought they were threads. That being said, is it normal that their number is growing ?

**Comment by cpuguy83** [comment]
I don't see any growth around using `exec` on 1.6
