### ISSUE TITLE
Debian 8 has no package update

### ISSUE THREAD

**Issue by baptistedonaux** [docker/docker#12686]
Hi,

I don't know where I must post  this issue. I works with Debian 8 and the last version of Docker stay the 1.3.3.

An idea why debian jessie hasn't package updated ?

**Comment by vdemeester** [comment]
You would likely report this on the debian issue tracker. But it's more or less how debian stable works, there is no major update of packages.

To have an up-to-date docker package, use the docker apt repository (using this ``wget -qO- https://get.docker.com/ | sh`` or manually add the ``deb https://get.docker.com/ubuntu docker main > /etc/apt/sources.list.d/docker.list`` and import the gpg key) and the ``lxc-docker`` package instead.

Anyway it's a packaging issue, related to Debian, nothing to do here, except maybe update the documentation on the Debian page.

**Comment by baptistedonaux** [comment]
Thank you for your response. I had re-try with your command but I would have a fail before (docker service is masked).

I run these commands :
```bash
sudo wget -qO- https://get.docker.com/ | sh
sudo echo "deb https://get.docker.com/ubuntu docker main" > /etc/apt/sources.list.d/docker.list
sudo apt-get update
sudo apt-get install lxc-docker
sudo systemctl unmask docker.service
sudo systemctl unmask docker.socket

sudo service docker restart
```

Without  ```systemctl unmask```, the service docker is unusable.

**Comment by vdemeester** [comment]
ah never tried debian + systemd for now so I don't know :P

**Comment by cpuguy83** [comment]
First, you must uninstall the `docker.io` package from debian.
Then run `curl -sSL https://get.docker.com | sh`. That should be all.

**Comment by baptistedonaux** [comment]
The [documentation](https://github.com/docker/docker/blob/master/docs/sources/installation/debian.md#debian-jessie-80-64-bit) is it really usable ?

**Comment by cpuguy83** [comment]
@baptistedonaux That documentation is correct, however it won't be the latest docker version.

**Comment by baptistedonaux** [comment]
Ok, I wanted the last release. Thank you for help.

**Comment by dworzanski** [comment]
@cpuguy83 The docs are not correct. There is no `docker.io` package in backports. The package would be [here](https://packages.debian.org/jessie-backports/docker.io). A search for it reveals [nothing](https://packages.debian.org/search?keywords=docker.io&searchon=names&section=all&suite=jessie-backports). I also tried to manually install it from backports and an error confirmed it did not exist there.

The only places the [Docker package](https://packages.debian.org/search?suite=all&arch=any&searchon=names&keywords=docker.io) exists in Debian at this time is in sid and experimental.

Debian has essentially abandoned Docker for the time being. This isn't your fault.

`curl -sSL https://get.docker.com | sh` works fine.

**Comment by thaJeztah** [comment]
@dworzanski adding docker to backports is currently being worked on, see https://github.com/docker/docker/issues/13253#issuecomment-103441306
