### ISSUE TITLE
The output of `docker run -t` contains `\r\n` end of line.

### ISSUE THREAD

**Issue by noteed** [docker/docker#12685]
I don't know if this is required for the pseudo-TTY to work but those two commands produce different results:

```
> docker run -t ubuntu:14.04 echo hello > a
> docker run ubuntu:14.04 echo hello > b
> ls -la a b
-rw-rw-r-- 1 thu thu 7 Apr 23 12:31 a
-rw-rw-r-- 1 thu thu 6 Apr 23 12:31 b
```

Notice that the files have different sizes; the longest one has a trailing `\r\n` and the shorter has only `\n`.

This bite me because I was using `cut` to extract a directory name, and the result was terminated by `\r`.

**Comment by cpuguy83** [comment]
Using `-t` both stderr and stdout and combined into one stream, which is likely the cause of this.

**Comment by noteed** [comment]
Maybe it is perfectly normal that allocating a pseudo-TTY implies using `\r\n` line termination but I would like to be sure this is expected from docker and maybe redirected to the proper place in the documentation.

That being said I don't understand how it is likely to be related to stderr being output too:
- The '\r' would always be "inserted" before the `\n`, which is clearly from stdout.
- I don't see `echo hello` make any use of stderr.

Can you elaborate ?
