### ISSUE TITLE
more docs for ulimit nproc

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#12695]
The `nproc` setting for `--ulimit` seems to be a special case in that it is limited per user (and per process). As such if you start up multiple containers using the same uid, they are limited by the same `nproc` value, for example:

```
docker run -d -u daemon --ulimit nproc=3 busybox top
docker run -d -u daemon --ulimit nproc=3 busybox top
docker run -d -u daemon --ulimit nproc=3 busybox top
docker run -d -u daemon --ulimit nproc=3 busybox top
```

The last `docker run` will fail since each container is using the same uid, and nproc for that user has been limited to 3... this is, unfortunately, how the system handles `nproc`

Some extra docs explaining this would be extremely helpful.

**Comment by jmzwcn** [comment]
Hi cpuguy83,

Do you mean we need append this explaining at https://github.com/docker/docker/blob/master/docs/sources/reference/commandline/cli.md#default-ulimits?

**Comment by jmzwcn** [comment]
e.g this explanation look like:
For "nproc" tag, you should set "nproc" more than actual container count; otherwise, a failure will occur.

**Comment by cpuguy83** [comment]
Probably both there and here: https://github.com/docker/docker/blob/master/docs/sources/reference/commandline/cli.md#setting-ulimits-in-a-container

I would explain exactly what's happening and why with an example (but probably better than the one I wrote above?)

**Comment by jmzwcn** [comment]
Nice, wait for your update.

**Comment by thaJeztah** [comment]
Wanted to suggest to add a mention to [Run reference](https://docs.docker.com/reference/run/#runtime-constraints-on-cpu-and-memory), but it looks like `--ulimit` never made it into that document

**Comment by amouat** [comment]
Also note that you can't set nproc ulimits for root. Which is probably a good thing given the above, but not obvious.

**Comment by resouer** [comment]
@cpuguy83 I noticed this issue earlier when i try to fix fork bomb. 

So, #dibs

**Comment by jmzwcn** [comment]
Sure, thank you,@resouer!
