### ISSUE TITLE
File mounted as a volume in a container spawned from another container becomes a directory

### ISSUE THREAD

**Issue by rsokolowski** [docker/docker#12696]
I'm creating Docker container from within a Docker container. When I mount a file volume (or a directory that contains files) to a child container then it is viewed as a directory.
docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

$ echo 'file' > file.txt
$ docker run -i  -v /var/run/docker.sock:/var/run/docker.sock:ro -v /usr/bin/docker:/usr/bin/docker:ro -v ~/file.txt:/file.txt ubuntu:latest
$ ls -lh
...
-rw-r-----   1 108109 5000    5 Apr 23 14:25 file.txt
$ docker run -v /file.txt:/file.txt ubuntu:latest ls -lh
...
drwxr-xr-x   2 root root 4.0K Apr 23 14:26 file.txt

Am I doing something wrong or is it a bug ? Thanks !

**Comment by cpuguy83** [comment]
Yes, doing something wrong I think.
Keep in mind, you aren't running a container inside another container. You're attaching to a container from inside a container, but both are running directly on the outer daemon.

So `/file.txt` does not exist on the host fs, only in the container fs.
The mount here will come from the host.
