### ISSUE TITLE
docker man page is misleading about format of commands

### ISSUE THREAD

**Issue by programmerq** [docker/docker#12708]
The main docker manpage, `man docker`, makes it look like you can do things like `docker-ps` instead of `docker ps`, which is unintentionally misleading.

Given these parts of the manpage:

> **COMMANDS**
> &nbsp;&nbsp;&nbsp;&nbsp;**docker-attach(1)**
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Attach to a running container

This formatting *suggests* that I might want to run `docker-attach` as opposed to `docker attach`. This doesn't work of course, but it might be more clear to specifically refer to `attach` as the command, and point out that full documentation for attach is found in the `docker-attach(1)` manpage.

> **COMMANDS**
> &nbsp;&nbsp;&nbsp;&nbsp;**attach**
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Attach to a running container.
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;See **docker-attach(1)** for full documentation on the **attach** command.

**Comment by DarianAnjuhal** [comment]
Should I change that?

**Comment by programmerq** [comment]
+kind/writing
+docs-only

**Comment by programmerq** [comment]
+kind/writing

**Comment by albers** [comment]
+1

**Comment by WeiZhang555** [comment]
#dibs

**Comment by WeiZhang555** [comment]
I want to help do this :)

**Comment by vdemeester** [comment]
This one is closeable too then as #12817 has been merged :)

**Comment by programmerq** [comment]
agreed. closing. :)
