### ISSUE TITLE
delete "defer deleteContainer"

### ISSUE THREAD

**Issue by runcom** [docker/docker#12705]
Since docker test suite is now using gocheck there's no need to have such code anymore. Find and delete occurrences.

**Comment by vdemeester** [comment]
#dibs

On question though : does this apply just for ``defer deleteContainer`` or also others like ``defer deleteImages`` ?

And another question that is not really related but a tiny bit, the docker test suite is now using gocheck on docker_api_container & co, but not on, for example ``pkg/archive`` (and several others) ; it would be cool to setup gocheck on these too right ?

**Comment by runcom** [comment]
@vdemeester It only applies to defer deleteContainer, regarding the second question yes would be cool but def not in this pr :D

**Comment by vdemeester** [comment]
@runcom yes, for sure ;) that's was just a question, as I worked on them these past few days
