### ISSUE TITLE
logs with follow=1 should always be replied immediately

### ISSUE THREAD

**Issue by a-ba** [docker/docker#12704]
When calling `GET /containers/(id)/logs?follow=1` on a container which has **not yet produced any output** the current behaviour of the engine is to delay the HTTP response until the container writes some output.

The client cannot guess if the command is successful until some data is received.

This is problematic for example when you need to make the request in the foreground thread and process its output in a background thread. In python you would write something like:
```py
    gen = client.logs(container, follow=True)
    executor.submit(func, gen)
```
client.logs() returns a generator that is sent to another thread. However if the container log is empty then client.logs() hangs and will return the generator only when some output is available.

**Comment by LK4D4** [comment]
@a-ba You mean write HTTP status?

**Comment by a-ba** [comment]
the HTTP status and the headers (both are needed for parsing the response)
