### ISSUE TITLE
Remove empty line after client.CmdInspect docstring

### ISSUE THREAD

**Issue by LK4D4** [docker/docker#12706]
subj

**Comment by alimoeeny** [comment]
#dibs

**Comment by alimoeeny** [comment]
:D looks like we got it exactly at the same time, go ahead, I'll do something else. If I am not mistaken it points to line 16 of `api/client/inspect.go`

**Comment by DarianAnjuhal** [comment]
I had a look in api/client/inspect.go as well. But I didn't knew where this empty line in the docstring should be?!

**Comment by alimoeeny** [comment]
I think it is like 16 the commented line, I think the issue is that empty commented line shows up in the documentation / help

**Comment by DarianAnjuhal** [comment]
Okay, I tought the same. But I dont know how this doc stuff works...

**Comment by alimoeeny** [comment]
I guess, they meant just delete that line and commit and send a pull request, that's it.

**Comment by jmzwcn** [comment]
Alimorrny,  DarianAnjuhal  
I am also new comer, just try my first flow. Sorry for my checkin.
