### ISSUE TITLE
Remove `engine` package

### ISSUE THREAD

**Issue by LK4D4** [docker/docker#12713]
This one for @runcom

**Comment by runcom** [comment]
:metal:

**Comment by jfrazelle** [comment]
yayyy :)

**Comment by jfrazelle** [comment]
you deserve it!

**Comment by jfrazelle** [comment]
we should remember to close https://github.com/docker/docker/issues/12151 as well

/me feels like the issue police haha

**Comment by runcom** [comment]
sure :cop:
