### ISSUE TITLE
Change/feature req: Tag only requested tags in pull by default

### ISSUE THREAD

**Issue by tvierling** [docker/docker#12721]
(Docker 1.4.1 in use here, but this has been true for a while)

Currently, pulling an image by tag pulls in a lot of extra tags which, in most cases, result in stale images sitting around for no good reason. For instance, pulling `ubuntu:14.04` produces all of the following locally:

```
ubuntu                  trusty-20150320     b7cf8f0d9e82        2 days ago          188.3 MB
ubuntu                  14.04.2             b7cf8f0d9e82        2 days ago          188.3 MB
ubuntu                  14.04               b7cf8f0d9e82        2 days ago          188.3 MB
ubuntu                  latest              b7cf8f0d9e82        2 days ago          188.3 MB
ubuntu                  trusty              b7cf8f0d9e82        2 days ago          188.3 MB
```

But I only asked for `ubuntu:14.04`. When the image gets rebuilt and there's a new trusty-DATESTAMP tag, the old one is going to sit there doing nothing ~forever. Similarly when 14.04.3 is released, the 14.04.2 tag will linger there ~forever. They have to be manually untagged with `docker rmi` to purge them.

If I'm asking for something like `ubuntu:latest` or `ubuntu:trusty` or `ubuntu:14.04`, I want only that tag, because the next time I run `docker build` or `docker run` with it, I want the latest available image version for that tag. I don't want images that I no longer use sitting around chewing up space.

The default behavior of `docker pull` (and the `FROM` Dockerfile directive) should be to get only the specific requested tag. If there's an additional option to `pull` to grab all equivalent tags, great, but that leaves garbage sitting around if it's not specifically the desired behavior.

**Comment by jfrazelle** [comment]
This was fixed in 1.6
