### ISSUE TITLE
Daemon fails to parse config lines ending with a comment

### ISSUE THREAD

**Issue by noteed** [docker/docker#12736]
With a config file that contains a line like this:

    DOCKER_OPTS="--dns xxx.xxx.xxx.xxx --dns 8.8.8.8 --dns 8.8.4.4" # For xxx

The docker daemon will complain like this:

    Apr 24 09:32:55 localhost docker[4110]: invalid value "8.8.4.4#" for flag --dns: 8.8.4.4# is not an ip address

```
> docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.3.3
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.3.3
Git commit (server): a8a31ef
```

**Comment by jfrazelle** [comment]
This is because the configure file is only for environment variables not to mention this has only to do with your init system, this is not a docker bug sorry

**Comment by noteed** [comment]
Thanks..
