### ISSUE TITLE
Malformed -v output gives misguiding message

### ISSUE THREAD

**Issue by MakersF** [docker/docker#12747]
I was writing a script to run an image, but an environment variable was misspelled (so it evaluated to empty string) and I was getting a really misguiding error message, which really made me lose a lot of time.

It boils down to
`docker run --rm -v :/var/ ubuntu echo "echo"`
returning 
>Unable to find image 'ubuntu:latest' locally
latest: Pulling from ubuntu
706766fe1019: Already exists 
a62a42e77c9c: Already exists 
2c014f14d3d9: Already exists 
b7cf8f0d9e82: Already exists 
Digest: sha256:80d996c3693d792505039a3612cf9221ae9704317ea11fda75c86ede672ee1b3
Status: Image is up to date for ubuntu:latest
FATA[0005] Error response from daemon: No such image: ubuntu (tag: latest) 

with `docker images` showing
>REPOSITORY                     TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
ubuntu                         latest              b7cf8f0d9e82        2 days ago          188.3 MB
ubuntu                         14.04               d0955f21bf24        5 weeks ago         188.3 MB

It might be useful to check for the -v parameters and catch this kind of error, as the message is pointing out something different (I lost quite some time to try and figure out why docker wasn't finding the image. I was working with an image I built locally so I was even more confused by 

>Unable to find image 'makersf/php-apache-pg:latest' locally
Pulling repository makersf/php-apache-pg
FATA[0002] Error: image makersf/php-apache-pg:latest not found

**Comment by cpuguy83** [comment]
Thanks, this is really a dup of #11646
