### ISSUE TITLE
container can't exit

### ISSUE THREAD

**Issue by himcc** [docker/docker#12740]
OS:centos
docker version:1.5.0 build a8a31ef/1.5.0
image id: b7cf8f0d9e82

docker run -t -i ubuntu /bin/bash
then run
exit(no response,and CPU 100%)

**Comment by jfrazelle** [comment]
we need more info like the full output of docker version, docker info, uname -a

**Comment by himcc** [comment]
docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.3.3
Git commit (client): a8a31ef/1.5.0
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.3.3
Git commit (server): a8a31ef/1.5.0


docker info
Containers: 3
Images: 3
Storage Driver: devicemapper
 Pool Name: docker-8:1-918134-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 575.7 MB
 Data Space Total: 107.4 GB
 Metadata Space Used: 1.044 MB
 Metadata Space Total: 2.147 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: native-0.2
Kernel Version: 2.6.32-431.29.2.el6.x86_64
Operating System: <unknown>
CPUs: 1
Total Memory: 490.5 MiB
Name: i-sp8iynqq
ID: 4B52:2A2V:6O3U:ULE4:2PVD:NZUU:3VKK:GMMY:NTRC:FHOH:2I4L:PZGR


uname -a
Linux i-sp8iynqq 2.6.32-431.29.2.el6.x86_64 #1 SMP Tue Sep 9 21:36:05 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux


docker image  ubuntu14.04(b7cf8f0d9e82)  coentos7(fd44297e2ddb)

**Comment by visualphoenix** [comment]
This looks like an issue running docker on rhel/centos 6.5 kernel. I've had problems using docker with anything older than the 6.6 kernel. Please try using https://kojipkgs.fedoraproject.org/packages/docker-io/1.6.0/1.el6/x86_64/docker-io-1.6.0-1.el6.x86_64.rpm on Centos 6.6 host with the 6.6 kernel.

**Comment by thaJeztah** [comment]
We very recently raised the version (6.5 -> 6.6) and kernel requirements for RHEL/CentOS (see https://github.com/docker/docker/pull/12814) because of various issues.

@himcc are you able to check on an updated system?

**Comment by himcc** [comment]
It is OK running on centos6.6.
But,is there a way to run on centos6.5 with rhel/centos 6.5 kernel?

**Comment by visualphoenix** [comment]
Use docker 1.4.1 or older. Docker 1.5 on centos 6.5 with 6.5 kernel is buggy and prone to crashing the kernel in some instances.

**Comment by himcc** [comment]
Thank you very much !

**Comment by visualphoenix** [comment]
You should close this issue now :)

**Comment by thaJeztah** [comment]
Thanks @visualphoenix @himcc, good to hear you were able to resolve this!
