### ISSUE TITLE
assign a illegel ip to container,  IPAdress-172.17.0.255

### ISSUE THREAD

**Issue by hujb2000** [docker/docker#12746]
NetworkSettings": {
        "Bridge": "docker0",
        "Gateway": "172.17.42.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "172.17.0.255",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "fe80::42:acff:fe11:ff",
        "LinkLocalIPv6PrefixLen": 64,
        "MacAddress": "02:42:ac:11:00:ff",
        "PortMapping": null,
        "Ports": {
            "4001/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "4001"
                }
            ]
        }
    },

**Comment by phemmer** [comment]
If you're trying to say docker let you assign a supposedly invalid IP address (`172.17.0.255`) to a container: `172.17.0.255` is not an invalid IP address. Your subnet is `172.17.0.0/16`, this gives you the addresses `172.17.0.1`-`172.17.255.254`. Thus `172.17.0.255` is a perfectly valid IP in that range.

**Comment by unclejack** [comment]
Closing as this issue is invalid.
