### ISSUE TITLE
Feature for wildcard workdir

### ISSUE THREAD

**Issue by joowh85** [docker/docker#12742]
I need this feature.

RUN tar zxvf tomcat-native.tar.gz
WORKDIR ${JIRA_INSTALL}/bin/${ls -al | grep tomcat-native}

**Comment by jfrazelle** [comment]
There are a few ways to do this without, most notably tar has a
--strip-components flag see
https://github.com/docker/docker/blob/master/Dockerfile#L68

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.
