### ISSUE TITLE
Enhancement: Add support for COPY and ADD-like methods to the remote api

### ISSUE THREAD

**Issue by termie** [docker/docker#12757]
At current we can get files directly from the container, but we cannot add files directly to the container.

Most of the related code for COPY and ADD is https://github.com/docker/docker/blob/master/builder/internals.go#L124 and https://github.com/docker/docker/blob/master/builder/internals.go#L644

I suspect an "inject file" method would be significantly easier as it wouldn't have to deal with symlinks or file system semantics on the source end.

**Comment by cpuguy83** [comment]
Hi, this is already proposed (and implemented) here: #10198

Closing this one.
Thanks!

**Comment by termie** [comment]
yeyyy
