### ISSUE TITLE
Intermittent devicemapper error when building images

### ISSUE THREAD

**Issue by msabramo** [docker/docker#12750]
Sometimes when I do `docker build`, I get this error:

```
INFO[0000] Error getting container 
b26beb3a69f3ba809c57431206def5272db0e2b9d0326682682d6917d1fdf91c 
from driver devicemapper: open 
/dev/mapper/docker-253:1-135656-b26beb3a69f3ba809c57431206def5272db0e2b9d0326682682d6917d1fdf91c:
no such file or directory
```

I sometimes have to retry a few times before it works again.

```
monkey@marca-teamcity-agent:~/profileweb$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty

monkey@marca-teamcity-agent:~/profileweb$ docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64
```

**Comment by cpuguy83** [comment]
Can you do an output of `docker info`?

**Comment by msabramo** [comment]
Ah it just happened again, this time while trying to start a container.

```
vagrant@vagrant-ubuntu-trusty-64:~$ docker run --name=cassandra -d -v /srv/cassandra:/data tobert/cassandra
Unable to find image 'tobert/cassandra:latest' locally
Pulling repository tobert/cassandra
e8835ec87d3b: Download complete
511136ea3c5a: Download complete
3b363fd9d7da: Download complete
607c5d1cca71: Download complete
f62feddc05dc: Download complete
8eaa4ff06b53: Download complete
ce3d2134d66d: Download complete
5151d5e9a964: Download complete
2dc972f3e67b: Download complete
821f8a3bef56: Download complete
8bedd5accbc8: Download complete
6d334a6ad1a8: Download complete
88e955cf60d5: Download complete
527b42aa784c: Download complete
2c3f05e2181e: Download complete
228b6977f6a5: Download complete
c5c7377fdfef: Download complete
04648b2ae8a8: Download complete
Status: Downloaded newer image for tobert/cassandra:latest
a66e794ef34aab74b19961eb6ac0bc08576f43bb01a3f982c2aaa8fa4b354107
FATA[0125] Error response from daemon: Cannot start container a66e794ef34aab74b19961eb6ac0bc08576f43bb01a3f982c2aaa8fa4b354107: Error getting container a66e794ef34aab74b19961eb6ac0bc08576f43bb01a3f982c2aaa8fa4b354107 from driver devicemapper: Error mounting '/dev/mapper/docker-8:1-393218-a66e794ef34aab74b19961eb6ac0bc08576f43bb01a3f982c2aaa8fa4b354107' on '/var/lib/docker/devicemapper/mnt/a66e794ef34aab74b19961eb6ac0bc08576f43bb01a3f982c2aaa8fa4b354107': no such file or directory
vagrant@vagrant-ubuntu-trusty-64:~$ docker info
Containers: 5
Images: 68
Storage Driver: devicemapper
 Pool Name: docker-8:1-393218-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.625 GB
 Data Space Total: 107.4 GB
 Data Space Available: 37.49 GB
 Metadata Space Used: 4.248 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.143 GB
 Udev Sync Supported: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.13.0-45-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 2
Total Memory: 1.955 GiB
Name: vagrant-ubuntu-trusty-64
ID: 34NK:BX2U:BF3U:JFCU:3WZ2:7B3M:YVID:IBVK:7JSI:U3LY:U35U:E3SO
WARNING: No swap limit support
```

**Comment by cpuguy83** [comment]
Since you're using devicemapper, you should use a dyn binary instead of the statically compiled one.
In the `kernel info` you can see "udev sync supported: false", this is because you are using the statically compiled binary... and without udev sync devicemapper is completely unreliable... to the point where in 1.6 docker even refuses to start unless you pass in a special flag when udev sync is not supported.

**Comment by msabramo** [comment]
@cpuguy83: Thanks for investigating and taking he time to comment! To be honest, I don't think I have enough kernel/lxc/docker knowledge to understand, but I appreciate you taking the time to explain :-) and maybe if I do a bit of research and then come back to this it will make more sense to me. FWIW, I installed Docker by using this ansible module - https://github.com/angstwad/docker.ubuntu - I wonder if it's doing something wrong in the way it installs Docker? Perhaps you might want to file an issue if it's doing something wrong, as that might reduce the number of issues like this one?

**Comment by msabramo** [comment]
By the way, this was with docker 1.6 (I think; certainly the first time it was, though that was a different system) and it didn't seem to prevent me from starting it.

**Comment by cpuguy83** [comment]
It may not have made it into 1.6, but is in master.

Unfortunately the supported way to install Docker is from our repo, which uses the statically compiled binary, which breaks devicemapper.
I would suggest using either aufs (just need to install the kernel-extras package) or overlayfs.

**Comment by msabramo** [comment]
@angstwad: Do you think that the `angstwad.docker_ubuntu` ansible role should install the `kernel-extras` package to avoid this problem?

**Comment by angstwad** [comment]
@msabramo I've updated the role so this can be overridden with a variable, `install_kernel_extras`.

**Comment by msabramo** [comment]
Thanks, @angstwad !
