### ISSUE TITLE
Environment variables with an equals sign are not available in linked containers

### ISSUE THREAD

**Issue by squarejaw** [docker/docker#12763]
I'm trying to access an environment variable containing an equals sign in a linked container.

Example:
```
$ docker run -i -t --rm --name foo -e "FOO=BAR" -e "BAZ=QUX=QUUX" ubuntu /bin/bash 
root@073ecccb5a67:/# echo $FOO
BAR
root@073ecccb5a67:/# echo $BAZ
QUX=QUUX
```
Here is the result when I create a linked container in a separate terminal:
```
$ docker run -i -t --link foo:foo ubuntu /bin/bash
root@6f8edb5fbf66:/# echo $FOO_ENV_FOO
BAR
root@6f8edb5fbf66:/# echo $FOO_ENV_BAZ

root@6f8edb5fbf66:/# 
```
Am I missing some special handling for the equals sign?

**Comment by duglin** [comment]
interesting - i can reproduce this... will try to take a look at it....

**Comment by duglin** [comment]
should have a fix soon- I see it

**Comment by duglin** [comment]
PR #12783 fixes this

**Comment by squarejaw** [comment]
Thanks for the quick turnaround! :+1:

**Comment by duglin** [comment]
pr #12783 is merged despite a bug in github. so closing this issue.
