### ISSUE TITLE
Docker build fails with error: standard in must be a tty

### ISSUE THREAD

**Issue by pravinchikhale** [docker/docker#12761]
Docker Version:

Containers: 5
Images: 39
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 49
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.18.11-tinycore64
Operating System: Boot2Docker 1.6.0 (TCL 5.4); master : a270c71 - Thu Apr 16 19:50:36 UTC 2015
CPUs: 4
Total Memory: 1.961 GiB
Name: boot2docker
ID: LXQP:OL65:KPVE:L5AT:HLYN:LVK6:Q2QU:HWQW:KN5K:U7R2:HORC:ODHA
Debug mode (server): true
Debug mode (client): false
Fds: 12
Goroutines: 16
System Time: Fri Apr 24 18:25:08 UTC 2015
EventsListeners: 0
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker

**Comment by cpuguy83** [comment]
Can you provide some more information? What are you trying to build? What command did you use, etc?

**Comment by pravinchikhale** [comment]
Hi, I was trying to install Oracle Endeca setup on centos 6. After googling for one last time i found USER command, previous to that i was using su - <user-name> format while doing setup.

Issue is resolved now. :)
