### ISSUE TITLE
Docker container with attached volume won't start after reboot

### ISSUE THREAD

**Issue by webanck** [docker/docker#12776]
Hello,

I encounter some problems with volumes after rebooting.
I start a container with
```
sudo docker run -ti \
	-e DISPLAY \
	-v /tmp/.X11-unix:/tmp/.X11-unix:ro \
	-v ~/.Xauthority:/home/wine/.Xauthority \
	-v /dev/snd:/dev/snd --privileged \
	-v /run/user/`id -u`/pulse/native:/run/user/`id -u`/pulse/native \
	--net=host \
	webanck/docker-wine-steam
```
Then I stop the xxxx container and am perfectly able to restart it doing:
```
sudo docker start xxxx && sudo docker attach xxxx
```
But when I reboot my computer and try the same as above to restart my container I always get the same error:
```
Error response from daemon: Cannot start container xxxx: setup mount namespace mounting /run/user/1001/pulse/native into /var/lib/docker/aufs/mnt/9b2641d21b7895bded8b0783d3e69aae75f167412f8a4e6f69308d54590111bc/run/user/1001/pulse/native not a directory
FATA[0000] Error: failed to start one or more containers
```

Any idea of what I am doing wrong? Or is it a problem with docker itself?

PS: for more information on the image I am using, see my repository [docker-wine-steam](https://github.com/webanck/docker-wine-steam).

**Comment by cpuguy83** [comment]
Looks like you're trying to mount a dir onto a file.

**Comment by webanck** [comment]
@cpuguy83 Thanks for the answer but how could it be? It is a directory as far as I am being told be the `ls` command.

**Comment by webanck** [comment]
Up!
Anyone has any idea?

**Comment by calavera** [comment]
Can you please send the output of `docker info` and `uname -a`? I just tried with docker 1.6.2 and it seems to work, but I might be missing something.

**Comment by webanck** [comment]
Ok here it is:
```
Containers: 1
Images: 18
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 20
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.16.0-30-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 8
Total Memory: 15.58 GiB
Name: <name>
ID: <XXX>
WARNING: No swap limit support
```

```
Linux <name> 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by cpuguy83** [comment]
@webanck Inside the container you have a file, outside the container docker is trying to create a dir since no file exists at the path.
This is likely because the real path is actually changing.
Have you tried this with Docker 1.7 or 1.8?
