### ISSUE TITLE
 Docker --device CMD add support ':' in the host path

### ISSUE THREAD

**Issue by chenwin** [docker/docker#12778]
The --device=/dev/sdc:/dev/xvdc:rwm use ':' to split the devices to path_on_host and path_in_container, but the ':' is often using in the path, such as '/dev/block/253:0' in the following:
[root@localhost by-path]# cd /dev/block/
[root@localhost block]# ls
253:0  253:1  253:2  253:3  253:4  253:5  253:6  253:7  7:0  7:1  7:2  7:3  8:0  8:1  8:16  8:2

For example:--device=/dev/block/253:0:/dev/xvdc:rwm
This makes the path_on_host('/dev/block/253') and the path_in_container('0') unexpected, In fact
we want the path_on_host is '/dev/block/253:0' and the path_in_container is '/dev/xvdc'
thus it is better use another character(such as '$') instead of ':' to split.

https://github.com/docker/docker-py/blob/master/docker/utils/utils.py#L267

**Comment by coolljt0725** [comment]
I think we should use `:/` to split

**Comment by TheDong** [comment]
@coolljt0725 How does `:/` help with the issue? `:` can be the last character in an identifier easily enough. `/dev/folder:/device` is a perfectly valid path.

This can be solved by using invalid path characters (e.g. `$` as @chenwin suggests), decomposing the parts (offer `--device-hostpath=` and `--device-containerpath=`), or by allowing escaping rules (`--device=/dev/folder\:/device:/path/in/container\:/with\:colons`).

Suggesting the use of characters that are valid within paths as a delimiter between paths does *nothing* to improve the situation and is what causes this issue in the first place.

Although allowing decomposing the path (adding new flags) is a little messy, it's also the most backwards compatible option and seems quite reasonable to me. Allowing escaping of the delimiter is also backwards compatible, but non-obvious.

**Comment by runcom** [comment]
IMO I think introducing escaping sequence (such as `\:`) is much better than introducing two new flags it might not be so obvious but much better than introducing two new flags.

**Comment by runcom** [comment]
ping @duglin @LK4D4 would hear something from you also :) I think allowing colons in path is good since even in volumes I can mount a file which contains colons..

**Comment by cpuguy83** [comment]
Having escapes on the CLI won't help because the shell will consume them.

**Comment by runcom** [comment]
yup the string would be put inside quotes also

**Comment by duglin** [comment]
Where are we on this? I seem to recall some discussions (and work) going on for better detection of window's paths vs random colons in paths so perhaps this isn't an issue any more?  ping @jhowardmsft

**Comment by jhowardmsft** [comment]
Ask me in a week - on vacation :)

**Comment by duglin** [comment]
@jhowardmsft ping

**Comment by jhowardmsft** [comment]
@duglin - What's the actual question? If you're referring to volumes support, we moved the parsing/validation to the daemon. Life would have been significantly better if there were two parameters - one for host path and one for container path, and in the volumes case, not having overloaded the CLI with both volumes and bind mounts.

**Comment by duglin** [comment]
@chenwin with @jhowardmsft's comment about the parsing being done on the daemon-side, is this still an issue?

**Comment by duglin** [comment]
I'm going to assume this one is resolved by the parsing being done on the daemon side. @chenwin if not please reopen it.
