### ISSUE TITLE
Unable to use ^C to stop a running "docker run -ti" session

### ISSUE THREAD

**Issue by icy** [docker/docker#12780]
When `phantomjs-1.9.8` is used as an `init script` as below

    /usr/bin/phantomjs --webdriver=8190 --debug=${PHANTOMJS_DEBUG:-false}

it's impossible to press `^ C` to terminate the command `dock run -ti --rm ...`. Moreover, the `phantomjs`  can't be killed with `SIGTERM`. A `kill -9` must be used.

To reproduce the problem, please use exactly the following Dockefile: https://github.com/icy/docker/releases/tag/phantomjs-1.9.8_bug

````
git clone https://github.com/icy/docker.git
git checkout -b phantomjs_bug phantomjs-1.9.8_bug
docker build -t icy/phantomjs_bug .
docker run -ti --rm icy/phantomjs_bug
# press ^C a thousand times....
````

My docker environment

````
$ docker info
Containers: 2
Images: 335
Storage Driver: devicemapper
 Pool Name: docker-8:4-9437191-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 4.414 GB
 Data Space Total: 107.4 GB
 Data Space Available: 103 GB
 Metadata Space Used: 11.63 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.136 GB
 Udev Sync Supported: true
 Data loop file: /home/locker/data/devicemapper/devicemapper/data
 Metadata loop file: /home/locker/data/devicemapper/devicemapper/metadata
 Library Version: 1.02.93 (2015-01-30)
Execution Driver: native-0.2
Kernel Version: 3.18.6-1-ARCH
Operating System: Arch Linux
CPUs: 4
Total Memory: 3.563 GiB
Name: icy
WARNING: No swap limit support
````

**Comment by Mic92** [comment]
What kind of behavior, you would inspect instead of docker?

**Comment by icy** [comment]
When ^C is pressed, docker should stop (similar to `docker stop foobar`)

**Comment by icy** [comment]
There is a problem with signal handling. Maybe from `phantomjs` (note that `phantomjs` is still fine when it's being used without `docker`), maybe from `docker`. I am not sure it that's a feature or a bug. It's just too annoyed and  have to run `docker => supervisor => phantomjs`. Something mentioned in http://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/

**Comment by Mic92** [comment]
It would be surprising for users, if ^C would do anything but sending SIGTERM.
I think the only solution here would be to add a different key to initiate docker stop.
Systemd-nspawn for example allow to stop containers by using ^] three times in a row.
The reaping problem does not apply here, because phantomjs does not demonize at this point, but just do not react to SIGTERM.

**Comment by coolljt0725** [comment]
you should enter `exit` to stop a running container when use `-t`, `-t` means it was tty mode. If you without `-t` and only `-i`, you can use ^C to stop the running container

**Comment by icy** [comment]
@coolljt0725 Thanks, but ^C doesn't work if I run "docker run -i --rm phantomjs"

@Mic92 `phantomjs` works with ^C (or SIGTERM, if you really like that) if it runs on the host machine. If I run "docker run -ti --rm phantomjs /bin/bash" and start "phantomjs" from the container's container, `phantomjs` is still fine.

Only when `phantomjs` is run as container initsript, the process doesn't accept any signal. I can't see this similar behavior in any other applications.

**Comment by coolljt0725** [comment]
@icy sorry, my bad, I made a mistake , `-i` means `--interactive`, ^C can't stop a container with `-i`

**Comment by Mic92** [comment]
If phantomjs does not run in docker it runs in a shell too, doesn't it? Is this possible related to? https://github.com/ariya/phantomjs/issues/10818

Have you tried to use:

```bash
/usr/bin/phantomjs --webdriver=8190 --debug=${PHANTOMJS_DEBUG:-false}
```

instead of:

```bash
exec /usr/bin/phantomjs --webdriver=8190 --debug=${PHANTOMJS_DEBUG:-false}
```

in your start script

**Comment by icy** [comment]
@Mic92 Yeah that's a great idea. I have tried and that works :) I hadn't thought of that because I tried to follow the Docker idea: only one process / container (FIXME).

I don't know if the problem comes from https://github.com/ariya/phantomjs/issues/10818. It's weird that `phantomjs` just discards system signal when it's running as `container` init.

Anyway, I am using `supervisor` to start my application inside container now. It's a lot easier. So the team can decide what to do next on this ticket. IMHO, using `exec` here but not there is just an annoyed thing.

Thanks a lot for your support, @Mic92  and @coolljt0725

**Comment by thaJeztah** [comment]
Good to hear you managed to get it working.

I'm going to close this issue, because as far as I can tell, Docker is working correctly here, and there's not much we can do if the software running in the container doesn't respond to signals.

**Comment by icy** [comment]
Thank you @thaJeztah . I will ask `phantomjs` team if they have any idea.
