### ISSUE TITLE
System error: mountpoint for cgroup not found

### ISSUE THREAD

**Issue by JendaPlhak** [docker/docker#12785]
I deploy my app using wercker and latest docker 1.6. When docker build gets to command
`RUN mkdir /srv/serverdata` it fails with error message `INFO[0206] [8] System error: mountpoint for cgroup not found`. I am not sure whether this is a bug or I am doing something wrong.

The wercker uses box `box: wercker/ubuntu12.04-webessentials` but I upgrade it to 14.04 before I run the build using this series of commands

          sudo apt-get update
          sudo apt-get install -y update-manager-core
          sudo do-release-upgrade -f DistUpgradeViewNonInteractive -m server -d
          sudo apt-get install -y aptitude
          sudo aptitude update
          sudo aptitude safe-upgrade
          sudo apt-get install -y curl build-essential wget unzip
          sudo mkdir -p /usr/local/bin/ && cd /usr/local/bin && sudo wget https://dl.bintray.com/mitchellh/packer/0.5.2_linux_amd64.zip && sudo unzip 0.5.2_linux_amd64.zip
          curl -L https://www.opscode.com/chef/install.sh | sudo bash

**Comment by Mic92** [comment]
Is cgroups mounted?

```
$ mount | grep cgroup
```

**Comment by thaJeztah** [comment]
I'm going to close this issue because it went without response, and doesn't have enough information to work on, but feel free to comment here if you think I closed this by mistake
