### ISSUE TITLE
Command Examples

### ISSUE THREAD

**Issue by elliot-labs** [docker/docker#12786]
Docker lacks examples for commands. These would be really helpful for understanding the syntax as the --help items are (sometimes) confusing.

Here is an example:
```
docker commit --help

Usage: docker commit [OPTIONS] CONTAINER [REPOSITORY[:TAG]]

Create a new image from a container's changes

  -a, --author=       Author (e.g., "John Hannibal Smith <hannibal@a-team.com>")

  -c, --change=[]     Apply Dockerfile instruction to the created image
  --help=false        Print usage
  -m, --message=      Commit message
  -p, --pause=true    Pause container during commit

Examples:
docker commit syntax goes here
another example
etc...
```
So essentially the idea would be to append an `Examples:` section to the `--help` for each of the commands.

Thanks and keep up the great work!

**Comment by Mic92** [comment]
The man page contains at least one example per command.
For example:

```
$ man docker-attach
EXAMPLES
Attaching to a container
       In this example the top command is run  inside  a  container,  from  an
       image  called  fedora,  in  detached mode. The ID from the container is
       passed into the docker attach command:

              # ID=$(sudo docker run -d fedora /usr/bin/top -b)
              # sudo docker attach $ID
```

**Comment by elliot-labs** [comment]
What happens if you do not have man installed on your minimal computer?

**Comment by pdevine** [comment]
Install man?  I don't think we would want to pollute the --help output with examples;  the help output is supposed to be very lightweight.

**Comment by thaJeztah** [comment]
I don't think this is something we want; docker is a fast moving project and keeping all documentation in sync is already daunting. Adding examples to yet another document will only add to that.

As others mentioned above, installing man should give you what you want. In addition, there's a proposal to add links to the online documentation to the output of `--help` that you might be interested in; https://github.com/docker/docker/issues/13298

I'm personally for closing this, but I'll ping the other docs maintainers to check if I'm not alone in this;

ping @fredlf @jamtur01 @moxiegirl @SvenDowideit wdyt?

**Comment by jamtur01** [comment]
What @thaJeztah said.

**Comment by moxiegirl** [comment]
Docker's command presentation (if you weill) pretty closely matches that of `git` and those commands do include examples. I actually think it is a good idea to include examples.

We are short staffed in documentation as @thaJeztah points out and their are competing suggestions.  If you want to reframe this as a proposal so folks could vote. 

We have to come up with a better way --- expecting people to build man pages seems kind of heavy.  Then, haven't been around long,  I don't know the history behind why we have both man pages and help....maybe someone can fill me in.

**Comment by elliot-labs** [comment]
@moxiegirl How would I reframe the proposal?

**Comment by moxiegirl** [comment]
@elliot-labs You would do this as a PR proposal.  Basically, you'd do as suggested here: http://docs.docker.com/project/advanced-contributing/

You can do this even if you aren't planning on implementing the change yourself.

**Comment by elliot-labs** [comment]
k, thx for the info!

On Tue, May 26, 2015 at 6:26 PM, moxiegirl <notifications@github.com> wrote:

> @elliot-labs <https://github.com/elliot-labs> You would do this as a PR
> proposal. Basically, you'd do as suggested here:
> http://docs.docker.com/project/advanced-contributing/
>
> You can do this even if you aren't planning on implementing the change
> yourself.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/12786#issuecomment-105686742>.
>



-- 
Everybody talks about the weather but they do nothing about it - Mark Twain

Elliot Huffman

DISCLAIMER:
This e-mail is for the intended recipient(s) only

If you have received it by mistake please let me know by reply and then
delete it from your system; access, disclosure, copying, distribution or
reliance on any of it by anyone else is prohibited.

If you as intended recipient have received this e-mail incorrectly, please
notify the sender (via e-mail) immediately.

**Comment by ankushagarwal** [comment]
The docker manpages are distributed with the docker packages for most systems git style. (`man docker-run`) and the `--help` is sufficient for short reference. So I think that this can be closed. @elliot-labs the `man` command can be always be run inside a container 😏

So, can we go ahead and close this issue @thaJeztah @moxiegirl ?

**Comment by thaJeztah** [comment]
I was okay with closing, but given the discussion above, @moxiegirl might not be. Perhaps she had thoughts on how the existing docs can be integrated in `--help`?

**Comment by moxiegirl** [comment]
@thaJeztah IMO @elliot-labs has a great point about the examples and help. At this point, a full sweep to add examples in help seems out of reach for our staffing; and a lot to ask of a contributor. Moving forward, as flags are added to a command, let's also lookt to add a sample to the help.
