### ISSUE TITLE
Restarted Docker daemon hangs when starting previously paused container

### ISSUE THREAD

**Issue by lexandro** [docker/docker#12797]
Description of problem:
Docker daemon stops operating normally when I restart the daemon with a paused container and try to unpause/start the container again.

`docker version`:
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64

`docker info`:
Containers: 1
Images: 62
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 70
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.16.0-34-generic
Operating System: Ubuntu 14.10
CPUs: 4
Total Memory: 31.38 GiB
Name: lexandro-ubuntu
ID: LVT7:77ZC:2YT4:SVLB:UXUA:BJRV:LCOQ:OWEO:KBYK:DF44:WIT3:ECWQ
WARNING: No swap limit support

`uname -a`:
Linux 3.16.0-34-generic #47-Ubuntu SMP Fri Apr 10 18:02:58 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
physical

Steps to Reproduce:
1. docker run -itd --name tester busybox sleep 99999
2. docker pause tester
3. sudo service docker restart
4. docker ps -a (optional :) )
5. docker start tester
6. docker hangs...

Actual Results:
Console hangs, no interaction via CLI or remote API anymore, docker ps is not working, but docker images returns the list.

Expected Results:
Starting the paused/stopped container again, operating normally

**Comment by cpuguy83** [comment]
Yes, I've seen this on master. Killing a daemon that has paused containers seems to do bad things.

**Comment by coolljt0725** [comment]
I've seen this on master too. Restarting docker daemon will lead a paused container can't be start, I think we should unpause the paused containers on daemon shutdown,

**Comment by lexandro** [comment]
Not fixed yet, your merge request closed without merging :(

**Comment by thaJeztah** [comment]
I see there's a new PR crested here: https://github.com/docker/docker/pull/13304

**Comment by coolljt0725** [comment]
@thaJeztah  Yes, #13304  is going to fix this issue

**Comment by cpuguy83** [comment]
Closing as this is fixed.
