### ISSUE TITLE
Feature request: exporting iptables rules

### ISSUE THREAD

**Issue by icy** [docker/docker#12791]
By default, `docker` executes `iptables` command to alter system firewall rules.  This is fine as long as the host system hasn't any automatic way to handle firewall. 

If the host system has their own firewall deployment (puppet, chef, automation tools,...), then Docker just creates a mess. Especially, if the firewall is reset/flushed after a period (this is true on my systems), all Docker rules are gone away. The only way to make running containers alive is to restart them. Sometimes, Docker can't start new container because some base rules are missing (e.g, when `nat/DOCKER` was removed.)

Now I have to deploy an in-house tool to generate firewall (*NAT*) rules from containers's information; we also have to use `iptables=false`. Instead of reinventing the wheel, I suggest Docker to have an ability to export their `iptables` commands so `sysadmin` can use the rules any time they want.

Example

````
$ docker run -p 1234:1234 --name foo bar
$ docker inspect --format "{{.iptables.}}" foo 
iptables -t nat bla bla
iptables -t nat bla bla ...
````

**Comment by phemmer** [comment]
While I would argue that the change should be in your management tools to not wipe docker's rules, your request can already be done.

```
mkdir -p /usr/local/bin/docker/

cat > /usr/local/bin/docker/iptables <<'EOF'
#!/bin/sh
echo iptables "$@" >> /tmp/iptables.sh
exec /sbin/iptables "$@"
EOF

chmod a+x /usr/local/bin/docker/iptables

PATH="/usr/local/bin/docker:$PATH" docker -d
```

This will give you a file at `/tmp/iptables.sh` with all the iptables commands needed to recreate the current state.

**Comment by Mic92** [comment]
@phemmer, possible dangerous if one restart docker, as the script does only append.

I think having templates to generate iptables scripts would be a useful feature here.
This would allow more fine grained for admins by editing these and also allow to support other firewalls such as nftables or even ipfw (if freebsd is supported someday), without having to write a single line go.

**Comment by icy** [comment]
@phemmer That's very interesting trick. Some kind of `LD_PRELOAD` for scripting ;) I think that's very useful. The *append-only* issue as @Mic92 mentioned can be avoided by a simple tuning.

The problem is this way force us to `PRELOAD` for every use of `docker` command (and the best way is to replace `/usr/bin/docker` by a wrapper IMHO; -- in case some guy in your team to use `PRELOAD` feature.) It also requires you to have a good naming scheme to manage the bunch of generate scripts (unless you just have some one-shot tasks.) This is because containers' naming is very dynamic (random name, human-readable name, container ID). That's another kind of problem (what is this script for? what script is for this container?). I am not very sure if that's worth resolving that kind of problem; while there is possibly a simple way to do all stuff by slightly modifyting the `Exec` command from

https://github.com/docker/docker/blob/master/pkg/iptables/iptables.go#L264

(Yeah, I have to learn `Go` now!)

**Comment by icy** [comment]
Forgot to mention: I also have system whose out-going traffic is blocked by default. New `docker` rules on this system just doesn't work unless a small hook is invoked after `docker run` is complete. Basically, `docker` can't do everything on host machine so it's useful if sysadmin knows that `docker` needs.

**Comment by icy** [comment]
A #bash script to generate NAT rules for all running containers (NOTE: for NAT-network only) https://github.com/icy/hsabymho/blob/master/libs/docker.sh

**Comment by thaJeztah** [comment]
@mrjana @mavenugo any thoughts on this one?

**Comment by LK4D4** [comment]
I think it's too much for docker to do it. iptables is an implementation detail. I understand desire to have more control over it, but it would be not easy for us to maintain that feature.

**Comment by dansan** [comment]
I think this is to easily dismissing a vital security problem for system administrators and Linux distribution maintainers.

The simplest (and trivial to support) feature would be to create a configuration variable that can optionally be used to set the path to the iptables executable. That would allow Linux distributions to use their own means to set iptables rules (without phemmers workaround).

Better would be to call a program/script with a simple cmdline syntax ("API") to generate the rules (something like icys script), instead of generating them inside the docker engine.

Then this can be adapted by distributions to for example work with nftables - or are you planning to support nftables alongside iptables inside the docker engine?

**Comment by justincormack** [comment]
You can just set the PATH to override the iptables binary if you want, just
out the location of an alternate binary first.

**Comment by icy** [comment]
Then the question is which `iptables` binary is being used...

**Comment by dansan** [comment]
> You can just set the PATH to override the iptables binary if you want, just
> out the location of an alternate binary first.
Ofc that's possible - but that's a workaround, not an interface.
