### ISSUE TITLE
Unable to create redis cluster(redis3.0) on different docker containers(with 6 different Host IP's) 

### ISSUE THREAD

**Issue by Pratap6** [docker/docker#12805]
Hi,
I'm trying to create redis cluster(redis 3.0) on six docker containers for that I have created 6 redis docker images on different Hosts, And running , exposed with different public ports for each docker image on host machine.

After that when I'm trying to create redis cluster with 6 redis docker containers , I'm getting below error. 
The below command I'm running at another host machine:

 root@Plex-3010:/usr/share/Redis-3.0/redis-3.0.0/src# ./redis-trib.rb create --replicas 1 100.1.1.2:6379 100.1.1.1:6379 100.1.1.3:6379 100.1.1.4:6379 100.1.1.5:6379 100.1.1.6:6379
>>> Creating cluster
Connecting to node 100.1.1.2:6379: OK
Connecting to node 100.1.1.1:6379: OK
Connecting to node 100.1.1.3:6379: OK
Connecting to node 100.1.1.4:6379: OK
Connecting to node 100.1.1.5:6379: OK
Connecting to node 100.1.1.6:6379: OK
>>> Performing hash slots allocation on 6 nodes...
Using 3 masters:
100.1.1.2:6379
100.1.1.1:6379
100.1.1.3:6379
Adding replica 100.1.1.4:6379 to 100.1.1.2:6379
Adding replica 100.1.1.5:6379 to 100.1.1.1:6379
Adding replica 100.1.1.6:6379 to 100.1.1.3:6379
M: 4fa96e3c1b96647fdad56865e50d1e49e027965f 100.1.1.2:6379
   slots:0-5460 (5461 slots) master
M: cd418ea6381dc01da1f64a31aa567014b9062c79 100.1.1.1:6379
   slots:5461-10922 (5462 slots) master
M: e226b6228dc17cf252b74c074eda47ae9ece93bd 100.1.1.3:6379
   slots:10923-16383 (5461 slots) master
S: 4ed9135aba97aa8e329bfb53d1ee679c710e8280 100.1.1.4:6379
   replicates 4fa96e3c1b96647fdad56865e50d1e49e027965f
S: 7a40d774d36640bfb05bb53da07f197290d02eb3 100.1.1.5:6379
   replicates cd418ea6381dc01da1f64a31aa567014b9062c79
S: 28f18d451fc924ba52748094fc6a5ba82798a3d0 100.1.1.6:6379
   replicates e226b6228dc17cf252b74c074eda47ae9ece93bd
Can I set the above configuration? (type 'yes' to accept): yes
>>> Nodes configuration updated
>>> Assign a different config epoch to each node
>>> Sending CLUSTER MEET messages to join the cluster
Waiting for the cluster to join....................................................................................................................................................................................................................../var/lib/gems/1.9.1/gems/redis-3.2.1/lib/redis/client.rb:331:in `rescue in establish_connection': Error connecting to Redis on 100.1.1.2:6379 (Errno::ECONNREFUSED) (Redis::CannotConnectError)
        from /var/lib/gems/1.9.1/gems/redis-3.2.1/lib/redis/client.rb:317:in `establish_connection'
        from /var/lib/gems/1.9.1/gems/redis-3.2.1/lib/redis/client.rb:94:in `block in connect'
        from /var/lib/gems/1.9.1/gems/redis-3.2.1/lib/redis/client.rb:279:in `with_reconnect'
        from /var/lib/gems/1.9.1/gems/redis-3.2.1/lib/redis/client.rb:93:in `connect'
        from /var/lib/gems/1.9.1/gems/redis-3.2.1/lib/redis/client.rb:350:in `ensure_connected'
        from /var/lib/gems/1.9.1/gems/redis-3.2.1/lib/redis/client.rb:207:in `block in process'
        from /var/lib/gems/1.9.1/gems/redis-3.2.1/lib/redis/client.rb:292:in `logging'
        from /var/lib/gems/1.9.1/gems/redis-3.2.1/lib/redis/client.rb:206:in `process'
        from /var/lib/gems/1.9.1/gems/redis-3.2.1/lib/redis/client.rb:112:in `call'
        from /var/lib/gems/1.9.1/gems/redis-3.2.1/lib/redis.rb:2556:in `block in method_missing'
        from /var/lib/gems/1.9.1/gems/redis-3.2.1/lib/redis.rb:37:in `block in synchronize'
        from /usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
        from /var/lib/gems/1.9.1/gems/redis-3.2.1/lib/redis.rb:37:in `synchronize'
        from /var/lib/gems/1.9.1/gems/redis-3.2.1/lib/redis.rb:2555:in `method_missing'
        from ./redis-trib.rb:264:in `get_config_signature'
        from ./redis-trib.rb:524:in `block in is_config_consistent?'
        from ./redis-trib.rb:523:in `each'
        from ./redis-trib.rb:523:in `is_config_consistent?'
        from ./redis-trib.rb:531:in `wait_cluster_join'
        from ./redis-trib.rb:1007:in `create_cluster_cmd'
        from ./redis-trib.rb:1373:in `<main>'

Thanks!.

**Comment by cpuguy83** [comment]
Are you able to connect to it from the redis-cli?

**Comment by thaJeztah** [comment]
@Pratap6 I'm going to close this issue, because we need more information, but comment here with additional information, and I'll reopen. Thanks!
