### ISSUE TITLE
Port bindings through API 1.18

### ISSUE THREAD

**Issue by alessioguglielmo** [docker/docker#12816]
Hi,

I have a problem with port mapping when I create containers. 
If I want to map x container port to y host port (on 0.0.0.0), I usually insert ExposedPort and PortBindings in creation REST request, but it doesn't work correctly when I start it. It only map container port, not host port.

Documentation isn't clear about starting... seems there aren't any parameters to specify during starting.

Thanks for help
B.R.

Alessio

**Comment by cpuguy83** [comment]
Start can take anything that's in `HostConfig` in create.
There should be no change between prior docker versions and 1.18 API.

Can you provide what your sending, what's the container struct looks like after, and what you're expecting to see?

**Comment by alessioguglielmo** [comment]
Ok
I run create call:
```
{"Memory":"100000000","MemorySwap":"0","CpuShares":"1","ExposedPorts":{"9000\/tcp":[]},"Cmd":["node","server.js","-p","8180","-l","0.0.0.0","--auth","admin:admin_dblablblablae1","-w","\/root"], "HostConfig": {       
           "PortBindings": { "8180/tcp": [{ "HostPort": "9000" }] } ,"AttachStdin":"false","Image":"containerx"} 
```

Then I run start simply by

```
https://10.xxx.79.xxx:2376/containers/4b91731e3bf938320bbca3cedc1a1c4d9d21fc47ea24121be8fa0b0f5fba00c5/start 
```

All run correctly, service is up, but I can't access to the service using public ip (firewall is set, when I run command with -p 9000:8180 the server replies fine)

I've tried more and more... also without exposedports early, but with poor results. Sure is a stupid problem

**Comment by cpuguy83** [comment]
Couple of things, is the escape in `ExposedPorts` supposed to be there?
Also, `ExposedPorts` should be the container port not the host port.

**Comment by alessioguglielmo** [comment]
so
HostPort is encoded within PHP call, in the original form:
```
json_encode( array( "PortBindings"=> array( '8180/tcp'=> array( array( "HostPort"=> "9000" ) ) ) ) );
```

**Comment by alessioguglielmo** [comment]
Corrected container port instead of host port. Seems it work fine. Tomorrow I'll verify!

**Comment by runcom** [comment]
Also php `json_encode

**Comment by alessioguglielmo** [comment]
Yes I did, was a simple problem in mapping host-to-container. Thanks! ;)
