### ISSUE TITLE
Uninstallation of docker not documented

### ISSUE THREAD

**Issue by dradetsky** [docker/docker#12824]
I was going to install the latest docker via 

`wget -qO- https://get.docker.com/ | sh`

However, uninstalling after doing so is not documented.

1. It should be. 
2. I should be able to find it in the docs by searching for 'uninstall'.
3. The documentation ought to say that the solution is "run the command `sudo docker uninstall`" or something along those lines.

**Comment by cpuguy83** [comment]
Agreed, it should be documented if it's not already, but also one should read through the install script before running and it's pretty easy to tell how to remove it.

**Comment by dradetsky** [comment]
Assuming this is true (reading now), just adding "Uninstall: not currently documented, but by reading the install script you can probably figure it out" would at least be a step in the right direction. For one thing, it tells me to stop looking for proper documentation.

**Comment by kostickm** [comment]
#dibs
