### ISSUE TITLE
 Cannot start some containers after restarting docker daemon (=> #6675) 

### ISSUE THREAD

**Issue by blankenhaus** [docker/docker#12832]
This is in reference to #6675.  Please take a look at my comment at the very end.  This is still an issue 
with docker v1.6 and the device mapper storage driver.

**Comment by blankenhaus** [comment]
Tested this with aufs and my test scenario works just fine.

**Comment by jmakanjuola** [comment]
In reference to #6675 here is short fix:

Step1: 
docker start CONTAINER_ID  
Step2:
docker attach CONTAINER_ID 

This should bring the container.

**Comment by cpuguy83** [comment]
Just to confirm, this is happening with devicemapper?
Can you paste your `docker info` and `docker version`?
Does this still happen on docker 1.7 with a properly configured system? (i.e., udev sync must be supported)

**Comment by cpuguy83** [comment]
Closing for now due to no response.
If you can provide the requested info and repro steps please ping here so we an take a look.
Thanks!
