### ISSUE TITLE
Add CMD_DAEMON or some option for running non-terminating daemonized containers

### ISSUE THREAD

**Issue by JonasT** [docker/docker#12836]
I was recently fiddling around with a container. Basically, I had the issue with this container immediately terminating (docker container gives "job done" and it stops again gracefully) a second after I start it:
```
FROM ubuntu

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y nginx

CMD service nginx start
```
Of course I found out after not much googling that the container terminates because the command is designed to be non-blocking. Alright, then why not launch nginx directly:
```
FROM ubuntu

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y nginx

CMD nginx
```
Well it turns out that nginx *always* daemonizes.

At this point I wanted to try sleep infinity but then found out via google that it doesn't actually sleep forever apparently, just very long. I googled further to find various hacks like "tail -f /dev/null/".

And while googling around, I noticed that this is all a **huge waste of time**.

Docker should really just add a CMD_DAEMONIZE or CMD_WAITFOREVER or some "docker run" command line option which is usable from a docker-compose.yml that prevents a container from quitting after the main command has run. Why should I be googling half an hour just to make the command not terminate when that's such an obvious requirement?

**Comment by LK4D4** [comment]
@JonasT I believe there is sleep infinity in ubuntu. Also you can take a look at official Dockerfile of nginx:
https://github.com/nginxinc/docker-nginx/blob/abd253dde5d627b151cd737ce953d6d01e6fdf4c/Dockerfile
It is actually very easy to make it non-daemonized.

**Comment by JonasT** [comment]
Yes it is, if you know how. But the man page of nginx ain't obviously telling. Also as I wrote it appears "sleep infinity" doesn't actually sleep forever in some implementations but only very long.

And this doesn't address this sort of problem in general. It would be much more straightforward to simply specify in the Dockerfile or as some sort of option to "docker run" that I want this daemonized no matter what, instead of googling for a while how to make nginx not-daemonized or all those nasty bash hacks.

**Comment by JonasT** [comment]
I mean I can kind of understand the benefit of nginx running non-daemonized, since that will make a crash more obvious when the container goes down as a result. However, some apps might not run non-daemonized, or like nginx not in an immediately obvious way.

And all those bash hacks? Common, that's just a stupid way to work around the obvious limitation of specifying this in the Dockerfile properly. And if what I read about "sleep infinity" is actually true, then it's also an invitation for additional trouble.

**Comment by thaJeztah** [comment]
I don't think this is something we want; docker requires a single process to act as `pid 1` in the container. Once that process terminates, the container terminates. In some cases, you may need a process manager, such as supervisor to act as pid 1.

@LK4D4 thoughts?

**Comment by JonasT** [comment]
Forgive me for thinking that, but since ``&& while true; do sleep 1; done`` or ``&& sleep infinity`` appended to the CMD is good enough to give docker a required ``pid 1`` process, your argument that this would be a real technical challenge to do automatically doesn't seem that convincing... then again I have to admit I don't know that much about init processes or supervisors.

**Comment by cpuguy83** [comment]
@JonasT You are right, these are all hacks...
however... I have run into literally 0 apps that can't be run in the foreground and as such none that require such a hack.

Not taking the time to figure out how to start the app correctly is just as much of a hack as the other's you've mentioned.

Now you can certainly use something like upstart in a container, which does support monitoring of forked off processes.

**Comment by riquito** [comment]
A possible use case. I have a container with php and some libraries. I need to run commands every now and then, and the container need some volumes attached. It turns out that it needs 1.5 seconds before executing a 0.03 command because of the volumes and I don't know what else it needs to initialize.
The container doesn't contain daemons and I arrived here searching for a way to put in sleep the container so that I can `exec` my commands when I need it, which is blazing fast since the container is already running.

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.

**Comment by JonasT** [comment]
So will someone remember to reopen this once you are done with that transition and you are considering changes again? I'm a bit confused why closing this is even necessary... it's not a patch after all, just a future feature request.

**Comment by josdotso** [comment]
Need this 💯
