### ISSUE TITLE
TestWaitBlockedExitRandom broken on lxc

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#12859]
fix this test so it works on lxc

```

----------------------------------------------------------------------
FAIL: docker_cli_wait_test.go:109: DockerSuite.TestWaitBlockedExitRandom

docker_cli_wait_test.go:131:
    c.Fatalf("expected exit 99, got %s", status)
... Error: expected exit 99, got 0

```

**Comment by fntlnz** [comment]
#dibs

**Comment by jmzwcn** [comment]
Any comments about how to fix this issue?

**Comment by jmzwcn** [comment]
such as:
if strings.TrimSpace(status) != "99" && !strings.Contains(container.ExecDriver, "lxc") {
			c.Fatalf("expected exit 99, got %s", status)
		}
But I don't this this '&&' is good idea.

**Comment by runcom** [comment]
@jmzwcn you should note that @fntlnz already called dibs on this issue to avoid working on the same thing twice

**Comment by jfrazelle** [comment]
@fntlnz do you need help, kinda want the build fixed

**Comment by jfrazelle** [comment]
@jmzwcn also that would not be an appropriate fix, it should work on lxc, not be skipped on lxc

**Comment by fntlnz** [comment]
@jfrazelle  I tried to trap the command with all available signals from `kill -l`

```
docker run -d busybox /bin/sh -c "trap 'exit 99' 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 64; top"
```

At this point I think that with lxc I can't trap because when I do it the handler already did this.

**Comment by jfrazelle** [comment]
Ok I'll fix this do u want to open whatever you have so far so your work isn't wasted and I can carry from there

**Comment by jfrazelle** [comment]
We just kinda need this fixed it's a blocker for anything lxc coming in

**Comment by cpuguy83** [comment]
This looks like a bug in LXC itself (lxc-start is not returning the exit code properly).

**Comment by LK4D4** [comment]
@cpuguy83 is something on lxc tracker?

**Comment by cpuguy83** [comment]
Actually, I found the problem.
We are using `lxc-stop -k`, which always sends `SIGKILL` (by default) to the container, and causes the lxc-start process to always return immediately with exit code 0.
By default, `lxc-stop` with no `-k` sends `SIGPWR`, not `SIGTERM`... you are supposed to be able to customize this in the container's configuration `lxc.haltsignal`, but this does not seem to be working for me.

`lxc-stop` does not accept arbitrary signals to pass to the container like `lxc-kill` used to.

Sending signals directly to the `lxc-start` process does work.
When the container does exit, however, lxc-start sends this to stderr:
```
lxc-start: lxc_start.c: main: 342 The container failed to start.
lxc-start: lxc_start.c: main: 346 Additional information can be obtained by setting the --logfile and --logpriority options.
```

Note this happens even with `lxc-stop` (no `-k`) when the container traps `SIGPWR`.
So this error does look like a bug for lxc... which itself can also be silenced by using `-q` on `lxc-start`.
