### ISSUE TITLE
Docker-machine documentation not completly correct?

### ISSUE THREAD

**Issue by Spirit328** [docker/docker#12855]
Hi there, 

something with `docker-machine` resp. `docker swarm` is not working as described in the documentation.

I am wokring on 
`$ uname -a`
`Linux BIGServer 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

 with

`$ docker version`
`Client version: 1.6.0`
`Client API version: 1.18`
`Go version (client): go1.4.2`
`Git commit (client): 4749651`
`OS/Arch (client): linux/amd64`
`Server version: 1.6.0`
`Server API version: 1.18`
`Go version (server): go1.4.2`
`Git commit (server): 4749651`
`OS/Arch (server): linux/amd64`

I installed "docker-machine" as described in the documentation. I created a "swarm-master" as described and I also created a swarm node.

`$ docker-machine ls`
`NAME            ACTIVE   DRIVER       STATE     URL                         SWARM`
`swarm-master    *        virtualbox   Running   tcp://192.168.99.101:2376   swarm-master (master)`
`swarm-node-01            virtualbox   Running   tcp://192.168.99.107:2376   swarm-master`

Now, let's see, if these Virtualboxes are running at all:
`$ ps -ef | grep "VBoxHeadless"`
`tmichels  2998  2463  2 16:54 ?        00:02:35 /usr/lib/virtualbox/VBoxHeadless --comment swarm-master --startvm 221b9611-340f-45c1-99a7-c7a6a7db8b29 --vrde config`
`tmichels 10193  2463  5 18:27 ?        00:00:37 /usr/lib/virtualbox/VBoxHeadless --comment swarm-node-01 --startvm d2e780b0-54f9-4e9b-98d1-f261b96e7261 --vrde config`

So far, so good. 
Then I wanted to use the swarm-master for using the setup. I opened a new ssh-shell (bash) and did a:
`$ env | grep DOCKER`
`$ docker-machine env --swarm swarm-master`
`export DOCKER_TLS_VERIFY=1`
`export DOCKER_CERT_PATH="/home/tmichels/.docker/machine/machines/swarm-master"`
`export DOCKER_HOST=tcp://192.168.99.101:3376`
`# Run this command to configure your shell: eval "$(docker-machine env swarm-master)" `

I did as requested: 

`$ eval "$(docker-machine env swarm-master)"`
`$ env | grep DOCKER`
`DOCKER_HOST=tcp://192.168.99.101:2376`
`DOCKER_TLS_VERIFY=1`
`DOCKER_CERT_PATH=/home/tmichels/.docker/machine/machines/swarm-master`

This looks, like I would be on "swarm-master".
Now the documentations says, if I do a `docker info`, I should see my "swarm-master" and the node. Right?

`$ docker info`
`Containers: 4`
`Images: 21`
`Storage Driver: aufs`
` Root Dir: /var/lib/docker/aufs`
` Backing Filesystem: extfs`
` Dirs: 29`
` Dirperm1 Supported: true`
`Execution Driver: native-0.2`
`Kernel Version: 3.19.0-15-generic`
`Operating System: Ubuntu 15.04`
`CPUs: 16`
`Total Memory: 141.7 GiB`
`Name: BIGServer`
`ID: XXXX-XXXX-XXXX-XXXX-XXXX`
`Username: tmichels`
`Registry: [https://index.docker.io/v1/]`

This does not look completly as shown in the documentation. 
Either this is not working properly or there is an error in the documentation or it does not work on Ubuntu 15.04.

**Comment by aanm** [comment]
@Spirit328 
There's a docker-machine repo where you can fill your issues :)
First you wrote 
> `$ docker-machine env --swarm swarm-master`

then you did
> `$ eval "$(docker-machine env swarm-master)"`

they are different things (see the `--swarm` option ;-) )

**Comment by Spirit328** [comment]
Upps! Wrong repo. Sorry!
