### ISSUE TITLE
Update the Help page to use IRC Cloud instead of Webchat

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#12854]
http://docs.docker.com/project/get-help/ recommends using webchat and has a little procedure to get people started.  IRCloud has a free account and better usability. We should switch it out.

**Comment by Jonty** [comment]
Here's the full list of link-to-irccloud-channel options, for reference. https://www.irccloud.com/badges

**Comment by mikebrow** [comment]
#dibs

**Comment by mikebrow** [comment]
@moxiegirl  IRCCloud has a 7 day free trial thing going then it's $5 us monthly.  
![screen shot 2015-08-25 at 12 08 43 pm](https://cloud.githubusercontent.com/assets/12767641/9473751/24d13954-4b22-11e5-851b-979e02e28d6c.png)
![screen shot 2015-08-25 at 12 09 52 pm](https://cloud.githubusercontent.com/assets/12767641/9473764/3b4c1d48-4b22-11e5-9f40-39224d960bb5.png)

Looks like "free" is now limited... please confirm whether I should put together a PR for this.

Cheers, Mike

**Comment by moxiegirl** [comment]
Oh, I'm looking at the pricing page:

https://www.irccloud.com/pricing

That looks like they have a limited free option. Am I reading it wrong?

**Comment by mikebrow** [comment]
@moxiegirl no that's correct :-)  It's a Freemium IRC.  I just wanted to make sure that was understood at the time of the recommendation to switch out or if it's changed and you wanted to reconsider.  By switch out, I take that to mean remove and replace.. or would you instead prefer to make two suggestions and leave the webchat one at the bottom after the new irccloud section.

Cheers, Mike

**Comment by moxiegirl** [comment]
@mikebrow thank you sir! Sorted hear and via our IRC chat.

**Comment by kytrinyx** [comment]
Was this issue closed by #16023?

**Comment by mikebrow** [comment]
Yes. Should be closed now.

**Comment by thaJeztah** [comment]
Good catch! Thanks @kytrinyx
