### ISSUE TITLE
insecure-registry is ignored

### ISSUE THREAD

**Issue by rabejens** [docker/docker#12869]
I am running Docker 1.5, and I am in the situation that I am forced to run HTTP and HTTPS connections through a transparent proxy which has another proxy set as a cache_peer. The transparent proxy must rewrite the SSL certificates because of its nature. This causes pulling from the registry to fail, like:

```bash
$ docker pull ubuntu:latest
Pulling repository ubuntu
FATA[0005] Get https://index.docker.io/v1/repositories/library/ubuntu/images: x509: certificate is valid for 162.242.195.84, not index.docker.io
```

The transparent proxy sets the common name of the certificate to the IP instead of the hostname and this causes the SSL verification to fail.

Now, I thought of using `insecure-registry`, but it simply seems to get ignored. What i tried (everything failed):
* --insecure-registry=index.docker.io
* --insecure-registry=https://index.docker.io
* --insecure-registry=https://index.docker.io:443
* the same without equals sign
* the same with the IP

The setting just seems to be silently ignored. What am I missing / doing wrong?

**Comment by jfrazelle** [comment]
can you try with docker 1.6 the latest version, also checkout the proxy docs http://docs.master.dockerproject.com/articles/systemd/#http-proxy

**Comment by jfrazelle** [comment]
closing for failure to respond but obviously if you respond with steps to reproduce on the latest version we will reopen
