### ISSUE TITLE
Ubuntu 15.04 does not respect proxy settings

### ISSUE THREAD

**Issue by krunchyal** [docker/docker#12868]
Upgraded to 15.04 yesterday from 14.04 and Docker won't respect the proxy settings I have set in `/etc/default/docker`. The relevant line looks like

` export http_proxy="http://proxy.blah.blah:8080/" `

The config worked fine under 14.04, but since the upgrade Docker is unable to pull from the registry. All other aspects work as expected. Is this possibly a systemd related issue?

My Docker version is `Docker version 1.6.0, build 4749651`
My kernel is `3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by jfrazelle** [comment]
this is because of systemd's setup
please see http://docs.master.dockerproject.com/articles/systemd

**Comment by binario200** [comment]
Thanks I try to solve this and It was with 

http://docs.master.dockerproject.org/engine/admin/systemd/#http-proxy
