### ISSUE TITLE
Container Remove on V 1.3.1 Cleanup not working!

### ISSUE THREAD

**Issue by diezcode** [docker/docker#12860]
I have a big problem with my space volume on my server.

when I try to remove the container with:
"sudo docker rm -v containerid"

the volume is still there. in the volume path and the vfs/dir path

my server is at 95,5% of 936GB !

I have 121 container and 303 images.

the volume is with 936 directorys and it doesn't remove when I delete containers.

**Comment by cpuguy83** [comment]
Presumably there are other containers using this volume.
You'd have to check the docker daemon logs (depends on your distro where these are).
Docker does not let you delete a volume if other containers are using it.

**Comment by diezcode** [comment]
How Can I check that? When I'm looking in the volumes I see not really a good information about, what container use the volume?

**Comment by cpuguy83** [comment]
Easiest thing would be to use cpuguy83/docker-volumes, it will enumerate all your volumes, lets you see what containers are using your volumes, and remove them directly (if no container is using it).

**Comment by diezcode** [comment]
I made this steps:
docker build -t docker-volumes https://github.com/cpuguy83/docker-volumes.git
docker run --name docker-volumes docker-volumes
docker cp docker-volumes:/docker-volumes ./

container is exiting all time, It don't find docker-volume list and when I start this container it exit automatically
Any help?

**Comment by cpuguy83** [comment]
@diezcode Easiest is to download the binary from the releases section of the repo.

**Comment by diezcode** [comment]
I found my problem of Space, I had alot of using in the pg_xlog of postgres directory. So I clear them and now everthing works fine. For the unused Volumes that I have from the docker containers, I used this bash script to clear them. https://github.com/chadoe/docker-cleanup-volumes
thanks
