### ISSUE TITLE
Installation on Ubuntu based dist (elementary OS)

### ISSUE THREAD

**Issue by basickarl** [docker/docker#12863]
I am running elementary OS Freya, based on Ubuntu 14.04.
https://elementary.io/

I suspect this can be troublesome for other dists based on Ubuntu also such as Deepin.

The following page has instructions which do not work (perhaps not enough information): https://docs.docker.com/installation/ubuntulinux/
```  
curl -sSL https://get.docker.com/ | sh
```  
```  
Either your platform is not easily detectable, is not supported by this
installer script (yet - PRs welcome! [hack/install.sh]), or does not yet have
a package for Docker.  Please visit the following URL for more detailed
installation instructions:

https://docs.docker.com/en/latest/installation/
```

I was however able to install via:
```
sudo apt-get -y install docker.io
```

**Comment by YoungElPaso** [comment]
Heh, I just noticed this as well, same work-around worked for me.

**Comment by jfrazelle** [comment]
This was added in master so it will be updated at the next release

**Comment by ColinMc** [comment]
What I did was I modified the lsb-release file and changed the DISTRIB_ID value to ubuntu then I ran the command. After the script was finished I reverted the file change.

**Comment by nikoe14** [comment]
Hi!, I edited my lsb-release file with these values and worked well. I hope this works for you.

sudo nano /etc/lsb-release                                                                                                          

#DISTRIB_ID="elementary OS"
#DISTRIB_RELEASE=0.3
#DISTRIB_CODENAME=freya
#DISTRIB_DESCRIPTION="elementary OS Freya"

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04 LTS"

**Comment by fdaciuk** [comment]
Thanks @nikoe14! This worked fine for me :dancer: :dancer:

**Comment by jpanlasi** [comment]
Thanks @nikoe14 +1

**Comment by amila-ku** [comment]
Download the docker installer script

wget -q https://get.docker.com/ 

this will download the installer script as index.html, rename this to install_docker.sh

vi install_docker.sh

then search for ubuntu

modify line 129 as below

ubuntu|debian|linuxmint|elementaryos)
                 export DEBIAN_FRONTEND=noninteractive

save the modification and then run the script.
sudo bash install_docker.sh

**Comment by Nept** [comment]
@nikoe14 Worked for me too. Thanks

**Comment by 007lva** [comment]
Thanks @nikoe14 :+1:

**Comment by legsoVI** [comment]
Thanks @nikoe14 , worked like a charm!

**Comment by legsoVI** [comment]
Thanks @nikoe14 , worked like a charm!

**Comment by welingtonveiga** [comment]
@nikoe14, worked for Mint too!
Thanks!

**Comment by thaJeztah** [comment]
For those interested; there's work I'm progress for a more generic approach in this PR: https://github.com/docker/docker/pull/15001

Testing if that script works for your distro would be greatly appreciated!

**Comment by PurpleBabar** [comment]
changing this
```
sudo add-apt-repository \
       "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
       $(lsb_release -cs) \
       stable"
```

to this
```
sudo add-apt-repository \
       "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
        xenial \
       stable"
```
and then just follow the install documentation
did it for me :)
