### ISSUE TITLE
journald logger should probably not be using MESSAGE_ID to hold the container id

### ISSUE THREAD

**Issue by larsks** [docker/docker#12864]
According to `systemd.journal-fields(7)`, the `MESSAGE_ID` field is "A 128-bit message identifier ID for recognizing certain message types, if this is desirable."  I think we are abusing this field by stuffing the container id into it.  The field is meant to identify unique messages types, not message sources.

If we want to record the container ID in the journal, note that "New fields may freely be defined by applications".  Maybe we should just use a `CONTAINER_ID` field.

**Comment by thaJeztah** [comment]
closing, because https://github.com/docker/docker/issues/12865 was merged
