### ISSUE TITLE
1.6 regression: "docker exec -i" hangs when process terminates

### ISSUE THREAD

**Issue by omribahumi** [docker/docker#12871]
The 2nd command hangs forever on 1.6. Works fine on 1.5

```bash
$ id=$(docker run -d ubuntu:14.04 /bin/bash -c 'sleep 100000000')
$ docker exec -i $id /bin/bash -c 'exit 0'
```

When using `-it` it works fine.

**Comment by duglin** [comment]
Can you try on the latest 'master' ?  I was able to reproduce it on the 1.6 branch, but not on the latest so I suspect its been fixed

**Comment by omribahumi** [comment]
@duglin where do I grab the latest master from?

**Comment by duglin** [comment]
Try one of these: https://master.dockerproject.com/

**Comment by omribahumi** [comment]
@duglin works with
```
Client version: 1.7.0-dev
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): f2f8e4c
OS/Arch (client): linux/amd64
Server version: 1.7.0-dev
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): f2f8e4c
OS/Arch (server): linux/amd64
```

Can the fix somehow be backported? What's the policy in such cases?

**Comment by duglin** [comment]
I don't think we backport fixes very often but I'll let @jfrazelle address that one.

**Comment by jfrazelle** [comment]
let me find what commit it was

**Comment by jfrazelle** [comment]
but I think this could be closed for now

**Comment by omribahumi** [comment]
@jfrazelle any luck in spotting the commit? We can't upgrade to 1.6 unless this is addressed

**Comment by LK4D4** [comment]
@omribahumi Was fixed in #12659

**Comment by omribahumi** [comment]
@LK4D4 @jfrazelle any chance this will be backported?

**Comment by jfrazelle** [comment]
I do not think so but it will be in 1.7 which is due out in June, hopefully
that is soon enough
