### ISSUE TITLE
docker storage options not working

### ISSUE THREAD

**Issue by abilashks** [docker/docker#12873]
DOCKER_STORAGE_OPTIONS="--storage-opt dm.loopdatasize=200G"
I had set the below option in my docker service but after reaching default 100GB not able to use docker

[root@localhost ~]# docker info
Containers: 0
Images: 378
Storage Driver: devicemapper
 Pool Name: docker-8:2-28967013-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 54.65 GB
 Data Space Total: 214.7 GB
 Data Space Available: 160.1 GB
 Metadata Space Used: 53.49 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.094 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Kernel Version: 3.10.0-229.1.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 16
Total Memory: 7.625 GiB
Name: localhost.localdomain
ID: VYLE:NP5X:H3VW:YQN5:ZZYO:V7JZ:PDTA:OJFZ:N4AE:O2I7:YIVR:LWBU

[root@localhost ~]# docker version
Client version: 1.5.0
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): fc0329b/1.5.0
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): fc0329b/1.5.0
OS/Arch (server): linux/amd64

**Comment by jfrazelle** [comment]
ping @vbatts

**Comment by vbatts** [comment]
thanks. 

@abilashks can you post the output of `df -h /var/lib/docker/` ?

**Comment by abilashks** [comment]
[root@localhost ~]# du -sh /var/lib/docker/
101G	/var/lib/docker/

[root@localhost ~]# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2       459G  102G  334G  24% /
devtmpfs        3.9G     0  3.9G   0% /dev
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           3.9G   17M  3.8G   1% /run
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup

**Comment by abilashks** [comment]
any update on this?

**Comment by vbatts** [comment]
@abilashks sorry! Did you include the `--storage-opt dm.loopdatasize=200G` option _after_ you had run the docker daemon (even one time)?
This loopdatasize is primary for the initial construction of the file's limit, not something that can change over time.

It looks like you have a number of images already. To set this size limit, you would need to start from a clean /var/lib/docker/, so that could require some coordination.

I would recommend though, if you can instead resize local lvm volumes, to make room for a 200G thin provisioned volume, it will give you much more flexibility in the future. Are you familiar with doing this?

**Comment by calavera** [comment]
Hey, It looks like this is not a docker issue. I'm going to close it, but feel free to reopen it again if you think it's still relevant to continue the discussion.

**Comment by kalesastha** [comment]
@vbatts I had the configuration for increasing the data [ /var/lib/docker/devicemapper/devicemapper/data ] size as 200GB . I did the fresh docker installation and configure the storage options as --storage-opt dm.loopdatasize=200G and restart the docker service.

After pulled so many images and invoked containers in my machine. Now the data file size crossed as 148GB . Then i invoke an container docker throws an error and the complete log is given below for your reference 

[root@localhost ~]# sudo docker run -i -t cmtools.csez.zohocorpin.com:5000/integ/centos6.4 /bin/bash
Error response from daemon: Error running DeviceCreate (createSnapDevice) dm_task_run failed

[root@localhost ~]# docker info
Containers: 47150
Images: 792
Storage Driver: devicemapper
 Pool Name: docker-8:2-28836570-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop2
 Metadata file: /dev/loop3
 Data Space Used: 158.1 GB
 Data Space Total: 214.7 GB
 Data Space Available: 56.69 GB
 Metadata Space Used: 2.147 GB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 147.5 kB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.1.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 16
Total Memory: 7.625 GiB
Name: localhost.localdomain
ID: VYLE:NP5X:H3VW:YQN5:ZZYO:V7JZ:PDTA:OJFZ:N4AE:O2I7:YIVR:LWBU

[root@localhost ~]# sudo docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64

Configuration file :-

OS/Arch (server): linux/amd64
[root@localhost ~]# cat /etc/sysconfig/docker
# /etc/sysconfig/docker
#
# Other arguments to pass to the docker daemon process
# These will be parsed by the sysv initscript and appended
# to the arguments list passed to docker -d

other_args="--insecure-registry cmtools.csez.zohocorpin.com:5000 -H tcp://0.0.0.0:4243 --api-enable-cors=true -H unix:///var/run/docker.sock --storage-opt dm.loopdatasize=200G"

Am i missing anything .? Or mistakenly configured anything in confuguration file .

please guide me to achieve my requirement . Your suggestions are highly appreciated .

Thanks,
Kaleeswaran N

**Comment by ashish235** [comment]
I have a similar case, I have two servers running docker with same configurations and both of them were working fine but suddenly the docker on one server started to refuse running containers and till date that docker is not functional, I tried everything I could. 

The error which I get is:

9ade5017d47b: Error pulling image (latest) from mongo, Driver devicemapper failed to create image rootfs 4c8cbfd2973e1b92137486922e1af5677fced4f6902e6513b81413e22f33ceaFATA[0091] Error pulling image (latest) from mongo, Driver devicemapper failed to create image rootfs 4c8cbfd2973e1b92137486922e1af5677fced4f6902e6513b81413e22f33ceab: Error running DeviceCreate (createSnapDevice) dm_task_run failed

And none of my images can be started on this particular docker. The only configuration changes on my docker is in the /etc/sysconfig/docker file. 

OPTIONS='-H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock --insecure-registry 172.16.111.195:5000 -r=true --storage-opt dm.basesize=40G'

Please help. I was planning to push my applications on docker on production and this happened and I 'm really scared now. 
Kindly let me know if you need any further details/debugs, I will be happy to provide the same.

[root@localhost ~]# docker info
Containers: 4
Images: 129
Storage Driver: devicemapper
 Pool Name: docker-253:1-67136160-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 0 B
 Data Space Total: 107.4 GB
 Data Space Available: 13.18 GB
 Metadata Space Used: 577.5 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.10.0-123.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 4
Total Memory: 15.4 GiB
Name: localhost.localdomain
ID: OBVR:V7TP:5FY5:FOT6:AJ2I:5LNT:IC65:QH4O:IQKV:INN4:WACB:SZJI


[root@localhost ~]#
[root@localhost ~]# docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
