### ISSUE TITLE
Installation instructions for Debian point to jessie-backports

### ISSUE THREAD

**Issue by ChimeraCoder** [docker/docker#12880]
Currently, as noted in #12861, the documentation points to installing Docker from the `jessie-backports` repository: http://docs.master.dockerproject.com/installation/debian/. However, the `docker.io` package is actually not in `jessie-backports` (yet); it is only available in Sid: https://packages.debian.org/search?keywords=docker.io

I would love to see Docker included in `jessie-backports`, because the Ubuntu repositories are annoying to access from blank Debian installations (for example, `apt-transport-https` is generally not included on fresh installations). But at the moment neither the current documentation nor trunk are correct. 

What is the preferred method of installation on Debian Jessie?

**Comment by jfrazelle** [comment]
It will be ping @tianon for date of that landing ;)

**Comment by jfrazelle** [comment]
also our deb package works on jessie

```
curl -sSL https://get.docker.com | sh
```

**Comment by ChimeraCoder** [comment]
Got it - thanks for the clarification!
