### ISSUE TITLE
docker-1.7.0-devel start failed

### ISSUE THREAD

**Issue by Mashimiao** [docker/docker#12889]
Hi guys,

$ uname -a
Linux hostname 3.19.5-200.fc21.x86_64 #1 SMP Mon Apr 20 19:51:56 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ rpm -qi docker-io
Name        : docker-io
Version     : 1.6.0
Release     : 2.git3eac457.fc21
Architecture: x86_64
Install Date: Wed 29 Apr 2015 12:20:39 PM CST
Group       : Unspecified
Size        : 21878248
License     : ASL 2.0
Signature   : RSA/SHA256, Sat 25 Apr 2015 01:36:29 PM CST, Key ID 89ad4e8795a43f54
Source RPM  : docker-io-1.6.0-2.git3eac457.fc21.src.rpm
Build Date  : Sat 25 Apr 2015 01:28:42 AM CST
Build Host  : buildvm-24.phx2.fedoraproject.org
Relocations : (not relocatable)
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : http://www.docker.com
Summary     : Automates deployment of containerized applications

Problem:
I have installed docker-1.6 and works well.
I compiled docker from mainline. And used the following command to replace docker-1.6:
sudo cp contrib/completion/bash/docker /usr/share/bash-completion/completions/docker
sudo service docker stop ; sudo cp $(which docker) $(which docker)_ ; sudo cp ./bundles/$ver-dev/binary/docker-$ver-dev $(which docker);sudo service docker start

But it started failed with the following log:
Apr 30 13:48:19 hostname docker[3444]: time="2015-04-30T13:48:19.444274749+08:00" level=info msg="Listening for HTTP on unix (/var/run/docker.sock)"
Apr 30 13:48:19 hostname docker[3444]: time="2015-04-30T13:48:19.444792076+08:00" level=error msg="Udev sync is not supported. This will lead to unexpected behavior, data loss and errors. For more information, see https://docs.docker.com/reference/commandline/cli/#daemon-storage-driver-option"
Apr 30 13:48:19 hostname docker[3444]: time="2015-04-30T13:48:19.444820254+08:00" level=error msg="[graphdriver] prior storage driver \"devicemapper\" failed: driver not supported"
Apr 30 13:48:19 hostname docker[3444]: time="2015-04-30T13:48:19.445045857+08:00" level=fatal msg="Error starting daemon: error initializing graphdriver: driver not supported"

I don't know why. Do you have any ideas?

**Comment by coolljt0725** [comment]
You have to enable `Udev sync` and to enable `Udev sync` you should use dynamic binary of docker.
Or you can with `--storage-opt dm.override_udev_sync_check=true` on docker daemon start, but `This will lead to unexpected behavior, data loss and errors`  There is a long story in #4036

**Comment by coolljt0725** [comment]
Or you can use other grapdriver not devicemapper

**Comment by Mashimiao** [comment]
@coolljt0725 the docker-1.6.0 works well. So I think Udev sync is already enabled.

**Comment by Mashimiao** [comment]
I reinstalled docker-1.6.0 and docker info is:
Containers: 40
Images: 116
Storage Driver: devicemapper
 Pool Name: docker-8:6-2239216-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 6.922 GB
 Data Space Total: 107.4 GB
 Data Space Available: 26.09 GB
 Metadata Space Used: 9.925 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.138 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93 (2015-01-30)
Execution Driver: native-0.2
Kernel Version: 3.19.5-200.fc21.x86_64
Operating System: Fedora 21 (Twenty One)
CPUs: 4
Total Memory: 7.651 GiB

**Comment by coolljt0725** [comment]
But it's weird that your log has this `Apr 30 13:48:19 hostname docker[3444]: time="2015-04-30T13:48:19.444792076+08:00" level=error msg="Udev sync is not supported. This will lead to unexpected behavior, data loss and errors. `
 Do you compile the mainline use  `dynbinary`( `./hack/make.sh dynbinary`)?

**Comment by Mashimiao** [comment]
No, I

**Comment by coolljt0725** [comment]
That's the problem, `make binary` build a static binary, A way to build dynbinary is 
`docker run -ti --privileged $(pwd):/go/src/github.com/docker/docker dockercore/docker ./hack/make.sh dynbinary`
and copy `bundles/1.7.0-dev/binary/docker-1.7.0-dev` and `bundles/1.7.0-dev/binary/dockerinit-1.7.0-dev` to docker install path

**Comment by Mashimiao** [comment]
Well, I think that can't slove problem.
run docker in container will use vfs not devicemapper.

**Comment by hqhq** [comment]
1.6.0 is workable but not stable, you'll meet problem as https://github.com/docker/docker/issues/4036 described. There is conclusion in https://github.com/docker/docker/issues/4036#issuecomment-76723060, you should use dynbinary if you want to use devicemapper.
Then https://github.com/docker/docker/pull/11412 make udev sync as hard requirement, so you got fail on 1.7.0-dev.

Build dynbinary in container is workable. You must met problem like https://github.com/docker/docker/issues/12535 .

**Comment by coolljt0725** [comment]
@Mashimiao  `docker run -ti --privileged $(pwd):/go/src/github.com/docker/docker dockercore/docker ./hack/make.sh dynbinary` is not to run docker in container, it's to build a dynamic binary.
I build dynamic binary in this way and it works for me

**Comment by Mashimiao** [comment]
Thanks both of you.  The problem has been solved.

**Comment by rickyzhang82** [comment]
@coolljt0725 

I build a dynbinary in FC21. However, there's a showstopper.

see my comment: https://github.com/docker/docker/issues/12479#issuecomment-101465517
