### ISSUE TITLE
When does container.UpdateDns is ever set to true?

### ISSUE THREAD

**Issue by didip** [docker/docker#12883]
Reference: https://github.com/docker/docker/blob/d2f0b9ed976987576483387bc919cb7ffbfa38e8/daemon/container.go#L1076

The reason I ask is because on our docker 1.5.0, `/etc/resolv.conf` is never copied into the container directory.

### Background Info
**Docker Info**
```
Containers: 3
Images: 94
Storage Driver: btrfs
Execution Driver: native-0.2
Kernel Version: 3.10.0-123.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 40
Total Memory: 125.7 GiB
Name: chi-prod-docker-10.xxxxx.net
ID: JIRM:P3MI:F7JI:ASMD:AROJ:PE2N:3H2O:DAYL:52H7:FLCP:ET7J:K2JA
```
**Docker Version**
```
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.3.3
Git commit (client): a8a31ef/1.5.0
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.3.3
Git commit (server): a8a31ef/1.5.0
```
**rpm -qa | grep docker**
```
docker-1.5.0-1.el7.x86_64
```
**uname -a**
```
Linux chi-prod-docker-10.xxxxx.net 3.10.0-123.el7.x86_64 #1 SMP Mon Jun 30 12:09:22 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

### Environment details (AWS, VirtualBox, physical, etc.)
Bare metal.

### Reproduce Steps
1. `watch cat /path/to/docker/containers/{sha}/resolv.conf` It's empty.
2. Modify `/etc/resolv.conf` (add a nameserver for example).
3. Notice that `/path/to/docker/containers/{sha}/resolv.conf` is still empty.

### Have we tried to upgrade to Docker 1.6.0?
Yes, we have. But Docker 1.6.0 has this blocker bug: https://github.com/docker/docker/issues/12595. That issue is breaking all of our Nagios checks.

**Comment by coolljt0725** [comment]
`container.UpdateDns` will be true when you update your host's `/etc/resolv.conf` and the container is running, so the running containers can update their dns on next start. Is these relate your issue?  Is "/etc/resolv.conf is never copied into the container directory." happened when your use `docker run` to run a container?

**Comment by runcom** [comment]
`UpdateDns` isn't in the code base anymore and this is handled by libnetwork now.
I'm gonna close this issue, @didip feel free to ping me if there's any reason I should reopen it
