### ISSUE TITLE
How to clear var/lib/docker/vfs/dir/8c1a8da710c53e0e1fbeb509389bfbb605b97929344df9318491bf2440203bfb/pg_xlog

### ISSUE THREAD

**Issue by diezcode** [docker/docker#12891]
My pg_xlog File has 890 GB Space using.
It has a lot of files that I can't open.
What can I do to clear that?

For what is the pg_xlog? And how can it use 890GB of my Space?
No wondering my Server with 1 Tera is full 

Thank you

**Comment by cpuguy83** [comment]
This is a volume from your postgres container. If nothing is using it you can just delete it out right.
I'd recommend downloading https://github.com/cpuguy83/docker-volumes/releases/tag/v1.1.1 to inspect your volumes and delete them safely.
