### ISSUE TITLE
Documentation mistake with VolumesFrom

### ISSUE THREAD

**Issue by acroca** [docker/docker#12895]
Hi,

In the docs it says that the `VolumesFrom` is sent as part of the create container `HostConfig` (https://docs.docker.com/v1.5/reference/api/docker_remote_api_v1.17/#create-a-container).

But it has to be sent in the start container parameters. (see here: https://github.com/docker/docker/blob/d716f22aadc738a1d086e7713defc1e933b983e1/integration-cli/docker_api_containers_test.go#L189-L192)

**Comment by acroca** [comment]
Same thing happens with the `PortBindings`

**Comment by cpuguy83** [comment]
@acroca It can be sent either way.
