### ISSUE TITLE
Proposal: add a TO instruction to Docker files

### ISSUE THREAD

**Issue by danse** [docker/docker#12897]
It seems a pity to me that every Docker file lists the dependency in `FROM`, but it does not list the name of the image which is creating.

Other systems managing dependency between resources usually state what every element needs but also what it is going to provide. This it is convenient for troubleshooting, and for analysing a dependency tree out of a static collection of Docker files.

In order to make the correspondence between every Docker file and its tagged image more clear, in my company we will have to use naming conventions.

Arguments passed via the command line do not leave any track, while a declarative way to specify the name of the new image would be more useful in my opinion

**Comment by cpuguy83** [comment]
Closing since this is really a dup of #5603

Would be good to put your use case on that issue.
Thanks!
