### ISSUE TITLE
Docker 1.6: fails to mount Amazon EBS storage

### ISSUE THREAD

**Issue by jgautheron** [docker/docker#12894]
Works fine with Docker 1.5.
I'm mounting in a data container the following (using Docker Compose 1.1):
```
- /var/www:/var/www
- /storage/media:/var/www/app/media
```
The `/storage/media` folder is an EBS storage volume. In the containers using the data container, the `media` volume mount failed.

```
# docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

# docker info
Containers: 12
Images: 103
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 131
Execution Driver: native-0.2
Kernel Version: 3.13.0-43-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 1
Total Memory: 3.676 GiB
Name: ip-10-84-33-22
ID: SRER:JZUQ:XNP7:6KU2:EPEU:2OBV:ZMXU:XGBL:XPCS:X6TZ:USJ2:DC4J
WARNING: No swap limit support

# uname -a
Linux ip-10-84-33-22 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
Environment details (AWS, VirtualBox, physical, etc.): AWS EC2.

Steps to reproduce:
1. Mount EBS storage in a data container
2. Check in another container which uses the data container (`volumes_from: data`), if the EBS storage is mounted

**Comment by cpuguy83** [comment]
You can't mount an fs in one container and use it another one as each container gets it's own mount namespace.

**Comment by jgautheron** [comment]
It doesn't work even if I set the mount on a specific container (without then using the data container).

**Comment by cpuguy83** [comment]
@jgautheron Can you check your init script and see what Mount options are set?
