### ISSUE TITLE
/etc/init.d/docker shall not exist if upstart used

### ISSUE THREAD

**Issue by seeder** [docker/docker#12896]
It is a bad practice to have /etc/init.d/docker when it's not used , especially it that it exits with failure when upstart is present.
Instead of having this convoluted contraption, just not have it in in the first place if you intend on using something else.

This is a big issue when orchestration frameworks try to interact with docker service and it fails ...

**Comment by cpuguy83** [comment]
@jfrazelle Is this still happening with the new apt packages?

**Comment by tianon** [comment]
This is standard behaviour for Debian packages, especially when they
support multiple init systems.

**Comment by cpuguy83** [comment]
Thanks @tianon 
I'm going to close this, then.

**Comment by tianon** [comment]
For a good example of this, see the file list in "openssh-server":
https://packages.debian.org/sid/amd64/openssh-server/filelist

(sysvinit, systemd, and upstart all included)
