### ISSUE TITLE
Port TestPostContainersAttach and TestPostContainersAttachStderr to integration-cli 

### ISSUE THREAD

**Issue by runcom** [docker/docker#12905]
As the title says, these 2 tests need to be ported to integration-cli (they aren't in the code base anymore but you can find them at the links below)

TestPostContainerAttach https://github.com/runcom/docker/commit/f7e417ea5e26f11ec43dba64ee153765d2276f40#diff-43dd6c60c47613b163fc23c09dbff200L242
TestPostContainerAttachStderr https://github.com/runcom/docker/commit/f7e417ea5e26f11ec43dba64ee153765d2276f40#diff-43dd6c60c47613b163fc23c09dbff200L318

**Comment by draghuram** [comment]
#dibs

**Comment by kostickm** [comment]
#dibs

**Comment by runcom** [comment]
:tada: thanks @kostickm

**Comment by kostickm** [comment]
@runcom No problem! :)
