### ISSUE TITLE
disable online discards by default for devicemapper graph driver

### ISSUE THREAD

**Issue by rhvgoyal** [docker/docker#12902]
Right now devicemapper mounts thin device using online discards by default
    and passes mount option "discard". Generally people discourage usage of
    online discards as they can be a drain on performance. Instead it is
    recommended to use fstrim once in a while to reclaim the space.
    
    In case of  containers, we recommend to keep data volumes separate. So
    there might not be lot of rm, unlink operations going on and there might
    not be lot of space being freed by containers. So it might not matter
    much if we don't reclaim that free space in pool.
    
    User can still pass mount option explicitly using dm.mountopt=discard to
    enable discards if they would like to.
    
    So this is more like setting the containers by default for better performance
    instead of better space efficiency in pool. And user can change the behavior
    if they don't like default behavior.

**Comment by unclejack** [comment]
@rhvgoyal What would be a good approach for running discard out of band? This is something which needs to be taken care of as well. There are people who are doing a lot of builds and cleaning this up at some point would be a good idea. Perhaps doing this when unmounting would be a good idea?

**Comment by rhvgoyal** [comment]
@unclejack 

Running fstrim during unmount sounds like a reasonable option.  I am little concerned about user noticing latencies in container exit (fstrim might noticeable latencies). 

Would it be fair to not enable it by default. Instead create a new option say dm.run_fstrim_on_unmount=true to enable this behavior?

**Comment by rhvgoyal** [comment]
@unclejack 

Or could it even be a per container option, say --fstrim-on-exit, where user specifies to run fstrim on container exit. (something like --rm option).

**Comment by unclejack** [comment]
@rhvgoyal My main concern in this case is making sure we provide some means of handling this for people doing builds. People doing a lot of builds usually want good performance when the builds are taking place, but they might be OK with running these operations asynchronously during a scheduled maintenance window. If they don't necessarily see performance degradation on other containers running other builds, I think handling discard operations could be done asynchronously by providing a storage option to do this.

Exposing a flag for run doesn't make sense, we'd have to add that to build as well and it's not a particularly great idea. It's also a bit of a problem if we start letting such graph driver specific flags into run/build options.

**Comment by rhvgoyal** [comment]
@unclejack Let me take a step back. I am wondering why do we need to worry about build process. IIUC, during build we will delete all the containers used for building and only thing remaining at the end will be images. Images are freshly created thin devices (using docker export) and they don't have to issue discards.

Only actual containers which did the build could have required fstrim to reclaim space from thin pool. But anyway container is going away after the build, thin device will be deleted and we will get space back in pool.

IOW, if we know that a thin device is going away soon, we don't have to issue discards to reclaim space in thin pool. 

Am I missing something ?

**Comment by unclejack** [comment]
@rhvgoyal You haven't missed anything, but I have, sorry. I'm going to close this issue as the associated PR has been merged.
