### ISSUE TITLE
Error pushing to registry while following the documentation guide

### ISSUE THREAD

**Issue by agonzalezro** [docker/docker#12904]
Hi,

I am following this [guide to setup a local registry](https://docs.docker.com/registry/deploying/).

On the step to push the image I am getting the following error:

```
$ docker push localhost:5000/hello-mine:latest
a8219747be10: Image push failed
FATA[0000] Error pushing to registry: mux: variable "hello-mine" doesn't match, expected "^(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/){1,4}[a-z0-9]+(?:[._-][a-z0-9]+)*$"
```

I think that I have followed the previous steps properly:

```
$ docker ps|grep regis
92ccd2969bc2        registry:2.0        "registry cmd/regist   16 minutes ago      Up 16 minutes       0.0.0.0:5000->5000/tcp     jolly_heisenberg
```

&

```
$ docker images|grep hello
hello-world                         latest               91c95931e552        12 days ago         910 B
localhost:5000/hello-mine           latest               91c95931e552        12 days ago         910 B
```

**Comment by agonzalezro** [comment]
Following the bot advices.

I've search for the issue but I couldn't find it.

Description of problem: Following the guide to create a local registry (v2.0) I get an error trying to push to it.

`docker version`:
```
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): darwin/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

`docker info`:
```
Containers: 14
Images: 227
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 255
Execution Driver: native-0.2
Kernel Version: 3.18.5-tinycore64
Operating System: Boot2Docker 1.5.0 (TCL 5.4); master : a66bce5 - Tue Feb 10 23:31:27 UTC 2015
CPUs: 4
Total Memory: 1.961 GiB
Name: boot2docker
ID: KQJS:GT4Z:RG6Z:SPFT:HFNM:OF46:S2JD:2B5I:Y64A:2XXB:PZ7S:DTDU
Debug mode (server): true
Debug mode (client): false
Fds: 43
Goroutines: 52
EventsListeners: 0
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: agonzalezro
Registry: [https://index.docker.io/v1/]
```

`uname -a`:
```
Darwin Alexs-MacBook-Pro.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
```

Environment details (AWS, VirtualBox, physical, etc.): `boot2docker` env version 1.5.0 (commit ccd9032).

How reproducible: Always

Steps to Reproduce:
Follow this guide: https://docs.docker.com/registry/deploying/ until the `docker push localhost:5000/hello-mine:latest` command

Actual Results:
``` 
a8219747be10: Image push failed
FATA[0000] Error pushing to registry: mux: variable "hello-mine" doesn't match, expected "^(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/){1,4}[a-z0-9]+(?:[._-][a-z0-9]+)*$"
``` 

Expected Results:
Get the image uploaded to the new local registry.

Additional info:
Nothing to add.

**Comment by runcom** [comment]
I'm pretty sure the mux errors is related to the docker registry v2 (docker/distribution) when pushing an image to a v2 registry in `graph/push.go`. I'm trying to reproduce btw

**Comment by thaJeztah** [comment]
Registry 2.0 only supports Docker 1.6 and newer clients. If you need to support older Docker clients, you'll have to run both a Registry 1.0 and 2.0, as is described in this section of the same document: [Configure Nginx with a v1 and v2 registry](https://docs.docker.com/registry/deploying/#configure-nginx-with-a-v1-and-v2-registry)

Could you test your setup, using a Docker 1.6 client?

**Comment by agonzalezro** [comment]
Hi @thaJeztah,

After creating this issue I figured out that the version of the client could be a problem so I updated it, but even with the new version I get the same problem:

```
$ docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): darwin/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64
```

**Comment by agonzalezro** [comment]
Hi @thaJeztah it looks like that's the issue. I've updated the client after the creation of this issue and now I am getting a certificate error non related with this one.

As far as I can tell I can close this ticket if you are happy with it.

Thanks for the help!

**Comment by thaJeztah** [comment]
Thanks for confirming it's resolved. I'll close the issue :)
