### ISSUE TITLE
LXC driver fails to work with recent LXC versions because of lxc.autodev default changes

### ISSUE THREAD

**Issue by samm-git** [docker/docker#12912]
I was trying to use docker with recet (1.1.2) LXC and found that it fails to create any containers because of lxc error:
```
lxc-start -n 1758f7589db0a17679b619f95f89fbf53851e27200b197b3a5168d0b4af35cfc -f /sdcard/dockerlib/containers/1758f7589db0a17679b619f95f89fbf53851
e27200b197b3a5168d0b4af35cfc/config.lxc -F -- /.dockerinit -g 172.17.42.1 -i 172.17.0.1/16 -mtu 1500 -- ash
lxc-start: conf.c: mount_entry: 1722 No such file or directory - failed to mount 'shm' on '/usr/lib/lxc/rootfs//dev/shm'
lxc-start: conf.c: lxc_setup: 3843 failed to setup the mount entries for '1758f7589db0a17679b619f95f89fbf53851e27200b197b3a5168d0b4af35cfc'
```

The problem is that in recent versions of LXC  lxc.autodev default is replaced to 1, so it is creating own tmpfs for dev where /dev/shm is n/a. To fix this i did such patch:

```diff
diff --git a/daemon/execdriver/lxc/lxc_template.go b/daemon/execdriver/lxc/lxc_template.go
index b3be7f8..5556010 100644
--- a/daemon/execdriver/lxc/lxc_template.go
+++ b/daemon/execdriver/lxc/lxc_template.go
@@ -59,6 +59,9 @@ lxc.cgroup.devices.allow = {{$allowedDevice.CgroupString}}
 # Use mnt.putold as per https://bugs.launchpad.net/ubuntu/+source/lxc/+bug/986385
 lxc.pivotdir = lxc_putold

+# disable lxc.autodev
+lxc.autodev = 0
+
 # NOTICE: These mounts must be applied within the namespace
 {{if .ProcessConfig.Privileged}}
 # WARNING: mounting procfs and/or sysfs read-write is a known attack vector.
```
After it docker starts to work correctly. Please let me know if i need to do a pull request.

**Comment by samm-git** [comment]
Description of problem:

`docker version`:
Docker version 1.7.0-dev, build 72e9e12-dirty

`docker info`:
oot@turris-test:~# docker info
Containers: 6
Images: 1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: lxc-1.1.2
Logging Driver: json-file
Kernel Version: 3.10.49-0c2718eb181fbb374701993d0f983176
Operating System: Turrris OS
CPUs: 2
Total Memory: 1.976 GiB
Name: turris
ID: Z3SN:DIMO:MEI2:JP5N:RM74:ZXAB:2KGG:XAFR:5XGU:JQWO:4TOZ:73V4
Debug mode (server): true
Debug mode (client): false
File Descriptors: 18
Goroutines: 23
System Time: 2015-04-30T21:55:04.349401Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/bin/docker
Docker Root Dir: /sdcard/dockerlib
Username: sammcz
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

`uname -a`:

Linux turris 3.10.49-0c2718eb181fbb374701993d0f983176 #1 SMP Tue Apr 28 18:13:06 UTC 2015 ppc GNU/Linux
Environment details (AWS, VirtualBox, physical, etc.):
physical

How reproducible:

Docker wont start any container with recent versions of LXC 
Steps to Reproduce:
1. Install LXC 1.1.2
2. Run docker with -e lxc
3. Try to start container


Actual Results:
 failed to setup the mount entries for  '<CONTID>'

Expected Results:
Working container :)

Additional info:
See original description

**Comment by stgraber** [comment]
Turning off autodev is one way of doing it, however doing so won't help if someone is running docker in an unprivileged environment and it also won't help once upstream LXC deprecates non-autodev (which is in our plans).

As far as I can tell, the problem that docker has with autodev is the lack of /dev/shm in our generated /dev. We don't have it in there because some distros make it a symlink while some others make it a directory, so there wasn't one good way of doing it.

Instead what we (upstream LXC) recommend people (docker, distros, ...) do is use the "create=dir" mount flag that LXC supports, so that the mountpoint is created by LXC as needed.

To fix docker, you'd basically change:

    lxc.mount.entry = shm CONTAINERPATH/dev/shm tmpfs size=65536k,nosuid,nodev,noexec 0 0

to:

    lxc.mount.entry = shm CONTAINERPATH/dev/shm tmpfs size=65536k,nosuid,nodev,noexec,create=dir 0 0


Also one small note there, LXC has supported relative mounts for a long time, so instead of hardcoding the long CONTAINERPATH, you could also just do:

    lxc.mount.entry = shm dev/shm tmpfs size=65536k,nosuid,nodev,noexec,create=dir 0 0

**Comment by samm-git** [comment]
@stgraber thank you for reply, i will try create=dir flag. However i cant find in which LXC version this flag was added and if it will break compatibility with some older releases.

P.S. I also found that lxc-go binding is exists and working well. Do you think its a good idea to convert exec driver to use binding instead? As benefit - LXC could be statically compiled, so no mess with different versions and defaults.

**Comment by stgraber** [comment]
@samm-git I'm pretty sure LXC ignores unknown mount flags in older versions, so if you're on an older version, you'll have lxc.autodev and so won't need create=dir to begin with, so create=dir should work in all cases but definitely worth testing.

**Comment by stgraber** [comment]
Our Go bindings are stable and well supported, we suggested Docker uses them a few times but there was the concern that you'd need to ensure you have LXC 1.0 at least on all machines.

**Comment by samm-git** [comment]
Just tested: it works fine with such patch:
```diff
diff --git a/daemon/execdriver/lxc/lxc_template.go b/daemon/execdriver/lxc/lxc_template.go
index e4a8ed6..9f26667 100644
--- a/daemon/execdriver/lxc/lxc_template.go
+++ b/daemon/execdriver/lxc/lxc_template.go
@@ -80,11 +80,11 @@ lxc.aa_profile = {{.AppArmorProfile}}
 {{end}}

 {{if .ProcessConfig.Tty}}
-lxc.mount.entry = {{.ProcessConfig.Console}} {{escapeFstabSpaces $ROOTFS}}/dev/console none bind,rw 0 0
+lxc.mount.entry = {{.ProcessConfig.Console}} {{escapeFstabSpaces $ROOTFS}}/dev/console none bind,rw,create=file 0 0
 {{end}}

-lxc.mount.entry = devpts {{escapeFstabSpaces $ROOTFS}}/dev/pts devpts {{formatMountLabel "newinstance,ptmxmode=0666,nosuid,noexec" ""}} 0 0
-lxc.mount.entry = shm {{escapeFstabSpaces $ROOTFS}}/dev/shm tmpfs {{formatMountLabel "size=65536k,nosuid,nodev,noexec" ""}} 0 0
+lxc.mount.entry = devpts {{escapeFstabSpaces $ROOTFS}}/dev/pts devpts {{formatMountLabel "newinstance,ptmxmode=0666,nosuid,noexec,create=dir" ""}} 0 0
+lxc.mount.entry = shm {{escapeFstabSpaces $ROOTFS}}/dev/shm tmpfs {{formatMountLabel "size=65536k,nosuid,nodev,noexec,create=dir" ""}} 0 0

 {{range $value := .Mounts}}
 {{$createVal := isDirectory $value.Source}}
```
I am able to create container (interactive and non-interactive), volumes are also working fine.

**Comment by samm-git** [comment]
@stgraber may be i will try to convert it to the go api calls. Another thing i dont like - the way how driver works with LXC. All lxc tools are out of sync and cant manage or work with docker-created containers. I think this is the reason why `docker exec` is not implemented in the LXC backend.

**Comment by calavera** [comment]
Thanks for opening this issue @samm-git. Do you mind to open a pull request with the patch? I can do it for you, but I'd sign a work that's not really mine, and that's very rude.

**Comment by xnox** [comment]
Why is this still not fixed? I see there is merge proposal for this... Anything I can do to get this moving?

**Comment by xnox** [comment]
@cpuguy83  thanks a lot! =)

**Comment by cpuguy83** [comment]
Thanks to everyone else, I just hit the merge button.
