### ISSUE TITLE
Docker links environment variables are limiting

### ISSUE THREAD

**Issue by MahmoudMahfouz** [docker/docker#12923]
I was just thinking why the created env variables when linking docker containers have such strange format.
why do I need to know the port in order to get the env variable?

ex: linking mongodb container with another app that uses mongo
```
docker run --name mongo mongo
docker run --link mongo:db whatever-app-that-uses-mongo
```
now I have 
DB_NAME=/ci/db
DB_PORT_27017_TCP_ADDR=172.17.0.117
DB_PORT_27017_TCP_PORT=27017
DB_PORT_27017_TCP_PROTO=tcp
DB_PORT_27017_TCP=tcp://172.17.0.117:27017
DB_PORT=tcp://172.17.0.117:27017

If I need to create the mongodb connection URI either I have to string-replace tcp with mongo in the most generic env variable

`DB_URI = $DB_PORT.replace(tcp, mongodb)`

or I have to know the port that I will be connecting on it which is 27017

`DB_URI = "mongodb://" + "$DB_PORT_{get the port from another var}_TCP_ADDR"  + "$DB_PORT_{get the port from another var}_TCP_PORT"`

Correct me if I'm wrong but I don't get why do we need port number in the name of the env variable, and I think it could be more generic if it didn't have it.

Thanks

**Comment by cpuguy83** [comment]
This is a dup of several issues.
Also these env vars are likely to go away and are generally not good for service discovery.
