### ISSUE TITLE
Describe roles of new project members

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#12938]
I noticed some people now (more) actively participating in the project and, although I can roughly "guess", their role and/or responsibilities *within the project* are not clear to me.

I'd love to see @calavera @diogomonica and @NathanMcCauley (perhaps other people from libnetwork) added to the [MAINTAINERS document](https://github.com/docker/docker/blob/master/MAINTAINERS), and (possibly) new roles and rules involved in this.

/cc @shykes @spf13 @docker/maintainers @docker/owners

**Comment by jfrazelle** [comment]
Bleh sorry ignore Gordon I am going to make him ignore issues from us

**Comment by thaJeztah** [comment]
@jfrazelle I'll also remove his comments from issues where they have been addressed to keep the discussion readable (I do like the new feature though).

**Comment by jfrazelle** [comment]
Thanks sorry
Going to tweak him a but probably this weekend

**Comment by thaJeztah** [comment]
@jfrazelle hehe, no prob, take yer time. (Would be awesome if it removed the comment after it looks to be addressed, but don't know if there's some way to detect that).

Now, so long for a clean on-topic discussion LOL

**Comment by jfrazelle** [comment]
Ooooo good idea can do!

**Comment by icecrime** [comment]
Thanks @thaJeztah, that's totally true.

As you may have guessed, all three are recent Docker employees. The reason we didn't add them from day one is that we want to break the idea that being a Docker employee makes you an automatic open source project maintainer: this is something that should happen naturally from constant, quality contribution to the repo.

The fact that you raise their absence of the MAINTAINERS file as an anomaly kind of demonstrates the case in point, and shows that time has probably come for them ;-)

**Comment by thaJeztah** [comment]
Thanks, @icecrime the reason I also asked is a) if their LGTM's have to be taken into account (and for what parts), and b) who the designated person is/are for security (still @ewindisch, or not?)

I'm happy seeing more people added, the project can always use some extra hands!

**Comment by ewindisch** [comment]
@thaJeztah I would like to see @NathanMcCauley and @diogomonica become security maintainers, but it is neither necessary nor automatic. As for myself, I do feel I could be a better maintainer than I am, and seek to be so. Certainly feel free to call me out on reviews needing attention.

**Comment by thaJeztah** [comment]
@ewindisch I know can ping you for security issues, and from my point of view, no need to apologize.

Just like to have clear what role people have in the project (head of "security" for Docker, inc. doesn't imply "head of security for the *project*"). I don't think Docker employees *have* to be a maintainer per-se, perhaps an "advisor" as role can be added for this (e.g., an advisor doesn't make *decisions*, but can be asked for advice when needed)

Just thinking out loud here :smile:

**Comment by thaJeztah** [comment]
closing, because https://github.com/docker/docker/pull/13391 and https://github.com/docker/docker/issues/13638 have been merged and the people mentioned are now added.

Thanks!
