### ISSUE TITLE
How can I get more than 64MB of tmp space in my container?

### ISSUE THREAD

**Issue by sroegner** [docker/docker#12940]
> $ docker --version                                                                                                                                 
    Docker version 1.6.0, build 3eac457/1.6.0

    >$ docker info
    Containers: 5
    Images: 2
    Storage Driver: overlay
     Backing Filesystem: extfs
    Execution Driver: native-0.2
    Kernel Version: 3.19.5-200.fc21.x86_64
    Operating System: Fedora 21 (Twenty One)
    CPUs: 8
    Total Memory: 31.31 GiB

    > $ docker run centos:6 dd if=/dev/zero of=/tmp/only64mboftmpspace bs=100k count=1024                                                                
    dd: writing `/tmp/only64mboftmpspace': No space left on device
    656+0 records in
    655+0 records out
    67108864 bytes (67 MB) copied, 0.0229038 s, 2.9 GB/s

This does not appear to depend in any way on which image i am using - /tmp is invariably now mounted as a 64MB tmpfs, just like /run. Also using devicemapper instead of overlayfs doesn't change anything 

This is a hard showstopper for us - please help.
I'd also like to note that I was unable to locate any mention of this change in either Changelogs or commit messages..

Also discussed here: https://groups.google.com/forum/#!topic/docker-user/Jki8JtWIm7A

**Comment by sroegner** [comment]
`Description of problem`:
 We use containers to run integration tests and the software tested uses the tmp file system during installation. 

`docker version`: 

    Docker version 1.6.0, build 3eac457/1.6.0

`docker info`:

    Containers: 5
    Images: 2
    Storage Driver: overlay
     Backing Filesystem: extfs
    Execution Driver: native-0.2
    Kernel Version: 3.19.5-200.fc21.x86_64
    Operating System: Fedora 21 (Twenty One)
    CPUs: 8
    Total Memory: 31.31 GiB

Environment details (AWS, VirtualBox, physical, etc.): Physical boxes

How reproducible: 100%


Steps to Reproduce: 

1. try to write a file larger than 64MB to /tmp

Actual Results: Get an error message 'No space left on device' 

Expected Results: /tmp should be able to accomodate files larger than 64MB and
that limit should probably be configurable or not exist as a separate concern 
in the first place.

Additional info:

    > $ docker run centos:6 dd if=/dev/zero of=/tmp/only64mboftmpspace bs=100k count=1024                                                                
    dd: writing `/tmp/only64mboftmpspace': No space left on device
    656+0 records in
    655+0 records out
    67108864 bytes (67 MB) copied, 0.0229038 s, 2.9 GB/s

**Comment by thieman** [comment]
Not an expert, but I can't reproduce and the only difference from my Docker config is that I'm using `aufs` instead of `overlay` as a storage driver. Could you please see if you can still reproduce using `aufs` so we know if it's an `overlay`-specific problem? I'd try `overlay` on my end, but I don't have a box lying around with a recent-enough kernel.

**Comment by runcom** [comment]
I'm using overlay with an ubuntu box as host and vanilla kernel 4.0.0 and I cannot reproduce with the commands you gave. I'm spinning up a fedora vm and try to repro

**Comment by sroegner** [comment]
Thanks for trying - i also cannot reproduce this on Ubuntu using either aufs, devicemapper or overlayfs.
Will try Fedora 22 next.

**Comment by sroegner** [comment]
Problem is reproducible on Fedora 22 Beta, Kernel 4.0.1-300, so i guess this is Fedora-specific.
Will try CentOS 7  as well just to make sure.

**Comment by sroegner** [comment]
Not reproducible on CentOS 7/devicemapper

    docker info
    Containers: 0
    Images: 0
    Storage Driver: devicemapper
     Pool Name: docker-253:0-100869707-pool
     Pool Blocksize: 65.54 kB
     Backing Filesystem: xfs
     Data file: /dev/loop0
     Metadata file: /dev/loop1
     Data Space Used: 307.2 MB
     Data Space Total: 107.4 GB
     Data Space Available: 28.08 GB
     Metadata Space Used: 733.2 kB
     Metadata Space Total: 2.147 GB
     Metadata Space Available: 2.147 GB
     Udev Sync Supported: true
     Data loop file: /var/lib/docker/devicemapper/devicemapper/data
     Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
     Library Version: 1.02.93-RHEL7 (2015-01-28)
    Execution Driver: native-0.2
    Kernel Version: 3.10.0-229.1.2.el7.x86_64
    Operating System: CentOS Linux 7 (Core)
    CPUs: 1
    Total Memory: 3.274 GiB

**Comment by sroegner** [comment]
This was addressed in https://bugzilla.redhat.com/show_bug.cgi?id=1216096 and is reported to be fixed in the latest docker build for Fedora.

**Comment by thaJeztah** [comment]
Thanks so much for researching and reporting back, @sroegner. Much appreciated!
