### ISSUE TITLE
create container: pipe2: too many open files

### ISSUE THREAD

**Issue by nashasha1** [docker/docker#12951]
when I use overlay in docker1.5.0/docker 1.6.0.
I create about 200 containers in a VM,appear docker error:
FATA[0000] Error response from daemon: Cannot start container b50cb3977180e31516dc8557b340d90d1b431eafe11714c8f2f8b1c48bdfa9f7: pipe2: too many open files

but When I changed back to aufs or devicemapper. no such error.(I created more than 600 containers)

docker info:
Containers: 240
Images: 27
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 3.18.0-031800-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 4
Total Memory: 14.69 GiB
Name: ip-172-31-36-172
ID: N5GO:KXIL:D5FG:AKAR:P3SM:577L:SPNL:TAUE:QSVW:AE7A:2KTZ:NHU3
WARNING: No swap limit support

docker version:

Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

same error in 1.6.0

How can I resolve this.

**Comment by xiaods** [comment]
you need upgrade your kernel to 4.2, then testing again.

**Comment by thaJeztah** [comment]
Closing this, because this issue looks to be stale, but feel free to comment here if you have additional information

**Comment by mamaledoboi** [comment]
I occur this problem now ,my docker verion is:

`Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64`

how can I resolve this problem?

**Comment by thaJeztah** [comment]
@mamaledoboi docker 1.7 is very old, and EOL, at least try updating to the current (1.13.1) release. If you're still having the issue on an up-to-date system, please open a new issue
