### ISSUE TITLE
Load fails on images saved by digest.

### ISSUE THREAD

**Issue by bwb** [docker/docker#12968]
Edited `2015-05-04 19:34:32+00:00`: apply [Issue Report Template](https://github.com/docker/docker/blob/master/CONTRIBUTING.md#reporting-other-issues)

Description of problem:

The save command succeeds when referencing an image by its digest. The load command fails with an "Illegal tag name" error. When using save and load, I expect both commands to succeed or both commands to fail.

`docker version`:
```
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64
```

`docker info`:
```
Containers: 0
Images: 22
Storage Driver: aufs
 Root Dir: /home/[snipped]/docker/aufs
 Backing Filesystem: extfs
 Dirs: 22
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-46-generic
Operating System: Ubuntu precise (12.04.5 LTS)
CPUs: 4
Total Memory: 7.754 GiB
Name: bench
ID: GGQ2:KGA7:X3IC:BFFJ:B5UM:N6SK:VX3R:ZX24:RZKP:EEPU:L7L7:PMOE
WARNING: No swap limit support
```

`uname -a`:
```
Linux bench 3.13.0-46-generic #79~precise1-Ubuntu SMP Tue Mar 10 20:25:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.):

physical

How reproducible:

always

Steps to Reproduce:

1. sudo docker pull registry:2.0
2. sudo docker run -d -p 5000:5000 registry:2.0
3. sudo docker tag registry:2.0 localhost:5000/registry:2.0
4. sudo docker push localhost:5000/registry:2.0
5. sudo docker pull localhost:5000/registry@sha256:91fab37536df5ce6afbecb0ae83eb498c6ee02be2b4c5223220fd42676850b62
6. sudo docker save -o testcase.tar localhost:5000/registry@sha256:91fab37536df5ce6afbecb0ae83eb498c6ee02be2b4c5223220fd42676850b62
7. sudo docker load -i testcase.tar

Actual Results:

FATA[0000] Error response from daemon: Illegal tag name
(sha256:91fab37536df5ce6afbecb0ae83eb498c6ee02be2b4c5223220fd42676850b62): only [A-Za-z0-9_.-] are allowed, minimum 1, maximum 128 in length 

Expected Results:

Image loads.

**Comment by thaJeztah** [comment]
ping @stevvooe I saw you were working on the validation/regexes for valid tag names.

**Comment by stevvooe** [comment]
This is a bug in the save/load code. It sounds like the load does not expect a digest in the tags map json file (called repositories, if I remember correctly).

@ncdc
