### ISSUE TITLE
Instances freeze

### ISSUE THREAD

**Issue by mjsalinger** [docker/docker#12962]
I've been troubleshooting high CPU/docker daemon choke points from starting and stopping a large number of containers (referenced previously in #11228 and #12758).  Based on the advice in these two threads, I decided to give OverlayFS a try by installing on Ubuntu 15.04.  Initially it seemed like results were good. CPU/memory usage was low, containers were starting / stopping with good performance.  

However, after a day or two running, things slowed down and ground to a halt, to the point where the system became unresponsive and had to be reset.  

docker info:  
```
Containers: 8
Images: 35
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 3.19.0-15-generic
Operating System: Ubuntu 15.04
CPUs: 2
Total Memory: 3.675 GiB
Name: <redacted>
ID: 3X6T:TWPU:QBFS:M65A:724X:64GN:W763:ZVIP:NRPN:N2TP:HPND:YTE4
WARNING: No swap limit support
```

docker version

```
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64
```

uname -a

```
Linux <redacted> 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

ulimit
```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 15011
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 15011
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Comment by LK4D4** [comment]
@mjsalinger Can you provide flags which you use for run containers?

**Comment by mjsalinger** [comment]
Using the docker remote API, I am explicitly setting the following flags:  

```
      ExposedPorts: {"7000/tcp": {}}
      HostConfig:
        PublishAllPorts: true
        CapDrop: [
          "CHOWN"
          "DAC_OVERRIDE"
          "FOWNER"
          "KILL"
          "SETGID"
          "SETPCAP"
          "NET_BIND_SERVICE"
          "NET_RAW"
          "SYS_CHROOT"
          "MKNOD"
          "SETFCAP"
          "AUDIT_WRITE"
        ]
```

Each container exposes a single port.

**Comment by mjsalinger** [comment]
Also of note - when we made the change over to 15.04 and overlay, I also added the below two flags.  I have just recently (in the last hour) removed them to see if it makes a difference:  

```
Memory:  67108864
MemorySwap: -1
```

**Comment by unclejack** [comment]
@mjsalinger Please provide a script which reproduces this using the docker cli client. I'd like to look into this.

**Comment by mjsalinger** [comment]
After more investigation, it appears this is an issue related to a Kernel bug in Ubuntu 15.04:

https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1420029

Switching to 14.4 w/ a 3.18 kernel caused the problem to disappear.
