### ISSUE TITLE
mkdir fails with EINVAL with overlayfs on CentOS 7.1

### ISSUE THREAD

**Issue by ronin13** [docker/docker#12984]
docker version 1.6 with -s overlay with ext4 backend
CentOS 7.1

mkdir fails with EINVAL.

With perf trace:
```
80407.179 ( 0.034 ms): perl/27590 mkdir(pathname: 0x214d6d0, mode: 511                                  ) = 0
 80414.361 ( 0.146 ms): perl/27590 mkdir(pathname: 0x214d6d0, mode: 511                                  ) = -22
```

This is innobackupex from xtrabackup failing to create directory with mkdir in perl.

Reported at https://github.com/docker/docker/issues/10180 earlier. Reporting separately since it is not related to any checksum or yum.

**Comment by ronin13** [comment]
`docker version`:

docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64
```

```
docker info
Containers: 7
Images: 28
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 3.10.0-229.1.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 8
Total Memory: 31.23 GiB
Name: qaserver-04.ci.percona.com
ID: CKNT:AAX7:GLXY:JZ3P:JL55:SZS2:HFE7:57P5:VQWN:HMZG:A2W2:24BA

```

```
uname -a
Linux qaserver-04.ci.percona.com 3.10.0-229.1.2.el7.x86_64 #1 SMP Fri Mar 27 03:04:26 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

```

`Environment details (AWS, VirtualBox, physical, etc.):`
Physical box.


How reproducible:
Consistently


Steps to Reproduce:
The test involves running one of our tests which does innobackupex which in turn does a mkdir which fails with invalid argument.

**Comment by ronin13** [comment]
I can also repeat this with docker-1.7.0-dev downloaded from: 

https://master.dockerproject.com/linux/amd64/docker-1.7.0-dev

**Comment by rahulpowar** [comment]
I have the same issue on a VirtualBox CentOS 7.1 VM.

**Comment by calavera** [comment]
@ronin13, @rahulpowar can you provide some simple steps to reproduce it? that would be super helpful.

**Comment by thaJeztah** [comment]
ping @ronin13 @rahulpowar could you provide the steps to reproduce this?

**Comment by cpuguy83** [comment]
Closing as more info is needed.
If you can provide the requested information please ping here so we can take a look.
Thanks!
