### ISSUE TITLE
`docker rmi -r` to remove dependent images

### ISSUE THREAD

**Issue by jdmarshall** [docker/docker#12998]
Let's say I want to rerun all of the steps in a docker build starting at Layer 6 (1265e16d0c28) and the last layer generated by the dockerfile is 1265e16d0c28

Today if I want to delete Layer 6 and rerun `docker build` I have to do something like this:

```
docker rmi $(docker history -q 89785ab09669 | grep -B 100 1265e16d0c28)
```

Which basically takes all of the images 'after' 1265e16d0c28 (inclusive) and deletes them in reverse chronological order.

If docker could do that for me, with something like:

```
docker rmi -r 1265e16d0c28
```

That would be a lot easier to explain to people (especially new people) and it reduces the frequency with which someone has to use --no-cache

**Comment by cpuguy83** [comment]
Hmmm, in my experience if you rm an image, docker will rm all other layers it depended on if nothing else is dependent on them  and they are not tagged.

**Comment by PikachuEXE** [comment]
Currently, when:
- A => B => C (A is the base)
- A => B => D (A is the base)
If you remove C **and** D, then B & A is removed

But he wants:
remove B (with `-r` he suggested)
will also remove C & D

**Comment by jdmarshall** [comment]
Right now removing the last image, tag or not, removes the entire tree of images (or at least until it hits one shared with another tag)

What I want is the reverse.  In the images I've had experience with, the vast majority of the transfer cost is represented in the layers up to the last apt-get call, inclusive.  

Right now there is no way to remove half of the cached layers and start over from, say, where I fixed a bug in my code.

**Comment by wr0ngway** [comment]
+1

**Comment by vschiavoni** [comment]
:+1:

**Comment by levrado** [comment]
👍

**Comment by DrStrangepork** [comment]
👍

**Comment by cpuguy83** [comment]
There is no longer any such thing as a "dependent image".
Images are flat (not a tree), and just happen to be able to share layers.
Layers cannot be removed unless all images using a particular layer is removed.

Closing since this is no longer relevant.
