### ISSUE TITLE
IPTables issue after installing Docker

### ISSUE THREAD

**Issue by tigranbs** [docker/docker#13006]
Hi
Before <a href="https://docs.docker.com/installation/ubuntulinux/#installing-docker-on-ubuntu">installing Docker</a> I had worked IPTables configurations like this

```bash
sysctl net.ipv4.ip_forward=1
iptables -t nat -A PREROUTING -p tcp --dport port -j DNAT --to-destination ip:port
iptables -t nat -A POSTROUTING -j MASQUERADE
```

for port forwarding using IPTables.<br/>
But after installing Docker this configurations not working any more.<br/>
<p>
I've tried to delete all IPTables rules and configure again but its not working.<br/>
Is there any one who had the same issue ? or can help me with this ?
</p>

**Comment by LK4D4** [comment]
I think nothing can be done here now :(
