### ISSUE TITLE
Incomplete inclusion of CAP_AUDIT_READ

### ISSUE THREAD

**Issue by Thell** [docker/docker#13007]
CAP_AUDIT_READ was added in https://github.com/docker/docker/pull/10853#issuecomment-98821661 but this looks to be incomplete as passing `--cap-add audit_read` results in 'Unknown capability to add'. It looks like it needs to be added to https://github.com/docker/docker/blob/master/daemon/execdriver/utils.go

**Comment by LK4D4** [comment]
@Thell Thanks.
I think proper fix will be PR to syndtr/gocapability to add function which get list of caps, then we can generate our list.

**Comment by Thell** [comment]
Completed in https://github.com/docker/docker/pull/13091
