### ISSUE TITLE
Graceful shutdown of stats streaming

### ISSUE THREAD

**Issue by icecrime** [docker/docker#13005]
Docker 1.6.0: interrupting stats streaming clutters daemon logs:

```
May 05 01:34:22 ip-10-150-12-224.ec2.internal dockerd[527]: time="2015-05-05T01:34:22Z" level="info" msg="-job container_stats(615cf172c9c7a75b2086ded0131cc827f59b3e71b41b5155f01d5d59144732d0) = ERR (1)"
May 05 01:34:22 ip-10-150-12-224.ec2.internal dockerd[527]: time="2015-05-05T01:34:22Z" level="error" msg="Handler for GET /containers/{name:.*}/stats returned error: write unix @: broken pipe"
May 05 01:34:22 ip-10-150-12-224.ec2.internal dockerd[527]: time="2015-05-05T01:34:22Z" level="error" msg="HTTP Error: statusCode=500 write unix @: broken pipe"
```

Can we gracefully detect the closing of the other end, and avoid unnecessary error logs?

See related line here: https://github.com/docker/docker/blob/91fb4d672a8536d2f0437aeeb2dfc7b9e51aac16/daemon/stats.go#L26

**Comment by runcom** [comment]
@icecrime also I've noticed if you stop a currently docker stats'ed container the docker stats just remains there, is this something we need to enanche as well? meaning closing docker stats too

**Comment by icecrime** [comment]
@runcom I *think* this is expected, because you might want to restart the container later.

**Comment by runcom** [comment]
alright (just checked instead if you try to rm the (running) container docker stats exits)

**Comment by phemmer** [comment]
You can detect a closed net http request with [CloseNotifier](http://golang.org/pkg/net/http/#CloseNotifier), but you're still going to be subject to race conditions, as the close can happen immediately before the write.
Thus the only way to completely solve is to handle the specific write failures that can occur (e.g. broken pipe).

**Comment by jmzwcn** [comment]
#dibs
I will try if if this issue still exits.

**Comment by jmzwcn** [comment]
Don't have any solution. Any help?

**Comment by cpuguy83** [comment]
@jmzwcn As far as I'm aware, the only way to capture this error is like so:
https://github.com/cpuguy83/docker/blob/13014_fix_goroutine_leak_on_logs_follow/daemon/logs.go#L169-L175

**Comment by cpuguy83** [comment]
Closing since this doesn't happen anymore.

**Comment by jmzwcn** [comment]
Great.
