### ISSUE TITLE
Dockerfile RUN command cannot make multiple directories

### ISSUE THREAD

**Issue by zhouyq** [docker/docker#13011]
I try to create multiple directories with a RUN command, but can not be created:

RUN mkdir -pv / tmp / {a, b, c}

In the Shell it creates three directory / tmp / a, / tmp / b, / tmp / c but only in the mirror created / tmp / {a, b, c} directory

=================
**docker version**
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64

**docker info**
Containers: 3
Images: 452
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 462
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.16.0-34-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 24
Total Memory: 125.9 GiB
Name: akka07
ID: HGUU:IW7K:ESFE:IZXN:HKT7:7HA6:SNQN:DSZ6:CLVU:4NPQ:Y2ZB:I3NL
WARNING: No swap limit support

**uname -a**
Linux akka07 3.16.0-34-generic #45~14.04.1-Ubuntu SMP Tue Mar 24 11:14:29 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by vdemeester** [comment]
Hi @zhouyq,

the ``RUN mkdir …`` is run using the shell form, but I would guess there is no shell expension when doing that, because it will run ``sh -c mkdir /tmp/{a,b,c}``. It's probably related to the use of ``sh`` in the docker building steps, and using your shell (``bash`` or ``zsh``, or ?).

For testing that :
```sh
docker run -ti --rm debian:jessie /bin/sh
# mkdir /tmp/{a,b,c}
# ls /tmp/
{a,b,c}
```

**Comment by duglin** [comment]
@zhouyq is it ok if we close this since it appears using bash solves the issue?

**Comment by zhouyq** [comment]
Thank vdemeester, ubuntu default dash, revised to bash normal.
