### ISSUE TITLE
Error while trying to install docker-io

### ISSUE THREAD

**Issue by ramesh-mohan-reddy** [docker/docker#13021]
Hi

As per https://docs.docker.com/installation/rhel/ installation procedure for 6.5, I am trying to install docker using yum install docker-io command
However, I get error saying below

Setting up Install Process
No package docker-io available.
Error: Nothing to do

Any help in this regard is greatly appreciated

Thanks in advance
Ramesh

**Comment by cpuguy83** [comment]
Do you have epel setup? Are you on x86-64?

**Comment by ramesh-mohan-reddy** [comment]
Now I setup epel and running into different issue

Steps to reproduce the issue that I am facing 
1. Installed EPEL on 6.5 RHEL 
2. Installed docker-io 
3. Able to run "docker" command 
4. When running "docker run -i -t fedora /bin/bash" command using without root, getting below error FATA[0000] Post http:///var/run/docker.sock/v1.17/containers/create: dial unix /var/run/docker.sock http:///var/run/docker.sock/v1.17/containers/create:%20dial%20unix%20/var/run/docker.sock : permission denied. Are you trying to connect to a TLS-enabled daemon without TLS?

However, with root getting diff error like below for the same command FATA[0000] Cannot connect to the Docker daemon. Is 'docker -d' running on this host?

**Comment by cpuguy83** [comment]
2 issues, 1 your user doesn't have access to /var/run, and the docker daemon is not running.
You need to make sure to start the service first.
