### ISSUE TITLE
Reserve published ports when using HairpinNAT

### ISSUE THREAD

**Issue by icecrime** [docker/docker#13024]
The HairpinNAT PR is most likely getting merged soon (#12165). Relying on HairpinNAT and IPTables rules for port publishing means that **nothing in Docker actually binds the published port**. To put it differently:

1. `docker run -p 80:80 foo/bar` might succeed even if something on the host besides Docker was already listening on port 80.
2. Running a process binding port 80 on the host will succeed even if a container is already publishing that same port.

What will happen in those cases in terms of prioritization of trafic is left as an exercise for the reader.

### Proposed solution

When HairpinNAT is enabled (`--userland-proxy=false`), port publishing should bind the published port for the **whole lifetime** of the container. This will allow to mark the port as reserved at the kernel level, and prevent both of the use case above (failure to bind at container start will prevent 1, failure to bind at service start time will prevent 2).

**Comment by thaJeztah** [comment]
Guess this should be in the 1.7 milestone?

**Comment by icecrime** [comment]
Makes sense as it goes hand-in-hand with the other on.e

**Comment by icecrime** [comment]
Closed by docker/libnetwork#195.
