### ISSUE TITLE
"Experimental" channel

### ISSUE THREAD

**Issue by icecrime** [docker/docker#13023]
There is a need to be able to ship features which are not entirely fully baked, not ready for production, or which can cause [nasal demons](www.catb.org/jargon/html/N/nasal-demons.html).

### Build and distribution

Create a new "experimental" distribution channel
    - Distributed on https://experimental.docker.com
    - Released following the same calendar than the "mainline" Docker

That "experimental" binary will be build using a new `experimental` build tag, which will allow to segregate the experimental features (which means those will be merged in master). Whether the build tag should control all the feature implementation, or solely the UX making it possible to use it, can be decided for each case. As a general rule, the priority should be to preserve the mainline's stability.

### Documentation

The documentation will have a new "experimental" section with a dedicated page for each experimental feature. The reason for this is that we don't want to duplicate the whole documentation, especially as we don't have an easy equivalent to build tags.

### Q&A

**How to "promote" an experimental feature to mainline?**
Send a PR which removes the build tags for this particular feature, remove the dedicate documentation page, and impact the regular documentation where applicable.

**How to ensure the experimental channel build at all times?**
We will need to add a CI job for this.

*Pinging interested people: @jfrazelle @moxiegirl @duglin @SvenDowideit*

**Comment by moxiegirl** [comment]
@icecrime Now, that I read this it sounds like you want to put documentation on a whole other site than `docs.docker.com`.   I was envision a section called *experimental* in the existing documentation.  

Do you agree with a section titled "Experimental" in the `docs.docker.com` site?

**Comment by icecrime** [comment]
@moxiegirl Totally!

**Comment by moxiegirl** [comment]
@icecrime super --- I thought so but always best to check.  I'll make that today.

**Comment by chanezon** [comment]
Experimental channel build binary should mention experimental in docker -v
https://github.com/docker/docker/issues/13385

**Comment by bfirsh** [comment]
Do features in the experimental release have to make it in before the code freeze?

**Comment by icecrime** [comment]
@bfirsh Assuming that only the UX is driven by `experimental` (as done for `--volume-driver` in #13161), yes absolutely, because the code impact for mainline is significant.

**Comment by icecrime** [comment]
@bfirsh That being said, if 100% of the patch is experimental, I guess it's worth considering... As I wrote, priority is obviously mainline stability.

**Comment by rade** [comment]
Will the "experimental" channel contain the same distribution packages as the normal channel? E.g. will I able to tell ubuntu to fetch docker packages from it with

    echo deb https://experimental.docker.com/ubuntu docker main > /etc/apt/sources.list.d/docker.list

?

**Comment by tomdee** [comment]
Is there going to be a 1.7 experimental release at the same time as the main 1.7 release?

**Comment by jfrazelle** [comment]
yes but also experimental builds will be nightly from master

**Comment by icecrime** [comment]
Closing this, everything is up on https://experimental.docker.com! Thanks @jfrazelle :+1:
