### ISSUE TITLE
Not creating ethernet interface on docker after providing lxc options

### ISSUE THREAD

**Issue by ninzyshah** [docker/docker#13030]
Hi All,

I am facing issues while trying to create docker with lxc options. I am trying to assign IP address to docker on an ethernet.

Below is full command:
docker run \
-n=false \
--lxc-conf="lxc.network.type = veth" \
--lxc-conf="lxc.network.ipv4 = 172.17.42.20/24" \
--lxc-conf="lxc.network.ipv4.gateway = 172.17.42.1" \
--lxc-conf="lxc.network.link = docker0" \
--lxc-conf="lxc.network.name = eth0" \
--lxc-conf="lxc.network.flags = up" \
--name myreg \
-i -t centos:6.6 /bin/bash

Above command is successful and creates a container. But, It doesn't create any ethernet on the container except loopback.

Version detail are as below:
OS - centos 6.5
docker repository - centos 6.6
docker version - 1.5
docker package - docker-io

Link on the machine:
[root@dhcppc1 Desktop]# ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 00:50:56:25:33:f5 brd ff:ff:ff:ff:ff:ff
3: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 00:50:56:21:18:9e brd ff:ff:ff:ff:ff:ff
4: eth3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 00:50:56:32:97:08 brd ff:ff:ff:ff:ff:ff
5: eth4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 00:50:56:24:92:ca brd ff:ff:ff:ff:ff:ff
6: eth6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 00:50:56:3c:85:90 brd ff:ff:ff:ff:ff:ff
7: eth5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 00:50:56:36:51:ca brd ff:ff:ff:ff:ff:ff
8: pan0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN 
    link/ether 0a:0a:44:46:75:53 brd ff:ff:ff:ff:ff:ff
9: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN 
    link/ether 1e:1f:68:7b:2c:63 brd ff:ff:ff:ff:ff:ff
10: virbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN 
    link/ether 52:54:00:45:8c:ab brd ff:ff:ff:ff:ff:ff
11: virbr0-nic: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 500
    link/ether 52:54:00:45:8c:ab brd ff:ff:ff:ff:ff:ff

Bridge detail on the machine:
[root@dhcppc1 Desktop]# brctl show
bridge name	bridge id		STP enabled	interfaces
docker0		8000.000000000000	no		
pan0		8000.000000000000	no		
virbr0		8000.525400458cab	yes		virbr0-nic

Ethernet detail on the machine:
[root@dhcppc1 Desktop]# ifconfig -a
docker0   Link encap:Ethernet  HWaddr 1E:1F:68:7B:2C:63  
          inet addr:172.17.42.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::1c1f:68ff:fe7b:2c63/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 b)  TX bytes:468 (468.0 b)

eth1      Link encap:Ethernet  HWaddr 00:50:56:25:33:F5  
          inet addr:172.24.35.208  Bcast:172.24.35.255  Mask:255.255.254.0
          inet6 addr: fe80::250:56ff:fe25:33f5/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:34452 errors:0 dropped:0 overruns:0 frame:0
          TX packets:26107 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:37097488 (35.3 MiB)  TX bytes:1950903 (1.8 MiB)

eth2      Link encap:Ethernet  HWaddr 00:50:56:21:18:9E  
          inet addr:172.24.35.5  Bcast:172.24.35.255  Mask:255.255.254.0
          inet6 addr: fe80::250:56ff:fe21:189e/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3963 errors:0 dropped:0 overruns:0 frame:0
          TX packets:17 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:256654 (250.6 KiB)  TX bytes:2922 (2.8 KiB)

eth3      Link encap:Ethernet  HWaddr 00:50:56:32:97:08  
          inet addr:172.24.35.44  Bcast:172.24.35.255  Mask:255.255.254.0
          inet6 addr: fe80::250:56ff:fe32:9708/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:4138 errors:0 dropped:0 overruns:0 frame:0
          TX packets:204 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:294785 (287.8 KiB)  TX bytes:18769 (18.3 KiB)

eth4      Link encap:Ethernet  HWaddr 00:50:56:24:92:CA  
          inet addr:172.24.35.192  Bcast:172.24.35.255  Mask:255.255.254.0
          inet6 addr: fe80::250:56ff:fe24:92ca/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3967 errors:0 dropped:0 overruns:0 frame:0
          TX packets:21 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:257230 (251.2 KiB)  TX bytes:3282 (3.2 KiB)

eth5      Link encap:Ethernet  HWaddr 00:50:56:36:51:CA  
          inet addr:172.24.35.21  Bcast:172.24.35.255  Mask:255.255.254.0
          inet6 addr: fe80::250:56ff:fe36:51ca/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3977 errors:0 dropped:0 overruns:0 frame:0
          TX packets:26 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:265763 (259.5 KiB)  TX bytes:3637 (3.5 KiB)

eth6      Link encap:Ethernet  HWaddr 00:50:56:3C:85:90  
          inet addr:172.24.35.131  Bcast:172.24.35.255  Mask:255.255.254.0
          inet6 addr: fe80::250:56ff:fe3c:8590/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3957 errors:0 dropped:0 overruns:0 frame:0
          TX packets:14 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:255394 (249.4 KiB)  TX bytes:3204 (3.1 KiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:12 errors:0 dropped:0 overruns:0 frame:0
          TX packets:12 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:690 (690.0 b)  TX bytes:690 (690.0 b)

pan0      Link encap:Ethernet  HWaddr 0A:0A:44:46:75:53  
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 b)  TX bytes:0 (0.0 b)

virbr0    Link encap:Ethernet  HWaddr 52:54:00:45:8C:AB  
          inet addr:192.168.122.1  Bcast:192.168.122.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 b)  TX bytes:0 (0.0 b)

virbr0-nic Link encap:Ethernet  HWaddr 52:54:00:45:8C:AB  
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:500 
          RX bytes:0 (0.0 b)  TX bytes:0 (0.0 b)

Please let us know, If I may provide you anything else to debug into that direction.

Thanks & Regds,
Ninad Shah

**Comment by Nagodar** [comment]
have you changed the driver to lxc? (i.e. started de docker daemon with -e lxc )?

**Comment by thaJeztah** [comment]
As @Nagodar mentioned; the `--lxc-conf` options are only for the LXC driver, not the "native" driver;

https://docs.docker.com/reference/run/#runtime-privilege-linux-capabilities-and-lxc-configuration

> If the Docker daemon was started using the lxc exec-driver (docker -d --exec-driver=lxc) then the operator can also specify LXC options using one or more --lxc-conf parameters.

I'm going to close this issue, because this doesn't look to be a bug, but an incorrect use. Feel free to comment here if you think I closed this by mistake.
