### ISSUE TITLE
SSH login to debian:8.0 based container fails when started with --net="host"

### ISSUE THREAD

**Issue by jannek-octo3** [docker/docker#13042]
Description of problem:
When using debian:7.8 image, ssh login to container works when container is started with --net="host".
I get "Permission denied, please try again." when trying same on debian:8.0 image.

`docker version`:
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64

`docker info`:
Containers: 0
Images: 977
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 977
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-52-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 993.9 MiB
Name: janne-VirtualBox
ID: RNDC:2GI7:3Q2Z:DKUC:NDM3:FHK3:E7K7:TZSQ:MELL:JWPC:Z4KN:OZTW
Username: platformutribocom
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support

`uname -a`:
Linux janne-VirtualBox 3.13.0-52-generic #85-Ubuntu SMP Wed Apr 29 16:44:17 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
VirtualBox, 64 bit Windows 7 host, 64 bit Ubuntu 14.04.2 client used as Docker host.
Tested also on AWS EC2 with 64 bit Ubuntu 14.04.2 Docker host.

How reproducible:
always

Steps to Reproduce:
```
1. Use this dockerfile to reproduce problem:

FROM debian:8.0
RUN apt-get update
# Enable ssh
RUN export DEBIAN_FRONTEND=noninteractive && apt-get install openssh-server -y
# Make run directory for sshd
RUN mkdir -p /var/run/sshd
# Change default ssh port to 60001 for avoiding conflict with docker host if started with --net="host"
RUN sed -i "s/.*Port 22.*/Port 60001/" /etc/ssh/sshd_config
# Enable login with password
RUN sed -i "s/PermitRootLogin without-password/PermitRootLogin yes/" /etc/ssh/sshd_config
# Set root password
RUN echo 'root:abc123' |chpasswd
# Edit: xx.sh not needed for reproducing
# Start sshd and infinite loop that keeps container alive
#RUN echo "/usr/sbin/sshd" > /root/xx.sh
#RUN echo "while true; do sleep 5; done" >> /root/xx.sh

2. Build image:
sudo docker build -t janne:8.0 --rm=true --no-cache=true .

3. Start with only ssh port 60001:
# Edit: xx.sh not needed for reproducing
#sudo docker run -d -p 60001:60001 janne:8.0 /bin/bash /root/xx.sh
sudo docker run -d -p 60001:60001 janne:8.0 /usr/sbin/sshd -D

4. Login with password abc123 works fine:
ssh root@127.0.0.1 -p 60001

5. Stop container and start from same image with --net="host" setting:
# Edit: xx.sh not needed for reproducing
#sudo docker run -d --net="host" janne:8.0 /bin/bash /root/xx.sh
sudo docker run -d --net="host" janne:8.0 /usr/sbin/sshd -D

6. Try to login with same password, you get permission denied:
ssh root@127.0.0.1 -p 60001
```
Actual Results:
"Permission denied, please try again."

Expected Results:
Login succeed.

Additional info:
Change FROM line on dockerfile to debian:7.8 and do same test again, works fine.

**Comment by cpuguy83** [comment]
I imagine there's an extra setting you need to deal with for sshd.

**Comment by jannek-octo3** [comment]
You mean extra setting on host or image side?

Just compared my /etc/ssh/sshd_config files on debian:7.8 and debian:8.0 based images and only difference is line "HostKey /etc/ssh/ssh_host_ed25519_key" on 8.0 config that not exist on 7.8.

**Comment by jannek-octo3** [comment]
Shortly:
On debian:7.8 ssh works with both '-p 60001:60001' and '--net="host"'
On debian:8.0 ssh works with '-p 60001:60001' but not works with '--net="host"'

**Comment by cpuguy83** [comment]
I'm really not sure what the last couple of lines in your Dockerfile are about, but the correct way to start sshd would be `/usr/sbin/sshd -D`

Also, I'm not able to reproduce this issue.

**Comment by jannek-octo3** [comment]
Yes xx.sh script is not needed for reproducing problem. It was stripped from my longer script that starts sshd, cron, rsyslog, updates private ip address to sylkserver config file, starts sylkserver and then goes to infinite loop. Same script also stops them when container is stopped.

I just did new test on 64 bit Ubuntu 14.04.2 on AWS EC2. I copy/pasted Dockerfile contents and commands from this web page except started container "sudo docker run -d -p 60001:60001 janne:8.0 /usr/sbin/sshd -D" and "sudo docker run -d --net="host" janne:8.0 /usr/sbin/sshd -D".

Result was same: ssh login ok when started with "-p 60001:60001" but login failed when started with "--net="host"".

My problem would be solved if I could map port range for sylkserver but I've understood it is not possible and listing 10000 ports with -p parameter one by one not sounds a good idea...

**Comment by cpuguy83** [comment]
@jannek-octo3 You can map a port range as such `docker run -p 1000-11000`, however these will by dynamically allocated.

Also still I cannot reproduce your issue.
Wonder if it's some issue with pam and/or apparmor?
Have you tried running it with --privilege... or disabling pam in the sshd config?
Just guessing at things here.

**Comment by jannek-octo3** [comment]
I think it is quite difficult to get sylkserver working without 1:1 port mapping. Same problem with SEMS.

It is strange that you can't reproduce my ssh problem as I have it on both VirtualBox and EC2 but disabling PAM did the trick! I added this line to Dockerfile and login works now with "--net="host" setting:
RUN sed -i "s/UsePAM yes/UsePAM no/" /etc/ssh/sshd_config

What is the difference from container angle on ssh login to port 60001 if container is started "-p 60001:60001" or "--net="host"? I've understood container sees identical login attempt on both cases.

**Comment by jfrazelle** [comment]
I think this is not a bug and more of a misunderstanding be sure to checkout forums.docker.com or the docker-user mailing list for user oriented questions
