### ISSUE TITLE
Docker exec prints nothing without a PTY

### ISSUE THREAD

**Issue by russell** [docker/docker#13047]
When running docker exec commands from a service like ~~cron~~ or init there often isn't a PTY.  Docker still seems to run the commands but it doesn't return any stdout/stderr output.

This problem can be worked around by calling docker with the `unbuffer` command but it's really hard to figure this out.

**Comment by cpuguy83** [comment]
With what options are you calling `docker exec`?

**Comment by russell** [comment]
The command i'm running is.

`docker exec -i postgres-container bash -c "find /usr/lib/postgresql/ -name pg_isready"`

**Comment by russell** [comment]
hmmm. despite my best efforts i can't reproduce this any more with version 1.5.0-28.el7.centos

Apologise for the noise.

**Comment by cpuguy83** [comment]
I would also note that unless you are passing something to the stdin of the docker process, there is no reason to use `-i`.
