### ISSUE TITLE
devicemapper and aufs behave differently with setgid directory

### ISSUE THREAD

**Issue by icy** [docker/docker#13084]
Original report: https://github.com/icy/docker/tree/master/bugs/chmod_s_bug

## Description

`devicemapper` and `aufs` behave differently with setgid directory.

The directory `/var/log/exim4` is owned by `Debian-exim:adm`,
and it's `setgid` (aka `chmod g+s`). When `uid/gid` of `Debian-exim`
is updated, the user `Debian-exim` may not be able to write to
`/var/log/exim4/`.

The problem happens only when back-end storage is `aufs`.
Within `devicemapper` back-end, there isn't problem.

## Expected result

The directory `/var/log/exim4` is writable by `Debian-exim` after `uid`
is updated, on both `devicemapper` and `aufs` back-ends.

## Actual result

Within `aufs` back-end, the directory `/var/log/exim4` is not-writable
by `Debian-exim` after `uid` is updated.

## Reproduce the bug

First, switch to `aufs` back-end. Build the container from `debian:wheezy`
and run the final container.

````
$ git clone https://github.com/icy/docker.git
$ cd bugs/chmod_s_bug/
$ docker build -t icy/chmod_s_bug .
$ docker run --rm -ti icy/chmod_s_bug

+ _D_=/var/log/exim4/
+ ls -lad /var/log/exim4//
drwxr-s--- 2 Debian-exim adm 4096 May  8 10:41 /var/log/exim4//
+ groupmod -g 1200 Debian-exim
+ usermod -g 1200 -u 1200 Debian-exim
+ chown Debian-exim:adm -Rc /var/log/exim4/
changed ownership of `/var/log/exim4/' from 101:adm to Debian-exim:adm
+ su - Debian-exim -s /bin/bash -c 'date > //var/log/exim4//good.txt'
No directory, logging in with HOME=/
-su: //var/log/exim4//good.txt: Permission denied
+ ls -lad /var/log/exim4//
drwxr-s--- 2 Debian-exim adm 4096 May  8 10:41 /var/log/exim4//
+ ls -ltr /var/log/exim4//
total 0

````

## Docker environments

See `docker.aufs.txt` and `docker.devicemapper.txt`.

### docker/aufs

Docker version
````
Client version: 1.6.0
````

Docker info:

````
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64
Containers: 2
Images: 151
Storage Driver: aufs
 Root Dir: /example.com/docker/data/aufs
 Backing Filesystem: extfs
 Dirs: 155
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-44-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 3.859 GiB
Name: star-dev-001.us-west-2a.int.example.com
ID: ATZL:25Q3:C4XC:KEUA:KIPJ:KT4Z:2U5U:XZOO:DWVE:2LZX:LHTG:KKCN
WARNING: No swap limit support
````

Uname

````
Linux star-dev-001.us-west-2a.int.example.com 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

````

### docker/devicemapper

Docker version
````
Client version: 1.6.0
````

Docker info

````
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64
Containers: 3
Images: 168
Storage Driver: devicemapper
 Pool Name: docker-252:1-917508-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: 
 Metadata file: 
 Data Space Used: 4.114 GB
 Data Space Total: 107.4 GB
 Data Space Available: 103.3 GB
 Metadata Space Used: 7.385 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.14 GB
 Udev Sync Supported: false
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.13.0-44-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 3.859 GiB
Name: admin.us-west-2a.int.example.com
ID: IHB2:MZZH:JIL7:NTHZ:CZED:QQHV:4XCP:CLPF:DQKH:Q5BN:27J4:OF6N
WARNING: No swap limit support
````

Uname

````
Linux admin.us-west-2a.int.example.com 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

````

**Comment by icy** [comment]
is this a bug? I did search and I see no where a similar problem. Please take a look. Thank you the team!

**Comment by thaJeztah** [comment]
> `Dirperm1 Supported: false`

This could well be the reason this is not working correctly on AUFS; see https://github.com/docker/docker/issues/783#issuecomment-19237045, https://github.com/docker/docker/issues/783#issuecomment-76417033

**Comment by icy** [comment]
Thanks a lot, @thaJeztah . It seems that's an AUFS problem. I will stay with `devicemapper` instead! You may close this ticket.

**Comment by thaJeztah** [comment]
Keep in mind that devicemapper (with the default settings) isn't really intended for "production".  If possible, BTRFS and (it requires a modern kernel) overlay(fs) may be good alternatives.

(Oh, and we just merged an initial implementation of ZFS, which could be interesting)

I'll close this issue for now.
