### ISSUE TITLE
shellcheck linting

### ISSUE THREAD

**Issue by kojiromike** [docker/docker#13081]
I'd be up for picking through the various shellcheck nitpicks on docker's shell scripts if that would be of value. I created the following script to quickly identify files that could be affected:

```sh
find . -name .git -prune -o \
       -type f -exec awk '
         NR==1&&/^#!.*(env |bin\/)(ba)?sh/{
           print FILENAME;
           exit
         }' {} \; |
     xargs -n1 -P6 sh -c '
       shellcheck "$1" >/dev/null 2>&1 ||
       echo "$1"
     ' _
```

I am aware that there are some shell scripts that deliberately do behaviors flagged by shellcheck now, such as

```
In ./vendor/src/github.com/kr/pty/mktypes.bash line 6:
	echo 'undefined $GOOS_$GOARCH:' "$GOOSARCH" 1>&2
             ^-- SC2016: Expressions don't expand in single quotes, use double quotes for that.
```

For now, I would just ignore those warnings. Is this something the Docker community would find helpful?

**Comment by thaJeztah** [comment]
Thanks for suggesting this, I'll include @tianon, who is probably the most appropriate person to answer this :)

**Comment by tianon** [comment]
I'm not necessarily opposed (assuming the advice is good and we don't already have reasons for the way we do it otherwise). :+1:

You'll definitely want to ignore all of `vendor/`, since that's copied verbatim from our upstreams.

**Comment by cpuguy83** [comment]
Is this being worked on? If not I'd like to close this since it's not really actionable.

**Comment by kojiromike** [comment]
I'll open individual prs for lint issues.
