### ISSUE TITLE
root dir for execdriver (/var/run/docker) should be configurable

### ISSUE THREAD

**Issue by difro** [docker/docker#13082]
Unlike docker runtime dir, which can be configured with ```--graph`` option,
there doesn't seem to be any way to manually set execdriver's rootdir.

Seems the hard-coded ```/var/run/docker``` path was introduced with this PR #11716

It'd be great if we could configure this with command line arg?

**Comment by dqminh** [comment]
I think this is reasonable. Wdyt @LK4D4 ?

Also what will the flag be named if this is accepted ? `--execdir` ?

**Comment by shishir-a412ed** [comment]
+1 for this. Opened PR https://github.com/docker/docker/pull/13086.
