### ISSUE TITLE
404: "no such process" when stopping running container

### ISSUE THREAD

**Issue by jongiddy** [docker/docker#13088]
Description of problem: I get a 404 response from the Docker server when stopping a container, although the container exists.

`docker version`:
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.3.3
Git commit (client): a8a31ef/1.5.0
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.3.3
Git commit (server): a8a31ef/1.5.0

`docker info`:
Containers: 0
Images: 3
Storage Driver: devicemapper
 Pool Name: docker-202:1-125250-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 310.3 MB
 Data Space Total: 107.4 GB
 Metadata Space Used: 806.9 kB
 Metadata Space Total: 2.147 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82 (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.11.10-301.fc20.x86_64
Operating System: Fedora 20 (Heisenbug)
CPUs: 1
Total Memory: 3.662 GiB
Name: ip-172-31-13-100
ID: HOVD:D2O4:TQR7:RJBS:6REO:EYWR:FCZY:YSWJ:5ZFC:GR5G:EA6C:X35M

`uname -a`:
Linux ip-172-31-13-100 3.11.10-301.fc20.x86_64 #1 SMP Thu Dec 5 14:01:17 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
AWS Fedora-x86_64-20-20140407-sda (ami-cc8de6fc). 

How reproducible:
Cannot reproduce on my local machine, but consistent on above image.

Steps to Reproduce:
- Start a Fedora image on EC2 - I use Fedora-x86_64-20-20140407-sda (ami-cc8de6fc). This does not occur on my local machine, but does happen on AWS EC2.
- Create the file `waittest.py` containing:
```python
import sys
import time

from docker import Client
from docker.errors import APIError
from docker.utils import create_host_config

import requests.packages.urllib3
requests.packages.urllib3.add_stderr_logger()


def f():
    image_name = u'busybox'
    container_name = 'test1'
    client = Client()
    host_config = create_host_config(
        binds={}, port_bindings={}, restart_policy={u"Name": u""})
    sys.stderr.write('create\n')
    client.create_container(
        name=container_name, image=image_name, command=None, environment=None,
        ports=[], mem_limit=None, cpu_shares=None, host_config=host_config)
    while True:
        try:
            sys.stderr.write('inspect\n')
            client.inspect_container(container_name)
            break
        except APIError:
            sys.stderr.write('container not ready')
            time.sleep(0.1)
    try:
        fail = False
        sys.stderr.write('start\n')
        client.start(container_name)
        try:
            sys.stderr.write('stop\n')
            client.stop(container_name)
        except APIError as e:
            if e.response.status_code == 404:
                sys.stderr.write(
                    'Stop returned 404\n===\n%s\n===\n' % e.explanation)
                fail = True
            else:
                raise

        running = True
        while running:
            # If above raises APIError, we would expect the following to raise APIError
            sys.stderr.write('inspect\n')
            result = client.inspect_container(container_name)
            running = result['State']['Running']
            sys.stderr.write('%s\n' % running)
            time.sleep(0.1)

        # So if we get here and fail is True, we have a problem!
        if fail:
            sys.stderr.write('Problem occurred!\n')
            sys.exit(1)
    finally:
        # Try to cleanup
        client.remove_container(container_name)


def main():
    count = 0
    while True:
        count += 1
        sys.stderr.write('%d...' % count)
        f()


if __name__ == '__main__':
    main()

```
- Run the commands:
```
sudo yum install -y docker-io
sudo systemctl start docker.service
sudo yum install -y python-pip
sudo pip install docker-py==0.7.1
sudo docker pull busybox
sudo setenforce 0
sudo python waittest.py
```

Actual Results:

This usually stops after a few iterations (typically less than 10) indicating that the `stop` returned with 404 but the subsequent `inspect_container` returns OK. e.g.:

```
2015-05-08 13:48:53,115 DEBUG Added a stderr logging handler to logger: requests.packages.urllib3
1...create
2015-05-08 13:48:53,402 DEBUG "POST /run/docker.sock/v1.16/containers/create?name=test1 HTTP/1.1" 201 90
inspect
2015-05-08 13:48:53,405 DEBUG "GET /run/docker.sock/v1.16/containers/test1/json HTTP/1.1" 200 1765
start
2015-05-08 13:48:53,585 DEBUG "POST /run/docker.sock/v1.16/containers/test1/start HTTP/1.1" 204 0
stop
2015-05-08 13:48:53,606 DEBUG "POST /run/docker.sock/v1.16/containers/test1/stop?t=10 HTTP/1.1" 404 45
Stop returned 404
===
Cannot stop container test1: no such process
===
inspect
2015-05-08 13:48:53,613 DEBUG "GET /run/docker.sock/v1.16/containers/test1/json HTTP/1.1" 200 None
True
inspect
2015-05-08 13:48:58,702 DEBUG "GET /run/docker.sock/v1.16/containers/test1/json HTTP/1.1" 200 None
False
Problem occurred!2015-05-08 13:49:00,013 DEBUG "DELETE /run/docker.sock/v1.16/containers/test1?link=False&force=False&v=False HTTP/1.1" 204 0
```

Server log file contains:
```
May  8 14:32:59 localhost docker: time="2015-05-08T14:32:59Z" level="info" msg="POST /v1.17/containers/test1/stop?t=10"
May  8 14:32:59 localhost docker: time="2015-05-08T14:32:59Z" level="info" msg="+job stop(test1)"
May  8 14:32:59 localhost docker: time="2015-05-08T14:32:59Z" level="info" msg="Failed to send SIGTERM to the process, force killing"
May  8 14:32:59 localhost docker: Cannot stop container test1: no such process
May  8 14:32:59 localhost docker: time="2015-05-08T14:32:59Z" level="info" msg="-job stop(test1) = ERR (1)"
May  8 14:32:59 localhost docker: time="2015-05-08T14:32:59Z" level="error" msg="Handler for POST /containers/{name:.*}/stop returned error: Cannot stop container test1: no such process"
May  8 14:32:59 localhost docker: time="2015-05-08T14:32:59Z" level="error" msg="HTTP Error: statusCode=404 Cannot stop container test1: no such process"
```

Expected Results:

The script should iterate forever, displaying an incrementing count at the start of each cycle.

**Comment by runcom** [comment]
seems like the http request for start is done but by the time you call stop it isn't really started

**Comment by jongiddy** [comment]
The container does get stopped, so the stop call is effective. Hence, I think 404 is an incorrect error code. The container to be stopped is found - whether the underlying process is found is leaking into the status of stopping the container.

Another interesting aspect: the log message in `killPossiblyDeadProcess` does not appear, even though the error message that propagates is "no such process".  Maybe the check `err == syscall.ESRCH` is not correctly catching the actual error associated with a non-existing process?

**Comment by runcom** [comment]
@jongiddy that's seems to be the problem here, the httpError function in server will transform to status 404 if the error returned by a controller contains "no such" also, hence that status..
It's really weird `err == syscall.ESRCH` is false

something kinda related https://code.google.com/p/go/issues/detail?id=7658&can=1&q=esrch&colspec=ID%20Status%20Stars%20Release%20Owner%20Repo%20Summary

**Comment by thaJeztah** [comment]
> the httpError function in server will transform to status 404 if the error returned by a controller contains "no such" also, hence that status..

@duglin is working to make that less brittle in https://github.com/docker/docker/pull/9509

**Comment by runcom** [comment]
@thaJeztah yup. Here the problem seems to be that ESRCH errno should be catched and it isn't for some reason (to my best knowledge)

**Comment by thaJeztah** [comment]
@runcom If that's the issue that's causing this; I see that issue is moved here; https://github.com/golang/go/issues/7658 an should be solved in Go 1.4. IIRC "master" dropped Go 1.3 and is built using Go 1.4, so I wonder if this is still reproducible on master (https://master.dockerproject.com)

**Comment by runcom** [comment]
@thaJeztah that was not the issue, just something related that made me think something wrong with errno is happening, I don't have really investigated this but I'll do asap. @jongiddy do you have any chance to run the master binary?

**Comment by jongiddy** [comment]
`docker version`:
Client version: 1.7.0-dev
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): a5007e5
OS/Arch (client): linux/amd64                          
Server version: 1.7.0-dev
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): a5007e5
OS/Arch (server): linux/amd64

`docker info`:
Containers: 0
Images: 3
Storage Driver: vfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.11.10-301.fc20.x86_64
Operating System: Fedora 20 (Heisenbug)
CPUs: 1
Total Memory: 3.662 GiB
Name: ip-172-31-12-145
ID: FTVB:HG2E:R6RQ:XGEX:FZYW:ZE7N:NCQS:KVGR:EAJL:KCYI:UWVL:ASYX

`uname -a`:
Linux ip-172-31-12-145 3.11.10-301.fc20.x86_64 #1 SMP Thu Dec 5 14:01:17 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

Everything else as above, but run commands:
```
curl --output docker https://master.dockerproject.com/linux/amd64/docker
chmod 755 docker
sudo ./docker -d &
sudo yum install -y python-pip
sudo pip install docker-py==1.2.2
sudo ./docker pull busybox
sudo setenforce 0
sudo python waittest.py
```

Output is different, but not in a good way: now gives 500 instead of 404:
```
11...create
INFO[0272] POST /v1.18/containers/create?name=test1     
2015-05-12 08:02:26,359 DEBUG "POST /v1.18/containers/create?name=test1 HTTP/1.1" 201 90
inspect
INFO[0272] GET /v1.18/containers/test1/json             
2015-05-12 08:02:26,362 DEBUG "GET /v1.18/containers/test1/json HTTP/1.1" 200 1879
start
INFO[0272] POST /v1.18/containers/test1/start           
2015-05-12 08:02:26,494 DEBUG "POST /v1.18/containers/test1/start HTTP/1.1" 204 0
stop
INFO[0272] POST /v1.18/containers/test1/stop?t=10       
INFO[0272] Failed to send SIGTERM to the process, force killing 
ERRO[0272] Handler for POST /containers/{name:.*}/stop returned error: Cannot stop container test1: [2] Container does not exist: container destroyed
 
ERRO[0272] HTTP Error                                    err=Cannot stop container test1: [2] Container does not exist: container destroyed
 statusCode=500
2015-05-12 08:02:26,510 DEBUG "POST /v1.18/containers/test1/stop?t=10 HTTP/1.1" 500 80
INFO[0272] DELETE /v1.18/containers/test1?link=False&force=False&v=False 
2015-05-12 08:02:26,550 DEBUG "DELETE /v1.18/containers/test1?link=False&force=False&v=False HTTP/1.1" 204 0
Traceback (most recent call last):
  File "waittest.py", line 72, in <module>
    main()
  File "waittest.py", line 68, in main
    f()
  File "waittest.py", line 36, in f
    client.stop(container_name)
  File "/usr/lib/python2.7/site-packages/docker/utils/decorators.py", line 15, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 1085, in stop
    self._raise_for_status(res)
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 122, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("Cannot stop container test1: [2] Container does not exist: container destroyed")
```

**Comment by exarkun** [comment]
Any further thoughts on this?

**Comment by icecrime** [comment]
Hello! Can you please let us know if this is still happening on recent Docker version? Thanks a lot!

**Comment by thaJeztah** [comment]
I'll go ahead and close, but happy to reopen if this is still an issue
