### ISSUE TITLE
Repository incorrectly parsed when a digest is provided

### ISSUE THREAD

**Issue by stevvooe** [docker/docker#13083]
Docker fails to run the following:

```
$ docker run -it golang:1.4.2@sha256:6efc7717226ae757dbe3dc1f629cd06cf8bf736a5fbdfb3bae738d602d15c003
Unable to find image 'golang:1.4.2@sha256:6efc7717226ae757dbe3dc1f629cd06cf8bf736a5fbdfb3bae738d602d15c003' locally
FATA[0000] Invalid repository name (golang:1.4.2), only [a-z0-9-_.] are allowed
```

I would expect this to correctly parse the the repo, tag and digest into separate components. When selecting the image, it should ignore the tag portion and run as if passed `golang@sha256:6efc7717226ae757dbe3dc1f629cd06cf8bf736a5fbdfb3bae738d602d15c003`.

```
$ docker info
Containers: 3
Images: 423
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 429
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.18.11-tinycore64
Operating System: Boot2Docker 1.6.0 (TCL 5.4); master : a270c71 - Thu Apr 16 19:50:36 UTC 2015
CPUs: 8
Total Memory: 1.961 GiB
Name: boot2docker
ID: NG2P:MYSI:J7YO:PXLA:ZTBL:JAVV:IBYU:R3L5:S5HX:LKM6:T4LA:DFTO
Debug mode (server): true
Debug mode (client): false
Fds: 13
Goroutines: 18
System Time: Fri May  8 06:11:01 UTC 2015
EventsListeners: 0
Init SHA1: 9145575052383dbf64cede3bac278606472e027c
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: sday
Registry: [https://index.docker.io/v1/]
```

cc @ncdc @dmcgowan

**Comment by ncdc** [comment]
@stevvooe the `<repo>:<tag>@<digest>` format was one that we had discussed while this feature was in development. IIRC, we originally were looking at using this, but we decided that the housekeeping required to keep the links between tags and revisions was more trouble than it was worth.

Let's say that this format was allowed. If I ran the following commands:

```
docker push foo/bar:latest
# returns Digest=D1

docker push foo/bar:other
# returns Digest=D2
```

Should it be possible to do `docker pull foo/bar:latest@D2` or `docker pull foo/bar:other@D1`?

**Comment by stevvooe** [comment]
The primary reason I opened this ticket is the error message:

```
FATA[0000] Invalid repository name (golang:1.4.2), only [a-z0-9-_.] are allowed
```

This tells me we are making some odd assumptions in the parser.

> Should it be possible to do docker pull foo/bar:latest@D2 or docker pull foo/bar:other@D1?

@ncdc Perhaps. That is partially while I opened this ticket. Having the digest without the tag makes understanding where that digest may have come from harder. The other possibility is that the runner ensures that the tag has that digest.

**Comment by ncdc** [comment]
Agreed about the parser and the error. I think the way I wrote it, if the name has @, it splits and treats the 1st part as the repo name, which is why you'd see the tag showing up in the error.

You had some concerns about the housekeeping required in the registry to keep track of tag@revision, right? Also, the TagStore would require some significant (and potentially breaking) changes to support keeping track of multiple digests per tag.

**Comment by LK4D4** [comment]
@stevvooe @aaronlehmann what's up here?

**Comment by stevvooe** [comment]
Seems to work correctly:

```console
$ docker run -it golang:1.4.2@sha256:6efc7717226ae757dbe3dc1f629cd06cf8bf736a5fbdfb3bae738d602d15c003 sh
zsh: correct docke to docker [nyae]? y
Unable to find image 'golang@sha256:6efc7717226ae757dbe3dc1f629cd06cf8bf736a5fbdfb3bae738d602d15c003' locally

sha256:6efc7717226ae757dbe3dc1f629cd06cf8bf736a5fbdfb3bae738d602d15c003: Pulling from library/golang
7bdbf7d44e96: Pull complete
a3ed95caeb02: Pull complete
0031c763245c: Pull complete
d8d443e53ec2: Pull complete
dd53cb3268f0: Pull complete
df8fde8bb9c5: Pull complete
624dd595e975: Pull complete
bf048c661b7e: Pull complete
5e5602b8ec15: Pull complete
Digest: sha256:6efc7717226ae757dbe3dc1f629cd06cf8bf736a5fbdfb3bae738d602d15c003
Status: Downloaded newer image for golang@sha256:6efc7717226ae757dbe3dc1f629cd06cf8bf736a5fbdfb3bae738d602d15c003
#
#

Although, the tag is not picked up, which may be the right thing:

```console
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
docker-dev          master              142d45a55f79        5 days ago          2.611 GB
debian              jessie              031143c1c662        2 weeks ago         125.1 MB
redis               alpine              60d5af14b41c        2 weeks ago         21.03 MB
redis               <none>              5bd8336e208d        2 weeks ago         29.67 MB
alpine              latest              4e38e38c8ce0        11 weeks ago        4.799 MB
golang              <none>              44497aaab145        16 months ago       517.2 MB
```

I think we can close this.
