### ISSUE TITLE
[Feature] docker logs --head

### ISSUE THREAD

**Issue by MrMMorris** [docker/docker#13096]
We have --tail but not --head for whatever reason.

This is useful for something like mongoDB where there is a lot of valuable startup info when the container starts, but a LOT of repeated, less useful logs after. If startup fails and I can't look at the logs for a while, I have to risk filling up my screen with every log since startup and then scroll alllllll the way to the beginning to find what I need....

**Comment by thaJeztah** [comment]
Sounds reasonable, given the use case you're describing. (Slightly) related PR; https://github.com/docker/docker/pull/12362

cc @LK4D4

**Comment by phemmer** [comment]
what about using the `head` or `less` utilities? Do we really need to re-invent this within docker?

**Comment by MrMMorris** [comment]
oh.... :blush: I guess `head` does the job too. I guess I just assumed it wouldn't work for some reason and that's why we had `--tail`

...

why do we have `--tail`?

**Comment by LK4D4** [comment]
Because tail won't allow you to follow logs.

**Comment by bo0ts** [comment]
I think that would still be valuable for APIs. I have some useful output at the beginning of a container and extract it with `docker-py`. Currently I stream the logs to avoid reading the entire log to begin with, but this requires me to check that the container is actually stopped so I don't stream forever if the container didn't produce the expected output for whatever reason. `--head` would solve that nicely.

**Comment by schrieveslaach** [comment]
I'm using dockers REST API through the [`shiplift`](https://github.com/softprops/shiplift) crate and in my use case I need to look into the first 1000 loglines. However, is this possible without the head option? Currently I have to wait for all log messages to be processed which is quite slow.

**Comment by schrieveslaach** [comment]
In https://github.com/aixigo/PREvant/pull/12 it would improve the performance of the REST API when docker's REST API would support the equivalent of the following command. 

```
docker logs [CONTAINER] --since [TIMESTAMP] --head [NUMBER]
```

Do you have any plans to support this?

**Comment by thiagolsfortunato** [comment]
solve to me :smile: 
```
docker logs [container] | head [number] 
```

**Comment by mlaass** [comment]
> solve to me 
> 
> ```
> docker logs [container] | head [number] 
> ```

This does not work for me, for whatever reason, it prints the entire log as if the pipe didn't exist

**Comment by thaJeztah** [comment]
@mlaass if you have steps to reproduce, best to open a ticket with details.

I did a quick check, and it still works for me;

```bash
docker run -d --name foo alpine sh -c 'while true; do date; sleep 1; done'
```


```bash
docker logs foo
Tue Aug 10 11:13:41 UTC 2021
Tue Aug 10 11:13:42 UTC 2021
Tue Aug 10 11:13:43 UTC 2021
Tue Aug 10 11:13:44 UTC 2021
Tue Aug 10 11:13:45 UTC 2021
Tue Aug 10 11:13:46 UTC 2021
Tue Aug 10 11:13:47 UTC 2021

docker logs foo | head -n3
Tue Aug 10 11:13:48 UTC 2021
Tue Aug 10 11:13:49 UTC 2021
Tue Aug 10 11:13:50 UTC 2021
```

**Comment by mlaass** [comment]
Ok I tried your example, it works for me. But not, when I use the following command:
`docker run -d --name tensorflow --gpus all -p 8888:8888 -v /home/moritz/tf:/tf tensorflow/tensorflow:latest-gpu-jupyter`

`docker logs tensorflow | head -n2
[I 19:58:18.333 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[I 19:58:18.529 NotebookApp] Serving notebooks from local directory: /tf
[I 19:58:18.529 NotebookApp] Jupyter Notebook 6.1.4 is running at:
[I 19:58:18.529 NotebookApp] http://3f92e4662fdd:8888/?token=b3d2aadbea25c8374ff44eb2993f7867ffb86f1d9e8bc26f
[I 19:58:18.529 NotebookApp]  or http://127.0.0.1:8888/?token=b3d2aadbea25c8374ff44eb2993f7867ffb86f1d9e8bc26f
[I 19:58:18.529 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 19:58:18.532 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/nbserver-1-open.html
    Or copy and paste one of these URLs:
        http://3f92e4662fdd:8888/?token=b3d2aadbea25c8374ff44eb2993f7867ffb86f1d9e8bc26f
     or http://127.0.0.1:8888/?token=b3d2aadbea25c8374ff44eb2993f7867ffb86f1d9e8bc26f
[I 19:59:11.490 NotebookApp] 302 GET /?token=b3d2aadbea25c8374ff44eb2993f7867ffb86f1d9e8bc26f (178.7.109.86) 1.89ms`

**Comment by thaJeztah** [comment]
Ah! Quite likely it's printing to `STDERR`, and my example doesn't redirect, so only takes the `head` of `STDOUT` (keeping `STDERR` as-is);

Container that prints to both `STDERR` and `STDOUT`:

```bash
docker run -d --name foo alpine sh -c 'while true; do 1>&2 echo "STDERR"; echo "STDOUT"; sleep 1; done'
```

logs:

```bash
docker logs foo
STDOUT
STDERR
STDOUT
STDERR
STDOUT
STDOUT
STDERR
STDERR
STDOUT
```

And using `head` after redirecting `STDERR` to `STDOUT` (combining them) with `2>&1`;

```bash
docker logs foo 2>&1 | head -n2
STDERR
STDOUT
```

**Comment by matletix** [comment]
You can use 

`docker logs foo |& head`

**Comment by matletix** [comment]
@thaJeztah right, `|&` is simply a shorthand for `2>&1 |`. It's not supported by `/bin/sh` but works well with `bash`, `csh`, `zsh` and maybe others.

**Comment by VajiraPrabuddhaka** [comment]
> solve to me smile
> 
> ```
> docker logs [container] | head [number] 
> ```

This should be modified as follows: 
```bash
docker logs [container] | head -n 100
```

This worked for me.
