### ISSUE TITLE
Ec2 Centos7 + Docker 1.6

### ISSUE THREAD

**Issue by zaidiahmed** [docker/docker#13098]
Docker version 1.6.1, build 97cd073
CentOs7 in EC2
Packer + Chef

I am using packer to provision an AMI with a base Centos7 ami, I am using chef to setup my Image.

The issue I am running has to do with permissions on the docker.sock
`srw-rw---- 1 root root 0 May  8 21:47 /var/run/docker.sock`

I do not want to leave my instance wide open so I have created a user without sudo rights and added the user to the dockerroot group `dockerroot:x:995:myuser`.  How do I handle docker.sock being owned by root user and root group?

I have tried to do a chown command through chef, I have tried adding a chown in the rc.local to handle this on every reboot.  

I want to 
`chown root:dockerroot /var/run/docker.sock` 

you can reproduce this by running my chef script

```
when "rhel"
 package "docker"
 package "wget"

 execute 'get-docker-1.6' do
  command'wget https://get.docker.com/builds/Linux/x86_64/docker-latest -O /usr/bin/docker'
  user 'root'
  group 'dockerroot'
 end

 execute 'run-docker-service' do
  command 'systemctl enable docker.service'
  user 'root'
  group 'dockerroot'
 end

 execute 'start-docker-service' do
  command 'systemctl start docker.service'
  user 'root'
  group 'dockerroot'
 end
```

any help on the matter will be appreciated.

**Comment by jfrazelle** [comment]
on centos you cannot use the static binary you need to use the dynamic binary, this is brought up in several other issues, the version of udev needs to be insync with the binary being used, so this will not work, we are going to have our rpms ready for 1.7 so you can use those

**Comment by zaidiahmed** [comment]
Would you be so kind to link me to "several other issues" please.

**Comment by velichkov** [comment]
> I do not want to leave my instance wide open so I have created a user without sudo rights and added the user to the dockerroot group dockerroot:x:995:myuser. How do I handle docker.sock being owned by root user and root group?

The solution that works for me on centos7 and docker-1.6.0 from CentOS-Extras repository is to add '-G dockerroot ' to OPTIONS in /etc/sysconfig/docker

```
$ grep OPTIONS /etc/sysconfig/docker
OPTIONS='--selinux-enabled -G dockerroot'
```

**Comment by nxadm** [comment]
@velichkov Thx, that did the trick.

C.
