### ISSUE TITLE
Windows Installation step 2 has a typo

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#13109]
Windows installation step 2 has a typo change "or Windows" to "for Windows"

**Comment by bharaththiruveedula** [comment]
@moxiegirl, it was there in https://github.com/docker/docker/blob/949b929a328301a762dadf423ef6a01f83971d7c/docs/sources/installation/windows.md

**Comment by moxiegirl** [comment]
Thanks for the update @bharaththiruveedula

**Comment by jhowardmsft** [comment]
This can be closed. Was fixed by commit 3cdf94ed1a8a63c068e17310ffa764230b280cbe

**Comment by thaJeztah** [comment]
Thanks for paying attention, @jhowardmsft!
