### ISSUE TITLE
Proposal: Duration strings as inputs to logs/events (e.g. --since=1h)

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/docker#13107]
Some docker commands like `docker events` or `docker logs`(#12362) accept `--since` or `--until` parameters to filter events out. Although these methods accept either RFC3339 timestamps or Unix epoch times.

I can hardly imagine anybody trying to take a look into their container's past hour's logs sitting down and writing a command like :

    docker logs \
        --since=(oh what's the time now)2015-05-09T13:00:00(I hope format is correct )\
        mycontainer 

Therefore I propose `time.Duration` inputs in these commands such as:

    docker logs --since=1h mycontainer
    docker events --since=1d --until=5m

The way that's gonna work is instead of trying to parse specified string into RFC3339 first and then falling back to epoch, we will also try parsing with `time.ParseDuration` (see `pkg/timeutils/utils.go#GetTimestamp` I submitted at #12362).

Once the duration is parsed, it will be subtracted from `time.Now()` and will be converted to Unix epoch time (as the Remote API requires) and that value will be sent. Assumption here is time drift between client vs server is minimal<sup>1</sup>. Therefore when the durations are used the duration will be relative to client machine's time (different behavior than providing epoch or RFC3339 value).

<sup>1</sup>: [citation needed] lol.  Computers connected to internet have pretty precise clocks these days, give or take 5-10 secs max, but I don't expect anybody to use durations for precise timing on the engine-side. This is more for “usability”.

**Comment by thaJeztah** [comment]
+1 looks a lot more usable

**Comment by ahmetalpbalkan** [comment]
ping to get more attention

**Comment by thaJeztah** [comment]
@ahmetalpbalkan IRC might work better, but don't overdo it, or your nickname will become "Clippy" :smile:

**Comment by cpuguy83** [comment]
+1 this is reasonable to me

**Comment by ahmetalpbalkan** [comment]
Added a PR about this: #13165 please review.
