### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by joda70** [docker/docker#13118]
I am using docker 1.5.0 on CENTOS 7.
docker-1.5.0-28.el7.centos.x86_64

I run the container as follows:
docker run -v /opt/:/reg  -i -t centos /bin/bash

Then:
[root@172ed85bc401 /]# touch /reg/pipp.txt
touch: cannot touch '/reg/pipp.txt': Permission denied

The same error in the following case:

docker run -v /opt/:/reg -v /etc/group:/etc/group -v /etc/passwd:/etc/passwd --user 1001:1001 -i -t centos /bin/bash

bash-4.2$ id registry
uid=1001(registry) gid=1001(registry) groups=1001(registry)
bash-4.2$ touch /reg/pipp.txt
touch: cannot touch '/reg/pipp.txt': Permission denied

**Comment by joda70** [comment]
docker version:
Client version: 1.5.0-dev
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): fc0329b/1.5.0
OS/Arch (client): linux/amd64
Server version: 1.5.0-dev
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): fc0329b/1.5.0
OS/Arch (server): linux/amd64

docker info:
Containers: 15
Images: 22
Storage Driver: devicemapper
 Pool Name: docker-253:1-17648601-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.117 GB
 Data Space Total: 107.4 GB
 Data Space Available: 106.3 GB
 Metadata Space Used: 2.454 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Kernel Version: 3.10.0-123.9.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 3.704 GiB
Name: docker
ID: 32NL:KLKJ:G4PQ:N7T2:JBCO:IZQ3:DQIH:RGAV:3H6Q:5BJW:4IE4:RVN5

uname -a:
Linux caio 3.10.0-123.9.3.el7.x86_64 #1 SMP Thu Nov 6 15:06:03 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Env. details physical:?

How reproducible:

1. docker run centos
2. mkdir -p /tmp/pp
3. docker run -v /tmp/:/tmp -i -t centos /bin/bash
mktemp: failed to create file via template '/tmp/.colorlsXXX': Permission denied
bash: $TMP: ambiguous redirect
[root@192ffcfb1a83 /]# ls -al /tmp/
ls: cannot open directory /tmp/: Permission denied

**Comment by joda70** [comment]
It is quite curious because on ubuntu 
uname -a
Linux xxxx 3.11.0-26-generic #45-Ubuntu SMP Tue Jul 15 04:02:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

by using 

docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

docker info
Containers: 34
Images: 210
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 278
Execution Driver: native-0.2
Kernel Version: 3.11.0-26-generic
Operating System: Ubuntu 13.10
CPUs: 2
Total Memory: 3.582 GiB
Name: macjoda
ID: G7AX:XWRP:MSUG:K6Y6:6HTX:LAY5:RSOT:E4MO:5XVQ:RONQ:ZBMV:ECUA
Username: joda70
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support


I was able to create a file in the volume as shown below:

 docker run  --name prova1 -i -t -v /root/joda:/tmp centos /bin/bash
[root@5464fd146123 /]# ls /tmp/
[root@5464fd146123 /]# cd /tmp/
[root@5464fd146123 tmp]# touch pap.txt
[root@5464fd146123 tmp]# ls
pap.txt

**Comment by cpuguy83** [comment]
This is due to SELinux enforcement.
You'll need to run `chcon` on the host dir to set the SELinux label correctly.

Closing since this is a non-issue.
