### ISSUE TITLE
Ignore file extension in all folders with .dockerignore

### ISSUE THREAD

**Issue by Ralle** [docker/docker#13113]
I added *.DS_Store to my .dockerignore file but that only ignores the file in the build directory not in the following sub directories. I have also tried the same with *.pyc to no avail.

I took a look at the Go Match function ( http://golang.org/pkg/path/filepath/#Match ) and as far as I can tell, *.DS_Store would match any path that ends with .DS_Store, but in Docker it doesn't.

I am running Docker version 1.6.0, build 4749651 on Mac OS X using Boot2Docker version v1.6.0.

Description of problem:

`docker version`:
Docker version 1.6.0, build 4749651

`docker info`:
Containers: 13
Images: 232
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 258
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.18.11-tinycore64
Operating System: Boot2Docker 1.6.0 (TCL 5.4); master : a270c71 - Thu Apr 16 19:50:36 UTC 2015
CPUs: 4
Total Memory: 494.6 MiB
Name: boot2docker
ID: PDMU:VKYP:RD7V:VCTH:AARC:PHZG:FTQF:7A55:MWCO:TJIJ:Z6X2:3IXK
Debug mode (server): true
Debug mode (client): false
Fds: 32
Goroutines: 49
System Time: Sun May 10 09:33:09 UTC 2015
EventsListeners: 0
Init SHA1: 9145575052383dbf64cede3bac278606472e027c
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: ralle
Registry: [https://index.docker.io/v1/]

`uname -a`:
Darwin Rosa.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

Environment details (AWS, VirtualBox, physical, etc.):
Boot2Docker

How reproducible:
Every time

Steps to Reproduce:
Add *.DS_Store to .dockerignore file, and see how sub folder .DS_Store files aren't ignored.

Actual Results:
.DS_Store files in sub folders are added.

Expected Results:
.DS_Store files in all sub folders are ignored.

Additional info:

**Comment by duglin** [comment]
From looking at the the testcases for Match() itself ( https://golang.org/src/path/filepath/match_test.go ) I'm pretty sure it doesn't support mutliple levels of dirs w/o you being explicit about them.

**Comment by Ralle** [comment]
In any case, I think we should have a feature permitting any-depth filename matching. Go's Match() seems way too underpowered compared to the ignore capabilities of for example Git's system.

**Comment by pnovotnak** [comment]
Bump. Can we make it work the same way .gitignore does? I'm not trying to create a million .dockerignore files for each directory or a pattern for each level... Neither make sense to me.

**Comment by yourteamneedsadam** [comment]
As a Python user this would be great to have. Right now I have to do things like this:

```
*.pyc
*/*.pyc
*/*/*.pyc
...
```

And continue the pattern to twice the depth I think the project will ever reach, otherwise it's too easy to forget to add another line to the `.dockerignore` when doing routine things like expanding packages.

**Comment by spg** [comment]
+1, this would be nice

**Comment by laurrentt** [comment]
+1, I would love to see this disappear from my code base:
 ```
+*/*.pyc
+*/*/*.pyc
+*/*/*/*.pyc
+*/*/*/*/*.pyc
+*/*/*/*/*/*.pyc
+*/*/*/*/*/*/*.pyc
+*/*/*/*/*/*/*/*.pyc
+*/*/*/*/*/*/*/*/*.pyc
+*/*/*/*/*/*/*/*/*/*.pyc
```

**Comment by dbrgn** [comment]
+1
+*/1
+*/*/1
+*/*/*/1
+*/*/*/*/1

**Comment by sroze** [comment]
That is definitely a great to have!

**Comment by javierbq** [comment]
+1

**Comment by jbarlow83** [comment]
+1. I'm beginning to think that Docker is imitating PHP: the principle of maximum surprise - do whatever is unexpected, unconventional and internally inconsistent. Like have a .dockerignore that almost works like .gitignore, except that it doesn't in a key use case that's really easy to solve.

**Comment by thaJeztah** [comment]
> except that it doesn't in a key use case that's really easy to solve.

Feel free to create a pull-request, but you may want to pay attention to https://github.com/docker/docker/issues/13113#issuecomment-100626208, because Go doesn't support this by default. Also see some prior discussion on making it act more like gitignore; https://github.com/docker/docker/issues/9171, and a PR to implement that https://github.com/docker/docker/pull/12245

**Comment by duglin** [comment]
Will probably be issuing a PR today or tomorrow, but I wouldn't mind if someone could look at this https://github.com/duglin/docker/commit/1c4065431ee87cdb9e656500272e3bf70b9abc11  and see if it works ok.  The idea here was to be backwards compatible with golang Match() function but to also support any number of dirs by having the user specify `**` in the pattern.

For example: `**/*.txt` should find all txt files in all dirs.

**Comment by thaJeztah** [comment]
Thanks @duglin :)

**Comment by Ralle** [comment]
Wow, this sounds great!

**Comment by curtisz** [comment]
Phenomenal timing! Thanks :)

**Comment by curtiszimmerman** [comment]
Phenomenal timing! Thanks!

**Comment by duglin** [comment]
PR https://github.com/docker/docker/pull/17090

**Comment by jakirkham** [comment]
Sounds really cool. Will this make it into 1.9.0? It looks like it is close to ready.

**Comment by thaJeztah** [comment]
@jakirkham unfortunately, we're in code/feature freeze for 1.9 already, so this'll have to wait for 1.10 (and YES, we all want it :))

**Comment by duglin** [comment]
I agree its close to being ready but I still need to add more integrations test before I'm comfortable with it.  Should be any day now.... just been kind of busy.

**Comment by jakirkham** [comment]
That's fine. I'm patient. I'd rather see a stable feature enter than discover some surprises.

**Comment by BryanConradHart** [comment]
Does this work with directory matching?
I'm trying to do **/node_modules and I'm still seeing them get copied into my image

**Comment by cnlzxin** [comment]
use `**/*.pyc`

refer to [Docker ignores patterns in .dockerignore
](https://stackoverflow.com/questions/40261164/docker-ignores-patterns-in-dockerignore)

**Comment by Qix-** [comment]
Why wasn't the .gitignore pattern used? It's familiar and expected since `.dockerignore` is imitating both that format and the naming convention.

Further, Docker should follow symlinks - that would make `ln -s .gitignore .dockerignore` a much easier and more maintainable alternative to maintaining two lists for many projects that do not have git/docker-specific ignores.

**Comment by liaogz82** [comment]
I agree. I can ignore all `.DS_Store` in .gitignore but I have to add the extra `**/` in .dockerignore. I can save 2 characters.
