### ISSUE TITLE
Production-ready process monitoring

### ISSUE THREAD

**Issue by shykes** [docker/docker#1311]
For docker to be fully usable in production, we need a robust and standard way to do the following:

1. Auto-restart some long-running processes if they crash

2. Auto-start some processes at system startup

3. Send arbitrary signals to processes

This could be implemented in different ways:

- Option 1 is to implement these features directly in docker, and monitor docker with the host's init process. This is discussed in #26 and #230.

- Option 2 is to modify the docker client to behave as a "proxy" to the process it has remotely started, and have the host's init process monitor each instance of the docker client independently. This is the focus of the "dockrun" script by @backjlack, which he is currently working to merge into docker: #507, #1159 and more pull requests to come. 

- Option 3 is similar to option 2, except that "docker run" would be modified to be *standalone*: instead of starting the process remotely via the docker daemon, it would fork/exec itself and monitor its own child process (similarly to chroot). This is discussed in #503.

**Comment by cpuguy83** [comment]
Cleaning this one up since the restart policies and docker client signal proxying handle this.

**Comment by unclejack** [comment]
This should stay open because we don't have single process monitoring (e.g. starting and running a container without the docker cli/daemonless run).
