### ISSUE TITLE
out rpm + selinux

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#13128]
our rpm does have seamless networking out of the box when `--enable-selinux` is used

ping @rhatdan @vbatts  because this is so beyond my level of understanding

also  ping @pdevine who found this and has a work around i believe 

(docker info, docker version, uname -a so gordon doesnt yell at me)

**Comment by jfrazelle** [comment]
right now it works out of the box without selinux

**Comment by rhatdan** [comment]
U have no idea what you are asking for?

**Comment by jfrazelle** [comment]
Soooo when we run the daemon `--selinux-enabled` and our rpm (here is spec https://github.com/docker/docker/blob/master/hack/make/.build-rpm/docker-engine.spec)
you cannot ping, or get networking in a container to work

**Comment by jfrazelle** [comment]
and looking at the fedora and centos spec for docker-io, I have no idea what type of finaglery they are doinng

**Comment by rhatdan** [comment]
This is because the patch to fix the labels on /etc/resolv.conf, /etc/hostsname and /etc/hosts keeps being removed.

**Comment by rhatdan** [comment]
It is part of my selinux patch that you took over, but it has gotten merged into docker before and was dropped for some reason.
 
 func (container *Container) specialMounts() []execdriver.Mount {
        var mounts []execdriver.Mount
        if container.ResolvConfPath != "" {
+               label.SetFileLabel(container.ResolvConfPath, container.MountLabel)
                mounts = append(mounts, execdriver.Mount{Source: container.ResolvConfPath, Destination: "/etc/resolv.conf", Writable: !container.hostConfig.ReadonlyRootfs, Private: true})
        }
        if container.HostnamePath != "" {
+               label.SetFileLabel(container.HostnamePath, container.MountLabel)
                mounts = append(mounts, execdriver.Mount{Source: container.HostnamePath, Destination: "/etc/hostname", Writable: !container.hostConfig.ReadonlyRootfs, Private: true})
        }
        if container.HostsPath != "" {
+               label.SetFileLabel(container.HostsPath, container.MountLabel)
                mounts = append(mounts, execdriver.Mount{Source: container.HostsPath, Destination: "/etc/hosts", Writable: !container.hostConfig.ReadonlyRootfs, Private: true})

**Comment by jfrazelle** [comment]
ah i  see ok we have that PR open for 1.7 and I will rebase on michaels
volumes PR, thanks :)
