### ISSUE TITLE
Silence GET requests from daemon logs

### ISSUE THREAD

**Issue by sdodson** [docker/docker#13120]
Platforms like kubernetes make quite a few GET requests of the API, often dozens per second, so many that journald drops messages. Could we consider a knob to silence non error GET requests from daemon logs at info level?

**Comment by thaJeztah** [comment]
@LK4D4 any thoughts on this?

**Comment by duglin** [comment]
@sdodson just wondering, what "INFO" level data from the logs do you need that would prevent you from just running with "--log-level warn" ?

**Comment by sdodson** [comment]
@duglin I initially thought it'd be useful to see all write operations still logged so I could trace updaets via the API while foregoing the constant stream of container status requests. I was hoping that would be a good balance for production use.

**Comment by kwoodson** [comment]
Would also love to see who the request is coming from.  Even with debug enabled I am having difficulty tracking down the caller.


`Jul 27 09:56:43 172.16.13.25 docker[4704]: time="2015-07-27T09:56:43-04:00" level=debug msg="Calling GET /version"`
`Jul 27 09:56:48 172.16.13.25 docker[4704]: time="2015-07-27T09:56:48-04:00" level=debug msg="Calling GET /version"`
`Jul 27 09:56:53 172.16.13.25 docker[4704]: time="2015-07-27T09:56:53-04:00" level=debug msg="Calling GET /containers/json"`
`Jul 27 09:56:53 172.16.13.25 docker[4704]: time="2015-07-27T09:56:53-04:00" level=debug msg="Calling GET /containers/json"`
`Jul 27 09:56:53 172.16.13.25 docker[4704]: time="2015-07-27T09:56:53-04:00" level=debug msg="Calling GET /containers/json"`
`Jul 27 09:56:53 172.16.13.25 docker[4704]: time="2015-07-27T09:56:53-04:00" level=debug msg="Calling GET /containers/json"`
`Jul 27 09:56:53 172.16.13.25 docker[4704]: time="2015-07-27T09:56:53-04:00" level=debug msg="Calling GET /containers/json"`
`Jul 27 09:56:53 172.16.13.25 docker[4704]: time="2015-07-27T09:56:53-04:00" level=debug msg="Calling GET /containers/json"`
`Jul 27 09:56:53 172.16.13.25 docker[4704]: time="2015-07-27T09:56:53-04:00" level=debug msg="Calling GET /containers/json"`
`Jul 27 09:56:53 172.16.13.25 docker[4704]: time="2015-07-27T09:56:53-04:00" level=debug msg="Calling GET /containers/json"`

**Comment by bfirsh** [comment]
Thanks for the report @sdodson! We're aggregating daemon logging issues in https://github.com/docker/docker/issues/11621 so I'll close this and we can move the discussion there.
