### ISSUE TITLE
Cannot delete image by name if name prefixed with `-`

### ISSUE THREAD

**Issue by geek** [docker/docker#13123]
Create an image that has a name that starts with `-`, like `-i`.  You cannot delete the image by name using `rmi` but instead must use the Image ID.

**Comment by phemmer** [comment]
use `--` as the option terminator.

E.G.:

    docker rmi -- -mycontainername

**Comment by coolljt0725** [comment]
#13155  has made prevent user from tagging image use a name begin with `-`, I think this should be close. ping @thaJeztah

**Comment by runcom** [comment]
@coolljt0725 yup thanks
