### ISSUE TITLE
fix panic on tests on lxc

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#13126]
see: https://jenkins.dockerproject.com/job/Docker%20Master%20(lxc)/668/console

**Comment by LK4D4** [comment]
It's not panic, it's timeout btw :)

**Comment by thaJeztah** [comment]
> see: https://jenkins.dockerproject.com/job/Docker%20Master%20(lxc)/668/console

Hm, a gist would've been better, because that now 404's :wink:

**Comment by jfrazelle** [comment]
Actually I fixed this i think haha

**Comment by jfrazelle** [comment]
My b hahahaha

**Comment by thaJeztah** [comment]
@jfrazelle hey! You didn't #dibs it! That's not fair!
