### ISSUE TITLE
Provide new commands mount/umount

### ISSUE THREAD

**Issue by rhvgoyal** [docker/docker#13129]
Some people expressed desire to have capability to be able to quickly inspect an image. Right now one can save image content to tar file and untar it later and look into image. But taring the content creates additional copy which is slow.

Another method seems to be to create a container and then run a command inside that container. But that requires command to be present inside an image at the same time running container of image being inspected is not very clean. People argue that one does not want to run the container which is
being inspected.

So it was suggested how about implementing a new set of commands say mount/umount which just mount image read only at a given directory. That will allow host to quickly inspect image without creating copy and then unmount the image.

I am about to post a very basic patch to be able to do that. That can serve as place for discussion on this topic and how to go about solving this issue.

**Comment by ahmetalpbalkan** [comment]
@rhvgoyal I guess gordon wouldn't complain if you start title like `Proposal: `

**Comment by cpuguy83** [comment]
Closing since this was rejected some time ago here: #13130

**Comment by cpuguy83** [comment]
Shame since it seems like something could be useful for debugging purposes.

**Comment by cpuguy83** [comment]
Maybe we can open a discussion around debug tooling?

**Comment by AkihiroSuda** [comment]
I think that requirement can be implemented as `--mount type=image` (could not find the issue number.. IIUC @justincormack is proposing this 😅 ) rather than new commands

**Comment by thaJeztah** [comment]
Yes, see this issue https://github.com/docker/docker/issues/30449
