### ISSUE TITLE
/info returns Debug as an int not a bool

### ISSUE THREAD

**Issue by donhcd** [docker/docker#13139]
Description of problem:
/info api endpoint returns Debug as an int instead of bool

`docker version`:
```
$ docker version
Client API version: 1.16
Go version (client): go1.3.3
OS/Arch (client): linux/amd64
Server version: 1.6.1
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 97cd07
```

`docker info`:
```
$ docker -D info
Containers: 11
Images: 281
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 303
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-36-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 1
Total Memory: 1.955 GiB
Name: vagrant-ubuntu-trusty-64
ID: NUJZ:42WR:PCKJ:7XR2:VBGZ:PU44:C4ML:DIAQ:KP64:FV7E:TK6Y:MWP5
Debug mode (server): true
Debug mode (client): true
Fds: 38
Goroutines: 58
EventsListeners: 13
Init SHA1: 2dabfc43e5f856a0712787a6ff78ceaf791cc9e7
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker
Username: donhcd
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support
```

`uname -a`:
```
$ uname -a
Linux vagrant-ubuntu-trusty-64 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.):
vagrant/virtualbox vm

How reproducible:
100%

Steps to Reproduce:
1. `echo -e 'GET /info HTTP/1.1\r\n' | nc -U /var/run/docker.sock`

Actual Results:
`Debug` is an int

Expected Results:
`Debug` is a bool

Additional info:

looking at relevant code pieces, this seems to make sense:
https://github.com/docker/docker/blob/v1.6.1/daemon/info.go#L77 and
https://github.com/docker/docker/blob/v1.6.1/engine/env.go#L65

[the docs](https://docs.docker.com/reference/api/docker_remote_api_v1.18/#display-system-wide-information) claim that `Debug` should be a bool, and they also claim that `IndexServerAddress` is `[]string` when it is actually just `string`.

**Comment by runcom** [comment]
@donhcd Thanks for this, also ` "IPv4Forwarding": 1` should be a bool but it's an int, I'm looking into this

**Comment by HuKeping** [comment]
I can confirm what @runcom said, it is `bool` on master.

I checked it on commit 340fd14

**Comment by thaJeztah** [comment]
If the (example output) in the docs doesn't match the actual situation, then a PR would sure be welcome. So if anyone here is able to create one :+1:

**Comment by donhcd** [comment]
awesome, thanks for looking into this everyone!

@thaJeztah what do you mean? is it difficult to create docs PRs? also, would I have to make a PR to change the `bool`s to `int`s and another one to revert that change since this is fixed in master?

also, what should API consumers do for this? I'd like to update [samalba/dockerclient](https://github.com/samalba/dockerclient/blob/master/types.go#L220) to add in more Info fields, but I'm not sure what type I should mark these fields as now... Would you guys recommend making them `interface{}`s? :frowning:

**Comment by thaJeztah** [comment]
@donhcd I meant; if the docs are incorrect (I think that's what @runcom mentioned), that should be fixed.

Creating a PR for the docs is easy (they're in this repo as well), but if you don't know how, perhaps @runcom is able to create a PR to fix the docs.

I'm currently traveling myself, so cannot create a PR myself, and have to check everything on my phone, so was hoping someone was able to pick it up :smile:

**Comment by draghuram** [comment]
I don't see any issue with "Debug" as both the actual response and docs show it as "bool". However, "IndexServerAddress" is indeed a string and not an array as the docs have it. I can create a PR to fix it.

**Comment by draghuram** [comment]
BTW, the new "info" structure has been introduced in the commit f4942ed8. Should I fix "IndexServerAddress" in v1.18 docs as well as v1.19?

**Comment by runcom** [comment]
@draghuram Debug as of Docker 1.6.1shows up as an int (old engine put 1/0 whether true or false) but current master is OK. If you are going to make a pr for this you should fix IndexServerAddress for old and new api and for Debug as well

**Comment by runcom** [comment]
So to sum up, I've checked reference api again, v1.18 lists Debug and other bool flag as Boolean but they should be int 1/0, instead v1.19 is already fixed about the Boolean fields being lister as Boolean. IndexServerAddress should be fixed in both instead.

**Comment by draghuram** [comment]
@runcom I will create the PR.
