### ISSUE TITLE
Invalid tagnames (parsers.ParseRepositoryTag)

### ISSUE THREAD

**Issue by KekSfabrik** [docker/docker#13149]
I noticed through a wonky bash script that i could generate tagnames that begin with a `-` but i can't remove them:
i wanted multiple versions tagged for the same image-id and tried to remove the falsely named `-` image: 
```
root@docker0:~/java# docker rmi -t:keks/java
flag provided but not defined: -t:keks/java
```
then i tried again with the tagname
```
root@docker0:~/java# docker rmi '-t:keks/java:8'
flag provided but not defined: -t:keks/java:8
See 'docker rmi --help'.
root@docker0:~/java# docker images 
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
-t:keks/java        8                   d4dfe0daed45        2 minutes ago       686.7 MB
-t:keks/java        latest              d4dfe0daed45        2 minutes ago       686.7 MB
```
...
then i tried around whether i can reproduce it and noticed i can `rmi` it several times until the wrongly named ones are all gone:
```
root@docker0:~/java-base# docker rmi e5935d9930e0
Error response from daemon: Conflict, cannot delete image e5935d9930e0 because it is tagged in multiple repositories, use -f to force
FATA[0000] Error: failed to remove one or more images   
root@docker0:~/java-base# docker rmi -f e5935d9930e0
Untagged: --:keks/test:latest
root@docker0:~/java-base# docker rmi -f e5935d9930e0
Untagged: -t:keks/java-base:8
```

cpuguy83 suggested i post this here..

cheers, KekS

*EDIT* after `GordonTheTurtle` complained:
```
root@docker0:~# docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64

root@docker0:~# docker info
Containers: 10
Images: 88
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 110
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.16.0-34-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 1.955 GiB
Name: docker0
ID: FI6W:SGC7:OUIX:OT7S:BFOR:UWXD:KH4V:LNKZ:HJHK:SKJ3:ZS3Z:ILES
Username: keks
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support

root@docker0:~# uname -a
Linux docker0 3.16.0-34-generic #47~14.04.1-Ubuntu SMP Fri Apr 10 17:49:16 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
Environment details:
VM running on own hardware (libvirt/kvm/qemu/virsh)

Steps to Reproduce:
1. run `docker build -t -t:repo/name:version` .
2. try to remove it again `docker rmi -t:repo/name:version`
3. look at error and frown

Actual Results:
image can't be removed this way, `rmi` with the image-id has to be run multiple times and will remove one of the tagged images each time

Expected Results:
being able to remove the image or not be allowed to name it beginning with a `-` and including a `:`

Additional info:
/msg keksi on freenode if you have further questions

**Comment by coolljt0725** [comment]
I think we should not allowed the name begining with `-`, I working on that.

**Comment by crosbymichael** [comment]
@KekSfabrik just for my own curiosity why are you using `-` as the starting char of an image?  Does this come from some type of paradigm or project?

**Comment by KekSfabrik** [comment]
@crosbymichael like i wrote initially: it was a wonky bash script - the script was supposed to either be called `./build.sh` to build with tag keks/path:latest or `./build -t TAG` to build keks/PATH:TAG - apparently it then called `docker build -t -t:keks/PATH:TAG` instead

**Comment by crosbymichael** [comment]
@KekSfabrik ahh ic.
