### ISSUE TITLE
UNit tests fail for zfs when run with make test-unit

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#13142]
ping @mic92

so when I run using a binary from master.dockerproject.com, I have a host with a zfs volume /var/lib/docker on my host

I run `make test-unit`  in docker, and the unit-tests fail with 
```
+ go test -test.timeout=30m github.com/docker/docker/daemon/graphdriver/zfs
--- FAIL: TestZfsCreateEmpty (0.03s)
	graphtest.go:159: Newly created image doesn't exist
FAIL
coverage: 61.7% of statements

Tests failed: ./daemon/graphdriver/zfs
```

but all the integration-cli tests pass, so that's good, but I figure this is just something small

**Comment by Mic92** [comment]
@jfrazelle see the PR
