### ISSUE TITLE
Update docker version to latest

### ISSUE THREAD

**Issue by mateeyow** [docker/docker#13145]
Hi, I am running Elementary OS (Freya) and I want to install the latest docker version. Installing docker using `sudo apt-get -y install docker.io` will only install **Docker version 1.0.1** and I need the latest version to run `docker exec` on my container.

**Comment by mateeyow** [comment]
Description of problem:
I need to update my docker version to the latest one on Elementary OS to run `docker exec`

`docker version`: Docker version 1.0.1, build 990021a


`docker info`: 
Containers: 2
Images: 96
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 100
Execution Driver: native-0.2
Kernel Version: 3.16.0-37-generic
WARNING: No swap limit support

`uname -a`:
Linux drachma 3.16.0-37-generic #51~14.04.1-Ubuntu SMP Wed May 6 15:23:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
Physical

Steps to Reproduce:
1. Install docker using `sudo apt-get install docker.io -y`
2. Pull an ubuntu image
3. Run Container using `docker run -itd --name test ubuntu`
4. Execute Container `docker exec -it test bash`


Actual Results:
Error: Command not found: exec
Error: Command not found: -it

Expected Results:
Can execute bash for the container

Additional info:
`lsb_release -a` yields:
LSB Version:	core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch
Distributor ID:	elementary OS
Description:	elementary OS Freya
Release:	0.3
Codename:	freya

**Comment by PikachuEXE** [comment]
Have you installed http://www.ubuntuupdates.org/package/docker/docker/main/base/lxc-docker ?

**Comment by mateeyow** [comment]
@PikachuEXE Oh, it worked. Thanks. I can't seem to find it on the installation guide.
