### ISSUE TITLE
Ran out of disk space. I do I know which containers/images take most space?

### ISSUE THREAD

**Issue by olalonde** [docker/docker#13148]
I'm running boot2docker + docker and ran out of disk space. Is there a way to list which containers/images take the most space? Also, in which directory does Docker save its images/containers? Is there a way to delete all containers which have not been started for more than X weeks?

**Comment by stephenwithav** [comment]
You can use `docker images` to see the size of your images.

Everything, by default, is stored in `/var/lib/docker`.

**Comment by cpuguy83** [comment]
Also `docker ps -a --size`.
You should probably also do something like `docker rmi -f $(docker images --filter dangling=true -q)`

Closing since this is not an issue.
For support please hop on #docker on IRC, forums.docker.com, or the docker-user mailing list.
Thanks!
