### ISSUE TITLE
Consider allowing the Docker data file in /var/lib/docker/devicemapper/devicemapper to exceed 100GB

### ISSUE THREAD

**Issue by whyistheinternetbroken** [docker/docker#13159]
I've noticed that if we want to use external storage via the docker-storage file for Docker, we have to configure a block-based device.

However, it also seems possible to mount NFS directly to /var/lib/docker and leverage that for Docker images instead. This provides us with more free space, as well as resiliency if our client ever crashed on us. 

Additionally, if we're using clients with > 100GB in free space, it would be nice to exceed that 100GB if we wanted.

Any implications in allowing the data and metadata flat files be configured to exceed their default sizes?

Any reason why using external file-based shares like NFS for Docker images is bad?

# docker version
Client version: 1.5.0-dev
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): fc0329b/1.5.0
OS/Arch (client): linux/amd64
Server version: 1.5.0-dev
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): fc0329b/1.5.0
OS/Arch (server): linux/amd64

# docker info
Containers: 1
Images: 22
Storage Driver: devicemapper
 Pool Name: docker-253:1-50476183-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 959.7 MB
 Data Space Total: 107.4 GB
 Data Space Available: 9.646 GB
 Metadata Space Used: 1.688 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Kernel Version: 3.10.0-229.1.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 1
Total Memory: 1.797 GiB
Name: centos7.domain.win2k8.netapp.com
ID: 5BE4:TT7E:5IJT:XFLZ:JYQK:AX5O:QT74:HEFR:ZGDS:EBRB:LCDH:6RSF
Username: parisi
Registry: [https://index.docker.io/v1/]

# uname -a
Linux centos7.domain.win2k8.netapp.com 3.10.0-229.1.2.el7.x86_64 #1 SMP Fri Mar 27 03:04:26 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details: VM running CentOS 7

How reproducible: More of a feature request than something that's broken.

Steps to reproduce: Data and metadata seem to be hard coded to specific sparse file sizes.

Actual results: Inability to configure sparse file sizes for data and metadata in /var/lib/docker/devicemapper/devicemapper

Expected results: Ability to configure sparse file size

Additional info: N/A

**Comment by cpuguy83** [comment]
Hi,

This is a configuration option when first starting docker with the devicemapper driver.
If you use AUFS or overlay there are no space restrictions (since they just use the underlying fs).
For more information see: https://github.com/docker/docker/tree/master/daemon/graphdriver/devmapper

Closing since this is not an issue.
If you have any questions feel free to hop on #docker on IRC!
Thanks!

**Comment by whyistheinternetbroken** [comment]
Awesome. Thanks! 

RTFM FTW! :)

:+1:
