### ISSUE TITLE
Install Docekr latest version on Debian Squeeze.

### ISSUE THREAD

**Issue by sagarrao** [docker/docker#13153]
Hi,

We have a spring boot project which has been dockerized. The images have been built and it runs perfectly on my local machine(Windows 7). However, we want to deploy it to a 64 bit debian box(version info:
Distributor ID: Debian
Description:    Debian GNU/Linux 6.0.10 (squeeze)
Release:        6.0.10
Codename:       squeeze

The installation docs for Docker latest version state that it is supported only on 7.7 and 8.0. 

Just wanted to know if there is a way of installing docker(latest or any prior version) on the above mentioned configuration.

**Comment by unclejack** [comment]
Debian squeeze is unsupported.

Please upgrade to Debian Jessie. Wheezy also requires a kernel from backports as kernel 3.2 (the kernel shipped with wheezy) is too old for Docker.

**Comment by sagarrao** [comment]
Description of problem: Install Docker on Debian Squeeze. the install docs state that it isn't supported on Debian Squeeze so is there a way to do the same?

`docker version`: Any version.
`docker info`:
`uname -a`:
Environment details (AWS, VirtualBox, physical, etc.): 

Distributor ID: Debian
Description: Debian GNU/Linux 6.0.10 (squeeze)
Release: 6.0.10
Codename: squeeze

How reproducible:


Steps to Reproduce:
1.
2.
3.


Actual Results:


Expected Results:


Additional info: How to install Docker on Debian Squeeze box. As per the documentation it isn't supported. We want to deploy a Docker image onto a Debian box for our testing purposes.
