### ISSUE TITLE
openSUSE Won't Run Docker Images with Published Ports

### ISSUE THREAD

**Issue by jbulchergist** [docker/docker#13164]
I'm running a brand-new install of openSUSE 13.2. When I attempt to run containers with the `-p` or `-P` option, they exit with `exit status 1`. 

This works:

    docker run --rm -it ubuntu:latest bash

This doesn't:

    docker run --rm -p 4444:4444 -it ubuntu:latest bash

Again, the container fails to start with `exit status 1`

I asked a [unix.stackexchange](http://unix.stackexchange.com/questions/203019/opensuse-wont-run-docker-images-with-published-ports) question before coming here.

---

# Details

```
> docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): 4749651
OS/Arch (server): linux/amd64
```

```
>docker info
Containers: 18
Images: 198
Storage Driver: btrfs
 Build Version: Btrfs v3.16.2+20141003
 Library Version: 101
Execution Driver: native-0.2
Kernel Version: 3.16.7-21-desktop
Operating System: openSUSE 13.2 (Harlequin) (x86_64)
CPUs: 4
Total Memory: 15.63 GiB
Name: linux-c2nk
ID: BMIX:JL3Q:3GZL:Z46E:HTUC:JSG4:FRQG:EWVY:XK3S:6MVM:F23G:W7KV
WARNING: No swap limit support
```

```
> uname -a
Linux linux-c2nk 3.16.7-21-desktop #1 SMP PREEMPT Tue Apr 14 07:11:37 UTC 2015 (93c1539) x86_64 x86_64 x86_64 GNU/Linux
```

## Step to Reproduce

1. Run an image using `-p`, e.g. `docker run --rm -p 4444:4444 -it ubuntu:latest bash`

## Actual Results:

```
FATA[0000] Error response from daemon: Cannot start container 060f9186bd44a46f31ae84f4e2574deb76549d6f7fbc35a7010fc1c04c007d53:  (exit status 1)
```

## Expected Results:

A bash prompt inside the container.

**Comment by phemmer** [comment]
The daemon logs should indicate what is wrong. Dunno where you'll find this on SUSE, but likely either `/var/log/docker` or `journalctl -u docker.service`.

**Comment by jbulchergist** [comment]
Thanks for your reply.

I finally got it to work by restarting the docker daemon. I'm not sure what that accomplished, but it works now, so I'm not complaining.
