### ISSUE TITLE
docker-pull man page usage line is incomplete

### ISSUE THREAD

**Issue by pdevine** [docker/docker#13168]
The docker-pull man page usage line is missing an entry for alternate registries.  Right now it looks like:

docker pull [-a|--all-tags[=false]] [--help] NAME[:TAG]

but should probably look like:

docker pull [-a|--all-tags[=false]] [--help] [REGISTRY_HOST[:REGISTRY_PORT]/]NAME[:TAG]

The docker-push man page has a more correct usage line which includes alternate registries, but it's a little misleading because it looks like:
... NAME[:TAG] | [REGISTRY_HOST[:REGISTRY_PORT]/]NAME[:TAG]

**Comment by thaJeztah** [comment]
Closing, because it looks like that man page has been updated in https://github.com/docker/docker/commit/2c07fd9fdf78842b4a09ff9a226bd57ba500f16b#diff-3b6160ad6c0abca616e6828ea34eb14e
