### ISSUE TITLE
events --since/--until timestamp parsing is not correct

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/docker#13175]
I'm running docker 1.6.1 release bits and I just created some container `docker run --rm busybox date` to create some events.

Then I ran `docker events --since=2015-01-01T00:00:01` many events showed up.
Then I added **`Z`** to the timestamp (because allowed in RFC3339) and requested:

    docker events --since=2015-01-01T00:00:01Z 

It shows nothing and command just hangs there.

Adding **`Z`** for some reason, causes string to be not parsed as date correctly and as a fallback we just send the string as is to the daemon:

    GET /v1.18/events?since=1420095601  (without Z)
    GET /v1.18/events?since=2015-01-01T00%3A00%3A01Z (with Z)

However daemon (Remote API) is supposed to handle only Unix timestamps. According to the docs, RFC3339 is an allowed timestamp and this looks like a bug.

My change #12362 made this surface up clearly (now it clearly says the specified value is not an integer). However as I said, it was broken in the release without my change as well.

Conclusion: `pkg/timeutills/utils.go#GetTimestamp()` is unable to parse the standard RFC3339.  It's happening because this special thing added to `pkg/timeutils/json.go`:

    RFC3339NanoFixed = "2006-01-02T15:04:05.000000000Z07:00"

 The test case I added now (#13165) made me catch this. I don't know how far this goes back.

**Comment by ahmetalpbalkan** [comment]
cc: @unclejack

**Comment by duglin** [comment]
Sure looks like a 'go' bug to me.  Guess we could create our own parser for this.  
I noticed it also has trouble with trailing timezone info after a Z even if you do get it to accept the Z:
http://play.golang.org/p/wcOScjG-WX

**Comment by ahmetalpbalkan** [comment]
@duglin why do we use a special layout? Will you be sending a PR, this blocks another PR atm.

**Comment by duglin** [comment]
We needed to have a layout that padded with extra 0's at the end so things lined-up in the logs.
yea, I'm working on a fix....

**Comment by duglin** [comment]
geez this is annoying. I can't even get Go's `time.Parse()` to parse `2015-01-01T00:00:01Z07:00` in the default RFC3339 format w/o it saying `err:"parsing time \"2015-01-01T00:00:01Z07:00\": extra text: 07:00"`.  Maybe I'm doing something wrong...

**Comment by ahmetalpbalkan** [comment]
Maybe we can do some post-processing to align those strings, while they're shown? Or maybe this method shouldnt be used for parsing user inputs (we can just use rfc3339format const in go)?

**Comment by thaJeztah** [comment]
@ahmetalpbalkan I think this should have been closed by https://github.com/docker/docker/issues/13188, so I'll close it, but let me know if I'm incorrect here :)
