### ISSUE TITLE
Incorrect document storage-opt

### ISSUE THREAD

**Issue by rickyzhang82** [docker/docker#13173]
The document in 
./daemon/graphdriver/devmapper/README.md|273 col 34| ``docker -d --storage-opt dm.use_deferred_device_removal=true``   

But the code use dm.use_deferred_removal

1779         case "dm.use_deferred_removal":
1780             EnableDeferredRemoval, err = strconv.ParseBool(val)
1781             if err != nil {
1782                 return nil, err
1783             }

**Comment by coolljt0725** [comment]
@rickyzhang82  Thanks for reporting, next time when you find an incorrect document, you can open
an PR to correct it. :)
