### ISSUE TITLE
Creating and afterwards deleting files in volume does not release disk space

### ISSUE THREAD

**Issue by timeu** [docker/docker#13182]
I have a weird issue regarding a docker container that runs a python script which creates a single file in a volume, processes it and afterwards deletes it (this consecutive times). The problem seems to be that disk usage increases although the files are deleted after they are processed and after a while the python scripts fails because the disk runs out of space.  

Below is the output of `df -h` after the python script has been running for some time (the volume is mounted on */home* )

Filesystem|  Size|  Used| Avail| Use%| Mounted on
------------- |------- |-------- |------- |--------| ---------------------
 /dev/vda1  |      20G | 7.3G |  12G  | 39% /
 none     |       1.9G |    0 | 1.9G |  0% |/dev/shm
 /dev/vdb    |     30G |  20G | 8.7G | 69%| /home

After I stop the container and run `df -h` again, */home* displays the correct disk usage:

Filesystem  |    Size | Used | Avail | Use% | Mounted on
--------------- | --------- | ---- | ----- | ------ | -----------
/dev/vda1   |     20G | 7.3G |  12G | 39%  |/
none       |     1.9G    | 0 | 1.9G  | 0% | /dev/shm
/dev/vdb    |     30G  |4.2G|   24G  |15%| /home

While the container is running, I checked the volume on the host and interestingly I see some previously processed and supposingly deleted files with 0 bytes and one file ( <> 0 bytes) which is currently processed. 

This happens on a Centos 6.5 VM.

**uname -a**: `Linux vm64 2.6.32-504.12.2.el6.x86_64 #1 SMP Wed Mar 11 22:03:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

**docker info:**
```
Storage Driver: devicemapper
 Pool Name: docker-252:1-398424-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: 
 Metadata file: 
 Data Space Used: 1.301 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 2.507 MB
 Metadata Space Total: 2.147 GB
 Udev Sync Supported: true
 Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: native-0.2
Kernel Version: 2.6.32-504.12.2.el6.x86_64
Operating System: <unknown>
CPUs: 1
Total Memory: 3.741 GiB
Name: vm64
ID: 3WUB:EVCM:DKFV:OJJ6:KF3Z:2HN4:H233:I5FG:3CFU:W7BM:Y4UP:TFBN
```

**docker version:** 
```
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.3.3
Git commit (client): a8a31ef/1.5.0
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.3.3
Git commit (server): a8a31ef/1.5.0
```

**Comment by phemmer** [comment]
This sounds like your script isn't closing its file handles, which is keeping the files from being released.
See https://unix.stackexchange.com/questions/34140/tell-fs-to-free-space-from-deleted-files-now

**Comment by cpuguy83** [comment]
Agreed. This is just a simple bind-mount from the host fs into the container, docker isn't doing anything here.
And since it's a bind-mount it's not using any of the graph drivers or anything.

I'm going to close this since it doesn't look like a docker issue.
Feel free to ping me here or (prefferably on #docker on IRC) for any questions/help.
Thanks!

**Comment by timeu** [comment]
Yes you are right of course.  The script was leaking the file handles. 
After fixing it, the problem went away. 
Sorry for opening the issue.
