### ISSUE TITLE
lxc-start: conf.c: mount_entry: 2049 No such file or directory - failed to mount 'tmpfs' on '/usr/lib64/lxc/rootfs///run'

### ISSUE THREAD

**Issue by lichgo** [docker/docker#13181]
I started docker with --exec-driver=lxc in docker config file:
```
# /etc/sysconfig/docker
OPTIONS='--selinux-enabled --exec-driver=lxc'
```

But when I `docer run` there is always an error:
```
lxc-start: conf.c: mount_entry: 2049 No such file or directory - failed to mount 'tmpfs' on '/usr/lib64/lxc/rootfs///run'
lxc-start: conf.c: lxc_setup: 4163 failed to setup the mount entries for '441699355d9dc71c3d104d28ce07b47fb577d58650196273a5933fdd7378c936'
lxc-start: start.c: do_start: 688 failed to setup the container
lxc-start: sync.c: __sync_wait: 51 invalid sequence number 1. expected 2
lxc-start: start.c: __lxc_start: 1080 failed to spawn '441699355d9dc71c3d104d28ce07b47fb577d58650196273a5933fdd7378c936'
lxc-start: lxc_start.c: main: 342 The container failed to start.
lxc-start: lxc_start.c: main: 346 Additional information can be obtained by setting the --logfile and --logpriority options.
```
Is it necessary to install other lib or to mount something?

( The issue below has been fixed)
=====
I am trying to enable lxc on docker. 

1. Before that, I have installed lxc on my Centos7 (`yum install lxc`).

2. Then I tried to enable lxc: `sudo docker -d -e=lxc`.

3. Firstly, it reported that pid file was found. So I removed the pid file. Then I enabled lxc again. Now it print some INFO logs and hanged there.

I couldn't find any clue to figure out why. Can someone suggest ideas? Thanks.

```
INFO[0000] +job serveapi(unix:///var/run/docker.sock)
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
INFO[0000] +job init_networkdriver()
INFO[0000] -job init_networkdriver() = OK (0)
INFO[0000] Loading containers: start.
...ERRO[0000] Failed to load container 36485fb72c65ed752018d2b0b343118266e37f6aa43c33274e6a0493ee97a699: open /var/lib/docker/containers/36485fb72c65ed752018d2b0b343118266e37f6aa43c33274e6a0493ee97a699/config.json: no such file or directory
...ERRO[0000] Failed to load container 609f78bb23d0418eb57c0213a42863cf1252d9781bec17aec755dc338a670141: open /var/lib/docker/containers/609f78bb23d0418eb57c0213a42863cf1252d9781bec17aec755dc338a670141/config.json: no such file or directory
......................
INFO[0000] Loading containers: done.
INFO[0000] docker daemon: 1.5.0-dev fc0329b/1.5.0; execdriver: lxc-1.0.7; graphdriver: devicemapper
INFO[0000] +job acceptconnections()
INFO[0000] -job acceptconnections() = OK (0)
```

**Comment by jfrazelle** [comment]
why not use the native execdriver

**Comment by lichgo** [comment]
@jfrazelle I need hard (absolute) limit on CPU for each container. It seems that using LXC is the only way.

Any other ways to set hard limit on CPU?

**Comment by jfrazelle** [comment]
we have cpu options for cgroups...
https://docs.docker.com/reference/run/#runtime-constraints-on-cpu-and-memory

**Comment by lichgo** [comment]
@jfrazelle I think the link you provided is the setting cgroups, which is a part of lxc. The web page you gave is just for setting relative CPU shares, not absolute limit. For example, if only one container is running (100% extensive CPU), relative CPU shares solution still allows it to run 100% CPU, but I need a hard limit, say, only 20% of CPU can be used even there is only one container running.

**Comment by stephenfin** [comment]
I'm seeing the same issue - I have a hard dependency on the lxc driver also (so I can attach to a systemd container). Here's my logs:

---

# Description of problem:

Docker instance fail to start using the lxc driver. However, this issue does not occur when I start docker manually like so:

```
sudo -E docker -dD
```

# `docker version`: 1.6.0

$ docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 350a636/1.6.0
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 350a636/1.6.0
OS/Arch (server): linux/amd64

# `docker info`:

Containers: 0
Images: 4
Storage Driver: devicemapper
 Pool Name: docker-253:0-1316946-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 5.352 GB
 Data Space Total: 107.4 GB
 Data Space Available: 24.85 GB
 Metadata Space Used: 3.973 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93 (2015-01-30)
Execution Driver: lxc-1.0.7
Kernel Version: 3.17.8-300.fc21.x86_64
Operating System: Fedora 21 (Twenty One)
CPUs: 20
Total Memory: 62.82 GiB
Name: xxxx
ID: xxxx

# `uname -a`:

Linux silpixa00385143.ir.intel.com 3.17.8-300.fc21.x86_64 #1 SMP Thu Jan 8 23:32:49 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

# Environment details (AWS, VirtualBox, physical, etc.):

Physical machine

# How reproducible:

Always

# Steps to Reproduce:

1. start docker service: `sudo service docker start`
2. attempt to start bash in container: `docker run --privileged -it fedora /bin/bash`

# Actual Results:

```
$ docker run --privileged -it fedora /bin/bash
lxc-start: conf.c: mount_entry: 2049 No such file or directory - failed to mount 'tmpfs' on '/usr/lib64/lxc/rootfs///run'
lxc-start: conf.c: lxc_setup: 4163 failed to setup the mount entries for '6f65842ce9cd295030422a077b61fced7c645fafe507f0133f889b5ea7fea672'
lxc-start: start.c: do_start: 688 failed to setup the container
lxc-start: sync.c: __sync_wait: 51 invalid sequence number 1. expected 2
lxc-start: start.c: __lxc_start: 1080 failed to spawn '6f65842ce9cd295030422a077b61fced7c645fafe507f0133f889b5ea7fea672'
lxc-start: lxc_start.c: main: 342 The container failed to start.
lxc-start: lxc_start.c: main: 346 Additional information can be obtained by setting the --logfile and --logpriority options.
```

# Expected Results:

The docker container should start

# Additional info:

I am a member of the `docker` group. I have restarted both the machine and the service multiple times.

I can avoid this issue by starting docker manually like so:

```
sudo -E docker -dD
```

When I do this (and create a VM in another tab), things work as expected. This could suggest a service spec issue on Fedora?

**Comment by sbhaskaran** [comment]
It says the issue has been fixed .. Can you please post what was the fix?

I have the same issue with docker1.5 or greater , kernel 3.10.0-229.el7.x86_64 using lxc as driver.

lxc-start: conf.c: mount_entry: 2049 No such file or directory - failed to mount 'tmpfs' on '/usr/lib64/lxc/rootfs///run'

**Comment by icecrime** [comment]
As notified in our [deprecation notice](https://github.com/docker/docker/blob/d023d5a8a24c18e912162c2f4c724cfb21028301/docs/misc/deprecated.md#lxc-built-in-exec-driver), Docker 1.10.0 will drop support for the LXC exec driver (#17700).

Thank you for the report, I'm now closing this.
