### ISSUE TITLE
Please don't remove old packages from apt repo

### ISSUE THREAD

**Issue by burke** [docker/docker#13191]
It causes us a lot of pain when old packages disappear from `get.docker.com` immediately upon the release of a new package. It would be much more user-friendly to keep at *least* the previous release, but ideally a full history.

```
$ apt-cache madison lxc-docker
lxc-docker |      1.6.1 | https://get.docker.com/ubuntu/ docker/main amd64 Packages
$
```

**Comment by cpuguy83** [comment]
@burke All older packages are available as `lxc-docker-<version>`

**Comment by cpuguy83** [comment]
And actually `lxc-docker` installs `lxc-docker-<latest version>`

**Comment by burke** [comment]
Ok, and I see that they're all mutually-incompatible, which makes this work fine for me. It's still really weird behaviour though.

**Comment by PikachuEXE** [comment]
It's not well documented, but it works

**Comment by cpuguy83** [comment]
Closing since these are not removed.
Also the new apt repo `apt.dockerproject.org` is a proper repo that stores versions in a single package name.

**Comment by burke** [comment]
I just noticed that chef runs have been failing on some of my nodes because 
`1.8.0~rc1-0~trusty` has been pulled from the repo. Obviously I should upgrade to rc2, but it's really inconvenient to have this upgrade time forced upon me.

**Comment by cpuguy83** [comment]
ping @calavera

**Comment by burke** [comment]
This happened again with `1.8.0~rc3-0~trusty` :(

**Comment by cpuguy83** [comment]
ping @tianon @jfrazelle

**Comment by thaJeztah** [comment]
reopening so that we can investigate

**Comment by jfrazelle** [comment]
they are all still there https://apt.dockerproject.org/repo/pool/testing/d/docker-engine/

**Comment by jfrazelle** [comment]
looking into it... what does your chef script look like?

**Comment by burke** [comment]
Strange. It's totally possible I just don't understand how to ubuntu.

```
burke@borg3.chi:~ $ apt-cache madison docker-engine
docker-engine | 1.8.0~rc3-0~trusty | https://apt.dockerproject.org/repo/ ubuntu-trusty/testing amd64 Packages
docker-engine | 1.7.1-0~trusty | https://apt.dockerproject.org/repo/ ubuntu-trusty/main amd64 Packages
burke@borg3.chi:~ $ cat /etc/apt/sources.list.d/docker.list
deb     https://apt.dockerproject.org/repo ubuntu-trusty main testing
burke@borg3.chi:~ $
```

Moreover, requesting an older version fails:

```
burke@borg3.chi:~ $ sudo apt-get install docker-engine=1.8.0~rc1-0~trusty
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Version '1.8.0~rc1-0~trusty' for 'docker-engine' was not found
```

**Comment by burke** [comment]
I can show you the chef stuff if you want but that cuts a bit closer to the heart of it ^

**Comment by jfrazelle** [comment]
nah this is enough info, let me try :)

**Comment by burke** [comment]
Ah yeah, https://apt.dockerproject.org/repo/dists/ubuntu-trusty/testing/binary-amd64/Packages only specifies the newest

**Comment by jfrazelle** [comment]
yeah ok i can fix sorry

**Comment by tianon** [comment]
This is https://bugs.debian.org/570623 again. :disappointed:

**Comment by burke** [comment]
No worries, thanks for looking into it :)

**Comment by jfrazelle** [comment]
we can use `dak` instead

**Comment by stevenschlansker** [comment]
We just hit a serious issue with 1.8.1 ( #15985 ) and now cannot downgrade without serious hackery due to this issue.  We use Puppet to manage apt versions, so changing to a different version with proper metadata is extremely easy, but downloading and using dpkg directly is extremely painful.

**Comment by thaJeztah** [comment]
@burke @stefanberger this should now be resolved soon, see https://github.com/docker/docker/issues/16001. Thanks for reporting!

**Comment by burke** [comment]
This is great, thanks a ton, @jfrazelle &co.
