### ISSUE TITLE
Docker unable to identify hosts

### ISSUE THREAD

**Issue by DakotaNelson** [docker/docker#13207]
I initially assumed a DNS issue, but `docker run -dns 8.8.8.8 ubuntu ping www.docker.io` returns `ping: unknown host www.docker.io`.

Additionally, I've tried:

1. Restarting the docker daemon
2. Restarting my entire machine
3. Running the docker daemon with `docker -d -dns 8.8.8.8`
4. The reset [here](https://github.com/docker/docker/issues/866#issuecomment-19218300)
5. The NetworkManager.conf fix found [here](https://github.com/docker/docker/issues/1809)
6. Uninstalling and reinstalling `docker-io` via yum

And yet, when I try to build a dockerfile witih `apt-get install` in it, I get 

`W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease` et. cetera for the various sources, with the daemon output of:

`INFO[0085] +job build()                                 
INFO[0086] +job allocate_interface(7f418be5c910a6d6ed0de24c70598b2fb99349452da8f2b321fb0dca014c2bd1) 
INFO[0086] -job allocate_interface(7f418be5c910a6d6ed0de24c70598b2fb99349452da8f2b321fb0dca014c2bd1) = OK (0) 
INFO[0086] +job log(start, 7f418be5c910a6d6ed0de24c70598b2fb99349452da8f2b321fb0dca014c2bd1, 6aef879eb2b9) 
INFO[0086] -job log(start, 7f418be5c910a6d6ed0de24c70598b2fb99349452da8f2b321fb0dca014c2bd1, 6aef879eb2b9) = OK (0) 
INFO[0096] +job log(die, 7f418be5c910a6d6ed0de24c70598b2fb99349452da8f2b321fb0dca014c2bd1, 6aef879eb2b9) 
INFO[0096] -job log(die, 7f418be5c910a6d6ed0de24c70598b2fb99349452da8f2b321fb0dca014c2bd1, 6aef879eb2b9) = OK (0) 
INFO[0096] +job release_interface(7f418be5c910a6d6ed0de24c70598b2fb99349452da8f2b321fb0dca014c2bd1) 
INFO[0096] -job release_interface(7f418be5c910a6d6ed0de24c70598b2fb99349452da8f2b321fb0dca014c2bd1) = OK (0) 
ERRO[0106] Error waiting for device 7f418be5c910a6d6ed0de24c70598b2fb99349452da8f2b321fb0dca014c2bd1 to close: Timeout while waiting for device 7f418be5c910a6d6ed0de24c70598b2fb99349452da8f2b321fb0dca014c2bd1 to close 
ERRO[0117] Error unmounting device 7f418be5c910a6d6ed0de24c70598b2fb99349452da8f2b321fb0dca014c2bd1: Device is Busy 
The command [/bin/sh -c apt-get -qq update && apt-get install -y       python3-pip       python-dev       libpq-dev] returned a non-zero code: 100
INFO[0117] -job build() = ERR (1)`

Any thoughts? I'm at a loss.

**Comment by DakotaNelson** [comment]
In that case:

`docker version`:
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 350a636/1.6.0
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 350a636/1.6.0
OS/Arch (server): linux/amd64

`docker info`:
Containers: 4
Images: 55
Storage Driver: devicemapper
 Pool Name: docker-253:0-1831737-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: 
 Metadata file: 
 Data Space Used: 1.271 GB
 Data Space Total: 107.4 GB
 Data Space Available: 106.1 GB
 Metadata Space Used: 2.908 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Library Version: 1.02.93 (2015-01-30)
Execution Driver: native-0.2
Kernel Version: 3.19.5-200.fc21.x86_64
Operating System: Fedora 21 (Twenty One)
CPUs: 4
Total Memory: 7.738 GiB
Name: blueharvest
ID: ILF2:TCHW:K7X4:HUXS:MJSI:YXDO:Q6WB:5B66:BWCH:SGDD:JRQW:TPPA

`uname -a`:
Linux blueharvest 3.19.5-200.fc21.x86_64 #1 SMP Mon Apr 20 19:51:56 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

It's a desktop Fedora Linux machine (dual booted with W7 if that matters).

**Comment by jmakanjuola** [comment]
Dakota,

Solution:
--------
mv /etc/apt/sources.list /etc/apt/sources.list.bak

and then rerun apt-get command

**Comment by Gillingham** [comment]
I'm encountering the same issue with docker 1.6.0 on Fedora 22. I can ping IP addresses from the container, including the DNS servers, but DNS resolution always fails.

**Comment by Gillingham** [comment]
@DakotaNelson have you checked the SELinux Alert Browser? I found a docker entry in there and then ran:
```
sudo grep docker /var/log/audit/audit.log | audit2allow -M mypol
sudo semodule -i mypol.pp
```
and now docker works after a reboot, I also did a dnf update shortly before this but I didn't see anything network/docker related in those updates so I'm assume SELinux was maybe blocking the docker networking.

**Comment by moldcraft** [comment]
I have a similar problem.
When ssh as `root`, I can `ping google.com` but when ssh as simple user (or `sudo -u simple_user`), the hosts are not resolved.

I found the problem: Sometimes `/etc/resolv.conf` has `600` permission.
The fix: ssh as `root` and set it to `644`.

**Comment by jpocentek** [comment]
@moldcraft - this actually solved all issues for me.

**Comment by cpuguy83** [comment]
Closing since this seemed to be some permission problem on Fedora?
Thanks for reporting back!
