### ISSUE TITLE
Docker build has no -v option

### ISSUE THREAD

**Issue by itsryandrake** [docker/docker#13203]
In your documentation located here - https://docs.docker.com/reference/commandline/cli/#build - there's no option to pass through -v, which I believe would be very useful for developers who are trying to debug Docker build configuration issues.

Any thoughts on when this option might be available?

**Comment by cpuguy83** [comment]
Hi, thanks for submitting.
This is by design.
To troubleshoot build issues, the failed container and image are preserved for inspection.
