### ISSUE TITLE
Docker Hub gives "invalid repo" when trying to link a repo

### ISSUE THREAD

**Issue by adamkdean** [docker/docker#13209]
Docker Hub gives "invalid repo" when trying to link a repo. 

    Failed to load resource: the server responded with a status of 404 (NOT FOUND)
    https://registry.hub.docker.com/u/adamkdean/node-libvips/settings/links/

I've tried reponame, username/reponame, and username/reponame:tag, reponame:tag ...

![screen shot 2015-05-14 at 10 20 12](https://cloud.githubusercontent.com/assets/1639527/7629228/d896fa6a-fa22-11e4-8536-46c228151571.png)

**Comment by adamkdean** [comment]
Hi GordonTheTurtle, I assume you are a bot?

I could not find an issue already relating to this, and it's not on my machine so the other commands are not required. Everything has already been provided. Please take this information to your overlords.

Thanks.

P.S. when I enable the button manually, I get `POST https://registry.hub.docker.com/u/adamkdean/node-libvips/settings/links/ 404 (NOT FOUND)`

**Comment by adamkdean** [comment]
This does work with other images, for example, `phusion/baseimage` works fine.

**Comment by cpuguy83** [comment]
Hi, can you send this to support@docker.com?

Thanks!

**Comment by silvio** [comment]
WTF ... and what is the solution? I have the same situation on my automatics builds.

**Comment by cpuguy83** [comment]
@silvio all dockerhub related things ought to go to support@docker.com

**Comment by thaJeztah** [comment]
@silvio issues related to Docker Hub are not handled in this issue tracker, but handled via support@docker.com
