### ISSUE TITLE
docker v2 registry push repeat issue analyze

### ISSUE THREAD

**Issue by blackfader** [docker/docker#13210]
first I push my docker version and docker info

```
Client version: 1.7.0-dev
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 1b09ac5
OS/Arch (client): linux/amd64
Server version: 1.7.0-dev
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 1b09ac5
OS/Arch (server): linux/amd64

Containers: 0
Images: 10
Storage Driver: btrfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.12.35-100.el6.x86_64
Operating System: <unknown> (containerized)
CPUs: 24
Total Memory: 63.01 GiB
Name: 8168d9029f8f
ID: S5PV:25YJ:IKCF:OUUQ:FBWV:ZHGV:44VA:GOOT:NIOW:L6O4:YA3T:KVOI
Debug mode (server): true
Debug mode (client): false
File Descriptors: 13
Goroutines: 15
System Time: 2015-05-14T18:56:35.348407166+08:00
EventsListeners: 0
Init SHA1:
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker
```

### i think docker push check image course is this:

**client : docker push  order begin**

ex:  docker push cents:6.6

docker client get /var/lib/graph/{image.id}/checksum is exist , if not exist , execute docker push this image, after push success, get push "digest" , and write it in /var/lib/graph/{image.id}/checksum.

**second, docker push same image again.**

docker get /var/lib/graph/{image.id}/checksum,and request v2 registry api , get registry blob digest, like

```
http://registry/v2/<name>/blobs/sha256:6547613252cf9a0a959575a4d22d99a9c91bcdc5bb4b5812a132d1fb757b6156
```

if response http code is "200" , docker think this image layer is exist .

so docker client echo "Image already exists".

### so this is a import question:

ex : 

I have a base image "centos:6.6"  , I push it to registry success .

this image layers is ：
f1b10cd84249
8b44529354f3
b0120c5afd0c
dfef3577fe68:
b0918483ae7c

and I docker build another image "app1", from "cents:6.6" in Dockerfile.

this image layer is 

f1b10cd84249(inherit centos:6.6)
8b44529354f3(inherit centos:6.6)
b0120c5afd0c(inherit centos:6.6)
dfef3577fe68(inherit centos:6.6)
b0918483ae7c(inherit centos:6.6)
5cd06ab8d856(app1 image layer self)
69abefce2aff(app1 image layer self)
b5a3454eaa54(app1 image layer self)
94dce5816750(app1 image layer self)

I push app1 , docker client will request ，check image layer is exist。

 ```
http://registry/v2/app1/blobs/{digest}
``` 

this will get b0918483ae7c(inherit centos:6.6) checksum , and request

```
http://registry/v2/app1/blobs/{digest}
``` 

**response 404 !.**

**because b0918483ae7c is  centos:6.6 image layer** , if request 

```
http://registry/v2/centos/blobs/{digest}
``` 

 **response 200 !.**

so , if docker push app1 , it will repeat image layers inherit centos:6.6, and push success will rewrite checksum .

so, if you docker build a new image first , it will push whole image layers , from 0 to last , not to mind if not  inherit 。

this way is not efficiency 。

**Comment by blackfader** [comment]
@stevvooe

**Comment by stevvooe** [comment]
@blackfader Efficiency-wise, the V2 protocol is biased towards pull rather than push. The behavior you've described is a side-effect of access-control in the V2 protocol. From a high-level, the image has a list of blobs that make it up. Currently, all of these blobs need to be "mounted" into a remote repository (ie "app1" or "centos"). When pushing these blobs (layers) for the first time into a _new_ repository, the client must "prove" they have access to the blob by sending it. This gets verified and the blob then becomes available in the new repository. Even though data is sent "unnecessarily", data is only ever stored once.

We are working on cross-repository dependencies for V2 images as a part of docker/distribution#62 to address this. The caveat is that one must retain access to the dependent repositories to be able to continue running the image.

**Comment by blackfader** [comment]
@stevvooe  thanks to your replay，in my scene to use docker：
a user will have a app1 self，so，the step of starting this app1 is ：
first ，create app1 dockerfile（from centos）。
second，build image by dockerfile。
next，push this image in build machine
next，pull this image in other machine  (work machine)
next， docker run in work machine 

so, this steps spend time about 2min, and "push image" spend about 1min20s.
so, "push image" spend 80% time , and I know second app1 update , "push image" spend time will be little less。

I think ， “first push a new image” spend too much time，so ， Is there a way to save time ？

**Comment by stevvooe** [comment]
@blackfader The best way to save time is to keep the image name constant on each update. For example, if you have an image `app1` based on `centos`, make sure that subsequent builds of `app1` are tagged as `app1` or you will have to push again (ie don't push `app2`, `app3`...) . This will reduce the likelihood that data needs to be re-pushed.

Optionally, you could just retag the `centos` image `app1:centos-base` as the first step, and let that run in parallel with the build. When the build is done, tag the image as `app1:<some build>`. By the time you push `app1:<some build>`, the layers should already be available.

**Comment by blackfader** [comment]
@stevvooe thanks a lot , this way is good! 
I think ，others also have this problem， so I suggest write in to document as FAQ 。

**Comment by stevvooe** [comment]
@blackfader No problem. I filed #526 to document this issue.
