### ISSUE TITLE
images overwritten by newer images become untagged

### ISSUE THREAD

**Issue by shishir-a412ed** [docker/docker#13215]
We have seen 2 issues like this in the past. N we did a short term solution (introduced a warning message) for one of them. Now I have encountered a third one in docker commit.
I feel we need a proper fix for this problem.

Issue 1) #10592 

Brief: When saving a repo, if you specify the image by ID, then the FQIN is discarded. On load, the result is a `none:none` repo which isn't very user-friendly. However, saving by FQIN does preserve the repo. name/tag, such that loading the tarball restores them.

Issue 2) #11285

Brief: Given an image "foo:latest" with ID 1234 already in docker, docker load < foo.tar with ID 5678 (same name, different ID) clobbers the existing name (of ID 1234) to none:none. 

Issue 3) docker commit
    a) sudo docker run -it rhel7 /bin/bash
    b) create a file /run/foo.txt inside the container
    c) sudo docker ps {get the container ID}
    d) sudo docker commit <container_id> rhel7
    e) sudo docker images {rhel7 shows the new image ID, old image gets renamed to none:none}

Shishir

**Comment by rhatdan** [comment]
This leads the user to see lots of images that he has no idea what the content is.

docker images | grep none | wc -l
41

I believe we should attempt to maintain the first part of the label.  
Updating foo:latest, would result in the prevous foo:latest to be foo:UUID.  Then if I list the images, I have some idea what the image contains.

**Comment by unclejack** [comment]
Those images aren't renamed, they merely become untagged. An untagged image is something which needs to be cleaned up, not have its tag left as it is or attempt to produce some kind of new tag.

From what I recall, there's a plan to garbage collect such untagged images so that only tagged images can exist.

**Comment by shishir-a412ed** [comment]
@unclejack yeah it's a real problem, user experience is one aspect. Disk space can also start 
getting filled up pretty quickly.

Is there a PR, where we can track progress of the work going on in this regard ?

**Comment by thaJeztah** [comment]
Not the issue to "track" this, but https://github.com/docker/docker/issues/928 (and https://github.com/docker/docker/issues/928#issuecomment-28249901) for prior discussion on easier "cleaning up".

Unfortunately, it was closed without a replacement proposal being opened

**Comment by thaJeztah** [comment]
Oh, actually, there's this one: https://github.com/docker/docker/issues/6802

**Comment by shishir-a412ed** [comment]
@thaJeztah I like the idea of `docker prune`. 
Just wondering if any active work is going on in this area.
The proposal seems to be 10 months old.

**Comment by thaJeztah** [comment]
> Just wondering if any active work is going on in this area. The proposal seems to be 10 months old.

Not sure, haven't heard of it recently, might be easier/quicker to ask on #docker-dev if you have plans to work on that

**Comment by shishir-a412ed** [comment]
@thaJeztah Is docker prune already implemented to collect and clean dangling file system layers ?

Is `dangling=true` flag the solution for this ?

e.g. `docker rmi $(docker images -f "dangling=true" -q)`

**Comment by shishir-a412ed** [comment]
@thaJeztah We can close this one too.
Related to #10592

**Comment by thaJeztah** [comment]
Thanks @shishir-a412ed, missed this one!
