### ISSUE TITLE
docker command without argument doesn't show help

### ISSUE THREAD

**Issue by xyc** [docker/docker#13235]
usingdocker.md says "Try typing Docker followed with a [command] to see the usage for that command:",
$ docker attach
Help output . . .

But it will not show help without additional arguments:
$ docker attach
docker: "attach" requires 1 argument. See 'docker attach --help'.

**Comment by hqhq** [comment]
#dibs

**Comment by hqhq** [comment]
I think we should change the doc, allow only with `--help` to show help info, because some commands like `docker ps` can be used without any additional arguments.

**Comment by duglin** [comment]
https://github.com/docker/docker/pull/11858 might play a role here

**Comment by vdemeester** [comment]
I think this one should be closed as the commit "related to" has been merged and it was *just* about documentation.

**Comment by cpuguy83** [comment]
Thankds @vdemeester
