### ISSUE TITLE
Docker upgrade docs does not work on Ubuntu 14.04

### ISSUE THREAD

**Issue by dkirrane** [docker/docker#13247]
I've checked docker --version before and after running the command and I still have version `Docker version 1.5.0, build a8a31ef`

```
wget -N https://get.docker.com/ | sh
--2015-05-15 11:09:03--  https://get.docker.com/
Resolving get.docker.com (get.docker.com)... 162.242.195.82
Connecting to get.docker.com (get.docker.com)|162.242.195.82|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7452 (7.3K) [text/plain]
Saving to: ‘index.html’

100%[===============================================================================================================================================================================>] 7,452       --.-K/s   in 0s

2015-05-15 11:09:04 (1.46 GB/s) - ‘index.html’ saved [7452/7452]
```

```
#uname -a
Linux UBUNTU4117V 3.13.0-49-generic #83-Ubuntu SMP Fri Apr 10 20:11:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
# docker info
Containers: 0
Images: 129
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 129
Execution Driver: native-0.2
Kernel Version: 3.13.0-49-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 15.67 GiB
Name: UBUNTU4117V
ID: QTIT:JXGL:A6XO:7YXZ:5LKY:PCKL:EG7T:FD4A:CZID:UE72:A77K:3WAY
WARNING: No swap limit support
```

**Comment by vdemeester** [comment]
Hi @dkirrane,

The command to use is ``wget -qO- https://get.docker.com/ | sh``. Without the ``-qO-`` flags, it's downloading it as a a file and default to ``index.html`` instead of putting it in the stdout (for sh to get it), and so ``sh`` doesn't see anithing.

**Comment by cpuguy83** [comment]
Yep, as @vdemeester said.
Also, you should just use apt-get to update.

Closing.

**Comment by dkirrane** [comment]
Ok this is probably a documenation defect so. Cause the upgrade documentation suggests the command I used

https://docs.docker.com/installation/ubuntulinux/#upgrade-docker

**Comment by vdemeester** [comment]
Ah didn't see that :sob:

**Comment by cpuguy83** [comment]
Oh nice, I'll re-open so someone can fix docs!

**Comment by vdemeester** [comment]
#dibs on this then :P

**Comment by vdemeester** [comment]
@cpuguy83 Ah nevermind, it's already fixed (https://github.com/docker/docker/blob/master/docs/sources/installation/ubuntulinux.md#upgrade-docker), the docs are just not up-to-date on the site.

**Comment by cpuguy83** [comment]
Thanks for checking into this!
