### ISSUE TITLE
docker.io package no more present in jessie-backports

### ISSUE THREAD

**Issue by krishna-kashyap** [docker/docker#13253]
Docker package is not available in jessie-backports as documented in the installation guide for the Debian OS

**Comment by thaJeztah** [comment]
Thanks for reporting this. We're aware of this issue; the docs were updated a bit prematurely and it turns out the docker.io package isn't in the back ports repo *yet*, see this discussion https://github.com/docker/docker/pull/13104 and this comment by the maintainer of the package https://github.com/docker/docker/pull/13104#issuecomment-100645071

The `curl -sSL https://get.docker.com/ | sh` should work though.

**Comment by krishna-kashyap** [comment]
Thanks Sebastiaan. Was able to get that to work for me, reported just in
case it was a recent development (Debian moving docker out of backports)

Regards,
Krishna

**Comment by thaJeztah** [comment]
Good to hear you got it working. I hope this will be resolved soon!

I'm going to close this issue, because we are aware of this problem, but feel free to continue the discussion.

ping @paultag :wink:

**Comment by paultag** [comment]
It migrated this morning, less than 30 minutes before this comment. It'll
be in Jessie soon.

On Sat, May 16, 2015 at 1:44 PM, Sebastiaan van Stijn <
notifications@github.com> wrote:

> Good to hear you got it working. I hope this will be resolved soon!
>
> I'm going to close this issue, because we are aware of this problem, but
> feel free to continue the discussion.
>
> ping @paultag <https://github.com/paultag> [image: :wink:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/13253#issuecomment-102659027>.
>



-- 
:wq

**Comment by thaJeztah** [comment]
Happy to hear that @paultag!

**Comment by andybarnes** [comment]
it's still not available in backports:

`apt-get install docker.io`
`Reading package lists... Done`
`Building dependency tree`       
`Reading state information... Done`
`Package docker.io is not available, but is referred to by another package.`
`This may mean that the package is missing, has been obsoleted, or`
`is only available from another source`

`E: Package 'docker.io' has no installation candidate`

**Comment by paultag** [comment]
The process takes time. You need to be patient. I have to backport and test
everything. Thanks.

**Comment by paultag** [comment]
I've started tracking this on my kanban tracker -
http://z.ero.cool/project/debian/us/9

On Tue, May 19, 2015 at 7:06 AM, Paul R. Tagliamonte <paultag@gmail.com>
wrote:

> The process takes time. You need to be patient. I have to backport and
> test everything. Thanks.
> On May 19, 2015 4:13 AM, "Andy Barnes" <notifications@github.com> wrote:
>
>> it's still not available in backports:
>>
>> apt-get install docker.io
>> Reading package lists... Done
>> Building dependency tree
>>
>> Reading state information... Done
>> Package docker.io is not available, but is referred to by another
>> package.
>> This may mean that the package is missing, has been obsoleted, or
>> is only available from another source
>>
>> E: Package 'docker.io' has no installation candidate
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/docker/docker/issues/13253#issuecomment-103391930>.
>>
>


-- 
:wq

**Comment by mfine** [comment]
Can this issue get re-opened to track this? As of today, there is no `docker.io` in [jessie](https://packages.debian.org/source/jessie/allpackages) or [jessie-backports](https://packages.debian.org/source/jessie-backports/allpackages). Looking forward to having the packages available, thanks!

**Comment by paultag** [comment]
http://z.ero.cool/project/debian/us/9?kanban-status=21 has latest status.
Waiting for a backport to clear backports new.

Please don't reopen the ticket.

**Comment by dworzanski** [comment]
Debian pulled Docker out of Jessie right before it became stable. It was a pretty crazy last-second move. As I recall, it had something to do with and inability to maintain Go. Docker had been in Jessie testing for a very long time and it now seems to be back in testing for the next release of Debian.

I'm glad to see Docker will be in backports for Jessie. RHEL has gone all-in on Docker. Debian needs support as well.

**Comment by andybarnes** [comment]
@dworzanski https://lists.debian.org/debian-release/2015/03/msg00685.html

**Comment by thaJeztah** [comment]
@andybarnes @dworzanski more factually, see https://github.com/docker/docker/pull/13104#discussion_r30002311;

> It was not remove for security concerns, it was removed because I wanted to avoid work for myself.
> 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=781554
> is the actual link and why.
