### ISSUE TITLE
Proposal: Make Ansi Terminal Emulation Components External

### ISSUE THREAD

**Issue by gabrielhartmann** [docker/docker#13257]
This pull request (https://github.com/docker/docker/pull/13224) is about 3000 lines long, and most of it isn't really relevant just to Docker.  There is a general purpose Ansi Terminal emulation system in there which I think should be external to Docker.  Docker could just reference the external repository as a vendor contribution, and then terminal emulation improvements will automatically improve the Window client experience without any code changes needing to be made in Docker.

**Comment by ahmetalpbalkan** [comment]
cc: @tiborvass @icecrime @brendandixon

Our intent is to move the ANSI emulation repository to github.com/Azure and maintain it there.  How does that sound to you guys?

**Comment by tiborvass** [comment]
That's what we wanted from the beginning :) It's easier for Docker, easier for the Go community, I'm a strong +1.

**Comment by unclejack** [comment]
+1 on doing this. We're already doing this with kr/pty.

**Comment by ahmetalpbalkan** [comment]
@tiborvass @unclejack nice to hear. We started the internal process to OSS that library into its own repository. @gabrielhartmann will update you folks and the PR #13224.

**Comment by LK4D4** [comment]
@ahmetalpbalkan Any update here? :)

**Comment by gabrielhartmann** [comment]
We're waiting on a lawyer right now.  Gets back from vacation tomorrow.

**Comment by gabrielhartmann** [comment]
Ansi terminal parsing and actions based on that parsing is now external here:
https://github.com/Azure/go-ansiterm
