### ISSUE TITLE
Cannot `docker run -v $(pwd):/mnt scratch /mnt/binary`

### ISSUE THREAD

**Issue by aidanhs** [docker/docker#13252]
This was useful for explicitly checking whether a static binary could operate without touching the filesystem. You can do the same with `hello-world`, but then you actually have to download something. Is it possible to create a scratch fs at runtime to use?

**Comment by aidanhs** [comment]
You can't even create an empty image with a dockerfile containing just `FROM scratch` :(

**Comment by cpuguy83** [comment]
@aidanhs You can create an emtpy tarball and import that in.
