### ISSUE TITLE
Does docker build remove volumes of intermediate containers?

### ISSUE THREAD

**Issue by jamesyli** [docker/docker#13267]
In the output of docker build, I saw an output line of 'Removing intermediate container xyz', does that mean all the volums of the intermediate container xyz get removed?

I know I need 'docker rm **-v**' to remove volums, just not sure if docker build adds the '-v' option to remove intermediate containers.

Thanks.

**Comment by calavera** [comment]
It **does**. You can see the options for the cleanup in the builder internals:

https://github.com/docker/docker/blob/master/builder/internals.go#L747-L749
