### ISSUE TITLE
Changed Behavior: Apparmor profile overly constrictive

### ISSUE THREAD

**Issue by Thell** [docker/docker#13264]
Recent changes in mounting restrictions and AppArmor profile can cause a container to fault during initialization forcing the use of _apparmor:unconfined_ or _privileged_ when all that is needed is SYS_ADMIN. Is this intended and should it be that way?

A simple example Dockerfile (below) using ubuntu vivid running systemd started without the use of 'privileged' __or__ 'sec-opts' prior to the new restrictions. The Dockerfile _should_ start with only  
```
docker run -it --cap-add SYS_ADMIN --cap-add AUDIT_READ \
  -v /sys/fs/cgroup:/sys/fs/cgroup:ro <image>
```

but now the result is...
```
Failed to mount tmpfs at /run: Permission denied
Failed to mount tmpfs at /run/lock: Permission denied
[!!!!!!] Failed to mount API filesystems, freezing.
```

According to capabilities SYS_ADMIN should have the right to mount, and the init routine of a container should surely be capable as well.

----
Example Dockerfile:

```
FROM ubuntu:vivid
ENV container docker
RUN apt-get install -y --no-install-recommends dbus
 
# Setup simple autologin root shell
RUN systemctl set-default multi-user.target; \
  systemctl enable console-getty.service console-setup.service; \
  CONF_FILE=/etc/systemd/system/console-getty.service.d/override.conf; \
  mkdir -p ${CONF_FILE%/*}; \
  echo "[Service]" >> $CONF_FILE; \
  echo "ExecStart=" >> $CONF_FILE; \
  echo "ExecStart=-/sbin/agetty --noclear --autologin root --keep-baud console 115200,38400,9600 linux" >> $CONF_FILE; \
  echo "TTYVTDisallocate=no" >> $CONF_FILE; \
  echo "Type=simple" >> $CONF_FILE
 
ENTRYPOINT ["/bin/systemd"]
CMD [""]
```

**Comment by LK4D4** [comment]
ping @ewindisch

**Comment by ewindisch** [comment]
Users may write and use custom policies which match their requirements. The docker-default policy is fairly straight-forward to copy and modify as needed. In this case, a user/deployer could duplicate the policy under a new name and remove the 'mount'. Is this a fair compromise?

@Thell the unfortunate problem is that if we allow 'mount' by default, it allows mounts from inside user namespaces created within a Docker container. The current setting was introduced after discussion indicating that we did not wish to allow  unprivileged users to use 'mount' by default.

**Comment by Thell** [comment]
__Shouldn't tmpfs on `/run` be whitelisted?__ Just as reopening the mounting of /sys/fs/cgroup, some things are needed/desired that fall outside of the release notes statement of "proactively tighten the policy further by outright denying the use of the sys_mount syscall." Even the Benchmark document doesn't seem to call for such a swing.

Perhaps if a __Dockerfile__ could state its requirements and be signed in an extendable? There are quite a few successful models along these lines ( Powershell comes to mind ).

**Comment by ewindisch** [comment]
@Thell There is an entirely valid question here as to if the mount restriction is too restrictive. Perhaps FUSE support will evolve where it can be used safely from a container, or perhaps we deem bind mounts safe.  The fact is, however, that we either leave this open and patch it every time there is a newly discovered vector, or we get ahead of it and block the entire class of vulnerabilities.

There has already been at least one local-privilege-escalation vulnerability discovered in the kernel that was not covered by the old apparmor policy. The new policy, however restrictive, has proven to provide protection against it.

I feel it's entirely appropriate for multiple AppArmor policies to exist, both as part of the packages and locally, and the patches I have already proposed will make it easier to change the local default as well. Perhaps it will help if this is well documented?

**Comment by cpuguy83** [comment]
Can this be closed?

**Comment by Thell** [comment]
@cpuguy83 sure; I had left it open until these changes hit mainstream for others; but it seems others don't have an issue with it. :)
