### ISSUE TITLE
Futex contention via Node.js between containers

### ISSUE THREAD

**Issue by garrickp** [docker/docker#13268]
This is a very odd one, so please bear with me.

On an AWS node, running four instances of Node each in their own docker container, under load, the four instances appear to all be waiting on the same futex. When running four instances of Node inside one container, the contention goes away, and throughput quadruples.

Setup:

    $ node --version
    v0.12.2 # Installed via linux 64-bit tar.gz from website

    $ sudo docker version
    Client version: 1.6.1
    Client API version: 1.18
    Go version (client): go1.4.2
    Git commit (client): 97cd073
    OS/Arch (client): linux/amd64
    Server version: 1.6.1
    Server API version: 1.18
    Go version (server): go1.4.2
    Git commit (server): 97cd073
    OS/Arch (server): linux/amd64

    $ sudo docker info
    Containers: 19
    Images: 73
    Storage Driver: aufs
     Root Dir: /var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 111
     Dirperm1 Supported: false
    Execution Driver: native-0.2
    Kernel Version: 3.13.0-36-generic
    Operating System: Ubuntu 14.04.2 LTS
    CPUs: 2
    Total Memory: 7.305 GiB
    Name: <>
    ID: B6DY:VT2K:WTMM:SWCT:PY7K:QPL2:P33C:GS4R:D2ZC:FJUT:RMMQ:MKMW
    WARNING: No swap limit support

    $ uname -a
    Linux <> 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

    $ cat /etc/lsb-release
    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=14.04
    DISTRIB_CODENAME=trusty
    DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"
    $ cat /proc/
    Display all 200 possibilities? (y or n)
    $ cat /proc/cpuinfo
    processor	: 0
    vendor_id	: GenuineIntel
    cpu family	: 6
    model		: 62
    model name	: Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
    stepping	: 4
    microcode	: 0x415
    cpu MHz		: 2500.058
    cache size	: 25600 KB
    physical id	: 0
    siblings	: 2
    core id		: 0
    cpu cores	: 1
    apicid		: 0
    initial apicid	: 0
    fpu		: yes
    fpu_exception	: yes
    cpuid level	: 13
    wp		: yes
    flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology eagerfpu pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm xsaveopt fsgsbase smep erms
    bogomips	: 5000.11
    clflush size	: 64
    cache_alignment	: 64
    address sizes	: 46 bits physical, 48 bits virtual
    power management:

    processor	: 1
    vendor_id	: GenuineIntel
    cpu family	: 6
    model		: 62
    model name	: Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
    stepping	: 4
    microcode	: 0x415
    cpu MHz		: 2500.058
    cache size	: 25600 KB
    physical id	: 0
    siblings	: 2
    core id		: 0
    cpu cores	: 1
    apicid		: 1
    initial apicid	: 1
    fpu		: yes
    fpu_exception	: yes
    cpuid level	: 13
    wp		: yes
    flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology eagerfpu pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm xsaveopt fsgsbase smep erms
    bogomips	: 5000.11
    clflush size	: 64
    cache_alignment	: 64
    address sizes	: 46 bits physical, 48 bits virtual
    power management:

    $ cat Dockerfile
    FROM ubuntu:trusty
    RUN apt-get -y update && apt-get -y dist-upgrade && apt-get -y clean all
    RUN apt-get install -y -qq wget redis-server
    RUN \
        cd /opt && \
        wget http://nodejs.org/dist/v0.12.2/node-v0.12.2-linux-x64.tar.gz && \
        tar -xzf node-v0.12.2-linux-x64.tar.gz && \
        mv node-v0.12.2-linux-x64 node && \
        cd /usr/local/bin && \
        ln -s /opt/node/bin/* . && \
        rm -f /opt/node-v0.12.2-linux-x64.tar.gz

    COPY ./ /opt/<>/webapp/
    ENV PORT=3000
    ENV NODE_ENV=production
    WORKDIR /opt/<>/webapp
    EXPOSE 3000

I initially produced this with an internal application, however I was also able to reproduce it using the `google/nodejs_hello` repository as well (just to a less dramatic effect - 400 TPS became 520 TPS). To reproduce, create a container with a Node.js application, run multiples of this container (I did 4 on a 2 core box), and apply load (I used JMeter with 16 threads). Then, I stopped all four containers, and ran `/bin/bash` in one of them, and started four node instances from the command line and applied the same load once more.

The symptoms were that CPU usage on the box was abnormally low for pushing four node.js processes to their limits, and running an `strace -c` showed that the wait was all in `futex` and `epoll` syscalls. Running `strace` directly on them displayed that they were all calling using the same memory address for the `FUTEX_WAIT` and `FUTEX_WAKE` calls (this does not occur when running all four instances inside one container). This is what lead us to try the "four services in one container" test, which showed more appropriate CPU usage, and a dramatic increase in throughput.

The expected behavior is that two applications in separate containers would be unable to acquire a FUTEX on the same memory location.

**Comment by garrickp** [comment]
We have narrowed this down to AUFS. We moved to AUFS to mitigate the problems from the infamous Ubuntu 14.04 devicemapper problems outlined [here](https://github.com/docker/docker/issues/4036). This is a pretty unfortunate situation; until docker 1.7, it seems like the only option is realistically backport the dynamic library option and build our own docker.

**Comment by unclejack** [comment]
@garrickp There's nothing to backport. Dynamically linked Docker binaries can be built on Ubuntu using similar steps to https://github.com/docker/docker/issues/4036#issuecomment-70525473.
The main command is `AUTO_GOPATH=1 DOCKER_BUILDTAGS="btrfs_noversion" ./project/make.sh dynbinary` in the source tree of Docker.

**Comment by garrickp** [comment]
Documenting the full build (unable to test yet) for posterity, running from a system provisioned to make go binaries:

    git clone https://github.com/docker/docker.git
    git checkout release
    apt-get install libsqlite3-dev libdevmapper-dev btrfs-tools
    AUTO_GOPATH=1 DOCKER_BUILDTAGS="btrfs_noversion" hack/make.sh dynbinary

And verifying the dynamic nature of it:

    vagrant@vagrant-ubuntu-trusty-64:~/docker$ ldd bundles/1.6.2/dynbinary/docker
	linux-vdso.so.1 =>  (0x00007fff4f5fe000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f765670f000)
	libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007f7656456000)
	libdevmapper.so.1.02.1 => /lib/x86_64-linux-gnu/libdevmapper.so.1.02.1 (0x00007f765621c000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7655e56000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7656937000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7655c52000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f7655a2e000)
	libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007f765581d000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f76555df000)
	libcgmanager.so.0 => /lib/x86_64-linux-gnu/libcgmanager.so.0 (0x00007f76553c3000)
	libnih.so.1 => /lib/x86_64-linux-gnu/libnih.so.1 (0x00007f76551ab000)
	libnih-dbus.so.1 => /lib/x86_64-linux-gnu/libnih-dbus.so.1 (0x00007f7654fa1000)
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007f7654d5b000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f7654b53000)

Hopefully this will be sufficient. And hopefully this will help someone else running into this same issue. Perhaps the cross-container lock on shared image files can be mentioned as a downside to using the AUFS file system in the documentation?

This is what it looks like with AUFS:

    root@docker-vagrant:~# strace -p 22899 -c
    Process 22899 attached
    ^CProcess 22899 detached
    % time     seconds  usecs/call     calls    errors syscall
    ------ ----------- ----------- --------- --------- ----------------
     44.63    0.003531           2      1464           futex
     25.81    0.002042           1      1467           epoll_wait
     11.89    0.000941           2       549           epoll_ctl
      9.95    0.000787           4       183           write
      4.56    0.000361           2       183           close
      1.81    0.000143           0       366       183 accept4
      1.35    0.000107           0      1098           read
    ------ ----------- ----------- --------- --------- ----------------
    100.00    0.007912                  5310       183 total

vs with devicemapper:

    root@docker-vagrant:~# sudo strace -p 24822 -c
    Process 24822 attached
    ^CProcess 24822 detached
    % time     seconds  usecs/call     calls    errors syscall
    ------ ----------- ----------- --------- --------- ----------------
     61.54    0.001205          11       110           close
     21.60    0.000423           1       662           epoll_wait
      7.87    0.000154           0       330           write
      3.93    0.000077           0       220       110 accept4
      2.35    0.000046           0       330           read
      1.94    0.000038           0       440           epoll_ctl
      0.72    0.000014           0       110           getpeername
      0.05    0.000001           0         4           munmap
      0.00    0.000000           0         4           mmap
      0.00    0.000000           0         2           brk
    ------ ----------- ----------- --------- --------- ----------------
    100.00    0.001958                  2212       110 total

**Comment by MrMMorris** [comment]
@garrickp is this something you have since resolved by moving away from AUFS? 

I am in the same situation (running node, was using devicemapper, not AUFS) and haven't checked to see if we are running into Futex contentions, but it would be good to know if I should be looking to move to Overlay or ZFS or something :smile:

**Comment by garrickp** [comment]
@MrMMorris The futex contention with the simplest node server did indeed disappear upon moving to device mapper, but the more complicated program (i.e. our actual webapp) is still acquiring futexes across containers (and within containers). We haven't had the opportunity to dig into this further, or try other file systems.

**Comment by Rucknar** [comment]
Anyone get any further tracking this one down? I've noticed that futex's are by far our most contended system calls. Example output from sysdig: 

```
[2J[0;0HTime                Syscall             

--------------------------------------------------------------------------------

697.75s             futex
52.58s              switch
29.13s              epoll_wait
27.11s              nanosleep
24.23s              accept
19.46s              poll
16.82s              read
11.07s              wait4
4.46s               select
36ms                close
28ms                recvfrom
28ms                write
27ms                open
15ms                getdents64
15ms                connect
10ms                stat
6.45ms              mmap
6.01ms              fsync
5.27ms              socket
5.22ms              sendto
5.08ms              execve
4.04ms              fstat
3.21ms              getdents
2.71ms              clone
2.53ms              writev
2.53ms              epoll_ctl
1.98ms              sendmsg
1.17ms              mprotect
887us               fcntl
```

Key difference for us i guess is that the majority of our containers are running tomcat, not node.

**Comment by justincormack** [comment]
The memory locations you see on `strace` are in the application's address space, so that just means the application is being loaded into the same virtual address space in each container, not that it is technically the same futex, as futexes are really in physical not virtual memory addresses.

That does not answer why there is an issue though, or indeed why the virtual memory addresses are different if you run multiple copies in one container. It would really help to work out what the futex is a lock for in order to debug further. The fact that it varies with graph driver suggests it might be filesystem related - maybe you could try running the application entirely in a tmpfs mount in the container? Does it use files much in the application?

**Comment by garrickp** [comment]
I no longer have access to the application which triggered this behavior initially. The disk usage was not abnormally high under load; the code was loaded into memory and served from memory from there out.

Sorry I'm unable to assist further on this issue.
