### ISSUE TITLE
Can't mount file when in /usr/local

### ISSUE THREAD

**Issue by guillaumewuip** [docker/docker#13276]
I think I've found something strange.

When I'm in a `/usr/local/` subfolder I can't mount a file into container.

To reproduce :
```
$ cd /usr/local/test/subTest
$ ls -l 
total 0
-rw-r--r--  1 Guillaume  admin  0 16 mai 13:04 nginx.conf
$ docker run --name nginx -d -p 8080:80 \ 
   --add-host host:$(boot2docker ip) \
   -v $(pwd)/nginx.conf:/etc/nginx/nginx.conf \
   nginx
FATA[0000] Error response from daemon: Cannot start container f9a8da81489bf1222e75e5b1b3906a9a184d1482a1e004b3dc655c4fb15ee558: [8] System error: not a directory
$ docker stop nginx && docker rm nginx
```
Expect same result that :
```
$ cd ~/Desktop/tmp/
$ ls -l 
total 8
-rw-r--r--+ 1 Guillaume  staff  735 16 mai 13:08 nginx.conf
$ docker run --name nginx -d -p 8080:80 \ 
   --add-host host:$(boot2docker ip) \
   -v $(pwd)/nginx.conf:/etc/nginx/nginx.conf \
   nginx
f2f1b18269ef958309eaa85f774db238503c076687017d818f42a8943d621f1a
```

I'm using boot2docker on OSX.
`boot2docker version`
`Boot2Docker-cli version: v1.6.2
Git commit: cb2c3bc`

`docker -v`
`Docker version 1.6.2, build 7c8fca2`

`docker info`
```
Containers: 1
Images: 77
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 83
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 4.0.3-boot2docker
Operating System: Boot2Docker 1.6.2 (TCL 5.4); master : 4534e65 - Wed May 13 21:24:28 UTC 2015
CPUs: 8
Total Memory: 1.957 GiB
Name: boot2docker
ID: RGHJ:6UUO:ETVO:UMMN:VTTD:CJAK:5X3B:ABCG:OHYZ:6JG6:BF4S:PFK7
Debug mode (server): true
Debug mode (client): false
Fds: 11
Goroutines: 16
System Time: Sat May 16 11:28:05 UTC 2015
EventsListeners: 0
Init SHA1: 7f9c6798b022e64f04d2aff8c75cbf38a2779493
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
```

`uname -a`
`Darwin Mac-mini.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64`

**Comment by guillaumewuip** [comment]
Actually the problem could be not only with files, but with full directories too.
In `/usr/local/test/subTest`, I'm trying to use `-v $(pwd)/store:/src/store` but it the container `/src/store` directory is empty.

**Comment by thaJeztah** [comment]
This is not a bug. Boot2Docker by default only shares the `/Users` OS X directory with VBox Guest Additions (see https://github.com/boot2docker/boot2docker#virtualbox-guest-additions). Directories outside of that folder (by default) are not shared with the Boot2Docker virtual machine, so those directories don't exist there, resulting in Docker *creating* an empty directory at the specificed path.

**Comment by guillaumewuip** [comment]
Ok thanks @thaJeztah. Sorry for the post :)

**Comment by thaJeztah** [comment]
@guillaumewuip no problem, hope you get it working with the extra info I gave you!
