### ISSUE TITLE
How to change docker engine ID?

### ISSUE THREAD

**Issue by quickwind** [docker/docker#13278]
We have a ESXi env, and we setup one VM and installed docker, then we clone it into multiple VMs, but we found the docker engine ID is the same for all the docker engines, and couldn't find a way to change it. This prevents us to use swarm to create cluster properly. Anything we missed?

docker info output:

Containers: 12
Images: 251
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 435
Execution Driver: native-0.2
Kernel Version: 3.16.0-30-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 15.67 GiB
Name: xxxxx
ID: 33Z5:BE33:KSMC:S4GY:GRDO:EH5E:5T7G:GNHG:ENHZ:XRBE:ANQB:SBSV

**Comment by devinwatkins** [comment]
I ran into something similar.  I was able to fix this by deleting our docker ```key.json``` file then restarting the daemon.  For me the file was in ```/etc/docker/key.json```

**Comment by quickwind** [comment]
Thanks @devinwatkins , it works for me:) Closing the issue...

**Comment by icebob** [comment]
Great! Thank you @devinwatkins !

**Comment by semad** [comment]
Thank you @devinwatkins !

**Comment by KuaJnio** [comment]
Thank you @devinwatkins  for the answer, didn't know how the ID was generated, i guess i must have cloned my SD card and forgot that

Regards
