### ISSUE TITLE
java application memory limit fails

### ISSUE THREAD

**Issue by allencloud** [docker/docker#13289]
Hi, All, 

I ran into an issue that Docker Daemon failed to limit a Java application's memory.  I have already searched keyword "java",  "memory", "limit", "fail", and found nothing related. Did cgroups filesystem fail to limit this container's memory? It is really weird.

Below is the details:

<pre>docker ps : 
25248ca03b7f        app                  "tomcat/bin/catalina   42 hours ago        Up 42 hours         0.0.0.0:61048->8080/tcp

docker stats:
25248ca03b7f        0.12%               <b>525.5 MiB</b>/11.74 GiB   4.37%               89.95 KiB/276.4 KiB

docker inspect 25248ca03b7f:
[{
...
"Config":{
        "Memory": <b>134217728,      (128MB)</b>
        "MemorySwap": <b>134217728</b>,
}
...
}
]

docker top 2524:
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
root                9179                14463               0                   May16               pts/6               00:00:00            /bin/bash
root                26946               14463               0                   May16               ?                   00:04:12            java -Djava.util.logging.config.file=/tomcat/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djava.endorsed.dirs=/tomcat/endorsed -classpath /tomcat/bin/bootstrap.jar:/tomcat/bin/tomcat-juli.jar -Dcatalina.base=/tomcat -Dcatalina.home=/tomcat -Djava.io.tmpdir=/tomcat/temp org.apache.catalina.startup.Bootstrap start

docker info:
Containers: 11
Images: 20
Storage Driver: devicemapper
 Pool Name: docker-253:16-5505030-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file:
 Metadata file:
 Data Space Used: 42.62 GB
 Data Space Total: 536.9 GB
 Data Space Available: 494.2 GB
 Metadata Space Used: 72.97 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.075 GB
 Udev Sync Supported: false
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.13.0-49-generic
Operating System: Ubuntu 14.04 LTS
CPUs: 2
Total Memory: 11.74 GiB
Name: vm
ID: UK4I:SBAD:ERKA:TXRK:8TEN:PDBO:KLKY:VSKX:TFY3:HNKB:VLBD:YABW

docker version:
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64

uname -a:
Linux vm 3.13.0-49-generic #83-Ubuntu SMP Fri Apr 10 20:11:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

</pre>

**Comment by hqhq** [comment]
Hi,

How did you run your container? Parse the exactly command would help, and can you try on the latest Docker? `Memroy` is now in `HostConfig` instead of `Config`.
Cgroup don't care your application is Java or anything else.

**Comment by allencloud** [comment]
Thank you very much. @hqhq    And I use docker-client to run container. I checked my HostConfig, and I missed memory data in it.
