### ISSUE TITLE
Read Only Error on yosemite MacOsX

### ISSUE THREAD

**Issue by bussiere** [docker/docker#13288]
May be linked to this : https://forums.docker.com/t/docker-image-building-read-only-error/1561

root@boot2docker:/Users/bussiere/Documents# docker load < choual.tar 
FATA[0902] Error response from daemon: mkdir /mnt/sda1/var/lib/docker/tmp/docker-import-660441420: read-only file system 

root@boot2docker:/Users/bussiere/Documents# docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

The same thing worked fine (same tar) on windows & Ubuntu

**Comment by bussiere** [comment]
Description of problem:
A read error on Yosemite : root@boot2docker:/Users/bussiere/Documents# docker load < choual.tar
FATA[0902] Error response from daemon: mkdir /mnt/sda1/var/lib/docker/tmp/docker-import-660441420: read-only file system  When trying to load a tar. This tar and the load worked on my ubuntu computer and windows 8 computer. It just messed on the Yosemite Macosx computer

`docker version`:
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

`docker info`:
docker@boot2docker:~$ docker info
Containers: 0
Images: 0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 4.0.3-boot2docker
Operating System: Boot2Docker 1.6.2 (TCL 5.4); master : 4534e65 - Wed May 13 21:24:28 UTC 2015
CPUs: 4
Total Memory: 1.957 GiB
Name: boot2docker
ID: FECS:FE3C:DW5T:ONXX:AIQL:PCG2:T7A4:OE36:HE5J:WNE6:72ZR:TU6T
Debug mode (server): true
Debug mode (client): false
Fds: 11
Goroutines: 16
System Time: Mon May 18 03:14:34 UTC 2015
EventsListeners: 0
Init SHA1: 7f9c6798b022e64f04d2aff8c75cbf38a2779493
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker


`uname -a`:
Linux boot2docker 4.0.3-boot2docker #1 SMP Wed May 13 20:54:49 UTC 2015 x86_64 GNU/Linux


Environment details (AWS, VirtualBox, physical, etc.):
Boot2docker on Yosemite


How reproducible:


Steps to Reproduce:
1. Launch Boot2docker
2.Go to /User/Documents/Bussiere/
3. type : docker load < choual.tar


Actual Results:
root@boot2docker:/Users/bussiere/Documents# docker load < choual.tar
FATA[0902] Error response from daemon: mkdir /mnt/sda1/var/lib/docker/tmp/docker-import-660441420: read-only file system 

Expected Results:
I would liked to get the choual.tar imported so that i can run it. ( It's the natural state for a horse.)


Additional info:

Seems to have read / write error on yosemite on the forum : https://forums.docker.com/t/docker-image-building-read-only-error/1561 it may be related

**Comment by ashgillman** [comment]
I get a similar error regularly when attempting a build.

> $ docker build .
> docker build .
> Sending build context to Docker daemon 3.072 kB
> Error response from daemon: mkdir /mnt/sda1/var/lib/docker/tmp/docker-build887969595: read-only file system

It can be fixed by re-running the initialisation script, which restarts the server:
> . '/Applications/Docker/Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh'

But it is NOT due to inconsistent docker environment variables

I am running OSX Yosemite 10.10.4
> $ docker version
> Client:
>  Version:      1.8.1
>  API version:  1.20
>  Go version:   go1.4.2
>  Git commit:   d12ea79
>  Built:        Thu Aug 13 02:49:29 UTC 2015
>  OS/Arch:      darwin/amd64
>
> Server:
>  Version:      1.8.1
>  API version:  1.20
>  Go version:   go1.4.2
>  Git commit:   d12ea79
>  Built:        Thu Aug 13 02:49:29 UTC 2015
>  OS/Arch:      linux/amd64
> $ docker-machine --version
> docker-machine version 0.4.1 (e2c88d6)
> $ vboxmanage --version
> 5.0.2r102096

**Comment by ashgillman** [comment]
And I should add the "default" vm is definitely still running on Virtualbox

**Comment by matteobachetti** [comment]
Hi,
Are there any news on this issue? I have a similar problem, and I see that there is a number of possible related issues discussed here and there, but I don't see any solution or workaround available.
The actual file and error message changes from time to time, e.g.
```
$ cat pulsar.tar | docker import - pulsar
Error response from daemon: mkdir /mnt/sda1/var/lib/docker/graph/_tmp/92f78f30b2b01805c9f0be1e6c61083298c6141dee3a6252062099c740cfdb0a: read-only file system

$ cat pulsar.tar | docker import - pulsar
Error response from daemon: Untar re-exec error: exit status 1: output: write (...)/pgdemo13: read-only file system
```
Thanks in advance for your help.

**Comment by camilonova** [comment]
I'm having this issue as well, any updates?

**Comment by gustavo-hp** [comment]
Here too, check my configurations on the following guist>   https://gist.github.com/gustavo-hp/b7afa60a54bd6bf5ee1c00d82324c06d

**Comment by devisscher** [comment]
Have the same issue as well. 
```
Sending build context to Docker daemon 4.096 kB
Error response from daemon: mkdir /mnt/sda1/var/lib/docker/tmp/docker-builder882554616: read-only file system 

```

**Comment by ycherfan** [comment]
Same issue here when trying to run a docker image:

$ docker run -d --name php-fpm mageinferno/magento2-php
Unable to find image 'mageinferno/magento2-php:latest' locally
latest: Pulling from mageinferno/magento2-php
d4bce7fd68df: Pull complete 
a3ed95caeb02: Pull complete 
77a07a807b0b: Pull complete 
8e9dd06f34b8: Downloading [==================================================>] 69.23 MB/69.23 MB
bdeb40d51bd7: Download complete 
51bdf6163dd0: Download complete 
6896ffaaee49: Download complete 
a81715563078: Download complete 
05267d44316e: Download complete 
75632b051906: Downloading [==================================================>] 65.04 MB/65.04 MB
d726f4d99dec: Download complete 
00e649933bdb: Downloading [==================================================>] 6.314 MB/6.314 MB
247079f11a76: Waiting 
1d0ce8dd434e: Waiting 
c1a5388efd89: Downloading [==================================================>]   885 kB/885 kB
2a46f4754761: Waiting 
ba3be71b5085: Waiting 
e9f3729db7b7: Waiting 
docker: open /mnt/sda1/var/lib/docker/tmp/GetImageBlob806286343: read-only file system.
See 'docker run --help'.

System info:

OS X Yosemite 10.10.5

$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64


$ docker info   
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 0
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.1.19-boot2docker
Operating System: Boot2Docker 1.10.3 (TCL 6.4.1); master : 625117e - Thu Mar 10 22:09:02 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: HO6V:BKA2:KSXD:6KGO:H4V3:QKA2:GXVV:AGRG:UR4H:2AA6:UMLC:KBEU
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 27
 System Time: 2016-04-24T19:38:13.43667385Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox


$ uname -a
Darwin laranjeiras 14.5.0 Darwin Kernel Version 14.5.0: Mon Jan 11 18:48:35 PST 2016; root:xnu-2782.50.2~1/RELEASE_X86_64 x86_64

**Comment by thebenjy** [comment]
i have same problem el capitan (using docker package docker quick start terminal)

$ docker version
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64

Darwin imac.local 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64

**Comment by cpuguy83** [comment]
This does not look like a Docker issue.

You'll usually get this error ("usually" in the since of you weren't expecting to hit a read-only disk) when there is a consistency issue in the filesystem.
You'd need to run an fsck on the filesystem in question (or you can try to re-mount as read-write).

**Comment by thebenjy** [comment]
thanks brian - thats good to understand - do you mean the file system of the host or of the container OS?

**Comment by cpuguy83** [comment]
They are one in the same.

**Comment by rjurney** [comment]
I have this problem as well, and my disk is without errors. This is a real problem.

**Comment by jhrf** [comment]
I was experiencing this problem on Mac OSX 10.13.3 (High Sierra)

Fixed by a simple restart of docker.

**Comment by matzero** [comment]
Simply restarting Docker for Mac worked for me.

**Comment by james-innes** [comment]
Same issue but on Windows and WSL2
