### ISSUE TITLE
Proposal: provide API for dockerfile parser

### ISSUE THREAD

**Issue by TomasTomecek** [docker/docker#13293]
When we build layered images, we tend to parse and edit dockerfiles. I think it would be really benefitial to have one, single codebase which would be responsible for parsing dockerfiles: the docker itself.

Therefore I would like to propose to have a new command in docker's CLI which would use the native parser of dockerfiles and would be capable of providing serializable output.

Motivation behind this is that when we parse dockerfiles with our custom parser, we can't be sure how the instructions will be parsed during build (will it strip whitespace? what happens with `\` in multiline instructions? what is the precise syntax for `LABEL`s?)

In case of positive feedback, I'll provide more thorough proposal with specification of the output and the whole interface.

**Comment by cpuguy83** [comment]
I'm not sure I understand this request.
The Dockerfile parser is an importable package you can consume with any go code.

There are talks of moving the builder client side... this is not final.
The only required API to do this is the ability to inject new files to a container. PR for this is #13171

**Comment by TomasTomecek** [comment]
I would like to have something like:
```
$ docker parse-dockerfile ./path/to/Dockerfile
[
  {"from": "fedora:21"},
  {"cmd": "yum -y update"},
  {"label": {"key": "value"}},
  ...
]
```

**Comment by cpuguy83** [comment]
But to what end?

**Comment by TomasTomecek** [comment]
As I said in my original post: right now, we have our own codebase (*not* go) for parsing dockerfiles. That's pretty bad because the parser is probably different from the one in builder. That means that every time I change something, I need to check that our parser is consistent with the one in builder.

It would be way easier if the parser of builder had API where I would stuff my dockerfile and get serialized output -- same data which docker operates with when it builds the image.

Also, having special command would also verify that the dockerfile is valid.

**Comment by cpuguy83** [comment]
Closing this as it really needs to be an external tool. The tool can import the parser directly to output the ast/json/whatever for you.

**Comment by TomasTomecek** [comment]
I don't understand why it needs to be an external tool. I guess it shouldn't be hard to create one.

**Comment by erikh** [comment]
Hi, when I wrote the parser I wrote a dumping tool:

`go get github.com/docker/docker/builder/parser/dumper` should install a version that represents the parse tree when handed dockerfiles. We use this same facility that it exposes to test the parser itself. If it doesn't work, whoever broke it should probably fix it.

**Comment by TomasTomecek** [comment]
@erikh Thanks!

I actually started working on it yesterday and indeed I took your dumper: https://github.com/TomasTomecek/parse-dockerfile

It can't do anything yet, I'm still working on the json serialization.

**Comment by erikh** [comment]
Cool!
