### ISSUE TITLE
mc crashes docker (boot2docker 1.6.2) under windows

### ISSUE THREAD

**Issue by rshmelev** [docker/docker#13299]
Docker panics with go stacktrace when I try to run mc (i'm using latest boot2docker under windows)  
I've tried to find similar issue here but failed... 

`docker version`:
```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): windows/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

`docker -D info`:
```
Containers: 10
Images: 13
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 33
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 4.0.3-boot2docker
Operating System: Boot2Docker 1.6.2 (TCL 5.4); master : 4534e65 - Wed May 13 21:24:28 UTC 2015
CPUs: 8
Total Memory: 1.957 GiB
Name: boot2docker
ID: N46B:V4BQ:K7PV:DPH3:QLKS:LRH3:HCDO:KFRY:UCVB:DOA5:XWL5:AGMX
Debug mode (server): true
Debug mode (client): true
Fds: 29
Goroutines: 54
System Time: Mon May 18 11:47:02 UTC 2015
EventsListeners: 0
Init SHA1: 7f9c6798b022e64f04d2aff8c75cbf38a2779493
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
```

`uname -a`:
```
MINGW32_NT-6.1 FF-VAIO 1.0.12(0.46/3/2) 2012-07-05 14:56 i686 unknown
```

Environment details (AWS, VirtualBox, physical, etc.):  
my laptop Sony Vaio, Windows 7 64bit professional, VirtualBox 4.3.28 (r100309), latest boot2docker 1.6.2

How reproducible:  
Always

Steps to Reproduce:   

1. `run boot2docker environment using desktop shortcut`
2. `$ docker run -it ubuntu bash`
3. `root@29a99d9ef82b:/# apt-get update && apt-get install mc -y`
4. `root@29a99d9ef82b:/# mc`

Actual Results:    
The following stacktrace: http://pastebin.com/BzF19Hb6  
The most interesting part is:   
```
panic: runtimerror: slice bounds out of range
 goroutine 12 [running]:
bufio.(*Reader).fill(0xc08212a360)
        /usr/local/go/src/bufio/bufio.go:86 +0x2e2
bufio.(*Reader).WriteTo(0xc08212a360, 0x2972778, 0xc082008c30, 0x9b02, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:449 +0x285
io.Copy(0x2972778, 0xc082008c30, 0x2974bc8, 0xc08212a360, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:354 +0xb9g ftps: 'cd ftp://user@machine.edu'
github.com/docker/docker/api/client.funcT¬022(0x0, 0x0)
        /go/src/github.com/docker/docker/api/client/hijack.go:210 +0x1e0
...
```

Expected Results:   
mc start :)

Additional info:   
tried to follow basic tutorial, not sure what is wrong, starting mc -b -d also crashes it, but without stacktrace

**Comment by thaJeztah** [comment]
ping @ahmetalpbalkan @jhowardmsft

**Comment by jhowardmsft** [comment]
Yup, very familiar stack trace - I've seen this many, many times. It should be fixed by this PR: https://github.com/docker/docker/pull/13224 with the ANSI emulation rewrite in the Windows client. One workaround which may suffice is to use ConEMU rather than cmd for now. @gabrielhartmann @brendondixon.  (BTW @thaJeztah - you generally want Ahmet for client things, myself with the daemon port to Windows).

**Comment by thaJeztah** [comment]
@jhowardmsft doh! You're right, I thought you were working on the ANSI-emulation as well, my bad

@gabrielhartmann Let me know if your want this issue to stay opened; I found some other issues related to the CLI rewrite, but this looked slightly different.

**Comment by ahmetalpbalkan** [comment]
@thajeztah the rewrite hasnt been done. This is old code running. And error is a known issue and filed under several other issues under os/windows I believe.

**Comment by gabrielhartmann** [comment]
You can leave the issue open for now. I believe the rewrite probably fixes this, but I will verify and then close.

**Comment by thaJeztah** [comment]
@ahmetalpbalkan sorry, I put it in words badly; I know the rewrite wasn't done yet, meant to say; "issues that will benefit from the rewrite"

**Comment by GotCode** [comment]
I ran Boot2Docker Version 1.6.2 on Windows 10 Enterprise Preview and the VirtualBox app failed to start the Docker-vm with this error:
![docker-vm error](https://cloud.githubusercontent.com/assets/586999/7971805/5a76c626-09fc-11e5-8d8e-8f35c1de06d8.png)

Result Code: 
VBOX_E_VM_ERROR (0x80BB0003)
Component: 
Machine
Interface: 
IMachine {480cf695-2d8d-4256-9c7c-cce4184fa048}
Callee RC: 
E_FAIL (0x80004005)

**Comment by jhowardmsft** [comment]
@GotCode that looks like it's a problem with Virtual Box not running properly on Windows 10 rather than a docker issue. Can you run any VM under VirtualBox? If not, sounds like a support call to VB....

**Comment by GotCode** [comment]
I can run Ubuntu or any Windows VM with VirtualBox.   They all run fine.

**Comment by jhowardmsft** [comment]
@GotCode - sorry then, really no idea. I don't use B2D or VirtualBox myself

**Comment by gabrielhartmann** [comment]
mc now works with the new terminal emulation code.  It's not as pretty as in a native Ubuntu environment, but it is functional, doesn't crash and seems to operate correctly.  It's not a tool I use, so I don't know how to do a thorough test of it.

**Comment by gabrielhartmann** [comment]
This PR has the fixes which address this issue: https://github.com/docker/docker/pull/13224

**Comment by cpuguy83** [comment]
Is this resolved now that the ansi rewrite is in?

**Comment by ahmetalpbalkan** [comment]
@cpuguy83 it fails with a different error in this rewrite:

![image](https://cloud.githubusercontent.com/assets/159209/9865513/68adcee0-5b0c-11e5-808a-374b940e6937.png)

I think `mc` is a bit of an extreme example. ANSI emulation we implemented is quite minimalistic and handles many management tools and editors like vim/emacs/nano well. Programs like `mc` or images such as `supertest2014/nyan` will not work anytime soon. cc: @jstarks

**Comment by jstarks** [comment]
I don't intend to improve the ANSI emulation code any further at the moment. PRs certainly welcome, though.

**Comment by thaJeztah** [comment]
Closing, following @jstarks's comment, but I think some additional improvements were made recently

**Comment by jstarks** [comment]
With the latest Docker client and the latest insider version of Windows 10, we can use the inbox terminal emulation (like Docker does on every other platform). It would be interesting to see how well mc works in this environment.
