### ISSUE TITLE
Remove redunant else clauses

### ISSUE THREAD

**Issue by runcom** [docker/docker#13296]
There are some redunant else clauses to be removed:

- `api/client/help.go:26`
- `daemon/networkdriver/bridge/driver.go:312`
- `daemon/networkdriver/bridge/driver.go:330`
- `pkg/units/duration.go:29`

Please reference this issue from the PR so this can be automagically closed!

**Comment by WeiZhang555** [comment]
#dibs

**Comment by runcom** [comment]
closed by #13311
