### ISSUE TITLE
RFE: inspect should return or reconstruct original command to docker run 

### ISSUE THREAD

**Issue by PAStheLoD** [docker/docker#13302]
Hello!

It comes up pretty frequently, and I know that the docker CLI is just but one client, however, the productivity gain would be very much welcome, because copy-pasting and/or parsing JSON back to a shell command is currently rather tiresome and error prone. (Especially considering that one has to know that CMD goes at the end of the command line, VOLUME before IMAGE and so on, all of which inspect conveniently lists in lexicographic ordering :)) 

See also #11460 and #9924, #9150.

Thanks for considering (even though a similar ticket has been closed)!

**Comment by cpuguy83** [comment]
Closing this for the same reasons that the other one was closed.
The Docker CLI is an API client. You can use the output of `docker inspect` to re-construct an equivalent `docker run`.
