### ISSUE TITLE
Consider increasing (or allowing configuration of) connection timeout for registry related operations

### ISSUE THREAD

**Issue by lightsofapollo** [docker/docker#13307]
At Mozilla we use Docker _mostly_ for CI on AWS ( at a fairly large scale so 1k~ or so machines running at a time if not more). Generally this works just fine but we hit some issues with the inflexibility of timeouts in docker when pull images in particular connection timeouts.

Can we increase the defaults to something like 30s or add config flags?

----

See:

https://github.com/docker/docker/blob/756b8f2fde210da5529e0a5480e149917ab25524/registry/registry.go#L53-L56

**Comment by LK4D4** [comment]
@lightsofapollo I think we can and it is reasonable to add daemon flag.
ping @docker/core-maintainers

**Comment by duglin** [comment]
Yup - config options are good.
At some point I do wonder whether it would be better to stop adding new cmd line flags and just read these things from a config file.

**Comment by LK4D4** [comment]
@duglin I think cmd flags and config should duplicate each other forever.

**Comment by lightsofapollo** [comment]
Can I up it to something higher then 5s by default to start? 5s is pretty low all considering?

**Comment by lightsofapollo** [comment]
Actually the ideal would be (particularly now we are in a registry v2 world) to retry this whole process with some sort of exponential backoff (or again allow it to be configured)

**Comment by LK4D4** [comment]
@lightsofapollo I think you can. You're experiencing problems, timeout really relatively low, so why not.

**Comment by unclejack** [comment]
+1 for config options

I wouldn't want to wait for so long to get an error if there are connectivity issues.
