### ISSUE TITLE
Install of docker.io is not available in the jessie-backports repo

### ISSUE THREAD

**Issue by mcattell** [docker/docker#13305]
The install instructions for Debian jessie are incorrect. They advise adding the jessie-backports repo to your source.list and updating. Then to use apt-get -t jessie-backports install "docker.io". Unfortunately, docker.io is missing from the said repository. Please update the documentation as I've just wasted time messing around when I could have just used the Ubuntu install instructions.

**Comment by vdemeester** [comment]
@mcattell see https://github.com/docker/docker/issues/13253 (duplicate)

**Comment by vdemeester** [comment]
@mcattell see https://github.com/docker/docker/issues/13253 (duplicate) it has been update in this PR : https://github.com/docker/docker/pull/13104/ (but not up-to-date on the website)

**Comment by cpuguy83** [comment]
Closing this one.
