### ISSUE TITLE
event notify without container name

### ISSUE THREAD

**Issue by linlinlinlin** [docker/docker#13316]
Description of problem:
           For the container state change event: ``die`` or ``destroy``.
           Sometimes it will response without container name, but still with container id.

    `docker version`: 
            Client version: 1.6.0
            Client API version: 1.18
            Go version (client): go1.4.2
            Git commit (client): 7ad12e4
            OS/Arch (client): linux/amd64
            Server version: 1.6.0
            Server API version: 1.18
            Go version (server): go1.4.2
            OS/Arch (server): linux/amd64

    `docker info`: 
            Containers: 4
            Images: 78
            Storage Driver: aufs
             Root Dir: /var/lib/docker/aufs
             Backing Filesystem: extfs
             Dirs: 86
             Dirperm1 Supported: false
            Execution Driver: native-0.2
            Kernel Version: 3.13.0-49-generic
            Operating System: Ubuntu 14.04.2 LTS
            CPUs: 2
            Total Memory: 1.955 GiB
            Name: trusty-64
            ID: DDNH:IHQY:FIUR:WZEF:JPZW:4WBP:DALO:RANJ:IATJ:ZPLP:X3GN:SM4W
            Registry: [https://index.docker.io/v1/]

    `uname -a`:
            Linux trusty-64 3.13.0-49-generic #83-Ubuntu SMP Fri Apr 10 20:11:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

    Environment details:
             VirtualBox

    How reproducible:
              Just continuously stop or destroy running containers. 

    Actual Results:
             Event notify without container name sometimes

    Expected Results:
             Event notify with container name every time

**Comment by runcom** [comment]
@linlinlinlin pretty sure container name isn't logged at all in docker events (https://github.com/docker/docker/blob/master/daemon/container.go#L205) so maybe I'm missing something here. Do you expect to get the container name in docker events? Btw I'm testing this on docker 1.6.2 so almost sure container name isn't logged

**Comment by linlinlinlin** [comment]
Sorry I make a mistake here. Just ignore this issue.
