### ISSUE TITLE
A new container is created every time I run a command

### ISSUE THREAD

**Issue by GCorbel** [docker/docker#13317]
This issue can be view [on the forum](https://forums.docker.com/t/not-able-to-install-anything-with-apt-get-on-a-docker-container/1595).

Description of problem:

I just created a new container with this command docker pull ubuntu. It created a new container as expected. When I run docker run -t -i ubuntu apt-get install wget it install wget. When I run it a second time, it install wget again. When I start bash, wget is not found.

I seen than every time a run a command, a new container.

`docker version`:

    Client version: 1.6.2
    Client API version: 1.18
    Go version (client): go1.4.2
    Git commit (client): 7c8fca2
    OS/Arch (client): linux/amd64
    Server version: 1.6.2
    Server API version: 1.18
    Go version (server): go1.4.2
    Git commit (server): 7c8fca2
    OS/Arch (server): linux/amd64

`docker info`:

    Containers: 126
    Images: 180
    Storage Driver: aufs
     Root Dir: /var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 432
     Dirperm1 Supported: false
    Execution Driver: native-0.2
    Kernel Version: 3.13.0-24-generic
    Operating System: Ubuntu 14.04.1 LTS
    CPUs: 4
    Total Memory: 15.64 GiB
    Name: oscar
    ID: UZ7F:4DT7:OMPS:7OVG:ELF6:OYNJ:43T3:SCV5:TMMU:DEKI:HTGO:WO4F
    WARNING: No swap limit support

`uname -a`:

    Linux oscar 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):

    I'm on linux mint 17.1

How reproducible:

    ➜  docker pull ubuntu
    latest: Pulling from ubuntu
    e9e06b06e14c: Already exists
    a82efea989f9: Already exists
    37bea4ee0c81: Already exists
    07f8e8c5e660: Already exists
    Digest: sha256:8126991394342c2775a9ba4a843869112da8156037451fc424454db43c25d8b0
    Status: Image is up to date for ubuntu:latest

    ➜  docker run -t -i ubuntu apt-get install wget
    Reading package lists... Done
    Building dependency tree
    #... install successfully

    ➜  docker run -t -i ubuntu apt-get install wget
    Reading package lists... Done
    Building dependency tree
    #... install again

    ➜  docker run -t -i ubuntu /bin/bash
    root@68b55de7a9d7:/# wget
    bash: wget: command not found

    ➜  docker info
    Containers: 130

    ➜  docker run ubuntu echo 'test'
    test

    ➜  docker info
    Containers: 131

Actual Results:

Every applications that I found seems to not be installed. Containers are recreated.

Expected Results:

Applications should be installed. I should have only one container.

**Comment by 3onyc** [comment]
`docker pull` pulls an image from the repository.
`docker run` creates a new container based on that image, containers do not modify images

Please refer to the [user guide](https://docs.docker.com/userguide/) for info on how docker works, and how to use it.

Relevant links:
* [Working With Containers](https://docs.docker.com/userguide/usingdocker/)
* [Working With Docker Images](https://docs.docker.com/userguide/dockerimages/)

**Comment by unclejack** [comment]
Please read the docs at https://docs.docker.com. Docker doesn't work the way you've written above.

1. `docker pull` pulls an image. A container is an instance of an image and pull only downloads the image, it doesn't create a container.
2. `docker run` creates a container from the image you choose.
3. Any changes made to a container you've started via `docker run` won't affect another container run from the same image
4. What you've told us above is something along the lines of: "I've installed the operating system from the CD/DVD, installed some apps, then reinstalled the system and couldn't find the apps I installed before reinstalling".

This isn't a Docker bug, this is a question which is more appropriate for
1) the forums: https://forums.docker.com/
2) the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user
3) the #docker channel on Freenode.
