### ISSUE TITLE
search or pull my own docker images from other docker client get 404 error

### ISSUE THREAD

**Issue by wonleing** [docker/docker#13339]
I am running docker-registry on my own server, pull images from docker 
hub, re-tag image, push to local 
container all work fine. But search or pull images from other docker 
client always fail.

The docker registry server log is:

139.185.48.134 - - [19/May/2015:08:24:27 +0000] "GET 
/v1/search?q=hello-world HTTP/1.1" 404 19 "" "docker/1.5.0 go/go1.3.3 
kernel/3.8.13-55.1.6.el7uek.x86_64 os/linux arch/amd64"

Any idea?

Thanks, 
Leon

**Comment by jmakanjuola** [comment]
wonleing,

In those other client run (docker login) and enter your docker credentials. See if that helps. Feel free to close the ticket once the issue has been resolve.

**Comment by wonleing** [comment]
[root@localhost ~]# docker login
Username: wonleing
Password: 
Email: wonleing@163.com
FATA[0007] Error response from daemon: 404 page not found

**Comment by wonleing** [comment]
that was the situation of my docker client.
my docker-registry server can do docker login correctly. But what i want to do is connect directly from the docker client to my registry server, without any connection to the official Docker Hub.
I am actually want to build my own hub, a very simple one

**Comment by wonleing** [comment]
I found the problem. each time I restart "docker run -p 5000:5000 secure_registry", I have to push the image again! Or the pull will report a 404 error.
Isn't it a bug?!

**Comment by cpuguy83** [comment]
@wonleing A `docker run` is creating a new container and then starting it.
To start a stopped container, use `docker start <container id/name>`

Closing.
