### ISSUE TITLE
Discrepancy between docs.docker.com and docs in repo

### ISSUE THREAD

**Issue by davidxia** [docker/docker#13334]
The docs in this repo for [container creation][1] say the `SecurityOpt` field belong in the `HostConfig` field:

```
         "HostConfig": {
           ...
           "SecurityOpt": [""],
           ...
        }
```

But the docs on docs.docker.com [here][2] say it's outside of `HostConfig`

```
         ...
         "SecurityOpts": [""],
         "HostConfig": {
         ...
```

They both work but there should be consistent documentation. Also the `SecurityOpts` in the second example should be `SecurityOpt` (no "s").

  [1]: https://github.com/docker/docker/blob/master/docs/sources/reference/api/docker_remote_api_v1.18.md#create-a-container
  [2]: https://docs.docker.com/v1.6/reference/api/docker_remote_api_v1.18/#create-a-container

**Comment by cpuguy83** [comment]
Closing since docs.docker.com is generated from these docs.

**Comment by thaJeztah** [comment]
To clarify, the docs on docs.docker.com are generally "behind" what's on GitHub and are periodically updated by hand-picking (cherry-picking) changes.

To view the latest version of the docs, based on GitHub, look at http://docs.master.dockerproject.com
but be aware that those docs contains documentation that may not work yet on the current release.

**Comment by davidxia** [comment]
Ah I see. The typo of the additional "s" on securityOpts should at least be
fixed because that actually doesn't work at all.

On Tuesday, May 19, 2015, Sebastiaan van Stijn <notifications@github.com>
wrote:

> To clarify, the docs on docs.docker.com are generally "behind" what's on
> GitHub and are periodically updated by hand-picking (cherry-picking)
> changes.
>
> To view the latest version of the docs, based on GitHub, look at
> http://docs.master.dockerproject.com
> but be aware that those docs contains documentation that may not work yet
> on the current release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/13334#issuecomment-103699274>.
>


-- 
David Xia
davidxia.com
