### ISSUE TITLE
Make `docker diff` take a path as argument

### ISSUE THREAD

**Issue by niko** [docker/docker#13349]
It would be nice if `docker diff` would take a path as argument so only changed files in the given folder path are output.

**Comment by thaJeztah** [comment]
I think this would be easily achievable using standard tools, e.g.

    docker diff mycontainer | grep /some/path

So I don't think this is needed to be implemented in docker itself. wdyt?

**Comment by niko** [comment]
Agreed. Thanks.

**Comment by thaJeztah** [comment]
I'm going to close this issue, because this can be achieved with external tooling, but feel free to comment if there's another use-case that I'm overlooking.
