### ISSUE TITLE
Update Mac installation instructions to mentionVirtualBox is also installed

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#13345]
I used the instructions on your website to install Docker on my Mac:

https://docs.docker.com/installation/mac/

After installing Boot2Docker, I noticed that a copy of VirtualBox also appeared in my Applications folder. You might want to mention this in the instructions. 

For example:

	• Install Boot2Docker by double-clicking the package.

The installer places VirtualBox and Boot2Docker in your "Applications" folder.

**Comment by anchal-agrawal** [comment]
I can reproduce this on my Mac. I'll take this up if needed (since it's a minor documentation change).

**Comment by moxiegirl** [comment]
@anchal-agrawal Thank you for the offer, please feel to go and do it. Much appreciated.

**Comment by anchal-agrawal** [comment]
#dibs
