### ISSUE TITLE
Delete "defer deleteAllContainers()" from integration-cli

### ISSUE THREAD

**Issue by LK4D4** [docker/docker#13357]
Remove all such lines.

**Comment by jmakanjuola** [comment]
What are you trying to achieve here LK4D4? Are you trying to remove containers or images?

**Comment by runcom** [comment]
@jmakanjuola basically tests in integration-cli now use gocheck and we don't need such calls anymore because at test's tearDown all created containers get removed automagically

**Comment by jmakanjuola** [comment]
Thanks for the update @runcom

**Comment by WeiZhang555** [comment]
#dibs
