### ISSUE TITLE
docker 1.6.2 still push images to registry 1.0

### ISSUE THREAD

**Issue by chenjie901** [docker/docker#13351]
i make reverse proxy(nginx) to registry 1.0 and 2.0，when i push images from docker 1.6.2, i found out it still push images to registry 1.0
Is this a normal behavior? 
how to force push images to registry 2.0?

**Comment by chenjie901** [comment]
'docker version':
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
Linux ubuntu 3.14.0-031400rc1-generic #201402022035 SMP Mon Feb 3 01:37:33 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

nginx config server:

server {
  listen 443;
  server_name io.huawei.com;

  ssl on;
  ssl_certificate_key /etc/ssl/certs/domain.key;
  ssl_certificate /etc/ssl/private/domain.crt;

  # disable any limits to avoid HTTP 413 for large image uploads
  client_max_body_size 0;

  # required to avoid HTTP 411: see Issue #1486 (https://github.com/docker/docker/issues/1486)
  chunked_transfer_encoding on;

  location /v2/ {
    auth_basic "Restricted";
    auth_basic_user_file /auth/docker-registry.htpasswd;
    # Do not allow connections from docker 1.5 and earlier
    # docker pre-1.6.0 did not properly set the user agent on ping, catch "Go *" user agents
    if ($http_user_agent ~ "^(docker\/1\.(3|4|5(?!\.[0-9]-dev))|Go ).*$" ) {
      return 404;
    }

    include               docker-registry-v2.conf;
  }

  location / {
    auth_basic "Restricted";
    auth_basic_user_file /auth/docker-registry.htpasswd;
    include               docker-registry.conf;
  }

}

and the same config without auth works fine to registry 2.0

**Comment by thaJeztah** [comment]
ping @dmcgowan perhaps you can have a look at this?

**Comment by dmcgowan** [comment]
When using basic auth with nginx the registry is unable to set a needed header used by the client to determine what API version the server supports when a 401 is returned.

Add this to the `/v2/` section
```
add_header 'Docker-Distribution-Api-Version' 'registry/2.0' always;
```

If you want to discuss further head over to the distribution repo.  We are working on making sure this called out better in the documentation. https://github.com/docker/distribution/issues/460

**Comment by thaJeztah** [comment]
Thanks @dmcgowan I thought I saw this mentioned, but didn't remember where :)

@chenjie901 I'm going to close this issue, because it is already being worked on in https://github.com/docker/distribution/issues/460. Please continue the discussion on https://github.com/docker/distribution/issues/460 or ask for assistance in the #docker-distribution or #docker IRC channel.
