### ISSUE TITLE
Non-started containers should not be treated as exited

### ISSUE THREAD

**Issue by andylowry** [docker/docker#13353]
If I use `docker create` to create a container, then `docker ps -a -f status=exited` shows that container.

This is conceptually problematic because the container was never started, hence it cannot ever have truly "exited.". It's a practical problem too, because it means that such a container is removed by `docker rm $(docker ps -aq -f status=exited)` performed as part of routine hygiene.

As a result of this, I'm forced to run something in a container whose sole purpose is to host shared data for other containers - or give up using an otherwise harmless hygiene step.

It would seem that some other status, e.g. "created", would be preferable for a created container that has not yet been started. Unfortunately, this proposed change could be a breaking change, so it may be dead on arrival.

**Comment by andylowry** [comment]
Sorry, hadn't seen the template... here it is, filled out:

Description of problem:

Container that is created but not started matches `status=exited` filter in `docker ps`

`docker version`:
```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

`docker info`:
```
Containers: 2
Images: 48
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 52
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-32-generic
Operating System: Ubuntu precise (12.04.5 LTS)
CPUs: 1
Total Memory: 1.955 GiB
Name: UbuntuVM
ID: G3F4:RRWW:CTPR:K5FU:QU25:PVS3:M6OJ:2TZV:LVC5:F4EU:JGMJ:MQTN
WARNING: No swap limit support
```

`uname -a`:
```
Linux UbuntuVM 3.13.0-32-generic #57~precise1-Ubuntu SMP Tue Jul 15 03:51:20 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.):
Virtualbox hosted on 64bit WIndows 7

How reproducible:

Fully reproducible

Steps to Reproduce:
1. `docker create --name test busybox`
2. `docker ps -a -f status=exited`  

Actual Results:

Container 'test' is listed in step 2 output.

Expected Results:

Step 2 output should not include container 'test' since it was never started and hence never exited.

Additional info:

Treating a never-started container as having exited seems wrong conceptually. Practically it means that such containers are destroyed by the otherwise harmless `docker rm $(docker ps -aq -f status=exited)` command used for routine hygiene.

**Comment by duglin** [comment]
#dibs
