### ISSUE TITLE
Question: Why does Dockerfile support multiple FROM entries?

### ISSUE THREAD

**Issue by luebken** [docker/docker#13352]
While reading the docs I've stumbled upon: 
> FROM can appear multiple times within a single Dockerfile in order to create multiple images. Simply make a note of the last image ID output by the commit before each new FROM command.
https://docs.docker.com/reference/builder/#from

I've tested this via:
```
FROM busybox:ubuntu-14.04
ENTRYPOINT ["echo", "from1"]

FROM debian:latest
ENTRYPOINT ["echo", "from2"]
```
```
$ docker run deaee2cc56ed
from1
$ docker run 93b41e538f02
from2
```

This example is particular interesting since the docs say:
> Only the last ENTRYPOINT instruction in the Dockerfile will have an effect.
https://docs.docker.com/reference/builder/#entrypoint

So I am wandering why are multiple FROMs allowed? What are the use-cases?

**Comment by duglin** [comment]
@luebken please see: https://github.com/docker/docker/issues/13026

non-last FROMs do take effect but only the last one is related to the image (and name) being asked for on the 'docker build' command.

**Comment by luebken** [comment]
Thanks for the pointer.
