### ISSUE TITLE
fix the --net none build

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#13369]
see error here https://jenkins.dockerproject.com/job/Docker%20Master%20(--net=none)/474/console

(for gordon: docker info, docker version, uname -a)

**Comment by hqhq** [comment]
#dibs

**Comment by hqhq** [comment]
Sorry didn't look it through, my environment is behind GFW and proxy, `ping` is not working, so I can't debug this, I'm gonna cancel my dibs.

**Comment by jfrazelle** [comment]
its actually pretty easy if you want to just add `testRequires(c Network)` to the test ;)

**Comment by jfrazelle** [comment]
would be greatly appreciated

**Comment by hqhq** [comment]
@jfrazelle Yeah, I see the problem, just in my box, this kind of testcase (ping www.docker.io) can never pass, but I think the fix is as certain as you said. Can you trigger a `--net=none` on https://github.com/docker/docker/pull/13399?
