### ISSUE TITLE
v2 image validation does not compare requested ID to retrieved ID

### ISSUE THREAD

**Issue by ewindisch** [docker/docker#13360]
With the v2 format, a malicious registry or a MITM attacker could swap any v2 image for any other v2 image. All that is confirmed is that the manifest and the data match, not that the requested image ID was the image that was actually returned.

Furthermore, it seems that upon pulling an image, Docker always places the tag in the local graph according to the image name as it was requested. In the above example, should a user request "ubuntu" from a malicious registry which returns "debian", the downloaded image will be tagged to the name "ubuntu".

/cc @stevvooe

Verified with 1.6.0 (no fixes exist in 1.6.1 which would resolve this)

**Comment by stevvooe** [comment]
To clarify, a few things need to happen to content fetched from a registry by content digest:

1. The data needs to be digested using the "local" algorithm, used to pull the content. For example, if one pulls `sha256:abcd`, the client should verify against that digest, using sha256.
2. If the registry provides a different digest, in the `Docker-Content-Digest` header, the client *should* also verify that the data matches that hash.

This needs to be done for both layers and manifests fetched by digest.

@dmcgowan @tiborvass

**Comment by nakedible** [comment]
Confirmation: this bug affects pulls that depend on signatures on manifests, but does not affect pulls that pull by digest, as swapping the manifest with any other manifest in that case would invalidate the hash?

Verifying digests for each layer is already done doing local hash verification, and not against Docker-Content-Digest header or something silly like that, right?

**Comment by stevvooe** [comment]
I've just completed a full analysis of the current codebase:

1. Remote manifest is verified against the `Docker-Content-Digest` header, rather than using the reference. This needs to be fixed. I'm submitting a PR to address this shortly.
2. Layer digest verification is in better shape, but the failure is only treated as a verification error, similar to signature preview. The PR will make a digest verification a hard failure.

**Comment by dmcgowan** [comment]
There is a PR which makes it a hard failure and attempts to clean up some of the messaging #11830. If your PR supersedes it we should close that one.

**Comment by ewindisch** [comment]
This isn't only for layer digests but for the image name itself. I need to verify if #13576 solves the full scope of this issue.

**Comment by stevvooe** [comment]
@ewindisch #13576 covers the issue I spoke to you about, which led to filing this issue. The second clause above requires a much larger fix.
