### ISSUE TITLE
Add UDP and TCP support to syslog log adapter

### ISSUE THREAD

**Issue by pebo** [docker/docker#13362]
Currently the [syslog log adapter](https://github.com/docker/docker/blob/master/daemon/logger/syslog/syslog.go) introduced in docker 1.6 only seems to support logging to a unix domain socket (e.g. /dev/log). If logger options are introduced it could be useful to have support for configuring syslog hostname, port and protocol (https://golang.org/pkg/log/syslog/#Dial).

**Comment by runcom** [comment]
+1!

**Comment by pebo** [comment]
The changes in https://github.com/docker/docker/pull/13392 seems to perfectly solve what's in this proposal!
