### ISSUE TITLE
Should I replace DNAT port mapping by userland proxy (docker-proxy)?

### ISSUE THREAD

**Issue by mingqi** [docker/docker#13379]
I noticed docker will automatically start up a docker-proxy(userland proxy) when new container. The userland proxy also can do the port mapping works. How it performance,  in particular compare DNAT port mapping? I can't find out more document about userland proxy. Somebody said it only used for handle localhost traffic and shouldn't use in produciton. it's correct?

**Comment by coolljt0725** [comment]
correct , userland-proxy is for loopback traffic

**Comment by cpuguy83** [comment]
userland proxy is terrible and will have a flag to disable in docker 1.7
You shouldn't use it if you don't have to.
