### ISSUE TITLE
docker run does not accept domainname as argument

### ISSUE THREAD

**Issue by cgcgbcbc** [docker/docker#13378]
Description of problem:

`docker version`:
```
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64
```

`docker info`:
```
Containers: 26
Images: 293
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 345
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-46-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 4
Total Memory: 3.75 GiB
Name: optiplex
ID: RUTD:IS5A:T5QK:3LTQ:QGS2:AAVA:KGDU:4LOI:LSWN:LFEZ:GFZN:4YKP
WARNING: No swap limit support
```

`uname -a`:
```
Linux optiplex 3.13.0-46-generic #75-Ubuntu SMP Tue Feb 10 15:24:04 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.):
physical machine

How reproducible:
`docker run --rm -ti --hostname=foo --domainname=bar.com ubuntu bash

Actual Results:
```
flag provided but not defined: --domainname
See 'docker run --help'.
```

Expected Results:
Append the domain name after the hostname

Additional info:
 I noticed that `domainname` is available in docker-compose, but actually it does not set the domainname.

**Comment by cgcgbcbc** [comment]
I've found that I mistook the document, if I want to set domain name only, I should set the hostname to `.domain.name`

**Comment by muikrad** [comment]
This behavior has changed with Docker 1.11 - placing dots in the --hostname no longer populates domainname as before, and --domainname is not supported either. I am trying to find more information about this new behavior - anyone cares to chime in?

**Comment by sanimej** [comment]
@muikrad When you pass a FQDN as --hostname the domain part should be populated in `dnsdomainname` and not `domainname` 

From the man page..
```    
       hostname - show or set the system’s host name
       domainname - show or set the system’s NIS/YP domain name
       dnsdomainname - show the system’s DNS domain name
```
dnsdomainname works fine for me in 1.11. 

One change that got merged in 1.11 in this area is 
https://github.com/docker/docker/pull/20200. This was mainly to separate hostname and domainname in the API.
Can you explain the difference in behavior you see with 1.11 and what the older version was ?

**Comment by chukka** [comment]
http://superuser.com/questions/962658/how-to-define-domainname-in-a-docker-run-command/1065412#1065412

**Comment by muikrad** [comment]
I noticed the same exact thing as @chukka using the same versions. Also, there is now a 64 character limit imposed on the --hostname value, among other things (underscores no longer supported, etc - but this is a good thing because before, it would accept non dns-compliant values)

**Comment by nafg** [comment]
In any case the docker-compose documentation seems to be stale, because [here](https://docs.docker.com/compose/compose-file/#cpushares-cpuquota-cpuset-domainname-hostname-ipc-macaddress-memlimit-memswaplimit-privileged-readonly-restart-shmsize-stdinopen-tty-user-workingdir) it lists both as being the same as the docker run argument, which apparently doesn't exist.
