### ISSUE TITLE
Experimental channel build binary should mention experimental in docker -v

### ISSUE THREAD

**Issue by chanezon** [docker/docker#13385]
With the introduction of a new "Experimental" channel in https://github.com/docker/docker/issues/13023, there should be a way for the user to determine that they are running an experimental build.

```docker -v```
today
```Docker version 1.6.0, build 4749651```
or
```Docker version 1.6.2-cs4, build 47224f0```
For experimental
```Docker version 1.6.2-exp, build 47224f0```
or
```Docker version 1.6.0, experimental build 4749651```

**Comment by chanezon** [comment]
Good call from @icecrime docker version also needs to reflect that
Right now
```$ docker version
Client version: 1.6.2-cs4
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 47224f0
OS/Arch (client): linux/amd64
Server version: 1.6.2-cs4
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 47224f0
OS/Arch (server): linux/amd64```

**Comment by duglin** [comment]
I'm partial to: `Docker version 1.6.0, experimental build 4749651`  Very clear.

**Comment by icecrime** [comment]
@duglin How do you feel about this?

```
--- a/hack/make.sh
+++ b/hack/make.sh
@@ -96,6 +96,7 @@ fi
 if [ "$DOCKER_EXPERIMENTAL" ]; then
        echo >&2 '# WARNING! DOCKER_EXPERIMENTAL is set: building experimental features'
        echo >&2
+       VERSION+="-exp"
        DOCKER_BUILDTAGS+=" experimental"
 fi
```

**Comment by duglin** [comment]
its not as eye-catching as "experimental" :-)  but I guess it'll work.

**Comment by icecrime** [comment]
I can go with `-experimental`, the question was mostly about basically "faking" the version, which may or may not fit for everyone.

Also, we will have the weird `1.7.0-dev-experimental` :p

**Comment by thaJeztah** [comment]
Hm I actually opted for this in https://github.com/docker/docker/pull/13338#issuecomment-103956879, but think it got lost in the process

+1

**Comment by duglin** [comment]
As long as the info is easy to notice (not too easy to miss), I think that's all that really matters.

**Comment by icecrime** [comment]
@thaJeztah Damn, sorry I totally missed it :-)

**Comment by thaJeztah** [comment]
@icecrime we can add it as an experimental feature?

Might be worth considering more granular settings at some point in stead of just on/off (i.e. `DOCKER_EXPERIMENTAL=volume-drivers,userns`). But now I'm getting off-track.
