### ISSUE TITLE
doc: docker images should explain repository column and when none

### ISSUE THREAD

**Issue by lloydde** [docker/docker#13397]
doc: docker images should explain repository column and when none. Or provide a link to where these are explained.

https://docs.docker.com/reference/commandline/cli/#images

`docker images` starts "The default docker images will show all top level images, their repository and tags, and their virtual size."  It goes on to do a good job of explaining the last item "virtual size".

**Comment by lloydde** [comment]
@GordonTheTurtle you silly bot. How do I get you not to respond for doc bugs?

**Comment by thaJeztah** [comment]
@lloydde perhaps you are willing to create a pull-request to enhance the description of those columns?

**Comment by lloydde** [comment]
@thaJeztah unfortunately my motivation of filing this is, because I don't know the answers. I was surprised that many images have <none> for their repository.

I think I've read that when an image is "replaced" the old image would be untagged. This part makes more sense.

**Comment by thaJeztah** [comment]
There actually was some work done on adding a glossary to the documentation in https://github.com/docker/docker/pull/11897.

You can read it here; http://docs.master.dockerproject.com/reference/glossary/

I just noticed it is no longer linked in the menu, so I will ask if there's any reason for that.

**Comment by lloydde** [comment]
@thaJeztah that's helpful! Thank you.

The definition for "registry" in the glossary reads "containing repositories of images" and does not address images having `<none>` for their registry.
http://docs.master.dockerproject.com/reference/glossary/#registry

**Comment by thaJeztah** [comment]
@lloydde hm, true. Not sure that part should be explained there. But I agree that we might to explain *somewhere* that "un tagging" and image will show it as `<none>` in the output of `docker images`.

**Comment by charleswhchan** [comment]
Note: Page has moved, here's the link to the latest doc
https://docs.docker.com/reference/commandline/images/

**Comment by HackToday** [comment]
hi @lloydde  and @thaJeztah from what I learnt above, is it a question about

$ docker images
REPOSITORY                TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
<none>                    <none>              77af4d6b9913        19 hours ago        1.089 GB

this none case ?

**Comment by thaJeztah** [comment]
@HackToday the output can still show `<none>` if an image is untagged (e.g. on repeated builds, the latest version is tagged, and the previous version of the image will show as `<none>`;

```
REPOSITORY            TAG                                   IMAGE ID            CREATED             VIRTUAL SIZE
docs-base             update-ubuntu-install                 56bbadd77a9b        4 days ago          672.5 MB
docs-base             fix-api-network-output                d08282e1e03e        6 days ago          672.4 MB
<none>                <none>                                ca73b76e31c1        6 days ago          672.4 MB
<none>                <none>                                8f55a964bb3e        6 days ago          672.4 MB
```

**Comment by sammyshj** [comment]
@thaJeztah The [doc](http://docs.docker.com/engine/reference/commandline/images/) already has a section about untagged images(dangling).
Can you clarify what exactly needs to be done in this issue then, I will like to work on this issue.

**Comment by thaJeztah** [comment]
@sammyshj good question, I think that section covers it quite well. Perhaps we should explicitly mention `<none>`, and explain that those are untagged images?

**Comment by sammyshj** [comment]
Okay working on it right now.
Following the [Docker Contribution Guide](https://docs.docker.com/opensource/workflow/find-an-issue/), #dibs.

**Comment by thaJeztah** [comment]
Awesome @sammyshj, thanks!
