### ISSUE TITLE
Experimental feedback - Plugins

### ISSUE THREAD

**Issue by icecrime** [docker/docker#13419]
This is a placeholder issue to collect feedback on the plugins experimental feature shipped as part of Docker 1.7.0.

**Comment by mariusGundersen** [comment]
During the keynote plugin support for service discovery was mentioned. Any place to find information about this?

**Comment by thaJeztah** [comment]
@mariusGundersen docs for the experimental features can be found here; https://github.com/docker/docker/tree/master/experimental. I think what you're looking for is this; https://github.com/docker/docker/blob/master/experimental/networking.md (there's still ongoing discussions on tweaking the networks/end points/services design)

**Comment by bboreham** [comment]
I guess this should probably be closed; things have moved on and feedback was supplied in many other places.
