### ISSUE TITLE
Missing tests for image verification

### ISSUE THREAD

**Issue by nakedible** [docker/docker#13410]
Currently docker has only a single test which tests image verification, and that will just pull `hello-world` and check that the client outputs the log message "The image you are pulling has been verified". Image verification has a multitude of checks that need to be checked and simple code refactoring can easily leave some of these ineffective while still printing that log message.

What is needed are tests which explicitly return bad data to the client and verify that the client rejects the data (preferably before processing).

An incomplete list of things that should be covered:
- Correct manifest signature from an unknown key
- Whitespace modification (preserving well-formed JSON) of a signed manifest, returned for the correct tag
  - Apparently libtrust handles a JSON trailer separately, so there probably should be two tests, one with modification in the payload and one with modification in the trailer, unless this is covered sufficiently in libtrust test cases already
- Whitespace modification of an unsigned manifest, pulled with a digest tag
- Adding/removing trailing 512 bytes of zero on a single sha256 digest layer of a multi-layer image (to also catch errors where only first/last layer is verified)

(Tests designed to catch the most stringent acceptance criteria, so if the criteria is loosened at a later date, for example by verifying canonical JSON and not byte exact JSON, the tests will break and it has to be a conscious decision to loosen up the criteria.)

(This issue is written in "must" form, but obviously it is up for debate if these test are really critical.)

**Comment by NathanMcCauley** [comment]
This is drastically different now that notary has been implemented, but some of the tests seem like they'd be good to consider. @cyli @riyazdf @diogomonica WDYT?

**Comment by diogomonica** [comment]
We have the majority of these tests (corruption of every metadata file) at the notary library level. We could port them to the Docker level (creating a malicious registry that modified things), but it might be a lot of work for not a lot of gain.

**Comment by cyli** [comment]
@diogomonica By porting to the Docker level, do you mean corrupting the manifest files in every way possible?

**Comment by diogomonica** [comment]
@cyli correct.

**Comment by LK4D4** [comment]
ping @cyli @NathanMcCauley @diogomonica

**Comment by justincormack** [comment]
I am going to close this as there are good tests now. Of course they could be better, and fuzzing would be a good project here, but I think the original issue has been addressed.
