### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by kvasdopil** [docker/docker#13423]
Hello guys. What do you think of porting docker to FreeBSD? FreeBSD already has all required technologies (like ZFS and jails) so implementing is possible.

The work is already begun at http://github.com/kvasdopil/docker. Now it can load the image, create container and run it. Basic networking is available (with preconfigured NAT on host machine)

One of primary concerns is support for FreeBSD (and thus, linux-incompatible images on the hub) is okay for docker project? What do developers think?

**Comment by thaJeztah** [comment]
For reference, @kvasdopil is currently working on this (which is awesome :))
