### ISSUE TITLE
libnetwork: different behavior while creating bridge with IPv6 support compared to v1.5 and v1.6

### ISSUE THREAD

**Issue by MalteJ** [docker/docker#13426]
As described in the [snapshot documentation](http://docs.master.dockerproject.com/articles/networking/#ipv6-with-docker) Docker versions 1.5 and 1.6 did setup a route and enabled IPv6 routing to Docker's fixed-cidr-v6 subnet (e.g. `2001:db8:1::/64`) while creating the docker0 bridge:

    $ ip -6 route add 2001:db8:1::/64 dev docker0
    $ sysctl net.ipv6.conf.default.forwarding=1
    $ sysctl net.ipv6.conf.all.forwarding=1

Currently, with libnetwork merged in 1.7.0-dev, these steps are not executed.

Should those steps be executed manually by the user or automatically when starting the Docker daemon?

Either we have to adjust the docs or we have to add functionality.

**Comment by thaJeztah** [comment]
ping @mrjana @mavenugo possible regression after libnetwork integration

**Comment by mavenugo** [comment]
@MalteJ @thaJeztah will take a look. We need good ipv6 integration-cli to catch these early.

**Comment by thaJeztah** [comment]
@mavenugo thanks, perhaps you could check https://github.com/docker/docker/pull/13226 as well, to see if the test is still relevant for libnetwork

**Comment by calavera** [comment]
That libnetwork PR still needs to be ported to docker, doesn't it @mavenugo?
