### ISSUE TITLE
progressreader should not write to output on Close()

### ISSUE THREAD

**Issue by moysesb** [docker/docker#13432]
The Reader wrapper in `pkg/progressreader` prints a full progress bar when it is closed. That causes confusing/weird output when the the `Close()` function is called some time after the read has finished and other writers have printed to the same output in the intervening time. 

Example:
```bash
$docker build -f ctx/Dockerfile --no-cache http://localhost/ctx.tar.gz
Downloading context: http://localhost/ctx.tar.gz    240 B/240 B
Step 0 : FROM busybox
 ---> 8c2e06607696
Step 1 : ADD ctx/container.cfg /
 ---> 30b6fcb567fd
Removing intermediate container e92cce98d64e
Step 2 : CMD /bin/ls
 ---> Running in 82a0515dd3a1
 ---> 151003bc1cc4
Removing intermediate container 82a0515dd3a1
Downloading context: http://localhost/ctx.tar.gz    240 B/240 B
```
That last line should not be there.

Since there's a well defined completion point for the `progressreader` operation in [`Read()`](https://github.com/docker/docker/blob/a39d49d676c5cd0b4e20c1cec549a32fe0837e93/pkg/progressreader/progressreader.go#L62), anything that needs to be written could be written from that point, right?. That last full progress line from the progressreader is printed when the reader is closed by a `defer`.

Removing the call to `config.Out.Write()` from `Close()` fixes the problem and does not seem to cause any issues with the other users of `progressreader` (e.g. `docker push / pull`).

Is there some special case for which that output was included originally?

**Comment by duglin** [comment]
@moysesb moving the final print to the Read() makes sense to me.  But, would we need to call `FormatProgress()` one last time to ensure that it showed things at 100% (still within Read())?  Also, if someone does call Close() prematurely, I'm not sure we'd want to lose that final `Write` so what if the Close() only printed a final status IFF it wasn't already done within Read() ?
