### ISSUE TITLE
how set SGID for file with different user and group ? postqueue and postdrop files for postfix

### ISSUE THREAD

**Issue by jericho63** [docker/docker#13437]
Hello,

i try to dockerize postfix but i have the same problem than this case #6828, I 'm unable to set the sgid on file postdrop and posqueue.
In the case #6828, it's said the problem it's fixed with docker version 1.2, but i use docker version1.6

Environment Details:

docker version:
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 8aae715/1.6.0
OS/Arch (client)Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 8aae715/1.6.0
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 8aae715/1.6.0
OS/Arch (server): linux/amd64
[root@homeserver mailserver]# ^C
[root@homeserver mailserver]# docker info
Containers: 9
Images: 729
Storage Driver: devicemapper
 Pool Name: docker-253:1-87030-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 6.141 GB
 Data Space Total: 107.4 GB
 Data Space Available: 44.69 GB
 Metadata Space Used: 24.43 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.123 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Kernel Version: 3.10.0-229.4.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 4
Total Memory: 3.416 GiB
Name: homeserver.mydomain.com
ID: XFON:B5HF:DXCL:PHYU:REMG:TVRW:HQ75:4KZ7:7A2S:ONEG:IOZR:AUQC
: linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 8aae715/1.6.0
OS/Arch (server): linux/amd64
docker info
uname -a
Linux homeserver 3.10.0-229.4.2.el7.x86_64 #1 SMP Wed May 13 10:06:09 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details:
centos 7 as host 
debian jessie as image.

actual result:
-r-xr-xr-x. 1 root postdrop 14328 Nov  4  2014 postdrop
-r-xr-xr-x. 1 root postdrop 14280 Nov  4  2014 postqueue

Expected Results:
-r-xr-sr-x. 1 root postdrop 14328 Nov  4  2014 postdrop
-r-xr-sr-x. 1 root postdrop 14280 Nov  4  2014 postqueue

DO you have an idea?

thank you

**Comment by cpuguy83** [comment]
I'm not able to repro.
Do you still have this issue?
Can you include simple repro steps?

**Comment by thaJeztah** [comment]
closing because there was no response, but happy to reopen if you're still able to reproduce this on the current release
