### ISSUE TITLE
Document justone per 12333

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#13431]
@moxiegirl can we add @justone tool to documentation somewhere and reference to docker images.
@justone Thank you! This is so cool!

See https://github.com/docker/docker/pull/12333

**Comment by justone** [comment]
The tool's name is [dockviz](https://github.com/justone/dockviz), and it replaces the following:

* `docker images -t` is now `dockviz images -t`
* `docker images -d` is now `dockviz images -d`

There are other features too, but those are the two that it's replacing.

I can do the PR if nobody else grabs it.  Just need to know (or find) where it's appropriate to add the information.

Thanks.

**Comment by moxiegirl** [comment]
Thanks @justone that would be great if you wanted to make the change.  I think these two places would be good to update:

docs/man/docker-images.1.md
userguide/dockerimages.md
