### ISSUE TITLE
Wrong linked-container name

### ISSUE THREAD

**Issue by nstanar** [docker/docker#13459]
Just to keep it simple, I am using a dummy example to explain the issue. After building an image using Dockerfile, I am starting two containers based on the same image running on different ports. Second container has a link towards first one, but the problem is that link name is wrong.

`docker version`: 
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

`docker info`:
Containers: 3
Images: 28
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 34
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.16.0-30-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 5.891 GiB
Name: ubuntu
ID: HYT2:FPBT:OEKK:Q7VJ:JIWO:KMBU:MFJT:L7K4:N2VF:TOSV:UUEM:ZTYF

`uname -a`:
Linux ubuntu 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

I am running docker on a Virtual Box.

Content of Dockerfile:

FROM tomcat:7.0
MAINTAINER example@test.com
WORKDIR /app
COPY config/ ./
COPY hateoas.jar ./
EXPOSE 8080
ENTRYPOINT ["java","-jar","hateoas.jar"]

Commands for running the containers:
docker run -it -d --name=app1 -p=8080:8080 app
docker run --name app2 --link app1:app1 -d -p 8081:8080 app

For some reason after starting the container app2 it has invalid link name specified for app1, which can be seen in HostConfig part after using docker inspect ( link should be named /app1 instead of /app2/app1 ):

"HostConfig": {
        "Binds": null,
        "CapAdd": null,
        "CapDrop": null,
        "CgroupParent": "",
        "ContainerIDFile": "",
        "CpuShares": 0,
        "CpusetCpus": "",
        "Devices": [],
        "Dns": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "IpcMode": "",
        "Links": [
            "/app1:/app2/app1"
        ],
        "LogConfig": {
            "Config": null,
            "Type": "json-file"
        },
        "LxcConf": [],
        "Memory": 0,
        "MemorySwap": 0,
        "NetworkMode": "bridge",
        "PidMode": "",
        "PortBindings": {
            "8080/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "8081"
                }
            ]
        },

**Comment by runcom** [comment]
`/app2/app1` is notation to say that the second container has a child (`app1`) (pretty sure about this but maybe someone could correct me

**Comment by nstanar** [comment]
Here is the output of the env command inside app2 container:

HOSTNAME=91a2f7f5e1a4
TOMCAT_VERSION=7.0.62
CATALINA_HOME=/usr/local/tomcat
APP1_ENV_LANG=C.UTF-8
APP1_PORT_8080_TCP=tcp://172.17.0.5:8080
APP1_PORT=tcp://172.17.0.5:8080
APP1_ENV_TOMCAT_VERSION=7.0.62
APP1_NAME=/app2/app1
APP1_PORT_8080_TCP_PROTO=tcp
APP1_ENV_TOMCAT_TGZ_URL=
https://www.apache.org/dist/tomcat/tomcat-7/v7.0.62/bin/apache-tomcat-7.0.62.tar.gz
PATH=/usr/local/tomcat/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/app
LANG=C.UTF-8
APP1_ENV_CATALINA_HOME=/usr/local/tomcat
JAVA_VERSION=7u79
APP1_ENV_TOMCAT_MAJOR=7
APP1_PORT_8080_TCP_ADDR=172.17.0.5
SHLVL=1
HOME=/root
JAVA_DEBIAN_VERSION=7u79-2.5.5-1~deb8u1
TOMCAT_MAJOR=7
APP1_ENV_JAVA_DEBIAN_VERSION=7u79-2.5.5-1~deb8u1
TOMCAT_TGZ_URL=
https://www.apache.org/dist/tomcat/tomcat-7/v7.0.62/bin/apache-tomcat-7.0.62.tar.gz
APP1_ENV_JAVA_VERSION=7u79
APP1_PORT_8080_TCP_PORT=8080
_=/usr/bin/env


As you see APP1_NAME has the same value. I am not sure If I am getting it
right, but if this is the way it supposes to work then I cannot use this
APP1_NAME environment variable as a property inside my app2 (unless I strip
the /app2 part). For example if I want to call rest service in app1 from
app2.

On Mon, May 25, 2015 at 1:51 PM, Antonio Murdaca <notifications@github.com>
wrote:

> /app2/app1 is notation to say that the second container has a child (app1)
> (pretty sure about this but maybe someone could correct me
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/13459#issuecomment-105216770>.
>



-- 
Nikola Stanar

**Comment by coolljt0725** [comment]
For the `Hostconfig` has `/app2/app1` I think @runcom  is right, but it is doesn't make sense that the
environment variable `APP1_NAME` is also `/app2/app1`

**Comment by runcom** [comment]
@coolljt0725 agree but maybe someone has a better explaination about why the format is `/app2/app1`

**Comment by runcom** [comment]
@nstanar I made a PR to *fix* this but I don't understand how you can access `APP1_NAME` without knowing in advance that your linked container is called `app1`, just wondering, could you explain this to me?

**Comment by duglin** [comment]
@runcom the linking features (sort of) assumes you already know what you're looking for.  See: https://github.com/docker/docker/pull/8515  which tried to fix that.

**Comment by runcom** [comment]
@duglin exactly, after thinking a bit more of this I came to what you said here

**Comment by nstanar** [comment]
Thanks Antonio. Like Doug said, I already know what is the name of the
linked container. This is just a dummy example I have posted because the
behavior was strange to me. I am probably going to use consul with
registrator for my project.


On Tue, May 26, 2015 at 1:06 PM, Antonio Murdaca <notifications@github.com>
wrote:

> @duglin <https://github.com/duglin> exactly, after thinking a bit more of
> this I came to what you said here
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/13459#issuecomment-105489740>.
>



-- 
Nikola Stanar

**Comment by thaJeztah** [comment]
Also have a look out for coming features brought in by the Libnetwork integration. I'm not sure if a discovery-mechanism is part of those plans, but worth a look anyway.

**Comment by nstanar** [comment]
I will check it out, thanks for recommendation.

On Tue, May 26, 2015 at 1:48 PM, Sebastiaan van Stijn <
notifications@github.com> wrote:

> Also have a look out for coming features brought in by the Libnetwork
> integration. I'm not sure if a discovery-mechanism is part of those plans,
> but worth a look anyway.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/13459#issuecomment-105497299>.
>



-- 
Nikola Stanar

**Comment by runcom** [comment]
@nstanar after further discussing this and due to https://github.com/docker/docker/pull/8515#issuecomment-61690215 I think we can't break compatibility changing `_NAME` to something else (people expect a path format) and before a discovery mechanism is made available here in docker (or libnetwork as @thaJeztah said) you should just strip down the first part of the path

I'm going to close this (and the associated PR also) due to what I said above
