### ISSUE TITLE
is the network behavior depend on how we set the ip address of docker0?

### ISSUE THREAD

**Issue by epiphyllum** [docker/docker#13456]
when I set docker0  to  188.66.0.1/16,    then the created container can access internet
when I set docker0  to  172.17.42.1/16(default),    then the created container can access internet
but when I set docker0 to 10.0.0.1/8,  then the created container can not access internet. 

why?   I just want to set all my containers's IP addresses  to 10.xx.xx.xx.   it seems unachievable;

**Comment by epiphyllum** [comment]
`docker version`: 

Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

`docker info`:
Containers: 9
Images: 293
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 311
Execution Driver: native-0.2
Kernel Version: 3.13.0-32-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 4
Total Memory: 49.14 GiB
Name: docker
ID: UIW5:5O2A:IY4O:FQC7:M5QN:6QRN:QB2Z:F3VG:VX3V:HJ4C:4HGD:SXFO
WARNING: No swap limit support


`uname -a`:
Linux docker 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux



`Environment details (AWS, VirtualBox, physical, etc.):`
physical

`How reproducible:`
always


`Steps to Reproduce:`
1.  sudo ifconfig docker0 down
2.  sudo service docker stop
3.  sudo ifconfig docker0 10.0.0.1/8 up
4.  sudo service docker start
5.  sudo docker run -it --rm centos:6.6 bash
6.  in container:   ping www.yahoo.com

`Actual Results:`
no response


`Expected Results:`
64 bytes from 116.214.12.74: icmp_seq=0 ttl=51 time=53.980 ms

`Additional info:`

**Comment by thaJeztah** [comment]
Not really familiar in this area, but there's some information about changing the docker bridge in the Advanced Networking section of the documentation. These sections may be interesting here; https://docs.docker.com/articles/networking/#docker0 (`--bip=...`, `--fixed-cidr=CIDR`) and this section: https://docs.docker.com/articles/networking/#building-your-own-bridge

**Comment by thaJeztah** [comment]
This issue may be helpful as well; https://github.com/docker/docker/issues/13158

**Comment by epiphyllum** [comment]
Actually,  in the senario where I setup docker daemon by myself like this:
1>  sudo su;   mkdir  -p  /opt/{data,run,log}
2>  brctl addbr  br-uat
3>  ip address add 10.0.0.1/8 dev br-uat
4>  ip link set dev br-uat up
5>  /usr/bin/docker -d  -g /opt/data -b br-uat -p /opt/run/docker.pid -H unix:///opt/run/docker.sock > /opt/log/docker.log 2>&1  &
6>  docker -H unix://opt/run/docker.sock pull centos:6.6
7>  docker -H unix://opt/run/docker.sock run -it --rm  centos:6.6  bash
8>  in the temporary container:    ping www.yahoo.com

then:   no response. 


but if I change step 3  to  "ip address add 188.66.0.1/16 dev br-uat"   then www.yahoo.com is pingable;

also:  "ip address add 188.88.0.1/16 dev br-uat",    then  www.yahoo.com is pingable;

**Comment by cpuguy83** [comment]
Sounds like you have a conflict/routing issue.

**Comment by jmakanjuola** [comment]
I agree cpuguy83

**Comment by haryzhou** [comment]
yes.   I restart my box,  and test it again, it is ok. 
3ks!

**Comment by thaJeztah** [comment]
Good to hear you managed to fix it (I take it that @haryzhou and @epiphyllum are both your accounts?)

I'm going to close this issue, but let me know if you think I closed this by mistake
