### ISSUE TITLE
./nuke-graph-directory.sh will not remove /var/lib/docker/btrfs; what now?

### ISSUE THREAD

**Issue by scottidler** [docker/docker#13469]
Description of problem:
I have read through the copious issues regarding this and tried every suggested fix including the nuke script, but I am unable to removed /var/lib/docker/btrfs.  The reason I am even doing this is because docker wouldn't start, after a yum update to 1.6,  and the suggested fix was, remove /var/lib/docker and reinstall.

Currently, I have docker uninstalled, but can't remove these files.  I even tried btrfs subvol remove to no avail.
`docker version`:
docker 1.6 (but not relevant as it is yum removed)

`docker info`:
N/A see above

`uname -a`:
Linux fedev 3.19.7-200.fc21.x86_64 #1 SMP Thu May 7 22:00:21 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
Home dev system, metal host although VirtualBox is installed, it should not play a role in this

How reproducible:
Hard to tell, did yum udpate and then the service wouldn't start with: sudo systemctl start docker.service

Following advice found on StackOverflow, I attemped to yum remove docker, but the /var/lib/docker directory needs to be removed.  The subdir, btrfs is the stubborn one that can't be removed.

Steps to Reproduce:
sudo rm -rf /var/lib/docker

or sudo dockerrepo/contrib/nuke-graph-directory.sh /var/lib/docker

Actual Results:
multiples of this:
rm: cannot remove ‘/var/lib/docker/btrfs/subvolumes/64a7b9f8aa9f0830be02f4e00c7eb1e4d1eb005c2711c420817d795008a82ef9’: Operation not permitted

Expected Results:
directory removed

Additional info:
Fedora 21

also tried:
<(((º> sudo btrfs subvolume delete /var/lib/docker/btrfs/subvolumes/*
ERROR: error accessing '/var/lib/docker/btrfs/subvolumes/*'

**Comment by kcolford** [comment]
you can fix this easily by doing

    cd /var/lib/docer/btrfs/subvolumes/
    btrfs subvolume delete *
    cd /
    rm -rf /var/lib/docker

**Comment by cpuguy83** [comment]
Closing since it seems like the above would handle this.
