### ISSUE TITLE
docker volume mounting fails from vagrant

### ISSUE THREAD

**Issue by NikolaMandic** [docker/docker#13478]
hello I have the same issue here
http://stackoverflow.com/questions/20240788/shared-volume-in-docker-through-vagrant
I created vagrant box installed docker inside then I wanted to mount shared volume and all it sees are empty folders sometimes I mount one folder and it sees only one folder and when I go down directory tree terminal directories are empty inside of the container
killing local docker daemon did not work nor did      
`docker kill container`    
so I connect to daemon on another vagrant instance via htts to start containers.
                 
so docker in vagrant with docker daemon on another vagrant box with https
ubuntu 14.04 
tried latest docker and tried 1.3.3
uname -a 
Linux vagrant-ubuntu-trusty-64 3.13.0-52-generic #86-Ubuntu SMP Mon May 4 04:32:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

docker info
Containers: 1
Images: 122
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 124
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-52-generic
Operating System: Ubuntu 14.04.2 LTS
WARNING: No swap limit support

environment details
virtualbox with vagrant on laptop

how reproducible : I am setting up CI pipeline so it fails each time

steps to reproduce:

create vagrantfile that will run  virtualbox vm with ubuntu/trusty64 
do vagrant up
install latest docker on it
try to mount directory to container with -v that has some files inside
if it does not have files you expect to see then it fails 
docker container is ubuntu 14.04
ps. when doing docker inspect it shows that it mounted everything
ps. I use docker daemon on remote host over https and that remote host is also vagrant virtualbox vm with ubuntu/trusty64

**Comment by cpuguy83** [comment]
Mount points are local to the docker daemon, not the docker client.
So if those do not exist on the docker host docker will create the dirs and mount those in.

Closing since this is not a docker issue.
If you need additional help, feel free to hop on #docker on freenode.
Thanks!

**Comment by NikolaMandic** [comment]
it won't mount them when stuff is on the host also I tried running the command on the host to start the container
