### ISSUE TITLE
Cannot access some https in docker, when host machine under VPN.

### ISSUE THREAD

**Issue by jinchizhong** [docker/docker#13475]
Dear developer,

I met a very strange problem. Can you help me?

When I use VPN, part of https(not all) links cannot receive data. It's hard to scribe, so I made a table.

I thinks it's a mistake in iptables, but I do not understand iptables T_T

    VPN-off
            http  https
    docker  OK    OK
    host    OK    OK

    VPN-on
            http  https
    docker  OK    PART FAIL
    host    OK    OK

    failed links:
        https://api.rubygems.org/api/v1/dependencies
        https://www.baidu.com
    succeed links:
        https://www.google.com
        https://www.facebook.com

A failed curl report:

    root@caba483189e1:/# curl https://api.rubygems.org/api/v1/dependencies -Iv
    * Hostname was NOT found in DNS cache
    *   Trying 54.186.104.15...
    * Connected to api.rubygems.org (54.186.104.15) port 443 (#0)
    * successfully set certificate verify locations:
    *   CAfile: none
      CApath: /etc/ssl/certs
    * SSLv3, TLS handshake, Client hello (1):
    ( curl wait for a long time here, and then timeout )
    * Unknown SSL protocol error in connection to api.rubygems.org:443 
    * Closing connection 0
    curl: (35) Unknown SSL protocol error in connection to api.rubygems.org:443 

Same environment, but access http

    root@caba483189e1:/# curl http://api.rubygems.org/api/v1/dependencies -Iv
    * Hostname was NOT found in DNS cache
    *   Trying 54.186.104.15...
    * Connected to api.rubygems.org (54.186.104.15) port 80 (#0)
    > HEAD /api/v1/dependencies HTTP/1.1
    > User-Agent: curl/7.38.0
    > Host: api.rubygems.org
    > Accept: */*
    > 
    < HTTP/1.1 200 OK
    HTTP/1.1 200 OK
    * Server nginx is not blacklisted
    < Server: nginx
    Server: nginx
    ( ignore ... )

Same command under host with VPN

    jcz@jcz-pc:~/src/backend/jcz-im$ curl https://api.rubygems.org/api/v1/dependencies -Iv
    * Hostname was NOT found in DNS cache
    *   Trying 54.186.104.15...
    * Connected to api.rubygems.org (54.186.104.15) port 443 (#0)
    * successfully set certificate verify locations:
    *   CAfile: none
      CApath: /etc/ssl/certs
    * SSLv3, TLS handshake, Client hello (1):
    * SSLv3, TLS handshake, Server hello (2):
    * SSLv3, TLS handshake, CERT (11):
    * SSLv3, TLS handshake, Server key exchange (12):
    * SSLv3, TLS handshake, Server finished (14):
    ( ignore ... )

The dump of iptables

    jcz@jcz-pc:~/src/backend/jcz-im$ sudo iptables-save 
    # Generated by iptables-save v1.4.21 on Tue May 26 18:35:28 2015
    *mangle
    :PREROUTING ACCEPT [273077:515912715]
    :INPUT ACCEPT [272347:515703059]
    :FORWARD ACCEPT [598:127461]
    :OUTPUT ACCEPT [182453:12240305]
    :POSTROUTING ACCEPT [183140:12379149]
    -A POSTROUTING -o virbr0 -p udp -m udp --dport 68 -j CHECKSUM --checksum-fill
    COMMIT
    # Completed on Tue May 26 18:35:28 2015
    # Generated by iptables-save v1.4.21 on Tue May 26 18:35:28 2015
    *nat
    :PREROUTING ACCEPT [2053:243335]
    :INPUT ACCEPT [1951:234663]
    :OUTPUT ACCEPT [1698:108997]
    :POSTROUTING ACCEPT [1698:108997]
    :DOCKER - [0:0]
    -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
    -A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
    -A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
    -A POSTROUTING -s 192.168.122.0/24 -d 224.0.0.0/24 -j RETURN
    -A POSTROUTING -s 192.168.122.0/24 -d 255.255.255.255/32 -j RETURN
    -A POSTROUTING -s 192.168.122.0/24 ! -d 192.168.122.0/24 -p tcp -j MASQUERADE --to-ports 1024-65535
    -A POSTROUTING -s 192.168.122.0/24 ! -d 192.168.122.0/24 -p udp -j MASQUERADE --to-ports 1024-65535
    -A POSTROUTING -s 192.168.122.0/24 ! -d 192.168.122.0/24 -j MASQUERADE
    COMMIT
    # Completed on Tue May 26 18:35:28 2015
    # Generated by iptables-save v1.4.21 on Tue May 26 18:35:28 2015
    *filter
    :INPUT ACCEPT [272128:515682862]
    :FORWARD ACCEPT [0:0]
    :OUTPUT ACCEPT [182400:12235274]
    :DOCKER - [0:0]
    -A INPUT -i virbr0 -p udp -m udp --dport 53 -j ACCEPT
    -A INPUT -i virbr0 -p tcp -m tcp --dport 53 -j ACCEPT
    -A INPUT -i virbr0 -p udp -m udp --dport 67 -j ACCEPT
    -A INPUT -i virbr0 -p tcp -m tcp --dport 67 -j ACCEPT
    -A FORWARD -o docker0 -j DOCKER
    -A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
    -A FORWARD -i docker0 ! -o docker0 -j ACCEPT
    -A FORWARD -i docker0 -o docker0 -j ACCEPT
    -A FORWARD -d 192.168.122.0/24 -o virbr0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
    -A FORWARD -s 192.168.122.0/24 -i virbr0 -j ACCEPT
    -A FORWARD -i virbr0 -o virbr0 -j ACCEPT
    -A FORWARD -o virbr0 -j REJECT --reject-with icmp-port-unreachable
    -A FORWARD -i virbr0 -j REJECT --reject-with icmp-port-unreachable
    -A OUTPUT -o virbr0 -p udp -m udp --dport 68 -j ACCEPT
    COMMIT
    # Completed on Tue May 26 18:35:28 2015

docker version

    jcz@jcz-pc:~/src/backend/jcz-im$ docker -v 
    Docker version 1.6.2, build 7c8fca2

**Comment by jinchizhong** [comment]
Hi friend,

I have googled and searched and do not found solution or similar issues.
This problem is wide, both in my home and company's computer.
And I have to use VPN because of GFW. T_T

This is my home computer. If necessary, I can add my company's computer info tomorrow.

    Description of problem:
        Cannot access part of https, when VPN is on

    `docker version`:
        Client version: 1.6.2
        Client API version: 1.18
        Go version (client): go1.4.2
        Git commit (client): 7c8fca2
        OS/Arch (client): linux/amd64
        Server version: 1.6.2
        Server API version: 1.18
        Go version (server): go1.4.2
        Git commit (server): 7c8fca2
        OS/Arch (server): linux/amd64

    `docker info`:
        Containers: 16
        Images: 45
        Storage Driver: aufs
         Root Dir: /var/lib/docker/aufs
         Backing Filesystem: extfs
         Dirs: 77
         Dirperm1 Supported: true
        Execution Driver: native-0.2
        Kernel Version: 3.19.0-15-generic
        Operating System: Ubuntu 15.04
        CPUs: 4
        Total Memory: 7.727 GiB
        Name: jcz-nuc
        ID: 5KEH:4FVL:KUG2:I2X5:TRKD:3UCN:UNIK:EI5U:GKEI:ASHU:CS3Y:VZTY
        WARNING: No swap limit support

    `uname -a`:
        Linux jcz-nuc 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

    Environment details (AWS, VirtualBox, physical, etc.):
        ubuntu 15.4 desktop
        PPTP

    How reproducible:
        1. add a vpn to system (I use PPTP, and unity)
        2. $ docker run -i -t ubuntu /bin/bash
        3. $ apt-get update
        4. $ apt-get install curl
        5. turn VPN on
        6. $ curl https://api.rubygems.org/api/v1/dependencies -Iv

    Actual Results:
        * Hostname was NOT found in DNS cache
        *   Trying 54.186.104.15...
        * Connected to api.rubygems.org (54.186.104.15) port 443 (#0)
        * successfully set certificate verify locations:
        *   CAfile: none
          CApath: /etc/ssl/certs
        * SSLv3, TLS handshake, Client hello (1):
        ( remark: suspend for a long time, here ... )
        * Unknown SSL protocol error in connection to api.rubygems.org:443 
        * Closing connection 0
        curl: (35) Unknown SSL protocol error in connection to api.rubygems.org:443 

    Expected Results:
        * Hostname was NOT found in DNS cache
        *   Trying 54.186.104.15...
        * Connected to api.rubygems.org (54.186.104.15) port 443 (#0)
        * successfully set certificate verify locations:
        *   CAfile: none
          CApath: /etc/ssl/certs
        * SSLv3, TLS handshake, Client hello (1):
        * SSLv3, TLS handshake, Server hello (2):
        * SSLv3, TLS handshake, CERT (11):
        * SSLv3, TLS handshake, Server key exchange (12):
        * SSLv3, TLS handshake, Server finished (14):
        * SSLv3, TLS handshake, Client key exchange (16):
        * SSLv3, TLS change cipher, Client hello (1):
        * SSLv3, TLS handshake, Finished (20):
        * SSLv3, TLS change cipher, Client hello (1):
        * SSLv3, TLS handshake, Finished (20):
        * SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
        * Server certificate:
        * 	 subject: OU=Domain Control Validated; OU=EssentialSSL Wildcard; CN=*.rubygems.org
        * 	 start date: 2014-10-16 00:00:00 GMT
        * 	 expire date: 2015-10-16 23:59:59 GMT
        * 	 subjectAltName: api.rubygems.org matched
        * 	 issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Domain Validation Secure Server CA
        * 	 SSL certificate verify ok.
        > HEAD /api/v1/dependencies HTTP/1.1
        > User-Agent: curl/7.38.0
        > Host: api.rubygems.org
        > Accept: */*
        > 
        < HTTP/1.1 200 OK
        HTTP/1.1 200 OK
        * Server nginx is not blacklisted
        < Server: nginx
        Server: nginx
        < Date: Tue, 26 May 2015 13:26:09 GMT
        Date: Tue, 26 May 2015 13:26:09 GMT
        < Content-Type: text/html;charset=utf-8
        Content-Type: text/html;charset=utf-8
        < Content-Length: 0
        Content-Length: 0
        < Connection: keep-alive
        Connection: keep-alive
        < X-Xss-Protection: 1; mode=block
        X-Xss-Protection: 1; mode=block
        < X-Content-Type-Options: nosniff
        X-Content-Type-Options: nosniff
        < X-Frame-Options: SAMEORIGIN
        X-Frame-Options: SAMEORIGIN
        < Vary: Accept-Encoding
        Vary: Accept-Encoding
        < Via: 1.1 vegur
        Via: 1.1 vegur

        < 
        * Connection #0 to host api.rubygems.org left intact

    Additional info:
        If you need a VPN, give me a mail in private.

**Comment by thaJeztah** [comment]
Worth a try; 

@xiaods If I remember correctly, you had some tips for people who are behind the GFW? Perhaps you are able to help out here?

**Comment by xiaods** [comment]
@thaJeztah yeah, let me have a try.

@jinchizhong this is not Docker issue,  if you want to install rubygem, you can change the url to rubygem mirror site:  ruby.taobao.org. and if you want to access rubygems.org, you can use another type vpn to have a try. I don't think docker can resolve this specified issue.

**Comment by jinchizhong** [comment]
@xiaods Thank you for your idea. I known how to set rubygem mirror. But I don't want to write it to Dockerfile. The image will be used in America, access Chinese server is another security issue. (Because GFW is a bidirectional weapon)

T_T

**Comment by xiaods** [comment]
@jinchizhong you can select another vpn provider to check  if the issue always happened.

**Comment by jinchizhong** [comment]
@xiaods I tried 2 VPN, one in San Francisco, another in HongKong.
Neither works. 

But both are PPTP VPN, I don't tried another VPN type.
Because I don't known how to deploy other kind VPN.

BTW, last night, I did lots of experiments.
Maybe this is not a bug for docker, but for Linux kernel.
I tried LXC and KVM. They have same problem too.

And I checked the iptables for LXC and KVM, they are different.
Especially lxc, all rule is blank.
But neither works.

And I tried:
Other proto over 443(OK)
https over another port(Failed)
nmap -sT(443 is open)

**Comment by mountkin** [comment]
@jinchizhong Please add `--mtu=1400`  parameter when your start your docker daemon and test it again.  I noticed that when I start the PPTP connection, the MTU of the ppp0 interface is 1400.
Problems about the MTU can be found here: https://github.com/docker/docker/issues/3596 and http://lartc.org/howto/lartc.cookbook.mtu-discovery.html

**Comment by jinchizhong** [comment]
@mountkin Sorry for reply so later...
I add --mtu=1400 to docker, and it's works.
Thank you very much, that's help me a lot.

**Comment by cpuguy83** [comment]
Closing since this seems like a non-issue and totally related to needing to adjust MTU's for vpn traffic (which is the case even w/o Docker).

**Comment by gcorrao** [comment]
Just to help others, I had this exact issue and also solved it by changing the docker daemon MTU configuration

**Comment by simPod** [comment]
How to set mtu value on OSX?

**Comment by opyate** [comment]
@simPod untested, but try this:

<img width="492" alt="screen shot 2017-03-07 at 15 40 38" src="https://cloud.githubusercontent.com/assets/96808/23664074/7768103c-034c-11e7-8eb9-16c6033d34fc.png">

**Comment by simPod** [comment]
Thanks, will try
