### ISSUE TITLE
docker_remote_api in (Inspect an image) response problem?

### ISSUE THREAD

**Issue by crazywen** [docker/docker#13473]
the document just response the size;
but the actually response the 'size' and 'VirtualSize';
What is their significance?

**Comment by hqhq** [comment]
Do you read document from http://docs.docker.com/reference/api/docker_remote_api_v1.18/#inspect-an-image? I think that's kind of out dated. It's different from source code.

**Comment by hqhq** [comment]
Well, ignore my last post.

If you are asking why in doc it only said `size` but actually you got `Size` and `VirtualSize`, then in doc that's just an example, that's probably not latest, it's command they have some difference.

If you are asking the difference between `Size` and `VirtualSize`, `Size` is the real disk size this image consumes, `VirtualSize` including shared size with it's parent.

**Comment by thaJeztah** [comment]
I think @hqhq answered your question, so I'm going to close this issue, but feel free to comment here if you think I closed this by mistake and there's something else that's incorrect.

**Comment by crazywen** [comment]
thx,i get my answer。
