### ISSUE TITLE
Dockerfile from Postgres:9.1 causes host reboot

### ISSUE THREAD

**Issue by jaybennett89** [docker/docker#13485]
Hi,

I'm a new docker user and I managed to create a simple Dockerfile that caused the host machine to reboot upon starting the container. Docker version was Docker version 1.6.0, build 4749651. The file itself is as follows:

FROM postgres:9.1

CMD printf "%s\n%s\n" "custom_variable_classes = 'ericsson'" "ericsson.session_signum = NULL" >> /var/lib/postgresql/data/postgresql.conf

It should be noted that I also had a massive build context (didn't realize exactly what . was doing). The image would build. Upon starting the container it would reboot the host. As you can see it is a very simple one liner and even if its totally wrong it still shouldn't cause a reboot in the host.

**Comment by unclejack** [comment]
The information requested by the @GordonTheTurtle bot hasn't been provided. Without this information, there's no way to debug the problem as there's insufficient information to investigate the problem. The absence of the steps needed to reproduce is another problem.

I'm going to close this issue now. Should the requested information be provided, this can be opened again.
