### ISSUE TITLE
Make logs pollable (like events)

### ISSUE THREAD

**Issue by jayfk** [docker/docker#13503]
I'd like to suggest a enhancement to the docker remote api: add the option to poll for logs using a timestamp.

**Why**
It's not always feasible to have a long running connection to stream container logs through the remote api. The `tail` option can be used for polling, but adds unnecessary overhead especially  if you call the API consecutively.

**How** 
Add a parameter `since=<timestamp>` and (optionally) `until=<timestamp>`. The event endpoint is a good example for this with the ability to supply since/until timestamps: [Docker Remote API Events](https://docs.docker.com/reference/api/docker_remote_api_v1.18/#monitor-dockers-events)

**Comment by runcom** [comment]
actually this have been already implemented here #12362 and we should have `until` param as well (soon)

I'm going to close this but feel free to ping me if I misunderstood your proposal :)
