### ISSUE TITLE
RPM DB corruption with docker-1.7.0-dev from centos RPM - works in 1.6

### ISSUE THREAD

**Issue by sdake** [docker/docker#13511]
I am the PTL (project technical lead) for an upstream project in OpenStack to containerize OpenStack called Kolla.  We want to use the mount propagation feature of docker 1.7.0-dev.  We are running into problems actually building our docker containers now, however.

The default storage driver went from devicemapper to overlay in 1.7.  This results in an inability to build docker images.  Further, when I try -s devicemapper, that doesn't seem to be a valid option.

I am pretty certain this is an overlay storage driver problem.  A fellow in our community indicated it is because overlay doesn't support sockets properly.

Reliable reproducer:
git clone http://github.com/stackforge/kolla
cd kolla
tools/build-all-docker-images

The first one will fail with rpm database corruption problems.

Log:
http://ur1.ca/mniob -> http://paste.fedoraproject.org/226113/74075514

**Comment by sdake** [comment]
Description of problem:
Docker-1.7.0-dev fails to build a centos container with layers.

`docker version`:
[sdake@bigiron kolla]$ docker version
Client version: 1.7.0-dev
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 3f66f6f
OS/Arch (client): linux/amd64
Server version: 1.7.0-dev
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 3f66f6f
OS/Arch (server): linux/amd64

`docker info`:
[sdake@bigiron kolla]$ docker info
Containers: 1
Images: 10
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.3-200.fc21.x86_64
Operating System: Fedora 21 (Twenty One)
CPUs: 16
Total Memory: 125.9 GiB
Name: bigiron.broked.org
ID: ZIVH:262K:R2AN:3BIL:DGKC:PEB6:LI7U:6BTJ:5FRJ:6YPB:ZLP2:GTIP

`uname -a`:
[sdake@bigiron kolla]$ uname -a
Linux bigiron.broked.org 3.19.3-200.fc21.x86_64 #1 SMP Thu Mar 26 21:39:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
bare metal

How reproducible:
100%

Steps to Reproduce:
1. download our dockerfiles: git clone http://github.com/stackforge/kolla
2. cd kolla/docker/centos/rdo/centos-rdo-base
3. ./build

Note ./build is a wrapper around docker build
Actual Results:
container fails to build

Expected Results:
container builds on 1.6 with devicemapper - should build on 1.7 with overlay :)

Additional info:
Complete!
error: rpmdb: BDB0060 PANIC: fatal region error detected; run recovery
error: db5 error(-30973) from db->close: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: rpmdb: BDB0060 PANIC: fatal region error detected; run recovery
error: db5 error(-30973) from db->close: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: rpmdb: BDB0060 PANIC: fatal region error detected; run recovery
error: db5 error(-30973) from db->close: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: rpmdb: BDB0060 PANIC: fatal region error detected; run recovery
error: db5 error(-30973) from db->close: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: rpmdb: BDB0060 PANIC: fatal region error detected; run recovery
error: db5 error(-30973) from db->close: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: rpmdb: BDB0060 PANIC: fatal region error detected; run recovery
error: db5 error(-30973) from db->close: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: rpmdb: BDB0060 PANIC: fatal region error detected; run recovery
error: db5 error(-30973) from db->close: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: rpmdb: BDB0060 PANIC: fatal region error detected; run recovery
error: db5 error(-30973) from db->close: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: rpmdb: BDB0060 PANIC: fatal region error detected; run recovery
error: db5 error(-30973) from db->close: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: rpmdb: BDB0060 PANIC: fatal region error detected; run recovery
error: db5 error(-30973) from db->close: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: rpmdb: BDB0060 PANIC: fatal region error detected; run recovery
error: db5 error(-30973) from db->close: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: rpmdb: BDB0060 PANIC: fatal region error detected; run recovery
error: db5 error(-30973) from db->close: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: rpmdb: BDB0060 PANIC: fatal region error detected; run recovery
error: db5 error(-30973) from db->close: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: rpmdb: BDB1581 File handles still open at environment close
error: rpmdb: BDB1582 Open file handle: /var/lib/rpm/__db.001
error: rpmdb: BDB1582 Open file handle: /var/lib/rpm/__db.002
error: rpmdb: BDB1582 Open file handle: /var/lib/rpm/__db.003
error: rpmdb: BDB1582 Open file handle: /var/lib/rpm/Packages
error: rpmdb: BDB1582 Open file handle: /var/lib/rpm/Name
error: rpmdb: BDB1582 Open file handle: /var/lib/rpm/Basenames
error: rpmdb: BDB1582 Open file handle: /var/lib/rpm/Group
error: rpmdb: BDB1582 Open file handle: /var/lib/rpm/Requirename
error: rpmdb: BDB1582 Open file handle: /var/lib/rpm/Providename
error: rpmdb: BDB1582 Open file handle: /var/lib/rpm/Conflictname
error: rpmdb: BDB1582 Open file handle: /var/lib/rpm/Obsoletename
error: rpmdb: BDB1582 Open file handle: /var/lib/rpm/Triggername
error: rpmdb: BDB1582 Open file handle: /var/lib/rpm/Dirnames
error: rpmdb: BDB1582 Open file handle: /var/lib/rpm/Installtid
error: rpmdb: BDB1582 Open file handle: /var/lib/rpm/Sigmd5
error: rpmdb: BDB1582 Open file handle: /var/lib/rpm/Sha1header
error: rpmdb: BDB0060 PANIC: fatal region error detected; run recovery
error: db5 error(-30973) from dbenv->close: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: rpmdb: BDB0060 PANIC: fatal region error detected; run recovery
error: db5 error(-30973) from db->close: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: rpmdb: BDB0060 PANIC: fatal region error detected; run recovery
error: db5 error(-30973) from db->close: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: rpmdb: BDB0060 PANIC: fatal region error detected; run recovery
error: db5 error(-30973) from db->close: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: rpmdb: BDB0060 PANIC: fatal region error detected; run recovery
error: db5 error(-30973) from db->close: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: rpmdb: BDB0060 PANIC: fatal region error detected; run recovery
error: db5 error(-30973) from db->close: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: rpmdb: BDB0060 PANIC: fatal region error detected; run recovery
error: db5 error(-30973) from db->close: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: rpmdb: BDB0060 PANIC: fatal region error detected; run recovery
error: db5 error(-30973) from db->close: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: rpmdb: BDB0060 PANIC: fatal region error detected; run recovery
error: db5 error(-30973) from db->close: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: rpmdb: BDB0060 PANIC: fatal region error detected; run recovery
error: db5 error(-30973) from db->close: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: rpmdb: BDB0060 PANIC: fatal region error detected; run recovery
error: db5 error(-30973) from db->close: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: rpmdb: BDB0060 PANIC: fatal region error detected; run recovery
error: db5 error(-30973) from db->close: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: rpmdb: BDB0060 PANIC: fatal region error detected; run recovery
error: db5 error(-30973) from db->close: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: rpmdb: BDB0060 PANIC: fatal region error detected; run recovery
error: db5 error(-30973) from db->close: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: rpmdb: BDB1581 File handles still open at environment close
error: rpmdb: BDB1582 Open file handle: /var/lib/rpm/__db.001
error: rpmdb: BDB1582 Open file handle: /var/lib/rpm/__db.002
error: rpmdb: BDB1582 Open file handle: /var/lib/rpm/__db.003
error: rpmdb: BDB1582 Open file handle: /var/lib/rpm/Packages
error: rpmdb: BDB1582 Open file handle: /var/lib/rpm/Name
error: rpmdb: BDB1582 Open file handle: /var/lib/rpm/Basenames
error: rpmdb: BDB1582 Open file handle: /var/lib/rpm/Group
error: rpmdb: BDB1582 Open file handle: /var/lib/rpm/Requirename
error: rpmdb: BDB1582 Open file handle: /var/lib/rpm/Providename
error: rpmdb: BDB1582 Open file handle: /var/lib/rpm/Conflictname
error: rpmdb: BDB1582 Open file handle: /var/lib/rpm/Obsoletename
error: rpmdb: BDB1582 Open file handle: /var/lib/rpm/Triggername
error: rpmdb: BDB1582 Open file handle: /var/lib/rpm/Dirnames
error: rpmdb: BDB1582 Open file handle: /var/lib/rpm/Installtid
error: rpmdb: BDB1582 Open file handle: /var/lib/rpm/Sigmd5
error: rpmdb: BDB1582 Open file handle: /var/lib/rpm/Sha1header
error: rpmdb: BDB0060 PANIC: fatal region error detected; run recovery
error: db5 error(-30973) from dbenv->close: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
The command '/bin/sh -c yum -d 10 -y install systemd systemd-libs systemd-devel && yum clean all' returned a non-zero code: 1
ERROR: failed to build kollaglue/centos-rdo-base:378de66

**Comment by sdake** [comment]
Reached out to @rhatdan got following:

[08:31:02]  <dwalsh>	sdake, rpm open database twice, once as read/only later as read/write.  Which causes a writeup and ends up with the app pointing to two different files.
[08:31:23]  <dwalsh>	Gets confused and all hell breaks loose.
[08:31:28]  <sdake>	dwalsh thanks that explains it
[08:31:35]  <dwalsh>	Overlayfs is just not quite ready for prime time.
[08:31:58]  <sdake>	so thats not a docker thing thats a kernel.org thing sounds like
[08:32:22]  <dwalsh>	Or an rpm thing, depending on who you want to point the finger at.
[08:32:41]  <dwalsh>	I think yum -y update in docker build blows up, which triggered people figuring this out.

**Comment by tiborvass** [comment]
@sdake thanks, I'm closing this for now then. Please follow up with additional information as you have it.

**Comment by rhatdan** [comment]
@tiborvass You might want to add this to release notes that overlayfs does not support this flow.

**Comment by thaJeztah** [comment]
A note was added about incompatibility with RPM in https://github.com/docker/docker/pull/13561
