### ISSUE TITLE
docker0 dies without message

### ISSUE THREAD

**Issue by poelzi** [docker/docker#13513]
We use gitlab-ci-multi runner that spawn docker instances for build jobs. We notice that docker0 sometimes disappears with no reason or message in the docker log.

The images started run in privileged mode and run a internal docker server (docker in docker).

this maybe related:
http://stackoverflow.com/questions/28923743/dockers-docker0-device-dies-repeatedly-inet-addr-disappears

We are not running dhclient or any other network mananger. a cronjob now checks if docker0 exists.
It seems to be related to fast start/teardown of images.

From the last restart:
```
ESC[34mINFOESC[0m[4979] -job log(start, 8699bc8620abe05e5c507d0f555188e1a9dc460d5ffed0075ed1218d3c0b246b, docker-registry.cloudandheat.com/cloudandheat/gitlab-ci-runner:latest) = OK (0)
ESC[34mINFOESC[0m[4979] -job start(8699bc8620abe05e5c507d0f555188e1a9dc460d5ffed0075ed1218d3c0b246b) = OK (0)
ESC[34mINFOESC[0m[4979] POST /containers/8699bc8620abe05e5c507d0f555188e1a9dc460d5ffed0075ed1218d3c0b246b/attach?logs=1&stderr=1&stdin=1&stdout=1&stream=1
ESC[34mINFOESC[0m[4979] +job container_inspect(8699bc8620abe05e5c507d0f555188e1a9dc460d5ffed0075ed1218d3c0b246b)
ESC[34mINFOESC[0m[4979] -job container_inspect(8699bc8620abe05e5c507d0f555188e1a9dc460d5ffed0075ed1218d3c0b246b) = OK (0)
ESC[34mINFOESC[0m[4979] +job attach(8699bc8620abe05e5c507d0f555188e1a9dc460d5ffed0075ed1218d3c0b246b)
ESC[34mINFOESC[0m[5094] Received signal 'terminated', starting shutdown of docker...
ESC[34mINFOESC[0m[0000] +job serveapi(unix:///var/run/docker.sock)
ESC[34mINFOESC[0m[0000] Listening for HTTP on unix (/var/run/docker.sock)
ESC[34mINFOESC[0m[0005] +job init_networkdriver()
ESC[34mINFOESC[0m[0005] -job init_networkdriver() = OK (0)
ESC[33mWARNESC[0m[0005] Your kernel does not support cgroup swap limit.
ESC[34mINFOESC[0m[0005] Loading containers: start.
.............................................................................................................................................................................................................................................
....................................................................................................ESC[34mINFOESC[0m[0007] +job allocate_interface(4085402aaa3d5da2fa41b9a7a37778c2bd270bc0911807880f5b75b2eb93bdc6)
ESC[34mINFOESC[0m[0007] -job allocate_interface(4085402aaa3d5da2fa41b9a7a37778c2bd270bc0911807880f5b75b2eb93bdc6) = OK (0)
```

**Comment by poelzi** [comment]
root@gitlabcirunner5:~# docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

root@gitlabcirunner5:~# docker info
Containers: 160
Images: 108
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 438
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-53-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 4
Total Memory: 7.798 GiB
Name: gitlabcirunner5
ID: NMXE:RR4X:N6CV:JC3X:FI4O:6RFG:GMKA:VX5S:3QE3:63TP:2BUM:JL34
WARNING: No swap limit support

Running on VM in KVM (openstack). Only root filesystem directly mounted from host.

root@gitlabcirunner5:~# uname -a
Linux gitlabcirunner5 3.13.0-53-generic #89-Ubuntu SMP Wed May 20 10:34:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

No steps to reproduce it yet. Now running in debug output to collect more informations.

**Comment by cpuguy83** [comment]
This sounds related to something else running on the host.
Is this still an issue? Have you tried with 1.7.0 (which has a complete network rewrite)?

**Comment by cpuguy83** [comment]
Closing as this one seems to have gone cold.
Ping here if you still have an issue on the latest docker (currently 1.8).
