### ISSUE TITLE
docker registry might be having some issues right now...

### ISSUE THREAD

**Issue by cliveb** [docker/docker#13519]
...It couldn't properly fetch some images for me for 6 days till now. Is there anyway to trigger an automated build w/o taking on someone else's docker project?

Description of problem:

https://registry.hub.docker.com/u/wasabeef/android/

Pulling repository wasabeef/android
e688e6c18784: Error pulling image (latest) from wasabeef/android, Untar gzip: invalid header

539c0211cd76: Error downloading dependent layers 
INFO[0236] Error pulling image (latest) from wasabeef/android, Untar gzip: invalid header 
make: *** [env] Error 1

`docker version`:
Client version: 1.6.2
Client API version: 1.18

Go version (client): go1.4.2
Git commit (client): 7c8fca2
  
`docker info`:

Server version: 1.6.2
Server API: 1.18

`uname -a`:

wasabeef
cliveb

Environment details (AWS, VirtualBox, physical, etc.):

OS/Arch (client): darwin/amd64
OS/Arch (server): linux/amd64

How reproducible:

Easiest way 
Install Boot2docker for Mac OS X

$ git clone https://camlistore.googlesource.com/camlistore
Build Camlistore by running this command in the folder you downloaded or checked out:
$ go run make.go

To build the Android binary use Docker.

Steps to Reproduce:
  
$ cd camlistore/clients/android
$ make env  # builds a docker image w/ android sdk + go compilers

Actual Results:

Pulling repository wasabeef/android
e688e6c18784: Error pulling image (latest) from wasabeef/android, Untar gzip: invalid header

539c0211cd76: Error downloading dependent layers 
INFO[0236] Error pulling image (latest) from wasabeef/android, Untar gzip: invalid header 
make: *** [env] Error 1

Expected Results:

Unzip gzip: completes

Additional info:

related https://github.com/wasabeef/dockerfiles/issues/1

**Comment by thaJeztah** [comment]
@cliveb if you're having issues with the Docker Hub, please report them via https://support.docker.com. Support for Docker Hub is not handled via the GitHub issue tracker.
