### ISSUE TITLE
Setting stack size limit either prevents container from starting or the values set are ignored.

### ISSUE THREAD

**Issue by delcypher** [docker/docker#13521]
## Description of problem:

I'm trying to use the newly added ``--ulimit`` functionality added (by @cpuguy83 ) to the docker client and the ``docker-py`` API. I discovered when trying set the stack limit that this seems to prevent the container from being started or the values set are ignored.

``docker-version``:  ``Docker version 1.6.2, build 7c8fca2``

``docker info``:
```
Containers: 28
Images: 259
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 4.0.4-2-ARCH
Operating System: Arch Linux
CPUs: 4
Total Memory: 7.709 GiB
Name: dan-sputnik
ID: **redacted**
Username: delcypher
Registry: [https://index.docker.io/v1/]
```

``uname -a``: ``Linux dan-sputnik 4.0.4-2-ARCH #1 SMP PREEMPT Fri May 22 03:05:23 UTC 2015 x86_64 GNU/Linux``

## Environment details:

This was running natively on my Arch Linux machine

## Steps to reproduce:

I first discovered this when trying to set the stack limit via the ``docker-py`` API but I discovered the same issue occurred on the command line. I'm assuming that the arguments for stack are in bytes like ``RLIMIT_STACK`` in ``prlimit()`` (confusingly ``bash`` works in terms of KiB, not bytes).

1. Run

```
$ docker run --rm -ti --ulimit stack=8277716992:8277716992 ubuntu:14.04 /bin/bash -c ulimit -s -H
```

The stack size I'm setting is the amount of physical memory my machine has in bytes. Side note it would be nice to be able to set unlimited here (i.e. ``RLIM_INFINITY``) but that doesn't seem possible currently.

I get the following error message

```
FATA[0000] Error response from daemon: Cannot start container c702b6a6d2897fa877659c101879fccdf22a660a186e340d395421b58ff78bf1: [8] System error: argument list too long 
```

if I try smaller values they don't seem to have an affect. I don't expect unlimited to be outputted here but it is.

```
$ docker run --rm -ti --ulimit stack=168676:168676 ubuntu:14.04 /bin/bash -c ulimit -s
unlimited
```

This shouldn't happen.

**Comment by delcypher** [comment]
@cpuguy83 @thaJeztah @SvenDowideit @jeremyeder @icecrime Ping

Sorry if this isn't relevant to you. I just took a few usernames from the the original [PR](https://github.com/docker/docker/pull/9437) that looked like they were interested.

**Comment by cpuguy83** [comment]
Can you try with the 1.7-rc1? https://github.com/docker/docker/pull/13528#issuecomment-106157829
Also, please do this in a test env and not on something important as there are known issues in downgrading from from 1.7.

**Comment by delcypher** [comment]
@cpuguy83 Okay. Will I avoid downgrade issues if I use a separate graph directory? It's either that or I run docker inside docker.

**Comment by cpuguy83** [comment]
Any update here?

**Comment by delcypher** [comment]
@cpuguy83 You don't really need me to confirm this as the issue is reproducible from a single command line.

I've updated my machine to

```
Docker version 1.7.1, build 786b29d
```

The command

```
$ docker run --rm -ti --ulimit stack=8277716992:8277716992 ubuntu:14.04 /bin/bash -c ulimit -s -H
unlimited
```

no longer fails :)

however the following command still behaves unexpectedly

```
$ docker run --rm -ti --ulimit stack=168676:168676 ubuntu:14.04 /bin/bash -c ulimit -s
unlimited
```

the stack limit should not be reported as unlimited. This makes me think that it might be the case that the first command no longer fails because the stacklimit is not being set at all.

**Comment by cpuguy83** [comment]
Your command is wrong :)

Need to put everything after `-c` in quotes.

**Comment by delcypher** [comment]
> Your command is wrong :)

Doh!
```
docker run --rm -ti --ulimit stack=8277716992:8277716992 ubuntu:14.04 /bin/bash -c "ulimit -s -H"
808370
````

I guess this can be closed then :D

**Comment by thaJeztah** [comment]
@delcypher thanks for confirming! And no worries, I think we all made that mistake :smile:
