### ISSUE TITLE
Add support for starting multiple containers from a dockerfile

### ISSUE THREAD

**Issue by ulope** [docker/docker#1352]
Currently it's not very easy to run complex setups consisting of multiple services that should each run in their own container.
It would be very useful to be able run such setups with a single docker command.

I see at least two possible solutions:
*  allow specifying multiple CMDs / ENTRYPOINTs (with their own port mappings) in a dockerfile 
* add some kind of dependency system between images / dockerfiles

**Comment by cpuguy83** [comment]
Closing since this is what docker-compose is doing ( github.com/docker/fig and #9694 )
