### ISSUE TITLE
Getting  "FATA[0041] Error response from daemon... " on Docker Login

### ISSUE THREAD

**Issue by jekram** [docker/docker#13531]
Description of problem:
FATA[0041] Error response from daemon: Server Error: Post https://index.docker.io/v1/users/: dial tcp: lookup index.docker.io on 192.168.1.1:53: read udp 192.168.1.1:53: i/o timeout 

Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): darwin/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64

`uname -a`: jawaid

Environment details (AWS, VirtualBox, physical, etc.): Mac OS

How reproducible: Every time

Steps to Reproduce:
1. Login
2.
3.

Actual Results:
FATA[0041] Error response from daemon: Server Error: Post https://index.docker.io/v1/users/: dial tcp: lookup index.docker.io on 192.168.1.1:53: read udp 192.168.1.1:53: i/o timeout 

Expected Results:

Additional info:

**Comment by thaJeztah** [comment]
Just a quick initial thought; based on this;

    dial tcp: lookup index.docker.io on 192.168.1.1:53: read udp 192.168.1.1:53: i/o timeout

I'd say that Docker is unable to connect to your DNS server. Are you sure that DNS server is working correctly?

**Comment by jmakanjuola** [comment]
@thaJeztah I agree that it a network issue.

**Comment by thaJeztah** [comment]
Agreed, reading back this, I don't think this is a bug in docker but a problem in your network, DNS-server or setup.

I'm going to close this issue for that reason, but feel free to comment here, and "ping" me if you think I closed this by mistake.

**Comment by mcbhenwood** [comment]
To add some closure for folks who arrive here after a Google search: I had the same error, also in OSX. Restarting the Boot2Docker VM cleared it; therefore entirely a localised network problem.

**Comment by flaccid** [comment]
@mcbhenwood really appreciate that comment, was my issue too; boot2docker is not robust yet, issues mean I kill and re-do (https://docs.docker.com/installation/mac/) a lot.

**Comment by donald-s** [comment]
Same here. I'm using Docker Machine though, so restarting my VM via Docker Machine did the trick for me. Definitely seems like it is an internal network issue with the VM.

**Comment by TroyWorks** [comment]
restarting VM, machine and network fixed this for me.

I paused the VM, upgraded the network (router, modem, etc) and when the machine/vm restarted whatever IP stuff it was expecting no longer existed, so needed to be refeshed.

**Comment by htmldrum** [comment]
:+1: for @TroyWorks
