### ISSUE TITLE
Is LDAP authentication supported by registry 2 ?

### ISSUE THREAD

**Issue by wx1982** [docker/docker#13545]

**Comment by thaJeztah** [comment]
I saw it on the roadmap; https://github.com/docker/distribution/blob/f2954260a63f041bb5aeed3bb854502a86231111/ROADMAP.md#registry-20

But I *think* it hasn't actually been implemented (yet?), see this comment; https://github.com/docker/distribution/pull/367#issuecomment-93621596

@dmp42 do you know if the "Pluggable authentication system" (e.g. LDAP authentication) is still on the roadmap for Registry?

**Comment by dmp42** [comment]
The registry supports a pattern where authentication itself is delegated to a secondary server that then issues a signed grant that the registry can verify.

This design is indeed implemented and supported, and does allow for that secondary server to use whatever authentication backend it wants.

Though, we don't provide implementation examples, specifically we don't ship a running LDAP connector (getting AD to behave is notoriously difficult).

Now, DHE  does ship with LDAP support IIRC (https://www.docker.com/enterprise/hub/)

In a shell, if you want LDAP:

 * DIY using the token / delegated auth path for the registry
 * use DHE, or any other product that ship with it
