### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by AndyBerman** [docker/docker#13540]
The page at https://github.com/docker/docker has 2 broken links in the line " The cgroup and namespacing capabilities of the Linux kernel".

**Comment by thaJeztah** [comment]
Thanks for reporting! Looks like that site is no longer "live"

For reference, the links refer to the http://blog.dotcloud.com domain;

http://blog.dotcloud.com/kernel-secrets-from-the-paas-garage-part-24-c
http://blog.dotcloud.com/under-the-hood-linux-kernels-on-dotcloud-part

And on the wayback machine;
http://web.archive.org/web/20150326152913/http://blog.dotcloud.com/kernel-secrets-from-the-paas-garage-part-24-c
http://web.archive.org/web/20150326185901/http://blog.dotcloud.com/under-the-hood-linux-kernels-on-dotcloud-part


@moxiegirl any idea if those blog-posts have been migrated to the current blog, or are archived somewhere?

**Comment by moxiegirl** [comment]
@thaJeztah I'll check and see what is up with those.

**Comment by thaJeztah** [comment]
Thanks again for reporting this, @AndyBerman it took a while, but we decided to replace the links in https://github.com/docker/docker/pull/14244 by absence of the original blogs, so I'm going to close this.

Keep those (bug)reports coming, it's much appreciated!
