### ISSUE TITLE
update contrib/check-config.sh CONFIG_RESOURCE_COUNTERS is removed in new kernel

### ISSUE THREAD

**Issue by s7v7nislands** [docker/docker#13543]
CONFIG_RESOURCE_COUNTERS is removed in new kernel.

https://github.com/torvalds/linux/commit/5b1efc027c0b51ca3e76f4e00c83358f8349f543

**Comment by hqhq** [comment]
Yeah, I've noticed that before, forgot to fix it.
#dibs

**Comment by wking** [comment]
Can we close this now that #13546 has landed?

**Comment by tianon** [comment]
:+1:
