### ISSUE TITLE
Memory Leak with Syslog Driver

### ISSUE THREAD

**Issue by sschepens** [docker/docker#13552]
### Description of problem:
I'm experiencing docker daemon using LOTS of memory when using syslog driver and container logging lots of messages per seconds.
Using syslog driver:
```bash
$ sudo docker run -d --log-driver syslog ubuntu:latest bash -c "for i in \$(seq 100000); do echo \"testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest\"; done"
```
Docker daemon now consumes aproximately 40% (38.8%) of memory:
```bash
$ ps aux|grep docker| grep -v grep
root     32558  8.8 38.8 841024 395048 ?       Ssl  14:41   0:03 /usr/bin/docker -d
```

Usging json log driver:
```bash
$ sudo docker run -d ubuntu:latest bash -c "for i in \$(seq 100000); do echo \"testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest\"; done"
```
Docker daemon consumes aproximately 2% (1.5%) of memory:
```bash
$ ps aux|grep docker| grep -v grep
root     32717 11.6  1.5 356052 15376 ?        Ssl  14:43   0:04 /usr/bin/docker -d
```

OS Info:
I'm running docker in an EC2 t2.micro ubuntu server 14.04 instance:
```bash
$ uname -a
Linux ip-172-31-32-169 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

### Docker version:
```bash
$ docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

### Docker Info:
```bash
$ docker info
Containers: 4
Images: 4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 12
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-48-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 992.5 MiB
Name: ip-172-31-32-169
ID: MKQ5:EPHS:PNVG:DS6X:JOCT:QIRW:ROW2:FI4J:LSAL:RPFD:ZOJX:S23P
WARNING: No swap limit support
```

**Comment by runcom** [comment]
I'll spin up a micro instance to try to repro cause it's not happening on my machine (ubuntu 14.10 with 4.0.0 kernel) with latest 1.7 rc1

**Comment by runcom** [comment]
seems like it's not happening on 1.7.0 rc1 but please confirm this :)

**Comment by sschepens** [comment]
@runcom is there an easy way of installing 1.7.0rc1 on ubuntu? is there an unstable ppa or something?

**Comment by runcom** [comment]
@sschepens look here, I'm still testing something right now tho

**Comment by lizf-git** [comment]
Can't reproduce this issue in my laptop with docker 1.6.2 and ubuntu 14.04 (kernel 3.13).

**Comment by sschepens** [comment]
@runcom tested with with 1.7.0rc1 and having the same issue.
I have configured rsyslog as my system's syslog server.
I'm thinking this may be happen if syslog takes long time to process messages maybe?

**Comment by LK4D4** [comment]
@sschepens Yes, probably slow processing. Also you will lose messages if this is a case :/

**Comment by sschepens** [comment]
@LK4D4 @runcom here is my syslog config, could you give this a test?
```bash
cat /etc/rsyslog.d/10-docker.conf
# Docker logging

$SystemLogRateLimitInterval 1
$SystemLogRateLimitBurst 100000000

if $programname contains 'docker' then {
  action(type="omfile" dirCreateMode="0700" FileCreateMode="0644"
       File="/tmp/rsyslog.log")
}
```
```bash
$ cat /etc/rsyslog.conf 
$ModLoad imuxsock # provides support for local system logging
$ModLoad imklog   # provides kernel logging support (previously done by rklogd)

$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

$RepeatedMsgReduction off

$FileOwner syslog
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022
$PrivDropToUser syslog
$PrivDropToGroup syslog

$WorkDirectory /var/spool/rsyslog

$IncludeConfig /etc/rsyslog.d/*.conf
```

 I know that i would loose messages if a process happens to be logging so fast, but i wouldn't expect my system to crash because docker daemon eats up al available memory. Plus, docker daemon never releases memory back to the system after the logging spree ended.

**Comment by unclejack** [comment]
I'll look into this.

**Comment by LK4D4** [comment]
This can be because of overcomplicated broadcastwriter. I'm pretty sure that we can remove `json-logs` part from it.
@sschepens I think your memory should be released after half-hour.
Also std syslog driver has VERY bad bug golang/go#5932 , which can lead to leaks as well.

**Comment by oncletom** [comment]
I also encounter such an error with Docker 1.7.0 and syslog driver enabled on an EC2 t2.micro instance.

Recurrent error is: *Error response from daemon: Cannot start container 5cbc9625e9d954ebc6115e955de528617ca59d841e05b22a2f7b7e33e9e8120e: namespace creation reexec command failed: fork/exec /usr/bin/docker: cannot allocate memory*

The containers are chatty log-wise, we have 3 long-running one spawning ~500 ephemeral containers per hour.

```bash
$ docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

```bash
$ docker info
Containers: 3
Images: 119
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 125
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: syslog
Kernel Version: 3.13.0-53-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 992.5 MiB
Name: ip-10-0-0-192
ID: L3LB:QZSG:F6GO:KSSJ:MJFJ:N7TV:ALPX:OHTN:JWXH:TEBP:AASQ:37FJ
WARNING: No swap limit support
```

```bash
$ free
             total       used       free     shared    buffers     cached
Mem:       1016340     921332      95008        860      58864     134856
-/+ buffers/cache:     727612     288728
Swap:            0          0          0
```

**Comment by joantune** [comment]
It has been happening recently with me as well.
```
root@debian:/home/joantune# docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

```
root@debian:/home/joantune# docker info
Containers: 5
Images: 315
Storage Driver: devicemapper
 Pool Name: docker-202:0-131843-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 12.74 GB
 Data Space Total: 107.4 GB
 Data Space Available: 80.96 GB
 Metadata Space Used: 22.56 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.125 GB
 Udev Sync Supported: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 4.0.4-x86_64-linode57
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 4
Total Memory: 3.906 GiB
Name: debian
ID: WAL2:ETBL:QJOK:UBQ5:EUZS:QJU5:ETXB:4IN3:B2YH:26SJ:F7OZ:PONU
WARNING: No memory limit support
WARNING: No swap limit support
```

Let me know if there's any kind of info that I can provide to help

**Comment by joantune** [comment]
Humm, the memory usage dropped kinda suddenly, no idea on the why, but there have been some containers that have been stopped and others that have started that could have triggered that ??. However, the initial problem showed the docker daemon consuming the memory, not the children processes i.e. the app(s)/services I run with docker

**Comment by nagas** [comment]
I have the same issue on my machine. Setup is as follows:
EC2 machine (m4.xlarge),
Ubuntu 14.04 (3.13.0-48-generic),
Docker 1.7.1 (build 786b29d).

I can reproduce it every time by running:
```for i in {1..30}; do docker run -d --log-driver=syslog ubuntu timeout 30 yes `env`; done```
It takes all available memory (RES ~14G, VIRT ~20G) in a matter of seconds. 

My rsyslog configuration:
```
$RepeatedMsgReduction off
daemon.* {
 /var/log/docker.log
 stop
}
```

**It looks like it's not happening when `$RepeatedMsgReduction` is set to `on`, which makes rsyslog to reduce repeated log messages.**

**Comment by LK4D4** [comment]
@nagas Looks like just syslog isn't fast enough to consume such messages flow.

**Comment by onorua** [comment]
@LK4D4 I have enabled statistics for rsyslog with following config:
```
module(
  load="impstats"
  interval="1"             # how often to generate stats
  resetCounters="on"        # to get deltas (e.g. # of messages submitted in the last 10 seconds)
  log.file="/tmp/stats"     # file to write those stats to
  log.syslog="off"          # don't send stats through the normal processing pipeline. More on that in a bit
)
```
and here you can find what happens:
![msgsec](https://cloud.githubusercontent.com/assets/407040/8762961/2d9db6d6-2dbb-11e5-8b66-17d1e2ef5f90.jpeg)
it means that rsyslog can actually receive much more than even 5k/sec while docker sends about 1.5-3k messages, but some times (when RAM is out) you can see some spikes of msg/sec. 
Are you sure that rsyslog is the bottleneck here?

**Comment by LK4D4** [comment]
@onorua no, I'm not sure, but syslog driver is pretty simple, you can read through it, it should be faster than json-file.

**Comment by icecrime** [comment]
This issue has been confirmed by our infra, and got them to move away from the syslog logging driver. I'm adding this to the 1.9.0 milestone (can be 1.8.2 if we find a localized fix).

**Comment by icecrime** [comment]
@runcom @LK4D4 @unclejack Did you get a chance to look into this? Do you have any idea? I can try to get more details on my side.

**Comment by unclejack** [comment]
@icecrime I'll try something and comment soon on this issue.

**Comment by LK4D4** [comment]
I'll try too.

**Comment by LK4D4** [comment]
I can't reproduce serious leak without superintense writing, which also case for other drivers. We can reduce leaks if we swap timeout-size priority in bufReader and call `debug.FreeOSMemory` on buffer reset, but probably that won't be full fix and people with syslog will lose all messages because of syslog driver bug. WDYT @unclejack

**Comment by icecrime** [comment]
The weird thing is that @bmangold suggested that moving out of the syslog logging driver fixed it: you're saying that it shouldn't grow more/faster than others?

**Comment by LK4D4** [comment]
@icecrime it could grow faster if syslog daemon is slow. For me with local journald I can hardly measure memory consumption more than mux router.

**Comment by sschepens** [comment]
@LK4D4 @icecrime I recall this was not happening with json file logging driver with the same amount of intenste writing. When I reported the issue I tested without syslog and did not see any issue.

**Comment by unclejack** [comment]
@LK4D4 I think the FreeOSMemory hack would be good as a last resort, but I wouldn't rely on it to fix this problem.

Here's what I'd propose:
- add support for external logging plugins which aren't included in the main Docker binary
- migrate syslog logging to an external plugin & package it with Docker
- make any necessary changes to the syslog code

JSON file logging doesn't have these problems because its code has been changed repeatedly to avoid memory related issues.

**Comment by LK4D4** [comment]
@unclejack We can fork syslog to make change which fixes deadlock on older kernels.
What do you think about reversing timeout-size priority? With high-amount logging I can eat memory in less than minute and timeout is 3-5 minutes.

**Comment by unclejack** [comment]
@LK4D4 I'm OK with forking syslog and vendoring that.

**Comment by sgirones** [comment]
This can be easily reproduced if the rsyslog endpoint is down after the container is created and the container generates output faster than Docker discards the logs when they fail to be delivered.

The Docker daemon will eventually OOM and affect the rest of containers running on the same host.

What do you think about enforcing a limit on the amount of pending logs?

**Comment by rvadim** [comment]
So, as i understand, docker 1.7 and 1.8 have no limits for log buffer in any realization of log driver, and when logs can't be read from buffer(disk is full, syslog server down, network problem, disk subsytem overloaded), buffer will grow until heap memory is over?
And, why we break all system(OOM kill docker daemon), in case when we can't write logs?
I just can not afford to stop production containers, because periphery malfunction.

**Comment by onorua** [comment]
@rvadim for some cases, it's better to don't process anything rather than process without keeping traces of what had been done. Bank sector come to my mind as an example, if you have no logs, auditor can treat it as a breach. 
So I would rather make buffer limit configurable for such type of applications as well. But you are right, for most people logging stays aside from production operation.

**Comment by LK4D4** [comment]
We capped buffer in #17877 
Feel free to try and post your opinion.
