### ISSUE TITLE
docker 1.6.2: System error: accessing a corrupted shared library while start new container

### ISSUE THREAD

**Issue by nkwangleiGIT** [docker/docker#13570]
Hi, I got the exception below when trying to start a new container on a system that already had some running containers:

root@iZ25ascko3yZ:/var/lib/docker# docker run -it ubuntu /bin/bash
accessing a corrupted shared library
```FATA[0000] Error response from daemon: Cannot start container 518652250d5617048f9c2876634b4c083fc9937823f554b35685a30c1eed3bfe: [8] System error: accessing a corrupted shared library ```

I'm using devicemapper as the backend storage, here is my docker version and info, let me know if any suggestions or workaround:

docker version
```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.2.1
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.2.1
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```
docker info
```
Storage Driver: devicemapper
 Pool Name: docker-202:17-1359873-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop4
 Metadata file: /dev/loop5
 Data Space Used: 2.469 GB
 Data Space Total: 107.4 GB
 Data Space Available: 102.9 GB
 Metadata Space Used: 5.612 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.142 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Kernel Version: 3.18.0-031800-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 4
Total Memory: 7.796 GiB
Name: iZ25ascko3yZ
ID: IW2E:IM27:KNG2:GSSL:XIQG:HC6H:JN4I:ZSLP:L7PO:YCON:TPHB:MJ6W
```
Thanks.

**Comment by nkwangleiGIT** [comment]
Hi,  see my detail information below:
Description of problem:
Run into the exceptions below while starting a new container on a system that already had some running containers:
```
root@iZ25ascko3yZ:/var/lib/docker# docker run -it ubuntu /bin/bash
accessing a corrupted shared library
FATA[0000] Error response from daemon: Cannot start container 518652250d5617048f9c2876634b4c083fc9937823f554b35685a30c1eed3bfe: [8] System error: accessing a corrupted shared library
```

`docker version`:
```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.2.1
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.2.1
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

`docker info`:
```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.2.1
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.2.1
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
root@iZ25va7drfmZ:~# docker info
Containers: 112
Images: 178
Storage Driver: devicemapper
 Pool Name: docker-202:17-6275073-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.468 GB
 Data Space Total: 107.4 GB
 Data Space Available: 99.95 GB
 Metadata Space Used: 9.585 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.138 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Kernel Version: 3.13.0-32-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 4
Total Memory: 7.797 GiB
Name: iZ25va7drfmZ
ID: 6EIB:GWCL:JMQY:O5NP:2I6A:SMCP:ZCC3:XFXF:WKQO:4COK:RCTZ:RKKK
```

`uname -a`:
```
Linux iZ25va7drfmZ 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.):
Physical machine

How reproducible:

Steps to Reproduce:
1. Start some containers first, and memory on the host will be in low status:
```KiB Mem:   8175580 total,  7934192 used,   241388 free,   468984 buffers```
2. Then try to create a new container, like "docker run -d tomcat"

3. Then you'll see the exception above

Actual Results:
System error: accessing a corrupted shared library

Expected Results:
The container should be created normally

Additional info:

**Comment by nkwangleiGIT** [comment]
Could you help take a look at this issue? thanks!

**Comment by thaJeztah** [comment]
I noticed the first comment mentions a kernel 3.18, and the second a kernel 3.13; are those different machines or did you switch kernels?

**Comment by nkwangleiGIT** [comment]
Hi thaJeztah,
Yes, I tried to upgrade the kernel version from 3.13 to 3.18 to see if this DM issue can be fixed. I also clear /var/lib/docker directory after upgrade, but seems it didn't work after just upgrade the kernel.

Thanks!

**Comment by icecrime** [comment]
I'm going to close this as it is very old, and there's nothing in the data so far which points to a Docker issue. Sorry if you're still encountering the problem: feel free to ping me and I'll reopen if you're still experiencing this with newer Docker versions.
