### ISSUE TITLE
Paused container has true running state

### ISSUE THREAD

**Issue by hqhq** [docker/docker#13579]
Here is the thing:
```
$ docker run --ti --rm --name test ubuntu bash
(change to another terminal)
$ docker inspect -f "{{.State.Running}}" test
true
$ docker inspect -f "{{.State.Paused}}" test
false
$ docker pause test
$ docker inspect -f "{{.State.Running}}" test
true
$ docker inspect -f "{{.State.Paused}}" test
true
```

Many users could consider this confused (someone complained in irc), I was trying to fix this, then I found it breaks `docker ps -f status=paused`. 

Found code in `daemon/state.go:String()`
```
 25 func (s *State) String() string {
 36         if s.Running {
 37                 if s.Paused {
 38                         return fmt.Sprintf("Up %s (Paused)", units.HumanDuration(time.Now().UTC().Sub(s.StartedAt)))
 39                 }
 40                 if s.Restarting {
 41                         return fmt.Sprintf("Restarting (%d) %s ago", s.ExitCode, units.HumanDuration(time.Now().UTC().Sub(s.FinishedAt)))
 42                 }
 43
 44                 return fmt.Sprintf("Up %s", units.HumanDuration(time.Now().UTC().Sub(s.StartedAt)))
 45         }
```
Seems it's on purpose to take `paused` as kind of sub state of `running`, just want to confirm is this really what we want? Because it's not user friendly.

**Comment by thaJeztah** [comment]
@duglin any thoughts on this? You recently made some changes to the "states"

**Comment by aanm** [comment]
IMO `Running` states a container that is or isn't stopped and paused a container that is or isn't paused.
I would see it has this:
```
____________________________________
Status    |  s.Running |  s.Paused |  
Running   |    true    |   false   |
Paused    |    true    |   true    |
Stopped   |    false   |   D.C.    |
------------------------------------
```
I think it makes sense, doesn't?

**Comment by HackToday** [comment]
hi @aanm  so for third-party developement (for contaner management)

If check container running or pause, we need to check both s.running and s.paused ?

What's the meaning for Paused container have S.running is true ?

**Comment by duglin** [comment]
I don't know the history here, but if I had to guess I'd say the `state` property not only tells you whether the container is running but it can also easily tell you whether its consuming resources - irrespective of whether its paused or not. If `state` were set to `false` when `paused` is `true` then the `state` field alone wouldn't be good enough to know if a container was more than just taking up disk space.  Imagine we had additional states, aside from `paused`, if we added more properties (as siblings to `paused`) then the logic to know if something was using resources would be ugly because we'd have to check multiple fields.

Of course, I would prefer if we didn't have a separate field for each sub-running-state (ie. `state` should be a string with possible values of 'running', 'paused', ....) but that's a different issue.

**Comment by HackToday** [comment]
hi @duglin  the history is 
for docker remote api, for paused container, the response get like this

{u'State': {u'Pid': 2688, u'OOMKilled': False, u'Paused': True, u'Running': True, u'FinishedAt': u'2015-05-29T00:20:08.168917295Z', 

As 3-rd party development, I think container status should be one specific status at one time,
whether it is running or pause or stopped.


So how do we check if container is paused or not ?

The paused container has running set true, same as running container, it is confused.

Do you mean we have to check both Running and Paused at the same time ?  I think it is not friendly API

**Comment by HackToday** [comment]
any updates for this issue ?

**Comment by duglin** [comment]
It does seem a bit odd that we force people to check multiple fields when using 'inspect' while when they use 'ps' it come back as one nice word.
We can easily add a new field to the `inspect` container json:
```
diff --git a/api/types/types.go b/api/types/types.go
index 70033d0..35ba59c 100644
--- a/api/types/types.go
+++ b/api/types/types.go
@@ -182,6 +182,7 @@ type ExecStartCheck struct {
 }
 
 type ContainerState struct {
+       Status     string
        Running    bool
        Paused     bool
        Restarting bool
diff --git a/daemon/inspect.go b/daemon/inspect.go
index c935c2b..59b90f6 100644
--- a/daemon/inspect.go
+++ b/daemon/inspect.go
@@ -64,6 +64,7 @@ func (daemon *Daemon) getInspectData(container *Container) (*t
        }
 
        containerState := &types.ContainerState{
+               Status:     container.State.StateString(),
                Running:    container.State.Running,
                Paused:     container.State.Paused,
                Restarting: container.State.Restarting,
```
to show the same string as `ps`.  But @LK4D4 @tiborvass what do you guys think?

**Comment by aanm** [comment]
@duglin I think that maybe doing a `ps` is not good for scripts? How does one can easily grep the state of the container with `ps`? A `status` message will be helpful and it doesn't hurt :-)

**Comment by tiborvass** [comment]
+1 to what @duglin said, although it feels weird to have all those booleans in the state API, should have been just a status string in the first place.

**Comment by duglin** [comment]
@tiborvass agreed - a single word instead of a list of bools would have been better.

**Comment by hqhq** [comment]
@duglin Sent a PR as you suggested #15023

**Comment by cpuguy83** [comment]
Not sure why this didn't close with #15023 was merged, but closing now.
Thanks!

**Comment by wenchma** [comment]
$ docker -v
Docker version 1.8.2, build 0a8c2e3

$ docker inspect a493de0ead7e
[
{
    "Id": "a493de0ead7e3e349389c7916b20434f370f9f5d25aa1ae63545bf4721715392",
    "Created": "2015-09-23T03:31:35.367669919Z",
    "Path": "/bin/bash",
    "Args": [],
    "State": {
        "Running": true,
        "Paused": true,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 13260,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2015-09-23T03:32:26.454832197Z",
        "FinishedAt": "2015-09-23T03:32:04.651769825Z"
    }

but not found the "status" string in the returned state, it is right ? or about the version ?
@duglin

**Comment by duglin** [comment]
@wenchma what version is your daemon?  Using master I see:
```
...
    "State": {
        "Status": "paused",
        "Running": true,
        "Paused": true,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 72565,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2015-09-24T17:44:56.998878781Z",
        "FinishedAt": "0001-01-01T00:00:00Z"
    },
...
```
