### ISSUE TITLE
FreeBSD build ci task

### ISSUE THREAD

**Issue by kvasdopil** [docker/docker#13592]
As FreeBSD support is being added, some commits start to break FreeBSD builds and soon we gonna to do something about that, perhaps a dedicated jenkins task and some build environment.

//cc @jfrazelle

**Comment by jfrazelle** [comment]
Ya I can add this

**Comment by jfrazelle** [comment]
Thanks for the ping :) should be cool

**Comment by jfrazelle** [comment]
this was done woohoo
