### ISSUE TITLE
Update our documentation regarding process interaction with container

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#13595]
![image](https://cloud.githubusercontent.com/assets/1347209/7888740/8df9e62e-05ef-11e5-8d55-c67425ba7039.png)

**Comment by yosifkit** [comment]
>  by design the docker container will exit when the process it is running exits, so if you do thing like a ‘ service x start’, you might start a new process somewhere else, but root process of the container (service x start) has already returned and the container stops
> -- relevant for users searching

https://github.com/docker-library/docs/pull/248 contiains an example where users miss the "daemon" mode of haproxy.

It might help to explain why daemonized processes (ie fork and parent process kills itself) fail to run in docker.

**Comment by dharmit** [comment]
#dibs 
If no one else is working on this, I would like to pick it up.

**Comment by moxiegirl** [comment]
go @dharmit go! :-D
