### ISSUE TITLE
Docker builder failed with 'text file busy'

### ISSUE THREAD

**Issue by pbecotte** [docker/docker#13594]
We build this container very frequenty.  Earlier today it failed a single time- I wanted to share the output I have in case it comes in handy.  This build run inside a docker-in-docker container (with a seperate daemon and binary).

```
13:16:37 [91m
13:16:37 [0m[91mmkdir /sftp
13:16:37 [0m[91mmv data/sshd_config /etc/ssh/sshd_config
13:16:37 [0m[91mdpkg-reconfigure openssh-server
13:16:38 [0m[91mdebconf: unable to initialize frontend: Dialog
13:16:38 [0m[91mdebconf: (TERM is not set, so the dialog frontend is not usable.)
13:16:38 [0m[91mdebconf: falling back to frontend: Readline
13:16:38 [0m[91mdebconf: unable to initialize frontend: Readline
13:16:38 [0m[91mdebconf: (This frontend requires a controlling tty.)
13:16:38 [0m[91mdebconf: falling back to frontend: Teletype
13:16:38 [0m[91mCreating SSH2 RSA key; this may take some time ...[0m[91m
13:16:38 [0m[91mCreating SSH2 DSA key; this may take some time ...[0m[91m
13:16:38 [0m[91mCreating SSH2 ECDSA key; this may take some time ...[0m[91m
13:16:39 [0m[91minvoke-rc.d: policy-rc.d denied execution of restart.
13:16:39 [0m[91m
13:16:39 [0m[91mgroupadd sftpusers
13:16:39 [0m[91m
13:16:39 [0m[91mmv data/users /users
13:16:39 [0m[91mmv setup-users.sh /setup-users.sh
13:16:39 [0m[91mchmod +x /setup-users.sh
13:16:39 [0m[91m/setup-users.sh
13:16:39 [0m[91msetup_sftp.sh: /setup-users.sh: /usr/bin/env: bad interpreter: Text file busy
13:16:39 [0mtime="2015-05-29T17:16:32Z" level=info msg="+job log(die, 465ef90ec2d788ea70f43bab0a07fba226f37c7653007e6e06d3dd9989b1980c, f3216c242a02)" 
13:16:39 time="2015-05-29T17:16:32Z" level=info msg="-job log(die, 465ef90ec2d788ea70f43bab0a07fba226f37c7653007e6e06d3dd9989b1980c, f3216c242a02) = OK (0)" 
13:16:39 time="2015-05-29T17:16:32Z" level=info msg="+job release_interface(465ef90ec2d788ea70f43bab0a07fba226f37c7653007e6e06d3dd9989b1980c)" 
13:16:39 time="2015-05-29T17:16:32Z" level=info msg="-job release_interface(465ef90ec2d788ea70f43bab0a07fba226f37c7653007e6e06d3dd9989b1980c) = OK (0)" 
13:16:39 The command [/bin/sh -c cd /setup_sftp; bash setup_sftp.sh] returned a non-zero code: 126
13:16:39 time="2015-05-29T17:16:32Z" level=info msg="-job build() = ERR (1)" 
13:16:39 time="2015-05-29T17:16:32Z" level=info msg="The command [/bin/sh -c cd /setup_sftp; bash setup_sftp.sh] returned a non-zero code: 126" 
```

The host runs on EC2 and has the following info...
```
Docker info: 
docker info
Containers: 23
Images: 352
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 398
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-53-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 3.859 GiB
Name: ip-172-31-31-7
ID: CSQS:JGPK:E43K:BFRQ:Y6P7:WMYE:PNIU:MBCD:PITD:JDYC:GSJI:JPPT
Username: pbecotte
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support
```

Docker version:
```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

Info from inside the dind container...

```
Containers: 0
Images: 0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-53-generic
Operating System: Ubuntu 14.04.2 LTS (containerized)
CPUs: 2
Total Memory: 3.859 GiB
Name: 080037324c29
ID: BQGE:ROW2:JXUM:TQNF:HKDW:TFJM:HOPK:LRQ6:GGJW:RKJS:VLMH:JZAV
WARNING: No swap limit support
```
```
Client version: 1.6.1
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 97cd073
OS/Arch (client): linux/amd64
INFO[0049] GET /v1.18/version                           
INFO[0049] +job version()                               
INFO[0049] -job version() = OK (0)                      
Server version: 1.6.1
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 97cd073
OS/Arch (server): linux/amd64
```

**Comment by cpuguy83** [comment]
Can you try with the dind's `/var/lib/docker` mapped to a volume (and as such not on top of aufs itself)?

**Comment by pbecotte** [comment]
My DinD image is the jpatezzo one that we vendored a couple weeks ago.  It has this line in the Dockerfile...

VOLUME /var/lib/docker

Is this sufficient or do you need me to specify something at runtime?

**Comment by dqminh** [comment]
`VOLUME /var/lib/docker` should be sufficient. aufs can't be nested.

I remember reading some reports about ETXTBUSY with aufs (found it https://github.com/docker/docker/issues/9547). I'm not sure what can we do here. It would be nice if there's a minimal Dockerfile to replicate this issue.

**Comment by pbecotte** [comment]
I haven't seen this happen again, so I doubt this ticket is going to be useful to you guys :)

**Comment by neurogenesis** [comment]
We've run into this occasionally too when launching containers. Most recently when a Ruby process is being launched:

```
% sudo docker logs 0cba60954591
bash: /app/bin/bundle: /usr/bin/env: bad interpreter: Text file busy
```

docker info:
```
Containers: 2
Images: 99
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 103
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-49-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 7.337 GiB
```

docker version:
```
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

**Comment by buley** [comment]
I see this error up to once a day while building on Docker Hub

It's the first line in all of my Dockerfiles. Perhaps it's a simple test case

  KernelVersion: 3.13.0-40-generic
  Os: linux
  BuildTime: Mon Oct 12 05:37:18 UTC 2015
  ApiVersion: 1.20
  Version: 1.8.3
  GitCommit: f4bf5c7
  Arch: amd64
  GoVersion: go1.4.2
  Step 0 : FROM centos:latest
   ---> e9fa5d3a0d0e
  Step 1 : MAINTAINER Taylor Buley (taylor.buley@mcnaughton.media)
   ---> Running in ba8585caa7cb
   ---> d74fbef54d36
  Removing intermediate container ba8585caa7cb
  Step 2 : RUN groupadd -g 1855 application   && /usr/sbin/useradd --uid 1855 --create-home --home-dir /usr/local/application --shell /bin/bash -g application application   && /usr/sbin/usermod -g application root   && chown -R application:application /usr/local/   && chown -R application:application /usr/src/   && chown -R application:application /usr/lib/   && chown -R application:application /usr/bin/   && chown -R root:application /var/log   && chown -R application:application /srv   && chmod 765 /srv   && chmod +s /srv
   ---> Running in e1f36818cfe4
  [91m/bin/sh: /usr/bin/chown: Text file busy
  [0mRemoving intermediate container e1f36818cfe4

**Comment by zdenekmaxa** [comment]
I am using Django inside a docker container and from some point on I see this
./manage.py: /usr/bin/env: bad interpreter: Text file busy
(running Django database migrations) very very frequently.

- sometime rerun docker built hepls
- there is no other docker container of the kind running
- most of the time I have to delete previous images and then the build proceeds
- it's very time consuming and annoying

I am running docker-engine 1.9.1-0~trusty on freshly updated Ubuntu 14.04 LTS

**Comment by sobolevn** [comment]
I have also suffering this issue: https://travis-ci.org/sobolevn/travis-test/jobs/137226459

**Comment by opsxcq** [comment]
The very same issue, but I can't reproduce it.
I just run the build again and it works.

**Comment by sobolevn** [comment]
Here's my workaround: https://github.com/sobolevn/git-secret/blob/master/Makefile#L24

I have added `sync;` command and it works now without a single problem.

**Comment by pporada-gl** [comment]
It turns out that this is a problem with AUFS. I run Ubuntu 16.04 and was using AUFS as the storage driver. I switched to overlay2 and everything is working as intended.
