### ISSUE TITLE
Volumes upgrade issue from 1.6 to 1.7

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#13608]
This is basically a place holder right now.  I'm currently seeing issues where I have 1.6 installed and then upgrade to 1.7 and the new container do not have volumes set up correctly.  I need to continue to investigate.

**Comment by cpuguy83** [comment]
There's a known issue with bind mounts that got fixed after rc1 was fixed.
Is this what you're talking about?

**Comment by thaJeztah** [comment]
@cpuguy83 I think you're referring to this one? https://github.com/docker/docker/pull/13563

@ibuildthecloud are you able to check if https://github.com/docker/docker/pull/13563 resolves what you're seeing?

**Comment by calavera** [comment]
Hey, no hard feelings, but I'm going to close this issue. Please, feel free to open any new ones with specific issues, but let's not keep around open issues "just in case".

Ping me with your specific issues about volume migrations and I'll try to fix them right away.

**Comment by ibuildthecloud** [comment]
@calavera My issue is not fixed on master.  I'll try to investigate tomorrow in depth.  Basically when upgrading from 1.6 to 1.7 some of the my containers seem to be missing mounts after the upgrade.  I'll try to narrow it down a bit.
