### ISSUE TITLE
Release Cadence not documented in this repo.

### ISSUE THREAD

**Issue by jogo** [docker/docker#13629]
The MAINTAINERS file says all decisions can be expressed as a pull request (https://github.com/docker/docker/blob/master/MAINTAINERS#L76). But I was unable to find any documentation explaining the release cadence (when is a minor as in semver's MAJOR.MINOR.PATCH). The closes thing I could find was https://github.com/docker/docker/blob/master/project/RELEASE-CHECKLIST.md which discusses what to do once you know you are working on making a release

**Comment by jfrazelle** [comment]
its every two months

**Comment by jogo** [comment]
Thanks, it would be nice to have this documented somewhere the docker repo.

**Comment by thaJeztah** [comment]
There's some initial work done to add a roadmap to the wiki; https://github.com/docker/docker/wiki, right now the information is quite limited, but the intention is to add more information once available (also for the longer term)

**Comment by cpuguy83** [comment]
Thanks, closing as this is documented in the wiki now.
