### ISSUE TITLE
Allowing ENTRYPOINT to run with privilege while restricting the end user

### ISSUE THREAD

**Issue by jakirkham** [docker/docker#13623]
A Dockerfile that I have written must patch some system files before the image can be used no matter what command is run (e.g. requires the hostname, number of cores, etc.) so I use `ENTRYPOINT`. I also would like to switch to a non-privileged user before the end user can interact with my image so I use `USER`.

However, it appears that I cannot still run commands as a super user in the entry point script. ( http://docs.docker.com/reference/builder/#user ) This means that I must either allow the end user some ability to use `sudo`, which is not desirable, or switch users in the entrypoint and hope that I have done a good enough job to avoid dropping out of some subshell into root.

What is the best way forward to allow the entry point to act with privilege without supplying that same privilege to the end user?

**Comment by cpuguy83** [comment]
Start the container with root, and drop privileges in your entrypoint script when ready.
For support issues, please see docker-user mailing list, #docker on IRC, or forums.docker.com

Closing since this is not a Docker issue..
Thanks!
