### ISSUE TITLE
ENH: Default `docker run`/`docker exec` arguments in CMD

### ISSUE THREAD

**Issue by jakirkham** [docker/docker#13624]
It would be nice if there was a way to enable default arguments for `docker run`/`docker exec` when specifying `CMD`. For example, when using `bash` one does something like this normally.

    CMD [ "/bin/bash" ]

To enable default TTY one might do something like the following. This could naturally be expanded to include other arguments like various redirects and forwardings.

    CMD [ "-t", "/bin/bash" ]

**Comment by jakirkham** [comment]
I did take a look through existing issues and didn't see anything like this. If I missed something that was similar apologies.

As this is an enhancement request and not a bug, I don't know that the rest of this message is pertinent. If I missed something, feel free to correct me.

**Comment by Munchery-JunyuWang** [comment]
This is a great feature and I wonder if anyone is working on this right now?

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.
