### ISSUE TITLE
`docker rmi -f` failing even after all using containers have been removed

### ISSUE THREAD

**Issue by stuartpb** [docker/docker#13625]
I was trying to remove an image that a few lingering containers appeared to still be using:

```
root@stuartup:~# docker rmi 77741d1dccee
Error response from daemon: Conflict, cannot delete 77741d1dccee because the container cd786ce1fddf is using it, use -f to force
```

Running `docker ps -a`, cd7 strangely had *nothing* in its status column, but I was able to `docker rm cd7` anyway.

```
root@stuartup:~# docker ps -a
CONTAINER ID        IMAGE                                                                     COMMAND                CREATED              STATUS                     PORTS                            NAMES
<... snip ...>
cd786ce1fddf        f56a915584d4c0ad30e4c328c49fc8d3a7b29b22c6413f9d985e5d6efdb6908b:latest   "/start web"           9 weeks ago                                     5000/tcp                         jovial_elion        
<... snip ...>
20d986f063db        f56a915584d4c0ad30e4c328c49fc8d3a7b29b22c6413f9d985e5d6efdb6908b:latest   "/start web"           3 months ago         Exited (143) 9 weeks ago                                    insane_goldstine    
<... snip ...>
root@stuartup:~# docker rm cd7
cd7
```

There was another container with the same image in its tree (listed above), but I was able to remove that one, too:

```
root@stuartup:~# docker rmi 77741d1dccee
Error response from daemon: Conflict, cannot delete 77741d1dccee because the container 20d986f063db is using it, use -f to force
root@stuartup:~# docker rm 20d
20d
```

However, those things being done, I **still** can't remove the image, now with no explanation:

```
root@stuartup:~# docker rmi 77741d1dccee
Error response from daemon: Conflict, 77741d1dccee wasn't deleted
root@stuartup:~# docker rmi -f 77741d1dccee
Error response from daemon: Conflict, 77741d1dccee wasn't deleted
```

## BUG REPORT INFORMATION

```
root@stuartup:~# docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
root@stuartup:~# docker info
Containers: 8
Images: 100
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 116
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-43-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 490 MiB
Name: stuartup.com
ID: UV2Z:H62P:XJGM:PK5Q:HJQS:ODMN:YNDI:A7WP:B7JP:JX5E:H3IF:WEQX
WARNING: No swap limit support
root@stuartup:~# uname -a
Linux stuartup.com 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by stuartpb** [comment]
Having updated/upgraded everything and rebooted, I'm still encountering this issue. This is on a DigitalOcean droplet.

## BUG REPORT INFORMATION

```
root@stuartup:~# docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
root@stuartup:~# docker info
Containers: 8
Images: 100
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 116
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-43-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 490 MiB
Name: stuartup.com
ID: UV2Z:H62P:XJGM:PK5Q:HJQS:ODMN:YNDI:A7WP:B7JP:JX5E:H3IF:WEQX
WARNING: No swap limit support
root@stuartup:~# uname -a
Linux stuartup.com 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by coolljt0725** [comment]
I think the image `77741d1dccee` is parent of other images, so you can't delete it directly.

**Comment by stuartpb** [comment]
No, it's a leaf:

```
root@stuartup:~# docker images --tree && echo EOF
Warning: '--tree' is deprecated, it will be removed soon. See usage.
├─39bb80489af7 Virtual Size: 125.2 MB
└─511136ea3c5a Virtual Size: 0 B
  └─ed53cd6f7f21 Virtual Size: 87.02 MB
    └─6370e261ca45 Virtual Size: 87.02 MB
      └─cd24398a9060 Virtual Size: 87.02 MB
        └─781098c022ba Virtual Size: 87.02 MB
          └─67f34fa63844 Virtual Size: 1.251 GB
            └─77741d1dccee Virtual Size: 1.339 GB
EOF
```

**Comment by coolljt0725** [comment]
But I see information from your post on https://github.com/docker/docker/issues/13625#issue-83253443, ti show the container user the image `f56a915584d4c0ad30e4c328c49fc8d3a7b29b22c6413f9d985e5d6efdb6908b:latest`, I think the `77741d1dccee ` should be the parent of `f56a915584d4c0ad30e4c328c49fc8d3a7b29b22c6413f9d985e5d6efdb6908b:latest`

**Comment by stuartpb** [comment]
It was, before I removed the `f56a915584d4c0ad30e4c328c49fc8d3a7b29b22c6413f9d985e5d6efdb6908b:latest` image (after removing container `20d986f063db`). `77741d1dccee` has no remaining child images.

**Comment by coolljt0725** [comment]
Then, it's really weird. if  `77741d1dccee` only has child `f56a915584d4c0ad30e4c328c49fc8d3a7b29b22c6413f9d985e5d6efdb6908b`, I think remove `f56a915584d4c0ad30e4c328c49fc8d3a7b29b22c6413f9d985e5d6efdb6908b` will automatically remove `77741d1dccee`

**Comment by jmakanjuola** [comment]
@stuartpb try the following commands below


### Removing Docker container & Images ####
---------------------------------------------

Step 1:
-------
docker images --no-trunc

Step 2:
-------
docker rm $(docker stop $(docker ps -q)) 

## Remove the containers that are using this image as:

Step 3:
-------
                   (e.g shykes/couchdb)
docker ps -a | grep CONTAINER_NAME | awk '{print $1}' | xargs docker rm

d621eef1d5ff
767b308f5114
ede7b132ad6a
de2d7d47b534
92318d131354
4022f09a9736

Step 4:
-------
docker ps -a -f "exited=-1"

### All running contianers, as opposed to meeting a specific criteria, can be removed as:

Step 5:
-------
docker rm $(docker ps -aq)

Step 6:
-------
docker rmi container_ID

## Retun output

Untagged: ubuntu:latest
Untagged: ubuntu:latest
Deleted: fd44297e2ddb050ec4fa9752b7a4e3a8439061991886e2091e7c1f007c906d75
Deleted: 41459f052977938b824dd011e1f2bec2cb4d133dfc7e1aa0e90f7c5d337ca9c4
Deleted: 6941bfcbbfca7f4f48becd38f2639157042b5cf9ab8c080f1d8b6d047380ecfc

#### Just like removing all containers, all images can be removed if you choose to remove all the images:

**Comment by thaJeztah** [comment]
Could this be related to https://github.com/docker/docker/issues/11414, which was resolved (again) in https://github.com/docker/docker/pull/13596?

@jmakanjuola are you able to reproduce this on the current master? You can download master binaries from https://master.dockerproject.com. Just make sure you *don't* run them on critical data, because they may contain bugs :)

**Comment by stuartpb** [comment]
> Could this be related to #11414, which was resolved (again) in #13596?

Unlikely, considering this image (and its child) was never tagged even once, let alone multiple times.

**Comment by jmakanjuola** [comment]
@stuartpb 

What was listed above is just a example of the what the output will look like. Okay.

**Comment by jmakanjuola** [comment]
@thaJeztah 

Thanks, this is from my docker personal notes. I've had this sample issue in the past and now I can just run docker rmi container_ID and it will remove it.

**Comment by cpuguy83** [comment]
Is this one still a problem? I know the rmi code has been touched a few times.
