### ISSUE TITLE
Why "docker stat " calculation must multiplied by CPU kernal count？

### ISSUE THREAD

**Issue by Liuyanglong** [docker/docker#13626]
When I read source code about  " docker stat", the current is : 
cpuPercent = (cpuDelta / systemDelta) * float64(len(v.CpuStats.CpuUsage.PercpuUsage)) 
https://github.com/docker/docker/blob/0d445685b8d628a938790e50517f3fb949b300e0/api/client/stats.go#L199

I do not understand why " * float64(len(v.CpuStats.CpuUsage.PercpuUsage))  ",  (cpuDelta / systemDelta) is Correct。

cpuDelta = float64(v.CpuStats.CpuUsage.TotalUsage - previousCPU)
systemDelta = float64(v.CpuStats.SystemUsage - previousSystem)

so total cpu delta / total system delta is correct , not need to multiplied by CPU kernal count.
Am I think right?

**Comment by coolljt0725** [comment]
I have some comments in https://github.com/docker/docker/pull/13627#issuecomment-107415691 about this

**Comment by thaJeztah** [comment]
From the comment linked by @coolljt0725;

> total time consumes of all cores, so (cpuDelta / systemDelta) is the average cpu usage of each core, so it need multiply the number of cpu cores to calculate the total cpu usage.

Agreed; for example, on a 4-core system, cpu usage can be anywhere between 0 and 400%, so it has to be multiplied by the number of cores.

I'm going to close this issue, because I don't think this change is correct, but feel free to comment if you think I closed this by mistake.

**Comment by Liuyanglong** [comment]
@thaJeztah  @coolljt0725 
 
We have different opinions on this question. 
I think the "stats CPU%" should be the average, but sourcecode says it should be total. 
I have a Pic about docker stats run on my server, one of the containers is larger than 100%, so if do not know how many cpu cores on my server, I will never know how much cpu idle left.
![qq 20150609102615](https://cloud.githubusercontent.com/assets/1468470/8049541/2036a512-0e93-11e5-84c4-cf2bbe917d7f.png)

**Comment by coolljt0725** [comment]
@Liuyanglong  We can get the cpu cores by using `docker info`, so I don't think this is a problem.

**Comment by Liuyanglong** [comment]
@coolljt0725 I do not think this is a problom， but it feel strange .
I want get a number show me the esource usage from '' docker stats", but now I must get the number from 'docker stats' and 'docker info'.For me, I care more about average.
