### ISSUE TITLE
Unexpected behaviour when mouting a volume containing a symbolic link

### ISSUE THREAD

**Issue by aliassmoller** [docker/docker#13632]
Hi

How to reproduce:
- Host command: echo 'host' > /tmp/a
- Spin up a empty/minimal docker image: docker run -it -v /home/test:/test some:image /bin/bash
- Container command: echo 'container' > /tmp/a
- Container command: ln -s /tmp/a /test/a
- Exit container command: Ctrl+p, Ctrl+q
- Host command: more /home/test/a

The result:
- The echo of the file /home/test/a returns 'host'

The expected result:
- I would expected that the file /home/test/a returns 'container'. 

Thoughts: 
- Seems counter-intuitive that a mounted symbolic link in a container is resolved to the host file system instead of begin resolved within the the file system of the the container only.
- This can produce unforeseen behaviors, as one might perform changes on a symbolic linked file in hope of changes in the container images, but in reality the changes are only performed on the host.

Is this an expected behavior? 

Running: Centos7, Docker 1.6.0/8aae715, Physical box

```
Containers: 6
Images: 110
Storage Driver: devicemapper
 Pool Name: docker-253:19-1191-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.721 GB
 Data Space Total: 107.4 GB
 Data Space Available: 2.27 GB
 Metadata Space Used: 5.64 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.142 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Kernel Version: 3.10.0-229.4.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 7.698 GiB
Name: 
ID: 
```
```
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 8aae715/1.6.0
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 8aae715/1.6.0
OS/Arch (server): linux/amd64
```
```
Linux alpha 3.10.0-229.4.2.el7.x86_64 #1 SMP Wed May 13 10:06:09 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by phemmer** [comment]
> Is this an expected behavior?

Yes it is.

Symbolic links are resolved at the time of their lookup, and in the context of their path at the time of lookup.

**Comment by aliassmoller** [comment]
Still seems a bit counter-intuitive that symbolic links can cross the host/container boundary. Can imagine a lot of nasty stuff and guess I might not be the only not knowing about this behavior.

**Comment by phemmer** [comment]
> Can imagine a lot of nasty stuff from this behavior

Such as?

I can't think of any. However it is very easy to abuse this behavior if it worked as you describe. For example, from the host I could do `ln -s /etc/shadow /home/test/shadow`, and get access to the `/etc/shadow` file within the container, where normally I would not have access to it.

**Comment by aliassmoller** [comment]
Lets say you setup SSH in a container, and you for some reason perform <code>ln -s /etc/ssh/sshd_config /root/config/sshd_config<code> in the container and mount volume with <code> -v /home/service:/root/config <code>. Then you will actually modify the host sshd_config instead of the container sshd_config. This specific use case requires <code>--privileged=true<code>. This use case may be bad.

Seems like symbolic links and docker containers must be used with care.

**Comment by thaJeztah** [comment]
> and mount volume with  `-v /home/service:/root/config`

In that case, the "dangerous" part is in mounting a host-directory in the container, **not** the symlink. By mounting a host-directory in a container, you are *explicitly* breaking the boundary between the container's filesystem and the host. You should *always* be careful doing that.

If you're worried about making changes to a bind-mounted directory, you can also mount with the `:ro` option to make it read-only.

**Comment by aliassmoller** [comment]
I will take care setting up the production containers. Lets close this. Thanks for feedback
