### ISSUE TITLE
Host architecture and operating system type ouput as part of 'info' api call

### ISSUE THREAD

**Issue by bpradipt** [docker/docker#13634]
With docker engine able to run on multiple architectures now, it will be useful to return the engine host architecture as part of the 'info' api. 

Additionally the 'Operating System:'  o/p returns the distribution type for Linux like 'Ubuntu 14.10' etc. and not really the operating system type eg. Linux, Windows etc.  Providing the operating system type explicitly as part of the 'Info' will be useful when managing a multi-arch/os  swarm cluster.

I would like to get some thoughts on the following options, based on which I'll submit the relevant PRs
1. Add a new 'Architecture' field to 'Info' struct to display the platform arch (runtime.GOARCH)
2. Add a new 'Operating System Type' field to 'Info' struct (runtime.GOOS)
3. Add a new 'Platform' field to 'Info' struct to display both Architecture and Operating System type.
4. Any other suggestions

Thanks

**Comment by chanwit** [comment]
It's a bit redundant to the current `operatingsystem` label, but I'd like to propose adding:
```
"platform": runtime.GOOS + "_" + runtime.GOARCH
```
to the info.

This will make Swarm to just use the `platform` label for selecting image without any addition parsing. This conforms the design proposed in docker/swarm#826.

**Comment by azurezk** [comment]
Is this issue still on?

**Comment by bubakazouba** [comment]
should we close this issue now?

**Comment by vdemeester** [comment]
@bubakazouba true :wink:
