### ISSUE TITLE
skip DockerSuite.TestDevicePermissions on lxc

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#13641]

**Comment by jmakanjuola** [comment]
@jfrazelle is this an issue?

**Comment by jfrazelle** [comment]
yes its an issue anyone can fix

On Mon, Jun 1, 2015 at 2:12 PM, Jubilee Makanjuola <notifications@github.com

**Comment by jmakanjuola** [comment]
Kool. I try to answer docker questions that are familiar and unfamiliar with. I am really excited about docker and its potential for it's impact on the industry. I have been learning all I can about docker and have been trying to actively contribute to the open source community, mainly through resolving issues on github.

**Comment by jfrazelle** [comment]
great thats awesome! thanks!

On Mon, Jun 1, 2015 at 2:42 PM, Jubilee Makanjuola <notifications@github.com

**Comment by runcom** [comment]
closed by https://github.com/docker/docker/issues/13656
