### ISSUE TITLE
Bash completion for files command such as 'cp'

### ISSUE THREAD

**Issue by ferdy-galema** [docker/docker#13646]
Would it nice if the `docker cp` command autocompleted files on the container's filesystem?

Is this feasible?

**Comment by vdemeester** [comment]
It's probably possibke but the cost would be high I think, and would depend on the fs backend used, etc..

**Comment by thaJeztah** [comment]
I could've sworn I commented on this. Either forgot to send, or there's a duplicate. I'll check when I'm on my computer

**Comment by ferdy-galema** [comment]
I have opened a related issue at the same time.

**Comment by thaJeztah** [comment]
Ah! that's it; here https://github.com/docker/docker/issues/13647#issuecomment-108610580

I think the same applies here; as @vdemeester explained, *if* possible at all, it'll be quite heavy, and will depend on the container.

So, while I agree this would be a very nice feature, I don't think it's feasible, so I'm going to close this issue.

Thanks for the nice thought though!
