### ISSUE TITLE
Issues installing Docker in Windows 8.1 (Boot2Docker v1.6.2)

### ISSUE THREAD

**Issue by valeriemaite** [docker/docker#13655]
I'm trying to install Docker for Windows installer (Boot2Docker) and even though I'm following the instructions set by Docker I'm getting an issue.  After I download the executable (docker-install.exe v 1.6.2), I double-click the icon in the desktop and the cmd opens but after it says "loading" it closes down and I can't finish the set up process.  I then try to open the cmd window and try to execute boot2docker up or boot2docker -v up and I'm getting errors.  I tried to open the Virtual Box and I also got errors.  I've attached the .  Any idea what I could be missing?  Thanks!
![cmderror](https://cloud.githubusercontent.com/assets/4131500/7927480/3899165a-08a6-11e5-9260-800de3b112c2.JPG)
![virtualboxerror](https://cloud.githubusercontent.com/assets/4131500/7927483/4252e91e-08a6-11e5-9b87-1cf9b10568c9.JPG)

**Comment by unclejack** [comment]
@valeriemaite You need to enable VT-x in your EFI firmware/BIOS. Without support for virtualization support, there's no way to start the virtual machine.

Please make sure your hardware supports VT-x and look for steps on how to enable VT-x on your machine.

This isn't a Docker, a boot2docker bug, Windows bug or a Linux kernel bug.
