### ISSUE TITLE
Prevent git remote from escaping build context

### ISSUE THREAD

**Issue by ewindisch** [docker/docker#13653]
Build context may escape git root when building from git remote. Reported by @tonistiigi. Does not affect any releases, only master. Introduced in PR#12769 (#7071)

Needed for 1.7.0 milestone.

**Comment by ewindisch** [comment]
@jfrazelle lets make sure we get a fix merged into PR#13528

**Comment by jfrazelle** [comment]
yep its there

**Comment by thaJeztah** [comment]
@ewindisch there was already a PR created by @tonistiigi, which is merged and (I think) cherry-picked. See https://github.com/docker/docker/pull/13639.

I'm going to close this issue because it's been resolved by https://github.com/docker/docker/pull/13639. Thanks for the reminder though!
