### ISSUE TITLE
Resource options are missing from Config JSON

### ISSUE THREAD

**Issue by aanand** [docker/docker#13663]
As of https://github.com/docker/docker/pull/10298, resource options (`Cpuset`, `Memory` etc) are no longer in the `Config` section of a container's JSON, but in `HostConfig`. Unfortunately, that appears to be the case across all API versions, which I believe is a regression.

Test script:

```python
from docker.client import Client
from docker.utils import kwargs_from_env

kwargs = kwargs_from_env()
kwargs['tls'].assert_hostname = False

for minor_version in range(1, 19):
    version = '{}.{}'.format(1, minor_version)
    client = Client(version=version, **kwargs)
    container = client.create_container('busybox', 'true', cpu_shares=1)
    container_info = client.inspect_container(container)

    print '{}: CpuShares = {}'.format(version, container_info['Config'].get('CpuShares'))
```

Output when run against a Docker 1.6.2 daemon:

```
$ python test.py
1.1: CpuShares = 1
1.2: CpuShares = 1
1.3: CpuShares = 1
1.4: CpuShares = 1
1.5: CpuShares = 1
1.6: CpuShares = 1
1.7: CpuShares = 1
1.8: CpuShares = 1
1.9: CpuShares = 1
1.10: CpuShares = 1
1.11: CpuShares = 1
1.12: CpuShares = 1
1.13: CpuShares = 1
1.14: CpuShares = 1
1.15: CpuShares = 1
1.16: CpuShares = 1
1.17: CpuShares = 1
1.18: CpuShares = 1
```

Output when run against a Docker 1.7.0 RC1 daemon:

```
$ python test.py
1.1: CpuShares = None
1.2: CpuShares = None
1.3: CpuShares = None
1.4: CpuShares = None
1.5: CpuShares = None
1.6: CpuShares = None
1.7: CpuShares = None
1.8: CpuShares = None
1.9: CpuShares = None
1.10: CpuShares = None
1.11: CpuShares = None
1.12: CpuShares = None
1.13: CpuShares = None
1.14: CpuShares = None
1.15: CpuShares = None
1.16: CpuShares = None
1.17: CpuShares = None
1.18: CpuShares = None
```

**Comment by runcom** [comment]
@aanand thanks, taking care of this

**Comment by bfirsh** [comment]
It's worth noting that this is affecting both Swarm and [Compose](https://github.com/docker/compose/pull/1497).

**Comment by runcom** [comment]
https://github.com/docker/docker/commit/767df67e3149b83255db0809f6543b449a4f652e#diff-ae476143d40e21ac0918630f7365ed3c removed these infos

**Comment by runcom** [comment]
ping @calavera

**Comment by calavera** [comment]
As far as I know those options were deprecated from `Config` some time ago. Wouldn't it be better to move those project that still use the old config to use the new host config rather than adding the fields back as `deprecated` again?

**Comment by thaJeztah** [comment]
The old API versions shouldn't change, though? So I think this should be made conditional, based on the API version

**Comment by calavera** [comment]
agreed

**Comment by icecrime** [comment]
Yep I agree. Those fields were rightfully moved to `HostConfig`, but breaking old API versions is a problem.

@runcom Are you taking this? Thanks!

**Comment by runcom** [comment]
Yup @icecrime
