### ISSUE TITLE
Each docker logs command creates new LoggingDriver instance

### ISSUE THREAD

**Issue by LK4D4** [docker/docker#13676]
There should be one instance.
ping @ahmetalpbalkan

**Comment by LK4D4** [comment]
I propose maybe create it on `Create` and `load`.

**Comment by ahmetalpbalkan** [comment]
@LK4D4 is this some behavior I recently introduced or has been the case? What comes to my mind is when and where to garbage collect if we're going to create only one per container and reuse. As far as I remember, we've been creating one logging driver (for reading) for each `docker logs` request.

**Comment by LK4D4** [comment]
@ahmetalpbalkan There was no logging driver in docker logs before your refactoring.

**Comment by ahmetalpbalkan** [comment]
Oh I see. I'm not really familiar with the logs reading code. However the logging drivers nearly don't store any streams or readers. So does it have perf impact to have a logging driver per request? As far as I can tell, `AttachWithLogs` method used to open the logging file through `c.ReadLog("stdout")` (one per request) and now it does ` c.getLogger().GetReader()` (again, one per request). I can't see what sort of problem we have here.

I don't know how can I fix this, please feel free to jump in @LK4D4 as you're the SME and probably can get it done quicker.

**Comment by LK4D4** [comment]
@ahmetalpbalkan Yeah, just wanted your opinion, I'm storing pubsub object in logger for streaming for refactoring.

**Comment by LK4D4** [comment]
@ahmetalpbalkan #12800 if you interested, I'm trying to rewrite it to add something like `Follow() (Follower, error)` to interface.

**Comment by thaJeztah** [comment]
@LK4D4 so #12800 closes this?

**Comment by LK4D4** [comment]
@thaJeztah I'm not sure, it's not even close to real master code. I'll update if I finish.

**Comment by thaJeztah** [comment]
@LK4D4 no problem, just checking :)

**Comment by cpuguy83** [comment]
Closing since this is no longer the case after the log reader refactor.
A new instance is only created if one doesn't already exist.
