### ISSUE TITLE
Docker images cost quite a long time 

### ISSUE THREAD

**Issue by HuKeping** [docker/docker#13688]
Hi there,

Do you find commands like `docker images` will cost more and more time when the number of image increase?

Recently I'll take more than 20s to wait for the response, is there anyway I can speed it up, thanks.

```
$ docker info
Containers: 372
Images: 10309
Storage Driver: btrfs
Execution Driver: native-0.2
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04 LTS
CPUs: 160
Total Memory: 1.968 TiB
Name: docker
ID: WTSZ:44VG:ZGZP:QIA4:EIHE:3HHU:RVWL:EIMR:EO3K:EOLX:L3ZV:OPA7
Debug mode (server): true
Debug mode (client): false
Fds: 106
Goroutines: 159
EventsListeners: 0
Init Path: /usr/bin/docker.io
Docker Root Dir: /docker/docker_aufs
WARNING: No swap limit support
```

```
$ docker version
Client version: 1.5.0-dev
Client API version: 1.18
Go version (client): go1.4
Git commit (client): 862c6d9
OS/Arch (client): linux/amd64
Server version: 1.5.0-dev
Server API version: 1.18
Go version (server): go1.4
Git commit (server): 862c6d9
```

```
$ uname -a
Linux docker 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by HuKeping** [comment]
Words fail me to you @GordonTheTurtle

**Comment by unclejack** [comment]
@HuKeping The time it takes to show the images using `docker images` depends on the number of images and on the speed of your HDD. A slow drive means that it'll take a lot more time to load the images from the drive.

Kernel `3.13.0-24-generic` is outdated and unsafe to be used because it has known data corruption bugs. Please make sure to update your system using `apt-get update && apt-get dist-upgrade` and reboot.

**Comment by HuKeping** [comment]
@unclejack Thanks for reply but still have a little question, do you think the key factor is the number of images? I have more than 10,000 images on my server

**Comment by unclejack** [comment]
@HuKeping The number of images has a lot to do with this, but it's the slow HDD IO that makes this slow. Listing images when you only have 10 images on a slow HDD is going to be about as fast as listing those same 10 images on a fast HDD. 10,000 images will be listed slower on the slow HDD.
