### ISSUE TITLE
command line completion should be aware of 'rename'

### ISSUE THREAD

**Issue by VynceMontgomery** [docker/docker#13687]
Both the existence of the command, and the fact that the first argument should be an existing container name. (tested on v1.5 in bash) 

(rename feature requested in #3036, added in pull request #8570)

**Comment by VynceMontgomery** [comment]
**docker version**
```
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```
**docker info**
```
Containers: 3
Images: 37
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 43
Execution Driver: native-0.2
Kernel Version: 3.13.0-46-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 1.95 GiB
Name: cms-nodex-stage-001
ID: JYXC:FAFO:RB5Y:2KCQ:6HK6:BLWA:G45T:S24I:VGRG:YNT6:SZPT:5GMJ
Username: destinationsc
Registry: [https://index.docker.io/v1/]
```
**uname -a**
```
Linux cms-nodex-stage-001 3.13.0-46-generic #79-Ubuntu SMP Tue Mar 10 20:06:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
**other**
Rackspace virtual machine

**Reproduction steps:**
from a command line: 
```
docker r[TAB][TAB]
```
shows ```restart  rm       rmi      run``` 
but not ```rename```

```
docker rename [TAB][TAB]
```
does not list containers.

It would be great if it completed as the other commands do.

**Comment by coolljt0725** [comment]
#10883 has add `docker rename` to bash completion

**Comment by thaJeztah** [comment]
Yes, this has already been solved. The completion scripts can be found here; https://github.com/docker/docker/tree/master/contrib/completion

I'm going to close this issue, because this has been resolved in https://github.com/docker/docker/pull/10883
