### ISSUE TITLE
Docker 1.7: empty labels map missing in /containers/json

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#13691]
`/containers/json` returns a field `Labels` that has the labels of the container.  In 1.7 if the labels map is empty it is not sent.  The API should return `{}`, but instead the field is missing.  Below is the out of running

    docker run ubuntu
    docker run -l a=b ubuntu

```json
{
    "Id": "c48aef9ecfa1bebbd90286f17396f681a7859f650f1e3d7d4d2252f96f9c9300",
    "Names": [
      "/prickly_wilson"
    ],
    "Image": "ubuntu",
    "Command": "/bin/bash",
    "Created": 1433309853,
    "Labels": {
      "a": "b"
    },
    "Status": "Exited (0) 2 minutes ago"
  },
  {
    "Id": "3a140dee6f844d3eba5ebef04fd14b277f345424037e1fb50f490232bd8c47ee",
    "Names": [
      "/prickly_pasteur"
    ],
    "Image": "ubuntu",
    "Command": "/bin/bash",
    "Created": 1433309830,
    "Status": "Exited (0) 3 minutes ago"
  }
```

Stuff:
```
docker version; docker info
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.7.0-dev
Server API version: 1.20
Go version (server): go1.4.2
Git commit (server): 63823cd
OS/Arch (server): linux/amd64
Containers: 6
Images: 884
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 4.0.1-040001-generic
Operating System: Ubuntu 14.10
CPUs: 4
Total Memory: 7.504 GiB
Name: inotmac
ID: FPSO:Z7SO:BZJ3:IXH4:DNKV:UPZQ:KLP2:IRXW:5CBY:PBDM:HAKO:UOC7
Debug mode (server): true
Debug mode (client): false
Fds: 42
Goroutines: 59
System Time: Tue Jun  2 23:02:12 MST 2015
EventsListeners: 23
Init Path: /home/darren/src/docker/bundles/latest/binary/docker
Docker Root Dir: /var/lib/docker
Http Proxy: 
Https Proxy: 
No Proxy: 
Username: ibuildthecloud
Registry: [https://index.docker.io/v1/]

```

**Comment by ibuildthecloud** [comment]
@GordonTheTurtle you haunt my dreams

**Comment by runcom** [comment]
Looking (thanks @ibuildthecloud)

**Comment by ibuildthecloud** [comment]
@runcom The same applies to `"Ports": []`.  Should file a separate issue, or is this related and something generic like "empty" fields are getting dropped?

**Comment by runcom** [comment]
@ibuildthecloud let's leave just this one opened. It's weird because look at this comment https://github.com/docker/docker/pull/13675#issuecomment-108113556
Output shows Labels as empty curly braces

I just only noticed your client is 1.6.2 and server is 1.7 dev so maybe something with this

**Comment by ibuildthecloud** [comment]
@runcom Inspect output is fine.  This is the output for `docker ps` essentially.  So listing all containers, not just getting one.

Your right my client and server don't match, but the issue is with talking to the API.  So I was using docker-py, but validate by just using curl against the unix socket.  So client doesn't make a difference here.

**Comment by runcom** [comment]
@ibuildthecloud gotcha thanks for the extra info

**Comment by thaJeztah** [comment]
Added this to the milestone, because this sounds like a regression

**Comment by ibuildthecloud** [comment]
@thaJeztah @runcom This bug is blocking me from really fully testing Docker 1.7.  Too much of my stuff fails because of this so I can't run a full regression suite on 1.7.

**Comment by runcom** [comment]
I'm on this @ibuildthecloud (do not desperate)

**Comment by thaJeztah** [comment]
Let me include the release captain(s) here, just so it's not overlooked. Afaik there were plans to push 1.7.0-rc2 out today, not sure this will make it in time, so a rc3 may be needed.

ping @vieux @jfrazelle for regression in 1.7

**Comment by runcom** [comment]
This bug is really simple I think, from 1.6+ we now have this struct from ps output -> https://github.com/docker/docker/blob/master/api/types/types.go#L112

I don't know why `json:",omitempty"` is there
but I'm making a PR @ibuildthecloud @thaJeztah :)

**Comment by jfrazelle** [comment]
I haven't made the RC yet so there's time

**Comment by thaJeztah** [comment]
@runcom good to hear. Fingers crossed! Make sure to ping Jess on the pull-request so that it can be cherry-picked for RC2

**Comment by thaJeztah** [comment]
Hmf GitHub cache :)
