### ISSUE TITLE
autofs does not work in containers

### ISSUE THREAD

**Issue by ksalman** [docker/docker#13700]
I am trying to get autofs to work inside containers and it does not work. Specifically, I need indirect mapping to work, though I can't even get direct mapping to work. There are times that it works, but most of the times it just hangs. 

docker version:
```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```
docker info:
```
Containers: 24
Images: 23
Storage Driver: aufs
 Root Dir: /work/docker/aufs
 Backing Filesystem: extfs
 Dirs: 73
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04 LTS
CPUs: 32
Total Memory: 125.8 GiB
Name: amberjack
ID: ZMR6:XRED:SO7Q:URGP:I3PK:4AAH:5R4J:VDQZ:RR5P:NO3Q:PVK4:DPZQ
WARNING: No swap limit support
```
uname -a:
```
Linux amberjack 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
Environmental details:
This host is Ubuntu 14.04 and the container is Scientific Linux 6.1.

How reproducible:
It's very consistent

Steps to reproduce:
I created an image with this Dockerfile
```
FROM sl6.1-64:rockmachine
COPY start-services.sh /start-services.sh
RUN chmod a+x /start-services.sh
ENTRYPOINT ["/start-services.sh"]
```
There's nothing special in sl6.1-64:rockmachine - it's just the base Scientific Linux 6.1 image with a bunch of packages already installed

start-services.sh looks like this
```
#!/bin/sh

# Start services
service rpcidmapd start
service rpcbind start
service nfslock start
service autofs start

# autofs does not work until killed and started again
kill -9 `pgrep -f automount`
service autofs start

/usr/sbin/sshd -D
```
Incidentally, I noticed that I need kill and restart autofs service for the rare times it does work.

Build image:
```
sudo docker build -t ksalman:test .
```
Since I am using indirect maps, there's not much in auto.master
```
[root@3029cb0205ae ~]# cat /etc/auto.master
+auto.master
/net -hosts -dev
```
The container was started with in privileged mode:
```
sudo docker run --privileged --expose=22 -d -P -v /etc:/shared/etc:ro --name ksalman ksalman:test
```
Actual results:
I can browse the parent directories but nothing after that
```
[root@3029cb0205ae ~]# ls /net/lurker/datapool/
englab  repository  scratch  winpe
[root@3029cb0205ae ~]# ls /net/lurker/datapool/repository
^Cls: cannot access /net/lurker/datapool/repository: Interrupted system call
```
It just hangs here and I ctrl-c out.

Expected results:
```
ksalman@latite ~ $ ls /net/lurker/datapool/repository
add-rpms  centos-archive-rsync.txt  epel            rhel                  sl                                 ubuntu
aptly     centos-rsync.txt          epel-rsync.txt  opencsw  rpmforge              sysdump-swash-20141217-080344.tgz  VNC-5.2.2-Windows.exe
centos    debian                    fedora          ovas     scientific-rsync.txt  treasury-isos                      windows
```

**Comment by vagifverdi** [comment]
autofs in containers works for me on ubuntu 15.04 host, but not on ubuntu 14.04 host. Perhaps it has to do with kernell support?

**Comment by thaJeztah** [comment]
Related to https://github.com/docker/docker/issues/13376#issuecomment-119200971?

**Comment by JamesKyburz** [comment]
Any news on this? We're having issues with autofs using docker 1.9.0.

**Comment by vagifverdi** [comment]
@JamesKyburz: Whats your linux version? It is working for me on ubuntu 15.04 and later. But not on ubuntu 14.04.

**Comment by rhvgoyal** [comment]
Have not gone through the whole thread but I think with volume propagation patches in 1.10, it should be possible to access autofs mounts inside container. Say autofs volumes are under /mnt. Then following should work.

Make sure source mount dir is shared.
$ mount --make-shared /mnt

Launch container with slave volume

$ docker run -ti -v /mnt:/volumes:slave fedora bash

Now when container steps into /volumes/foo then /mnt/foo should get mounted and be visible inside container.

**Comment by cyberjoac** [comment]
+1 Any news on that ? 
Cannot see my mounts using automount in RHEL 7.
mount DOES work so I'm very surprised why it does not work with automount..
Anyone had success with it ? Thanks
