### ISSUE TITLE
ENH: Testing Docker Entrypoints during Docker build

### ISSUE THREAD

**Issue by jakirkham** [docker/docker#13701]
During the `docker build` phase we can effectively implement tests in docker by having `sh` scripts that use `set -/+e` sections. Thus, we can fail our own builds if these scripts don't pass. Of course, we can use more sophisticated testing strategies, as well.

However, I am still unclear on how we can test `ENTRYPOINT` and `CMD` as the container is not run after building. It seems that a nice feature for testing would be to tack on a command like this `docker run -it <image> /bin/sh -e -c "exit 0"` at the end of the Dockerfile or at least provide us a way to specify such a run command to validate the `ENTRYPOINT` (e.g. `TEST_ENTRYPOINT`). That way the container can be started in some minimal configuration and terminated with an indicative error code. Validating `CMD` could be tricky. I say this with a mind towards automated builds on Docker Hub where the build could be errored before providing an unusable container.

If this already exists in some fashion, I apologize for asking the obvious and ask that you kindly point me where to look. If not, I would really appreciate some thought as to how this could be implemented.

**Comment by jakirkham** [comment]
Tried searching through issues here and Docker Hub forum. Didn't see anything relevant. Also, not a bug, but a feature request so ignoring the rest.

**Comment by cpuguy83** [comment]
You can just run the image manually to test the entrypoint/cmd.
However running with `/bin/sh -e -c "exit 0"` would be frivolous as this is replacing the cmd.
