### ISSUE TITLE
Bug report: docker rebuilds layer when doing COPY directory even if directory is not changed.

### ISSUE THREAD

**Issue by sochka** [docker/docker#13717]
```
[17:05:23] ~> docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
[17:05:55] ~> docker info
Containers: 3
Images: 72
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 78
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.19.0-18-generic
Operating System: Ubuntu 15.04
CPUs: 1
Total Memory: 1.954 GiB
Name: stepler
ID: RCGA:EIQL:AAXU:V32B:ES4J:KSVX:RLHO:BJMC:HBA3:SH4B:54S4:VIGH
WARNING: No swap limit support
[17:06:39] ~> uname -a
Linux stepler 3.19.0-18-generic #18-Ubuntu SMP Tue May 19 18:31:35 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

```

Environment: Microsoft Azure (ubuntu 14.04) and a VM at some private hosting (ubuntu 15.04). Docker is managed using `Dokku-alt`.

Steps (reproducible on my servers powered by Dokku-alt but not locally using `docker` cli tool):
1. Build image, using `git push production` (project is here https://github.com/kpi-wdc/wdc)
2. Change any file except package.json and files inside proc directory. (for example .dockerignore).
3. Redeploy app

Expected: `COPY proc /tmp/proc ` this line shouldn't trigger a rebuild at this point (too early). 
Result: build is triggered even though nothing in proc directory was changed.

Hi, seems like docker doesn't support caching directories.

In my `Dockerfile` I have a line `COPY proc /tmp/proc` and even if I do not change anything inside proc directory, at this point docker tells `removing intermediate container` (why!?) and rebuilds everything that follows (as expected). Copying single files works ok and detects that the same layer already exists (like in `COPY package.json /tmp/package.json` on a previous step of my `Dockerfile`). Dockerfile itself:
```
FROM iojs:2.1
MAINTAINER Oleksandr Sochka ""

# Set production settings
ENV PRODUCTION true
ENV NPM_CONFIG_PRODUCTION true

# Cache npm packages
VOLUME /root/.npm

# Don't even run `npm install` if `package.json` and `proc` weren't changed.
COPY package.json /tmp/package.json
COPY proc /tmp/proc # AT THIS POINT EVERYTHING GETS REBUILD even if I change just one file *not* in this directory.
RUN cd /tmp && npm install

RUN mkdir -p /app
RUN cp -a /tmp/node_modules /app/
COPY . /app

WORKDIR /app
RUN npm run-script postinstall # for some reason this is not called automatically in docker

ENV PORT 80
EXPOSE 80
```

Is this a bug or expected? Or maybe I'm doing something wrong.

**Comment by duglin** [comment]
Hmm,
```
FROM busybox
COPY dir /tmp/dir
RUN ls -l /tmp/dir
```
seems to work for me.  Perhaps you could try to reduce your testcases down and then share the specific files you have in your dir that's causing the issue?

**Comment by sochka** [comment]
So I edited the description as asked adding some additional info. @duglin I'm not quite sure how to reduce it - just randomly removing other absolutely irrelated files or files inside proc directory?

**Comment by duglin** [comment]
yeah, remove all extra noise from the Dockerfile (even if its just becomes FROM + COPY) and if you can reduce it down to just one file in the dir that would be good.

**Comment by sochka** [comment]
Uhmm, strange. I tried this locally and detected that everything works as expected. But not on the server... Maybe this is important, I use `dokku-alt` as a custom PaaS solution and deploy app using `git push my-server`. Still, can't figure out how could this result in docker not being able to detect directory having the same content.

**Comment by duglin** [comment]
Ah, be careful, if your dir is downloaded git via (or updated by it) and the timestamp changes then Docker considered that a modified file.

**Comment by duglin** [comment]
There's #12031 in the works. If that is indeed your issue.

**Comment by sochka** [comment]
Probably it is. But I don't really touch this directory at all. Why would timestamp change?

**Comment by duglin** [comment]
dunno, do you see its mtime changing between your two builds?

**Comment by tianon** [comment]
Just "git pull" can change the mtime on files in ".git" (even if nothing
has actually changed).

I'd recommend adding ".git" to your ".dockerignore" file if it's not
necessary for use inside your container.

**Comment by sochka** [comment]
Nope, mtime is not changed locally.

```
[00:48:02] ~/Projects/wdc> stat proc
  File: ‘proc’
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: 801h/2049d      Inode: 6426226     Links: 6
Access: (0755/drwxr-xr-x)  Uid: ( 1000/oleksandr)   Gid: ( 1000/oleksandr)
Access: 2015-06-03 18:10:56.877703059 +0300
Modify: 2015-05-26 23:31:59.610579731 +0300
Change: 2015-05-26 23:31:59.610579731 +0300
 Birth: -
[00:48:21] ~/Projects/wdc> stat proc/*
  File: ‘proc/avg’
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: 801h/2049d      Inode: 6426799     Links: 2
Access: (0755/drwxr-xr-x)  Uid: ( 1000/oleksandr)   Gid: ( 1000/oleksandr)
Access: 2015-06-03 18:10:56.877703059 +0300
Modify: 2015-04-27 20:50:54.848995983 +0300
Change: 2015-04-27 20:50:54.848995983 +0300
 Birth: -
  File: ‘proc/multiplier’
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: 801h/2049d      Inode: 6427054     Links: 2
Access: (0755/drwxr-xr-x)  Uid: ( 1000/oleksandr)   Gid: ( 1000/oleksandr)
Access: 2015-06-03 18:10:56.877703059 +0300
Modify: 2015-04-27 20:50:54.848995983 +0300
Change: 2015-04-27 20:50:54.848995983 +0300
 Birth: -
  File: ‘proc/update’
  Size: 4096            Blocks: 8          IO Block: 4096   directory                                                                 
Device: 801h/2049d      Inode: 6427207     Links: 2                                                                                   
Access: (0755/drwxr-xr-x)  Uid: ( 1000/oleksandr)   Gid: ( 1000/oleksandr)                                                            
Access: 2015-06-03 18:10:56.877703059 +0300                                                                                           
Modify: 2015-04-27 20:50:54.848995983 +0300                                                                                           
Change: 2015-04-27 20:50:54.848995983 +0300                                                                                           
 Birth: -                                                                                                                             
  File: ‘proc/xlsx2json’                                                                                                              
  Size: 4096            Blocks: 8          IO Block: 4096   directory                                                                 
Device: 801h/2049d      Inode: 6427226     Links: 2                                                                                   
Access: (0755/drwxr-xr-x)  Uid: ( 1000/oleksandr)   Gid: ( 1000/oleksandr)                                                            
Access: 2015-06-03 18:10:56.877703059 +0300                                                                                           
Modify: 2015-05-26 23:31:59.414579754 +0300                                                                                           
Change: 2015-05-26 23:31:59.414579754 +0300                                                                                           
 Birth: -                                                                           
```

**Comment by sochka** [comment]
@tianon , it's already there.

**Comment by duglin** [comment]
back to reducing it down then...

**Comment by sochka** [comment]
Probably not the best idea on real server. Maybe a bit later when I have time to setup dokku-alt and other required stuff locally.

**Comment by thaJeztah** [comment]
@sochka I'm going to close this issue for now, because at this moment we don't have enough information to work on (it could still be an mtime issue).

Please ping me when you have had the time to narrow down the problem and I'll reopen. Also, be sure to subscribe to https://github.com/docker/docker/pull/12031 to check progress on that PR.
