### ISSUE TITLE
1.7: docker ps does not append ":latest" if not already there

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#13723]
If you send an Image in the Config that does not have a tag, in 1.6 `docker ps` would append `:latest`, in 1.7 that does not happen anymore.

In Docker 1.6

```
docker run -d ibuildthecloud/helloworld
docker ps
CONTAINER ID        IMAGE                              COMMAND             CREATED             STATUS              PORTS               NAMES
f2da6a56f956        ibuildthecloud/helloworld:latest   "/sleep.sh"         34 seconds ago      Up 33 seconds       8080/tcp            serene_ptolemy      
```

In 1.7
```
docker run -d ibuildthecloud/helloworld
docker ps
CONTAINER ID        IMAGE                       COMMAND             CREATED             STATUS              PORTS               NAMES
b6ecdc4af377        ibuildthecloud/helloworld   "/sleep.sh"         9 seconds ago       Up 8 seconds                            focused_sinoussi    
```

**Comment by hqhq** [comment]
After some digging, found out:
 - It's broken by #11895
 - There is a similar issue #12595
 - and a related PR #12918 

But seems #12918 didn't fix this problem.

**Comment by runcom** [comment]
@hqhq care to comment on #12918 about the correct approach to fixing this? :)

**Comment by runcom** [comment]
ok you did it https://github.com/docker/docker/pull/12918#discussion_r31716346 thanks @hqhq

**Comment by tianon** [comment]
This sounds to me like an intentional feature of #11895, not a bug. :innocent:

**Comment by ibuildthecloud** [comment]
Is this a bug or not?  Just need to know.  This breaks some code I have so I need to know if I should change it to be compatible with 1.7.

**Comment by ibuildthecloud** [comment]
I'm cool with this change in 1.7, closing.
