### ISSUE TITLE
Step 6 in Tutorial marks step as correct when incorrect

### ISSUE THREAD

**Issue by paladique** [docker/docker#13729]
Was running through the tutorial and accidentally did:
`docker run learn/ping www.google.com`

instead of
`docker run learn/ping ping www.google.com` (as the answer states)

My mistake validated as a incorrect answer in the emulator with a popup claiming it was correct.

![dockerissue](https://cloud.githubusercontent.com/assets/1414307/7973411/ff3fcb82-0a22-11e5-90ce-eeb4faefaa8a.png)

**Comment by thaJeztah** [comment]
Oh! Thanks for having the courage to report this! You realise we'll now have to invalidate your exam, right? :smile:

Seriously, good find, and thanks for reporting this!

**Comment by jfrazelle** [comment]
this is not the right place for this, please email support@docker.com
