### ISSUE TITLE
1.7: `docker ps` status for created is "Created" and not ""

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#13724]
In docker 1.6 the status for a Created container is "".  In 1.7 it is "Created".  While Created is much nicer to display in 1.19, for strict conformance, 1.18 should return "" as before.

**Comment by calavera** [comment]
Hey @duglin, I've assigned this to you because you know all about this :smile_cat:

**Comment by icecrime** [comment]
Traces back to #13367.

**Comment by icecrime** [comment]
Discussed on IRC: it is indeed a breaking change, but I think we can consider the old behavior a bug that shouldn't be preserved over time.

Sorry, closing this one (don't worry, you still have many other actual bugs :p)

**Comment by duglin** [comment]
LOL

**Comment by ibuildthecloud** [comment]
http://xkcd.com/1172/

Still a breaking change.  The only way to detect a created but not started container was to look for "", so I have code just for that.  Will change to "" or "Created".
