### ISSUE TITLE
1.7: /version is not map[string]string anymore

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#13730]
For 1.6 and earlier /version would return `map[string]string`.  In 1.7 it now has a `experimental` flag in it which is a boolean.  So the type now is essentially `map[string]interface{}`.  I don't know if this is considered a bug but basically github.com/fsouza/go-dockerclient fails to work now because of this.

**Comment by icecrime** [comment]
The fact that the `bool` is sent to a bad version is a (my) mistake, and will be fixed by #13731. The type of the field in itself is not an issue: we don't guarantee `/version` to be returning a `map[string]string` but valid JSON.
