### ISSUE TITLE
Question: Is it possible running docker on big endian, arm32, linux=2.6.34?

### ISSUE THREAD

**Issue by hewei1990102** [docker/docker#13737]
'docker version' :
Client API version: 1.18
Go version (client): go1.4.2
OS/Arch (client): linux/arm
Server version:
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server):
OS/Arch (server): linux/arm

'docker info' :

'uname -a' :
Linux 3.10 #2 SMP Sat May 23 16:00:50 UTC 2015 armv7l GNU/Linux

Can cross compile docker from source to big endian?

**Comment by DivyaYash** [comment]
Was this ever answered?
