### ISSUE TITLE
Error creating aufs mounts: Invalid argument

### ISSUE THREAD

**Issue by pbecotte** [docker/docker#13742]
Hi guys.  This just started happening to me multiple times per day.  Our workflow is to create a DinD container to build our various containers in our build pipeline.  When we merge a change, Jenkins kicks off two container builds by using docker start -a on the existing containers.  It has started that pretty nearly every other time both of those builds fail with the same error.  Pasted from the Jenkins log...

09:54:28 docker start -a build_base || \
09:54:28 	docker run --name build_base --privileged -v ${WORKSPACE}:/opt/bamx bamx/dind \
09:54:28     bash -e /opt/bamx/buildbase.sh
09:54:28 time="2015-06-04T13:54:03Z" level=fatal msg="Error response from daemon: Cannot start container build_base: Error getting container 07c45e3d90c27a3ad427519f401e05f1cfcdff97cfad14358f2b1b76d5a9e271 from driver aufs: error creating aufs mount to /var/lib/docker/aufs/mnt/07c45e3d90c27a3ad427519f401e05f1cfcdff97cfad14358f2b1b76d5a9e271: invalid argument"

The other job references a different container, but other then that, the error is identical.  I am not sure what I have changed... the bamx/dind image is vendored so I know it is the same.  The AMI I build the Jenkins slaves with has not changed, and I have swapped those machines out several times to ensure it wasn't a problem with one of them.  The only thing I can think of is that I run a `docker rmi $(docker images -q)` a lot more frequently to try and keep on top of disk space on the slave, but I had thought that was save with not deleting needed images ... and the jobs ALWAYS work properly the next time I try them... we have had a lot of failures, but not two in a row.

The host runs on EC2 and has the following info...

Docker info: 
docker info
Containers: 23
Images: 352
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 398
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-53-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 3.859 GiB
Name: ip-172-31-31-7
ID: CSQS:JGPK:E43K:BFRQ:Y6P7:WMYE:PNIU:MBCD:PITD:JDYC:GSJI:JPPT
Username: pbecotte
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support
Docker version:

Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
Info from inside the dind container...

Containers: 0
Images: 0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-53-generic
Operating System: Ubuntu 14.04.2 LTS (containerized)
CPUs: 2
Total Memory: 3.859 GiB
Name: 080037324c29
ID: BQGE:ROW2:JXUM:TQNF:HKDW:TFJM:HOPK:LRQ6:GGJW:RKJS:VLMH:JZAV
WARNING: No swap limit support
Client version: 1.6.1
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 97cd073
OS/Arch (client): linux/amd64
INFO[0049] GET /v1.18/version                           
INFO[0049] +job version()                               
INFO[0049] -job version() = OK (0)                      
Server version: 1.6.1
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 97cd073
OS/Arch (server): linux/amd64

**Comment by cpuguy83** [comment]
So running docker in docker?
I think you need to make sure the inner docker's `/var/lib/docker` is mapped to a non-aufs dir on the host fs.

**Comment by pbecotte** [comment]
Indeed.  The Dockerfile I use is from the official docker in docker repository, and includes the line

VOLUME /var/lib/docker

FYI, I set Jenkins to not run the two jobs at the same time anymore... and one of the containers failed to launch even when it was being launched by itself (though it worked the next couple times).

**Comment by cpuguy83** [comment]
The only thing I can think of is an unclean shutdown causing some aufs mounts to be left around, this would cause the `invalid argument` error to be returned.

**Comment by thaJeztah** [comment]
@pbecotte are you still having this issue?

**Comment by pbecotte** [comment]
We moved away from using Docker-in-Docker, so no... but that doesn't say anything.  On a related note, my original reason for doing this is so I didn't have to worry about how a bunch of jenkins jobs hitting the same docker daemon would interact with one another, but we have not had a single issue with concurrency in that respect :)

**Comment by thaJeztah** [comment]
@pbecotte thanks, I think it's best to close this issue then,  but feel free to comment here if you don't agree.

If you haven't read it yet, this article may be of interest to you: http://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/

**Comment by pbecotte** [comment]
We had moved away from it by that point, but I had read that article... thanks!

**Comment by till** [comment]
Just adding my two cents here: I had a similar problem, running Docker in Docker on Github Actions.

Turns out, the outer Docker is using Aufs and then my Docker in Docker fails downloading images, or creating anything that involves a mount. When I configure my inner (😂) Docker daemon with `storage-driver: vfs` it works.

**Comment by thomasstaltner** [comment]
Thanks to @till -> starting the daemon with `storage-driver: vfs` ` (/usr/bin/dockerd --storage-driver=vfs)` solved the problem in my case 😁

**Comment by geerlingguy** [comment]
And to be more specific, @till's fix worked for me by adding the following step in my GitHub Actions workflow:

```yaml
      - name: Force GitHub Actions' docker daemon to use vfs.
        run: |
          sudo systemctl stop docker
          echo '{"cgroup-parent":"/actions_job","storage-driver":"vfs"}' | sudo tee /etc/docker/daemon.json
          sudo systemctl start docker
```
