### ISSUE TITLE
The default-gateway{,-v6} feature was lost during the libnetwork merge

### ISSUE THREAD

**Issue by eolamey** [docker/docker#13755]
This feature was added by @lebauce in https://github.com/docker/docker/pull/9381, shortly before the libnetwork mega-merge. After the merge, only the CLI flags were left in `daemon/config_linux.go`, but the values were not set in the new bridge network driver.

**Comment by mrjana** [comment]
@eolamey we did port this feature into libnetwork. Why do you think the values are not set in the new driver

**Comment by mrjana** [comment]
@eolamey I see what you mean. We did port the feature but it looks like we are not passing the cli flags to libnetwork when the feature is configured. We will fix this.

**Comment by mrjana** [comment]
@eolamey I see you also made a PR to fix this. Let me review that instead.

**Comment by eolamey** [comment]
Wow, @mrjana, we are way to fast for me :) I was preparing the PR, which I just properly created. I added integration test so that this won't get lost again :)
