### ISSUE TITLE
docker 1.7 events api reporting last 64 events causes issues

### ISSUE THREAD

**Issue by phobologic** [docker/docker#13753]
Description of problem:

The new events API seems to return the last 64 events when you query it, rather than simply tailing.  This is causing issues for logspout. You can see the logspout bug here:

https://github.com/gliderlabs/logspout/issues/106

This seems to be the expected behavior, so I'm mostly looking for guidance on how to deal with it.  If there could be a way to  get the old tail behavior, that'd be awesome.

```
$ docker --version
Docker version 1.7.0-dev, build 115b11a
```

```
$ docker info
Containers: 8
Images: 69
Storage Driver: btrfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-53-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 8
Total Memory: 14.69 GiB
Name: ip-10-128-17-16
ID: JCSN:4DZP:HF3H:OFRY:TX4J:IW37:FT5K:5TXS:7NIR:65H5:VDI6:V7CS
```

```
$ uname -a
Linux ip-10-128-17-16 3.13.0-53-generic #89-Ubuntu SMP Wed May 20 10:34:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Environment details: `AWS, c4.2xlarge`

How reproducible:  Easily reproducible, it's a change in the API behavior.

Steps to Reproduce:
1. Hit the events API - it returns the last 64 events (if there are some) then goes into the tail behavior.

**Comment by cpuguy83** [comment]
Confirmed this is changed behavior from 1.6
