### ISSUE TITLE
Ressource management at runtime

### ISSUE THREAD

**Issue by mboussaa** [docker/docker#13759]
Is there any attempt to manage containers configuration at runtime?
I have to change ressources limitation at runtime.
A Web UI would be great to manage all containers settings at runtime like cockpit... 

Thanks in advance.

**Comment by isuftin** [comment]
@mboussaa What sort of resources are you describing? I'm assuming you're talking about CPU count limits? Mem limits?

**Comment by mboussaa** [comment]
yes I am talking about CPU and MEMORY reconfiguration at runtime

**Comment by cpuguy83** [comment]
Closing as dup of #6323
