### ISSUE TITLE
Docker service loaded but active:failed on Ubuntu 15.04

### ISSUE THREAD

**Issue by VirgilMing** [docker/docker#13758]
Installed via `wget -qO- http://get.docker.com | sh` on Ubuntu 15.04 x64, OS image provided by Vultr.

Problem: can't `sudo docker run hello-world`, says 
> FATA[0000] Post http:///var/run/docker.sock/v1.18/containers/create: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?

Information:

`sudo systemctl start docker` executes without complaint, but `systemctl status docker` prints the following:
> docker.service - Docker Application Container Engine
>   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
>   Active: **failed** (Result: exit-code) since Thu 2015-06-04 17:03:11 UTC; 13h ago
>   Docs: http://docs.docker.com
>  Process: 638 ExecStart=/usr/bin/docker -d -H fd:// **(code=exited, status=1/FAILURE)**
> Main PID: 638 (code=exited, status=1/FAILURE)

`sudo apt-get install apparmor` says up to date.

`docker version`:
> Client version: 1.6.2
> Client API version: 1.18
> Go version (client): go1.4.2
> Git commit (client): 7c8fca2
> OS/Arch (client): linux/amd64

`uname -a`:
> Linux scarlet 3.19.0-18-generic #18-Ubuntu SMP Tue May 19 18:31:35 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by thaJeztah** [comment]
Could you check the daemon log files, to see if they contain anything relevant?

**Comment by VirgilMing** [comment]
Sorry but where are these log files? I suppose it should be found at `/var/log/upstart/docker.log` as documented in #705, but there's not even `upstart` directory. Is this the source of problem?

**Comment by runcom** [comment]
Try with `journalctl -u docker.service` and paste logs here

**Comment by VirgilMing** [comment]
> No journal files were found.

**Comment by runcom** [comment]
This thing doesn't seems like a bug tho so I'm going to close this for now. 
@VirgilMing would you come to IRC on #docker channel and we can try to debug what's happening to you and eventually fill  a bug report here on github? 
If you can, we can continue talking here even if the  issue is closed

So, could you try to manually do `docker -dD` and paste the output? Ping me on irc btw :)
