### ISSUE TITLE
exit or kill commands make the server completely shutdown and reboot

### ISSUE THREAD

**Issue by rookie7799** [docker/docker#13769]
docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.3.3
Git commit (client): a8a31ef/1.5.0
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.3.3
Git commit (server): a8a31ef/1.5.0
You have mail in /var/spool/mail/root

docker info
Containers: 12
Images: 6
Storage Driver: devicemapper
 Pool Name: docker-8:3-1059673-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.857 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 3.256 MB
 Metadata Space Total: 2.147 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: native-0.2
Kernel Version: 2.6.32-431.5.1.el6.x86_64
Operating System: <unknown>
CPUs: 24
Total Memory: 31.32 GiB
Name: api1
ID: Q4MJ:BTJM:T6QL:MT47:B63D:5BM5:QF4W:HIZ6:UCVK:AFPS:PRZI:44AA

uname -a
Linux xxxx 2.6.32-431.5.1.el6.x86_64 #1 SMP Wed Feb 12 00:41:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

This is a physical box.

We are experimenting with centos:latest containers and total server reboot happened twice:

1. Container was running, used command: docker kill [containerid]
2. We were inside the container instance and typed: exit

Both of these instances made the server freeze and reboot, after which lot's of system checks/fixes happend.

Server Centos version is 6.5 with 2.6.32-431.5.1.el6.x86_64 kernel.

Unfortunately we do not have any logs for this...

**Comment by cpuguy83** [comment]
Looks like your kernel is pretty old.
Have you tried updating to the latest? RH backports bugfixes to 2.6.32 all the time.
Looks like 2.6.32-504

**Comment by Cbeck527** [comment]
Saw this with our machine running the same kernel... still seeing the above issue after updating to the latest kernel available in our repositories: 
```
$ uname -a
Linux m-bamboo02 2.6.32-504.16.2.el6.x86_64
```

**Comment by visualphoenix** [comment]
@rookie7799 can you try 1.6.2 on 2.6.32-504.16.2.el6.x86_64? I've used:

```
sudo yum install -y http://mirror.centos.org/centos/6.6/os/x86_64/Packages/device-mapper-libs-1.02.90-2.el6.x86_64.rpm http://mirror.centos.org/centos/6.6/os/x86_64/Packages/device-mapper-1.02.90-2.el6.x86_64.rpm http://mirror.centos.org/centos/6.6/os/x86_64/Packages/device-mapper-event-1.02.90-2.el6.x86_64.rpm http://mirror.centos.org/centos/6.6/os/x86_64/Packages/device-mapper-event-libs-1.02.90-2.el6.x86_64.rpm https://dl.fedoraproject.org/pub/epel/testing/6/x86_64/docker-io-1.6.2-1.el6.x86_64.rpm
```

**Comment by Cbeck527** [comment]
FWIW, updating our server's kernel to 3.x solved this issue completely.

**Comment by visualphoenix** [comment]
@Cbeck527 custom kernels (eg 3.x kernels) on 6.6 have never been supported by Docker

**Comment by Cbeck527** [comment]
@visualphoenix absolutely. I'm not recommending anyone take this option, but merely saying that it fixed it for us. This issue was blocking our deployments, and we had to take a relatively unorthodox approach to fix it. ¯\_(ツ)_/¯

**Comment by thaJeztah** [comment]
closing this issue per https://github.com/docker/docker/issues/14174#issuecomment-118166662
