### ISSUE TITLE
Creating container via remote API with data volume specification causes error and creates unwanted folder in the host machine's root filesystem

### ISSUE THREAD

**Issue by lexandro** [docker/docker#13786]
Docker version:
-
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

Docker info:
-
Containers: 8
Images: 140
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 156
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-37-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 4
Total Memory: 31.38 GiB
Name: lexandro-linux
ID: LCZ4:UAF3:OR4A:7QA5:3VTG:SUAI:ZI6T:623G:KIV3:IYSS:DVAL:3NYK
Debug mode (server): true
Debug mode (client): false
Fds: 32
Goroutines: 48
System Time: Sat Jun  6 17:27:56 CEST 2015
EventsListeners: 0
Init SHA1: 7f9c6798b022e64f04d2aff8c75cbf38a2779493
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker
Username: lexandro
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support

uname -a:
-
Linux lexandro-linux 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Environment details:
-
my **local** Linux Mint 17.1 machine

How to reproduce:
-
1. Configure docker daemon with the following options: DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4 -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock -api-enable-cors --debug=true"
1. runL 'docker pull ubuntu'
2. Submit a POST call to http://localhost:2375/containers/create with Content-Type=application/json and message body: {"Image":"ubuntu","HostConfig":{"Binds":["/fakedir"]}}
3. You'll get http status 500, message: Invalid volume specification: /fakedir
4. A 'fakedir' folder created in the docker host's root.

Actual results:
-
1. /fakedir created in the docker host
2. Showing a created container in the docker ps -a

Expected Results:
-
Creates a container with /fakedir shareable volume based on https://docs.docker.com/reference/api/docker_remote_api_v1.18/#create-a-container:
"Binds – A list of volume bindings for this container. Each volume binding is a string of the form container_path (to create a new volume for the container), host_path:container_path (to bind-mount a host path into the container), or host_path:container_path:ro (to make the bind-mount read-only inside the container)."

...or throwing error about a non existing folder, but definitely not creating new folder in the host machine's root.

Additional info: 
-
**Docker log:**
DEBU[178483] Calling POST /containers/create              
INFO[178483] POST /containers/create                      
DEBU[178483] CORS header is enabled and set to: *         
INFO[178483] +job create()                                
ERRO[178483] Couldn't run auplink before unmount: exec: "auplink": executable file not found in $PATH 
ERRO[178483] Couldn't run auplink before unmount: exec: "auplink": executable file not found in $PATH 
Invalid volume specification: /fakedir
INFO[178483] -job create() = ERR (1)                      
ERRO[178483] Handler for POST /containers/create returned error: Invalid volume specification: /fakedir 
ERRO[178483] HTTP Error: statusCode=500 Invalid volume specification: /fakedir

**Comment by lexandro** [comment]
I purged all containers and images, then pulled only the ubuntu image to retest. The result was the same.

**Comment by runcom** [comment]
@lexandro on latest master `/fakedir` isn't created anymore so first problem gone (I'll tell you if the latest rc release for 1.7 works as soon as I try)
The fact that the container is shown in `docker ps -a` with created status even if creation had an error maybe it's wanted for some reason but I don't recall so maybe someone has this answer

**Comment by cpuguy83** [comment]
Volumes aren't created until after the container is created.
There is a PR to do validations on the volume specs prior to creating the container.

**Comment by lexandro** [comment]
This is a great news! :)

Btw I also tried the :/fakedirectory format to see the string splitting, that resulted with different 'image not found' like-ish error. Could you try it please, before I submit another ticket without reason? :)

**Comment by thaJeztah** [comment]
@lexandro if you want to test the current release candidate yourself, you ca find the downloads here; https://github.com/docker/docker/pull/13528#issuecomment-109061623.

Be aware that you should **not** test this on critical data, there may still be bugs. Also, you may not be able to downgrade to 1.6 after testing 1.7

**Comment by thaJeztah** [comment]
@lexandro I see you closed this issue; out of interest, was this issue resolved for you on 1.7?

**Comment by lexandro** [comment]
Yes. I tested it on 1.7 and worked as expected.

**Comment by thaJeztah** [comment]
Good to hear! Thanks for testing it and closing the issue
