### ISSUE TITLE
Exported Fields are completely undocumented

### ISSUE THREAD

**Issue by stevvooe** [docker/docker#13782]
There is an enormous amount of struct definitions and fields without documentation. Too examples of code docker datatypes, absolutely critical to the internals of docker, having passing documentation:

https://github.com/docker/docker/blob/master/image/image.go#L24
https://github.com/docker/docker/blob/master/runconfig/config.go#L109

The lack of documentation on these fields leads to major issues in a large codebase. The largest issue is that intent of the field is completely lost to history. This makes adding new features more complex and leads to situations where new fields are added in other, non-optimal locations. It also leads to misuse of said fields. Discovery within the codebase is heavily impacted. One example of this is `(image.Image).Container`. One looks at that and asks, why would an image know anything about a container? Don't we create images from containers? What is the intended relationship? Such detail can only be inferred by search existing uses. However, such uses don't provide any detail about correctness, making it much harder to spot inconsistencies and bugs.

One of the best features of Go is the automatic documentation. It not only allows one to understand available APIs, but also provides deep links into the source. There are few better tools to understand the architecture of an application. Looking at [image.Image](http://godoc.org/github.com/docker/docker/image#Image), the lack of documentation here is opting out of fully leveraging such a fantastic tool.

I propose two things with this issue:

- [ ] No new fields should be added in without complete documentation. Ideally, we'd adopt full go documentation standards.
- [ ] Existing fields should be documented (this is a larger effort)

The effect of taking these actions will be two folds:

1. New contributors will spend less time understanding the application and provide better contributions.
2. Obvious architectural mistakes will become apparent and can be addressed and fixed.

I understand this style of issue has a danger of not being actionable, but I hope this can open a conversation on code quality that is much needed.

**Comment by thaJeztah** [comment]
:+1: excellent suggestion; wrt documenting the existing fields; Perhaps we should create separate issues for those; it sounds like something beginning contributors can contribute, learning the codebase at the same time?

> I hope this can open a conversation on code quality that is much needed.

Would that be something to discuss during the contributors summit after DockerCon?

ping @crosbymichael as chief maintainer

**Comment by stevvooe** [comment]
@thaJeztah Whatever it takes to help make this more actionable. I am not sure if this is the best task for "beginners", since there is a lot of "archaeology" required. We can probably auto-generate an initial list of candidates with golint or specialized tooling.

**Comment by thaJeztah** [comment]
@stevvooe agreed on the "beginning contributors" part, that was me thinking out loud, thinking of ways to make this manageable.

**Comment by stevvooe** [comment]
Discussed with @calavera. We may want to start this effort by modifying this recommendation to the contributor documentation.

**Comment by runcom** [comment]
where are we on this now that existing code base is linted (documented) and golint is enabled on commit push

**Comment by LK4D4** [comment]
@runcom I think all should be documented now. I personally thought it would be much longer :)

**Comment by calavera** [comment]
Yeah, I'm going to close this issue as fixed. Golint is probably 99.99% complete if not 100%. But if we find any pending case we can handle it individually.

We should thank everyone that participated in #14756. It was awesome seeing those people coordinate in this common effort.

**Comment by stevvooe** [comment]
O wow. This is closable!!!

:clap: 

Great work all around!
