### ISSUE TITLE
/var/run/docker.sock mounting /run/docker.sock instead

### ISSUE THREAD

**Issue by jeffcharles** [docker/docker#13781]
Description of problem:

When I run `docker run -it --name registrator2 -v /var/run/docker.sock:/tmp/docker.sock -h ubuntu-14 gliderlabs/registrator:v5 consul://127.0.0.1:8500`, I see the following volumes entry after running `docker inspect registrator2`:

```
"Volumes": {
        "/tmp/docker.sock": "/run/docker.sock"
    },
```

despite having this entry further up:

```
"HostConfig": {
        "Binds": [
            "/var/run/docker.sock:/tmp/docker.sock"
        ],
```

`docker version`:

Docker version 1.6.2, build 7c8fca2

`docker info`:

```
Containers: 11
Images: 305
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 327
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04 LTS
CPUs: 2
Total Memory: 993.9 MiB
Name: ubuntu-14
ID: TAKT:FKDW:PND3:BUCN:TGPE:AUMN:KDA3:EBWQ:BWLV:SBBC:YXRP:JZ55
```

`uname -a`:

`Linux ubuntu-14 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`

Environment details (AWS, VirtualBox, physical, etc.):

VirtualBox (4.3.26r98988)

How reproducible:

Consistently

Steps to Reproduce:
1. run `docker run -it --name registrator2 -v /var/run/docker.sock:/tmp/docker.sock -h ubuntu-14 gliderlabs/registrator:v5 consul://127.0.0.1:8500`
2. run `docker inspect registrator2`

Actual Results:

```
"Volumes": {
        "/tmp/docker.sock": "/run/docker.sock"
    },
```

Expected Results:

```
"Volumes": {
        "/tmp/docker.sock": "/var/run/docker.sock"
    },
```

The path pointed to should have `/var/` in front of it

Additional info:

**Comment by LK4D4** [comment]
I think this is because of FollowSymlink. Isn't it working?

**Comment by jeffcharles** [comment]
Ah! That would make sense. I was not aware that volumes reported on the symlink destination rather than the source.

Initially I thought it wasn't working, but it turns out it was due to Registrator not reporting errors when failing to connect to Consul which caused Docker events to not get picked up.

**Comment by LK4D4** [comment]
@jeffcharles Thanks for check!
