### ISSUE TITLE
system(not VM) crashed and can't reboot(centos 7, 3.10.79, docker 1.6)

### ISSUE THREAD

**Issue by gaddifymac** [docker/docker#13798]
Use the commands below to provide key information from your environment:
```
docker version: 1.6 
docker info: 
Images: 152
Storage Driver: devicemapper
 Pool Name: docker-253:1-2149379557-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 4.582 GB
 Data Space Total: 107.4 GB
 Data Space Available: 102.8 GB
 Metadata Space Used: 7.164 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.14 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Kernel Version: 3.10.79
Operating System: CentOS Linux 7 (Core)
CPUs: 4
Total Memory: 7.708 GiB
Name: 192.168.70.211
ID: 4QVU:IKGW:BLSU:OWUK:EQ7H:5STV:VPM3:XN4T:WCPU:GAQS:6GD5:RYCH
```
```
uname -a: 3.10.79 #1 SMP Fri Jun 5 13:51:07 CST 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Provide additional environment details (AWS, VirtualBox, physical, etc.): 
physical machine hp prodesk 680 g1 twr

List the steps to reproduce the issue:
1. run several containers in a marathon+mesos+docker  cluster, only one machine crashed

Describe the results you received:  can't reboot and  get ERROR: cannot initialize the agpgart module 
DRM: Fill_in_dev failed  
systemd[1]:Failed to execute /bin/sh, giving up:No such file or directory

Describe the results you expected:

Provide additional info you think is important:
This happened three times(2 times with 2.6.32-504, so I updated the kernel version to 3.10.79). But the problem still exists. Is docker 1.6 not that stable or we should do some special settings or recommendation for docker? Thanks.

**Comment by gaddifymac** [comment]
I run serveral container services in a docker-mesos-marathon cluster.

**Comment by unclejack** [comment]
@gaddifymac RHEL 6 / CentOS 6 aren't supported with any custom kernels. They are only supported with the kernels they ship with (2.6.32...). Please make sure your system is fully updated using `yum update`.

**Comment by cpuguy83** [comment]
Closing since there really doesn't seem to be enough information to look into this, and is likely due to kernel issues.

If you are still having issues, please ping here with a simple repro case.
Thanks!
