### ISSUE TITLE
Provide dynamically-linked binary packages

### ISSUE THREAD

**Issue by chrissnell** [docker/docker#13794]
See discussion here: https://github.com/docker/docker/pull/13038#issuecomment-99721834

For those of us that need Registry 2.0 support on the Ubuntu 14.04 platform, the only game in town is dynamically-linked 1.7.0-dev binaries.  Building these binaries and packaging them up in .debs takes some work and it's especially painful for people who want to install them using an apt repo.  

Ideal solution: nightly (or at least regular) builds of 1.7.0-dev (dynbinary) available as signed packages in the official get.docker.io repo.

Less ideal solution: nightly builds of 1.7.0-dev (dynbinary) packaged as .debs and made available on master.dockerproject.org.   The problem with this solution is that this site isn't (to my knowledge...) set up as an apt repository.  Perhaps someone could go through the process of making it into one?

Thanks!

**Comment by thaJeztah** [comment]
Thanks @chrissnell (I shortened the title a bit for readability)

ping @tianon @jfrazelle I *know* you are working on this, but I don't think there's a general issue for tracking. Also, I wasn't sure what the status was and if this included master- and experimental builds, so I suggested @chrissnell to open an issue.

**Comment by jfrazelle** [comment]
There's a PR

**Comment by thaJeztah** [comment]
Doh! Looks like I missed that one :blush: https://github.com/docker/docker/pull/13680. I'll add a "closes" to that PR

**Comment by jfrazelle** [comment]
Ah cool ya ;) there's a checklist of remaining it's too so kinda track
progress

**Comment by thaJeztah** [comment]
I noticed, cool that it actually shows a progress bar here!

**Comment by chrissnell** [comment]
Dupe noted.  Thanks y'all.
