### ISSUE TITLE
Proposal: In-driver storage-driver configuration behavior

### ISSUE THREAD

**Issue by vbatts** [docker/docker#13807]
storage-drivers allow for additional options (http://docs.docker.com/reference/commandline/cli/#daemon-storage-driver-option)

I propose expected behavior of the storage driver preserving the provided options at runtime. If the options change in a way that is not migratable, then it can bail with a message to the user on how to mitigate the issue. (e.g. whether `/var/lib/docker` needs to be a clean slate, etc)

**Comment by therealromster** [comment]
I haven't been looking closely at this, but allowing where to set /var/lib/docker data too might be a nice idea. Or even store the database layout in the configured storage pool.

**Comment by vbatts** [comment]
@therealromster i'm not sure i understand what you mean. There is already a daemon flag `-g` to designate the location for docker (i.e. `/var/lib/docker`). This is more a image storage case handling proposal, so we can have a consistent recovery for changes and variations of configured settings by the user.

**Comment by therealromster** [comment]
Any status on migrating the settings for storage out of the daemon command line/docker.conf and actually sorting the storage settings in /var/lib/docker/somefile ? that way multiple directories with -g will just work.

**Comment by thaJeztah** [comment]
While it would be nice to store the options in the storage directory itself, we now have the daemon.json file, which makes it easier to keep track of your options.

We don't think this is a high priority issue, so I'm closing, but @vbatts you can comment if you disagree  :heart:
