### ISSUE TITLE
Systemd scopes leakage

### ISSUE THREAD

**Issue by LK4D4** [docker/docker#13802]
There is leak of systemd scopes in `/sys/fs/cgroup/systemd/system.slice/`. You can easily reproduce with `docker-stress`.

**Comment by LK4D4** [comment]
#7015 old issue

**Comment by LK4D4** [comment]
docker/libcontainer#617 should fix this.

**Comment by runcom** [comment]
fwiw it's now happening consistently to me when I close stdin/out of a running container while it's doing thinghies and I try to run another instance of it

**Comment by LK4D4** [comment]
@runcom leaked fds probably. ping @philips

**Comment by philips** [comment]
@LK4D4 what do you need help with? What is the ping for? :confused:

**Comment by LK4D4** [comment]
@philips Can opened fds prevent transient unit from autostop? Sorry, I will be more accurate with pings :(

**Comment by philips** [comment]
@LK4D4 It should not, the process should simply get a sigterm from systemd and then a sigkill later.

**Comment by c2h5oh** [comment]
@LK4D4 Can we get that included in 1.7.1? It seems https://github.com/docker/libcontainer/pull/617 haven't made it into libcontainer 2.1.1

**Comment by LK4D4** [comment]
@c2h5oh I'm not sure, looks like it isn't regression... And updating libcontainer now can be a pain

**Comment by c2h5oh** [comment]
@LK4D4 `--restart=always` always fails because of this on Ubuntu 15.04 within a couple of days right now. The service I'm running is fairly stable, so it might be it fails on 1st restart - I'll check.

**Comment by c2h5oh** [comment]
@LK4D4 confirmed `--restart=always` will fail on Ubuntu 15.04 100% of the time (or close - sample I have is small)

**Comment by LK4D4** [comment]
ping @icecrime

**Comment by hadronzoo** [comment]
I'm also seeing this error when running containers with docker-compose on a Debian 8.1 (Docker 1.7.1). Executing `sudo systemctl stop docker-<hash>.scope` fixes it temporarily.

**Comment by LK4D4** [comment]
Anyway fix will be in 1.8 :)

**Comment by ahmetalpbalkan** [comment]
@LK4D4 issue still happens in 1.8.1. Is the fix in?

I can easily/frequently hit this in CoreOS 723.3.0 (stable) when I `docker restart` some container (that has `--restart=always`) and it fits @ibuildthecloud's description over at https://github.com/docker/docker/issues/7015#issue-37804746 at @c2h5oh's comment above.

**Comment by shehi** [comment]
Yea, same here. Started having this problem few weeks ago for project github.com/AudithSoftworks/Basis (both in dev and CI environment, check Test badge in README).

**Comment by shime** [comment]
happening to me too on `CoreOS alpha (789.0.0)` with `Docker version 1.7.1, build 2c2c52b-dirty`, with`fig 1.0.1`

using `systemctl stop docker-*` fixes it

**Comment by stefanklug** [comment]
The following script helped me automate ```systemctl stop docker-*``` without touching running containers. Just run it as root.
```
#!/bin/sh
set -e
RUNNING_CONTAINERS=`docker ps -q --no-trunc=true | paste -sd "|" -`
cd /sys/fs/cgroup/systemd/system.slice/
for f in $(ls -1 | grep -e "docker-.*\.scope" | grep -Ev "docker-($RUNNING_CONTAINERS)"); do
	echo "Stopping $f"
	systemctl stop "$f"
done
```

**Comment by LK4D4** [comment]
Not an issue anymore in docker master.

**Comment by philips** [comment]
@LK4D4 how was it fixed?

**Comment by LK4D4** [comment]
@philips I don't know for sure, it might be double-stop in libcontainer(docker/libcontainer#617) or fix in systemd. Because there was no reports recently I think it's double-stop.

**Comment by cornfeedhobo** [comment]
When was this marked not an issue anymore? I run into this regularly ....

**Comment by 2rs2ts** [comment]
still happens all the time for my company. we're running debian stretch, kernel is version `5.4.38`, docker is version `19.03.8`, containerd is version `1.2.13`, and systemd is version `232`.
