### ISSUE TITLE
volume-driver: In response type "error" is expected, but there is no way to decode it from json

### ISSUE THREAD

**Issue by yasker** [docker/docker#13818]
Here is the definition of expected response from plugins of volume in volume/drivers/proxy.go:
https://github.com/docker/docker/blob/master/volume/drivers/proxy.go#L14

```
type volumeDriverResponse struct {
        Mountpoint string `json:",ommitempty"`
        Err        error `json:",ommitempty"`
}
```

I don't believe you can actually decode/encode from/to type "error", which is defined as:

```
type error interface {
        Error() string
}
```

It's an interface, not an struct, and no exportable field available.

This result in any non-null error message from external plugin shows:

```
ERRO[0071] Handler for POST /containers/create returned error: External volume driver request failed for test: json: cannot unmarshal object into Go value of type error
ERRO[0071] HTTP Error                                    err=External volume driver request failed for test: json: cannot unmarshal object into Go value of type error statusCode=500
```

BTW: Also, there are typos in struct descriptor: "ommitempty" should be "omitempty"

**Comment by yasker** [comment]
docker version: 1.7.0-dev

@calavera

**Comment by phemmer** [comment]
> I don't believe you can actually decode/encode from/to type "error"

You can, but it requires a custom marshaller/unmarshaller.

**Comment by yasker** [comment]
@phemmer Yeah, thanks for clarify...

And the current code used an standard decoder.

https://github.com/docker/docker/blob/master/pkg/plugins/client.go#L80

**Comment by calavera** [comment]
Thanks for catching this @yasker. I'll have a patch ready for reviewing in a few minutes.

**Comment by calavera** [comment]
I've removed from the milestone, since it's not activated in 1.7 but experimental only. Nothing changes, working on it.

**Comment by calavera** [comment]
#13828 should fix these issues. I went for an easy implementation, because there is no much we can do with go errors.

**Comment by yasker** [comment]
Yeah, that's what I thought as well. error type is in fact not very necessary so far.

Checking on PR now.
