### ISSUE TITLE
BasicAuth registry login should not send Authentication header on 302

### ISSUE THREAD

**Issue by ewindisch** [docker/docker#13811]
When authenticating to a registry using BasicAuth (such as a standalone registry), or when X-Docker-Token is true, we should not continue to send Authentication headers following a redirect.  This appears to be a regression introduced during 1.7 development due to RoundTripper refactoring and does not appear to affect earlier versions.

/cc @tiborvass

**Comment by tiborvass** [comment]
Thanks @ewindisch, will take care of it.

**Comment by ewindisch** [comment]
:+1:
