### ISSUE TITLE
Permission on folders is not correct on using COPY

### ISSUE THREAD

**Issue by mebinjacob** [docker/docker#13823]
Description of problem:
d????????? ? ?      ?              ?            ? src
d????????? ? ?      ?              ?            ? queries
d????????? ? ?      ?              ?            ? lib
d????????? ? ?      ?              ?            ? dist
d????????? ? ?      ?              ?            ? bin

This is what is see as a non root user named hadoop, now if I exit from this user and run ls -ltr as root user, it shows the permission correctly, that is 

drwx------ 4 hadoop hadoop      4096 Jun  9 11:13 src
drwx------ 2 hadoop hadoop      4096 Jun  9 11:13 queries
drwx------ 2 hadoop hadoop      4096 Jun  9 11:13 lib
drwxrwxr-x 2 hadoop hadoop      4096 Jun  9 11:13 dist
drwxrwxr-x 4 hadoop hadoop      4096 Jun  9 11:13 bin

on folder path /usr/local/hadoop/dSparq/d-sparq-master/. The folder dSparq came inside the docker via a COPY command.
And now if I move to user hadoop, and run ls -ltr it shows the permission correctly.
`docker version`:
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

`docker info`:
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
mebin@mebin:~$ docker info
Containers: 6
Images: 204
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 216
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.16.0-38-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 4
Total Memory: 15.4 GiB
Name: mebin
ID: RXE6:4KPY:ELOU:3AJO:VMYW:OXHC:KRPP:FBJM:VBAT:T7HY:PBXM:PYOC
WARNING: No swap limit support

`uname -a`:
Linux mebin 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
physical, i5, 16GB RAM, Ubuntu 14.04

How reproducible:

Steps to Reproduce:
1.Create docker file containing, copy and chown commands like 
COPY Master /usr/local/hadoop/dSparq and RUN groupadd hadoop
RUN useradd -m -g  hadoop hadoop
RUN chown hadoop:hadoop -R /usr/local/hadoop

2. login as non-root user(here hadoop) and see permission of /usr/local/hadoop/dSparq.
3.exit and login as root user in the container, and see permission of /usr/local/hadoop/dSparq
4. log in back as non-root user(hadoop) and everything becomes fine.

Actual Results:
Doesnt show proper permissions, cause of which applications are not able to access the files.

Expected Results:
Should show proper permissions.

Additional info:

**Comment by thaJeztah** [comment]
I'm not really sure how you "login", exit and login into the container, but I tried to reproduce this with these steps, but failed to reproduce the problem;

```bash
mkdir 13823-repro && cd 13823-repro
touch foo bar


cat << EOF > Dockerfile
FROM ubuntu
COPY . /test/
RUN groupadd hadoop
RUN useradd -m -g hadoop hadoop
RUN echo 'hadoop:hadoop' | chpasswd
RUN chown hadoop:hadoop -R /test/
EOF

docker build -t 13823-test .
```

Run the container as root

```bash
$ docker run --rm 13823-test ls -ltr /test/
total 4
-rw-rw-r-- 1 hadoop hadoop   0 Jun  9 13:21 foo
-rw-rw-r-- 1 hadoop hadoop   0 Jun  9 13:21 bar
-rw-rw-r-- 1 hadoop hadoop 149 Jun  9 13:31 Dockerfile
```

Run the container as hadoop

```bash
$ docker run --rm --user hadoop 13823-test ls -ltr /test/
total 4
-rw-rw-r-- 1 hadoop hadoop   0 Jun  9 13:21 foo
-rw-rw-r-- 1 hadoop hadoop   0 Jun  9 13:21 bar
-rw-rw-r-- 1 hadoop hadoop 149 Jun  9 13:31 Dockerfile
```


Run the container interactively

```bash
$ docker run -it --rm 13823-test
root@e4d0a2ef8ae1:/# login hadoop
Password:
hadoop@e4d0a2ef8ae1:~$ ls -ltr /test/
total 4
-rw-rw-r-- 1 hadoop hadoop   0 Jun  9 13:21 foo
-rw-rw-r-- 1 hadoop hadoop   0 Jun  9 13:21 bar
-rw-rw-r-- 1 hadoop hadoop 149 Jun  9 13:31 Dockerfile
```

**Comment by phemmer** [comment]
This is another issue relating to the umask docker runs with (see also #12745).

When you do `COPY Master /usr/local/hadoop/dSparq`, docker implicitly creates all the leading directories. If the umask docker is running with is restrictive, say `077`, those directories end up being created as readable by root only.

To fix this, make sure docker is running with a less restrictive umask, such as `022`.

**Comment by mebinjacob** [comment]
Here is my dockerfile content to reproduce this issue 

FROM ubuntu:14.04
MAINTAINER mebin <mebinjacob@gmail.com>

ENV HADOOP_INSTALL /usr/local/hadoop

COPY Master $HADOOP_INSTALL/dSparq

RUN groupadd hadoop
RUN useradd -m -g  hadoop hadoop

RUN chown hadoop:hadoop -R /usr/local/hadoop

#Setting up path
ENV PATH /usr/lib/jvm/java-8-oracle/bin:/usr/local/hadoop/bin:$PATH

RUN echo "/usr/local/hadoop/bin" >> /home/hadoop/.profile

ENV HADOOP_USER_HOME=/home/hadoop
ENV SHARED_DIRECTORY=/tmp/shared

And here is my folder structure with file permissions :- 
.
├── [-rw-rw-rw-]  Dockerfile
└── [drwx------]  Master
    └── [drwx------]  test
        ├── [drwx------]  test1
        └── [drwx------]  test2
Commands i run :- 
1. docker build -t mebin/issue .
2. docker run   --name issue   -it mebin/issue, Now you should enter the container, as root user.
3.  Inside the container, now run su hadoop.
4. Followed by ls -ltr /usr/local/hadoop/dSparq/test/
This is what i see then :- 
d????????? ? ? ? ?            ? test2
d????????? ? ? ? ?            ? test1
5. Now type exit to return to root user.
6. Now type ls -ltr /usr/local/hadoop/dSparq/test/ again but this time as root user.
This is what i see.
drwx------ 2 hadoop hadoop 4096 Jun 11 07:56 test1
drwx------ 2 hadoop hadoop 4096 Jun 11 07:56 test2
7. Now type su hadoop and ls -ltr /usr/local/hadoop/dSparq/test/ again,
I see,
drwx------ 2 hadoop hadoop 4096 Jun 11 07:56 test1
drwx------ 2 hadoop hadoop 4096 Jun 11 07:56 test2

which is what I was expecting to see at the first time I did ls -ltr on /usr/local/hadoop/dSparq/test.

ls -ltr /usr/local/hadoop/dSparq/test/ as root user seems to kick in something for hadoop user, that should happen when the image is created out of docker file.

This may or may not be related to https://github.com/docker/docker/issues/12745, cause I am not changing any of the permissions, it is right somewhere, it just doesnt kick in right after it boots.

Please let me know if you need any more information. If possible please let me know the module where the relevant code is written.
 
Thanks - Mebin
