### ISSUE TITLE
How to give write permission to /dev/cpu_dma_latency in docker?

### ISSUE THREAD

**Issue by satyajitpadhyewit** [docker/docker#13820]
Hello. Being a beginner in docker, I am aware that due to security issues we cant have writable permission to /dev but one of my program which is responsible for getting low latency needs to open the /dev/cpu_dma_latency and write zero to it in the container but I can't do it since I can't get permissions. Any help?

**Comment by bpradipt** [comment]
@satyajitpadhyewit, have you tried using a privileged container and trying the setting ?
Something like docker run -itd -v /dev:/dev --privileged <image> <cmd>
On my test system
With privileged 
docker run -it -v /dev/cpu_dma_latency:/dev/cpu_dma_latency --privileged busybox /bin/sh
# echo 0 > /dev/cpu_dma_latency 

Without privileged
docker run -it -v /dev/cpu_dma_latency:/dev/cpu_dma_latency busybox /bin/sh
# echo 0 > /dev/cpu_dma_latency 
/bin/sh: can't create /dev/cpu_dma_latency: Operation not permitted

**Comment by satyajitpadhyewit** [comment]
Sorry for the late reply but thank you so much for the reply. It worked.

**Comment by bpradipt** [comment]
Great @satyajitpadhyewit !!. I feel this issue can be closed now.
