### ISSUE TITLE
Unable to build docker images, Docker cgroup no space left on device

### ISSUE THREAD

**Issue by rajiff** [docker/docker#13843]
I am unable to build docker images having below issues, i notice this is something happening recently (April onwards)

Did looked at similar issues, none of them offered useful solution, hence not sure exactly what is the solution to this problem

Not sure if docker is eating up space or am I short of space

earlier (docker 1.5) i have done this many number of times and i have my production systems running smoothly 

How to reproduce

Create a new AMI instance on AWS and run below command 

	$ docker run hello-world
	Unable to find image 'hello-world:latest' locally
	latest: Pulling from hello-world

	a8219747be10: Pull complete 
	91c95931e552: Already exists 
	hello-world:latest: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.

	Digest: sha256:aa03e5d0d5553b4c3473e89c8619cf79df368babd18681cf5daeb82aab55838d
	Status: Downloaded newer image for hello-world:latest
	FATA[0001] Error response from daemon: Cannot start container af08d47afa459cf73d0c0fd2f325296fb6946d0e97d69a322a7eef0fa4e354bc: [8] System error: write /cgroup/docker/af08d47afa459cf73d0c0fd2f325296fb6946d0e97d69a322a7eef0fa4e354bc/cgroup.procs: no space left on device

Here are the information about AMI and docker

    $ cat /etc/system-release
    Amazon Linux AMI release 2015.03

And uname details

	$ uname -a
	Linux ip-172-xx-xx-xx 3.14.35-28.38.amzn1.x86_64 #1 SMP Wed Mar 11 22:50:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Docker version
	
	$ docker version
	Client version: 1.6.2
	Client API version: 1.18
	Go version (client): go1.3.3
	Git commit (client): 7c8fca2/1.6.2
	OS/Arch (client): linux/amd64
	Server version: 1.6.2
	Server API version: 1.18
	Go version (server): go1.3.3
	Git commit (server): 7c8fca2/1.6.2
	OS/Arch (server): linux/amd64

Docker info
	
	$ docker info
	Containers: 1
	Images: 2
	Storage Driver: devicemapper
	 Pool Name: docker-202:1-264647-pool
	 Pool Blocksize: 65.54 kB
	 Backing Filesystem: extfs
	 Data file: /dev/loop0
	 Metadata file: /dev/loop1
	 Data Space Used: 307.3 MB
	 Data Space Total: 107.4 GB
	 Data Space Available: 28.92 GB
	 Metadata Space Used: 815.1 kB
	 Metadata Space Total: 2.147 GB
	 Metadata Space Available: 2.147 GB
	 Udev Sync Supported: true
	 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
	 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
	 Library Version: 1.02.89-RHEL6 (2014-09-01)
	Execution Driver: native-0.2
	Kernel Version: 3.14.35-28.38.amzn1.x86_64
	Operating System: Amazon Linux AMI 2015.03
	CPUs: 1
	Total Memory: 996.3 MiB
	Name: ip-172-xx-xx-xx
	ID: XXXX:.............<edited>

Thanks for your help

**Comment by cpuguy83** [comment]
Closing since #14386 is the same issue and there are more comments there. Thanks!
