### ISSUE TITLE
Proposal: names and labels in events api

### ISSUE THREAD

**Issue by samsabed** [docker/docker#13845]
It would be good to have the events api endpoint provide the names and labels with the events. For people than encode metadata in the name/label. Otherwise I'd need to do an inspect after receiving an event or have a cache of id(s) to metadata
It looks fairly straightforward to implement  and I can send a PR.

docker version:
docker info:
uname -a:

Provide additional environment details (AWS, VirtualBox, physical, etc.):
List the steps to reproduce the issue:
Describe the results you received:
Describe the results you expected:
Provide additional info you think is important:

**Comment by cpuguy83** [comment]
Can you provide an example of what you think this would look like in the JSON and CLI output?

**Comment by samsabed** [comment]
yes I'm not thinking about the cli, it would get too wide, only the api endpoint.
just adding the Label and Name fields as in inspect. 
e.g..
{
    "status": "create",
    "id": "0f2c4e2d08bc5313eb87b6729e379d31ff631e6bbf4289d49eb9d53fafffe4f5",
    "from": "docker.io/busybox:latest",
    "time": 1433945130,
    "name": "bar_foo",
    "labels": {
        "app": "foo",
        "slot": "6",
        "env": "prod",
        "service": "xyz"
    }
}

**Comment by aanm** [comment]
I'm in favor of this :+1:

**Comment by thaJeztah** [comment]
Also see https://github.com/docker/docker/issues/18164
