### ISSUE TITLE
Feature request: xhyve support

### ISSUE THREAD

**Issue by alisnic** [docker/docker#13841]
> The [xhyve](https://github.com/mist64/xhyve) hypervisor is a port of bhyve to OS X. It is built on top of Hypervisor.framework in OS X 10.10 Yosemite and higher, runs entirely in userspace, and has no other dependencies. It can run vanilla Linux distributions and may gain support for other guest operating systems in the future.

The main benefit of this is that OSX users would not need boot2docker anymore to run Docker, and the performance should be better. But this statement is highly speculative, since I did not make any proper assessment of the technology involved in xhyve.

Thoughts?

**Comment by phemmer** [comment]
> The main benefit of this is that OSX users would not need boot2docker anymore to run Docker

How do you figure? xhyve is still a hypervisor, it still runs a virtual machine.

**Comment by alisnic** [comment]
> How do you figure?

Now that I think of it, you're right. I guess I got carried away in excitement. I'm waiting for native container support in OSX for a long time.

**Comment by unclejack** [comment]
Technically speaking, Docker doesn't support VirtualBox, VMware or Hyper-V when it comes to Linux. It supports Linux and Linux is what can run on those hypervisors.

This is something to be discussed on the boot2docker repository. There's no actionable item here for the Docker project itself.

I'm going to close this issue now. Please feel free to discuss this on the boot2docker repository instead.
