### ISSUE TITLE
netlink_linux type mismatch with go 1.5

### ISSUE THREAD

**Issue by mchasal** [docker/docker#13856]
When performing a build from Master on Power with the latest golang changes, I get the following error during a build:

mchasal@ubuntu1504:~/src/github.com/docker$ AUTO_GOPATH=1 ./hack/make.sh dynbinary

---> Making bundle: dynbinary (in bundles/1.7.0-dev/dynbinary)
github.com/docker/libcontainer/netlink
vendor/src/github.com/docker/libcontainer/netlink/netlink_linux.go:1261: cannot use ifrDataByte(hw[i]) (type int8) as type uint8 in assignment

Adding a typecast to the assignment clears the error. PR forthcoming with that change.

**Comment by thaJeztah** [comment]
@mchasal make sure you create that PR in the right repository. Libnetwork is a "vendored" package; the repository can be found here; https://github.com/docker/libnetwork

**Comment by thaJeztah** [comment]
Ehm, wrong "lib"; libcontainer can be found here; https://github.com/docker/libcontainer :)

**Comment by mchasal** [comment]
Thanks for the repository pointer, I was creating it in the wrong places since it's in the docker tree. 

#dibs and Additional info:

mchasal@ubuntu1504:~/src/github.com/docker$ uname -a
Linux ubuntu1504 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:13 UTC 2015 ppc64le ppc64le ppc64le GNU/Linux

mchasal@ubuntu1504:~/src/github.com/docker$ docker version
Client version: 1.7.0-dev
Client API version: 1.20
Go version (client): devel +70cf735 Tue Jun 2 13:55:40 2015 +0000
Git commit (client): 63b5d5f-dirty
OS/Arch (client): linux/ppc64le
Server version: 1.7.0-dev
Server API version: 1.20
Go version (server): devel +70cf735 Tue Jun 2 13:55:40 2015 +0000
Git commit (server): 63b5d5f-dirty
OS/Arch (server): linux/ppc64le

mchasal@ubuntu1504:~/src/github.com/docker$ docker info
Containers: 19
Images: 19
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 57
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-15-generic
Operating System: Ubuntu 15.04
CPUs: 1
Total Memory: 7.974 GiB
Name: ubuntu1504
ID: DH4G:2YEH:YPCX:RHP4:GY6D:TGDM:CYRK:RYO3:5UTB:2V5X:HXIO:QVMT
WARNING: No swap limit support

**Comment by mchasal** [comment]
PR #625 in libcontainer created with a fix for this.

**Comment by thaJeztah** [comment]
Great, @mchasal. Once that is merged in libcontainer and a new version is tagged, you can create a PR here to update the vendored version of libcontainer. This is done by updating the vendored version in [`hack/vendor.sh`](https://github.com/docker/docker/blob/9e4ee3dea52ec0615f59c729ed972d08732a3edd/hack/vendor.sh#L27), and running that script.

An example of such a PR can be found here; https://github.com/docker/docker/pull/13893

**Comment by unclejack** [comment]
ping @mchasal Is this something you still want to work on?

**Comment by mchasal** [comment]
I'll check again, but I had looked a while ago and thought that it had already been pulled in. Perhaps during the changeover to runc. So I think this is complete.

**Comment by LK4D4** [comment]
Closing. Seems like solved.
