### ISSUE TITLE
Plugins can only use a hardcoded directory - /usr/share/docker/plugins

### ISSUE THREAD

**Issue by tomdee** [docker/docker#13859]
This presents a problem on CoreOS which has /usr mounted read only.

The values is defaulted in pkg/plugins/discovery.go and the pkg/plugins/plugins.go only allows this defaulted value.

ping @mavenugo @calavera

**Comment by calavera** [comment]
I knew it! https://github.com/docker/docker/pull/13514

**Comment by SvenDowideit** [comment]
+1 - plugins need to be much more aware of the Docker daemon's cfg
