### ISSUE TITLE
Docker ps slow to return for 50 containers

### ISSUE THREAD

**Issue by icecrime** [docker/docker#13864]
Feedback received by mail:

> After running for about 2 days, 1.7.0-RC2 takes about 8 seconds to return from docker ps with 50 containers running.

**Comment by jfrazelle** [comment]
ya im seeing if this is the case for our servers

**Comment by jfrazelle** [comment]
ya its not :(

**Comment by icecrime** [comment]
Getting back to the tester for more information: it's not easily reproduced, and `ps` had no significant changes since 1.6.0.

**Comment by cpuguy83** [comment]
@icecrime other than engine removal :trollface:

**Comment by icecrime** [comment]
![image](https://cloud.githubusercontent.com/assets/1564054/8098460/2c0d7df8-0fa5-11e5-99de-3935c96ff05b.png)

**Comment by LK4D4** [comment]
Anything could slow ps, ps is like indicator that something wrong. I think it should be reproducible by hour of docker-stress with right arguments. Maybe our sqlite db grows uncontrollably, who knows...

**Comment by icecrime** [comment]
Removing from milestone until (if) we get more information.

**Comment by unclejack** [comment]
This issue is very hard to look into without the usual information we request: `docker info`, `docker version` and `uname -a`.

There could be multiple causes behind Docker becoming slow and 99% of those have nothing to do with Docker.

**Comment by jfrazelle** [comment]
should we even still keep this open

**Comment by cpuguy83** [comment]
Closing since there isn't anything we can do with this w/o more detailed info.
