### ISSUE TITLE
what is the impact of running with --cap-add SYS_ADMIN --device /dev/fuse

### ISSUE THREAD

**Issue by eyalto** [docker/docker#13875]
Description of problem:

following:
https://github.com/docker/docker/issues/6535
https://github.com/docker/docker/issues/9448
https://github.com/SvenDowideit/docker/commit/e2c3da6e7a40008c6e8c4c8ae2fdfc0f382af0a3

I would like to understand what is the impact (i.e. what other things the root user within the container will be able to do) if I enable both device and capability

I have a docker running dev env for multiple users - I would like to mount a remote shared folder every time a developer opens a new project. I would like to mount sshfs folder in a running docker without stopping it and attaching a volume.

docker version:
Docker version 1.5.0, build a8a31ef

docker info:
Containers: 71
Images: 16
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 158
Execution Driver: native-0.2
Kernel Version: 3.13.0-48-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 48
Total Memory: 62.81 GiB
Name: zegpu2
ID: YEQH:R4KO:NHGX:H6VN:5XHQ:HBBG:MGHV:7E7I:ATMV:RSKU:BRYN:IWKQ
Debug mode (server): false
Debug mode (client): true
Fds: 523
Goroutines: 517
EventsListeners: 0
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker
WARNING: No swap limit support

uname -a:
Linux 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

environment :  Ubuntu 14.04.2 LTS ==>  Physical

**Comment by eyalto** [comment]
Hi its not a but - this is a documentation request

**Comment by cpuguy83** [comment]
Article on CAP_SYS_ADMIN: https://lwn.net/Articles/486306/
If a user has it... they are not contained.

Closing since this is not an issue.
