### ISSUE TITLE
Support setting http url as DOCKER_HOST for docker client

### ISSUE THREAD

**Issue by tnachen** [docker/docker#13871]
Currently docker client requires just a host:port or tcp/unix schemes, but then later just translates this into  http/https later on in api/client.
This is troublesome when you have a HTTP proxy in front of the docker daemon, and it's not a simply host but also has paths such as http://proxy.com/service/test/, and this doesn't pass the Host parsing validation.

**Comment by tnachen** [comment]
docker version:
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 8aae715/1.6.0
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 8aae715/1.6.0
OS/Arch (server): linux/amd64

tnachen@srv2:~$ docker info
Containers: 59
Images: 312
Storage Driver: btrfs
Execution Driver: native-0.2
Kernel Version: 3.10.0-229.1.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 40
Total Memory: 251.7 GiB
Name: srv2.hw.ca1.mesosphere.com
ID: KQUO:TFUX:K5UN:Y3OU:B23L:CDY4:G57X:MHQ5:YXLY:2MK6:MWLL:AH6K
Username: tnachen
Registry: [https://index.docker.io/v1/]

**Comment by calavera** [comment]
Thanks for opening this @tnachen. I could agree with you, the api is http, therefore `http` should be a valid scheme in the host url. If you want to open a pull request for further discussion, I think these are the two spots that need change:

https://github.com/docker/docker/blob/0bfbc6e78823fc2f455b01a02721f17bcbcaecff/api/server/server_linux.go#L47
https://github.com/docker/docker/blob/0bfbc6e78823fc2f455b01a02721f17bcbcaecff/api/server/server_windows.go#L20

**Comment by vdemeester** [comment]
@calavera @tnachen Isn't this client-only ? the ability to do something like :
```bash
$ docker -H http://127.0.0.1:80 info
$ DOCKER_HOST="http://127.0.0.1:80" docker info
```

But yeah it would be cool to be able to run the daemon with ``docker -dD -H https://127.0.0.1:443/`` too. Or even without the ``:80`` or ``:443``.

I'll send a PR for the client part of this, and I'll see with discussion if we implement it on the server part too — so #dibs on this on :wink:.

**Comment by calavera** [comment]
This was fixed by #14304. You can pass now tcp addresses with a full path. Thanks for opening the issue!

**Comment by thaJeztah** [comment]
Looks like https://github.com/docker/docker/pull/14304 added support for paths, but didn't add support for `http(s):` as protocol thought. @vdemeester perhaps you can resurrect that part of your original PR?

**Comment by vdemeester** [comment]
@thaJeztah Not sure it make sense, see https://github.com/docker/docker/issues/14270#issuecomment-116847837. Well it would be just a matter of support ``http(s)`` in ``-H`` flags and such but :stuck_out_tongue:

**Comment by thaJeztah** [comment]
@vdemeester ah! I overlooked that comment. nothing left to do then :+1:
