### ISSUE TITLE
Cannot get OS name in centos 6

### ISSUE THREAD

**Issue by yank1** [docker/docker#13880]
centos 6 do not has file /etc/os-release. So can not get name

**Comment by cpuguy83** [comment]
Are you referring to the centos6 image? Not sure I understand the issue.

**Comment by calavera** [comment]
Fix in progress

**Comment by calavera** [comment]
@cpuguy83 CentOS 6 hosts don't include /etc/os-release, the info is in /etc/redhat-release, just because. #13887 should fix this issue and other similar issues with other derivatives.

**Comment by tiborvass** [comment]
I filed https://bugs.centos.org/view.php?id=8894
