### ISSUE TITLE
Proposal: Add tuning swappiness of container

### ISSUE THREAD

**Issue by ktraghavendra** [docker/docker#13881]
The memory cgroup has swappiness feture (takes 0-100) which can be used to tune swappiness behavior of container. In real world, it helps in improving the performance of highly active container
by reducing the major fault and thus reducing swapping behavior (when we tune it to lower value).

**Comment by ktraghavendra** [comment]
Closing this as per https://github.com/docker/docker/pull/13882. and raising new issue after libcontainer changes merged  as per https://github.com/docker/libcontainer/issues/621.

**Comment by thaJeztah** [comment]
Replaced by https://github.com/docker/docker/issues/13938

**Comment by ktraghavendra** [comment]
will wait for https://github.com/docker/docker/pull/13893 to create a updated vendor patch for libcontainer (if necessary)
