### ISSUE TITLE
Docker build -f command should use case insensitive compare on windows

### ISSUE THREAD

**Issue by yanchenw** [docker/docker#13898]
docker version: 
```
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): windows/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```
docker info:
```
Containers: 38
Images: 239
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 315
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-32-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 2
Total Memory: 6.807 GiB
```

Provide additional environment details: 
Use Docker client command line tool on Windows machine to talk to a Ubuntu Docker host.

List the steps to reproduce the issue:
1. Create a dummy Dockerfile under C:\Package
2. Try to do docker build in that folder:
```
docker build -f "C:\PACKAGE\Dockerfile" "c:\package"
```

Describe the results you received:
Receive error: The Dockerfile (C:\PACKAGE\Dockerfile) must be within the build context (c:\package)

Describe the results you expected:
No error.

Provide additional info you think is important:

 On windows command line, use the following command will fail:

c:\>docker --tlsverify -H tcp://foo:2376 build -t myapp -f "**C:\PACKAGE\Dockerfile**" "**c:\package**"
The Dockerfile (C:\PACKAGE\Dockerfile) must be within the build context (c:\package)

@ahmetalpbalkan

**Comment by ahmetalpbalkan** [comment]
It looks like uppercase C: vs lowercase c: problem although those actually mean the same thing on Windows.

I may get to this soon unless someone else wants to pick up.

**Comment by andyneff** [comment]
I'm getting the (exact, I believe) same problem, I've finally realized its just more confusing in mingw32 where the drive letter is more hidden...

```
$ docker build -t delme -f dock2 .
unable to prepare context: The Dockerfile (m:\src\package\docker\dock2) must be within the build context (.)
```

Using the full path
```bash
#docker build -t delme -f /m/src/package/docker/dock2 /m/src/package/docker
$ docker build -t delme -f `pwd`/dock2 `pwd`
unable to prepare context: The Dockerfile (m:\src\package\docker\dock2) must be
within the build context (m:/src/package/docker)
```
Note: pwd evaluated to  `/m/src/package/docker`, NOT the `m:\src\package\docker` format, but mingw32 converts it to m:/src/package/docker before making the docker call (CreateProcess I'm guessing)

A little creative accounting reveals the TRUE cwd in mingw32 is `m:\src\package\docker` NOT `M:\src\package\docker`, so using `.` or relative paths can NEVER work, unless in cmd where it is `M:`

Or course, if you start cmd from mingw32, then it will be m: and suffer the consequences.

```
$ docker build -t delme -f 'm:\src\package\docker\dock2' 'm:\src\package\docker'
unable to prepare context: The Dockerfile (m:\src\package\docker\dock2) must be within the build context (m:\src\package\docker)
```
Doesn't work... Not 100% sure why.... Its as if the path is always converted to M: somewhere... after relative?

However
```
docker build -t delme -f M:\src\package\docker\dock2 m:\src\package\docker
docker build -t delme -f M:\src\package\docker\dock2 M:\src\package\docker
```
Work

And 
```
docker build -t delme -f M:\src\package\docker\dock2 .
docker build -t delme -f dock2 .
```
Works in cmd.exe only because it's `M:` instead of `m:`

docker version
```
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by duglin** [comment]
ping @jhowardmsft is this still an issue?

**Comment by jhowardmsft** [comment]
@duglin - Probably. I haven't fixed anything client side directly for this, many all my stuff has been on the Windows daemon side. But that's not to say it hasn't been indirectly fixed - this is a very old issue relatively. 

Looks like there's two issues though - one in the client, and one potentially in mingw munging paths. Can't comment about the second one though - I run everything from cmd or PowerShell. If I get a chance, I can look at the first one.

**Comment by jhowardmsft** [comment]
Closing. No longer repros under 1.12 Windows to Linux. 

```
e:\>dir Docker\build\space2
 Volume in drive E is SSD Internal
 Volume Serial Number is 3ADA-E070

 Directory of e:\Docker\build\space2

05/20/2016  03:15 PM    <DIR>          .
05/20/2016  03:15 PM    <DIR>          ..
05/24/2016  02:45 PM             2,019 Dockerfile
05/20/2016  03:15 PM                16 foo bar.txt
               2 File(s)          2,035 bytes
               2 Dir(s)  514,808,651,776 bytes free

e:\>docker build -t space2 --no-cache=true -f e:\DOCKER\build\space2\Dockerfile e:\DOCKER\BuIlD\SpAcE2
Sending build context to Docker daemon 4.608 kB
Step 1 : FROM ubuntu
 ---> 1c9b046c2850
Step 2 : CMD sh
 ---> Running in f4e2afcff98b
 ---> 794ec78cb069
Removing intermediate container f4e2afcff98b
Successfully built 794ec78cb069
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.

e:\>docker version
Client:
 Version:
 API version:  1.24
 Go version:   go1.6
 Git commit:   86a7632-jhoward-JHOWARD-Z420-Dynamic
 Built:        Tue May 24 20:00:47 UTC 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.4
 Git commit:   36af73b
 Built:        Mon Apr 25 16:58:17 2016
 OS/Arch:      linux/amd64

e:\>
```
