### ISSUE TITLE
Using bro IDS to monitor traffic between two containers.

### ISSUE THREAD

**Issue by sbaks0820** [docker/docker#13892]
I want to install bro to monitor network traffic between two containers that are using tcp. Is there a way to access traffice between two containers if I were to run bro from another container? Or is the traffic between two containers only possible if I have access to the `docker0` interface from the host machine?

**Comment by cpuguy83** [comment]
Hello, can you move this to the `docker-user` mailing list, #docker on IRC, or forums.docker.com?

Thanks!

**Comment by sbaks0820** [comment]
I'll do that
