### ISSUE TITLE
Missing environment variables when linking containers, caused by `=` in values

### ISSUE THREAD

**Issue by nonsensery** [docker/docker#13891]
Description of problem:

Environment variables whose values contain one or more `=` characters do not show up in linked containers.

`docker version`:

Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

`docker info`:

Containers: 8
Images: 382
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 398
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 4.0.3-boot2docker
Operating System: Boot2Docker 1.6.2 (TCL 5.4); master : 4534e65 - Wed May 13 21:24:28 UTC 2015
CPUs: 8
Total Memory: 1.957 GiB
Name: boot2docker
ID: UCKV:ES4Y:2UN5:U664:444G:OUPG:ZR7Q:LTXC:X6TA:VE4F:74ZB:F56E
Debug mode (server): true
Debug mode (client): false
Fds: 30
Goroutines: 52
System Time: Thu Jun 11 19:54:57 UTC 2015
EventsListeners: 0
Init SHA1: 7f9c6798b022e64f04d2aff8c75cbf38a2779493
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker

`uname -a`:

Linux boot2docker 4.0.3-boot2docker #1 SMP Wed May 13 20:54:49 UTC 2015 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):

Boot2Docker 1.6.2 running on OSX 10.10.3

How reproducible:

This is pretty easy to reproduce by starting some containers and linking them together.

Steps to Reproduce:

**Step 1**: Start a container with an env variable containing `=`:
```sh
docker run -d --name=other_container \
  -e 'THIS_WORKS'='PIZZA' \
  -e 'THIS_DOES_NOT'='BEER=' \
  busybox sh -c 'while true; do sleep 100; done'
```

**Step 2**: Verify that it has the variables:
```sh
docker exec other_container env | grep THIS_
# => THIS_WORKS=PIZZA
# => THIS_DOES_NOT=BEER=
```

**Step 3**: Start another container that is linked to the first container, and print out the variables it gets:
```sh
docker run \
  --link other_container:other_container \
  busybox env | grep OTHER_CONTAINER_ENV_THIS_
# => OTHER_CONTAINER_ENV_THIS_WORKS=PIZZA
```

Actual Results:

As shown, the environment variable `THIS_WORKS` is available to the second container (as `OTHER_CONTAINER_ENV_THIS_WORKS`), but the variable `THIS_DOES_NOT` is not.

Expected Results:

Both environment variables should be available in the second container (with the `OTHER_CONTAINER_ENV_` prefix).

Additional info:

I've also tried this with `+` and `/` characters in the environment variable values, and those work fine. It's only `=` that causes the variable to be MIA.

This is important to me because I have some Base64-encoded "secrets" that I'm providing via environment variables. Base64-encoded values often end with `=` or `==`.

My current work-around is to use `_` in the environment variable values, and then turn replace those with `=` in my code. This is an ugly hack, but it gets the job done for this specific case.

**Comment by duglin** [comment]
Can you try on the latest version, it works for me:
```
$ docker run \
>   --link other_container:other_container \
>   busybox env 
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=c866aec97a53
OTHER_CONTAINER_NAME=/prickly_yonath/other_container
OTHER_CONTAINER_ENV_THIS_WORKS=PIZZA
OTHER_CONTAINER_ENV_THIS_DOES_NOT=BEER=
```
I'll try to find the PR but I seem to recall this being fix recently

**Comment by duglin** [comment]
here we go, I think this is it: https://github.com/docker/docker/pull/12783

**Comment by duglin** [comment]
Going to close this for now since I'm pretty sure its fixed. If I'm wrong please reopen it.
