### ISSUE TITLE
Can I check a container's deivcemapper device usage just on host?

### ISSUE THREAD

**Issue by allencloud** [docker/docker#13904]
Hi, all

Now I find devicemapper is great when doing disk usage limit. 
And if I enter the container's namespaces to do command `df -h`, I can check the container disk usage like this:

<pre>root@4b5484f6dd0f:/usr/src/myapp# df -h
Filesystem                                                                                      Size  Used Avail Use% Mounted on
/dev/mapper/docker-8:1-131342-4b5484f6dd0fc7505e7f2b4ef2a19a4c98363132f87c0c8bc4f3db0d01ecd468  976M  791M  119M  87% /</pre>

However, if I do not enter the container, how can I check the container's devicemapper device disk usage?

And I also try to enter some specific directory of this container and execute the command `du`, but I think it is not a gracefully way to check device disk usage.

Anything helps.

Thanks.

**Comment by allencloud** [comment]
Now , is it not proper to post an question which is issued to ask for help?
And github docker/issue is  just used to report some real software issues?
If so, I can migrate it to the google groups. @GordonTheTurtle

**Comment by cpuguy83** [comment]
You can certainly run `df -h` from the host to see this as well.
In addition, `docker inspect` will also give you detailed information about the device mapper volume used for the container which you can use to manually inspect.
