### ISSUE TITLE
Get files from container to host

### ISSUE THREAD

**Issue by Z3roCoder** [docker/docker#13909]
First off:
docker version: 
```
Client Version: 1.6.0
Client API Version: 1.18
```
docker info:
```
Containers: 37
Images: 297
Storage Driver: devicemapper
 Pool Name: docker-253:0-133720-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 11.02 GB
 Data Space Total: 107.4 GB
 Data Space Available: 41.12 GB
 Metadata Space Used: 16.51 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.131 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Kernel Version: 3.10.0-229.4.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 1.83 GiB
Name: localhost.localdomain
ID: CF6O:4MAG:N4BV:YTY3:CMCN:3CKJ:5XRF:I4OV:NOJ2:7223:JOTV:V6MO
```
uname -a:
```
Linux localhost.localdomain 3.10.0-229.4.2.el7.x86_64 #1 SMP Wed May 13 10:06:09 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Hello there. I am facing a strange problem here. I am using docker-gitlab ( https://github.com/sameersbn/docker-gitlab )

I have modified the docker-compose.yml and added a volume:
volumes:

(predefined volume)
/srv/docker/logs:/home/git/gitlab/log (note that 'log' folder is generated by gitlab itself - is that the problem?)

After creating the container for gitlab and using docker-compose up to get the container up and running, and doing some actions there is absolutely nothing inside /srv/docker/logs but the log-folder inside of the container is filled with logs.

Is it the problem that the "log"-Folder gets created by gitlab itself, and thus I can't point the volume on it? If yesm is there any workaround so that gitlab writes all logs to /srv/docker/logs without having to install or do anything inside of the image itself?

Edit: Same behaviour using docker run [options] -v /srv/docker/logs:/home/git/gitlab/log gitlab - thus I posted it in here and not docker-compose

**Comment by vdemeester** [comment]
hi @Z3roCoder,

What version of the gitlab image are you running ?
According to the Dockerfile (on the master branch at least), the only declared volumes are 
```
VOLUME ["/home/git/data"]
VOLUME ["/var/log/gitlab"]
```

And reading the [assets/setup/install](https://github.com/sameersbn/docker-gitlab/blob/c2ae9e740495251e7f12a440a5ddfed2272d0844/assets/setup/install) file, it seems the logs are meant to go to the ``/var/log/gitlab``. 

Thus, when you run this image, you should use something like ``-v /srv/docker/logs:/var/log/gitlab``. If the logs are not put in the right place, seems to me it's more a bug of the image than of Docker.

Let me know if that fixes your porblem.

**Comment by unclejack** [comment]
Please keep in mind that this isn't a general support forum.

This is an issue tracker for Docker bugs, features and pull requests. Please take this into account when opening an issue.

This isn't a Docker bug, this is a question which is more appropriate for
1) the forums: https://forums.docker.com/
2) the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user
3) the #docker channel on Freenode.

1) and 2) should be better for longer conversations.
