### ISSUE TITLE
Let "docker build -" respect .dockerignore

### ISSUE THREAD

**Issue by jacobat** [docker/docker#13919]
Currently `docker build .` will respect a `.dockerignore` whereas `tar -cf- . | docker build -` will not. This is confusing to some users as witnessed by https://github.com/docker/docker/issues/10536.

I propose that `docker build -` and `docker build URL` respect `.dockerignore` in the same way to make the behaviour consistent from the users point of view.

/cc @duglin

**Comment by tianon** [comment]
I've said it before (https://github.com/docker/docker/pull/8748#discussion_r19455996), but I'm definitely +1 on the daemon also handling `.dockerignore` appropriately so this isn't just a client-only feature and simply becomes a client optimization tool where implemented.

**Comment by posita** [comment]
Forgive my ignorance, but why not use `tar`'s `--exclude` or `--exclude-from` options? Or does this issue primarily pertain to the behavior inconsistencies among `docker build` invocations? In light of #12886, I'd prefer to see magic files like `.dockerignore` go away. I'd much prefer to see `--exclude` and `--exclude-from` analogies make it into `docker build`.

**Comment by duglin** [comment]
@jacobat I'm going to close this because I think this actually does work the way you want now. I seem to recall that we made it so that .dockerignore will be processed on both the cli and daemon side now.  Let me know if you're not seeing it.

**Comment by posita** [comment]
@duglin, I *think* what @jacobat meant was that the client-side `docker` instance should prevent transmission of those files excluded by `.dockerignore` to the server, so server-side exclusion is probably too late. I might have misunderstood though.

**Comment by duglin** [comment]
perhaps, but I don't see us un-tarring the input just to remove files that the daemon will eventually remove anyway. I think the net result is the same.

**Comment by posita** [comment]
I tend to agree (I haven't changed my stance from this https://github.com/docker/docker/issues/13919#issuecomment-126495353). I just wanted to clarify what I thought was the behavior identified by this issue.

**Comment by jacobat** [comment]
I don't really care where the filtering happens. What's important to me is that I can use the regular unix way of composing things and get the expected result. That is `docker build .` should end up building the same image as `tar cf- . | docker build -`.

I would definitely like to see command line arguments for excluding files as well, but that's a different topic.

**Comment by grefrit** [comment]
Any updates on this? 
I definitely agree with @jacobat about that is `docker build .` should end up building the same image as `tar cf- . | docker build -`. It's much simpler to use `.dockerignore` that manually exclude files from tar
