### ISSUE TITLE
[1.7.0-rc2] Response of GET /containers/(id)/stats?stream=0 has wrong content type

### ISSUE THREAD

**Issue by unguiculus** [docker/docker#13910]
The new one-time stats feature `GET /containers/(id)/stats?stream=0` returns a json response with content type `text/plain; charset=utf-8`. The correct content type should be `application/json`.

**Comment by thaJeztah** [comment]
ping @cpuguy83 :)

**Comment by unguiculus** [comment]
It also returns a chunked response. Not sure if this is correct.

```
200, OK
Date: Fri, 12 Jun 2015 14:12:22 GMT
Transfer-Encoding: chunked
Content-Type: text/plain; charset=utf-8
```

**Comment by thaJeztah** [comment]
^^ (I think)

**Comment by cpuguy83** [comment]
Ok, will take a look.

**Comment by cpuguy83** [comment]
#13911

**Comment by thaJeztah** [comment]
thanks for resolving so quickly @cpuguy83!

**Comment by unguiculus** [comment]
Yeah, thanks a lot. That was real quick.
