### ISSUE TITLE
Proposal: Add tuning swappiness of container

### ISSUE THREAD

**Issue by ktraghavendra** [docker/docker#13938]
The memory cgroup has swappiness feture (takes 0-100) which can be used to tune swappiness behavior of container. In real world, it helps in improving the performance of highly active container
by reducing the major fault and thus reducing swapping behavior (when we tune it to lower value).
corresponding libcontainer changes taken in https://github.com/docker/libcontainer/pull/622

**Comment by unclejack** [comment]
@ktraghavendra Please don't close this issue to open a new one on the same topic. https://github.com/docker/docker/issues/13881 didn't need to be closed and this issue didn't need to be opened.

**Comment by ktraghavendra** [comment]
@unclejack sorry, I had the same doubt and confusion. Thanks for clarification.
waiting for vendor libcontainer update.

**Comment by ktraghavendra** [comment]
will wait for #13893 to create a updated vendor patch for libcontainer (if necessary)

**Comment by cpuguy83** [comment]
PR was merged.

**Comment by ktraghavendra** [comment]
Thanks @cpuguy83 Opened https://github.com/docker/docker/pull/14004

**Comment by cpuguy83** [comment]
Closing since #14004 was merged.
