### ISSUE TITLE
Docker logs fails

### ISSUE THREAD

**Issue by zstarer** [docker/docker#13948]
Hi guys -

Cross post from [here.](https://github.com/docker/swarm/issues/946)

I'm not sure what the cause of this is, but I've tried rebooting the manager, all the slaves, all the containers, and pretty much everything short of creating a new token. I'm on CoreOS.

This happens on every container running in the swarm. I can get the logs by ssh-ing into the host and running 'docker logs $id', so it seems limited to getting logs via the master.

```
$ docker logs $id
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x504b1e]

goroutine 1 [running]:
github.com/docker/docker/engine.(*Env).Get(0x0, 0xd18630, 0x4, 0x0, 0x0)
	/go/src/github.com/docker/docker/engine/env.go:21 +0x21e
github.com/docker/docker/api/client.(*DockerCli).CmdLogs(0xc208064280, 0xc20800a020, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/client/commands.go:1975 +0x6dc
reflect.callMethod(0xc20810cf90, 0xc208151b78)
	/usr/local/go/src/reflect/value.go:605 +0x179
reflect.methodValueCall(0xc20800a020, 0x2, 0x2, 0x1, 0xc20810cf90, 0xc208064301, 0xc20805c360, 0x4, 0xc20802c001, 0x7f13683a37f8, ...)
	/usr/local/go/src/reflect/asm_amd64.s:29 +0x36
github.com/docker/docker/api/client.(*DockerCli).Cmd(0xc208064280, 0xc20800a010, 0x3, 0x3, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/client/cli.go:81 +0x37e
main.main()
	/go/src/github.com/docker/docker/docker/docker.go:138 +0xcc6

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 11 [runnable]:
net/http.(*persistConn).readLoop(0xc20812b8c0)
	/usr/local/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 12 [select]:
net/http.(*persistConn).writeLoop(0xc20812b8c0)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc
```

**Comment by LK4D4** [comment]
ping @vieux @aluzzardi

**Comment by zstarer** [comment]
**Docker Version**
ubuntu@$host:~$ docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: swarm/0.2.0
Go version (server): go1.3.3
Git commit (server): 48fd993
OS/Arch (server): linux/amd64

**Docker Info**
ubuntu@$host:~$ docker info
Containers: 210
Strategy: spread
Filters: affinity, health, constraint, port, dependency
Nodes: 11
 ip-10-0-14-14.ec2.internal: 10.0.14.14:2375
  └ Containers: 24
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 2.318 GiB / 31.46 GiB
 ip-10-0-14-146.ec2.internal: 10.0.14.146:2375
  └ Containers: 8
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 2.367 GiB / 31.46 GiB
 ip-10-0-14-147.ec2.internal: 10.0.14.147:2375
  └ Containers: 9
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 1.465 GiB / 31.46 GiB
 ip-10-0-14-15.ec2.internal: 10.0.14.15:2375
  └ Containers: 29
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 9.375 GiB / 15.69 GiB
 ip-10-0-14-156.ec2.internal: 10.0.14.156:2375
  └ Containers: 26
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 2.637 GiB / 15.69 GiB
 ip-10-0-14-157.ec2.internal: 10.0.14.157:2375
  └ Containers: 14
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 4.004 GiB / 15.69 GiB
 ip-10-0-14-158.ec2.internal: 10.0.14.158:2375
  └ Containers: 15
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 5.078 GiB / 15.69 GiB
 ip-10-0-14-159.ec2.internal: 10.0.14.159:2375
  └ Containers: 25
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 2.539 GiB / 15.69 GiB
 ip-10-0-14-16.ec2.internal: 10.0.14.16:2375
  └ Containers: 10
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 2.416 GiB / 31.46 GiB
 ip-10-0-14-4.ec2.internal: 10.0.14.4:2375
  └ Containers: 41
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 14.31 GiB / 31.46 GiB
 ip-10-0-14-67.ec2.internal: 10.0.14.67:2375
  └ Containers: 9
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 1.367 GiB / 15.69 GiB

**uname -a**
ubuntu@$host:~$ uname -a
Linux ip-10-0-14-89 3.13.0-54-generic #91-Ubuntu SMP Tue May 26 19:15:08 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Calling the swarm (which is on CoreOS) from Ubuntu all on AWS.

-------------------------

Describe the results you received:
'docker logs $id' fails out with an error

Describe the results you expected:
I expected to be able to get my logs. :)

Provide additional info you think is important:
Let me know if you guys need more info.

**Comment by aluzzardi** [comment]
This seems to be the offender:

https://github.com/docker/docker/blob/v1.6.2/api/client/commands.go#L1975
```
env.GetSubEnv("HostConfig").GetSubEnv("LogConfig").Get("Type") != "json-file"
```

This is probably because with `Swarm 0.2` there's no such thing as `LogConfig`, AFAIK.

Even then, I don't think the CLI should crash if there is no `LogConfig` in `HostConfig`.

This seems to have changed in master:
```
c.HostConfig.LogConfig.Type; logType != "json-file" 
```

**Comment by zstarer** [comment]
@aluzzardi it looks like this has been resolved in the newest update..I can get my logs again. :)
