### ISSUE TITLE
1.7: iptables cleanup on shutdown, not start

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#13957]
I noticed the Docker iptables are cleaned up on shutdown and not daemon start.  If you gracefully stop the Docker daemon it will issue something like:

``` -t nat -D DOCKER -p udp -d 0/0 --dport 4500 -j DNAT --to-destination 172.17.0.1:4500 ! -i docker0```

But if you kill Docker or just keep sending enough SIGTERMs (because your impatient like me).  The cleanup doesn't happen.  On the next start new iptables rules are added so you get duplicate rules.  If the container gets a new IP then you have odd rules hanging around.  Anyhow, it's bad, my iptables got all confused.

**Comment by ibuildthecloud** [comment]
Tested against 1.7.0-rc4

**Comment by ibuildthecloud** [comment]
@jfrazelle @LK4D4 This is a regression.  Half of this "bug" exists in 1.6.2 but 1.7 makes it worse.  Docker adds rules to OUTPUT and DOCKER chains.  In 1.6.2 it appears the DOCKER chain is flushed on start.  In 1.7 that doesn't seem to happen.  The DOCKER chain does DNAT for incoming traffic where as the OUTPUT chain just does the hair pin traffic.  Bad rules in the hairpin has very little impact, but bad rules in DOCKER does.

**Comment by mavenugo** [comment]
@ibuildthecloud Yes. your observation is correct. 1.6.2 has the same cleanup issue for OUTPUT. But the bridge driver does cleanup the DOCKER chain on start `RemoveExistingChain`. We have to reintroduce this in the new bridge driver. will fix this.

**Comment by icecrime** [comment]
Closed by docker/libnetwork#301.
