### ISSUE TITLE
DOCKER_TLS_VERIFY env var doesn't work in master

### ISSUE THREAD

**Issue by mitchcapper** [docker/docker#13964]
setting DOCKER_TLS_VERIFY=1 no longer works in master.  The command line flag works but env var does not.  Will try to track down where it broke, the code in flags.go hasn't changed so I am not yet sure why.
Client version: 1.7.0-dev
Client API version: 1.20
Go version (client): go1.4.2
Git commit (client): 6a7a757
OS/Arch (client): linux/amd64
Server version: 1.7.0-dev
Server API version: 1.20
Go version (server): go1.4.2
Git commit (server): 6a7a757
OS/Arch (server): linux/amd64

Working command line arg:
docker@testhost:~$ docker --tlsverify
Could not read CA certificate /home/docker/.docker/ca.pem: open /home/docker/.docker/ca.pem: no such file or directory

setting the ENV:
docker@testhost:~$ export DOCKER_TLS_VERIFY=1
docker@testhost:~$ env | grep -i DOCKER_TLS
DOCKER_TLS_VERIFY=1

env var does not work docker does not error:
docker@testhost:~$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

doesn't work in windows or linux.

**Comment by cpuguy83** [comment]
Why do you think it's not working?
If it wasn't working you wouldn't be getting `CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES`

**Comment by phemmer** [comment]
@cpuguy83 he's saying it's not enforcing the certificate check. It *shouldn't* be showing that `CONTAINER ID IMAGE...` line.

**Comment by mitchcapper** [comment]
Sorry I was giving an example against a docker host WITHOUT tls enabled on the daemon.  So you see the correct behavior would be the error like with docker --tlsverify  is called it should complain about the missing certs.  

Here is an example against a host with tlsverify required:
PS C:\> docker ps
Get http://dockertest:1234/v1.20/containers/json: malformed HTTP response "\x15\x03\x01\x00\x02\x02". Are you try
ing to connect to a TLS-enabled daemon without TLS?
PS C:\> docker --tlsverify ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS
NAMES

**Comment by mitchcapper** [comment]
I will try to bisect this soon, I found this a few weeks ago and checked in the channel if anyone had any ideas but was hoping to have the time to find and patch it myself, just been very busy.

**Comment by cpuguy83** [comment]
Confirmed, working on a fix.
Adding to 1.7 milestone.

**Comment by cpuguy83** [comment]
Removed 1.7 milestone b/c this isn't an issue on 1.7

**Comment by tiborvass** [comment]
@mitchcapper thank you so much for testing master, we need to come up with badges or achievements or some sort of recognition! /cc @crosbymichael @spf13 @theadactyl
