### ISSUE TITLE
Warning message about br_netfilter

### ISSUE THREAD

**Issue by mdavranche** [docker/docker#13969]
On vendor/src/github.com/docker/libnetwork/drivers/bridge/bridge.go, we try to load br_netfilter module. But this option can be enabled or disabled, but not it can not be used as module (see net/Kconfig in the Linux kernel, or try to specify "CONFIG_BRIDGE_NETFILTER=m" in your Linux kernel .config file, it will be changed to "CONFIG_BRIDGE_NETFILTER=y").

That leads to 2 things:
- The important one, we do not really check if br_netfilter is enabled or not,
- The cosmetic one, we have a false warning while launching the docker daemon.

docker version
Client version: 1.7.0-dev
Client API version: 1.20
Go version (client): go1.4.2
Git commit (client): 55bdb51-dirty
OS/Arch (client): linux/amd64
Server version: 1.7.0-dev
Server API version: 1.20
Go version (server): go1.4.2
Git commit (server): 55bdb51-dirty
OS/Arch (server): linux/amd64

docker info
Containers: 1
Images: 50
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 52
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 4
Total Memory: 15.62 GiB
Name: webm215.cluster016.ha.ovh.net
ID: JYYY:LCE2:GSEK:DLMW:DJIX:TDA5:RKVP:RINU:CUPW:YSV2:R5QU:GGFG

uname -a
Linux webm215.cluster016.ha.ovh.net 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux

**Comment by coolljt0725** [comment]
Is #13292  what you want?

**Comment by mdavranche** [comment]
Yes it is!
So now, we just have to remove the module load attempt: See pull request #13981.

**Comment by mdavranche** [comment]
See pull request #13981: will be applied in docker/libnetwork.
