### ISSUE TITLE
Permission denied on chowned directories

### ISSUE THREAD

**Issue by ginoledesma** [docker/docker#13974]
This seems to be related to, if not exactly, https://github.com/docker/docker/issues/783 and https://github.com/docker/docker/issues/6047

Case 1
------

This is how I first stumbled into the issue — inherited containers setting explicit permissions on a common directory.

A.Dockerfile
```
FROM ubuntu:trusty

RUN groupadd app-group
RUN useradd app-user -g app-group

RUN mkdir -p /opt/shared/dir1 /opt/shared/dir2 /opt/shared/dir3
RUN chown -R app-user:app-group /opt/shared
RUN chmod -R 770 /opt/shared
```

B.Dockerfile
```
FROM a

RUN groupadd dev-group
RUN useradd dev-user -g dev-group

RUN mkdir /opt/shared/dev-group
RUN chown -R dev-user /opt/shared
RUN chmod -R 770 /opt/shared
```

```bash
$ docker build -t a -f A.Dockerfile .
$ docker build -t b -f B.Dockerfile .
$ docker run -u dev-user -it b /bin/bash -c "ls -lha /opt/shared"
ls: cannot access /opt/shared/dir1: Permission denied
ls: cannot access /opt/shared/dir3: Permission denied
ls: cannot access /opt/shared/dir2: Permission denied
ls: cannot access /opt/shared/dev-group: Permission denied
total 8.0K
drwxrwx--- 20 dev-user app-group 4.0K Jun 16 18:06 .
drwxr-xr-x  8 root     root      4.0K Jun 16 18:06 ..
d?????????  ? ?        ?            ?            ? dev-group
d?????????  ? ?        ?            ?            ? dir1
d?????????  ? ?        ?            ?            ? dir2
d?????????  ? ?        ?            ?            ? dir3
```

Case 2
------

The Dockerfiles above can be compacted into the one to replicate the issue:

C.Dockerfile
```
FROM ubuntu:trusty

RUN groupadd app-group
RUN groupadd dev-group
RUN useradd app-user -g app-group
RUN useradd dev-user -g dev-group

RUN mkdir -p /opt/shared/dir1 /opt/shared/dir2 /opt/shared/dir3
RUN chown -R app-user:app-group /opt/shared
RUN chmod -R 770 /opt/shared
RUN chown -R dev-user:dev-group /opt/shared
```

```bash
$ docker build -t c -f C.Dockerfile .
$ docker run -u dev-user -it c /bin/bash -c "ls -lha /opt/shared"
ls: cannot access /opt/shared/dir1: Permission denied
ls: cannot access /opt/shared/dir3: Permission denied
ls: cannot access /opt/shared/dir2: Permission denied
total 8.0K
drwxrwx--- 14 dev-user dev-group 4.0K Jun 16 17:41 .
drwxr-xr-x  6 root     root      4.0K Jun 16 17:41 ..
d?????????  ? ?        ?            ?            ? dir1
d?????????  ? ?        ?            ?            ? dir2
d?????????  ? ?        ?            ?            ? dir3
```

Additional data point:

If the new user shares the same group as the parent, the issue doesn't manifest itself, for example:

```
RUN useradd dev-user -g dev-group -G app-group
```

regardless of whether chown/chgrp changes the username, group, or both username and group.

I can replicate this issue in Docker 1.4.0 through Docker 1.6.2.

```bash
$ docker -v 
Docker version 1.6.2, build 7c8fca2

$ docker info
Containers: 80
Images: 149
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 309
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 4.0.3-boot2docker
Operating System: Boot2Docker 1.6.2 (TCL 5.4); master : 4534e65 - Wed May 13 21:24:28 UTC 2015
CPUs: 4
Total Memory: 1.957 GiB
Name: boot2docker
ID: P6OK:TBN4:V2SO:5BEK:JGDX:AYHU:E764:CRXI:6WOQ:5IXE:UZDY:CO5U
Debug mode (server): true
Debug mode (client): false
Fds: 12
Goroutines: 17
System Time: Tue Jun 16 18:10:42 UTC 2015
EventsListeners: 0
Init SHA1: 7f9c6798b022e64f04d2aff8c75cbf38a2779493
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
```

**Comment by ginoledesma** [comment]
@GordonTheTurtle, what's the etiquette on commenting/reopening issues that have already been closed?

**Comment by thaJeztah** [comment]
I think it's okay in this case to open a new issue, because the old ones already have a long conversation, which doesn't really help :)

**Comment by thaJeztah** [comment]
This could actually be a duplicate of https://github.com/docker/docker/issues/13823 and https://github.com/docker/docker/issues/12745, which should be solved by https://github.com/docker/docker/pull/13941 (or https://github.com/docker/docker/issues/13823#issuecomment-110693592)

/cc @unclejack

**Comment by cyphar** [comment]
IIRC this is an AUFS issue -- chown of directories in AUFS layers is broken.

**Comment by cpuguy83** [comment]
@cyphar That's fixed when dirperm1 is enabled, which also requires a newer version of aufs.
@ginoledesma can you make sure you have an update to date version of AUFS with dirperm1 enabled?

**Comment by ginoledesma** [comment]
@cpuguy83 I've tested against Docker 1.7.0 with Kernel 4.0.5 and [AUFS@a8c8a84](https://github.com/sfjro/aufs4-standalone/commit/a8c8a849e236d7f7fa121c8344899a796ccf7b8f).

However, I can't seem to replicate the issue using a Linux box with a vanilla kernel + AUFS toolset outside outside of Docker/LXC. I've tried mimicking the steps that Docker performs as specified in [driver/aufs/aufs.go](https://github.com/docker/docker/blob/master/daemon/graphdriver/aufs/aufs.go#L426-481):

```
# First Layer
mount -t aufs -o br:/rw_layer=rw:/layer_3=ro+wh,dio,xino=/dev/shm/aufs.xino,dirperm1 /aufs-root
# Subsequent layers (from "leaf" to "root")
mount -t aufs -o append:/layer_2=ro+wh,remount /aufs-root
mount -t aufs -o append:/layer_1=ro+wh,remount /aufs-root
```

The mounted filesystem in /aufs-root shows the proper user/permission and the user has appropriate access as well.

I'm still trying to hunt down where the breakage is. I'm hoping that the MsRemount flag for Go's mount() call translates to -o remount. Still more experimenting to be done.

**Comment by ginoledesma** [comment]
I'm going to try testing against Docker built with the fix in 6578ad9.

**Comment by ginoledesma** [comment]
Preliminary testing with Docker 1.7.0 + https://github.com/docker/docker/commit/6578ad90c307c5500a7998819743be88f63ef2b3 doesn't show it's fixed

**Comment by ginoledesma** [comment]
OK, I can confirm that Docker 1.7.0 @ https://github.com/docker/docker/commit/6578ad90c307c5500a7998819743be88f63ef2b3 fixes this problem. Thanks!

**Comment by thaJeztah** [comment]
Thanks for reporting back, @ginoledesma and glad to hear it's resolved!
