### ISSUE TITLE
move --net option from network mode to actual CNM managed network

### ISSUE THREAD

**Issue by mavenugo** [docker/docker#13977]
Based on the discussions from #13441 am opening this enhancement issue to gather feedback and opinion from interested folks for deprecating --net as a network mode and replace it with `network` as defined by libnetwork CNM.

**Comment by squaremo** [comment]
I am in favour of changing the meaning of `--net` to be "use the priorly constructed network named here", where `container:...` has a special meaning; and `"bridge"`, "`none"` and `"host"` are reserved for the singleton networks that do what Docker <1.7 would have done given those values.

By way of example,

    docker network create -d bridge anotherbridge
    docker run --net=anotherbridge -ti ubuntu

This has the advantages of most likely working with existing tooling, which won't have to learn a new option, and seems to be unsurprising and obvious to people. The implementation of libnetwork, and initial integrations, certainly suggest to me that's where things were headed.

**Comment by erikh** [comment]
I think separate options for mode and network are probably best. As much as `--net` sounds alluring, I think a separate flag would be far less surprising, especially for shell programs that drive docker.

**Comment by squaremo** [comment]
@erikh Could you give a quick example of how it would end up being surprising?

**Comment by erikh** [comment]
I think `docker network create $x` where x is one of the standard network options would be particularly confusing.

Even if that is prevented, we still have an option that has different semantics depending on which arguments you pass to it. I used to spend a lot of time in Perl, so I guess I’ve been burned. :)

**Comment by squaremo** [comment]
> Even if that is prevented, we still have an option that has different semantics depending on which arguments you pass to it.

I see what you mean here; although I think treating the special cases as a "default configuration" makes some sense if you squint.

Also, I'd argue that having two different, overlapping mechanisms (`docker run --net=bridge ...` v `docker run --use-network=whatever ...` or similar) is at least as confusing in the other direction.

**Comment by squaremo** [comment]
I suggest we continue discussion at PR #14143

**Comment by LK4D4** [comment]
This was implemented.
