### ISSUE TITLE
Expose the CPU cgroup realtime options to the run CLI

### ISSUE THREAD

**Issue by Lawouach** [docker/docker#13983]
Hi all,

I have an application that calls the sched_setscheduler system call [1]. This requires that I set the followings (assuming a CentOS 7 for example):

$ C=$(docker run ...)
$ echo 950000 > /sys/fs/cgroup/cpu/system.slice/cpu.rt_runtime_us
$ echo 950000 > /sys/fs/cgroup/cpu/system.slice/docker-$C.scope/cpu.rt_runtime_us

Unlike cpu.shares, this cannot be done directly via the docker CLI (as of 1.6.2) which is a bit of an issue because my process fails when it calls sched_setscheduler as I didn't get a chance to set the appropriate system values. We can't rely on the fact the parent cgroup has the appropriate value since the kernel clearly states that children cgroups will always get initialized to 0 anyhow [2]

> By default all bandwidth is assigned to the root group and new groups get the period from /proc/sys/kernel/sched_rt_period_us and a run time of 0.

Browsing the code, I can see some other options have been added [3] but not the ones regarding real-time scheduling.

However, looking at the libcontainer's code, I can see the underlying code is already there [4]. So, what's lacking is to expose them from the docker interface.

Is there a chance this could be added to the CLI as well? This would make using docker and real-time scheduling much friendlier.

Thanks,

[1] http://man7.org/linux/man-pages/man2/sched_setscheduler.2.html
[2] http://lxr.free-electrons.com/source/Documentation/scheduler/sched-rt-group.txt?v=3.10
[3] https://github.com/docker/docker/blob/master/runconfig/parse.go#L70
[4] https://github.com/docker/docker/blob/04c6f09fbdf60c7765cc4cb78883faaa9d971fa5/vendor/src/github.com/docker/libcontainer/cgroups/fs/cpu.go#L54

**Comment by cpuguy83** [comment]
dup of #10459 which was closed.

You can use --cgroup-parent and set these.

**Comment by Lawouach** [comment]
Hello @cpuguy83,

I don't think that fixes it. Like I said, when you create a cgroup, the kernel will always set the cpu.rt_runtime_us to 0. See [1].

> By default all bandwidth is assigned to the root group and new groups get the period from /proc/sys/kernel/sched_rt_period_us and a run time of 0.

And in fact, I have tried using --cgroup-parent as you suggest and cpu.rt_runtime_us was being set to 0 anyhow.

For instance, on a CentOS 7

```
$ echo 950000 > /sys/fs/cgroup/cpu/system.slice/cpu.rt_runtime_us
$ docker run --rm --cap-add=SYS_NICE --cgroup-parent=system.slice -it ubuntu bash
# python3
>>> import os 
>>> os.sched_setscheduler(os.getpid(), os.SCHED_FIFO, os.sched_param(2))"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
PermissionError: [Errno 1] Operation not permitted
```

Indeed since:
```
$ cat /sys/fs/cgroup/cpu/system.slice/system.slice-<DOCKER_ID>.scope/cpu.rt_runtime_us
0
```

Now let's change that value to give some realtime share to that container:

```
$ echo 950000 > /sys/fs/cgroup/cpu/system.slice/system.slice-<DOCKER_ID>.scope/cpu.rt_runtime_us
```

And sure enough

```
# python3
>>> import os 
>>> os.sched_setscheduler(os.getpid(), os.SCHED_FIFO, os.sched_param(2))"
```

Maybe, I'm missing something though.



[1] http://lxr.free-electrons.com/source/Documentation/scheduler/sched-rt-group.txt?v=3.10

**Comment by Lawouach** [comment]
Is it possible that could be evaluated again @cpuguy83?

Thanks.

**Comment by cpuguy83** [comment]
After testing, you cannot use cgroup parent for this currently since the container is getting a default value of 0 in it's cgroup regardless of what the parent has set.

**Comment by cjschroeder** [comment]
Where does this currently stand?

**Comment by ivotron** [comment]
I'm curious about the motivation behind the call to `sched_setscheduler`. Unless I'm misunderstanding the docs [[1]], the kernel uses RT scheduling (95% RT / 5% not RT), even if `CONFIG_RT_GROUP_SCHED` is not enabled, which means that within the root group, the 95% assigned to it is scheduled using CFS, which has the ability to set quotas and periods. Thus, [`cpu-quota`/`cpu-period` [[2]] might be enough for the purposes of OP. Or is it more of an issue of not being able to conditionally call `sched_setscheduler` within the app?

[1]: https://www.kernel.org/doc/Documentation/scheduler/sched-rt-group.txt
[2]: https://docs.docker.com/reference/run/#runtime-constraints-on-cpu-and-memory

**Comment by Lawouach** [comment]
Maybe I'm misreading it but, it wouldn't be enough to set the bandwidth. Indeed, you would still need to  allocated RT shares to the group:

> By default all bandwidth is assigned to the root group and new groups get the
period from /proc/sys/kernel/sched_rt_period_us and a run time of 0. If you
want to assign bandwidth to another group, reduce the root group's bandwidth
and assign some or all of the difference to another group.

As you say, cpu-quote/cpu-period are useful but you still need to allocate RT period to the group anyway.

**Comment by ivotron** [comment]
I was wrong in assuming that the RT allocation on the root group would propagate to any children (as with other cgroups options). So you're right, it has to be reduced from the root and assigned to others, if they need to use the RT scheduler.

However, I think that cpu-quota/cpu-period serve the same purpose without having to use the RT scheduler (or change `cpu.rt_runtime_us`). After reading the red hat docs on this [[1]] and experimenting myself, I think this is the case. From the docs:

> The RT scheduler works similar to the ceiling enforcement control of the CFS (for more information, refer to Section 3.2.1, “CFS Tunable Parameters”) but limits CPU access to real-time tasks only

The main difference is that in order for a task to get affected by `cpu.rt_*` options, it has to explicitly use the RT scheduler (as you show via your python example).

[1]: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Resource_Management_Guide/sect-rt_options.html

**Comment by neuhausler** [comment]
Any update on this one? I'm running a Docker container on a network-switch. To interact with the ASIC I use OpenNSL which wants to change interrupt priorities. To get it working I currently manually change the cgroup settings, similar as described above:

    $ echo 950000 > ./cgroup/cpu/docker/cpu.rt_runtime_us 
    $ echo 950000 > ./cgroup/cpu/docker/CONTAINER-ID/cpu.rt_runtime_us

Obviously it would be nice to get this done via the docker cli.

**Comment by thaJeztah** [comment]
@neuhausler I don't think someone is working on this, but we always welcome PRs :innocent: :heart:

**Comment by coolljt0725** [comment]
@thaJeztah  I’m working on this

**Comment by thaJeztah** [comment]
Thanks @coolljt0725!

**Comment by neuhausler** [comment]
@coolljt0725 any thoughts about timeframe, when that function will be implemented and available in docker?

**Comment by justincormack** [comment]
Hi, can you look at this PR and see if it supports your use case? https://github.com/docker/docker/pull/23430

**Comment by icecrime** [comment]
Tentatively closing as the issue seems to be resolved: please let me know if it needs reopening! Thanks.
