### ISSUE TITLE
Initialize volumes when mounted to a host directory

### ISSUE THREAD

**Issue by omribahumi** [docker/docker#13984]
According to the [documentation](https://docs.docker.com/userguide/dockervolumes/#data-volumes), new volumes should be initialized with the contents of the base image in the volume location.

This indeed works when running `docker -v /path/inside/container ...`, but not when running `docker -v /path/on/host:/path/inside/container ...`.

The documentation doesn't mention there should be a different behavior, so we should either:
1. Update the documentation to mention that the behavior is different when the volume is bound to a host directory
2. Find a way to initialize the volume when binding it to a host directory. Perhaps if the host directory does not initially exist, or with an extra `docker` flag?

**Comment by cpuguy83** [comment]
We really don't want to do anything to user specified paths.
So this should just be a doc update.

Thanks!
