### ISSUE TITLE
docker-py failing pretty often on CI

### ISSUE THREAD

**Issue by LK4D4** [docker/docker#13996]
Test is `TestRemoveLink`.
https://github.com/docker/docker-py/blob/master/tests/integration_test.py#L930
I think for our integration-cli it looks like:
```
func (s *DockerSuite) TestLinkRm(c *check.C) {
	dockerCmd(c, "run", "-d", "--name", "first", "busybox", "top")
	dockerCmd(c, "run", "-d", "--name", "second", "--link=first:mylink", "busybox", "top")
	dockerCmd(c, "rm", "--link", "second/mylink")
}
```
I think it wasn't failing so often before.
ping @tiborvass for stacktrace

**Comment by cpuguy83** [comment]
This was fixed, closing.
