### ISSUE TITLE
Detached container is not running

### ISSUE THREAD

**Issue by chouclee** [docker/docker#14005]
`docker run -d chouclee/devbox-alpha-0.0.6`
I could see the returned container id.
But then `docker ps` told me that there was no running container.
I checked with `docker inspect id`, found the `Running` state was `false`.

Everything was normal before I changed to this docker image. Any hint of the cause?
`$ docker version `
`Client version: 1.6.2`
`Client API version: 1.18`
`Go version (client): go1.4.2`
`Git commit (client): 7c8fca2`
`OS/Arch (client): darwin/amd64`
`Server version: 1.6.2`
`Server API version: 1.18`
`Go version (server): go1.4.2`
`Git commit (server): 7c8fca2`
`OS/Arch (server): linux/amd64`

`$ docker info`
`Containers: 20`
`Images: 49`
`Storage Driver: aufs`
` Root Dir: /mnt/sda1/var/lib/docker/aufs`
` Backing Filesystem: extfs`
` Dirs: 89`
` Dirperm1 Supported: true`
`Execution Driver: native-0.2`
`Kernel Version: 4.0.3-boot2docker`
`Operating System: Boot2Docker 1.6.2 (TCL 5.4); master : 4534e65 - Wed May 13 21:24:28 UTC 2015`
`CPUs: 1`
`Total Memory: 998.1 MiB`
`Name: dev-test`
`ID: ZFGH:2R2M:DVEN:DZEL:BIKI:OLNV:RL6I:LZNA:UHHO:ZDD2:4GZ2:JBQ4`
`Debug mode (server): true`
`Debug mode (client): false`
`Fds: 11`
`Goroutines: 17`
`System Time: Thu Jun 18 07:39:03 UTC 2015`
`EventsListeners: 0`
`Init SHA1: 7f9c6798b022e64f04d2aff8c75cbf38a2779493`
`Init Path: /usr/local/bin/docker`
`Docker Root Dir: /mnt/sda1/var/lib/docker`
`Username: chouclee`
`Registry: [https://index.docker.io/v1/]`
`Labels:`
` provider=virtualbox`

**Comment by duglin** [comment]
try running w/o the `-d` and see if it does anything. I suspect there's no process being run or its setup to return right away.

**Comment by cpuguy83** [comment]
Closing since this is not a docker issue.
For support see #docker on IRC, forums.docker.com, or the docker-user mailing list.

Thanks!

**Comment by chouclee** [comment]
Hi @duglin, w/o `-d` it does nothing. Only adding `-i` I could see containers with `docker ps`

**Comment by chouclee** [comment]
BTW it's RUDE just closing other's issue even without asking.

**Comment by cpuguy83** [comment]
@chouclee I read the issue. This is not a docker issue. As I said come on IRC and I am happy to help.

**Comment by duglin** [comment]
@chouclee that probably means that the process being run expects stdin to be open, which `-d` won't do. Perhaps you need to define a different cmd for it to run?

**Comment by chouclee** [comment]
@duglin  I think you are right. Two images are different and one of them has Supervisor installed.

**Comment by chouclee** [comment]
@cpuguy83 For users, it is sometimes hard to figure out it's a 'software bug' or user caused 'bug'. Anyway, Thanks.
