### ISSUE TITLE
Remote API version for Docker 1.5 and 1.6?

### ISSUE THREAD

**Issue by fbuchinger** [docker/docker#14008]
How can I find out the remote API version supported in a Docker release without actually installing the release? I want to find out the Remote API versions supported in Docker 1.5 and 1.6. 

When I click the on "Version 1.5" in the Version Dropdown of the [Docker remote API Page] (https://docs.docker.com/v1.6/reference/api/docker_remote_api_v1.18/), I am taken to the Remote API Version 1.15 page, although Docker 1.5 seems to [support Remote API Version 1.18](https://github.com/docker/docker/issues/12942#issuecomment-98436238).

Changelogs or VERSION files don't give any hint either.

**Comment by fbuchinger** [comment]
Steps to reproduce:
1. Open [Docker Remote API Page 1.18](https://docs.docker.com/v1.6/reference/api/docker_remote_api_v1.18/) (most recent version)
2. click on "version 1.5" in the version dropdown

expected behaviour: pages takes me to the remote api documentation/version coming with Docker 1.5
actual behaviour: "page not found" error shown, cannot find out about the remote api version in Docker 1.5

My Docker environment (not relevant for my problem, just for making peace with GordonTheTurtle):
```
$ docker version
Client version: 1.6.1
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 97cd073
OS/Arch (client): windows/amd64
Server version: 1.6.1
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 97cd073
OS/Arch (server): linux/amd64

fbu@NB000498 ~
$ docker info
Containers: 20
Images: 121
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 161
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 4.0.2-boot2docker
Operating System: Boot2Docker 1.6.1 (TCL 5.4); master : 43209d4 - Thu May  7 22:
06:28 UTC 2015
CPUs: 4
Total Memory: 1.957 GiB
Name: boot2docker
ID: BDEV:UIJY:5W3S:3Z52:YJ57:RZ26:EIUV:RN6B:RXTY:CNSI:OO64:AL36
Debug mode (server): true
Debug mode (client): false
Fds: 11
Goroutines: 16
System Time: Thu Jun 18 11:24:23 UTC 2015
EventsListeners: 0
Init SHA1: 2dabfc43e5f856a0712787a6ff78ceaf791cc9e7
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker

fbu@NB000498 ~
$ uname -a
MINGW32_NT-6.1 NB000498 1.0.12(0.46/3/2) 2012-07-05 14:56 i686 unknown
```

**Comment by thaJeztah** [comment]
Thanks for reporting, there are indeed some issues with that drop down. The documentation will very soon be replaced by a new theme/skin. (Which is a guarantee for new bugs, so please report!).

In addition, we've discussed adding a Docker-version/API-version matrix to make finding this more easy.

**Comment by dchen1107** [comment]
subscribe me.

**Comment by cpuguy83** [comment]
drop down is gone, but ultimately still difficult to tell what API version maps to an engine version.

**Comment by tedyoung** [comment]
Looks like a matrix/table was added at some point to https://docs.docker.com/engine/reference/api/docker_remote_api/ so this issue can be closed.

**Comment by cpuguy83** [comment]
Thanks!
