### ISSUE TITLE
[PROPOSAL] allow passing signals between containers (`--signals-to`)

### ISSUE THREAD

**Issue by rysiekpl** [docker/docker#14009]
I have a `logrotate_cont` container, and an `nginx_cont` container; `nginx` running in the latter needs to be signalled by `logrotate` to re-open its logfiles. Currently, there is no sane way of doing this, save from giving the `logrotate_cont` container docker API acccess (which is not a good idea).

So here's an idea: just as files and ports can be linked/shared between containers, it would be useful to be able to make container A able to send signals to container B.

I propose a `signals-to` command-line parameter.

Why not `--signals-from`? Because we usually know where we want to send the signal, not necessarily who/what is going to send it (i.e. `nginx` running in my `nginx_cont` container has a set PID; `logrotate`'s PID changes with each run).

The parameter would take one argument:
`<container_id>(:<pid_or_process_name>(:<comma_separated_signals>))`

So in my use-case I could use `--signals-to nginx_cont`, or if I want to be much more specific (and safe): `--signals-to nginx_cont:nginx:USR1`.

Or, if I wanted container A to send specific signals (say, `USR1` and `USR2` only) to any PID in container B: `--signals-to cont_b::USR1,USR1`

Question is, of course, if this is actually doable?

**Comment by cpuguy83** [comment]
In this case I would say you should just use `--pid=host` so you can see the nginx in the process tree.

Closing since this is not really something we can do w/o sharing a pid namespace, which has been rejected in the past, and is completely possible by using the host's pid namespace.

**Comment by rysiekpl** [comment]
For reference, it hasn't been rejected as a whole, see #10163, and [this pull request](https://github.com/docker/docker/pull/13453).

Also, quoting the docker documentation: "--pid=host Set the PID mode for the container host: use the host's PID namespace inside the container. Note: the host mode gives the container full access to local PID and is therefore considered insecure."

But yes, `--pid=<container>` makes more sense (even if it gives a bit less fine-grained control, I guess).
