### ISSUE TITLE
Docker 1.6 not mount shared folder in Ubuntu cloud

### ISSUE THREAD

**Issue by hongquan** [docker/docker#14001]
The issue is originally reported here: https://meta.discourse.org/t/shared-folder-not-mounted-in-docker-container/30077 (I'm using Docker to deploy Discourse).

More info:

```
$ docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

$ docker info
Containers: 1
Images: 13
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 15
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.5.0-52-generic
Operating System: Ubuntu precise (12.04.4 LTS)
CPUs: 8
Total Memory: 31.38 GiB
Name: prodhk
ID: 4YHL:Z2JQ:OA4M:754G:WUYA:W5ZW:KZZU:L4FH:KRDW:HVQT:P77X:G4TF

$ docker images
REPOSITORY             TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
local_discourse/app    latest              6a3adde35fe5        3 days ago          1.773 GB
samsaffron/discourse   1.0.12              2285ff53ab18        2 weeks ago         1.217 GB
samsaffron/discourse   1.0.11              ef8d4f405f84        9 weeks ago         1.167 GB
```

The permission detail of the folder in host which we want to mount:

```
$ ll -h /var/discourse/shared/standalone
total 40K
drwxr-xr-x 10 root       root      4.0K Mei  28 02:45 ./
drwxr-xr-x  3 root       root      4.0K Mei  28 01:47 ../
drwxr-xr-x  2 banana_root  www-data  4.0K Mei  28 01:47 backups/
drwxr-xr-x  4 root       root      4.0K Mei  28 01:47 log/
drwxr-xr-x  2 messagebus ssh       4.0K Mei  28 01:47 postgres_backup/
drwx------ 15 messagebus ssh       4.0K Jun  17 00:01 postgres_data/
drwxrwxr-x  3 messagebus ssh       4.0K Jun  17 00:01 postgres_run/
drwxr-xr-x  2 sshd       bluetooth 4.0K Jun  17 22:36 redis_data/
drwxr-xr-x  4 root       root      4.0K Mei  28 02:45 state/
drwxr-xr-x  3 banana_root  www-data  4.0K Mei  28 02:45 uploads/
```

When I launch the container, I run the Discourse-provided command `./launch start app`, under user `banana_dev`, from this folder:

```
$ ll -h
total 76K
drwxr-xr-x 11 banana_dev banana_dev 4.0K Jun  16 23:47 ./
drwxrwxr-x  3 banana_dev banana_dev 4.0K Jun  16 04:20 ../
drwxrwxr-x  2 banana_dev banana_dev 4.0K Mei  28 01:29 bin/
drwxrwxr-x  2 banana_dev banana_dev 4.0K Jun  14 21:32 cids/
drwxrwxr-x  2 banana_dev banana_dev 4.0K Jun  16 05:16 containers/
drwxrwxr-x  8 banana_dev banana_dev 4.0K Mei  28 01:29 .git/
-rw-rw-r--  1 banana_dev banana_dev   83 Mei  28 01:29 .gitignore
drwxrwxr-x 14 banana_dev banana_dev 4.0K Mei  28 01:29 image/
-rwxrwxr-x  1 banana_dev banana_dev  17K Mei  28 01:29 launcher*
-rw-rw-r--  1 banana_dev banana_dev 7.9K Mei  28 01:29 README.md
drwxrwxr-x  2 banana_dev banana_dev 4.0K Mei  28 02:53 samples/
drwxrwxr-x  2 banana_dev banana_dev 4.0K Mei  28 01:29 scripts/
drwxrwxr-x  2 banana_dev banana_dev 4.0K Mei  28 01:29 shared/
drwxrwxr-x  2 banana_dev banana_dev 4.0K Mei  28 02:51 templates/
```

**Comment by cpuguy83** [comment]
I really don't understand your issue.

Can you provide the docker commands you are running, what you expect to see, and what you are actually seeing?

Also a minimal repro case (ie, not firing up discourse), would be super helpful.

**Comment by hongquan** [comment]
Hi, I'm closing this. I didn't use directly docker commands, but used Discourse-provided commands (to start the container and to enter the container).

The phenomenon of not mounting only occurs if I enter the container via Discourse's `./launcher enter app`. Everything is fine if I enter via `./launcher ssh app`. So this is Discourse problem, not Docker. Difference between the two:

``
$ ./launcher --help
Usage: launcher COMMAND CONFIG [--skip-prereqs]
Commands:
    start:      Start/initialize a container
    stop:       Stop a running container
    restart:    Restart a container
    destroy:    Stop and remove a container
    enter:      Use nsenter to enter a container
    ssh:        Start a bash shell in a running container
    logs:       Docker logs for container
    mailtest:   Test the mail settings in a container
    bootstrap:  Bootstrap a container for the config based on a template
    rebuild:    Rebuild a container (destroy old, bootstrap, start new)
    cleanup:    Remove all containers that have stopped for > 24 hours

Options:
    --skip-prereqs   Don't check prerequisites
    --docker-args    Extra arguments to pass when running docker
```

Thanks for your patient.
