### ISSUE TITLE
Docker binds only on IPV6

### ISSUE THREAD

**Issue by ebuildy** [docker/docker#14010]
docker version:

````
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
````

docker info:

````
Containers: 0
Images: 35
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 35
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.19.0-21-generic
Operating System: Ubuntu 15.04
CPUs: 1
Total Memory: 668.4 MiB
Name: prod-docker-ad
ID: YSJS:KYUS:DXPQ:CQRH:5AUS:2TRW:PY3Q:CBN5:ORPH:EF4S:VZIW:L3ZF
WARNING: No swap limit support
````
uname -a:

````
Linux prod-docker-ad 3.19.0-21-generic #21-Ubuntu SMP Sun Jun 14 18:31:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
````

Running on Microsoft Azure cloud under a public load-balancer.

Step to produce the error:

1) docker run -d -p 80:8080 --name admin_rancher rancher/server

Result received: 

![netstat -a]
(https://beemapp.s3-eu-west-1.amazonaws.com/8d15a601-b3db-4a45-9a7f-217cfcc054c3.jpg)

Result excepted:

Where ssh is listening on both IPV4 and IPV6, Docker only on IPV6. I don't know if it's a bug or not, but how can I force Docker to use only IPV4 ? (I have already disable and blacklist IPV6).

**Comment by cpuguy83** [comment]
This is a dup of #2174, and as stated in that one this is just an issue with netstat.
If something is not connecting correctly I'd just the service in the container is actually working properly rather than netstat.
Closing as this is a dup.
