### ISSUE TITLE
Docker Stats API missing network information

### ISSUE THREAD

**Issue by boucher** [docker/docker#14027]
The docker stats API seems to use the libcontainer network settings in order to collect stats[1], but these settings are null since the introduction of libnetwork, so the network stats are not included.

[1] https://github.com/docker/docker/blob/master/daemon/execdriver/driver_linux.go#L145

**Comment by boucher** [comment]
Just as a comment, I noticed this because checkpoint/restore support in libcontainer has also been broken because of the same change: https://github.com/docker/docker/blob/master/vendor/src/github.com/docker/libcontainer/container_linux.go#L481

**Comment by LK4D4** [comment]
I wonder if we can fill state from namespace, but it looks like not very easy task :/

**Comment by LK4D4** [comment]
ping @mrjana 
Can we introduce stats API to libnetwork?
