### ISSUE TITLE
Proposal: --env for docker exec

### ISSUE THREAD

**Issue by csabapalfi** [docker/docker#14036]
Setting environment variables with docker exec currently requires a shell and a bit of extra code:
`docker exec 123abc /bin/sh -c 'export ONE=1; echo $ONE'`

Wouldn't it be nice if could just do this?
`docker exec -e ONE=1 123abc  echo $ONE`

Happy to contribute this and it looks quite straightforward to implement. Asked about this on IRC, too. What do you think?

**Comment by dqminh** [comment]
I think it's ok to add this. We already have `--user` support and want to add `--privileged` IIRC, so `--env` probably fits right in.

**Comment by duglin** [comment]
SGTM as long as there isn't a technical reason it hasn't been done before.

**Comment by henrysher** [comment]
i have prepared a PR for your proposal #14202, try to add two new options in `exec` command, similar usage to `run` command, also with some integration-cli tests.
```
-e, --env=[]               Set environment variables
--env-file=[]              Read in a file of environment variables
```
The environment variables provided in `exec` command will not clear the variables directly in the container, but replace the existing one or append for new one, as the func "**ReplaceOrAppendEnvValues**" re-used here (same to `run`, in *docker/utils*). For example, 
```
# docker exec CONTAINER1  env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=bdc64e485829
HOME=/root
```
```
# cat env.file
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin

# docker exec --env-file env.file nginx env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin
HOSTNAME=bdc64e485829
HOME=/root
```
```
# docker exec -e "TEST=H" -e "HOSTNAME=xxx" CONTAINER1  env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin
HOSTNAME=xxx
TEST=H
HOME=/root
```

Please help review it. @cpuguy83 @crosbymichael @icecrime

**Comment by cpuguy83** [comment]
hmm... Not sure I see the technical reason to actually include this.

docker exec is a hack to break into a container.
It's purposefully designed to put you in the exact env as the container was started with.

**Comment by jfrazelle** [comment]
closing see the reason why in the roadmap https://github.com/docker/docker/blob/master/ROADMAP.md#21-docker-exec

**Comment by csabapalfi** [comment]
Understood. Thanks.

**Comment by gsauthof** [comment]
Alternatively you can set the environment variable like this:

    docker exec 123abc env ONE=1 /path/to/cmd/inside/container

**Comment by thaJeztah** [comment]
this was implemented `docker exec` now has an `--env` option; https://docs.docker.com/engine/reference/commandline/exec/#usage

**Comment by gsauthof** [comment]
Hm, some issue comments and references read as though this functionality were rejected.

FWIW, `docker exec --help` on Docker 1.6.2/Ubuntu 14 doesn't have it.

And with Docker 1.12.3 (this is what Travis has) I get this error:

    flag provided but not defined: --env

(translate: unrecognized/unknown option) And indeed, the `--help` screen doesn't mention it.

With Docker 17.03 the `--env` option is documented and works as expected.
