### ISSUE TITLE
download-frozen-image.sh: not found 

### ISSUE THREAD

**Issue by GeertVL** [docker/docker#14039]
When I want to build docker on windows I get the following error. I use boot2docker 1.7.0 if that has something to do with it.

my build command is c:\>docker build -t dry-run-test .

Result:
Step 34 : COPY contrib/download-frozen-image.sh /go/src/github.com/docker/docker/contrib/             
 ---> Using cache                                                                                     
 ---> cbe8e4279edf                                                                                    
Step 35 : RUN contrib/download-frozen-image.sh /docker-frozen-images    busybox:latest@8c2e06607696bd4
afb3d03b687e361cc43cf8ec1a4a725bc96e39f05ba97dd55       hello-world:frozen@91c95931e552b11604fea91c2f5
37284149ec32fff0f700a4769cfd31d7696ae   jess/unshare@5c9f6ea50341a2a8eb6677527f2bdedbf331ae894a41714fd
a770fb130f3314d                                                                                       
 ---> Running in 250becc90b8e                                                                         
/bin/sh: 1: contrib/download-frozen-image.sh: not found

Any idea what to do? I try to change the Dockerfile to the actual path to that file but it doesn't fix it.

**Comment by dobsiin** [comment]
this could happen if windows puts a carriage return in the .sh file.
was my prolbem at least.
i have used tofrodos to get rid of those, in the end docker was able to actually find my .sh file

**Comment by GeertVL** [comment]
What do you mean by tofrodos?

**Comment by GeertVL** [comment]
+1 for dobsiin. You can do it with notepad++ too if you want. download-frozen-image in the contrib file is sufficient to fix this problem.
