### ISSUE TITLE
 Cannot initiate the connection

### ISSUE THREAD

**Issue by lbpierre** [docker/docker#14038]
Sorry for the first post.

My issues is, when I run a docker build, my network failed.(command is: apt-get install golang -y) And I get this error:
```
Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8c01::19). - connect (101: Network is unreachable)
````

The strange thing is, I can download and install some packages and for others it failed. I have check on ubuntu repository and there exist.

Have you an idea to fixe up ?

**Comment by cpuguy83** [comment]
This sounds like a connectivity issue in general...

But in any case, can you provide:

1. repro steps
2. docker info output
3. docker version output

**Comment by cpuguy83** [comment]
Closing, if you can provide requested info and repro and please ping here and we can take a look.
Thanks!

**Comment by juan-jimenez** [comment]
I have the same problem and I think it could be proxy related even though I have alredy set values for the proxy.  Here is the basic info required:

**$ docker version**
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:14:21 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 20:39:58 2016
 OS/Arch:      linux/amd64

**$ docker info**
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 2
Server Version: 1.10.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 24
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 4.1.17-boot2docker
Operating System: Boot2Docker 1.10.1 (TCL 6.4.1); master : b03e158 - Thu Feb 11 22:34:01 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.2 MiB
Name: default
ID: OGZY:HQCY:WTZS:PRYZ:HGDH:2LMR:26A4:DVXN:SI3L:WUWR:FHJ6:TIMB
Debug mode (server): true
 File Descriptors: 10
 Goroutines: 22
 System Time: 2016-02-17T11:30:39.087794072Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Http Proxy: http://proxy1.audatex.es:80
Https Proxy: http://proxy1.audatex.es:80
Labels:
 provider=virtualbox

**$ uname -a**
MINGW64_NT-6.1 AXES-1056 2.4.0(0.292/5/3) 2016-01-07 19:39 x86_64 Msys
