### ISSUE TITLE
Daemon image pulling freezes and then refuses to pull anything

### ISSUE THREAD

**Issue by Soulou** [docker/docker#14043]
Description of problem:

Sometimes when I pull an image from a private registry, the pulling never stopped:

The logs give the following output:

```
INFO [43018] POST /v1.12/images/create?fromImage=registry.example.com.com%2Fmyapp&repo=registry.example.com%2Fmyapp&tag=0ae43dd2d60d4e3
INFO [43018] +job pull(registry.example.com/myapp, 0ae43dd2d60d4e3) 
INFO [43018] +job resolve_repository(registry.example.com/myapp) 
INFO [43018] -job resolve_repository(registry.example.com/myapp) = OK (0) 
```

The pull action never finished. The  issue is that I can't control anything and even days after, if I try to pull the image, I get:

```
Repository registry.example.com/myapp already being pulled by another client. Waiting.
```

From this point any pull will free exactly the same way, the only solution so far has been to restart the docker daemon which is really not a solution. How can I avoid this kind of freeze which definitely makes Docker unusable, thank you.

Version:

```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

Info:

```
Containers: 214
Images: 451
Storage Driver: btrfs
Execution Driver: native-0.2
Kernel Version: 3.19.0-21-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 6
Total Memory: 31.42 GiB
Name: <hostname>
ID: IORK:X3R5:VRLX:BI2Z:EISE:DTSR:PVRY:WK6T:OLEW:T7ZT:Q6SB:XPEE
```

Uname:

```
Linux <hostname> 3.19.0-21-generic #21~14.04.1-Ubuntu SMP Sun Jun 14 18:45:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.): vmware instance

How reproducible: not found yet

**Comment by dmp42** [comment]
Thanks for the report @Soulou 

If I read this correctly, you are interacting with a private registry.
What registry is that? python-v1? or golang-v2? Are you using a proxy in front of it? What's in your registry logs?

On the client side, are you using boot2docker? What's in your docker daemon logs (ran in debug)?

Thanks.

**Comment by Soulou** [comment]
Thank @dmp42 for your response, here are the answers to your questions:

Registry version:
* v1 python (Still have some Docker 1.5 nodes, and this also appears with Docker 1.5), I've upgraded one of them to 1.6.2 without success.

Proxy:
* Yes nginx 1.8, with the following configuration

```
server {
  listen 80;
  listen 443 ssl;
  ssl_certificate     <crt path>;
  ssl_certificate_key <key path>;
  server_name <hostname>;

  client_max_body_size 800M;

  location / {
    // allow / deny instructions
    proxy_pass http://<backend name>;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

  }
}
```

Registry logs: nothing special

```
2015-06-19 20:45:20 [632] [INFO] Booting worker with pid: 632
2015-06-19 20:48:00 [518] [INFO] Autorestarting worker after current request.
2015-06-19 20:48:00,776 INFO: Autorestarting worker after current request.
2015-06-19 20:48:01 [518] [INFO] Worker exiting (pid: 518)
2015-06-19 20:48:01,195 INFO: Worker exiting (pid: 518)
2015-06-19 20:48:02 [635] [INFO] Booting worker with pid: 635
2015-06-19 21:04:00 [623] [INFO] Autorestarting worker after current request.
2015-06-19 21:04:00,049 INFO: Autorestarting worker after current request.
2015-06-19 21:04:00 [623] [INFO] Worker exiting (pid: 623)
2015-06-19 21:04:00,949 INFO: Worker exiting (pid: 623)
```

Client side:
* ruby service hitting Docker remote API.

Docker logs in debug:

Unavailable now, that's a problem in production which appears on nodes starting hundreds of containers every day, I'll try to restart one of them in Debug and to reproduce the issue, but not sure I'll succeed

**Comment by dmp42** [comment]
@Soulou I strongly advise you start looking into the new registry (https://github.com/docker/distribution/blob/master/docs/index.md).

I would also advise against the use of a proxy like nginx (with the new registry, you don't need such a proxy anymore for TLS termination).

I wish I could give you a better answer than "migrate", but really the new version was started from scratch for a reason.

Hope that helps.

**Comment by Soulou** [comment]
That was my plan, but as it requires to shutdown all the containers to restart docker, it is easier to say than to do ;-)

**Comment by thaJeztah** [comment]
Reading the above discussion, I think this should be closed, because it looks like this is an issue with the old 'V1" registry and won't be addressed.

Feel free to comment here if you think I closed this by mistake.
