### ISSUE TITLE
Docker build --pull FROM private repo fails

### ISSUE THREAD

**Issue by rosskukulinski** [docker/docker#14057]
Description of problem:

Originally reported here
https://github.com/docker/compose/issues/1577#issuecomment-113674412

Using Dockerhub, doing a docker pull from a private repo works just fine.  Running a docker build FROM that repo also works.  But if you use ```docker build --pull```, then the build fails with 'Error: image private_account/private_image:private_tag not found'

`docker version`:
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): darwin/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64

`docker info`:
Containers: 0
Images: 45
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 45
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.5-boot2docker
Operating System: Boot2Docker 1.7.0 (TCL 6.3); master : 7960f90 - Thu Jun 18 18:31:45 UTC 2015
CPUs: 4
Total Memory: 1.955 GiB
Name: boot2docker
ID: NO24:6XJP:RJXD:XRSQ:NQHC:FCFA:Z22R:AYRH:7QJR:QN4D:VBDI:TJFP
Debug mode (server): true
File Descriptors: 9
Goroutines: 17
System Time: 2015-06-20T00:12:49.612951271Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: rosskukulinski
Registry: https://index.docker.io/v1/

`uname -a`:
Darwin rossk-air.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

Environment details (AWS, VirtualBox, physical, etc.):

boot2docker

How reproducible:

Every time. Every, stinkin time.

Steps to Reproduce:
1. Create Dockerfile with FROM using private registry
2. docker build --pull .
3. See the error

Actual Results:

Error: image private_account/private_image:private_tag not found

Expected Results:

It should successfully pull the image and run the docker build.

**Comment by dmp42** [comment]
Possibly related to #14065

**Comment by adambiggs** [comment]
@dmp42 this is happening for a private repo that doesn’t contain a hyphen, so I’m no sure it’s directly related to #14065.

**Comment by clementmangin** [comment]
+1, experimenting the same issue with a repo without hyphens

**Comment by rosskukulinski** [comment]
sorry, I should have been more clear in my examples.  My repo & tags do not have hyphens, so at least my issues is not related to #14065

**Comment by alairock** [comment]
I too am experiencing this *very* painful issue.

**Comment by dmp42** [comment]
A fix has been submitted on #14139

**Comment by goffinf** [comment]
Also seeing this issue using a private (ECR) registry. No hyphens in image names, pull and push work fine. When is the fix slated for release ?

**Comment by thaJeztah** [comment]
@goffinf the fix shipped two years ago, so what you're seeing is a different issue.

If you suspect there's a bug, and you have steps to reproduce, please open a new issue with details. Commenting on closed issues makes it very easy for your report to go unnoticed, and may well be unrelated (which is not possible to tell without enough information).

I'm locking the conversation on this issue, but feel free to open a new issue per my comment above.
