### ISSUE TITLE
'docker search' does not say official images are automated as well

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/docker#14059]
The following screenshot gives me an impression like `mono` image is not actually automatically built although it's official.

![image](https://cloud.githubusercontent.com/assets/159209/8265604/c0252b24-16b4-11e5-872b-593817ba2721.png)

For someone coming new to the ecosystem, this is probably confusing. I think it should say `[OK]` for both "AUTOMATED" and "OFFICIAL" for official images.

If the official images are automated, too, then this output is misleading. (Please correct if I'm wrong.)

```
docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): darwin/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

```
docker info
Containers: 3
Images: 231
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 237
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.16.0-31-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 3.362 GiB
Name: redacted
ID: VJEO:U3TS:HJ7T:IKNS:JHJP:YTOW:UVLP:NUMC:RSA7:U42X:OMNC:QCYW
Debug mode (server): true
Debug mode (client): false
Fds: 19
Goroutines: 27
System Time: Sat Jun 20 01:57:43 UTC 2015
EventsListeners: 0
Init SHA1: 7f9c6798b022e64f04d2aff8c75cbf38a2779493
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker
WARNING: No swap limit support
```

**Comment by thaJeztah** [comment]
I actually don't think the official images are automated builds (at least, not all of them) so the information could we'll be correct.

deferring to @tianon because I don't know for this particular image.

**Comment by ahmetalpbalkan** [comment]
I thought all these images have dockerfiles that the image is built from?

**Comment by thaJeztah** [comment]
I think they're built, tested and then pushed, but I'm not 100% familiar with the process, also see https://github.com/docker-library/official-images

**Comment by tianon** [comment]
`AUTOMATED` here refers specifically to the Hub's own automated build infrastructure, which is not used for the images which are `OFFICIAL` (since they've got peer review before being built/pushed).

**Comment by ahmetalpbalkan** [comment]
@tianon understood. It just seemed complicated to me as a user, as I probably assumed their build/push steps are also automated. It makes sense then.
