### ISSUE TITLE
docs/reference/run.md: says --expose overrides EXPOSE when it doesn't

### ISSUE THREAD

**Issue by SpencerBrown** [docker/docker#14050]
docs/reference/run.md in section "Overriding Dockerfile image defaults" implies that the docker run --expose option overrides the EXPOSE command in a Dockerfile. It does not. docker run --expose simply adds to the list of exposed ports. It does not override the Dockerfile EXPOSE list of ports.

If you think this is trivial, this actually cost me a cycle, because I *assumed* from the doc that I could put an EXPOSE command in the Dockerfile, and override it later. 

There should be a --unexpose option but that's a different issue. This issue is just about correcting the doc.

**Comment by thaJeztah** [comment]
Thanks for reporting this, @SpencerBrown (and apologies for such a late reply). I agree that the docs around this are not clear.

Are you perhaps interested in creating a pull-request to improve that section? The source for that document can be found here; https://github.com/docker/docker/blob/master/docs/reference/run.md

**Comment by SpencerBrown** [comment]
Pull request:  #14625
