### ISSUE TITLE
Broken links on Docker Remote API docs page

### ISSUE THREAD

**Issue by EvanKrall** [docker/docker#14055]
On https://docs.docker.com/reference/api/docker_remote_api/, the "Full Documentation" links are broken:

```
<h3 id="full-documentation">Full documentation</h3>

<p><a href="/reference/reference/reference/reference/api/docker_remote_api_v1.19/"><em>Docker Remote API v1.19</em></a></p>
```

They appear to be correct in the markdown:

```
### Full documentation

[*Docker Remote API v1.19*](/reference/api/docker_remote_api_v1.19/)
```

**Comment by EvanKrall** [comment]
BUG REPORT INFORMATION

Use the commands below to provide key information from your environment:

docker version: irrelevant
docker info: irrelevant
uname -a: 5

Provide additional environment details (AWS, VirtualBox, physical, etc.):

List the steps to reproduce the issue:
1. go to https://docs.docker.com/reference/api/docker_remote_api/#v1-19
2. click "Docker Remote API v1.19"

Describe the results you received:
404

Describe the results you expected:
200

Provide additional info you think is important:

----------END REPORT ---------

**Comment by anchal-agrawal** [comment]
@EvanKrall See the note at the bottom at https://docs.docker.com/index.html. The site UI is being revamped, so there are a few link/markdown issues that should be resolved pretty soon!

**Comment by thaJeztah** [comment]
ping @moxiegirl, looks like some issue with the tooling in this case?

**Comment by anchal-agrawal** [comment]
@thaJeztah @moxiegirl There are also a few issues with the heading markdown at https://docs.docker.com/docker/installation/ubuntulinux/.

**Comment by moxiegirl** [comment]
@thaJeztah Yes, that was a tooling issue. I'm no longer seeing a problem wiht this link @EvanKrall  http://docs.docker.com/reference/api/docker_remote_api/

**Comment by thaJeztah** [comment]
Confirmed, looks like the links and the headings are resolved now (headings aren't published yet), thanks @moxiegirl 

Thanks @EvanKrall @anchal-agrawal, for reporting, much appreciated!
