### ISSUE TITLE
Pointing "FROM" to a private repo which name contains an hyphen is broken in 1.7

### ISSUE THREAD

**Issue by dmp42** [docker/docker#14065]
Create and push the following images:

  * `foo/test-private` - make this private on the hub
  * `foo/test-public`
  * `foo/private` - make this private on the hub

Now, rmi all these images.

Try to build the following dockerfiles:

 * `FROM foo/test-private` <- FAIL
 * `FROM foo/test-public` <- WORKS
 * `FROM foo/private` <- WORKS

Note that a simple `docker pull foo/test-private` works.

Reported initially by @sbasyal 
cc @icecrime 

ping @jlhawn @dmcgowan @stevvooe @RichardScothern

**Comment by duglin** [comment]
Can you show how it fails?

**Comment by dmp42** [comment]
@duglin I believe it fails authenticating properly.

```
DEBU[2559] Pulling tag from V2 registry: "latest"
DEBU[2559] [registry] Calling "GET" https://registry-1.docker.io/v2/dmp42/test-repo/manifests/latest
DEBU[2559] Getting bearer token with map[service:registry.docker.io realm:https://auth.docker.io/token] for
DEBU[2559] hostDir: /etc/docker/certs.d/auth.docker.io
DEBU[2560] hostDir: /etc/docker/certs.d/registry-1.docker.io
ERRO[2560] Error from V2 registry: Authentication is required.
DEBU[2560] image does not exist on v2 registry, falling back to v1
DEBU[2560] pulling v1 repository with local name "dmp42/test-repo"
Pulling repository dmp42/test-repo
DEBU[2560] [registry] Calling GET https://index.docker.io/v1/repositories/dmp42/test-repo/images
DEBU[2560] hostDir: /etc/docker/certs.d/index.docker.io
Error: image dmp42/test-repo:latest not found

```

**Comment by alairock** [comment]
I don't think this is just private repos that contain hyphens. I have several that fail in this same way for all images I have and none have hyphens. 

I would also like to note, if I do a `$ docker pull {user}/{repo}/{tag}` everything works fine. 

If I have a Dockerfile that looks like:

```
FROM {user}/{repo}/{tag}
MAINTAINER alairock
RUN "Hello World"
```

It fails with the same error you have there. (Note `{user}/{repo}/{tag}` == Private repo)

Docker v1.7.0
