### ISSUE TITLE
docker is blocked when starts to attach a container

### ISSUE THREAD

**Issue by shafreeck** [docker/docker#14063]
## How to produce:
1. docker run -it centos /bin/bash
2. Ctrl-D to exit
3. docker start -a \<cid\>  
Now docker is blocked.

##  lldb prints the thread info
(lldb) thread list
Process 52896 stopped
* thread #1: tid = 0x1cb6a6, 0x000000000004316b docker`runtime.mach_semaphore_wait + 11, stop reason = signal SIGSTOP
  thread #2: tid = 0x1cb6a9, 0x0000000000043183 docker`runtime.mach_semaphore_timedwait + 19
  thread #3: tid = 0x1cb6aa, 0x000000000004316b docker`runtime.mach_semaphore_wait + 11
  thread #4: tid = 0x1cb6ac, 0x0000000000043243 docker`runtime.kevent + 35

## docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

## docker info
Containers: 2
Images: 23
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 27
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 4.0.3-boot2docker
Operating System: Boot2Docker 1.6.2 (TCL 5.4); master : 4534e65 - Wed May 13 21:24:28 UTC 2015
CPUs: 4
Total Memory: 1.957 GiB
Name: boot2docker
ID: PBDP:CLVG:6BCP:MMCF:457N:7MUQ:57QU:SAA4:2YK6:2GLX:XSUQ:A6VU
Debug mode (server): true
Debug mode (client): false
Fds: 23
Goroutines: 45
System Time: Sat Jun 20 15:18:59 UTC 2015
EventsListeners: 0
Init SHA1: 7f9c6798b022e64f04d2aff8c75cbf38a2779493
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: shafreeck
Registry: [https://index.docker.io/v1/]

## I use boot2docker on Mac OS X
uname -a
Darwin matrix 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

**Comment by runcom** [comment]
This affects 1.7.0 as well :/ @shafreeck could you also paste here `uname -a` and `docker info`?

**Comment by shafreeck** [comment]
It turns out that's my fault. Use `docker start -a -i cid` instead of `docker start -a` , `-i` indicates to use the interactive mode. I will close this issue.

**Comment by runcom** [comment]
@shafreeck thanks!
