### ISSUE TITLE
Unable to download certain tags (oraclelinux:7) - error 400

### ISSUE THREAD

**Issue by maniankara** [docker/docker#14060]
Hi,
    There are certain tags or certain images which throw 400 error.
--------------------------- clip -------------------
Unable to find image 'oraclelinux:7' locally
Pulling repository oraclelinux
8a2b759d9dd8: Error pulling image (7) from oraclelinux, HTTP code 400 
8c3e49cb06dc: Download complete 
90fed8b1ceab: Error pulling dependent layers 
FATA[0014] Error pulling image (7) from oraclelinux, HTTP code 400 
--------------------------- clip -------------------
However other tags like "oraclelinux:7.0" works.
  
Thanks,
 - Anoop

**Comment by thaJeztah** [comment]
This could be an issue with Docker Hub, could you raise an issue via support@docker.com?

I'm going to close this issue because I think this is an issue with Docker Hub, not Docker, but feel free to comment with additional information if this turns out not being the case. thanks!
