### ISSUE TITLE
Docs for "Getting started"

### ISSUE THREAD

**Issue by vikas-parashar** [docker/docker#14076]
I'm a newbie and trying to contribute. Where I could find the docs file for getting started for linux https://docs.docker.com/linux/started/
and the getting started link in https://docs.docker.com/linux/started/ is broken

**Comment by thaJeztah** [comment]
Thanks for reporting, @vikas-parashar and sorry for such a late response. That part of the documentation is currently in a private repository (see https://github.com/docker/docker/issues/14237#issuecomment-116743558)

I couldn't find a broken link on that page, but it may already have been solved.

I'm going to close this issue, for the above reasons, but please comment if the link is still broken (and I overlooked it), then I'll try to get it solved.

Thanks for taking the time reporting!
