### ISSUE TITLE
"The database file is locked: database is locked" in a DinD setup

### ISSUE THREAD

**Issue by sttts** [docker/docker#14072]
We use a Docker-in-Docker setup to run kubernetes-mesos end-2-end tests using docker-compose. This worked pretty reliable with Docker 1.6, but leads to reproducible "database is locked" errors in Docker 1.7.

The error occurs for the inner Docker daemon. When it happens, it does not go away, the DB stays locked.

The DinD container can be found here:

  https://github.com/mesosphere/kubernetes/tree/docker-compose-dind/cluster/mesos/docker/kubernetes-mesos-slave

I will try to isolate the problem more next week.

**Comment by sttts** [comment]
It's the same error message reported in #2325 long ago.

**Comment by thaJeztah** [comment]
@sttts could you add the information that @GordonTheTurtle requested above?

**Comment by cpuguy83** [comment]
Closing as we need more info to be able to look into the issue.
@sttts If you can provide more details and repro on docker 1.8 (or nightly build) please ping here and we can take a look.
Thanks!
