### ISSUE TITLE
Backwards incompatibility between Client 1.19 and Server 1.18

### ISSUE THREAD

**Issue by arun-gupta** [docker/docker#14077]
Running a Docker 1.7 client to start a machine created using Docker 1.6 and got the error message:

```
client and server don't have same version (client : 1.19, server: 1.18)
```

The client should maintain backwards compatibility otherwise should explicitly state that it will break it.

**Comment by arun-gupta** [comment]
```
> docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): darwin/amd64
Error response from daemon: client and server don't have same version (client : 1.19, server: 1.18)
```

```
> docker info
Error response from daemon: client and server don't have same version (client : 1.19, server: 1.18)
```

```
> uname -a
Darwin Aruns-MacBook-Pro.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
```

**Comment by duglin** [comment]
We don't support new clients talking to old servers. 

-Doug

**Comment by arun-gupta** [comment]
Sounds pretty lame!

Is there a migration policy defined on how to update client and servers to migrate to new versions in that case?

**Comment by cpuguy83** [comment]
Hey, closing this as it's been discussed several times before. Having the daemon be compatible with newer client versions is not do-able.

There is #11486 for allowing the client to set the API version to use (ie, tell the client to use an older version).

**Comment by WangWenchao** [comment]
```
boot2docker uprgade 
```
maybe fix this problem

**Comment by IanVaughan** [comment]
```
error in run: Unknown command: uprgade
Usage: boot2docker [<options>] {help|init|up|ssh|save|down|poweroff|reset|restart|config|status|info|ip|shellinit|delete|download|upgrade|version} [<args>]
 ```

**Comment by IanVaughan** [comment]
@WangWenchao 
```
boot2docker upgrade
```

**Comment by mikkergimenez** [comment]
There is also this tool we put together to hot-swap local docker versions:

https://github.com/newrelic/dkenv

**Comment by rgbkrk** [comment]
@mikkergimenez D'oh. We wrote [`dvm`](https://github.com/rgbkrk/dvm) without knowing about dkenv! /cc @smashwilson

**Comment by IAIS4EP** [comment]
hi all, well a) dkenv not clear how to install b) dvm installs but does not seem to be able to switch the versions really, it just kindof fakes the output of --versiob?! Using ubuntu  3.13.0-52-generic...

![image](https://cloud.githubusercontent.com/assets/13382270/11405102/16dd552c-93a6-11e5-945f-b0c742478c72.png)

**Comment by rgbkrk** [comment]
dvm functions like nvm, rvm, virtualenv and other version managers/environments by changing the PATH.

By the way, if you installed dvm in the last day, you should install over the top of it. The Travis deploy is broken, working on fixing that in upstream Travis.

**Comment by IAIS4EP** [comment]
hi rgbkrk, thx for your input, now I am not sure whether I have properly "installed over top" but the issue seems still to be there..

![image](https://cloud.githubusercontent.com/assets/13382270/11418032/53806ae8-941c-11e5-9b9e-7d16bb5aee94.png)

**Comment by IAIS4EP** [comment]
upgraded to docker-enging with docker 1.9.1; seems to work now! dvm not worked for me.

**Comment by rgbkrk** [comment]
Ah! I see your image there. docker-compoe relies on docker-py to talk to the Docker API directly. It doesn't use the `docker` binary, which is what `dvm` manages. Looks like you would need to pin the version of compose you're installing.

**Comment by benjohnson77** [comment]
I ran into this issue, thinking that boot2docker could be removed in favor of using docker machine so I installed boot2docker again and ran `boot2docker upgrade` but then also had to run `docker-machine upgrade dockerhost-name`

**Comment by Jailman** [comment]
Solution:  
Run the command below
export COMPOSE_API_VERSION=1.18

**Comment by abelbezu** [comment]
If `docker-machine upgrade <machine-name>`  doesn't work, you can down grade the docker version by running the command

`export DOCKER_API_VERSION=<lower-version-number>`
