### ISSUE TITLE
Docker documentation is contradictory regarding VolumesFrom

### ISSUE THREAD

**Issue by vincentwoo** [docker/docker#14087]
Here is what you get when you search in the docker repo for the string `"VolumesFrom"`: https://github.com/docker/docker/search?utf8=%E2%9C%93&q=VolumesFrom

The issue is that most of the response formats ascribed to docker inspect say that the endpoint will return something like

` "VolumesFrom":""`

This is untrue - as of docker 1.7 (and probably much earlier), docker returns either `null` or something like `["contrainerid"]` as the value for that key.

The tricky part is that early docker (1.0) used to accept a string as input for `VolumesFrom` in the remote api, before a change (maybe around 1.4?) had it take an array instead. I'm not sure when both the input and output changed, but someone more knowledgeable should probably retroactively correct the documentation thereof.

I stumbled across this issue because docker 1.7's remote API started **throwing errors** when passed string values for `VolumesFrom` - it used to silently accept the empty string as a valid input. I don't count this as a bug, but it was certainly surprising.

*As an aside there has GOT to be a better way to arrange all of these docs besides a series of increasingly large and self-contradictory markdown files.*

**Comment by vincentwoo** [comment]
By the way, that bot is obnoxious. At least shorten it to say something less off-putting like "Hi! If this is a bug report regarding the runtime, please follow this link to ensure that we have all the information we need! This message is being posted automatically because we don't see the minimum amount of information we need to investigate bugs in the engine."

**Comment by LK4D4** [comment]
Documentation was fixed. Thanks for report.
