### ISSUE TITLE
Docker daemon doesn't start after updating to 1.7 on Ubuntu 15.04

### ISSUE THREAD

**Issue by lots0logs** [docker/docker#14088]
I'm creating a new issue because I don't think the issue I am experiencing is the same as #14035 as I have always used the aufs storage drive and the error I am getting doesn't mention anything about the storage driver:
```
root@buildsrv:~# systemctl status -l docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/etc/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: start-limit) since Mon 2015-06-22 02:15:42 CDT; 7min ago
     Docs: https://docs.docker.com
 Main PID: 3217 (code=exited, status=0/SUCCESS)

Jun 22 02:15:42 buildsrv systemd[1]: Started Docker Application Container Engine.
Jun 22 02:15:42 buildsrv systemd[1]: Starting Docker Application Container Engine...
Jun 22 02:15:42 buildsrv docker[3217]: Please specify only one -H
Jun 22 02:15:42 buildsrv systemd[1]: start request repeated too quickly for docker.service
Jun 22 02:15:42 buildsrv systemd[1]: Failed to start Docker Application Container Engine.
Jun 22 02:15:42 buildsrv systemd[1]: Unit docker.service entered failed state.
Jun 22 02:15:42 buildsrv systemd[1]: docker.service failed.
```

The documentation says that `-H` can be included multiple times. Has this changed?? How would I specify both a tcp port and a unix socket then?

**Comment by lots0logs** [comment]
Update: I figured out the reason for the error was that the socket was being managed by systemd socket file and I was also including it in the service files exec command. After removing it from the service file I get a different error that seems to be related to #14035 after all:
```
● docker.service - Docker Application Container Engine
   Loaded: loaded (/etc/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: start-limit) since Mon 2015-06-22 02:34:40 CDT; 3s ago
     Docs: https://docs.docker.com
  Process: 3733 ExecStart=/usr/bin/docker -d --dns 8.8.8.8 --dns 8.8.4.4 -H tcp://127.0.0.1:4243 (code=exited, status=1/FAILURE)
 Main PID: 3733 (code=exited, status=1/FAILURE)

Jun 22 02:34:40 buildsrv docker[3733]: time="2015-06-22T02:34:40.096575829-05:00" level=fatal msg="Error starting daemon: error initializing graphdriver: \"/var/lib/docker\" contains other graphdrivers: devicemapper; Please cleanup or explicitly choose storage driver (-s <DRIVER>)"
```

**Comment by lots0logs** [comment]
Another update: I moved `/var/lib/docker/devicemapper` outside of `/var/lib/docker` and everything seems to be back to normal. Sorry for the noise, but hopefully it will help someone

**Comment by magnetikonline** [comment]
@lots0logs just to add - this fix worked for me - upgrading to Docker 1.7.1 from 1.6 on Ubuntu 14.04LTS. Cheers!

**Comment by tf** [comment]
@magnetikonline Same here

**Comment by jb11211** [comment]
Found this fun little gotcha updating from 1.6 to 1.8 as well. It's disappointing that this is still an issue.

**Comment by mylons** [comment]
also happened to me upgrading to 1.8 from a much earlier version.

**Comment by michael-henderson** [comment]
Happened to me moving from 1.6.* to 1.9.0.

**Comment by lots0logs** [comment]
Seems I should reopen this issue I guess :smirk:

**Comment by cpuguy83** [comment]
What does your unit file look like?

**Comment by thaJeztah** [comment]
@michael-henderson @Bilge @mylons what is the issue you're having? The problem with multiple `-H` flags, or the "error initializing graphdriver" message?

**Comment by Bilge** [comment]
@thaJeztah The graphdriver message. I had to delete `/var/lib/docker/devicemapper`.

**Comment by thaJeztah** [comment]
@Bilge the graphdriver message can be expected; previously other existing directories were silently ignored when docker "switched" to another graphdriver (docker automatically selects the best available graphdriver). However, this resulting in situations where all images and/or containers apparently disappeared, if another graphdriver was used before upgrading, We therefore decided to add that error to make the user either remove the unwanted directories, or explicitly specify the graphdriver that should be used.

**Comment by repptilia** [comment]
Getting a similar issue on my stack:
docker version:
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

docker info:
Containers: 1
Images: 13
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 15
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-68-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 490 MiB
Name: ChillingMonkey
ID: YS4M:XA5L:7VXL:PGWM:5RPQ:KB6D:2FJW:2Y4G:EOR7:USUJ:AYYW:HXOR

Machine:
Linux ChillingMonkey 3.13.0-68-generic #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Installing the package  httpd-2.4.6-40.el7.centos.x86_64 fails with the error
 
error: unpacking of archive failed on file /usr/sbin/suexec: cpio: cap_set_file

**Comment by flaccid** [comment]
@thaJeztah that is ok but we might need a message to point the user to how e.g. a link to doc, additionally with no docker running I still get `sudo rm -Rf /var/lib/docker/devicemapper` and will probably need to disable the service and reboot, then remove that directory.

**Comment by thaJeztah** [comment]
@flaccid the current message is;

    Error starting daemon: error initializing graphdriver: "/var/lib/docker" contains other graph drivers:
    devicemapper; Please cleanup or explicitly choose storage driver (-s <DRIVER>)

Do you think that message needs more information?
Note that it's not strictly needed to remove the "devicemapper" directory; as long as you've specified a storage driver.

**Comment by flaccid** [comment]
Sure I just think most users will end up googling with that error, preventing that is an art form :)

**Comment by hanyong** [comment]
I'm a user end up googling with this things. I don't sure how to do a "cleanup ", is there some command, or just do a "rm -rf". I found this, It seems a simply "rm -rf" should work.

**Comment by icecrime** [comment]
Tentatively closing as the issue seems to be resolved: please let me know if it needs reopening! Thanks.

**Comment by douglas-larocca** [comment]
For anyone getting `rm: cannot remove ‘/var/lib/docker/devicemapper’: Device or resource busy`, I was finally able to remove it by running `sudo umount /var/lib/docker/devicemapper` first.
