### ISSUE TITLE
add digest info to v2 registry tags list

### ISSUE THREAD

**Issue by imreFitos** [docker/docker#14082]
v1 Registry API "tags" endpoint listed the image digests for each tag - this allowed client programs to find the exact version of "latest" for example. 

v2 Registry API doesn't list the digest ID for tags, and there is no way to find the digest id for an existing tag without downloading the tag . Manifest only lists the layer digests.

Please add the digest field to the v2 version of tags list! Thanks.

**Comment by imreFitos** [comment]
BUG REPORT INFORMATION

Use the commands below to provide key information from your environment:

docker version:
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64

docker info:
ontainers: 43
Images: 57
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 143
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-53-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 1.955 GiB
Name: dockervm
ID: TU6Q:7KOF:VW22:HMWC:E5KN:E2ZS:A3CD:6TJF:EKOD:RDXP:4DP2:QUHA
WARNING: No swap limit support

uname -a:
Linux dockervm 3.13.0-53-generic #89-Ubuntu SMP Wed May 20 10:34:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Provide additional environment details (AWS, VirtualBox, physical, etc.):
VirtualBox

List the steps to reproduce the issue:
1. run the latest 2.0.1 docker registry image: docker run -d -p 5000:5000 registry:2.0.1
2. curl http://localhost:5000/v2/mysql56/tags/list
3. receive a json object that only list the tags: {"name":"mysql56","tags":["latest","0.1"]}

Describe the results you received:
{"name":"mysql56","tags":["latest","0.1"]}

Describe the results you expected:
JSON object containing tags and digests:
{"0.1": "e9c379f8772deab9b73c7a2dfd2a70bbd732cfda5d214c584d2f9982068282bc", "latest": "e9c379f8772deab9b73c7a2dfd2a70bbd732cfda5d214c584d2f9982068282bc"}

Provide additional info you think is important:
The original v1 repository API described this before it got deleted. https://docs.docker.com/reference/api/registry_api/

----------END REPORT ---------

**Comment by stefanullinger** [comment]
+1

**Comment by tzz** [comment]
Yes, please. It's unnecessarily hard to get the digest IDs right now.

**Comment by johnculviner** [comment]
I honestly can't even figure out how to get the digest IDs. @tzz Where is this? This is the most confusing API I've ever looked at....

**Comment by johnculviner** [comment]
@stefanullinger 's approach doesn't seem to be working:

```>>> GET /v2/docker-node-example/manifests/2016-07-08_9b87d40```

```<<< Docker-Content-Digest → sha256:53ba9ae557c6999c5924e4994862923c3d4b8c327dbd999b1a8b1c1e3683e44e```

```>>> GET /v2/docker-node-example/manifests/sha256:53ba9ae557c6999c5924e4994862923c3d4b8c327dbd999b1a8b1c1e3683e44e```

```<<< 
{
    "errors": [
        {
            "code": "MANIFEST_UNKNOWN",
            "message": "manifest unknown",
            "detail": {
                "Name": "docker-node-example",
                "Revision": "sha256:53ba9ae557c6999c5924e4994862923c3d4b8c327dbd999b1a8b1c1e3683e44e"
            }
        }
    ]
}```

Same occurs if I go with the above minus the sha256 in front. What am I missing?

**Comment by tzz** [comment]
Unfortunately the digest ID is not stable. See https://github.com/docker/distribution/issues/1662 and the earlier https://github.com/deitch/docker_registry2/issues/4 among others.

So I would treat the digest ID as a read-only property that can't be used for querying or much else. This is a real pain, I agree.

**Comment by thaJeztah** [comment]
This is something that needs to be implemented in the _registry_ not the docker-engine, so this issue should be opened in that issue tracker; https://github.com/docker/distribution/issues. I'll close this issue here, because we cannot implement/fix this issue in this repository

**Comment by jurgenweber** [comment]
Where is the new ticket? Anyone worked out a way to do this yet?
