### ISSUE TITLE
Empty resolv.conf with --net=host since 1.7.0

### ISSUE THREAD

**Issue by gionn** [docker/docker#14096]
Hi,

after upgrading to docker 1.7.0, resolv.conf inside containers is always empty, while under 1.6.2 was working as expected (same resolv.conf of the host).

**Comment by thaJeztah** [comment]
@gionn are you still able to reproduce this on docker 1.7.1?

**Comment by gionn** [comment]
old.

**Comment by thaJeztah** [comment]
Oh, thanks for checking/closing @gionn!

**Comment by gionn** [comment]
:beers:

**Comment by thaJeztah** [comment]
bit early, but I'll join you on that :beers:  cheers!
