### ISSUE TITLE
1.7.0 Broken legacy containers that used the `--volumes-from` option

### ISSUE THREAD

**Issue by mgcrea** [docker/docker#14108]
Did upgrade today one of our servers  to docker `v1.7.0` (running Ubuntu 14.04LTS), and discovered that all our legacy containers started with the `--volumes-from` flag would not start anymore:

```
# docker start foo_backend.production
Error response from daemon: Cannot start container foo.backend.production: Unable to setup mount point, neither source nor volume defined
Error: failed to start containers: [foo_backend.production]
```

```
# docker inspect foo_backend.production | jq .[0].Volumes
{
  "/srv/data": ""
}
```

---

```
# docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

```
# docker info
Containers: 13
Images: 110
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 136
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-55-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 8
Total Memory: 62.89 GiB
Name: fr-6f6e
ID: SUBT:ZILY:FYIX:KZQL:UMLN:HYYG:4X75:BA3J:346R:XSDJ:U5HR:2L63
WARNING: No swap limit support
```

```
# uname -a
Linux fr-6f6e 3.13.0-55-generic #94-Ubuntu SMP Thu Jun 18 00:27:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jnummelin** [comment]
We're seeing also same errors with few "legacy" containers that have old-school bind mounts:
```
"Config": {
       ....
        "Volumes": {
            "/etc/mysql": {},
            "/var/lib/mysql": {}
        },
....
"HostConfig": {
        "Binds": [
            "/volumes/xyzdef/_var_lib_mysql:/var/lib/mysql"
        ],
"Volumes": {
        "/etc/mysql": "/data/docker/vfs/dir/84faf1a975042e1c1c0bd36803cb4e1d806de9f160551215751ca9a8c2768a22",
        "/var/lib/mysql": "/volumes/xyzdef/_var_lib_mysql"
    },
    "VolumesRW": {
        "/etc/mysql": true,
        "/var/lib/mysql": true
    }
```

**Comment by thaJeztah** [comment]
ping @calavera

**Comment by calavera** [comment]
@mgcrea can you provide more info about those mount points? Things that can be helpful:

1. How they were created in the the parent container.
2. Full run command for the child container.
3. Inspect information for the parent container with old docker version, both Volumes and VolumesRW.
4. Inspect information for the child container with old docker version, both Volumes and VolumesRW.
5. Old docker version and info.

**Comment by calavera** [comment]
@mgcrea for what it's worth, the error seems correct. But I'm trying to figure out why your volumes end up in that scenario. that ` "/srv/data": ""` means that the volume mounted in `/srv/data` doesn't have a source or a volume mounted from.

@jnummelin your issue doesn't seem related to this issue. Do you get any error log? Those paths seem correct.

**Comment by jnummelin** [comment]
@calavera The log shows pretty much the same messages:
```
Handler for POST /containers/{name:.*}/start returned error: Cannot start container d3737856bf4877866f824f96c54de29da02343819361b53bf6f53253f8a0f686: Unable to setup mount point, neither source nor volume defined 
 HTTP Error Cannot start container d3737856bf4877866f824f96c54de29da02343819361b53bf6f53253f8a0f686: Unable to setup mount point, neither source nor volume defined 
```
The paths are correct as the container works perfectly on 1.3.3 docker. We're seeing this issue only when trying to upgrade to Docker 1.7.0

**Comment by mgcrea** [comment]
@calavera 

The setup was something like this:

```
# docker run --volume /srv/data --name foo-bar.data.production ubuntu:trusty true
# docker run --detach --volumes-from foo-bar.data.production --name foo-bar.backend.production --expose 3030 --publish 127.0.0.1:3030:3030 --publish 172.17.42.1:3030:3030 --publish 10.100.0.1:3030:3030 --env NODE_ENV=production --env NODE_PORT=3030 --env CLIENT_ID=foo mgcrea/nodejs
```

`mgcrea/nodejs` is an image that starts supervisord (ssh+nodejs+redis+mongo)

I can't rollback docker because the server is currently in production with sensitive data.

**Comment by calavera** [comment]
thank you guys, that makes a lot of sense. It looks like there are something missing deserializing those old configurations into 1.7. I'll take a look.

**Comment by zergin** [comment]
This is not an issue with deserializing configs but (at least for me) with order of execution. I've made a simple test case to illustrate the point: https://gist.github.com/zergin/d0d526a0e5fce1070552 

@calavera This is a serious regression. It messes existing deployments that relay on ro/rw mounts for security. It works as expected with 1.6.2 and before.

It seems to be the same case as #14347
