### ISSUE TITLE
docker run fails with "Cannot start container XYZ: [8] System error: mountpoint for cgroup not found" on Amazon Linux AMI

### ISSUE THREAD

**Issue by cacti77** [docker/docker#14102]
This may be related to #13979 or #8791...

I installed docker on an m3.large Linux AMI:

    $ sudo yum update -y

    $ sudo yum install -y docker

    $ sudo service docker start
    Starting cgconfig service: Error: cannot mount hugetlb to /cgroup/hugetlb: No such file or directory /sbin/cgconfigparser; error loading /etc/cgconfig.conf: Cgroup mounting failed
    Failed to parse /etc/cgconfig.conf                         [FAILED]
    Starting docker:	                                   [  OK  ]

Unfortunately at the time I didn't notice the error message about cgconfig.conf above and ploughed on with...

    $ docker version
    Client version: 1.6.2
    Client API version: 1.18
    Go version (client): go1.3.3
    Git commit (client): 7c8fca2/1.6.2
    OS/Arch (client): linux/amd64
    Server version: 1.6.2
    Server API version: 1.18
    Go version (server): go1.3.3
    Git commit (server): 7c8fca2/1.6.2
    OS/Arch (server): linux/amd64

    $ docker pull hello-world
    latest: Pulling from hello-world
    a8219747be10: Pull complete 
    91c95931e552: Already exists 
    hello-world:latest: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
    Digest: sha256:aa03e5d0d5553b4c3473e89c8619cf79df368babd18681cf5daeb82aab55838d
    Status: Downloaded newer image for hello-world:latest

    $ docker run hello-world
    FATA[0000] Error response from daemon: Cannot start container af1e80bac06939464fc05f9ffa1cf41b9f19714ef461f696957ac212e5cdae0b: [8] System error: mountpoint for cgroup not found

After looking at @mbentley's comments in #8791 I did:

    $ sudo /etc/init.d/cgconfig status
    Stopped

    $ sudo /etc/init.d/cgconfig start
    Starting cgconfig service: Error: cannot mount hugetlb to /cgroup/hugetlb: No such file or directory
    /sbin/cgconfigparser; error loading /etc/cgconfig.conf: Cgroup mounting failed
    Failed to parse /etc/cgconfig.conf                         [FAILED]

    $ cat /etc/cgconfig.conf
    #
    #  Copyright IBM Corporation. 2007
    #
    #  Authors:	Balbir Singh <balbir@linux.vnet.ibm.com>
    #  This program is free software; you can redistribute it and/or modify it
    #  under the terms of version 2.1 of the GNU Lesser General Public License
    #  as published by the Free Software Foundation.
    #
    #  This program is distributed in the hope that it would be useful, but
    #  WITHOUT ANY WARRANTY; without even the implied warranty of
    #  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    #
    # See man cgconfig.conf for further details.
    #
    # By default, mount all controllers to /cgroup/<controller>

    mount {
        blkio      = /cgroup/blkio;
        cpu        = /cgroup/cpu;
        cpuacct    = /cgroup/cpuacct;
        cpuset     = /cgroup/cpuset;
        devices    = /cgroup/devices;
        freezer    = /cgroup/freezer;
        hugetlb    = /cgroup/hugetlb;
        memory     = /cgroup/memory;
        perf_event = /cgroup/perf_event;
    }

Note this Linux AMI was created using [Apache Spark's EC2 script](https://spark.apache.org/docs/latest/ec2-scripts.html), in case that helps at all. I then tried following [Amazon's instructions](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/docker-basics.html#install_docker) to install docker on the Spark Master node.

Do you know how to fix this please so I can run docker containers on AWS EC2?

Response to request for additional info:

    $ docker info
    Containers: 3
    Images: 21
    Storage Driver: devicemapper
     Pool Name: docker-202:1-131132-pool
     Pool Blocksize: 65.54 kB
     Backing Filesystem: extfs
     Data file: /dev/loop0
     Metadata file: /dev/loop1
     Data Space Used: 1.386 GB
     Data Space Total: 107.4 GB
     Data Space Available: 3.43 GB
     Metadata Space Used: 1.884 MB
     Metadata Space Total: 2.147 GB
     Metadata Space Available: 2.146 GB
     Udev Sync Supported: true
     Data loop file: /var/lib/docker/devicemapper/devicemapper/data
     Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
     Library Version: 1.02.89-RHEL6 (2014-09-01)
    Execution Driver: native-0.2
    Kernel Version: 3.4.37-40.44.amzn1.x86_64
    Operating System: Amazon Linux AMI 2015.03
    CPUs: 2
    Total Memory: 7.06 GiB
    Name: ip-172-31-25-17.eu-west-1.compute.internal
    ID: V3OX:6FI3:EJKR:47CJ:PCHE:U3VA:25NQ:FNQK:22VL:2F5N:IRY4:Z6XA
    Username: xerxes
    Registry: [https://index.docker.io/v1/]
    WARNING: No memory limit support
    WARNING: No swap limit support
    
    $ uname -a
    Linux ip-172-31-25-17.eu-west-1.compute.internal 3.4.37-40.44.amzn1.x86_64 #1 SMP Thu Mar 21 01:17:08 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

Expected results:
1) `sudo service docker start` returns:

    Starting cgconfig service:                                 [  OK  ]
    Starting docker:	                                   [  OK  ]

2) `docker run` actually starts a container!

My best guess is that either the installation of Spark on EC2 interferes with prereqs for docker; or maybe that the call to `sudo yum update -y` before installing docker somehow screwed up cgroups? This is speculation.

**Comment by cacti77** [comment]
Following @LK4D4 's comments in #13979 I fetched https://raw.githubusercontent.com/docker/docker/master/contrib/check-config.sh and ran it on my AMI:

    $ ./check-config.sh 
    warning: /proc/config.gz does not exist, searching other paths for kernel config...
    info: reading kernel config from /boot/config-3.4.37-40.44.amzn1.x86_64 ...

    Generally Necessary:
    - cgroup hierarchy: nonexistent??
        (see https://github.com/tianon/cgroupfs-mount)
    - CONFIG_NAMESPACES: enabled
    - CONFIG_NET_NS: enabled
    - CONFIG_PID_NS: enabled
    - CONFIG_IPC_NS: enabled
    - CONFIG_UTS_NS: enabled
    - CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled
    - CONFIG_CGROUPS: enabled
    - CONFIG_CGROUP_CPUACCT: enabled
    - CONFIG_CGROUP_DEVICE: enabled
    - CONFIG_CGROUP_FREEZER: enabled
    - CONFIG_CGROUP_SCHED: enabled
    - CONFIG_CPUSETS: enabled
    - CONFIG_MACVLAN: missing
    - CONFIG_VETH: enabled (as module)
    - CONFIG_BRIDGE: enabled (as module)
    - CONFIG_BRIDGE_NETFILTER: enabled
    - CONFIG_NF_NAT_IPV4: missing
    - CONFIG_IP_NF_FILTER: enabled (as module)
    - CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
    - CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
    - CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
    - CONFIG_NF_NAT: enabled (as module)
    - CONFIG_NF_NAT_NEEDED: enabled
    - CONFIG_POSIX_MQUEUE: enabled

    Optional Features:
    - CONFIG_MEMCG_SWAP: missing
    - CONFIG_MEMCG_SWAP_ENABLED: missing
    - CONFIG_RESOURCE_COUNTERS: enabled
    - CONFIG_BLK_CGROUP: enabled
    - CONFIG_IOSCHED_CFQ: enabled (as module)
    - CONFIG_CGROUP_PERF: enabled
    - CONFIG_CFS_BANDWIDTH: enabled
    - Storage Drivers:
      - "aufs":
        - CONFIG_AUFS_FS: missing
        - CONFIG_EXT4_FS_POSIX_ACL: enabled
        - CONFIG_EXT4_FS_SECURITY: enabled
      - "btrfs":
        - CONFIG_BTRFS_FS: enabled (as module)
      - "devicemapper":
        - CONFIG_BLK_DEV_DM: enabled (as module)
        - CONFIG_DM_THIN_PROVISIONING: enabled (as module)
        - CONFIG_EXT4_FS: enabled (as module)
        - CONFIG_EXT4_FS_POSIX_ACL: enabled
        - CONFIG_EXT4_FS_SECURITY: enabled
      - "overlay":
        - CONFIG_OVERLAY_FS: missing
        - CONFIG_EXT4_FS_SECURITY: enabled
        - CONFIG_EXT4_FS_POSIX_ACL: enabled
      - "zfs":
        - /dev/zfs: missing
        - zfs command: missing
        - zpool command: missing

**Comment by cacti77** [comment]
As per @LK4D4's comments in #13979 I then fetched https://raw.githubusercontent.com/tianon/cgroupfs-mount/master/cgroupfs-mount and ran that:

    $ sudo ./cgroupfs-mount 
    
    $ mount
    proc on /proc type proc (rw,relatime)
    sysfs on /sys type sysfs (rw,relatime)
    devtmpfs on /dev type devtmpfs (rw,relatime,size=3828016k,nr_inodes=957004,mode=755)
    devpts on /dev/pts type devpts (rw,relatime,gid=5,mode=620,ptmxmode=000)
    tmpfs on /dev/shm type tmpfs (rw,relatime,size=3727200k,nr_inodes=931800)
    /dev/xvda1 on / type ext4 (rw,noatime,data=ordered)
    /dev/xvdb on /mnt type ext3 (rw,noatime,nodiratime,errors=continue,user_xattr,acl,barrier=1,data=ordered)
    none on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
    cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
    cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
    cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
    cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
    cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
    cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
    cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
    cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)

Restarting docker still failed, however:

    $ sudo service docker restart
    Stopping docker:                                           [  OK  ]
    Starting cgconfig service: Error: cannot mount hugetlb to /cgroup/hugetlb: No such file or directory
    /sbin/cgconfigparser; error loading /etc/cgconfig.conf: Cgroup mounting failed
    Failed to parse /etc/cgconfig.conf                         [FAILED]
    Starting docker:	                                   [  OK  ]

but despite that I was still able to start the container now:

    $ docker run hello-world
    Hello from Docker.
    This message shows that your installation appears to be working correctly.
    ...<truncated>

**Comment by xujihui1985** [comment]
I was able to solve this problem by re mount the cgroup/devices

mount -t cgroup -o devices devices /cgroup/devices

**Comment by ianweller** [comment]
The hugetlb cgroup was added in kernel 3.10 on the Amazon Linux AMI, but your `docker info` output shows you are running kernel 3.4. If you're using the docker package from the Amazon Linux AMI yum repositories, it should have installed the new kernel as a dependency, but you still have to reboot to be running the latest kernel.

This specific problem doesn't appear to be a bug with docker, so I think this issue can be closed.

**Comment by cacti77** [comment]
@ianweller Thanks for looking at this. Unfortunately I no longer have the VM. Based on what you said, my guess is that the special AMIs used by the Spark EC2 script have an out-of-date kernel with respect to docker and that I should have rebooted the instance between doing `sudo yum install -y docker` and `sudo service docker start`.

I appreciate this is potentially an unusual combination of products - Spark EC2 and docker - but if all I had to do was reboot the instance it would've been nice if docker had told me something like that rather than the cryptic (to me) error message of `Starting cgconfig service: Error: cannot mount hugetlb to /cgroup/hugetlb: No such file or directory /sbin/cgconfigparser; error loading /etc/cgconfig.conf: Cgroup mounting failed` in response to `sudo service docker start`.  So I don't know if you want to use this issue as an opportunity to improve docker's error reporting?  Otherwise feel free to close this if you wish.

**Comment by ianweller** [comment]
Good call, @cacti77. I'll look into adding a check to the initscript in the Amazon Linux AMI to warn the user (in a less cryptic fashion) if they're currently running an unsupported kernel and need to reboot.

**Comment by cacti77** [comment]
Great - thanks very much @ianweller. I'm all for meaningful error messages:).

**Comment by thaJeztah** [comment]
Looks like this is not a Docker issue, so I'll close this one, but feel free to comment here if you think I closed by mistake

**Comment by cacti77** [comment]
@thaJeztah As long as @ianweller made the change he said he would do to provide a more meaningful error message in future, that's fine, thanks.
