### ISSUE TITLE
Can't build Dockerfiles located on FUSE filesystem

### ISSUE THREAD

**Issue by Jaykah** [docker/docker#14109]
I am using yas3fs to store my Dockerfiles on Amazon S3. The directory is then mounted to a dynamic slave (Docker-in-Docker), and the build is executed.

However, after upgrading from Docker 1.5 this no longer works:

```
Sending build context to Docker daemon 
Error response from daemon: Untar re-exec error: exit status 1: output: operation not supported
```

```
ln: failed to create symbolic link '/sys/fs/cgroup/systemd/name=systemd': Operation not permitted
time="2015-06-22T19:57:52.893937500Z" level=info msg="Listening for HTTP on unix (/var/run/docker.sock)"
time="2015-06-22T19:57:52.894842400Z" level=fatal msg="Error starting daemon: error initializing graphdriver: backing file system is unsupported for this graph driver"
```

docker version
```
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

docker info
```
Containers: 1
Images: 7
Storage Driver: vfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-55-generic
Operating System: Ubuntu 14.04.2 LTS (containerized)
CPUs: 4
Total Memory: 6.807 GiB
Name: Logstash1
ID: OMG5:2MN7:ZUQ2:D2JQ:S6AT:QHMI:SGFZ:TLY7:FDEI:HOZZ:M6RJ:TCST
WARNING: No swap limit support
```

uname -a
```
Linux Logstash1 3.13.0-55-generic #94-Ubuntu SMP Thu Jun 18 00:27:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.

**Comment by Jaykah** [comment]
@jfrazelle Thanks for your reply. Can you please clarify how the matter in question is related to Dockerfile syntax?

**Comment by jfrazelle** [comment]
It's not, sorry about that I'll reopen, can only blame github search :/ thanks for being proactive 

On Jul 13, 2015, at 08:27, Jay J <notifications@github.com> wrote:

@jfrazelle Thanks for your reply. Can you please clarify how the matter in question is related to Dockerfile syntax?

**Comment by SergeyCherepanov** [comment]
Hi!

Any way to fix it?

**Comment by Jaykah** [comment]
@SergeyCherepanov Switching to AUFS with a dynamic Docker 1.7.1 binary did it for me.
