### ISSUE TITLE
exec doesn't default to user specified in image anymore

### ISSUE THREAD

**Issue by michaelsauter** [docker/docker#14115]
In Docker <= 1.6.2, using `docker exec` defaults to the user specified in the image via `USER`.

In Docker 1.7.0, it defaults to `root`. Is this intended or a bug?

docker info:
```
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.16.0-37-generic
Operating System: Ubuntu 14.10
```

1.6.2 docker version:
```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

1.7.0 docker version:
```
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

Dockerfile:
```
FROM ubuntu:14.04
RUN   useradd -m -s /bin/bash default
USER  default
```

Steps to reproduce:
```
docker exec -it <container> bash
```

**Comment by dbartow** [comment]
I've also just noticed this.  Using the same `docker exec -it <container> bash --login` command I've been using for months now logs me in as root instead of the user specified in the Dockerfile.

**Comment by vagnerzampieri** [comment]
@michaelsauter use:
  
  `docker exec --user=user_name -it <container> bash`

**Comment by asazernik** [comment]
Not sure if this is intentional or not; the new manpages say this about the "--user" flag:

```
       -u, --user=""
          Sets the username or UID used and optionally the groupname or GID for the specified command.

       The followings examples are all valid:
          --user [user | user:group | uid | uid:gid | user:gid | uid:group ]

       Without this argument the command will be run as root in the container.
```

So this seems to be intentional, but I'm not sure if whoever made this decision thought about the consequences (specifically, scripts currently using 'docker exec' that are now broken because they assumed it would respect the container's `USER` property by default).

**Comment by asazernik** [comment]
Paging @coolljt0725 

The `--user` flag is awesome, but the default when the flag is not given is bad and breaks existing scripts.

**Comment by michaelsauter** [comment]
@vagnerzampieri Thanks. I know could use that, but as @asazernik said, it breaks current scripts, and `--user` is not available in 1.6.2, so I can't easily add it to the scripts without breaking functionality for my team mates who are still on 1.6.2. It would be good to have at least one transition version where the default is unchanged.

Besides, I think it is quite reasonable to assume that the default user should be the one specified in the image, not root.

@cpuguy83 Does that mean the default is going to change again for 1.7.1?

**Comment by vagnerzampieri** [comment]
@cpuguy83 +1 ... thanks :)

**Comment by cpuguy83** [comment]
It means I intend to look at this to see if it's really a breakage and fix for 1.7.1 if the break was unintentional :)

**Comment by LK4D4** [comment]
@cpuguy83 This is definetely a bug. You should set `processConfig.User` to `container.Config.User` if `config.User == ""` in `ContainerExecCreate`.

**Comment by icecrime** [comment]
@cpuguy83 Do you take that one?

**Comment by calavera** [comment]
@cpuguy83, @LK4D4, @icecrime review #14218, please.

**Comment by cpuguy83** [comment]
Thanks guys. Been on flights all day.

**Comment by Ericwonne** [comment]
There is no -u nor --user option in my docker, whose version is 1.6.2. And I currently now could not upgrade the docker version. How can I gain root privilege?

**Comment by thaJeztah** [comment]
@Ericwonne Docker 1.6.2 is really old; it was [released in may 2015](https://github.com/moby/moby/releases/v1.6.2), and reached EOL in _June_ 2015. After that date, it has not received any updates, and there's known vulnerabilities in those old versions (including possible container escapes, where the container can obtain full `root` access on the host).

I would _highly_ recommend updating to a current version

**Comment by Ericwonne** [comment]
Yeah, thanks for your advice. Looks like mine is really old.

**Comment by thaJeztah** [comment]
Note that there was a regression found recently in this area; see https://github.com/moby/moby/issues/38865 (fix being worked on in https://github.com/moby/moby/pull/38871)
