### ISSUE TITLE
DOCKER_TLS_VERIFY

### ISSUE THREAD

**Issue by catuss-a** [docker/docker#14129]
when setting docker_tls_verify to 0 instead of 1 then I get this error from the client:
'FATA[0000] An error occured when trying to connect: .... tls: oversized recored received with length 20527'

working: setting DOCKER_TLS_VERIFY='' or get rid of the env variable.

edit: osx

**Comment by cpuguy83** [comment]
Yes, if the env var is set at all, it is assumed you want to use TLS verification (and enables TLS).
Closing as this is expected behavior.

**Comment by nickdgriffin** [comment]
Hi @cpuguy83 , is there a reason why it only works that way rather than 0 being a valid value for TLS being disabled?

**Comment by gesellix** [comment]
I would also be interested to know why an explicit value of 0 is ignored. In case you'd be open to change that behaviour, I'd be happy to provide a PR.
