### ISSUE TITLE
docker/contrib/dockerize-disk.sh script doesn't take into account system locale

### ISSUE THREAD

**Issue by Tim-Ur** [docker/docker#14123]
Добрый день. Когда вы используйте sed для анализа ответа diff, вы не учитываете, что diff не всегда отвечает на английском. Для русифицированной версии Ubuntu я изменил строку 79 на:
```Shell
  | sed -re "s|Только в workdir(.*?): |DEL \1/|g;s|Только в disk_image(.*?): |ADD \1/|g;s|Файлы disk_image/(.+) и workdir/(.+) различаются|UPDATE /\1|g" \
```
и всё заработало. Ничего сложного, но есть повод подумать над более изящным решением.

**Comment by thaJeztah** [comment]
Thanks for opening an issue @Tim-Ur, I can't read Russian, but I heard that the author of that script might be able to.

@maximkulkin (hope I'm correct that you are able to read this issue), could you have a look here? Thanks!

**Comment by maximkulkin** [comment]
Ok, here is issue translation for the records:

> docker/contrib/dockerize-disk.sh script doesn't take into account system locale. When processing output of diff when comparing disk file trees, script assumes diff messages in English, but if system locale is different, this won't work.

My take on this is to do
```
export LANG=en_US.UTF8
```
at top of the script (or at least when running diff) to enforce messages to be in English.

**Comment by crosbymichael** [comment]
@LK4D4 TRANSLATE!!!!!

**Comment by thaJeztah** [comment]
>Ok, here is issue translation for the records:

Thanks @maximkulkin !
