### ISSUE TITLE
How to create a mirror of official hub

### ISSUE THREAD

**Issue by liudonghua123** [docker/docker#14121]
In my work place, a lot of people use docker, and they pull the images from official `registry.hub.docker.com` site. I want to create a mirror so that these people can configure (add `–registry-mirror=http://my_own_registry_mirror_site`) to pull from my synchronized mirror.
I read the documentation and only find some useful link like `https://docs.docker.com/reference/api/hub_registry_spec/`, `https://github.com/docker/distribution/blob/master/docs/deploying.md`, however, I don't quite understand, can anyone show me some simple explanation about how to create a mirror of official hub.
More specifically, how much stroage should it takes if I want to create a complete mirror?
Thanks in advance!

**Comment by cpuguy83** [comment]
@liudonghua123 You should ask this on #docker-distribution on IRC, or in the docker-user mailing list. Since GH Issues isn't really a great forum for this kind of thing, I'm going to close this issue, but do please hop on IRC or docker-user to get some help with this.

Thanks!
