### ISSUE TITLE
libnetwork: a container has already joined the endpoint

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#14132]
running a container with the same name as one that was already deleted fails:

```
Error response from daemon: Cannot start container f1eff556ccad06993d833ef2aa04569914579a2531f8fe8a1daba42c2b1431f7: a container has already joined the endpoint
```

this is on master.... and NOT experiemtnal

**Comment by mavenugo** [comment]
@jfrazelle thanks. we will take a look at it asap.

**Comment by tomdee** [comment]
The issue tracking this on the experimental build is #14107

**Comment by mavenugo** [comment]
@jfrazelle I could reproduce the problem with containers launched with `--net=host`, but not with other modes. Does that fit your use-case well ?

**Comment by jfrazelle** [comment]
I think so yeah

**Comment by petejcullen** [comment]
I get the same problem running "hello-world"

$ docker run hello-world
Error response from daemon: Cannot start container 58d26f5c20e7c81fa7349b47d5668cd6742f991ccac9195203e0a98de156e278: invalid argument

**Comment by mavenugo** [comment]
@petejcullen the error doesn't seem to match what @jfrazelle reported.
Can you please confirm ?

**Comment by petejcullen** [comment]
@mavenugo you are right! apologies, I'll log a new issue. I must have seen the error in another thread somewhere, but ended up commenting on this one!
