### ISSUE TITLE
DOCKER_OPTS not being honored on debian 8

### ISSUE THREAD

**Issue by jgkamat** [docker/docker#14130]
This seems like a really simple fix, but I wanted to get someone's opinion before adding this:
The [default systemd service file](https://github.com/docker/docker/blob/master/contrib/init/systemd/docker.service) dosen't seem to be appending DOCKER_OPTS to the docker daemon, or sourcing /etc/default/docker. Since debian 8 uses systemd, the DOCKER_OPTS variable is ignored, as it is not appended in the file. A fix would be adding these lines to systemd.service
```
[Unit]
...

[Service]
ExecStart=/usr/bin/docker -d -H fd:// $DOCKER_OPTS
EnvironmentFile=-/etc/default/docker
...

[Install]
...
```

Adding this fixes the problem, but it would be nice if this could be put upstream as well, so we don't need to keep changing this file manually. Would this affect any other setups? Any other thoughts?

Info:
```
Containers: 0
Images: 0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 8
Total Memory: 7.701 GiB
Name: laythe
ID: TLY3:UEE7:RDSD:6N5I:EKLN:EHHT:WQDU:RAH5:TKNT:Y6BD:CH6V:LOBK
WARNING: No memory limit support
WARNING: No swap limit support
```
version:
```
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

**Comment by jgkamat** [comment]
Description of problem:
DOCKER_OPTS not honored. See above

`docker version`:
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64

`docker info`:
Containers: 0
Images: 0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 8
Total Memory: 7.701 GiB
Name: laythe
ID: TLY3:UEE7:RDSD:6N5I:EKLN:EHHT:WQDU:RAH5:TKNT:Y6BD:CH6V:LOBK
WARNING: No memory limit support
WARNING: No swap limit support

`uname -a`:
Linux laythe 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
Physical machine

How reproducible:
Always

Steps to Reproduce:
1. Add options to DOCKER_OPTS in /etc/default docker
2. Restart docker daemon

Actual Results:
DOCKER_OPTS not honored

Expected Results:
DOCKER_OPTS appended to docker -d command

Additional info:
See above.

**Comment by cpuguy83** [comment]
This is maintained in `contrib/init` if you want to submit  PR.

**Comment by jgkamat** [comment]
:+1: will go ahead and do that!

**Comment by calavera** [comment]
See #14130 for more information
