### ISSUE TITLE
Experimental build doesn't work easily in boot2docker 

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#14138]
Talking with @kbastani and he wanted to test the Swarm stuff in multi-host environment. He is on Mac.  We either need to fix this issue or maybe document a work around.

**Comment by slajax** [comment]
I'm also attempting to set up the experimental build using boot2docker but I'm getting this:

```
❯ docker ps -a                                                                                                                                                
Error response from daemon: client and server don't have same version (client API version: 1.20, server API version: 1.19)
```

If I try to do docker-machine upgrade, it upgrades to 1.7.0, but it looks like I need it to upgrade the remote server to 1.8.0-dev for the API versions to match.

I tried ssh'ing into machine to manually upgrade docker binary, but had no luck due to permissions. If anyone has a work around, I'm happy to try it.

**Comment by moxiegirl** [comment]
I'm sitting with Vieux and if you are trying to deploy to local VM via boot2docker, he said that is unlikely to work. He recommends you deploy to a cloud provider like Digital Ocean or Cloud. Then deploy experimental through machine to onto  the cloud instances.

**Comment by ahbeng** [comment]
Found this issue while trying to use the experimental build with Boot2Docker. I've built an image which builds a customized Boot2Docker ISO containing the experimental build, with usage instructions for Docker Machine and Boot2Docker CLI.

[Boot2DockerExperimental on Docker Hub](https://registry.hub.docker.com/u/ahbeng/boot2docker-experimental/), [Boot2DockerExperimental on GitHub](https://github.com/ahbeng/boot2docker-experimental)

It's currently set to rebuild whenever [boot2docker/boot2docker](https://registry.hub.docker.com/u/boot2docker/boot2docker/) or [dockercore/docker](https://registry.hub.docker.com/u/dockercore/docker/) are updated, so the ISO from the image should always be updated, but the image is ~2.1 GB.

I've hosted the [latest copy](https://github.com/ahbeng/boot2docker-experimental/releases/latest) of the ISO (~ 28 MB) on GitHub Releases. I added a `sha256sum` call to the Dockerfile, but the build logs on Docker Hub aren't visible to public. I'm not sure if there would be another way to verify that the uploaded ISO comes from a trusted automated build - the ISO's hash changes with every rebuild, so even if you downloaded the image yourself it might not match.

This suffices for my usage, but if more people are interested in using it, the ISO releases could be automated using the GitHub API.

**Comment by cpuguy83** [comment]
ping @tianon

**Comment by cpuguy83** [comment]
Opend boot2docker/boot2docker#1061
Closing this one.
Thanks!
