### ISSUE TITLE
Proposal: add --label flag to `docker build`

### ISSUE THREAD

**Issue by tony-spataro-rs** [docker/docker#14144]
Use case: I want to tag my images with metadata such as the SCM branch name or revision from which the image was built.

Counter-argument: determinism is very important during the build process, which is why all state involved in a build (env, files, labels) comes from the Dockerfile or the build context.

Rebuttal to counter-argument: labels typically don't govern the behavior of containers; rather, they're intended as a way to add arbitrary metadata to containers (and to images, so that the metadata will appear in containers derived from that image). It seems reasonable that some metadata might be contextual to the image build.

Alternatives considered:
1) Adding a subset of .git to the container (or otherwise adding metadata in the form of files). This works, but it's hard to view the metadata from the host, or to make decisions based on the metadata without actually running a container from the image.
2) Running the built image using `--label` and then re-committing the (hopefully) unchanged image. Also works, but boy, what a hack!

I'd be happy to submit a PR for this feature, but wanted to see how it was received by the community.

**Comment by cpuguy83** [comment]
I'm personally fine with this.
Labels are benign and do not affect the image or the resulting container.

**Comment by duglin** [comment]
Seems ok to me too.  Sure would be nice if there was a way to add a label outside of `docker build` too. Something like: `docker image label foo=bar`  but that's a bigger discussion ( https://github.com/docker/docker/issues/13509 )

**Comment by curator** [comment]
I would very much like this.  My organization generates a variety of build metadata prior and through the image build process (build tags and numbers, upstream components, git sha, build actuator, etc.) and it would be nice to keep this metadata around with the image without having to dynamically generate what is otherwise a static Dockerfile.

**Comment by thaJeztah** [comment]
Seems like we're fine with this; @cpuguy83 @duglin either of you willing to create a PR? :innocent:

**Comment by duglin** [comment]
okie dokie!  #dibs

**Comment by thaJeztah** [comment]
Thanks @duglin (was skimming through my notifications and spotted this one) :smile:

**Comment by vdemeester** [comment]
@duglin @thaJeztah isn't this like #13412 ? :stuck_out_tongue_closed_eyes:

**Comment by thaJeztah** [comment]
@vdemeester oh! you're right, it did sound familiar. Looks like there's no consensus on this then, and @icecrime didn't want to go this path. :-/

**Comment by duglin** [comment]
I think we should reopen #13412.
@icecrime we are adding 'ENV" ( https://github.com/docker/docker/pull/15182 ).
Ignoring for a moment the idea of "moving Dockerfile commands to the build cmd line", I think we need to look at this more generically and ask:
- does it make sense to dynamically add labels to images? I think so (and I thought I saw an issue or PR about this but I can't seem to find it)
- do we always know what labels at Dockerfile creation time we want to assign to an image? I don't think so

So, rather than worry about opening a "bad door" I think we need to examine the usecases that @tony-spataro-rs mentioned and asked if they're valid and ones we want to support.  I think they are.

**Comment by tony-spataro-rs** [comment]
I commented on #13412 with some justification for my position that `LABEL` has different purpose from `ENV`, `VOLUME` or `EXPOSE` (at least for the use cases I'm concerned with). Much thanks for your consideration -- and kudos to @vdemeester for actually writing some code to back up his position!

**Comment by vdemeester** [comment]
@tony-spataro-rs as commented by @thaJeztah there https://github.com/docker/docker/issues/13178#issuecomment-146449261 it is now possible to setup *dynamic* lables using build. Quoting :

```Dockerfile
FROM ubuntu:14.04

# Define the "foo" arg and set a default value
ARG foo=defaultfoo

# Create a label "mylabel" and set it to the value of $foo
LABEL mylabel=$foo
```


Building without passing a build-time arg:

```
docker build -t foo .
docker inspect foo
```

produces:

```
...
"Labels": {
    "mylabel": "defaultfoo"
},
...
```

And specifying a custom value:

```
docker build -t foo --build-arg foo=commit123 .
docker inspect foo
```

produces:
```
...
"Labels": {
    "mylabel": "commit123"
},
...
```

I think this handle your use-case, so maybe this issue could be closed ? What do you think ? :wink:

**Comment by tony-spataro-rs** [comment]
Agreed; build args are a more general way of doing what I need to. I'll close this issue in favor of #13178; thanks.

**Comment by thaJeztah** [comment]
Thanks @tony-spataro-rs !

**Comment by mydevbox** [comment]
This is an okay alternative to adding a --label flag to build however, the fact that you can add only one ARG key=value per line or you get this error 'ARG requires exactly one argument definition' is quite a shame. This means that if you have 5+ labels to set you'll generate at least 6 extra layers. That's 5 for each ARG key=value line plus the LABEL if you specify them all together using \.

**Comment by xeger** [comment]
The proliferation of layers is annoying, but I expect that `docker build` will be changing sooner or later to distinguish between commands that require a new layer and those that do not. (Certainly `ARG` or `MAINTAINER` should not require a new layer, and possibly things like `LABEL`, depending on how labels are implemented.)

**Comment by thaJeztah** [comment]
@xeger have a look at https://github.com/docker/docker/pull/17924, which (among other advantages), will do that.

**Comment by xeger** [comment]
@thaJeztah that is a very bold change, sir! Props to you all for having the chutzpah to do this in a backward-compatible way.
