### ISSUE TITLE
TCPDump in privileged mode

### ISSUE THREAD

**Issue by imehrdad2012** [docker/docker#14140]
Hi All,

When I run an ubuntu container with privileged mode which is needed to run Mininet, I cannot successfully install tcpdump. What's the solution for the error: libcrypto.so.1.0.0: cannot open shared object file: Permission denied?

To reproduce this issue: 
sudo docker run --name="ryu-mininet" --privileged=true -it imehrdad2012/mininet /bin/bash
root@152f3f17bef3:/# sudo apt-get install tcpdump
tcpdump: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: Permission denied

---- More information: 
docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64

Linux beirut 3.13.0-53-generic #89-Ubuntu SMP Wed May 20 10:34:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

docker info
Containers: 3
Images: 6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 12
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-53-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 32
Total Memory: 125.9 GiB
Name: beirut
ID: NRMH:IAGL:AIND:5ZDM:4O6Y:X6CB:EEPJ:HRSN:3KLK:RZ2N:EHVN:ZJC4
Username: imehrdad2012
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

**Comment by phemmer** [comment]
I am unable to duplicate

```
# docker run -ti --privileged imehrdad2012/mininet bash -c 'apt-get install -y tcpdump && ( ping -c 10 google.com & tcpdump -i eth0 -c 1 )'                                                                                                                        
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  libpcap0.8
Suggested packages:
  apparmor
The following NEW packages will be installed:
  libpcap0.8 tcpdump
0 upgraded, 2 newly installed, 0 to remove and 3 not upgraded.
Need to get 464 kB of archives.
After this operation, 1445 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu/ trusty/main libpcap0.8 amd64 1.5.3-2 [110 kB]
Get:2 http://archive.ubuntu.com/ubuntu/ trusty-updates/main tcpdump amd64 4.5.1-2ubuntu1.2 [355 kB]
Fetched 464 kB in 7s (60.7 kB/s)                                               
Selecting previously unselected package libpcap0.8:amd64.
(Reading database ... 23224 files and directories currently installed.)
Preparing to unpack .../libpcap0.8_1.5.3-2_amd64.deb ...
Unpacking libpcap0.8:amd64 (1.5.3-2) ...
Selecting previously unselected package tcpdump.
Preparing to unpack .../tcpdump_4.5.1-2ubuntu1.2_amd64.deb ...
Unpacking tcpdump (4.5.1-2ubuntu1.2) ...
Setting up libpcap0.8:amd64 (1.5.3-2) ...
Setting up tcpdump (4.5.1-2ubuntu1.2) ...
Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 65535 bytes
PING google.com (216.58.192.110) 56(84) bytes of data.
64 bytes from mia07s35-in-f14.1e100.net (216.58.192.110): icmp_seq=1 ttl=54 time=12.2 ms
64 bytes from mia07s35-in-f14.1e100.net (216.58.192.110): icmp_seq=2 ttl=54 time=13.1 ms
21:54:48.071931 IP google-public-dns-a.google.com.domain > 41c3004c8ee1.60754: 63484 1/0/0 A 216.58.192.110 (44)
1 packet captured
9 packets received by filter
0 packets dropped by kernel
```

**Comment by imehrdad2012** [comment]
The following is the output of your commands on around 10 different machines with Ubuntu 14.04. May I know your host OS and kernel version? I learnt there are some problems with apparmor but I am not expert on this.

docker run -ti --privileged imehrdad2012/mininet bash -c 'apt-get install -y tcpdump && ( ping -c 10 google.com & tcpdump -i eth0 -c 1 )'
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  libpcap0.8
Suggested packages:
  apparmor
The following NEW packages will be installed:
  libpcap0.8 tcpdump
0 upgraded, 2 newly installed, 0 to remove and 3 not upgraded.
Need to get 464 kB of archives.
After this operation, 1445 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu/ trusty/main libpcap0.8 amd64 1.5.3-2 [110 kB]
Get:2 http://archive.ubuntu.com/ubuntu/ trusty-updates/main tcpdump amd64 4.5.1-2ubuntu1.2 [355 kB]
Fetched 464 kB in 0s (1589 kB/s)
Selecting previously unselected package libpcap0.8:amd64.
(Reading database ... 23224 files and directories currently installed.)
Preparing to unpack .../libpcap0.8_1.5.3-2_amd64.deb ...
Unpacking libpcap0.8:amd64 (1.5.3-2) ...
Selecting previously unselected package tcpdump.
Preparing to unpack .../tcpdump_4.5.1-2ubuntu1.2_amd64.deb ...
Unpacking tcpdump (4.5.1-2ubuntu1.2) ...
Setting up libpcap0.8:amd64 (1.5.3-2) ...
Setting up tcpdump (4.5.1-2ubuntu1.2) ...
Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
tcpdump: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: Permission denied

**Comment by phemmer** [comment]
It probably is apparmor, and there I'm clueless. My system is gentoo, 3.13.2. But no apparmor here.

**Comment by bprodoehl** [comment]
This is kind of a dup of #5490.  My suggestion if you just want tcpdump is to move the tcpdump binary in the container.  So after installing it, if it resides at /usr/sbin/tcpdump, move it to /usr/bin/tcpdump, and then run it.  This is easy to bake into the Dockerfile, with something like this:

```
RUN apt-get install -y tcpdump
# HACK around https://github.com/dotcloud/docker/issues/5490
RUN mv /usr/sbin/tcpdump /usr/bin/tcpdump
```

**Comment by imehrdad2012** [comment]
@bprodoehl Thanks for the response both here and there. I was able to solve the problem for tcpdump using your quick solution. However, what is the longterm solution of the docker development team for this problem as I was able to reproduce the same problem on many different machines. Is that something we should fix or they will plan to do?

**Comment by bprodoehl** [comment]
By "many different machines" you mean all Ubuntu hosts running AppArmor and Ubuntu guests running in privileged mode, right?  @ewindisch said that the stuff in #5490 will get merged, but there are other higher-priority tasks around AppArmor.  I'm not expecting a fix in the mainstream for another couple releases.  He may be able to shed more light on it.

**Comment by imehrdad2012** [comment]
Yes. I meant containers running with privileged mode in different ubuntu machines with various kernel versions.  In the mean time, It would be great if you can provide more details on how one can allow privileged containers to use "unconfined-profiles" by modifying AppArmor.

**Comment by cpuguy83** [comment]
ping @ewindisch Is this resolved with the new AppArmor stuff you've been doing?

**Comment by ewindisch** [comment]
@cpuguy83 yes, this should now be resolved with #14855 and may be closed

**Comment by cpuguy83** [comment]
Excellent, thanks!

**Comment by phemmer** [comment]
Just a FYI, this does not appear resolved. I just launched a brand new ubuntu 14.04 instance on GCE, installed docker with VIA `curl -sSL https://get.docker.com/ | sh` (which installed docker 1.9.1), and was unable to use tcpdump with the exact same error.

**Comment by bprodoehl** [comment]
Yeah, I've been meaning to reopen this one. I'm seeing the same thing.

**Comment by cpuguy83** [comment]
Confirmed

**Comment by jfrazelle** [comment]
im checking again now, ive redone a bit of apparmor stuff

**Comment by jfrazelle** [comment]
this works:

```
root@jess-apparmor-test:~# docker run -ti --cap-add net_admin ubuntu:trusty bash -c 'apt-get update && apt-get install -y tcpdump && ( ping -c 10 google.com & tcpdump -i eth0 -c 1 )'
Ign http://archive.ubuntu.com trusty InRelease
Get:1 http://archive.ubuntu.com trusty-updates InRelease [64.4 kB]
...
Get:20 http://archive.ubuntu.com trusty/universe amd64 Packages [7589 kB]
Fetched 21.4 MB in 8s (2650 kB/s)                                              
Reading package lists... Done
Reading package lists... Done
Building dependency tree        
Reading state information... Done
The following extra packages will be installed:
  libpcap0.8
Suggested packages:
  apparmor
The following NEW packages will be installed:
  libpcap0.8 tcpdump
0 upgraded, 2 newly installed, 0 to remove and 2 not upgraded.
Need to get 464 kB of archives.
After this operation, 1445 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu/ trusty/main libpcap0.8 amd64 1.5.3-2 [110 kB]
Get:2 http://archive.ubuntu.com/ubuntu/ trusty-updates/main tcpdump amd64 4.5.1-2ubuntu1.2 [355 kB]
Fetched 464 kB in 0s (2801 kB/s)
Selecting previously unselected package libpcap0.8:amd64.
(Reading database ... 11542 files and directories currently installed.)
Preparing to unpack .../libpcap0.8_1.5.3-2_amd64.deb ...
Unpacking libpcap0.8:amd64 (1.5.3-2) ...
Selecting previously unselected package tcpdump.
Preparing to unpack .../tcpdump_4.5.1-2ubuntu1.2_amd64.deb ...
Unpacking tcpdump (4.5.1-2ubuntu1.2) ...
Setting up libpcap0.8:amd64 (1.5.3-2) ...
Setting up tcpdump (4.5.1-2ubuntu1.2) ...
Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
PING google.com (74.125.226.169) 56(84) bytes of data.
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 65535 bytes
64 bytes from lga15s45-in-f9.1e100.net (74.125.226.169): icmp_seq=1 ttl=58 time=1.33 ms
64 bytes from lga15s45-in-f9.1e100.net (74.125.226.169): icmp_seq=2 ttl=58 time=1.33 ms
21:22:52.126294 IP google-public-dns-a.google.com.domain > c88a9a2b1b9d.35027: 8096 1/0/0 PTR lga15s45-in-f9.1e100.net. (83)
1 packet captured
5 packets received by filter
0 packets dropped by kernel
```

**Comment by necto** [comment]
@jfrazelle , that worked, but this:

    $ docker run -ti --cap-add net_admin ubuntu:trusty bash -c 'apt-get update && apt-get install -y tcpdump && ( ping -c 10 google.com & tcpdump -i eth0 -c 1 )'

does not:

    Ign http://archive.ubuntu.com trusty InRelease
    Get:1 http://archive.ubuntu.com trusty-updates InRelease [64.4 kB]
    Get:2 http://archive.ubuntu.com trusty-security InRelease [64.4 kB]
    Hit http://archive.ubuntu.com trusty Release.gpg     
    Hit http://archive.ubuntu.com trusty Release         
    Get:3 http://archive.ubuntu.com trusty-updates/main Sources [309 kB]
    Get:4 http://archive.ubuntu.com trusty-updates/restricted Sources [5219 B]
    Get:5 http://archive.ubuntu.com trusty-updates/universe Sources [183 kB]
    Get:6 http://archive.ubuntu.com trusty-updates/main amd64 Packages [851 kB]
    Get:7 http://archive.ubuntu.com trusty-updates/restricted amd64 Packages [23.4 kB]
    Get:8 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [431 kB]
    Get:9 http://archive.ubuntu.com trusty-security/main Sources [128 kB]
    Get:10 http://archive.ubuntu.com trusty-security/restricted Sources [3920 B]
    Get:11 http://archive.ubuntu.com trusty-security/universe Sources [36.5 kB]
    Get:12 http://archive.ubuntu.com trusty-security/main amd64 Packages [495 kB]
    Get:13 http://archive.ubuntu.com trusty-security/restricted amd64 Packages [20.2 kB]
    Get:14 http://archive.ubuntu.com trusty-security/universe amd64 Packages [158 kB]
    Get:15 http://archive.ubuntu.com trusty/main Sources [1335 kB]                 
    Get:16 http://archive.ubuntu.com trusty/restricted Sources [5335 B]            
    Get:17 http://archive.ubuntu.com trusty/universe Sources [7926 kB]             
    Get:18 http://archive.ubuntu.com trusty/main amd64 Packages [1743 kB]          
    Get:19 http://archive.ubuntu.com trusty/restricted amd64 Packages [16.0 kB]    
    Get:20 http://archive.ubuntu.com trusty/universe amd64 Packages [7589 kB]      
    Fetched 21.4 MB in 24s (879 kB/s)                                              
    Reading package lists... Done
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    The following extra packages will be installed:
      libpcap0.8
    Suggested packages:
      apparmor
    The following NEW packages will be installed:
      libpcap0.8 tcpdump
    0 upgraded, 2 newly installed, 0 to remove and 2 not upgraded.
    Need to get 464 kB of archives.
    After this operation, 1445 kB of additional disk space will be used.
    Get:1 http://archive.ubuntu.com/ubuntu/ trusty/main libpcap0.8 amd64 1.5.3-2 [110 kB]
    Get:2 http://archive.ubuntu.com/ubuntu/ trusty-updates/main tcpdump amd64 4.5.1-2ubuntu1.2 [355 kB]
    Fetched 464 kB in 1s (343 kB/s) 
    Selecting previously unselected package libpcap0.8:amd64.
    (Reading database ... 11542 files and directories currently installed.)
    Preparing to unpack .../libpcap0.8_1.5.3-2_amd64.deb ...
    Unpacking libpcap0.8:amd64 (1.5.3-2) ...
    Selecting previously unselected package tcpdump.
    Preparing to unpack .../tcpdump_4.5.1-2ubuntu1.2_amd64.deb ...
    Unpacking tcpdump (4.5.1-2ubuntu1.2) ...
    Setting up libpcap0.8:amd64 (1.5.3-2) ...
    Setting up tcpdump (4.5.1-2ubuntu1.2) ...
    Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
    tcpdump: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: Permission denied

And, e.g., for my case I need privileged in order to use hugepages for DPDK:

    docker exec vnds_nat mkdir /mnt/huge
    docker exec vnds_nat mount -t hugetlbfs nodev /mnt/huge
    docker exec vnds_nat sh -c 'echo 384 > /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages'

these commands work only if the container were `run` in a `--privileged` mode.

**Comment by GeoffreyVDB** [comment]
Any news on this? Just ran into this problem on a container that needs privileged mode for virtualbox

**Comment by randunel** [comment]
This does not appear to have been fixed. 1.11.2.

**Comment by abhilashgupta** [comment]
Hi,
Confirmed to not be fixed in Docker 1.11.2.
As suggested by @bprodoehl , when I moved tcpdump to /usr/bin, I got a new error:
bash: /usr/bin/tcpdump: No such file or directory.

My path variable is:
root@fpc0]$echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

System details:
abhilash@abhilash-VirtualBox:~$ docker --version
Docker version 1.11.2, build b9f10c9
abhilash@abhilash-VirtualBox:~$ uname -a
Linux abhilash-VirtualBox 3.13.0-32-generic #57~precise1-Ubuntu SMP Tue Jul 15 03:51:20 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Is there any fix for or hack around this issue?

**Comment by RobinCutshaw** [comment]
Run "hash -r" to rehash your path after the binary move.

**Comment by sp576** [comment]
Instead of `--privileged` option, try `--cap-add net_admin`. Then it worked for me.

**Comment by Kent-H** [comment]
This is still broken (as of 17.03.1-ce).  Please reopen.

**Comment by peterhorvath** [comment]
it happens with debian 9.2 newest docker/docker-compose if started in privileged mode
`root@dcad848392c1:~# tcpdump -nn port 9000 -A
tcpdump: error while loading shared libraries: libcrypto.so.1.0.2: cannot stat shared object: Permission denied
`

**Comment by RobinCutshaw** [comment]
Try copying the tcpdump binary to /usr/local/bin and run it from there
using the full path.  I had this happen in another container.  Sounds weird
but it worked.

Robin

**Comment by ffahri** [comment]
@RobinCutshaw yep thats working for me too interesting and thanks

**Comment by leslie-qiwa** [comment]
Still see this issue at ubuntu 18.04. After moving tcpdump binary, it works. I think it should be resolved without this trick.
