### ISSUE TITLE
why I can't get the experimental docker binary

### ISSUE THREAD

**Issue by wf2004081522** [docker/docker#14157]
Hi, 

I want to try out some new feature of docker like build-in networking and plugin mechanism, so i followed the instruction on https://github.com/docker/docker/tree/master/experimental to use "wget -qO- https://experimental.docker.com/ | sh" to install it, but what I got is not what i want, the installed docker is is still 1.6(docker-io-1.6.0-4.git350a636.fc21.x86_64) rather than 1.7, my system is fedora 21. I just glimpsed the script in "https://experimental.docker.com", it look like just to use yum to install the docker, how can it get experimental version? who knows how to get the experimental docker binary?

best regards.

**Comment by phemmer** [comment]
Looks like a dup of #14146

**Comment by wf2004081522** [comment]
it's true, i will close this issue and comment on old one, thanks
