### ISSUE TITLE
formatting issue on the fedora install docs

### ISSUE THREAD

**Issue by vieux** [docker/docker#14165]
See https://docs.docker.com/installation/fedora/

![screen shot 2015-06-24 at 12 11 24](https://cloud.githubusercontent.com/assets/1032519/8339170/7a0a9f02-1a6a-11e5-8361-a9101b8374dd.png)

**Comment by ChanderG** [comment]
There is a minor problem with the Prerequisites heading just above this.

**Comment by thaJeztah** [comment]
The table rendering issue was fixed in https://github.com/docker/docker/issues/14392 (docs website not updated yet), more changes coming in https://github.com/docker/docker/issues/14276
