### ISSUE TITLE
Docker build will not run, no output

### ISSUE THREAD

**Issue by jasonsemko** [docker/docker#14172]
BUG REPORT INFORMATION

    Mac 10.9.5
    Client version: 1.7.0
    Client API version: 1.19
    Go version (client): go1.4.2
    Git commit (client): 0baf609
    OS/Arch (client): darwin/amd64
    Server version: 1.7.0
    Server API version: 1.19
    Go version (server): go1.4.2
    Git commit (server): 0baf609
    OS/Arch (server): linux/amd64

Provide additional environment details (AWS, VirtualBox, physical, etc.):
    VirtualBox: 4.3

List the steps to reproduce the issue:
1. Create a Dockerfile, any valid content appears to reproduce issue
2. Run the following command in same directory as Dockerfile
    
    docker build .

Describe the results you received: There is no output, several minutes have gone by
Describe the results you expected: Output / Progress for building ubuntu
Provide additional info you think is important: 
    
    docker build git://github.com/jbfink/docker-lampstack.git

The above command works fine.

![dockerissue](https://cloud.githubusercontent.com/assets/422906/8344784/88c2b7de-1a9a-11e5-98cf-cd8e511cbcdf.jpg)

----------END REPORT ---------

#ENEEDMOREINFO

**Comment by duglin** [comment]
what is in your current dir?  If its large then it may not be hung, but instead it may be trying to transfer everything over to the daemon.

**Comment by jasonsemko** [comment]
@duglin It's my home root directory...so yes it would have a ton/all of my own files in it. Let me try moving into a smaller folder on the desktop

**Comment by jasonsemko** [comment]
@duglin Wow that was it! Thanks so much. 

I made a new directory on my desktop and put the Docker file in there. cd into it and ran the same command, worked right away.

Would be awesome to add some type of verboseness to the process just so one would be able to tell what was going on while it was attempting to transfer.

Thanks again, closing

**Comment by duglin** [comment]
@jasonsemko you should have seen something like:
```
Sending build context to Docker daemon
```
while not exactly `yo, dude did you really want to send 3 TB of data!`, it is a bit of a clue  :-)

**Comment by jasonsemko** [comment]
@duglin haha did not see that message but I prefer yours

**Comment by dhilst** [comment]
I have the same problem, thanks @duglin for pointing the "trying to transfer everything to daemon" thing!
