### ISSUE TITLE
doc: messy table format for Linux capability options in `run` reference

### ISSUE THREAD

**Issue by henrysher** [docker/docker#14176]
https://docs.docker.com/reference/run/

The table format is messy after the paragraph shown as below.

>
In addition to --privileged, the operator can have fine grain control over the capabilities using --cap-add and --cap-drop. By default, Docker has a default list of capabilities that are kept. The following table lists the Linux capability options which can be added or dropped.

I have checked other tables in `run` reference - **markdown** issue - has been converted to **html** format.

**Comment by henrysher** [comment]
ping @thaJeztah 
add a screenshot here: 
![messy-table-format-run-cli](https://cloud.githubusercontent.com/assets/65181/8369402/a5bf21e0-1beb-11e5-82a7-7023c555c8e6.png)

**Comment by thaJeztah** [comment]
Oh, that *is* messy, looks like the new tooling either doesn't support Markdown tables at all (which is an extension to Markdown), or this particular type of tables.

I'm still travelling at the moment after DockerCon, and don't have access to my computer right now, so I'll need to check further.

@moxiegirl is this a known issue, and something you're working on already?

**Comment by vdemeester** [comment]
@thaJeztah See https://github.com/docker/distribution/pull/659, it's just that blackfriday (used by Hugo, used for the docs) is not working the same as rdiscount use by github for example. I started to look at this in the documentation on ``docker/distribution``. It's not that bad to fix (just alignement) but we probably should do a pass on all the docs to fix it.

**Comment by moxiegirl** [comment]
@vdemeester I'll address that today and cherry pick it forward. Thank you for filing the issue.

**Comment by charleswhchan** [comment]
Appeared to be fixed now:
![screenshot](https://cloud.githubusercontent.com/assets/679475/8888074/eefcbaca-3252-11e5-9247-e2004fd9cf15.png)

So this issue can be closed?

**Comment by thaJeztah** [comment]
Oh, thanks @charleswhchan, yes, this looks to be resolved since.
