### ISSUE TITLE
Permission denied on accessing host directory in docker in Centos

### ISSUE THREAD

**Issue by xiuni** [docker/docker#14175]
Hi,
I have faced this problem, when I mount a host directory to a container:
`docker run -it -v /home/share:/home/share centos /bin/bash`

 and then in container:
` cd /home/share `
 ` ls `
`ls: cannot open directory .: Permission denied`

But I tried it on  ubuntu system, it works well.

Docker option SELinux are both enabled.
What is the difference between the two system? Can someone give comments? 

Thanks
Brs,

**Comment by cyphar** [comment]
Can you give the output of `id -Z` and `ls -ldZ /home/share`?

**Comment by xiuni** [comment]
@cyphar , the output:
The host：
`[root@centos-minion share]# id -Z`
`unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023`

`[root@centos-minion share]# ls -ldZ /home/share`
`drwxr-xr-x. root root unconfined_u:object_r:home_root_t:s0 /home/share`

The container：
`[root@4ccce73bed9d share]# id -Z`
`id: --context (-Z) works only on an SELinux-enabled kernel`

`[root@4ccce73bed9d share]# ls -ldZ /home/share`
`drwxr-xr-x. root root unconfined_u:object_r:home_root_t:s0 /home/share`

Thanks!

**Comment by xiuni** [comment]
I think maybe I known the reason now.
The difference is the SELinux. 
My ubuntu system disabled the  SELinux. (getenforce = Disabled)
So the docker actually didn't enable the SELinux, so user in the container can access the mounted directory from host.

Thanks !

**Comment by cpuguy83** [comment]
Yes, this is because of SELinux.
You need to relabel the host path to allow the docker container access.

If you are using Docker 1.7 you can do this by doing either `-v /home/share:/home/share:z` or `-v /home/share:/home/share:Z` depending on if you want it to be shared or private.

Closing since this is a non-issue.
