### ISSUE TITLE
Wrong comments in https://experimental.docker.com/

### ISSUE THREAD

**Issue by vieux** [docker/docker#14188]
At the top of https://experimental.docker.com/ it still says `get.docker.com` in the comments.

**Comment by vieux** [comment]
ping @tianon

**Comment by aanm** [comment]
And fedora installation only points to the yum/dnf command which means, fedora distro won't get the experimental binary but the one in the fedora's repo.

**Comment by tianon** [comment]
This was fixed in #14335! :heart:
