### ISSUE TITLE
docker build should provide an environment variable of the git commit if applicable

### ISSUE THREAD

**Issue by herrphon** [docker/docker#14191]
It would be so great if docker build could provide the git hash (or git describe) as an environment variable of the container when the dockerfile is under git version control. This way, application could reference / show the commit hash and hence have a nice way to find the code...

somehow this is linked to https://github.com/docker/docker/pull/9176...

I have a workaround but its ugly:

    export GIT_DESCRIBE=$(git describe)
    cat Dockerfile | envsubst | docker build -t tag -

Or maybe there's a better way?

**Comment by duglin** [comment]
If we had https://github.com/docker/docker/pull/9176 you could then do:
`docker build -e GIT_DESCRIBE="$(git describe)" -tag tag .` 
Would that be ok?

**Comment by herrphon** [comment]
sure, that would be sufficient - but I guess environment vars during build time can be dangerous as one can build different versions of the same dockerfile... and hence only some limited things should be allowed... 
as far as I can summarize the discussion in #9176, so I guess this general purpose solution will probably never get merged...

**Comment by duglin** [comment]
Still keeping my fingers crossed  :-)

**Comment by pyros2097** [comment]
@duglin Still keeping it crossed huh!

**Comment by duglin** [comment]
@herrphon with `--build-arg` support and https://github.com/docker/docker/issues/14191#issuecomment-115672621 would that solve your issue?

**Comment by pyros2097** [comment]
Yeah I've solved it. Like in my docker file I add this,
```Dockerfile
ARG GIT_COMMIT
ENV GIT_COMMIT ${GIT_COMMIT}
```
`docker build --build-arg GIT_COMMIT=$(git rev-parse --short HEAD) .`

And then in my node process,
```js
process.env.GIT_COMMIT
```
is accessible

**Comment by duglin** [comment]
great - I'll close the issue then. Thanks. And thanks @pyros2097 for the ping/reminder.

**Comment by adzenith** [comment]
In case anyone comes here much later, like I did, and wants to keep the git hash around just for your own records, you can also [use the `LABEL` command in a build file](https://stackoverflow.com/questions/31647843/labelling-images-in-docker/34676790#34676790).
