### ISSUE TITLE
Docker tries to download image that has already been pulled

### ISSUE THREAD

**Issue by Slamper** [docker/docker#14206]
When I try to start a container with the ubuntu:latest image I get:
```
Unable to find image 'ubuntu:latest' locally
latest: Pulling from ubuntu
428b411c28f0: Already exists
435050075b3f: Already exists
9fd3c8c9af32: Already exists
6d4946999d4f: Already exists
Digest: sha256:45e42b43f2ff4850dcf52960ee89c21cda79ec657302d36faaaa07d880215dd9
Status: Image is up to date for ubuntu:latest
FATA[0002] Error response from daemon: Conflict. The name "test" is already in use by container ef8ce6737cad. You have to delete (or rename) that container to be able to reuse that name.
```

There is no other container with the name "test" so the error message is not correct
I already tried doing "docker rmi ubuntu:latest" and repulling it but that doesnt fix the problem.
I don't know how that bug occured so I can't provide steps for reproduction

docker version: Docker version 1.6.2, build 7c8fca2
docker info:

```
Containers: 18
Images: 62
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 225
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-53-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 4
Total Memory: 7.503 GiB
Name: vm
ID: SAJF:ERSE:B5DF:NMPK:3ALD:ICP2:TIZU:25L2:YOEP:PPKI:54OR:F2GE
WARNING: No swap limit support
```

uname -a :
```
Linux vm 3.13.0-53-generic #89-Ubuntu SMP Wed May 20 10:34:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by vdemeester** [comment]
Hi @Slamper,

Without more information of commands like ``docker ps -a``, it's really difficult to know if it's actually a bug or just something that you missed. From the message, it seems you have 18 containers and 62 images (I would think layers :)). I would think that ``docker ps -a | grep test`` would return you something. (you could try ``docker rm test && docker run -ti --name test ubuntu /bin/bash``)

Anyway, I think you're problem / question would fit more in forums or chats, like :

* In the #docker IRC channel on freenode
* On https://forums.docker.com
* In the [docker-user](https://groups.google.com/forum/#!forum/docker-user) Google Group

**Comment by Slamper** [comment]
@vdemeester 
The creation oft the container results in a container but that container cannot be started and seems broken.
Removing and recreating it has the same result.
But I will try to ask someone on the forums thx.

Also I dont't geht why removing ubuntu:latest and then pulling it again shows already exists. It seems like it didn't remove the relevant layers.
