### ISSUE TITLE
Container Timeout not working as expected

### ISSUE THREAD

**Issue by Ankitmaroo** [docker/docker#14207]
Hi, I am trying to timeout the docker run command but it doesnt seem to work. It returns a proper exit status but the container itself doesnt exit till the command inside finishes.

$$ timeout 2s docker run busybox sh -c 'sleep 5 && echo end'
end
$$ echo $?
0

Any thoughts whats happening and what i could be doing wrong?

**Comment by Ankitmaroo** [comment]
Additonal info:

# docker -v
Docker version 1.6.0, build 4749651

# uname -a
Linux ilmn-tt-mb1 2.6.32-504.el6.x86_64 #1 SMP Wed Oct 15 04:27:16 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

# docker info
Containers: 49
Images: 1004
Storage Driver: devicemapper
 Pool Name: docker-253:0-12059614-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 28.7 GB
 Data Space Total: 107.4 GB
 Data Space Available: 78.68 GB
 Metadata Space Used: 59.36 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.088 GB
 Udev Sync Supported: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 2.6.32-504.el6.x86_64
Operating System: <unknown>
CPUs: 24
Total Memory: 62.82 GiB
Name: ilmn-tt-mb1
ID: HG7D:6LXI:V36W:CYDI:3IGI:4SLW:6QPN:IJPZ:FLKH:A26P:76YL:UD5R


Running it on single node.

**Comment by vdemeester** [comment]
Hi @Ankitmaroo,

From the man page of timeout :

> If  no signal  is specified, send the TERM signal upon timeout.  The TERM signal kills any process that does not block or catch that signal.  It may be  necessary  to  use the KILL (9) signal, since this signal cannot be caught, in which case the exit status is 128+9 rather than 124.

This means by default it sends ``TERM`` to the docker cli command, which probably does not handle it. This means that ```timeout -s 9 2s docker run busybox sh -c 'sleep 5 && echo end'`` should do what you want.

```bash
$ timeout -s 9 2s docker run busybox sh -c 'sleep 5 && echo end'               
zsh: killed     timeout -s 9 2s docker run busybox sh -c 'sleep 5 && echo end'
```

I think you're problem / question would fit more in forums or chats, like :

* In the #docker IRC channel on freenode
* On https://forums.docker.com
* In the [docker-user](https://groups.google.com/forum/#!forum/docker-user) Google Group

**Comment by Ankitmaroo** [comment]
Thank you. I understand it now. Will take care about posting too.
