### ISSUE TITLE
Pulling image fills disk/image size is huge, version 1.7.0

### ISSUE THREAD

**Issue by antonbormotov** [docker/docker#14204]
I am trying to pull image from docker hub repository.
(AWS, Ubuntu 14.04, c3.large, 40GB disk, docker version 1.7.0)
Pulling takes time, finishes and uses 38GB of dosk space for one image only.
I thought, that it is problem of repository.
I re-created automated build and tried to specify `docker pull repository/image:latest`, but it didn't help.
After pulling docker service CPU usage is 40-50% with 80% spikes.

The output of uname -a:
Linux ip-10-0-1-11 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

The output of docker version:
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64

The output of docker -D info.
Containers: 2
Images: 223
Storage Driver: devicemapper
 Pool Name: docker-202:1-398123-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.242 GB
 Data Space Total: 107.4 GB
 Data Space Available: 37.19 GB
 Metadata Space Used: 11.44 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.136 GB
 Udev Sync Supported: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.13.0-48-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 3.676 GiB
Name: ip-10-0-2-16
ID: JXWZ:CW2X:S7DM:UK54:T7CC:UDAV:OCIC:HOAU:CLF4:NCAP:MNG2:6G7K
Debug mode (server): false
Debug mode (client): true
Fds: 22
Goroutines: 32
System Time: Fri Jun 26 11:44:24 UTC 2015
EventsListeners: 0
Init SHA1: 7f9c6798b022e64f04d2aff8c75cbf38a2779493
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker
Username: qqwrst
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support

Some people left messages as well:
https://forums.docker.com/t/docker-1-7-0-is-using-huge-amount-of-disk-space/2046

**Comment by ankushagarwal** [comment]
1. How did you install docker?
2. Can you provide the list the steps to reproduce the issue?
3. Can you post the output from `sudo du -sh /var/lib/docker/*`
4. You are using devicemapper as a storage driver, can you try using aufs?

**Comment by antonbormotov** [comment]
Hello,

1. I install docker using `sudo apt-get -y install lxc-docker-1.7.0`
(If be more specific, using shell script https://get.docker.com/ubuntu/ which does action above)

2. Steps to reproduce issue:
A) Deploy new instance in AWS, even t2.micro is enough.
B) Install docker 1.7
C) docker login
D) docker pull myrepository/imagename
It is pulling image until disk is full, or almost full.

3. I will post output later, dont' have access now.

4. Yes, devicemapper, how can I try aufs?

**Comment by ankushagarwal** [comment]
Hey @antonbormotov ,
Can you try installing using the instructions here : https://docs.docker.com/installation/ubuntulinux/
It boils down to running
```
wget -qO- https://get.docker.com/ | sh
```
It eventually does `apt-get -y install lxc-docker-1.7.0`, but also sets up a lot of things (aufs for example)

**Comment by antonbormotov** [comment]
I see, thanks @ankushagarwal, so, I will try and let you know.

**Comment by m1keil** [comment]
We start hitting this issue as well.
It looks like the script located here: `https://get.docker.com/ubuntu/` does not include aufs related installs. This cause docker to fallback to `devicemapper`.

The script at `https://get.docker.com/` on the other hand includes it.

**Comment by antonbormotov** [comment]
Yes, you are right, it doesn't, but,
I guess, devicemapper should work as well, shouldn't it?

**Comment by m1keil** [comment]
It does work, but devicemapper takes much more disk space.

Yes, you are right, it doesn't, but,
I guess, devicemapper should work as well, shouldn't it?

—
Reply to this email directly or view it on GitHub
<https://github.com/docker/docker/issues/14204#issuecomment-116421532>.

**Comment by thaJeztah** [comment]
I this still an issue? @antonbormotov have you been able to test this with aufs? Also be aware that the *default* devicemapper settings are *not* intended for production use. The default settings are to "get things working", but require manual configuration for production use (those settings are really dependent on your use case, so cannot be done automatically by the install script). This is one of the reasons to use aufs as the default driver for Ubuntu.

Docker recently launched new apt and yum repositories, containing dynamically linked binaries, which also solve a number of issues. More information on this can be found in the blog post here; https://blog.docker.com/2015/07/new-apt-and-yum-repos/

**Comment by antonbormotov** [comment]
Thanks @thaJeztah. It is gone in version 1.7.1, and we have changed to aufs. I agree with you.
We saw, and using new repositories already, I guess we can close this issue.

**Comment by thaJeztah** [comment]
thanks @antonbormotov!
