### ISSUE TITLE
documentation of stream format for `GET /containers/(id)/logs`

### ISSUE THREAD

**Issue by Kosta-Github** [docker/docker#14201]
Is there a documentation/specification available about the stream format returned by accessing the `GET /containers/(id)/logs` endpoint of the REST API?

It looks like each line is prefixed with `8 bytes` of binary data, which might encode line length, a time code, line codes, char offsets, or ... but I haven't found any documentation about that format (at least not in the [docker remote api v1.19 docs](https://docs.docker.com/reference/api/docker_remote_api_v1.19/)).

I am running:

```
Docker version 1.7.0, build 0baf609
```

E.g.: running this request:

```
curl "http://localhost:2375/containers/8c579/logs?follow=true&stderr=true&stdout=true&timestamps=true"
```

gives this result (note the garbage characters in front of the time stamps):

``````
☺      ½2015-06-25T18:10:22.916242788Z 1:C 25 Jun 18:10:22.914 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
☺      e2015-06-25T18:10:22.921992353Z                 _._
☺      e2015-06-25T18:10:22.922012790Z            _.-``__ ''-._
☺      g2015-06-25T18:10:22.922020284Z       _.-``    `.  `_.  ''-._           Redis 3.0.2 (00000000/0) 64 bit
☺      e2015-06-25T18:10:22.922026895Z   .-`` .-```.  ```\/    _.,_ ''-._
☺      b2015-06-25T18:10:22.922033469Z  (    '      ,       .-`  | `,    )     Running in standalone mode
☺      R2015-06-25T18:10:22.922039644Z  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
☺      N2015-06-25T18:10:22.922045827Z  |    `-._   `._    /     _.-'    |     PID: 1
☺      e2015-06-25T18:10:22.922052038Z   `-._    `-._  `-./  _.-'    _.-'
☺      e2015-06-25T18:10:22.922057983Z  |`-._`-._    `-.__.-'    _.-'_.-'|
☺      e2015-06-25T18:10:22.922064221Z  |    `-._`-._        _.-'_.-'    |           http://redis.io
☺      e2015-06-25T18:10:22.922070404Z   `-._    `-._`-.__.-'_.-'    _.-'
☺      e2015-06-25T18:10:22.922078420Z  |`-._`-._    `-.__.-'    _.-'_.-'|
☺      e2015-06-25T18:10:22.922084460Z  |    `-._`-._        _.-'_.-'    |
☺      e2015-06-25T18:10:22.922090389Z   `-._    `-._`-.__.-'_.-'    _.-'
☺      e2015-06-25T18:10:22.922096333Z       `-._    `-.__.-'    _.-'
☺      e2015-06-25T18:10:22.922102155Z           `-._        _.-'
☺      e2015-06-25T18:10:22.922108076Z               `-.__.-'
☺       2015-06-25T18:10:22.922113903Z
☺      ]2015-06-25T18:10:22.923169420Z 1:M 25 Jun 18:10:22.923 # Server started, Redis version 3.0.2
``````

**Comment by cpuguy83** [comment]
@Kosta-Github This is the stdout/stderr formatter, and is only pre-pended to the log line when using `-t` (or `"Tty": true` from the API)

Looks like this is missing from the API docs.

**Comment by saamalik** [comment]
I'm setting "Tty" to false, and I still get the 8-bytes per line. Any other ideas how to get this formatting removed?

```
Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Sat Aug 15 17:29:10 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by cpuguy83** [comment]
@saamalik I'd have to see how you created the container, and the inspect output after you've created it.
The stdout/stderr encoding should only be there when using tty mode.

**Comment by zfeng-cliqr** [comment]
@cpuguy83 @saamalik  I faced the same issue.

But I have fixed it by setting tty to true when I create the container. Then no matter I provide the tty=0 or not when querying the log, I get the correct input without the unknown characters added the front.

The server is running using 1.8.1

**Comment by saamalik** [comment]
@zfeng-cliqr what happens when you run the inspect output on your created containers? Does does the tty option show 'true' or 'false'?

**Comment by zfeng-cliqr** [comment]
This is part of the output of docker inspect.  

  "Config": {
        "Hostname": "43bd642b270b",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": null,
        "PublishService": "",
        "Tty": true,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "JAVA_VERSION=1.7.0"
        ],
        "Cmd": [
            "START"
        ],

**Comment by megastef** [comment]
@cpuguy83 please have a look at this discussion: https://github.com/mcollina/docker-loghose/issues/4
I have seen:
* Container running in background, having tty set to true - with no headers in logs  (raw stream)
* Container running attached to console / interactive - having headers (multiplexed stream)

So I'm confused when we can expect what. Please advise. Docker 1.9.

**Comment by cpuguy83** [comment]
@megastef https://github.com/docker/docker/blob/master/daemon/logs.go#L47-L50
It encodes the streams with stdout/stderr headers when TTY is not set.
This is so the client can differentiate the streams.

**Comment by megastef** [comment]
Thx. And the headers go then in here https://github.com/docker/docker/blob/master/pkg/stdcopy/stdcopy.go (if TTY is not set)

**Comment by megastef** [comment]
One more question. How does it behave when somebody uses "docker exec -it" or the TTY flag changes for any other reasons? Do we have to check for each log line the container TTY status? This sounds like overhead (my current temporary solutions is to detect the header by the 3 zero bytes also a little overhead). Why not add always a header?

**Comment by cpuguy83** [comment]
You can't change the tty flag. There are no logs for exec.

No headers with tty enabled because it is a single multiplexed stream.

**Comment by yosifkit** [comment]
@cpuguy83, why not keep the headers all the time?  Then it doesn't matter whether the container has a tty or not.  A container with a tty wouldn't be any different from a container that never uses stderr.

**Comment by santosh0705** [comment]
Could you please help me out.
I've written my own client in python and when getting logs I'm getting multiplexed output. Wanted to know how to get the demultiplexed output. Or is there any ways to show it on console without the leading special characters. 
I'm connecting to docker API v1.19

**Comment by thaJeztah** [comment]
@santosh0705 please don't use the issue tracker for support questions, this is not the right location for that. https://docs.docker.com/opensource/get-help/. Looking at https://github.com/docker/docker-py could be a good start

**Comment by santosh0705** [comment]
@thaJeztah sorry for the inconvenience. I didn't get any documentation related to this so asked here. I wrote my client to keep everything minimal in a single script. I had checked the docker-py project, will check again to know how they do it.
Thanks

**Comment by cpuguy83** [comment]
Closing since the stream format is now documented, just below https://docs.docker.com/engine/api/v1.26/#operation/ContainerAttach

**Comment by jrichardsz** [comment]
My workaround was "tr" command:
```

my_log=$(curl http://localhost:2375/containers/8c579/logs?stderr=true&stdout=true&timestamps=true)

echo "$my_log" | tr -cd '\11\12\15\40-\176'
```
Source : https://alvinalexander.com/blog/post/linux-unix/how-remove-non-printable-ascii-characters-file-unix
