### ISSUE TITLE
Confusing message when specifying resource limits

### ISSUE THREAD

**Issue by kkebb** [docker/docker#14215]
# BUG REPORT INFORMATION

Use the commands below to provide key information from your environment:

```docker version:```
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): darwin/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64

```docker info:```
Containers: 8
Images: 298
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 317
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.5-boot2docker
Operating System: Boot2Docker 1.7.0 (TCL 6.3); master : 7960f90 - Thu Jun 18 18:31:45 UTC 2015
CPUs: 8
Total Memory: 7.604 GiB
Name: boot2docker
ID: 24GL:J44Z:VKU5:NCGQ:EIBI:TAJ6:K32X:7JBL:TJDF:M4RW:CPEQ:PR33
Debug mode (server): true
File Descriptors: 43
Goroutines: 64
System Time: 2015-06-26T21:17:50.988494018Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker

```uname -a:```
Darwin [MYPC] 13.3.0 Darwin Kernel Version 13.3.0: Tue Jun  3 21:27:35 PDT 2014; root:xnu-2422.110.17~1/RELEASE_X86_64 x86_64

Provide additional environment details (AWS, VirtualBox, physical, etc.):
16GB RAM
running boot2docker

List the steps to reproduce the issue:
1. ``` docker run -d --name bb2 -m 4g --memory-swap="1g" -c 2 busybox ```

Describe the results you received:
``` Error response from daemon: Minimum memoryswap limit should be larger than memory limit, see usage. ```

Describe the results you expected:
Runs seamlessly..
Thank you for your time and efforts. Much appreciated!

**Comment by ankushagarwal** [comment]
From the docs : https://docs.docker.com/reference/run/#runtime-constraints-on-resources
```
-m, --memory="": Memory limit (format: <number><optional unit>, where unit = b, k, m or g)
-memory-swap="": Total memory limit (memory + swap, format: <number><optional unit>, where unit = b, k, m or g)
```

The memory-swap options lets you specify the memory + swap space (Swap space in Linux is used when the amount of physical memory (RAM) is completely used up), so swap should be greater than memory

**Comment by cpuguy83** [comment]
Closing as this is a non-issue and is quite explicit about what it needs.

**Comment by macedd** [comment]
I’d like to suggest a review of the memory swap limitation in Docker, specifically the requirement that `memswap_limit` must be greater than `mem_limit`. 

This requirement can be confusing, as many users configure swap space to be equal to or less than physical memory (e.g., 1:1 or 1:2 ratio). Adjusting this limitation could make Docker more user-friendly and better align with common practices.
