### ISSUE TITLE
Top-level volume management

### ISSUE THREAD

**Issue by icecrime** [docker/docker#14214]
# Description

As indicated by our [roadmap](https://github.com/docker/docker/blob/master/ROADMAP.md), we want a better management for volumes. There has been [good attempts](https://github.com/docker/docker/pull/8484) toward this in the past but it wasn't a priority, and the volume subsystem needed a refactoring.

# How to

We need a top-level volume management command which takes its inspiration from what has been done on [networking](https://github.com/docker/libnetwork/tree/master/client) to support the new CNM (Container Networking Model).

- [ ] Define and propose a new volume management UX
    - Consistent with network management
    - Taking plugins into account
    - Doesn't make it cumbersome fo create "throwawy" volumes?
- [ ] Ideally implement command-line and API endpoints inside the volumes subsystem

# Questions

- How are networks internally idenfied? Do they have a randomly generated unique id? If so, should
we do the same for volumes and should those ids be all be in the same scope?

# Reference

- #8484: earlier implementation
- #13161: volume refactoring
- #13420: some feedback to take into account
- #14213: volume extensions

Ping @cpuguy83!

**Comment by cpuguy83** [comment]
Implementation here: #14242 

There are some things to address.

**Comment by icecrime** [comment]
@cpuguy83 Can you clarify what remains? Do you need any help with it? Thanks!

**Comment by cpuguy83** [comment]
@icecrime There's a checklist on the other issue.
Biggest issue is that mount/unmount really becomes pointless with this, and the accounting for the local volume driver is not sufficient.
Probably stuff I need to discuss with @calavera

**Comment by calavera** [comment]
> Biggest issue is that mount/unmount really becomes pointless with this

what do you mean? We still need to mount the endpoints inside the containers, don't we?

**Comment by cpuguy83** [comment]
@calavera Sure, but the drivers are not responsible for this, the daemon is.

**Comment by marcmerlin** [comment]
As discussed with @icecrime via Email, as part of my unusual use of docker http://marc.merlins.org/linux/talks/DockerLocalDisk-LC2015/DockerLocalDisk.pdf  I found arguably a security bug where if you use -v /usr:/usr:ro, and /usr/local is a separate partition, docker will automatically mount /usr/local in my container, and mount it read/write, wihch is bad.

More generally, I'd like for -v /usr:/usr:ro not to be recursive.
@jpetazzo mentioned we could just allow some -v /usr:/usr:ro:nr for non recursive, or I'd be happy with -V /usr:/usr for a non recursive -v

Thanks :)

**Comment by cpuguy83** [comment]
@marcmerlin currently this is completely handled by libcontainer, and is really just how rbind works.
But I agree, it'd be nice to be able to tweak whether or not to use rbind... but not really relevant in this discussion.

**Comment by marcmerlin** [comment]
@cpuguy83 you know better than me, it's just that @icecrime told me to chime in on this bug :)
I personally don't care where or how this gets fixed, but having non recursive mounts somehow would be good.

**Comment by srust** [comment]
@cpuguy83 Can you please clarify what you meant by "mount/unmount becomes pointless with this"? You are not referring to the volume plugin API mount/unmount, correct? Those are still needed.

**Comment by vaibhavkhanduja** [comment]
I like the idea of not giving mount point from volume plugins .. this makes it easy to have volume plugins containerized ... the volume plugin can return disk path for block device or a url for nfs/cifs shares etc ...

**Comment by marcmerlin** [comment]
I see. So, rbind recursively mounts, and if you ask for an ro mount, it will recursively mount sub mount points, but read-write. Do you know who the best folks to file this bug with, would be?

**Comment by cpuguy83** [comment]
It recursively mounts as they are mounted on the host. You can change the top-most mount (the one you specified, but the submounts will come in as they are on the host.

**Comment by cpuguy83** [comment]
Closing as #14242 was merged which address this.

**Comment by rossettistone** [comment]
Docs at https://docs.docker.com/engine/userguide/dockervolumes/ still reference this PR. Not sure what the latest information is, but seems like perhaps those docs are due for an update :smile:

**Comment by thaJeztah** [comment]
@rossettistone nice catch! Yes, that page may need an update overall. Removing / replacing that reference with something more useful would be a start :smile:
