### ISSUE TITLE
Rely on Open Containers as sole execution driver

### ISSUE THREAD

**Issue by icecrime** [docker/docker#14212]
# Description

As indicated by our [roadmap](https://github.com/docker/docker/blob/master/ROADMAP.md), we want to split out the Runtime part of the Engine, and have it call out to a separated binary. Today, our best candidate for this is [`runc`](https://github.com/opencontainers/runc).

> Note: as part of this effort, Docker will effectively drop builtin support for LXC. However, it is entirely possible for LXC maintainers to provide a [Open Container Project](opencontainers.org) compliant implementation that relies on LXC.

# How to

- [ ] Remove the [`execdriver`](https://github.com/docker/docker/blob/master/daemon/execdriver)
mechanism in favor of a single implementation which job is to fork/exec a binary following
`nsinit` existing interface
- [ ] Provide a mechanisms to pick the binary to call-out to (thus offering a way to substitute the backend with any [OCP](opencontainers.org) compliant implementation.

# Questions

- What are the impacts on packaging/releasing?

# References

- [`runc`](https://github.com/opencontainers/runc).
- [`execdriver`](https://github.com/docker/docker/blob/master/daemon/execdriver)

**Comment by Crazykev** [comment]
ping @icecrime I'm interested in this roadmap, but I don't know what `nsinit` is, and  I can't grep anything match nsinit in docker source code.

**Comment by cpuguy83** [comment]
@Crazykev nsinit == runc

**Comment by dalanlan** [comment]
@Crazykev 
>nsinit is a cli application which demonstrates the use of libcontainer. It is able to spawn new containers or join existing containers

For more details, ref https://github.com/docker/libcontainer/tree/master/nsinit

**Comment by Crazykev** [comment]
@cpuguy83 @dalanlan Thanks for help! :smile: 
It seems `nsinit` has been abandoned and replaced by runc.

**Comment by icecrime** [comment]
Ping @tonistiigi: now related to [docker/containerd](https://github.com/docker/containerd) integration.

**Comment by vdemeester** [comment]
Should https://github.com/docker/docker/issues/20361 and this one be merged into one and only *roadmap* issue ? :angel:

**Comment by icecrime** [comment]
@vdemeester Good point, I think I can close this one in favor of this other. This was always our intention, but containerd was the missing link to make it happen.
