### ISSUE TITLE
docker stats blocking when container is stopped

### ISSUE THREAD

**Issue by asssaf** [docker/docker#14216]
With docker 1.7, calling the stats API with stream=0 on a stopped container blocks:

curl 'https://docker:2376/v1.19/containers/532e58c97fee/stats?stream=0'

Interestingly, using the cli with --no-stream doesn't block.

This works fine for a running container.

core@localhost ~ $ uname -a
Linux localhost 4.0.5 #2 SMP Thu Jun 25 01:57:28 UTC 2015 x86_64 Intel(R) Xeon(R) CPU E5-2680 0 @ 2.70GHz GenuineIntel GNU/Linux
core@localhost ~ $ docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609-dirty
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609-dirty
OS/Arch (server): linux/amd64
core@localhost ~ $ docker -D info
Containers: 17
Images: 449
Storage Driver: devicemapper
 Pool Name: docker-8:17-786433-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 16.19 GB
 Data Space Total: 107.4 GB
 Data Space Available: 28.44 GB
 Metadata Space Used: 24.58 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.123 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.88 (2014-08-05)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.5
Operating System: CoreOS 723.0.0
CPUs: 2
Total Memory: 15.68 GiB
Name: localhost
ID: 62O4:27W3:XJKL:PQYM:LHBY:PC3N:7F6X:QOSU:BVVW:TM5U:YSJO:KKVY

**Comment by asssaf** [comment]
This was reported in https://github.com/docker/docker/issues/12529 but was that was prior to the 'stream=0' parameter support.

**Comment by HuKeping** [comment]
The CLI `docker stats` works fine because there is a 2s-timeout for waiting the response from daemon.
```
...
for {
        select {
        case <-time.After(2 * time.Second):
            // zero out the values if we have not received an update within
            // the specified duration.
...
```

In the daemon, it is always wait for stopped-container to be restart again, that's why fail your `curl`
```
...
for _, pair := range pairs {
            stats, err := pair.container.Stats()

            // HERE, the err is ErrNotRunning if the container not run.
            if err != nil {
                if err != execdriver.ErrNotRunning {
                    logrus.Errorf("collecting stats for %s: %v", pair.container.ID, err)
                }   
                continue
            } 
...
```

**Comment by cpuguy83** [comment]
If `stream=0` we should probably check if the container is running and return immediately if not. WDYT?

**Comment by HuKeping** [comment]
I agree with you @cpuguy83 . I'll make a PR about that.

**Comment by HuKeping** [comment]
ping @cpuguy83 I've post a PR, PTAL
