### ISSUE TITLE
Attach stdout of one container to stdin of another (pipe-like)

### ISSUE THREAD

**Issue by francisbouvier** [docker/docker#14221]
Is it possible now ?
I believe it's not, at least not at the daemon level.

The idea is to have a built-in pipe-like feature to easily chain micro-services:
```sh
docker run -i --name my_service ubuntu bash -c "cat"
docker run --stdout my_service ubuntu bash -c "echo foo"
```
With the exact same result as local:
```sh
echo foo | cat
```

**Comment by duglin** [comment]
Not near my computer but did you try piping one docker command into the other?

docker run ... | docker run ...

-Doug

**Comment by ankushagarwal** [comment]
@francisbouvier 
```
docker run ubuntu printf "line1\nline2\n" | docker run -i ubuntu grep line2 | docker run -i ubuntu sed 's/line2/line3/g'
```

This seems to work

**Comment by Evalle** [comment]
Yes, I've just check it out, it's working.

**Comment by duglin** [comment]
I'm going to close this issue as I think the piping solution works - if I'm mistaken please reopen it.

**Comment by francisbouvier** [comment]
@duglin 
Yes the piping solution works but at the client level: the stream is retrieved (then send) by the docker client and the pipe is done in your shell.

That means:
- If your are accessing a remote docker agent the stream will be process through the network
- if you close your shell you close the pipe too

My idea is to have something reliable and permanent in order to pipe long term micro-services.
That's why you have to tell the docker agent to do the pipe.

**Comment by phemmer** [comment]
If you want to pipe between containers, I'd use a shared volume and make a named pipe.

```
# docker run -d -v /tmp/share:/tmp/share fedora:20 bash -c 'mkfifo /tmp/share/pipe && echo -e "one\ntwo" > /tmp/share/pipe' 
61986d26922c2c183ce7a4e4e6cffcc14bdad426cdc36c4e04dfdf8eec9c2ac5

# docker run -ti -v /tmp/share:/tmp/share fedora:20 bash -c 'cat /tmp/share/pipe'
one
two
```

**Comment by francisbouvier** [comment]
@phemmer 
It's a clever solution and it works perfectly if you want to link 2 services.

However if you want more services in the pipeline you will have to deal with multiples named pipes, one by each link (n-1).
And you need some setup (create and use the named pipes as command arguments, shared volume).

Docker daemon already deal with sdtin/stdout/stderr pipes of containers (used by the attach feature), so we could tell him to copy stdout of container A to stdin of container B.
And because stdout/stderr pipes of containers are broadcast, you can redirect them to several containers, to do parallel processing.

Actually I have now a small working hack, but I'm not sure about the API.
Either as an option in run:
```sh
docker run --name containerA <image>
docker run --name containerB --stdin containerA <image>
```
Or as a command like attach:
```sh
docker pipe containerA containerB
```
I prefer the last one as it's closer to the attach command.

And I want to see if someone is interested before working more on that a make a PR.

**Comment by dimichgh** [comment]
@francisbouvier
I am interested in this.
My idea is to have micro services managed by docker compose and link containers one to the other depending on pipeline requirements and when one dies the docker would restart it and re-link it.
Kind of similar to what erlang/OTP does.

**Comment by dunk** [comment]
I also need this. I believe that the data will flow via the Docker HTTP API if you chain them in this way, which would be quite inefficient. Vote that it is reopened?

**Comment by murphyke** [comment]
One problem with the conventional pipe approach that was the motivation for closing the ticket is that the pipe I/O will be logged by Docker along with everything else, right? Linux folks are used to piping enormous amounts of data around, which invites some extra I/O problems.

**Comment by pveber** [comment]
@murphyke I confirm, I've just had to delete hundreds of GB of suchs logs. So piping one docker command to or from some other command is absolutely wrong when dealing with large amounts of data.

**Comment by murphyke** [comment]
@pveber If it helps in some circumstances, you can safely pipe from a `docker exec`, but not from a `docker run`, which will blow up your logs.

**Comment by eqhmcow** [comment]
You can disable logging at run time with `--log-driver=none`

An example:

    echo "This was piped into docker" |
      docker run -i --log-driver=none -a stdin -a stdout -a stderr \
        alpine cat - |
      xargs echo This is coming out of docker: 

emits:

    This is coming out of docker: This was piped into docker
