### ISSUE TITLE
Udev sync is not supported -> ubuntu server 14.04

### ISSUE THREAD

**Issue by neovea** [docker/docker#14224]
Hi,
I found a lot of different issues having the same message, but cannot figure out on my dedicated provided server (ubuntu server 14.04).
I first installed docker via apt-get, in root. I had a lot of trouble with docker-compose which was not usable.
When I get docker-compose working, I had an issue with client and server versions which were not the same. I finally used the script given on docker.io : `wget -qO- https://get.docker.com/ | sh` which solved my problems. 
When I run `docker info`, it returns : 
`Cannot connect to the Docker daemon. Is 'docker -d' running on this host?`
But `docker -d` is giving : 
```
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
ERRO[0000] Udev sync is not supported. This will lead to unexpected behavior, data loss and errors. For more information, see https://docs.docker.com/reference/commandline/cli/#daemon-storage-driver-option 
ERRO[0000] [graphdriver] prior storage driver "devicemapper" failed: driver not supported 
FATA[0000] Error starting daemon: error initializing graphdriver: driver not supported
```
My uname -a : 
`Linux kimlabs 3.14.32-xxxx-grs-ipv6-64 #1 SMP Sat Feb 7 11:35:27 CET 2015 x86_64 x86_64 x86_64 GNU/Linux`
Here is my docker version command return : 
```
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
```
also a file /usr/bin/docker returns : 
```
ELF 64-bit LSB  executable, x86-64, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.24, BuildID[sha1]=cea03ea625730fc1fb27dbcd639047a103864e0a, not stripped
```
Everything has been ran as root.
Thanks for helping out

**Comment by ankushagarwal** [comment]
Can you do a fresh install of docker on a fresh instance of Ubuntu 14.04. It looks like the apt-get install of docker polluted the environment. Following the installation instructions here should work : https://docs.docker.com/installation/ubuntulinux/

**Comment by neovea** [comment]
Hi, how can I remove everything which was installed via the script ?

**Comment by ankushagarwal** [comment]
Follow the instructions here  : https://docs.docker.com/installation/ubuntulinux/#uninstallation

**Comment by cpuguy83** [comment]
Hi, 

This is because devicemapper cannot be used with a statically compiled binary, as is the case with the version of docker provided by the get.docker.com scripts.
You can force it to use devicemapper, however this is not recommended as you are absolutely guaranteed to have issues, even data loss.

If you can, I'd recommend using aufs. Get this by installing the `linux-image-extra` package for your kernel. Docker will detect that the aufs mods exist and will use it.

Closing this since it's not really an issue, and is reported many times.
