### ISSUE TITLE
Remove the script at https://get.docker.com/ubuntu/

### ISSUE THREAD

**Issue by ankushagarwal** [docker/docker#14232]
People are using `https://get.docker.com/ubuntu/` to install docker and end up with problems because it does not install aufs (Example : https://github.com/docker/docker/issues/14204). https://get.docker.com/ubuntu/ should just redirect to `https://get.docker.com/`, so that people install docker on ubuntu correctly.

CC : @moxiegirl @thaJeztah @jfrazelle

**Comment by thaJeztah** [comment]
Hm, that's not the best experience, no. Wondering;

- Is there a specific reason for that script to exist separately?
- Did we actually *document* that URL, or is it just something people discovered

**Comment by ankushagarwal** [comment]
I don't see it anywhere in the docker/docker repo. I grepped the internet (using google) and the only reference I see is stackoverflow and github issues

**Comment by jfrazelle** [comment]
-1 for removing this, ping @tianon it is supposed to be bare minimal plus
we are redoing all this anyways


Also for your own curiosity it is generated in hack/release.sh but I will
not LGTM a PR for removal sorry

**Comment by thaJeztah** [comment]
Yup, did the same, so I guess people just found an "undocumented feature"

Thanks @jfrazelle, perhaps we should add a comment or something to notify people that that script might *not* be what they're looking for to perform a regular install.

**Comment by m1keil** [comment]
Hey, 
as one who just spent a good part of my day trying to debug this issue, it would be great if the changes between get.docker.com and get.docker.com/ubuntu could be documented and maybe echoed during the install ("aufs won't be installed").

**Comment by thaJeztah** [comment]
Yes, I was thinking of a similar approach as is used in the [main install script](https://github.com/docker/docker/blob/957622d452983f14bcc79443c9ff05780e1fd6bf/hack/install.sh#L53-L65) and add that to the [Ubuntu minimal install](https://github.com/docker/docker/blob/0f0f5ecd578d5d351b63b4d1799168ba5b3eef0c/hack/release.sh#L294-L312). We should still regard this an "edge case", because the documentation doesn't mention using this script for installing Docker.

@jfrazelle @tianon would that be acceptable for you?

**Comment by m1keil** [comment]
well.. it does, just for the [old version](http://beta-docs.docker.io/v1.4/installation/ubuntulinux/#for-precise-1204-lts). That's how I believe we hit the bug in the first place, seems like the installer shifted below our legs :-)

**Comment by vielmetti** [comment]
On Bing (yeah, I know, Bing) if you search for

```
site:docker.com ubuntu installation
```

you find 

```
script to install the Docker package on Ubuntu
https://get.docker.com/ubuntu
... ubuntu docker main > /etc/apt/sources.list.d/docker.list # Then import the repository key apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys ...
```

just below the fold. So yeah, it's not hard to discover, and if it's no longer correct it should be corrected.

**Comment by Pensu** [comment]
I have added a warning for the users to go with https://get.docker.com/ if they want aufs. Should be sufficient if someone wants aufs explicitly. @thaJeztah @moxiegirl

**Comment by m1keil** [comment]
:+1: Thanks

**Comment by moxiegirl** [comment]
Ref @Pensu PR https://github.com/docker/docker/pull/14343
