### ISSUE TITLE
doc: code markdown issue with "Getting Started" guide (minor)

### ISSUE THREAD

**Issue by charleswhchan** [docker/docker#14237]
Minor issue: When going thru the tutorial: http://docs.docker.com/mac/step_six/

The text for step 4 is messed up and not enclosed within a code block:
> 4.Type docker images to list the images you currently have:
> $ docker images REPOSITORY TAG IMAGE ID CREATED VIRTUAL SIZE docker-whale latest 7d9495d03763 38 minutes ago 273.7 MB 5dac217f722c 45 minutes ago 273.7 MB docker/whalesay latest fb434121fc77 4 hours ago 247 MB hello-world latest 91c95931e552 5 weeks ago 910 B

I wasn't able to find the file under /docs folder, otherwise I would have made the changes and submit a PR directly. By comparison step 7 looks alright.

Cheers.

**Comment by laijs** [comment]
@charleswhchan's post is clear, the document is also messed up in my box (flesh new firefox in fedora22)
![xxxxx](https://cloud.githubusercontent.com/assets/125671/8399056/f0a63bc8-1e37-11e5-9753-f4c9b9960749.png)

**Comment by vdemeester** [comment]
@laijs @charleswhchan thanks for reporting (@gordon is a post, don't mind its comment)

/ping @moxiegirl @thaJeztah

**Comment by thaJeztah** [comment]
Hm, I actually don't know which repository this documentation is in; could be a private repository. Perhaps @moxiegirl knows :)

**Comment by moxiegirl** [comment]
@charleswhchan Yep, this is in a currently private repository. I'll see about making this fix and potentially opening that repo.

**Comment by charleswhchan** [comment]
Thanks @moxiegirl, sounds good. :)

**Comment by moxiegirl** [comment]
@charleswhchan Thank you! For calling out the problem. Much appreciate the contribution.

**Comment by moxiegirl** [comment]
Fixed!
