### ISSUE TITLE
Parallel pull from V2 registry may lead to corruption of shared ancestor images

### ISSUE THREAD

**Issue by aarondav** [docker/docker#14239]
### Description

Pulling images with common ancestors from a V2 private registry seems to have some probability of corrupting the images, and the issue seems to stem from the client side. Serializing download of all images made the problem go away, but is not a good user solution because (A) it cannot be done correctly outside of the docker daemon and (B) it slows downloads which could otherwise be done in parallel.

Due to the severity of this issue, we have been unable to use the docker registry in production, for fear of corrupted images leading to hard-to-trace failures.

### Bug report

*List the steps to reproduce the issue:*
1. Execute many "docker pull" requests in parallel against images in a V2 private registry which share several common ancestors.
2. docker run all of them after downloads have been completed.

*Describe the results you received:*
Nondeterministically, this produces corrupt images. If ubuntu is corrupted, for instance, we may receive (during build time of subsequent images):
`System error: exec: "/bin/bash": stat /bin/bash: no such file or directory`

In other cases, we've seen aufs mount failed exceptions while running images which had been fully downloaded and built without error, but unfortunately I do not have one of these errors recorded.

*Describe the results you expected:*
Pulling and building should deterministically work with parallel operations.

*Provide additional info you think is important:*
We worked around the issue on our test machines and development environment by serializing all "docker pull" operations behind a global lock. This caused both the /bin/bash error and the aufs mount failed error to go away, and the build returned to relative stability.

*docker version:*
1.6.2

*docker info:*
Containers: 88
Images: 1715
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1891
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.11.0-26-generic
Operating System: Ubuntu 13.10
CPUs: 4
Total Memory: 15.38 GiB
WARNING: No swap limit support

*uname -a:*
Linux kitties 3.11.0-26-generic #45-Ubuntu SMP Tue Jul 15 04:02:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

*Provide additional environment details (AWS, VirtualBox, physical, etc.):*
Reproducible on AWS, boot2docker on Mac, and Linux laptop.

**Comment by stevvooe** [comment]
This should be covered by #14193.

**Comment by stevvooe** [comment]
Closing as fixed, for now. If 1.7.1 rc still sees issue, please re-open.

**Comment by joelapatatechaude** [comment]
Hi there,

I think I am still seeing this issue:

Building images on docker 1.8.2, build 0a8c2e3
Pushing to registry:2
Pulling images on 1.7.1, build 2c2c52b-dirty (coreos 766.3.0)

It looks like I am missing the layer where I installed java because some containers complains about it. If I run the container directly on the machine that build it (without pulling from registry:2) everything works fine. registry v1 works fine too.

**Comment by CybotTM** [comment]
Hi,

same problem here, pulled with 1.7.1 (RH) - so far it is okay if this is fixed in later releases, but after upgrading to 1.8.2 (RH) the problem did still not "go away" or got automatically fixed, we had to prune all images and pull again - would be nice if there would be an option to check/verify pulled images.

**Comment by stevvooe** [comment]
@CybotTM Please avoid commenting on closed issues.

Docker 1.10 has done a lot to address these kinds of problems. Specifically, the download manager addressed the concurrency problems leading to corruption. I'd recommend trying it out.
