### ISSUE TITLE
docker strips 127.0.0.1 from resolv.conf even in --net=host mode

### ISSUE THREAD

**Issue by rncry** [docker/docker#14246]
Is this desired behaviour?

We're running a local consul agent which is being used as a dns server locally (for dynamic service discovery). We've added 127.0.0.1 to resolv.conf on hosts so dns lookups are handled by the consul agent.

However when docker starts it strips any local resolvers from resolv.conf, which makes sense for containers in bridged mode, but shouldn't this be allowed when --net=host?

**Comment by rncry** [comment]
Or perhaps replacing 127.0.0.1 with the ip address of the docker container?

**Comment by rncry** [comment]
docker version: Docker version 1.7.0, build 0baf609
docker info: Containers: 3
Images: 72
Storage Driver: aufs
 Root Dir: /mnt/data/docker/graph/aufs
 Backing Filesystem: extfs
 Dirs: 78
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-55-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 3.859 GiB
Name: ip-172-20-121-181
ID: AVBV:2KB4:5R7R:XQ7E:RGDS:XSSA:XMN5:5YS2:HCYV:P7VV:FPSH:SRII
WARNING: No swap limit support

uname -a: Linux ip-172-20-121-181 3.13.0-55-generic #94-Ubuntu SMP Thu Jun 18 00:27:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by calavera** [comment]
This should be fixed on master and was merged into the release branch #14264. Closing.
