### ISSUE TITLE
Docs: Horizontal Slider 

### ISSUE THREAD

**Issue by HuKeping** [docker/docker#14247]
There are some example of remote API like: [Inspect a container](https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api_v1.20.md#inspect-a-container), [Exec Inspect](https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api_v1.20.md#exec-inspect) have horizontail sliders due to the over long text.

Is this what we want or can we update that?

**Comment by HuKeping** [comment]
ping @moxiegirl

**Comment by moxiegirl** [comment]
@HuKeping we've always had horizontal sliders in our docs.  They also existed in the older documentation layout.  We don't have any plans to change this.
