### ISSUE TITLE
device mapper suport in docker 1.7

### ISSUE THREAD

**Issue by rohit-conn** [docker/docker#14255]
Hi,

On upgrade to docker 1.7 support for device mapper as a storage driver is limited to dynamically compiled binary only.
Is there any work around are alternative that can help me use it with the static binary.

**Comment by cpuguy83** [comment]
You can certainly force it to start, which is not recommended.
But unfortunately no, it is not possible for devicemapper to work correctly with a static binary.

Closing this, but if you need some extra help, please feel free to ping on IRC.

Thanks!
