### ISSUE TITLE
Proposal: pull down JSON file independent from an image

### ISSUE THREAD

**Issue by miminar** [docker/docker#14257]
As a Docker user, I'd like to be able to inspect remote images without downloading binary blobs.

## Possible interface
Add `-r` flag to `docker inspect` denoting *inspect remote registry*. Unless given, keep the old behavior.

### Example:

    docker inspect -r docker.io/fedora
    [
    {
        "Id": "ded7cd95e059788f2586a51c275a4f151653779d6a7f4dad77c2bd34601d94e4",
        "Parent": "48ecf305d2cf7046c1f5f8fcbcd4994403173441d4a7f125b1bb0ceead9de731",
        ...
        "Os": "linux",
        "Size": 186515831
    }]

**Comment by LK4D4** [comment]
looks like https://docs.docker.com/registry/spec/api/#/get-manifest
