### ISSUE TITLE
Pull from Docker Hub stopped working - failed to parse certificate

### ISSUE THREAD

**Issue by tehsenaus** [docker/docker#14260]
Something must have changed recently, as I cannot pull images from Docker Hub anymore. I get the following error:

```
$ docker pull jwilder/nginx-proxy:latest
Pulling repository jwilder/nginx-proxy
2015/06/29 14:01:10 Get https://index.docker.io/v1/repositories/jwilder/nginx-proxy/images: tls: failed to parse certificate from server: x509: RSA modulus is not a positive number
```

I am behind a corporate proxy, so I suspect it's something to do with that. This was working fine in the past though, and has only recently started returning the error above. I have been using Docker for over 6 months with no such issue.

Running curl on the URL above works as expected.

**Comment by cpuguy83** [comment]
Hello, can you open a ticket with support.docker.com?

Thanks!

**Comment by joysarkarhub** [comment]
I am faceing same issue too...Any luck?
