### ISSUE TITLE
Experimental script outdated

### ISSUE THREAD

**Issue by aanm** [docker/docker#14263]
Is the experimental script correct? https://experimental.docker.com/
```
# This script is meant for quick & easy install via:
#   'curl -sSL https://get.docker.com/ | sh'
# or:
#   'wget -qO- https://get.docker.com/ | sh'
```
and even the fedora installation only points to the yum/dnf command

**Comment by ankushagarwal** [comment]
I would think this is correct as per the following section
```
set -x
if [ "https://get.docker.com/" = "$url" ]; then
  $sh_c "apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9"
elif [ "https://test.docker.com/" = "$url" ]; then
  $sh_c "apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 740B314AE3941731B942C66ADF4FD13717AAD7D6"
elif [ "https://experimental.docker.com/" = "$url" ]; then
  $sh_c "apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys E33FF7BF5C91D50A6F91FFFD4CC38D40F9A96B49"
else
  $sh_c "$curl ${url}gpg | apt-key add -"
fi
$sh_c "echo deb ${url}ubuntu docker main > /etc/apt/sources.list.d/docker.list"
$sh_c 'sleep 3; apt-get update; apt-get install -y -q lxc-docker'
```

You can also download the experimental binary directly here : 
```
https://experimental.docker.com/builds/Linux/x86_64/docker-latest
```

**Comment by jordimassaguerpla** [comment]
Hi!
for SUSE it only runs

zypper -n install docker

which will install the docker in the SUSE repos, which is not the experimental one.

I can provide such package and how to install it. I just need to know how to properly build it. Is experimental a package from master branch? I guess I could just adapt https://github.com/docker/docker/commits/master/hack/make/.build-rpm/docker-engine.spec

right?

**Comment by aanm** [comment]
Duplicate of #14188
