### ISSUE TITLE
Issue running docker -d

### ISSUE THREAD

**Issue by dbclkclk** [docker/docker#14265]
Use the commands below to provide key information from your environment:

### docker version:

     Client version: 1.6.2
     Client API version: 1.18 
     Go version (client): go1.4.2
     Git commit (client): ba1f6c3/1.6.2
     OS/Arch (client): linux/amd64
     Server version: 1.6.2
     Server API version: 1.18
     Go version (server): go1.4.2
     Git commit (server): ba1f6c3/1.6.2
     OS/Arch (server): linux/amd64

### docker info:

      Pool Name: docker-253:0-207386140-pool
      Pool Blocksize: 65.54 kB
      Backing Filesystem: xfs
      Data file: /dev/loop0
      Metadata file: /dev/loop1
      Data Space Used: 9.585 GB
      Data Space Total: 107.4 GB
      Data Space Available: 25.33 GB
      Metadata Space Used: 7.643 MB
      Metadata Space Total: 2.147 GB
      Metadata Space Available: 2.14 GB
      Udev Sync Supported: true
      Data loop file: /var/lib/docker/devicemapper/devicemapper/data
      Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
      Library Version: 1.02.93-RHEL7 (2015-01-28)
     Execution Driver: native-0.2
     Kernel Version: 3.10.0-229.7.2.el7.x86_64
     Operating System: CentOS Linux 7 (Core)
     CPUs: 4
    Total Memory: 7.524 GiB
    Name: localhost.localdomain
    ID: GGNJ:KL4R:EHDQ:Q7Y4:KGIT:J57E:IFDC:IMVA:RYN2:LDOM:MXAH:5C5J

### uname -a:

     Linux localhost.localdomain 3.10.0-229.7.2.el7.x86_64 #1 SMP Tue Jun 23 22:06:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

### List the steps to reproduce the issue:

1. Inside my docker container, run `ping google.com` and got `ping: unknown host google.com`
2. type `exit` and then followed steps: 

     *pkill docker
     *iptables -t nat -F
     *ifconfig docker0 down
     *brctl delbr docker0
      *docker -d

### Describe the results you received:

At the point of running `docker -d`, I got this error:

      ERRO[0000] WARNING: No --storage-opt dm.thinpooldev specified, using loopback; this configuration is strongly discouraged for production use 
      INFO[0000] +job serveapi(unix:///var/run/docker.sock)   
      INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
      INFO[0000] +job init_networkdriver()                    
      INFO[0000] -job init_networkdriver() = OK (0)           
      INFO[0000] Loading containers: start.                   
      ........
     INFO[0000] Loading containers: done.                    
     INFO[0000] docker daemon: 1.6.2 ba1f6c3/1.6.2; execdriver: native-0.2; graphdriver:   devicemapper 
     INFO[0000] +job acceptconnections()                     
     INFO[0000] -job acceptconnections() = OK (0)            
     INFO[0000] Daemon has completed initialization  

### Describe the results you expected:

Restart docker and when I return to my container, I'm able to access the internet. 

### Provide additional info you think is important:

As mentioned, within my docker container, I'm trying to access the internet and wasn't able to. I found this instruction about restarting my network interface for docker0 https://github.com/docker/docker/issues/866#issuecomment-19218300

However, at the point of running `docker -d`, I got an error and the container isn't restarting. I have to run `service docker start` for it to run however, going back inside the container, I'm still not able to access the internet.

**Comment by cpuguy83** [comment]
I'm not certain what issue you are referring to here.
Can you provide some extra details?

**Comment by dbclkclk** [comment]
@cpuguy83 just updated the first post.

**Comment by cpuguy83** [comment]
Hmm, that "ERROR" is not really an error, it's a warning, and is unrelated.

**Comment by dbclkclk** [comment]
OK but, what about the issue when I run `docker -d` and the container isn't started? This has never happened before and I tried the step before (few days ago) and it worked and was able to access the internet. BTW, `firewalld` is turned off.

**Comment by cpuguy83** [comment]
When docker exits it stops all containers. When it starts it will force kill anything that didn't stop.
If you have `--restart=always` set on the container, it will restart those.

Otherwise you should expect your container to be stopped.

**Comment by dbclkclk** [comment]
OK how about the issue of not access the internet?

**Comment by cpuguy83** [comment]
@dbclkclk For that, I'd suggest hitting up #docker on IRC or the docker-user ML for support.

Closing since this is not related to a specific docker issue.
