### ISSUE TITLE
question: how docker commit works in devicemapper storage backend

### ISSUE THREAD

**Issue by sainath14** [docker/docker#14274]
when i do a docker commit of a container, i notice it does the following
1. activate the devmapper volume of the container 
2. activate the devmapper volume for the xx-init of the container
3. unmount and deactivate the devmapper volume for xx-init of the container
4. create a snap device from the container's image topmost layer
5. Start untar
6. deactivate and Unmount the snap device created

Could some one please elaborate on why do we need to activate the devmapper volume for xx-init of the container? Also how is the difference between the the container volume and xx-init volume of the container captured and applied to the new snap device?

**Comment by unclejack** [comment]
@sainath14 Diff is done with -init as the source and the container as the destination. The resulting diff is applied to a new layer based on the parent of the -init layer.

**Comment by sainath14** [comment]
@unclejack is the difference captured between two directories? Directories of mounted container volume and mounted -init volume? What library/tool does docker use to capture the difference between directories?
