### ISSUE TITLE
Proposal: Support base url in the client

### ISSUE THREAD

**Issue by vieux** [docker/docker#14270]
Today in the client you can use `-H` with `unix://<file>`, `tcp://<ip:port>` and `fd://<num>`

I'm currently hosting my docker daemon behind a Reverse Proxy (nginx).
I wonder if the docker client should support

`-H tcp://<ip:port></path>` or `-H http://<ip></path>` 

What do you guys think ?

**Comment by crosbymichael** [comment]
This is not supporting a reverse proxy, its for supporting a base URL right?

**Comment by vieux** [comment]
@crosbymichael yes, sorry if it's confusing

**Comment by LK4D4** [comment]
Makes sense for me. We just need little modify parsing and router creation.

**Comment by huslage** [comment]
Can you clarify the use case here?

**Comment by crosbymichael** [comment]
`/containers/redis`
vs
`/mydockerapi/containers/redis`

**Comment by vieux** [comment]
@huslage My docker daemon is behind a reverse proxy (nginx) 
I want to do `docker -H tcp://50.10.12.23/swarm info` and go through my reverse proxy hosted at 50.10.12.23.

@crosbymichael @LK4D4 are you more in favor of changing `tcp://` or using `http://`

I think `tcp` makes more sense.

**Comment by LK4D4** [comment]
@vieux Yes, I don't want new proto to handle.

**Comment by vieux** [comment]
@LK4D4 cool, I'll open a PR soon.

**Comment by calavera** [comment]
It might make sense to support `http` and `https` as proto too. The api talks http anyways.

**Comment by vieux** [comment]
Today we differentiate proto and scheme, the scheme is always `http` or `https` (if a tlsconfig is given)
and then we use this scheme on any proto (unix/tcp)

**Comment by vdemeester** [comment]
There was another issue on this : https://github.com/docker/docker/issues/13871. I submitted a PR that is related : https://github.com/docker/docker/pull/14285. Let me know what you think.
