### ISSUE TITLE
Upstart scripts don't wait for main docker process after hard restart

### ISSUE THREAD

**Issue by sheavner** [docker/docker#14272]
If we hard reboot a server (i.e. via a big red button or simulation thereof) on restart, none of our container upstart scripts wait for the main docker process to start up and they all exit as failed without successfully starting anything.   

Attempted adding ```rm -f /var/run/docker.sock``` to the end of the pre-start script, but this wasn't sufficient to correct the issue.    /var/run/docker.sock exists if the machine is hard rebooted and exists prior to starting the docker upstart script.   A second clean reboot immediately after the unclean restart fixes things.

Docker version: 1.6.0, build 4749651

Docker Info:
Containers: 9
Images: 1252
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1270
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-48-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 8
Total Memory: 14.68 GiB
Name: amoeba
ID: 3UTJ:747V:7H3D:VLOB:YEWT:VO52:WNBX:JFZC:4S3T:FNP7:LB3L:ZJBA

uname -a:
Linux hostname 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

See file docker/contrib/init/upstart/docker.conf

**Comment by sheavner** [comment]
Closed pull request, not sufficient to fix issue.   May be part of complete solution.

**Comment by cpuguy83** [comment]
Are you checking the upstart logs as to why it's not starting properly?
