### ISSUE TITLE
Docker 1.7 consuming more space than Docker 1.5 for images

### ISSUE THREAD

**Issue by motaro** [docker/docker#14279]
Initially i had docker 1.5 installed in ubuntu Trusty via Vagrant.

Then i created new Ubuntu Trusty and now the docker version is 1.7.

I tried building Image of my Postgres Container with this Dockerfile

https://gist.github.com/anonymous/19cf7ede56c5a4499201

Now when i check my ubuntu with docker 1.5 the
```
Filesystem           Size  Used Avail Use% Mounted on
/dev/sda1             40G  2.3G   36G   6% /
none                 4.0K     0  4.0K   0% /sys/fs/cgroup
```
When i check on docker 1.7 then
```
Filesystem           Size  Used Avail Use% Mounted on
/dev/sda1             40G   14G   24G  38% /
none                 4.0K     0  4.0K   0% /sys/fs/cgroup 
```
I have specifically tested with only one image and nothing else on the server.
I have even checked the disk usage and its coming from /var/lib/docker/vfs/dir
I want to know what have changed in 1.7 thats causing this

**Comment by cpuguy83** [comment]
I'm absolutely certain this is a dup, but GH search fails so hard.

But in any case, can you paste your `docker info` and `docker version` output?

**Comment by motaro** [comment]
Thanks I solved it from here

https://forums.docker.com/t/docker-1-7-0-is-using-huge-amount-of-disk-space/2046/2
