### ISSUE TITLE
Wheezy link is broken on debian page

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#14287]
![image](https://cloud.githubusercontent.com/assets/1347209/8431290/3f52f26a-1eed-11e5-8356-29042a55dd25.png)

**Comment by Tenk42** [comment]
#dibs

**Comment by runcom** [comment]
closing #14309 merged

**Comment by thaJeztah** [comment]
Thanks @runcom apparently GitHub didn't like the colon (:)
