### ISSUE TITLE
where is the contains file in 1.7

### ISSUE THREAD

**Issue by loveai88** [docker/docker#14283]
When I use 1.6,I found that the contain files all in /var/lib/docker/devicemapper/mnt  which directory named contain id,but I can not found the file in 1.7.How can i see it?
Thanks

docker version :1.7.0, build 0baf609
docker info:
```
Containers: 102
Images: 117
Storage Driver: devicemapper
 Pool Name: docker-253:0-6684678-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file:
 Metadata file:
 Data Space Used: 4.785 GB
 Data Space Total: 107.4 GB
 Data Space Available: 102.6 GB
 Metadata Space Used: 13.51 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.134 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.80-1.el6.elrepo.x86_64
Operating System: <unknown>
CPUs: 4
Total Memory: 31.46 GiB
Name: store40
ID: VAD6:HWJP:TJYY:HZJH:W7KW:GI5I:FLVE:4X6S:QZA4:WO35:BQZI:CB7H
WARNING: No swap limit support
```
uname -r :3.10.80-1.el6.elrepo.x86_64

**Comment by benfb** [comment]
From inside the container, `cat /proc/self/cgroup` should return a bunch of strings like this `2:cpu:/docker/4ac0c2ebe190b523bf5fe79d5efc4ec6d06830feaeba8beb31096adbcf3b5b25` where `4ac0c2ebe...` is the id. From outside the container you can just run `docker ps`. Not sure if there's a better way from inside the container.

**Comment by cpuguy83** [comment]
It's still there.

Closing since there is no issue here.
