### ISSUE TITLE
Ability to map to any available port in range 

### ISSUE THREAD

**Issue by tarlabs** [docker/docker#14280]
Hi All,

Not sure if this is something docker currently supports, but I couldn't find any information. Currently when we do a port mapping we do it like `-p 8888:8888`, this is good when we are running a static number of containers.

I am looking at a capability where docker can map to any available port on host specified within a range. This would allow to expose the port directly through host. something like `-p 8000-9000:8888`. This should dynamically map to any available port on that range. 

Would like to know your thoughts on the same and if there is any such plan to include this feature in docker?

Regards,
Tarun

**Comment by bru7us** [comment]
See #12622, #12927 (docker/libnetwork#285) and #13322 for existing discussions on the matter....

**Comment by tarlabs** [comment]
@bru7us, Thanks I will close this and follow those discussions
