### ISSUE TITLE
docker [1.7.0] ps output breaks certain compatibility

### ISSUE THREAD

**Issue by michaelshobbs** [docker/docker#14293]
In some dokku plugins (ex: https://github.com/Kloadut/dokku-pg-plugin/blob/35edfebd9bc4eafcdf9f3ecfc32cef3404853b9b/commands#L42) the image tag was used to identify a particular running container. 

Why drop this from the output and is there a way to gain it back (with arguments perhaps?)

related: https://github.com/progrium/dokku/issues/1263

**Comment by cpuguy83** [comment]
This was most likely unintentional.

**Comment by runcom** [comment]
oh I recall this

**Comment by michaelshobbs** [comment]
I see. This just seems like a weird thing to change. Please correct me if I'm wrong but the net result is if you exec `docker run myimage:tag`, `docker ps` will show the tag but if you run `docker run myimage`, you get no tag? Why change the output when you're still actually running the `latest` tag in the latter case?

**Comment by michaelshobbs** [comment]
Any suggestions on what to do here?

**Comment by icecrime** [comment]
Tentatively closing as the issue seems to be resolved by #12918: please let me know if it needs reopening! Thanks.
