### ISSUE TITLE
Docker 1.6.2 missing from Ubuntu package site

### ISSUE THREAD

**Issue by stevenschlansker** [docker/docker#14301]
```
Hit https://get.docker.com docker Release                                  
Hit https://get.docker.com docker/main amd64 Packages    
root@ab64cdfc5bf1:/var/cache/debconf# apt-get install lxc-docker=1.6.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Version '1.6.2' for 'lxc-docker' was not found
```

Docker 1.7.0 breaks our deployment process, and now we cannot install the working 1.6.2 version.  So we cannot provision any new machines in this state.

Please do not remove old versions from the package site, they are small and it is really nasty to get rid of them.

I suspect this is because the release.sh script regenerates the Debian mirror metadata files without considering prior releases, only the current one:
https://github.com/docker/docker/blob/master/hack/release.sh#L270

**Comment by phemmer** [comment]
I think this is a dup of #13191

**Comment by LK4D4** [comment]
ping @tianon

**Comment by stevenschlansker** [comment]
Yes, duplicate, sorry.
