### ISSUE TITLE
Filter on push events for a specific image

### ISSUE THREAD

**Issue by venkatramachandran** [docker/docker#14316]
I am trying to use `docker events` to list push events for a specific image(as a part of my CI/CD pipeline - the push event would be a trigger to pull the image and create a new container). Running `docker events --filter 'event=push' --filter 'image=<name>'` does not give me any event when a new image is pushed to the repo.
`docker events --filter 'event=push'` does work for but all image push events. `docker events --filter 'image=<name>'` works but lists create/destroy events as well.
Is there no way to filter specific image's push events?

**Comment by venkatramachandran** [comment]
```
vagrant@vagrant:~$ docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
vagrant@vagrant:~$ docker info
Containers: 5
Images: 118
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 128
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-55-generic
Operating System: Ubuntu 14.04 LTS
CPUs: 1
Total Memory: 2.939 GiB
Name: vagrant
ID: OXRP:6VZL:PLXK:Y7SU:EFEI:2KF5:PILP:UKXH:35MK:CUC6:VOP4:G75Q
WARNING: No swap limit support
vagrant@vagrant:~$ uname -a
Linux vagrant 3.13.0-55-generic #94-Ubuntu SMP Thu Jun 18 00:27:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
vagrant@vagrant:~$ 
```

Environment: vagrant

List the steps to reproduce the issue:
1. Run `docker events --filter 'event=push' --filter 'image=<name>'`

Describe the results you received:
No events generated when a new image with name `<name>` is pushed to the repo.

Describe the results you expected:
An event is generated when a new image with name `<name>` is pushed to the repo.

**Comment by runcom** [comment]
@venkatramachandran thanks for the report, I'm looking into this

**Comment by venkatramachandran** [comment]
:+1:
