### ISSUE TITLE
Containers can't reach outside network randomly...

### ISSUE THREAD

**Issue by rrfeng** [docker/docker#14313]
I don't know what happened or what I did cause this problem.

when problem comes, no container can reach outside, I used ping and tracepath, in containers, only can reach the HOST IP.

Restart the docker service can fix this.

- on EC2, AMI Linux

Is there anyone else who has this problem?

**Comment by LK4D4** [comment]
I think it is duplicate of #14073

**Comment by rrfeng** [comment]
yes，thank you.
