### ISSUE TITLE
FROM instruction not part of image

### ISSUE THREAD

**Issue by geku** [docker/docker#14311]
When building a new image with a Dockerfile based on an existing one, e.g. FROM debian:wheezy, then the FROM instruction is not part of the final image, but all other instructions are added to it.

Now, why is the FROM instruction of interest? One use case is to identify if the parent image is out of date and hence the current image should be rebuilt based on a newer parent image.

`docker version`:
````
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): darwin/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
````

`docker info`:
````
Containers: 15
Images: 319
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 349
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 4.0.3-boot2docker
Operating System: Boot2Docker 1.6.2 (TCL 5.4); master : 4534e65 - Wed May 13 21:24:28 UTC 2015
CPUs: 4
Total Memory: 1.957 GiB
Name: boot2docker
ID: 2233:AAFF:IGML:K3VS:R7WC:4MER:KUU3:MDYG:2M5U:7HRA:LVHX:H3SW
Debug mode (server): true
Debug mode (client): false
Fds: 12
Goroutines: 17
System Time: Tue Jul  7 14:26:14 UTC 2015
EventsListeners: 0
Init SHA1: 7f9c6798b022e64f04d2aff8c75cbf38a2779493
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
````

`uname -a`:
````
Linux boot2docker 4.0.3-boot2docker #1 SMP Wed May 13 20:54:49 UTC 2015 x86_64 GNU/Linux
````

Environment details (AWS, VirtualBox, physical, etc.):
VirtualBox

#### Steps to Reproduce:

1. Show history for an image built by a Dockerfile: `docker history redis:3.0.1`

**Actual Results:**

````
95af5842ddb9        8 weeks ago         /bin/sh -c #(nop) CMD ["redis-server"]          0 B
eb3ba1568dec        8 weeks ago         /bin/sh -c #(nop) EXPOSE 6379/tcp               0 B
3796e141ac51        8 weeks ago         /bin/sh -c #(nop) ENTRYPOINT ["/entrypoint.sh   0 B
37f0390d9546        8 weeks ago         /bin/sh -c #(nop) COPY file:c4bbead0efd18835c   109 B
eb0a79a8f15f        8 weeks ago         /bin/sh -c #(nop) WORKDIR /data                 0 B
480d8f032bc5        8 weeks ago         /bin/sh -c #(nop) VOLUME [/data]                0 B
648d9befdc15        8 weeks ago         /bin/sh -c mkdir /data && chown redis:redis /   0 B
a6f2f4d93716        8 weeks ago         /bin/sh -c buildDeps='gcc libc6-dev make';      s                   9.373 MB
79d59cc55f8f        8 weeks ago         /bin/sh -c #(nop) ENV REDIS_DOWNLOAD_SHA1=fe1   0 B
9459d638c6f2        8 weeks ago         /bin/sh -c #(nop) ENV REDIS_DOWNLOAD_URL=http   0 B
5d02ef3689d5        8 weeks ago         /bin/sh -c #(nop) ENV REDIS_VERSION=3.0.1       0 B
8d9a45a71a91        10 weeks ago        /bin/sh -c curl -o /usr/local/bin/gosu -SL "h   2.141 MB
c215cb712b89        10 weeks ago        /bin/sh -c gpg --keyserver pool.sks-keyserver   98.87 kB
b720af9a6508        10 weeks ago        /bin/sh -c apt-get update                       && apt-get install   14.13 MB
29809ed33dfd        10 weeks ago        /bin/sh -c groupadd -r redis && useradd -r -g   328.3 kB
b3d362b23ec1        10 weeks ago        /bin/sh -c #(nop) CMD ["/bin/bash"]             0 B
21e4345e9035        10 weeks ago        /bin/sh -c #(nop) ADD file:20cd6318f68d34ca8e   84.98 MB
````

**Expected Results:**

Expected to have an image layer specifically for the `FROM` instruction, similar to e.g. the `CMD` instruction which is visible in image 95af5842ddb9 and b3d362b23ec1 above.

**Comment by duglin** [comment]
The image is in there, its image ID `b3d362b23ec1`. What's missing is something to indicate that its the `debian:wheezy` tag or its there because of the `FROM`. The reason it doesn't show up as a separate layer is because there's no need for it to - there's no change being made. As an example, the CMD command results in the metadata of the image being modified.  FROM just means, start with this image - nothing needs to change on anything.

If you want to know when a parent image is out of date I think you'll need to compare the image ID of the image in question and see if its different from the image ID in your history - if so then you need to rebuild.  Or, I guess just check to see if the imageID of your base image is found (ala grep) in your history, and if not then rebuild.  

```
docker history redis | grep $(docker inspect -f "{{ .Id }}" debian:wheezy | cut -c 1-12)
```
Should do it.
