### ISSUE TITLE
Memory usage not reported correctly

### ISSUE THREAD

**Issue by bobhlo** [docker/docker#14325]
The memory usage and quota don't seem to agree.  How do I get memory usage for a container?

Containers are created with cf container broker. For testing, each container is limited to use 25m of memory (based on 'docker inspect'), but the memory usage is reported as ~600m (based on memory.usage_in_bytes). 

root@4c45cfdb-82df-46d4-89a8-f04fe9af07a0:/# docker --version
Docker version 1.6.0, build 4749651

root@4c45cfdb-82df-46d4-89a8-f04fe9af07a0:/# docker --host unix:///var/vcap/sys/run/docker/docker.sock ps
CONTAINER ID        IMAGE                  COMMAND             CREATED             STATUS              PORTS                                                                      NAMES
dc64cdc2ee07        lnguyen/logstash:1.4   "/scripts/run.sh"   18 hours ago        Up 18 hours         0.0.0.0:32771->514/tcp, 0.0.0.0:32772->9200/tcp, 0.0.0.0:32773->9300/tcp   cf-e59dec24-cf2e-43c9-b1e9-2a36d3fb7902   
root@4c45cfdb-82df-46d4-89a8-f04fe9af07a0:/# cat /sys/fs/cgroup/memory/docker/dc64cdc2ee0743e76c3bf6551f47697a957f86552a68d4583882074bd9b876c4/memory.usage_in_bytes
604872704

root@4c45cfdb-82df-46d4-89a8-f04fe9af07a0:/# docker --host unix:///var/vcap/sys/run/docker/docker.sock inspect dc64cdc2ee07|grep Memory
        "Memory": 26214400,
        "MemorySwap": 0,
        "Memory": 0,
        "MemorySwap": 0,

**Comment by bobhlo** [comment]
root@4c45cfdb-82df-46d4-89a8-f04fe9af07a0:/# cat /sys/fs/cgroup/memory/docker/dc64cdc2ee0743e76c3bf6551f47697a957f86552a68d4583882074bd9b876c4/memory.stat
cache 4861952
rss 599449600
rss_huge 0
mapped_file 471040
writeback 0
swap 0
pgpgin 277094
pgpgout 129557
pgfault 298893
pgmajfault 0
inactive_anon 8192
active_anon 599998464
inactive_file 589824
active_file 3715072
unevictable 0
hierarchical_memory_limit 18446744073709551615
hierarchical_memsw_limit 18446744073709551615
total_cache 4861952
total_rss 599449600
total_rss_huge 0
total_mapped_file 471040
total_writeback 0
total_swap 0
total_pgpgin 277094
total_pgpgout 129557
total_pgfault 298893
total_pgmajfault 0
total_inactive_anon 8192
total_active_anon 599998464
total_inactive_file 589824
total_active_file 3715072
total_unevictable 0

**Comment by LK4D4** [comment]
@bobhlo What kernel version do you use?

**Comment by bobhlo** [comment]
root@d1636972-508c-4f00-a871-841f22a378cc:/var/vcap/bosh_ssh/bosh_kah85ph3g# uname -a
Linux d1636972-508c-4f00-a871-841f22a378cc 3.16.0-31-generic #43~14.04.1-Ubuntu SMP Tue Mar 10 20:13:38 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
root@d1636972-508c-4f00-a871-841f22a378cc:/var/vcap/bosh_ssh/bosh_kah85ph3g# docker --host unix:///var/vcap/sys/run/docker/docker.sock info
Containers: 2
Images: 34
Storage Driver: aufs
 Root Dir: /var/vcap/store/docker/docker/aufs
 Backing Filesystem: extfs
 Dirs: 38
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.16.0-31-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 32
Total Memory: 58.81 GiB
Name: d1636972-508c-4f00-a871-841f22a378cc
ID: RCLY:TYQD:BYJ6:4DMN:PXG4:SI52:3QUA:4X5V:H4NK:HDMD:CS4G:MUK5

**Comment by hqhq** [comment]
Seems your memory limit didn't work, how do you set your memory limit?
According to inspect, there are two memory and memoryswap, it should work for both of them, but I'm not sure if there would be a broken version. Better choice is upgrade Docker version, I'm sure the problem would gone.

**Comment by bobhlo** [comment]
Configured container memory quota according to https://github.com/cf-platform-eng/docker-boshrelease/blob/master/CONTAINERS.md

Excerpt from manifest -
      plans:
      - container:
          backend: docker
          image: lnguyen/logstash
          tag: '1.4'
          memory: '25m'

Excerpt from inspect output - 
```
[{
    "AppArmorProfile": "",
    "Args": [],
    "Config": {
...
        "Memory": 26214400,
        "MemorySwap": 0,
...
    },
...
    "HostConfig": {
...
       "Memory": 0,
       "MemorySwap": 0,
```

**Comment by bobhlo** [comment]
Checked the change logs, but not seeing bug/fix regarding to resource constrains like memory - https://github.com/docker/docker/blob/master/CHANGELOG.md

**Comment by hqhq** [comment]
Resource configs have been moved to HostConfig long time ago, we did have backward compatibility, but it might be removed in engine refactor, it's not on purpose, so probability not recorded in `CHANGELOG.md`.
Can you try to set the limit in `HostConfig`? Or upgrade Docker version? It'd too old to debug or fix, because codes are quite different, and current release is 1.7.0, I don't know if there are anyone maintaining 1.6.0.

**Comment by bobhlo** [comment]
In the manifest, how do we configure mem quota for ```HostConfig```?

**Comment by cpuguy83** [comment]
@bobhlo There's "Memory" and "MemorySwap" in HostConfig.

**Comment by cpuguy83** [comment]
Also, the backwards compat seems to be working just fine, at least on master.

**Comment by bobhlo** [comment]
@cpuguy83: Can you post the output from 'uname -a', 'docker info', 'docker inspect',  'memory.usage_in_bytes' for the container?  If you were able to change 'Memory' for HostConfig, how did you do it? 

My experience with docker 1.6.0 was the memory usage from container was not correctly reported. However, my manifest deployed below changes 'Memory' in Config, but not HostConfig. 

```
      plans:
      - container:
          backend: docker
          image: lnguyen/logstash
          tag: '1.4'
          memory: '25m'
```

**Comment by cpuguy83** [comment]
@bobhlo I don't know what thing you have pasted there is, but this works:

```
curl -XPOST -H 'Content-Type: application/json' localhost:2376/containers/create -d '{"Image": "busybox", "HostConfig": { "Memory": 12346}}'
```
