### ISSUE TITLE
Remote API 1.19, containers attach, error handling

### ISSUE THREAD

**Issue by goloroden** [docker/docker#14320]
We are using [dockerode](https://github.com/apocas/dockerode) to connect from a Node.js application to a Docker server and attach to a container to fetch its logs.

With Docker 1.6.2 (remote API 1.18) everything worked fine. When we tried to access a non-existent container, dockerode returned an `Error` object.

With Docker 1.7.0 (remote API 1.19) we now have the effect that dockerode does not recognize any more if you try to attach to a non-existing container, i.e. we do not get an `Error` object any longer. The only evidence is that the stream contains a line such as

> Error attaching: no such id: my-non-existent-container

According to the API documentation Docker should return a `404` in this case, and [dockerode apparently handles 404s](https://github.com/apocas/dockerode/blob/51359d09220bda77b71d7c388bbc2948d386d3b6/lib/container.js#L412). Since the very same code worked for remote API 1.18, we *guess* that it *may* be a problem with the remote API 1.19.

Could anybody please be so kind to verify this issue? Are we doing something wrong?

We are using Docker 1.7.0 on OS X 10.10.3. The output of `uname -a` is

> Darwin Schneehase.fritz.box 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

The output of `docker -D info` is

    Containers: 0
    Images: 854
    Storage Driver: aufs
     Root Dir: /mnt/sda1/var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 854
     Dirperm1 Supported: true
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 4.0.5-boot2docker
    Operating System: Boot2Docker 1.7.0 (TCL 6.3); master : 7960f90 - Thu Jun 18 18:31:45 UTC 2015
    CPUs: 8
    Total Memory: 1.955 GiB
    Name: dev
    ID: 3DDJ:EO4N:TYCN:NV2P:L43F:KWZN:HJOL:7JWA:VS4R:D5K4:5R42:GUN6
    Debug mode (server): true
    File Descriptors: 13
    Goroutines: 20
    System Time: 2015-07-01T15:13:15.703543084Z
    EventsListeners: 1
    Init SHA1: 
    Init Path: /usr/local/bin/docker
    Docker Root Dir: /mnt/sda1/var/lib/docker
    Username: $MYUSERNAME
    Registry: https://index.docker.io/v1/
    Labels:
     provider=virtualbox

**Comment by runcom** [comment]
found, pr coming

**Comment by cpuguy83** [comment]
Thanks @runcom!

**Comment by runcom** [comment]
@goloroden thanks for reporting!

**Comment by goloroden** [comment]
You're welcome, and kudos for fixing it **that** fast - this really is impressive :-)
