### ISSUE TITLE
Problem with Docker remote API

### ISSUE THREAD

**Issue by santosh0705** [docker/docker#14328]
Im writing a Perl remote API and using Docker v1.4.1

If I use HTTP/1.1 with /events its working fine but if I use HTTP/1.0 its not working. However it work fine in Python or if I netcat on commanline.

Here is the piece of code what I'm trying:

```
#!/usr/bin/perl

use IO::Socket;

my $client = IO::Socket::UNIX->new(
    Type => SOCK_STREAM(),
    Peer => "/var/run/docker.sock",
);

send($client, "GET /events HTTP/1.1\r\n\r\n", 0);

while (1)
{
    recv($client, $data, 1, 0);
    print "$data";
}
```

**Comment by LK4D4** [comment]
@santosh0705 I think this is because of `Transfer-Encoding: chunked`. Not sure if it's worth to support HTTP/1.0 for streams.

**Comment by santosh0705** [comment]
tested in Docker v1.7 on CentOs 7 its working fine. I'll upgrade to 1.7

**Comment by LK4D4** [comment]
@santosh0705 Cool :)

**Comment by santosh0705** [comment]
```Transfer-Encoding: chunked``` only supported in HTTP/1.1 and its working fine. Only problem with Perl.
