### ISSUE TITLE
load fails with no messages, no images loaded from tar file

### ISSUE THREAD

**Issue by jl-montes** [docker/docker#14334]
After invoking the docker load command to load tar files, no images are loaded and no messages are displayed. Re-ran the same command with the -D option for debug, only saw the following message -->  'DEBU[0000] [stream] End of stdout'

Steps:
host ~ $ docker -D load  -i mon-influxdb.tar
DEBU[0000] [stream] End of stdout
host ~ $
host ~ $ docker -D load  -i mon-kafka.tar
DEBU[0000] [stream] End of stdout
host ~ $

Environment Details: CoreOS ver 647.0.0 running in a VMware VM
uname -a 
3.19.3 #2 SMP Thu Apr 9 01:47:33 UTC 2015 x86_64 Intel(R) Xeon(R) CPU E5-2697 v3 @ 2.60GHz GenuineIntel GNU/Linux

docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.3.3
Git commit (client): a8a31ef-dirty
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.3.3
Git commit (server): a8a31ef-dirty

**Comment by runcom** [comment]
@jl-montes do you have any chance of running the latest version (1.7.0) or a master build to see if this problem still persists? Also seems like you aren't using official bin `Git commit (server): a8a31ef-dirty` are you?

**Comment by jl-montes** [comment]
I'm just running the native version of Docker that is packaged with CoreOS v 647.0.0

**Comment by thaJeztah** [comment]
Is this still an issue? Has the CoreOS version of Docker already been updated to a more recent version of Docker?
