### ISSUE TITLE
Read-only host mounts with read-write sub-mounts

### ISSUE THREAD

**Issue by icecrime** [docker/docker#14337]
Here, `/tmp/` from the host is mounted read-only, but the sub-mounts have been propaged read-write.

```
root@vorpal:~# mkdir /tmp/danger
root@vorpal:~# mount -o bind /tmp/danger /tmp/danger
root@vorpal:~# docker run -ti -v /tmp:/tmp:ro ubuntu bash
root@fe243ca8f803:/# touch /tmp/x
touch: cannot touch '/tmp/x': Read-only file system
root@fe243ca8f803:/# touch /tmp/danger/x
root@fe243ca8f803:/# exit
root@vorpal:~# ls -l /tmp/danger/x 
-rw-r--r-- 1 root root 0 May 24 23:24 /tmp/danger/x
```

**Comment by visualphoenix** [comment]
can we get this fixed in 1.7.x?

**Comment by thaJeztah** [comment]
@icecrime A quick look at this, looks like this is the same as https://github.com/docker/docker/issues/10714, which was closed because "that's the way bind mounts work" https://github.com/docker/docker/issues/10714#issuecomment-83601721

**Comment by icecrime** [comment]
Indeed, that's the answer I got from @crosbymichael too... Closing this, thanks.
