### ISSUE TITLE
Move Log Read logic into daemon/logger/$(logger_name)

### ISSUE THREAD

**Issue by wlan0** [docker/docker#14331]
Currently, the read logic for each of the log drivers that support it are implemented in daemon/logs.go. As we add more log drivers that support reading, this will become unscalable and cumbersome. 

The Read logic should be implemented in the logging driver files and exposed out as a buffer through an interface to the daemon/logs.go endpoint.

**Comment by wlan0** [comment]
ping @cpuguy83 @LK4D4

**Comment by thaJeztah** [comment]
ping @cpuguy83 @LK4D4 wdyt?

**Comment by cpuguy83** [comment]
Closing, this is done now.
