### ISSUE TITLE
Config/HostConfig regressions

### ISSUE THREAD

**Issue by runcom** [docker/docker#14338]
Similar to #14318 and #14170. Some Config/HostConfig options suffer from a regression where previously (<1.7.0) it was possible to just pass a string in json and  be adapted to be a strings slice (old engine `GetenvList`) while now it isn't possible anymore cause we are directly decoding in `[]string`

`Dns` and `DnsSearch` are suffering the same issue (compose moves a single string to a list if there's only one element https://github.com/docker/compose/blob/77c939b256dbed699fdc4643114bea543208a660/compose/service.py#L570 so this could have been missed)
I'm fixing `Dns` and `DnsSearch` though, and I still haven't looked at all the options

/cc @aanand @calavera @LK4D4

**Comment by LK4D4** [comment]
@runcom Hehe, maybe nobody need it :)

**Comment by runcom** [comment]
@LK4D4 I thought about that and I've opened this before doing anything :)

**Comment by cpuguy83** [comment]
```
# git grep GetenvList | grep -v test                                                                                       ) ✗git:(7c8fca2
builder/job.go:176:		changes   = job.GetenvList("changes")
daemon/networkdriver/bridge/driver.go:709:		ports        = job.GetenvList("Ports")
engine/job.go:188:func (job *Job) GetenvList(key string) []string {
runconfig/config.go:61:	if PortSpecs := job.GetenvList("PortSpecs"); PortSpecs != nil {
runconfig/config.go:64:	if Env := job.GetenvList("Env"); Env != nil {
runconfig/config.go:67:	if Cmd := job.GetenvList("Cmd"); Cmd != nil {
runconfig/config.go:73:	if Entrypoint := job.GetenvList("Entrypoint"); Entrypoint != nil {
runconfig/exec.go:34:	cmd := job.GetenvList("Cmd")
runconfig/hostconfig.go:202:	hostConfig.SecurityOpt = job.GetenvList("SecurityOpt")
runconfig/hostconfig.go:203:	if Binds := job.GetenvList("Binds"); Binds != nil {
runconfig/hostconfig.go:206:	if Links := job.GetenvList("Links"); Links != nil {
runconfig/hostconfig.go:209:	if Dns := job.GetenvList("Dns"); Dns != nil {
runconfig/hostconfig.go:212:	if DnsSearch := job.GetenvList("DnsSearch"); DnsSearch != nil {
runconfig/hostconfig.go:215:	if ExtraHosts := job.GetenvList("ExtraHosts"); ExtraHosts != nil {
runconfig/hostconfig.go:218:	if VolumesFrom := job.GetenvList("VolumesFrom"); VolumesFrom != nil {
runconfig/hostconfig.go:221:	if CapAdd := job.GetenvList("CapAdd"); CapAdd != nil {
runconfig/hostconfig.go:224:	if CapDrop := job.GetenvList("CapDrop"); CapDrop != nil {
```

**Comment by cpuguy83** [comment]
Were we really expecting strings on anything other than cmd and entrypoint?

**Comment by LK4D4** [comment]
@cpuguy83 nope :/

**Comment by runcom** [comment]
is it that bad to just drop support for string for these args and just show a nice message instead of the "cannot unmarshall into []string" thingie? if these opts aren't though as strings then it's sort of a bug right? Or maybe just show a warning for now and remove the string parsing in 1.8.0

**Comment by runcom** [comment]
ping @icecrime

**Comment by aanand** [comment]
@runcom I'd argue that it needs to stick around for as long as the Docker daemon supports API version 1.18.

**Comment by runcom** [comment]
@aanand yes make sense

**Comment by cpuguy83** [comment]
But this was completely undocumented. API docs specifically say "a list of ..."

**Comment by calavera** [comment]
I'm going to remove this from 1.7.1, since we're still talking about it.

**Comment by thaJeztah** [comment]
Can we change this now that the deprecation policy is in place?

**Comment by runcom** [comment]
> Can we change this now that the deprecation policy is in place?

+1 on this, I'll make a PR to update the deprecation list and adapt code to accept strings till removal as per deprecation policy

**Comment by calavera** [comment]
This was fixed already, AFAIK. Closing.
