### ISSUE TITLE
Client and server don't have same version (client : 1.18, server: 1.17)

### ISSUE THREAD

**Issue by KidDavidacus** [docker/docker#14330]
I am installing docker on Centos 6.6 I was able to get all the steps going.

The last thing I am trying to do is run docker-compose, but when I attempted to run it it comes up with said error:

client and server don't have same version (client : 1.18, server: 1.17)

How can I resolve this issue?

**Comment by cpuguy83** [comment]
You either need to downgrade your client or upgrade your server.
Client version can't be newer than the server version.
