### ISSUE TITLE
Ubuntu Markdown spaces between hash and heading missing

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#14340]
http://docs.master.dockerproject.org/installation/ubuntulinux/

![image](https://cloud.githubusercontent.com/assets/1347209/8467066/87f09866-200e-11e5-8743-1770a7e265b1.png)

**Comment by ChanderG** [comment]
How often are the docs re-generated? If this is rendered from the docs folder on branch master, the markdown is fine here https://github.com/docker/docker/blob/master/docs/installation/ubuntulinux.md.

**Comment by moxiegirl** [comment]
@ChanderG In between releases, we release from the docs branch.  I have to cherry pick a change from master into release and push it live.
