### ISSUE TITLE
how can connect remote karaf jmx in contain

### ISSUE THREAD

**Issue by loveai88** [docker/docker#14346]
Hi ,I run a karaf in a contain,now I want to connect the karaf jmx on 
```
service:jmx:rmi:///jndi/rmi://HOST_IP:2099/karaf-root
```
I have use `-p 2099:1099` to public the contain port,but I can not connect it.
Who know how to connet it .
Thanks

docker version :```1.7.0, build 0baf609```
docker info:
```
Containers: 102
Images: 117
Storage Driver: devicemapper
 Pool Name: docker-253:0-6684678-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file:
 Metadata file:
 Data Space Used: 4.785 GB
 Data Space Total: 107.4 GB
 Data Space Available: 102.6 GB
 Metadata Space Used: 13.51 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.134 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.80-1.el6.elrepo.x86_64
Operating System: <unknown>
CPUs: 4
Total Memory: 31.46 GiB
Name: store40
ID: VAD6:HWJP:TJYY:HZJH:W7KW:GI5I:FLVE:4X6S:QZA4:WO35:BQZI:CB7H
WARNING: No swap limit support
```
uname -r :```3.10.80-1.el6.elrepo.x86_64```

**Comment by unclejack** [comment]
This isn't a Docker bug, this is a question which is more appropriate for 1) the forums: https://forums.docker.com/ 2) the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user 3) the #docker channel on Freenode.


This is an issue tracker for Docker bugs, features and pull requests. Please take this into account when opening an issue.

This isn't a Docker bug, this is a question which is more appropriate for
1) the forums: https://forums.docker.com/
2) the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user
3) the #docker channel on Freenode.

1) and 2) should be better for longer conversations.
