### ISSUE TITLE
System error: mountpoint for devices not found - faced while running container

### ISSUE THREAD

**Issue by amitkumarghatwal** [docker/docker#14353]
Hi All,

My set up is as below :
$ docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2 gccgo (GCC) 5.1.1 20150701
Git commit (client): f9978e8
OS/Arch (client): linux/ppc64le
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2 gccgo (GCC) 5.1.1 20150701
Git commit (server): f9978e8
OS/Arch (server): linux/ppc64le

$ lscpu
Architecture:          ppc64le
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Model:                 IBM pSeries (emulated by qemu)
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             64K
L1i cache:             32K
NUMA node0 CPU(s):     0,1

$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
ubuntu_utopic       14.10               3befbd1d67b7        3 hours ago         248.7 MB
ubuntucore          latest              8f92a47e67b7        11 weeks ago        211.6 MB

When i try to run docker images , i am facing below errors:
$ docker run --name test1 -it ubuntu_utopic:14.10 /bin/bash
time="2015-07-02T08:38:36-04:00" level=fatal msg="Error response from daemon: Cannot start container 2911f6ef3040bd2d1abc1a0f7ab31b94ae33c8649a62d7b814cea44a3287a4d2: [8] System error: mountpoint for devices not found"

Any pointers in above ?

Regards,
Amit

**Comment by LK4D4** [comment]
@amitkumarghatwal I think you have no devices cgroup mounted. Can you try to run `./contrib/check-config.sh` from our repo?

**Comment by amitkumarghatwal** [comment]
@LK4D4  can u tell me the commands for " no devices cgroup mounted "  ?
fyi
$ $ docker info
Containers: 2
Images: 2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 6
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.16.0-23-generic
Operating System: Ubuntu 14.10
CPUs: 2
Total Memory: 3.979 GiB
Name: pts00433-vm7
ID: SSTY:IX77:STJA:MTU3:45Z4:PBFY:FGZJ:FTLH:IYGY:QQP3:6DI4:4HWM
WARNING: No memory limit support
WARNING: No swap limit support

Regards,
Amit

**Comment by amitkumarghatwal** [comment]
@LK4D4 as requested , please see below 
$ ./contrib/check-config.sh
warning: /proc/config.gz does not exist, searching other paths for kernel config...
info: reading kernel config from /boot/config-3.16.0-23-generic ...

Generally Necessary:
- cgroup hierarchy: nonexistent??
    (see https://github.com/tianon/cgroupfs-mount)
- apparmor: enabled and tools installed
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MACVLAN: enabled
- CONFIG_VETH: enabled
- CONFIG_BRIDGE: enabled
- CONFIG_NF_NAT_IPV4: enabled
- CONFIG_IP_NF_FILTER: enabled
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled
- CONFIG_NF_NAT: enabled
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_MEMCG_SWAP: enabled
- CONFIG_RESOURCE_COUNTERS: enabled
- CONFIG_CGROUP_PERF: enabled
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: enabled
    - CONFIG_EXT4_FS_POSIX_ACL: enabled
    - CONFIG_EXT4_FS_SECURITY: enabled
  - "btrfs":
    - CONFIG_BTRFS_FS: enabled
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: enabled
    - CONFIG_DM_THIN_PROVISIONING: enabled
    - CONFIG_EXT4_FS: enabled
    - CONFIG_EXT4_FS_POSIX_ACL: enabled
    - CONFIG_EXT4_FS_SECURITY: enabled
  - "overlay":
    - CONFIG_OVERLAY_FS: missing
    - CONFIG_EXT4_FS_SECURITY: enabled
    - CONFIG_EXT4_FS_POSIX_ACL: enabled

I am not able to understand much in above part , please kindly point to probable resolution.

Regards,
Amit

**Comment by LK4D4** [comment]
@amitkumarghatwal Your cgroups isn't mounted as you can see in line:
```
cgroup hierarchy: nonexistent?? (see https://github.com/tianon/cgroupfs-mount)
```
https://github.com/tianon/cgroupfs-mount script can mount cgroups for you

**Comment by amitkumarghatwal** [comment]
@LK4D4 thanks for all ur inputs. see below the output which shows cgroups presence..
$ ./contrib/check-config.sh
warning: /proc/config.gz does not exist, searching other paths for kernel config...
info: reading kernel config from /boot/config-3.16.0-23-generic ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- apparmor: enabled and tools installed
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MACVLAN: enabled
- CONFIG_VETH: enabled
- CONFIG_BRIDGE: enabled
- CONFIG_NF_NAT_IPV4: enabled
- CONFIG_IP_NF_FILTER: enabled
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled
- CONFIG_NF_NAT: enabled
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_MEMCG_SWAP: enabled
- CONFIG_RESOURCE_COUNTERS: enabled
- CONFIG_CGROUP_PERF: enabled
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: enabled
    - CONFIG_EXT4_FS_POSIX_ACL: enabled
    - CONFIG_EXT4_FS_SECURITY: enabled
  - "btrfs":
    - CONFIG_BTRFS_FS: enabled
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: enabled
    - CONFIG_DM_THIN_PROVISIONING: enabled
    - CONFIG_EXT4_FS: enabled
    - CONFIG_EXT4_FS_POSIX_ACL: enabled
    - CONFIG_EXT4_FS_SECURITY: enabled
  - "overlay":
    - CONFIG_OVERLAY_FS: missing
    - CONFIG_EXT4_FS_SECURITY: enabled
    - CONFIG_EXT4_FS_POSIX_ACL: enabled

i followed below steps to resolve the issue
1. Had to manually comment out existing cgroups in /etc/fstab by logging as root. 
2. Using "https://github.com/tianon/cgroupfs-mount" , ran the mount script to manually mount cgroups. The unmount script wasn't able to remove existing cgroups so had to do step 1 above.
3. Restarted docker deamon.
4. Verified if cgroups existed using "./contrib/check-config.sh" in my docker source code folder.
5. Able to successfully run docker images to create containers.

Regards,
Amit
