### ISSUE TITLE
Remote API behaviour - Is this normal?

### ISSUE THREAD

**Issue by santosh0705** [docker/docker#14354]
I'm writing an event listener and faced problem with older version of docker so switched from Docker v1.4 to v1.7.

In previous version if connecting to socket and sending command ```GET /events HTTP/1.0\r\n\r\n``` I was getting the HTTP response immediately after sending the command but in v1.7 I have to wait till any event is triggered.

My question is is this the normal behaviour of the API or this is a bug?

Testing this in Perl and Python both had the same result.
Any clue?

**Comment by cpuguy83** [comment]
This is probably a bug introduced in 1.7

**Comment by cpuguy83** [comment]
Fix is in #14359

**Comment by santosh0705** [comment]
Wow so quick...
when v1.7.1 is scheduled to released?

**Comment by LK4D4** [comment]
@santosh0705 next tuesday
