### ISSUE TITLE
Proposal : restart policies "validations"

### ISSUE THREAD

**Issue by vdemeester** [docker/docker#14351]
As wrote in ``runconfig/parse_test.go`` (https://github.com/docker/docker/blob/master/runconfig/parse_test.go#L458 and https://github.com/docker/docker/blob/master/runconfig/parse_test.go#L472), it's currently possible to set invalid restart policies and the result is kinda weird :

* with ``always``: ``docker run --restart=always:1 …`` will not work as expected but ``docker run --restart=alwasy:1:1 …`` or even ``docker run --restart=always:a:b`` will.
* with ``on-failure``: ``docker run --restart=on-failure:5:anything`` will not fail *but* the value of ``on-failure`` will be ``0`` which is worse.

I'ld propose we do a little more validation on these so those invalid inputs will result in an error at run *or* at least make it that ``on-failure:5:1`` result the same as ``on-failure:5``.

What do you think ?

**Comment by LK4D4** [comment]
We definitely should do this. I think it's a bug.

**Comment by thaJeztah** [comment]
:+1: great suggestion

**Comment by coolljt0725** [comment]
Great suggestion, working on that :)
