### ISSUE TITLE
Proposal: --no-color option with `docker -d`

### ISSUE THREAD

**Issue by chiefy** [docker/docker#14358]
Currently we're using AWS CloudWatch logging and it's kind of annoying as the logs look like this:

`[34mINFO[0m[134448] GET /containers/json?all=1&filters={%22status%22:%5b%22restarting%22%5d}&limit=100`

I know I could work some magic and remove the color codes, but it'd be nice if `docker -d` had an option like `docker-compose`'s `--no-color` to provide stdout/stderr w/o color.

**Comment by LK4D4** [comment]
Makes sense

**Comment by phemmer** [comment]
On the subject, I also think the logging format needs to be consistent. Right now the output is radically different based on whether STDOUT is a TTY or not. Using color when connected to a TTY I can understand, but why change the format?

**Comment by LK4D4** [comment]
@phemmer we can ask @Sirupsen :)

**Comment by Sirupsen** [comment]
@phemmer that's the Logrus defaults for opinionated reasons. I like that format a lot when working locally, but it's not really meant for production usage where the non-coloured key/value is more appropriate.

**Comment by chiefy** [comment]
@Sirupsen :+1: logging out in JSON (or at least the option to) would be nice.

**Comment by Sirupsen** [comment]
Making the default the key-value pairs would probably be ideal. This is still easy to parse by humans. A custom formatter could also be written, but I don't think that's necessary right off the bat. In `/etc/default/docker` we could allow configuring to the JSON logger.

**Comment by vincentwoo** [comment]
@Sirupsen been a while on this one, any chance of getting this in?
