### ISSUE TITLE
Proxy within container only works with proxy ip, rather than hostname

### ISSUE THREAD

**Issue by pdxjohnny** [docker/docker#14356]
Description of problem:
When behind a corporate proxy, http://proxy.company.com:8080/, I can set the
proxy variables for the docker daemon on my host machine. However once in a
container, ubuntu:14.04, attempting to set the proxies with
```bash
export http_proxy="http://proxy.company.com:8080/"
export https_proxy="http://proxy.company.com:8080/"
export HTTP_PROXY="http://proxy.company.com:8080/"
export HTTPS_PROXY="http://proxy.company.com:8080/"
```
or when building a container with
```Dockerfile
ENV http_proxy 'http://proxy.company.com:8080'
ENV https_proxy 'http://proxy.company.com:8080'
ENV HTTP_PROXY 'http://proxy.company.com:8080'
ENV HTTPS_PROXY 'http://proxy.company.com:8080'
```
Does not work. This is using the --net=host option with docker run.
I could not figure out how to give the build access to the host network.

The trick I found was to ping proxy.company.com from my host and get the ip
then set the proxies from within my container like so.
```bash
ping proxy.company.com
PING proxy.company.com (12.34.567.898) 56(84) bytes of data.
^C

docker run --net=host -t -i ubuntu:14.04 /bin/bash

export http_proxy="http://12.34.567.898:8080/"
export https_proxy="http://12.34.567.898:8080/"
export HTTP_PROXY="http://12.34.567.898:8080/"
export HTTPS_PROXY="http://12.34.567.898:8080/"
```

`docker version`:
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64

`docker info`:
Containers: 11
Images: 26
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 48
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-55-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 4
Total Memory: 5.718 GiB
Name: Graphics
ID: TFMJ:I23E:WUXS:ZF5X:5NJ5:CVHX:F2JN:XUH5:X7GD:EGLU:4IXQ:UPRP
Http Proxy: http://proxy.company.com:8080/
Https Proxy: http://proxy.company.com:8080/
Username: pdxjohnny
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

`uname -a`:
Linux Graphics 3.13.0-55-generic #94-Ubuntu SMP Thu Jun 18 00:27:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
physical

How reproducible:
Every time

Steps to Reproduce:
1. Start container
2. Set proxies
3. apt-get / ping anything

Actual Results:
apt-get says:
Can't resolve hostname proxy.company.com
when updating

Expected Results / What would work best:
If it would resolve the hostname proxy.company.com and find the ip
of the proxy itself

Additional info:

**Comment by rasputnik** [comment]
Can you do DNS lookups in the container? That sounds likely to be your issue.

**Comment by cpuguy83** [comment]
Yeah, this sounds like a DNS problem, not a problem with Docker, especially Docker itself isn't really doing anything here.

Closing this for now since it really doesn't look like a Docker issue.
Feel free to ping on IRC or docker-user ML for help!
