### ISSUE TITLE
check error before response's status code in sockRequestRaw

### ISSUE THREAD

**Issue by runcom** [docker/docker#14362]
There are various places where a check to the response's status code from `sockRequestRaw` is done before checking its error returned eg https://github.com/docker/docker/blob/master/integration-cli/docker_api_containers_test.go#L493

(Also some calls lack of proper err checking eg https://github.com/docker/docker/blob/master/integration-cli/docker_api_containers_test.go#L1232)

**Comment by Tenk42** [comment]
#dibs

**Comment by Tenk42** [comment]
@runcom, I will clean in the same time some sockRequest.

**Comment by Gadal** [comment]
Pull's been merged.  Should this be closed?

**Comment by runcom** [comment]
definitively! thanks @Gadal
