### ISSUE TITLE
Unable to start docker version 1.8.0-dev, build 71f8ca3

### ISSUE THREAD

**Issue by aanm** [docker/docker#14368]
```bash
[aanm@localhost docker]$ sudo service docker restart
Redirecting to /bin/systemctl restart  docker.service
Job for docker.service failed. See "systemctl status docker.service" and "journalctl -xe" for details.
[aanm@localhost docker]$ systemctl status docker.service -l
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Qui 2015-07-02 23:16:12 WEST; 41s ago
     Docs: http://docs.docker.com
  Process: 17737 ExecStart=/usr/bin/docker -d $OPTIONS $DOCKER_STORAGE_OPTIONS $DOCKER_NETWORK_OPTIONS $INSECURE_REGISTRY (code=exited, status=1/FAILURE)
 Main PID: 17737 (code=exited, status=1/FAILURE)

Jul 02 23:16:12 localhost.localdomain systemd[1]: Starting Docker Application Container Engine...
Jul 02 23:16:12 localhost.localdomain docker[17737]: time="2015-07-02T23:16:12.806317973+01:00" level=fatal msg="Error starting daemon: error initializing graphdriver: devicemapper storage driver cannot reliably be used with a statically linked docker binary: please either pick a different storage driver, install a dynamically linked docker binary, or force this unreliable setup anyway by specifying --storage-driver=devicemapper"
Jul 02 23:16:12 localhost.localdomain systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Jul 02 23:16:12 localhost.localdomain systemd[1]: Failed to start Docker Application Container Engine.
Jul 02 23:16:12 localhost.localdomain systemd[1]: Unit docker.service entered failed state.
Jul 02 23:16:12 localhost.localdomain systemd[1]: docker.service failed.
```
```bash
$ uname -a
Linux localhost.localdomain 4.0.6-300.fc22.x86_64 #1 SMP Tue Jun 23 13:58:53 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by phemmer** [comment]
This line has the important info: 

> Jul 02 23:16:12 localhost.localdomain docker[17737]: time="2015-07-02T23:16:12.806317973+01:00" level=fatal msg="Error starting daemon: error initializing graphdriver: devicemapper storage driver cannot reliably be used with a statically linked docker binary: please either pick a different storage driver, install a dynamically linked docker binary, or force this unreliable setup anyway by specifying --storage-driver=devicemapper"


See https://github.com/docker/docker/pull/14292#issuecomment-117763368

**Comment by calavera** [comment]
I feel very ashamed of my comment, but that's a feature :pensive: Please refer to that log and make the decision that works better in your case. Closing this issue.

**Comment by aanm** [comment]
@calavera The same way you help the user how to force the setup using "--storage-driver=devicemapper" I think you should also provide more info to which are the different storage drivers and how to install a dynamic linked docker binary, or at least build it.

**Comment by calavera** [comment]
> or at least build it

agreed, the idea is to provide a dynamic linked binary soon, but we cannot work on everything at the same time and we need to prioritize. Feel free to help, the release script is in https://github.com/docker/docker/blob/master/hack/release.sh

**Comment by aanm** [comment]
@calavera Ah, roger that. I thought #14292 was the last close for this problem

**Comment by calavera** [comment]
@aanm do you mind to post the output of `ls -la /var/lib/docker` ? I'm considering another theory and you might have been affected by a very bad resolved issue.

**Comment by aanm** [comment]
@calavera Okay, so I was working with docker right now, with 1.6.2 so I assume you wanted a "fresh" directory. I did `sudo mv /var/lib/docker /var/lib/docker.bak && sudo mkdir /var/lib/docker && sudo chmod 755 /var/lib/docker`.
Fortunately I still had the binary that I'd build, the 71f8ca3, so I stop the service, change the binary (backed the /var/lib/directory) and restart the service and it worked!
To make sure I stopped the service again, deleted did `sudo rm -fr /var/lib/docker && sudo mv /var/lib/docker.bak /var/lib/docker` and when I tried to restart the service it failed! Do you still want the output of this faulty directory?

**Comment by calavera** [comment]
yes please

**Comment by aanm** [comment]
```bash
#OLD
[aanm@localhost ~]$ sudo ls -la /var/lib/docker
total 92
drwxr-xr-x.  10 root root  4096 Jul  6 10:43 .
drwxr-xr-x.  59 root root  4096 Jul  6 19:58 ..
drwx------.  11 root root  4096 Jul  6 10:43 containers
drwx------.   5 root root  4096 Jul  2 21:58 devicemapper
drwx------. 207 root root 28672 Jul  5 08:47 graph
drwx------.   2 root root  4096 Jul  6 09:55 init
-rw-r--r--.   1 root root 11264 Jul  6 10:43 linkgraph.db
-rw-------.   1 root root  1901 Jul  5 08:46 repositories-devicemapper
drwx------.   2 root root  4096 Jul  5 08:46 tmp
drwx------.   2 root root  4096 Jul  2 21:58 trust
drwx------.   3 root root  4096 Jul  2 22:08 vfs
drwx------. 105 root root 12288 Jul  6 10:08 volumes

#NEW
[aanm@localhost ~]$ sudo ls -la /var/lib/docker
total 48
drwxr-xr-x.  9 root root 4096 Jul  6 20:04 .
drwxr-xr-x. 60 root root 4096 Jul  6 20:03 ..
drwx------.  2 root root 4096 Jul  6 20:04 containers
drwx------.  2 root root 4096 Jul  6 20:04 graph
drwx------.  2 root root 4096 Jul  6 20:04 init
-rw-r--r--.  1 root root 5120 Jul  6 20:04 linkgraph.db                                                                                                                                                                                       
drwxr-xr-x.  2 root root 4096 Jul  6 20:04 overlay                                                                                                                                                                                            
-rw-------.  1 root root   19 Jul  6 20:04 repositories-overlay                                                                                                                                                                               
drwx------.  2 root root 4096 Jul  6 20:04 tmp                                                                                                                                                                                                
drwx------.  2 root root 4096 Jul  6 20:04 trust                                                                                                                                                                                              
drwx------.  2 root root 4096 Jul  6 20:04 volumes
```

**Comment by calavera** [comment]
awesome, thanks for the info @aanm. This confirms my suspicion, you probably weren't using devicemapper with your previous version of docker, but a bad logic in the selection algorithm assigned you that driver only because you had the directory already created.

**Comment by aanm** [comment]
@calavera Thanks for taking a look at this ;-)

**Comment by vikassinghal05** [comment]
Hi I am also getting the same error but...Please help to resolve the issue : 

 [vagrant@host1 ~]$ sudo service docker start
Redirecting to /bin/systemctl start  docker.service
Job for docker.service failed. See 'systemctl status docker.service' and 'journalctl -xn' for details.
