### ISSUE TITLE
Update Registry documentation

### ISSUE THREAD

**Issue by metalivedev** [docker/docker#1438]
On http://docs.docker.io/en/latest/api/registry_index_spec/

* update/correct the CLI commands
* add "swimlane" sequence diagrams for push, pull, and delete
* show user-space examples of the same commands for self-hosted registries
* make sure we use the same terms here and in the API docs for Index and Registry

**Comment by jfrazelle** [comment]
@jlhawn @steeve do you think we can move this to the distribution repo or the spec

**Comment by dmp42** [comment]
@jfrazelle sure we can move the issue. Who do you think should work on it (Fred?)?

**Comment by jfrazelle** [comment]
Its up to you just trying to triage things :D

**Comment by dmp42** [comment]
Then let's close this :)
Updating registry v1 documentation is absolutely low-priority and probably not going to happen unless someone from the docs team pick-it up.
