### ISSUE TITLE
Proposal: Add LCOPY/LUNCOPY Dockerfile commands

### ISSUE THREAD

**Issue by greaber** [docker/docker#14387]
## Goal

This proposal aims to solve three problems.  1. Docker often sends unused build context, unnecessarily consuming network bandwidth.  2. The COPY and ADD commands do not make it easy to pick and choose what to add to a docker image.  3. Docker doesn't allow sending build context that is located outside of a fixed directory (which must contain the Dockerfile, unless the relation of the Dockerfile to its build context is only specified at the command line, using docker build -f).

## Current workarounds and other proposed solutions

The following list is quite incomplete.

 - Dockerignore is often used to address 1 and 2, but it has limitations such as not being per-Dockerfile, using an impoverished pattern language, making things less explicit by removing them from the Dockerfile, and not enforcing the constraint that one can't send unnecessary context.

 - Issue #12886 includes useful discussion and other partial solutions, including (in the comments) a proposal to have docker figure out what to send based on what COPY and ADD commands are in the Dockerfile, which inspired the present proposal.

- Issue #6094 (among others) discusses adding support for following symlinks in source paths.  Much of the motivation seems to be for cases that are handled by the present proposal.  While there are possible security concerns about both the symlinks proposal and the present one, the present proposal is safer since if context from outside the directory the Dockerfile is in will be sent, that is obvious from the Dockerfile; one doesn't have to search the whole directory tree for errant symlinks.

## Scope of solution

The solution to 1 is importantly limited in that the proposal includes no provision for caching on the server, so a lot of unnecessary information can still be sent if it is used across builds.  It would be nice if a future enhancement to docker could address this remaining problem.

## Proposal

Two new Dockerfile commands will be added: LCOPY and LUNCOPY.  LCOPY could largely supersede COPY.

1. LCOPY works similarly to COPY, but paths can reach out of the directory the Dockerfile is in and are specified using a rich pattern language (the syntax we wish dockerignore had used).  Here is a first pass at how it might work:
 - Patterns have two parts.  The first part consists of any number of '../' components, which determine the base directory relative to which strings matching the second part of the pattern are interpreted.  (n '../'s means take the nth parent of the file the Dockerfile is in to be the base.)  To avoid surprising people, the first part could also be allowed to consist of '/' or './', which would have the same effect as ''.  
 - The rest of the pattern is matched against paths relative to the base directory (not including paths that involve the special '.' and '..' directories) in the following way: ? matches any non-slash character, * matches any sequence of non-slash characters; ** matches any sequence of characters.
 - Directories (but not plain files) can optionally be referred to with paths with a trailing slash.

2. LUNCOPY undoes the effect of previous LCOPY, COPY, and ADD commands (similarly to ! patterns in .dockerignore).  It uses the same pattern language as LCOPY.

3. If a Dockerfile contains any LCOPY or LUNCOPY commands, no context is sent by default.  The only context that will be sent is that necessary to build the image.  Moreover, it is an error if the base image contains ONBUILD triggers.

## Caveats

- The proposal proceeds on the assumption that ONBUILD triggers are not very important, or even a misfeature.  If it is thought important to fully support them, one method would be to add LSEND and LUNSEND commands that work like LCOPY and LUNCOPY but determine a build context for ONBUILD triggers rather than adding or removing anything from the image.

- The concrete proposal regarding pattern syntax will not be easy to extend without breaking backwards compatibility.  Yet it might be desirable to extend it, for instance to include character ranges

- I probably can't implement this even if there is uptake.

- One possible advantage of dockerignore over this proposal is that it can by more DRY when there are multiple Dockerfiles.  However,
  + The proposal doesn't do away with dockerignore (which couldn't be done without breaking compatibility).
  + The problem of repeated content in Dockerfiles really needs to be solved at some other level since it arises for many things, not just LCOPY/LUNCOPY.

- Maybe RCOPY/RUNCOPY would be better names than LCOPY/LUNCOPY?

**Comment by thaJeztah** [comment]
Thanks for writing this up. Some initial thoughts on this;

> LCOPY works similarly to COPY, but *paths can reach out of the directory the Dockerfile is in* and are specified using a rich pattern language

I don't think this is something that can be accepted. This effectively allows a Dockerfile to have access to *any* file on the hosts system, and is a severe security risk. The main reason for having to explicitly specify a build context is to prevent this.

> Two new Dockerfile commands will be added: LCOPY and LUNCOPY.

At this moment, we don't want to add new commands to the Dockerfile syntax. There are plans to completely refactor the way Dockerfiles are handled, by moving the "builder" out of the daemon, and making it part of the "docker client"; see this issue: https://github.com/docker/docker/issues/14298

Moving the builder out of the daemon will give a lot more flexibility, including being able to implement alternatives to Dockerfiles and (giving the client full control over the build process), more selectively send files to the daemon, in stead of always sending *all* files that are inside the build-context.

Please read https://github.com/docker/docker/issues/14298 and the [roadmap](https://github.com/docker/docker/blob/master/ROADMAP.md) for more information.


Because of those reasons, I'm leaning on closing this (at least until the builder refactor has completed), but I'll defer to @icecrime and @jlhawn for additional thoughts.

Again, thanks for opening this proposal, even if it may not be accepted, thinking along to improve the project is really appreciated!

**Comment by greaber** [comment]
Regarding the first point, I'm not that clear on what kinds of attack scenarios are of most concern, but it seems like there could be ways to mitigate the risk such as not letting the LCOPY commands reach out of the directory passed to docker build (so, in particular, if the Dockerfile were not in that directory it wouldn't be able to access anything using LCOPY).  The second point is quite fair, and I don't have any problem with you closing.

**Comment by thaJeztah** [comment]
Wrt the first point, a short example;

    docker build -f /path/to/Dockerfile /path/to/build-context/

In this case, the build-context is `/path/to/build-context/`, and all `COPY` / `ADD` actions in the Dockerfile are relative to that directory, i.e., `COPY foo /` will copy `/path/to/build-context/foo` to `/foo` in the container.

Allowing `LCOPY ../foo /` would then imply trying to copy `/path/to/foo`, which is outside of the build-context, so should not be allowed.

**Comment by greaber** [comment]
That's actually blocked by the restriction mooted in my last message.  (It falls under the particular case I highlighted.)  I think this was unclear because I was not clear that the LCOPY and LUNCOPY source paths are supposed to be relative to the directory the Dockerfile is in, not the directory passed to the build command.  (Otherwise, the mooted restriction  would make the '../' paths totally useless.)

**Comment by jlhawn** [comment]
Thanks for the great writeup @greaber!

Unfortunately, [we will probably not be making any more changes/additions to the Dockerfile syntax](https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax). Despite that though, I've got a few comments/questions in relation to the client-side builder project that I'm working on:

> Docker often sends unused build context, unnecessarily consuming network bandwidth.

I know the pain :disappointed: and this is quite an annoying problem for many people. It's especially bothersome when your Docker client and daemon are on separate machines. Not only does it use unnecessary bandwidth but it can also be painfully slow (even if most or all build steps are cached). For example, when I am developing docker the `make` commands will run a `docker build` which needs to upload 56MB+ for the build context and this takes about 3 seconds on my machine.

The immediate benefit of a client-side builder is that the context does not have to be bundled up and  transferred at all; files and directories are only sent when they need to be sent for a COPY step.

> The COPY and ADD commands do not make it easy to pick and choose what to add to a docker image.

Ignoring the `ADD` command, can you be more specific about this statement? Do you mean in handling files/directories to ignore? would optional flags to the COPY command help? Something like:

```
COPY --ignore=foo . /path/in/container
```

---

I also wonder why you chose to have an `L` at the beginning of these command names. Does the `L` have a particular meaning? Same question with the `R` proposal.

---

> LUNCOPY undoes the effect of previous LCOPY, COPY, and ADD commands

So it removes files? This could be done with `RUN rm <filename>` or `RUN rm -rf <dirname>` but the caveat there is that the `rm` command must exist in the container which is generally a safe assumptions but some minimal image builds wouldn't have this luxury. Also, the files/directories would still exist in the hidden ancestor layers of the image so this wouldn't actually make your image smaller.

That being said, there are a lot of use cases for this. Typically this needs comes up when setting up a particular dev environment during a build, copying source code into the container, and compiling it to have the final artifact. You now no longer need all of the tools needed to compile your code, not to mention the source code itself, but they're still there essentially bloating your Docker image. I'm more of a fan of the "nested" build approach for this use case: begin a new build where the context is the rootfs of the previous build. You can then copy only the artifacts you want into the final image, without all of the bloat. I'm working on adding this to my experimental client-side builder.

**Comment by greaber** [comment]
Hi, @jlhawn, your client-side builder idea sounds cool.  I think it could solve most of the problems people are currently having surrounding big build contexts.  But a remote builder will always have advantages in certain settings like not requiring local Linux and not requiring downloading base images, right?

> So it removes files? This could be done with RUN rm <filename> or RUN rm -rf <dirname>

LUNCOPY is supposed to avoid sending stuff over the network in the first place.  Now I realize that there is a problem with this behavior given that Docker is supposed to build intermediate images for **every** Dockerfile command.  I actually think it would be nice if the Dockerfile gave us more control over intermediate image building, but short of that there could be a special exception for sequences of LCOPYs and LUNCOPYs, or the syntax could be changed so that what is a sequence of LCOPYs and LUNCOPYs in the current syntax could be packed into one long Dockerfile command.

I agree that "nested" builds are a very elegant approach for the the scenario where you need to build a bunch of stuff but don't need the build tools in the final container!

Where I'm coming from with my proposal is that a Dockerfile in its native environment (i.e., some directory in your source repo) should ideally contain all the instructions necessary to build the image it is a recipe for.  For that to work, you need a reasonably expressive language for saying what should and should not be copied into the container, and it also makes sense for source-paths to be anchored to the directory the Dockerfile is in, not to the "build context" directory passed to docker build.  (That directory would ideally not need to be specified at all, though there are security concerns with having the default behavior be that Dockerfiles can access any file.)

If you don't care about having all the instructions necessary to build the image in the Dockerfile then you can just have a script that copies all the files you want to add into the right places in an empty directory, put "COPY <that directory> /" in your Dockerfile, and run "docker build -f <your Dockerfile> <that directory>".

The "L" and "R" were for "local" and "remote", but I'm not too proud of the names.

The --ignore syntax, assuming you can use rich patterns in both the --ignore arguments, and the main source path pattern arguments, would be equivalent in power to a single LCOPY followed by a single LUNCOPY, where the LCOPY and LUNCOPY have the same target path.  If you were going to implement something like LCOPY/LUNCOPY but wanted to keep to the one intermediate image per command paradigm, a better alternative, IMO, would be to just have a single new command but require the source path pattern arguments to be prefaced with "+" or "-" to specify whether they were being copied or uncopied.

Anyway, feel free to close this issue now.  I'm looking forward to all the developments you guys have planned!

**Comment by thaJeztah** [comment]
I'll close this proposal, but feel free to comment / discuss here after it's closed.

Thanks again for your proposal and thinking, @greaber, be sure to subscribe to the other issues wrt the builder, so that you can test (and provide feedback) once it arrives. I suspect them to be released as experimental features first, which gives more room for testing and feedback. :+1:
