### ISSUE TITLE
docker 1.7 not starting:  [graphdriver] prior storage driver "aufs" failed

### ISSUE THREAD

**Issue by andibachmann** [docker/docker#14405]
Since the upgrade to version 1.7 docker does not start anymore at boot.
The error message in `/var/log/upstart/docker.log` is 

    /var/run/docker.sock is up
    INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
    ERRO[0000] [graphdriver] prior storage driver "aufs" failed: backing file system is unsupported for this graph driver 
    FATA[0000] Error starting daemon: error initializing graphdriver: backing file system is unsupported for this graph driver 

Other system info:
* os: ubuntu 14.04 LTS, 
* docker installed via

        wget -q0- https://get.docker.com/ | sh

* docker version `docker -v`:

        Docker version 1.7.0, build 0baf609

**Comment by thaJeztah** [comment]
@andibachmann the "backing file system is unsupported for this graph driver" message indicates that you're trying to run docker (the aufs graph) on a filesystem that is known to cause problems. e.g. you cannot run aufs on top of another layered / copy-on-write filesystem (btrfs, for example).

In case of aufs, the (known) incompatible filesystems are "btrfs" and "aufs", which can be seen here: [/daemon/graphdriver/aufs/aufs.go#L48](https://github.com/docker/docker/blob/e69df2589c1220217054abdc6a361b55990b3c0b/daemon/graphdriver/aufs/aufs.go#L48)

**Comment by andibachmann** [comment]
Providing more info:

    $ docker version
    Client version: 1.7.0
    Client API version: 1.19
    Go version (client): go1.4.2
    Git commit (client): 0baf609
    OS/Arch (client): linux/amd64

    $ docker info
    Cannot connect to the Docker daemon. Is 'docker -d' running on this host?

    $ uname -a
    Linux ls083 3.13.0-55-generic #94-Ubuntu SMP Thu Jun 18 00:27:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Procedures to start `docker`:

    $ sudo service docker start

Error messages as in my initial comment.

    $  sudo docker -d
    INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
    ERRO[0000] [graphdriver] prior storage driver "aufs" failed: backing file system is unsupported for this graph driver 
    FATA[0000] Error starting daemon: error initializing graphdriver: backing file system is unsupported for this graph driver

**Comment by unclejack** [comment]
@andibachmann What file system is /var/lib/docker on? Can you provide the output of `mount`, please?

**Comment by andibachmann** [comment]
@thaJeztah : Ooops! I'm running on `btrfs`!

    $ df -T
    Filesystem     Type     1K-blocks     Used Available Use% Mounted on
    /dev/sda1      btrfs    153600000 43613716 108387948  29% /
    none           tmpfs            4        0         4   0% /sys/fs/cgroup
    udev           devtmpfs   3924252       12   3924240   1% /dev
    tmpfs          tmpfs       787044     1260    785784   1% /run
    none           tmpfs         5120        0      5120   0% /run/lock
    none           tmpfs      3935204      432   3934772   1% /run/shm
    none           tmpfs       102400       28    102372   1% /run/user
    /dev/sda1      btrfs    153600000 43613716 108387948  29% /home

I used to experiment with `btrfs` and forget about it, when I installed my current env half a year ago.

However, the previous version of `docker` where running smoothely, it's only after the upgrade
to version 1.7 (1 week ago).

Can I hope for relief, i.e. is this going to be supported?

**Comment by andibachmann** [comment]
@unclejack 

    $ mount
    /dev/sda1 on / type btrfs (rw,subvol=@)
    proc on /proc type proc (rw,noexec,nosuid,nodev)
    sysfs on /sys type sysfs (rw,noexec,nosuid,nodev)
    none on /sys/fs/cgroup type tmpfs (rw)
    none on /sys/fs/fuse/connections type fusectl (rw)
    none on /sys/kernel/debug type debugfs (rw)
    none on /sys/kernel/security type securityfs (rw)
    udev on /dev type devtmpfs (rw,mode=0755)
    devpts on /dev/pts type devpts (rw,noexec,nosuid,gid=5,mode=0620)
    tmpfs on /run type tmpfs (rw,noexec,nosuid,size=10%,mode=0755)
    none on /run/lock type tmpfs (rw,noexec,nosuid,nodev,size=5242880)
    none on /run/shm type tmpfs (rw,nosuid,nodev)
    none on /run/user type tmpfs (rw,noexec,nosuid,nodev,size=104857600,mode=0755)
    none on /sys/fs/pstore type pstore (rw)
    cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
    cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
    /dev/sda1 on /home type btrfs (rw,subvol=@home)
    systemd on /sys/fs/cgroup/systemd type cgroup (rw,noexec,nosuid,nodev,none,name=systemd)
    gvfsd-fuse on /run/user/3190/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,user=bachmann)

**Comment by unclejack** [comment]
@andibachmann You've upgraded from a very old version of Docker to Docker 1.7. Your /var/lib/docker folder is on btrfs. aufs isn't meant to be used on btrfs. We've seen aufs+btrfs lead to data corruption and many other problems (interrupted builds, missing files, etc).

I'd suggest that you back up your important data and then wipe out /var/lib/docker. If you've used aufs on top of btrfs in the past, your Docker images might have missing or corrupted files.

The btrfs storage driver should be used on btrfs, not aufs.

Please keep in mind that problems have been reported against kernel 3.13 on Ubuntu 14.04. Should you really want to keep your images, keep using aufs or both, you can set up a separate partition at /var/lib/docker using ext4 and (optionally) migrate your existing images.

**Comment by andibachmann** [comment]
@unclejack Do I understand you correctly that my `docker` setup was mixing file system and storage drivers (and the misconfiguration resulted from an incorrect upgrade)? I.e., I just managed to start docker using

    $ docker -d -s btrfs

Anyway, I'll throw away my current docker setup and containers (`rm -rf /var/lib/docker`).
But, before starting again, do I have to change my file system or will everything be OK?

**Comment by cpuguy83** [comment]
@andibachmann Not quite.
Docker does not ever create btrfs partitions, so somewhere along the line /var/lib/docker was converted to a btrfs partition.

**Comment by andibachmann** [comment]
@cpuguy83 hmmm, but `/var/lib/docker` is just a ordinary folder in my `/` btrfs file system. I noted
that there are two subfolders `aufs` and `btrfs` accomapanied with `repositories-aufs` and `repositories-btrfs`. Looking at these json-files, I see that my 'latest' stuff is `repositories-btrfs` and
the 1 year old `repositories-aufs` contains my very first steps with docker.

On explanation is that last year when I started with docker I installed it using `apt-get install docker`. The version of this first docker installation was probably the usual 3 minor version numbers behind the official release. I played around with docker and then some more important tasks came by and docker slept until May this year.
With new spirits I restarted from scratch and installed the latest version of docker  (~1.6.2 ).
Everything work liked a charm (I and the new docker-bin didn't see the old images, but I didn't care anyway).
Then after the update to 1.7  docker seems to have changed a bit the backend storage driver setup and it got confused with old 'aufs' stuff.

Does that make sense?

**Comment by cpuguy83** [comment]
@andibachmann ah yes, it does. In 1.7 we went from a straight priority list for the drivers to "check if there is already data for a driver and use that" if no specific graphdriver is selected in the daemon opts.
In the case where it's ambiguous (ie, a btrfs dir and an aufs dir), then it bails out.

**Comment by andibachmann** [comment]
OK. I just removed the subfolder `aufs` and the file `repositories-aufs` and then I issued a

    service docker start

it works again!

Thank you!

**Comment by moylop260** [comment]
@andibachmann 
:+1:

**Comment by joewired** [comment]
:+1:

**Comment by pablormier** [comment]
@andibachmann same problem here, your solution worked flawlessly. Thanks!

**Comment by ojhaujjwal** [comment]
same problem and removing aufs was the trick like you said. Thanks guys!

**Comment by tobegit3hub** [comment]
It works for me and thanks very much.

**Comment by hobrom** [comment]
same problem, same solution - thx!
