### ISSUE TITLE
Add Group Metatag to RPM Build

### ISSUE THREAD

**Issue by ediri** [docker/docker#14404]
This is really a small issue and possible quite quick to fix! 

Can a contributor just quickly add to the 

https://github.com/docker/docker/blob/master/hack/make/.build-rpm/docker-engine.spec

file following line:
```
Group : Tools/Docker
```

Because currently it shows only Unspecified in in our company we rely on this tag for deployment purpose.

Cheers!

**Comment by thaJeztah** [comment]
ping @jfrazelle for RPMs

**Comment by jfrazelle** [comment]
anyone can submit a PR, even you :)

**Comment by jfrazelle** [comment]
ill do it if no one else does in a few days

**Comment by Evalle** [comment]
#dibs

**Comment by thaJeztah** [comment]
@jfrazelle I pinged you because wanted to check with you first if you agreed on adding this. Happy to see @Evalle picked this up (yay!)
