### ISSUE TITLE
How my proccess catch User-defined signal with docker kill ?

### ISSUE THREAD

**Issue by ZhiqinYang** [docker/docker#14400]
i used docker kill -s TERM , my proccess can't catch it , my proccess in docker pid is 1.how can i do it ??

**Comment by cpuguy83** [comment]
This highly depends on what's running.
But docker does not change how signal handlers work/
Sometimes when a process is run as pid1 it's default signal handlers are ignored, so you may need to setup explicit handlers for the signals you want to listen for.
