### ISSUE TITLE
x509 warning

### ISSUE THREAD

**Issue by Ethaan** [docker/docker#14408]
So im facing this issue and dont realy know how to solve it.

```x509: certificate is valid for 127.0.0.1, 10.0.2.15, not 192.168.59.103```

**Comment by cpuguy83** [comment]
Hi, this is not a docker issue, it is an issue with your SSL certificates.
If you are using docker-machine, see https://github.com/docker/machine/issues/531

Closing since this isn't a Docker issue.

**Comment by Ethaan** [comment]
Hi i wont reopen this issue, but it seems like im facing some weird issue with my repos, here is the SO question, can you take a quick look and tell me where i can open a new issue for the hub?

http://stackoverflow.com/questions/31252664/docker-pull-repositoryname-dont-work-cant-see-public-repos/31253822?noredirect=1#comment50505077_31253822
