### ISSUE TITLE
No event emitted on container rename

### ISSUE THREAD

**Issue by kgutwin** [docker/docker#14407]
Service discovery tools such as [dnsdock](https://github.com/tonistiigi/dnsdock) rely on container events to remain in sync with container metadata. However, the `POST /containers/(id)/rename` API call does not generate any events, so a `docker rename` command will not notify the service discovery tool to update its metadata cache. See tonistiigi/dnsdock#22.

**Comment by runcom** [comment]
on it

**Comment by duglin** [comment]
@runcom https://github.com/docker/docker/blob/master/daemon/rename.go#L43
I think it was already fixed.

**Comment by runcom** [comment]
@duglin nope it isn't working because the container remains locked while LogEvent is  fired and getContainer in api isn't working, I've just made a fix, will post pr soon

**Comment by duglin** [comment]
@runcom now you have me really curious to know why https://github.com/docker/docker/blob/master/integration-cli/docker_cli_events_test.go#L720 doesn't seem to do its job   :-)

**Comment by runcom** [comment]
@duglin as I wrote cause it filters with new name but I'm still looking :smile: a simple failing test is `docker events` and rename a container and you won't see any events

**Comment by duglin** [comment]
weird - I do see an event when I tested it just now.
```
2015-07-06T06:35:28.000000000-07:00 bf71805206b333209678a1614fa36bbeb2549d39d3494d2ff7d259b1fbf74086: (from ubuntu) rename
```

**Comment by runcom** [comment]
@duglin yeah weird cause I don't see it...

**Comment by duglin** [comment]
@kgutwin what version of Docker are you using?

**Comment by kgutwin** [comment]
```
$ docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): darwin/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

And a repro log:

```
$ docker events &
[1] 51660
$ docker run -d --name one httpd
3490e228f1b261cb437f6966bafdb9e9f0930cd1259a9468abf15263f3768351
2015-07-06T10:54:16.000000000-04:00 3490e228f1b261cb437f6966bafdb9e9f0930cd1259a9468abf15263f3768351: (from httpd) create
2015-07-06T10:54:16.000000000-04:00 3490e228f1b261cb437f6966bafdb9e9f0930cd1259a9468abf15263f3768351: (from httpd) start
$ docker rename one two
$ docker stop two
2015-07-06T10:54:37.000000000-04:00 3490e228f1b261cb437f6966bafdb9e9f0930cd1259a9468abf15263f3768351: (from httpd) die
2015-07-06T10:54:38.000000000-04:00 3490e228f1b261cb437f6966bafdb9e9f0930cd1259a9468abf15263f3768351: (from httpd) stop
two
$ docker rm two
two
2015-07-06T10:54:41.000000000-04:00 3490e228f1b261cb437f6966bafdb9e9f0930cd1259a9468abf15263f3768351: (from httpd) destroy
```

**Comment by duglin** [comment]
From looking at the code, I don't see the rename event code in v1.7.0 but I do see it in 'master'.  Can you try on the latest to see if that does indeed fix it for you?

**Comment by kgutwin** [comment]
OK, I installed experimental on an EC2 instance and was able to see the rename event. Version information:
```
Client:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   71f8ca3
 Built:        Thu Jul  2 20:43:59 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   71f8ca3
 Built:        Thu Jul  2 20:43:59 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

```

**Comment by runcom** [comment]
@kgutwin thanks! This issue can be closed then

**Comment by kgutwin** [comment]
Could you at least add the `rename` event to the API docs?

**Comment by runcom** [comment]
@kgutwin sure!

**Comment by duglin** [comment]
See PR #14411
