### ISSUE TITLE
Docker "Advanced Networking" Docs seem to be messed up.

### ISSUE THREAD

**Issue by hayderimran7** [docker/docker#14416]
The link https://docs.docker.com/v1.2/articles/networking/ shows text wrapped up and no images rendered. I have tried opening on all browsers and on/off my vpn but same result. 
[Here is the screenshot ](http://i.imgur.com/jxayBbT.png?1) of browser window. If someone else can verify, thats a valid bug then )

**Comment by cpuguy83** [comment]
ping @moxiegirl

**Comment by moxiegirl** [comment]
Hi @hayderimran7 we are only supporting back to version 1.4. of the documentation .  So, 1.2 is beyond the scope of our support.   Maybe you can share why you are still on 1.2 and we can revisit our policy.

**Comment by hayderimran7** [comment]
@moxiegirl thanks for clarifying the version. I was directed from an old pull request. Closing it down.
