### ISSUE TITLE
Allow referencing self when using multiple FROM

### ISSUE THREAD

**Issue by moander** [docker/docker#14412]
```dockerfile
FROM php
RUN echo php

FROM ubuntu
RUN echo ubuntu

# Reference previous image in file
FROM .
RUN echo my base is ubuntu

# Reference a specific image in file
FROM .1
RUN echo my base is php
```

**Comment by vdemeester** [comment]
@moander Using multiple ``FROM`` is not really a feature but a bug (oh well, the limit is tight and there is few use cases for multiple ``FROM`` in a ``Dockerfile``). I'm not sure this would be a good idea ; Could you elaborate more on the use case you think of ?

Note that :
1. There is discussion to remove support for multiple ``FROM`` : https://github.com/docker/docker/issues/13026
2. ``Dockerfile`` changes are frozen for now : https://github.com/docker/docker/blob/master/ROADMAP.md#2-frozen-features
