### ISSUE TITLE
Dangling link in run.md

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#14418]
YOu have a dangling link in line 80 of docs/reference/commandline/run.md:

    The `docker run` command can be used in combination with `docker commit` to
    [*change the command that a container runs*](#commit-an-existing-container).

This should probably point to docs/reference/commandline/commit.md,
but I'm not sure exactly how that link should look (there didn't seem
to be any examples in the existing run.md document).

Identified here: https://github.com/docker/docker/pull/13987

**Comment by maaquib** [comment]
#dibs
