### ISSUE TITLE
Mounting a directory from host pc inside docker container using container_settings.json

### ISSUE THREAD

**Issue by rwatts3** [docker/docker#14419]
Greetings, 

I am using container_settings.json file to keep my dev, and deployment process clean. 
I have not been successful in mapping a directory from within my code to a specific directory within my container/image. 

I am using a lucee-tomcat image where the files to render the site needs to go to /var/www. There is a folder in my code called /mura, where I want to edit , and have the updates go to /var/www. Could someone please provide an example of how to do this that is not a CLI example. Again I'm trying to make this as clean as possible utilizing a container_settings.json file. 

Thank you , 

Ryan

**Comment by cpuguy83** [comment]
See https://docs.docker.com/reference/api/docker_remote_api_v1.19/#create-a-container
It's under HostConfig.Binds

**Comment by rwatts3** [comment]
Thank you , i'll look into it. 
Btw great work, and great product.
