### ISSUE TITLE
Cannot docker cp from a "created" container in 1.7

### ISSUE THREAD

**Issue by vieux** [docker/docker#14420]
Sorry I don't have simpler reproductible case:

```
# with docker 1.7.0
$ docker build -t test https://github.com/docker/swarm.git
[...]
Successfully built 6cf32fd0bd6e
$ docker create test
09e47aeb20c47c1190bc22d2853a816e1e998864e75cb611a468e41c2f5bd590
$ docker cp 09e47aeb20c47c1190bc22d2853a816e1e998864e75cb611a468e41c2f5bd590:/go/bin/swarm .
Error response from daemon: Could not find the file /go/bin/swarm in container 09e47aeb20c47c1190bc22d2853a816e1e998864e75cb611a468e41c2f5bd590
```

```
# with docker 1.6.2
$ docker build -t test https://github.com/docker/swarm.git
[...]
Successfully built 6cf32fd0bd6e
$ docker create test
09e47aeb20c47c1190bc22d2853a816e1e998864e75cb611a468e41c2f5bd590
$ docker cp 09e47aeb20c47c1190bc22d2853a816e1e998864e75cb611a468e41c2f5bd590:/go/bin/swarm .
```

If I replace `create` by `run` it works 1.7.0

**Comment by calavera** [comment]
mmmm this is strange, but it seems to work with a simple:

```
FROM alpine:latest
RUN touch /test
```

**Comment by calavera** [comment]
@vieux I get this error building swarm when I try your test:

```
The command '/bin/sh -c CGO_ENABLED=0 go install -v -a -tags netgo -installsuffix netgo -ldflags "-w -X github.com/docker/swarm/version.GITCOMMIT `git rev-parse --short HEAD`"' returned a non-zero code: 1
```

**Comment by coolljt0725** [comment]
I had take a look at this , this will happen when the image has a `VOLUME`
Simply can reproduce by
<pre><code>FROM busybox
VOLUME /test

docker build -t test:cp .
[l00284783@localhost docker]$ docker create test:cp
2a62d3c9a89f90417480e6174a608e5dc3b4a60e3f1884a0298b9d1bbe0c1c4d
[l00284783@localhost docker]$ docker cp 2a62d3c9a89f90417480e6174a608e5dc3b4a60e3f1884a0298b9d1bbe0c1c4d:/bin/sh .
Error response from daemon: Could not find the file /bin/sh in container 2a62d3c9a89f90417480e6174a608e5dc3b4a60e3f1884a0298b9d1bbe0c1c4d
</code></pre>

I'm working on to fix this. 
#dibs

**Comment by icecrime** [comment]
Thanks @coolljt0725!
