### ISSUE TITLE
Setting fixed address/network for docker0 raises fatal error

### ISSUE THREAD

**Issue by deas** [docker/docker#14425]
I would like to assign a fixed configuration to the docker0 interface. I was expecting

```
docker -d --bip=172.17.42.1/16
```
to do the trick, but it does not. Instead it fails:

```
FATA[0000] Error starting daemon: Error initializing network controller: Error creating default "bridge" network: bridge IPv4 (10.1.42.1) does not match requested configuration 172.17.42.1
```

I understand it can be done setting up the interface before launching he daemon using -b, but that seems overly complicated. Besides if that's what you should do, what would be the purpose of --bip?

```
➜  ~  docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
➜  ~  docker info   
Containers: 112
Images: 914
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1138
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-21-generic
Operating System: Ubuntu 15.04
CPUs: 8
Total Memory: 31.33 GiB
Name: bruce
ID: TUZV:ZHGP:GRHH:EJMH:BXHJ:NSUN:SGF2:L3LX:AK3X:OQ4A:PAT3:FNJO
Username: deas
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
➜  ~  uname -a
Linux bruce 3.19.0-21-generic #21-Ubuntu SMP Sun Jun 14 18:31:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
➜  ~ 
```

**Comment by mrjana** [comment]
@deas This is expected and intended behavior. As a rule, docker does not try to change the IP address of docker0 if one is already configured and is not the same as the one you are requesting using `--bip`. To make this work please remove the IP address from docker0 and then launch the daemon with the appropriate `--bip` configuration and it should work. Alternatively you can completely delete the docker0 bridge before you use this configuration. Daemon will create and set the right IP address for you
