### ISSUE TITLE
Pushing checksum to index always pushing an empty list 

### ISSUE THREAD

**Issue by oilbeater** [docker/docker#14423]
In the process of pushing to registry v1, docker client will send a list of image id and checksums to index in the last step as shown in the [document](http://beta-docs.docker.io/v1.6/reference/api/hub_registry_spec/)

However I try to push but always get an empty at last. I find the function pushRepository in https://github.com/docker/docker/blob/master/graph/push.go. It seems that at the second PushImageJSONIndex,there is no checksum in imageIndex, and the entry with no checksum will be remove in the function,so it always return an empty list.

I am not sure whether my analysis is right or there are some other consideration.

**Comment by crosbymichael** [comment]
@stevvooe ping

**Comment by stevvooe** [comment]
@oilbeater Could you please detail what exact commands you are running and what the expected result is? I cannot figure out which part of the document you are referring to.

**Comment by oilbeater** [comment]
@stevvooe I was trying to write hub in front of registry. The push process doc is (here)[docker contacts the Docker Hub to give checksums for upload images]. At the last step,

> docker contacts the Docker Hub to give checksums for upload images

It suppose to return a list with tag, id and checksum,but I always get an empty list after pushing anything.

**Comment by stevvooe** [comment]
@oilbeater I need to know _exactly_ what you did to be able to troubleshoot this. Lots of others have followed that exactly, without issue.

Please follow the advice from https://github.com/docker/docker/issues/14423#issuecomment-119062579.

Without exact information about what you're doing, we'd just be guessing.

**Comment by oilbeater** [comment]
The situation is complex, I will try to make it clear.

The background is that we were writing a docker hub for private use, and with the hub we want to trigger an event when an image is pushed for future processing. What I need is to know when and which tag is pushed to registry.  

Our registry is docker-registry v1 and I meet the same problem in both client 1.5 and 1.6, and my 1.6 info is:

sudo docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

sudo docker info
Containers: 0
Images: 97
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 97
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-44-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 1
Total Memory: 588.6 MiB
Name: ip-172-31-46-197
ID: FN4G:NIGC:K65H:ODDT:W5H6:VSYI:QFU6:NVBM:PBPE:LOFA:6FJI:ZNNU

The push process that docker client , registry and hub communication with each other is documented [here](http://beta-docs.docker.io/v1.6/reference/api/hub_registry_spec/#push). At last step it writes:
> docker contacts the Docker Hub to give checksums for upload images

The detail process below says docker client  will send a http request  to hub with body like this

```
    (The image, id`s, tags and checksums)
    [{“id”:
    “9e89cc6f0bc3c38722009fe6857087b486531f9a779a0c17e3ed29dae8f12c4f”,
    “checksum”:
    “b486531f9a779a0c17e3ed29dae8f12c4f9e89cc6f0bc3c38722009fe6857087”}]
```

So I write a hook in our hub to catch this request and find the tags that just finished a push.However no matter what tag I push, the body of the request is always an empty list.

The process is like this:

1. docker push myhub/oilbeater/hello:latest
2. capture the request and response between docker client and our hub
3. find the target request that docker client send to hub that finish a push and parse the request body

The result I except is like :
[{"id":  "9e89cc6f0bc3c38722009fe6857087b486531f9a779a0c17e3ed29dae8f12c4f",
"tag": "latest",
"checksum": "b486531f9a779a0c17e3ed29dae8f12c4f9e89cc6f0bc3c38722009fe6857087"}]

But what I get is always an empty list:
[]

The reason I guess is a bug in the implementation of docker client as I mentioned in the issue above.

**Comment by stevvooe** [comment]
@oilbeater So, you have a custom hub and registry and think this is a bug in the docker client? Are you sure that the docker client is sending the request to your custom hub?

To tell you the truth, I am not sure if this is something we can support. For this problem to happen, you already require a modified docker client to point at your hub (index, perhaps?). It then sounds like you have a separate implementation of some index/hub and a registry.

If you can reproduce this with a supported client and registry, we may be able to identify a problem, but I am not sure if we can be much help if all the software has been forked.
