### ISSUE TITLE
Unable to mount volumes on Nginx container in docker 1.6

### ISSUE THREAD

**Issue by sbose78** [docker/docker#14424]
I'm running docker 1.6 on Centos 6 to run nginx. However, mounting a volume doesn't seem to working. Could someone help debug this? 
 
I've used the following command:

```
docker run --name a2 -p 443:443 -v /etc/nginx/conf.d:/etc/nginx/conf.d -P -d nginx
```

I checked 

```
docker ps
```

There were no containers running.

However, if I run,

```
docker run --name a1 -p 443:443 -P -d nginx
```

I'm using the older version of docker because current version ( docker 1.7 ) is not being supported in Centos /RHEL 6

**Comment by cpuguy83** [comment]
Can you check the logs from the failed container, and the daemon logs from when you created this container?

**Comment by thaJeztah** [comment]
@sbose78 could you check the log files, as requested by @cpuguy83 ?

**Comment by cpuguy83** [comment]
Closing as we need more info here.
If you can still repro and provide the requested info please ping here and we can take a look.
Thanks!
