### ISSUE TITLE
Don't remove containers that are linked by volumes-from with other containers with rm without --force

### ISSUE THREAD

**Issue by griwes** [docker/docker#14431]
I am not sure whether this was discussed before, since quick searching for this did not yield any results, but:

`docker rm` has no problems removing "data only" containers, that are "linked" by `--volumes-from` with other containers, when executed without `--force`. Is this a conscious design decision, or something that was overlooked when designing `volumes-from`?

My actual use case is "remove everything that is not used", and this would be nicely achievable with `docker ps -aq | xargs docker rm`, if `docker rm` refused to remove containers that are in any way linked with (running?) containers. I hope that this use-case isn't an otherwise solved problem, since that'd mean I kinda suck at searching for things :D

Just a note: I am aware that the actual data directory doesn't go away, but this is kind of annoying anyway.

    griwes@waterdeep:~$ uname -a
    Linux waterdeep 3.19.0-21-generic #21-Ubuntu SMP Sun Jun 14 18:31:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
    griwes@waterdeep:~$ docker version
    Client version: 1.7.0-dev
    Client API version: 1.19
    Go version (client): go1.4.2
    Git commit (client): 9234460
    OS/Arch (client): linux/amd64
    Server version: 1.7.0-dev
    Server API version: 1.19
    Go version (server): go1.4.2
    Git commit (server): 9234460
    OS/Arch (server): linux/amd64
    griwes@waterdeep:~$ docker -D info
    Containers: 6
    Images: 194
    Storage Driver: aufs
     Root Dir: /home/docker-storage/aufs
     Backing Filesystem: extfs
     Dirs: 206
     Dirperm1 Supported: true
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 3.19.0-21-generic
    Operating System: Ubuntu 15.04
    CPUs: 8
    Total Memory: 31.26 GiB
    Name: waterdeep
    ID: 4S2S:VS6M:ZCNP:5AMF:BELQ:C46U:EKCU:AQEK:IUKI:3EBM:7JFU:HQPA
    Debug mode (server): false
    Debug mode (client): true
    File Descriptors: 43
    Goroutines: 68
    System Time: 2015-07-07T10:44:07.044902299+02:00
    EventsListeners: 0
    Init SHA1: 323d7713479cd6532394dac736f6b9dda4a6fd2f
    Init Path: /usr/lib/docker.io/dockerinit
    Docker Root Dir: /home/docker-storage
    WARNING: No swap limit support

**Comment by cpuguy83** [comment]
What's the problem if the data-only container is removed?
The volume still exists, and all referencing containers will still work (and you can re-create it).

Also, these data-only containers should go away in Docker 1.8 assuming we merge top-level volume management.

**Comment by griwes** [comment]
Okay, I was not aware you were working on that. The containers getting removed makes a mess when using docker-compose, since suddenly, after creating it again, it isn't actually used to store the data, which is confusing.

But a top level feature for that will be a far better fix for this, I agree.
