### ISSUE TITLE
Building image with CpusetCpus set. Running image shows blank CpusetCpus

### ISSUE THREAD

**Issue by stefansaru** [docker/docker#14439]
Hi,

Quick question:

Just noticed that after building an image with --cpuset-cpus="0,1", and running a container from that image, the "inspected" CpusetCpus is "". A complete example can be seen below

Is this behavior expected -> all platform dependent stuff has to be explicitly defined in the docker run command?

Thanks!
Stefan

--

root@e097e49d1bb1:/go/src/github.com/docker/docker# cat my_dockerfile
FROM fedora:latest
RUN echo hi
root@e097e49d1bb1:/go/src/github.com/docker/docker# docker build -t my_image --cpuset-cpus="0,1" - < my_dockerfile
Sending build context to Docker daemon 2.048 kB
Step 0 : FROM fedora:latest
 ---> ded7cd95e059
Step 1 : RUN echo hi
 ---> Running in 22c6de7093fd
hi
 ---> 1364b51c13d3
Removing intermediate container 22c6de7093fd
Successfully built 1364b51c13d3
root@e097e49d1bb1:/go/src/github.com/docker/docker# docker run --name=my_container my_image sleep 100 &
[1] 31161
root@e097e49d1bb1:/go/src/github.com/docker/docker# docker ps -a | grep my_container
a82c0ae15191        my_image            "sleep 100"         14 seconds ago      Up 12 seconds                                   my_container
root@e097e49d1bb1:/go/src/github.com/docker/docker# docker inspect a82c0ae15191 | grep CpusetCpus
        "CpusetCpus": "",
root@e097e49d1bb1:/go/src/github.com/docker/docker#

**Comment by stefansaru** [comment]
I haven't found a duplicate for this issue
I will post relevant information upon request

**Comment by cpuguy83** [comment]
This is expected behavior.
Resource constraints (among other things) are not saved as part of an image.
