### ISSUE TITLE
Default Forward rules in iptables

### ISSUE THREAD

**Issue by DominicBoettger** [docker/docker#14435]
Hello,

in my opinion --iptables=should be false as this can cause major security troubles.

Docker is rewriting the firewall rules of the server in the default configuration. So it's possible to connect to docker containers with published ports from outside even when there is a firewall configured on the host.

```
docker version: Docker version 1.6.0, build 4749651
docker info: 

Containers: 5
Images: 76
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 86
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-52-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 8
Total Memory: 31.29 GiB
```

uname -a: 3.13.0-52-generic #86-Ubuntu SMP Mon May 4 04:32:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Best regards
Dominic

**Comment by thaJeztah** [comment]
ping @mavenugo @dave-tucker I think this is your area :smile:

**Comment by sanmai-NL** [comment]
ping

**Comment by rmartinho** [comment]
So, nothing on this? So if this is not the are of @mavenugo or @dave-tucker, whose is it?

**Comment by sanimej** [comment]
Docker uses the iptables rules to provide isolation across networks, masquerading, ICC etc. So by default we can't disable iptables. For publishing the ports you can restrict the IPs with the format `ip:hostPort:containerPort` so that the external IPs are not open.

**Comment by rmartinho** [comment]
@sanimej that's not how it works. I don't want to block external IPs. I want docker to not override my firewall rules. I might be blocking everything except from a specific IP, and the way that docker messes with iptables it just trumps that and exposes the ports to the wide world.

**Comment by sanimej** [comment]
If you don't want Docker to add rules to the iptabels at all use the engine option `--iptables=false`. Give it a try with 1.12.3 and if there are any issues with that I can help.

`Docker is essentially destroying my firewall. This could even be construed as malicious behaviour; it's silly to downplay the problem.` - I wasn't downplaying your problem. This issue as reported originally seems to be about published ports being accessible from anywhere by default. That can be avoided by specifying the IP. But for your requirement setting `iptables=false` is the way to go.

**Comment by mavenugo** [comment]
Closing as per the above comment. Pls comment if you face any issues with `iptables=false` setting.

**Comment by rmartinho** [comment]
Excuse me, but this is not productive. You can't tell me that you can't disable this to provide "isolation across networks, masquerading, ICC etc so by default you can't disabled iptables" and then give me "disable iptables" as the workaround.

Because I want "isolation across networks, masquerading, ICC etc", I just don't want the security holes.

Should I take this to mean that I cannot have those features without the security holes?
