### ISSUE TITLE
Suggestion: ability to lock/unlock containers

### ISSUE THREAD

**Issue by adamkdean** [docker/docker#14438]
This suggestion will probably have the lowest priority that any suggestion has ever had, however I think it could possibly be a very low cost, high value feature.

I would like the ability to lock containers so that they cannot be removed without unlocking them. I would use this for data volume containers to stop them being accidentally removed. For example:

    $ docker run -d -v data --name example-data busybox /bin/bash
    72fc9b9fed363fb925badc7e2cc6fb3efc29323b9cb2e2b5b088262fb7fd3442

    $ docker lock 72fc9b9fed36
    72fc9b9fed36 is now locked

    $ docker rm -f 72fc9b9fed36
    Error response from daemon: container locked: 72fc9b9fed36
    Error: failed to remove containers: [72fc9b9fed36]

    $ docker unlock 72fc9b9fed36
    72fc9b9fed36 is now unlocked

    $ docker rm -f 72fc9b9fed36
    72fc9b9fed363fb925badc7e2cc6fb3efc29323b9cb2e2b5b088262fb7fd3442

I know this seems like a really small and nonsensical feature but it really would make the docker ps -a | grep etc | xargs docker rm "cleanup" routines easier. I might be tempted to get my feet wet and work on this myself but I wondered what people's thoughts were on this first?

**Comment by lukebennett** [comment]
I'd concur with something like this, although perhaps the lock should apply at volume-level instead so as to prevent deletion of the last container referencing that volume?

**Comment by cpuguy83** [comment]
This will be pointless for volumes since we will have top-level management.
However I can see the usefulness in being able to lock a container.

**Comment by icecrime** [comment]
Closing as duplicated of #9878.
