### ISSUE TITLE
*Second* time start of tomcat:7 / windows 7 does not bind into host port

### ISSUE THREAD

**Issue by tkassila** [docker/docker#14434]
Description of problem:
A docker container or bootdocker does not bind again container port into host port after first binding.

`docker version`:

Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64

`docker info`:
.. 
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 88
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.5-boot2docker
Operating System: Boot2Docker 1.7.0 (TCL 6.3); master : 7960f90 - Thu Jun 18 18:                                                                                        31:45 UTC 2015
CPUs: 4
Total Memory: 1.955 GiB
Name: boot2docker
ID: VVQV:M2C2:7P5A:3ZWP:AYFB:WCYC:AIFR:DGA4:2TY5:7LRE:LZTD:C4EP
Debug mode (server): true
File Descriptors: 10
Goroutines: 15
System Time: 2015-07-07T12:28:11.046845432Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker

`uname -a`:

Linux boot2docker 4.0.5-boot2docker #1 SMP Tue Jun 16 01:39:56 UTC 2015 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):

VBox v. 4.3.28 r 100309 on Windows 7 64 bit, latest updates, host machine: Hp Probook 6560B

How reproducible:

Steps to Reproduce:
0. Run bootdocker 1.5 on Windows 7 with VBox using docker user
1. docker run -d -P tomcat:7
(2. docker ps)
3. Working with any browser on windows 7 host: localhost:32768
4. docker stop <id of "tomcat:7:32768">
5. docker ps
6. docker run -d -P tomcat:7
7. curl 127.0.0.1:32769  (ok, tomcat responds), but host browser does not work on port 32769

Actual Results:
After step 6, a host browser does not work any more with updated port of the tomcat:7.

Expected Results:
An updated binded host port after start a new tomcat container after the first tomcat container.

Additional info:
Without stopping any tomcat7 container (step 5), also a new started second running tomcat7 container does not working on the host browser. And stopped and started new containers has the same result: no working host ports.

Latest VBox (the same as above) debian 8 / docker / tomcat:7 is working perfect with the same docker commands. Debian 8 web browser is working as except.

Also same happend, when I deleted all images and containers without debian and ubuntu 14.04 images. At last I downloaded tomcat:7 again and started a new tomcat container.

Commands:
docker run, stop

**Comment by cpuguy83** [comment]
I'm closing this because it is specifically not a Docker issue.
If anything it should go in the boot2docker repo..

But even then, I think there's probably some misconceptions here.
I would not expect you to be able to access a container from the host on localhost unless you specifically setup those port mappings.
Neither boot2docker nor docker-machine will set these up for you.

If you would like to troubleshoot, feel free to head over to #docker on IRC, the docker-user mailing list, or forums.docker.com

Thanks!

**Comment by tkassila** [comment]
I'm moving it there. At first time I cannot find it.
