### ISSUE TITLE
Misleading wording in the Dockerfile best practices documentation

### ISSUE THREAD

**Issue by michipili** [docker/docker#14433]
In the [Dockerfile best practices](https://docs.docker.com/articles/dockerfile_best-practices/) documentation, we read:

> In the case of the ADD and COPY instructions, the contents of the file(s) being put into the image are examined. Specifically, a checksum is done of the file(s) and then that checksum is used during the cache lookup. If anything has changed in the file(s), including its metadata, then the cache is invalidated.

The first sentence is incomplete and misleading, *files*, *files contents*, and *files contents and metadata* are used interchangeably, but there is actually only the latter. The purpose of mentioning the checksum is unclear, and mentioning it breaks the logical connection between the first and and the third sentence. A better wording would be:

> In the case of the ADD and COPY instructions, the files being put into the image are examined and if anything has changed in their contents or their metadata, then the cache is invalidated. The comparison mechanism actually uses a checksum deduced from the files contents and metadata. Therefore, in some extremely rare occurrences, some cache entry might not be invalidated as expected.

----
    docker version:     Not relevant,
    docker info:          this is about 
    uname -a:                   the website

**Comment by jfrazelle** [comment]
pull requests welcome

**Comment by michipili** [comment]
infos about were that text lie in which repository welcome

**Comment by thaJeztah** [comment]
@michipili sure! You can find tat document here; https://github.com/docker/docker/blob/master/docs/articles/dockerfile_best-practices.md

Thanks in advance for contributing!

**Comment by charleswhchan** [comment]
+exp/beginner
+kind/writing

**Comment by charleswhchan** [comment]
#dibs

**Comment by thaJeztah** [comment]
Pull request is here; https://github.com/docker/docker/pull/14725

**Comment by michipili** [comment]
Nice things happened during my holiday! :)

I like #14433, not taking creation times and modification times for cache invalidation anymore. Until today, I only found me artificially setting these timestamps to the epoch to let only the checksum count!

I guess *this* is to close when #14433 has been merged.

@thaJeztah Thank you for the documentation reference!

**Comment by charleswhchan** [comment]
PR #14725 merged. 
Please review if this issue can be also be closed.

**Comment by thaJeztah** [comment]
thanks @charleswhchan!
