### ISSUE TITLE
hack/install.sh does not appear to support Boot2Docker VMs

### ISSUE THREAD

**Issue by alvinr** [docker/docker#14443]
# Problem
I'm trying to install an experimental build on Boot2Docker VM and get the following

```
  Either your platform is not easily detectable, is not supported by this
  installer script (yet - PRs welcome! [hack/install.sh]), or does not yet have
  a package for Docker.  Please visit the following URL for more detailed
  installation instructions:

    https://docs.docker.com/en/latest/installation/
```

# Diagnosis
There are a couple of issues I see

1. lsb_release
Appears to return a full string, not just the distro (e.g. on Ubuntu this command returns "Ubuntu")

```
$ lsb_release -si
Boot2Docker 1.6.2 (TCL 5.4); master : 4534e65 - Wed May 13 21:24:28 UTC 2015
```

2. No conditional branch for boot2docker

There are specific branches for ubuntu, gentoo, fedora etc. but not one for boot2docker

# System Info

```
docker@dev:~$ uname -a
Linux dev 4.0.3-boot2docker #1 SMP Wed May 13 20:54:49 UTC 2015 x86_64 GNU/Linux
```

```
docker@dev:~$ docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

```
docker@dev:~$ docker -D info
Containers: 0
Images: 0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 4.0.3-boot2docker
Operating System: Boot2Docker 1.6.2 (TCL 5.4); master : 4534e65 - Wed May 13 21:24:28 UTC 2015
CPUs: 1
Total Memory: 998 MiB
Name: dev
ID: 4BYU:OUJU:56MT:3RTH:WQVR:HEM5:NU7L:THRR:NWUZ:EIXB:DM2I:2Z6J
Debug mode (server): true
Debug mode (client): true
Fds: 10
Goroutines: 16
System Time: Tue Jul  7 17:04:37 UTC 2015
EventsListeners: 0
Init SHA1: 7f9c6798b022e64f04d2aff8c75cbf38a2779493
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=vmwarefusion
```

**Comment by unclejack** [comment]
@alvinr Yes, this is how it works. You don't install Docker on boot2docker. It's bundled with the system and it's never ever installed by hand.

This isn't a bug.

**Comment by alvinr** [comment]
So the machine was created through docker-machine. I want to use the experimental version hence the need to upgrade Docker locally. If I was using a cloud provider I could use

```
--engine-install-url https://experimental.docker.com
```

But because Docker is baked into the Read Only F/S of the Boot2Docker ISO, I would either need an experimental version of the ISO image or manually update the Docker binary after the VM comes up (with the knowledge that this gets wiped out on re-boot).

Opened this issue up because this is not a very clean user experience. Perhaps my use case is wrong.

**Comment by unclejack** [comment]
@alvinr That would require an experimental boot2docker.iso build.
