### ISSUE TITLE
oom_kill_disable poorly understood & implemented

### ISSUE THREAD

**Issue by phemmer** [docker/docker#14440]
While it's no secret I've been hugely against this feature since back when it was just a proposal/PR (#12528/#11034), upon further investigation, it seems that the feature was implemented without much understanding, as proven by the fact that it doesn't even work :-)

Ok, so first subject, it doesn't work (docker 1.7.0):
I don't know where docker thinks it's setting the cgroup parameter to disable the oom killer, but it's not on the cgroup used by the container.

```
# docker run -i --privileged --oom-kill-disable fedora:20 bash <<'EOF' 
mount -n -t tmpfs -o uid=0,gid=0,mode=0755 cgroup /sys/fs/cgroup
mkdir /sys/fs/cgroup/memory
mount -n -t cgroup -o memory cgroup /sys/fs/cgroup/memory
memcgpath="/sys/fs/cgroup/memory/$(awk -F: '$2 == "memory" { print $3 }' < /proc/1/cgroup)"
echo "memcgpath=$memcgpath"
cat $memcgpath/memory.oom_control
EOF

memcgpath=/sys/fs/cgroup/memory//system.slice/docker-dc1408974e62968ff7e73fe3206045a98a540a0f455d864677be5e9a47d76cc5.scope
oom_kill_disable 0
under_oom 0
```

Secondly, the cgroup oom_kill_disable setting only does anything if a cgroup memory limit is also in place. Currently nothing enforces or advises the oom-kill-disable option only be used in conjunction with a memory limit.

Thirdly, using this flag requires manual intervention if the container does hit an OOM condition. The flag does prevent the process from being killed, but the process hangs instead (goes into defunct state). This means manual intervention is required to either kill the process/container, or to increase the memory limits. If you want to increase the limits, you have to go mucking around in the cgroup filesystem. So realistically, the action to take here is to manually kill the container.
To compound this, the fact that the process has been sent defunct is not easily observable. From the perspective of someone using the docker client, the container is still running, the processes inside it are still there, they just stop responding.

&nbsp;

Here's a little test container I created for this: [phemmer/do-oom](https://registry.hub.docker.com/u/phemmer/do-oom/) ([github](http://github.com/phemmer/docker-do-oom))
The container runs a process which allocates 20gb of memory, and then tries to use that 20gb (which invokes OOM).
**NOTE**: I do not advise running this container on a system which you care about. The OOM killer is very indiscriminate, and can kill anything. Also don't run it on a system with swap enabled, or the entire system will likely come grinding to a halt.

The first example, we run the container with oom killer (supposedly) disabled:

```
# docker run -ti --oom-kill-disable do-oom 
mallocs complete
Used 0 bytes
Used 104857600 bytes
Used 209715200 bytes
Used 314572800 bytes
Used 419430400 bytes
Used 524288000 bytes
Used 629145600 bytes
Used 734003200 bytes
Used 838860800 bytes
Used 943718400 bytes
Used 1048576000 bytes
Used 1153433600 bytes
Used 1258291200 bytes
Used 1363148800 bytes
Used 1468006400 bytes
Used 1572864000 bytes
Used 1677721600 bytes
Used 1782579200 bytes
Used 1887436800 bytes
Used 1992294400 bytes
Used 2097152000 bytes
Used 2202009600 bytes
Used 2306867200 bytes
Killed
#
```
Here we see the container was killed due to OOM.

&nbsp;

Now we set a limit of 500M
```
# docker run -ti --oom-kill-disable -m 500M do-oom 
mallocs complete
Used 0 bytes
Used 104857600 bytes
Used 209715200 bytes
Used 314572800 bytes
Used 419430400 bytes
Killed
#
```
&nbsp;

Now lets run it with the fix enabled, but no memory limit:
```
# docker run -ti --oom-kill-disable --privileged do-oom fix do-oom
mallocs complete
Used 0 bytes
Used 104857600 bytes
Used 209715200 bytes
Used 314572800 bytes
Used 419430400 bytes
Used 524288000 bytes
Used 629145600 bytes
Used 734003200 bytes
Used 838860800 bytes
Used 943718400 bytes
Used 1048576000 bytes
Used 1153433600 bytes
Used 1258291200 bytes
Used 1363148800 bytes
Used 1468006400 bytes
Used 1572864000 bytes
Used 1677721600 bytes
Used 1782579200 bytes
Used 1887436800 bytes
Used 1992294400 bytes
Used 2097152000 bytes
Used 2202009600 bytes
Used 2306867200 bytes
Used 2411724800 bytes
#
```
Still was killed

&nbsp;

Now we run it with a memory limit, and the fix enabled:
```
# docker run -ti --oom-kill-disable -m 500M --privileged do-oom fix do-oom 
mallocs complete
Used 0 bytes
Used 104857600 bytes
Used 209715200 bytes
Used 314572800 bytes
Used 419430400 bytes
```
Here the process just hangs as it's gone defunct. CTRL+C doesn't work, and we have to detach & kill the container.

----

```
# docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64

# docker info
Containers: 107
Images: 376
Storage Driver: btrfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.18.1-gentoo
Operating System: Gentoo/Linux
CPUs: 4
Total Memory: 7.512 GiB
Name: gadget
ID: KLI3:BPWQ:CK45:NJCL:ULCH:BV6Z:XDFM:YKTZ:EZ7D:UBE7:ZQCK:HOGN
Username: phemmer
Registry: https://index.docker.io/v1/

# uname -a
Linux gadget 3.18.1-gentoo #1 SMP Sun Dec 21 12:15:16 EST 2014 x86_64 Intel(R) Core(TM) i7-3517U CPU @ 1.90GHz GenuineIntel GNU/Linux
```

**Comment by phemmer** [comment]
The documentation for the feature also has errors:

https://docs.docker.com/reference/run/#memory-constraints
> By default, Docker kills processes in a container if an out-of-memory (OOM) error occurs. To change this behaviour, use the `--oom-kill-disable` option. Only disable the OOM killer on containers where you have also set the `-m`/`--memory` option. If the `-m` flag is not set, this can result in the host running out of memory and require killing the host’s system processes to free memory.

* Docker doesn't kill anything, the kernel does.
* The host can run out of memory with or without the `-m` flag set. But it's also irrelevant as `--oom-kill-disable` does nothing unless `-m` is passed.

**Comment by hqhq** [comment]
First subject, that's a mistake, the author must forgot to add systemd support for oom-kill-disable in libcontainer, so it won't work on Fedora, so all your following tests won't work as expected, can you try on other distros like Ubuntu and test again? Fix for runc is on the way: https://github.com/opencontainers/runc/pull/97

Secondly, I'm totally agree with you, I did sent a PR: https://github.com/docker/docker/pull/13242 but it's a break change, and didn't catch up 1.7, so it won't be merged. :disappointed: 

Thirdly, when oom kill disabled, processes hang when oom occur is expected, oom sucks, there is no way to handle it to make everyone happy.

For documentation, I sent a PR #14450 , it only addresses your first comment, I'm not sure about your other two.
 - OOM killer always enabled, we can control it to affect one container or not by setting oom-kill-disable
 - if we use `--oom-kill-disable` without `-m`, when we run out of memory, OOM killer will kill something, but `--oom-kill-disable` can help prevent processes in our container from being killed, so it does something.

Can you explain more? Or feel free to comment in the PR.

**Comment by cpuguy83** [comment]
Being that the OOM docs were enhanced, and that this flag does one thing, disable the oom killer, is this issue still relevant?
Is there some better way to handle oom-kill-disable?

**Comment by crosbymichael** [comment]
I think with the recent changes that were merged this has been explain a little better.

@phemmer let me know if there is anything else we can do and I'll reopen this with something actionable for us to complete.

Thanks!
