### ISSUE TITLE
docker cp overwrites anything without prompting user

### ISSUE THREAD

**Issue by aanm** [docker/docker#14448]
Making a
```bash
docker cp ID:FILE $HOME
```
can overwrite user's home directory with a file without any warning to the end-user causing loss of $HOME. (if $HOME's name equals to FILE's name)
Guilty: https://github.com/docker/docker/blob/master/pkg/archive/archive.go#L581
Affected versions: since docker cp was implemented

**Comment by vdemeester** [comment]
@aanm I think it's related to that issue https://github.com/docker/docker/issues/10040, right ?

**Comment by aanm** [comment]
@vdemeester Oh yeah, you're right, unfortunately since Jan 12 the bug hasn't been fixed.
