### ISSUE TITLE
"docker build" does not use the credentials in .dockercfg to pull the base image

### ISSUE THREAD

**Issue by pchico83** [docker/docker#14469]
This is very inconvenient to automate builds, since in order to build a dockerfile like this:

```
FROM my_private_image

RUN some command
```

I need to do:

```
docker pull my_private_image
docker build .
```

which requires parsing of the dockerfile. Is this by design? or is it possible to change it?

**Comment by ekristen** [comment]
@pchico83 there was a change with the builder that was a regression, supposedly there is a fix in `1.7.1-rc1`. I am working on testing that out right now.

**Comment by ekristen** [comment]
https://github.com/docker/docker/commit/6906fb0693eabb2cb7b84b9cfbaf203b9f8e2b59

**Comment by pchico83** [comment]
@ekristen Thanks! I guess I can close this issue then.
