### ISSUE TITLE
boot2docker volume resize suggests gparted livecd which is currently incompatible with the boot2docker vm

### ISSUE THREAD

**Issue by dunk** [docker/docker#14467]
The guide here on the docker documentation (https://docs.docker.com/articles/b2d_volume_resize/) suggests using the gparted livecd iso, however, the current version does not work. Others have experienced this problem too, see: https://gist.github.com/joost/a7cfa7b741d9d39c1307

Version of gparted livecd: gparted-live-0.22.0-2-i586.iso
Version of boot2docker:
Boot2Docker-cli version: v1.6.0
Git commit: 9894ae9

**Comment by thaJeztah** [comment]
@dunk are you interested in contributing, and opening a PR to improve that documentation? The markdown file used to create that documentation can be found in this repository; https://github.com/docker/docker/blob/master/docs/articles/b2d_volume_resize.md

**Comment by dunk** [comment]
With the new native docker, and also the ability to resize the mv via docker-machine (albeit by creating a new one), I think that this ticket is no longer really relevant.

**Comment by thaJeztah** [comment]
Thanks @dunk!
