### ISSUE TITLE
Return DOCKER_OPTS when using GET /info

### ISSUE THREAD

**Issue by disconnect3d** [docker/docker#14465]
It would be cool to be able to get `DOCKER_OPTS` defined in `/etc/default/docker` from GET api request to `/info` (e.g. `echo -e "GET /info HTTP/1.0\r\n" | nc -U /var/run/docker.sock`).

Actually my use case is that I need to know whether the `DOCKER_OPTS` contains:
```
-d --bip=172.17.42.1/16 --dns=172.17.42.1
```
because I would like to warn user if it's not set so [dnsdock](https://github.com/tonistiigi/dnsdock) won't work (and launch dnsdock automatically if it's set).

**Comment by jfrazelle** [comment]
no because what would happen on windows or other distros that is not a generic thing

**Comment by phemmer** [comment]
I actually find this request kinda interesting. However the request should be to show the docker arguments, and arguments are cross-platform.
