### ISSUE TITLE
Proposal: Lock out access to containers

### ISSUE THREAD

**Issue by aleemb** [docker/docker#14473]
I took on Docker today with the hope that I could use it as a sort of application binary: Allow users to run the container and consume the services provided by it but not allow them access inside the container.

My primary use-case is that I would like to be able to deploy small enterprise services as docker containers, as opposed to deploying entire hardware systems behind lock and key.

My other use-case is also that I want to do have docker containers run as a sandbox for critical but dependent services without providing access to junior developers or sub-contractors. Typically this can be achieved by running certain services on the local intranet (on staging/development servers) but having these services run locally would be really helpful.

Is there anything I can do to achieve this today? I don't need a fool-proof system but something that would be reasonably difficult to snoop inside.

**Comment by cpuguy83** [comment]
Thanks for the proposal!

I'm going to close this in favor of the discussion going on here: #13697 around the greater access/authorization topic.
