### ISSUE TITLE
Problem docker pull any image

### ISSUE THREAD

**Issue by kixiro** [docker/docker#14470]
~$ docker pull php:5.4-fpm
5.4-fpm: Pulling from php
64e5325c0d9d: Downloading [>                                                  ] 195.7 kB/51.36 MB
64e5325c0d9d: Error downloading dependent layers 
addf6a6a564c: Downloading [===>                                               ]   684 kB/8.72 MB
addf6a6a564c: Downloading [====>                                              ] 749.6 kB/8.72 MB
7aa4041d8445: Downloading [>                                                  ] 1.047 MB/69.23 MB
da3d2c32f45c: Download complete 
e5836e7aeccf: Download complete 
ef7f17c25d56: Download complete 
6b54cf50c66a: Download complete 
867a56e9452c: Download complete 
8c32c9923692: Downloading [>                                                  ]   326 kB/31.79 MB
8c32c9923692: Downloading [>                                                  ] 522.6 kB/31.79 MB
280fa6561318: Download complete 
508fcd7b9200: Download complete 
bdeaf8642f53: Download complete 
15e8f1529b87: Download complete 
15e8f1529b87: Error pulling image (5.4-fpm) from php, Untar re-exec error: exit status 1: output: unexpected EOF 
Error pulling image (5.4-fpm) from php, Untar re-exec error: exit status 1: output: unexpected EOF

/var/log/docker.log 

time="2015-07-08T18:37:19.435684876+03:00" level=debug msg="Calling POST /images/create" 
time="2015-07-08T18:37:19.435734304+03:00" level=info msg="POST /v1.19/images/create?fromImage=php%3A5.4-fpm" 
time="2015-07-08T18:37:19.435783559+03:00" level=debug msg="pulling image from host \"docker.io\" with remote name \"library/php\"" 
time="2015-07-08T18:37:19.435827151+03:00" level=debug msg="pinging registry endpoint https://index.docker.io/v1/" 
time="2015-07-08T18:37:19.435838276+03:00" level=debug msg="attempting v1 ping for registry endpoint https://index.docker.io/v1/" 
time="2015-07-08T18:37:19.503507817+03:00" level=debug msg="Fetched 1 base graphs at 2015-07-08 18:37:19.50349019 +0300 MSK" 
time="2015-07-08T18:37:19.503660031+03:00" level=debug msg="pulling v2 repository with local name \"php\"" 
time="2015-07-08T18:37:19.503748007+03:00" level=debug msg="pinging registry endpoint https://registry-1.docker.io/v2/" 
time="2015-07-08T18:37:19.503820539+03:00" level=debug msg="attempting v2 ping for registry endpoint https://registry-1.docker.io/v2/" 
time="2015-07-08T18:37:19.503899429+03:00" level=debug msg="hostDir: /etc/docker/certs.d/registry-1.docker.io" 
time="2015-07-08T18:37:19.507394977+03:00" level=debug msg="Reloaded graph with 3 grants expiring at 2017-03-22 19:04:46.713978458 +0000 UTC" 
time="2015-07-08T18:37:20.005937088+03:00" level=debug msg="Getting authorization for library/php [pull]" 
time="2015-07-08T18:37:20.006486299+03:00" level=debug msg="Pulling tag from V2 registry: \"5.4-fpm\"" 
time="2015-07-08T18:37:20.006596845+03:00" level=debug msg="[registry] Calling \"GET\" https://registry-1.docker.io/v2/library/php/manifests/5.4-fpm" 
time="2015-07-08T18:37:20.006663571+03:00" level=debug msg="Getting bearer token with map[realm:https://auth.docker.io/token service:registry.docker.io] for " 
time="2015-07-08T18:37:20.006736146+03:00" level=debug msg="hostDir: /etc/docker/certs.d/auth.docker.io" 
time="2015-07-08T18:37:20.458936212+03:00" level=debug msg="hostDir: /etc/docker/certs.d/registry-1.docker.io" 
time="2015-07-08T18:37:21.501829640+03:00" level=debug msg="provided manifest reference \"5.4-fpm\" is not a digest: invalid checksum digest format" 
time="2015-07-08T18:37:21.502942332+03:00" level=debug msg="Key check result: verified" 
time="2015-07-08T18:37:21.503004693+03:00" level=info msg="Image manifest for php:5.4-fpm has been verified" 
time="2015-07-08T18:37:21.505635672+03:00" level=debug msg="pulling blob \"sha256:df22f9f3e4ec0314365ab381f1ec439d276a6883e7175b1decd3955402ae5f61\" to V1 img 64e5325c0d9d80a28031d3c3689ac02041d74360cb0e7383a4df8a780328d833" 
time="2015-07-08T18:37:21.505799775+03:00" level=debug msg="[registry] Calling \"GET\" https://registry-1.docker.io/v2/library/php/blobs/sha256:df22f9f3e4ec0314365ab381f1ec439d276a6883e7175b1decd3955402ae5f61" 
time="2015-07-08T18:37:21.505849521+03:00" level=debug msg="Using cached token for " 
time="2015-07-08T18:37:21.505905876+03:00" level=debug msg="hostDir: /etc/docker/certs.d/registry-1.docker.io" 
time="2015-07-08T18:37:21.505963467+03:00" level=debug msg="pulling blob \"sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4\" to V1 img bf84c1d84a8fbea92675f0e8ff61d5b7f484462c4c44fd59f0fdda8093620024" 
time="2015-07-08T18:37:21.506078873+03:00" level=debug msg="[registry] Calling \"GET\" https://registry-1.docker.io/v2/library/php/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" 
time="2015-07-08T18:37:21.506121714+03:00" level=debug msg="Using cached token for " 
time="2015-07-08T18:37:21.506170454+03:00" level=debug msg="hostDir: /etc/docker/certs.d/registry-1.docker.io" 
time="2015-07-08T18:37:21.506213875+03:00" level=debug msg="pulling blob \"sha256:20cdf1ed7e7335bd307f168b50afda247060cbbfe7f89542fdb4e950a97cf285\" to V1 img addf6a6a564c0b60142b29c1fe9bb0d2c7667925e259787e08f8cde65187aeeb" 
time="2015-07-08T18:37:21.506296729+03:00" level=debug msg="[registry] Calling \"GET\" https://registry-1.docker.io/v2/library/php/blobs/sha256:20cdf1ed7e7335bd307f168b50afda247060cbbfe7f89542fdb4e950a97cf285" 
time="2015-07-08T18:37:21.506328893+03:00" level=debug msg="Using cached token for " 
time="2015-07-08T18:37:21.506366555+03:00" level=debug msg="hostDir: /etc/docker/certs.d/registry-1.docker.io" 
time="2015-07-08T18:37:21.506405566+03:00" level=debug msg="pulling blob \"sha256:62f6aede02855d47410439b1bae16ea3fe34e0f4b799406ebd87ec23f86ba11e\" to V1 img 7aa4041d84451cdbb6c111bda575479a8e6cde0b507fa17a825721efd98ff5d8" 
time="2015-07-08T18:37:21.506494355+03:00" level=debug msg="[registry] Calling \"GET\" https://registry-1.docker.io/v2/library/php/blobs/sha256:62f6aede02855d47410439b1bae16ea3fe34e0f4b799406ebd87ec23f86ba11e" 
time="2015-07-08T18:37:21.506528040+03:00" level=debug msg="Using cached token for " 
time="2015-07-08T18:37:21.506563167+03:00" level=debug msg="hostDir: /etc/docker/certs.d/registry-1.docker.io" 
time="2015-07-08T18:37:21.506601723+03:00" level=debug msg="pulling blob \"sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4\" to V1 img dfb0928bb61e4260487415636ceee4b7cd57939835ef2377e809eeadacae8e48" 
time="2015-07-08T18:37:21.506682531+03:00" level=debug msg="[registry] Calling \"GET\" https://registry-1.docker.io/v2/library/php/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" 
time="2015-07-08T18:37:21.506714447+03:00" level=debug msg="Using cached token for " 
time="2015-07-08T18:37:21.506747773+03:00" level=debug msg="hostDir: /etc/docker/certs.d/registry-1.docker.io" 
time="2015-07-08T18:37:21.506785082+03:00" level=debug msg="pulling blob \"sha256:e16b361ccf42a5ab8b9def19a35b0cbddc81158cd1bcf5d262e93e13f45c3001\" to V1 img da3d2c32f45cb4fa667a105d12125183f357e2b2b66eb885ccb37ca029719a1b" 
time="2015-07-08T18:37:21.506862868+03:00" level=debug msg="[registry] Calling \"GET\" https://registry-1.docker.io/v2/library/php/blobs/sha256:e16b361ccf42a5ab8b9def19a35b0cbddc81158cd1bcf5d262e93e13f45c3001" 
time="2015-07-08T18:37:21.506894216+03:00" level=debug msg="Using cached token for " 
time="2015-07-08T18:37:21.506928295+03:00" level=debug msg="hostDir: /etc/docker/certs.d/registry-1.docker.io" 
time="2015-07-08T18:37:21.506966049+03:00" level=debug msg="pulling blob \"sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4\" to V1 img e5836e7aeccfa3a61111609f2767d7700f0936ed78ed3e902b957c863525bfc6" 
time="2015-07-08T18:37:21.507043761+03:00" level=debug msg="[registry] Calling \"GET\" https://registry-1.docker.io/v2/library/php/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" 
time="2015-07-08T18:37:21.507074879+03:00" level=debug msg="Using cached token for " 
time="2015-07-08T18:37:21.507110468+03:00" level=debug msg="hostDir: /etc/docker/certs.d/registry-1.docker.io" 
time="2015-07-08T18:37:21.507151846+03:00" level=debug msg="pulling blob \"sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4\" to V1 img ef7f17c25d56d33ff3966e228774832f25de471ec96e6b5202fbbc3c7544ee32" 
time="2015-07-08T18:37:21.507230403+03:00" level=debug msg="[registry] Calling \"GET\" https://registry-1.docker.io/v2/library/php/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" 
time="2015-07-08T18:37:21.507269027+03:00" level=debug msg="Using cached token for " 
time="2015-07-08T18:37:21.507302133+03:00" level=debug msg="hostDir: /etc/docker/certs.d/registry-1.docker.io" 
time="2015-07-08T18:37:21.507339410+03:00" level=debug msg="pulling blob \"sha256:df2dbe60c792769495ed21bda7933d51772e6e33ee3b23665a73fb2acf1d4235\" to V1 img 6b54cf50c66ac160a979b69529336a0b5577b4e1de6b0a0030a607587ee17e3b" 
time="2015-07-08T18:37:21.507418951+03:00" level=debug msg="[registry] Calling \"GET\" https://registry-1.docker.io/v2/library/php/blobs/sha256:df2dbe60c792769495ed21bda7933d51772e6e33ee3b23665a73fb2acf1d4235" 
time="2015-07-08T18:37:21.507452097+03:00" level=debug msg="Using cached token for " 
time="2015-07-08T18:37:21.507489925+03:00" level=debug msg="hostDir: /etc/docker/certs.d/registry-1.docker.io" 
time="2015-07-08T18:37:21.507531930+03:00" level=debug msg="pulling blob \"sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4\" to V1 img 867a56e9452c165618b343771ab1953809533d993407c53e13cb31c250329854" 
time="2015-07-08T18:37:21.507609965+03:00" level=debug msg="[registry] Calling \"GET\" https://registry-1.docker.io/v2/library/php/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" 
time="2015-07-08T18:37:21.507641361+03:00" level=debug msg="Using cached token for " 
time="2015-07-08T18:37:21.507675558+03:00" level=debug msg="hostDir: /etc/docker/certs.d/registry-1.docker.io" 
time="2015-07-08T18:37:21.507713484+03:00" level=debug msg="pulling blob \"sha256:4982ea6cf2d909ca5eb158c68b8b6df631e8cd2d36348d973c8c9ccf1822b4d5\" to V1 img 8c32c99236920cfd8ff575a7a76552dcabd43ec0aa93952162e5d2d445e5bbc0" 
time="2015-07-08T18:37:21.507790459+03:00" level=debug msg="[registry] Calling \"GET\" https://registry-1.docker.io/v2/library/php/blobs/sha256:4982ea6cf2d909ca5eb158c68b8b6df631e8cd2d36348d973c8c9ccf1822b4d5" 
time="2015-07-08T18:37:21.507822008+03:00" level=debug msg="Using cached token for " 
time="2015-07-08T18:37:21.507856731+03:00" level=debug msg="hostDir: /etc/docker/certs.d/registry-1.docker.io" 
time="2015-07-08T18:37:21.507895240+03:00" level=debug msg="pulling blob \"sha256:8b9be27b019bbe535e061b7fb9e19fcdfd1e88dd98390b18ad325f15829064ef\" to V1 img 48dac20b2b06cb70e7bfc9f49ce194072d2eefc3f858d3089f290ea0ce2c0739" 
time="2015-07-08T18:37:21.507976716+03:00" level=debug msg="[registry] Calling \"GET\" https://registry-1.docker.io/v2/library/php/blobs/sha256:8b9be27b019bbe535e061b7fb9e19fcdfd1e88dd98390b18ad325f15829064ef" 
time="2015-07-08T18:37:21.508009081+03:00" level=debug msg="Using cached token for " 
time="2015-07-08T18:37:21.508046181+03:00" level=debug msg="hostDir: /etc/docker/certs.d/registry-1.docker.io" 
time="2015-07-08T18:37:21.508099351+03:00" level=debug msg="pulling blob \"sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4\" to V1 img 280fa6561318511fa14acef062e18299a4ea1754f1eeca2321deca07caa0ff29" 
time="2015-07-08T18:37:21.508185479+03:00" level=debug msg="[registry] Calling \"GET\" https://registry-1.docker.io/v2/library/php/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" 
time="2015-07-08T18:37:21.508234998+03:00" level=debug msg="Using cached token for " 
time="2015-07-08T18:37:21.508282957+03:00" level=debug msg="hostDir: /etc/docker/certs.d/registry-1.docker.io" 
time="2015-07-08T18:37:21.508326248+03:00" level=debug msg="pulling blob \"sha256:8f4a67f469bdb39a3407eb28866e3259acb7eaa09b852c4f0e7455056cfc98dc\" to V1 img 508fcd7b92000eea69c930edc722dcad431e085349d548d1f4dfc9eecfff31d0" 
time="2015-07-08T18:37:21.508405047+03:00" level=debug msg="[registry] Calling \"GET\" https://registry-1.docker.io/v2/library/php/blobs/sha256:8f4a67f469bdb39a3407eb28866e3259acb7eaa09b852c4f0e7455056cfc98dc" 
time="2015-07-08T18:37:21.508437270+03:00" level=debug msg="Using cached token for " 
time="2015-07-08T18:37:21.508474317+03:00" level=debug msg="hostDir: /etc/docker/certs.d/registry-1.docker.io" 
time="2015-07-08T18:37:21.508516531+03:00" level=debug msg="pulling blob \"sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4\" to V1 img bdeaf8642f535a142e2b0dfd5eef5d32c73547f4760015ccc722f62dd7411efa" 
time="2015-07-08T18:37:21.508603810+03:00" level=debug msg="[registry] Calling \"GET\" https://registry-1.docker.io/v2/library/php/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" 
time="2015-07-08T18:37:21.508636293+03:00" level=debug msg="Using cached token for " 
time="2015-07-08T18:37:21.508669328+03:00" level=debug msg="hostDir: /etc/docker/certs.d/registry-1.docker.io" 
time="2015-07-08T18:37:21.508708166+03:00" level=debug msg="pulling blob \"sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4\" to V1 img 15e8f1529b8703bb9032ba80f2ef20f181bac881bcc3c3330dbeec8fde31132e" 
time="2015-07-08T18:37:21.508783007+03:00" level=debug msg="[registry] Calling \"GET\" https://registry-1.docker.io/v2/library/php/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" 
time="2015-07-08T18:37:21.508818966+03:00" level=debug msg="Using cached token for " 
time="2015-07-08T18:37:21.508851829+03:00" level=debug msg="hostDir: /etc/docker/certs.d/registry-1.docker.io" 
time="2015-07-08T18:37:21.508888685+03:00" level=debug msg="pulling blob \"sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4\" to V1 img 15e8f1529b8703bb9032ba80f2ef20f181bac881bcc3c3330dbeec8fde31132e" 
time="2015-07-08T18:37:21.953659472+03:00" level=debug msg="hostDir: /etc/docker/certs.d/dseasb33srnrn.cloudfront.net" 
time="2015-07-08T18:37:21.965220797+03:00" level=debug msg="hostDir: /etc/docker/certs.d/dseasb33srnrn.cloudfront.net" 
time="2015-07-08T18:37:21.968264834+03:00" level=debug msg="hostDir: /etc/docker/certs.d/dseasb33srnrn.cloudfront.net" 
time="2015-07-08T18:37:21.969521524+03:00" level=debug msg="hostDir: /etc/docker/certs.d/dseasb33srnrn.cloudfront.net" 
time="2015-07-08T18:37:21.976600450+03:00" level=debug msg="hostDir: /etc/docker/certs.d/dseasb33srnrn.cloudfront.net" 
time="2015-07-08T18:37:21.980688213+03:00" level=debug msg="hostDir: /etc/docker/certs.d/dseasb33srnrn.cloudfront.net" 
time="2015-07-08T18:37:21.983798742+03:00" level=debug msg="hostDir: /etc/docker/certs.d/dseasb33srnrn.cloudfront.net" 
time="2015-07-08T18:37:21.990925229+03:00" level=debug msg="hostDir: /etc/docker/certs.d/dseasb33srnrn.cloudfront.net" 
time="2015-07-08T18:37:21.991694825+03:00" level=debug msg="hostDir: /etc/docker/certs.d/dseasb33srnrn.cloudfront.net" 
time="2015-07-08T18:37:22.014679965+03:00" level=debug msg="hostDir: /etc/docker/certs.d/dseasb33srnrn.cloudfront.net" 
time="2015-07-08T18:37:22.018045175+03:00" level=debug msg="hostDir: /etc/docker/certs.d/dseasb33srnrn.cloudfront.net" 
time="2015-07-08T18:37:22.024472878+03:00" level=debug msg="hostDir: /etc/docker/certs.d/dseasb33srnrn.cloudfront.net" 
time="2015-07-08T18:37:22.066969825+03:00" level=debug msg="hostDir: /etc/docker/certs.d/dseasb33srnrn.cloudfront.net" 
time="2015-07-08T18:37:22.077951610+03:00" level=debug msg="hostDir: /etc/docker/certs.d/dseasb33srnrn.cloudfront.net" 
time="2015-07-08T18:37:22.130120342+03:00" level=debug msg="hostDir: /etc/docker/certs.d/dseasb33srnrn.cloudfront.net" 
time="2015-07-08T18:37:22.141644733+03:00" level=debug msg="hostDir: /etc/docker/certs.d/dseasb33srnrn.cloudfront.net" 
time="2015-07-08T18:37:22.411716086+03:00" level=debug msg="Downloaded bf84c1d84a8fbea92675f0e8ff61d5b7f484462c4c44fd59f0fdda8093620024 to tempfile /var/lib/docker/tmp/GetV2ImageBlob094758942" 
time="2015-07-08T18:37:22.418114479+03:00" level=debug msg="Downloaded e5836e7aeccfa3a61111609f2767d7700f0936ed78ed3e902b957c863525bfc6 to tempfile /var/lib/docker/tmp/GetV2ImageBlob650781161" 
time="2015-07-08T18:37:22.418863046+03:00" level=debug msg="Downloaded 15e8f1529b8703bb9032ba80f2ef20f181bac881bcc3c3330dbeec8fde31132e to tempfile /var/lib/docker/tmp/GetV2ImageBlob282372700" 
time="2015-07-08T18:37:22.419149116+03:00" level=debug msg="Downloaded ef7f17c25d56d33ff3966e228774832f25de471ec96e6b5202fbbc3c7544ee32 to tempfile /var/lib/docker/tmp/GetV2ImageBlob068759604" 
time="2015-07-08T18:37:22.419671960+03:00" level=debug msg="Downloaded 508fcd7b92000eea69c930edc722dcad431e085349d548d1f4dfc9eecfff31d0 to tempfile /var/lib/docker/tmp/GetV2ImageBlob960035354" 
time="2015-07-08T18:37:22.420546396+03:00" level=debug msg="Downloaded 6b54cf50c66ac160a979b69529336a0b5577b4e1de6b0a0030a607587ee17e3b to tempfile /var/lib/docker/tmp/GetV2ImageBlob179282435" 
time="2015-07-08T18:37:22.420763130+03:00" level=debug msg="Downloaded bdeaf8642f535a142e2b0dfd5eef5d32c73547f4760015ccc722f62dd7411efa to tempfile /var/lib/docker/tmp/GetV2ImageBlob358036657" 
time="2015-07-08T18:37:22.422003581+03:00" level=debug msg="Downloaded 867a56e9452c165618b343771ab1953809533d993407c53e13cb31c250329854 to tempfile /var/lib/docker/tmp/GetV2ImageBlob486329222" 
time="2015-07-08T18:37:22.424741306+03:00" level=debug msg="Downloaded da3d2c32f45cb4fa667a105d12125183f357e2b2b66eb885ccb37ca029719a1b to tempfile /var/lib/docker/tmp/GetV2ImageBlob678933042" 
time="2015-07-08T18:37:22.425792365+03:00" level=debug msg="Downloaded dfb0928bb61e4260487415636ceee4b7cd57939835ef2377e809eeadacae8e48 to tempfile /var/lib/docker/tmp/GetV2ImageBlob143145055" 
time="2015-07-08T18:37:22.428713750+03:00" level=debug msg="Downloaded 280fa6561318511fa14acef062e18299a4ea1754f1eeca2321deca07caa0ff29 to tempfile /var/lib/docker/tmp/GetV2ImageBlob792686055" 
time="2015-07-08T18:38:22.473121831+03:00" level=error msg="Error from V2 registry: unable to copy v2 image blob data: read tcp 54.230.45.243:443: i/o timeout" 
time="2015-07-08T18:38:22.473212131+03:00" level=debug msg="image does not exist on v2 registry, falling back to v1" 
time="2015-07-08T18:38:22.473242941+03:00" level=debug msg="pulling v1 repository with local name \"php\"" 
time="2015-07-08T18:38:22.473302568+03:00" level=debug msg="[registry] Calling GET https://index.docker.io/v1/repositories/library/php/images" 
time="2015-07-08T18:38:22.473372831+03:00" level=debug msg="hostDir: /etc/docker/certs.d/index.docker.io" 
time="2015-07-08T18:38:23.986169003+03:00" level=debug msg="Retrieving the tag list" 
time="2015-07-08T18:38:23.986342003+03:00" level=debug msg="hostDir: /etc/docker/certs.d/registry-1.docker.io" 
time="2015-07-08T18:38:47.324985512+03:00" level=debug msg="Got status code 200 from https://registry-1.docker.io/v1/repositories/library/php/tags" 
time="2015-07-08T18:38:47.325415870+03:00" level=debug msg="Registering tags" 
time="2015-07-08T18:38:47.328482386+03:00" level=debug msg="hostDir: /etc/docker/certs.d/registry-1.docker.io" 
time="2015-07-08T18:38:47.842510966+03:00" level=debug msg="Ancestry: [15e8f1529b8703bb9032ba80f2ef20f181bac881bcc3c3330dbeec8fde31132e bdeaf8642f535a142e2b0dfd5eef5d32c73547f4760015ccc722f62dd7411efa 508fcd7b92000eea69c930edc722dcad431e085349d548d1f4dfc9eecfff31d0 280fa6561318511fa14acef062e18299a4ea1754f1eeca2321deca07caa0ff29 48dac20b2b06cb70e7bfc9f49ce194072d2eefc3f858d3089f290ea0ce2c0739 8c32c99236920cfd8ff575a7a76552dcabd43ec0aa93952162e5d2d445e5bbc0 867a56e9452c165618b343771ab1953809533d993407c53e13cb31c250329854 6b54cf50c66ac160a979b69529336a0b5577b4e1de6b0a0030a607587ee17e3b ef7f17c25d56d33ff3966e228774832f25de471ec96e6b5202fbbc3c7544ee32 e5836e7aeccfa3a61111609f2767d7700f0936ed78ed3e902b957c863525bfc6 da3d2c32f45cb4fa667a105d12125183f357e2b2b66eb885ccb37ca029719a1b dfb0928bb61e4260487415636ceee4b7cd57939835ef2377e809eeadacae8e48 7aa4041d84451cdbb6c111bda575479a8e6cde0b507fa17a825721efd98ff5d8 addf6a6a564c0b60142b29c1fe9bb0d2c7667925e259787e08f8cde65187aeeb bf84c1d84a8fbea92675f0e8ff61d5b7f484462c4c44fd59f0fdda8093620024 64e5325c0d9d80a28031d3c3689ac02041d74360cb0e7383a4df8a780328d833]" 
time="2015-07-08T18:38:47.843044959+03:00" level=debug msg="hostDir: /etc/docker/certs.d/registry-1.docker.io" 
time="2015-07-08T18:38:48.370895174+03:00" level=debug msg="hostDir: /etc/docker/certs.d/registry-1.docker.io" 
time="2015-07-08T18:38:48.912712499+03:00" level=debug msg="hostDir: /etc/docker/certs.d/dseasb33srnrn.cloudfront.net" 
time="2015-07-08T18:38:49.009432541+03:00" level=debug msg="server doesn't support resume"

**Comment by hqhq** [comment]
I met the same problem, but not for every image, I can pull small images like busybox, but failed to pull larger images like dockercore/docker.
```
$ docker pull dockercore/docker
Pulling repository dockercore/docker
2788124571e1: Error pulling image (latest) from dockercore/docker, Untar re-exec error: exit status 1: output: unexpected EOF rror: exit status 1: output: unexpected EOF cd: Download complete 
29460ac93442: Download complete 
d2a0ecffe6fa: Download complete 
c171881d800e: Download complete 
b1859b2172bf: Download complete 
121a8b7bb2c0: Download complete 
9b893972cb16: Error downloading dependent layers 
Error pulling image (latest) from dockercore/docker, Untar re-exec error: exit status 1: output: unexpected EOF
```

**Comment by thaJeztah** [comment]
@vbatts is this the issue that https://github.com/docker/docker/pull/15040 should resolve?

**Comment by vbatts** [comment]
What version of docker are y'all using (`docker version `)?

**Comment by tonswieb** [comment]
I believe I am having the same or similar issue. I migrated from boot2docker to docker tools on Mac OSX.
Not sure if I should open a new issue for this or append it to this one.

The message I am getting is: Error pulling image ....., Untar re-exec error: unexpected EOF: output

I was able to download and untar the layer from the internal docker registry directly by using:
curl -o temp.jar http://....../v1/images/c852f6d61e65cddf1e8af1f6cd7db78543bfb83cdcd36845541cf6d9dfef20a0/layer
tar -xvf temp.layer

*docker info*
Containers: 1
Images: 24
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 26
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.2 (TCL 6.4); master : aba6192 - Thu Sep 10 20:58:17 UTC 2015
CPUs: 1
Total Memory: 3.859 GiB
Name: default
ID: GJB6:VGXW:ZUU2:AQS5:GZV3:FQSL:TY6J:IJU6:O5Y3:AZCV:3UZ7:SVWE
Debug mode (server): true
File Descriptors: 11
Goroutines: 17
System Time: 2015-09-15T15:16:00.44516372Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

*docker version*
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      linux/amd64

*uname -a*
Darwin MacBook-Pro-van-Ton.local 14.1.0 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64

**Comment by jadhavsagar** [comment]
docker pull fails with error unable to get remote tags, i/o timeout:


Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

$ docker pull hello-world
Using default tag: latest
Pulling repository docker.io/library/hello-world
Get https://registry-1.docker.io/v1/repositories/library/hello-world/tags/latest: dial tcp 52.86.197.218:443: i/o timeout

Debug log:

WARN[0027] Error getting v2 registry: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
ERRO[0057] unable to get remote tags: Get https://registry-1.docker.io/v1/repositories/library/hello-world/tags/latest: dial tcp 52.86.197.218:443: i/o timeout

**Comment by thaJeztah** [comment]
@jadhavsagar looks like a non-related issue, sound like something network related, and may be separate from docker. I'd check if your network is working correctly, and if there isn't a proxy-server or firewall blocking requests. Given that that doesn't look like a bug, but more a support question, I think the #docker IRC channel on freenode, or forums.docker.com may be a better place to ask that question

**Comment by thaJeztah** [comment]
I'm closing this issue, because the original issue reported does not mention enough information to look into, and the other posts are for a now outdated version of docker. Please open a new issue, if you're having this on docker 1.11 or newer
