### ISSUE TITLE
Please exempt issues beginning with UX: from Gordon Check

### ISSUE THREAD

**Issue by jberkus** [docker/docker#14483]
Dockerites:

Per requests at DockerCon, I've been filing UX issues on Github.  However, these always get flagged with a "Gordon check" because they lack a version and steps to reproduce.

Can you fix the Gordon Check to exempt any issue starting with "UX"?  Thanks!

**Comment by vdemeester** [comment]
@jberkus I would guess these are proposals to change/enhance the UX of docker. If true, you can use ``Proposal: `` in the title, and @GordonTheTurtle will not comment the way it does right now :wink:

**Comment by jberkus** [comment]
Thanks, will do!

**Comment by thaJeztah** [comment]
@jberkus if you're still interested to have this changed; you can find Gordon in the https://GitHub.com/docker/leeroy/ repository. You can create a pull request there, probably this line; https://github.com/docker/leeroy/blob/d5ee4f3bf05276a9891b1eca949a5889b66aec19/github/issue.go#L15

**Comment by jberkus** [comment]
Thanks, but I think the recommended solution is sufficient.

**Comment by thaJeztah** [comment]
@jberkus alright! just wanted to point out where to find the code if you felt it was needed :-)
