### ISSUE TITLE
'Overlay not found...ensure kenel new enough' Error on Arch Linux

### ISSUE THREAD

**Issue by toddleo** [docker/docker#14489]
Hi, I'm trying to run a docker image on my Arch Linux machine, however I cannot pull the image from Docker Registry, and as I dig into it I found the docker daemon failed to start:

    > sudo docker pull ubuntu
    Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
    > sudo docker -d
    INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
    ERRO[0000] 'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded. 
    WARN[0000] Running modprobe bridge nf_nat failed with message: , error: exit status 1 
    FATA[0000] Error starting daemon: Error initializing network controller: Error creating default "bridge" network: operation not supported

   
`docker version`: 
    Client version: 1.7.0
    Client API version: 1.19
    Go version (client): go1.4.2
    Git commit (client): 0baf609
    OS/Arch (client): linux/amd64
    Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
`docker info`: Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
`uname -r`: 4.0.6-1-ARCH
Any thoughts?

**Comment by cpuguy83** [comment]
The overlay kernel module is not loaded, and as such cannot be used.
Are you using a custom kernel? Is the kernel compiled with overlay support?

Closing since this is not a Docker issue.

**Comment by toddleo** [comment]
Hi cpuguy83,
no, the kernel is not customized, it comes with Arch Linux.

**Comment by vanga** [comment]
@toddleo did you get it to work? what's the solution for this?  I get the same error on ArchLinux

Th

**Comment by vanga** [comment]
though, my error is slightly different 
```
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
ERRO[0000] 'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded. 
WARN[0000] Running modprobe bridge nf_nat failed with message: , error: exit status 1 
FATA[0000] Error starting daemon: Error initializing network controller: Error creating default "bridge" network: package not installed 
```

**Comment by toddleo** [comment]
@vanga: no I haven't got it right yet, decided to deploy on physical machine instead of using docker, due to our strict time limit. :D

**Comment by benjah1** [comment]
@toddleo @vanga have you try the --privileged flag?

https://github.com/docker-library/docker/issues/5

**Comment by hut8** [comment]
I just had the same issue a few minutes ago on Arch. The official Docker package for Arch does install `bridge-utils`, but then you need to reboot to load it.
