### ISSUE TITLE
Misleading error message about CA certificates when DNS resolution fails for registry host

### ISSUE THREAD

**Issue by ferrouswheel** [docker/docker#14486]
Tried building an image, got warnings about certificates.

After looking around for the solution based on the error message I noticed the "no such host" errors, and then checked the DNS. DNS was funky and I couldn't resolve quay.io.

```
docker build -t xxxxx:latest .
Sending build context to Docker daemon 28.94 MB
Sending build context to Docker daemon
Step 0 : FROM quay.io/user/image
invalid registry endpoint https://quay.io/v0/: unable to ping registry endpoint https://quay.io/v0/
v2 ping attempt failed with error: Get https://quay.io/v2/: dial tcp: lookup quay.io: no such host
 v1 ping attempt failed with error: Get https://quay.io/v1/_ping: dial tcp: lookup quay.io: no such host. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry quay.io` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/quay.io/ca.crt
```

```
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): darwin/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

Ideally docker could differentiate between DNS failure and unknown CA certificates and avoid sending the user down the security rabbit hole.

**Comment by cpuguy83** [comment]
Thanks for reporting.
Looks like we just need to do a better job of detecting the type of error being thrown here instead of just printing that message all willy nilly.

**Comment by jlevesy** [comment]
#dibs

Actually, we need to watch 403 StatusCode when performing ping on both pingV1 and pingV2, right ?

**Comment by thaJeztah** [comment]
ping @cpuguy83 ^^

**Comment by cpuguy83** [comment]
@jlevesy You'll probably have to check the error string for `no such host` since the error looks like it's coming directly from the http package.

**Comment by opreaadrian** [comment]
Hi guys. Is somebody working on this atm? I see the status/claimed label removed, but I don't know if there is progress on this.

**Comment by thaJeztah** [comment]
@opreaadrian I haven't seen a pull-request for this, but since this was created several months ago, it's worth checking if improvements have already been implemented here.

**Comment by opreaadrian** [comment]
Does this involve going through the commits that at some point modified this area of functionality, or is there a more "formal" way of seeing this? I apologise if some questions seem stupid, but I'm just getting used to this type of contributions.

**Comment by thaJeztah** [comment]
@opreaadrian hm, I don't think there's a "formal way", apart from trying to reproduce the error, and see if the message was already improved. It might be worth joining the #docker-dev IRC channel, and ask if @duglin or @cpuguy83 are around for hints

**Comment by ripcurld00d** [comment]
#dibs

**Comment by ripcurld00d** [comment]
This issue was resolved.
cc: @thaJeztah @cpuguy83 @jfrazelle -- you can close it.

## Docker version

```bash
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 06:35:36 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 06:35:36 UTC 2015
 OS/Arch:      linux/amd64
```

## Dockerfile @${HOME}/bla

```Dockerfile
FROM ripcurld.void.space/busyninja:latest
```

## Executing from ${HOME}/bla

```bash
$ docker build -t busyninja .
```

## Error message

```bash
Sending build context to Docker daemon 2.048 kB
Step 0 : FROM docker-ninja.io/bla:latest
unable to ping registry endpoint https://docker-ninja.io/v0/
v2 ping attempt failed with error: Get https://docker-ninja.io/v2/: dial tcp: lookup docker-ninja.io: no such host
 v1 ping attempt failed with error: Get https://docker-ninja.io/v1/_ping: dial tcp: lookup docker-ninja.io: no such host
```

**Comment by duglin** [comment]
@ferrouswheel you ok with us closing this?

**Comment by ferrouswheel** [comment]
Yup - looks good. Thanks! :+1:
