### ISSUE TITLE
[master]: cannot pull docker image where repo name is 1 letter

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#14485]
```
Unable to find image 'jess/t:latest' locally
repository name component must be 2 or more characters
```

NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by jfrazelle** [comment]
ping @stevvooe @dmcgowan

**Comment by jfrazelle** [comment]
i should be able to have a 1 letter repo, plus this is already uploaded to hub, I refuse to change the name

**Comment by stevvooe** [comment]
@jfrazelle You're so difficult. :japanese_ogre: 

This is probably a "bug" in the distribution regexps.

**Comment by jfrazelle** [comment]
:innocent:

**Comment by stevvooe** [comment]
@jfrazelle I filed docker/distribution#687. We'll take of this.
