### ISSUE TITLE
Unable to load Docker image

### ISSUE THREAD

**Issue by shyamjithkv** [docker/docker#14496]
I know nothing about Docker....
Trying to load docker image by "sudo docker load -i symdrive.tar.gz" but getting following error 

FATA[0938] Error response from daemon: open /var/lib/docker/tmp/docker-import-403767651/repo/bin/json: no such file or directory 

Any idea what this mean

sudo docker version 

Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

sudo docker info 

Containers: 23
Images: 2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 48
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04 LTS
CPUs: 4
Total Memory: 3.763 GiB
Name: acs-desktop
ID: ZAXI:6OBQ:DNMK:KJOW:SDZG:ZS3F:5NCU:3WJA:CSJD:FARC:AJTG:O4SP
WARNING: No swap limit support

uname -a 

Linux acs-desktop 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by duglin** [comment]
How was that tar created? It needs to have some special docker files in there - so normally its the result of a "docker save"

**Comment by shyamjithkv** [comment]
Sorry i don't know how that was created.... i was downloading that form internet...will you please give a more detailed explanation

**Comment by duglin** [comment]
you can't just upload any old tar file it needs to match the docker image tar format. I would suggest that you contact the people you got the image from and ask them if its a real docker image/tar.
Closing since I don't see this as a Docker issue since I suspect the tar file is bad. If I'm mistaken please reopen.

**Comment by hixichen** [comment]
check this path issue:
tar cvf image.tar image/  

==>cd image/   
tar cvf image.tar  ＊
