### ISSUE TITLE
Installation breaks on CentOS 6.6 using get.docker.io script

### ISSUE THREAD

**Issue by luscus** [docker/docker#14497]
Hello,

I am not sure it is the right place to file the issue, but I found no other place and no open or closed issue seams related.
When trying to install docker using the following:

    wget -q -O - https://get.docker.io | sh

I get an error

    	  Either your platform is not easily detectable, is not supported by this
    	  installer script (yet - PRs welcome! [hack/install.sh]), or does not yet have
    	  a package for Docker.  Please visit the following URL for more detailed
    	  installation instructions:
    
    	    https://docs.docker.com/en/latest/installation/

The platform detection logic is missing the following lines as on CentOS the `lsb_release` and `os_release` file do not exist:

    	if [ -z "$lsb_dist" ] && [ -r /etc/centos-release ]; then
		lsb_dist='centos'
    	fi

**Comment by jfrazelle** [comment]
pull requests welcome

**Comment by Evalle** [comment]
#dibs

**Comment by luscus** [comment]
@jfrazelle point me to the right file/repo and I will do it

**Comment by Evalle** [comment]
Hello, @luscus 
I'm already done it here https://github.com/docker/docker/pull/14556
