### ISSUE TITLE
GetV2ImageBlob

### ISSUE THREAD

**Issue by martingartonft** [docker/docker#14506]
/var/lib/docker/tmp is getting full of files with prefix GetV2ImageBlob*

It got up to >20G before I deleted a bunch of them.  I don't know yet what triggered this.

Looking at pullV2Tag in graph/pull.go it appears this file can be created but not removed in at least one case.

my versions etc:

core@ip-172-31-25-180 ~ $ uname -a
Linux ip-172-31-25-180.eu-west-1.compute.internal 4.0.5 #2 SMP Thu Jun 18 08:53:45 UTC 2015 x86_64 Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz GenuineIntel GNU/Linux
core@ip-172-31-25-180 ~ $ docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2-dirty
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2-dirty
OS/Arch (server): linux/amd64
core@ip-172-31-25-180 ~ $ docker -D info 
Containers: 5
Images: 213
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 4.0.5
Operating System: CoreOS 681.2.0
CPUs: 1
Total Memory: 3.68 GiB
Name: ip-172-31-25-180.eu-west-1.compute.internal
ID: 7GH7:E2RC:3QRC:EI6G:UFX5:XALU:HR7Y:GFYZ:3SN4:EAKF:GHUK:VDXJ
Debug mode (server): false
Debug mode (client): true
Fds: 100
Goroutines: 998
System Time: Thu Jul  9 20:18:41 UTC 2015
EventsListeners: 0
Init SHA1: 66b480ca5c853908c6b972298be91461398414a7
Init Path: /usr/libexec/docker/dockerinit
Docker Root Dir: /var/lib/docker

**Comment by Florent-C** [comment]
Same issue experienced here. One of my docker nodes deployed through openshift on openStack gets overflowed with /var/lib/docker/tmp/GetV2ImageBlob* files.
The occupied space is widely larger than what the container images are supposed to occupy and seems to grow continuously until the disk is full (currently more than 28G consumed).

df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1        40G   40G   20K 100% /
**lsof -p 3449 | grep GetV2ImageBlob |  awk 'BEGIN{sizeof=0}{sizeof+=$7}END{print sizeof}'**
29508787814
**lsof -p 3449 | grep GetV2ImageBlob | wc -l**
24237

**docker version**
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): ba1f6c3/1.6.2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): ba1f6c3/1.6.2
OS/Arch (server): linux/amd64

**docker info**
Containers: 7
Images: 49
Storage Driver: devicemapper
 Pool Name: docker-253:1-117440655-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 1.156 GB
 Data Space Total: 107.4 GB
 Data Space Available: 106.2 GB
 Metadata Space Used: 2.892 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Kernel Version: 3.10.0-229.4.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 3.703 GiB
Name: 192.168.125.5
ID: Q7SD:O4AD:VWM7:64OW:JOSU:JSXB:JFJX:KDA3:3RFB:JXHQ:D3AC:WDZ7

**uname -a**
Linux 192.168.125.5 3.10.0-229.4.2.el7.x86_64 #1 SMP Wed May 13 10:06:09 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by LK4D4** [comment]
Yes, looks like that code pretty weird.
Can I have your attention @dmcgowan ?
I'm talking about downloads handling, it calls methods on `d.tmpFile` without checking nilness and also not removing it in case of `!d.download`.

**Comment by dmcgowan** [comment]
#14389 is addressing this issue

**Comment by stevvooe** [comment]
Looks like #15545 will now address this.

**Comment by thaJeztah** [comment]
@stevvooe I see https://github.com/docker/docker/pull/15545 was merged; just to be sure (previous time there was confusion around "address" and "resolve"); should this one be resolved?

**Comment by dmcgowan** [comment]
#15545 "resolved" this, closing
