### ISSUE TITLE
Unclear instructions for showing env vars after doing GUI then CLI install per doc.

### ISSUE THREAD

**Issue by ronaldpetty** [docker/docker#14511]
Hello,

On this page: http://docs.docker.com/installation/mac/

Under this heading: "From your command line"

Step 3: Display the environment variables for the Docker client.

It says to run 'boot2docker shellinit' to display your environment variables for the Docker client. It does not.

> boot2docker shellinit 
Writing /Users/rpetty/.boot2docker/certs/boot2docker-vm/ca.pem 
Writing /Users/rpetty/.boot2docker/certs/boot2docker-vm/cert.pem 
Writing /Users/rpetty/.boot2docker/certs/boot2docker-vm/key.pem 
Your environment variables are already set correctly.

This might only be on fresh installs. I tried running boot2docker via the Mac 'applications', then I tried as the instructions say to start via the cli. In either case, it did not show the environment variables. If its only during the vary first time (like during initial set up, then maybe mention that.) Could be something else, not sure yet.

Regards.

Ron

**Comment by dgeske** [comment]
`docker version`
```
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): darwin/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```

`docker info`
```
Containers: 0
Images: 16
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 16
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.7-boot2docker
Operating System: Boot2Docker 1.7.1 (TCL 6.3); master : c202798 - Wed Jul 15 00:16:02 UTC 2015
CPUs: 4
Total Memory: 1.955 GiB
Name: boot2docker
ID: YAPW:VW24:X2KS:MNS4:KWHT:BXB3:VPOR:TWYQ:DDEJ:BNPD:NOTG:ZWVX
Debug mode (server): true
File Descriptors: 10
Goroutines: 15
System Time: 2015-07-22T09:25:54.206628396Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
```

`uname -a`
```
Darwin upan 15.0.0 Darwin Kernel Version 15.0.0: Wed Jun 17 21:18:51 PDT 2015; root:xnu-3247.1.6.2.2~1/RELEASE_X86_64 x86_64
```

Running on VirtualBox via home-brew cask.

Steps to reproduce the issue:
1. Start boot2docker `boot2docker start`
2. Display the shell commands to set up the Docker client `boot2docker shellinit`


Describe the results you received:

`boot2docker start`
```
Waiting for VM and Docker daemon to start...
.o
Started.
Writing /Users/dgeske/.boot2docker/certs/boot2docker-vm/ca.pem
Writing /Users/dgeske/.boot2docker/certs/boot2docker-vm/cert.pem
Writing /Users/dgeske/.boot2docker/certs/boot2docker-vm/key.pem
Your environment variables are already set correctly.
```

`boot2docker shellinit`
```
Writing /Users/dgeske/.boot2docker/certs/boot2docker-vm/ca.pem
Writing /Users/dgeske/.boot2docker/certs/boot2docker-vm/cert.pem
Writing /Users/dgeske/.boot2docker/certs/boot2docker-vm/key.pem
Your environment variables are already set correctly.
```

Describe the results you expected:

Instead of the line `Your environment variables are already set correctly.` I expect to see the environment variables, e.g. `DOCKER_HOST`.

**Comment by dgeske** [comment]
This issue belongs to the boot2docker CLI. Raised as boot2docker/boot2docker-cli#378.

**Comment by cpuguy83** [comment]
Also see the note at the bottom of that command output

> Your environment variables are already set correctly.

This is why it is not displaying the env vars.
If you want just the env and not the full init, do `boot2docker env`.

But in any case, this is a docs issue in that the wording of the command usage for `shellinit` is not completely true.

**Comment by dgeske** [comment]
Brian, thanks for picking this up so quickly. In theory that's a great and simple solution. Unfortunately it does not work for me:
```
$ boot2docker env
error in run: Unknown command: env
Usage: boot2docker [<options>] {help|init|up|ssh|save|down|poweroff|reset|restart|config|status|info|ip|shellinit|delete|download|upgrade|version} [<args>]

$ boot2docker version
Boot2Docker-cli version: v1.7.1
Git commit: 8fdc6f5
```

**Comment by thaJeztah** [comment]
@ronaldpetty @dgeske this page has been rewritten to use docker machine (boot2docker cli is marked deprecated); https://github.com/docker/docker/blob/master/docs/installation/mac.md

Could you check if the new version improved this issue?

**Comment by dgeske** [comment]
Thanks @thaJeztah - that absolutely clarifies/fixes the issue.

**Comment by thaJeztah** [comment]
I'll close this issue, per the above comment
