### ISSUE TITLE
Unclear details on Volumes Page

### ISSUE THREAD

**Issue by ronaldpetty** [docker/docker#14510]
https://docs.docker.com/userguide/dockervolumes/

Under "Adding a data volume" you create a volume.  You then go to confirm it via the next section "Locating a volume".  When I run 'docker inspect web', I see similar output but not exact.  I see the following:
```
...
    "Volumes": {
        "/webapp": "/mnt/sda1/var/lib/docker/volumes/d2c56f0880cb121190e0d5b50c98c57d241109f37139d995da55883b7955427b/_data"
    },
    "VolumesRW": {
        "/webapp": true
    },
...
"Volumes": {
            "/webapp": {}
        },
...
```
Might want to clarify when you scroll up to see results the first 'Volumes' is not the one showing in the article, you need to scroll further up to see the detailed ones.  The empty Volumes is under the 'Config' block.  I am not sure what it is or represents.  Might just want to add a warning about seeing that or explain what it is.

Regards.

Ron

**Comment by ronaldpetty** [comment]
docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): darwin/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64

**Comment by ronaldpetty** [comment]
docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): darwin/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
[16:23][rpetty@ronsmacbookpro2:~/mydockerbuild[chef_org:]{rs_env:}]$  docker info
Containers: 32
Images: 41
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 105
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.5-boot2docker
Operating System: Boot2Docker 1.7.0 (TCL 6.3); master : 7960f90 - Thu Jun 18 18:31:45 UTC 2015
CPUs: 8
Total Memory: 1.955 GiB
Name: boot2docker
ID: NORK:HER6:3652:YPYZ:6HJ6:54FN:YWO6:R4BG:XDDF:YS3D:J4BI:LLXU
Debug mode (server): true
File Descriptors: 15
Goroutines: 25
System Time: 2015-07-09T23:23:47.257903124Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: ronaldpetty
Registry: https://index.docker.io/v1/

**Comment by ronaldpetty** [comment]
uname -a
Darwin ronsmacbookpro2.local 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64

**Comment by ronaldpetty** [comment]
On Mac using B2D.  Steps are above.  I just ran exactly what is in the docs.  Again, its not a bug per say, but the docs are unclear.

**Comment by ronaldpetty** [comment]
Also, this statement is either incorrect or unclear:

"The directory on the host must be specified as an absolute path and if the directory doesn’t exist Docker will automatically create it for you"

I tried, it does not make a directory on a Mac host.  I suspect what it means to say is:

"The directory on the host must be specified as an absolute path and exist.  If the directory on the container doesn’t exist Docker will automatically create it for you"

Not 100%, but as it reads now, its incomplete or worse incorrect.

**Comment by cpuguy83** [comment]
@ronaldpetty Docker does automatically create it for you, but keep in mind when running on a Mac, docker is remote (which can be in a VM, like boot2docker).
So it is creating the dirs local to the docker daemon.

Also, feel free to open a PR with the desired doc change.
The docs are in this repo.

**Comment by LK4D4** [comment]
It was a long time. I'm closing this for now because everything changed since.
