### ISSUE TITLE
docker should prevent from building images with same repository name.

### ISSUE THREAD

**Issue by raymondmeng36** [docker/docker#14519]
Description of problem:
For example, there is an image named aaa/bbb. Then you create another image using docker build command with paramiters -t="aaa/bbb". Right after the new image successfully created, the former image's repository and tag will turn to "none".

`docker version`:
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.3.3
Git commit (client): a8a31ef/1.5.0
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.3.3
Git commit (server): a8a31ef/1.5.0

`docker info`:
Containers: 1
Images: 13
Storage Driver: devicemapper
 Pool Name: docker-8:2-269741-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 771.2 MB
 Data Space Total: 107.4 GB
 Metadata Space Used: 1.45 MB
 Metadata Space Total: 2.147 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: native-0.2
Kernel Version: 2.6.32-504.el6.x86_64
Operating System: <unknown>
CPUs: 1
Total Memory: 988.6 MiB
Name: localhost
ID: DRCH:KHSF:45LW:LTHX:ZCIV:5LN6:2WHQ:O4FA:PUUC:EOXK:FEZJ:RPQ2
Username: cxyyouxi
Registry: [https://index.docker.io/v1/]

`uname -a`:
Linux localhost 2.6.32-504.el6.x86_64 #1 SMP Wed Oct 15 04:27:16 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
VMWare Workstation 10
CentOS_6.6_x86_64

How reproducible:
Always

Steps to Reproduce:
1. successfully create a docker image using docker build with parameter -t="aaa/bbb", return image id: aaaaaaaa
2. check the image info using docker images
3. try to create another docker image using docker build still with parameter -t="aaa/bbb", return image id: bbbbbbbb

Actual Results:
the first image aaaaaaaa's repository name and tag name turn to "none".

Expected Results:
docker should not allow user to create image with repository name that already existed.

Additional info:
![image 1](https://cloud.githubusercontent.com/assets/3907772/8611104/92fc06be-26ee-11e5-9af2-52f6da912b14.png)

**Comment by phemmer** [comment]
This is intended behavior. An image is labeled by a combination of it's repository and tag. Since you are not providing a tag it defaults to "latest". Since an image with this same repo and tag already exists, and you can't have 2 images with the same repo/tag combination, it untags the previous one.

The solution is to provide a tag to your images. E.G. `docker build -t aaa/bbb:$(date +%s)`

**Comment by coolljt0725** [comment]
Yes, this is a intended behavior, the code is here https://github.com/docker/docker/blob/master/builder/job.go#L212, `return d.Repositories().Tag(repoName, tag, id, true)` the `true` is to make build always replace the
old tag.

**Comment by raymondmeng36** [comment]
I know this is inteded behavior. But I think If docker gives a tip message before creating will be more friendly.

**Comment by coolljt0725** [comment]
Maybe we should updates the docs

**Comment by cpuguy83** [comment]
This is pretty much exactly how git tagging works.
If you have a git tag, and tag something else with the same name, the commit will be untagged.
I think this should be fully expected by all users.... so I'm inclined to close, but will leave open for discussion, maybe there does need to be a doc update?

Today there isn't even a way to untag an image without tagging a new one with the same repo/tag name, so it's really the _only_ way to handle it in this situation outside of never re-using tag names.

**Comment by jfrazelle** [comment]
this is intended
