### ISSUE TITLE
experimental libnetwork not working in AWS

### ISSUE THREAD

**Issue by vijayendrabvs** [docker/docker#14517]
Hi,

I spun up two Ubuntu 14.04 VMs in AWS, and on each, upgraded to the 3.18 kernel, installed docker, did a git clone https://github.com/docker/docker.git; followed by a make DOCKER_EXPERIMENTAL=1 . I then created a soft link to docker/bundles/1.8.0-dev/binary/docker-1.8.0-dev at /usr/bin/docker, effectively replacing the older docker that was installed.

Then, I followed the instructions at https://github.com/docker/libnetwork/blob/master/docs/overlay.md, copy-pasting each instruction and replacing the IPs as applicable. Consul came up, docker daemons came up well on each node, and I was able to create services, networks, attach containers to services, etc, as described in the document.

The problem I'm seeing is that while pings between containers on the same host work fine, I'm not able to ping one container from another across the two hosts. 

Any idea why this doesn't work? I'll be testing libnetwork on my vagrant setup in a short while, and will update the bug with those results.

Thanks,
Regards,
Vijay

**Comment by mavenugo** [comment]
@vijayendrabvs the overlay driver uses Serf to exchange L2/L3 reach-ability information. It operates on a specific TCP port which needs to be allowed to be exposed on the AWS VMs. @nathanleclaire recently went through this process and we will be updating the document with that information. @nathanleclaire can you please share the settings that you used to get the overlay driver working in AWS ?

**Comment by vijayendrabvs** [comment]
Thanks @mavenugo ! I tried this on my localhost vagrant setup with 2 VMs and it works fine on it. I'll await the instructions for AWS and try it out and let you know how it goes.

**Comment by nathanleclaire** [comment]
I can't actually recall off the top of my head what I ended up doing (other than opening the port for Serf in the SG which you seem to have done already), and I think I couldn't get it working except on DigitalOcean.  So, I'm probably not much help on the matter right now I'm afraid.

**Comment by vijayendrabvs** [comment]
@nathanleclaire NP, thanks for the info. We can revisit this at a later time, and in the meantime, while I prefer that this ticket remains open to track this issue, if you prefer, you can close it or let me know and I can.

**Comment by aboch** [comment]
@vijayendrabvs  The feaures related to this ticket are no longer part of experimental build for few releases now. I am also aware they are currently used in AWS and other cloud hosting services and they work provided the proper ports are open for the control plane protocols.

Are you still seeing this issue, otherwise I'd suggest we close it. Thanks.

**Comment by thaJeztah** [comment]
I'll go ahead and close, but feel free to comment if you're still running into this
