### ISSUE TITLE
why does GET /containers/json return 'names' as array?

### ISSUE THREAD

**Issue by jgangemi** [docker/docker#14525]
could someone please provide some clarification on this b/c there is nothing docs on it. the `inspect' command returns it as a a string, so i am wondering if there is ever a case more then one name could be returned.

thanks!

**Comment by duglin** [comment]
See https://github.com/docker/docker/pull/14128#issuecomment-119383552  for more info.

**Comment by jgangemi** [comment]
@duglin thanks!
