### ISSUE TITLE
Daemon API fields not versioned correctly for v1.18

### ISSUE THREAD

**Issue by vbatts** [docker/docker#14524]
Version, Os, and KernelVersion are being returned even for `/v1.17/version` calls.

Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1241699

**Comment by duglin** [comment]
returning more fields are ok - or supposed to be.
See: https://docs.docker.com/reference/api/docker_remote_api/
`
The Remote API uses an open schema model. In this model, unknown properties in incoming messages will be ignored. Client applications need to take this into account to ensure they will not break when talking to newer Docker daemons.
`

**Comment by runcom** [comment]
@duglin but we're not so consistent with that statement https://github.com/docker/docker/blob/master/api/server/server.go#L255

**Comment by duglin** [comment]
Even if we do hide some fields for older clients that doesn't mean we have to do it in all cases  :-)  
The statement is just a heads up for client that we may not always be so nice - which I think is true is some cases.

**Comment by vbatts** [comment]
fair. though having a respected _versioned_ API is nice. ;-)

**Comment by thaJeztah** [comment]
I think we can close this, because it's described in https://docs.docker.com/engine/reference/api/docker_remote_api/ (could be slightly improved, perhaps):

> Docker’s Remote API uses an open schema model. In this model, unknown properties in incoming messages are ignored. Client applications need to take this behavior into account to ensure they do not break when talking to newer Docker daemons.
