### ISSUE TITLE
Docker build from private image not authorized?

### ISSUE THREAD

**Issue by ulimit** [docker/docker#14536]
We recently upgraded to docker 1.7 from docker 1.5 (yesterday). Now we're experiencing an odd issue, our docker builds can't pull our private images via dockerfile. CLI docker pulls work just fine though... Here's how to reproduce:
Note: bunchballdev is our company dockerhub group
#login
$ sudo docker login
Username: [username]
Password:
Email: stuff@example.com
WARNING: login credentials saved in /home/<homedir>/.docker/config.json
Login Succeeded

##the most basic dockerfile
$ cat Dockerfile
FROM bunchballdev/fedora
RUN echo "got here"

##building it responds with the error message that it doesn't exist, but also could be that I'm not authorized
$ sudo docker build .
Sending build context to Docker daemon 20.48 kB
Sending build context to Docker daemon
Step 0 : FROM bunchballdev/fedora
Pulling repository bunchballdev/fedora
Error: image bunchballdev/fedora:latest not found

##clearly it not only exists, but I'm authorized to pull it
$ sudo docker pull bunchballdev/fedora
latest: Pulling from bunchballdev/fedora
48ecf305d2cf: Pull complete
ded7cd95e059: Pull complete
08146ed4d2fb: Pull complete
d6683cfa8605: Pull complete
f7490fdf7bd6: Pull complete
33a9229518a7: Already exists
Digest: sha256:45df6c06cab4211fbfd730e608e7ef374c2fec8fb9ccd6b849ca46f3128965dc
Status: Downloaded newer image for bunchballdev/fedora:latest

##Just in case I'm an idiot and referencing a different base image
$ sudo docker build .
Sending build context to Docker daemon 20.48 kB
Sending build context to Docker daemon
Step 0 : FROM bunchballdev/fedora
 ---> 33a9229518a7
Step 1 : RUN echo "got here"
 ---> Running in f9175b949870
got here
 ---> 141398bf5586
Removing intermediate container f9175b949870
Successfully built 141398bf5586

soooooo, docker build is somehow using a different authfile than docker pull, but I don't see how that could be given the following:
https://github.com/docker/docker/blob/master/api/client/build.go#L281

Here's my specs:
$ sudo docker -D info
Containers: 0
Images: 242
Storage Driver: btrfs
 Build Version: Btrfs v4.0
 Library Version: 101
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.3-200.fc21.x86_64
Operating System: Fedora 21 (Twenty One)
CPUs: 4
Total Memory: 14.69 GiB
Name: <hostname>
ID: C3GX:NQYI:PVQJ:3YK3:K4WT:EMMF:PKEG:XNDG:QO6S:FKCS:62LI:5WQT
Username: <username>
Registry: https://index.docker.io/v1/

$ sudo docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609-dirty
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609-dirty
OS/Arch (server): linux/amd64

**Comment by ulimit** [comment]
Gordon you sly turtle. ;)
I checked the open issues and didn't find one corresponding to my problem.
uname -a
Linux <hostname> 3.19.3-200.fc21.x86_64 #1 SMP Thu Mar 26 21:39:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
running on AWS
steps to reproduce already included above
Other important info:
Code is compiled from source via the provided rpm build scripts. I am NOT using any RHEL patches.
https://github.com/docker/docker/tree/v1.7.0/contrib/builder/rpm
$ sudo yum list installed | grep docker
docker-engine.x86_64               1.7.0-0.0.20150618.050136.git0baf609.fc20
Due to reasons, we are using the fc20 version on a fc21 host. I don't think it matters, but let me know if it might.

**Comment by cpuguy83** [comment]
Hi, this is fixed in the upcoming 1.7.1 release (should be released on Tuesday).
You can test the latest RC here: https://github.com/docker/docker/pull/14264#issuecomment-120166928

**Comment by ulimit** [comment]
Thanks found it!
https://github.com/calavera/docker/commit/6906fb0693eabb2cb7b84b9cfbaf203b9f8e2b59
