### ISSUE TITLE
golang client for libnetwork

### ISSUE THREAD

**Issue by vijayendrabvs** [docker/docker#14538]
Is there a golang client library that supports libnetwork calls? The golang libraries listed on https://docs.docker.com/reference/api/remote_api_client_libraries/ don't have it yet.

I wasn't able to find an API spec for libnetwork - can someone point me to it at the earliest? I would be able to write the client wrappers based on that and contribute back to the existing golang libs.

**Comment by vijayendrabvs** [comment]
CC: @mavenugo @nathanleclaire

**Comment by jfrazelle** [comment]
this should be opened on the libnetwork repo itself
