### ISSUE TITLE
System error: open /proc/self/task/1/attr/exec: no such file or directory 

### ISSUE THREAD

**Issue by thecodethinker** [docker/docker#14532]
Every container I create that tries to mount a `VOLUME` gives me the error `System error: open /proc/self/task/1/attr/exec: no such file or directory`

I've tried changing to 2 older kernels, reinstalling docker, changing the base image, making a new dockerfile, and nothing is fixing it.

This ONLY shows up when I try creating a shared folder, but it happens every time.

The Dockerfile that causes the error
```
FROM alpine:latest # or ubuntu or fedora

RUN mkdir /app

ENTRYPOINT ["echo", "Hello, World"]
```

then I run 

`docker run -v"$(pwd):/app" <image_name>`

**Comment by thecodethinker** [comment]
I just found out it was a small typo on my part.

**Comment by thecodethinker** [comment]
Apparently it wasn't a typo. It happens seemingly randomly.

**Comment by thecodethinker** [comment]
This actually only happens when I'm using docker-compose. I'm going to open the same issue over there as well

**Comment by thaJeztah** [comment]
@thecodethinker did you create the issue in compose? If so, could you add the link to that issue here? Thanks!

**Comment by cpuguy83** [comment]
Ping?

Can you also provide output of `docker info` and `docker version`.
Do you have a reliable way to repro?
