### ISSUE TITLE
docker run --privileged mode errors, run strongswan inside container.

### ISSUE THREAD

**Issue by netskyline** [docker/docker#14550]
docker run --privileged mode errors, run strongswan inside container. these errors are reported：

Jul 11 03:13:47 sg2 kernel: [539237.172711] audit_printk_skb: 9 callbacks suppressed
Jul 11 03:13:47 sg2 kernel: [539237.172716] type=1400 audit(1436598827.277:266049): apparmor="DENIED" operation="getattr" info="Failed name lookup - disconnected path" error=-13 profile="/usr/lib/ipsec/charon" name="var/lib/docker/aufs/diff/fed62ecd54db79fbce8e66a6ba17fe2fafb71cec19c71f671b9fa85bdea6126c/usr/lib" pid=15021 comm="charon" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Jul 11 03:13:52 sg2 kernel: [539242.174548] type=1400 audit(1436598832.277:266050): apparmor="DENIED" operation="open" info="Failed name lookup - disconnected path" error=-13 profile="/usr/lib/ipsec/charon" name="var/lib/docker/aufs/diff/fed62ecd54db79fbce8e66a6ba17fe2fafb71cec19c71f671b9fa85bdea6126c/usr/lib/ipsec/libstrongswan.so.0.0.0" pid=15022 comm="charon" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Jul 11 03:13:52 sg2 kernel: [539242.174583] type=1400 audit(1436598832.277:266051): apparmor="DENIED" operation="getattr" info="Failed name lookup - disconnected path" error=-13 profile="/usr/lib/ipsec/charon" name="var/lib/docker/aufs/diff/fed62ecd54db79fbce8e66a6ba17fe2fafb71cec19c71f671b9fa85bdea6126c/usr/lib/ipsec" pid=15022 comm="charon" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Jul 11 03:13:52 sg2 kernel: [539242.174617] type=1400 audit(1436598832.277:266052): apparmor="DENIED" operation="open" info="Failed name lookup - disconnected path" error=-13 profile="/usr/lib/ipsec/charon" name="var/lib/docker/aufs/diff/fed62ecd54db79fbce8e66a6ba17fe2fafb71cec19c71f671b9fa85bdea6126c/etc/ld.so.cache" pid=15022 comm="charon" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Jul 11 03:13:52 sg2 kernel: [539242.174676] type=1400 audit(1436598832.277:266053): apparmor="DENIED" operation="getattr" info="Failed name lookup - disconnected path" error=-13 profile="/usr/lib/ipsec/charon" name="var/lib/docker/aufs/diff/fed62ecd54db79fbce8e66a6ba17fe2fafb71cec19c71f671b9fa85bdea6126c/lib/x86_64-linux-gnu" pid=15022 comm="charon" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Jul 11 03:13:52 sg2 kernel: [539242.174754] type=1400 audit(1436598832.277:266054): apparmor="DENIED" operation="getattr" info="Failed name lookup - disconnected path" error=-13 profile="/usr/lib/ipsec/charon" name="var/lib/docker/aufs/diff/fed62ecd54db79fbce8e66a6ba17fe2fafb71cec19c71f671b9fa85bdea6126c/usr/lib/x86_64-linux-gnu" pid=15022 comm="charon" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Jul 11 03:13:52 sg2 kernel: [539242.174797] type=1400 audit(1436598832.277:266055): apparmor="DENIED" operation="getattr" info="Failed name lookup - disconnected path" error=-13 profile="/usr/lib/ipsec/charon" name="var/lib/docker/aufs/diff/fed62ecd54db79fbce8e66a6ba17fe2fafb71cec19c71f671b9fa85bdea6126c/lib" pid=15022 comm="charon" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Jul 11 03:13:52 sg2 kernel: [539242.174849] type=1400 audit(1436598832.277:266056): apparmor="DENIED" operation="getattr" info="Failed name lookup - disconnected path" error=-13 profile="/usr/lib/ipsec/charon" name="var/lib/docker/aufs/diff/fed62ecd54db79fbce8e66a6ba17fe2fafb71cec19c71f671b9fa85bdea6126c/usr/lib" pid=15022 comm="charon" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Jul 11 03:13:57 sg2 kernel: [539247.177379] type=1400 audit(1436598837.281:266057): apparmor="DENIED" operation="open" info="Failed name lookup - disconnected path" error=-13 profile="/usr/lib/ipsec/charon" name="var/lib/docker/aufs/diff/fed62ecd54db79fbce8e66a6ba17fe2fafb71cec19c71f671b9fa85bdea6126c/usr/lib/ipsec/libstrongswan.so.0.0.0" pid=15023 comm="charon" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Jul 11 03:13:57 sg2 kernel: [539247.177435] type=1400 audit(1436598837.281:266058): apparmor="DENIED" operation="getattr" info="Failed name lookup - disconnected path" error=-13 profile="/usr/lib/ipsec/charon" name="var/lib/docker/aufs/diff/fed62ecd54db79fbce8e66a6ba17fe2fafb71cec19c71f671b9fa85bdea6126c/usr/lib/ipsec" pid=15023 comm="charon" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Jul 11 03:13:57 sg2 kernel: [539247.177491] type=1400 audit(1436598837.281:266059): apparmor="DENIED" operation="open" info="Failed name lookup - disconnected path" error=-13 profile="/usr/lib/ipsec/charon" name="var/lib/docker/aufs/diff/fed62ecd54db79fbce8e66a6ba17fe2fafb71cec19c71f671b9fa85bdea6126c/etc/ld.so.cache" pid=15023 comm="charon" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

**Comment by netskyline** [comment]
docker version 
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64


docker info
Containers: 1
Images: 18
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 20
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-52-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 490 MiB
Name: sg2
ID: ZJE5:VSAM:4URL:LJ5Y:5VJG:SQWD:AJAX:5XBR:NHWW:2ZS3:HTQ7:WBUK
WARNING: No swap limit support


uname -a
Linux sg2 3.13.0-52-generic #85-Ubuntu SMP Wed Apr 29 16:44:17 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bprodoehl** [comment]
This looks related to #5490.  My advice for now is to move the strongswan binaries in the container so that the host's AppArmor profiles no longer apply to them.  In your case, that could be something like moving /usr/lib/ipsec to /usr/local/lib/ipsec.  May take some jiggling after that to get the path and perhaps LD_LIBRARY_PATH to know where to look for everything, but relocation of affected binaries has proven way easier than actually disabling AppArmor on the host or maintaining a patched version of Docker to use the unconstrained profile mentioned in #5490.

**Comment by ewindisch** [comment]
We've gone back and forth on reverts for a fix for this, but we should be able to close this, especially as it's a dupe.

**Comment by netskyline** [comment]
Use --cap-add=all alternative --privileged option. It works.
