### ISSUE TITLE
Mac nginx example not fully working 

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#14558]
This issue transfer of https://github.com/docker/docs-base/issues/102

For me, it seems this link:

http://docs.docker.com/installation/mac/

doesn't fully work.  When using nginx, the SSL ports are not working (can't curl, telnet, etc.)

Also, some of the commands like under section "Mount a volume on the container" step 5 don't show any wrapping, so unless you know to look, you miss part of the command.  Aka, I only see:

docker run -d -P -v $HOME/site:/usr/share/nginx/html --name

When you should see

docker run -d -P -v $HOME/site:/usr/share/nginx/html --name mysite nginx

Clearly that could be a css browser issue, but in my latest Chrome, there is no eye candy to show the command goes long.

Regards.

Ron

**Comment by campoy** [comment]
This sounds like something I should be able to fix ... and I wanna be a contributor so:

#dibs !!
