### ISSUE TITLE
Rewrite Windows Installation for toolbox

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#14562]
Toolbox installation see [internal requirements](https://docker.atlassian.net/wiki/display/CORE/Docker+Toolbox+PRD)

**Comment by ahmetalpbalkan** [comment]
@moxiegirl is there a public copy of this wiki link?

**Comment by moxiegirl** [comment]
@ahmetalpbalkan Not currently. I've spoken with the project lead and given him your email.  You should hear from him shortly.

**Comment by jasonwilliams200OK** [comment]
Is this fixed by #15514?

**Comment by thaJeztah** [comment]
@jasonwilliams200OK yes, I think this can be closed, thanks!
