### ISSUE TITLE
Documentation: TOC links in Best Practices page links to reference instead of the heading

### ISSUE THREAD

**Issue by charleswhchan** [docker/docker#14573]
https://docs.docker.com/articles/dockerfile_best-practices

To the right of the page is a TOC listing the major headings "On this page:". The first half of the TOC is ok. The bottom half includes the best practices for commands (FROM, RUN, CMD, ... etc) and these links to the references. eg. https://docs.docker.com/reference/builder/#from instead of the actual heading/section on the page.

This behaviour makes it difficult to navigate and jump to the specific heading/section by using the TOC.

**Comment by vdemeester** [comment]
@charleswhchan Thank you for the report. Stumbled upon this few days ago, I'll submit a fix :wink:.

/cc @thaJeztah @moxiegirl
