### ISSUE TITLE
Execute external docker-* commands ala git

### ISSUE THREAD

**Issue by pugnascotia** [docker/docker#14585]
Ala git, it would be useful if, when docker is executed with an unrecognised subcommand `$CMD`, and a command exists on the `$PATH` name `docker-$CMD`, then docker executed that command, passing all arguments from the command line.

This would be useful for when you forget the hyphen in docker-compose or docker-machine, or if you want to write your own wrapped scripts and keep them docker-flavoured.

I've already tried this out on a branch, so I'm keen for feedback.

**Comment by LK4D4** [comment]
Sound like not very abstract thing. I think it's sorta plugins, which was proposed by @duglin

**Comment by duglin** [comment]
@pugnascotia @LK4D4 is referring to #13140 which will be looked at again in the go 1.5 timeframe so we can make sure we address you concerns then too.  Closing this to not hold on to lingering (non-actionable at this time) issues.
