### ISSUE TITLE
docker daemon fails silently due to incorrect iptables NAT kernel modules

### ISSUE THREAD

**Issue by asridharan** [docker/docker#14592]
Description of problem:
I am running docker daemon on Gentoo, on AWS. I am running Gentoo with a custom kernel. While configuring the kernel options looks like, by mistake, I had turned of the CONFIG_NF_NAT because of which the iptables_nat.ko module wouldn't load. Docker was failing to start cause when it launched the iptables -t NAT .... command iptables was failing and causing network connectivity issues to the instance on which it was running. 

I was able to figure out the problem by running docker in debug mode (docker -d --log-level=debug). However, I would expect docker to be able to log this failure in /var/log/docker.log, which would saved me a lot of time (initially I started suspecting there was a problem with the btrfs backend driver I was using).

When starting docker daemon should dectect if iptable is NAT capable or not. 

`docker version`:
Client version: 1.6.1
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 97cd073
OS/Arch (client): linux/amd64
Server version: 1.6.1
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 97cd073
OS/Arch (server): linux/amd64

`docker info`:
Containers: 0
Images: 0
Storage Driver: devicemapper
 Pool Name: docker-202:1-924875-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 305.7 MB
 Data Space Total: 107.4 GB
 Data Space Available: 47.35 GB
 Metadata Space Used: 733.2 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.88 (2014-08-05)
Execution Driver: native-0.2
Kernel Version: 3.14.14-gentoo
Operating System: Gentoo/Linux
CPUs: 2
Total Memory: 3.68 GiB
Name: stitchnetos-aws
ID: BJM2:HBTR:HS2Y:CHUD:BMUV:BM26:GB7J:K2FV:4FRK:22JN:VWCF:3DBM

`uname -a`:
Linux stitchnetos-aws 3.14.14-gentoo #3 SMP Sun Jul 12 23:31:41 PDT 2015 x86_64 Intel(R) Xeon(R) CPU E5-2666 v3 @ 2.90GHz GenuineIntel GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
Custom Gentoo EBS-backed AMI running on AWS. This is a PV-HVM AMI

How reproducible:
Should be reproducible every time. 

Steps to Reproduce:
1. Make sure that CONFIG_NF_NAT is turned off. This will lead to a missing nf_nat.ko module which in turn will not allow iptable_nat.ko to be loaded.
2. Start docker. It will fail to start
3. Check the /var/log/docker.log, there won't be any ERROR messages indicating something went wrong with docker. 
4. Try running docker in debug mode docker -d --log-level=debug and you should see docker going and getting stuck trying to install the NAT rules.

Actual Results:
No message in /var/log/docker.log

Expected Results:
Expect ERROR messages in /var/log/docker.log indicating the failures (or absence) of iptable NAT.  

Additional info:
The missing KERNEL config can be checked using the check_config.sh script, but in a production environment if there is a missing kernel module it might be harder to debug the issue, without apriori knowing that it is a problem with the kernel modules. Hence raising this issue to see if any checks and logs can be added to the docker daemon.

**Comment by LK4D4** [comment]
@asridharan Could you provide message from debug level pls?

**Comment by asridharan** [comment]
oddly, I am unable to reproduce the kernel config that caused this problem. It could be that I incorrectly edited the Kconfig leading to the issue. If I explicitly remove iptables NAT from the kernel, I can see iptables throwing and error and it being reflected in /var/log/docker.log:
ime="2015-07-13T18:45:47-07:00" level=info msg="+job init_networkdriver()" 
time="2015-07-13T18:45:47-07:00" level=warning msg="Running modprobe bridge nf_nat failed with message: , error: exit status 1" 
Unable to enable network bridge NAT: iptables failed: iptables --wait -t nat -I POSTROUTING -s 172.17.42.1/16 ! -o docker0 -j MASQUERADE: iptables v1.4.21: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
 (exit status 3)
time="2015-07-13T18:45:47-07:00" level=info msg="-job init_networkdriver() = ERR (1)" 


This is what I was expecting. Going to close this issue. Will re-open if I am able to reproduce this problem .
