### ISSUE TITLE
Move boot2docker documentation into a deprecated status

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#14598]
Make clear the boot2docker CLI is **deprecated** in the installation docs.  The iso is still part of everything.  Move the current installation documentation to the boot2docker repository.

**Comment by thaJeztah** [comment]
@moxiegirl I think this can be closed, or did you have other things that aren't covered yet?

**Comment by moxiegirl** [comment]
@thaJeztah Ah...this is closable. Thanks for pointing it out.
