### ISSUE TITLE
Docker Experimental Script Installs Docker 1.6.2 Stable on CentOS

### ISSUE THREAD

**Issue by kkirsche** [docker/docker#14590]
When running `wget -qO- https://experimental.docker.com | sh ` on CentOS 7, this installs `Docker version 1.6.2, build ba1f6c3/1.6.2`. Is there something I'm missing for experimental release installation?

**Comment by kkirsche** [comment]
1. Simply run `wget -qO- https://experimental.docker.com | sh` on CentOS 7
2. Do a `docker -v` to see this installed `Docker version 1.6.2, build ba1f6c3/1.6.2`.


`uname`: `Linux hidden.hostname.com 3.10.0-229.7.2.el7.x86_64 #1 SMP Tue Jun 23 22:06:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by Evalle** [comment]
Hello @kkirsche 
The configuration script at http://experimental.docker.com/ doesn’t seem to be adding any new repositories, all it is doing is running yum -y -q install docker-io. Also check this WIP link https://github.com/docker/docker/pull/13680

**Comment by thaJeztah** [comment]
@kkirsche the new apt and yum repos are now live;

http://blog.docker.com/2015/07/new-apt-and-yum-repos/

Could you test if this issue is resolved for you?

**Comment by kkirsche** [comment]
Will test that shortly. Thanks!

**Comment by kkirsche** [comment]
@thaJeztah no luck:

<img width="809" alt="screen shot 2015-07-27 at 6 16 22 pm" src="https://cloud.githubusercontent.com/assets/947110/8919230/ac6ec442-348b-11e5-9c94-7a6494e27758.png">

**Comment by thaJeztah** [comment]
@kkirsche hmmm, could you try

`wget -qO- https://experimental.docker.com | sudo sh`

To work around the permissions issue?

(You could use the manual install of course, using this URL for the repo http://yum.dockerproject.org/repo/experimental/centos/7/, but that's not the issue here)

**Comment by kkirsche** [comment]
@thaJeztah that worked. Sorry about that. I was basing that on what is in the `README.md` file in the experimental folder.

**Comment by jfrazelle** [comment]
oh i see the fix

**Comment by thaJeztah** [comment]
Thanks Jess!

**Comment by kkirsche** [comment]
... better communication would be appreciated for that rather than just "What error are you getting because this is not the correct fix" ...

**Comment by thaJeztah** [comment]
@kkirsche I'm sure it wasn't meant impolitely, it's a bit hectic right now, getting a lot of PRs reviewed and merged for the upcoming release; short comments like that are mostly due time constraints.

**Comment by kkirsche** [comment]
@thaJeztah it really doesn't come off that way and personally I don't feel it's a reasonable excuse honestly. Everyone is busy, we all have stuff to do and a ton of things to get done. Not everyone at docker is doing this out of love, and there is a full company behind your product (Docker Inc.). You really can't spend an extra five seconds to be a bit more complete with contributors in general and gain some positive sentiment?

**Comment by thaJeztah** [comment]
Really, I try to (and I know the other maintainers as well). I'm doing this in my spare time; slip-ups happen, so again, apologies.

**Comment by jfrazelle** [comment]
I apologize, just been churning through 100+ PRs today. It was not meant in
any way.

**Comment by kkirsche** [comment]
It happens, and I'm sure I came off as rude as well. And for that I want to apologize. I just feel personally as though my experience at least hasn't been the best with attempting to work with docker's repo and has left me nervous to recommend docker as a project to focus my or my team's resources on
