### ISSUE TITLE
Proposal refactor : Use dockerCmd to run docker commands in integration-cli tests

### ISSUE THREAD

**Issue by vdemeester** [docker/docker#14603]
As discussed a little bit on IRC, it would be cool if *almost* all cli integration test would use ``dockerCmd`` and the like.

This issue is there to list the files that need updates so we can share the work :wink:. I'll keep this list up-to-date when PRs will be merged. If you wanna work on this, please comment which file(s) you wanna work on, and I'll add your name :sweat_smile:.

If the test needs to check out that it errors out (``err != nil``) then do not use ``dockerCmd`` — but you could use something like : ``runCommandWithOutput(exec.Command(dockerBinary, "diff", ""))`` (like [here](https://github.com/docker/docker/pull/14500#discussion-diff-34479965)) or ``dockerCmdWithError`` (but you need to cherry-pick one of my commit : https://github.com/docker/docker/commit/4290bdefabc46d6faada968ef7ddba1d3c21dcca).

- [X] integration-cli/docker_cli_attach_test.go (vdemeester)
- [X] integration-cli/docker_cli_attach_unix_test.go (vdemeester)
- [X] integration-cli/docker_cli_build_test.go (vdemeester)
- [X] integration-cli/docker_cli_build_unix_test.go (vdemeester)
- [X] integration-cli/docker_cli_by_digest_test.go (vdemeester)
- [X] integration-cli/docker_cli_commit_test.go (vdemeester)
- [X] integration-cli/docker_cli_config_test.go (vdemeester)
- [X] integration-cli/docker_cli_cp_test.go (vdemeester)
- [X] integration-cli/docker_cli_create_test.go (vdemeester)
- [X] integration-cli/docker_cli_daemon_experimental_test.go (hqhq)
- [X] integration-cli/docker_cli_daemon_test.go (hqhq)
- [X] integration-cli/docker_cli_diff_test.go (hqhq)
- [X] integration-cli/docker_cli_events_test.go (hqhq)
- [X] integration-cli/docker_cli_events_unix_test.go (hqhq)
- [X] integration-cli/docker_cli_exec_test.go (hqhq)
- [X] integration-cli/docker_cli_exec_unix_test.go (hqhq)
- [X] integration-cli/docker_cli_experimental_test.go (hqhq)
- [X] integration-cli/docker_cli_export_import_test.go (hqhq)
- [X] integration-cli/docker_cli_help_test.go (hqhq)
- [X] integration-cli/docker_cli_history_test.go (hqhq)
- [X] integration-cli/docker_cli_images_test.go (hqhq)
- [X] integration-cli/docker_cli_import_test.go (hqhq)
- [X] integration-cli/docker_cli_info_test.go (hqhq)
- [X] integration-cli/docker_cli_inspect_test.go (hqhq)
- [X] integration-cli/docker_cli_kill_test.go (hqhq)
- [X] integration-cli/docker_cli_links_test.go (coolljt0725)
- [X] integration-cli/docker_cli_links_unix_test.go (coolljt0725)
- [X] integration-cli/docker_cli_login_test.go (coolljt0725)
- [X] integration-cli/docker_cli_logs_test.go (coolljt0725)
- [X] integration-cli/docker_cli_nat_test.go (coolljt0725)
- [X] integration-cli/docker_cli_network_test.go (coolljt0725)
- [X] integration-cli/docker_cli_pause_test.go (vdemeester)
- [X] integration-cli/docker_cli_port_test.go (vdemeester)
- [X] integration-cli/docker_cli_port_unix_test.go (vdemeester)
- [X] integration-cli/docker_cli_proxy_test.go (vdemeester)
- [X] integration-cli/docker_cli_ps_test.go (vdemeester)
- [X] integration-cli/docker_cli_pull_test.go (vdemeester)
- [X] integration-cli/docker_cli_push_test.go (vdemeester)
- [X] integration-cli/docker_cli_rename_test.go (HuKeping)
- [X] integration-cli/docker_cli_restart_test.go (HuKeping)
- [X] integration-cli/docker_cli_rmi_test.go (HuKeping)
- [X] integration-cli/docker_cli_rm_test.go (HuKeping)
- [X] integration-cli/docker_cli_run_test.go (HuKeping)
- [X] integration-cli/docker_cli_run_unix_test.go (HuKeping)
- [X] integration-cli/docker_cli_save_load_test.go (sunyuan3) (HuKeping)
- [X] integration-cli/docker_cli_save_load_unix_test.go (sunyuan3)
- [X] integration-cli/docker_cli_search_test.go (sunyuan3)
- [X] integration-cli/docker_cli_service_test.go (sunyuan3)
- [X] integration-cli/docker_cli_start_test.go (sunyuan3)
- [X] integration-cli/docker_cli_start_volume_driver_unix_test.go (sunyuan3)
- [X] integration-cli/docker_cli_stats_test.go (coolljt0725)
- [X] integration-cli/docker_cli_tag_test.go (coolljt0725)
- [X] integration-cli/docker_cli_top_test.go (coolljt0725)
- [X] integration-cli/docker_cli_version_test.go (coolljt0725)
- [X] integration-cli/docker_cli_wait_test.go (coolljt0725)
- <del>integration-cli/docker_test_vars_cli.go (coolljt0725)</del>

And API(s)
- [X] docker_api_attach_test.go (vdemeester)
- [X] docker_api_containers_test.go (vdemeester)
- [X] docker_api_events_test.go (vdemeester)
- [X] docker_api_exec_resize_test.go (vdemeester)
- [X] docker_api_exec_test.go (vdemeester)
- [X] docker_api_images_test.go (vdemeester)
- [X] docker_api_info_test.go (vdemeester)
- [X] docker_api_inspect_test.go (vdemeester)
- [X] docker_api_logs_test.go (vdemeester)
- [X] docker_api_network_test.go (vdemeester)
- [X] docker_api_resize_test.go (vdemeester)
- [X] docker_api_service_test.go (vdemeester)
- [X] docker_api_stats_test.go (vdemeester)
- [X] docker_api_test.go (vdemeester)
- [X] docker_api_version_test.go (vdemeester)

Feels like a lot :blush:.

*Notes*: We might want a ``dockerCmdWithStdin`` or some way to customize a bit (in ``docker_cli_build_test.go`` for example).

**Comment by vdemeester** [comment]
Taking a-b-c letters for now :smile:

**Comment by hqhq** [comment]
I'd like to help, let me take `d,e,f,g,h,i,j,k` :smile:

**Comment by LK4D4** [comment]
Haha :)
@hqhq @vdemeester We're so lucky to have such contributors.

**Comment by coolljt0725** [comment]
I'd like to  take the last 6 from `integration-cli/docker_cli_stats_test.go` to `integration-cli/docker_test_vars_cli.go`

**Comment by vdemeester** [comment]
@hqhq, @coolljt0725 Thanks, added you :smile:

**Comment by HuKeping** [comment]
I'd like to take ` integration-cli/docker_cli_rename_test.go` and `restart`

**Comment by vdemeester** [comment]
@HuKeping go it :)

**Comment by vdemeester** [comment]
@LK4D4 I've added a ``dockerCmdWithError`` (which is as simple as it can get : https://github.com/vdemeester/docker/commit/f9efe7fab2bf3df7061c386c9c9c48cefdb96a16#diff-56e050aac937f91b9152c08ee4f7517dR553), for the "I want to check the error" cases.

**Comment by HuKeping** [comment]
Will this `dockerCmdWithError` be merged? I think my change will depend on it

**Comment by hqhq** [comment]
Guys, I haven't started, but I think this work would be very simple replacement. Let's not split it into too many PRs, I think 4 or 5 PRs would be top. @HuKeping @coolljt0725 @vdemeester let's split all rest, WDYT?

**Comment by sunyuan3** [comment]
I would like to take the following.

docker_cli_save_load_test.go
docker_cli_save_load_unix_test.go
docker_cli_search_test.go
docker_cli_service_test.go
docker_cli_start_test.go
docker_cli_start_volume_driver_unix_test.go

**Comment by HuKeping** [comment]
OK @hqhq, I think I could take all `r`

**Comment by coolljt0725** [comment]
OK, I'll take all the `s`

**Comment by vdemeester** [comment]
@hqhq yes it's not that bad, it just takes some time (to re-run integration-cli, …). Some file are already using ``dockerCmd`` pretty well, other less.

For the "Let's not split it into too many PRs", I kinda agree :sweat_smile:. 5 it is, I'll update the list according to your comment.

@HuKeping I'll make a PR today, let's see how quick it's going in, but another way would be for your to add my fork as a remote and checkout my branch and go from there (but in this case, I'll have to rework my branch a bit :sweat_smile:).

@coolljt0725 & @sunyuan3 who's taking the ``s``'s then ? :stuck_out_tongue_closed_eyes:

**Comment by vdemeester** [comment]
I'm taking the ``p`` btw :smile:

**Comment by coolljt0725** [comment]
@vdemeester  @sunyuan3  take the `docker_cli_save_load_test.go
docker_cli_save_load_unix_test.go
docker_cli_search_test.go
docker_cli_service_test.go
docker_cli_start_test.go
docker_cli_start_volume_driver_unix_test.go`
and I take the rest

And I take the `l` and `n`

**Comment by vdemeester** [comment]
@coolljt0725 Perfect, we're good to go !

**Comment by vdemeester** [comment]
@HuKeping I've split my commit in two (one to add the ``dockerCmdWithError``, the other for the tests), so if you add my fork as a remote, you should be able to cherry-pick my commit into your branch and thus having ``dockerCmdWithError`` :wink:. (https://github.com/docker/docker/commit/4290bdefabc46d6faada968ef7ddba1d3c21dcca)

**Comment by HuKeping** [comment]
@vdemeester great!

**Comment by HuKeping** [comment]
hi, @vdemeester  the ` integration-cli/docker_cli_run_test.go` has not been finished yet, it was not in #14623 . I'm working on it and will post another pr. 
Maybe you should update the tasklist

**Comment by vdemeester** [comment]
ohh ok, will do :wink:

**Comment by vdemeester** [comment]
I guess now everything has been merged, we are done :wink: :smiley_cat:.
Thanks everyone :tada:.
