### ISSUE TITLE
log level should be warn if the msg is WARNING

### ISSUE THREAD

**Issue by gouyang** [docker/docker#14617]
Description of problem:
```time="2015-07-14T14:25:26+08:00" level=error msg="WARNING: No --storage-opt dm.thinpooldev specified, using loopback; this configuration is strongly discouraged for production use"```

The log level is error but msg is WARNING.

`docker version`:
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 9d26a07/1.6.0
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 9d26a07/1.6.0
OS/Arch (server): linux/amd64

`docker info`:
Containers: 0
Images: 0
Storage Driver: devicemapper
 Pool Name: docker-253:1-10750841-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 305.7 MB
 Data Space Total: 107.4 GB
 Data Space Available: 107.1 GB
 Metadata Space Used: 725 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93 (2015-01-30)
Execution Driver: native-0.2
Kernel Version: 4.0.7-300.fc22.x86_64
Operating System: Fedora 22 (Twenty Two)
CPUs: 4
Total Memory: 3.795 GiB
Name: ghua.nay.redhat.com
ID: YTXM:RTAQ:CV77:5DZG:MJN4:KIGR:QQAM:BLI5:ZR3Y:2DJQ:7FW2:CQMV

`uname -a`:
Linux  4.0.7-300.fc22.x86_64 #1 SMP Mon Jun 29 22:15:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
Fedora 22, Physical

How reproducible:
100%

Steps to Reproduce:
1. systemctl start docker
2. systemctl status docker

Actual Results:

Expected Results:
the log level should be `warn`

Additional info:

**Comment by cpuguy83** [comment]
Closing since this error doesn't appear to even exist anymore.
