### ISSUE TITLE
--net=host broken in windows client (starting a linux container)

### ISSUE THREAD

**Issue by mitchcapper** [docker/docker#14615]
I noticed some changes committed recently around the windows network code that may have broken this.   Running a container like:
docker run -t -i --net=host ubuntu bash
returns: docker: --net: invalid net mode: invalid --net: host.
in windows
but in linux you get the proper behavior of the container starting.

info:
Client:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   b58565e
 Built:        Sun Jul 12 21:13:50 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   5ca3e7c
 Built:        Tue Jul 14 01:16:14 UTC 2015
 OS/Arch:      linux/amd64

**Comment by cpuguy83** [comment]
ping @jhowardmsft

**Comment by jhowardmsft** [comment]
#dibs #mybad. This will be fixed by #14530 which I'm actively working on fixing the tests for today.

**Comment by mitchcapper** [comment]
It is good this is fixed in  #14530 however as that doesn't seem to be going to be integrated any time soon any time this breaking change could be backed out?  It completely breaks the windows client when trying to use with --net host

**Comment by jhowardmsft** [comment]
I'm pushing to get 14530 merged.

**Comment by jhowardmsft** [comment]
This should have been fixed a while back. @mitchcapper can you confirm please. Thanks. @thaJeztah

**Comment by mitchcapper** [comment]
Yep fixed.
