### ISSUE TITLE
Volumes left orphaned when not all refering containers use `-v`

### ISSUE THREAD

**Issue by jest** [docker/docker#14622]
[The docs][1] say that the volume will be removed when the last referring container uses `rm -v`. However, this doesn't happen when previously some containers were removed without `-v` switch:

```
$ docker create --name d1 -v /data busybox
$ docker create --name c1 --volumes-from d1 busybox
$ VOL=$(docker inspect -f '{{ index .Volumes "/data" }}' d1)
$ ls -d $VOL
/var/lib/docker/volumes/f2cf6f32f91fbf1d9778665c1b20ac09146f1b066c1f4d73746954b1ae66cb03/_data
$ docker rm c1
$ docker rm -v d1
$ sudo ls -d $VOL
/var/lib/docker/volumes/f2cf6f32f91fbf1d9778665c1b20ac09146f1b066c1f4d73746954b1ae66cb03/_data
```

`docker info`:
```
Containers: 3
Images: 61
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 67
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-22-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 8
Total Memory: 11.46 GiB
Name: pw-tp
ID: ZTDW:FI5G:NERJ:QYQB:6GWU:PTCK:AC7E:YAHH:G4L7:I45P:SLDC:ZLCU
WARNING: No swap limit support
```

[1]: https://docs.docker.com/userguide/dockervolumes/#creating-and-mounting-a-data-volume-container

**Comment by jest** [comment]
`docker version`:
```
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

`uname -a`:
```
Linux pw-tp 3.19.0-22-generic #22~14.04.1-Ubuntu SMP Wed Jun 17 10:03:13 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by cpuguy83** [comment]
Hi thanks for reporting.
This is a known issue with how volumes are accounted in Docker 1.7 and is fixed as part of #14242

**Comment by jest** [comment]
OK, thanks.

Out of curiosity, where is the "flag" present that keeps the volume not deleted even when the last container is removed with `-v`? Obviously not in containers; volumes also look ephemeral to me. Some internal bookkeeping?

**Comment by cpuguy83** [comment]
@jest Yes, in `volume/local`. Volumes are only incremented on `Create` and decremented on `Remove`. However `Remove` is only ever called if someone passed in `-v` to rm.

Restarting the daemon would resolve this issue for you, since this is all kept in memory only.

**Comment by jest** [comment]
OK, I see. So restarting the daemon before the last `rm -v` is a workaround.

**Comment by cpuguy83** [comment]
Closing as this is now fixed.
