### ISSUE TITLE
Builder - Build-time argument passing (e.g., HTTP_PROXY)

### ISSUE THREAD

**Issue by icecrime** [docker/docker#14634]
# Description

In the past, we refused pull requests which were basically allowing to inject environment variables or such through the command line as it makes it too easy to write a Dockerfile which would only build assuming you know what it expects. We believe this would hinder repeatability of builds.

Nevertheless, there is a real need for build-time argument passing, one example which we often get being `HTTP_PROXY`. We believe Docker should have a predefined set of general purpose build-time variables it allows to override like this one, as well as a Dockerfile instruction allowing to define image-specific ones.

# How to

The best description of the solution is described here https://github.com/docker/docker/pull/9176#issuecomment-115879217. However, we would still like to prioritize client-side build (#14298) before moving on to this feature.

To give a few more details:
- Introduce a new `ARG` Dockerfile instruction that defines a build-time argument. The instruction take the name of the argument, a default value (which can be empty), and an optional description.
- Introduce an internal list of builtin, Engine-provided, build arguments. In a first version, the set of predefined arguments will be `HTTP_PROXY`, `HTTPS_PROXY`, `FTP_PROXY`, and `NO_PROXY`.
- Introduce a new `--build-arg` command-line flag to `docker build` that will receive argument values (e.g., `docker build --build-arg HTTP_PROXY=http://...`) in a similar way that `docker run -e` works today.
- Build-time arguments will not be persisted into the resulting image.
- Build-time arguments are injected in the environment of commands being `RUN`'ed as part of the build.
- Build-time arguments are available as substitution throughout the Dockerfile (for example, they can be used as part of an `ENV` instruction).

# What's next

Ping @duglin for review.
Ping @mapuri: we'd really appreciate if you could close your original PR and submit a rebased version of it that implements the spec described here. Thanks again for your patience :+1:

Tentatively adding this to the 1.9.0 milestone.

**Comment by marcellodesales** [comment]
Expectations
----
@icecrime I think you definitely gave a great summary about the importance of this feature... As  (#14298) is prioritized, do you see (#9176) also making their way to Docker 1.8??? I've been waiting for this feature for such a long time and it is blocking the development of a Docker Registry + Builder solution, for instance. 

CI Servers in mind
-------

Our worker hosts are behind the `HTTP_PROXY` and `NO_PROXY`, no HTTP connection at all from outside world... So, ALL of our Docker builds must depend on Images that are behind one of our Docker Registries. That is, all of the images depend on a parent that we host. Engineers trying out Docker for the first time usually complain about the inability of getting a Docker file from the public Registry and building it locally. 

As we own our builder machines (those that runs "docker builds" upon git merge of a GitHub Enterprise environment), we could easily be augmenting the default build steps with the Host's options, which would include the HTTP_PROXY related environment variables automatically. All because YUM, NPM, MAVEN etc would need those variables in order to properly load dependencies.

Thanks and I would love get this ASAP...

**Comment by icecrime** [comment]
Added more details, and tentatively adding to 1.9.0 milestone.

**Comment by mapuri** [comment]
@icecrime thanks for pinging me. 

At a high level, as I understand, this spec adds to #9176 a new `ARG` primitive to validate the passed `--build-arg` flags against.

I can start looking at changes to rebase my patch to this new spec. I will close #9176 and update this thread as I make progress. Just FYI, I will need a few cycles to scope the work and prioritize this among my other things so it might be a bit slow. Looking forward to contribute.

**Comment by icecrime** [comment]
@mapuri No problem at all, thank you so much for your understanding here. We will fix this ;-)

**Comment by thaJeztah** [comment]
@icecrime I think this will replace https://github.com/docker/docker/issues/4962 as well?

**Comment by icecrime** [comment]
@thaJeztah Yes!

**Comment by jgreat** [comment]
I have another use case for the ability to inject environment variables at build time: credentials.  

We use docker to containerize our private apps. A lot of these apps need access to private package repositories like npm and github at build time. At this time the only way reasonable way to provide these credentials in an automated build is to include a file in the code repository. This isn't an ideal solution.   

Having the ability to pass in an api key or username/password at build time is a feature I've been waiting for a long time.

**Comment by icecrime** [comment]
Build time secrets are an entirely different topic.

**Comment by mapuri** [comment]
@icecrime  @duglin

just FYI I created the PR #15182 to address the requirements for `ARG` and `--build-arg`

PTAL when you get a chance.

**Comment by igorescobar** [comment]
:+1:

**Comment by flower-pot** [comment]
:+1: This is also very useful to only include development and test dependencies when actually required, allowing them to be excluded in official images, which are used in production.

**Comment by tpires** [comment]
+1

In some cases you have some Dockerfiles to support similar environments in which it just differs on the datasource, db_host, etc.

**Comment by jacoelho** [comment]
:+1:

**Comment by thaJeztah** [comment]
@tpires that more sounds like *runtime* configuration of a *container*, not something that is needed during *build*; you should be able to use environment variables for that. (e.g `docker run -e db_host=db1.example.com my-image`)

**Comment by tpires** [comment]
@thaJeztah On Wildfly 8.x I need to add datasource(s) and for that I need to point it to one host. For now I've defined it as ${env.DB_HOST} and on the Dockerfile I've set ENV DB_HOST <ip-address>. But that host needs to exist and running my db. If I could pass that argument on build I could omit  db_host, db_password, etc.

**Comment by xenoterracide** [comment]
I would like this to be available to `ADD` as well. I'm currently in a low bandwidth environment and what I'm trying to do is.

~~~
ENV FILENAME apache-archiva-$VERSION-bin.tar.gz
ENV MIRROR_ROOT http://archive.apache.org/dist/archiva/$VERSION/binaries/

ADD $MIRROR_ROOT/$FILENAME /opt
~~~

and I have a download of the file on my local filesystem, but that same build wouldn't work in a CI environment (I also wouldn't want to commit the tarball).

**Comment by duglin** [comment]
@xenoterracide I think this is a slightly different issue since you're asking for env var substitution on the `ADD` command, which isn't really related to this `ARG` stuff. I would suggest you open up an issue for it but keep in mind that per https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax it might be postponed (or rejected for now).

**Comment by xenoterracide** [comment]
@duglin I suppose I can do that, but it seems like the same thing, I need to define a build argument, but I want to do it for an `ADD`

**Comment by mapuri** [comment]
@duglin I think we can do what @xenoterracide is looking for with `ARG` (as build-args will work with variable substitution as well with changes proposed in #15182), please correct if I got it wrong:

```
> VERSION="v1.0" docker build --build-arg FILENAME=apache-archiva-$VERSION-bin.tar.gz --build-arg MIRROR_ROOT=http://archive.apache.org/dist/archiva/$VERSION/binaries/ < EOF

ARG FILENAME
ARG MIRROR_ROOT

ADD $MIRROR_ROOT/$FILENAME /opt
EOF
```

**Comment by duglin** [comment]
Ah, sorry, yes I know that ARG would work ok but what I forgot was that ADD supported env var substitution already - I thought we'd need to add it to the list of cmds.

**Comment by xenoterracide** [comment]
There is an additional problem for what I want to do, #16085, local and remote adds don't behave in a consistent way when dealing with tarballs

**Comment by calavera** [comment]
Closing this now that #15182 has been merged!

Thank you @mapuri :metal:

**Comment by flower-pot** [comment]
Nice! So we can expect to see it in the 1.9.0 release?

**Comment by calavera** [comment]
@flower-pot yep.

**Comment by nuttycom** [comment]
Just a quick question - I'm looking for a way to be able to use the output of $(git describe) as the version number in a FROM clause, so that I don't have to change my Dockerfile each time that I want to release a new version of a pair of related containers. Is this newly added functionality suitable for this purpose?

**Comment by duglin** [comment]
@nuttycom I don't think there's a way to do that via a Dockerfile command. I think the only option is to run the git command on your 'docker build' command line and pass the output to a '-e' flag.
Something like:
```
docker build -e myVar=$(git ...) ...
```

**Comment by adamkdean** [comment]
I think we definitely need the ability to provide runtime variables to the build process via the `-e` flag.

I should not have to use `sed`.

**Comment by mapuri** [comment]
sorry for a late response.

@adamkdean 
I think the current limitation comes from the fact that variable substitution is not supported for the `FROM` instruction in Dockerfile (https://docs.docker.com/reference/builder/#environment-replacement). Otherwise following would have been possible with the `--build-arg` flag in `docker build`, which I assume what @nuttycom is looking for, please correct me if I misunderstood.

```
$ docker  build --build-arg Version=$(git ...) - <<EOF
ARG Version
FROM base_image.${Version:-"default_version"}
...
...
EOF
```

@duglin 
>  I think the only option is to run the git command on your 'docker build' command line and pass the output to a '-e' flag.

I might have missed this but is `-e` flag something that is being added to `docker build`? If not do you think it will be a good idea to support substitution for the `FROM` instruction? I can't think much gotchas with that other than the current requirement of `FROM` being the first instruction of the docker file (https://docs.docker.com/reference/builder/#from) which is violated by my example Dockerfile above.

**Comment by donny-dont** [comment]
@icecrime did you also include the snake case versions? Some things like apt-get and wget seem to want http_proxy and ignore HTTP_PROXY. This is what I was seeing when we were getting our Drone servers to build out docker images behind a proxy.

**Comment by thaJeztah** [comment]
@donny-dont both uppercased and lowercased are supported

**Comment by donny-dont** [comment]
@thaJeztah sounds good thanks for the speedy response :+1:

**Comment by neciu** [comment]
Cool! :+1:

**Comment by na-g** [comment]
@mapuri While I can't speak for @nuttycom, your interpretation of his request is exactly what I am looking for.  I need to build containers for multiple architectures, and the only difference between the builds is which base image is used.

**Comment by himikk** [comment]
I find issue when use external argument defined by ARG with EXPOSE when pass more than one port number:

Dockerfile:
```
FROM busybox
ARG EXPOSED_PORTS
RUN echo ${EXPOSED_PORTS}
EXPOSE ${EXPOSED_PORTS}
```
$ docker build --build-arg EXPOSED_PORTS="10001 10002" -t test .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM busybox
 ---> c51f86c28340
Step 2 : ARG EXPOSED_PORTS
 ---> Using cache
 ---> 38b1bdfbf3aa
Step 3 : RUN echo ${EXPOSED_PORTS}
 ---> Running in 576441131c49
10001 10002
 ---> 2a4f56d378b6
Removing intermediate container 576441131c49
Step 4 : EXPOSE ${EXPOSED_PORTS}
**Invalid containerPort: 10001 10002**
pro:test himik$ cat Dockerfile 
FROM busybox
ARG EXPOSED_PORTS
RUN echo ${EXPOSED_PORTS}
EXPOSE ${EXPOSED_PORTS}

**Comment by thaJeztah** [comment]
@himikk can you open a new issue for that, and "ping" me there? thanks!

**Comment by himikk** [comment]
Thank for fast response, @thaJeztah 
Done: docker/docker#17781

**Comment by thaJeztah** [comment]
Thanks!

**Comment by marcellodesales** [comment]
Hi @thaJeztah 

Is there a `docker-compose` instruction for the `--build-arg` when building images?

**Comment by flower-pot** [comment]
IMO this should be part of the compose specification and allow interpolating values in the file. Just my 2 cents.

**Comment by cpuguy83** [comment]
@flower-pot That would be best discussed in github.com/docker/compose.

**Comment by marcellodesales** [comment]
For those depending on using an HTTP proxy, make sure to use both the upper-case and lower-case versions of it... Wget, Curl or any other app will use either version and you may think this feature is not working... I was using HTTP_PROXY in upper-case, and wget only reads `http_proxy`.

Dockerfile with Wget calls
-----

The dockerfile here makes the same wget call.

```
FROM richxsl/rhel7
MAINTAINER Marcello_deSales@intuit.com

# Utilities
RUN yum install -y install unzip wget
RUN echo $HTTP_PROXY \
    && cat /etc/resolv.conf \
    && cd tmp \
    && wget -qO jdk8.tar.gz \
       --header "Cookie: oraclelicense=accept-securebackup-cookie" \
       http://download.oracle.com/otn-pub/java/jdk/8u65-b17/jdk-8u65-linux-x64.tar.gz \
    && tar xzf jdk8.tar.gz -C /opt \
    && mv /opt/jdk* /opt/java \
    && rm /tmp/jdk8.tar.gz \
    && update-alternatives --install /usr/bin/java java /opt/java/bin/java 100 \
    && update-alternatives --install /usr/bin/javac javac /opt/java/bin/javac 100

# Define commonly used JAVA_HOME variable
ENV JAVA_HOME /opt/java
```

Build
-----

We have Docker images builder hosts that need to supply all the different alternatives of HTTP Proxy environment variables for Java, Node.js and other apps. Our environment:

* Internal RPM repos
* HTTP Proxy to download external endpoints.
* Supply Upper-case and Lower-case HTTP_PROXY variables.

For this example, we download RPM dependencies but some people still download binaries from external resources like the Java binary.

```
[root@pppdc9prda2y java]# docker build 
  --build-arg https_proxy=$HTTP_PROXY --build-arg http_proxy=$HTTP_PROXY 
  --build-arg HTTP_PROXY=$HTTP_PROXY --build-arg HTTPS_PROXY=$HTTP_PROXY 
  --build-arg NO_PROXY=$NO_PROXY  --build-arg no_proxy=$NO_PROXY -t java .

Sending build context to Docker daemon 8.704 kB
Step 1 : FROM dockerhub.corp.intuit.net/intuit/base
 ---> 1e39a8af64bc
Step 2 : MAINTAINER Marcello_deSales@intuit.com
 ---> Using cache
 ---> 6f2a336c2200
Step 3 : RUN yum install -y install unzip wget
 ---> Using cache
 ---> 11b63146be8e
Removing intermediate container c47a53b63bfd
Step 4 : RUN echo $HTTP_PROXY     && cat /etc/resolv.conf     && cd tmp     && wget -qO jdk8.tar.gz       --header "Cookie: oraclelicense=accept-securebackup-cookie"       http://download.oracle.com/otn-pub/java/jdk/8u65-b17/jdk-8u65-linux-x64.tar.gz     && tar xzf jdk8.tar.gz -C /opt     && mv /opt/jdk* /opt/java     && rm /tmp/jdk8.tar.gz     && update-alternatives --install /usr/bin/java java /opt/java/bin/java 100     && update-alternatives --install /usr/bin/javac javac /opt/java/bin/javac 100
 ---> Running in a17deb64529d
 ---> 67d2c137dd50
Removing intermediate container a17deb64529d
Step 5 : ENV JAVA_HOME /opt/java
 ---> Running in f0dc2f7d6f8f
 ---> 2bdac22ad493
Removing intermediate container f0dc2f7d6f8f
Successfully built 2bdac22ad493
```

Not sure why wget does not work even if the HTTP_PROXY is visible during build :( Any clues?

**Comment by dkirrane** [comment]
Is there an open issue to to support passing build-args from Docker Compose? Or is this already supported?

**Comment by dkirrane** [comment]
Never-mind found it:
https://github.com/docker/compose/issues/2111
https://github.com/docker/compose/issues/2163

**Comment by otheus** [comment]
@thaJeztah  The most useful one would be `ALL_PROXY`

**Comment by thaJeztah** [comment]
@otheus hadn't heard of that one; how standard is it? If it's widely used, feel free to open a separate feature request

**Comment by otheus** [comment]
@thaJeztah ALL_PROXY is supported in curl since... well, the changelog doesn't mention, but mailing lists indicate at least since 2008. https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html  (mailing list discussion https://curl.haxx.se/mail/archive-2008-01/0044.html )

Do we need a separate feature request to amend a bugfix?

**Comment by thaJeztah** [comment]
@otheus there's more than cURL, but please open a new issue to suggest adding `ALL_PROXY` to the default list of supported args

**Comment by junneyang** [comment]
does the ARG support **default parameter**?
eg:
ARG PARAM1 123456
ARG PARAM2 654321

thanks for your help!

**Comment by otheus** [comment]
@thaJeztah done: https://github.com/docker/docker/issues/21319

**Comment by alvinchevolleaux** [comment]
Is there some sort of prompt option when building a Docker image? I don't really like passing passwords in cleartext via command line. An prompt option in the build process would also make building more interactive and self explanatory without the user needing to be aware of many command line arguments before building. Of course for automated builds you could just pass some no prompt flag.

**Comment by VonC** [comment]
@alvinchevolleaux Sure, use docker-compose (1.6 with docker 1.10), and environment variables: http://stackoverflow.com/a/36084324/6309

**Comment by alvinchevolleaux** [comment]
@VonC But with this method you still need to write your password in cleartext right? And then you'll need to be sure to clear your history, etc. I meant a method where you can use a password prompt instead of setting env variables. I'm thinking of where I want to set the root password for a database container for example.

**Comment by VonC** [comment]
@alvinchevolleaux I don't know about a prompt method. For the rest, you are back to the old "[Secrets: write-up best practices, do's and don'ts, roadmap](https://github.com/docker/docker/issues/13490)" debate. Last proposal: https://github.com/docker/docker/issues/13490#issuecomment-191977167, using `shsh exec`: https://github.com/realestate-com-au/shush#use-as-a-command-shim

**Comment by DanielDent** [comment]
Currently, when a build-arg is used that was not specified in the Dockerfile, Docker fails the build with "One or more build-args were not consumed, failing build."

I'm using build-args to inject local proxies/mirrors in a CI build environment. While HTTP_PROXY and friends are covered by being allowed by default, NPM_CONFIG_REGISTRY, HEX_MIRROR, and similar variables for other package managers are not.

It would be nice to be able to inject environment variables for all supported package managers without needing to worry about if a particular build is using that build argument.

I don't entirely understand why this check exists. No similar check is done to see if a runtime environment variable is 'allowed' by a Dockerfile.

If there is a good reason for maintaining this restriction, perhaps a --build-arg-optional could be provided which does not fail if the ARG wasn't specified in the Dockerfile.

**Comment by thaJeztah** [comment]
@DanielDent please open a new issue; commenting on a closed issue is usually not the best for new feature requests

**Comment by innocentme1** [comment]
@icecrime I saw your previous comment saying "Build time secrets are an entirely different topic.". I am not clear on this point. ARG variables are not persistent in final images as ENV variables, so whats wrong in using them for passing secrets. Even the ARG documentation says that this cannot be used for passing secrets. - I am not sure why it cannot be used?  Can you or someone please clarify? 

Is ARG designed for passing variables like proxy etc. which are "only" needed/used for building images and not needed later? If yes - can't we just expand this for secrets too?  Are these ARG's by anyway stored in final images?

**Comment by hairyhenderson** [comment]
@innocentme1 - while build args aren't persisted in the runtime environment, they _are_ persisted in the image's metadata. See the output from `docker history` or `docker inspect` on an image built with these.

Also, I issued #24522 earlier to clarify the docs on this point :grin:

**Comment by innocentme1** [comment]
@hairyhenderson makes sense now. Thank you :D

**Comment by rupakg** [comment]
@mapuri I see your comments from 9/25/15 above to @adamkdean question.

```
I think the current limitation comes from the fact that variable substitution is not supported for the FROM instruction in Dockerfile (https://docs.docker.com/reference/builder/#environment-replacement). Otherwise following would have been possible with the --build-arg flag in docker build, which I assume what @nuttycom is looking for, please correct me if I misunderstood.

$ docker  build --build-arg Version=$(git ...) - <<EOF
ARG Version
FROM base_image.${Version:-"default_version"}
...
EOF
```

I have a very similar use case as above.

Is there a resolution or plan to include ARG replacement in the FROM instruction? Is it because FROM has to be the first instruction that ARG cannot be supported for FROM?

Apart from var replacement solutions outside of docker (like using sed etc.), is there a way that others are doing it? Any feedback is appreciated.

**Comment by nuttycom** [comment]
@rupakg I did ultimately find a simple workaround for this - ARG values *are* substituted into RUN evaluation, so I'm now doing basically this:

```

**Comment by rupakg** [comment]
@nuttycom Thanks for your comment. I need ARG replacement for the FROM instructions which is purely a 'build' req. Maybe I am missing what you did? Can you show me an example of ARG with FROM? I would really appreciate it.

**Comment by nuttycom** [comment]
@rupakg Ah, now that I recall correctly, what I've been doing recently is actually something different from what I'd initially requested here. Sorry for the confusion.

**Comment by nuttycom** [comment]
@rupakg However, a combination of our approaches could work - what if you just used a Makefile (as I'm doing) and then used sed to replace the version number in the Dockerfile being streamed in via your `<<` clause?

**Comment by rupakg** [comment]
@nuttycom Yeah, sed works fine. ARG is much cleaner but not supported. Thanks again.
