### ISSUE TITLE
Add --is-existed option for docker rm/rmi commands

### ISSUE THREAD

**Issue by yeasy** [docker/docker#14649]
When the image/container does not exist, those commands will result in errors.

Add this option can ignore this error, and only do the deletion when the image/container exists.

**Comment by cpuguy83** [comment]
-1 (and I think we've discussed this before).
The CLI doesn't exit on error here, it just sends the error to stderr.
It does exit with a non-zero value... but it should exit with a non-zero value, you asked it to delete things that don't exist.

If you need super fine-grained control you should use the API directly.

**Comment by duglin** [comment]
For reference: #13855

**Comment by thaJeztah** [comment]
@duglin I see https://github.com/docker/docker/pull/13855 was rejected. Should this be closed, or are you planning on re-implementing it, using `-f`?

**Comment by duglin** [comment]
yes for consistency we should close this too ( will do so now ), even though I disagree with the decision.
