### ISSUE TITLE
Provide reporting mechanism for images which break with "Error pulling image gzip: invalid header stdout"

### ISSUE THREAD

**Issue by alberto56** [docker/docker#14656]
Periodically, an image that worked previously can no longer be pulled from the Docker hub because of an "invalid header".

It has happened once before to me, and after two days was "fixed", but with "FROM dockerfiles/centos-lamp", for example, I have been stuck for five days.

To make sure the problem is with the Docker hub, I have created a very simple github repo https://github.com/alberto56/test20150715091543 which contains only a Dockerfile FROM dockerfiles/centos-lamp, and a circle.yml file which builds it. I ran this locally on the latest version of CoreOS (738.1.0) and the problem persists:

    core@core-01 ~/share/test20150715091543 $ docker build .
    Sending build context to Docker daemon 3.072 kB
    Sending build context to Docker daemon 
    Step 0 : FROM dockerfiles/centos-lamp
    Pulling repository dockerfiles/centos-lamp
    666d59f8429d: Error pulling image (latest) from dockerfiles/centos-lamp, endpoin666d59f8429d: Error pulling image (latest) from dockerfiles/centos-lamp, ApplyLayer gzip: invalid header stdout: {"layerSize":300550566}
    INFO[0058]  stderr:                                     

The same problem also occurs on other projects with use dockerfiles/centos-lamp on the CircleCI continuous integration tool, for example https://circleci.com/gh/dcycleproject/dcyclebox/67

In a continuous delivery workflow, this can be a major impediment.

For the record, I have also tried running `docker build --pull=true .` to no avail.

According to the output, the image `666d59f8429d` is broken on the Docker hub as of today.

My feature request is this: provide a **reporting mechanism** for broken images, something like:

    docker report 666d59f8429d

This would trigger a script on Docker hub which would simply attempt to build that image, and if it fails, repair it.

In addition, it might be good for maintainers of images to be able to rebuild broken images, so if the maintainer of dockerfiles/centos-lamp is told that the image is broken, for example with https://github.com/dockerfiles/centos-lamp/issues/1, the maintainer might run a script like:

    docker push --rebuild=true ...

or something like that.

**Comment by alberto56** [comment]
This might have to do with the tag 6.4 no longer available for centos:

See the output at https://circleci.com/gh/alberto56/test20150715091543/2

in which case the error seems cryptic:

    666d59f8429d: Error pulling image (latest) from dockerfiles/centos-lamp, endpoin666d59f8429d: Error pulling image (latest) from dockerfiles/centos-lamp, ApplyLayer gzip: invalid header stdout: {"layerSize":300550566}
    INFO[0058]  stderr:

Perhaps an error like this might make more sense:

    Error: cannot build 666d59f8429d because a required intermediate image (centos:6.4) has been removed from the Docker hub.

**Comment by cpuguy83** [comment]
I just reported this to support.docker.com

I'm not sure why centos 6.4 is missing (other than of course it's tremendously out of date and shouldn't be used...), since I don't believe the Hub team generally removes images.

Also I would not recommend building images from this user.

**Comment by unclejack** [comment]
All the available tags of the centos image can be found at https://registry.hub.docker.com/_/centos/tags/manage/. There's no `6.4` tag there.

**Comment by metalivedev** [comment]
@alberto56 let's move this over to https://forums.docker.com/c/all-things-docker-hub so we're not bothering the open source team here on docker/docker.

Would you like me to copy this conversation so far over there (but it will appear as if I'd written it), or would you like to bring it over (so it stays with your name)?

/Andy Rothfusz
Docker Support

**Comment by alberto56** [comment]
@metalivedev thanks, I added this to https://forums.docker.com/t/better-error-message-when-a-required-image-has-been-deleted-from-the-hub/2456
