### ISSUE TITLE
Permission denied for loading the config.json

### ISSUE THREAD

**Issue by killercentury** [docker/docker#14669]
Once I upgraded to Docker 1.7, I got following warning message when I run docker on Jenkins CI. (The jenkins user is inside the docker group already.)
```
WARNING: Error loading config file:stat /root/.docker/config.json: permission denied
```
There is no config.json existing, and I don't need this file as well. This only happens when I run the build on Jenkins. But if I run the same thing under the same user manually, I won't get this warning. Just be curious about why it reports permission denied when I don't have this file.

docker version:
```
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```

**Comment by tiborvass** [comment]
@killercentury most likely the problem is that docker is running in a container as root, hence the homedir is `/root` but the jenkins user does not have permissions to access `/root/.docker`, so regardless of whether `/root/.docker/config.json` exists, it errors out. And something must be different when you try it manually.

I am not sure whether we want to skip the error if permissions are denied. /cc @duglin

**Comment by dennisgermany** [comment]
Hi I think I have the same/similar problem:
When I try to login into my private docker registry within a Jenkins build via:
docker login -u dennis -p dennis reg:5000
I get:
WARNING: Error loading config file:stat /root/.docker/config.json: permission denied
Error saving config file: mkdir /root/.docker: permission denied

But when I do this via command line and user jenkins there is no error

docker version
-----------------------------
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64

docker info
---------------------------------
Containers: 0
Images: 29
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 29
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-52-generic
Operating System: Ubuntu 14.04.2 LTS (containerized)
CPUs: 1
Total Memory: 994 MiB
Debug mode (server): true
File Descriptors: 9
Goroutines: 16
System Time: 2015-07-16T22:19:58.205560688Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker

**Comment by duglin** [comment]
try specifying a different config dir - ala: https://github.com/docker/docker/pull/12856

**Comment by dennisgermany** [comment]
via command line
docker login -u dennis -p dennis reg:5000
I get 
WARNING: login credentials saved in /var/lib/jenkins/.docker/config.json
but in combination with jenkins, docker wants to to something with /root

**Comment by duglin** [comment]
@dennisgermany in the variant where it works, what user are you when you run the docker command and who owns the $HOME dir ?

**Comment by dennisgermany** [comment]
I'm using Docker in Docker via the following image: killercentury / jenkins-dind

In the variant where it works...

1.) ssh my machine
2.) start docker in docker container
3.) docker -i -t exec mydockerindocker "/bin/bash"
4.) change to jenkins user: su jenkins
5.) login into my private registry (that is also a docker container via shared via link): docker login -u dennis -p dennis reg:5000 

output: 
WARNING: login credentials saved in /var/lib/jenkins/.docker/config.json
Account created. Please see the documentation of the registry http://reg:5000/v1/ for instructions how to activate it.

HOME_DIR: /var/lib/jenkins
drwxrwxrwx 12 jenkins jenkins 4096 Jul 18 07:52 jenkins

**Comment by dennisgermany** [comment]
I just solved the problem.
The docker image "killercentury / jenkins-dind" starts jenkins via "supervisor". But supervisor does override the environment variable for HOME by default. HOME was still set to root's HOME even though running as user jenkins.

Solution: Modify the supervisor config in:
/etc/supervisor/conf.d/supervisord.conf
and add for jenkins: environment=FOO=JENKINS_HOME="/var/lib/jenkins",HOME="/var/lib/jenkins",USER="jenkins"
