### ISSUE TITLE
Centos7 1.7.1 not honouring other_args flag in systemctl 

### ISSUE THREAD

**Issue by numanoids** [docker/docker#14663]
I installed the 1.7.1 rpm on a new centos7 system and created a couple of logical devices for data and metadata storage. I added the relevant arguments to the other_args section in /etc/sysconfig/docker, cleared out existing storage and restarted the daemon. 

other_args="-G docker -s=devicemapper --storage-opt dm.datadev=/dev/vg01/data --storage-opt dm.metadatadev=/dev/vg01/meta"

Docker info reports:

root@centosdocker1 ~]# docker info
Containers: 0
Images: 0
Storage Driver: devicemapper
 Pool Name: docker-253:0-89742-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 307.2 MB
 Data Space Total: 107.4 GB
 Data Space Available: 9.609 GB
 Metadata Space Used: 729.1 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.7.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 1
Total Memory: 979.7 MiB
Name: centosdocker1
ID: CPPC:L3XN:JY6M:WYYT:5N3M:U77M:YM5K:HWRI:IMYI:ZJMB:RPZY:BYYQ
[root@centosdocker1 ~]#

So it is still using the loopback devices

However on the command line, if I carry out the following (after stopping the daemon and clearing out /var/lib/docker)

. /etc/sysconfig/docker
docker -d $other_args

root@centosdocker1 ~]# docker info
Containers: 0
Images: 0
Storage Driver: devicemapper
 Pool Name: docker-253:0-33870349-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/vg01/data
 Metadata file: /dev/vg01/meta
 Data Space Used: 307.2 MB
 Data Space Total: 12.88 GB
 Data Space Available: 12.58 GB
 Metadata Space Used: 364.5 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.7.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 1
Total Memory: 979.7 MiB
Name: centosdocker1
ID: CPPC:L3XN:JY6M:WYYT:5N3M:U77M:YM5K:HWRI:IMYI:ZJMB:RPZY:BYYQ
[root@centosdocker1 ~]#

It would seem something isn't reading the options properly when running from the startup scripts. Also, when calling the startup script, a ps -ef shows the following:

root       1904      1  5 23:59 ?        00:00:00 /usr/bin/docker -d -H fd://

It doesn't seem to pick up the extra options.

**Comment by numanoids** [comment]
Just in case not clear from above

docker version:
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64

docker info (when running from systemd):

Containers: 0
Images: 0
Storage Driver: devicemapper
 Pool Name: docker-253:2-12677338-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 307.2 MB
 Data Space Total: 107.4 GB
 Data Space Available: 3.766 GB
 Metadata Space Used: 729.1 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.7.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 1
Total Memory: 993.4 MiB
Name: centos7
ID: XFJF:75DH:HUMT:7LLT:VHIQ:CNEX:X4C4:CJ67:RULZ:AV3X:UYTI:OEIX

uname -a:

Linux centos7 3.10.0-229.7.2.el7.x86_64 #1 SMP Tue Jun 23 22:06:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by BrianHicks** [comment]
I've fixed this in our environment by changing the service file at `/usr/lib/systemd/system/docker.service` to read:

```
[Service]
EnvironmentFile=-/etc/sysconfig/docker
ExecStart=/usr/bin/docker -d -H fd:// $other_arg
```

I've opened PR #15043 to address this.

**Comment by numanoids** [comment]
Thanks @BrianHicks.

**Comment by jfrazelle** [comment]
see this for full discussion but we will be fixing the docs instead https://github.com/docker/docker/pull/14513#issuecomment-125009350
