### ISSUE TITLE
Cannot start container: operation not supported on Debian Jessie ARM

### ISSUE THREAD

**Issue by Pastafarianist** [docker/docker#14673]
I am running Docker on Debian Jessie built for ODroid C1 using scripts from [this project](https://github.com/tomuta/debian-mini-odroid-c1). Docker is installed from the `jessie-backports` repository. Running the Hello World, it crashes with:

    root@odroidc1:~# docker run --rm hello-world
    FATA[0000] Error response from daemon: Cannot start container c82d8e17ad10911d453544bea48e2700235d36baf2da0cb761f53807abefbfdc: [8] System error: operation not supported
    
    root@odroidc1:~# tail -f /var/log/daemon.log -n 50
    <...>
    Jul 16 04:03:36 odroidc1 docker[1930]: time="2015-07-16T04:03:36-06:00" level=info msg="POST /v1.18/containers/create"
    Jul 16 04:03:36 odroidc1 docker[1930]: time="2015-07-16T04:03:36-06:00" level=info msg="+job create()"
    Jul 16 04:03:36 odroidc1 docker[1930]: time="2015-07-16T04:03:36-06:00" level=info msg="+job log(create, c82d8e17ad10911d453544bea48e2700235d36baf2da0cb761f53807abefbfdc, hello-world:latest)"
    Jul 16 04:03:36 odroidc1 docker[1930]: time="2015-07-16T04:03:36-06:00" level=info msg="-job log(create, c82d8e17ad10911d453544bea48e2700235d36baf2da0cb761f53807abefbfdc, hello-world:latest) = OK (0)"
    Jul 16 04:03:36 odroidc1 docker[1930]: time="2015-07-16T04:03:36-06:00" level=info msg="-job create() = OK (0)"
    Jul 16 04:03:36 odroidc1 docker[1930]: time="2015-07-16T04:03:36-06:00" level=info msg="POST /v1.18/containers/c82d8e17ad10911d453544bea48e2700235d36baf2da0cb761f53807abefbfdc/attach?stderr=1&stdout=1&stream=1"
    Jul 16 04:03:36 odroidc1 docker[1930]: time="2015-07-16T04:03:36-06:00" level=info msg="+job container_inspect(c82d8e17ad10911d453544bea48e2700235d36baf2da0cb761f53807abefbfdc)"
    Jul 16 04:03:36 odroidc1 docker[1930]: time="2015-07-16T04:03:36-06:00" level=info msg="-job container_inspect(c82d8e17ad10911d453544bea48e2700235d36baf2da0cb761f53807abefbfdc) = OK (0)"
    Jul 16 04:03:36 odroidc1 docker[1930]: time="2015-07-16T04:03:36-06:00" level=info msg="+job attach(c82d8e17ad10911d453544bea48e2700235d36baf2da0cb761f53807abefbfdc)"
    Jul 16 04:03:36 odroidc1 docker[1930]: time="2015-07-16T04:03:36-06:00" level=info msg="POST /v1.18/containers/c82d8e17ad10911d453544bea48e2700235d36baf2da0cb761f53807abefbfdc/start"
    Jul 16 04:03:36 odroidc1 docker[1930]: time="2015-07-16T04:03:36-06:00" level=info msg="+job start(c82d8e17ad10911d453544bea48e2700235d36baf2da0cb761f53807abefbfdc)"
    Jul 16 04:03:36 odroidc1 docker[1930]: time="2015-07-16T04:03:36-06:00" level=info msg="+job allocate_interface(c82d8e17ad10911d453544bea48e2700235d36baf2da0cb761f53807abefbfdc)"
    Jul 16 04:03:36 odroidc1 docker[1930]: time="2015-07-16T04:03:36-06:00" level=info msg="-job allocate_interface(c82d8e17ad10911d453544bea48e2700235d36baf2da0cb761f53807abefbfdc) = OK (0)"
    Jul 16 04:03:36 odroidc1 docker[1930]: time="2015-07-16T04:03:36-06:00" level=info msg="+job log(start, c82d8e17ad10911d453544bea48e2700235d36baf2da0cb761f53807abefbfdc, hello-world:latest)"
    Jul 16 04:03:36 odroidc1 docker[1930]: time="2015-07-16T04:03:36-06:00" level=info msg="-job log(start, c82d8e17ad10911d453544bea48e2700235d36baf2da0cb761f53807abefbfdc, hello-world:latest) = OK (0)"
    Jul 16 04:03:36 odroidc1 systemd[1]: Starting docker container c82d8e17ad10911d453544bea48e2700235d36baf2da0cb761f53807abefbfdc.
    Jul 16 04:03:36 odroidc1 systemd[1]: Failed to set cpu.cfs_period_us on /system.slice/docker-c82d8e17ad10911d453544bea48e2700235d36baf2da0cb761f53807abefbfdc.scope: Permission denied
    Jul 16 04:03:36 odroidc1 systemd[1]: Failed to set cpu.cfs_quota_us on /system.slice/docker-c82d8e17ad10911d453544bea48e2700235d36baf2da0cb761f53807abefbfdc.scope: Permission denied
    Jul 16 04:03:36 odroidc1 systemd[1]: Started docker container c82d8e17ad10911d453544bea48e2700235d36baf2da0cb761f53807abefbfdc.
    Jul 16 04:03:36 odroidc1 docker[1930]: time="2015-07-16T04:03:36-06:00" level=warning msg="signal: killed"
    Jul 16 04:03:37 odroidc1 docker[1930]: time="2015-07-16T04:03:37-06:00" level=info msg="-job attach(c82d8e17ad10911d453544bea48e2700235d36baf2da0cb761f53807abefbfdc) = OK (0)"
    Jul 16 04:03:37 odroidc1 docker[1930]: time="2015-07-16T04:03:37-06:00" level=info msg="+job release_interface(c82d8e17ad10911d453544bea48e2700235d36baf2da0cb761f53807abefbfdc)"
    Jul 16 04:03:37 odroidc1 docker[1930]: time="2015-07-16T04:03:37-06:00" level=info msg="-job release_interface(c82d8e17ad10911d453544bea48e2700235d36baf2da0cb761f53807abefbfdc) = OK (0)"
    Jul 16 04:03:37 odroidc1 docker[1930]: time="2015-07-16T04:03:37-06:00" level=info msg="+job release_interface(c82d8e17ad10911d453544bea48e2700235d36baf2da0cb761f53807abefbfdc)"
    Jul 16 04:03:37 odroidc1 docker[1930]: time="2015-07-16T04:03:37-06:00" level=info msg="-job release_interface(c82d8e17ad10911d453544bea48e2700235d36baf2da0cb761f53807abefbfdc) = OK (0)"
    Jul 16 04:03:37 odroidc1 docker[1930]: time="2015-07-16T04:03:37-06:00" level=info msg="+job log(die, c82d8e17ad10911d453544bea48e2700235d36baf2da0cb761f53807abefbfdc, hello-world:latest)"
    Jul 16 04:03:37 odroidc1 docker[1930]: time="2015-07-16T04:03:37-06:00" level=info msg="-job log(die, c82d8e17ad10911d453544bea48e2700235d36baf2da0cb761f53807abefbfdc, hello-world:latest) = OK (0)"
    Jul 16 04:03:37 odroidc1 docker[1930]: Cannot start container c82d8e17ad10911d453544bea48e2700235d36baf2da0cb761f53807abefbfdc: [8] System error: operation not supported
    Jul 16 04:03:37 odroidc1 docker[1930]: time="2015-07-16T04:03:37-06:00" level=info msg="-job start(c82d8e17ad10911d453544bea48e2700235d36baf2da0cb761f53807abefbfdc) = ERR (1)"
    Jul 16 04:03:37 odroidc1 docker[1930]: time="2015-07-16T04:03:37-06:00" level=error msg="Handler for POST /containers/{name:.*}/start returned error: Cannot start container c82d8e17ad10911d453544bea48e2700235d36baf2da0cb761f53807abefbfdc: [8] System error: operation not supported"
    Jul 16 04:03:37 odroidc1 docker[1930]: time="2015-07-16T04:03:37-06:00" level=error msg="HTTP Error: statusCode=500 Cannot start container c82d8e17ad10911d453544bea48e2700235d36baf2da0cb761f53807abefbfdc: [8] System error: operation not supported"
    
    root@odroidc1:~# uname -a
    Linux odroidc1 3.10.80 #1 SMP PREEMPT Sat Jun 20 10:47:49 GMT 2015 armv7l GNU/Linux
    
    root@odroidc1:~# docker --version
    Docker version 1.6.2, build 7c8fca2
    
    root@odroidc1:~# docker info
    Containers: 6
    Images: 2
    Storage Driver: aufs
     Root Dir: /var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 14
     Dirperm1 Supported: true
    Execution Driver: native-0.2
    Kernel Version: 3.10.80
    Operating System: Debian GNU/Linux 8 (jessie)
    CPUs: 4
    Total Memory: 820.6 MiB
    Name: odroidc1

**Comment by thaJeztah** [comment]
If you're running docker on a non-standard architecture (ARM in this case), you'll also have to run images specially created for that architecture. The default `hello-world` image is not build for arm, so won't run.

See, for example, this document that explains how to run docker on those platforms;
https://github.com/umiddelb/armhf/wiki/Installing,-running,-using-docker-on-armhf-(ARMv7)-devices

I'm closing this issue, because running docker on other architectures is not (yet) officially supported and experimental
