### ISSUE TITLE
Docker Experimental(1.8 dev ) issue

### ISSUE THREAD

**Issue by JosenChareles** [docker/docker#14672]
from https://github.com/docker/libnetwork/blob/master/docs/overlay.md

sudo docker -H tcp://0.0.0.0:2375  --kv-store=consul:10.151.140.110:8500 --label=com.docker.network.driver.overlay.bind_interface=eth0 -d

WARN[0000] Running experimental build                   
WARN[0000] You are running linux kernel version 2.6.32-504.12.2.el6.x86_64, which might be unstable running docker. Please upgrade your kernel to 3.10.0. 
WARN[0000] Udev sync is not supported. This will lead to unexpected behavior, data loss and errors. For more information, see https://docs.docker.com/reference/commandline/cli/#daemon-storage-driver-option 
WARN[0000] /!\ DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING /!\ 
INFO[0000] Listening for HTTP on tcp (0.0.0.0:2375)     
INFO[0000] [graphdriver] using prior storage driver "devicemapper" 
INFO[0000] Option DefaultDriver: bridge                 
INFO[0000] Option DefaultNetwork: bridge                
INFO[0000] Option OptionKVProvider: consul              
INFO[0000] Option OptionKVProviderURL: 10.151.140.110:8500 
WARN[0000] Running modprobe bridge nf_nat br_netfilter failed with message: WARNING: Module br_netfilter not found.
, error: exit status 1 
INFO[0000] Firewalld running: false                     
FATA[0000] Error starting daemon: Error initializing network controller: error obtaining controller instance: initializing serf instance failed: getBindAddr error: failed to get bind address

**Comment by kadishmal** [comment]
I am encountering the same issue:

	$ docker version
	Client:
	 Version:      1.8.0-dev
	 API version:  1.20
	 Go version:   go1.4.2
	 Git commit:   8c7cd78
	 Built:        Tue Jul 14 23:47:18 UTC 2015
	 OS/Arch:      linux/amd64
	 Experimental: true
	Cannot connect to the Docker daemon. Is 'docker -d' running on this host?

	$ uname -a
	Linux xseed118.kdev 2.6.32-504.3.3.el6.x86_64 #1 SMP Wed Dec 17 01:55:02 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Running Docker and friends on a physical machine on CentOS 6.6.

Step to reproduce:

1. Download `docker-latest`.
2. Copy it to `/usr/bin/docker`.
3. `chmod +x`
4. Install `consul` on 3 physical nodes.
5. On node 1, run:

        $ sudo docker -d --kv-store=consul:localhost:8500 --label=com.docker.network.driver.overlay.bind_interface=eth0

Results in:

	WARN[0000] Running experimental build
	WARN[0000] You are running linux kernel version 2.6.32-504.3.3.el6.x86_64, which might be unstable running docker. Please upgrade your kernel to 3.10.0.
	INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
	WARN[0000] Udev sync is not supported. This will lead to unexpected behavior, data loss and errors. For more information, see https://docs.docker.com/reference/commandline/cli/#daemon-storage-driver-option
	INFO[0000] [graphdriver] using prior storage driver "devicemapper"
	INFO[0000] Option DefaultDriver: bridge
	INFO[0000] Option DefaultNetwork: bridge
	INFO[0000] Option OptionKVProvider: consul
	INFO[0000] Option OptionKVProviderURL: localhost:8500
	WARN[0000] Running modprobe bridge nf_nat br_netfilter failed with message: WARNING: Module br_netfilter not found.
	, error: exit status 1
	FATA[0000] Error starting daemon: Error initializing network controller: error obtaining controller instance: initializing serf instance failed: getBindAddr error: failed to get bind address

Would be glad if this issue is reopened and possible workarounds suggested. Thank you.

**Comment by thaJeztah** [comment]
Searched a bit for this, and I think there's currently a PR in libnetwork to work around this issue; https://github.com/docker/libnetwork/pull/399

/cc @dave-tucker @mavenugo 


**however**, be aware that with the Docker 1.8 release, CentOS/RHEL 6 and kernel 2.6 will no longer be supported (and is already not supported by RedHat). Docker will not be running reliably on these systems and it's highly recommended to upgrade to CentOS/RHEL 7 to keep using Docker

**Comment by mavenugo** [comment]
@kadishmal the error

>> FATA[0000] Error starting daemon: Error initializing network controller: error obtaining controller instance: initializing serf instance failed: getBindAddr error: failed to get bind address

Indicates that Serf is unable to get the bind address from the provided bind interface. Can you please check the status of eth0 and the security settings in centos 6.6 that might cause this error ?

Also, as @thaJeztah suggested, centos6.6 runs a very old kernel 2.6 with many fixes on top & there is a discussion to drop support for this from Docker 1.8 release onwards. Also, the overlay driver depends on the kernel's VXLAN support (which got introduced after 3.8, also due to an issue, this driver is supported only for 3.15+).

Hence, we highly encourage you to upgrade to CentOS 7 and check the status of your bind interface (eth0) and try it again.

**Comment by thaJeztah** [comment]
Ah, thanks @mavenugo, I wasn't sure if there was a relation between the last two errors/warnings.

**Comment by favorinfo** [comment]
I've got the same error with my boot2docker version is '4.1.19' as well as my docker-machine version is 0.6.0, build e27fb87. 

```
 back git:(master) ✗ docker-machine -v
docker-machine version 0.6.0, build e27fb87

docker -v
Docker version 1.10.3, build 20f81dd
```
