### ISSUE TITLE
Documentation of 'list containers' API call misses 'Names' element

### ISSUE THREAD

**Issue by rhuss** [docker/docker#14675]
When calling `GET /containers/json` the objects in the returned array contain a `Names` element with an array. This property is not documented in the [API doc](https://docs.docker.com/reference/api/docker_remote_api_v1.19/) so I wonder whether this is an official feature and one can use it without being afraid that it gets removed later ?

Also, why is this an array and no a scalar value because AFAIK a container can carry only a single name (this can be also infered from the response of 'container inspect').

**Comment by duglin** [comment]
re: Names vs Name - see: https://github.com/docker/docker/pull/14128  for an on-going discussion - apparently there can be multiple names.

**Comment by duglin** [comment]
PR #14676 will add it to the docs though.

**Comment by rhuss** [comment]
Thanks ! good to know that it is an official feature since I can really use that ;-)
