### ISSUE TITLE
docs: update Docker Hub API reference

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#14686]
As discussed in https://github.com/docker/docker/pull/13375#issuecomment-120170880, the [Docker Hub and Registry V1](https://github.com/docker/docker/blob/master/docs/reference/api/hub_registry_spec.md) API reference needs to be deprecated or rewritten.

Adding this issue as a reminder, but there might be an overlap here with the distribution docs, so not sure what the best approach is here.

Also, technical guidance is needed here (https://github.com/docker/docker/pull/13375#issuecomment-120173326)

/cc @moxiegirl @tiborvass @stevvooe

**Comment by moxiegirl** [comment]
@thaJeztah This is already covered by: https://github.com/docker/docker/issues/14616

**Comment by stevvooe** [comment]
@thaJeztah What are the specific goals of the rewrite? Does this make sense without having a deprecation plan fully in place?

**Comment by moxiegirl** [comment]
@thaJeztah @stevvooe We should close this one in favor of the one that I already had open.  @stevvooe I'll forward you the internal email discussion; the particular topic was raised by Ken and Banjot.
