### ISSUE TITLE
"docker images" should support image tags.

### ISSUE THREAD

**Issue by jmmills** [docker/docker#14684]
This behavior seems inconsistent, and leaves a trail of grep and awk when trying to figure out if a particular image:tag has been pulled already.

    charlie:~$ docker version && docker images ubuntu && docker images ubuntu:latest
    Client version: 1.7.0
    Client API version: 1.19
    Go version (client): go1.4.2
    Git commit (client): 0baf609
    OS/Arch (client): darwin/amd64
    Server version: 1.7.0
    Server API version: 1.19
    Go version (server): go1.4.2
    Git commit (server): 0baf609
    OS/Arch (server): linux/amd64
    REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
    ubuntu              latest              d2a0ecffe6fa        6 days ago          188.4 MB
    REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE

**Comment by cpuguy83** [comment]
Closing, dup of #13501

**Comment by jmmills** [comment]
@cpuguy83 thanks, my search skilled failed me.

**Comment by cpuguy83** [comment]
No worries. GH search is the worst.
