### ISSUE TITLE
Basic Docker Setup Linux VM

### ISSUE THREAD

**Issue by samillm** [docker/docker#14692]
Hi, 

I'm following step one of [this](http://docs.docker.com/linux/step_one/) docker tutorial.
I have installed ubuntu version 14.04 on a virtual box vm.
I intentionally downgraded by docker version so that when I type "docker version" I get Client version: 1.5.0. This is because the server I intend to communicate with is on 1.5.0.

When trying the command "docker run hello-world" I get the response:

Post http:///var/run/docker.sock/v1.17/containers/create: dial unix /var/run/docker.sock: permission denied. Are you trying to connect to a TLS-enabled daemon without TLS?

When running "sudo docker run hello-world" I get the response:
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?

Can someone please explain to me what's happening and how can fix it?
Thanks.

**Comment by thaJeztah** [comment]
Is the docker daemon running on your host (the VM)? Try `service docker start` and check log files in `/var/log/upstart/docker.log`

However, the GitHub issue tracker is for reporting bugs and feature requests, and is not a general support forum. 

For that reason, I'm going to close this issue. Please ask this question in the #docker IRC channel on freenode or the docker-users Google Group, which are more intended for this kind of questions.
