### ISSUE TITLE
Upgrading from docker 1.7.0 to 1.7.1 loses images?

### ISSUE THREAD

**Issue by newhook** [docker/docker#14707]
This is on Ubuntu 14.04.2 LTS. I did an upgrade and post upgrade the images are all gone:

$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE

cat /etc/default/docker
DOCKER_OPTS="-g /home/docker --iptables=false"

It looks to me that perhaps the storage driver changed during the upgrade? On an un-upgraded host I see:

```
$ docker info
Containers: 11
Images: 124
Storage Driver: vfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.14.32-xxxx-grs-ipv6-64
Operating System: Ubuntu 14.04.2 LTS
CPUs: 8
Total Memory: 62.94 GiB
Name: XXXXX
ID: FOD4:IYDO:Q2VL:JLRC:PPTI:AT57:7SSF:QBCU:UW3A:4Y26:WYO2:JOGK
```

On an upgraded host I see:
```
docker info
Containers: 0
Images: 0
Storage Driver: devicemapper
 Pool Name: docker-9:2-4718673-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 305.7 MB
 Data Space Total: 107.4 GB
 Data Space Available: 107.1 GB
 Metadata Space Used: 733.2 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: false
 Deferred Removal Enabled: false
 Data loop file: /home/docker/devicemapper/devicemapper/data
 Metadata loop file: /home/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.14.32-xxxx-grs-ipv6-64
Operating System: Ubuntu 14.04.2 LTS
CPUs: 8
Total Memory: 62.94 GiB
Name: XXXXXX
ID: 2OIX:UCYC:HCLE:R5DA:F2DG:CSTQ:6PIL:BXOU:LZQK:4VAM:WKMP:UXUP
```

**Comment by cpuguy83** [comment]
This is because on 1.7.0 you were using the vfs graphdriver.
When you upgraded to 1.7.1 the devicemapper driver became available, and as such was used as vfs should never really be used unless nothing else is supporter of it was specified in the daemon startup.

With 1.7.0 there were some configurations which docker refused to run devicemapper with, these restrictions were relaxed a bit in 1.7.1.

**Comment by newhook** [comment]
This was suprising and should have been mentioned in the release notes.

**Comment by cpuguy83** [comment]
From Changelog:
> Fix implicit devicemapper selection with static binaries

**Comment by newhook** [comment]
Ah, very descriptive and informative!

**Comment by cpuguy83** [comment]
@newhook Your images are not gone.
If you want to access your old images you can start docker with `-s vfs` and they will be available.
