### ISSUE TITLE
Update the commandline/logs.md file to point to logging page

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#14711]
Need to point to the reference/logging page from the logs.md page as per comments on this PR: https://github.com/docker/docker/pull/11485/files#diff-bf81424845bcab2902c9809e30dfe6e0

Also should update the page to point that other drivers have other options

**Comment by LK4D4** [comment]
There is no more reference/logging.

**Comment by thaJeztah** [comment]
Yup, there is, but it was moved to https://docs.docker.com/engine/admin/logging/overview/

let me open a PR
