### ISSUE TITLE
Docker stop and rm don't act on tagged or named containers??

### ISSUE THREAD

**Issue by Thetoxicarcade** [docker/docker#14710]
I'm working with docker-compose to handle naming my containers (which I'm guessing is --label?)
```
CONTAINER ID        IMAGE                    COMMAND                CREATED             STATUS              PORTS                            NAMES
421a0ae09ce6        kdelfour/cloud9-docker   "supervisord -c /etc   2 days ago          Up 2 days           3000/tcp, 0.0.0.0:7676->80/tcp   alex_code_1         
54f5026523b7        cloudfleet/mailpile      "/bin/sh -c './mp --   2 days ago          Up 2 days           0.0.0.0:33411->33411/tcp         alex_mail_1         
6fcd5f666fd4        ghost                    "/entrypoint.sh npm    2 days ago          Up 2 days           0.0.0.0:11180->2368/tcp          alex_blog_1 
```
anyway, on interacting with them:

```
docker stop --label alex_blog_1
flag provided but not defined: --label
See 'docker stop --help'.
```

Any help on interacting with docker containers by name? my solution at this point was to use their ID, which isn't fun and in fact takes away the "I can't believe it's not awful™" factor.

I suppose if this is a bug or a fix, what mostly needs to be repaired is the man page and --help output?

**Comment by icecrime** [comment]
@Thetoxicarcade I believe `docker stop alex_code_1` should just work! There are no labels involved here.

**Comment by Thetoxicarcade** [comment]
weeeee! thanks c:

**Comment by icecrime** [comment]
No problem :-) You can substitute container ID by its name pretty much anywhere on the CLI.

**Comment by Thetoxicarcade** [comment]
just so long as I can name it at some point.
