### ISSUE TITLE
Unable to pull image from an insecure registry

### ISSUE THREAD

**Issue by venkatramachandran** [docker/docker#14712]
```
vagrant@vagrant:~$ docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
vagrant@vagrant:~$ docker info
Containers: 0
Images: 34
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 34
Execution Driver: native-0.2
Kernel Version: 3.13.0-57-generic
Operating System: Ubuntu 14.04 LTS
CPUs: 1
Total Memory: 994 MiB
Name: vagrant
ID: OXRP:6VZL:PLXK:Y7SU:EFEI:2KF5:PILP:UKXH:35MK:CUC6:VOP4:G75Q
WARNING: No swap limit support
vagrant@vagrant:~$ uname -a
Linux vagrant 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
Environment: vagrant

List the steps to reproduce the issue:
1. Run `docker pull <localrepo>/<image>`

Describe the results you received:
`FATA[0010] Error: image origins:latest not found`

Describe the results you expected:
The image is pulled successfully.

I am running 2 vagrant boxes on `172.28.128.4` and `172.28.128.5`. The box on `172.28.128.4` runs a registry:2 container (with container port 5000 mapped to host port 5000). I've pushed an image called `origins` to this repo.

When I try to pull the same from `172.28.128.5`, I get the above-mentioned error. It should be noted that I've updated my `/etc/default/docker` file and the `DOCKER_OPTS` does read like this: `DOCKER_OPTS="--insecure-registry 172.28.128.4:5000"`

Yet, I am unable to pull the image.

What could I be missing here?

**Comment by dmp42** [comment]
You need docker 1.6 or more recent to use registry:2.

https://github.com/docker/distribution/blob/master/docs/index.md#requirements

Let me know if you still have issues (closing this for now).
