### ISSUE TITLE
Documentation: Formatting issue in Ubuntu installation guide

### ISSUE THREAD

**Issue by charleswhchan** [docker/docker#14729]
https://docs.docker.com/installation/ubuntulinux/

Under Installation, step 3, there are odd > characters in the paragraph:
![screen shot 2015-07-18 at 6 39 52 am](https://cloud.githubusercontent.com/assets/679475/8761787/fae2db20-2d17-11e5-91b6-f9781c99b372.png)

I think the > is used as quote in GitHub's markdown and does not render properly on the docs site.
https://github.com/docker/docker/blob/master/docs/installation/ubuntulinux.md

**Comment by Evalle** [comment]
I can see this issue in Chromium, Chrome and Firefox. Fix is trivial. 
#dibs

**Comment by Evalle** [comment]
Fixed in https://github.com/docker/docker/pull/14731 so this issue can be closed. 
ping @charleswhchan

**Comment by charleswhchan** [comment]
Thanks @Evalle!

**Comment by thaJeztah** [comment]
Thanks! closing
