### ISSUE TITLE
when build docker,run apt-get update, report hash mismatch

### ISSUE THREAD

**Issue by YuleiXiao** [docker/docker#14723]
Description of problem:
when build docker image , run apt-get update, but it report hash mismatch. build process can not continue.

cat Dockerfile :

FROM golang:1.4.2

RUN apt-get update -y && \
	apt-get dist-upgrade -y && \
	apt-get install --no-install-recommends --auto-remove -y git build-essential pkg-config file npm && \
 	apt-get clean autoclean && \
 	apt-get autoremove -y && \
 	rm -rf /tmp/* && \
	ln -s /usr/bin/nodejs /usr/bin/node

ENV GOPATH /go
ENV ROACHPATH $GOPATH/src/github.com/cockroachdb

RUN mkdir -p $ROACHPATH && \
	ln -s "${ROACHPATH}/cockroach" /cockroach

WORKDIR ${ROACHPATH}/cockroach

ADD . ${ROACHPATH}/cockroach/build/devbase/
RUN ["./build/devbase/deps-docker.sh"]

CMD ["/bin/bash"]

result:
Building Docker Cockroach images...
Sending build context to Docker daemon 20.48 kB
Sending build context to Docker daemon
Step 0 : FROM golang:1.4.2
---> 124e2127157f
Step 1 : MAINTAINER Tobias Schottdorf tobias.schottdorf@gmail.com
---> Using cache
---> 6779403f4903
Step 2 : RUN apt-get update -y && apt-get dist-upgrade -y && apt-get install --no-install-recommends --auto-remove -y git build-essential pkg-config file npm && apt-get clean autoclean && apt-get autoremove -y && rm -rf /tmp/* && ln -s /usr/bin/nodejs /usr/bin/node
---> Running in f3b531115198
Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
Get:2 http://security.debian.org jessie/updates/main amd64 Packages [139 kB]
Get:3 http://httpredir.debian.org jessie InRelease [134 kB]
Get:4 http://httpredir.debian.org jessie/main amd64 Packages [9019 kB]
Get:5 http://httpredir.debian.org jessie-updates InRelease [133 kB]
Get:6 http://httpredir.debian.org jessie-updates/main amd64 Packages [3616 B]
W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie/main/binary-amd64/Packages Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
Fetched 9493 kB in 13s (695 kB/s)
The command '/bin/sh -c apt-get update -y && apt-get dist-upgrade -y && apt-get install --no-install-recommends --auto-remove -y git build-essential pkg-config file npm && apt-get clean autoclean && apt-get autoremove -y && rm -rf /tmp/* && ln -s /usr/bin/nodejs /usr/bin/node' returned a non-zero code: 100

`docker version`:
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64

`docker info`:
Containers: 5
Images: 15
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 25
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-43-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 5.583 GiB
Name: ubuntu
ID: WRRK:57FL:C4Y2:QRKU:7CVB:7FRQ:UMRV:WQTM:7Q4P:UUCN:MT45:7L7I
WARNING: No swap limit support

`uname -a`:
Linux ubuntu 3.16.0-43-generic #58~14.04.1-Ubuntu SMP Mon Jun 22 10:21:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
physical ubuntu 14.04

**Comment by thaJeztah** [comment]
I don't think this is something related to Docker, it looks like a hiccup trying to fetch the index from Debian
