### ISSUE TITLE
Cannot link to container with --net=none

### ISSUE THREAD

**Issue by timthelion** [docker/docker#14728]
Description of problem:

I would like to link to a container which has `--net=none` configured. I have two containers: x11app and x11server. x11server does not need to connect to the internet, so I give it `--net=none`, however it does provide the x11 service via a UDP socket. I would like to give x11app the ability to connect to that socket, so I pass x11app the `--link=x11server:x11server` argument. Unfortunately this does not work and docker failes to launch x11app with an unfriendly error message.

`docker version`:
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

`docker info`:
Containers: 644
Images: 598
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1886
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 4
Total Memory: 5.642 GiB
Name: timothy-debian-hp
ID: M63M:TGWY:SLXX:IHVP:N4IA:6Y7N:LDKQ:GHOG:L7X2:WZL4:EAGA:BNJI
WARNING: No memory limit support
WARNING: No swap limit support

`uname -a`:
Linux timothy-debian-hp 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
Physical laptop running debian jessie.

How reproducible: 100%

Steps to Reproduce:
1. Open two terminal windows.

2. In terminal 1 enter:
````
$ docker run --name service --net=none -i -t debian /bin/bash
root@28a1bc3a26e8:/# 
````

3. In termina 2 enter:
````
$ docker run --link=service:service -i -t debian /bin/bash
FATA[0000] Error response from daemon: Cannot start container 3de4395146fa2be1bc8e85147a4fc1cf755f94f018a54281df4eb5c4cd0c8b28: Child IP '' is invalid 
````

Desired Results:

This should work. It is common to has a service such as a database, which does not require an internet connection but does need to be linked to in order to allow other containers to take advantage of its UDP socket services.

Additional info:

A [previous bug report](https://github.com/docker/docker/issues/8333) involving `--net=host` was resolved by @jfrazelle by producing a nice error message https://github.com/jfrazelle/docker/blob/6743be44ca9006cb7ca26cd3d8410877727a6313/daemon/daemon.go#L699 .

**Comment by cpuguy83** [comment]
None means no networking at all, it had nothing to do with reaching the Internet.
You cannot link to something that has no network interface, as there is nothing to link to.

Closing as this is expected and intentional behavior.

**Comment by timthelion** [comment]
The error message still needs to be changed.

**Comment by timthelion** [comment]
What is the appropriate way to give a container a network interface but to prevent that container from communicating with the outside world?

**Comment by cpuguy83** [comment]
I'll have to check, but I think this errors out sooner on 1.7 (and gives a proper error message).

You should block access with iptables.

**Comment by timthelion** [comment]
If it does error out sooner on 1.7 I would still request that you re-open this bug report because that check should probably be in the same place as the check that I linked to in order to prevent a spaghetti code situation.

**Comment by cpuguy83** [comment]
@timthelion Actually this doesn't error out in 1.7
