### ISSUE TITLE
Swarm docs alternate confusingly between `docker run swarm` and `swarm`

### ISSUE THREAD

**Issue by metalivedev** [docker/docker#14721]
The basic docs for swarm use `docker run swarm`, keeping it clear that the binary is in a container. The "discovery" section refers to `swarm` as a binary. The [swarm docs on GitHub](https://github.com/docker/swarm) show how to build the `swarm` binary, but this is not mentioned in docs.docker.com

Please pick one method and use that for all documentation or otherwise make it clear how to execute the commands.

**Comment by metalivedev** [comment]
https://docs.docker.com/swarm/discovery/ uses `swarm`
https://docs.docker.com/swarm/install-manual/ uses `docker run swarm`

**Comment by thaJeztah** [comment]
Hi Andy! this part of the documentation is actually in the Swarm repository. It looks like there's an issue open to track this; https://github.com/docker/swarm/issues/722 so I'll close this one.

Thanks for reporting, feel free to comment on https://github.com/docker/swarm/issues/722 ;-)
