### ISSUE TITLE
Documentation: Environment replacement needs improvement

### ISSUE THREAD

**Issue by charleswhchan** [docker/docker#14734]
Found a few problems with this section:
https://docs.docker.com/reference/builder/#environment-replacement

> Note: prior to 1.3, Dockerfile environment variables were handled similarly, in that they would be replaced as described below. However, there was no formal definition on as to which instructions handled environment replacement at the time. After 1.3 this behavior will be preserved and canonical.

>... there was no formal definition on as to which instructions handled environment replacement at the time
1. This sentence doesn't make sense.

Dockerfile environment variables were handled similarly
2. Similarly to what? Perhaps the note block should be moved after the explanation of Environment variable.

Perhaps someone could review the Environment variable section and reorganize the material presented.

**Comment by ankushagarwal** [comment]
I tried to address this issue, but it was not very clear to me either. Pinging @erikh for help as he authored that paragraph https://github.com/docker/docker/pull/8807

**Comment by erikh** [comment]
It’s a kludgy sentence, but it’s correct. What it means is that before, there was no formal set of rules around what could be replaced in what instructions. Environment replacement is very instruction-oriented, and several instructions deliberately do not support it.

Now, there are rules, and they should be below that paragraph. :)

On August 6, 2015 at 10:24:51 PM, Ankush Agarwal (notifications@github.com) wrote:

I tried to address this issue, but it was not very clear to me either. Pinging @erikh for help as he authored that paragraph #8807
