### ISSUE TITLE
Privileged container unable to view network namespace of libnetwork bridge

### ISSUE THREAD

**Issue by vijayendrabvs** [docker/docker#14743]
Please refer to https://github.com/docker/docker/issues/14666 for a background on this issue. This is for overlay networks. Libnetwork creates a namespace for each overlay network/subnet combination on which it plumbs the peer veths of eth interfaces that are visible within a container using that network (via a service attached to that network).

If we mount this network namespace into the host's /var/run/netns/, tools like ip/ethtool etc are able to view this namespace and allow us to look into them. But if we mount the namespace within the /var/run/netns of a privileged container, this fails with this error -

setting the network namespace "<ct-name>" failed: Invalid argument

An strace of an ip netns exec command on the above mounted namespace from within the privileged container fails thus -

open("/var/run/netns/ct2", O_RDONLY|O_CLOEXEC) = 4
setns(4, CLONE_NEWNET)                  = -1 EINVAL (Invalid argument)

Privileged containers should be able to carry out the above operation.

**Comment by vijayendrabvs** [comment]
docker version:
```
$ docker -v
Docker version 1.8.0-dev, build cc7fe0d, experimental
$
```
docker info:
uname -a:
```
$ uname -a
Linux big-libnetinst1 3.19.0-21-generic #21-Ubuntu SMP Sun Jun 14 18:31:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):

GCE instance.

List the steps to reproduce the issue:
1. Please refer to #14666 for details on how to reproduce this issue.

Describe the results you received:

Describe the results you expected:

Provide additional info you think is important:

----------END REPORT ---------

**Comment by vijayendrabvs** [comment]
It would be great if someone could provide me with some pointers to where I should look to fix this. I can start by looking at the network namespace creation path in libnetwork, but this may possibly be an issue with docker itself. Any help would be much appreciated, thanks!

**Comment by vijayendrabvs** [comment]
Any update on this?

**Comment by vijayendrabvs** [comment]
Hi @mavenugo !
@dsampath updated me about the brief conversation you both had and passed on your suggestion of using --cap-add ALL when spinning up the privileged container, and that did the trick!

So after doing a docker run --privileged --cap-add ALL --name <ct_name>  -v /proc and other options.... , I was able to view both halves of the network bridge configuration from inside the privileged container. I'm noting the steps below so it could be helpful to someone reading this thread.

0) docker exec -it <privileged_ct> /bin/bash
1) mkdir /var/run/netns
2) ln -s /host/proc/<container_pid>/ns/net /var/run/netns/<ct_name_or_some_name> [ To get the container's PID, use docker inspect -f '{{.State.Pid}}' <container_name_or_id> ]
3) ip netns exec <ct_name_or_same_name> ip a
         - shows the interfaces as seen by the container. ethtool -S <eth_iface> would give us the peer if_index.
4) ln -s /var/run/docker/netns/<network_id> /var/run/netns/<network_name_or_some_name>
5) ip netns exec <network_name_or_some_name> ip a
        - shows the veth pair peers + vxlan TEP + br0 (the other "side" of the network of the containers attached to this network via services).

I'm not sure yet what exact capability we need to add instead of doing an overall --cap-add ALL, which wouldn't be desirable, but this is good to know. Will wait to hear back on the exact capability for this functionality.

Thanks a lot!

Regards,
Vijay

**Comment by thaJeztah** [comment]
looks like this is resolved, so I'll close

**Comment by yeasy** [comment]
A more simple solution is just run "ip a" in both container and the host, then compare the index number at the beginning of each interface row.

Index(container_side) + 1 == Index(host_id).
