### ISSUE TITLE
unable to login to registry

### ISSUE THREAD

**Issue by dopatraman** [docker/docker#14761]
on login:
```
$ docker login <url>
$ <username>
$ <password>
```

I get this error:
```
FATA[0000] Error response from daemon: }
```

I am confident the username and password are valid. I suspect the problem might be related to the size of the container i recently built/pushed. Has anyone else run into this issue?

**Comment by dmp42** [comment]
Can you provide docker daemon logs? (in debug mode: `-D`)

**Comment by cpuguy83** [comment]
Closing for now, but if you can provide the requested info please ping here and we can take a look.
Thanks!
