### ISSUE TITLE
deprecate hostConfig on start for API > 1.21

### ISSUE THREAD

**Issue by runcom** [docker/docker#14777]
As per comments here #14691 and current comments on code here https://github.com/docker/docker/blob/master/daemon/start.go#L30 we could actually deprecate passing hostConfig to container start for newer api (> 1.21)

close #10695

ping @icecrime @cpuguy83 @LK4D4

**Comment by thaJeztah** [comment]
any update in this?

**Comment by runcom** [comment]
Gathering feedbacks

**Comment by thaJeztah** [comment]
Let's make some noise then :-)

ping @icecrime @cpuguy83 @LK4D4 wdyt?

**Comment by runcom** [comment]
This could be done with the new deprecation policy. We'll start by marking hostConfig on start deprecated and will remove it after next two releases.

Cli is not affected by this issue.
The only hassle would be to modify the mux route for back-compatibility either to add content to a 204 NoContent response (I'm -1 on this, just listing possibilities) or add warning to postContainersStart with deprecation message and modify the returned status code right now.

thoughts?

**Comment by aanm** [comment]
So, all values from `HostConfig` will disappear from `docker inspect`?

**Comment by cpuguy83** [comment]
@aanm No. Currently `POST /containers/<id>/start` accepts a `HostConfig` which is merged with anything set `create`... but this doesn't necessarily actually do anything, it depends on the subsystem if changes to this affect anything... and really they shouldn't.

**Comment by aanm** [comment]
Ah misread the "from start" part, okay makes sense.
