### ISSUE TITLE
Nondeterministic test TestLinksEtcHostsContentMatch

### ISSUE THREAD

**Issue by icecrime** [docker/docker#14774]
# Description

The test `TestLinksEtcHostsContentMatch` in `integration-cli/` is nondeterministic and leads to randomly failing test suites.  

See [the output](https://jenkins.dockerproject.org/job/Docker-PRs/11689/console):

```
FAIL: docker_cli_links_unix_test.go:20: DockerSuite.TestLinksEtcHostsContentMatch

docker_cli_links_unix_test.go:30:
    c.Errorf("container")
... Error: container
```

# How to

Review the test implementation to make it deterministic.

**Comment by duglin** [comment]
@icecrime where did you see this failing?

**Comment by runcom** [comment]
PR about this was merged, should this be closed @icecrime?
