### ISSUE TITLE
Experimental libnetwork: docker service info should show the IP list associated with the service

### ISSUE THREAD

**Issue by vijayendrabvs** [docker/docker#14781]
It would be good to have libnetwork service info show the list of IP addresses that it is associated with. Currently, docker inspect <container_id/name> doesn't show us the libnetwork service info.

I've put in a fix for this and it would be great if someone could review this patch and provide their comments - I'll make the necessary changes and resubmit if required.

Will submit a pull request in a short while.

Environment info:

docker version: 
```Docker version 1.8.0-dev, build cc7fe0d, experimental```

docker info:
```
Containers: 1
Images: 160
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 162
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-21-generic
Operating System: Ubuntu 15.04
CPUs: 16
Total Memory: 58.98 GiB
Name: big-libnetinst1
ID: WUZL:4AX2:X4OO:JNUB:WKBY:F5FP:E4PK:SNG3:5PVX:WGXM:YFW2:WK7B
Debug mode (server): true
File Descriptors: 30
Goroutines: 83
System Time: 2015-07-21T18:56:19.376096358Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker
WARNING: No swap limit support
Labels:
 com.docker.network.driver.overlay.bind_interface=eth0
Experimental: true
```
uname -a:
```
$ uname -a
Linux big-libnetinst1 3.19.0-21-generic #21-Ubuntu SMP Sun Jun 14 18:31:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):

GCE instance.

List the steps to reproduce the issue:
1. Install docker using `sudo wget -qO- https://get.docker.com/ | sh`
2. `git clone https://github.com/docker/docker.git; cd docker; make DOCKER_EXPERIMENTAL=1; service docker stop; cp /usr/bin/docker /usr/bin/docker.orig; ln -s bundles/1.8.0-dev/binary/docker-1.8.0-dev /usr/bin/docker; docker -d -D --kv-store=consul:localhost:8500 --label=com.docker.network.driver.overlay.bind_interface=eth0; docker network create -d overlay net1; docker service publish svc1.net1`
3. `docker service info svc1.net1`

Describe the results you received:

```
$ docker service info esvc1.enet1
Service Id: ea2b815a0d77b700823cc4b4596da7b6c36f0dfa9715946fc9201fa1b1043acb
	Name: esvc1
	Network: enet1
$ 
```

Describe the results you expected:

```
$ docker service info esvc1.enet1
Service Id: ea2b815a0d77b700823cc4b4596da7b6c36f0dfa9715946fc9201fa1b1043acb
	Name: esvc1
	Network: enet1
	IPList: [172.21.0.4]
```

Provide additional info you think is important:

----------END REPORT ---------

[Updated with Gordon's reqs]

**Comment by vijayendrabvs** [comment]
CC: @mavenugo

**Comment by vijayendrabvs** [comment]
Submitted pull request at https://github.com/docker/libnetwork/pull/404 (let me know if the resource isn't found :p )

**Comment by vijayendrabvs** [comment]
Cc: @mrjana @mavenugo

**Comment by vijayendrabvs** [comment]
It would be great if someone reviewed this - tracking iface/network/service/IPs is required and not having this info presented in the API response would make it hard to correlate docker container interfaces with their respective services/networks.

**Comment by aboch** [comment]
Multihost networking has exited experimental mode with considerably changes to the model. Specifically the service entity described by this issue no longer exists nor is accessible via CLI or rest API.

Therefore I am suggesting to close this issue as obsolete.

**Comment by thaJeztah** [comment]
Agreed. Documentation for the new networking can be found here; https://docs.docker.com/engine/userguide/networking/dockernetworks/

Additional improvements and features are coming in docker 1.10
