### ISSUE TITLE
exec: "cd": executable file not found in $PATH

### ISSUE THREAD

**Issue by suexcxine** [docker/docker#14782]
I tried the following example in http://docs.docker.com/userguide/dockervolumes/ but an error happened, any idea is appreciated! Thanks!
$ docker run --volumes-from dbdata2 -v $(pwd):/backup ubuntu cd /dbdata && tar xvf /backup/backup.tar
exec: "cd": executable file not found in $PATH
Error response from daemon: Cannot start container cfe05330bec35b5c80c1e8fdc9ed85d621f3558af8e1bbf8bf99a2e05b363aba: [8] System error: exec: "cd": executable file not found in $PATH

**Comment by suexcxine** [comment]
$ docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64

$ docker info
Containers: 28
Images: 47
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 103
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-43-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 4
Total Memory: 7.759 GiB
Name: chenduo-desktop
ID: 5CI4:SIDG:YMIA:HXON:7BB5:MATY:4UZX:2MRO:XGSC:I2LZ:RI6A:5A6Q
Username: suexcxine
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

$ uname -a
Linux chenduo-desktop 3.16.0-43-generic #58~14.04.1-Ubuntu SMP Mon Jun 22 10:21:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by phemmer** [comment]
`cd` is a shell builtin. Meaning you have to be inside a shell to use it. You also need to quote your command otherwise everything after the `&&` will be executed outside the container.

    docker run --volumes-from dbdata2 -v $(pwd):/backup ubuntu /bin/sh -c 'cd /dbdata && tar xvf /backup/backup.tar'

&nbsp;

For help using docker, I'd recommend [the docker forums](https://forums.docker.com/) or [the mailing list](https://groups.google.com/forum/#!forum/docker-user). The github issue tracker is generally for problems with docker.

**Comment by TUTUBIG** [comment]
i have got this trouble too, you need to get into the shell and then excute the "cd" command.use "ls" first,and,use "cd"
