### ISSUE TITLE
libnetwork: Does libnetwork deviate from intention of app-container which does not have any endpoint?

### ISSUE THREAD

**Issue by Zhang-Haoyu** [docker/docker#14797]
We are running hundreds of app-containers per-host for our stateless applications.
The app-container uses host-mode network which doesn't create one network namespace and just share the host's, and provides a light-weight isolated executing environment for apps, can be started and destroyed very efficiently and costlessly for stateless apps.
Does libnetwork deviate from intention of app-containers which does not have any network endpoints inside?
Or I missed something.

Thanks,
Yuzhou

**Comment by cpuguy83** [comment]
I don't understand your question.
But libnetwork is the network library that docker uses for all network code.
The old docker (pre-libnetwork) code was ported to libnetwork as a base (so things like --net=host and --net=none continue to work as expected).

**Comment by Zhang-Haoyu** [comment]
I read the libnetwork design doc (https://github.com/docker/libnetwork/blob/master/docs/design.md) and below blog,
https://blog.docker.com/2015/04/docker-networking-takes-a-step-in-the-right-direction-2/
I think that introducing endpoints and network concepts, from certain angle, is just consider the container as a VM, like ones created by kvm, xen, vmware,  not a app-container.
But it's okay, just as you said, the libnetwork is the network library that docker uses for all network mode, I still can use host mode to create app-container without any endpoints inside.

But for app-container, what benefits can be gained from the libnetwork project?
Or the libnetwork is just a unified network library and interface, it dose not care about underlying network driver at all, if so, it's okay.

**Comment by cpuguy83** [comment]
@Zhang-Haoyu I do not see how endpoints make this like a VM.
If anything it's about ensuring that only containers that need to talk to each other can (and do so bi-directionally).

The benefit of libnetwork is in the creation of networks that you wire up containers to, and being able to publish services on that network for consumption, and this is done via whatever backend networking technology is wired up to the container network.
For instance out of the box there is support for bridge networking and overlay networking (for multi-host).

Closing this as this is not a docker issue.

**Comment by mavenugo** [comment]
@Zhang-Haoyu, @cpuguy83 summarized it well. If you have further questions, please raise it in libnetwork project and we will be happy to give more explanation.
