### ISSUE TITLE
Include issue numbers in changelog

### ISSUE THREAD

**Issue by mindscratch** [docker/docker#14791]
When looking at the CHANGELOG, I sometimes see items that were fixed that I'd like to research a bit to see what the original problems were. It would be nice if the CHANGELOG included the issue numbers next to the items to make it easier to map the work being released with the context from which it came.

**Comment by duglin** [comment]
+1 good idea

**Comment by bprodoehl** [comment]
Yes, absolutely, I'd love to see this.

**Comment by thaJeztah** [comment]
Great idea, I've though about this many times, but wonder if it's possible to automatically generate a list of PRs (and issues) included in the release

/cc @tianon do you have some trickery up your sleeve to generate a list with PRs and issues?

**Comment by Djelibeybi** [comment]
:+1: This would be excellent.

**Comment by calavera** [comment]
We already do this. Thanks for the suggestion. Closing the issue.
