### ISSUE TITLE
Virtual interfaces are entering/leaving promiscuous mode

### ISSUE THREAD

**Issue by aaronjwood** [docker/docker#14807]
For some containers that are launched and stopped or killed (due to errors with what's running inside of them) I'm seeing logs that the virtual interfaces are entering and leaving promiscuous mode. These containers are running with the normal `bridge` networking mode. Example:

```
device veth0bb1f1f entered promiscuous mode
device veth0bb1f1f left promiscuous mode
```

Most of the containers aren't running with any special privileges or capabilities. There is one that runs with `--privileged` but it exhibits the same behavior as all the others. Another thing to note is that none of the other interfaces on the host are in promiscuous mode.

What could be causing this. It doesn't seem to be consistent and I have been unable to reproduce it on a Ubuntu machine with the same Docker version. Here's some info about the environment it's happening in:

```
docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.3.3
Git commit (client): a8a31ef-dirty
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.3.3
Git commit (server): a8a31ef-dirty
```

```
docker info
Containers: 14
Images: 271
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 3.19.3
Operating System: CoreOS 647.0.0
CPUs: 40
Total Memory: 125.9 GiB
```

```
uname -a
Linux 3.19.3 #2 SMP Thu Apr 9 01:47:33 UTC 2015 x86_64 Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz GenuineIntel GNU/Linux
```

**Comment by cpuguy83** [comment]
Seems like something on the host may be doing this...
But in any case, the latest release of docker, 1.7, includes a complete rewrite of Docker's networking code.
It would be good to upgrade to 1.7 so we can troubleshoot against the existing code base.

**Comment by aaronjwood** [comment]
Thanks. That's on our roadmap but we won't be getting to it until maybe a month or two from now.
I'll do some testing on a pristine CoreOS VM and see if it's specific to CoreOS (though I doubt that's the issue)

**Comment by aaronjwood** [comment]
Surprise, surprise. This does seem to be the default behavior on CoreOS. Closing this as invalid :)

**Comment by mrjana** [comment]
@aaronjwood This is how things work when you connect a particular interface to a bridge. In this case the host end of the veth pair is getting connected to the bridge and when you are a bridge port you cannot only receive packets for your own mac address. You need to receive packets destined to any mac address so that the bridge can forward the packet out of the appropriate outgoing interface or flood it on every interface part of the bridge. So all of this is intentional

**Comment by aaronjwood** [comment]
@mrjana you're right. I wasn't looking in the right place on the other non-CoreOS variants. Thanks for the explanation.

**Comment by mansurali901** [comment]
I was able to fix this by using turning to privileged to off 

administrator@gitlabrunner-prod01:~$ docker run --rm --privileged -t -d -p 23:22 --name ubuntu ubuntu
