### ISSUE TITLE
When veritas VxFS is used as backing filesystem to run docker daemon, docker info output shows "Backing Filesystem: <unknown>".

### ISSUE THREAD

**Issue by SymOSRB** [docker/docker#14803]
Description of problem:
When veritas VxFS is used as backing filesystem to run docker daemon, docker info output shows "Backing Filesystem: <unknown>".

`docker version`:
    # docker version
    Client version: 1.6.0
    Client API version: 1.18
    Go version (client): go1.4.2
    Git commit (client): 8aae715/1.6.0
    OS/Arch (client): linux/amd64
    Server version: 1.6.0
    Server API version: 1.18
    Go version (server): go1.4.2
    Git commit (server): 8aae715/1.6.0
    OS/Arch (server): linux/amd64

`docker -D info`:
    # docker -D info
    Containers: 1
    Images: 1
    Storage Driver: devicemapper
    Pool Name: docker-199:1001-7-pool
    Pool Blocksize: 65.54 kB
    Backing Filesystem: <unknown>
    Data file: /dev/loop0
    Metadata file: /dev/loop1
    Data Space Used: 494.2 MB
    Data Space Total: 107.4 GB
    Data Space Available: 533.7 MB
    Metadata Space Used: 892.9 kB
    Metadata Space Total: 2.147 GB
    Metadata Space Available: 533.7 MB
    Udev Sync Supported: true
    Data loop file: /vol1/devicemapper/devicemapper/data
    Metadata loop file: /vol1/devicemapper/devicemapper/metadata
    Library Version: 1.02.93-RHEL7 (2015-01-28)
    Execution Driver: native-0.2
    Kernel Version: 3.10.0-123.el7.x86_64
    Operating System: Red Hat Enterprise Linux
    CPUs: 4
    Total Memory: 3.704 GiB
    Name: hostname.domainname
    ID: BIVC:C42E:JXWK:LIK5:B2FO:CZEG:55KY:WPQH:BBM2:ATRP:AFFB:IQVQ
    Debug mode (server): false
    Debug mode (client): true
    Fds: 13
    Goroutines: 18
    System Time: Thu Jul  9 14:43:27 UTC 2015
    EventsListeners: 0
    Init SHA1: 21f5d557e28d349916ae4c8466e0df0781deea4e
    Init Path: /usr/libexec/docker/dockerinit
    Docker Root Dir: /vol1

`uname -a`:

# uname -a
    Linux hostname.domainname 3.10.0-123.el7.x86_64 #1 SMP Mon May 5 11:16:57 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
1. Physical machine with RHEL7Update0 installed.
2. Veritas volume manager installed to manage logical volumes.
3. Veritas file system installed to manage file systems.
4. Volume and filesystem is created on SAN disk.

How reproducible:
Easily and consistently reproducible.

Steps to Reproduce:
1. Create disk group using vxdg cli
    # vxdg init dockerdg hitachi_vsp0_42bc hitachi_vsp0_42bd hitachi_vsp0_42be hitachi_vsp0_42b1

2. Create a veritas volume using vxassist cli
    # vxassist -g dockerdg make vol1 10G

3. Install vxfs filesystem on volume using mkfs.vxfs cli
    # mkfs.vxfs /dev/vx/rdsk/dockerdg/vol1 
    version 11 layout
    20971520 sectors, 10485760 blocks of size 1024, log size 16384 blocks
    rcq size 1024 blocks
    largefiles supported
    maxlink supported

4. Mount the filesystem
    # mount.vxfs /dev/vx/dsk/dockerdg/vol1 /vol1

    [root@vmr720-13 ~]# df -h | grep vol1
    /dev/vx/dsk/dockerdg/vol1   10G   21M  9.4G   1% /vol1

    [root@vmr720-13 ~]# mount | grep vol1
    /dev/vx/dsk/dockerdg/vol1 on /vol1 type vxfs (rw,delaylog,largefiles,ioerror=mwdisable)

5. Start Docker Daemon with /vol1 as root FS

    # docker -d -g /vol1 &
    [1] 1295
    # INFO[0000] +job serveapi(unix:///var/run/docker.sock)   
    INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
    ERRO[0000] WARNING: No --storage-opt dm.thinpooldev specified, using loopback; this    configuration is strongly discouraged for production use 
    INFO[0002] +job init_networkdriver()                    
    INFO[0002] -job init_networkdriver() = OK (0)           

   # INFO[0003] Loading containers: start.                   

    INFO[0003] Loading containers: done.                    
    INFO[0003] docker daemon: 1.6.0 8aae715/1.6.0; execdriver: native-0.2; graphdriver: devicemapper 
    INFO[0003] +job acceptconnections()                     
    INFO[0003] -job acceptconnections() = OK (0)            
    INFO[0003] Daemon has completed initialization          

# docker info
    INFO[0017] GET /v1.18/info                              
    INFO[0017] +job info()                                  
    INFO[0017] +job subscribers_count()                     
    INFO[0017] -job subscribers_count() = OK (0)            
    INFO[0017] +job registry_config()                       
    INFO[0017] -job registry_config() = OK (0)              
    INFO[0017] -job info() = OK (0)                         
    Containers: 0
    Images: 0
    Storage Driver: devicemapper
    Pool Name: docker-199:26000-5-pool
    Pool Blocksize: 65.54 kB
    Backing Filesystem: <unknown>
    Data file: /dev/loop4
    Metadata file: /dev/loop5
    Data Space Used: 307.2 MB
    Data Space Total: 107.4 GB
    Data Space Available: 10.4 GB
    Metadata Space Used: 733.2 kB
    Metadata Space Total: 2.147 GB
    Metadata Space Available: 2.147 GB
    Udev Sync Supported: true
    Data loop file: /vol1/devicemapper/devicemapper/data
    Metadata loop file: /vol1/devicemapper/devicemapper/metadata
    Library Version: 1.02.93-RHEL7 (2015-01-28)
    Execution Driver: native-0.2
    Kernel Version: 3.10.0-123.el7.x86_64
    Operating System: Red Hat Enterprise Linux
    CPUs: 32
    Total Memory: 62.72 GiB
    Name: machinename.domainname
    ID: UYJ7:CEU5:SGFF:X3SU:44UX:WPZN:T5BB:AFDZ:DLWQ:NTCI:KNYY:H2NJ

Actual Results:
Backing filesystem is shown as: "Backing Filesystem: <unknown>"

Expected Results:
Backing filesystem should be shown as: "Backing Filesystem: VxFS"

Additional info:
Magic Number os VxFS is: 0xa0501fcf5

Additional info can be provided as and when required.

**Comment by thaJeztah** [comment]
Duplicated by https://github.com/docker/docker/issues/14847, and a pull request to fix this https://github.com/docker/docker/pull/14940
