### ISSUE TITLE
Permissions on Docker tree

### ISSUE THREAD

**Issue by mdavranche** [docker/docker#14806]
As the Docker Unix socket's owner is root:docker and its permissions is 660 (what is a great thing), wouldn't it be legitimate to have a rootdir (ie /var/lib/docker/), containers rootdir (ie /var/lib/docker/containers/) and container dir (ie /var/lib/docker/containers/xxx_container_id_xxx/) with the same owner and permissions? The three of them now have the root:root owner and the 700 permissions.

Same question for the xxx_container_id_xxx-json.log, that have the 600 permissions whereas all the other files have the 644 ones (config.json, hostname.json, ...).

My needs: I have a daemon, looking for all my containers' logs and sending them to a GrayLog platform (without querying the Docker socket). This daemon now have to run as root, what is not good, I should run it as a user in the docker group.

Before I propose a pull request to fix this, do you agree with the design?

 # docker version
Client:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   5a29f0a
 Built:        Tue Jul 21 14:12:33 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   5a29f0a
 Built:        Tue Jul 21 14:12:33 UTC 2015
 OS/Arch:      linux/amd64

**Comment by phemmer** [comment]
> the xxx_container_id_xxx-json.log, that have the 600 permissions
> ...
> This daemon now have to run as root

You can solve this using filesystem ACLs:

```
setfacl -d -R -m u:graylog:r-X /var/lib/docker/containers
setfacl -R -m u:graylog:r-X /var/lib/docker/containers
```

The `graylog` user will now have full read access to `/var/lib/docker/containers`.

**Comment by mdavranche** [comment]
Thanks @phemmer for this workaround. Do you know if there is a good reason why there is such restrictive permissions? A user in the docker group can access everything through the Docker socket, why can't he access the Docker tree?

**Comment by thaJeztah** [comment]
I don't think there's a need to open up the permissions on these files. Apart from debugging, I think the files inside `/var/lib/docker` is an implementation detail that shouldn't be something that an end-user has to deal with. Grabbing the log-files directly from those directories is not something I think should be recommended.

Just out of interest, have you considered using the plugin drivers that are now part of docker?
https://github.com/docker/docker/blob/master/docs/reference/logging/index.md

**Comment by mdavranche** [comment]
I agree with that. Thanks for your advises about logging driver, that sounds great!

**Comment by thaJeztah** [comment]
You're welcome!
