### ISSUE TITLE
/etc/hosts: '172.17.0.X self' instead of `172.17.0.X {id}`

### ISSUE THREAD

**Issue by moldcraft** [docker/docker#14814]
This will be an easy way to get current container IP address (like `localhost`).
We will be able to use the `self` hostname (or any other name you will choose) in various configs where current host ip is required/needed.
For e.g. I need to specify [this](http://docs.datastax.com/en/cassandra/1.2/cassandra/configuration/configCassandra_yaml_r.html?scroll=reference_ds_qfg_n1r_1k__broadcast_address) and [this](http://docs.datastax.com/en/cassandra/1.2/cassandra/configuration/configCassandra_yaml_r.html?scroll=reference_ds_qfg_n1r_1k__listen_address).

**Comment by cpuguy83** [comment]
This really wouldn't work well.
It's fairly trivial to get the IP address of an interface, and also the hostname used is the actual hostname of the container, so `hostname` would return the same hostname used in /etc/hosts.

**Comment by moldcraft** [comment]
> This really wouldn't work well.

Why? It's very simple, just add a new line in `/etc/hosts` after id hostname

```
172.17.0.X {id}
172.17.0.X self
```

> `hostname` would return the same hostname used in /etc/hosts

It's a command that needs to be executed. But I have a text config

```
foo: 'bar'
hello: 'world'
address: '...' <-----
```

which hostname should I put there?

----

An solution would be: on container startup, to use `sed` to replace that line with `hostname` result.
But the solution I request would make things easier.

**Comment by cpuguy83** [comment]
Using self just doesn't make sense and is not standard anywhere.
This is the purpose of hostnames.

I'm going to close this unless you can point me to somewhere where this would be an expectation from a Linux OS.
