### ISSUE TITLE
ONBUILD RUN data persistence

### ISSUE THREAD

**Issue by anapsix** [docker/docker#14834]
In Docker 1.7.1 (and possibly earlier)..
Data written by ONBUILD RUN doesn't persist in dirs which parent exports with VOLUME.  
In other words, If **parent** image with `VOLUME /app` has some sort of ONBUILD RUN step that makes changes to /app, those changes will not persist in resulting **child** image.

Parent image:
```
FROM busybox
RUN mkdir /app && touch /app/step1
ONBUILD RUN touch /app/step2
VOLUME /app
CMD ls -ltr /app
```

Child image:
```
FROM parent
RUN touch /app/step3
```

**Comment by duglin** [comment]
This is working as designed.  Volumes are not saved within the resulting image.
ping @cpuguy83 to keep my honest.

**Comment by cpuguy83** [comment]
You are correct, you cannot make changes to volume dirs during build. You want want to reconsider the usage of "VOLUME" at all in your Dockerfile.

Closing as this is expected behavior.
