### ISSUE TITLE
Unable to reach host ip:port from container using bridge network on CentOS

### ISSUE THREAD

**Issue by tnachen** [docker/docker#14836]
BUG REPORT INFORMATION

With the following docker version:
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): ba1f6c3/1.6.2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): ba1f6c3/1.6.2
OS/Arch (server): linux/amd64

I'm not able to reach the host ip port from the container.

Basically the following fails:

from the host:

$ nc -l 9999

another terminal:

docker run --net=bridge ubuntu:14.04 /bin/sh -c "echo 'hi' | nc `hostname -i` 9999"

When running the above test in Ubuntu 14.04 with the same docker version 1.6.2 you'll see the ncat listen output hi and exits, but on CentOS it never receives the message.

Wierd part is that I'm able to ping the host ip, but somehow with a port it doesn't work.

**Comment by cpuguy83** [comment]
Maybe I don't understand, but in the container `hostname -i` would yield the ip address of the container, not the host.

**Comment by phemmer** [comment]
What is the error you get? Connection refused, host lookup failed, timeout while connecting, ... ?

Does the centos box have any iptables rules on it?

What does `hostname -i` output on the centos box?

**Comment by phemmer** [comment]
@cpuguy83 

    docker run --net=bridge ubuntu:14.04 /bin/sh -c "echo 'hi' | nc `hostname -i` 9999"

The `hostname -i` part evaluates on the host, not in the container (double quotes, not single)

**Comment by cpuguy83** [comment]
@phemmer Aaah, thanks I see now.

**Comment by tnachen** [comment]
So im actually using another image tnachen/test-executor and it simply says cannot route to that IP address right away

**Comment by tnachen** [comment]
And actually 1.7.0 with Ubuntu the same steps listed in the pr doesn't work as well, I believe with standard settings for docker and OS

**Comment by tnachen** [comment]
@phemmer host name -I returned 172.16.0.12 for me

**Comment by mrjana** [comment]
@tnachen Is `firewalld` running in your CentOS host?

**Comment by cpuguy83** [comment]
@tnachen Any word?

**Comment by thaJeztah** [comment]
closing because there was no response, but happy to reopen if this is still an issue on the current release
