### ISSUE TITLE
run  "TESTFLAGS='-check.f TestBuild*' hack/make.sh binary test-integration-cli" gets error in lxc

### ISSUE THREAD

**Issue by azurezk** [docker/docker#14841]
I run that command in my docker development container as "https://docs.docker.com/project/test-and-docs/#run-tests-on-your-local-host" says and get 
"Get http:///go/src/github.com/docker/docker/bundles/1.8.0-dev/test-integration-cli/docker.sock/v1.20/version: dial unix /go/src/github.com/docker/docker/bundles/1.8.0-dev/test-integration-cli/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
---> Making bundle: .integration-daemon-stop (in bundles/1.8.0-dev/test-integration-cli)
" at the end.  And I already run docker daemon "docker -dD" in  my container. 

I check hack/make.sh and found a comment says 
"# If $TESTFLAGS is set in the environment, it is passed as extra arguments to 'go test'.
"# You can use this to select certain tests to run, eg.
"#
"#     TESTFLAGS='-test.run ^TestBuild$' ./hack/make.sh test-unit"
I try the command and it gets result well. 

And also the hack/make.sh has comment 
"# For integration-cli test, we use [gocheck](https://labix.org/gocheck), if you want
"# to run certain tests on your local host, you should run with command:
"#
"#     TESTFLAGS='-check.f DockerSuite.TestBuild*' ./hack/make.sh binary test-integration-cli"
When in localhost should I use "make" instead of "hack/make.sh"? like "TESTFLAGS='-check.f DockerSuite.TestBuild*' make test-integration-cli"?

My container docker version is 
Client:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   98907c4-dirty
 Built:        Tue Jul 21 09:48:15 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   98907c4-dirty
 Built:        Tue Jul 21 09:48:15 UTC 2015
 OS/Arch:      linux/amd64

My localhost docker version is 
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): darwin/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64

**Comment by cpuguy83** [comment]
You can run locally by initiating `hack/make.sh <command>` scripts. Generally this is expected to be run in a container.
To instantiate a container, use `make <command>`

Thanks!
