### ISSUE TITLE
Remote API - /images/search has text/plain Content-Type, not application/json

### ISSUE THREAD

**Issue by maseev** [docker/docker#14846]
BUG REPORT INFORMATION

Description of problem:
/images/search REST endpoint for some reasons returns Content-Type = text/plain instead of application/json. There's certainly some inconsistency with documentation, because documentation says that GET /images/search has to return Content-Type: application/json - https://docs.docker.com/reference/api/docker_remote_api_v1.19/.

`docker version`:
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64

`docker info`:
Containers: 16
Images: 38
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 70
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-43-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 3.767 GiB
Name: evilmachine
ID: KHKF:433U:3AFM:YDZX:JSRG:24FE:KZQU:ZHSH:NRJG:7YVK:LLZX:TKXX
WARNING: No swap limit support

`uname -a`:
Linux evilmachine 3.16.0-43-generic #58~14.04.1-Ubuntu SMP Mon Jun 22 10:21:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

How reproducible:
Send GET request to /images/search. Content-Type application/json is expected, but text/plain returns instead.

Steps to Reproduce:
1. Send GET request to /images/search?term=test
2. Check Content-Type that was returned with the response
3. Content-Type has to be application/son

Actual Results:
GET /images/search returns Content-type = text/plain

Expected Results:
GET /images/search has to return Content-Type = application/json

**Comment by runcom** [comment]
Thanks for the report, found the problem, fixing
