### ISSUE TITLE
How to give custom NAME to docker container?

### ISSUE THREAD

**Issue by shyamjithkv** [docker/docker#14849]
Hi,
I am new to docker and my question is , How to  give custom name  to my docker container

running sudo docker ps show the NAME of my docker as "prickly_kirch" .Why this name, shall i give my own name there??

**Comment by runcom** [comment]
@shyamjithkv There's a `--name` option for `docker run` e.g. `docker run -d --name  "yay" busybox top` will show NAME yay in `docker ps`

Closing as a non issue, if I'm mistaken please ping me to reopen
Also, if you have this kind of question it's better to come on IRC in #docker-dev and ask
