### ISSUE TITLE
Cannot build the latest "master"

### ISSUE THREAD

**Issue by Ramzec** [docker/docker#14866]
<pre>
Linux nix-devel1 4.0.5-gentoo #1 SMP Sun Jul 12 17:26:24 MSK 2015 x86_64 Intel(R) Core(TM) i7 CPU 930 @ 2.80GHz GenuineIntel GNU/Linux
</pre>

<pre>
Client:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   96d2071-dirty
 Built:        Tue Jul 14 13:14:25 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d965136-dirty
 Built:        Thu Jul  9 13:47:11 UTC 2015
 OS/Arch:      linux/amd64
</pre>

The first error:
<pre>
Step 11 : RUN curl -sSL https://golang.org/dl/go${GO_VERSION}.src.tar.gz | tar -v -C /usr/local -xz     && mkdir -p /go/bin
 ---> Running in 725e63373ae4
curl: (60) SSL certificate problem: certificate is not yet valid
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
INFO[0285] The command '/bin/sh -c curl -sSL https://golang.org/dl/go${GO_VERSION}.src.tar.gz | tar -v -C /usr/local -xz        && mkdir -p /go/bin' returned a non-zero code: 2 
Makefile:74: recipe for target 'build' failed
make: *** [build] Error 2
</pre>

I added "-k" to the correspond cmd in Dockerfile, run the build and it fails again.

The second error:

<pre>
+ go get -v -d github.com/cpuguy83/go-md2man
package code.google.com/p/go.net/html: Get https://code.google.com/p/go/source/checkout?repo=net: x509: certificate has expired or is not yet valid
INFO[0008] The command '/bin/sh -c set -x       && export GOPATH="$(mktemp -d)" && export GIT_SSL_NO_VERIFY=true        && git clone -b v1.0.3 https://github.com/cpuguy83/go-md2man.git "$GOPATH/src/github.com/cpuguy83/go-md2man"    && git clone -b v1.2 https://github.com/russross/blackfriday.git "$GOPATH/src/github.com/russross/blackfriday"  && go get -v -d github.com/cpuguy83/go-md2man   && go build -v -o /usr/local/bin/go-md2man github.com/cpuguy83/go-md2man        && rm -rf "$GOPATH"' returned a non-zero code: 1 
Makefile:74: recipe for target 'build' failed
make: *** [build] Error 1
</pre>

**Comment by cpuguy83** [comment]
Are you behind a corporate proxy or something?

**Comment by Ramzec** [comment]
no, i have no proxy. Yesterday i had no issues. Today i pulled the latest changes. After that i cannot build.

**Comment by phemmer** [comment]
Check your system clock. I have a feeling it might be off by a few years.

**Comment by Ramzec** [comment]
Patrick, big thanks. I was in the past :-)
The issue can be closed, sorry for troubling.

**Comment by scifisamurai** [comment]
@phemmer Thank you!  I was getting that "certificate is not yet valid" error when trying to use https://github.com/sstephenson/ruby-build (which uses curl to download and install versions of ruby) on Arch Linux in a vm.  Turns out the clock was a few months behind.  I reset it using https://wiki.archlinux.org/index.php/Time and it started working.
