### ISSUE TITLE
Weird error when using docker exec

### ISSUE THREAD

**Issue by frioux** [docker/docker#14876]
I made a little repo to try to demonstrate a separate issue (which I'll post once this one is somehow resolved): https://github.com/frioux/agent-test.

On my computer I can run

```
make build
make fail
```

and I get the following unusual error:

`nsenter: Failed to open ns file /proc/963543/ns for ns ipc: No such file or directory`

At the very least the error should be more clear, but as far as I can tell I'm not doing anything incorrect, so there may be a bigger issue here.

**Comment by frioux** [comment]
Sorry about that!  I did look through the issues and couldn't find another similar issue.

```
docker version: Client version: 1.7.1
                Client API version: 1.19
                Go version (client): go1.4.2
                Git commit (client): 786b29d
                OS/Arch (client): linux/amd64
                Server version: 1.7.1
                Server API version: 1.19
                Go version (server): go1.4.2
                Git commit (server): 786b29d
                OS/Arch (server): linux/amd64

docker info: Containers: 4
             Images: 128
             Storage Driver: overlay
              Backing Filesystem: extfs
             Execution Driver: native-0.2
             Logging Driver: json-file
             Kernel Version: 3.19.0-21-generic
             Operating System: Ubuntu 15.04
             CPUs: 4
             Total Memory: 15.37 GiB
             Name: zfp
             ID: WWAV:EBRG:XQKU:LLZ7:JUMU:MDR4:BPJ4:C7T3:XKVQ:WFUT:3DAP:6ZHU
             WARNING: No swap limit support

uname -a: Linux zfp 3.19.0-21-generic #21-Ubuntu SMP Sun Jun 14 18:31:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Steps to reproduce issue:

1. git clone git@github.com/frioux/agent-test
2. cd agent-test
3. make build
4. make fail

I expected to see either a list of ssh-keys or a strange error related to ssh-agent permissions

Instead I see an error related to docker exec itself.

**Comment by cpuguy83** [comment]
This looks like it may be that you are starting cash without -t, and so it stops immediately, but is running for long enough for your exec command to fire.

**Comment by cpuguy83** [comment]
*bash, darn phone...

Bash needs a tty otherwise it will exit.

**Comment by frioux** [comment]
Thanks @cpuguy83!  I should have realized that there was some kind of race condition.  There could theoretically be a better error message nonetheless.  I'll let you decide if you want to just close this because it's so weird

**Comment by cpuguy83** [comment]
@frioux Did your error message include `error response from daemon`?

**Comment by frioux** [comment]
No, it was exactly as I pasted.

-- 
sent from a rotary phone, pardon my brevity

@frioux <https://github.com/frioux> Did your error message include error
response from daemon?

—
Reply to this email directly or view it on GitHub
<https://github.com/docker/docker/issues/14876#issuecomment-125315909>.

**Comment by thaJeztah** [comment]
@cpuguy83 what's the status here; is there a way to handle this and output a better error message?

**Comment by cpuguy83** [comment]
Yes, it looks like we can improve this. I'll have something up in a few mins.
Right now it's just returning the low-level error which is not good.

**Comment by cpuguy83** [comment]
#15446

**Comment by thaJeztah** [comment]
Thanks @cpuguy83 !
