### ISSUE TITLE
typo on website

### ISSUE THREAD

**Issue by dhbarnett** [docker/docker#14879]
In your tutorial documentation on https://docs.docker.com/mac/step_four/ you have in steap 1.5:

CMD /usr/games/fortunes -a | cowsay

and then on step 2.2:

CMD /usr/games/fortune -a | cowsay # Singular fortune

The 2nd example is correct.

**Comment by dhbarnett** [comment]
docker version: None
docker info: The website
uname -a: my name minus a would be Dvid

Provide additional environment details (AWS, VirtualBox, physical, etc.): Website

List the steps to reproduce the issue:
1. Go to the website
2. Look at the what I submitted before the bot rejected me.

**Comment by thaJeztah** [comment]
Thanks for reporting this @dhbarnett the page you're referring to is actually in a separate repository, and can be found here: https://github.com/docker/tutorials/blob/master/docs/mac/step_four.md

Are you interested in contributing, and creating a pull request in that repository?

**Comment by dhbarnett** [comment]
Perhaps. Right now I'm still trying to figure out what docker is!

**Comment by thaJeztah** [comment]
> Right now I'm still trying to figure out what docker is!

It's an open source project, that is run by many people and always welcomes new contributors. The project is backed by a great community to help users "use", maintainers "maintain", and contributors "contribute".

Just joking. No worries, I'll have a look at this later.

Reporting issues is also contributing - much appreciated!

**Comment by charleswhchan** [comment]
#dibs

**Comment by charleswhchan** [comment]
PR: https://github.com/docker/tutorials/pull/13

@thaJeztah: Just out of curiosity, why are these docs stored in a separate repo? Is the plan to merge these into the main docker repo? Or extract all docs into the separate repo? :relaxed:

**Comment by thaJeztah** [comment]
@charleswhchan Great!  And.. good question, I don't know why they're in a separate repo. I think the repo was "private" before and only recently opened up, but not sure. We like to keep the docs together with the code for each project (docker, compose, swarm etc) so that docs and code can be updated and reviewed in the same PR. But you're right that these tutorials could be in this repository (I think)

@moxiegirl any reason to keep the tutorials in a separate repo?

**Comment by moxiegirl** [comment]
@charleswhchan Why is this in this repo? This content is part of a special project. The content is structured in a specific way to support a a particular output with its own unique look and feel.  In the future, we will most likely add other tutorials that are handled in a similar way.

**Comment by charleswhchan** [comment]
@moxiegirl Thanks for the clarifications. :+1:

**Comment by thaJeztah** [comment]
https://github.com/docker/tutorials/pull/13 was merged, so this will be fixed when the docs are published again. Thanks!
