### ISSUE TITLE
network down while making image using 1.7.0 release

### ISSUE THREAD

**Issue by moypray** [docker/docker#14888]
I met a issue:
Test Case:
  1. setup HTTPs docker daemon in a Server using TCP ports:  [this Server named "Deamon Server"]
     docker -dD -H tcp://0.0.0.0:6789  --tlsverify --tlscacert=/root/.docker/certs/ca.pem --tlskey=/root/.docker/certs/server-key.pem --tlscert=/root/.docker/certs/server-cert.pem
  2.  on another Server [named client Server], I run a container [for simple,any container would be ok]. and I will build image in this container,  Dockerfile as below:
   FROM busybox:latest
   RUN while true; do date;sleep 300; done

  in a container which run in Client Server, using build command to build this image:
   docker build -t test:latest  .

at the beginning 10 minutes, there is "date" output in client Server, but after about 30 minutes [it is not stable number], the connection between docker client and docker daemon is cut down. 
the Client Server no longer has output and  in docker daemon log, there is "Client disconnected, cancelling job: xxx" output, 
using netstat, we can not see the connection anymore.

but if I run docker build using the same dockerfile in Daemon Server and NOT in container, the connection will be fined [this test lasts for about 3 days, we can see "date" output.]

so it might be a problem.

root@build1:/home/wt# docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 7731c46-dirty
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 7731c46-dirty
OS/Arch (server): linux/amd64

root@build1:/home/wt# docker info
Containers: 3
Images: 127
Storage Driver: devicemapper
 Pool Name: docker-253:1-261371-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.46 GB
 Data Space Total: 107.4 GB
 Data Space Available: 13.29 GB
 Metadata Space Used: 6.291 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.141 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-39-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 1
Total Memory: 1.955 GiB
Name: build1
ID: WG2F:6RCQ:NSX6:ZYSP:XEGZ:YLVD:GIO6:RAZH:VXNH:Y7BP:PRR2:GIRG

client server:
root@build1:/home/wt# uname -a
Linux build1 3.13.0-39-generic #66-Ubuntu SMP Tue Oct 28 13:30:27 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

daemon server:
root@test6:~# uname -a
Linux test6 3.13.0-39-generic #66-Ubuntu SMP Tue Oct 28 13:30:27 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by moypray** [comment]
hi , if use HTTP not HTTPs, the result is the same

**Comment by moypray** [comment]
Today, I do more tests,  the build command run on Client Server only, not in a  container.
For 1.7.0 docker, the connection will be cut down too.

**Comment by cpuguy83** [comment]
Can you post exact reproducible steps?
It's also not clear what exactly are the actions you are taking or what is happening. Can you help me understand?

**Comment by cpuguy83** [comment]
Closing due to no response.
If you can provide some more detail, please ping here so we can take a look.
Thanks!

**Comment by moypray** [comment]
@cpuguy83 , sorry , this is my openstack VM bugs. These days I am working on it , not reply, sorry.
