### ISSUE TITLE
Is the query parameter 'filter' for '/images' officially supported ?

### ISSUE THREAD

**Issue by rhuss** [docker/docker#14894]
The query parameter [filter](https://github.com/docker/docker/blob/7e4db0a3704b3f156e6a67ce32a7fcada61fdef1/api/server/server.go#L358) can be used in `GET /images/json?filter=myname` to match on image name. This is not documented so I wonder whether this is an official feature on can rely on ?

BTW, `filter` doesn't work well with default registries `index.docker.io` and `docker.io`. I.e. if you create an  image `docker.io/myimage` and try to get it back with `GET /images/json?filter=docker.io/myimage` you get an empty list.

**Comment by duglin** [comment]
@rhuss does it work if you leave off the docker.io part of the filter?

**Comment by rhuss** [comment]
Yes, the filter must be set literally as show when doing a `docker images`. So, when you do a `docker build -t docker.io/myimage` it appears as `myimage` in `docker images`. When searching with `filter=myimage` the image is found, but not with `filter=docker.io/myimage`.

For inspecting bot `GET /images/myimage/json` and `GET /images/docker.io%2Fmyimage/json` work.
