### ISSUE TITLE
Get https://index.docker.io/v1/repositories/library/hello-world/images

### ISSUE THREAD

**Issue by rajeshgotur** [docker/docker#14892]
Hi
 I am getting the below error while installing Docket Initially; followed the below steps - 
1.Clicked the icon to launch a Boot2Docker terminal.
2. Allowed VirtualBox to make changes to your computer. The terminal did several things to set up Boot2Docker.
3.The terminal displayed the $ prompt.
4.Typed docker run hello-world command with office network. Got below error (probably because of Firewall)
Rajesh.Gotur@WKSBAN04GFA013 ~
$ docker run hello-world
Unable to find image 'hello-world:latest' locally
Pulling repository hello-world
Get https://index.docker.io/v1/repositories/library/hello-world/images: dial tcp
 54.174.226.171:443: connection refused.

5. The connected to separate wireless network (Reliance netconnect- a wireless broadband internet bypassing firewall) got the below error- 

Rajesh.Gotur@WKSBAN04GFA013 ~
$ docker run hello-world
Unable to find image 'hello-world:latest' locally
Pulling repository hello-world
Get https://index.docker.io/v1/repositories/library/hello-world/images: dial tcp
 54.174.226.171:443: connection refused

$ docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): windows/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64

I need help...
Regards
Rajesh Gotur

**Comment by rajeshgotur** [comment]
Hi I searched it, Looks like a new issue. But don't thin it is bug.

**Comment by rajeshgotur** [comment]
Hi

I resolved the above and followed the below steps

1. boot2docker delete && boot2docker init && boot2docker up && $(boot2docker shellinit) 
2.To connect the Docker client to the Docker daemon, please set:
  export DOCKER_HOST=tcp://192.168.59.103:2376
  export DOCKER_CERT_PATH='/C/Users/rajesh.gotur/.boot2docker/certs/boot2docker-vm'
  export DOCKER_TLS_VERIFY=1

3.$ docker run hello-world

**Comment by thaJeztah** [comment]
Thanks @rajeshgotur. I'll close this issue then.

**Comment by rajeshgotur** [comment]
My pleasure....

This issue can be closed.

**Comment by rama-krishna** [comment]
Hi Rajesh,

can you please throw some light on 
1. boot2docker delete && boot2docker init && boot2docker up && $(boot2docker shellinit)

**Comment by rama-krishna** [comment]
Hi,

Actually, I'm facing the same issue with Docker Toolbox, can you please suggest me the solution.

Thanks,
