### ISSUE TITLE
Installer script fails

### ISSUE THREAD

**Issue by saschaarthur** [docker/docker#14911]
Hey,

I want to inform you that your installer script (curl -sSL https://get.docker.com/ | sh) fails for debian 8.1.

The reason:

Your Code:

    if [ -z "$lsb_dist" ] && [ -r /etc/lsb-release ]; then
        lsb_dist="$(. /etc/lsb-release && echo "$DISTRIB_ID")"
        dist_version="$(. /etc/lsb-release && echo "$DISTRIB_CODENAME")"
    fi

The file which leads to the fail:

    # cat /etc/lsb-release
    DISTRIB_ID=Debian
    DISTRIB_RELEASE=8
    DISTRIB_CODENAME=
    DISTRIB_DESCRIPTION=

Whats wrong:

it copys "deb https://apt.dockerproject.org/repo debian- main" to repo ist, but it should be "deb https://apt.dockerproject.org/repo debian-jessie main"

**Comment by thaJeztah** [comment]
ping @jfrazelle @tianon if I understand correctly, debian 8.1 doesn't have a codename here? Is that something we should / can fix, or with debian upstream?

**Comment by jfrazelle** [comment]
I run 8.1 and tested this :/

**Comment by jfrazelle** [comment]
But ya we can fix this, not today tho for me unless someone makes a PR ;)

**Comment by jfrazelle** [comment]
The PR should be to check both codename and _RELEASE

**Comment by thaJeztah** [comment]
> not today tho for me unless someone makes a PR ;)

No worries, I was just browsing through issues on a rainy Sunday.

@saschaarthur are you interested in creating a PR to fix this?

**Comment by runcom** [comment]
see #15015

**Comment by thaJeztah** [comment]
Oh, thanks @runcom, that was fast!

**Comment by runcom** [comment]
sorry, I had the PR ready before and didn't read here :(
