### ISSUE TITLE
Installer does not work any more for LinuxMint

### ISSUE THREAD

**Issue by thomasbilk** [docker/docker#14916]
Description of problem:
Commit 451d3f5950b removed the support for Linux Mint.

`docker version`:
 
    command not found: docker

`docker info`:

    command not found: docker

`uname -a`:

    Linux flatland 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
Linux Mint 64 bit latest version 17.2

How reproducible:
Follow the instructions from the Ubuntu install docs which results in this:

    Either your platform is not easily detectable, is not supported by this
    installer script (yet - PRs welcome! [hack/install.sh]), or does not yet have
    a package for Docker.  Please visit the following URL for more detailed
    installation instructions:

    https://docs.docker.com/en/latest/installation/

Additional info:
Commit 451d3f5950b is the culprit.

**Comment by jcuga** [comment]
I have the same issue with mint 17

3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

RELEASE=17
CODENAME=qiana
EDITION="Cinnamon 64-bit"
DESCRIPTION="Linux Mint 17 Qiana"
DESKTOP=Gnome
TOOLKIT=GTK
GRUB_TITLE=Linux Mint 17 Cinnamon 64-bit

**Comment by ewindisch** [comment]
should be addressed by https://github.com/docker/docker/pull/14910

**Comment by thomasbilk** [comment]
Great. So this issue can probably be closed. Thank you.
