### ISSUE TITLE
Install script pulls LSB Codename as dist_version on RHEL/clones which isn't correct

### ISSUE THREAD

**Issue by Djelibeybi** [docker/docker#14924]
In ```hack/install.sh```, the first method of determining distro name and version is via lsb_release:

    if command_exists lsb_release; then
                lsb_dist="$(lsb_release -si)"
                dist_version="$(lsb_release --codename | cut -f2)"
    fi

This works great for Debian/Ubuntu repos which use the codename in the path, but is not so great for RHEL/Fedora (and clones) who don't. If a RHEL/Fedora machine has lsb_release installed, the install.sh fails:

    # curl -sSL https://get.docker.com/ | sh
    sh: line 249: [: TwentyTwo: integer expression expected
    + sh -c 'sleep 3; yum -y -q install docker-engine'
    Yum command has been deprecated, redirecting to '/usr/bin/dnf -y -q install docker-engine'.
    See 'man dnf' and 'man yum2dnf' for more information.
    To transfer transaction metadata from yum to DNF, run:
    'dnf install python-dnf-plugins-extras-migrate && dnf-2 migrate'

    Failed to synchronize cache for repo 'docker-main-repo' from 'https://yum.dockerproject.org/repo/main/fedora/TwentyTwo': Cannot download repomd.xml: Cannot     download repodata/repomd.xml: All mirrors were tried, disabling.
    Error: no package matched: docker-engine

Because the ```dist_version``` returned from ```lsb_release --codename``` is ```TwentyTwo``` on Fedora. On RHEL, it'll return something like ```Maipo``` for RHEL7 and it'll return ```n/a``` on Oracle Linux (which doesn't use codenames).

**Comment by levinmr** [comment]
+1
