### ISSUE TITLE
Storage on Docker

### ISSUE THREAD

**Issue by krishna555Storage** [docker/docker#14938]
Hi Guys,

    Can we map LVM or ceph volume on a docker container to use it as an external storage. Is there a way to map ISCSI targets on container?I tried logging in to the target and i get error. Help is much appreciated. thanks.

Krishna. 
Cloud Storage

**Comment by cpuguy83** [comment]
Yes, but you have to set these up manually on the host then bind-mount them in, or mount directly from in the container (which requires the SYS_ADMIN cap.. which basically makes it insecure).
To mount host file/dirs `docker run -v /path/on/host:/path/in/container`

In the experimental channel (and stable in docker 1.8) we have support for volume plugins that would enable you to write plugins that manage lvm or ceph to handle this automatically for you by specifying the `--volume-driver` option on `docker run`.
