### ISSUE TITLE
Can not reference locally-built image using FROM at dockerfile

### ISSUE THREAD

**Issue by Dmitriusan** [docker/docker#14943]
This used to be possible some time ago http://stackoverflow.com/questions/20481225/how-can-i-use-a-local-image-as-the-base-image-with-a-dockerfile

What I'm trying to do, is to build image locally:
```
REPOSITORY                           TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
base-www-image_img                   latest              f5998cc568b5        16 minutes ago      290.5 MB
dmitriusan/base-www-image_img        latest              f5998cc568b5        16 minutes ago      290.5 MB
```
and then specify it in FROM statement of a dockerfile. Tried both base-www-image_img and dmitriusan/base-www-image_img , but neither works:

```
docker build --rm=true -t www.my.container_img --pull=true /opt/payload/www-container
Sending build context to Docker daemon  7.68 kB
Sending build context to Docker daemon 
Step 0 : FROM dmitriusan/base-www-image_img
Pulling repository dmitriusan/base-www-image_img
Error: image dmitriusan/base-www-image_img:latest not found
```

```
docker build --rm=true -t www.my.container_img --pull=true /opt/payload/www-container
Sending build context to Docker daemon  7.68 kB
Sending build context to Docker daemon 
Step 0 : FROM base-www-image_img
Pulling repository base-www-image_img
Error: image library/base-www-image_img:latest not found
```

Is it desired to be supported? Could not find any mentions in official documentation.

BUG REPORT INFORMATION 

docker version:
Docker version 1.7.0, build 0baf609
docker info:
Containers: 49
Images: 425
Storage Driver: aufs
 Root Dir: /media/vconts/docker/aufs
 Backing Filesystem: extfs
 Dirs: 525
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-44-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 24
Total Memory: 62.9 GiB
Name: sigrid14
ID: XXXX
WARNING: No swap limit support

uname -a:
Linux sigrid14 3.16.0-44-generic #59~14.04.1-Ubuntu SMP Tue Jul 7 15:07:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by coolljt0725** [comment]
if you want use the local image as the base image, please without the option `--pull=true`, `--pull=true` will  always attempt to pull a newer version of the image.

**Comment by Dmitriusan** [comment]
Thank you! My bad :)
