### ISSUE TITLE
docker not logging to journald on centos 7 when journald logging driver is specified

### ISSUE THREAD

**Issue by pfremm** [docker/docker#14948]
I installed docker 1.7.1 rpm available here: https://get.docker.com/rpm/1.7.1/centos-7/RPMS/x86_64/docker-engine-1.7.1-1.el7.centos.x86_64.rpm

Options attempted: 
1. Configuring either the service in systemd to reference the journald logging driver.
2.Specifying it as a command line flag when running the container.

Docker recognizes the journald flag as when I run the docker logs command for a container it does state the journald logging driver is being used.

I have watch the journal as I start container with journalctl -follow and I do not see any of my container logs.  I've also tried the following command and always see only a empty journal

journalctl CONTAINER_NAME=containername
journalctl MESSAGE_ID=containeridhere

My application logs do show up directly in the container logs in json format when I do not specify a logging driver.

**Comment by LK4D4** [comment]
ping @rhatdan 
Any ideas? Maybe journald changed protocol?

**Comment by rhatdan** [comment]
Not sure this works on RHEL7/Centos7 yet,  I am not sure if anyone has tested it.  I know that systemd will be getting updated in RHEL7.2 time frame.

**Comment by rhatdan** [comment]
@pfremm Open a bugzilla on this for RHEL so that we have our QE Team test it.  But I know that the systemd/journald on RHEL7  is fairly old.  Does not support RegisterMachine protocol yet for example.

**Comment by nalind** [comment]
@pfremm Do you have the exact version number for the systemd package you're running?  I've tried with both 208-11.el7_0.4 and 208-20.el7_1.5, and they both produce messages when I run `journalctl CONTAINER_NAME=naughty_kirch` or `journalctl CONTAINER_ID_FULL=0326f4ce99b9c96b564a5b539587416751e75ec8c63ac56962f4632f009b93f3` (the `CONTAINER_ID` variable in the messages is set to the first 12 characters of the container ID, so matching with `CONTAINER_ID=0326f4ce99b9` also works here).

**Comment by nalind** [comment]
I did have to run `journalctl` as root, though.

**Comment by pfremm** [comment]
Yeah, I did run it as root as well, but I had upgraded my centos server from docker 1.6 to 1.7.  Now starting fresh with docker 1.7 from the docker website this does seem to be working.

**Comment by pfremm** [comment]
I have this working now without issues.

**Comment by n1t1nv3rma** [comment]
It's still not working! 

[root@master ~]# uname -a 
Linux master.localdomain 3.10.0-327.36.1.el7.x86_64 #1 SMP Sun Sep 18 13:04:29 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

[root@master ~]# more /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 

[root@master ~]# docker -v
Docker version 1.12.1, build 23cf638

[root@master ~]# docker info | grep -i log
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
WARNING: bridge-nf-call-ip6tables is disabled
Logging Driver: journald

[root@master ~]# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
755910e1b599        busybox             "/bin/sh -c 'while sl"   3 hours ago         Up 17 minutes                           desperate_easley

[root@master ~]# docker logs desperate_easley | tail -2
Wed Jul 13 09:05:54 UTC 2016
Wed Jul 13 09:05:59 UTC 2016

[root@master ~]# journalctl CONTAINER_NAME=desperate_easley
-- Logs begin at Wed 2016-07-13 01:17:15 EDT, end at Wed 2016-07-13 05:01:01 EDT. --
[root@master ~]#


Any idea?

**Comment by nalind** [comment]
Please double-check that the container was also launched to use the journal logging driver (`docker inspect -f '{{.HostConfig.LogConfig.Type}}' desperate_easley`).

Are you using the build from https://get.docker.com/builds/Linux/x86_64/docker-1.12.1.tgz, or an RPM package from https://yum.dockerproject.org/repo/main/centos/7/Packages/?  The first appears to be a static binary.  The library that is used for reading the journal is not available for static builds, so I wouldn't expect that copy of dockerd to have been built with support for reading the journal.  The RPM packaged version links dynamically, so it should be able to read from the journal.

**Comment by n1t1nv3rma** [comment]
Correct! Thanks @nalind  !

The container wasn't using the journal logging driver :( 

[root@master ~]# docker inspect -f '{{.HostConfig.LogConfig.Type}}'  desperate_easley 
json-file
[root@master ~]#

Not sure what happened, I thought it was installed via Centos Docker Repo only... I just removed and  installed via Yum and it seems to be working fine now!

[vagrant@master ~]$ docker inspect -f '{{.HostConfig.LogConfig.Type}}'  tender_bose
journald
[vagrant@master ~]$ 

Now my other worry is that it doesn't show the container name, ID etc in the logs, as per [https://docs.docker.com/engine/admin/logging/journald/](https://docs.docker.com/engine/admin/logging/journald/) ? **Any idea?** 

[vagrant@master ~]$ sudo journalctl -f
-- Logs begin at Wed 2016-07-13 01:17:15 EDT. --
Jul 13 07:13:43 master.localdomain dockerd[19697]: Wed Jul 13 11:13:43 UTC 2016
Jul 13 07:13:48 master.localdomain dockerd[19697]: Wed Jul 13 11:13:48 UTC 2016
Jul 13 07:13:53 master.localdomain dockerd[19697]: Wed Jul 13 11:13:53 UTC 2016
Jul 13 07:13:58 master.localdomain dockerd[19697]: Wed Jul 13 11:13:58 UTC 2016
Jul 13 07:14:03 master.localdomain dockerd[19697]: Wed Jul 13 11:14:03 UTC 2016
Jul 13 07:14:08 master.localdomain dockerd[19697]: Wed Jul 13 11:14:08 UTC 2016
Jul 13 07:14:13 master.localdomain dockerd[19697]: Wed Jul 13 11:14:13 UTC 2016
Jul 13 07:14:18 master.localdomain dockerd[19697]: Wed Jul 13 11:14:18 UTC 2016
Jul 13 07:14:23 master.localdomain dockerd[19697]: Wed Jul 13 11:14:23 UTC 2016


**No difference!**


[vagrant@master ~]$ sudo journalctl -f CONTAINER_NAME=tender_bose
-- Logs begin at Wed 2016-07-13 01:17:15 EDT. --
Jul 13 07:15:13 master.localdomain dockerd[19697]: Wed Jul 13 11:15:13 UTC 2016
Jul 13 07:15:18 master.localdomain dockerd[19697]: Wed Jul 13 11:15:18 UTC 2016
Jul 13 07:15:23 master.localdomain dockerd[19697]: Wed Jul 13 11:15:23 UTC 2016
Jul 13 07:15:28 master.localdomain dockerd[19697]: Wed Jul 13 11:15:28 UTC 2016
Jul 13 07:15:33 master.localdomain dockerd[19697]: Wed Jul 13 11:15:33 UTC 2016
Jul 13 07:15:38 master.localdomain dockerd[19697]: Wed Jul 13 11:15:38 UTC 2016
Jul 13 07:15:43 master.localdomain dockerd[19697]: Wed Jul 13 11:15:43 UTC 2016
Jul 13 07:15:48 master.localdomain dockerd[19697]: Wed Jul 13 11:15:48 UTC 2016
Jul 13 07:15:53 master.localdomain dockerd[19697]: Wed Jul 13 11:15:53 UTC 2016


I see another package specific to journald , wondering if that should be used! 

[vagrant@master ~]$ sudo yum search docker | grep -i journal
docker-forward-journald.x86_64 : Forward stdin to journald

I'll test it later...

**Comment by nalind** [comment]
The name, ID and such are sent to the journal as metadata accompanying chunks of the container's output text.  By default, _journalctl_  uses an output format that looks similar to syslogs, which does not include most of the metadata fields that were recorded with each chunk of text.  The _journalctl_ _-o_ flag can be used to select other output formats, some of which include metadata.

**Comment by petermillsacumentive** [comment]
> Please double-check that the container was also launched to use the journal logging driver (`docker inspect -f '{{.HostConfig.LogConfig.Type}}' desperate_easley`).
> 
> Are you using the build from https://get.docker.com/builds/Linux/x86_64/docker-1.12.1.tgz, or an RPM package from https://yum.dockerproject.org/repo/main/centos/7/Packages/? The first appears to be a static binary. The library that is used for reading the journal is not available for static builds, so I wouldn't expect that copy of dockerd to have been built with support for reading the journal. The RPM packaged version links dynamically, so it should be able to read from the journal.

This was my problem too, I had containers already running being handled by IoT Edge. I stopped, pruned and restarted and they're going to journald now!
