### ISSUE TITLE
Tomcat slow at startup with Docker into KVM VM

### ISSUE THREAD

**Issue by zepouet** [docker/docker#14944]
Hello,

We meet a problem with Tomcat extremly slow at startup. After a long investigation we understand the problem came from entropy with /dev/random
There is a lot of web articles around theses problem https://www.digitalocean.com/community/questions/fresh-tomcat-takes-loong-time-to-start-up

The best article to help us is : http://stackoverflow.com/questions/26021181/not-enough-entropy-to-support-dev-random-in-docker-containers-running-in-boot2d

So we add as volume /dev/urandom from host into /dev/random into container.
I wonder if it is a good idea for long time... for short time it could be a workaround but ?

This problem doesn't appear on virtualbox or vmware. Only KVM...

Thansk for your help.
Best regards,

docker version: 1.6 or 1.7

docker info:
```
Containers: 17
Images: 1343
Storage Driver: aufs
 Root Dir: /srv/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1377
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.16.0-0.bpo.4-amd64
Operating System: Debian GNU/Linux 7 (wheezy)
CPUs: 2
Total Memory: 7.816 GiB
Name: evocloudunit00
ID: G4FF:TRW2:ONSD:52DB:JETC:WTFV:WT73:HQ7V:NDNQ:NZLP:52QX:OYNU
WARNING: No swap limit support
````

uname -a: Linux 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt11-1~bpo70+1 (2015-06-08) x86_64 GNU/Linux

```
ii  qemu-kvm                           1.1.2+dfsg-6+deb7u8           amd64        Full virtualization on x86 hardware
ii  libvirt0                           0.9.12.3-1+deb7u1             amd64        library for interfacing with different virtualization systems
ii  linux-image-3.2.0-4-amd64          3.2.68-1+deb7u2               amd64        Linux 3.2 for 64-bit PCs

The mode bridge is easy on hypervisor with 2 VMs


/sbin/brctl show
bridge name     bridge id               STP enabled     interfaces
br0             8000.d4ae52842cc1       no              eth0
                                                        vnet0
                                                        vnet1
with :
ii  bridge-utils                       1.5-6                         amd64        Utilities for configuring the Linux Ethernet bridge
```

**Comment by mountkin** [comment]
I use `rng-tools` to feed the kernel's random number entropy pool. Thus I don't have to map the volume to the container.
On Ubuntu it can be done by 
```
apt-get install -y rng-tools
rngd -r /dev/urandom 
```
![screenshot from 2015-07-24 20 25 29](https://cloud.githubusercontent.com/assets/1496652/8874298/32ddd5b4-3242-11e5-8c86-a422f1026754.png)

**Comment by icecrime** [comment]
Tentatively closing as the issue seems to be resolved: please let me know if it needs reopening! Thanks.
