### ISSUE TITLE
FAQ has broken links

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#14953]
The FAQ on docs.docker.com has broken links. Need to fix them.

**Comment by MHBauer** [comment]
#dibs 
I can figure this out.
As an example, `http://docs.docker.com/index.html#windows` should be `http://docs.docker.com/installation/windows/` . Is that correct?

**Comment by MHBauer** [comment]
well, something like that, I'll figure out how it works...

**Comment by MHBauer** [comment]
Looking at these links has reveal some others that are commonly used and don't work correctly. `terms/image` is an example. Should that go to the definition in the glossary?

**Comment by MHBauer** [comment]
@moxiegirl what should I do about links to draft pages?

**Comment by moxiegirl** [comment]
HI @MHBauer there is a page with the links here; `docs/reference/glossary.md` so the link should be `/reference/glossary#image` I believe give it a try.  Run `make docs` to test. 

The old glossary material is draft because I'm thinking to remove it.

**Comment by MHBauer** [comment]
Is everything in docs/terms the old glossary? Is all of that on the way out?

**Comment by moxiegirl** [comment]
@MHBauer a contributor added the `glossary.md` during the Birthday. I've been swamped and unable to do the clean up which is:

- make sure everything in terms is covered in glossary.md
- locate existing links to terms and restructure them to glossary.md links
- test all of the above

So, yes, it is on its way out soon pending all that.

**Comment by MHBauer** [comment]
Do the docs need to be deployed before this is closed?

**Comment by moxiegirl** [comment]
@MHBauer Usually, the PR closes an issue by including a ref in the pr like closes #14953.  Since we didn't have one of those. I'll do it manually.  Fixed by   https://github.com/docker/docker/pull/14960

**Comment by MHBauer** [comment]
Thanks for the lesson. Is that something anyone can do?

**Comment by moxiegirl** [comment]
@MHBauer Sure.  Here are some how-tos: https://help.github.com/articles/closing-issues-via-commit-messages/
