### ISSUE TITLE
Remote API : add docker's version information in info request

### ISSUE THREAD

**Issue by Shini31** [docker/docker#14952]
Is it possible to add docker's version in result for /info request for remote API ?

Thanks in advance.
Regards.

**Comment by cpuguy83** [comment]
@Shini31 Is the `/version` endpoint not sufficient? I understand you need to make 2 requests.
Also I think this is a dup.

**Comment by Shini31** [comment]
@cpuguy83 Of course it's sufficient but as you say, 2 requests are necessary if you want global information on Docker.
For example in a monitoring script two requests can raise the execution time.
Moreover there are already some duplicate information as the kernel version

**Comment by azurezk** [comment]
#dibs
