### ISSUE TITLE
Proposal: unified driver for union filesystems

### ISSUE THREAD

**Issue by alex-aizman** [docker/docker#14968]
## 1.	Introduction

This proposal is inspired by the https://github.com/docker/docker/issues/14049 “Global Image/Layer Namespace”. It stands by itself as well, as a separate proposal to improve docker’s graphdriver architecture, in particular – support of the union filesystems.

Union filesystems form a class of their own which is layered directly on top of actual (true) local filesystems such as, for instance, ext4 or zfs. There are variations and differences of course from the original Unionfs circa 2004. For the docker those differences are irrelevant - what's relevant is whether this or that or the other union filesystem is upstreamed in the Linux kernel or included in a given distribution, and which one performs better under given circumstances. None of these arguments has an impact on the corresponding docker drivers.

So. Arguments for this Proposal include at least one architectural reason (i.e., layering) and one good-coding reason (functional overlap between the overlayfs and aufs graphdrivers). 

More practically though, the idea to support global image namespace required minor changes in the union filesystems drivers, to support immutable remote images and layers. And the idea to change them in turn prompted this development and this proposal..

## 2.	Union-Federated Driver

There’s now (a proposed) one and only one docker driver, called union-federated, that can be configured to run both aufs or overlayfs. In the future the driver can be extended to support other kernel-based union-type filesystems that support multiple read-only layers.

The driver unifies the unification drivers, and that is the ```#1```. In addition, union-federated provides support for an optional global image namespace: you can either run it locally on a single host over aufs or overlayfs. Or, you can use it exactly as described in the https://github.com/docker/docker/issues/14049. And that’s ```#2```.

## 3.	The Patch

* Local separation of (local) images and layers: https://github.com/Ramzec/docker/commit/0579f2ff3ecb08426f645ad6d75edecf28c96bf8

* Union-federated graphdriver: https://github.com/Ramzec/docker/commit/9aecfbc12a524ba9818e1080a56b74f0a9279b1c

## 4.	Getting started

```# docker –graph=/var/lib/docker_uf –storage-opt=uf.subdriver=overlay```

This will run docker with union-federated driver; “subdriver” option tells it which of the union filesystems to use. Both aufs and overlayfs are supported, with one comment: 

•	As far as the current patch (```#3``` above), overlayfs option requires Linux kernel 3.19 or later. This is due to the fact that older overlayfs does not support so called “multi-layer” – see e.g. http://www.phoronix.com/scan.php?page=news_item&px=MTg1Nzg.  

In addition to the mandatory uf.subdriver=aufs|overlay option, other (optional) –storage-opt options include:

•	uf.localonly = (true | false) 
•	uf.nfsroot = (local pathname)

For instance, to use the local-only option with aufs and to work with only the local images, run union-federated as follows:

```# docker –graph=/var/lib/docker_uf –storage-opt=uf.localonly=true –storage-opt=uf.subdriver=aufs```

(Note: suggested to make aufs default..)

## 5.	Directory Layout

The driver imposes/supports the following directory layout to store and access images and layers, local and remote:

	  ├──host1
	  │       ├── layers // Metadata of layers
	  │       │   ├── 1
	  │       │   ├── 2
	  │       │   └── 3
	  │       ├── diff  // Content of the layer
	  │       │   ├── 1  // Contains layers that need to be mounted for the id
	  │       │   ├── 2
	  │       │   └── 3
	  │       └── mnt    // Mount points for the rw layers to be mounted
	  │              ├── 1
	  │              ├── 2
	  │              └── 3
	  ├──host1
	  │       ├── layers // Metadata of layers
	  │       │   ├── 1
	  │       │   ├── 2
	  │       │   └── 3
	  │       ├── diff  // Content of the layer
	  │       │   ├── 1  // Contains layers that need to be mounted for the id
	  │       │   ├── 2
	  │       │   └── 3
	  │       └── mnt    // Mount points for the rw layers to be mounted
	  │              ├── 1
	  │              ├── 2
	  │              └── 3
	  .
	  .
	  .
	  ├──hostN
	
	rootLocalContainerLayers - The directory that contains
	                                                     only container-layers
	  ./
	  ├── layers // Metadata of layers
	  │   ├── 1
	  │   ├── 2
	  │   └── 3
	  ├── diff  // Content of the layer
	 │   ├── 1  // Contains layers that need to be mounted for the id
	  │   ├── 2
	  │   └── 3
	  └── mnt    // Mount points for the rw layers to be mounted
	      ├── 1
	      ├── 2
	      └── 3
	
	rootLocalImageLayers - The directory that contains
	                                             only image-layers
	  ./
	  ├── layers // Metadata of layers
	  │   ├── 1
	  │   ├── 2
	  │   └── 3
	  ├── diff  // Content of the layer
	  │   ├── 1  // Contains layers that need to be mounted for the id
	  │   ├── 2
	  │   └── 3
	  └── mnt    // Mount points for the rw layers to be mounted
	      ├── 1
	      ├── 2
	      └── 3

As usual, the ‘diff’ directories store actual layer content; locally the driver stores images under 

•	root/image-layers/(diff|layers|mnt|work) 

and containers under: 

•	root/container-layers/(diff|layers|mnt|work) 

Clean separation of local images vs. local containers is intended to support global image namespace: access to the immutable images (and images only) from other dockerized hosts..

## 6.	Initialization and checks

At init time the driver looks in the /proc for requested aufs/overlayfs option. Assuming the corresponding union filesystem is included, for the overlayfs there’s another check: kernel version >= 3.19

## 7.	What’s Next

Apart from couple minor points mentioned above (aufs default, pre-3.19 overlayfs), union-federated driver seems to be done and is immediately usable. The other roadmap is described at the bottom of “Global Namespace” https://github.com/docker/docker/issues/14049

**Comment by unclejack** [comment]
Coming up with something like this is somewhat redundant as most distributions are migrating towards overlay from aufs. The AUFS driver's code is looking good, it's just that there are some issues with AUFS itself which are unlikely to go away. The only way to get AUFS in the near future will be by having custom patched kernels, not by running the distribution's default kernel.

Overlay needs work on the kernel side to make it ready for prime time. I'd suggest contributing to the overlay driver's code in Docker and in the kernel, instead of attempting to unify the union file system code in Docker's tree.

**Comment by unclejack** [comment]
This proposal has been open for a while and there have been no more comments on this since the last time I've commented.

This unified driver for union file systems still seems to be a bad idea. There's the risk of leaving out some vital code for aufs or overlay after some refactoring. The risk of not taking some driver specific aspect into account during refactoring would also lead to very subtle and very hard to track bugs.

We should strive to improve the separate drivers instead. I'll close this now. Please feel free to comment.
