### ISSUE TITLE
Registry Client response code acceptance is too narrow

### ISSUE THREAD

**Issue by stevvooe** [docker/docker#14975]
Details are in docker/distribution#748 but we need to fix this for 1.8. We'll need to fix this in distribution then update the vendored version.

History repeating itself: #10402.

**Comment by aaronlehmann** [comment]
Created a PR in the distribution repo: https://github.com/docker/distribution/pull/750

**Comment by thaJeztah** [comment]
https://github.com/docker/distribution/pull/750 was merged, so I think we need an update of the vendored distribution now?
