### ISSUE TITLE
docker cannot run because of "container no such file or directory"

### ISSUE THREAD

**Issue by jdoliner** [docker/docker#14972]
I think this bug is similar to #9066.

I have a Dockerfile which produces a container which I cannot start. Anytime I try to do run with it it gives me the error:

```
Error response from daemon: Cannot start container 9da65b976ad00b0dde374391265f73c5964ce24fefdefe7cb948e88dd8efb6e2: [8] System error: no such file or directory
```

The Dockerfile looks like this:

```
FROM gliderlabs/alpine:3.2
MAINTAINER peter@pachyderm.io

RUN mkdir -p /etc/ssl/certs
ADD etc/certs/ca-certificates.crt /etc/ssl/certs/
COPY etc/bin/btrfs-wrapper /bin/btrfs
ADD _tmp/pfsd /bin/pfsd
ENTRYPOINT ["/bin/pfsd"]
```

`_tmp/pfsd` is a binary executable that's compile from some go code.

I'm pretty certain that it's the source of the problem. If I remove the line `ENTRYPOINT ["/bin/pfsd"]` then I'm able to start the container.

If I do so with `/`bin/sh` I can get a shell inside the container. It tried running `/bin/pfsd` inside of that shell and it gave me the following:

```shell
/ # ls -lh /bin/pfsd
-rwxr-xr-x    2 root     root        9.7M Jul 24 20:49 /bin/pfsd
/ # /bin/pfsd
/bin/sh: /bin/pfsd: not found
```

**Comment by mountkin** [comment]
@jdoliner I suspect the executable is dynamically linked but some of the required libraries don't exist in the docker image.
You can confirm that by running "ldd pfsd" on the host to see if it's dynamically linked.

**Comment by cpuguy83** [comment]
Yeah, this is most likely because alpine uses uclibc, not glibc.
You'll need to re-compile your app against uclibc.

**Comment by jdoliner** [comment]
Yup you guys are 100% correct. Ty for the help :D!
Closing.
