### ISSUE TITLE
docker -v and default directory permissions? Part Deux #14937

### ISSUE THREAD

**Issue by coderlol** [docker/docker#14984]
See #14937 
 
cpu dude closed issue unilaterally, but I think the issue warrants a discussion.  When mounting a host directory and if the host directory does not exist, docker creates one, but, alas, it sets its own default permissions, overriding existing host filesystem ACL.

A good set of options would be to enable users to instruct docker to not set its own permission, allow users to specify what they want or simply go with the host defaults

**Comment by icecrime** [comment]
Reopening the original one instead to avoid duplicates.
