### ISSUE TITLE
Validate checks not always working

### ISSUE THREAD

**Issue by runcom** [docker/docker#14994]
Sometimes validate checks don't work because the `git diff` command in `hack/make/.validate` doesn't show any file to be validated (I think)
This build for instance https://jenkins.dockerproject.org/job/Docker-PRs/11694/console was supposed to fail cause of go vet checks but it didn't. From other tests/builds the only difference I see is that the commits in this build aren't fast forward (in git fast-forward validate works)
Is this wrong or I'm missing something?

ping @jfrazelle @tianon

**Comment by tianon** [comment]
I'm not sure what's up, but this definitely warrants further investigation to make sure our scripts are working properly.  They fetch `master` from the upstream repo directly and compare against that so they _should_ be working, but I wouldn't be surprised if there are edge cases. :cry:

**Comment by calavera** [comment]
I'm pretty sure this is solved. Closing.
