### ISSUE TITLE
Systemd units missing from 1.8.0-rc1 packages for Vivid and Wily 

### ISSUE THREAD

**Issue by eolamey** [docker/docker#14995]
It seems like the systemd units that were part of the Ubuntu packages (>= 15.04), `/lib/systemd/system/docker.socket` and `/lib/systemd/system/docker.service`, are missing from the just released 1.8.0-rc1 packages, as found on http://apt.dockerproject.org.

**Comment by thaJeztah** [comment]
ping @calavera @jfrazelle

**Comment by jfrazelle** [comment]
whoa wierd can you try the ones on the main channel? is it the same?

**Comment by eolamey** [comment]
The ones in `main`, 1.7.1-0, are OK. The ones in `experimental` are not however, but the oldest is from July 23rd, which seems a bit weird.

**Comment by jfrazelle** [comment]
the rc's are pushed to testing not experimental

**Comment by jfrazelle** [comment]
but ya maybe there is something wrong w master..

**Comment by jfrazelle** [comment]
I can reproduce... I'll figure it out...

**Comment by jfrazelle** [comment]
ping @tianon in case he knows what changed

**Comment by jfrazelle** [comment]
i think maybe this https://github.com/docker/docker/commit/80d99236c1ef9d389dbaca73c1a949da16b56b42#diff-be14a01cac8999f7234e37cd21ab9a72R35

**Comment by eolamey** [comment]
That's what I was thinking too. I'm no expert, but I usually do something like:

```shell
override_dh_install:
    dh_install
    other custom stuff
```

**Comment by jfrazelle** [comment]
totally :)

**Comment by jfrazelle** [comment]
im fixing ;) thanks for finding this! would have been super bad!

**Comment by eolamey** [comment]
No problem, that's what RCs are for :)

**Comment by thaJeztah** [comment]
Thanks @eolamey!  Pull request is here: https://github.com/docker/docker/issues/14998

**Comment by icecrime** [comment]
Thanks a lot for the report and @jfrazelle for the express fix :+1:

**Comment by jfrazelle** [comment]
experimental has been reuploaded and fixed
