### ISSUE TITLE
Docker bridge doesn't work properly in Arch Linux at Digitalocean.

### ISSUE THREAD

**Issue by mikroskeem** [docker/docker#15008]
Hello! I can't get Docker running properly on Arch Linux in Digitalocean droplet.
Arch Linux is installed using gh2o/digitalocean-debian-to-arch

"ip addr show dev docker0" in Arch Linux droplet, when centos7 container is running:
```
4: docker0@NONE: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 8a:97:99:91:d1:5e brd ff:ff:ff:ff:ff:ff
    inet 172.17.42.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::5470:3ff:fee3:fb6b/64 scope link 
       valid_lft forever preferred_lft forever
```

"ip addr show dev docker0" when no containers are running:
```
4: docker0@NONE: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state LOWERLAYERDOWN group default 
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
    inet 172.17.42.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::5470:3ff:fee3:fb6b/64 scope link 
       valid_lft forever preferred_lft forever
```

net.ipv4.ip_forward is 1, no firewall, no errors in journal. Can ping container from host and vice-versa, just there is no damn connection to outside world from container.
I haven't edited any configs.
Seems like Docker is broken in Arch Linux at Digitalocean, since Docker works on my personal laptop.

When I make new Ubuntu 15.04 droplet and install Docker using `wget -qO- https://get.docker.com/ | sh`, containers get network.

"ip addr show dev docker0" shows this:
```
4: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 56:84:7a:fe:97:99 brd ff:ff:ff:ff:ff:ff
    inet 172.17.42.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::5484:7aff:fefe:9799/64 scope link 
       valid_lft forever preferred_lft forever
```
Output doesn't change when container is running or not

Out of ideas today.

**Comment by mikroskeem** [comment]
Environment: Digitalocean

`docker version`:
```
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```
`docker info`:
```
Containers: 2
Images: 4
Storage Driver: devicemapper
 Pool Name: docker-254:3-394175-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 513.4 MB
 Data Space Total: 107.4 GB
 Data Space Available: 18.9 GB
 Metadata Space Used: 1.012 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.102 (2015-07-07)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.2-2-ARCH
Operating System: Arch Linux
CPUs: 1
Total Memory: 493.8 MiB
Name: nightsnack.cf
ID: EAGT:CB7Z:2XK2:BCQ2:43TL:Q7PD:XUTJ:27D6:NROR:LFPL:XVZ7:RRN2
```
`uname -a`: `Linux nightsnack.cf 4.1.2-2-ARCH #1 SMP PREEMPT Wed Jul 15 08:30:32 UTC 2015 x86_64 GNU/Linux`

Steps to reproduce:
- Create Debian 8 x64 droplet in DigitalOcean and install Arch Linux on it by following tutorial in gh2o/digitalocean-debian-to-arch repo
- Install and enable Docker using `pacman -S docker`, `systemctl enable docker` and `systemctl start docker`
- Start any container and try to ping google.com `docker run -ti centos:7 /usr/bin/ping google.com`

I expect ping reply, but I get "Unknown host"

**Comment by thaJeztah** [comment]
This looks like a dup of https://github.com/docker/docker/issues/14185, could you try with the instructions in https://github.com/docker/docker/pull/15007?

**Comment by mikroskeem** [comment]
@thaJeztah It worked. Thanks

**Comment by thaJeztah** [comment]
Good to hear, @mikroskeem !

**Comment by mikroskeem** [comment]
actually had to use IPForward=yes and match eth0, so here's final file:
```
[Match]
Name=eth0

[Network]
IPForward=yes
```
Which means, it doesn't matter how you name network file

**Comment by hookenz** [comment]
I was having the same issue on CoreOS.  But I have just found that it'll say LOWERLAYERDOWN if there are no containers attached to the bridge!  So that caught me out for a moment.
