### ISSUE TITLE
Container (Ubuntu) passwd bug

### ISSUE THREAD

**Issue by dtesler** [docker/docker#15016]
docker exec containerid echo -e "password\npassword" | passwd root 

seems to change the password on the parent node.

System info:

        root@srv:~# docker version
        Client version: 1.7.0
        Client API version: 1.19
        Go version (client): go1.4.2
        Git commit (client): 0baf609
        OS/Arch (client): linux/amd64
        Server version: 1.7.0
        Server API version: 1.19
        Go version (server): go1.4.2
        Git commit (server): 0baf609
        OS/Arch (server): linux/amd64
        root@srv:~# docker info
        Containers: 60
        Images: 1028
        Storage Driver: aufs
         Root Dir: /var/lib/docker/aufs
         Backing Filesystem: extfs
         Dirs: 1148
         Dirperm1 Supported: false
        Execution Driver: native-0.2
        Logging Driver: json-file
        Kernel Version: 3.13.0-55-generic
        Operating System: Ubuntu 14.04.2 LTS
        CPUs: 16
        Total Memory: 94.41 GiB
        WARNING: No swap limit support
        root@srv:~# uname -a
        Linux srv 3.13.0-55-generic #92-Ubuntu SMP Sun Jun 14 18:32:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Issue happens after:

        docker run -dt ubuntu
        docker exec containerid echo -e "password\npassword" | passwd root

I noticed when trying to ssh from a different computer, that the initial password didn't work, but when I tried the one that was set using the command, that worked for the parent node.

**Comment by thaJeztah** [comment]
If I understand the problem correctly, this can be expected; just as;

    docker exec containerid echo -e "foobar" > hello-world

Will result in a file `hello-world` on the host, containing "foobar"

**Comment by dtesler** [comment]
@thaJeztah This isn't exlusive to doing that

        docker exec containerid -it bash

the same happened while I was inside the container as such.

**Comment by thaJeztah** [comment]
@dtesler let met try to understand; if you run a container, then `docker exec containerid -it bash`,
then `echo -e "password\npassword" | passwd root` (inside the container).

This results in changing the root password on the *host*?
