### ISSUE TITLE
Documentation (minor): Missing indentation in "Creating a Dockerfile"

### ISSUE THREAD

**Issue by charleswhchan** [docker/docker#15011]
Under "Creating a Dockerfile", the last line is missing an indent
https://docs.docker.com/docker-trusted-registry/quick-start/#creating-a-dockerfile

```
 FROM jenkins

 #New plugins must be placed in the plugins file
 COPY plugins /usr/share/jenkins/plugins

 #The plugins.sh script will install new plugins
 RUN /usr/local/bin/plugins.sh /usr/share/jenkins/plugins

 #Copy private key and cert to image
 COPY https.pem /var/lib/jenkins/cert
 COPY https.key /var/lib/jenkins/pk

 #Configure HTTP off and HTTPS on, using port 1973
ENV JENKINS_OPTS --httpPort=-1 --httpsPort=1973 --httpsCertificate=/var/lib/jenkins/cert --httpsPrivateKey=/var/lib/jenkins/pk
```

If someone can point out where the file is, I can fix.

**Comment by thaJeztah** [comment]
Thanks! I think that part of the docs may be in a private repository

ping @SvenDowideit @moxiegirl I think you have access to that :smile:

**Comment by LK4D4** [comment]
I think that was fixed in that private repository.
