### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by dwcramer** [docker/docker#15027]
On the page https://docs.docker.com/reference/run under the heading "Operator exclusive options" there's a broken link to https://docs.docker.com/reference/run/#runtime-constraints-on-cpu-and-memory (link text: "Runtime Constraints on CPU and Memory"). That url should probably be https://docs.docker.com/reference/run/#runtime-constraints-on-resources

**Comment by vdemeester** [comment]
hi @dwcramer, thanks for the catch. It's still the case in ``master`` (here : https://github.com/docker/docker/blob/master/docs/reference/run.md).

Would you like to submit a pull-request on that fix :blush: ?

**Comment by charleswhchan** [comment]
PR: #15027 was fixed. So this can probably be closed as well.

**Comment by vdemeester** [comment]
oh right, ping @thaJeztah

**Comment by thaJeztah** [comment]
Oh, yes! Thanks for paying attention (and for the ping!)
