### ISSUE TITLE
Build error: constant overflows int

### ISSUE THREAD

**Issue by paralin** [docker/docker#15038]
When building, I get the following error:

```
.gopath/src/github.com/docker/docker/daemon/logger/fluentd/fluentd.go:98: constant 4294967295 overflows int
```

This seems like a pretty big issue. I used .hack/vendor to check out the correct revisions for everything.

**Comment by paralin** [comment]
Hi,

docker version: git, 1.8.0-rc1
uname -a: Linux 3.19.0-22-generic #22-Ubuntu SMP Tue Jun 16 17:15:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Steps to reproduce:
 1. Attempt to compile docker

Results expected: successful compilation
Results received: error:
```
.gopath/src/github.com/docker/docker/daemon/logger/fluentd/fluentd.go:98: constant 4294967295 overflows int
```

Your problem is that your math.max is actually bigger than Golang's supported Math.Max.

----------END REPORT ---------

**Comment by LK4D4** [comment]
@paralin That's weird, because `math.MaxInt32` is smaller, than `math.MaxInt64`. Seems like you're trying to build on 32-bit arch.

**Comment by paralin** [comment]
@LK4D4 Okay, some more information:

Building under buildroot, cross-compiling for GO_ARCH=arm. The previous version compiles okay, this problem was introduced between 1.7.1 and 1.8.0-rc1

**Comment by paralin** [comment]
Thank you!
