### ISSUE TITLE
Ubuntu installation has a Markdown issue in a note

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#15033]
In the Installation step 3.

![image](https://cloud.githubusercontent.com/assets/1347209/8911222/e878495a-343f-11e5-8bbd-4109eb00cb37.png)

**Comment by MHBauer** [comment]
Looks fine to me in firefox and safari when running `make docs` off of master.

![ubuntudocs](https://cloud.githubusercontent.com/assets/13337345/8911879/e9bcc62a-3443-11e5-86fb-6e0b5ed24189.png)

The biggest problem I see is the numbering restarts.

**Comment by moxiegirl** [comment]
@MHBauer Interesting, I see the note problem on Chrome but not the restart you see.

**Comment by MHBauer** [comment]
I installed chrome, `make docs` looks good.

The deployed version on docs.docker.com does have the problem. In all three browsers.

**Comment by moxiegirl** [comment]
@MHBauer Thanks for that test. I'll see what is going on.

**Comment by thaJeztah** [comment]
Looks like the formatting issue was already resolved in https://github.com/docker/docker/pull/14731

For the numbering restarting, I suspect that is because the "note" isn't indented, and therefore "ending" the numbered list. I think indenting the note one level (4 spaces) should fix that. (But haven't tried)

**Comment by MHBauer** [comment]
That does fix the interrupted numbering.

<img width="722" alt="screen shot 2015-07-27 at 13 12 21" src="https://cloud.githubusercontent.com/assets/13337345/8916557/4fe4d678-3461-11e5-9a27-014cef4677ef.png">

**Comment by ankushagarwal** [comment]
Can we close this as it's fixed on the master branch.

**Comment by thaJeztah** [comment]
Ah, yes!
