### ISSUE TITLE
build: Cannot locate specified Dockerfile: Dockerfile

### ISSUE THREAD

**Issue by crosbymichael** [docker/docker#15037]
This is the error I get after updating docker this morning from master and trying to build the Dockerfile in the repo.

```bash
michael|~/docker > docker build -t docker .
WARN[0000] Tar: Can't archive a file with includes      
Sending build context to Docker daemon 1.536 kB
Error response from daemon: Cannot locate specified Dockerfile: Dockerfile
michael|~/docker > docker version
Client:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f0f753d
 Built:        Mon Jul 27 16:53:02 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f0f753d
 Built:        Mon Jul 27 16:53:02 UTC 2015
 OS/Arch:      linux/amd64
michael|~/docker > 
```

**Comment by icecrime** [comment]
My vote goes to https://github.com/dmcgowan/docker/commit/578b1521df85eae8a6205118131751c631323ba5

**Comment by crosbymichael** [comment]
I know the root cause.  It's because my `cwd` is a symlink `~/docker`.  If I do a docker build here it's broken.  If I resolve my `cwd` to the full path `~/development/gocode/src/github.com/docker/docker` docker build works again.

**Comment by thaJeztah** [comment]
@crosbymichael is this a dup of https://github.com/docker/docker/issues/12842 (and https://github.com/docker/docker/issues/7804)? (Haven't checked thoroughly, but remembered that one)
