### ISSUE TITLE
[1.8.0-rc1] Unit docker.socket failed to load: No such file or directory

### ISSUE THREAD

**Issue by mbentley** [docker/docker#15046]
Description of problem: When upgrading from `1.7.1-0~stretch` to `1.8.0~rc1-0~stretch`, docker fails to restart properly as it appears that there is not a systemd service file `/lib/systemd/system/docker.service`.  I have a drop-in file `/etc/systemd/system/docker.service.d/override.conf` as I am expecting there to be a `/lib/systemd/system/docker.service` file.

Is this the intended behavior to no longer have a system service file?  I am seeing the same with the 1.8.0-rc1 build for jessie as well.

`docker version`:
```
# docker version
Client:
 Version:      1.8.0-rc1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   4f1c66a
 Built:        Sat Jul 25 05:32:36 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:
n/a - docker daemon doesn't start

`uname -a`:
```
# uname -a
Linux localdev 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.):
VirtualBox, Debian Sid w/kernel from jessie for AUFS support

How reproducible:
Every time

Steps to Reproduce:
1. Start with `docker-engine=1.7.1-0~stretch`
2. Upgrade to `docker-engine=1.8.0~rc1-0~stretch`
3. Daemon doesn't start:

```
Setting up docker-engine (1.8.0~rc1-0~stretch) ...
Installing new version of config file /etc/bash_completion.d/docker ...
Installing new version of config file /etc/init.d/docker ...
Installing new version of config file /etc/init/docker.conf ...
Failed to start docker.service: Unit docker.socket failed to load: No such file or directory.
invoke-rc.d: initscript docker, action "start" failed.
dpkg: error processing package docker-engine (--configure):
 subprocess installed post-installation script returned error exit status 6
Processing triggers for libc-bin (2.19-19) ...
Processing triggers for systemd (222-2) ...
Errors were encountered while processing:
 docker-engine
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Actual Results:
The docker daemon is not running after upgrade because the systemd file isn't included so drop-ins fail.

Expected Results:
Expecting systemd file to exist in the package and get installed

Additional info:

With `docker-engine=1.7.1-0~stretch`:

```
# systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─override.conf
   Active: active (running) since Mon 2015-07-27 14:15:29 EDT; 3s ago
     Docs: https://docs.docker.com
           http://docs.docker.com
 Main PID: 31675 (docker)
   CGroup: /system.slice/docker.service
           └─31675 /usr/bin/docker -d -s aufs -H fd:// -H 0.0.0.0:2376 --tlsverify --tlscacert=/etc/docker/ca.pem --tlscert=/etc/docker/server.pem --tlskey=/etc/docker/server-key...
```

With  `docker-engine=1.8.0~rc1-0~stretch`:

```
# systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/etc/init.d/docker)
  Drop-In: /etc/systemd/system/docker.service.d
           └─override.conf
   Active: inactive (dead) since Mon 2015-07-27 14:10:01 EDT; 3min 56s ago
     Docs: man:systemd-sysv-generator(8)
           http://docs.docker.com
 Main PID: 759 (code=exited, status=0/SUCCESS)
```

**Comment by eolamey** [comment]
Hi,

I think this is a duplicate of https://github.com/docker/docker/issues/14995, as the debian and ubuntu packages are using a common `rules` file.

**Comment by mbentley** [comment]
You're right there... I somehow missed that when I searched earlier.  Thanks!
