### ISSUE TITLE
Question: Automatically include container name in syslog program?

### ISSUE THREAD

**Issue by phil-monroe** [docker/docker#15058]
Currently, the syslog program field is set to `docker/CONTAINER-ID` by default. Would it make sense to include the containers name as well? Perhaps something like `docker/CONTAINER-NAME/CONTAINER-ID`? Doing so would allow easy parsing + grouping of logs when using something like ELK without having to add custom `--log-opt syslog-tag="app-name"` to every submitted container.

Should just be a simple addition to [syslog.go](https://github.com/docker/docker/blob/master/daemon/logger/syslog/syslog.go#L60):
``` go
tag := ctx.Config["syslog-tag"]
if tag == "" {
    tag = fmt.Sprint(ctx.ContainerName, "/", ctx.ContainerID[:12])
}
```

I'm happy to provide a pull request, but just wanted to make sure it would make sense.

**Comment by phil-monroe** [comment]
Whoops... duplicate. sorry.

**Comment by phil-monroe** [comment]
Actually, not really a duplicate. Some people had mentioned this, but nothing ever happened. Still think it would be a good idea?

**Comment by thaJeztah** [comment]
This has come up a few times, IIRC, this was a concern; https://github.com/docker/docker/pull/12391#issuecomment-93273044, and the `--log-opt syslog-tag=""` was created as an alternative.

I don't think changing the *default* would be wise to do, because that will break backward compatibility. Perhaps some other option?

**Comment by cpuguy83** [comment]
Also -1 on names, however providing  way to customize which fields are present may be interesting.

**Comment by phemmer** [comment]
Perhaps docker should implement a [syslog rfc5424](https://tools.ietf.org/html/rfc5424#section-6.3) driver, and log stuff like this in the data fields.

**Comment by trompx** [comment]
I just tried the new option and launch a container :
```
docker run -d --name mon_precieux --log-driver=syslog --log-opt syslog-tag="mon_precieux" mon_precieux
```

When I docker inspect I get :
```
 "LogConfig": {
     "Type": "syslog",
     "Config": {
         "syslog-tag": "mon_precieux"
     }
 },
```

But when I check syslog, I have still :
```
Jul 30 16:04:34 test mon_precieux/cab38e951896[1023]: 2015/07/30 16:04:34 ...
```

I run docker 1.7.1.

**Comment by phil-monroe** [comment]
@trompx - the `syslog-tag` log option is not available in [1.7.1](https://github.com/docker/docker/blob/v1.7.1/daemon/logger/syslog/syslog.go#L32).

@phemmer - I am hoping for "it just works" with the [logstash syslog input](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-syslog.html), which is strictly syslog RFC3164. It could be done with some logstash contributions, but I'm looking for simplicity.

@cpuguy83 - what if there was something like `--log-opt syslog-tag-fields=name,id`? I don't really want to keep piling on the log-opts, so maybe something that includes field interpolations, eg: `--log-opt syslog-tag=%name/%tag`?

**Comment by phil-monroe** [comment]
Actually, there is no need that this needs to be syslog altogether. Another log driver could be created that will send the logs as JSON to a remote TCP port. Then we could easily use the [TCP input](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-tcp.html) with the [JSON codec](https://www.elastic.co/guide/en/logstash/current/plugins-codecs-json_lines.html) and have fully structured logs in logstash. 

Think this would be better?

**Comment by phemmer** [comment]
The problem with that is it seems like it would be specific to logstash. Flexible solutions are generally considered better.

**Comment by Filirom1** [comment]
Something like `--log-opt syslog-tag=%name/%id` would be perfect
