### ISSUE TITLE
skip docker_api_exec_resize_test on lxc

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#15054]
submit patch to skip this test on lxc

**Comment by chrisseto** [comment]
I'd like to take a whack at this if that's okay.

**Comment by jfrazelle** [comment]
yes please, its very simple, you just need to add a `testRequires(c,
NativeExecDriver)` to that test

**Comment by chrisseto** [comment]
Just wanted to make sure I've got it right before submitting the PR:
You mean adding that to all the tests, the 2, in the file `docker_api_exec_resize_test.go`.
Adding the `testRequires(...)` will stop the tests from running with lxc and windows? Or does this test never run for windows?

**Comment by jfrazelle** [comment]
not to all sorry just to DockerSuite.TestExecResizeImmediatelyAfterExecStart
