### ISSUE TITLE
1.8.0-rc1: Why is HostConfig in /containers/json output?

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#15056]
In 1.8.0-rc1 I see in the `/containers/json` output that there is a new element.  Why?  This seems a bit premature being that networking is still experimental.

```http
HTTP/1.1 200 OK
Content-Type: application/json
Date: Mon, 27 Jul 2015 21:43:46 GMT
Server: Docker/1.8.0-rc1 (linux)
Transfer-Encoding: chunked

[
    {
        "Command": "/bin/bash", 
        "Created": 1438033414, 
        "HostConfig": {
            "NetworkMode": "bridge"
        }, 
        "Id": "335b44b018d2b8795c91d3b474fb78ca31840f2e9b7f510bd4a0c7b7a212af26", 
        "Image": "ubuntu", 
        "Labels": {}, 
        "Names": [
            "/bridge"
        ], 
        "Ports": [], 
        "Status": "Exited (0) 12 seconds ago"
    }, 
```

**Comment by boonkerz** [comment]
i think the overlay is experimental but the bridge mode not

**Comment by mavenugo** [comment]
@ibuildthecloud I dont think this is related to experimental changes. PTAL #12812

**Comment by ibuildthecloud** [comment]
#12812 This seem like a very small enhancement to necessitate adding an additional field to the `container/json`.  We've always been very conservative as to what is in this response and it just seems odd that this field was added when I don't see a huge need for it.  Especially with the Docker networking coming, what does NetworkMode mean anyway?  It's like we added a field just in time to deprecate it.

**Comment by mavenugo** [comment]
@ibuildthecloud I cannot speak for #12812, but as you know, the meaning of NetworkMode is still not fully ratified with the new libnetwork changes that is coming in and the discussions are ongoing in other PRs. AFAIK, there is no decision to deprecate network mode. but, it might resurface as under different UI context based on user feedback and discussions.

**Comment by cpuguy83** [comment]
@mavenugo Should we revert this before 1.8 is released?

**Comment by mavenugo** [comment]
@cpuguy83 I dont see a need for that. Unless there is a strong reason from @ibuildthecloud and agreed upon by other core maintainers. Obviously #12812 is approved for good reasons.

**Comment by ibuildthecloud** [comment]
@cpuguy83 I'd prefer it is reverted.  I don't see the need, but obviously somebody will disagrees with me.  @mavenugo After networking leaves experimental what does NetworkMode mean any more?  I thought that would be essentially deprecated and left to just indicate the special cases of host, none, container.

**Comment by ibuildthecloud** [comment]
@mavenugo sorry, overlooked your comment above.  Given that things are still up in the air I really don't like having NetworkMode in the container list.  I'll let somebody with authority decide that one.

**Comment by icecrime** [comment]
Mmmm I don't really know what to tell you there. I see the use of this field "today", now indeed, if it's meant to be deprecated when the new networking model makes it to stable, then yeah merging this to 1.8.0 is a loss of time.

@mavenugo Do you see use for this field in a world where the new networking is mainstream?

**Comment by mavenugo** [comment]
@ibuildthecloud @icecrime from an user stand-point NetworkMode (host, bridge, container, none) will all stay the same as today (infact 1.7.0 already have moved to the CNM model for these modes). But in the backend these modes are all simply special networks using these special inbuilt drivers.

So, from an User standpoint, the meaning of host, container, none and bridge stays exactly the same and in-addition to these, we will also have the user-defined networks created using external drivers/plugins.

I see @ibuildthecloud's point. But the user's dont really care about the backend implementation.

**Comment by icecrime** [comment]
Ok then I'd be for keeping it. I'm not sure why it's nested in a `HostConfig` structure though, but that's not relevant here.

**Comment by thaJeztah** [comment]
I don't think the backend implementation is the issue here; the issue is that the API response changes, *possibly* only to be reverted or changed again in the next release (if I understand correctly). If there's no huge demand for this information right now, I'm leaning towards reverting, otherwise the API output will be really changing with each release.

**note** I see that the documentation is not updated with this change? https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api_v1.20.md

**Comment by ibuildthecloud** [comment]
I'm fine either way, but it should be documented.  Just FYI, the reason I seem to bring up these pedantic issue about API is because I have a very strict test suite that we run for Rancher validation (test suite runs against rancher, which in turn calls Docker).  So whenever the API changes I have to address that somehow.  So currently my tests are failing w/ 1.8 because I see a new element I don't know about.

What is the policy on new fields to current api versions?  So this is a new field in 1.19 even though 1.20 is the current API revision.

**Comment by thaJeztah** [comment]
> What is the policy on new fields to current api versions? So this is a new field in 1.19 even though 1.20 is the current API revision.

https://docs.docker.com/reference/api/docker_remote_api/

> The Remote API uses an open schema model. In this model, unknown properties in incoming messages will be ignored. Client applications need to take this into account to ensure they will not break when talking to newer Docker daemons.

(But I'm always in favour of being more strict, just my personal preference)

**Comment by ibuildthecloud** [comment]
Closing, because time made this discussion irrelevant, sigh.
