### ISSUE TITLE
master: ENV var propigation to ADD is broken

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#15072]
Dockerfile:

```
FROM alpine
MAINTAINER Jessica Frazelle <jess@docker.com>

RUN apk update && apk add \
	ca-certificates \
	curl \
	unzip \
	&& rm -rf /var/cache/apk/* \

ENV CONSUL_VERSION 0.5.2

ADD https://jesss.s3.amazonaws.com/binaries/consul/${CONSUL_VERSION}/consul /usr/local/bin/consul
ADD https://jesss.s3.amazonaws.com/binaries/curl-unix-socket /usr/local/bin/curl-unix-socket

# download the ui
RUN curl -sSL https://jesss.s3.amazonaws.com/binaries/consul/${CONSUL_VERSION}/ui.zip -o /tmp/ui.zip \
	&& unzip /tmp/ui.zip -d /usr/src/ \
	&& rm -rf /tmp/ui.zip \
	&& mv /usr/src/dist /usr/src/consul \
	&& mkdir -p /etc/consul.d/ \
	&& chmod +x /usr/local/bin/consul \
	&& chmod +x /usr/local/bin/curl-unix-socket

ENTRYPOINT [ "/usr/local/bin/consul" ]
```

will fail with

```
Step 3 : ADD https://jesss.s3.amazonaws.com/binaries/consul/${CONSUL_VERSION}/consul /usr/local/bin/consul
Got HTTP status code >= 400: 403 Forbidden
```

ping @duglin @tiborvass @jlhawn

**Comment by duglin** [comment]
The issue is the trailing \\ on:
```
    && rm -rf /var/cache/apk/* \
```
believe it or not, and at one point I did try to change (fix!) this, but the \\ tells the parser to continue to the next line but then since the next line is blank, it reads the following line - meaning the ENV is part of the RUN.

I know its insane to not treat the blank line as something that stops the continuation, but due to backwards compat we had to keep it.

When I removed the trailing \\ everything worked for me.

**Comment by phemmer** [comment]
> I know its insane to not treat the blank line as something that stops the continuation, but due to backwards compat we had to keep it.

I want to echo a comment I just made in another issue (https://github.com/docker/docker/issues/15080#issuecomment-125611480).
I think docker needs to document/adopt a compatibility policy. This seems like a trivial item to maintain backwards compatibility for, and I see lots of other more significant breaking changes all the time.

**Comment by tiborvass** [comment]
@duglin can we fix this? This is a bug.

**Comment by duglin** [comment]
I have no problem with "fixing" this but this keep in mind, it is a breaking change.

ping @crosbymichael you ok with this change?

**Comment by tiborvass** [comment]
@duglin oh wait, I thought the desired behavior was already in docker. So are you saying it's not a bug in docker, but a typo in @jfrazelle's Dockerfile and that it would have never worked on any docker version?

**Comment by duglin** [comment]
I believe so yes, @jfrazelle needs to change her Dockerfile to remove the trailing \\ .

Now, its fair to say that it **should have** worked because to any normal person :-)  a blank line should not be considered the same as a \\ on that line, but that's how Docker has worked for quite some time. See this test:  https://github.com/docker/docker/blob/master/builder/parser/testfiles/brimstone-consuldock/Dockerfile#L18

**Comment by jfrazelle** [comment]
Oh whoops lol my b

**Comment by jfrazelle** [comment]
It was late haha but I do think it should err on that line :/

**Comment by duglin** [comment]
@jfrazelle @tiborvass and I were discussing this on irc - for 1.8 we won't make a chance, but do you have any opinion on whether we should change this for the long term?

**Comment by jfrazelle** [comment]
Closing tho due to my negligence

**Comment by jfrazelle** [comment]
I think it should have errored out

**Comment by cleung2010** [comment]
I am encountering this issue while trying to get Nomad's binary.

Dockefile:
```
FROM alpine:3.2
MAINTAINER Calvin Leung Huang <https://github.com/cleung2010>

ENV NOMAD_VERSION 0.2.3

# Add Nomad binary
ADD https://releases.hashicorp.com/nomad/{NOMAD_VERSION}/nomad_{NOMAD_VERSION}_linux_amd64.zip /tmp/nomad.zip

# Install Nomad and create optional config folder to be used
RUN unzip /tmp/nomad.zip -d /usr/bin \
    && chmod +x /usr/bin/nomad \
    && rm /tmp/nomad.zip \
    && mkdir /etc/nomad.d \
    && chmod a+w /etc/nomad.d

# Expose Nomad-related ports
EXPOSE 4646 4647 4648 4648/udp

ENTRYPOINT ["/usr/bin/nomad", "agent"]

```

```
Step 4 : ADD https://releases.hashicorp.com/nomad/{NOMAD_VERSION}/nomad_{NOMAD_VERSION}_linux_amd64.zip /tmp/nomad.zip
Got HTTP status code >= 400: 403 Forbidden
```

**Comment by cleung2010** [comment]
Whoops `{NOMAD_VERSION}` should have been `${NOMAD_VERSION}`!
