### ISSUE TITLE
Running a container changes /dev/pts mount options

### ISSUE THREAD

**Issue by colemickens** [docker/docker#15070]
```
$ docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
Docker version 1.7.1, build 786b29d
```

```
$ uname -a
Linux pixel 4.1.3-8ph #1 SMP Thu Jul 23 18:23:50 PDT 2015 x86_64 GNU/Linux
```

```
$ docker info
Containers: 95
Images: 238
Storage Driver: devicemapper
 Pool Name: docker-8:1-1709143-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 10.98 GB
 Data Space Total: 107.4 GB
 Data Space Available: 28.19 GB
 Metadata Space Used: 18.17 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.129 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.102 (2015-07-07)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.3-8ph
Operating System: Arch Linux
CPUs: 4
Total Memory: 15.61 GiB
Name: pixel
ID: IQZ2:YFRS:PP5C:XUIR:NRUX:PZ5N:LFTB:EBB3:FL6E:UYNG:WI5M:AGDG
Username: colemickens
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

Repro steps:

1: Open a terminal
2: Run any docker container
3: Try to open a new terminal. It fails "There was an error creating the child process for this terminal. grantpt: Operation not permitted.

This fails because docker is changing the mount options of /dev/pts:

```
$ mount | grep pts                          
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620)

 $ docker run -it ubuntu:14.10                  
root@28b7e9a71ba2:/# exit
exit

$ mount | grep pts           
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,mode=600)
```

I'm running on Arch Linux (all up to date). I can't recall any changes I'd made that would cause this to be happening all of the sudden.

**Comment by colemickens** [comment]
Done, issue description update.

**Comment by thaJeztah** [comment]
ping @LK4D4 @crosbymichael (I think) :-)

**Comment by colemickens** [comment]
Here's another person who seemed to have had this issue: http://www.kianmeng.org/2015/05/grantpt-failed-read-only-file-system.html

Please let me know if there's any information I can provide that will be helpful, @LK4D4, @crosbymichael. Thanks.

**Comment by LK4D4** [comment]
@colemickens That's weird, it changes nothing for me :/
Maybe you updated your kernel?

**Comment by colemickens** [comment]
So now I'm even more intrigued. Other users are seeing this remount behavior, but are not experiencing the grantpt failures: https://github.com/raphael/linux-4.1-samus/issues/24#issuecomment-127105286

Still stumped, but I'll try to dig into why grantpt is failing for me but not raphael.

**Comment by thaJeztah** [comment]
Please keep us posted, then we can decide if this issue should be closed or not :-)

**Comment by colemickens** [comment]
So, I can't repro this issue on a stock kernel. It looks like there is something about the patches applied from raphael/linux-4.1-samus, or something up with the kernel config in that repo.

Is there any documentation on the docker side about expected kernel configuration/options/etc?

**Comment by runcom** [comment]
@colemickens take a look at https://github.com/docker/docker/blob/master/contrib/check-config.sh

**Comment by colemickens** [comment]
@runcom that was very helpful, among other things, the script pointed out that CONFIG_DEVPTS_MULTIPLE_INSTANCES was missing, which seems like a likely culprit.

I'll go ahead and close this out.

**Comment by thaJeztah** [comment]
Thanks @colemickens !
