### ISSUE TITLE
Error when attempting to kill a non-running container breaks backwards compatibility

### ISSUE THREAD

**Issue by aanand** [docker/docker#15080]
As I understand it, #12371 made it an error to attempt to kill a non-running container. This makes sense, but it's very likely that lots of code out there relies on the current idempotency of the kill operation. The old behaviour should be preserved for older API versions.

**Comment by phemmer** [comment]
Perhaps the docker project should document its backwards-compatibility policy.
I've seen it stated in the past that the project aims to be compatible between 0.0.X releases, but not between 0.X.
There seems to be no official stance on the subject in the docs (that I can find).

**Comment by calavera** [comment]
I personally don't understand why we should error when the container is not running, but I guess that's too late to change.

I agree though that the previous behavior should have been preserved for backwards-compatibility. Basically everything that changes any response in the API needs to preserve backwards-compatibility, that should basically be the policy, if it's not already.

**Comment by calavera** [comment]
#15098 should fix this issue.
