### ISSUE TITLE
Multiline ENV statement does not expand environment variables

### ISSUE THREAD

**Issue by gurunars** [docker/docker#15083]
The following declaration:

    ENV ONE=foobar TWO=$ONE/zooloo

Produces:

    > echo $ONE
    foobar
    > echo $TWO
    $ONE/zooloo

Should be:

    > echo $ONE
    foobar
    > echo $TWO
    foobar/zooloo

At the same time two separate statements work just fine:

    ENV ONE=foobar
    ENV TWO=$ONE/zooloo

with:

    > echo $ONE
    foobar
    > echo $TWO
    foobar/zooloo

**Comment by phemmer** [comment]
see #14914

**Comment by duglin** [comment]
@phemmer thanks was looking for that issue!
Closing.

**Comment by gurunars** [comment]
Thanks. Understood.
