### ISSUE TITLE
Is multiple ethernet possible for docker option?

### ISSUE THREAD

**Issue by letusfly85** [docker/docker#15110]
Description of problem:

I want to use docker with bond which includes multiple ethernets,

I generated bond using `nmcui`, and configured `/etc/sysconfig/docker` and tried to restart docker.

`systemctl restart docker`

however, docker didn't start...

`docker version`:
```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): ba1f6c3/1.6.2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): ba1f6c3/1.6.2
OS/Arch (server): linux/amd64
```

`docker info`:
```
Containers: 2
Images: 93
Storage Driver: devicemapper
 Pool Name: docker-253:1-356462-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 7.51 GB
 Data Space Total: 107.4 GB
 Data Space Available: 28.8 GB
 Metadata Space Used: 7.864 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.14 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Kernel Version: 3.10.0-229.7.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 4
Total Memory: 7.603 GiB
Name: zns.qc
ID: SCQ3:JNDM:UIZM:LNR3:UIN2:NAB2:XZR3:5TUW:D3KG:A3GS:DY7P:DWC3
```

`uname -a`:
root

Environment details (AWS, VirtualBox, physical, etc.):
CentOS Linux release 7.1.1503 (Core) 

Question:
I want to use network bond for `DOCKER_OPTS` like

```
OPTIONS="-b=bond"
```

Is it possible to use multiple ethernet?

**Comment by unclejack** [comment]
@letusfly85 You can have multiple network interfaces in a container using https://github.com/jpetazzo/pipework

I'm going to close this as this is a solution you can use right away. The networking system is still being developed to allow more flexible custom network drivers.

Please feel free to comment if you have any other questions.

**Comment by letusfly85** [comment]
@unclejack 

Thanks, I'll try this! :smile:

**Comment by letusfly85** [comment]
@unclejack 

I got it!
Thank you!!! :+1: :smile:
