### ISSUE TITLE
feature request: docker pull info

### ISSUE THREAD

**Issue by senthilnayagam** [docker/docker#1512]
1) there should be a docker command to get info about the image being pulled, specifically the total size of the download.

some of the downloads were couple of MB where others where in GB

2) there should be option to download just the dockerfile which built the image and rebuild it locally

**Comment by schmunk42** [comment]
:+1:

**Comment by resouer** [comment]
@thaJeztah  Thanks for lead me here. But there's another question in my use case: how can I conveniently list all the image layers on a host?

**Comment by LK4D4** [comment]
I saw similar issue today and even pinged @estesp there, but I'm too lazy to find it. This is definitely duplicate, but I won't close it without a link to another issue.
ping @thaJeztah maybe you know

**Comment by thaJeztah** [comment]
@LK4D4 did you mean https://github.com/docker/docker/issues/4239 ?

**Comment by LK4D4** [comment]
@thaJeztah nope #15794

**Comment by LK4D4** [comment]
But probably they all about same thing - proxy registry api to docker api.

**Comment by LK4D4** [comment]
This is superseded by #24739 and I hope will be implemented soon.
