### ISSUE TITLE
Allow status of Docker containers to be watched

### ISSUE THREAD

**Issue by arun-gupta** [docker/docker#15143]
Add a new option to `docker ps` to allow watching the status of containers.

Something like `docker ps -w` would be useful.

**Comment by cpuguy83** [comment]
Can you give an example in what this might look like?
I'm not sure I understand the request.

**Comment by arun-gupta** [comment]
`docker ps -w` can refresh the status every 30 seconds by default. This can also be customized like `docker ps -w 45` where the status will refresh every 45 seconds.

**Comment by phemmer** [comment]
You can use the `watch` utility for this.

    watch -n 30 docker ps

**Comment by arun-gupta** [comment]
That's not a utility packaged with OS X and it would be nice to provide a native integration within `docker ps` itself.

**Comment by vdemeester** [comment]
@arun-gupta maybe you can achive this with something like ``docker stats $(docker ps -q)`` ?

**Comment by arun-gupta** [comment]
@vdemeester that does not show any new containers that are started, or old containers that are shutdown. Formatting options are pretty limited too.

**Comment by cpuguy83** [comment]
```bash
docker-watch() {
  sleep_time=$1
  [ -z $sleep_time ] && sleep_time=30
  while true; do
    printf "\033c"
    docker ps -a
    sleep $sleep_time
  done
}
```

**Comment by arun-gupta** [comment]
@cpuguy83 sure, there are multiple ways to achieve that. But I think this would be a common functionality and providing a more seamless support from the docker CLI would be useful.

**Comment by aidanhs** [comment]
When you say it's a common functionality, what's the use case for needing it? I can't see that it's worth the burden of maintaining within docker when it's so trivial to achieve externally.

**Comment by cpuguy83** [comment]
Agreed, this isn't right inside docker. This can be watched externally easily enough.

**Comment by ryan-blunden** [comment]
For those on OSX who want this functionality:

# Presumes homebrew is install
`
brew install watch
watch -n 5 docker ps
`
