### ISSUE TITLE
Docker pull not working with special characters in TAG name

### ISSUE THREAD

**Issue by sachingharge** [docker/docker#15152]
Hi,

We could able to push docker image with special characters in tag name however while pulling it gives error image not found.

TAG name: 1.0.0-SNAPSHOT

Please confirm if special characters are allowed in TAG name? Also please share us the allowed values for tag name?

Thanks in advance!

**Comment by sachingharge** [comment]
Hi,

Please find below request information:

---------------------------------------------------------------------------------------------------------------------------------------
docker version:
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2-dirty
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2-dirty
OS/Arch (server): linux/amd64

docker info:
Containers: 7
Images: 44
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 4.0.5
Operating System: CoreOS 717.3.0
CPUs: 2
Total Memory: 3.863 GiB
Name: ip-10-17-17-52.us-west-2.compute.internal
ID: VK5U:46F2:DED7:JIH7:LUJ4:QIY7:CZ3S:7NCI:BBIX:VHDM:EP6O:FQYJ

uname -a:
Linux ip-10-17-17-52.us-west-2.compute.internal 4.0.5 #2 SMP Fri Jul 10 06:25:01 UTC 2015 x86_64 Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz GenuineIntel GNU/Linux

Environment: AWS, CoreOS with Kubernetes

We are pulling from docker private repo hosted on Artifactory.

Docker pull output:
docker -D pull repo_hostname/app/app-service:1.0.0-SNAPSHOT
pulling repository docker-repo.cloud.accedo.tv/viamw/appgrid-service
FATA[0008] Error: image app/app-service:1.0.0-SNAPSHOT not found
---------------------------------------------------------------------------------------------------------------------------------------

Please let us know if you need any more information on this topic.

**Comment by cpuguy83** [comment]
Is this to DockerHub?
There was an issue yesterday with pushing images to DockerHub.
Is it still a problem?
Have you tried pushing to a private registry?

**Comment by thaJeztah** [comment]
@sachingharge could you provide the information @cpuguy83 requested? I'm going to close this issue for now, but will re-open once we have some more information
