### ISSUE TITLE
Install on RHEL 7.1 using the script fails

### ISSUE THREAD

**Issue by schrepfler** [docker/docker#15155]
The install script fails as the dist_version on RHEL 7.1 will resolve to 7.1 making the script look into https://yum.dockerproject.org/repo/main/centos/7.1/ rather than https://yum.dockerproject.org/repo/main/centos/7/
This can be fixed either by fixing the script or making a symlink on the repo.

**Comment by Djelibeybi** [comment]
Resolved by PR #15103.

**Comment by thaJeztah** [comment]
Thanks for reporting @schrepfler. This should be resolved by https://github.com/docker/docker/pull/15103 (thanks @Djelibeybi), could you test if this is working for you now?

I'm going to close this issue, but feel free to comment if it's not resolved :+1:

**Comment by schrepfler** [comment]
Working :+1:

**Comment by thaJeztah** [comment]
Thanks for confirming @schrepfler !
