### ISSUE TITLE
/etc/default/docker has no effect on debian 8

### ISSUE THREAD

**Issue by anapsix** [docker/docker#15157]
It appears that `/lib/systemd/system/docker.service` does not care about `/etc/default/docker`.
Discovered when attempted to set `DOCKER_OPTS="-H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock"`.
Perhaps, it would make sense to make `docker.service` load it with with EnvironmentFile

    EnvironmentFile=/etc/default/docker
    ExecStart=/usr/bin/docker -d $DOCKER_OPTS

## environment
Installed `docker` via `curl get.docker.io | bash` two hours ago.. 

```
anapsix@fit:~$ docker version 
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```

```
anapsix@fit:~$ docker info
Containers: 3
Images: 87
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 93
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 4
Total Memory: 7.438 GiB
Name: fit
ID: 5TGZ:CYVO:PQ4R:7NQO:BWGV:PG5M:CBD2:QFNK:KMHC:4Y7S:R665:LPG6
```

**Comment by jgkamat** [comment]
See [this pr](https://github.com/docker/docker/pull/13923#issuecomment-112220002)
I'm not sure of the status of this at this point though.

**Comment by anapsix** [comment]
ok, so there are bunch of issues for this:
- #13439
- #14196
- docker/machine#1431
- #14319
- #14323
- #14149
- #14513

and a number of PRs.. no obvious solution though..
no sense if keeping this one open
