### ISSUE TITLE
adding page-title for docs

### ISSUE THREAD

**Issue by arthurk** [docker/docker#15150]
Hi, would it be possible to display a page-title in the docs? When browsing the documentation with multiple tabs it is hard to distinguish which tab has which section open:

![screen shot 2015-07-30 at 10 03 16](https://cloud.githubusercontent.com/assets/23406/8978403/3e8e8b74-36a2-11e5-8bb4-aca98146513e.png)

**Comment by thaJeztah** [comment]
Thanks for reporting this; this was actually already fixed, and will be published with the next release; https://github.com/docker/docs-base/commit/c2e00b96b6caddd004df29bafd3df27e6f1351e4#diff-8ab16b2cae0b26a574b75e8e5c19e378

I'm going to close this, but feel free to come there after closing. Thanks again!
