### ISSUE TITLE
Question: Install specific version to Debian

### ISSUE THREAD

**Issue by MichaelDrogalis** [docker/docker#15165]
Hi everyone! Thanks for the awesome work you put into Docker!

I have a question about installation. The website recommends that we install docker via `wget -qO- https://get.docker.com/ | sh`. This is problematic for creating repeatable infrastructure because we can't specify a version. I ran into an issue a bit ago where that script previously installed 1.6, and running it again this week I pulled down 1.7. This caused some breakage of the services that were using it.

What's the recommended approach for downloading a *specific* version of Docker?

**Comment by cpuguy83** [comment]
@MichaelDrogalis Check out the script (you should anyway!).
It just loads an apt repo. You can do this manually and specify a version as you normally would... i.e. `apt-get install docker-engine=1.7.1` (or whatever the version string is).

**Comment by MichaelDrogalis** [comment]
Thanks!
