### ISSUE TITLE
Provide a way to remove all stopped containers

### ISSUE THREAD

**Issue by luxas** [docker/docker#15160]
Now we can do `docker rm $(docker ps -aq)` and ignore the errors if a container is running.

But it doesn't seem like a good solution.

Could `docker rm --stopped` be a solution?

After a lot of builds via Dockerfiles, many stopped, only used once containers are left in the system and takes up much space.

Thanks for looking into this.

**Comment by jgkamat** [comment]
This would be nice to have, I spend a lot of time running ```docker rm -f `docker ps -aq` ```, and running `docker rm -s` would be much faster in my workflow.

**Comment by cpuguy83** [comment]
I'm a huge -1 on this.
Not adding another flag to `docker rm`.
You can already do `docker rm $(docker ps --filter status=exited -q)`

**Comment by luxas** [comment]
Yeah, but isn't that a very long command?
Should it say in the docs, type `docker rm $(docker ps --filter status=exited -q)` and then docker will remove your 8 containers.

I think this would make users workflow faster

```
$ docker rm --help
  -f, --force=false      Force the removal of a running container (uses SIGKILL)
  --help=false           Print usage
  -l, --link=false       Remove the specified link
  -v, --volumes=false    Remove the volumes associated with the container
```
I don't understand what you mean with "another flag".
Please explain.

**Comment by phemmer** [comment]
It's about feature bloat. If you start adding lots of little features everywhere, the code gets very large and unmaintainable.

This feature is also very specific, with a very limited use case. What if someone wants to only remove containers with an exit status of `1`. Or containers that are paused. These would require additional flags. `docker ps --filter` has a very capable filtering system where the output can be sent into `docker rm`.
[Rule of Composition: Design programs to be connected with other programs](http://www.faqs.org/docs/artu/ch01s06.html#id2877684)

**Comment by jgkamat** [comment]
Perhaps docker could have an aliasing option (sort of like the one git has)? Not sure how useful this could be though, aside from running docker on personal machines.

I currently just alias `dockerremoveallcontainers`->`docker rm $(docker rm -aq)`. (which can be autocompleted).

**Comment by luxas** [comment]
@phemmer Ok, I take that explanation.
Didn't think about it that way, and I understand if it's against your philosophy.

But I would have been an useful command for users :)

@jgkamat How did you set up that alias (in Bash)?
Is it in the .bashrc file?

**Comment by jgkamat** [comment]
Yup, I just have this in my bashrc.
```
dockerremoveallcontainers() {
	docker rm $@ $(docker ps -a -q)
}
```
This is a little better than an alias, in that any flags passed to dockerremoveallcontainers will be passed to docker rm. tbh a shorter name is probably better. This works too (but dosen't let you pass flags):
```
alias dockerremoveallcontainers='docker rm -f $(docker ps -aq)'
```

**Comment by thaJeztah** [comment]
So, based on the discussion above, I think there are some options here;

- Improve documentation around this; perhaps a "tips and tricks" section, describing frequently used commands (and how to create those aliases)
- Add examples to the `/contrib/` directory in the repository
- Add a `--filter` flag to `docker rm`, providing the same options as `docker ps`. Given the responses above, this may not be wanted (feature bloat)

/cc @moxiegirl any opinion on such section in the docs? Would that be out of bound for the documentation?

**Comment by phemmer** [comment]
What about the other option I see mentioned a lot (@jgkamat did so above), using git style custom commands? Drop a script called "rm-exited" in a directory and have it become available as `docker rm-exited`?

**Comment by luxas** [comment]
It would be nice with a "tips and tricks" section in the docs, absolutely.
And there it could be a section with git-like custom commands, with some examples (and maybe some code in /contrib)

That sounds good

**Comment by thaJeztah** [comment]
@phemmer yup, that'd be an option; I didn't leave it out on purpose, just trying to see if we can move this issue forward in some way.

I know git-style commands have been discussed a number of times before, but never got much traction. However, I think I saw some (core-) maintainers warming up to the idea, so it may become an option.

@phemmer Do you think we should add it to the list here, or open a separate proposal for that? I fear that adding it may only lengthen the discussion here.

**Comment by banerRana** [comment]
Trying to delete all stopped containers, sounds like wanting to flush the
environment. So why not consider to reboot. In production, there will be
scenarios where deleting all stopped containers can wreck havoc, at times
it is needed to analyze what went wrong . Incorporating that into the
feature will allow novice users consider this solution.

Having this functionality setup outside of docker, via shell or any other
means is a more pragmatic approach.

**Comment by moxiegirl** [comment]
@thaJeztah A section  "Using your shell with Docker" or some such. Tips and tricks is a bit generic and could apply to anything.  WDYT?

**Comment by thaJeztah** [comment]
@moxiegirl yeah, "tips and tricks" was the first that sprang in mind :-)

**Comment by xiaods** [comment]
-1

**Comment by cpuguy83** [comment]
Anyone want to take a shot at these docs?

**Comment by LK4D4** [comment]
ping @thaJeztah 
Can you open issue or PR for docs?
I'm closing this because title and discussion outdated.
