### ISSUE TITLE
Header requirement prevents pull from static files

### ISSUE THREAD

**Issue by mhrivnak** [docker/docker#15173]
Docker requires [0] that the header "Docker-Distribution-API-Version" be included in a response from the /v2/ endpoint. Based on my testing with 1.7.1, this requirement is the only thing preventing "docker pull" from working with static files on a dumb web server.

Background: https://github.com/docker/distribution/issues/99

Perhaps a deployment requiring authn doesn't require this extra complexity. An alternative would be to require a 404 response from a server that does not implement the requested API endpoint. So if someone requests `/v3/`, they get a 404 instead of 401.

If unauthenticated version discovery is important, consider making an unauthenticated endpoint explicitly for returning a list of supported versions. Why hide this data in headers?

```
GET /api_versions/

[
    {
        "version": "2", 
        "link": "/v2/"
    }, 
    {
        "version": "2.1", 
        "link": "/v2.1/"
    }
]
```

These are just a couple of ideas to start the conversation, and I'm sure there are other fine options. One way or another, we are _very_ close to being able to "docker pull" from static files, which is a great feature. Removing the requirement for this header will seal the deal.

[0] https://github.com/docker/docker/blob/v1.7.1/registry/endpoint.go#L236

**Comment by thaJeztah** [comment]
Although I'm not always a fan of headers, I *do* think that this has the advantage that a single request provides all the required information to determine what kind of registry Docker is talking to.

ping @stevvooe

**Comment by stevvooe** [comment]
@mhrivnak Can you not add `Docker-Distribution-API-Version: registry/2.0` header to the static file server?

We opted to fully protect the server in v2, rather than allow certain URLs but not others. It simplifies the security model at the cost of unauthenticated exploration used during version resolution. A similar json response was explored but choosing a future-proof format proved problematic. The headers are fairly unfortunate but most negotiation is actually done on a per endpoint level, making the url version less useful. In the future, the endpoint versions will be a part of the docker daemon's configuration and discovery process.

**Comment by mhrivnak** [comment]
@stevvooe it depends. If I'm running my own apache instance, it's fairly trivial. If I want to host a registry directly on S3, then no. How amazingly convenient would that be, to host your registry in S3 or similar!

Or if I'm using shared file/web hosting, like ``http://username.fedorapeople.org``, I may not have the ability to add custom headers. (I have no idea if that's true specifically for fedorapeople.org, but you can imagine similar infrastructure through a job or school being locked down.)

Another completely reasonable option is to try auth on the endpoint the client prefers. So if you get a 401 on ``/v2.1/``, try again with credentials. If that fails or results in 404, then fall back to ``/v2/``. After all, how many API versions do you realistically intend to support in one version of the client? Given this approach, most of the time the first requests would succeed. For those cases where they have to fall back to an older API, there will be one or two extra requests, and that's incentive to upgrade. ;)

Speaking to simplicity, no deployment would be simpler than dropping static files in a cloud storage service. If we can find some agreeable solution to this header issue, the overall usability gains will be huge.

**Comment by stevvooe** [comment]
I agree, this would be nice.

IMHO, S3 is way behind the times. CDNs like fastly allow [one to set custom headers](https://docs.fastly.com/guides/basic-configuration/adding-or-modifying-headers-on-http-requests-and-responses). Really, the power use case here is actually exporting to a static file server, which one tends to have more control over.

> Another completely reasonable option is to try auth on the endpoint the client prefers. So if you get a 401 on /v2.1/, try again with credentials. If that fails or results in 404, then fall back to /v2/. After all, how many API versions do you realistically intend to support in one version of the client? Given this approach, most of the time the first requests would succeed. For those cases where they have to fall back to an older API, there will be one or two extra requests, and that's incentive to upgrade. ;)

The code was originally written to assume v1 and try to make v2 work. We can change this assumption now. I agree with the assertion that v1 incurring a few extra requests is acceptable.

A few things we'll need to make this real:

1. Relax the header requirement in docker engine client. We should try v2 auth by default and only go back to v1 when a 404 is encountered on "/v2/". There are some subtleties around tags and manifest 404s, but we can handle those. 
2. Provide a registry export mechanism. Imagine this:

  1. Export the registry to a static root with the following command:

    ```console
    registry export <url> > registry-www-root.zip
    ```
  
    The zipfile will be laid out in the same format as the registry API.

  2. Ship the entire exported registry zip file to your datacenter. Perhaps, build it as a docker container, complete with data.
  3. Unpack the zip file under your desired static file server. Perhaps, we could provide a "zip" backend for the registry that operates read-only.

You're welcome to give this a try.

**Comment by vbatts** [comment]
Ok, This actually looks like it was _intended_ to work correctly without this header being provided, but there is a logic loop blocking it from happening.

The header field to check for is [set as a global variable `DefaultRegistryVersionHeader`](https://github.com/docker/docker/blob/v1.8.2/registry/config.go#L30). The global variable [is set as the `VersionHeader`](https://github.com/docker/docker/blob/v1.8.2/registry/service.go#L189) to be checked for. Then lastly in the docker/docker code base, the http response from the registry endpoint is [checked for presence of the header](https://github.com/docker/docker/blob/v1.8.2/graph/registry.go#L71).
Then we're over into docker/distribution code base. The [check for headers](https://github.com/docker/distribution/blob/ec87e9b6971d831f0eff752ddb54fb64693e51cd/registry/client/auth/api_version.go#L28) is calling `ParseAPIVersion()`. This parser looks to fail with an "unknown" entry on an empty record, which works fine for a static registry. Unfortunately, that parse will on get hit for each [matched header in the `http.Response`](https://github.com/docker/distribution/blob/ec87e9b6971d831f0eff752ddb54fb64693e51cd/registry/client/auth/api_version.go#L31), which is 0 times.

Now our [list of `versions`](https://github.com/docker/docker/blob/v1.8.2/graph/registry.go#L71) is an empty list. Causing a cascade of nil pointers when fetching. :frowning: 

As a hack to test this, I checked if the list was empty, if so, add an "unknown" version. This works fine.
```diff
diff --git a/graph/registry.go b/graph/registry.go
index 9b744ed..46be5b6 100644
--- a/graph/registry.go
+++ b/graph/registry.go
@@ -69,6 +69,9 @@ func NewV2Repository(repoInfo *registry.RepositoryInfo, endpoint registry.APIEnd
        defer resp.Body.Close()
 
        versions := auth.APIVersions(resp, endpoint.VersionHeader)
+       if len(versions) == 0 {
+               versions = append(versions, auth.APIVersion{Type: "unknown", Version: "-1"})
+       }
        if endpoint.VersionHeader != "" && len(endpoint.Versions) > 0 {
                var foundVersion bool
                for _, version := range endpoint.Versions {
```
(diff is against docker/docker v1.8.2 tag)

**Comment by LK4D4** [comment]
@stevvooe Any news here? Should we close or proceed?

**Comment by stevvooe** [comment]
@LK4D4 With default usage of v2, we can relax this requirement. I think we should proceed and support this use case.

**Comment by LK4D4** [comment]
@stevvooe Cool!
@thaJeztah Can you pls take care of this issue. Maybe add it to milestone?

**Comment by thaJeztah** [comment]
I reopened https://github.com/docker/docker/pull/16325, but it will require some work to get it working again for the current code base

**Comment by thaJeztah** [comment]
Based on https://github.com/docker/docker/pull/16325#issuecomment-247079797, this most likely should now work; @mhrivnak are you able to confirm if this issue is resolved?

**Comment by stevvooe** [comment]
@aaronlehmann PTAL

**Comment by aaronlehmann** [comment]
I commented here: https://github.com/docker/docker/pull/16325#issuecomment-247079797

**Comment by thaJeztah** [comment]
Ok, this should be resolved https://github.com/docker/docker/pull/16325#issuecomment-247079797
