### ISSUE TITLE
Docker installation script chokes on Fedora 21

### ISSUE THREAD

**Issue by andrewrothstein** [docker/docker#15171]
sudo wget -qO- https://get.docker.com/ | sh
When I run this on my Fedora 21 box it complains: "TwentyOne" is not a number...
Digging in this code block:
```bash
        if command_exists lsb_release; then
                lsb_dist="$(lsb_release -si)"
                dist_version="$(lsb_release --codename | cut -f2)"
        fi
```
On my desktop dist_version is
    arothste@localhost ~ > lsb_release --codename | cut -f2
    TwentyOne

The script assumes this is a number like `21`.
Not sure how well this works on other platforms but...
    arothste@localhost ~ > lsb_release -r | cut -f2
    21
works better!

**Comment by Djelibeybi** [comment]
Resolved by PR #15103.

**Comment by thaJeztah** [comment]
Thanks for reporting @andrewrothstein. This should be resolved by https://github.com/docker/docker/pull/15103 (thanks @Djelibeybi), could you test if this is working for you now?

I'm going to close this issue, but feel free to comment if it's not resolved :+1:

**Comment by andrewrothstein** [comment]
It worked for me thanks!

**Comment by thaJeztah** [comment]
Thanks for confirming, @andrewrothstein, much appreciated!
