### ISSUE TITLE
error pulling

### ISSUE THREAD

**Issue by aakash17** [docker/docker#15197]
336ea692b64d: Error pulling dependent layers 
Error pulling image (latest) from greenqloud/varnish-nginx, HTTP code 401
how to resolve it

**Comment by cpuguy83** [comment]
Please provided the requested details.
401 == unauthorized, so maybe the image layer is now private? This is of course assuming you have looked at other connectivity issues (such as issues from a proxy server).

**Comment by thaJeztah** [comment]
unable to reproduce this issue, pulling this image with docker 1.7.1 worked for me. I suggest checking if there are general connection issues, as @cpuguy83 commented

**Comment by cpuguy83** [comment]
Closing since we need more information.
If you can provide repro steps please ping here with the info and we can take a look.
Thanks!
