### ISSUE TITLE
Docs: wrong path to 'Routing' menu for openSUSE Tumbleweed.

### ISSUE THREAD

**Issue by Evalle** [docker/docker#15198]
For openSUSE Tumbleweed there is a wrong path to 'Routing' menu in docker installation docs.  
Here is the link: https://docs.docker.com/installation/SUSE/

> "If you want your containers to be able to access the external network you must enable the net.ipv4.ip_forward rule. This can be done using YaST by browsing to the Network Devices -> Network Settings -> Routing menu and ensuring that the Enable IPv4 Forwarding box is checked." 

It's true for openSUSE 12.3, 13.1, 13.2 and also for SLES12, but for openSUSE Tumbleweed there is no 'Network devices' menu in YaST and 'Network settings' menu in 'System' menu of YaST. 
So I believe that we need to add that information into docs.

**Comment by Evalle** [comment]
# dibs
I want to change mentioned lines to:

> "If you want your containers to be able to access the external network you must enable the net.ipv4.ip_forward rule. This can be done using YaST by browsing to the System -> Network Settings -> Routing menu (for openSUSE Tumbleweed and later) or Network Devices -> Network Settings -> Routing menu (for SUSE Linux Enterprise 12 and previous openSUSE versions) and ensuring that the Enable IPv4 Forwarding box is checked." 

Please, tell me if it's OK for you or not.

**Comment by Evalle** [comment]
#dibs

I want to change mentioned lines to:

> "If you want your containers to be able to access the external network you must enable the net.ipv4.ip_forward rule. This can be done using YaST by browsing to the System -> Network Settings -> Routing menu (for openSUSE Tumbleweed and later) or Network Devices -> Network Settings -> Routing menu (for SUSE Linux Enterprise 12 and previous openSUSE versions) and ensuring that the Enable IPv4 Forwarding box is checked." 

Please, tell me if it's OK for you or not.

**Comment by thaJeztah** [comment]
sgtm, @Evalle feel free to create a pull request!

**Comment by Evalle** [comment]
Fixed
