### ISSUE TITLE
Deadlock when deleting images

### ISSUE THREAD

**Issue by mountkin** [docker/docker#15195]
When I run `docker rmi $(docker images -q -f dangling=true)` on one terminal while at the same time call the image list API via `curl -v http://127.0.0.1:2375/images/json` on another terminal, the daemon seems to be running into a dead lock.
```
goroutine 139 [semacquire, 60 minutes]:
sync.(*RWMutex).RLock(0xc2082d7e00)
	/usr/local/go/src/sync/rwmutex.go:36 +0x5f
github.com/docker/docker/pkg/truncindex.(*TruncIndex).Get(0xc2082d7e00, 0xc208410580, 0x40, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/pkg/truncindex/truncindex.go:111 +0x12b
github.com/docker/docker/graph.(*Graph).Get(0xc20817cb80, 0xc208410580, 0x40, 0xc2092074c0, 0x0, 0x0)
	/go/src/github.com/docker/docker/graph/graph.go:173 +0x69

......

goroutine 230 [semacquire, 60 minutes]:
sync.(*RWMutex).Lock(0xc2082d7e00)
    /usr/local/go/src/sync/rwmutex.go:87 +0xa4
github.com/docker/docker/pkg/truncindex.(*TruncIndex).Delete(0xc2082d7e00, 0xc209947640, 0x40, 0x0, 0x0) 
    /go/src/github.com/docker/docker/pkg/truncindex/truncindex.go:80 +0x56
github.com/docker/docker/graph.(*Graph).Delete(0xc20817cb80, 0xc2093ed100, 0x40, 0x0, 0x0) 
    /go/src/github.com/docker/docker/graph/graph.go:360 +0x125
github.com/docker/docker/daemon.(*Daemon).imgDeleteHelper(0xc2080efce0, 0xc20888fb45, 0xc, 0xc2093e02a0, 0x1, 0x0, 0x0) 
    /go/src/github.com/docker/docker/daemon/image_delete.go:120 +0xea5
github.com/docker/docker/daemon.(*Daemon).ImageDelete(0xc2080efce0, 0xc20888fb45, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0) 
    /go/src/github.com/docker/docker/daemon/image_delete.go:19 +0x122
github.com/docker/docker/api/server.(*Server).deleteImages(0xc208035300, 0xc20888fb39, 0x4, 0x7fb50589f038, 0xc208701540, 0xc208eff6c0, 0xc20888fcb0, 0x0, 0x0)
```

The full stack via pprof is here https://gist.github.com/mountkin/079210d66370ed99bc03
I also encountered another deadlock while I ran `docker build` on one terminal and call the image list API on another terminal.

After bisecting I found before cc955ae73c8aa234e0c41bdb65f111be79b32b90 everything is ok.

I'm not sure if this is related to @vbatts's issue #15087 

---
To make @GordonTheTurtle happy,
docker info
```
Containers: 26
Images: 933
Storage Driver: aufs
 Root Dir: /root/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1028
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 2
Total Memory: 994 MiB
Name: local-dev
ID: LD3D:36J2:EXD2:2TA6:DJYU:ZLPK:W3BS:VHHH:VFA2:URJD:OID6:QJ2Y
Debug mode (server): true
File Descriptors: 31
Goroutines: 52
System Time: 2015-07-31T14:46:00.021003093+08:00
EventsListeners: 0
Init SHA1: 
Init Path: /usr/bin/docker
Docker Root Dir: /root/docker
Username: csphere
Registry: https://index.docker.io/v1/
```

docker version
```
Client:
 Version:      1.8.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   500a314
 Built:        Fri Jul 31 06:45:08 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   500a314
 Built:        Fri Jul 31 06:45:08 UTC 2015
 OS/Arch:      linux/amd64
```

uname-a
```
Linux local-dev 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by thaJeztah** [comment]
@calavera is this only reproducible on master, or also on 1.8-rc1?

**Comment by mountkin** [comment]
@thaJeztah I haven't tested 1.8.0-rc1 yet. Will have a try later.
I opened a PR #15196, let's see if it can be reproduced successfully.

**Comment by thaJeztah** [comment]
Thanks for the extensive reporting, @mountkin, let me know if it's reproducible on rc1, then I'll add it to the milestone

**Comment by mountkin** [comment]
@thaJeztah  seems like it's blocking https://jenkins.dockerproject.org/job/Docker-PRs/13020/console

**Comment by thaJeztah** [comment]
@mountkin hm, alright. I'll add it to the milestone - thanks!

**Comment by mountkin** [comment]
@thaJeztah You're welcome.
I can confirm that 1.8.0-rc1 is also affacted.

**Comment by calavera** [comment]
thanks for opening this issue and bisecting the changes @mountkin. I think as a precaution measure I'm going to revert that commit, it was only a code improvement, kinda.

**Comment by thaJeztah** [comment]
This is fixed in https://github.com/docker/docker/pull/15207

Thanks again @mountkin! If you have time to confirm if https://github.com/docker/docker/pull/15207 resolve the issue, that would be great!
