### ISSUE TITLE
docker help - should display from begining

### ISSUE THREAD

**Issue by SaravanaStorageNetwork** [docker/docker#15200]
Hi,
I am trying docker.
When I just do docker --help. It just throws one page full of help and ends.
I have to scroll back to reach the top to see what it shows. 

Showing the help from begining helps :)

Something like this:
# docker --help 
Usage: docker [OPTIONS] COMMAND [arg...]

A self-sufficient runtime for linux containers.

[root@gant test]# docker version
Client version: 1.7.1.fc22
Client API version: 1.19
Package Version (client): docker-1.7.1-1.gitb6416b7.fc22.x86_64
Go version (client): go1.4.2
Git commit (client): b6416b7/1.7.1
OS/Arch (client): linux/amd64
Server version: 1.7.1.fc22
Server API version: 1.19
Package Version (server): docker-1.7.1-1.gitb6416b7.fc22.x86_64
Go version (server): go1.4.2
Git commit (server): b6416b7/1.7.1
OS/Arch (server): linux/amd64
[root@gant test]#
[root@gant test]#
[root@gant test]# docker info
Containers: 7
Images: 2
Storage Driver: devicemapper
Pool Name: docker-253:2-2265870-pool
Pool Blocksize: 65.54 kB
Backing Filesystem: extfs
Data file: /dev/loop0
Metadata file: /dev/loop1
Data Space Used: 531.4 MB
Data Space Total: 107.4 GB
Data Space Available: 10.25 GB
Metadata Space Used: 1.245 MB
Metadata Space Total: 2.147 GB
Metadata Space Available: 2.146 GB
Udev Sync Supported: true
Deferred Removal Enabled: false
Data loop file: /var/lib/docker/devicemapper/devicemapper/data
Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
Library Version: 1.02.93 (2015-01-30)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.6-300.fc22.x86_64
Operating System: Fedora 22 (Twenty Two)
CPUs: 8
Total Memory: 15.37 GiB
Name: gant
ID: LXQW:XOX4:AYMG:CSMN:3XZC:HIUZ:EW77:A6MA:ELPY:AMF2:UQ2U:S4ME
[root@gant test]# uname -a
[root@gant test]# uname -a
Linux gant 4.0.6-300.fc22.x86_64 #1 SMP Tue Jun 23 13:58:53 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[root@gant test]#

How to reproduce:
docker --help

**Comment by SaravanaStorageNetwork** [comment]
[root@gant test]# docker version
Client version: 1.7.1.fc22
Client API version: 1.19
Package Version (client): docker-1.7.1-1.gitb6416b7.fc22.x86_64
Go version (client): go1.4.2
Git commit (client): b6416b7/1.7.1
OS/Arch (client): linux/amd64
Server version: 1.7.1.fc22
Server API version: 1.19
Package Version (server): docker-1.7.1-1.gitb6416b7.fc22.x86_64
Go version (server): go1.4.2
Git commit (server): b6416b7/1.7.1
OS/Arch (server): linux/amd64
[root@gant test]# 
[root@gant test]# 
[root@gant test]# docker info
Containers: 7
Images: 2
Storage Driver: devicemapper
 Pool Name: docker-253:2-2265870-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 531.4 MB
 Data Space Total: 107.4 GB
 Data Space Available: 10.25 GB
 Metadata Space Used: 1.245 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93 (2015-01-30)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.6-300.fc22.x86_64
Operating System: Fedora 22 (Twenty Two)
CPUs: 8
Total Memory: 15.37 GiB
Name: gant
ID: LXQW:XOX4:AYMG:CSMN:3XZC:HIUZ:EW77:A6MA:ELPY:AMF2:UQ2U:S4ME
[root@gant test]# uname -a
[root@gant test]# uname -a
Linux gant 4.0.6-300.fc22.x86_64 #1 SMP Tue Jun 23 13:58:53 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[root@gant test]# 

How to reproduce:
docker --help

**Comment by duglin** [comment]
@SaravanaStorageNetwork I don't understand what you by "from the beginning".  Also, can you try the latest docker, the help text has changed a bit.

**Comment by SaravanaStorageNetwork** [comment]
@duglin  I may not have clearly stated the issue.

What I am kind of expecting is : 
docker --help  | less

Given that docker has *lots of options* , I need to scroll back to reach the top. :)

**Comment by hermansc** [comment]
He essentially wants `man docker` behaviour (i.e. going into less/pager mode) for when doing `docker --help`. I disagree and think it's common behaviour for `--help` not to hijack the tty and also if you indeed want to "go to the beginning" either use `man docker` or `docker --help | less`.

**Comment by duglin** [comment]
Unless some other maintainer wants to reopen it, I'm going to close this because this isn't something that Docker does today with any comments that might have lots of output.  And, as @hermansc said, you can just pipe the output to `more` or `less`.
