### ISSUE TITLE
Docker not utilizing all cores effectively

### ISSUE THREAD

**Issue by sheldonkwok** [docker/docker#15223]
Currently running around 40 containers on a 40 core bare metal machine. However, the load on the machine is pretty low and only two cores are ever at 100%. The system works fine on lower core count machines and also works when I individually cpuset each container to a core. Any known issues with cpu resource sharing? I would much rather use the standard cpu shares method over specifying a cpu for each process

Containers: 40
Images: 40
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.18.0-031800-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 40
Total Memory: 125.9 GiB
Name: worker1

Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd6

Linux worker1 3.18.0-031800-generic #201412071935 SMP Mon Dec 8 00:36:34 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cpuguy83** [comment]
This is all handled by the kernel. Certainly cgroups lets you assign processes to specific cores, but otherwise I'd let the kernel do what it does.

As far as the Docker daemon itself, it will by default only startup using a single core as this is the go default.

**Comment by sheldonkwok** [comment]
Okay thanks I'll handle this on my own then

**Comment by unclejack** [comment]
As @cpuguy83 has also stated, whatever you run in containers has nothing to do with Docker itself when it comes to using all cores, it depends on the software you run and on the kernel itself.

The Docker daemon uses only one core by default. This will change when we switch to Go 1.5.

I'm going to close this issue now as I've seen containers scale to 32+ cores and there's really nothing to fix there.

**Comment by sheldonkwok** [comment]
It wasn't an issue with Docker but with the scheduler. Thanks to @cpuguy83 for the info
