### ISSUE TITLE
docker pull errror :Error response from daemon...." after add --insecure-registry {centos 7}

### ISSUE THREAD

**Issue by kaulie** [docker/docker#15221]
OS : centos 7
when I execute 
-- docker pull 172.27.2.14::5000/gl/hello-world 
Error response from daemon: invalid registry endpoint https://172.27.2.14:5000/v0/: unable to ping registry endpoint https://172.27.2.14:5000/v0/
v2 ping attempt failed with error: Get https://172.27.2.14:5000/v2/: tls: oversized record received with length 20527
 v1 ping attempt failed with error: Get https://172.27.2.14:5000/v1/_ping: tls: oversized record received with length 20527. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry 172.27.2.14:5000` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/172.27.2.14:5000/ca.crt

then i add "other_args="--insecure-registry 172.27.2.14:5000"" to /etc/sysconfig/docker 
then 'sudo service docker restart'
> Restarting docker (via systemctl):                         [  OK  ]
then execute "docker pull 172.27.2.14::5000/gl/hello-world", error still there !!!!

-- But when I run docker -d --insecure-registry 172.27.2.14:5000
-- succeed!

so I wonder "sudo service docker restart" don't restart docker with "--insecure-registry 172.27.2.14:5000",
why???

-- docker version

Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64

help!!

**Comment by hermansc** [comment]
You need to add the flag to the service file that systemd uses for starting your daemon. It's explained in the [systemd configuration page](https://docs.docker.com/articles/systemd/) and more specifically your need to add `EnvironmentFile=-/etc/sysconfig/docker` to your service file.

**Comment by kaulie** [comment]
@hermansc That works! thanks!

**Comment by thaJeztah** [comment]
looks to be resolved, closing

thanks all!
