### ISSUE TITLE
Documentation: Docker Event diagram add "zoom-in"

### ISSUE THREAD

**Issue by charleswhchan** [docker/docker#15234]
https://docs.docker.com/reference/api/docker_remote_api/

There is a state diagram under "Docker Events" and it looks okay on a large screen. However, on smaller screens (such as laptops), due to the page flow, the diagram can become too small to read.

Would be nice from a UX perspective if there was a way to zoom-in / maximize the picture when clicked. :relaxed:

**Comment by thaJeztah** [comment]
Did you have a particular script in mind, perhaps an example somewhere?

I'm  not against (I think the diagram could be made more interactive), but it depends a bit on the implementation I think :-)

**Comment by charleswhchan** [comment]
Something simple, like the example from Atlassian docs:
https://confluence.atlassian.com/display/BAMBOOCLOUD/Creating+a+job

When you click on a picture, it expands to full screen.

**Comment by thaJeztah** [comment]
ah, a generic lightbox. Perhaps we could add this to all images (although it won't be useful for all images)

/cc @moxiegirl

**Comment by LK4D4** [comment]
ping @thaJeztah

**Comment by thaJeztah** [comment]
opened a PR that adds a direct link to the image. not a fancy lightbox, but we can improve in future if needed: https://github.com/docker/docker/pull/26582
