### ISSUE TITLE
1.8: Error starting daemon: Error loading key file /etc/docker/key.json: unable to decode private key JWK: decoding JWK Private Key JSON data: unexpected end of JSON input

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#15247]
I started seeing this error with 1.8 and not <= 1.7 although I doubt it's really 1.8 specific.  What happens is if you start from a clean server that has no `/etc/docker/key.json` and then kill the Docker daemon before the is time for the buffers to be flushed, you end up with a zero byte `/etc/docker/key.json`.

I believe the correct approach here is to write to a temporary file, close, and then rename to `/etc/docker/key.json` to avoid creating a zero byte file.

**Comment by thaJeztah** [comment]
@ibuildthecloud interested in (and time for) opening a PR? (you know we :heart: those pully-thingies :smile:)

**Comment by telphan** [comment]
This issue is still present in docker 1.10. 

I suggest having checks in place before creating the file to delete corrupted trust files (e.g. zero byte size)

**Comment by thaJeztah** [comment]
@telphan can you open a new issue with steps to reproduce?

**Comment by telphan** [comment]
@thaJeztah https://github.com/docker/docker/issues/23985
