### ISSUE TITLE
"docker inspect gcr.io/google_containers/pause:0.8.0" command returned message slowly.

### ISSUE THREAD

**Issue by qq690388648** [docker/docker#15245]
The "gcr.io/google_containers/pause:0.8.0" image is the default "pod-infra-container-image" of kubernetes, that means when started a pods in kubernetes, it need to start a "gcr.io/google_containers/pause:0.8.0" container.
But I found when I typed "docker inspect gcr.io/google_containers/pause:0.8.0", it took about 10 seconds to return message. 
But when I typed "docker inspect hello-world", it returned the message immediately.
All of the images above had already been pulled into my machine before, so I'm wonder about why it happened.

**Comment by qq690388648** [comment]
I read the code in <code>api/client/inspect</code> and fount that the inspect command just sent a GET request to the daemon, so I used the "wget" tools to do the same thing.
Then I found the follow command got the return message immediately:
<code>
wget 127.0.0.1:4243/images/hello-world/json
wget 127.0.0.1:4243/images/docker.registry:5000/test/hello-world/json
wget 127.0.0.1:4243/images/2c40b0526b63/json
</code>
The "hello-world" image is the classical images pulled from docker hub.
The "docker.registry:5000/test/hello-world" image is the images pulled from our local registry.
The "2c40b0526b63" is the image_id of "gcr.io/google_containers/pause:0.8.0" image.
But the below command returned message after about 10 second.
<code>
wget 127.0.0.1:4243/images/gcr.io/google_containers/pause:0.8.0/json
</code>
Is there anyone can tell me what's different between these command?

**Comment by LK4D4** [comment]
@aaronlehmann Could you try to answer this question?

**Comment by aaronlehmann** [comment]
Sorry, no idea. If I try the command without pulling the image first, I get:

```
Error: No such image, container or task: gcr.io/google_containers/pause:0.8.0
```

If I pull the image and try again, it runs instantly.

Could this be some issue with locking slowing things down (cc @cpuguy83)? What version of Docker are you running?

**Comment by LK4D4** [comment]
@aaronlehmann Maybe it was fixed. The issue is a year old. Thanks for testing. Going to close now because we can't reproduce. Feel free to open new if the problem persists.
