### ISSUE TITLE
Docker crashes when MaxThreads is reached

### ISSUE THREAD

**Issue by jeremyeder** [docker/docker#15258]
According to [1], the idea of SetMaxThreads is to kill the program to save the OS (similar to oomkill).

The behavior of Docker when the limit is reached is that Docker itself crashes.  This should not happen of course; Docker should be hardened to return a sensible error to the client when it is nearing the MaxThreads limit.

[1] https://github.com/golang/go/blob/master/src/runtime/debug/garbage.go#L136

**Comment by jeremyeder** [comment]
@vbatts @rhatdan

**Comment by jeremyeder** [comment]
The full traceback is here:  http://people.redhat.com/jeder/docker_15258/docker_2500_container_backtrace.txt

The first few lines of the traceback:
```
Jul 28 16:05:00 dell-r510-02 docker: runtime: program exceeds 10000-thread limit
Jul 28 16:05:00 dell-r510-02 docker: fatal error: thread exhaustion
Jul 28 16:05:00 dell-r510-02 docker: runtime stack:
Jul 28 16:05:00 dell-r510-02 docker: runtime.throw(0x129a3c1)
Jul 28 16:05:00 dell-r510-02 docker: /usr/lib/golang/src/runtime/panic.go:491 +0xad fp=0x7fa56f709be8 sp=0x7fa56f709bb8
Jul 28 16:05:00 dell-r510-02 docker: checkmcount()
Jul 28 16:05:00 dell-r510-02 docker: /usr/lib/golang/src/runtime/proc.c:185 +0x60 fp=0x7fa56f709c00 sp=0x7fa56f709be8
Jul 28 16:05:00 dell-r510-02 docker: mcommoninit(0xc233be2e00)
Jul 28 16:05:00 dell-r510-02 docker: /usr/lib/golang/src/runtime/proc.c:200 +0xbb fp=0x7fa56f709c28 sp=0x7fa56f709c00
Jul 28 16:05:00 dell-r510-02 docker: runtime.allocm(0xc208010000, 0xc208000360)
Jul 28 16:05:00 dell-r510-02 docker: /usr/lib/golang/src/runtime/proc.c:901 +0x72 fp=0x7fa56f709c48 sp=0x7fa56f709c28
Jul 28 16:05:00 dell-r510-02 docker: newm(0x0, 0xc208010000)
Jul 28 16:05:00 dell-r510-02 docker: /usr/lib/golang/src/runtime/proc.c:1142 +0x28 fp=0x7fa56f709c80 sp=0x7fa56f709c48
Jul 28 16:05:00 dell-r510-02 docker: startm(0xc208010000, 0x442900)
Jul 28 16:05:00 dell-r510-02 docker: /usr/lib/golang/src/runtime/proc.c:1220 +0xd0 fp=0x7fa56f709cb0 sp=0x7fa56f709c80
Jul 28 16:05:00 dell-r510-02 docker: handoffp(0xc208010000)
Jul 28 16:05:00 dell-r510-02 docker: /usr/lib/golang/src/runtime/proc.c:1238 +0x1f9 fp=0x7fa56f709cd0 sp=0x7fa56f709cb0
Jul 28 16:05:00 dell-r510-02 docker: retake(0x22d6dcacb99e7, 0x0)
Jul 28 16:05:00 dell-r510-02 docker: /usr/lib/golang/src/runtime/proc.c:3007 +0x142 fp=0x7fa56f709d18 sp=0x7fa56f709cd0
Jul 28 16:05:00 dell-r510-02 docker: sysmon()
Jul 28 16:05:00 dell-r510-02 docker: /usr/lib/golang/src/runtime/proc.c:2930 +0x20c fp=0x7fa56f709da0 sp=0x7fa56f709d18
Jul 28 16:05:00 dell-r510-02 docker: mstart()
Jul 28 16:05:00 dell-r510-02 docker: /usr/lib/golang/src/runtime/proc.c:859 +0xe1 fp=0x7fa56f709db0 sp=0x7fa56f709da0
Jul 28 16:05:00 dell-r510-02 docker: runtime.mstart()
Jul 28 16:05:00 dell-r510-02 docker: /usr/lib/golang/src/runtime/proc.c:836 +0xa4 fp=0x7fa56f709dc8 sp=0x7fa56f709db0
Jul 28 16:05:00 dell-r510-02 docker: goroutine 1 [chan receive, 292 minutes]:
Jul 28 16:05:00 dell-r510-02 docker: runtime.gopark(0x43fec0, 0xc208030cb8, 0xca3af0, 0xc)
Jul 28 16:05:00 dell-r510-02 docker: /usr/lib/golang/src/runtime/proc.go:130 +0x105 fp=0xc2082637b0 sp=0xc208263780
Jul 28 16:05:00 dell-r510-02 docker: runtime.goparkunlock(0xc208030cb8, 0xca3af0, 0xc)
Jul 28 16:05:00 dell-r510-02 docker: /usr/lib/golang/src/runtime/proc.go:136 +0x48 fp=0xc2082637d8 sp=0xc2082637b0
Jul 28 16:05:00 dell-r510-02 docker: runtime.chanrecv(0xa3a080, 0xc208030c60, 0xc208263a98, 0xc208030101, 0xc209100000)
Jul 28 16:05:00 dell-r510-02 docker: /usr/lib/golang/src/runtime/chan.go:410 +0x452 fp=0xc208263878 sp=0xc2082637d8
Jul 28 16:05:00 dell-r510-02 docker: runtime.chanrecv1(0xa3a080, 0xc208030c60, 0xc208263a98)
Jul 28 16:05:00 dell-r510-02 docker: /usr/lib/golang/src/runtime/chan.go:311 +0x2b fp=0xc2082638a8 sp=0xc208263878
Jul 28 16:05:00 dell-r510-02 docker: main.mainDaemon()
Jul 28 16:05:00 dell-r510-02 docker: /builddir/build/BUILD/docker-4740812f06d1d63d6c9e62ade9611f9172c057e9/docker/daemon.go:198 +0x16fa fp=0xc208263b88 sp
```

**Comment by vbatts** [comment]
@jeremyeder this is on golang 1.4.2?

**Comment by jeremyeder** [comment]
This is using docker-1.7.1-108; which I do believe was compiled with 1.4.2-ish.

**Comment by vitzx** [comment]
Hello,
I observe the same issue on: Docker version 1.9.0-dev, build 7001619, experimental

The docker daemon crashes on reaching 2500 containers. Could you please share an update on this? Will there be an option for tuning the MaxThreads limit?

Thank you.

**Comment by MarcoLotz** [comment]
Hi all. That's a GoLand standard limitation for threads
 
There's two ways to solve that:
1) recompile goland modifying proc.go (or proc1.go in 1.5go) line to 
sched.maxmcount = 100000

2) recompile your docker engine to make the following call on the start:
``import "runtime/debug"
debug.SetMaxStack(100000)``

**Comment by kuldeepsinh-3990** [comment]
Hi 
I am receiving following error from docker when i try to launch more than 700 containers. 
using docker 1.9.0
I am using mesos(0.25.0)+marathon(0.14.0) for bulk deployment.

there is no limit issue as no. of process and max-threads are high. not a RAM exhaustion.

What is the issue here?

runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0xf34319

goroutine 0 [idle]:

goroutine 1 [chan receive, 9 minutes]:
main.(*DaemonCli).CmdDaemon(0xc2084f5210, 0xc20800a010, 0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/docker/docker/docker/daemon.go:308 +0x20a7
reflect.callMethod(0xc2084d5f80, 0xc209a1bce8)
    /usr/local/go/src/reflect/value.go:605 +0x179
reflect.methodValueCall(0xc20800a010, 0x0, 0x0, 0x1, 0xc2084d5f80, 0x0, 0x0, 0xc2084d5f80, 0xc2084f5320, 0x4dcb9f, ...)
    /usr/local/go/src/reflect/asm_amd64.s:29 +0x36
github.com/docker/docker/cli.(*Cli).Run(0xc2084d5ec0, 0xc20800a010, 0x1, 0x1, 0x0, 0x0)
    /go/src/github.com/docker/docker/cli/cli.go:89 +0x38e
main.main()
    /go/src/github.com/docker/docker/docker/docker.go:65 +0x418

goroutine 5 [syscall, 11 minutes]:
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
    /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, 11 minutes, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 11 [IO wait]:
net.(*pollDesc).Wait(0xc208079330, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208079330, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2080792d0, 0x0, 0x7f14c1f42500, 0xc215fba0b0)
    /usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*UnixListener).AcceptUnix(0xc20850a040, 0xc215027fa0, 0x0, 0x0)
    /usr/local/go/src/net/unixsock_posix.go:282 +0x56
net.(*UnixListener).Accept(0xc20850a040, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/unixsock_posix.go:293 +0x4c
github.com/docker/docker/pkg/listenbuffer.(*defaultListener).Accept(0xc20850a060, 0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/docker/docker/pkg/listenbuffer/buffer.go:71 +0x67
net/http.(*Server).Serve(0xc208042720, 0x7f14c0559458, 0xc20850a060, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:1728 +0x92
github.com/docker/docker/api/server.(*HTTPServer).Serve(0xc20850a220, 0x0, 0x0)
    /go/src/github.com/docker/docker/api/server/server.go:113 +0x4d
github.com/docker/docker/api/server.func·006(0xc20850a220)

**Comment by morphyno** [comment]
I'm running on docker on Ubuntu 16.04 (installed from repositories). It seems golang or gccgo packages are not installed apart of docker-engine installation (i'm assuming its just running pre-build binaries) somewhere? I would like to modify the "SetMaxStack" limit imposed by golang, do I have to install golang from source? Would docker automatically pick up the installed gccgo afterwards or should I install that from source as well?

**Comment by cpuguy83** [comment]
Closing since we now set max threads to 90% of the max threads allowed by the kernel.
