### ISSUE TITLE
ACLs do not work inside containers

### ISSUE THREAD

**Issue by alexkamp** [docker/docker#15251]
hey, 

I run the following script: 

    #!/bin/bash
    
    getfacl .
    
    setfacl -d -m u::rwx,g::rwx,o::rwx .
    setfacl -m u::rwx,g::rwx,o::rwx .
    
    getfacl .
    
    mkdir test
    
    ls -al

On Linux Fedora, installed on bare metal with ext4 as file system, I get: 

    # file: .
    # owner: me
    # group: me
    user::rwx
    group::rwx
    other::rwx
    
    # file: .
    # owner: me
    # group: me
    user::rwx
    group::rwx
    other::rwx
    default:user::rwx
    default:group::rwx
    default:other::rwx
    
    total 24
    drwxrwxrwx+  3 me me 4096 Aug  3 14:19 .
    drwxrwxr-x. 19 me me 4096 Aug  3 14:10 ..
    -rw-rw-r--.  1 me me  126 Aug  3 14:18 full.sh
    drwxrwxrwx+  2 me me 4096 Aug  3 14:19 test

With a Fedora base image on boot2docker, MacOS X as a base system, I get: 

    # file: .
    # owner: root
    # group: root
    user::rwx
    group::rwx
    other::rwx
    
    # file: .
    # owner: root
    # group: root
    user::rwx
    group::rwx
    other::rwx
    default:user::rwx
    default:group::rwx
    default:other::rwx
    
    total 24
    drwxrwxrwx+  3 root root 4096 Aug  3 14:19 .
    drwxrwxr-x. 19 root root 4096 Aug  3 14:10 ..
    -rwxrwxrwx.  1 root root  126 Aug  3 14:18 full.sh
    drwxr-xr-x+  2 root root 4096 Aug  3 14:19 test

Mind the difference in access rights on test, as reported by ls. It seems that Access Control Lists do not work here. 

boot2docker uses AUFS, I observed the same with OverlayFS and a Fedora host system. It does work with device mapper and a fedora host. Is this a file system bug, e.g. a bug in AUFS/OverlayFS or is it a docker bug?

**Comment by cpuguy83** [comment]
I don't believe AUFS supports ACLs... I would be surprised if overlayfs supported them.

**Comment by thaJeztah** [comment]
Yeah, not sure about overlayfs, but I don't think AUFS supports this; https://github.com/docker/docker/issues/1070#issuecomment-20624664 and https://github.com/docker/docker/issues/1070#issuecomment-22206125

**Comment by thaJeztah** [comment]
@alexkamp I'm going to close this issue, because I don't think there's anything Docker can do here, but feel free to comment here after I've closed this :+1:

**Comment by nathancarter** [comment]
Just to be sure I understand here:  If I'm running Docker for Mac, does this mean I can't use, inside a container, any software that relies on ACLs?  That seems like the upshot of this conversation, and a pretty significant restriction.  Do I understand correctly?
