### ISSUE TITLE
Mixed content warning on https://blog.docker.com and doesn't enforce secure connection

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#15250]
(This issue is reported in the wrong repository, but no public tracker is available for the blog)

While checking links for https://github.com/docker/docker/pull/15248, I noticed that visiting the Docker blog over https (https://blog.docker.com) results in "mixed content warnings", because some content is loaded from non-secure URLs. These links should be changed to consistently use https://

In addition, http://blog.docker.com/ is *not* automatically redirected to the secure domain.

![mixed-content-warning](https://cloud.githubusercontent.com/assets/1804568/9035701/9ef54ff8-39da-11e5-9467-a7788f7406b8.jpg)

**Comment by moxiegirl** [comment]
@thaJeztah I'll also forward this to Marketing. They own blogs.

**Comment by thaJeztah** [comment]
@moxiegirl thanks! feel free to close this one whenever you want

**Comment by moxiegirl** [comment]
@thaJeztah Forwarded to the appropriate team.

**Comment by LK4D4** [comment]
@thaJeztah was this fixed?

**Comment by thaJeztah** [comment]
Looks like a redirect is now in place, so I'll close this
