### ISSUE TITLE
missing Content-Length in registry response causes parse error

### ISSUE THREAD

**Issue by mhrivnak** [docker/docker#15264]
If during a ``docker pull`` operation the registry response to a blob GET request either does not have the ``Content-Length`` header, or if the value of that header is incorrect (in which case the golang client code silently removes it from the Response struct), a parsing error will occur when ``strconv.ParseInt`` gets called.

https://github.com/docker/docker/blob/v1.7.1/registry/session_v2.go#L223

This was tested with 1.7.1.

A patch is forthcoming to fix this.

**Comment by mhrivnak** [comment]
It looks like this may no longer be an issue on master. It's hard to tell since the entire ``session_v2.go`` code seems to be gone. This patch definitely fixes the issue on 1.7.1: https://github.com/mhrivnak/docker/commit/4987e320ded79480df9237c39984bbd0767bd677

It would be helpful if someone with more knowledge of the same workflow on master could verify if this is still a problem or not.

**Comment by dmp42** [comment]
cc @docker/distribution-maintainers

**Comment by calavera** [comment]
This was solved in master in this commit:

https://github.com/docker/docker/commit/19515a7ad859b28c474d81e756ac245afcd968e3#diff-7e2a216082b6bd557c7ecebd68305e2eR155

Thanks for the report. It will be fixed in 1.8 :tada:

**Comment by rvillars** [comment]
Are you really sure this is fixed with 1.8? I got exactly the same error with docker 1.8.1. Here the log of the daemon:

```text
DEBU[0075] pulling blob "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" to bc8e9a27c6065f7fe966429fe859d1c6891e5ae58268d00287ef57018155d9cd 
DEBU[0075] Error statting layer: error parsing content-length: strconv.ParseInt: parsing "": invalid syntax 
DEBU[0075] Error trying v2 registry: error parsing content-length: strconv.ParseInt: parsing "": invalid syntax 
DEBU[0075] Trying to pull repo-docker.edorasware.com/edorasware/edorasbookapp from https://repo-docker.edorasware.com v1 
ERRO[0075] error copying from layer download progress reader: download canceled
```

**Comment by dohnto** [comment]
I don't know if this is related but I am trying to get to work swift backend storage. When I try to push an image to my repository, i get:

```bash
$ docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:29:38 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:29:38 UTC 2015
 OS/Arch:      linux/amd64

$ docker push registry:11111/test
The push refers to a repository [registry/test] (len: 1)
e9ae3c220b23: Image already exists 
a6785352b25c: Pushed 
0998bf8fb9e9: Pushed 
0a85502c06c9: Pushing 196.8 MB
error parsing content-length: strconv.ParseInt: parsing "": invalid syntax```

If I use filesystem backend, the push finish just fine.

**Comment by thaJeztah** [comment]
@dohnto I think it's better to report that issue, or search for existing issues in the distribution (https://github.com/docker/distribution/issues) repository

**Comment by firelyu** [comment]
I meet the same issue with `oss` backend.  The registry is `registry:2.2.1`. 
The `oss` support the redirect and I disable the `redirect` in  the config.yml.
```
storage:
    redirect:
        disable: true
    oss:
        accesskeyid: xxxxx
        accesskeysecret: yyyyyy
        region: oss-cn-hangzhou
        bucket: registry1
```
The push fails.
```
# docker push myregistry:5000/swarm:latest
The push refers to a repository [myregistry:5000/swarm] (len: 1)
a9975e2cc0a3: Pushing 1.024 kB
error parsing content-length: strconv.ParseInt: parsing "": invalid syntax
```
