### ISSUE TITLE
Fixed-cidr option without 'bip' now fails, but worked in 1.7

### ISSUE THREAD

**Issue by ewindisch** [docker/docker#15268]
In testing 1.8, I have found that --fixed-cidr now causes the daemon to exit and fail to start.

Similar to #11336, but may be a separate issue. This occurs even if I first perform a 'brctl delbr docker0'.

Experienced behavior:
--------------------------------

```
$ docker daemon --fixed-cidr 172.17.252.0/22
...
FATA[0001] Error starting daemon: Error initializing network controller: Error creating default "bridge" network: setup FixedCIDRv4 failed for subnet 172.17.252.0/22 in 172.17.42.1/24: network does not contain specified subnet
```

Expected behavior
----------------------------
- Use of specified cidr when specifying 'docker daemon --fixed-cidr'

**Comment by aboch** [comment]
@ewindisch the container subnet you are specifying does not belong to the bridge subnet (of existing docker0 running).
Error is expected.

**Comment by ewindisch** [comment]
@aboch this happens even if docker0 does not exist. It happens upon a fresh reboot. This is a machine that had been using this cidr successfully with 1.7.2 before upgrading to the latest master.

**Comment by aboch** [comment]
Yes, it is expected.
In case docker0 does not exist, docker creates it for you and assign it an IP from a statically coded list on networks. Most likely will get the first one which is 172.17.42.1/24.

To achieve what you are trying to do, besides first removing the existing docker0, you need to pass to daemon the bridge network of your choice with `--bip 172.17.0.254/16` along with the container network `FixedCIDR=172.17.252.0/22`

**Comment by ewindisch** [comment]
aboch: that sounds perfectly acceptable except it breaks existing configurations. The current behavior does not match 1.7.2 and will result in some users not knowing they need to set --bip.

**Comment by ewindisch** [comment]
Indicating that --bip may need to be set and docker0 destroyed would be a better UX than providing a relatively obscure error regarding a seemingly random IP address.

Perhaps unrelated but falling back to and automatically assigning 172.17.42.1 could be dangerous for usrs if this machine is redistributing routes via OSPF or BGP. Again, it's not something users expect.

**Comment by aboch** [comment]
@ewindisch I agree the way docker self assigns a bridge network is very handy (and we have not changed that), but also that we should not assume that docker0 network will always be the same at each docker daemon boot.

In 1.8.0, as before, the first network picked for bridge0 should be `172.17.42.1/16` and no issues should have happened with the FixedCIDR you specified. We need to see from where that `/24` came from.

Will get back to you if I can't reproduce.

**Comment by aboch** [comment]
@ewindisch Thanks for reporting this issue. I see where the bug is (causing bridge network to be a `/24`).

**Comment by mavenugo** [comment]
@ewindisch #15276 will resolve this issue. But, it is not a good idea to depend on the assumption that the docker0 bridge will use the 172.17.x.x/16 network. Especially after we add the IPAM plugin where we will let the IP Address management be handled by an external plugin.
#15276 simply brings the existing behavior back.

**Comment by ewindisch** [comment]
@mavenugo thank you. No, I didn't (intentionally) assume that docker0 was using 172.17.x.x/16. I had thought it was only using the /22 I was giving it. At least part of this is a UX problem, I suspect. It's also a machine I had configured a long time ago and never really reevaluated the configuration until it broke.
