### ISSUE TITLE
Add instructions how to register a nick on IRC

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#15267]
Following repeated abusive visitors on the #docker-dev IRC channel, we might soon switch this channel to be open only for people that have registered a nick, just as currently is done for the #docker IRC channel. (See the [logged discussion on botbot.me](https://botbot.me/freenode/docker-maintainers/2015-08-03/?msg=46293182&page=2)

Not all users know how to do so, and we don't want to lock out people that want to start developing on, or contributing to docker, so we should add some pointers to the documentation to assist those users. (For example, https://freenode.net/faq.shtml#nicksetup)

**Comment by thaJeztah** [comment]
I added this as a "todo" to add links to appropriate locations in the docs, but suggestions are welcome :-)

**Comment by shishir-a412ed** [comment]
@thaJeztah If someone is planning to contribute to a huge codebase such as docker.
I feel they should be able to figure out how to register and identify a nick on irc :)

**Comment by thaJeztah** [comment]
@shishir-a412ed we all have to start somewhere, and some contributors begin with simple typo fixes. Especially those contributors may need assistance with their contributions (sign off, rebase, etc).

Sure, they should be able to find it, but we should not make it too difficult, after all, we want to *attract* new contributors, not steer them away ;-)

**Comment by thaJeztah** [comment]
Closing as this is described on the [Where to chat or get help page](https://github.com/docker/docker/blob/8855bf350026a27a6615fa057d176b28715d77d5/docs/project/get-help.md), and improved by the recent work of @mikebrow (https://github.com/docker/docker/pull/16023)
