### ISSUE TITLE
RFE: The ability to build custom roots from within Dockerfile

### ISSUE THREAD

**Issue by muayyad-alsadi** [docker/docker#15271]
in many cases people use scripts to build their images from scratch for example when they build [busybox images](https://github.com/fedora-cloud/Fedora-Dockerfiles/blob/master/busybox/makeimage.sh) or when the build environment is so complex but the result is so simple (ex. a golang project needs compiler ..etc. but all you need is the resulted binary)

I believe it would be great if we add a `Dockerfile` instruction like this
```
SWITCH_ROOT <other_image> <new_root>...
```

typically `other_image` would be an empty image `scratch` or a small image like `busybox` and `new_root` would be a directory in the parent image

this way we can make almost all docker images to support Dockerfile-based automated builds and eliminate the need for scripted builds.

The [fedora busybox](https://github.com/fedora-cloud/Fedora-Dockerfiles/blob/master/busybox/makeimage.sh) would be something like this:

```
FROM fedora
RUN mkdir -p /dest/sbin/ /dest/bin/ && \
         yum install -y busybox && \
         cp /sbin/busybox /dest/sbin/ && \
         for i in $( /dest/sbin/busybox --list ); do ln /sbin/busybox /dest/bin/$i; done
SWITCH_ROOT scratch dest
CMD /bin/sh
```

and a `golang` application with busybox would be like this

```
FROM golang
ADD myapp /usr/src/myapp
RUN mkdir /dest && .... & cp /usr/src/myapp/myapp /dest/
SWITCH_ROOT busybox dest
CMD /myapp
```

the proposed switch root would reset all docker meta data to be the same as the `other_image` except maintainer.

**Comment by muayyad-alsadi** [comment]
@GordonTheTurtle although I know it might be an automated bot. I'm not reporting a bug. this is RFE (request for enhancement) that suggest a new instruction in the docker file.

**Comment by calavera** [comment]
Hi @muayyad-alsadi. Sorry, but we don't accept new keywords in dockerfiles for now. There is more information about this reasoning in our roadmap:

https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

**Comment by muayyad-alsadi** [comment]
> A standalone Builder will also offer the opportunity for a better
*dedicated group* of maintainers to own the Dockerfile syntax and decide
collectively on the direction to give it.

How can I reach that group and project?

> Our experience with official images tend ...

I believe that official images for busybox use from scratch and some script
outside docker. This would no longer be necessary and no script on host
machine would be needed at all. This is not about syntax sugar. It's a new
level of functionality that was impossible and was done by relaying on the
host os but now be done inside docker regardless of host (ex. Build fedora
busybox on Ubuntu host)

**Comment by phemmer** [comment]
Also, this looks like it's meant to accomplish the same end goal as #332, which was closed because nobody could agree on anything.

**Comment by muayyad-alsadi** [comment]
Although this can be used to produce flat images. This is not the main
purpose. The reason behind this idea is to eliminate dependency on specific
host os for building some images. Not all images are autobuild because they
involve running a script on host os.

The main value of docker is to provide a universal runtime so that
application can be shipped anywhere. But they can't be built anywhere if
build depend on specific host os (specific tool or version on host os that
builds the root from scratch).

With this proposal we have the host os or build toolchain needed to build
the target image inside docker then we switch root to the target root. This
way anything can be made to be automated reproducible builds no matter what
is the host os.

**Comment by muayyad-alsadi** [comment]
this [docker file](https://registry.hub.docker.com/u/progrium/busybox/dockerfile/) 70,000 pulls involves some bootstrapping that was done on some random host OS. 

```
FROM       scratch
ADD ./rootfs.tar /
```

but with my proposal the actual builing of rootfs would be built in a well-known env. set by dockerfile and the actual building of the binaries would happen inside the dockerfile.


another example is `etcd` a 4MB binary in this [dockerfile (https://registry.hub.docker.com/u/elcolio/etcd/dockerfile/) instead of being built by docker, it was pulled from random tarball (which was built on some random host os)

```
ADD https://github.com/coreos/etcd/releases/download/v2.0.9/etcd-v2.0.9-linux-amd64.tar.gz etcd-v2.0.9-linux-amd64.tar.gz
```

and in [this example](https://registry.hub.docker.com/u/nuagebec/etcd/dockerfile/) the 4MB binary become loaded with hundreds of MB of ubuntu and golang compiler

**Comment by thaJeztah** [comment]
I think this is similar to https://github.com/docker/docker/issues/7115

Pending the "spinning out" of the builder (https://github.com/docker/docker/issues/14298), it's not fully determined which direction the Dockerfile syntax will go; keep it as-is (and allow third-parties to develop their own builders/syntax), or add more features (*and* allow third-party builders).

The discussion on this hasn't really started yet, but it's best to follow https://github.com/docker/docker/issues/7115 to keep informed.
