### ISSUE TITLE
does not build with Go 1.5 tip

### ISSUE THREAD

**Issue by mwhudson** [docker/docker#15279]
```shellsession
---> Making bundle: dynbinary (in bundles/1.8.0-dev/dynbinary)
Created binary: bundles/1.8.0-dev/dynbinary/dockerinit-1.8.0-dev
Building: bundles/1.8.0-dev/dynbinary/docker-1.8.0-dev
# github.com/docker/docker/pkg/devicemapper
.gopath/src/github.com/docker/docker/pkg/devicemapper/devmapper_wrapper.go:191: Cdeps.device undefined (type *C.struct_dm_deps has no field or method device)
```

This is the fault of https://github.com/golang/go/commit/7904946eeb35faece61bbf6f5b3cc8be2f519c17, which is one of those "well, someone has to be broken" fixes.

**Comment by vbatts** [comment]
ugly. Now this C struct
```C
struct dm_deps {
        uint32_t count;
        uint32_t filler;
        uint64_t device[0];
};
```
doesn't appear to have a `device` field through cgo.

**Comment by LK4D4** [comment]
@vbatts Maybe we should ask Ian Lance Taylor what should we do now. Such structures are super-popular in C.

**Comment by vbatts** [comment]
https://gist.github.com/vbatts/fddc81848e510b9c56de for simple reference.

**Comment by tiborvass** [comment]
@vbatts golang/go@7904946eeb35faece61bbf6f5b3cc8be2f519c17 is the issue.

**Comment by LK4D4** [comment]
I started some discuss in golang/go#11925. Seems like only way is to get pointer to field and cast to slice.

**Comment by mwhudson** [comment]
I think this can be closed now, reopen if I've misunderstood process :-)

**Comment by seblu** [comment]
I still have this issue when building docker (1.8.2) on Archlinux with golan 1.5.1.

**Comment by unclejack** [comment]
@seblu The Docker project doesn't support building Docker 1.8.2 with Golang 1.5.x and this will never change as it's not a bug. Existing releases are never modified to support new versions of Go.

Building with Go 1.5.x wil only be supported after releasing a Docker version which includes #15703 (or an equivalent PR).
