### ISSUE TITLE
Double ipv4 forward check

### ISSUE THREAD

**Issue by runcom** [docker/docker#15286]
step to repro (my host is fedora 22) on latest master:
```
make
echo 0 > /proc/sys/net/ipv4/ip_forward
./bundles/1.8.0-dev/binary/docker-1.8.0-dev daemon -D -s overlay --ip-forward=false
docker run busybox true

WARNING: IPv4 forwarding is disabled. Networking will not work.
WARNING: IPv4 forwarding is disabled.
```
two warnings are printed. The second one is also checking is `--networking` is true (the opt is deprecated also) but it's redunant I think.
I'm taking care of this one in my other PR about sysinfo #15275

**Comment by coolljt0725** [comment]
#14665 has a commit to fix this

**Comment by calavera** [comment]
I'd really :heart: if we could have an isolated patch for this, rather than shoving it into other PRs. It seems like it could be merged easily.

**Comment by coolljt0725** [comment]
I send separate PR #15354  to solve this.

**Comment by runcom** [comment]
Perfect thanks, I'll remove the patch in my other PR
