### ISSUE TITLE
Specify container IP address at startup

### ISSUE THREAD

**Issue by candlerb** [docker/docker#15289]
(Extracted from #11336)

At the moment, `docker run` and `docker start` automatically pick an IP address from the allocator, which may be constrained to a specific pool using `--fixed-cidr`

It would be convenient to be able to choose an IP address for a container explicitly, e.g. to tie up with pre-defined DNS.

The chosen address could still be checked with the IP allocator, and rejected if already in use. (This would be consistent with the `--name` option, which rejects duplicate container names).

Design options: the chosen address may or may not persist with the container.

* If it persisted, then `docker start` would automatically re-use the same address. However this implies that the IP allocator would have to take note of all reserved IP addresses at startup time (even for stopped containers).

* Alternatively, if it is not persisted, then the user would have to pass the option again to `docker start` when re-starting the container; if not, they would get a new random IP address.

I would expect the second option would be a simpler and less invasive change.

Either option is acceptable for my use case, which is lightweight VMs for a training lab. The exercises have all been documented and configured assuming a particular mapping of hosts to IP addresses and DNS names. Since they are in the DNS, I could do `docker start host1 --address host1` and host1 would resolve to the right address anyway.

**Comment by phemmer** [comment]
I think this is a dup of #6743

**Comment by candlerb** [comment]
OK, I'll accept that.  I wish github made it easier to search for issues :-(
