### ISSUE TITLE
Allow arbitrary start and end IP addresses for IP allocation

### ISSUE THREAD

**Issue by candlerb** [docker/docker#15287]
(Extracted from #11336)

At the moment you can configure the docker daemon with e.g. `--fixed-cidr=10.10.0.192/28`, and the allocator will allocate addresses within that range - in this case starting 10.10.0.193, probably ending 10.10.0.206 or 10.10.0.205 (untested)

It would be helpful to be able to specify arbitrary start and end IPs instead, e.g. `--fixed-range=10.10.0.100,10.10.0.199`

This would allow more flexibility in avoiding fixed infrastructure (e.g. routers, switches), other VMs, existing DHCP ranges etc.

**Comment by candlerb** [comment]
Looking at `vendor/src/github.com/docker/libnetwork/ipallocator/allocator.go`

`newAllocatedMap` already explodes a CIDR range into firstIP and lastIP, so it looks like it would be pretty simple to change it to take firstIP and lastIP as arguments instead; with a similar change to `RegisterSubnet` to become `RegisterRange`.

**Comment by cpuguy83** [comment]
I'd definitely be -1 on a new flag, especially given the on-going networking work.

**Comment by candlerb** [comment]
Well, how about same flag with alternate syntax: `--fixed-cidr=10.10.0.100,10.10.0.199`? But then the flag is misnamed.

A start-end range is what the allocator actually wants and uses internally. If the flag had been `--fixed-range` to begin with then all use cases would be covered.

`--fixed-cidr` could be kept for backwards compatibility, auto-expanding to the first+1 and last-1 addresses.

On-going networking work seems to me like an ideal opportunity to sort this, particularly if any APIs are about to be baked.

**Comment by cpuguy83** [comment]
See https://github.com/docker/docker/blob/master/experimental/networking.md re: networking

**Comment by aboch** [comment]
@candlerb If the docker fixedcidr flag change is accepted, then please open the container IP address range request in [libnetwork](https://github.com/docker/libnetwork). With few small changes, the new ipam can accomodate this feature.

**Comment by cpuguy83** [comment]
Yeah, we can deprecate the current flag name and give it a new one.

**Comment by candlerb** [comment]
Raised in libnetwork as https://github.com/docker/libnetwork/issues/437

By implementing RegisterRange whilst retaining RegisterSubnet then I believe the transition should be straightforward.

**Comment by LK4D4** [comment]
There is --ip-range flag now. Going to close this. Feel free to open new issue if I was wrong.

**Comment by candlerb** [comment]
> There is --ip-range flag now. Going to close this.

Where is this flag? I cannot find it documented [here](https://docs.docker.com/engine/reference/commandline/dockerd/) or [here](https://docs.docker.com/engine/userguide/networking/default_network/custom-docker0/)

**Comment by candlerb** [comment]
Ah, it turns out `--ip-range` is option to [docker network create](https://docs.docker.com/engine/reference/commandline/network_create/#options), not `dockerd`.
