### ISSUE TITLE
docker installation script does not support Mint

### ISSUE THREAD

**Issue by lerignoux** [docker/docker#15293]
Description of problem:
On a linux Mint It is impossible to install docker using the Ubuntu script (```curl -sSL https://get.docker.com/ | sh```) though the distribution is based on it.

`docker version`: 1.8.0-dev

`docker info`: None

`uname -a`: 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
A clean Mint Rafaela installation.

How reproducible:
Easy, 100%
- Download the latest Mint image: http://www.linuxmint.com/download.php
- Install it.
- It will fail saying it is unable to find the distribution version

Steps to Reproduce:
1. wget http://mirror.karneval.cz/pub/linux/linuxmint/iso//stable/17.2/linuxmint-17.2-cinnamon-64bit.iso
2. burn image on key or launch it in a virtualbox
3. in the newly installed machine: ```curl -sSL https://get.docker.com/ | sh```

Actual Results:
fails with an error
```
Either your platform is not easily detectable, is not supported by this
installer script (yet - PRs welcome! [hack/install.sh]), or does not yet have
a package for Docker.  Please visit the following URL for more detailed
installation instructions:

https://docs.docker.com/en/latest/installation/
```

Expected Results:
should install the correct docker version corresponding to mint base Ubuntu version

Additional info:

**Comment by lerignoux** [comment]
#dibs

**Comment by lerignoux** [comment]
linked PR: https://github.com/docker/docker/pull/15294

**Comment by vdemeester** [comment]
Hi @lerignoux,

Thanks for reporting and sending a PR. there is a work on this though, in this PR : #15001 :wink:.

**Comment by thaJeztah** [comment]
I'm going to close this issue; this will be covered by #15001. Thanks though!!
