### ISSUE TITLE
Docker documentation readme not up to date. There is no md list yml anymore

### ISSUE THREAD

**Issue by lerignoux** [docker/docker#15296]
Description of problem:
in documentation README, when adding a new md file it is required to update the relevant docs/mkdocs.yml

`docker version`: 1.8.0-dev

`docker info`: None

`uname -a`: 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
Main system, Mint rafaela up to date.

How reproducible:
README not up to date Easy, 100%

Steps to Reproduce:
1. read the README
2. Add a new .md file in docker/docs/*
3. make docs
4. your doc appears without anything else

Actual Results:
line 66 is wrong. it is said that when adding a new .md file docs/mkdocs.yml must be updated as well.

Expected Results:
this appear to be deprecated.
You just need to add the .md file for it to be taken into account.

**Comment by lerignoux** [comment]
#dibs

**Comment by vdemeester** [comment]
I guess it has been fixed by #15297, should be close :wink:

**Comment by thaJeztah** [comment]
yup, thanks both!

@lerignoux for future PRs; if you add `fixes #xxx` in the description of your pull request, Github automatically closes that issue when the PR is merged :smile:
