### ISSUE TITLE
Proposal: Migrate Containers from one storage to another.

### ISSUE THREAD

**Issue by shishir-a412ed** [docker/docker#15299]
Problem: 
We have users who are running docker (Production environment), using lvm devmapper on top of loopback devices. Since this storage option is not production ready, we recommend them to switch to a different storage. Being a production environment they don't want to loose their containers when migrating from one storage to another.

Currently they can achieve this using docker export/import. However there are some shortcomings with these commands.
Let's take an example.

1) I have my source docker (devmapper running on loopback devices) running with 1 image {fedora}.
2) I start a container on this image: docker run --name fedora_container -it fedora /bin/bash
3) I make some changes in the container: echo foobar > /home/foobar.txt
4) I stop the container and I want to migrate my images {fedora} and containers {fedora_container} to the new storage.

Current setup:

1) docker save fedora > fedora.tar
2) docker export -o fedora_container.tar fedora_container [This will tar up the container rootfs including the changes {foobar.txt} we made]
3) Switch to the new storage.
4) docker load < fedora.tar
5) cat fedora_container.tar | docker import - fedora_new:latest
6) Now I can start a container which will have my changes {foobar.txt} on this new image, fedora_new:latest

Shortcomings:

1) The container on the new storage is based on image {fedora_new} eventhough the original container was based on image {fedora}.
2) The image fedora_new is a completely standalone image which is not based on any image.
    docker inspect -f {{.Parent}} fedora_new = ""
3) Any metadata associated with the containers e.g Mount points is lost, since the container is recreated at the new storage.
4) Docker import results into an image (not container). This means if a user is trying to migrate X images and Y Containers.
   At the new storage he will see X+Y Images, and then he has to start all the containers again on these new images.
5) Since docker export tars up the entire rootfs, the tarball is heavy (In our example, we just created one file {foobar.txt} and the tar ball is ~200MB)

Proposal:

1) docker export with a new flag (--diff-metadata) will create a tarball with only the diff and metadata of the container. {~ 17 Kb in size}
2) docker import will:
        a) createRootfs on the new storage.
        b) Apply diff.
        c) setup metadata.
        d) load the container in the daemon.

After the import the user will see exact replica of `docker images` and `docker ps -a` in the new storage.

I have a working version of this proposal on my github branch.
https://github.com/shishir-a412ed/docker/tree/migrate_containers

How to:
EXPORT: docker export -o fedora_container.tar --diff-metadata fedora_container
IMPORT: cat fedora_container.tar|docker import --diff-metadata -

I am opening this proposal so that we can discuss how to best approach this problem. 
You can also take a look at my implementation, and if you like that approach I can open a PR and we can take it there.

**Comment by shishir-a412ed** [comment]
ping @tiborvass @crosbymichael @LK4D4

**Comment by duglin** [comment]
would the live-migration stuff that was demoed at DockerCon help with this?

**Comment by rhvgoyal** [comment]
docker commit will create an image and will not have container metadata. IOW, I can't use that image to recreate container as it. I need to know container parameters which were passed during creation. Also new container will have different ID.

**Comment by aidanhs** [comment]
Worth pointing out that this feature will do two things no other command does - 1) treat container metadata as something transferable and 2) partially export an image/container.

1. This is pretty radical and highly brittle - there's no guarantee some of the settings make sense on another host and there's no provided way to investigate what's wrong. Additionally, tightly tying the metadata and diff together makes this feature useless for anyone who wants just the diff - surely this should be two different calls.
2. Export and save take great care to avoid giving you something which might fail when taken back into Docker. This has caused me frustration in the past (due to a desire for individual layers) but plumbing is now promised to fill this need.

So, this could fail to load in two different ways - if the base image is not available and if the container settings are off-kilter. I'm not sure that saying "the user needs to deal with this themselves" is appropriate for high level commands - surely this feature should be decomposed into primitives which can then be added to plumbing for use by all rather than this niche use-case?

**Comment by shishir-a412ed** [comment]
@aidanhs 
This use case is more specific to moving from one storage to another. If you have read my complete proposal, users who are running docker in production with a slow storage (like devmapper on loopback) cannot just stop their production environments and start a fresh environment on new storage. They want to retain their containers, diff and metadata.

1) Host is same in this case. We can later discuss on how to extend this for different hosts. But for now it's more of a use-case for moving from one storage to another.
2) Images would be migrated first, so base images would be available to support the containers.

**Comment by aidanhs** [comment]
I accept that this is a need users have, but I'd prefer to look at it from a bottom up approach (i.e. api call to get a tarball of changed files on container, api call to get container metadata, api call to validate container metadata, api call to create a container from container metadata, api call to apply a tarball to a stopped container) rather than a top down approach (i.e. here is a feature to migrate between storage drivers).

Otherwise you've locked away all of these useful tiny components inside a big feature most users won't ever use, and those that do will use it very infrequently.

**Comment by rhvgoyal** [comment]
@aidanhs,

In general I like the idea of looking at individual components of this feature and see how these can be implemented so these are useful in more generic way.

I am not sure how tricky it would be to implement "validate new container metadata".  But in general, being able to export container metadata and being able to create a new container using that metadata makes sense. And once that is done, it is just a matter of applying diff layer.

**Comment by aidanhs** [comment]
Surely you have to validate the container metadata to implement this feature anyway (check available ports, check there are no lxc options if you're going onto a native driver, check there are no devicemapper storage options if moving onto aufs, no conflicting container IDs, etc etc)? Or would the plan just be to try and apply it and see if it works? In which case fair enough.

**Comment by rhatdan** [comment]
I think this feature is a little bigger then just what @shishir-a412ed suggested.  What we want to do is to save the configuration of one backend storage device.  Change the back end and then apply the content back on top.  

imagine a script

systemctl stop docker
docker-migrate -to /mnt/docker.lib
mv /var/lib/docker /var/lib/docker.old
Change back end configuration
docker-migrate --from /mnt/docker.lib
systemctl start docker

Then when overlayfs becomes stable you could migrate your docker content off of devicemapper or aufs and try out overlayfs.  If you find overlayfs does not work for you, you could migrate to something else.

Not really looking currently at moving cross nodes.

**Comment by thaJeztah** [comment]
@rhatdan in your example, the actual migration would be an external tool? Asking because I'm not sure the *actual* migration is something that should be in the main binary (it feels more suitable as an external tool)

**Comment by shishir-a412ed** [comment]
@thaJeztah Yes this would be an external tool. I had discussion with @rhvgoyal also on this.

If docker can accept these 4 API in the main binary (may or may not be exposed as docker CLI options, either way is good for us), we should be able to integrate it with our external tool.

1) Export container metadata.
2) Export container diff.
3) Import container metadata.
4) Import container diff: This API will first do a `createRootfs()` and then apply the diff from incoming tar ball.

**Comment by rhatdan** [comment]
As @shishir-a412ed says this would be an external tool.  Potentially a shell script or rolled into our atomic command.  Were figuring this would be a rare occurrence, but we need to support it.

**Comment by thaJeztah** [comment]
ping @tiborvass @icecrime @crosbymichael wdyt https://github.com/docker/docker/issues/15299#issuecomment-131403294?

**Comment by tiborvass** [comment]
I'm not exactly sure about this, however if we were to accept such a feature, I would recommend `docker export --diff` and `docker export --metadata` be separate (same for `import`). Not sure how this would help with the `fedora_new` issue.

**Comment by shishir-a412ed** [comment]
@tiborvass 

I have already broken this down into two separate options `--diff` and `--metadata` (both for docker export and import commands). You can see the changes in the PR #15895 .

However, if you want to try out the feature with the CLI, you can checkout my branch `migrate_containers`.

**Comment by tiborvass** [comment]
@shishir-a412ed oh my bad then, I just read your comments in the thread for now.

I wonder how the UX affects `docker commit` since you could redo `commit` with `import --diff` and `import --metadata`.

**Comment by shishir-a412ed** [comment]
@tiborvass yes you are right, a user can `redo commit`.

But the idea is If I am a docker user and I want to migrate my 200 images and 500 containers from one storage to another. I don't want to commit my 500 containers just to get them back at the target storage.

That would end up me having 700 images and 500 containers. Yes if I want to commit it, the option is always there. There are other concerns like size of the tarball (docker export) which is huge since we practically tar up the container entire rootfs right now.

**Comment by tiborvass** [comment]
Another thing we need to think about is how checkpoint/restore blends into this. I know it's slightly different because you only care about stopped containers but from a high-level, it makes sense to think about "moving containers" whether they are running or not.

cf #13602

**Comment by shishir-a412ed** [comment]
@tiborvass 

https://github.com/docker/docker/pull/15895#issuecomment-137564255.

@rhvgoyal @calavera Moving the discussion here. So everyone can follow.

**Comment by rhvgoyal** [comment]
@tiborvass 

Agreed that at high level we need to think about how to move containers. That will benefit our use case as well as checkpoint/restore.

Conceptually, I think once we have the capability to move a container, checkpoint/restore should be able to use moved container and restore it. And I think that should allow following.

- Checkpoint a container on one host.
- Migrate container on a different host.
- Restore the migrated container.

I am assuming that checkpoint/restore does not deal with container migration. It only saves process states and restores these and assumes that underlying filesystem has not changed.

I think it will be good if checkpoint/restore guys can comment on this. 

CC @boucher

**Comment by boucher** [comment]
This seems pretty cool, and I would love to integrate checkpoint/restore with the ability to natively migrate containers. Right now the goal for checkpoint/restore has been to ignore the migration use case until we can land an initial implementation (its still possible, but requires a lot of work). One simple use case for checkpoint/restore is restarting the daemon without losing your container state, for example.

The proposal of having separate export --metadata and export --diff seems a bit strange to me. Just, conceptually, to have a command that actually exports 3 completely different things (and two different types of data), depending on the flags. And there's some interest in not introducing a new "checkpoint" command, which may mean having yet another type of data that would be exported. 

It may also be helpful to read through some of the comments in #13602 to see what some other people have mentioned.

**Comment by thaJeztah** [comment]
> One simple use case for checkpoint/restore is restarting the daemon without losing your container state, for example.

Actually, never thought of that use case, that's actually very interesting!

**Comment by geota** [comment]
+1 This would be an awesome feature. I agree that the design should avoid coupling of the metadata export to the diff export.

**Comment by tholu** [comment]
+1

**Comment by LK4D4** [comment]
This is kinda old. @tonistiigi @thaJeztah any insights about this?

**Comment by thaJeztah** [comment]
Given that images are already distributable through a registry, and containers should not be considered "pets", I think this proposal introduces a lot of risks, that I'm not sure it's worth the effort.

**Comment by LK4D4** [comment]
@thaJeztah maybe we can close it then?

**Comment by thaJeztah** [comment]
I'm okay with closing this

**Comment by timchenxiaoyu** [comment]
the docker export --diff  only support docker1.12 or 1.12 over ?
