### ISSUE TITLE
git clone lvm2 failed

### ISSUE THREAD

**Issue by stefansaru** [docker/docker#15290]
Hi,

I'm getting the following while building the binary for release_v1.8.0:

RUN git clone -b v2_02_103 https://git.fedorahosted.org/git/lvm2.git /usr/local/lvm2
 ---> Running in 6f55e1d41fb9
Cloning into '/usr/local/lvm2'...
fatal: unable to access 'https://git.fedorahosted.org/git/lvm2.git/': gnutls_handshake() failed: A TLS packet with unexpected length was received.
The command '/bin/sh -c git clone -b v2_02_103 https://git.fedorahosted.org/git/lvm2.git /usr/local/lvm2' returned a non-zero code: 128
Makefile:74: recipe for target 'build' failed
make: *** [build] Error 1

Does anyone else experience an issue with the logical volume manager repository?

Thanks,
Stefan

**Comment by stefansaru** [comment]
Found a workaround by using wget instead of git clone, for getting lvm2, branch version 2.02.103 :

```bash
# Get lvm2 source for compiling statically
#RUN git clone -b v2_02_103 https://git.fedorahosted.org/git/lvm2.git /usr/local/lvm2
# see https://git.fedorahosted.org/cgit/lvm2.git/refs/tags for release tags

# Workaround using WGET
RUN mkdir -p /usr/local/lvm2
RUN wget https://git.fedorahosted.org/cgit/lvm2.git/snapshot/lvm2-2_02_103.zip -O /usr/local/lvm2/lvm2-2_02_103.zip
RUN apt-get install unzip
RUN unzip /usr/local/lvm2/lvm2-2_02_103.zip -d /usr/local/lvm2/
RUN mv /usr/local/lvm2/lvm2-2_02_103/* /usr/local/lvm2/
```

so far it seems to be working !

**Comment by cpuguy83** [comment]
Closing since this is also a question on docker-user ML and not likely a docker issue.
