### ISSUE TITLE
docker engine listening only on ipv6 wildcard address

### ISSUE THREAD

**Issue by doxxx** [docker/docker#15306]
I have a Centos 7 VM running in vSphere. I used docker-machine 0.4.0-rc2 to configure it as a docker host with the following command from a Windows 7 box:

    docker-machine create -d generic --generic-ip-address=10.4.117.137 torgtylervm1

That command never successfully completed because it could never contact the docker engine. When I ssh'd into the machine, I could see that docker was running:

     4406 ?        Ssl    0:00 /usr/bin/docker -d -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver devicemapper --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=generic

But when I checked listening ports, I noticed that port 2376 was only bound on a ipv6 wildcard address:

```
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN
tcp        0     64 10.4.117.137:22         10.4.114.103:45395      ESTABLISHED
tcp6       0      0 :::2376                 :::*                    LISTEN
tcp6       0      0 :::22                   :::*                    LISTEN
tcp6       0      0 ::1:25                  :::*                    LISTEN
```

Since the VM is only reachable via IPv4, this explains why docker-machine could not contact the docker engine.

`ifconfig` reports the following for the main network interface:

```
eno16777728: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.4.117.137  netmask 255.255.254.0  broadcast 10.4.117.255
        inet6 fe80::250:56ff:feb6:27f8  prefixlen 64  scopeid 0x20<link>
        ether 00:50:56:b6:27:f8  txqueuelen 1000  (Ethernet)
        RX packets 14030  bytes 8697003 (8.2 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 5810  bytes 791362 (772.8 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

As far as I know, the machine was not configured to use IPv6. We only use IPv4 on our local network and the VM template was created by one of network admins.

I tried disabling IPv6 at the system level, but Docker is *still* only binding to the IPv6 wildcard address. I have disabled the firewalld service and rebooted the system. Still no dice.

**Comment by thaJeztah** [comment]
@doxxx this sounds like a duplicate of https://github.com/docker/docker/issues/2174, could you check if I'm right?

**Comment by doxxx** [comment]
Kinda sorta? I'm not even trying to run any containers. I'm just trying to connect to the docker engine from another host. The docker engine in the VM is only listening on ":::2376" and not "0.0.0.0:2376" even though it was explicitly started with the IPv4 form, so any attempt to connect to the docker engine via IPv4 fails.

**Comment by doxxx** [comment]
So I feel a bit stupid now. I tried connecting with docker and it does actually work now. I had assumed that the "tcp6" in the netstat output meant that it wasn't listening for ipv4 connections and didn't actually *try* the connection. `docker-machine ls` shows the machine as running and I can use `docker info` to query the docker engine on that host.

So something I changed made it work. Now to figure out what. :)

**Comment by thaJeztah** [comment]
@doxxx no worries, good luck finding!

**Comment by doxxx** [comment]
Yeah it was the default firewall in Centos 7. I setup a new VM from scratch and ran into the same problem of the create (or the env command) just hanging. Stopped the firewall (`systemctl stop firewalld`) and the env command completed immediately and I was able to query the docker engine's info.

**Comment by aijanai** [comment]
totally nailed it
