### ISSUE TITLE
Malformed URL in error message when no daemon is running

### ISSUE THREAD

**Issue by aaronlehmann** [docker/docker#15309]
With no daemon running:

    $ docker version
    Client version: 1.7.0
    Client API version: 1.19
    Go version (client): go1.4.2
    Git commit (client): 0baf609
    OS/Arch (client): darwin/amd64
    Get http:///var/run/docker.sock/v1.19/version: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?

The "http:///var/run/docker.sock/v1.19/version" part is bizarre. That looks like an error.

**Comment by fredk1018** [comment]
Yes I am currently having the same issue. I will let you know if I find a solution. Please do the same.

**Comment by cpuguy83** [comment]
Yes, it's an error because `docker version` reports both client and server version info, if the server isn't able to be reached it has an error.

**Comment by aaronlehmann** [comment]
My concern isn't that the daemon needs to be running, but that the output cites the URL "http:///var/run/docker.sock/v1.19/version". This is clearly not a HTTP URL.

**Comment by cpuguy83** [comment]
ah, ok... cleaning up here #15370

I never liked these errors anyway.
