### ISSUE TITLE
Why I can't rm docker image?

### ISSUE THREAD

**Issue by dayiguizhen** [docker/docker#15319]
docker version:
    
    Client version: 1.7.1
    Client API version: 1.19
    Go version (client): go1.4.2
    Git commit (client): 786b29d
    OS/Arch (client): linux/amd64
    Server version: 1.7.1
    Server API version: 1.19
    Go version (server): go1.4.2
    Git commit (server): 786b29d
    OS/Arch (server): linux/amd64

docker info:
    
    Containers: 7
    Images: 141
    Storage Driver: aufs
    Root Dir: /var/lib/docker/aufs
    Backing Filesystem: extfs
    Dirs: 155
    Dirperm1 Supported: false
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 3.8.0-44-generic
    Operating System: Ubuntu precise (12.04.5 LTS)
    CPUs: 8
    Total Memory: 7.798 GiB
    Name: n14.build.lewatek.com
    ID: K2QV:NGVH:JNCK:532B:7LYQ:GAGC:TW2K:DZ5I:LMGA:WOPJ:FO5F:G3FG
    WARNING: No swap limit support

uname -a:
    
    Linux n14.build.lewatek.com 3.8.0-44-generic #66~precise1-Ubuntu SMP Tue Jul 15 04:01:04 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

My steps:

* I run container A from image A

* Then, I do change something in container A and commit this container to image B

* I run container B from image B and rm -f container A

* I rmi image A .

The docker tell me the container B is using image A,so I can't `rmi` it.

I hope I can `rmi` image A.

I guess **image B is based on image A**.But I try to do something follow:
* push image B to my private repository.
* pull image B in other VM.
* run container C from image B ,it can run fine.

So container C can run without image A,why in first vm container B need image A?

**Comment by Pensu** [comment]
That's quite interesting. My best guess would be that when you commit your changes, docker still keeps the base image as A, puts a layer on it and names it B. The difference here would be that it's just adding a layer and naming it B, not creating a new image. On the other hand, when you push the image to dockerhub, it pushes the whole image, so that you can pull it somewhere else and run as container. Correct me if I am wrong!

**Comment by aidanhs** [comment]
This is expected behaviour, unless I'm misunderstanding.

If you do `docker history` on image B on host 2 you'll see the image ID for image A listed - the layer has transparently come with it. Read https://docs.docker.com/introduction/understanding-docker/#how-does-a-docker-image-work

**Comment by mountkin** [comment]
@aidanhs I think in this case image A should be allowed to untag. 
I made a proposal on this some time ago #13422

**Comment by aidanhs** [comment]
Ah I see, it wasn't clear to me that the reporter was trying to remove an image *name* rather than ID. That makes sense.

**Comment by cpuguy83** [comment]
Closing as this should no longer be a problem (not the linked issue above is also resolved).

Images no longer really have parents and are not really a tree.
They do share layers, but each image stands on it's own. If nothing is using image A it can be removed, but any fs layers being used by other images will not be removed.
