### ISSUE TITLE
docker.io is default for docker login

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#15317]
Shouldn't the default be `registry.hub.docker.com`  --- the reason I ask is that I have an account on Docker Hub which is where we are sending everyone.  Do we want people creating accounts on `docker.io` which doesn't seem to have the same set?

**Comment by LK4D4** [comment]
@thaJeztah was this addressed?

**Comment by thaJeztah** [comment]
I think it is, at least the visible message is now:

```
Login with your Docker ID to push and pull images from
Docker Hub. If you don't have a Docker ID, head over to
https://hub.docker.com to create one.
```
