### ISSUE TITLE
install on Ubuntu 14.04 should fail due to missing requirements

### ISSUE THREAD

**Issue by hans-d** [docker/docker#15323]
BUG REPORT INFORMATION

Use the commands below to provide key information from your environment:

docker version:
```
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
```
docker info: `Cannot connect to the Docker daemon. Is 'docker -d' running on this host?`

uname -a: `Linux h2464861.stratoserver.net 3.13.0-042stab092.3 #1 SMP Sun Jul 20 13:27:24 MSK 2014 x86_64 x86_64 x86_64 GNU/Linux`

Provide additional environment details (AWS, VirtualBox, physical, etc.): VPS

List the steps to reproduce the issue:
1. get fresh ubuntu 14.04.03
2. `wget -qO- https://get.docker.com/ | sh`

Describe the results you received:
docker -d is not running

Describe the results you expected:
1. docker -d is running
2. or quit installer and complain about missing packages

Provide additional info you think is important:
- from https://docs.docker.com/installation/ubuntulinux/: For Trusty 14.04 - There are no prerequisites for this version.
- see below

----------END REPORT ---------

Having a fresh Ubuntu 14.04.3

```
$ lsb_release
No LSB modules are available.
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
```

ran docker-machine with generic driver, I see it install docker.
Then
```
Using SSH client type: external
About to run SSH command:
sudo docker version
&{/usr/bin/ssh [/usr/bin/ssh -o PasswordAuthentication=no -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -i /id_rsa -p 22 user@someserver sudo docker version] []  <nil> <nil> <nil> [] <nil> <nil> <nil> ?reflect.Value? false [] [] [] [] <nil>}
SSH cmd err, output: exit status 1: Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?

Error getting SSH command to check if the daemon is up: exit status 1
```

running `docker -d` manually on that server:
```
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
ERRO[0000] 'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded.
WARN[0000] Running modprobe bridge nf_nat failed with message: , error: exit status 1
FATA[0000] Error starting daemon: Error initializing network controller: Error creating default "bridge" network: package not installed
```

installing manually on the server results in the same.
```
$ wget -qO- https://get.docker.com/ | sh
modprobe: ERROR: ../libkmod/libkmod.c:507 kmod_lookup_alias_from_builtin_file() could not open builtin file '/lib/modules/3.13.0-042stab092.3/modules.builtin.bin'
modprobe: FATAL: Module aufs not found.
Warning: current kernel is not supported by the linux-image-extra-virtual
 package.  We have no AUFS support.  Consider installing the packages
 linux-image-virtual kernel and linux-image-extra-virtual for AUFS support.
+ sleep 10
+ sudo -E sh -c sleep 3; apt-get update
```
(looks like also docker-machine produces this, but missed it due to not large enough scroll buffer)

Documentation states for Ubuntu 14.04 no prerequisites.

**Comment by juliantaylor** [comment]
```
uname -a: Linux h2464861.stratoserver.net 3.13.0-042stab092.3 #1 SMP Sun Jul 20 13:27:24 MSK 2014 x86_64 x86_64 x86_64 GNU/Linux
```

this does not look like a stock ubuntu kernel, those would report something with -Ubuntu

**Comment by hans-d** [comment]
indeed not a normal kernel. Played some more with it, and cancelled that VPS. In this case the installer should fail, in stead of just the warning.

**Comment by rav3n-80-bl4ck** [comment]
not sure but try installing docker this way first :

sudo apt-get install docker.io lxc

then do ---> "docker -d" without "" incase it won't start automatically.

**Comment by dodekaeder** [comment]
hey hans,
i've the same problem. Having a strato vps and searched since hours for a solution of this problem, ending in this post. Well I like to switch my vps too, but I'm not sure if I'll get into the same problem by just choosing one of the other big player.

Do you allready got a new vps?

**Comment by hans-d** [comment]
@dodekaeder strato dedicated works. Many other vps privders seem to have working solutions.

**Comment by thaJeztah** [comment]
We recently updated our docs, moving away from the automatic `curl | sh` install script, and explaining the manual steps to install docker; https://docs.docker.com/installation/ubuntulinux/

**Comment by LK4D4** [comment]
I'm closing this issue. Rouge kernels is sad story :(
