### ISSUE TITLE
Build doesn't add files in script if run in a volume

### ISSUE THREAD

**Issue by milch** [docker/docker#15333]
I am currently encountering the following problem - I have a `Dockerfile` for a container that is used as a data container. When building this container, I would like to download a few files, with my `init.sh` script:

```bash
#!/bin/bash

cd /var/www
wget -q -O ldap.zip https://github.com/leenooks/phpLDAPadmin/archive/master.zip
unzip ldap

wget -q -O zpush.zip https://github.com/fmbiete/Z-Push-contrib/archive/master.zip 
unzip zpush

# A few more downloads here ...
```

The idea is that I have all the configuration files in this container, and add the downloaded files on top. So the directory structure on my machine looks a bit like this:

```
|-- Dockerfile
|-- root
    |-- var/www/zpush
        `-- config.php
    `-- var/www/phpldapadmin
        `-- config.php
```

With the following `Dockerfile`:

```
FROM debian:jessie
VOLUME ["/var/www"]
RUN DEBIAN_FRONTEND=noninteractive apt-get update -qq && apt-get install -y wget unzip && apt-get clean
ADD ["root","/"]

RUN ./init.sh

CMD ["/bin/true"]
```

However, when looking into the `/var/www` folder (for example by running `docker run data-container ls -l /var/www` after building), none of the downloaded files are actually in there! Only the ones that were put in with the `ADD ["root", "/"]` instruction are found, the others just seem to have vanished into nirvana. If I modify my `init.sh` script and add `ls` at the start and the end, I can clearly see that the files get added, but they seem to vanish after the `init.sh` script finishes.

Here is some additional information - `$ docker -D info`:
```
Containers: 3
Images: 20
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 26
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.5-boot2docker
Operating System: Boot2Docker 1.7.0 (TCL 6.3); master : 7960f90 - Thu Jun 18 18:31:45 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
ID: LTF3:2WCG:KWHL:U5SC:HDUX:2DCH:JIXP:ZU7O:VD4D:PSXI:BXNU:XWIO
Debug mode (server): true
File Descriptors: 9
Goroutines: 17
System Time: 2015-08-05T15:50:31.495141275Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: milch
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

`$ docker version`:
```
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): darwin/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

`$ uname -a`
```
Darwin 15.0.0 Darwin Kernel Version 15.0.0: Sun Jul 26 19:48:55 PDT 2015; root:xnu-3247.1.78~15/RELEASE_X86_64 x86_64
```

**Comment by duglin** [comment]
@milch any data put into a volume during the build process will not be saved in the resulting image.  So if you want that data in the image you'll have to put it some place other than /var/www

**Comment by milch** [comment]
Huh? Why not? 

Since this is a data container and not really supposed to run what would be a possible workaround? I need the data to end up in `/var/www` and multiple other containers need to access that data.

**Comment by thaJeztah** [comment]
I think it should work if you put your `VOLUME` to the end of your Dockerfile, then the volume is not used during the earlier build steps; could you give that a try?

**Comment by thaJeztah** [comment]
To explain; a `VOLUME` in a Dockerfile results in a *new* volume being created in each build step after that, changes made in that volume get lost, because the next build step will create a new volume

**Comment by milch** [comment]
Oh, I didn't know that. Glad to see that it is getting changed in the documentation already!

Anyway, putting `VOLUME` at the end seems to work. Thanks!

**Comment by thaJeztah** [comment]
@milch I actually think there's already mention of this in the docs, but it's still tripping people :-)

Glad to hear this worked for you!

**Comment by milch** [comment]
I didn't find it [here](https://docs.docker.com/reference/builder/#volume) in the documentation regarding volumes in the Dockerfile, which is why I didn't know about this. The PR that just linked this issue (#15337) seems to fix that, though.

**Comment by thaJeztah** [comment]
yeah I'm looking as well, maybe it got lost in a rebase.
