### ISSUE TITLE
Reporting graph driver storage utilization

### ISSUE THREAD

**Issue by simon3z** [docker/docker#15331]
It may be interesting, for monitoring purpose, to report the storage utilization of the graph drivers.

The information is already reported by some graph drivers, e.g.

https://github.com/docker/docker/blob/a15b676/daemon/graphdriver/devmapper/driver.go#L73-L86

but it's in an unstructured fashion.

I think each driver should report, total and used (or free, or both used/free) space in such a way that could be reliably monitored by external applications.

**Comment by vbatts** [comment]
@simon3z for posterity, can you include the version of docker you're working with presently.

This has come up in discussions before, but has been decided to not be an enforced expectation of a graphdriver. The methodologies of what actually being reported are subject to what aspect you're interested in. Finding the common expectations, and how to derive that from the different filesystems is not a clear path.

I'm game to see this implemented, though it will take investigation and likely some concessions.

**Comment by simon3z** [comment]
> @simon3z for posterity, can you include the version of docker you're working with presently.

$ docker --version
Docker version 1.7.1.fc22, build b6416b7/1.7.1

**Comment by LK4D4** [comment]
@mlaventure I believe this will be closed by data management?

**Comment by mlaventure** [comment]
I think so yes. My PR is only reporting usage from a "top object" point of view (e.g. images, containers) but I don't think we want to expose the low level internals (i.e. layers) to the users, so that should do it at least for now.

**Comment by LK4D4** [comment]
#26108 for reference.
