### ISSUE TITLE
Docker Systemd Service not using  config

### ISSUE THREAD

**Issue by kameshsampath** [docker/docker#15339]
I installed docker on Centos 7.x via the docker yum repo. When I enabled the docker systemd service , the service gets started but it is not picking the other_args from the /etc/sysconfig/docker, when debugged the /usr/lib/systemd/system/docker.service, I saw that the EnvironmentFile entry was missing in the docker.service, I have to add it manually to make my docker options work the daemon.

**Comment by kameshsampath** [comment]
Docker version 1.7.1, build 786b29d

Docker Info:
Containers: 3
Images: 90
Storage Driver: devicemapper
 Pool Name: docker-253:1-101210720-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.96 GB
 Data Space Total: 107.4 GB
 Data Space Available: 15.65 GB
 Metadata Space Used: 4.235 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.143 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.7.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 1
Total Memory: 1.797 GiB
Name: dockins
ID: EPNJ:E3GA:GJ3T:5OYI:7CCC:REYD:BXE7:QXF7:D3NQ:CYLY:ZLIK:67EF

uname -a
Linux dockins 3.10.0-229.7.2.el7.x86_64 #1 SMP Tue Jun 23 22:06:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Box: Vagrant with VirutalBox with Centos 7

Steps:

1. Install docker registry 
2. Start Docker registry 
3. Build any docker container
4. Push the image to local registry 
5. You will get an error with all registry urls using https://
6. Edit the /etc/sysconfig/docker, set the other_args='--insecure-registry 192.168.10.1:5000'
7. Restart the docker daemon 
8. Repeat Step 4, you will get the same result 
9. Edit the /usr/lib/systemd/system/docker.service and add the Entry 'EnvironmentFile=-/etc/system/docker'
10. Repeat Step 4, now it will be successful

The default 'docker.service' is not having the entry for 'EnvironmentFile'

**Comment by phemmer** [comment]
Dup of #14663 (and many others).

**Comment by thaJeztah** [comment]
Yes, we've updated the documentation around this, which will be published together with the 1.8 release. See https://github.com/docker/docker/pull/15301 for the documentation changes.

I'm going to close this issue, but feel free to comment here if you think I closed by mistake
