### ISSUE TITLE
Proposal: Link containers on Build

### ISSUE THREAD

**Issue by mariolameiras** [docker/docker#15338]
#### Problem:

We are building images with ready-to-use applications where we have a separated DB or other external service that needs to be populated while installing the main application in a separated container.

The problem is that we can't execute all the installation tasks for an application if it depends on an external service running on a separate container.

#### Example:

On container #1 I want to install a tomcat with a deployed WebApp and a datasource pointing to a mysql database

On Container #2 I'll have the mysql docker image 

On my dockerfile for container #1 i want to be able to configure and test the datasource and install via script the tables running on the database.

Currently, as far as i know this is only possible by starting the container #2 manually, and pointing the datasource on the build phase to the dynamic ip on container #2.

It would be much more elegant to be able to link both containers while running `docker build`

#### Proposal:

Implement the --link option on `docker build`

On docker-compose it would be great to have this feature as well respecting the order on the yml file 

I can't seem to find any discussion or planning about this problem on github, but it seems to be more or less common:

- https://stackoverflow.com/questions/26551279/how-to-link-docker-containers-on-build
- https://blogs.gnome.org/alexl/2014/06/12/building-clean-docker-images/

**Comment by ZJaffee** [comment]
Try using docker-compose, you might be able to find some solutions to your problem there.

**Comment by duglin** [comment]
one of the ideas people have talked about is splitting the builder/Dockerfile commands up so each one could be invoked as a stand-alone executable. This would then allow you to do the same thing as what's done during a build but do it in your favorite scripting language.  Once we have that I think you should be able to use `--link` as well.  Not there yet so it can't help immediately, but something to watch for.

**Comment by cpuguy83** [comment]
Definitely -1 on doing such a thing for the build API (whether or not its server-side or the official client).
This breaks important separation of concerns.

Creating the runtime to which the application can actually run in is different than providing the environment specific details (like state in mysql).
You can of course build these into the same image and not have the problem you are having... but it's the same concern about separation.

I'm going to close this as builds are quite purposefully self-contained and should have no side-effects outside of the build.

**Comment by mariolameiras** [comment]
@cpuguy83  I agree that the container should be self-contained. But on the other hand we have things like docker-compose that are meant to interlink containers. 

So maybe it would make sense to have some "config" phase where you configure a set of containers to be distributed together ?

What are your thoughts on this ? I have to agree with your concern, but still i feel there is a common problem left to be solved, that should have a common solution.

**Comment by cpuguy83** [comment]
I don't think it's a problem at all, you just need to separate the concept of seeding a database with creating your apicatipn runtime.

When I say self-contained I'm referring specifically to builds. Building an image should not expect to connect to some external thing to seed state information.

**Comment by duglin** [comment]
What if the container that we need to link to holds the install packages we want to install?

**Comment by cpuguy83** [comment]
Can certainly hack in some DNS.
The services API would also handle this, presuming that you publish the service to the network.

**Comment by PrakashNeelakanta** [comment]
I have similar problem...
Container #1 postgres Db
Container #2 web app. In my web app when i do mvn clean install, it should connect to postgres but currently it is failing to connect to postgress... 
approach
1)
 a) i ran the postgres container first make sure it is up and checked 5432.. 
 b) ran mvn clean install 

failed to connect to postgress...

2) created docker-compose.yaml file like below 

version: "2"
services:
 web:
   build: .
  command: mvn clean install
  links:
   - mongoapp
   - postgressapp

 mongoapp:
  image: mongoapp
  ports:
   - "27017:27017"
  depends_on:
   - "postgressapp"
  expose:
   - "27017"

 postgressapp:
  image: postgressapp
  ports:
   - "5432:5432"
  expose:
   - "5432"

same error... 
(In one of pom file we are connecting to postgres and checking connection status)
Can anybody help me here...

**Comment by myuseringithub** [comment]
I actually need this feature too. The ability to use multiple containers as resources for a build. Any hackish way of achieving this ?
