### ISSUE TITLE
Docs: "docker run --net" possible values not documented.

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/docker#15347]
http://docs.docker.com/reference/commandline/run/ and  `docker run --help` docs are not showing what possible values `docker  run --net` argument can take.

I know `--net=host` exists from some prior knowledge but I can't seem to locate it in the docs. cc:@thajeztah

**Comment by thaJeztah** [comment]
It's documented in run reference; http://docs.docker.com/reference/run/#network-settings

**Comment by ahmetalpbalkan** [comment]
@thaJeztah fair enough, but shouldn't this page: http://docs.docker.com/reference/commandline/run/ link to the "Docker run Reference" page? First one nearly looks like a subset of the latter.

**Comment by thaJeztah** [comment]
Actually there is;
![image](https://cloud.githubusercontent.com/assets/1804568/9099331/2e5a28c0-3bd0-11e5-828d-437155bbdcd3.jpg)

But I agree that the separation between "run reference" and "CLI run" has become confusing. Either "CLI run" should get *less* detail (and refer to run reference), or the documents should be combined.

There's a *lot* of information for docker run, though.

**Comment by ahmetalpbalkan** [comment]
Very well, then. :)
