### ISSUE TITLE
docs for API < 1.14 is broken

### ISSUE THREAD

**Issue by vieux** [docker/docker#15349]
From https://docs.docker.com/reference/api/docker_remote_api/

https://docs.docker.com/reference/api/docker_remote_api_v1.15/
https://docs.docker.com/reference/api/docker_remote_api_v1.14/

are working, but

https://docs.docker.com/reference/api/docker_remote_api_v1.13/
https://docs.docker.com/reference/api/docker_remote_api_v1.12/
....

doesn't (404)

**Comment by vieux** [comment]
ping @moxiegirl

**Comment by vieux** [comment]
@GordonTheTurtle NO

**Comment by moxiegirl** [comment]
@vieux We are only supporting through .14 --- is there a reason you think we need the older versions?

**Comment by thaJeztah** [comment]
IIRC, the older versions were deliberately removed some time ago

**Comment by MHBauer** [comment]
Do you want everything less than .14 removed from the current version of the repo? I can make a PR for that.

**Comment by vieux** [comment]
@moxiegirl if we support only 1.14 and up, but in that case we should remove all the unsupported versions from https://docs.docker.com/reference/api/docker_remote_api/

**Comment by moxiegirl** [comment]
@vieux You are correct...good catch. Sorry I missed that yesterday was a bit crazy.  @MHBauer fire at will also
