### ISSUE TITLE
VolumeDriver currently in Config, not HostConfig

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#15342]
I wanted to raise this because I feel like it's wrong.
Currently `VolumeDriver` is specified in `Config` instead of `HostConfig`, even though this is a host-specific configuration. And, for instance, I wouldn't want someone to commit a container to an image where it's specifying some plugin as a driver.

**Comment by cpuguy83** [comment]
ping @LK4D4 @calavera @icecrime @jfrazelle

**Comment by cpuguy83** [comment]
Also ping @ibuildthecloud

**Comment by calavera** [comment]
I removed from the release. It's too late to change this for this release, if it needs to be changed.

My take: it's not a host specific configuration.

**Comment by cpuguy83** [comment]
I think this is the very definition of a host-specific setting.
If someone creates an image where they've specified `--volume-driver ceph`, and I try to run that, it will fail because I don't have ceph.
An image should be runnable regardless of where/how it's state information is stored.

**Comment by thaJeztah** [comment]
Yup, agree with @cpuguy83 here. The example above makes images non-portable, and no longer "run anywhere"
