### ISSUE TITLE
Docker repository in a mirror mode doesn't support a corporate proxy

### ISSUE THREAD

**Issue by dmeytin** [docker/docker#15358]
Hi there,
The current version of docker repository doesn't support external communication using corporate proxy.
In mirroring.py we should add proxies parameter in the request object initiation. I.e.:
 proxies = {
        "http": os.getenv('http_proxy')
        "https": os.getenv('https_proxy')
    }
    source_resp = requests.get(
        source_url,
        params=flask.request.args,
        headers=headers,
        cookies=flask.request.cookies,
        stream=stream,
        proxies=proxies
    )

**Comment by aidanhs** [comment]
I assume you're talking about `mirroring.py` from the docker-registry repository (https://github.com/docker/docker-registry/blob/master/docker_registry/lib/mirroring.py) so I suggest you raise that there (https://github.com/docker/docker-registry).

That said, the python docker registry is deprecated so it may never be implemented - instead, you may wish to consider raising this in the new registry repository, https://github.com/docker/distribution

**Comment by dmeytin** [comment]
Thanks for clarification!
