### ISSUE TITLE
Release client-only binaries for Linux

### ISSUE THREAD

**Issue by aidanhs** [docker/docker#15360]
Now static linking on some platforms is becoming a thing of the past, it's no longer reliable to do `-v /usr/bin/docker:/usr/bin/docker -v /var/run/docker.sock:/var/run/docker.sock` to get docker inside a container.

It would therefore be helpful to have statically linked client binaries for downloading inside containers because they're so much smaller.

**Comment by aidanhs** [comment]
I think @jfrazelle is the release binaries boss?

**Comment by jfrazelle** [comment]
we will always have the static binaries as well that will never change they are in the docs and downloadable today and future releases

**Comment by jfrazelle** [comment]
https://docs.docker.com/installation/binaries/

**Comment by aidanhs** [comment]
@jfrazelle this is about *client-only* binaries which you don't release for Linux.

**Comment by phemmer** [comment]
Why do you need a client-only binary?

**Comment by aidanhs** [comment]
Size reasons:

```
$ make binary && ls -hl bundles/1.9.0-dev/binary/docker-1.9.0-dev
[...]
-rwxr-xr-x 1 root root 21M Aug 27 12:37 bundles/1.9.0-dev/binary/docker-1.9.0-dev
$ make DOCKER_CLIENTONLY=1 binary && ls -hl bundles/1.9.0-dev/binary/docker-1.9.0-dev
[...]
-rwxr-xr-x 1 root root 9.9M Aug 27 12:38 bundles/1.9.0-dev/binary/docker-1.9.0-dev
```

If you need to download a docker client binary on-demand (concrete example: I've built a tool which shells out to the docker client, but I need an older client version to make sure I can interact with older daemons), it can take a while to download the binary. Not everyone has fast internet :(

**Comment by Zoltu** [comment]
:+1: 	I also would like client-only binaries for linux for similar reasons.

**Comment by thaJeztah** [comment]
This may become reality for all platforms soon https://github.com/docker/docker/pull/20639

**Comment by itaysk** [comment]
I also would love to see a client only release. The reason is that I do automated swarm tasks from different servers and I don't need the entire docker stack there, just the client.

**Comment by justincormack** [comment]
The client and daemon are now separate binaries. I don't think they are packaged seperately but you can use them seperately.

**Comment by vlerenc** [comment]
+1, please provide separate packages.

This is handy if you connect remotely, i.e. definitely only need the CLI and the engines (possibly Swarm cluster) runs elsewhere or for CI purposes where you interact either with a Docker instance elsewhere (outside your CI container) or not at all (e.g. only to build images).

**Comment by astewart-twist** [comment]
+1

**Comment by sdomula** [comment]
+1

**Comment by murali44** [comment]
+1

**Comment by YichengPu** [comment]
+1

**Comment by panga** [comment]
+1

**Comment by AkihiroSuda** [comment]
Actually there is the client binary (although not "release")
https://master.dockerproject.org

**Comment by minhoryang** [comment]
I want a way to install docker client only at ubuntu-apt-repository!

**Comment by pcgeek86** [comment]
Please provide a client-only `docker` executable file, similar to Docker Compose and Docker Machine.

**Comment by artemkaint** [comment]
+1 to separate packages

**Comment by ryanwalls** [comment]
FYI, this has already been done in #20639.  To get the individual binaries, download the release, e.g. https://get.docker.com/builds/Linux/x86_64/docker-1.12.2.tgz and unzip it.  Inside you will find `docker` which is the client and `dockerd` which is the engine as well as some other binaries.  

You can get the latest releases here: https://github.com/docker/docker/releases.

**Comment by Daniel15** [comment]
Is there a Debian package containing just the client binary?

**Comment by thaJeztah** [comment]
@Daniel15 no, currently it's only the static binaries (as mentioned above). Our current build/release procedure will need to be updated to do client-only debs/rpms, which involves quite some changes.

@andrewhsu is currently working on changes in that area, and possibly releasing client-only debs would be more easy to implement in future. So, the TL;DR is that we see this being useful, but no ETA yet

**Comment by atrauzzi** [comment]
Hopefully this can be bumped up in priority.

**Comment by dimitrovs** [comment]
+1

**Comment by persapiens** [comment]
+1

**Comment by Christian-Schmid** [comment]
+1

**Comment by briceburg** [comment]
I vote to release _client only_ binaries to make adding the docker binary to a container network and space efficient. E.g.

```
RUN mkdir -p /tmp/download && \
 curl -L https://get.docker.com/builds/Linux/x86_64/docker-1.13.1.tgz | tar -xz -C /tmp/download && \
 rm -rf /tmp/download/docker/dockerd && \
 mv /tmp/download/docker/* /usr/local/bin/ && \
 rm -rf /tmp/download
```

becomes

```
RUN mkdir -p /tmp/download && \
 curl -L https://get.docker.com/builds/Linux/x86_64/docker-client-1.13.1.tgz | tar -xz -C /tmp/download && \
 mv /tmp/download/docker/docker* /usr/local/bin/ && \
 rm -rf /tmp/download
```

The above use-case comes from a DooD setup (e.g. mounting /var/run/docker.sock into container, but _not_ $(which docker):/usr/bin/docker)

**Comment by MicahZoltu** [comment]
If the client-only binaries were a single file that would be even simpler:
```
RUN curl -L https://get.docker.com/builds/Linux/x86_64/docker-client-1.13.1.tgz | tar -xz -C /usr/local/bin
```

**Comment by ava-dylang** [comment]
Whats the status on this? What is the best way to connect to a docker server without installing the whole docker engine on the client?

**Comment by taylorp36** [comment]
Also curious ^

**Comment by a0viedo** [comment]
I don't know if it's for official use but I'm using https://master.dockerproject.org/linux/x86_64/docker to get the binary and https://master.dockerproject.org/linux/x86_64/docker.sha256 to perform the checksum.

**Comment by 10000TB** [comment]
+1

**Comment by wgerlach** [comment]
+1

**Comment by thaJeztah** [comment]
With the split between the Moby project, and Docker's products, this discussion would be better taken to https://github.com/docker/docker-packaging/issues, as the Moby maintainers are not responsible for what's packaged / distributed by Docker.

While there's no separate package for just the client, I suggest to download a `.tgz` with static binaries (including the client);

- For Linux; https://download.docker.com/linux/static/
- For Mac; https://download.docker.com/mac/static/
- For Windows; https://download.docker.com/win/static/

The official Docker image on Docker Hub may also be helpful;

https://hub.docker.com/_/docker/

I'm locking the conversation here; not because I don't agree (or disagree) with this request, but because this is a decision to be made by the Docker release team, and not something that can be decided on in this repository, but feel free to open a request in the https://github.com/docker/docker-packaging/issues repository.

**Comment by thaJeztah** [comment]
Apologies, I linked to a private mirror of the https://github.com/docker/docker-ce-packaging packaging scripts repository, but that one doesn't have an issue tracker; the right repository would be https://github.com/docker/for-linux/issues
