### ISSUE TITLE
Error unmarshaling return header; nested exception // Unknown Host Exception 

### ISSUE THREAD

**Issue by kps18** [docker/docker#15363]
Hi

For Build purpose, While connecting windows machine from docker container, We are facing unmarshaling error. and while transferring from container we are facing Unknown host exception.
Please help.

Here the server details:-
Docker 

info

docker info
Containers: 2103
Images: 251
Storage Driver: devicemapper
 Pool Name: docker-8:4-110756217-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 63.85 GB
 Data Space Total: 107.4 GB
 Data Space Available: 43.52 GB
 Metadata Space Used: 207.1 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 1.94 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.18.16
Operating System: CentOS Linux 7 (Core)
CPUs: 64
Total Memory: 503.9 GiB
Name:<Hostname>
ID: SHT2:SGL5:XDHB:KV2V:IAYX:35H3:OAAY:BB7N:I7EA:7FIH:TWWU:E3PU

docker  version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64

**Comment by kps18** [comment]
I dont know this is bug, This is second issue i have raised here.

Thanks

**Comment by cpuguy83** [comment]
@kps18 Can you provide some more detail? Where are these messages coming from? What was happening when the errors occurred, etc.
Can you paste the full daemon log?

**Comment by kps18** [comment]
Purpose is mainly  for  build purpose. i get unknown host exception randomly during my build. i dont have any idea why this is happening.

**Comment by cpuguy83** [comment]
@kps18 

We really need more information to be able to look at this:
 - Logs from the daemon
 - What is running when this happens
 - Exact error messages

Closing for now, if you can provide this info please ping here so we can take a look.
Thanks!
