### ISSUE TITLE
Orphaned docker container continues to live on after daemon is killed

### ISSUE THREAD

**Issue by hermansc** [docker/docker#15397]
After upgrading to Docker 1.7.1 (from 1.5.0) I consequently killed/restarted the Docker daemon (through upstart: `service docker restart`) and started seeing strange behaviours when starting new containers on the new daemon. Most prominent was it that 50% of our requests to HAProxy were dropped with 503 errors, but with no logs or traces of this in the HAproxy container that we ran and exec'd into running `docker exec`. Here's an example of what we saw, port 1012 is just a random HTTP service under HAProxy:

```
# for i in {1..100}; do curl -I -s http://127.0.0.1:1012/ | head -n 1; done
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.0 503 Service Unavailable
HTTP/1.1 200 OK
HTTP/1.0 503 Service Unavailable
```

Now, after a good amount of debugging I traced the issue down after running the following command on the host system:

```
# sudo netstat -tulpn | grep 1012
tcp        0      0 0.0.0.0:1012            0.0.0.0:*               LISTEN      6256/haproxy
tcp        0      0 0.0.0.0:1012            0.0.0.0:*               LISTEN      3382/haproxy
```

The HAProxy container is running in host network mode, but I was not expecting to see two processes bound to port 1012 at all!

Using `ps auxf` I can see that PID 6256 is indeed running as a child of the docker daemon process, but 3382 is owned by PID 1 and seems to be the old HAProxy container from Docker 1.5.0. Is this the consequence of a potentially failed graceful shutdown of the docker container?

<img width="1068" alt="screen shot 2015-08-07 at 09 16 28" src="https://cloud.githubusercontent.com/assets/116978/9131754/535c69c8-3ce6-11e5-811d-d149b0f79d95.png">

In any case, it all worked after I did `kill 6284` which was the PID of the init system in the orphaned process (see screenshot).

Tips on how to avoid this happening again would be greatly appreciated, as the consequences in many cases are very subtle.

And to make the turtle happy:
`docker version`:
```
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```

`docker info`:
```
Containers: 25
Images: 1422
Storage Driver: aufs
 Root Dir: /local/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1474
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-29-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 16
Total Memory: 18.9 GiB
Name: hostname
ID: CR5T:Q6FF:ZCWB:77JB:IWJG:MK6E:CICB:HZAH:NSG3:DXIX:7UAT:YPLH
WARNING: No swap limit support
```
`uname -a`:
```
Linux rainey2 3.13.0-29-generic #53-Ubuntu SMP Wed Jun 4 21:00:20 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by cpuguy83** [comment]
How was HA Proxy started?
I can see this happening if HA Proxy became a zombie if the container was started and HA Proxy wasn't PID1 (And PID1 in the container didn't waitpid on it).
Also could be a bug in docker 1.5 with host networking mode...

**Comment by hermansc** [comment]
HAProxy was started through "marathon" which in turn communicates with Mesos. Mesos is then the actual executor of the docker command, I reckon. In terms of config options, the only ones passed into Marathon+Mesos and thus the daemon were:

`--volume /data/haproxy:/local/haproxy:ro` and `--net=host`.

But as I'm using the `phusion/baseimage` image HAProxy wasn't PID1, and it could be that the `/sbin/my_init` didn't waitpid it. As I mentioned though it was started on a Docker 1.5.0 daemon, so for all I know (and if you say so) it could be related to a bug in the host networking mode on that version.

If you want you can close this, and I'll re-open it if I experience the same on 1.7.1? :)

**Comment by crosbymichael** [comment]
Because of the recent changes with docker if you are still running into this issue please reopen it.  

We now have features like live-restore that allows containers to live after the daemon is killed and the default handling for containers has been improved. 

Thanks!
