### ISSUE TITLE
To many environment variables prevents the execution of binaries on CentOS.  The variables docker creates on link are overwhelming my test composition.

### ISSUE THREAD

**Issue by McAlister** [docker/docker#15391]
I was creating a test environment in docker-compose for a tool with many ... MANY ... external dependencies. Among its typical ecosystem is a Rabbit MQ ring with three nodes and a pair of Apache Solr servers along with memcached, and some services we wrote ourselves.   

When I 'docker_compose up' my environment in the main container has over 1k entries in it from linking dependencies. The rings are particularly chatty with rabbit3 alone haveing well over 100 entries. This is causing my kernel to be unable to execute binaries. Per documentation the shell environment, some security information, and argv/argc are all put into the same buffer when execing a program and it has limited size.

Validation:

1- If I open a sub-shell in the dock and empty the ENV, the binaries run just fine.

2 -If I copy my environment into a file, strip out everything but what compose generated, and load the same variables on a physical centOS box the same failures start occuring. So it isn't a poison environmental pill or special value interracting with our code.

3 - by shortening my container names to two letter abbreviations and ditching the third rabbit node I got the number of characters in my environment under the threshold and my app resumed working.

Since I'm using /etc/hosts instead of these variables to talk to the various containers anyway I don't need them.  Can I get a flag to prevent them from being generated in the first place?

Thank You

**Comment by cpuguy83** [comment]
Oy... really not sure what to do here... I'd really rather not make a new flag for this.
I'd say we should deprecate the link env vars as they are pretty much useless.

**Comment by cpuguy83** [comment]
Might I suggest also not using the linking feature for such a use-case and instead use a full DNS or some other service discovery mechanism?

**Comment by McAlister** [comment]
> I'd say we should deprecate the link env vars as they are pretty much useless.

As a PR note, when the environment gets too full it doesn't give you a clear error or anything but starts randomly failing in a non-deterministic way.  So a binary might work once, core halfway through the next time, and fail to even start the third time returning nothing. I could press up arrow and enter 5 times in a row and have it fail in 5 completely different ways, producing 3 cores that backtraced to completely different lines of code in a non-threaded demo program that did nothing but read a config file and exit. One of the fails that didn't produce a core would be, "Cannot find config file /config/myco$(#*??N..." highlighting that memory corruption was clearly at play.  But we knew it wasn't our memory corruption because it happened with anything we put inside the container.  

This is terrifying.  

And when we didn't understand *why* it called into question the integrity of docker itself because ... well .. they run fine outside of docker ... docker shouldn't be capable of corrupting application memory even if it tried ... but .. *they run fine outside of docker* ... 

I'm a little bit biased because I'm the main evangelist for docker at this office but its hard enough to get people to adopt a new technology without something like that happening.  I want to baby-proof this so that when I get someone enthusiastic about docker and they go off on their own they don't run into *that*.  I don't want to have to warn them about it or explain it to them or even introduce the idea that putting things inside docks might cause something like that to happen.  

Deprecate.  Deprecate *now*.  If possible, get a time machine an retroactively deprecate such that this never happened. =)

> Might I suggest also not using the linking feature for such a use-case and instead use a full DNS or some other service discovery mechanism?

For service discovery that is a phase two or three thing.  The team responsible for this component is under a mandate to wrap it up tightly in test automation before modifying it - its one of those mission critical pieces written in an obscure language with no automated tests whose original authors is long gone situations.  I can't request code changes to facilitate the dockerization at this stage.  Its both something they aren't supposed to do and likely to provoke a, "well if this tool doesn't do what we need as is we won't use it" response.  Once they get hooked on being able to create working environments in minutes instead of weeks I presume that will change.  

I've squeeked under the wire by moving one node out of every ring to expose its ports on localhost rather than through the link and shortening the container names.  So we are good to go on this one =).  It just looks bad to tell people they can't use long names if they have a lot of containers in a link because if they do they could lose the ability to exec binaries inside the containers.

**Comment by cpuguy83** [comment]
And you can't setup DNS for the containers?

**Comment by McAlister** [comment]
These are ephemeral containers.  The component test rigs are primed with test data for the app in the primary container to process.  When the run is complete they must be torn down and restarted to return to the initial state.  The next time jenkins triggers a test run the containers will have new 127.x.x.x ips and will probably be spun up on a different one of its build boxes with a different 10.x.x.x IP depending on which one is free and jenkins load balancing.  Devs would spin them up while working on the main app in a volume mount but then periodically bounce them to refresh the test scenarios while keeping their work safe in the mount.

Or am I misunderstanding what you mean?  Would there be a DNS trick that could handle this?  Ideally in a way that does not require education of every user?

**Comment by thaJeztah** [comment]
> Deprecate. Deprecate now

@cpuguy83 now that there's a lot of work in progress for the new networking / services, perhaps we *should* mark the link environment variables deprecated (and to be removed in version x.x)

There's been so much talk about most of them being useless (especially the "port" ones); giving a notice *now* that they will be removed in future won't hurt? wdyt?

**Comment by mavenugo** [comment]
@thaJeztah @McAlister agreed. With the upcoming networking and services features, it replaces the link functionality without these issues. Issuing a deprecation notice now is a good idea.

@McAlister you can try out these features which is currently under experimental (https://github.com/docker/docker/blob/master/experimental/networking.md). Also please provide any comments : https://github.com/docker/docker/issues/14083 so that we can include them when we exit experimental and make it a native part of Docker future release.

**Comment by phemmer** [comment]
I'd be interested in seeing a reproduction case for this. I am unable to reproduce locally. When I try, docker properly errors out with `Cannot start container ... System error: argument list too long`

**Comment by McAlister** [comment]
> I'd be interested in seeing a reproduction case for this. 

This was my docker-compose file when it started happening - I redacted the names paths and port numbers of our own containers but you can see the quantity of ports they use.  The ones based on io.docker containers are just the basic container with wrappers that prime them with test data.  

Presumably you can reproduce locally by substituting the containers there for ones with the same ports exposed.  This ran on CentOS 7 with the containers being cent 6 for our stuff and whatever the vender used for the off the shelf stuff.

-------------------------------
indexerdata:
    build: indexer-data
    volumes:
        - /path
        - /other/path
        - work:/work

memcached:
    image: memcached

seqsrv:
    image: app/arc-seq-srv
    hostname: seqsrv
    domainname: test.org
    tty: true
    volumes_from:
        - indexerdata
    ports:
        - "XXXX:XXXX"

rabbit1:
    image: app/rabbitmq
    hostname: rabbit1
    ports:
      - "5672:5672"
      - "15672:15672"

rabbit2:
    image: app/rabbitmq
    hostname: rabbit2
    links:
        - rabbit1
    environment:
        - CLUSTERED=true
        - CLUSTER_WITH=rabbit1
        - RAM_NODE=true
    ports:
        - "5673:5672"
        - "15673:15672"


rabbit3:
    image: app/rabbitmq
    hostname: rabbit3
    links:
        - rabbit1
        - rabbit2
    environment:
        - CLUSTERED=true
        - CLUSTER_WITH=rabbit1
    ports:
        - "5674:5672"
        - "15674:15672"


badrabbit:
    build: indexer-bad-rabbit
    tty: true
    hostname: badrabbit
    domainname: test.org
    volumes:
        - indexer-bad-rabbit/testData/queuelist.txt:/queuelist.txt
    volumes_from:
        - indexerdata

indexerpsql:
    build: indexer-psql
    tty: true
    hostname: indexer-psql
    domainname: test.org
    volumes:
        - indexer-psql/psql/:/sql
        - indexer-psql/test-data:/testData
    ports:
        - "5432:5432"

mockwebservice:
    image: mock/webservice
    volumes_from:
        - indexerdata
    volumes:
        - indexer-dev/files/missingMsgs.txt:/missingMsgs.txt
        - indexer-dev/files/timeoutMsgs.txt:/timeoutMsgs.txt

solr2:
    image: app/arc-solr-core
    tty: true
    hostname: solr2
    domainname: test.org
    privileged: true
    volumes:
        - indexer-dev/files/pod_config.xml:/mxl/etc/pod_config.xml
        - indexer-dev/files/mxl_message_archive.xml:/mxl/etc/mxl_message_archive.xml
        - indexer-dev/files/solr.xml:/mxl/var/solr/solr.xml
    links:
        - memcached
        - indexerpsql
        - seqsrv

solr1:
    image: app/arc-solr-core
    tty: true
    hostname: solr1
    domainname: test.org
    privileged: true
    ports:
        - "8080:8080"
        - "XXXX:XXXX"
        - "XXXX:XXXX"
    volumes:
        - indexer-dev/files/pod_config.xml:/mxl/etc/pod_config.xml
        - indexer-dev/files/mxl_message_archive.xml:/mxl/etc/mxl_message_archive.xml
        - indexer-dev/files/solr.xml:/mxl/var/solr/solr.xml
    links:
        - solr2
        - memcached
        - indexerpsql
        - seqsrv

indexerdev:
    build: indexer-dev
    tty: true
    hostname: indexer
    domainname: test.org
    volumes_from:
        - indexerdata
    links:
        - rabbit1
        - rabbit2
        - rabbit3
        - indexerpsql
        - solr1
        - solr2
        - badrabbit
        - seqsrv
        - memcached

----------------------------------------

If I pop back to that rev and do like so ... 

docker-compose up -d
docker exec -it 14cc1050793e /bin/bash

[root@indexer arc-indexer]# get_config_entry -S "config_name"
config value, success!
[root@indexer arc-indexer]# get_config_entry -S "config_name"
Error opening in_file '/confi_??x': No such file or directory
Error trying to read config file (/confi_??x)!
Error reading config file: /confi_??x
[root@indexer arc-indexer]# get_config_entry -S "config_name"
config value, success!
[root@indexer arc-indexer]# get_config_entry -S "config_name"
[root@indexer arc-indexer]# get_config_entry -S "config_name"
[root@indexer arc-indexer]# get_config_entry -S "config_name"
Error opening in_file '/con?': No such file or directory
Error trying to read config file (/con?)!
Error reading config file: /con?
[root@indexer arc-indexer]# get_config_entry -S "config_name"
config value, success!


The ones that return nothing at all produce a core.  The core straces to random places in the program.

**Comment by McAlister** [comment]
Oh, and in the rabbit dockerfiles they have a lot more exposed than what is put there:

           
EXPOSE 5672   
EXPOSE 15672  
EXPOSE 25672  
EXPOSE 4369   
EXPOSE 9100   
EXPOSE 9101   
EXPOSE 9102   
EXPOSE 9103   
EXPOSE 9104   
EXPOSE 9105   
              
based on this project:

https://github.com/bijukunjummen/docker-rabbitmq-cluster/blob/master/server/Dockerfile

**Comment by McAlister** [comment]
@mavenugo 

> Native multi-host networking

ooooOOOOOooooo ... shiny.  We definitely have use cases that could exercise that.  

> Inbuilt simple Service Discovery

This is hovering dangerously close to my to-good-to-be-true alarm.  

Thanks.

**Comment by LK4D4** [comment]
some sort of service discovery was implemented and links are not right way now. Thanks!
