### ISSUE TITLE
Where is the roofs of container in host machine after docker 1.6.0

### ISSUE THREAD

**Issue by cheyang** [docker/docker#15394]
In docker v1.4.1, we can find the rootfs of a container in host machine.For example, it's in
```
cd /var/lib/docker/devicemapper/mnt/ab83a2638bb23f24d8811fa9b4ca458efca9269696ff3112cc670be2833f3f92/rootfs/
.autofsck     .dockerenv    lost+found/   proc/         sys/
.autorelabel  .dockerinit   media/        root/         tmp/
bin/          etc/          mnt/          sbin/         usr/
boot/         lib/          opt/          selinux/      var/
dev/          lib64/        .pki/         srv/
```

But in docker v1.6.0, I found that '/var/lib/docker/devicemapper/mnt/911d7ac8fca78b2beca8752ec89d80c06a1ea1dd8a65099d074ed40eec0c6cce' is empty. where is it for v1.6.0.

**Comment by cpuguy83** [comment]
This should be in the same basic area, but maybe docker was started with `unshare -m`?

In any case, please ask questions on docker-user, #docker on IRC, or forums.docker.com
docker-user is probably best for something like this.

Thanks!
