### ISSUE TITLE
Create RPM config knob to select which RPMs to build

### ISSUE THREAD

**Issue by Djelibeybi** [docker/docker#15395]
in `hack/make/build-rpm`, we find this TODO item:

    TODO add a configurable knob for _which_ rpms to build so we don't have to modify the file or build all of them every time we need to test

This would be very useful for us who will only be building Oracle Linux images without having to modify the git repo to remove the others. I'm keen to implement this, but I'm seeking feedback on what sort of knob you'd prefer. 

I'm thinking that it has to be something that is external to the Git repo so it can be set via build/CI systems, so I imagine an environment variable is the way to go.

Also, how specific did you want it to be? My initial thought is "all", "distro", "one", i.e. you can either flag to build all RPMs (`*`), build all RPMs for a specific distro (`fedora-*`) or a specific RPM (`fedora-22`).

Ping @jfrazelle and @tianon for thoughts/suggestions.

**Comment by LK4D4** [comment]
ping @tianon @tiborvass @mlaventure

**Comment by tianon** [comment]
Over in `build-deb` we handle this with `DOCKER_BUILD_PKGS` (https://github.com/docker/docker/blob/8aa454dfc8192094221d9ffae5a48d642ea865e4/hack/make/build-deb#L41-L48), which `build-rpm` appears to also support: https://github.com/docker/docker/blob/8aa454dfc8192094221d9ffae5a48d642ea865e4/hack/make/build-rpm#L71-L78

**Comment by LK4D4** [comment]
@tianon Sorry, have no idea what does it mean :) Can we close issue?

**Comment by tianon** [comment]
Oh, this is an old issue!  Yes, this is implemented now. :+1:
