### ISSUE TITLE
How to set "DOCKER_TMPDIR" in 1.7.1

### ISSUE THREAD

**Issue by miztiik** [docker/docker#15403]
I recently upgraded to docker 1.7.1 in centos7, I no longer see the option `DOCKER_TMPDIR` in /etc/sysconfig/docker.

I only see the following now,
```
# /etc/sysconfig/docker
#
# Other arguments to pass to the docker daemon process
# These will be parsed by the sysv initscript and appended
# to the arguments list passed to docker -d

other_args=""
```
How do i tell docker to use a different temporary directory in 1.7.1?

**Comment by miztiik** [comment]
This host is running on VirtualBox hosted on Windows 7
##### Docker info
```
[root@dockerHostCentOS7 docker-image-build]# docker info
Containers: 1
Images: 63
Storage Driver: btrfs
 Build Version: Btrfs v3.16.2
 Library Version: 101
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.11.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 1
Total Memory: 993.6 MiB
Name: dockerHostCentOS7
ID: PMHX:GBIS:ORKD:Z3LB:47SR:OIZE:2X4Z:P57N:ROVL:NZLI:L5HK:MK3G
```
##### Docker Version
```
[root@dockerHostCentOS7 docker-image-build]# docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```
##### uname :
```
[root@dockerHostCentOS7 docker-image-build]# uname -a
Linux dockerHostCentOS7 3.10.0-229.11.1.el7.x86_64 #1 SMP Thu Aug 6 01:06:18 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[root@dockerHostCentOS7 docker-image-build]#
```

**Comment by cpuguy83** [comment]
ping @LK4D4 @jfrazelle I've never set this... is this in `--exec-opt`?

**Comment by jfrazelle** [comment]
i do not think this is a thing

**Comment by jfrazelle** [comment]
and if it is, it is news to me

**Comment by jfrazelle** [comment]
hmmm it is a thing...

**Comment by jfrazelle** [comment]
are you using our RPMs, we use systemd drop in files instead of /etc/sysconfig/docker, also if it is not our rpm, then we do not control it ;)

**Comment by jfrazelle** [comment]
actually i think this can be closed for that very reason, if you want to have custom behavior you should use a systemd drop in file as described here https://docs.docker.com/articles/systemd/

**Comment by miztiik** [comment]
I haven't done anything that is too very much deviant, I use something like
After adding the systemd drop in files, i use something like
`printf "DOCKER_TMPDIR=/media/sf_dockerRepos/dockerTmp\n" >> /etc/sysconfig/docker` to specify the **`DOCKER_TMPDIR=`** , But this documentation https://docs.docker.com/articles/systemd/ doesn't have any reference to how to setup the temp directory.
