### ISSUE TITLE
SIGTERM not sent to process?

### ISSUE THREAD

**Issue by k2xl** [docker/docker#15402]
```
#!/bin/bash
_term() { 
  echo "Caught SIGTERM signal!" 
}
trap _term SIGTERM
echo "hi"
sleep 100000
wait $!
```
This bash script is what is called via the CMD in my Dockerfile

When running docker stop, I don't see Caught SIGTERM signal!

I'm running docker version 1.7.0

**Comment by cpuguy83** [comment]
This is because of sleep. The process doesn't receive the signal until after your sleep is received (nothing to do with docker).
Notice if you ctrl+c (which is SIGINT) out of the sleep it will show your message from the TERM handler.
if you do:

```bash
while true; do
    sleep 1
done
```
 And then send sigterm, you'll get your signal handler.

Closing as this is a non-issue.

**Comment by k2xl** [comment]
@cpuguy83  - If I add an "&" at the end of sleep, like
```sleep 100000 &```
Shouldn't then the trap get caught? Because it isn't for me

**Comment by cpuguy83** [comment]
That also works for me.

**Comment by k2xl** [comment]
It is definitely not working for me... Can you share what your dockerfile looks like?

**Comment by k2xl** [comment]
```
#!/bin/bash
_term() { 
  echo "Caught SIGTERM signal!" 
}
trap _term SIGTERM
echo "hi"
sleep 100000 &
echo "waiting..."
wait $!
```
This is what I'm running...  I never see Caught SIGTERM signal.

**Comment by cpuguy83** [comment]
```Dockerfile
FROM debian:jessie
ADD test.sh /test.sh
```

```bash
#!/bin/bash

_term() {
  echo "Caught SIGTERM signal!"
}
trap _term SIGTERM
echo "hi"
sleep 1000000 &
wait $!
```

```bash 
$ docker build -t test .
<!-- output supressed -->
$ docker run -it --rm test /test.sh
```
```bash
# in other terminal
$ docker kill -s TERM $(docker ps -lq)
```

**Comment by k2xl** [comment]
@cpuguy83  what happens when you run docker stop <id> instead of docker kill? Do you see the same output?

**Comment by cpuguy83** [comment]
@k2xl `docker stop` == `docker kill -s TERM + docker kill -s KILL`

And yes, same thing. Works.
