### ISSUE TITLE
Linux Artifacts from Ubuntu in an empty Docker Container

### ISSUE THREAD

**Issue by weranga-k** [docker/docker#15410]
Hello,
I have a question regarding the Linux artifacts from Ubuntu that appeared to be in empty Docker containers. Does anyone encountered this issue before? OR Does anyone have the list of Linux artifacts that included in an empty Docker container? 
Thank you in advance. 
Regards, Weranga

**Comment by cpuguy83** [comment]
Can you explain what you mean. What artifacts did you see?
What is an "empty" container? Since a container can't really be empty as it needs something to run.

**Comment by weranga-k** [comment]
The issue was posted on here; https://mjg59.dreamwidth.org/36312.html

Lets assume I have a working installation of Docker on Ubuntu. Now I want to create a container (empty) to deploy my own application. What I meant by empty is, that nothing is downloaded or installed on the container yet. As this moment do we have any Linux libraries in it? 

I'm trying to understand the issue based on the article. Is there a way that I can see what's inside of a docker container right after it's created?

Thank you in advance,

Weranga

**Comment by bronzdoc** [comment]
@weranga-k check the <code>-t</code> <code>-i</code> flags that you can pass to <code>docker run </code> to interact with your container.
i.e <code> docker run -it ubuntu/image /bin/bash </code> 

https://training.docker.com/

**Comment by cpuguy83** [comment]
@weranga-k No, there are no linux libraries except what you add to the image/container yourself (or inherited from a base image).
Absolutely nothing is taken from the host OS.

**Comment by weranga-k** [comment]
Thank you for your replies. Appreciate it.

**Comment by weranga-k** [comment]
Thank you..
