### ISSUE TITLE
docker ps image ID too wide

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#15418]
When an image ID is displayed in `docker ps` instead of a name, the output shows the full ID instead of ID[:12]
![screen shot 2015-08-07 at 5 10 51 pm](https://cloud.githubusercontent.com/assets/799078/9146028/47e233a2-3d27-11e5-8ed7-28a2f1aaa5ca.png)

**Comment by shishir-a412ed** [comment]
@cpuguy83 Looks fine to me. `docker ps` shows me ID[:12].
Can you give an example to reproduce this issue ?

**Comment by cpuguy83** [comment]
I'm seeing this on master

**Comment by shishir-a412ed** [comment]
@cpuguy83 
I am obviously missing something really trivial !
This is what I did on master branch:

1) `docker images` : Copied the image id for fedora image (IMG_ID)
2) `docker run -it IMG_ID /bin/bash`
3) `docker ps` shows me ID[:12] under IMAGE.

**Comment by MHBauer** [comment]
I have some entries with long full image IDs. I also see short ones. I am not sure how; attempting to repro.

**Comment by MHBauer** [comment]
example:
`$ docker run ubuntu /bin/bash`
`$ docker run d2a0ecffe6fa4ef3de9646a75cc629bbd9da7eead7f767cb810f9808d6b3ecb6 /bin/bash`
`$ docker run d2a0ecffe6fa4ef3de9646a75cc629bbd9da7 /bin/bash`
`$ docker run d2a0ecffe6fa4 /bin/bash`
`$ docker ps -n 4`
`CONTAINER ID        IMAGE                                                              COMMAND             CREATED             STATUS                      PORTS               NAMES`
`0218c442f1ea        d2a0ecffe6fa4                                                      "/bin/bash"         21 seconds ago      Exited (0) 20 seconds ago                       backstabbing_stallman3`
`bb1bc966a5d5        d2a0ecffe6fa4ef3de9646a75cc629bbd9da7                              "/bin/bash"         25 seconds ago      Exited (0) 24 seconds ago                       jolly_mestorf9`
`653f4c4e3664        d2a0ecffe6fa4ef3de9646a75cc629bbd9da7eead7f767cb810f9808d6b3ecb6   "/bin/bash"         29 seconds ago      Exited (0) 27 seconds ago                       determined_kilby`
`ef66af130ea2        ubuntu                                                             "/bin/bash"         38 seconds ago      Exited (0) 36 seconds ago                       sad_ptolemy`

**Comment by shishir-a412ed** [comment]
@MHBauer 
okay so the `IMAGE` in output is what you passed in `docker run`.
If you passed the full ID, full ID gets displayed. If you pass ID[:12], ID[:12] gets displayed.

Seems correct to me.
@cpuguy83 what do you want to do ? Change it to ID[:12] for all cases.

**Comment by maaquib** [comment]
@shishir-a412ed If you are not working on this I'd like to give it a shot

**Comment by shishir-a412ed** [comment]
@maaquib absolutely ! it's all yours.

**Comment by maaquib** [comment]
#dibs

**Comment by cpuguy83** [comment]
Yeah I think this should be id[:12] when not using --no-trunc... Since 12 is enough to get the image.
