### ISSUE TITLE
Cannot utilise previous defines in an single ENV block

### ISSUE THREAD

**Issue by JBodkin** [docker/docker#15419]
If you attempt to declare and re-use an environment variable declared in one single`ENV` command, the usages of that environment variable are not substituted correctly.

#### Example

````
ENV \
    MYSQL_VERSION="5.1.36" \
    MYSQL_ARCHIVE="https://cdn.mysql.com/Downloads/Connector-J/mysql-connector-java-${MYSQL_VERSION}.tar.gz"
````

#### Expected

The environment variable MYSQL_ARCHIVE should be built using the previously defined MYSQL_VERSION environment variable.

#### Affects

version 1.7.1, build 786b29d

**Comment by phemmer** [comment]
Dup of #15083 & #14914

Though maybe if they get enough requests, it'll change. :-)

**Comment by duglin** [comment]
see @phemmer's comment  :-(
