### ISSUE TITLE
Broken Links in Docs

### ISSUE THREAD

**Issue by ankushagarwal** [docker/docker#15415]
Crawled the latest docs on master for broken links and found the following :

CC : @moxiegirl @thaJeztah 

- [ ] **Broken Link** : http://docs.docker.com/terms/image/ , **Source Page** : http://docs.docker.com/articles/baseimages/
- [ ] **Broken Link** : http://docs.docker.com/terms/layer/ , **Source Page** : http://docs.docker.com/userguide/dockervolumes/
- [ ] **Broken Link** : http://docs.docker.com/v1.1/articles/host_integration/ , **Source Page** : http://docs.docker.com/articles/host_integration/
- [ ] **Broken Link** : http://docs.docker.com/misc/introduction/understanding-docker.md , **Source Page** : http://docs.docker.com/misc/
- [ ] **Broken Link** : http://docs.docker.com/reference/commandline/daemon/run.md , **Source Page** : http://docs.docker.com/reference/commandline/daemon/
- [ ] **Broken Link** : http://docs.docker.com/reference/run/reference/logging/overview.md , **Source Page** : http://docs.docker.com/reference/run/
- [ ] **Broken Link** : http://docs.docker.com/reference/api/docker_remote_api_v1.13/ , **Source Page** : http://docs.docker.com/reference/api/docker_remote_api/
- [ ] **Broken Link** : http://docs.docker.com/reference/api/docker_remote_api_v1.12/ , **Source Page** : http://docs.docker.com/reference/api/docker_remote_api/
- [ ] **Broken Link** : http://docs.docker.com/reference/api/docker_remote_api_v1.10/ , **Source Page** : http://docs.docker.com/reference/api/docker_remote_api/
- [ ] **Broken Link** : http://docs.docker.com/reference/api/docker_remote_api_v1.8/ , **Source Page** : http://docs.docker.com/reference/api/docker_remote_api/
- [ ] **Broken Link** : http://docs.docker.com/reference/api/docker_remote_api_v1.11/ , **Source Page** : http://docs.docker.com/reference/api/docker_remote_api/
- [ ] **Broken Link** : http://docs.docker.com/reference/api/docker_remote_api_v1.9/%23attach-to-a-container%20%22POST%20/containers/(id , **Source Page** : http://docs.docker.com/reference/api/docker_remote_api/
- [ ] **Broken Link** : http://docs.docker.com/reference/api/docker_remote_api_v1.9/ , **Source Page** : http://docs.docker.com/reference/api/docker_remote_api/
- [ ] **Broken Link** : http://docs.docker.com/reference/api/docker_remote_api_v1.5/ , **Source Page** : http://docs.docker.com/reference/api/docker_remote_api/
- [ ] **Broken Link** : http://docs.docker.com/reference/api/docker_remote_api_v1.3/ , **Source Page** : http://docs.docker.com/reference/api/docker_remote_api/
- [ ] **Broken Link** : http://docs.docker.com/reference/api/docker_remote_api_v1.4/ , **Source Page** : http://docs.docker.com/reference/api/docker_remote_api/
- [ ] **Broken Link** : http://docs.docker.com/reference/api/docker_remote_api_v1.6/ , **Source Page** : http://docs.docker.com/reference/api/docker_remote_api/
- [ ] **Broken Link** : http://docs.docker.com/reference/api/docker_remote_api_v1.2/ , **Source Page** : http://docs.docker.com/reference/api/docker_remote_api/
- [ ] **Broken Link** : http://docs.docker.com/reference/api/docker_remote_api_v1.7/ , **Source Page** : http://docs.docker.com/reference/api/docker_remote_api/
- [ ] **Broken Link** : http://docs.docker.com/reference/api/docker_remote_api_v1.1/ , **Source Page** : http://docs.docker.com/reference/api/docker_remote_api/
- [ ] **Broken Link** : http://docs.docker.com/reference/api/docker_remote_api_v1.0/ , **Source Page** : http://docs.docker.com/reference/api/docker_remote_api/

**Comment by MHBauer** [comment]
I know some of these are fixed already in master because I worked on the FAQ links. What did you run to get these results? Can you run it against the server that runs when `make docs` is called?

**Comment by thaJeztah** [comment]
@ankushagarwal could this be related to https://github.com/docker/docs-base/issues/120#issue-99591569 (and https://github.com/docker/distribution/pull/818)?

**Comment by moxiegirl** [comment]
@ankushagarwal  thank you for the contribution. @MHBauer is correct some of these are outdated and have already been fixed.  

I appreciate the help but some of the issues you are seeing is because we are in the process of internally  revising how we release documentation.  Without access to our servers, some of these actually can't be fixed.   I appreciate you making this available though for the ones that can be fixed.

**Comment by ankushagarwal** [comment]
@MHBauer : I used a ruby web crawler to crawl the site and spit out broken links, will push the source code soon. I'll try to run it on the master and update the list.

@thaJeztah : I am not sure. The production docs run an older version and this PR you're referencing was merged recently.

@moxiegirl : Thanks for the update. I'll try to update the list with what's on master rather than production. I think that a significant chunk of these links might be fixable without the internal servers.

**Comment by ankushagarwal** [comment]
Ran it on master and found only 21 broken links 😅 !
Manually filtered out some links which are not *actually* broken.

**Comment by thaJeztah** [comment]
@ankushagarwal awesome work! Thanks!

**Comment by MHBauer** [comment]
Sweet, I think #15411 fixes most of the api links.

**Comment by calavera** [comment]
Yep, closing this as fixed. Thanks!
