### ISSUE TITLE
https://test.docker.com/ exits with Exit Code 2

### ISSUE THREAD

**Issue by BenHall** [docker/docker#15425]
The test script runs a function called check_forked. 

This checks to see the OS version. On my 14.04 and 15.04 this results in the script exiting with an error code 2 and no output. This is the same output as when running form cmd (see below). 

Shouldn't this be run as a subshell command so that it doesn't terminate the main shell when it fails?

```
# lsb_release -a -u
Usage: lsb_release [options]

lsb_release: error: no such option: -u
root@ns3001358:~# echo $?
2
```

If I remove this then the script runs as expected.

```
# uname -a
Linux ns3001358.ip-37-59-48.eu 3.13.0-61-generic #100-Ubuntu SMP Wed Jul 29 11:21:34 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
# cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"
NAME="Ubuntu"
VERSION="14.04.3 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.3 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

**Comment by BenHall** [comment]
It looks like the `set -e` at the top causes any non-zero command to stop the entire process

**Comment by thaJeztah** [comment]
Thanks for reporting @BenHall 

ping @fmoliveira @jfrazelle @tianon hmf

**Comment by fmoliveira** [comment]
Thanks for reporting @BenHall @thaJeztah 

I'll check it!

**Comment by fmoliveira** [comment]
Thanks for reporting @BenHall @thaJeztah !

I'll check @BenHall fix in the referenced pull request.
