### ISSUE TITLE
enhancement request: allow substitution of ultimate image id for image tag to better enable pinning image versions

### ISSUE THREAD

**Issue by mattgiles** [docker/docker#15432]
I have on a couple of occasions been caught off guard by unexpected upstream changes to official docker images. For instance, as a result of [this PR](https://github.com/docker-library/postgres/pull/75). And it can be frustrating when production or build systems run into trouble using Dockerfiles that are under source control, that haven't changed in months, and that, moreover, derive from official images.

Which leads to a general question about the best way to pin docker image versions, when docker tags are frequently used to indicate software release (e.g. postgres:9.4) instead of being used to enforce version control. As it stands the best way seems to be to fork the underlying git repository---which feels heavy handed and against the spirit of having something like docker hub.

If it were possible to substitute something like `FROM postgres:730d1d72bda2` for something like `FROM postgres:9.4` that would seem to me to be a relatively straightforward way to allow users to voluntarily opt in to upstream changes.

**Comment by thaJeztah** [comment]
This is actually possible by referencing an image by "digest", for reference, see https://github.com/docker/docker/blob/master/docs/reference/builder.md#from and https://github.com/docker/docker/blob/7201127cfb2517f0c0be8f72355407e577882779/docs/reference/commandline/images.md#listing-image-digests

**Comment by mattgiles** [comment]
tremendous. thanks very kindly @thaJeztah.

**Comment by thaJeztah** [comment]
You're welcome! If you think it needs a better mention in the documentation, or it's missing in some part of the documentation, please let us know as well (we always welcome feedback :-))
