### ISSUE TITLE
Where do the Machine install docs live?

### ISSUE THREAD

**Issue by thieman** [docker/docker#15448]
I'm trying to figure out how to submit a fix to the docs hosted here: https://docs.docker.com/machine/#installation

This page is currently pointing to an old version of Docker Machine (0.3.0) which doesn't support the latest version of VirtualBox, so if you follow the instructions here you run into errors pretty much immediately. I'd like to contribute a fix, but I can't seem to find the source for this page in either docker/docker or docker/machine. Where does this stuff live?

**Comment by cpuguy83** [comment]
Machine docs are here: https://github.com/docker/machine/tree/master/docs

Thanks!

**Comment by thieman** [comment]
@cpuguy83 Can I request a rebuild of the docs on docs.docker.com then? The version of the docs on master in that repo look fine, but the live docs are waaaaaay behind that, and it's affecting end users. Specifically, it looks like the current live version is at least as old as this commit from July 7: https://github.com/docker/machine/commit/39806c02e0859463ac50ff346102edb2d860f168

cc @moxiegirl who I understand may be mistress of all things documentation

**Comment by cpuguy83** [comment]
We're doing a release tomorrow (assuming no show stoppers), which would also include a docs update.

**Comment by thieman** [comment]
:+1:
