### ISSUE TITLE
run DockerSuite.TestRunWithBlkioInvalidWeight failed in localhost

### ISSUE THREAD

**Issue by azurezk** [docker/docker#15443]
I found  "WARN[0000] Your kernel does not support cgroup blkio weight " in docker daemon debug info 
Maybe this testcase should add a requirement that an environment supports cgroup blkio weight?

**Comment by coolljt0725** [comment]
Add a requirement for this make sense just as we do on test `cpu-quota`  https://github.com/docker/docker/blob/master/integration-cli/docker_cli_run_unix_test.go#L253 
Working on a PR.

**Comment by cpuguy83** [comment]
Closing as it looks like this was added here: https://github.com/docker/docker/commit/ddf220a1d3af71519e742b2a5e6e31701eeb51f4
