### ISSUE TITLE
Docs: Incorrect Link to Dockerfile Best Practices

### ISSUE THREAD

**Issue by mtimkovich** [docker/docker#15453]
On the page https://docs.docker.com/reference/builder, the links for Dockerfile Best Practices link to

https://docs.docker.com/reference/reference/articles/dockerfile_best-practices

instead of

https://docs.docker.com/articles/dockerfile_best-practices/

I've seen this on some other pages as well where it links to "reference/reference" instead of the correct location.

**Comment by MHBauer** [comment]
Already fixed in master. Docs get pushed at the next release, I think?

**Comment by thaJeztah** [comment]
Yup, this is resolved now, thanks for reporting!
