### ISSUE TITLE
The CentOS installation instructions should use systemctl and both start and enable docker

### ISSUE THREAD

**Issue by exarkun** [docker/docker#15456]
The CentOS installation instructions at https://docs.docker.com/docker/installation/centos/ (`docs/installation/centos.md`) suggest that after installing the package one should:

```
4. Start the Docker daemon.

                $ sudo service docker start
```

`service` is a thin layer on top of systemctl on CentOS.  And starting a systemctl service is only half the job.  After a reboot, the service will be stopped again.  To make it run on every boot, it needs to be "enabled" as well:

```
    sudo systemctl enable docker
    sudo systemctl start docker
```

**Comment by LK4D4** [comment]
ping @thaJeztah
