### ISSUE TITLE
docker run --rm documentation should indicate whether volumes are removed

### ISSUE THREAD

**Issue by posita** [docker/docker#15455]
It's not clear from any documentation that I can find whether `docker run --rm` is equivalent to doing a `docker rm -v` on the created container. Caveat: I usually can't find the mustard in the fridge because I'm looking everywhere *except* right in front of me.

**Comment by posita** [comment]
Ignoring @GordonTheTurtle spam. This is a documentation bug.

**Comment by thaJeztah** [comment]
@posita are you interested in contributing, and creating a pull request to improve the documentation? The markdown files used to generate the documentation can be found in this repository. I think an appropriate location to add this information is here; https://github.com/docker/docker/blob/master/docs/reference/run.md#clean-up---rm
