### ISSUE TITLE
Volumes specified in Dockerfiles are mounted using VolumeDriver

### ISSUE THREAD

**Issue by clintonskitson** [docker/docker#15467]
There can be a condition where volumes are created inadvertently when using the new VolumeDriver functionality.

If a Dockerfile includes a ```volumes``` parameter, these volumes are created using the applicable VolumeDriver.  The default case is ```local```, but is overridden by ```--volume-driver``` at runtime.  If you are running something like ```docker run -ti --name mysql7 -p 3306:3306 -e MYSQL_PASS="87654321" --volume-driver=rexray -v wpmsql01c:/var/lib/mysql tutum/mysql``` then there will be an additional volume created since the ```tutum/mysql``` container includes two ```volumes``` in the ```Dockerfile```.

Spoke with @calavera about this, and currently the volumes specified in the Dockerfile should always default to using the ```local``` driver for volumes.  This should be overwritten by volumes specified with the ```-v``` flag.

**Comment by cpuguy83** [comment]
I believe this can be closed?
I'm not a huge fan of this change since the use case here is probably 50% on one side, 50% on the other... but in any case it seems like #15507 resolved this?

**Comment by clintonskitson** [comment]
Correct, this is fixed now.
