### ISSUE TITLE
Remote API doc has broken image link

### ISSUE THREAD

**Issue by fredlf** [docker/docker#15461]
https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api.md

Has a broken image link at ln. 50.

**Comment by Evalle** [comment]
hello @fredlf AFAIK these .md file are used for creating official docs pages, and you can check out that on the official docs page https://docs.docker.com/docker/reference/api/docker_remote_api/ image is on it's place. @moxiegirl please correct me if I'm wrong.

**Comment by moxiegirl** [comment]
@fredlf @Evalle Sorry for the confusion folks. The page should be: https://docs.docker.com/reference/api/docker_remote_api/ --- the link with extra `/docker/` in the path was an artifact of our change to the build system in June.

The https://docs.docker.com/reference/api/docker_remote_api/ page is showing the image.  Let me know if you spot any problems.

**Comment by fredlf** [comment]
Cool. LGTM.
