### ISSUE TITLE
how to change the max EndPortRange

### ISSUE THREAD

**Issue by membphis** [docker/docker#15468]
we use nginx in docker. and we found the container cant support more than 16000 connections. we tried the `--EXPOSE` and `--net=host`, but the limit is still here. we sure we have changed the ulimit successful. 

we found the nginx server only can use valid port 49153-65535.

our system is RHEL 6.5, the docker version is 1.5 docker.io .

**Comment by cpuguy83** [comment]
Hello, is this still a problem?
Note that we don't support RHEL/Centos < 7.0

Closing for now. Please ping if you still have an issue.
Likely this will be support related, so please ping on #docker on IRC, the docker-user ML, or forums.docker.com

Thanks!

**Comment by cpuguy83** [comment]
Also, sorry, re-read this again. You can change the port end range by setting the kernel ephemeral port range under `/proc/sys/net/ipv4/ip_local_port_range`
