### ISSUE TITLE
docker storage option not working in 1.7.1 version

### ISSUE THREAD

**Issue by abilashks** [docker/docker#15476]
i upgraded my docker to 1.7.1 version.
when i tried to start the service i get the below error
msg="Error starting daemon: error initializing graphdriver: Unknown option dm.loopmetadatasize"

docker version
Client version: 1.7.1
Client API version: 1.19
Package Version (client): docker-1.7.1-108.el7.centos.x86_64
Go version (client): go1.4.2
Git commit (client): 3043001/1.7.1
OS/Arch (client): linux/amd64
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?

uname -a
Linux localhost 3.10.0-123.el7.x86_64 #1 SMP Mon Jun 30 12:09:22 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

storage option was working fine in 1.6.2 version. we face this issue in all our docker machines for 17.1 version.

Any idea?

**Comment by nwind21** [comment]
I also have the same issue.  None of the dm.options such a thinpool, fs, metadatadev are recognized.

I did a clean install on a VM of Docker 1.7.1 and inspected the docker-storage configuration and the usage has not changed.

I did a yum downgrade to 1.6.2-14.el7.centos and the flags work fine.

**Comment by cpuguy83** [comment]
Have you explicitly set `-s devicemapper`?

**Comment by nwind21** [comment]
No, I did not.  I'll try it on another Vagrant in a couple days and let you know, I'm going to work with the 1.6.2 for now.

**Comment by abilashks** [comment]
nope din't set that option

**Comment by cpuguy83** [comment]
If you can repro with explicitly setting `-s devicemapper` please ping here and we can take a look.
Closing for now.
Thanks!

**Comment by maniagnihotri** [comment]
@cpuguy83 I tried and here is the result.

**Comment by maniagnihotri** [comment]
@cpuguy83  Where should I add "-s devicemapper" in docker configuration file (/etc/sysconfig/docker)

**Comment by nwind21** [comment]
FYI, I added the -s devicemapper to the /etc/sysconfig/docker file as part of OPTIONS and as you suspected, that resolved the issue.

Thanks.
