### ISSUE TITLE
Is dockerhub down?

### ISSUE THREAD

**Issue by sbutalia** [docker/docker#15470]
![image](https://cloud.githubusercontent.com/assets/1808387/9187345/464edc2a-3f84-11e5-8527-4548bb39c072.png)

**Comment by Pensu** [comment]
It's working fine for me. May be, some network issue within your environment?

**Comment by thaJeztah** [comment]
You can check via https://status.docker.com

However; I'm going to close this issue, because this issue tracker is for bugs and feature requests for Docker. Docker Hub is managed by a different team and issues can be reported via https://support.docker.com
