### ISSUE TITLE
Cannot start full systemd container with lxc driver.

### ISSUE THREAD

**Issue by dancewhale** [docker/docker#15477]
Description of problem:
Cannot start /sbin/init  within the container with lxc driver.
You can start  /sbin/init in docker with the native driver:
docker run  -it -privileged -e "container=docker" ubuntu:init /sbin/init

However, it does not work for the lxc driver:
docker run -it -privileged -e "container=docker"  ubuntu:init  /sbin/init
No response from the output, and the container is not started.

`docker version`:
Client:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   15cb7df-dirty
 Built:        Wed Jul 22 07:43:16 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.0-dev
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   15cb7df-dirty
 Built:        Wed Jul 22 07:43:16 UTC 2015
 OS/Arch:      linux/amd64

`docker  info`:
Containers: 18
Images: 88
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 228
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-15-generic
Operating System: Ubuntu 15.04
CPUs: 1
Total Memory: 976.6 MiB
Name: ubuntu
ID: 6CKH:DHL3:FSVK:NBWN:ZVYE:DIK3:QOQJ:3JHF:3DON:4F42:2LAZ:3KDM
WARNING: No swap limit support

`uname -a`:
Linux ubuntu 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

How reproducible
100%

Steps to Reproduce:
1.You can start /sbin/init in docker with native driver:
docker -d 
docker run -it --privileged -e "container=docker"  ubuntu:init /sbin/init

2.You can't start /sbin/init in docker with lxc driver,there is nothing put out with lxc driver:
docker -d -e lxc
docker run -it --privileged -e "container=docker"  ubuntu:init /sbin/init

**Comment by icecrime** [comment]
As notified in our [deprecation notice](https://github.com/docker/docker/blob/d023d5a8a24c18e912162c2f4c724cfb21028301/docs/misc/deprecated.md#lxc-built-in-exec-driver), Docker 1.10.0 will drop support for the LXC exec driver (#17700).

Thank you for the report, I'm now closing this.
