### ISSUE TITLE
fluentd-address is not used.

### ISSUE THREAD

**Issue by PharaohKJ** [docker/docker#15475]
Description of problem:

fluentd-address is not used in `/etc/default/docker`.

`docker version`:

```
docker -v
Docker version 1.8.0-rc3, build ba509ce
```

`docker info`:

```
~# docker info
Containers: 3
Images: 15
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 21
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: fluentd
Kernel Version: 3.16.0-0.bpo.4-amd64
Operating System: Debian GNU/Linux 7 (wheezy)
CPUs: 1
Total Memory: 3.625 GiB
Name: dockertest
ID: SGFS:BJIA:ZTJC:BG52:4LKM:K62T:Q7FL:AT2K:ZS7D:3ZPN:JQLP:N3FP
WARNING: No memory limit support
WARNING: No swap limit support
```

`uname -a`:

```
~# uname -a
Linux dockertest 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt11-1~bpo70+1 (2015-06-08) x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.):

on GCE Instance.

How reproducible:

Steps to Reproduce:
1. `gcloud compute instances create dockertest`
2. `gcloud compute ssh dockertest`
3. `sudo su -`, `curl -sSL https://test.docker.com | sh`
4. `vi /etc/default/docker` append this `DOCKER_OPTS="--log-driver=fluentd --log-opt fluentd-address=10.10.10.10:24224 --log-opt fluentd-tag=ownservice.docker.service_env"`
5. `/etc/init.d/docker restart`
6. `docker run ubuntu:latest /bin/bash`

Actual Results:

```
Error response from daemon: Cannot start container 4f5af807bec6f54da2ab429d362739fa78c5d0ee2b84df14c833151c0a967bdf: Failed to initialize logging driver: dial tcp 127.0.0.1:24224: connection refused
```

Expected Results:

'tcp 127.0.0.1:24224' is wrong. I want to use DOCKER_OPTS values ( 
`--log-opt fluentd-address=10.10.10.10:24224 --log-opt fluentd-tag=ownservice.docker.service_env` ).

Additional info:

If I do not use `/etc/default/docker` then address and tag are correct.

```
~# docker run --log-driver=fluentd --log-opt fluentd-address=10.10.10.10:24224 --log-opt fluentd-tag=prairiestack.docker.service_env ubuntu:latest /bin/bash
WARNING: Your kernel does not support memory swappiness capabilities, memory swappiness discarded.
Error response from daemon: Cannot start container addad7199b580f35f90d383062df471f4ca037a4ff4149d78b248a3160f629f2: Failed to initialize logging driver: dial tcp 10.10.10.10:24224: i/o timeout
```

**Comment by LK4D4** [comment]
@PharaohKJ any other DOCKER_OPTS works?

**Comment by PharaohKJ** [comment]
@LK4D4 may be works. I was checked in `ps ax`

```
~# ps ax|grep docker
 7137 ?        Sl     0:00 /usr/bin/docker daemon -p /var/run/docker.pid --log-driver=fluentd --log-opt fluentd-address=10.10.10.10:24224 --log-opt fluentd-tag=ownservice.docker.service_env
```

**Comment by gondor** [comment]
@LK4D4 I'm seeing the same thing with GELF.  I've added the --log-opt gelf-address=udp://host:ip and it gives me a message starting a container from the daemon that the address is not defined.  Like FluentD it shows up in the ``ps ax | grep docker``.     When I don't include this in the daemon and specify them via `docker run`  it works fine.   This is not ideal since I'm using Mesos and would like the daemon to control this for all tasks.

**Comment by kiyoto** [comment]
cc: @tagomoris

**Comment by gondor** [comment]
@mariussturm Should I open up a separate ticket for Gelf?  Seems to be an argument issue related to both new logging drivers since I'm seeing the same with Gelf.

**Comment by mariussturm** [comment]
I am following this one here. Will take a look!

**Comment by thaJeztah** [comment]
gelf issue is in https://github.com/docker/docker/issues/15509

**Comment by thaJeztah** [comment]
Closing. This should be resolved by https://github.com/docker/docker/pull/15611, which will be in the 1.8.2 release
