### ISSUE TITLE
Ubuntu 15.04 start coutdown when shutdown the pc.

### ISSUE THREAD

**Issue by beinnova** [docker/docker#15484]
Hello,
I have upgrade my Ubuntu to 15.04 version. Now, when I'm shutting down the pc, I see in a console the countdown of docker daemon.
I can disable the countdown?

**Comment by cpuguy83** [comment]
I'm not sure what you mean by a countdown. Docker is not doing a countdown, though it does try to stop all containers on exit, which can take as much as 10 seconds before it gives up.
If the containers you run are ignoring SIGTERM, it will take the full 10 seconds.
