### ISSUE TITLE
Docker is not smart enough to identify new version available on PyPI

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [docker/docker#15486]
My dockerfile is using lasio (RUN pip install lasio), in the script I'm checking the version (``lasio version: 0.7.3``) on the PyPI (https://pypi.python.org/pypi/lasio version 0.7.6 is available).

So docker -build is making me working with old version which is **not good** as we are loosing trust of docker and push us to rebuild all the images without cache to manually manage the intelligence of update.

My docker info, version, etc. was published yesterday in another post: https://github.com/docker/docker/issues/15469

Please do automatic and smart, not bot stupid :)

**Comment by unclejack** [comment]
@VelizarVESSELINOV RUN is as simple as running something in a shell script, it's not aware of what you're running in there and whether it should be invalidated.
This can be solved quite easily using `docker build --no-cache`.

Furthermore, you can check what version you've had in the previous image and use `--no-cache` to force the entire image to be built.

The Docker builder will be moved to the client side and that means it's going to be possible to extend it to do more. The Docker builder which currently exists inside the Docker daemon isn't going to be changed in any way to add any new functionality.

This isn't a bug. I'm going to close this now. Please feel free to comment.

**Comment by VelizarVESSELINOV** [comment]
Thank you for your inspired advice and promotion for usage ``--no-cache`` as the Docker cache is not smart enough, I understand this is outside your management boundaries (the fault is somewhere else :+1:)

**Comment by VelizarVESSELINOV** [comment]
Even worst randomly is updating packages that was not updated since 2 years, like https://pypi.python.org/pypi/cchardet/ looks like a joke outside Docker :)
