### ISSUE TITLE
Default container names

### ISSUE THREAD

**Issue by luca3m** [docker/docker#15480]
Working with containers I don't like default names used by docker, because they are hard to remember and also ids. I need to use `--name` parameter every time, what do you think if by default docker uses the image name as container name? If it's already used it can add a suffix like `redis1` `redis2` etc.

I think it's more predictable and easy to use.

**Comment by cpuguy83** [comment]
This is precisely what compose does (or rather, uses the name of the `service`).
I don't think we want to change Docker.

**Comment by luca3m** [comment]
Yes I know. But I don't think that anybody using Docker uses always docker-compose to bootstrap containers. For example to try out some new stuff.

**Comment by cpuguy83** [comment]
This should be up to the system orchestrating docker, not Docker itself.
Docker already provides a set of names which really should not be determined based on image name in the general case.
