### ISSUE TITLE
undefined reference

### ISSUE THREAD

**Issue by RustJason** [docker/docker#15488]
```
/usr/lib/x86_64-linux-gnu//libselinux.a(label_file.o): In function `closef':
(.text+0x136): undefined reference to `pcre_free'
/usr/lib/x86_64-linux-gnu//libselinux.a(label_file.o): In function `closef':
(.text+0x13f): undefined reference to `pcre_free_study'
/usr/lib/x86_64-linux-gnu//libselinux.a(label_file.o): In function `compile_regex.isra.5':
(.text+0x25e): undefined reference to `pcre_compile'
/usr/lib/x86_64-linux-gnu//libselinux.a(label_file.o): In function `compile_regex.isra.5':
(.text+0x27f): undefined reference to `pcre_study'
/usr/lib/x86_64-linux-gnu//libselinux.a(label_file.o): In function `lookup':
(.text+0x4ca): undefined reference to `pcre_exec'
/usr/lib/x86_64-linux-gnu//libselinux.a(label_file.o): In function `lookup':
(.text+0x542): undefined reference to `pcre_exec'
collect2: error: ld returned 1 exit status
make[1]: *** [dmsetup.static] Error 1
make[1]: Leaving directory `/usr/local/lvm2/tools'
make: *** [tools.device-mapper] Error 2

```

I add -lpcre and -L{lib_to_pcre.so}, but still not work

**Comment by Pensu** [comment]
@Red-wolf-s-husband Did you try building static library for pcre? I had the similar issue, I used static library and that resolved it for me.

**Comment by Red-wolf-s-husband** [comment]
@Pensu How? I build this error occurs when I try to build lvm2.

**Comment by Pensu** [comment]
@Red-wolf-s-husband Try installing pcre-static and pcre-devel packages. That should resolve the issue for you.

**Comment by sqleejan** [comment]
I have installed pcre-static and pcre-devel packages,But The same error occurs when I try to build lvm2

**Comment by Pensu** [comment]
@sqleejan Can you paste here the commands you have been using to build lvm2?

**Comment by Red-wolf-s-husband** [comment]
pcre-static and pcre-devel are only for centos. Ubuntu can't install that

**Comment by Pensu** [comment]
@RustJason they would be there by some other name. Just search there repo. Most probably, only dev, no devel.

**Comment by RustJason** [comment]
@Pensu tryed, don't work

**Comment by thaJeztah** [comment]
@RustJason I'm going to close this issue, because this is not really a bug in Docker, but a support question. However, feel free to continue the discussion here or ask for support in the #docker-dev IRC channel
