### ISSUE TITLE
Add labels to running Docker containers

### ISSUE THREAD

**Issue by astrostl** [docker/docker#15496]
Howdy,

I'm unable to identify a mechanism from either https://docs.docker.com/docker/userguide/labels-custom-metadata/ or the `docker` cli `help` which would let me add, change, and/or delete labels on *running* Docker containers. Would like to use this metadata on multi-tenant hosts, as opposed to doing it out-of-band (e.g. a key/value store which also references running container IDs).

If this feature does exist, could someone point me toward it? If not, requesting it.

Thanks!

**Comment by abronan** [comment]
You can only add labels when creating a container and search based on those labels. I don't think that there is any mechanism as of now to delete/update a key and use it as a primitive key/value store inside the container to store metadata. Not sure if this is something that will be added in a near future though.

/cc @icecrime @tiborvass

**Comment by phemmer** [comment]
I recall seeing discussion on this idea back when labels were being considered, and it was rejected because: currently, there is no method to modify a running container (no api call, and nothing like a `docker update` command). Adding this capability would be a very slippery slope as then it becomes "well, we can update labels, why not X, or why not Y?".

**Comment by thaJeztah** [comment]
I think it was previously proposed as "annotations" in https://github.com/docker/docker/pull/9013, which was closed after the labels were implemented, but it's not fully rejected, but awaits a new proposal; see https://github.com/docker/docker/pull/9013#issuecomment-88178441

**Comment by abronan** [comment]
OK, I think it makes sense overall to allow to update and remove labels on containers. We want to be able to do this for the *Engine* daemon (to control and modify a clustered setup for example), so why not for containers? The only downside is indeed that this requires new commands on the CLI and the API, which is an added burden to the overall UI.

@ibuildthecloud linking you to this issue as you are the author of the `label` feature. WDYT about updating/removing labels on containers? Do you think a proposal would make its way through? Just to make sure efforts are not wasted in trying to enhance the current labeling system :smile:

**Comment by aanm** [comment]
@abronan
If changing labels will be possible I propose that a docker event will be triggered if that happens.

**Comment by abronan** [comment]
@aanm Yes, events are the closest we can get to watch events (if we are thinking of labels as a very lightweight KV alternative). That would be convenient for numbers of scenarios: Temporarily tag a container or an image, trigger an event and have a monitoring process watching on a particular tag do something with this container: migrate/stop/exec/re-schedule or whatever, and finally remove the label. Or just store arbitrary metadata that might be useful for an application consuming the API.

**Comment by gauravphoenix** [comment]
I will appreciate this feature very much

**Comment by tiborvass** [comment]
There, I changed "labels" (sorry couldn't resist)

**Comment by bboreham** [comment]
Referencing #16203 (which is about daemon labels not container labels)

**Comment by amouat** [comment]
Personally, I was surprised to find I couldn't add labels to _images_, never mind containers. This would be very handy for associating stuff like git hashes with images. At the moment you have to use tags, which is a pain as the only way to find all tags is to cross-reference with the image ID.

**Comment by Random-Liu** [comment]
We plan to leverage the docker label to simplify container management.

However, we didn't use that before, so the containers already started have no labels on them. It is unacceptable for us to restart running containers to add labels. So it seems that the best solution is to add labels on the old running containers.

Will this kind of feature be added anytime soon? Or are there any other solutions for this problem with existing docker features?

**Comment by thaJeztah** [comment]
@Random-Liu while I agree this could be useful, it won't help in your case, because this needs an update of Docker, so you'll have to restart your containers anyway (because of updating the daemon)

> Will this kind of feature be added anytime soon? Or are there any other solutions for this problem with existing docker features?

There's an open PR to implement a "set" command, which would allow updating properties of a running container, but it has not been decided on yet; https://github.com/docker/docker/pull/15078

**Comment by Random-Liu** [comment]
@thaJeztah Good point! Thanks very much, :) We should consider some other solutions indeed.

However, this feature will still make it easier for us to manage containers, hope to see this in future docker release one day, :)

**Comment by thaJeztah** [comment]
@Random-Liu true, the discussion is currently whether we want to allow having containers be "mutable" and if so, which properties we want to allow being mutable. Those decisions should not be taken lightly, because they can have quite some impact.

**Comment by aanm** [comment]
@thaJeztah properties being mutable should be easier than containers themselves, no?

**Comment by Random-Liu** [comment]
@thaJeztah If container label is immutable, we may meet some other questions in the future. For example, if we want to add a container label in new version of the system, we have to restart all the old containers. It is really wired. I believe this kind of occasions will not only happen to us. :)

Wait for the good news! Thanks for your help, :)

**Comment by jeanpralo** [comment]
Hey there,

@thaJeztah  I reckon mutables labels would be a great advantage for docker. 

More and more people seems to use labels to store meta-data, this is handy and allow virtually everyone to use a docker-compose.yml without having to extend it with your own ugly keyword or worst create its own new manifest file :)

In my case, I have a couple of auto-discovery things that I do to check which vhosts a proxy should be listenning for my containers. Sometimes those vhosts can change and it would be handy not to have to delete/create a container in that specific case.

I can think of many other things for proxy, firewalling options on exposed ports if you want to open/close some services. 

It will be a good step forward to more dynamic gestion of the containers.

Cheers.

**Comment by jeanpralo** [comment]
and I guess ping @abronan  if this is someting that is beeing discussed at docker or not going to happen ? :)

**Comment by thaJeztah** [comment]
I added the "needs attention" label, with the thought of discussing this together with the https://github.com/docker/docker/pull/15078 PR/Proposal. I think they're closely related (w.r.t deciding immutable/mutable properties)

**Comment by amouat** [comment]
Sorry to pile in again, but I think this is a very important suggestion. It's needed for - as @jeanpralo says - "dynamic management of containers". It provides users with a way to identify and group containers at run-time, which is only going to become more and more important.

If something like this isn't adopted, I believe we will see users turning to messy solutions such as using external k/v stores indexed by container IDs or simply using frameworks like Kubernetes which comes with a similar tool out-of-the-box. (To this end, this suggestion would seem to be extremely relevant to Swarm).

**Comment by bboreham** [comment]
Referencing #9013, where the discussion seemed to cover a lot of the key issues

**Comment by astrostl** [comment]
```I believe we will see users turning to messy solutions such as using external k/v stores indexed by container IDs``` - I opened this issue, and that's more or less what we're doing :) We use CouchDB as a "CMDB" with helper scripts to populate data, but it ain't pretty!

**Comment by astrostl** [comment]
Forgot to say, +1 for *mutable*. I think immutable *options* (e.g. a flag for labels made at runtime) would be great, but I wouldn't like to be locked into it.

**Comment by icecrime** [comment]
I agree we should be able to set labels dynamically. I also agree with @thaJeztah that we _should_ discuss this under the more global umbrella of post-creation updates. Maybe the answer will be that labels are simple enough to be implemented independently of whatever we decide regarding `docker set`, but it's worth looking at the broader picture.

We'll bring up the topic in a future design session with maintainers.

**Comment by ehazlett** [comment]
Adding my +1 to this as well.  I would like to be able to update labels to store dynamic information as well.

**Comment by icecrime** [comment]
Ping @vdemeester who will be looking into it!

**Comment by vdemeester** [comment]
yeah, I'm gonna put a #dibs on that :smile_cat:

**Comment by thaJeztah** [comment]
Pull request for this is here: https://github.com/docker/docker/pull/18958

**Comment by thaJeztah** [comment]
For those interested in this feature; there's still some doubt among some maintainers if labels should actually be mutable (once a container is created, does its meta-data change, or should it only change if the container itself changes?). If you have real-life examples / use-cases that cannot be realized without this feature ("I forgot to set a label" may not be the best example), please add your example on the proposal here: https://github.com/docker/docker/pull/18958

**Comment by astrostl** [comment]
Replied over there.

**Comment by ehazlett** [comment]
Replied as well.  Thx @thaJeztah

**Comment by bamarni** [comment]
Should this be closed? It seems covered by the more generic #21721

**Comment by vdemeester** [comment]
Yeah, let's move the discussions on there :angel:

**Comment by HugoPoi** [comment]
For the folks arriving here because of misleading documentation, YOU CAN'T ADD OR REMOVE LABEL a running container. The current related issue is #21721. And for documentation issue is https://github.com/docker/docker.github.io/issues/7716
