### ISSUE TITLE
Docker File does not add to PATH variable 

### ISSUE THREAD

**Issue by marshell08** [docker/docker#15497]
Below is my docker file which is simply running a NodeJS Application in a docker container. Along with the installation i am also trying to add some path to the PATH variable in Linux but for whatever reason they do not get added. 

I am not sure what is it that i am doing wrong here ? The image when built and run works fine without the PATH variable being updated.

RUN mkdir -p /root/.cfenv/shims
env PATH /root/.cfenv/bin:/root/.cfenv/shims:$PATH

[root@web-server]# cat Dockerfile 
FROM    centos:centos6

RUN     rpm -Uvh http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm

RUN     rpm -Uvh https://dl.dropboxusercontent.com/u/143598220/cf-cli_amd64.rpm

RUN     yum install -y npm
RUN     yum install -y java-1.7.0-openjdk-devel
RUN     yum install -y  git

COPY . /src

RUN cd /src; npm install

RUN git clone https://github.com/nebhale/cfenv.git ~/.cfenv
RUN git clone https://github.com/nebhale/cf-build.git ~/.cfenv/plugins/cf-build

RUN mkdir -p /root/.cfenv/shims
env PATH /root/.cfenv/bin:/root/.cfenv/shims:$PATH

RUN echo 'export PATH="$HOME/.cfenv/bin:$HOME/.cfenv/shims:$PATH"' >> /root/.bash_profile
RUN echo 'eval "$(cfenv init -)"' >> /root/.bash_profile

EXPOSE  8083
CMD ["node", "/src/RunSanityOnWeb.js"]

----------------------------------------------------------------------------------------------------------------------------------

BUG REPORT INFORMATION

Use the commands below to provide key information from your environment:

docker version:
[root@web-server]# docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64

docker info:
[root@web-server]# docker info
Containers: 7
Images: 296
Storage Driver: devicemapper
Pool Name: docker-202:2-1540820-pool
Pool Blocksize: 65.54 kB
Backing Filesystem: extfs
Data file: /dev/loop0
Metadata file: /dev/loop1
Data Space Used: 3.826 GB
Data Space Total: 107.4 GB
Data Space Available: 99.79 GB
Metadata Space Used: 14.91 MB
Metadata Space Total: 2.147 GB
Metadata Space Available: 2.133 GB
Udev Sync Supported: true
Deferred Removal Enabled: false
Data loop file: /var/lib/docker/devicemapper/devicemapper/data
Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.11.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 4
Total Memory: 3.452 GiB
Name: cds-devops-tooling
ID: 4ZHT:XE7J:BKTJ:4FH7:KTGZ:FY2N:7UJU:HE3Z:RY54:2TFR:RXEZ:RTJK

uname -a:
Linux cds-devops-tooling 3.10.0-229.11.1.el7.x86_64 #1 SMP Thu Aug 6 01:06:18 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Provide additional environment details (AWS, VirtualBox, physical, etc.):

Virtual Server

Describe the results you received:

[root@cds-devops-tooling cds-sanityonweb-server]# docker exec 50e9c6ee0638 echo $PATH
/root/.cfenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin

Describe the results you expected:
Missing /root/.cfenv/shims

----------END REPORT ---------

**Comment by marshell08** [comment]
BUG REPORT INFORMATION

Use the commands below to provide key information from your environment:

docker version:
[root@web-server]# docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64

docker info:
[root@web-server]# docker info
Containers: 7
Images: 296
Storage Driver: devicemapper
 Pool Name: docker-202:2-1540820-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.826 GB
 Data Space Total: 107.4 GB
 Data Space Available: 99.79 GB
 Metadata Space Used: 14.91 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.133 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.11.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 4
Total Memory: 3.452 GiB
Name: cds-devops-tooling
ID: 4ZHT:XE7J:BKTJ:4FH7:KTGZ:FY2N:7UJU:HE3Z:RY54:2TFR:RXEZ:RTJK

uname -a:
Linux cds-devops-tooling 3.10.0-229.11.1.el7.x86_64 #1 SMP Thu Aug 6 01:06:18 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Provide additional environment details (AWS, VirtualBox, physical, etc.):

Virtual Server 

Describe the results you received:

[root@cds-devops-tooling cds-sanityonweb-server]# docker exec 50e9c6ee0638 echo $PATH
/root/.cfenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin

Describe the results you expected:
Missing /root/.cfenv/shims


----------END REPORT ---------

#ENEEDMOREINFO

**Comment by phemmer** [comment]
```
# docker exec 50e9c6ee0638 echo $PATH
/root/.cfenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
```

This is the `$PATH` value from the host, not the container. If you want to see the `$PATH` of the container, use:

    docker exec 50e9c6ee0638 sh -c 'echo $PATH'

**Comment by thaJeztah** [comment]
yes, you're seeing the local shell expanding the `$PATH` variable, as @phemmer explained (thanks again, Patrick!)

I'm closing this issue, but feel free to comment here after I closed

**Comment by DarioSwain** [comment]
@thaJeztah @phemmer Hi guys, If i correct understand this [topic](https://docs.docker.com/reference/builder/#env), next command don't work:
```bash
ENV PATH /my/bin/:$PATH
```
How i can override $PATH env?
