### ISSUE TITLE
why does docker save or export  command haven't a gzip or bzip2 options?

### ISSUE THREAD

**Issue by coztest** [docker/docker#15506]
I find that docker/pkg/archive has gzip or bzip2 CompressStream, if I want to save a tar.gz, I must use pipe like save | gzip or change docker source?

**Comment by cpuguy83** [comment]
Closing as I think this is as expected. I believe we've had this discussion before.
In any case, gzip/bzip is likely to give better performance and have more options, and keeps docker flexible.
