### ISSUE TITLE
gelf-address is not used in daemon mode

### ISSUE THREAD

**Issue by gondor** [docker/docker#15509]
When specifying the `--log-opt gelf-address=udp://host:ip` in the `/etc/default/docker` it is not used and during container startups issues an error from within the daemon.

**docker version:**  `Docker version 1.8.0-rc3, build 696147b`

**docker info:**
```
Containers: 24
Images: 58
Storage Driver: aufs
 Root Dir: /mnt/docker/aufs
 Backing Filesystem: extfs
 Dirs: 106
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: gelf
Kernel Version: 3.13.0-61-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 8
Total Memory: 14.69 GiB
Name: ip-10-238-194-160
ID: RK7H:NGP3:YU3T:OKTF:43ZR:M35G:C72E:XYQZ:SBSS:CY4M:AKKO:IM5N
Username: intotacloud
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**OS:**
```
Linux ip-10-238-194-160 3.13.0-61-generic #100-Ubuntu SMP Wed Jul 29 11:21:34 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Environment Details:** AWS EC2 instance running docker and mesos slave.
**Actual Results:**
```
Cannot start container ea77ddf16fbdd729d88b29a89e3b6290a85d0f384a0b605795fe0ebb18ca83ab: Failed to initialize logging driver: gelf: cannot connect to GELF endpoint:  dial udp: missing address statusCode=500
```

**Steps to Reproduce:**
1. ssh to slave
2. vi /etc/default/docker append this DOCKER_OPTS="--log-driver=gelf --log-opt gelf-address=udp://1.1.1.1:12201"
3. service docker restart
4. docker run ubuntu:latest /bin/bash

**Other Notes:** This is being picked up properly from the docker options.  It shows within the processes.   When running via `docker run` with the gelf-address logging is working as expected.  This only occurs with the `daemon` process.  Since we are using mesos we need it to be within the daemon.
```
ps aux | grep docker
root     28135  0.3  0.1 406872 20660 ?        Ssl  03:02   0:00 /usr/bin/docker daemon -g /mnt/docker -s aufs --log-driver=gelf --log-opt gelf-address=udp://10.238.194.117:12201
```
This issue is similar to Issue #15475

**Comment by gondor** [comment]
@GordonTheTurtle Did I not do it correctly?  Above has everything you needed and more?

**Comment by thaJeztah** [comment]
Closing. This should be resolved by https://github.com/docker/docker/pull/15611, which will be in the 1.8.2 release
