### ISSUE TITLE
Broken 404 page for docs.docker.com

### ISSUE THREAD

**Issue by ankushagarwal** [docker/docker#15500]
Earlier a missing page(404) redirected to the homepage, now it shows the following error : 

![image](https://cloud.githubusercontent.com/assets/796949/9212494/2ae7cc8e-403e-11e5-811d-6c4a4d7846e5.png)

**Comment by calavera** [comment]
We have CI for docs now to prevent this to happen. Closing as fixed. Thanks for the report.
