### ISSUE TITLE
There are a bunch of layers on the hub with nonconformant whiteout files

### ISSUE THREAD

**Issue by vincentwoo** [docker/docker#15517]
I understand both of the following situations with regards to [this part of the docker image spec](https://github.com/docker/docker/blob/master/image/spec/v1.md#creating-an-image-filesystem-changeset) to be nonconformant:

* A file in the tar stream that has a parent directory that starts with `.wh.`. In particular: `.wh..wh.plnk/292.1436735`
* A directory in the tar stream that starts with `.wh.`. From my reading of the spec, all whiteout files should be "files" in the tar stream. In particular: `.wh..wh.orph/`.

If I've misread the spec and these *are* conformant, some guidance on the spec on how to interpret such entries would be welcome.

You can pull `aff4b9bb562080c445a90bf43b402360a300b40249a2c3c2cee771a6a59422c7` to examine an example - I think this is a layer in one of the official nginx images. There are a lot of layers like this.

From my reading of @jlhawn's https://github.com/docker/docker/pull/8813, it seems these might be either poorly handled or legacy AUFS problems.

Does the registry do validation of this sort? The client doesn't like it if I try to produce nonconformant directories (`mkdir .wh.asdf` fails), but I imagine it's possible to get into a sticky situation via importing filesystems, etc.

P.S. I am downloading every layer on the hub (only sorta kidding).

**Comment by vincentwoo** [comment]
from my tower, gordon, i stab at thee

**Comment by thaJeztah** [comment]
Also see https://github.com/docker/docker/pull/15996

**Comment by LK4D4** [comment]
ping @tonistiigi 
Do you have some ideas here?

**Comment by tonistiigi** [comment]
We do not put `.wh..wh.plnk/.wh..wh.orph` files in the layers anymore but we used to do it in older docker versions and we still have the code that does some basic handling of these files. https://github.com/docker/docker/pull/16470/files#diff-2441da2e3b5de478b533a1310aa1864aR325 

Registry doesn't extract layers nor validate their contents.

**Comment by LK4D4** [comment]
@tonistiigi Thanks for the answer!
@vincentwoo I hope you got your answer one year later :(
