### ISSUE TITLE
Docker-engine 1.8 not available for Ubuntu 14.10

### ISSUE THREAD

**Issue by BMouser** [docker/docker#15529]
The new docker-engine PPA does not have docker 1.8 uploaded for Ubuntu 14.10 (Utopic). Instead it is docker 1.7.1 (still called docker-engine)

http://apt.dockerproject.org/repo/dists/ubuntu-utopic/main/binary-amd64/Packages

As a work around I changed my local /etc/apt/sources.list.d/docker.list to point to 14.04 which seems to work:
deb https://apt.dockerproject.org/repo ubuntu-trusty main

**Comment by thaJeztah** [comment]
this could well be possible; ubuntu 14.10 has been marked EOL and is no longer supported (both by Ubuntu and Docker); see http://fridge.ubuntu.com/2015/07/03/ubuntu-14-10-utopic-unicorn-reaches-end-of-life-on-july-23-2015/

I suggest to either use a LTS release (14.04) or Upgrade to 15.04

I'm going to close this issue, but feel free to comment here after I closed this
