### ISSUE TITLE
1.8.0 release notes document non-existent logging driver "rollover"

### ISSUE THREAD

**Issue by albers** [docker/docker#15520]
Similar to #15518.

In https://github.com/docker/docker/releases/tag/v1.8.0, section "Runtime":

>Add rollover log driver, and --log-driver-opts flag

Also in changelog.

    # docker daemon --log-driver rollover
    INFO[0000] [graphdriver] using prior storage driver "aufs"
    INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
    FATA[0000] Error starting daemon: error finding the logging driver: logger: no log driver named 'rollover' is registered

"rollover" is not a new logging driver. It is a new configurable behaviour of the json-file logging driver, introduced in #11485, see https://github.com/docker/docker/pull/11485/files#diff-bf81424845bcab2902c9809e30dfe6e0R35

**Comment by albers** [comment]
#15521 addresses the changelog part.

**Comment by albers** [comment]
@thaJeztah Sorry, this is not fixed in the release notes yet. Could you please re-open?

**Comment by dreamcat4** [comment]
Ok. So if this feature is already in `1.8.1` and a part of the json logger. How do we actually specify it? Like this?

```sh
docker run --log-driver-opts max_size=1k --log-driver-opts file_count=10
```

**Comment by albers** [comment]
@dreamcat4 See https://github.com/docker/docker/blob/master/docs/reference/logging/overview.md#json-file-options

**Comment by dreamcat4** [comment]
@albers Thanks man.
