### ISSUE TITLE
Support relative paths (with -v/--volume and -w/--workdir)

### ISSUE THREAD

**Issue by jakirkham** [docker/docker#15526]
It would be nice, particularly on the host side, if relative paths could be used here. Supporting this might be as simple as converting them to absolute paths once the arguments are parsed before continuing. On the container side, if there is a way to inspect the current workdir, this would, ideally, be simple, as well.

**Comment by phemmer** [comment]
> It would be nice, particularly on the host side, if relative paths could be used here.

Relative to what?

**Comment by jakirkham** [comment]
On the host side? Relative to the current working directory.
On the guest side? Relative to whatever `WORKDIR` or what the `-w`/`--workdir` are set to.

**Comment by phemmer** [comment]
> On the host side? Relative to the current working directory.

Using the current working directory is impossible. The docker client doesn't necessarily reside on the same host as the docker daemon.

**Comment by jakirkham** [comment]
I don't know that I agree with your pessimism. The client can convert the host side path to absolute paths before passing them through.

**Comment by phemmer** [comment]
No it can't.
If I'm on my client in `/home/phemmer`, and I run `docker run -v ./:/foo`, but the docker host is remote, and `/home/phemmer` doesn't exist there, what will be mounted?

**Comment by jakirkham** [comment]
Again, assuming you are referring to boot2docker. It actually mirrors your paths into the VM. So, there will be `/home/phemmer` in the VM. For instance, on my Mac I can run `boot2docker ssh` and `ls /Users/kirkhamj/` and see my home folder no problem. I am not sure how this case is handled with the Linux VM. In any event, I think you are missing my suggestion, which is with boot2docker cases the path be converted to an absolute path before calling `docker` within the VM. This will not be a problem as this already works now.

**Comment by phemmer** [comment]
I'm not referring to boot2docker.
The docker client operates via http calls. Thus the client filesystem does not have to look anything like the host's filesystem. boot2docker is popular yes, but it is not the only case where the client is remote to the host. Docker cannot support anything which relies upon the two to share a filesystem.

**Comment by thaJeztah** [comment]
Docker-compose currently does just this, but relative to the docker-compose.yml file. For docker, the general way to handle this, is `docker run -v $(pwd)/foo:/bar ...`.

However, @phemmer is right that the file system on the host you're running the client on can have a completely different directory layout then the host the daemon runs on. For this reason, Docker will not *assume* anything (think, for example, of cases where the docker daemon runs somewhere in the cloud)

Boot2Docker  is targeted at local development and shares the `/Users/` directory with the Boot2Docker virtual machine using VirtualBox shares. Basically, this is just a "hack" to make it work as if the daemon is running on your local system. Trying to use anything outside the `/Users/’ directory will fail to work or, more accurately, result in empty mountpoints being created on the daemon's file system.

I understand your use case, and this *would* make it more convenient to work with when using Boot2Docker, but I think it should be closed for the above reasons.

So, I'm -1, but there may be others that think different

**Comment by cpuguy83** [comment]
Closing because this is just not really possible.
Again it's relative to what exactly.
If you want to use a relative path to your current working dir you can use `$(pwd)`.
