### ISSUE TITLE
--insecure-registry not supported by docker run

### ISSUE THREAD

**Issue by telmich** [docker/docker#15522]
[14:04] wurzel:~% docker run -p 2379:2379 -v /usr/share/ca-certificates/:/etc/ssl/certs quay.io/coreos/etcd:v2.1.1
Unable to find image 'quay.io/coreos/etcd:v2.1.1' locally
Error response from daemon: invalid registry endpoint https://quay.io/v0/: unable to ping registry endpoint https://quay.io/v0/
v2 ping attempt failed with error: Get https://quay.io/v2/: dial tcp: lookup quay.io: no such host
 v1 ping attempt failed with error: Get https://quay.io/v1/_ping: dial tcp: lookup quay.io: no such host. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry quay.io` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/quay.io/ca.crt
[14:04] wurzel:~% docker run -p 2379:2379 --insecure-registry quay.io  -v /usr/share/ca-certificates/:/etc/ssl/certs quay.io/coreos/etcd:v2.1.1                          
flag provided but not defined: --insecure-registry
See 'docker run --help'.
[14:04] wurzel:~% docker --version
Docker version 1.7.1, build 786b29d
[14:06] wurzel:~%

**Comment by telmich** [comment]
It's seems to be a parsing issue, as stated in the above comment.

[14:38] wurzel:~% docker version; docker info; uname -a
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
Containers: 0
Images: 0
Storage Driver: devicemapper
 Pool Name: docker-254:0-4069541-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 305.7 MB
 Data Space Total: 107.4 GB
 Data Space Available: 107.1 GB
 Metadata Space Used: 733.2 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.102 (2015-07-07)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.4-1-ARCH
Operating System: Arch Linux
CPUs: 4
Total Memory: 7.684 GiB
Name: wurzel
ID: PAIY:45FB:AK45:25CT:M4UU:YOPY:466F:SBYK:IS3G:F7EX:IRRG:7UG7
Linux wurzel 4.1.4-1-ARCH #1 SMP PREEMPT Mon Aug 3 21:30:37 UTC 2015 x86_64 GNU/Linux
[14:38] wurzel:~%

**Comment by phemmer** [comment]
`--insecure-registry` is a daemon option, not a run option.

E.G. `docker -d --insecure-registry foo.com`

However your issue is not related to `--insecure-registry`,  your issue is:

    no such host

Either your local DNS server is borked, or this is an issue with `quay.io`. (the former is more likely)

**Comment by cpuguy83** [comment]
@phemmer is correct

Closing.
