### ISSUE TITLE
Ports aren't showing up in docker ps, and are failing for registrator.

### ISSUE THREAD

**Issue by jsindy** [docker/docker#15537]
docker run with "-p port:port" "-p port" or "-P" shows empty values in docker ps PORT line.

I believe this is also the reason why registrator shows the error.

2015/08/12 22:29:50 registrator: ignored: 14afdfe79c16 no published ports

Docker version 1.9.0-dev, build 0e3674d, experimental

**Comment by jsindy** [comment]
vagrant@net-1:~$ uname -a
Linux net-1 3.19.0-23-generic #24-Ubuntu SMP Tue Jul 7 18:52:55 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
vagrant@net-1:~$ docker info
Containers: 4
Images: 51
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 59
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-23-generic
Operating System: Ubuntu 15.04
CPUs: 1
Total Memory: 2.939 GiB
Name: net-1
ID: 6RP5:WOUU:BEPY:EZV4:JM5X:HFGJ:VY5T:DMKG:N6SB:DYCZ:BZSG:PTG5
WARNING: No swap limit support
Labels:
 com.docker.network.driver.overlay.bind_interface=eth1
 com.docker.network.driver.overlay.neighbor_ip=192.168.33.11
Experimental: true

**Comment by cpuguy83** [comment]
I'm not seeing this with master.

Can you provide exactly your repro steps?
Also the output of `docker version`

**Comment by chakrit** [comment]
Seeing this as well for this command:

```sh
docker run --name elastic --net="host" -p 9200:9200 -p 9300:9300 -d elasticsearch --node.name=xxx --cluster.name=xxx --http.cors.enabled=true
```

`docker ps` shows:

```sh
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
ab9c3dce3cf0        elasticsearch       "/docker-entrypoint.s"   3 seconds ago       Up 2 seconds                            elastic
```

No port information is shown. And supposedly, it wasn't mapped either as I can't even `telnet` into the port.

`docker version` is as follows:

```sh
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by phemmer** [comment]
@chakrit You're using `--net="host"`. Port mapping have no use when using host networking, as your container is using the host's network stack. Meaning when your app listens on a port, it's listening on the host's port.

**Comment by jsindy** [comment]
@cpuguy83 I am running 1.9.0-dev, build 0e3674d

I get the same output as chakrit but without running -net=host

**Comment by jsindy** [comment]
```
vagrant@net-1:~$ docker run -d -p 9999:9999 pingidentity/cfe
vagrant@net-1:~$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
193de3d61166        pingidentity        "/bin/sh -c /home/pin"   37 seconds ago      Up 36 seconds                           lonely_bohr
```

**Comment by jsindy** [comment]
Looks like another symptom is once you kill the container it does not release the port either.

Error response from daemon: Cannot start container 411a30710f8b3423f383b454c9934e7e989cb77cf1a3d83bc9e394a3cf64a472: Bind for 0.0.0.0:9999 failed: port is already allocated

**Comment by aboch** [comment]
@jsindy @chakrit 
Are you still seeing the port missing issue with 1.9.1 ?

**Comment by jsindy** [comment]
I am not seeing this issue anymore.

**Comment by thaJeztah** [comment]
Thanks @jsindy!

**Comment by MrMMorris** [comment]
running into this on 1.9.1.

`docker run -d --name graphite -p 2003:2003 sitespeedio/graphite`
```
$ docker ps
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS               NAMES
c3feaf05ab03        sitespeedio/graphite            "/sbin/my_init"          6 minutes ago       Up 6 minutes                            graphite
$ docker port graphite
```
