### ISSUE TITLE
Remove the terms folder

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#15530]
* Replace any links to the files in /terms with links to reference/glossary.md
* Remove the /terms directory

**Comment by dharmit** [comment]
#dibs

**Comment by dharmit** [comment]
@moxiegirl Could  you help me get started on this? It's my first time contributing to Docker.

From the description, I understand that the docs need to be updated with links to docs/reference/glossary.md instead of existing docs/terms.And all the docs reside in docs/ directory. Is that right?

**Comment by moxiegirl** [comment]
@dharmit Happy to help. Make sure you read through [the contributor's guide](http://docs.docker.com/project/make-a-contribution/)

Let me outline what I would do.

1. Clone the 'docker/docker' repo
2. Search the 'docs/*.md' source files to links to the files in 'terms/`
3. If I find any links, replace them with links to the term is `glossary.md`
4. Build the documentation with `make docs`
5. Verify any files that I edited in step 3 are building correctly.
6. Commit my changes.
7. [Rebase my branch](http://docs.docker.com/project/create-pr/#rebase-your-branch),
8. [Make a pull request](http://docs.docker.com/project/create-pr/#create-a-pr-on-github).

**Comment by dharmit** [comment]
@moxiegirl whenever you have time, let me know if things look good or I need to make any changes.
