### ISSUE TITLE
Fedora, packaging issue - service file doesn't read /etc/sysconfig/docker

### ISSUE THREAD

**Issue by pseudonymous-foss** [docker/docker#15535]
The default docker.service file doesn't have an 'EnvironmentFile' in its [Service] section. This is (to my understanding) the usual way of allowing custom flags to alter the behaviour of a daemon kind of like Ubuntu's /etc/default/<service> files.

Something like the following should do:

-- docker.service--
[Service]
EnvironmentFile=-/etc/sysconfig/docker
ExecStart=/usr/bin/docker -d -H fd:// $DAEMON_OPTS

-- /etc/sysconfig/docker --
DAEMON_OPTS=""

I'm writing this from a Fedora 22 installation with docker-engine 1.8 - curiously "/etc/sysconfig/docker" is provided by "docker-engine-1.8.0-1.fc22.x86_64" but not respected.

**Comment by pseudonymous-foss** [comment]
➜  ~  docker version
Client:
 Version:      1.8.0
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0d03096
 Built:        Tue Aug 11 16:46:16 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.0
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0d03096
 Built:        Tue Aug 11 16:46:16 UTC 2015
 OS/Arch:      linux/amd64

-----------
➜  ~  docker info
Containers: 27
Images: 157
Storage Driver: devicemapper
 Pool Name: docker-253:1-269250-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.801 GB
 Data Space Total: 107.4 GB
 Data Space Available: 41.35 GB
 Metadata Space Used: 8.446 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.139 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93 (2015-01-30)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.3-201.fc22.x86_64
Operating System: Fedora 22 (Twenty Two)
CPUs: 8
Total Memory: 15.58 GiB
Name: stark
ID: 32CK:6VGZ:RTYX:UDIS:TXB7:4VPQ:SCJK:UNFC:DJ7W:CAM3:HZ6U:XLBD

-----------------
➜  ~  uname -a
Linux stark 4.1.3-201.fc22.x86_64 #1 SMP Wed Jul 29 19:50:22 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux


Reproduce:
1) Add '--insecure-registry 192.168.8.12:5000' to 'other_args' in '/etc/sysconfig/docker'
2) systemctl daemon-reload
3) systemctl restart docker.service
4) ps aux|grep docker

Would expect to see the new argument in the command used to start the docker daemon as returned by (4).

**Comment by thaJeztah** [comment]
Thanks for reporting, however, this has come up several times, for reference; https://github.com/docker/docker/pull/14513, and https://github.com/docker/docker/pull/15301

To customize your daemon options, the recommended way is to use drop-in files, as described here: http://docs.docker.com/articles/systemd/#custom-docker-daemon-options

I'm going to close this issue, because this was discussed in earlier issues and rejected. Feel free to comment here after I closed this issue. Thanks!
