### ISSUE TITLE
Dockerfile naming convention

### ISSUE THREAD

**Issue by pleerock** [docker/docker#15549]
When there are lot of dockerfiles in a project "How do I name them" question is coming. Docker community need to came up with a good convention, something better then "Dockerfile".

Something I can suggest is:
use `.dockerfile` extension. This give us at least these two good opportunities. 
First, we can name files this:
`nginx.dockerfile`
`php.dockerfile`
`app.dockerfile`
`mysql.dockerfile`
...
or:
`ci.dockerfile`
`development.dockerfile`
`production.dockerfile`

Second it will give IDEs to understand what this file is, use an icon for it, and implement syntax highlighting.

**Comment by duglin** [comment]
The problem with this is that any tooling that is built would need to know the name of each Dockerfile. The advantage of promoting (but not requiring) it be called `Dockerfile` is that generic tooling will just work w/o any customization.  Beyond that, if customization I needed, I think (as evidenced by the lack of discussion on this PR) its simply each user's choice and not something we need to try to standardize.

I'm going to close this one - if there's interest in reopening it (based on an influx of discussion) we can do so.

**Comment by tiangolo** [comment]
I agree that having just `Dockerfile` simplifies tooling, and that each team can define their conventions for other Dockerfiles.

---

I'm just adding this as a note, just to add some more info for others that come here trying to find out reasons to adopt any convention.

First, [Docker Compose has examples with names like `Dockerfile-alternate`](https://docs.docker.com/compose/compose-file/#context):

```yaml
build:
  context: .
  dockerfile: Dockerfile-alternate
```

Nevertheless, some editors (at least, Visual Studio Code, but I imagine others too) detect a file's language automatically based on the file name. If it is named `Dockerfile`, it recognizes it and does syntax highlighting, etc. But if the file name is `Dockerfile-alternate` or something similar, it doesn't recognize it as a `Dockerfile` automatically. 

But it does recognize `.dockerfile` file extensions, like `alternate.dockerfile`.

So, the convention I'm using with my team is:

* If the image can live in its own directory, name it `Dockerifle`.
* If there are additional images (Dockerfiles) that need to be in the same directory (for example, if they share code), use the alternative name with an extension of `.dockerfile`, like in `alternate.dockerfile`.

So, for example, I have a directory `backend`, and inside of it I have:

* One Dockerfile for the main API Docker image, named `Dockerfile`
* One Dockerfile for a worker (a Celery worker) that shares some code, named `worker.dockerfile`
* One Dockerfile for API testing, that shares some code, named `tests.dockerfile`

That way, I keep the standard of the default `Dockerfile` for the main image, and have automatic language detection in editors for the other Dockerfiles that live in the same directory.
