### ISSUE TITLE
docker takes forever to start when /var/lib/docker/volumes is huge

### ISSUE THREAD

**Issue by imoverclocked** [docker/docker#15540]
On some nodes, docker takes many 10s of minutes to start.

$ sudo ls /var/lib/docker/volumes | wc -l
16641
$ sudo du -hs 
133M	/var/lib/docker/volumes
$ sudo docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

Doing an strace on docker -d shows that it is sequentially parsing all 16k (or more on most nodes) json files. When I manually inspect these files, they see to be referencing locations that no longer exist... thus they are defunct.

This needs to be made *much* faster or the files need to be garbage collected somehow. 99.999% of these files don't need to be here.

**Comment by cpuguy83** [comment]
Closing since this is a dup of other reports, and is also no longer relevant since these are no longer traversed since 1.7 (which should help your startup time).
In docker 1.9 we should have a top level `docker volumes` command, and in Docker 1.8 you can specifically used named volumes (and as such re-use the same volume over and over quite easily).

**Comment by imoverclocked** [comment]
$ sudo docker info
Containers: 76
Images: 102
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 4.1.3-181
Operating System: <unknown>
CPUs: 24
Total Memory: 94.38 GiB
Name: my.node.name
ID: FGQ7:ZOJP:WLTA:7VLH:5P44:GKZK:6F6Y:CJ7X:N6VE:OAW7:SC5O:NN3Y
$ uname -a
Linux my.node.name 4.1.3-181.el6siri #1 SMP PREEMPT Wed Jul 22 02:28:16 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

These are bare-hardware nodes.

**Comment by imoverclocked** [comment]
Oh, awesome. Thanks.
