### ISSUE TITLE
Cannot search images in private registries with the Docker remote API

### ISSUE THREAD

**Issue by fbuchinger** [docker/docker#15552]
The Docker Remote API seems to be inconsistent when dealing with private image registries: though I can create an image using [a private image registry](https://docs.docker.com/reference/api/docker_remote_api_v1.20/#create-an-image), I cannot search for available images in private registries - the [search  method](https://docs.docker.com/reference/api/docker_remote_api_v1.20/#search-images) seems to be hard-wired to search on docker hub. This is a bit annoying, as more and more companies set up their private image registries for increased download speed or non-public images. Any plans to improve the handling of private images in the Docker Remote API?

Steps to reproduce
```
1. GET /images/search?term=ubuntu&registry=http://mylocalregistry HTTP 1.1
```
Expected behaviour: image search is conducted in http://mylocalregistry
Actual behaviour: image search is conducted in docker hub registry

My Docker environment (not relevant for my problem, just for making peace with GordonTheTurtle):
```
$ docker version
Client version: 1.6.1
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 97cd073
OS/Arch (client): windows/amd64
Server version: 1.6.1
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 97cd073
OS/Arch (server): linux/amd64

fbu@NB000498 ~
$ docker info
Containers: 20
Images: 121
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 161
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 4.0.2-boot2docker
Operating System: Boot2Docker 1.6.1 (TCL 5.4); master : 43209d4 - Thu May  7 22:
06:28 UTC 2015
CPUs: 4
Total Memory: 1.957 GiB
Name: boot2docker
ID: BDEV:UIJY:5W3S:3Z52:YJ57:RZ26:EIUV:RN6B:RXTY:CNSI:OO64:AL36
Debug mode (server): true
Debug mode (client): false
Fds: 11
Goroutines: 16
System Time: Thu Jun 18 11:24:23 UTC 2015
EventsListeners: 0
Init SHA1: 2dabfc43e5f856a0712787a6ff78ceaf791cc9e7
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker

fbu@NB000498 ~
$ uname -a
MINGW32_NT-6.1 NB000498 1.0.12(0.46/3/2) 2012-07-05 14:56 i686 unknown
```

**Comment by dmp42** [comment]
Hi,

Issuing `docker search myregistry.com/searchsomething` should and will issue a request to myregistry.com

The corresponding remote API call being:
`/v1.20/images/search?term=myregistry.com%2Fubuntu`

That being said, the docker engine search functionality is still wired to the v1 protocol, and there is not yet a v2 protocol replacement for it, but this is another bug and is tracked already.

Hope that helps.
