### ISSUE TITLE
docker 1.8.1 cannot pull from redhat registry

### ISSUE THREAD

**Issue by binhex** [docker/docker#15558]
docker version:
```
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64
```

docker info:
```
Containers: 3
Images: 89
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 95
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-61-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 2
Total Memory: 5.823 GiB
Name: host.name.com
ID: ID57:5KWZ:XFO7:35N4:OGRL:HTKD:5QFD:IZMN:BUSA:ZF2V:WXMI:3UM6
WARNING: No swap limit support
```

uname -a:
```
Linux hostname.com 3.13.0-61-generic #100-Ubuntu SMP Wed Jul 29 11:21:34 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Environment details:- virtual machine running Ubuntu

**Steps to reproduce:-**
1. docker pull registry.access.redhat.com/rhel6.5:latest

**Describe the results you received:**
Using default tag: latest
Pulling repository registry.access.redhat.com/rhel6.5
Tag latest not found in repository registry.access.redhat.com/rhel6.5

**Describe the results you expected:**
Pulling repository registry.access.redhat.com/rhel6.5
17352558d512: Download complete
Status: Downloaded newer image for registry.access.redhat.com/rhel6.5:latest

**Provide additional info you think is important:**
This does not fail if running Docker 1.7.1 or earlier.

----------END REPORT ---------

**Comment by dmp42** [comment]
`curl https://registry.access.redhat.com/v1/repositories/rhel6.5/tags/latest` returns 404.

(while `curl https://registry.access.redhat.com/v1/repositories/rhel6.5/tags` returns the list of tags)

Other endpoints seem to be missing as well.

I suggest you bring this up with RedHat support.

**Comment by thaJeztah** [comment]
ping @rhatdan you may want to follow this one

**Comment by puja108** [comment]
Actually, we're experiencing the same problem with a self-hosted v1 registry, so could be a general v1 issue, not just redhat

**Comment by dmp42** [comment]
@puja108 please open a new issue over here: https://github.com/docker/docker-registry

These are definitely different issues, with different symptoms as far as I can tell.

**Comment by puja108** [comment]
@dmp42 indeed it might not be connected to #15538. However, we're experiencing the same issue as this one here (`Tag latest not found`) with a self-hosted v1 registry. I downgraded to 1.7.1 and everything is fine, it is thus a 1.8.x issue and not a registry issue imho. If you want I can create a new issue, but like I said I don't think it should be a registry issue as anything before docker 1.8.0 works perfectly fine.

**Comment by rhatdan** [comment]
We are working to fix the rhel image problems with docker-1.8.1.  There is a problem with the way the crane server (Red Hat's Registry) is serving the content.

**Comment by dmp42** [comment]
@puja108 404 and 405 are different errors. Just because the symptom is a failure to pull an image for both does not mean they are the same - the RedHat side of it will be fixed (according to @rhatdan ) with a RH registry patch.

Also, we absolutely need *logs* if we are to diagnose your problem.

Please open a new issue, and add:

 * your registry logs
 * any relevant details about your registry configuration (authentication, proxy, backend storage)
 * docker version (avoid 1.8.0, and use 1.8.1)
 * docker daemon logs

Thanks.

**Comment by gdw2** [comment]
I believe I'm seeing this issue as well.  I'm trying to pull from an Artifactory registry (not sure what they use underneath).  

Docker 1.5.0 successfully pulls tags from `...tags` whereas Docker 1.8.1 gets a 405 when trying to pull from `...tags/latest`.  

Here is the failing `docker daemon` output:

```
...
DEBU[0406] [registry] Calling GET https://artifactory.acme.com:8091/v1/repositories/acme/anvil/images
DEBU[0407] Retrieving the tag list
DEBU[0407] Got status code 405 from https://artifactory.acme.com:8091/v1/repositories/acme/anvil/tags/latest
ERRO[0407] unable to get remote tags: Could not reach any registry endpoint
DEBU[0407] Not continuing with error: Could not reach any registry endpoint
```

**Comment by tombutt** [comment]
a new crane has been released (Red Hat Registry), and you should be able to pull images with 1.8.1

**Comment by thaJeztah** [comment]
Thanks for the information @tombutt!

@binhex can you confirm this is resolved for you? Then we can close this issue, thanks!

**Comment by calavera** [comment]
Closing as solved. Thanks for the report.
