### ISSUE TITLE
Filtering containers via labels seems to be broken after upgrade to docker-toolbox

### ISSUE THREAD

**Issue by BjRo** [docker/docker#15553]
**Description of problem**

I just updated this morning my docker dev setup to use `docker-toolbox` instead of `boot2docker` and docker installed via `homebrew`. I had previously `docker 1.7.0` installed.

Before the update I was able to filter containers based on labels using this query

```
docker ps -q -f 'label=com.xing.category=continuous_configuration'
```

After the upgrade to `docker 1.8.1` the filter query does not match anything on `docker ps` anymore. However on `docker images` it still does.

The labels in my setup were only set inside the docker images via 

```
LABEL com.xing.category="continuous_configuration"
```

Is this a regression, or did I misuse a feature here?

**uname -a**

```
Darwin XXX 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
```

**docker --version**

```
Docker version 1.8.1, build d12ea79
```

**docker -D info**
```
DEBU[0000] Trusting certs with subjects: [010U
bjoern.rochel]
Containers: 8
Images: 35
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 51
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.1 (TCL 6.3); master : 7f12e95 - Thu Aug 13 03:24:56 UTC 2015
CPUs: 8
Total Memory: 1.955 GiB
Name: default
ID: J3DO:6QQM:TM66:PRV4:YOIH:3KT2:GJSB:EDOV:RUXY:EQ5M:FAEO:FUSW
Debug mode (server): true
File Descriptors: 63
Goroutines: 150
System Time: 2015-08-13T07:57:50.51448487Z
EventsListeners: 1
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

**Actual Results:**

**Expected Results:**

```
docker ps -q -f 'label=com.xing.category=continuous_configuration'
```
should find all containers that were created of images that had this label

**Comment by thaJeztah** [comment]
hm, I think this is related to https://github.com/docker/docker/pull/15503

If I understand correctly, you're trying to filter containers, based on labels set in the *image*, not set during run/create? (So not labels set via `docker run --label=foo=bar`)?

/cc @ibuildthecloud

**Comment by BjRo** [comment]
> If I understand correctly, you're trying to filter containers, based on labels set in the image, not set during run/create? (So not labels set via docker run --label=foo=bar)?

Yes that's what I'm doing.

I already suspected something like this. However switching to

```
docker run -d --label=foo=bar
```

also didn't make the filter query work again. There might be a regression

**Comment by thaJeztah** [comment]
I just tested this on docker 1.8.1 on ubuntu, and filtering by *container* labels looks to be working;
```bash
docker build -t repro-15553 - << EOF
FROM nginx
LABEL com.xing.category=testing
EOF

docker run -d --label=com.xing.category=continuous_configuration repro-15553

0c3992d04c94a118f83a75e2edc364c14e82829c47830b98824eb8c85c53122d

docker ps -f label=com.xing.category=continuous_configuration

CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS               NAMES
0c3992d04c94        repro-15553         "nginx -g 'daemon off"   About a minute ago   Up About a minute   80/tcp, 443/tcp     admiring_thompson
```
however, filtering on *image* labels does indeed no longer work in 1.8;

```bash
docker ps -f label=com.xing.category=testing

CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

**Comment by BjRo** [comment]
So I played around with our code again and it looks like filtering on running containers is indeed working. I must have made a mistake while trying to figure out while stuff after the upgrade wasn't working. 

I updated our scripts to not rely on container labels and apply the same label a second time when the container is started. Seems to work fine.
