### ISSUE TITLE
Daemon does not accept an IPv6 address to bind to

### ISSUE THREAD

**Issue by terror96** [docker/docker#15557]
The '-H' option does not support IPv6 addresses but returns an error: Invalid bind address format. pkg/parsers/parsers.go::ParseTCPAddr should be modified to accept IPv6 addresses in the format where the IPv6 IP number is encoded in square brackets, e.g. [2001:db8:1f70::999:de8:7648:6e8]:100.

**Comment by white-gecko** [comment]
This seams to be the same issue for the `DOCKER_HOST` environment variable used by the client. Is there any other format in which I can provide the IPv6 address? (Or any workaround?)

**Comment by white-gecko** [comment]
Defining a local host in `/etc/hosts` using the IPv6 address worked for me in this case. So this might be a workaround.

**Comment by perj** [comment]
I've looked into this. `ParseTCPAddr` misparses the option, allowing only a single `:` in the value after `tcp://'. I think it should be calling `net.SplitHostPort` instead of trying to parse it itself.

**Comment by cpuguy83** [comment]
#16950 should fix this, though it'll require square brackets around the address.
