### ISSUE TITLE
[DOC] Mistake for location of RSA keys with DockerToolbox on Windows

### ISSUE THREAD

**Issue by Mordead** [docker/docker#15564]
Hi,

There is a mistake in documentation for windows installation, in the part to connect with putty (Login with PUTTY instead of using the CMD).

With DockerToolbox, RSA keys was not generated in **%USERPROFILE%\.ssh\id_boot2docker** but in **%USERPROFILE%\.docker\machine\machines\<nameOfYourMachin\**

The file to be modify :
docker/docs/installation/windows.md

Thanks :)

**Comment by Evalle** [comment]
I will check it out.
#dibs

**Comment by thaJeztah** [comment]
Thanks @Evalle !

**Comment by Evalle** [comment]
This issue was fixed, see https://github.com/docker/docker/pull/15688

**Comment by Mordead** [comment]
Thanks
