### ISSUE TITLE
[EXPERIMENTAL Networking] Services are not cleaned up when a container is deleted

### ISSUE THREAD

**Issue by tomdee** [docker/docker#15573]
```
$ docker run  --publish-service=myservice.prod.bridge -tid --name container1 busybox
ef8c116c566424041a98c8cef2e93776a93e8c320915531865ca9564a5e13305
$ docker rm -f $(docker ps -qa)
ef8c116c5664
$ docker service ls
SERVICE ID          NAME                NETWORK             CONTAINER
fb80d5cb70d8        myservice           prod  
```

Is a user expected to manage these left over services themselves?

```
$ docker version
Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   0e3674d
 Built:        Tue Aug 11 22:53:37 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   0e3674d
 Built:        Tue Aug 11 22:53:37 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by mavenugo** [comment]
@tomdee Yes. it is expected. `--publish-service` creates explicit service just like `docker service create` does. and being an explicit service, the lifetime of it will stay just like the lifetime of a service created via the `docker service create`. We remove any implicit endpoint created via `docker run` that are implicitly created without a --publish-service.

**Comment by tomdee** [comment]
Hi @mavenugo, thanks for the reply. Can you give an example of how I can get implicit service creation?

**Comment by mavenugo** [comment]
@tomdee If you just do `docker run` without --publish-service, it will create an implicit endpoint. I wont call it the implicitly created services. They are just endpoints in the CNM model. They will get removed automatically when the container is removed.

**Comment by tomdee** [comment]
OK, makes sense. Closing.
