### ISSUE TITLE
syslog-tag is not used in daemon mode

### ISSUE THREAD

**Issue by aespinosa** [docker/docker#15575]
Description of problem:

syslog-tag is not used in `docker daemon`

`docker version`:
```
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:20:14 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:20:14 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:
```
Containers: 0
Images: 67
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 67
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: syslog
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 1
Total Memory: 494.5 MiB
Name: dockerhost
ID: F57Q:73M5:HAGL:SGHI:MM4B:T6FI:RWIY:IRDD:SL4S:7DFY:BONC:V6DA
Username: myuser
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
```

`uname -a`:

```
Linux dockerhost 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.):
Vagrant+ VMWare Fusion with the  vagrant box in https://atlas.hashicorp.com/boxcutter/boxes/debian81

How reproducible:

Steps to Reproduce:
1. Install docker through https://blog.docker.com/2015/07/new-apt-and-yum-repos/
2. Update `/etc/systemd/system/docker.service.d/10-syslog.conf`:
```
[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon --log-driver=syslog --log-opt syslog-tag=customtag -H fd://
```
3. `sudo systemctl daemon-reload`
4. `sudo systemctl restart docker.service`
5. `sudo docker run --rm busybox echo a tagged message to syslog`
6. `sudo grep "to syslog" /var/log/syslog`

Actual Results:

```
Aug 14 03:48:49 dockerhost docker/66f0eb134767[4459]: a tagged message to syslog
```

Expected Results:

```
Aug 14 03:48:49 dockerhost docker/customtag[4459]: a tagged message to syslog
```

Additional info:
Docker is running properly with the options as reported by systemd:

```
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─10-syslog.conf
   Active: active (running) since Fri 2015-08-14 03:46:35 UTC; 2s ago
     Docs: https://docs.docker.com
 Main PID: 4459 (docker)
   CGroup: /system.slice/docker.service
           └─4459 /usr/bin/docker daemon --log-driver=syslog --log-opt syslog-tag=customtag -H fd://
```

And `ps aux | grep docker`

```
root      4459  0.0  4.3 227732 22136 ?        Ssl  03:46   0:00 /usr/bin/docker daemon --log-driver=syslog --log-opt syslog-tag=customtag -H fd://
```

I confirmed that syslog-tag works when being specified in `docker run` itself.

I think this problem is related to #15475  and #15509 . It is probably a more generic problem on how daemon mode receives --log-opt data.

**Comment by thaJeztah** [comment]
Closing. This should be resolved by https://github.com/docker/docker/pull/15611, which will be in the 1.8.2 release
