### ISSUE TITLE
docker exec -i broken in head

### ISSUE THREAD

**Issue by mitchcapper** [docker/docker#15570]
to reproduce:
docker run -d --name test busybox ping google.com

docker exec -i -t test sh
will hang

without the -I it is fine.

Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   599b760
 Built:        Thu Aug 13 18:26:26 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   d50881e
 Built:        Thu Aug 13 00:10:13 UTC 2015
 OS/Arch:      linux/amd64

Containers: 34
Images: 1212
Storage Driver: aufs
 Root Dir: /mnt/datadrive/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1286
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 15.04
CPUs: 2
Total Memory: 6.805 GiB
Name: nc500A0
ID: CKPS:FIVB:5LY7:NQL5:YC56:S7LY:44DH:7H5D:RIV7:DRER:RS7L:MWCK
WARNING: No swap limit support

**Comment by tonistiigi** [comment]
seems to happen after #15446 

ping @cpuguy83

**Comment by cpuguy83** [comment]
Yep, I see the issue... totally flipped the logic of the tty check.
Working on a fix and some tests.

**Comment by cpuguy83** [comment]
#15446 fixes
