### ISSUE TITLE
[1.8.1]: ^C on pull broken

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#15589]
^C on a pull is unrecoverable, and does not even show the message "layer being pulled by another client"

**Comment by andyh2** [comment]
I think this is a dupe of #6928

**Comment by jfrazelle** [comment]
this is a regression

**Comment by hekaldama** [comment]
Is this a "good first bug"?

**Comment by calavera** [comment]
@hekaldama probably not. The distribution code is rather tricky.

**Comment by hekaldama** [comment]
@calavera okay. Thanks for the reply. Will keep looking for stuff to work on.
