### ISSUE TITLE
Should provide a way to install specific versioned docker

### ISSUE THREAD

**Issue by dalanlan** [docker/docker#15581]
Or at least give a kind doc. 
Solution in #9697 seems not quite working now.
Feel free to close it if there is a dup. Yet i didn't find one.

**Comment by mitchcapper** [comment]
Part of the problem with this is docker doesn't generally backport security features currently.  It is certainly a problem when the client/server API changes and you need to use multiple clients depending on which host you are talking to.

**Comment by cpuguy83** [comment]
This is working again on the new repos.
You need to specify the version by pinning it, ie `apt-get install docker-engine=1.7.0-trusty`

**Comment by psychok7** [comment]
I needed to downgrade so i did a `apt-cache policy docker-engine` to list the version and then `sudo apt-get install docker-engine=1.10.3-0~trusty`
