### ISSUE TITLE
tup error: Unable to chdir to virtual job directory.

### ISSUE THREAD

**Issue by JendaPlhak** [docker/docker#15587]
**Description of problem:**
Whenever I try to use tup in Docker, it returns error with message: 
`[ tup ] [0.060s] Parsing Tupfiles...
@tupjob-1: Operation not permitted
tup error: Unable to chdir to virtual job directory.
 [                                                                                                       ETA~=??? Remaining=229                                                                                                        ]   0%
 *** tup: 1 job failed.`

**`docker version`:**
`Docker version 1.8.1, build d12ea79`

**`docker info`:**
```
Containers: 51
Images: 658
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 764
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-61-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 8
Total Memory: 15.61 GiB
Name: machine
ID: ODUZ:BM32:42EY:THF7:WERJ:CIVU:X6TB:DRBZ:FGTV:FCDX:35JF:L2JJ
Username: jplhak
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**`uname -a`:**

```
Linux machine 3.13.0-61-generic #100-Ubuntu SMP Wed Jul 29 11:21:34 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
**Environment details (AWS, VirtualBox, physical, etc.):**
Physical machine

How reproducible:
It blows with any tupfile that has some jobs to do. 

Steps to Reproduce:
1. sudo docker run --rm -it --entrypoint=bash -privileged=true --tty --cap-add SYS_ADMIN --device /dev/fuse some_docker
2.tup init
3.tup

Please do you have any idea how to use tup properly? Of course, tup works as expected when ran on my local machine and not from docker.

**Comment by thaJeztah** [comment]
Did a quick google, and it looks like this is something related to FUSE; for example https://bugs.openvz.org/browse/OVZ-5376

Do you know if you're running a static docker binary, or a dynamically linked binary (from the new apt repository?)

**Comment by JendaPlhak** [comment]
Yeah, I found that, but it seemed to be related to fedora only.

About the static/dynamic library - I don't know. I recently upgraded to 1.8.1 `using curl -sSL https://get.docker.com/ | sh` command.

**Comment by LK4D4** [comment]
@thaJeztah @JendaPlhak wow, that's really old. I'm going to close it now. Feel free to open new so that it would be higher in a search.
