### ISSUE TITLE
Docker dead lock on pulling images

### ISSUE THREAD

**Issue by owenhaynes** [docker/docker#15582]
If two people do a pull of the same image at the same time using the same docker engine using the api a dead lock situation on layers each client report that its all ready being pulled by someone else, and never end up of this.

Docker 1.8.1
Registry 2.1

**Comment by LK4D4** [comment]
ping @stevvooe 
Might be related to other pull issues.

**Comment by stevvooe** [comment]
@mad0house We'll need more information to reproduce this.

@diogomonica Did you encounter this?

**Comment by diogomonica** [comment]
@stevvooe yes. There is also another bug that we just filed where if you Ctrl + C during a docker pull, the next pull will freeze forever (you need to restart the daemon).

**Comment by mad0house** [comment]
This was docker 1.8 on a fedora 22 machine running on AWS, same was happening with docker 1.7, so decided to upgrade they clients so if it resolved this issue.

To reproduce this you just need to 2 clients to request a pull of the same image, we have images with some big layers around 1GB++ in size it normally locks up on them images with this is being pulled by some one else message.

We use dockerpy(1.3.1) to communicate with the docker API, so both clients request to pull image using the same python code on 2 different machines. We do the pull in stream mode so we are able to see what is happening or the request just times out. 

The only was to resolve this is to reboot the machine, as kill -9 does not effect on the docker process.

**Comment by mad0house** [comment]
Also we have noticed that the when using docker as a socket with nginx it sometimes gives read errors.
We have switched to tcp and it does not seem to have gone, but image locking still happens.

**Comment by michelesr** [comment]
Actually i get this bug on docker 1.8 even if only one client is trying to pull an image:

    $ docker pull michelesr/jenkins
    Using default tag: latest
    latest: Pulling from michelesr/jenkins
     
     682b997ad926: Pull complete
     a594f78c2a03: Pull complete 
    8859a87b6160: Pull complete
    9dd7ba0ee3fe: Pull complete
    93934c1ae19e: Pull complete
    2262501f7b5a: Pull complete
    bfb63b0f4db1: Pulling fs layer
    49ebfec495e1: Download complete
    304b1d27dbc1: Download complete
    dd3ddf20b1fc: Download complete
    3845bc6f73c8: Download complete
    e5792931d61f: Download complete
    956ddd7dd4d5: Download complete
    df69bc327958: Download complete
    6b724a3e95bc: Download complete
    a2821a4835de: Download complete
    e4eda303e0ba: Download complete
    26704f1dbe44: Downloading 7.567 MB/62.88 MB 
    16d959216b93: Download complete
    7212ccd421e7: Download complete
    f8f21cb2876e: Pulling fs layer
    a2a0b5cf7025: Download complete
    a6685e884bae: Download complete
    014356d452df: Download complete
    803595966a6f: Download complete
    a47556c944b9: Download complete
    0c79d0a394dc: Download complete
    63334e3d8d73: Download complete
    17cc0786c214: Download complete
    8030cd6cadfc: Downloading 23.77 MB/67.82 MB
    7a7cc469b86e: Downloading 458.1 kB/1.203 MB
    aa47f04a2506: Download complete
    0bb0277bf1ff: Download complete
    3ff94adb843e: Download complete
    b7e686de599b: Download complete
    b7e686de599b: Layer already being pulled by another client. Waiting.
    9a61b6b1315e: Already exists
    1ff9f26f09fb: Already exists
    607e965985c1: Already exists
    Pulling repository docker.io/michelesr/jenkins

**Comment by dustymabe** [comment]
I am also seeing deadlock in docker pull for docker 1.8 on Fedora 22:

```
[root@f22 ~]# docker pull centos
Using default tag: latest
Trying to pull repository docker.io/library/centos ... latest: Pulling from library/centos
f1b10cd84249: Pull complete 
c852f6d61e65: Extracting [=============================================>     ] 57.38 MB/62.89 MB
7322fbe74aa5: Layer already being pulled by another client. Waiting.
```

It just hangs right there. Extracting never finishes.

```
[root@f22 ~]# docker version
Client:
 Version:      1.8.1.fc22
 API version:  1.20
 Package Version: docker-1.8.1-2.git3c1d7c8.fc22.x86_64
 Go version:   go1.4.2
 Git commit:   3c1d7c8/1.8.1
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1.fc22
 API version:  1.20
 Package Version: 
 Go version:   go1.4.2
 Git commit:   3c1d7c8/1.8.1
 Built:        
 OS/Arch:      linux/amd64
```

This may be related to #15603 ?

**Comment by michelesr** [comment]
Seems like Docker is trying to pull the same layer two times (`302f74a9f93f`) from the same client:
    ...
    7b212b78e8fe: Download complete
    70270c5e297c: Download complete
    8c8e2a0dbde4: Pulling fs layer
    909cf05ff400: Pulling fs layer
    302f74a9f93f: Pulling fs layer
    302f74a9f93f: Layer already being pulled by another client. Waiting.
    13c0c663a321: Already exists
    2bd276ed39d5: Already exists
    013f3d01d247: Already exists
    ...

**Comment by SaiOngole** [comment]
Each time I am doing a pull, there are two processes that are kicked off.
<img width="671" alt="screen shot 2015-08-31 at 10 54 13 am" src="https://cloud.githubusercontent.com/assets/6708858/9581644/a722e456-4fce-11e5-91de-f784b9751744.png">

This is the output of ps aux | grep docker

<img width="735" alt="screen shot 2015-08-31 at 10 55 04 am" src="https://cloud.githubusercontent.com/assets/6708858/9581666/bfd219d6-4fce-11e5-8d7d-a5c95ed24706.png">

If I try to kill one of the above listed process, it kills both of them.

**Comment by LK4D4** [comment]
I'm pretty sure this was fixed. Feel free to open new issue if you encounter this again.
