### ISSUE TITLE
Ubuntu (maybe other) apt repo missing metadata for older versions

### ISSUE THREAD

**Issue by leedm777** [docker/docker#15586]
Being able to install specific versions of `docker-engine` is important for configuration management. Without this, I don't have control over which versions of `docker-engine` are installed on the various VMs, instances, and machines throughout my different environments.

The current apt repo [has the binaries for older revs](http://apt.dockerproject.org/repo/pool/main/d/docker-engine), but (at least for Ubuntu trusty) it's [missing the metadata](http://apt.dockerproject.org/repo/dists/ubuntu-trusty/main/binary-amd64/Packages) in order to install them. It's likely the metadata is missing for other distros, but I have not checked.

```
# cat /etc/apt/sources.list.d/apt_dockerproject_org_repo.list 
deb https://apt.dockerproject.org/repo ubuntu-trusty main
# apt-get -qq update
# apt-cache show docker-engine | grep ^Version:
Version: 1.8.1-0~trusty
```

`docker version`: \<trying to install 1.7.1>
`docker info`: \<trying to install 1.7.1>
`uname -a`: `Linux docker-foo 3.13.0-61-generic #100-Ubuntu SMP Wed Jul 29 11:21:34 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

Provide additional environment details (AWS, VirtualBox, physical, etc.): instance in AWS

List the steps to reproduce the issue:
1. Put `deb https://apt.dockerproject.org/repo ubuntu-trusty main` in `/etc/apt/sources.list.d/apt_dockerproject_org_repo.list`
2. `apt-get -qq update`
3. `apt-get install docker-engine=1.7.1*`

Describe the results you received:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Version '1.7*' for 'docker-engine' was not found
```

Describe the results you expected:
```
Selected version '1.7.1-0~trusty' (ubuntu-trusty [amd64]) for 'docker-engine'
The following NEW packages will be installed:
  docker-engine
```

Provide additional info you think is important:

There are at least two other issues (#15581 and #9697) regarding specifying the version of `docker-engine` you with to install.

**Comment by cpuguy83** [comment]
ping @jfrazelle

**Comment by jfrazelle** [comment]
This is a dup

**Comment by jfrazelle** [comment]
Dup of https://github.com/docker/docker/issues/13191

**Comment by leedm777** [comment]
Sorry for the dup! Don't know why I couldn't find that issue earlier.

Thanks!
