### ISSUE TITLE
IP could not be fetched/error in setting up host only network

### ISSUE THREAD

**Issue by kday92** [docker/docker#15593]
Hello,

I just recently downloaded and installed docker by following the install guide that is currently up on the website.  However, as I was running it for the first time, I received an error as it was setting up the host only network.  I am currently running windows 7 64 bit enterprise, and I am using the latest version of of docker/virtualbox on the website.

Reinstalling / retrying generally gives the same result, and using the Kitematic tool gives me the error "machine IP could not be fetched".

How can I go about fixing this problem and getting docker to work?

![error](https://cloud.githubusercontent.com/assets/13664835/9282675/1887435c-429c-11e5-91d3-2e0d08d55f4e.jpg)

**Comment by cpuguy83** [comment]
ping @mchiang0610

**Comment by kday92** [comment]
Pinging just returns that it could not find a host with that name.  Also today, it returns this error when I try to start it up - 
![error2](https://cloud.githubusercontent.com/assets/13664835/9305863/9b367b38-44c2-11e5-9011-20fc5aee5c4f.jpg)

**Comment by cpuguy83** [comment]
Closing as this is a support related question and if an issue should be filed under github.com/docker/toolbox.

For support, please ping on #docker on IRC, the docker-user mailing list, or forums.docker.com
Thanks!
