### ISSUE TITLE
Windows: The docs need updating for the Windows daemon

### ISSUE THREAD

**Issue by jhowardmsft** [docker/docker#15597]
There's a lot of work to do here :)

**Comment by thaJeztah** [comment]
For example, https://github.com/docker/docker/pull/15356#issuecomment-131239359

**Comment by thaJeztah** [comment]
ping @jhowardmsft :-)

**Comment by jhowardmsft** [comment]
I know :) @taylorb_microsoft

**Comment by jhowardmsft** [comment]
@taylorb-microsoft I meant :)

**Comment by thaJeztah** [comment]
:dancer: thanks @jhowardmsft :)

**Comment by thaJeztah** [comment]
Also; document that links are not supported on windows, per: https://github.com/docker/docker/pull/18002

**Comment by LK4D4** [comment]
@thaJeztah @jhowardmsft there is certainly a lot of work to do here. But I'm not sure that we should keep this issue. Maybe create new issue with checklist of what needs to be documented or I dunno.

**Comment by jhowardmsft** [comment]
@neilpeterson One for you?

**Comment by jhowardmsft** [comment]
I'm closing this - there's a lot of work in the Microsoft virtualization documentation repo.
