### ISSUE TITLE
Systemd config missing option to set --insecure-registry

### ISSUE THREAD

**Issue by azweb76** [docker/docker#15590]
To enable push to an insecure registry, there used to be an option to set INSECURE_REGISTRY="--insecure-registry private-registry.com:5000" in /etc/sysconfig/docker.

/contrib/init/systemd/docker.service

**Comment by thaJeztah** [comment]
Closing per https://github.com/docker/docker/pull/15591#issuecomment-131195454, but feel free to comment here after I closed this
