### ISSUE TITLE
Can't activate build triggers when dockerfiles is in subdirectory

### ISSUE THREAD

**Issue by pandrew** [docker/docker#15608]
I cant seem to activate the build triggers on the hub when the dockerfile is in a subdirectory using automated build. For example i have a repo called dockerfiles with subdirectories for each app and activating build triggers seem to have no effect. If the dockerfile is in the root of the folder there seem to be no issues.

**Comment by thaJeztah** [comment]
Hi @pandrew. This issue tracker does not track issues related to Docker Hub (which is maintained by a different team). If you're having issues with Docker Hub, please open a ticket via https://support.docker.com for feedback on the new Docker Hub site, you can also search for existing tickets on https://github.com/docker/hub-beta-feedback and, if none exist, create a new one.

I'm going to close this issue, but feel free to comment here after I closed

**Comment by duglin** [comment]
@pandrew I don't think dockerhub supports the equivalent of the `-f` option on the build command.
