### ISSUE TITLE
HTTP response 403 when attempting to push to Docker hub

### ISSUE THREAD

**Issue by CGavrila** [docker/docker#15612]
First of all, I am quite a beginner, so I might be doing something completely wrong. However, I haven't been able to find anything helpful on this issue.

I have an account on https://hub.docker.com/, with `cgavrila` as a username. I have also created a public repository called `cgavrila/ubuntu-java`, even though I'm not sure if this is necessary for a `docker push` to work. It failed both before and after doing it anyway.

I am authenticating:
```
$ docker login
Username (cgavrila): 
WARNING: login credentials saved in /home/cgavrila/.docker/config.json
Login Succeeded
```

And then trying to push an image, but I get this error:
```
$ docker push cgavrila/ubuntu-java
The push refers to a repository [docker.io/cgavrila/ubuntu-java] (len: 1)
2a720e713044: Buffering to Disk 
Error parsing HTTP response: invalid character '<' looking for beginning of value: "<html><body><h1>403 Forbidden</h1>\nRequest forbidden by administrative rules.\n</body></html>\n\n"
```

Any ideas?

**Comment by CGavrila** [comment]
```
$ docker version
Client:
 Version:      1.8.0
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0d03096
 Built:        Tue Aug 11 16:48:39 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.0
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0d03096
 Built:        Tue Aug 11 16:48:39 UTC 2015
 OS/Arch:      linux/amd64

$ docker info
Containers: 61
Images: 72
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 194
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-45-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 3.776 GiB
Name: cgavrila
ID: 2FGX:DCSF:L6GT:MUAL:3NIX:4BU2:V5B5:33EH:N2I6:RAQZ:FETO:CHRU
Username: cgavrila
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

$ uname -a
Linux jmen 3.16.0-45-generic #60~14.04.1-Ubuntu SMP Fri Jul 24 21:16:23 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by donald-s** [comment]
I'm having the same issue. I came across [this StackOverflow post](http://stackoverflow.com/questions/31997045/docker-403-on-push-latest-to-private) that said that updating docker to the latest version - 1.8.1 - will fix the issue. However, it didn't work for me. @CGavrila You might want to give it a try and see if it works for you.

**Comment by CGavrila** [comment]
Sure, @donald-s, I'll give that a go. Do you know of any easy way to do it?

**Comment by CGavrila** [comment]
For future reference, I updated docker on Ubuntu via `apt-get install --only-upgrade docker-engine` and `docker push` now works. Thanks, @donald-s!

**Comment by donald-s** [comment]
@CGavrila  Awesome! I was just about to reply. ;) Glad to hear it worked for you!

**Comment by thaJeztah** [comment]
Thanks @donald-s for assisting!

**Comment by donald-s** [comment]
You're welcome @thaJeztah! Do you know if there are any plans to return a more descriptive error message? I think it would save you all a lot of time in support. It was difficult for me to figure out what was going on. Docker was working fine for me 2 days ago and then it suddenly started returning this cryptic error message yesterday and took me a good while to figure out what was going on.

By the way, great work on this project! :+1:

**Comment by xinzhangcmu** [comment]
any idea on how to do it on OS X with boot2docker? I ran into the same issue with Mac

**Comment by donald-s** [comment]
I'm trying to figure that out myself. I'll let you know if I come up with anything.

**Comment by donald-s** [comment]
@xinzhangcmu I think [this post] (http://blog.javabien.net/2014/03/17/upgrade-docker-and-boot2docker-on-osx/) might help you out.

**Comment by thaJeztah** [comment]
For OS X, there's now also "toolbox", an installer to setup docker and related tools on your Mac; https://docs.docker.com/installation/mac/

I agree on the error message, for some reason, docker tries to handle the response, and outputs the raw HTML as error message. I think this was resolved some time ago, but apparently still in 1.8, I'll have to check

**Comment by xinzhangcmu** [comment]
thanks @donald-s and @thaJeztah

**Comment by donald-s** [comment]
@thaJeztah I used the Docker Toolbox to try to upgrade to 1.8.1, but it didn't work. I just figured out it's because I didn't update my VM machine. (My apologies if this should have been obvious. I'm new to Docker.)

For anyone who might come across this problem in the future:

1. Go install latest version of the Docker Toolbox: https://docs.docker.com/installation/
2. Run `docker-machine upgrade [machine-name]` for each of your VMs.

And you should be good to go!

**Comment by thaJeztah** [comment]
Ah, perhaps that's something to be added

@jeffdm perhaps toolbox should mention that?

**Comment by diogogmt** [comment]
Upgrading boot2docker solved the issue.
Currently running version: 

* Boot2Docker-cli version: v1.8.0
* Git commit: 9a26066

**Comment by dalekurt** [comment]
Confirmed upgrading to v1.8.1b fixed the issue. I switched over to using the toolbox on the Mac, you have to execute `docker-machine upgrade default` after upgrading with toolbox

**Comment by yoanisgil** [comment]
For me I did not even need to upgrade Toolbox, just did:

     docker-machine upgrade [machine-name]

and that did the work ;). Thanks everyone!

**Comment by Josh-a-e** [comment]
I'm encountering this issue on 1.8.2 (both Client and Server) and no docker-machine upgrading has helped - somewhat out of ideas having tried pushing to private and public repos on both hub.docker.com and quay.io.

This is what I encounter:
```
docker push joshae/aaa:bbb
The push refers to a repository [docker.io/joshae/aaa] (len: 1)
Sending image list
Pushing repository docker.io/joshae/aaa (1 tags)
[hash]: Pushing 
HTTP code 403 while uploading metadata: "invalid character '<' looking for beginning of value"
```
It looks like the first few steps resolve successfully, but then the uploading of metadata step fails and the invalid character "<" is the first character in I'm guessing is the standard 403 access denied AWS S3 XML document (or similar).

Any ideas as to things to try next would be much appreciated.

**Comment by hantsy** [comment]
I am using the latest Docker 1.9(Installed from Toolbox 1.9.0 on Windows 10 64bit), got 403 when I was trying to login.

No doubt I have an account of the docker hub, and I can logged in in the web pages.

**Comment by DiogoDoreto** [comment]
@hantsy I'm facing the same issue as you are. I have the same configs: Docker 1.9 on Win10 x64.

```
> docker login
Username: [...]
Password:
Email: [...]
Error response from daemon: Unexpected status code [403] : <html><body><h1>403 Forbidden</h1>
Request forbidden by administrative rules.
</body></html>
```

**Comment by DiogoDoreto** [comment]
As an additional note, `docker login` works if inside the machine with `docker-machine ssh default`

**Comment by thaJeztah** [comment]
@hantsy @DiogoDoreto if you're both on Windows, could it be related to https://github.com/docker/docker/pull/17738 / https://github.com/docker/docker/issues/14336 ?

If you're also unable to log-in from inside the virtual machine, it could be worth a try to contact support@docker.com, in some cases it's related to docker hub or a connection from the region you're in; the support team should be able to check further

**Comment by rainabba** [comment]
Thanks to https://github.com/docker/docker/pull/17738 , I was able to attempt login by providing email, username and password as parameters to login, but then got a 403 and so I still can't login.

**Comment by jcanquelain** [comment]
I have the same issue here, with Docker 1.9.0, on windows 7 x64.

I am able to login from the machine after using `docker-machine ssh default`, but I can't login using directly `docker login`. I have the error "403 Request forbidden by administrative rules."

**Comment by abarsov** [comment]
I have experienced the same issue.
I can't login to docker hub from QuickStart terminal (windows 7, x64) 
and at the same time I can login from virtual bo after docker-machine ssh default

$ docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64

**Comment by mmoayyed** [comment]
Same issue. Windows 10 64-bit. 

```
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64
```

login command fails, but it does work when used inside `docker-machine ssh default`

**Comment by jmcginn13** [comment]
When I tried to ssh in via docker-machine login said it couldn't find the docker daemon, but when I went into the VM directly via Virtual Box it worked fine, maybe need to sudo? when I ssh in I'm docker instead of root. Yea that was it, had to sudo when SSH'ing in. I updated to 1.9.1 and this is still an issue.

**Comment by wordyallen** [comment]
+1

**Comment by wordyallen** [comment]
ssh works fine.

**Comment by ebuzz** [comment]
Same problem on windows 10, but ssh worked fine .

**Comment by bb12489** [comment]
Windows 10 here, and the same issue. SSH works fine.

**Comment by N0bl3** [comment]
Same issue on Windows 10 x64 Didn't try SSH.

**Comment by jm3** [comment]
same issue, OS X, Docker latest.
