### ISSUE TITLE
Docker inspect should show the command used to create the container

### ISSUE THREAD

**Issue by etopian** [docker/docker#15614]
It would be nice for Docker to be able to recall the exact command used to create the container. It's very useful for upgrading an existing container or starting a new one.

**Comment by thaJeztah** [comment]
This was proposed a few times, but rejected, see for example and info how to achieve this, https://github.com/docker/docker/issues/4480, https://github.com/docker/docker/issues/13302, https://github.com/docker/docker/issues/9150, https://github.com/docker/docker/issues/9924 https://github.com/docker/docker/issues/9007
