### ISSUE TITLE
apt.dockerproject.org is not working

### ISSUE THREAD

**Issue by pdericson** [docker/docker#15616]
```
$ curl https://apt.dockerproject.org/

<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 Connection refused</title>
  </head>
  <body>
    <h1>Error 503 Connection refused</h1>
    <p>Connection refused</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-syd1625-SYD 1439723427 3810394181</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
```

**Comment by thaJeztah** [comment]
ping @jfrazelle

**Comment by linqinli** [comment]
same issue I encounter

$ ping apt.dockerproject.org
PING j.global-ssl.fastly.net (103.245.222.68) 56(84) bytes of data.
64 bytes from 103.245.222.68: icmp_seq=1 ttl=128 time=160 ms
64 bytes from 103.245.222.68: icmp_seq=2 ttl=128 time=155 ms
64 bytes from 103.245.222.68: icmp_seq=3 ttl=128 time=164 ms

**Comment by johnae** [comment]
Yeah I'm having problems too.

**Comment by sunmh207** [comment]
I have the same issue

**Comment by thaJeztah** [comment]
I think it's down for everyone, but unfortunately it's 4.30 am on a Sunday in San Fransisco and afaik, these servers are managed by the open source project maintainers, not Docker, Inc., so no 24/7 support here

**Comment by yoramw** [comment]
I have the same issue too.

**Comment by ernestyao** [comment]
Same issue here and I was installing docker.

**Comment by thaJeztah** [comment]
As a temporary solution, the static builds can still be found on get.docker.com; see https://docs.docker.com/installation/binaries/#get-the-docker-binary

**Comment by pdericson** [comment]
fwiw *.dockerproject.org isn't mentioned on https://status.docker.com/

**Comment by thaJeztah** [comment]
@pdericson I think that's because it's not managed by Docker, Inc. (but it would make sense to have it included there - I noticed it as well)

@pdericson could you create a separate issue for that / feature request?

**Comment by jfrazelle** [comment]
fixed we are kinda getting ddosed tho, i will try to block the ips

**Comment by pdericson** [comment]
@thaJeztah thanks, good suggestion - I have created https://github.com/docker/docker/issues/15619

@jfrazelle thanks for the quick turnaround :)

**Comment by thaJeztah** [comment]
thank so much @jfrazelle, you rule!

**Comment by johnae** [comment]
awesome @jfrazelle thank you very much!

**Comment by linqinli** [comment]
nice job! @jfrazelle

**Comment by jfrazelle** [comment]
I'm assuming this was some cron jobs or ci's that are misconfigured on someone servers and just overly hitting us, which means if your ip is now blocked and you are still getting a 502 (or 501) that's you :P and let me know

**Comment by metavige** [comment]
If I use apt-cacher-ng, it will cause 403 error.
But if I remove apt proxy setting, it's ok.

I don't know why.

**Comment by advanderveer** [comment]
will this be happening every sunday?: 

```
ubuntu@ip-10-220-1-167:~$ curl https://apt.dockerproject.org/

<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 Connection refused</title>
  </head>
  <body>
    <h1>Error 503 Connection refused</h1>
    <p>Connection refused</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-lhr6331-LHR 1441529996 3381375556</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
```

**Comment by skinnyworm** [comment]
Happening again? I've got 503 as well.

**Comment by skinnyworm** [comment]
My IP is 116.226.186.39, hope it is not on the block-list

**Comment by AlexZeitler** [comment]
Ran into this also... sunday again.

**Comment by Micka33** [comment]
```
$ curl https://apt.dockerproject.org/

<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 Connection refused</title>
  </head>
  <body>
    <h1>Error 503 Connection refused</h1>
    <p>Connection refused</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-lhr6331-LHR 1441537303 3413366959</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
```

**Comment by Dids** [comment]
+1, hoping this gets fixed asap.

**Comment by Micka33** [comment]
how can anyone query `apt.dockerproject.org` that much, for such a long time ! (3hours till now)

**Comment by xianminx** [comment]
+1

**Comment by mvanholsteijn** [comment]
Can somebody reopen this again? Same problem....

**Comment by Micka33** [comment]
@mvanholsteijn it's reopened here https://github.com/docker/docker/issues/16101

**Comment by stenote** [comment]
My IP is 133.130.55.133, hope it is not on the block-list

**Comment by jeffman78** [comment]
Same issue (503 Error) when trying to access ``https://apt.dockerproject.org/``.

**Comment by lastboy** [comment]
I got this issue just now... 
Any workaround for that one?

10x

**Comment by Micka33** [comment]
@lastboy see https://github.com/docker/docker/issues/16101#issuecomment-138078533 for a workaround.

**Comment by jfrazelle** [comment]
its back up and if people could not set up faulty cron jobs that ping us at hundreds of thousands of requests per second that would be great.
Also just because it happened once before on a sunday weeks ago doesnt mean there is a pattern :p

**Comment by AlexZeitler** [comment]
@jfrazelle :+1: 
Sunday ping from hell :imp: :smile: 
No Docker on Sunday makes us sad pandas :panda_face:

**Comment by xianminx** [comment]
@GordonTheTurtle, thanks for the reminder. I am sorry to catch what you mean by `The people listed below have appreciated your meaningfull discussion with a random +1:`. 
Do you mean that I should not spam with "+1" action? 

ps: there is a minor typo: `meaningfull` -> `meaningful`
