### ISSUE TITLE
Docker incorrectly reports bad certificate on version mismatch when using verifytls 

### ISSUE THREAD

**Issue by lukebarton** [docker/docker#15622]
```
➜  ~  docker info
An error occurred trying to connect: Get https://HOST:2376/v1.19/info: remote error: bad certificate

➜  ~  /usr/local/Cellar/curl/7.43.0/bin/curl https://HOST:2376/v1.19/info \
  --cert ~/.docker/machine/machines/HOST/server.pem \
  --key ~/.docker/machine/machines/HOST/server-key.pem \
  --cacert ~/.docker/machine/machines/HOST/ca.pem
client and server don't have same version (client : 1.19, server: 1.18)

➜  ~  /usr/local/Cellar/curl/7.43.0/bin/curl https://HOST:2376/v1.18/info \
  --cert ~/.docker/machine/machines/HOST/server.pem \
  --key ~/.docker/machine/machines/HOST/server-key.pem \
  --cacert ~/.docker/machine/machines/HOST/ca.pem
{"Containers":1,"Debug":0, ... }
```

**Comment by lukebarton** [comment]
No, you don't need more info. I gave you all the info and demonstrated the problem. It's a simple bug, docker reports a bad certificate when versions of the docker a mismatched between client and server. The title describes this, the console log demonstrates this. If you're unhappy with the report, please just close the issue as I have no interest in explaining it much more than I already have. It's more than enough for someone to begin working with.

**Comment by dmp42** [comment]
Hi @lukebarton 

@GordonTheTurtle is a bot.

**Comment by cpuguy83** [comment]
I am not able to reproduce this.
It seems the certs specified in your env may not be correct.
Can you verify your env?

```
root@4209c3d74353:/go/src/github.com/docker/docker# docker --tlsverify info
Error response from daemon: client is newer than server (client API version: 1.21, server API version: 1.20)
```

**Comment by cpuguy83** [comment]
Closing due to no response.
Ping here if you can provide a way to repro with the latest version of docker.
Thanks!

**Comment by JoyceBabu** [comment]
@cpuguy83  I am seeing this error message after I upgraded to the experimental version of docker (1.9.0-dev).
