### ISSUE TITLE
COPY fails when path starts with "null"?

### ISSUE THREAD

**Issue by tgpfeiffer** [docker/docker#15634]
I have a Dockerfile that contains the line

    COPY nullmailer /etc/nullmailer

and when I run `docker build .`, I get

    Step 15 : COPY 
    COPY requires at least two arguments

When I change the line to

    COPY hogenullmailer /etc/nullmailer

then it still fails (because there is no `hogenullmailer` file), but I get the correct error message:

    Step 15 : COPY hogenullmailer /etc/nullmailer
    hogenullmailer: no such file or directory

If I rename `nullmailer` to `hogenullmailer` then the process runs fine and I can build my image. Note that `COPY ["nullmailer", "/etc/nullmailer"]` also works.

    $ sudo docker version
    Client version: 1.7.1
    Client API version: 1.19
    Go version (client): go1.4.2
    Git commit (client): 786b29d
    OS/Arch (client): linux/amd64
    Server version: 1.7.1
    Server API version: 1.19
    Go version (server): go1.4.2
    Git commit (server): 786b29d
    OS/Arch (server): linux/amd64

This seems to be a recently introduced problem; I could build the same Dockerfile fine before the latest `apt-get dist-upgrade`.

**Comment by duglin** [comment]
funny - I think its because it treats it as JSON but will investigate further....

**Comment by vdemeester** [comment]
@tgpfeiffer @duglin Reproduced it (using a integration test).. I think you're right, it might be a JSON thingy :sweat_smile:
