### ISSUE TITLE
question: any gotchas (e.g. EISDIR) around reading host mounted files from node app?

### ISSUE THREAD

**Issue by tony-kerz** [docker/docker#15637]
i'm trying to run a docker image containing a node app which wants to read a file mounted from the host.

something like this:

```
docker run -v /some/path/with/a/symlink/myfile.json:/myfile.json username/imagename
```

but (i think) since the LHS of the `-v` arg contains a symlink i'm getting the following from the node app:

```
Error: EISDIR: illegal operation on a directory, read
```

in my particular case, the host file resides in a jenkins workspace which apparently has a symlink along it's path.

is this a known behavior w.r.t. mounting host volumes which contain symlinks?

any guidance around this appreciated!

regards,
tony.

```
$ docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64
```
```
$ docker info
Containers: 56
Images: 64
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 178
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.1 (TCL 6.3); master : 7f12e95 - Thu Aug 13 03:24:56 UTC 2015
CPUs: 8
Total Memory: 1.955 GiB
Name: dev
ID: AUM7:QALE:ORN7:BMDR:KAHE:UL5F:HIQE:I5VU:UTIR:ULQJ:HYVT:WFRP
Debug mode (server): true
File Descriptors: 12
Goroutines: 19
System Time: 2015-08-17T16:17:52.352050585Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: <blah>
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```
```
$ uname -a
Darwin <blah>.local 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64
```

**Comment by tonistiigi** [comment]
I think there's something more going on here than just symlink path. I tested this and seemed to work fine. Can you test with a simple example where you create a symlink and try to mount it on a busybox with a volume. Maybe its a special kind of symlink(for example links to parent, or broken symlink) or the way your image is using the volume. From the error it seems that it is mixing up directories and files somewhere.

**Comment by thaJeztah** [comment]
I see this is a boot2docker setup; if the symlink is on the host, and resolves to a path outside of `/Users/`, will that still work? Given that, by default, only the  `/Users/` directory is shared with the VM using VirtualBox guest additions. Could that be an issue here?

**Comment by tony-kerz** [comment]
k, so (as usual), this is more complicated than i had originally hoped.
i first encountered the `EISDIR` node error on a linux based jenkins slave with this profile:
```
+ docker version
Client version: 1.0.1
Client API version: 1.12
Go version (client): go1.2.1
Git commit (client): 990021a
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.3.3
Git commit (server): a8a31ef-dirty
```
```
+ docker info
Containers: 18
Images: 245
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 3.19.0
```
```
+ uname -a
Linux dockerclient 3.19.0 #2 SMP Thu Mar 26 10:44:46 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
 ```

so i'm trying something like this:

```
docker run -v /var/tmp/workspace/my-workspace/my-file.json:/app/my-file.json...
```
and here is the (cascading) folder info for the host mount point:

```
+ ls -lad /var
drwxr-xr-x 1 root root 4096 Aug  6 16:03 /var
+ ls -lad /var/tmp
drwxrwxrwt 1 root root 4096 Aug 11 20:35 /var/tmp
+ ls -lad /var/tmp/workspace
drwxr-xr-x 6 root root 4096 Aug 18 01:38 /var/tmp/workspace
+ ls -lad /var/tmp/workspace/my-workspace
drwxr-xr-x 5 root root 4096 Aug 17 14:54 /var/tmp/workspace/my-workspace
+ ls -la /var/tmp/workspace/my-workspace/my-file.json
-rw-r--r-- 1 root root 170 Aug 17 14:52 /var/tmp/workspace/my-workspace/my-file.json
```

(so apparently, it has nothing to do with sym-links)

then i started trying to debug it on my mac-book which is the profile i originally posted above.

after my original post, i did see the below note on [this page of the documentation](https://docs.docker.com/userguide/dockervolumes/#mount-a-host-directory-as-a-data-volume):
> Note: If you are using Docker Machine on Mac or Windows, your Docker daemon only has limited access to your OS X/Windows filesystem. Docker Machine tries to auto-share your /Users (OS X)

which probably explains the `EISDIR` when i try to mount from a spot other than `/Users` on osx,
so osx/docker-machine/boot-2-docker has it's own details that make it non-ideal to debug my real issue which exists in a linux environment.

so, apologies for the misdirection, i should have posted details around my 'deployed' runtime environment vs my local environment...

still appreciated any suggestions around the `EISDIR` in the linux environment...

**Comment by tonistiigi** [comment]
These are pretty old versions, especially the client. Can you upgrade?

One thing you can do is to double check that your host path really exists. Maybe the machines are mixed up or something. Just because this is exactly the error you would get if the host path is not there, then new directory is created on the host and you can't `readFileSync` that directory.

**Comment by tony-kerz** [comment]
thanks t2, yeah, those are pretty old, and docker is a fast moving product, so that's a good place to start for sure. 

i'll look into updating docker in those jenkins slaves, an associate of mine set them up, i think they came in a docker image themself, but we should be able to re-create with recent versions of docker.

the host path/file is def there as those `ls -lad` commands from above were run from within the jenkins job that is also executing the `docker run -v` command.

**Comment by tony-kerz** [comment]
i finally figured out what was going with this:

brief context: i'm working on a jenkins based workflow which is supposed to build a docker image from git, and then deploy it somewhere via a json based request. The json based request is generated
via a docker-ized Node app, so i want to run the docker-ized Node app from a jenkins build
mounting an input json file from the git source in the jenkins workspace.

* create `Dockerfile` mashup based on official jenkins with docker added, something like:
```
FROM jenkins
RUN apt-get -y install docker.io
```

* build image using something like:
```
docker build tonykerz/jenkins-docker .
```

* run image, applying the following mounts 
  * `-v /var/run/docker.sock:/var/run/docker.sock` so docker in image uses container on host
  * `-v /var/jenkins_host:/var/jenkins_home` so jenkins data is persisted on host

so the above represents the jenkins run-time setup.

i can then add jobs to jenkins to build specific apps.

* so within one of those build jobs, the `config.json` file is in the root of the git project, and thus the root of the jenkins build workspace, and i want to invoke the node app like so:

```
run -v $(pwd)/config.json:/config.json tonykerz/my-node-app
```

so, the above command is the one that gave me grief.

probably, the Docker afficianados can spot the issue straight away, 
but what happened is that `tonykerz/my-node-app` couldn't
find `/config.json`, initially throwing an `EISDIR`.

the issue is that `$(pwd)` from above resolved to something like `/var/jenkins_home/...`
which only exists in the container running jenkins and NOT on the ultimate host,
so `docker run` created a __directory__ on the host at `/var/jenkins_home/...` and mounted it.

the node app then proceeded to try and use the directory as a file and threw an `EISDIR`...

what i ended up doing to get past this was to do something like this in the jenkins job:

```
run -v /var/jenkins_host/.../config.json:/config.json tonykerz/my-node-app
```

which seems kind of hacky to me because it requires that the jenkins job know
the path to which it's home directory was bound on the host (def abstraction leakage).

open to any suggestions around this, but just wanted to share and close out this issue
with some explanation.

regards,
tony.
