### ISSUE TITLE
Wildcard Symlink

### ISSUE THREAD

**Issue by alexandarp** [docker/docker#15647]
Hello,

I am trying to set a wildcard symlink in my Dockerfile so my tomcat instance can instantly pickup and deploy an application without having to hardcode a version.

Here is the line in the Dockerfile:

```
RUN ln -snfv /path/to/app/app-*-snapshot path/to/tomcat/webapps/app-name
```
The symlink doesn't work inside the Dockerfile but works on my local machine. I have a feeling that docker isn't evaluating the '*' character as a wildcard. Does anyone have experience using wildcards in docker?

Any help is appreciated.

**Comment by cpuguy83** [comment]
@alexandarp Docker isn't evaluating it at all, it should be parsed by `/bin/sh` in the container.

**Comment by alexandarp** [comment]
I forgot that you could do that, thanks @cpuguy83!
