### ISSUE TITLE
API/inspect container no longer returns path in Volumes map

### ISSUE THREAD

**Issue by cybercode** [docker/docker#15644]
As of 1.8.x, inspecting a container no longer returns the path to the persistent volume under the `Volumes` map, but instead in the `Mounts` slice (therefore unkeyed!) entries. For example:

```json
 "Volumes": {
            "/etc/nginx/certs": {},
            "/var/cache/nginx": {}
        },
```
...
```json
"Mounts": [
         {
            "Name": "bb9d6cf96309ae1c15984764a148022395edf1fa3f9399a8a99c3763be2fa612",
            "Source": "/var/lib/docker/volumes/bb9d6cf96309ae1c15984764a148022395edf1fa3f9399a8a99c3763be2fa612/_data",
            "Destination": "/var/cache/nginx",
            "Driver": "local",
            "Mode": "",
            "RW": true
        },
        {
            "Name": "ec61b53e4faf593997241230429e19a3b2d956dfb56ee87eacf80e5fd5773b99",
            "Source": "/var/lib/docker/volumes/ec61b53e4faf593997241230429e19a3b2d956dfb56ee87eacf80e5fd5773b99/_data",
            "Destination": "/etc/nginx/certs",
            "Driver": "local",
            "Mode": "",
            "RW": true
        }
    ],
```

Note that the documentation still states that the `Volumes` map contains the host path and r/w status.

**Comment by tonistiigi** [comment]
Where is that wrong documentation? https://docs.docker.com/reference/api/docker_remote_api_v1.20/#inspect-a-container seems correct to me. The Volumes map is still in the config object but not in the main object any more.

**Comment by cybercode** [comment]
The userguide: https://docs.docker.com/userguide/dockervolumes/#locating-a-volume. The api docs are correct for v1.20 but, nowhere can i find mention of this significant change, other than diff'ing the docs.

As a aside, listing all the mount points as an array containing all mounts (not just volumnes) vs a hash keyed by destination makes actually using the info much more difficult.

**Comment by thaJeztah** [comment]
Thanks @cybercode! This is now fixed (not yet published to the website) in https://github.com/docker/docker/issues/15671
