### ISSUE TITLE
can't filter by label if label is added in a commit

### ISSUE THREAD

**Issue by arieb** [docker/docker#15659]
BUG REPORT INFORMATION
========================
Description of problem:
im trying to create a new image by committing a container and add a few labels in the process and then to filter only the images with the given labels.
This doesn't seem to work

`docker version`:
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

`docker info`:
Containers: 1
Images: 114
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 116
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-52-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 7.705 GiB
Name: asgard
ID: VQVB:Y2YF:V43V:27C4:7P3F:GNCA:M6UK:Q2AC:SBNH:I6MK:MYWD:3OTC
WARNING: No swap limit support

`uname -a`:
Linux asgard 3.13.0-52-generic #86-Ubuntu SMP Mon May 4 04:32:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
physical (laptop)

How reproducible:
* Commit a container add add new labels to it using the -c flag
* run `docker images -f` and try to filter the images using the labels you added.

Steps to Reproduce:
```bash
docker run -ti --name bar ubuntu:12.04.5 /bin/bash
root@bar:/# .. do some stuff...
```
now i commit the container to a new image
```bash
docker commit -c "LABEL foo.version=1.0.0-1" -c "LABEL foo.name=bar" -c "LABEL foo.author=starlord" bar bar:1.0.0-1
```
now i try run `docker images` with a filter to find it
```bash
docker images -f label=foo.version=1.0.0-1
# no images found
```

Actual Results:
```bash
docker images -f label=foo.version=1.0.0-1
# no images found
```

Expected Results:
```bash
docker images -f label=foo.version=1.0.0-1
# bar image information
```

Additional info:

here is an example of `docker inspect` of the new image
```json
[
{
    "Id": "e6d5e3183adab1ccc6ce11a8b352a614bf94ac938654496f7873e1587fec65f2",
    "Parent": "9e18ba0255e99e7ab4e06b1b01787c889024aae4f0508f66c3d383edb51fce1f",
    "Comment": "Bar",
    "Created": "2015-08-18T11:21:36.13759834Z",
    "Container": "cb734c639cbc81b2daaadf651d837be8274c904c084c53315e797497a2e96858",
    "ContainerConfig": {
        "Hostname": "bar",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": true,
        "AttachStderr": true,
        "ExposedPorts": null,
        "PublishService": "",
        "Tty": true,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        ],
        "Cmd": [
            "/bootstrap.sh",
        ],
        "Image": "ubuntu-foo-base",
        "Volumes": null,
        "VolumeDriver": "",
        "WorkingDir": "",
        "Entrypoint": null,
        "NetworkDisabled": false,
        "MacAddress": "",
        "OnBuild": null,
        "Labels": {}
    },
    "DockerVersion": "1.8.1",
    "Author": "Foo Team",
    "Config": {
        "Hostname": "",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": {
            "443/tcp": {},
            "80/tcp": {}
        },
        "PublishService": "",
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        ],
        "Cmd": null,
        "Image": "",
        "Volumes": null,
        "VolumeDriver": "",
        "WorkingDir": "",
        "Entrypoint": [
            "/usr/bin/python3",
            "-u",
            "/sbin/my_init",
            "--skip-startup-files"
        ],
        "NetworkDisabled": false,
        "MacAddress": "",
        "OnBuild": null,
        "Labels": {
            "foo.version": "1.0.0-1",
            "foo.name": "bar",
            "foo.author": "starlord",
        }
    },
    "Architecture": "amd64",
    "Os": "linux",
    "Size": 1089856717,
    "VirtualSize": 1349562321,
    "GraphDriver": {
        "Name": "aufs",
        "Data": null
    }
}
]
```
----------END REPORT ---------

#ENEEDMOREINFO

**Comment by vdemeester** [comment]
@arieb I could reproduce this using the latest master too. I'll take a look :wink: #dibs.

**Comment by thaJeztah** [comment]
ping @calavera possibly for 1.8.2  ?

**Comment by calavera** [comment]
I rather not added to 1.8.2 if it was not introduced in 1.8

**Comment by thaJeztah** [comment]
@calavera fair, I'll check; IIRC, this option to allow committing *labels* was added recently; not sure if it was 1.8 or 1.7. Looks like the "commit" option was added in https://github.com/docker/docker/pull/13744

**Comment by arieb** [comment]
hey @vdemeester any update on this?

**Comment by vdemeester** [comment]
@arieb yea, PR #15503 is waiting for reviews. There is a few ways to fix this so this is why it's in design-review :wink:.
