### ISSUE TITLE
Docker experimental -p with default-network=overlay:multihost bug

### ISSUE THREAD

**Issue by emsi** [docker/docker#15663]
Hi!

I just started to experiment with docker 1.9.0-dev, swarm and multihost networking and I encounter, what I believe, is a docker engine bug that manifests itself when ```default-network=overlay:multihost ```is used (or any other nondefault network for that matter).

To reproduce the bug I have setup an environment kind of like in this blog post:
https://sirile.github.io/2015/07/15/docker-swarm-and-experimental-multihost-networking-with-docker-machine-and-boot2docker.html
it's based on:
https://github.com/docker/docker/blob/master/experimental/compose_swarm_networking.md
though it uses virtualbox rather than digital ocean.
My setup uses vmware ESXi but I don't think it's relevant. 

The bug manifests itself when the docker daemon is run with ```default-network=overlay:multihost``` (one swarm host is enough to reproduce it as the bug seems to be in docker engine). 
When I run the command:
```
docker run  --net bridge --name nginx -p 8080:80 -d nginx
```
(I should have added ```--net bridge``` to publish it on target host!) 
It seems to NOT work (no ports are published):
```
# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
9f0baac7e8df        nginx               "nginx -g 'daemon off"   2 minutes ago       Up 2 minutes                            swarm-1/nginx
```

However what happens is that the docker_proxy was run on the docker host:
```
docker@swarm-1:~$ sudo netstat  -lnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 10.168.113.36:7946      0.0.0.0:*               LISTEN      1223/docker
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      924/sshd
tcp        0      0 :::2376                 :::*                    LISTEN      1223/docker
tcp        0      0 :::8080                 :::*                    LISTEN      2578/docker-proxy
```
and the iptables rules were created anyway. The port forwarding WORKS on the host.

This could be treated as undefined behavior however when I remove that container the docker_proxy is not killed and keeps the port binding so I cannot publish anything on that host any more even though the container that it redirects to is not existing any more:
```
l# docker $(docker-machine config swarm-1) ps -a       
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
f53274466d44        swarm:latest        "/swarm join --addr 1"   54 minutes ago      Up 53 minutes       2375/tcp            distracted_visvesvaraya
# docker $(docker-machine config swarm-1) run --name nginx2 -p 8080:80 -d nginx
b2ea3f05b2a16e1df95e93cf441f9a75546abe16a3e5677fb3c9d012bc1e2127
Error response from daemon: Cannot start container b2ea3f05b2a16e1df95e93cf441f9a75546abe16a3e5677fb3c9d012bc1e2127: Bind for 0.0.0.0:8080 failed: port is already allocated
```
(this error it not apparent if I directly interact with the swarm as it is not passed to the client, comand exits silently without any error).

The same is true for the service that remains published even though there is no container:
```
# docker $(docker-machine config swarm-1) service ls
SERVICE ID          NAME                      NETWORK             CONTAINER
4a0a0afe5f74        distracted_visvesvaraya   bridge              f53274466d44
18960200160c        nginx                     bridge              
```
The removal of the container leaves clutter as it thinks that there are not ports published which is not the case.

To clean this up I had to manually unpublish the service:
```
docker $(docker-machine config swarm-1) service unpublish nginx.bridge
```
which solved the problem and is a workaround. :)

**Comment by cpuguy83** [comment]
Have you tried to reproduce this issue on the stable release?
It should largely have the same behavior, just that the experimental build has some extra UI bits.

**Comment by emsi** [comment]
The stable version does not support ```docker network``` so it cannot be affected.

**Comment by cpuguy83** [comment]
@emsi As far as I can see in your post, you aren't using `docker network` API's, just `--net=bridge` (which is the default).

Also wondering if you see the issue with the default being set to bridge.

**Comment by mavenugo** [comment]
@emsi @cpuguy83 I believe he meant `--default-network` which is also only in experimental channel which internally creates a network for the given `--default-driver`.
@emsi thanks for reporting the issue. I will take a look at it.

**Comment by emsi** [comment]
@mavenugo: yes, exactly. The behavior is caused when ```default-network``` is set. 
Thank you for taking care.

**Comment by mavenugo** [comment]
@emsi I could reproduce the issue *only* in the experimental version using these steps -
`sudo docker service publish nginx.bridge`
`sudo docker run  --net bridge --name nginx -p 8080:80 -d nginx`
btw, this is nothing to do with `--default-network` daemon configuration.

The reason for this behavior is the inherent assumption that container name is same as the existing service and hence the `-p` is ignored.

This issue will be addressed with the help of couple of upcoming changes in the to the CNM behavior -
1. Ability to connect containers to a network/scope without the need to publish a service
2. ability to publish ports in `service pubilsh`.

Thanks for reporting the issue. Added this to the 1.9.0 milestone.

**Comment by mavenugo** [comment]
@emsi with the latest UX changes, there is no more `service publish` and no more `--default-network`.
Also, the scenario that i mentioned is not possible any more because the service and container name cannot be individually configured. I guess this issue can be closed.

Pls reopen this issue If you see this again in the latest docker master (yes, we have exited experimental)
