### ISSUE TITLE
docker-engine in ubuntu overwrites /lib/systemd/system/docker.service

### ISSUE THREAD

**Issue by kryton** [docker/docker#15670]
hi guys.
is it possible to mark this file as 'config' so you don't wipe out the changes I need to make to it so I can have docker running on my system?

the old way used to read from /etc/default/docker . I don't know if there is a 'new' way to do this

**Comment by cpuguy83** [comment]
ping @tianon @jfrazelle

**Comment by tianon** [comment]
Yeah, see https://docs.docker.com/articles/systemd/
