### ISSUE TITLE
Unable to connect to container running MongoDB  from the host machine on initial boot

### ISSUE THREAD

**Issue by javmorin** [docker/docker#15674]
Upon upgrading my docker install to 1.8.1 (from 1.7.1) I could no longer connect to a container running an instance of MongoDB from the hosting machine despite exposing the ports.

### Command used:
```
docker run -d --name=mongo -v /data/mongodb:/data/db -p 127.0.0.1:27017:27017 -p 127.0.0.1:28017:28017 mongo:2.6 -smallfiles --rest --httpinterface
```

### Details:
 - When run with docker 1.8.1, the container starts, and I can connect within the container (using `docker exec`). Running any mongo connecting application on the host machine stalls and never completes connection.

 - When run with docker 1.7.1 (after downgrading from 1.8.1), I am able to connect from the host machine without issue.

- `netstat` shows the same listening connections with both versions
- `docker exec -it mongo mongo` works with both versions

Please let me know any debugging information I can provide to resolve this issue.

**Comment by javmorin** [comment]
While working to collect the additional data requested, the issue resolved itself. I wonder if it was bad state left around as part of the 1.7 > 1.8 upgrade. As I can no longer reproduce (I've tried) I am closing this issue.

**Comment by thaJeztah** [comment]
Thanks @javmorin. Feel free to reopen if you encounter it again and have more information :+1:

**Comment by javmorin** [comment]
I have come to realize that this is not resolved, but it's cause is different from what I thought. The issue seems to occur on initial boot for my laptop. I am connected on both WiFi and LAN (not sure that matters), and when I start my mongodb container (it's not set to start automatically) I am not able to connect to it. I am certain that this was NOT needed with docker 1.7 as I have been using this workflow for several months to run a specific version of MongoDB

### Steps to reproduce
1. Boot machine with docker 1.8.1 installed + enabled and mongodb installed but disabled on host 
1. Open terminal and start a mongodb container. (I am using mongo:2.6)
1. run `mongo` shell CLI and note that connection is not completed (says "connecting" but never shows connected prompt)

### Experienced behavior
Upon startup, call `docker start mongo` and have MongoDB boot and allow connection from the host system (ports are exposed direct on the host). Instead the `mongo` client hangs waiting for the connection to complete (would likely timeout if left for long enough).  Stopping the container, restarting the docker service (running Arch so using docker.service systemd unit) and restarting the container allows the connection to be made.

### Expected behavior
Upon startup, call `docker start mongo` and have a running MongoDB instance I can connect to from the host system.

### Environment details
`$ docker version`
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Sat Aug 15 17:29:10 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Sat Aug 15 17:29:10 UTC 2015
 OS/Arch:      linux/amd64

`$ docker info`
Containers: 1
Images: 14
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.6-1-ARCH
Operating System: Arch Linux
CPUs: 4
Total Memory: 15.38 GiB
Name: neo
ID: MHPF:AJNE:N3BU:HGDF:VO4A:E3AO:3OQZ:5UDS:4NZY:MJFZ:WFBC:NEGE

`$ uname -a`
Linux neo 4.1.6-1-ARCH #1 SMP PREEMPT Mon Aug 17 08:52:28 CEST 2015 x86_64 GNU/Linux

`$ iptables -L DOCKER`
Chain DOCKER (1 references)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             172.17.0.1           tcp dpt:28017
ACCEPT     tcp  --  anywhere             172.17.0.1           tcp dpt:27017


I now know that I can readily reproduce the issue on my machine, so if there is anything additional that would be helpful, please let me know.

**Comment by javmorin** [comment]
Still looking for some insight here.. I went ahead and did a couple more non-working/working config comparisons

`systemctl` output is effectively unchanged (for net items) after the docker restart
`iptables-save` output is also unchanged
`route` output however _is_ different.

__Before:__```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.0.1     0.0.0.0         UG    100    0        0 enp0s25
0.0.0.0         192.168.0.1     0.0.0.0         UG    600    0        0 wlp3s0
192.168.0.0     0.0.0.0         255.255.255.0   U     100    0        0 enp0s25
192.168.0.0     0.0.0.0         255.255.255.0   U     600    0        0 wlp3s0
```

__After:__```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.0.1     0.0.0.0         UG    100    0        0 enp0s25
0.0.0.0         192.168.0.1     0.0.0.0         UG    600    0        0 wlp3s0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.0.0     0.0.0.0         255.255.255.0   U     100    0        0 enp0s25
192.168.0.0     0.0.0.0         255.255.255.0   U     600    0        0 wlp3s0
```

Note the lack of a route for the docker0 interface in the first output. If there are any other before/after settings snapshots I can take to help resolve this issue, please let me know. Really would be nice to not have to restart docker every time I boot my machine.

**Comment by thaJeztah** [comment]
Thanks for the detailed info, @javmorin 


ping @mrjana @mavenugo could you have a look at this?

**Comment by javmorin** [comment]
@mrjana I will try to do this later today. I was away for the Labor Day holidays.

**Comment by javmorin** [comment]
1.8.2-rc1 does seem to fix this issue. I've verified by switching the binaries around twice. The 1.8.2-rc1 binary works on initial boot with no restart required where the 1.8.1 binary does not.

**Comment by thaJeztah** [comment]
Thanks for testing, and confirming its resolved! I'll close this issue again :+1:

**Comment by mrjana** [comment]
@javmorin Thanks for confirming
