### ISSUE TITLE
Container file-system has become read-only after some time

### ISSUE THREAD

**Issue by jtbcgdv** [docker/docker#15689]
Docker is running as part of a Kubernetes cluster on AWS.
It's running a jenkins container that's very similar to the official DockerHub image.
The container has been running for a couple of days but the file-system has become read-only so that jenkins executor threads fail.  It used to run jobs correctly

`java.io.IOException: Failed to create a temporary file in /var/jenkins_home/jobs/jenkins-s3-backup
	at hudson.util.AtomicFileWriter.<init>(AtomicFileWriter.java:68)
	at hudson.util.AtomicFileWriter.<init>(AtomicFileWriter.java:55)
	at hudson.util.TextFile.write(TextFile.java:118)
	at hudson.model.Job.saveNextBuildNumber(Job.java:290)
	at hudson.model.Job.assignBuildNumber(Job.java:348)
	at hudson.model.Run.<init>(Run.java:290)
	at hudson.model.AbstractBuild.<init>(AbstractBuild.java:170)`

Linux ip-172-20-0-164 3.19.0-20-generic #20-Ubuntu SMP Fri May 29 10:10:47 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64

Containers: 34
Images: 241
Storage Driver: aufs
 Root Dir: /mnt/ephemeral/docker/aufs
 Backing Filesystem: extfs
 Dirs: 309
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.19.0-20-generic
Operating System: Ubuntu 15.04 (containerized)
CPUs: 2
Total Memory: 7.304 GiB
Name: ip-172-20-0-164
ID: 2H52:TOTX:6FDO:3E5C:MGQ5:GCEZ:7BJF:LSRW:O523:BBWB:ZSLZ:NR5K
Debug mode (server): false
Debug mode (client): true
Fds: 99
Goroutines: 226
System Time: Wed Aug 19 08:32:06 UTC 2015
EventsListeners: 0
Init SHA1: 9145575052383dbf64cede3bac278606472e027c
Init Path: /usr/bin/docker
Docker Root Dir: /mnt/ephemeral/docker
WARNING: No swap limit support

Running Kubernetes cluster (v 1.0.1) on AWS (m3.large)

Filesystem                            Size  Used Avail Use% Mounted on
udev                                  3.7G     0  3.7G   0% /dev
tmpfs                                 748M   76M  673M  11% /run
/dev/xvda1                            7.8G  2.5G  5.0G  34% /
tmpfs                                 3.7G  2.8M  3.7G   1% /dev/shm
tmpfs                                 5.0M     0  5.0M   0% /run/lock
tmpfs                                 3.7G     0  3.7G   0% /sys/fs/cgroup
/dev/mapper/vg--ephemeral-docker       30G   26G  2.4G  92% /mnt/ephemeral/docker
/dev/mapper/vg--ephemeral-kubernetes  1.4G  1.1G  269M  80% /mnt/ephemeral/kubernetes
tmpfs                                 748M     0  748M   0% /run/user/1000

**Comment by jtbcgdv** [comment]
The docker root dir mount has changed to read-only so it's not a docker issue:

selected output from `/proc/mounts`

`/dev/mapper/vg--ephemeral-docker /mnt/ephemeral/docker ext4 ro,noatime,stripe=16,data=ordered 0 0`
`/dev/mapper/vg--ephemeral-kubernetes /mnt/ephemeral/kubernetes ext4 rw,noatime,data=ordered 0 0`

**Comment by willmore** [comment]
@jtbcgdv I hit this issue as well with Docker/Kubernetes/AWS - by any chance did you come across how/why the filesystem became read-only?

**Comment by willmore** [comment]
Found source of issue - same as: https://github.com/kubernetes/kubernetes/issues/12905
