### ISSUE TITLE
libc.so truncated when multiple perf processes are run

### ISSUE THREAD

**Issue by awreece** [docker/docker#15680]
I've been struggling for a while to hunt down a fairly strange issue. In short, I've been having a lot of difficulty running multiple `perf` invocations in my container. I frequently get an issue where `libc.so` is truncated: 

```
ls: error while loading shared libraries: /lib/x86_64-linux-gnu/libc.so.6: file too short
```

By leaving a python shell open during the issue, I was able to stat libc before and after:

```python
>>> before
posix.stat_result(st_mode=33261, st_ino=107757212, st_dev=2048L, st_nlink=174, st_uid=0, st_gid=0, st_size=1807032, st_atime=1438654223, st_mtime=1427400617, st_ctime=1439854235)
>>> after
posix.stat_result(st_mode=33261, st_ino=133981597, st_dev=2048L, st_nlink=2, st_uid=0, st_gid=0, st_size=0, st_atime=1439854715, st_mtime=1439854713, st_ctime=1439854713)
```

I notice both that the size is `0` and that the inode number changed (which is consistent with the explanation in the [documentation of overlayfs](https://www.kernel.org/doc/Documentation/filesystems/overlayfs.txt) of what happens if the contents/metadata of a file in the lower layer are modified).

Unfortunately, I don't have a reliable way of monitoring filesystem accesses to these files: [`fanotify` does not appear to work with overlayfs](https://lwn.net/Articles/636943/) and I cannot easily install packages in the host (it is running in a production environment, so tools like sysdig, etc are not feasible). At this point I cannot distinguish between an issue with `perf` or `overlayfs` so I'm filing an issue here in the hope that someone else can reproduce.

### Steps to reproduce

First, my config:

```console
$ docker --version
Docker version 1.5.0, build a8a31ef-dirty
$ uname -a
Linux coreos-10-128-15-206 3.18.6 #2 SMP Sat Feb 28 02:23:04 UTC 2015 x86_64 Intel(R) Xeon(R) CPU E5-2630L v2 @ 2.40GHz GenuineIntel GNU/Linux
```

I then installed a perf binary (I built it with no custom configuration from the Linux source via `cd linux/tools/perf; git checkout v3.18; make`. I'll also attach the binary if I can figure out how) in `/tmp/bin` of the `ubuntu:14.04` base docker image and ran the follow script to reproduce:

```bash
#!/bin/bash

outdir=/var/tmp/perf_data

(while true; do echo "traceme" >/dev/null; done) &
target_pid=$!

function start_perf_process
{
	local outfile=$1
	sudo /tmp/bin/perf record --call-graph=fp --freq 997 \
	    --pid=$target_pid --output=$outfile &
}

mkdir -p $outdir

start_perf_process $outdir/1.data
pid1=$!
start_perf_process $outdir/2.data
pid2=$!
start_perf_process $outdir/3.data
pid3=$!
start_perf_process $outdir/4.data
pid4=$!
start_perf_process $outdir/5.data
pid5=$!
start_perf_process $outdir/6.data
pid6=$!

sleep 3

kill $pid1 $pid2 $pid3 $pid4 $pid5 $pid6
sleep 1
kill $target_pid
wait
```

Example failure:
```console
$ docker run --privileged -v=/tmp/bin:/tmp/bin -it ubuntu:14.04
root@12935adccb1e:/# sudo apt-get install libpython2.7
... <output snipped> ...
root@12935adccb1e:/# PATH=/tmp/bin:$PATH /tmp/repro.sh 
[ perf record: Woken up 1 times to write data ]
[ perf record: Woken up 1 times to write data ]
[ perf record: Captured and wrote 0.238 MB /var/tmp/perf_data/4.data (~10407 samples) ]
[ perf record: Woken up 1 times to write data ]
[ perf record: Woken up 1 times to write data ]
[ perf record: Captured and wrote 0.238 MB /var/tmp/perf_data/3.data (~10386 samples) ]
[ perf record: Woken up 1 times to write data ]
[ perf record: Captured and wrote 0.242 MB /var/tmp/perf_data/6.data (~10588 samples) ]
[ perf record: Woken up 1 times to write data ]
[ perf record: Captured and wrote 0.239 MB /var/tmp/perf_data/1.data (~10458 samples) ]
[ perf record: Captured and wrote 0.238 MB /var/tmp/perf_data/2.data (~10382 samples) ]
[ perf record: Captured and wrote 0.241 MB /var/tmp/perf_data/5.data (~10532 samples) ]
[overlay] with build id e8772280c5c18fdc5a94ef2530ac8d9b556354e6 not found, continuing without symbols
[overlay] with build id e8772280c5c18fdc5a94ef2530ac8d9b556354e6 not found, continuing without symbols
[overlay] with build id e8772280c5c18fdc5a94ef2530ac8d9b556354e6 not found, continuing without symbols
[overlay] with build id e8772280c5c18fdc5a94ef2530ac8d9b556354e6 not found, continuing without symbols
[overlay] with build id e8772280c5c18fdc5a94ef2530ac8d9b556354e6 not found, continuing without symbols
[overlay] with build id e8772280c5c18fdc5a94ef2530ac8d9b556354e6 not found, continuing without symbols
/tmp/repro.sh: line 35:    86 Terminated              ( while true; do
    echo "traceme" > /dev/null;
done )
root@12935adccb1e:/# ls
ls: error while loading shared libraries: /lib/x86_64-linux-gnu/libc.so.6: file too short
```

**Comment by awreece** [comment]
Docker info output:

```
Containers: 4
Images: 779
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 3.18.6
Operating System: CoreOS 607.0.0
CPUs: 12
Total Memory: 62.88 GiB
Name: coreos-10-128-15-206
ID: OEDQ:3BLS:EZ3X:34H3:2OSZ:KAMI:NY7Q:UGKD:ZYON:N3NG:OCKO:PVVN
```

**Comment by awreece** [comment]
I was unable to upload a binary attachment, but I'll make it available to anyone who asks for it.

Other mysteries to me:

 - I don't hit the issue when my script creates only 3 perf process.
 - I don't hit the issue by manually attaching 20 perf processes and manually killing them.
 - I don't deterministically hit the issue and don't hit it when I use only 1 perf process, which leads me to not suspect the perf binary.

**Comment by cpuguy83** [comment]
@awreece have you tried with a different graphdriver than overlay?

**Comment by awreece** [comment]
@cpuguy83 I have not

**Comment by LK4D4** [comment]
@awreece this is probably the overlayfs bug. There were multiple fixes last year. Feel free to open a new issue if the problem persists with latest coreos.
