### ISSUE TITLE
docker-engine : Depends: init-system-helpers (>= 1.13~) but 1.7 is installed.

### ISSUE THREAD

**Issue by franciscovargas** [docker/docker#15692]
When installing docker on linux mint petra I get the following error:

    docker-engine : Depends: init-system-helpers (>= 1.13~) but 1.7 is installed.

I managed to curve around it by replacing my 1.7 with 1.18 (which feels like a downgrade...):

    $ wget https://launchpad.net/ubuntu/utopic/powerpc/init-system-helpers/1.18
    $ sudo dpkg -i init-system-helpers_1.18_all.deb

 nonetheless 1.7 is >1.13 as a version ... thus this is probably a bug worth looking in to ?

**Comment by phemmer** [comment]
> nonetheless 1.7 is >1.13 as a version

7 is less than 13

**Comment by cpuguy83** [comment]
@phemmer is correct, 1.13 means 1-dot-thirteen, vs 1-dot-seven (1.7)
Closing since it seems satisfying the dep fixed the issue.
Ping here if you still have an issue.

Thanks!

**Comment by franciscovargas** [comment]
gotcha thanks ! I was misreading it as 1.70

**Comment by binhht-evolableasia** [comment]
Hi all, 
Im ran `sudo apt-get install docker-engine` and got error:

`docker-engine : Depends: init-system-helpers (>= 1.18~) but it is not installable
                 Depends: lsb-base (>= 4.1+Debian11ubuntu7) but 4.0-0ubuntu20.3 is to be installed
                 Depends: libdevmapper1.02.1 (>= 2:1.02.99) but 2:1.02.48-4ubuntu7.4 is to be installed
                 Recommends: aufs-tools but it is not going to be installed
                 Recommends: cgroupfs-mount but it is not installable or
                             cgroup-lite but it is not going to be installed
E: Unable to correct problems, you have held broken packages.`

What should I do?

**Comment by perfectfoolish** [comment]
Me too.
```
The following packages have unmet dependencies:
 docker-engine : Depends: init-system-helpers (>= 1.18~) but 1.14 is to be installed
                 Depends: lsb-base (>= 4.1+Debian11ubuntu7) but 4.1+Debian11ubuntu6 is to be installed
                 Depends: libdevmapper1.02.1 (>= 2:1.02.99) but 2:1.02.77-6ubuntu2 is to be installed
                 Recommends: aufs-tools but it is not going to be installed
                 Recommends: cgroupfs-mount but it is not installable or
                             cgroup-lite but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by nmarasoiu** [comment]
same here: 
init-system-helpers (>= 1.18~) but 1.14 is to be installed

**Comment by nmarasoiu** [comment]
now it really looks like a downgrade is requested by docker-engine :( is it not

**Comment by phemmer** [comment]
Ubuntu utopic went end-of-life 3 months ago.
Those messages mean docker depends on a newer version of those packages, which you haven't installed.

You can try to see if those packages are available by doing: `apt-get install docker-engine init-system-helpers lsb-base lsb-base`. But since you're using an usupported distro, it may not work.

**Comment by binhht-evolableasia** [comment]
Im upgraded my ubuntu from 12.04 to 14.04 and run again but got error: `Unable to locate package docker-engine`.

**Comment by binhht-evolableasia** [comment]
I found the solution when run:
`sudo wget -qO- https://get.docker.com/ | sh`

It's work for me.

**Comment by shprink** [comment]
@binhht-evolableasia is right, it worked for me too! Thanks

**Comment by nmarasoiu** [comment]
confirm too

În data de vineri, 16 octombrie 2015, Julien Renaux <
notifications@github.com> a scris:

**Comment by thaJeztah** [comment]
@binhht-evolableasia I suspect the `unable to locate package docker-engine` error message was because you were still using the old apt-repository. We switched to a brand new repository a while ago, and have now updated our documentation to explain how to manually add the new repository;
https://docs.docker.com/installation/ubuntulinux/

(we are in the process of phasing out the `curl -sSL https://get.docker.com | sh` installation, because it's not really best practice)

**Comment by dkyktt** [comment]
https://launchpad.net/ubuntu/trusty/+package/init-system-helpers
Trusty (14.04) does not seems to support init-system-helpers v1.8 now.

**Comment by binhht-evolableasia** [comment]
@thaJeztah Thanks a lot

**Comment by sawyerlin** [comment]
hi, 
I propose a solution:
    sudo apt-get install docker-engine-1.8.3-0~trusty

Why:
I think the reason is the candidat
if you use
    sudo apt-cache policy docker-engine
then it shows
    docker-engine:
       Installé : (aucun)
       Candidat : 1.8.3-0~wily
That means 
    sudo apt-get install docker-engine
will always try to install version wily even thought we are using ubuntu 14.04

if you check the url of wily
    https://apt.dockerproject.org/repo/dists/ubuntu-wily/main/binary-amd64/Packages
it shows
    Depends: iptables, init-system-helpers (>= 1.18~), lsb-base (>= 4.1+Debian11ubuntu7), perl, libapparmor1 (>= 2.6~devel), libc6 (>= 2.14), libdevmapper1.02.1 (>= 2:1.02.99), libsqlite3-0 (>= 3.5.9)
wily is for ubuntu 15.04 (i think)

but for ubuntu 14.04 (trusty), if we see the url
    https://apt.dockerproject.org/repo/dists/ubuntu-trusty/main/binary-amd64/Packages
it shows
    Depends: iptables, init-system-helpers (>= 1.13~), sysv-rc (>= 2.88dsf-24) | file-rc (>= 0.8.16), perl, libapparmor1 (>= 2.6~devel), libc6 (>= 2.14), libdevmapper1.02.1 (>= 2:1.02.63), libsqlite3-0 (>= 3.5.9)

if we check the version of init-system-helpers  on ubuntu 14.04 by using 
    sudo apt-cache policy init-system-helpers
we can find that the version does not match the version required by wily
    init-system-helpers:
       Installé : 1.14
       Candidat : 1.14
So i think if we force the installtion of docker-engine 1.8.3-0~trusty then it should work.
I tried and it works. Hope that could help

**Comment by deshka** [comment]
Working on debian wheezy...

I added backports to my apt repo "deb http://ftp.de.debian.org/debian wheezy-backports main" and performed a "apt-get update". Afterwards, the apt-get install docker-engine completed fine. 

Personally, I'm leaving backports commented out for now but in my conf as a reminder...

**Comment by KillingJacky** [comment]
Thanks sawyerlin, your solution works never better!

**Comment by transonly** [comment]
The solution provided by deshka did it for me. Thanks!

**Comment by netmikey** [comment]
The backport repo did the trick. I think docker should fix that dependency though. If they clain wheezy compatibility, it shouldn't actually mean "wheezy with backport repo".

**Comment by johnraz** [comment]
:+1:  for @deshka's solution.

**Comment by appleboy** [comment]
:+1: @deshka Your solution is working for me.

**Comment by kalgar92** [comment]
:+1: @deshka

**Comment by metherton** [comment]
:+1: @deshka

**Comment by marchev** [comment]
Thank you @deshka ! This made it work for me on Debian Wheezy.

**Comment by tianon** [comment]
The main problem with Wheezy compatibility (besides library versions) is the kernel, which does require backports to get a decent version, so perhaps we really should update the documentation to state that we support "Debian Wheezy (with backports enabled)" instead of just Debian Wheezy.

Thoughts, @thaJeztah?

**Comment by thaJeztah** [comment]
@tianon we no longer support wheezy; this is the current docs (Vivid will be removed from there in 1.10)

Docker is supported on these Ubuntu operating systems:

- Ubuntu Wily 15.10
- Ubuntu Vivid 15.04
- Ubuntu Trusty 14.04 (LTS)
- Ubuntu Precise 12.04 (LTS)

**Comment by tianon** [comment]
Ah, fair enough; forgot that Wheezy had been dropped. :innocent:

**Comment by coreypobrien** [comment]
Came across this thread today and I feel compelled to note that Wheezy is definitely still supported in the docs. From https://docs.docker.com/engine/installation/linux/debian/

> Docker is supported on the following versions of Debian:
> 
> Debian testing stretch (64-bit)
> Debian 8.0 Jessie (64-bit)
> Debian 7.7 Wheezy (64-bit)

**Comment by NeilHanlon** [comment]
@coreypobrien https://docs.docker.com/v1.8/installation/debian/#debian-wheezy-stable-7-x-64-bit

Got that to work today.

**Comment by GLianwei** [comment]
Thanks @deshka . Works for me.

**Comment by Krocsky** [comment]
thanks @sawyerlin, give me thought, but i think this is best solution
first check your ubantu version `lsb_release -a`, mine is Ubantu 14.04,
then run `$ apt-cache madison docker-ce`, i choose 17.03.1~ce-0~ubuntu-trusty `$ sudo apt-get install docker-ce=17.03.1~ce-0~ubuntu-trusty`. Works for me:)

**Comment by giri-nitesh** [comment]
@binhht-evolableasia worked for me too :)
Thanks

**Comment by baishuotong** [comment]
Sorry to bother you! @giri-nitesh @Krocsky @binhht-evolableasia @appleboy @tianon @coreypobrien @johnraz @metherton @sawyerlin @shprink @GLianwei @coreypobrien @cpuguy83 @deshka @dkyktt @franciscovargas @GordonTheTurtle @kalgar92 @KillingJacky @marchev @metherton @NeilHanlon @netmikey @nmarasoiu @perfectfoolish @phemmer @qar @qbrossard @qeubar @Qiaohai8866 @qq690388648 @thaJeztah @tianon @transonly @x1022as @x1957 @xamyzhao @xdissent @zachborboa @zain @zaiste @zanedeg 

We are a software engineering team from the Jilin University of China, and we are currently carrying out research oriented to issue discussions in GitHub. In GitHub issue system, GitHub developers can leave comments to others for discussing and solving specific technology problems, which can strengthen the development of projects and cooperation among developers. However, compared with other traditional social platforms, the discussion structure of GitHub Issue is linear, and the comments are sorted in timelines. Besides, many important contents of GitHub issue discussions are flooded by the new and crowding incoming comments, making it difficult for new-comer developers search demanded information. The current discussion status reveals it is difficult for GitHub developers to quickly grasp the main content of the discussion, search for useful information, and locate responders.

Thus, to overcome those challenges, we aim at proposing an automatically approach to re-build the dialogue structure of GitHub discussions and extract the key information under different discussion topics, as shown in the following Figure . The root node represents the developer who proposed the issue, and each node represents the comment with its number and the commenter. Meanwhile, the edge reflects the reply relationship, that is, each children responds to its parent node. The key information of each subtree is displayed in the lower left corner of the Figure.

<img width="1440" alt="截屏2022-06-13 14 57 46" src="https://user-images.githubusercontent.com/38210633/173297996-6aa2fd90-3038-458e-9e81-e528444692e8.png">

 At your convenience, could you please browse Figure 2 and take 5 minutes to answer 3 questions?

1: Do you think this tree-structure dialogue structure can well reflect the reply relationship of GitHub issues, and it will facilitate your understanding of the overall issue content?

2: As for your comments, do you think our approach find the correct user who you want to reply?

3: Can you tell us the key information we extracted from sub-trees can reflect the important topics of each sub-tree or not?

Greatly appreciate any assistance you can provide and we are looking forward to your reply! (We guarantee that your responses will not be changed. The survey data is only utilized for this GitHub recommendation research and not for other purposes. Please feel free to fill it out.)

Have a nice day!

**Comment by baishuotong** [comment]
Sorry to bother you! @giri-nitesh @Krocsky @binhht-evolableasia @appleboy @tianon @coreypobrien @johnraz @metherton @sawyerlin @shprink @GLianwei @coreypobrien @cpuguy83 @deshka @dkyktt @franciscovargas @GordonTheTurtle @kalgar92 @KillingJacky @marchev @metherton @NeilHanlon @netmikey @nmarasoiu @perfectfoolish @phemmer @qar @qbrossard @qeubar @Qiaohai8866 @qq690388648 @thaJeztah @tianon @transonly @x1022as @x1957 @xamyzhao @xdissent @zachborboa @zain @zaiste @zanedeg

We are a software engineering team from the Jilin University of China, and we are currently carrying out research oriented to issue discussions in GitHub. In GitHub issue system, GitHub developers can leave comments to others for discussing and solving specific technology problems, which can strengthen the development of projects and cooperation among developers. However, compared with other traditional social platforms, the discussion structure of GitHub Issue is linear, and the comments are sorted in timelines. Besides, many important contents of GitHub issue discussions are flooded by the new and crowding incoming comments, making it difficult for new-comer developers search demanded information. The current discussion status reveals it is difficult for GitHub developers to quickly grasp the main content of the discussion, search for useful information, and locate responders.

Thus, to overcome those challenges, we aim at proposing an automatically approach to re-build the dialogue structure of GitHub discussions and extract the key information under different discussion topics, as shown in the following Figure . The root node represents the developer who proposed the issue, and each node represents the comment with its number and the commenter. Meanwhile, the edge reflects the reply relationship, that is, each children responds to its parent node. The key information of each subtree is displayed in the lower left corner of the Figure.

<img width="530" alt="截屏2022-06-13 14 58 04" src="https://user-images.githubusercontent.com/38210633/173298214-2b46e1b5-f66d-41a3-90b3-e8749ea68f93.png">

At your convenience, could you please browse the Figure and take 5 minutes to answer 3 questions?

1: Do you think this tree-structure dialogue structure can well reflect the reply relationship of GitHub issues, and it will facilitate your understanding of the overall issue content?

2: As for your comments, do you think our approach find the correct user who you want to reply?

3: Can you tell us the key information we extracted from sub-trees can reflect the important topics of each sub-tree or not?

Greatly appreciate any assistance you can provide and we are looking forward to your reply! (We guarantee that your responses will not be changed. The survey data is only utilized for this GitHub recommendation research and not for other purposes. Please feel free to fill it out.)

Have a nice day!

**Comment by baishuotong** [comment]
Sorry to bother you! @giri-nitesh @Krocsky @binhht-evolableasia @appleboy @tianon @coreypobrien @johnraz @metherton @sawyerlin @shprink @GLianwei @coreypobrien @cpuguy83 @deshka @dkyktt @franciscovargas @GordonTheTurtle @kalgar92 @KillingJacky @marchev @metherton @NeilHanlon @netmikey @nmarasoiu @perfectfoolish @phemmer @qar @qbrossard @qeubar @Qiaohai8866 @qq690388648 @thaJeztah @tianon @transonly @x1022as @x1957 @xamyzhao @xdissent @zachborboa @zain @zaiste @zanedeg

We are a software engineering team from the Jilin University of China, and we are currently carrying out research oriented to issue discussions in GitHub. In GitHub issue system, GitHub developers can leave comments to others for discussing and solving specific technology problems, which can strengthen the development of projects and cooperation among developers. However, compared with other traditional social platforms, the discussion structure of GitHub Issue is linear, and the comments are sorted in timelines. Besides, many important contents of GitHub issue discussions are flooded by the new and crowding incoming comments, making it difficult for new-comer developers search demanded information. The current discussion status reveals it is difficult for GitHub developers to quickly grasp the main content of the discussion, search for useful information, and locate responders.

Thus, to overcome those challenges, we aim at proposing an automatically approach to re-build the dialogue structure of GitHub discussions and extract the key information under different discussion topics, as shown in the following Figure . The root node represents the developer who proposed the issue, and each node represents the comment with its number and the commenter. Meanwhile, the edge reflects the reply relationship, that is, each children responds to its parent node. The key information of each subtree is displayed in the lower left corner of the Figure.

<img width="530" alt="截屏2022-06-13 14 58 04" src="https://user-images.githubusercontent.com/38210633/173298214-2b46e1b5-f66d-41a3-90b3-e8749ea68f93.png">

At your convenience, could you please browse the Figure and take 5 minutes to answer 3 questions?

1: Do you think this tree-structure dialogue structure can well reflect the reply relationship of GitHub issues, and it will facilitate your understanding of the overall issue content?

2: As for your comments, do you think our approach find the correct user who you want to reply?

3: Can you tell us the key information we extracted from sub-trees can reflect the important topics of each sub-tree or not?

Greatly appreciate any assistance you can provide and we are looking forward to your reply! (We guarantee that your responses will not be changed. The survey data is only utilized for this GitHub recommendation research and not for other purposes. Please feel free to fill it out.)

Have a nice day!

**Comment by thaJeztah** [comment]
@baishuotong please don't use the issue tracker for that; it's really not the right channel to ask for that feedback. You're commenting on a 7 Year old ticket and unnecessarily `@`-ing people for something that's not even related to this project. If you're looking for feedback on GitHub features, GitHub' public forums may be a better choice for that; https://github.com/github-community/community/discussions
