### ISSUE TITLE
x509: RSA modulus is not a positive number

### ISSUE THREAD

**Issue by kavehg** [docker/docker#15704]
Any docker command I run behind a corporate SSL interception proxy currently fails with the error shown in the title. I was hoping that I'd be able to run a local registry without having to go out to the external network but no luck:

> $ docker run -d -p 5000:5000 --name registry registry:2
> Unable to find image 'registry:2' locally
> Pulling repository docker.io/library/registry
> Error while pulling image: Get https://index.docker.io/v1/repositories/library/registry/images: tls: failed to > parse certificate from server: x509: RSA modulus is not a positive number

I've tried a few things:
1. Tried experimenting with --tls and --tlsverify
2. Tried to pass corporate root certificate with --tlscacert

I have added the corporate root certificate to Ubuntu (/usr/local/share/ca-certificates) and I am able to get to the various docker hosts (*.docker.io and *.docker.com) using wget, curl, and openssh.

But having no luck with the docker command

Any suggestions?

**Comment by kavehg** [comment]
$ docker version
> Client:
>  Version:      1.8.1
>  API version:  1.20
>  Go version:   go1.4.2
>  Git commit:   d12ea79
>  Built:        Thu Aug 13 02:40:42 UTC 2015
>  OS/Arch:      linux/amd64

> Server:
>  Version:      1.8.1
>  API version:  1.20
>  Go version:   go1.4.2
>  Git commit:   d12ea79
>  Built:        Thu Aug 13 02:40:42 UTC 2015
>  OS/Arch:      linux/amd64

$ uname -a
> Linux ubuntu 3.19.0-26-generic #28-Ubuntu SMP Tue Aug 11 14:16:32 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ docker info
> Containers: 0
> Images: 0
> Storage Driver: aufs
>  Root Dir: /var/lib/docker/aufs
>  Backing Filesystem: extfs
>  Dirs: 0
>  Dirperm1 Supported: true
> Execution Driver: native-0.2
> Logging Driver: json-file
> Kernel Version: 3.19.0-26-generic
> Operating System: Ubuntu 15.04
> CPUs: 4
> Total Memory: 8.358 GiB
> Name: ubuntu
> ID: T62D:BC2L:2OHR:CNOD:OPNF:47J2:RP3U:HT74:WCL4:LX6C:AFNJ:QEMT
> WARNING: No swap limit support

**Comment by jprogn** [comment]
I am also facing same issue. Any luck??

**Comment by abmohan** [comment]
+1

**Comment by joysarkarhub** [comment]
I am getting following error, when I am behind corporate network:
 docker run hello-world
Unable to find image 'hello-world:latest' locally
Pulling repository docker.io/library/hello-world
docker: Get https://registry-1.docker.io/v1/repositories/library/hello-world/tags/latest: tls: failed to parse certificate from server: x509: RSA modulus is not a positive number.

Any help?

**Comment by LK4D4** [comment]
@jprogn @joysarkarhub Is this still issue?
ping @aaronlehmann @stevvooe
@thaJeztah maybe you know some other people to ping

**Comment by thaJeztah** [comment]
I know @dmcgowan helped out in previous cases, based on the description this is a MITM proxy?

**Comment by dmcgowan** [comment]
Looks like this issue has been caused by a buggy version of gnutls generating invalid certificates. The error is indicative of an invalid certificate being presented to Docker.

If you encounter this issue you can see this references:
https://rhn.redhat.com/errata/RHSA-2015-1457.html
https://github.com/golang/go/issues/6837#issuecomment-122343528
http://blog.alex.org.uk/2015/10/13/rsa-modulus-is-not-a-positive-number-say-what/
