### ISSUE TITLE
Proposal: Add support for Dockerfile dependency

### ISSUE THREAD

**Issue by FrenchBen** [docker/docker#15700]
Too often Dockerfile documentations explain the need for a `--link` to a supporting/additional container. 
I propose to allow the Dockerfile to support a dependency tag (similar to FROM) which will allow a user to build a Dockerfile dependency for other/external container.

Prime example: Wordpress:
https://github.com/docker-library/docs/tree/master/wordpress

**Comment by thaJeztah** [comment]
If I understand correctly, you want to define which other containers should be started (and linked) for the application to run.

Doing this is called "orchestration"; I think you should have a look at docker compose, which is meant for orchestration, and allows you to describe these relations in a single `docker-compose.yml` file;

https://docs.docker.com/compose/

**Comment by FrenchBen** [comment]
@thaJeztah I agree that compose is the right tool for linking and making sure that a db is in place (or whatever).

What I'm looking for is a requirement for say the 'mysql' image is a dependency for this image to work properly. 
Think of RPM dependencies, where a package will tell you that it depends on another package and unless that package exists you can't install/run it.

**Comment by thaJeztah** [comment]
Sounds a bit like https://github.com/docker/docker/issues/7247

**Comment by FrenchBen** [comment]
it's exactly it - my search terms weren't on point :[ 
Closing - Thanks @thaJeztah
