### ISSUE TITLE
Docker engine RPM has no files marked as config

### ISSUE THREAD

**Issue by jimmidyson** [docker/docker#15714]
This means that any post-install customisations made to `/usr/lib/systemd/system/docker.service` are overwritten when upgrading. Please can this file be marked as config & hence use the normal RPM config behaviour?

**Comment by phemmer** [comment]
Files are marked as "config" in RPMs when the file is expected to be modified, and thus shouldn't be replaced on upgrades. The file `/usr/lib/systemd/system/docker.service` should not be modified. Generally only files in `/etc` should be modified, and almost never any files in `/usr/lib`.

I'm assuming you are modifying this file to override the defaults for the docker service. The documentation contains instructions on the proper way to do this: https://docs.docker.com/articles/systemd/#custom-docker-daemon-options

See also: #15670 & #15339

**Comment by thaJeztah** [comment]
Yup, you should *not* make modifications to that file, but use drop-ins as described in the docs that @phemmer linked. I'm going to close this issue, because this is a deliberate choice, but feel free to comment here after I've closed this. Thanks!

**Comment by jimmidyson** [comment]
Thanks! That works great & I learned a thing about systemd too - win!
