### ISSUE TITLE
Fail install docker on Mac 10.9

### ISSUE THREAD

**Issue by yuan78** [docker/docker#15712]
Hi, 
It fail when install docker on Mac 10.9, and  error info as below:

I try to remove virtual box and installed 4.3 version, but no use and it still fail.

How I can do to solve this issue. THX!

__________________________________________________________________________________________
Last login: Wed Aug 19 22:23:30 on ttys000
bash
. '/Applications/Docker/Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh'
garydeMac:~ gary$ bash
bash-3.2$ . '/Applications/Docker/Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh'

Machine default already exists in VirtualBox.
Starting machine default...
exit status 1
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
Setting environment variables for machine default...

                    ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/


host is not running
docker is configured to use the default machine with IP 
For help getting started, check out the docs at https://docs.docker.com

default is not running. Please start this with docker-machine start default
bash-3.2$

**Comment by dustins** [comment]
I'm seeing the same thing. I installed the newest docker toolbox 1.8.1b for Mac. I've tried deleting and letting the default machine get recreated, but it still behaves the same.

OS X 10.11 Beta (15A262e)
Virtual Box 5.0.2 (as installed by the toolbox)

	bash-3.2$ docker version
	Client:
	 Version:      1.8.1
	 API version:  1.20
	 Go version:   go1.4.2
	 Git commit:   d12ea79
	 Built:        Thu Aug 13 02:49:29 UTC 2015
	 OS/Arch:      darwin/amd64
	Get http:///var/run/docker.sock/v1.20/version: dial unix /var/run/docker.sock: no such file or directory.
	* Are you trying to connect to a TLS-enabled daemon without TLS?
	* Is your docker daemon up and running?

	bash-3.2$ docker info
	Get http:///var/run/docker.sock/v1.20/info: dial unix /var/run/docker.sock: no such file or directory.
	* Are you trying to connect to a TLS-enabled daemon without TLS?
	* Is your docker daemon up and running?

	bash-3.2$ uname -a
	Darwin silverbook.local 15.0.0 Darwin Kernel Version 15.0.0: Mon Aug 10 17:09:09 PDT 2015; root:xnu-3247.1.99~3/RELEASE_X86_64 x86_64

**Comment by nitrobass24** [comment]
Same problem here. Installed Docker Toolbox, immediately came to the error below. 
MBP 2015 running 10.10.4

                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/


host is not running
docker is configured to use the default machine with IP 
For help getting started, check out the docs at https://docs.docker.com

default is not running. Please start this with docker-machine start default
bash-3.2$ docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      darwin/amd64
Get http:///var/run/docker.sock/v1.20/version: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
bash-3.2$ docker info
Get http:///var/run/docker.sock/v1.20/info: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
bash-3.2$ uname -a
Darwin stephens-mbp.davis.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
bash-3.2$

**Comment by chrisburnett** [comment]
I had this same problem yesterday. I fixed it by removing VirtualBox 5.0.2 completely, and manually installing VirtualBox 4.3.3. It seems as though the current version of the Docker Toolbox isn't compatible with VirtualBox 5 on Mac yet.

Hope this helps you out.

**Comment by gion** [comment]
@chrisburnett , thanks! I had a similar problem and your solution did the trick!

**Comment by chwade** [comment]
I had the same issue. Reinstalling Virtual Box 4.3 worked to some extent but I am now receiving the following error:

docker is configured to use the default machine with IP 192.168.99.100
For help getting started, check out the docs at https://docs.docker.com

open /Users/charliewade/.docker/machine/machines/default/server.pem: no such file or directory

**Comment by yuan78** [comment]
I solved this issue as following steps:

1. Virtualbox : enable VTX option for CPU
2. Virtualbox: OS must select 64bit OS for Linux.

Then it's OK now! This is not Virtualbox version issue but the configuration issue.

**Comment by yuan78** [comment]
Another point you must pay attention is you need to shutdown the virtualbox correctly, quit Mac without  correctly shutting down virtualbox will cause bad start issue for it and even will loss data of your docker.

**Comment by tonypujals** [comment]
Confirming that I'm only able to run the latest docker tools with VirtualBox 4.3.30, not the 5.x version installed by Docker Toolbox.

**Comment by fastrde** [comment]
VBox issue at: https://www.virtualbox.org/ticket/14412
Test-Build 5.0.x with fix for that issue at: https://www.virtualbox.org/wiki/Testbuilds

fixed it for me.

**Comment by tonypujals** [comment]
Thanks @fastrde - that worked for me.

**Comment by troyfontaine** [comment]
Confirmed using a test build of 5.0.3 resolved the issues for me.

**Comment by webtoed** [comment]
same with 5.0.3

**Comment by yunti** [comment]
hmm 5.0.3 (r102467) didn't solve the issues for me . 
Error is:

VT-x is disabled in the BIOS for both all CPU modes (VERR_VMX_MSR_ALL_VMX_DISABLED).


Result Code: 
NS_ERROR_FAILURE (0x80004005)
Component: 
ConsoleWrap
Interface: 
IConsole {872da645-4a9b-1727-bee2-5585105b9eed}

**Comment by thaJeztah** [comment]
> `VT-x is disabled in the BIOS for both all CPU modes (VERR_VMX_MSR_ALL_VMX_DISABLED).`

Looks like `VT-x` is disabled (or not available) on your computer; these articles describe how to check if this is supported and/or enabled on your computer: http://kb.parallels.com/en/5653 https://support.apple.com/en-us/HT203296

**Comment by imod** [comment]
I had the exact same problem and figured it was a permission problem on my /Application directory (visible when I tried to start the "default" directly in VirtualBox).
Running "Repair Disk Permission" from the "Disk utility" as described in this post solved my issues: https://forums.virtualbox.org/viewtopic.php?f=8&t=47705

**Comment by lixgbg** [comment]
I had the same problem as well. Ran Repair Disk Permission but didn't help. I had to change permissions on my /Users/henrik/.docker directory, adding Group Writable:
$sudo chmod -R g+w /Users/henrik/.docker

After this I can start the Docker QuickStart Terminal as I'm supposed to. The Kinematic GUI works as well.

**Comment by xacaxulu** [comment]
+1

**Comment by mgooty** [comment]
@lixgbg - Thank you . That worked for me :)

**Comment by cpuguy83** [comment]
ping @mchiang

**Comment by cpuguy83** [comment]
ping @mchiang0610

**Comment by jersur** [comment]
@lixgbg - Thank you. That worked

**Comment by Puneeth-n** [comment]
@fastrde Thanks :) Worked like a charm

**Comment by calavera** [comment]
thanks for the working reports. Closing as fixed.
