### ISSUE TITLE
/etc/default/docker ignored when using systemd (Ubuntu 15.04)

### ISSUE THREAD

**Issue by zapp42** [docker/docker#15719]
The systemd startup file does not use the settings from /etc/default/docker.

Instead it has a hardcoded default config:
[...]
[Service]
ExecStart=/usr/bin/docker -d -H fd://
[...]

**Comment by zapp42** [comment]
uname -a: Linux xxx 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

docker version: 
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64

docker -D info:
Containers: 1
Images: 18
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-15-generic
Operating System: Ubuntu 15.04
CPUs: 4
Total Memory: 7.5 GiB
Name: battlecat
ID: RJWL:XYGA:7JIR:LDXC:OQFC:USFP:RSYA:74QW:YHJD:4AWG:572R:JD33
WARNING: No swap limit support

List the steps to reproduce the issue:
1. Fresh install of Ubuntu 15.04 (server)
2. Install docker: curl -sSL https://get.docker.com/ubuntu/ | sudo sh
3. Modify /etc/docker/default, add options to DOCKER_OPTS

Expected result: After daemon restart, see the options in the docker -d commandline in ps output

Actual result: No change in docker command line.

**Comment by mavenugo** [comment]
Thanks for filing the issue. But, this is a duplicate for #12926, #13384 and many more Issues opened on systemd specific configuration. Please refer to these Issues for the recommended solutions. Closing this issue.

**Comment by arthurlogilab** [comment]
The documentation does not reflect this http://docs.docker.com/engine/installation/ubuntulinux/#configure-a-dns-server-for-use-by-docker
