### ISSUE TITLE
Active NFS by default on Docker (boot2docker/kitematic)

### ISSUE THREAD

**Issue by CodzDev** [docker/docker#15729]
Hello,

**Virtualbox** don't mount correctly volumes on Mac OS X, there're a lot of permissions problems with vboxsf if you active NFS by default on Docker the permissions errors on Mac OS X will be resolved and mount a folder will be faster for users..

**Comment by phemmer** [comment]
I think you mean for this to be on [the boot2docker issue tracker](https://github.com/boot2docker/boot2docker/issues).

This is the issue tracker for the docker project, which is a separate organization than boot2docker. Docker itself does not manage the host on which it runs (such as the nfs service).

**Comment by CodzDev** [comment]
Sorry for the mistake..
