### ISSUE TITLE
Feature request: option to restart container with updated image

### ISSUE THREAD

**Issue by jbemmel** [docker/docker#15725]
Currently, 'docker restart' uses the same image that is running. In an application upgrade scenario, it would be convenient if a running container's image could be upgraded by simply pulling a new version of the image, and then doing:
docker restart --latest-image {container name}

This command should preserve any command line parameters that were used to start the container ( including volumes, env variables, etc. ).

Right now, one has to stop and remove the old container, then issue a new run command with all the same parameters. One could write an introspect script to figure out what the settings were, but it would be much easier if docker supported this natively

**Comment by phemmer** [comment]
`docker restart` doesn't just use the same image that is running, it uses the same filesystem. Meaning files that were created/modified/deleted are preserved.
This would not be possible to accomplish if you changed the underlying image. What if your container created a file in an already-existing directory, but in the new image, that directory doesn't even exist? There are many other such scenarios that would cause difficulty.

I think this also goes against the docker design. Once a container is created, you can't change its settings. Changing settings means you create a new container.

Granted I'm not associated with the docker project, but I'm not in favor of this.

**Comment by thaJeztah** [comment]
Hi @jbemmel, I don't think this is something we will implement, but here are some related discussions and ideas that might help you;

> This command should preserve any command line parameters that were used to start the container ( including volumes, env variables, etc. ).

We actually have this, but it's a separate project; *Docker Compose* allows you to do *exactly* that; define how your container(s) should be run, specify env-vars, etc. Have a look at the Docker Compose documentation; https://docs.docker.com/compose/

However, even with docker compose, replacing a container with a "fresh one" will make you loose any file system changes inside the container. When working with Docker, ideally, containers should not contain "state", in other words, you should be able to stop and delete a container and replace it with a new one, without loosing anything. Statefull data (anything that should be preserved after the container is destroyed) should be stored "outside" of the containers file system, for example, by using (bind-mounted) volumes.

Having said that, there is a proposal that would allow replacing a containers base-image, and preserving the writable layer; https://github.com/docker/docker/issues/9382. However, doing that would fail in most situations, some explanation can be found here; https://github.com/docker/docker/issues/7606#issuecomment-52467135

I'm going to close this issue, but hopefully the above helps you find a solution for your case. Feel free to comment here after I've closed the issue :+1:

**Comment by happymaster23** [comment]
Hello,

in my eyes (and maybe I have not catched something, so I am totally wrong), this will be great feature. I totally understand, that top container read/write layer will be lost. This proposal is not about preserving everything and just change image with updated one, but only preserve all command line parameters and links to other containers (preserve identity of container). 

Consider this scenario: One nginx container as reverse proxy linked to five application containers. Nginx container have five links to app containers and if I update image of one of them, I have to stop it and remove it. Then I can run it as a new container with same name, but nginx container is using old IP address to this container, so I have to stop it, remove it and then run it again with same command line parameters. With this proposed feature, I will just rerun container with new image (with lost rw layer of course) using just one command and everything will be done.

If I am missing anything, thank you in advance for explanation. 

Martin

**Comment by cpuguy83** [comment]
@happymaster23 This is out of scope of Docker and really in the land of higher-level orchestration, config management, and service discovery.

Note that with the new networking features, you can dynamically add/remove containers to a network and have IP resolution to the container names.
Also in 1.10 you'll be able to have both locally scoped aliases (ala --link) and network-scoped aliases.

**Comment by happymaster23** [comment]
@cpuguy83 Thank you for you reply. OK, I understand, you want to keep docker architecture clear. 

Could you please point me to some documentation of features you are talking about (in second sentence)?

Thank you in advance

**Comment by thaJeztah** [comment]
@happymaster23 see the docs here; https://docs.docker.com/engine/userguide/networking/dockernetworks/

**Comment by rjsteinert** [comment]
Instead of `docker restart` covering this functionality, `docker rerun` sub-command might be a more appropriate name. I'd like to remind anyone reading this of the moment when they needed to rerun a container with an updated image and had to fumble around to remember all options they used on the original run of that container.

**Comment by KangoV** [comment]
This would be a great feature to have. Do you think this might just get done?

**Comment by cpuguy83** [comment]
@KangoV On a container? Not likely.
Services (in 1.12 swarm mode) allow this.

**Comment by jbemmel** [comment]
It's been a while, and I still believe this would be a useful feature. It doesn't have to be tied to 'restart' if the semantics are different, but just like 'docker run' is create followed by start a "docker update" (or whatever name the team thinks is appropriate) would do a docker pull, docker stop and docker start with the same parameters and environment.

I found https://github.com/v2tec/watchtower which approximates the desired functionality, however instead of polling Docker hub every few minutes I would prefer a user trigger to perform the upgrade at a time convenient for them ( not whenever something new is pushed to Docker hub, but during a scheduled maintenance window )

**Comment by mitar** [comment]
watchtower is great! I am using it in one-time fashion to approximate behavior wanted here. But it would really be great if there would be just a command to do this in Docker core.

**Comment by raphaklaus** [comment]
Well, with docker-compose you have two ways:

`docker-compose up -d {service_name}`
or
`docker-compose create {service_name} && docker-compose restart {service_name]`

**Comment by thaJeztah** [comment]
Also `docker service update --image <new image> <some service>` allows you to update a service's image.

**Comment by willseward** [comment]
FWIW: https://github.com/assaflavie/runlike

**Comment by KuruvaSomaSekhar** [comment]
First we need to commit existing container with all updated data using **docker commit -p  containerName newImageName** . Then **docker service update --image <new image> <some service>**

**Comment by srittau** [comment]
As a newcomer to Docker, this seems to be such a basic, often-used command that I am mystified it does not exist. For a simple, single container app (outside the realm of docker compose or swarm), deploying consists of those steps:

* docker pull _image_
* docker stop _container_
* docker rm _container_
* docker run _container + try to remember the 20 options the container was originally started with_

While this is of course easily scriptable that does seem kind of redundant. Or maybe I am misunderstanding docker deployment.

**Comment by thaJeztah** [comment]
> For a simple, single container app (outside the realm of docker compose or swarm)

Docker compose can be used just fine to start a single container. Having a docker-compose file in your repository not only helps remembering those 20 options, it also allows you to easily share those options with colleagues (just clone the repository, and run `docker compose up`)

**Comment by Hubbitus** [comment]
Why you suggest for that docker-compose instead of docker-stack yaml files?

**Comment by zzzeek** [comment]
the runlike link mentioned above ( https://github.com/assaflavie/runlike ) is *exactly* what is needed here.   I'm just running a handful of containers so I'll probably use that.    my containers are absolutely stateless so I'd like to be able to blow them away and bring them right back from an updated image.    all that's needed to automate this is to rewrite the original commandline options (which in my case came in the first place from ansible playbooks).  it's such a simple thing and need not interfere with the spirit of docker; it is in fact entirely based on the spirit of docker in that you should design your containers to be totally stateless!

**Comment by Glideh** [comment]
[`docker-compose`](https://docs.docker.com/compose/) is a must have.
This is the way to go for configuring applications.
There is some magic behavior behind `docker-compose up`

**Comment by nyetwurk** [comment]
> As a newcomer to Docker, this seems to be such a basic, often-used command that I am mystified it does not exist. For a simple, single container app (outside the realm of docker compose or swarm), deploying consists of those steps:
> 
>     * docker pull _image_
> 
>     * docker stop _container_
> 
>     * docker rm _container_
> 
>     * docker run _container + try to remember the 20 options the container was originally started with_
> 
> 
> While this is of course easily scriptable that does seem kind of redundant. Or maybe I am misunderstanding docker deployment.

I couldn't agree more. It is inexcusable that something like runlike (mentioned above) doesn't already exist in docker.

I'm always frustrated when common sense feature requests like this are unceremoniously closed.

**Comment by cpuguy83** [comment]
What you are looking for is the "service" object, and it is part of swarm.

"docker service create --name fooService ... foo:v1"
"docker service update --image=foo:v2 fooService"

**Comment by jbemmel** [comment]
I use docker on a daily basis, but these are the sorts of things that create negative associations in my mind. I do not understand the logic or the thought process that decided this outcome, but I think it’s odd, and ultimately bad for docker. You could be encouraging users to contribute a patch instead, and have the feature - plus a positive feeling of inclusiveness and support, at little cost to you. “No” only has a negative value

**Comment by cpuguy83** [comment]
Again, the feature already exists.

"No" does not only have a negative value.
"No" is much simpler than "yes" because "yes" often leads to mistakes that we have to support long term.
"No" also doesn't mean always no, it can mean "not right now". Yes, however, is forever.

**Comment by jbemmel** [comment]
It does not exist in my world. I get the support considerations, and there may be technical reasons - but for me as a user, the way this was handled tells me that Docker isn’t the right tool for me

**Comment by jbemmel** [comment]
And there are many more responses possible besides “no” and “yes”. Like “would you be willing to submit a pull request?”
“No” closes the door. I am not upset about any of this, just sharing some thoughts

**Comment by tonymet** [comment]
https://github.com/jdevelop/repull is a docker utility that automates these steps:  stop container, pull new image, re-run with original containers ARGs . I think the folks here will find it useful
