### ISSUE TITLE
starting container when volume plugin is offline causes daemon exception on any subsequent operation

### ISSUE THREAD

**Issue by srust** [docker/docker#15720]
Description of problem:

A container was started that uses a volume from an external volume plugin. The volume plugin was initially online, and started successfully. Then, the plugin was stopped, and docker daemon restarted.

On startup, the container using the volume plugin was unable to initialize its volume (since plugin was offline). And so failed to register the container on boot:

````
DEBU[0015] Failed to register container 731b87fb85d32a60ace3346d4d77a66260cd9c17da132d39ff2a04a956abb401: Error looking up volume plugin
````

 However, it did actually start:

````
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
731b87fb85d3        busybox             "sh"                18 hours ago        Up 18 hours                             focused_hypatia
````

However, it is now referencing a volume that is not mounted and does not exist on the host, and is not bind mounted correctly into the container.

Any subsequent operation on that container, to `stop`, `rm`, etc. causes a daemon exception. That container is now stranded. The only recovery operation I have found is to remove it from the filesystem, ie: rm /var/lib/docker/containers/731b87fb*

`stop`:

*client*

$ ./docker-1.9.0-dev stop focused_hypatia
An error occurred trying to connect: Post http:///var/run/docker.sock/v1.21/containers/focused_hypatia/stop?t=10: EOF
Error: failed to stop containers: [focused_hypatia]

*server*

````
DEBU[65195] Calling POST /containers/{name:.*}/stop      
INFO[65195] POST /v1.21/containers/focused_hypatia/stop?t=10 
DEBU[65195] Sending 15 to 731b87fb85d32a60ace3346d4d77a66260cd9c17da132d39ff2a04a956abb401 
2015/08/20 09:32:36 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
goroutine 80 [running]:
net/http.func·011()
	/usr/local/go/src/net/http/server.go:1130 +0xbb
github.com/docker/docker/daemon.(*containerMonitor).ExitOnNext(0x0)
	/go/src/github.com/docker/docker/daemon/monitor.go:73 +0x78
github.com/docker/docker/daemon.(*Container).KillSig(0xc2080f54a0, 0xf, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container.go:384 +0x3b5
github.com/docker/docker/daemon.(*Container).killPossiblyDeadProcess(0xc2080f54a0, 0xf, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container.go:402 +0x58
github.com/docker/docker/daemon.(*Container).Stop(0xc2080f54a0, 0xa, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container.go:495 +0x93
github.com/docker/docker/daemon.(*Daemon).ContainerStop(0xc2080a4620, 0xc2080ee357, 0xf, 0xa, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/stop.go:13 +0x12b
github.com/docker/docker/api/server.(*Server).postContainersStop(0xc2080a0f40, 0xc2080ee347, 0x4, 0x7f8aaff1c110, 0xc2081cc3c0, 0xc2084e6000, 0xc208423590, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/container.go:210 +0x1e1
github.com/docker/docker/api/server.*Server.(github.com/docker/docker/api/server.postContainersStop)·fm(0xc2080ee347, 0x4, 0x7f8aaff1c110, 0xc2081cc3c0, 0xc2084e6000, 0xc208423590, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/server/server.go:346 +0x7b
github.com/docker/docker/api/server.func·008(0x7f8aaff1c110, 0xc2081cc3c0, 0xc2084e6000)
	/go/src/github.com/docker/docker/api/server/server.go:292 +0xc8f
net/http.HandlerFunc.ServeHTTP(0xc2080ee8c0, 0x7f8aaff1c110, 0xc2081cc3c0, 0xc2084e6000)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc2081389b0, 0x7f8aaff1c110, 0xc2081cc3c0, 0xc2084e6000)
	/go/src/github.com/docker/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x297
net/http.serverHandler.ServeHTTP(0xc20814a6c0, 0x7f8aaff1c110, 0xc2081cc3c0, 0xc2084e6000)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2081cc140)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e
````

Same with `rm`:

*client*:

$ ./docker-1.9.0-dev rm -fv focused_hypatia
An error occurred trying to connect: EOF
Error: failed to remove containers: [focused_hypatia]

*server*:

````
DEBU[65267] Calling DELETE /containers/{name:.*}         
INFO[65267] DELETE /v1.21/containers/focused_hypatia?force=1&v=1 
DEBU[65267] Sending 9 to 731b87fb85d32a60ace3346d4d77a66260cd9c17da132d39ff2a04a956abb401 
2015/08/20 09:33:48 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
goroutine 81 [running]:
net/http.func·011()
	/usr/local/go/src/net/http/server.go:1130 +0xbb
github.com/docker/docker/daemon.(*containerMonitor).ExitOnNext(0x0)
	/go/src/github.com/docker/docker/daemon/monitor.go:73 +0x78
github.com/docker/docker/daemon.(*Container).KillSig(0xc2080f54a0, 0x9, 0x0, 0x0)
	/go/src/github.com/docker/docker/daemon/container.go:384 +0x3b5
````

`docker version`:

$ ./docker-1.9.0-dev version
Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   f848f34-dirty
 Built:        Wed Aug 19 17:57:45 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   f848f34-dirty
 Built:        Wed Aug 19 17:57:45 UTC 2015
 OS/Arch:      linux/amd64

`docker info`:

$ ./docker-1.9.0-dev info
Containers: 5
Images: 81
Storage Driver: devicemapper
 Pool Name: docker-253:1-8771438-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.925 GB
 Data Space Total: 107.4 GB
 Data Space Available: 34.15 GB
 Metadata Space Used: 6.148 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.141 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.11.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 4
Total Memory: 15.48 GiB

`uname -a`:

Linux host 3.10.0-229.11.1.el7.x86_64 #1 SMP Thu Aug 6 01:06:18 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by coolljt0725** [comment]
I have meet the same problem when I use volume plugin `blockbridge`, I'm investigating on it.

**Comment by srust** [comment]
Hi @coolljt0725. We're working on a new version of the `blockbridge` plugin to better handle docker restarts, reboots, etc. By chance, are you seeing this issue when you restart docker?

However, the issue described here is a general problem, not plugin specific. If the plugin is not running, for any reason, then the daemon will exhibit this behavior and have the exception on the stranded containers.

Interestingly, the stranded container in my tests shows an uptime of before the daemon was started. Whereas, the successful started containers show an uptime equal to the daemon runtime. Perhaps some accounting is amiss here, too.

**Comment by coolljt0725** [comment]
@srust  I can see this issue when I restart docker. I'm also think this is not a plugin specific issue(but I haven't try other plugin driver), I'm investigating on the docker side.
