### ISSUE TITLE
Specifying json-file log driver to the daemon does not work

### ISSUE THREAD

**Issue by wlan0** [docker/docker#15726]
On Docker version 1.8.1, build d12ea7

While starting the docker daemon, If I specify the log-driver=json-file and --log-opts max-file=50 --log-opt max-size=50k, It did not rollover the log files. 

While starting the docker daemon, If I specified the log-driver=syslog, then it works fine.

**Comment by pbitty** [comment]
I have also had the same issue.  It seems that the `log-opt` parameters are not properly parsed in `daemon` mode.

When I provide a wrong `log-opt` value when running a container, it validates the value and returns an error:

    $ docker run --log-driver=json-file --log-opt foo ubuntu:trusty bash
    Error response from daemon: Cannot start container cae5e14df7580d9a83431d9ef49a0aec71f669109b7dc52a188a3ccca6e635d0: Failed to initialize logging driver: unknown log opt 'foo' for json-file log driver

When I do the same thing when starting the docker daemon, it silently continues:

    $ sudo docker daemon --log-driver=json-file --log-opt foo
    INFO[0000] [graphdriver] using prior storage driver "aufs"
    INFO[0000] Option DefaultDriver: bridge
    INFO[0000] Option DefaultNetwork: bridge
    INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
    WARN[0000] Running modprobe bridge nf_nat br_netfilter failed with message: modprobe: WARNING: Module br_netfilter not found., error: exit status 1
    INFO[0000] Firewalld running: false
    WARN[0000] Your kernel does not support swap memory limit.
    INFO[0000] Loading containers: start.......
    INFO[0000] Loading containers: done.
    INFO[0000] Daemon has completed initialization
    INFO[0000] Docker daemon                                 commit=d12ea79 execdriver=native-0.2 graphdriver=aufs version=1.8.1

**Comment by yang1992** [comment]
docker version:
 Client:
 Version:      1.8.0
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0d03096
 Built:        Tue Aug 11 17:17:40 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.0
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0d03096
 Built:        Tue Aug 11 17:17:40 UTC 2015

docker info:
Images: 4
Storage Driver: devicemapper
 Pool Name: docker-8:3-71722731-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.991 GB
 Data Space Total: 107.4 GB
 Data Space Available: 11.5 GB
 Metadata Space Used: 1.72 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: false
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.11.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 4
Total Memory: 979.7 MiB
Name: vm-yangheng
ID: B3AI:6V65:ZSIQ:AWX2:BLCI:ZLUE:UJIO:STUO:ZBSO:L3SO:ZNJF:MR5B
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

uname -a:
Linux vm-yangheng 3.10.0-229.11.1.el7.x86_64 #1 SMP Thu Aug 6 01:06:18 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:
1、docker daemon --log-driver=json-file --log-opt max-size=10k
2、docker run -i -t xxx:xxx (Container_id)
3、make log(exp. echo xxxxxxxxxxxxxxxxx in Container )

Actual Results:
Container_id-json.log can exceed 10k,It did not rollover the log files.

1、docker run -i -t --log-driver=json-file --log-opt max-size=10k
2、It works in container run opts

Expected Results:
It can rollover the  log(Container_id-json.log) files.

Additional info:

**Comment by coolljt0725** [comment]
This should have been fixed in #15611, you can try the master branch.

**Comment by cpuguy83** [comment]
Closing b/c I'm fairly certain this is resolved by the mentioned PR.
Ping here if you find otherwise! Thanks!
