### ISSUE TITLE
ENV PATH not working

### ISSUE THREAD

**Issue by DarioSwain** [docker/docker#15723]
Issue from [this comment](https://github.com/docker/docker/issues/15497#issuecomment-131891563).

@thaJeztah @phemmer Hi guys, If i correct understand this [topic](https://docs.docker.com/reference/builder/#env), next command don't work:
```bash
ENV PATH /my/bin/:$PATH
```
How i can override $PATH env?

I execute:
```bash
docker build -t php_tools .
...
Step 11 : ENV PATH /root/.composer/vendor/bin:$PATH
 ---> Using cache
 ---> d9306ed93877
...
docker run --rm -i -v $HOME/.ssh:/root/.ssh php_tools bash -c "echo $PATH"
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
```
It's not working for me...

My docker version:
```bash
/var/www/php_tools# docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by duglin** [comment]
It seems to work for me but perhaps I'm not doing the same thing as you. My Dockerfile is:
```
FROM ubuntu
ENV PATH /foo:$PATH
RUN env
```
and I see `/foo` in the PATH from the above RUN as well as when I run a container using this image.

**Comment by duglin** [comment]
Can you provide more info on your exact scenario?

**Comment by phemmer** [comment]
Use single quotes, not double.

    docker run --rm -i -v $HOME/.ssh:/root/.ssh php_tools bash -c 'echo $PATH'

not

    docker run --rm -i -v $HOME/.ssh:/root/.ssh php_tools bash -c "echo $PATH"

&nbsp;

I'd also recommend using the mailing list or forums for support using docker. The issue tracker is generally for bugs & feature requests.

**Comment by duglin** [comment]
@phemmer nice catch - closing issue assuming its the quote issue. If, @DarioSwain,  not go ahead and reopen.
