### ISSUE TITLE
Proposal: Group volumes by container by default

### ISSUE THREAD

**Issue by MrSchism** [docker/docker#15737]
When using `docker run` on a repository, by default, it creates a volume in the volumes/ folder.  This is convenient, but becomes complicated when you run multiple instances.

An improvement to the default behavior would be to put all of the volumes into `volumes/<container_name>` utilizing the ID if a name wasn't defined.

An example of how this can be illustrated is if you `docker pull ahumaro/grav-php-nginx` then using `docker run -d -i -p 8080:80 ahumaro/grav-php-nginx` (and repeating it a couple times).  It shows three volumes per instance.

Note: I'm still relatively new to using Docker.  If my terminology is off, I apologize.  If there' a better way to do this, I apologize for that, too.

**Comment by cpuguy83** [comment]
Maybe I'm not understanding your issue, but the behavior you describe is exactly what is done.
A volume doesn't really have an ID, it has a name only. The name is either specified by the user, or docker generates a unique name (which currently happens to looks like an ID).

**Comment by MrSchism** [comment]
My apologies; I forgot some code fencing and it wiped part of what I included.  I've fixed that.

The issue arises when you have to inspect each container for the specific volume it is using.  When you have multiple instances of a specific repository/image it can become a bit of a hassle.

**Comment by cpuguy83** [comment]
This doesn't really work because the volume is supposed to live beyond the life of a container, and can be used by multiple containers.

**Comment by MrSchism** [comment]
Alright.  Is there a feature where you can define a one-time volume creation location (besides going into all of the files and changing them manually)?

**Comment by cpuguy83** [comment]
You can specify the volume path explicitly `-v /host/path:/container/path`, or you can use a named volume `-v <name>:/foo`.
The assumption should be specifying the same name would give you the same volume.

**Comment by MrSchism** [comment]
I'll have to experiment with that.

Thank you.
