### ISSUE TITLE
Fedora 20 RPMs and SystemD

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#15734]
While discussing https://github.com/docker/docker/issues/14149#issuecomment-133167663, I noticed the RPMs disable systemd for Fedora 20 (at least, that's what I make of this line; https://github.com/docker/docker/blob/master/hack/make/.build-rpm/docker-engine.spec#L20)

As far as I could find, Fedora 20 uses SystemD, but I asked on IRC just to be sure; https://botbot.me/freenode/docker-dev/2015-08-20/?msg=47727480&page=3

I'm wondering if there's a specific reason to do this?

Also, the IRC discussion brought to light that Fedora 20 is EOL'd; https://lists.fedoraproject.org/pipermail/announce/2015-June/003279.html

So, perhaps we should exclude it from the builds altogether, but we don't have a clear policy on that yet (e.g., we *did* remove Ubuntu 14.10 because it's EOL'd)

**Comment by thaJeztah** [comment]
ping @jfrazelle @tianon because your probably know :smile:

**Comment by jfrazelle** [comment]
If it is EOL I will remove it, less to build then ;) PR coming
