### ISSUE TITLE
nano: no proper screen output (windows 7 with docker 1.8.1)

### ISSUE THREAD

**Issue by altsheets** [docker/docker#15738]
# nano issue on Windows

problems on Windows (7) with docker (Docker version 1.8.1, build d12ea79)

    docker run -it debian bash
    apt-get update && apt-get -y install nano git

so far all fine. But when nano is started:

    ls -R / > test.txt
    nano test.txt
	
then it does not show the contents of the file.
And it sometimes crashes the whole image, when opened with certain files:

    git clone https://github.com/altsheets/chaincountdown
    nano chaincountdown/server.py
	
sometimes (could not always reproduce it) resulted in

    panic: runtimerror: slice bounds out of range
	
and if it not crashes, then it does not show the file properly when scrolling.

**Comment by altsheets** [comment]
$ docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64
 
$ docker info
Containers: 1
Images: 36
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 38
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.1 (TCL 6.3); master : 7f12e95 - Thu Aug 13 03:24:56 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: that seems to be some personalization ID, I object that
Debug mode (server): true
File Descriptors: 15
Goroutines: 27
System Time: 2015-08-20T22:56:31.27926426Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
 
$ uname -a
MINGW32_NT-6.1 MachineName01 1.0.12(0.46/3/2) 2012-07-05 14:56 i686 unknown

**Comment by mitchcapper** [comment]
No repro in my environment using powershell and win10, can you try the master binary https://master.dockerproject.org/:
Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   5929502
 Built:        Sat Aug 22 00:44:17 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   5929502
 Built:        Sat Aug 22 00:44:17 UTC 2015
 OS/Arch:      linux/amd64

**Comment by thaJeztah** [comment]
@altsheets have you been able to test if this is still an issue with the current master? (https://github.com/docker/docker/issues/15738#issuecomment-140587905)

**Comment by altsheets** [comment]
Thanks for getting back to me.

So you could not reproduce my problem described above?

Does https://www.docker.com/toolbox 
https://github.com/docker/toolbox/releases/download/v1.8.2c/DockerToolbox-1.8.2c.exe
already include the fix for this?
Then I am happy to try. But I am quite busy, and reluctant to be a beta tester. 

Also, I have quit using Docker on Windows - only on Linux now.

**Comment by jhowardmsft** [comment]
This was fixed some time back. Closing.
