### ISSUE TITLE
Docker Quickstart Terminal cannot be resized permanently

### ISSUE THREAD

**Issue by altsheets** [docker/docker#15739]
# MINGGW32 window cannot be resized permanently

Windows (7) with Docker (version 1.8.1, build d12ea79)

The terminal window you are opening when "Docker Quickstart Terminal"
is much much much to small to properly show e.g. the output of docker ps -a 

And I can only resize it for the current session, which means I have to repeat this each time I am opening your "Docker Quickstart Terminal":

* left top corner
* properties
* layout
* Window size ... Width 180  

works, but when OK results in:

    Unable to modify the shortcut:
	.
	Check to make sure it has not been deleted or renamed.
	
so it is valid only for one session.

Any ideas what you could improve?

**Comment by altsheets** [comment]
$ docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64
 
$ docker info
Containers: 1
Images: 36
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 38
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.1 (TCL 6.3); master : 7f12e95 - Thu Aug 13 03:24:56 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: that seems to be some personalization ID, I object that
Debug mode (server): true
File Descriptors: 15
Goroutines: 27
System Time: 2015-08-20T22:56:31.27926426Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
 
$ uname -a
MINGW32_NT-6.1 MachineName01 1.0.12(0.46/3/2) 2012-07-05 14:56 i686 unknown

**Comment by thaJeztah** [comment]
I think this should better be reported in the Docker Toolbox issue tracker; https://github.com/docker/toolbox/issues, that's where development of those tools take place, but I'll ask @jeffdm to have a look here :smile: 

ping @jeffdm do you already have an issue tracking this?

**Comment by jeffdm** [comment]
@thaJeztah thanks for the ping!

We don't track this issue, but it should be fixed with the switch to Git 2.5. @altsheets can you please verify? Thanks!

**Comment by ozlerhakan** [comment]
Hi,

I now get this error after intalling docker [1.9.1](https://github.com/docker/toolbox/releases/tag/v1.9.1) on windows 10, prior to this I did not have such error.

**Comment by AlexTelon** [comment]
I got the same issue, though the solution proposed by @ozlerhakan worked fine.

On windows 7
**docker version:
**
```
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:18:11 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 19:55:25 2016
 OS/Arch:      linux/amd64
```


**docker info:**
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 4.1.17-boot2docker
Operating System: Boot2Docker 1.10.0 (TCL 6.4.1); master : b09ed60 - Thu Feb  4 20:16:08 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.2 MiB
Name: default
ID: NMVE:63VZ:EDEL:ZCO5:3FG6:BDLU:CF7D:N57R:DLVW:IXRD:GK4B:BPAT
Debug mode (server): true
 File Descriptors: 10
 Goroutines: 21
 System Time: 2016-02-05T16:24:35.326478136Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

It seems there still is no issue over at toolbox about this. @jeffdm do you guys want this over at the toolbox repo or is it left out for some reason? I could repost the issue there.

**Comment by thaJeztah** [comment]
@AlexTelon if you could post it there, and add a link here, then we can close it in this repository :heart:

**Comment by AlexTelon** [comment]
@thaJeztah I think you can close it here now :)

**Comment by thaJeztah** [comment]
Thanks closing this in favor of https://github.com/docker/toolbox/issues/408
