### ISSUE TITLE
Ubuntu 14.04 container

### ISSUE THREAD

**Issue by franciscovargas** [docker/docker#15730]
I currently have set up a simple docker build running ubuntu 14.04 for an openCV based application. I don't seem to be able to access the webcam when running the docker instance. Do I need to install drivers for the webcam ? or does docker just not have access to I\O like this ?

**Comment by phemmer** [comment]
The github issue tracker is generally for issues and feature requests. For support using docker I would recommend one of:

The mailing list: https://groups.google.com/forum/#!forum/docker-user
The forums: https://forums.docker.com/
IRC: irc.freenode.net #docker (https://botbot.me/freenode/docker/)

See also https://docs.docker.com/project/get-help/

**Comment by thaJeztah** [comment]
Closing because this is not a bug or feature request, as @phemmer explained. But do not hesitate to ask in the above channels!
