### ISSUE TITLE
Regression: docker exec freezes in experimental build, not in 1.8.1

### ISSUE THREAD

**Issue by felixrabe** [docker/docker#15736]
(This might be a duplicate of issue #15214: "Error running command in existing container with exec".)

## Description of problem:

Running `docker run -tid busybox` and then `docker exec -ti $cid /bin/sh` just hangs.

## `docker version`:

    Client:
     Version:      1.9.0-dev
     API version:  1.21
     Go version:   go1.4.2
     Git commit:   313b371
     Built:        Fri Aug 14 21:06:40 UTC 2015
     OS/Arch:      linux/amd64
     Experimental: true

    Server:
     Version:      1.9.0-dev
     API version:  1.21
     Go version:   go1.4.2
     Git commit:   313b371
     Built:        Fri Aug 14 21:06:40 UTC 2015
     OS/Arch:      linux/amd64
     Experimental: true

## `docker info`:

    Containers: 1
    Images: 7
    Storage Driver: aufs
     Root Dir: /var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 9
     Dirperm1 Supported: true
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 3.16.0-46-generic
    Operating System: Ubuntu 14.04.2 LTS
    CPUs: 1
    Total Memory: 992.2 MiB
    Name: ip-172-31-20-244
    ID: ENWL:4UQ6:MIO5:NG6Z:WC4Y:LGCY:MMCA:DNGX:P3FV:DJP5:JEDF:7JKE
    WARNING: No swap limit support
    Experimental: true

## `uname -a`:

    Linux ip-172-31-20-244 3.16.0-46-generic #62~14.04.1-Ubuntu SMP Tue Aug 11 16:27:16 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

## Environment details (AWS, VirtualBox, physical, etc.):

Running on *AWS* (region eu-central-1, image ami-accff2b1), Linux 3.16 installed via package `linux-image-generic-lts-utopic`, Docker experimental installed per the official instructions.

## How reproducible:

Always.

## Steps to Reproduce:

    ubuntu@ip-172-31-20-244:~$ docker run -tid busybox
    Unable to find image 'busybox:latest' locally
    latest: Pulling from library/busybox
    cf2616975b4a: Pull complete 
    6ce2e90b0bc7: Pull complete 
    8c2e06607696: Pull complete 
    Digest: sha256:df9e13f36d2d5b30c16bfbf2a6110c45ebed0bfa1ea42d357651bc6c736d5322
    Status: Downloaded newer image for busybox:latest
    f8d4ef5806ca93027ec387be38bbda6076cc95ab64010e1c64663d643d07344a

    ubuntu@ip-172-31-20-244:~$ docker ps -a
    CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
    f8d4ef5806ca        busybox             "/bin/sh"           4 seconds ago       Up 4 seconds                            lonely_yalow

    ubuntu@ip-172-31-20-244:~$ docker exec -ti f8d4ef /bin/sh

## Actual Results:

There is no output, and there is no way to quit this via Ctrl-C, but only via closing the terminal (in this case aborting the SSH connection via '\n', '~', '.').

## Expected Results:

The same works in stable 1.8.1 (upgraded "now inofficial" boot2docker 1.8.1 on OS X 10.9), i.e. I get greeted by a usable shell prompt in less than a second.

**Comment by felixrabe** [comment]
Done. Bye bye turtle ;)

**Comment by tonistiigi** [comment]
Seems to be duplicate of #15570

**Comment by felixrabe** [comment]
Yes, I confirm this is fixed in the current https://master.dockerproject.org/linux/amd64/docker binary:

    Version:      1.9.0-dev
    API version:  1.21
    Go version:   go1.4.2
    Git commit:   5ceff3f
    Built:        Fri Aug 21 07:22:39 UTC 2015
    OS/Arch:      linux/amd64

**Comment by felixrabe** [comment]
That was too soon. I have to re-test with the current _experimental_ version.

**Comment by felixrabe** [comment]
Any pointers where I can get a build more current than Aug 14? I can't find a current binary via https://github.com/docker/docker/tree/master/experimental.

`curl -sSL https://experimental.docker.com/ | sh` gives me 313b371 from Aug 14.

`curl -O https://experimental.docker.com/builds/Linux/x86_64/docker-latest` gives me 0e3674d from Aug 11.

**Comment by felixrabe** [comment]
Following https://experimental.docker.com/builds/ also gives the Aug 11 version.

**Comment by felixrabe** [comment]
The same question regarding current experimental builds can be found on the Google Groups mailing list: https://groups.google.com/forum/#!topic/docker-dev/q2EVvraYaGk

**Comment by cpuguy83** [comment]
This is likely a separate issue that should indeed be fixed already by #15598.
You can try with a binary from https://master.dockerproject.org/

**Comment by felixrabe** [comment]
Just confirmed that this is indeed fixed with the current / recent _experimental_ build as well:

    Client:
     Version:      1.9.0-dev
     API version:  1.21
     Go version:   go1.4.2
     Git commit:   5ceff3f
     Built:        Fri Aug 21 12:26:50 UTC 2015
     OS/Arch:      linux/amd64
     Experimental: true

    Server:
     Version:      1.9.0-dev
     API version:  1.21
     Go version:   go1.4.2
     Git commit:   5ceff3f
     Built:        Fri Aug 21 12:26:50 UTC 2015
     OS/Arch:      linux/amd64
     Experimental: true
