### ISSUE TITLE
FR: port mapping switch for windows

### ISSUE THREAD

**Issue by altsheets** [docker/docker#15741]
# feature request: port mapping for windows

**Idea:** Mapping of guest ports to host ports

**Reason:** Docker is not yet fully platform-independent for guest TCP/IP services
( see my workaround-by-complicated-user-manual here: https://github.com/docker/docker/issues/15740#issuecomment-133211078 )

**Suggestions:**

new switch for docker.exe:

    docker run -p 80:80 --guesttohost -d nginx

or 

    docker run -p 80:80 --guesttohost 80 -d nginx

and/or a new command for Dockerfiles:

    ...
    EXPOSE 80
    EXPOSE 443
    GUESTTOHOST

    CMD ["nginx"]

The latter is (a bit dangerous, and) less important - if the former switch is available.

Both 

    GUESTTOHOST

and

    --guesttohost

should be existent, but ignored on Linux systems - then writing one manual would be enough.

I am optimistic that this is possible. I have not looked into the details yet, but for sure, it has been solved already by some extra (VirtualBox) commands, which I simply suggest now to include into the docker.exe. It will have to do some magic manipulation of the Virtualbox-Ethernet-Adapters, to map the wanted guest machine ports to host machine ports. 

Thanks for considering this.

**Comment by altsheets** [comment]
thx GordonTheTurtle :-) but this suggestion is independent of my own system.

**Comment by altsheets** [comment]
I found this information:

    VBoxManage modifyvm "VM name" --natpf1 "guestssh,tcp,,2222,,22"
    With the above example, all TCP traffic arriving on port 2222 on any host interface will 
    be forwarded to port 22 in the guest. The protocol name tcp is a mandatory attribute 
    defining which protocol should be used for forwarding (udp could also be used). 
    The name guestssh is purely descriptive and will be auto-generated if omitted. 
    The number after --natpf denotes the network card, like in other parts of VBoxManage.
    http://www.virtualbox.org/manual/ch06.html#natforward


VBoxManage.exe knows about my "default" machine:

    C:\Program Files\Oracle\VirtualBox>VBoxManage.exe list vms
    ...
    "default" {aaaaaaaa-bbbb-1111-2222-333333333333}


Before my changes:

    VBoxManage showvminfo default --details

    NIC 1:           MAC: 112233445566, Attachment: NAT, Cable connected: on, Trace: off (file: none), Type: 82540EM, Reported speed: 0 Mbps, Boot priority: 0, Promisc Policy: deny, Bandwidth group: none
    NIC 1 Settings:  MTU: 0, Socket (send: 64, receive: 64), TCP Window (send:64, receive: 64)
    NIC 1 Rule(0):   name = ssh, protocol = tcp, host ip = 127.0.0.1, host port = 51122, guest ip = , guest port = 22
    NIC 2:           MAC: aabbccddeeff, Attachment: Host-only Interface 'VirtualBox Host-Only Ethernet Adapter #2', Cable connected: on, Trace: off (file: none), Type: 82540EM, Reported speed: 0 Mbps, Boot priority: 0, Promisc Policy: deny, Bandwidth group: none


My below VBoxManage command results in a "Rule(1)":

    VBoxManage showvminfo default --details

    NIC 1:           MAC: 112233445566, Attachment: NAT, Cable connected: on, Trace: off (file: none), Type: 82540EM, Reported speed: 0 Mbps, Boot priority: 0, Promisc Policy: deny, Bandwidth group: none
    NIC 1 Settings:  MTU: 0, Socket (send: 64, receive: 64), TCP Window (send:64, receive: 64)
    NIC 1 Rule(0):   name = ccdserver, protocol = tcp, host ip = , host port = 9999, guest ip = , guest port = 8888
    NIC 1 Rule(1):   name = ssh, protocol = tcp, host ip = 127.0.0.1, host port = 51122, guest ip = , guest port = 22
    NIC 2:           MAC: aabbccddeeff, Attachment: Host-only Interface 'VirtualBox Host-Only Ethernet Adapter #2', Cable connected: on, Trace: off (file: none), Type: 82540EM, Reported speed: 0 Mbps, Boot priority: 0, Promisc Policy: deny, Bandwidth group: none


This is what I had to do:

    docker-machine stop default
    C:\Program Files\Oracle\VirtualBox\VBoxManage modifyvm default --natpf1 "ccdserver,tcp,,9999,,8888"
    docker-machine start default

now when I am running my server:

    docker run -p 8888:8888 altsheets/chaincountdown

these two addresses result in exactly the same pages in my browser:

    * http://192.168.99.100:8888/
    * http://localhost:9999/

	
**SUCCESS!**
	

N.B.: 

I chose 9999 only for demonstration purposes, of course, the production system should simply map it to the same port 8888.


TODO:

(1) Find a way to change the port forwarding without powering down the VM. Note that in the "Oracle VM VirtualBoxManager" I can actually change port forwarding settings on a running machine!

(2) The above "VBoxManage modifyvm ..." should go into "docker run --guesttohost ..."

:-)

**Comment by cpuguy83** [comment]
It looks like you want docker to modify the VM host's port forwarding rules?
This is not possible, at least not from the daemon... if the docker client has sufficient privileges this could potentially happen, however the extra Dockerfile command would not work (and also is certainly not something that makes sense for the Dockerfile).

You an accomplish this same thing with no added features by listening to the event stream and automatically forwarding ports as needed.

I'm going to close this because it's just not something that really fits in with docker's functionality and can be done externally to docker easily enough.

If you think I've misinterpreted your use-case, please ping here so we can discuss.
Thanks!

**Comment by altsheets** [comment]
Thanks a lot then. I wish you a great weekend, summer, life.

**Comment by altsheets** [comment]
One more comment ...

And I am seeing myself more as a (new enthusiastic) user 
than a developer who writes essential docker patches :-)

> You an accomplish this same thing ...
> by listening to the event stream and 
> automatically forwarding ports as needed.

Sounds as if perhaps that is your way to go then.

What about you write such an easily done extension, to make 
Dockerfiles and/or docker.exe truly platform-independent also 
for internet services guest containers.
