### ISSUE TITLE
docker-1.8.1 requires service restart with systemd

### ISSUE THREAD

**Issue by alunduil** [docker/docker#15755]
On new boot of a system using docker-1.8.1 and systemd, any container created with docker will not have a functioning network stack (unable to even ping the gateway).  After restarting the docker service everything works fine and this is only required on fresh boot of a system.

**Comment by alunduil** [comment]
`docker version`:

```
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        
 OS/Arch:      linux/amd64
```

`docker info`:

```
Containers: 6
Images: 180
Storage Driver: btrfs
 Build Version: Btrfs v4.1.2
 Library Version: 101
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.6-gentoo
Operating System: Gentoo/Linux
CPUs: 4
Total Memory: 15.58 GiB
Name: elijah
ID: GZER:UHHG:V4HV:6YKI:MWUY:ETLV:FZJA:USIM:76CU:4QQV:NYTL:RC4N
Username: alunduil
Registry: https://index.docker.io/v1/
```

`uname -a`:

```
Linux elijah 4.1.6-gentoo #1 SMP PREEMPT Mon Aug 17 21:01:34 CDT 2015 x86_64 Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz GenuineIntel GNU/Linux
```

1. Boot system from powered off state using systemd with enabled docker.service
2. `docker run -t -i --rm alpine:3.2 /bin/sh`
3. `ping ${GATEWAY_IP}`

This results in all packets dropped and no networking available at all.

Restarting the docker service, `systemctl restart docker.service`, clears this right up and the above instructions will result in successful pings and the Internet at large is pingable as well.

**Comment by mavenugo** [comment]
I think this is a dup of #15630.
@alunduil can you please confirm https://github.com/docker/docker/issues/15630#issuecomment-132258988 ?

**Comment by alunduil** [comment]
Looks like a dupe.  Closing this issue and waiting for 1.8.2.
