### ISSUE TITLE
Windows preview tp3 listening on the wrong socket.

### ISSUE THREAD

**Issue by SvenDowideit** [docker/docker#15752]
It looks like the Windows Docker daemon service is TLS encrypted (yay), but is listening to port `2375`.

it should be listening to port `2376` :)

see http://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=docker

(test run over vnc, by calling something like `docker --tlsverify=false -H tcp://127.0.0.1:2375` which complains about oversized record received, and the same to 2376, when the connection is refused outright.

**Comment by StefanScherer** [comment]
As it seems you have to insert some certificates manually. Create the directory `%ProgramData%\docker\certs.d` and put `ca.pem`, `server-cert.pem`and `server-key.pem` into this directory.
Then restart the Docker service. The start script `%ProgramData%\docker\runDockerDaemon.cmd` starts docker with `docker daemon -D -b "$global:SwitchName" -H 0.0.0.0:2376 --tlsverify ...`

**Comment by SvenDowideit** [comment]
I'm not sure that part is working correctly - as the TP3 `runDockerDaemon.cmd` says port `2376`, but the Docker daemon is listening on `2375`.

**Comment by SvenDowideit** [comment]
turns out I totally forgot that `docker daemon -D --tlsverify=false` does not put the daemon into unencrypted mode, it only matches `curl --insecure` - so this is a false report, but the PR makes a worthwhile change :)
