### ISSUE TITLE
can't find pushed image...?

### ISSUE THREAD

**Issue by tony-kerz** [docker/docker#15768]
trying to build and push an image to docker-hub, but after build and push with no errors, image doesn't show up via `docker search` or at `https://hub.docker.com`. 

am i missing something obvious or could this be a bug?

```
~/g/d/hgenkins (tk/hgenkins) $ docker build -t tonykerz/jenkinz .
Sending build context to Docker daemon 4.608 kB
<build steps here>
Successfully built 6f51e16d36ec
```
```
~ $ docker push tonykerz/jenkinz
The push refers to a repository [docker.io/tonykerz/jenkinz] (len: 1)
6f51e16d36ec: Image already exists 
<dozens of these>
902b87aaaec9: Image already exists 
latest: digest: sha256:1ae7d6d3bb7f445e7d29b40fa77e2656e82d50a09c4c0f22ca67d86479787e95 size: 83123
```
```
~ $ docker search tonykerz
NAME                     DESCRIPTION   STARS     OFFICIAL   AUTOMATED
tonykerz/dcos-util                     0                    
tonykerz/hubot-scratch                 0                    
tonykerz/builder                       0   
```
__version info__
```
~ $ docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64
```
```
~ $ docker info
Containers: 111
Images: 70
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 294
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.1 (TCL 6.3); master : 7f12e95 - Thu Aug 13 03:24:56 UTC 2015
CPUs: 8
Total Memory: 1.955 GiB
Name: dev
ID: R7YU:T26R:K5VQ:7TVS:CZIF:ROAJ:IRFL:BC4V:KNE2:6SRJ:L6Z7:SXKJ
Debug mode (server): true
File Descriptors: 11
Goroutines: 19
System Time: 2015-08-22T04:33:32.42039835Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: tonykerz
Registry: https://index.docker.io/v1/
Labels:
provider=virtualbox
```
```
~ $ uname -a
Darwin <mbp-name-here> 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
```

**Comment by dmp42** [comment]
The hub was unable to process its notifications queue.
As far as I know, the problem was fixed, and the queue is draining.
Things should be back to normal soon.

cc @bcwalrus

**Comment by dmp42** [comment]
Dupes to close as well once this is settled:

 * https://github.com/docker/hub-beta-feedback/issues/307
 * https://github.com/docker/hub-beta-feedback/issues/306

**Comment by thaJeztah** [comment]
Thanks for reporting @tony-kerz can you confirm this has been resolved?

Note that for issues related to Docker Hub; Docker Hub is managed by a different team, and issues related to Docker Hub can best be reported via https://support.docker.com, so that they end up directly with them.

**Comment by rrarunan** [comment]
Adding one more dupe to close:
 * https://github.com/docker/hub-beta-feedback/issues/301

**Comment by bcwalrus** [comment]
I think this is no longer an issue. The notification queue was completely drained around Aug 22 08:30 PDT. Really sorry about that. We're also adding more alerting around the queue issue.

**Comment by tony-kerz** [comment]
@bcwalrus thanks man, all set now. i originally thought it was some form of operator error :)

**Comment by mikepulaski** [comment]
It seems like this is still periodically a problem; my image layers have pushed and are stored, but the image itself is not visible to `docker pull`.

I have webhooks registered as well and can confirm that they have not been invoked.

(sorry to comment on an old issue; shall I open a new one?)

**Comment by thaJeztah** [comment]
For docker hub; try contacting support@docker.com, as it's completely separate from the open source "docker" project
