### ISSUE TITLE
docker daemon on Windows should support longer path than 260 characters

### ISSUE THREAD

**Issue by StefanScherer** [docker/docker#15775]
Description of problem:
It seems that the Windows docker client and/or daemon needs to support longer file names than 260 characters. 

`docker version`:
```
Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   4376380
 Built:        Wed Aug 19 14:59:24 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   4376380
 Built:        Wed Aug 19 14:59:24 UTC 2015
 OS/Arch:      windows/amd64
```

`docker info`:
```
Containers: 37
Images: 89
Storage Driver: windowsfilter
 Windows:
Execution Driver: Windows 1854 1.9.0-dev 4376380
Logging Driver: json-file
Kernel Version: 10.0 10514 (10514.0.amd64fre.th2_release.150808-1529)
Operating System: Windows Server 2016 Technical Preview 3
CPUs: 2
Total Memory: 4 GiB
Name: VAGRANT-2016
ID: 3A6C:S32I:LEC6:YQJB:7PIZ:OK6F:5DEX:X4EI:4SQV:U6MJ:FOTF:W2KN
Debug mode (server): true
File Descriptors: -1
Goroutines: 14
System Time: 2015-08-22T12:59:06.9061205-07:00
EventsListeners: 0
Init SHA1:
Init Path: C:\Windows\System32\docker.exe
Docker Root Dir: C:\ProgramData\docker
```

`uname -a`:
```
MSYS_NT-10.0 vagrant-2016 2.1.0(0.288/5/3) 2015-06-28 18:57 x86_64 Msys
```

Environment details (AWS, VirtualBox, physical, etc.):
Windows 2016 TP3 running in VMware Fusion 7.1.2 on a Mac OSX 10.10.4

How reproducible:

Steps to Reproduce:
1. create sub directories until absolute path length is longer than 260 characters
2. docker build -t test .
3.

Actual Results:
Error message `Error checking context: 'can't stat ...`

Expected Results:
Docker should add all sub directories even if the absolute path length is longer than 260 characters. This is needed for Node.js/io.js apps running in a Windows container.

Additional info:

I try to build a Windows Docker image with an io.js application on a Windows 2016 TP3.

I've created a local `iojs:3.1.0` Docker image with [this Dockerfile](https://github.com/StefanScherer/dockerfiles-windows/blob/master/iojs/3.1/Dockerfile).

Then I tried to add a Node.js/io.js application with a deep nested `node_modules` file tree with this `Dockerfile`:

```
FROM iojs:3.1.0

ADD . /code/

CMD "node /code/bin/app.js"
```

But there is an error adding the directory tree:

```
PS C:\Users\vagrant\Documents\example-iojs-app> docker build -t example-iojs-app .
Error checking context: 'can't stat 'C:\Users\vagrant\Documents\example-iojs-app\node_modules\cust-log\node_modules\flaschenpost\node_modules\update-notifier\node_modules\latest-version\node_modules\package-json\node_modules\got\node_modules\duplexify\node_modules\end-of-stream\node_modules\once''.
```

The io.js application works fine running on the Win2016TP3 host itself with io.js 3.1.0 as io.js supports long file names https://github.com/nodejs/node/issues/1990

Is there a way to help improve the Docker daemon for Windows? Is there a description how to build the docker.exe that has to be replaced in the TP3 installation?

**Comment by StefanScherer** [comment]
I hope Go supports long pathes on Windows, just found this one https://github.com/golang/go/issues/3358

**Comment by thaJeztah** [comment]
Thanks for reporting, @StefanScherer 

/cc @jhowardmsft @swernli

**Comment by swernli** [comment]
Thanks for the heads up!  This can indeed be fixed on the docker side by pre-pending the appropriate paths with <code>"\\\?\"</code> as was used in https://github.com/docker/docker/pull/15491.

**Comment by StefanScherer** [comment]
@swernli Thank you! Ah, that seems promising. 

I found another issue in a combination of `WORKDIR` and  the `ONBUILD COPY` while writing a little [blog post](https://stefanscherer.github.io/create-an-io-js-container-image-for-windows/) about your amazing work of porting Docker to Windows. I have seen in #15491 that CI is not up and running for the Windows Docker daemon yet. Should I wait until CI is available or should I file an issue right now? Perhaps this is covered in some other tests.

**Comment by swernli** [comment]
We are still catching up with our tests for the daemon side, but better to file the issue now (and include myself and @jhowardmsft on it) so that we can track it and fix it sooner rather than later.

**Comment by StefanScherer** [comment]
@swernli Thanks for the PR, I've just tested it with latest nightly build 

```
Server:
 Version:      1.9.0-dev
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   9657062
 Built:        Thu Oct 29 02:23:58 UTC 2015
 OS/Arch:      windows/amd64
```

And adding a deep node_modules tree works fine!
I'll close this issue.

**Comment by blaskovicz** [comment]
I had a similar error about "Cannot stat <directory>." Docker build on windows seems to have problems with junctions. The fix was to move to a directory for docker build that has no junctions underneath it.
