### ISSUE TITLE
Docker has wacky error skipping tar.gz ADD behavior.

### ISSUE THREAD

**Issue by envygeeks** [docker/docker#15777]
Given we send Docker a tar that has bad data, docker will continue and add corrupted data to the image, it does not bail, it does not warn, it simply proceeds as if everything was alright.  This is especially problematic when building images from scratch where the entire file system gets corrupted because the head was corrupted in some way but Docker continues as if nothing ever happened.  This script can reliably build a corrupted docker image:

```
img=ubuntu-wily-core-cloudimg-amd64-root.tar.gz
partner_url=https://partner-images.canonical.com/core
codename=wily

[[ -f ubuntu-core.tar.gz ]] || {
  wget --progress=bar -O ubuntu-core.tar.gz $partner_url/$codename/current/$img
  sed -i "1i This should fail but it probably won't" ubuntu-core.tar.gz
}

head -n 1 ubuntu-core.tar.gz
printf 'FROM scratch\nMAINTAINER Some Guy <some.guy@example.com>\nADD ubuntu-core.tar.gz /\n' > Dockerfile
docker build -t bad/ubuntu .
docker run -it bad/ubuntu bash
```

Output:

```
This should fail but it probably won't
Sending build context to Docker daemon 50.37 MB
Step 0 : FROM scratch
 ---> 
Step 1 : MAINTAINER Some Guy <some.guy@example.com>
 ---> Using cache
 ---> 24eda95f7a2e
Step 2 : ADD ubuntu-core.tar.gz /
 ---> Using cache
 ---> c7fea9359d6c
Successfully built c7fea9359d6c
exec: "bash": executable file not found in $PATH
Error response from daemon: Cannot start container 542cac7bdd4eb71e00b09273a9c2b2adcae7ab0c5ec7d88544912dfc99c2f217: [8] System error: exec: "bash": executable file not found in $PATH
```

Docker Info:

```
Containers: 0
Images: 47
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 47
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-26-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 6.94 GiB
Name: envygeeks
ID: C5MI:BZFW:5KHB:N5HE:N46V:YXYM:5WE2:LYRO:EQ7U:FW2J:XQE5:PG4S
WARNING: No swap limit support
```

Docker Version: 1.8.1, build d12ea79

**Comment by thaJeztah** [comment]
I think this is a side effect of `ADD` being far too "magical". `ADD` supports both adding files as-is, and compressed files. In this case it doesn't detect it's a compressed file (because the first line is stripped), so adds the tar.gz file as-is, without extracting.

I'm not really sure we can fix this at this moment, because both cases are "valid". Adding a command "option" to the `ADD` command (I.e. `ADD --extract myfile.tar.gz`) to explicitly tell `ADD` to extract the file (and stop the build if it fails) could help.

Unfortunately, at this moment we don't accept changes to the Dockerfile format; see https://github.com/docker/docker/blob/master/ROADMAP.md

In your case, you're manually downloading the file before adding, so I think it would be best to *validate* the checksum of the downloaded file before adding (which would be good practice anyway, to check it's not tampered with)

/cc @duglin perhaps you have additional thoughts how this can be improved?

**Comment by envygeeks** [comment]
> In your case, you're manually downloading the file before adding, so I think it would be best to validate the checksum of the downloaded file before adding (which would be good practice anyway, to check it's not tampered with)

That conjecture is off point. The script you were given was made specifically for this ticket, that's not even anywhere close to what we do to build our golden images for Docker. We automatically download the core images from Ubuntu and GPG verify a checksum file with Ubuntu's signing key signed by 2 of our signing keys before verifying a checksum. The corruption was noticed by way of somebody forgetting to `>&2` a chroot on our core image adjustments and then our build server reporting that it was unable to start the image tests because of a Docker error.

I don't think it needs to be fixed with any amount of urgency if fixed at all... more than noted on the documentation site that there are edges that can cause corrupted builds.

**Comment by duglin** [comment]
I've opened PR #19592 to address this.

Sadly, as @thaJeztah said, there's just way too much magic around ADD and we can't really do something good - like show an error message.  ADD is designed such that if the magic bits aren't in the file (irrespective of the name ending in .tar.gz) we're just going to copy it and not even try to decompress it.  Attempts have been made to clean this up but no luck yet....

**Comment by envygeeks** [comment]
:+1: Thanks!

**Comment by parag4code** [comment]
where can i find the ubuntu-wily-core-cloudimg-amd64-root.tar.gz file?

**Comment by envygeeks** [comment]
@parag4code https://partner-images.canonical.com/core

**Comment by parag4code** [comment]
Thanks man!
