### ISSUE TITLE
NAT - issue

### ISSUE THREAD

**Issue by kps18** [docker/docker#15784]
HI 

Anybody face NAT issue in  docker

docker version - 1.6.2
Kernel - 3.18.16

**Comment by kps18** [comment]
@GordonTheTurtle 

docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): ba1f6c3/1.6.2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): ba1f6c3/1.6.2
OS/Arch (server): linux/amd64

Containers: 5
Images: 21
Storage Driver: devicemapper
 Pool Name: docker-8:7-34211360-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 5.123 GB
 Data Space Total: 644.2 GB
 Data Space Available: 639.1 GB
 Metadata Space Used: 7.205 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.14 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Kernel Version: 3.18.16
Operating System: CentOS Linux 7 (Core)
CPUs: 64
Total Memory: 503.8 GiB
Name: 
ID: F653:2ITS:Z752:WUVU:APX3:Z6PC:WHAQ:EFSP:B6FN:FLBY:BCNC:QWYA

Linux  3.18.16 #4 SMP Thu Aug 20 20:53:48 IST 2015 x86_64 x86_64 x86_64 GNU/Linux

Port forwarding is not working in the above version. Please help

**Comment by cpuguy83** [comment]
Closing since this is not an issue that should be in the issue tracker.
Please see #docker on IRC, forums.docker.com, or the docker-user mailing list for support.

I would also recommend upgrading to the latest version of Docker, 1.8.1.
Thanks!

**Comment by kps18** [comment]
@cpuguy83 
Hi
i upgraded to latest kernel 1.8.1

Same Port forwarding is not working 

docker --version
Docker version 1.8.1, build d12ea79

iptables -t nat -L -v
Chain PREROUTING (policy ACCEPT 44 packets, 23433 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    7   436 DOCKER     all  --  any    any     anywhere             anywhere             ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT 31 packets, 18782 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 34 packets, 2921 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    1    60 DOCKER     all  --  any    any     anywhere            !loopback/8           ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT 37 packets, 3101 bytes)
 pkts bytes target     prot opt in     out     source               destination         
  375 27000 MASQUERADE  all  --  any    !docker0  172.17.0.0/16        anywhere            
    0     0 MASQUERADE  tcp  --  any    any     172.17.0.4           172.17.0.4           tcp dpt:9110
    0     0 MASQUERADE  tcp  --  any    any     172.17.0.4           172.17.0.4           tcp dpt:8110
    0     0 MASQUERADE  tcp  --  any    any     172.17.0.1           172.17.0.1           tcp dpt:9110
    0     0 MASQUERADE  tcp  --  any    any     172.17.0.1           172.17.0.1           tcp dpt:8110

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    3   180 DNAT       tcp  --  !docker0 any     anywhere             anywhere             tcp dpt:9110 to:172.17.0.1:9110
    0     0 DNAT       tcp  --  !docker0 any     anywhere             anywhere             tcp dpt:8110 to:172.17.0.1:8110

I am not able to connect 9110 and 8110 port.

Kernel version is 3.18.16

Normal port forwarding is working but not working for docker container.
