### ISSUE TITLE
MPI issue w/ libmpich inside latest docker/docker-toolbox.

### ISSUE THREAD

**Issue by WardF** [docker/docker#15797]
Description of problem:

I maintain a set of docker images which perform regression tests for the open-source `netcdf` project.  The image related to this bug report is publicly available as `unidata/nctests:mpich`.  

After performing a fresh install of `docker-toolbox` (tested on Windows 7 and the latest OSX) the `unidata/nctests:mpich` image reports MPI-related failures when running the suite of netcdf tests.   The same image works fine when running under Ubuntu linux (14.04 LTS, Docker client version 1.5), or after downgrading from `docker-machine` to `boot2docker` (installed via `Homebrew`) on OSX.

We have a similar docker image, `unidata/nctests:openmpi` which tests the same MPI-related functionality.  This image works properly in environments using `docker-machine` or `boot2docker`.  

**docker version**:

```
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64
```

**docker info**:

```
DEBU[0000] Trusting certs with subjects: [010U
wfisher] 
Containers: 0
Images: 0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.1 (TCL 6.3); master : 7f12e95 - Thu Aug 13 03:24:56 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: ADHT:AORH:OTCE:VO5N:BTQS:WA72:VN3Z:SHTC:OSOK:GMYA:4RE3:3FBI
Debug mode (server): true
File Descriptors: 10
Goroutines: 16
System Time: 2015-08-24T17:17:56.152324849Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

**uname -a**: 

```
Darwin yakov.unidata.ucar.edu 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64
```

Environment details (AWS, VirtualBox, physical, etc.):

Virtualbox on Windows 7/OSX using the environment produced by a clean install of the Docker-Toolbox.

How reproducible:

Very

Steps to Reproduce:
1. docker run --rm -it unidata/nctests:mpich
2. The above command fails when run in an environment set up by installing docker-toolbox.
3. The above command succeeds when run in a boot2docker-configured environment, or when run directly on a linux box.

Actual Results:

Parallel tests in the netcdf regression test suite fail with 'unexpected results' and various MPI errors.

Expected Results:

All tests should pass.  Running the `unidata/nctests:openmpi` image show how things should look.

Additional info:

The Dockerfiles used to generate this docker image, `Dockerfile.mpich` and `Dockerfile.base`, are available at our public git repository found at https://github.com/Unidata/docker-nctests.

Let me know if I can provide additional info, thanks!

**Comment by WardF** [comment]
I believe discovered the culprit; the `default` virtualbox image created by `docker-machine` only has 1 CPU, whereas `boot2docker` would create a virtualbox image with however many cores it could detect on the system.  I've recreated the `docker-machine` default image, passing `--virtualbox-cpu-count 1` on the command line.  I'm testing the `unidata/nctests:mpich` image on this virtualbox hypervisor; if my suspicions are correct and this fixes the problem, I'll close out this issue.

**Comment by thaJeztah** [comment]
@WardF thanks for doing the additional research. I'll ping the docker-machine maintainers here, so that they can have a quick look before this is closed :+1: 

ping @ehazlett is this a known issue? something that needs improvement? (given that it's a change for people coming from Boot2Docker)

**Comment by WardF** [comment]
@thaJeztah No problem; closing out the issue since the fix worked.  Also corrected a typo in my previous comment; I passed `-1` to `--virtualbox-cpu-count` when recreating the `default` image, not `1`.  Thanks!
