### ISSUE TITLE
`export DOCKER_CONTENT_TRUST=1` versus `sudo docker`

### ISSUE THREAD

**Issue by cpswan** [docker/docker#15790]
Description of problem:

For those invoking `docker` with sudo (rather than running as root or adding their user to the docker group) it's likely that the DOCKER_CONTENT_TRUST env variable won't be passed when using a default sudo setup.

`docker version`:

```
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:32:18 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:32:18 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:

```
Containers: 738
Images: 1639
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 3116
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-29-generic
Operating System: Ubuntu precise (12.04.5 LTS)
CPUs: 1
Total Memory: 993.7 MiB
Name: docker
ID: OEQ3:4OFN:Q4WS:EW5C:HIFM:RDCV:Y6CE:ZE3I:OC3R:FDUB:24FN:XRXV
Username: cpswan
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

`uname -a`:

    Linux docker 3.13.0-29-generic #53~precise1-Ubuntu SMP Wed Jun 4 22:06:25 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.): VMware 5.5 VM

How reproducible:

```
$ export DOCKER_CONTENT_TRUST=1
$ sudo docker pull cpswan/hello_onug
```

Steps to Reproduce:
1. set the env variable `DOCKER_CONTENT_TRUST=1`
2. invoke `sudo docker` for a command that requires trust

Actual Results:

```
Using default tag: latest
Pulling repository docker.io/cpswan/hello_onug
183f0a0d3b62: Download complete
d3cc6fa2aa29: Download complete
9217ba43cf44: Download complete
339c97963d06: Download complete
Status: Image is up to date for cpswan/hello_onug:latest
```

Expected Results:

```
Using default tag: latest
no trust data available
```

Additional info:

The following workarounds may be used:

    sudo -E docker ...

Or 'sudo visudo' and add the following line:

    Defaults        env_keep += "DOCKER_CONTENT_TRUST"

**Comment by endophage** [comment]
So there are a few options here. I frequently just have a terminal open for long periods where I've executed `sudo -s` and then done my env setup. This works well for me because I also frequently have to tweak other docker env settings temporarily when I'm working staging/production hosts.

In addition to the options mentioned above, the `--disable-content-trust` flag is also available which will not be affected by which user the command runs as. The wierdness being, to __enable__ content trust, you need to set `--disable-content-trust=false`, the double negative of "disable" and "false" meaning "I want to use content trust." (this flag was chosen when considering the eventual goal of enabling trust by default).

Long term I believe, and others can comment with more authority, we aim to not require docker to run as root, which will solve these problems in the most natural way.

**Comment by cpswan** [comment]
@endophage some additional comments in the docs might be all that's needed here, otherwise those who regularly use `sudo docker` will come a cropper.

It's nice that `--disable-content-trust=false` does what it does - I think that probably deserves a mention in the docs too, as it provides an invocation by invocation mechanism (rather than per shell with the env variable).

**Comment by endophage** [comment]
It's in the docs already but I've just looked again and it certainly could be called out more clearly, especially in the case of using it to enable content trust. I'll make sure we add some extra explanation.

**Comment by moxiegirl** [comment]
@cpswan The  `--disable-content-trust=false` flag Disabling is discussed in the overview here: 

http://docs.docker.com/security/trust/content_trust/#disable-content-trust-for-specific-operations

Were you working in another area of the docs? I can mention it again.

**Comment by moxiegirl** [comment]
@diogomonica @NathanMcCauley Would y'all like to chime in on the `sudo` situation...sounds like something to document.

**Comment by diogomonica** [comment]
Agreed. Thank you for the contribution @cpswan.

**Comment by cpswan** [comment]
@moxiegirl the docs only show the flag without any boolean operators, so I was unaware that it could be pushed the other way by appending `=false` until @endophage mentioned it

**Comment by moxiegirl** [comment]
Thanks @cpswan I'll make that clearer in the docs.
