### ISSUE TITLE
File mount does not update with changes from host

### ISSUE THREAD

**Issue by greg0ire** [docker/docker#15793]
I have this nginx container, on which I'm mounting a vhost configuration file (indirectly, in fact, I'm using a data volume container). I would like to reload the configuration without stopping the container, with `docker-compose kill -s HUP webserver`, but when I change the configuration file on the host, it does not change on the guest, and *vice versa*. When I restart the container however, the guest takes into account the host changes. Here is an excerpt of my docker-compose.yml : 

```yaml
data:
    build: ./docker
    volumes:
        - .:/srv
        - ../symfony-1.4.20:/usr/lib/symfony-1.4
        - ./docker/conf/nginx_vhost.conf:/etc/nginx/sites-enabled/app.conf
        - .home-developer:/home/developer
        - $SSH_AUTH_SOCK:/tmp/agent.sock
webserver:
    image: greg0ire/nginx
    volumes_from:
        - data
    env_file:
        - ./docker-compose.env
    environment:
        - DNSDOCK_IMAGE=web
    links:
        - appserver
```

**Comment by cpuguy83** [comment]
Can you provide output of `docker info` and `docker version`?
Have you inspected the data in the container after updating to verify?

**Comment by greg0ire** [comment]
> Containers: 33
Images: 207
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 273
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-26-generic
Operating System: Ubuntu 15.04
CPUs: 4
Total Memory: 3.85 GiB
Name: grosbill
ID: UFPX:PUSX:ZCTO:KZYC:VJD5:5R4A:32U7:H4QL:MHLZ:TBF3:J5GS:T3JB
WARNING: No swap limit support

Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64

>  Have you inspected the data in the container after updating to verify?

To check if the data was up-to date, I did this : `docker exec -it carel_webserver_1 /bin/bash`

**Comment by cpuguy83** [comment]
I bet I know what's happening here...

If you are using some editor like vim, when you save the file it does not save the file directly, rather it creates a new file and copies it into place.
This breaks the bind-mount, which is based on inode. Since saving the file effectively changes the inode, changes will not propagate into the container.
When the container is restarted the new inode.
If you edit the file in place you should see changes propagate.

This is a known limitation of file-mounts and is not fixable.

Does this accurately describe the issue?

**Comment by greg0ire** [comment]
>  If you edit the file in place you should see changes propagate.

I just restarted my container, used nano to do the editing and it works! Thanks a lot. Feel free to close this, I am not sure if it should be considered as a bug or not.

**Comment by cpuguy83** [comment]
Closing, it's not really a bug, just how linux works unfortunately.

**Comment by OscarOrSomething** [comment]
Is there any workaround for this? I don't think using nano is really viable in a project larger than 1 file. I'm using Sublime Text and I'd like to keep it that way.

**Comment by greg0ire** [comment]
After reading [this](http://stackoverflow.com/questions/743150/how-to-prevent-vim-from-creating-and-leaving-temporary-files), I guess if I type `set noswapfile`, I might be able to continue using vim. Maybe Sublime Text has a similar option ?

**Comment by cpuguy83** [comment]
@OscarOrSomething Mount a dir instead of a file.

**Comment by OscarOrSomething** [comment]
@cpuguy83 I am mounting a dir.

After some googling, Sublime text has `atomic_save` instead so Adding `"atomic_save": false` to user preferences worked (After a restart). Thanks @greg0ire

**Comment by greg0ire** [comment]
> I am mounting a dir.

Are you sure ? That's really strange… @cpuguy83 : maybe he is mounting a file and a dir (dunno if this is possible).

**Comment by tiaguinho** [comment]
@greg0ire I try use `set noswapfile`, but nothing change..
Isn't possible use vim with volumes?

**Comment by greg0ire** [comment]
> Isn't possible use vim with volumes?

I don't know, but I'm interested in your results.

> This breaks the bind-mount, which is based on inode. Since saving the file effectively changes the inode, changes will not propagate into the container.
When the container is restarted the new inode.

1. Try [finding out the inode](http://www.cyberciti.biz/faq/linux-bsd-appleosx-unix-find-file-inode/) of your file before, change your file with vim, and check that the inode changes. This should validate @cpuguy83 's theory
2. If it turns out to be valid, then do the same, but set `noswapfile` before changing the file.
3. Please report back with your findings.

**Comment by tiaguinho** [comment]
I made some tests @greg0ire, and this is the result.

With or without `set noswapfile` the inode changes, everytime the file is saved, but I made a little research how to make vim don't change the inode of a file.
The result was to use `set backupcopy=yes`, I try and the inode don't change when the file is modified.

Thank you guys.

**Comment by greg0ire** [comment]
And than you for your feedback, it is interesting.

**Comment by OscarOrSomething** [comment]
This issue has come back for me a few days later. In both Sublime Text (3, with atomic save false) and Atom, The inode doesn't change at all. I assume this is an issue with the editors?

**Comment by OscarOrSomething** [comment]
It doesn't seem to be an editor issue [(at least on atom)](https://discuss.atom.io/t/inode-not-changing-on-file-save-causes-problems-with-docker-binds/23393/3)

The files do update but only after around a minute which is better but still incredibly annoying.

**Comment by thaJeztah** [comment]
@OscarOrSomething I suspect that's because VirtualBox shared folders don't support inotify; https://www.virtualbox.org/ticket/10660

**Comment by OscarOrSomething** [comment]
@thaJeztah I'm not using Virtual box. Arch Linux Docker version 1.9.1, build a34a1d5-dirty

**Comment by thaJeztah** [comment]
@OscarOrSomething oh, ignore my comment then :+1: (I know many people ran into that when using boot2docker/VirtualBox)

**Comment by sebwebdev** [comment]
Turning off sentfile off for Nginx solved this issue for me. Just put this in your vhost conf:
```
senfile off;
```
The equivalent for Apache it is "EnableSendfile off".
See https://abitwiser.wordpress.com/2011/02/24/virtualbox-hates-sendfile/ for reference.

**Comment by greg0ire** [comment]
@sebwebdev : thanks, but I think you are a bit off topic : obviously, you are not mounting the file you are providing with your vhost one by one. The issue at hand is about file mounts.

**Comment by sebwebdev** [comment]
You are right, but @OscarOrSomething 's problem sounds exactly like my issue. Maybe it points someone in the right direction.

**Comment by greg0ire** [comment]
I reread @OscarOrSomething and, after all he does not state if he was having the issue with the nginx configuration or with assets served by his webserver (but since he is having the issue with **several** files, the latter is more likely).

@OscarOrSomething : if you are having problems with assets, you should probably check the contents of the file from inside docker directly to know if the problems lies with docker or your webserver. The problem could be an HTTP caching problem if the webserver is at fault.

**Comment by OscarOrSomething** [comment]
Hi,

I checked and they are updating on the docker so it must be Apache.

Is this right?

```
/etc/apache2/sites-available/000-default.conf 

<VirtualHost *:80>
        # ...

        EnableSendfile Off
        EnableMMAP Off

        CustomLog ${APACHE_LOG_DIR}/access.log combined

        # ...
</VirtualHost>
```

**Comment by betoharres** [comment]
I'm facing this problem too, none of the suggestions worked for me. Any help? This kind of problem keeps me from developing in docker :( which I really want to

**Comment by cpuguy83** [comment]
@betoharres Either don't use virtualbox, or disable sendfile in apache/nginx.

**Comment by betoharres** [comment]
@cpuguy83 thanks, disabling sendfile didn't worked at all, now the files sometimes changes and sometimes changes back to previous state when reloading the page without updating to the newest changes, urgh

**Comment by stcalica** [comment]
I just have a node express app running in docker using docker-compose volume to map my html files to the container. Getting the same behavior. It is not updating in the docker container. i did the same with vim and add `set nobackup` and other settings. Does anyone have any updates on this?

**Comment by moneal** [comment]
I'm having the same issue with phpstorm and docker via virtualbox. The apache sendfile change didn't seem to help. I've also tried adjusting the save settings in phpstprm and no change.

**Comment by thaJeztah** [comment]
@stcalica @moneal you may be interested in https://blog.docker.com/2016/03/docker-for-mac-windows-beta/, which gets rid of VirtualBox and resolves these kind of issues

**Comment by daithi-coombes** [comment]
I'm having the same issue.
host: Debian 8 (jessie)
docker: Docker version 1.10.3, build 20f81dd

docker-compose.yml:
```yaml
web:
  build: .
  links:
    - mysql
  environment:
    - WORDPRESS_DB_PASSWORD=****
    - WORDPRESS_DB_USER=root
    - WORDPRESS_DB_NAME=asdf
  ports:
    - 0.0.0.0:8080:80
  working_dir: /var/www/html
  volumes:
    - ./plugins:/var/www/html/wp-content/plugins
    - ./themes:/var/www/html/wp-content/themes
mysql:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=****
    - MYSQL_DATABASE=asdf
```

Dockerfile:
```
FROM wordpress

RUN echo 'EnableSendfile Off' >> /etc/apache2/apache2.conf
```
This issue persists on both Atom and SublimeText3 and is killing me. I've added the `EnableSendfile Off` to apache conf, which has reduced the waiting time from a few mins to about 1 minute.

If, however, I `grep` the edited file from within the docker container then the changes will take effect instantly. So my workflow now is:

1. make changes on host
2. in container run `cat path_to_file | grep 'foo'`

From here I'm lost as to a solution (barely understand `inode` and filesystems etc)

**Comment by cpuguy83** [comment]
These are not issues with Docker.
Mounting individual files is tricky.
A file path and a file inode are different things.

A file path is more akin to a git tag where as an inode is like a commit hash.
Just like a git tag can be changed to point to a different hash, so can a file path point to a new inode.
A commit hash is definite, it doesn't change, likewise for an inode.
So, file paths are just references to an inode. These references can and do change depending on the actions you perform (e.g. `mv /foo /bar` defeferences `/foo` from the underlying inode and creates a new reference `/bar` to that same inode)

When you bind mount a path (file or dir), you are mounting an inode to a new location (kind of like creating a new git tag pointing to the same commit hash).

If you do something like move a bind-mounted dir to a new location, and then replace it with another dir, the bind-mount will follow the original dir, same for files.
With many editors, the editor will write to a temp file, then replace the real file with the temp file on save, in effect dereferencing the inode (like pointing a git tag to a different commit) from the given path and a new inode taking the reference.
Since mounts follow the inode, not the path reference, on the host side you are reading/writing to a new inode, on the container side you are reading/writing from the original inode.

**Comment by daithi-coombes** [comment]
@cpuguy83 that explains `inode` a lot better than anything I've come across past few days - thanks ;)

But I'm still lost as to how `grep`ing the changed file triggers the changes. Also note that if I grep a string that doesn't exist in the file then the problem persists - this is very weird behavior for me. Also if I `cat` the file, without grep, I can see the changes but the issue persists. I've also tried `tail`ing the file with no joy.

So by piping `cat` into `grep`, and only when grep finds a result, something is triggered that lets `apache` know that the file has updated. Maybe a flag or something?

**Comment by daithi-coombes** [comment]
I have to report that my previous hack of running `cat path_to_file | grep 'foobar'` was a false positive. I got 2 hours today of docker working and then its back to make a change, reload, reload, reload, reload...

I don't see how this issue isn't considered a serious blocker if it means that nobody can ever develop on Docker.

**Comment by moneal** [comment]
I updated to the docker beta on mac and so far running grep has always shown the correct update but apache is still not seeing the change.

**Comment by moneal** [comment]
Turns out it was the opcache settings in the wordpress image I was using. Adding the below lines to my Dockerfile fixed the problem for me (no problems in an hour). Now the files are showing in the container and when previewing with apache.

```
FROM wordpress:latest
RUN rm -rf /usr/local/etc/php/conf.d/opcache-recommended.ini
```

**Comment by daithi-coombes** [comment]
@moneal +1 - that seems to have done the trick

**Comment by seeekr** [comment]
Came here because I had a similar issue, stating my solution for others searching on the web:

If nginx is not sending updated static files, make sure to add

```
sendfile off;
```

to your nginx config. Does the trick for me.

**Comment by cpuguy83** [comment]
@seeekr or use Docker4Mac and it also just works.

**Comment by seeekr** [comment]
@cpuguy83 True, that's something that works really well in Docker for Mac. But other things don't (yet), so for some things and for some folks Docker Toolbox / Docker Machine-based Docker on Mac is still necessary, for now. (I've hit roadblocks with Docker Compose (known DNS resolver issue) as well as with rancher/k8s (though that one may have been simply due to my inexperience with those technologies and less about D4M).)

**Comment by thaJeztah** [comment]
k8s isn't fully compatible with Docker 1.11 yet, also k8s does some things outside of the "api" for Docker (direct access to files in `/var/lib/docker`, working around standard networking in docker), which is, well, not always the most reliable approach.

**Comment by buildog** [comment]
I'm experiencing a similar issue on Mac 10.11.4, everything work fine except the volume update, while the same config is working fine on ubuntu.

`Docker version 1.10.0, build 590d5108`


**Dockerfile:**

```
FROM node:5-slim

# create a layer for dependencies so they're cached
RUN mkdir -p /reactjs
WORKDIR /reactjs
COPY package.json package.json
RUN npm install
RUN npm install -g concurrently

# copy the source and build
COPY . /reactjs

# add user and transfer ownership
RUN useradd -d /reactjs adrien \
	&& chown -R adrien:adrien /reactjs \
	&& chmod -R g+rw /reactjs

```

**Docker-compose:**

```
web:
    image: 1a35b1ab7c06
    command: npm run dev:watch
    volumes:
        - ./src:/reactjs/src
    ports:
        - "8083:8083"
    environment:
        NODE_ENV: development
        PORT: "8083"

```

**Comment by magbicaleman** [comment]
I have Docker for Mac. Adding a new file with code works instantly. Yay, right? When I modify the file with `Atom` text editor, the changes take around a minute. 

The image I'm using is the [official Wordpress image](https://hub.docker.com/_/wordpress/), even if Docker for Mac fixes the `inode` stuff, it wouldn't seem like it. Why? Because there seems to be a caching of files as @moneal pointed out earlier. 

For example make a new file:
```php
// my-plugins/stopper.php
<?php
  die('edit me 1');
// This will happen instantly when you reload
```

```php
// my-plugins/stopper.php
<?php
  die('edit me 2');
// This will not instantly change, we changed it to number 2
```

```php
// my-plugins/stopper.php
<?php
  opcache_reset();
  die('edit me 3');
// This will work instantly, we changed it to number 3
```

**Comment by unmultimedio** [comment]
In case anyone here searching for the problem, and having a Dockerized Rails5 app, this might be helpful: http://stackoverflow.com/questions/37144122/dockerized-rails-5-rc1-application-not-picking-up-updates-to-controllers-and-mod

**Comment by JeNeSuisPasDave** [comment]
I've worked up a solution that uses `rsync` to push local file and directory changes to the data volume (either classic data volumes or data volume containers). This works well for Docker Toolbox scenarios on a Mac and should also work for Windows folks via Bash for Windows. See the examples at https://github.com/JeNeSuisPasDave/asd-sync-src-to-container and a discussion of the issue at https://www.develves.net/blogs/asd/2016-11-26-still-using-docker-toolbox/. I've been this mechanism on a variety of projects to great success.

**Comment by dacz** [comment]
Maybe little bit later but I discovered, that changes on php (wordpress development) in docker done in Atom editor do not propagate to container (changes not visible until container restart), using sublime text editor is ok and working.

Probably different way Atom editor and Sublime work with files as mentioned by @cpuguy83 .

**Comment by klaszlo** [comment]
@cpuguy83: It could be easily workarounded inside docker. 

Instead of watching the file's inode, it should be watching the parent's directory inode, then resolve the file change from there. 

Or at the *VERY LEAST* a simple warning should be displayed, when a `docker run` is issued.

**Comment by cpuguy83** [comment]
@klaslo docker does not monitor anything.in this regard. It relies on the kernel, and the kernel does not support this.
The right place to "fix" this is the kernel.
We could introduce hacks, but I'm not sure it's worth it, at least not right now.

**Comment by klaszlo** [comment]
@cpuguy83: 
1. displaying a warning does not require kernel support
2. monitoring how many path points to an inode is already supported. 
So overwriting a file with a new one is detectable.

`docker run ... -d /home/user/data/something.txt:/data/something.txt`
`echo "new content" > /home/user/data/something2.txt`
`mv something2.txt something.txt`

Then the inode table have one row less, so it is detectable. Docker already knows the original path (`/home/user/data/something.txt`), also knows the inside path (`/var/lib/docker/volume/.../something.txt`), 
so he can check and remount the new path.

Or file path in volumes should be disabled. It is more trouble, then good.

**Comment by aiphee** [comment]
@cpuguy83 s answer helped me.  Now i do this:
``` BASH
nano copy_authorized_container_keys # editace kopie
chattr -i authorized_container_keys # odebrat RO status
cp authorized_container_keys copy_authorized_container_keys # přepsání kopií v místě
chattr +i authorized_container_keys # vrátit RO status
```

**Comment by tomschinelli** [comment]
> I bet I know what's happening here...
> 
> If you are using some editor like vim, when you save the file it does not save the file directly, rather it creates a new file and copies it into place.
> This breaks the bind-mount, which is based on inode. Since saving the file effectively changes the inode, changes will not propagate into the container.
> When the container is restarted the new inode.
> If you edit the file in place you should see changes propagate.
> 
> This is a known limitation of file-mounts and is not fixable.
> 
> Does this accurately describe the issue?

Thank you! 
My Volume Setup was the follow: 
```
services:
  db:
    . . .
    volumes:
      - ./docker/db/startup.sh:/docker-entrypoint-initdb.d/startup.sh
```

My goal was to debug the script, after the container was created

so I changed the script and I executed it inside the docker container. nothing "new" happend.

I moved the startup script to a "startup" folder and changed the docker-compose.yml

```
services:
  db:
    . . .
    volumes:
      - ./docker/db/startup/:/docker-entrypoint-initdb.d/
```

I executed the script again inside the docker container and my changes w.ere recognized.

PS: my english sucks :D

**Comment by RiccardoManfrin** [comment]
> I bet I know what's happening here...
> 
> If you are using some editor like vim, when you save the file it does not save the file directly, rather it creates a new file and copies it into place.
> This breaks the bind-mount, which is based on inode. Since saving the file effectively changes the inode, changes will not propagate into the container.
> When the container is restarted the new inode.
> If you edit the file in place you should see changes propagate.
> 
> This is a known limitation of file-mounts and is not fixable.
> 
> Does this accurately describe the issue?

Dazed and confused.. saved my afternoon

**Comment by jlegido** [comment]
@RiccardoManfrin  I faced exactly the same issue (in another docker image), thanks for your comment, for sure saved me a lot of time....

**Comment by ismailcherri** [comment]
If someone is facing the same issue with Docker PHP image, another helpful thing is to disable any PHP cache extension e.g. opcache. memcache, etc

**Comment by GreatFireWall** [comment]
Is there any better solutions..  I'm using VSCode facing same issue. Mounting folder instead of a single file is not a good idea.

**Comment by thaJeztah** [comment]
Unfortunately I don't think there's a way to make bind-mounting single files work; mounting a folder is really the only solution if the editor does a "move old, and write updated file to old location"

**Comment by GreatFireWall** [comment]
Okay.. Thank you all saving my time.. 🌹

**Comment by Wirone** [comment]
Yesterday I faced this issue when using [Docker HostManager](https://github.com/iamluc/docker-hostmanager/) - `/etc/hosts` wasn't updated though DHM container was working. Yes, I use `vim` for simple editing and didn't have idea that swapping files on save causes inode change and Docker file mount desynchronization. I'll sum up what I did:

- Updated `~/.vimrc` with:
  ```
  " Disable swapping files in the same directory as edited file,
  " mostly for editing /etc/hosts which is mounted to Docker HostManager
  " and swapping causes inode change and breaks DHM.
  " @see https://stackoverflow.com/a/15317146/842480
  " IMPORTANT: directories must exist, so create them!
  :set backupdir=~/.vim/backup//
  :set directory=~/.vim/swap//
  :set undodir=~/.vim/undo//
  ```
- NeoVim users should also add `source ~/.vimrc` to `~/.config/nvim/init.vim`
- Added ACL to `/etc/hosts` so I don't need to use `sudo` and my own `.vimrc` is loaded: `sudo setfacl -m  u:your-user:rwX /etc/hosts`

Now, when I edit `/etc/hosts` manually, it is instantly propagated to DHM container and everything works like it should. Thanks all for your comments, it helped me to find real issue :)

References:
- https://stackoverflow.com/a/15317146/842480
- https://stackoverflow.com/questions/3495124/not-reading-vimrc#comment86939843_28422013

**Comment by tjura** [comment]
I had the same problem on Windows 10 after updating Docker to 2.1.* 
To solve it I rearrange my app structure.

```
volumes:
- './:/var/www/html/app/'
- './protected/data/mysql:/var/lib/mysql'
- './docker/php/vhost.conf:/etc/apache2/sites-enabled/000-default.conf'
- './docker/php/cert/:/etc/apache2/ssl/'
- './docker/php/config/php.ini:/usr/local/etc/php.ini'
etc ...
```
I thing mapping whole directory `./` 
in combination with other mappings caused problem.

**Comment by spraff** [comment]
My workaround was to `ln /tmp/foo path/to/foo` the extra reference count on the inode means it doesn't change when the editor writes the new file.

**Comment by ZackKing** [comment]
have the same  problem

```shell
volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
```

i change for this and it  work

```shell
volumes:
      - /work/docker/nginx/conf.d:/etc/nginx/conf.d
```

i think the reason is
```shell
./
```

**Comment by digglife** [comment]
Thanks to @greg0ire and cpuguy83 . It's always a relief to me when some mysterious technical glitch that happened to me has a decent reason.

**Comment by nimpossible** [comment]
> > If you edit the file in place you should see changes propagate.
> 
> I just restarted my container, used nano to do the editing and it works! Thanks a lot. Feel free to close this, I am not sure if it should be considered as a bug or not.

The `nano` approach is not working for me! :-(

**Comment by DiegoChajtur** [comment]
> > > If you edit the file in place you should see changes propagate.
> > 
> > 
> > I just restarted my container, used nano to do the editing and it works! Thanks a lot. Feel free to close this, I am not sure if it should be considered as a bug or not.
> 
> The `nano` approach is not working for me! :-(

I edit a copy of file and after `cat` to new file:
`vi file_new`
`cat file_new > mounted_file`
note: `>` overwrite entire file

**Comment by nicolajknudsen** [comment]
Ouch. So this is why we sometimes have to reload our containers inexplicably. This is a dreadful bug, I must say that I don't really agree with it being closed. When explicitly volume binding a file _name_ I would expect changes to the file with that name to be reflected in the container without the need to have knowledge about the intricacies of the file system.

Is it really impossible to monitor for example the modified time stamp and update the inode reference accordingly?

**Comment by thaJeztah** [comment]
It's how the linux kernel works 🤷‍♂️  you can try it on your host (on a linux machine, but probably works on macOS as well);


```bash
# create your file on the host
echo "# my-file" > myfile.txt

# create a directory (this is the "container's filesystem")
mkdir container

# create the mountpoint inside the container's filesystem
touch container/myfile.txt

# mount the file from the host into the container
mount -o ro,bind myfile.txt container/myfile.txt

# read the bind-mounted file "inside the container"
cat container/myfile.txt
# my-file

# "modify" the file, in this case, using `sed`, which uses a temporary file, then replaces the file
sed -i 's/my-file/my-file-updated/g' myfile.txt

# check that the file "on the host" is updated
cat myfile.txt
# my-file-updated

# check the mounted file "inside the container:
cat container/myfile.txt
# my-file

# unmount the file
umount container/myfile.txt
```

**Comment by videoMonkey** [comment]
This thread is amazing. I was running into this problem and effectively, yes, I was using vim and yes, `set backupcopy=yes` makes things work as hoped. Thanks for resolving my problem users of github 😊

**Comment by sre-data-engineer** [comment]
In Vim you can use `backupcopy`  option set to `yes`

> ['backupcopy'](http://vimdoc.sourceforge.net/htmldoc/options.html#'%20rel=) ['bkc'](http://vimdoc.sourceforge.net/htmldoc/options.html)	string	(Vi default for [Unix](http://vimdoc.sourceforge.net/htmldoc/os_unix.html#Unix): "yes", otherwise: "auto")
> 
> 
> 	"yes"	make a copy of the file and overwrite the original one
> 
> 	Making a copy and overwriting the original file:
> 	- Takes extra time to copy the file.
> 	+ When the file has special attributes, is a (hard/symbolic) link or
> 	  has a resource [fork](http://vimdoc.sourceforge.net/htmldoc/os_unix.html#fork), all this is preserved.
> 	- When the file is a link the [backup](http://vimdoc.sourceforge.net/htmldoc/editing.html#backup) will have the name of the link, not of the real file.

**Comment by Krisslk** [comment]
> > If you edit the file in place you should see changes propagate.
> 
> I just restarted my container, used nano to do the editing and it works! Thanks a lot. Feel free to close this, I am not sure if it should be considered as a bug or not.

hey, I am facing the same issue, did you start the docker container and used nano to edit the nginx.conf and save, I just tried it but didn't work, can you elaborate how you overcome this issue, big help, thanks
