### ISSUE TITLE
[RFE] add command to generate/output manifest, blobs and digest

### ISSUE THREAD

**Issue by TomasTomecek** [docker/docker#15794]
In [pulp](https://pulp-docker.readthedocs.org/en/latest/) you can store docker images and serve them via readonly registry API. The way v1 content is uploaded is that you `docker save` the image and upload it to pulp via pulp's API. With v2, we would like to upload blobs and manifest directly. Unfortunately there is only a single way to get those: via v2 registry API. That's pretty cumbersome.

Would it possible for docker client to output manifest and blobs?

I have in mind something like:

```
$ docker manifest <image>
{
   "name": "image",
   "tag": "latest",
   "architecture": "amd64",
   "fsLayers": [
      {
         "blobSum": "sha256:074533a2d610d82f28097af30284da4077614e30cb0171f0d8d859d2bd294d74"
      },
...
```

and

```
$ docker export -o blob.tar.gz --blob sha256:074533a2d610d82f28097af30284da4077614e30cb0171f0d8d859d2bd294d74
```

This is *not* a dupe of https://github.com/docker/distribution/issues/727

**Comment by LK4D4** [comment]
btw ping @estesp 
I think it's not so hard to implement and might be useful

**Comment by estesp** [comment]
Conceptually we are just now discussing what a command/subcommand that interacts with manifests looks like; see this comment for probably the best description of what we think it would include: https://github.com/docker/docker/issues/24739#issuecomment-233771271

Note that the functionality requested here is represented there in the UX list items 1 and 3.

**Comment by TomasTomecek** [comment]
This can be easily done now with [skopeo](https://github.com/projectatomic/skopeo).

I also feel like that #24739 is a superset of this, hence closing.

@LK4D4 @estesp  thanks for update!
