### ISSUE TITLE
Slow create calls leading to FD issues

### ISSUE THREAD

**Issue by euank** [docker/docker#15802]
##### Issue Report Template

`docker version`: 
```
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
# hangs, server won't respond to any api calls after reaching broken state
``` 
`docker info`:
```
$ # Note, this is a similar instance (docker installed in same way, but not used yet) because the broken instance will not respond to docker info api calls
$ docker info
Containers: 0
Images: 0
Storage Driver: devicemapper
 Pool Name: docker-202:1-263526-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 305.7 MB
 Data Space Total: 107.4 GB
 Data Space Available: 6.766 GB
 Metadata Space Used: 725 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.14.48-33.39.amzn1.x86_64
Operating System: Amazon Linux AMI 2015.03
CPUs: 1
Total Memory: 1.957 GiB
Name: ip-172-31-37-115
ID: BFKD:H6TL:LN4P:5MPD:PTJR:RII2:FJXT:NQJ4:R7NJ:RY2Z:ZA4Z:K7DM
```
`uname -a`: `Linux ip-172-31-xxx-xxx 3.14.35-28.38.amzn1.x86_64 #1 SMP Wed Mar 11 22:50:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`
Docker package installed from the docker-maintained centos yum repo.
```
$ rpm -q docker-engine
docker-engine-1.7.1-1.el6.x86_64
```
Environment: AWS

How reproducible:
Fairly reproducible, though one reproduction is time consuming (on the order of 5 hours). This repro is running very short-lived ECS tasks as quickly as possible, essentially.
The other is [this script](https://gist.github.com/euank/f39e76b7f9ef414c20ea#file-docker_create-go).

Steps to Reproduce:
0. Either lower Docker's or raise your ulimit if your distro modifies the default limits for Docker.
1. Run the above linked code with a suitably low `-sleep` parameter. 
2. Wait for Docker to begin experiencing "too many open files" issues, and then some
3. Kill the above-run client.

Actual Results:
Docker begins experiencing "too many open files" issues even if it can keep up at first, showing that create calls are taking longer over time.
Docker also, once it hits maximum open FDs, sometimes remains in that state perpetually, even with the client stopped.

Expected Results:
Ideally Docker should mitigate ever reaching this state via rate-limiting the client or some other means.
Once in that state, Docker should be able to recover if the abusive client goes away.

### More detailed information

When running a fairly intensive load of short-lived containers on [ECS](https://aws.amazon.com/ecs/), we find ourselves consistently having the Docker daemon run out of file descriptors after running for several hours. Near the end of this issue, I've also include a reproduction that attempts to mimic this without involving ECS at all.

I think this is ultimately caused by "create" calls taking increasing amounts of time until eventually ~1000 create calls pile up, causing the Docker daemon to hit its 1024 fd limit.

Possible improvements for this include our client behaving better, the Docker daemon rate-limiting requests, or create calls not taking as long.

However, this issue often leads into a worse issue: Once the Docker daemon has hit the maximum number of FDs, frequently it just stays there in a broken state forever, even after all abusive clients have stopped making requests and, even. have exited. It still retains a large number of `/var/run/docker.sock` FD references open.
Once the Docker daemon gets into this state, it can't serve any request until restarted. The following information was gathered from an instance in this broken state:

Although I can't run `docker info` on that instance (can't service any API requests), it's using devicemapper and running on the Amazon Linux AMI, though I'm using the docker-provided yum repository to install docker:

The Docker daemon's logfile shows the following sorts of messages:
```
time="2015-08-20T18:50:41.639179694Z" level=info msg="POST /containers/create"
time="2015-08-20T18:50:41.639534449Z" level=error msg="Handler for POST /containers/create returned error: open /var/lib/docker/graph/8c2e06607696bd4afb3d03b687e361cc43cf8ec1a4a725bc96e39f05ba97dd55/layersize: too many open files"
time="2015-08-20T18:50:41.639568826Z" level=error msg="HTTP Error" err="open /var/lib/docker/graph/8c2e06607696bd4afb3d03b687e361cc43cf8ec1a4a725bc96e39f05ba97dd55/layersize: too many open files" statusCode=500
time="2015-08-20T18:50:41.669537070Z" level=error msg="leaving endpoint failed: a container has already joined the endpoint"
time="2015-08-20T18:50:41.693015644Z" level=error msg="Handler for DELETE /containers/{name:.*} returned error: Cannot destroy container c5c4b4cbaff24f40226e999f6bf6c3a98e2a49064145f14d876e4b1bb118252b: Driver devicemapper failed to remove root filesystem c5c4b4cbaff24f40226e999f6bf6c3a98e2a49064145f14d876e4b1bb118252b: Can not set cookie: dm_task_set_cookie failed"
time="2015-08-20T18:50:41.693097901Z" level=error msg="HTTP Error" err="Cannot destroy container c5c4b4cbaff24f40226e999f6bf6c3a98e2a49064145f14d876e4b1bb118252b: Driver devicemapper failed to remove root filesystem c5c4b4cbaff24f40226e999f6bf6c3a98e2a49064145f14d876e4b1bb118252b: Can not set cookie: dm_task_set_cookie failed" statusCode=500
time="2015-08-20T18:50:41.693190632Z" level=error msg="Error unmounting device 15ab0815244586fe9ff34747e11076393ab3b3b6e7efa8eb94b482baa98653c2: UnmountDevice: device not-mounted id 15ab0815244586fe9ff34747e11076393ab3b3b6e7efa8eb94b482baa98653c2"
time="2015-08-20T18:50:41.693322093Z" level=error msg="Handler for POST /containers/{name:.*}/start returned error: Cannot start container 15ab0815244586fe9ff34747e11076393ab3b3b6e7efa8eb94b482baa98653c2: [8] System error: exec: \"invalid\": executable file not found in $PATH"
time="2015-08-20T18:50:41.693373616Z" level=error msg="HTTP Error" err="Cannot start container 15ab0815244586fe9ff34747e11076393ab3b3b6e7efa8eb94b482baa98653c2: [8] System error: exec: \"invalid\": executable file not found in $PATH" statusCode=404
2015/08/20 18:50:41 http: Accept error: accept unix /var/run/docker.sock: too many open files; retrying in 5ms
time="2015-08-20T18:50:41.898376889Z" level=info msg="POST /containers/create"
time="2015-08-20T18:50:41.898507460Z" level=error msg="Handler for POST /containers/create returned error: open /var/lib/docker/repositories-deviceThis is ultimately caused by "create" calls taking increasing amounts of time until eventually ~1000 create calls pile up, causing the Docker daemon to hit its 1024 fd limit.mapper: too many open files"
time="2015-08-20T18:50:41.898537387Z" level=error msg="HTTP Error" err="open /var/lib/docker/repositories-devicemapper: too many open files" statusCode=500
2015/08/20 18:50:42 http: Accept error: accept unix /var/run/docker.sock: too many open files; retrying in 5ms
time="2015-08-20T18:50:42.063603037Z" level=info msg="DELETE /containers/f7d67c5d96bd13c7855c19ffc3c0cca14d108a71cf107edf438f97e246cd6f4e?v=1"
2015/08/20 18:50:42 http: Accept error: accept unix /var/run/docker.sock: too many open files; retrying in 10ms
...
time="2015-08-20T18:50:49.960666091Z" level=error msg="Handler for POST /containers/create returned error: Error saving transaction metadata: Error creating metadata file: open /var/lib/docker/devicemapper/metadata/.tmp262161696: too many open files"
...
time="2015-08-20T23:15:52.876495343Z" level=error msg="collecting system cpu usage: open /proc/stat: too many open files"
2015/08/20 23:15:53 http: Accept error: accept unix /var/run/docker.sock: too many open files; retrying in 1s
time="2015-08-20T23:15:53.876538989Z" level=error msg="collecting system cpu usage: open /proc/stat: too many open files"
2015/08/20 23:15:54 http: Accept error: accept unix /var/run/docker.sock: too many open files; retrying in 1s
...
```
```
$ echo $(pidof docker)
2729
$ sudo nsenter --mount=/proc/$(pidof docker)/ns/mnt -- ss -p | grep docker
u_str  ESTAB      0      0      /var/run/docker.sock 2103638               * 0       users:(("docker",pid=2729,fd=986))
u_str  ESTAB      0      0      /var/run/docker.sock 1938680               * 0       users:(("docker",pid=2729,fd=185))
... # 1015 of these entries
```
I've taken a goroutine stack dump of it in this state as well, uploaded [here](https://gist.github.com/euank/0e5fb7020408788772b7).

What create-times and fd-counts look like leading up to this issue (when reproduced using ECS + short-lived tasks constantly running):
![fds_vs_create](https://cloud.githubusercontent.com/assets/2147649/9454065/28a58d04-4a74-11e5-8ba4-efff078a60c5.png)

I'm able to reproduce something which might match our original issue via running the [following program](https://gist.github.com/euank/f39e76b7f9ef414c20ea#file-docker_create-go), though it begins having FD issues much more quickly and I haven't yet graphed it to see if the spike is more gradual. the `-sleep` argument can be varied depending on how fast your graphdriver / hardware is.
It can definitely get it into the broken state where the Docker daemon has too many open FDs and can't recover. This was also tested against Docker 1.7.1 using the overlay graphdriver with a much shorter sleep period than the default.

What I'd like out of this is, ideally, for the above underlying issues to be resolved, but rate-limiting calls would also make this state more difficult to get into.
I'd be happy to try and provide more information.

**Comment by crazywen** [comment]
I also met this problem,When I request unceasingly stats api。
it also show the error:
level=error msg="collecting system cpu usage: open /proc/stat: too many open files"

**Comment by LK4D4** [comment]
That looks quite bad, but code changed a lot since.
@euank I wonder if you tried newer version of docker under same load.
@crazywen sadly stats api is very heavy on this stuff :(

**Comment by thaJeztah** [comment]
@euank do you still have this issue on the current release?

**Comment by euank** [comment]
It seems like containerd makes this better. I can't trivially reproduce it and I have no desire to go through the more complicated reproduction I was working with before.

It's not something that impacts me anymore whether it exists or not. Closing...

**Comment by thaJeztah** [comment]
Thank you @euank
