### ISSUE TITLE
Documentation issue: REGISTRY_AUTH missing

### ISSUE THREAD

**Issue by bronger** [docker/docker#15803]
On https://docs.docker.com/registry/deploying/, where "Native basic auth" is explained, the environment variable "REGISTRY_AUTH" is missing, which should be set to "htpasswd".

**Comment by dmp42** [comment]
Thanks @bronger 

This has been fixed already in github: https://github.com/docker/distribution/blob/master/docs/deploying.md#native-basic-auth

Given this is fixed here, I'm going to close that ticket.
That will go into the next major update to the docs site.

Thanks for the report.
