### ISSUE TITLE
Upgrade Remote API Version for Docker

### ISSUE THREAD

**Issue by Priyanky** [docker/docker#15805]
I have a docker version < 1.7.1 . which has the Client API version: 1.18.
I need Client API version: 1.19. Is there a way I can upgrade my APIs alone with newer features (ie upgrade to 1.19) without upgrading the docker itself.
If not can we have this as a feature?

**Comment by calavera** [comment]
Nope. Sorry, but client and server are incompatibles and they'd expect information going back and forward that might or might not be in the json payloads.
