### ISSUE TITLE
invalid parsing of private registry uri in "docker push"

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [docker/docker#15806]
there seems to be a bug in parsing of private registry uri

1) preconditions
* build a local image with tag such as  ```registry/default/ubuntu-15.04```
* setup a private registry running on address ```registry:80```
* run w/o auth: ```DOCKER_OPTS="$DOCKER_OPTS --insecure-registry 192.168.0.0/16"```

2) issue docker command
```
$ docker push registry/default/ubuntu-15.04
```
3) response from docker (in error)
```
The push refers to a repository [docker.io/registry/default/ubuntu-15.04] (len: 1)
6c9d2317bb54: Buffering to Disk 
unauthorized: access to the requested resource is not authorized
```
4) work around
 change the tag to include explicit port, i.e: ```registry:80/default/ubuntu-15.04```
only then dockers understands :-)

5) version information

```
$ uname -a
Linux work3 3.19.0-26-generic #28~14.04.1-Ubuntu SMP Wed Aug 12 14:09:17 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ docker --version
Docker version 1.8.1, build d12ea79
```

```
$ docker info
Containers: 1
Images: 444
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 446
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-26-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 32
Total Memory: 62.81 GiB
Name: work3
ID: FXHO:2SB5:LPMF:MYOR:SL26:GXBM:XH3H:O3PH:BAFZ:3KAS:OPDG:PCEY
WARNING: No swap limit support
```

**Comment by ndelitski** [comment]
Same issue with me, docker 1.8.2. Pull and curl with basic auth work nice, when pushing got `unauthorized: access to the requested resource is not authorized', when toggling off basic auth problem disappears.

**Comment by beni05** [comment]
Thenth,,

**Comment by LK4D4** [comment]
ping @aaronlehmann @stevvooe 
Is this expected? Can we close this?

**Comment by aaronlehmann** [comment]
Docker treats `registry/default/ubuntu-15.04` as an image on the Hub. It only treats the first component as a hostname if it has a `.` or `:` character. It's an unfortunate design choice IMHO.

Unless someone has an idea for how to improve this, maybe we should close this.

**Comment by LK4D4** [comment]
@aaronlehmann That's what I thought. Thanks.
