### ISSUE TITLE
BUG: Docker 1.7.1 unable to start first time with pre configured docker storage option

### ISSUE THREAD

**Issue by riuvshin** [docker/docker#15812]
HI!
I've used to suppress docker warning about loopdevices on centos7 vm by adding 
    --storage-opt dm.no_warn_on_loop_devices=true to docker-storage

docker is unable to start:
    Aug 25 09:00:02 dev docker[23825]: time="2015-08-25T09:00:02+01:00" level=error msg="WARNING: No --storage-opt dm.thinpooldev specified, using loopback; this configuration is strongly discouraged for production use"

It work only if I start docker with no any docker-storage option 1st time, once docker was started with no option it's no more fails when I'm adding docker-storage option.

    docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 8aae715/1.6.0
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 8aae715/1.6.0
OS/Arch (server): linux/amd64

    docker info
Containers: 0
Images: 0
Storage Driver: devicemapper
 Pool Name: docker-253:1-151925074-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 307.2 MB
 Data Space Total: 107.4 GB
 Data Space Available: 43 GB
 Metadata Space Used: 733.2 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Kernel Version: 3.10.0-229.1.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 2.782 GiB
Name: dev.box.com
ID: J6WP:GKWG:BVFK:B47K:6JHQ:F4GL:WS7X:K55X:UVYH:HITZ:VLAG:4EBL

    uname -a
Linux dev.box.com 3.10.0-229.1.2.el7.x86_64 #1 SMP Fri Mar 27 03:04:26 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

    Steps to reproduce
1) install docker 1.7.1
2) add docker storage option into /etc/sysconfig/docker-storage
    DOCKER_STORAGE_OPTIONS = --storage-opt dm.no_warn_on_loop_devices=true
3) service docker start

    IMPORTANT: to reproduce issue do not start docker after installation before adding docket-storage opts.

**Comment by calavera** [comment]
All that mess was fixed with docker 1.8.0. If you install from our repositories, you'll get a dynamically linked binary that works just fine.
