### ISSUE TITLE
Remove API reference docs are not properly sorted in the sidebar

### ISSUE THREAD

**Issue by calavera** [docker/docker#15810]
v1.21 should appear before v1.20:

![image](https://cloud.githubusercontent.com/assets/1050/9464321/4f56bc7a-4b23-11e5-9506-b8a3ead1bba7.png)

/cc @moxiegirl

**Comment by MHBauer** [comment]
asciibetical strikes again. The `weight` can be adjusted, but going forward either going to need to edit a bunch of non-relevant pages each time a new version comes up, or make a big one time adjustment in preparation for the future.

I can make a pr in either case.
