### ISSUE TITLE
docker 1.8.1 `docker logs -f container_name`  runs into unexpected error, always return at once with different results? 

### ISSUE THREAD

**Issue by allencloud** [docker/docker#15815]
`docker version`:
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

`docker info`:
Containers: 110
Images: 15685
Storage Driver: devicemapper
 Pool Name: docker-253:16-24641542-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 330.9 GB
 Data Space Total: 536.9 GB
 Data Space Available: 197.1 GB
 Metadata Space Used: 667.4 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 1.48 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /data/docker/devicemapper/devicemapper/data
 Metadata loop file: /data/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-62-generic
Operating System: Ubuntu 14.04 LTS
CPUs: 2
Total Memory: 11.74 GiB
Name: ubuntu
ID: SDGY:EEUT:QTMG:KODE:AJHB:T7YX:ZB2Z:ZVWP:5BM3:I2VR:GVYK:Y3ON

`uname -a`:
Linux ubuntu 2-Ubuntu SMP Tue Aug 11 14:29:36 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Description of problem:
I am really sorry that I can not reproduce this kind of problem, as in my experiement environment, 2 docker work fine, and 2 failed to run command `docker logs -f container_name`.

Below is my running error display:
```
root@ubuntu:~# docker logs -f 0426992ca9c2
root@ubuntu:~# docker logs -f 0426992ca9c2
root@ubuntu:~# docker logs -f 0426992ca9c2
=> Creating and admin user with a random password in Tomcat
=> Done!
root@ubuntu:~# docker logs -f 0426992ca9c2
=> Creating and admin user with a random password in Tomcat
root@ubuntu:~# docker logs -f 0426992ca9c2
root@ubuntu:~# docker logs -f 0426992ca9c2
=> Creating and admin user with a random password in Tomcat
You have new mail in /var/mail/root
root@ubuntu:~# docker logs -f 0426992ca9c2
root@ubuntu:~# docker logs -f 0426992ca9c2
=> Creating and admin user with a random password in Tomcat
=> Done!
========================================================================
root@ubuntu:~# docker logs -f 0426992ca9c2
=> Creating and admin user with a random password in Tomcat
root@ubuntu:~# docker logs -f 0426992ca9c2
root@ubuntu:~# docker logs -f 0426992ca9c2
root@ubuntu:~# docker logs -f 0426992ca9c2
=> Creating and admin user with a random password in Tomcat
root@ubuntu:~# docker logs -f 0426992ca9c2
root@ubuntu:~# docker logs -f 0426992ca9c2
root@ubuntu:~# docker logs -f 0426992ca9c2
root@ubuntu:~# docker logs -f 0426992ca9c2
```

While command `docker logs -f  0426992ca9c2` should be blocked as the parameter `-f`. However, in my machine it returns at once.
When I ran this command several times, <b>no one will be blocked</b> and <b>return different results</b>.It is definitely a severe BUG.

Below is the actual log json file on the disk:

```
{"log":"=\u003e Creating and admin user with a random password in Tomcat\n","stream":"stdout","time":"2015-08-25T03:52:08.284018814Z"}
{"log":"=\u003e Done!\n","stream":"stdout","time":"2015-08-25T03:52:08.285392692Z"}
{"log":"========================================================================\n","stream":"stdout","time":"2015-08-25T03:52:08.285410189Z"}
{"log":"You can now configure to this Tomcat server using:\n","stream":"stdout","time":"2015-08-25T03:52:08.285417819Z"}
{"log":"\n","stream":"stdout","time":"2015-08-25T03:52:08.285423802Z"}
{"log":"    admin:1W3EIMQmQ89N\n","stream":"stdout","time":"2015-08-25T03:52:08.285429289Z"}
{"log":"\n","stream":"stdout","time":"2015-08-25T03:52:08.285434852Z"}
{"log":"========================================================================\n","stream":"stdout","time":"2015-08-25T03:52:08.285440298Z"}
{"log":"Aug 25, 2015 3:52:28 AM org.apache.catalina.core.AprLifecycleListener init\n","stream":"stderr","time":"2015-08-25T03:52:29.082414705Z"}
{"log":"INFO: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib\n","stream":"stderr","time":"2015-08-25T03:52:29.084458481Z"}
{"log":"Aug 25, 2015 3:52:39 AM org.apache.coyote.AbstractProtocol init\n","stream":"stderr","time":"2015-08-25T03:52:39.601750274Z"}
{"log":"INFO: Initializing ProtocolHandler [\"http-bio-8080\"]\n","stream":"stderr","time":"2015-08-25T03:52:39.601826153Z"}
{"log":"Aug 25, 2015 3:52:40 AM org.apache.coyote.AbstractProtocol init\n","stream":"stderr","time":"2015-08-25T03:52:40.19324596Z"}
{"log":"INFO: Initializing ProtocolHandler [\"ajp-bio-8009\"]\n","stream":"stderr","time":"2015-08-25T03:52:40.193303832Z"}
{"log":"Aug 25, 2015 3:52:40 AM org.apache.catalina.startup.Catalina load\n","stream":"stderr","time":"2015-08-25T03:52:40.23796512Z"}
{"log":"INFO: Initialization processed in 25971 ms\n","stream":"stderr","time":"2015-08-25T03:52:40.238035231Z"}
{"log":"Aug 25, 2015 3:52:41 AM org.apache.catalina.core.StandardService startInternal\n","stream":"stderr","time":"2015-08-25T03:52:41.224497076Z"}
{"log":"INFO: Starting service Catalina\n","stream":"stderr","time":"2015-08-25T03:52:41.224572273Z"}
{"log":"Aug 25, 2015 3:52:41 AM org.apache.catalina.core.StandardEngine startInternal\n","stream":"stderr","time":"2015-08-25T03:52:41.225001973Z"}
{"log":"INFO: Starting Servlet Engine: Apache Tomcat/7.0.55\n","stream":"stderr","time":"2015-08-25T03:52:41.225001973Z"}
{"log":"Aug 25, 2015 3:52:41 AM org.apache.catalina.startup.HostConfig deployDirectory\n","stream":"stderr","time":"2015-08-25T03:52:41.630898209Z"}
``` 

Sorry that I can not reproduce this situation, but I think this issue is really important. What I can provide more is that  It seems that this situation happens on some high load machine, as all docker daemons in my environment are the same, however docker with low load did not run into `docker logs -f` error. 

Allen Sun
DaoCloud

**Comment by mountkin** [comment]
Perhaps your container is frequently restarting? 
The reason that `docker logs -f` isn't blocking may be the state of the container isn't "running" when you run the command.

The scenario can be reproduced by 
`docker run --restart=always -d --name=sleep ubuntu:trusty sh -c "date;sleep 1"`
If you run `docker logs -f` multiple times you'll find that sometimes it's blocking and sometimes it's not blocking.

**Comment by allencloud** [comment]
@mountkin Thanks for your reply. Actually I can make sure I have not set any restart policy. 

And after I typed sentences above, I checked my environment again, it still ran into the problem I described.

Running containers, but it returns immediately when `docker logs -f`.

**Comment by cpuguy83** [comment]
@allencloud Can you check the daemon logs?

**Comment by allencloud** [comment]
@cpuguy83  Yes, Of course. I checked the docker daemon log and found
```
ERRO[97656] Error streaming logs: too many open files
```

And I checked that the amount number of docker daemon's fds is about 1040 ,which is a little abnormal.

I think this error is thrown when docker daemon needs to open the XXX-json.log.
```
latestFile, err := os.Open(pth)
	if err != nil {
		logWatcher.Err <- err
		return
	}
```


And I am wondering what is max fds number of docker daemon.

**Comment by LK4D4** [comment]
@allencloud I think it depends on your ulimit settings.

**Comment by allencloud** [comment]
@LK4D4  It is still strange. Hard limit is 4096 and soft limit is 1024. 

While in another machine with a docker daemon of 880 fds, this issue still occurs.

As the cause of this issue seems to be somewhat explicit , I try to use another machine to check whether this kind of issue can be reproduced.

**Comment by allencloud** [comment]
@mountkin @cpuguy83 @LK4D4  Actually when I was learning the source code of `docker logs`, I found docker daemon uses inotify to deal `-f` parameter which is really reasonable.

However, in my machine, when I use command `tail -f`, it always returns such kind of information:
```
tail: inotify cannot be used, reverting to polling: Too many open files
```

Seems no inotify watch resources.

**Comment by resouer** [comment]
something is eating out your fds in the background, interesting ...

`lsof`, sort the result and find out PID of the bad guy :8ball:

**Comment by cpuguy83** [comment]
We could also support polling (I originally made a file poller to use with this but removed it) if we must.

**Comment by allencloud** [comment]
@cpuguy83  Yes, what you said is reasonable. Now If docker daemon is only using inotify, with high load `docker logs -f`, docker daemon will not work. Under such kind of situation, docker daemon is highly coupled with the kernel inotify setting.

**Comment by allencloud** [comment]
@cpuguy83 Wish docker daemon would support polling again as soon as possible. Thanks.

**Comment by cpuguy83** [comment]
We'll keep this open until there is a fix

**Comment by phemmer** [comment]
Just for my own curiosity, I'd like to understand exactly what is going on behind the scenes here.
From the conversation, it looks like: Docker daemon reads STDOUT/STDERR from the application, and writes it to a file on disk. When a client connects to stream the logs, the Docker daemon opens the log file, and uses inotify so it knows when to read any new data.
Is this correct? If so, both writing the log, and reading the log happen within the same docker daemon. Why not have it so that whatever writes to the log file also just pipes the message into the listener (or at the very least, notifies it that there is data to be read)?

**Comment by cpuguy83** [comment]
@phemmer This is sort of how it used to be, but it complicated broadcastwriter tremendously, as well as the hand-off between old logs-> current logs.
It also made slow log readers adversely affect writing the logs, and notifying on every log write is generally unnecessary overhead.

**Comment by cpuguy83** [comment]
I have a poller in the works, however did not make it for feature cutoff for 1.9.
