### ISSUE TITLE
Windows docker daemon with different behavior for ONBUILD COPY + WORKDIR

### ISSUE THREAD

**Issue by StefanScherer** [docker/docker#15817]
Description of problem:
I'm trying to port the official Linux iojs:onbuild Dockerfile to Windows and found a different behavior at the `ONBUILD COPY` keyword in combination with the `WORKDIR`.

`docker version`:
```
Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   4376380
 Built:        Wed Aug 19 14:59:24 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   4376380
 Built:        Wed Aug 19 14:59:24 UTC 2015
 OS/Arch:      windows/amd64
```

`docker info`:
```
Containers: 37
Images: 89
Storage Driver: windowsfilter
 Windows:
Execution Driver: Windows 1854 1.9.0-dev 4376380
Logging Driver: json-file
Kernel Version: 10.0 10514 (10514.0.amd64fre.th2_release.150808-1529)
Operating System: Windows Server 2016 Technical Preview 3
CPUs: 2
Total Memory: 4 GiB
Name: VAGRANT-2016
ID: 3A6C:S32I:LEC6:YQJB:7PIZ:OK6F:5DEX:X4EI:4SQV:U6MJ:FOTF:W2KN
Debug mode (server): true
File Descriptors: -1
Goroutines: 14
System Time: 2015-08-22T12:59:06.9061205-07:00
EventsListeners: 0
Init SHA1:
Init Path: C:\Windows\System32\docker.exe
Docker Root Dir: C:\ProgramData\docker
```

`uname -a`:
```
MSYS_NT-10.0 vagrant-2016 2.1.0(0.288/5/3) 2015-06-28 18:57 x86_64 Msys
```

Environment details (AWS, VirtualBox, physical, etc.):
Windows 2016 TP3 running in VMware Fusion 7.1.2 on a Mac OSX 10.10.4

How reproducible:

Steps to Reproduce:
1. Clone a sample repo with the Windows version of `iojs` 3.2.0
2. Build the `iojs:lastest` and `iojs:3.2.0` Docker images
3. Build the `iojs:onbuild` Docker image and try to use it.

Here are the exact steps to reproduce it:

```
git clone https://github.com/StefanScherer/dockerfiles-windows
cd dockerfiles-windows\iojs\3.2.0
docker build -t iojs .
docker tag iojs:latest iojs:3.2.0
cd onbuild
docker build -t iojs:onbuild -f Dockerfile.workdir .
cd testapp
docker build -t testapp .
```

The `Dockerfile.workdir` looks very similar to the official Linux iojs:onbuild Dockerfile:

```
FROM iojs:3.2.0

RUN mkdir \app
WORKDIR /app

ONBUILD COPY package.json /app/
ONBUILD RUN npm install
ONBUILD COPY . /app

CMD [ "npm.cmd", "start" ]
```

Actual Results:
Building the testapp Docker image results in an error. It seems that the `ONBUILD COPY package.json /app/` does not copy the file into the `C:\app` directory.

```
npm ERR! package.json ENOENT: no such file or directory, open 'C:\app\package.json'
```

Expected Results:
The fie `package.json` should be copied to `C:\app\package.json`.

Additional info:

So I tried to use a file name as a target inside the container. The following steps reproduce my next workaround:

```
cd ..
docker build -t iojs:onbuild -f Dockerfile.workdir2 .
cd testapp
docker build -t testapp .
```

This `Dockerfile.workdir2` looks like this:

```
FROM iojs:3.2.0

RUN mkdir \app
WORKDIR /app

ONBUILD COPY package.json package.json
ONBUILD RUN npm install
ONBUILD COPY . /app

CMD [ "npm.cmd", "start" ]
```

And now has this line `ONBUILD COPY package.json package.json` which works as the `testapp` Docker image can be built.

But running the container with `docker run -it testapp` shows another error that the file `C:\app\index.js` could not be found.

I have inspected the container with a cmd shell and have seen that the directory from the host is copied into a sub directory `app`:

```
PS C:\Users\vagrant\dockerfiles-windows\iojs\3.2\onbuild\testapp> docker run -it testapp cmd /c dir
 Volume in drive C has no label.
 Volume Serial Number is 0896-CC16

 Directory of C:\app

08/25/2015  06:25 AM    <DIR>          .
08/25/2015  06:25 AM    <DIR>          ..
08/25/2015  06:25 AM    <DIR>          app
08/25/2015  06:24 AM               337 package.json
               1 File(s)            337 bytes
               3 Dir(s)  21,273,026,560 bytes free
```

So I tried another workaround with these steps:

```
cd ..
docker build -t iojs:onbuild -f Dockerfile.workdir3 .
cd testapp
docker build -t testapp .
```

The `Dockerfile.workdir3` looks like this:

```
FROM iojs:3.2.0

RUN mkdir \app
WORKDIR /app

ONBUILD COPY package.json package.json
ONBUILD RUN npm install
ONBUILD COPY . .

CMD [ "npm.cmd", "start" ]
```

With the line `ONBUILD COPY . .` which seems to make it work on Windows.
Running the testapp with `docker run -it testapp` works.

There is a different behavior between the Linux version and the Windows version. Perhaps it is possible to change the behavior so that the Windows version and the Linux version work the same. This would be easier to port other Dockerfiles to Windows.

PS: I also tried this line `ONBUILD COPY package.json .` but this seems to break the workdir completely. 

/cc @jhowardmsft @swernli

**Comment by jhowardmsft** [comment]
#dibs. I'll take a look. I know we haven't done any testing of ONBUILD, and I also know of a few outstanding issues in COPY (both dockerfile and docker cp), so these are probably all related.

**Comment by jhowardmsft** [comment]
So this is interesting. I'm not sure if this is a bug in the Linux implementation, or in Windows. I simplified things to make it as clear as possible.

On Windows, create `\onbuild\Dockerfile` with
`FROM windowsservercore`
`RUN mkdir \app`
`WORKDIR /app`
`ONBUILD copy file.txt /app/`

On Linux, create `/onbuild/Dockerfile` with
`FROM Ubuntu`
`RUN mkdir /app`
`WORKDIR /app`
`ONBUILD copy file.txt /app/`

Then run `docker build -t ob /onbuild` (`\onbuild` on Windows)

Next, create a subdirectory \onbuild\step2. Add file.txt to that directory containing anything. Also in that directory, create a Dockerfile containing the following

`FROM ob`

Now build step2:` docker build -t ob2 \onbuild\step2` (forward slashes for the Linux version). This will do the copy.

Finally get to a shell inside the ob2 image. `docker run -it --rm ob2 cmd` (sh on Linux) and examine the contents of the \app directory.

On Linux: /app/file.txt is present.
On Windows: /app/app/file.txt is present.

Which is correct? I would somewhat argue Windows is as the first Dockerfile changes the working directory to /app/, and `ONBUILD copy file.txt /app/` is doing exactly what COPY file.txt /app/ would do - copy to WORKDIR/app/file.txt, or /app/app/file.txt

So the question is, should a WORKDIR be preserved on Linux for a subsequent ONBUILD?

**Comment by jhowardmsft** [comment]
Ah nevermind, I see the problem. It's because in `ONBUILD copy file.txt /app/`, `/app/` IS an absolute path in Linux, but from the golang definition of filepath.IsAbs() on Windows, `/app/` is NOT an absolute path in Windows (and technically this is correct). However, as we can't specify drive letters in Windows here, I did a very similar fix in Windows earlier today. Will submit a PR to fix this shortly.

**Comment by jhowardmsft** [comment]
Yeah, this looks better :)

E:\go\src\github.com\StefanScherer\dockerfiles-windows\iojs\3.2>docker build -t iojs .
Sending build context to Docker daemon 11.26 kB
Step 1 : FROM windowsservercore
 ---> db7790e174dd
Step 2 : ENV NPM_CONFIG_LOGLEVEL info
 ---> Running in 267b3a171d10
Removing intermediate container 267b3a171d10
Step 3 : ENV IOJS_VERSION 3.2.0
 ---> Running in 77d4693dc08c
 ---> c0d20ee9c41f
Removing intermediate container 77d4693dc08c
Step 4 : RUN powershell -Command "wget -Uri https://iojs.org/dist/v%IOJS_VERSION%/iojs-v%IOJS_VERSION%-x64.msi -OutFile iojs.msi -UseBasicParsing"
 ---> Running in 1035ba8e8892
 ---> 2fe2f3121376
Removing intermediate container 1035ba8e8892
Step 5 : RUN msiexec.exe /q /i iojs.msi
 ---> Running in e91f610a09f7
 ---> 112da643232c
Removing intermediate container e91f610a09f7
Step 6 : CMD iojs
 ---> Running in a006a60e165a
 ---> 8435eb07410c
Removing intermediate container a006a60e165a
Successfully built 8435eb07410c

E:\go\src\github.com\StefanScherer\dockerfiles-windows\iojs\3.2>docker tag iojs:latest iojs:3.2.0

E:\go\src\github.com\StefanScherer\dockerfiles-windows\iojs\3.2>cd onbuild

E:\go\src\github.com\StefanScherer\dockerfiles-windows\iojs\3.2\onbuild>docker build -t iojs:onbuild -f Dockerfile.workdir .
Sending build context to Docker daemon 9.728 kB
Step 1 : FROM iojs:3.2.0
 ---> 8435eb07410c
Step 2 : RUN mkdir \app
 ---> Running in 73d1934b9a96
 ---> 8bbe26f1d53f
Removing intermediate container 73d1934b9a96
Step 3 : WORKDIR /app
 ---> Running in 230941d62054
 ---> f014d270686a
Removing intermediate container 230941d62054
Step 4 : ONBUILD copy package.json /app/
 ---> Running in 04d318d81a18
 ---> 8f71c697ec82
Removing intermediate container 04d318d81a18
Step 5 : ONBUILD run npm install
 ---> Running in b3ed70772777
 ---> 28c71481e748
Removing intermediate container b3ed70772777
Step 6 : ONBUILD copy . /app
 ---> Running in 58c048f360ab
 ---> 0e309c91f2dd
Removing intermediate container 58c048f360ab
Step 7 : CMD npm.cmd start
 ---> Running in e43d6234e753
 ---> 795b1218e291
Removing intermediate container e43d6234e753
Successfully built 795b1218e291

E:\go\src\github.com\StefanScherer\dockerfiles-windows\iojs\3.2\onbuild>cd testapp

E:\go\src\github.com\StefanScherer\dockerfiles-windows\iojs\3.2\onbuild\testapp>docker build -t testapp .
Sending build context to Docker daemon  5.12 kB
Step 1 : FROM iojs:onbuild
# Executing 3 build triggers
Trigger 0, COPY package.json /app/
Step 1 : COPY package.json /app/
Trigger 1, RUN npm install
Step 1 : RUN npm install
 ---> Running in bdab995c2866
npm info it worked if it ends with ok
npm info using npm@2.13.3
npm info using node@v3.2.0
npm WARN package.json testapp@0.0.1 No repository field.
npm WARN package.json testapp@0.0.1 No README data
npm info preinstall testapp@0.0.1
npm info build C:\app
npm info linkStuff testapp@0.0.1
npm info install testapp@0.0.1
npm info postinstall testapp@0.0.1
npm info prepublish testapp@0.0.1
npm info ok
Trigger 2, COPY . /app
Step 1 : COPY . /app
 ---> 792188feb5c7
Removing intermediate container 9eff921c7252
Removing intermediate container e1a7eaf146d5
Removing intermediate container bdab995c2866
Successfully built 792188feb5c7
