### ISSUE TITLE
building docker-development container fails: Failed to fetch http://archive.ubuntu.com/.../Sources

### ISSUE THREAD

**Issue by Snorch** [docker/docker#15813]
on Fedora 20, Centos 7; docker v1.7.1, v1.8.1 one can not run tests:

there is no file http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/source/Sources in http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/source/, but only Release, Sources.bz2, Sources.gz

test log:
sudo make test-unit
docker build -t "docker-dev:HEAD" .
Sending build context to Docker daemon 153.3 MB
Sending build context to Docker daemon 
Step 0 : FROM ubuntu:14.04
 ---> d0955f21bf24
Step 1 : MAINTAINER Tianon Gravi <admwiggin@gmail.com> (@tianon)
 ---> Using cache
 ---> 4a635bdb3d31
Step 2 : RUN apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61
 ---> Using cache
 ---> 09f22c94cba4
Step 3 : RUN echo deb http://ppa.launchpad.net/zfs-native/stable/ubuntu trusty main > /etc/apt/sources.list.d/zfs.list
 ---> Using cache
 ---> 21bf5c022806
Step 4 : RUN apt-get update && apt-get install -y 	apparmor 	aufs-tools 	automake 	bash-completion 	btrfs-tools 	build-essential 	curl 	dpkg-sig 	git 	iptables 	libapparmor-dev 	libcap-dev 	libsqlite3-dev 	mercurial 	parallel 	python-mock 	python-pip python-websocket 	reprepro 	ruby1.9.1 	ruby1.9.1-dev 	s3cmd=1.1.0* 	ubuntu-zfs 	libzfs-dev 	--no-install-recommends
 ---> Running in 7b903da0d77b
Ign http://ppa.launchpad.net trusty InRelease
Ign http://archive.ubuntu.com trusty InRelease
Ign http://archive.ubuntu.com trusty-updates InRelease
Get:1 http://ppa.launchpad.net trusty Release.gpg [316 B]
Ign http://archive.ubuntu.com trusty-security InRelease
Hit http://archive.ubuntu.com trusty Release.gpg
Get:2 http://archive.ubuntu.com trusty-updates Release.gpg [933 B]
Get:3 http://archive.ubuntu.com trusty-security Release.gpg [933 B]
Hit http://archive.ubuntu.com trusty Release
Get:4 http://archive.ubuntu.com trusty-updates Release [63.5 kB]
Get:5 http://ppa.launchpad.net trusty Release [15.1 kB]
Get:6 http://archive.ubuntu.com trusty-security Release [63.5 kB]
Get:7 http://archive.ubuntu.com trusty/main Sources [1335 kB]
Get:8 http://archive.ubuntu.com trusty/restricted Sources [5335 B]
Get:9 http://archive.ubuntu.com trusty/universe Sources [7926 kB]
Get:10 http://archive.ubuntu.com trusty/main amd64 Packages [1743 kB]
Get:11 http://archive.ubuntu.com trusty/restricted amd64 Packages [16.0 kB]
Get:12 http://archive.ubuntu.com trusty/universe amd64 Packages [7589 kB]
Get:13 http://ppa.launchpad.net trusty/main amd64 Packages [5158 B]
Get:14 http://archive.ubuntu.com trusty-updates/main Sources [286 kB]
Get:15 http://archive.ubuntu.com trusty-updates/restricted Sources [4524 B]
Get:16 http://archive.ubuntu.com trusty-updates/universe Sources [165 kB]
Get:17 http://archive.ubuntu.com trusty-updates/main amd64 Packages [755 kB]
Get:18 http://archive.ubuntu.com trusty-updates/restricted amd64 Packages [22.7 kB]
Get:19 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [401 kB]
Get:20 http://archive.ubuntu.com trusty-security/main Sources [114 kB]
Get:21 http://archive.ubuntu.com trusty-security/restricted Sources [1874 B]
Get:22 http://archive.ubuntu.com trusty-security/universe Sources [33.5 kB]
Get:23 http://archive.ubuntu.com trusty-security/main amd64 Packages [411 kB]
Get:24 http://archive.ubuntu.com trusty-security/restricted amd64 Packages [14.8 kB]
Get:25 http://archive.ubuntu.com trusty-security/universe amd64 Packages [146 kB]
Fetched 21.1 MB in 3s (6790 kB/s)
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/source/Sources  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/universe/source/Sources  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/universe/binary-amd64/Packages  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
INFO[0007] The command [/bin/sh -c apt-get update && apt-get install -y 	apparmor 	aufs-tools automake 	bash-completion 	btrfs-tools 	build-essential 	curl 	dpkg-sig 	git iptables 	libapparmor-dev 	libcap-dev 	libsqlite3-dev 	mercurial 	parallel 	python-mock 	python-pip 	python-websocket 	reprepro 	ruby1.9.1 	ruby1.9.1-dev 	s3cmd=1.1.0* 	ubuntu-zfs 	libzfs-dev 	--no-install-recommends] returned a non-zero code: 100 
make: *** [build] Error 1

**Comment by Snorch** [comment]
That was a problem with local network proxy, as after cache for archive.ubuntu.com was dropped all worked well.

**Comment by thaJeztah** [comment]
thanks for reporting back!
