### ISSUE TITLE
Proposal: Add container/image labels to logging driver output

### ISSUE THREAD

**Issue by dpgeekzero** [docker/docker#15816]
I'm using the new fluentd logging driver in my environment.  It would be great to have the labels that are attached to my container included in the data that goes to fluentd.

**Comment by xealot** [comment]
OMG YES. I was just looking for this :+1:

**Comment by tdterry** [comment]
Absolutely. We use labels to link containers to our own internal data. I imagine passing these along would be very useful for other drivers too.

**Comment by dqminh** [comment]
+1 for this

We have a patch that adding this for gelf, but it should be easy to add the same to fluentd and journald as well. Going to send this soon.
