### ISSUE TITLE
gordon should not ask for uname

### ISSUE THREAD

**Issue by phemmer** [docker/docker#15820]
Every time someone creates an issue, gordon asks for `uname -a` output. This should not be necessary.
Either:
1. This output should be included in `docker info` (golang is capable of making the syscall to get this info: https://golang.org/pkg/syscall/#Uname)
2. This shouldn't be provided at all. `docker info` (and `docker version`) already includes the kernel version. What is it we're looking for from `uname -a`?

**Comment by thaJeztah** [comment]
Unfortunately, older versions of Docker didn't report this as part of docker info, so that's why it's still there.

We just need to decide when the times right to remove it from Gordon

**Comment by phemmer** [comment]
Gordon should be smart enough to see it in the `docker info` / `docker version` output.
I image gordon is just regexing through the issue description, just need to tweak the regex (or add a fallback secondary regex).

**Comment by thaJeztah** [comment]
@phemmer I'm absolutely +1 if this could be improved, and Gordon is made smarter. If you have ideas on improving this; Gordon can be found in in this repository; https://github.com/docker/leeroy

The code is quite simple, and this particular "detection" can be found here; https://github.com/docker/leeroy/blob/master/github/issue.go#L22
