### ISSUE TITLE
Ubuntu install steps - still necessary to install linux-image-extra-virtual?

### ISSUE THREAD

**Issue by dockermikeg** [docker/docker#15825]
The Docker engine install steps on Ubuntu include a step to install linux-image-(uname -r), followed by a step to reboot the system.  (see: https://github.com/docker/docker/blob/master/docs/installation/ubuntulinux.md)

However, the Docker install script (https://github.com/docker/docker/blob/master/hack/install.sh) automatically performs this step.

Can we remove the instructions to manually install linux-image-* and to reboot?

**Comment by programmerq** [comment]
The doc at https://github.com/docker/docker/blob/master/docs/installation/ubuntulinux.md talks about installing the necessary kernel package (linux-image-*) for versions of ubuntu that are old enough to not have a new enough kernel by default.

The script at https://github.com/docker/docker/blob/master/hack/install.sh doesn't install a whole kernel for you. It installs an extras package (linux-image-extras-*) to enable aufs support. The extras package pretty much has modules that aren't in the core kernel package.
 
+kind/docs +exp/beginner

**Comment by LK4D4** [comment]
ping @thaJeztah

**Comment by thaJeztah** [comment]
The installation procedure in the docs is the manual installation, so these steps are required if you're not using the install script.

As far as I can see the docs are correct, so I'm closing this issue.
