### ISSUE TITLE
Proposal: extension mechanism for plugin/drivers

### ISSUE THREAD

**Issue by dqminh** [docker/docker#15829]
Currently, plugins (external and internal) talk to docker via a known common interface, for example 
[libnetwork remote design](https://github.com/docker/libnetwork/blob/master/docs/remote.md) and [libnetwork api design](https://github.com/docker/libnetwork/blob/master/docs/design.md#api)

One of the problem i want to solve is https://github.com/docker/docker/issues/6574, specifically https://github.com/docker/docker/issues/6574#issuecomment-134198175. To summarize the problem:
- Our systems run iptables-restore frequently agains a set of known rules
- Whenever iptables-restore is run, docker loses its own iptables rules
- We want the iptables rules to be recreated without restarting lots of containers on the host

To do this, there are two ways i can think of:
1. Expose an additional API to the common interface that drivers can choose to implement ( i.e. bridge driver can use it to reset iptables, rewrite proc values etc.. ). However this may not be approriate for all drivers. So we probably want to decide how a drivers can update / refresh their own settings.
2. Allow some sort of extension mechanisms for plugins / drivers so they can register their own hooks, and that is exposed to Docker user. For example, bridge may want to register an API to refresh iptables settings, proc values etc. while remote plugins can also register their own extension.

Some diccussion on IRC: https://botbot.me/freenode/docker-network/2015-08-25/?msg=48091484&page=1

cc @mavenugo @mrjana

**Comment by gdm85** [comment]
@dqminh give a look to the approach I used in [docker-fw](https://github.com/gdm85/docker-fw) to solve a similar class of problems, maybe you can get some ideas from there too

**Comment by dqminh** [comment]
ping @mrjana @mavenugo for comments

**Comment by mavenugo** [comment]
@dqminh as discussed in IRC, a wrapper plugin that provides pre and post hooks on top of any existing plugin will solve the problem.
Also @ibuildthecloud had a similar request. I think, we can do this without any plugin api changes. Rather, all we need is a wrapper plugin which can provide augmentation calls to an extension plugin during pre or post operation performed by the base plugin (that is being extended here).
Pls submit a PR in libnetwork project.

**Comment by dqminh** [comment]
@mavenugo looking. I wasnt aware of the wrapper plugin idea. Are you talking about https://botbot.me/freenode/docker-network/2015-09-30/?msg=50810019&page=1 ?

**Comment by mavenugo** [comment]
@dqminh thats correct. will that approach work for you ?

**Comment by thaJeztah** [comment]
what's the status here?

**Comment by calavera** [comment]
Closing per Madhu's comments.
