### ISSUE TITLE
Docker on EL7 with systemd doesn't load sysconfig files on startup

### ISSUE THREAD

**Issue by Djelibeybi** [docker/docker#15839]
Description of problem:

Docker 1.8.1 installed via docker-engine-1.8.1-1.el7.rpm doesn't load configuration from `/etc/sysconfig/docker-*` so it is not possible to set daemon configuration via standard EL configuration methods. 

`docker version`:

1.8.1-1

`docker info`:

    Containers: 0
    Images: 3
    Storage Driver: btrfs
     Build Version: Btrfs v3.16.2
     Library Version: 101
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 3.8.13-98.1.2.el7uek.x86_64
    Operating System: Oracle Linux Server 7.1
    CPUs: 4
    Total Memory: 1.704 GiB
    Name: dockerx7.lot209.com
    ID: 7RTZ:PVFL:2KES:YFLP:WRVL:FHTC:7UJR:VKN5:O2RB:UXWA:XAMR:EW4L
    Username: avmiller
    Registry: https://index.docker.io/v1/

`uname -a`:

`Linux dockerx7.lot209.com 3.8.13-98.1.2.el7uek.x86_64 #2 SMP Thu Aug 13 12:21:30 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux`

Environment details (AWS, VirtualBox, physical, etc.):

VirtualBox

How reproducible:

100%

Steps to Reproduce:
1. Install an EL7-based distro (RHEL7, CentOS7, OL7)
2. Install docker-engine-1.8.1-1.el7.rpm
3. Set a proxy in /etc/sysconfig/docker (note the file doesn't even exist on a fresh install)
4. Start the docker daemon via systemctl start docker

Actual Results:

Docker daemon has no proxy configured because it doesn't read the `/etc/sysconfig/docker-*` files.

Expected Results:

Docker daemon works via proxy.

Additional info:

Setting daemon configuration via `/etc/sysconfig` is still the preferred method even on EL7-based distros. Docker should provide and support setting configuration via these files.

I am preparing a pull request that restores the `/etc/sysconfig/docker-*` configuration files and updates the systemd startup control file accordingly.

**Comment by jfrazelle** [comment]
we have gotten a ton of PRs for this I have updated the docs and if you want to see why checkout https://github.com/docker/docker/pull/14513#issuecomment-125009350 and all the threads pointing to it sorry

**Comment by thaJeztah** [comment]
@Djelibeybi please read these docs before submitting, https://docs.docker.com/articles/systemd/#custom-docker-daemon-options

Several PRs were created and rejected, because using drop-ins to override options is the preferred way, and allows you to do this (see the linked docs)

**Comment by thaJeztah** [comment]
cr*p, sorry for the double comment, GitHub cache got me..

**Comment by thaJeztah** [comment]
I'll close this issue for the reasons given above, but feel free to comment here after its closed :+1:

**Comment by Djelibeybi** [comment]
You'd think with all the issues and PRs raised that this is a contentious change. Keep in mind that all distro-provided RPMs on EL7-based distros still use `/etc/sysconfig/` for their configuration, even with systemd. 

So, while this is probably the right long-term method, it's going to be something that will affect lots and lots of users, particularly those who upgrade from distro-provided previous docker RPMs.

In fact, I'm not sure why both solutions can't be used simultaneously for the life of the EL7 distros, i.e. the default systemd service file should still load any existing EnvironmentFiles so that configuration is maintained. However, the documentation can state that this method is deprecated and the preferred method is systemd drop-in files.

I get that Docker is a rapidly moving product, but this kind of change makes life challenging for large environment sysadmins that really shouldn't have to troubleshoot why a version upgrade of an RPM has just caused startup failures.

But, at the end of the day, it's your call and we will adjust accordingly. I have already notified our documentation team to call out this change in our documentation.
