### ISSUE TITLE
Dead link to introduction in docs

### ISSUE THREAD

**Issue by rsmitty** [docker/docker#15835]
There's a dead link in the very first linke userguide that reads "In the **Introduction** you got a taste of what Docker is...". The "Introduction" text is supposed to point to (I believe) the "About Docker" page [here](https://docs.docker.com/misc/).

I have already updated the docs to fix this bug and will submit a pull request shortly

**Comment by vdemeester** [comment]
@thaJeztah This one can be closed (PR sent and merged :wink:)
