### ISSUE TITLE
Proposal: blacklist/whitelist ip sets on daemon and container level

### ISSUE THREAD

**Issue by dqminh** [docker/docker#15830]
Problems:
- we want our containers to only receive traffic from known ip sets
- we have services that should only reach out to external services and not internal services

Currently doing these things outside of docker is very clunky. It would be nice if daemon and containers can accept `--allow-ipset` and `--reject-ipset` and insert proper rules into iptables instead of end user having to manage these rules outside of docker.

**Comment by ajaali** [comment]
bump

**Comment by Pirabarlen-Cheenaramen** [comment]
Hi, I am currently giving this issue a shot, and so far, here's I am, am writing an ipset layer first, once that is done, i adding those helpers should be easy.

If you have any feedbacks [good or bad], I will be most pleased to hear them out, it will help me out getting the details right. 


Thanks

**Comment by thaJeztah** [comment]
I'm not sure this would fit the scope of what docker does, and would be replicating what a firewall does. At this point, we don't think we should implement this, but we can reconsider if there's a lot of interest
