### ISSUE TITLE
Dead link in Understanding Docker in About Docker section

### ISSUE THREAD

**Issue by rsmitty** [docker/docker#15837]
The link in the About Docker page under "About this Guide" header 404s trying to find the understanding-docker.md file. It's just an incorrect path, as that guide no longer exists under /misc/introduction, it's simply under /introduction now. I'll update this one with a PR shortly.

**Comment by vdemeester** [comment]
@thaJeztah This one should be closed too (PR sent and merged :wink:).

**Comment by runcom** [comment]
Thanks @vdemeester
