### ISSUE TITLE
Image not working as expected after transfer to another host

### ISSUE THREAD

**Issue by martein** [docker/docker#15844]
Hello,
I managed to create my own image based on opensuse, installed and configured there a bunch of stuff I need for my project testing. Then I found a primary home for my docker host and started to transfer there. I used the docker save command to export the image and then loaded it on the new host with docker load. After the import my container started to fail with the following problem - no single linux service was present. Every time I execute lets say 
> service cron restart 

from within the container I get 
> cron is neither service nor target!?

I dug a little more into the internals of /sbin/service and found that in the container on the old host /sys/fs/cgroup/systemd is not present, but it is indeed on the new one. That's why the service script is going in the wrong direction. I also saw that during the time I created my stuff docker changed versions. On the old host I have:
> Client version: 1.7.0
> Client API version: 1.19
> Go version (client): go1.4.2
> Git commit (client): 0baf609

and on the new one:
> Version:      1.8.1
> API version:  1.20
> Go version:   go1.4.2
> Git commit:   d12ea79

The OS on the both hosts is Ubuntu 14.04 LTS.
Reverting to Docker 1.7.0 on the new host fixed the issue.
Is this behavior inconsistency expected or the newer version required more configuration that I missed?

Regards.

**Comment by LK4D4** [comment]
This is a quite old issue. There was probably a bug with an upgrade to the version where cgroups became mounted by default. Now it's too late to do anything :(
