### ISSUE TITLE
Leaking mounted netns

### ISSUE THREAD

**Issue by LK4D4** [docker/docker#15857]
After killing daemon with -9 with running contianer and starting again I see records in mounts:
```
nsfs on /var/run/docker/netns/44ba3ad8c973 type nsfs (rw)
```
and they never disappear. I don't remember where we finished last time, but for other resources as graphdriver mounts we cleaning all up on daemon start. Also if I start container and then remove it - netns disappear, but if just remove stopped - it will be there forever.

**Comment by LK4D4** [comment]
This is still an issue.

**Comment by vdemeester** [comment]
@LK4D4 @thaJeztah should this be in 1.10 ?

**Comment by thaJeztah** [comment]
@vdemeester not sure, it's not a bug/regression that's introduced in 1.9. We probably should give it some attention though.

**Comment by LK4D4** [comment]
This is fixed.
