### ISSUE TITLE
RPM  docker-engine-1.X for RHEL distro includes bad systemd service

### ISSUE THREAD

**Issue by dvdred** [docker/docker#15856]
In the systemd service (/usr/lib/systemd/system/docker.service) there isn't the inclusion of environment file. To make the script working in the correct manner it is needed to change also the exec start statement, like in the following example:

<pre>
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target docker.socket
Requires=docker.socket

[Service]
Type=notify
EnvironmentFile=-/etc/sysconfig/docker
ExecStart=/usr/bin/docker daemon -H fd:// $OPTIONS
MountFlags=slave
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity

[Install]
WantedBy=multi-user.target

**Comment by phemmer** [comment]
This comes up all the time. I'd take a look at https://github.com/docker/docker/pull/14513
The docs have been updated to cover setting daemon options when using systemd: https://docs.docker.com/articles/systemd/#custom-docker-daemon-options

**Comment by dvdred** [comment]
Ok, i understand that there is a strategy to put all the configurations in systemd service file... But, imho, for packages specifically oriented to servers (like centos) there is not so much urgency. There are people like me using external tool to manage servers, like puppet or chef. Classes developed to install and configure softwares, like docker daemon, needs time to be updated to parse and populate new configuration files. It is frustrating when a deploy fails for a so simple but enormous change like this. Continuity is a main objective for enterprise distros.

Maybe could be possible to include a postinstallation script in the rpm to read the legacy configuration file, if exists, and populate the systemd service file? Upgrades will thank you!

**Comment by phemmer** [comment]
Not to rub the wrong way, but:
1. If stability is really a big concern, you should be using the packages from the distribution's repositories, not from the upstream project (docker).
2. Package upgrades should get rolled out to development environments first. Any issues such as dropping support for `/etc/systemctl/foo` would be picked up there.
3. Support has to be dropped eventually. If `/etc/systemctl/foo` support were dropped a year from now, the same problems would have arisen then. Support would have disappeared, and people would come complaining asking to put it back, asking for more time. Rinse, repeat.

The fine print: this is just my opinion, and I am in no way associated with the docker project.

**Comment by dvdred** [comment]
Ok, thank you for the reply.
The rpm contains the word "el7", and for my idiot point of view it means should be compatible with rhel/centos7, or not?
The problem is not so big. I am using a test environment, where i need compose and recent updates of docker daemon. I thought that during upgrades would be a good idea to preserve legacy options, if present, to a drop in systemd file, and I'm only suggesting this.
Doing so will reduce the time "from dev to prod" and make possible to change "configuration philosophy (<b>\<sarcastic\> seghe mentali! \</sarcastic\></b>)" in transparent way to automatic management tool that installs and configure servers.
Of course, in production, i will wait for the upgrade of distribution's package because they are more conservative, but implementing a way to reduce contrast for the two environment should exist, or not? Both teams (docker's and distro's) will benefit from that, and i think is necessary to support legacy configuration, at least in the <i>same major version</i> of distro.
Anyway i close this issue cause a possible manual solution is very well documented in the link of previous comment.

**Comment by phemmer** [comment]
> The rpm contains the word "el7", and for my idiot point of view it means should be compatible with rhel/centos7, or not?

It means the package is compatible with rhel/centos/sl/etc yes. But compatible doesn't mean equivalent to the distro packages. It just means that the package will work.

> I thought that during upgrades would be a good idea to preserve legacy options, if present, to a drop in systemd file, and I'm only suggesting this.

The problem with something like this, is there's no good way to say "hey, stop using this feature". The only way would be to put it in the docs. And as long as a feature works, people aren't going to notice something in the docs which say to stop using it. They'll keep using it until it stops working, then go read the docs (I hope :-P) to figure out why.

> i think is necessary to support legacy configuration, at least in the same major version of distro.

And distro packages do this. This is why redhat doesn't often push a new version of a package that isn't a bug fix, and why they backport fixes to package versions upstream doesn't officially support any more.
The docker organization is simply providing the latest and greatest package for those who do want packages newer than what the distro provides.

> Anyway i close this issue cause a possible manual solution is very well documented in the link of previous comment.

You don't have to close it. Present a strong argument, and the docker team might change their mind, or come up with some way to compromise.
