### ISSUE TITLE
pull error: error copying from layer download progress reader: download cancelled

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#15854]
A user reported the error message: `error copying from layer download progress reader: download cancelled` while attempting a pull.

This is a horrible error message as it has nothing to do with copying download progress and seems to be that there is an issue actually pulling the image/layer.

This error is produced @ https://github.com/docker/docker/blob/v1.8.1/graph/pull_v2.go#L225
Which comes from the defer beneath it: https://github.com/docker/docker/blob/v1.8.1/graph/pull_v2.go#L228-L236

It seems that any error produced by this function is being masked (as far as the user can see) the `errors.New` call. The real error should be visible in some way to the user.

**Comment by aaronlehmann** [comment]
This bad error message is being removed by https://github.com/docker/docker/pull/15955

We may need some additional work to expose a useful error message.

**Comment by jmzwcn** [comment]
this issue has been gone? Seems graph dir is missing...

**Comment by aaronlehmann** [comment]
Yes, I think this has since been fixed. The error message should now pass through the network-level error that caused the pull to fail.

@cpuguy83: OK to close?
