### ISSUE TITLE
Incomplete /lib/systemd/system/docker.service file on fedora 22

### ISSUE THREAD

**Issue by aanm** [docker/docker#15859]
I fresh installed docker using `get.docker.com | sh` on fedora 22 and I see that the contents of this file are incomplete:
```
$ cat /lib/systemd/system/docker.service
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target docker.socket
Requires=docker.socket

[Service]
Type=notify
ExecStart=/usr/bin/docker daemon -H fd://
MountFlags=slave
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity

[Install]
WantedBy=multi-user.target
```
since there's also a file created under `/etc/sysconfig/docker`
```
$  cat /etc/sysconfig/docker 
# /etc/sysconfig/docker
#
# Other arguments to pass to the docker daemon process
# These will be parsed by the sysv initscript and appended
# to the arguments list passed to docker daemon

other_args=""
```
The content of `docker.service` should have the `EnvironmentFile` set to `/etc/sysconfig/docker`
```
$ cat /lib/systemd/system/docker.service
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target docker.socket
Requires=docker.socket

[Service]
EnvironmentFile=-/etc/sysconfig/docker
EnvironmentFile=-/etc/sysconfig/docker-storage
EnvironmentFile=-/etc/sysconfig/docker-network
Type=notify
ExecStart=/usr/bin/docker daemon -H fd:// $other_args
MountFlags=slave
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity

[Install]
WantedBy=multi-user.target
```

```
$ docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:39:27 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:39:27 UTC 2015
 OS/Arch:      linux/amd64
$ uname -a
Linux localhost.localdomain 4.1.5-200.fc22.x86_64 #1 SMP Mon Aug 10 23:38:23 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by vbatts** [comment]
ping @lsm5

**Comment by phemmer** [comment]
This comes up all the time. I'd take a look at https://github.com/docker/docker/pull/14513
The docs have been updated to cover setting daemon options when using systemd: https://docs.docker.com/articles/systemd/#custom-docker-daemon-options

**Comment by aanm** [comment]
@phemmer Then either remove `/etc/sysconfig/docker` file from the installation or make the option available inside `/lib/systemd/system/docker.service`

**Comment by phemmer** [comment]
The file is there for the sysvinit script.
Now if your proposal is to remove sysvinit support from the fedora-22 rpm, that I might agree with. Thought it might be better to start a new issue.

**Comment by andybalaam** [comment]
As I understand it, to modify command line options to the docker daemon under systemd, you have to override the ExecStart property, which seems overly tricky to me compared with the situation under sysvinit (where you only needed to supply a DOCKER_OPTS environment variable).

I wrote up how I did it here: http://www.artificialworlds.net/blog/2015/08/27/changing-the-docker-daemon-options-in-systemd-on-ubuntu-15-04/

If there is an easier way, please let me know.

If the default ExecStart property included "$DOCKER_OPTS" or similar, we could just drop in a config with with an Environment line and it would be quite straightforward.

**Comment by andybalaam** [comment]
I see now that all this was discussed under issue #14513.  I'd still suggest the docs need improving to specify systemd command that is needed to create your own custom config that overrides ExecStart.

**Comment by thaJeztah** [comment]
@andybalaam could you explain what's you think is missing in the example/docs provided here; https://docs.docker.com/articles/systemd/#custom-docker-daemon-options. I think that example describes how to override the ExecCommand

**Comment by mc0e** [comment]
Maybe there should be a comment in `/etc/sysconfig/docker` to the effect that this is for `sysvinit` use only, and referring to info on how to do it for `systemd`?

**Comment by thaJeztah** [comment]
@mc0e hm, could help; just as in https://github.com/docker/docker/blob/master/contrib/init/sysvinit-debian/docker.default#L1 you mean?

**Comment by mc0e** [comment]
Maybe not quite explicit enough.  Something like:

    # This configuration file is used by /etc/init.d/docker.  For systemd configuration see http://....

**Comment by phemmer** [comment]
I believe it has been proposed before, but it would be cleaner to not put sysvinit files on systems which don't use sysvinit, such as fedora 22.
Are there even any supported rpm distros using sysvinit? Rehl7 I would imagine is the oldest supported, and it uses systems.


-------- Original Message --------

**Comment by thaJeztah** [comment]
@phemmer IIRC some changes were already made to not include those files in SystemD installs. Will check

**Comment by thaJeztah** [comment]
Looks like it's only installed on SystemD systems now: https://github.com/docker/docker/blob/729c9a97822ebee2c978a322d37060454af6bc66/hack/make/.build-rpm/docker-engine.spec#L132-L139

**Comment by thaJeztah** [comment]
@aanm I'm closing this issue, following the discussion above, but please comment here if you think I closed this by mistake
