### ISSUE TITLE
Multi-arch support for docker daemon registry interface

### ISSUE THREAD

**Issue by estesp** [docker/docker#15866]
This issue will be used as a synchronization point between **docker/distribution** PRs and core Docker changes required to implement the multi-architecture support between registry schema changes (to enable tagging with information like `arch` and `os`) and smart parsing of fat manifests on the daemon side during pull.

Also, a design for fat manifest creation (which may need to be different than basic `docker push`) will be discussed here, and, as needed, PRs will be created to implement these capabilities.

**References**
 - https://github.com/docker/distribution/pull/62 - *proposal for new generic content schema for registry v2; rework by @stevvooe TBD*
 - https://github.com/docker/distribution/issues/200 - *specific issue to collect multi-arch requirements/discussion on* **docker/distribution** *repo*

**Completed work**
 - https://github.com/docker/distribution/pull/912 - *moves current schema to specific versioned package to make schema2 implementation work possible*

**Comment by icecrime** [comment]
@estesp Is there anything remaining for this issue with Engine 1.10 shipped and fat manifest support?

**Comment by estesp** [comment]
I'll close @icecrime as I think we don't need a "collector" issue anymore as all the various base PRs went in without even being tracked through this issue anyway :eyes: :)  The last bits are fine to handle post-1.10 in their own PRs

**Comment by bradrydzewski** [comment]
@icecrime @estesp wondering if there is an issue I can subscribe to, or any information you can provide regarding when the registry will take platform / architecture into account for pulling and pushing images? Or does it already do this now? 

Specifically when I can do something like `docker pull foo:latest` from arm and `docker pull foo:latest` from amd64 (same image name and tag) and the registry will return the appropriate image for the host machines architecture

Thanks!

**Comment by estesp** [comment]
The pull side has an initial implementation here (which made it into Docker 1.10): https://github.com/docker/docker/blob/master/distribution/pull_v2.go#L602-L622

As the note from @aaronlehmann shows, there is additional work to handle the richer **platform** construct that exists in the schema2 definition of a "[manifest list](https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-2.md#example-manifest-list)" object.

What that leaves is the **push** side of the equation which we are working on with the distribution team now (with the hope of a 1.11 timeframe for availability). The general concept is described here (with all the appropriate caveats about no guarantees on specifics until there is an agreed to PR/design): https://gist.github.com/estesp/e8128058e02526d95acf

**Comment by tianon** [comment]
For "arm", just using GOARCH isn't necessarily granular enough -- for
example, ARMv7 images will not work on ARMv6 or ARMv5 boxes (generally).
Are there any plans in the works to address this?

**Comment by tianon** [comment]
Oh scratch that -- that's the manifest lists you linked to already. :+1;

**Comment by bradrydzewski** [comment]
@estesp thanks for the update!

**Comment by rtsisyk** [comment]
I use armhf images to build Debian packages in my CI.
Could you please also add armhf/centos and armhf/fedora?
Thanks!

**Comment by stevvooe** [comment]
@rtsisyk Multi-arch support is still in its infancy. I am not sure that this is the right venue for your request. I think you'll have to contact the maintainer of armhf through https://hub.docker.com/r/armhf/.

**Comment by rtsisyk** [comment]
@stevvooe sorry, I thought that armhf/ are experimental images made by someone from Docker team.

**Comment by stevvooe** [comment]
@rtsisyk No worries. I just want to make sure you get your question answered!
