### ISSUE TITLE
Improve the way we deliver Examples in command line

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#15869]
The build and run commands both have long sections of examples.  In run them come in the middle of the page in build they come at the end.

- Standardize examples at the end of every page
- Design a consistent structure for calling out "categories of examples" in these larger sections

http://docs.docker.com/reference/commandline/build/
http://docs.docker.com/reference/commandline/run/

**Comment by dharmit** [comment]
#dibs I'd like to work on this if no one else is.

**Comment by moxiegirl** [comment]
@dharmit \0/ go for it.  This one is interesting...

**Comment by lordzero0000** [comment]
@moxiegirl @GordonTheTurtle @jfrazelle is this taken? I would like to work on it if is available.

**Comment by cpuguy83** [comment]
@lordzero0000 Go for it!

**Comment by zhangjianfnst** [comment]
#dibs If nobody takes this, I do.
