### ISSUE TITLE
[update] a graphdriver related question

### ISSUE THREAD

**Issue by michael4RD** [docker/docker#15867]
Hi,

I have a graph driver related question.

Suppose one wants to design and implement a graph driver for some new file system, what would be the general rule to do so? I mean, one can look into existing graph drivers (e.g., btrfs, aufs, zfs, vfs, devmapper, etc) to figure out interfaces and data structures for the new file system driver, but is there any driver specification doc available somewhere? It will make it easier to design new file system driver for docker.

Any suggestions/comments would be helpful! Thanks.

Best,

**Comment by cpuguy83** [comment]
The driver interface to implement is here: https://github.com/docker/docker/blob/master/daemon/graphdriver/driver.go#L39

It would be super awesome if someone were to put up a generic design doc around how the graphdrivers are expected to operate.

**Comment by michael4RD** [comment]
I can try to come up with a generic design doc once I have traversed the process :)

Right now, I had another naive question: If I add new directory/source file in the current source code, how can I make sure my source files are compiled then I do "hack/make.sh binary"? I did not any Makefile or Scons file in the sub directory. Any comment could be welcome.

Best,

**Comment by cpuguy83** [comment]
@michael4RD As long as something is importing your code, it will be compiled in.
This is all handled by go.

**Comment by LK4D4** [comment]
I think the question was answered. Feel free to ask more.
