### ISSUE TITLE
Incorrect URL on https://docs.docker.com/kitematic/userguide/

### ISSUE THREAD

**Issue by sbasyal** [docker/docker#15870]
The "Docker Machine" link on the first paragraph points to http://192.168.99.100:8000/machine/, which is not correct.

**Comment by charleswhchan** [comment]
Checked https://docs.docker.com/kitematic/userguide/ and the fix https://github.com/kitematic/kitematic/pull/976 has been deployed to the website. :+1: 

So this issue can be closed.
