### ISSUE TITLE
lxc fix kernel memory limit test

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#15876]
```
----------------------------------------------------------------------
FAIL: docker_cli_run_unix_test.go:284: DockerSuite.TestRunWithKernelMemory

docker_cli_run_unix_test.go:287:
    dockerCmd(c, "run", "--kernel-memory", "50M", "--name", "test", "busybox", "true")
github.com/docker/docker/integration-cli/_test/_obj_test/docker_utils.go:839:
    ...open github.com/docker/docker/integration-cli/_test/_obj_test/docker_utils.go: no such file or directory
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc20826db60)} ("exit status 255")
... "run --kernel-memory 50M --name test busybox true" failed with errors: WARNING: You specified a kernel memory limit on a kernel older than 4.0. Kernel memory limits are experimental on older kernels, it won't work as expected and can cause your system to be unstable.
, exit status 255


----------------------------------------------------------------------
```

**Comment by Tenk42** [comment]
#dibs

**Comment by cholerae** [comment]
It seems that we should add an additional judge in DockerSuite.TestRunWithKernelMemory, if the kernel is older than 4.0 then this test will be skipped.

**Comment by choleraehyq** [comment]
It seems that we should add an additional judge in DockerSuite.TestRunWithKernelMemory, if the kernel is older than 4.0 then this test will be skipped.

**Comment by sallyom** [comment]
Had similar problem while writing some tests for https://github.com/docker/docker/pull/14012, I'll take a look :)

**Comment by thaJeztah** [comment]
@Tenk42 were you working on this as well? If you are, please comment, to prevent you and @sallyom duplicating effort :smile:

**Comment by Tenk42** [comment]
@thaJeztah, i am working on this as well. I have made a reproducible environment and I study the daemon_unix.go. I reproduce the issue to have this warning that i should not have.

**Comment by thaJeztah** [comment]
@sallyom can you try to coordinate with @Tenk42 ? It's `tenk` on IRC :+1:

**Comment by sallyom** [comment]
sure thing, thanks!

**Comment by Tenk42** [comment]
Hello @sallyom, tell me when we can coordinate on irc. Was in the channel this afternoon but i have to leave it soon for today.

**Comment by thaJeztah** [comment]
@Tenk42 in case it helps; all contributors sign off their commits, which contains an email address; follow this link; https://github.com/docker/docker/pull/14012/commits

And view the commit message :innocent:

**Comment by jfrazelle** [comment]
any updates on this?

**Comment by Tenk42** [comment]
Working on it. Was able to reproduce the issue like https://jenkins.dockerproject.org/job/Docker%20Master%20(lxc)/
but now i have some trouble to have the same exactly error (no more warning)
I have more issue on my other test-integration-client replay than yours (my fork is up to date)
I am often on irc if you want to discuss but not as the same timezone than US (Japan)

**Comment by sallyom** [comment]
haven't looked into this any more, I am following though.  Thanks @Tenk42

**Comment by Tenk42** [comment]
@thaJeztah, i understand that lxc driver is depreciated and will be removed. Still the case?
@jfrazelle I can push a temporary modification to skip this test when daemon is using lxc driver.
In my configuration, if i remove the kernel memory limit test, i can't start a docker image with the kernelmemory modification if i launch the daemon with lxc exec driver. I have done several test with several way without success (my configuration fedora 22, 4.1.6)

**Comment by thaJeztah** [comment]
@Tenk42 yes, it's marked deprecated, and scheduled to be removed in Docker 1.10; see https://github.com/docker/docker/blob/master/docs/misc/deprecated.md

**Comment by jfrazelle** [comment]
But the test still needs to be fixed

**Comment by jfrazelle** [comment]
can some one fix it please :)
