### ISSUE TITLE
Layer Upload broken due to URL sanitization bug

### ISSUE THREAD

**Issue by stevvooe** [docker/docker#15875]
Under certain proxy configurations, where a relative url is encountered in Location fields, blob uploads may not be resolvable. The cli will report "blob upload unknown" and not provide much else.

There are more details here: https://github.com/docker/distribution/issues/928#issuecomment-135235658.

We need to get a fix in distribution and update the client in docker.

cc @dmcgowan

**Comment by stevvooe** [comment]
Marking as 1.8.2 pending impact analysis.

**Comment by stevvooe** [comment]
Confirmed this function is broken with a small test case sanitizing `sanitizeLocation("/v2/foo/baasdf?_state=asdfasfdasdfasdf", "http://blahalaja.com/v1")`:

```
repository_test.go:867: bad sanitize: "http://blahalaja.com/v2/foo/baasdf%3F_state=asdfasfdasdfasdf" != "http://blahalaja.com/v2/foo/baasdf?_state=asdfasfdasdfasdf"
```

**Comment by calavera** [comment]
@stevvooe can we port that fix in distribution to the vendored version we have in docker?

I think the best way to do that is:
1. Create a branch in distribution from the commit we have vendored in docker.
2. Apply the patch.
3. Vendor the result in docker.

What do you think?

**Comment by dmcgowan** [comment]
@calavera that is exactly the plan

**Comment by calavera** [comment]
cool :sunglasses:
