### ISSUE TITLE
System error generated for previously used Volumes

### ISSUE THREAD

**Issue by clintonskitson** [docker/docker#15880]
I believe https://github.com/docker/docker/pull/14242 introduced a regression where if you run a container with an external volume, and then kill the docker daemon, any following usage of the volume results in system errors.

It looks like the volume name is recognized, but it does not try and mount the volume.

```
./docker -d --storage-driver=vfs &
./docker run -ti --volume-driver=rexray -v testa15:/test busybox
kill pid
```

```
./docker -d --storage-driver=vfs &
./docker run -ti --volume-driver=rexray -v testa15:/test busybox
INFO[0003] POST /v1.21/containers/create                
INFO[0003] POST /v1.21/containers/deb4b572c3fa950d16279d0e5485c7322e2b865f5f0d666a94a561f4140dfb4c/attach?stderr=1&stdin=1&stdout=1&stream=1 
INFO[0003] POST /v1.21/containers/deb4b572c3fa950d16279d0e5485c7322e2b865f5f0d666a94a561f4140dfb4c/start 
Timestamp: 2015-08-27 07:18:29.736025403 +0000 UTC
Code: System error

Message: stat /var/lib/docker/volumes/testa15/_data: no such file or directory

Frames:
---
0: setupRootfs
Package: github.com/opencontainers/runc/libcontainer
File: rootfs_linux.go@37

```

```
[root@mdm2 centos]# ./docker version
INFO[0457] GET /v1.21/version                           
Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   44ea7e9
 Built:        Thu Aug 27 07:14:12 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by cpuguy83** [comment]
hmm, there should be no reason this changed... I'll have to take a look. Mount/Unmount should still be called after daemon every time a container starts.

**Comment by cpuguy83** [comment]
I cannot repro this, though I'm not using rexray.
@clintonskitson Can you ping me on IRC?

I tried this with both a clean shutdown and with `kill -9`ing the daemon.

**Comment by clintonskitson** [comment]
I just noticed that the volume driver it gets associated to goes to local on initialization of Docker.

```
./docker -d --storage-driver=vfs &
./docker volume ls
rexray              testa16
kill pid
```

```
./docker volume ls
local               testa16
```

**Comment by cpuguy83** [comment]
@clintonskitson Also not seeing this:

```
$ docker volume ls
DRIVER              VOLUME NAME
mydriver            testing
$ kill $(pidof docker)
INFO[0084] Processing signal 'terminated'
DEBU[0084] starting clean shutdown of all containers...
DEBU[0084] Clean shutdown succeeded
$ docker -d -D -s overlay &
...
$ docker volume ls
DRIVER              VOLUME NAME
mydriver            testing
```

**Comment by cpuguy83** [comment]
We figured this out.
Rexray is storing volume data in `/var/lib/docker/volumes`. When docker restarts it asks the local driver what volumes it has, which it figures out based on the subdirs in `/var/lib/docker/volumes`.

It does this specifically so that we don't lose track of volumes which aren't in use by a container after a daemon restart.
What ends up happening with rexray is the local driver is assuming control of these volumes since they are in docker's volume path.

I don't think we should make a change here since only docker should be writing to `/var/lib/docker`

**Comment by thaJeztah** [comment]
Maybe this should be added to the https://docs.docker.com/extend/plugin_api/ docs, so that plugin developers know that `/var/lib/docker/` should not be used.

**Comment by calavera** [comment]
yeah, this is a breaking change that we should make sure we communicate very clearly. Now I need to fix all my volume plugins! :imp:

**Comment by thaJeztah** [comment]
Closing this because a note was added here: https://github.com/docker/docker/pull/19051
