### ISSUE TITLE
Querying for all images with image size hangs

### ISSUE THREAD

**Issue by remh** [docker/docker#15888]
Description of problem:

`docker version`: 
```
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:
 ```
Containers: 175
Images: 1043
Storage Driver: devicemapper
 Pool Name: docker-9:5-4456459-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 62.44 GB
 Data Space Total: 107.4 GB
 Data Space Available: 44.94 GB
 Metadata Space Used: 81.19 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.066 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /data/docker/devicemapper/devicemapper/data
 Metadata loop file: /data/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.3-031903-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 15.58 GiB
Name: [REDACTED]
ID: KT4I:FZHC:U7CK:VZTR:73NB:PMTX:3CC3:ON2I:W5KT:XPCH:P3LG:EPSC
Username: remh
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

`uname -a`: 
```
Linux [REDACTED] 3.19.3-031903-generic #201503261036 SMP Thu Mar 26 14:37:55 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.): Bare metal dedicated server

How reproducible: Always with a high number of images

Steps to Reproduce:
1. Have a high number of images available
2. Query for all containers with image size: 
```python
python -c "import docker; docker.Client().containers(all=True, size=True)"
```

Actual Results:
The API call times out after 60 secs (default timeout for docker-py) but then the docker daemon is hanging forever (even a docker ps command without having actual containers running is hanging)

Expected Results:
The api call should return

**Comment by cpuguy83** [comment]
How many images do you have? I would imagine this is trying to calculate the size of each image layer and is taking a long time.

**Comment by remh** [comment]
i think it was something around 50

**Comment by cpuguy83** [comment]
what does `docker images -a | wc -l` give you?

**Comment by remh** [comment]
1659

**Comment by cpuguy83** [comment]
Oh sorry, I was seeing images for some reason, this would need to be containers....

so `docker ps -a | wc -l`
I'm also not sure what the speed of this is expected to be for devicemapper. It may be helpful to try with a single container.
This takes roughly 3 seconds for me with just 4 containers on overlay.

**Comment by remh** [comment]
I cleared my containers since though so i don't have access to this information anymore

**Comment by cpuguy83** [comment]
I'm going to close this, b/c it seems like this would be expected behavior.
Querying the size on all containers is going to be slow, probably even more so on devicemapper than aufs.
In the meantime there is a PR (and a related issue) to allow querying the size of a single container: #15796

If you do find that there is a deeper issue here, please ping and we can take a look.
Thanks!
