### ISSUE TITLE
Add image and container labels in logs

### ISSUE THREAD

**Issue by jfroche** [docker/docker#15884]
It would be nice to push container/image labels in the logs of our containers. We use this to give more context to the logs sent to our syslog/logstash. The log-opt parameter doesn't seem to enable this yet.

**Comment by vdemeester** [comment]
Hi @jfroche,

Thanks for reporting this, but I think this has already been propose there : #15816. If you think the same, I think we could close this one as a duplicate from #15816 :wink:.

**Comment by jfroche** [comment]
thanks ! this is a duplicate
