### ISSUE TITLE
Sharing images between multiple docker hosts

### ISSUE THREAD

**Issue by abdulrahmanazab** [docker/docker#15887]
At the university of oslo, we have a slurm cluster, Abel (https://www.notur.no/hardware/abel) with 630 nodes. We want to enable docker on these nodes.
The details of the issue can be found here, since this represents exactly what we need:
http://stackoverflow.com/questions/27794567/how-to-share-images-between-multiple-docker-hosts?answertab=active#tab-top

Docker swarm is not an option (at least for Abel) since we already have slurm as a queuing system. We just need a way to share the image repository to avoid waste of disk space. 

Also setting up a private registry (discussed here: https://github.com/docker/docker/issues/9935) is not what we are looking for, since it won't prevent image replication (630 times in our case).

I understand that each host needs to have its own containers repo, but for images, I don't see any logical reason not to be able to share them between any number of hosts

**Comment by clnperez** [comment]
It sounds like the solution for you might be simply creating your hosts' docker directories (e.g. /var/lib/docker) on some external storage (like FC).

**Comment by cpuguy83** [comment]
@clnperez Definitely not. The underlying storage driver would need to synchronize access here.
#13777 can help with implementing this outside of docker itself.

**Comment by abdulrahmanazab** [comment]
@clnperez This I tried before, sharing the whole '/var/lib/docker' in a shared area between nodes. It didn't work (and actually this seems logical). Then I shared the binary and had a separate docker directory for each node (adding '-g /shared/docker/nodename/') to  /etc/sysconfig/docker, But by having one place with repositories-devicemapper, /graph, and /devicemapper. And created symlinks in each /shared/docker/nodename to this central place (assuming that this is what I need to do to share images). It also didn't work

**Comment by abdulrahmanazab** [comment]
@cpuguy83 Well, your solution seems ok, but could you please provide some guidelines on how to implement this in practice? I don't see sufficient details in https://github.com/docker/docker/pull/13777

**Comment by cpuguy83** [comment]
yes, that flat out will not work.
You cannot share graph dirs between multiple daemons. This will lead to really bad results.
None of the built-in storage drivers are going to work as is for multi-daemon configurations.

**Comment by abdulrahmanazab** [comment]
@cpuguy83 Good to know :)

**Comment by abdulrahmanazab** [comment]
@cpuguy83 Then will your other solution prevent replication, or each host will need to have its separate image repo anyway?

**Comment by cpuguy83** [comment]
@abdulrahmanazab The above PR introduces being able to build a graph driver outside of docker. Fundamentally to do multi-daemon, this driver would still need to coordinate things.
So no, that PR is not solving multi-daemon, it's making it easier to do it since it can be handled by out-of-process plugins.
Docker Engine is very much single-host focussed (today).

**Comment by abdulrahmanazab** [comment]
@cpuguy83 I see, but then you might consider opening up this direction in the future. In Notur (https://www.notur.no/hardware) we have five large clusters. We want to go for docker since we are really tired of native installations with the module system. But also it won't be very practical having e.g. 600 replicates of the same software (one for each node).

However, just had an idea that might make things slightly better. Is there a way to check when the last time an image was used? What I can do is to create a cron job on each docker host to automatically remove old images. And off course they will be automatically pulled from e.g. our local registry once called to run again. It is important also to know if there will be some obstacles removing old images related to dependencies ..etc since docker uses layered FS

**Comment by clnperez** [comment]
@cpuguy83, I see, and thanks for the explanation. It would definitely be cool if/when there was a way to take advantage of the layered and shared nature of the docker images workflow and extend it to the multi-daemon direction.

**Comment by abdulrahmanazab** [comment]
@cpuguy83 I also want to test your external graphdriver solution https://github.com/docker/docker/pull/13777 
How to create an external graph? and how to access it from docker daemon(s) afterwards?

**Comment by auzias** [comment]
@abdulrahmanazab, I run into the same issue. Did you went through with this issue? How did you solved the problem? What are you using today?

**Comment by faddat** [comment]
Why does each host need to have its own container repo?  I'm missing something critical here, I think.

**Comment by faddat** [comment]
@abdulrahmanazab -- any idea why sharing /var/lib/docker didn't work?  That was the approach that I was mid-way through trying.

**Comment by thaJeztah** [comment]
@faddat the daemon keeps track of various things, for example, if an image is in use by a container. Having two daemons run on the same directory can result in bad things, such as removing that image while it's in use by a container running on another host. Read, for example, https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/

**Comment by aanm** [comment]
Out of curiosity, so **every time** you start/run a container, the _base_ image needs to be pulled from your sort of private registry? That means you must have the _base_ image for each container when the containers are running. Thus, can't you create a cron job that removes _base_ images on each host that aren't being used by containers?

**Comment by thaJeztah** [comment]
Given the discussion above; the `/var/lib/docker` directory is not designed to do this, and implementing would require a big rewrite, so I'm closing this issue
