### ISSUE TITLE
Swarm on a network

### ISSUE THREAD

**Issue by abdulrahmanazab** [docker/docker#15892]
I'm trying to install swarm on our test cluster SNabel (16 compute nodes), by setting one as the manager. Have been through this manual (https://docs.docker.com/swarm/install-manual/), but there are issues. when docker is configured to run as ```docker -H tcp://0.0.0.0:2375 -d```
I found that the daemon MUST be called afterwards using ```docker -H tcp://0.0.0.0:2375 <command>```, and NOT ```docker <command>```, so I guess this should be fixed in the manual.
The more important thing, is that I managed to get the swarm manager running together with one node (which is the local node), but things didn't work with the other nodes. What happens is, when I run:
```docker -H tcp://0.0.0.0:2375 run -d swarm join --addr=<node_ip:2375> token://<cluster_id>```
on each node, the container starts ok, but it does not appear in the list of the manager. 

I feel there is something messing here. I don't see, in the steps described in the manual, how the swarm nodes will know the address of the manager. in the join command above, the manager's address is not provided as an argument

**Comment by MHBauer** [comment]
dup of https://github.com/docker/swarm/issues/1175

**Comment by abronan** [comment]
Closing this one as this was handled in swarm already :)
