### ISSUE TITLE
Fix broken pipe error on client pull disconnect

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#15891]
When a client disconnects while a pull is in progress, an error is written to the daemon logs for the broken pipe.
We can probably ignore this error for broken pipe.

**Comment by thaJeztah** [comment]
is this a dup of  https://github.com/docker/docker/issues/15589 (resolved by https://github.com/docker/docker/pull/15646)? Not sure, just thought there could be some overlap :-)

**Comment by cpuguy83** [comment]
No, this has to do with the error logs in the daemon that #15646 generates.

**Comment by cpuguy83** [comment]
This was fixed by #18752
