### ISSUE TITLE
Use /etc/hosts entries when populating environment variable for links 

### ISSUE THREAD

**Issue by gionn** [docker/docker#15906]
Hi,

`/etc/hosts` is automatically populated with entries of linked containers: https://docs.docker.com/userguide/dockerlinks/#updating-the-etc-hosts-file

so it should be safe to use the *hostname* instead of the plain *private ip* address when injecting environment variables for links (e.g.: `DB_PORT_5432_TCP_ADDR`).

This will permit to avoid restarting any dependent container when a container is upgraded (bad on production environments), since `/etc/hosts` entry are automatically updated.

This is the main reason why we are happy with links on dev and jenkins environment, but we are sticking with `--net=host` on production.

**Comment by cpuguy83** [comment]
ping @mrjana

**Comment by cpuguy83** [comment]
Honestly, I'd argue why even both using the env vars at all?
The hostname of the linked container is known, so just use that.

**Comment by gionn** [comment]
You are probably right, but I imagine a use case where I want to easily switch linking between different containers (think of a web container linked to a db container) for different environments (staging, production).

I can't do it since I can't create two container with the same name, so I would need to inject an additional environment variable to specify the name of the actual linked container.

IMHO it's more simple to just add another env var generated by docker via links, e.g.:

```
DB_PORT_5432_TCP_HOST=postgres
```

**Comment by cpuguy83** [comment]
They would use the same alias, but not the same name.

**Comment by thaJeztah** [comment]
I'm closing this issue; we won't be updating the behavior of the environment-variables, because we only keep them around for backward-compatibility on the default bridge network.

Using the hostname from `/etc/hosts` (or the new embedded DNS discovery), in combination with an alias `--link foo:bar` sounds like something that works for this use case.

Thanks for suggesting, @gionn!

**Comment by gionn** [comment]
Yeah, we already stopped using links since 1.9.0.

Cheers!
