### ISSUE TITLE
-d flag referenced in docs where daemon is used in the accompanying example

### ISSUE THREAD

**Issue by cpswan** [docker/docker#15909]
In https://docs.docker.com/project/set-up-dev-env/ (Start a container and run a test, part 8)

The command line example has been updated to use `daemon` rather than `-d`:

>`root@5f8630b873fe:/go/src/github.com/docker/docker#  docker daemon -D`

But the following explanation still refers to `-dD`, which was previously there

> The -dD flag starts the daemon in debug mode. You’ll find this useful when debugging your code.

**Comment by lyndaoleary** [comment]
Hi, I can change this :) #dibs
