### ISSUE TITLE
Creating container via remote API with data volume specification causes error

### ISSUE THREAD

**Issue by barsteadr** [docker/docker#15908]
## uname -a
`Linux rjb 3.19.0-26-generic #28~14.04.1-Ubuntu SMP Wed Aug 12 14:09:17 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

## docker version
```Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64
```

##  docker info
```
Containers: 2
Images: 51
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 55
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-26-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 2
Total Memory: 5.813 GiB
Name: rjb
ID: U3PM:6Q7Q:4N54:TB2L:N4OR:BU2J:H4LE:XUAP:IAUO:H5VM:5LWB:JVJZ
WARNING: No swap limit support
```

#### Environment details: 
`VMWare Fusion V8`

#### How reproducible: 
`Fails every time`

#### Steps to Reproduce:
1. run:
 `docker pull ubuntu:14.04`
2. Submit a POST call: 
`curl -XPOST localhost:4243/containers/create?name=dockerdata -H "Content-Type:application/json" -d '{"Image": "ubuntu:14.04", "Hostconfig": {"Binds": ["/var/www"] }  }'`

#### Actual Results: 
1. Error: `Invalid volume specification: /var/www`
2. No volume mounts reported for the container

#### Expected Results:
Expected something like the following when inspecting the container
```
    "Mounts": [
        {
            "Name": "67bfe6dca71...",
            "Source": "/var/lib/docker/volumes/67bfe6dca71.../_data",
            "Destination": "/var/www",
            "Driver": "local",
            "Mode": "",
            "RW": true
        }
```

#### Additional info:
The same issue was reported [here](https://github.com/docker/docker/issues/13786) for Docker V1.6

I'm attempting to create a data volume container.

Expectations come from the Documentation: 
Creates a container with /fakedir shareable volume based on https://docs.docker.com/reference/api/docker_remote_api_v1.18/#create-a-container:
"Binds – A list of volume bindings for this container. Each volume binding is a string of the form container_path (to create a new volume for the container), host_path:container_path (to bind-mount a host path into the container), or host_path:container_path:ro (to make the bind-mount read-only inside the container)."

Finally, the expected behavior is obtained when not using the remote API. Running this command:
`docker create -v /var/www --name dockerdata ubuntu:14.04 /bin/true` 
leads to the desired result.

**Comment by cpuguy83** [comment]
@barsteadr Keep in mind, the CLI uses the remote API in all cases.

A "Bind" is a `host_path:container_path`. The bind spec you have is indeed incorrect since you have not specified a host path.

If all you are looking to do is to create a normal volume (not bound to a specific host dir), then you should do:

```json
{
    "Image": "ubuntu:14.04",
    "Volumes": { "/var/www": {} }
}
```

**Comment by jom** [comment]
@cpuguy83 Volumes is not included in Remote API v1.20 (https://docs.docker.com/reference/api/docker_remote_api_v1.20/#create-a-container) and doesn't seem to be working.

**Comment by cpuguy83** [comment]
Yes, it appears someone has made a mistake when updating the API docs...

**Comment by cpuguy83** [comment]
The syntax I pasted is correct, however:
```
$ curl -XPOST -H 'Content-Type: application/json' localhost/containers/create?name=foo -d '{"Image": "busybox", "Volumes": { "/foo": {}}}'
$ docker inspect -f '{{ json .Mounts }}' foo | jq .
[
  {
    "RW": true,
    "Mode": "",
    "Driver": "local",
    "Destination": "/foo",
    "Source": "/var/lib/docker/volumes/9b2a28e96e288b674e9b8ef0b645af7696d31f43c761ac44bd33e3a3a661a833/_data",
    "Name": "9b2a28e96e288b674e9b8ef0b645af7696d31f43c761ac44bd33e3a3a661a833"
  }
]
```

**Comment by barsteadr** [comment]
@cpuguy83 Sorry, I should have replied earlier. Yes, as @jom said the the 'volumes' key is undocumented in the API docs. Yes, the syntax you suggested worked perfectly for me :+1:. Many thanks.
