### ISSUE TITLE
namespace inside container

### ISSUE THREAD

**Issue by sowndaryak** [docker/docker#15907]
how do i map the uid in the host to the container? please get me through linux commands?

**Comment by sowndaryak** [comment]
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64



Containers: 81
Images: 17
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 181
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-30-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 979.7 MiB
Name: ubuntu

Linux ubuntu 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14
UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by hqhq** [comment]
Map uid from host to container needs user namespace support, which is not supported yet, the phase one support should be in 1.9.

And this is not a Docker issue, should not ask questions here, you can ask questions in google groups: https://groups.google.com/forum/#!forum/docker-dev

**Comment by sowndaryak** [comment]
Youth4workHi ,Sowndarya K, your contact & who has this profileSuggests you to try a quick, 5 min, Online Skill test to know your own skillshttps://www.youth4work.com/onlinetalenttestIt’s a fun test that helps you know where you stand for your skills across the globe. It also helps you get professional opportunities.Regards,Youth4workUnsubscribe
