### ISSUE TITLE
no Dockerfile in web gui for automated build

### ISSUE THREAD

**Issue by nilskuhn** [docker/docker#15928]
Hi,
there is no Dockerfile in this [automated build](https://hub.docker.com/r/iteratechh/rearview-init/~/dockerfile/).
The Dockerfile in associated [gitub repository](https://github.com/iteratec-hh/dockerfiles) isn't located in the root of that repository. Maybe that's the reason. But if the possibility exists to set the location of Dockerfile explicitly it should be shown in web gui approppriately.
Or am I missing something?

**Comment by TomNussbaumer** [comment]
Go to __build settings__. There you can modify the location of the Dockerfile.

**Comment by thaJeztah** [comment]
I think this can be closed; also, this repository is for tracking bugs in Docker; issues for Docker hub are handled by a different team and can be reported via https://support.docker.com. Issues with the new Docker Hub web interface via https://github.com/docker/hub-beta-feedback/

Hope this helps!

**Comment by nilskuhn** [comment]
Sorry, I think I was too fast with this ticket. 
It took a while until Dockerfile was visible after first build was visible.
Everything works as expected.
