### ISSUE TITLE
Add option to decompress remote tarballs in ADD

### ISSUE THREAD

**Issue by mboes** [docker/docker#15934]
Currently, the [dockerfile_best-practices](https://docs.docker.com/articles/dockerfile_best-practices/) article has (in part) this to say about `ADD` vs `COPY`:

> Because image size matters, using ADD to fetch packages from remote URLs is strongly discouraged; you should use curl or wget instead. That way you can delete the files you no longer need after they’ve been extracted and you won’t have to add another layer in your image. For example, you should avoid doing things like:
>
> ```
> ADD http://example.com/big.tar.xz /usr/src/things/
> RUN tar -xJf /usr/src/things/big.tar.xz -C /usr/src/things
> RUN make -C /usr/src/things all
> ```

This is counter intuitive, but what's going on here is that the user is performing `RUN` because the archive is *remote*, and remote archives are not auto extracted (for some unknown reason not documented anywhere).

In https://github.com/docker/docker/issues/11174, @duglin notes that once https://github.com/docker/docker/pull/10775 is merged, adding a flag to control `ADD`'s behaviour here should be looked into.

The flag would unconditionally extract the tarball even if `<src>` is remote.

cc @TZer0.

**Comment by duglin** [comment]
Given https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax and that the pattern we're following is to close issues that ask to change the Dockerfile syntax until the embargo is lifted I'm going to close this.  We can reopen it later if needed.

**Comment by JanoschDeurer** [comment]
Is there now a chance you can reopen this? There seems to be a lot of interest in this especially here: #2369
