### ISSUE TITLE
[DOC] "Dockerizing MongoDB" - Dockerfile not found

### ISSUE THREAD

**Issue by charleswhchan** [docker/docker#15939]
Going thru the "Dockerizing MongoDB" documentation: https://docs.docker.com/examples/mongodb/

> Note:
> The full version of this Dockerfile can be found [here](https://docs.docker.com/examples/mongodb/Dockerfile).

The link https://docs.docker.com/examples/mongodb/Dockerfile leads to a "404" page not found, even though the file is found under [/examples/mongodb/Dockerfile](https://github.com/docker/docker/tree/master/docs/examples/mongodb) in the Git repo.

Perhaps the file is not uploaded to the web server, or is placed in an alternate path?

**Comment by SvenDowideit** [comment]
I suspect the best thing to do, is to change the URL to point to the github repo version of these files.

we used to publish them with the docs, but I'm not sure that there's a strong benefit to it anymore.

@moxiegirl @thaJeztah

**Comment by moxiegirl** [comment]
@charleswhchan thanks for the contribution. I tend to agree with @SvenDowideit  think it makes sense to point to the github repo --- why publish in two places?

**Comment by charleswhchan** [comment]
Sounds good to me. :smiley: 

#dibs

**Comment by charleswhchan** [comment]
PR #15969 merged. I will mark this as closed.
