### ISSUE TITLE
Invalid docker version output

### ISSUE THREAD

**Issue by haosdent** [docker/docker#15933]
In Fedora 22, the `docker --version` output is

```
Docker version 1.7.0.fc22, build 74e7a7a/1.7.0
```

Seems this one is not match [semver](http://semver.org/), change to "1.7.0-fc22" would be better.

**Comment by runcom** [comment]
seems like this has to do with specific fedora Docker pkg and as such I think it would be better to report this directly to their tracker rather than here cause we can't do anything (docker rpm repo doesn't add anything after version also)
 
I'm closing but ping me if you think I'm mistaken

**Comment by haosdent** [comment]
Thank you very much!
