### ISSUE TITLE
docker inspect image-id: why are there no details about repository(s) and tag(s)?

### ISSUE THREAD

**Issue by TomNussbaumer** [docker/docker#15930]
Is there any (good) reason why there is no info about repository(s) and tag(s) when inspecting an image (`docker inspect <image-id>`)?

IMHO its really awkward to parse the unstructured (=no json) output of `docker images` and combine it with the output of `docker inspect` to get a complete set of informations about an image.

**Comment by duglin** [comment]
@TomNussbaumer have you tried the REST APIs instead?  e.g.   /images/json

**Comment by vdemeester** [comment]
@TomNussbaumer I think this is going to be fixed with #13185 isn't it ? (for the inspect part).

**Comment by thaJeztah** [comment]
looks like a dup of https://github.com/docker/docker/issues/10139, which will be fixed by https://github.com/docker/docker/pull/13185, but feel free to comment if you think it's different, then I'll reopen
