### ISSUE TITLE
Killed container still appeared to be running

### ISSUE THREAD

**Issue by bartmeuris** [docker/docker#15942]
Description of problem:

I run my irc client inside docker, and use it with docker attach. This morning when I ran the script, which should have attached the container, it hanged and didn't respond to Ctrl-L to refresh the display, and had to kill the docker client from another console. When doing a `docker ps`, it showed that the container was "Up 5 weeks" and had been created "5 weeks ago". Killing resulted in an error that clearly didn't have anything to do with it (it mentioned TLS). A quick `ps auwx` did not show any irssi process.

It was the only container running on the system, so I rebooted the machine. After the reboot I did a quick `docker ps` - and to my surprise the container still appeared to be "Up 5 weeks", but `ps` still didn't show any irssi process.

To fix this, I stopped the docker daemon, edited the `/var/lib/docker/containers/<id>/config.json` and set the `running` to `false` and restarted the daemon.

I have no idea how to reproduce it, but it seems some extra validation checks might be needed before assuming a container is running and not just relying on the `config.json`.

`docker version`:
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

`docker info`:
Containers: 12
Images: 170
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 194
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-62-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 3.861 GiB
Name: koffie
ID: 6QXR:2KPJ:R4LD:RO26:LR4S:MX4V:QHAI:BFLR:RXNZ:JFZJ:HBTV:PDZD
Username: bartmeuris
Registry: https://index.docker.io/v1/

`uname -a`:
Linux koffie 3.13.0-62-generic #102-Ubuntu SMP Tue Aug 11 14:29:36 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):

VM running on VMWare ESX

Steps to reproduce:

- Haven't been able to reproduce

Actual Results:

Container not attaching, container process not running, docker still showing the container as "Up"

Expected Results:

Docker not showing the container as running

Additional info:

Dockerfile and script to start/attach container here: https://gist.github.com/bartmeuris/ed6a45f9c4d0216649b8

**Comment by thaJeztah** [comment]
ping @coolljt0725 I think some improvements were made in this, or am I mistaken?

**Comment by coolljt0725** [comment]
The PR fixed this is not in 1.8.1
>To fix this, I stopped the docker daemon, edited the /var/lib/docker/containers/<id>/config.json and set the running to false and restarted the daemon.

is the right approach

**Comment by thaJeztah** [comment]
@coolljt0725 is the fix in master / 1.9? I couldn't find the PR :relaxed:

**Comment by coolljt0725** [comment]
@thaJeztah  #15748 #16275 is going to fix this.
In normal, daemon will `set the running to false` if detect the container has a state `running=true` on container registering when daemon starting, but sometimes registering failed before `set the running to false` and returned left with the container has a state `running=true`.

**Comment by thaJeztah** [comment]
Thanks @coolljt0725, those changes will be in docker 1.9.

@bartmeuris as commented above, docker 1.9 will have fixes to prevent this situation. I'm going to go ahead and close this issue, but feel free to comment here after I've closed this issue! thanks!
