### ISSUE TITLE
Docker apt repository only having one version

### ISSUE THREAD

**Issue by philicious** [docker/docker#15947]
With the old repository we had package "lxc-docker" pointing to latest greatest version and "lxc-docker-1.6.0" etc for specific version.
With the new repo there is only one package "docker-engine" in the "Packages" file, pointing to 1.8.1 although more versions do exist ( http://apt.dockerproject.org/repo/pool/main/d/docker-engine/ )

For automatic use of this repo, like with Chef/Puppet, it is quite handy if you can pin a certain version and later raise that version for automatic upgrades

**Comment by cpuguy83** [comment]
Closing as a dup of #13191

**Comment by cpuguy83** [comment]
No worries, GH search is awful.

Btw, what should actually happen here is you specify the version like so: `docker-engine=x.y.z-0~trusty`.
