### ISSUE TITLE
Docker Account Confirmation difficulties

### ISSUE THREAD

**Issue by duane** [docker/docker#15940]
1. Sign up for account.
2. Ignore email confirmation.
3. Find it impossible to log in or send another email confirmation after initial one expires.

Result: account is impossible to access, but username and email are still reserved.

**Comment by ubergesundheit** [comment]
I think you should reopen this issue in the hub-beta-feedback repository https://github.com/docker/hub-beta-feedback

**Comment by cpuguy83** [comment]
Closing since this belongs in with Hub.
Please open a ticket with https://support.docker.com or send an email to support@docker.com

Thanks! Sorry you seem to have hit a bug in the sign-up process!
