### ISSUE TITLE
Unsupported content file

### ISSUE THREAD

**Issue by ybalt** [docker/docker#15956]
Just updated from 1.7.1 to 1.8.0

curl -XGET 'http://127.0.0.1:2375/version'

{"Version":"1.8.1","ApiVersion":"1.20","GitCommit":"d12ea79","GoVersion":"go1.4.2","Os":"linux","Arch":"amd64","KernelVersion":"3.16.0-4-amd64","BuildTime":"Thu Aug 13 02:20:14 UTC 2015"}

curl -XGET 'http://127.0.0.1:2375/info'

{"ID":"KF3S:J2QG:OP6T:JZ2P:CQWT:5P5V:EXWG:IKHX:2AX3:WWN5:322O:53L6","Containers":1,"Images":103,"Driver":"aufs","DriverStatus":[["Root Dir","/opt/docker/aufs"],["Backing Filesystem","extfs"],["Dirs","105"],["Dirperm1 Supported","true"]],"MemoryLimit":false,"SwapLimit":false,"CpuCfsPeriod":false,"CpuCfsQuota":false,"IPv4Forwarding":true,"BridgeNfIptables":true,"BridgeNfIp6tables":true,"Debug":false,"NFd":17,"OomKillDisable":false,"NGoroutines":30,"SystemTime":"2015-08-31T18:51:43.757684989+02:00","ExecutionDriver":"native-0.2","LoggingDriver":"json-file","NEventsListener":0,"KernelVersion":"3.16.0-4-amd64","OperatingSystem":"Debian GNU/Linux 8 (jessie)","IndexServerAddress":"https://index.docker.io/v1/","RegistryConfig":{"InsecureRegistryCIDRs":["127.0.0.0/8"],"IndexConfigs":{"172.24.0.40:5000":{"Name":"172.24.0.40:5000","Mirrors":[],"Secure":false,"Official":false},"docker.io":{"Name":"docker.io","Mirrors":null,"Secure":true,"Official":true}},"Mirrors":null},"InitSha1":"adf381ad91157d139cc0db713963144d07fee714","InitPath":"/usr/lib/docker/dockerinit","NCPU":2,"MemTotal":2107985920,"DockerRootDir":"/opt/docker","HttpProxy":"","HttpsProxy":"","NoProxy":"","Name":"log1","Labels":null,"ExperimentalBuild":false}

uname -a
Linux log1 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u2 (2015-07-17) x86_64 GNU/Linux

Doing 
curl -X POST 'http://127.0.0.1:2375/build?t=127.0.0.1:5000/zookeeper&remote=http://mercurial.local/ms/raw-file/tip/Dockerfiles/Services/zookeeper/Dockerfile'

got 
Error detecting content type for remote http://mercurial.local/ms/raw-file/tip/Dockerfiles/Services/zookeeper/Dockerfile: unsupported Content-Type "application/binary"

and build not happen. On 1.7.1 no issues.
Any workaround? There is no way to change CT for mercurial web server output.

**Comment by LK4D4** [comment]
Closing as old :(
