### ISSUE TITLE
regression: docker rename

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#15952]
Unsure if this is only on master or not:

steps to reproduce:
```console
$ docker run -it --name test debian:jessie bash
root@e121360413a0:/# 

# keep that one open, in new tab
$ docker rename test test-1

jessie at debian in ~
$ docker run -it --name test debian:jessie bash
Error response from daemon: Cannot start container 69512151a18e701f1d29373a05f355583a87c96184901a20635d4ad89eb0e829: 
a container has already joined the endpoint

```
ping @mrjana @mavenugo

**Comment by jfrazelle** [comment]
I'm testing 1.8.1 now to make sure this does not need to be in 1.8.2

**Comment by jfrazelle** [comment]
yes this needs to be in 1.8.2, ping @calavera @icecrime so they are aware

**Comment by jfrazelle** [comment]
considering i was the first person to notice the regression and its been broken since 1.7.0 when we merged libnetwork, no one must use this feature /o\

**Comment by jfrazelle** [comment]
let's remember to point to this, when people are mad we don't merge their features ;)

**Comment by chenchun** [comment]
:laughing:

**Comment by mavenugo** [comment]
:) @jfrazelle this is a dupe of https://github.com/docker/docker/issues/15727. Reported 11 days ago. Calls for a regression test for renaming. Being a dupe, I will close this.

**Comment by jfrazelle** [comment]
ah cool! omg so glad not the first thasnk!

**Comment by mavenugo** [comment]
almost the first ... your point on feature addition still holds... still a big lead time between 1.7.0 and {1.8.2.RC1 - 11 days}.
