### ISSUE TITLE
Parse error breaks docker run -v functionality

### ISSUE THREAD

**Issue by jjaquinta** [docker/docker#15962]
BUG REPORT INFORMATION

>$ docker version
>Client:
> Version:      1.8.1
> API version:  1.20
> Go version:   go1.4.2
> Git commit:   d12ea79
> Built:        Thu Aug 13 02:49:29 UTC 2015
> OS/Arch:      windows/amd64
>
>Server:
> Version:      1.8.1
> API version:  1.20
> Go version:   go1.4.2
> Git commit:   d12ea79
> Built:        Thu Aug 13 02:49:29 UTC 2015
> OS/Arch:      linux/amd64

>$ docker info
>Containers: 11
>Images: 34
>Storage Driver: aufs
> Root Dir: /mnt/sda1/var/lib/docker/aufs
> Backing Filesystem: extfs
> Dirs: 56
> Dirperm1 Supported: true
>Execution Driver: native-0.2
>Logging Driver: json-file
>Kernel Version: 4.0.9-boot2docker
>Operating System: Boot2Docker 1.8.1 (TCL 6.3); master : 7f12e95 - Thu Aug 13 03:
>24:56 UTC 2015
>CPUs: 1
>Total Memory: 1.956 GiB
>Name: default
>ID: 5PYO:K4MX:4TMA:XWZT:QBE5:D346:SJBN:JSHW:SB2A:EIWP:PQMX:S64G
>Debug mode (server): true
>File Descriptors: 23
>Goroutines: 82
>System Time: 2015-08-31T20:26:57.762207194Z
>EventsListeners: 0
>Init SHA1:
>Init Path: /usr/local/bin/docker
>Docker Root Dir: /mnt/sda1/var/lib/docker
>Username: jjaquinta
>Registry: https://index.docker.io/v1/
>Labels:
> provider=virtualbox

>$ uname -a
>MINGW32_NT-6.1 TRAJAN 1.0.12(0.46/3/2) 2012-07-05 14:56 i686 unknown

### 1. Validate that you can run a simple bash shell, logout.

>$ docker run -i -t ubuntu:latest bash
>root@02c2775e59d0:/# pwd
>/
>root@02c2775e59d0:/# exit

### 2. Validate you have a complete path to a valid directory.

>$ ls -lsd /c/Users/IBM_ADMIN/Documents
>   2 dr-xr-xr-x    1 jo_grant Administ     4096 Aug 31 09:21 /c/Users/IBM_ADMIN/Documents

### 3. Try to run bash mounting that directory as volume /Documents according to syntax defined in Managing Data In Containers/Adding a Data Volume (https://docs.docker.com/userguide/dockervolumes/)

>$ docker run -i -t -v /Documents /c/Users/IBM_ADMIN/Documents ubuntu:latest bash

## Describe the results you received:
Docker failed to parse the command line based on the documentation. It produced the following error:

>Unable to find image 'c:/Users/IBM_ADMIN/Documents:latest' locally
>repository name component must match "[a-z0-9]+(?:[._-][a-z0-9]+)*"

## Describe the results you expected:
I expected it to mount the host directory /c/Users/IBM_ADMIN/Documents into the container as the point /Documents

## Provide additional info you think is important:
If I use the following command line:

>$ docker run -i -t -v /Documents:/c/Users/IBM_ADMIN/Documents ubuntu:latest bash

It produces this error:

>invalid value "C:\\Program Files (x86)\\Git\\Documents;c:\\Users\\IBM_ADMIN\\Documents" for flag -v: bad mount mode specified : \Users\IBM_ADMIN\Documents
>See 'c:\Program Files\Docker Toolbox\docker.exe run --help'.

It is interpreting the : separator as separating the first file name from the optional file mode. This jives with what the documentation says.

If I use this command line:

>$ docker run -i -t -v /Documents:ro ubuntu:latest bash

It mounts the given directory onto /ro!

>root@7a406f4bb924:/# df
>Filesystem     1K-blocks    Used Available Use% Mounted on
>none            19049892 2300340  15758828  13% /
>tmpfs            1025388       0   1025388   0% /dev
>shm                65536       0     65536   0% /dev/shm
>tmpfs            1025388       0   1025388   0% /sys/fs/cgroup
>tmpfs            1845704  115064   1730640   7% /ro
>/dev/sda1       19049892 2300340  15758828  13% /etc/hosts
>tmpfs            1025388       0   1025388   0% /proc/kcore
>tmpfs            1025388       0   1025388   0% /proc/timer_stats

The problem is that in part of the code, it expects there to be only a single argument, delimited by :. But in another part of the code, expects multiple arguments.
Between the two, the functionality is broken. (Unless you always want to name your mounts "ro"!)

**Comment by robmint** [comment]
I am having this exact same problem - serious breakage!

**Comment by xlgao-zju** [comment]
I think if you want to mount the host directory /c/Users/IBM_ADMIN/Documents into the container as the point /Documents, you should use
     $ docker run -i -t -v /Documents:/c/Users/IBM_ADMIN/Documents:/Documents ubuntu:latest bash

**Comment by xlgao-zju** [comment]
#dibs

**Comment by vdemeester** [comment]
Hi @jjaquinta, 

>  $ docker run -i -t -v /Documents /c/Users/IBM_ADMIN/Documents ubuntu:latest bash

As @xlgao-zju  pointed out, the documentation example is the following : `$ docker run -d -P --name web -v /webapp training/webapp python app.py`. It does **not** mean mount `/webapp` in `training/webapp` — `training/webapp` is the name of the image. So the result you have is expected. (I do agree the documentation can be misleading though :sweat_smile:).

> I think if you want to mount the host directory /c/Users/IBM_ADMIN/Documents into the container as the point /Documents, you should use
> $ docker run -i -t -v /Documents:/c/Users/IBM_ADMIN/Documents:/Documents ubuntu:latest bash

@xlgao-zju  ` /Documents:/c/Users/IBM_ADMIN/Documents:/Documents` is invalid. It can either be `containerPath`, `containerPath:mode`, `hostPath:containerPath` or `hostPath:containerPath:mode` (where mode can be `ro`, `rw` and some other thing [SELinux stuff]).

**Comment by xlgao-zju** [comment]
@vdemeester Sorry, I can't be more careless. Recently, I've read the code of volume, and I think my pr (#15846) will make -v /paht:ro fail.

**Comment by vdemeester** [comment]
@xlgao-zju I might have yeah :sweat_smile:. See my comment on #16013 though :wink:.

**Comment by jfrazelle** [comment]
see explanation here https://github.com/docker/docker/pull/16013#issuecomment-146647216
