### ISSUE TITLE
Bug installing Docker on Mac OS 10.8.5

### ISSUE THREAD

**Issue by shoshi** [docker/docker#15960]
Steps to reproduce:

1. Download the latest available version from: https://www.docker.com/toolbox. `DockerToolbox-1.8.1c.pkg`
2. Launch the installer.
3. Click "Continue".
![screen shot 2015-08-31 at 1 35 19 pm](https://cloud.githubusercontent.com/assets/171493/9585494/55ce47dc-4fe5-11e5-8ecc-b00f5e06dd21.png)
4. Get to the Introduction step and click "Continue" again.
![screen shot 2015-08-31 at 1 35 27 pm](https://cloud.githubusercontent.com/assets/171493/9585502/5bf2d786-4fe5-11e5-85d9-11bb3b0b2a6c.png)
5. Get stuck here. No options are available.
![screen shot 2015-08-31 at 1 35 32 pm](https://cloud.githubusercontent.com/assets/171493/9585510/6d0cee26-4fe5-11e5-8453-a84e136c873c.png)

The only errors in the installer log seem to be related to Mixpanel:
```
Aug 31 13:09:48 *.local Installer[5386]: objc[5386]: Class Mixpanel is implemented in both /var/folders/8t/218drryn6b3_xnrgzy0pnxlc0000gn/T/com.apple.install.3bOAli6T/overviewplugin.bundle/Contents/MacOS/overviewplugin and /var/folders/8t/218drryn6b3_xnrgzy0pnxlc0000gn/T/com.apple.install.3bOAli6T/managevmplugin.bundle/Contents/MacOS/managevmplugin. One of the two will be used. Which one is undefined.
Aug 31 13:09:48 *.local Installer[5386]: objc[5386]: Class Mixpanel is implemented in both /var/folders/8t/218drryn6b3_xnrgzy0pnxlc0000gn/T/com.apple.install.3bOAli6T/overviewplugin.bundle/Contents/MacOS/overviewplugin and /var/folders/8t/218drryn6b3_xnrgzy0pnxlc0000gn/T/com.apple.install.3bOAli6T/quickstartplugin.bundle/Contents/MacOS/quickstartplugin. One of the two will be used. Which one is undefined.
```

I also tried rebooting the computer and re-downloading the installer just to see if that helped. Unfortunately, it didn't change anything.

**Comment by fntlnz** [comment]
This is not a docker related issue, you should open it on the  [docker/toolbox](https://github.com/docker/toolbox) project

**Comment by shoshi** [comment]
Thanks for the info! I'll close this ticket in favor of: https://github.com/docker/toolbox/issues/134 .
