### ISSUE TITLE
local resolver fails

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#15978]
Issue is reported by user on #docker.

Using ElemtaryOS on a university network, /etc/resolv.conf is set to use a local resolver @ 127.0.1.1.
In this case, docker discards this entry and uses `8.8.8.8` and `8.8.4.4` in the container.
However in this particular case, the public DNS is not working likely due to some captive portal requiring to use the Uni's DNS servers.
In this case it is not clear what DNS servers to use and is difficult to get started... unfortunately this is the user's first experience with Docker (so not a good first impression!).

**Comment by phemmer** [comment]
See #14627 for a proposal on fixing this issue.

**Comment by LK4D4** [comment]
ping @mrjana @mavenugo @aboch @sanimej

**Comment by sanimej** [comment]
@LK4D4 This issue is not resolved yet. But since we have #14627 to track this requirement this can be closed.
