### ISSUE TITLE
`/sys` should be mounted readonly also in privileged containers

### ISSUE THREAD

**Issue by paulmenzel** [docker/docker#15973]
When using Docker 1.6.2 and a Debian 8.1 (Jessie) image, when running a Docker container (with the capability `SYS_ADMIN` added) from it with systemd 215-17+deb8u1, `/sys` is mounted initially with read-write permissions and is only later on switched to read-only by systemd (probably by systemd-remount-fs).

```
# grep sys /proc/self/mounts         
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=22,pgrp=1,timeout=300,minproto=5,maxproto=5,direct 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
# more /etc/fstab
# UNCONFIGURED FSTAB FOR BASE SYSTEM
# systemctl status systemd-remount-fs
● systemd-remount-fs.service - Remount Root and Kernel File Systems
   Loaded: loaded (/lib/systemd/system/systemd-remount-fs.service; static)
   Active: active (exited) since Mon 2015-08-31 17:55:19 CEST; 18h ago
     Docs: man:systemd-remount-fs.service(8)
           http://www.freedesktop.org/wiki/Software/systemd/APIFileSystems
  Process: 23 ExecStart=/lib/systemd/systemd-remount-fs (code=exited, status=0/SUCCESS)
 Main PID: 23 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/docker-7b835f5018853634c7ff0aadd4eb3aa884296950ed5f364bbd4db102c0f48660.scope/system.slice/systemd-remount-fs.service
[…]
```

**Comment by paulmenzel** [comment]
How does Docker mount `/sys` into a container? Does it do a bind-mount?

**Comment by paulmenzel** [comment]
### Bug Report Information

```
$ sudo docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
$ sudo docker info
Containers: 15
Images: 609
Storage Driver: btrfs
 Build Version: Btrfs v3.17
 Library Version: 101
Execution Driver: native-0.2
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 8
Total Memory: 30.5 GiB
Name: my-awesome-docker-server
ID: QDG3:62QH:GGBT:EOKC:XETS:RHFV:VXBL:P6X3:K5BM:UT4Q:7YEO:PWOE
WARNING: No memory limit support
WARNING: No swap limit support
$ uname -a
Linux my-awesome-docker-server 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux
```

**Comment by cpuguy83** [comment]
/sys is mounted ro for me except for when using `--privileged`.

**Comment by LK4D4** [comment]
@paulmenzel no, like `mount -t sysfs sysfs /sys`. It is indeed readonly for me too on master.

**Comment by paulmenzel** [comment]
Thank you for your answers.

What’s the reason for mounting it with read-write permissions when `--privileged` is used? That’s an unexpected side-effect.

**Comment by LK4D4** [comment]
@paulmenzel Because it's privileged. What the reason for mounting it read-only?

**Comment by cpuguy83** [comment]
@paulmenzel it is only `--privileged`.
Privileged is privileged. It means full host access.

**Comment by paulmenzel** [comment]
@cpuguy83, I know that. If user want to have it mounted with read-write permissions, they can remount it without any problems.

Is there a switch to tell Docker how to mount certain directories?

**Comment by LK4D4** [comment]
@paulmenzel You can bindmount your host /sys as ro volume inside. You can add `CAP_SYS_ADMIN` to unprivileged container with `--cap-add` also.

**Comment by paulmenzel** [comment]
@LK4D4, unfortunately that’s too late. As written in my report, `systemd-remount-fs` already does this, but that’s too late and udev is started nevertheless.

**Comment by LK4D4** [comment]
@paulmenzel Too late for what? volume with -v mounts at the same time as `/sys`, then `/sys` for you too late too.

**Comment by paulmenzel** [comment]
`systemd-remount-fs` seems to be run after `udev`. So that’s too late.

I am sorry, I did not fully grasp your second sentence.

**Comment by LK4D4** [comment]
@paulmenzel Could you ping me in irc `#docker-dev` on freenode, pls?

**Comment by cpuguy83** [comment]
Any update here?

**Comment by LK4D4** [comment]
I don't think it's bug.

**Comment by sanmai-NL** [comment]
Can it be closed then?

**Comment by paulmenzel** [comment]
I’ll close the bug, as there won’t be a conclusion.

For systemd compatibility I’d still believe, that it should only be mount read-only even in privileged mode. With that, systemd can easily tested in privileged mode, to help users to find out what is wrong, and not change systemd’s behavior in the process. Users needing write permissions can easily remount it writable.

Issue #18796 might be interesting for people wanting to run systemd inside a container.

Therefore, I’ll close this report.

**Comment by justincormack** [comment]
You should be able to run systemd with just `--cap-add sys_admin` (and maybe `--security-opt seccomp=unconfined` but this requirement should go away by 1.12), you should not need `--privileged`. In fact you may not need any privileges at all, some people have working non privileged setups.

**Comment by paulmenzel** [comment]
> You should be able to run systemd with just --cap-add sys_admin (and maybe --security-opt seccomp=unconfined but this requirement should go away by 1.12), you should not need --privileged. In fact you may not need any privileges at all, some people have working non privileged setups.

I don’t see how that is related to the issue at hand. I am well aware of that.

The point is, that if something does not work in a container, it’s a good practice to see if it works in a privileged container to rule out any permission problems. The current behavior makes that hard, as systemd also changes behavior as it doesn’t recognize the container as a container, as currently systemd’s specification is violated.
