### ISSUE TITLE
Installation on OSX 10.11

### ISSUE THREAD

**Issue by VikramTiwari** [docker/docker#15987]
default machine can't boot-up in OSX 10.11

Error as shown in Kinematics:
```
/Applications/Docker/Kitematic (Beta).app/Contents/Resources/resources/docker-machine -D create -d virtualbox --virtualbox-memory 2048 default returned non zero exit code. Stderr: Converting from raw image file="stdin" to file="/Users/<redacted>/.docker/machine/machines/default/disk.vmdk"... Creating dynamic image with size 20971520000 bytes (20000MB)... Error creating machine: exit status 1 You will want to check the provider to make sure the machine and associated resources were properly removed.
```

**Comment by VikramTiwari** [comment]
```
docker version:
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      darwin/amd64
Get http:///var/run/docker.sock/v1.20/version: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
```

```
docker info:
Get http:///var/run/docker.sock/v1.20/info: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
```

```
uname -a
Darwin Vikrams-Air.local 15.0.0 Darwin Kernel Version 15.0.0: Wed Aug 26 19:41:34 PDT 2015; root:xnu-3247.1.106~5/RELEASE_X86_64 x86_64
```

Steps to reproduce:
Install docker on OSX 10.11 and do initial setup.

Result received: unable to launch default docker vm with error:
`/Applications/Docker/Kitematic (Beta).app/Contents/Resources/resources/docker-machine -D create -d virtualbox --virtualbox-memory 2048 default returned non zero exit code. Stderr: Converting from raw image file="stdin" to file="/Users/<redacted>/.docker/machine/machines/default/disk.vmdk"... Creating dynamic image with size 20971520000 bytes (20000MB)... Error creating machine: exit status 1 You will want to check the provider to make sure the machine and associated resources were properly removed.`

Expected result: A docker vm to spin up

I am using preview release of OSX El Captain which might be the primary reason for the bug.

**Comment by thaJeztah** [comment]
This could actually be an issue in VirtualBox, and looks like a dup of https://github.com/docker/machine/issues/1725#issuecomment-133660200 and https://github.com/docker/toolbox/issues/119

Can you check if updating VirtualBox resolves this for you?

**Comment by VikramTiwari** [comment]
Updating VirtualBox with the [test builds](https://www.virtualbox.org/wiki/Testbuilds) worked. Thanks!

**Comment by thaJeztah** [comment]
Great!
