### ISSUE TITLE
Docker Quickstart Terminal failing - OSX Yosemite

### ISSUE THREAD

**Issue by matfin** [docker/docker#15982]
I am following the steps as detailed in these instructions for [getting started](http://docs.docker.com/mac/step_one/) and I cannot proceed because of the following error.

````
STDERR: 
executing: /usr/local/bin/VBoxManage modifyvm default --nic2 hostonly --nictype2 82540EM --hostonlyadapter2 vboxnet1 --cableconnected2 on
STDOUT: 
STDERR: 
executing: /usr/local/bin/VBoxManage modifyvm default --natpf1 delete ssh
STDOUT: 
STDERR: VBoxManage: error: Code NS_ERROR_INVALID_ARG (0x80070057) - Invalid argument value (extended info not available)
VBoxManage: error: Context: "RemoveRedirect(Bstr(ValueUnion.psz).raw())" at line 1766 of file VBoxManageModifyVM.cpp

executing: /usr/local/bin/VBoxManage modifyvm default --natpf1 ssh,tcp,127.0.0.1,62658,,22
STDOUT: 
STDERR: 
executing: /usr/local/bin/VBoxManage startvm default --type headless
STDOUT: Waiting for VM "default" to power on...
VM "default" has been successfully started.

STDERR: 
Error creating machine: exit status 1
You will want to check the provider to make sure the machine and associated resources were properly removed.
Starting machine default...
exit status 1
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
Setting environment variables for machine default...



                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/


host is not running
docker is configured to use the default machine with IP 
For help getting started, check out the docs at https://docs.docker.com

default is not running. Please start this with docker-machine start default

````

More information that may be helpful

````
matfin$ docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      darwin/amd64
Get http:///var/run/docker.sock/v1.20/version: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
````

````
matfin$ uname -a
Darwin Matthews-MacBook-Pro-2.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64 
````

````
matfin$ docker -D info
Get http:///var/run/docker.sock/v1.20/info: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
````

I am trying to install and run docker my development Macbook Pro using OSX Yosemite.

To reproduce this issue, I am following the steps as outlined in the [getting started](http://docs.docker.com/mac/step_one/) guide.

I was getting this error before and from reading into various suggestions from other users, I removed my existing installation of Virtualbox and then re-ran the docker installer.

Has anyone else encountered this issue and if so, how did you overcome it?

**Comment by matfin** [comment]
On looking into this more, I think the issue might have been caused by Virtualbox. I had version 5.0.2 installed and this was also preventing Vagrant from working properly, so if anyone else has had the above issue I would suggest downgrading to version 5.0.0

**Comment by fromonesrc** [comment]
I'm having the same issue and downgrading to 5.0.0 doesn't fix.

```
docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      darwin/amd64
Get http:///var/run/docker.sock/v1.20/version: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
```

**Comment by matfin** [comment]
I couldn't get past this issue so what I did was kept my existing version of Virtualbox, installed ubuntu-trusty64 on it and then followed this guide to install Docker on that. 

I had heard from others that running Docker this way is much simpler. The guide can be found at http://www.liquidweb.com/kb/how-to-install-docker-on-ubuntu-14-04-lts/

**Comment by yunti** [comment]
There seems to be multiple issues created with docker not working on OS X - some have solved with updating to a virtual box test build (5.0.3) but however, 
 5.0.3 (r102467) didn't solve the issue for me . the default host still fails to start

Error is:

VT-x is disabled in the BIOS for both all CPU modes (VERR_VMX_MSR_ALL_VMX_DISABLED).

Result Code: 
NS_ERROR_FAILURE (0x80004005)
Component: 
ConsoleWrap
Interface: 
IConsole {872da645-4a9b-1727-bee2-5585105b9eed}

Hmmm in the virtual box settings mentioned by yuan78 . I can't see an option for VTX for the CPU. And I can only select 32bit version of Linux there are no 64 bit options for some reason?

update: I believe the vtx option for the cpu is under acceleration (under system) this is greyed out for me, so it looks like this version of virtual box is pretty broken.

my details:

Study:~ $ docker version
Client:
Version: 1.8.1
API version: 1.20
Go version: go1.4.2
Git commit: d12ea79
Built: Thu Aug 13 02:49:29 UTC 2015
OS/Arch: darwin/amd64
Get http:///var/run/docker.sock/v1.20/version: dial unix /var/run/docker.sock: no such file or directory.

Are you trying to connect to a TLS-enabled daemon without TLS?
Is your docker daemon up and running? Study:$ docker info Get http:///var/run/docker.sock/v1.20/info: dial unix /var/run/docker.sock: no such file or directory.
Are you trying to connect to a TLS-enabled daemon without TLS?
Is your docker daemon up and running? Study$ uname -a Darwin Study_Pc.home 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64 Study_Pc:$

**Comment by thaJeztah** [comment]
@yunti I'm not sure your issue is related; @matfin is able to run VirtualBox, whereas in your situation I don't think the VirtualBox VM actually starts?

For the `VT-X` problem, I created two issues to track improvements to the documentation (https://github.com/docker/docker/issues/16182) and the Toolbox installer (https://github.com/docker/docker/issues/16182)

**Comment by cpuguy83** [comment]
Ok, closing this since it looks like a toolbox issue, and is being dealt with in the mentioned issues.

Thanks!
