### ISSUE TITLE
Docker "volume create" doesn't error on conflicting options

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#15998]
When creating a volume, `docker volume create` should produce an error if a conflicting option is provided. Currently the conflicting option is silently ignored

```bash
$ docker volume create --name myvolume
myvolume
$ docker volume create --name myvolume --driver convoy
myvolume
```

**expected result**

```bash
$ docker volume create --name myvolume
myvolume
$ docker volume create --name myvolume --driver convoy
Error: cannot create volume 'myvolume' using the 'convoy' driver because ... (some description)
```

**Comment by cpuguy83** [comment]
Yep, this is because create just currently returns the volume it already new about.
This should be adjusted to error if `vol.DriverName()` != the requested driver.

**Comment by azurezk** [comment]
#dibs
