### ISSUE TITLE
Race condition causing 'a container has already joined the endpoint' 

### ISSUE THREAD

**Issue by dnephin** [docker/docker#15995]
Related to #14083
Very similar to  #15727, but in this case it's not as repeatable.

We're seeing a test in the compose test suite (`ServiceTest.test_scale_with_custom_container_name_outputs_warning`) fail frequently against docker 1.8.1 (docker is curled from https://get.docker.com/builds/Linux/x86_64/docker-1.8.1 on each run): https://jenkins.dockerproject.org/job/Compose-PRs/1208/console

```
ERROR: for 2  Cannot start container 95da47d874fa328c0d6585130237b82ab9ba495ccb462ce939ffcdd90becded0: a container has already joined the endpoint 
ERROR: for 3  Cannot start container c531de7a43481b59f02961554a65830f04076586a8695d829a06e185112d6489: a container has already joined the endpoint 
```

### Description of problem:

The test attempts to create 3 containers with the same name (in parallel). The expected result is that one container should be created and started, and the other two should fail. The test runs successfully occasionally, but fairly often we're seeing a failure case where one container is created, but fails to start. 

```
$ docker inspect custom-container | jq '.[].State'
{
  "FinishedAt": "0001-01-01T00:00:00Z",
  "StartedAt": "0001-01-01T00:00:00Z",
  "Running": false,
  "Paused": false,
  "Restarting": false,
  "OOMKilled": false,
  "Dead": false,
  "Pid": 0,
  "ExitCode": 128,
  "Error": "a container has already joined the endpoint"
}
```

### Expected result

One container should be created and started

### Actual result

The one container was created but it failed to start

### Steps to Reproduce

```
parallel docker run --name duplicate -d alpine:edge sleep ::: 2 2 2 2
```

It will fail 25%-75% of the runs.

Running it against a `docker-machine` virtualbox with no containers doesn't trigger the error, so it may need a few containers to trigger the issue.

**Comment by dnephin** [comment]
Updated the steps to reproduce to use docker-cli instead of the compose test suite.

**Comment by thaJeztah** [comment]
ping @mavenugo

**Comment by dnephin** [comment]
The compose build is now hitting this pretty frequently with 1.9.0rc1.

**Comment by mavenugo** [comment]
@mrjana is looking at this.

**Comment by mrjana** [comment]
@dnephin I've tried the following repro steps several times in 1.9rc1
```
parallel docker run --name duplicate -d alpine:edge sleep ::: 2 2 2 2
```
with various options on number of parallel jobs and number of container runs etc. But did not see the problem even once. Can you please point me to the compose build logs where it is failing for you in 1.9rc1?

**Comment by dnephin** [comment]
The error message has changed in 1.9rc1, but the result is the same. The new error is "container already connected to network bridge"

https://jenkins.dockerproject.org/job/Compose-PRs/1650/console
https://jenkins.dockerproject.org/job/Compose-PRs/1651/console
https://jenkins.dockerproject.org/job/Compose-PRs/1648/console

I was able to reproduce this error with the parallel command when running locally on most runs.

**Comment by mrjana** [comment]
@dnephin I am pasting the relevant logs from one of the janky runs:
```
Creating and starting 1 ... 

Creating and starting 2 ... 

Creating and starting 3 ... 


Creating and starting 3 ... error

Creating and starting 1 ... error

Creating and starting 2 ... done

ERROR: for 1  Cannot start container 6aa1cd1237df032c1f0c42d0c3a17f29acc324126e008d6dce8d2543fd5a742d: container already connected to network bridge 
ERROR: for 3  Cannot start container 90436aa36668c3162a5b93735c6cc55a0044d3a7eae95f02e2eabcd45e2f7372: container already connected to network bridge 
```

I am assuming you are trying to create 3 containers with the same name. And looks like one is succeeding and the other two is erroring out. If that is what the test is doing, then that is expected. Am I misunderstanding the test case?

**Comment by thaJeztah** [comment]
@dnephin this should be fixed in master now, so if you could give that a test, that'd be great!

**Comment by dnephin** [comment]
Yup, looks good. Thanks for the fix!
