### ISSUE TITLE
Many / most errors with v2 API are hidden in DEBUG level messages and covered up by "unsupported v1 endpoint"

### ISSUE THREAD

**Issue by stevenschlansker** [docker/docker#15993]
We now have isolated three separate issues relating to the v2 api.  I've filed separate tickets, this is not about those issues specifically, but the extremely poor error reporting.  For example we have the conversation:

```
[steven@Anesthetize:~]% docker pull docker.otenv.com/ot-ubuntu:231
231: Pulling from ot-ubuntu
0ab1c2a05ab9: Extracting [> ] 1.671 MB/96.06 MB
Pulling repository docker.otenv.com/ot-ubuntu
Error: Status 400 trying to pull repository ot-ubuntu: "{\n \"errors\" : [ {\n \"status\" : 400,\n \"message\" : \"Unsupported docker v1 repository request for 'docker-v2'\"\n } ]\n}"
```
And the daemon logs:
```
ESC[34mINFOESC[0m[0717] POST /v1.20/images/create?fromImage=docker.otenv.com%2Fot-ubuntu%3A231
ESC[31mERROESC[0m[0724] error copying from layer download progress reader: download canceled 
```

Neither the client nor the daemon actually get any helpful error message, the actual error is not found until you restart your daemon with `-D` and find:

```
ESC[37mDEBUESC[0m[0008] Error trying v2 registry: ApplyLayer exit status 1 stdout:  stderr: archive/tar: invalid tar header 
```

* Once a v2 operation starts, we should never fall back to v1.  Only if v2 is not supported at all.  Or at least the final error message sent back to the client should prefer the v2 error, not some unhelpful "v1 not supported"
* Every failure in the v2 api client should be threaded back to the Docker client level; end users shouldn't be expected to trawl through daemon logs, or especially having to restart the daemon at debug level just to find out why a pull failed.

**Comment by HuKeping** [comment]
I think #16385 will solve this?

**Comment by stevenschlansker** [comment]
Partly?  It will at least eliminate the v1 fallback messages, although the "actual errors hidden at DEBUG level" would still be a separate problem.

**Comment by RichardScothern** [comment]
The error reporting is not ideal.  Which registry versions are you running against?  

I'm slightly confused as to where `Unsupported docker v1 repository request for 'docker-v2'` is coming from

**Comment by stevenschlansker** [comment]
That is the error message Artifactory's Docker support produces when asked via the v1 API, which it no longer supports.

**Comment by RichardScothern** [comment]
Ah, OK.  What error causes the fallback to v1 here during the pull?

**Comment by stevenschlansker** [comment]
In this case, it was a problem with the 1.8.1 release which created invalid layers that could not be extracted.  But this behavior seems to happen independent of which error is triggered.

**Comment by thaJeztah** [comment]
@RichardScothern were you still looking into this?

**Comment by BoJoe22** [comment]
+1  I get the exact same issues when using Artifactory's Docker support.

**Comment by e-nouri** [comment]
+1 Same bug for Artifactory and Docker.

**Comment by thaJeztah** [comment]
@BoJoe22 @e-nouri does setting `--no-legacy-registry` on the daemon solve this? I mentioned it above, but not sure if that'd fully solve the issue, given @stevenschlansker's comment

**Comment by e-nouri** [comment]
@thaJeztah was kinda of a dumb error the arg parser is too stronk ! In the logs it kept saying:

flag provided but not defined: --insecure-registry 10.0.0.0/8
See '/usr/bin/docker daemon --help'

after I added the equal '=' I was able to restart the docker daemon.
DOCKER_OPTS="$DOCKER_OPTS --dns='10.248.2.1' --insecure-registry='10.0.0.0/8'"

**Comment by LK4D4** [comment]
Not sure if it was addressed.
ping @stevvooe @aaronlehmann @dmcgowan

**Comment by aaronlehmann** [comment]
This seems a lot better than it used to be.

`Error trying v2 registry` is a `logrus.Errorf` now.

I looked around and the only other debugging log lines I see that should arguably be errors instead are in the v1 protocol code, which is very seldom used and only exists for backward compatibility.

We can probably close this.

**Comment by LK4D4** [comment]
@aaronlehmann Thanks!
