### ISSUE TITLE
`docker volume` does not track plugins over a restart

### ISSUE THREAD

**Issue by erikh** [docker/docker#15994]
Steps to reproduce; you'll need a volume plugin to test.

* `docker volume create -d myplugin --name test`
* `docker volume ls`
* `docker run --name foo -it -v test:/mnt ubuntu bash`
* `docker inspect foo` # note that the driver is set to `local`, not `myplugin`
* restart docker
* `docker volume ls` # the driver should say local now
* `docker rm foo` # hangs trying to delete a volume that doesn't exist

/cc @cpuguy83 @shaleman @jainvipin @srust

**Comment by srust** [comment]
Also reproduced in: https://gist.github.com/srust/88b53f1e85814fdb2662

**Comment by thaJeztah** [comment]
Just tested this, and confirmed

**Comment by cpuguy83** [comment]
fixed in #15999
