### ISSUE TITLE
Docker -it inside Tmux doesn't work with text editors

### ISSUE THREAD

**Issue by jberkus** [docker/docker#16000]
If I call docker -it from inside Tmux, the session exhibits several text display issues.  Most notably, scrolling and text display inside text editors is mangled, making it impossible to use them.

Tested on: 1.5, 1.7.1
Editors tested: emacs, nano, joe

Steps to reproduce:

1. start a tmux session
2. run "docker -it --rm ubuntu:trusty"
3. apt-get install nano
4. nano /etc/init.d/networking
5. scroll down 3 screens or so
6. you'll see lines of text get mangled.

Workarounds:

* don't start docker -it in tmux

This is a problem because:

* I use tmux to test things inside several containers on our build server, which limits the number of SSH connections I can have.
* Other sysadmins have similar needs

May be related to:

Issue #8755

System Info:
Linux 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 

GNU/Linux
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64

josh@g:~/patroni$ docker -D info
Containers: 7
Images: 40
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 54
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-32-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 4
Total Memory: 7.797 GiB
Name: g
ID: XQ6U:LWIO:ASG5:564C:WHFL:Y2QG:QTZA:L6PG:EFPS:6EDW:3DCD:CW7X
WARNING: No swap limit support

**Comment by tianon** [comment]
This sounds kind of similar to #5379, actually.  Have you tried adding `-e TERM` to your `docker run` commands to see if it makes a difference? (ie, `docker run -it -e TERM image command`)

**Comment by MHBauer** [comment]
Can confirm it for nano on 1.8.1, and that running with -e TERM fixes it.

```
root@node-1:~# docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

# echo $TERM
screen
```

hth

**Comment by jberkus** [comment]
I've confirmed -e TERM to work in several environments, including tmux on the remote host and tmux on the local host, with both nano and joe.  So, closing this.  Thanks!

**Comment by thaJeztah** [comment]
Thanks for testing/confirming, @jberkus
