### ISSUE TITLE
curl install error

### ISSUE THREAD

**Issue by wplatform** [docker/docker#16003]
when install docker on ubuntu14.04, using curl -sSL https://get.docker.com/ | sh
an error occurred:  curl: (35) Unknown SSL protocol error in connection to get.docker.com:443 
http://docs.docker.com/installation/ubuntulinux/

**Comment by Evalle** [comment]
Hello @wplatform can you provide your curl and openssl versions ? (e.g. curl --version and ssl --version) I believe that it's a known bug with curl.
