### ISSUE TITLE
Allow pulling multiple images at once

### ISSUE THREAD

**Issue by dgommeren** [docker/docker#16019]
With docker stop, start, rm etc. you can specify multiple containers, but docker pull can only specify one container. It would be convenient if you could specify multiple containers, eg:

docker pull ubuntu centos redhat

**Comment by tobegit3hub** [comment]
It seems that docker supports to pull multiple images at the same time after 1.10.

I'm not sure we still need this.

**Comment by thaJeztah** [comment]
@tobegit3hub see https://github.com/docker/docker/issues/16106#issuecomment-208266482, but thanks for commenting, looks like this is a duplicate.

@dgommeren I'll close this issue as a duplicate of https://github.com/docker/docker/issues/16106, which was created later, but has a more active discussion. Please subscribe to that issue to keep up to date
