### ISSUE TITLE
Version problems

### ISSUE THREAD

**Issue by ggerman** [docker/docker#16021]
docker-machine create -d virtualbox dev
  docker run busybox echo hello world

 eval $(docker-machine env dev)
 Error response from daemon: client is newer than server (client API version: 1.21, server API version: 1.20)

Docker running without docker-machine

 docker version
Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   3111aa7
 Built:        Tue Sep  1 20:35:25 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   3111aa7
 Built:        Tue Sep  1 20:35:25 UTC 2015
 OS/Arch:      linux/amd64

**Comment by cpuguy83** [comment]
Yes, your client cannot have a newer version than the running daemon.
Downgrade your client to 1.8.1.
