### ISSUE TITLE
a question regarding docker building structure

### ISSUE THREAD

**Issue by michael4RD** [docker/docker#16033]
Hi,

I may be asking a naive question here: we are using "hack/make.sh" to compile docker source code (inside a new container), but it is not clear (at least to me) how those go source files are compiled all together (no Makefile/Scons file inside subdir). This prevents me from adding new go file and functionality to the existing docker source code. I could not locate any document on this issue as well.

Any comment would be very helpful here.

Thanks,

**Comment by duglin** [comment]
@michael4RD you may find it easier to follow if you just do "make binary" at the top of the source tree. See the `Makefile` and `Dockerfile` at the root of the tree for more info.

**Comment by duglin** [comment]
Closing this since its not really an issue (ala bug) - you might want to ask on the Google docker mailing list next time: https://github.com/docker/docker#talking-to-other-docker-users-and-contributors

**Comment by michael4RD** [comment]
Oh I see. Sorry for the inconvenience. I will use the Google docker mailing list next time. Thanks.
