### ISSUE TITLE
Make Docker More Robust to Network Changes

### ISSUE THREAD

**Issue by burhan** [docker/docker#16044]
``docker -v 1.7.1, build 3043001/1.7.1``

I am evaluating docker using RHEL7; running in VMWare.

All I did was rename the primary connection name from `eno167777736` to something sensible like `eth0`.

After making this simple change; docker refuses to start with:

``Running modprobe bridge nf_nat br_netfilter failed with message: , error: exit status 1``

**Comment by cpuguy83** [comment]
@burhan The error message is about loading a kernel module, and even then it's just a warning (at least on master).

**Comment by LK4D4** [comment]
Going to close it, because there are no logs provided. Feel free to open new issue.
