### ISSUE TITLE
docker run --rm -ti debian:jessie cat hangs

### ISSUE THREAD

**Issue by nornagon** [docker/docker#16040]
```
$ echo hi | docker run -ti debian:jessie cat
# The above quits instantly, without even printing "hi"
$ echo hi | docker run --rm -ti debian:jessie cat
# hangs forever.
```

Am I doing something dumb? I'm on docker 1.0.1 on ubuntu 14.04.

```
$ uname -a
Linux 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Evalle** [comment]
Hello @nornagon. 

I don't think that it's an issue in docker. if you want to run `echo "hi"` command inside your docker container you need to run ```sudo docker run -ti debian:jessie echo "hi"```

And BTW it's a good idea to use last version of docker. Docker 1.0.1 is quite old now :)

**Comment by phemmer** [comment]
That is definitely an issue with docker. However I will second that 1.0.1 is really old. Current docker versions won't even let you do that with the `-t` flag, but work fine without it:

    # echo hi | docker run -ti debian:jessie cat
    cannot enable tty mode on non tty input

    # echo hi | docker run -i debian:jessie cat
    hi

    # echo hi | docker run --rm -i debian:jessie cat 
    hi

^with docker 1.7.0

**Comment by Evalle** [comment]
My fault. 
I can confirmed that with 1.8.1 version of docker this command works as well.
```
evgeny ~/Downloads $ echo hi | docker run -i debian:jessie cat
hi
evgeny ~/Downloads $ docker --version
Docker version 1.8.1, build 786b29d
```

**Comment by nornagon** [comment]
Ah, I see there's no way to combine -t with piping stuff in to stdin. I was
hoping to get a docker process that I could pipe things to on stdin and
kill with SIGINT/SIGTERM after a timeout—`docker run --rm -i` doesn't seem
to correctly kill the process inside the container when it itself receives
SIGTERM.

**Comment by cpuguy83** [comment]
@nornagon docker only forwards signals to the first process of the container. It is up to the process to handle the signal properly.

Confirmed `echi hi | docker run -i --rm debian:jessie cat` exits as expected.
