### ISSUE TITLE
get rid of reprepro

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#16050]
this is a reminder to myself to make the pr to remove reprepro since really we are now just using it as a glorifed way to get the deb into the pool

**Comment by jfrazelle** [comment]
also TODO: prehaps making a tool named `reprepPRO` 

bah dum chhhhh

cc @tianon

**Comment by tianon** [comment]
yesss, so good

cc @paultag (`reprepPRO` as a new tool, because @jfrazelle is a comedic genius)
