### ISSUE TITLE
Windows: Needs an implementation of system.Utimesnano

### ISSUE THREAD

**Issue by jhowardmsft** [docker/docker#16051]
#16027

**Comment by jhowardmsft** [comment]
Gordon, be quiet!

**Comment by darrenstahlmsft** [comment]
#dibs

**Comment by LK4D4** [comment]
@jhowardmsft @darrenstahlmsft How is your new hire, lol? :D

**Comment by darrenstahlmsft** [comment]
This was actually fixed by my first PR (Adding Chtimes as the method of changing file times instead of Utimesnano), I just didn't link it back to the issue. Oops. :innocent: https://github.com/docker/docker/pull/16490

**Comment by LK4D4** [comment]
@darrenstahlmsft Thanks! closing!
