### ISSUE TITLE
1.8.1 - Client and server don't have same version (client API version: 1.20, server API version: 1.19)

### ISSUE THREAD

**Issue by moylop260** [docker/docker#16059]
Steps to reproduce:
 1. Create a ubuntu14.04 container --privileged
 2. Install docker 1.7
 3. Remove and purge docker 1.7
 4. Install docker 1.8.1
 5. Exeucte docker version

Saw:
```bash
# docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64
Error response from daemon: client and server don't have same version (client API version: 1.20, server API version: 1.19)
```

Expected:
Without error
`Error response from daemon: client and server don't have same version (client API version: 1.20, server API version: 1.19)`

Video with steps number 3 to 5:
 https://asciinema.org/a/25937

**Comment by duglin** [comment]
can you paste the exact commands you used to install/purge/etc.... ?

**Comment by moylop260** [comment]
Thank for reply
From asciinema video you can copy and paste, let me paste it here...

**Comment by moylop260** [comment]
Commands used:
```bash
echo "Checking current linux and docker version" && sleep 3 && \
docker version && lsb_release -a

echo "Purge lxc" && sleep 3 && \
apt-get autoremove --purge lxc

echo "Purge lxc*" && sleep 3 && \
apt-get purge lxc*

echo "Cleaning apt list" && sleep 3 && \
apt-get clean && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*

echo "Installing new docker version" && sleep 3 && \
curl -sSL https://get.docker.com/ | sh
```

**Comment by Pensu** [comment]
If you are using boot2docker, you can try to upgrade it. That solves the problem.

**Comment by moylop260** [comment]
I'm not using boot2docker...
I'm using docker --privileged directly...
I will create a travis test with my problematic image with the upgrade...

**Comment by moylop260** [comment]
I have created next project to test this isse:

https://github.com/moylop260/docker-api-error

And generated next travis build:
https://travis-ci.org/moylop260/docker-api-error/builds/79079860

Now, the issue is fixed!

**Comment by thaJeztah** [comment]
@moylop260 note that, with docker 1.8+ you may not even need the dind things; see this PR https://github.com/docker/docker/pull/15596

**Comment by moylop260** [comment]
@thaJeztah 
Ok, I got it!
Thank you for the information!

**Comment by moylop260** [comment]
@all 
FYI If you have the same problem you can fixed with:
`# docker stop dkr-in-dkr-container`
`# docker start dkr-in-dkr-container`
And wait 1 minute to try again.

The problem is when you have previous images downloaded from 1.7 and upgrade to 1.8 without reboot

**Comment by postalC** [comment]
@moylop260 
Noted, thanks alot

**Comment by facaitu** [comment]
$ sudo apt-get update
$ sudo apt-get install -t wheezy-backports linux-image-amd64
$ curl -sSL https://get.docker.com/ | sh
that is all
no thanks!

**Comment by kratzlo** [comment]
@facaltu runs perfectly
