### ISSUE TITLE
kill SIGSTOP and SIGCONT removing container

### ISSUE THREAD

**Issue by tolmasky** [docker/docker#16077]
I am attempting to send SIGSTOP and SIGCONT to containers as so:

    docker kill -s STOP
    docker kill -s CONT

This line makes me believe this will behave as I expect: https://github.com/docker/docker/issues/5948#issuecomment-43684471

But what I'm seeing is that the containers are being removed. Am I missing some option to make it just send the signal and not remove the container?

**Comment by cpuguy83** [comment]
How are you seeing that the containers are removed?

Docker is definitely not supposed to be removing containers with `docker kill`... and `docker stop` is a wrapper around `docker kill`, really.

**Comment by tolmasky** [comment]
I'm doing docker kill -s STOP/CONT and then the container stops showing up in docker ps.

**Comment by cpuguy83** [comment]
What about "docker ps -a"?
You should also look at "docker pause" and "docker unpause"  if you are trying to freeze your processes.

**Comment by Pensu** [comment]
@tolmasky  I am doing the same, but I can see containers in "docker ps". I am using docker 1.8.0. What version are you using?

**Comment by jonathanperret** [comment]
@cpuguy83 , there's at least a line here: https://github.com/docker/docker/blob/26b1064967d9fcefd4c35f60e96bf6d7c9a3b5f8/daemon/container.go#L376 that likely makes it problematic to use `docker kill` as a harmless-signal-sending mechanism:

```go
	// signal to the monitor that it should not restart the container
	// after we send the kill signal
	container.monitor.ExitOnNext()
```

(I actually just went looking for an issue like this one because I stumbled upon that line).

**Comment by jonathanperret** [comment]
…although this could just be #13665 . Still worried about that line, though.

**Comment by LK4D4** [comment]
Looks like works now.
