### ISSUE TITLE
docker volume vs docker volume ls

### ISSUE THREAD

**Issue by vieux** [docker/docker#16070]
I see `docker volume` is a shortcut to `docker volume ls`

Is it expected ? if so I think `docker volume` should support the `docker volume ls` flags, like:

`docker volume -q` so we could do 

```
docker volume rm `docker volume -q`
```

**Comment by vieux** [comment]
ping @cpuguy83

**Comment by cpuguy83** [comment]
Yes it is expected.
If you do `docker volume` you get `ls`, `docker volume <invalid subcmd>` shows the help message for the `docker volume` subcommand (which lists all the volume sub commands).

Agreed, it should support the flags.

**Comment by vieux** [comment]
@cpuguy83 any update ton this ? Thanks.

**Comment by cpuguy83** [comment]
Looks like @azurezk is addressing in #16210
