### ISSUE TITLE
SOCKS support for docker client

### ISSUE THREAD

**Issue by PerilousApricot** [docker/docker#16083]
Supporting access to tcp:// docker ports over SOCKS is necessary to access docker-machine hosts that are on the other side of a ssh bastion host. With most other applications, this works by starting a SOCKS tunnel via ```ssh -D <port> bastion.host``` and setting the environment variable ```all_proxy=socks5://localhost:<port>```. Poking at Go's proxy support and docker's usage of it, only http:// proxies are supported.

Tidying this up will make using docker-machine on private clouds doable without a ton of manual handholding.

**Comment by cpuguy83** [comment]
I am absolutely certain this is a dup... but GH search is being terrible.

**Comment by PerilousApricot** [comment]
I was surprised to not find an issue about it. I even plowed through some
google searches for different variations of "docker socks" and came up
empty handed.

-- 
Sent from Gmail Mobile

**Comment by cpuguy83** [comment]
Here we go, thank you google: #5989
Closing as this is a dup.
