### ISSUE TITLE
Can't docker pause from within a container

### ISSUE THREAD

**Issue by tolmasky** [docker/docker#16093]
I can docker pause just fine from the host machine:

    sudo docker pause container1

However, if I enter another container and try to pause container1, I get the following error:

    docker exec -it container2 bash
    docker pause container1 (in container2)

 ---> Cannot pause container container1: open /sys/fs/cgroup/freezer/docker/e045e46773783c32c9038cb835864c2ecf526b5f547ed5c7811c5fe609e6a661/freezer.state: no such file or directory

From the tests it seems like I should be able to do this, but perhaps I'm missing something.

`docker version`: Client version: 1.6.1
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 97cd073
OS/Arch (client): linux/amd64
Server version: 1.6.1
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 97cd073
OS/Arch (server): linux/amd64
`uname -a`: Linux vagrant 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by aidanhs** [comment]
Seems ok for me:
```
/space/dock/runc $ docker run -d ubuntu:14.04.3 sleep 6000                          
2cd31305ea6644290866075f1518a6719e26e774df979480e41e937c319e4d69
/space/dock/runc $ docker pause 2cd3
2cd3
/space/dock/runc $ docker unpause 2cd3                                              
2cd3
/space/dock/runc $ docker run --name c2 ubuntu:14.04.3 sleep 6000
/space/dock/runc $ docker run --name c2 -v /var/run/docker.sock:/var/run/docker.sock -v /usr/bin/docker:/usr/bin/docker ubuntu:14.04.3 sleep 6000
/space/dock/runc $ docker run --name c2 -d -v /var/run/docker.sock:/var/run/docker.sock -v /usr/bin/docker:/usr/bin/docker ubuntu:14.04.3 sleep 6000
c46f3021d70df9fc9990b7cb5bbfa32a8164c1c4e0aab8b9ea61e14d5449dd9b
/space/dock/runc $ docker exec -it c2 bash
root@c46f3021d70d:/# docker pause 2cd3
2cd3
```

I'm on 1.7.1. Have you tried upgrading?

**Comment by calavera** [comment]
Yep, this works as expected in 1.8.2 too. Also, don't forget that you have to mount docker's socket, like @aidanhs is doing in his example.

Closing this. Please, feel free to reopen if you upgrade to 1.8.2 and still find issues following the previous example.
