### ISSUE TITLE
docker-engine install error on CentOS 7.1

### ISSUE THREAD

**Issue by smuthali** [docker/docker#16097]
Hello experts,

I am unable to install docker-engine on CentOS 7.1, unless I modify the installer.

Here’s the OS details:
```
[root@tsi-ngx1-wus ~]# cat /etc/redhat-release
CentOS Linux release 7.1.1503 (Core)

[root@tsi-ngx1-wus ~]# uname -a
Linux tsi-ngx1-wus 3.10.0-229.11.1.el7.x86_64 #1 SMP Thu Aug 6 01:06:18 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

[root@tsi-ngx1-wus ~]# uname -r
3.10.0-229.11.1.el7.x86_64

[root@tsi-ngx1-wus ~]# uname -srvim
Linux 3.10.0-229.11.1.el7.x86_64 #1 SMP Thu Aug 6 01:06:18 UTC 2015 x86_64 x86_64
```
Environment details:
Type: VM
Infrastructure: MS Azure

When I attempt to install docker-engine
```
[root@tsi-ngx1-wus ~]# curl -sSL https://get.docker.com/ | sh

+ sh -c 'sleep 3; yum -y -q install docker-engine'


File contains parsing errors: file:///etc/yum.repos.d/docker-main.repo
	[line  4]: 7

Check the repo contents:

[root@tsi-ngx1-wus ~]# cat /etc/yum.repos.d/docker-main.repo
[docker-main-repo]
name=Docker main Repository
baseurl=https://yum.dockerproject.org/repo/main/centos/7
7 ===================================================> this causes the parse error
enabled=1
gpgcheck=1
gpgkey=https://yum.dockerproject.org/gpg
```

So, if we take a look at the installer ```(curl https://get.docker.com > installer.sh)```, specifically as to how ```dist_version``` is evaluated:
```
line 205:


                fedora|centos)
                         dist_version="$(rpm -q --whatprovides redhat-release --queryformat "%{VERSION}\n" | sed 's/\/.*//' | sed 's/\..*//' | sed 's/Server*//')"
                 ;;
```

Printing out ```$dist_version```
```
[root@tsi-ngx1-wus ~]# dist_version="$(rpm -q --whatprovides redhat-release --queryformat "%{VERSION}\n" | sed 's/\/.*//' | sed 's/\..*//' | sed 's/Server*//‘)"

[root@tsi-ngx1-wus ~]# echo $dist_version
7 7
```
Workaround:
Unless I modify it something like
```
dist_version="$(rpm -q --whatprovides redhat-release --queryformat "%{VERSION}\n" | sed 's/\/.*//' | sed 's/\..*//' | sed 's/Server*//‘)"
dist_version=${dist_version:0:1}
```
which will yield the desired result
```
[root@tsi-ngx1-wus ~]# echo $dist_version
7
```

Has anyone else run in to this?

**Comment by Djelibeybi** [comment]
What is the output of `rpm -q --whatprovides redhat-release --queryformat "%{VERSION}\n"` on that machine? On my test CentOS 7.1 Docker container it returns "7" which is appropriate, but obviously it's not returning that on your machine.

**Comment by smuthali** [comment]
Sure, and this is the problem
```
[root@tsi-ngx1-wus ~]# rpm -q --whatprovides redhat-release --queryformat "%{VERSION}\n"
7
7
```

**Comment by smuthali** [comment]
'''
[root@tsi-ngx1-wus ~]# rpm -q --whatprovides redhat-release
centos-release-7-0.1406.el7.centos.2.5.x86_64
centos-release-7-1.1503.el7.centos.2.8.x86_64
'''

**Comment by Djelibeybi** [comment]
There should only ever be one installed version of `centos-release`. You'll need to investigate why you have multiple versions installed.

**Comment by smuthali** [comment]
@Djelibeybi - yep, looking in to it.

**Comment by smuthali** [comment]
@Djelibeybi - looks like when I ran ```yum update``` the ```centos-release``` package did not get replaced.  I agree this is not a docker issue.

**Comment by Djelibeybi** [comment]
@smuthali yes, and I just tested a CentOS 7 VM upgrade from 7.0 to 7.1 and it worked fine, so something weird on your end.

**Comment by jfrazelle** [comment]
closing let me know if that was in error

**Comment by smuthali** [comment]
Hi Jess, nah we are good to close. It turned out that my CentOS 7.1 VM went nuts after a yum update.

Thanks
Satish
