### ISSUE TITLE
Proposal: Docker stats should default to showing stats for all running containers

### ISSUE THREAD

**Issue by shishir-a412ed** [docker/docker#16105]
Description of problem:
Currently 'docker stats' requires one or more container IDs/names in order to report said stats.

Running just 'docker stats' should imply the user wants to see stats for all currently running containers.

Version-Release number of selected component (if applicable):
docker-1.7.1-108.el7.x86_64

How reproducible:
Always

Steps to Reproduce:
1. Run 'docker stats' with no container IDs
2.
3.

Actual results:

No stats are shown:

# docker stats
docker: "stats" requires a minimum of 1 argument.
See 'docker stats --help'.

Usage: docker stats [OPTIONS] CONTAINER [CONTAINER...]

Expected results:

Stats for all running containers should be shown

Additional info:

Running 'docker stats $(docker ps -q)' serves this same function, so this more of an ease-of-use request.

**Comment by runcom** [comment]
this is a dup of #10772 which I'm working on to fix
I'm going to close this

**Comment by runcom** [comment]
PR is here #13227 but closed for now since I'm still working on it

**Comment by shishir-a412ed** [comment]
@runcom 
thanks !
