### ISSUE TITLE
https://apt.dockerproject.org  is down ?

### ISSUE THREAD

**Issue by William-Sang** [docker/docker#16101]
<img width="434" alt="qq20150906-1 2x" src="https://cloud.githubusercontent.com/assets/4018929/9703393/808163ea-54b5-11e5-989e-26da1dfee3ab.png">

**Comment by advanderveer** [comment]
My 2 cents: seems like some automated script somewhere in the world nukes the apt.dockerproject.org every sunday. see reports every week in this issue: #15616

**Comment by jkehler** [comment]
Just chiming in here for more visibility on how many users this issue is affecting on Sunday. I'm getting the same 503 message as well. Perhaps a mirror is in order?

**Comment by William-Sang** [comment]
@advanderveer  You'r probably right  -_-! Nothing can do about it.

**Comment by William-Sang** [comment]
@jkehler  +1

**Comment by Micka33** [comment]
Can't install docker on my ubuntu machine because of it. This need to be fixed with something like a maximum requests/sec or something.
```
$ curl https://apt.dockerproject.org/

<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 Connection refused</title>
  </head>
  <body>
    <h1>Error 503 Connection refused</h1>
    <p>Connection refused</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-lhr6331-LHR 1441537303 3413366959</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
```

**Comment by thaJeztah** [comment]
This is just a workaround, but statically compiled binaries can still be downloaded.

Instructions for finding the right URLs can be found here; https://docs.docker.com/installation/binaries/#get-the-linux-binary

**Comment by Evalle** [comment]
https://apt.dockerproject.org is not working for me too. So +1.

**Comment by thaJeztah** [comment]
Yup, it's down; probably no need to add more "+1"'s. Unfortunately, if 5:45AM on a Sunday now in San Francisco, so we'll have to be patient for now. 

/cc @jfrazelle

**Comment by approxit** [comment]
+1 :sob:

**Comment by pdericson** [comment]
Guys, I gave you the benefit of the doubt when I raised #15616 - time to get serious now, with the amount of money being poured into Docker Inc apt and yum repos can't be managed by volunteers on a best effort basis.

**Comment by alex-sherwin** [comment]
+1

Definitely expect installation repo's to stay online.. 5+ hours?

**Comment by stenote** [comment]
+1

```
Err https://apt.dockerproject.org ubuntu-trusty/main amd64 Packages
  HttpError503
Err https://apt.dockerproject.org ubuntu-trusty/main i386 Packages
  HttpError503
Hit http://security.ubuntu.com trusty-security/universe Translation-en
W: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-trusty/main/binary-amd64/Packages  HttpError503

W: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-trusty/main/binary-i386/Packages  HttpError503

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by RaymondKlass** [comment]
+1

**Comment by vstepanyuk** [comment]
still down

**Comment by vstepanyuk** [comment]
https://mirrors.ustc.edu.cn/apt.dockerproject.org/repo/dists/ubuntu-vivid/main/binary-amd64/Packages

**Comment by jfrazelle** [comment]
its back up and if people could _not_ set up faulty cron jobs that ping us at hundreds of thousands of requests per second that would be great.

**Comment by pdericson** [comment]
@jfrazelle I wonder if it a single very large organisation doing a schedule "apt-get update" behind a single NAT'd IP address that's causing the problem?  Varnish doesn't seem to mind, it stays up, what do you have behind varnish?  nginx in a container?  a rails app?  I would expect apt and yum repos to be absolutely hammered 24/7 based on the popularity of docker.

**Comment by jfrazelle** [comment]
It is hammered 24/7 but gets nuked like this morning sometimes and from various IPs at once so it could be an entire org doing a cron... But it would have to be a verrrryyy large org to cause the surge and ip range which I will look into when it's not the weekend lol but ya be get around 2.5 million hits on a normal day so we see some traffic ;) and behind varnish are a few nginx containers, but when the cache gets missed when we are nuked then it's bad (to be totally transparent)






On Sun, Sep 6, 2015 at 5:27 PM -0700, "Peter Ericson" <notifications@github.com> wrote:












@jfrazelle I wonder if it a single very large organisation doing a schedule "apt-get update" behind a single NAT'd IP address that's causing the problem?  Varnish doesn't seem to mind, it stays up, what do you have behind varnish?  nginx in a container?  a rails app?  I would expect apt and yum repos to be absolutely hammered 24/7 based on the popularity of docker.

**Comment by jfrazelle** [comment]
So in this instance rate limiting wouldn't really do much

**Comment by jfrazelle** [comment]
Also we have pager duty set up and I slept through like 7 phone calls, so yeah, how's that for a post mortum, I need like an old school pager lol

**Comment by pdericson** [comment]
Well fwiw I would have probably gone with varnish in a net host container backed by nginx in containers and I have never had to deal with that kind of load. I do find the problem interesting - it's a good example of docker at extreme scale. Can I ask, when people are getting 503s is it because their is not enough backends to service the request (assume there is X backends which varnish is allow to give Y concurrent connections to) or are the nginx containers themselves spiralling out of control?

**Comment by jfrazelle** [comment]
We use fastly for varnish

**Comment by jfrazelle** [comment]
And the 503 is because there is no where for the requests to go, I'm going to adjust the cache settings but the cache should handle the problems like this morning it should not be annihilating the backends

**Comment by advanderveer** [comment]
Cool, thanks jess!

**Comment by jfrazelle** [comment]
For anyone who is interested,
After parsing all the unique ips, turns out about 80% of them were
from Digital Ocean. Which lead us to discover, the DigitalOcean
pre-configured Docker server has a DAILY cron job to run an apt-get
update, which hits our servers.

A LOT of people have these servers apparently but the interesting thing is
this cron job is DAILY. So on a normal day this works but on this Sunday
varnish for some reason broke the contract w how many requests it can serve
to each backend.

I have also updated our varnish config to better serve stale content if
this ever happens again.

**Comment by jfrazelle** [comment]
Long story short we are actually handling hundreds of thousands of requests
per second every night :P

**Comment by rutsky** [comment]
@jfrazelle, is apt.dockerproject.org accessibility solved and how?

I have Ubuntu image on DigitalOcean and can't access apt.dockerproject.org (but can access from my computer).
Is DigitalOcean IPs were simply banned and there is no way to use `apt-get update`/`apt-get install` from DigitalOcean machines?

**Comment by thaJeztah** [comment]
@rutsky Just checked, and I'm able to access the repository from my DigitalOcean machines (AMS3)

**Comment by rutsky** [comment]
@thaJeztah, my droplet in AMS2 region. Machine IP in 188.226.255.255/20 range.

```
# curl --connect-timeout 10 apt.dockerproject.org
curl: (28) Connection timed out after 10000 milliseconds
#
```

**Comment by jfrazelle** [comment]
Can you try curling dockerproject.org in general?

**Comment by rutsky** [comment]
> Can you try curling dockerproject.org in general?

Sure! Works:

```
# curl -s -I -w "%{http_code}\n" -o /dev/null https://dockerproject.org
200
# curl -s -I -w "%{http_code}\n" -o /dev/null docs.master.dockerproject.org
200
```

Doesn't:

```
# curl --connect-timeout 2 https://docker.io
curl: (7) Failed to connect to docker.io port 443: Connection timed out
# curl --connect-timeout 2 https://www.docker.com
curl: (28) Connection timed out after 2000 milliseconds
# curl --connect-timeout 2 https://docker.com
curl: (7) Failed to connect to docker.com port 443: Connection timed out
# curl --connect-timeout 2 https://apt.dockerproject.org
curl: (28) Connection timed out after 2001 milliseconds
# curl --connect-timeout 2 https://yum.dockerproject.org
curl: (28) Connection timed out after 2001 milliseconds
# curl --connect-timeout 2 https://hub.docker.com
curl: (7) Failed to connect to hub.docker.com port 443: Connection timed out
```

Though apt.dockerproject.org is pingable:

```
# ping -c 4 apt.dockerproject.org
PING j.global-ssl.fastly.net (23.235.43.68) 56(84) bytes of data.
64 bytes from 23.235.43.68: icmp_seq=1 ttl=61 time=0.435 ms
64 bytes from 23.235.43.68: icmp_seq=2 ttl=61 time=0.348 ms
64 bytes from 23.235.43.68: icmp_seq=3 ttl=61 time=0.368 ms
64 bytes from 23.235.43.68: icmp_seq=4 ttl=61 time=0.341 ms

--- j.global-ssl.fastly.net ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3001ms
rtt min/avg/max/mdev = 0.341/0.373/0.435/0.037 ms
#
```

Traceroute:

```
# traceroute apt.dockerproject.org
traceroute to apt.dockerproject.org (185.31.17.68), 30 hops max, 60 byte packets
 1  178.62.191.254 (178.62.191.254)  1.354 ms 178.62.191.253 (178.62.191.253)  0.272 ms 178.62.191.254 (178.62.191.254)  1.258 ms
 2  95.85.0.241 (95.85.0.241)  0.260 ms 95.85.0.233 (95.85.0.233)  0.227 ms 95.85.0.241 (95.85.0.241)  0.214 ms
 3  83.231.213.1 (83.231.213.1)  0.761 ms adm-b7-link.telia.net (62.115.45.53)  0.723 ms 83.231.213.1 (83.231.213.1)  0.862 ms
 4  adm-bb4-link.telia.net (62.115.141.16)  0.703 ms adm-bb3-link.telia.net (80.91.253.162)  0.587 ms adm-bb3-link.telia.net (213.155.137.194)  0.579 ms
 5  hbg-bb4-link.telia.net (62.115.136.127)  7.303 ms hbg-bb4-link.telia.net (80.91.245.143)  7.292 ms hbg-bb1-link.telia.net (62.115.112.13)  6.616 ms
 6  ffm-bb2-link.telia.net (213.155.135.22)  52.816 ms ffm-bb1-link.telia.net (62.115.115.226)  14.819 ms ffm-bb1-link.telia.net (62.115.142.80)  14.884 ms
 7  * * *
 8  * * *
 9  * * *
10  * * *
11  * * *
12  * * *
13  * * *
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *
```

**Comment by jfrazelle** [comment]
weird that you cant get docker.com either..

**Comment by jfrazelle** [comment]
is there a proxy or something?

**Comment by rutsky** [comment]
> is there a proxy or something?

Shouldn't be. At least on the VM side network is configured to use gateway:

```
# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         188.226.240.1   0.0.0.0         UG    0      0        0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
188.226.240.0   0.0.0.0         255.255.240.0   U     0      0        0 eth0
#
```

**Comment by unclejack** [comment]
I'm seeing similar problems with the yum repositories (https://yum.dockerproject.org/repo/main/centos/7/repodata/repomd.xml).

I'm not using proxies of any kind.

**Comment by rutsky** [comment]
I thoroughly debugged connection issues and came to conclusion that my host had iptables misconfiguration: all outgoing IPv4 packets were effectively blocked, only IPv6 connections were allowed.
That explains selective connections problems: dockerproject.org has IPv6 and AWS S3 (which hosts package repositories) doesn't support IPv6.

Sorry for the noise @thaJeztah, @jfrazelle.

**Comment by jfrazelle** [comment]
oh ya im working on turning on the cloudflare ipv6 compat mode for the
repos... so we will see if that works

**Comment by thaJeztah** [comment]
Thanks for reporting back @rutsky!

**Comment by bonly** [comment]
+1

**Comment by rutsky** [comment]
@bonly what are you voting for? Is https://apt.dockerproject.org down for you?

**Comment by RGD2** [comment]
+1  - https://apt.dockerproject.org is down for me. (Ubuntu 14.04.3 LTS )

**Comment by RGD2** [comment]
I worked around it by putting:

~~~
deb [arch=amd64] https://mirrors.ustc.edu.cn/apt.dockerproject.org/repo ubuntu-trusty main
~~~
into
    /etc/apt/sources.list.d/docker-cnfix.list 

No idea how secure it is to be using this mirror though, so...  YMMV.
Is there any other preferred mirror?

**Comment by cicku** [comment]
@RGD2 This mirror is provided by @ustclug as unofficial since dockerproject.org hasn't support community mirrors.

**Comment by zoechi** [comment]
It's currently down for me (since a few days)
```
Linux zdev 4.9.0-2-amd64 #1 SMP Debian 4.9.13-1 (2017-02-27) x86_64 GNU/Linux
```

**Comment by thaJeztah** [comment]
@zoechi it's working here, and we haven't had any reports so far, so may be something in your connection. If the problem persists; please open a new issue with details

**Comment by thaJeztah** [comment]
I'm locking this issue because the original issue was resolved. If you're encountering issues with apt.dockerproject.org, yum.dockerproject.org or download.dockerproject.org, please open a new issue instead of commenting here. Comments on closed issues often go unnoticed and if there's an actual issue with one of those sites (which can be region dependent, thus not found by our monitoring system), reporting a new issue is appreciated.
