### ISSUE TITLE
double underscore and double hyphen in image names

### ISSUE THREAD

**Issue by adambrett** [docker/docker#16117]
I'm not sure if this is a bug or a deliberate decision, as I can't find any documentation on the change to the name regex (other than the generic v2 api docs), but somewhere ~1.7/8 double hyphens and double underscores are no longer allowed in image names.

The commit with the regex is here: https://github.com/docker/docker/commit/f011d722ce2ec7ef00654130f7f4ff8d295f025f#diff-0e119052c1201c5ded2882bad626640cR30

The fix would be something like:

```golang
var RepositoryNameComponentRegexp = regexp.MustCompile(`[a-z0-9]+(?:[._-a-z0-9]+)*`)
```

The reason we use double underscore and hyphen is an internal naming convention to make our image names easily scannable visually, and easily parsable with regex, whilst allowing a single hyphen in the sub parts: e.g. `business-area__project-name--app-name`, this is the same convention we use with our jenkins jobs and also relates back to our stash repos.

If there is a better way to do this now/this was introduced deliberately I'm happy to go away and look in to other solutions, or if this was an accident I'm happy to submit a PR to update the regex!

Thanks

---

```
docker version:

Docker version 1.8.1, build d12ea79

docker info:

Containers: 0
Images: 33
Storage Driver: devicemapper
 Pool Name: docker-253:2-528198-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.491 GB
 Data Space Total: 107.4 GB
 Data Space Available: 39.2 GB
 Metadata Space Used: 2.621 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93 (2015-01-30)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.6-200.fc22.x86_64
Operating System: Fedora 22 (Twenty Two)
CPUs: 4
Total Memory: 15.55 GiB
Name: hq-lap-2946
ID: YP2I:32WY:4PUE:XPO2:IYJU:NMG4:4QLM:TASV:CJ6R:GHOF:RNYD:JPCM

uname -a:

Linux hq-lap-2946 4.1.6-200.fc22.x86_64 #1 SMP Mon Aug 17 19:54:31 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):

List the steps to reproduce the issue:
1. Any valid dockerfile
2. `docker build -t test__one--two .`

Describe the results you received:

repository name component must match "[a-z0-9]+(?:[._-][a-z0-9]+)*"

Describe the results you expected:

image built and tagged

Provide additional info you think is important:

as above

**Comment by svetlyak40wt** [comment]
I have this problem too :(

**Comment by calavera** [comment]
I think this was kinda deliberated to avoid things like `this-----------is--------my-------docker-------image`. But I agree with you that it's not very ideal.

This code comes from https://github.comdocker/distribution. Please, feel free to open an issue there, or better if it's a pull request with the suggested change. Any changes will be vendor back in docker.

**Comment by dmcgowan** [comment]
Defining a strict regex to define a name component is deliberate. We recognized it is next to impossible to go from a very loosely defined format to something that is strongly defined without breaking any image names. The strict definition follows the idea that names are collection of components with separators. Just as a repository name is separated by '/', individual parts of a name (a-z0-9) can be separated by (._-) to create meaningful and parse-able names. Using that idea `business-area__project-name--app-name` would become something like `business-area_project-name.app-name`.

If you feel this is still breaking a use case then feel free to open an issue in distribution to discuss further.

**Comment by noxiouz** [comment]
We have hundreds of images with double underscores in their names, it would be a challenge to rename them. 
Anyway before opening an issue, I have to think about possible solutions. 

Thanks for the answer.

**Comment by stevvooe** [comment]
@noxiouz @adambrett Allowing less restricted image names is more of a security issue than anything else. Our initial goal in unifying these was to ensure that these worked across a wide variety of systems without much effort (DNS, filesystems, databases, etc.). The other goal is to reduce the likelihood of fracturing registry support. By having the same naming conventions across all registries and docker daemons, we ensure that images can be transitioned between systems (obviously, your use case has run afoul of this goal, but this is more about the future).

I know this is quite the request, but __if you could help us to vet this change from that angle, it would go along way in allowing this.__

**Comment by stevvooe** [comment]
@adambrett Any reason for the close? I think we are still open to this.

**Comment by adambrett** [comment]
Yep, this isn't the place for it, the new work in https://github.com/docker/distribution/pull/963 will supersede it and I need to spend some time looking at how those changes work, and how this change will affect it.

**Comment by stevvooe** [comment]
@adambrett https://github.com/docker/distribution/pull/963 only provides a type that has full compatibility. It will merge the work we've done identifying these discrepancies. We won't be making changes to the accepted name set.

**Comment by adambrett** [comment]
@stevvooe what I meant was: Any changes I make to the existing name set will either need to be after the changes in https://github.com/docker/distribution/pull/963 are integrated or be made first and then rebased in to https://github.com/docker/distribution/pull/963.

When I was looking at the original change to the regex before I was aware of https://github.com/docker/distribution/pull/963 I saw that the tests were failing because the same regex was being used to validate all parts of the "Name" by splitting on "/". I considered adding a new regex(s) to validate the different parts by different rules, or creating one single (much larger) regex to validate it all in one go, which would stop invalid hostnames (e.g. zx--y.com), but allow images named zx--y.

On my brief look over https://github.com/docker/distribution/pull/963 it seems that has already been done, so actually integrating the image name changes would be easier and more reliable/safer if I build on the work done there, but I need to spend some time reading and understanding the changes there to know what impact it will have.

Either way, the issue is in https://github.com/docker/distribution and not https://github.com/docker/docker, so any new issues/PRs I create will be there!

**Comment by dmcgowan** [comment]
@adambrett feel free to comment #963 with any tests you feel should be included. Not the `zx--y.com` support does not extend to the full image name, just the hostname.
