### ISSUE TITLE
Bridge network does not work for 1 second after starting container.

### ISSUE THREAD

**Issue by yoshiokatsuneo** [docker/docker#16114]
Description of problem:

Just after starting container on bridge network, network RTT is long like 1sec for the first second.
The issue happens on bridge network, but does not happens on host network.
If I run multiple docker command within 3sec, there is no delay on the second docker command.

```
$ docker run  -i -t ubuntu ping 23.3.74.35
PING 23.3.74.35 (23.3.74.35) 56(84) bytes of data.
64 bytes from 23.3.74.35: icmp_seq=1 ttl=54 time=1008 ms
64 bytes from 23.3.74.35: icmp_seq=2 ttl=54 time=8.91 ms
64 bytes from 23.3.74.35: icmp_seq=3 ttl=54 time=8.77 ms
64 bytes from 23.3.74.35: icmp_seq=4 ttl=54 time=8.62 ms
$ docker --version
Docker version 1.8.1, build d12ea79
```

`docker version`:
Docker version 1.8.1, build d12ea79

`docker info`:
Containers: 215
Images: 89
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 519
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-48-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 3.859 GiB
Name: ip-172-30-1-129
ID: IJPX:CXAX:QHEA:6ORA:URFS:OTKJ:XN4R:5IUI:AJUS:A7SW:7NAP:34EC
WARNING: No swap limit support

`uname -a`:
Linux ip-172-30-1-129 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
AWS

How reproducible:
Every time.

Steps to Reproduce:
1.Run a command:
```
$ docker run  -i -t ubuntu ping 23.3.74.35
```

Actual Results:
```
$ docker run  -i -t ubuntu ping 23.3.74.35
PING 23.3.74.35 (23.3.74.35) 56(84) bytes of data.
64 bytes from 23.3.74.35: icmp_seq=1 ttl=54 time=1008 ms
64 bytes from 23.3.74.35: icmp_seq=2 ttl=54 time=8.91 ms
64 bytes from 23.3.74.35: icmp_seq=3 ttl=54 time=8.77 ms
64 bytes from 23.3.74.35: icmp_seq=4 ttl=54 time=8.62 ms
$ docker --version
Docker version 1.8.1, build d12ea79
```

Expected Results:
The first ping reply time is not 1000ms but like the second or later.(ex: 10ms)

Additional info:

**Comment by LK4D4** [comment]
I remember that I had the same bug, but I can't reproduce it now. @yoshiokatsuneo feel free to create a new issue if it still there.
