### ISSUE TITLE
Volumes: relative host-path creates named volumes

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#16132]
While reviewing a PR (https://github.com/docker/docker/pull/16100#issuecomment-138455740), I discovered that using a *relative* path as host path, will create a named volume, instead of erroring out or creating a bind-mounted volume.

To reproduce;

```bash
docker run -v ./:/foobar ubuntu
```

Then inspect the container;

    "Mounts": [
        {
            "Name": "./",
            "Source": "/var/lib/docker/volumes/_data",
            "Destination": "/foobar",
            "Driver": "local",
            "Mode": "z",
            "RW": true
        }
    ],

From the inspect, it's visible that a volume named `"./"` is created

Note that using `-v ~/:/foobar` *does work*;

    "Mounts": [
        {
            "Source": "/root",
            "Destination": "/foobar",
            "Mode": "",
            "RW": true
        }
    ],

**Expected result**

Docker producing an error

I think we should (at least, for now) only allow `[a-zA-Z0-9][a-zA-Z0-9_.-]+` for volume-names, anything else should produce an error.

**Actual result**

Docker created a volume named `"./"`

docker version
```
Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   8562c42
 Built:        Sat Sep  5 12:34:19 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   8562c42
 Built:        Sat Sep  5 12:34:19 UTC 2015
 OS/Arch:      linux/amd64
```

docker info
```
Containers: 16
Images: 579
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 620
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-61-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 994 MiB
Name: [REDACTED]
ID: [REDACTED]
```

**Comment by thaJeztah** [comment]
ping @calavera @cpuguy83

**Comment by thaJeztah** [comment]
Hm, `-v ../:/foo/` also produces some interesting results; `"Source": "/var/lib/docker/_data"`

**Comment by xlgao-zju** [comment]
#dibs

**Comment by runcom** [comment]
This is also happening on 1.8.1 if it's a bug

**Comment by thaJeztah** [comment]
Thanks for checking, @runcom 

@xlgao-zju Thanks for starting on this. I think we need to;

- Agree if `[a-zA-Z0-9][a-zA-Z0-9_.-]+` is what we want
- Make sure that `--name` (i.e. `docker volume create --name=something`) uses the same regex/restriction

Adding the regex will break backward-compatibility, for example if people are currently able to create a named volume containing other characters (e.g. `my (personal) volume`), so if we agree on the Regex, this needs a mention in the changelog.

ping @calavera @cpuguy83 for thoughts ^^

**Comment by xlgao-zju** [comment]
That's ok. I'll fix

    Agree if [a-zA-Z0-9][a-zA-Z0-9_.-]+ is what we want 

at first.

**Comment by thaJeztah** [comment]
Yes, the decision on that depends on other maintainers as well, so it's possible that the definitive Regex will still change a bit.

**Comment by cpuguy83** [comment]
This probably needs to be the same regex is container names.
