### ISSUE TITLE
Bad address Docker-Toolbox for windows

### ISSUE THREAD

**Issue by chrisber** [docker/docker#16139]
I installed the docker-toolbox for windows together with virtualbox 5.0.3.

After starting `Docker Quickstart Terminal` it suggest I should run:    

```
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
``` 

The result is:
`bash: /c/Program Files/Docker Toolbox/docker-machine: Bad address`

`docker info` results in:

```
Get http://127.0.0.1:2375/v1.20/info: dial tcp 127.0.0.1:2375: ConnectEx tcp: No connection could be made because the target machine actively refused it..
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
```

Any suggestions to fix this issue?

**Comment by jfrazelle** [comment]
sorry this should be opened on github.com/docker/machine
