### ISSUE TITLE
Fail to start daemon on centos 6.5

### ISSUE THREAD

**Issue by zhuguoliang** [docker/docker#16138]
I am working on centos 6.5 and I downloaded rpm from
 http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
then I run  
yum -y install docker-io
service docker start
all good.(after reconfigured kernel with enabling cgroup memory and yum install  device-mapper-event-libs)

when I am trying to run 
docker -d -D
I got 
.....
FATA[0000] Error starting daemon: Error initializing network controller: Error creating default "bridge" network: Failed to Setup IP tables: Unable to enable NAT rule: iptables failed: iptables -t nat -I POSTROUTING -s 172.17.42.1/16 ! -o docker0 -j MASQUERADE: iptables v1.4.7: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
 (exit status 3) 

What should I do to fix it?
I already tried to update iptables and my kernel version is 3.12.13

**Comment by jfrazelle** [comment]
we no longer support rhel/centos 6 as of 1.8
