### ISSUE TITLE
[documentation] 404 when clicking on the "plugin documentation" link

### ISSUE THREAD

**Issue by alvinr** [docker/docker#16143]
# Problem
Get a 404 when following the "plugin documentation" link from the "write a volumen plugin" page.

![screen shot 2015-09-08 at 9 18 22 am](https://cloud.githubusercontent.com/assets/336450/9740711/fd12436a-560a-11e5-9c00-249d069ef3d0.png)
![screen shot 2015-09-08 at 9 18 15 am](https://cloud.githubusercontent.com/assets/336450/9740708/fad239a2-560a-11e5-97d2-c72854352a4b.png)

# Reproduce

1. Navigate to https://docs.docker.com/extend/plugins_volume/
2. Follow the link "plugin documentation" links ot https://docs.docker.com/extend/plugins_volume/plugins.md

# Solution
Fix the Link

# Environment
NA

**Comment by MHBauer** [comment]
Fixed in master.

I thought the documentation was synced a week or two ago? Caching issue?

**Comment by thaJeztah** [comment]
@MHBauer looks like it wasn't cherry-picked into the docs branch yet https://github.com/docker/docker/blob/docs/docs/extend/plugins_volume.md

But agreed, this is fixed on master, so I'll close this. Thanks for reporting @alvinr !


@moxiegirl is a docs update planned to go out together with the 1.8.2 release?

**Comment by moxiegirl** [comment]
@thaJeztah I wasn't planning on doing one.  The 1.9 release is coming on pretty fast.
