### ISSUE TITLE
check for cpuset.cpus before set the value

### ISSUE THREAD

**Issue by HuKeping** [docker/docker#16141]
Here comes the example:

Assume I have 4 CPUs in my host, at the very beginning everything is OK for
```
 docker run -ti --name hkp_ubuntu  --cpuset-cpus=0-3 ubuntu bash
```

Then I put CPU1 off and then put it on
```
echo 0 > /sys/devices/system/cpu/cpu1/online

echo 1 > /sys/devices/system/cpu/cpu1/online
```

Let's check for the cpuset.cpus of cgroup docker
```
cat /sys/fs/cgroup/cpuset/docker/cpuset.cpus
0,2-3
```

And then run that docker CLI again, error happen
```
Error response from daemon: Cannot start container 0abdc40d8a96d66318340b863cff56177e4958540839440fb25edb8a57430c51: [8] System error: write /sys/fs/cgroup/cpuset/docker/0abdc40d8a96d66318340b863cff56177e4958540839440fb25edb8a57430c51/cpuset.cpus: invalid argument
```

This is because when we shut down CPU1, the cgroup system update all the sub-cgroup system about the cpuset.cpus.  But when the CPU1 comes back it didn't do the same thing.

**Comment by HuKeping** [comment]
I'll rise a pr to libcontainer to fix it  https://github.com/opencontainers/runc/pull/254

**Comment by runcom** [comment]
@HuKeping your patch in runc is working fine with latest docker master

**Comment by hqhq** [comment]
@runcom As I mentioned in opencontainers/runc#254 , I don't think it's a bug, WDYT?

**Comment by runcom** [comment]
@hqhq reading your conversation on runc, yeah it doesn't seems so but I'd like other maintainers to check on this before closing

**Comment by hqhq** [comment]
@runcom Sure, just for clear, it is a problem, just I don't think there are anything we can do on Docker or runC side, it's not a Docker bug. It should be fixed on kernel side, but kernel didn't fix mutil hierarchy case.

**Comment by runcom** [comment]
@hqhq I see, libcontainer error is awful tho and reading from root cgroup isn't ok as highlighted on runc PR :/

**Comment by megastef** [comment]
Q:  When I run vmstat in a container, the CPU ticks do not change!
The displayed values are completly differnt from the host. 

Is this related to this issue?

**Comment by HuKeping** [comment]
@megastef  seems not.

**Comment by thaJeztah** [comment]
@HuKeping @hqhq so what's the status here; is this something to be solved in docker or in the kernel?

**Comment by HuKeping** [comment]
They prefer not do this in docker but the kernel side

**Comment by thaJeztah** [comment]
Thanks @HuKeping, I'll go ahead and close this, but feel free to comment here
