### ISSUE TITLE
`docker volume inspect --help` does not contain --help option

### ISSUE THREAD

**Issue by albers** [docker/docker#16146]
In current master:
```
$ docker volume inspect --help

Usage:  docker volume inspect [OPTIONS] [VOLUME NAME]

Return low-level information on a volume

  -f, --format=      Format the output using the given go template.
```

There is no `--help=false       Print usage` line. `--help` is available, though.
The other subcommands of `docker volume` are correct in this regard.

```
$ docker --version
Docker version 1.9.0-dev, build 3a539c6
```

**Comment by thaJeztah** [comment]
Thanks @albers! Do you want to create a PR yourself, or want someone else to pick this up?

/cc @cpuguy83

**Comment by albers** [comment]
@thaJeztah I already tried to fix it but failed. `--help` has some special treatment, and I really don't understand why it doesn't appear in this specific command.

**Comment by thaJeztah** [comment]
No worries, @albers! I'm sure there's a maintainer that can pick it up; I wanted to check first if you weren't working on it already :+1:

**Comment by duglin** [comment]
I got it - the flag stuff is kind of funky

**Comment by albers** [comment]
I'm looking forward to the solution of that puzzle.

**Comment by duglin** [comment]
Here's the diff of the fix - creating the testcase to make sure we don't break again is actually the hard part...
```
diff --git a/api/client/volume.go b/api/client/volume.go
index ccb0188..d320259 100644
--- a/api/client/volume.go
+++ b/api/client/volume.go
@@ -104,13 +104,14 @@ func (cli *DockerCli) CmdVolumeLs(args ...string) error {
 func (cli *DockerCli) CmdVolumeInspect(args ...string) error {
        cmd := Cli.Subcmd("volume inspect", []string{"[VOLUME NAME]"}, "Return l
        tmplStr := cmd.String([]string{"f", "-format"}, "", "Format the output u
-       if err := cmd.Parse(args); err != nil {
-               return nil
-       }
 
        cmd.Require(flag.Min, 1)
        cmd.ParseFlags(args, true)
 
+       if err := cmd.Parse(args); err != nil {
+               return nil
+       }
+
        var tmpl *template.Template
        if *tmplStr != "" {
                var err error
```

**Comment by duglin** [comment]
PR#16158
