### ISSUE TITLE
Error response from daemon: Cannot start container : [8] System error: invalid argument

### ISSUE THREAD

**Issue by aleclerc** [docker/docker#16150]
Description of problem:
Upgraded to 1.7.1 this morning, since then I can't start any docker containers. RHEL 6.6

`docker version`:

```
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d/1.7.1
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d/1.7.1
OS/Arch (server): linux/amd64
```

`docker info`:

```
Containers: 3
Images: 126
Storage Driver: devicemapper
 Pool Name: docker-253:2-10223880-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.353 GB
 Data Space Total: 107.4 GB
 Data Space Available: 104 GB
 Metadata Space Used: 6.746 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.141 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 2.6.32-504.30.3.el6.x86_64
Operating System: <unknown>
CPUs: 8
Total Memory: 9.615 GiB
Name: [REDACTED]
ID: [REDACTED]
```

`uname -a`:

Linux [REDACTED] 2.6.32-504.30.3.el6.x86_64 #1 SMP Thu Jul 9 15:20:47 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):

RHEL 6.6

How reproducible:
Everytime

Steps to Reproduce:
1. docker run hello-world

Actual Results:
```
$ docker run hello-world
invalid argument
Error response from daemon: Cannot start container e8b0ed445c73f1552942c256da774e460b24bf2dcbc2d6673a3f59865698c500: [8] System error: invalid argument
```
Expected Results:
New Container Running

Additional info:

Was previously using 1.6.2
Even tried to revert the package and got this:
```
yum history undo 64
....
Failed to downgrade: docker-io-1.6.2-3.el6.x86_64
````

All ran the check-config script. definitely some issues, but not sure what to do about them:
```
[lecerca@oc6131723517 ~]$ ./check-config.sh 
warning: /proc/config.gz does not exist, searching other paths for kernel config ...
info: reading kernel config from /boot/config-2.6.32-504.30.3.el6.x86_64 ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/cgroup]
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MEMCG: missing
- CONFIG_MACVLAN: enabled (as module)
- CONFIG_VETH: enabled (as module)
- CONFIG_BRIDGE: enabled (as module)
- CONFIG_BRIDGE_NETFILTER: enabled
- CONFIG_NF_NAT_IPV4: missing
- CONFIG_IP_NF_FILTER: enabled (as module)
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: missing
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
- CONFIG_NF_NAT: enabled (as module)
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_MEMCG_KMEM: missing
- CONFIG_MEMCG_SWAP: missing
- CONFIG_MEMCG_SWAP_ENABLED: missing
- CONFIG_RESOURCE_COUNTERS: enabled
- CONFIG_BLK_CGROUP: enabled
- CONFIG_IOSCHED_CFQ: enabled
- CONFIG_BLK_DEV_THROTTLING: enabled
- CONFIG_CGROUP_PERF: enabled
- CONFIG_CGROUP_HUGETLB: missing
- CONFIG_NET_CLS_CGROUP: enabled
- CONFIG_NETPRIO_CGROUP: enabled
- CONFIG_CFS_BANDWIDTH: enabled
- CONFIG_FAIR_GROUP_SCHED: enabled
- CONFIG_RT_GROUP_SCHED: enabled
- CONFIG_EXT3_FS: enabled (as module)
- CONFIG_EXT3_FS_XATTR: enabled
- CONFIG_EXT3_FS_POSIX_ACL: enabled
- CONFIG_EXT3_FS_SECURITY: enabled
- CONFIG_EXT4_FS: enabled (as module)
- CONFIG_EXT4_FS_POSIX_ACL: enabled
- CONFIG_EXT4_FS_SECURITY: enabled
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: missing
  - "btrfs":
    - CONFIG_BTRFS_FS: enabled (as module)
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: enabled (as module)
    - CONFIG_DM_THIN_PROVISIONING: enabled (as module)
  - "overlay":
    - CONFIG_OVERLAY_FS: missing
  - "zfs":
    - /dev/zfs: missing
    - zfs command: missing
    - zpool command: missing
```

**Comment by borntorock** [comment]
I also experienced the same issue, #14386

**Comment by truatpasteurdotfr** [comment]
do you have DOCKER_STORAGE_OPTIONS defined in /etc/sysconfig/docker-storage?

**Comment by calavera** [comment]
Hi @aleclerc,

Thanks for opening this issue. I'm going to close it though as it's duplicated. That way we can centralize all the information regarding the same problem under only one issue. Please, feel free to follow up in #14386.

**Comment by mbaudisch** [comment]
I don't understand why this was closed. Issue #14386 has an error stating there is no disk space left while this one states an invalid argument. I have this same issue now (or very similar) I upgraded from RHEL 6.6 to RHEL 6.7   and I upgraded to Docker 1.7.1   and now I cannot start any containers as I get "invalid argument" error every time with every image. I can do a lot of other things with docker, like build new images, but I can't run containers. Personally, I think it has something to do with the kernel supporting  Docker 1.7.1 And I suspect I will have to uninstall docker and reinstall 1.6.x . Either that or upgrade my kernel to RHEL 7   I would like any advice or pointers to instruction on how to do either of these scenarios

**Comment by truatpasteurdotfr** [comment]
@mbaudisch if you are using docker-io-1.7.1-2 from epel, try upgrading to the testing version 1.7.1-4 which fixes the devicemapper storage driver setup

**Comment by kubilus1** [comment]
@mbaudisch I agree.  #14386 gives a different error.  I have the same issue here.   @truatpasteurdotfr tried that, but it didn't fix the issue.

**Comment by hunternet** [comment]
poxa o meu erro persiste 

FATA[0012] Error response from daemon: Cannot start container 82da267bde763f0a3f8d6452ffbe5252247bb4ed068db1f8ebae0fa1eebea970: [8] System error: mountpoint for devices not found

estou tentando inicializar um app cloud-torrent

https://github.com/jpillora/cloud-torrent

se algen puder me ajudar agradeço
