### ISSUE TITLE
Cannot use docker search when search expression ends with a - or _

### ISSUE THREAD

**Issue by jharveysmith** [docker/docker#16155]
This is with docker 1.8.1, but have observed it since docker 1.7.  The problem doesn't happen in docker 1.6
```
% docker search ubuntu/ubuntu | grep ubuntu-
ubuntu-upstart              Upstart is an event-based replacement for ...   31        [OK]       
tleyden5iwx/ubuntu-cuda     Ubuntu 14.04 with CUDA drivers pre-installed    17                   [OK]
ubuntu-debootstrap          debootstrap --variant=minbase --components...   12        [OK]       
rastasheep/ubuntu-sshd      Dockerized SSH service, built on top of of...   7                    [OK]
fike/ubuntu-postgresql      PostgreSQL 9.4 beta until 9.0 version runn...   4                    [OK]
densuke/ubuntu-jp-remix     Ubuntu Linuxの日本語remix風味です                       1                    [OK]
densuke/ubuntu-supervisor   densuke/ubuntu-jp-remix:trusty 上で supe...       0                    [OK]
```
but
```
% docker search ubuntu/ubuntu-
repository name component must match "[a-z0-9]+(?:[._-][a-z0-9]+)*"
```

Search terms shouldn't be restricted to only full valid repository names.  It should be perfectly valid to search using a part of a name, even if it ends with a - or _

**Comment by thaJeztah** [comment]
Thanks for reporting, yes, I agree this should be possible

**Comment by HuKeping** [comment]
come across a similar issue, I'll look into this

**Comment by HuKeping** [comment]
Get it. When typing `docker search`

- first get into the CmdSearch
- and then get through `ParseRepositoryInfo()`, `NewRepositoryInfo()`, `validateRemoteName()`, `ValidateRepositoryName()` one by one.
- in `ValidateRepositoryName()` it will use `[a-z0-9]+(?:[._-][a-z0-9]+)*` to do the match, but as @jharveysmith said it should not be that restricted in `search`. Which I think `[a-z0-9]+(?:[._-][a-z0-9]*)*` is enough.

We can create a new `Regexp` there  and add an extra parameter in those four methods to tell us whether we are in a search or not. But I don't think it's a nice change in this way. Any suggestions please? @thaJeztah

**Comment by thaJeztah** [comment]
I haven't looked deeply into the handling inside docker itself, but I don't think search should have any restrictions *at all*.

Searching for :8ball: :football: :cake: (as an extreme example) should be allowed, but just won't a result. It's up to the *registry* / *docker hub* / *index* to decide what to do with the entered search query.

Just my thoughts here :-)

**Comment by jharveysmith** [comment]
@thaJeztah I agree.

**Comment by HuKeping** [comment]
#dibs
