### ISSUE TITLE
Update "find an issue" page with new labels

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#16156]
The new labels are now present, as decided on in https://github.com/docker/docker/pull/14719, and described in [project/ISSUE-TRIAGE.md](https://github.com/docker/docker/blob/master/project/ISSUE-TRIAGE.md), so the ["find an issue"](https://github.com/docker/docker/blob/master/docs/project/find-an-issue.md) page should be updated to reflect the new labels.

**Comment by thaJeztah** [comment]
ping @lyndaoleary. This one's for you!

Hm... Looks like we no longer have a "claimed" label, LOL, I'll ask about that

**Comment by thaJeztah** [comment]
The label is back, so I reserved it for you :+1:

**Comment by lyndaoleary** [comment]
#dibs thanks @thaJeztah
