### ISSUE TITLE
Fix incomplete sentence on docker/basics page

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#16161]
I noticed an incomplete sentence on the following link: https://docs.docker.com/articles/basics/. The "Please" is not followed by a proper sentence. Thought I'd bring it to your attention!

If you get docker: command not found or something like/var/lib/docker/repositories: permission denied you may have an incomplete Docker installation or insufficient privileges to access Docker on your machine. Please

**Comment by moxiegirl** [comment]
@duglin -- should I just ping you on these?

**Comment by HuKeping** [comment]
Absolutely something is missing there.

**Comment by mikebrow** [comment]
@dibs

**Comment by mikebrow** [comment]
#dibs

**Comment by zelahi** [comment]
Hello, I was wondering if I could help out with this issue

**Comment by moxiegirl** [comment]
Thanks @zelahi but it looks like Mike fixed this one.  Please feel free to take one of these:

https://goo.gl/gh59WC
