### ISSUE TITLE
Bind mounted file not updated

### ISSUE THREAD

**Issue by geku** [docker/docker#16178]
In certain cases on CentOS 7 bind mounted files are static and not updated, e.g. when the mounted file is updated on the host, the updates are not visible within the container and the file still has the old content.

#### `docker version`:

```
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

#### `docker -D info`:

```
Containers: 19
Images: 195
Storage Driver: devicemapper
 Pool Name: docker-9:2-4195102-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 13.81 GB
 Data Space Total: 107.4 GB
 Data Space Available: 93.57 GB
 Metadata Space Used: 14.07 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.133 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.7.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 12
Total Memory: 125.7 GiB
Name: CentOS-71-64-minimal
ID: NZKS:IXPB:TYGG:IJI2:EGZA:ZZV6:MRR4:43MS:BELH:FSLV:ZG6G:U42D
```

#### `uname -a`:

```
Linux CentOS-71-64-minimal 3.10.0-229.7.2.el7.x86_64 #1 SMP Tue Jun 23 22:06:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

#### Environment details (AWS, VirtualBox, physical, etc.):

physical machine

#### How reproducible:

It is reproducible with Vagrant/VirtualBox when using a CentOS 7.0 image.

Steps to Reproduce:

1. `mkdir -p /home/staging/demo/shared`
2. `echo "demo" > /home/staging/demo/shared/any_file`
3. `docker run -it -v /home/staging/demo/shared/any_file:/tmp/any_file ubuntu /bin/bash`
4. in container: `cat /tmp/any_file `
=> demo
5. Change `any_file` on host: `vi /home/staging/demo/shared/any_file`
6. in container: `cat /tmp/any_file`
 => demo

#### Actual Results:

File mounted to container and updated on host does not get updated within container.

#### Expected Results:

File changes should be visible in the container during container runtime.

#### Additional info:

It looks like a problem with `vi` because when the file is changed with an `echo` command, the file change is visible within the container. And as soon as the file is modified with `vi`, changes are no longer propagated.

Additionally, changing owner and group to root fixes the problem as well: `chown root:root /home/staging/demo/shared/any_file`

**Comment by cpuguy83** [comment]
Hello,

The way bind-mounts work is it uses the file's inode.
In cases where you are editing the file with something like vim, the inode is actually changed on save, and as such breaks the bind-mount (or at least, the mount is still tied to the old inode).

If you edit the file in place this will not be a problem.

Thanks!

**Comment by cpuguy83** [comment]
Relevant docs: https://docs.docker.com/userguide/dockervolumes/#mount-a-host-file-as-a-data-volume

**Comment by geku** [comment]
Thanks a lot for the clarification!
