### ISSUE TITLE
volume ls to support --filter

### ISSUE THREAD

**Issue by chanwit** [docker/docker#16175]
Similar to `docker images`, there are several use cases that `docker volume ls` needs filters.
In case of `swarm`, we'd like to do something like:

`docker volume ls --filter node=node-01`

to list volumes only on node-01.

So, an enhancement for volume subcommands to support filtering would be great.

Ref: docker/swarm#1196

/cc @vieux @icecrime @cpuguy83

**Comment by cpuguy83** [comment]
"ls" does support filtering, namely "dangling=true".
Was there something else that's needed?

**Comment by chanwit** [comment]
@cpuguy83 thank you for letting me know :):) and sorry for my ignorant.

@vieux it seems we already have `volume ls` with filter in the engine. Should we start a new PR to support this on `swarm`?

**Comment by vieux** [comment]
@chanwit yes, my bad it's my fault.
