### ISSUE TITLE
support Alpine processors for Synology DS215+ (and others)

### ISSUE THREAD

**Issue by christian-steinmeyer** [docker/docker#16184]
I hope, that this is the right place to ask this question. I just got a Synology DS215+ NAS and had a look at all the available apps, after seeing the awesome of Docker, I tried to install it, but it's not available through the provided OS DSM 5.2. After contacting the Synology support, they replied by saying: "Availability of this Docker for alpine processors not depends from us but from the developers of Docker, so we don't have info about it...". 

Maybe someone from this team can help me. Is supporting the smaller Synology NAS intended? And if so, can you already tell me an approximate time when it might be available? If it's not the case, may I ask why, and also what good alternatives are to install it, if not through the official OS? Thank you very much in advance!

**Comment by cpuguy83** [comment]
Only x86-64 Linux is officially supported... I believe ARM support is pending (and it should generally compile and work fine for you).
Anything else would be a community effort.

**Comment by christian-steinmeyer** [comment]
Thank you for your quick reply. Do you have any idea, who is responsible for the integration of docker into DSM (Synology's NAS OS)? I mean, that doesn't look like a community effort to me. Have a look at:
https://www.synology.com/en-us/dsm/app_packages/Docker

**Comment by cpuguy83** [comment]
@christian-steinmeyer This looks like something Synology on their own.
