### ISSUE TITLE
'docker cp' doesn't work as expected

### ISSUE THREAD

**Issue by arieb** [docker/docker#16186]
BUG REPORT INFORMATION
========================
Description of problem:
im trying to copy a folder's sub directories from inside a container to the host, however I get the directory itself too.

`docker version`:
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

`docker info`:
Containers: 1
Images: 114
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 116
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-52-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 7.705 GiB
Name: milano
WARNING: No swap limit support

`uname -a`:
Linux milano 3.13.0-52-generic #86-Ubuntu SMP Mon May 4 04:32:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
physical (laptop)

How reproducible:
* Create a basic directory structure inside a container
* try and copy the base of the directory structure from the container (SRC_DIR) to an existing directory on the host (DST_DIR), while making sure you add the '/' at the end of the SRC_DIR.

Steps to Reproduce:
Create a very simple directory structure inside a container
```bash
arie@milano:~$ docker run --name=cp_test -ti ubuntu:12.04.5 /bin/bash
root@f4f36b882e75:/# mkdir foo 
root@f4f36b882e75:/# mkdir foo/bar
root@f4f36b882e75:/# mkdir foo/moo
root@f4f36b882e75:/# mkdir foo/bla
root@f4f36b882e75:/# touch foo/bar/test1
root@f4f36b882e75:/# touch foo/bar/test2
root@f4f36b882e75:/# touch foo/moo/test3
root@f4f36b882e75:/# touch foo/bla/test4
root@f4f36b882e75:/# exit
```

try and copy the base of the directory structure so it copies the CONTENTS of the directory and not the directory itself
according to the `docker cp` documentation this is done by adding a '/' to the end of the SRC_DIR in case that both the SRC_DIR and DST_DIR exist and are directories.

```bash
arie@milano:~$ mkdir /tmp/cp_test
arie@milano:~$ cd /tmp/cp_test
arie@milano:/tmp/cp_test$ docker cp cp_test:/foo/ /tmp/cp_test/
arie@milano:/tmp/cp_test$ ls
foo
arie@milano:/tmp/cp_test$ 
```

foo itself is copied, not only its sub-directories

Actual Results:
```bash
arie@milano:~$ ls /tmp/cp_test
foo
```

Expected Results:
```bash
arie@milano:~$ ls /tmp/cp_test
bar  bla  moo
```

Additional info:
This seems to correspond to test case 'J' inside the 'integration-cli/docker_cli_cp_from_container_test.go' im not sure whether this works as intended and the problem is with the documentation or an actual bug both in the code and in the test.

----------END REPORT ---------

#ENEEDMOREINFO

**Comment by phemmer** [comment]
This is exactly how the `cp` utility works (normal `cp`, outside of docker).

```
# mkdir a

# mkdir a/b

# touch a/b/c

# mkdir d

# cp -r a/ d/

# ls d/
a/
```

That being said, you can get the behavior you want by using `/foo/.` (note the dot).

E.G.:

    docker cp cp_test:/foo/. /tmp/cp_test/

**Comment by arieb** [comment]
well, im in the documentation it says:
* DST_PATH exists and is a directory
    * SRC_PATH does not end with /.
        * the source directory is copied into this directory
    * SRC_PAPTH does end with /.
        * the content of the source directory is copied into this directory

So I guess its not very clear.

**Comment by phemmer** [comment]
How would you clarify it? `the source directory is copied into this directory` and `the content of the source directory is copied into this directory` seems clear to me.

**Comment by jlhawn** [comment]
Sorry for the confusion. Those aren't periods in the documentation. It should read:

* DST_PATH exists and is a directory
    * SRC_PATH does not end with `/.`
        * the source directory is copied into this directory
    * SRC_PAPTH does end with `/.`
        * the content of the source directory is copied into this directory

**Comment by jlhawn** [comment]
Actually, It already is emphasized: 

![screen shot 2015-09-11 at 5 00 10 pm](https://cloud.githubusercontent.com/assets/1441929/9828722/9fffd09a-58a6-11e5-81f0-93d6b73633b4.png)

**Comment by jlhawn** [comment]
I also want to point out a difference between `GNU cp` and `BSD cp` (like what you'd find in Mac OS X). Both let you copy the **contents** of a directory be using a trailing `/.`, but `BSD cp` has the additional quirk that you can do the same thing by simply having a trailing `/`.

**Comment by cpuguy83** [comment]
So is this an issue?

**Comment by arieb** [comment]
well I think I understand the reason for my confusion, since im reading a
manpage from my terminal I mistook the period as being part of the sentence
not the actual syntax.
thanks for clarifying

**Comment by cpuguy83** [comment]
Ok, I will close since this doesn't seem like it's an issue, unless I'm misunderstanding.

Thanks!

**Comment by TylerRick** [comment]
> I mistook the period as being part of the sentence

Ack, I just did that too, and was about to submit a bug report when I found this one first (thankfully)!

Wow, and I was even reading the docs at https://docs.docker.com/engine/reference/commandline/cp/, where the the `/.` is at least formatted as one (`<code>`) unit.

If I were paying closer attention, I would have noticed, but for someone who is skimming the man page 
in a hurry (esp. on a terminal, which doesn't have the advantage of `<code>` blocks being formatted differently), this would be a *very* easy mistake to make.

It didn't help that I had *just* been working with the same type of issue with an **`rsync`** command, where only a trailing slash is needed to get it to *copy the contents*!

> You can think of a trailing / on a source as meaning "copy  the  contents  of  this directory" as opposed to "copy the directory by name"

Since both conventions are prevalent (one with `cp` and one with `rsync`), I would recommend attempting to make it even more painfully clear which convention `docker cp` uses. Perhaps:

- DST_PATH exists and is a directory
  - SRC_PATH does not end with `/.` (slash dot)
    - the source directory is copied into this directory
  - SRC_PATH does end with `/.` (slash dot)
    - the content of the source directory is copied into this directory

Putting the parenthetical clarification would serve both to reiterate the punctuation marks using spelled-out words *and* to make it less likely that someone would think the dot was a period at the end of the sentence.

**Comment by thaJeztah** [comment]
@TylerRick would you be willing to open a pull request with the changes you think are needed? The markdown file that's used to generate that page in the docs is part of this repository; https://github.com/docker/docker/blob/master/docs/reference/commandline/cp.md
