### ISSUE TITLE
Virtual Size ... negative

### ISSUE THREAD

**Issue by kapolos** [docker/docker#16189]
I have created an image from a running container - all good so far.
````
root@scw-ec24f6:~# docker images
REPOSITORY               TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
kapolos/armhf-arangodb   2.7.0-devel         6515245edb56        3 minutes ago       1.564 GB
[...skipped...]
````

I realize I forgot to clean some files, I remove them on the still running container and commit again
````
root@scw-ec24f6:~# docker commit hopeful_bose kapolos/armhf-arangodb:2.7.0-devel
0bbc0ce06368e8a923737b4c8505d4157d43399495a72cf6a39b606a1b24e9ed
````

And then...
````
root@scw-ec24f6:~# docker images
REPOSITORY               TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
kapolos/armhf-arangodb   2.7.0-devel         0bbc0ce06368        44 seconds ago      -1.956e+09 B
`````

Negative volume is awesome but might be slightly problematic :) Pushing the image to the hub, I see the actual size is 938MB, which sounds right.

````
Docker version 1.8.1, build d12ea79-dirty
````
````
armhf arch
````

**Comment by HuKeping** [comment]
Any steps that can reproduce this ?

**Comment by kapolos** [comment]
@HuKeping 

I just tried this:
````
# docker pull kapolos/armhf-arangodb:2.7.0-devel
[snip]
Digest: sha256:606115d753364b4004b94bc8d37e3b073d19bf7b462bf8d63b1c789e9da5eb2d
Status: Downloaded newer image for kapolos/armhf-arangodb:2.7.0-devel

# docker images
[snip]
kapolos/armhf-arangodb     2.7.0-devel    0bbc0ce06368    5 weeks ago   -1.956e+09 B
````

That's on the same machine as I had originally created the image, don't know if it matters in any way.

**Comment by thaJeztah** [comment]
Looking at the image you're running, this is on a ARM platform, correct?

**Comment by kapolos** [comment]
@thaJeztah Yes, I am using it on [Scaleway's C1](https://www.scaleway.com) ARM servers (mentioning it in case you'd like an easy way to execute it).

**Comment by LK4D4** [comment]
@thaJeztah Do you know who can try on ARM?
@kapolos do you still have problem?

**Comment by thaJeztah** [comment]
Given that this is on a (now) very old custom build of docker, and image storage got a massive rewrite in docker 1.10, I'll go ahead and close this issue, but @kapolos let us know if there's still something to be done, and I can reopen if needed
