### ISSUE TITLE
Docs: document that VT-X support is required for Toolbox on Windows and OS X

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#16182]
If virtualization (VT-X) is not supported on the hardware that Docker Toolbox / VirtualBox is installed on, the VirtualBox VM will fail to start.

We should document that;

- `VT-X` must be supported *and enabled* on the hardware
- How to check if `VT-X` is supported and enabled
- Some basic instructions (or links to) to enable VT-X

I opened an issue in the Docker Toolbox repository to track improvements in the installer; https://github.com/docker/toolbox/issues/166

This problem is reported in https://github.com/docker/docker/issues/11877, and mentioned in https://github.com/docker/docker/issues/15982#issuecomment-138822418, but there are various reports in the Docker Machine and Docker Toolbox repository as well.

/cc @moxiegirl @jeffdm @ehazlett

**Comment by ehazlett** [comment]
Thanks!  We will get this in the machine docs as well.

**Comment by yunti** [comment]
Just to follow up from my previous post in the other thread (which probably doesn't fit that related issue hence posting here).  Note that after initially having the wrong setting at vt-x not enabled. The boot2docker vm in virtual box continued to report the not x86-64 cpu issue.  Deleting the vm and reinstalling toolbox fixed the issue. (just took a loooong time to realise that it could be fixed by that).

**Comment by thaJeztah** [comment]
Thanks @yunti, that's useful information to add. So the best approach would be to detect missing `vt-x` *before* attempting to install VirtualBox or the Machine VM.

Wondering if it's *VirtualBox* that needs to be reinstalled in that case, or if removing the VM would be sufficient.

**Comment by yunti** [comment]
Yes I would detect before.

To fix I deleted the VM from within virtual box and then reinstalled via toolbox.  I didn't remove anything else before reinstalling, so I'm not sure if toolbox will reinstall virtual box in the case (as it will depend on what it does if it detects the same version)

**Comment by opreaadrian** [comment]
Literally bumped into this issue today. I was on a Windows 7 machine, running on VMWare ESXi Server, and kept getting this error when trying to install [Docker Toolbox](https://www.docker.com/toolbox). I tried with our sysadmin to enable both versions of VT-X available in the management interface and remove/reinstall the whole thing but with no luck. 
I'll also attach a screenshot, hopefully it helps.

![Uploading Screen Shot 2015-09-14 at 12.41.43.png…](Hardware acceleration not available on system)

**Comment by yunti** [comment]
if using windows check in the task manager to see if you have virtualisation enabled (it's in the docker docs).  That will confirm whether virtualisation or docker are the issue.

**Comment by opreaadrian** [comment]
@yunti , thanks for the heads-up! Never went through that part, given the fact that we had the Virtualisation option available on the VMWare management interface, and we tried every possible combo. We were stuck on that.

**Comment by dustinlapierre** [comment]
I would like to look into adding this documentation. I am new to GitHub and FOSS software and was looking for an easy issue to get me started as a beginner. Is this something I could work on?

**Comment by opreaadrian** [comment]
@dustinlapierre Check the docs to find out how you can contribute. You can start here: https://docs.docker.com/opensource/project/who-written-for/

**Comment by kevinBlum** [comment]
I would also like to look into writing some proper documentation for this as I have run into this issue before on a different project and see there is another issue tracker opened under docker / toolbox for the same issue #166 https://github.com/docker/toolbox/issues/166 and was just wondering if the documentation was still necessary and if I could write it up

**Comment by thaJeztah** [comment]
Closing, because this was addressed in https://github.com/docker/toolbox/pull/488
