### ISSUE TITLE
get.docker.com invalid config

### ISSUE THREAD

**Issue by capoferro** [docker/docker#16195]
`curl -sSL https://get.docker.com/ | sh` on CentOS 7 results in an invalid config in `/etc/yum.repos.d/docker-main.repo`

Here's what I get:

```
$ cat /etc/yum.repos.d/docker-main.repo
[docker-main-repo]
name=Docker main Repository
baseurl=https://yum.dockerproject.org/repo/main/centos/7
7
enabled=1
gpgcheck=1
gpgkey=https://yum.dockerproject.org/gpg
```

Here's the corrected config:

```
$ cat /etc/yum.repos.d/docker-main.repo
[docker-main-repo]
name=Docker main Repository
baseurl=https://yum.dockerproject.org/repo/main/centos/7
enabled=1
gpgcheck=1
gpgkey=https://yum.dockerproject.org/gpg
```

**Comment by thaJeztah** [comment]
Thanks for reporting!

ping @jfrazelle

**Comment by jfrazelle** [comment]
yes someone else reported this but it was because they had 2 centos versions installed or something

**Comment by jfrazelle** [comment]
please see https://github.com/docker/docker/issues/16097

**Comment by capoferro** [comment]
That appears to be the problem. Thanks!
