### ISSUE TITLE
QUESTION alias for docker exec throws EOF

### ISSUE THREAD

**Issue by buehler** [docker/docker#16209]
Hey there

I really love docker and I use it in many dev projects now. I'm a lazy ubuntu user and I intended to create a small alias in my shell:
```
alias dconnect='docker exec -it $1 /bin/bash'
```

But when I execute this command, my terminal just throws an EOF.

But why? :cry: 

On the other side:
```
alias dlg='docker logs -f --tail="50" $1'
```
does work...

Cheers
Chris

**Comment by buehler** [comment]
I searched the issues, and fount nothing like it. But here the information :)

```
docker version:
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```

```
docker info:
Containers: 13
Images: 260
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 286
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-26-generic
Operating System: Ubuntu 15.04
CPUs: 4
Total Memory: 7.704 GiB
Name: christoph-nb
ID: SLAS:Q2J3:C35R:WCFO:5JXJ:KWT7:X4VD:JJGH:YJTX:MGAJ:NKMU:S45M
WARNING: No swap limit support
```

```
uname -a:
Linux 3.19.0-26-generic #28-Ubuntu SMP Tue Aug 11 14:16:32 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```



Steps to reproduce:
1. get ubuntu
2. get shell.
3. alias dconnect='docker exec -it $1 /bin/bash'
4. try to execute dconnect with any running container
5. get EOF in shell.

I'd expect to connect to this container with a shell.

**Comment by cpuguy83** [comment]
I don't think you can interpolate shell variables into an alias like that.

You'd need to do something like:
```bash
dconnect() {
    docker exec -it $1 /bin/bash
}
```

**Comment by wil93** [comment]
@buehler For what it's worth: the cause of the EOF was that $1 is translated to an empty string (try `echo $1` in the terminal) so the alias was basically just `docker exec -it /bin/bash`. Now, when you launch `dconnect container_name` you are really launching `docker exec -it /bin/bash container_name`, and that basically means swapping the last two arguments :smile: (if you try *that* you get an EOF error)

**Comment by np** [comment]
But the error was not particularly helpful (EOF).
