### ISSUE TITLE
Proposal: Add api to modify docker daemon labels

### ISSUE THREAD

**Issue by feiyang21687** [docker/docker#16203]
Hi guys,

We use swarm as orchestration tools. And we add labels on docker daemon to let swarm to do some specific scheduling, such as schedule redis container to the docker daemon which has ```ssd``` label.

But in some case, we need to change the docker daemon labels, such as we want add MapR-ability label to some daemon in the midnight, so the map reduce container could be scheduled to this daemon. 

There's no API to change the daemon labels on the fly, and we can't afford to restart daemon. So we want add API to do that, such as:

```
Usage: docker labels [COMMAND] [OPTION]

Manage docker daemon labels:

list - show the docker daemon labels.
add - add new labels to docker daemon, docker labels add --label=[k=v]
remove - remove any exist labels from docker daemon, docker labels remove --label=[k]
```

**Comment by jimmyxian** [comment]
Pretty good, I like this idea.

**Comment by hacpai** [comment]
Would be great :) :+1:

**Comment by feiyang21687** [comment]
@hacpai Let's do it.

**Comment by hacpai** [comment]
@feiyang21687 Okay, I finished it.
https://github.com/docker/docker/pull/16583

**Comment by feiyang21687** [comment]
ping @cpuguy83

**Comment by calavera** [comment]
As I mentioned in #16583, this feature is too narrow. We've had discussions about having a more general command to change configuration options in the daemon that could be in a better scope than this.

Thanks for opening the issue, it helps us notice those little details we need to nail down better. I'm going to close this issue since we won't implement it.

**Comment by bluefishforsale** [comment]
I would also appreciate a manner to add / remove labels from running docker daemons without having to restart all containers on the host where the daemon is running.

**Comment by thaJeztah** [comment]
You can set labels in the `daemon.json` and reload the daemon, without restarting containers; see https://docs.docker.com/engine/reference/commandline/dockerd/#configuration-reloading
