### ISSUE TITLE
 docker  run -itd  -m 100m stress /bin/bash  can`t  limit the container memory

### ISSUE THREAD

**Issue by fireflyhoo** [docker/docker#16204]
if dispose of  -d the limt  is succs

my docker  info 

Containers: 3
Images: 6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 12
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-15-generic
Operating System: Ubuntu 15.04
CPUs: 4
Total Memory: 976.6 MiB
Name: argo
ID: JVV3:SFQP:Z7V2:UF72:W37O:DJRI:QWC2:SUD2:6UZX:QFDA:ZDCY:GEXU

system info 

root@argo:/home/argo# uname -a
Linux argo 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by fireflyhoo** [comment]
root@argo:/home/argo# docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64




root@argo:/home/argo# docker info
Containers: 3
Images: 6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 12
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-15-generic
Operating System: Ubuntu 15.04
CPUs: 4
Total Memory: 976.6 MiB
Name: argo
ID: JVV3:SFQP:Z7V2:UF72:W37O:DJRI:QWC2:SUD2:6UZX:QFDA:ZDCY:GEXU


root@argo:/home/argo# uname -a
Linux argo 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cpuguy83** [comment]
Can you provide some extra details?
How are you testing that ram is not limited?

**Comment by fireflyhoo** [comment]
root@argo:~# docker run -itd -m 100M --name=red stress
f0c34c049387de49752485d93aff275c153f1528fcf9e723f2744c4577a12829
root@argo:~# docker-enter red
Last login: Thu Sep 10 02:19:00 UTC 2015
[root@f0c34c049387 ~]# stress --vm 1 --vm-bytes 300M --vm-hang 0
stress: info: [36] dispatching hogs: 0 cpu, 0 io, 1 vm, 0 hdd




^Z
[1]+  Stopped                 stress --vm 1 --vm-bytes 300M --vm-hang 0
[root@f0c34c049387 ~]# 


root@argo:~# docker run -it -m 100M --name=bule stress /bin/bash
[root@19b741de2a4c /]#  stress --vm 1 --vm-bytes 300M --vm-hang 0
stress: info: [18] dispatching hogs: 0 cpu, 0 io, 1 vm, 0 hdd
stress: FAIL: [18] (420) <-- worker 19 got signal 9
stress: WARN: [18] (422) now reaping child worker processes
stress: FAIL: [18] (456) failed run completed in 1s
[root@19b741de2a4c /]# 


so if i run container in The background ,is  can't limit the memory

**Comment by cpuguy83** [comment]
`docker-enter` is likely not being constrained. This has nothing to do with the container.
`-d` is specifically a client side feature. Without `-d` the client will call `docker attach` once the container is started, with `-d`, it just doesn't.

You can use `docker exec` to get into a container and have the same constraints.
Or you can have your `docker run` start up a shell and then use `docker attach` to access that shell... but this is literally that same as `docker run -it` (no `-d`).
