### ISSUE TITLE
1.8.2-rc1: Docker-in-Docker pid=host fails to stop outer container

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#16206]
If you create a dind setup with --pid=host and launch a container the outer container can not be stopped.  Confusing, right?  Steps to reproduce.  I did this on an Ubuntu 14.04 host but should apply to all environments I assume:

Assuming `./docker` exists

1. Launch DIND

    ./docker run --name dind -it --privileged --pid=host -v /var/lib/docker -v $(pwd)/docker:/usr/bin/docker -v /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt busybox

2. Inside DIND launch Docker:

    docker daemon -D &

3. Launch container:

    docker run -d nginx

4. From host, stop dind outer container

    docker stop dind

You will see the following output from the outer Docker

```
INFO[0593] POST /v1.20/containers/951/stop?t=10         
DEBU[0593] Sending 15 to 951ac2b5f7ba2115fb26599165a5494889a54ccb73af39af1dc09c7cf72b6967 
INFO[0603] Container 951ac2b5f7ba2115fb26599165a5494889a54ccb73af39af1dc09c7cf72b6967 failed to exit within 10 seconds of SIGTERM - using the force 
DEBU[0603] Sending 9 to 951ac2b5f7ba2115fb26599165a5494889a54ccb73af39af1dc09c7cf72b6967 
WARN[0603] wait: no child processes                     
INFO[0613] Container 951ac2b5f7ba failed to exit within 10 seconds of kill - trying direct SIGKILL 
DEBU[0613] Cannot kill process (pid=3924) with signal 9: no such process. 
```

Doing a `ps` you see that `nginx`'s parent is now the host PID 1 and that the inner docker process has been killed.  A `docker ps` will show

````
951ac2b5f7ba        busybox             "/bin/sh"           11 minutes ago      Up 11 minutes                           dind
````

As you can see that container is considered running, but in fact the container PID is dead.  Any attempt to stop/kill the container will now result in the following

```
DEBU[0613] Cannot kill process (pid=3924) with signal 9: no such process. 
```

**Comment by ibuildthecloud** [comment]
I'm going to try my best to figure out what's going on here.

**Comment by ibuildthecloud** [comment]
Here's my stab in the dark guess at what is happening.  For pid host when Docker goes to destroy a container is does a freeze, kills all PIDs in the cgroup, and then thaw.  The current `GetPids()` code doesn't the look for subdirectories in the cgroup to collect the pids but instead just looks at `cgroup.procs`.  So we freeze, kill some process, thaw, and then some processes remain.

Now I just made this up on the stop, so I haven't validated anything I just said.

**Comment by LK4D4** [comment]
@ibuildthecloud did that work before? 
I'll take a look tomorrow, too.

**Comment by ibuildthecloud** [comment]
@LK4D4 It must have, because this is how RancherOS works today (which is still using 1.7).  In 1.8 did the cgroups become nested?  Was it previously just a flat /docker/:id structure always?

**Comment by LK4D4** [comment]
@ibuildthecloud I think they always was sorta nested. But before you needed to mount them by dind, now they mounted by docker.

**Comment by LK4D4** [comment]
I personally have panic on master :)

**Comment by ibuildthecloud** [comment]
@LK4D4 I have a working fix for this at https://github.com/ibuildthecloud/docker/commit/5a54db0c00d19ceb17fe379090b49e40da54d9e1 but I haven't put in a PR with runc because I had troubles writing a test case.  Still working on it.

**Comment by thaJeztah** [comment]
@ibuildthecloud are you still working on this? Just noticed you didn't open a PR (yet) :smile:

**Comment by ibuildthecloud** [comment]
Totally forgot about this one...

**Comment by icecrime** [comment]
@ibuildthecloud Is that still a problem on master?
