### ISSUE TITLE
Splunk driver

### ISSUE THREAD

**Issue by glennblock** [docker/docker#16207]
Hello Docker community!

I work on [Splunk's] (http://www.splunk.com) core platform. We've been seeing interest from customers in pushing logs captured from containers to Splunk. Once in Splunk, customers would like to utilize Splunk's query, reporting, dash-boarding and alerting to monitor their Docker containers.

We're interested in contributing a log driver for Splunk. The driver will push events to the new [HTTP Event Collector] (http://dev.splunk.com/view/event-collector/SP-CAAAE6M) in Splunk 6.3. With the driver in place, a Docker user will be able to select the driver and specify their  Splunk host information after which events will start to flow. The new driver would be compatible with [Splunk Enterprise] (http://www.splunk.com/en_us/products/splunk-enterprise.html), [Splunk Light] (http://www.splunk.com/en_us/products/splunk-light.html), and [Splunk Cloud] (http://www.splunk.com/en_us/products/splunk-cloud.html).

We'd love your feedback on this proposed work. We're keen on pushing this forward!

# High level design

* A new `splunk` log-driver will be introduced in the docker command line
* A `\daemon\loggers\splunk` folder will be added containing the driver. The driver will push events to the HTTP Event Collector. This approach will remove the need to have any additional Splunk-specific components deployed within Docker such as [this] (http://blogs.splunk.com/2015/08/24/collecting-docker-logs-and-stats-with-splunk/) post 
* The driver will have automatic retry logic to handle cases where the endpoint is unavailable.

# Command line options
The `--log-opt NAME=VALUE` flag to specify these additional Splunk
logging driver options.

  - `splunk-token` required, Splunk [HTTP Event Collector token] (http://dev.splunk.com/view/event-collector/SP-CAAAE7C)
  - `splunk-url` required, path to your Splunk instance including scheme and HTTP Event Collector port.  `https://your_splunk_instance:8088`.
  - `splunk-source` optional, event source
  - `splunk-sourcetype` optional, event source type
  - `splunk-host` optional, host where the event originated
  - `splunk-index` optional, index where the event will be stored
  - `splunk-capath` optional, path to root certificate.
  - `splunk-caname` optional, name which should be used for validating server
      certificate, by default the hostname of the `splunk-url` will be used
  - `splunk-insecureskipverify` optional, ignore server certificate validation

Example of the logging option specified for the Splunk Enterprise instance
installed locally on the same box where is Docker daemon is running, HTTPS schema
is used with specified path to the root certificate and Common Name which
should be used for verification (`SplunkServerDefaultCert` is a name, which is
used for autogenerated by Splunk certificates)

`docker run --log-driver=splunk \
    --log-opt splunk-token=6F68ABCB-0168-4D88-B186-677BF575ECA6 \
    --log-opt splunk-url=https://localhost:8088 \
    --log-opt splunk-capath=/opt/splunk/etc/auth/cacert.pem \
    --log-opt splunk-caname=SplunkServerDefaultCert `

**Comment by phemmer** [comment]
I think the `splunk-url` option should support having the username/password in it (either in addition to `splunk-user` and `splunk-pwd` options, or instead of). E.G. `https://user:pass@splunk.example.com:8089`.

I think `splunk-pwd` would be better as `splunk-pass`. "pwd" sounds too much like "present working directory", and is not a typical name for a password parameter.

There should also be a way to set the index.

**Comment by halr9000** [comment]
Agreed with @phemmer regarding PWD.

**Comment by glennblock** [comment]
@phemmer Thanks for the input!

* Agreed on `splunk-pwd`, it was originally `splunk-password` I've reverted it back. 
* I've added `splunk-index`. 
* As to supporting the user/pass in the uri, that should work as long as we don't pre-validate that user/pass are specified in config. I'll look into it.

**Comment by glennblock** [comment]
Question for folks on the Docker team. How should we handle retry? Is there any specific mechanism in Docker for doing this? As this is an HTTP endpoint, we have the possibility to detect if the events were received (unlike UDP). Is it worth us baking in an auto-retry mechanism?

**Comment by outcoldman** [comment]
Few more questions about implementation:

If we (Splunk) are going to implement ILogger interface, what are the expectations for implementation of [Log method](https://github.com/docker/docker/blob/master/daemon/logger/logger.go#L36):

- Do we need to do anything in this method to be sure that we are not blocking callers? Do you expect us to make HTTP calls using goroutine or it is ok to call it right from the Log message?
- (repeats @glennblock question) Because we are going to use HTTP - we may be able to get acknowledgement of receiving, which means that we can implement retry logic. At the same time I see that Log method returns error. So the question is - should we implement retry logic, or is the Caller going to have a retry logic / backup drivers when error happens?

**Comment by cpuguy83** [comment]
+1 to a splunk driver, some thoughts:

1. Please implement go bindings in a separate project that can be vendored into the project
2. Retry logic is fine, but need to be careful about how many messages can stay queued up (ie, in memory).
3. See the aws cloudwatch log driver which was recently added

ping @LK4D4

**Comment by glennblock** [comment]
Great @cpuguy83. Thanks for weighing in. We will look into this. We're planning to send a PR in the next few days.

**Comment by glennblock** [comment]
Hi folks. We've just launched a new token-based direct event collection capability which is much more performant, scalable and secure for sending data like Docker data directly.

We'll be sending a PR shortly which uses the new capability.

@cpuguy83 the PR is not ready yet to merge, and we will update based on your feedback.

**Comment by glennblock** [comment]
I've updated the issue description to reflect the changes.

**Comment by phylake** [comment]
:+1: Looking forward to this. Thanks @glennblock

**Comment by glennblock** [comment]
Cook @phylake!

**Comment by glennblock** [comment]
@cpuguy83 can you give more input on the 'vendoring in' aspect? We don't depend on any splunk lib or anything.

**Comment by glennblock** [comment]
@phylake can you take a look at this? https://github.com/splunk/docker/pull/1. I think it is what you said you wanted at reinvent.

**Comment by glennblock** [comment]
👍

**Comment by glennblock** [comment]
FYI we just blogged on the new driver here: http://blogs.splunk.com/2015/12/16/splunk-logging-driver-for-docker

**Comment by juniorjbn** [comment]
Maybe the splunk driver could receive more than one host in **"--log-opt splunk-url"** for the cases splunk running in cluster ?

**Comment by glennblock** [comment]
Thanks for the suggestion. With HEC the recommendation is always to have a
load balancer in front of the HEC pool. Based on that I don't think we need
clustering support. Also that will complicate the implementation.
