### ISSUE TITLE
double add on the same file don't overwrite it 

### ISSUE THREAD

**Issue by nigifabio** [docker/docker#16214]
as example 
FROM xxxx 
...
...
ADD go.sudo.1 /etc/sudoers.d/go

(actions)

ADD go.sudo.2 /etc/sudoers.d/go

the result image at the end contains go.sudo.1 as source instead of go.sudo.2

**Comment by HuKeping** [comment]
Any step to reproduce this please? I tried with the docker from the master branch and everything seems fine.

**Comment by duglin** [comment]
When I try a Dockerfile like:
```
FROM ubuntu
ADD file1 /etc/sudoers.d/go
RUN cat /etc/sudoers.d/go
ADD file2 /etc/sudoers.d/go
RUN cat /etc/sudoers.d/go
```
I don't see the issue - the 'cat's show the correct output. Can you give more details on how to reproduceit?

**Comment by cpuguy83** [comment]
Hello, I'm going to close this for now, but if you can provide more details, please ping here so we can take a look.

thanks!
