### ISSUE TITLE
environment variables are not exported to child processes anymore

### ISSUE THREAD

**Issue by sealor** [docker/docker#16217]
# BUG REPORT INFORMATION
Hi folks,

I noticed a bug in Docker version 1.8.2-rc1 and 1.7.0. The Docker version 1.6.2 is working for me.
Please fix this issue in the following releases. Thank you!

**Key information from my environment**
```
stefan@ubuntu:~$ docker version
Client:
 Version:      1.8.2-rc1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   28220ac
 Built:        Thu Sep  3 19:15:10 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2-rc1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   28220ac
 Built:        Thu Sep  3 19:15:10 UTC 2015
 OS/Arch:      linux/amd64
```
```
stefan@ubuntu:~$ docker info
Containers: 2
Images: 4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 8
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-63-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 994 MiB
Name: ubuntu
ID: AMXD:FNGU:ZVFH:NAMJ:MUSU:Y6IU:N6ZG:4UYH:J7RU:XGRT:USCS:AVSR
Http Proxy: http://q369740:firefo12@proxy.muc:8080
WARNING: No swap limit support
```
```
stefan@ubuntu:~$ uname -a
Linux ubuntu 3.13.0-63-generic #103-Ubuntu SMP Fri Aug 14 21:42:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
* Docker is started in VirtualBox 4.3.26 r98988 on Windows 7 64 bit

**Steps to reproduce the bug**
1. run a new ubuntu container (`docker run -t -i ubuntu /bin/bash`)
2. create a exported env variable (`export ABC=DEF`)
3. fork a simple process (`sleep 60 &`)
4. check the env variables of that process (`ps e a`)
There should be a line like this containing the variable `ABC=DEF`:
`   16 ?        S      0:00 sleep 60 ABC=DEF HOSTNAME=910e219675d5 TERM=xterm LS_COLORS=rs` ...
But with Docker version 1.8.2-rc1 there is only the following output:
`   16 ?        S      0:00 sleep 60`

**Console output with Docker 1.8.2-rc1 (bug)**
```
stefan@ubuntu:~$ docker run -t -i ubuntu /bin/bash
root@80aea8a1a7f6:/# export ABC=DEF
root@80aea8a1a7f6:/# sleep 60 &
[1] 16
root@80aea8a1a7f6:/# ps e a
  PID TTY      STAT   TIME COMMAND
    1 ?        Ss     0:00 /bin/bash
   16 ?        S      0:00 sleep 60
   17 ?        R+     0:00 ps e a ABC=DEF HOSTNAME=80aea8a1a7f6 TERM=xterm LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40
root@80aea8a1a7f6:/# exit
```

**Console output with Docker 1.6.2 (working)**
```
stefan@ubuntu:~> docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
stefan@ubuntu:~> docker run -t -i ubuntu /bin/bash
root@baa686202a86:/# export ABC=DEF
root@baa686202a86:/# sleep 60 &
[1] 15
root@baa686202a86:/# ps e a
  PID TTY      STAT   TIME COMMAND
    1 ?        Ss     0:00 /bin/bash PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOSTNAME=baa686202a86 TERM=x
   15 ?        S      0:00 sleep 60 ABC=DEF HOSTNAME=baa686202a86 TERM=xterm LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;
   16 ?        R+     0:00 ps e a ABC=DEF HOSTNAME=baa686202a86 TERM=xterm LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35
root@baa686202a86:/# exit
```

**Comment by duglin** [comment]
@sealor I'm not sure where the issue is but I'm not sure its docker. I just tried the latest and v1.6.2 and I'm seeing the same thing in both. And in both cases I'm not seeing the env var listed for "sleep" on the "ps e a" output.

In your newer docker, instead of running "sleep" try just running "sh" and see if "ABC" shows up in that shell. If it does then there's something outside of docker's control going on - I think.

**Comment by coolljt0725** [comment]
@sealor  I try the master branch, it works
<pre><code>$ docker run -ti --rm ubuntu
root@393017e4711c:/# export ABC=DEF
root@393017e4711c:/# sleep 60 &
[1] 8
root@393017e4711c:/# ps e a
  PID TTY      STAT   TIME COMMAND
    1 ?        Ss     0:00 /bin/bash PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOSTNAME=393017e4711c TERM=xterm HOME=/
    8 ?        S      0:00 sleep 60 ABC=DEF HOSTNAME=393017e4711c TERM=xterm PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin PWD=/ S
    9 ?        R+     0:00 ps e a ABC=DEF HOSTNAME=393017e4711c TERM=xterm PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin PWD=/ SHL
root@393017e4711c:/#
</code></pre>

<pre><code>$ docker version
Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   6efe459-dirty
 Built:        Thu Sep 10 02:31:12 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   6efe459-dirty
 Built:        Thu Sep 10 02:31:12 UTC 2015
 OS/Arch:      linux/amd64
</code></pre>

**Comment by sealor** [comment]
@duglin and @coolljt0725 
Thank you for your help. I agree with you: it seams to be a problem with Ubuntu 14.04 Mini.
The bug does not appear in Ubuntu **15.04** Mini. Docker works like a charm. :-)

The following setup didn't work for me (I tried it two times ...):
* Ubuntu 14.04 Mini (http://archive.ubuntu.com/ubuntu/dists/trusty/main/installer-amd64/current/images/netboot/mini.iso)
* VirtualBox 4.3.26 r98988 on Windows 7 64 bit
