### ISSUE TITLE
docker logs -f is no longer following the logs

### ISSUE THREAD

**Issue by JensPiegsa** [docker/docker#16212]
I recognized that my current docker installation does no longer follow the log output for a running container executed by `docker logs -f <container>`. The actual behavior is the same as without the `-f` switch and it applies to both the Windows client, and the Linux client accessed via SSH.

>docker-machine version 0.4.0 (9d0dc7a)
Docker version 1.8.1, build d12ea79

This may relate to [this issue](https://github.com/docker/docker/issues/4801).

**Comment by duglin** [comment]
@JensPiegsa can you give a little more info on your exact scenario?  I just tried it and it seems to work ok for me - but perhaps you're flow is different.  The exact (minimal) commands needed to reproduce it would be great.

**Comment by cpuguy83** [comment]
`docker logs -f` uses inotify to notify listeners that there is more log data to read. If inotify does not work on your system for one reason or another, this would be the problem.
Note that this is all done on the daemon.

Assuming this is a dup of #15815

**Comment by txus** [comment]
I'm having the same problem when running docker inside Vagrant.
