### ISSUE TITLE
i want to share files with docker container on my OSX by samba ,but it not work

### ISSUE THREAD

**Issue by fyddaben** [docker/docker#16216]
### i open my OSX share file ,it tells by 
```
smb://192.168.11.1
```
### so , i install samba-client on my docker container(centos) ,and i typed
```
smbclient //192.168.11.1/data -U fanyongdong
```
### it turns out
```
dos charset 'CP850' unavailable - using ASCII
session setup failed: NT_STATUS_LOGON_FAILURE
```

### is there anyone samba success?

**Comment by cpuguy83** [comment]
Can the container reach that IP?
Can you get more verbose output?

I'm going to close this because it is not really a docker issue so much as how to use smbclient in a container.
Please feel free to reach me on #docker on IRC, or docker-user ML, or forums.docker.com
Thanks!

**Comment by fyddaben** [comment]
ok. i use sshfs solve my problem .
