### ISSUE TITLE
Services in containers: <service> dead but pid file exists 

### ISSUE THREAD

**Issue by rootAmeen** [docker/docker#16223]
Hey guys,

I've looked around for a solution to this but I couldn't find something working for my case.

I created a custom image of centos with some services that I need to run on multiple containers in the same time. I already chkconfig'd the services and started them before commiting the container.

Now when I run a new container based on this image I created, it goes up, but the services I installed face the following error: 

\<service-name> dead but pid file exists

\<service-name>' is any services I installed and started on the container.

Any help is appreciated.

Regards,

**Comment by phemmer** [comment]
> I already chkconfig'd the services and started them before commiting the container.

Images don't preserve running processes. Images are essentially a snapshot of the filesystem. Thus you're starting something, the PID file is created, and then you create a snapshot of the filesystem. So when you create a container based on that snapshot, there is no process matching the PID file.

The issue tracker is generally for bugs, and feature requests.
For getting something like this working, I'd try the [mailing list](https://groups.google.com/forum/#!forum/docker-user), the [forums](https://forums.docker.com/), or irc (irc.freenode.net #docker).
Chances are someone has done something similar to whatever you're trying to accomplish.

**Comment by cpuguy83** [comment]
@phemmer Is right.
Also chkconfig will not start up services when you start up a container unless you are somehow starting up the init procedure.

Closing to help keep things tidy in the issue tracker.
Please feel free to ping on #docker on IRC, docker-user ML, or forums.docker.com
Thanks!
