### ISSUE TITLE
Docker Hub repository Markdown strips out non-HTTPS links

### ISSUE THREAD

**Issue by emersonf** [docker/docker#16234]
When writing Markdown descriptions for repositories on Docker Hub,

```Markdown
[foo](https://foo)
```
gets rendered as a link, but 

```Markdown
[foo](http://foo)
```
gets completely stripped out.

See https://forums.docker.com/t/repository-full-description-field-eliminates-markdown-http-links/3124/1 for a similar report.

**Comment by albers** [comment]
I can confirm that http links get stripped. Didn't try https.

**Comment by emersonf** [comment]
It looks like this issue is being tracked in the [hub-beta-feedback](https://github.com/docker/hub-beta-feedback/issues/195) repo.
