### ISSUE TITLE
RUN instruction in shell mode is not consistant with other executions

### ISSUE THREAD

**Issue by AmeBel** [docker/docker#16239]
##### Description of problem:
 A `bin/bash -c` will run a single quoted string of commands without the need of `\`, on newlines, seemlessly. On docker build `Error response from daemon: ENV must have two arguments` is returned.

It might just be my lack of understanding of how the different shells work, or a missing documentation or a bug. Need clarification.

##### Environment details
```
>> docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:21:21 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:21:21 UTC 2015
 OS/Arch:      linux/amd64

>> docker info
Containers: 16
Images: 451
Storage Driver: btrfs
 Build Version: Btrfs v3.17
 Library Version: 101
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-28-generic
Operating System: Ubuntu 15.04
CPUs: 8
Total Memory: 15.57 GiB
Name: zleno
ID: SQQC:7JHE:SHHA:5WGK:77ST:KSP6:6ROK:SKRB:GSUB:KKJZ:MSN6:IJFS
WARNING: No swap limit support

>> uname -a
Linux zleno 3.19.0-28-generic #30-Ubuntu SMP Mon Aug 31 15:52:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
##### Steps to Reproduce:
1. Dockerfile content
```
FROM ubuntu

RUN  /bin/bash -c 'echo "-------------------------------------------- start" ;
                   echo $HOME ;
                   echo "-------------------------------------------- echo home" ;
                   env ;
                  '
```
2. Command 
```
>> docker build -t test .
Sending build context to Docker daemon 2.048 kB
Error response from daemon: ENV must have two arguments
```

##### Expected Results:
```
>> docker build -t test2 .
Sending build context to Docker daemon 2.048 kB
Step 0 : FROM ubuntu
 ---> 91e54dfb1179
Step 1 : RUN /bin/bash -c 'echo "-------------------------------------------- start" ;                   echo $HOME ;                   echo "-------------------------------------------- echo home" ;                   env ;                  '
 ---> Running in 5db70c358859
-------------------------------------------- start
/root
-------------------------------------------- echo home
HOSTNAME=e611e15f9c9d
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
SHLVL=1
HOME=/root
_=/usr/bin/env
 ---> a3c06f9cd4ca
Removing intermediate container 5db70c358859
Successfully built a3c06f9cd4ca

```

##### Additional info:
Expected result was gained by using the following Dockerfile content
```

FROM ubuntu

RUN  /bin/bash -c 'echo "-------------------------------------------- start" ;\
                   echo $HOME ;\
                   echo "-------------------------------------------- echo home" ;\
                   env ;\
                  '

```

**Comment by phemmer** [comment]
Unfortunately this has nothing to do with bash, or shells in general. This is just how the dockerfile syntax works. Any time you want to continue an instruction onto the next line, it has to be ended with a backslash.
You could argue that docker should be intelligent to see that opening single quote, and that until it sees a non-escaped single quote, it should treat every character as part of the argument. But the dockerfile parser is very basic. And unfortunately changing this behavior would be a very significant breaking change as everyone is used to the current behavior.

As a general rule, when embedding one language inside another (in this case, bash inside dockerfile), you just have to keep in mind the separation between languages.

**Comment by AmeBel** [comment]
Thanks @phemmer just made pull request documenting you response.

**Comment by thaJeztah** [comment]
> just made pull request documenting you response.

Thanks @AmeBel :+1:
