### ISSUE TITLE
Mounting in running container not working again

### ISSUE THREAD

**Issue by pyotr777** [docker/docker#16233]
See #9448 

After upgraded Docker from 1.5 to 1.8.1 the solution on previous issue stopped working.
The solution was to start container with  ```--cap-add SYS_ADMIN --device /dev/fuse```.

In 1.8.1 I start container 
```docker run -ti --cap-add SYS_ADMIN --device /dev/fuse ...```
In container:
```sshfs -o StrictHostKeyChecking=no -p <port> <user>@<address>:"<dir>" "<dir>"```
and get error:
```fuse: mount failed: Permission denied```

In dmesg:
```[86690.569280] type=1400 audit(1441943381.165:51): apparmor="DENIED" operation="mount" info="failed flags match" error=-13 profile="docker-default" name="<dir>" pid=26423 comm="sshfs" fstype="fuse.sshfs" srcname="<user>@<address>:<dir>" flags="rw, nosuid, nodev"```

In /etc/apparmor.d/docker I can see
```
   deny mount,
```

Is this the reason I cannot mount?

docker version:
```
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:32:18 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:32:18 UTC 2015
 OS/Arch:      linux/amd64
```
My OS:
```Linux poweredge320 3.13.0-63-generic #104~precise1-Ubuntu SMP Tue Aug 18 17:03:03 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux```
Docker info:
```
Containers: 8
Images: 277
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 302
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-63-generic
Operating System: Ubuntu precise (12.04.4 LTS)
CPUs: 4
Total Memory: 3.813 GiB
Name: poweredge320
ID: EBVC:QV4Q:T7BF:F7CW:EB4Y:JE3X:DO2V:FTNB:PHOI:TPWO:K4MX:W7LR
Username: pyotr777
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Comment by cpuguy83** [comment]
Closing since this is a dup of #16429

**Comment by ewindisch** [comment]
AppArmor can be disabled per-container using '--security-opt apparmor:unconfined'.

**Comment by pyotr777** [comment]
Thank you @ewindisch !
```
--cap-add SYS_ADMIN --device /dev/fuse --security-opt apparmor:unconfined
```
works for me.
