### ISSUE TITLE
Proposal: Should json-file logging driver be renamed to ors or ors-file instead?

### ISSUE THREAD

**Issue by ibnesayeed** [docker/docker#16230]
I liked the idea of having flexible and expressive JSON messages squeezed in a single line and create a stream of them one per line for logging. I liked the idea of breaking single root node restriction posed by JSON which makes parsing JSON a nightmare for long files. I also like the idea of adding some additional lookup key information in front of each entry such as timestamp or something else (for example fluentd adds one or more keys in front of each JSON block). This helps using text processing tools like grep, awk, sort, and cut etc. on such files while keeping the data portion as flexible as possible.

I am a Web archive researcher. We have huge file based indexes. For quite some time we were using a predefined column based format called CDX which is very specific to Web archiving needs and it does not have a lot of options for extension. Some time ago an archiving tool developer realized that we can combine CDX and JSON to bring more flexibility in it, we called it CDX-JSON or CDXJ. Later I found that similar format is already being used in Docker and Fluentd logs and is quite useful.

However, calling them JSON as a whole is technically incorrect and no JSON parser will parse such files. To me, they are stream of objects instead and deserve their own media type, which allow general tooling around this format. For this purpose we are trying to formalize this format and if enough interest is shown, we are planning to write an RFC for this. I have published [a blog post about the ORS](http://ws-dl.blogspot.com/2015/09/2015-09-10-cdxj-object-resource-stream.html) and would like to hear some thoughts from the Docker community on it. First half of the blog post might not be very relevant to some people as it is specifically talking about an archiving related issue, but the portion where couple of railroad diagrams are added is more general description of the Object Resource Stream (ORS) serialization.

![Object Resource Stream (ORS)](http://4.bp.blogspot.com/-7NUHdUWRC6E/VenV6AlqGnI/AAAAAAAAe0I/JtslxAIHrkQ/s1600/ors-railroad.png)

**Comment by LK4D4** [comment]
This stuff is called json everywhere(python, golang), but I agree it's sorta incorrect. However,  changing name will bring more problem than profits. I'm closing issue, because naming is hard and renaming is insanely hard.
