### ISSUE TITLE
Static vs Dynamic docker binary

### ISSUE THREAD

**Issue by chrisskilton** [docker/docker#16236]
Is there any chance docker could be shipped with a static binary _as well as_ the now dynamic one on debian? Is there a better practice way to forward the docker binary into a container? Usually would use `-v $(which docker):$(which docker)` (which works in 1.8.2 using boot2docker) but that does not work in 1.8.2 on a linux (Debian wheezy) distro due to the dynamic binary (was static in 1.4.x). Is jpetazzo's dind image a better route (forwarding on just the socket instead)? 

docker version:
```
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:12:52 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:12:52 UTC 2015
 OS/Arch:      linux/amd64
```

docker info:
```
Containers: 103
Images: 194
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: xfs
 Dirs: 444
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.2.0-4-amd64
Operating System: Debian GNU/Linux 7 (wheezy)
CPUs: 8
Total Memory: 31.41 GiB
WARNING: No memory limit support
WARNING: No swap limit support
```

uname -a:

```
Linux ludo 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u1 x86_64 GNU/Linux
```

command to illustrate problem: `docker run -v "$(which docker):$(which docker)" ubuntu docker version` yields `docker: error while loading shared libraries: /lib/x86_64-linux-gnu/libapparmor.so.1: cannot read file data: Error 21`

Sorry if this isn't the right place for it.

**Comment by cpuguy83** [comment]
You can get the static binary from `https://get.docker.com/builds/Linux/x86_64/docker-latest`.
The static binary won't be packaged with the deb/rpm packages any more.

**Comment by chrisskilton** [comment]
Thanks!

**Comment by cowlinator** [comment]
@cpuguy83 , the url link you posted no longer works.  Where can I find the latest static binary for docker?

**Comment by cpuguy83** [comment]
@cowlinator Probably if you want to get a static binary you'll need to build it yourself.
See `hack/dockerfile/install/runc.installer` in this repo for an example of how we do this for the docker dev environment.
