### ISSUE TITLE
Document how to generate pluginrpc clases

### ISSUE THREAD

**Issue by calavera** [docker/docker#16248]
As far as I know, we don't have documentation about how the volume, networking and other external driver proxies are generated. I don't think we have a make command to generate them. We should add documentation and a script to facilitate those tasks.

**Comment by calavera** [comment]
@cpuguy83 I'd really appreciate to have this. Otherwise, the generators are not very useful if people don't know who to use them, specially me :smile_cat:

**Comment by cpuguy83** [comment]
Sure, I'll work on this.
