### ISSUE TITLE
Update docs: systemd service doesn't load sysconfig file for daemon startup options

### ISSUE THREAD

**Issue by dgersting** [docker/docker#16251]
It seems the systemd service file doesn't load the config file from sysconfig which prevents any docker startup options from taking effect.

Doc reference: https://docs.docker.com/articles/configuring/#configuring-docker-1

**Comment by villlem** [comment]
There is doc oriented to systemd https://docs.docker.com/articles/systemd/

**Comment by thaJeztah** [comment]
Thanks for reporting, @dgersting. @villlem is right, that the preferred approach is to use drop-in files to configure the docker daemon when using SystemD. Unfortunately that docs seems to still refer to using `/etc/sysconfig/docker` to do so.

I think the right solution is to update the docs you're referring to, and explain / link to the documentation that explains using drop-ins.

Would you be interested in opening a PR to make this change?

**Comment by thaJeztah** [comment]
I updated the title, also /cc @moxiegirl

**Comment by dgersting** [comment]
@thaJeztah Okay, I'll take a look at writing a PR for the docs when I get a chance in the next couple days.

**Comment by thaJeztah** [comment]
Awesome! Feel free to let us know if you need help, or don't have time to do do so. :+1:

**Comment by dgersting** [comment]
What's the advantage to using drop-in files as opposed to the way it's currently in the doc?

To me it seems much more error prone (as evident in #14491 which I actually just got burned by) because having to add `ExecStart` twice isn't obvious.

It also feels like a bad idea having to copy the `ExecStart` line from the upstream service file which makes any changes (like the -d to daemon change) volatile since my drop-in file won't get that change when the underlying docker package changes.

I can see the power of drop-ins for some use-cases, but I'm not sure I see the advantage of having it as the only/default way to customize the systemd service. (especially for new users)

**Comment by thaJeztah** [comment]
@dgersting fair question, it's come up various times; I think these comments; https://github.com/docker/docker/pull/5141#issuecomment-40940481, https://github.com/docker/docker/pull/5141#issuecomment-40137703 describes the reasoning behind it. Also, this thread (and all issues linked from/to it) contains some background on the decision; https://github.com/docker/docker/pull/14513#issuecomment-125009350

**Comment by thaJeztah** [comment]
@dgersting I'm going to close this issue in favor of https://github.com/docker/docker/issues/17586, which is currently being worked on. Please subscribe to that issue to get informed of status updates!

Feel free to comment here after I've close this issue, or if you think I closed this by mistake :smile:
