### ISSUE TITLE
Docker toolbox osx installer hangs on overview

### ISSUE THREAD

**Issue by fronto** [docker/docker#16257]
I downloaded Docker Toolbox osx installer package and ran it and nothing happens, it just hangs on the Overview.

I am using:

 OSX 10.8.5
Docker Toolbox 1.8.2

**Comment by thaJeztah** [comment]
Thanks for reporting, @fronto. I see there's an issue in the Docker Toolbox issue tracker that's tracking this; https://github.com/docker/toolbox/issues/177

I'm going to close this issue, here; please subscribe to https://github.com/docker/toolbox/issues/177 (using the "subscribe" button on that issue), to stay up to date on progress.
