### ISSUE TITLE
Cannot connect to docker after PC woken from sleep

### ISSUE THREAD

**Issue by Mellbourn** [docker/docker#16265]
I have just installed docker using [docker-toolbox 1.8.2][1] on Windows 10.

Due to due to [this issue][2] I had to recreate the docker image using these commands

    docker-machine rm default
    docker-machine --native-ssh create -d virtualbox default

After that it has been working fine, except for one problem:

When the PC has gone to sleep and then wakes again, the docker commands can no longer connect. Example:

    > docker images
    An error occurred trying to connect: Get https://192.168.99.100:2376/v1.20/images/json: 
    dial tcp 192.168.99.100:2376: ConnectEx tcp: A connection attempt failed because the 
    connected party did not properly respond after a period of time, or established connection 
    failed because connected host has failed to respond.

However the `docker-machine` lists the machine as running:

    > docker-machine ls
    NAME      ACTIVE   DRIVER       STATE     URL                         SWARM
    default   *        virtualbox   Running   tcp://192.168.99.100:2376

I can also confirm in VirtualBox that the VM screen seems to be active.

I have tried starting and stopping the machine, but that does not help

    C:\x> docker-machine stop default
    C:\x> docker-machine start default
    Starting VM...
    Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
    C:\x> docker-machine env default --shell=powershell

Ironically, the last command hangs, so I never get any environment settings.

The only thing that helps is to restart the whole PC. But that should be unnecessary?

I have also posted this as [a question on StackOverflow][3]

I am running
Docker version 1.8.2, build 0a8c2e3
On Windows 10 Professional 64bit.

    >uname -a
    MSYS_NT-10.0 Phantom2 2.1.0(0.288/5/3) 2015-06-28 18:57 x86_64 Msys

    C:\x> docker info
    Containers: 1
    Images: 32
    Storage Driver: aufs
     Root Dir: /mnt/sda1/var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 34
     Dirperm1 Supported: true
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 4.0.9-boot2docker
    Operating System: Boot2Docker 1.8.2 (TCL 6.4); master : aba6192 - Thu Sep 10 20:58:17 UTC 2015
    CPUs: 1
    Total Memory: 996.2 MiB
    Name: default
    ID: DBFV:VWPR:CFZV:4KFH:THSV:YV3J:WV5J:T5TI:SFMP:7L27:JI5M:5PK6
    Debug mode (server): true
    File Descriptors: 12
    Goroutines: 16
    System Time: 2015-09-13T16:09:14.620288561Z
    EventsListeners: 0
    Init SHA1:
    Init Path: /usr/local/bin/docker
    Docker Root Dir: /mnt/sda1/var/lib/docker
    Username: mellbourn
    Registry: https://index.docker.io/v1/
    Labels:
     provider=virtualbox

  [1]: https://www.docker.com/toolbox
  [2]: https://github.com/kitematic/kitematic/issues/386#issuecomment-123804467
  [3]: http://stackoverflow.com/questions/32547427/docker-unreachable-after-computer-sleep

**Comment by clnperez** [comment]
I don't have a Windows system to try this on, but do you get any more info if you use the -D option with the env command? docker-machine -D env default --shell=powershell

**Comment by Mellbourn** [comment]
Here is the output:

<pre>
C:\temp> docker-machine -D env default --shell=powershell
executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo default --machinereadable
STDOUT: name="default"
groups="/"
ostype="Linux 2.6 / 3.x / 4.x (64-bit)"
UUID="29e36969-3227-4181-a5a3-24d6506c8df1"
CfgFile="C:\\Users\\Klas\\.docker\\machine\\machines\\default\\default\\default.vbox"
SnapFldr="C:\\Users\\Klas\\.docker\\machine\\machines\\default\\default\\Snapshots"
LogFldr="C:\\Users\\Klas\\.docker\\machine\\machines\\default\\default\\Logs"
hardwareuuid="29e36969-3227-4181-a5a3-24d6506c8df1"
memory=1024
pagefusion="off"
vram=8
cpuexecutioncap=100
hpet="on"
chipset="piix3"
firmware="BIOS"
cpus=1
pae="on"
longmode="on"
cpuid-portability-level=0
bootmenu="disabled"
boot1="dvd"
boot2="dvd"
boot3="disk"
boot4="none"
acpi="on"
ioapic="on"
biossystemtimeoffset=0
rtcuseutc="on"
hwvirtex="on"
nestedpaging="on"
largepages="on"
vtxvpid="on"
vtxux="on"
paravirtprovider="default"
VMState="running"
VMStateChangeTime="2015-09-18T20:37:14.823000000"
monitorcount=1
accelerate3d="off"
accelerate2dvideo="off"
teleporterenabled="off"
teleporterport=0
teleporteraddress=""
teleporterpassword=""
tracing-enabled="off"
tracing-allow-vm-access="off"
tracing-config=""
autostart-enabled="off"
autostart-delay=0
defaultfrontend=""
storagecontrollername0="SATA"
storagecontrollertype0="IntelAhci"
storagecontrollerinstance0="0"
storagecontrollermaxportcount0="30"
storagecontrollerportcount0="30"
storagecontrollerbootable0="on"
"SATA-0-0"="C:\Users\Klas\.docker\machine\machines\default\boot2docker.iso"
"SATA-ImageUUID-0-0"="bf9d4367-a567-4a67-b91e-fa6a6af82fbd"
"SATA-tempeject"="off"
"SATA-IsEjected"="off"
"SATA-1-0"="C:\Users\Klas\.docker\machine\machines\default\disk.vmdk"
"SATA-ImageUUID-1-0"="b13894f5-f5cf-4404-9406-78b0bfaf5cb0"
"SATA-2-0"="none"
"SATA-3-0"="none"
"SATA-4-0"="none"
"SATA-5-0"="none"
"SATA-6-0"="none"
"SATA-7-0"="none"
"SATA-8-0"="none"
"SATA-9-0"="none"
"SATA-10-0"="none"
"SATA-11-0"="none"
"SATA-12-0"="none"
"SATA-13-0"="none"
"SATA-14-0"="none"
"SATA-15-0"="none"
"SATA-16-0"="none"
"SATA-17-0"="none"
"SATA-18-0"="none"
"SATA-19-0"="none"
"SATA-20-0"="none"
"SATA-21-0"="none"
"SATA-22-0"="none"
"SATA-23-0"="none"
"SATA-24-0"="none"
"SATA-25-0"="none"
"SATA-26-0"="none"
"SATA-27-0"="none"
"SATA-28-0"="none"
"SATA-29-0"="none"
natnet1="nat"
macaddress1="0800274BA2D9"
cableconnected1="on"
nic1="nat"
nictype1="82540EM"
nicspeed1="0"
mtu="0"
sockSnd="64"
sockRcv="64"
tcpWndSnd="64"
tcpWndRcv="64"
Forwarding(0)="ssh,tcp,127.0.0.1,50825,,22"
hostonlyadapter2="VirtualBox Host-Only Ethernet Adapter #2"
macaddress2="08002706BAE8"
cableconnected2="on"
nic2="hostonly"
nictype2="82540EM"
nicspeed2="0"
nic3="none"
nic4="none"
nic5="none"
nic6="none"
nic7="none"
nic8="none"
hidpointing="ps2mouse"
hidkeyboard="ps2kbd"
uart1="off"
uart2="off"
lpt1="off"
lpt2="off"
audio="none"
clipboard="disabled"
draganddrop="disabled"
SessionName="headless"
VideoMode="720,400,0"@0,0 1
vrde="off"
usb="off"
ehci="off"
xhci="off"
SharedFolderNameMachineMapping1="c/Users"
SharedFolderPathMachineMapping1="c:\Users"
VRDEActiveConnection="off"
VRDEClients=0
vcpenabled="off"
vcpscreens=0
vcpfile="C:\Users\Klas\.docker\machine\machines\default\default\default.webm"
vcpwidth=1024
vcpheight=768
vcprate=512
vcpfps=25
GuestMemoryBalloon=0
GuestOSType="Linux26_64"
GuestAdditionsRunLevel=2
GuestAdditionsVersion="5.0.4 r102546"
GuestAdditionsFacility_VirtualBox Base Driver=50,1442608650416
GuestAdditionsFacility_VirtualBox System Service=50,1442608658377
GuestAdditionsFacility_Seamless Mode=0,1442608650415
GuestAdditionsFacility_Graphics Mode=0,1442608650415

STDERR:
Using SSH client type: external
About to run SSH command:
ip addr show dev eth1
&{C:\Program Files\Git\usr\bin\ssh.exe [C:\Program Files\Git\usr\bin\ssh.exe -o PasswordAuthentication=no -o IdentitiesO
nly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o Connect
Timeout=10 -i C:\Users\Klas\.docker\machine\machines\default\id_rsa -p 50825 docker@localhost ip addr show dev eth1] []
 <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> false [] [] [] [] <nil>}
SSH cmd err, output: <nil>: 4: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default
qlen 1000
    link/ether 08:00:27:06:ba:e8 brd ff:ff:ff:ff:ff:ff
    inet 192.168.99.100/24 brd 192.168.99.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe06:bae8/64 scope link
       valid_lft forever preferred_lft forever

SSH returned: 4: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:06:ba:e8 brd ff:ff:ff:ff:ff:ff
    inet 192.168.99.100/24 brd 192.168.99.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe06:bae8/64 scope link
       valid_lft forever preferred_lft forever

END SSH

$Env:DOCKER_TLS_VERIFY = "1"
$Env:DOCKER_HOST = "tcp://192.168.99.100:2376"
$Env:DOCKER_CERT_PATH = "C:\Users\Klas\.docker\machine\machines\default"
$Env:DOCKER_MACHINE_NAME = "default"
# Run this command to configure your shell:
# C:\Program Files\Docker Toolbox\docker-machine.exe env --shell=powershell default | Invoke-Expression
C:\temp>
</pre>

**Comment by clnperez** [comment]
Thanks @Mellbourn. So that doesn't look like it hung this time?

**Comment by Mellbourn** [comment]
It didn't hang that time since I had just started docker.

In fact, I left my computer on so that it fell asleep. Now when it has woken again, the same command hangs. The output is now the following.

<pre>
> docker-machine -D env default --shell=powershell
executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo default --machinereadable
STDOUT: name="default"
groups="/"
ostype="Linux 2.6 / 3.x / 4.x (64-bit)"
UUID="29e36969-3227-4181-a5a3-24d6506c8df1"
CfgFile="C:\\Users\\Klas\\.docker\\machine\\machines\\default\\default\\default.vbox"
SnapFldr="C:\\Users\\Klas\\.docker\\machine\\machines\\default\\default\\Snapshots"
LogFldr="C:\\Users\\Klas\\.docker\\machine\\machines\\default\\default\\Logs"
hardwareuuid="29e36969-3227-4181-a5a3-24d6506c8df1"
memory=1024
pagefusion="off"
vram=8
cpuexecutioncap=100
hpet="on"
chipset="piix3"
firmware="BIOS"
cpus=1
pae="on"
longmode="on"
cpuid-portability-level=0
bootmenu="disabled"
boot1="dvd"
boot2="dvd"
boot3="disk"
boot4="none"
acpi="on"
ioapic="on"
biossystemtimeoffset=0
rtcuseutc="on"
hwvirtex="on"
nestedpaging="on"
largepages="on"
vtxvpid="on"
vtxux="on"
paravirtprovider="default"
VMState="running"
VMStateChangeTime="2015-09-19T07:24:31.362000000"
monitorcount=1
accelerate3d="off"
accelerate2dvideo="off"
teleporterenabled="off"
teleporterport=0
teleporteraddress=""
teleporterpassword=""
tracing-enabled="off"
tracing-allow-vm-access="off"
tracing-config=""
autostart-enabled="off"
autostart-delay=0
defaultfrontend=""
storagecontrollername0="SATA"
storagecontrollertype0="IntelAhci"
storagecontrollerinstance0="0"
storagecontrollermaxportcount0="30"
storagecontrollerportcount0="30"
storagecontrollerbootable0="on"
"SATA-0-0"="C:\Users\Klas\.docker\machine\machines\default\boot2docker.iso"
"SATA-ImageUUID-0-0"="bf9d4367-a567-4a67-b91e-fa6a6af82fbd"
"SATA-tempeject"="off"
"SATA-IsEjected"="off"
"SATA-1-0"="C:\Users\Klas\.docker\machine\machines\default\disk.vmdk"
"SATA-ImageUUID-1-0"="b13894f5-f5cf-4404-9406-78b0bfaf5cb0"
"SATA-2-0"="none"
"SATA-3-0"="none"
"SATA-4-0"="none"
"SATA-5-0"="none"
"SATA-6-0"="none"
"SATA-7-0"="none"
"SATA-8-0"="none"
"SATA-9-0"="none"
"SATA-10-0"="none"
"SATA-11-0"="none"
"SATA-12-0"="none"
"SATA-13-0"="none"
"SATA-14-0"="none"
"SATA-15-0"="none"
"SATA-16-0"="none"
"SATA-17-0"="none"
"SATA-18-0"="none"
"SATA-19-0"="none"
"SATA-20-0"="none"
"SATA-21-0"="none"
"SATA-22-0"="none"
"SATA-23-0"="none"
"SATA-24-0"="none"
"SATA-25-0"="none"
"SATA-26-0"="none"
"SATA-27-0"="none"
"SATA-28-0"="none"
"SATA-29-0"="none"
natnet1="nat"
macaddress1="0800274BA2D9"
cableconnected1="on"
nic1="nat"
nictype1="82540EM"
nicspeed1="0"
mtu="0"
sockSnd="64"
sockRcv="64"
tcpWndSnd="64"
tcpWndRcv="64"
Forwarding(0)="ssh,tcp,127.0.0.1,50825,,22"
hostonlyadapter2="VirtualBox Host-Only Ethernet Adapter #2"
macaddress2="08002706BAE8"
cableconnected2="on"
nic2="hostonly"
nictype2="82540EM"
nicspeed2="0"
nic3="none"
nic4="none"
nic5="none"
nic6="none"
nic7="none"
nic8="none"
hidpointing="ps2mouse"
hidkeyboard="ps2kbd"
uart1="off"
uart2="off"
lpt1="off"
lpt2="off"
audio="none"
clipboard="disabled"
draganddrop="disabled"
SessionName="headless"
VideoMode="720,400,0"@0,0 1
vrde="off"
usb="off"
ehci="off"
xhci="off"
SharedFolderNameMachineMapping1="c/Users"
SharedFolderPathMachineMapping1="c:\Users"
VRDEActiveConnection="off"
VRDEClients=0
vcpenabled="off"
vcpscreens=0
vcpfile="C:\Users\Klas\.docker\machine\machines\default\default\default.webm"
vcpwidth=1024
vcpheight=768
vcprate=512
vcpfps=25
GuestMemoryBalloon=0
GuestOSType="Linux26_64"
GuestAdditionsRunLevel=2
GuestAdditionsVersion="5.0.4 r102546"
GuestAdditionsFacility_VirtualBox Base Driver=50,1442608650416
GuestAdditionsFacility_VirtualBox System Service=50,1442608658377
GuestAdditionsFacility_Seamless Mode=0,1442608650415
GuestAdditionsFacility_Graphics Mode=0,1442608650415

STDERR:
Using SSH client type: external
About to run SSH command:
ip addr show dev eth1
&{C:\Program Files\Git\usr\bin\ssh.exe [C:\Program Files\Git\usr\bin\ssh.exe -o PasswordAuthentication=no -o IdentitiesO
nly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o Connect
Timeout=10 -i C:\Users\Klas\.docker\machine\machines\default\id_rsa -p 50825 docker@localhost ip addr show dev eth1] []
 <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> false [] [] [] [] <nil>}
SSH cmd err, output: <nil>: 4: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default
qlen 1000
    link/ether 08:00:27:06:ba:e8 brd ff:ff:ff:ff:ff:ff
    inet 192.168.99.100/24 brd 192.168.99.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe06:bae8/64 scope link
       valid_lft forever preferred_lft forever

SSH returned: 4: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:06:ba:e8 brd ff:ff:ff:ff:ff:ff
    inet 192.168.99.100/24 brd 192.168.99.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe06:bae8/64 scope link
       valid_lft forever preferred_lft forever

END SSH

invalid certs detected; regenerating for 192.168.99.100:2376
command=configureAuth machine=default
Using SSH client type: external
About to run SSH command:
cat /etc/os-release
&{C:\Program Files\Git\usr\bin\ssh.exe [C:\Program Files\Git\usr\bin\ssh.exe -o PasswordAuthentication=no -o IdentitiesO
nly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o Connect
Timeout=10 -i C:\Users\Klas\.docker\machine\machines\default\id_rsa -p 50825 docker@localhost cat /etc/os-release] []  <
nil> <nil> <nil> [] <nil> <nil> <nil> <nil> false [] [] [] [] <nil>}
SSH cmd err, output: <nil>: NAME=Boot2Docker
VERSION=1.8.2
ID=boot2docker
ID_LIKE=tcl
VERSION_ID=1.8.2
PRETTY_NAME="Boot2Docker 1.8.2 (TCL 6.4); master : aba6192 - Thu Sep 10 20:58:17 UTC 2015"
ANSI_COLOR="1;34"
HOME_URL="http://boot2docker.io"
SUPPORT_URL="https://github.com/boot2docker/boot2docker"
BUG_REPORT_URL="https://github.com/boot2docker/boot2docker/issues"

found compatible host: boot2docker
Using SSH client type: external
About to run SSH command:
sudo /usr/bin/sethostname default && echo "default" | sudo tee /var/lib/boot2docker/etc/hostname
&{C:\Program Files\Git\usr\bin\ssh.exe [C:\Program Files\Git\usr\bin\ssh.exe -o PasswordAuthentication=no -o IdentitiesO
nly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o Connect
Timeout=10 -i C:\Users\Klas\.docker\machine\machines\default\id_rsa -p 50825 docker@localhost sudo /usr/bin/sethostname
default && echo "default" | sudo tee /var/lib/boot2docker/etc/hostname] []  <nil> <nil> <nil> [] <nil> <nil> <nil> <nil>
 false [] [] [] [] <nil>}
SSH cmd err, output: <nil>: ←[1;32mSetting hostname to ←[1;35mdefault←[0;39m ←[1;32mDone.←[0;39m
default

executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo default --machinereadable
STDOUT: name="default"
groups="/"
ostype="Linux 2.6 / 3.x / 4.x (64-bit)"
UUID="29e36969-3227-4181-a5a3-24d6506c8df1"
CfgFile="C:\\Users\\Klas\\.docker\\machine\\machines\\default\\default\\default.vbox"
SnapFldr="C:\\Users\\Klas\\.docker\\machine\\machines\\default\\default\\Snapshots"
LogFldr="C:\\Users\\Klas\\.docker\\machine\\machines\\default\\default\\Logs"
hardwareuuid="29e36969-3227-4181-a5a3-24d6506c8df1"
memory=1024
pagefusion="off"
vram=8
cpuexecutioncap=100
hpet="on"
chipset="piix3"
firmware="BIOS"
cpus=1
pae="on"
longmode="on"
cpuid-portability-level=0
bootmenu="disabled"
boot1="dvd"
boot2="dvd"
boot3="disk"
boot4="none"
acpi="on"
ioapic="on"
biossystemtimeoffset=0
rtcuseutc="on"
hwvirtex="on"
nestedpaging="on"
largepages="on"
vtxvpid="on"
vtxux="on"
paravirtprovider="default"
VMState="running"
VMStateChangeTime="2015-09-19T07:24:31.362000000"
monitorcount=1
accelerate3d="off"
accelerate2dvideo="off"
teleporterenabled="off"
teleporterport=0
teleporteraddress=""
teleporterpassword=""
tracing-enabled="off"
tracing-allow-vm-access="off"
tracing-config=""
autostart-enabled="off"
autostart-delay=0
defaultfrontend=""
storagecontrollername0="SATA"
storagecontrollertype0="IntelAhci"
storagecontrollerinstance0="0"
storagecontrollermaxportcount0="30"
storagecontrollerportcount0="30"
storagecontrollerbootable0="on"
"SATA-0-0"="C:\Users\Klas\.docker\machine\machines\default\boot2docker.iso"
"SATA-ImageUUID-0-0"="bf9d4367-a567-4a67-b91e-fa6a6af82fbd"
"SATA-tempeject"="off"
"SATA-IsEjected"="off"
"SATA-1-0"="C:\Users\Klas\.docker\machine\machines\default\disk.vmdk"
"SATA-ImageUUID-1-0"="b13894f5-f5cf-4404-9406-78b0bfaf5cb0"
"SATA-2-0"="none"
"SATA-3-0"="none"
"SATA-4-0"="none"
"SATA-5-0"="none"
"SATA-6-0"="none"
"SATA-7-0"="none"
"SATA-8-0"="none"
"SATA-9-0"="none"
"SATA-10-0"="none"
"SATA-11-0"="none"
"SATA-12-0"="none"
"SATA-13-0"="none"
"SATA-14-0"="none"
"SATA-15-0"="none"
"SATA-16-0"="none"
"SATA-17-0"="none"
"SATA-18-0"="none"
"SATA-19-0"="none"
"SATA-20-0"="none"
"SATA-21-0"="none"
"SATA-22-0"="none"
"SATA-23-0"="none"
"SATA-24-0"="none"
"SATA-25-0"="none"
"SATA-26-0"="none"
"SATA-27-0"="none"
"SATA-28-0"="none"
"SATA-29-0"="none"
natnet1="nat"
macaddress1="0800274BA2D9"
cableconnected1="on"
nic1="nat"
nictype1="82540EM"
nicspeed1="0"
mtu="0"
sockSnd="64"
sockRcv="64"
tcpWndSnd="64"
tcpWndRcv="64"
Forwarding(0)="ssh,tcp,127.0.0.1,50825,,22"
hostonlyadapter2="VirtualBox Host-Only Ethernet Adapter #2"
macaddress2="08002706BAE8"
cableconnected2="on"
nic2="hostonly"
nictype2="82540EM"
nicspeed2="0"
nic3="none"
nic4="none"
nic5="none"
nic6="none"
nic7="none"
nic8="none"
hidpointing="ps2mouse"
hidkeyboard="ps2kbd"
uart1="off"
uart2="off"
lpt1="off"
lpt2="off"
audio="none"
clipboard="disabled"
draganddrop="disabled"
SessionName="headless"
VideoMode="720,400,0"@0,0 1
vrde="off"
usb="off"
ehci="off"
xhci="off"
SharedFolderNameMachineMapping1="c/Users"
SharedFolderPathMachineMapping1="c:\Users"
VRDEActiveConnection="off"
VRDEClients=0
vcpenabled="off"
vcpscreens=0
vcpfile="C:\Users\Klas\.docker\machine\machines\default\default\default.webm"
vcpwidth=1024
vcpheight=768
vcprate=512
vcpfps=25
GuestMemoryBalloon=0
GuestOSType="Linux26_64"
GuestAdditionsRunLevel=2
GuestAdditionsVersion="5.0.4 r102546"
GuestAdditionsFacility_VirtualBox Base Driver=50,1442608650416
GuestAdditionsFacility_VirtualBox System Service=50,1442608658377
GuestAdditionsFacility_Seamless Mode=0,1442608650415
GuestAdditionsFacility_Graphics Mode=0,1442608650415

STDERR:
Using SSH client type: external
About to run SSH command:
ip addr show dev eth1
&{C:\Program Files\Git\usr\bin\ssh.exe [C:\Program Files\Git\usr\bin\ssh.exe -o PasswordAuthentication=no -o IdentitiesO
nly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o Connect
Timeout=10 -i C:\Users\Klas\.docker\machine\machines\default\id_rsa -p 50825 docker@localhost ip addr show dev eth1] []
 <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> false [] [] [] [] <nil>}
SSH cmd err, output: <nil>: 4: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default
qlen 1000
    link/ether 08:00:27:06:ba:e8 brd ff:ff:ff:ff:ff:ff
    inet 192.168.99.100/24 brd 192.168.99.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe06:bae8/64 scope link
       valid_lft forever preferred_lft forever

SSH returned: 4: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:06:ba:e8 brd ff:ff:ff:ff:ff:ff
    inet 192.168.99.100/24 brd 192.168.99.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe06:bae8/64 scope link
       valid_lft forever preferred_lft forever

END SSH

Daemon not responding yet: dial tcp 192.168.99.100:2376: ConnectEx tcp: A connection attempt failed because the connecte
d party did not properly respond after a period of time, or established connection failed because connected host has fai
led to respond.
Daemon not responding yet: dial tcp 192.168.99.100:2376: ConnectEx tcp: A connection attempt failed because the connecte
d party did not properly respond after a period of time, or established connection failed because connected host has fai
led to respond.
Daemon not responding yet: dial tcp 192.168.99.100:2376: ConnectEx tcp: A connection attempt failed because the connecte
d party did not properly respond after a period of time, or established connection failed because connected host has fai
led to respond.
Daemon not responding yet: dial tcp 192.168.99.100:2376: ConnectEx tcp: A connection attempt failed because the connecte
d party did not properly respond after a period of time, or established connection failed because connected host has fai
led to respond.
Daemon not responding yet: dial tcp 192.168.99.100:2376: ConnectEx tcp: A connection attempt failed because the connecte
d party did not properly respond after a period of time, or established connection failed because connected host has fai
led to respond.
Daemon not responding yet: dial tcp 192.168.99.100:2376: ConnectEx tcp: A connection attempt failed because the connecte
d party did not properly respond after a period of time, or established connection failed because connected host has fai
led to respond.
Daemon not responding yet: dial tcp 192.168.99.100:2376: ConnectEx tcp: A connection attempt failed because the connecte
d party did not properly respond after a period of time, or established connection failed because connected host has fai
led to respond.
</pre>

The last line keeps repeating every 22 seconds.

**Comment by cpuguy83** [comment]
Hello, this does not look like the right repo for this issue.
It's probably an issue with virtualbox itself, but github.com/docker/docker-machine would be a better place for this.
Thanks!

**Comment by Dzoukr** [comment]
Hi guys, just to let you know, I had exactly the same problem and this fix works for me:
http://stackoverflow.com/questions/32547427/docker-unreachable-after-computer-sleep/33010351#33010351

**Comment by thaJeztah** [comment]
Thanks @Dzoukr

**Comment by 2uanta** [comment]
Thanks @Dzoukr. The tip works for me.

**Comment by thaJeztah** [comment]
@2uanta if you have thoughts on how to fix this; please open an issue in the https://github.com/docker/machine issue tracker :+1:

**Comment by man-bohdan** [comment]
I'm running Docker on Win7 host in a boot2docker vm. I'm having same issue. After host sleeps and wakes up, docker commands are no longer working. 
Example: 
$ docker images
An error occurred trying to connect: Get https://192.168.99.101:2376/v1.21/images/json: dial tcp 192.168.99.101:2376: ConnectEx tcp: A connection attempt failed because t
he connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

I have found next workaround in restoring docker functionality. 
$ docker-machine ssh default 
docker@default:~$ docker run hello-world
docker@default:~$ exit

Bingo, everything works again. Notice, I was able to ssh into boot2docker, so for me it is not connectivity issue.

I hope this will help to track and solve the issue.

**Comment by sandeepkapri** [comment]
If you have installed docker toolbox then run docker quickstart terminal (it's a program and get installed during installation process).

After this open a new command prompt window and run a docker command **docker version**.
You will get no error.

Works for me.
