### ISSUE TITLE
Suggestion: Add site wide search

### ISSUE THREAD

**Issue by charleswhchan** [docker/docker#16263]
As the Docker website continues to expand, it is going to become increasing difficult to find the information required by navigation alone. 

eg. To find more information about a particular command, such as docker info, I used the following search string in Google: `docker info site:docs.docker.com`

See: https://www.python.org/

**Comment by thaJeztah** [comment]
This was actually discussed during DockerCon as well (https://github.com/docker/opensource/issues/8), where https://www.algolia.com was suggested as an alternative to Google search

**Comment by charleswhchan** [comment]
:+1: Great

**Comment by Pensu** [comment]
+! for algolia. In my experience, they give a lot wider results.

**Comment by SvenDowideit** [comment]
ah, you mean https://community.algolia.com/docsearch/ ? having a play.

**Comment by thaJeztah** [comment]
There's now a site-wide search in place; https://docs.docker.com/search/?q=foobar
