### ISSUE TITLE
BTRFS large tar operation stops at 9,8 GB 

### ISSUE THREAD

**Issue by frank-dspeed** [docker/docker#16267]
Hello i expirence complet docker daemon crashing when i run a tar job inside a container that tars more then 10gb to a host volume

do i miss something ? its not device mapper and i write to host dir

**Comment by frank-dspeed** [comment]
Thank you too you got informed its reproduce able scince all version maybe simply do some large operations in standart tests?

i could bet there is no one who can run tar cfv in a container and use as target a host dir and even read from mounted host dir if sice is over 10gb and driver is btrfs

**Comment by frank-dspeed** [comment]
steps to reproduce docker run -v /data/containing_300_directorys:/data --name data busybox
docker run --volumes-from data -v /backup:/backup  tar cvf /backup/data.tar /data

there you get your crash. of complet daemon 

docker info
Containers: 114
Images: 998
Storage Driver: btrfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.5-100.fc21.x86_64
Operating System: Fedora 22 (Twenty Two)
CPUs: 16
Total Memory: 125.9 GiB

**Comment by LK4D4** [comment]
ping @cpuguy83 
I remember you had some btrfs host

**Comment by cpuguy83** [comment]
@frank-dspeed A log of with the daemon stack dump would be super helpful.
Unless you are sending the tar details to stdout, I do not see any reason docker would crash here since Docker should not even be involved.

Is this still a problem?

Going to close this very old issue, but if you can provide more details that we can look at I will definitely take a look.

**Comment by cpuguy83** [comment]
Also, are you certain this is not the OOM killer killing off the docker daemon to make more memory for your tar job?

**Comment by frank-dspeed** [comment]
i did the following i got a btrfs container that had a host volume mounted that contained 60gb the host volume was btrfs.

the docker host it self used btrfs too 

i runned a secund container using volumes-from + a host directory as target and executed tar in it to dump the data from the first container as tar to a other directory.

**Comment by cpuguy83** [comment]
So 60gb file/dir is sitting in the host directory, and you are using a container to tar it up to another host directory?

Logs from the daemon crash will be extremely helpful, thanks.
