### ISSUE TITLE
`docker -D info` does not include debug information

### ISSUE THREAD

**Issue by charleswhchan** [docker/docker#16264]
(docker version: 1.8.1)

According to the `info` [documentation](https://docs.docker.com/reference/commandline/info/)
> The global -D option tells all docker commands to output debug information.

When I use the -D option, I get the same result as without -D:
```
$ docker -D info
Containers: 8
Images: 140
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 156
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 1.955 GiB
Name: test-VirtualBox
ID: YHUO:K2OX:K6UA:UEBP:RQYK:F2K7:SWDJ:IH67:TWO4:MQ5J:IAFJ:3XCH
WARNING: No swap limit support
```
```
$ docker info
Containers: 8
Images: 140
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 156
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 1.955 GiB
Name: test-VirtualBox
ID: YHUO:K2OX:K6UA:UEBP:RQYK:F2K7:SWDJ:IH67:TWO4:MQ5J:IAFJ:3XCH
WARNING: No swap limit support
```
Not sure if the -D option has been deprecated, and documentation simply needs to be updated?

(I also have a question about the `Images: 140`, what does this number corresponds to? It doesn't appears to match up with the output from `docker images` : 18)

**Comment by thaJeztah** [comment]
> what does this number corresponds to? It doesn't appears to match up with the output from docker images : 18)

I think it includes all intermediate images, so should match `docker images -a`

> When I use the -D option, I get the same result as without -D:

Hm, good point, I know it's still used for the daemon to output more log messages, but it could be that the client doesn't use it anymore (previously `docker info` *did* show more info when used with `-D`)

**Comment by charleswhchan** [comment]
>I think it includes all intermediate images, so should match docker images -a

I see!
----
* Old(?) Gordon bot asks for `docker -D info`
https://github.com/docker/docker/blob/634a848b8e3bdd8aed834559f3b2e0dfc7f5ae3a/contrib/report-issue.sh#L39
* New(?) Gordon bot asks for `docker info`
https://github.com/docker/leeroy/blob/a3fb0f9f89e99bc5663435265fec361c4eca9200/github/comments.go#L60

From what I can tell in info.go, it looks like the debug is only shown if the daemon is started with -D:
https://github.com/docker/docker/blob/634a848b8e3bdd8aed834559f3b2e0dfc7f5ae3a/api/client/info.go#L54

So, I tried to start the docker daemon manually with -D: `docker daemon -D`. When I issued `docker info` again, I can see the extra debug info:
```
$ docker info
Containers: 9
Images: 157
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 175
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 1.955 GiB
Name: test-VirtualBox
ID: YHUO:K2OX:K6UA:UEBP:RQYK:F2K7:SWDJ:IH67:TWO4:MQ5J:IAFJ:3XCH
Debug mode (server): true
File Descriptors: 11
Goroutines: 18
System Time: 2015-09-13T13:22:20.604492352-07:00
EventsListeners: 0
Init SHA1: f03be8ef95c082e1e68bfb533064420fcfd161eb
Init Path: /usr/lib/docker/dockerinit
Docker Root Dir: /var/lib/docker
WARNING: No swap limit support
```
So I guess the documentation could be updated with both examples. One example would show the output of `info` when daemon is started as normal, and the other example when daemon is started with `-D`. Finally, remove the description of `-D` from `info` command itself.

**Comment by charleswhchan** [comment]
#dibs

**Comment by thaJeztah** [comment]
Thanks for doing the research. Looking at some PRs that could be related here; https://github.com/docker/docker/pull/11965 which removed coupling of `-D` and the "Debug" env-var, and https://github.com/docker/docker/pull/13221 brought it back in, and this line seems to tell if the extra should be output or not; https://github.com/docker/docker/pull/11965/files#diff-9ee0ca443f464cd85f2e1339c2c204d9R47

@duglin any ideas? Should this output be dependent on the *daemon* being in debug?

**Comment by duglin** [comment]
@tiborvass as @thaJeztah mentioned, the issue is here:
https://github.com/docker/docker/blob/master/api/client/info.go#L53
we only check the daemon's debug flag, not the client's or the "common" flags:
https://github.com/docker/docker/blob/master/docker/common.go#L40

I wasn't sure if the way you want this solved is to pull in those 'common' flags into the CLI code or if there was some other way you wanted people to get access to them.  Adding a check for the "DEBUG" env var does work but I'd really prefer to not use that if we can avoid it.

**Comment by duglin** [comment]
ping @tiborvass

**Comment by duglin** [comment]
I think #19893 fixes this but keep in mind that not all commands will generate debug info - some just don't have anything to say  :-)   Once that PR is in, try "docker -D run ubuntu echo hi" and you should see some output.  "docker -D info" though is just a quiet one.

**Comment by calavera** [comment]
I can confirm that #19893 fixed this issue:

![image](https://cloud.githubusercontent.com/assets/1050/12734682/01b16392-c8f7-11e5-81bd-c33f3346b65e.png)

I'm also adding a regression test to make sure this doesn't break again: #19901

**Comment by duglin** [comment]
@calavera I'm not seeing that debug line when I do `docker -D info` from master? Anything needed?

**Comment by calavera** [comment]
@duglin the debug flag must be set on the server to see that:

**Comment by duglin** [comment]
right, that's what I figured, so to his scenario the only way we'll see more info is if he gets lucky on the particular command. e.g. docker info doesn't have any debug info, but "docker run" does.
