### ISSUE TITLE
Syntax Error REST-API Documentation Example

### ISSUE THREAD

**Issue by volker-schukai** [docker/docker#16266]
i think, the follow example on file 

* docker/docs/reference/api/docker_remote_api_v1.21.md
* docker/docs/reference/api/docker_remote_api_v1.20.md
* docker/docs/reference/api/docker_remote_api_v1.19.md
* ...
```
Ulimits: { "Name": "nofile", "Soft": 1024, "Hard", 2048 }}
```
should be
```
Ulimits: { "Name": "nofile", "Soft": 1024, "Hard": 2048 }
```

**Comment by thaJeztah** [comment]
Good catch! Absolutely, that's a typo (or copy-pasta)

Are you interested in creating a PR to fix that?

**Comment by opreaadrian** [comment]
#dibs
