### ISSUE TITLE
Containers don't have access to internet when using multi-host overlay network

### ISSUE THREAD

**Issue by gauravphoenix** [docker/docker#16272]
I'm following https://github.com/docker/libnetwork/blob/master/docs/overlay.md 
Containers on different host are able to ping each other but none of them have internet access. 

I think this issue was reported but I can't seem to find it.

**Comment by mountkin** [comment]
To access the internet you have to attach a bridge network to the container.

**Comment by gauravphoenix** [comment]
@mountkin  how do I do that? I am reading https://docs.docker.com/reference/run/#network-settings but can't find an option to attach additional network

**Comment by sanimej** [comment]
@gauravphoenix When using the overlay network if you want to access internet start the container with -p option. You can give any port number. Passing the -p option creates an endpoint on the default bridge network (docker0 bridge) and provides external connectivity. This is the current behavior in 1.8 experimental version.

We are working on providing a cleaner solution in the next release.

**Comment by mavenugo** [comment]
@gauravphoenix there is a minor hack that makes the external connectivity work in experimental channel. Containers in overlay network gets external connectivity automatically when the container is launched with `-p` or `-P` or `--expose` flags. Essentially, when either of these flags are used to expose / port-map, the daemon automatically attaches the container to the bridge network.

But, this will change in a few days through proper external connectivity support.

**Comment by gauravphoenix** [comment]
Thanks @mavenugo and @sanimej

**Comment by gauravphoenix** [comment]
@mavenugo @sanimej 

I am trying to build a docker image from a Dockerfile against a docker daemon which is using overlay networking. In the dockerfile I have a "wget" command which needs internet access. How do I workaround this issue now?

**Comment by mavenugo** [comment]
@gauravphoenix remove the daemon `--default-network` configuration. That will make bridge driver as the default driver and hence you will not hit this issue.

**Comment by gauravphoenix** [comment]
@mavenugo  thanks. That should work

**Comment by bercinho** [comment]
Hi maenugo,

I also have the problem with containers connecting to a docker-overlay network not having Internet access.

I am starting up the Containers with docker-compose, but there are also some started dynamically.

I understand "-p", "-P", "--expose" was a solution with previous versions of Docker, but what is the way to get around this now?

[root@ip-10-43-185-247 log]# docker -v
Docker version 1.11.2, build b9f10c9/1.11.2

[root@ip-10-43-185-247 log]# uname -a
Linux ip-10-43-185-247 4.4.23-31.54.amzn1.x86_64 #1 SMP Tue Oct 18 22:02:09 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

[root@ip-10-43-185-247 log]# docker info
Containers: 160
 Running: 0
 Paused: 0
 Stopped: 160
Images: 25
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker-202:1-395936-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 11 GB
 Data Space Total: 107.4 GB
 Data Space Available: 36.81 GB
 Metadata Space Used: 40.85 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.107 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 4.4.23-31.54.amzn1.x86_64
Operating System: Amazon Linux AMI 2016.09
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.8 GiB
Name: ip-10-43-185-247
ID: CC6B:EWR3:LNJT:OESW:SVBT:BN6B:DBSK:HB34:U4OA:J2BV:AX37:BY3J
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Http Proxy: http://webproxy.aws.db.de:8080/
Https Proxy: http://webproxy.aws.db.de:8080/
Registry: https://index.docker.io/v1/

Thanks & Cheers,

 Bert
