### ISSUE TITLE
Better storage driver documentation

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#16286]
We need better documentation about choosing a storage driver.  Jerome's presentation is a good place to start.

**Comment by moxiegirl** [comment]
@nigelpoulton is working on this issue

**Comment by bfirsh** [comment]
:sparkles: https://github.com/docker/docker/pull/17486 :sparkles: 

@moxiegirl This can probably be closed, right? :)

**Comment by thaJeztah** [comment]
Yup, let's close this!
