### ISSUE TITLE
Two way sync volume setting questions

### ISSUE THREAD

**Issue by daituzhang** [docker/docker#16280]
Hi,
docker version:
```Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      darwin/amd64
```
docker info:
```
Containers: 1
Images: 38
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 40
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.1 (TCL 6.3); master : 7f12e95 - Thu Aug 13 03:24:56 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: default
ID: PLRQ:7MWW:IHZM:5TEJ:JTAF:LUNW:4VFS:RQHQ:7QJV:KMTK:C5PO:SJJI
Debug mode (server): true
File Descriptors: 19
Goroutines: 67
System Time: 2015-09-14T15:14:16.392107827Z
EventsListeners: 1
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: daituzhang
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```
uname -a:
`Darwin Yulu-Zhang-MacBook-Pro.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
`
Provide additional environment details (AWS, VirtualBox, physical, etc.): VirtualBox

I was using a docker image https://github.com/gabrielmoreira/docker-craft
It installs a cms called craft under the `/var/www` in ubuntu. (Dockerfile: https://github.com/gabrielmoreira/docker-craft/blob/master/Dockerfile)
I ran the container by `run -d -p 80:80 --name craft -v /Users/yuluzhang/docker-craft:/var/www gabrielmoreira/craft`
and got error: `Error response from daemon: Cannot start container 8322bbb86896fd7ffcc7348d9f5135e53e5ce00fd319be54ef2ba2ee9392eb27: [8] System error: no such file or directory`
That is probably because that the docker folder `/var/www` that has installed craft in is switched to the local empty folder.

Is there a way that when I set the volumes up, the local folder can sync up with the docker folder?

Thank you.

**Comment by cpuguy83** [comment]
This is not possible, sorry.
