### ISSUE TITLE
Spawning 12,000 docker-proxy instances isn't sensible nor expected

### ISSUE THREAD

**Issue by wrouesnel** [docker/docker#16284]
So I was launching a container with a very large exposed port range for the host. Then my machine locked up. Rebooted and tried again. Same result, only this time I was watching top and saw docker spawning thousands of separate docker-proxy processes to do port forwarding.

Needless to say I was surprised by this result - it is definitely not expected, nor sensible behavior when the one process would be more then capable of doing port forwarding over any number of ports.

**Comment by thaJeztah** [comment]
We do have an option to disable the userland proxy (which will be the default in docker 1.9: https://github.com/docker/docker/issues/14856), by using the `--userland-proxy=false` daemon option.

IIRC, (even without the proxy) there were still some improvements to be made for large ranges of ports.

**Comment by Jaykah** [comment]
https://github.com/docker/docker/issues/11185#issuecomment-129085898

**Comment by thaJeztah** [comment]
Thanks for linking, @Jaykah that was indeed the "improvement" I was referring to

**Comment by cpuguy83** [comment]
Closing as this is a dup of existing issues.
