### ISSUE TITLE
WARNING: Your kernel does not support memory swappiness capabilities

### ISSUE THREAD

**Issue by carloscarcamo** [docker/docker#16298]
Hello,

I'm trying to run a docker image with:

 ```bash
~# docker run -t -i debian /bin/bash
```
I always get this warning

```bash
WARNING: Your kernel does not support memory swappiness capabilities, memory swappiness discarded.
root@e52597aebf3c:/#
```

Is there something wrong with my kernel? 

Thanks in advance!

Here are my docker and system info:

```bash
~# docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:28:37 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:28:37 UTC 2015
 OS/Arch:      linux/amd64
```

```bash
~# docker info
Containers: 4
Images: 7
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 15
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-0.bpo.4-amd64
Operating System: Debian GNU/Linux 7 (wheezy)
CPUs: 4
Total Memory: 5.732 GiB
Name: homeserver
ID: BBTT:P6ZB:H3NH:XJDW:LINQ:NM7P:LOWY:H4FT:NLMO:67DR:AQOA:INID
WARNING: No memory limit support
WARNING: No swap limit support
```

```bash
~# uname -a
Linux homeserver 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3~bpo70+1 (2015-08-08) x86_64 GNU/Linux
```

**Comment by coolljt0725** [comment]
@carloscarcamo  Run `check-config.sh`(https://github.com/docker/docker/blob/master/contrib/check-config.sh) on your machine, you will find what was missing with your kernel.

**Comment by runcom** [comment]
@coolljt0725 thanks
docker info is also showing your kernel doesn't support memory swap and memory limit, most likely cgroup not mounted. I'm gonna close this as there's no issue but ping me if I'm mistaken and I'll reopen

**Comment by falzm** [comment]
Is there a way to get rid of this message? Not all machines have swap space and this is really annoying... Maybe display the message in the docker-engine's logs at startup, but not at container startup?

**Comment by sigma001** [comment]
That solves it: https://github.com/docker/docker/issues/4250
