### ISSUE TITLE
Docker suddenly filling up disk with huge JSON log entries

### ISSUE THREAD

**Issue by zopyx** [docker/docker#16297]
On several occasions Docker 1.6.X started to write a massive amount
of JSON logs for one particular container causing almost disk-full situtations

insgesamt 135928172
drwx------ 2 root root         4096 Sep  9 23:43 .
drwx------ 5 root root         4096 Sep  9 23:43 ..
-rw------- 1 root root 139190348267 Sep 15 06:46 
7b56b5070f929f8d5b06bebd1121d508523970f5cbe3b91e8e6fd65b20e61d08-json.log
-rw-r--r-- 1 root root         2453 Sep  9 23:43 config.json
-rw-r--r-- 1 root root          646 Sep  9 23:43 hostconfig.json
-rw-r--r-- 1 root root           13 Sep  9 23:43 hostname
-rw-r--r-- 1 root root          174 Sep  9 23:43 hosts
-rw-r--r-- 1 root root          177 Sep  9 23:43 resolv.conf
-rw-r--r-- 1 root root           71 Sep  9 23:43 resolv.conf.hash

The disk usage was always constant and starting to write 130 GB of logs just happens suddenly.
Why is this happening? 

$ docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

This happened in the past also with Docker 1.4 and 1.5 ....systematic misfeature?

```
{"log":"Page 94121: 0/0[[attribute (1.9.3.38.3.4.3):'0 7.4697...3.129623'] ] 174/1[text (1.9.3.38.3.4.4):'Mortalit...t Frauen'] 205/2[text (1.9.3.38.4):'\n","stream":"stdout","time":"2015-09-15T04:46:27.172854597Z"}
{"log":"'] 217/3[element (1.9.3.39) children: 2 attributes: 1] 240/4[[attribute (1.9.3.39.1):'g250'] ] 256/5[element (1.9.3.39.2) children: 3 attributes: 2] 279/6[[attribute (1.9.3.39.2.1):'url(#cli...Path254)'] ] 310/7[[attribute (1.9.3.39.2.2):'g252'] ] 327/8[element (1.9.3.39.2.3) children: 3 attributes: 2] 351/9[[attribute (1.9.3.39.2.3.1):'scale(0....1.00806)'] ] 390/10[[attribute (1.9.3.39.2.3.2):'g258'] ] 408/11[element (1.9.3.39.2.3.3) children: 3 attributes: 3] 433/12[[attribute (1.9.3.39.2.3.3.1):'path260'] ] 454/13[[attribute (1.9.3.39.2.3.3.2):'fill:non...pacity:1'] ] 619/14[[attribute (1.9.3.39.2.3.3.3):'m 2.4179...2.3412 z'] ] ; records in page: 15 (header says: 15); currentTupleID: 14; data length: 705 (last non-zero byte: 705)\n","stream":"stdout","time":"2015-09-15T04:46:27.172919696Z"}
{"log":"Page 94121: 0/0[[attribute (1.9.3.38.3.4.3):'0 7.4697...3.129623'] ] 174/1[text (1.9.3.38.3.4.4):'Mortalit...t Frauen'] 205/2[text (1.9.3.38.4):'\n","stream":"stdout","time":"2015-09-15T04:46:27.173324247Z"}
{"log":"'] 217/3[element (1.9.3.39) children: 2 attributes: 1] 240/4[[attribute (1.9.3.39.1):'g250'] ] 256/5[element (1.9.3.39.2) children: 3 attributes: 2] 279/6[[attribute (1.9.3.39.2.1):'url(#cli...Path254)'] ] 310/7[[attribute (1.9.3.39.2.2):'g252'] ] 327/8[element (1.9.3.39.2.3) children: 3 attributes: 2] 351/9[[attribute (1.9.3.39.2.3.1):'scale(0....1.00806)'] ] 390/10[[attribute (1.9.3.39.2.3.2):'g258'] ] 408/11[element (1.9.3.39.2.3.3) children: 3 attributes: 3] 433/12[[attribute (1.9.3.39.2.3.3.1):'path260'] ] 454/13[[attribute (1.9.3.39.2.3.3.2):'fill:non...pacity:1'] ] 619/14[[attribute (1.9.3.39.2.3.3.3):'m 2.4179...2.3412 z'] ] ; records in page: 15 (header says: 15); currentTupleID: 14; data length: 705 (last non-zero byte: 705)\n","stream":"stdout","time":"2015-09-15T04:46:27.173437118Z"}
```

**Comment by cpuguy83** [comment]
Docker writes whatever is sent to stdout and stderr from the container.

Docker 1.7 has support for using syslog as a logging driver instead of the json log. Docker 1.8 added support for journald, gelf, and fluentd.
Docker 1.9 (October) will include support for AWS Cloud Watch logs.
It is recommend to use one of these logging drivers for production scenarios.
These can be specified both at the daemon level as well as per container overrides.

In addition, docker 1.8 added support for log rotation for the json file logger. You can specify both the max size of the file as well as the max number of files to keep.

Thanks for reporting but closing as this is solved in newer versions of Docker.
