### ISSUE TITLE
enhancement: ability to specify file v folder mount

### ISSUE THREAD

**Issue by tony-kerz** [docker/docker#16302]
i have ran into problems in the past attempting to mount a file that is accidentally not present.

docker will assume that i want to mount a folder and it will create a folder (named after the missing file) creating confusion.

for example:

```
docker run -v /path/to/file.txt:/file.txt me/my-image
```

will create a folder named `file.txt` at `/path/to` if `/path/to/file.txt` doesn't exist.

i burned a few hours on this once with a docker-ized node app that was complaining that i was trying to open a folder as a file.

i thought it might be smoother if i could signal to docker that i am going after a file v a folder, and then if i specify `:ro` have it throw an error if it doesn't exist, or if it is `:rw` (default) have it just create the file.

so something like a `-f` option to indicate mounting a file, like so:

```
docker run -f /path/to/file.txt:/file.txt me/my-image
```

**Comment by mikebrow** [comment]
Comments... 

It might be confusing to go with a new -f parameter as -v is already used to mount a single file so this would leave us with two commands that do the same thing with respect to files but with different default behavior.  

Other options:  
a) add output indicating that the path does not exist on the host and is being created...  
b) add an option to the -v parameter to change the behavior from create if does not exist to fail if does not exist.

**Comment by tony-kerz** [comment]
@mikebrow good points.

i would think being able to force a fail v output would be more fool-proof, but what ever the command-line ux pros agree is good practice is fine with me as long there is a way to indicate that you intend to mount a file.

**Comment by cpuguy83** [comment]
I would probably be ok adding something like `f` to the list of modes you can specify... e.g. `-v /foo:/bar:ro,f`, and then erroring out if `/foo` is not a file (or `/bar` in the container is not a file).
Or maybe `/foo:/bar:ro,f,!` where `!` specifies to error out if the host side doesn't exist.
It would error out if `/foo` is not a file too.. probably could use some input from someone else here.

`!` isn't the best because bash will interpret this as the last run command instead of just a simple bang.

I would definitely like to solve this as it is a common problem. Especially when people do things like mount sockets from the host, which come from `/run`, which is a tmpfs and is cleared away after reboot. Docker ends up creating a dir if those sockets aren't in place when the container starts up.

ping @calavera

**Comment by mikebrow** [comment]
Suggestions:
On the force create vs do not create issue:  [c|p] where `c` is create and is the default and `p` is for passive mode where the host directory or file is not created if it does not exist on the host. 

Then on the file vs directory issue: [e|f] where 'e' is use existing directory or file and is the defailt, and `f` is open or create as a file on the host.

**Comment by calavera** [comment]
Tbh, I'd rather deprecate the directory recreation than adding a new flag, option. It's very confusing for a lot of people.

**Comment by cpuguy83** [comment]
I would too if it wasn't going to break so many people.
Maybe we can just add to deprecation.md and remove in 1.11?
This would also close like 6 issues I've come across in the last few days.

**Comment by mikebrow** [comment]
Bed's been made no?  Adding the option for `c` create as the default would have the added behavior of not reporting the warning that the create directory is occurring.  Adding a warning when `c` is not used and the file or directory does not exist has the added behavior of informing folks what is going on and to start using `c` to make the default behavior explicit.  

If deprecate... you might want to just do a new `-mo[unt]` parameter `-m` has been used already for memory.

**Comment by calavera** [comment]
> Maybe we can just add to deprecation.md and remove in 1.11?
> This would also close like 6 issues I've come across in the last few days.

Agreed. Let's kill it.
