### ISSUE TITLE
/info JSON output of docker swarm is not machine friendly 

### ISSUE THREAD

**Issue by gauravphoenix** [docker/docker#16319]
Here is sample output given by "/info" api

`{
    "ID": "",
    "Containers": 83,
    "Driver": "",
    "DriverStatus": [
        [
            "\bRole",
            "primary"
        ],
        [
            "\bStrategy",
            "spread"
        ],
        [
            "\bFilters",
            "affinity, health, constraint, port, dependency"
        ],
        [
            "\bNodes",
            "2"
        ],
        [
            "dockerhost2",
            "10.240.148.187:2376"
        ],
        [
            " └ Containers",
            "51"
        ],
        [
            " └ Reserved CPUs",
            "0 / 2"
        ],
        [
            " └ Reserved Memory",
            "0 B / 1.851 GiB"
        ],
        [
            " └ Labels",
            "executiondriver=native-0.2, kernelversion=3.16.0-4-amd64, operatingsystem=Debian GNU/Linux 8 (jessie), storagedriver=aufs"
        ],
        [
            "dockerhost3",
            "10.240.15.206:2376"
        ],
        [
            " └ Containers",
            "32"
        ],
        [
            " └ Reserved CPUs",
            "0 / 2"
        ],
        [
            " └ Reserved Memory",
            "0 B / 1.851 GiB"
        ],
        [
            " └ Labels",
            "com.example.environment=production, executiondriver=native-0.2, kernelversion=3.16.0-4-amd64, operatingsystem=Debian GNU/Linux 8 (jessie), storagedriver=aufs"
        ]
    ],
    "ExecutionDriver": "",
    "Images": 7,
    "KernelVersion": "",
    "OperatingSystem": "",
    "NCPU": 4,
    "MemTotal": 3975392870,
    "Name": "0ac63565be62",
    "Labels": null,
    "Debug": false,
    "NFd": 0,
    "NGoroutines": 0,
    "SystemTime": "2015-09-15T19:21:59.258278674Z",
    "NEventsListener": 0,
    "InitPath": "",
    "InitSha1": "",
    "IndexServerAddress": "",
    "MemoryLimit": true,
    "SwapLimit": true,
    "IPv4Forwarding": true,
    "BridgeNfIptables": true,
    "BridgeNfIp6tables": true,
    "DockerRootDir": "",
    "HttpProxy": "",
    "HttpsProxy": "",
    "NoProxy": ""
}`

Instead of providing JSON array of docker hosts with nested information, the API provides a flat output which is cumbersome to parse. The parser needs to be aware of position of elements within JSON array which is not a good design

A much cleaner output will look like this- 

`
{
    "dockerHosts": [
        {
            "dockerhost2": {
                "Containers": 4
            },
            "dockerhost3": {
                "Containers": 32
            }
        }
    ]
}`

**Comment by abronan** [comment]
Hi @gauravphoenix, I think this issue belongs to `swarm` as docker has no knowledge on how it should output `/info` with cluster awareness ;)

Would you mind opening this issue in `swarm` instead? Thanks.

**Comment by gauravphoenix** [comment]
@abronan sure, will do
