### ISSUE TITLE
Incorrect link to cpu/memory section in run reference

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#16318]
If you look at Docker run reference page at https://docs.docker.com/reference/run/ , the "Runtime Constraints on CPU and Memory" link in the Operator exclusive options is broken and "goes nowhere": https://docs.docker.com/reference/run/#runtime-constraints-on-cpu-and-memory

**Comment by frachel** [comment]
Question from a newb (experienced developer, but new to git and docker, so the git terminology and usage is a bit confusing still coming from heavy svn). On the live website I see that this doesn't work. However after I forked, etc, and built my local documentation I don't see this issue. The anchor on the latest code is "#runtime-constraints-on-resources" which is correct, whereas the live docs on docs.docker.com have the incorrect anchor. So I assume that means someone fixed this in the code already thats on github?

**Comment by moxiegirl** [comment]
@frachel It sounds like that is is likely the case.  You can actually look at the file source on docs.docker.com to see the timestamp in the buildinfo struct.  Then compare it against the timestamp of the last line in the code.

**Comment by frachel** [comment]
Ok so following up - I see a commit on Jul 27 that fixed this issue https://github.com/docker/docker/commit/00f7ced864be4440a100dad5b0726e36a52ac4e5#diff-fbcb793c0a119849605e7f3054308a97  

It changes the text to "Runtime constraints on resources" as well as the anchor to "#runtime-constraints-on-resources"

If I go to the live doc website at https://docs.docker.com/reference/run/ it's wrong, and the buildinfo struct has a date of Aug 27. 

So again pardon my git and docker new-ness - how come if the docs have a build date of a month after the commit, they're incorrect? (also, is 'commit' the right term here.. thats svn-speak on my end)

**Comment by moxiegirl** [comment]
That's because of the way we cut RCs.  So, about a month before a release we branch an RC off the master.  Work continues on the master branch while we iterate on the release. 

 For a change that happens on master *after* the first RC-1, we have to flag that change *manually* and then do a `git cherry-pick` to get it into the RC and from there into the official release.

So, it sounds like that change was not cherry-picked into an RC and missed the release date.  We do cherry-picks after the release but `run` is a pretty actively developed command.  So, in addition to the negligible link fix, it likely also has new content for as yet unreleased features.

**Comment by moxiegirl** [comment]
I'll go ahead and close this as fixed by https://github.com/docker/docker/pull/15066

Thank you for doing the research @frachel  --- I know that doesn't seem like contributing because you didn't write code. But the work you did certainly is and saved the team time.  I very much appreciated that.
