### ISSUE TITLE
Add ZenHub to readme?

### ISSUE THREAD

**Issue by stevenbrichards** [docker/docker#16311]
Hey, I'm one of the engineers from ZenHub.io. I noticed this repo uses ZenHub task boards to organize issues. 

To help contributors know to check the task boards for current priorities, what do you think about adding the ZenHub badge to your ReadMe (or contributor guidelines)? I'm happy to create a PR. A lot of people don't know ZenHub is free for open-source users :smile: 

Thoughts?

**Comment by calavera** [comment]
Hi @stevenbrichards. Several contributors use ZenHub to track issues. That's their personal preference. In general, we prefer to leave the project as vanilla as possible regarding tooling. That way, it's more accessible to everyone.

Thanks for the offer but we rather not point people to tools that the maintainers have not consensually agreed in using.

**Comment by stevenbrichards** [comment]
Makes sense @calavera, thanks for the response :)
