### ISSUE TITLE
Why does docker use PREROUTING?

### ISSUE THREAD

**Issue by stresler** [docker/docker#16329]
By using a PREROUTING rule in iptables to send all traffic to the DOCKER chain this effectively eliminates the INPUT chain and a lot of default bahvaviour. This has negative affects for people running more than just docker on a machine. 

Would INPUT be a better place to add a rule, then allowing users to construct their own policies as long as traffic lands in the DOCKER chain eventually.

This would be less fool-proof, but could be compensated for by parsing the rules and providing adequate messaging if a user is accidentally bypassing the DOCKER chain. 

I've removed the PREROUTING rule and added it back to the INPUT chain and on a test instance and am not seeing any negative consequences.  I do want to know if what the underlying logic is here. 

There are some pretty severe limitations to the doc's recommendation: "Docker’s forward rules permit all external source IPs by default. To allow only a specific IP or network to access the containers, insert a negated rule at the top of the DOCKER filter chain. For example, to restrict external access such that only source IP 8.8.8.8 can access the containers, the following rule could be added:"

For example, what if someone wants to lock down access to one of 2 IP's?  

This also prevents adding system wide rules like restricting SSH to a list of ips.

**Comment by phemmer** [comment]
You can use `DNAT` rules from the `INPUT` chain on the nat table. `DNAT` is only valid on `PREROUTING` and `OUTPUT`.

**Comment by stresler** [comment]
Ok, I think I was misreading what was going on in those tables. Closing this for now, but might re-open if I come up with a better solution.
