### ISSUE TITLE
fedora 22 rpm contains the /etc/sysconfig/docker and it should not

### ISSUE THREAD

**Issue by looztra** [docker/docker#16323]
## docker version
```
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:20:17 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:20:17 UTC 2015
 OS/Arch:      linux/amd64
```

## docker info
```
Containers: 5
Images: 165
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.6-201.fc22.x86_64
Operating System: Fedora 22 (Twenty Two)
CPUs: 4
Total Memory: 15.62 GiB
Name: fedolooz.kalaari.net
ID: TMPI:T5I4:XRWA:UXE2:IQJK:RUWS:HTIZ:4MIR:TNUX:ZULS:G4R5:MZ6J
Username: looztra
Registry: https://index.docker.io/v1/
```

## uname -a
```
Linux fedolooz.kalaari.net 4.1.6-201.fc22.x86_64 #1 SMP Fri Sep 4 17:49:24 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

## description

Others have already reported it in the blog post [new-apt-and-yum-repos](https://blog.docker.com/2015/07/new-apt-and-yum-repos/). See [comment-246075](https://blog.docker.com/2015/07/new-apt-and-yum-repos/#comment-246075) and [comment-257043](https://blog.docker.com/2015/07/new-apt-and-yum-repos/#comment-257043).

According to [the spec file](https://github.com/docker/docker/blob/master/hack/make/.build-rpm/docker-engine.spec#L168-L174), the init.d related files (and /etc/sysconfig/docker is identified as one of them) should not be present in 'systemd' distro related rpm.

But all the init.d files are present at least on Fedora 22 and Centos 7 (I did not check other systemd distro like fc21/rhel7)

start of the output of `rpm -ql docker-engine`

```
/etc/rc.d/init.d/docker
/etc/sysconfig/docker
/etc/udev/rules.d/80-docker.rules
/usr/bin/docker
/usr/lib/systemd/system/docker.service
/usr/lib/systemd/system/docker.socket
...
```

The fact that the *init.d* files are present should not be a problem, except that the `/etc/sysconfig/docker` file is **not** tagged as `%config(noreplace)`, hence the file is overwritten after each package update...and that is a problem for people that did customize their docker systemd config using a drop-in that specifies `/etc/sysconfig/docker` as an _Environment_ file.

**Comment by jfrazelle** [comment]
it doesnt anymore, this will be fixed in the next release, you can view the rpm sepc file for proof

**Comment by jfrazelle** [comment]
https://github.com/docker/docker/blob/master/hack/make/.build-rpm/docker-engine.spec#L168-L174

**Comment by thaJeztah** [comment]
Thanks for reporting. Actually, I think this was resolved recently in this PR https://github.com/docker/docker/pull/16192

**Comment by thaJeztah** [comment]
Oh, hmf, sorry, see @jfrazelle just commented :relaxed:

**Comment by looztra** [comment]
awesome! I like issue solved even before they are reported even if it make you feel like someone coming after the storm :D

Now I understand why the specs in the git repo looked good but not the actual rpm :) (could have dug harder)

Thanks!
