### ISSUE TITLE
docker run/pull failed

### ISSUE THREAD

**Issue by dayiguizhen** [docker/docker#16334]
When I want pull docker image:   
    
    [root@localhost yzxu]# docker pull sameersbn/memcached
    latest: Pulling from sameersbn/memcached
    60e6547a5ed0: Download complete 
    60e6547a5ed0: Error downloading dependent layers 
    2bde99560607: Download complete 
    3cd6891b6c03: Download complete 
    9357f5fee449: Downloading [================================================>  ] 491.5 kB/509.2 kB
    9357f5fee449: Download complete 
    a59e0487e1dd: Download complete 
    0aca596b01f0: Download complete 
    29554da128a3: Download complete 
    669cbf9e238a: Download complete 
    669cbf9e238a: Error pulling image (latest) from sameersbn/memcached, mkdir /var/lib/docker/devicemapper/mnt/60e6547a5ed07ca5368f488c56aa6f929c37bb8c8a3df50c42eaedebc2937a95/rootfs: input/output error  input/output error ad complete 
    c22013c84729: Download complete 
    d74508fb6632: Download complete 
    91e54dfb1179: Download complete 
    Error pulling image (latest) from sameersbn/memcached, mkdir /var/lib/docker/devicemapper/mnt/60e6547a5ed07ca5368f488c56aa6f929c37bb8c8a3df50c42eaed    ebc2937a95/rootfs: input/output error
    
And when I run docker image:

    [root@localhost yzxu]# docker run ubuntu:latest /bin/echo 'Hello World'
    Error response from daemon: mkdir /var/lib/docker/devicemapper/mnt/d9c8d5f5c45110dd2a84ce5aeaca62591f10fa533f2ce0e3c86983a75e39bb71-init/rootfs: input/output error

docker version:
    
    [root@localhost yzxu]# docker version
    Client version: 1.7.1
    Client API version: 1.19
    Go version (client): go1.4.2
    Git commit (client): 786b29d/1.7.1
    OS/Arch (client): linux/amd64
    Server version: 1.7.1
    Server API version: 1.19
    Go version (server): go1.4.2
    Git commit (server): 786b29d/1.7.1
    OS/Arch (server): linux/amd64

docker info:

    Containers: 1
    Images: 4
    Storage Driver: devicemapper
     Pool Name: docker-253:0-652876-pool
     Pool Blocksize: 65.54 kB
     Backing Filesystem: extfs
     Data file: /dev/loop0
     Metadata file: /dev/loop1
     Data Space Used: 79.3 MB
     Data Space Total: 107.4 GB
     Data Space Available: 17.75 GB
     Metadata Space Used: 1.024 MB
     Metadata Space Total: 2.147 GB
     Metadata Space Available: 2.146 GB
     Udev Sync Supported: true
     Deferred Removal Enabled: false
     Data loop file: /var/lib/docker/devicemapper/devicemapper/data
     Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
     Library Version: 1.02.95-RHEL6 (2015-07-29)
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 2.6.32-573.3.1.el6.x86_64
    Operating System: <unknown>
    CPUs: 4
    Total Memory: 3.742 GiB
    Name: localhost.localdomain
    ID: U4MP:PDQL:VTF6:H3JD:QJDL:WH2I:XJM2:72WI:JYF2:KRRB:SQFD:SDGS

uname -a:
    
    Linux localhost.localdomain 2.6.32-573.3.1.el6.x86_64 #1 SMP Thu Aug 13 22:55:16 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by phemmer** [comment]
Can you provide the output of `dmesg|tail` when this issue occurs?
`input/output error` is often indicative of either filesystem corruption, or hardware failure.

**Comment by dayiguizhen** [comment]
EXT4-fs error (device dm-4): ext4_add_entry: bad entry in directory #2: rec_len is smaller than minimal - block=8865offset=0(0), inode=0, rec_len=0, name_len=0
    EXT4-fs error (device dm-4): ext4_free_blocks: Freeing blocks in system zone - Block = 524288, count = 1
    EXT4-fs (dm-4): mounted filesystem with ordered data mode. Opts: 
    EXT4-fs error (device dm-4): ext4_mb_generate_buddy: EXT4-fs: group 16: 32768 blocks in bitmap, 24544 in gd
    EXT4-fs error (device dm-4): ext4_add_entry: bad entry in directory #2: rec_len is smaller than minimal - block=8865offset=0(0), inode=0, rec_len=0, name_len=0
    EXT4-fs error (device dm-4): ext4_free_blocks: Freeing blocks in system zone - Block = 524288, count = 1
    EXT4-fs (dm-4): mounted filesystem with ordered data mode. Opts: 
    EXT4-fs error (device dm-4): ext4_mb_generate_buddy: EXT4-fs: group 16: 32768 blocks in bitmap, 24544 in gd
    EXT4-fs error (device dm-4): ext4_add_entry: bad entry in directory #2: rec_len is smaller than minimal - block=8865offset=0(0), inode=0, rec_len=0, name_len=0
    EXT4-fs error (device dm-4): ext4_free_blocks: Freeing blocks in system zone - Block = 524288, count = 1

**Comment by unclejack** [comment]
@dayiguizhen You're running CentOS 6 or RHEL 6. These distributions don't support Docker officially. Please upgrade to RHEL 7 or CentOS 7 and install all updates.

I'm going to close this because this setup isn't supported by those two distributions and we can't support it either because we can't fix issues outside of Docker (kernel issues which break containers, data corruption issues when using Docker on those platforms, kernel panics and so on). Please feel free to comment. There's no need to open another issue on this topic.
