### ISSUE TITLE
Bash completion on MacBooks problem: compopt: command not found

### ISSUE THREAD

**Issue by albers** [docker/docker#16348]
bash completion uses the `compopt` shell builtin that is not available in the rather outdated bash 3.2.57(1) that comes with current MacBooks.

There is no error when loading bash completion. You get runtime errors on secific completions that use `compopt -o nospace` to suppress the trailing whitespace that otherwise gets appended automatically. This is used for completion of map arguments, e.g. `--log-opt`.

To reproduce: completion of `docker run --log-opt` will result in

    # docker run --log-opt bash: compopt: command not found

This problem has been around since 01/2014 when `compopt` was first used in c6e43154f186c9fac8501016473b459db3130222.

#dibs

**Comment by albers** [comment]
#dibs

**Comment by albers** [comment]
see also https://github.com/docker/docker/issues/15246#issuecomment-131856817

**Comment by calavera** [comment]
Fixed in #16348.
