### ISSUE TITLE
Ubuntu 14.04 - docker installation hangs at user input

### ISSUE THREAD

**Issue by kamaltherocky** [docker/docker#16340]
Hi,

i am using the docker installation script to install docker in ubuntu 14.04. The installation gets to the point where it is stopping for a user input

Setting up docker-engine (1.8.2-0~trusty) ...

Configuration file '/etc/init/docker.conf'
 ==> Deleted (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** docker.conf (Y/I/N/O/D/Z) [default=N] ? I

Even after providing the input as I , it is stuck and not proceeding.

I have two issues,

1. This is running as a cloud init so the installation should be non interactive, so how to avoid this prompt and force it to install with new configuration

2. why it is getting stuck even after the input is provided

Note:
I think the prompt appears because of some residue files related to docker in the OS image. I even tried to delete them (as below) before starting the installation but still it ended up in the prompt

sudo rm -rf /etc/init/docker.conf
sudo rm -rf /etc/init.d/docker
sudo rm -rf /etc/default/docker
sudo rm -rf /etc/docker

**Comment by kamaltherocky** [comment]
BUG REPORT INFORMATION

Use the commands below to provide key information from your environment:

docker version: installing the docker engine (latest(
docker info: 
uname -a: root

Provide additional environment details (AWS, VirtualBox, physical, etc.):

List the steps to reproduce the issue:
1. curl -sSL https://get.docker.com/ | sh
2.
3.

Describe the results you received:

Setting up docker-engine (1.8.2-0~trusty) ...

Configuration file '/etc/init/docker.conf'
==> Deleted (by you or by a script) since installation.
==> Package distributor has shipped an updated version.
What would you like to do about it ? Your options are:
Y or I : install the package maintainer's version
N or O : keep your currently-installed version
D : show the differences between the versions
Z : start a shell to examine the situation
The default action is to keep your current version.
*** docker.conf (Y/I/N/O/D/Z) [default=N] ? I

Even after providing the input as I , it is stuck and not proceeding.


Describe the results you expected:

The installation should proceed in a non interaction way and complete without issue. Currently, i am not sure what is causing the prompt. if i know the reason, i can fix the root cause in the image.

Provide additional info you think is important:

----------END REPORT ---------

#ENEEDMOREINFO

**Comment by thaJeztah** [comment]
@kamaltherocky the https://get.docker.com script is not really intended for automated use, and only for clean installs, not updates (although it "works" in most cases). In fact, we're in the process of "phasing out" the install script in our documentation (see https://github.com/docker/docker/pull/16662).

This problem seems specific to your situation, and I don't think we can have the install script handle all cases non-interactively, without making it overly complicated.
 For that reason, I'm going to close this issue, but if you need assistance, please ask in the #docker IRC channel, forums.docker.com or the Docker Users google group.
