### ISSUE TITLE
 device-mapper: table: 253:7: thin: Couldn't open thin internal device

### ISSUE THREAD

**Issue by olea** [docker/docker#16341]
Hi:

info about my configuration:

```
# uname -a
Linux XXXXXXl 4.1.6-100.fc21.x86_64 #1 SMP Mon Aug 17 22:20:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

# docker version
Client:
 Version:      1.8.1.fc21
 API version:  1.20
 Package Version: docker-io-1.8.1-2.git32b8b25.fc21.x86_64
 Go version:   go1.4.2
 Git commit:   32b8b25/1.8.1
 Built:        
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?


# rpm -q docker-io
docker-io-1.8.1-2.git32b8b25.fc21.x86_64

# cat /etc/fedora-release 
Fedora release 21 (Twenty One)

```

After docker upgrades I can't start the service:
```
# systemctl status docker.service -l
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled)
   Active: failed (Result: exit-code) since mié 2015-09-16 16:53:58 CEST; 13min ago
     Docs: http://docs.docker.com
  Process: 4138 ExecStart=/usr/bin/docker -d $OPTIONS $DOCKER_STORAGE_OPTIONS $DOCKER_NETWORK_OPTIONS $INSECURE_REGISTRY (code=exited, status=1/FAILURE)
 Main PID: 4138 (code=exited, status=1/FAILURE)

sep 16 16:53:58 patxuko.local docker[4138]: Warning: '-d' is deprecated, it will be removed soon. See usage.
sep 16 16:53:58 patxuko.local docker[4138]: time="2015-09-16T16:53:58+02:00" level=warning msg="please use 'docker daemon' instead."
sep 16 16:53:58 patxuko.local docker[4138]: time="2015-09-16T16:53:58.234295219+02:00" level=info msg="Listening for HTTP on unix (/var/run/docker.sock)"
sep 16 16:53:58 patxuko.local docker[4138]: time="2015-09-16T16:53:58.269879366+02:00" level=fatal msg="Error starting daemon: error initializing graphdriver: Could not query and save base device UUID:Error running DeviceCreate (ActivateDevice) dm_task_run failed"
sep 16 16:53:58 patxuko.local systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
sep 16 16:53:58 patxuko.local systemd[1]: Failed to start Docker Application Container Engine.
sep 16 16:53:58 patxuko.local systemd[1]: Unit docker.service entered failed state.
sep 16 16:53:58 patxuko.local systemd[1]: docker.service failed.

```

To be honest I've fully upgraded the system to last versions because I've got this «table: 253:7: thin: Couldn't open thin internal device» after a blackout. So, maybe the thin device is corrupt but I have no idea how really check and fix it.

I prepared a more detailed error log at http://pastebin.centos.org/34436/

Please ask any info I could gather for you.

**Comment by olea** [comment]
Now the same configuration is working, and I didn't change anything.

I don't understand what is happening. Sorry for the noise.

**Comment by smoebody** [comment]
hi, im experiencing the same error, but for me its not going away magically. i upgraded to fedora 22 and now i have the entry

    --storage-driver devicemapper --storage-opt dm.fs=btfs --storage-opt dm.thinpooldev=/dev/mapper/ubuntu--vg-docker--pool

in my `/etc/sysconfig/docker-storage` which causes the same error that you've got. when i start docker without the options from that file everything works fine. 

could you have a look into your `/etc/sysconfig/docker-storage` whether you still have this options?

**Comment by olea** [comment]
> could you have a look into your /etc/sysconfig/docker-storage whether you still have this options?

Well, this is a bit embarrasing. After reading your entry I checked my (currently running) conf and realised DOCKER_STORAGE_OPTIONS is empty. The reason is I've reinstalled Fedora's docker-io package and rpm moved the old conf to /etc/sysconfig/docker-storage.rpmsave.

OTOH, I've just tracked the etckeeper logs and found the origin of my problem in sept 7 in a regular update:
```
-0:docker-io-1.6.2-3.gitc3ca5bb.fc21.x86_64
+0:docker-io-1.8.1-2.git32b8b25.fc21.x86_64
-0:docker-storage-setup-0.0.3-1.fc21.noarch
```
doing this:

```
-DOCKER_STORAGE_OPTIONS=
+DOCKER_STORAGE_OPTIONS=--storage-driver devicemapper --storage-opt dm.fs=xfs --storage-opt dm.thinpooldev=/dev/mapper/vg_patxuko-docker--pool
```

So, as I'm a docker newbie, I've been messing around as a headless chicken thinking I was having a corrupted thin device block due to this 8-/

Hope it helps.

**Comment by pgampe** [comment]
Some background:
I have upgrade to Fedora 24 (from 23) and then docker stopped working with the above error.

It seems some options changed and it is impossible or hard to migrate to the new storage format. I was able to recover with the following step. I hope it helps someone else stumbling upon the same error.

```
# docker-storage-setup --reset
```

```
# docker-storage-setup
ERROR: Docker has been previously configured for use with devicemapper graph driver. Not creating a new thin pool as existing docker metadata will fail to work with it. Manual cleanup is required before this will succeed.
INFO: Docker state can be reset by stopping docker and by removing /var/lib/docker directory. This will destroy existing docker images and containers and all the docker metadata.
```

```
# rm -rf /var/lib/docker/
```

```
# systemctl status docker.service
```

**Comment by olea** [comment]
>  I was able to recover with the following step. 

@pgampe so, could you finally recover your previous containers?

**Comment by pgampe** [comment]
@olea No. I deleted everything, because this was just my dev machine and not a server.

You might want to try to copy the `/var/lib/docker/` somewhere and see if you can save at least some bits.
