### ISSUE TITLE
How to modify the time is not synchronized to the host

### ISSUE THREAD

**Issue by R1hug0** [docker/docker#16369]
I have a problem in the process of using the container.
I found that I modified the existing container time it will synchronize to the host, I have what way to ensure that the time to modify the container and not synchronized to the host，what way  can do it

like this :  in container i change time 
docker_container# date -s 11:11:00
Thu Sep 17 11:11:00 CST 2015
docker_container# exit
logout
host#date
Thu Sep 17 11:11:42 CST 2015
I just want to change the container time and do not want to host the time also changed, but now to change the time of  container and the host time also changed

env(physical):
1.Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d/1.7.1
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d/1.7.1
OS/Arch (server): linux/amd64
2.Containers: 1
Images: 27
Storage Driver: devicemapper
 Pool Name: docker-253:0-393252-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.364 GB
 Data Space Total: 107.4 GB
 Data Space Available: 47.02 GB
 Metadata Space Used: 2.118 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /docker/devicemapper/devicemapper/data
 Metadata loop file: /docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: lxc-1.0.7
Logging Driver: json-file
Kernel Version: 2.6.32-504.el6.x86_64
Operating System: <unknown>
CPUs: 1
Total Memory: 1.826 GiB
Name: centos160
ID: NTFU:C6SI:LJT6:V7KT:Q7VZ:GR3G:FNM4:42FQ:66FS:RMME:VOYG:25IN
3.Linux centos160 2.6.32-504.el6.x86_64 #1 SMP Wed Oct 15 04:27:16 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by phemmer** [comment]
You cannot. The time is tracked by the kernel, and the container shares the kernel with the host.

Also, for help using docker, you should use either the [mailing list](https://groups.google.com/forum/#!forum/docker-user), the [forums](https://forums.docker.com/), or IRC (irc.freenode.net #docker).
The bug tracker is for bugs and feature requests.

**Comment by cpuguy83** [comment]
Yep, @phemmer is bang on again! Can't change the container's time w/o affecting the host.

**Comment by R1hug0** [comment]
And if so ,is this question changed in the future?   can we have other ways that change  the container's time no affecting the host ,

**Comment by nmiroshnichenko** [comment]
as a workaround - use faketime tool (http://manpages.ubuntu.com/manpages/trusty/man1/faketime.1.html)
