### ISSUE TITLE
Proposal to allow manipulation of restart policy on existing containers

### ISSUE THREAD

**Issue by hookenz** [docker/docker#16362]
Sorry if this is already proposed but I can't find that proposal.

It should be possible to manipulate the restart policy on an existing container just like it is possible to manipulate policy on starting services on your machine.  There are lots of use cases.

In fact, there is an argument to be able to manipulate various other things too, like bind-mounts or other things.  Is this going to be added soon?

**Comment by cpuguy83** [comment]
This is a dup of several other issues.
See #15078 which will at least allow manipulating resource controls but is a gateway to other things.
