### ISSUE TITLE
Docker Error message

### ISSUE THREAD

**Issue by sanjaykumarjha** [docker/docker#16365]
i am trying to login on remote docker resgitry..in this case password is incorrect..
[root@admin ~]# docker login -e testid@gmail.com -u test -p xyzz

result
Error response from daemon: Wrong login/password, please try again

but again if i run same command with incorrect password
why docker shows below line of error message..why error message get changed by this line

Error response from daemon: Get https://index.docker.io/v1/users/: dial tcp: lookup index.docker.io: Temporary failure in name resolution

is there any way to get last line or error message..?

**Comment by cpuguy83** [comment]
Based on the error I would say there is an issue with your DNS.
For support related questions, please see #docker on IRC, the docker-user mailing list, or forums.docker.com

Thanks!
