### ISSUE TITLE
Add the AFTERBUILD capability

### ISSUE THREAD

**Issue by geisbruch** [docker/docker#16373]
Hi Guys,
  I am making images that needs some information from the user at build time to make their stuff, for example we want to provide an NVM image that abstract the user of how their version is installed

For example want our users to have the next kind of images
```
FROM magic_nvm
ENV NODE_VERSION=4.0.0
```

So when the image is build we can read that version and make something or install a default

The idea is to have a **magic_nvm** image like the next

```
 FROM ubuntu
 RUN install_nvm
 ENV NODE_VERSION=2.0.0
 AFTERBUILD update_nvm_version
```

I imagine this feature like the ONBUILD but instead of add the lines to begining of the next Dockerfile add to the end.

That feature make sense for you?

**Comment by cpuguy83** [comment]
:-1: for magic
With #15182, the user can pass this in at build time.

**Comment by geisbruch** [comment]
Hi cpuguy83, I think that the uses of ARG and AFTERBUILD are differents. If I understood with arg you can send parameters on build time. My idea with afterbuild it's a similar behavior than on build (a trigger or command used when the image is used as base of a next one) with the difference that BUILD will run at the begining and AFTERBUILD run at the end. I see ONBUILD as a before hook and AFTERBUILD as an after hook for the next image that use the first one as base image

**Comment by duglin** [comment]
@geisbruch if I'm understanding this correctly, you want the build of a 'base image' to cause the build of another image to happen, because that other Dockerfile has a "FROM baseImage". Do I have that right?

If so, I would prefer if this were done outside of "docker build" because its kind of odd to have a base image know about everyone that depends on it. Its like the reverse of the Makefile dependency stuff. This means each time someone new references the baseImage, baseImage would need to change. Doesn't sound scalable.

**Comment by geisbruch** [comment]
Hi @duglin , I don't think that the base image should change, The only thing that I am proposing it's add an operation similar to ONBUILD but with the difference that instead of run on the begining runs at the end.

For example, we have today an Image that comes with GVM, and we provide in the image a base command to update the grails version. So our uses use the image in the next way:
```
FROM my_repo/grails:latest
#Configure image to use grails 2.3.8
ENV GRAILS_VERSION=2.2.5
RUN /commands/update_grails_version.sh
```

That we want to avoid with AFTERBUILD it's the necesity of the line **RUN /commands/update_grails_version.sh**

So if we can add on our my_repo/grails:latest image a line like **AFTERBUILD RUN /commands/update_grails_version.sh** we can avoid the necesity of our users to add that RUN line and this ends in a much understable image. 

So the end image will be:
```
FROM my_repo/grails:latest
#HERE RUNS OBBUILD COMMANDS
ENV GRAILS_VERSION=2.2.5
#HERE IS WHERE I WANT AFTERBUILD COMMANDS TO BE RUN
```

Thanks,
Gabriel.

**Comment by yoanisgil** [comment]
@cpuguy83 even if #15182 looks pretty cool I think there is still some room for logic in what @geisbruch is asking for. I think the rationale behind ONBUILD could be extended furthermore and one could think of use cases where the image owner might want to execute commands after the child image has been built (clean up tasks, setup of environment variables, etc). If you look at it like that, there's no much difference between and ONBUILD instruction and an AFTERBUILD one. It all comes down to the moment instructions declared on the parent are triggered under the context of a child image build.

**Comment by LK4D4** [comment]
This issue was inactive for quite some time, so I think we can close it because most of usecases is supported with buildtime args and adding new commands to dockerfile is extremely hard in terms of support and technical debt.
