### ISSUE TITLE
Docker - Service accessible from external IP only

### ISSUE THREAD

**Issue by JoyceBabu** [docker/docker#16387]
I am having a strange issue with a statsd instance running in a docker container. I can connect to the server from outside the host machine (using its public/external IP address). But I am unable to access it from the host machine using the local ip address or the ip address of the container.

The port is mapped to the host using docker-composer

    ports:
        - "8125:8125/udp"
        - "8126:8126"

The following works, when executed from outside the host

    echo stats | nc host.domain.com 8126
    echo stats | nc <host.public.ip.address> 8126

The the following command works, when executed within the container

    echo stats | nc 127.0.0.1 8126

But the following commands does not work when run on the host

    echo stats | nc 127.0.0.1 8126
    echo stats | nc 10.1.1.8 8126

Where 10.1.1.8 is the statsd container's ip address.

I believe it is an iptables configuration issue, and have already tried with the firewall (CSF) disabled. What should I do to access the container service from within the host?

**Comment by JoyceBabu** [comment]
**docker version:**
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:21:21 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:21:21 UTC 2015
 OS/Arch:      linux/amd64

**docker info**
Containers: 11
Images: 300
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 322
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-28-generic
Operating System: Ubuntu 15.04
CPUs: 8
Total Memory: 31.32 GiB
Name: pluto.ennexa.com
ID: PPZI:24UI:S5HU:6ZD7:BIW4:P7C2:BUHE:D3G5:QZNJ:K6LY:HWMN:2U7W
WARNING: No swap limit support

**uname -a**
Linux pluto.ennexa.com 3.19.0-28-generic #30-Ubuntu SMP Mon Aug 31 15:52:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment - Physical

**Comment by cpuguy83** [comment]
What about `echo stats | nc 10.1.1.8 8126` in the container?

**Comment by JoyceBabu** [comment]
`echo stats | nc 10.1.1.8 8126` works from all linked and non-linked containers, including the StatsD container.

I can ping `10.1.1.8` from the host, but the above command does not work from the host. But I can access the stats using the external ip address of the host, from the host machine.

**Comment by JoyceBabu** [comment]
I have found out the cause of the issue. CSF had a DROP rule for all packets except for those from whitelisted IP addresses. The IP address of the host server and the other servers I used to test where already whitelisted in CSF. I have added docker IP address range to the CSF allow list, and now it is working correctly.

**Comment by cpuguy83** [comment]
Awesome.
I'm going to close since it seems like you resolved the issue.

LMK if you have any problems here.
Also, feel free to hop on #docker on IRC to troubleshoot.
Thanks!
