### ISSUE TITLE
Incorrect stream value in log statements from json-file logging driver

### ISSUE THREAD

**Issue by yoanisgil** [docker/docker#16386]
A couple of days ago I wrote an article on Docker and the json-file and syslog driver (see [here](https://medium.com/@yoanis_gil/logging-with-docker-part-1-b23ef1443aac)) and some of the readers brought to my attention an issue which I find slightly disturbing. The demo is quite simple indeed (source https://github.com/yoanisgil/docker-logging-tutorial/blob/master/part-01/logging-01.py):

```python
import sys
import time
while True:
    sys.stderr.write('Error\n')
    sys.stdout.write('All Good\n')
    time.sleep(1)
``` 

and then run:

```
docker run --name logging-01 -t -d -v $(pwd):/tmp  -w /tmp python:2.7 python logging-01.py
```

which outputs :

```
Error
All Good
....
```
however when I check the json file where log messages are kept, I see this:

```
{"log":"Error\r\n","stream":"stdout","time":"2015-09-18T01:44:29.361979588Z"}
{"log":"All Good\r\n","stream":"stdout","time":"2015-09-18T01:44:29.36244363Z"}
```

and what I find disturbing and, so those the reader, is that for the "Error" entry the `stream` field is set to  `stdout`. Shouldn't that be `stderr`. Is this an expected behaviour? Notice that the "Error" string is written with:

```
sys.stderr.write('Error\n')
```

Maybe I a missing something obvious here but if I am I'd love to know what am I doing wrong.

**Comment by yoanisgil** [comment]
docker version:
```
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64
```

docker info:
```
Containers: 12
Images: 210
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 234
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.1 (TCL 6.3); master : 7f12e95 - Thu Aug 13 03:24:56 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: ERDB:OBAQ:C3XQ:UIZU:PT2L:N6IY:7RGS:LFNL:2RS5:2Q2B:VAIR:ZAHO
Debug mode (server): true
File Descriptors: 61
Goroutines: 113
System Time: 2015-09-18T02:18:35.686653807Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: yoanisgil
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

uname -a:
```
Darwin arya.local 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64
```

**Comment by phemmer** [comment]
This is actually expected behavior, though the documentation on the behavior is a bit obscure.
The reason is because of the `-t` argument. If you leave off the `-t`, you'll see the behavior you expect.
The remote API documentation explains this behavior: https://docs.docker.com/reference/api/docker_remote_api_v1.20/#attach-to-a-container

> When using the TTY setting is enabled in `POST /containers/create` , the stream is the raw data from the process PTY and client’s `stdin`. When the TTY is disabled, then the stream is multiplexed to separate `stdout` and `stderr`.

So what's happening is that docker is allocating a TTY, and docker reading the output of that TTY to generate the log. And when reading the output of a TTY, you can't tell whether what went into it went in on STDOUT or STDERR.

**Comment by yoanisgil** [comment]
@phemmer thanks for the quick reply. Indeed I did try leaving off the `-t` option but things got even more weird at that moment. So if I run the container like this:

```
docker run --name logging-01  -d -v $(pwd):/tmp  -w /tmp python:2.7 python logging-01.py
```

then all I see from `docker logs -f logging-01` is:

```
Error
Error
Error
```

which is fine I think given that there is not TTY. Whoever there is no stdout stream in the log file:

```
{"log":"Error\n","stream":"stderr","time":"2015-09-18T02:55:28.901390774Z"}
{"log":"Error\n","stream":"stderr","time":"2015-09-18T02:55:29.903324466Z"}
```

which is again consistent with the output from the `docker logs` command above. Seems to me like it's not possible to have both streams on the json log file. Or is it? 

I just want to make sure I got things right so I do not spread around the wrong concepts ;). But yes you're right, docs are a bit confusing and does not provide this level of detail, which is what I was trying to achieve with my post.

**Comment by yoanisgil** [comment]
I am looking at this:

https://github.com/docker/docker/blob/master/daemon/logger/jsonfilelog/jsonfilelog.go#L100

and it seems like the source of the stream it's actually send by the caller of the function, which totally makes sense. However I am having a hard time figuring out who calls (and how) that function.

**Comment by phemmer** [comment]
Your app is likely buffering STDOUT. While I'm not very familiar with python, this is a common default on most scripting languages.
See http://stackoverflow.com/questions/107705/disable-output-buffering

Here is a basic test using only shell:

```
# cid="$(docker run -d fedora:22 bash -c 'printf "stderr\n" >&2; printf "stdout\n"')"

# docker wait $cid
0

# cat /var/lib/docker/containers/$cid/$cid-json.log
{"log":"stdout\n","stream":"stdout","time":"2015-09-18T04:13:56.805773269Z"}
{"log":"stderr\n","stream":"stderr","time":"2015-09-18T04:13:56.806001524Z"}

```

**Comment by yoanisgil** [comment]
Yep that was it:

```
docker run  --name logging-01  -d -v $(pwd):/tmp  -w /tmp python:2.7 python -u logging-01.py
````

that `-u` does the trick. Now everything makes sense:

```
{"log":"Error\n","stream":"stderr","time":"2015-09-18T04:27:28.135894927Z"}
{"log":"All Good\n","stream":"stdout","time":"2015-09-18T04:27:28.136186603Z"}
```

and I will make sure to update my post. 

Though, when it comes to the syslog driver, is there actually a way to make a difference between what gets logged to stdout and stderr? As per my testings and findings there is no way of telling by looking at syslog messages which messages came from the container's `stderr` and which ones from `stdout`. Just a question, I will continue investigating ;).

**Comment by cpuguy83** [comment]
For syslog, the severity for the message is set to `LOG_ERR` when it is from stderr, otherwise it's `LOG_INFO`

https://github.com/docker/docker/blob/master/daemon/logger/syslog/syslog.go#L95-L100
https://golang.org/pkg/log/syslog/#Writer.Err

**Comment by yoanisgil** [comment]
Thanks!! Very useful that last bit of information.
