### ISSUE TITLE
Proposal: Support custom headers between docker client and the remote api

### ISSUE THREAD

**Issue by foliea** [docker/docker#16388]
As developing a docker proxy for the remote api, I notice that there is no way to customize how the docker client
is communicating with the docker API.

* A docker proxy implementation doesn't have to stick with tls authentication, it could have its own authentications system (oauth token, jwt token, service key) and have its own way to manage users and their access.

e.g: For `shipyard`, in order to hit the docker api of the swarm cluster proxified, we need to include
either one of the following headers:

Auth Method	| Header	| Example
------------|---------|---------- 
Service Key	| X-Service-Key  |	X-Service-Key:12345
Auth Token  | X-Access-Token |	X-Access-Token:admin:$2$34...xxx

* A docker proxy could also be able to talk to multiple docker clusters and target a cluster
specified by the user in the request header (e.g `X-Cluster-Target:myawesome-cluster`).

It would be really convenient to be able configure the docker client to  add some headers to each request sent to the remote API.

In fact, it would be great to think about something more generic, that other tools using the remote API
like docker-compose or any API client would use as a de facto standard (like the environment variables `DOCKER_HOST`, `DOCKER_CERT_PATH`, etc).

e.g: `DOCKER_HEADERS='Authorization:JWT $2$34...xxx ; X-Cluster-Target:node1'`

I found another issue with some similarities (around authentication only) (#8283).

@ehazlett @ahmetalpbalkan

**Comment by duglin** [comment]
@foliea see https://docs.docker.com/reference/commandline/cli/ and search for "HttpHeaders" within the config file section - it should give you exactly what you're looking for.

**Comment by ehazlett** [comment]
@duglin :+1:

**Comment by fxdgear** [comment]
@duglin that url now 404's. Is there an updated link?

**Comment by thaJeztah** [comment]
@fxdgear (:wave:) new URL is https://docs.docker.com/engine/reference/commandline/cli/#configuration-files, but perhaps you can open an issue in the https://github.com/docker/docker.github.io issue tracker, because apparently a redirect is missing for the old url
