### ISSUE TITLE
Docs leave password exposed in bash history

### ISSUE THREAD

**Issue by morninj** [docker/docker#16384]
The docs (https://docs.docker.com/mac/step_six/) encourage users to enter their Docker Hub passwords in shell commands. This is bad because it exposes the password in clear text in the user's bash history. It would be better to have the user enter his or her password interactively.

**Comment by phemmer** [comment]
Security implication is slightly worse than that too. While a `.bash_history` file should be readable only by the user, command line arguments are visible to anyone on the box while the command is running (a simple `ps` will show them).

**Comment by thaJeztah** [comment]
Agreed.

@morninj that page of the docs is actually in another repo, here: https://github.com/docker/tutorials/blob/master/docs/mac/step_six.md

Would you be interested in creating a PR to improve it?
Perhaps it would be good to remove the option altogether, but that's another discussion I think.

/cc @ewindisch @NathanMcCauley @diogomonica

**Comment by morninj** [comment]
Sure—done: https://github.com/docker/tutorials/pull/27

**Comment by thaJeztah** [comment]
Awesome! Thanks :+1:

**Comment by moypray** [comment]
@thaJeztah  Why not remove "--password" option from login CLI, it is security risk.

**Comment by thaJeztah** [comment]
@moypray see my earlier comment: https://github.com/docker/docker/issues/16384#issuecomment-141256692 :

> Perhaps it would be good to remove the option altogether, but that's another discussion I think.

Making such changes is something to do very carefully though, given that it can break a lot of setups.

**Comment by vikstrous** [comment]
This should probably be closed since it seems to be fixed.

**Comment by thaJeztah** [comment]
@vikstrous thanks! Yes, this was fixed in https://github.com/docker/tutorials/pull/58 (repository is private now)
