### ISSUE TITLE
`docker logs --since` incorrectly parses timestamps generated by `docker logs -t`

### ISSUE THREAD

**Issue by mdub** [docker/docker#16395]
`docker logs -t` emits RFC3339 timestamps with a "Z" timezone suffix, which denotes UTC.

```
$ docker logs -t 196a93700f9c
2015-09-18T11:30:13.368899817Z 1
2015-09-18T11:30:13.871609615Z 2
2015-09-18T11:30:14.376469980Z 3
2015-09-18T11:30:14.878498664Z 4
2015-09-18T11:30:15.383748382Z 5
```

But, `docker logs --since TIMESTAMP` seems to ignore the "Z" suffix.

```
$ docker logs -t --since 2015-09-18T11:30:15.383748382Z 196a93700f9c
2015-09-18T11:30:13.368899817Z 1
2015-09-18T11:30:13.871609615Z 2
2015-09-18T11:30:14.376469980Z 3
2015-09-18T11:30:14.878498664Z 4
2015-09-18T11:30:15.383748382Z 5
```

even though it does recognise the equivalent "+00:00":

```
$ docker logs -t --since 2015-09-18T11:30:15.383748382+00:00 196a93700f9c
2015-09-18T11:30:15.383748382Z 5
```

We can also see that even with the explicit "Z" suffix, timestamp parsing is affected by local timezone:

```
$ docker logs -t --since 2015-09-18T11:30:15.383748382Z 196a93700f9c
2015-09-18T11:30:13.368899817Z 1
2015-09-18T11:30:13.871609615Z 2
2015-09-18T11:30:14.376469980Z 3
2015-09-18T11:30:14.878498664Z 4
2015-09-18T11:30:15.383748382Z 5

$ TZ=GMT docker logs -t --since 2015-09-18T11:30:15.383748382Z 196a93700f9c
2015-09-18T11:30:15.383748382Z 5
```

**Comment by mdub** [comment]
I'm running docker on a VirtualBox VM, created using `docker-machine`, on OS X 10.0.5.

```
$ docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.5.1
 Git commit:   0a8c2e3
 Built:        Fri Sep 11 01:46:35 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      linux/amd64

$ docker info
Containers: 65
Images: 294
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 424
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.2 (TCL 6.4); master : aba6192 - Thu Sep 10 20:58:17 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: dev
ID: XSZW:IWAY:JH4Y:CQI5:IBIM:UX2D:FT2G:BG5O:NY4P:QYQ6:B2Q2:D52G
Debug mode (server): true
File Descriptors: 17
Goroutines: 34
System Time: 2015-09-18T11:46:06.281911837Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: woollyams
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox

$ uname -a
Darwin dukeofyork-2.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
```

**Comment by mikebrow** [comment]
#investigating

**Comment by cpuguy83** [comment]
I looked at this haven't really tested yet. But the client looks to be converting to time.Unix(), and of course this is what api is expecting (and also using time.Unix()).

**Comment by cpuguy83** [comment]
And posted that on the wrong one

**Comment by mikebrow** [comment]
Also have not tested but it looks like we may have an issue of truncating the format to the length of the parameter used.   @mdub you might want to try.. 
    $ docker logs -t --since 2015-09-18T11:30:15.383748382Z00:00 196a93700f9c



pkg/timeutils/utils.go

       func GetTimestamp(value string, reference time.Time) string {
	if d, err := time.ParseDuration(value); value != "0" && err == nil {
		return strconv.FormatInt(reference.Add(-d).Unix(), 10)
	}

	var format string
	if strings.Contains(value, ".") {
		format = time.RFC3339Nano
	} else {
		format = time.RFC3339
	}

	loc := time.FixedZone(time.Now().Zone())
	if len(value) < len(format) {  **** appears to be converting the format to a subset …  don’t know why this code is here, this might be the time zone issue?
		format = format[:len(value)]  
	}
	t, err := time.ParseInLocation(format, value, loc)
	if err != nil {
		return value
	}
	return strconv.FormatInt(t.Unix(), 10)  **** appears to be striping the nanoseconds here and    outputting only seconds should be nano or add an additional parameter for the nanoseconds
       }

**Comment by mdub** [comment]
Thanks for looking into it, @mikebrow.

The "Z00:00" suffix doesn't work:

```
$ docker logs -t --since 2015-09-18T11:30:15.383748382Z00:00 196a93700f9c
Error response from daemon: strconv.ParseInt: parsing "2015-09-18T11:30:15.383748382Z00:00": invalid syntax
```

According to RFC 3339, "Z" should be sufficient to denote UTC.

* https://tools.ietf.org/html/rfc3339#section-2

**Comment by mdub** [comment]
Related: the tests for `timeutils.GetTimestamp` appear to be broken in my timezone:

```
$ TZ=Australia/Melbourne go test github.com/docker/docker/pkg/timeutils
--- FAIL: TestGetTimestamp (0.00s)
	utils_test.go:41: wrong value for '0'. expected:'-62167305600' got:'-62167341600'
FAIL
FAIL	github.com/docker/docker/pkg/timeutils	0.011s

$ TZ=UTC go test github.com/docker/docker/pkg/timeutils
ok  	github.com/docker/docker/pkg/timeutils	0.011s
```

**Comment by mikebrow** [comment]
#dibs
