### ISSUE TITLE
Docker 1.7.1: Panic due to invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by sybrandy** [docker/docker#16398]
This is similar to other issues, except our stack trace is a bit different.  Unfortunately, I can't paste all of the information that is asked for, but I'll provide as much as I can.

Docker Version:
* Client version: 1.7.1
* Client API version: 1.19
* Go version (client): go1.4.2
* Git commit (client): 786b29d
* OS/Arch (client): linux/amd64
* Server version: 1.7.1
* Server API version: 1.19
* Go version (server): go1.4.2
* Git commit (server): 786b29d
* OS/Arch (client): linux/amd64

Docker Info:
* Storage Driver: devicemapper
  * Library Version: 1.02.93-RHEL7 (2015-01-28)
* Execution Driver: native-0.2
* Logging Driver: json-file
* Kernel Version: 3.10.0-123.el7.x86_64
* Operating System: CentOS Linux 7 (Core)

Describe the results you received:

The process panicked when we restarted marathon job using Docker containers.  This job has 600 containers running.  This panic caused unrelated containers to stop running, thus putting our cluster into an unstable state.

Describe the results you expected:

All of the containers to continue to work as advertised during the restart.

Provide additional info you think is important:

The docker registry (2.0) is in a container as well.  

Stack trace (partial)

    goroutine ... [running]:
    runtime.gopanic(...)
        /usr/local/go/src/runtime/panic.go:425
    runtime.panicmem
        /usr/local/go/src/runtime/panic.go:42
    runtime.sigpanic
        /usr/local/go/runtime/sigpanic_unix.go:26
    bufio.(*Writer).flush
        /usr/local/go/src/bufio/bufio.go:530
    bufio.(*Writer).Flush
        /usr/local/go/src/bufio/bufio.go:519
    net/http.(*response).Flush
        /usr/local/go/src/net/http/server.go:1047
    github.com/docker/docker/pkg/ioutils.(*WriteFluser).Write
        /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/pkg/ioutils/writefluser.go:21
    github.com/docker/docker/pkg/progressreader.(*Config).Read
        /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/pkg/progressreader/progressreader.go:37
    io.Copy
        /usr/local/go/src/io/io.go:362
    github.com/docker/docker/graph.func
        /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/graph/pull:602
    github.com/docker/docker/graph.func
        /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/graph/pull:602
    runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232
    created by github.com/docker/docker/graph.(*TagStore).pullV2Tag
        /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/graph/pull:602

**Comment by LK4D4** [comment]
was fixed
