### ISSUE TITLE
Failed to implement HA by installing Keepalived in a container

### ISSUE THREAD

**Issue by dieuroi** [docker/docker#16390]
I installed Keepalived in virtual machine and successfully got a VIP. Then I try to implement this in a Docker container but failed to get a VIP.
I thought the reason why I didn't got the VIP is a Docker container can't control its network configuration freely but something weird occurred.
After using *service keepalived start* I got different results below with command *ps -ef|grep keepalived*
```
In virtual machine:
root 99687 1 ... /usr/sbin/keepalived -D
In Docker container:
root 8921  1 ... /usr/sbin/keepalived -d
```
In Keepalived, para D stands for detailed log but para d stands for dumping config data. I found that I got two totally different results with same installation and configuration. Besides, even I use **/usr/sbin/keepalived -D** in the Docker container to start Keepalived I still get no log in **/var/log/messages** which can show log of Keepalived on virtual machine.

I wonder whether Keepalived in Docker can work well. If the answer is yes, please tell me your solutions.

Thank you!

**Comment by phemmer** [comment]
> Besides, even I use /usr/sbin/keepalived -D in the Docker container to start Keepalived I still get no log in /var/log/messages

Logging to `/var/log/messages` is generally controlled by a syslog daemon. For messages to appear in `/var/log/messages` on the host, you need to allow the container some way of connecting to the syslog daemon, such as `-v /dev/log:/dev/log` (though this is not without issues). For messages to appear in `/var/log/messages` inside the container, you need to start a syslog daemon inside the container.

**Comment by cpuguy83** [comment]
@dieuroi Thanks for reporting, however this is not quite the right forum for support related questions.
Please use the docker-user mailing list, #docker on IRC, or forums.docker.com

Thanks!
