### ISSUE TITLE
"docker logs --since" ignores sub-second component of timestamp

### ISSUE THREAD

**Issue by mdub** [docker/docker#16396]
I expected the `--since` option to `docker logs` to consider the entire timestamp, but it appears to ignore the sub-second component.

```
$ docker logs -t --since 2015-09-18T11:30:15.999999999+00:00 196a93700f9c
2015-09-18T11:30:15.383748382Z 5

$ docker logs -t --since 2015-09-18T11:30:16+00:00 196a93700f9c
```

With

```
$ docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.5.1
 Git commit:   0a8c2e3
 Built:        Fri Sep 11 01:46:35 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by mdub** [comment]
I'm running docker on a VirtualBox VM, created using `docker-machine`, on OS X 10.0.5.

```
$ docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.5.1
 Git commit:   0a8c2e3
 Built:        Fri Sep 11 01:46:35 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      linux/amd64

$ docker info
Containers: 65
Images: 294
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 424
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.2 (TCL 6.4); master : aba6192 - Thu Sep 10 20:58:17 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: dev
ID: XSZW:IWAY:JH4Y:CQI5:IBIM:UX2D:FT2G:BG5O:NY4P:QYQ6:B2Q2:D52G
Debug mode (server): true
File Descriptors: 17
Goroutines: 34
System Time: 2015-09-18T11:46:06.281911837Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: woollyams
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox

$ uname -a
Darwin dukeofyork-2.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
```

**Comment by mikebrow** [comment]
#investigating

**Comment by cpuguy83** [comment]
I looked at this but haven't really tested yet. But the client looks to be converting to time.Unix(), and of course this is what api is expecting (and also using time.Unix()).

**Comment by mikebrow** [comment]
ayup... the client only sends seconds... does not send nanoseconds.  Same on server side... only parses seconds... does not allow for nanoseconds.

**Comment by mikebrow** [comment]
api/server/container.go
var since time.Time
	if r.Form.Get("since") != "" {
		s, err := strconv.ParseInt(r.Form.Get("since"), 10, 64)
		if err != nil {
			return err
		}
		since = time.Unix(s, 0) **** this should be time.Unix(s,n) for seconds then nano seconds
	}

**Comment by mikebrow** [comment]
pkg/timeutils/utils.go
// GetTimestamp tries to parse given string as golang duration,
// then RFC3339 time and finally as a Unix timestamp. If
// any of these were successful, it returns a Unix timestamp
// as string otherwise returns the given value back.
// In case of duration input, the returned timestamp is computed
// as the given reference time minus the amount of the duration.
func GetTimestamp(value string, reference time.Time) string {
	if d, err := time.ParseDuration(value); value != "0" && err == nil {
		return strconv.FormatInt(reference.Add(-d).Unix(), 10)
	}

	var format string
	if strings.Contains(value, ".") {
		format = time.RFC3339Nano
	} else {
		format = time.RFC3339
	}

	loc := time.FixedZone(time.Now().Zone())
	if len(value) < len(format) {  **** appears to be converting the format to a subset …  don’t know why this code is here, 
		format = format[:len(value)]  
	}
	t, err := time.ParseInLocation(format, value, loc)
	if err != nil {
		return value
	}
	return strconv.FormatInt(t.Unix(), 10)  **** appears to be striping the nanoseconds here and outputting only seconds should be nano or add an additional parameter for the nanoseconds
}

**Comment by phemmer** [comment]
If it's changed to send a float across the wire, this would maintain API compatibility.

**Comment by mikebrow** [comment]
#dibs
