### ISSUE TITLE
Blank "attaching to" when up'ing containers w/ docker-compose

### ISSUE THREAD

**Issue by ryanbaldwin** [docker/docker#16397]
Description of problem:
When I perform a _docker-compose up_ I see very little useful info, and logs never flow. This is different than from previous versions.

`docker version`:
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64

`docker info`:
Containers: 21
Images: 191
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 237
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.1 (TCL 6.3); master : 7f12e95 - Thu Aug 13 03:24:56 UTC 2015
CPUs: 4
Total Memory: 1.955 GiB
Name: default
ID: OHNM:3O2O:FTZO:4RFH:2FYF:4NMR:G463:ANQN:PRPL:YATX:EIRR:ER43
Debug mode (server): true
File Descriptors: 20
Goroutines: 51
System Time: 2015-09-18T11:49:15.492434043Z
EventsListeners: 1
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: ryanbaldwin
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox

`uname -a`:
Darwin slim.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64

Environment details (AWS, VirtualBox, physical, etc.):
VirtualBox, using OS X 10.10.5 + Docker Toolbox 1.8.2a install.

How reproducible:
Happens every time.

Steps to Reproduce:
1. Create a docker-compose.yml file that defines a single container. Here is mine (though I've found this to work for anything I use, not just Postgres):
````yml
dbserver:
image: postgres:9.4.4
environment:
  - POSTGRES_USER=test
  - POSTGRES_PASSWORD=Da4UJroyJRJjTMWUKbrViboLcRY2cz
ports:
  - "5432:5432"
````

2. do a _docker-compose up_
3. wait, and only ever see the following output:
````
ryanbaldwin@slim:~$ docker-compose up
Starting ryanbaldwin_dbserver_1...
Attaching to 
````

Actual Results:
_Attaching to_ stays forever, and logs never stop flowing. This is different to previous docker-compose versions where _docker-compose up_ would provide useful output about recreating containers, and then show logs. This one only ever shows "Attaching to" and nothing more, which forces me to open a different term and do a _docker-compose logs_ because I don't know if something failed to launch.

Expected Results:
To see more useful information, especially logs, as in previous versions.

Additional info:

**Comment by phemmer** [comment]
docker compose has it's own [issue tracker](https://github.com/docker/compose/issues). This should probably be over there.

**Comment by dnephin** [comment]
See https://github.com/docker/compose/issues/2067
Please close this issue
