### ISSUE TITLE
zsh completion: provide container names in addition to ids

### ISSUE THREAD

**Issue by ThiefMaster** [docker/docker#16401]
```
[adrian@pluto:~/dock]> docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                     NAMES
1238d09b7774        training/webapp     "python app.py"     11 minutes ago      Up 11 minutes       0.0.0.0:32768->5000/tcp   mad_fermat
[adrian@pluto:~/dock]> docker port
containers
1238d09b7774  --      11 minutes, training/webapp
webapp
```

Instead of the ID it would be nice if the name was in the list, too.
Also, the `webapp` in the second line probably shouldn't be there:

```
[adrian@pluto:~/dock]> docker port webapp
Error response from daemon: no such id: webapp
```

**Comment by thaJeztah** [comment]
Thanks for reporting

/cc @sdurrheimer @vincentbernat (who maintain the zsh completion scripts <3)

**Comment by vincentbernat** [comment]
I think this has been fixed by a recent PR. @ThiefMaster, could you test again with the current version?

**Comment by thaJeztah** [comment]
Latest version can be found here if you want to try it: https://github.com/docker/docker/blob/master/contrib/completion/zsh/_docker

**Comment by ThiefMaster** [comment]
Works fine :)

**Comment by thaJeztah** [comment]
Thanks for testing @ThiefMaster! I'll close this issue then :+1:
