### ISSUE TITLE
Proposal: Add Cluster Join API/CLI

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#16416]
This is a quick write up of a design to enable programmatic bootstrapping of a Docker cluster.  I will quickly submit a PR if we can decide this is generally the right direction.  The motivation of this is to allow bootstrapping a cluster in a more user friendly fashion and additionally allow scripts and other programs to setup a cluster without having to deal with distro specific configuration files to handle daemon flags.

## API

`POST /join`
```json
{
  "DiscoveryBackend": "...",
  "DiscoveryAddress": "...",
  "KvStore": "...",
}
```

## CLI

`docker join --backend ... --address .. --kv-store ...`

## Design

If no options are passed as daemon flags for `--discovery-backend`, `--discovery-address`, and `--kv-store` then the `/join` API can be used.  If any of those daemon flags are set the `/join` API should fail.  When POST-ing to `/join` the three arguments will be passed to `pkg/discovery` to initialize the discovery backend.  Additionally these parameters will be saved in `/var/lib/docker/discovery/config.json` to be used if the daemon restarts.

On start of the daemon discovery info will be read first from the CLI and then if not available will look in `/var/lib/docker/cluster/config.json`

**Comment by ibuildthecloud** [comment]
@mavenugo @icecrime

**Comment by cpuguy83** [comment]
I don't understand the reasoning behind this if it is completely non-dynamic, set it once and that's it.
At that point there is no advantage over the daemon flags.

**Comment by ibuildthecloud** [comment]
Having join not be dynamic is a compromise I discussed with @mavenugo. 

The biggest advantage is that the configuration does not require distro specific knowledge.  Today the default daemon configuration is usable by the vast majority of users.  As I support people running docker I rarely need to tell them to reconfigure the daemon and restart.  With the addition of the discovery config every user will need to do this.

It is immensely better to tell a user to run `docker join ...` then to tell them to edit a file and restart because I either have to write long instructions that cover all the distros or automate it.  Trying to automate this becomes a testing nightmare.

I absolutely beg you to consider this.  I use Docker a lot, I support a lot of users running Docker.  The beauty of Docker is that I don't have to care about the distro, it's largely all the same.  Daemon flags are a PITA, I hate them with a passion.  I've gone to great length to ensure that all solutions I build do not require changing daemon flags.  The user experience is just not good and hard to support.

**Comment by shykes** [comment]
+1 on your comment @ibuildthecloud. Dynamic, portable api calls beat static, distro-specific config files.

**Comment by LK4D4** [comment]
I have vague feeling that it was deprecated because of swarmkit.
@ibuildthecloud feel free to close if it is.

**Comment by thaJeztah** [comment]
I also opened https://github.com/docker/docker/issues/26743, to further improve Swarm mode for automated setup.

I'll go ahead and close this, but gimme a ping if it's still something to look at @ibuildthecloud
