### ISSUE TITLE
Docker logs -f is dumping entire log file

### ISSUE THREAD

**Issue by JoyceBabu** [docker/docker#16422]
Running `docker logs -f <containername>` is dumping all the lines from the container's log file, instead of the just the new lines. Wouldn't it be more useful if it behaves more like `tail -f`, i.e. last few lines + new lines?

**Comment by cpuguy83** [comment]
Hello, you can use `--tail <lines>` to handle this.

**Comment by JoyceBabu** [comment]
@cpuguy83  But doesn't it exit after printing `<lines>` lines of log? I want to follow the logs, in fact I don' t even need the old logs, just the new ones as they arrive, just like `logs -f`. But `logs -f` is currently dumping the entire log files (over 10000 lines). I finally had to clear the file, to follow the logs.

**Comment by cpuguy83** [comment]
`docker logs -f --tail <lines> <container>`

**Comment by JoyceBabu** [comment]
Aha! Thanks :)
