### ISSUE TITLE
Proposal : Adding qemu-arm in docker server to autobuild ARM based images

### ISSUE THREAD

**Issue by theshadowx** [docker/docker#16427]
These days, installing Docker in Raspberry Pi and other ARM based boards has become easier, also as for the opensource community that wants to share their applications in these board, Docker represents a great tool to encapsulate them with all the needed dependencies so that deploying them could be easy.

In the other hand, sharing image saves a lot of time than just building it , but we have to build it anyhow. The efficient way is to put the dockerfile in a git repository, link the hub to it then autobuild it in the hub. Unfortunately autobuild can't be  done for the images based on ARM processor. (Until now I haven't found a solution)

One of the solution is to implement qemu in the host (server) so that it would be possible to autobuild this kind of images. Unless  if there is already a method to that which I'm not aware of.

**Comment by theshadowx** [comment]
@GordonTheTurtle sorry turtle it's not a bug

**Comment by cpuguy83** [comment]
Hello,

Can you send this feature request to https://support.docker.com?

Thanks!
