### ISSUE TITLE
Unable to mount within a container even w/ `--cap-add=SYS_ADMIN`

### ISSUE THREAD

**Issue by dalanlan** [docker/docker#16429]
According to [docke run reference](https://docs.docker.com/reference/run/) #Runtime privilege, Linux capabilities, and LXC configuration session, it should enable mount syscall w/ `--cap-add=SYS_ADMIN`.
This is also confirmed by someone who opened #9950 with docker 1.5. 
Yet it doesn't work for me now. Is this expected?

####How to reproduce
```
$ docker run --cap-add=SYS_ADMIN -it ubuntu /bin/bash
root@1a6c069a8589:/# cd home/
root@1a6c069a8589:/home# mkdir 1
root@1a6c069a8589:/home# mkdir 2
root@1a6c069a8589:/home# mount --bind 1 2
mount: block device /home/1 is write-protected, mounting read-only
mount: cannot mount block device /home/1 read-only
root@1a6c069a8589:/home# exit
$ docker run --cap-add=ALL -it ubuntu /bin/bash
root@1e04bcd81fee:/# cd home/
root@1e04bcd81fee:/home# mkdir 1
root@1e04bcd81fee:/home# mkdir 2
root@1e04bcd81fee:/home# mount --bind 1 2
mount: block device /home/1 is write-protected, mounting read-only
mount: cannot mount block device /home/1 read-only
root@1e04bcd81fee:/home# exit
```
`--privileged` is all right though. FYI.
####ENV 
docker version: 1.7.1
platform: ubuntu 12.04

/cc @cpuguy83

**Comment by dalanlan** [comment]
Does not work with docker 1.8.2 either. 
My guess it's a bug.
```
$ docker run --rm -it --cap-add SYS_ADMIN ubuntu /bin/bash
root@52c5d275b818:/# cd home/
root@52c5d275b818:/home# ls
root@52c5d275b818:/home# mkdir 1 
root@52c5d275b818:/home# mkdir 2
root@52c5d275b818:/home# mount --bind 1 2
mount: block device /home/1 is write-protected, mounting read-only
mount: cannot mount block device /home/1 read-only
root@52c5d275b818:/home# exit
$ docker info
Containers: 43
Images: 212
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 303
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.11.0-26-generic
Operating System: Ubuntu precise (12.04.5 LTS)
CPUs: 4
Total Memory: 7.718 GiB
Name: emma-OptiPlex-3010
ID: LPC7:QFZN:IFY7:ALEL:FXQB:I56Q:KZP3:TWWT:AM53:VPOT:6YKB:P6BT
Username: dalanlan
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```
/cc @ewindisch who answered related issue reported on docker-user group

**Comment by petrosagg** [comment]
I started facing the same issue on Ubuntu Vivid 15.04 when I updated the kernel from `3.19.0-26-generic` to `3.19.0-28-generic`.

On `3.19.0-28-generic` I've confirmed the issue happens with docker `1.6.2`, `1.7.1`, and `1.8.2` on both `btrfs` and `overlayfs` storage drivers.

Here is the kernel log of ubuntu, however I can't see anything that could affect capabilities.
http://kernel.ubuntu.com/git/ubuntu/ubuntu-vivid.git/log/

Mounting works on both kernels when `--privileged` is used.

```bash
vagrant@resinvm ~ $ docker info
Containers: 11
Images: 38
Storage Driver: btrfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-28-generic
Operating System: Ubuntu 15.04
CPUs: 2
Total Memory: 1.954 GiB
Name: resinvm
ID: EUBC:CECU:IFCX:BWT6:BFBG:SWQC:T7N2:AZSK:NWCY:6P56:ERPP:MZCT
Username: resindev
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Comment by cpuguy83** [comment]
This looks like an apparmor issue.
Works fine in b2d, not on Ubuntu.

**Comment by cpuguy83** [comment]
ping @ewindisch

**Comment by petrosagg** [comment]
Disabling apparmor indeed fixes the issue. However, something extra must be going on because if I only change the default kernel in `/boot/grub/grub.conf` and nothing else, it is enough to go between working and not working.

**Comment by ewindisch** [comment]
Users are not advised to disable AppArmor globally. This can be disabled per-container using '--security-opt apparmor:unconfined'.

**Comment by petrosagg** [comment]
I completely agree. My main point is that `mount()` in a container that has the `--cap-add=SYSADMIN` **does** work with AppArmor enabled with a slightly different kernel. I'll try to bisect the two kernel versions to see which commit breaks it.

**Comment by LK4D4** [comment]
Yup, it will be good info for documentation if not report to apparmor maintainers.

**Comment by ewindisch** [comment]
@petrosagg  but it seems to me the incorrect behavior (allowing mount) was only with an older kernel, yes? If so, it would seem the bug is already fixed upstream.

**Comment by petrosagg** [comment]
@ewindisch no, the bug appears when I upgrade to a newer one. `3.19.0-26-generic` works, `3.19.0-28-generic` fails.

**Comment by cpuguy83** [comment]
The expected behavior here is that if a user has CAP_SYS_ADMIN then that user should be able to mount.

**Comment by ewindisch** [comment]
@cpuguy83 that is not true when AppArmor is enabled on the host. There may be a kernel regression to be verified.

**Comment by petrosagg** [comment]
Finally finished the bisect. Found the commit [1] and relevant bug [2] that cause the issue on Ubuntu 15.04. It looks like they backported it from linux 4.0. There are still a couple of question marks for me though.

1. Why is this also happening with btrfs, since btrfs backend works with subvolumes. Hm, unless subvolumes use the virtual dentries. I'm unaware of that.
2. I couldn't find an equivalent commit for the `3.11.0-26-generic` kernel that @dalanlan is using on Ubuntu 12.04.

[1] http://kernel.ubuntu.com/git/ubuntu/ubuntu-vivid.git/commit/?id=371a54cdf42d545a43641fadd106aaf88adb3f3a
[2] https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1479468

**Comment by ewindisch** [comment]
This is strange because it wouldn't seem that the filesystem/VFS would be at all questioned when testing the mount syscall denial in AppArmor?

@petrosagg I'll send you an email.

**Comment by danbeaulieu** [comment]
I am seeing this same thing. I typically start my containers with cap_sys_admin capability to allow mounting, but with 1.9 I need to make the container privileged...

root@ip-10-149-108-196:~# docker info
Containers: 7
Images: 50
Server Version: 1.9.0
Storage Driver: devicemapper
 Pool Name: docker-202:1-271547-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 5.07 GB
 Data Space Total: 107.4 GB
 Data Space Available: 2.148 GB
 Metadata Space Used: 6.91 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.141 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-67-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 2
Total Memory: 3.676 GiB
Name: ip-10-149-108-196
ID: SQHE:Q4EL:X4SR:EGER:L5QA:D75O:POGF:BKK4:6H7N:MOMN:WJ4Q:IKC3
WARNING: No swap limit support

**Comment by ctindel** [comment]
Had there been any progress on this?  I'm seeing the same issue trying to mount tmpfs on a container under synology DSM6, and when I stop apparmor completely I'm not able to run any containers due to other errors.

**Comment by ksb2go** [comment]
I had the same issue and launching with ``` docker run --cap-add=SYS_ADMIN --security-opt apparmor:unconfined ``` worked for me. Thanks.

**Comment by thaJeztah** [comment]
Looks like this is resolved, so I'll close this issue, but feel free to comment after I closed

**Comment by ps1dr3x** [comment]
I still have this issue in a debian stretch based container, kernel version `4.17.0-3-amd64`. Disabling apparmor works also for me, but i think this isn't the right way, only a workaround.
Anyone here has news about this issue?

**Comment by jleadford** [comment]
let me know if i'm off-base here, but looks like there's a general conflict between default apparmor and seccomp here?

i.e. mount is punched through for seccomp if you're granted SYS_ADMIN

https://github.com/moby/moby/blob/a1ec8551ab48962c0b71111de8917c189bf0226b/profiles/seccomp/default.json#L564-L586

but apparmor still denies the mount operation

https://github.com/moby/moby/blob/a1ec8551ab48962c0b71111de8917c189bf0226b/profiles/apparmor/template.go#L35

**Comment by xuxucode** [comment]
Maybe it's better to use a custom AppArmor profile instead of 'unconfined':
`docker run -it --cap-add SYS_ADMIN --security-opt apparmor=my-profile ubuntu bash`

#### my-profile
The profile is modified based on [docker-default](https://github.com/moby/moby/issues/33060#issuecomment-1948635934) profile on Ubuntu.
```
#include <tunables/global>

profile my-profile flags=(attach_disconnected,mediate_deleted) {
  #include <abstractions/base>

  network,
  capability,
  file,
  umount,
  # Host (privileged) processes may send signals to container processes.
  signal (receive) peer=unconfined,
  # dockerd may send signals to container processes (for "docker kill").
  signal (receive) peer=unconfined,
  # Container processes may send signals amongst themselves.
  signal (send,receive) peer=my-profile,

  deny @{PROC}/* w,   # deny write for all files directly in /proc (not in a subdir)
  # deny write to files not in /proc/<number>/** or /proc/sys/**
  deny @{PROC}/{[^1-9],[^1-9][^0-9],[^1-9s][^0-9y][^0-9s],[^1-9][^0-9][^0-9][^0-9/]*}/** w,
  deny @{PROC}/sys/[^k]** w,  # deny /proc/sys except /proc/sys/k* (effectively /proc/sys/kernel)
  deny @{PROC}/sys/kernel/{?,??,[^s][^h][^m]**} w,  # deny everything except shm* in /proc/sys/kernel/
  deny @{PROC}/sysrq-trigger rwklx,
  deny @{PROC}/kcore rwklx,

  # NOTE: enable mount instead of "deny mount"
  mount,

  deny /sys/[^f]*/** wklx,
  deny /sys/f[^s]*/** wklx,
  deny /sys/fs/[^c]*/** wklx,
  deny /sys/fs/c[^g]*/** wklx,
  deny /sys/fs/cg[^r]*/** wklx,
  deny /sys/firmware/** rwklx,
  deny /sys/devices/virtual/powercap/** rwklx,
  deny /sys/kernel/security/** rwklx,

  # suppress ptrace denials when using 'docker ps' or using 'ps' inside a container
  ptrace (trace,read,tracedby,readby) peer=my-profile,
}
```
