### ISSUE TITLE
FATA[0000] Error response from daemon: Cannot start container ********************: [8] System error:fork/exec /usr/bin/docker: invalid argument

### ISSUE THREAD

**Issue by captainmingo** [docker/docker#16424]
when I am running this command
#docker run -i -t centos /bin/bash 
then i am getting this error.
what is solution???

**Comment by captainmingo** [comment]
1-DOCKER-VERSION:
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
2-DOCKER INFO:
Containers: 12
Images: 11
Storage Driver: devicemapper
 Pool Name: docker-0:16-18011-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: aufs
 Data file: /dev/loop5
 Metadata file: /dev/loop6
 Data Space Used: 878 MB
 Data Space Total: 107.4 GB
 Data Space Available: 1.226 GB
 Metadata Space Used: 1.597 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 1.226 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.79 (2013-08-13)
Execution Driver: native-0.2
Kernel Version: 3.17.4-porteus
Operating System: Slackware 14.1
CPUs: 4
Total Memory: 3.757 GiB
Name: porteus
ID: H536:VLMW:EDAU:CADS:K5YT:VBGG:5IGE:ZMEG:CDX4:BK5J:IAUU:Q47O
WARNING: N
![snapshot1](https://cloud.githubusercontent.com/assets/14361136/9976954/7c5cc37e-5ee5-11e5-8521-2eaabc55490c.png)
o memory limit support
WARNING: No swap limit support
3-UNAME -A
Linux porteus 3.17.4-porteus #1 SMP PREEMPT Fri Dec 12 12:48:28 Local time zone must be set-- x86_64 Intel(R) Core(TM) i3-3217U CPU @ 1.80GHz GenuineIntel GNU/Linux

RESULT:FATA[0000] Error response from daemon: Cannot start container 780a5417eaddb7d64622aa09b23de2c218a26548a0e6a411e708b19a6b3a379c: [8] System error: fork/exec /usr/bin/docker: invalid argument

EXPECTED RESULT:
$ docker run -t -i centos /bin/bash
bash-4.1#

**Comment by thaJeztah** [comment]
Are you still having this issue with the current release?

/cc @vbatts because it looks like you're maintaining a docker package for slackware; http://slackbuilds.org/repository/14.1/system/docker/

**Comment by vbatts** [comment]
@thaJeztah i am, but this is not a supported setup.

the `docker info` shows using a backend filesystem of `Backing Filesystem: aufs` with `devicemapper` driver. This is bonkers and should never work.
Further Slackware kernel does not include AUFS patches or packages. @captainmingo must have patched the kernel and manually configured devicemapper. This is in no way a supported set up, and very likely to get a kernel error like `invalid argument`.

**Comment by captainmingo** [comment]
yes

on current release i am facing diffrent type of issues.



On Mon, Nov 2, 2015 at 7:38 PM, Sebastiaan van Stijn <
notifications@github.com> wrote:

> Are you still having this issue with the current release?
>
> /cc @vbatts <https://github.com/vbatts> because it looks like you're
> maintaining a docker package for slackware;
> http://slackbuilds.org/repository/14.1/system/docker/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/16424#issuecomment-153025214>.
>



-- 
RAM SWAROOP MISRA

**Comment by vbatts** [comment]
@captainmingo ideally, try devicemapper with a dedicated lvm thin pool device. and use only ext4 or xfs for its backing filesystem.
Otherwise try `overlay` or `btrfs`. Personally, I've been on btrfs and like it.

**Comment by captainmingo** [comment]
Thank you so much Vincent.

I will try.

On Mon, Nov 2, 2015 at 10:09 PM, Vincent Batts <notifications@github.com>
wrote:

> @captainmingo <https://github.com/captainmingo> ideally, try devicemapper
> with a dedicated lvm thin pool device. and use only ext4 or xfs for its
> backing filesystem.
> Otherwise try overlay or btrfs. Personally, I've been on btrfs and like
> it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/16424#issuecomment-153076892>.
>



-- 
RAM SWAROOP MISRA

**Comment by bloodymind** [comment]
I have the same issue here , no fixes yet ?
