### ISSUE TITLE
Return fake kernel info to container

### ISSUE THREAD

**Issue by linquize** [docker/docker#16423]
I am using Docker 1.6

Problem: 64-bit Linux host, but 32-bit Linux container.
Inside 32-bit container, run `uname -m` and it returns `x86_64` which is from the host kernel.
This may cause problems inside 32-bit container, because some software rely on this CPU architecture identifier to perform their tasks.

I suggest to add function to return fake kernel info to container.

**Comment by linquize** [comment]
```
$ docker version 
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

$ docker info
Containers: 19
Images: 187
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 225
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.19.0-18-generic
Operating System: Ubuntu 15.04
CPUs: 4
Total Memory: 7.704 GiB
Name: Ubt4
ID: ZQI3:QJZU:RRAU:DMVW:PG7V:YLDC:ODUD:MWMT:QOOI:6X32:OCPZ:TGOR
WARNING: No swap limit support

$ uname -a
Linux Ubt4 3.19.0-18-generic #18-Ubuntu SMP Tue May 19 18:31:35 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

physical PC

`docker run -it --rm steeb/debian-32:wheezy /bin/bash`
`uname -m` returns x86_64

**Comment by cpuguy83** [comment]
This behavior is no different than running outside the container.
We cannot change this behavior, and even so doing this would be potentially dangerous.
If you really need such behavior, replace `uname` in the container with your own binary.

Thanks!

**Comment by linquize** [comment]
So I should workaround by wrapping / replacing `uname` in my 32-bit container.

**Comment by cpuguy83** [comment]
Yep!

**Comment by linquize** [comment]
What happen if the app relies on `/proc/version` that cannot be replaced?

**Comment by unclejack** [comment]
That's a broken app which needs to be fixed.

**Comment by ekovacs** [comment]
answers like that upsets me, and makes me give a thumb down.
...but case closed, problem solved, please disperse nothing to see here...



![giphy](https://user-images.githubusercontent.com/1477846/29119757-bad11456-7d07-11e7-9f8d-56df4b484833.gif)

**Comment by AkihiroSuda** [comment]
SystemTap could be used for that purpose, but unrelated to this repo

**Comment by jnj16180340** [comment]
@linquize @ekovacs I ran into this when cross-building ARM binaries in a container via qemu using a build system that checks `/proc/cpuinfo` for architecture (yeah...)

In principle, you can just overwrite `/proc/stuff` by bind-mounting your replacement file.

On the host:
- Run container in privileged mode: `docker run --privileged ...`

In the container:
- file `cpuinfo.raspi3` exists, was generated by `cat /proc/cpuinfo` on an actual device + committed to repo
- `sudo mount --bind ./cpuinfo.raspi3 /proc/cpuinfo` at runtime
