### ISSUE TITLE
docker/windows/virtualbox/corporate proxy/cannot connect to hub/tri

### ISSUE THREAD

**Issue by sudhevan** [docker/docker#16426]
I am running docker on windows using virtualbox in a corporate machine.
I cannot connect docker hub, not even able to login to hub
tried all the options which are suggested in this forum with no luck.
Need some expert advise please.

$ docker run --env http_proxy=http://proxy.com:8080 hello-world
Unable to find image 'hello-world:latest' locally
Pulling repository docker.io/library/hello-world
Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/hello-world/images. You may want to check your internet connection or if you are behind a proxy.

docker@default:~$ docker login
Username: user
Password:
Email: email
Error response from daemon: Server Error: Post https://index.docker.io/v1/users/: dial tcp 54.174.187.194:443: i/o timeout

docker@default:~$ cat /var/lib/boot2docker/profile

EXTRA_ARGS='
--label provider=virtualbox

'
CACERT=/var/lib/boot2docker/ca.pem
DOCKER_HOST='-H tcp://0.0.0.0:2376'
DOCKER_STORAGE=aufs
DOCKER_TLS=auto
SERVERKEY=/var/lib/boot2docker/server-key.pem
SERVERCERT=/var/lib/boot2docker/server.pem
HTTP_PROXY=http://proxy.com:8080/
HTTPS_PROXY=http://proxy.com:8080

**Comment by sudhevan** [comment]
Hi Gordon,
i searched everywhere and almost tried all the options with no luck, need some expert level debugging, thanks.

there are no certificates installed on my server, and canot install them using apt-get
docker@default:~$ apt-get
-sh: apt-get: not found

here is the details from the server
docker@default:~$ curl -L -k https://index.docker.io/v1/repositories/library/ubuntu/images
curl: (56) Received HTTP code 400 from proxy after CONNECT
docker@default:~$

docker@default:~$ docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      linux/amd64
docker@default:~$ docker info
Containers: 11
Images: 3
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 25
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.2 (TCL 6.4); master : aba6192 - Thu Sep 10 20:58:17 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: UAJS:2YZW:Z2VW:232X:UEPS:YBAS:SEBU:4KY5:R4YH:7R5J:FM5B:EVAJ
Debug mode (server): true
File Descriptors: 12
Goroutines: 17
System Time: 2015-09-19T17:53:41.193980115Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
docker@default:~$ uname -a
Linux default 4.0.9-boot2docker #1 SMP Thu Sep 10 20:39:20 UTC 2015 x86_64 GNU/Linux
docker@default:~$

**Comment by sudhevan** [comment]
hi, Is there a way i can fix this issue? 
or alternatively from where can i download the image tar files to load them using "docker load" ?

**Comment by cpuguy83** [comment]
You should be able to use the http proxy by setting the environment variable on your client.

For instance: `HTTP_PROXY=proxy.com:80 docker pull busybox`
And then if you need access from inside the container you would set the HTTP_PROXY  on `docker run -e HTTP_PROXY=proxy.com:80`

For help, please see the docker-user mailing list, #docker on IRC, or forums.docker.com

Thanks!

**Comment by sudhevan** [comment]
still cannot connect, raised a request on docker forum.

docker@default:~$ HTTP_PROXY=http://proxy.com:8080/
docker@default:~$ docker pull busybox
Using default tag: latest
Pulling repository docker.io/library/busybox
Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/busybox/images. You may want to check your internet connection or if you are behind a proxy.

**Comment by alexandrem** [comment]
I know the pain of corporate proxies.

When using docker-machine to bootstrap your docker/virtualbox, ensure you pass the proxy env variables:

docker-machine create -d virtualbox \
    --engine-env HTTP_PROXY=http://proxy.company.com:3128 \
    --engine-env HTTPS_PROXY=http://proxy.company.com:3128 \
    default

On a side note, if you have a proxy that requires authentication then you might want to look at using CNTLM on your workstation with proper configuration instead, which should solve 99% of all the issues that softwares have with proxies (especially with credentials). You then just have to use "http_proxy=http://localhost:3128" everywhere.

When using nested virtualized environments with virtualbox, like vagrant and docker-machine (formally boot2docker), then you need to pass the following parameters instead:

docker-machine create -d virtualbox \
    --engine-env HTTP_PROXY=http://10.0.2.2:3128 \
    --engine-env HTTPS_PROXY=http://10.0.2.2:3128 \
    default

Note the use of the VBox gateway 10.0.2.2.

**Comment by xavierchow** [comment]
Recreating the machine with the proxy env passed works for me. Thanks @alexandrem

**Comment by fnishi** [comment]
@alexandrem solution worked for me too

thanks!

**Comment by elan100cs** [comment]
@alexandrem suggestions works for me also. Before that, i tried going inside the machine and set http_proxy and https_proxy environment variable. It doesnt seemed to work. It seems as suggested by @alexandrem this needs to be done during the creation of the machine.

**Comment by softwareklinic** [comment]
how do i acheive this on linux--- i have docker on ubuntu (AWS) --- and have a container that cannot talk to internet - since im behind corporate proxy... any insights... im kind of stuck

**Comment by elan100cs** [comment]
@softwareklinic This is a thread for windows, I suggest you post your problem on another issue thread. There is also a documentation in the docker site https://docs.docker.com/engine/admin/systemd/ how to achieve this.
