### ISSUE TITLE
Mount directory to host option

### ISSUE THREAD

**Issue by d2xdt2** [docker/docker#16421]
Right one have to use a [helper container](https://docs.docker.com/userguide/dockervolumes/#backup-restore-or-migrate-data-volumes) to make backups of data in containers, which seams like a hacky way to compensate for a still to come feature in Docker.

I propose a `mount` option which will make directories available on the host. Example:

```
FROM fedora:22
RUN dnf -y install httpd
MOUNT ["/var/www/html:html:rw", "/var/log/httpd:logs:ro"]
CMD ["/usr/sbin/httpd", "-DFOREGROUND"]
```

Running

```
docker build -t test80 .
docker run -d test80
```

would make the following two directories on the host

```
/var/lib/docker/mount/test80/html
/var/lib/docker/mount/test80/logs
```

Here the `mount` option uses the `volume` syntax in array form.

This would making backups a lot easier and more intuitive and giving a kind of `volume` but with correct container file ownership.

**Comment by cpuguy83** [comment]
No, we cannot support this.
It would be incredibly dangerous for host security, and makes for potentially very inconsistent builds.
In addition there are already a number of proposals open for support volumes on build, so this would be a dup.
