### ISSUE TITLE
Problem with volume mounting lingering files

### ISSUE THREAD

**Issue by tlovett1** [docker/docker#16434]
Steps to reproduce:

1. I create/run a container like so:
  `docker run -it -v /path/to/folder:/tmp/test my-image`

2. Within the container, I create a file named `TEST` inside the mounted folder at `/tmp/test`.

3. I exit the container. I then remove the container like so:
  `docker rm -v CONTAINER-ID`

4. Now the file `TEST` still exists on the host machine on the folder I mounted.

Providing the `-v` option to `docker rm` doesn't seem to properly remove the volume.

**Comment by cpuguy83** [comment]
Hello, this is expected behavior.
Docker will not remove dirs/files bind-mounted from the host like that.

**Comment by tlovett1** [comment]
Can you tell me how to properly remove those files then?

**Comment by cpuguy83** [comment]
They are normal files, you can `rm -rf <path to files>`
