### ISSUE TITLE
 docker data in the absence of uninstalling partition will damage when reboot server 

### ISSUE THREAD

**Issue by ystyle** [docker/docker#16436]
my company deploy a docker server and changed docker runtime dir win  --graph option ,
because the dir in umount partition ,then pull some images and run them ,
but every time reboot the server ,the docker services is don't work ,can't restart 

so copy back data to Cover every times

**Comment by cpuguy83** [comment]
Can you provide exact steps, what the the issue you are seeing is, and what you expected?

Thanks!

**Comment by ystyle** [comment]
[root@AY1304241510022 ~]# docker version
Client version: 1.7.1
Client API version: 1.19
Package Version (client): docker-1.7.1-108.el7.centos.x86_64
Go version (client): go1.4.2
Git commit (client): 3043001/1.7.1
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Package Version (server): docker-1.7.1-108.el7.centos.x86_64
Go version (server): go1.4.2
Git commit (server): 3043001/1.7.1
OS/Arch (server): linux/amd64

[root@AY1304241510022 ~]# docker info
Containers: 2
Images: 20
Storage Driver: devicemapper
 Pool Name: docker-202:21-2654347-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 4.467 GB
 Data Space Total: 107.4 GB
 Data Space Available: 48.92 GB
 Metadata Space Used: 3.813 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /mnt/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /mnt/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-123.9.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 3.452 GiB
Name: AY1304241510022
ID: FONR:6SFB:5FQT:3YKU:NQ2M:MRXJ:6KYB:K3DX:DSWG:VOW6:G2VJ:55EP

[root@AY1304241510022 ~]# uname -a
Linux AY1304241510022 3.10.0-123.9.3.el7.x86_64 #1 SMP Thu Nov 6 15:06:03 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

1. install docker(and systemctl enable docker) , edit /etc/sysconfig/docker options ,change runtime dir(othor Partition ,umount ) with --graph option;
2. pull some image e.g. ubuntu and run it .

3. backup new runtime dir and reboot 

now the docker is no working

**Comment by cpuguy83** [comment]
Can you provide the logs from the daemon startup after it fails?

**Comment by ystyle** [comment]
There is something I describe the error,
the Partition is not umount , it's don't in /etc/fstab,so the Partition is can't mount automatic on start server.

where the logs file

**Comment by thaJeztah** [comment]
Are you still having this issue? This sounds like a configuration issue to me, not a bug in Docker, but perhaps I'm misunderstanding

**Comment by LK4D4** [comment]
Closing as inactive.
