### ISSUE TITLE
docker 1.8.2 --link mess with /etc/hosts 

### ISSUE THREAD

**Issue by MichaelBitard** [docker/docker#16445]
Description of problem: 
/etc/hosts seems to mess with linked containers.

This reproduce on multiple machines : 
I run a container linked to 3 other containers 

```
"Links": [
            "/cosmos:/babylon/cosmos",
            "/doorman:/babylon/doorman",
            "/loadout:/babylon/loadout"
]
```

It works for a while, then stop working. When I ```docker exec -ti babylon cat /etc/hosts``` 

sometimes there is nothing, but sometimes there are other hosts that were NEVER linked with this container : 

I expected : 
```
10.0.30.138     caa3227dba57
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
10.0.0.14       cosmos 7c9481205bfd
10.0.0.13       doorman 7a7c3aba63ba
10.0.0.3        loadout 925f5601359b
```

I got : 
```
10.0.30.134     farcaster-aggtempo
10.0.30.134     farcaster-aggtempo.bridge
10.0.30.135     collector-netflow-wan
10.0.30.135     collector-netflow-wan.bridge
```

When I docker restart the container it seems to work for a while, then again everything is messed up

`docker version`:
```
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:
```
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64
louser@BT-LABS-TEST:/data/logs/babylon$ docker info
Containers: 23
Images: 208
Storage Driver: aufs
 Root Dir: /data/docker/aufs
 Backing Filesystem: extfs
 Dirs: 256
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 8
Total Memory: 19.61 GiB
Name: BT-LABS-TEST
ID: KUTS:7RVR:KDJL:VYSH:XDTO:PC6T:47D7:J43A:W72H:PLQD:GVKT:SY37
WARNING: No swap limit support
```

`uname -a`: Linux BT-LABS-TEST 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.): physical

How reproducible:
I can reproduce it on 2 machines : ubuntu 14.04.3 server with docker 1.8.2

I had'nt any problem with the same docker images on docker 1.7.2

**Comment by MichaelBitard** [comment]
I downgraded docker to 1.8.1 to see if the issue is still here

**Comment by cpuguy83** [comment]
I believe the extra hosts is expected since 1.8.0

ping @mavenugo for issues with network breaking in a container.

**Comment by MichaelBitard** [comment]
This is not a problem with the extra hosts, I was aware of that.
The issue is that a some point, everything is messed up in the /etc/hosts and the links don't work anymore.

More troublesome, As soon as i started to see strange behaviors in the application,  I did `docker exec -ti babylon cat /etc/hosts` several times and I got completely differents results.

I got one time where /etc/hosts was completely empty, another where I got some extra hosts but not the linked one,...

This does not seem to reproduce on 1.8.1

**Comment by MichaelBitard** [comment]
This issue is also present in 1.8.1, tested on Oracle Enterprise Linux.

We are the only one facing this issue ?

**Comment by LK4D4** [comment]
ping @mavenugo @mrjana

**Comment by mavenugo** [comment]
@MichaelBitard @LK4D4 this behavior was introduced as part of the inbuilt service discovery functionality in libnetwork. We acknowledge this issue and it will be addressed as part of https://github.com/docker/libnetwork/issues/567 for 1.9

**Comment by MichaelBitard** [comment]
Thanks,

I assume this is partly caused by a cron which start a docker container every minute

**Comment by thaJeztah** [comment]
@mavenugo do you want to keep this issue open, or track it via https://github.com/docker/libnetwork/issues/567?

**Comment by thaJeztah** [comment]
Also see https://github.com/docker/docker/issues/16619

**Comment by mavenugo** [comment]
closed via https://github.com/docker/docker/pull/17325
