### ISSUE TITLE
Proposal: Add custom fields to journald logging

### ISSUE THREAD

**Issue by ceecko** [docker/docker#16446]
When using journald for logging, it would be nice to have a way to add a custom field to the journald log.

Example: When there are several containers running the same application, to filter all log messages from a single app, you have to list all container IDs which belong to the app. Having the possibility to define a custom field for each container would make the filtering much easier e.g. `journal-ctl APP_ID=<id>` instead of `journal-ctl CONTAINER_ID=<id1> CONTAINER_ID=<id2> CONTAINER_ID=<id3>`

**Comment by runcom** [comment]
This could be linked to https://github.com/docker/docker/pull/15975
If labels are added to the logger context (even in journald) you could easly set labels on each container and filter by these in journalctl)

**Comment by ceecko** [comment]
@runcom is it possible to set labels per container? I only found labels for daemon and images at https://docs.docker.com/userguide/labels-custom-metadata/

**Comment by runcom** [comment]
@ceecko docs may need enhancement but yes you can do `docker run --label`

**Comment by ceecko** [comment]
This sounds good. Labels in custom fields would work for this use case.

**Comment by runcom** [comment]
https://github.com/docker/docker/pull/15975 has been merged, I suppose this can be closed now, but ping me I'm wrong

**Comment by ceecko** [comment]
Thanks, LGTM
