### ISSUE TITLE
Container Networking - Set firewall inside a container

### ISSUE THREAD

**Issue by hkuyam007** [docker/docker#16447]
Let's say I have 5 containers (A,B,C,D,E) on the same host. 
I want to setup firewall rules for container A such that only container B would be able to access it on a specific port say 22 (SSH). Remaining containers would be blocked, even container linking would be blocked

1. Where should I setup the firewall rule? inside container A or on docker hosted in NAT table?
    and how?

2. Even if I setup specific firewall rules manually, will docker daemon override existing rule or add new rule to allow connections, if I use container linking to link, say Container C to Container A? 
If yes, how to block or stop connections through container linking?

**Comment by cpuguy83** [comment]
You can do this at the daemon level by setting `--icc=false`. This will disable all inter-container communication except for containers which are linked, and even then only over ports which have been exposed.

Closing as this is not a docker issue.
For support/questions, please use #docker on IRC, the docker-user mailing list, or forums.docker.com
Thanks!
