### ISSUE TITLE
docker version 1.8.2 has issues pulling from docker registry version 1.5

### ISSUE THREAD

**Issue by fueler** [docker/docker#16459]
Below is the command and the output. I've tried all kind of debug options but this is the only thing that gets printed. This has been repeated by others. Using docker 1.7, 1.6 and 1.5 does not have this problem when pulling image.

docker pull corporate-server:4713/my-build-env:latest
Pulling repository corporate-server:4713/my-build-env

invalid character 'b' looking for beginning of value

**Comment by LK4D4** [comment]
was fixed
