### ISSUE TITLE
TTL for containers

### ISSUE THREAD

**Issue by bsideup** [docker/docker#16478]
Hi!

We're running Docker during CI testing. Since test process could be interrupted (i.e. restart of CI system) there will be some Docker containers which are not used anymore, but they are still running and consume memory and CPU. 

What we expect is something like "TTL" (Time-to-live) option when running container, so it will be killed after specified amount of time.

Thanks!

**Comment by phemmer** [comment]
With PR #15307, I think you can do this (haven't tried).

    cid=$(docker run -d --stop-signal=0 foo)
    docker stop -t 300 $cid &

This will stop the container after 300 seconds. The `--stop-signal=0` is the part that makes this work. Signal 0 is an allowed signal, but it's a no-op usually used to check that the target process is alive.

This technique will work even if the client process running `docker stop` gets killed. The process sends the request off to the daemon, and it's the daemon that enforces the timeout. The client is just sitting waiting for it. Backgrounding it is just the easiest method to get it out of the way.

**Comment by cpuguy83** [comment]
This is a dup of #6688

**Comment by phemmer** [comment]
@cpuguy83 I don't believe it is. #6688 is about cleaning up stopped containers after they haven't been used for a while. This issue is about stopping containers.

**Comment by cpuguy83** [comment]
I see it as a different use-case for the same feature.

**Comment by phemmer** [comment]
I don't see how.
Use case: stopping containers which have not been attached in X minutes
Feature #6688: remove stopped containers which exited X minutes ago.

The feature does not satisfy the use case.

**Comment by cpuguy83** [comment]
@phemmer I see the generic case, perform some action on a container after a given time.

**Comment by cpuguy83** [comment]
But maybe I'm mis-reading?

**Comment by bsideup** [comment]
Hi @phemmer & @cpuguy83,

Sorry for resurrecting some super old issue, but I need it again and want to keep the conversation going.

I tried `docker stop -t` hack. While it works, it seems that it doesn't serve the purpose for me:
1) signal have to be set on the container. Stop signal `0` doesn't work anymore (tested with `17.12.0-ce`), I'm using `SIGINFO(3)` now.
2) `docker stop -t 10 $CID & sleep 5 && docker stop -t 10 $CID` will stop the container after 10 secs, not after 15 secs (i.e. new `stop` command does not override the previous one), which makes it useless for the use-case where I want to continuously extend the lifetime of a container until I stop doing that.

Background:
I'm one of the developers of https://github.com/testcontainers/testcontainers-java library.
We want to introduce a system to keep the containers we create up and running until our own process dies (i.e. user kills the tests).
Unfortunately, Java does not execute the shutdown hooks if you `kill -9` it. Because of that, we have to report "Hey, I still keep control of that container", and if we stop, we want the daemon to kill the container.

**Comment by thaJeztah** [comment]
> Stop signal 0 doesn't work anymore (tested with 17.12.0-ce)

Could you open an issue for that? If that used to work, and no longer does, that sounds like a bug.

When opening that issue, could you include the last version of docker (if you know) where this still worked on?
