### ISSUE TITLE
Sometimes the Create button on hub.docker.com fails to work. 

### ISSUE THREAD

**Issue by chamunks** [docker/docker#16472]
In certain browsers namely Safari Version 8.0.8 (10600.8.9) and google chrome Version 45.0.2454.93 (64 bit) the Create button fails to be clickable. 

![http://i.imgur.com/ayiJMih.png](http://i.imgur.com/ayiJMih.png)

**Comment by chamunks** [comment]
I believe this is all of the information I could possibly provide if there is any more procedures you'd like me to follow please let me know.  Since this doesn't apply to the docker daemon or engine or anything except for the docker hub registry there is no uname -a or docker info or docker version applicable in this scenario.  

The steps to reproduce the issues are pretty much described effectively in the screenshot and body of the report. The results I expected was a button that was clickable hence why I wrote that.

**Comment by calavera** [comment]
Hi @chamunks. Please, feel free to redirect your questions about hub.docker.com to https://github.com/docker/hub-feedback. You'll get better answers there.

I'm closing this issues since it doesn't belong to this repo.

Cheers.

**Comment by chamunks** [comment]
@calavera I was only directed here from #docker on freenode.
