### ISSUE TITLE
HostConfig.MemorySwap changed from 0 to -1 on some systems

### ISSUE THREAD

**Issue by jperville** [docker/docker#16476]
# Description of problem

On some systems (see below), creating containers with `--memory=<positive value> and --memory-swap=0` results in the value of `HostConfig.MemorySwap` being `-1` instead of the provided `0`.

The consequence is that on affected systems, all containers managed by the chef-docker cookbook will be redeployed at every chef-run because the provided and the actual values for `docker_container.memory_swap` differ. See original report (and reproduction instructions, and workaround) here: https://github.com/bflad/chef-docker/pull/451

# System information

`docker version`:

```
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:

```
Containers: 48
Images: 62
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 158
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 2
Total Memory: 993.1 MiB
Name: resources-182-ubuntu-1404
ID: EZVD:FBWT:INFX:XU2C:WBKF:5OE6:4K7J:ZSXJ:2QMQ:6KXI:N2XY:GVAS
WARNING: No swap limit support
```

`uname -a`: `Linux resources-182-ubuntu-1404 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

# Environment details (AWS, VirtualBox, physical, etc.)

Both VM (kitchen) and physical.

# How reproducible

Systematic on some systems (like my kitchen VM) and never on other systems (at least 1 production server)

# Steps to Reproduce:
1. git checkout https://github.com/bflad/chef-docker.git
2. install the [chef development kit](https://downloads.chef.io/chef-dk/ubuntu/) to provide the 'kitchen' command
3. run `kitchen converge resources-182-ubuntu-1404`
4. in another terminal run `kitchen login resources-182-ubuntu-1404` to enter the VM
5. run `sudo docker run -d --name xxx --memory=128m --memory-swap=0 busybox:ubuntu-14.04 nc -lp 777`
6. run `sudo docker inspect -f 'memory: {{ .HostConfig.Memory }}, memory_swap: {{.HostConfig.MemorySwap }}'  xxx`

## Actual Results

The value of `.HostConfig.Memory` is `-1`

## Expected Results

The value of `.HostConfig.Memory` should be `0`, as specified in the docker-run command-line

## Additional info

Workaround is actually to specify `--memory-swap=-1` because the code branches on strictly positive value (see [code](https://github.com/docker/docker/blob/dac92a8afbe0900641afa00e33e84e180d432239/vendor/src/github.com/opencontainers/runc/libcontainer/cgroups/fs/memory.go#L62); specifying a value of `0` or `-1` will have the same effect of disabling memory-swap limit.

**Comment by coolljt0725** [comment]
On the master branch, if you set `--memory-swap=0`, docker will adapt it to the double size of the `--memory`  https://github.com/docker/docker/blob/master/daemon/daemon_unix.go#L109   It's better to use `--memory-swap=-1` if you want disable memory-swap

**Comment by jperville** [comment]
Would that explain why on systems with `WARNING: No swap limit support` in the docker info, the original value of `0` seems to turn into a `-1` in the HostConfig.MemorySwap ?

**Comment by runcom** [comment]
> Actual Results
> 
> The value of .HostConfig.Memory is -1

This is probably because you don't have memory cgroup enabled see https://github.com/docker/docker/blob/master/daemon/daemon_unix.go#L133

**Comment by runcom** [comment]
> Would that explain why on systems with WARNING: No swap limit support in the docker info, the original value of 0 seems to turn into a -1 in the HostConfig.MemorySwap ?

And yes, you need to have swap limit support as well. You need to have `GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"` in your grub cfg file

see https://docs.docker.com/installation/ubuntulinux/#adjust-memory-and-swap-accounting for instance

**Comment by runcom** [comment]
@jperville  I'm going to close this since this isn't a docker issue/bug but feel free to ping me if what I wrote above doesn't help you and I'll reopen this

**Comment by jperville** [comment]
No problem, this is working as intended.

And I will push for cookbook default for memory swap to be -1 instead of 0 since not all deployments have setup grub command line to enable swap accounting.
