### ISSUE TITLE
/etc/hosts not updated after a container is renamed

### ISSUE THREAD

**Issue by HoffmannP** [docker/docker#16485]
Steps to reproduce the issue:
    
    $  docker run -d --name AA -e MYSQL_ROOT_PASSWORD=test mysql:5.6
    9d30384b6a585537bdb36222d9fc31fafced9bd83de72d19195ff5d15c761a2b
    $  docker run -d --name BB -e MYSQL_ROOT_PASSWORD=test mysql:5.6
    5005e06cf8add2b2ed808773744731058ac65970171f2b3888d86e3c2dcc8ef9
    $  docker rename AA Ada
    $ docker exec BB cat /etc/hosts

Results I received:

    172.17.0.67	5005e06cf8ad
    127.0.0.1	localhost
    ::1	localhost ip6-localhost ip6-loopback
    fe00::0	ip6-localnet
    ff00::0	ip6-mcastprefix
    ff02::1	ip6-allnodes
    ff02::2	ip6-allrouters
    172.17.0.67	BB.bridge
    172.17.0.66	AA
    172.17.0.67	BB
    172.17.0.66	AA.bridge

Results I expected:

    172.17.0.67	5005e06cf8ad
    127.0.0.1	localhost
    ::1	localhost ip6-localhost ip6-loopback
    fe00::0	ip6-localnet
    ff00::0	ip6-mcastprefix
    ff02::1	ip6-allnodes
    ff02::2	ip6-allrouters
    172.17.0.67	BB.bridge
    172.17.0.66	Ada
    172.17.0.67	BB
    172.17.0.66	Ada.bridge

My system:

    $  docker -v
    Docker version 1.8.2, build 0a8c2e3

    $ docker info
    [snip]
    Library Version: 1.02.93-RHEL7 (2015-01-28)
    [snip]

hope this is sufficient

**Comment by rocknrollMarc** [comment]
I will take a look at it If I may

**Comment by cpuguy83** [comment]
Please provide the full `docker info` and `docker version` output, note that `docker -v` is different than `docker version`.
Thanks!

**Comment by HoffmannP** [comment]
docker info

    Containers: 9
    Images: 199
    Storage Driver: devicemapper
     Pool Name: docker-252:0-2831-pool
     Pool Blocksize: 65.54 kB
     Backing Filesystem: extfs
     Data file: /dev/loop0
     Metadata file: /dev/loop1
     Data Space Used: 5.604 GB
     Data Space Total: 107.4 GB
     Data Space Available: 18.5 GB
     Metadata Space Used: 10.8 MB
     Metadata Space Total: 2.147 GB
     Metadata Space Available: 2.137 GB
     Udev Sync Supported: true
     Deferred Removal Enabled: false
     Data loop file: /crypt/docker/devicemapper/devicemapper/data
     Metadata loop file: /crypt/docker/devicemapper/devicemapper/metadata
     Library Version: 1.02.93-RHEL7 (2015-01-28)
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 3.10.0-229.14.1.el7.x86_64
    Operating System: CentOS Linux 7 (Core)
    CPUs: 4
    Total Memory: 1.671 GiB
    Name: [hidden]
    ID: TPEA:DOBV:PNME:QEBC:5AR5:OQOX:FEOS:SVZI:SNNI:B6CO:ZJCS:FP52
    WARNING: bridge-nf-call-iptables is disabled
    WARNING: bridge-nf-call-ip6tables is disabled

docker version

    Client:
     Version:      1.8.2
     API version:  1.20
     Go version:   go1.4.2
     Git commit:   0a8c2e3
     Built:        Thu Sep 10 19:08:45 UTC 2015
     OS/Arch:      linux/amd64
    
    Server:
     Version:      1.8.2
     API version:  1.20
     Go version:   go1.4.2
     Git commit:   0a8c2e3
     Built:        Thu Sep 10 19:08:45 UTC 2015
     OS/Arch:      linux/amd64


BTW: There are information in `docker info` that I rather not disclose, maybe another reporting command should be established…

**Comment by cpuguy83** [comment]
I have a feeling this is related to #15727
ping @mavenugo

**Comment by thaJeztah** [comment]
ping @mavenugo ^^

**Comment by mavenugo** [comment]
@cpuguy83 @thaJeztah yes it is related to #15727 and @sanimej is working on it. we will have a fix today.

**Comment by thaJeztah** [comment]
Cool! Thanks @mavenugo

**Comment by tiborvass** [comment]
Closed by #17390
