### ISSUE TITLE
Unnecessary kernel checks Docker does

### ISSUE THREAD

**Issue by hrstoyanov** [docker/docker#16486]
https://vpsdime.com/viewticket.php?tid=166125&c=F14mAeDT

**Comment by cpuguy83** [comment]
Can you provide a specific problem?
In general kernel version checks only issue a warning.

**Comment by runcom** [comment]
and they usually doesn't strictly check for specific version but functionalities

**Comment by hrstoyanov** [comment]
Sorry for not being clear on the issue:
VPSDime, a very nice VPS provider claims that Docker makes arbitrary/unnecessary checks on the kernel, which prevents OpenVZ, their virtualization platform to run Docker containers, and therefore they do not allow their clients to do so.

**Comment by cpuguy83** [comment]
Here's the kernel checking code: https://github.com/docker/docker/blob/master/daemon/daemon_unix.go#L75-L90

Docker does not bail out when the kernel version is not new enough, only warns.
Closing, but if we can find a specific case where this is an issue, please ping here.

Also note, the minimum "supported" kernel is 3.10, not 3.16 as is suggested on the ticket.

Thanks!
