### ISSUE TITLE
Docker 1.8.2 : Windows platform

### ISSUE THREAD

**Issue by tma0si3** [docker/docker#16483]
Hello ,
I got the very latest version of docker tookbox installed on my Windows OS.
I have set-up the right proxy as I am behind the corporate firewall.
But , when i run a simple command , I see message "Layer already being pulled by another client. Waiting" . Nothing progresses.

Many other users have also reported the same on stackoverflow. 
http://stackoverflow.com/questions/32183390/error-on-docker-pull-layer-already-being-pulled-by-another-client

Kindly , provide the resolution for the same .

**Comment by phemmer** [comment]
I'd take a peek at these search results: https://github.com/docker/docker/issues?q=is%3Aissue+%22Layer+already+being+pulled+by+another+client%22+is%3Aopen

This is unfortunately a rather common issue lately, and seems to have gotten more prevalent after 1.7 (in my own experience).

#12823 seems to be the main issue where this is tracked.

**Comment by cpuguy83** [comment]
Closing since this is a dup of the aforementioned issues.
I believe most of these issues are fixed on master, but without wide-spread usage it is difficult to tell.
