### ISSUE TITLE
Machine IP could not be fetched. Please retry the setup

### ISSUE THREAD

**Issue by acidhax** [docker/docker#16489]
Using Kitematic, I get this error:
Machine IP could not be fetched. Please retry the setup.

If I Delete VM and Retry:

/Applications/Docker/Kitematic (Beta).app/Contents/Resources/resources/docker-machine -D create -d virtualbox --virtualbox-memory 2048 default returned non zero exit code. Stderr: Converting from raw image file="stdin" to file="/Users/<redacted>/.docker/machine/machines/default/disk.vmdk"... Creating dynamic image with size 20971520000 bytes (20000MB)... Error creating machine: exit status 1 You will want to check the provider to make sure the machine and associated resources were properly removed.

**Comment by acidhax** [comment]
Mac OSX 10.10.5

tpms-mac-pro-20:resources mat$ docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      darwin/amd64

**Comment by cpuguy83** [comment]
Moved to kitematic/kitematic#1055
