### ISSUE TITLE
How can i get the local image digest?

### ISSUE THREAD

**Issue by ruijf** [docker/docker#16482]
I want use registry 2.0 api to push image ,and the api need the digest param.  so I use "docker images --digests" command to query image's digest, but i got this output:
```shell
REPOSITORY                                        TAG                 DIGEST              IMAGE ID            CREATED             VIRTUAL SIZE
localhost:81/admin/demo2                          1.0                 <none>              235bf8296091        5 hours ago         395.4 MB
admin/demo2                                       1.0                 <none>              235bf8296091        5 hours ago         395.4 MB
localhost:81/admin/demo1                          1.2                 <none>              0bfc9986f077        6 hours ago         395.4 MB
admin/demo1                                       1.2                 <none>              0bfc9986f077        6 hours ago         395.4 MB 
```
The DIGEST are all none. 
Then how can i use the docker registry2.0 api to push image?

**Comment by xiaods** [comment]
firstly, please input 
docker version:
docker info:
uname -a:

**Comment by ruijf** [comment]
```shell
[root@bogon nginx]# docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64
[root@bogon nginx]# docker info
Containers: 1
Images: 157
Storage Driver: devicemapper
 Pool Name: docker-253:1-1714158-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 5.509 GB
 Data Space Total: 107.4 GB
 Data Space Available: 11.2 GB
 Metadata Space Used: 7.795 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.14 GB
 Udev Sync Supported: false
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.4-301.fc22.x86_64
Operating System: Fedora 22 (Twenty Two)
CPUs: 4
Total Memory: 7.698 GiB
Name: bogon
ID: WKUS:6WOZ:WR72:KUBE:DG35:7RNU:VVGU:4XDG:UO22:PTLK:7A5B:XHQO
[root@bogon nginx]# uname -a
Linux bogon 4.0.4-301.fc22.x86_64 #1 SMP Thu May 21 13:10:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by davidxia** [comment]
@ruijf Images are only assigned digests once pushed to a registry. https://groups.google.com/forum/#!topic/docker-user/PvAcxDrvP30

**Comment by davidxia** [comment]
I should clarify that the digest referred to here is a digest of the image's manifest which can change depending on what you tag it and the manifest version used. For the longest time, I didn't understand why contents of an image could be hashed differently. But the digest here isn't the hash of the image contents. It's of the image manifest. See more in that google groups discussion and here. https://github.com/docker/distribution/issues/1662

**Comment by bademux** [comment]
@davidxia, it not entirely true. [Jib](https://github.com/GoogleContainerTools/jib) create imageDigest BEFORE push, see  jib-image.json

**Comment by thaJeztah** [comment]
I'm not very familiar with Jib, but one of the reasons it's not available "before push" is that the digest is calculated over the image manifest, which references the _compressed_ image layers; those compressed layers are not available on disk in docker's local image store, and are constructed during `docker push`. Containerd fixes this (to some extend) by storing _both_ uncompressed and compressed versions of image layers, but this comes at a cost of using more space on disk to keep both.

**Comment by bademux** [comment]
@thaJeztah more info is here [#3394](https://github.com/docker/cli/issues/3394)
sorry for spaming
