### ISSUE TITLE
Accessing /proc/self/pagemap encounters Operation not permitted

### ISSUE THREAD

**Issue by tanjianfeng** [docker/docker#16506]
From OS's side, for /proc/<pidof docker app>/pagemap, owner is the user starting this app, permission is -r--------. And user in Docker app is another user, who cannot read this file. So what can we do to read it inside Docker app?

**Comment by cpuguy83** [comment]
This requires the CAP_SYS_ADMIN capability.
`docker run --cap-add SYS_ADMIN ...`
Note that this disables a significant amount of the container security and should be used with caution.

Closing.
