### ISSUE TITLE
[Proposal] secure image reposirory

### ISSUE THREAD

**Issue by hrstoyanov** [docker/docker#16510]
I was reading about Docker private repository, and the need for certificates, TLS, etc. Has anyone thought about this much more elegant protocol, SRP:

https://en.m.wikipedia.org/wiki/Secure_Remote_Password_protocol

**Comment by thaJeztah** [comment]
ping @dmcgowan @endophage perhaps you could have a quick look

**Comment by LK4D4** [comment]
Closing as nobody interested :(
