### ISSUE TITLE
Docker 1.8.2 won't push images with filenames in iso-8859-1 encoding to registry (v1 or v2 doesn't matter): no such file or directory

### ISSUE THREAD

**Issue by kwk** [docker/docker#16516]
# Problem description

We build our own images and found that there's an issue when we push these images to our v2 registry. I've made a simple example without the crap that we do, so everybody should be able to reproduce the problem quite easily.

The problem has something to do with filename encoding, I guess, and it is not related to the v2 registry because v1 produces the same error.

**We have a build machine that still runs docker 1.6 and the problem doesn't exist there. Therefore I think the issue has something to do with changes to docker itself between 1.6 and 1.8.**

# Expected results

We expect docker to allow pushing images that contain files with any encoding just like it used to (e.g. with docker 1.6).

# Actual results

Push doesn't work and fails with this message:

```
/var/lib/docker/aufs/mnt/518537cd7343665f034d008b7b48098ebdf3462b80536897dd3a6515ea7f6d58/data/file-with-german-umlaut-ae-�: no such file or directory
```

# Steps to reproduce the problem

We first start a v1 and a v2 registry on localhost running on port `5001` and `5002` respectively. To these registry we're going to push our test image later:

```
$ docker run -d -p 5001:5000 --name registry1 registry:0.9.1
$ docker run -d -p 5002:5000 --name registry2 registry:2
```

We then create a directory for all of our files. All we want is a simple debian:jessie image with a file inside that has an `iso-8859-1` encoding. We're creating this file (`file-with-german-umlaut-ae-ä`)  below with the `iconv` command and add it to the `/data` directory in our image. Then we build the image and tag it so we can push it to our v1 and v2 registry.

```
$ mkdir -p bug-with-filename-encoding/data
$ cd bug-with-filename-encoding
$ echo -e "FROM debian:jessie\nADD data /data" > Dockerfile
$ echo "arbitrary data" > data/file-with-german-umlaut-ae-$(echo ä | iconv -t iso-8859-1)
$ docker build -t bug .
$ docker tag bug localhost:5001/kkleine/bug
$ docker tag bug localhost:5002/kkleine/bug
```

Notice that the error looks almost identical no matter if we push to docker v1 or v2 registry:

**Pushing to v1 registry** 

```
The push refers to a repository [localhost:5001/kkleine/bug] (len: 1)
Sending image list
Pushing repository localhost:5001/kkleine/bug (1 tags)
843e2bded498: Image successfully pushed 
8c00acfb0175: Image successfully pushed 
518537cd7343: Buffering to disk 2.048 kB
Failed to generate layer archive: open /var/lib/docker/aufs/mnt/518537cd7343665f034d008b7b48098ebdf3462b80536897dd3a6515ea7f6d58/data/file-with-german-umlaut-ae-�: no such file or directory
```

Due to the string "Failed to generate layer archive", the file and line causing this message was  easily spotted: https://github.com/docker/docker/blob/master/graph/push_v1.go#L277 :

```go
	layerData, err := p.graph.TempLayerArchive(imgID, p.sf, p.out)
	if err != nil {
		return "", fmt.Errorf("Failed to generate layer archive: %s", err)
	}
```

**Pushing to v2 registry**

```
$ docker push localhost:5002/kkleine/bug
The push refers to a repository [localhost:5002/kkleine/bug] (len: 1)
518537cd7343: Buffering to Disk 
open /var/lib/docker/aufs/mnt/518537cd7343665f034d008b7b48098ebdf3462b80536897dd3a6515ea7f6d58/data/file-with-german-umlaut-ae-�: no such file or directory
```

# System information

Here are my system information:

## Linux distribution
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
```

## Kernel

```
$ uname -a
Linux kkleinework 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

## Docker version

```
$ sudo docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64
```

## Docker info

```
$ sudo docker info
Containers: 1
Images: 35
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 37
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 8
Total Memory: 15.63 GiB
Name: kkleinework
ID: A5PC:FL5L:UJM6:4P7S:KXTW:B3PT:74OK:M3OL:DOJD:DDGH:DQK3:6FLY
WARNING: No swap limit support
```

**Comment by stonemaster** [comment]
+1 Having the same problem

**Comment by cpuguy83** [comment]
ping @vbatts 
Some issue with tar-split, maybe?

**Comment by kwk** [comment]
Just a side note: A colleague tested out multiple version of Docker on his OpenSuse machine and the issue didn't exists with Docker version 1.7.1, build 786b29d whereas Docker 1.8.1 also has the same problem as I have only on his machine.

**Comment by vbatts** [comment]
oh cute...
@cpuguy83 it is indeed triggered by the addition of tar-split, but the root issue is actually that golang's `string` + `encoding/json.Marshal` only support utf-8. Per the docs, whenever an invalid utf-8 get's marshalled, there is no warning or error, but the invalid characters are replaced U+FFFD (https://golang.org/pkg/encoding/json/#InvalidUTF8Error).
So with this example, when the layer is built and committed, the tar data preserved is
```json
{"type":1,"name":"data/file-with-german-umlaut-ae-\ufffd","size":15,"payload":"045asuUM8Hs=","position":3}
```

**Comment by vbatts** [comment]
as a side note, while this may have worked before, the fact that you're file on disk is seen with `�` in the name means your fs and local may not be handling the character correctly either. That character is the unicode for `0xFFFD` and see as character unknown.
`/var/lib/docker/aufs/mnt/518537cd7343665f034d008b7b48098ebdf3462b80536897dd3a6515ea7f6d58/data/file-with-german-umlaut-ae-�: no such file or directory`


Example, with this simple golang app to see the raw bytes (`seebytes.go`):
```golang
package main

import (
        "bufio"
        "fmt"
        "io"
        "log"
        "os"
)

func main() {
        buf := bufio.NewReader(os.Stdin)
        for {
                b, err := buf.ReadByte()
                if err != nil {
                        if err != io.EOF {
                                log.Fatal(err)
                        }
                        break
                }
                fmt.Printf("0x%X\n", int(b))
        }
}
```

running the following, you'll see the filename is not the same bytes as the output as `iconv` is providing:
```bash
$ go build seebytes.go
$ echo file-ä | iconv -t iso-8859-1 | ./seebytes 
0x66
0x69
0x6C
0x65
0x2D
0xE4
0xA
$ touch file-$(echo ä | iconv -t iso-8859-1)
$ ls file-* | ./seebytes 
0x66
0x69
0x6C
0x65
0x2D
0x5C
0x33
0x34
0x34
0xA
```

`0xE4` != `0x5C 0x33 0x34 0x34`

Just food for another though.

**Comment by vbatts** [comment]
https://github.com/vbatts/tar-split/pull/18#issuecomment-142708647 shows my fix works for your use case. And I've opened https://github.com/docker/docker/pull/16531 which includes this fix.

**Comment by kwk** [comment]
@vbatts 

Just a thought: this would have been much simpler than writing a go program: `$ echo file-ä | iconv -t iso-8859-1 | hexdump -C`

**Comment by vbatts** [comment]
@kwk the example was showing how the string changes as it processes through the golang logic, like it does in docker.

**Comment by vbatts** [comment]
i've misspoken. I should work on one thing at a time. ;-)

**Comment by kwk** [comment]
Thank you all for fixing this bug! Can't wait to get my hands on an appropriate docker version.
