### ISSUE TITLE
docker push error "Failed to generate layer archive: Unknown device ..."

### ISSUE THREAD

**Issue by bcroq** [docker/docker#16524]
`docker version`:
```
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.5.1
 Git commit:   0a8c2e3-dirty
 Built:        Mon Sep 14 12:09:36 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.5.1
 Git commit:   0a8c2e3-dirty
 Built:        Mon Sep 14 12:09:36 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:
```
Containers: 16
Images: 146
Storage Driver: devicemapper
 Pool Name: docker-8:2-3189280-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 21.47 GB
 Data Space Total: 107.4 GB
 Data Space Available: 13.54 GB
 Metadata Space Used: 16.64 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.131 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.102 (2015-07-07)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.6-1-ARCH
Operating System: Arch Linux (containerized)
```
`uname -a` : `Linux arch64-2013-3 4.1.6-1-ARCH #1 SMP PREEMPT Mon Aug 17 08:52:28 CEST 2015 x86_64 GNU/Linux`

Steps to reproduce the issue: 
- `docker push docker-registry.localnet/name:0`

Results received:
```
The push refers to a repository [docker-registry.localnet/name] (len: 1)
Sending image list
Pushing repository docker-registry.localnet/name (1 tags)
e7a4463ba4d8: Buffering to disk 
Failed to generate layer archive: Unknown device e7a4463ba4d839b91fe34e932f9c78d5f17b2956541016a300ed944c9629026b
```

Expected results: the image is pushed to the registry.

Additional info: same results with an image create with `docker commit my-container docker-registry.localnet/name:0` or with `docker tag debian:6 docker-registry.localnet/name:0`.

**Comment by bcroq** [comment]
After restarting the compter, I was able to push the image.

**Comment by thaJeztah** [comment]
Some questions;

- Are you able to reproduce with an official build? (`0a8c2e3-dirty` indicates that it's not an official build)
- Are you having the same issues with pushing to Docker Hub?
- It looks like you're running docker-in-docker; `Arch Linux (containerized)`, which can cause issues if you're now using the right setup http://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/

**Comment by bcroq** [comment]
1) no, it happened once and never happened again anywhere
2) no
3) my workstation is not containerized, it is a "true" Arch Linux system; I don't use docker-in-docker on my workstation.
