### ISSUE TITLE
LABEL com.example.version.is-beta

### ISSUE THREAD

**Issue by progtologist** [docker/docker#16526]
__docker version:__
```
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64
```
__docker info:__
```
Containers: 408
Images: 121
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 937
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-49-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 8
Total Memory: 11.73 GiB
Name: mobile-lab
ID: MNKA:XEBM:UGJ7:HGT4:MN5L:WMCP:ZYIL:7FZZ:K4S2:6Q7I:3K7S:XCTG
WARNING: No swap limit support
```
__uname -a:__
```
Linux mobile-lab 3.16.0-49-generic #65~14.04.1-Ubuntu SMP Wed Sep 9 10:03:23 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
__Steps to reproduce:__
1. Create a basic dockerfile with only one LABEL layer
```
FROM ubuntu
LABEL com.example.version.is-beta
```
2. Try to build this container

__Results received:__
```
Error response from daemon: Syntax error - can't find = in "com.example.version.is-beta". Must be of the form: name=value
```
__Expected results:__
The container is built correctly.

__Additional info:__
In the official [userguide](https://docs.docker.com/userguide/labels-custom-metadata/), it is mentioned that "The LABEL instruction adds a label to your image, optionally setting its value. ". There are examples in the same context, showing this functionality.

However that is not the case in the actual program, as shown in [line_parsers.go](https://github.com/docker/docker/blob/1ffff4c8e2b208664b6f63ea6cd3c4c3dace3cc9/builder/parser/line_parsers.go#L166)

**Comment by tiborvass** [comment]
Not sure if this is a code bug, or a documentation bug.

**Comment by crosbymichael** [comment]
I would say docs bug, I think a value is required.

**Comment by cpuguy83** [comment]
--label accepts a string with no value.

**Comment by thaJeztah** [comment]
IIRC, the intent was to be able to add a label without value (which would default to an empty string). If the code doesn't support that, sounds like a bug to me.

/cc @ibuildthecloud to confirm if this was indeed the intent.

**Comment by runcom** [comment]
This sounds weird because I get:
```
$ docker build -t labelbug - <<EOF
heredoc> FROM ubuntu
heredoc> LABEL com.example.version.is-beta
heredoc> EOF
Sending build context to Docker daemon 2.048 kB
Error response from daemon: LABEL must have two arguments
```
Which it's hitting https://github.com/docker/docker/blob/1ffff4c8e2b208664b6f63ea6cd3c4c3dace3cc9/builder/parser/line_parsers.go#L156 because LABEL w/o value is evaluated at this check https://github.com/docker/docker/blob/1ffff4c8e2b208664b6f63ea6cd3c4c3dace3cc9/builder/parser/line_parsers.go#L150

So, is your repro example wrong somewhere? I also think it's a code bug though because doc says it's optional to set a value
