### ISSUE TITLE
Proposal: context file describing the container info

### ISSUE THREAD

**Issue by Yonisha** [docker/docker#16527]
When application is running within a container, there's no easy way to understand whether the application is Dockerized or not. Moreover, when querying the host name (for example, in Java: InetAddress.getLocalHost().getHostName()) the host name is represented by an integer, which is meaningless.

It will be very useful, especially for monitoring & diagnostics purposes, to be able to easily fetch (local file injected to the container fs on startup?) the container info, such as real host name, image name, container name and container ID.

**Comment by phemmer** [comment]
There are several proposals for this type of thing. See https://github.com/docker/docker/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+introspection

**Comment by cpuguy83** [comment]
Thanks closing as this is a dup.
