### ISSUE TITLE
LXC OOM tests failures

### ISSUE THREAD

**Issue by runcom** [docker/docker#16520]
`TestEventsOOMDisableFalse`
`TestEventsOOMDisableTrue`
`TestRunOOMExitCode`

these tests are currently failing on master in lxc while they didn't before (`TestRunOOMExitCode` this was the only present)

```
WARN[0006] Your kernel does not support OOM notifications: open /sys/fs/cgroup/memory/docker/29a4e198e2a4947e4360649d82652c602d279b307fdcdd02e98e9c85dce89b10/lxc/f21811f84a2c0738e8fdb8c202fff0410a0c17c673e09a5ca9ec6ed69123061f/memory.oom_control: no such file or directory
```

this is a log from docker with lxc running in docker (native). That cgroup path and file exists though so don't know what's wrong here

**Comment by HuKeping** [comment]
Relate with https://github.com/docker/docker/pull/16235?

**Comment by runcom** [comment]
@HuKeping I don't think so, reverting that doesn't help but maybe I'm doing something wrong, I'll find a good commit and bisect from there

**Comment by runcom** [comment]
Even going back to a working commit like 1.8.2 tag doesn't work:
```
+ go test -check.f DockerSuite.TestRunOOMExitCode* -test.timeout=60m -check.v github.com/docker/docker/integration-cli

----------------------------------------------------------------------
FAIL: docker_cli_run_unix_test.go:286: DockerSuite.TestRunOOMExitCode

docker_cli_run_unix_test.go:299:
    c.Assert(err, check.IsNil)
... value *errors.errorString = &errors.errorString{s:"wrong exit code for OOM container: expected 137, got 0 (output: \"\")"} ("wrong exit code for OOM container: expected 137, got 0 (output: \"\")")

OOPS: 0 passed, 1 FAILED
--- FAIL: Test (0.44s)
FAIL
```
