### ISSUE TITLE
provide progress indicator for docker cp

### ISSUE THREAD

**Issue by ErikGrimes** [docker/docker#16532]
Currently there's no feedback on copy progress, so you're not sure when a copy will complete.  Feedback could be something like that provided by docker pull or the command line utility scp.

**Comment by gittycat** [comment]
I agree. This is currently my main shortcoming of using `docker cp` versus ssh directly. I'd prefer using `docker cp` since my current setup doesn't rely on the host for storage or environment variables (dumb host).

**Comment by thaJeztah** [comment]
Sorry, @ErikGrimes, but I'm closing this. There were quite some concerns about adding this on the pull request (see https://github.com/docker/docker/pull/17014#issuecomment-166982627).

Thanks for suggesting!
