### ISSUE TITLE
Docker not initiating / installing in windows?

### ISSUE THREAD

**Issue by bboysathish** [docker/docker#16549]
Hi

i am getting the below error, after installing docker and started using docker quick start terminal.

![docker-error](https://cloud.githubusercontent.com/assets/8023447/10074980/f23347f8-62f0-11e5-8081-653abfed61d1.PNG)

System Configuration:
DockerToolbox-1.8.2a
Windows : 8.1
git version 1.9.5.msysgit.1
VirtualBox - 5.0.4

**Comment by calavera** [comment]
@bboysathish it looks like this issue is related with the Toolbox. You can find the repo in https://github.com/docker/toolbox.

Do you mind reopening the issue there? you'll get the right :eyes: on it.

I'm going to close this issue since it doesn't belong to this repo.

Thank you!
