### ISSUE TITLE
ssh: docker run --rm

### ISSUE THREAD

**Issue by fentas** [docker/docker#16546]
Hey there, following situation:
I connect to a remote host via ssh. I run e.g. `docker run --rm -it ubuntu:14.04 bash`. Now the ssh connection closed unexpectedly. I would expect that the docker container removed itself but it is still running.
Is there a way to **bind** the container to the ssh session/connection?
Or is there any way to handle this differently?

**Comment by fentas** [comment]
**docker version:** Docker version 1.8.2, build 0a8c2e3
**docker info:**
Containers: 11
Images: 166
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 188
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-28-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 3.614 GiB
Name: default-houston-cmj9
ID: MATJ:BSIR:MM7T:XANC:MAUD:7Y2K:QYTS:XCKD:WX36:OMRA:AIKO:3IWM
WARNING: No swap limit support
**uname -a:** Linux default-houston-cmj9 3.19.0-28-generic #30~14.04.1-Ubuntu SMP Tue Sep 1 09:32:55 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by fentas** [comment]
After some digging around the best which I came up with to solve this temporally is that I execute the following bash script before I start a specific docker container.
```bash
nohup bash -c "while who | awk '{print \$2}' | grep -q $(echo ${SSH_TTY} | awk -F'/' '{print $NF}'); do sleep 1; done; docker rm -f $DOCKER_NAME" &
```

But I would love to see something more reliable from docker.

**Comment by cpuguy83** [comment]
No, this is not possible.
Think of the container as just a process that docker starts for you. It is not tied to the user that started it in any way.
