### ISSUE TITLE
Problem after reboot: policy restart=always with icc=false and linked containers

### ISSUE THREAD

**Issue by mikechris** [docker/docker#16548]
Steps to reproduce:
Run docker with --icc=false 
Run docker-compose up  (with linked containers and restart=always policy)
Reboot OS couple times (min. 2)

Problem:
After first (most time second) reboot/shutdown and boot most of containers that use links are down. 
Simply starting docker-compose up and every container is up again.

Other info:
When icc=true and with links between containers everything is fine.
When icc=false and without links between containers everything is fine too.

debug_log:
ESC[31mERROESC[0m[0002] leaving endpoint failed: a container has already joined the endpoint
ESC[31mERROESC[0m[0002] leaving endpoint failed: a container has already joined the endpoint
ESC[31mERROESC[0m[0002] leaving endpoint failed: a container has already joined the endpoint
ESC[31mERROESC[0m[0002] leaving endpoint failed: a container has already joined the endpoint
ESC[31mERROESC[0m[0002] leaving endpoint failed: a container has already joined the endpoint
ESC[31mERROESC[0m[0002] leaving endpoint failed: a container has already joined the endpoint
[...]
ESC[34mINFOESC[0m[0006] Loading containers: done.\

VirtualMachine Parallels
Tested on Docker version: 1.7.1, 1.8.1 and most recent 1.9-dev
Linux 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Containers: 39
Images: 410
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 488
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 2
Total Memory: 3.856 GiB
Name: XXX
ID: K4VD:3MVL:654M:XT2I:XSZU:M5PE:Y2NR:A5OO:RYGI:6SN7:PLCN:SDER
WARNING: No swap limit support

**Comment by mikechris** [comment]
Issue updated

**Comment by cpuguy83** [comment]
ping @mavenugo

**Comment by mavenugo** [comment]
@mikechris this must be resolved now by #16910. can you please confirm ?

**Comment by cpuguy83** [comment]
ping @mikechris

**Comment by calavera** [comment]
I'm going to close this issue as fixed. @mikechris, please feel free to open a new issue if the problem persists.
