### ISSUE TITLE
Suggestion: Instructions should point to an alternative to "curl | sh" method of installation

### ISSUE THREAD

**Issue by csirac2** [docker/docker#16543]
You know, all this wonderful effort goes into creating nice signed distro packaging, and yet I have to study some random shell scripts or dig through 3rd-party blogs just to find the information I needed to configure our whitelists appropriately and get docker running without having to run some unsigned script piped into my shell over https :-)

I'm talking about the instructions at:

* https://docs.docker.com/installation/debian/ (gives a sources.list line example, but it's for debian's repo which is stuck on 1.7)
* https://docs.docker.com/installation/ubuntulinux/ (for the words that are dedicated to installing and using curl, it seems we could just as easily have explained how to add a sources.list and apt-key one-liner :-)

Over the past 12 months, it seems my whitelists have contained:
* get.docker.io
* get.docker.com
* apt.dockerproject.org

Each time this changes, it seems weird there's no canonical place which points to where the current official packages are being published to.

But perhaps it's just me that's weird...

**Comment by csirac2** [comment]
I'm not sure that this bug report fits the required template...

**Comment by vdemeester** [comment]
@csirac2 I think this would be handled when #16593 will be taken care of, don't you think ? 

*So I'm tempted to close one of it as it's duplicate*.

**Comment by vdemeester** [comment]
And the PR that should fix it is there : #16662 :wink:

**Comment by moxiegirl** [comment]
@vdemeester I standardized as rpm/yum being the way to go.  Curl is the if you must version.  This once can get closed.

**Comment by csirac2** [comment]
This can be closed, neither #16593 nore #16662 didn't exist when I created this. Thanks!

**Comment by vdemeester** [comment]
Cool :wink:

**Comment by moxiegirl** [comment]
@csirac2 Thank you for contributing the issue...really appreciate that.
