### ISSUE TITLE
`docker cp` can't follow symbol link

### ISSUE THREAD

**Issue by WeiZhang555** [docker/docker#16555]
When I tried to copy a symbol link into a docker container, I found that the `docker cp` can't follow the symbol link and only copied an invalid symbol file. e.g.

```
$ echo "hello world" > /tmp/test
$ cat /tmp/test
hello world
$ ln -s /tmp/test /tmp/test.ln
$ ls -l /tmp/test.ln
lrwxrwxrwx 1 darcy darcy 9  9月 25 00:05 /tmp/test.ln -> /tmp/test
$ docker run -tid ubuntu bash
f597b1a3b93a535818a4f7ac14d49b20331ff79fba29b6482e1f752d9832ce38
$ docker cp /tmp/test.ln f597b1a3b93a:/
$ docker exec -ti f597b1a3b93a ls -l /test.ln
lrwxrwxrwx 1 root root 9 Sep 24 16:05 /test.ln -> /tmp/test
$ docker exec -ti f597b1a3b93a cat /test.ln
cat: /test.ln: No such file or directory
```
It's obvious that the symbol link is invalid, `docker cp` file from container to host is in exactly same situation.

IMO the most reasonable behavior is that `docker cp` should follow the symbol link and copy content of `/tmp/test` on host to file `/test.ln` in container, just as what the `cp` command will do.

What's your opinion? I can push a PR to fix this, but I want to make sure this fix is acceptable to you firstly. :)

**Comment by WeiZhang555** [comment]
And #dibs  in advance

**Comment by zopyx** [comment]
again the trailing slash problem at the end of directory names....what a stupid behavior

**Comment by jlhawn** [comment]
@WeiZhang555, you are making the assumption that `docker cp` behaves like `cp` but it is documented to behave like `cp -a` which *does not* follow symbolic links.

@calavera I think the best solution to this problem would be to support more options in `docker cp` and only have the `cp -a` behavior if you specify `docker cp -a`. We could also have a `docker cp -r` (recursive option) for copying directories. This would add many more cases to handle and test however.

**Comment by WeiZhang555** [comment]
@jlhawn add more options is a good choice, this is also first thought in my head.
I can handle options `-a` and `-r` as you said and test cases things.
What do you think?

**Comment by WeiZhang555** [comment]
After some comparation of unix `cp` and `scp`, I think a `docker cp` should be more similar to `scp` than `cp`. Copying data between a host and a container is more like between two different hosts, not just from logical view but also from security view. And a `scp` always follow the symbol link instead of the symbol link itself.
So the question is: Do we really need a `-a` option?

**Comment by aespinosa** [comment]
Reiterating my comment in #16896.

Prior to 1.8.0 symlinks were followed when copying. I think the flag should be to disable following symlinks instead to get pre-1.8.0 behavior.

But then the documentation (1.8.2) says it's `cp -a` behavior. So i'll leave it to the maintainers to decide on that decision in terms of interface. Note that `cp -a` is not mentioned in documentation prior to 1.8.0 (https://github.com/docker/docker/blob/v1.7.0/docs/reference/commandline/cli.md)
