### ISSUE TITLE
ecoding dwarf section info at offset 0x4

### ISSUE THREAD

**Issue by fedya** [docker/docker#16553]
Hello.
I'm trying to build a docker binary without docker package and i got

[omv@localhost docker-1.8.2]$ DEBUG=1 CXX=g++ CC=gcc AUTO_GOPATH=1  ./hack/make.sh dynbinary
WARNING! I don't seem to be running in the Docker container.
The result of this command might be an incorrect build, and will not be
officially supported.
Try this instead: make all

bundles/1.8.2 already exists. Removing.

---> Making bundle: dynbinary (in bundles/1.8.2/dynbinary)
github.com/opencontainers/runc/libcontainer/system
cannot load DWARF output from $WORK/github.com/opencontainers/runc/libcontainer/system/_obj//_cgo_.o: decoding dwarf section info at offset 0x4: unsupported version 0
github.com/docker/docker/pkg/term
cannot load DWARF output from $WORK/github.com/docker/docker/pkg/term/_obj//_cgo_.o: decoding dwarf section info at offset 0x4: unsupported version 0

uname -a: 
Linux localhost.localdomain 4.1.3-nrjQL-desktop-3omv #1 SMP PREEMPT Sat Aug 1 10:23:00 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
docker version: 1.8.2

**Comment by fedya** [comment]
CC=gcc go build -o bundles/1.8.2/dynbinary/dockerinit-1.8.2 -a -tags 'netgo static_build  daemon' -installsuffix netgo -ldflags ' -w  -linkmode external -extldflags "-static"' ./dockerinit
# github.com/opencontainers/runc/libcontainer/system
cannot load DWARF output from $WORK/github.com/opencontainers/runc/libcontainer/system/_obj//_cgo_.o: decoding dwarf section info at offset 0x4: unsupported version 0
# github.com/docker/docker/pkg/term
cannot load DWARF output from $WORK/github.com/docker/docker/pkg/term/_obj//_cgo_.o: decoding dwarf section info at offset 0x4: unsupported version 0

**Comment by cpuguy83** [comment]
Can you try against master? I think I saw someone on IRC have the same issue with 1.8 but master is ok.

**Comment by fedya** [comment]
Affected only gcc 5.2.0 from Linaro.

**Comment by cpuguy83** [comment]
So sounds like it's not a docker issue?

**Comment by fedya** [comment]
So, true.
