### ISSUE TITLE
Docker machine start.sh not using the VirtualBox's preferences default machine folder setting to create machine

### ISSUE THREAD

**Issue by kenhuang** [docker/docker#16568]
Hi, I just upgraded my docker tool to the latest version(1.8.2a for windows), after I create my "default" docker machine, I notice it was not using the VirtualBox's preferences default machine folder setting, My C drive have limited disk space, so I setup VirtualBox use the machine folder in D drive.

Is there any way I can create docker machine in different location manually as work around?

Thanks for your help in advance!

Regards
Ken

**Comment by cpuguy83** [comment]
Hello, I moved this to docker/machine#1928
