### ISSUE TITLE
Docker, npm install local packages: node_modules not visible to container

### ISSUE THREAD

**Issue by lucaspottersky** [docker/docker#16565]
What is the recommended way to work with Docker and node.js?

I'm trying to setup an Ember.js App with Docker, but it complains about `node_modules` folder being empty, even though `npm install` runs succesfully in the build phase. When I run the container with a volume to share my host source folder, the container does not see the `node_modules` folder that was once built into the image.

I'm basically facing the same issue as: http://stackoverflow.com/questions/30043872/docker-compose-node-modules-not-present-in-a-volume-after-npm-install-succeeds

**Comment by cpuguy83** [comment]
Hello,

I'd be happy to help, but this isn't quite the right forum to do so.
Please see the docker-user mailing list, or ping me on IRC @ #docker 

Thanks!
