### ISSUE TITLE
Exit status 1 on `service docker restart`, debian 7.8 sysvinit (/etc/init.d/docker)

### ISSUE THREAD

**Issue by xmik** [docker/docker#16560]
### Description of problem:
When I run `sudo service docker restart`: docker daemon is being stopped and immediately after then docker daemon is being started. When docker daemon is running and >=1 container is running, it takes some time (I assume [up to 10 seconds](https://docs.docker.com/reference/commandline/stop/)) to stop the running containers. With current `/etc/init.d/docker` file, `start` happens immediatelly after `stop`, docker daemon is still running and thus **exit status is 1** (`start` has nothing to do). 

According to [start-stop-daemon](http://manpages.ubuntu.com/manpages/raring/man8/start-stop-daemon.8.html): exit status 
```
1      If --oknodo was not specified and nothing was done.
```

### Solution
Replace [this line](https://github.com/docker/docker/blob/master/contrib/init/sysvinit-debian/docker#L120) with:
```
start-stop-daemon --stop --pidfile "$DOCKER_SSD_PIDFILE" --retry 10
```

### Environment
Debian 7.8, virtual machine.
```
$ docker --version
Docker version 1.8.2, build 0a8c2e3
```
```
$ sudo docker info
Containers: 2
Images: 22
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 26
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-0.bpo.4-amd64
Operating System: Debian GNU/Linux 7 (wheezy)
CPUs: 1
Total Memory: 1000 MiB
Name: kt-ai-docker-debian
ID: P466:YJIC:UQHQ:NZT5:TC2V:CAL3:4FOO:WPS4:LV55:2IQQ:6GXN:ZJPB
WARNING: No memory limit support
WARNING: No swap limit support
```
```
$ uname -a
Linux kt-ai-docker-debian 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3~bpo70+1 (2015-08-08) x86_64 GNU/Linux
```

```
$ cat /etc/debian_version 
7.8
```

### How reproducible:
Steps to Reproduce:
1. Start Docker daemon
2. Start some long running container, e.g. `sudo docker run -dti debian:7.8 /bin/bash`
3. Run `sudo service docker restart`:

Actual Results:
```
debian@kt-ai-docker-debian:~$ sudo docker run -dti debian:7.8 /bin/bash
WARNING: Your kernel does not support memory swappiness capabilities, memory swappiness discarded.
34eb318b500fcf55dcfdd3c9804c1f9fc3892e4f238e1a5cf70a707435b3d95d
debian@kt-ai-docker-debian:~$ sudo service docker restart
[ ok ] Stopping Docker: docker.
[....] Starting Docker: dockerdebian@kt-ai-docker-debian:~$ echo $?
1
```

Expected Results:
Exit status 0 after `sudo service docker restart`

**Comment by xmik** [comment]
Reproduced also with long running container started from image `busybox:latest` (run command: `$ sudo docker run -dti busybox /bin/sh`)

**Comment by thaJeztah** [comment]
I think this can be closed now that https://github.com/docker/docker/pull/16561 is merged
