### ISSUE TITLE
Revise mounting volume note for clarity

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#16566]
http://docs.docker.com/userguide/dockervolumes/

![image](https://cloud.githubusercontent.com/assets/1347209/10088246/5953c598-62ce-11e5-94cb-5c58a4ff9df7.png)

**Comment by marcusstenbeck** [comment]
@moxiegirl Looks like this has already been rewritten: https://github.com/docker/docker/blob/master/docs/userguide/dockervolumes.md#mount-a-host-directory-as-a-data-volume

**Comment by moxiegirl** [comment]
Nice...now we just need it live. Thanks for the check!
