### ISSUE TITLE
[Proposal] a new way to handle none https registry

### ISSUE THREAD

**Issue by feiyang21687** [docker/docker#16578]
# Problem

In private cluster, we run docker registry in none https way, and may multiple registries. But docker must set daemon parameter ```--insecure-registry```. This is not easy to use. For example, some team builds a docker cluster, they must modify docker daemon parameter and restart hole cluster in order to use a new none https registry.

# Proposal Request

We prefer to add docker cli to support this. like this:

```
docker registry add --insecure-registry registry.xxx.xxx.com
```

**Comment by azurezk** [comment]
#dibs

**Comment by LK4D4** [comment]
@aaronlehmann @stevvooe @NathanMcCauley does this still makes sense? #15365 was merged.

**Comment by aaronlehmann** [comment]
It's still an issue. #22337 will help a bit. In general we discourage using registries without TLS. The latest version of Registry has support for LetsEncrypt so it's even easier to set up TLS now. I don't think we're going to put much effort into making it easier to avoid TLS.

**Comment by LK4D4** [comment]
I'm closing this then. TLS is nice thing.
Thanks @aaronlehmann
