### ISSUE TITLE
docker pull --filter "chrome.flavor=stable" elgalu/selenium

### ISSUE THREAD

**Issue by elgalu** [docker/docker#16584]
New feature request;

To be able to pull images by LABEL filtering in a similar way than [label filtering works now](https://docs.docker.com/userguide/labels-custom-metadata/#query-labels)

Example usage:

Pull the latest image tag that fulfills the query filter:

```sh
docker pull \
  --filter "label=chrome.flavor=stable" \
  --filter "label=chrome.version=45" \
  --filter "label=selenium.version=2.47.1" \
  elgalu/selenium
```

We could also use `--label-filer "chrome.version=45"` instead but keeping it consistent may be convenient.

**Comment by LK4D4** [comment]
@aaronlehmann @stevvooe Do you think it's doable and reasonable.
For me it looks like too sophisticated feature.

**Comment by elgalu** [comment]
Looking in retrospective I don't see this as a good idea anymore, might be better to do this in 2 steps, first querying the images then choosing which one to run, through some tooling outside of docker.

Feel free to close if you agree.

**Comment by LK4D4** [comment]
@elgalu thanks for an update! really appreciate it.
I think we all changed our view on docker features in last year.
