### ISSUE TITLE
Docker remote API [POST /images/(name)/tag] doesn't respect "tag" parameter

### ISSUE THREAD

**Issue by imlk** [docker/docker#16592]
Description : 
<pre>
curl -X POST http://192.168.99.102:2375/images/busybox:v1/tag?repo=busybox&tag=v2
</pre>
will give busbox a "latest" tag, instead of "v2". (Both "latest" and "2" don't exist before).

Steps to reproduce:
1. pull an image busybox:oldtag
2. Tag the image with newtag by sending http request : 
_curl -X POST http://192.168.99.102:2375/images/busybox:oldtag/tag?repo=busybox&tag=newtag_
3. The busybox image now will be tagged as "latest" instead of newtag

Environment : 
Virtualbox created by docker-machine

Docker version 
<pre>
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      linux/amd64
</pre>

Docker Info
<pre>
Containers: 0
Images: 59
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 59
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.1 (TCL 6.3); master : 7f12e95 - Thu Aug 13 03:24:56 UTC 2015
CPUs: 8
Total Memory: 1.955 GiB
Name: boot2docker
ID: H4PN:LTAM:RT5Z:HOPW:CTO3:SUWK:CL3X:KLFC:YE2K:RCP6:CL3B:EIUP
Debug mode (server): true
File Descriptors: 10
Goroutines: 16
System Time: 2015-09-25T19:37:51.064129509Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: imlkai
Registry: https://index.docker.io/v1/
</pre>

uname -a
<pre>
Darwin localhost 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
</pre>

**Comment by MHBauer** [comment]
The ampersand '&' is getting caught by your shell. Quote the URL argument to CURL.

**Comment by imlk** [comment]
@MHBauer Thanks !
