### ISSUE TITLE
Ensure all the installation documentation uses new repos

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#16593]
https://twitter.com/scott_lowe/status/647174608844640256

https://blog.docker.com/2015/07/new-apt-and-yum-repos/

**Comment by csirac2** [comment]
Yes, despite searching beforehand, it does seem this is a duplicate. I've had a quick look at the commit against #16662 and you're right, this should be closed.

Thanks :)

**Comment by csirac2** [comment]
Ah, stupid me. I didn't find #16662 because it's actually newer than this bug.
