### ISSUE TITLE
[Raspberry Pi 2] System error: open /sys/fs/cgroup/.../cpu.shares: no such file or directory

### ISSUE THREAD

**Issue by luxas** [docker/docker#16607]
**BUG REPORT INFORMATION**
Description of problem:
I'm using Arch Linux ARM and a Raspberry Pi 2. Today I ran `pacman -Syu` to update the whole system. Everything went fine. Until I tried to `docker build`. The same error shows up in `docker run`, but my already running containers didn't stop. 

`uname -a` before: Linux pimaster 4.1.5-1-ARCH #1 SMP PREEMPT Wed Aug 12 19:02:34 MDT 2015 armv7l GNU/Linux
`uname -a` after: Linux pimaster 4.1.8-1-ARCH #1 SMP PREEMPT Tue Sep 22 19:47:50 MDT 2015 armv7l GNU/Linux

Full error: (fails on the last Dockerfile step)
```
[8] System error: open /sys/fs/cgroup/cpu,cpuacct/init.scope/system.slice/docker-5be33bba40f6db1534eca351c7158e1645d03bea3cf29e6a353d34fde3a4e728.scope/cpu.shares: no such file or directory
```
`docker version`
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/arm
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/arm

`docker info`
Containers: 2
Images: 6
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.8-1-ARCH
Operating System: Arch Linux ARM (containerized)
CPUs: 4
Total Memory: 923 MiB
Name: pimaster
ID: R2VA:6UUB:KPPI:KNWT:FY5X:G64X:WQET:KPIA:QOR6:7R7K:XWSQ:4OZQ
WARNING: No memory limit support
WARNING: No swap limit support

Notice the (containerized) after Operating System. It didn't show up before.

Environment details: physical Raspberry Pi

----------END REPORT ---------
#ENEEDMOREINFO

Lucas

**Comment by runcom** [comment]
This is probably an issue with the new systemd 226 and the new init.scope (in which case there's already an issue opened)
Can you confirm you're running systemd 226+?

**Comment by runcom** [comment]
The related issue  https://github.com/docker/docker/issues/16256

**Comment by luxas** [comment]
Yes, after the update, it's 226

**Comment by runcom** [comment]
Perfect, I'm gonna close this and you can track this issue at the link I posted above

**Comment by luxas** [comment]
OK, thanks!
