### ISSUE TITLE
Checking if a container is running is unnecessarily hard

### ISSUE THREAD

**Issue by lwcolton** [docker/docker#16605]
Why do I have to grep and sed the output of `docker inspect` or `docker ps` or call the docker API to programmatically check if a container is running?  Would it be possible to have a `docker status --exit-code` command or something that exits 1 if a container is stopped?  Also, the ability to call a shell script if docker restart policy has to restart a container would be great for alerting as well.

**Comment by duglin** [comment]
try: `docker inspect -f "{{.State.ExitCode}}" df04a8fc10ce`
