### ISSUE TITLE
Docker updates /etc/hosts for all containers, I don't want it to

### ISSUE THREAD

**Issue by thockin** [docker/docker#16619]
I swear this is recent - I have never seen it before 1.8 (but maybe I am nuts).  It used to be that if you used docker links, the /etc/hosts file would be updated.  Now it seems that ALL containers (even those without links) have their /etc/hosts files updated to know about all containers on the local machine.

Sniffing around this look like it might be libnetwork related, but I am not 100% sure.

How do I turn this off?  Container names are not what we want to be exposing to users.

@mavenugo

**Comment by mavenugo** [comment]
@thockin this was introduced as part of the inbuilt service discovery functionality in libnetwork. we have plans for making service discovery as a pluggable component with which the default battery can be replaced by other service discovery plugin.

Having said that, we are tracking this issue & i just opened https://github.com/docker/libnetwork/issues/567 in the libnetwork project. It will be addressed as part of 1.9.

**Comment by thockin** [comment]
So no way to turn that off?

**Comment by mavenugo** [comment]
@thockin you mean in 1.8 ? unfortunately not.

**Comment by bgrant0607** [comment]
It looks like the workaround was also broken: #10316

**Comment by bgrant0607** [comment]
And the workaround was apparently fixed:  #14613.

**Comment by bgrant0607** [comment]
A change that doesn't help us: #17230

**Comment by bgrant0607** [comment]
Related: https://github.com/docker/libnetwork/issues/519

**Comment by mfischer-zd** [comment]
What's worse, if you use the `--link` option as before, there now exist two entries for the same container name in `/etc/hosts`:

```
172.17.0.65	server 59cef7f41bbc
172.17.0.65	server
```

This would be fine, since they're not inconsistent -- except that when the `server` container is subsequently stopped, the `/etc/hosts` entry remains for the stopped container:

```
172.17.0.65	server 59cef7f41bbc
```

Then, if you remove the `server` container, and create a new one also called `server`, the /etc/hosts file in the linked container then becomes inconsistent!

```
172.17.0.68	server 59cef7f41bbc
172.17.0.69	server
```

**Comment by thaJeztah** [comment]
See this issue https://github.com/docker/docker/issues/17190#issuecomment-150743021 for more information
