### ISSUE TITLE
Docker remote api stop returned 301 status

### ISSUE THREAD

**Issue by PlugIN73** [docker/docker#16626]
Hi! Sometimes docker respond 301 for stop command.
I do it like this:

    def self.stop(cuid)
      connection.request(
        expects: [204, 304, 404],
        method: :post,
        path: "/v#{configus.docker.api_version}/containers/#{cuid}/stop",
        headers: {
          'Content-Type' => 'application/json'
        }
      )
    end

I can't see this status in docker remote api docs (v1.20):
Status Codes:

    204 – no error
    304 – container already stopped
    404 – no such container
    500 – server error

I've been seen this status for half year - from docker 1.5 to docker 1.8.2

Now my docker version:

Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

alexander.v@ip-10-0-1-80:~$ docker info
Containers: 6041
Images: 3874
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 16164
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-44-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 4
Total Memory: 29.96 GiB
Name: ip-10-0-1-80
ID: X5OZ:4RPT:25RO:GGLP:SAD3:T3PI:ULI6:AHFE:VYAU:KEVC:7LAF:H7H4
WARNING: No swap limit support

My server:
$ uname -a
Linux ip-10-0-1-80 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

I use api v1.20 from my app (but it can be reproduced on another versions).

So, this is bug or it must be documented? How i must handle this state?

**Comment by cpuguy83** [comment]
Are you going through some proxy?
Docker never responds with a 301 afaict.

**Comment by cpuguy83** [comment]
Actually, maybe this is related? https://github.com/docker/docker/pull/16577#issuecomment-143245128
Do you have a slash prefixed on your `cuid`?

**Comment by PlugIN73** [comment]
@cpuguy83 i find my mistake - i send this command without cuid (cuid - nil).
I'm sorry and thank you!
