### ISSUE TITLE
Issue mounting partition using the toolkit

### ISSUE THREAD

**Issue by sjparkinson** [docker/docker#16627]
I'm trying to mount my project source code but I'm running into the following error:

    ~/Repositories/app $ docker run -it --rm -v $(pwd):/srv ubuntu bash
    Error response from daemon: Cannot start container d229edb17428971b4f690f97d050eb62960a53ee3fae3815da241d4219063783: mkdir /Users/Samuel/Repositories: file exists

I managed to narrow it down with @rszgrz to the fact that I am using a combination of symlinks and partitions to get around the default case insensitive file system on OSX.

I have a partition at `/Volumes/Storage` (Mac OS Extended Case-sensitive, Journaled). I point to `/Volumes/Storage/Repositories` with a symlink at `/Users/Samuel/Repositories`.

I've also tried `docker run -it --rm -v /Volumes/Storage/Repositories:/srv ubuntu bash` which mounts one folder, but it's empty.

It seems like there's an issue mounting volumes on a partition with docker/docker-machine.

`docker version`: Docker version 1.8.1, build d12ea79
`uname -a`: Darwin Samuels-MacBook-Pro.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
`docker info`:

```
Containers: 5
Images: 77
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 87
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.1 (TCL 6.3); master : 7f12e95 - Thu Aug 13 03:24:56 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: RLP7:JEBP:DGOH:H4QP:X4GL:ROAF:TT2A:FMLQ:HUDB:E7MK:U7GL:V4IK
Debug mode (server): true
File Descriptors: 10
Goroutines: 20
System Time: 2015-09-28T11:54:47.904056777Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

Environment details (AWS, VirtualBox, physical, etc.): OSX toolkit

**Comment by cpuguy83** [comment]
docker-machine automatically mounts `/Users` into the VM, which makes it seamless to use with your local user files... anything other than that and you are on your own to set this up manually.
If you look at the VM details you will see the shared folder setup for /Users.

Additionally, you can't mount a file onto a dir, or a dir onto a file, which is where the "file exists" error would be coming from.

Closing as this is a non-issue.
Thanks!
