### ISSUE TITLE
Where does the package from vendor.sh go?

### ISSUE THREAD

**Issue by Pensu** [docker/docker#16625]
Hi,

So, I have been trying to add a module to docker. AFAIK you add a module to hack/vendor.sh and it is stored in vendor/ directory. I did that, but I can't find my module in vendor/ directory. Any idea what am I doing wrong? Or what is the correct way to do it? TIA.

**Comment by runcom** [comment]
This is not an issue, I'm closing this and this kind of questions are more appropriate in IRC #docker-dev channel :)  feel free to ping there
