### ISSUE TITLE
Proper documenting of Env attribute for remote API

### ISSUE THREAD

**Issue by kevinsimper** [docker/docker#16623]
Was open here, but not fixed #3622

The documentation still don't give any examples on how this works!

https://docs.docker.com/reference/api/docker_remote_api_v1.20/#create-a-container

**Comment by cpuguy83** [comment]
It is there, underneath the JSON: `Env - A list of environment variables in the form of VAR=value`

**Comment by kevinsimper** [comment]
@cpuguy83 No, it does not say whether it wants string, or a object with key values.

This would be the logic way of providing Environment variables, 

```
Env: {
  Path: '/var/bin/local/'
}
```

but in docker it is different, but the that one-liner does not explain it 

and there is not a single example of it!

**Comment by cpuguy83** [comment]
@kevinsimper For me this is defined by `in the form of VAR=value`.
But feel free to open a PR to make it more clear.
Docs are in `docs/` in this git repo.
