### ISSUE TITLE
Dockerfile documentation on EXPOSE confusing

### ISSUE THREAD

**Issue by lwcolton** [docker/docker#16634]
The Dockerfile documentation about the EXPOSE directive states it is used "to determine which ports to expose to the host when using the -P flag."

Then, it goes on to say:

"Note: EXPOSE doesn’t define which ports can be exposed to the host or make ports accessible from the host by default."

It seems to me the first statement is wrong and should be removed, because AFAIK EXPOSE does not determine which ports to expose to the host.  If I'm wrong about that, than the documentation should be updated with clarification.

**Comment by cpuguy83** [comment]
Feel free to update, docs are located in this repo at `/docs`

**Comment by mikebrow** [comment]
#dibs

**Comment by lwcolton** [comment]
Nice work, thank you

On Tue, Oct 13, 2015 at 1:35 PM, moxiegirl <notifications@github.com> wrote:

> Closed #16634 <https://github.com/docker/docker/issues/16634> via #16965
> <https://github.com/docker/docker/pull/16965>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/16634#event-434367254>.
>



-- 
Sincerely,

Colton Leekley-Winslow
651-242-9559
lwcolton@gmail.com
