### ISSUE TITLE
Eliminate stretchr/testify usage from tests.

### ISSUE THREAD

**Issue by LK4D4** [docker/docker#16633]
`pkg/discovery` uses `stretchr/testify` for testing, which looks weird, because we don't use any framework for unit-tests and use `go-check` for integration tests.

**Comment by calavera** [comment]
Let's just move everything to go-check, that way we will remove any inconsistency and doubt.

**Comment by vdemeester** [comment]
@calavera unit-tests too ? :smile_cat:

**Comment by calavera** [comment]
@vdemeester I'm all for it.

**Comment by LK4D4** [comment]
I'd move it to check too.

**Comment by vdemeester** [comment]
cool, then I guess my *shakers* project is going to be put to use \o/.

**Comment by jfrazelle** [comment]
sounds good to me lets get rid of testify first tho

**Comment by fabioxgn** [comment]
I'd like to do this, but first could you guys please tell me if I'm doing it correctly?

I've replaced testify with go-check in on package, please see if this is corret:

https://github.com/fabioxgn/docker/commit/7b3a22a19dfe3bd7e71c44b16371471a74eed9f4

Some doubts:

- I noticed the the other packages uses `github.com/go-check/check` but this gives me an error saying i should use `gopakg.in/check.v1`, which should I use?
- Is it a bad practice to import the go-check package as `.` so I don't need to call `check.` everytime? I've noticed that other test files always uses `check.` so I did it.

If the changes I've made are ok, I'll change the rest of the packages.

Thanks

**Comment by MHBauer** [comment]
Going to have some problems with the usage of testify/mock in kv_test. Is there a standardized mocking library at use in docker?

To help, here's some gofmt rules to do most of the rewrites:
```
gofmt -r 'assert.Equal(t, a, b) -> c.Assert(a, Equals, b)' -l -w ./ && \
gofmt -r 'assert.NoError(t, a) -> c.Assert(a, IsNil)' -l -w ./ && \
gofmt -r 'assert.True(t, a) -> c.Assert(a, Equals, true)' -l -w ./ && \
gofmt -r 'assert.Error(t, e) -> c.Assert(e, NotNil)' -l -w ./ && \
gofmt -r 'assert.False(t, a) -> c.Assert(a, Equals, false)' -l -w ./ && \
gofmt -r 'assert.Empty(t, a) -> c.Assert(a, HasLen, 0)' -l -w ./ && \
gofmt -r 'assert.Len(t, a, b) -> c.Assert(a, HasLen, b)' -l -w ./ && \
gofmt -r 'assert.NotNil(t, f) -> c.Assert(f, NotNil)' -l -w ./ && \
gofmt -r 'assert.Nil(t, f) -> c.Assert(f, IsNil)' -l -w ./
```

I've got a branch [here](https://github.com/docker/docker/compare/master...MHBauer:perjury). All the tests pass, and the last thing to do is get rid of the mocking.

**Comment by MHBauer** [comment]
With the asserts converted, what's left is figuring out how to convert the mocks. It might be good to get the original authors opinion, so ping @aluzzardi @abronan

**Comment by MHBauer** [comment]
With #16740 merged, I think this is complete.

**Comment by LK4D4** [comment]
@MHBauer you're right, thank you!
