### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by sowndaryak** [docker/docker#16646]
How we are differentiating pid 1,17...etc of docker containers with Host's 1,17..etc pid's? and what kernel changes are happening when we craete a new process inside the docker container?  

Linux ubuntu 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
root@ubuntu:/# docker info
Containers: 252
Images: 53
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 558
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-30-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 979.7 MiB
Name: ubuntu
ID: GWDO:XDN6:E5W2:KWGJ:L55J:KODH:I2NP:FERK:FEDU:2LHN:WMOL:DR3Z

root@ubuntu:/# docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64

**Comment by cpuguy83** [comment]
Closing as this is not an issue.
Please use the docker-user mailing list to discuss these kinds of questions.
