### ISSUE TITLE
Unable to ping registry endpoint https://myserver.example.com:5000/v0/ v2 ping attempt failed with error: Get https://myserver.example.com:5000/v2/: tls: oversized record received with length 20527 // By JCR

### ISSUE THREAD

**Issue by jc-evogi** [docker/docker#16657]
BUG REPORT INFORMATION

Use the commands below to provide key information from your environment:

docker version: 1.8.2 
```
docker info:
Containers: 1
Images: 81
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 83
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.1 (TCL 6.3); master : 7f12e95 - Thu Aug 13 03:24:56 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: dev
ID: MG5B:CBPY:RHYT:O3NS:3WT6:O3T7:P2W7:V5ZB:7DMM:X3ZI:IXWK:5VIW
Debug mode (server): true
File Descriptors: 10
Goroutines: 17
System Time: 2015-09-29T16:15:43.628363228Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

uname -a:
localdomain 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):
I am getting the following error when I try to pull an image through a docker client running in my MAC . and against a Docker Registry hosted in AWS (Ubuntu 14.04).  The Registry front-end is using Nginx (Proxy server) with SSL with CA signed certificates, also handling basic authorization through httpasswd. The docker registry storage is in S3. The registry server hosted in Amazon has the option  DOCKER_OPTS="--insecure-registry "myserver.example.com:5000" enabled.   If I try to Pull images from a Docker client running in the same docker registry host docker pull/push works just fine: 

List the steps to reproduce the issue:
1. After a successfully  docker login:
  docker login '--username=myuser' '--password=mypassword' "--email=$(whoami)@example.com" https://myserver.example.com
output:
WARNING: login credentials saved in /Users/myuser/.docker/config.json
Login Succeeded

2..Try a docker pull of the image stored in our Registry server 
docker pull myserver.example.com:5000/nginx_test

Describe the results you received:
Using default tag: latest
Error response from daemon: unable to ping registry endpoint https://myserver.example.com:5000/v0/
v2 ping attempt failed with error: Get https://myserver.example.com:5000/v2/: tls: oversized record received with length 20527
 v1 ping attempt failed with error: Get https://myserver.example.com:5000/v1/_ping: tls: oversized record received with length 20527

Describe the results you expected:
latest: Pulling from nginx_test
843e2bded498: Already exists 
8c00acfb0175: Already exists 
426ac73b867e: Already exists 
d6c6bbd63f57: Already exists 
4ac684e3f295: Already exists 
91391bd3c4d3: Already exists 
b4587525ed53: Already exists 
0240288f5187: Already exists 
28c109ec1572: Already exists 
063d51552dac: Already exists 
d8a70839d961: Already exists 
ceab60537ad2: Already exists 
Digest: sha256:c49f8f86928f20c56873ebc99e4b6b72638e762b60a0f289aed99112a33e7a3b
Status: Downloaded newer image for myserver.example.com :5000/nginx_test:latest
jcr@docker-registryv2:~$ 

Provide additional info you think is important:
If I "pull/push" images through a docker client running in the same docker host where docker registry container is running the events works just fine

----------END REPORT ---------

#ENEEDMOREINFO

**Comment by cpuguy83** [comment]
Hello, 

My initial thoughts on this is that there is a misconfiguration somewhere rather than a bug.
I'm going to close this since this isn't the correct forum for troubleshooting.
However I'd like to invite you to the docker-user mailing list or #docker-distribution on IRC where it is much easier to provide support for troubleshooting these kinds of issues.

Thanks!

**Comment by jc-evogi** [comment]
The issue was the "port" it not suppose to be included in the "Docker pull/push" command . ..;)

Thanks,

JC

**Comment by h6w** [comment]
That contradicts this blog entry: https://blog.docker.com/2013/07/how-to-use-your-own-registry/.  "Now the new feature! To push to or pull from your own registry, you just need to add the registry’s location to the repository name. It will look like my.registry.address:port/repositoryname."

**Comment by cpuguy83** [comment]
@h6w it's not due to the port. The telling bit is here:  `tls: oversized record received with length 20527`
This seems to indicate that tls is misconfigured on nginx.

**Comment by justinjby2016** [comment]
@jc-evogi hi, i have the same exact problem, can you help me? can you tell me what do you mean by "The issue was the "port" it not suppose to be included in the "Docker pull/push" command"??

i'm kind new to docker.
thank you so much

**Comment by bluepuma77** [comment]
Instead of 
```docker pull myserver.example.com:5000/nginx_test``` 
do 
```docker pull myserver.example.com/nginx_test```

**Comment by justinjby2016** [comment]
@bluepuma77 thank you for your help, but i kind fixed the problem. 

it's kind weird, first i was working on a CentOs (vmwares station environment), i download docker, and it doesn't work.

my solution: i moved to a Ubuntu 14.04 (vmware), i download docker, and docker works.

i find it so strange, but if this is how i solved the problem. hopefully my solution will help someone in the future.

**Comment by kkorada** [comment]
i am also facing same issue, ping attempt to v2 is failing and so it is falling back to v1 and from v1 i am able to fetch! what might be the issue can someone please help me ?
