### ISSUE TITLE
DOCS : missing .Names placeholder for docker ps --format

### ISSUE THREAD

**Issue by j0r0** [docker/docker#16651]
https://docs.docker.com/reference/commandline/ps/

The placeholder .Names is missing in available placeholders for
```
docker ps  --format
```

```
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:21:21 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:21:21 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by Evalle** [comment]
#dibs

**Comment by Evalle** [comment]
Hm it's already done but still not updated in main docs :\

**Comment by odigity** [comment]
In what version?  I'm on 1.8.3, and --format '{{.Name}}' errors out.

**Comment by thaJeztah** [comment]
This has been fixed in https://github.com/docker/docker/pull/16153, and the docs website will be updated together with the 1.9 release.

@odigity the placeholder is actually `Names` (plural)
