### ISSUE TITLE
docker timeouts when waiting for mkfs to finish on devicemapper storage driver device

### ISSUE THREAD

**Issue by jaryn** [docker/docker#16653]
# Description
```
docker version: docker-1.7.1-115.el7.x86_64
docker info: N/A
uname -a: Linux test-node-compute-f429d.example.com 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
platform: libvirt (kvm)
```

By default on RHEL 7.1 docker creates sparse file one upon start (systemctl start docker). That file is used as a loopback-device (seemingly using dmsetup syscall eqivalents), then issues 

    mkfs.ext4 -E nodiscard,lazy_itable_init=0,lazy_journal_init=0 /dev/mapper/docker-253:1-243367-base

This command may take several minutes to complete. Meanwhile the ```avgqu-sz``` gauge of sar shoots up to >25000. Then the systemctl start reports  timeout.

# Reproducer
Remove the backing files. I am not sure about the order of dmsetup lines here.
```
# systemctl stop docker
#dmsetup remove /dev/dm-0
#dmsetup remove /dev/dm-1
# rm /var/lib/docker/devicemapper/devicemapper/*
# systemctl start docker
```
... BLOCKING

```
# sar -d 1
...
15:28:24          DEV       tps  rd_sec/s  wr_sec/s  avgrq-sz  avgqu-sz     await     svctm     %util
15:28:25     dev253-0      0,00      0,00      0,00      0,00      0,00      0,00      0,00      0,00
15:28:25    dev253-16      0,00      0,00      0,00      0,00      0,00      0,00      0,00      0,00
15:28:25     dev252-0      0,00      0,00      0,00      0,00    112,86      0,00      0,00    100,40
15:28:25     dev252-1      0,00      0,00      0,00      0,00  34883,39      0,00      0,00    100,40
```

For some time, we can see the mkfs being performed
```
#ps aux | grep mkfs
mkfs.ext4 -E nodiscard,lazy_itable_init=0,lazy_journal_init=0 /dev/mapper/docker-253:1-243367-base
```

But the user-space process disappears before the kernel-space process, while the queue is still quite full.

The result is 
```
[root@test-node-compute-f429d openshift]# systemctl status -l docker.service
docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled)
  Drop-In: /usr/lib/systemd/system/docker.service.d
           └─docker-sdn-ovs.conf
   Active: failed (Result: timeout) since Út 2015-09-29 15:30:25 UTC; 1min 53s ago
     Docs: http://docs.docker.com
 Main PID: 25025

zář 29 15:27:25 test-node-compute-f429d.example.com systemd[1]: Starting Docker Application Container Engine...
zář 29 15:27:25 test-node-compute-f429d.example.com docker[25025]: time="2015-09-29T15:27:25.975880434Z" level=warning msg="--storage-opt dm.thinpooldev is preferred over --storage-opt dm.datadev or dm.metadatadev"
zář 29 15:27:25 test-node-compute-f429d.example.com docker[25025]: time="2015-09-29T15:27:25.976662822Z" level=info msg="Listening for HTTP on unix (/var/run/docker.sock)"
zář 29 15:27:25 test-node-compute-f429d.example.com docker[25025]: time="2015-09-29T15:27:25.978128795Z" level=error msg="Unable to delete device: Error running DeleteDevice dm_task_run failed"
zář 29 15:28:55 test-node-compute-f429d.example.com systemd[1]: docker.service operation timed out. Terminating.
zář 29 15:30:25 test-node-compute-f429d.example.com systemd[1]: docker.service stopping timed out (2). Killing.
zář 29 15:30:25 test-node-compute-f429d.example.com systemd[1]: Failed to start Docker Application Container Engine.
zář 29 15:30:25 test-node-compute-f429d.example.com systemd[1]: Unit docker.service entered failed state.
```

It seems mkfs wrote about at least 150MB of data:
```
#du -h /var/lib/docker/devicemapper/devicemapper/*
150M	/var/lib/docker/devicemapper/devicemapper/data
672K	/var/lib/docker/devicemapper/devicemapper/metadata
```
subsequent mkfs executed on the device exits fast, I think this is caused by the fact it is thin-provisioned.

I can't see any meaningfull error message in the logs that would help me debugging this problem.

Note that when one tries to start the docker again, docker will re-create the sparse file so the start is likely to fail again even though the FS is created fine every time, because this is done asychronously

# Expected state
Docker started on system no matter how much loaded it is. This would probably need checking of the mkfs progress.

Maybe the -D mkfs option may help.

       -D     Use  direct I/O when writing to the disk.  This avoids mke2fs dirtying a lot of
              buffer cache memory, which may impact other  applications  running  on  a  busy
              server.   This  option  will  cause mke2fs to run much more slowly, however, so
              there is a tradeoff to using direct I/O.

**Comment by cpuguy83** [comment]
ping @rhvgoyal

**Comment by rhvgoyal** [comment]
@jaryn 

This primarily happens because your underlying storage is slow. And recently we had increased the default size of base image to 100G (from 10G) so on slower storage problem became worse and it started to run into systemd timeout.

Quick work around are following.

- Don't use loop devices. Use lvm thin pool on top of a resonably fast block device.
- Use 10G base device size. Pass daemon option --storage-opt dm.basesize=10G
- Increase systemd timeout. (man systemd.unit).

In the long run, I think we should revert the patch to reduce the base image size to say 20G and allow a docker create/run option which can specify the size of container at creation time. (Say --storage-opt dm.size=100G). That way one can start with a small base size but specify a bigger size for specific containers. This might still run into build issues though.

**Comment by jaryn** [comment]
Well, my underlying storage is SSD, so my guess it is not the bottleneck.

However although I have been able to reproduce this issue several times before I reported it I am not able to reproduce it any more.

**Comment by rhvgoyal** [comment]
@jaryn Trying using lvm thin pool instead of loop devices and should have a better experience.

**Comment by rhvgoyal** [comment]
@jaryn docker-storage-setup utility can easily setup lvm thin pool for you.

https://github.com/projectatomic/docker-storage-setup

We also ship it as part of docker package in fedora/rhel/centos.

**Comment by thaJeztah** [comment]
@rhvgoyal perhaps you can have a look at https://github.com/docker/docker/pull/17486, it's a WIP for improvements around the docs for storage drivers; perhaps that tool should be mentioned in the docs as well, wdyt?

**Comment by rhvgoyal** [comment]
@thaJeztah I think mentioning docker-storage-setup in docker docs is a good idea. It should help people setup lvm thin pool relatively easily. (Better then reading `man lvmthin` and doing it yourself).

**Comment by thaJeztah** [comment]
Thanks @rhvgoyal, I left a comment there to consider including it

**Comment by jaryn** [comment]
Please note my complain that there was no useful error that would help me to immediately see what is the problem. Can / have this been improved?

**Comment by thaJeztah** [comment]
@jaryn I'm not sure that's possible, given that the timeout is produced by systemd, open to suggestions though.

**Comment by rhvgoyal** [comment]
I think we can put one debug/info message in docker which says that docker is creating filesystem on base device. That way when it times out, user can look at the logs and figure out that creating filesystem was taking a long time.

**Comment by thaJeztah** [comment]
@rhvgoyal guess that could work, i.e. a message before and after the filesystem was created. Are you interested in creating a PR for that? :innocent:

**Comment by rhvgoyal** [comment]
@thaJeztah Ok, I will create one.

**Comment by jaryn** [comment]
Thanks you all.

**Comment by thaJeztah** [comment]
Thanks for reporting @jaryn, your feedback helps us improve the project!
