### ISSUE TITLE
1.9: docker ps truncates image name

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#16663]
If you run `docker ps` on 1.9 you only get the first 12 characters of the image name

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                  PORTS               NAMES
fa8aedb577d8        ibuildtheclo        "/sleep.sh"         1 seconds ago       Up Less than a second   8080/tcp            backstabbing_northcutt
```

Yeah.... that's no good.  Running `--no-trunc` fixes this, but your going to have some unhappy users with this one.

```
Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   17062ae
 Built:        Tue Sep 29 16:05:42 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   17062ae
 Built:        Tue Sep 29 16:05:42 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by calavera** [comment]
Indeed, I don't like this change either. It was introduced in master a few weeks ago. We should reevaluated for 1.9.

**Comment by coolljt0725** [comment]
#15472  is to fix the problem

**Comment by wcwxyz** [comment]
Please don't truncate image:tag. Otherwise we're losing information.
OTOH, trunc ID is ok. Because trunc'd ID is still valid information and we don't lose anything.
