### ISSUE TITLE
1.9: Config.Cpuset (and probably others) are missing in inspect

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#16665]
I realize that `Config.Cpuset` has been replaced with `HostConfig.CpusetCpus` but this is a breaking change for API <= 1.20.  Only 1.21 should not return these fields if we really want to drop them.

**Comment by calavera** [comment]
I'm almost certain those changes were introduced in 1.8, but I might be wrong. At least, my PR to move legacy types tells me that `Config.Cpuset` was deprecated in 1.20:

https://github.com/docker/docker/pull/16564/files

**Comment by ibuildthecloud** [comment]
@calavera The changes were introduced in 1.8 but the breaking change appeared in (the yet to be released) 1.9.  In 1.8 Cpuset was still being returned.  Also, should have mentioned that I'm testing with 1.18 client.

**Comment by calavera** [comment]
okay, I added it to the milestone to take a look. I'm going to be MIA for the next two weeks, so at least other people will have it in consideration.
