### ISSUE TITLE
docker-engine.rpm push the fish completion in the wrong place

### ISSUE THREAD

**Issue by amluto** [docker/docker#16668]
See https://github.com/fish-shell/fish-shell/issues/2436

The fish completion file should be in /usr/share/fish/vendor_completions.d

**Comment by amluto** [comment]
BUG REPORT INFORMATION

docker version: git master.  also affects docker-engine-1.8.2-1.fc22.x86_64
docker info: I didn't even bother installing docker.
uname -a: Linux [redacted] 4.1.6-200.fc22.x86_64 #1 SMP Mon Aug 17 19:54:31 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Provide additional environment details (AWS, VirtualBox, physical, etc.):

Inspection.  Also, the specfile is clearly wrong.

List the steps to reproduce the issue:
1.  # dnf install fish
2.  # curl -sS curl https://get.docker.com/ |sh
3.  Read https://github.com/docker/docker/blob/master/hack/make/.build-rpm/docker-engine.spec#L146 and observe that the directory is indeed wrong.

Describe the results you received:

I didn't actually try it, but it will fail.  Or follow the link above for someone who did try it.

Describe the results you expected:

It shouldn't have failed.  I can't believe I'm typing this.

Provide additional info you think is important:

----------END REPORT ---------

**Comment by LK4D4** [comment]
ping @jfrazelle

**Comment by jfrazelle** [comment]
Cool wanna open a pr

**Comment by thaJeztah** [comment]
PR for RPM created in https://github.com/docker/docker/issues/17144

now looking at apt/deb

**Comment by thaJeztah** [comment]
and pr for deb; https://github.com/docker/docker/issues/17145

**Comment by bings** [comment]
Still getting this with latest 1.9.0 docker on CentOS 7? 
```
Transaction check error:
  file /usr/share/fish/completions/docker.fish from install of fish-2.2.0-3.1.x86_64 conflicts with file from package docker-engine-1.9.0-1.el7.centos.x86_64
```

**Comment by jfrazelle** [comment]
that PR was not in the release

**Comment by jfrazelle** [comment]
it will be in the next one

**Comment by thaJeztah** [comment]
@jfrazelle 1.9.1?

**Comment by jfrazelle** [comment]
if @tiborvass wants

**Comment by thaJeztah** [comment]
`<-- insert cute puppy eyes image here -->`

**Comment by ashtonbatty** [comment]
Still happening with 1.9.1 
````
Transaction check error:
  file /usr/share/fish/completions/docker.fish from install of fish-2.2.0-3.1.x86_64 conflicts with file from package docker-engine-1.9.1-1.el7.centos.x86_64
````

**Comment by thaJeztah** [comment]
@ashtonbatty these changes are not used when building the 1.9.x RPMs, they'll probably land in the next, 1.10 release

**Comment by metal3d** [comment]
So, at this time, the only way to install docker-engine package from docker repo is to use `dnf download docker-engine-selinux docker-engine` and install them with `rpm -ivh --replacefiles ...`

But any update of fish package with `dnf update` will break... It could be great to have a fix on 1.9.1-X package.

**Comment by Assada** [comment]
+1

**Comment by phocean** [comment]
Very annoying, especially because I cannot use the version of Docker provided in Fedora (for some reason, it is unable to log into the hub).
Can't it be fixed with the 1.9, or is there a repo with 1.10 ?

**Comment by thaJeztah** [comment]
1.10 is now out; repo is at yum.dockerproject.org

**Comment by metal3d** [comment]
Seems to work as expected. I updated and didn't had any problem.

Thanks
