### ISSUE TITLE
Docker 1.8.2 push to private registry doesn't work but 1.7.1 does

### ISSUE THREAD

**Issue by Khazrak** [docker/docker#16677]
After an upgrade to Docker-engine 1.8.1 and then 1.8.2 pushing to the private registry (v2.1.1) doesn't work, it says: 
```The push refers to a repository [myregistry:443/myrepo/wiremock] (len: 1)
df20de480fa2: Pushing [==================================================>]     32 B/32 B
unauthorized: access to the requested resource is not authorized```

It's not that I'm not logged in, I've tried:
docker login myregistry:443 && docker push myregistry:443/myrepo/wiremock:1.56 and it says login successful and then the same error message.

The logs of the Docker Daemon says:
```\<MY_IP> - iptv [30/Sep/2015:10:56:49 +0000] "PUT /v2/myrepo/wiremock/manifests/1.56 HTTP/1.1" 201 0 "-" "docker/1.8.2 go/go1.4.2 git-commit/0a8c2e3 kernel/3.13.0-63-generic os/linux arch/amd64" "-"

\<MY_IP> - - [30/Sep/2015:10:57:04 +0000] "GET /v2/ HTTP/1.1" 401 194 "-" "docker/1.8.2 go/go1.4.2 git-commit/0a8c2e3 kernel/3.13.0-63-generic os/linux arch/amd64" "-"

\<MY_IP> - iptv [30/Sep/2015:10:57:04 +0000] "POST /v2/myrepo/wiremock/blobs/uploads/ HTTP/1.1" 202 0 "-" "docker/1.8.2 go/go1.4.2 git-commit/0a8c2e3 kernel/3.13.0-63-generic os/linux arch/amd64" "-"

\<MY_IP> - - [30/Sep/2015:10:57:04 +0000] "PATCH /v2/myrepo/wiremock/blobs/uploads/773d0840-33e3-440a-8347-64534914ee2b?_state=QJcrX3IyH6lZZXCvE1JSvW9_JsXLN0jSQ2ikEfCyBxJ7Ik5hbWUiOiJ0ZWxpYS93aXJlbW9jayIsIlVVSUQiOiI3NzNkMDg0MC0zM2UzLTQ0MGEtODM0Ny02NDUzNDkxNGVlMmIiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMTUtMDktMzBUMTA6NTc6MDQuNzE4Nzk0MTEyWiJ9 HTTP/1.1" 401 194 "-" "docker/1.8.2 go/go1.4.2 git-commit/0a8c2e3 kernel/3.13.0-63-generic os/linux arch/amd64" ```

The last part (PATCH) seems to give 401.

I'm using a nginx-proxy by following this guide: http://container-solutions.com/running-secured-docker-registry-2-0/

And downgrading to 1.7.1 works fine. Is it Docker-engine or the Registry?

**Comment by cpuguy83** [comment]
This looks like a configuration issue.

I'm going to close this as it is not likely a bug in docker and this isn't really the best place to provide support.
I would like to invite you to the docker-user mailing list or #docker-distribution on IRC to help troubleshoot.
https://github.com/docker/distribution/blob/master/docs/deploying.md also has some pretty extensive documentation on setting this up.

Thanks!

**Comment by ferrix** [comment]
I am having this exact same problem.

I am running docker 1.8.2 and registry 2.1.1. The configuration is pretty much identical to the one in https://docs.docker.com/registry/nginx/. I am using s3 as my backend and it has been functioning before with the exact configuration.

The PATCH request is not shown on registry at all.

**Comment by ferrix** [comment]
Logs state only this for the push:

    172.17.0.17 - - [02/Oct/2015:14:40:57 +0000] "POST /v2/flower/blobs/uploads/ HTTP/1.0" 202 0 "" "docker/1.8.2 go/go1.4.2 git-commit/0a8c2e3 kernel/4.0.9-boot2docker os/linux arch/amd64"

The client says thus (debug reveals nothing important):

    e2ea28d6: Pushing [==================================================>]     32 B/32 B
    unauthorized: access to the requested resource is not authorized

**Comment by cpuguy83** [comment]
@ferrix Please see the the forums mentioned in https://github.com/docker/docker/issues/16677#issuecomment-144413480 for help troublshooting this issue.
Thanks!

**Comment by ferrix** [comment]
The nginx log reveals one more call:

    172.31.24.120 - ferrix [02/Oct/2015:14:42:54 +0000] "POST /v2/flower/blobs/uploads/ HTTP/1.1" 202 0 "-" "docker/1.8.2 go/go1.4.2 git-commit/0a8c2e3 kernel/4.0.9-boot2docker os/linux arch/amd64" "188.127.204.162"
    172.31.32.136 - - [02/Oct/2015:14:42:54 +0000] "PATCH /v2/flower/blobs/uploads/4127d3b8-231b-4e4c-b6d2-16d45e763202?_state=lZMfxIem4N1ZLydT3W3MLkJHhbha3Cd1HS4NXfW95V57Ik5hbWUiOiJzaWdydW4tZnJvbnQiLCJVVUlEIjoiNDEyN2QzYjgtMjMxYi00ZTRjLWI2ZDItMTZkNDVlNzYzMjAyIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE1LTEwLTAyVDE0OjQyOjU0LjY5NjM3OTcxMloifQ%3D%3D HTTP/1.1" 401 194 "-" "docker/1.8.2 go/go1.4.2 git-commit/0a8c2e3 kernel/4.0.9-boot2docker os/linux arch/amd64" "188.127.204.162"

**Comment by ferrix** [comment]
Since I am following your user guides and they have worked and I have not touched my nginx since, this is likely a bug in docker OR you have failed to update your guidance for nginx configuration.

THIS IS A BUG.

**Comment by ferrix** [comment]
Actually. The client probably doesn't authenticate the patch request. The third field in the nginx log is the authenticated user and you can see there is a dash there. So this is something with 1.8.1 and 1.8.2 clients that we have been testing this with.

**Comment by Khazrak** [comment]
I switched from Nginx proxy (basic auth) to Docker Registry's native basic auth and now 1.8.2 works fine.
