### ISSUE TITLE
Connections to Docker Hub are timing out from engine

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/docker#16691]
Hi, I have a virtual machine on the cloud (Azure) behind a firewall, which I ssh into using VPN.

This machine cannot do `docker pull`/`docker search`  and connection times out. But if I do curl to these URLs it just works fine. 

I'm out of ideas, friends. How do I debug this?

```
$ docker search ubuntu
Error response from daemon: Get https://index.docker.io/v1/search?q=ubuntu: dial tcp: i/o timeout

$ curl https://index.docker.io/v1/search?q=ubuntu
[ works fine, returns json response ]
```

```
$ docker pull ubuntu
Using default tag: latest
Pulling repository docker.io/library/ubuntu
Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/ubuntu/images. You may want to check your internet connection or if you are behind a proxy.

$ curl https://index.docker.io/v1/repositories/library/ubuntu/images
[ works just fine as well ]
```

### Version
```
$ docker version
Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   743dc1c
 Built:        Mon Sep 21 13:20:09 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   743dc1c
 Built:        Mon Sep 21 13:20:09 UTC 2015
 OS/Arch:      linux/amd64
```

```
$ uname -a
Linux ahmetb-dev 3.19.0-28-generic #30~14.04.1-Ubuntu SMP Tue Sep 1 09:32:55 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty
```

**Comment by cpuguy83** [comment]
Working here.
Is this still a problem?

**Comment by ahmetalpbalkan** [comment]
@cpuguy83 I'm not saying it's not working for others, too. My other engines are working, too. But this machine has a weird behavior, curl-ing the URL works but Docker engine can't do the same operation. I was wondering if there is a way to debug this.

**Comment by ahmetalpbalkan** [comment]
I realized this is about me installing docker stable and then just replacing engine binary with the master build. Closing.

**Comment by aerodame** [comment]
I was having this same problem over and over today.  Just trying to pull gcc gives me network timeouts (from about 5 different wifi network locations... network speed is at least 15MB/s...

$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

Is this is a known problem?  In googling around it doesn't seem to be addressed.

**Comment by tedchang77** [comment]
I'm seeing the same problems as areodame. Below is the information from my environment:

$ docker search ubuntu
Error response from daemon: Get https://index.docker.io/v1/search?q=ubuntu: dial tcp: lookup index.docker.io on 192.168.1.1:53: read udp 192.168.1.1:53: i/o tim
eout

$ curl https://index.docker.io/v1/search?q=ubuntu
[ works fine, returns json response ]

$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

$ docker info
Containers: 7
Images: 18
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 32
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: default
ID: KRTW:K35I:Y4RW:WXZF:OBBX:7KRH:MROL:CEVH:AV6K:3XCY:U5OO:CR2E
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 20
 System Time: 2016-01-19T17:54:16.0943974Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

$ uname -a
MINGW64_NT-6.1 LT-PK23XXL 2.1.0(0.288/5/3) 2015-06-28 18:57 x86_64 Msys

**Comment by vhmth** [comment]
Problem for me as well. [This](http://stackoverflow.com/a/32023104/696130) seemed to fix it.

`version`:

```
vinay@Vinays-MacBook-Pro ~> docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:18:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 19:55:25 2016
 OS/Arch:      linux/amd64
```

`info`:

```
vinay@Vinays-MacBook-Pro ~> docker info
Containers: 19
 Running: 0
 Paused: 0
 Stopped: 19
Images: 4
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 78
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 4.1.17-boot2docker
Operating System: Boot2Docker 1.10.0 (TCL 6.4.1); master : b09ed60 - Thu Feb  4 20:16:08 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: SCGO:II2Y:EVAP:KYPX:R6ZO:A36D:2TXG:CBG6:RG5A:ASJS:ZRX3:VZXT
Debug mode (server): true
 File Descriptors: 10
 Goroutines: 22
 System Time: 2016-02-05T06:13:03.941772053Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: vinayh
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

`uname`:

```
Darwin Vinays-MacBook-Pro.local 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64
```

**Comment by jlongie** [comment]
Running against Docker 1.10 the following steps worked for assuming Im behind a corporate firewall.

```sh
docker-machine rm default
docker-machine create -d virtualbox \
    --engine-env HTTP_PROXY=http://proxy:8080 \
    --engine-env HTTPS_PROXY=http://proxy:8080 \
    --engine-env NO_PROXY=*.corp,localhost \
    default
```

Once this is built you then need to set your shell env:

```sh
eval $(docker-machine env default) 
```

This worked for me as corporate firewall was blocking everything!

**Comment by raghuchowdareddy** [comment]
Thank you , it worked for me as well.
however , my issued was not in "default" vm . when i create a new VM with diffenre name (example: test1)  and try to run my docker image, it use to block because of corporate proxy i think.
so , with the above command (by jlongie) will worked fine
