### ISSUE TITLE
api to control other containers from a container

### ISSUE THREAD

**Issue by ibukanov** [docker/docker#16693]
Currently it is not possible to start/stop other containers from a docker container unless one exposes the docker socket connection to it. It would be nice if docker could expose a limited API into a container to start/stop or listen events from other containers.

This would allow, for example, from a container running crone-like service to start periodically jobs from other containers. Another example is to start from sshd container sftp session running in a separated container for maximum isolation.

To implement this Docker could, for example,  expose a special socket into a container witch allows to control containers that explicitly allowed to do so.

**Comment by cpuguy83** [comment]
Hello,

Please see https://github.com/docker/docker/issues?utf8=✓&q=is%3Aissue+is%3Aopen+introspection

Closing as this seems covered by other issues.

This could also be accomplished through proxying the API to allow only access to the bits that you want to expose into the container.

Thanks!
