### ISSUE TITLE
containers API: "Names" might be None instead of empty list

### ISSUE THREAD

**Issue by blueyed** [docker/docker#16706]
The response from the `containers()` API will return `None` (with docker-py) value of key `Names` sometimes:

It seems that for "Dead" containers, the `Names` attribute is "null" from the CLI.

    {'Status': 'Dead', 'Created': 1429869422, 'Image': 'busybox:latest', 
    'Labels': {}, 'Ports': [], 'Command': '/bin/sh', 
    'Names': None, 'Id': u'51bce5b06abf3e27cf1f6526105cac1f5022b828d8aaf3cc089044115f3a4adb'}

Should it always be an empty list?
Otherwise it results in issues like https://github.com/saltstack/salt/pull/27601.

See https://github.com/docker/docker-py/issues/561.

**Comment by cpuguy83** [comment]
I don't see how names could ever be empty.
Can you plase paste the requested info (output of `docker version` and `docker info`).

**Comment by blueyed** [comment]
@cpuguy83 
Thanks for looking into this.

It popped up during Salt deployment tests.  The involved Docker version was either 1.6.2 or 1.8.2-0~trusty.
I am not sure if the latter/current one was affected also.
I could investigate further, but it requires a "Dead" machine in the list to reproduce it, and given the issue I've found for docker-py, it seems to at least have been an issue with Docker before.
Can you provide some pointer where to look at?

I could provide the `docker version` and `docker info`, but the latter won't have the Dead images anymore.

**Comment by cpuguy83** [comment]
Sure, this happens in `daemon/list.go`.
Basically, containers always have a name, and that name is always populated...
Maybe in 1.6.2 it was an issue, but there's been significant change since then....

I'd be interested to see if this is still true and how to repro.

**Comment by blueyed** [comment]
@cpuguy83 
Is there a way to easily create a Dead container?
I assume this might be easier to ensure by having a mocked test for it?

**Comment by cpuguy83** [comment]
oh, hmm... the container's state is "Dead"?... Should be easy to create one. From the host, create a mount in the container's fs path, then try to remove the container.

**Comment by blueyed** [comment]
> the container's state is "Dead"?

Yes, that's specific to this issue apparently.

I will not retry to reproduce it now or in the next days probably.

**Comment by dnephin** [comment]
We had to work around this in compose as well: https://github.com/docker/compose/commit/dfa4bf4452584f1a2533254231b862d521d75f85, https://github.com/docker/compose/pull/1835.

> If a container is in the process of being removed, or removal has failed, it can sometimes appear in the output of GET /containers/json but not have a Name key

In https://github.com/docker/compose/issues/1593  there are a bunch of reports from docker 1.7.x. We patched it after that, so I'm not sure if it's still happening in 1.8.x.

**Comment by cpuguy83** [comment]
@dnephin Thanks, that helps a lot.

**Comment by blueyed** [comment]
Thanks, @dnephin!

`daemon/list.go` has changed a lot since v1.7.0, especially with regard to the `listContext` being added, and which seems to make sure that it is always a list now.

**Comment by cpuguy83** [comment]
I found the issue.
It's because the containers names are remove first on removal... but the most likely thing to cause a remove issue is removing the container fs, which comes later and names are never restored.

**Comment by blueyed** [comment]
@cpuguy83 
Awesome!  I'm glad the bug is found! :)

**Comment by cpuguy83** [comment]
#16736, testing appreciated.

**Comment by rgbkrk** [comment]
Welp @minrk and @andrewosh it seems we now know the source of this strange one.
