### ISSUE TITLE
Add built-in support for aliases in docker CLI

### ISSUE THREAD

**Issue by mathieu-pousse** [docker/docker#16702]
It will be nice to have a built-in system of aliases in the docker CLI. 

This could help users to define complex "one-liner" they use to join a running container, clean up, start a new ubuntu or playing a nice hello world instead of using bash aliases. Built-in aliases can reuse your bash completion and are well integrated with your environment

Check out this video : https://youtu.be/ZfP-K2AYtbI

@agouriou @ggerbaud and my self have already implemented this feature during the docker global hackday, PR to follow

**Comment by calavera** [comment]
As I mentioned in #16703, we should not reimplement bash features. Closing.
