### ISSUE TITLE
facing netlink error when building docker on ubuntu15.04 

### ISSUE THREAD

**Issue by nareshk355** [docker/docker#16701]
when I run `hack/make.sh gyngccgo` 

getting below error  

vendor/src/github.com/docker/libcontainer/netlink/netlink_linux.go:1246:26: error: incompatible types in assignment (cannot use type int8 as type uint8)
   ifr.IfruHwaddr.Data[i] = ifrDataByte(hw[i])

any suggestions to fix the error

**Comment by nareshk355** [comment]
I'm trying to build docker version 1.6.2 
 uname -a : Linux pts00449-vm4 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:13 UTC 2015 ppc64le ppc64le ppc64le GNU/Linux

when I tried to run hack/make.sh gyngccgo command getting above error

**Comment by alexellis** [comment]
@nareshk355 I managed to resolve the issue at my end. Either a new version of gcc-go or a binary version of go itself.

**Comment by thaJeztah** [comment]
@nareshk355 I'm going to close this issue because this is a question better asked in the #docker-dev IRC channel, but feel free to comment here after I've closed, thanks!
