### ISSUE TITLE
Incomplete documentation for updating Docker on Ubuntu

### ISSUE THREAD

**Issue by aldobongio** [docker/docker#16716]
ubuntu@server:~$ docker version
    Client version: 1.7.1
    Client API version: 1.19
    Go version (client): go1.4.2
    Git commit (client): 786b29d
    OS/Arch (client): linux/amd64
    Server version: 1.7.1
    Server API version: 1.19
    Go version (server): go1.4.2
    Git commit (server): 786b29d
    OS/Arch (server): linux/amd64

    ubuntu@server:~$ docker info
    Containers: 8
    Images: 63
    Storage Driver: aufs
     Root Dir: /var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 79
     Dirperm1 Supported: false
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 3.13.0-58-generic
    Operating System: Ubuntu 14.04.2 LTS
    CPUs: 2
    Total Memory: 3.859 GiB
    Name: ************
    ID: 36XS:MMPO:MGBK:EEKA:T2UF:QJKH:FROW:EARP:G7MJ:ATXF:C3WT:5ZTQ
    WARNING: No swap limit support

    ubuntu@server:~$ uname -a
    Linux ************ 3.13.0-58-generic #97-Ubuntu SMP Wed Jul 8 02:56:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

# Steps to reproduce the issue:
1. Open the official "Installation on Ubuntu" documentation page
2. Go to the Upgrade section https://docs.docker.com/installation/ubuntulinux/#upgrade-docker
3. Run the suggested command in order to upgrade from 1.7.1 to the current stable version (1.8.2)

 `$ curl -sSL https://get.docker.com/ | sh`

I received the following message:
`Warning: the "docker" command appears to already exist on this system.
If you already have Docker installed, this script can cause trouble, which is
why we're displaying this warning and provide the opportunity to cancel the
installation.
If you installed the current Docker package using this script and are using it
again to update Docker, you can safely ignore this message.
You may press Ctrl+C now to abort this script.`

What I expected:
I've discovered that I've installed version 1.7.1 using the following command (please see the `/ubuntu` at the end):
`$ curl -sSL https://get.docker.com/ubuntu | sh`

If I try to re-run the original command (the one with `/ubuntu`) nothing happens, the version stays at 1.7.1, so I can guess that the new command (the one without `/ubuntu`) is the only one able to perform the upgrade, but it is suggesting me to stop it using CTRL+C because the original installation were not performed using such a script.

In the end the issue is: I don't know how to proceed because neither the script nor the documentation page are suggesting me what to do in order to upgrade Docker. The only suggestion is to perform CTRL+C and stay with version 1.7.1.

**Comment by cpuguy83** [comment]
Yes, this is just plain wrong.
`apt-get update && apt-get install docker-engine` would be the way to upgrade on ubuntu.
This is assuming you are using the `docker-engine` package and not `lxc-docker`.

**Comment by aldobongio** [comment]
According to the following commands, it seems that I'm using `lxc-docker`. And I'm using it because of the old `curl -sSL https://get.docker.com/ubuntu/ | sudo sh` that I used when I first installed Docker 1.7.1 following the official documentation.

    ubuntu@server:~$ dpkg -s lxc-docker
    Package: lxc-docker
    Status: install ok installed
    Priority: extra
    Section: default
    Installed-Size: 0
    Maintainer: support@docker.com
    Architecture: amd64
    Version: 1.7.1
    Depends: lxc-docker-1.7.1
    Description: Linux container runtime
     Docker complements LXC with a high-level API which operates at the process
     level. It runs unix processes with strong guarantees of isolation and
     repeatability across servers.
     Docker is a great building block for automating distributed systems:
     large-scale web deployments, database clusters, continuous deployment systems,
     private PaaS, service-oriented architectures, etc.
    License: Apache-2.0
    Vendor: none
    Homepage: https://www.docker.com/

    ubuntu@server:~$ dpkg -s docker-machine
    dpkg-query: package 'docker-machine' is not installed and no information is available
    Use dpkg --info (= dpkg-deb --info) to examine archive files,
    and dpkg --contents (= dpkg-deb --contents) to list their contents.

Retrying to execute the old installation script seems to demonstrate my point:

    curl -sSL https://get.docker.com/ubuntu/ | sudo sh
    ...
    lxc-docker is already the newest version.
    0 upgraded, 0 newly installed, 0 to remove and 75 not upgraded.

**Comment by cpuguy83** [comment]
Yes, you'd have to `apt-get install lxc-docker-<version>`.
But in any case, i would remove `lxc-docker` and install `docker-engine`. You'd have to replace your `/etc/apt/sources.list.d/docker` with the one pointing to the new repos..
This is b/c the lxc-docker package is deprecated.

**Comment by thaJeztah** [comment]
(Please note that the `https://get.docker.com/ubuntu` script is not recommended for installation, because that will only perform a minimal installation, and not install the packages needed to run aufs)

We're actually in the middle of rewriting the documentation, to add more info on removing the previous installation, and repo's and manually adding the new repo; see https://github.com/docker/docker/pull/16662

We welcome feedback, so if you think something is missing in that PR, feel free to comment there!

**Comment by aditirajagopal** [comment]
ping @thaJeztah - can this be closed?

**Comment by thaJeztah** [comment]
Yes, I think so; the documentation has updated since, and now describes updating with `apt-get`;
https://docs.docker.com/engine/installation/ubuntulinux/#upgrade-docker

Thanks @aditirajagopal (and thanks @aldobongio for reporting)
