### ISSUE TITLE
commit does not finish

### ISSUE THREAD

**Issue by ikitayama** [docker/docker#16715]
$ docker commit on Fedora 23 aarch64 does not finish, daemon just leaves a message below:

INFO[4813] POST /v1.20/commit?author=&comment=&container=11b82&repo=itaru%2Farm64-vivid&tag=

Any other logs to look at to understand this issue?

**Comment by ikitayama** [comment]
docker version:
Client:
 Version:      1.8.2-fc23
 API version:  1.20
 Package Version: docker-1.8.2-2.gitd449443.fc23.aarch64
 Go version:   go1.4.2 gccgo (GCC) 5.1.1 20150618 (Red Hat 5.1.1-4)
 Git commit:   8a838c0-dirty
 Built:        Wed Sep 16 09:42:34 UTC 2015
 OS/Arch:      linux/arm64

Server:
 Version:      1.8.2-fc23
 API version:  1.20
 Package Version: 
 Go version:   go1.4.2 gccgo (GCC) 5.1.1 20150618 (Red Hat 5.1.1-4)
 Git commit:   8a838c0-dirty
 Built:        Wed Sep 16 09:42:34 UTC 2015
 OS/Arch:      linux/arm64

docker info:
Containers: 36
Images: 37
Storage Driver: devicemapper
 Pool Name: docker-8:4-1835115-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 33.61 GB
 Data Space Total: 107.4 GB
 Data Space Available: 73.76 GB
 Metadata Space Used: 28.26 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.119 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107 (2015-09-05)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.0-rc5+
Operating System: Fedora 23 (Twenty Three)
CPUs: 8
Total Memory: 31.34 GiB
Name: r2-a21
ID: 7IB5:NDCH:OPIJ:Q2ZD:CHYK:3QLY:YCJ4:Y35I:BBIK:IQD6:JDGW:ZSLD
Username: itaru
Registry: https://index.docker.io/v1/

uname -a:
Linux r2-a21 4.2.0-rc5+ #1 SMP Mon Sep 28 06:10:43 EDT 2015 aarch64 aarch64 aarch64 GNU/Linux

Provide additional environment details (AWS, VirtualBox, physical, etc.):

Observed on X-Gene, aarch64.

List the steps to reproduce the issue:
1. Issue docker commit against a particular commit 
2.
3.

Describe the results you received:
It does not finish.

Describe the results you expected:
It should finish with a message.

Provide additional info you think is important:

**Comment by cpuguy83** [comment]
This will be difficult to solve, since you are on ARM and on an unreleased kernel version, and using gccgo.

**Comment by ikitayama** [comment]
I'll ask the package maintainer when they'll switch to golang.

**Comment by thaJeztah** [comment]
I'll close this issue for now, but feel free to comment after I've closed

**Comment by ikitayama** [comment]
Just wanted to let the Community know, using the docker aarch64 packages as listed 
here (Go 1.5 based build):

http://arm.koji.fedoraproject.org/koji/taskinfo?taskID=3257125

, I am again able to commit to the repository. Tested on real hardware APM Mustang.
