### ISSUE TITLE
Website: order of remote API versions sorted incorrectly

### ISSUE THREAD

**Issue by charleswhchan** [docker/docker#16712]
When looking at the [remote API](https://docs.docker.com/reference/api/docker_remote_api_v1.20/), I noticed the links for the versions is sorted incorrectly:
v1.20 --> v1.21 --> v1.19

![screen shot 2015-10-01 at 8 32 38 pm](https://cloud.githubusercontent.com/assets/679475/10239004/b2adfcc8-687b-11e5-9480-e897eca64f6e.png)

Tried looking at the docs in Github, but not sure where this resides?

**Comment by MHBauer** [comment]
dup of  #15810, resolved by #15843

**Comment by vdemeester** [comment]
@MHBauer oh yeah, I should have check the master version of the docs, thanks :wink: 
@charleswhchan gonna close this as it's already fix and will *land* next update of docs.docker.com I guess :wink:

**Comment by charleswhchan** [comment]
Thanks.
