### ISSUE TITLE
images name and tag will be none when save/load many images.

### ISSUE THREAD

**Issue by xiaohui** [docker/docker#16711]
I wanna get some images from remote host, I run `docker save -o k8s.tar.gz <ImageID1> <ImageID2> <ImageID3>` , then I download it from remote host and load to my localhost with `docker load -i k8s.tar.gz`, and the image name and tag was gone.

docker version and docker info on the remote host:
>
 Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

>
Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64
> 
Containers: 7
Images: 53
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 67
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-63-generic
Operating System: Ubuntu 14.04 LTS
CPUs: 2
Total Memory: 3.861 GiB
Name: 10-11-4-24
ID: DES2:DZVT:VJCF:YTFA:WVXL:B6HU:VSX2:7XYX:EUGY:ECFD:P2QB:U6ZI
WARNING: No swap limit support

docker version and info on localhost:
>
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 19:47:52 UTC 2015
 OS/Arch:      darwin/amd64
>
Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64
>
Containers: 0
Images: 16
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 16
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.1 (TCL 6.3); master : 7f12e95 - Thu Aug 13 03:24:56 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: k8s
ID: ZRUE:QRNN:PHI4:N45S:GWNZ:XQZD:KMLH:OZFD:DYPW:3IZ4:VFNU:GU25
Debug mode (server): true
File Descriptors: 9
Goroutines: 17
System Time: 2015-10-02T02:43:19.400898453Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: xiaohui
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox

**Comment by cpuguy83** [comment]
Hello, this is a dup of #10592
A PR to fix this is here: #15263
