### ISSUE TITLE
Meteor Docker

### ISSUE THREAD

**Issue by dominicarrojado** [docker/docker#16719]
I'm new to docker.. Can someone please give me a full documentation on how to dockerize meteor? I did my research and it just doesn't work. I'm stuck at running my meteor app in local. Can someone help? 
docker run -d \
    -e ROOT_URL=http://yourapp.com \
    -e MONGO_URL=mongodb://url \
    -e MONGO_OPLOG_URL=mongodb://oplog_url \
    -v /mybundle_dir:/bundle \
    -p 8080:80 \
    meteorhacks/meteord:base

can someone supply those with the right urls from running it in local? When I try to run it gives a long ID, but when I check docker ps -a it says it exited. So my meteor app didn't run.. Hope someone will shed some light. Thank you!

**Comment by cpuguy83** [comment]
Hello,

Would be happy to help, however this is not the right forum for this kind of inquiry.
I would like to invite you to our docker-user mailing list, or #docker on IRC to discuss.

Thanks!
