### ISSUE TITLE
SECURITY: Docker versions 1.8.1 and 1.8.2 does not send authentication header while pushing

### ISSUE THREAD

**Issue by ferrix** [docker/docker#16728]
When following the documentation in https://docs.docker.com/registry/nginx/, the user will end up getting a 401 response when trying to push images using 1.8.1 or 1.8.2 versions of the client. This has been verified with both Linux and OS X with docker-machine, not that it matters. The registry in question is 2.1.1. When peeking into the nginx logs, the flaw is evident:

    172.31.24.120 - ferrix [02/Oct/2015:15:30:44 +0000] "POST /v2/flower/blobs/uploads/ HTTP/1.1" 202 0 "-" "docker/1.8.2 go/go1.4.2 git-commit/0a8c2e3 kernel/4.0.9-boot2docker os/linux arch/amd64" "188.127.204.162"
    172.31.24.120 - - [02/Oct/2015:15:30:45 +0000] "PATCH /v2/flower/blobs/uploads/c23b91f6-0487-4513-9ba4-09a673660b8e?_state=kcAPSJKxisE_MvKyWcu4Jy1TdQOaBoZlydWvGMDlcLV7Ik5hbWUiOiJzaWdydW4tZnJvbnQiLCJVVUlEIjoiYzIzYjkxZjYtMDQ4Ny00NTEzLTliYTQtMDlhNjczNjYwYjhlIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE1LTEwLTAyVDE1OjMwOjQ0LjU1ODg2NzA5OFoifQ%3D%3D HTTP/1.1" 202 0 "-" "docker/1.8.2 go/go1.4.2 git-commit/0a8c2e3 kernel/4.0.9-boot2docker os/linux arch/amd64" "188.127.204.162"
    172.31.24.120 - - [02/Oct/2015:15:30:45 +0000] "PUT /v2/flower/blobs/uploads/c23b91f6-0487-4513-9ba4-09a673660b8e?_state=XzUfHs_m1Vkk3q8mGTctoxH0K7hgKr56nzz8wG8KYCp7Ik5hbWUiOiJzaWdydW4tZnJvbnQiLCJVVUlEIjoiYzIzYjkxZjYtMDQ4Ny00NTEzLTliYTQtMDlhNjczNjYwYjhlIiwiT2Zmc2V0IjozMiwiU3RhcnRlZEF0IjoiMjAxNS0xMC0wMlQxNTozMDo0NFoifQ%3D%3D&digest=sha256%3Aa3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4 HTTP/1.1" 401 194 "-" "docker/1.8.2 go/go1.4.2 git-commit/0a8c2e3 kernel/4.0.9-boot2docker os/linux arch/amd64" "188.127.204.162"

The third column in nginx logs is the authenticated user and the latter two lines have no such thing. This snippet from my logs is from a phase where I worked around PATCH requests being bounced and allowed them explicitly without authentication.

To try this out, modify the basic authentication lines in the example nginx configuration as follows:

    limit_except PUT PATCH {
      auth_basic "INSECURE DOCKER";
      auth_basic_user_file /etc/nginx/conf.d/htpasswd;
    }

After this, pushing will start working again. This renders the server *very* vulnerable, for anything else that may be done without authorization through PUT and PATCH methods. According to spec, manifests don't even have POST method, so manifests will become writable to anyone. It is worth it to check whether or not that endpoint is equally broken.

### Most likely the registry is broken as well

Since this flaw has not been noticed without nginx, it is likely that the registry server does not expect authentication either for PUT and PATCH requests for blobs.

**Comment by ferrix** [comment]
Ping @cpuguy83

**Comment by ferrix** [comment]
I am thinking #16677 is another user reproducing the same problem.

**Comment by dmp42** [comment]
ping @ferrix 
Can you provide your entire nginx config, and confirm you followed https://github.com/docker/distribution/blob/master/docs/nginx.md step by step without modification and were able to push succesfully?

Remember that you need to `docker login`. There is no reason to disable authentication for any method.

**Comment by ferrix** [comment]
The exception there was only to prove the result and show that client does
not provide credentials. You should have a look at your logs to see the
credentials are there for all requests.

My configuration is exactly like the documents say. This configuration
worked until 1.8 client and revert to 1.7 resolved this.
2.10.2015 8.03 ip. "Olivier Gambier" <notifications@github.com> kirjoitti:

**Comment by dmp42** [comment]
@ferrix I ran the doc step by step with docker 1.8.2 with no issue.
Can you confirm you did explicitly `docker login myregistry:port` and that you tested exactly what's in the doc?
If so, please copy your complete configuration plus the docker daemon logs showing both the login and the failed push.

Thanks.

**Comment by ferrix** [comment]
I think it may have been a problem with the scheme and 1.8.3 upgrade.
