### ISSUE TITLE
TestExecStartFails is broken on Windows

### ISSUE THREAD

**Issue by icecrime** [docker/docker#16738]
See [this log](https://jenkins.dockerproject.org/job/Windows-PRs/14229/console) for example:

```
FAIL: docker_cli_exec_test.go:616: DockerSuite.TestExecStartFails

docker_cli_exec_test.go:624:
    c.Assert(out, checker.Contains, "executable file not found")
... value string = ""
... substring string = "executable file not found"
```

**Comment by icecrime** [comment]
Ping @jhowardmsft: any hints?

**Comment by mavenugo** [comment]
@icecrime i saw this failure even for Janky and experimental today.
but after a rebase and rerun, I didnt see it again. FYI.

**Comment by jhowardmsft** [comment]
Yeah, I've seen this all week. Windows Jenkins was pretty much out from lunchtime last Friday until either Wednesday or yesterday. Since coming back, I've noticed this test pretty consistently failing. I was going to take a look at what might have changed, but haven't had a chance.

**Comment by cpuguy83** [comment]
It's just broken in general, no?

**Comment by MHBauer** [comment]
It is broken in general.
```
```

**Comment by jhowardmsft** [comment]
I'm sure there's something deeper going on here to cause this to start failing in the past week. It was a reliable test before. I will dig in over the weekend (hopefully)

**Comment by mavenugo** [comment]
now am seeing the failure only in windows.
https://github.com/docker/docker/pull/16718

**Comment by vdemeester** [comment]
Related to (and almost duplicates) #16598

**Comment by mavenugo** [comment]
Failed in janky again : https://jenkins.dockerproject.org/job/Docker-PRs/17172/console

**Comment by LK4D4** [comment]
@MHBauer seems to work for me. Do you use remote daemon?

**Comment by MHBauer** [comment]
@LK4D4 yes I am using a remote daemon. Is this not supported with this test?

**Comment by LK4D4** [comment]
@MHBauer It is of course, just seems like it's easily reproduced with remote daemon. Seems like we closing something prematurely. @cpuguy83 could know more.

**Comment by cpuguy83** [comment]
It's easily reproducible for me with a Linux daemon over a unix socket.
Within 5-10 times I get the failure, but only when _not_ using `-t`.
I also see this problem in 1.8.2...

**Comment by LK4D4** [comment]
@cpuguy83 Probably `stdcopy` problem then?

**Comment by jhowardmsft** [comment]
FWIW I left this test running in a loop for a few hours here (from Windows to a remote Linux daemon) and didn't see any failures.

**Comment by cpuguy83** [comment]
@LK4D4 Not sure.
I can confirm the daemon logs always shows the error it's just not always making it to the client... however I did notice that 100% of the time, when it doesn't make it to the client, the daemon logs are slightly different: https://github.com/docker/docker/issues/16598#issuecomment-145558865

**Comment by LK4D4** [comment]
@cpuguy83 Indeed stdcopy works between daemon and client when -t isn't specified :)

**Comment by cpuguy83** [comment]
@LK4D4 Yep, you're right.

**Comment by cpuguy83** [comment]
opencontainers/runc#316
