### ISSUE TITLE
memory limit violated 

### ISSUE THREAD

**Issue by neda824** [docker/docker#16732]
Hello all,

I am running an application on a docker container with 128MB memory allocated to it (using -m 128m command). By default there will be 128 MB swap space available for the container. My application to run on the container requires 256 MB space. So 128 MB of the swap space should be used. When I first run the application, things are as expected and 128 MB of RAM + 128 MB swap is used (ref to memory.stat). As I access this data it seems like the kernel is giving more and more memory to the container without docker or cgroup being aware of!!! so after a few runs I see 128 MB RAM being used and very small swap usage in memory.stat (23101440 bytes). Even when running docker stats I see the limit for memory as 128MB and about 100% usage of RAM. However, when checking top command in host machine 256MB RAM is residing on host RAM and no swap in/out is being performed. This is very strange and seems like kernel is not respecting cgroup limits as the pages (originally stored on the swap space) are swapped back in to the RAM. Greatly appreciate any comments or help.

Thanks,
Neda

**Comment by cpuguy83** [comment]
Please provide the requested Gordon requested, also if you can give some real numbers (or real-ish) it will make the issue a bit easier to read.

Thanks!

**Comment by neda824** [comment]
Hello Brian,

Thanks for your email. I will try to make an easier application to be
easier to regenerate. Sure I will provide the real numbers.


Thanks


Best Regards,
Neda Nasiriani

**Comment by neda824** [comment]
My docker version is as follows:
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64

my kernel version is:
3.13.0-61-generic

Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty

**Comment by LK4D4** [comment]
Going to close for now, because wasn't reported since and probably is kernel issue. Feel free to reopen if problem still persists.
