### ISSUE TITLE
In documentation, COPY is said to not care about timestamps

### ISSUE THREAD

**Issue by vincentbernat** [docker/docker#16743]
Hey!

In [documentation](https://docs.docker.com/articles/dockerfile_best-practices/#build-cache):

> For the ADD and COPY instructions, the contents of the file(s) in the image are examined and a checksum is calculated for each file. The last-modified and last-accessed times of the file(s) are not considered in these checksums. During the cache lookup, the checksum is compared against the checksum in the existing images. If anything has changed in the file(s), such as the contents and metadata, then the cache is invalidated.

However, when using something like:

```
FROM ubuntu
COPY ./somefile /tmp/somefile
```

Touching `somefile` will invalidate the cache.

**Comment by vincentbernat** [comment]
Or maybe the documentation is inconsistent. The last sentence is about metadata.

**Comment by thaJeztah** [comment]
Are you on Docker 1.8.x? This was added in docker 1.8.0 via PR https://github.com/docker/docker/pull/12031. I'll try and see if I can reproduce

**Comment by thaJeztah** [comment]
Hm, I'm unable to reproduce this :/ could you provide some more info on your setup?

**Comment by vincentbernat** [comment]
OK, I am in Docker 1.7.1 and didn't find anything relevant in the changes or issues. Sorry.

**Comment by thaJeztah** [comment]
No problem, happy to hear it's not a bug :-)
