### ISSUE TITLE
New command: docker wait-ready $CONTAINER

### ISSUE THREAD

**Issue by elgalu** [docker/docker#16754]
### Problems:

1. When creating a container in daemon mode `docker run -d` the prompt is returned immediately but that doesn't mean the container finished starting.

2. There is no best practice on performing active waiting 

### Solution

a. Add `docker run -d` cli option `--wait-ready=true` to specify that it should hold the shell prompt until the container finished starting. Non-breaking change, defaults to false. How it knows it finished starting? keep reading.

b. Add docker build command `WAIT_CMD` that works similarly to 'CMD' or `ENTRYPOINT` in the sense that should be used to specify a shell script command but this time to specify what to execute when the user wants to do active waiting on the container to start. Example of active wait scripts: [xvfb](https://github.com/elgalu/docker-selenium/blob/95bd73db327a8b6ac1717d524f180b1d95890a6d/xvfb/bin/wait-xvfb.sh#L7) and [selenium](https://github.com/elgalu/docker-selenium/blob/95bd73db327a8b6ac1717d524f180b1d95890a6d/selenium-hub/bin/wait-selenium-hub.sh#L17). It could also be added some default simply wait for HTTP 200 on some port inside the cotainer like https://github.com/aanand/docker-wait tries to solve. Other common use cases are, to wait for the creation of a file like certain scripts use to communicate they are done, e.g. [Sauce Labs - Sauce Connect](https://github.com/elgalu/docker-selenium/blob/95bd73db327a8b6ac1717d524f180b1d95890a6d/saucelabs/bin/start-saucelabs.sh#L50)

c. Add docker run command `wait-ready` or similar (docker wait is already taken) that works the same as `docker run --wait-ready=true` but useful after the container has already being created. It can take a cli argument `--timeout=30s` which allows to avoid blocking forever. If the wait command doesn't return `0` success it will keep retrying every 50ms or some default until the active wait script specified through the new build command `WAIT_CMD` succeed or simply return an error exit code if it fails after 30 seconds as in the current example.

    docker wait-ready $CONTAINER --timeout=30s

d. Add `docker run` cli option `--timeout=30s` that allows to specify up to how long it will wait in order to avoid blocking forever. Time syntax can be the same as bash [timeout](https://www.gnu.org/software/coreutils/manual/html_node/timeout-invocation.html) command.

e. Avoid reinventing the wheel providing common use cases via a docker build `WAIT_MACRO` instruction, similar to `WAIT_CMD` but instead of a command it provides the common use case, list:

Wait for a file to exist:

    WAIT_MACRO file-exists:/tmp/ready.txt

Wait for the container log output to contain certain text. 

    WAIT_MACRO stdout-has-content:"Selenium is ready"

Wait for a TCP port to be listening

    WAIT_MACRO tcp:8080

Wait for an HTTP/HTTPS to be listening and be responde 200 OK

    WAIT_MACRO http-200:8080

The advantage of providing these default macros is that docker maintainers can start using them without adding more scripting to their containers, and through the cli they don't even need to touch the Dockerfile to start enjoying this feature.

f. Implement the same `WAIT_MACRO` functionality via docker cli, e.g.

    docker wait-ready $CONTAINER --timeout=30s --wait-macro=tcp:8080

a.k.a. health check

To improve the reasoning behind this feature request take a look at https://github.com/Supervisor/supervisor/issues/584

**Comment by duglin** [comment]
I think you can get similar net result by using:
```
docker inspect -f ""{{.State.Status}" [conainerID]
```
and then just write a script that checks for it to be in the desired state.

**Comment by elgalu** [comment]
@duglin I already write the scripts what check for the desired state, the idea of this feature request is to standardize it a bit.

**Comment by duglin** [comment]
https://github.com/docker/docker/pull/13140   :-(

**Comment by elgalu** [comment]
;)
