### ISSUE TITLE
Access docker in Windows using Putty 

### ISSUE THREAD

**Issue by visumagic** [docker/docker#16760]
I am not able to login through Putty. I followed the steps mentioned in following manual. 

https://docs.docker.com/installation/windows/

```
login as: docker
Server refused our key
docker@192.168.99.100's password:
```

**Comment by thaJeztah** [comment]
Have you taken the steps described in [Login with PUTTY instead of using the CMD](https://docs.docker.com/installation/windows/#login-with-putty-instead-of-using-the-cmd) to convert the keys?

**Comment by thaJeztah** [comment]
Oh! I see that page of the documentation contains the old path of the private key; this has been fixed in the repository, but not yet published on the docs website;

Could you try with the [updated instructions](https://github.com/docker/docker/blob/master/docs/installation/windows.md#login-with-putty-instead-of-using-the-cmd) ?

**Comment by vassilvk** [comment]
I am having the same issue. Windows 8.1.

The updated instructions are a bit confusing as they refer to two places where the keys are supposed to be: `%USERPROFILE%\.ssh` and `%USERPROFILE%\.docker\machine\machines\<name_of_your_machine>`.

Not sure which one is the correct one, but after a fresh install of Docker, I had no certs and no keys in neither of these locations.

I regenerated the keys using `docker-machine regenerate-certs default`.
This generated new keys in `%USERPROFILE%\.docker\machine\machines\default`.
I found two keys: `key.pem` and `cerver-key.pem`. I used puttygen to convert these to *.ppk and then attempted to connect PuTTY to my running `default` VM with each of the keys, but I invariably got back:
```
Using username "docker".
Server refused our key
docker@192.168.99.100's password:
```

Any help would be greatly appreciated.
Vassil

**Comment by thaJeztah** [comment]
@vassilvk I think there's an id_rsa file in there, could you try with that one?

**Comment by vassilvk** [comment]
Nice! This worked :)

Thank you so much, theJeztah!

**Comment by thaJeztah** [comment]
@vassilvk so, I agree that this needs some improvement to the docs, to explain *which* file contains the key. Are you interested in contributing and creating a pull-request, or do you want a maintainer to take care of that?

**Comment by visumagic** [comment]
It worked .. Please update the documentation.

**Comment by vassilvk** [comment]
Yes, @thaJeztah, I will gladly help.

**Comment by thaJeztah** [comment]
@vassilvk the documentation is in this repository, and can be found here: https://github.com/docker/docker/blob/master/docs/installation/windows.md

The documentation is generated from the Markdown files, and you can find a short description on how to test the generated docs in this readme: https://github.com/docker/docker/blob/master/docs/README.md

A more extensive guide to contributing can be found in our contributing guide, which contains a lot of useful information: http://docs.docker.com/project/who-written-for/

Let us know if you need help, and thanks so much in advance for contributing!

**Comment by s093294** [comment]
Just did a PR https://github.com/docker/docker/pull/17941 fixing the path.

**Comment by justechn** [comment]
Hey guys, I am trying to do the same thing, but the instructions are confusing. In the first paragraph it says to use the key in %USERPROFILE%\.ssh, but on my machine I don't have a key in that directory, I have a single file called known_hosts

But then in step one it says to load a file from %USERPROFILE%\.docker\machine\machines\<name_of_your_machine>\id_rsa 

So which is it?

**Comment by thaJeztah** [comment]
@justechn the second one, so looks like we missed that line; are you interested in opening a PR?
