### ISSUE TITLE
Docker Quickstart Terminal fails to start due to multiple directory search matches

### ISSUE THREAD

**Issue by erictune** [docker/docker#16768]
Symptom: Docker Quickstart Terminal prints `/bin/bash: /bin/bash: cannot execute binary file`

Setting: Installing DockerToolbox-1.8.2c.pkg on OS X 10.10.5 (14F27) on a new MacBook.

Root cause:

- `/Applications/Docker/Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh` runs `dscl /Search -read /Users/$USER UserShell` to determine current user's login shell.
- On my laptop, that command returns two lines of results, viz: 
```console
$ dscl /Search -read /Users/$USER UserShell
UserShell: /bin/bash
UserShell: /bin/bash
```
- This is apparently intentional in my corporate environment, as one ldap entry handles networked login and the other handles login when not connected to the corporate environment.   

I have no idea if this is a common problem or unique to me.  My fix was this:
```patch
--- /Applications/Docker/Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh	2015-09-16 17:51:08.000000000 -0700
+++ ./start.sh	2015-10-05 09:36:22.000000000 -0700
@@ -56,7 +56,7 @@
 
 eval $($DOCKER_MACHINE env $VM --shell=bash)
 
-USER_SHELL=$(dscl /Search -read /Users/$USER UserShell | awk '{print $2}')
+USER_SHELL=$(dscl /Search -read /Users/$USER UserShell | awk '{print $2}' | head -1)
 if [ "$USER_SHELL" = "/bin/bash" ] || [ "$USER_SHELL" = "/bin/zsh" ] || [ "$USER_SHELL" = "/bin/sh" ]; then
   $USER_SHELL --login
 else
```

**Comment by phemmer** [comment]
This was reported in #16479, which is tracked upstream by https://github.com/docker/toolbox/issues/210, and a fix was merged in https://github.com/docker/toolbox/pull/211

**Comment by tjwudi** [comment]
Yeah, it's fixed. I found it confusing too. Anyway, the fix is rolling out today. cheers! :)

**Comment by erictune** [comment]
awesome, thanks.
