### ISSUE TITLE
Terrible `docker rmi` performance

### ISSUE THREAD

**Issue by icecrime** [docker/docker#16771]
Currently, a daemon with >50 images takes a ridiculous amount of time to honor a single `rmi` request.

After investigation, the root cause of the issue is [this line](https://github.com/docker/docker/blob/ec1d8d7f2a8f563deb61df2b35aa8a9d6a07c3e2/daemon/image_delete.go#L282). The `HasChildren` function is incredibly complex: it calls into [`graph.ByParent()`](https://github.com/docker/docker/blob/ec1d8d7f2a8f563deb61df2b35aa8a9d6a07c3e2/graph/graph.go#L391) that walks the entire graph just for the sake of determining if an image has children.

Having a "fast-exit" (e.g., stop the loop when a first children is found) won't solve the most common case. We should look into maybe removing that `ByParent()` function, and maintain a reference count for each graph entry such as delete would fail immediately unless the counter is down to 0.

I would love to fix this for 1.9.0 but still haven't found the time to do it myself :-( Ping @LK4D4 @runcom if interested!

PS: the issue is easily reproduced by doing a `docker pull --all-tags` on `ubuntu` or `debian`.

**Comment by runcom** [comment]
I feel the ref count alone won't solve this performance problem, I implemented a basic ref count to be used instead of looping the whole idIndex but the only gain on my laptop was 1 sec (was 3 secs before w/o the hash map as a ref counter and docker compiled with `-race`).
@icecrime are you using overlay?
By profiling docker:
```
1.09s of 1.39s total (78.42%)
Showing top 10 nodes out of 142 (cum >= 0.05s)
      flat  flat%   sum%        cum   cum%
     0.81s 58.27% 58.27%      0.84s 60.43%  syscall.Syscall
     0.14s 10.07% 68.35%      0.14s 10.07%  [docker]
     0.06s  4.32% 72.66%      0.10s  7.19%  runtime.scanobject
     0.02s  1.44% 74.10%      0.02s  1.44%  racecall
     0.01s  0.72% 74.82%      1.05s 75.54%  os.RemoveAll
     0.01s  0.72% 75.54%      0.01s  0.72%  runtime.(*gcWork).put
     0.01s  0.72% 76.26%      0.03s  2.16%  runtime.SetFinalizer
     0.01s  0.72% 76.98%      0.01s  0.72%  runtime.assertI2T2
     0.01s  0.72% 77.70%      0.01s  0.72%  runtime.cas
     0.01s  0.72% 78.42%      0.05s  3.60%  runtime.concatstrings
```

**Comment by LK4D4** [comment]
@runcom When I profiled stuff it spend most time in `HasParent` func.

**Comment by runcom** [comment]
@LK4D4 fair, having a ref counter instead of walking the whole graph improved only 1 sec on my system, I'll look if I did something wrong then..

**Comment by LK4D4** [comment]
@runcom You should try some more intense removing maybe. 3 seconds sounds like too fast to have enough profiling data :)

**Comment by icecrime** [comment]
@runcom Thanks for the input! Do you rebuild the refcount at each `rmi` call, or are you caching and updating as time goes?

**Comment by unclejack** [comment]
@icecrime @LK4D4 Perhaps it could be benchmarked?

**Comment by runcom** [comment]
@icecrime cached and updated

**Comment by icecrime** [comment]
@runcom Such disappoint, I thought this would be enough :cry: Thanks though!

**Comment by thedrow** [comment]
Isn't one second less better than nothing, at least for now?

**Comment by LK4D4** [comment]
@thedrow @runcom @icecrime one second is definitely better. We talking about times like ~30 mins now and 1 sec will became 10 minutes.
