### ISSUE TITLE
Update Configuring Docker Article

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#16770]
The "configuring docker" section is not updated to reflect the new packages, which no longer use /etc/sysconfig/docker on SystemD; https://docs.docker.com/engine/articles/configuring/#configuring-docker-1

Installation articles duplicate a lot of this same content.  Updating this should include fixing that material; we might want to update the installs to link to configuring rather than having a lot of material duplicated all around.

See #16662 for the origination story behind this issue

**Comment by jeffjohnston** [comment]
I have this page fixed so the RHEL/CentOS section is right. However, now that Ubuntu switched to systemd it kind of feels like this would just turn into a Upstart page as there already is a systemd page. I did try to make my section feel like the Ubuntu section even though it does duplicate some work done in the systemd page.

Should I still do a pull request and see what you think?

**Comment by thaJeztah** [comment]
@jeffjohnston yes, please! It's easier for us to look at it and discuss / add suggestions. Thanks in advance!

**Comment by thaJeztah** [comment]
Reopening this, per https://github.com/docker/docker/issues/9889#issuecomment-168379960; the Ubuntu section also needs a mention that newer Ubuntu releases use systemd

**Comment by write2sathyan** [comment]
hello @thaJeztah I am a newbie to docker and working on configuring the private registry... I am unable to use --insecure registry on my rhel 7.2 OS. Here are the details on my config...


$docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64


$docker info
Containers: 11
Images: 80
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-253:4-12897049-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem:
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.289 GB
 Data Space Total: 107.4 GB
 Data Space Available: 6.996 GB
 Metadata Space Used: 5.386 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.142 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-327.4.5.el7.x86_64
Operating System: Red Hat Enterprise Linux Workstation 7.2 (Maipo)
CPUs: 2
Total Memory: 1.954 GiB
Name: xyz
ID: NBC6:F2KA:DJOM:BPDV:G5MF:FNJW:KJCD:TVXU:6LEE:ZU7F:4B5N:PTGY
Username: write2sathyan
Registry: https://index.docker.io/v1/

By default I don't find the below files on my system...

/etc/default/docker
/etc/sysconfig/docker

I manually ran $ echo 'DOCKER_OPTS="--insecure-registry myregistry:5000"' > /etc/default/broker 
And restarted the docker service but still I dont see the docker daemon running on insecure mode.

Are there anyway I would use $DOCKER_OPTS and declare in systemd files?

Looking for your help here....

**Comment by thaJeztah** [comment]
RHEL 7.2 uses systemd; custom options for the daemon should be set by creating a "drop-in" file that overrides the default settings that are set in the systemd docker.service file. See this section for how to do that; https://docs.docker.com/engine/admin/systemd/#custom-docker-daemon-options

**Comment by write2sathyan** [comment]
Hello @thaJeztah 

As you recommended I created a drop-in file under "etc/systemd/system/docker.service.d" however still the docker daemon is starting with just the defaults not with the defined OPTIONS. Please let me know if I am missing anything here...

# cat docker.service
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target docker.socket
Requires=docker.socket

[Service]
Type=notify
EnvironmentFile=-/etc/sysconfig/docker
EnvironmentFile=-/etc/sysconfig/docker-storage
EnvironmentFile=-/etc/sysconfig/docker-network
ExecStart=
ExecStart=/usr/bin/docker daemon -H fd:// --insecure-registry="1.2.3.4:5000"
MountFlags=slave
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity

[Install]
WantedBy=multi-user.target

# pwd
/etc/systemd/system/docker.service.d

After service restart still it works with defaults...

# ps -ef | grep docker
root      8717     1  0 14:40 ?        00:00:00 /usr/bin/docker daemon -H fd://

**Comment by thaJeztah** [comment]
Did you `sudo systemctl daemon-reload` to load the changes?

**Comment by jeffjohnston** [comment]
You can also look at this page which shows a more condensed how-to for Redhat 7.x.

https://docs.docker.com/engine/admin/configuring/

**Comment by write2sathyan** [comment]
Yes I did...

**Comment by write2sathyan** [comment]
Thanks @jeffjohnston and @thaJeztah 

This time it worked !!! Instead of copying the entire file from "/usr/lib/systemd/system".. I just create a docker.conf with the required entries for ExecStart, that kicked-off the custom options while starting. 

$cat docker.conf
[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon -H fd:// --insecure-registry 1.2.3.4:5000"

Thanks
