### ISSUE TITLE
nfs volume mount to mysql docker container inside a ubuntu virtualbox fail 

### ISSUE THREAD

**Issue by phani1kumar** [docker/docker#16797]
I've a nfs file share set-up from freenas server, which I am mounting on a host linux (ubuntu 14.04 server) 
```
mount -t nfs -o proto=tcp xxx.xxx.x.xxx:/mnt/freenas/nmedia /mnt/media
```
On the linux host, I've oracle virtualbox (4.3) installed and I've linux virtualbox  with shared folder from host `/mnt/media` (ubuntu 14.04 server again) in which I've installed kodi-xbmc. On this virtualbox, I've docker with following version details:

# BUG REPORT INFORMATION

```
root@kodixbmc:~# docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```
```
root@kodixbmc:~# docker info
Containers: 1
Images: 15
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 17
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-32-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 1.463 GiB
Name: kodixbmc
ID: XJQY:LP5P:OOE3:5A5J:UJEB:JIDT:IVZT:J4I2:LIMR:NHKU:7KS7:V2AV
WARNING: No swap limit support
```
```
root@kodixbmc:~# uname -a
Linux kodixbmc 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
# Steps to re-produce
I've mounted the shared folder from host into the virtualbox through the following start-up script with entry in `/etc/rc.local`:
```
#!/bin/bash
echo 'Mounting Share folder to /mnt/Share'
`sudo mount -t vboxsf -o uid=$UID,gid=root media /mnt/media`
```
I wanted to run the mysql container (built from https://github.com/sameersbn/docker-mysql) pointing to the `/mnt/media/mysql` through the following run command:
```
docker run -d --privileged --name=mysql -v /mnt/media/mysql/data:/var/lib/mysql -v /mnt/media/mysql/logs:/var/log/mysql mgmttools:443/phani/mysql:latest
```
Mysql demon is not starting, when I tried to connect to the terminal through 
```
docker run -it --privileged --name=mysql -v /mnt/media/mysql/data:/var/lib/mysql -v /mnt/media/mysql/logs:/var/log/mysql mgmttools:443/phani/mysql:latest /bin/bash
```
and then execute the mysqld myself using`/usr/bin/mysqld_safe` it is able to write into the log file and following is the content of the log file
```
151006 11:02:19 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
151006 11:02:19 [Warning] Using unique option prefix key_buffer instead of key_buffer_size is deprecated and will be removed in a future release. Please use the full name instead.
151006 11:02:19 [Warning] Using unique option prefix myisam-recover instead of myisam-recover-options is deprecated and will be removed in a future release. Please use the full name instead.
151006 11:02:19 [Note] Plugin 'FEDERATED' is disabled.
/usr/sbin/mysqld: Table 'mysql.plugin' doesn't exist
151006 11:02:19 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
151006 11:02:19 InnoDB: The InnoDB memory heap is disabled
151006 11:02:19 InnoDB: Mutexes and rw_locks use GCC atomic builtins
151006 11:02:19 InnoDB: Compressed tables use zlib 1.2.8
151006 11:02:19 InnoDB: Using Linux native AIO
151006 11:02:19 InnoDB: Initializing buffer pool, size = 128.0M
151006 11:02:20 InnoDB: Completed initialization of buffer pool
151006 11:02:20  InnoDB: Operating system error number 13 in a file operation.
InnoDB: The error means mysqld does not have the access rights to
InnoDB: the directory.
InnoDB: File name ./ibdata1
InnoDB: File operation call: 'create'.
InnoDB: Cannot continue operation.
151006 11:02:20 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended
```
# Results received
Docker container doesn't get access to the mounted nfs volume

# Results expected
Mysql container is expected to start without any errors pointing to the mounted nfs volume.

----------END REPORT ---------

**Comment by phemmer** [comment]
rc.local typically occurs very late in the boot process. If you're starting docker from an init script, it's likely started before the mount comes up.
You should put the entry in `/etc/fstab`. Most distros ensure all mounts in `/etc/fstab` are up before proceeding with services.

**Comment by phani1kumar** [comment]
@phemmer thank you very much for a quick and prompt response. I've tried to mount the share directory in virtualbox through fstab by many means and failed to achieve that and hence used thie rc.local approach. 
```
media   /mnt/media      vboxsf  rw,auto,uid=0,gid=0,umask=0000  0       0
```
I've tried uid=$UID,gid=root; uid=1000,gid=1000. It always says "an error occurred while mounting press S to skip and M to manually modify"!

Apologies, I am shameless to accept I am coming from a windows background, all I am trying to do is what I've been learning from the experts out here online.

**Comment by phani1kumar** [comment]
Also, I tried to restart the docker service using `service docker restart` before running the docker container, in this case it shall work right? But still having the same problem described in the original post.

**Comment by cpuguy83** [comment]
`InnoDB: The error means mysqld does not have the access rights to`

This looks like the mysql user in the container does not have privileges to access the file.

**Comment by phani1kumar** [comment]
But the same container working well from a windows host (windows 8.1, virtualbox 4.3) --> linux guest (ubuntu 14.04) --> docker. Also, I am running multiple other containers there.

Also, one more question, is there any prescription (I've been searching all over and couldn't find any) of the minimum set of privileges to be given to the share folders to be usable as volume mounts? If you could point me to the right place where I can find this, it would be great.

**Comment by cpuguy83** [comment]
@phani1kumar It comes down purely to linux filesystem permissions.
You need to get the uid of the mysql process and ensure that the file has sufficient permissions for that user to access the file.

See http://linuxcommand.org/lts0070.php

I'm going to close this since it is not a Docker issue, but please feel free to ping me on #docker on IRC, or check out the docker-user mailing list.
Thanks!
