### ISSUE TITLE
archlinux on i686 : Can't build with yaourt/makepkg (compilation error)

### ISSUE THREAD

**Issue by vmonteco** [docker/docker#16808]
Hello!
I'm trying to install the **docker-git** package on my Archlinux (i686), but I get the following when running makepkg :

    $ makepkg
    ==> Making package: docker-git 1:1.9.0.dev.18703.670c488-1 (Tue Oct  6 22:27:42 CEST 2015)
    ==> Checking runtime dependencies...
    ==> Checking buildtime dependencies...
    ==> Retrieving sources...
      -> Updating docker git repo...
    Fetching origin
    remote: Counting objects: 7, done.
    remote: Compressing objects: 100% (4/4), done.
    remote: Total 7 (delta 5), reused 4 (delta 3), pack-reused 0
    Unpacking objects: 100% (7/7), done.
    From https://github.com/docker/docker
     + 382d383...29cbec5 refs/pull/16758/merge -> refs/pull/16758/merge  (forced update)
      -> Found docker.service
      -> Found docker.install
      -> Found docker.conf
    ==> Validating source files with md5sums...
        docker ... Skipped
        docker.service ... Passed
        docker.install ... Passed
        docker.conf ... Passed
    ==> Extracting sources...
      -> Creating working copy of docker git repo...
    Switched to a new branch 'makepkg'
    ==> Starting pkgver()...
    ==> Starting prepare()...
    ==> Removing existing $pkgdir/ directory...
    ==> Starting build()...
    # WARNING! I don't seem to be running in the Docker container.
    # The result of this command might be an incorrect build, and will not be
    #   officially supported.
    #
    # Try this instead: make all
    #
    
    bundles/1.9.0-dev already exists. Removing.
    
    ---> Making bundle: dynbinary (in bundles/1.9.0-dev/dynbinary)
    Created binary: bundles/1.9.0-dev/dynbinary/dockerinit-1.9.0-dev
    Building: bundles/1.9.0-dev/dynbinary/docker-1.9.0-dev
    # _/home/vmonteco/Downloads/docker-git/src/docker/docker
    /usr/lib/go/pkg/tool/linux_386/link: running gcc failed: exit status 1
    /tmp/go-link-183610645/000007.o: In function `__udivdi3':
    (.text+0x8ebc0): multiple definition of `__udivdi3'
    /tmp/go-link-183610645/000003.o:(.text+0x740): first defined here
    collect2: error: ld returned 1 exit status
    
    ==> ERROR: A failure occurred in build().
        Aborting...

Did I forget something? I don't know what the error means.

Also, the docker.service MD5 sum was incorrect and I had to modify the PKGBUILD file.

I also tried `make all` as suggested from the **src/docker** subdirectory but I got :

    $ make all
    docker build -t "docker-dev:makepkg" .
    /bin/sh: docker: command not found
    Makefile:74: recipe for target 'build' failed
    make: *** [build] Error 127

How could I solve this?

**Comment by vdemeester** [comment]
Hi @vmonteco,

`make all` in the docker sources needs docker to work (we build docker inside a docker container :wink:. You want to run `./hack/make.sh [yourtarget]` if you want to build it without docker (as it's done in the `PKGBUILD` - https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=docker-git).

That being said, it's not something maintained by docker, and thus it's not supported here. 
I feel like the right *channel* for it would be the #archlinux irc channel (or the archlinux-aur one if there is one) or on the [docker-git aur page](https://aur4.archlinux.org/packages/docker-git/).

**Comment by thaJeztah** [comment]
@vmonteco I'm going to close this issue because (as @vdemeester explained) this is not a package that's maintained here. Also, for general support questions, please use the #docker IRC channel, forums.docker.com or the Docker Users group on Google, thanks!

Feel free to comment here after I've close the issue

**Comment by flaccid** [comment]
I can't replicate this on x86_64 and don't have an i686 to test with. I recommend ensuring that your packages are up to date including the deps of the package.
