### ISSUE TITLE
hello-world does not run

### ISSUE THREAD

**Issue by tomciopp** [docker/docker#16805]
After installation, I receive the following error when trying to run the hello-world to confirm that docker is running.

    Post http:///var/run/docker.sock/v1.20/containers/create: dial unix /var/run/docker.sock: no such file or directory.
    * Are you trying to connect to a TLS-enabled daemon without TLS?
    * Is your docker daemon up and running?

Running on OSX Yosemite 10.10.5, any idea on how to troubleshoot?

**Comment by cpuguy83** [comment]
Hello, this depends on how you installed docker.
If via Docker Toolbox or docker machine, you'll need to run `eval $(docker-machine env default)` before you run any docker commands.
This will setup your environment to talk to the docker daemon.

Closing as this is not a docker issue.
For support, please see #docker on IRC, the docker-user mailing list, or forums.docker.com

Thanks!
