### ISSUE TITLE
docker commands hang on Ubuntu (vivid) today

### ISSUE THREAD

**Issue by mbruzek** [docker/docker#16819]
# Description of problem: docker commands hang on Ubuntu

`docker version`: Version:      1.9.0-dev  Git commit:   1529343

`docker info`: not available (command hangs)

`uname -a`: Linux warhorse 3.19.0-30-generic #34-Ubuntu SMP Fri Oct 2 22:08:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux  

### Environment details (AWS, VirtualBox, physical, etc.):  
Physical Ubuntu Vivid (15.04) system.  

### How reproduce:  
I am using the docker experimental build on Ubuntu Vivid (15.04).  Today I am not able to complete any docker commands they all hang indefinitely.   

### Steps to Reproduce:
1. `sudo docker -D info`        (hangs)
2. `sudo docker version`       (hangs) 
3. `sudo systemctl restart docker`  
Job for docker.service failed. See "systemctl status docker.service" and "journalctl -xe" for details.

### Actual Results:  
All the docker client commands hang.  The docker daemon issues an error but *is* running.  

### Expected Results:  
The docker commands should work even if they can not contact the daemon.

### Additional info:

This morning I am unable to run any docker commands successfully.  I suspected the docker daemon might have problems so I restarted that service and got a message that it failed:

$ sudo systemctl restart docker
Job for docker.service failed. See "systemctl status docker.service" and "journalctl -xe" for details.

Everything appears to be running checking docker.service and ps shows the docker daemon running.

$ `sudo systemctl status docker.service -l`
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2015-10-07 13:39:25 CDT; 16s ago
     Docs: https://docs.docker.com
  Process: 25371 ExecStart=/usr/bin/docker daemon -H fd:// (code=exited, status=2)
 Main PID: 25371 (code=exited, status=2)

Oct 07 13:37:55 warhorse systemd[1]: Starting Docker Application Container Engine...
Oct 07 13:37:55 warhorse docker[25371]: time="2015-10-07T13:37:55-05:00" level=warning msg="Running experimental build"
Oct 07 13:39:25 warhorse systemd[1]: docker.service start operation timed out. Terminating.
Oct 07 13:39:25 warhorse systemd[1]: docker.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 07 13:39:25 warhorse systemd[1]: Failed to start Docker Application Container Engine.
Oct 07 13:39:25 warhorse systemd[1]: Unit docker.service entered failed state.
Oct 07 13:39:25 warhorse systemd[1]: docker.service failed.

According to syslog the last start of the Docker Application Engine failed.
/var/log/syslog:  
...  
Oct  7 13:37:55 warhorse systemd[1]: docker.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Oct  7 13:37:55 warhorse systemd[1]: Unit docker.service entered failed state.
Oct  7 13:37:55 warhorse systemd[1]: docker.service failed.
Oct  7 13:37:55 warhorse systemd[1]: Stopping Docker Socket for the API. 
Oct  7 13:37:55 warhorse systemd[1]: Starting Docker Socket for the API. 
Oct  7 13:37:55 warhorse systemd[1]: Listening on Docker Socket for the API. 
Oct  7 13:37:55 warhorse systemd[1]: Starting Docker Application Container Engine...
Oct  7 13:37:55 warhorse docker[25371]: time="2015-10-07T13:37:55-05:00" level=warning msg="Running experimental build"
Oct  7 13:39:25 warhorse systemd[1]: docker.service start operation timed out. Terminating.
Oct  7 13:39:25 warhorse systemd[1]: docker.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Oct  7 13:39:25 warhorse systemd[1]: Failed to start Docker Application Container Engine.
Oct  7 13:39:25 warhorse systemd[1]: Unit docker.service entered failed state.
Oct  7 13:39:25 warhorse systemd[1]: docker.service failed.

All docker commands hang for me.  Is there any other file or information you need to diagnose this problem?  Are there any workarounds at this time?

**Comment by mbruzek** [comment]
I fixed the original bug report to follow the format.  Please re-review.

**Comment by mbruzek** [comment]
I see in the error message "INVALIDARGUMENT" so I tried to run the docker daemon manually in the foreground.  `docker daemon` worked but `docker daemon -H fd:\\` does not.
```bash 
# docker daemon 
WARN[0000] Running experimental build                   
INFO[0000] [graphdriver] using prior storage driver "aufs" 
INFO[0000] Option DefaultDriver: bridge                 
INFO[0000] Option DefaultNetwork: bridge                
INFO[0000] Firewalld running: false                     
WARN[0000] Your kernel does not support swap memory limit. 
INFO[0000] Loading containers: start.                   

INFO[0000] Loading containers: done.                    
INFO[0000] Daemon has completed initialization          
INFO[0000] Docker daemon                                 commit=1529343 execdriver=native-0.2 graphdriver=aufs version=1.9.0-dev
INFO[0000] API listen on /var/run/docker.sock           
INFO[0009] GET /v1.21/version                           
^CINFO[0094] Processing signal 'interrupt'                
root@warhorse:/home/mbruzek# docker daemon -H fd://
WARN[0000] Running experimental build                   
FATA[0000] No sockets found  
```

**Comment by nordic-style** [comment]
same for me - fresh installation

**Comment by mbruzek** [comment]
After 2 updates since the original problem was reported, the docker daemon now runs on my system without error.  Someone must have fixed it elsewhere.  Closing the issue.  Thanks!

**Comment by thaJeztah** [comment]
thanks @mbruzek. good to hear it got resolved for you, but feel free reopen if you encounter this again, or have additional information :+1:

**Comment by jaredbroad** [comment]
@mbruzek - I have the same error - same identical system configuration and hanging on the version command, what updates fixed it for you? I've just done a fresh install and get the same bug.

**Comment by mbruzek** [comment]
@jaredbroad - The docker update (delivered via apt-get upgrade) on October 14th 2015 fixed my issue.  I suspect that the version of docker for 16.04 was lagging behind the other releases of the same package and it just caught up in the next update.

I the problem it had everything to do with an invalid argument, I had considered editing the systemd start up file, but the update fixed me before I dug into that.  The key was to figure out the argument that is invalid and either comment it out, or call it's no deprecated version.

It is still running for me, please let me know if you need any specific information from my machine to compare against your machine.

**Comment by jaredbroad** [comment]
Thanks @mbruzek, turned out to be a bad install and then couldnt find my way back to this issue :) I reported and self-closed an issue here with having too many containers: https://github.com/docker/docker/issues/17811#issuecomment-154878019

**Comment by rhalff** [comment]
Had the same issue on update trusty which was fully updated.

Only after a dist-upgrade docker worked again.

Not sure which package was responsible but here is what got upgraded:
```
$ apt-get dist-upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following NEW packages will be installed:
  libdrm-amdgpu1 liboxideqtquick0 linux-headers-3.13.0-77
  linux-headers-3.13.0-77-generic linux-image-3.13.0-77-generic
  linux-image-extra-3.13.0-77-generic python-chardet-whl python-colorama-whl
  python-distlib-whl python-html5lib-whl python-pip-whl python-requests-whl
  python-setuptools-whl python-six-whl python-urllib3-whl python-wheel
The following packages will be upgraded:
  libdrm-dev libdrm-intel1 libdrm-intel1:i386 libdrm-nouveau2
  libdrm-nouveau2:i386 libdrm-radeon1 libdrm-radeon1:i386 libdrm2 libdrm2:i386
  liboxideqt-qmlplugin liboxideqtcore0 linux-generic linux-headers-generic
  linux-image-generic oxideqt-codecs-extra python-pip
16 upgraded, 16 newly installed, 0 to remove and 0 not upgraded.
Need to get 91,1 MB of archives.

```

**Comment by ivoba** [comment]
Same here with `sudo apt-get install docker-engine` on trusty.
After installation docker uses constant cpu and no command finishes.

Installing docker with `curl -fsSL https://get.docker.com/ | sh` made no difference.
Initial docker version shows:

```
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

After starting the service `sudo service docker start` again high cpu usage and no command terminates.

**Comment by rhalff** [comment]
@ivoba you did do a ` apt-get dist-upgrade`? (not just upgrade), because that's what brought things back to normal again for me.

**Comment by thaJeztah** [comment]
@ivoba did you have an older version of docker installed before that? because the high-cpu may be related to the migration to content-addressable storage; see https://github.com/docker/docker/wiki/Engine-v1.10.0-content-addressability-migration

**Comment by ivoba** [comment]
@rhalff yes i did but it had no effect
@thaJeztah yes indeed its an upgrade of docker. so i just have to wait until the "one time hit" terminates, i guess.

**Comment by fterragna** [comment]
I'm also having this issue on a fresh install of Ubuntu 16.04 LTS. @ivoba any luck since February?

**Comment by ivoba** [comment]
@fterragna yes i went for a walk and took a nap and after i got back docker finished the migration and everything was working as usual

**Comment by bgaillard** [comment]
Hi, I also encounter the problem after upgrading Docker from version 1.9 to 1.11 (all Docker commands do not respond). 

@thaJeztah the docker process uses CPU resources so I suppose the migration process is in progress.

I updated docker since several hours now and the docker process still uses CPU. 

Is it possible to have an idea of the progression of this migration (ideally a percentage of the progres) ? If the migration will take too much time I would like to know it.

Thanks

**Comment by bgaillard** [comment]
Ok, the migration process is finished now, it took 8 to 10 hours to complete. Thanks

**Comment by thaJeztah** [comment]
@bgaillard it's not really possible to give a predictable estimation as to how long the migration process takes, so for that reason, no progress is shown.
