### ISSUE TITLE
Unit test case for devmapper hangs for ever  

### ISSUE THREAD

**Issue by harche** [docker/docker#16811]
While trying to run `make test-unit` (or `hack/make.sh test-unit` from inside of dev container) the unit test for devmapper hangs for ever

```
+ go test -test.timeout=60m github.com/docker/docker/daemon/graphdriver/devmapper
time="2015-10-07T06:16:30Z" level=warning msg="Udev sync is not supported. This will lead to unexpected behavior, data loss and errors. For more information, see https://docs.docker.com/reference/commandline/daemon/#daemon-storage-driver-option"
```

System - Ubuntu 15.04 (running inside VirtualBox), X64.

**Comment by thaJeztah** [comment]
Hi @harche, given that this test runs correctly on our CI servers, this doesn't sound like a bug in Docker. Perhaps you can ask for assistance in the #docker-dev IRC channel?

I'll close this issue, but feel free to comment here after I've closed

**Comment by mikebrow** [comment]
https://github.com/boot2docker/boot2docker/pull/483
