### ISSUE TITLE
Possible bug (regarding hardlinks of ADDed files) with storage driver overlayfs 

### ISSUE THREAD

**Issue by Andre-Freitas** [docker/docker#16813]
# BUG REPORT INFORMATION

### My docker Host
```
$ docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): df2f73d-dirty
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): df2f73d-dirty
OS/Arch (server): linux/amd64
```
```
$ docker info
...
Containers: 3
Images: 44
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.7-coreos
Operating System: CoreOS 766.4.0
CPUs: 1
Total Memory: 3.618 GiB
```
```
uname -a
Linux master-pgsql1 4.1.7-coreos #2 SMP Wed Sep 16 22:54:37 UTC 2015 x86_64 Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Linux
```
## Environment details (AWS, VirtualBox, physical, etc.)
GCE instance with CoreOS stable (766.4.0)

### 1ª Step - creating base image
```
docker build --rm -t="teste/ubuntu-base" .
```
with the following files
dockerfile - http://ur1.ca/nxvo0
src/supervisord.conf - http://ur1.ca/nxvod 
src/cron.conf - http://ur1.ca/nxvoi)

### 2º Step - creating base postgresql configuration where i install postgresql and add a few files 
```
docker build --rm -t="teste/postgresql-base-isolated" .
```
with the following files
dockerfile - http://ur1.ca/nxvpe
for each or cronjob they can be empty ones has the problem is hardlinks

### 3º Step - run the above image
```
docker run -it teste/postgresql-base-isolated -n teste
```
## Describe the results you received:

If i run the postgresql-base in docker host above i get various hardlinks for my cron jobs when i should only have 1
```
$ docker exec -it teste bash
# ls -l /var/spool/cron/crontabs/
total 8
-rw------- 12 postgres crontab 90 Oct  1 13:23 postgres
-rw------- 12 root     crontab 70 Oct  6 17:28 root
```
## Provide additional info you think is important:

If i start a docker with this image in a different Storage Driver, for example devicemapper i don't have more that 1 hardlink
```
# ls -l /var/spool/cron/crontabs/
total 8
-rw------- 1 postgres crontab 90 Oct  1 13:23 postgres
-rw------- 1 root     crontab 70 Oct  6 17:28 root
```

**Comment by Andre-Freitas** [comment]
issue updated

**Comment by Andre-Freitas** [comment]
if i use a more recent coreos CoreOS alpha (815.0.0)
```
$ docker info
Containers: 2
Images: 44
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.0-coreos-r1
Operating System: CoreOS 815.0.0
CPUs: 1
Total Memory: 3.618 GiB
Name: master-pgsql1-birmingham-test.c.nice-catbird-486.internal
ID: 7UNB:ONWY:P7W4:2FOD:OG5R:47DO:GHYR:MQ3N:TN3R:KDIG:3WWJ:ODBV

$ docker version 
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   fae4436-dirty
 Built:        Thu Sep 24 08:01:15 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   fae4436-dirty
 Built:        Thu Sep 24 08:01:15 UTC 2015
 OS/Arch:      linux/amd64
```
and if i do docker run -it teste/postgresql-base-isolated -n teste now i have now the correct values 
```
root@f8d6da0ed63e:/var/spool/cron/crontabs# ls -l
total 16
-rw-------. 1 postgres crontab 90 Oct  1 13:23 postgres
-rw-------. 1 root     crontab 70 Oct  6 17:28 root
```
But if i use this image as a base to another dockerfile docker build --rm -t="teste/postgresql-base" . with the dockerfile - http://ur1.ca/nysrx i how have the same problem
```
root@4e959d22ad09:/var/spool/cron/crontabs# ls -l
total 16
-rw-------. 12 postgres crontab 90 Oct  1 13:23 postgres
-rw-------. 12 root     crontab 70 Oct  6 17:28 root
```

**Comment by tonistiigi** [comment]
Overlay graphdriver implementation currently uses hardlinks for joining files over readonly layers.

**Comment by jfoy** [comment]
We've just run into this, too. It looks like classic vixie-cron in containers is simply incompatible with overlayfs. We're exploring cron alternatives.

**Comment by cyphar** [comment]
@Andre-Freitas Can you please post the code **in the tracker**. Url-shorteners and pastes make life harder for people coming from the future (like me).

**Comment by sazo** [comment]
Any update on this one? :)

**Comment by Andre-Freitas** [comment]
I will try to update this issue in next few days after a few more tests.

**Comment by cyphar** [comment]
@Andre-Freitas This isn't a bug. The overlayfs driver uses hardlinks for the "lower" directory in overlayfs to save disk space when splatting an image into a container. As such, you'll get a set of hardlinks to the same inode. If you do something like `touch <the file>` the number of hardlinks will drop to zero.

**Comment by Andre-Freitas** [comment]
@cyphar ok thanks
