### ISSUE TITLE
OS X 10.11  - timed out index.docker.io

### ISSUE THREAD

**Issue by juanjbrown** [docker/docker#16829]
Times out on build or run. 

VirtualBox to 5.0.5 r103020 

Terminal output:

    $ docker-machine create --driver virtualbox default
    Creating VirtualBox VM...
    Creating SSH key...
    Starting VirtualBox VM...
    Starting VM...
    To see how to connect Docker to this machine, run: docker-machine env default
    $ eval $(docker-machine env default)
    $ docker run hello-world
    Unable to find image 'hello-world:latest' locally
    Pulling repository docker.io/library/hello-world
    Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/hello-world/images. You may want to check your internet connection or if you are behind a proxy.

$ docker version

    Client:
     Version:      1.8.2
     API version:  1.20
     Go version:   go1.4.2
     Git commit:   0a8c2e3
     Built:        Thu Sep 10 19:10:10 UTC 2015
     OS/Arch:      darwin/amd64

    Server:
     Version:      1.8.2
     API version:  1.20
     Go version:   go1.4.2
     Git commit:   0a8c2e3
     Built:        Thu Sep 10 19:10:10 UTC 2015
     OS/Arch:      linux/amd64
$ docker info

    Containers: 0
    Images: 0
    Storage Driver: aufs
     Root Dir: /mnt/sda1/var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 0
     Dirperm1 Supported: true
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 4.0.9-boot2docker
    Operating System: Boot2Docker 1.8.2 (TCL 6.4); master : aba6192 - Thu Sep 10 20:58:17 UTC 2015
    CPUs: 1
    Total Memory: 996.2 MiB
    Name: default
    ID: INDA:V46X:P2VC:C2QZ:WRHV:RYZ4:SXRF:6RAR:YUDC:XP45:PJTI:NBZE
    Debug mode (server): true
    File Descriptors: 11
    Goroutines: 16
    System Time: 2015-10-12T15:22:04.149833281Z
    EventsListeners: 0
    Init SHA1: 
    Init Path: /usr/local/bin/docker
    Docker Root Dir: /mnt/sda1/var/lib/docker
    Labels:
     provider=virtualbox
$ uname -a

    Darwin Juans-Macintosh.local 15.0.0 Darwin Kernel Version 15.0.0: Wed Aug 26 16:57:32 PDT 2015; root:xnu-3247.1.106~1/RELEASE_X86_64 x86_64

**Comment by juanjbrown** [comment]
$ docker version

    Client:
     Version:      1.8.2
     API version:  1.20
     Go version:   go1.4.2
     Git commit:   0a8c2e3
     Built:        Thu Sep 10 19:10:10 UTC 2015
     OS/Arch:      darwin/amd64

    Server:
     Version:      1.8.2
     API version:  1.20
     Go version:   go1.4.2
     Git commit:   0a8c2e3
     Built:        Thu Sep 10 19:10:10 UTC 2015
     OS/Arch:      linux/amd64
$ docker info

    Containers: 0
    Images: 0
    Storage Driver: aufs
     Root Dir: /mnt/sda1/var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 0
     Dirperm1 Supported: true
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 4.0.9-boot2docker
    Operating System: Boot2Docker 1.8.2 (TCL 6.4); master : aba6192 - Thu Sep 10 20:58:17 UTC 2015
    CPUs: 1
    Total Memory: 996.2 MiB
    Name: default
    ID: INDA:V46X:P2VC:C2QZ:WRHV:RYZ4:SXRF:6RAR:YUDC:XP45:PJTI:NBZE
    Debug mode (server): true
    File Descriptors: 11
    Goroutines: 16
    System Time: 2015-10-12T15:22:04.149833281Z
    EventsListeners: 0
    Init SHA1: 
    Init Path: /usr/local/bin/docker
    Docker Root Dir: /mnt/sda1/var/lib/docker
    Labels:
     provider=virtualbox
$ uname -a

    Darwin Juans-Macintosh.local 15.0.0 Darwin Kernel Version 15.0.0: Wed Aug 26 16:57:32 PDT 2015; root:xnu-3247.1.106~1/RELEASE_X86_64 x86_64

**Comment by thaJeztah** [comment]
This sounds like a networking issue on your machine (also see the error message: "You may want to check your internet connection or if you are behind a proxy.").

**Comment by jdgiotta** [comment]
I'm having the same problem. This isn't the first image I've pulled.

docker version: 1.8.3
docker info: 
Containers: 1
Images: 25
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 27
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.10-boot2docker
Operating System: Boot2Docker 1.8.3 (TCL 6.4); master : af8b089 - Mon Oct 12 18:56:54 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: MBMO:NNOJ:Q67Y:6YFE:HNW6:WJUV:ZDV6:O3YZ:MH2V:CYCW:VOHX:OPU4
Debug mode (server): true
File Descriptors: 21
Goroutines: 52
System Time: 2015-10-17T21:05:10.476966823Z
EventsListeners: 1
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

uname -a:
Darwin Johns-MacBook-Pro.local 15.0.0 Darwin Kernel Version 15.0.0: Wed Aug 26 16:57:32 PDT 2015; root:xnu-3247.1.106~1/RELEASE_X86_64 x86_64

1. Launch docker cli
2. type docker pull redis
3. Receive the following message:
Using default tag: latest
Pulling repository docker.io/library/redis
Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/redis/images. You may want to check your internet connection or if you are behind a proxy.

**Comment by juanjbrown** [comment]
Thanks. It seems to be a problem with the network I was running it in.

**Comment by juanjbrown** [comment]
The issue got solved when I changed the DNS server to one of Google's

**Comment by thaJeztah** [comment]
Thanks for reporting back @juanjbrown!

**Comment by jdgiotta** [comment]
I ended up re-installing Docker I didn't get to far into installation. Not a big lose.

**Comment by thunderrabbit** [comment]
This fixed it for me:

$ docker-machine restart default      # Restart the environment
$ eval $(docker-machine env default)  # Refresh your environment settings

via http://stackoverflow.com/a/32023104/194309

**Comment by lamnk** [comment]
I can't believe it. Changing the DNS from 4.4.2.2 to Google's 8.8.8.8 solve the issues. Who knows???

Just some context: I removed the old Docker and installed Docker for Mac Beta anew.

**Comment by omouse** [comment]
I'm actually using Google's DNS servers and it still times out when I run `docker run --rm -ti ubuntu:latest /bin/bash`

**Comment by fumi** [comment]
Same here. I have installed Docker for Mac to my new machine today, the docker-compose works well after changing the DNS to 8.8.8.8.

**Comment by throll** [comment]
A reboot also solved the issue in my case.

**Comment by rodionos** [comment]
Changing DNS to 8.8.8.8 fixes the problem.

**Comment by georgehrke** [comment]
I can reproduce this issue on macOS sierra and can confirm that using Google's 8.8.8.8 "fixes" the issue.
I'm sorry, but requiring users to use Google's DNS service is no acceptable solution.

The DNS entry is pretty much the same 😕
<details>
[georgehrke@liberator (14:12:08) ~] dig index.docker.io

; <<>> DiG 9.8.3-P1 <<>> index.docker.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43742
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 4, ADDITIONAL: 1

;; QUESTION SECTION:
;index.docker.io.               IN      A

;; ANSWER SECTION:
index.docker.io.        274     IN      CNAME   elb-io.us-east-1.aws.dckr.io.
elb-io.us-east-1.aws.dckr.io. 171 IN    CNAME   us-east-1-elbio-rm5bon1qaeo4-623296237.us-east-1.elb.amazonaws.com.
us-east-1-elbio-rm5bon1qaeo4-623296237.us-east-1.elb.amazonaws.com. 34 IN A 52.207.178.113
us-east-1-elbio-rm5bon1qaeo4-623296237.us-east-1.elb.amazonaws.com. 34 IN A 54.85.12.131
us-east-1-elbio-rm5bon1qaeo4-623296237.us-east-1.elb.amazonaws.com. 34 IN A 52.73.159.23

;; AUTHORITY SECTION:
us-east-1.elb.amazonaws.com. 36 IN      NS      ns-1793.awsdns-32.co.uk.
us-east-1.elb.amazonaws.com. 36 IN      NS      ns-934.awsdns-52.net.
us-east-1.elb.amazonaws.com. 36 IN      NS      ns-1119.awsdns-11.org.
us-east-1.elb.amazonaws.com. 36 IN      NS      ns-235.awsdns-29.com.

;; ADDITIONAL SECTION:
ns-235.awsdns-29.com.   99578   IN      A       205.251.192.235

;; Query time: 49 msec
;; SERVER: 192.168.178.1#53(192.168.178.1)
;; WHEN: Sat Nov 12 14:12:09 2016
;; MSG SIZE  rcvd: 354

[georgehrke@liberator (14:12:09) ~] dig @8.8.8.8 index.docker.io

; <<>> DiG 9.8.3-P1 <<>> @8.8.8.8 index.docker.io
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 12984
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;index.docker.io.               IN      A

;; ANSWER SECTION:
index.docker.io.        129     IN      CNAME   elb-io.us-east-1.aws.dckr.io.
elb-io.us-east-1.aws.dckr.io. 729 IN    CNAME   us-east-1-elbio-rm5bon1qaeo4-623296237.us-east-1.elb.amazonaws.com.
us-east-1-elbio-rm5bon1qaeo4-623296237.us-east-1.elb.amazonaws.com. 32 IN A 52.207.178.113
us-east-1-elbio-rm5bon1qaeo4-623296237.us-east-1.elb.amazonaws.com. 32 IN A 54.85.12.131
us-east-1-elbio-rm5bon1qaeo4-623296237.us-east-1.elb.amazonaws.com. 32 IN A 52.73.159.23

;; Query time: 52 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sat Nov 12 14:12:11 2016
;; MSG SIZE  rcvd: 201

[georgehrke@liberator (14:12:11) ~] 
</details>

Is `docker pull` talking to other domains than index.docker.io?

**Comment by thaJeztah** [comment]
@georgehrke could you open a new issue in the docker for mac issue tracker? https://github.com/docker/for-mac/issues that way it gets the right attention of the d4m team

**Comment by Rwarlock** [comment]
What worked for me was [changing the DNS to google.](https://developers.google.com/speed/public-dns/docs/using). 

Please make sure that you change the settings in the docker setting as well. 
**Docker -> Settings -> Networks -> DNS Server (Fixed : Check)  -> Apply**
