### ISSUE TITLE
Fail to install new docker-engine package: size mismatch

### ISSUE THREAD

**Issue by fabeschan** [docker/docker#16820]
```
# apt-get install docker-engine
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  aufs-tools cgroup-lite
The following NEW packages will be installed:
  aufs-tools cgroup-lite docker-engine
0 upgraded, 3 newly installed, 0 to remove and 4 not upgraded.
Need to get 5,691 kB/5,787 kB of archives.
After this operation, 28.8 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://apt.dockerproject.org/repo/ ubuntu-trusty/main docker-engine amd64 1.8.2-0~trusty [5,691 kB]
Fetched 5,691 kB in 0s (7,373 kB/s)
E: Failed to fetch https://apt.dockerproject.org/repo/pool/main/d/docker-engine/docker-engine_1.8.2-0~trusty_amd64.deb  Size mismatch

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by Braggy85** [comment]
Hi,

I'm geting the same thing: Ubuntu 3.19.0-15-generic.
Linux kuba 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

I'm following the basic instructions here: 
https://docs.docker.com/installation/ubuntulinux/

Get:1 https://apt.dockerproject.org/repo/ ubuntu-vivid/main docker-engine amd64 1.8.2-0~vivid [5,699 kB]
Fetched 5,697 kB in 2s (2,396 kB/s)
E: Failed to fetch https://apt.dockerproject.org/repo/pool/main/d/docker-engine/docker-engine_1.8.2-0~vivid_amd64.deb  Size mismatch

I assume this is a very very new issue? What else can i provide?

RB

**Comment by ah-taktik** [comment]
Same issue here : 

Trying to install docker on ubuntu :
```
Linux ubuntu-14 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

via this command : 

```
curl -sSL https://get.docker.com/ | sh
```

and get this error : 
```javascript
Reading package lists... Done
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  docker-engine
0 upgraded, 1 newly installed, 0 to remove and 215 not upgraded.
Need to get 5,691 kB of archives.
After this operation, 28.5 MB of additional disk space will be used.
Get:1 https://apt.dockerproject.org/repo/ ubuntu-trusty/main docker-engine amd64 1.8.2-0~trusty [5,691 kB]
Fetched 5,691 kB in 3s (1,445 kB/s)
E: Failed to fetch https://apt.dockerproject.org/repo/pool/main/d/docker-engine/docker-engine_1.8.2-0~trusty_amd64.deb  Size mismatch

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by yathi-naik** [comment]
Seeing the same problem on a fresh AWS box. 

``` Linux ip-10-0-1-124 3.19.0-25-generic #26-Ubuntu SMP Fri Jul 24 21:17:31 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux ```
```curl -sSL https://get.docker.com/ | sh```
```
apparmor is enabled in the kernel and apparmor utils were already installed
+ sudo -E sh -c apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.Kmux1bQwJS --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
gpg: requesting key 2C52609D from hkp server p80.pool.sks-keyservers.net
gpg: key 2C52609D: "Docker Release Tool (releasedocker) <docker@docker.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
+ sudo -E sh -c mkdir -p /etc/apt/sources.list.d
+ sudo -E sh -c echo deb https://apt.dockerproject.org/repo ubuntu-vivid main > /etc/apt/sources.list.d/docker.list
+ sudo -E sh -c sleep 3; apt-get update; apt-get install -y -q docker-engine
Hit http://us-west-1.ec2.archive.ubuntu.com vivid InRelease
Hit http://us-west-1.ec2.archive.ubuntu.com vivid-updates InRelease
Hit http://us-west-1.ec2.archive.ubuntu.com vivid/main Sources
Hit http://us-west-1.ec2.archive.ubuntu.com vivid/universe Sources
Hit http://us-west-1.ec2.archive.ubuntu.com vivid/main amd64 Packages
Hit http://us-west-1.ec2.archive.ubuntu.com vivid/universe amd64 Packages
Hit http://us-west-1.ec2.archive.ubuntu.com vivid/main Translation-en
Hit http://us-west-1.ec2.archive.ubuntu.com vivid/universe Translation-en
Hit http://us-west-1.ec2.archive.ubuntu.com vivid-updates/main Sources
Hit http://us-west-1.ec2.archive.ubuntu.com vivid-updates/universe Sources
Hit http://us-west-1.ec2.archive.ubuntu.com vivid-updates/main amd64 Packages
Hit http://us-west-1.ec2.archive.ubuntu.com vivid-updates/universe amd64 Packages
Hit http://us-west-1.ec2.archive.ubuntu.com vivid-updates/main Translation-en
Hit http://us-west-1.ec2.archive.ubuntu.com vivid-updates/universe Translation-en
Get:1 https://apt.dockerproject.org ubuntu-vivid InRelease
Ign https://apt.dockerproject.org ubuntu-vivid InRelease
Hit https://apt.dockerproject.org ubuntu-vivid Release.gpg
Hit https://apt.dockerproject.org ubuntu-vivid Release
Hit https://apt.dockerproject.org ubuntu-vivid/main amd64 Packages
Get:2 https://apt.dockerproject.org ubuntu-vivid/main Translation-en_US
Get:3 https://apt.dockerproject.org ubuntu-vivid/main Translation-en [162 B]
Get:4 https://apt.dockerproject.org ubuntu-vivid/main Translation-en_US [162 B]
Get:5 https://apt.dockerproject.org ubuntu-vivid/main Translation-en [162 B]
Get:6 https://apt.dockerproject.org ubuntu-vivid/main Translation-en_US [162 B]
Get:7 https://apt.dockerproject.org ubuntu-vivid/main Translation-en [162 B]
Get:8 https://apt.dockerproject.org ubuntu-vivid/main Translation-en_US [162 B]
Get:9 https://apt.dockerproject.org ubuntu-vivid/main Translation-en [162 B]
Get:10 https://apt.dockerproject.org ubuntu-vivid/main Translation-en_US [162 B]
Ign https://apt.dockerproject.org ubuntu-vivid/main Translation-en_US
Get:11 https://apt.dockerproject.org ubuntu-vivid/main Translation-en [162 B]
Ign https://apt.dockerproject.org ubuntu-vivid/main Translation-en
Hit http://security.ubuntu.com vivid-security InRelease
Hit http://security.ubuntu.com vivid-security/main Sources
Hit http://security.ubuntu.com vivid-security/universe Sources
Hit http://security.ubuntu.com vivid-security/main amd64 Packages
Hit http://security.ubuntu.com vivid-security/universe amd64 Packages
Hit http://security.ubuntu.com vivid-security/main Translation-en
Hit http://security.ubuntu.com vivid-security/universe Translation-en
Reading package lists... Done
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  aufs-tools cgroupfs-mount
The following NEW packages will be installed:
  aufs-tools cgroupfs-mount docker-engine
0 upgraded, 3 newly installed, 0 to remove and 58 not upgraded.
Need to get 5,699 kB/5,796 kB of archives.
After this operation, 28.9 MB of additional disk space will be used.
Get:1 https://apt.dockerproject.org/repo/ ubuntu-vivid/main docker-engine amd64 1.8.2-0~vivid [5,699 kB]
Fetched 5,697 kB in 0s (20.6 MB/s)
E: Failed to fetch https://apt.dockerproject.org/repo/pool/main/d/docker-engine/docker-engine_1.8.2-0~vivid_amd64.deb  Size mismatch

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by cpuguy83** [comment]
ping @jfrazelle

**Comment by linxcat** [comment]
Same here, looks like docker has a bit of a broken somewhere... no wonder no one I asked could tell why it wasn't working even though apt-get upgrade did on the line just before

**Comment by brianbruggeman** [comment]
Same issue here (on fresh aws box after an apt-get update).

**Comment by albertoleal** [comment]
Same on DigitalOcean.

**Comment by edublancas** [comment]
Getting the same when trying to install:

`$ curl -sSL https://get.docker.com/ | sh`

Output:

```After this operation, 28.8 MB of additional disk space will be used.
Fetched 5691 kB in 0s (5962 kB/s)
E: Failed to fetch https://apt.dockerproject.org/repo/pool/main/d/docker-engine/docker-engine_1.8.2-0~trusty_amd64.deb  Size mismatch
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?```

Machine: `Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-48-generic x86_64)`

**Comment by linxcat** [comment]
I think this is enough evidence, I'd guess there's an investigation and fix in-process now

**Comment by e1senh0rn** [comment]
Same here, Ubuntu 12.04 (Vagrant):
```text
file: docker-engine_1.8.2-0~trusty_amd64.deb

Current:
  size: 5690994
  md5: 809a064aa451849dfdce77b41d89a9f5

Expected (in Docker APT repo in Packages.bz2 manifest):
  size: 5690966
  md5: 178c3d51507cd9a7b8e69c3bb9f057c4
```

**Comment by alph486** [comment]
Ditto - 14.04 Trusty on AWS and Parallels.

**Comment by joeandrews** [comment]
same for cloud66. 	Deployment failed: Failed command: sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install docker-engine=1.8.2-0~trusty. Error output: E: Failed to fetch https://apt.dockerproject.org/repo/pool/main/d/docker-engine/docker-engine_1.8.2-0~trusty_amd64.deb Size mismatch E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by JayH5** [comment]
`apt-get install docker-engine=1.8.1-0~trusty` still works FWIW

**Comment by tomilsinszki** [comment]
I get the same error when I run `vagrant up` using the following Vagrantfile (**it worked without any errors before**):

```bash
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.define "host"
  config.vm.network "private_network", ip: "192.168.33.71"
  config.vm.synced_folder ".", "/app", type: Vagrant::Util::Platform.windows? ? "smb" : "nfs"

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1536"]
  end

  # Add swap
  config.vm.provision :shell, inline: "fallocate -l 4G /swapfile && chmod 0600 /swapfile && mkswap /swapfile && swapon /swapfile && echo '/swapfile none swap sw 0 0' >> /etc/fstab"
  config.vm.provision :shell, inline: "echo vm.swappiness = 10 >> /etc/sysctl.conf && echo vm.vfs_cache_pressure = 50 >> /etc/sysctl.conf && sysctl -p"

  # Install docker
  config.vm.provision "shell", inline: "curl -sSL https://get.docker.com/ | sh"

  # Install docker-compose
  config.vm.provision "shell", inline: "apt-get install -y python-pip"
  config.vm.provision "shell", inline: "pip install -U docker-compose"
end
```

**Error response:**

```bash
# ...
==> host: E: Failed to fetch https://apt.dockerproject.org/repo/pool/main/d/docker-engine/docker-engine_1.8.2-0~trusty_amd64.deb  Size mismatch
==> host: 
==> host: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by michel-jader** [comment]
Having same issue here (ubuntu 14.04)!!!!

**Comment by stevevega** [comment]
Also happening on Debian Jessie.

**Comment by mbrewster** [comment]
Same here- Vagrant w/ 14.04

**Comment by martinsbalodis** [comment]
Same on kvm ubuntu 14.04, docker ubuntu

**Comment by marcsalomon** [comment]
this seems to do the trick:

$ wget https://apt.dockerproject.org/repo/pool/main/d/docker-engine/docker-engine_1.8.2-0~trusty_amd64.deb
$ sudo dpkg -i docker-engine_1.8.2-0~trusty_amd64.deb

**Comment by Amzani** [comment]
Same issue on Ubuntu 15.04/vivid

**Comment by tiborvass** [comment]
Thanks guys we're working on it

**Comment by alph486** [comment]
@marcsalomon - Yes good workaround.

**Comment by michel-jader** [comment]
@marcsalomon thanks man

**Comment by cpuguy83** [comment]
It would not be a good idea to bypass the gpg checking here, imo.

**Comment by ah-taktik** [comment]
@marcsalomon, Thanks for the workaround :+1:

**Comment by Deric4** [comment]
Failed on 3.13 kernel

Linux my-server-1 3.13.0-46-generic #77-Ubuntu SMP Mon Mar 2 18:23:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux


worked on 3.19 kernel

Linux my-server-2 3.19.0-30-generic #34~14.04.1-Ubuntu SMP Fri Oct 2 22:09:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by sehyoc** [comment]
Encountered same issue

0 upgraded, 6 newly installed, 0 to remove and 174 not upgraded.
Need to get 9,133 kB of archives.
After this operation, 50.4 MB of additional disk space will be used.
Get:1 http://us-west-2.ec2.archive.ubuntu.com/ubuntu/ trusty/universe aufs-tools amd64 1:3.2+20130722-1.1 [92.3 kB]
Get:2 http://us-west-2.ec2.archive.ubuntu.com/ubuntu/ trusty/main liberror-perl all 0.17-1.1 [21.1 kB]
Get:3 http://us-west-2.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/main git-man all 1:1.9.1-1ubuntu0.1 [698 kB]
Get:4 http://us-west-2.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/main git amd64 1:1.9.1-1ubuntu0.1 [2,627 kB]
Get:5 http://us-west-2.ec2.archive.ubuntu.com/ubuntu/ trusty/main cgroup-lite all 1.9 [3,918 B]
Get:6 https://apt.dockerproject.org/repo/ ubuntu-trusty/main docker-engine amd64 1.8.2-0~trusty [5,691 kB]
Fetched 9,133 kB in 0s (10.6 MB/s)
E: Failed to fetch https://apt.dockerproject.org/repo/pool/main/d/docker-engine/docker-engine_1.8.2-0~trusty_amd64.deb  Size mismatch

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
ubuntu@ip-172-31-33-55:~$ uname -a
Linux ip-172-31-33-55 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by chuckbutler** [comment]
@tiborvass this **should be** as simple as reindexing the apt archive. You may need to remove / re-add the package and then regenerate.

**Comment by bushono** [comment]
@marcsalomon, Thanks for the workaround! Works perfect!

**Comment by icecrime** [comment]
We should be back: let us know if you're still seeing issues, thanks for your patience.

**Comment by tomilsinszki** [comment]
@icecrime seems to be working, thx for the fix

**Comment by alph486** [comment]
@icecrime Thanks :)

**Comment by hernandesbsousa** [comment]
I just got this error for version `1.10.3`, forcing apt to install the previous version with `sudo apt-get install docker-engine=1.10.2-0~trusty` solved the problem

**Comment by tiborvass** [comment]
@hernandesbsousa that's weird, do you still have a box with the issue? I can't reproduce.

**Comment by hernandesbsousa** [comment]
Thanks a lot for the quick response.

I tried to reproduce this today on a fresh system and failed. On the old one which did not have the latest version, `apt-get update && apt-get ugpgrade` did not throw any erros (maybe I should not have updated the apt cache before trying to upgrade the package). Anyway it's working fine now, thank you!

**Comment by thomasshanks** [comment]
I'm having the same problem with a later version:

`E: Failed to fetch http://apt.dockerproject.org/repo/pool/main/d/docker-engine/docker-engine_1.11.2-0~trusty_amd64.deb  Size mismatch
`
Running `sudo apt-get install docker-engine=1.11.2-0~trusty` worked.  I, however, need to release a script to others that uses the latest.

**Comment by thaJeztah** [comment]
@thomasshanks are you installing on a local machine, on a cloud provider? Could there be an apt-cacher running?

**Comment by cindy06** [comment]
Err https://apt.dockerproject.org/repo/ ubuntu-trusty/main docker-engine amd64 1.12.1-0~trusty
  gnutls_handshake() failed: A TLS packet with unexpected length was received.
E: Failed to fetch https://apt.dockerproject.org/repo/pool/main/d/docker-engine/docker-engine_1.12.1-0~trusty_amd64.deb  gnutls_handshake() failed: A TLS packet with unexpected length was received.

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
