### ISSUE TITLE
Docker Client And Server Authentication

### ISSUE THREAD

**Issue by kamaljeetrathi** [docker/docker#16835]
How to authenticate client and server in docker.For now they both are on my host machine require no authentication.What if I have client and server on different machine,how I will validate my client with server with some username and password or with some other authentication.

**Comment by kamaljeetrathi** [comment]
Issue-:
1.Docker version
  Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

2.Docker Info
  Containers: 154
Images: 71
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 379
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-65-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 7.68 GiB
Name: uranus
ID: RJFK:S2F2:GPDM:2MVQ:4N5H:26X5:7KDH:NNAF:PHSH:QCEC:6CSD:X3LE
Username: kamaljeet
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

3.uname-a

Linux uranus 3.13.0-65-generic #106-Ubuntu SMP Fri Oct 2 22:08:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
4.Right now I have installed docker on my local machine and docker client and server are both on my local machine and easily communicating.
My question is that how will I authenticate my client and server if they are on different machine.
If I do sudo docker login :
It ask for 
username
password
email
I have enter those information same as my dockerhub account.
and than get login success.
Now if I dont have account it create it with above information entered.

So I have query on my client authentication,how I will know that client is authenticated and can communicate to server

**Comment by coolljt0725** [comment]
May be you want this https://github.com/docker/docker/blob/master/docs/articles/https.md#protect-the-docker-daemon-socket  :-)

**Comment by kamaljeetrathi** [comment]
@coolljt0725  I have tried that looks complicated.It will be great if you can provide any video link to this or  any other link which is simple to use.In this I am quite confuse where all the .pem file are generating and how and when to use it.

**Comment by coolljt0725** [comment]
@kamaljeetrathi  Sorry, I don't know if there is a video to show how to do this. Maybe other guys can provide some detailed information

**Comment by kamaljeetrathi** [comment]
Do I have to install boot2docker also for this

**Comment by cpuguy83** [comment]
Closing as this is not a Docker issue.
Authentication is done via client TLS verification.

Feel free to ping on #docker on IRC, or the docker-user mailing list.
Thanks!
