### ISSUE TITLE
APT package for Ubuntu utopic is disappeared.

### ISSUE THREAD

**Issue by AiOO** [docker/docker#16839]
Description of problem:
===================

I can't run `apt-get update` because APT package for Ubuntu utopic is disappeared.

`docker version`: NA

`docker info`: NA

`uname -a`: Linux ip-10-165-121-233 3.16.0-29-generic #39-Ubuntu SMP Mon Dec 15 22:27:29 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Environment details:
=========================================

AWS, Ubuntu 14.10(utopic)

How reproducible:
==============

Steps to Reproduce:
----------------------------

1. Add `deb https://apt.dockerproject.org/repo ubuntu-utopic main` to `/etc/apt/sources.list.d/docker.list`.
2. Run `apt-get update`.

Actual Results:
---------------------

```
# apt-get update
... elipsis ...
Err https://apt.dockerproject.org ubuntu-utopic/main amd64 Packages
  HttpError403
... elipsis ...
Ign https://apt.dockerproject.org ubuntu-utopic/main Translation-en
W: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-utopic/main/binary-amd64/Packages  HttpError403

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Expected Results:
-------------------------

The command `apt-get update` runs successfully.

Additional info:
---------------------

None.

**Comment by AiOO** [comment]
There is actually no any files or directories on [this path](https://apt.dockerproject.org/repo/dists/ubuntu-utopic/main/binary-amd64/).

**Comment by cpuguy83** [comment]
ping @jfrazelle

**Comment by xynny** [comment]
We also have this issue.  All builds are failing.  What is the recommended upgrade path?

**Comment by jfrazelle** [comment]
ah its the index file is wrong one sec

**Comment by tianon** [comment]
See also #15529 -- Utopic is EOL and you should switch to either LTS
(14.04) or upgrade (15.04).

**Comment by xynny** [comment]
yeah I am trying 14.04 & 15.04, too, but need to test those further to get the entire build working.

**Comment by jfrazelle** [comment]
updated

**Comment by jfrazelle** [comment]
might take a sec for the cache to bust

**Comment by AiOO** [comment]
Oh thanks!
