### ISSUE TITLE
Docker stats "precpu_stats" is not documented

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#16849]
Reported by "univahpollinger" on IRC; ([logs](https://botbot.me/freenode/docker-dev/msg/51414351/);

> I'm running Docker 1.8.2 and use the RemoteAPI. The response on a "GET /containers/<id>/stats" request contains a "precpu_stats" field - this is not documented, but is the exact copy of the "cpu_stats" field - is the "precpu_stats" field intended - what is this then? - or is it just a copy&paste error in the code?

PR https://github.com/docker/docker/pull/13320 introduced a `precpu_stats` field in the stats, but this field has not been documented

ping @coolljt0725 :smile:

**Comment by beetree** [comment]
I'm also struggling understanding the output of /stats/ failing to find any documentation.

**Comment by coolljt0725** [comment]
@thaJeztah  @beetree  The `precpu_stats` is the cpu statistic of last read, which is used for  calculating the cpu usage percent. 
` cpuPercent = (cpuDelta / systemDelta)`
`cpuDelata=CpuStats-precpu_stats`

**Comment by ZJUshuaizhou** [comment]
HI! it is new for me and I have read the logs on IRC,PR [#13320](https://github.com/docker/docker/pull/13320),PR [#16](https://github.com/lebauce/docker-collectd-plugin/issues/16),and the change [code](https://github.com/coolljt0725/docker/commit/96123a1fd5c2779ccd7dd722a1fa4196e91dd716),it is not hard,but i want to know what i should do? write a new documentation or update someone already existed?i don't know which one(link) i need to update and where i need to introduce! Can you give me some information and links?  thanks! @thaJeztah @jeanpralo

**Comment by thaJeztah** [comment]
@ZJUshuaizhou the idea is to make sure the examples in the API documentation show this field. Since this is introduced in docker 1.7, the API docs for versions 1.19 .. 1.23 may need to be updated; https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api_v1.19.md#get-container-stats-based-on-resource-usage

**Comment by ZJUshuaizhou** [comment]
Yeah！I get it ! Is it introduced since docker 1.7 ? I found it is contained in [V 1.17 API changes](https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api.md).I have checkout all the versions after V1.14. And all of  docs version after docker V1.17 contain the field "percpu_usage" in the examples.  Do you agree that what i should do is to update the docs after V1.17 and give some explain ? By the way,where i can find the api docs before V1.14 ? I have not find [them](https://github.com/docker/docker/tree/master/docs/reference/api) thanks :) @thaJeztah

**Comment by ZJUshuaizhou** [comment]
I have got in touch with @coolljt0725 ,i will work on it ! :)

**Comment by thaJeztah** [comment]
Thanks @ZJUshuaizhou!

**Comment by coolljt0725** [comment]
@ZJUshuaizhou  Thanks

**Comment by thaJeztah** [comment]
Closing as this is now documented
