### ISSUE TITLE
Revert 90 col change from #14546

### ISSUE THREAD

**Issue by duglin** [docker/docker#16892]
See #16815.

We should find a different option name than `--disable-content-trust` so that we can keep our help text within 80 characters. By doing so we are also ensuring that we're not forcing people to use excessively long option names.

Possible alternatives:
```
--disable-trust=true
--disable-ctrust=true
```

**Comment by duglin** [comment]
ping @dmcgowan

**Comment by dmcgowan** [comment]
I have no opinion on this as the naming was not my choice nor a battle I would care to fight. I will say this flag was not intended to be short and using it will be actively discouraged.

Ping @diogomonica and @NathanMcCauley for timeline on when this flag would become more relevant by having trust on by default.

**Comment by diogomonica** [comment]
@duglin the point, as @dmcgowan stated, was that this is long and annoying. People shouldn't be using it.

I personally don't care about the 80 char thing.

**Comment by duglin** [comment]
I have no issue with making that flag annoying, but now we'll annoy people with 80 char screens. We went out of our way in the past to fit everything in 80 chars, now that's all blown away.  Would you object to just `--disable-ctrust` ?

**Comment by cpuguy83** [comment]
Instead of changing the flag (b/c it seems correct), maybe we can work on fixing wrapping issues in the help output?
There have been times when I had to really skimp on a flag description to make it fit into the 80 col test.

**Comment by duglin** [comment]
Each command can have several lines of extra text to help describe the command and its options. But I think keeping the one-liner for each option is a good thing.

**Comment by duglin** [comment]
We could go all out and format it like a normal man page.
```
OTHER OPTIONS
     Operation modifiers:

     -[0-7][lmh]
           specify drive and density

     --atime-preserve
           preserve access times on dumped files, either by restoring the
           times

     --acls
           Enable the POSIX ACLs support
```

**Comment by duglin** [comment]
But to be honest, I think that'll make things pretty verbose.

**Comment by LK4D4** [comment]
I dunno where we were here. But going to close it for now, because seems like everyone lost interest.
