### ISSUE TITLE
revert following symlinks in docker cp

### ISSUE THREAD

**Issue by aespinosa** [docker/docker#16896]
Description of problem:

This was disabled with the fix in #14885 . Adding a flag to the `docker cp` command like `-L' or '-H' like in the `cp` command can probably enable this feature back again.

`docker version`:

```
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:08:05 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:08:05 UTC 2015
 OS/Arch:      linux/amd64
```
`docker info`:
```
Containers: 2
Images: 164
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 168
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: syslog
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 1
Total Memory: 494.5 MiB
Name: dockerhost.localdomain
ID: F57Q:73M5:HAGL:SGHI:MM4B:T6FI:RWIY:IRDD:SL4S:7DFY:BONC:V6DA
Username: aespinosa
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
```

`uname -a`: `uname -a
Linux dockerhost.localdomain 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u4 (2015-09-19) x86_64 GNU/Linux`

How reproducible:

Just `docker cp` a symlink inside a container to the host. 

Steps to reproduce:

See above description

Actual results:

A symlink

Expected result:

A file

Additional info:

I think the change was major and broke the existing functionality. In reenabling the feature I think not following symlinks should be the flag and following symlinks be the default.

**Comment by tonistiigi** [comment]
Duplicate of #16555, and there is some good work on this in #16613

**Comment by aespinosa** [comment]
Thanks. I wasn't able to find the related tickets except for the one I mentioned earlier. Closing.

**Comment by thaJeztah** [comment]
Ah, thanks! I thought I'd seen a discussion on `-L`


@aespinosa I'm closing this as duplicate of https://github.com/docker/docker/issues/16555, please continue the discussion there

**Comment by thaJeztah** [comment]
Oops, beat me to it :+1:
