### ISSUE TITLE
Docker on Ubuntu 14.04.3 always getting "[8] System error: no such file or directory"

### ISSUE THREAD

**Issue by datakid** [docker/docker#16926]
I had Docker working three weeks ago, but now I can't get anything except 

```
no such file or directory
Error response from daemon: Cannot start container 7d3cb483971037da163fd8d220100728f51e055e7d0ae811a70bf2ef32564552: [8] System error: no such file or directory
```

docker version
```
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Wed Oct  7 17:48:28 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Wed Oct  7 17:48:28 UTC 2015
 OS/Arch:      linux/amd64
```

docker info
```
Containers: 1
Images: 2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 4
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-66-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 7.74 GiB
Name: footscray
ID: IWMM:MCLX:3H5C:V4QA:JQA2:TVBM:F3PX:4VC4:45XZ:C6AT:TB75:QQNG
```

uname -a
```
Linux footscray 3.13.0-66-generic #108-Ubuntu SMP Wed Oct 7 15:20:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Am running on localhost.

docker run hello-world
```
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world

535020c3e8ad: Pull complete 
af340544ed62: Pull complete 
Digest: sha256:a68868bfe696c00866942e8f5ca39e3e31b79c1e50feaee4ce5e28df2f051d5c
Status: Downloaded newer image for hello-world:latest
no such file or directory
Error response from daemon: Cannot start container b834de00b11decea01b36d1105352eca423bf708dda4b14016bab8fecd5bff41: [8] System error: no such file or directory
```

At first I'd used the wget method to install docker, but then I removed everything and used the method described in the docs https://docs.docker.com/installation/ubuntulinux/

**Comment by joberget** [comment]
+1 same problem here.

**Comment by datakid** [comment]
FWIW, I've tried changing the storage driver to both vfs and devicemapper without any success.

Also, when updating yesterday I pulled Docker 1.8.3 - but am still getting the same result.

**Comment by thaJeztah** [comment]
I wonder if this is somehow related to AppArmor, see a similar issue on Debian here: https://github.com/docker/docker/issues/14931 (which contains some instructions on debugging the issue)

**Comment by datakid** [comment]
Ah! I read that issue but also couldn't find any issues within my dmesg logs.

But I have discovered something that works - it's worth noting that my docker and AppArmor skills are rudimentary, so I'm not 100% sure of what's going on here.

When I first applied the AppArmor solution (aa-complain, per session) it worked. I then disabled the profile in general for consistency across reboots (as advised on the [Ubuntu wiki](https://help.ubuntu.com/community/AppArmor#Disable_one_profile)):

```
sudo ln -s /etc/apparmor.d/docker /etc/apparmour.d/disable/docker
```


When I deleted the entry in /etc/apparmour.d/disable, and just have the aa-complain set, docker starts to work again.

For reference, I set up a VM of Ubuntu 15.04 this AM and had exactly the same problem - this was how I found the solution.

**Comment by thaJeztah** [comment]
Thanks for reporting back @datakid and good to hear you were able to resolve it.

/cc @ewindisch

**Comment by dsifford** [comment]
For those who may still be facing this issue. I've recently discovered that this happens on my Windows machine if I do not explicitly set my `.sh`, `Dockerfile`, and `docker-compose.yml` line endings to UNIX `LF` format (default is `CRLF`).. Might be worth giving that a shot if you're running a Windows machine.

**Comment by aldarund** [comment]
Same error was for me on Windows. Changhing from CRLF to LF fixed the issue.

**Comment by thaJeztah** [comment]
@dsifford @aldarund does that apply to both the Dockerfile and docker-compose.yml? If so, please open a new issue for docker and compose https://github.com/docker/compose/issues

We may not support CRLF line-endings, but (if possible), adding a better error message would be good

**Comment by dsifford** [comment]
@thaJeztah Looking back at my `.gitattributes` file, it appears that I only ended up changing the line endings on the Dockerfile and the `.sh` files that my build process depends on. I don't think Compose is effected by this.

**Comment by thaJeztah** [comment]
@dsifford in that case, it may actually be the .sh files that cause the problem, I think I've see that happening on Linux, but not 100% sure. If it's the .sh files that cause the problems, I don't think we can change anything on that, but if it's the Dockerfile, that would be something we can control

**Comment by dsifford** [comment]
@thaJeztah You make a good point. Let me give that a shot now and report back.

**Comment by dsifford** [comment]
@thaJeztah Your suspicion was correct. Docker is not to blame for this issue. 

After running a few tests, the error message (below) could only be invoked by changing the line endings in the `.sh` files to CRLF. Having CRLF endings on the `Dockerfile` and/or the `docker-compose.yml` file did not produce the error.

**The error message:**
```sh
ERROR: Cannot start container 057540c349f83925271f6c8d132d120975c3479370b43072cadc7bfd4a847014: [8] System error: no such file or directory
```

**Comment by thaJeztah** [comment]
@dsifford awesome, thank you so much for testing!

**Comment by jpblair** [comment]
I experienced a similar issue on Windows that appears to have been resolved by converting everything from CRLF to LF.  A more descriptive error message would be useful.

**Comment by thaJeztah** [comment]
@jpblair unfortunately, that issue is in Linux itself, you'll have the same problem on a bare-metal Linux system when trying to run a shell script that has CRLF. I.e., it's not Docker specific

**Comment by nmilutinovic** [comment]
dos2unix was also my savior. Man! What a bummer...
