### ISSUE TITLE
Cannot ping between containers via overlay multihost network

### ISSUE THREAD

**Issue by chanwit** [docker/docker#16923]
Description of problem:
I setup 1 `kvstore` and 2 engines on Debian 8, `node-1` and `node-2`.
Then starting a consul instance in `kvstore`.
Back to the Engine build 20151005 (`--kv-store`, `--default-network`), I could ping across containers.
But with changes in build 20151008 (`--cluster-store`, and manual `network create`), ping does not work.

Here's details of these 3 machines. Sorry for a lot of texts here.

### kvstore (159.203.87.31)

/usr/bin/docker daemon -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver aufs --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=digitalocean

`uname -a`:
Linux kvstore 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

`docker info`:
Containers: 1
Images: 18
Engine Version: 1.9.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/0.0/aufs
 Backing Filesystem: extfs
 Dirs: 20
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-57-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 490 MiB
Name: kvstore
ID: NXYF:BARX:TA44:AIOP:N2BC:FQBB:SKCI:YP5Q:GMQI:CQKS:FDTD:APF4
WARNING: No swap limit support
Labels:
 provider=digitalocean
Experimental: true

### node-1 (159.203.92.181)

/usr/bin/docker -d -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver aufs --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label com.docker.network.driver.overlay.bind_interface=eth0 --label provider=digitalocean --cluster-store consul://159.203.87.31:8500

`uname -a`:
Linux node-1 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux

`docker info`:
Containers: 1
Images: 2
Engine Version: 1.9.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/0.0/aufs
 Backing Filesystem: extfs
 Dirs: 4
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 1
Total Memory: 494.5 MiB
Name: node-1
ID: WI3N:CRKY:VDT3:525C:S7EG:GU35:SPGH:25PV:GI3Q:3MO2:D5GK:ITDJ
WARNING: No memory limit support
WARNING: No swap limit support
Labels:
 com.docker.network.driver.overlay.bind_interface=eth0
 provider=digitalocean
Experimental: true
Cluster store: consul://159.203.87.31:8500

### node-2

/usr/bin/docker -d -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver aufs --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label com.docker.network.driver.overlay.bind_in
terface=eth0 --label com.docker.network.driver.overlay.neighbor_ip=159.203.92.181 --label provider=digitalocean --cluster-store consul://159.203.87.31:8500

`uname -a`:
Linux node-2 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux

`docker info`:
Containers: 1
Images: 2
Engine Version: 1.9.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/0.0/aufs
 Backing Filesystem: extfs
 Dirs: 4
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 1
Total Memory: 494.5 MiB
Name: node-2
ID: 2IYV:34JT:SGTJ:BFRM:UQTZ:TUSA:AEWO:2VU4:BEVJ:DHYU:ZZEX:PDCF
WARNING: No memory limit support
WARNING: No swap limit support
Labels:
 com.docker.network.driver.overlay.bind_interface=eth0
 com.docker.network.driver.overlay.neighbor_ip=159.203.92.181
 provider=digitalocean
Experimental: true
Cluster store: consul://159.203.87.31:8500

### Step to Reproduce

1. Setup 3 machines
2. On node-1: `$ docker network create -d overlay multi`
3. On node-1: `$ docker run -d --net=multi --name foo busybox top`
4. On node-2: `$ docker network ls`
```
NETWORK ID          NAME                DRIVER
a3e49bcf303f        none                null
3f8346142126        host                host
d372258896f6        bridge              bridge
a108b3ec6815        multi               overlay
```
5. On node-2: `$ docker run --rm --net=multi busybox ping -c 1 foo`

PING foo (172.21.0.1): 56 data bytes

Actual Results:
--- foo ping statistics ---
1 packets transmitted, 0 packets received, 100% packet loss

Expected Results:
PING should work here.

**Comment by mavenugo** [comment]
@chanwit since the introduction of docker native discovery, the daemon flags for multi-host networking has changed. Pls DONT use  `--label com.docker.network.driver.overlay.bind_interface` and `--label com.docker.network.driver.overlay.neighbor_ip` any more.

The only 2 flags that you have to use are - `--cluster-store` and `--cluster-advertise`.
Please refer to the https://github.com/abronan/docker/blob/fix_discovery_pkg_readme/pkg/discovery/README.md.

**Comment by chanwit** [comment]
Thank you @mavenugo.
It seems what I am missing there is `--cluster-advertise`. I'll be trying it.

**Comment by chanwit** [comment]
Viola `--cluster-advertise` did the trick!

```
$ docker run --rm --net=multi busybox ping -c 5 test
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
cfa753dfea5e: Pull complete
d7057cb02084: Pull complete
Digest: sha256:16a2a52884c2a9481ed267c2d46483eac7693b813a63132368ab098a71303f8a
Status: Downloaded newer image for busybox:latest
PING test (172.21.0.3): 56 data bytes
64 bytes from 172.21.0.3: seq=0 ttl=64 time=5.394 ms
64 bytes from 172.21.0.3: seq=1 ttl=64 time=2.576 ms
64 bytes from 172.21.0.3: seq=2 ttl=64 time=0.796 ms
64 bytes from 172.21.0.3: seq=3 ttl=64 time=1.011 ms
64 bytes from 172.21.0.3: seq=4 ttl=64 time=0.805 ms

--- test ping statistics ---
5 packets transmitted, 5 packets received, 0% packet loss
round-trip min/avg/max = 0.796/2.116/5.394 ms
```

I'm closing this issue. Thank you again @mavenugo.

**Comment by mavenugo** [comment]
:+1: now I think you can admit it in your tweet ;)

**Comment by AgustinCB** [comment]
Hi! 

I just tried that solution, with same parameters, but keep getting all packets lost.

node-1

$ uname -a
Linux docker-experimental-1 3.19.0-28-generic #30~14.04.1-Ubuntu SMP Tue Sep 1 09:32:55 UTC 2015 x86_64 x86_64 x
86_64 GNU/Linux

$ sudo docker version
time="2015-10-27T14:20:41.141567291Z" level=info msg="GET /v1.22/version" 
Client:
 Version:      1.9.0-dev
 API version:  1.22
 Go version:   go1.4.3
 Git commit:   ccf5b60
 Built:        Fri Oct 16 19:06:02 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true
Server:
 Version:      1.9.0-dev
 API version:  1.22
 Go version:   go1.4.3
 Git commit:   ccf5b60
 Built:        Fri Oct 16 19:06:02 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

docker -d --cluster-store=consul://localhost:8500 --cluster-advertise=localhost:2376 
docker network create -d overlay nt
sudo docker run -it --net=nt busybox test

node-2

$ uname -a
Linux docker-experimental-1 3.19.0-28-generic #30~14.04.1-Ubuntu SMP Tue Sep 1 09:32:55 UTC 2015 x86_64 x86_64 x
86_64 GNU/Linux

$ sudo docker version
time="2015-10-27T14:20:41.141567291Z" level=info msg="GET /v1.22/version" 
Client:
 Version:      1.9.0-dev
 API version:  1.22
 Go version:   go1.4.3
 Git commit:   ccf5b60
 Built:        Fri Oct 16 19:06:02 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true
Server:
 Version:      1.9.0-dev
 API version:  1.22
 Go version:   go1.4.3
 Git commit:   ccf5b60
 Built:        Fri Oct 16 19:06:02 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

docker -d --cluster-store=consul://localhost:8500 --cluster-advertise=localhost:2376 
docker network create -d overlay nt
sudo docker run -it --net=nt busybox test1
ping test
PING test (10.0.2.4): 56 data bytes
^C
--- test ping statistics ---
7 packets transmitted, 0 packets received, 100% packet loss

**Comment by cpuguy83** [comment]
@AgustinCB I don't think advertising localhost is going to work.

**Comment by mavenugo** [comment]
@cpuguy83 is right. --cluster-advertise should contain a cluster-wide reachable IP-Address.
