### ISSUE TITLE
How do I view docker daemon's debug logs?

### ISSUE THREAD

**Issue by pratikfegade** [docker/docker#16937]
Hi, I am working with docker's source code and need to debug the daemon. For this reason I need to view the logs. The logs I find at /var/log/upstart/docker.log are not comprehensive and as another post on this forum suggests, they are upstart logs and not docker logs.

**Comment by runcom** [comment]
you need to start the docker daemon with the `-D` flag to be able to see docker daemon debug logs

Also, pls, next time, pop up in #docker-dev on IRC since this is not an issue to be reported here on github.
Thanks, closing
