### ISSUE TITLE
/bin/bash permission denied

### ISSUE THREAD

**Issue by alexislg2** [docker/docker#16939]
Hey folks

I'm running docker 1.8.2 on Ubuntu 14.04

It used to work great but now nothing works. Each time I want to run or build something I got the same error /bin/bash permission denied. 

Step to reproduce (on my machine only)
1. Run `docker run -ti ubuntu:trusty /bin/bash`

Results received:
```
exec: "/bin/bash": permission denied
Error response from daemon: Cannot start container 1db470dc718cc5110404bd4b04e88eb21ed6539e30e0042dc5915e19526376e5: [8] System error: exec: "/bin/bash": permission denied
```

Results expected: 
Open a running container with bash open

The same happens if I write only bash or sh or /bin/sh. On this machine, both `bash` and `sh` are working well. I tried as root. Same result

How can I debug that? I found nothing on google.

docker version:
```
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64
```

docker info:
```
Containers: 27
Images: 9
Storage Driver: aufs
 Root Dir: /media/alexis/Windows8_OS/docker/aufs
 Backing Filesystem: <unknown>
 Dirs: 63
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-39-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 4
Total Memory: 3.559 GiB
Name: pegase
ID: FUUM:LIMJ:GXUM:CDOY:P6OJ:JLB2:Y7N6:O3GX:6GIX:EDF2:7LAX:GZ4H
Username: alexislg
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

uname -a:
`Linux pegase 3.13.0-39-generic #66-Ubuntu SMP Tue Oct 28 13:30:27 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by thaJeztah** [comment]
Just a long shot; is there something special with `/media/alexis/Windows8_OS/docker/aufs`? (I see the output shows `Backing Filesystem: <unknown>`)

**Comment by alexislg2** [comment]
Oh you were right : /media/alexis/Windows8_OS/docker/aufs is a NTFS mounted volume. I put `#DOCKER_OPTS="-g /media/alexis/Windows8_OS/docker"` in my /etc/default/docker

If I remove this line and restart docker it's working. Can't we store docker data on external volume?

**Comment by thaJeztah** [comment]
I've never tested its but I suspect that aufs (or the other layered file systems) doesn't work properly on NTFS. It certainly isn't a setup we support at this moment.

**Comment by tjdett** [comment]
@alexislg2 Storage drivers that might work are `devicemapper` as a loopback, or `vfs`. Neither are considered production-grade (or particularly fast), but if you're using a Windows 8 mount you're probably OK with that.

For more info:
<https://docs.docker.com/reference/commandline/daemon/#daemon-storage-driver-option>

**Comment by thaJeztah** [comment]
I'm going to close this issue because this is not something we support, but feel free to continue the discussion here.

Thanks for the extra hints, @tjdett
