### ISSUE TITLE
Docker push fails with EOF in private registry 2.0 behind NGINX Proxy

### ISSUE THREAD

**Issue by andrefreitas** [docker/docker#16949]
## Description of problem
Docker push fails in a private registry behind an NGINX proxy.

## docker version
```
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      linux/amd64
```
## docker info

```
Containers: 2
Images: 108
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 112
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.2 (TCL 6.4); master : aba6192 - Thu Sep 10 20:58:17 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: default
ID: 4IIS:67Q3:ZWX4:NRYK:TCBL:2IYY:C4OP:ACGJ:L2UP:VMPY:5WOT:IOAW
Debug mode (server): true
File Descriptors: 12
Goroutines: 18
System Time: 2015-10-12T16:52:12.072845557Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```
## uname -a 

```Darwin artemis.ndrive.com 15.0.0 Darwin Kernel Version 15.0.0: Wed Aug 26 16:57:32 PDT 2015; root:xnu-3247.1.106~1/RELEASE_X86_64 x86_64````

## How reproducible:
Always.

## Steps to Reproduce:
1. Configure an NGINX proxy for Docker Registry 2.0
2. Login into registry
3. docker push docker.yourcompany.com/yourepository

## Actual Results: 

The push refers to a repository [docker.<censored>/<censored>] (len: 1)
269dc21b3cd3: Pushing [==================================================>]     32 B/32 B
EOF

### Nginx Configuration
```
server {
  listen 80;
  listen 443 ssl;
  server_name docker.company.com;

  # disable any limits to avoid HTTP 413 for large image uploads
  client_max_body_size 0;

  # required to avoid HTTP 411: see Issue #1486 (https://github.com/docker/docker/issues/1486)
  chunked_transfer_encoding on;

  location / {
    root /srv/container-data/docker-registry/docker/registry;
  }

  location /v2/ {
    # Do not allow connections from docker 1.5 and earlier
    # docker pre-1.6.0 did not properly set the user agent on ping, catch "Go *" user agents
    if ($http_user_agent ~ "^(docker\/1\.(3|4|5(?!\.[0-9]-dev))|Go ).*\$" ) {
      return 404;
    }

    auth_basic "Registry realm";
    auth_basic_user_file /srv/container-data/docker-registry/docker/registry/.htpasswd;
    add_header 'Docker-Distribution-Api-Version' 'registry/2.0' always;

    proxy_set_header  Host              \$http_host;   # required for docker client's sake
    proxy_set_header  X-Real-IP         \$remote_addr; # pass on real client's IP
    proxy_set_header  X-Forwarded-For   \$proxy_add_x_forwarded_for;
    proxy_set_header  X-Forwarded-Proto \$scheme;
    proxy_read_timeout                  900;

    proxy_pass http://localhost:8022;
  }
}
```

### Nginx Access logs

```
^[[B192.168.1.45 - - [12/Oct/2015:17:55:41 +0100] "GET /v2/ HTTP/1.1" 401 194 "-" "docker/1.8.2 go/go1.4.2 git-commit/0a8c2e3 kernel/4.0.9-boot2docker os/linux arch/amd64"
192.168.1.45 - <censored user> [12/Oct/2015:17:55:41 +0100] "POST /v2/gemserver/blobs/uploads/ HTTP/1.1" 202 0 "-" "docker/1.8.2 go/go1.4.2 git-commit/0a8c2e3 kernel/4.0.9-boot2docker os/linux arch/amd64"
192.168.1.45 - <censored user> [12/Oct/2015:17:55:41 +0100] "PATCH /v2/<censored>/blobs/uploads/%5Chttps://%5Cdocker.<censored>.com/v2/gemserver/blobs/uploads/80eba973-2d93-45d4-8549-aa36aee26940?_state=mGjSpcDIpOnRh4vHgaCMTIVHr7Z11L3QW_WsYk2k6vN7Ik5hbWUiOiJnZW1zZXJ2ZXIiLCJVVUlEIjoiODBlYmE5NzMtMmQ5My00NWQ0LTg1NDktYWEzNmFlZTI2OTQwIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE1LTEwLTEyVDE2OjU1OjQxLjM3OTU4NjkzMVoifQ%3D%3D HTTP/1.1" 301 0 "-" "docker/1.8.2 go/go1.4.2 git-commit/0a8c2e3 kernel/4.0.9-boot2docker os/linux arch/amd64"
```

**Comment by arcolombo** [comment]
I am generating this error when pushing to Docker hub. 

I'm having a similar issue here.

The push refers to a repository [arcolombo/artemisunlayer] (len: 1)
3b15a479aa85: Image already exists
f43a789562e2: Image successfully pushed
20895e1cb336: Image successfully pushed
8bf26c72ef69: Image successfully pushed
90e1f131e119: Image push failed
FATA[1473] Error pushing to registry: Put https://registry-1.docker.io/v2/arcolombo/artemisunlayer/blobs/uploads/c7154030-84a0-4c2e-b783-590514f09394?_state=SG5dRTUm_qcSvUnlLHGReCeBb4K1SdNGbQp7MfD3wO97Ik5hbWUiOiJhcmNvbG9tYm8vYXJ0ZW1pc3VubGF5ZXIiLCJVVUlEIjoiYzcxNTQwMzAtODRhMC00YzJlLWI3ODMtNTkwNTE0ZjA5Mzk0IiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE1LTEwLTEyVDE4OjA5OjIxLjczNjYxNzA4N1oifQ%3D%3D&digest=sha256%3Abbe8192a830437430746d8afad853073e107e3a455d6627952c5b58af27bad75: EOF
anthonycolombo@quigonjinn:~/Documents$

anthonycolombo@quigonjinn:~/Documents$ sudo docker -D info
[sudo] password for anthonycolombo: 
Containers: 1
Images: 129
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 131
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.16.0-50-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 7.712 GiB
Name: quigonjinn
ID: U5LV:PN5L:LQZY:B36M:IJF7:LYRS:LEQB:2NMY:RNVY:IYYV:GWRI:YRBO
Debug mode (server): false
Debug mode (client): true
Fds: 12
Goroutines: 19
System Time: Mon Oct 12 11:51:20 PDT 2015
EventsListeners: 0
Init SHA1: 7f9c6798b022e64f04d2aff8c75cbf38a2779493
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker
Username: arcolombo
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support
anthonycolombo@quigonjinn:~/Documents$ sudo docker -version
flag needs an argument: -e
See 'docker --help'.
flag provided but not defined: -version
See 'docker --help'.
anthonycolombo@quigonjinn:~/Documents$ sudo docker -v
Docker version 1.6.2, build 7c8fca2
anthonycolombo@quigonjinn:~/Documents$ 
anthonycolombo@quigonjinn:~/Documents$ uname -a
Linux quigonjinn 3.16.0-50-generic #67~14.04.1-Ubuntu SMP Fri Oct 2 22:07:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
anthonycolombo@quigonjinn:~/Documents$

**Comment by andrefreitas** [comment]
It also happens in Docker 1.8.3

**Comment by andrefreitas** [comment]
## More additional info:

I got these logs from inside the registry container:

time="2015-10-13T10:19:48Z" level=warning msg="invalid remote IP address: \"\\\\192.168.1.45\""
time="2015-10-13T10:19:48Z" level=warning msg="invalid remote IP address: \"\\\\192.168.1.45\""
time="2015-10-13T10:19:48Z" level=warning msg="invalid remote IP address: \"\\\\192.168.1.45\""
time="2015-10-13T10:19:48Z" level=warning msg="invalid remote IP address: \"\\\\192.168.1.45\""
time="2015-10-13T10:19:48Z" level=info msg="response completed" http.request.host="\\docker.<censored>" http.request.id=d907bf56-8f39-49d8-94d0-e238c1a39aca http.request.method=POST http.request.remoteaddr="172.17.42.1:50170" http.request.uri="/v2/gemserver/blobs/uploads/" http.request.useragent="docker/1.8.3 go/go1.4.2 git-commit/f4bf5c7 kernel/4.1.10-boot2docker os/linux arch/amd64" http.response.duration=11.570822ms http.response.status=202 http.response.written=0 instance.id=bbc5c870-f92e-4d10-9c2c-a24b6c5d40e9 version=v2.1.1
172.17.42.1 - - [13/Oct/2015:10:19:48 +0000] "POST /v2/gemserver/blobs/uploads/ HTTP/1.0" 202 0 "" "docker/1.8.3 go/go1.4.2 git-commit/f4bf5c7 kernel/4.1.10-boot2docker os/linux arch/amd64"
time="2015-10-13T10:19:48Z" level=warning msg="invalid remote IP address: \"\\\\192.168.1.45\""
time="2015-10-13T10:19:48Z" level=warning msg="invalid remote IP address: \"\\\\192.168.1.45\""
time="2015-10-13T10:19:48Z" level=info msg="response completed" http.request.host="\\docker.<censored>" http.request.id=4b21f1e4-9c4f-4870-b10e-0d96eab400bc http.request.method=PATCH http.request.remoteaddr="172.17.42.1:50172" http.request.uri="/v2/gemserver/blobs/uploads/%5Chttps://%5Cdocker.<censored>/v2/gemserver/blobs/uploads/a16dafb6-353d-4b72-a256-a6c45af54b2b?_state=Qb0hMWTt3YP7v-5WgD3YoMBc3fBew6iTc1KqC3s4CoR7Ik5hbWUiOiJnZW1zZXJ2ZXIiLCJVVUlEIjoiYTE2ZGFmYjYtMzUzZC00YjcyLWEyNTYtYTZjNDVhZjU0YjJiIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE1LTEwLTEzVDEwOjE5OjQ4LjMxODQwNjMyNVoifQ%3D%3D" http.request.useragent="docker/1.8.3 go/go1.4.2 git-commit/f4bf5c7 kernel/4.1.10-boot2docker os/linux arch/amd64" http.response.duration="265.962µs" http.response.status=301 http.response.written=0 instance.id=bbc5c870-f92e-4d10-9c2c-a24b6c5d40e9 version=v2.1.1
172.17.42.1 - - [13/Oct/2015:10:19:48 +0000] "PATCH /v2/gemserver/blobs/uploads/%5Chttps://%5Cdocker.<censored>/v2/gemserver/blobs/uploads/a16dafb6-353d-4b72-a256-a6c45af54b2b?_state=Qb0hMWTt3YP7v-5WgD3YoMBc3fBew6iTc1KqC3s4CoR7Ik5hbWUiOiJnZW1zZXJ2ZXIiLCJVVUlEIjoiYTE2ZGFmYjYtMzUzZC00YjcyLWEyNTYtYTZjNDVhZjU0YjJiIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE1LTEwLTEzVDEwOjE5OjQ4LjMxODQwNjMyNVoifQ%3D%3D HTTP/1.0" 301 0 "" "docker/1.8.3 go/go1.4.2 git-commit/f4bf5c7 kernel/4.1.10-boot2docker os/linux arch/amd64"

**Comment by andrefreitas** [comment]
More info: The errors only happens for images built locally.

**Comment by andrefreitas** [comment]
Found a similar issue in: https://github.com/docker/distribution/issues/970 and fixed this issue by commenting:

```
    # proxy_set_header  Host              \$http_host;   # required for docker client's sake
    # proxy_set_header  X-Real-IP         \$remote_addr; # pass on real client's IP
    # proxy_set_header  X-Forwarded-For   \$proxy_add_x_forwarded_for;
    # proxy_set_header  X-Forwarded-Proto \$scheme;
```
 Please fix the documentation at https://docs.docker.com/registry/nginx/. I should be already fixed due the issue reported above. @thaJeztah You should take documentation issues more seriously since we trust them to work.

**Comment by thaJeztah** [comment]
@andrefreitas correct, it looks like the documentation has already been updated in https://github.com/docker/distribution/pull/981, but not yet published to the website. The docs on the website are usually updated together with a release, and if time permits, updates are cherry-picked and published between releases.

**Comment by arcolombo** [comment]
how should I resolve this issue?  I'm not sure what I can comment out from my end.  thank you again.

**Comment by thaJeztah** [comment]
@arcolombo if you're having issues with Docker Hub, it's best to send an e-mail to support@docker.com or open an issue via https://support.docker.com

**Comment by thaJeztah** [comment]
Closing because the documentation for this is now published; https://docs.docker.com/registry/nginx/#gotchas

**Comment by emcniece** [comment]
[This link](https://docs.docker.com/registry/nginx/#gotchas) is now a 404 - does anyone know where it migrated to?

**Comment by thaJeztah** [comment]
@emcniece it's still in the archived docs; https://docs.docker.com/v1.9/registry/nginx/#gotchas

**Comment by zoltan-fedor** [comment]
I still get the same whether or not using NGinx or going directly to the Docker registry and whether or not those NGinx proxy settings are there:
`time="2019-11-12T20:35:04.529028691Z" level=warning msg="invalid remote IP address: "unknown""`
