### ISSUE TITLE
Machine default already exists in VirtualBox.

### ISSUE THREAD

**Issue by pinouf** [docker/docker#16943]
hello,

i would like to test docker.
when i try to run the docker quickstart terminal.

i got an error ..

Machine default already exists in VirtualBox.
Starting machine default...
Error setting up host only network on machine start: exit status 1
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
Setting environment variables for machine default...

when i run  docker-machine ls
i got that
NAME      ACTIVE   DRIVER       STATE     URL   SWARM
default            virtualbox   Stopped    

i dont know what i have to do .

thank you

**Comment by pinouf** [comment]
docker version:
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      darwin/amd64
Get http:///var/run/docker.sock/v1.20/version: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?

docker info:
Get http:///var/run/docker.sock/v1.20/info: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?

uname -a:
Darwin iMac-de-Pinouf.local 15.0.0 Darwin Kernel Version 15.0.0: Wed Aug 26 16:57:32 PDT 2015; root:xnu-3247.1.106~1/RELEASE_X86_64 x86_64

---------------------

1) i have virtual box 5.0.4 r102546
2) i closed virtual box 
3 ) i run docker quickstart terminal application
4 ) i got error

Machine default already exists in VirtualBox.
Starting machine default...
Error setting up host only network on machine start: exit status 1
Started machines may have new IP addresses. You may need to re-run the docker-machine env command.
Setting environment variables for machine default...

**Comment by cpuguy83** [comment]
ping @nathanleclaire
A machine issue, I found a number of issues in the machine repo that may apply, but not sure... so I didn't want to just move and make yet another dup.

**Comment by nathanleclaire** [comment]
@pinouf  If it's related to Toolbox, please file an issue at : https://github.com/docker/toolbox

Otherwise provide instructions to duplicate using only Docker Machine.  Thanks!

**Comment by thaJeztah** [comment]
@pinouf I'm going to close this issue here; can you search for, and otherwise open an issue in the issue-trackers of "toolbox" or "machine"? As @nathanleclaire explained?

**Comment by pinouf** [comment]
thanks you for the information @nathanleclaire .
i will try to resolve the problem in Toolbox github.
