### ISSUE TITLE
Error Pushing to Docker Hub,  several errors: EOF,  use of closed network connection, 

### ISSUE THREAD

**Issue by arcolombo** [docker/docker#16959]
Hi.

#Required Information  

##Docker Info  
>Containers: 1
>Images: 129
>Storage Driver: aufs
> Root Dir: /var/lib/docker/aufs
 >Backing Filesystem: extfs
 >Dirs: 131
 > Dirperm1 Supported: true
> Execution Driver: native-0.2
> Logging Driver: json-file
> Kernel Version: 3.16.0-50-generic
> Operating System: Ubuntu 14.04.3 LTS
> CPUs: 4
> Total Memory: 7.712 GiB
> Name: quigonjinn
> ID: U5LV:PN5L:LQZY:B36M:IJF7:LYRS:LEQB:2NMY:RNVY:IYYV:GWRI:YRBO
> Username: arcolombo
> Registry: https://index.docker.io/v1/
> WARNING: No swap limit support
 
##Docker Version
>  anthonycolombo@quigonjinn:~/Documents/trnaDB$ sudo docker -v
>Docker version 1.8.3, build f4bf5c7

##System Information
 > uname -a
> Linux quigonjinn 3.16.0-50-generic #67~14.04.1-Ubuntu SMP Fri Oct 2 22:07:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

##Steps taken:
     I have made commits to an image that is size 10GB
     anthonycolombo@quigonjinn:~/Documents/trnaDB$ sudo docker images
     REPOSITORY                 TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
     arcolombo/artemisunlayer   v1                  3b15a479aa85        2 hours ago         10.21 GB

and am trying to push to Docker Hub.  
 I can successfully run the image   via  sudo docker run -it arcolombo/aretemisunlayer:v1 /bin/bash

I have tried 3 times to push to Docker hub, and received several error messages.

###Error 1
The push refers to a repository arcolombo/artemisunlayer
3b15a479aa85: Image already exists
f43a789562e2: Image already exists
20895e1cb336: Image already exists
8bf26c72ef69: Image already exists
90e1f131e119: Image push failed
FATA[1416] Error pushing to registry: Put https://registry-1.docker.io/v2/arcolombo/artemisunlayer/blobs/uploads/4accb54c-a964-4153-ac24-7a8610662ec0?_state=gx-cY2jt1fzbwLyOcnLYZKxt_e4-1cCJ8bK8WUvQwiV7Ik5hbWUiOiJhcmNvbG9tYm8vYXJ0ZW1pc3VubGF5ZXIiLCJVVUlEIjoiNGFjY2I1NGMtYTk2NC00MTUzLWFjMjQtN2E4NjEwNjYyZWMwIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE1LTEwLTEyVDE4OjQ1OjQxLjAyMDAwNDg5N1oifQ%3D%3D&digest=sha256%3A1da5e7d6dc4f04d8038b88fe7fd4e726d71e24fc98f4095c711d63b67d760979: use of closed network connection

###Error 2   

The push refers to a repository arcolombo/artemisunlayer
3b15a479aa85: Image already exists
f43a789562e2: Image successfully pushed
20895e1cb336: Image successfully pushed
8bf26c72ef69: Image successfully pushed
90e1f131e119: Image push failed
FATA[1473] Error pushing to registry: Put https://registry-1.docker.io/v2/arcolombo/artemisunlayer/blobs/uploads/c7154030-84a0-4c2e-b783-590514f09394?_state=SG5dRTUm_qcSvUnlLHGReCeBb4K1SdNGbQp7MfD3wO97Ik5hbWUiOiJhcmNvbG9tYm8vYXJ0ZW1pc3VubGF5ZXIiLCJVVUlEIjoiYzcxNTQwMzAtODRhMC00YzJlLWI3ODMtNTkwNTE0ZjA5Mzk0IiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE1LTEwLTEyVDE4OjA5OjIxLjczNjYxNzA4N1oifQ%3D%3D&digest=sha256%3Abbe8192a830437430746d8afad853073e107e3a455d6627952c5b58af27bad75: EOF
anthonycolombo@quigonjinn:~/Documents$

###Error 3
anthonycolombo@quigonjinn:~/Documents$ sudo docker push arcolombo/artemisunlayer:v1
The push refers to a repository [docker.io/arcolombo/artemisunlayer] (len: 1)
3b15a479aa85: Image already exists 
f43a789562e2: Image already exists 
20895e1cb336: Image already exists 
8bf26c72ef69: Image already exists 
90e1f131e119: Pushing 3.454 GB/6.366 GB
EOF

###Additional Info:

 I have tried using docker version 1.6.2, and docker version 1.8.  I have received the same errors.

**Comment by andrefreitas** [comment]
Wondering if it is related with #16949 issue.

**Comment by thaJeztah** [comment]
@arcolombo Since this is with Docker Hub, not a private repository, could you contact support@docker.com or open a ticket via https://support.docker.com ?

**Comment by thaJeztah** [comment]
@andrefreitas yes this looks similar to https://github.com/docker/docker/issues/16949, but this is with Docker Hub, not a private registry. Thanks for paying attention though!

**Comment by thaJeztah** [comment]
closing per https://github.com/docker/docker/issues/16959#issuecomment-147904418
