### ISSUE TITLE
The docker:dind image should include a `master` build

### ISSUE THREAD

**Issue by tomdee** [docker/docker#16967]
Now that Docker is integrating with an increasing number of third parties, it would be great if Docker could make it easier for others to run integration tests against pre-release versions of Docker. This would allow them to spot issues and regressions before they made it into releases.

The docker:dind image (https://hub.docker.com/_/docker/) is a great tool for testing but it only has tags for official releases. It should be easy to set up an automated build to update a `dind-master` on each checkin, but that's something that only Docker can easily do.

ping @jfrazelle @tianon @jpetazzo

**Comment by LK4D4** [comment]
Not sure it's worth efforts. You can build image from repo with simple script.

**Comment by LK4D4** [comment]
@tianon thanks for update!
