### ISSUE TITLE
docker pull --list --> flag provided but not defined: --list

### ISSUE THREAD

**Issue by anshum17** [docker/docker#16979]
I had to stop ongoing image pull. I googled around and found some references.
I might be naive asking this question, but when I run 'docker pull --list', I got 'flag provided but not defined: --list'. what is this thing related to. Couldn't find anything on this.
docker version - 1.8.2.
Can anyone help?

**Comment by cpuguy83** [comment]
There is no such flag `--list`.

Currently the only way to abort a pull (or push) is to restart the daemon.
See #6928
