### ISSUE TITLE
Premature opening of exposed ports.

### ISSUE THREAD

**Issue by svenwltr** [docker/docker#16976]
+kind/bug
+area/runtime
+exp/intermediate
+priority/P2

Exposed ports seem to get opened before the related port is getting opened in the container. This behaviour differs when using different IPs for the same host. This makes it hard to wait for opening a port.

### Dockerfile 

```
FROM fedora:22
RUN dnf install -y nmap-ncat iproute
COPY ./run.sh /run.sh
RUN chmod +x /run.sh
CMD ["/bin/bash", "/run.sh"]
```

### run.sh

```
#!/bin/sh
ip addr
echo "Wating 10 seconds."
sleep 10
echo "Listening on port 3333."
nc -l 3333 --keep-open
```

## steps reproduce

1. copy `Dockerfile` and `run.sh` into directory
2. `docker build .`
3. `docker run --publish "4444:3333" <imageid>`
4. within 10 seconds run:
   a. `nc localhost 4444`
   b. `nc 172.17.42.1 4444`

## actual results

```
$ nc localhost 4444
*waiting some time*
Ncat: Broken pipe.
```

```
$ nc 172.17.42.1 4444
Ncat: Connection refused.
```

## expected results

When calling both netcat commands within 10 seconds after `docker run`:

```
$ nc localhost 4444
Ncat: Connection refused.
$ nc 172.17.42.1 4444
Ncat: Connection refused.
```

## additional info

It seems the exposed port is immediately opened on localhost and reopenend after this port is available inside the container.

## system info

```
$ docker version
Client:
 Version:      1.8.2-fc22
 API version:  1.20
 Package Version: docker-1.8.2-1.gitf1db8f2.fc22.x86_64
 Go version:   go1.4.2
 Git commit:   f1db8f2/1.8.2
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2-fc22
 API version:  1.20
 Package Version: 
 Go version:   go1.4.2
 Git commit:   f1db8f2/1.8.2
 Built:        
 OS/Arch:      linux/amd64
```

```
$ docker info
Containers: 0
Images: 134
Storage Driver: devicemapper
 Pool Name: docker-253:1-396115-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 6.277 GB
 Data Space Total: 107.4 GB
 Data Space Available: 45.65 GB
 Metadata Space Used: 8.241 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.139 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93 (2015-01-30)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.8-200.fc22.x86_64
Operating System: Fedora 22 (Twenty Two)
CPUs: 8
Total Memory: 7.493 GiB
Name: svenwltr
ID: KCEW:VP6Y:VI4W:BH2K:2F62:SFJP:TGPP:HEKP:GKHJ:42TE:TUVZ:REWR
```

```
$ uname -a
Linux svenwltr 4.1.8-200.fc22.x86_64 #1 SMP Tue Sep 22 12:13:21 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by phemmer** [comment]
You can solve this by starting docker with `--userland-proxy=false`.
As it is, there is no way for the userspace proxy to not open its port until the container is listening. The proxy would have to poll the container indefinitely to match its state.

**Comment by cpuguy83** [comment]
yes, as @phemmer mentioned, this is expected behavior.
Docker starts up a proxy daemon to proxy local traffic to the container from the host port.
With `--userland-proxy=false` docker will not do this, and instead will use hairpin nat to forward the traffic to the container.

It is not possible for Docker to determine when the container is ready, or is at least out of scope for docker engine.
I would also recommend connecting directly to the container IP for local traffic rather than routing through the host.

**Comment by svenwltr** [comment]
Ok, thanks for your help!

I also would prefer to access the container directly, but I have to check how this can achieved by `docker-machine`.
