### ISSUE TITLE
Avoid creating container Id starting with digits

### ISSUE THREAD

**Issue by ginbalin** [docker/docker#16975]
Hello,

I have multiple time encountered an issue with the container which are assigned an ID starting with a digit. Indeed the container ID is also set as the host name of the container.
Although I know that according to the RFCs it is acceptable a hostname to start with a digit I many time had issue with with application code that refuse such cases.

Is it possible to restrict this with an option or to simply change docker engine to always assign an ID starting with a letter?

Thanks

**Comment by cpuguy83** [comment]
See #8194
Also note that you can provide your own hostname via the `-h` parameter on `docker run` or `docker create`
