### ISSUE TITLE
why not make mirror support a private v2 registry until now?

### ISSUE THREAD

**Issue by Kaffa-MY** [docker/docker#16974]
It's very easy to change the logic of endpoints in the function "lookupV2Endpoints" to put the mirror (remoteurl points to a private registry) in the final endpoint list even if the image is not in the hub, and in fact I find that mirrors can support private v2 registries after I rewrite few lines of codes. @stevvooe @RichardScothern

**Comment by thaJeztah** [comment]
@Kaffa-MY I'm going to close this issue for now, because I think it's better to discuss this in the #docker-distribution IRC channel first. Feel free to comment here though, after I've closed. Also, interested to hear what the outcome is of that discussion :+1:

**Comment by stevvooe** [comment]
@Kaffa-MY Without going into detail, the main issue here is trust and provenance. Basically, the registry controls the naming, so once you point the daemon at another registry, you can no longer trust the content if layers collide. We avoid these issues by disallowing arbitrary mirroring.

This is a situation we are working on resolving but it will take some effort to appropriately address.

**Comment by thaJeztah** [comment]
@stevvooe I see I actually forgot to close, but do you want this stay opened, or is this tracked already in your repo?

**Comment by stevvooe** [comment]
@thaJeztah This is described in the road map, I believe. @RichardScothern Do we have this documented anywhere?

**Comment by RichardScothern** [comment]
It is now: https://github.com/docker/distribution/pull/1136

**Comment by thaJeztah** [comment]
thanks all, I'll close this one!

**Comment by Kaffa-MY** [comment]
@stevvooe thanks for your reply
