### ISSUE TITLE
Initialization of vxlan failed with cluster-store in format ip:port/path

### ISSUE THREAD

**Issue by chanwit** [docker/docker#16983]
Description of problem:
Usually in `swarm`, we are setting up a store with the `ip:port/path` format. When doing so with the `--cluster-store` option, the vxlan id manager could not start.

```
Error response from daemon: failed to initialize vxlan id manager: failed to initialize bit sequence handler: Get http://104.236.192.190:8500/master/v1/kv/docker/libnetwork/idm/vxlan-id/?consistent=: dial tcp: unknown port tcp/8500/master
```

`docker version`:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   ed9434c
 Built:        Sun Oct 11 00:23:12 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

`docker info`:
Containers: 0
Images: 0
Engine Version: 1.9.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/0.0/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 1
Total Memory: 494.5 MiB
Name: node-1
ID: GWKV:EV4G:NZSL:TW5N:WSPR:HZVX:W5OG:AXYA:V7QJ:ZQTV:6XSX:DY25
Labels:
 provider=digitalocean
Experimental: true
Cluster store: consul://104.236.192.190:8500/master
WARNING: No memory limit support
WARNING: No swap limit support

`uname -a`:
Linux node-1 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
DigitalOcean

Steps to Reproduce:
1. Create an engine containing `--cluster-store ip:port/path` 
2. Create a multihost network with `$ docker network create -d overlay multihost`

Actual Results:
```
Error response from daemon: failed to initialize vxlan id manager: failed to initialize bit sequence handler: Get http://104.236.192.190:8500/master/v1/kv/docker/libnetwork/idm/vxlan-id/?consistent=: dial tcp: unknown port tcp/8500/master
```

Expected Results:
A network should be normally created.

**Comment by chanwit** [comment]
ping @mavenugo for the networking part
@abronan for libkv

**Comment by sanimej** [comment]
@chanwit cluster-store config needs only the ip and port. for ex: --cluster-store=consul://192.168.33.10:8500

**Comment by chanwit** [comment]
@sanimej it's cannot be like that for the discovery service. FYI, this cluster-store code is from `swarm` and what we've done there are allowing `/path` in the store URL.

Here's the reference:
https://github.com/abronan/docker/blob/fix_discovery_pkg_readme/pkg/discovery/README.md

Basically, we need to parse the cluster-store URL, chop the `/path` of for the networking stuff. But for the discovery service stuff, we should use the URL which include `/path`.

**Comment by sanimej** [comment]
path is not mandatory for discovery as well. To make progress now you can try without the path.

In libnetwork, yes, we have to remove the path from the url if its present. I will fix that.

**Comment by LK4D4** [comment]
@chanwit @sanimej issue is pretty old. Can we close it now?

**Comment by thaJeztah** [comment]
@chanwit I'll go ahead and close this, but ping me if this is still an issue
