### ISSUE TITLE
daemon failed to start when specify multiple cluster store address

### ISSUE THREAD

**Issue by coolljt0725** [docker/docker#17007]
When start docker daemon with flag `--cluster-store` and specify multiple store address for example `--cluster-store=etcd://9.81.1.161:2379,9.81.1.162:2379`, docker daemon will failed to start.
<pre><code>[root@fedora lei]# docker daemon  -s overlay --cluster-store=etcd://9.81.1.161:2379,9.81.1.162:2379
WARN[0000] Running experimental build
INFO[0000] API listen on /var/run/docker.sock
INFO[0000] Firewalld running: true
ERRO[0000] failed to get networks for scope global: client: etcd cluster is unavailable or misconfigured
FATA[0000] Error starting daemon: Error initializing network controller: Error creating default "bridge" network: failed to allocate gateway (172.17.42.1): No available addresses on this pool
[root@fedora lei]#</code></pre>
For the HA, we should specify multiple kv store address.
docker version
<pre><code>Client:
 Version:      1.9.0-dev
 API version:  1.22
 Go version:   go1.4.2
 Git commit:   7a19164
 Built:        Wed Oct 14 06:30:51 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.9.0-dev
 API version:  1.22
 Go version:   go1.4.2
 Git commit:   7a19164
 Built:        Wed Oct 14 06:30:51 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true
</code></pre>

docker info

uname 

Have some investigation and found it cause by `libnetwork/datastore`, working on fixing.

**Comment by mavenugo** [comment]
thanks @coolljt0725 . In addition to your fix in https://github.com/docker/libnetwork/issues/646 , it is also related to https://github.com/docker/libnetwork/issues/651 for a cleaner implementation at the datastore level to make sure a "perceived" mis-configuration doesnt fail ungracefully.

**Comment by mavenugo** [comment]
fixed by https://github.com/docker/libnetwork/pull/646. Vendored-in via #17191.

**Comment by djain13** [comment]
@mavenugo @coolljt0725 Can you throw some light around- whats the order in which docker daemon will consult etcd. Is it round-robin or random or always the first etcd node?
