### ISSUE TITLE
Add a log file driver for plaintext files

### ISSUE THREAD

**Issue by mikehaertl** [docker/docker#17020]
I wonder why there is no log driver for simple text based log files. I don't want JSON format. I want the same format as what I get from `docker logs` in a plaintext file.

So unless I've missed something I suggest a simple `file` log driver. It would also be nice if this driver offered a way to rotate the logs with logrotate, without messing things up (e.g. still logging to the old file after rotation).

**Comment by azurezk** [comment]
I would like to try on that:)

**Comment by thaJeztah** [comment]
thanks @azurezk! please note that it's not agreed on yet, so it could still be rejected in the PR.

I'll label this issue as "claimed" for you :+1:

**Comment by cpuguy83** [comment]
Docker supports rotating logs on the json file now, not via logrotate but via it's own mechanism based on size/time, and is safe for rotation.
I don't think it makes sense to store this on disk in a format that docker cannot really make sense of.
It would be better to create (or use an existing driver) that sends logs to some desired logging backend like syslog, journald, fluentd, etc.

**Comment by mikehaertl** [comment]
Guys, really? Please consider, that there are developers that still have a very simple custom infrastructure. You can not assume that everyone uses a logging backend. Believe it or not, some of us really still log to simple logfiles. You seem to cut off the lower end of the food chain :(.

Is it really so difficult to implement this simple file log driver?

**Comment by cpuguy83** [comment]
@mikehaertl Logging for what, exactly?
Can you not log to a file in a container if you want plain text?

Docker can literally do nothing with a plain text file, and we really don't want people messing around with stuff in /var/lib/docker.

**Comment by mikehaertl** [comment]
Say you have a legacy PHP application that is deployed on bare metal machine and runs PHP as an apache module. The log files are written to disk and rotated with logrotate. If there are problems with the site, the log files are the first thing I usually check.

Now I want to migrate this app to docker. So what was a simple Apache log file before should now be a Docker logfile. Right now I'd have to mess around with the syslog driver, which is a pain. Same for configuring a log file inside the container: It requires me to mess around with the default image configs.

Why would docker want to read that log file back in? And if that is so important, then why is there a syslog driver? Docker can't read from there either.

**Comment by cpuguy83** [comment]
That's the point. It's a plain text file that docker can do nothing with yet it is storing it internally.

**Comment by mikehaertl** [comment]
But why is there a `syslog' driver then? Docker probably can do nothing with it either.

**Comment by mikehaertl** [comment]
Maybe you can explain this a bit further. In my understanding a logging driver is an output stream. Docker sends container messages to some recipient. So you say, it's important, that docker can read this back in. That's quite counterintuitive to me. If I look at the existing loggin drivers (journald, gelf, fluentd, awslog), then docker can not read from *any* of them. So why is this a problem if the output would be a simple text file instead?

**Comment by cpuguy83** [comment]
@mikehaertl I'm not saying it's important for docker to be able to read this back in, but having a file in `/var/lib/docker` (or even a file that docker is creating/writing to) that docker can't actually do anything with is a bit weird.

**Comment by mikehaertl** [comment]
@cpuguy83 Of course the file path should be passed as an option. I just had a look at the `json-file` driver and was surprised that there is no such thing.

Again: All I want is really one simple human readable log file per container. For the poor guys among as that are in the process of migrating older apps to docker step by step. Not everyone has one of those log aggregator services available. And I can hardly think of any server software that can *not* log to a file. So hard to believe that it seems to be such a big issue for docker.

**Comment by thaJeztah** [comment]
Closing this issue per https://github.com/docker/docker/pull/17582#issuecomment-157544082. Thanks for suggesting @mikehaertl, and sorry this feature didn't get accepted

**Comment by mikehaertl** [comment]
Thanks. That's very disappointing.

Writing plaintext logs has been the standard on unix-like systems for decades. It's one of the core principles of these OSes that many things are text based and human readable. Look at Apache or Nginx as an analogy: It's easy to set up access- and error-logs in different formats for each Vhost. While it may not be top-notch anymore, there still *are* systems that depend on using raw log files, mainly for historical reasons.

Now you say, that docker can't do the same for a container? You seriously force your users to always use a log aggregator service to gather container logs? Honestly, that's not what I consider developer friendly.

You are basically now locking me out of using docker for reasons that sound unbelievable trivial and simple. I'm sorry, but I think something's going really wrong here.

**Comment by cpuguy83** [comment]
@mikehaertl You can still log to a file. This is about _docker's_ logging mechanism.

**Comment by mikehaertl** [comment]
@cpuguy83 Am I missing something? It seems to be a de-facto standard that containers write their log output to `stdout`/`stderr` (at least that's what the official base images do), instead of writing to a file on some volume. So if docker is able to convert this to JSON and then write it to a vile, what exactly is so hard to *not* convert it to JSON and write the unmodified entry to a file instead?

**Comment by mikehaertl** [comment]
Ok, I've done some more search on the topic and also read the notes in #7333 about why the sylsog driver is the way to go. Some first tests look good and with some simple rsyslog configs I should finally get what I wanted.

So thanks and sorry if my previous post sounded a bit too harsh.

**Comment by cpuguy83** [comment]
@mikehaertl Note that the json file driver does log rotation as well if that's something you are looking for.

**Comment by mikehaertl** [comment]
Thanks, but the syslog driver now does what I want.

For the record and just in case someone also needs this, here's my setup on a Ubuntu system.

**`docker-compose.yml`**

```
    [...]
    log_driver: "syslog"
    log_options:
        tag: "web"
```

**`/etc/rsyslog.d/30-docker-container`**

```
# Log docker messages to one file per container
$template DockerFileName,"/var/log/docker/%syslogtag:R,ERE,1,DFLT:docker/(.*)\[--end%.log"

# Log messages usually already contain a timestamp, so only log the raw message
$template DockerLog,"%msg%\n"
:syslogtag,startswith,"docker/" ?DockerFileName;DockerLog

# Do not pollute default syslog with docker messages
& ~
```

**`/etc/logrotate.d/docker-container`**

```
/var/log/docker/*.log
{
    rotate 2
    weekly
    missingok
    notifempty
    delaycompress
    compress
    postrotate
        reload rsyslog >/dev/null 2>&1 || true
    endscript
}
```

This gives me one logfile per container tag, for example `/var/log/docker/web.log`.

**Comment by rprieto** [comment]
Hi, just thought I'd add another use case in case the conversation can be re-opened. The `json-file` driver is very useful, however I have another case where I'd just like to have access to the raw logs as produced by the containers. For example, it's common for Node services to already output logs in [ndjson](http://ndjson.org/) format using [Bunyan](https://www.npmjs.com/package/bunyan) or [Bole](https://www.npmjs.com/package/bole), e.g.

```json
{"name":"my-app","hostname":"8734ba1eb853","pid":6,"level":30,"time":"2015-09-13T03:36:30Z","msg":"hello"}
```

Using the `json-file` driver, logs get written to `/var/lib/docker/containers/8734ba1eb853/8734ba1eb853-json.log` as

```json
{"container":"8734ba1eb853","time":"2015-09-13T03:36:30Z","stream":"stdout","log":"{\"name\":\"my-app\",\"hostname\":\"8734ba1eb853\",\"pid\":6,\"level\":30,\"time\":\"2015-09-13T03:36:30Z\",\"msg\":\"hello\"}"}
```

This means there's some duplication, but more importantly that any processing now requires extra commands to extract and un-escape the `log` field, for example using [Fluentd's parser plugin](http://docs.fluentd.org/articles/parser-plugin-overview), or

```bash
cat 8734ba1eb853-json.log | jq ".log" | python -c 'import json,sys;obj=json.load(sys.stdin);print obj;' | jq ".msg"
```

Being able to simply write the raw logs would make the setup a lot easier. I'll have a look at @mikehaertl's `syslog` setup (thanks a lot!) but it would sure be nice if we could do this out of the box.

**Comment by Hronom** [comment]
I have create small app to convert docker json logs online, check it out https://docker-json-log-converter.herokuapp.com/

**Comment by estani** [comment]
I downloaded via scp, because they where huge, and needed to properly see them.

This converts the json to text using `jq`
```sh
jq '.stream + " " + .time + " " + .log' docker.log | xargs printf '%b'
```
