### ISSUE TITLE
docker network inspect should inspect multiple networks

### ISSUE THREAD

**Issue by albers** [docker/docker#17023]
`docker inspect` allows you to inspect multiple containers/images in one invocation.
`docker network inspect` only accepts one network parameter. For consistency and for convenience, this should be adjusted.

**Comment by cpuguy83** [comment]
Tentatively adding to 1.9 since this is going to be expected and is already implemented in other commands.

**Comment by cpuguy83** [comment]
If anyone from core disagrees, feel free to change.

**Comment by albers** [comment]
@cpuguy83 Yes, this should be treated as a bugfix because a CLI feature that's missing in completion is a bug.
