### ISSUE TITLE
Image inconsistencies from AUFS to BTRFS

### ISSUE THREAD

**Issue by Kanshiroron** [docker/docker#17022]
Hello everyone,

We've noticed a bug when we create an image on a system using docker with aufs and loading it on a system using docker with btrfs (and not the other way). The issue is reproduced using docker save & docker load, and also with a private registry in the middle.
The scenario is quite simple ; consider the following Dockerfile:
```
FROM busybox
RUN mkdir /foo
RUN touch /foo/bar
RUN rm -r /foo && mkdir foo
```

On the computer with docker/aufs (the one that have generated the image) the `/foo` folder is empty, but when we load it on the docker/btrfs system it's not!
```shell
$ docker run --rm de54e6fa2fe4 ls -l /foo
total 0
-rw-r--r--    1 root     root           0 Oct 14 13:53 bar
```

(Nothing wrong was noticed in the docker logs)

Docker version 1.8.3, build f4bf5c7 (on all of them)
Docker/aufs : Ubuntu 14.04
Docker/btrfs : Debian 8.2 (btrfs v3.17 (lib version 101))
Registry v2 (official docker image): Docker/aufs on Ubuntu 14.04

Thanks for your help,
Best

**Comment by tonistiigi** [comment]
This should be fixed with #16470

**Comment by cpuguy83** [comment]
Please test this with the 1.9.0-rc1 release! - https://github.com/docker/docker/pull/17000#issuecomment-147926878
Thanks!

**Comment by thaJeztah** [comment]
ping @Kanshiroron have you been able to test this with the current release candidate?

**Comment by Kanshiroron** [comment]
Hello everybody,
Sorry for the late answer.
The problem has been fixed, tested on Docker version 1.9.0-rc3, build 2100b94 on both sides.

But I was able to reproduce it if I import the image (created with the rc3 on AUFS) on a older Docker version (1.8.3, build f4bf5c7) on a BTRFS filesystem. I thought the bug was on the AUFS side, isn't it?

Thanks,
Best

**Comment by tonistiigi** [comment]
@Kanshiroron The bug is in pull side, so this is consistent with what you are describing. If you upgrade your `btrfs` daemon this will also be fixed for the old images(after repulling).

**Comment by Kanshiroron** [comment]
Thanks for the precision
