### ISSUE TITLE
[1.9.0-rc1] Cancelling a build leaves artifacts in /tmp

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#17027]
When cancelling a build in progress, /tmp is littered with `trusted-dockerfile-465530198`
I've also seen it with `build-context` though I can't seem to reproduce that right now.

I assume this is the client dropping the file there.
This does not seem to happen on the OSX client for some reason... unless it's writing to a different tmp dir (which should be /private/tmp, which is what /tmp is pointing to).

**Comment by coolljt0725** [comment]
I can reproduce and can confirm this is drop by client since the client doesn't deal with ctrl-c when cancel the build

**Comment by calavera** [comment]
We decided with @tiborvass that this is not critical for 1.9. I removed it from the milestone.

**Comment by crosbymichael** [comment]
Temp files in /tmp are ok and will be removed by the host, it's fine to have these in there.
