### ISSUE TITLE
`docker inspect` issue in 1.9.0-rc1

### ISSUE THREAD

**Issue by awh** [docker/docker#17026]
````
$ docker version
Client:
 Version:      1.9.0-rc1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   9291a0e
 Built:        Wed Oct 14 03:07:34 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0-rc1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   9291a0e
 Built:        Wed Oct 14 03:07:34 UTC 2015
 OS/Arch:      linux/amd64
$ docker run -tid --name test busybox
56fcd6a8512e880465c84695e8669c17b74332a1ab9dc0369b8ac219e5ed577b
$ docker inspect -f '{{.State.Running}} {{.State.ExitCode}} {{.HostConfig.Dns}}' test
true 0 true 0 <no value>
````
Note that the string `true 0 ` is repeated erroneously. Here's the same on 1.8.3:

````
$ docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:27:08 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:27:08 UTC 2015
 OS/Arch:      linux/amd64
$ docker run -tid --name test busybox
$ docker inspect -f '{{.State.Running}} {{.State.ExitCode}} {{.HostConfig.Dns}}' test
true 0 []

````

**Comment by rade** [comment]
That `<no value>` vs `[]` for the DNS config looks wrong too, or is at least something that would merit mentioning in the docs  / release notes as a compatibility breaker.

**Comment by awh** [comment]
Possibly related to #15566

**Comment by duglin** [comment]
yep was thinking the same thing - @awh if you think its the same please close as a dup.

**Comment by awh** [comment]
> if you think its the same please close as a dup.

I am not certain that it is - in this case all the template substitutions are valid. Here's what happens if I have a value in `.HostConfig.Dns`:

````
$ docker inspect -f '{{.State.Running}} {{.State.ExitCode}} {{.HostConfig.Dns}}' c2
false 0 false 0 [172.17.42.1]
````
Bizarrely, If I switch the template expressions around the problem goes away:
````
$ docker inspect -f '{{.HostConfig.Dns}} {{.State.Running}} {{.State.ExitCode}}' c2
[172.17.42.1] false 0
````
So there could actually be three issues here - #15566, the duplication shown here, and also the fact that `docker inspect -f {{.HostConfig.Dns}}` is now returning `<no value>` instead of `[]` when `.HostConfig.Dns` is `null`. All three need investigation.

**Comment by cpuguy83** [comment]
Well, the real field name is `DNS` now.

**Comment by cpuguy83** [comment]
Which is probably why the strange behavior is happening.

**Comment by duglin** [comment]
which sounds like the other one.

**Comment by rade** [comment]
Sounds like https://github.com/docker/docker/pull/15567#issuecomment-132446966, i.e. template execution trips over the `Dns` and then re-executes, looking at the JSON. And the output of both runs is collated. Which is obviously a bug.

> Well, the real field name is `DNS` now.

Combined with the buggy behaviour, that is a pretty serious compatibility issue, because old dockers do not understand `DNS`, and new dockers do not (correctly) understand `Dns`, so atm there is no way to write code that works with both.

**Comment by awh** [comment]
> Well, the real field name is DNS now.

How might I have discovered this, given the following?

````
$ docker inspect test|grep -c DNS
0
$ docker inspect test|grep Dns
        "Dns": null,
        "DnsOptions": null,
        "DnsSearch": null,
````

**Comment by cpuguy83** [comment]
@awh this is due to the internal struct type having "DNS" and the json marshaller marshals it to "Dns".
The formatter first uses the internal struct and then falls back to the raw json (for a number of issues).

**Comment by rade** [comment]
This got broken by #15310. Which is not present in 1.8.x.

Is this going to get fixed before 1.9 goes out? It is a pretty serious breakage.

**Comment by runcom** [comment]
on it, basically #15310.didn't add the correct json tags to maintain compatibitlity at inspect/api layer, will look into it

**Comment by LK4D4** [comment]
I don't know how we can fix this. Because inspect doesn't uses any tags.

**Comment by runcom** [comment]
https://github.com/docker/docker/pull/15567 should fix this

**Comment by LK4D4** [comment]
@runcom It's not fixes problem that people used `Dns` in their templates :)

**Comment by runcom** [comment]
true that sadly..

**Comment by calavera** [comment]
The real fix for this is in #17284.

**Comment by wenchma** [comment]
but I got the following, is it right ? :question: 

    root@56ad636cf819:/go/src/github.com/docker/docker# docker inspect -f '{{.HostConfig.Dns}}' container1
    Template parsing error: template: :1:13: executing "" at <.HostConfig.Dns>: Dns is not a field of struct type *runconfig.HostConfig
    root@56ad636cf819:/go/src/github.com/docker/docker# docker -v
    Docker version 1.10.0-dev, build c920895-dirty
    root@56ad636cf819:/go/src/github.com/docker/docker# go version
    go version go1.5.1 linux/amd64

**Comment by thaJeztah** [comment]
@wenchma yup, there was another issue, it's being worked on for 1.9.1; see https://github.com/docker/docker/issues/17680
