### ISSUE TITLE
docker cp completion not correct

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#17029]
Completion for `docker cp` only seems to work for the case of `docker cp <container>:<path> <client path>`

And not for `docker cp <client path> <container>:<path>`
This functionality was added in 1.8

Confirmed on zsh and bash.

Also the `<path>` on the container side is resolving to local/client paths which is not correct (at least in ZSH).
Note that there is an API to stat container paths, but no client UI... so may not be feasible for completion.

I did take a stab at this for zsh, but really not sure the correct way to handle both cases properly.

**Comment by cpuguy83** [comment]
ping @albers in case you are interested.

**Comment by thaJeztah** [comment]
and @sdurrheimer for zsh :)

**Comment by sdurrheimer** [comment]
`docker cp` is quite hard to autocomplete. There is no option to differentiate `container-to-host` to `host-to-container`.

Same for the `container path`. Don't know how to do it.

**Comment by cpuguy83** [comment]
Indeed.
I thought to look at the scp completion, but can't work out how to map that to docker co.

**Comment by albers** [comment]
We could make completion for the second argument dependent on the type of the first one: if a local file exists under the given name, complete containers, if it is a container, complete local files.

**Comment by sdurrheimer** [comment]
@albers As I said, don't know yet how to do it in zsh since the first argument can be a file or a container.

**Comment by albers** [comment]
@cpuguy83 proposed solution in #17153

**Comment by albers** [comment]
@cpuguy83 @thaJeztah This was fixed in #17153 and IMHO can be closed.

**Comment by thaJeztah** [comment]
Thanks @albers! I'll close \o/

**Comment by theSoenke** [comment]
works on bash, but not on zsh
