### ISSUE TITLE
docker service command seems to be broken in ed9434c

### ISSUE THREAD

**Issue by rcgoodfellow** [docker/docker#17033]
Hi Folks,

I have been using the libnetwork capabilities in docker for a few weeks now and everything has been going quite smoothly. However, I just upgraded the docker binary on one of my machines to ed9434c
```
$ docker version
Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   ed9434c
 Built:        Sun Oct 11 00:28:14 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   7001619
 Built:        Wed Sep 23 17:48:55 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true
```
and now the `docker service` command seems to be broken
```
$ docker service
docker: 'service' is not a docker command.
See 'docker --help'.
```

The `docker service` command worked fine under the following setup
```
$ docker version
Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   1e514de
 Built:        Thu Sep 24 16:59:15 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   7001619
 Built:        Wed Sep 23 17:48:55 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true
```
```
$ docker service ls
SERVICE ID          NAME                NETWORK             CONTAINER
```

**Comment by rcgoodfellow** [comment]
Sorry I did not submit all the required ticket info. Here is the rest. This setup is running through docker machine to a remote host, which is why you see the two different Linux versions. However, even when running locally, I should be able to do a `docker service ls` right? I have tested running `docker service ls` on the remote machine that docker-machine is connecting to and it works fine. That machine is running a build from 1e514de which is the same local build that was working prior to the update.

```
$ uname -a
Linux abby 3.19.0-30-generic #34-Ubuntu SMP Fri Oct 2 22:08:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ docker info
Containers: 9
Images: 17
Engine Version: 1.9.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 35
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-28-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 24
Total Memory: 23.51 GiB
Name: marina
ID: MMNL:WUCU:BFZS:BDO5:5S55:3S4I:TB4S:RYSN:2OGR:KK4E:RL3H:DHPO
Username: rgoodfel
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=generic
 com.docker.network.driver.overlay.bind_interface=eth5
Experimental: true
```

**Comment by cpuguy83** [comment]
`docker service` does not exist anymore.

**Comment by cpuguy83** [comment]
Also see `docker network connect` and `docker network disconnect` which essentially replaces that.

**Comment by rcgoodfellow** [comment]
Thanks @cpuguy83 for the quick response! I thought it would be something like that but could not find any pointers to `docker service` being gone.
