### ISSUE TITLE
docker info believes my OS is containerized

### ISSUE THREAD

**Issue by mbentley** [docker/docker#17037]
Description of problem:
The output of `docker info` shows that my Operating System is containerized when it is not.  I've seen this in 1.8.3 and also with 1.9.0-rc1 so it isn't something specific to rc1.

`docker version`:

```
$ docker version
Client:
 Version:      1.9.0-rc1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   9291a0e
 Built:        Wed Oct 14 02:48:58 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0-rc1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   9291a0e
 Built:        Wed Oct 14 02:48:58 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:

```
$ docker info
Containers: 0
Images: 2
Engine Version: 1.9.0-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 2
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux stretch/sid (containerized)
CPUs: 2
Total Memory: 1.963 GiB
Name: localdev
ID: ABO2:4REM:BS7R:OXYG:R7V6:UJGL:2YTX:CJ7H:UEYY:IK7O:JXYQ:YBYX
Username: migratortest
Registry: https://index.docker.io/v1/
```

`uname -a`:

```
$ uname -a
Linux localdev 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.):
Debian Sid running kernel from Jessie; VirtualBox 5.0.6r103037 on OS X

How reproducible:
Every time

Steps to Reproduce:
1. Type `docker info`
2. Read the text
3. Wonder if I am accidentally running from inside a container

Actual Results:
`docker info` thinks that I am in a container

Expected Results:
`docker info` not thinking I am in a container

Additional info:
I'm quite certain that I am not running this from inside a container.

**Comment by thaJeztah** [comment]
Think this is detected in https://github.com/docker/docker/blob/729c9a97822ebee2c978a322d37060454af6bc66/pkg/parsers/operatingsystem/operatingsystem_linux.go#L33 
Which was added in https://github.com/docker/docker/pull/7215

/cc @tiborvass :)

**Comment by tiborvass** [comment]
@mbentley what's the content of `/proc/1/cgroup` ?

**Comment by mbentley** [comment]
@tibor:

```
# cat /proc/1/cgroup
9:memory:/init.scope
8:net_cls,net_prio:/
7:cpuset:/
6:freezer:/
5:devices:/init.scope
4:blkio:/init.scope
3:cpu,cpuacct:/init.scope
2:perf_event:/
1:name=systemd:/init.scope
```

**Comment by boynux** [comment]
The issue seems to be related to this: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=798778/sid

Seems systemd update 226 moves init script into a separate cgroup (init.scope).
Does it makes sense add this check in `IsContainerized` method?

**Comment by pmalmgren** [comment]
@tiborvass @boynux I've ran into this problem as well on Arch Linux and would like to claim/fix this issue. Is there any problem with putting the fix in the ``IsContainerized`` method?

**Comment by thaJeztah** [comment]
@pmalmgren thanks for working on this! Fixing it as part of the `IsContainerized` method sounds good, but can be further discussed when reviewing your pull request :+1:
