### ISSUE TITLE
Bind mounts behaving strangely on Windows

### ISSUE THREAD

**Issue by atrauzzi** [docker/docker#17044]
I'm not sure if this is a known issue already, but I've been using docker-compose to configure a container layout.  When I specify bind mounts, I get some odd behaviour.

In one case, a directory from the host shows up, but everything else (and there are a lot of files!) is missing.  In other cases, files written by the running container aren't visible to the host.

I'm running on Windows 10, using the currently available Docker Toolbox.  I am running docker-compose via a pip install and just reinstalled it recently.  So I think I'm running a fairly current rc?

**Comment by cpuguy83** [comment]
A couple of things to note:

1. Bind-mounts mount a dir on the docker host into the container. In this case your docker client is a remote client
2. With toolbox + hyperv (or virtualbox, vmware, etc.), your user dir is being mounted into the docker VM

Given point 2, it would seem like you can mount dirs from the client into the daemon but it's just a hack to make life a little easier.

Also, currently when a host dir does not exist docker will create an empty dir and mount that in.

Can you provide some repro steps that's causing each behavior?

**Comment by atrauzzi** [comment]
Here's the `docker-compose.yml`: https://github.com/atrauzzi/bryophyte/blob/develop/docker-compose.yml

Here's the fpm container definition: https://github.com/atrauzzi/bryophyte/blob/develop/laravel/Dockerfile.fpm

Here's the nginx container definition: https://github.com/atrauzzi/bryophyte/blob/develop/laravel/Dockerfile.nginx

What's happening is I'm binding the [https://github.com/atrauzzi/bryophyte/tree/develop/laravel](laravel directory) found here, but in my containers, all I see is the `public` directory.  Again, very odd because it's seemingly mounting *something*.  It just only ends up containing the `public` subdirectory and nothing else.

All on Windows 10.

**Comment by thaJeztah** [comment]
@atrauzzi is this still an issue for you?

**Comment by atrauzzi** [comment]
I'd say close for now.  More important stuff
