### ISSUE TITLE
docker network disconnect hangs using overlay driver

### ISSUE THREAD

**Issue by rcgoodfellow** [docker/docker#17041]
When I attempt to disconnect a container from an overlay network the command hangs

__my setup info__

```
$ uname -a
Linux marina 3.19.0-28-generic #30~14.04.1-Ubuntu SMP Tue Sep 1 09:32:55 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ docker info
Containers: 2
Images: 4
Engine Version: 1.9.0-dev
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-28-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 24
Total Memory: 23.51 GiB
Name: marina
ID: MMNL:WUCU:BFZS:BDO5:5S55:3S4I:TB4S:RYSN:2OGR:KK4E:RL3H:DHPO
WARNING: No swap limit support
Labels:
 com.docker.network.driver.overlay.bind_interface=eth5
Experimental: true
Cluster store: consul://localhost:8500
```
```
$ docker version
Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   ed9434c
 Built:        Sat Oct 10 23:54:27 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   ed9434c
 Built:        Sat Oct 10 23:54:27 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true
```

I am starting docker like this (have also tried with aufs with same results)
```
$ sudo docker daemon -s overlay -H unix:///var/run/docker.sock --cluster-store=consul://localhost:8500 --label=com.docker.network.driver.overlay.bind_interface=eth5
```

__reproducing the problem__
I start of by creating a few containers and connecting them to an overlay network
```
$ docker network create -d overlay nt
11785bf709d4cf7029e50c52ee277d186bd7efc1ec7e3899e0a8263431aa6efa
$ docker run -itd --name=aa --hostname=aa ubuntu:15.04 bash 
38620ac7245deb69a9c4a5d9e1849c49c927c4fe52acbc57f231e1c16b95003e
$ docker run -itd --name=bb --hostname=bb ubuntu:15.04 bash
6edd83fce8356f4378bbf3fc4ae3927747c706d34304a4022cc25532d454a10e
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
6edd83fce835        ubuntu:15.04        "bash"              5 seconds ago       Up 4 seconds                            bb
38620ac7245d        ubuntu:15.04        "bash"              24 seconds ago      Up 23 seconds                           aa
$ docker network connect nt aa
$ docker network connect nt bb
$ docker exec -it aa bash
root@aa:/# apt-get install -y ping
...
root@aa:/# ping bb
PING bb (172.17.0.2) 56(84) bytes of data.
64 bytes from bb (172.17.0.2): icmp_seq=1 ttl=64 time=0.175 ms
64 bytes from bb (172.17.0.2): icmp_seq=2 ttl=64 time=0.059 ms
^C
--- bb ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 999ms
rtt min/avg/max/mdev = 0.059/0.117/0.175/0.058 ms
root@aa:/# exit
exit
```
so far so good, now time to disconnect
```
$ docker network disconnect nt bb
```
this just hangs so I give it a CTL-C and then inspect the network. The endpoint appears to be gone in this view.
```
^C $ 
$ docker network inspect nt
{
    "name": "nt",
    "id": "11785bf709d4cf7029e50c52ee277d186bd7efc1ec7e3899e0a8263431aa6efa",
    "driver": "overlay",
    "containers": {
        "38620ac7245deb69a9c4a5d9e1849c49c927c4fe52acbc57f231e1c16b95003e": {
            "endpoint": "b997263e7953e6d196b60ef057ef4bd06333b4ea79ebdac990434d1d5a0b0c58",
            "mac_address": "02:42:ac:15:00:01",
            "ipv4_address": "172.21.0.1/16",
            "ipv6_address": ""
        }
    }
}
```
I repeat the process for the other node ``aa``. Have to CTL-C again, but now I do see an empty network which feels like progress. 
```
$ docker network inspect nt
{
    "name": "nt",
    "id": "11785bf709d4cf7029e50c52ee277d186bd7efc1ec7e3899e0a8263431aa6efa",
    "driver": "overlay",
    "containers": {}
}
```
However when I try to remove the network itself it fails saying it has active endpoints.
```
$ docker network rm nt
Error response from daemon: network with name nt id 11785bf709d4cf7029e50c52ee277d186bd7efc1ec7e3899e0a8263431aa6efa has active endpoints
```
I have been kinda getting around this by using stopping the docker daemon and using the following
```
$ curl -X DELETE http://localhost:8500/v1/kv/?recurse
```
which seems to clear things out. But this process is not really feasible from the tooling and automation we are currently trying to build.

__other info__
+ this problem does not crop up when using the `bridge` networking driver
+ this process was working before using the exact same underlying OS and machine but with an older docker version which used the `service publish/unpublish` mechanism.

Thanks

ry

**Comment by mbentley** [comment]
I am seeing the same with the `overlay` network driver in docker 1.9.0-rc1.

```
$ docker network inspect multihost
{
    "name": "multihost",
    "id": "e310a07581e2fc4d90ea35265ce390768b779c4f1d6787a155ca6a7947af1b27",
    "scope": "global",
    "driver": "overlay",
    "ipam": {
        "driver": "default",
        "config": [
            {}
        ]
    },
    "containers": {}
}
```

```
$ docker network rm multihost
Error response from daemon: network multihost has active endpoints
```

**Comment by mavenugo** [comment]
@rcgoodfellow @mbentley apologies in advance for the lacking complete documentation. Its being worked on. With the latest 1.9.0-rc1, the flags have changed and multi-host networking makes use of native docker discovery with just the 2 flags introduced in discovery -

`--cluster-store=consul://localhost:8500 --cluster-advertise=<ip-address-bind-interface>`
in your case, use the ip-address of eth5.

@moxiegirl is working on complete revamp of the documentation and we will have them in next week.

**Comment by mavenugo** [comment]
@mbentley fyi `docker network inspect multihost` displays only the containers present in the local node. But, since the multihost network is cluster-wide, you have to make sure all the containers cluster-wide is removed from the network before you can delete the network.

We were contemplating of adding a new `docker network rm -f <network>` but that is more disruptive if the user is not careful.

Hence, pls make sure all the containers across the cluster is removed before attempting to remove the network.

**Comment by mbentley** [comment]
Hmm, well that is certainly interesting.  It would appear that container cleanup didn't successfully remove all data as there weren't any containers on both of my nodes.  A quick restart of my VMs resolved it so I no longer have the same broken state.

**Comment by mavenugo** [comment]
@mbentley ok. I will try to reproduce it. but, since the network states are in the kv-store, the states dont get removed even after reboot. So, I have to check how a restart would help.

**Comment by mbentley** [comment]
I was able to get it to reproduce on a 2 node swarm cluster (swarm 1.0.0-rc1) using this quick script (and running it a number of times):

```
echo -e "\nStarting container on 'swarm-0'..."
docker run -d \
  --name="long-running" \
  --net="multihost" \
  --env="constraint:node==swarm-0" \
  busybox top

echo -e "\nStarting container on 'swarm-1'..."
docker run --rm \
  --net="multihost" \
  --env="constraint:node==swarm-1" \
  busybox ping -c 4 long-running

echo -e "\nRemoving container on 'swarm-0'..."
docker rm -fv long-running
```

I ran this several times until I received an error:

```
Starting container on 'swarm-1'...
Error response from daemon: Cannot start container d2da0d8676131043581011566e46f53b5be8aa6f7803ee2e120095075a8afc49: subnet sandbox join failed for "10.0.0.0/24": bridge creation in sandbox failed for subnet "10.0.0.0": invalid argument
```

As you can see, it is not showing any containers listed from either node:

```
$ docker network inspect swarm-0/multihost; docker network inspect swarm-1/multihost
{
    "name": "multihost",
    "id": "323b5281f3f77aa3790020894a712378c31cdba2cd6763b66e46539466ca138e",
    "scope": "global",
    "driver": "overlay",
    "ipam": {
        "driver": "default",
        "config": [
            {}
        ]
    },
    "containers": {}
}
{
    "name": "multihost",
    "id": "323b5281f3f77aa3790020894a712378c31cdba2cd6763b66e46539466ca138e",
    "scope": "global",
    "driver": "overlay",
    "ipam": {
        "driver": "default",
        "config": [
            {}
        ]
    },
    "containers": {}
}
```

I'm guessing something is occurring in the error that is causing the condition.  If you need further information such as my environment setup and how to set it up, I can provide that.  I have a script I am using on OS X that will stand up 3 boot2docker VMs using docker-machine on VirtualBox.

**Comment by mavenugo** [comment]
@mbentley thanks. that answers. this is a dupe of https://github.com/docker/docker/issues/17083 and @mrjana is working on a fix for this.

**Comment by mbentley** [comment]
Great, thanks for the super quick follow up!

**Comment by mavenugo** [comment]
@mbentley thanks for the script. it is super-useful.

**Comment by thaJeztah** [comment]
@mavenugo should this be closed as dup of #17083? I see the other issue is on the milestone and being associated with the bug fix?

**Comment by rcgoodfellow** [comment]
@mavenugo @mbentley thanks for the very quick followup! I have the information I need now to move forward. Closing the ticket as there is a working solution that is not a workaround, just isn't documented yet.

**Comment by thaJeztah** [comment]
Thanks @rcgoodfellow, and thanks for reporting!
