### ISSUE TITLE
volume removal behavior unexpected when using `--rm` in run command

### ISSUE THREAD

**Issue by mbentley** [docker/docker#17040]
Description of problem:
With the new `docker volumes` features in 1.9.0-rc1, some behavior is a bit unexpected when working with pre-existing volumes.  For example, if I manually create a volume for use, run a quick container that is attached to it using `docker run -it --rm -v myvolume:/data debian:jessie`, do some quick tasks with my data and then exit the container, my volume gets removed along with the container if no other containers are using it.

This makes sense from a legacy standpoint because of how `--rm` works but it doesn't really make sense now that we can manage volumes.  If the volume existed before I started my container, I do not think that `--rm` should remove the volume, it should persist until I tell it that it should be removed.  Whether this is some sort of flag that I can set on the daemon or whatever, it seems like trusting my data in volumes that are managed by docker can be troublesome from a data persistence standpoint.

`docker version`:
$ docker version

```
Client:
 Version:      1.9.0-rc1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   9291a0e
 Built:        Wed Oct 14 02:48:58 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0-rc1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   9291a0e
 Built:        Wed Oct 14 02:48:58 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:

```
Containers: 0
Images: 2
Engine Version: 1.9.0-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 2
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux stretch/sid (containerized)
CPUs: 2
Total Memory: 1.963 GiB
Name: localdev
ID: ABO2:4REM:BS7R:OXYG:R7V6:UJGL:2YTX:CJ7H:UEYY:IK7O:JXYQ:YBYX
Username: mbentley
Registry: https://index.docker.io/v1/
```

`uname -a`:

```
Linux localdev 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.):
VirtualBox 5.0.6r103037, Debian Sid

How reproducible:
All the time

Steps to Reproduce:
1. Create a volume: `docker volume create --name test`
2. Run a container that uses the volume: `docker run -it --rm -v test:/data debian:jessie`
3. Exit the container and see that the volume is no longer there: `docker volume ls`

Actual Results:
Volume that I created and manage manually was automatically removed.

Expected Results:
Volume that I created and manage manually shouldn't be automatically removed.

Additional info:

**Comment by cpuguy83** [comment]
See #16809
