### ISSUE TITLE
reload group cache "sudo usermod -aG docker $USER"

### ISSUE THREAD

**Issue by denji** [docker/docker#17050]
I think the current version after installing docker on ubuntu not enough call command to clean the cache group `docker`:

```
If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker $USER

Remember that you will have to log out and back in for this to take effect!
```

We should cause newgrp to force updating groups cache without re-login account:

``` bash
$ newgrp docker
```

Use the commands below to provide key information from your environment:

`docker version`:

```
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:42:26 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:42:26 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:

```
Containers: 1
Images: 7
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 9
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.0-11-generic
Operating System: Ubuntu Wily Werewolf (development branch)
CPUs: 2
Total Memory: 989.1 MiB
Name: ubuntu
ID: K2ET:4NZ2:NUUP:V7ON:QWYU:NK2W:URV6:USY2:XGQO:N3KA:6XS7:CUUG
```

`uname -a`:

```
Linux ubuntu 4.2.0-11-generic #13-Ubuntu SMP Mon Sep 21 21:33:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Provide additional environment details (AWS, VirtualBox, physical, etc.): [xhyve](https://github.com/mist64/xhyve) Hypervisor.framework in OS X
List the steps to reproduce the issue: –
Describe the results you received: –
Describe the results you expected: –
Provide additional info you think is important: –

**Comment by thaJeztah** [comment]
closing because this issue is very old now, and we didn't get more people requesting this. In addition, the _manual_ installation procedure is overall preferred over using the script
