### ISSUE TITLE
Docker RPM overwrites user configuration of systemd service

### ISSUE THREAD

**Issue by AaronDMarasco-VSI** [docker/docker#17067]
The file `/usr/lib/systemd/system/docker.service` should be marked as `%config(noreplace)` in the RPM spec file.

For my installation, I have to add a "`-g /export/docker`" to `ExecStart` to move the default storage location. When upgrading the RPM, that shouldn't be replaced.

My system in particular is CentOS 7, but that should not be relevant.

**Comment by cpuguy83** [comment]
You should not be changing the systemd unit file for docker.
Instead you can use a dropin, which is the supported way to overwrite settings in systemd.

**Comment by AaronDMarasco-VSI** [comment]
OK, I see that now, thanks.

For the next guy who has no idea what a dropin is...
```
sudo mkdir /etc/systemd/system/docker.service.d
sudo vi /etc/systemd/system/docker.service.d/00-move-library.conf
# Make the new file have this content (that empty assignment counts!):
$ cat /etc/systemd/system/docker.service.d/00-move-library.conf
[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon -H fd:// -g /export/docker
# EOF
sudo systemctl daemon-reload
sudo service docker restart
docker images # ensure any images are still there
```

**Comment by cpuguy83** [comment]
@AaronDMarasco-VSI Thanks for that!

**Comment by ioggstream** [comment]
At least in this phase, I strongly suggest to add a "DO NOT EDIT" disclaimer on top of this file.

**Comment by AaronDMarasco-VSI** [comment]
That would be smart. Maybe a URL pointing to the proper configuration
method as well.
