### ISSUE TITLE
/volumes and /networks with "filter" or "filters" query parameter?

### ISSUE THREAD

**Issue by gesellix** [docker/docker#17091]
The `GET /volumes` remote api [query parameter](https://github.com/docker/docker/blob/master/api/server/router/local/volume.go#L17) "**filters**" (plural) is consistent with similar list commands (e.g. `GET /images`), but the [v1.21 docs](https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api_v1.21.md#list-volumes) state that the parameter is named "**filter**" (singular).

Which one is correct? I guess the docs are wrong, and if so, I could provide a PR to fix them. If the docs are right and the param was meant to be **filter** (singular), I'd like to discuss about consistency to the other endpoints ;-)

**Comment by gesellix** [comment]
P.S. the same applies to `GET /networks` and the docs for that endpoint.

**Comment by cpuguy83** [comment]
Indeed, the doc is incorrect. `filters` is the right name in both cases.

**Comment by gesellix** [comment]
:+1:  ok, I'll create a PR

**Comment by gesellix** [comment]
@cpuguy83 see #17127
