### ISSUE TITLE
add CONTAINER_LABELS to journald

### ISSUE THREAD

**Issue by KostyaSha** [docker/docker#17095]
Please add labels to journald fields. imho CSV delimiter could be enough.

**Comment by vdemeester** [comment]
Hi @KostyaSha,

I think the feature you're looking for is implemented in #16961 and will be available with the 1.9 release of docker.

If you feel it's what your looking for, you can close the issue, otherwise, we can discuss on it :wink:

**Comment by KostyaSha** [comment]
I used search, sems it was without closed issue. Closing this
@vdemeester maybe if you have time, could you debug log drivers for ram leaking? I think that log drivers should have configurable buffer either on huge stdout docker daemon dies.
