### ISSUE TITLE
Implement autocomplete generators

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#17114]
Right now, through the help of some fantastic folks like @albers and @sdurrheimer, autocompletion scripts for bash, zsh, and fish are part of this repo.

It would be really awesome if we could auto-generate these completion scripts from source rather than continuously having to play catch up.

**Comment by thaJeztah** [comment]
Actually, for fish, there's already a generator; https://github.com/docker/docker/blob/master/contrib/completion/fish/docker.fish#L3-L4

**Comment by LK4D4** [comment]
Yeah, would be cool.

**Comment by thaJeztah** [comment]
I think this is possible with Cobra - didn't we have another issue for tracking that? @dnephin

**Comment by dnephin** [comment]
We had issues for auto-generating docs, but I don't remember seeing any for autocomplete

**Comment by thaJeztah** [comment]
perhaps we discussed it in that issue, that's possible. Looks like (currently) Cobra only supports *bash* completion, so if we'd like to have completions for other shells that would need a contribution to the Cobra repo; https://github.com/spf13/cobra/blob/master/bash_completions.md

I know a lot of work / manual tweaking has gone into our current completion scripts, so I have no idea if (with proper templates), automatic generation would result in the same level of quality as we current have, but perhaps it's worth looking into, to see how flexible Cobra is.

ping @albers @sdurrheimer wdyt?

**Comment by albers** [comment]
Here are my thoughts:

Generated completion is desirable, but not at the expense of poor quality. The generation should also increase maintainablility.

In detail:

## quality
Docker's bash completion is very advanced. This makes it not only a timesaver but also a tool for exploring the Docker CLI.
If you don't remember whether the filter for running containers is called `state` of `status`, no problem, 
`docker ps -f s<tab>` will tell you. What are the available states? Just another tab.

**A generated completion should come as close as 90% to the current state.**

## split logic
Imagine an autogenerated completion script. Generation would be easy for the available commands and subcommands, for the available options and their values if they are boolean or enumerations. For all other cases the code could contain meta-information that links to bash functions that implement special behavior.
In such a scenario, logic would be split between two systems: go code that is responsible for the mapping, and bash code in the template that acually implements the logic. I think the resulting system will be hard to maintain. It will require more skills than manually created completions.

## generating completions on the fly
I can imagine a system where the Docker command generates the individual completions on the fly.
The bash completion script would be just a tiny function that passes `cur` `prev` `words` and `cword` to a new hidden Docker command.
This command generates the code block that is necessary to perform the current completion and outputs it to stdout (which allows easy debugging). Back in the calling bash function, this code would be `eval`ed.

### Example

typing `docker run --log-opt gelf-compression-type=<tab>`

would call
```
docker complete --shell bash --cur "=" --prev "gelf-compression-type" "docker" "run" "--log-opt" "gelf-compression-type" "="
```
which would output this snippet:
```
COMPREPLY=( $( compgen -W "gzip none zlib" -- "${cur##*=}" ) )
```

For `docker ps -f`, the snippet would be
```
COMPREPLY=( $( compgen -S = -W "ancestor before exited id label name network since status volume" -- "$cur" ) )
compopt -o nospace
```

`--env-file` would lead to the snippet `_filedir`

For this to work, the framework would have to be able to parse the command line into commands, subcommands, options and values of different kinds. Map values and their individual value spaces have to be enumerable/computable.
Each heirarchy level will have to route the completion request to the next downstream level, accumulating state (completion might depend on other options present in the command line). Each level must know how to generate the snippet (using subtypes for different completion schemes). Only for very rare times we should fall back to split logic, i.e. a link to a hardcoded function in the bash script.

Most of this should be implemented in cobra.

**Comment by albers** [comment]
There was an attempt for autogenerated bash completion in docker-machine: https://github.com/docker/machine/pull/1309, which was superseded by a traditional approach in https://github.com/docker/machine/pull/1993

**Comment by thaJeztah** [comment]
Wow, thanks for the excellent write up there, @albers. 

> A generated completion should come as close as 90% to the current state.

I agree. I think that (although auto-generated would be really _cool_), there currently isn't a direct need. We have an awesome team in @albers, and @sdurrheimer to help us out with the completion scripts, and, in fact, while doing so, helped us find actual bugs and inconsistencies in the code base on multiple occasions.

Unless someone wants to explore options, and invest time in "teaching" Cobra how to write advanced completion scripts (not only for Bash, but also zsh, and fish), I'm inclined to close this.

@cpuguy83 @dnephin wdyt?

**Comment by cpuguy83** [comment]
Agree. It would be pretty difficult to do this, and the solution probably wouldn't truly be autogenerated.
