### ISSUE TITLE
Deprecate '-c' short variant flag for 'docker build' and 'docker create'

### ISSUE THREAD

**Issue by sdurrheimer** [docker/docker#17117]
As I say on #17101.

Given that `-c` (cpu-shares) flag as been removed from `docker run` in #16271, I think it should also be removed from `docker build` and `docker create` for consistency.

**Comment by thaJeztah** [comment]
ping @tiborvass @runcom in case you think this would be consistent for the 1.9 release

**Comment by tiborvass** [comment]
+1 please PR, will add it to 1.9.0 since this would be inconsistent otherwise.

**Comment by runcom** [comment]
+1 (how do I missed this)

**Comment by thaJeztah** [comment]
@runcom np, you're creating a PR?

**Comment by runcom** [comment]
@thaJeztah I can't now cause I don't have my laptop with me :( if nobody is gonna do this before Monday I'll do it btw

**Comment by vdemeester** [comment]
@runcom @thaJeztah I can take care of it :stuck_out_tongue_closed_eyes:

**Comment by thaJeztah** [comment]
@vdemeester sgtm, I was about to give it a go, but you're probably faster than I am :+1:

**Comment by runcom** [comment]
@vdemeester thank you!
