### ISSUE TITLE
1.9: Config.NetworkDisabled gets dropped

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#17139]
If `HostConfig.NetworkDisabled` is false the field is dropped.  This was not the case in Docker <=1.8.

**Comment by thaJeztah** [comment]
Similar to https://github.com/docker/docker/issues/17131

I'll add it to the milestone, so we don't overlook, but no promises :innocent: 

/cc @tiborvass

**Comment by runcom** [comment]
I belive we're talking about **`Config`**`.NetworkDisabeld` here right?

**Comment by ibuildthecloud** [comment]
@runcom Yes, sorry, this is for `Config.NetworkDisabled`.  I've updated the title of the issue.

**Comment by runcom** [comment]
@ibuildthecloud cool, this has the same underlying problem of #17131 tho :( (I agree with your comment also https://github.com/docker/docker/issues/17131#issuecomment-149151735)
