### ISSUE TITLE
Error creating machines

### ISSUE THREAD

**Issue by 1993hzh** [docker/docker#17137]
I was trying to install docker in OSX(a virtual machine installed in my windows10), I got some problems when create machines: 
> /Applications/Docker/Kitematic (Beta).app/Contents/Resources/resources/docker-machine -D create -d virtualbox --virtualbox-memory 2048 default returned non zero exit code. Stderr: Converting from raw image file="stdin" to file="/Users/<redacted>/.docker/machine/machines/default/disk.vmdk"... Creating dynamic image with size 20971520000 bytes (20000MB)... Error creating machine: exit status 1 You will want to check the provider to make sure the machine and associated resources were properly removed.

I tried to downgrade virtualbox to 5.0.4&5.0.2 but it doesn't work, the virtualbox version is 5.0.6.

Here is some info.

docker version:
> Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 18:01:15 UTC 2015
 OS/Arch:      darwin/amd64
Get http:///var/run/docker.sock/v1.20/version: dial unix /var/run/docker.sock: no such file or directory.

docker info:
> Get http:///var/run/docker.sock/v1.20/info: dial unix /var/run/docker.sock: no such file or directory.
(I searcher for this problem, as they said 'sudo' shouldn't be used, however, i didn't use 'sudo' command)

uname -a:
> Darwin HuLeos-Mac.local 13.1.0 Darwin Kernel Version 13.1.0: Thu Jan 16 19:40:37 PST 2014; root:xnu-2422.90.20~2/RELEASE_X86_64 x86_64

**Comment by cpuguy83** [comment]
Hello, this should go in github.com/docker/machine.

Thanks!
