### ISSUE TITLE
inconsistent api endpoints in v1.21

### ISSUE THREAD

**Issue by gesellix** [docker/docker#17132]
Looking at the new remote api endpoints for `POST /volumes` and `POST /networks/create`, which both create a new volume or a network, and then looking at the older endpoints like `POST /images/create`, I get the impression that the `POST /volumes` endpoint should be renamed to `POST /volumes/create`.

WDYT?

**Comment by vdemeester** [comment]
Hum, yeah there is a little bit of inconsistency it seems. From a *pure* REST point of view, `POST /volumes` to create a volume is quite good.

**Comment by runcom** [comment]
Yes, it should be even `POST /images` :)

**Comment by vdemeester** [comment]
@runcom and `POST /containers`. But the question(s) then is/are the other actions `inspect, stop, …` and if docker needs to be implemented in a `pure` REST way.

Anyway, having consistency — using `/…/create` or not for all creation operation — would be good :wink:

**Comment by gesellix** [comment]
I would also prefer a more RESTful way, but I wouldn't like to start a discussion about the degree of RESTfulness of the Docker api ;-)
So like @vdemeester said, I'd also prefer consistency over RESTfulness. I actually started to create a PR and can add it here asap.

**Comment by gesellix** [comment]
P.S.: discussing about a more RESTful design of the whole api could be an independent issue.
In this case, I only wanted to help making the upcoming 1.9 Docker release to be consistent with the other endpoints people are already used to.

**Comment by gesellix** [comment]
PR #17136 renames the `POST /volumes` endpoint. I've run the tests locally, but two failed. I guess that both failing tests only fail on my local setup and not due to the changes in the PR:

```
FAIL: docker_api_containers_test.go:789: DockerSuite.TestContainerApiCreateWithCpuSharesCpuset

docker_api_containers_test.go:799:
    c.Assert(status, check.Equals, http.StatusCreated)
... obtained int = 500
... expected int = 201
```

```
FAIL: docker_api_inspect_unix_test.go:14: DockerSuite.TestInspectApiCpusetInConfigPre120

docker_api_inspect_unix_test.go:19:
    dockerCmd(c, "run", "--name", name, "--cpuset", "0-1", "busybox", "true")
/go/src/github.com/docker/docker/pkg/integration/dockerCmd_utils.go:35:
    c.Assert(err, check.IsNil, check.Commentf("%q failed with errors: %s, %v", strings.Join(args, " "), out, err))
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc209d27420)} ("exit status 1")
... "run --name cpusetinconfig-pre120 --cpuset 0-1 busybox true" failed with errors: Warning: '--cpuset' is deprecated, it will be replaced by '--cpuset-cpus' soon. See usage.
Error response from daemon: Requested CPUs are not available - requested 0-1, available: 0.
, exit status 1
```
