### ISSUE TITLE
1.9: Conflicting options: -h and the network mode (--net)

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#17147]
In 1.8 the docker CLI will block combining `-h` with `--net container:x`.  This was never block from the API though.  It didn't set the hostname, but silently ignored the hostname parameter.  Now this throws an error.  I have some apps that are breaking on 1.9 now because -h was combined with --net container:x

**Comment by thaJeztah** [comment]
added to the milestone, but not sure about this one; is there a reason you're providing both flags?

**Comment by linzhaoming** [comment]
have a test

**Comment by ibuildthecloud** [comment]
@thaJeztah Not sure what the correct fix should be.  The fact that both flags are sent is basically a user error, but it doesn't blow up.  Now it does blow up.  So this is a situation where something that is working on 1.8 will not work on 1.9.  Do we accept that 1.9 is more strict and callers should update there code if wrong, or do we support the old behavior.

**Comment by runcom** [comment]
I'm +1 on erroring out in api as well, seems inconsistent otherwise. We check and return errors in api and cli for many other things (cgroups setting is an example) so I don't see why we don't have to check and error out here

**Comment by runcom** [comment]
Unless of course there was a reason not to error out which I'm not aware of

**Comment by thaJeztah** [comment]
Let's get clear why we didn't error out in the API; if there's a reason for that we can reconsider to revert the change in behavior.

**Comment by ibuildthecloud** [comment]
This seems to apply to mac-address too:

`Conflicting options: --mac-address and the network mode (--net)`

**Comment by coolljt0725** [comment]
I think we should error out both on API and CLI.  #11516 add error out on CLI, but I forget why I didn't add error out on API, maybe just I forget do that at that time.....

**Comment by runcom** [comment]
Perfect, seems the correct behavior to me tho

**Comment by tiborvass** [comment]
@ibuildthecloud I'll close this issue since I think most of us agree the behavior in 1.8 and before was erroneous, undocumented and unsupported. I would recommend you update the code.

**Comment by dnephin** [comment]
The behaviour seems correct, but isn't the error message wrong and misleading? It references cli params which don't mean anything to someone using the API directly.
