### ISSUE TITLE
Reverse order of comments on docker hub

### ISSUE THREAD

**Issue by MikeMitterer** [docker/docker#17154]
It's annoying that the most current comment is the last one in the list - can you please change that order?
In most cases it's not relevant anymore what was, say, 3 month ago.

**Comment by thaJeztah** [comment]
HI @MikeMitterer could you open this issue in the "Hub Feedback" issue tracker? Docker Hub is not handled by the open source team, so not in this repository. You can create an issue here:

https://github.com/docker/hub-feedback/issues

**Comment by vdemeester** [comment]
@thaJeztah I think the hub help page should be update though (https://hub.docker.com/help/), it's pointing to `docker/docker`.

**Comment by thaJeztah** [comment]
@vdemeester oh! that's weird. Can you create an issue for that in https://github.com/docker/hub-feedback/issues?

**Comment by vdemeester** [comment]
I can :wink:
