### ISSUE TITLE
Change Cgroups when container is runing

### ISSUE THREAD

**Issue by leejansq** [docker/docker#17164]
docker version:
    Version:      1.9.0-dev
    API version:  1.21
    Go version:   go1.5
    OS/Arch:      linux/amd64
docker info:
     Storage Driver: devicemapper
     Pool Name: docker-253:1-2491450-pool
     Execution Driver: native-0.2
     Kernel Version: 4.1.8-200.fc22.x86_64

uname -a:
     Linux localhost.localdomain 4.1.8-200.fc22.x86_64 #1 SMP Tue Sep 22 12:13:21 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

I need to change cgroups when container is running;

So,I modify the docker source code! Append new API that call the method  of libcontainer.Container and change the hostconfig of container to Avoid the Question 

But,I think this is not a good way;I hope to get the offical soluttions,or You can take my advice.

**Comment by cpuguy83** [comment]
Dup of #15078 and #3285
