### ISSUE TITLE
Misleading error on docker pull

### ISSUE THREAD

**Issue by jarischaefer** [docker/docker#17168]
Pulling an image larger than the available storage space results in a misleading error message claiming the image was not found. The process typically halts during the download phase once 100% storage space is used, followed by the image not found error message. This has bitten us at least twice at the company I work for. I have seen this with different docker versions, graph drivers, filesystems and kernels.

#### One of our machine's setup:
Ubuntu 14.04 running Linux 3.19.0-30-generic x86_64, Docker 1.8.3 using aufs on xfs 

#### Steps to Reproduce:
1. Find/create a large image (e.g. baseimages)
2. Make sure Docker's data directory resides in a filesystem with insufficient space for the image of your choosing
3. docker pull largeimage
4. An image not found error should appear before the download finishes
5. df -h should report 100% usage on the mount point where Docker's data directory resides

#### Actual Results:
- Image not found error

#### Expected Results:
- Insufficient space error
- Even better: "Insufficient storage space, cannot pull image" prior to starting the download (does not fill the filesystem 100%)

**Comment by thaJeztah** [comment]
Looks similar to https://github.com/docker/docker/issues/6484 (and the related PR https://github.com/docker/docker/pull/6503)

@LK4D4 you looked into the other issue, any idea if we can make improvements here? I think the problem is that upfront, we don't know how large the image is before pulling IIRC

**Comment by askb** [comment]
I was looking into the code (~docker/graph/pull_v2.go->download() and pullV2Tag()), but was unable to find any checks being performed for determining the disk space during a pull request. I would like to work on this issue (require some guidance), if no one is working. #dibs :)

Thanks to @cpuguy83 for giving some heads up on the issue, some highlights or approaches to resolve this:  
* the checks for every pull request maybe be a overkill on the server, but its is expected to return a more appropriate error code as returned from the syscall. This may not be limited to aufs/xfs or specific to a platform, require more investigation where the errors are propagating from.  
* refer to #16450 (could be linked) - checking before pulling the actual layers, to be able to essentially do a dry-run pull which would let the client inspect the size/etc before doing the real thing.

**Comment by askb** [comment]
@cpuguy83 Here are the steps to reproduce the issue on ubuntu 14.04 using aufs / default drivers. 

```
$ docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64
```

```
On the remote host the root partiton has about ~100MiB space file systems reserved blocks.
$ df -lh
Filesystem                   Size  Used Avail Use% Mounted on
/dev/mapper/ubuntu--vg-root   75G   75G   31M 100% /
```

Docker daemon run with `-D` gives the output (***), when a pull request of a large enough image, we get error "no space left on device" `(pkg/chrootarchive/archive_unix.go:invokeUnpack)` but the docker client does not show anything relevant. We are getting error message printed (in two parts "output: write /usr/lib/klibc/bin/mkdir: no space left on device"), one returned while uncompromising the image, which may be propagating to the caller functions (`pullV2Repository()`) which prints "Error trying v2 registry".  

```
...
....
DEBU[6740] Downloaded 549000bd581a99fc8219cecdc62e4c430cfeb3f1f21da427ea81cf15a2c69e6c to tempfile /var/lib/docker/tmp/GetImageBlob752007914 
DEBU[6740] Downloaded 0105f98ced6dc9e178b4b2aa3400759d0395c402c3718992561b11652a1eb6f6 to tempfile /var/lib/docker/tmp/GetImageBlob417784662 
DEBU[6742] Error trying v2 registry: Untar re-exec error: exit status 1: output: write /usr/lib/klibc/bin/mkdir: no space left on device ===>***
DEBU[6742] Trying to pull 192.168.1.34:5000/batman/registry from http://192.168.1.34:5000 v1 
ERRO[6745] error copying from layer download progress reader: download canceled 
DEBU[6748] [registry] Calling GET http://192.168.1.34:5000/v1/repositories/batman/registry/images 
DEBU[6749] Not continuing with error: Error: image batman/registry:latest not found
```

Error message returned by docker is need to be more meaningful ("Error: image batman/registry:latest not found") not sure if this is from `graph/pull_v1.go:pullRepository()` I may need to spend more time digging the code. 
 
```
$ docker pull 192.168.1.34:5000/batman/registry
Using default tag: latest
latest: Pulling from batman/registry
0105f98ced6d: Extracting [================>                                  ] 21.17 MB/65.79 MB
66395c31eb82: Download complete 
002fa881df8a: Download complete 
a005e6b7dd01: Download complete 
549000bd581a: Download complete 
b3eddd200064: Download complete 
2a63916f3f25: Download complete 
aa0321cc95bd: Download complete 
333caf563dfe: Download complete 
cdb323497e73: Download complete 
7fcb4e2b13fd: Download complete 
Pulling repository 192.168.1.34:5000/batman/registry
Error: image batman/registry:latest not found   ======> may need to look into this further.
```
Please let me know your thoughts on narrowing the issue further, any suggestions are welcome. Thanks.

**Comment by askb** [comment]
The main issue here is the way `ErrNoSupport` or `discardNoSupportErrors` is being handled in `graph/pull.go:Pull()`. The docker client first sends a v2 pull request which fails with "no disk space error", this error is stored in `lastErr` var, on failure the error message is not returned to the client, instead v1 pull is attempted on the docker daemon which results in an error. Therefore the var `lastErr` gets overwritten with a subsequent error returned on v1 (as the first attempt with v2 failed). Therefore overwriting and returning "error: no disk image found"  with `lastErr` causing the issue. 

To solve this issue, would it be better to return v2 error (more valuable) instead of the v1 error or is there some way to tell if the request was for v1/v2. I am not sure if we need to return both error code/messages to the docker client (concatenated as a single string). Any better ways to handling this?

**Comment by askb** [comment]
When the docker daemon is started with "--disable-legacy-registry=true", the correct error message is sent to the client. Not sure if could be recommend as possible work around till the issue gets fixed. 

```
$ docker pull 192.168.1.34:5000/askb/devbox
Using default tag: latest
latest: Pulling from askb/devbox
972087ac0357: Extracting [=====>                                             ] 20.61 MB/191.4 MB
6b248174e4db: Download complete 
........
11ee04239602: Download complete 
Untar re-exec error: exit status 1: output: write /usr/bin/python2.7: no space left on device
```

This is caused in the `puller.Pull()` function, which returns lists of endpoints (v2,v1,v0) pointing to the same registry. Therefore, when legacy registry is enabled, daemon loops into looking of requested image in the older registry version. This looping causes subsequent errors to overwrite the error returned from (`graph/pull.go:puller.Pull()` function) the first time ("no disk space left on device"), with the later error messages returned, therefore returning "image not found" to the docker client. 
Sorry, I am not very familiar with `discardErrNoSupportError` and how its handled, any suggestions fixing this would be appreciated. included @dmcgowan @thaJeztah

**Comment by thaJeztah** [comment]
ping @RichardScothern ^^

**Comment by RichardScothern** [comment]
@askb : `--disable-legacy-registry-` effectively hides the problem because it prevents the daemon from falling back to a V1 registry and producing the `NotFound` error.  However, if the daemon were configured with two v2 registries, it may produce multiple disk space errors (one for each fallback).  Ideally there should be a class of errors which cannot be retried, of which out of disk space is one.

**Comment by askb** [comment]
@RichardScothern, I agree, daemon should not proceed on "no disk space" error, while checking if the error belonged to a class and avoid retries should be implemented to address this issue. Can this be achieved with adding a case for "no disk space errors" to `registry/registry.go:ContinueOnError()`, which checks if a fall back is required on the type of error ?
