### ISSUE TITLE
Restart of container expecting a network fails with uninformative error:

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#17160]
If I restart a container that was attached to a network I removed, the container restart fails because the network no longer exists.  Shouldn't I have the option to restart the container outside of a network? How do I do that?

Also, the error returned doesn't mention the network is missing --- better error message needed.

To recreate:

1. Create a network
2. Add a container to the network
3. Stop the container
4. Remove the network
5. Restart the container

```bash
ubuntu@ip-172-31-45-85:~$ docker network inspect mary-network
{
    "name": "mary-network",
    "id": "ae59a5db981f3b860a77a05741632cf9de28f8f642361091b49b36df2bfd3f62",
    "scope": "local",
    "driver": "bridge",
    "ipam": {
        "driver": "default",
        "config": [
            {}
        ]
    },
    "containers": {
        "007fdb4085c2ff0f5ef006083d496c70380ef62bb3d46b4495b5b3080f617e3b": {
            "endpoint": "63cbfe26d49aafaa4532d6bd2f1c384780560241051b32b4ef8abceba510b963",
            "mac_address": "02:42:ac:12:00:02",
            "ipv4_address": "172.18.0.2/16",
            "ipv6_address": ""
        }
    }
}
ubuntu@ip-172-31-45-85:~$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
007fdb4085c2        busybox             "sh"                12 minutes ago      Up 10 minutes                           fervent_booth
ubuntu@ip-172-31-45-85:~$ docker stop fervent_booth
fervent_booth
ubuntu@ip-172-31-45-85:~$ docker network inspect mary-network
{
    "name": "mary-network",
    "id": "ae59a5db981f3b860a77a05741632cf9de28f8f642361091b49b36df2bfd3f62",
    "scope": "local",
    "driver": "bridge",
    "ipam": {
        "driver": "default",
        "config": [
            {}
        ]
    },
    "containers": {}
}
ubuntu@ip-172-31-45-85:~$ docker network rm mary-network
ubuntu@ip-172-31-45-85:~$ docker network inspect mary-network
Error response from daemon: network mary-network not found
ubuntu@ip-172-31-45-85:~$ docker start fervent_booth
Error response from daemon: Cannot start container fervent_booth: [8] System error: nosandbox: error locating sandbox id 007fdb4085c2ff0f5ef006083d496c70380ef62bb3d46b4495b5b3080f617e3b: %!v(MISSING)
Error: failed to start containers: [fervent_booth]
ubuntu@ip-172-31-45-85:~$ 
```

**Comment by thaJeztah** [comment]
Should it be possible at all to remove a network, if there are containers that use it? Perhaps add a `-f` / `--force` flag on `docker network rm` that detaches all containers from the network on removal

/cc @mavenugo @mrjana @tiborvass

**Comment by moxiegirl** [comment]
@thaJeztah I'd be more interested in being able to start a container but *not* automatically attach to the network.  That would be 1) a way to get around the problem I just encountered 2) allow me to isolate a suspect container in a security situation (right now a container once attached has to be disconnected or it always starts "connected" to the network)

**Comment by thaJeztah** [comment]
@moxiegirl agreed, for isolation / security audit

**Comment by mavenugo** [comment]
@moxiegirl @thaJeztah when a container is connected to the network explicitly by the user, I believe they will come to expect to have the containers automatically connected back to the network when restarted. Without that, everytime the container restart, they have to manually connect to the networks and that doesnt seem right.

We let the network to be removed when there is no Active container connected to the network. We can fail the container create with a valid message if a network that the container was connected to is missing.

**Comment by thaJeztah** [comment]
> when a container is connected to the network explicitly by the user, I believe they will come to expect to have the containers automatically connected back to the network when restarted. 

Sounds reasonable, but is there a way to override the "connecting to the network", for reasons @moxiegirl mentioned?

> We let the network to be removed when there is no Active container connected to the network.

With "active", you mean, only *running* containers? Thinking of situations where containers are *created*, but not yet started. From a UX perspective, I think it's more consistent

**Comment by thaJeztah** [comment]
for reference, this is the behavior of volumes;

```bash
$ docker volume create --name foobar
foobar
$ docker create -v foobar:/foobar hello-world
b24a48816e742d4aa1ca56dee06a7f620af57c90c9587b222787a69f6de6ed26
$ docker volume rm foobar
Error response from daemon: Conflict: volume is in use
```

**Comment by moxiegirl** [comment]
@mavenugo I agree the container should *automatically* connect to the network. I do think there are cases where someone might want to pass a flag to `docker start` to bypass this behavior.  But definitely a nice to have.
