### ISSUE TITLE
Restart policy doesn't work with docker run, but does with docker start

### ISSUE THREAD

**Issue by jonnystoten** [docker/docker#17171]
I have a container that I know will exit with a non-zero status code. If I run it with `docker run --restart always --name auth_test rocketmakers/auth:0.1.0`, it just quits, and the status is "Exited (1)".

If I then run `docker start auth_test`, the container restarts itself in a loop (what I expect).

Use the commands below to provide key information from your environment:

**docker version:**
```
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 18:01:15 UTC 2015
 OS/Arch:      linux/amd64
```
**docker info:**
```
Containers: 13
Images: 242
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 268
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.10-boot2docker
Operating System: Boot2Docker 1.8.3 (TCL 6.4); master : af8b089 - Mon Oct 12 18:56:54 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: OLWI:IP42:RC4A:YORG:RCWB:GBCH:REOP:2J6K:P5MG:FA5M:BGS5:PVYJ
Debug mode (server): true
File Descriptors: 50
Goroutines: 103
System Time: 2015-10-19T12:58:07.148374541Z
EventsListeners: 2
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```
**uname -a:**
```
Darwin jonny.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
```

**Provide additional environment details (AWS, VirtualBox, physical, etc.):**

Running VirtualBox on OS X via docker-machine.

**List the steps to reproduce the issue:**
1. `docker run --restart always --name auth_test busybox sh -c 'sleep 1; exit 1'; docker events` as per @phemmer's example

**Describe the results you received:**
No output from `docker events`, `docker ps -a` shows that the container status is "Exited (1)"

**Describe the results you expected:**
The same output as @phemmer got

**Provide additional info you think is important:**
When I run
```
$ docker create --restart always --name auth_test busybox sh -c 'sleep 1; exit 1'
$ docker start auth_test; docker events
```
I get the expected output.

----------END REPORT ---------

**Comment by phemmer** [comment]
Please provide the requested info. I am unable to reproduce.

```
# docker run --restart always --name auth_test busybox sh -c 'sleep 1; exit 1'; docker events
2015-10-19T08:25:33.000000000-04:00 9b956e78341e7c2310df0b5c4f473356269ee20408f9b5f89b61caadcbe7008d: (from busybox) die
2015-10-19T08:25:34.000000000-04:00 9b956e78341e7c2310df0b5c4f473356269ee20408f9b5f89b61caadcbe7008d: (from busybox) start
2015-10-19T08:25:35.000000000-04:00 9b956e78341e7c2310df0b5c4f473356269ee20408f9b5f89b61caadcbe7008d: (from busybox) die
2015-10-19T08:25:36.000000000-04:00 9b956e78341e7c2310df0b5c4f473356269ee20408f9b5f89b61caadcbe7008d: (from busybox) start
2015-10-19T08:25:37.000000000-04:00 9b956e78341e7c2310df0b5c4f473356269ee20408f9b5f89b61caadcbe7008d: (from busybox) die
2015-10-19T08:25:38.000000000-04:00 9b956e78341e7c2310df0b5c4f473356269ee20408f9b5f89b61caadcbe7008d: (from busybox) start
2015-10-19T08:25:39.000000000-04:00 9b956e78341e7c2310df0b5c4f473356269ee20408f9b5f89b61caadcbe7008d: (from busybox) die
```

**Comment by cpuguy83** [comment]
Also, `docker run` is literally calling the api for `docker create` and then `docker start`

**Comment by jonnystoten** [comment]
Thanks for the comments, I have updated my initial comment with the requested information

**Comment by cpuguy83** [comment]
`docker create; docker run; docker events`... this would fail on `docker run` since the container already exists from `docker create`.

**Comment by jonnystoten** [comment]
Sorry, I meant `docker start`, I will update

**Comment by cpuguy83** [comment]
I can confirm the behavior... very strange...
Note that if you use `-d` it works just fine.

**Comment by cpuguy83** [comment]
But if you start the container again after it's exited, it works...
Seems like a race between create and start API calls somehow.

**Comment by cpuguy83** [comment]
I think I see it... client is sending SIGPIPE `level=info msg="POST /v1.21/containers/8674180582c978090870d5fc53807a575f88f47ea01b260332fba524f5b30303/kill?signal=PIPE"`

**Comment by cpuguy83** [comment]
So when the container exits, SIGPIPE is being sent to the client process, which is forwarding all signals via the API, when the kill or stop API is triggered, this disables the restart policy.

**Comment by pvnovarese** [comment]
Just ran into this on 1.11 experimental, so it's still hanging around.

**Comment by cpuguy83** [comment]
#21333
