### ISSUE TITLE
Docker 1.9.0-rc1: Tagging+pushing an image originally pulled by sha256 digest causes subsequent pulls to fail

### ISSUE THREAD

**Issue by samuelkarp** [docker/docker#17178]
Description of problem: Pulling an image by its sha256 digest, tagging it to a repository, and pushing it to said repository causes subsequent pulls of the same sha256 digest to fail. 

`docker version`:
```
$ docker version
Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   504e67b
 Built:        Sat Oct 17 00:20:39 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   504e67b
 Built:        Sat Oct 17 00:20:39 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:
```
$ docker info
Containers: 1
Images: 17
Engine Version: 1.9.0-dev
Storage Driver: devicemapper
 Pool Name: docker-202:1-263819-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.111 GB
 Data Space Total: 107.4 GB
 Data Space Available: 27.79 GB
 Metadata Space Used: 2.122 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.7-15.23.amzn1.x86_64
Operating System: Amazon Linux AMI 2015.09
CPUs: 2
Total Memory: 3.862 GiB
Name: ip-172-31-2-7
ID: VTG3:R6C2:FSRU:TWTL:KEEB:MVHG:JUIB:UOSR:5PP5:SBUF:Q7DA:D32U
```

`uname -a`:
```
$ uname -a
Linux ip-172-31-2-7 4.1.7-15.23.amzn1.x86_64 #1 SMP Mon Sep 14 23:20:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.):
Amazon EC2 instance running the latest Amazon Linux AMI

How reproducible:
Always

Steps to Reproduce:
1. Pull an image by a sha256 tag (e.g. `docker pull busybox@sha256:ced99ae82473e7dea723e6c467f409ed8f051bda04760e07fd5f476638c33507`)
2. Tag it as an image in a different registry (e.g. `docker tag -f busybox@sha256:ced99ae82473e7dea723e6c467f409ed8f051bda04760e07fd5f476638c33507 "127.0.0.1:51670/busybox:latest"`)
3. Push the newly-tagged image (e.g. `docker push "127.0.0.1:51670/busybox:latest"`)
4. Attempt to pull the original image again (e.g. `docker pull busybox@sha256:ced99ae82473e7dea723e6c467f409ed8f051bda04760e07fd5f476638c33507`)

See [reproduction script](https://gist.github.com/samuelkarp/4cdb98e0010a23bd606e).

Actual Results:
`Conflict: Digest sha256:ced99ae82473e7dea723e6c467f409ed8f051bda04760e07fd5f476638c33507 is already set to image 4db036b4be06ff5e1c938060a39ea6023a6049510672f1a53522905d2927f987 `

Expected Results:
```
sha256:ced99ae82473e7dea723e6c467f409ed8f051bda04760e07fd5f476638c33507: Pulling from busybox
cf2616975b4a: Already exists 
6ce2e90b0bc7: Already exists 
8c2e06607696: Already exists 
Digest: sha256:ced99ae82473e7dea723e6c467f409ed8f051bda04760e07fd5f476638c33507
Status: Image is up to date for busybox@sha256:ced99ae82473e7dea723e6c467f409ed8f051bda04760e07fd5f476638c33507
```

Additional info:

Running the reproduction script with `git bisect` finds 504e67b867865a2835e8002c01087a2cfd7bfd0e as the commit responsible.

**Comment by thaJeztah** [comment]
Thanks for reporting!

ping @tonistiigi PTAL
