### ISSUE TITLE
1.9: VolumeDriver field

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#17172]
VolumeDriver has moved from Config to HostConfig in 1.21 but API versions <=1.20 should still report VolumeDriver as being in Config.  This not the case.

**Comment by runcom** [comment]
On latest master I see it

v1.19
```
curl -s http://localhost:2375/v1.19/containers/252/json | jq ".Config"      
{
  "Cpuset": "",
  "CpuShares": 0,
  "MemorySwap": 0,
  "Memory": 0,

  "VolumeDriver": "",

  "StopSignal": "SIGTERM",
  "Labels": {},
  "OnBuild": null,
  "OpenStdin": false,
  "Tty": false,
  "AttachStderr": false,
  "AttachStdout": false,
  "AttachStdin": false,
  "User": "",
  "Domainname": "",
  "Hostname": "252506b5aaeb",
  "StdinOnce": false,
  "Env": null,
  "Cmd": [
    "top"
  ],
  "Image": "busybox",
  "Volumes": null,
  "WorkingDir": "",
  "Entrypoint": null,
  "MacAddress": "52:54:00:a7:09:de"
}
```
v1.20
```
curl -s http://localhost:2375/v1.20/containers/252/json | jq ".Config"    
{

  "VolumeDriver": "",

  "StopSignal": "SIGTERM",
  "Labels": {},
  "OnBuild": null,
  "OpenStdin": false,
  "Tty": false,
  "AttachStderr": false,
  "AttachStdout": false,
  "AttachStdin": false,
  "User": "",
  "Domainname": "",
  "Hostname": "252506b5aaeb",
  "StdinOnce": false,
  "Env": null,
  "Cmd": [
    "top"
  ],
  "Image": "busybox",
  "Volumes": null,
  "WorkingDir": "",
  "Entrypoint": null,
  "MacAddress": "52:54:00:a7:09:de"
}
```

**Comment by ibuildthecloud** [comment]
@runcom let me look at this.  maybe I messed up

**Comment by calavera** [comment]
It should be in the right place:

https://github.com/docker/docker/blob/master/api/types/versions/v1p19/types.go#L23

```
➜  curl -s http://localhost:2375/v1.19/containers/test/json |  jq ".Config" | grep VolumeDriver
  "VolumeDriver": "",
➜  curl -s http://localhost:2375/v1.20/containers/test/json |  jq ".Config" | grep VolumeDriver
  "VolumeDriver": "",
➜  curl -s http://localhost:2375/v1.21/containers/test/json |  jq ".Config" | grep VolumeDriver
➜  
```

The field is in `Config` for api versions 1.19 and 1.20, but it's not there anymore for 1.21.

**Comment by runcom** [comment]
yup

**Comment by runcom** [comment]
can we close it then?

**Comment by calavera** [comment]
@ibuildthecloud feel free to reopen it if you find something inconsistent here. I'm going to close it for now to clean the pending tasks in the milestone.

**Comment by ibuildthecloud** [comment]
@calavera @runcom hmmm.... I can't reopen.  I found what confused me, on <=1.20 VolumeDriver is in both Config and HostConfig.  This isn't too bad, so maybe you can just ignore it.  But in 1.21 the VolumeDriver is just in HostConfig

**Comment by runcom** [comment]
@ibuildthecloud that's the place it should be in 1.21

**Comment by ibuildthecloud** [comment]
@runcom Sorry, maybe I wasn't clear.  The VolumeDriver field is in both Config and HostConfig in <=1.20.  In Docker 1.8 for <=1.20 it was just in the Config section.  So there is a new field.  This doesn't really cause any problems, but you can decide if you don't want it additionally in the HostConfig for <= 1.20.
