### ISSUE TITLE
1.9-RC: Inconsistent UX between `docker network` and `docker volume`

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#17194]
The UX of `docker volume create` and `docker network create` is inconsistent;

```bash
# creates a volume named "foobar"
docker volume create --name foobar

# creates a network named "foobar"
docker network create foobar
```

**Comment by mavenugo** [comment]
@thaJeztah name is not an optional parameter for network.

**Comment by thaJeztah** [comment]
hm, yes I just realized that may be the reason for the difference

**Comment by thaJeztah** [comment]
I just tripped over it, trying to create a network and a volume fast :smile:
