### ISSUE TITLE
(debian jessie) dpkg: error  processing package docker-engine

### ISSUE THREAD

**Issue by AJNOURI** [docker/docker#17197]
---- ISSUE DESCRIPTION

LiveCD on physical box

$ uname -a
>Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux

user@debian:~$ lsb_release -a
>No LSB modules are available.
>Distributor ID:	Debian
>Description:	Debian GNU/Linux 8.2 (jessie)
>Release:	8.2
>Codename:	jessie

sudo docker info
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
user@debian:~$ 
user@debian:~$ docker -d
Warning: '-d' is deprecated, it will be removed soon. See usage.
WARN[0000] please use 'docker daemon' instead.          
FATA[0000] Error starting daemon: open /var/run/docker.pid: permission denied 
user@debian:~$ 

sudo docker version

> Client:  Version:      1.8.3  API version:  1.20  Go version:  
> go1.4.2  Git commit:   f4bf5c7  Built:        Mon Oct 12 05:27:08 UTC
> 2015  OS/Arch:      linux/amd64 Cannot connect to the Docker daemon.
> Is 'docker -d' running on this host?

----

List the steps to reproduce the issue:

1- sudo apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 
 58118E89F3A912897C070ADBF76221572C52609D   
2- sudo apt-get update 
3- apt-cache policy docker-engine  
> docker-engine:   Installed:
> 1.8.3-0~jessie   Candidate: 1.8.3-0~jessie   Version table:  *** 1.8.3-0~jessie 0
>         500 https://apt.dockerproject.org/repo/ debian-jessie/main amd64 Packages
>         100 /var/lib/dpkg/status
>      1.8.2-0~jessie 0
>         500 https://apt.dockerproject.org/repo/ debian-jessie/main amd64 Packages
>      1.8.1-0~jessie 0
>         500 https://apt.dockerproject.org/repo/ debian-jessie/main amd64 Packages
>      1.8.0-0~jessie 0
>         500 https://apt.dockerproject.org/repo/ debian-jessie/main amd64 Packages
>      1.7.1-0~jessie 0
>         500 https://apt.dockerproject.org/repo/ debian-jessie/main amd64 Packages
>      1.7.0-0~jessie 0
>         500 https://apt.dockerproject.org/repo/ debian-jessie/main amd64 Packages

4- sudo apt-get install docker.engine

> Reading package lists... Done Building dependency tree        Reading
> state information... Done Note, selecting 'docker-engine' for regex
> 'docker.engine' The following NEW packages will be installed:  
> docker-engine 0 upgraded, 1 newly installed, 0 to remove and 13 not
> upgraded. Need to get 0 B/5,630 kB of archives. After this operation,
> 28.4 MB of additional disk space will be used. Selecting previously unselected package docker-engine. (Reading database ... 102791 files
> and directories currently installed.) Preparing to unpack
> .../docker-engine_1.8.3-0~jessie_amd64.deb ... Unpacking docker-engine
> (1.8.3-0~jessie) ... Processing triggers for man-db (2.7.0.2-5) ...
> Processing triggers for systemd (215-17+deb8u2) ... Setting up
> docker-engine (1.8.3-0~jessie) ... Job for docker.service failed. See
> 'systemctl status docker.service' and 'journalctl -xn' for details.
> invoke-rc.d: initscript docker, action "start" failed. dpkg: error
> processing package docker-engine (--configure):  subprocess installed
> post-installation script returned error exit status 1 Processing
> triggers for systemd (215-17+deb8u2) ... Errors were encountered while
> processing:  docker-engine E: Sub-process /usr/bin/dpkg returned an error code (1)

----

user@debian:~$ systemctl status docker.service

> ● docker.service - Docker Application Container Engine    Loaded:
> loaded (/lib/systemd/system/docker.service; enabled)    Active: failed
> (Result: exit-code) since Tue 2015-10-20 04:10:41 UTC; 2min 57s ago
>      Docs: https://docs.docker.com   Process: 21462 ExecStart=/usr/bin/docker daemon -H fd:// (code=exited,
> status=1/FAILURE)  Main PID: 21462 (code=exited, status=1/FAILURE)

----

user@debian:~$ sudo journalctl -xn

>  Logs begin at Tue 2015-10-20 03:43:43 UTC, end at Tue 2015-10-20
> 04:26:17 UTC. -- Oct 20 04:24:41 debian systemd[1]: Listening on
> Docker Socket for the API.
> -- Subject: Unit docker.socket has finished start-up
> -- Defined-By: systemd
> -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel  
> -- Unit docker.socket has finished starting up.  
> -- The start-up result is done. Oct 20 04:24:41 debian systemd[1]: Starting Docker Application Container Engine...
> -- Subject: Unit docker.service has begun with start-up
> -- Defined-By: systemd
> -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel  
> -- Unit docker.service has begun starting up. Oct 20 04:24:41 debian docker[22736]: time="2015-10-20T04:24:41.148865646Z" level=error
> msg="[graphdriver Oct 20 04:24:41 debian docker[22736]:
> time="2015-10-20T04:24:41.149344258Z" level=fatal msg="Error starti
> Oct 20 04:24:41 debian systemd[1]: docker.service: main process
> exited, code=exited, status=1/FAILURE Oct 20 04:24:41 debian
> systemd[1]: Failed to start Docker Application Container Engine.
> -- Subject: Unit docker.service has failed  Defined-By: systemd  Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel  
> -- Unit docker.service has failed.  
> -- The result is failed. Oct 20 04:24:41 debian systemd[1]: Unit docker.service entered failed state. Oct 20 04:24:41 debian
> sudo[22710]: pam_unix(sudo:session): session closed for user root Oct
> 20 04:26:17 debian sudo[22755]: user : TTY=pts/0 ; PWD=/home/user ;
> USER=root ; COMMAND=/bin/journalc Oct 20 04:26:17 debian sudo[22755]:
> pam_unix(sudo:session): session opened for user root by user(uid=0)

**Comment by AJNOURI** [comment]
Similar issue for Ubuntu #17061

**Comment by omidraha** [comment]
I have the same problem on my `Debian Stretch` OS that is installed,
I follow  installation from [Docker documentation for install docker on debian](https://docs.docker.com/engine/installation/debian/)

    $ docker --version
    Docker version 1.9.1, build a34a1d5

    $ docker info
    Cannot connect to the Docker daemon. Is the docker daemon running on this host?

    # uname -a
    Linux debian 4.0.0-2-amd64 #1 SMP Debian 4.0.8-2 (2015-07-22) x86_64 GNU/Linu

```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux testing (stretch)
Release:	testing
Codename:	stretch
```

```
# apt-cache policy docker-engine 
docker-engine:
  Installed: 1.9.1-0~stretch
  Candidate: 1.9.1-0~stretch
  Version table:
 *** 1.9.1-0~stretch 500
        500 https://apt.dockerproject.org/repo debian-stretch/main amd64 Packages
        100 /var/lib/dpkg/status
     1.9.0-0~stretch 500
        500 https://apt.dockerproject.org/repo debian-stretch/main amd64 Packages
     1.8.3-0~stretch 500
        500 https://apt.dockerproject.org/repo debian-stretch/main amd64 Packages
     1.8.2-0~stretch 500
        500 https://apt.dockerproject.org/repo debian-stretch/main amd64 Packages
     1.8.1-0~stretch 500
        500 https://apt.dockerproject.org/repo debian-stretch/main amd64 Packages
     1.8.0-0~stretch 500
        500 https://apt.dockerproject.org/repo debian-stretch/main amd64 Packages
     1.7.1-0~stretch 500
        500 https://apt.dockerproject.org/repo debian-stretch/main amd64 Packages
     1.7.0-0~stretch 500
        500 https://apt.dockerproject.org/repo debian-stretch/main amd64 Packages
     1.6.2-0~stretch 500
        500 https://apt.dockerproject.org/repo debian-stretch/main amd64 Packages
     1.6.1-0~stretch 500
        500 https://apt.dockerproject.org/repo debian-stretch/main amd64 Packages
     1.6.0-0~stretch 500
        500 https://apt.dockerproject.org/repo debian-stretch/main amd64 Packages
     1.5.0-0~stretch 500
        500 https://apt.dockerproject.org/repo debian-stretch/main amd64 Packages
```

```
# apt-get install docker-engine
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  docker-engine
0 upgraded, 1 newly installed, 0 to remove and 439 not upgraded.
Need to get 0 B/7,500 kB of archives.
After this operation, 37.9 MB of additional disk space will be used.
Selecting previously unselected package docker-engine.
(Reading database ... 286713 files and directories currently installed.)
Preparing to unpack .../docker-engine_1.9.1-0~stretch_amd64.deb ...
Unpacking docker-engine (1.9.1-0~stretch) ...
Processing triggers for systemd (228-2) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up docker-engine (1.9.1-0~stretch) ...
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
dpkg: error processing package docker-engine (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for systemd (228-2) ...
Errors were encountered while processing:
 docker-engine
```

```
# systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2015-12-31 21:34:16 IRST; 6min ago
     Docs: https://docs.docker.com
 Main PID: 13605 (code=exited, status=1/FAILURE)

Dec 31 21:34:16 debian systemd[1]: Starting Docker Application Container Engine...
Dec 31 21:34:16 debian docker[13605]: time="2015-12-31T21:34:16.888917357+03:30" level=info msg="API listen on /var/run/docker.sock"
Dec 31 21:34:16 debian docker[13605]: time="2015-12-31T21:34:16.889304190+03:30" level=error msg="[graphdriver] prior storage driver \"aufs\" failed: driver not supported"
Dec 31 21:34:16 debian docker[13605]: time="2015-12-31T21:34:16.889324433+03:30" level=fatal msg="Error starting daemon: error initializing graphdriver: driver not supported"
Dec 31 21:34:16 debian systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Dec 31 21:34:16 debian systemd[1]: Failed to start Docker Application Container Engine.
Dec 31 21:34:16 debian systemd[1]: docker.service: Unit entered failed state.
Dec 31 21:34:16 debian systemd[1]: docker.service: Failed with result 'exit-code'.
```

use  ``docker daemon -D -s vfs `` seems to work:

```
# docker daemon -D -s vfs
DEBU[0000] docker group found. gid: 124                 
DEBU[0000] Server created for HTTP on unix (/var/run/docker.sock) 
DEBU[0000] [graphdriver] trying provided driver "vfs"   
DEBU[0000] Using graph driver vfs                       
DEBU[0000] Using default logging driver json-file       
DEBU[0000] Creating images graph                        
DEBU[0000] Restored 0 elements                          
INFO[0000] API listen on /var/run/docker.sock           
DEBU[0000] Creating repository list                     
DEBU[0000] Option DefaultDriver: bridge                 
DEBU[0000] Option DefaultNetwork: bridge                
INFO[0000] Firewalld running: false                     
DEBU[0000] /sbin/iptables, [--wait -t nat -D PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t nat -D PREROUTING] 
DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT]    
DEBU[0000] /sbin/iptables, [--wait -t nat -F DOCKER]    
DEBU[0000] /sbin/iptables, [--wait -t nat -X DOCKER]    
DEBU[0000] /sbin/iptables, [--wait -t nat -n -L DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t nat -N DOCKER]    
DEBU[0000] /sbin/iptables, [--wait -t filter -n -L DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t filter -N DOCKER] 
DEBU[0000] Registering ipam provider: default           
INFO[0000] Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address 
DEBU[0000] Allocating IPv4 pools for network bridge (ded71c0a7fa45c4ea4bd2f0252b57a154dfa727cfa32faf5742a7453ac90726b) 
DEBU[0000] RequestPool(LocalDefault, 172.17.0.0/16, , map[], false) 
DEBU[0000] RequestAddress(LocalDefault/172.17.0.0/16, <nil>, map[]) 
DEBU[0000] Setting bridge mac address to 02:42:89:b8:72:8e 
DEBU[0000] Assigning address to bridge interface docker0: 172.17.0.1/16 
DEBU[0000] /sbin/iptables, [--wait -t nat -C POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE] 
DEBU[0000] /sbin/iptables, [--wait -t nat -I POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE] 
DEBU[0000] /sbin/iptables, [--wait -D FORWARD -i docker0 -o docker0 -j DROP] 
DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -i docker0 -o docker0 -j ACCEPT] 
DEBU[0000] /sbin/iptables, [--wait -I FORWARD -i docker0 -o docker0 -j ACCEPT] 
DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -i docker0 ! -o docker0 -j ACCEPT] 
DEBU[0000] /sbin/iptables, [--wait -I FORWARD -i docker0 ! -o docker0 -j ACCEPT] 
DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT] 
DEBU[0000] /sbin/iptables, [--wait -I FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT] 
DEBU[0000] /sbin/iptables, [--wait -t nat -C PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8] 
DEBU[0000] /sbin/iptables, [--wait -t nat -A OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8] 
DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -j DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -I FORWARD -o docker0 -j DOCKER] 
WARN[0000] Your kernel does not support cgroup memory limit: mountpoint for memory not found 
WARN[0000] Your kernel does not support cgroup cfs period 
WARN[0000] Your kernel does not support cgroup cfs quotas 
DEBU[0000] Cleaning up old shm/mqueue mounts: start.    
DEBU[0000] Cleaning up old shm/mqueue mounts: done.     
DEBU[0000] Cannot load container 00162c30ac6827abff3236eeb58fb6ed2d29954ab644da21bcb65501cd77c402 because it was created with another graph driver. 
DEBU[0000] Cannot load container f118c804b7fc3cc6cdac645a7270a3ad63c88e202cdebb61320b39bf33ab4e65 because it was created with another graph driver. 
INFO[0000] Daemon has completed initialization          
INFO[0000] Docker daemon                                 commit=a34a1d5 execdriver=native-0.2 graphdriver=vfs version=1.9.1
DEBU[0000] Registering routers                          
DEBU[0000] Registering HEAD, /containers/{name:.*}/archive 
DEBU[0000] Registering OPTIONS, /                       
DEBU[0000] Registering GET, /_ping                      
DEBU[0000] Registering GET, /events                     
DEBU[0000] Registering GET, /info                       
DEBU[0000] Registering GET, /version                    
DEBU[0000] Registering GET, /images/json                
DEBU[0000] Registering GET, /images/search              
DEBU[0000] Registering GET, /images/get                 
DEBU[0000] Registering GET, /images/{name:.*}/get       
DEBU[0000] Registering GET, /images/{name:.*}/history   
DEBU[0000] Registering GET, /images/{name:.*}/json      
DEBU[0000] Registering GET, /containers/json            
DEBU[0000] Registering GET, /containers/{name:.*}/export 
DEBU[0000] Registering GET, /containers/{name:.*}/changes 
DEBU[0000] Registering GET, /containers/{name:.*}/json  
DEBU[0000] Registering GET, /containers/{name:.*}/top   
DEBU[0000] Registering GET, /containers/{name:.*}/logs  
DEBU[0000] Registering GET, /containers/{name:.*}/stats 
DEBU[0000] Registering GET, /containers/{name:.*}/attach/ws 
DEBU[0000] Registering GET, /exec/{id:.*}/json          
DEBU[0000] Registering GET, /containers/{name:.*}/archive 
DEBU[0000] Registering GET, /volumes                    
DEBU[0000] Registering GET, /volumes/{name:.*}          
DEBU[0000] Registering POST, /auth                      
DEBU[0000] Registering POST, /commit                    
DEBU[0000] Registering POST, /build                     
DEBU[0000] Registering POST, /images/create             
DEBU[0000] Registering POST, /images/load               
DEBU[0000] Registering POST, /images/{name:.*}/push     
DEBU[0000] Registering POST, /images/{name:.*}/tag      
DEBU[0000] Registering POST, /containers/create         
DEBU[0000] Registering POST, /containers/{name:.*}/kill 
DEBU[0000] Registering POST, /containers/{name:.*}/pause 
DEBU[0000] Registering POST, /containers/{name:.*}/unpause 
DEBU[0000] Registering POST, /containers/{name:.*}/restart 
DEBU[0000] Registering POST, /containers/{name:.*}/start 
DEBU[0000] Registering POST, /containers/{name:.*}/stop 
DEBU[0000] Registering POST, /containers/{name:.*}/wait 
DEBU[0000] Registering POST, /containers/{name:.*}/resize 
DEBU[0000] Registering POST, /containers/{name:.*}/attach 
DEBU[0000] Registering POST, /containers/{name:.*}/copy 
DEBU[0000] Registering POST, /containers/{name:.*}/exec 
DEBU[0000] Registering POST, /exec/{name:.*}/start      
DEBU[0000] Registering POST, /exec/{name:.*}/resize     
DEBU[0000] Registering POST, /containers/{name:.*}/rename 
DEBU[0000] Registering POST, /volumes/create            
DEBU[0000] Registering PUT, /containers/{name:.*}/archive 
DEBU[0000] Registering DELETE, /containers/{name:.*}    
DEBU[0000] Registering DELETE, /images/{name:.*}        
DEBU[0000] Registering DELETE, /volumes/{name:.*}       
DEBU[0000] Registering GET, /networks                   
DEBU[0000] Registering GET, /networks/{id:.*}           
DEBU[0000] Registering POST, /networks/create           
DEBU[0000] Registering POST, /networks/{id:.*}/connect  
DEBU[0000] Registering POST, /networks/{id:.*}/disconnect 
DEBU[0000] Registering DELETE, /networks/{id:.*}        


DEBU[0056] Calling GET /v1.21/containers/json           
INFO[0056] GET /v1.21/containers/json                   
DEBU[0058] Calling GET /v1.21/containers/json           
INFO[0058] GET /v1.21/containers/json?all=1  
```

**Comment by thaJeztah** [comment]
aufs is not supported on Debian stretch, so this may be expected. Did you upgrade this machine from an older version of Debian, or previously used aufs?

I'd really not recommend using `vfs` as a driver; it's only there as a last resort, and not useful for anything other then testing. If possible, consider overlay, or btrfs

**Comment by omidraha** [comment]
No, my `` Debian stretch`` is not upgraded from older version, it's installed originally from `` Debian stretch netinst`` CD image.

But i have ``aufs`` old directory on this machine, 
And I removed ``/var/lib/docker/aufs`` directory, 
And reinstalling ``docker-engine`` installation now works without any errors.

```
# docker info
Containers: 0
Images: 0
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.0-2-amd64
Operating System: Debian GNU/Linux stretch/sid (containerized)
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support

```

**Comment by thaJeztah** [comment]
@omidraha yup, that's expected; if docker finds a 'aufs' directory, it will try to use that storage driver, so that you can use your existing images and containers.

**Comment by HeadlessChild** [comment]
This is the same behavior if you install a kernel on Debian Jessie (stable) from jessie-backports as that kernel exceeds version 3.18 which aufs was removed from. https://lists.debian.org/debian-kernel/2014/12/msg00136.html

The solution is to remove the `/var/lib/docker/aufs` directory or start Docker with overlayfs instead, this can be done with the following flag `-s overlay`.
