### ISSUE TITLE
x509: certificate is valid for ASA Temporary Self Signed Certificate, not index.docker.io"

### ISSUE THREAD

**Issue by Pensu** [docker/docker#17208]
Hi all,

So, my docker pull was working fine till morning and suddenly I hit this error in the afternoon. When I try to do docker search, I am getting this error:

```
[root@localhost ~]# docker search ubuntu
time="2015-10-20T05:57:48-05:00" level=fatal msg="Error response from daemon: Get https://index.docker.io/v1/search?q=ubuntu: x509: certificate is valid for ASA Temporary Self Signed Certificate, not index.docker.io" 
```

I tried finding solution, and it seems it's some networking issue. I am able to connect to internet, I can ping google.com etc., but can't ping index.docker.io. Can you please help me figure out the exact issue? TIA.

**Comment by phemmer** [comment]
This sounds like you're on a corporate network with a web content firewall that's doing MITM.


P.S., these types of problems are best for the docker mailing list, forums, or irc. The issue tracker is generally for bugs and feature requests.

**Comment by thaJeztah** [comment]
That's what I suspect as well. This is no bug in docker, so not something we can fix.

Thanks for reporting though!
