### ISSUE TITLE
Docker 1.9.0-rc1: compression when pushing to V2 registry

### ISSUE THREAD

**Issue by vehovmar** [docker/docker#17209]
Push performance is significantly better in 1.9 compared to 1.8  thanks to #15493. What someone could consider to be a regression is that images pushed to V2 are not compressed, or compression level was changed significantly. 

Pushing large image layer (exactly the same image layer in both cases) to V2 docker registry (registry 2.1.1):

Daemon 1.8.1 => **2.7GB**
Daemon 1.9.0-rc1 => **4.5GB**

`docker version`:

    version
    Client:
     Version:      1.9.0-rc1
     API version:  1.21
     Go version:   go1.4.2
     Git commit:   9291a0e
     Built:        Wed Oct 14 03:04:22 UTC 2015
     OS/Arch:      linux/amd64
    
    Server:
     Version:      1.9.0-rc1
     API version:  1.21
     Go version:   go1.4.2
     Git commit:   9291a0e
     Built:        Wed Oct 14 03:04:22 UTC 2015
     OS/Arch:      linux/amd64
	 
`docker info`:

    Containers: 2
    Images: 389
    Engine Version: 1.9.0-rc1
    Storage Driver: aufs
     Root Dir: /data/docker/aufs
     Backing Filesystem: extfs
     Dirs: 393
     Dirperm1 Supported: false
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 3.13.0-65-generic
    Operating System: Ubuntu 14.04.3 LTS
    CPUs: 4
    Total Memory: 15.56 GiB
    Name: ICM-YELLOW
    ID: VZ4T:7XFC:LTCS:G5KQ:JZTF:CMIN:7QGW:OAPI:ELCR:CDTU:F6MT:R3DZ
    WARNING: No swap limit support

`uname -a`:

    Linux xyz 3.13.0-65-generic #106-Ubuntu SMP Fri Oct 2 22:08:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cpuguy83** [comment]
ping @stevvooe @aaronlehmann

**Comment by aaronlehmann** [comment]
Is this the size indicated by the "docker push" command, or registered on the registry side?

The progress indications in "docker push" are measured based on the uncompressed size, since we don't know the compressed size in advance. This is a known caveat with https://github.com/docker/docker/pull/15493 (see https://github.com/docker/docker/pull/15493/files#diff-592041b611364e78f016f9bce43e90a7R229).

**Comment by vehovmar** [comment]
It's the actual size of the same image when the image is pulled from the registry by client.

On production we use 1.8.1 so I pulled this image it's size about 2.7GB, then I re-tagged this image pushed to different V2 registry using 1.9.0-rc1 daemon. Then I downloaded the image from another client and the size when pulling was about 4.5GB.

**Comment by aaronlehmann** [comment]
I was able to reproduce this. It turns out that there was a regression which means the layers are not getting compressed at all. I've opened PR #17227 to fix this.
