### ISSUE TITLE
Flaky test: DockerHubPullSuite.TestPullFromCentralRegistryImplicitRefParts

### ISSUE THREAD

**Issue by tiborvass** [docker/docker#17214]
Encountered on #17177

```
----------------------------------------------------------------------
FAIL: docker_cli_pull_test.go:69: DockerHubPullSuite.TestPullFromCentralRegistryImplicitRefParts

docker_cli_pull_test.go:83:
    c.Assert(out, checker.Contains, "Image is up to date for hello-world:latest")
... obtained string = "" +
...     "Pulling repository docker.io/library/hello-world\n" +
...     "975b84d108f1: Pulling image (latest) from docker.io/library/hello-world\n" +
...     "975b84d108f1: Pulling image (latest) from docker.io/library/hello-world, endpoint: https://registry-1.docker.io/v1/\n" +
...     "975b84d108f1: Pulling dependent layers\n" +
...     "3f12c794407e: Pulling metadata\n" +
...     "3f12c794407e: Pulling fs layer\n" +
...     "3f12c794407e: Download complete\n" +
...     "975b84d108f1: Pulling metadata\n" +
...     "975b84d108f1: Pulling fs layer\n" +
...     "975b84d108f1: Download complete\n" +
...     "975b84d108f1: Download complete\n" +
...     "Status: Downloaded newer image for hello-world:latest\n" +
...     "docker.io/library/hello-world: this image was pulled from a legacy registry.  Important: This registry version will not be supported in future versions of docker.\n"
... substring string = "Image is up to date for hello-world:latest"


----------------------------------------------------------------------
```

**Comment by aaronlehmann** [comment]
This is a network or hub glitch and the test is falling back the v1 protocol. Hard to do much about this as long as the tests are going to pull images from hub. I think it's better in general to avoid using outside services in the tests.

**Comment by thaJeztah** [comment]
Had this one twice today already :disappointed: 

https://jenkins.dockerproject.org/job/Docker-PRs/23196/console (janky)
https://jenkins.dockerproject.org/job/Docker-PRs-gccgo/1365/console (gccgo)

**Comment by thaJeztah** [comment]
@aaronlehmann what do you suggest to test this functionality, without relying on Docker Hub? I'm not sure we're able to mock this, given that it's also testing for `library/...` etc. https://github.com/docker/docker/blob/e8ce350669b0b8096ef2bb365ecad6fbfa966bfb/integration-cli/docker_cli_pull_test.go#L75-L97

Do you have a suggestion how we can make this more reliable?

**Comment by aaronlehmann** [comment]
I think this is already covered well by the unit test `TestParseRepositoryInfo`, so I would recommend removing `TestPullFromCentralRegistryImplicitRefParts`.

**Comment by thaJeztah** [comment]
Reopening because we saw this again on https://github.com/docker/docker/pull/20832#issuecomment-190934567 and https://github.com/docker/docker/pull/20831

**Comment by thaJeztah** [comment]
Haven't seen this failing in a while, I'll close this
