### ISSUE TITLE
Proposal: add new parameter to docker run: ---add-hosts=<a big host file>

### ISSUE THREAD

**Issue by DanielYWoo** [docker/docker#17210]
I have a small cluster with only 20 servers, I don't have redundant DNS servers so I use puppet/saltstack to update /etc/hosts on each server. The problem is that unless I run all my applications with net=host, my applications cannot talk to my backend servers with hostname because the /etc/hosts has only a few lines for bridging only. I know there is already a parameter --add-hosts=[] to do this, but it's very lengthy to expand my hosts file into so many parameters. Can we add a new parameter like --add-hosts=<host file> so that I can avoid such a lengthy command line?

**Comment by cpuguy83** [comment]
@DanielYWoo You can mount your hosts file to `/etc/hosts`.
`docker run -v /path/to/custom_hosts:/etc/hosts`

**Comment by DanielYWoo** [comment]
Hi cpuguy83, /etc/hosts is generated at runtime when the container starts, it is dynamic, so I think I can only append entries to the generated one, not replacing the whole file by mounting.

**Comment by cpuguy83** [comment]
You can replace the whole thing just as I showed above
