### ISSUE TITLE
docker container unreachable through a physical network interface which is not the default gateway

### ISSUE THREAD

**Issue by haozhenxiao** [docker/docker#17212]
There are two physical network interfaces on my machine, **eno1** and **eno2**, they are in different subnets, the ip address of **eno1** is **10.10.24.157/24**, this interface is the default gateway, the default gateway is **10.10.24.1**. The ip address of **eno2** is **10.10.26.160/25**. I added a new **ip rule** for **eno2**, so that traffic going through **eno2** uses gateway **10.10.26.129** instead of the default gateway, the output of **ip rule show** is like this:
```
0:	from all lookup local 
32765:	from 10.10.26.160 lookup ifout 
32766:	from all lookup main 
32767:	from all lookup default
```
where **ifout** is the routing table for **eno2**, currently, I'm able to ping **10.10.26.160** from another subnet, and I'm also able to ping a host under another subnet through **eno2**, so I assume my configuration of **eno2** is correct.

On my machine, I have a docker container which is a webserver, my the **PORTS** of my container looks like this:

```        
0.0.0.0:8089->8089/tcp, 0.0.0.0:8080->80/tcp, 0.0.0.0:1235->10666/tcp, 0.0.0.0:2235->10678/tcp
```

I can access this web server successfully with the url **10.10.24.157:8080**, but I'm not able to access it with the url **10.10.26.160:8080**, and I tried to scan **10.10.26.160** with **nmap**, the result is realy strange:

```
PORT     STATE    SERVICE
22/tcp   open     ssh
80/tcp   filtered http
4001/tcp open     newoak
8080/tcp filtered http-proxy
8089/tcp filtered unknown
``` 

As you can see, all the ports of the docker container are filtered. How could I solve this? Do I need to do some configuration of **docker0**?

**Comment by phemmer** [comment]
Your rule is `from 10.10.26.160 lookup ifout`. Traffic from docker containers isn't coming from `10.10.26.160`, it's coming from the IP address of the container (somewhere in the `172.17.0.0/16` subnet by default).
The problem you are having is a typical multipath routing issue when you're accepting traffic on 2 different subnet addresses.

From a high level, what you need to do is set a firewall mark on the incoming connection, marking the connection with an ID specific to the interface the traffic came in on, and save it using connmark. Then on outbound traffic, restore the mark (during prerouting), and set up a routing rule to route based on the mark.

But this isn't really a docker issue though.

**Comment by haozhenxiao** [comment]
It seems that the high level setting of **10.10.26.160** has no problems, as I said before, I'm able to ping **10.10.26.160** from another subnet, and I'm also able to ping a host under another subnet through **eno2**, I also tried to transfer a file using **scp** to and from **10.10.26.160**, it worked fine. The problem here is with the docker ports, to make it more clear:

```nmap 10.10.26.160```:

```
PORT     STATE    SERVICE
22/tcp   open     ssh
80/tcp   filtered http
4001/tcp open     newoak
8080/tcp filtered http-proxy
8089/tcp filtered unknown
```

```nmap 10.10.24.157```:

```
PORT     STATE SERVICE
22/tcp   open  ssh
80/tcp   open  http
4001/tcp open  newoak
8080/tcp open  http-proxy
8089/tcp open  unknown
```

Ports ```80, 8080 and 8089``` are all bound to some ports in docker containers, the only difference between **eno1(10.10.26.160)** and **eno2(10.10.24.157)** is that **eno1** is the default gateway, while **eno2** uses **ip rule**. What's the relevance between the docker containers and host's default gateway? Form what I understand, the containers doesn't use any gateways. Then why the host ports which are bound to docker containers not accessible?

**Comment by phemmer** [comment]
> I'm able to ping 10.10.26.160 from another subnet, and I'm also able to ping a host under another subnet through eno2, I also tried to transfer a file using scp to and from 10.10.26.160, it worked fine. The problem here is with the docker ports

I'm sorry, but no it's not.

This has everything to do with routing as I indicated. The scenario you described is a very common issue with multipath routing.
Your pings work because you're initiating the outbound traffic from your host, and sending it from 10.10.26.160. Not responding to incoming traffic, and sending it from an address other than 10.10.26.160.

**Comment by thaJeztah** [comment]
@haozhenxiao I'm going to close this issue because this doesn't look like a docker issue to me. Feel free to continue the discussion here after I've closed, I hope you'll be able to resolve your issue with the tips that @phemmer gave here.

(thanks @phemmer for helping out here, it's really appreciated!)
