### ISSUE TITLE
Hook that runs when a Image is mounted, "started", "restarted" or "continued" in any way

### ISSUE THREAD

**Issue by srcspider** [docker/docker#17235]
_I've looked for the functionality but can't seem to find it anywhere, either here, official docs or google; hopefully it's not just me searching for the wrong terminology._

*Is there a way to run a simple script every time a docker image is mounted/run on a machine?*

If there isn't one can we have one?

Use Case: Let's say you have a simple logging system that want to send some very contextual information of the particular instance that is unique to the instance or the specific node/group where the instance runs; we're assuming this information is procurable (which in many environments there is such contextual information)

There are some workarounds for this, such as including a check in every system that tries to use it, or crons. The problem is that the workarounds are annoyingly tangly and complicated (every system has to have this check), and the check woefully unreliable, complicated (has to start only when the image is mounted after its made but not before at any point) or slow (because they have to be started based on a guess with no indication of changes).

**Comment by phemmer** [comment]
Why not adjust the image and use an entrypoint script?

**Comment by cpuguy83** [comment]
Is the events API not sufficient for this?

**Comment by srcspider** [comment]
@cpuguy83 
> Is the events API not sufficient for this?

Google seems to point to Docker Remote API as the thing you're referring to. That's the backwards of what I want.

I need for scripts running INSIDE the container to get notified of things happening with the container (more precisely I need some host information like gcloud metadata api and things like node information from kubernetes for localizing the container in my logs).

> Why not adjust the image and use an entrypoint script?

Uh... I guess a high priority script with single execution and no restart policy would do the trick. 

It sounds like it solves my problem and from what I've read since reporting this there is probably no corner case where the container might get "paused" / "resumed" / "moved" or some such. It should always be a clean restart from the docker image; at least I think so, it's not very clear docker will "never" do that. 

For now at least that workaround should work fine. Thanks. Closing.
