### ISSUE TITLE
Tags in docker inspect contains digests

### ISSUE THREAD

**Issue by tonistiigi** [docker/docker#17246]
#13185 added `"Tags"` to `docker inspect` output but that array will also contain image digests and the output isn't really tags but `repo:tag` pairs(references). is this intentional? Maybe we should rename it.

`/images/json` uses keys `RepoTags` and `RepoDigests`

**Comment by thaJeztah** [comment]
`RepoTags` and `RepoDigests` sgtm for consistency, but that would also mean not just renaming, but also splitting them up, correct?

**Comment by tonistiigi** [comment]
@thaJeztah Yes, although the fact that we currently keep them together should be an implementation detail for historical reasons that may change in the future.

**Comment by vdemeester** [comment]
@tonistiigi on it :wink:
