### ISSUE TITLE
Ambiguuty between name and short ID

### ISSUE THREAD

**Issue by doronp** [docker/docker#17247]
Steps to reproduce:
1 - Create a container of any kind - say Ubuntu
2 - Create a container of another kind - say Redis and give it a name which is a prefix (say 5 chars long) of the former container ID (the one which was created at step 1) Let us mark this prefix and name with XXXXX
3 - docker inspect XXXXX

You will get the container from stage 2.
Looking at the code Get tries as follows:
1 - match exact name
2 - match full Id
3 - match partial ID

now since before the creation of the second container the command in 3 return the Ubuntu container and after it the Redis container return this seems to me like an ambiguity (and if you delete the redis you get the ubuntu again after the inspect command)

**Comment by doronp** [comment]
Version:
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64

Info:
Containers: 70
Images: 118
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 280
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.16.0-38-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 4
Total Memory: 7.829 GiB
Name: vizio-devswarm-host2
ID: JZQE:UR3Q:IVBX:JIH2:MZTT:LETM:GPIK:6ITF:OYXL:F2Z3:KHR6:JCZA
Username: haih
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support

uname:
 Linux ubuntu 3.13.0-51-generic

**Comment by thaJeztah** [comment]
Thanks for reporting, @doronp. The actual behavior (in 1.8) is:

1. If the ID is a full match (i.e., when using the *full ID*), use that
2. If the *Name* is a full match, use that
3. If there's no full match, match on partial ID

So, in all cases, a *full* ID will make sure that you're addressing the right container or image, and is the recommended approach here.

I just tested this and it seems to work as described above, but feel free if you're still able to reproduce this on 1.8 or 1.9

Thanks for reporting, I'm going to close this issue, but feel free to comment after I've closed

**Comment by doronp** [comment]
Hi, 

I just retested with 1.9 and It still behaves that same
(create 1 container take prefix of its ID and name another container with it, then the existence of the second container effect the response you get for inspect on that prefix (which is the name of the second container)) See above for full scenario.

BTW I fully agree that using full ID is best - but what I see is that when people can use prefix they do and this corner may prove problematic.

Thanks,
Doron P

**Comment by thaJeztah** [comment]
@doronp see my previous comment https://github.com/docker/docker/issues/17247#issuecomment-150036904. this is the expected behavior; doing a partial ID match first would, for example, not enable you to use a container named `db` (many people do that) if a container ID exists that starts with `db......`

If you need to access a specific container or image, use the full ID
