### ISSUE TITLE
docker 1.8.3 push fails with 'percent-encoded characters in host' error

### ISSUE THREAD

**Issue by xueshanf** [docker/docker#17258]
I am getting the errors after upgrading CoreOS to CoreOS 835.1.0. The docker engine version is 1.8.3, the private registry version is registry:2.1.1. 

```
/tmp/core-ubuntu $ docker build -t private-registry.domain/core/ubuntu  .
.....
Step 16 : RUN apt-get clean
 ---> Running in bd044c0def01
 ---> c3bc83f39cba
Removing intermediate container bd044c0def01
Step 17 : ONBUILD run apt-get -qq update
 ---> Running in ea9cbce14d3d
 ---> b4f57476154e

/tmp/core-ubuntu $ docker push  private-registry.domain/core/ubuntu
The push refers to a repository [private-registry.domain/core/ubuntu] (len: 1)
b4f57476154e: Buffering to Disk
parse https://%5Cprivate-registry.domin/v2/core/ubuntu/blobs/uploads/a2e892c9-cddb-4c7d-8e4e-dbf0b783a0c2?_state=BUOV6H9YBGURBIIODxSbmG-1ueUNazAu3H6EMeVeC_F7Ik5hbWUiOiJjb3JlL3VidW50dSIsIlVVSUQiOiJhMmU4OTJjOS1jZGRiLTRjN2QtOGU0ZS1kYmYwYjc4M2EwYzIiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMTUtMTAtMjJUMDU6MTQ6MTIuNTMyMTM0MDkXXXXX: percent-encoded characters in host
```
Docker infomation:

```
/tmp/core-ubuntu $ docker -D info

Containers: 5
Images: 97
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.2-coreos
Operating System: CoreOS 835.1.0
CPUs: 2
Total Memory: 3.863 GiB
Name: ip-10-0-2-35.us-west-2.compute.internal
ID: XXXX:PQUM:AEHD:GISS:LO7N:LDVX:NDNS:C3B5:VA6O:QCRV:EY35:XXXX
Username: XXXXXXXX
Registry: https://index.docker.io/v1/
```
I am using the nginx proxy configuration as documented in [here](https://docs.docker.com/registry/nginx/).

I can still pull the images built from docker version 1.7.1, and push them back to the repo without a rebuild. I just seemed having problem to upload the images built with docker 1.8.3. 

Xueshan

**Comment by thaJeztah** [comment]
Can you add the output of `docker version` as well?

**Comment by xueshanf** [comment]
core@ip-10-0-2-35-itla-etcd /tmp/core-ubuntu $ docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.5.1
 Git commit:   cedd534-dirty
 Built:        Fri Oct 16 04:20:25 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.5.1
 Git commit:   cedd534-dirty
 Built:        Fri Oct 16 04:20:25 UTC 2015
 OS/Arch:      linux/amd64

**Comment by thaJeztah** [comment]
It looks like that's a version that's maintained by CoreOS (https://github.com/docker/docker/commit/cedd53482c5a3ce88f3bb98d1d325dae4c95d9b6)

I wonder where the `%5C` comes from (it's a URL-encoded back-slash)

**Comment by NOX73** [comment]
Have the same issue. 

Registry log:

```
time="2015-10-22T09:17:00.941194834Z" level=debug msg="authorizing request" http.request.host="\\registry2.default.kube.ul.home" http.request.id=cd2c6949-8154-40a1-9b3b-a158771
6387b http.request.method=HEAD http.request.remoteaddr="172.16.11.0:47630" http.request.uri="/v2/vss/web/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c2295
5b46d4" http.request.useragent="docker/1.8.3 go/go1.4.2 git-commit/f4bf5c7 kernel/3.19.0-30-generic os/linux arch/amd64" instance.id=52e55d8a-bea8-4970-be75-664b4d67077a servic
e=registry vars.digest="sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" vars.name="vss/web" version=v2.1.1 
```

There is back-slash in http.request.host. I'm wondering what it is doing here and where it came from.

**Comment by dronov** [comment]
Hey, have similar problem with docker at Arch Linux like @xueshanf 

>docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.5.1
 Git commit:   f4bf5c7-dirty
 Built:        Wed Oct 14 11:17:02 UTC 2015
 OS/Arch:      linux/amd64

> Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.5.1
 Git commit:   f4bf5c7-dirty
 Built:        Wed Oct 14 11:17:02 UTC 2015
 OS/Arch:      linux/amd64

**Comment by NOX73** [comment]
It comes from nginx config. Check this line:

```
    proxy_set_header  Host              \$http_host;   # required for docker client's sake
```

**Comment by xueshanf** [comment]
@NOX73 thanks! Removing backslash for both  $http_host and $remote_addr  works. Not sure why it breaks docker 1.8.1 push command.

**Comment by xueshanf** [comment]
I meant 1.8.3, for my case.

**Comment by thaJeztah** [comment]
Looks like you've *copied* [the example from the docs](https://github.com/docker/distribution/blob/a266f99418758264347f78fc469e7c2823478b1b/docs/nginx.md#setting-things-up) instead of running it (it's a bash script to run)

I'm going to close this issue, because this isn't a bug in docker. Feel free to continue the discussion after I've close this!
