### ISSUE TITLE
docker 1.8.2 pull/push to IPv6-enabled registry fails

### ISSUE THREAD

**Issue by shmcfarl** [docker/docker#17252]
A 'docker push' (or pull) fails on ping attempt to registry.

root@docker-v6-2:~# docker push docker-v6-1.example.com:5000/ubuntu
The push refers to a repository [docker-v6-1.example.com:5000/ubuntu] (len: 1)
unable to ping registry endpoint https://docker-v6-1.example.com:5000/v0/
v2 ping attempt failed with error: Get https://docker-v6-1.example.com:5000/v2/: dial tcp: no suitable address found
 v1 ping attempt failed with error: Get https://docker-v6-1.example.com:5000/v1/_ping: dial tcp: no suitable address found

IPv6 works to Docker Registry:
root@docker-v6-2:~# ping6 -n docker-v6-1.example.com
PING docker-v6-1.example.com(fd15:4ba5:5a2b:1009:20c:29ff:fef3:f848) 56 data bytes
64 bytes from fd15:4ba5:5a2b:1009:20c:29ff:fef3:f848: icmp_seq=1 ttl=64 time=0.257 ms
64 bytes from fd15:4ba5:5a2b:1009:20c:29ff:fef3:f848: icmp_seq=2 ttl=64 time=0.421 ms

root@docker-v6-2:~# wget --no-check-certificate  https://docker-v6-1.example.com:5000/v2/
--2015-10-21 14:15:30--  https://docker-v6-1.example.com:5000/v2/
Resolving docker-v6-1.example.com (docker-v6-1.example.com)... fd15:4ba5:5a2b:1009:20c:29ff:fef3:f848
Connecting to docker-v6-1.example.com (docker-v6-1.example.com)|fd15:4ba5:5a2b:1009:20c:29ff:fef3:f848|:5000... connected.
WARNING: cannot verify docker-v6-1.example.com's certificate, issued by ‘/C=US/ST=CO/L=Boulder/O=example/CN=docker-v6-1.example.com/emailAddress=eyepv6@example.com’:
  Self-signed certificate encountered.
HTTP request sent, awaiting response... 200 OK
Length: 2 [application/json]
Saving to: ‘index.html’

100%[=========================================================================================>] 2           --.-K/s   in 0s

2015-10-21 14:15:30 (501 KB/s) - ‘index.html’ saved [2/2]

So the issue seems to be in the 'docker push' logic where it tries to first ping the registry and since its ping syntax or protocol dependency is broken then the ping test fails.

Environment:
Tested on both physical HW and VMs (Fusion).

root@docker-v6-2:~# docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64
root@docker-v6-2:~# docker info
Containers: 1
Images: 8
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 10
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-63-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 2
Total Memory: 3.854 GiB
Name: docker-v6-2
ID: JYQW:CGZU:Q6P7:J46F:XIAG:VO6Y:TPLU:JBMF:QIMW:7ANO:P5LI:LAEU
WARNING: No swap limit support
root@docker-v6-2:~# uname -a
Linux docker-v6-2 3.13.0-63-generic #103-Ubuntu SMP Fri Aug 14 21:42:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by endophage** [comment]
@shmcfarl the term 'ping' in the docker output is an unfortunately misused term. It's not literally trying to do a ping, it is (if I remember the code right) attempting to do an HTTP GET to the /v2 endpoint. Would you be able to post the `http` section of your registry configuration?

**Comment by shmcfarl** [comment]
After a rebuild and a simplification of my docker-compose file, it is working.  I had an environment setting in my docker-compose setup that was causing an issue with the registry for IPv6.  Everything seems to be working now:

root@docker-v6-2:~# ping6 -n docker-v6-1.example.com
PING docker-v6-1.example.com(fd15:4ba5:5a2b:1009:20c:29ff:fef3:f848) 56 data bytes
64 bytes from fd15:4ba5:5a2b:1009:20c:29ff:fef3:f848: icmp_seq=1 ttl=64 time=0.402 ms
64 bytes from fd15:4ba5:5a2b:1009:20c:29ff:fef3:f848: icmp_seq=2 ttl=64 time=0.367 ms

root@docker-v6-2:~# docker tag ubuntu docker-v6-1.example.com:5000/ubuntu
root@docker-v6-2:~# docker push docker-v6-1.example.com:5000/ubuntu
The push refers to a repository [docker-v6-1.example.com:5000/ubuntu] (len: 1)
a005e6b7dd01: Image successfully pushed
002fa881df8a: Image successfully pushed
66395c31eb82: Image successfully pushed
0105f98ced6d: Image successfully pushed
latest: digest: sha256:167f1c34ead8f1779db7827a55de0d517b7f0e015d8f08cf032c7e5cd6979a84 size: 6800

root@docker-v6-1:~# tcpdump -n -vvv ip6 -i eth0
tcpdump: listening on eth0, link-type EN10MB (Ethernet), capture size 65535 bytes
19:36:09.283820 IP6 (hlim 64, next-header TCP (6) payload length: 40) fd15:4ba5:5a2b:1009:6540:bb36:2e23:f5a2.56066 > fd15:4ba5:5a2b:1009:20c:29ff:fef3:f848.5000: Flags [S], cksum 0x65b1 (correct), seq 2754754540, win 28800, options [mss 1440,sackOK,TS val 645579 ecr 0,nop,wscale 7], length 0
19:36:09.283930 IP6 (hlim 64, next-header TCP (6) payload length: 40) fd15:4ba5:5a2b:1009:20c:29ff:fef3:f848.5000 > fd15:4ba5:5a2b:1009:6540:bb36:2e23:f5a2.56066: Flags [S.], cksum 0xcd92 (correct), seq 1577491031, ack 2754754541, win 28560, options [mss 1440,sackOK,TS val 859496 ecr 645579,nop,wscale 7], length 0
