### ISSUE TITLE
Manual cache control in Dockerfile via cache labels

### ISSUE THREAD

**Issue by bsideup** [docker/docker#17260]
Hi! I do know that current Dockerfile format is freezed and you do not accept any new proposals, but I want it to be as a "TODO" for the future when this "dockerfile freeze" will end.
# Problem
Currently docker cache (which is filesystem-based cache) works in the way of sequential caching - if one step changed then all steps will be invalidated. It's good until you have some 100% non-conflict filesystem changes. Few examples:

1. You're using some Java application server. To install it, you need: some base image like ubuntu, java and server itself (like Tomcat). And your WAR file as well. And all of them could be installed in parallel because they don't share filesystem (Java goes to /opt/java/, Tomcat goes to /opt/tomcat/, etc).
1. You're deploying your app as a Go statically linked binary and you use "alpine" as a base image. Then you update base image (because of some critical security fix). Currently Docker will re-apply your Go app on top of alpine, but you don't need it since they have no conflicts in file system.

# Proposal
Introduce *CACHE_* commands in Dockerfile. Example:

### Before
```Dockerfile
# base image update will clear the cache
FROM ubuntu

# Java update (which is frequent) will do the same
RUN <install Java> 

RUN <download and install Tomcat>

ADD app.war /path/to/ROOT.war
```
So, all of them are separate folders in file system.

### After
```Dockerfile
# will force re-cache only on dependent layers
CACHE_LAYER ubuntu_installed
FROM ubuntu

# Will be changed only in case of change in base image
CACHE_FROM ubuntu_installed
RUN apt-get update && apt-get install -y htop && rm -rf /var/lib/apt/lists/*

# tools for other steps
CACHE_FROM ubuntu_installed
CACHE_LAYER base_tools
RUN apt-get update && apt-get install -y unzip && rm -rf /var/lib/apt/lists/*

# We still need ubuntu because of wget/tar, but we don't want this step to be re-executed after it was cached once (because each version of wget/tar would be fine)
CACHE_FROM scratch
CACHE_AFTER ubuntu_installed
CACHE_LAYER java
RUN <download and untar Java>

CACHE_FROM base_tools
CACHE_LAYER tomcat
RUN <download and unzip Tomcat>

# means that we want to use "scratch" meta-label which is "empty filesystem"
CACHE_FROM scratch
CACHE_LAYER app
ADD app.war /path/to/ROOT.war
ENV JAVA_OPTS="-Xmx1024m"

CACHE_FROM java, tomcat, app
RUN <deploy app>
```

If Java step was changed, then it will execute only following steps and will use `base_tools` layer as a base
```Dockerfile
RUN <download and unpack Java>
RUN <deploy app>
```

If app was changed, then it will execute only following steps:
```Dockerfile
ADD app.war /path/to/ROOT.war
RUN <deploy app>
```

If base image was changed, it will trigger cache invalidation for the following steps (because of base tools dependency):
```Dockerfile
RUN apt-get update && apt-get install -y htop && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y wget curl unzip && rm -rf /var/lib/apt/lists/*
RUN <download and unzip Tomcat>
RUN <deploy app>
```

**Comment by LK4D4** [comment]
I think such specific use-case can be built with tooling around docker. Implementation in Dockerfile would be challenging and hard to maintain.

**Comment by duglin** [comment]
I'd still prefer just the simple `NOCACHE` cmd to turn off caching from that point on in the Dockerfile.

**Comment by LK4D4** [comment]
@duglin Yeah, I believe there is issue about this as well.

**Comment by duglin** [comment]
@LK4D4 more than that there was a rejected PR:  https://github.com/docker/docker/pull/10682
