### ISSUE TITLE
When spawning a docker container via per-minute crontab, box eventually complains of "too many open files"

### ISSUE THREAD

**Issue by PeterGrace** [docker/docker#17264]
It appears that spawning lots of docker containers, even if they exit quickly and remove themselves, will still eventually exhaust all open files for the docker daemon.

**Versions:**
_Distro:_**CentOS 6.7**

_Kernel:_ **2.6.32-573.7.1.el6.x86_64**

_Docker:_ **Docker version 1.7.1, build 786b29d/1.7.1**

**Background:**
I have a small script that I package in a docker container to ensure the dependencies are proper across the machines that run that script.

It is triggered via a per-minute crontab with the following entry:

     * * * * * docker run -i --rm=true docker-registry/pgrace/sei_redascript >/dev/null

The script ran fine for about 12 hours, but afterwards we started receiving cron e-mails with this error:

    Error response from daemon: open /var/lib/docker/graph/f3acb0cc41ecc5f579fa831c3b1a5137a5f2570060a08e8abe0c71e4d2edbf89/layersize: too many open files

Checking the docker daemon's /proc/pidnum/fd subdirectory, I noticed it had 1023 entries in that list, most consisting of the below output:

    lr-x------ 1 root root 64 Oct 22 13:10 97 -> /cgroup/memory/docker/7409385b11e991fddc7fb5d0abe42cd1c3729c1de7700d00e4775160b011b48a/memory.oom_control (deleted)
    lrwx------ 1 root root 64 Oct 22 13:10 970 -> [eventfd]
    lr-x------ 1 root root 64 Oct 22 13:10 971 -> /cgroup/memory/docker/7c8216591f05ba60c7addeca1c9150169eccada23f2d9587ee7896b1825d4e3f/memory.oom_control (deleted)
    lrwx------ 1 root root 64 Oct 22 13:10 972 -> [eventfd]
    lr-x------ 1 root root 64 Oct 22 13:10 973 -> /cgroup/memory/docker/2366735fa41ea8f6d4ac9f220be3d31f205280121e0b67eac728a47937a80b6c/memory.oom_control (deleted)
    lrwx------ 1 root root 64 Oct 22 13:10 974 -> [eventfd]
    lr-x------ 1 root root 64 Oct 22 13:10 975 -> /cgroup/memory/docker/370dae9eebffbe779fb1b0f5e1100afb4f4a21a46d5bebbec4b46d901730d3c0/memory.oom_control (deleted)
    lrwx------ 1 root root 64 Oct 22 13:10 976 -> [eventfd]
    lr-x------ 1 root root 64 Oct 22 13:10 977 -> /cgroup/memory/docker/7bc9f57cd1a98a9c21f4a9a1f284ff14c5e1a004d6fb9595b88ee036b2c539b8/memory.oom_control (deleted)
    lrwx------ 1 root root 64 Oct 22 13:10 978 -> [eventfd]
    lr-x------ 1 root root 64 Oct 22 13:10 979 -> /cgroup/memory/docker/e77bb2ad9946fd4e836d03fb6c9e26723ac385ba406797a1592f4762bc28199f/memory.oom_control (deleted)
    lrwx------ 1 root root 64 Oct 22 13:10 98 -> [eventfd]
    lrwx------ 1 root root 64 Oct 22 13:10 980 -> [eventfd]
    lr-x------ 1 root root 64 Oct 22 13:10 981 -> /cgroup/memory/docker/879d7c49f5f63d5003977a955aedd075219bc102371ecb5e6e6de01125fccf6e/memory.oom_control (deleted)
    lrwx------ 1 root root 64 Oct 22 13:10 982 -> [eventfd]
    lr-x------ 1 root root 64 Oct 22 13:10 983 -> /cgroup/memory/docker/bcf797e58063fbecc2b55ac3c3cd15c4b0b94330c39b25c347fb7b1b56b83cfe/memory.oom_control (deleted)
    lrwx------ 1 root root 64 Oct 22 13:10 984 -> [eventfd]
    lr-x------ 1 root root 64 Oct 22 13:10 985 -> /cgroup/memory/docker/49db6f25923f47bc64584ffacf1e8b91f0d66e5aaeb004b50206c213e3a33258/memory.oom_control (deleted)
    lrwx------ 1 root root 64 Oct 22 13:10 986 -> [eventfd]
    lr-x------ 1 root root 64 Oct 22 13:10 987 -> /cgroup/memory/docker/d5550588fa2df59ea7c31e70939298e48cae2c16ee0bc8eafee73bf7bd53b1dc/memory.oom_control (deleted)
    lrwx------ 1 root root 64 Oct 22 13:10 988 -> [eventfd]
    lr-x------ 1 root root 64 Oct 22 13:10 989 -> /cgroup/memory/docker/24281a2ee50c8e0466462bec76bffa579f6c704a4cb043e3a4b46bc0f1d21644/memory.oom_control (deleted)
    lr-x------ 1 root root 64 Oct 22 13:10 99 -> /cgroup/memory/docker/c5308c5a0b8f25bd01efdebc60739fcea3c31d8741fc9e888e627f501b76a399/memory.oom_control (deleted)
    lrwx------ 1 root root 64 Oct 22 13:10 990 -> [eventfd]
    lr-x------ 1 root root 64 Oct 22 13:10 991 -> /cgroup/memory/docker/d24ee6a39960837fe56bd946c25511cd7b39ace1410f0ba7f223b8d59e23e7a9/memory.oom_control (deleted)
    lrwx------ 1 root root 64 Oct 22 13:10 992 -> [eventfd]
    lr-x------ 1 root root 64 Oct 22 13:10 993 -> /cgroup/memory/docker/ee3d9ec05298432d47f98fe5f12e9d6091dfbd61a95315e1721803bf6300aac6/memory.oom_control (deleted)
    lrwx------ 1 root root 64 Oct 22 13:10 994 -> [eventfd]
    lr-x------ 1 root root 64 Oct 22 13:10 995 -> /cgroup/memory/docker/3dea1e1cb423f5d814ad149031ad40d7891010d8073edf2b58c108445e94ccf5/memory.oom_control (deleted)
    lrwx------ 1 root root 64 Oct 22 13:10 996 -> [eventfd]
    lr-x------ 1 root root 64 Oct 22 13:10 997 -> /cgroup/memory/docker/c71e93b3a370958751173535ff53ed266861b5ab760f2223b31d5b7f36da66ce/memory.oom_control (deleted)
    lrwx------ 1 root root 64 Oct 22 13:10 998 -> [eventfd]
    lr-x------ 1 root root 64 Oct 22 13:10 999 -> /cgroup/memory/docker/f3c00abb6fcbacb6e90544f3b33395a04c35ac34bef98a4fc130e12ec7f1709f/memory.oom_control (deleted)

**Please let me know if there's any other information you require, I am pretty sure this will be a reproducible issue, I'll confirm that in 12 hours or so!**

**Comment by PeterGrace** [comment]
I provided version and uname above already, above.  The docker host is in a vSphere cluster, virtualized and with the latest vmware guest tools.

`docker info`:
    Containers: 6
    Images: 87
    Storage Driver: devicemapper
     Pool Name: docker-253:0-392886-pool
     Pool Blocksize: 65.54 kB
     Backing Filesystem: extfs
     Data file:
     Metadata file:
     Data Space Used: 4.913 GB
     Data Space Total: 107.4 GB
     Data Space Available: 102.5 GB
     Metadata Space Used: 7.279 MB
     Metadata Space Total: 2.147 GB
     Metadata Space Available: 2.14 GB
     Udev Sync Supported: true
     Deferred Removal Enabled: false
     Library Version: 1.02.95-RHEL6 (2015-09-08)
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 2.6.32-573.7.1.el6.x86_64
    Operating System: <unknown>
    CPUs: 1
    Total Memory: 7.688 GiB
    Name: redactedhostname
    ID: IFOH:RL5U:OZPN:5FQJ:3BIS:7HNH:BBEW:AP5W:LLOA:KN4N:Z5RH:QWQR

Steps to repro:
 - Start a docker container every minute

Results received: `too many open files`, could not spawn additional containers.  Additionally, `docker images` returned no results.  After restarting docker daemon, `docker images` again returned results.

Results expected: I did not expect any `too many open files` errors, or any errors whatsoever.

**Comment by thaJeztah** [comment]
Hi @PeterGrace, thanks for reporting. Are you able to reproduce this on the current version of docker and CentOS 7.x? The problem here is that we ended support for CentOS/RHEL 6.x with Docker 1.8 and Docker 1.7 will no longer receive patch updates. If you're still able to reproduce this on the current release (and a supported platform), we can investigate this.

**Comment by LK4D4** [comment]
Centos 6 is not supported anymore.
