### ISSUE TITLE
ENH: Respect `.dockerignore` in same dir as `Dockerfile`

### ISSUE THREAD

**Issue by jakirkham** [docker/docker#17267]
# Use Case

It is common to have a context that is higher than some `Dockerfile`s. In this case, not every `Dockerfile` cares about the same things in the context. It would be helpful to specify what can be ignored on a per `Dockerfile` case basis. However, this does not mean that there are not some things that can be ignored by all the `Dockerfile`s

# Request

Currently, `.dockerignore` needs to be at the root of the context to be respected. However, it would be nice if one that is specified in the same directory as the `Dockerfile` is **also** respected.

# Evidence of Use Case

Here are some people with this usage pattern already. ( https://github.com/docker/hub-feedback/issues/292 ) ( https://github.com/docker/hub-feedback/issues/403 )

**Comment by jakirkham** [comment]
This might provide another way to address this ( https://github.com/docker/docker/issues/12886 ).

**Comment by thaJeztah** [comment]
@jakirkham thanks for suggesting! I think it's best to close this one though, and keep the discussion on #12886 because they're very related.

Please continue the discussion in #12886
