### ISSUE TITLE
docker volume create to a Swarm Master issues command for each host in cluster

### ISSUE THREAD

**Issue by kacole2** [docker/docker#17271]
Not sure if this is a bug with the Docker 1.9's storage enhancement or Swarm. 

If I issue the command `docker volume create --driver=rexray --name=student001a --opt=volumetype=io1 --opt=iops=100 --opt=size=10` to a docker daemon configured to point to a Swarm Master, then this command is issued on every host in the Swarm cluster.

The result is multiple volumes created with the same name but unique IDs
```
$ rexray volume get
...
- name: student001a
  volumeid: vol-3b9811d7
  availabilityzone: us-east-1b
  status: available
  volumetype: io1
  iops: 100
  size: "10"
  networkname: ""
  attachments: []
- name: student001a
  volumeid: vol-819b126d
  availabilityzone: us-east-1b
  status: available
  volumetype: io1
  iops: 100
  size: "10"
  networkname: ""
  attachments: []
```

I'm assuming that the `docker volume create` function was intended to only create a single volume. I do not know if this logic should be directed to the volume-driver or the docker engine itself or within Swarm.

**Comment by thaJeztah** [comment]
ping @vieux @abronan can you have a look here?

**Comment by cpuguy83** [comment]
This is the expected behavior.
Same thing happens for pull and network operations.

**Comment by rgbkrk** [comment]
> This is the expected behavior.

Interesting. I'm assuming data isn't synced though?

**Comment by thaJeztah** [comment]
@rgbkrk I think that depends on the driver that's used

**Comment by everett-toews** [comment]
@kacole2 I'd be interested to hear your thoughts on https://github.com/docker/swarm/issues/1529

**Comment by kacole2** [comment]
@everett-toews will post on your issue... but yeah... it's a bit annoying that there is a new volume created for every host on persistent detached storage.

**Comment by thaJeztah** [comment]
Closing this in favor of https://github.com/docker/swarm/issues/1529, please continue the discussion there. Thanks!
