### ISSUE TITLE
add ipam driver specific options

### ISSUE THREAD

**Issue by rmb938** [docker/docker#17282]
libnetwork allows driver specific options for ipam drivers but there does not seem to be a way to pass them in via the cli or api.

docker version: ```Docker version 1.9.0-dev, build 4816626```
docker into:
```
Containers: 13
Images: 9
Server Version: 1.9.0-dev
Storage Driver: devicemapper
 Pool Name: docker-253:0-33662528-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.595 GB
 Data Space Total: 107.4 GB
 Data Space Available: 10.87 GB
 Metadata Space Used: 2.691 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: false
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.14.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 1.797 GiB
Name: ccompute1.rmb938.com
ID: IAQS:6E74:7NGG:5JOG:JXFM:26VD:IAQV:FZNU:E23J:QUAA:NI4O:DI3S
```

uname -a ```Linux ccompute1.rmb938.com 3.10.0-229.14.1.el7.x86_64 #1 SMP Tue Sep 15 15:05:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux```

The current cli and api has the ability to pass in driver specific options for network drivers but not ipam drivers.

**Comment by rmb938** [comment]
It would also be useful to allow ipam options to be passed in while connecting a container to a network. These options would then be passed into the ipam driver's RequestAddress

**Comment by mavenugo** [comment]
we could possibly do that via the `-opt` that is currently defined for `docker network create` and filter out the key that are prefixed with say `com.docker.network.ipam.`.
@aboch @mrjana wdyt ?

**Comment by rmb938** [comment]
That would work. Also possibly adding -opt to ```docker network connect``` so options can be passed in when connecting to a network. That may require some work on libnetwork's end though.

**Comment by aboch** [comment]
Agree, also soon or later we may want to allow some ipam config to be passed during network connect to support user chosen ip for the container or to allow an ipam plugin to provide a specific address to a specific container

**Comment by rmb938** [comment]
> allow an ipam plugin to provide a specific address to a specific container 

That is exactly what I would be using the options on connect for. Options will be sent to the ipam plugin and an ip will be assigned based off of those options.

**Comment by rmb938** [comment]
Pull request for IPAM config driver options docker/docker#17316

**Comment by linuxluser** [comment]
I have a use case where I would like to have a custom IPAM driver that assigns an IP address based upon information about the container being started, such as the hostname that's assigned during a `docker run` command. It seems that this is currently not possible. The new --ipam-opt flag can only handle static options that are set when the network is created. How would this help for per-container information that the IPAM driver wants to know to make a decision?

**Comment by cpuguy83** [comment]
@linuxluser docker explicitly does not provide this information to drivers.

Also closing this issue because #17316 is merged.
