### ISSUE TITLE
Errant :warning on registry doc

### ISSUE THREAD

**Issue by nathanleclaire** [docker/docker#17281]
FYI @moxiegirl @thaJeztah -- looks like at https://docs.docker.com/registry/insecure/ in the second section there is a dangling ":warning" which doesn't get converted correctly to the relevant HTML bit.

**Comment by thaJeztah** [comment]
Thanks @nathanleclaire, looks like they used emoji's in their documentation; https://github.com/docker/distribution/blob/master/docs/insecure.md

**Comment by nathanleclaire** [comment]
:clap:
