### ISSUE TITLE
1.9: build caching broken from symlink??

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#17290]
This is an odd one but I tried to extract out the offending files out of a real build.  In the end second build in the below script will end up using the cached image for `CP . ./` when it shouldn't

```bash
#!/bin/bash

cat > Dockerfile << "EOF"
FROM busybox
COPY . ./
EOF

mkdir -p Godeps/_workspace/src/github.com/fsouza/go-dockerclient/testing/data
ln -s doesnotexist Godeps/_workspace/src/github.com/fsouza/go-dockerclient/testing/data/symlink

docker build -f Dockerfile .
echo ${RANDOM} > "$(date)"
docker build  -f Dockerfile .
```

This will output

```
Sending build context to Docker daemon  12.8 kB
Step 1 : FROM busybox
 ---> 8c2e06607696
Step 2 : COPY . ./
 ---> Using cache
 ---> 09b76d77bc36
Successfully built 09b76d77bc36
Sending build context to Docker daemon 13.82 kB
Step 1 : FROM busybox
 ---> 8c2e06607696
Step 2 : COPY . ./
 ---> Using cache
 ---> 09b76d77bc36
Successfully built 09b76d77bc36
```

Notice the offending lines

```
Step 2 : COPY . ./
 ---> Using cache
 ---> 09b76d77bc36
```

Version stuff

```
docker version; docker info
Client:
 Version:      1.9.0-rc2
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   60d36f7
 Built:        Fri Oct 23 00:20:59 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0-rc2
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   60d36f7
 Built:        Fri Oct 23 00:20:59 UTC 2015
 OS/Arch:      linux/amd64
Containers: 17
Images: 1249
Server Version: 1.9.0-rc2
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.1-040001-generic
Operating System: Ubuntu 14.10
CPUs: 4
Total Memory: 15.4 GiB
Name: inotmac
ID: FPSO:Z7SO:BZJ3:IXH4:DNKV:UPZQ:KLP2:IRXW:5CBY:PBDM:HAKO:UOC7
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 20
 System Time: 2015-10-22T19:45:15.96379998-07:00
 EventsListeners: 0
 Init SHA1: 
 Init Path: /home/darren/Downloads/docker-1.9.0-rc2
 Docker Root Dir: /var/lib/docker
Username: ibuildthecloud
Registry: https://index.docker.io/v1/
```

**Comment by ibuildthecloud** [comment]
Somebody let me know if they can reproduce.

**Comment by vdemeester** [comment]
@ibuildthecloud hum, using docker-1.9.0-rc2 I cannot reproduce on my laptop.

```
Sending build context to Docker daemon 6.656 kB
Step 1 : FROM busybox
 ---> d7057cb02084
Step 2 : COPY . ./
 ---> Using cache
 ---> 9f24ac82cfc0
Successfully built 9f24ac82cfc0
Sending build context to Docker daemon  7.68 kB
Step 1 : FROM busybox
 ---> d7057cb02084
Step 2 : COPY . ./
 ---> 2f80eb99c501
Removing intermediate container fac333456dd4
Successfully built 2f80eb99c501
```

**Comment by ibuildthecloud** [comment]
@vdemeester I've yet to find anyone who can reproduce and I haven't reproduced except on my laptop....  But it consistently fails on my laptop.

**Comment by vdemeester** [comment]
@ibuildthecloud hum.. more info on your laptop (storage driver & co) ?

**Comment by runcom** [comment]
I can't repo this

**Comment by ibuildthecloud** [comment]
Okay, I'm closing. I wiped out my `/var/lib/docker` and now I can't reproduce anymore.  So.... fixed that :)

**Comment by ibuildthecloud** [comment]
I'm reopening because I consistently get this issue.  I will work on a new test case.

**Comment by thaJeztah** [comment]
All on overlay? or also on other drivers?

**Comment by ibuildthecloud** [comment]
@thaJeztah preparing a new test case, more involved but should be more reproducible...

**Comment by thaJeztah** [comment]
thanks @ibuildthecloud we've moved this to the 1.9.1 milestone for now, but thanks so much for this :+1:

**Comment by ibuildthecloud** [comment]
@thaJeztah I found the root cause and shared it on #docker-maintainer (sorry, on plane, and have spotty internet, i'll try to update issue later)

**Comment by thaJeztah** [comment]
@ibuildthecloud yup, saw it on IRC, thx!

**Comment by ibuildthecloud** [comment]
If this could be fixed in 1.9.0 it would be greatly appreciated :)

**Comment by thaJeztah** [comment]
The whole team is currently looking at the issue to see if there's a way to still get it fixed before the 1.9 release, but (as you probably understand) no promises :heart:

**Comment by ibuildthecloud** [comment]
I'm in SF, I'll personally show up to the office for moral support if needed :smile:  (I think I might have made this release hell...)

**Comment by thaJeztah** [comment]
@ibuildthecloud unfortunately, it didn't make it in the release, but I'm sure they welcome you for moral support (and proper coffee :smile:) :heart:

**Comment by jfrazelle** [comment]
we <3 moral support

**Comment by akatrevorjay** [comment]
Just got bit by this on the 1.9.0 stable release. It was not easy to track down either.
Can we put a big notice out that 1.9.0 has a bug that breaks many builds that use symlinks?
Maybe in the release notes?
Thanks!

**Comment by thaJeztah** [comment]
@tiborvass perhaps on the releases page on GitHub? ^^

**Comment by pwaller** [comment]
I just lost several hours editing code I wasn't running to this exact situation. The failure mode is pretty gnarly. I also have a vendor'd copy of go-dockerclient. It's amusing what broken symlinks can do to you. I would very much appreciate a release of this ASAP so we can use docker for our builds again!

**Comment by akatrevorjay** [comment]
@tiborvass Is this showcased on the releases page on GitHub? I still don't see it?

**Comment by reejosamuel** [comment]
```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 35
Server Version: 1.12.0-rc3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 23
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null bridge host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.14-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.954 GiB
Name: moby
ID: ZUAS:CKCG:YAG7:XWIN:TYFK:INOY:TPZE:REI6:DEO7:AQCX:QD4T:UTAU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 30
 System Time: 2016-07-06T15:57:55.119832527Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: carbonr
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8

```

Happening again on this version

**Comment by thaJeztah** [comment]
@reejosamuel do you have a way to reproduce?

**Comment by akatrevorjay** [comment]
Was this *ever* added to the release notes?


Thanks,
Trevor

**Comment by thaJeztah** [comment]
It's in the release notes for 1.9.1 https://github.com/docker/docker/releases/tag/v1.9.1
