### ISSUE TITLE
[Doc] Working with containers guide not updated to use Docker-machine

### ISSUE THREAD

**Issue by mchiang0610** [docker/docker#17297]
Description of problem:
cc/ @moxiegirl 

Docker documentation is not updated to use Docker machine. 

![image](https://cloud.githubusercontent.com/assets/3325447/10685004/c5e132a4-7908-11e5-86c5-d54f1d1df9b8.png)
 
Additional Information: 
https://docs.docker.com/userguide/usingdocker/

**Comment by thaJeztah** [comment]
Thanks @mchiang0610, it looks like this has already been resolved in https://github.com/docker/docker/pull/14713. The current version of the docs no longer contain the reference to boot2docker, but the fixed version has not been published yet on https://docs.docker.com (which will be together with the 1.9 release)
