### ISSUE TITLE
Docker reporting 'bad certificate' with docker commands

### ISSUE THREAD

**Issue by ravishtiwari** [docker/docker#17314]
Hi,
I am getting following error with any docker command that I run:
```
docker run hello-world
The server probably has client authentication (--tlsverify) enabled. Please check your TLS client certification settings: Post https://192.168.99.100:2376/v1.20/containers/create: remote error: bad certificate
```
 Even with simple **docker version** command. 
My system info: 
OS : **Mac OS X Yosemite (10.10.5)**
docker version: 
``` 
1.8.3
```
docker info: 
```
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 18:01:15 UTC 2015
 OS/Arch:      darwin/amd64
```
*uname -a:*
```
Darwin ravishk.local 14.5.0 Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64 x86_64
```

*Steps to reproduce*
- Install docker package from docker.com, using following guide http://docs.docker.com/mac/step_one/
- Go to Terminal and do *docker run hello-world*

You'll the TLS verify error, instead output stated in the getting started guide. I've used Docker on Ubuntu earlier, but, never faced this issue before.

Ravish

**Comment by cpuguy83** [comment]
Hello, seems like this ought to go in github.com/docker/toolbox.

**Comment by ravishtiwari** [comment]
@cpuguy83 thanks. If this belongs to toolbox, let me close this and raise a it there.
