### ISSUE TITLE
Update syntax for docker network inspect

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#17318]
@vdemeester You might want this one sir!  The command's help syntax should be updated:

`docker network inspect [OPTIONS] NETWORK  [NETWORK...]`

Based on this comparison

```
ubuntu@ip-172-31-36-118:~$ docker network inspect  --help

Usage:	docker network inspect [OPTIONS] NETWORK

Displays detailed information on a network

  --help=false       Print usage
ubuntu@ip-172-31-36-118:~$ docker inspect --help

Usage:	docker inspect [OPTIONS] CONTAINER|IMAGE [CONTAINER|IMAGE...]

Return low-level information on a container or image
```

**Comment by vdemeester** [comment]
ah :sweat_smile: 
Taking it ! :stuck_out_tongue_closed_eyes: Thanks :P

**Comment by thaJeztah** [comment]
tsk tsk, @moxiegirl you forgot to include an emoji in the description to make it @vdemeester compatible! 😋

**Comment by vdemeester** [comment]
ohh :scream: I actually forgot an unicode one :sob: 🐸

**Comment by moxiegirl** [comment]
:eyes: + :sob: @vdemeester @thaJeztah

**Comment by thaJeztah** [comment]
haha :bird:

**Comment by vdemeester** [comment]
@moxiegirl 😽 😝
