### ISSUE TITLE
Ubuntu install instructions not working, failing when trying to add the gpg key

### ISSUE THREAD

**Issue by ryanwalls** [docker/docker#17315]
# BUG REPORT INFORMATION

Use the commands below to provide key information from your environment:

docker version: n/a
docker info: n/a
uname -a: 3.13.0-48-generic

Provide additional environment details (AWS, VirtualBox, physical, etc.):  This is the default Ubuntu 14.04 LTS AWS instance for the free tier in EC2.

List the steps to reproduce the issue:
1.  Launch new EC2 instance using default Ubuntu free tier
2.  SSH to new server
3.  Run
```
apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
```

Describe the results you received:
Response: 
```
gpg: requesting key 2C52609D from hkp server pgp.mit.edu
gpg: no writable keyring found: eof
gpg: error reading `[stream]': general error
gpg: Total number processed: 0
```

Describe the results you expected:
Expected the command to run successfully.

Provide additional info you think is important:

----------END REPORT ---------

**Comment by ryanwalls** [comment]
Updated with template.

**Comment by ryanwalls** [comment]
Fixed the issue.  You just need to run it as root user.  e.g.  
```
sudo apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
```

**Comment by ryancastle** [comment]
Thanks

**Comment by sghiassy** [comment]
@ryanwalls suggestion worked for me. Thx

**Comment by xbugster** [comment]
sudo works! thanks
