### ISSUE TITLE
docker inspect should show subnet, iprange, gateway

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#17323]
`docker inspect`  should also return:

* subnet
* ip-range
* gateway

They should show with the default or empty if they have nothing.

**Comment by LK4D4** [comment]
@thaJeztah @mavenugo psst

**Comment by thaJeztah** [comment]
Not sure if IP-range would make much sense for inspect on a single container (it is visible on `docker network inspect`), the other properties possibly

ping @mavenugo wdyt?

**Comment by mavenugo** [comment]
Yes. I dont see a need for ip-range and gateway for containers. infact the most important one is the ip-address which we already display. I think we should just close this issue.

**Comment by thaJeztah** [comment]
I agree, but @moxiegirl if you recall if there was a specific use case for the other properties, please let us know :heart:
