### ISSUE TITLE
Corrections to Ubuntu installation instructions

### ISSUE THREAD

**Issue by ffxsam** [docker/docker#17326]
https://docs.docker.com/installation/ubuntulinux/

This:

    $ apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

Should be:

    $ sudo apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

And `sudo usermod -aG docker ubuntu` is listed under optional configurations, but that step is most definitely required.

**Comment by thaJeztah** [comment]
For the first issue (adding `sudo`), perhaps we could change the text;

    If you haven’t already done so, log into your Ubuntu instance.

To

    If you haven’t already done so, log into your Ubuntu instance as a privileged user

(Or similar), so that we don't have to add `sudo` to all steps


> And sudo usermod -aG docker ubuntu is listed under optional configurations, but that step is most definitely required.

No, that step is really optional, as is explained in the introduction of that section;

> To avoid having to use sudo when you use the docker command.....

**Comment by Evalle** [comment]
#dibs

**Comment by Evalle** [comment]
Hi, info was added in https://github.com/docker/docker/pull/17523 
Happy Halloween! :jack_o_lantern:

**Comment by thaJeztah** [comment]
Thanks @Evalle! Will have a look later on :smile: 

Halloween is not as big in the Netherlands as in the United States, but thanks :+1:
