### ISSUE TITLE
[1.9.0] [windowsserver] run --net=host fails

### ISSUE THREAD

**Issue by tiagomacarios** [docker/docker#17321]
# Description of problem:

docker run --net does not seem to work on windows server. It looks like this was already reported on #14615 which is closed, but problem persists (maybe I missed something)?

```
PS C:\> docker version
Client:
 Version:      1.9.0-dev
 API version:  1.22
 Go version:   go1.4.3
 Git commit:   a2e5bbe
 Built:        Fri Oct 23 20:13:08 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.9.0-dev
 API version:  1.22
 Go version:   go1.4.3
 Git commit:   a2e5bbe
 Built:        Fri Oct 23 20:13:08 UTC 2015
 OS/Arch:      windows/amd64

PS C:\> docker info
Containers: 6
Images: 1
Server Version: 1.9.0-dev
Storage Driver: windowsfilter
 Windows:
Execution Driver: Windows 1854 1.9.0-dev a2e5bbe
Logging Driver: json-file
Kernel Version: 10.0 10514 (10514.0.amd64fre.th2_release.150808-1529)
Operating System: Windows Server 2016 Technical Preview 3
CPUs: 4
Total Memory: 8 GiB
Name: WIN-UL4EQUVRNND
ID: ILKR:O4BI:BRKA:IVRX:WBNJ:Q5ME:LV4W:XMQ7:ORW2:IWX4:QHPP:DISK
Debug mode (server): true
 File Descriptors: -1
 Goroutines: 14
 System Time: 2015-10-23T14:47:57.711319-07:00
 EventsListeners: 0
 Init SHA1:
 Init Path: C:\Windows\System32\docker.exe
 Docker Root Dir: C:\ProgramData\docker

PS C:\> [Environment]::OSVersion
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.10514.0 Microsoft Windows NT 10.0.10514.0

PS C:\> (Get-WmiObject -class Win32_OperatingSystem).Caption
Microsoft Windows Server 2016 Technical Preview 3

```

# Environment details (AWS, VirtualBox, physical, etc.):
windows server TP3 vhd from MSDN

# How reproducible:
always

# Steps to Reproduce:
1. Download and setup a windows server tp3 machine
2. Follow instructions to get docker running: https://msdn.microsoft.com/virtualization/windowscontainers/quick_start/inplace_setup?f=255&MSPPError=-2147217396
Instruction above use an old docker version. Build a new version and switch it with the old one.
3. Try to run run --net, example:
```
PS C:\> docker run -t -i --net=host windowsservercore cmd
Error response from daemon: invalid --net: host
```

# Additional info:
I found the problem while trying to use gitlab's CI system. I filled the bug before on their, system and after debugging a bit it seems like the bug is in docker. Discussion here: https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/243

**Comment by thaJeztah** [comment]
Thanks for reporting, it looks like this one is slightly different from https://github.com/docker/docker/issues/14615, because that issue was when using a windows client and a Linux daemon

/cc @jhowardmsft

**Comment by jhowardmsft** [comment]
This is totally expected :) Windows does not (yet) anywhere the networking capability that Linux docker does. Windows only supports --net-default or --net=none. This is the same for both TP3 and the soon to be available TP4.

**Comment by thaJeztah** [comment]
Thanks @jhowardmsft, I removed the "bug" label. We may want to improve the documentation about that so that people are better aware what is and is not supported (yet) on windows. 

I'll close this issue, because https://github.com/docker/docker/issues/15597 is still in place to improve the documentation.

Thanks for reporting @tiagomacarios !

**Comment by tiagomacarios** [comment]
@jhowardmsft @thaJeztah Thanks for replying so quickly. Is there anyway outsiders can help with the documentation issue? I guess it is a bit tricky since we don't know everything that's going on, but if there is a way to help.

**Comment by jhowardmsft** [comment]
All the docker documentation is in the public repo :) @scooley who was looking at the docs issue with @moxiegirl

**Comment by thaJeztah** [comment]
Correct, all the documentation (for the docker "engine") can be found here; https://github.com/docker/docker/tree/master/docs. There's also a basic README explaining how it's used, but more in-depth documentation on how to contribute and make changes to docs can be found in our contributing guide; https://docs.docker.com/project/make-a-contribution/

The Windows documentation is a bit of an exception, because we're still working out how it's best to document those, without duplicating all the existing documentation for Linux.
