### ISSUE TITLE
Docker Daemon configuration

### ISSUE THREAD

**Issue by jas99** [docker/docker#17336]
Hey
Can I configure docker daemon to always forward certain devices automatically by default without usage of --device flag in run cmd.

I want to basically always forward gpu devices to all containers in ec2 gpu instance. 
Thx

**Comment by coolljt0725** [comment]
@jas99  I think there is no way to do this, you have to add `--device` flag in run cmd per container

**Comment by jas99** [comment]
@coolljt0725 It will be nice to have though.

**Comment by thaJeztah** [comment]
I don't think this is something we'd add as a daemon option, as it's really something specific to a container. Perhaps other maintainers think differently on this.

**Comment by jas99** [comment]
@thaJeztah If I start gpu instance I want all containers on that host to have gpu capability. ECS service from AWS as of now didn't exposed device forwarding. My query emerged from that. Maybe creating container wise default settings for all options might be something that is use of to docker users.

Thx
