### ISSUE TITLE
Installation on OSX Yosemite 10.10.2 Issue

### ISSUE THREAD

**Issue by vasu-d** [docker/docker#17337]
Please find the details:

~ $ docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 18:01:15 UTC 2015
 OS/Arch:      darwin/amd64

Virtual box version: Version 5.0.8 r103449

when starting through Kinematics UI getting the following:

/Applications/Docker/Kitematic (Beta).app/Contents/Resources/resources/docker-machine -D create -d virtualbox --virtualbox-memory 2048 default returned non zero exit code. Stderr: Converting from raw image file="stdin" to file="/Users/<redacted>/.docker/machine/machines/default/disk.vmdk"... Creating dynamic image with size 20971520000 bytes (20000MB)... Error creating machine: Maximum number of retries (5) exceeded You will want to check the provider to make sure the machine and associated resources were properly removed.

When launching through docker quickstart terminal getting the following:
Machine default already exists in VirtualBox.
Starting machine default...
Starting VM...
exit status 255
docker is configured to use the default machine with IP 
For help getting started, check out the docs at https://docs.docker.com
Unexpected error getting machine url: exit status 255

Tried to delte the default vm in virtual box and kick quickstart terminal, but the same issue is recurrent.

please help.

**Comment by vasu-d** [comment]
Please find the details:

~ $ docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 18:01:15 UTC 2015
 OS/Arch:      darwin/amd64
Get http:///var/run/docker.sock/v1.20/version: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?

~ $ docker info
Get http:///var/run/docker.sock/v1.20/info: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?

Darwin xxx-MacBook-Pro.local 14.1.1 Darwin Kernel Version 14.1.1: Fri Feb  6 21:06:10 PST 2015; root:xnu-2782.15.4~1/RELEASE_X86_64 x86_64

Virtual box version: Version 5.0.8 r103449

when starting through Kinematics UI getting the following:

/Applications/Docker/Kitematic (Beta).app/Contents/Resources/resources/docker-machine -D create -d virtualbox --virtualbox-memory 2048 default returned non zero exit code. Stderr: Converting from raw image file="stdin" to file="/Users//.docker/machine/machines/default/disk.vmdk"... Creating dynamic image with size 20971520000 bytes (20000MB)... Error creating machine: Maximum number of retries (5) exceeded You will want to check the provider to make sure the machine and associated resources were properly removed.

When launching through docker quickstart terminal getting the following:
Machine default already exists in VirtualBox.
Starting machine default...
Starting VM...
exit status 255
docker is configured to use the default machine with IP 
For help getting started, check out the docs at https://docs.docker.com
Unexpected error getting machine url: exit status 255

Tried to delte the default vm in virtual box and kick quickstart terminal, but the same issue is recurrent.

**Comment by fntlnz** [comment]
Since this is a problem about creating the virtual machine which runs the docker daemon I would suggest you to open this issue on the [docker/machine](https://github.com/docker/machine) repo.
On both, machine and kitematic repositories there are a few issues related to this like: [#1080](https://github.com/kitematic/kitematic/issues/1080), [#1632](https://github.com/docker/machine/issues/1632), [#1712](https://github.com/docker/machine/issues/1712)

**Comment by thaJeztah** [comment]
Thanks for reporting @vasu-d, and thanks for looking up the related issues @fntlnz!

Let's close this one, and continue the discussion on the issues @fntlnz mentioned, otherwise the discussion is spread over multiple repositories; it's better to keep them in a single location
