### ISSUE TITLE
docker cp on OS X 10.11 fails to copy contents of directories recursively

### ISSUE THREAD

**Issue by mmatiaschek** [docker/docker#17346]
i get a "permission denied" error when copying contents of subdirectories...

mmatiaschek@Markus-MBP ~/Work> docker exec d8 ls -al /var/www/html/sites/default
total 76
dr-xr-xr-x  3 www-data www-data  4096 Oct 25 10:04 .
drwxr-xr-x  5 www-data www-data  4096 Oct 25 10:11 ..
-rw-r--r--  1 www-data www-data  5997 Oct 21 22:51 default.services.yml
-rw-r--r--  1 www-data www-data 28086 Oct 21 22:51 default.settings.php
drwxrwxr-x 10 www-data www-data  4096 Oct 25 10:09 files
-r--r--r--  1 www-data www-data 28609 Oct 25 10:06 settings.php

mmatiaschek@Markus-MBP ~/Work> rm -rf 8/*

mmatiaschek@Markus-MBP ~/Work> docker cp d8:/var/www/html/sites/ 8/
open /Users/mmatiaschek/Work/8/sites/default/default.services.yml: permission denied

mmatiaschek@Markus-MBP ~/Work> ls -al 8/sites/default/
total 0
dr-xr-xr-x  2 mmatiaschek  staff   68 25 Okt 11:04 .
drwxr-xr-x  4 mmatiaschek  staff  136 25 Okt 12:05 ..
mmatiaschek@Markus-MBP ~/Work> ls -al 8/sites/
total 8
drwxr-xr-x  4 mmatiaschek  staff  136 25 Okt 12:05 .
drwxr-xr-x  3 mmatiaschek  staff  102 25 Okt 12:05 ..
-rw-r--r--  1 mmatiaschek  staff  515 22 Okt 00:51 README.txt
dr-xr-xr-x  2 mmatiaschek  staff   68 25 Okt 11:04 default

mmatiaschek@Markus-MBP ~/Work> docker --version
Docker version 1.8.2, build 0a8c2e3

**Comment by LK4D4** [comment]
I'm closing this as it's impossible to get anything without particular versions.
