### ISSUE TITLE
docker inspect container only reports last assigned IP

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#17352]
The container info should return `NetworkSettings` as an array --- one for each network the container belongs to.  Right now, `NetworkSettings` appears to be only holding the last assigned values.  For example, I created a container it appears on the default bridge with an ip of : 172.17.0.2.  After attaching the container to a second network, only the IPAddress for the second network is visible to inspection.

**Comment by coolljt0725** [comment]
I found this issues too. It only return the last `docker network connect` networking settings even if you have `docker network disconnect` the last network.
