### ISSUE TITLE
Support dhcp in the host network for container

### ISSUE THREAD

**Issue by duffqiu** [docker/docker#17353]
I want to use the dhcp in the host network for container.

But right now, I have to create the container with --net=none and then do it manually something like pipe did.

Hope docker engine can support it with some flag e.g., --dhcp=external

**Comment by mavenugo** [comment]
@duffqiu have you looked at the upcoming 1.9 Pluggable IPAM feature, which lets you manage container ip allocation using your favorite IPAM plugin : https://github.com/docker/libnetwork/blob/master/docs/ipam.md. One can implement a DHCP plugin using this feature (I think there is already a community effort underway). Although the IPAM plugin is not applicable for host network, with the pluggable network and IPAM drivers, you have full control over both the forwarding and IP Address assignment for the containers. Hence you wouldn't have to rely on host networking.

**Comment by thaJeztah** [comment]
@duffqiu I'm going to close this issue, because the IPAM plugins in Docker 1.9 will allow you to implement this, but feel free to comment here after I've closed

**Comment by deitch** [comment]
@mavenugo two questions:

1. Do you know where the community dhcp effort is coordinated? Is it a github repo, or a discussion somewhere?
2. I have been reading the libnetwork model, and cannot figure out how DHCP renew would work. I get that on creating an endpoint, a dhcp plugin would receive the request for an IP, deal with DHCP, and assign the address... which has a lease life. When the address expires in 2 hours or 2 days, how would a reactive plugin (it only responds to requests from libnetwork) renew the lease? The plugin could know that it needs to renew, but has no way to tell docker that it must, while the ip link certainly does, but it is inside the container.

**Comment by aboch** [comment]
@deitch 

I think your DHCP plugin should be in charge of sending the lease renewal messages to the DHCP server.

Then, when the endpoint is being deleted, libnetwork will send the DHCP plugin the `ReleaseAddress()` request. From this point on the DHCP plugin knows it has to stop asking for renewal.

**Comment by deitch** [comment]
@aboch I have no issue with that in principle, but as I understood the libnetwork remote API, libnetwork calls the plugin, and the plugin responds. The plugin has no way that I can find to initiate a connection to docker or the sandbox/endpoint to say "renew".

Or are you saying that the sandbox should be ignorant? It just has an endpoint with an IP, and as long as it wasn't stopped, the container blithely continues with the same IP, and the plugin continues to renew until it receives a container stopped notification?

That would make more sense, but then how would we handle a failure to renew? DHCP servers have the right to refuse a renewal, and thus force a change in IP.

**Comment by aboch** [comment]
@deitch Yes, I meant the second option you said,  where the sandbox from its point of view it is assigned a static IP.

Agree that with this model it will not be possible to handle a renew failure. 

For that, just thinking, we could have libnetwork regularly poll the ipam plugin to get to know if the lease is still successful. Polling would happen only for ipam plugin which specify that in the capability during registration.

**Comment by deitch** [comment]
When it comes down to it, even if you do traditional DHCP using dhclient or udhcpc on a traditional Linux OS, isn't it just a process assigning addresses to a clueless interface? Does the interface even know that the address has a lifetime?

I think you are raising the issue that the libnetwork knows to contact a network/IPAM driver when a container is created and destroyed, but it needs mechanisms for other non-container driven events.

I am going to open an issue for libnetwork. My recommendation would be to enable network/IPAM to tell libnetwork, when returning an address, "check back with me in x seconds/minutes".

**Comment by deitch** [comment]
https://github.com/docker/libnetwork/issues/843

**Comment by aboch** [comment]
Thanks @deitch for opening the issue in libnetwork. We'll discuss over there.
