### ISSUE TITLE
v1.9.0-RC2 - FreeBSD jenkins build failure

### ISSUE THREAD

**Issue by kalw** [docker/docker#17369]
Hi there,

Any chances that someone take a look at the FreeBSD jenkins job that fails since 14 days ? =)
Not an expert in this field but seems that it is only a workspace issue :

https://jenkins.dockerproject.org/job/Docker%20Master%20(freebsd)/1555/console 

```
Caused by: hudson.plugins.git.GitException: Command "git -c core.askpass=true fetch --tags --progress https://github.com/docker/docker.git +refs/heads/*:refs/remotes/origin/*" returned status code 1:
stdout: 
stderr: remote: Counting objects: 8, done.        
remote: Total 8 (delta 5), reused 5 (delta 5), pack-reused 2        
From https://github.com/docker/docker
   75128c4..9328fc7  master     -> origin/master
error: Cannot lock ref 'refs/remotes/origin/release/1.8': 'refs/remotes/origin/release' exists; cannot create 'refs/remotes/origin/release/1.8'
 ! [new branch]      release/1.8 -> origin/release/1.8  (unable to update local ref)
error: Cannot lock ref 'refs/remotes/origin/release/v1.9': 'refs/remotes/origin/release' exists; cannot create 'refs/remotes/origin/release/v1.9'
 ! [new branch]      release/v1.9 -> origin/release/v1.9  (unable to update local ref)
error: some local refs could not be updated; try running
 'git remote prune https://github.com/docker/docker.git' to remove any old, conflicting branches
```

**Comment by thaJeztah** [comment]
Thanks for reporting! I'll try to get someone to have a look

**Comment by thaJeztah** [comment]
ping @kvasdopil we may need your help here :heart:

**Comment by kvasdopil** [comment]
@thaJeztah hi, i'll take a look asap, thx for ping

**Comment by thaJeztah** [comment]
Thanks @kvasdopil !

**Comment by kvasdopil** [comment]
The error doesn't seem to be related to freebsd build, looks like some kind of repository misconfiguration, maybe @jfrazelle could take a look.
However freebsd build is also broken, i'll try to fix it.

**Comment by sakal** [comment]
FreeBSD build faild on git fetch in jenkins:

 > git -c core.askpass=true fetch --tags --progress https://github.com/docker/docker.git +refs/heads/*:refs/remotes/origin/*
ERROR: Error fetching remote repo 'origin'

It's looks like simple or it not important?
Anyway thank you for your great job!

**Comment by LK4D4** [comment]
Freebsd machine is stopped for 4 months and also there is no active work on it. I'm closing this issue for now. Feel free to post new.
