### ISSUE TITLE
Add --all support to Docker rm command to allow remove all containers in one simple step

### ISSUE THREAD

**Issue by LiYMS** [docker/docker#17372]
Sometimes we found we have to do clumsy steps to remove all the containers from the host. It would great if we can add an option --all to Docker rm command to allow user to handle that kind of request gracefully.

Thx.

**Comment by cpuguy83** [comment]
`docker rm -f $(docker ps -aq)`?

**Comment by thaJeztah** [comment]
yes, I agree with @cpuguy83 here. To be clear; I understand `--all` can be more convenient, but we try not to overload the docker commands with flags/options unless really necessary. It's easy to create an alias for this in your shell, if you need to do this frequently

Also, see this issue for earlier discussions https://github.com/docker/docker/issues/928
