### ISSUE TITLE
logs is buffered in docker 1.9.0

### ISSUE THREAD

**Issue by e-max** [docker/docker#17398]
It seems that in docker 1.9.0-rc2 logs from containers appears in logfile after some delay.

I've create simple docker image which just print current unixtime every second.

When I started it with -i -t flags everything worked perfectly

```
# docker run --rm -i -t registry.test.ivi.ru/zzz
1445941111.02
1445941112.03
1445941113.03
```

But with -d flag docker apparently started buffering logs

```
# docker run -d --name=test2 zzz
# docker logs test2
# 
```

json file is also empty
```
# docker inspect test2 | grep LogPath
    "LogPath": "/var/lib/docker/containers/2176619a3b325a5e6aa75ed803a29d351faced2a8d88a83c1e607bcae6573e45/2176619a3b325a5e6aa75ed803a29d351faced2a8d88a83c1e607bcae6573e45-json.log"

# cat /var/lib/docker/containers/2176619a3b325a5e6aa75ed803a29d351faced2a8d88a83c1e607bcae6573e45/2176619a3b325a5e6aa75ed803a29d351faced2a8d88a83c1e607bcae6573e45-json.log
#
```

Аfter couple minutes logs appeared in the file, but if we take a look at it :
```
{"log":"1445940817.09\n","stream":"stdout","time":"2015-10-27T10:18:31.471372769Z"}
{"log":"1445940818.09\n","stream":"stdout","time":"2015-10-27T10:18:31.471530826Z"}
{"log":"1445940819.09\n","stream":"stdout","time":"2015-10-27T10:18:31.47155176Z"}
{"log":"1445940820.1\n","stream":"stdout","time":"2015-10-27T10:18:31.471565509Z"}

```

we can notice that every "time" field contains the same time.

**Comment by thaJeztah** [comment]
ping @LK4D4 @unclejack perhaps one of you can have a look?

**Comment by thaJeztah** [comment]
Thanks for testing the release candidates @e-max <3

I'm tentatively adding this to the milestone, just so we don't loose sight

**Comment by phemmer** [comment]
@e-max how are you generating these log entries?
This sounds like the classic case of a programming language which buffers when it detects STDOUT is not a TTY (ruby, perl, python, and others do this)

**Comment by e-max** [comment]
I am sorry, it was absolutely stupid mistake.  Thanks!
