### ISSUE TITLE
Docker Not able to start 

### ISSUE THREAD

**Issue by gjprabu** [docker/docker#17399]
Hi All,

We are using docker with Centos Linux kernel 3.18.16 and its working properly. Due to hardware incompatibility issue we have downgraded the kernel version to 3.10.79 after that docker not able to start and it says below error.

"Shutting down daemon due to errors: error initializing graphdriver: Error running DeviceCreate (CreatePool) dm_task_run failed"

I have tried by removing /var/lib/docker but still not working.

This is our configuration 

docker --version
Docker version 1.6.2, build ba1f6c3/1.6.2

cat /etc/sysconfig/docker
OPTIONS='--selinux-enabled --insecure-registry ztest.xyz.com:5000 -H tcp://0.0.0.0:4243 --api-enable-cors=true -H unix:///var/run/docker.sock'
DOCKER_CERT_PATH=/etc/docker

cat /etc/sysconfig/docker-storage 
DOCKER_STORAGE_OPTIONS="--storage-opt dm.loopmetadatasize=16G --storage-opt dm.loopdatasize=800G --storage-opt dm.basesize=50G --storage-opt dm.no_warn_on_loop_devices=true"

Kindly check and give us the solution asap.

**Comment by gjprabu** [comment]
Hi All,

Please find the details.

docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): ba1f6c3/1.6.2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): ba1f6c3/1.6.2
OS/Arch (server): linux/amd64

Not running state docker info
FATA[0000] Get http:///var/run/docker.sock/v1.18/info: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?

Previous running state docker info 
Containers: 0
Images: 0
Storage Driver: devicemapper
 Pool Name: docker-8:5-72220844-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 979.9 MB
 Data Space Total: 536.9 GB
 Data Space Available: 535.9 GB
 Metadata Space Used: 3.637 MB
 Metadata Space Total: 17.05 GB
 Metadata Space Available: 17.04 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Kernel Version: 3.10.0-229.14.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 48
Total Memory: 62.71 GiB
Name: integ-hm9
ID: WCZ3:4IXO:MQAN:XNFN:RE37:MC3Y:L6VA:4A3T:HR5L:BBSF:DKEE:2HKF

uname -a
Linux integ-hm9 3.10.91 #2 SMP Tue Oct 27 17:23:35 IST 2015 x86_64 x86_64 x86_64 GNU/Linux

List the steps to reproduce the issue
1. Install kernel 3.18.16  and install docker and run.
2. Now downgrade the kernel to 3.10.91 and now docker not able to start.

# docker -D -d
DEBU[0000] waiting for daemon to initialize             
DEBU[0000] libdevmapper(6): ioctl/libdm-iface.c:1795 (4) dm version   OF   [16384] (*1) 
DEBU[0000] libdevmapper(6): ioctl/libdm-iface.c:1795 (4) dm version   OF   [16384] (*1) 
DEBU[0000] devicemapper: udev sync support: true        
DEBU[0000] Generated prefix: docker-8:5-72220844        
DEBU[0000] Checking for existence of the pool 'docker-8:5-72220844-pool' 
DEBU[0000] libdevmapper(6): ioctl/libdm-iface.c:1795 (4) dm info docker-8:5-72220844-pool  OF   [16384] (*1) 
DEBU[0000] Pool doesn't exist. Creating it.             
DEBU[0000] libdevmapper(6): libdm-common.c:2304 (4) Udev cookie 0xd4de374 (semid 65536) created 
DEBU[0000] libdevmapper(6): libdm-common.c:2324 (4) Udev cookie 0xd4de374 (semid 65536) incremented to 1 
DEBU[0000] libdevmapper(6): libdm-common.c:2196 (4) Udev cookie 0xd4de374 (semid 65536) incremented to 2 
DEBU[0000] libdevmapper(6): libdm-common.c:2446 (4) Udev cookie 0xd4de374 (semid 65536) assigned to CREATE task(0) with flags DISABLE_SUBSYSTEM_RULES DISABLE_DISK_RULES DISABLE_OTHER_RULES         (0xe) 
DEBU[0000] libdevmapper(6): ioctl/libdm-iface.c:1795 (4) dm create docker-8:5-72220844-pool  OF   [16384] (*1) 
DEBU[0000] libdevmapper(6): ioctl/libdm-iface.c:1795 (4) dm reload docker-8:5-72220844-pool  OF   [16384] (*1) 
DEBU[0000] libdevmapper(6): ioctl/libdm-iface.c:1795 (4) dm resume docker-8:5-72220844-pool  OF   [16384] (*1) 
DEBU[0000] libdevmapper(3): ioctl/libdm-iface.c:1813 (-1) device-mapper: resume ioctl on docker-8:5-72220844-pool failed: Invalid argument 
DEBU[0000] libdevmapper(6): libdm-common.c:2231 (4) Udev cookie 0xd4de374 (semid 65536) decremented to 1 
DEBU[0000] libdevmapper(6): libdm-common.c:2196 (4) Udev cookie 0xd4de374 (semid 65536) incremented to 2 
DEBU[0000] libdevmapper(6): libdm-common.c:2446 (4) Udev cookie 0xd4de374 (semid 65536) assigned to REMOVE task(2) with flags DISABLE_SUBSYSTEM_RULES DISABLE_DISK_RULES DISABLE_OTHER_RULES         (0xe) 
DEBU[0000] libdevmapper(6): ioctl/libdm-iface.c:1795 (4) dm remove docker-8:5-72220844-pool  OF   [16384] (*1) 
DEBU[0000] libdevmapper(6): libdm-common.c:1396 (4) docker-8:5-72220844-pool: Stacking NODE_DEL [verify_udev] 
DEBU[0000] libdevmapper(6): libdm-common.c:2231 (4) Udev cookie 0xd4de374 (semid 65536) decremented to 1 
DEBU[0000] libdevmapper(6): libdm-common.c:2496 (4) Udev cookie 0xd4de374 (semid 65536) waiting for zero 
DEBU[0000] libdevmapper(6): libdm-common.c:2246 (4) Udev cookie 0xd4de374 (semid 65536) destroyed 
DEBU[0000] libdevmapper(6): libdm-common.c:1396 (4) docker-8:5-72220844-pool: Processing NODE_DEL [verify_udev] 
INFO[0000] +job serveapi(unix:///var/run/docker.sock)   
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
DEBU[0000] Registering GET, /containers/{name:.*}/export 
DEBU[0000] Registering GET, /containers/{name:.*}/changes 
DEBU[0000] Registering GET, /exec/{id:.*}/json          
DEBU[0000] Registering GET, /images/{name:.*}/history   
DEBU[0000] Registering GET, /containers/json            
DEBU[0000] Registering GET, /images/{name:.*}/json      
DEBU[0000] Registering GET, /containers/{name:.*}/json  
DEBU[0000] Registering GET, /containers/{name:.*}/top   
DEBU[0000] Registering GET, /containers/{name:.*}/stats 
DEBU[0000] Registering GET, /containers/{name:.*}/attach/ws 
DEBU[0000] Registering GET, /_ping                      
DEBU[0000] Registering GET, /images/search              
DEBU[0000] Registering GET, /images/get                 
DEBU[0000] Registering GET, /images/{name:.*}/get       
DEBU[0000] Registering GET, /containers/ps              
DEBU[0000] Registering GET, /events                     
DEBU[0000] Registering GET, /images/viz                 
DEBU[0000] Registering GET, /images/json                
DEBU[0000] Registering GET, /containers/{name:.*}/logs  
DEBU[0000] Registering GET, /info                       
DEBU[0000] Registering GET, /version                    
DEBU[0000] Registering POST, /commit                    
DEBU[0000] Registering POST, /images/{name:.*}/tag      
DEBU[0000] Registering POST, /containers/create         
DEBU[0000] Registering POST, /containers/{name:.*}/attach 
DEBU[0000] Registering POST, /containers/{name:.*}/exec 
DEBU[0000] Registering POST, /containers/{name:.*}/rename 
DEBU[0000] Registering POST, /containers/{name:.*}/unpause 
DEBU[0000] Registering POST, /containers/{name:.*}/start 
DEBU[0000] Registering POST, /exec/{name:.*}/start      
DEBU[0000] Registering POST, /exec/{name:.*}/resize     
DEBU[0000] Registering POST, /build                     
DEBU[0000] Registering POST, /images/create             
DEBU[0000] Registering POST, /images/load               
DEBU[0000] Registering POST, /images/{name:.*}/push     
DEBU[0000] Registering POST, /containers/{name:.*}/pause 
DEBU[0000] Registering POST, /containers/{name:.*}/restart 
DEBU[0000] Registering POST, /containers/{name:.*}/stop 
DEBU[0000] Registering POST, /containers/{name:.*}/copy 
DEBU[0000] Registering POST, /auth                      
DEBU[0000] Registering POST, /containers/{name:.*}/kill 
DEBU[0000] Registering POST, /containers/{name:.*}/wait 
DEBU[0000] Registering POST, /containers/{name:.*}/resize 
DEBU[0000] Registering DELETE, /containers/{name:.*}    
DEBU[0000] Registering DELETE, /images/{name:.*}        
DEBU[0000] Registering OPTIONS,                         
DEBU[0000] Warning: could not chgrp /var/run/docker.sock to docker: Group docker not found 
FATA[0000] Shutting down daemon due to errors: error intializing graphdriver: Error running DeviceCreate (CreatePool) dm_task_run failed

**Comment by phemmer** [comment]
given that kernel 3.18.16 is not a supported CentOS kernel, how did you install it? Did you use a public yum repo?
There's a good chance you ended up upgrading the devicemapper libs as well (since they're tightly integrated with the kernel), and they're no longer compatible with your older kernel.

**Comment by gjprabu** [comment]
We have downloaded the kernel from https://www.kernel.org/ and complied manually. If the devicemapper libs are not supported with old kernel, then we have other server centos7 default kernel 3.10.0-229.14.1.el7.x86_64 and which is working fine.

**Comment by gjprabu** [comment]
As we required some file system functionality and need to compile kernel manually to get that filesystem modules. Even though we have upgrade kernel from centos 7 default kernel 3.10.0-229.14.1.el7.x86_64 to 3.10.1 and 3.10.79 but Its throwing same error. 

"Shutting down daemon due to errors: error initializing graphdriver: Error running DeviceCreate (CreatePool) dm_task_run failed"

**Comment by aku163** [comment]
@gjprabu : Can you provide result of `df -h` ?

We had similar issue where / was out of space and was unable to start the daemon and was getting same error.

**Comment by gjprabu** [comment]
Hi aku,

    Please find the details.
df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2       289G   30G  244G  11% /
devtmpfs         32G     0   32G   0% /dev
tmpfs            32G   12K   32G   1% /dev/shm
tmpfs            32G  9.1M   32G   1% /run
tmpfs            32G     0   32G   0% /sys/fs/cgroup
/dev/sda1       9.5G  396M  8.6G   5% /boot
/dev/sdb1       917G  217G  654G  25% /home
/dev/sda5       1.5T  643G  726G  47% /var
/dev/sdb2       1.5T  460G  978G  32% /data
/dev/rbd1       9.6T  1.5T  8.1T  16% /data/build/downloads

**Comment by gjprabu** [comment]
We found the issue, when we change the option in /etc/sysconfig/docker-storage to default value its working fine. When we set below storage option in kernel 3.10.91 docker not able to start. Please share the solution with below options.

DOCKER_STORAGE_OPTIONS="--storage-opt dm.loopmetadatasize=16G --storage-opt dm.loopdatasize=500G --storage-opt dm.basesize=50G --storage-opt dm.no_warn_on_loop_devices=true"

**Comment by gjprabu** [comment]
Now problem with only dm.loopmetadatasize=16G, it is not allowing me in storage option. If we remove that setting docker able to start and its working. Our setup will required more image and metadata size. Please advice me to change the size of metadata.

**Comment by cpuguy83** [comment]
@gjprabu I believe you need to remove the existing device in order to change the size.

**Comment by thaJeztah** [comment]
IIRC this blog post described the process, but I'm not too familiar with this; https://jpetazzo.github.io/2014/01/29/docker-device-mapper-resize/

**Comment by LK4D4** [comment]
Looks resolved.
