### ISSUE TITLE
adding interface veth684aea0 to bridge docker0 failed

### ISSUE THREAD

**Issue by bergtwvd** [docker/docker#17392]
Running in AWS Docker version 1.7.1, build 786b29d/1.7.1.

I intermittently get the following error (typically when starting containers with docker-compose):

Cannot start container 0faa3b09e35fdf6fb1954a2a3589bc74feb02448be5db0773d8e0623813764f6: adding interface veth684aea0 to bridge docker0 failed: could not find bridge docker0: no such network interface

It differs each time when and were it occurs.
Then I wait a while and try again, after which I can start containers.

Docker-compose file:
[ec2-user@docker-0A ~]$ more vesselsim.yml
air:
 links:
 - crc:crc
 image: msaas/pi-aircraft
 command: -F TheWorld -f Airraft -c crc

shipsim:
 links:
 - crc:crc
 image: msaas/shipsim
 command: -F TheWorld -f Ship -c crc

trafficsimdata:
 image: msaas/shipsimdata

trafficsim:
 links:
 - crc:crc
 volumes_from:
 - trafficsimdata
 image: msaas/shipsim
 command: -F TheWorld -f VesselGen -c crc -background /tmp/shipsim/paths/backgro
und.json

crc:
 image: msaas/pi-crc:5.0.1.0L
 mac_address: 00:18:8B:0D:4F:0B
 container_name: crc
 ports:
 - "8989:8989"

web:
 image: msaas/pi-web:2.1.0
 container_name: web
 ports:
 - "8080:8080"

ge:
 links:
 - crc:crc
 image: msaas/pi-ge:1.4.1L
 mac_address: 74:86:7A:6E:94:FA
 container_name: ge
 command: -F TheWorld -f Google -g 54.229.213.215 -t 10 -c crc
 ports:
 - "8765:8765"

[ec2-user@docker-0A ~]$ docker info
Containers: 8
Images: 91
Storage Driver: devicemapper
 Pool Name: docker-202:1-263700-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.566 GB
 Data Space Total: 107.4 GB
 Data Space Available: 12.89 GB
 Metadata Space Used: 4.792 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.143 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.7-15.23.amzn1.x86_64
Operating System: Amazon Linux AMI 2015.09
CPUs: 2
Total Memory: 7.8 GiB
Name: docker-0A
ID: T3ZF:H34C:UYTJ:PBR6:A53X:QQKV:OJOL:T2OY:RYJ5:WSWD:LMIL:RYER
Username: bergtwvd
Registry: https://index.docker.io/v1/
[ec2-user@docker-0A ~]$

[ec2-user@docker-0A ~]$ uname -a
Linux docker-0A 4.1.7-15.23.amzn1.x86_64 #1 SMP Mon Sep 14 23:20:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mrjana** [comment]
@bergtwvd This is fixed in 1.8.2. Please upgrade to 1.8.2

**Comment by bergtwvd** [comment]
How do I do this on AWS/centos7 ?
Seems that in AWS I am stuck with an older version.
Tom

Sent from my Android phone using Symantec TouchDown (www.symantec.com)

-----Original Message-----

**Comment by thaJeztah** [comment]
I think there's work on that being done in https://github.com/docker/docker/pull/17283, but I suggest asking for support at Amazon.

I'm going to close this issue, because the issue in docker itself has been fixed. Feel free to comment here after I've closed the issue. Thanks for reporting!
