### ISSUE TITLE
Misspelling in image management breaks link

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#17407]
This page has a broken link https://docs.docker.com/userguide/image_management/ - links to https://docs.docker.com/dockter-trusted-registry but should https://docs.docker.com/docker-trusted-registry

**Comment by tophj-ibm** [comment]
Looks like it was already fixed a month ago, and the website hasn't updated.

3e6991f35c6b98f3503cc81f166420645e7d3c9e

**Comment by moxiegirl** [comment]
Hey thanks for checking it out.  That helped!
