### ISSUE TITLE
UX: docker network inspect should include container names

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#17404]
The `docker network inspect` output only contains container-ID's. Given that service discovery is based on container names, it's odd that the container-names / service-names are not included in the output.

**Comment by coolljt0725** [comment]
I think if we use containers names here, we should update on `docker rename`

**Comment by thaJeztah** [comment]
@coolljt0725 yes, that would be needed; libnetwork does already update `/etc/hosts` entries on container-rename, so this should follow as well.

**Comment by WeiZhang555** [comment]
Your suggestion looks reasonable and I'm +1 on this. 
After a quick look in the code, I think it  needs not much change for solving this, so I made a quick implementation and already pushed a PR, hope that's helpful. :smile: 
@thaJeztah

**Comment by thaJeztah** [comment]
Thanks @WeiZhang555 !
