### ISSUE TITLE
When a volume plugin fails to create a volume while creating a container, the container should not be created

### ISSUE THREAD

**Issue by lukemarsden** [docker/docker#17415]
Currently when a volume plugin fails (response `Err` != `null`) to create a volume at container create time with `docker run -v foo:/bar --volume-driver=baz` (perhaps, because the referenced volume does not exist) the container being created still gets created, but without the referenced mount. This is confusing behaviour, because if the created container then gets started (e.g. by a future run of `docker-compose`, which will start containers which already exist), instead of the volume-driver volume, the container ends up with a local volume, which is not what the user asked for.

Ping @calavera @cpuguy83 - WDYT?

**Comment by lukemarsden** [comment]
```
$ docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64
$ docker info
Containers: 541
Images: 148
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1230
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-48-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 1.954 GiB
Name: ip-10-0-0-59
ID: FAGW:D4A2:UBI3:2GW6:XGCC:LMWX:5G5W:N2VS:ODD7:CR2G:TOGH:2QZC
WARNING: No swap limit support
$ uname -a
Linux ip-10-0-0-59 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by thaJeztah** [comment]
Thanks for reporting, @lukemarsden, I agree this is confusing

**Comment by lukemarsden** [comment]
Thanks! I suggest that failing to create a volume should fail the creation of the entire container. This may need to roll back other volume (or other object) creation.

**Comment by robhaswell** [comment]
Definitely the failure to provision a volume should be a catastrophic failure. This falls under repeatability, and, safety.

**Comment by cpuguy83** [comment]
Based on the code I would expect it to clean up the container on error, so maybe something's not working as expected.

**Comment by robhaswell** [comment]
I can confirm that the container is being created but not started in Docker 1.8.2.

**Comment by thaJeztah** [comment]
@lukemarsden @robhaswell one of you interested in creating a PR for this?

**Comment by Skarlso** [comment]
I'm curious @cpuguy83 why do you think so? Could you please share which code would do that? 

I'm not asking sarcastically. :) 

I'm trying to learn this stuff, to help and contribute. If I see this correctly, it does return errors here.

You mean this guy, for example => 

```go
func (daemon *Daemon) VolumeCreate(name, driverName string, opts map[string]string) (*types.Volume, error) {
```

But I couldn't find where a teardown or a failure of a container creation would happen if mounting a volume would fail. 

Thanks!

**Comment by calavera** [comment]
I'm pretty sure this is fixed on master. At least my initial tests seem to say so:

```
➜  bundles/1.9.0-dev/binary/docker run -v foo:/bar --volume-driver=baz --name shouldnotbethere alpine ls /
Error response from daemon: Error looking up volume plugin baz: Plugin not found
➜ bundles/1.9.0-dev/binary/docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
➜  bundles/1.9.0-dev/binary/docker ps -a --format '{{ .ID }}: {{ .Names }}'
cfb80b95e652: test
ba360f875ca6: pensive_elion
c1524587b202: high_dijkstra
caa498da4175: goofy_visvesvaraya
48dbe4282ac7: modest_panini
53942f4086fc: gigantic_curie
e3d1a71ca520: reverent_brahmagupta
fe290c6306e4: pensive_spence
f22b870e147a: sad_payne
609509796a99: condescending_mahavira
d3151fb3bb88: berserk_ptolemy
```

**Comment by lukemarsden** [comment]
Thanks! I wonder if a volume driver which fails to create volumes might trigger a different codepath to a missing volume driver? Anyhow, I'll test on an 1.9.0 rc ASAP, thanks!
