### ISSUE TITLE
Docker 1.8.3: Chown not working

### ISSUE THREAD

**Issue by muuki88** [docker/docker#17416]
The following `Dockerfile` works with 

```
Docker version 1.7.1, build 786b29d
```

but not with a current `Docker version 1.8.3`

On `docker run` the start script isn't able to find the jars under `/opt`, because they have the wrong access rights. If we set the `DAEMON` user to `root`, everything works.

### Dockerfile

```
FROM lwieske/java-8:jre-8u60
MAINTAINER Nepomuk Seiler
WORKDIR /opt/docker
ADD opt /opt
RUN ["chown", "-R", "daemon:daemon", "."]
EXPOSE 9000
USER daemon
ENTRYPOINT ["bin/akka-http-elasticsearch"]
CMD []
```

cc @hseeberger

**Comment by thaJeztah** [comment]
Can you add the output of `docker version`, `docker info` and `uname -a`? Chowning issues can be dependent on the graph driver and underlying filesystem

**Comment by phemmer** [comment]
Your workdir is `/opt/docker`. Your chown is `chown -R daemon:daemon .`. Thus you're chowning `/opt/docker`, yet your add is to `/opt`.
Change your chown to `/opt` and you should be good.

**Comment by LK4D4** [comment]
Looks like resolved.
