### ISSUE TITLE
Docker 1.8.3 Error Starting Daemon

### ISSUE THREAD

**Issue by hiraq** [docker/docker#17426]
Hi,

My current server environment : 

- kernel : Linux my-server 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

- docker version : 
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:37:18 UTC 2015
 OS/Arch:      linux/amd64

I've follow the official instructions from here : https://docs.docker.com/installation/ubuntulinux/ , including Create docker group

And when i run the daemon:

```
INFO[0000] [graphdriver] using prior storage driver "aufs" 
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
FATA[0000] Error starting daemon: Couldn't create Tag store repositories-aufs: EOF
```

I've installed kernel : `linux-image-generic-lts-trusty` but still not works.

Then i've tried setup on vagrant using same version OS : Ubuntu 14.04.3 but with different kernel :

```
Linux vagrant 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

And everything is fine.  What happened with daemon inside my server environment ? (using kernel 3.13)

**Comment by lagilaper** [comment]
@hiraq @GordonTheTurtle 
This issue can be closed. We solved this by deleting `repositories-aufs` file. After docker service restarted, it re-create the file again. The downside is we need to rebuild our images or re-download from docker hub.

The cause of this issue might be corrupted `repositories-aufs` when our disk was full (reach 99.9%).
