### ISSUE TITLE
panic: runtime error: makeslice: len out of range using docker-machine on windows 10 64b

### ISSUE THREAD

**Issue by stefanleh** [docker/docker#17430]
stefan@Monster MINGW64 ~/centos-jenkins-docker-slave (master)
	$ winpty docker run -it 61138c91bd2a
	panic: runtime error: makeslice: len out of range
	
	goroutine 1 [running]:
	github.com/docker/docker/pkg/term/winconsole.WinConsoleStreams(0xed3fb0, 0xc0820069b0, 0x0, 0x0, 0x0, 0x0)
	        /go/src/github.com/docker/docker/pkg/term/winconsole/console_windows.go:252 +0x50f
	github.com/docker/docker/pkg/term.StdStreams(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	        /go/src/github.com/docker/docker/pkg/term/term_windows.go:33 +0x220
	main.main()
	        /go/src/github.com/docker/docker/docker/docker.go:24 +0x47
	
	goroutine 2 [runnable]:
	runtime.forcegchelper()
	        /usr/local/go/src/runtime/proc.go:90
	runtime.goexit()
	        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
	
	goroutine 3 [runnable]:
	runtime.bgsweep()
	        /usr/local/go/src/runtime/mgc0.go:82
	runtime.goexit()
	        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
	
	goroutine 4 [runnable]:
	runtime.runfinq()
	        /usr/local/go/src/runtime/malloc.go:712
	runtime.goexit()
	        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
	
	goroutine 5 [runnable]:
	os/signal.loop()
	        /usr/local/go/src/os/signal/signal_unix.go:19
	created by os/signal.init┬À1
	        /usr/local/go/src/os/signal/signal_unix.go:27 +0x3c

**Comment by thaJeztah** [comment]
@stefanleh curious why you closed this one. If this is still an issue, can you add the requested information? thanks!

**Comment by stefanleh** [comment]
**$ docker version**

Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 18:01:15 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 18:01:15 UTC 2015
 OS/Arch:      linux/amd64

**$ docker info**

Containers: 1
Images: 10
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 12
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.10-boot2docker
Operating System: Boot2Docker 1.8.3 (TCL 6.4); master : af8b089 - Mon Oct 12 18:56:54 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: 6CXJ:AZ6D:XEYS:3CQ4:S2EW:DR5P:LS4H:Z5RO:HKIA:FYUM:GEYS:JJHV
Debug mode (server): true
File Descriptors: 16
Goroutines: 35
System Time: 2015-10-28T14:38:35.086919988Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

**$ uname -a**

MINGW64_NT-10.0 Monster 2.1.0(0.288/5/3) 2015-06-28 18:57 x86_64 Msys

**environment**

docker toolbox for windows / mingw64

**steps to reproduce**

1. install docker toolbox on windows
2. git clone https://github.com/stefanleh/centos-jenkins-docker-slave.git
3. cd centos-jenkins-docker-slave
4. docker build .
5. winpty docker run -it IMAGEID bash

**the result**

	stefan@Monster MINGW64 ~/centos-jenkins-docker-slave (master)
	$ winpty docker run -it 61138c91bd2a
	panic: runtime error: makeslice: len out of range
	
	goroutine 1 [running]:
	github.com/docker/docker/pkg/term/winconsole.WinConsoleStreams(0xed3fb0, 0xc0820069b0, 0x0, 0x0, 0x0, 0x0)
	        /go/src/github.com/docker/docker/pkg/term/winconsole/console_windows.go:252 +0x50f
	github.com/docker/docker/pkg/term.StdStreams(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	        /go/src/github.com/docker/docker/pkg/term/term_windows.go:33 +0x220
	main.main()
	        /go/src/github.com/docker/docker/docker/docker.go:24 +0x47
	
	goroutine 2 [runnable]:
	runtime.forcegchelper()
	        /usr/local/go/src/runtime/proc.go:90
	runtime.goexit()
	        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
	
	goroutine 3 [runnable]:
	runtime.bgsweep()
	        /usr/local/go/src/runtime/mgc0.go:82
	runtime.goexit()
	        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
	
	goroutine 4 [runnable]:
	runtime.runfinq()
	        /usr/local/go/src/runtime/malloc.go:712
	runtime.goexit()
	        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
	
	goroutine 5 [runnable]:
	os/signal.loop()
	        /usr/local/go/src/os/signal/signal_unix.go:19
	created by os/signal.init┬À1
	        /usr/local/go/src/os/signal/signal_unix.go:27 +0x3c

**Comment by ssreekanth** [comment]
+1

**Comment by jhowardmsft** [comment]
Can you try the latest CLI. There have been many fixes to the ansi emulator, this looks like one of the well known ones.

**Comment by stefanleh** [comment]
> Can you try the latest CLI. There have been many fixes to the ansi emulator, this looks like one of the well known ones. 

Do you mean the latest docker toolbox for windows or latest mingw64?

I'm using whats included in DockerToolbox-1.8.3 from https://www.docker.com/docker-toolbox

**Comment by jhowardmsft** [comment]
Latest docker.exe from master.dockerproject.org. I've no idea how toolbox is packaged tho :(

**Comment by stefanleh** [comment]
version coming with toolbox:

	 Version:      1.8.3
	 API version:  1.20
	 Go version:   go1.4.2
	 Git commit:   f4bf5c7
	 Built:        Mon Oct 12 18:01:15 UTC 2015
	 OS/Arch:      windows/amd64

version i've downloaded from master.dockerproject.org:

	 Version:      1.9.0-dev
	 API version:  1.22
	 Go version:   go1.5.1
	 Git commit:   8d56954
	 Built:        Tue Nov  3 16:40:14 UTC 2015
	 OS/Arch:      windows/amd64

response:

	Error response from daemon: client is newer than server (client API version: 1.22, server API version: 1.20)

is there any >1.8.3 version of the client i could use which is still working with api 1.20?

**Comment by jhowardmsft** [comment]
Ugh. I doubt it. You could update the binary in the container host too probably. Use the Linux 64 bit one.

**Comment by thaJeztah** [comment]
Docker Toolbox 1.9 was just made available https://github.com/docker/toolbox/releases/tag/v1.9.0

But non-matching API versions is a pita; there's a PR to solve that here; https://github.com/docker/docker/pull/15964

**Comment by stefanleh** [comment]
Thank you for the information. Version 1.9.0 solves my issue.

**Comment by thaJeztah** [comment]
@stefanleh great! Thanks for reporting back

I'll close this issue, thanks for reporting (and thanks for having a look, @jhowardmsft)

**Comment by Baeke** [comment]
I have the same issue and I also use version 1.9.0. I get the error when I run  docker ps from windows. 
When I do 'docker ps' from unix I get no error ( from windows to unix by:  'docker-machine ssh default' )

Does anyone know 

`Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64
`

**Comment by thaJeztah** [comment]
@Baeke I suggest to try if this is still an issue with the current release (1.10.3, or 1.11.0 which will be released later this week)
