### ISSUE TITLE
Docker website encourages users to import GPG key for apt repository in unsafe ways

### ISSUE THREAD

**Issue by JonasT** [docker/docker#17436]
Docker needlessly encourages users to import the GPG key for the apt repository in unsafe ways without verifying the full fingerprint. TLS has some tampering protection after all, so this should be used to give users the power with the help of the HTTPS-delivered site to do this better and get informed about the supposed fingerprint and how to check it. As far as I'm aware, the **HKP protocol is not tampering-proofed.** (I might be wrong, but that is what a quick google appears to reveal)

Therefore, those are the things that need fixing:

1. Step 3 of https://docs.docker.com/installation/ubuntulinux/ which tells me to add the gpg key absolutely *needs* to mention the correct fingerprint in the text. With the https encryption, there's at least a slight chance I can ensure that I get the correct key even if someone tries a man in the middle when I consult the keyserver.

2. Step 3 of https://docs.docker.com/installation/ubuntulinux/ must use a command that afterwards checks against a fingerprint which is written/baked into that command I am supposed to copy from the site, so that again HTTPS gives the user some basic tampering protection when copying and running the command and getting the key from a keyserver.

3. The script from https://get.docker.com/ needs to have the fingerprint embedded, and it must check the fingerprint after running the apt-key adv import. (needs similar fix as mentioned in the previous point)

The user should basically never run a key import over a protocol that isn't protected against tampering without being instructed to verify the key fingerprint afterwards.

There's probably other places that need fixing/rewriting too, but those are the few I have seen.

PS: I'm not a cryptographer, so if all of this is unnecessary due to some integrated protection mechanism I'm not aware of, feel free to ignore my rambling ;-)

**Comment by thaJeztah** [comment]
ping @tianon I think this has been discussed before, but you're way better than I am at this :smile:

**Comment by cpuguy83** [comment]
http://security.stackexchange.com/a/4175/15496 is a good explaination.

**Comment by tianon** [comment]
If you look at the actual command documented/executed, you'll see that it
embeds the full fingerprint already so the that gpg tool will verify the
key during import as well.  Additionally, if the key is wrong, APT's
default configuration will refuse to install packages from the repo.

- Tianon

**Comment by thaJeztah** [comment]
Thanks for adding the explanation @tianon, @cpuguy83.

I think it's safe (no pun intended) to close this issue, thanks for suggesting though @JonasT, it's appreciated

**Comment by JonasT** [comment]
@cpuguy83 yes it explains why my remark is *completely valid*. Because the argument is "well you can just check the key itself cryptographically, so who cares about the connection", such a check is of even more importance.

@tianon actually, I'm just seeing this: ```apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D``` Is that long id actually equal to a fingerprint? I'm not familiar enough with the protocol to tell. If yes, I guess my remarks are unwarranted.

**Comment by thaJeztah** [comment]
Apologies @JonasT, I'll reopen

**Comment by cpuguy83** [comment]
@JonasT It is explaining that you don't need to trust the key server, you need to trust the signers, which is verified by apt.

**Comment by JonasT** [comment]
@cpuguy83 so apt is actually checking signatures on the key to be issued by a trusted party? Because the command does kinda *not* look like it does:

```
gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.mJ2kJvaGnM --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
```
--trust-model always, --no-auto-check-trustdb? Doesn't sound that safe to me...

**Comment by JonasT** [comment]
I just discussed this with @cpuguy83 in chat, and I think it comes down to whether ```58118E89F3A912897C070ADBF76221572C52609D``` is either the fingerprint or similarly strong as a fingerprint to avoid a forged key matching up that id. If someone with GPG knowledge can confirm that, I think I opened this issue needlessly... sorry for that :-)

However, as a minor nitpick: in that case you should probably replace the command
```
  $ wget -qO- https://get.docker.com/gpg | sudo apt-key add -
```
with the safer variant
```
  $ apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
```
in the guide at http://docs.docker.com/linux/step_one/

**Comment by tianon** [comment]
Yes, that long ID is literally the full key fingerprint.

**Comment by JonasT** [comment]
Ok, then sorry for confusing everyone :-) and thanks for explaining. The problem I imagined doesn't exist then
