### ISSUE TITLE
[1.9.0-rc3] - Upgrade from RC2 can't load containers

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#17435]
After upgrading from RC2 to RC3 I get the following error trying to load containers on daemon init:

Failed to load container 15359d38429bb14c831848eec016a5c1dfad2a1229a6852c8e2f43a3274f049a: json: cannot unmarshal array into Go value of type map[string]*network.EndpointSettings

**Comment by mavenugo** [comment]
@tiborvass @calavera please correct me if am wrong.. isnt this expected due to the changes involved in https://github.com/docker/docker/pull/17393 ?

**Comment by mavenugo** [comment]
@cpuguy83 can you confirm if this is a problem if you upgrade from 1.8 -> 1.9 ?

**Comment by cpuguy83** [comment]
Tested, is indeed only an issue from rcN-rc3

**Comment by tiborvass** [comment]
@cpuguy83 @mavenugo so can we close this?
