### ISSUE TITLE
config file not been used 

### ISSUE THREAD

**Issue by sysmat** [docker/docker#17433]
How I determine which configuration file docker is using?

Environment:
--------------------
OS: CentOS release 6.7 (Final)
docker : Docker version 1.7.1, build 786b29d/1.7.1

I have file /etc/sysconfig/docker:
-------------------------------------------
# Resolves: rhbz#1176302 (docker issue #407)
DOCKER_NOWARN_KERNEL_VERSION=1
DOCKER_OPTS="-D --dns 193.2.1.66 --dns 193.2.1.72 --dns 193.2.1.92 --dns-search arnes.si"
OPTIONS="-D --dns 193.2.1.66 --dns 193.2.1.72 --dns 193.2.1.92 --dns-search arnes.si"
HTTP_PROXY="http://proxy.arnes.si:3128"
http_proxy="${HTTP_PROXY}"

but with ps aux | grep docker I see:
----------------------------------------------
/usr/bin/docker -d

I'm using docker build behind the closed network and I'm getting error:
---------------------------------------------------------------------------------------------------
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=6&arch=x86_64&repo=os error was
14: PYCURL ERROR 6 - "Couldn't resolve host 'mirrorlist.centos.org'"

Regards, Tomaz

**Comment by sysmat** [comment]
docker info:
---------------
Containers: 6
Images: 101
Storage Driver: devicemapper
 Pool Name: docker-253:0-6160709-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 11.2 GB
 Data Space Total: 107.4 GB
 Data Space Available: 31.57 GB
 Metadata Space Used: 9.232 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.138 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.95-RHEL6 (2015-09-08)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 2.6.32-573.7.1.el6.x86_64
Operating System: <unknown>
CPUs: 1
Total Memory: 3.743 GiB
Name: sfinga.arnes.si
ID: MT2E:YB6V:IP6W:PZIJ:X23L:YCFU:USRH:545N:YWND:DDCE:LLQD:SNV5

uname -a:
--------------
Linux sfinga.arnes.si 2.6.32-573.7.1.el6.x86_64 #1 SMP Tue Sep 22 22:00:00 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cpuguy83** [comment]
Closing since this isn't an actual issue and I see you've posted this in docker-user already.
