### ISSUE TITLE
Feature Request: docker network inspect --format

### ISSUE THREAD

**Issue by albers** [docker/docker#17446]
Both `docker inspect` and `docker volume inspect` have an option to produce formatted output:

    -f, --format=      Format the output using the given go template

For consistency, `docker network inspect` should also support this option.
This would be very helpful for the shell completions of `docker disconnect`, allowing something like `docker network inspect -f '{{.containers}}' some-network`

**Comment by vdemeester** [comment]
I do agree, working on doing this for `docker images`, guess the next one would be `network inspect`.

**Comment by albers** [comment]
Great, thanks!

**Comment by thaJeztah** [comment]
Yay, the PR has been merged! Thanks for suggesting, @albers!
