### ISSUE TITLE
No permissions for non root users inside a container on host with nfsroot

### ISSUE THREAD

**Issue by nikel123** [docker/docker#17444]
I have some read and execution permission issues on my machine with nfsroot without local storage:

andrej@nikel:~$ docker run -it --name test --privileged=true ubuntu:14.04 bash                                                                                                   
Unable to find image 'ubuntu:14.04' locally
14.04: Pulling from ubuntu

3fd0c2ae8ed2: Already exists 
9e19ac89d27c: Already exists 
ac65c371c3a5: Already exists 
a5a467fddcb8: Already exists 
ubuntu:14.04: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.

Digest: sha256:d4b37c2fd31b0693e9e446e56a175d142b098b5056be2083fb4afe5f97c78fe5
Status: Downloaded newer image for ubuntu:14.04
root@143b1a24faaa:/# useradd test
root@143b1a24faaa:/# su test
Cannot execute /bin/bash: Permission denied
root@143b1a24faaa:/# 

On my laptop it works fine. I also have problems with apache2 server: it can't read anything, when it dropped root privileges. I use on both machines ubunut 15.10. Docker info:

Containers: 1
Images: 81
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: nfs
 Dirs: 83
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 4.2.0-16-generic
Operating System: Ubuntu 15.10
CPUs: 8
Total Memory: 31.43 GiB
Name: nikel
ID: PCUI:C6IU:GCNM:H7GN:HSAS:ITX4:G2DM:NJ5W:VYFZ:EDJG:I55W:W3AX
WARNING: No swap limit support

docker version:
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.5.1
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.5.1
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

**Comment by thaJeztah** [comment]
I'm not sure using nfs is officially supported, but I know there are various other issues as well, e.g. https://github.com/docker/docker/issues/15239, https://github.com/docker/docker/issues/14227, https://github.com/docker/docker/issues/4213

**Comment by LK4D4** [comment]
Going to close this because AUFS doesn't support remote filesystems.
