### ISSUE TITLE
[1.9.0-rc3] DEBUG serf messages displayed on daemon stdout

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#17449]
While the daemon is running without the debug flag, I keep getting serf(?) debug messages from the daemon's stdout:

```
2015/10/28 19:26:12 [DEBUG] memberlist: Initiating push/pull sync with: 172.17.0.3:7946
2015/10/28 19:26:20 [DEBUG] memberlist: Responding to push/pull sync with: 172.17.0.3:47065
```

**Comment by mavenugo** [comment]
@calavera @cpuguy83 its a bug in serf library. we have to see if we can selectively suppress these messages (or) fix it in the library & vendor that in. ping @mrjana

**Comment by cpuguy83** [comment]
it is possible.
Basically you have to supply a custom io.Writer to the config for serf and memberlist.
Hashicorp provides a pkg that works well with this: https://github.com/hashicorp/logutils

LMK what you want to do and I can make a patch.

**Comment by mrjana** [comment]
@cpuguy83 We don't directly initialize memberlist. We only invoke serf apis and we properly initialize serf with a custom io.Writer. There is a bug in serf where they are not passing down the custom io.Writer down to the memberlist config when they create a memberlist. So the fix is in serf

**Comment by cpuguy83** [comment]
@mrjana Can it be set here? https://github.com/docker/libnetwork/blob/master/drivers/overlay/ov_serf.go#L43

**Comment by cpuguy83** [comment]
Success! That at least seems to work.

**Comment by cpuguy83** [comment]
docker/libnetwork#717

**Comment by mavenugo** [comment]
@cpuguy83 :+1:

**Comment by mavenugo** [comment]
@cpuguy83 

drivers/overlay/ov_serf.go:51: config.MemberlistConifg undefined (type *serf.Config has no field or method MemberlistConifg)

version mismatch ?

:(

**Comment by cpuguy83** [comment]
typo, per usual :(

`Conifig`

**Comment by mrjana** [comment]
@cpuguy83 :+1: if it works :-)
