### ISSUE TITLE
Add labels on running containers for managing old running containers with no labels

### ISSUE THREAD

**Issue by Random-Liu** [docker/docker#17457]
We plan to leverage the docker label to simplify container management.

However, we didn't use that before, so the containers already started have ***no*** labels on them. It is unacceptable for us to restart running containers to add labels. So it seems that the best solution is to add labels on the old ***running*** containers.

Will this kind of feature be added anytime soon? Or are there any other solutions for this problem with existing docker features?

It seems that there are some discussion about that already, like #15496

@dchen1107 @yujuhong

**Comment by cpuguy83** [comment]
Closing since this is a dup of the already mentioned issue.

**Comment by Random-Liu** [comment]
Thanks, I was just not sure whether this will be considered as a dup issue, :)
I'll comment in the old one.
