### ISSUE TITLE
update selenium/standalone-firefox-debug tags

### ISSUE THREAD

**Issue by theblueskies** [docker/docker#17466]
Hi, 

The latest version on selenium/standalone-firefox-debug is 2.48.2 in the repo. However, the current tag does not reflect that. The latest version in the tags in 2.48.1. Could you please update the latest version in the tags at https://hub.docker.com/r/selenium/standalone-firefox-debug/tags/    ? 

Thanks!

**Comment by cpuguy83** [comment]
hello,

Please contact the owner of the selenium repo.
Thanks.
