### ISSUE TITLE
docs: wrong format for man page

### ISSUE THREAD

**Issue by WeiZhang555** [docker/docker#17469]
It looks like there's some format problems about man page, at least on my machine(ubuntu 15.04), I'll show details:

1). 'item' list can't show clearly. e.g.
```
$ man docker cp
...
       0

              item SRC_PATH specifies a file

       0

              item DST_PATH does not exist

       0

              item the file is saved to a file created at DST_PATH item DST_PATH does not exist and ends with /

       0

              item Error condition: the destination directory must exist.  item DST_PATH exists and is a file
```
It's supposed to be something like this:
```
 * SRC_PATH specifies a file
 * DST_PATH does not exist
 * the file is saved to a file created at DST_PATH item DST_PATH does not exist and ends with /
 * Error condition: the destination directory must exist.  item DST_PATH exists and is a file
```
This appears on serveral files, I guess this may be a `go-md2man` related problem. 
@cpuguy83 

2） some `~` are missing:
```
$ man docker
       --tlscacert= /.docker/ca.pem
         Trust certs signed only by this CA.

       --tlscert= /.docker/cert.pem
         Path to TLS certificate file.
```
This maybe also be a `go-md2man` related problem because the source text contains `~` definitely.

 3) some formats don't come to an agreement:
e.g.
![2](https://cloud.githubusercontent.com/assets/1203611/10809683/026f211a-7e34-11e5-838b-b19413828047.PNG)
vs
docker exec: 
![3](https://cloud.githubusercontent.com/assets/1203611/10809707/2892f786-7e34-11e5-8be4-08b766ee7d34.PNG)
vs
docker daemon:
![4](https://cloud.githubusercontent.com/assets/1203611/10809752/90e00856-7e34-11e5-8e96-bc394036f0dc.PNG)

underline or not underline, I really can't find a regular pattern. 
I'll propose that we should come to an agreement and unify the format as these man pages all belong to docker though they may be written by different person.  This is a detail problem.

**Comment by cpuguy83** [comment]
Thanks, for sure the list handling was wrong in go-md2man.
Have a fix for unordered lists... ordered lists seem to be a bit weird... I think the markdown parser is not parsing them correctly, but still investigating.

**Comment by moxiegirl** [comment]
@WeiZhang555 nice catch!

**Comment by calavera** [comment]
Fixed!
