### ISSUE TITLE
Proposal: optional/remote exec-driver support & per-container exec-driver

### ISSUE THREAD

**Issue by WeiZhang555** [docker/docker#17477]
## Background
As we can see that there already are some good works towards making docker support extra exec drivers, for example, `clear container`( #17441, #17244, #16163), which is trying to run docker containers with optimizational virtualization technology. Also there's other nice project doing similar work such as `runv` which is also compatible with OCI standard. 

Some of us may be interested in these technologies, which I mean using docker to boot a extremely light-weight virtual machine, this VM may not boot as fast as docker container, but owns enhanced security with standalone kernel for each containerized-vm.  I can also understand that Docker may not embed more exec drivers, so what I'm proposing is " optional/remote exec-driver support" and "per-container exec-driver".

## Optional/remote exec-driver support
Now docker has supported pluggable network driver, pluggable ipam driver and pluggable volume driver thanking to docker's nice design of plugin mechanism. I'm wondering whether we can provide a plugin for exec driver, so docker can interact with any custom exec driver without embed it directly, so users can still make use of docker's powerful UX and their own runtime according to different business needs. 

## Per-container exec-driver
As I know that `--exec-driver` is a daemon flag, it will take effect for all containers once set. With optional exec driver support, user will need a per-container exec driver flag, so they can choose to boot a container with any exec driver. For example, we can use `docker run ` to start a linux container with docker's default setting, or use `docker run --exec-driver remote:vm-container` to boot a lightweight kvm virtual machine. This can be super useful because we don't need to run two different docker daemons with different exec-driver flags, the latter method will bring other problems such as docker image management chaos(they can't share same image repo, if the do, they need to solve the image conflict problem)

The exec driver plugin is really useful and helpful, as there may appear more runtime projects compatible with OCI standard in the future, this plugin will make docker more open and flexible, and give user an overall solution no matter what(vm or container) user need for business.

**Comment by cpuguy83** [comment]
I think plugins is doable, but will require some extra work to implement due to passing around execdriver pipes.

**Comment by WeiZhang555** [comment]
@cpuguy83 Yes, I concur, this may require some more work besides exec driver plugin, but I think it's worth.
As I know that you are planning to make engine "directly call out to a binary implementing the Open Containers Specification such as runC ", please consider to add a plugin support for exec driver at the same time, this is really useful for who wants to use docker's UX with other OCI-compatible runtime. Because developers don't need to modify docker's source code to embed custom runtime which will be miserable when they need to update docker engine. And I believe that there could be lots of people who is interested in trying other container runtimes.

And thank you for your response! @cpuguy83

**Comment by WeiZhang555** [comment]
And I will be glad to help if this feature is accepted, looking forward to that day. :smile:

**Comment by xnox** [comment]
+1 from me.

**Comment by LK4D4** [comment]
It was implemented through `--runtime` option
