### ISSUE TITLE
--hostname is ignored by other containers in the same network

### ISSUE THREAD

**Issue by mbontemps** [docker/docker#17482]
**Description of problem:**

When using `docker run --name=project_www_1 --hostname=www --net=demo` one may expect other containers in the `demo` network to be able to access the former container as `www`.

This would be especially useful when using docker-compose 1.5 where containers use qualified names with the dir/project name (like `myproject_www_1`) for the image names, forcing us to use these as hostnames too.

**Steps to Reproduce:**

```
# docker network create demo
# docker run -d   --name test1 --hostname=bob   --net=demo    alpine sleep 30
# docker run --rm --name test2 --hostname alice --net=demo    alpine ping bob
```

**Actual Results:**

```
ping: bad address 'bob'
```

**Expected Results:**
```
PING bob (172.23.0.2): 56 data bytes
64 bytes from 172.23.0.2: seq=0 ttl=64 time=0.804 ms
64 bytes from 172.23.0.2: seq=1 ttl=64 time=0.071 ms
```

**Context:**
```
Client:
 Version:      1.9.0-rc2
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   60d36f7
 Built:        Fri Oct 23 00:20:59 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0-rc2
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   60d36f7
 Built:        Fri Oct 23 00:20:59 UTC 2015
 OS/Arch:      linux/amd64


docker info:
Containers: 9
Images: 1
Server Version: 1.9.0-rc2
Storage Driver: vfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.10-boot2docker
Operating System: Alpine Linux v3.2 (containerized)
CPUs: 1
Total Memory: 1.956 GiB
Name: cd4c8cc2e9cb
ID: HK4R:RKF6:F4IJ:FP6D:FAZO:K2BN:LJ5X:FRYW:4WNI:S4YG:QIXH:3M26

uname -a:
Linux cd4c8cc2e9cb 4.1.10-boot2docker #1 SMP Mon Oct 12 18:36:49 UTC 2015 x86_64 Linux
```

**Comment by coolljt0725** [comment]
@mbontemps  I think `docker run --rm --name test2 --hostname alice --net=demo    alpine ping test1` can work, since the `/etc/hosts` store the `container IP` and `container name` but not `hostname` of other containers

**Comment by cpuguy83** [comment]
Yes, we don't wire up the hostnames.
There is another issue for that somewhere...

**Comment by ByteFlinger** [comment]
I was going to report the same issue but stumbled upon this one. Any chance we can get a link to the other issue "somewhere"?

**Comment by skelethan** [comment]
There are actually quite a few issues related to this swirling across docker, compose, libnetwork.

Here's one of the more complete ones:
https://github.com/docker/docker/issues/17805

I am really hoping for a fix or a workaround as this issue deflates the last mile value of the new networking stack for my use cases.
