### ISSUE TITLE
docs: archlinux installation instruction minor flaw

### ISSUE THREAD

**Issue by mradke** [docker/docker#17483]
In the installation instructions for Archlinux http://docs.docker.com/installation/archlinux/ it is advised, that you may install docker-git via `sudo yaourt -S docker-git`.
I think this should be changed to `yaourt -S docker-git`, since it is not recommended to run yaourt as root. Additionally it will ask for root priviledges when it needs them.

**Comment by tophj-ibm** [comment]
Looks like it's already fixed in the repo via e9c64b6d99f23ca2ad6a755952fd9d5bcf63e19c and the website hasn't updated yet.

**Comment by mradke** [comment]
Awesome. I'll close this issue. :+1:
