### ISSUE TITLE
Starting docker service before remote filesystems are mounted breaks container bind-mounts

### ISSUE THREAD

**Issue by jperville** [docker/docker#17485]
# Description of problem

The docker service starts before remote filesystems are mounted on the host. Upon restart of the host, containers may start with broken volumes and the data from the remote filesystem won't be available from within those containers.

The fix: modify the `/etc/init/docker.conf` file to `start on (filesystem and net-device-up IFACE!=lo)` instead of `start on (local-filesystems and net-device-up IFACE!=lo)`.

# System information

`docker version`: `Docker version 1.8.3, build f4bf5c7`
`docker info`:

```
Containers: 1
Images: 2178
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: xfs
 Dirs: 2180
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-31-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 8
Total Memory: 15.58 GiB
Name: jp440p
ID: CB5Z:P7RF:RIET:BEGL:XC55:566P:2VWO:GL6X:GU75:5ZZN:66WM:SOAH
Http Proxy: http://10.0.3.84:3128
Https Proxy: http://10.0.3.84:3128
No Proxy: localhost,127.0.0.1,172.17.42.1,10.0.3.1,192.168.56.1,192.168.33.1,192.168.122.1,192.168.33.1,192.168.33.10.xip.io,10.0.2.15,/var/run/docker.sock
WARNING: No swap limit support
```

`uname -a`: `Linux jp440p 3.19.0-31-generic #36~14.04.1-Ubuntu SMP Thu Oct 8 10:21:08 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

Environment details (AWS, VirtualBox, physical, etc.):
 - ubuntu 14.04 host
 - /etc/fstab file referencing remote filesystems (in my case, cephfs mounted at /ceph)
 - docker containers declared with `docker run ... --restart=always ... -v /ceph:/ceph`

# Reproducing

How reproducible: always, as long as the remote filesystem is slow enough to mount. We use the Fuse CephFS driver which take a couple seconds to start even host-only network; I'm unsure how reproducible the problem is using NFS which is usually pretty fast to mount.

Steps to Reproduce:
1. add a /ceph mount in /etc/fstab (ours looks like `conf=//etc/ceph/ceph.conf,id=cephfs.staging4-compute,keyfile=/etc/ceph/ceph.client.cephfs.staging4-compute.secret /ceph fuse.ceph defaults,_netdev 0 0`)
2. mount /ceph and touch some files there to make it non empty
3. declare some containers which are restarted on boot and use the /ceph mount point: `docker run -d --name=bindmountbug --restart=always -v /ceph:/ceph busybox:ubuntu-14.04 nc -l 1337 -l`
4. verify with `docker exec bindmountbug ls -la /ceph` that the expected files are present
5. reboot the host
6. run `docker exec bindmountbug ls -la /ceph` and compare with results from step 3.

Actual Results:
 - The files created at step 3. are not listed in the output of the `ls -la /ceph` from step 6.

Expected Results:
 - The files created at step 3. are listed in the output of the `ls -la /ceph` from step 6.

# Additional info

The bug is explained by the docker service starting on the `local-filesystems` event (on ubuntu 14.04), which is an event which triggers before the remote file systems are mounted. The docker service should be started on the `filesystem` event instead (the filesystem event triggers after all filesystems, both local and remote, are mounted; see `man 7 filesystem`).

I fixed the issue manually by editing the `/etc/init/upstart.conf` file like this:

```diff
diff --git a/init/docker.conf b/init/docker.conf
index ec50b35..b403408 100644
--- a/init/docker.conf
+++ b/init/docker.conf
@@ -1,6 +1,6 @@
 description "Docker daemon"
 
-start on (local-filesystems and net-device-up IFACE!=lo)
+start on (filesystem and net-device-up IFACE!=lo)
 stop on runlevel [!2345]
 limit nofile 524288 1048576
 limit nproc 524288 1048576
```

See also:
 - https://github.com/docker/docker/pull/5840 , in which the docker service was modified to start on local-filesystem instead of filesystem (which introduced this issue in the first place)

**Comment by jperville** [comment]
Please also note that the remote file system may not even mount at all after the reboot in the following case:
 - the containers create files on what they think is the remote volume (but is actually the mountpoint directory on the host)
 - the operating system tries to mount the remote filesystem on the mountpoint but gives up because the mountpoint directory is not empty (the container just created a file in it)

**Comment by alexmac** [comment]
This caused me similar head-scratching when I mounted an EBS volume onto my EC2 machine afterthe docker daemon had already started and tried to volume map it into a docker container.

If there is some technical reason the docker daemon can't react to mount changes at "docker run" time then at least a warning would be good.

**Comment by cpuguy83** [comment]
Can you paste your init files (or rather link them in a gist?)

**Comment by jperville** [comment]
My /etc/init/docker.conf, before I applied my workaround: https://gist.github.com/jperville/5a5f9205e42b36bf0492

**Comment by thaJeztah** [comment]
ping @cpuguy83 any thoughts on this? do you think this could be used as a default in https://github.com/docker/docker/blob/729c9a97822ebee2c978a322d37060454af6bc66/contrib/init/upstart/docker.conf#L3 ?

**Comment by cpuguy83** [comment]
It's probably fine.
But note that if mounts aren't showing up after docker is started, this is indicative of starting docker either with private mount flags or in it's own mount namespace.

**Comment by thaJeztah** [comment]
@jperville are you interested in creating a pull-request with the proposed changes? We can continue the discussion on the pull-request once it's there

**Comment by jperville** [comment]
@thaJeztah I just submitted PR #17731 with my current workaround for this issue.

**Comment by thaJeztah** [comment]
@jperville and it's merged already! Great!


I think this can be closed then, but ping me if I closed by mistake :+1:

**Comment by pryorda** [comment]
Looks like this was not fixed in the systemd files :/

**Comment by andymadge** [comment]
@pryorda what do you mean it wasn't fixed in systemd files?

I think https://github.com/docker/for-linux/issues/293#issuecomment-397398781 is a reoccurrence of this issue. That is on Docker 18.05.0-ce / Ubuntu 18.04

**Comment by pryorda** [comment]
When starting from systemd it does not mount the remote filesystems first.

**Comment by mattdale77** [comment]
I am having this issue with Vbox shares into Ubuntu 21. I can't seem to find a work around other than manually restarting the docker service after the VM is fully booted
