### ISSUE TITLE
Running a command only once when new container is created

### ISSUE THREAD

**Issue by divyakumarjain** [docker/docker#17507]
Would like to propose a feature to be able to run a command only once when new docker container is started from an image. The use case can be database initialization using DDL only once. i know DDL scripts can be written in a way that it does not clean up old data. But we have an app were we use Apache ant scripts to run DDL and thus we do not have full control over DDL or ant script to modify them.

Thus thought to share this has a feature request.

**Comment by phemmer** [comment]
See #17235

You can do this through `docker events`, or with an entrypoint script.

**Comment by cpuguy83** [comment]
Yes, do this in a separate container.
Don't try to init the DB in the same container that you are actually running your app.
When you need to init the db, init it, when you don't, just run your container.
