### ISSUE TITLE
docker network create default driver

### ISSUE THREAD

**Issue by vieux** [docker/docker#17500]
Before https://github.com/docker/docker/pull/16910

The docker cli sent "" as driver, so engine was using bridge and swarm was using overlay if `-d` wasn't specified.

After https://github.com/docker/docker/pull/16910 

The docker cli always send "bridge" as driver, so it makes it impossible for swarm to know if a user specified "bride" or if it's the default.

I'd like to revert this behaviour.

**Comment by vieux** [comment]
ping @mavenugo @mrjana @dave-tucker

**Comment by tiborvass** [comment]
whoever sends PR to fix this, please add a test.

**Comment by calavera** [comment]
working on it.

**Comment by calavera** [comment]
Take a look at #17504.
