### ISSUE TITLE
Unable to create users in ubuntu container when running with --net host

### ISSUE THREAD

**Issue by WillPlatnick** [docker/docker#17501]
Docker: 1.8.3
OS: Ubuntu 14.04 x64
Kernel: 3.13.0-66
Baseimage: ubuntu

#docker run -i -t --net host ubuntu adduser --system --quiet --home /var/lib/postgresql --no-create-home             --shell /bin/bash --group --gecos "PostgreSQL administrator" postgres
chfn: PAM: System error
adduser: `/usr/bin/chfn -f PostgreSQL administrator postgres' returned error code 1. Exiting.

#docker run -i -t --net bridge ubuntu adduser --system --quiet --home /var/lib/postgresql --no-create-home             --shell /bin/bash --group --gecos "PostgreSQL administrator" postgres
does not throw an error.

**Comment by cpuguy83** [comment]
This is a dup, and not really a Docker issue in particular.
`--net=host` means you are the host network stack, and due to that this can cause issues with pam.
