### ISSUE TITLE
Retry push on 500?

### ISSUE THREAD

**Issue by adriancole** [docker/docker#17506]
It is a fairly regular occurrence to have 500 errors doing a docker push. Like this:
`Received unexpected HTTP status: 500 Internal Server Error`

Not sure if they are always 500s, but this happens every few releases.

I'm wondering if status quo is best (external retries based on docker status) or if it makes sense to allow a retry policy or flag. Thoughts?

**Comment by cpuguy83** [comment]
I think it's a bit weird to get 500 on push and relatively trivial to re-attempt on failure from your code.

If you are seeing many 500's, then please report to https://support.docker.com

Thanks!
