### ISSUE TITLE
align output of `docker network inspect` with other inspect commands

### ISSUE THREAD

**Issue by albers** [docker/docker#17519]
In #17481, a problem in the current implementation of `docker network inspect`surfaced:
The output has all keys lowercased, e.g. `name`, `id`. This is not in line with the output of the other inspect commands, that use capitalized keys, e.g. `Id` and `Name`.

This is confusing. In all outputs, IDs should be `Id` and names should be `Name`.
This also complicates the implementation in #17481.

Therfore the implementation of `docker network inspect` should be changed to use the capitalized key names like defined in https://github.com/docker/docker/blob/master/api/types/types.go#L337-L345.

### docker inspect

    root@19726e047c5a:~# docker inspect sad_bhaskara | head
    [
    {
        "Id": "e87a85628a32e40cf43a2958328a7a3b57c4ee274c7a5a45cf45f23d932e6a0f",
        "Created": "2015-10-30T07:37:27.590472546Z",
        "Path": "/hello",
        "Args": [],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
    
### docker volume inspect

    root@19726e047c5a:~# docker volume inspect volume
    [
        {
            "Name": "volume",
            "Driver": "local",
            "Mountpoint": "/var/lib/docker/volumes/volume/_data"
        }
    ]

### docker network inspect

    root@19726e047c5a:~# docker network inspect host
    [
        {
            "name": "host",
            "id": "ea55f7db377c388395080351f5778aee23edcac3f0364604f05cce09a7e3bd98",
            "scope": "local",
            "driver": "host",
            "ipam": {
                "driver": "default",
                "config": []
            },
            "containers": {},
            "options": {}
        }
    ]

**Comment by albers** [comment]
Is it possible to address this in 1.9, before the problematic API is released?

**Comment by vdemeester** [comment]
@albers Thanks for creating this issue :heart_eyes_cat:. 

/ping @tiborvass on the question :wink:

**Comment by albers** [comment]
I do not think it is an enhancement as it is a breaking api change. I see it as a bug.

**Comment by vdemeester** [comment]
@albers true, putting question and bug then :sweat_smile:

**Comment by albers** [comment]
Thanks, Vincent!

**Comment by thaJeztah** [comment]
Yes, I agree, but I'm not sure there's still time to get it in 1.9 :cry:

**Comment by albers** [comment]
If we don't get it in, the release notes and API docs should mention that the JSON is not stable yet.

**Comment by thaJeztah** [comment]
I'll add it to the milestone, just so that it doesn't get overlooked

**Comment by mavenugo** [comment]
@thaJeztah @albers @tiborvass this was to be consistent with the experimental REST APIs for network API which was all lower-case :(. In the experimental version, the entire UX was handled by libnetwork while the router was hooked from docker side.
I will let the other maintainers decide on the way forward.

**Comment by thaJeztah** [comment]
ping @vieux @aluzzardi @dnephin @shin- any thoughts on this as well? I had a quick chat with @tiborvass and, yes, if we want to make this change, this may be the best time to prevent it being part of a release

**Comment by mavenugo** [comment]
@aboch is working on the fix. I agree that its better to get this consistent with other docker APIs now.

**Comment by abronan** [comment]
This should be included asap when the fix is out so we can make the appropriate changes in swarm/compose. Thanks for raising the issue @albers.

**Comment by thaJeztah** [comment]
thanks @Albers (with a capital A for the occasion)!

**Comment by albers** [comment]
@thaJeztah Cool! I't case-insensitive!
