### ISSUE TITLE
Entry missing in the /etc/hosts file of the source container after linking containers

### ISSUE THREAD

**Issue by lhsvobodaj** [docker/docker#17533]
Description of problem: It seems that an entry in the file `/etc/hosts` of the source container is missing. The missing entry contains the ID of the recipient container. Below is the output of two the `hosts` files after containers are linked. *Host-1* (cffd3d6aaa69) is the source and *host-2* (4937d32a2ca3) is the recipient:
```   
root@cffd3d6aaa69:/# cat /etc/hosts 
172.17.0.44	cffd3d6aaa69
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.44	host-1
172.17.0.44	host-1.bridge
172.17.0.45	host-2
172.17.0.45	host-2.bridge
```
```
root@4937d32a2ca3:/# cat /etc/hosts 
172.17.0.45	4937d32a2ca3
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.44	host-1 cffd3d6aaa69
172.17.0.45	host-2
172.17.0.45	host-2.bridge
172.17.0.44	host-1
172.17.0.44	host-1.bridge
```
```
svoboda@ubuntu-64:~$ docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:37:18 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:37:18 UTC 2015
 OS/Arch:      linux/amd64
```
```
svoboda@ubuntu-64:~$ docker info
Containers: 9
Images: 30
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 48
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-31-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 8
Total Memory: 7.781 GiB
Name: ubuntu-64
ID: JDUN:YLMS:LORM:U5WJ:GHLE:7WBA:BMWK:FHRU:HVUA:4A56:TC5R:2SFE
WARNING: No swap limit support
```
```
svoboda@ubuntu-64:~$ uname -a
Linux ubuntu-64 3.19.0-31-generic #36~14.04.1-Ubuntu SMP Thu Oct 8 10:21:08 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.): The host machine is a VM running inside VMWare 11.1.2 build-2780323.

Steps to Reproduce:
1. docker run -it --name=host-1 ubuntu:14.04
2. docker run -it --name=host-2 --link host-1 ubuntu:14.04

Actual Results:
From the recipient container it is possible to `ping` the source container using its CONTAINER ID. However it is not possible to do the same from the source container to the recipient.

Expected Results:
Both containers should be able to reach each other by using their CONTAINER IDs.

Additional info:
The issue described above was detected during some tests with a cluster running Apache Storm. The symptom is that no message has been transferred among the members of the cluster. Looking at the Storm logs we found the following error:
```
b.s.m.n.StormClientErrorHandler [INFO] Connection failed Netty-Client-1dcef2215f68:6701
java.nio.channels.UnresolvedAddressException: null
```
We fixed this behavior by using the `--hostname` option.

**Comment by aboch** [comment]
Thanks for the thorough description.

The entry `172.17.0.44 host-1 cffd3d6aaa69` in the second container's etc/hosts file is added because of the `--link`.

This is the entry which allows container 2 to ping container 1 by container id.

But `--link` is unidirectional. It does not install an reciprocal entry on the source container's etc/hosts file.

**Comment by lhsvobodaj** [comment]
Thanks for your clarification @aboch.

Indeed, the Docker documentation mentions that using the `--link` parameter allows the recipient container to access information about the source container. However, if you have an entry like `172.17.0.45 host-2` on the source container which also allows it to access the recipient, why omit the entry with the CONTAINER ID as an alias?

**Comment by cpuguy83** [comment]
@lhsvobodaj This was a bug. This functionality will not exist in docker 1.9, at least for the default bridge.

**Comment by aboch** [comment]
@lhsvobodaj 
The entries you see in the hosts file are the result of two separate features.
The `<container id>` entry comes from the link feature.
The `<container name>` and `<container name>.<network name>` entries come from the inbuilt service discovery feature from the new networking.

As @cpuguy83 explained, the second feature was not supposed to be available on the default docker0 bridge network and it is being turned off in 1.9.
See [comment](https://github.com/docker/docker/issues/17190#issuecomment-150743021)

**Comment by lhsvobodaj** [comment]
Perfect. In this case I believe one could assign an appropriate label to this issue and close it.
