### ISSUE TITLE
[1.9.0-rc3] Cant use network id in `--net` flag

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#17543]
`docker network create` always outputs the network ID.
`docker run --net` will accept the ID, but you end up with an error: `Error response from daemon: Cannot start container 69b5abfc1fd1e625d76e55897441dd568d2573f69c3e2ff08eb0ff2128b664f0: container already connected to network backend`

As we can see, the network name is `backend` and it was resolved correctly, however it is not usable.
I can however use `docker network connect` with the network ID (but not with this container, as it is now a garbage container that I cannot start).

**Comment by aboch** [comment]
Can reproduce anytime.
Will push a fix for this shortly.
