### ISSUE TITLE
network ls on Swarm Master shows only a single overlay network

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#17552]
I got to my swarm master with `eval $(docker-machine env --swarm mhs-demo0)`, then I created my overlay network and listed. I got this:

```
$ docker network ls
NETWORK ID          NAME                DRIVER
412c2496d0eb        mhs-demo1/host      host                
dd51763e6dd2        mhs-demo0/bridge    bridge              
6b07d0be843f        my-net              overlay             
b4234109bd9b        mhs-demo0/none      null                
1aeead6dd890        mhs-demo0/host      host                
d0bb78cbe7bd        mhs-demo1/bridge    bridge              
1c0eb8f69ebb        mhs-demo1/none      null      
```
Which is nice because it shows the networks on every agent in the cluster. But it only shows the overlay network once.  If I look at the agent's individually. I get one of each network as expected.

```
$ eval $(docker-machine env mhs-demo0)

$ docker network ls
NETWORK ID          NAME                DRIVER
6b07d0be843f        my-net              overlay             
dd51763e6dd2        bridge              bridge              
b4234109bd9b        none                null                
1aeead6dd890        host                host                

$ eval $(docker-machine env mhs-demo1)

$ docker network ls
NETWORK ID          NAME                DRIVER
d0bb78cbe7bd        bridge              bridge              
1c0eb8f69ebb        none                null                
412c2496d0eb        host                host                
6b07d0be843f        my-net              overlay             
```

Seems like the FIRST  `docker network ls` should have shown two `overlay` networks one on each node but it doesn't.

**Comment by calavera** [comment]
@moxiegirl I think that's because there is really only 1 `overlay` network, both containers are attached to the same one. You see the other networks duplicated because they are not shared between hosts.

**Comment by moxiegirl** [comment]
OK, the FIRST list is by unique ID.  So..it is consistent...the id is the samw on the other two. @calavera yep @mavenugo set me straight there
