### ISSUE TITLE
1.9: shm/mqueue errors

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#17550]
When a container fails to start for random reasons, you end up see the following errors:

```
ERRO[0386] failed to umount /var/lib/docker/containers/403e99f976cb191561d7f0242eec7f3bc8c8d4e529d29a0fd04058e2b5d4cc09/shm: invalid argument 
ERRO[0386] failed to umount /var/lib/docker/containers/403e99f976cb191561d7f0242eec7f3bc8c8d4e529d29a0fd04058e2b5d4cc09/mqueue: invalid argument 
ERRO[0386] 403e99f976cb191561d7f0242eec7f3bc8c8d4e529d29a0fd04058e2b5d4cc09: Failed to umount ipc filesystems: failed to cleanup ipc mounts:
```

These errors are either misleading and nothing bad is happening or there really is an issue and now I have weird mounts hanging around?

**Comment by calavera** [comment]
They are very misleading. They should be warnings, that happens when the mount doesn't exist and we try to unmount, sorry :pensive:

**Comment by calavera** [comment]
fixing in #17554

**Comment by cpuguy83** [comment]
These errors should be gone now.

**Comment by cpuguy83** [comment]
#17539
