### ISSUE TITLE
Proposal: add --default-registry for daemon

### ISSUE THREAD

**Issue by hqhq** [docker/docker#17564]
Nowadays, the only default registry is `https://registry-1.docker.io`, it's hard coded. I propose we add a new option `--default-regitry` for daemon, so users who have their own registries can set this option and they don't need to add prefix for every image and can get images from their own registry.

I already have a simple demo on my local machine, want to confirm if it's a reasonable option for docker and if there are some people think it's useful.

**Comment by thaJeztah** [comment]
This has been proposed before and rejected; the reason is that Dockerfiles should be reproducible, and `FROM ubuntu` (for example), should mean the same everywhere

**Comment by hqhq** [comment]
@thaJeztah Thanks for your info, it makes sense, thanks, closing it.
