### ISSUE TITLE
Proposal: A more powerful filtering syntax for docker ps, docker images and co

### ISSUE THREAD

**Issue by jawher** [docker/docker#17569]
Various docker commands support filtering of item lists, like `docker ps`, `docker images` and `docker volumes`

A generic syntax for filtering has already been implemented as suggested in #2659.

However, as it is implemented now, there are a couple of shortcomings:

* Inconsistent handling of invalid filtering keys. For example, `docker images` will reject unknown fields, whereas `docker ps` would not.
* No handling of invalid syntax: `docker ps` will accept  `"a & b.c=42"` as a filter without complaining
* No support for other operators than `=`
* Due to the previous point, `docker ps` and co need to expose various flags (`--before`, `--since`, ...) to implement features which could have been implemented as regular filter if more operators were supported, e.g. `>`, `<`, or `before` ...
* Filters can only be combined using the `and` boolean operation. there is no way to combine them using `or`. It is not possible to retrieve in one-shot containers having one of two different labels for example.
* Filters cannot be negated. It is not possible to retrieve the containers without a specific label for example.

Faced with the previous issues, and since I frequently (multiple times a day) have to select a lot of temporary containers generated by various tools, I created [a tool called bateau](https://github.com/jawher/bateau) (sorry :)) which filters wither docker containers or images according to a flexible querying language.

Here are a couple of examples of the queries `bateau` can handle:

```
docker rm -fv $(bateau "!running & (name~bazooka/build | (image="bazooka/orchestration" & exit=0)))"
```

```
bateau 'created > 2w & !running & name!=precious' | xargs docker rm -fv
```

Another example for querying images:
```
 bateau -i 'size>300MB & (created > 2M | docker_version~1.5 | docker_version~1.6)'
```

As can be seen from the previous examples, the filter syntax supports:

* boolean fields, like `running`. Similar to `label` in `docker ps -f`.
* multiple operators: strict equal `=`, like `~`, `!=`, `!~`, `>`, `>=`, `<`, `<=`, ...
* negation using the `!` operator: `!running`, ...
* combining multiple filters using `&` and `|` operators
* parenthesised expressions to control operator precedence
* quoted strings
* etc.

`bateau` works extremely well for my day to day workflow.
However, it is not very efficient since it runs client-side and has to first fetch the list of all docker containers from the daemon, and then fetch the full descriptor of every container to be able to access all the container fields.

So, my question is: would you be interested in seeing such a query language integrated in the docker daemon for a more *flexible*, *efficient* and *extendable* filtering facility ?

## Retro-compatibility

It should be noted that such a change could be made retro-compatible with the existing filters.
Not cleanly admittedly, but doable all the same:

* `exited=0`, `id=<id>`, `name=<name>` and co: directly maps to bateau's syntax
* `label=<key>`: bateau's equivalent is `label.key`, but the current syntax could be implemented easily
* `label=<key>=<value>`:  bateau's equivalent is `label.key=value`, but the current syntax could be implemented easily

**Comment by duglin** [comment]
I like the idea of a more powerful filtering mechanism for a couple of reasons:
1 - well, its more powerful :-)
2 - it would allow us to combine filtering and some of the flags (like --since, as you said)
3 - it would remove some of the Golang specific nature of our UX. IMO, we shouldn't expose our choice of programming language thru the UX.

My concerns are:
1 - how to introduce this. It would probably need to be under a different flag so that both exist at the same time for a while - and deprecate the existing flags
2 - is supporting a query language a full-time job? do we want to sign-up for that?

**Comment by jawher** [comment]
Thanks for th reply @duglin 

Regarding the concerns you listed:

1 - We could introduce a new flag, but as I said in the issue description, the query syntax I implemented is backward compatible with docker current syntax: any valid filter which works now will work the same in the new query language
2 - As can be seen in [bateau's implementation](https://github.com/jawher/bateau/blob/master/query/parser.go) of the query parser, the said parser is a hand-written recursive descent parser. It's only 170 lines long of rather readable code (subjectively of course).
Extending the query language, IMHO shouldn't be a big issue. Possible extensions include:

* adding new comparison operators: in which case the lexer should be modified. I can easily modify the current implementation to make it accept the possible operators as a string slice instead of hard-coding them as is now.
* adding new fields: doesn't require modifying the lecture nor the parser.
* adding new syntax for values (something like bateau's duration and size values): doesn't require modifying the lecture nor the parser.

I think the previous 3 points cover 90% of the possible future extensions, and all could be achieved without touching the lexing and parsing logic.

Of course there is another alternative which is to generate the lecture and parser from a lex/yacc file, although I'm not a big fan of the ugly code they generate and cryptic error messages they produce for invalid input.

**Comment by thaJeztah** [comment]
I like more powerful features here as well, perhaps the Swarm team should be cc'd in this as well, I know they've looked into some things as well in the past

**Comment by jawher** [comment]
Now that 1.9 is out and DockerCon is over, any news on this ? :smile:

**Comment by jawher** [comment]
@duglin:
> My concerns are:
> 1 - how to introduce this. It would probably need to be under a different flag so that both exist at the same time for a while - and deprecate the existing flags

After looking at the existing code, I tend to agree with you there: as is now, the docker client will collect all the filters provided via `-f` and store them in a `map[string][]string` (where keys are field names and values are the list of provided values), and then encode them as JSON before sending them to the server.

Extending this behaviour to handle the proposed query syntax while maintaining compatibility with older clients is not going to be very clean.

So a new flag (mutually exclusive with `-f`) might be a better way to do it.

@thaJeztah:
> perhaps the Swarm team should be cc'd in this as well, I know they've looked into some things as well in the past

Would be interested in their feedback. Could you ping the relevant persons please ?

(A gratuitous ping for @vdemeester as well :stuck_out_tongue:)

**Comment by vdemeester** [comment]
ping @vieux @aluzzardi @abronan I guess :wink:

**Comment by jpawlik** [comment]
At the very least I think it would make sense to have filter negation. It would help to take care issues like https://github.com/docker/docker/issues/9878, among other things. A wildcard operator would be nice too.

**Comment by LK4D4** [comment]
I think this proposal had enough time opened without attention. Some work was done by David Calavera. I personally think that we shouldn't overload CLI too much.
Feel free to open new issue or PR if you'll feel like that.
