### ISSUE TITLE
Centos 7 firewalld/selinux container fail

### ISSUE THREAD

**Issue by bgrissin** [docker/docker#17566]
[root@localhost ~]# uname -a
Linux localhost.localdomain 3.10.0-229.14.1.el7.x86_64 #1 SMP Tue Sep 15 15:05:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

[root@localhost ~]# docker version
Client:
 Version:      1.9.0-rc3
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   2100b94
 Built:        Wed Oct 28 01:42:24 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0-rc3
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   2100b94
 Built:        Wed Oct 28 01:42:24 UTC 2015
 OS/Arch:      linux/amd64

[root@localhost ~]# docker info
Containers: 4
Images: 57
Server Version: 1.9.0-rc3
Storage Driver: devicemapper
 Pool Name: docker-8:3-67208028-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: /dev/loop2
 Metadata file: /dev/loop3
 Data Space Used: 2.369 GB
 Data Space Total: 107.4 GB
 Data Space Available: 47.01 GB
 Metadata Space Used: 3.215 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.14.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 1.784 GiB
Name: localhost.localdomain
ID: SJCF:6NH7:H4M4:D32W:DBWW:VJXQ:VU5L:FCGI:X4QD:G3LG:B2NL:UP7D
Username: bgrissin
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

Environment details (AWS, VirtualBox, physical, etc.):  VMware Fusion
How reproducible:   highly reproducible
Steps to Reproduce: 

1)	start a very vanilla Centos 7 install instance.  
2)	In order to get Docker 1.9 rc3 installed and started, I had to stop firewalld.  Once installed, I turned the firewalld service back on, setenforce set to enforcing.
3)	Then tried to run container  (docker run -d -p 80:80 nginx )   fails 
4)	Stop firewalld and setenforce0, step 3 works works.

Actual Results:   Containers fail to start getting firewalld issues reporting in journalctl 

Expected Results:   Containers run on start, regardless if firewalld and/or setenforce 

Additional info:

**Comment by bgrissin** [comment]
more specific details - installed with firewalld enable and started, could not start the service 

[root@localhost ~]# systemctl start docker
Job for docker.service failed. See 'systemctl status docker.service' and 'journalctl -xn' for details.
[root@localhost ~]# journalctl -xn
-- Logs begin at Fri 2015-10-30 11:29:41 PDT, end at Fri 2015-10-30 11:34:43 PDT
Oct 30 11:33:09 localhost.localdomain systemd[1]: Closed Docker Socket for the A
-- Subject: Unit docker.socket has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.socket has finished shutting down.
Oct 30 11:33:13 localhost.localdomain systemd[1]: Starting Docker Socket for the
-- Subject: Unit docker.socket has begun with start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.socket has begun starting up.
Oct 30 11:33:13 localhost.localdomain systemd[1]: Listening on Docker Socket for
-- Subject: Unit docker.socket has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.socket has finished starting up.
-- 
-- The start-up result is done.
Oct 30 11:33:13 localhost.localdomain systemd[1]: Starting Docker Application Co
-- Subject: Unit docker.service has begun with start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has begun starting up.
Oct 30 11:33:13 localhost.localdomain docker[11810]: time="2015-10-30T11:33:13.1
Oct 30 11:33:13 localhost.localdomain docker[11810]: time="2015-10-30T11:33:13.2
Oct 30 11:33:13 localhost.localdomain docker[11810]: time="2015-10-30T11:33:13.2
Oct 30 11:34:43 localhost.localdomain systemd[1]: docker.service operation timed
Oct 30 11:34:43 localhost.localdomain systemd[1]: Failed to start Docker Applica
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has failed.
-- 
-- The result is failed.
Oct 30 11:34:43 localhost.localdomain systemd[1]: Unit docker.service entered fa
lines 18-40/40 (END)
-- 
-- Unit docker.socket has finished starting up.
-- 
-- The start-up result is done.
Oct 30 11:33:13 localhost.localdomain systemd[1]: Starting Docker Application Con
-- Subject: Unit docker.service has begun with start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has begun starting up.
Oct 30 11:33:13 localhost.localdomain docker[11810]: time="2015-10-30T11:33:13.18
Oct 30 11:33:13 localhost.localdomain docker[11810]: time="2015-10-30T11:33:13.20
Oct 30 11:33:13 localhost.localdomain docker[11810]: time="2015-10-30T11:33:13.25
Oct 30 11:34:43 localhost.localdomain systemd[1]: docker.service operation timed 
Oct 30 11:34:43 localhost.localdomain systemd[1]: Failed to start Docker Applicat
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has failed.
-- 
-- The result is failed.
Oct 30 11:34:43 localhost.localdomain systemd[1]: Unit docker.service entered fai
lines 18-40/40 (END)

**Comment by thaJeztah** [comment]
Could be dup / related to https://github.com/docker/docker/issues/16763, https://github.com/docker/docker/issues/15498, https://github.com/docker/docker/issues/16137 could you have a look of those look similar?


How did you install docker? Did you download a static binary, or use the rpm?

**Comment by bgrissin** [comment]
17566 is most like 16763 in that the installation of docker is the same (curl using test.docker.com), which installed 1.9 rc3.  Will try the rpm with selinux bundle.  thnx

**Comment by bgrissin** [comment]
created docker repo using  http://yum.dockerproject.org/repo/testing/centos/7/Packages/ and successfully installed and  started latest docker-engine (rc4).

**Comment by thaJeztah** [comment]
Cool, thanks @bgrissin !
