### ISSUE TITLE
Proposal: API/UI to Edit Daemon Configuration

### ISSUE THREAD

**Issue by dhiltgen** [docker/docker#17560]
This proposal builds upon the [persistent configuration file proposal](https://github.com/docker/docker/issues/17559) and exposes an API and UI for runtime editing of the daemon configuration.  Where possible, configuration changes will be performed immediately on the running daemon and yield a 204 response.  When not possible, the configuration changes will be recorded in the configuration file and take effect on a subsequent restart of the daemon, and yield a 202 response, with a response body message indicating a restart of the daemon is required for the changes to take effect.  Multiple changes may be applied in one operation, or individual changes can be performed one at a time.

An initial implementation is envisioned to only support KV store and label configuration.  Additional settings may be added over time.  Initial configuration of the KV store would be supported without requiring a restart, however changing the KV store would require restarting the daemon.  Updating daemon labels would be supported without requiring a restart.

If the configuration change requires a restart, subsequent queries for the configuration will return the persistent configuration and a status of “restart required”  Future enhancements could offer a query parameter to distinguish active from persisted state.

### Display current configuration

`GET /config`

Display current configuration

**Example request**:

    GET /config HTTP/1.1

**Example response**:

    HTTP/1.1 200 OK
    Content-Type: application/json
    
    {
        “status”: “active”,
        “configuration”: {
            "cluster-advertise": “192.168.1.2:2376”,
            "cluster-store": “etcd://192.168.1.2:2379”,
            "cluster-store-opt": {
                “kv.cacertfile”: “/etc/docker/ssl/ca.pem”,
                “kv.certfile”: “/etc/docker/ssl/cert.pem”,
                “kv.keyfile”: “/etc/docker/ssl/key.pem”
            },
            “label”: {
                “storage”: “ssd”,
                “rack”: “42”
            }
        }
    }

### Change configuration

`POST /config`

Change configuration

**Example request**:

    POST /config HTTP/1.1
    
    {
        "cluster-advertise": “192.168.1.2:2376”,
        "cluster-store": “etcd://192.168.1.2:2379”,
        "cluster-store-opt": {
            “kv.cacertfile”: “/etc/docker/ssl/ca.pem”,
            “kv.certfile”: “/etc/docker/ssl/cert.pem”,
            “kv.keyfile”: “/etc/docker/ssl/key.pem”
        },
        “label”: {
            “storage”: “ssd”,
            “rack”: “42”
        }
    }

**Example response**:

    HTTP/1.1 204 OK

If the caller attempts to change a setting (or a map key) that was passed to the daemon as a CLI argument, the request will be rejected with a 403 response code, and a payload indicating the setting was specified via a command line argument.  To change the setting, the daemon flags must be changed manually.

To remove a setting from the configuration file, the key is passed with an empty string value in the POST.

The following examples illustrate the UI for configuration management:

```bash
% docker config set \
cluster-store=etcd://1.2.3.4:5678 \
cluster-advertise=tcp://1.2.3.4:2376 \
cluster-store-opt=kv.cacertpath=/etc/docker/ssl/ca.pem \
cluster-store-opt=kv.certpath=/etc/docker/ssl/cert.pem \
cluster-store-opt=kv.keypath=/etc/docker/ssl/key.pem \
label=storage=ssd

% docker config ls
cluster-store=etcd://1.2.3.4:5678
cluster-advertise=tcp://1.2.3.4:2376
cluster-store-opt=kv.cacertpath=/etc/docker/ssl/ca.pem
cluster-store-opt=kv.certpath=/etc/docker/ssl/cert.pem
cluster-store-opt=kv.keypath=/etc/docker/ssl/key.pem
label=storage=ssd
```

**Comment by thaJeztah** [comment]
Just reading up on this;

- your example shows setting all options at once; I take its also possible to set/update options individually?
- can I export/import (save/load) all options from the CLI?
- does the CLI give feedback if a daemon restart is required?
-should changing options be more atomic? I.e. what if half the options have direct effect, and the other half require a restart of the daemon?

just some quick thoughts (didn't look into the code yet)

**Comment by dhiltgen** [comment]
Thanks for taking a look!  (No code yet - I'd like to try to get consensus on the approach first.)

Yes, the intention was to support individual or bulk change.  I'll update the proposal to clarify that.

On the subject of import/export round-trip via the CLI, I don't oppose making that work, but I'm not sure what the use-case is to motivate it.  Since this builds upon the configuration file proposal, I think leveraging the file directly for those scenarios might make more sense.

For the active vs. restart state of the daemon, yes, I agree that should be exposed. I'd like to try to keep the display output consistent and easily parseable, so how about an additional sub-command

```bash
% docker config status
Active

% docker config status
Restart required
```

**Comment by thaJeztah** [comment]
> No code yet - I'd like to try to get consensus on the approach first.)

Oh! You're right; was reading on my phone, lol

> On the subject of import/export round-trip via the CLI, I don't oppose making that work, but I'm not sure what the use-case is to motivate it. Since this builds upon the configuration file proposal, I think leveraging the file directly ...

That could be an option, yes; assuming that we always use a configuration file. Being able to do it via the API, would allow using a different storage mechanism for these configurations. Thinking of having an easy, standardized way to configure a daemon with a pre-made configuration file.

I think @nathanleclaire may be interested in having a look at this (for docker machine)

> For the active vs. restart state of the daemon, yes, I agree that should be exposed. I'd like to try to keep the display output consistent and easily parseable, so how about an additional sub-command

My biggest concern was ending up in a situation where configuration changes are only partly applied until the daemon is restarted; I haven't given that a lot of thought yet, but wondering if that could result in nasty situations.


How would this API interact with (e.g.) SystemD unit files / drop-ins? Would those need changes? Which one would take precedence?

**Comment by dhiltgen** [comment]
Once we have an agreed upon way to configure the docker daemon, yes, I think it make sense for other related tools to follow that same pattern.

I think we should follow the common practice where command line flags take precedence over configuration file settings. Ultimately I think the init system should not carry the configuration, although that may take a few releases to realize.  The system daemon would rely on the configuration in the file for all the settings.  Running the daemon by hand would be the use-case where CLI flags still make sense.

**Comment by nathanleclaire** [comment]
IANTM (just CCed in the thread), but my feeling is that having the daemon update configuration in-place is an extremely dangerous idea, especially through a mechanism like you've outlined here.  I'd generally expect Docker daemon configuration changes to require a restart or at least a UNIX signal to the process.  All of the state management logic (and tracking what's allowed to change in place vs. what's forbidden) blows up the scope of implementing such a configuration file 10x.

**Comment by nathanleclaire** [comment]
What's the motivation for wanting to change configuration while the process is running?

**Comment by cpuguy83** [comment]
@nathanleclaire I think only specific things would be supported here.

Specifically, being able to join (or potentially leave) a cluster is extremely helpful.

**Comment by dhiltgen** [comment]
In addition to cluster membership, engine labels are used by many schedulers and users want to be able to update them dynamically.

**Comment by tiborvass** [comment]
It would be interesting to explore just reloading the config instead of dynamically change through the API.

**Comment by duglin** [comment]
Some thoughts:
- should we allow tweaking of individual properties?  In cases like this, where you expose an API to modify something, you're basically distributing the write-access to the resource. There's usually less of a chance of conflicts, or overwrites, if everyone is forced to ssh to the box and modify a config file than there is if someone POSTs what they **think** is a tweak to the latest, when in fact they forgot to GET it first to be sure.  Allowing modifications to individual properties reduces the problem.  I'd still support full update though too.

- this PR assumes all changes are written to disk so that a restart of the daemon will pick-up those new config file settings.  On today's call someone asked if we were going to detect changes to the on-disk config file. I don't have an opinion yet on whether we should or not, but if we did then we could easily look at this PR as exposing API on the config file itself rather than the daemon. Meaning, this API updates the config file - then the daemon cron-like process that looks for a modified config file will pick up the new values irrespective of whether the mods were done via the API or via vim.

- on the point of rejecting API requests that modify cli settings, I would prefer to not do that. Let's do what they asked for since, to me, they're saying "run it with these properties from now on".  Besides, trying to track (and check) which properties were set via the cmd line vs config file just feels like a lot more work than it's worth.

**Comment by thaJeztah** [comment]
FYI, there's also an existing PR for updating daemon settings; https://github.com/docker/docker/issues/17560

**Comment by duglin** [comment]
Related to: https://github.com/docker/docker/pull/16978   I think

**Comment by duglin** [comment]
with the new daemon config file stuff we may want to revisit this one (and #16978)
ping @calavera @icecrime

**Comment by thaJeztah** [comment]
@duglin do you have a direct need for an API now? Wondering if we should wait one release, to see how the current config-file works out / stabilizes, before adding more features.

**Comment by duglin** [comment]
@thaJeztah that's fine with me.

**Comment by dhiltgen** [comment]
One thing we might want to consider in the next release as a stepping stone towards this is a more machine friendly way to determine if the configuration is good.  The current setup requires OS specific tailing of log files looking for patterns which is error prone.

**Comment by dhiltgen** [comment]
One potential approach would be to add something to `/info` that gets updated when the signal triggers the daemon to load the configuration to let us know if the dynamic config load was successful or if it encountered errors.

**Comment by thaJeztah** [comment]
Keep thinking of something similar to `apachectl configtest`

**Comment by dhiltgen** [comment]
That could work well for manual user testing, but makes it tricky when you're trying to automate configuration management from within a self-hosted privileged container.

**Comment by thaJeztah** [comment]
ah, right, API
ignore me😊

**Comment by thaJeztah** [comment]
We now have the daemon.json, and in future will integrate with InfraKit, which possibly could provide some options here.

I'll close this issue, but let me know if something is still needed

**Comment by endophage** [comment]
@thaJeztah is there a way to determine what daemon.json is currently in use? Also is there a way to determine if there were any command line overrides? I think both those would be necessary in the case where we want to programmatically reconfigure a daemon.

**Comment by thaJeztah** [comment]
@endophage setting options both on the CLI and in `daemon.json` currently will result in an error, but we may want to design a different behavior for that. For active configuration, see https://github.com/docker/docker/issues/21559, and https://github.com/docker/docker/pull/27473#issuecomment-265830228

**Comment by endophage** [comment]
Good to know on CLI+daemon.json, that definitely makes things easier. 

Don't see a solution in those linked items though for finding the active configuration. Simply doing `cat /etc/docker/daemon.json` is overly naive as a different configuration location can be passed to `dockerd`. Short of looking up the dockerd process, parsing how it was run to see if an alternate config was passed, and falling back to the default `/etc/docker/daemon.json`, I don't see a way to get either the actual active configuration, or the location of the configuration file that was loaded.
