### ISSUE TITLE
Docker hosts compatibility

### ISSUE THREAD

**Issue by mitar** [docker/docker#17570]
As [commented here](https://github.com/docker/docker/issues/14083#issuecomment-119346611) for new Docker networking features.

I am using [docker-hosts](https://github.com/blalor/docker-hosts) which does something similar by adding custom entries for each container into the `/etc/hosts`. What I like there is that I am able to define both the short name, but also full domain name, so service `hello` would be available as `hello`, but also as `hello.example.com`. So could you add a feature where we could define a domain to be appended to the service? This then allows easier migration from external to internal services and back.

**Comment by thaJeztah** [comment]
For docker 1.9.x we're in feature freeze, but I'll cc the network team for thoughts, thanks for suggesting!

/cc @mavenugo @mrjana

**Comment by mitar** [comment]
It seems that docker-hosts works again with Docker 1.8 and you can mount a volume over `/etc/hosts` correctly. I have not tested it with 1.9 though.

**Comment by calavera** [comment]
Thanks for opening this issue. I'm going to close it since we cannot guarantee how tools that have not been updated in almost two years can work with modern versions of docker.

**Comment by Fredjet** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  fredjet15@gmail.com
    Domain ventureacceleration.com has exceeded the max emails per hour (55/50 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:48261 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by eaglepeak.ovasp.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1abd13-0000aB-2Q
	for fred@ventureacceleration.com; Thu, 03 Mar 2016 18:50:45 -0500
Date: Thu, 03 Mar 2016 15:50:04 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457049004;
	bh=Y/O77RQ8CS3laQE4FijBOykwHux/kDaoEdugtydJB/4=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=IxRiAnqyYu4pqNFvmmKq4m17NIG7WFiI8pCxCMyeF6qy9QgYNaSw7EWQvqWi7mwd+
	 mvm1Id3Z8IdXdev7zsQKe2YPF4nIDrEj4TUmpmnu3TcSuOuBaNBILYYCKH36rssj/S
	 Zndhsz/Zxk/5BhhY9VbkxmxEqrylJhmbBp1G4zp0=

**Comment by Fredjet** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  fredjet15@gmail.com
    Domain ventureacceleration.com has exceeded the max emails per hour (56/50 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:48321 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by eaglepeak.ovasp.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1abd13-0000aC-8B
	for fred@ventureacceleration.com; Thu, 03 Mar 2016 18:50:45 -0500
Date: Thu, 03 Mar 2016 15:50:04 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457049004;
	bh=nXkOhbTjCqAvumvB/L2bJK6317SqrMBEYpzokcy+Idk=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=K4A2V3hM2bNn+5YcaycWJK4ESq/KcN/HgTIiJLLoBYojUQDkacMVzF8F2Qb8DyHdA
	 WCX+pcWg7vg2JZor0c/9S8PTlxdui0U8VOoRbYF7FQEPHheyzNkvn8urq6AFVSRTLH
	 n8haNAAD8AVd9YEHTQgWXnJ7VUKKhqEiypBB6QoI=
