### ISSUE TITLE
Volume plugin Unmount Issues

### ISSUE THREAD

**Issue by rsmoorthy** [docker/docker#17585]
Using Docker Volume Plugin
Docker version: 1.8.2

* Start a container, using a volume plugin:
```
docker run -id --name first -v volname:/data --volume-driver=plugin ubuntu bash
```
* The volume plugin receives these calls, and the volume gets mounted:
```
Create: {"Name":"volname"}
Path: {"Name":"volname"}       Responds with {MountPoint: /mnt/volname, Err:null}
Path: {"Name":"volname"}      Responds with {MountPoint: /mnt/volname, Err:null}
Mount: {"Name":"volname"}      Responds with {MountPoint: /mnt/volname, Err:null}
```
* Start another container, with the same volume name:
```
docker run -id --name second -v volname:/data --volume-driver=plugin ubuntu bash
```
* The volume plugin gets the same set of calls and responds exactly the same way.
* Now stop the second container. The volume plugin receives an unmount request.
```
Unmount: {"Name":"volname"}      Responds with {MountPoint: /mnt/volname, Err:null}
```

**The volume plugin unmounts volume, while the first container still expects the volume to be available**

Possible solutions:
* Volume Plugin could possibly keep track of "Create" requests as the count of containers and do the actual unmount at the last Unmount call.
    - However, Docker does not call "Remove" API call, on deletion of containers (unless there is an error)
* For the given volume name, Docker daemon should only call Unmount API call on the last container  being stopped.
* Docker could provide a reference value (referring the container), along with each Create/Mount/Unmount call -- so that the Volume plugin can unmount at the last possible scenario.

Please refer to https://github.com/rsmoorthy/docker-volume-plugin-helloworld that uses SSHFS as the backend, using which it was tested. This [reference](https://github.com/rsmoorthy/docker-volume-plugin-helloworld/blob/master/Unmount_Issues.md) explains how the lazy unmounting, helped the first container retain the mount, even after the second container had stopped.

**Comment by cpuguy83** [comment]
You should expect each new mount call to be usable as a ref count.
Docker does send remove when a container is removed, but only if the user specified "-v" as an argument to "docker rm".
This is equivalent of "docker volume rm".

**Comment by rsmoorthy** [comment]
Thanks @cpuguy83. I confirmed the Remove API call being sent to the plugin, when the "-v" was provided.

Is it possible to update the documentation at https://docs.docker.com/extend/plugins_volume/ -- regarding the ref count, so there is clarity for plugin writers? Thanks

**Comment by thaJeztah** [comment]
@rsmoorthy are you interested in creating a pull request to add it to that documentation? The Markdown file that's used to generate that page can be found in this repository; https://github.com/docker/docker/blob/master/docs/extend/plugins_volume.md
