### ISSUE TITLE
cpu.cfs_quota_us: permission denied

### ISSUE THREAD

**Issue by cwmp** [docker/docker#17587]
When trying to start a scales (https://github.com/PufferPanel/Scales) docker container, I am getting the following error.

cmd: docker start pp-tf33_ry5bcxf

Error response from daemon: Cannot start container pp-tf33_ry5bcxf: [8] System error: open /sys/fs/cgroup/cpu,cpuacct/system.slice/docker-6f2a7ce736c6c1ea55f036638211a9a73a1df8ab3e31cc117532f359099eb3b3.scope/cpu.cfs_quota_us: permission denied
Error: failed to start containers: [pp-tf33_ry5bcxf]

=================

docker image used: 

https://github.com/PufferPanel/docker-images/tree/master/srcds

=====
Physical Box

uname -a:
-Debian Jessie - 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u5 (2015-10-09) x86_64 GNU/Linux

docker version:
-Docker version 1.8.3, build f4bf5c7

docker info:
Containers: 12
Images: 21
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 45
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 12
Total Memory: 62.92 GiB
Name: XXXXXX
ID: XXXXX

docker inspect:

[
{
    "Id": "b46281b6524d80e304d7824a81ae377a68a3b181093a63f169c3d3cf52843d13",
    "Created": "2015-11-01T12:44:35.234670797Z",
    "Path": "/bin/bash",
    "Args": [],
    "State": {
        "Running": false,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 0,
        "ExitCode": -1,
        "Error": "[8] System error: open /sys/fs/cgroup/cpu,cpuacct/system.slice/docker-b46281b6524d80e304d7824a81ae377a68a3b181093a63f169c3d3cf52843d13.scope/cpu.cfs_quota_us: permission denied",
        "StartedAt": "0001-01-01T00:00:00Z",
        "FinishedAt": "0001-01-01T00:00:00Z"
    },
    "Image": "4afcabec9aea1c5e0bbfbf77e1e9cbc9e3c0f3272d61ff2da56a212427ff6657",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "",
        "Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "",
        "NetworkID": "",
        "PortMapping": null,
        "Ports": null,
        "SandboxKey": "",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "ResolvConfPath": "/var/lib/docker/containers/b46281b6524d80e304d7824a81ae377a68a3b181093a63f169c3d3cf52843d13/resolv.conf",
    "HostnamePath": "/var/lib/docker/containers/b46281b6524d80e304d7824a81ae377a68a3b181093a63f169c3d3cf52843d13/hostname",
    "HostsPath": "/var/lib/docker/containers/b46281b6524d80e304d7824a81ae377a68a3b181093a63f169c3d3cf52843d13/hosts",
    "LogPath": "/var/lib/docker/containers/b46281b6524d80e304d7824a81ae377a68a3b181093a63f169c3d3cf52843d13/b46281b6524d80e304d7824a81ae377a68a3b181093a63f169c3d3cf52843d13-json.log",
    "Name": "/pp-tf2_sr_s6uiq",
    "RestartCount": 0,
    "Driver": "aufs",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "AppArmorProfile": "",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": [
            "/home/pp-tf2_sr_s6uiq/public:/home/container"
        ],
        "ContainerIDFile": "",
        "LxcConf": [],
        "Memory": 2097152000,
        "MemorySwap": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": -1,
        "BlkioWeight": 500,
        "OomKillDisable": false,
        "MemorySwappiness": -1,
        "Privileged": false,
        "PortBindings": {
            "27015/tcp": [
                {
                    "HostIp": "x.x.x.x",
                    "HostPort": "29415"
                }
            ],
            "27015/udp": [
                {
                    "HostIp": "x.x.x.x",
                    "HostPort": "29415"
                }
            ]
        },
        "Links": null,
        "PublishAllPorts": false,
        "Dns": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "VolumesFrom": null,
        "Devices": [],
        "NetworkMode": "default",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "GroupAdd": null,
        "RestartPolicy": {
            "Name": "no",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
        "CgroupParent": "",
        "ConsoleSize": [
            0,
            0
        ]
    },
    "GraphDriver": {
        "Name": "aufs",
        "Data": null
    },
    "Mounts": [
        {
            "Source": "/home/pp-tf2_sr_s6uiq/public",
            "Destination": "/home/container",
            "Mode": "",
            "RW": true
        }
    ],
    "Config": {
        "Hostname": "docker",
        "Domainname": "",
        "User": "2001:126",
        "AttachStdin": true,
        "AttachStdout": true,
        "AttachStderr": true,
        "ExposedPorts": {
            "27015/tcp": {},
            "27015/udp": {},
            "27020/tcp": {}
        },
        "Tty": true,
        "OpenStdin": true,
        "StdinOnce": true,
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "DEBIAN_FRONTEND=noninteractive",
            "HOME=/home/container"
        ],
        "Cmd": [
            "/bin/bash"
        ],
        "Image": "pufferpanel/srcds",
        "Volumes": null,
        "WorkingDir": "/home/container",
        "Entrypoint": null,
        "OnBuild": null,
        "Labels": {}
    }
}
]

**Comment by cwmp** [comment]
extended information regarding the issue:

 systemd                               215-17+deb8u2                        amd64        system and service manager
systemd-sysv                          215-17+deb8u2                        amd64        system and service manager - SysV links

/var/log/daemon.log:

Nov  3 00:04:52 localhost systemd[1]: Failed to set memory.limit_in_bytes on : Invalid argument
Nov  3 00:04:52 localhost systemd[1]: Failed to set cpu.cfs_period_us on /system.slice: Permission denied
Nov  3 00:04:52 localhost systemd[1]: Failed to set cpu.cfs_quota_us on /system.slice: Permission denied
Nov  3 00:04:52 localhost systemd[1]: Failed to set cpu.cfs_period_us on /system.slice/docker-b46281b6524d80e304d7824a81ae377a68a3b181093a63f169c3d3cf52843d13.scope: Permission denied
Nov  3 00:04:52 localhost systemd[1]: Failed to set cpu.cfs_quota_us on /system.slice/docker-b46281b6524d80e304d7824a81ae377a68a3b181093a63f169c3d3cf52843d13.scope: Permission denied
Nov  3 00:04:52 localhost systemd[1]: Failed to set cpu.cfs_period_us on /user.slice: Permission denied
Nov  3 00:04:52 localhost systemd[1]: Failed to set cpu.cfs_quota_us on /user.slice: Permission denied

**Comment by cwmp** [comment]
https://lists.debian.org/debian-kernel/2015/10/msg00313.html

missing kernerl feature

**Comment by cwmp** [comment]
please close this issue

**Comment by vdemeester** [comment]
@cwmp you can close it yourself too :wink:
