### ISSUE TITLE
docker starts even there are misconfigured config options in /etc/sysconfig/docker

### ISSUE THREAD

**Issue by ekuric** [docker/docker#17588]
If there is typo and/or miss-configured option in /etc/sysconfig/docker , docker will start.
Example, if there is 
`OPTIONS='--selinux-enabled"`  ( it should be closed with single quotation mark ' instead of double ") 

docker will start while reporting in logs 
`Nov  1 14:34:12 e-makina systemd: Ignoring invalid environment assignment 'OPTIONS=--selinux-enabled"`

and `systemctl status docker -l`  output will give 

`systemctl status docker -l
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2015-11-01 14:34:12 CET; 28s ago
     Docs: http://docs.docker.com
 Main PID: 6127 (docker)
   CGroup: /system.slice/docker.service
           └─6127 /usr/bin/docker daemon --storage-driver devicemapper --storage-opt dm.fs=xfs --storage-opt dm.thinpooldev=/dev/mapper/vg_e--makina-docker--pool --insecure-registry 0.0.0.0/0`

from this is visible docker started without selinux enabled. I did not tested other misconfigurations / typos in `/etc/sysconfig/docker` but I think if there is issue with configuration, then service should fail instead of starting.

Installed package when above issue is visible 
`docker-1.8.2-7.gitcb216be.fc22.x86_64`

**Comment by ekuric** [comment]
ok, it is physical system, rest of info below. 
$ docker version
Client:
 Version:      1.8.2-fc22
 API version:  1.20
 Package Version: docker-1.8.2-7.gitcb216be.fc22.x86_64
 Go version:   go1.5.1
 Git commit:   cb216be/1.8.2
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2-fc22
 API version:  1.20
 Package Version: 
 Go version:   go1.5.1
 Git commit:   cb216be/1.8.2
 Built:        
 OS/Arch:      linux/amd64
[elvir@e-makina docker]$ docker info
Containers: 0
Images: 23
Storage Driver: devicemapper
 Pool Name: vg_e--makina-docker--pool
 Pool Blocksize: 524.3 kB
 Backing Filesystem: extfs
 Data file: 
 Metadata file: 
 Data Space Used: 1.48 GB
 Data Space Total: 2.718 GB
 Data Space Available: 1.238 GB
 Metadata Space Used: 512 kB
 Metadata Space Total: 335.5 MB
 Metadata Space Available: 335 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Library Version: 1.02.93 (2015-01-30)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.3-200.fc22.x86_64
Operating System: Fedora 22 (Twenty Two)
CPUs: 4
Total Memory: 7.682 GiB
Name: e-makina
ID: CVVU:MO6A:LFQI:QJC5:E3IC:RRDJ:OTE2:EPW3:KVQF:JMZI:XE5T:XU3C
Username: elvirkuric
Registry: https://index.docker.io/v1/
[elvir@e-makina docker]$ uname -a 
Linux e-makina 4.2.3-200.fc22.x86_64 #1 SMP Thu Oct 8 03:23:55 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by phemmer** [comment]
Your error indicates you are using the systemd `EnvironmentFile` unit file directive. The systemd [`docker.service` file provided by docker](https://github.com/docker/docker/blob/master/contrib/init/systemd/docker.service) does not have this in it.
You must either be using the docker package provided by your distro and not the one from docker (in which case you should be contacting your distro's maintainers), or you're using a custom `docker.service`.

**Comment by thaJeztah** [comment]
Please refer to this page in the documentation, describing how to customize daemon options with SystemD http://docs.docker.com/articles/systemd/#custom-docker-daemon-options

**Comment by ekuric** [comment]
@thaJeztah @phemmer thank you. I will sort this using distro docs. Sorry for noise.
