### ISSUE TITLE
Adding line information in the parsed dockerfile

### ISSUE THREAD

**Issue by perhapszzy** [docker/docker#17596]
I'm writing an application that analyzes the dockerfile and I want to add the line number information to the parsed dockerfile at:

https://github.com/docker/docker/blob/master/builder/dockerfile/parser/parser.go#L26

Basically I only need to add two fields (i.e. starting line and ending line) in the Node struct, can I push this change to the main repo? I think this information should be useful for all others who want take a deeper understanding about the dockerfile.

I have already made the change (delta < 7 lines), if you think it's fine to merge this with the main repo, I'll create a pull request.

Thanks

**Comment by duglin** [comment]
Seems harmless to me.  @tiborvass what do you think?

**Comment by perhapszzy** [comment]
Thanks for confirming. I have created a pr for this.
