### ISSUE TITLE
docker does not work after install on 10.8.5

### ISSUE THREAD

**Issue by tommyjcarpenter** [docker/docker#17597]
When I install Docker from scratch onto OS X 10.8.5, using 1.8.3 Toolkit, it tells me to upgrade my default machine by running `docker-machine upgrade default`.  That does not work, as seen below:

```
tommy-mbp:~ tcarpent$ docker-machine upgrade default
Error: machine must be running to upgrade.
tommy-mbp:~ tcarpent$ docker-machine start default
Error setting up host only network on machine start: exit status 1
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
tommy-mbp:~ tcarpent$ docker-machine env default
default is not running. Please start this with docker-machine start default
tommy-mbp:~ tcarpent$ 
```

I went and blew away that default machine

`rm -rf .docker/machine/machines/defualt`

Then reinstalled the toolkit. This time I get slightly farther, but still no luck:

```
tommy-mbp:~ tcarpent$ bash --login '/Applications/Docker/Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh'
Machine default already exists in VirtualBox.
Starting machine default...
Error setting up host only network on machine start: exit status 1
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
Setting environment variables for machine default...


                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/

host is not running
docker is configured to use the default machine with IP 
For help getting started, check out the docs at https://docs.docker.com
default is not running. Please start this with docker-machine start default
tommy-mbp:~ tcarpent$ docker-machine start default
Error setting up host only network on machine start: exit status 1
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command
```

In another thread I read about the env command, but it does not help either:

```
tommy-mbp:~ tcarpent$ docker-machine start default
Error setting up host only network on machine start: exit status 1
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
tommy-mbp:~ tcarpent$ eval "$(docker-machine env default)"
default is not running. Please start this with docker-machine start default
tommy-mbp:~ tcarpent$ docker-machine start default
Error setting up host only network on machine start: exit status 1
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
```

I used to have boot2docker running, but now it does not even let me run that saying that it is deprecated and that docker-machine must be used instead.

**Comment by calavera** [comment]
Please, feel free to open this issue again with further information if you didn't solve the issue already. Thanks.

**Comment by Fredjet** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  fredjet15@gmail.com
    Domain ventureacceleration.com has exceeded the max emails per hour (53/50 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:55663 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by eaglepeak.ovasp.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1abczg-0000WH-7p
	for fred@ventureacceleration.com; Thu, 03 Mar 2016 18:49:20 -0500
Date: Thu, 03 Mar 2016 15:48:39 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457048919;
	bh=AnCv04jqgtcoTskvJlNRJozwJe1a7NowudCoOLKuELQ=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=iUEh1ezYrCUcM0WywdiQYHfMxbXwjjsZLI8IkJIXg18sX0uzqB+OeRBt2JAGjgxZ5
	 dXrTZvmVHrt6OaDFWjfJHpoeNOsd3kZXDMCgYcBYt9rEK/P7g2TKrE4pw0+5EarbLe
	 ykGxfYSf+3ir9Y6Jquo2cOwQtEGkCohIWkXOdbm0=

**Comment by Fredjet** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  fredjet15@gmail.com
    Domain ventureacceleration.com has exceeded the max emails per hour (54/50 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o6.sgmail.github.com ([192.254.113.101]:32232)
	by eaglepeak.ovasp.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <bounces+848413-c2da-fred=ventureacceleration.com@sgmail.github.com>)
	id 1abczx-0000WM-3H
	for fred@ventureacceleration.com; Thu, 03 Mar 2016 18:49:39 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=zYt+fOqvJvh7j0EnX6s8acAkqhM=; b=HmVXVW9PdVsI9po6
	AIGcAEF1XcbQttvMQ3eg5oELO1aJ10K3zJULc/AmZpW0PjOSbxKxO8S5Ifm85i8y
	lRYxq8dZAdIHmKV5HBrSM9oUdjpJc557dgtpdEtyTloAv72N3HXiGTKyMhv3VCot
	J6V4BjIccvC/i+0fanq4T4Mp0VQ=
Received: by filter0663p1mdw1.sendgrid.net with SMTP id filter0663p1mdw1.15893.56D8CD5FF
        2016-03-03 23:48:47.072286592 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0001p1iad1.sendgrid.net (SG) with ESMTP id FPDLjZunSB2raUWV4pKv-Q
	for <fred@ventureacceleration.com>; Thu, 03 Mar 2016 23:48:47.251 +0000 (UTC)
Date: Thu, 03 Mar 2016 15:48:39 -0800
