### ISSUE TITLE
[1.9.0-rc4] Can't survive a hard reboot

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#17618]
This has been a long standing issue with Docker but I haven't pushed on it because it didn't seem to happen very often.  With 1.9 it has gotten much worse and happens quite easily.

Docker writes a lot of little json files but it seems to do it in a way that is not very safe and has the ability to create zero bytes files quite easily.  On start Docker will attempt to read the 0 byte file and fail and then the daemon won't start.  Again in 1.8 this wasn't very often, in 1.9 it's is quite common that I see this.

Here is my scenario:

1. Start RancherOS VM from a clean disk image (using KVM)
2. Once booted run `docker run -itd busybox`
3. Kill VM
4. Next start Docker daemon will refused to start.  The error is below

```
time="2015-11-02T18:12:08.919123488Z" level=info msg="API listen on /var/run/docker.sock" 
time="2015-11-02T18:12:08.922337393Z" level=fatal msg="Error starting daemon: EOF" 
```

Looking at `/var/lib/docker` I have the following zero byte files

```
/var/lib/docker/graph/039b63dd2cbaa10d6015ea574392530571ed8d7b174090f032211285a71881d0/tar-data.json.gz
/var/lib/docker/graph/039b63dd2cbaa10d6015ea574392530571ed8d7b174090f032211285a71881d0/json
/var/lib/docker/graph/039b63dd2cbaa10d6015ea574392530571ed8d7b174090f032211285a71881d0/layersize
/var/lib/docker/graph/039b63dd2cbaa10d6015ea574392530571ed8d7b174090f032211285a71881d0/checksum
/var/lib/docker/graph/039b63dd2cbaa10d6015ea574392530571ed8d7b174090f032211285a71881d0/v1Compatibility
/var/lib/docker/graph/c51f86c283408d1749d066333f7acd5d33b053b003a61ff6a7b36819ddcbc7b7/tar-data.json.gz
/var/lib/docker/graph/c51f86c283408d1749d066333f7acd5d33b053b003a61ff6a7b36819ddcbc7b7/json
/var/lib/docker/graph/c51f86c283408d1749d066333f7acd5d33b053b003a61ff6a7b36819ddcbc7b7/layersize
/var/lib/docker/graph/c51f86c283408d1749d066333f7acd5d33b053b003a61ff6a7b36819ddcbc7b7/checksum
/var/lib/docker/graph/c51f86c283408d1749d066333f7acd5d33b053b003a61ff6a7b36819ddcbc7b7/v1Compatibility
/var/lib/docker/containers/14c8e08438701d5143073531e81a273bc50b899469e5fe5558e45a2a4d8eae71/14c8e08438701d5143073531e81a273bc50b899469e5fe5558e45a2a4d8eae71-json.log
/var/lib/docker/containers/14c8e08438701d5143073531e81a273bc50b899469e5fe5558e45a2a4d8eae71/hostname
```

This exact scenario in 1.8 does not fail.  I don't know exactly what file is being read that is failing, but again this is very easy to reproduce and fails the Docker daemon from starting.

It would seem to me that docker needs to write to a temp file and then rename to dest to avoid these 0 byte file issues.

**Comment by ibuildthecloud** [comment]
Updating with debug logs from the daemon.  Not a lot of more info.

```
time="2015-11-02T18:33:54.326644194Z" level=debug msg="docker group found. gid: 1101" 
time="2015-11-02T18:33:54.326690696Z" level=debug msg="Server created for HTTP on unix (/var/run/docker.sock)" 
time="2015-11-02T18:33:54.326909217Z" level=debug msg="[graphdriver] trying provided driver \"overlay\"" 
time="2015-11-02T18:33:54.326930705Z" level=info msg="API listen on /var/run/docker.sock" 
time="2015-11-02T18:33:54.329241329Z" level=debug msg="Using graph driver overlay" 
time="2015-11-02T18:33:54.329265215Z" level=debug msg="Using default logging driver json-file" 
time="2015-11-02T18:33:54.329279309Z" level=debug msg="Creating images graph" 
time="2015-11-02T18:33:54.329357032Z" level=debug msg="Cleaning up old shm/mqueue mounts: start." 
time="2015-11-02T18:33:54.329406659Z" level=fatal msg="Error starting daemon: EOF" 
```

**Comment by runcom** [comment]
I know what's this

**Comment by runcom** [comment]
And I actually improved the log here https://github.com/docker/docker/pull/17605

**Comment by runcom** [comment]
And I was suggesting (as @crosbymichael on IRC) to not prevent daemon startup

**Comment by ibuildthecloud** [comment]
@runcom I'll try this patch so see if it's the same issue I'm hitting

**Comment by runcom** [comment]
I'm making a PR to not prevent the daemon from starting if there are 0 byte files under graph
