### ISSUE TITLE
Docker stuck when I run "docker pull" 

### ISSUE THREAD

**Issue by xDinomode** [docker/docker#17622]
![dockerissue](https://cloud.githubusercontent.com/assets/12665713/10890778/91b204e0-815f-11e5-8a13-274baca6e64b.png)

**Comment by xDinomode** [comment]
It's been over half an hour and it's still stuck at pull complete!!

**Comment by cpuguy83** [comment]
See http://www.fixedbyvonnie.com/2014/09/heck-virtualbox-guru-meditation-error/ which explains this mode.
This is not a docker issue, so closing.
