### ISSUE TITLE
Proposal: docker-build flag that displays only the image ID

### ISSUE THREAD

**Issue by ripcurld00d** [docker/docker#17623]
Hi,

As @duglin suggested to me on the IRC, I am posting a proposal to get only the image id from the `docker build` command.
(Inspired by #7727)

The `-q` flag just suppresses the verbose output generated by the containers.
I would like to add another flag that suppresses the verbose output of the daemon and will display the image ID at the end. However, If the build of the image isn't succeeded,  an error message will be shown instead.

As mentioned in #7727, this kind of output is very useful, when using docker-build within a Bash script.

Thanks.

**Comment by thaJeztah** [comment]
I think it makes sense, so +1 from me, but let other maintainers have a say as well :)

**Comment by ripcurld00d** [comment]
@thaJeztah - thanks.

I have already implemented this, but I am waiting for @duglin to review it (#17428)
