### ISSUE TITLE
layers get re uploaded

### ISSUE THREAD

**Issue by Juanchimienti** [docker/docker#17648]
Hi, I'm hitting a bug where i push the same image twice to the registry and I get layers re uploaded since they get a 404 from the docker registry.

Building and registry version:
docker -v
Docker version 1.7.1, build 786b29d/1.7.1

I attach the Dockerfiles and the script I'm using to build and push.

docker run -d -p 5000:5000 --restart=always --name registry -v /opt/docker/certs:/certs -v /opt/docker/data:/var/lib/registry -v /opt/docker/auth:/auth -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key -e REGISTRY_AUTH=htpasswd registry:2

Registry log:
time="2015-11-02T11:16:53Z" level=error msg="response completed with error" auth.user.name=autobot err.code="BLOB_UNKNOWN" err.detail=sha256:2607274acb71aaabc54f3c0c2cf34f8228636f0c2b6465755b17a42d7c955ff8 err.message="blob unknown to registry" http.request.host="192.168.80.3:5000" http.request.id=f385373a-7b6f-46d5-bc34-212cba007e38 http.request.method=HEAD http.request.remoteaddr="192.168.80.247:5496" http.request.uri="/v2/taringa_base_php/blobs/sha256:2607274acb71aaabc54f3c0c2cf34f8228636f0c2b6465755b17a42d7c955ff8" http.request.useragent="docker/1.7.1 go/go1.4.2 kernel/2.6.32-573.7.1.el6.x86_64 os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=6.635495ms http.response.status=404 http.response.written=157 instance.id=a634580a-1388-4f10-b624-309e4aeadb3d vars.digest="sha256:2607274acb71aaabc54f3c0c2cf34f8228636f0c2b6465755b17a42d7c955ff8" vars.name="taringa_base_php" version=v2.1.1 
192.168.80.247 - - [02/Nov/2015:11:16:53 +0000] "HEAD /v2/taringa_base_php/blobs/sha256:2607274acb71aaabc54f3c0c2cf34f8228636f0c2b6465755b17a42d7c955ff8 HTTP/1.1" 404 157 "" "docker/1.7.1 go/go1.4.2 kernel/2.6.32-573.7.1.el6.x86_64 os/linux arch/amd64"

+ REGISTRY=192.168.80.3:5000
+ IMAGES='taringa_base
taringa_base_nginx
taringa_base_php'
+ for IMAGE in '${IMAGES}'
+ docker build -t taringa_base taringa_base
Sending build context to Docker daemon 2.048 kB
Sending build context to Docker daemon 
Step 0 : FROM centos:centos6
 ---> 3bbbf0aca359
Step 1 : RUN yum -y install "http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm"
 ---> Using cache
 ---> fab9afbebec5
Step 2 : RUN yum -y install "http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm"
 ---> Using cache
 ---> 86ecac389f5f
Step 3 : RUN yum install -y python-setuptools python-meld3 	&& easy_install pip
 ---> Using cache
 ---> 8345d756cee9
Step 4 : RUN pip install supervisor
 ---> Using cache
 ---> 9c98fed78644
Step 5 : CMD supervisord -n
 ---> Using cache
 ---> 4e7f6d56ff46
Successfully built 4e7f6d56ff46
+ for IMAGE in '${IMAGES}'
+ docker build -t taringa_base_nginx taringa_base_nginx
Sending build context to Docker daemon 2.048 kB
Sending build context to Docker daemon 
Step 0 : FROM taringa_base
 ---> 4e7f6d56ff46
Step 1 : RUN yum --disableplugin=fastestmirror install -y 	curl 	gcc 	GeoIP 	GeoIP-devel 	openssl-devel 	patch 	pcre-devel 	tar
 ---> Using cache
 ---> 4ceb48f326a7
Step 2 : EXPOSE 8080
 ---> Using cache
 ---> 53cc1a878804
Successfully built 53cc1a878804
+ for IMAGE in '${IMAGES}'
+ docker build -t taringa_base_php taringa_base_php
Sending build context to Docker daemon 2.048 kB
Sending build context to Docker daemon 
Step 0 : FROM taringa_base_nginx
 ---> 53cc1a878804
Step 1 : RUN yum -y install "http://rpms.famillecollet.com/enterprise/remi-release-6.rpm"
 ---> Using cache
 ---> 3f662e98f33b
Successfully built 3f662e98f33b
+ docker login -u autobot -p password -e user@domain 192.168.80.3:5000
WARNING: login credentials saved in /var/lib/jenkins/.docker/config.json
Login Succeeded
+ for IMAGE in '${IMAGES}'
+ docker tag -f taringa_base 192.168.80.3:5000/taringa_base
+ docker push 192.168.80.3:5000/taringa_base
The push refers to a repository [192.168.80.3:5000/taringa_base] (len: 1)
4e7f6d56ff46: Image already exists
4e7f6d56ff46: Image already exists
9c98fed78644: Image already exists
8345d756cee9: Buffering to Disk
8345d756cee9: Image successfully pushed
86ecac389f5f: Image already exists
fab9afbebec5: Image already exists
3bbbf0aca359: Image already exists
fea77d2fd61e: Image already exists
91e6f84b8fe8: Image already exists
2c2557968d48: Image already exists
47d44cb6f252: Image already exists
Digest: sha256:f9bb4c341f02deb58f8d3a41911e65c7b804d70e025b6b3ca824d8901bfcf0ce
+ for IMAGE in '${IMAGES}'
+ docker tag -f taringa_base_nginx 192.168.80.3:5000/taringa_base_nginx
+ docker push 192.168.80.3:5000/taringa_base_nginx
The push refers to a repository [192.168.80.3:5000/taringa_base_nginx] (len: 1)
53cc1a878804: Image already exists
53cc1a878804: Image already exists
4ceb48f326a7: Buffering to Disk
4ceb48f326a7: Image successfully pushed
4e7f6d56ff46: Image already exists
9c98fed78644: Image already exists
8345d756cee9: Buffering to Disk
8345d756cee9: Image successfully pushed
86ecac389f5f: Image already exists
fab9afbebec5: Image already exists
3bbbf0aca359: Image already exists
fea77d2fd61e: Image already exists
91e6f84b8fe8: Image already exists
2c2557968d48: Image already exists
47d44cb6f252: Image already exists
Digest: sha256:e87d7dad819d7539a3b5b577ecb5b9d041f3b08453bfdbec1d76e098b81ce452
+ for IMAGE in '${IMAGES}'
+ docker tag -f taringa_base_php 192.168.80.3:5000/taringa_base_php
+ docker push 192.168.80.3:5000/taringa_base_php
The push refers to a repository [192.168.80.3:5000/taringa_base_php] (len: 1)
3f662e98f33b: Image already exists
3f662e98f33b: Image already exists
53cc1a878804: Image already exists
4ceb48f326a7: Buffering to Disk
4ceb48f326a7: Image successfully pushed
4e7f6d56ff46: Image already exists
9c98fed78644: Image already exists
8345d756cee9: Image already exists
86ecac389f5f: Image already exists
fab9afbebec5: Image already exists
3bbbf0aca359: Image already exists
fea77d2fd61e: Image already exists
91e6f84b8fe8: Image already exists
2c2557968d48: Image already exists
47d44cb6f252: Image already exists
Digest: sha256:dc1ef52e328ff27fecd37bbaf7c929eaf5fa7c6ee693a874cd6761e2add3e727

**Comment by dmcgowan** [comment]
While we don't currently guarantee that re-uploads will not happen, this issue has been largely mitigated in 1.8 by storing metadata which can be used to reproduce a same upload content. If you still have issues with 1.8+ please re-open up the issue so we can attempt to reproduce test cases around this.  Thanks for your report.
