### ISSUE TITLE
 Docker Remote api version 1.19 pull request not returning a valid json

### ISSUE THREAD

**Issue by kamaljeetrathi** [docker/docker#17643]
Hi ,
I am using docker remote api version 1.19 and using below request to pull image. 
POST /images/create?fromImage=ubuntu HTTP/1.1

Above request have Content-Type: application/json but it is not returning a valid json.
In case of wrong image it return 
{"status":"Pulling repository docker.io/library/cento"}
{"errorDetail":{"message":"Error while pulling image: Get https://index.docker.io/v1/repositories/library/cento/images: dial tcp: lookup index.docker.io: no such host"},"error":"Error while pulling image: Get https://index.docker.io/v1/repositories/library/cento/images: dial tcp: lookup index.docker.io: no such host"}

which is not a valid json so i am unable to send the proper response.

**Comment by kamaljeetrathi** [comment]
1.docker version:
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:37:18 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:37:18 UTC 2015
 OS/Arch:      linux/amd64

2.docker info:
Containers: 169
Images: 240
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 578
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-66-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 7.68 GiB
Name: uranus
ID: RJFK:S2F2:GPDM:2MVQ:4N5H:26X5:7KDH:NNAF:PHSH:QCEC:6CSD:X3LE
Username: kamaljeet
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

3.uname -a:
Linux uranus 3.13.0-66-generic #108-Ubuntu SMP Wed Oct 7 15:20:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

4.Environment:
Both docker server and client on my local machine

I am using okhttp client for POST request

Request getRequest = new Request.Builder()
		.url("http://hostname:2376/images/create?fromImage=debian:latest")
		.post(requestBody).build();
		Response getResponse = client.newCall(getRequest).execute();
ResponseBody realResponse = getResponse.body();
System.out.println("real response"+realResponse.string());



Actual Results:

{"status":"Pulling repository docker.io/library/cento"}
{"errorDetail":{"message":"Error while pulling image: Get https://index.docker.io/v1/repositories/library/cento/images: dial tcp: lookup index.docker.io: no such host"},"error":"Error while pulling image: Get https://index.docker.io/v1/repositories/library/cento/images: dial tcp: lookup index.docker.io: no such host"}


Expected Results:
Above json but valid,it is giving only {"status":"Pulling repository docker.io/library/cento"}
rest part is not printed if printed as json because of invalid json 

It misses comma between two json

**Comment by phemmer** [comment]
That actually is a valid response. It's called [JSON streaming](https://en.wikipedia.org/wiki/JSON_Streaming).

Though the API docs don't seem to mention that a stream can be sent back. So I'd say the fix here is to update the docs.

**Comment by thaJeztah** [comment]
Yup, agreed. Added a "docs" label.

@kamaljeetrathi are you interested in creating a pull request to clarify this in the documentation? The Markdown files used to generate the documentation can be found in this repository, and are located in this directory: https://github.com/docker/docker/tree/master/docs/reference/api

**Comment by koyadume** [comment]
Main problem here is that docker Remote API returns same value (application/json) for ```Content-Type``` header irrespective of whether its normal json or streaming json. This creates problem as most of the json parsers will try to parse streaming json assuming it to be normal json which will not work.

Right now I maintain a list of Remote API endpoints which returns streaming json. So whenever I invoke an endpoint from this list, my json parser uses a special logic to handle the response. However I need to update my list with every new release of Remote API.

Ideally docker should use a different value for ```Content-Type``` header wherever response is not normal json (e.g. /images/create, /build etc). This way a client will be able to parse json correctly.

**Comment by kamaljeetrathi** [comment]
Thanks @phemmer for guiding me now I am using JsonStreamParser for getting both json object

**Comment by thaJeztah** [comment]
@koyadume at some point some endpoints returned an `application/x-json-stream` (see https://github.com/docker/docker/pull/8101), but that was later reverted (https://github.com/docker/docker/pull/8482) because it broke some clients
