### ISSUE TITLE
Fail to Mount data volume from a ramdisk location

### ISSUE THREAD

**Issue by stanleyxu2005** [docker/docker#17644]
Docker Version: 1.8.3
Docker info:
```
Containers: 1
Images: 26
Storage Driver: devicemapper
 Pool Name: docker-8:1-11010765-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 482.5 MB
 Data Space Total: 107.4 GB
 Data Space Available: 66.89 GB
 Metadata Space Used: 1.421 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.95-RHEL6 (2015-09-08)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.18.21-16.el6.x86_64
Operating System: <unknown>
CPUs: 48
Total Memory: 252.4 GiB
Name: node22
ID: WJB7:IVVA:WJSK:63ML:I7PI:5R5B:LWFW:JIL4:7MEO:6A35:HYCC:BHTC
WARNING: No swap limit support
```
Linux Information: `Linux node22 3.18.21-16.el6.x86_64 #1 SMP Sat Sep 26 01:24:19 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

==================== CONCRETE ISSUE =================

I've created a simple Docker file
```
FROM errordeveloper/oracle-jre
ENTRYPOINT ping somewhere
```
And then I run the container with
```
mount -t tmpfs -o size=4G tmpfs /path/to/ramdisk
docker run -d --name test -v /path/to/ramdisk:/proj my_docker_container
```
I tried to check the mount point with
```
docker exec test ls /proj
```
The directory is empty. But if I mount to normal disk path, e.g. `-v /tmp:/proj`, I can see all files in `/proj`.

Is this a bug? I have tested with 

1. Docker 1.8.3 on CentOS 7 and 
2. Docker 1.7.1 on CentOS 6.5

**Comment by cpuguy83** [comment]
If you restart docker after the mount is created, does it work?

**Comment by phemmer** [comment]
> And then I run the container with
```
mount -t tmpfs -o size=4G tmpfs /path/to/ramdisk
docker run -d --name test -v /path/to/ramdisk:/proj my_docker_container
```
...
The directory is empty

Just to be sure, you have an intermediary step in there where you're putting something in the directory right? As a freshly mounted tmpfs directory is going to be empty.

**Comment by stanleyxu2005** [comment]
@cpuguy83 using `docker restart test` doesn't help.

@phemmer the directory `/path/to/ramdisk` has files and sub-directories. It is actually my source code repository checked out from github. Today i did a same test again, the mounted directory `/proj` shows one sub-directory. Expected result should be like this:
```
/proj/file_a
/proj/file_b
/proj/dir_1/dir_1/file_a
/proj/dir_1/file_a
/proj/dir_2/file_b
```
The actual result (also differ from the original bug report) is
```
/proj/dir_1/dir_1
```

**Comment by cpuguy83** [comment]
Not restart the container, restart the docker daemon.

**Comment by stanleyxu2005** [comment]
@cpuguy83 Oh, yes. This helps. Magic!

**Comment by cpuguy83** [comment]
@stanleyxu2005 Can you check your init script for docker?
Can you paste it in a gist?

**Comment by stanleyxu2005** [comment]
@cpuguy83 For the container, the `Dockerfile` is posted in the question, Do you mean some script for the docker server? Where is the init script you mentioned?

**Comment by phemmer** [comment]
If you're seeing different content in `/proj` when inside a docker container, and when outside it, and restarting the docker daemon fixes the issue, then it sounds like something is getting mounted on top of your root filesystem after docker starts.

**Comment by cpuguy83** [comment]
Or docker is either being started in it's own mount namespace or with "private" as a mount flag.

**Comment by phemmer** [comment]
True. Hadn't considered something other than docker might be doing namespacing :-)

**Comment by stanleyxu2005** [comment]
Thanks. Possible. So I close the issue.
