### ISSUE TITLE
Faied to connect to the Docker daemon

### ISSUE THREAD

**Issue by wenchma** [docker/docker#17645]
Description of problem:

After install docker by running `curl -sSL https://test.docker.com/ | sh` , and `DOCKER_HOST` environment variable is not set in my shell, run docker cmd, but return :
$ docker ps
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
$ service docker status
docker start/running, process 28966

`docker version` :

    Client:
     Version:      1.9.0-rc5
     API version:  1.21
     Go version:   go1.4.2
     Git commit:   9318004
     Built:        Tue Nov  3 05:59:27 UTC 2015
     OS/Arch:      linux/amd64
    Cannot connect to the Docker daemon. Is the docker daemon running on this host?

`docker info` :

    Cannot connect to the Docker daemon. Is the docker daemon running on this host?

`uname -a` :

    Linux docker 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):OpenStack Cloud instance

Actual Results: docker daemon cannot work 

Expected Results: docker daemon can work Ok

**Comment by Skarlso** [comment]
Could you please try running

```bash
sudo su -
service docker start
docker images
```
See if that works. And if it does, please add your user to the docker user group like this =>
```bash
sudo usermod -aG docker <username>
```

**Comment by wenchma** [comment]
@Skarlso ,  I did "sudo usermod -aG docker ubuntu" , but not log out and back in to take effect. :smile:

**Comment by Skarlso** [comment]
Hah, I couldn't count on one hand how many times that happened to me as well. :D :+1:

**Comment by ceritium** [comment]
Try with

`sudo gpasswd -a ${USER} docker`

**Comment by lordnynex** [comment]
To anyone who stumbles across this issue in the future. 

I just spent a bit of time debugging this issue in a few of my servers. I now realize ssh ControlPersist multiplexing makes the whole 'log out log back in' thing not work the way you think it does. It makes sense why this happens, I just never thought about it happening like this before. 

To fix this

```bash
$ ssh -O check -S ~/.ssh/mux-user@server.com server.com
Master running (pid=14920)
$ ssh -O stop -S ~/.ssh/mux-user@server.com server.com
Stop listening request sent.
```

Then log back into your server.

**Comment by kikiya** [comment]
I'm having the same problem but neither of the solutions provided worked. 
```
service docker status

Redirecting to /bin/systemctl status  docker.service

● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: active (running) since Wed 2015-12-16 18:19:56 EST; 17h ago
     Docs: https://docs.docker.com
 Main PID: 5181 (docker)
   Memory: 2.3M
   CGroup: /system.slice/docker.service
           └─5181 /usr/bin/docker daemon -H fd://
```
When I try to execute other commands, it shows "cannot connect to the docker daemon"
```
# docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```
Has any one tried other troubleshooting? I'm running redhat/softlayer.

**Comment by kikiya** [comment]
Solved by manually starting the daemon. For some reason, the service is not actually starting it. 

ran ` docker daemon &` and now it's working fine. will have to investigate further to see why the service is not fully starting it.

**Comment by fflatorre** [comment]
We got exactly the same issue. Also for us "/usr/boin/docker -d" worked but we'd much prefer to be fixed when restarting via upstart.

**Comment by bhaumikwork** [comment]
thanks @Skarlso

**Comment by xecronix** [comment]
On Fedora 22

Installing Docker: 
$> curl -fsSL https://get.docker.com/ | sh

After installing Docker:

A user needs to be added to the docker group.
$> sudo usermod -aG docker <username>

The docker daemon needs to be started
$> sudo service docker start

You can set the daemon to start at boot
$> sudo chkconfig docker on

You can verify the docker service is running
$> service docker status

And one last final check
$> docker run hello-world

**Comment by ackris** [comment]
The issue is neatly documented in Docker Documentation. 

My environment:
VirtualBox

OS: CentOS-7 -x86_64-Minimal

[](https://docs.docker.com/engine/installation/linux/centos/ )

After adding user to the group, execute the following command. 

`sudo chkconfig docker on`

At first, I couldn't view the server config details on the execution of `docker version` , and I received the same error "Cannot connect to the Docker daemon. Is the docker daemon running on this host?"

After executing `sudo chkconfig docker on` , everything works super fine :)

**Comment by hopeseekr** [comment]
On the latest Arch Linux, the only way I can get docker to work is to 

`sudo systemctl stop docker`
`sudo docker daemon &`

Then it works appropriately.

**Comment by thaJeztah** [comment]
@hopeseekr was that an upgrade from an existing installation, or a fresh install? Anything in the logs? Any modifications you made to the systemd unit file?

**Comment by hopeseekr** [comment]
Fresh install on a new Arch Linux install that I setup yesterday.  I don't see any docker-specific log files in `/var/log`.

**Comment by hopeseekr** [comment]
I actually absolutely hate systemd, and I have NO IDEA how to debug or even look at what commands a systemd service actually runs. God! I miss OpenRC so much!

**Comment by thaJeztah** [comment]
@hopeseekr haha 🙊 

you can probably get some information from `sudo systemctl status docker` and `journalctl -xe -u docker`. Did you use the package from our apt repositories or the arch-linux repos?

**Comment by hopeseekr** [comment]
Yes, I used the official `packman -S docker` route. 

After a fresh reboot:
```
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabl
   Active: active (running) since Tue 2016-05-24 09:28:34 CDT; 12s ago
     Docs: https://docs.docker.com
 Main PID: 7302 (docker)
    Tasks: 19 (limit: 512)
   Memory: 15.4M
      CPU: 134ms
   CGroup: /system.slice/docker.service
           ├─7302 /usr/bin/docker daemon -H fd://
           └─7308 docker-containerd -l /var/run/docker/libcontainerd/docker-containerd.so

May 24 09:28:34 libran docker[7302]: time="2016-05-24T09:28:34.277017655-05:00" level=inf
May 24 09:28:34 libran docker[7302]: time="2016-05-24T09:28:34.289658653-05:00" level=inf
May 24 09:28:34 libran docker[7302]: time="2016-05-24T09:28:34.295186622-05:00" level=inf
May 24 09:28:34 libran docker[7302]: time="2016-05-24T09:28:34.341449086-05:00" level=inf
May 24 09:28:34 libran docker[7302]: time="2016-05-24T09:28:34.388887470-05:00" level=inf
May 24 09:28:34 libran docker[7302]: time="2016-05-24T09:28:34.389074804-05:00" level=inf
May 24 09:28:34 libran docker[7302]: time="2016-05-24T09:28:34.389156085-05:00" level=inf
May 24 09:28:34 libran docker[7302]: time="2016-05-24T09:28:34.389239746-05:00" level=inf
May 24 09:28:34 libran docker[7302]: time="2016-05-24T09:28:34.393658963-05:00" level=inf
May 24 09:28:34 libran systemd[1]: Started Docker Application Container Engine.
```

journalctl:
```
-- Subject: Unit docker.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has begun starting up.
May 24 09:28:33 libran docker[7302]: time="2016-05-24T09:28:33.271562128-05:00" level=inf
May 24 09:28:34 libran docker[7302]: time="2016-05-24T09:28:34.277017655-05:00" level=inf
May 24 09:28:34 libran docker[7302]: time="2016-05-24T09:28:34.289658653-05:00" level=inf
May 24 09:28:34 libran docker[7302]: time="2016-05-24T09:28:34.295186622-05:00" level=inf
May 24 09:28:34 libran docker[7302]: time="2016-05-24T09:28:34.341449086-05:00" level=inf
May 24 09:28:34 libran docker[7302]: time="2016-05-24T09:28:34.388887470-05:00" level=inf
May 24 09:28:34 libran docker[7302]: time="2016-05-24T09:28:34.389074804-05:00" level=inf
May 24 09:28:34 libran docker[7302]: time="2016-05-24T09:28:34.389156085-05:00" level=inf
May 24 09:28:34 libran docker[7302]: time="2016-05-24T09:28:34.389239746-05:00" level=inf
May 24 09:28:34 libran docker[7302]: time="2016-05-24T09:28:34.393658963-05:00" level=inf
May 24 09:28:34 libran systemd[1]: Started Docker Application Container Engine.
-- Subject: Unit docker.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has finished starting up.
-- 
-- The start-up result is done.
```

**Comment by thaJeztah** [comment]
> Yes, I used the official packman -S docker route.

Yes, those are packages maintained and supported by arch linux; it's possible that they ship with different options and configuration.

From the output you gave, it looks like there's something incorrectly set in the systemd unit-file, or there's a `daemon.json` present somewhere; the daemon that's started through systemd is listening on 0.0.0.0:2375;

    API listen on 0.0.0.0:2375 

(note that that is a *dangerous* configuration, if your host is accessible from the internet; it gives unprotected access to the API through port 2375 of your computer)

When you start it manually, it's using the defaults, and correctly listening on a local socket only;

    INFO[0001] API listen on /var/run/docker.sock 

So;

- check if the systemd unit for docker has the right command-line options set for docker. you can see the unit-files we ship in the official packages here; https://github.com/docker/docker/tree/master/contrib/init/systemd
- it's possible there's a drop-in (override) file installed somewhere that overrides the default settings. see https://docs.docker.com/engine/admin/systemd/#custom-docker-daemon-options

**Comment by fayyazurrehman** [comment]
For ubuntu 14.04 on virtual box vm with docker installation

sudo groupadd docker
sudo gpasswd -a ${USER} docker
sudo service docker restart
Now, restart the OS. This solution is well explained here 
https://jee-appy.blogspot.com/2016/02/installing-docker-in-virtual-box.html

**Comment by doublebyte1** [comment]
I experiment the same issue on Ubuntu Xenial (and on the previous version on ubuntu).  Although the daemon is running, I cannot connect to it with my regular user (which is part of the docker group). Sometimes I restart, and it magically works! No idea why....

**Comment by jesseluo** [comment]
I got same issue on Cent OS 7 which I installed docker by yum. I tried all @xecronix mentioned here but still can't fix it.

At last I found I should run docker after sudo. The hint doesn't mean docker daemon isn't running...

**Comment by smelike** [comment]
I got the same issue in CentOS Linux release 7.2.1511 (Core)  which I installed by "https://get.docker.com/ | sh".  I tried "sudo docker daemon &", and the issue is fixed.

**Comment by doublebyte1** [comment]
In my case, if I check:
`sudo service docker status`
I can see the daemon is running. Running :
`sudo service docker restart`
Apparently solves the problem (I don't know why).

**Comment by NoviceF** [comment]
On ubuntu 14.04 for me workaround is not simply run docker (not service, but client) as sudo. Before run "docker run --rm busybox true", for example, move to sudo bash by typing "sudo su". In sudo bash docker is working fine.

**Comment by LeoWinterDE** [comment]
fully restart the os, not just logging out and back in. was the solution for me.

**Comment by LaharlMontogmmery** [comment]
The use group changes doesn't apply immediately when a user is added in a group (the user need to log off and log on again for the changes to apply), but it is better to just restart the OS.

**Comment by dandv** [comment]
@Skarlso: can you please add to your answer that the user must log out and back in for the solution to work? Thanks!

**Comment by Skarlso** [comment]
@dandv Done.

**Comment by dandv** [comment]
@Skarlso: awesome, thanks! I'll delete my now obsolete comments from this too-long thread.

**Comment by dandv** [comment]
@wenchma: can you please correct the typo in the title of this issue, so searches can find it more easily? Also, "but not log out and back in to take effect." -> "but had to log out and back in."

**Comment by Skarlso** [comment]
No problem man. :-) glad I could help out folks. :-)

**Comment by Devlopers** [comment]
On my latest Mac OSX Sierra, 
I also got the error, after I install Docker Toolbox, when I run docker on my terminal:
 
```
git:(master) ✗ docker version
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 17:00:50 2016
 OS/Arch:      darwin/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Comment by johshoff** [comment]
Based on the number of people giving a thumbs up to @Skarlso's comment about

    sudo usermod -aG docker <username>

maybe there should be check for that so you could say:

> You need to be in the 'docker' group

instead of the misleading advice

> Cannot connect to the Docker daemon. Is the docker daemon running on this host?

**Comment by thaJeztah** [comment]
@johshoff docker 1.13 will give a more informative error message if the client fails to connect due to permissions error; see this pull request; https://github.com/docker/docker/pull/26797

**Comment by Suncatcher** [comment]
I get on my AWS instance following stuff:

```
time="2017-02-01T12:34:46.999769865Z" level=info msg="libcontainerd: new containerd process, pid: 2737" 
time="2017-02-01T12:34:48.004600950Z" level=fatal msg="Error starting daemon: error initializing graphdriver: devicemapper: Non existing device docker-docker--pool" 
```

What should I do then?

P.S. [Full log](http://pastebin.com/BgEkrD4Q)

**Comment by Skarlso** [comment]
@Suncatcher This Issues is closed. If you have a problem, please open a new one.

**Comment by DrST** [comment]
Dear all, just in case this would happen to solve you issue ...

I did all the abode, but only running docker daemon in interactive mode solved my problem.
When running the daemon like this, I got the missing information:

> Error starting daemon: error initializing graphdriver: /var/lib/docker contains several valid graphdrivers: aufs, devicemapper; Please cleanup or explicitly choose storage driver (-s <DRIVER>)

Previously I was using the old docker from Ubuntu 14.04 and upgraded it using the official upstream docker repository...

After specifying the correct devince mapper (aufs) a lot of checks were performed for existing images and everything was fine afterwards.

I hope this will help others :-)

**Comment by Suncatcher** [comment]
What means  _running docker daemon in interactive mode_?
Could you please describe the exact steps you did?

**Comment by westy92** [comment]
Should we fix the typo in the issue name? *Failed

**Comment by Suncatcher** [comment]
> Should we fix the typo in the issue name? *Failed
Definitely!

**Comment by jpdonnell** [comment]
There underlying problem is the docker group isn't created ; so a usermod -G user docker will also fail

**Comment by Suncatcher** [comment]
Dunno where the problem is, but on standard Amazon linux Docker is installable like a charm, so I recommend to use standard. 
But to ship **ECS**-optimized Linux AMI (yes-yes, pay attention to these letters - it's container-optimized) - to ship it [without ability to being configured for Docker](https://github.com/docker/docker/issues/30631#issuecomment-278474854) is a bullshit!
It's simply a shit! *ucking Amazon is trying to make money from nowhere and it's frustrating.
Why the hell I have to be a DevOps-level to simply use Docker? They make me to buy their paid support plan, I see no other reason.

**Comment by soupault** [comment]
Had the same issue in AWS-hosted Archlinux.
Fixed via:
```
pacaur -S docker-machine
docker-machine env default
sudo systemctl start docker
```

**Comment by l-zhi** [comment]
centos 6.6 ,docker 1.7.1 
```bash
> yum install device-mapper-event-libs
> sudo service docker restart
```
it's worked for me

**Comment by sironitomas** [comment]
I had the same problem on Arch Linux (Docker package version:  1:17.03.1-1). I modified this on `/usr/lib/systemd/system/docker.service` and I got it working fine after that.
```
#ExecStart=/usr/bin/dockerd -H fd://
ExecStart=/usr/bin/dockerd
```

**Comment by RakeshMsr** [comment]
Just follow below steps to resolve the issue.

$:sudo groupadd docker 
$:sudo gpasswd -a ${USER} docker 
$:sudo service docker restart 
$:newgrp docker

**Comment by KingAndroid** [comment]
Thank you RakeshMsr.
You save my hard working and day.

**Comment by postarc** [comment]
Type:
$: dockerd
If you see a message: "Please upgrade your kernel to 3.10.0 or newer.", upgrade your linux kernel.
