### ISSUE TITLE
Client (docker push) appears not to respect /etc/hosts or work with subdomains (and manages to resolve and entry for example.com, wat)

### ISSUE THREAD

**Issue by waynew** [docker/docker#17656]
I'm running `Docker version 1.8.3, build f4bf5c7` on Mac OSX El Capitan.

I created a self-signed certificate and built me an image from this dockerfile:

    FROM registry

    COPY certs/ /certs/
    ENV REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt REGISTRY_HTTP_TLS_KEY=/certs/domain.key

Then I started my image from this `docker-compose.yml` (the extra env variables are in there because I didn't know if something was happening with the timing of the `ENV` from the dockerfile`):

    docker_hub:
        build: docker-hub
        ports:
            - "0.0.0.0:5000:5000"
        environment:
            REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
            REGISTRY_HTTP_TLS_KEY: /certs/domain.key

Now, do the following:

    docker pull busybox
    docker tag busybox example.com:5000/busybox

Then insert into `/etc/hosts` the output of `docker-machine ip default` pointing to `example.com`. I tried using `subdomain.mycompany.com` but that didn't work - it was resolving to `mycompany.com`'s IP address. So I tried `example.com`.

Well, that didn't work either. Not only did it not work, it actually resolved `example.com` to the ip address `93.184.216.34`, which apparently belongs to Edgecast?

---

# Edit/Solved?

So I discovered my issue as I was typing this - the `push` command doesn't run from *my* box, it runs from within the docker VM. I had to run `docker-machine ssh default` and then edit *its* `/etc/hosts`. Of course there I could just put `127.0.0.1 example.com` in as the entry. Doh!

Anyway, I'm not sure if there should be an annotation in the documentation to point that out. Or maybe I'm just the only one crazy enough to try such things :trollface:. In any case, at least now if someone is searching for `docker push subdomain` they might have a chance of finding *this* issue.

Feel free to close this issue if it's not worth adding anything to the docs, or let me know if I can help clarify anything! Thanks for making Docker so awesome :+1:

**Comment by thaJeztah** [comment]
Thanks for the update, I'll close this issue. I'm not sure we should mention this in the documentation, because we cannot cover every use case/issue. We're open to suggestions though, or a pull request to update the documentation :+1:
