### ISSUE TITLE
How do I connect to a server running inside a docker container?

### ISSUE THREAD

**Issue by xDinomode** [docker/docker#17668]
I've installed apache inside a docker cointainer that has an ubuntu image but I can't connect to the IP I'm given. I run the following command to start apache and I can curl to it inside the container but not from outside it. I know I'm supposed to set up port forwarding but none of the commands I've found have worked.

root@721809baa616:/# service apache2 start
 * Starting web server apache2        AH00558: apache2: Could not reliably deter
mine the server's fully qualified domain name, using 172.17.0.4. Set the 'Server
Name' directive globally to suppress this message
 *

**Comment by xDinomode** [comment]
Why does this dumb bot always comment ^

**Comment by aanm** [comment]
@xDinomode try `docker run -P yourimage` or, if you don't want to expose all ports try, `docker run -p 80:80`
The bot always comment because you didn't write what he asks, such as:
`docker version:`
`docker info:`
`uname -a:`

**Comment by cpuguy83** [comment]
Hello,

This is not really appropriate for GH issues, so I'm going to close it.
Please see #docker on IRC, docker-user mailing list, or forums.docker.com for questions.

To answer the question requires some extra information about your setup. Are you running on straight linux or are you going through OSX (and as such a VM). 

In general ip addresses should be accessible from the docker host, but not necessarily outside the docker host unless you've explicitly setup the routing to allow this.
You can publish a container port to the host, which effectively sets up a port forward (really a NAT) from the host port to the container port, and thus making the service accessible to anything that has access to the docker host address.
