### ISSUE TITLE
Use a non-successful exit code in https://get.docker.com/ubuntu/

### ISSUE THREAD

**Issue by philBrown** [docker/docker#17675]
Any chance you fine folks could add an `exit 1` or something similar to the now deprecated script at https://get.docker.com/ubuntu/.

At the moment, running

    curl -sSL https://get.docker.io/ubuntu|sh
    
doesn't result in an error so it was a little hard to catch in our automated system.

**Comment by thaJeztah** [comment]
ping @jfrazelle I think you were working on this?

**Comment by jfrazelle** [comment]
It should be there now

**Comment by jfrazelle** [comment]
Might have gotten overwritten on last release I can fix later

**Comment by jfrazelle** [comment]
This is fixed
