### ISSUE TITLE
Proposal: Use the newgrp and the id commands as an alternative way to the log-out-and-in step

### ISSUE THREAD

**Issue by ripcurld00d** [docker/docker#17679]
In the installation document at the `Create a docker group` part:

> 3 . Log out and log back in.
>      This ensures your user is running with the correct permissions.

IMHO, this step is not the only way to ensure "your user is running with the correct permissions".
Perhaps, one can run `id` and see whether he's listed on the `docker` group:

    $ id
    uid=13x(bshuster) gid=13x(bshuster) groups=13x(bshuster),10(wheel),981(docker) ...

In addition, you can use the `newgrp` command to change the group ID to docker during that login session.

    $ newgrp docker

Which saves time on the "log out and log back in" process.

Thanks.

**Comment by cpuguy83** [comment]
The problem with newgrp is I believe it puts you only in that new group and you end up dropping your  other groups (for that login).
Basically, it literally changes your current group.

**Comment by ripcurld00d** [comment]
@cpuguy83 -- you're right.
I just thought we could take away the "logout->login" redundancy by using it, but there are cases this will be a bad idea.

Thanks.
