### ISSUE TITLE
Update docs missing referrence to windows platform on Organize our issues page.

### ISSUE THREAD

**Issue by askb** [docker/docker#17684]
Just built the latest version of the docs and noticed minor update would be required to [Organize our issues page](http://docs.docker.com/opensource/ways/issues/) for missing reference to `Windows` platform. Jump to section ===> `How Do I triage ?`

```
kitematic/kitematic 	Kitematic is a simple application for managing Docker containers on Mac OS X.
```
should be replaced to 

```
kitematic/kitematic 	Kitematic is a simple application for managing Docker containers on Mac OS X and Windows.
```

**Comment by thaJeztah** [comment]
@askb Thanks! That page is actually in another repository; https://github.com/docker/opensource/blob/master/docs/ways/issues.md

are you interested in creating a PR there, or want us to do so?

**Comment by askb** [comment]
@thaJeztah - no worries, I can do it.  can this issue be closed ? :)

**Comment by thaJeztah** [comment]
@askb yes, the process is basically the same as working on docker; fork the repository, clone it to your local machine etc.

If you create a PR, you can even mention `closes https://github.com/docker/docker/issues/17684` and GitHub will close this issue when the PR is merged

**Comment by LK4D4** [comment]
This was fixed
