### ISSUE TITLE
apt warns about untrusted source on recent lxc-docker .deb update

### ISSUE THREAD

**Issue by mulander** [docker/docker#17681]
BUG REPORT INFORMATION

Use the commands below to provide key information from your environment:

docker version:
```
root@build:~# docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
root@build:~# 
```
docker info:
```
root@build:~# docker info
Containers: 3
Images: 18
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.5-x86_64-linode61
Operating System: Debian GNU/Linux 7 (wheezy)
CPUs: 4
Total Memory: 3.858 GiB
Name: build
ID: M3DG:JTLB:D7RX:2MY4:HEL7:I2KA:OFFS:DZCO:NYTG:TAQR:7WVM:FNIR
WARNING: No swap limit support
```
uname -a:
```
root@build:~# uname -a
Linux build 4.1.5-x86_64-linode61 #7 SMP Mon Aug 24 13:46:31 EDT 2015 x86_64 GNU/Linux
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):
Linode VPS.

List the steps to reproduce the issue:
1. Run aptitude safe-upgrade

Describe the results you received:

WARNING: untrusted versions of the following packages will be installed!

Untrusted packages could compromise your system's security.
You should only proceed with the installation if you are certain that
this is what you want to do.

  lxc-docker lxc-docker-1.9.0 

Describe the results you expected:

Upgraded packages without warnings

Provide additional info you think is important:

Hi,

Recently I started to notice a trust issue on my Debian servers. The official repository is generating warnings even though the official key was added.

```
root@build:~# wget -qO- https://get.docker.com/gpg | sudo apt-key add -
OK
root@build:~# aptitude safe-upgrade
Resolving dependencies...                
The following NEW packages will be installed:
  lxc-docker-1.9.0{a} 
The following packages will be REMOVED:
  lxc-docker-1.7.1{u} 
The following packages will be upgraded:
  lxc-docker 
1 packages upgraded, 1 newly installed, 1 to remove and 0 not upgraded.
Need to get 8487 kB of archives. After unpacking 13.9 MB will be used.
Do you want to continue? [Y/n/?] y
WARNING: untrusted versions of the following packages will be installed!

Untrusted packages could compromise your system's security.
You should only proceed with the installation if you are certain that
this is what you want to do.

  lxc-docker lxc-docker-1.9.0 

Do you want to ignore this warning and proceed anyway?
To continue, enter "Yes"; to abort, enter "No": No
Abort.
root@build:~# apt-cache policy lxc-docker
lxc-docker:
  Installed: 1.7.1
  Candidate: 1.9.0
  Version table:
     1.9.0 0
        500 https://get.docker.com/ubuntu/ docker/main amd64 Packages
 *** 1.7.1 0
        100 /var/lib/dpkg/status
root@build:~# 
```

Note that the key is present:

```
pub   2048R/A88D21E9 2013-08-16
uid                  Docker Release Tool (releasedocker) <docker@dotcloud.com>
```

Was there a signing issue for the 1.9.0 package?

----------END REPORT ---------

**Comment by thaJeztah** [comment]
Hm, the package for Ubuntu is now called `docker-engine`, not `lxc-docker`. Could you try the manual procedure, as described in http://docs.docker.com/engine/installation/ubuntulinux/ ?

**Comment by mulander** [comment]
Interesting. That page points to a completely different repository.

That's the one I had from my initial installation in the source list:
```
deb https://get.docker.com/ubuntu docker main
```

The new one points to:
```
deb https://apt.dockerproject.org/repo debian-wheezy main
```

I followed http://docs.docker.com/engine/installation/debian/#debian-wheezy-stable-7-x-64-bit to solve my issue.

One question remains though. Why suddenly the *old* repository served a new lxc-docker upgrade that wasn't properly signed?

**Comment by thaJeztah** [comment]
> One question remains though. Why suddenly the old repository served a new lxc-docker upgrade that wasn't properly signed?

Good question; @jfrazelle any ideas here?

**Comment by thaJeztah** [comment]
Alright, small update; first of all, the 1.9 release is indeed still published to the old repo's as well (I actually didn't know that was still the case), this is just to give users time to move to the new repositories, so it's advisable to migrate to the new repositories (apt.dockerproject.org) - 1.9 is the last release that will be published on the old repo.

We're currently looking into the signing issue; it's possibly a cache issue on a CDN, but its being investigated; see https://github.com/docker/docker/issues/12461#issuecomment-153758535 for more information

**Comment by mulander** [comment]
Thanks, closing this issue as my problem has been resolved and you guys seem to be on top the signing issue with a discussion at #12461.

**Comment by thaJeztah** [comment]
Thanks @mulander, and thanks for reporting!
