### ISSUE TITLE
"docker inspect -f dns" incompatibility between 1.8 and 1.9

### ISSUE THREAD

**Issue by bboreham** [docker/docker#17680]
As noted in #17026,

    docker inspect -f {{.HostConfig.Dns}} somecontainer

works in 1.8 (and earlier) and doesn't work in 1.9, while

    docker inspect -f {{.HostConfig.DNS}} somecontainer

works in 1.9 and doesn't work in 1.8.  

This is a pretty bad compatibility breakage for anyone with a script that fetches this setting.
Also I cannot see the change mentioned in the release notes.

**Comment by awh** [comment]
`DnsOptions` and `DnsSearch` are also affected; furthermore, 1.9 `docker inspect` still reports these values with the original 1.8 capitalisation.

**Comment by thaJeztah** [comment]
Hm possibly related to https://github.com/docker/docker/issues/15566, https://github.com/docker/docker/pull/15567 https://github.com/docker/docker/pull/17284

/cc @calavera

**Comment by thaJeztah** [comment]
oh, I see https://github.com/docker/docker/issues/17026 was mentioned in the description

**Comment by cpuguy83** [comment]
Thanks for reporting this.

**Comment by cpuguy83** [comment]
Tentatively adding to 1.9.1

**Comment by thaJeztah** [comment]
This should be fixed by https://github.com/docker/docker/issues/17779

Thanks again for reporting @bboreham @awh !

**Comment by bboreham** [comment]
The issue I meant to raise is that the case of the name changed, not how it behaves on an empty value.

So it is impossible to write a script inspecting the value (when it is non-empty) that works against both 1.8 and 1.9.

**Comment by thaJeztah** [comment]
@bboreham IIUC, https://github.com/docker/docker/pull/17779 should fix that; @calavera can you confirm? Just in case..

**Comment by bboreham** [comment]
My apologies; having tested again I see the problem only hits when the field is empty.

Looks fixed to me in 1.9.1, thanks!

**Comment by thaJeztah** [comment]
Thanks for testing @bboreham, good to hear it's fixed :+1:
