### ISSUE TITLE
Updates to "Get started with multi-host networking"

### ISSUE THREAD

**Issue by davidcurrie** [docker/docker#17706]
Just worked through the examples at https://docs.docker.com/engine/userguide/networking/get-started-overlay/ and have the following corrections/suggestions:

Step 2.2 - should this now just be --swarm-image="swarm" rather than --swarm-image="swarm:1.0.0-rc2" ?

Step 4 - given that constraints are specified, any reason why the docker run commands are targeted at the individual nodes rather than the swarm master?

Step 6.3 - doesn't indicate that the file needs to be in a directory called counter
Step 6.4 - specifies a node constraint that is not consistent with those created earlier in the article
Step 6.6 - has an extraneous 'up' after 'docker-compose' which is hard to diagnose from the usage instructions that you then get back given that the experimental option is not documented
Step 6.x - would be good to have a final step to browse to the app

**Comment by thaJeztah** [comment]
Thanks for the suggestions, @davidcurrie! Are you interested in contributing, and creating a pull request to make those changes? We're planning to release a 1.9.1 update soon and probably update the docs together with that. Would be great to have these fixes in that as well.

The markdown files used to generate that page can be found in this repository; https://github.com/docker/docker/tree/master/docs/userguide/networking

Let us know if you're interested!

**Comment by davidcurrie** [comment]
Looks like @nathanleclaire has already cleaned up 6.4/6.6 but I'll work up a PR for the remainder.

#dibs

**Comment by nathanleclaire** [comment]
`--swarm-image` can be taken out entirely in the examples since by default it will use `swarm:latest`.

**Comment by davidcurrie** [comment]
Thanks @nathanleclaire - PR updated to remove --swarm-image options.

**Comment by LK4D4** [comment]
Docs was updated.
