### ISSUE TITLE
1.9.0: TTY mode is broken on OS X

### ISSUE THREAD

**Issue by skozin** [docker/docker#17707]
Run `sleep 500` inside `ubuntu:latest` container with `--it` flags.

Press Enter.
    
* **Expected:** Cursor moves to a new line.
* **Actual:** `^M` is printed, cursor stays at the same line (run Bash instead of `sleep` to see why this behavior is undesired).

Now press `^C`.

* **Expected:** `SIGINT` is forwarded to container.
* **Actual:** client Docker process stops, leaving container running.

Logs:

```
$ docker run --name test --rm -it ubuntu sleep 500
^M^M^M^C

$ docker ps
CONTAINER ID   IMAGE    COMMAND        CREATED         STATUS         PORTS    NAMES
34c361b32fe4   ubuntu   "sleep 500"    5 seconds ago   Up 5 seconds            test
```

Without `-t` flag, `SIGINT` is forwarded correctly.

### Versions

* The issue is repoducible with Docker 1.9.0 server and 1.9.0/1.8.3 clients running under OS X.
* The issue is NOT repoducible with Docker clients running under Linux.
* The issue is NOT repoducible with Docker 1.8.2 server.

```
$ docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      darwin/386

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64

$ docker info
Containers: 16
Images: 193
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 225
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-15-generic
Operating System: Ubuntu 15.04
CPUs: 4
Total Memory: 3.856 GiB
Name: local-dev
ID: NHNL:65RX:7EKO:ALLG:7ZL7:MPQ3:KHVA:SXKI:F3YT:VZMD:VS22:V45T
Username: admin
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

$ uname -a (client)
Darwin sam-mbp.local 15.0.0 Darwin Kernel Version 15.0.0: Wed Aug 26 16:57:32 PDT 2015; root:xnu-3247.1.106~1/RELEASE_X86_64 x86_64

$ uname -a (server)
Linux local-dev 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by cpuguy83** [comment]
Not in front of my Mac right now, but "darwin/386" seems suspect.

**Comment by skozin** [comment]
Update: I tried to make fresh VM with Docker 1.8.3, and it exhibits the same issue. From which I conclude that something went wrong with my OS X.

**Comment by thaJeztah** [comment]
Looks like we still build a i386 version for OS X; the 64-bit version can be found here; https://get.docker.com/builds/Darwin/x86_64/docker-1.9.0

**Comment by skozin** [comment]
@cpuguy83, @thaJeztah, thank you very much! The issue was indeed caused by i386 version of Docker client (both 1.9.0 and 1.8.3). After installing 64-bit client everything started working as usual.

Apparently I somehow downloaded 1.9.0 client for darwin/i386 arch, and then used the same link (with changed version) to download 1.8.3 client after experiencing the issue.

Bottom line: 32-bit Docker client is broken on 64-bit OS X. Maybe this arch should be removed or there are some reasons to keep it?

**Comment by thaJeztah** [comment]
I actually don't know why it's still build (given that all OS X releases for the past 5+ years are 64-bit)

I'll check and see if we can remove those builds
