### ISSUE TITLE
Support partial IDs in `docker volume` commands

### ISSUE THREAD

**Issue by ndarilek** [docker/docker#17702]
I like how, when manipulating containers, I can type the first few non-colliding characters of the container's ID. This doesn't seem to be true for volumes. Could these also be matched in the same way that container/image IDs are? At the moment I have to cut-and-paste the entire volume ID, which is annoying.

Thanks.

**Comment by cpuguy83** [comment]
These aren't really id's, they are names as volumes don't have id's.
While with container ID's it's likely that the first few characters will guarantee uniqueness, with volume names it will not.
So it's not impossible... but...

**Comment by thaJeztah** [comment]
It could use the same UX as the other commands;

```bash
docker inspect 9
Error: No such image or container: 9

docker inspect 91
[
{
    "Id": "914c82c5a678cf9fa73c25d91d30f5e174ac69f6b494890d262cc58f43b304ef",
    "RepoTags": [
   ....
```

**Comment by LK4D4** [comment]
I can swear I saw similar issue today. Yes, I think it's possible and might be easier to do after cli rewriting. But might not worth it. I actually DON'T like that you can use prefixes and think it was a bad decision. Not for me to decide, though :)

**Comment by cpuguy83** [comment]
@LK4D4 Yes, and yes... but alas we have it :(

Here is the other issue: #26346

I'll close this one.

**Comment by ndarilek** [comment]
Weird. Why not close the *second* issue as a duplicate?

**Comment by cpuguy83** [comment]
Just more recent discussion.
