### ISSUE TITLE
DOC Overlay Network Required TCP/UDP Ports + Cluster Options

### ISSUE THREAD

**Issue by nicolaka** [docker/docker#17709]
Need to document the exact  required TCP/UDP ports to be open in order for overlay networks to work:

engine port (e.g TCP 2376), 
vxlan: UDP 4789
serf: TCP + UDP 7946
key-value store ( e.g for consul TCP 8500) 

Additionally, in `Understand Docker container networks`
need to edit `--cluster-advertise=HOST_IP` and make it `--cluster-advertise=HOST_IP:ENGINE_PORT` or `--cluster-advertise=HOST_INTERFACE:ENGINE_PORT`

**Comment by thaJeztah** [comment]
@moxiegirl @mavenugo This was an issue when running on AWS, but could apply to other situations 

Thanks @nicolaka

**Comment by nathanleclaire** [comment]
Got close on my first try but missed the VXLAN port.  +1 :)
