### ISSUE TITLE
"docker ps" doesn't include non-running containers with --before filter

### ISSUE THREAD

**Issue by wenchma** [docker/docker#17716]
Description of problem:

	ubuntu@docker:~$ docker ps -a
	CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                    PORTS               NAMES
	a3396c149690        busybox             "sh"                24 hours ago        Up 9 seconds                                  container3
	e86c22769399        busybox             "sh"                24 hours ago        Exited (0) 23 hours ago                       container2
	0e338f61bf62        busybox             "sh"                24 hours ago        Up 14 seconds                                 container1
	ubuntu@docker:~$ docker ps --before=container3
	CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
	0e338f61bf62        busybox             "sh"                24 hours ago        Up 27 seconds                           container1
	ubuntu@docker:~$ docker ps --since=container1
	CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                    PORTS               NAMES
	a3396c149690        busybox             "sh"                24 hours ago        Up 31 seconds                                 container3
	e86c22769399        busybox             "sh"                24 hours ago        Exited (0) 23 hours ago                       container2

I think the `before` filter should include the non-running containers like `since` filter, also like the man doc (https://github.com/docker/docker/blob/master/man/docker-ps.1.md#options) says.

`docker version` 

    Client:
	 Version:      1.9.0-rc5
	 API version:  1.21
	 Go version:   go1.4.2
	 Git commit:   9318004
	 Built:        Tue Nov  3 05:59:27 UTC 2015
	 OS/Arch:      linux/amd64

	Server:
	 Version:      1.9.0-rc5
	 API version:  1.21
	 Go version:   go1.4.2
	 Git commit:   9318004
	 Built:        Tue Nov  3 05:59:27 UTC 2015
	 OS/Arch:      linux/amd64

`docker info` :+1:

    Client:
	 Version:      1.9.0-rc5
	 API version:  1.21
	 Go version:   go1.4.2
	 Git commit:   9318004
	 Built:        Tue Nov  3 05:59:27 UTC 2015
	 OS/Arch:      linux/amd64

	Server:
	 Version:      1.9.0-rc5
	 API version:  1.21
	 Go version:   go1.4.2
	 Git commit:   9318004
	 Built:        Tue Nov  3 05:59:27 UTC 2015
	 OS/Arch:      linux/amd64
	ubuntu@docker:~$ docker info
	Containers: 3
	Images: 2
	Server Version: 1.9.0-rc5
	Storage Driver: aufs
	 Root Dir: /var/lib/docker/aufs
	 Backing Filesystem: extfs
	 Dirs: 8
	 Dirperm1 Supported: false
	Execution Driver: native-0.2
	Logging Driver: json-file
	Kernel Version: 3.13.0-43-generic
	Operating System: Ubuntu 14.04.1 LTS
	CPUs: 4
	Total Memory: 15.67 GiB
	Name: docker
	ID: UT5D:M5ZY:IEXQ:6LCU:YX6J:ZMWM:BLNJ:MTXH:PRHO:ETVF:3FHH:6LC4
	WARNING:

`uname -a` :+1: 

    Linux docker 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):OpenStack Cloud instance

Actual Results: `before` filter doesn't include the non-running containers

Expected Results:  `before` filter includes the non-running containers

**Comment by wenchma** [comment]
debug info for docker 1.8.2 version:

        mars@docker:~$ docker ps -a
	CONTAINER ID        IMAGE                    COMMAND              CREATED             STATUS                      PORTS               NAMES
	a493de0ead7e        wenchma/ubuntu:mariadb   "/bin/bash"          6 days ago          Up 5 hours                  3306/tcp            thirsty_lumiere
	37c688837ad4        ubuntu:14.04             "/bin/bash"          10 weeks ago        Dead                                            
	35f84153ecbd        ubuntu:14.04             "/usr/sbin/sshd-D"   10 weeks ago        Created                                         furious_darwin
	0a86cb72698a        wenchma/ubuntu:mariadb   "/bin/bash"          10 weeks ago        Exited (0) 10 weeks ago                         condescending_leakey
	d31eca25d0a9        wenchma/ubuntu:mariadb   "/bin/bash"          3 months ago        Up 4 hours                  3306/tcp            grave_engelbart
	79938f784a12        ubuntu                   "/bin/bash"          3 months ago        Exited (0) 3 months ago                         agitated_newton
	04cb438ca8bb        training/webapp          "python app.py"      3 months ago        Exited (137) 3 months ago                       admiring_hypatia
	f6d8b1019f5b        ubuntu                   "/bin/bash"          3 months ago        Exited (0) 3 months ago                         reverent_wozniak
	f430e879030c        ubuntu:14.04             "/bin/bash"          3 months ago        Exited (0) 3 months ago                         grave_brown
	mars@docker:~$ docker version
	Client:
	 Version:      1.8.2
	 API version:  1.20
	 Go version:   go1.4.2
	 Git commit:   0a8c2e3
	 Built:        Thu Sep 10 19:19:00 UTC 2015
	 OS/Arch:      linux/amd64

	Server:
	 Version:      1.8.2
	 API version:  1.20
	 Go version:   go1.4.2
	 Git commit:   0a8c2e3
	 Built:        Thu Sep 10 19:19:00 UTC 2015
	 OS/Arch:      linux/amd64
	mars@docker:~$ docker ps --before=furious_darwin
	CONTAINER ID        IMAGE                    COMMAND             CREATED             STATUS                      PORTS               NAMES
	0a86cb72698a        wenchma/ubuntu:mariadb   "/bin/bash"         10 weeks ago        Exited (0) 10 weeks ago                         condescending_leakey
	d31eca25d0a9        wenchma/ubuntu:mariadb   "/bin/bash"         3 months ago        Up 4 hours                  3306/tcp            grave_engelbart
	79938f784a12        ubuntu                   "/bin/bash"         3 months ago        Exited (0) 3 months ago                         agitated_newton
	04cb438ca8bb        training/webapp          "python app.py"     3 months ago        Exited (137) 3 months ago                       admiring_hypatia
	f6d8b1019f5b        ubuntu                   "/bin/bash"         3 months ago        Exited (0) 3 months ago                         reverent_wozniak
	f430e879030c        ubuntu:14.04             "/bin/bash"         3 months ago        Exited (0) 3 months ago                         grave_brown

**Comment by vdemeester** [comment]
@wenchma So the problem is that `--before` and `--since` do not act the same, one is showing only running ones, and the other all of them.

Now, I wonder if it's `--before` we should change or `--since`. My point is, by default docker shows only running one. You have to had `-a` to show them all. From a UX perspective, I would this a flag like `--before` or `--since` would act the same.

```bash
$ docker ps
# shows running ones
$ docker ps -a
# shows all of them
$ docker ps --before=mycontainer
# shows running ones started before mycontainer
$ docker ps -a --before=mycontainer
# shows all the container started before mycontainer
$ docker ps --since=mycontainer
# shows running ones started since mycontainer
$ docker ps -a --since=mycontainer
# shows all the container started since mycontainer
```

Right now to achieve the "Only show the running container since mycontainer", you have to do `docker ps --since=mycontainer --filter=status=running`.

So, I tend to agree something should be done to fix the difference of behavior between `--since` and `--before`, but not sure it's `--before`.

/ping @thaJeztah for opinions :stuck_out_tongue_closed_eyes:

**Comment by thaJeztah** [comment]
I actually think (and mentioned that thought in other issues) we should mark `--before` and `--since` deprecated, and re-implement them as options for `--filter`. In that implementation we can change the behavior to what we think is most logical. (And keep the behavior for `--before` and `--since` unchanged until they are removed)

**Comment by vdemeester** [comment]
@thaJeztah ah yeah, that feels like a pretty good idea :+1:

**Comment by thaJeztah** [comment]
And to answer "how should they behave"; a filter should only affect the thing you're filtering on; so `--filter=since=something` should show the same as `docker ps`, but filtered, *unless* I add a `status` filter

**Comment by vdemeester** [comment]
@wenchma would you like to implement this (by updating your current PR) ? :wink:

**Comment by wenchma** [comment]
@vdemeester  @thaJeztah 's idea looks good, :+1:  I will implement it to update my current PR.

**Comment by wenchma** [comment]
fixed this issue and completed the design, close it.
