### ISSUE TITLE
Getting warnings on Ubuntu 14.04

### ISSUE THREAD

**Issue by digitalronin** [docker/docker#17727]
I've recently started to see the following warning, every time I run a docker command;

    WARNING: Error loading config file:The Auth config file is empty

The OS is  Ubuntu 14.04.2 LTS.
Docker version 1.9.0, build 76d6bc9

The warning isn't causing any problems, AFAICT, but I'd like to get rid of it. Can anyone tell me what file it's looking for and, ideally, what is supposed to be in it?

Many thanks

David

**Comment by thaJeztah** [comment]
possibly an old `.dockercfg` file in your home folder

**Comment by digitalronin** [comment]
Thanks, but I don't think so. This is happening on brand-new VMs onto which I'm installing Docker from scratch.

**Comment by thaJeztah** [comment]
@digitalronin did you find what caused your issue?
