### ISSUE TITLE
Error trying to migrate boot2docker to docker-machine

### ISSUE THREAD

**Issue by jpblair** [docker/docker#17723]
I am trying to migrate my old boot2docker VM to docker-machine.  When I try the command provided in the FAQ, I get this error:

http://pastebin.com/4RJ7mQ8H

I'm running Windows if that makes any difference.  I tried it both in the normal CLI and MINGW.

**Comment by cpuguy83** [comment]
Can you move this to github.com/docker/docker-machine ?

Thanks!
