### ISSUE TITLE
Cannot mount a volume with '/' in it's name

### ISSUE THREAD

**Issue by srayevskyy** [docker/docker#17734]
ErrorCodeVolumeName error is generated: "%s includes invalid characters for a local volume name, only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed"

Possible root cause: the constant in https://github.com/docker/docker/blob/master/utils/names.go lacks forward slash in regexp.

const RestrictedNameChars = `[a-zA-Z0-9][a-zA-Z0-9_.-]`

**Comment by cpuguy83** [comment]
Yeah, this is expected, and purposefully rejected.
We don't want `/` in the name for the local storage as this screws up things.

**Comment by srayevskyy** [comment]
Brian,

Does it mean I cannot pass host volume '/home/user/directory' into a container?

**Comment by cpuguy83** [comment]
@srayevskyy No, this mounts the host path into the container and bypasses volumes

**Comment by srayevskyy** [comment]
So, the functionality 'Mount a host directory as a data volume' (http://docs.docker.com/engine/userguide/dockervolumes/) no longer exists?

**Comment by cpuguy83** [comment]
This still works exactly as it always has.

**Comment by srayevskyy** [comment]
Clay, problem is resolved, thank you!

I was violating this requirement: The host-dir can either be an absolute path or a name value.

In my case host volume path was relative. I was actually deceived by the error message:

Error response from daemon: volumes/adms1/app includes invalid characters for a local volume name, only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed

**Comment by arthur-tacca** [comment]
I've just bitten by this too. Any chance the message could be fixed to reflect the fact that paths are allowed but must be absolute?

**Comment by gaboesquivel** [comment]
+1 for improving the error message

**Comment by muayyad-alsadi** [comment]
> ErrorCodeVolumeName error is generated: "%s includes invalid characters for a local volume name, only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed"

should be

> ErrorCodeVolumeName error is generated: "%s includes invalid characters for a local volume name, only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed. If you did not intent to pass host-dir use absolute path starting with /"

**Comment by thaJeztah** [comment]
@muayyad-alsadi feel free to open a pull request

**Comment by muayyad-alsadi** [comment]
@thaJeztah  here you go

**Comment by cognitiaclaeves** [comment]
Was the behavior always this way? I had this issue with a script that I could have sworn used to work with a relative path.

**Comment by Dieterbe** [comment]
note that paths starting like `~/foo` or `$HOME/foo` are expanded to an absolute path (`/home/username/foo`) by your shell, before invoking docker.

**Comment by GerryG** [comment]
I'm having this problem with docker-compose, not clear how to get it to expand ${HOME} or ~ ... still looking. The message isn't too bad, but it would be nice if it showed what it was trying to use (after expansions, etc)

**Comment by muayyad-alsadi** [comment]
Expanding ~ is the job of your shell (bash)

**Comment by GerryG** [comment]
Or in this case, docker-compose. It worked with ${PWD} in the docker-compose.yml file.

**Comment by rbecheras** [comment]
For those it is not clear, here is a great explanation from #34532 by @thaJeztah https://github.com/moby/moby/issues/34532#issuecomment-322738970 about the invalid characters in the volume name.
