### ISSUE TITLE
Regression: Specifying an mac address does not create a deterministic IPv6 address

### ISSUE THREAD

**Issue by TimWolla** [docker/docker#17739]
Description of problem:
The [docs](https://docs.docker.com/engine/userguide/networking/default_network/ipv6/) state that:
> Remember the subnet for Docker containers should at least have a size of /80. This way an IPv6 address can end with the container’s MAC address and you prevent NDP neighbor cache invalidation issues in the Docker layer.

This worked fine until Docker 1.9 came along, as of docker 1.9 the IP addresses are not static anymore.

`docker version`:
```
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:29:38 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:29:38 UTC 2015
 OS/Arch:      linux/amd64
```
`docker info`:
```
Containers: 9
Images: 201
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 221
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 8
Total Memory: 31.35 GiB
Name: *redacted*
ID: *redacted*
WARNING: No memory limit support
WARNING: No swap limit support
```
`uname -a`:
```
Linux *redacted* 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u4 (2015-09-19) x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.):
Bare metal Debian Jessie box.

How reproducible: Always.

Steps to Reproduce:
1. Configure a `/80` for use by docker: `ExecStart=/usr/bin/docker -d --icc=false --ipv6 --fixed-cidr-v6="2001:db8:1234:5678:1337::/80" -H fd://`
2. Start a container using a fixed mac address: `docker run -it --rm --mac-address AA:BB:CC:DD:EE:FF debian ip -6 addr`
3. Observe the output

Actual Results:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
102: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 
    inet6 2001:db8:1234:5678:1337::9/80 scope global tentative 
       valid_lft forever preferred_lft forever
    inet6 fe80::a8bb:ccff:fedd:eeff/64 scope link tentative 
       valid_lft forever preferred_lft forever
```

Expected Results:
Taken from another box that still runs on Docker 1.8:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
390: eth0: <NO-CARRIER,BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 
    inet6 2001:db8:1234:5678:1337:aabb:ccdd:eeff/80 scope global tentative 
       valid_lft forever preferred_lft forever
    inet6 fe80::a8bb:ccff:fedd:eeff/64 scope link tentative 
       valid_lft forever preferred_lft forever
```
Note the `2001:db8:1234:5678:1337:aabb:ccdd:eeff/80` containing the container's mac address.

**Comment by icecrime** [comment]
@mavenugo Is that a regression?

**Comment by mavenugo** [comment]
@icecrime yes. @aboch is working on the fix.
