### ISSUE TITLE
broken link in https://github.com/docker/docker/blob/master/CONTRIBUTING.md

### ISSUE THREAD

**Issue by heckj** [docker/docker#17737]
I was reading through the contribution documentation, and under the section https://github.com/docker/docker/blob/master/CONTRIBUTING.md#design-and-cleanup-proposals, there's a link to http://docs.docker.com/opensource/project/advanced-contributing/ for advanced contributor details. That link leads to a blank page (not a 404 - just a blank page).

Wanted to let y'all know about the broken link as well as ask where I could find the details on how you're asking folks to present design and refactor concepts to the project.

Thanks!

-joe

**Comment by heckj** [comment]
This isn't related to docker, but to your online documentation, could you please look (or have a human look)? I'm happy to reformat the text if you need, but I though the bug was pretty reasonable in completeness and description

**Comment by davidcurrie** [comment]
This seems to be a more general issue with the docs. Looking at https://docs.docker.com/opensource/code/ I get broken links for the redirects from /project/find-an-issue/, /project/work-issue/ and /project/create-pr/.

**Comment by thaJeztah** [comment]
@heckj @davidcurrie thanks for reporting. The contribution guide has recently been moved to another repository, and some URLs were updated (for not all of them, redirects are in place); looks like this is the right URL for the broken link; https://docs.docker.com/opensource/workflow/advanced-contributing/ I'll check the other ones (and if they've been fixed already)

**Comment by heckj** [comment]
awesome, thanks @thaJeztah !
