### ISSUE TITLE
docker login

### ISSUE THREAD

**Issue by ljrittle** [docker/docker#17742]
Create a docker engine (1.9) via docker-machine-0.5:

`docker-machine create -d vmwarevsphere --engine-opt disable-legacy-registry --engine-storage-driver overlay test-xxx`

(The exact driver shouldn't matter.)

Point docker client (1.9) to the new docker engine:

`eval "$(docker-machine env test-xxx)"`

Note the output of `docker login --help` which states that:
`If no server is specified "https://index.docker.io/v1/" is the default.`

Attempt to run `docker login` and see:
`Error response from daemon: invalid registry endpoint https://index.docker.io/v2/: https://index.docker.io/v2/ does not appear to be a v2 registry endpoint. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry index.docker.io` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/index.docker.io/ca.crt`

**Comment by ljrittle** [comment]
$ docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64
$ docker info
Containers: 1
Images: 46
Server Version: 1.9.0
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.12-boot2docker
Operating System: Boot2Docker 1.9.0 (TCL 6.4); master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015
CPUs: 2
Total Memory: 7.792 GiB
Name: test-xxx
ID: VBLL:L6V5:SWEC:AHFW:V5I4:XJBG:KAP6:UYNH:ONIS:KR7R:SIMS:BSVF
Debug mode (server): true
 File Descriptors: 48
 Goroutines: 61
 System Time: 2015-11-06T00:16:49.776798048Z
 EventsListeners: 1
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=vmwarevsphere
$ uname -a
Darwin sanitized-machine-name 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64

**Comment by calavera** [comment]
`https://index.docker.io/v2/` does not exist. The error that you're getting is correct. The right address is `https://index.docker.io/v1`. I'm closing this as it's not an issue. Please double check your config in `~/.docker/config.json`.
