### ISSUE TITLE
COPY with wildcard fails when context contains invalid symlinks

### ISSUE THREAD

**Issue by mikz** [docker/docker#17756]
Docker 1.9.0 on several machines (osx + boot2docker, ubuntu 14.04, 12.04).

To reproduce:

```
FROM busybox

COPY lib/*.rb /foo/
```

and filesystem:

```
mkdir lib
touch lib/bar.rb
mkdir public
ln -s invalid public/invalid
```

Copy fails with `stat lib/invalid: no such file or directory`.

Works when the wildcard is expanded to `lib/bar.rb`.

Related to #17730

**Comment by tonistiigi** [comment]
This should be fixed with #17710

**Comment by tonistiigi** [comment]
Closing as #17710 is merged

**Comment by mikz** [comment]
Thanks @tonistiigi !
