### ISSUE TITLE
how to use `docker inspect <containerId>` infomation to find container network dstName?

### ISSUE THREAD

**Issue by dotNetDR** [docker/docker#17752]
I know v1.8.3 'docker stats <containerId>' return network I/O data from 'cat /proc/net/dev' (by dstName).

Q:how to get single container network I/O data in my container monitor agent?

---------
just like

step 1
　search containerId "6426e5883420" return "veth2b8e8d3"

step 2
　'cat /proc/net/dev' (find "veth2b8e8d3") and collect single container network I/O data.

i try call docker remote api v1.20 /containers/(id)/stats but very slow(time:20ms~3s)

**Comment by Skarlso** [comment]
Could you please clarify the problem a bit more? 

Usually ```docker stats``` requires a container-id to return data about. And you can retrieve a container id by doing the following command => ```docker ps -aq --filter="name=<nameofthecontainer>"```.

This returns an ID. You can then pipe it to stats like this => 

```bash
docker stats `docker ps -aq --filter="name=<nameofthecontainer>"
```

Would this help?

**Comment by dotNetDR** [comment]
@Skarlso 
I have container id('6426e5883420')
How do I get into this container virtual NIC name(veth2b8e8d3)?

I want to collect every container network I/O.

My job is for the private cloud to develop the monitoring system

**Comment by Skarlso** [comment]
I'm not sure I completely got this. If you have a list of containers which you would like to cycle through you can use a shell script for that, something like this: 

```bash
cont=( $(docker ps -qa) )
if [ ${#cont[@]} -eq 0 ]; then
    echo 'No containers found... Nothing to do'
    exit 1
fi

for cont in `docker ps -qa`; do
    docker inspect $cont |grep NetworkID # >> do something with networkID.
done
```
Not sure if network ID is something that you are looking for, but inspect has a lot of information as well. You can gather and parse the output from that commend which will look something like this:
```NetworkID": "957194ef1b00e06c730e809301a1cfe516f328f23ccc332ddb3d27a317ed50fa",```

**Comment by dotNetDR** [comment]
[add query container network api](https://github.com/dotNetDR/docker/commit/2a10fa37aea4fa230a6fab399b2aff78398a8b82)

thanks all~


![sys](https://cloud.githubusercontent.com/assets/926166/11032684/5f66fbb2-8718-11e5-9765-39a8c44c61d1.jpg)
![singecontainernetio](https://cloud.githubusercontent.com/assets/926166/11032697/87e56df8-8718-11e5-9195-06e5b4a5d94e.png)

**Comment by Skarlso** [comment]
If this is solved, would you please also close the Issue? 

thanks!
Gergely.
