### ISSUE TITLE
Docker runtime error

### ISSUE THREAD

**Issue by owenhaynes** [docker/docker#17759]
System centos 7vm
Memory 2GB
CPU 2 with Hyper-threading 2.5Ghz
Docker version 1.9

Linux vm-docker 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

building 2 images on one VM from Jenkins, I don't know what else to report. VM does not looked ram starved according to VM sphere  never hits more then 80% ram usage at the time the crash happend

Nov 06 14:47:10 vm-docker docker[2536]: time="2015-11-06T14:47:10.608950328Z" level=info msg="POST /v1.21/images/docker.someplace.co.uk/test/push?tag=1.0v1b13"
Nov 06 14:48:16 vm-docker docker[2536]: panic: runtime error: invalid memory address or nil pointer dereference
Nov 06 14:48:16 vm-docker docker[2536]: [signal 0xb code=0x1 addr=0x20 pc=0x6e458a]
Nov 06 14:48:16 vm-docker docker[2536]: goroutine 2348 [running]:
Nov 06 14:48:16 vm-fdocker docker[2536]: bufio.(*Writer).flush(0xc20baab140, 0x0, 0x0)
Nov 06 14:48:16 vm-docker docker[2536]: /usr/local/go/src/bufio/bufio.go:530 +0xda
Nov 06 14:48:16 vm-docker docker[2536]: bufio.(*Writer).Flush(0xc20baab140, 0x0, 0x0)
Nov 06 14:48:16 vm-docker docker[2536]: /usr/local/go/src/bufio/bufio.go:519 +0x3a
Nov 06 14:48:16 vm-docker docker[2536]: net/http.(*response).Flush(0xc20d6ecaa0)
Nov 06 14:48:16 vm-docker docker[2536]: /usr/local/go/src/net/http/server.go:1047 +0x4c
Nov 06 14:48:16 vm-docker docker[2536]: github.com/docker/docker/pkg/ioutils.(*WriteFlusher).Write(0xc20d6e6b70, 0xc20b288184, 0x3c, 0x40, 0x3c, 0x0, 0x0)
Nov 06 14:48:16 vm-docker docker[2536]: /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/pkg/ioutils/writeflusher.go:22 +0x145
Nov 06 14:48:16 vm-docker docker[2536]: github.com/docker/docker/pkg/progressreader.updateProgress(0xc20bea7a40)
Nov 06 14:48:16 vm-docker docker[2536]: /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/pkg/progressreader/progressreader.go:67 +0x101
Nov 06 14:48:16 vm--docker docker[2536]: github.com/docker/docker/pkg/progressreader.(*Config).Read(0xc20bea7a40, 0xc20bea8000, 0x8000, 0x8000, 0x8000, 0x7fb15f853240, 0xc20802a120)
Nov 06 14:48:16 vm-docker docker[2536]: /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/pkg/progressreader/progressreader.go:41 +0x229
Nov 06 14:48:16 vm-docker docker[2536]: io.Copy(0x7fb15c1157e8, 0xc20d72d8c0, 0x7fb15434fa80, 0xc20bea7a40, 0x0, 0x0, 0x0)
Nov 06 14:48:16 vm-docker docker[2536]: /usr/local/go/src/io/io.go:362 +0x1f6
Nov 06 14:48:16 vm-docker docker[2536]: github.com/docker/docker/graph.func·016()
Nov 06 14:48:16 vm-docker docker[2536]: /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/graph/push_v2.go:270 +0xb9
Nov 06 14:48:16 vm-docker docker[2536]: created by github.com/docker/docker/graph.(*v2Pusher).pushV2Image
Nov 06 14:48:16 vm-docker docker[2536]: /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/graph/push_v2.go:282 +0xa54
Nov 06 14:48:16 vm-docker docker[2536]: goroutine 1 [chan receive, 26 minutes]:
Nov 06 14:48:16 vm-docker docker[2536]: main.(*DaemonCli).CmdDaemon(0xc2084f5240, 0xc20800a020, 0x8, 0x8, 0x0, 0x0)
Nov 06 14:48:16 vm-docker docker[2536]: /root/rpmbuild/BUILD/docker-engine/docker/daemon.go:308 +0x20a7
Nov 06 14:48:16 vm-docker docker[2536]: reflect.callMethod(0xc2084d5f80, 0xc208d19ce8)
Nov 06 14:48:16 vm-docker docker[2536]: /usr/local/go/src/reflect/value.go:605 +0x179
Nov 06 14:48:16 vm-docker docker[2536]: reflect.methodValueCall(0xc20800a020, 0x8, 0x8, 0x1, 0xc2084d5f80, 0x0, 0x0, 0xc2084d5f80, 0x0, 0x4e297f, ...)
Nov 06 14:48:16 vm-docker docker[2536]: /usr/local/go/src/reflect/asm_amd64.s:29 +0x36
Nov 06 14:48:16 vm-docker docker[2536]: github.com/docker/docker/cli.(*Cli).Run(0xc2084d5ec0, 0xc20800a010, 0x9, 0x9, 0x0, 0x0)
Nov 06 14:48:16 vm-docker docker[2536]: /root/rpmbuild/BUILD/docker-engine/.gopath/src/github.com/docker/docker/cli/cli.go:89 +0x38e
Nov 06 14:48:16 vm-docker docker[2536]: main.main()
Nov 06 14:48:16 vm-docker docker[2536]: /root/rpmbuild/BUILD/docker-engine/docker/docker.go:65 +0x418
Nov 06 14:48:16 vm-docker docker[2536]: goroutine 5 [syscall, 28 minutes]:
Nov 06 14:48:16 vm-docker docker[2536]: os/signal.loop()
Nov 06 14:48:16 vm-docker docker[2536]: /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
Nov 06 14:48:16 vm-docker docker[2536]: created by os/signal.init·1

**Comment by cpuguy83** [comment]
I think this is already fixed for 1.9.1
@stevvooe Is this related to that panic you fixed?

**Comment by stevvooe** [comment]
@cpuguy83 Should have been fixed by https://github.com/docker/docker/issues/17625. I don't think that made the release. Should come out with 1.9.1.

**Comment by thaJeztah** [comment]
Thanks, I'll close this as fixed by https://github.com/docker/docker/pull/17634 (#17625 is the issue), but feel free to comment if you're still able to reproduce on 1.9.1 once that has been released
