### ISSUE TITLE
Is it possible to bind a container to multi networks?

### ISSUE THREAD

**Issue by tonicbupt** [docker/docker#17750]
I'm using docker 1.9.0 and I use `docker network create` to create 2 networks named `'net'`, `'net2'`, but when I started container, I tried to pass `--net=net1 --net=net2` or `--net=net1,net2` to join multi network before real process in container starts, I got failed.
I checked source code and I found `allocateNetwork` when allocate all networks in `container.NetworkSettings.Networks`, so it must be possible to do this, but how? It seems currently the API doesn't offer this feature.

**Comment by coolljt0725** [comment]
you can use `docker network connect` to add network after container starting.   `docker run` only support a network.

**Comment by tonicbupt** [comment]
@coolljt0725 but If my process needs both networks to boot, it will fail if only one network is up, then container will exit, and nothing is ever meaningful... the main point is that when I check source code, docker can deal with multi networks, I was wondering why API doesn't support this ...  = =

**Comment by coolljt0725** [comment]
@tonicbupt  Actually, I +1 on supporting multiple network on `docker run` and I have done some work to make this happen :-)

**Comment by cpuguy83** [comment]
Yes, it's possible, not currently possible to do this at runtime. So you can only attach to one network, start the container, then you can attach to other networks.
I think ideally `--net` could be extended to take multiple entries `--net=backend --net=frontend`... but maybe the network team has some plans around this,

**Comment by thaJeztah** [comment]
@tonicbupt unfortunately, this enhancement was rejected because it complicated things if additional settings are required per network; https://github.com/docker/docker/pull/17796#issuecomment-162612624

For that reason, I'll have to close this issue, but thanks for suggesting, it's appreciated!

**Comment by mavenugo** [comment]
actually the functionality of having multiple networks connected before the container starts is possible and is addressed via 
https://github.com/docker/docker/pull/18531 and https://github.com/docker/docker/pull/18906

Once https://github.com/docker/docker/pull/18906 is merged, one can create a container in 1 network and connect to multiple networks using (`docker network connect`) and then start the container.

**Comment by thaJeztah** [comment]
Ah, you're right, I was looking at the multiple `--net[]` option, apologies there. I'll reopen

**Comment by thaJeztah** [comment]
https://github.com/docker/docker/pull/18906 was merged, so you can now connect a container to multiple networks before starting (using `docker network connect`). Closing this issue :+1:
