### ISSUE TITLE
docker pull tutum/wordpress fails

### ISSUE THREAD

**Issue by LK4D4** [docker/docker#17766]
With error:
```
5025a6da41dd: Error pulling image (latest) from docker.io/tutum/wordpress, ApplyLayer exit status 1 stdout:  stderr: chtimes /app/.git: no such file or directory
```

**Comment by LK4D4** [comment]
It seems like it fails everywhere, it fails in `archive.UnpackLayer` function.

**Comment by tonistiigi** [comment]
Pretty sure it's the `opq` whiteouts that are causing this. Its kind of a known issue but I wasn't aware that its so easy to reproduce or that it could fail a pull.

If someone sees the same thing happening to their images, then quick workaround is to rebuild it and if you rebuild on aufs try to avoid `rm -rf /dir` and adding new files to that dir in the same layer.
