### ISSUE TITLE
Not working in macosx 

### ISSUE THREAD

**Issue by HypnoTheNomad** [docker/docker#17768]
THis is not working on macosx (running 10.11.1)

source ~/.docker-bash-complete
-bash: /Users/rmartini/.docker-bash-complete: line 758: syntax error near unexpected token `('
-bash: /Users/rmartini/.docker-bash-complete: line 758: `		*dm.@(blkdiscard|override_udev_sync_check|use_deferred_@(removal|deletion))=*)'

I can't understand where is the issue..

Bash version:
GNU bash, version 4.3.42(1)-release (x86_64-apple-darwin15.0.0)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by albers** [comment]
see also #17791
#dibs

**Comment by thaJeztah** [comment]
thanks @albers!

**Comment by thaJeztah** [comment]
This should be fixed in https://github.com/docker/docker/issues/17806

Thanks for reporting @HypnoTheNomad !
