### ISSUE TITLE
Configurable group and permissions for docker json-logs

### ISSUE THREAD

**Issue by jhmartin** [docker/docker#17763]
It would be useful to be able to pass an option to the json-logger to define the group and umask of json-file logs, to make it simpler for tools like Logstash to read the logs without having to run as root.

https://github.com/docker/docker/blob/c30b9e590c69a01ee6ea0510142fb9f965b62f7a/daemon/logger/jsonfilelog/jsonfilelog.go#L59

**Comment by thaJeztah** [comment]
I don't think this is something we want; files inside `/var/lib/docker` are managed by the daemon, and no outside processes should use those files.

**Comment by jhmartin** [comment]
What is the point of the configurability of json-file if the logs are not meant to be read?  Only recently did docker have a built-in log-rotation mechanism, prior to that it would have to rely on an external process to keep the logfiles in check.  

Since json-file is a published logging format with configuration options, it seems reasonable to add a configuration modifying what can read the files.

**Comment by thaJeztah** [comment]
The files are just the storage, and meant for consumption via `docker logs`. Afaik, it's not intended to directly access those files, and not documented where those files are stored

**Comment by jhmartin** [comment]
From a consumption perspective it is awkward to run a separate docker-logs process for each stream, while it is very efficient to look for all available files and read/tail them.

**Comment by cpuguy83** [comment]
Agree with @thaJeztah, it doesn't make sense to support this in Docker.

If you want to use logstash, please use one of the available logging drivers (syslog, fluentd, journald, gelf), which logstash seems to support any/all of natively.
If you have any questions feel free to ping me.

Thanks!
