### ISSUE TITLE
Allow configurable metadata for custom log drivers

### ISSUE THREAD

**Issue by glennblock** [docker/docker#17772]
A common need for log drivers is to allow specifying container-level metadata which a custom log driver has access to and can embed in the data it sends to other systems. This useful for mining the data after the fact. We've heard this specifically from @phylake, and from other Splunk customers looking to use Docker. We've also heard this from Amazon ECS folks who mentioned this is a very common request. 

The idea is to allow specifying arbitrary key/value pairs at the time the log-driver is initialized. An ideal situation would be to allow this metadata to even be updated dynamically after the container is running.

I did a small spike on this over [here](https://github.com/splunk/docker/pull/1). That approach relies on command line args that are passed to the driver. This works for static metadata, but not for metadata that can change which was a requirement fed by @phylake.

In doing that work, it became clear that is something that likely other docker drivers would want to use and not something Splunk specific.

## Proposal
There should be a standard way of specifying metadata for a log driver. That metadata should be passed in to custom log driver implementations. It is up to the driver itself to determine what to do with that metadata / how to pass it on.

Different approaches come to mind for how to specify the metadata.

1. Use a command line arg for the driver like `log-opt metadata` with the value being a JSON object. Pro: This would be very simple to use. Con: Only useful for specifying static metadata. 
1. Introduce a general docker command for setting container-level metadata i.e. `docker metadata`. You pass the ID of the container and the metadata and call invoke it whenever you need to. I've noticed you can add [labels](http://docs.docker.com/engine/userguide/labels-custom-metadata/) to images, maybe having a similar capability for containers, and then have that flow into the log-driver. Pro: Easy to use, supports dynamic metadata per container. Con: Harder to implement.
1. Introduce a standard configuration file which contains the metadata like `[name]-driver.json` (splunk-logging-driver.json). This file contains the metadata as a json object. A file watcher could monitor this file and detect changes / reload the metadata. Pro: Supports dynamic metadata per container. Con: Hard to use, more complexity (config per container, file watching). 

For handling within the driver itself, the metadata will be passed as a `metadata` param on the `msg` param of the `log` function. 

## Example
Below is an example of how this might be used with a new `docker metadata` command.
```
docker metadata a63446b1b8c94853acc58a04e91349fe '{"category":"web", "region":"west"}'
```

And here is how events might be sent to Splunk using our new Splunk driver if it had access to the metadata.  Notice the metadata is under the `metadata` field.

```javascript
{
  "containeridId": "a63446b1b8c94853acc58a04e91349fe",
  "metadata": {
    "category": "web",
    "region": "west"
  },
  "line": "Hello World",
  "source": "stdout"
}
```

**Comment by nickperry** [comment]
I prefer the simplicity of the command line arg. I'd be interested to hear more on the requirement to be the metadata whilst the contained is running. If it is neccesary, there's got to be a more elagant way to implement it than a watched config file. For one thing you'd need a config file per container not one per container host, so you could set different metadata psr co tainer.

**Comment by nickperry** [comment]
I prefer the simplicity of the command line arg.

I'd be interested to hear more on the requirement to be able to manipulate the metadata whilst the container is running. If it is neccesary, there's got to be a more elagant way to implement it than a watched config file. For one thing you'd need a config file per container not one per container host, so you could set different metadata per co tainer.

**Comment by glennblock** [comment]
@nickperry great points. I also think it would be ideal to not require the file, though the file was something that come up as we discussed it. One idea thrown out was to have a URI that is polled, I was worried that would be complicated. 

An alternative approach would be some sort of cmd/API you could invoke from the docker command line passing in the containerid and metadata. Then you could run that as often as you like.

**Comment by glennblock** [comment]
@nickperry I added the general metadata for containers via docker command line as an option.

**Comment by halr9000** [comment]
I feel like the CLI approach should be mandatory for this proposal, even though it doesn't satisfy a dynamic requirement. My reasoning is that if one's workflow requires the metadata, then specifying that at runtime is going to be implicit. In that case, having to issue two commands for every container run seems silly (but not harmful).

Why not both 1 and 2 (`docker metadata`)?

**Comment by glennblock** [comment]
@halr9000 sounds reasonable to me.

**Comment by nickperry** [comment]
Agreed. Possibly 1 in the first instance then expand functioanlity to1+2?

**Comment by glennblock** [comment]
MVP :-)

**Comment by outcoldman** [comment]
@glennblock if you are interesting in this metadata only for logger driver then possible that this is a duplicate of http://docs.docker.com/engine/reference/logging/log_tags/ which has been implemented in docker v1.9 (https://github.com/docker/docker/pull/15384/files)

**Comment by glennblock** [comment]
Hi @outcoldman.

Interesting! 

It "looks" like this could work for static metadata specified when the container starts. I'll have to test that out and see if it could work with a JSON payload or a set of key value pairs. 

This doesn't look like it addresses the dynamic requirement to change the tag after the container is running, though if it works for static metadata, maybe that dynamic behavior could be added on top of the same mechanism.

**Comment by glennblock** [comment]
Reading through log_tags, I don't think it will work for the scenarios described in its current form, but I'll experiment with it.

**Comment by glennblock** [comment]
Closing this as labels in 1.9.1 appears to address static metadata supplied at the time the container is started. 

See this PR which uses this: https://github.com/docker/docker/pull/17891
