### ISSUE TITLE
means to mount host volume/s to containers as shared volumes.

### ISSUE THREAD

**Issue by necrose99** [docker/docker#17776]
**/usr/portage/packages**  > Docker-Gentoo-build-wore_1 & Docker-Gentoo-build-wore_2
etc.
/var/log/builds etc. ie read build fails etc . 
In my case , build packages in CHROOT/docker/lxc containers and drop them back on the host.
in case of clean container (reset to clean) steal binaries from the root host IE package updates.

if an update goes bad , then the likely-hood of my main production environment going to hell is far far  less. but for testing my own package scripts ie ebuilds for new packages before upstreaming to Gentoo , using a container is a safe bet , also keeps disk space to lot less.

**Comment by necrose99** [comment]
i'm just trying to use host folders ie local machine , granted i'm building a few dockerhub generic environment containers. , however Docker-lxc pysical is target ,  ie  necrose99/my-gentoo-base > (FROM my-gentoo-base) necrose99/my_personal-dockerfile build add crap in and settings. 

**anyhow better documentation of a how too for wiki would be a plus.. **
-IE how to expose host folders to the container- 
** my use case is ebuilds & binary packages and or push finished binaries to host's packages folder**  having rsync/ftp/sftp I/O to host/docker-Build-container/s would thus needlessly increase disk-space. ** just trying to sync /usr/portage and some /var/ folders governing emerge build logs to host. IE for test packages. 


sftp or or nfs to host , I just don't see a point of having docker containers and package folders in them to dump built packages from source's , when the host's container is more convenient.
how to bind docker A to b,c,d,e is know. for some shared volume/folders. 

**hostsvolume /usr/portage/*  ADD volume /usr/portage*  ? donk know, but any case for safer testing of bumped or alpha/beta packages , in container for build testing 
if it were a mainstay chroot one could use mount bind or rbind.

**Comment by cpuguy83** [comment]
A little confused by your description here, but it sounds like you want to mount a host dir into a container.
This needs to be done at runtime -- `docker run -v /host/path:/container/path`

**Comment by necrose99** [comment]
OK just could not find the docs for such.
