### ISSUE TITLE
Apply custom metadata

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#17770]
This is just hanging there in an odd place.

http://docs.docker.com/engine/userguide/labels-custom-metadata/

**Comment by LK4D4** [comment]
@thaJeztah Could you pls find who doing docs now and tell me? :)

**Comment by thaJeztah** [comment]
ping @mstanleyjones perhaps you have thoughts which section we should move this page to? Should we keep this issue open for tracking, or is this already on the radar in the docs team?
