### ISSUE TITLE
Remote API: Failure start to start registry:2 container created through remote API

### ISSUE THREAD

**Issue by athrane** [docker/docker#17771]
I ran into an issue where containers which are created using the remote API fails to start under some circumstances. I encountered the issue during my work on Docker plugin for the Pineapple project, https://java.net/jira/browse/PINEAPPLE-1139 I have reproduced the issue using the Chrome advanced Rest client. To reproduce:

0) A registry container is created using the CLI (for later comparison):
docker run -d -p 5000:5000 --restart=always --name registry registry:2

1) A registry container is created using the remote API: 
POST http://DOCKERHOST:PORT/containers/create 
with payload:
{
  "Cmd": [],
  "Env": [],
  "Entrypoint": [],
  "ExposedPorts": {},
  "HostConfig": {
    "Binds": [],
    "Dns": [],
    "DnsSearch": [],
    "ExtraHosts": [],
    "GroupAdd": [],
    "Links": [],
    "RestartPolicy": null,
    "LogConfig": null,
    "PortBindings": {},
    "SecurityOpt": [],
    "VolumesFrom": [],
    "BlkioWeight": null,
    "ContainerIDFile": null,
    "CapAdd": null,
    "CapDrop": null,
    "CgroupParent": null,
    "ConsoleSize": null,
    "CpuShares": 0,
    "CpuPeriod": 0,
    "CpusetCpus": "",
    "CpusetMems": "",
    "CpuQuota": null,
    "Devices": null,
    "LxcConf": null,
    "IpcMode": null,
    "NetworkMode": null,
    "Memory": 0,
    "MemorySwap": 0,
    "MemorySwappiness": null,
    "OomKillDisable": null,
    "PidMode": null,
    "Privileged": null,
    "PublishAllPorts": null,
    "ReadonlyRootfs": null,
    "Ulimits": null,
    "UtsMode": null
  },
  "Labels": {},
  "OnBuild": [],
  "Volumes": {},
  "AttachStderr": true,
  "AttachStdin": true,
  "AttachStdout": true,
  "Domainname": "",
  "Hostname": "",
  "Image": "docker.io/registry:2",
  "MacAddress": null,
  "NetworkDisabled": false,
  "OpenStdin": true,
  "StdinOnce": false,
  "Tty": true,
  "User": "",
  "WorkingDir": ""
}

2) View the created containers:
GET http://DOCKERHOST:PORT/containers/json?all=true

0:  {
Id: "f8fb00707c11c27a85b8872d5b4c3981c782321c67df7059a210785f7155c189"
Names: [1]
0:  "/hopeful_wozniak"
-
Image: "docker.io/registry:2"
Command: "/etc/docker/registry/config.yml"
Created: 1446839557
Ports: [0]
Labels: {}
Status: ""
}-
1:  {
Id: "9a6f91cc9082f306e6267487319fae54e4d5cfd98f7f70bebd63271f7cb55388"
Names: [1]
0:  "/registry"
-
Image: "registry:2"
Command: "/bin/registry /etc/docker/registry/config.yml"
Created: 1446763800
Ports: [0]
Labels: {}
Status: "Exited (2) 2 hours ago"
}

Please look at the Command property for the containers. The container created through the remote API doesn't contain the values of the ENTRYPOINT directive from the registry image dockerfile.

3) Attempting the start the "hopeful_wozniak"container fails:

docker start  hopeful_wozniak

Error response from daemon: Cannot start container hopeful_wozniak: [8] System error: exec: "/etc/docker/registry/config.yml": permission denied
Error: failed to start containers: [hopeful_wozniak]

Environment information:

uname -a
Linux localhost.localdomain 3.10.0-123.el7.x86_64 #1 SMP Mon Jun 30 12:09:22 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Package Version: docker-1.8.2-7.el7.centos.x86_64
 Go version:   go1.4.2
 Git commit:   bb472f0/1.8.2
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Package Version:
 Go version:   go1.4.2
 Git commit:   bb472f0/1.8.2
 Built:
 OS/Arch:      linux/amd64

docker info
[docker@localhost vagrant]$ docker info
Containers: 1
Images: 22
Storage Driver: devicemapper
 Pool Name: docker-253:1-134297063-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.428 GB
 Data Space Total: 107.4 GB
 Data Space Available: 37.9 GB
 Metadata Space Used: 2.445 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-123.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 1.798 GiB
Name: localhost.localdomain
ID: PKQY:A5BI:HDLQ:FJH4:BMH4:2A26:SAV3:25S3:FUM4:P2GI:7FYR:RJBF

**Comment by cpuguy83** [comment]
Everything the docker CLI does is via the remote API.

In your create API request, you have specified `"Entrypoint": []`, this overrides what is in the image.
In your create API request you are using `"Image": "docker.io/registry:2`, where as on the `run` you are using just `registry:2`.

Closing.

**Comment by athrane** [comment]
Thank you for the help. 
I had the misunderstanding that sending "Entrypoint": [], i.e. the empty array, would correspond to sending no input in the request. Sending "no input" must be implemented sending null and not the empty array in the request. Usage of the "Image": "docker.io/registry:2" was a typo, the observed behavior is the same whether , "docker.io/registry:2" or "registry:2" are used.

**Comment by cpuguy83** [comment]
Yep. You only need to send the things you want to change.
Really to create a container, all you need to do is `curl -XPOST /containers/create -d '{"Image": "registry:2"}'`
