### ISSUE TITLE
docker "command not found" on windows

### ISSUE THREAD

**Issue by drozzy** [docker/docker#17774]
After following install instructions in Windows 7:
http://docs.docker.com/windows/step_one/

when I get to Step 4, trying to run `docker run hello-world` I get the error:

`bash: docker: command not found`

**Comment by drozzy** [comment]
Trying:

`winpty docker run hello-world`

yields:

`Error 0x2 starting docker run hello-world`

**Comment by Skarlso** [comment]
Hi. 

Did you try restarting? 

Are you running it from the docker toolbox terminal? Is Kitematic working fine?

**Comment by lmmarsano** [comment]
Same problem here.
The Docker Toolbox installer doesn't add the Docker path to the system `path` variable.
It only adds the path to the installing user's `path`.
This is no good for those who keep administrator accounts separate and use the least-privileged user account to follow the [principle of least privilege](//en.wikipedia.org/wiki/Principle_of_least_privilege).

**Comment by thaJeztah** [comment]
ping @jeffdm please take a look here

**Comment by lmmarsano** [comment]
Here's my bug report info (after fixing the environment)

	$ docker version
	Client:
	 Version:      1.9.0
	 API version:  1.21
	 Go version:   go1.4.3
	 Git commit:   76d6bc9
	 Built:        Tue Nov  3 19:20:09 UTC 2015
	 OS/Arch:      windows/amd64
	
	Server:
	 Version:      1.9.0
	 API version:  1.21
	 Go version:   go1.4.3
	 Git commit:   76d6bc9
	 Built:        Tue Nov  3 19:20:09 UTC 2015
	 OS/Arch:      linux/amd64
	$ docker info
	Containers: 2
	Images: 2
	Server Version: 1.9.0
	Storage Driver: aufs
	 Root Dir: /mnt/sda1/var/lib/docker/aufs
	 Backing Filesystem: extfs
	 Dirs: 6
	 Dirperm1 Supported: true
	Execution Driver: native-0.2
	Logging Driver: json-file
	Kernel Version: 4.1.12-boot2docker
	Operating System: Boot2Docker 1.9.0 (TCL 6.4); master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015
	CPUs: 1
	Total Memory: 996.2 MiB
	Name: default
	ID: AF63:BPY5:32P4:DOLS:2WEB:EGZP:R3KU:UGBW:N2QZ:GU62:YWWY:C746
	Debug mode (server): true
	 File Descriptors: 11
	 Goroutines: 20
	 System Time: 2015-11-08T00:01:36.541458872Z
	 EventsListeners: 0
	 Init SHA1:
	 Init Path: /usr/local/bin/docker
	 Docker Root Dir: /mnt/sda1/var/lib/docker
	Labels:
	 provider=virtualbox
	> systeminfo.exe | Select-String -Pattern ^OS
	
	OS Name:                   Microsoft Windows 10 Home
	OS Version:                10.0.10240 N/A Build 10240
	OS Manufacturer:           Microsoft Corporation
	OS Configuration:          Standalone Workstation
	OS Build Type:             Multiprocessor Free

To reproduce the issue, just follow [Getting Started](http://docs.docker.com/windows/step_one/) exactly with a Standard user account.

**Comment by drozzy** [comment]
@Skarlso I don't think I restarted. I can give it a shot again sometime...

**Comment by paddyurlich** [comment]
was there a solution to this, I have the same problem.

**Comment by calavera** [comment]
Please, feel free to open an issue in the toolbox(https://github.com/docker/toolbox) repository with more information about this. They might be able to provide much better help.

**Comment by Fredjet** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  fredjet15@gmail.com
    Domain ventureacceleration.com has exceeded the max emails per hour (59/50 (118%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o6.sgmail.github.com ([192.254.113.101]:17229)
	by eaglepeak.ovasp.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <bounces+848413-c2da-fred=ventureacceleration.com@sgmail.github.com>)
	id 1abd2z-0000dp-68
	for fred@ventureacceleration.com; Thu, 03 Mar 2016 18:52:45 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=p6N24k8nI78Ap4JtMNdMn6SBfP0=; b=UJbWjKdB99J19QsV
	603cec8uUZYQnfAj4XjnX0iQ78EW936AyYarvt9d93ekOck7vOtvez3b78f2SA1e
	UZnqFZdBRNh2DcLyLjRmTGqqPmUuR/UbC+NIMcdVuZ7Pll3tHMx5g6b0FCsGhL9e
	YlUOVchxxzJrMljUC3DqM5BKp6E=
Received: by filter0549p1mdw1.sendgrid.net with SMTP id filter0549p1mdw1.30835.56D8CE2130
        2016-03-03 23:52:01.688748635 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0006p1iad1.sendgrid.net (SG) with ESMTP id 4Q-FN7zmS3in2Z2hUrjGEg
	for <fred@ventureacceleration.com>; Thu, 03 Mar 2016 23:52:01.824 +0000 (UTC)
Date: Thu, 03 Mar 2016 15:52:01 -0800

**Comment by Fredjet** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  fredjet15@gmail.com
    Domain ventureacceleration.com has exceeded the max emails per hour (58/50 (115%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:57829 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by eaglepeak.ovasp.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1abd2x-0000do-OX
	for fred@ventureacceleration.com; Thu, 03 Mar 2016 18:52:44 -0500
Date: Thu, 03 Mar 2016 15:52:03 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457049123;
	bh=DbU2r3O+XVSrealaJVAHgLNUSr2OLPSscG4HzvX2S3E=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=w5YTeI/qrF4T1v8tIeWDYqqf4JIRfMoVttzyHE8bfu0pm5j383GKTZJrViCmGFOHd
	 4eu9gxohD9M7njylNAaphm2esdob/4lnvaCKgCzZv5nualu76QlEPLNTfECMwSDEae
	 AHA84KkCvbfgbr6el9Kjm2GLOfzFgHiOUK476OmQ=

**Comment by thaJeztah** [comment]
@Fredjet PLEASE turn of that auto-reply, as it is spamming more than 2500 people with each action in our repository

**Comment by sappster** [comment]
Add the docker installation folder to your **system** path using the environment variable editor and ensure that the path is not too long and getting truncated by windows variable size limits. You can` echo %path%` to ensure that it is complete.

**Comment by dolphinziyo** [comment]
Thank you @sappster as you said it is a problem with the environment variables. 
This happens when using a non administrator account, Docker only add the variables to the Administrator account path.

**Comment by sappster** [comment]
I'm not following. It seems to me that there is an issue with install even from and administrator account; I installed from an administrator account (only account on the system) and the user's path variable was the one set not the system's.

I didn't find an issue raised on github for this - should I create one?

**Comment by Markus88** [comment]
Make sure that you point to the 'start.sh' file (example: "C:\Program Files\Docker Toolbox\start.sh").
If it cannot recognize the file, can it be that Git isn't installed on the machine. Remember to let Docker install Git, during the installation.
