### ISSUE TITLE
Strange docker volume + nginx behaviour

### ISSUE THREAD

**Issue by oleynikd** [docker/docker#17773]
Hi,

I'm facing super strange behaviour with docker ( + docker-compose) + official nginx image.

My system configuration:
```
MacBook Pro (15-inch, Late 2011)
OSX 10.11.1 (15B42)
Docker version 1.9.0, build 76d6bc9
docker-compose version: 1.5.0
docker-machine version 0.5.0 (04cfa58)
VirtualBox Version 5.0.8 r103449
```

docker info
```
Containers: 2
Images: 12
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 16
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.12-boot2docker
Operating System: Boot2Docker 1.9.0 (TCL 6.4); master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: dev
ID: R52Z:CIA2:BLZO:76OC:CPA3:LO4Y:QUC3:2A7M:SLA7:B5RO:2J5M:P5GZ
Debug mode (server): true
 File Descriptors: 17
 Goroutines: 29
 System Time: 2015-11-06T20:58:13.738312707Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: oleynikd
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

I'm using VirtualBox

The issue is that after first serving a static file nginx stops understanding that it was changed. nginx only knows that the size has changed, but not the content. File is located on mounted on host `volume`

I've recorded a screencast illustrating the issue: https://dl.dropboxusercontent.com/u/14522796/docker_nginx_fs.mov

If I delete the file, try to access it in nginx, of course it will throw 404. Then if I'll recreate it - nginx will serve it correctly but only until the first modification.

I tried to recreate VB Machine - didn't helped. Also I'm facing the same issue on other Computer so I guess my own file system's issues can be excluded.

Maybe it's a known issue, but I can't find any info about it. Also I'm not sure if it's nginx issue or docker's.

Please help!

**Steps to reproduce the issue:**

1. `docker run -v /some/folder/with/index.html/:/usr/share/nginx/html:ro -p 80:80 -d nginx`
2. Open browser and take a look on docker host ip to see `index.html`
3. Modify `index.html`
4. Refresh browser. Voila

Results you will se - output in browser did not changed
Expected results - see modifications in browser

**Comment by oleynikd** [comment]
Dear @GordonTheTurtle I'm sorry, I've updated the issue.

Also I tried the same configuration with [httpd official image](https://hub.docker.com/_/httpd/) - everything works fine! So for now issue appears only with [nginx](https://hub.docker.com/_/nginx/)

**Comment by cpuguy83** [comment]
See https://abitwiser.wordpress.com/2011/02/24/virtualbox-hates-sendfile/ for an exaplaination.
Closing at this is not a docker issue.

**Comment by oleynikd** [comment]
Thank you. This solved the issue
