### ISSUE TITLE
AppArmor "Invalid Regex" error while setting docker to complain mode

### ISSUE THREAD

**Issue by venkatramachandran** [docker/docker#17783]
```
venkat@instance-2:~$ sudo docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64
Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64
venkat@instance-2:~$ sudo docker info
Containers: 3
Images: 15
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 21
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-28-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 3.614 GiB
Name: instance-2
ID: OMLM:5CYV:RIJX:JTKX:66AF:OUMV:CTA7:6P73:76FH:PQYH:PLR5:PJBW
WARNING: No swap limit support
venkat@instance-2:~$ uname -a
Linux instance-2 3.19.0-28-generic #30~14.04.1-Ubuntu SMP Tue Sep 1 09:32:55 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

While running apparmor to set docker to complain mode, I get a regex validation error:

```
venkat@instance-2:~$ sudo aa-complain /etc/apparmor.d/docker 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apparmor/aa.py", line 2910, in parse_profile_data
    re.compile(p_re)
  File "/usr/lib/python3.4/re.py", line 219, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.4/re.py", line 288, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.4/sre_compile.py", line 465, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.4/sre_parse.py", line 751, in parse
    raise error("unbalanced parenthesis")
sre_constants.error: unbalanced parenthesis
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/sbin/aa-complain", line 30, in <module>
    tool.cmd_complain()
  File "/usr/lib/python3/dist-packages/apparmor/tools.py", line 154, in cmd_complain
    apparmor.read_profiles()
  File "/usr/lib/python3/dist-packages/apparmor/aa.py", line 2594, in read_profiles
    read_profile(profile_dir + '/' + file, True)
  File "/usr/lib/python3/dist-packages/apparmor/aa.py", line 2620, in read_profile
    profile_data = parse_profile_data(data, file, 0)
  File "/usr/lib/python3/dist-packages/apparmor/aa.py", line 2912, in parse_profile_data
    raise AppArmorException(_('Syntax Error: Invalid Regex %(path)s in file: %(file)s line: %(line)s') % { 'path': path, 'file': file, 'line': lineno + 1 })
apparmor.common.AppArmorException: 'Syntax Error: Invalid Regex @{PROC}/{*,**^[0-9*],sys/kernel/shm*} in file: /etc/apparmor.d/docker line: 16'
```

This seems to stem from the apparmor.go changes in 7342d59114fe443ae8d59474abb59280f014c493 .

I am using apparmor version 2.8.95 on Google Compute Engine.

```
venkat@instance-2:~$ sudo dpkg -s apparmor | head -12
Package: apparmor
Status: install ok installed
Priority: extra
Section: admin
Installed-Size: 1183
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Version: 2.8.95~2430-0ubuntu5.3
Replaces: apparmor-parser, apparmor-utils (<< 2.8.0-0ubuntu28), libapache2-mod-apparmor (<< 2.5.1-0ubuntu3)
Depends: libc6 (>= 2.14), debconf (>= 0.5) | debconf-2.0, python3, libapparmor-perl, lsb-base, initramfs-tools, debconf
Suggests: apparmor-profiles, apparmor-docs, apparmor-utils
Breaks: apparmor-easyprof-ubuntu (<< 1.1.14), apparmor-utils (<< 2.8.0-0ubuntu28), libapache2-mod-apparmor (<< 2.5.1-0ubuntu3), libvirt-bin (<< 1.2.2-0ubuntu9~), lightd
m (<< 1.9.14-0ubuntu2~), lxc (<< 1.0.2-0ubuntu2~)
```

Is there some dependency I am missing that is causing this error?

**Comment by datakid** [comment]
+1 am seeing this issue today. On Ubuntu 14.04.3, completely up to date, 
```
Package: apparmor
Status: install ok installed
Priority: extra
Section: admin
Installed-Size: 1183
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Version: 2.8.95~2430-0ubuntu5.3
Replaces: apparmor-parser, apparmor-utils (<< 2.8.0-0ubuntu28), libapache2-mod-apparmor (<< 2.5.1-0ubuntu3)
Depends: libc6 (>= 2.14), debconf (>= 0.5) | debconf-2.0, python3, libapparmor-perl, lsb-base, initramfs-tools, debconf
Suggests: apparmor-profiles, apparmor-docs, apparmor-utils
Breaks: apparmor-easyprof-ubuntu (<< 1.1.14), apparmor-utils (<< 2.8.0-0ubuntu28), libapache2-mod-apparmor (<< 2.5.1-0ubuntu3), libvirt-bin (<< 1.2.2-0ubuntu9~), lightdm (<< 1.9.14-0ubuntu2~), lxc (<< 1.0.2-0ubuntu2~)
```

```
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64
```
I got it working by commenting out the line with the Invalid regex, line 16 in /etc/apparmour.d/docker:

``` 
   #deny @{PROC}/{*,**^[0-9*],sys/kernel/shm*} wkx,
```

**Comment by thinking-aloud** [comment]
I have the same error on Ubuntu server 14.04.3

**Comment by reece** [comment]
Same on 15.10

**Comment by AxelVoitier** [comment]
I am also affected on Ubuntu server 14.04.3. I reverted the changes made in 7342d59 and I was able to run `aa-complain docker`.

**Comment by MBoretto** [comment]
I have this problem on ubuntu 15.10 as well. But Uncommenting line 16 and retyping 
```
sudo aa-complain /etc/apparmor.d/docker
```
as expalined by @datakid, I always got 
```
Syntax Error: Invalid Regex @{PROC}/{*,**^[0-9*],sys/kernel/shm*} in file: /etc/apparmor.d/docker_bak line: 16
```
I try
```
sudo systemctl restart docker
```
Then the file is reloaded uncommented as before.

**Comment by MBoretto** [comment]
I resolve it following the instruction in this repo:
https://github.com/mconcas/docks#allow-docker-container-to-call-ptrace
Hope to be useful

**Comment by thuandt** [comment]
I faced same problem

```
sudo aa-complain /usr/sbin/tcpdump

Syntax Error: Invalid Regex @{PROC}/{*,**^[0-9*],sys/kernel/shm*} in file: /etc/apparmor.d/docker line: 17

```

**Comment by jfrazelle** [comment]
I will take a look today or tomorrow thanks

**Comment by jfrazelle** [comment]
can you all runn apparmor_parser --version for me thanks

**Comment by datakid** [comment]
user@footscray:~$ apparmor_parser --version
AppArmor parser version 2.8.95
Copyright (C) 1999-2008 Novell Inc.
Copyright 2009-2012 Canonical Ltd.

**Comment by jfrazelle** [comment]
as I suspected.... ok I know the fix :)

**Comment by jfrazelle** [comment]
will do tomorrow

**Comment by thuandt** [comment]
```
apparmor_parser --version
AppArmor parser version 2.10
Copyright (C) 1999-2008 Novell Inc.
Copyright 2009-2012 Canonical Ltd.
```

**Comment by AxelVoitier** [comment]
```
$ apparmor_parser --version
AppArmor parser version 2.8.95
Copyright (C) 1999-2008 Novell Inc.
Copyright 2009-2012 Canonical Ltd.
```

**Comment by venkatramachandran** [comment]
```
$ apparmor_parser --version
AppArmor parser version 2.8.95
Copyright (C) 1999-2008 Novell Inc.
Copyright 2009-2012 Canonical Ltd.
```

**Comment by jfrazelle** [comment]
opened https://github.com/docker/docker/pull/18239 to fix this, thanks for
the patience

**Comment by cboltz** [comment]
For the records: the regex is not really invalid, but it triggers a bug in the AppArmor utils (aa-*). apparmor_parser will happily accept the regex.

However I'm afraid the regex does something else than you expect ;-)

The changed regex

        deny @{PROC}/{*,**^[0-9]*,sys/kernel/shm*} wkx,

will match paths like
- the `sys/kernel/shm*` part:
    - /proc/sys/kernel/shm* - not surprising and probably correct
- the `*` part:
    - /proc/foo
    - /proc/xy
    - -> all /proc/* files, but not directories or subdirectories
- the  `**^[0-9]*` part:
    - /proc/foo/bar/baz^1_foo
    - /proc/foo^1a
    - /proc/foo/bar/^1asdf
    - /proc/foo/bar/baz^1asdf
    - -> every filename in /proc that contains ^ followed by a digit - but I've never seen such a strange filename in /proc

I slightly ;-) doubt this is what you want, especially the `**^[0-9]*` part. Since this is a deny rule, this might mean that the profile doesn't deny something that should be denied.

If my guess is right, I'll happily help to find a better regex.

.

Christian (from AppArmor upstream)

**Comment by thaJeztah** [comment]
ping @jfrazelle ^^

(Thanks @cboltz)

**Comment by jfrazelle** [comment]
ping @ewindisch what was the original use case for the 0-9?

**Comment by jfrazelle** [comment]
oh nevermind I see what its trying to do, probably match on dirs that are digits

**Comment by jfrazelle** [comment]
@cboltz should it be `[^0-9]`?

**Comment by cboltz** [comment]
That will match a single non-digit - but with the `**` before and `*` after, that doesn't mean much since the `**` or `*` can still match non-digits as long as the filename contains at least one non-digit.

`/proc/**[^0-9]*` will match /proc/foo, but also /proc/foo/bar1baz. Basically nearly everything in /proc will match - which is probably more than you want.


To match dirs that are digits (which probably means you are looking for `/proc/<pid>/**`?), I'd use `@{PROC}/@{pids}/**` (the @{pids} variable will match 1 to 6 digits - see /etc/apparmor.d/tunables/kernel-vars).

If you want to exclude `/proc/<pid>/**`, a good enough regex is `@{PROC}/[^0-9]**` - it matches files and directories that are directly in /proc (not in a subdir) and start with a digit.

If that is not what you need, please tell me what you want to match (and what not) with some examples ;-)

**Comment by ewindisch** [comment]
Deny writes to all files in proc except the shm files and <pid>/**

**Comment by jfrazelle** [comment]
But but but... you know what I am going to say, I feel like the process
should be able to modify its own pid

**Comment by ewindisch** [comment]
Processes will be able to modify their own pid. In other words:

Allow writes to /proc/<pid>/* and the shm* files and deny everything else.

**Comment by ewindisch** [comment]
@cboltz it seems the intention here of "**^" was to use the apparently-yet-proposed feature of negating regex match entirely according to http://wiki.apparmor.net/index.php/AppArmor_Core_Policy_Reference per 

```
"{**^} - a proposed glob similar to ** with an alternation style list of things is is not allowed to match eg. /etc/{**^shadow} is the same as /etc/** matches - /etc/shadow"
```

This rule should:
* Allow writes to sys/kernel/shm,
* Allow writes to /proc/<pid>/*
* Disallow all other writes

**Comment by cboltz** [comment]
Things would be much easier without the generic "file," rule ;-)

I assume you don't want to drop that "file," rule, which means you'll need an ugly regex ;-)
Well, better two - a simple one and an ugly one:

    deny @{PROC}/* w,   # deny write for all files directly in /proc (not in a subdir)
    # deny write to files not in /proc/<number>/** or /proc/sys/**
    # (/proc/sys/kernel/shm* is what would really be needed, but that would be a monster regex)
    deny @{PROC}/{[^1-9],[^1-9][^0-9],[^1-9s][^0-9y][^0-9s],[^1-9][^0-9][^0-9][^0-9]*}/** w,

Thinking about it, we can get the /proc/sys/kernel/shm* restriction with two more deny rules:

    deny @{PROC}/sys/[^k]** w,  # deny /proc/sys except /proc/sys/k* (effectively /proc/sys/kernel)
    deny @{PROC}/sys/kernel/{?,??,[^s][^h][^m]**} w,  # deny everything except shm* in /proc/sys/kernel/

This is completely untested, but should work.

(Did I already mention that you better should replace the "file," rule with something more restrictive? It will make things much easier.)

That said - yes, we know we need an easy-to-use syntax for "... except ...". It's on the TODO list, but I don't know when it will be implemented. Until then, take the current state as a reminder that allowing everything and excluding some parts with deny rules a) can be ugly and b) is not the recommended way ;-)

**Comment by thaJeztah** [comment]
@cboltz may I add a big *thank you* for thinking along? really great!

**Comment by ewindisch** [comment]
Actually, it seems that sys/kernel/shm* files were made read-only at some point. I'm pretty sure it was once a "feature" that these could be modified. Perhaps it's okay to just allow writes to /proc/[0-9]* and be done with it. It will be far more simple, anyway.

@cboltz I'm not sure why you're suggesting the alternations for the [0-9] matching instead of just doing /proc/[^0-9]* ? There can be more than 9999 pids... (also, yes, thanks for joining this conversation!)

**Comment by ewindisch** [comment]
Also, removing the 'file' won't gain a whole lot. It's a nice idea, but would have to explicitly allow everything except these files in proc...

**Comment by ewindisch** [comment]
@cboltz as an aside, if you're willing to help, the engine-policy itself could use some TLC. It uses 'file' in way too many places because chroot_relative/namespace_relative were mind-bending.

**Comment by cboltz** [comment]
To explain the alternations for the [0-9] matching, let me focus on the relevant part of the regex:

    @{PROC}/{[^1-9],[^1-9][^0-9],[^1-9s][^0-9y][^0-9s],[^1-9][^0-9][^0-9][^0-9]*}/

The alternation parts will match
- `[^1-9]` - /proc/a/ (one char)
- `[^1-9][^0-9]` - /proc/ab/ (two chars)
- `[^1-9s][^0-9y][^0-9s]` - /proc/abc/ (three chars, except if those three chars == "sys")
- `[^1-9][^0-9][^0-9][^0-9]*` - /proc/abcd/ and /proc/abcdeasdfadsfas/ (four and more chars)
- the / at the end ensures that only directory names are matched

.

Removing "file," would have a big advantage - even if you want to allow everything except /proc/, the rules will still be much more readable ;-)

    /{?,??,???,[^p][^r][^o][^c]/** rwmlk,  # all except /proc, all permissions
    /@{PROC}/@{pids}/** rw,

.

For the chroot_relative and namespace_relative stuff, alternations should help (`/{ch/root/,}/etc/`). 

If the same alternation is needed multiple times, define and use a variable instead:

    @{my_basedir} = / /ch/root
    
    /my/profile {
        @{my_basedir}/etc/ r,
    }

Even using `/**/what/ever` can be an improvement if the `/what/ever` part is long and detailed enough (but it's not as good as alternations or variables).

Another option would be to use `flags=(chroot_relative, namespace_relative)` for the whole profile.

That said - I'm happy to help with AppArmor issues, but unfortunately my time is limited, so I can't fix everything in the docker profiles ;-)  Nevertheless, feel free to ping me if you have questions, or ask on #apparmor on oftc.net or the AppArmor upstream mailinglist.

**Comment by ewindisch** [comment]
@jfrazelle it may not be a bad time to consider drop 'file' and using specific allow statements as recommended by @cboltz. The main reason I never did this was because lots of apparmor changes were going in at the time, and I didn't want to rock the boat too hard (and yet I did, anyway, if you recall)

**Comment by jfrazelle** [comment]
hmm ok ya ill try a few things
