### ISSUE TITLE
Update repos for fedora 23

### ISSUE THREAD

**Issue by aanm** [docker/docker#17785]
`https://yum.dockerproject.org/repo/main/fedora/23` link doesn't exist causing installation to fail.
```
+ sudo -E sh -c 'sleep 3; dnf -y -q install docker-engine'
Failed to synchronize cache for repo 'docker-main-repo' from 'https://yum.dockerproject.org/repo/main/fedora/23': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried, disabling.
```

**Comment by thaJeztah** [comment]
yup Fedora 23 was released literally 3 hours after docker 1.9 was released.

This has already been fixed, and RPMs will be pushed for 1.9.1, see https://github.com/docker/docker/pull/17664

**Comment by mmckinst** [comment]
For anyone looking for the RPMs, they're in the testing repo right now. https://yum.dockerproject.org/repo/testing/fedora/23/Packages/

**Comment by thaJeztah** [comment]
@mmckinst those are the release-candidates, so only use them for testing, not on production
