### ISSUE TITLE
docs: warn users about backup software and /var/lib/docker

### ISSUE THREAD

**Issue by fawzi** [docker/docker#17795]
I just installed docker on my laptop with Ubuntu 14.04 and I just got a big scare, as my system ran out of space, and kept using all the space I did free.
This was due to /var/lib/docker/aufs/timeshift using up everything.
It turns out by default timeshift does not skip /var/lib, so one has to add an explicit exclusion.
Not docker fault, but it would be good to have an "head's up" somewhere, in the installation info for ubuntu.

**Comment by unclejack** [comment]
This requires a documentation change to let users know to exclude /var/lib/docker from their backup software.

**Comment by thaJeztah** [comment]
closing per https://github.com/docker/docker/pull/20495#issuecomment-187344218
