### ISSUE TITLE
Tab-Complete for bash throws syntax error

### ISSUE THREAD

**Issue by EyecarePD** [docker/docker#17791]
Hi @albers It looks like at commit 2d44ed6d there was a change to line 758 that broke the bash tab-completion file

#### Steps to Reproduce:
1. [download tab-completion file for docker bash](https://github.com/docker/docker/blob/master/contrib/completion/bash/docker)
2. import docker tab-completion
```bash
source docker-completion.bash
```

#### Actual Results:
```
line 758: syntax error near unexpected token `('
line 758: `*dm.@(blkdiscard|override_udev_sync_check|use_deferred_@(removal|deletion))=*)'
```

#### Expected Results:
import docker-completion and work in bash

#### Additional info:
This is probably not the right solution but, it worked when I rolled back line 758 from:
```shell
*dm.@(blkdiscard|override_udev_sync_check|use_deferred_@(removal|deletion))=*)
```
to:
```shell
*dm.blkdiscard=*)
```

**Comment by albers** [comment]
Hi @EyecarePD,

thanks very much for reporting this issue, and thanks even more for spotting the offending line and change.
As the problem does not surface on my system (and passed unnoticed in code review), I need some more information about your environment.

* what operating system do you use? Is it a Mac?
* which version of bash do you use? (`bash --version`)
* which version of bash completion do you use? (`grep RELEASE /etc/bash_completion` should do)

#dibs

**Comment by IanEdington** [comment]
Thank you. Sorry, I didn't find the other issue when I searched. EyecarePD is guy I manage a repo for; this is my account.

Mac OSX 10.11.1
GNU bash, version 3.2.57(1)

    shopt -p extglob -> shopt -u extglob
    shopt extglob -> off

When I ran ```grep RELEASE /etc/bash_completion``` it said the file didn't exist. The way I turned it on in Mac OSX is by putting ```TAB: menu-complete``` in my ```.inputrc``` file.

If you need more info let me know.

**Comment by albers** [comment]
@IanEdington Thanks for the information. This happens when `extglob` is not set, which seems to be the case on Macs quite frequently. Sorry for the inconvenience. I don't have a Mac at hand, so this slipped through. 

I created a PR that should fix the issue. Please download and source https://raw.githubusercontent.com/albers/docker/fix-17768/contrib/completion/bash/docker.
Please let me know if this fixes the issue for you.

**Comment by IanEdington** [comment]
This seems to have fixed the error for me. Thank you @albers!

**Comment by thaJeztah** [comment]
This should be fixed in https://github.com/docker/docker/issues/17806

Thanks for reporting @EyecarePD !
