### ISSUE TITLE
Support Docker on ARM

### ISSUE THREAD

**Issue by Govinda-Fichtner** [docker/docker#17802]
The demand for Docker on ARM devices is growing as ARM-based IoT devices and ARM-based servers are getting more and more traction. 

In order to properly support Docker on ARM the existing way of building, testing and packaging Docker needs to work on ARM devices. 

That means it should be possible to clone the docker/docker repository on an ARM device and then to execute the appropriate make commands to test, build and package Docker.

**Comment by thaJeztah** [comment]
Thanks for requesting, and yes, we agree. In fact, some preparations have already been made to run CI on ARM

/cc @dieterreuter

**Comment by DieterReuter** [comment]
@thaJeztah We just filed the first PR #17803 to address this new feature/improvement to use the ARM architecture as a first class citizen for Docker.

**Comment by thaJeztah** [comment]
@dieterreuter saw it, awesome!

**Comment by LK4D4** [comment]
We even have arm ci which works perfectly!
