### ISSUE TITLE
upstart and init.d (1.9)

### ISSUE THREAD

**Issue by codezomb** [docker/docker#17812]
I was doing some troubleshooting on why docker was starting before my remote filesystems had mounted, even after applying the changes from https://github.com/docker/docker/pull/17731 to the upstart script. I noticed that the installation had provided both a `/etc/init/docker.conf` as well as `/etc/init.d/docker` script. The init.d script was taking precedence and all settings in the upstart script were being ignored. Removing the init.d script fixed the issue. Is there any reason that both are provided?

**Comment by cpuguy83** [comment]
Most packages provide both, this is because there is no guarantee of the host's init.

**Comment by codezomb** [comment]
> Most packages provide both, this is because there is no guarantee of the host's init.

Providing both is fine, but activating both seems wrong. Especially when one completely overrides the other. This was in ubuntu 15.04. It seems this would be easy enough to detect and make an educated decision on which should be used.

**Comment by cpuguy83** [comment]
ping @tianon
