### ISSUE TITLE
docker exec can not run with redirect command

### ISSUE THREAD

**Issue by HackToday** [docker/docker#17818]
I have a docker instance, and like this

$ docker exec c05825f1b8bf ls -l  /dbdata/testwork
-rw-r--r-- 1 root root 0 Nov  9 02:05 /dbdata/testwork

$ docker exec c05825f1b8bf  echo nicsd > /dbdata/testwork
-bash: /dbdata/testwork: No such file or directory

It seems docker exec can not support echo with redirect commands

**Comment by HackToday** [comment]
$ docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64
$ docker info
Containers: 3
Images: 30
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 36
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-32-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 4
Total Memory: 7.798 GiB
Name: ip9-114-194-111.pok.stglabs.ibm.com
ID: IWKJ:4ZJL:DSJJ:MMQX:32P3:OSJF:WX2L:AQ5J:MHK6:ESNC:5IZI:AX6L
WARNING: No swap limit support
$ uname -a
Linux ip9-114-194-111.pok.stglabs.ibm.com 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux


reproduce the issue:
1.$ docker exec c05825f1b8bf ls -l /dbdata/testwork
-rw-r--r-- 1 root root 0 Nov 9 02:05 /dbdata/testwork

2. $ docker exec c05825f1b8bf echo nicsd > /dbdata/testwork
-bash: /dbdata/testwork: No such file or directory

Expect:
above echo command can work for docker instance.

**Comment by tonistiigi** [comment]
That redirect is handled on the client side, meaning the file is being written on the cli app's filesystem. Try `docker exec c05825f1b8bf sh -c "echo nicsd > /dbdata/testwork"`

**Comment by HackToday** [comment]
Hi @tonistiigi  Thanks. It works. I will close it, it seems not issue.
