### ISSUE TITLE
Unable to remove filesystem [...]/mqueue: device or resource busy

### ISSUE THREAD

**Issue by bboreham** [docker/docker#17823]
We have been trying to figure out some cases where users get this error message when using our product, weave, with Docker 1.9.  This is a repro without any weave containers - just alpine - so the steps may seem a little weird.

`docker version`:
````
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64
````

`docker info`:
````
Containers: 1
Images: 83
Server Version: 1.9.0
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-28-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 3.614 GiB
Name: host5
ID: Y2J3:4YXQ:PJZB:SU2G:TVQG:WMS4:JOAS:OOC2:7RVB:ONPP:NR3Q:V3ZT
WARNING: No swap limit support
````

`uname -a`:
````
Linux host5 3.19.0-28-generic #30~14.04.1-Ubuntu SMP Tue Sep 1 09:32:55 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
````

Environment details: GCE VM

How reproducible: 100%

Steps to Reproduce:
````
$ docker run --name=c1 -v /var/lib/docker/containers:/var/lib/docker/containers -d alpine /bin/sh
e8f88525360b1b74d28326676e1ead149c5191f58800ab0f1e1860023fc8bd4d
$ docker run --name=c2 -td alpine /bin/sh
171ac63b59d57756a21d992ec705b96f4647d85ceaa57d155492be6a885dc437
$ docker cp c1:/etc/hosts /tmp/hosts
$ docker rm -f c2
````

Actual Results:
````
Error response from daemon: Unable to remove filesystem for 171ac63b59d57756a21d992ec705b96f4647d85ceaa57d155492be6a885dc437: remove /var/lib/docker/containers/171ac63b59d57756a21d992ec705b96f4647d85ceaa57d155492be6a885dc437/mqueue: device or resource busy
Error: failed to remove containers: [c2]
````

Expected Results:
````
c2
````

Additional info:

This repro is using `overlayfs`; we have seen the same message using `aufs`

Reference https://github.com/weaveworks/weave/issues/1647, https://github.com/weaveworks/weave/issues/1652

**Comment by cpuguy83** [comment]
In 1.9, /dev/mqueue and /dev/shm are mounted into the container by docker.
I've not seen this error... is weave doing anything with `--ipc=<container>`?

**Comment by bboreham** [comment]
No, nothing with `--ipc`; also note this repro is using nothing beyond Linux, Docker and the `alpine` image.

I checked the same steps with the aufs driver too since filing, on a freshly-created Ubuntu VM.  Same result.

**Comment by bboreham** [comment]
I have looked at what Docker is doing using strace.  It seems that the `cp` mounts all volumes for the dead container c1, and the subsequent `umount` fails, which sets things up for the `rm` to fail.  But I can't see why.

Looking at the code, I'm a bit puzzled why there Docker doesn't unmount `mqueue` and `shm` under normal operation - are you relying on the mounts going away by themselves?  (They seem to, most of the time.)

**Comment by cpuguy83** [comment]
Oh I see... I must have missed it in your original post... you are mounting `/var/lib/docker/containers` and then doing a `cp`, and that's causing the issue. hmmm...

**Comment by bboreham** [comment]
One other thing that maybe isn't clear: we do the mount and the copy in one container, but the `rm` fails on the _other_ container.

(OK, it fails on c1 too, but failing on c2 is the part that actually causes us trouble)

**Comment by cpuguy83** [comment]
Right, because mqueue and shm are mounted in c1

**Comment by rhvgoyal** [comment]
I am not able to see the problem. Trying to create it with fedora image. 

Anyway, so what's the issue. I thought we don't have to do unmounts while we are exiting the container. When mount namespace exits (last process exited), then all the reference to mounts
will be dropped in that namespace. So does that not apply to /dev/mqueue and /dev/shm mounts? I am assuming we are just bind mounting these inside containers. What am I missing?

**Comment by bboreham** [comment]
It happens fully reliably on Ubuntu, e.g. stock 14.04 image on Azure is one I tried fresh.

The problem is that Docker gives a weird error removing `c2`, which did not bind-mount anything special.

Obviously this is triggered by the `c1` bind-mount and `docker cp`, but I am unable to figure out the exact way it is connected.  Also `c1` is dead at the point we do the `docker cp`.

**Comment by rhvgoyal** [comment]
Does it happen only with alpine image. Can you reproduce it with some standard image say busybox, fedora etc? Give me a test case where I can run it and test it and reproduce it. Then I can figure out what's wrong.

**Comment by bboreham** [comment]
Yes, just replace `alpine` with `busybox` and the exact same thing happens.

**Comment by cpuguy83** [comment]
A simpler repro case is:
```
$ mkdir -p test/test2
$ mkdir test2
$ sudo mount --bind test2 test/test2
$ docker run --name test -v $(pwd)/test:/test busybox touch /asdf
$ docker cp test:/asdf /tmp/
$ docker rm -f test
Error response from daemon: Driver aufs failed to remove root filesystem 0652b5addb93777426238acd4abbd70ae6c9ff0c05ca74712baf2514264774f1: rename /mnt/sda1/var/lib/docker/aufs/mnt/0652b5addb93777426238acd4abbd70ae6c9ff0c05ca74712baf2514264774f1 /mnt/sda1/var/lib/docker/aufs/mnt/0652b5addb93777426238acd4abbd70ae6c9ff0c05ca74712baf2514264774f1-removing: device or resource busy
Error: failed to remove containers: [test]
```

**Comment by cpuguy83** [comment]
My first thought: on removal we check the mount table for anything nested under the container's mount dir and unmount that first.

**Comment by rhvgoyal** [comment]
@cpuguy83 I tried your test case with devicemapper graph drvier and I can't see the problem. I can remove container test after cp operation. So may be this is related to graph driver? I will try with overlay too.

**Comment by rhvgoyal** [comment]
@cpuguy83 @bboreham ping

**Comment by cpuguy83** [comment]
@rhvgoyal I think we still want rbind here.
We could make `cp` happen in a new mnt namespace?

**Comment by rhvgoyal** [comment]
@cpuguy83 yes, I realized that by default volumes are bind mounted using recursive flag. That means if any directory has submounts under it, those submounts will be visible inside container if top level directory is used as bind mounted volume. 

https://github.com/docker/docker/blob/master/daemon/execdriver/native/create.go#L291

And that means we can't get rid of `rbind`. So in unmount volumes we will have to unmount these recursively. We can think of calling into umount directly and use option -R. `umount -R`. It seems to be doing the right thing.

**Comment by rhvgoyal** [comment]
@cpuguy83 I think making cp happen in a mnt namespace should work too. So when mount namespace exits, it will automatically cleanup all the mounts. Whatever is easier.
