### ISSUE TITLE
Docker network connect cli has problem connecting a container with portmapping

### ISSUE THREAD

**Issue by coolljt0725** [docker/docker#17824]
When a container has port mappings, it will failed to connect to other network.
Step to reproduce:
<pre><code>$ docker run -d --name test1  -p 5000:5000 busybox top
a2119164c5bee543d7c3cc4e128826290d114c18095dbf268b2014835b625f6b
$ docker network connect test test1
Error response from daemon: failed to create endpoint test1 on network test: Bind for 0.0.0.0:5000 failed: port is already allocated
$
</code></pre>
`docker version`
Client:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.4.2
 Git commit:   e357be4
 Built:        Mon Nov  9 12:25:37 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.4.2
 Git commit:   e357be4
 Built:        Mon Nov  9 12:25:37 UTC 2015
 OS/Arch:      linux/amd64
<pre><code></code></pre>

**Comment by mavenugo** [comment]
ping @sanimej
