### ISSUE TITLE
json log format is lost when using fluentd log driver

### ISSUE THREAD

**Issue by EricFortin** [docker/docker#17830]
I am using nodejs' bunyan module to output my logs in json so I can index them better in elasticsearch. When using fluentd log driver, my json logs get "stringified" so structure is lost. I searched to find a solution using a fluentd plugins but can't. It doesn't seem to be fixable with elasticsearch mapping either.

Would there be a way to tell the driver to use the log as json ?

**Comment by LK4D4** [comment]
ping @tagomoris
Can you answer this question, pls?

**Comment by tagomoris** [comment]
@EricFortin Using `fluent-plugin-parser` with `format json` looks good for your purpose.
https://github.com/tagomoris/fluent-plugin-parser
(It's my product, but I believe that it's major plugin in fluentd community...)

**Comment by tagomoris** [comment]
It's a kind of solution in side of Fluentd.
For now, logging driver receive logs as a (stringified) line. So fluentd logging driver can't handle structured logs natively.

**Comment by EricFortin** [comment]
@tagomoris Thanks for your answer. I never thought about input plugin. I tried to make it work with yours but I don't see how it could be possible as my logs, when outputted by the logging driver are not json anymore. Here's an example of what one log entry looks like when it gets out of node.js :

```json
{
  "name":"myservice",
  "hostname":"01001d3cc173",
  "pid":6,
  "level":30,
  "req":{
    "method":"GET",
    "url":"/routers",
    "headers": {
      "host":"192.168.99.100:32798",
      ...
    },
  },
  "msg":"start",
  "time":"2015-11-09T20:27:07.133Z",
  "v":0
}
```

When fluentd receives it, it looks like so:

```json
"source": "stdout",
"log": 
  "{\"name\":\"myservice\",\"hostname\":\"01001d3cc173\",\"pid\":6,\"level\":30,\"req\": \
   {\"method\":\"GET\",\"url\":\"/routers\",\"headers\": \
   {\"host\":\"192.168.99.100:32798\",\"connection\":\"keep-alive\",...\"}, \
     ...}, \"msg\":\"start\",\"time\":\"2015-11-09T20:27:07.133Z\",\"v\":0}",
"container_id": "01001d3cc173d3af397c9fed69ef879df93b0131c5335135f2a9be3a62b18b19",
"container_name": "/myservice"
```

So using a plugin parser and telling format as json will fail as the value is a string and not json.

Apart from writing my own input plugin or bypassing logging driver(which would remove flexibility), do you see another solution. I kind of made it do what I want by using record_transformer and regexp parsing but that is a bad solution at best as this doesn't scale since it runs multiple regexp on every log input and requires knowing in advance all keys to parse which defeat the purpose of using json in the first place.

**Comment by EricFortin** [comment]
@tagomoris I ended up using your plugin with a custom parser plugin for the log field which basically parses the string as JSON and adds the resulting hash. Will try to put in on github or will post the code here if I don't have enough time to learn how to package it as a gem since I don't really know ruby. Thanks for your help.

**Comment by tagomoris** [comment]
@EricFortin your log looks to have JSON string as an attribute named `log`, isn't it?
Anyway, it's good to hear that you find some solution for your problem.

**Comment by EricFortin** [comment]
@tagomoris Yes the value associated to log is a json inside a string(double quotes are escaped). When I tried your plugin by specifying format json, it wasn't forwarding logs so I assumed it didn't work. Am I mistaken ?

**Comment by tagomoris** [comment]
@EricFortin Probably yes. But I think it's about fluentd (not docker), so it should be followed in Fluentd ML or somewhere else.

**Comment by EricFortin** [comment]
I do agree that the solution does not lie in the log driver as it needs to wrap the log in some way. Thanks for your help.

**Comment by oosidat** [comment]
@EricFortin I'm facing a similar problem as you did (log field has type string, instead of json). From the comments, it appears that you figured out a solution to the problem - can you please share your code/process?

**Comment by EricFortin** [comment]
@oosidat I asked a question on [fluentd](https://groups.google.com/forum/#!topic/fluentd/mkw8bGXybH8) group as suggested. But their suggestion was to fix log generation which is not possible. So I ended up implementing a fluentd parser plugin to parse the string as json.

Here's the code:

```
require 'json'

module Fluent
  class TextParser
    class JsonInStringParser < Parser
      Plugin.register_parser("json_in_string", self)

      config_param :time_format, :string, :default => nil # time_format is configurable

      def configure(conf)
        super
        @time_parser = TimeParser.new(@time_format)
      end

      # This is the main method. The input "text" is the unit of data to be parsed.
      # If this is the in_tail plugin, it would be a line. If this is for in_syslog,
      # it is a single syslog message.
      def parse(text)
        hash = JSON.parse(text)
        time = @time_parser.parse(hash['time'])
        yield time, hash
      end
    end
  end
end
```

And then used it in fluent.conf like so:

```
<filter docker.all>
  type parser
  format json_in_string
  time_format %Y-%m-%dT%H:%M:%S.%L%Z
  key_name log
  reserve_data yes
</filter>
```

**Comment by oosidat** [comment]
Thanks @EricFortin!

**Comment by dionjwa** [comment]
Thanks so much for this, it really helped me.

**Comment by dbousamra** [comment]
FWIW I solved this with the fluentd parser filter as described here: http://docs.fluentd.org/v0.12/articles/filter_parser#reservedata

```xml
<filter docker.**>
  @type parser
  format json
  key_name log
  reserve_data true
  hash_value_field log
</filter>
```

**Comment by EricFortin** [comment]
@dbousamra Honestly, I have to say I totally missed the `hash_value_field` param in the documentation which is really the fix for the issue I had. I tried it this morning and can attest that this solution works. I sort of feel bad. It does have some difference from the plugin I wrote though:

 - It uses a filter parser which has access to a stream interface. This is better.
 - It keeps your json log nested in a member. Not a problem, just adjust elasticsearch mapping(and queries) in my case.
 - It does not handle well log that is not in json. In my plugin, I eventually changed it to:

```
def parse(text)
  begin
    hash = JSON.parse(text)
    time = @time_parser.parse(hash['time'])
  rescue
    hash = {'raw_log' => text}
    time = Engine.now
  ensure
    yield time, hash
  end
end
```

This way, I was guaranteed that my log would always be a single(and json) type and this is important for elasticsearch. With the testing I have done, the standard plugin either logs a warning if not json and keeps it as is(string) or if you configure `suppress_parse_error_log`, it produce and empty `log` member.

If you can guarantee all logs will be json or don't care dropping those that aren't, then @dbousamra's solution is a better one and one I will investigate more as I don't want to maintain a plugin long term.

**Comment by dbousamra** [comment]
@EricFortin Hmm so now I am also running into issues with my approach. Perhaps you have some insight.

I have some JSON being emitted from a docker container via the FluentD driver like:
```
'{"timeMillis":1485917543709,"thread":"main","level":"INFO","loggerName":"com.imageintelligence.ava.api.Boot","message":"{\"dom\":\"DOM\"}","loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":1,"threadPriority":5}'
```
Notice the `message` field is string encoded JSON? When this data is captured by fluentD, it ends up looking like this, as expected:
```json
2017-02-01 06:29:15 +0000 docker.6faad650faa6: {"log":"{\"timeMillis\":1485917543709,\"thread\":\"main\",\"level\":\"INFO\",\"loggerName\":\"com.imageintelligence.ava.api.Boot\",\"message\":\"{\\\"dom\\\":\\\"DOM\\\"}\",\"loggerFqcn\":\"org.apache.logging.slf4j.Log4jLogger\",\"threadId\":1,\"threadPriority\":5}\r","com.amazonaws.ecs.cluster":"dombou","container_id":"6faad650faa6012af4f32df79901b42488543a5e6e53517fe3579b01ab2b6862","container_name":"/upbeat_booth","source":"stdout"}`
```

So I use my approach, or your plugin as a filter, and I end up with semi-sanitized JSON:

```json
2017-02-01 06:32:10 +0000 docker.68c794f7f694: {"source":"stdout","log":{"timeMillis":1485917543709,"thread":"main","level":"INFO","loggerName":"com.imageintelligence.ava.api.Boot","message":"{\"dom\":\"DOM\"}","loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","threadId":1,"threadPriority":5},"com.amazonaws.ecs.cluster":"dombou","container_id":"68c794f7f6948d4261b9497947834651abbf766e9aa51a76f39d6895b7a9ac18","container_name":"/sad_hamilton"}
```json

The issue is, the `message` field is still a string escaped JSON field. Any advice on how I can parse that field as well? How do I stack filters?

**Comment by aniamin** [comment]
@repeatedly @sugimura @sohel2020 

We have some nodejs and python applications that are running as Docker container. When using fluentd log driver, our json logs get "stringified",so structure is lost. I searched to find a solution using a fluentd plugins but can't. It doesn't seem to be fixable with elasticsearch mapping either.

Actual Application Log:

{"cid": "1c2675fc-82dd-4a7d-ae7c-7082d48dabbe", "source": "USSD", "timestamp": "2017-12-21 10:42:23.012765", "action": "USSD_BROWSING", "msisdn": null, "browsing": {"UMBSessionId": null, "response": {"code": 200}, "request": {"url": "http://localhost/", "path": "/", "queryString": ""}}}

When we are using json log driver from Docker, the log is converted as below (When fluentd receives it, it looks like below)


{"source":"stderr","log":"{\"cid\": \"6aca9d54-a4e0-47d9-af24-f9d29b39d262\", \"source\": \"USSD\", \"timestamp\": \"2018-01-07 12:45:45.557018\", \"action\": \"USSD_BROWSING\", \"request_type\": \"browsing\", \"msisdn\": \"8801711082722\", \"UMBSessionId\": \"201801071845450422752340\", \"response\": {\"code\": 302, \"location\": \"/retailer/choice.html\"}, \"request\": {\"url\": \"http://10.172.66.2/ussd/index.php?SessionID=201801071845450422752340&msisdn=8801711082722&service=454\", \"path\": \"/ussd/index.php\", \"queryString\": \"SessionID=201801071845450422752340&msisdn=8801711082722&service=454\"}}","container_id":"51ee5f9a9536c26389dbca75df3fe749486bdf4a504e23462ace58f8908708e4","container_name":"/ussd"}

N.B: We are using tail inside <source> directive to read the logs from `/var/lib/docker/containers/*`

Here I am mentioning how do we want to process our logs:


1) We are tailing all messages from /var/lib/docker/containers/*

 <source>
	@type tail
	path /var/lib/docker/containers/*
	tag x
 </source>

2) Want to work with message only with some special parameter (Example: source\": \"USSD)
 <filter x>
 	@type grep

 	tag y
 </filter>

3) Want to remove unwanted back slash
  <filter y>
	 @type parser
	 format json
	 key_name log
	 reserve_data true
	 hash_value_field log
	 tag z
   </filter>

N.B: You have already helped me giving an example for forward plugin. We found it little difficult to work with tail.

4) Flatten Nested Json value:

	<filter z>
	  @type flatten_hash
	</filter>

5) Output the value in stdout or elasticsearch

	<match z>
  	  @type stdout
	</match>

 I have given our input log sample. Would be a great If you can help me by instructing me how the fluent config file should be.
@EricFortin @dbousamra @tagomoris

**Comment by thaJeztah** [comment]
> N.B: We are using tail inside directive to read the logs from /var/lib/docker/containers/*

That's the basic issue; the files inside `/var/lib/docker` are designed for exclusive access to docker. The `json-file` logging driver uses the log files you're tailing as its internal storage format (where logs from the container are stored in a JSON format; docker adds additional data to the logs, so that (e.g.) `docker logs --since ...` can filter on timestamp.

> When using fluentd log driver, our json logs get "stringified",so structure is lost.

Can you elaborate? You mention two things; 1) you're using  the `json-file` driver, and `tail` to get the container logs, and 2) you're using the Fluentd logging driver

If you're using the `json-file` logging driver, and `tail`; have you tried using the `fluentd` logging driver instead? https://docs.docker.com/engine/admin/logging/fluentd/

**Comment by EricFortin** [comment]
@thaJeztah The issue I originally filed, and I guess the reason @aniamin landed here, is when using `fluentd` log driver. As I alluded in one of my reply, I understand(and want) that docker daemon wants to add some context to my log like container id, name, etc. And that to do it, it needs some form of structured data. The problem here is that it destroys my own structured data in the process. It would be nice if the log driver had an option to tell it that logs will come in already structured and it could just put it under a `log` member as is instead of putting it in a string and escaping it.

**Comment by aniamin** [comment]
@thaJeztah
We have initially started with fluent log driver where other containers were dependent of fluentd container in my docker-compose.yml. In this way container was not working if my fluent container became down.

Then We have tried with the json-file logging driver where containers were running in its way and generating logs. Fluentd is running as a separate container and tailing the log file of docker container.

Here I am mentioning how do we want to process our logs. 

> 1. Tail container log
> 2. Grep with specific message and proceed with those logs only
> 3. Remove unwanted back slash from nested json
> 4. Flatten Json message from nested json
> 5. Match output to stdout or elasticsearch

**Sudo config file is given below for your convenience:**

1) We are tailing all messages from `/var/lib/docker/containers/*` like below:
 ```
<source>
	@type tail
	path /var/lib/docker/containers/*
	tag x
 </source>
```
2) Want to work with message only with some special parameter (Example: source\": \"USSD)
 ```
<filter x>
 	@type grep
 	tag y
 </filter>
```
3) Want to remove unwanted back slash
  ```
<filter y>
	 @type parser
	 format json
	 key_name log
	 reserve_data true
	 hash_value_field log
	 tag z
   </filter>
```
4) Flatten Nested Json value:
```
<filter z>
	  @type flatten_hash
</filter>
```
5) Output the value in stdout or elasticsearch
```
<match z>
  	  @type stdout
</match>

```
 **I have given our input log sample. Would be a great help If you can help me by instructing me how the fluent config file should be. **

@EricFortin As I have seen you facing the similar type of problem, I wanted to see If you could find any way around for this. Would be super helpful If you can provide me a sample config that will serve my purpose. If you want to suggest any better way around, You are most welcome.

**Application Log:**
`{"cid": "1c2675fc-82dd-4a7d-ae7c-7082d48dabbe", "source": "USSD", "timestamp": "2017-12-21 10:42:23.012765", "action": "USSD_BROWSING", "msisdn": null, "browsing": {"UMBSessionId": null, "response": {"code": 200}, "request": {"url": "http://localhost/", "path": "/", "queryString": ""}}}`

**Final Expected Log:**
`{"cid": "1c2675fc-82dd-4a7d-ae7c-7082d48dabbe", "source": "USSD", "timestamp": "2017-12-21 10:42:23.012765", "action": "USSD_BROWSING", "msisdn": null, "browsing.UMBSessionId": null, "browsing.response.code": 200, "browsing.request.url": "http://localhost/", "browsing.request.path": "/", "browsing.request.queryString": ""}`

**Comment by thaJeztah** [comment]
The `jq` utility (https://stedolan.github.io/jq/) may be useful for that; taking your earlier example of a log entry;


```bash
echo '{"source":"stderr","log":"{\\"cid\\": \\"6aca9d54-a4e0-47d9-af24-f9d29b39d262\\", \\"source\\": \\"USSD\\", \\"timestamp\\": \\"2018-01-07 12:45:45.557018\\", \\"action\\": \\"USSD_BROWSING\\", \\"request_type\\": \\"browsing\\", \\"msisdn\\": \\"8801711082722\\", \\"UMBSessionId\\": \\"201801071845450422752340\\", \\"response\\": {\\"code\\": 302, \\"location\\": \\"/retailer/choice.html\\"}, \\"request\\": {\\"url\\": \\"http://10.172.66.2/ussd/index.php?SessionID=201801071845450422752340&msisdn=8801711082722&service=454\\", \\"path\\": \\"/ussd/index.php\\", \\"queryString\\": \\"SessionID=201801071845450422752340&msisdn=8801711082722&service=454\\"}}","container_id":"51ee5f9a9536c26389dbca75df3fe749486bdf4a504e23462ace58f8908708e4","container_name":"/ussd"}' | jq '.log | fromjson | .'
```

Which outputs

```json
{
  "cid": "6aca9d54-a4e0-47d9-af24-f9d29b39d262",
  "source": "USSD",
  "timestamp": "2018-01-07 12:45:45.557018",
  "action": "USSD_BROWSING",
  "request_type": "browsing",
  "msisdn": "8801711082722",
  "UMBSessionId": "201801071845450422752340",
  "response": {
    "code": 302,
    "location": "/retailer/choice.html"
  },
  "request": {
    "url": "http://10.172.66.2/ussd/index.php?SessionID=201801071845450422752340&msisdn=8801711082722&service=454",
    "path": "/ussd/index.php",
    "queryString": "SessionID=201801071845450422752340&msisdn=8801711082722&service=454"
  }
}
```

jq also allows you to filter based on attributes (see https://stedolan.github.io/jq/manual/#Basicfilters)


The general problem you're describing for your use-case looks to be two-fold:

Docker makes no assumption about the logs sent by a container; logs from a container are what's sent to `stdout` and `stderr`, which is just text. If your container sends `JSON` to `stdout`/`stderr`, it's still text (but has a special meaning for your use). I think this is the correct behaviour; Docker should not make any assumptions about the output of a container; the only behaviour is that logs are line-delimited


> The problem here is that it destroys my own structured data in the process.

Docker sends logs to Fluentd as JSON; the `.log` attribute contains the raw data that's received from the container, but has to be encoded to make the whole JSON that's sent valid (which, in case of textual output, means escaping characters - which is the case if that text happens to be JSON)

Fluentd receives the logs as JSON, but (by default?) does not have a feature to view the RAW `.log` property. I don't have personal experience using Fluentd, but I see there's a massive list of plugins, including plugins to handle JSON manipulation (I see there's even one that's using the forementioned `jq`: https://github.com/winebarrel/fluent-plugin-filter-jq, which would likely make it easy to replace the original message with the decoded message of the nested JSON.


If Fluent also can accept non-structured logs (i.e. just receive the RAW data as output from the container, without the additional meta-data being sent to Fluentd), a `fluentd-format=raw` option could be added. A similar option was added for the Splunk logging driver; https://github.com/moby/moby/pull/25786

This option should still work if Fluentd only accepts JSON logs (and your container already outputs JSON), but there would be a risk if the container's output invalid JSON.

**Comment by EricFortin** [comment]
@thaJeztah I wasn't aware of the splunk log driver but this kind of option would be exactly what we need for the fluentd one. Having a way to tell the driver that logs are already formatted as json and having it embedding it inside its own json document would be great.

**Comment by EricFortin** [comment]
@thaJeztah I don't have all the details about how it works in the splunk log driver but from the PR

> `json` - driver will try to parse each line as a JSON object and embed it
inside of the JSON payload

If it doesn't parse, it could continue working as is, wrapping it in a string and escaping, or better yet putting it in a log_raw like my fluentd plugin is doing. This way, fluentd would be able to work with inner log members too.

**Comment by anusha-ragunathan** [comment]
@thaJeztah : I agree that if fluend cannot parse the json, it could send it over as a string, which is what it is doing now. This is akin to the splunk json parsing behavior.

**Comment by lironmo** [comment]
@EricFortin 
have the same issue.

did you able to fix it?

**Comment by Sushma569** [comment]
@EricFortin, After adding JSON filter in td-agent, do I need to restart td-agent/fluentd? Because I won't see any changes to message after adding filter

**Comment by pvalois** [comment]
hello Oosidat, where do you put this Ruby script ? 
i get this error : 

 error_class=Fluent::ConfigError error="Unknown format template 'json_in_string'"

**Comment by arik555** [comment]
Do not use any filter with @type parser
Just use the below conf. and give it a try.

```
<filter *.**>
  @type record_transformer
  enable_ruby true
  <record>
    record ${ begin; JSON.parse(record); rescue; {}; end; }
  </record>
</filter>
```
