### ISSUE TITLE
Types of errors docker in Windows?

### ISSUE THREAD

**Issue by farhadibehnam** [docker/docker#17831]
When I began to start docker it stuck and there are so many bad problem with it

System: Windows 8.1 64-bit

I replace virtualbox 5.0.6 to virtualbox 5.0.7 Still, there's an error

Error One:

**When Docker Quickstart Terminal want to begin Starting VM... is hanging.**

Error two

I test my installation with docker run hello-world I get the following:

**Post http://127.0.0.1:2375/v1.20/containers/create: dial tcp 127.0.0.1:2375: ConnectEx tcp: No connection could be made because the target machine actively refused it.. * Are you trying to connect to a TLS-enabled daemon without TLS? * Is your docker daemon up and running?**

Error three

Kinematic doesn't work It work until 99% BUT suddenly it doesn't work

**Machine IP could not be fetched. Please retry the setup. If this fails please file a ticket on our GitHub repo.**

**Comment by thaJeztah** [comment]
This sounds more like a Toolbox issue. Could you search the toolbox issues if an issue exists for this, or otherwise open it there? Thanks! https://github.com/docker/toolbox/issues
