### ISSUE TITLE
docker on btrfs and ubuntu 14.04 LTS / kernel 3.13 will grow btrfs subvolumes and apparently not delete them properly until it runs out of space

### ISSUE THREAD

**Issue by JonasT** [docker/docker#17839]
Apparently, docker on btrfs and ubuntu 14.04 lts / kernel 3.13 will create subvolumes and they will grow and grow until it runs out of space. The only way for me to work around this is currently to reinstall docker every 48 hours.

**My setup in more detail**: I had a 50GB HDD, and nothing notable except docker-engine and docker-compose installed on the main system, so the system files were around 15GB. I have all my data volumes in one folder, which was less than 10gb. In overall, the system was sitting between 20 and 30GB in total disk usage a few months ago. Since then, I didn't add any notable amount of files. I checked today, my volumes folder is still below 10GB. However, the system was *completely out of disk space*. At this point, `docker ps -s` shows still *less than 10GB* in summary for all containers. I deleted all unused containers in `docker ps -a`. I deleted all unused images (by simply deleting all of them without -f, so docker deleted all that weren't in explicit use by my containers), and the dangling image list showed no images. The disk is **still almost full**.

**How I managed to resolve it:** After manually deleting all btrfs subvolumes in /var/lib/docker/subvolumes/ and entirely wiping docker and /var/lib/docker, the problem is resolved temporarily - until stuff has grown back...

**System information:**

```
root@Ubuntu-1404-trusty-64-minimal ~ # docker info
Containers: 7
Images: 139
Storage Driver: btrfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-65-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 2
Total Memory: 1.955 GiB
Name: Ubuntu-1404-trusty-64-minimal
ID: ERML:VEZB:Z3JD:IPJW:BNMM:NYIS:VLGE:TEDW:46AI:EYDU:AGB3:W7E2
WARNING: No swap limit support
root@Ubuntu-1404-trusty-64-minimal ~ #
```
Docker version: Docker version 1.8.3, build f4bf5c7
uname -a: Linux Ubuntu-1404-trusty-64-minimal 3.13.0-65-generic #106-Ubuntu SMP Fri Oct 2 22:08:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cpuguy83** [comment]
Are you using docker-in-docker with btrfs? There was an issue with deleting nested subvolumes, I think this is resolved in 1.9.

Are you sure you didn't have dangling images?

**Comment by JonasT** [comment]
Judge for yourself:
```
root@Ubuntu-1404-trusty-64-minimal /var # docker images --filter "dangling=true"
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
root@Ubuntu-1404-trusty-64-minimal /var #
```
This is 1. after deleting stuff from ```docker images``` already (so there might have been dangling things before), however 2. the disk was still exhausted at this point so this is at a point in time where the disk is magically kept exhausted by docker despite of like 80% of the containers and images deleted and as you can see nothing dangling left around that should cause this. Docker was still holding my disk space hostage and only manually wiping entire /var/lib/docker helped.

---
As a side note, will you finally introduce some `docker clean-up-all-the-old-junk` command to easily wipe all unused containers and images in one go? Forgetting/postponing to do this as a server admin (which happens easily, given howcumbersome this is to do manually right now) can lead to some serious free disk space problems even when bugs like this one here are finally fixed.

**Comment by cpuguy83** [comment]
Not sure how forgetting to do it and there being one command instead of 2 is going to help.
Unfortunately docker itself can't just clean things up since it's impossible to know what's legit and what's not. A higher level orchestration system can do this.

Do you use docker in docker?
Are you sure it is the btrfs volume running out of space?
Is /var/lib/docker/volumes on the btrfs volume?

**Comment by JonasT** [comment]
> Not sure how forgetting to do it and there being one command instead of 2 is going to help.

You mean two commands where you then need to manually copy all of the 50 id entries like a brainless monkey for deletion, or write some awk hacks or copy them from some website. It's simply not very practical right now.

> Unfortunately docker itself can't just clean things up since it's impossible to know what's legit and what's not. A higher level orchestration system can do this.

While this is true in a strictly speaking manner, many people have a pretty simple system: all containers that are stopped can be deleted and all images not used by containers any more without any special tags can be deleted too.

That system pretty simple, and very common. (All my friends whom I found using docker use this with very few exceptions) While I agree it's not necessarily the only way, it seems sensible to provide a more useful command for people using this approach. Make it require a --force and spit out angry red text as a warning, but at least it should be only one command instead of the current fiddling and manual deletion command for each of the 50 old containers or images I have lying around. Don't make it harder than it needs to be

> Do you use docker in docker?

No, this setup where the bug occured is a KVM with one large btrfs volume/partition, and I'm running docker there. There's no docker in docker stuff or anything, just a KVM machine where I installed docker for direct use of some more or less straightforward containers.

> Are you sure it is the btrfs volume running out of space?```

Yes, there is only one single partition with one single btrfs volume (except for /boot), and I simply got "no space left on device" for any terminal command that tries to anything non-trivial and the system was filled to the limits with all of the 50GB space. 

> Is /var/lib/docker/volumes on the btrfs volume?

Yes, and docker made subvolumes in there which in the end I had to manually delete along with /var/lib/docker to finally get my disk space back! None of the container or image deletions would free any of it - which it should have, right?

**Comment by cpuguy83** [comment]
@JonasT `docker rm $(docker ps -aq)` and `docker rmi $(docker images --filter dangling=true)`. There shouldn't be a need to copy/paste individual id's, unless I'm missing something?

> Yes, and docker made subvolumes in there which in the end I had to manually delete along with /var/lib/docker to finally get my disk space back! None of the container or image deletions would free any of it - which it should have, right?

Docker doesn't create any subvolumes in `/var/lib/docker/volumes`, what it does have is volumes used by containers when doing `docker run -v`, or images that have volumes implicitly (ie, `VOLUME` in a Dockerfile).
Removing a container does not remove data from here, unless you do so explicitly with `docker rm -v`.
This can also be managed, in docker 1.9, by it's own subcommand via `docker volume ls`, `docker volume rm`, etc.

**Comment by JonasT** [comment]
> docker rm $(docker ps -aq) and docker rmi $(docker images --filter dangling=true). There shouldn't be a need to copy/paste individual id's, unless I'm missing something?

That is what I meant by "or write some awk hacks or copy them from some website". This sort of shell script hackery should not be necessary just to remove all old containers and images.

> Docker doesn't create any subvolumes in /var/lib/docker/volumes, what it does have is volumes used by containers when doing docker run -v, or images that have volumes implicitly (ie, VOLUME in a Dockerfile).

But it does in /var/lib/docker/subvolumes or somewhere

> Removing a container does not remove data from here, unless you do so explicitly with docker rm -v.
This can also be managed, in docker 1.9, by it's own subcommand via docker volume ls, docker volume rm, etc.

See? **Yet another pitfall** in cleaning up, another detail to know. I am using docker for a year now in production with lots of containers, and I still don't know *all of the required details* just to clean the crap up it leaves everywhere in regular use! Don't you think that's a problem?? There really needs to be an easier command that does all of this.

**Comment by cpuguy83** [comment]
> That is what I meant by "or write some awk hacks or copy them from some website". This sort of shell script hackery should not be necessary just to remove all old containers and images.

This is not shell hackery, or even using any external tools like awk. It's common, quite versatile, and really great for automating things.

re: subvolumes

BTFS stores stuff in `/var/lib/docker/btrfs/subvolumes`
This is where image and container layers live (for btrfs).
Unless there was some error, when you remove a container/image, it should be removing the subvolume.
If there are dirs in here and you don't have any containers images, please check `docker ps -a` and `docker images -a`.
Also note that images are made up of many layers (typically), each layer is it's own subvolume.
If data is still not freed up, you may need to rebalance your btrfs volumes.

There is also `/var/lib/docker/volumes`, which is for persistent local storage (volumes).

With regard to cleanup, it really is impossible for Docker to know what to clean up. People use stopped containers, people have persistent data (which can and should live beyond the life of a single container, otherwise why do you have a volume?), images that could get used at any time, etc.

**Comment by cpuguy83** [comment]
A note about reblancing btrfs voumes: http://marc.merlins.org/perso/btrfs/post_2014-05-04_Fixing-Btrfs-Filesystem-Full-Problems.html

**Comment by JonasT** [comment]
I'm now down to 13GB from previously 50GB with *the exact same containers* and volume data, I just rebuilt my services. All I did was wipe /var/lib/docker, including all subvolumes inside, and reinstalling the whole thing.

(and as I commented above, nope deleting the stopped containers and unused images before did **nothing**. And yes, I had no dangling images left, as you can also see above)

Unless your opinion is that I should be required to do that every 2-3 months, maybe it would be worth looking into this issue..

**Comment by cpuguy83** [comment]
@JonasT I'm looking at this issue, this is why I'm commenting, the issue is still open.

If you rebuilt all your services and are now back at full capacity, then it seems like this is steady state for your workload.

**Comment by JonasT** [comment]
I'm still having this issue and investigated it more closely.

My containers are set up as follows:
- all VOLUME-mentioned things are mounted into a single folder `/root/.docker-services/` which is less than 7GB
- none of my containers has access to the docker socket or is privileged, so nothing fiddles with docker in normal operation mode

This is the timeline of things happening:

### Initial state:
```
Total system usage: ~60GB
`/var/lib/docker`: ~50GB
`/root/.docker-services/`: 6-7GB
```

### Trying to fix things the usual way:
All containers running, I'm again out of disk space:  uses up ~50GB, disk is full. `/root/.docker-services/` is between 6-7GB as usual. I did the following three things:

1. I listed all containers with `docker ps -a`, and used `docker rm` on all of them without `-f` (so effectively removing the stopped ones),

2. I run `docker rmi $(docker images -aq)`

3.  I list `docker volume ls -qf dangling=true` and use `docker volume rm <id>` on all the listed results.

The result: I get <2GB of free space, so /var/lib/docker is now still at >45GB usage and `/root/.docker-services/` at 6-7GB as usual - pretty much **no change**.
```
Total system usage: ~59GB
`/var/lib/docker`: ~49GB
`/root/.docker-services/`: 6-7GB
```

### Getting out the big guns again (docker wipe & reinstall!):
I stop all containers and the docker daemon, then I run `apt-get remove --purge docker-engine`, and then `btrfs subvolume delete /var/lib/docker/btrfs/subvolumes/*`, and then `rm -rf /var/lib/docker`. Then I reinstall docker with `apt-get install docker-engine` and I rebuild all containers and services and launch them again. **Please note at this point I would highly expect the disk usage to be back at the old usage as before** (~50GB in /var/lib/docker), however suddenly my *entire system* with docker and Linux itself uses only 18GB in total *including* all containers set up and running exactly as before.
```
Total system usage: ~18GB
`/var/lib/docker`: <12GB
`/root/.docker-services/`: 6-7GB
```

### Stuff slowly growing back
This evening, roughly 12 hours later, I am observing the following and as you can see all my manually mounted volumes have not grown at all, however docker's storage has:
```
Total system usage: ~24GB
`/var/lib/docker`: notably larger (btrfs reports some slightly confusing values, probably because of the way subvolumes are counted)
`/root/.docker-services/`: still at 6-7GB with no change
```
Since then, I haven't restarted or build a single container. No server reboot either, I didn't touch it.

However, when I'm now listing `docker ps -s`, all the containers' virtual sizes sum to exactly 1487MB which therefore in total is still much less than the increase I'm seeing. However, **if the increase is not in the containers (docker ps -s), and not in the only writeable volumes I'm mounting (`/root/.docker-services/`), where is it??**

I suppose this should easily explain my confusion, and maybe possibly give you a hint at either what I'm doing wrong or where to investigate further for a possible bug.

Oh and all this started roughly around the time I upgraded to docker 1.8.x, so if it's a bug maybe it's a regression around that ish? I don't know

**Comment by JonasT** [comment]
It has now grown to 35G over night:
```
root@Ubuntu-1404-trusty-64-minimal ~ # df -H /
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda3        50G   35G   14G  72% /
```
The folder with all writable volumes is still between 6-7GB as always:
```
root@Ubuntu-1404-trusty-64-minimal ~ # du -c -h -d 0 /root/.docker-services/
6.4G	/root/.docker-services/
6.4G	total
```
.. and in `docker ps -s`, I can't see any notable growth of any of the running containers either:
```
root@Ubuntu-1404-trusty-64-minimal ~ # docker ps -s
CONTAINER ID        IMAGE                   COMMAND                   CREATED             STATUS              PORTS                                          NAMES                     SIZE
4f39b96fceea        informationnode_nginx   "/bin/sh -c 'sh /laun"    24 hours ago        Up 24 hours         0.0.0.0:443->443/tcp, 80/tcp                   informationnode_nginx_1   3.038 kB (virtual 242 MB)
bbe7e41d1c11        icecast2_icecast2       "/bin/sh -c 'service "    24 hours ago        Up 24 hours         0.0.0.0:8000-8001->8000-8001/tcp               icecast2_icecast2_1       589 B (virtual 354.4 MB)
bce12f18dc95        mumble_mumble           "/bin/sh -c 'chown 10"    24 hours ago        Up 24 hours         0.0.0.0:64738->64738/tcp                       mumble_mumble_1           0 B (virtual 236.2 MB)
0155bf21d8ed        chat_irssi              "/bin/sh -c 'echo \"ir"   24 hours ago        Up 24 hours         0.0.0.0:2222->22/tcp                           chat_irssi_1              299.1 kB (virtual 239.4 MB)
91ec49833150        nginx_nginx             "/bin/sh -c 'chown ro"    24 hours ago        Up 24 hours         0.0.0.0:20-21->20-21/tcp, 0.0.0.0:80->80/tcp   nginx_nginx_1             232.1 kB (virtual 228.5 MB)
ca2ae949b6e1        ipv6test_test           "/bin/sh -c '/bin/bas"    24 hours ago        Up 24 hours         0.0.0.0:66->66/tcp                             ipv6test_test_1           0 B (virtual 186.6 MB)
root@Ubuntu-1404-trusty-64-minimal ~ #
```

**Comment by JonasT** [comment]
Difference over 2-3 hours:

Before:
```
root@Ubuntu-1404-trusty-64-minimal ~ # du -ch -d 1 /var/lib/docker
0	/var/lib/docker/tmp
35G	/var/lib/docker/btrfs
17G	/var/lib/docker/containers
4.5M	/var/lib/docker/graph
0	/var/lib/docker/volumes
0	/var/lib/docker/trust
56K	/var/lib/docker/network
52G	/var/lib/docker
52G	total
root@Ubuntu-1404-trusty-64-minimal ~ # df -H /
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda3        50G   35G   14G  72% /
root@Ubuntu-1404-trusty-64-minimal ~ # docker ps -s
CONTAINER ID        IMAGE                   COMMAND                   CREATED             STATUS              PORTS                                          NAMES                     SIZE
4f39b96fceea        informationnode_nginx   "/bin/sh -c 'sh /laun"    24 hours ago        Up 24 hours         0.0.0.0:443->443/tcp, 80/tcp                   informationnode_nginx_1   3.038 kB (virtual 242 MB)
bbe7e41d1c11        icecast2_icecast2       "/bin/sh -c 'service "    24 hours ago        Up 24 hours         0.0.0.0:8000-8001->8000-8001/tcp               icecast2_icecast2_1       589 B (virtual 354.4 MB)
bce12f18dc95        mumble_mumble           "/bin/sh -c 'chown 10"    24 hours ago        Up 24 hours         0.0.0.0:64738->64738/tcp                       mumble_mumble_1           0 B (virtual 236.2 MB)
0155bf21d8ed        chat_irssi              "/bin/sh -c 'echo \"ir"   24 hours ago        Up 24 hours         0.0.0.0:2222->22/tcp                           chat_irssi_1              299.1 kB (virtual 239.4 MB)
91ec49833150        nginx_nginx             "/bin/sh -c 'chown ro"    24 hours ago        Up 24 hours         0.0.0.0:20-21->20-21/tcp, 0.0.0.0:80->80/tcp   nginx_nginx_1             232.1 kB (virtual 228.5 MB)
ca2ae949b6e1        ipv6test_test           "/bin/sh -c '/bin/bas"    24 hours ago        Up 24 hours         0.0.0.0:66->66/tcp                             ipv6test_test_1           0 B (virtual 186.6 MB)
root@Ubuntu-1404-trusty-64-minimal ~ #
```
After:
```
root@Ubuntu-1404-trusty-64-minimal ~ # du -ch -d 1 /var/lib/docker
0	/var/lib/docker/tmp
35G	/var/lib/docker/btrfs
20G	/var/lib/docker/containers
4.5M	/var/lib/docker/graph
0	/var/lib/docker/volumes
0	/var/lib/docker/trust
56K	/var/lib/docker/network
55G	/var/lib/docker
55G	total
root@Ubuntu-1404-trusty-64-minimal ~ # df -H /
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda3        50G   39G   11G  80% /
root@Ubuntu-1404-trusty-64-minimal ~ # docker ps -s
CONTAINER ID        IMAGE                   COMMAND                   CREATED             STATUS              PORTS                                          NAMES                     SIZE
4f39b96fceea        informationnode_nginx   "/bin/sh -c 'sh /laun"    29 hours ago        Up 29 hours         80/tcp, 0.0.0.0:443->443/tcp                   informationnode_nginx_1   78.25 kB (virtual 242.1 MB)
bbe7e41d1c11        icecast2_icecast2       "/bin/sh -c 'service "    29 hours ago        Up 29 hours         0.0.0.0:8000-8001->8000-8001/tcp               icecast2_icecast2_1       589 B (virtual 354.4 MB)
bce12f18dc95        mumble_mumble           "/bin/sh -c 'chown 10"    29 hours ago        Up 29 hours         0.0.0.0:64738->64738/tcp                       mumble_mumble_1           0 B (virtual 236.2 MB)
0155bf21d8ed        chat_irssi              "/bin/sh -c 'echo \"ir"   29 hours ago        Up 29 hours         0.0.0.0:2222->22/tcp                           chat_irssi_1              299.5 kB (virtual 239.4 MB)
91ec49833150        nginx_nginx             "/bin/sh -c 'chown ro"    29 hours ago        Up 29 hours         0.0.0.0:20-21->20-21/tcp, 0.0.0.0:80->80/tcp   nginx_nginx_1             281.3 kB (virtual 228.5 MB)
ca2ae949b6e1        ipv6test_test           "/bin/sh -c '/bin/bas"    29 hours ago        Up 29 hours         0.0.0.0:66->66/tcp                             ipv6test_test_1           0 B (virtual 186.6 MB)
root@Ubuntu-1404-trusty-64-minimal ~ #
```
As you can see, the containers themselves as listed in `docker ps -s` change barely. Needless to say, my directory containing all the folders for the mounted writable volumes `/root/.docker-services/` is also stable at 6-7GB.

**Comment by JonasT** [comment]
If anyone else should run into the same issue, I'm running this now:
```
#!/bin/sh
docker-services.py stop all
service docker stop
apt-get remove -y --purge docker-engine
cd / && btrfs subvolume del /var/lib/docker/btrfs/subvolumes/*
rm -rf /var/lib/docker
apt-get install -y docker-engine
service docker start
docker-services.py clean
docker-services.py start all
```
(replace ```docker-services.py stop all``` and  ```docker-services.py start all``` with the respective calls to stop and restart all your required containers, it's a little script of mine which basically does just that)

Sadly, it appears I will now need to run this script every 2 days until this issue is resolved. Therefore, any sort of further feedback or investigation would be highly appreciated.

**Comment by JonasT** [comment]
If you have any ideas for diagnostic stuff, I would be very happy to try it.

**Comment by cpuguy83** [comment]
@JonasT What all are you doing? Are you adding/removing images/containers constantly?
Have you looked at rebalancing?

**Comment by JonasT** [comment]
@cpuguy83 again as I wrote above, **I'm not doing anything with the containers except leaving them running untouched** after initially building them. Rebalancing does close to nothing, the space seems to be legitimately filled.

**Comment by cpuguy83** [comment]
@JonasT Docker is not just randomly consuming space.
Are these perhaps coming from container logs?
Log files are stored in `/var/lib/docker/containers/<id>/<id>-log.json`

**Comment by JonasT** [comment]
@cpuguy83 my hero :-)

People have mentioned logs before, but I foolishly thought of /var/log/ inside the containers which should have made them grow (and `docker ps -a` was remaining static all the time). I totally forgot docker stores logs outside of stdout/stderr.

So yes, it was the log of one container spamming around!

*On a slightly related note (lol!)*: will docker log rotation get a higher priority soon? I mean it's not strictly needed, but it could help part-time idiots like me ;-) nobody likes to have their disk unexpectedly filled to the last bit

**Comment by cpuguy83** [comment]
Log rotation is in since 1.8, you can configure it on the daemon with `--log-opt max-size=50M --log-opt max-file=4`, for example.
You can also use syslog/journald/fluentd/gelf/cloudwatch.

**Comment by thaJeztah** [comment]
Also see the documentation for log-rotation here; http://docs.docker.com/engine/reference/logging/overview/#json-file-options

**Comment by JonasT** [comment]
What do you think about adding something to `docker ps -s` for log size? Either that, or auto-rotating logs enabled per default if they get REALLY huge (>1GB or something) would be helpful for... a special kind of people like me. :-) But good to know it's available! Last time I read about it was around 1.7ish where it wasn't available yet

**Comment by thaJeztah** [comment]
@JonasT for high volume logging (and in most cases, in production in general), the default json-file logging is not recommended. I don't think we want to overload `docker ps` with showing logfile sizes. Adding log-rotation to the default options; I'm not against that personally, but perhaps I'm overlooking possible implications. I suggest to open an issue / feature request for that. (e.g. to add that to the default daemon options, allowing people to still undo/change/override that setting)

**Comment by wattletimber** [comment]
Hi Guys. I have the same dilemma.
ubuntu@ip-172-31-5-57:~$ sudo du -ch -d 1 /var/lib/docker
9.9G	/var/lib/docker/containers
8.0K	/var/lib/docker/tmp
2.9M	/var/lib/docker/image
60K	/var/lib/docker/volumes
4.0K	/var/lib/docker/trust
1.4G	/var/lib/docker/aufs
60K	/var/lib/docker/network
12G	/var/lib/docker
12G	total

I did upgrade my space from 16gig to 40gig but it is still growing. What can I do. I have mongoDB running see infor below. I am a newbie. My fear is that I may delete information. Its a production server.
ubuntu@ip-172-31-5-57:~$ docker ps -s
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                        NAMES               SIZE
6029a2b4c013        mongo               "/entrypoint.sh mongo"   10 weeks ago        Up 2 weeks          127.0.0.1:27017->27017/tcp   mongodb             0 B (virtual 309.8 MB)
ubuntu@ip-172-31-5-57:~$

**Comment by wattletimber** [comment]
How can I run these commands and make sure that mongoDB is not disturbed?

**Comment by JonasT** [comment]
Have you checked the log files for the container? This was the actual culprit for me. Search for files ending with -json.log in `/var/lib/docker/containers` and check their size

**Comment by thaJeztah** [comment]
If you're using JSON logs, you can limit the size of those files using the instructions above in https://github.com/docker/docker/issues/17839#issuecomment-159433448

**Comment by wattletimber** [comment]
Hi do not have permission to get in to the folder
ubuntu:~$ cd /var/lib/docker/containers
-bash: cd: /var/lib/docker/containers: Permission deniedubuntu@ip-172-31-5-57:~$ sudo docker images
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
mongo                       latest               e79b013480eb        11 weeks ago        309.8 MB
<none>                     <none>              467eb21035a8        12 weeks ago        309.7 MB
<none>                     <none>              a5d16d62f4cf        4 months ago        317.4 MB
meteorhacks/meteord   base                83d6a4b61a93        4 months ago        330.7 MB
Please help guys i have a challenge here. I also want to know if i run ./launcher cleanup. will i be safe with my data?
