### ISSUE TITLE
Can pull but cannot run image?  repository name component must match "[a-z0-9]+(?:[._-][a-z0-9]+)*"

### ISSUE THREAD

**Issue by sorenriise** [docker/docker#17836]
Trying to install docker on Fedora 23.   The `wget -qO- https://get.docker.com/ | sh` does not (yet) recognize fc23 -- but im able to install docker 1.8.2 using yum/dnf.

Starting pulling containers work, but for some reason I'm getting an error running them

$ sudo docker pull mesoscloud/zookeeper:latest
Trying to pull repository docker.io/mesoscloud/zookeeper ... latest: Pulling from mesoscloud/zookeeper
47d44cb6f252: Already exists 
168a69b62202: Already exists 
812e9d9d677f: Already exists 
4234bfdd88f8: Already exists 
ce20c473cd8a: Already exists 
0522f1166ed9: Already exists 
4b65dd9f3103: Already exists 
e2903988a2c2: Already exists 
7e3562a2bb69: Already exists 
483a5c7e666b: Already exists 
8b91c532247a: Already exists 
4a0ecdfffe7a: Already exists 
Digest: sha256:4109eb28dc70186633ba92a0f0ff469fbea9eb1d739a04df1b11b973287d36f8
Status: Image is up to date for docker.io/mesoscloud/zookeeper:latest

$ sudo  docker run -d -e MYID=1 -e SERVERS=localhost --name=zookeeper --net=host --restart=always  mesoscloud/zookeeper:latest
Unable to find image ' mesoscloud/zookeeper:latest' locally
repository name component must match "[a-z0-9]+(?:[._-][a-z0-9]+)*"

The daemon outpul looks like 

DEBU[0010] Calling POST /images/create                  
INFO[0010] POST /v1.20/images/create?fromImage=mesoscloud%2Fzookeeper%3Alatest 
DEBU[0010] Trying to pull docker.io/mesoscloud/zookeeper from https://registry-1.docker.io v2 
DEBU[0011] Pulling tag from V2 registry: "latest"       
DEBU[0012] Verification failed for /mesoscloud/zookeeper using key RNG3:ZIHZ:GR2E:4TKC:FXWZ:RPFP:6Z6D:SXKZ:DFKO:HMU7:CU6C:WT6W 
DEBU[0012] Key check result: not verified               
DEBU[0012] Image already exists: 47d44cb6f252ea4f6aecf8a447972de5d9f9f2e2bec549a2f1d8f92557f4d05a 
DEBU[0012] Image already exists: 168a69b6220279e6d5bd8dafd2edf71434a08e32b60a7060f7a705f64857169d 
DEBU[0012] Image already exists: 812e9d9d677f15c39277b2edc8f9bc07354c899483409bb07d1c13c2b9c33ec8 
DEBU[0012] Image already exists: 4234bfdd88f8ed2bc4607bd2ebba2d41d61e2693ad0d184e7b05e1b57f8b8b33 
DEBU[0012] Image already exists: ce20c473cd8ac1fab6601529ce6a075743f2cf7a8f4cfed2216f8cfcb53bfc4e 
DEBU[0012] Image already exists: 0522f1166ed96126509a53e8b3b5cfd8ddfba4488591554f670f840bd5b5796d 
DEBU[0012] Image already exists: 4b65dd9f3103fd0b1ac67294a4d7cab3ace5f7fd1c51c7ef644b84d199ca03ae 
DEBU[0012] Image already exists: e2903988a2c2e69c54efa49d29d08b5c11a373f805306f1db9bf6c7a0df188c0 
DEBU[0012] Image already exists: 7e3562a2bb691d24107d2388e73675ddf248200d380836c35e6240a22446f130 
DEBU[0012] Image already exists: 483a5c7e666b37653ddc19f49953f528b5d8e13a7547c02465bad9c9675c9a6d 
DEBU[0012] Image already exists: 8b91c532247aeac9ba0b4be336b2b20e4599185ef9457cb7b7cbd9434a1ead20 
DEBU[0012] Image already exists: 4a0ecdfffe7a51f6aebe1f8530dc6fe3a36225fd2178a88d63be40f8e7898d55 
DEBU[0022] Calling POST /containers/create              
INFO[0022] POST /v1.20/containers/create                
ERRO[0022] Handler for POST /containers/create returned error: No such image:  mesoscloud/zookeeper:latest (tag: latest) 
ERRO[0022] HTTP Error      

Running the hello-world container however works.  Any idea what is going one here?

**Comment by sorenriise** [comment]
[soren@homeoffice ~]$ sudo docker version
Client:
 Version:      1.8.2-fc23
 API version:  1.20
 Package Version: docker-1.8.2-10.git28c300f.fc23.x86_64
 Go version:   go1.5.1
 Git commit:   cc2d489-dirty
 Built:        Tue Nov  3 06:41:23 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2-fc23
 API version:  1.20
 Package Version: 
 Go version:   go1.5.1
 Git commit:   cc2d489-dirty
 Built:        Tue Nov  3 06:41:23 UTC 2015
 OS/Arch:      linux/amd64
[soren@homeoffice ~]$ sudo docker info
Containers: 0
Images: 49
Storage Driver: devicemapper
 Pool Name: docker-253:0-2249727-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.307 GB
 Data Space Total: 107.4 GB
 Data Space Available: 9.403 GB
 Metadata Space Used: 3.834 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107 (2015-09-05)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.5-300.fc23.x86_64
Operating System: Fedora 23 (Twenty Three)
CPUs: 4
Total Memory: 7.796 GiB
Name: homeoffice.attlocal.net
ID: ZMAW:VV7N:DJRL:G4QH:SXRI:L7A3:5GG4:W2JT:CR4T:VSWA:XQ6K:JWNE
[soren@homeoffice ~]$ uname -a
Linux homeoffice.attlocal.net 4.2.5-300.fc23.x86_64 #1 SMP Tue Oct 27 04:29:56 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Physical machine (my desktop), no VMs

List the steps to reproduce the issue:
$ sudo docker pull mesoscloud/zookeeper:latest
[... pull ok ... ]
$ sudo docker run -d -e MYID=1 -e SERVERS=localhost --name=zookeeper --net=host --restart=always  mesoscloud/zookeeper:latest
Unable to find image ' mesoscloud/zookeeper:latest' locally
repository name component must match "[a-z0-9]+(?:[._-][a-z0-9]+)*"

Describe the results you expected:
Container launched without errors (like what it does on my fc22, w docker 1.9)

**Comment by cpuguy83** [comment]
Being that this works on docker 1.9, and I don't really see anything wrong with the repo name... I'm going to say that this was either something that got fixed or is a bug in the RH docker package (which is forked and packaged by RH).

In either case, this is not an issue on docker 1.9 (as you mention), so it should be closed.

**Comment by stevvooe** [comment]
@sorenriise Looks like there is an extra space in the image name. From the logs:

```
' mesoscloud/zookeeper:latest'
```

Do you have any scripts or modifications that might be adding invalid image names? Are you running this in a way that might quote the extra space when assembling the run arguments?

**Comment by sorenriise** [comment]
I have no scripts -- is is done from the command line by hand just as I show it above.

**Comment by sorenriise** [comment]
Actually, it may be a cut-and-paste problem from a google doc (not sure why) which has caused a non-breaking space to be inserted

[soren@homeoffice ~]$ echo 'sudo  docker run -d -e MYID=1 -e SERVERS=localhost --name=zookeeper --net=host --restart=always  mesoscloud/zookeeper:latest' | od -c
0000000   s   u   d   o           d   o   c   k   e   r       r   u   n
0000020       -   d       -   e       M   Y   I   D   =   1       -   e
0000040       S   E   R   V   E   R   S   =   l   o   c   a   l   h   o
0000060   s   t 302 240   -   -   n   a   m   e   =   z   o   o   k   e
0000100   e   p   e   r       -   -   n   e   t   =   h   o   s   t    
0000120   -   -   r   e   s   t   a   r   t   =   a   l   w   a   y   s
0000140     **302 240**   m   e   s   o   s   c   l   o   u   d   /   z   o
0000160   o   k   e   e   p   e   r   :   l   a   t   e   s   t  \n

**Comment by stevvooe** [comment]
@sorenriise That looks like the cause of that error message.
