### ISSUE TITLE
Docker leaks container IDs and IPs even with icc=false

### ISSUE THREAD

**Issue by vincentwoo** [docker/docker#17842]
When running the docker daemon with `DOCKER_OPTS="-s overlay -icc=false"`, I'd expect that the auto-population of `/etc/hosts` inside containers would not occur. However, it does very plainly:

```
root@a8887a462d5f:~# cat /etc/hosts
172.17.0.1	a8887a462d5f
```

This occurs on both 1.8 and 1.9, and is somewhat of a security risk for me. I have mitigated this in userland but would have preferred not to have had to.

```
vwoo@ubuntu:~$ docker info
Containers: 2
Images: 22
Server Version: 1.9.0
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-21-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 3.766 GiB
Name: ubuntu
ID: 6LST:RRCU:BKCS:Z73Y:HOMA:UUY7:RHNL:YRDY:52H6:IGID:SL3G:57BR
Username: coderpad
Registry: https://index.docker.io/v1/
vwoo@ubuntu:~$ docker --version
Docker version 1.9.0, build 76d6bc9
vwoo@ubuntu:~$ uname -a
Linux ubuntu 3.19.0-21-generic #21~14.04.1-Ubuntu SMP Sun Jun 14 18:45:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by thaJeztah** [comment]
ping @tiborvass @mavenugo

**Comment by mavenugo** [comment]
@vincentwoo when icc is false, docker doesn't update the /etc/hosts of containers in the default bridge network. the `172.17.0.1  a8887a462d5f` update that you see in your container is the ip-address of self (not that of other containers in the bridge network). Can you please confirm ?

**Comment by vincentwoo** [comment]
Ah, you're correct. I confused myself testing both 1.8 and 1.9 - I think the behavior changed. Closing.
