### ISSUE TITLE
Bash completion is broken

### ISSUE THREAD

**Issue by bfontaine** [docker/docker#17840]
As I wrote [here](https://github.com/docker/docker/commit/fb6ef9086d4f68a239a237dcdfeb6a4518163e28#commitcomment-14287645) the Bash completion script is broken in Docker 1.9 as well as in the current commit (143f3579b0553b50b03438aef76d908a5d327863): https://github.com/docker/docker/blob/143f3579b0553b50b03438aef76d908a5d327863/contrib/completion/bash/docker#L758

The reason is that the following `case` pattern is invalid in Bash:
```bash
*dm.@(blkdiscard|override_udev_sync_check|use_deferred_@(removal|deletion))=*)
```

The only way to make it valid is [to use `shopt -s extglob`](http://stackoverflow.com/a/4555979/735926).

## Steps to reproduce

1. Run the completion file with `bash docker` (`docker` being the name of the script)

### Expected output

Nothing

### Actual output

```
docker: line 731: syntax error near unexpected token `('
docker: line 731: `     *dm.@(blkdiscard|override_udev_sync_check|use_deferred_@(removal|deletion))=*)'
```

Tested with `GNU bash, version 4.3.42(1)-release (x86_64-apple-darwin14.5.0)` as well as `GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)`.

**Comment by bfontaine** [comment]
Didn’t search enough; this is a duplicate of #17791.

**Comment by thaJeztah** [comment]
Thanks @bfontaine !
