### ISSUE TITLE
Docker container on auto-start can't be stopped or killed

### ISSUE THREAD

**Issue by etiago** [docker/docker#17856]
Hi,

I'm running a container with the following Dockerfile:
```
FROM ubuntu:14.04.2

EXPOSE 9000

RUN apt-get clean
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y php5-fpm php5-mysql php5-gd
RUN echo "include=/var/conf/php-fpm/fpm/php-fpm.conf" > /etc/php5/fpm/php-fpm.conf

ENV PHPRC "/var/conf/php-fpm/fpm/php.ini"

CMD php5-fpm --nodaemonize
```

I started this container 5 months ago with a policy to auto-restart on boot but now every time I try to ```docker stop``` it or ```docker kill``` it, docker hangs and then nothing else docker-related works until I restart the whole system.

Then after a restart, the docker container starts again and it gets stuck again.

Basically, I'm left with a container which I cannot delete no matter what I do.

Is there any way of stopping the auto-restart behavior of an existing container so I can at least reboot the system and it doesn't start automatically?

Also, I've created another container from the same image and this second container does not suffer from this problem.

Any help, short of reinstalling my OS? :-(

**Comment by etiago** [comment]
Some additional info:

I'm running Ubuntu 14.04.3 LTS as host with all the updates installed.

```docker version``` returns:
```
tiago@pingyao:~/docker-images$ docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

**Comment by JBodkin** [comment]
The restart policy is held in json form, perhaps you can stop docker and edit it?

e.g.
/var/lib/docker/containers/<CONTAINER ID>/hostconfig.json

**Comment by etiago** [comment]
@JBodkin this fixed it! I tried editing the hostconfig.json *without* stopping docker and by restarting the machine and docker simply set it back to auto-restart. But by stopping docker first, it did the job!

Many thanks!

**Comment by uvwild** [comment]
Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:07:42 2017
 OS/Arch:      linux/amd64
 Experimental: false


its not working anymore.... no such file :(

**Comment by conatus** [comment]
Hey @JBodkin 

Where is the equivalent location on Mac OS X?

**Comment by heathweaver** [comment]
Perhaps I need to create a separate issue, but this seems somewhat similar. 

Every time I kill or stop a redis:3.0.6 container a new one starts back up. I've checked in the hostconfig.json and they are both set to:

"RestartPolicy":
{"Name":"",
"MaximumRetryCount":0
}

I can't rm the image, because it's in use by the containers. When I restart docker, there they are.

**Comment by thaJeztah** [comment]
@heathweaver is that container started using `docker run` or part of a service (`docker service create` or deployed through `docker stack deploy`)? If the latter, then that's expected, as docker swarm will reconcile services to their desired state.

**Comment by heathweaver** [comment]
Yes, didn't realise it was part of a swarm. Once I left that, I was able to delete the service. Thanks.

**Comment by andrewb-ms** [comment]
Why isn't there a way to more easily kill an auto-restart container?

**Comment by thaJeztah** [comment]
use the "unless-stopped" restart policy instead

**Comment by andrewb-ms** [comment]
How about this:

Change Docker Stop to warn users when they try to Stop an Auto-restart container and suggest the fix

**Comment by MahadevG** [comment]
I got a improvement solution to kill and remove the container.
That is I was running docker as non root user.
To kill and remove what i did is,
sudo -i
docker ps
docker service kill dockerimage
docker service rm dockerimage

**Comment by azizzoaib786** [comment]
docker service rm <service-id> **works** .. and followed by docker stop $(docker ps -a -q) & docker update --restart=no $(docker ps -a -q)
