### ISSUE TITLE
/etc/ chowned to root in Docker 1.9.0

### ISSUE THREAD

**Issue by tjdett** [docker/docker#17854]
From Docker 1.9.0 onwards, `/etc` inside containers is owned by UID 0 (root) rather than the owner in the image. This breaks images where `/etc` is owned by a different user.

`docker version`:
```
Server:
 Version:      1.9.0
 API version:  1.21
 Package Version: 
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:
```
Containers: 3
Images: 12
Storage Driver: vfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.3-200.fc22.x86_64
Operating System: Alpine Linux v3.2 (containerized)
CPUs: 8
Total Memory: 15.63 GiB
Name: de8c5f62960d
ID: EHMU:MINO:I4LJ:SU66:BNWJ:Z4JD:ZS6K:ZVNB:T7DV:MJ4G:VLWK:JGCZ
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

`uname -a`:
Tests run against `docker:1.9.0-dind`.

Environment details (AWS, VirtualBox, physical, etc.):
Local `docker:1.9.0-dind`

How reproducible:
All 1.9.0, as best as can be established.

Steps to Reproduce:
1. `docker run -i --rm dit4c/centos-notroot:7 /bin/ls -lad /etc`

Actual Results:
`drwxr-xr-x. 46 root root 4096 Nov 10 01:14 /etc`

Expected Results:
`drwxr-xr-x. 46 notroot notroot 4096 Nov 10 01:13 /etc`

Additional info:
The `dit4c/centos-notroot` image is essentially `centos:7`, with all files owned by an unprivileged user and [proot](http://proot.me) installed. No setuid binaries are present or required, as the unprivileged user has sufficient file permissions to install packages. For applications which check uid, `proot -0` can be used to pretend to be UID 0 provided `PTRACE` is available to the container. The result is that untrusted code can be run with full filesystem privileges inside the container without access to UID 0 ever being provided, which works around the lack of user namespaces (which are currently only in Docker 1.9.0 experimental).

For package managers like `yum` to work properly however, `/etc` needs to be writeable. Files supplied by Docker like `/etc/hostname`, `/etc/hosts`, `/etc/mtab`, `/etc/resolv.conf` don't need to be writeable, but the directory itself does so new configuration files can be created.

If this change is for security reasons (because `/etc/mtab` being replaceable is somehow a problem) then it should at least appear in `CHANGELOG.md`, as it breaks previous behaviour.

**Comment by tjdett** [comment]
Are there any extra details I need to provide before this either gets a "bug" label or a "wontfix"?

**Comment by thaJeztah** [comment]
Hm, good point, this may have been a security change, but perhaps @crosbymichael knows

**Comment by thaJeztah** [comment]
I do remember this change; https://github.com/docker/docker/pull/12947 but not sure if there were other changes, I'll see if I can find something in the meantime

**Comment by tjdett** [comment]
@thaJeztah From a quick read of the #12947 diff, if it is the origin then I don't think this behaviour is intentional. The mounts appear to be limited to `/etc/hostname`, `/etc/hosts` & `/etc/resolv.conf` specifically.

There doesn't appear to be a way for those changes to spill over to `/etc` directory ownership.

**Comment by thaJeztah** [comment]
@tjdett yes, it's not that PR that made the change, but it was one that I remembered tweaking permissions in this area.

**Comment by cpuguy83** [comment]
I'm not sure I follow.

I've got an image I created here:
```Dockerfile
FROM busybox
RUN chown -R daemon.daemon /etc
```

Then run the image:
```
$ docker build -t test -< Dokerfile
...
$ docker run --rm test ls -lh /etc
total 24
-rw-rw-r--    1 daemon   daemon       299 Sep  6 20:57 group
-rw-r--r--    1 root     root          13 Dec  3 18:05 hostname
-rw-r--r--    1 root     root         174 Dec  3 18:05 hosts
lrwxrwxrwx    1 root     root          12 Dec  3 18:05 mtab -> /proc/mounts
-rw-rw-r--    1 daemon   daemon       371 Sep  6 20:57 passwd
-rw-r--r--    1 root     root          20 Dec  3 18:05 resolv.conf
-rw-rw-r--    1 daemon   daemon       239 Sep  6 20:57 shadow
$ 
```

With the exception of the files we are mounting in, which have always been mounted in, it's all owned by the user I chowned to.

**Comment by tjdett** [comment]
@cpuguy83 Yeah, you've missed the important part. With your test image:

#### Docker 1.8.3
```
$ docker run -ti --rm test ls -la /etc
total 32
drwxr-xr-x    2 daemon   daemon        4096 Dec  4 03:18 .
drwxr-xr-x   12 root     root          4096 Dec  4 03:18 ..
-rw-rw-r--    1 daemon   daemon         299 Sep  6 20:57 group
-rw-r--r--    1 root     root            13 Dec  4 03:18 hostname
-rw-r--r--    1 root     root           235 Dec  4 03:18 hosts
lrwxrwxrwx    1 root     root            12 Dec  4 03:18 mtab -> /proc/mounts
-rw-rw-r--    1 daemon   daemon         371 Sep  6 20:57 passwd
-rw-r--r--    1 root     root           102 Dec  4 03:18 resolv.conf
-rw-rw-r--    1 daemon   daemon         239 Sep  6 20:57 shadow
```

#### Docker 1.9.x
```
$ docker run -ti --rm test ls -la /etc
total 32
drwxr-xr-x    2 root     root          4096 Dec  4 03:10 .
drwxr-xr-x   12 root     root          4096 Dec  4 03:10 ..
-rw-rw-r--    1 daemon   daemon         299 Sep  6 20:57 group
-rw-r--r--    1 root     root            13 Dec  4 03:10 hostname
-rw-r--r--    1 root     root           174 Dec  4 03:10 hosts
lrwxrwxrwx    1 root     root            12 Dec  4 03:10 mtab -> /proc/mounts
-rw-rw-r--    1 daemon   daemon         371 Sep  6 20:57 passwd
-rw-r--r--    1 root     root           102 Dec  4 03:10 resolv.conf
-rw-rw-r--    1 daemon   daemon         239 Sep  6 20:57 shadow
```

In case it doesn't stand out:
```diff
 total 32
-drwxr-xr-x    2 daemon   daemon        4096 Dec  4 03:20 .
+drwxr-xr-x    2 root     root          4096 Dec  4 03:20 .
 drwxr-xr-x   12 root     root          4096 Dec  4 03:20 ..
```

In your test image, `/etc` shouldn't be owned by root. You chowned it to `daemon`, so unless there's a spec somewhere that says otherwise, it should still be owned by `daemon`.

Why is this important?

#### Docker 1.8.3
```
$ docker run -ti --rm --user daemon test sh -c "touch /etc/daemon.test && ls -la /etc/daemon.test"
-rw-r--r--    1 daemon   daemon           0 Dec  4 03:25 /etc/daemon.test
```

#### Docker 1.9.0
```
$ docker run -ti --rm --user daemon test sh -c "touch /etc/daemon.test && ls -la /etc/daemon.test"
touch: /etc/daemon.test: Permission denied
```

If you're relying on a non-root user to be able to write to `/etc`, then you have a problem.

**Comment by cpuguy83** [comment]
@tjdett Thanks!

I think this might have come from the userns work.
Ping @estesp.
This is happening due to some call to `idtools.MkdirAllAs`
Note this is happening in the *stable* build

**Comment by estesp** [comment]
I've figured out the issue--I'll be generating a PR
