### ISSUE TITLE
curl (7) a failed connection in docker

### ISSUE THREAD

**Issue by mehdiAhmed** [docker/docker#17864]
I'm using docker on ubuntu 14.04.

>cat /etc/lsb-release
>DISTRIB_ID=Ubuntu
>DISTRIB_RELEASE=14.04
>DISTRIB_CODENAME=trusty
>DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS

I have this container:

>CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                  NAMES
>2b20d2dc367c        myImage       "/root/run.sh"      11 minutes ago      Up 11 minutes       0.0.0.0:8080->80/tcp   containerName

If I understand, docker map the port 80 of the container to the port 8080 of the host. I ran this machine: 
>docker-machine ls
>NAME       ACTIVE   DRIVER       STATE     URL                         SWARM
>Test   -        virtualbox   Running   `tcp://<IP>:2376`

However, when I run
`curl http://<IP>:8080/-/`
I got this error:
`curl: (7) Failed to connect to <IP> port 8080`

and the curl version is :
`curl --version`
`curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3`

The container IP is:
>docker inspect erocci | grep IPAddress
>"SecondaryIPAddresses": null,
>        "IPAddress": "172.17.0.1",
 >               "IPAddress": "172.17.0.1",

But when i try: `telnet 172.17.0.1 80` I got:
>Trying 172.17.0.1...
>telnet: Unable to connect to remote host: Connection refused

For information:
1- docker version
>Client:
> Version:      1.9.0
> API version:  1.21
> Go version:   go1.4.2
> Git commit:   76d6bc9
> Built:        Tue Nov  3 17:43:42 UTC 2015
> OS/Arch:      linux/amd64
>
>Server:
> Version:      1.9.0
> API version:  1.21
> Go version:   go1.4.2
> Git commit:   76d6bc9
> Built:        Tue Nov  3 17:43:42 UTC 2015
> OS/Arch:      linux/amd64

2-docker info

>Containers: 26
>Images: 31
>Server Version: 1.9.0
>Storage Driver: aufs
> Root Dir: /var/lib/docker/aufs
> Backing Filesystem: extfs
> Dirs: 83
> Dirperm1 Supported: true
>Execution Driver: native-0.2
>Logging Driver: json-file
>Kernel Version: 3.16.0-53-generic
>Operating System: Ubuntu 14.04.3 LTS
>CPUs: 4
>Total Memory: 7.706 GiB
>Name: mehdi-Latitude-E7240
>ID: UWUF:57PY:QJC2:WRUJ:IOOT:XFBM:W3UY:5AQC:532A:2CWU:SYP7:5JCE
>WARNING: No swap limit support

3- uname -a

>Linux mehdi-Latitude-E7240 3.16.0-53-generic #72~14.04.1-Ubuntu SMP Fri Nov 6 18:17:23 UTC >2015 x86_64 x86_64 x86_64 GNU/Linux

My question is: how can i run `curl http://IP:8080/-/` properly ?

**Comment by LK4D4** [comment]
Closing this as it's not possible to understand what was going on now :( Feel free to open new issue.
