### ISSUE TITLE
TarSum is not idempotent

### ISSUE THREAD

**Issue by cristiklein** [docker/docker#17863]
Dear all,

We commonly build and push the same docker image from source code on various machines (e.g., developer laptops, CI servers), as we thought that the TarSum should be idempotent. By idempotent, I mean that it only depends on the FROM image TarSum and the build context including Dockerfile. However, we recently ran into some caching issues and realised that the TarSum is far from idempotent. Even the MAINTAINER line induces a different TarSum (see below).

Is this behaviour intended? Wouldn't it be possible to make TarSum idempotent? (Sorry if I missed some blueprint.)

Regards,
Cristian

> mumbai:~/workspace/docker-test$ cat Dockerfile 
FROM ubuntu:14.04
MAINTAINER cklein@simscale.com

> mumbai:~/workspace/docker-test$ docker build --no-cache .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM ubuntu:14.04
 ---> 5ba9dab47459
Step 2 : MAINTAINER cklein@simscale.com
 ---> Running in bdd45b1590f0
 ---> 0fad5c04a95d
Removing intermediate container bdd45b1590f0
Successfully built 0fad5c04a95d

> mumbai:~/workspace/docker-test$ docker build --no-cache .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM ubuntu:14.04
 ---> 5ba9dab47459
Step 2 : MAINTAINER cklein@simscale.com
 ---> Running in abd39e5ef805
 ---> 72d32ba58e94
Removing intermediate container abd39e5ef805
Successfully built 72d32ba58e94

**Comment by cpuguy83** [comment]
Everything in the Dockerfile contributes to the tarsum.

**Comment by cpuguy83** [comment]
Also, the cache is not from tarsum.
Each entry in the Dockerfile creates a new image layer. This is what is used for the cache. "Is there an image who's parent ID is XXXXXX and who's config matches `<resolved runconfig from dockerfile command>`

**Comment by cristiklein** [comment]
docker version
>Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

> Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64


docker info
>Containers: 20
Images: 485
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 525
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-67-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 7.682 GiB
Name: mumbai
ID: HJRN:QH4V:CW6O:DVPM:MDX2:O4KX:WBQO:MPPJ:QVEM:HHID:IKKE:3VQH
WARNING: No swap limit support

uname -a
>Linux mumbai 3.13.0-67-generic #110-Ubuntu SMP Fri Oct 23 13:24:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

> on a physical machine

**List the steps to reproduce the issue:**
Create the following `Dockerfile`

> FROM ubuntu:14.04
MAINTAINER cklein@simscale.com

1. Run `docker build --no-cache .`
2. Re-run `docker build --no-cache .`

**Describe the results you received:** Command 1 and 2 generate two distinct images, with different tarsums.

**Expected results:** Since I did not change the `Dockerfile` nor the build context, I would have expected the two commands to generate the same image, i.e., the same tarsum, twice.

**Provide additional info you think is important:** I am not sure whether this is by design or a bug. Anyway, making Docker idempotent, i.e., making it always generate the same output for the same input, is a highly desirable property for caching. This is in particular true if the build is distributed, i.e., there is no central machine that generates the images.

**Comment by cristiklein** [comment]
> Everything in the Dockerfile contributes to the tarsum.

@cpuguy83 Exactly! I was expecting the tarsum to be determined **only** by everything in the Dockerfile. Clearly this is not the case, as seen in the example above. The Dockerfile was not changed between two consecutive invocations of `docker build --no-cache .`, still the tarsum changed.

Can you clarify if this is indented behaviour or a bug?

**Comment by cpuguy83** [comment]
@cristiklein This has nothing to do with tarsum.
Tarsum is not used for caching (except to sum blobs from ADD/COPY)

The process that happens here is as it relates to the cache:
```
FROM foo --> downloads foo image 
MAINTAINER foo@bar.com --> check images for image with parent ID is the resolved image id from the `foo` image and  CMD matches `["/bin/sh", "-c", "#(nop) MAINTINER foo@bar.com"]` --> if none run a container with the CMD and resolved id from `foo` image, commit the results to a new image --> generates new image iD
RUN echo stuff --> check images where parent image ID matches ID from previous line and CMD is `["/bin/sh", "-c", "echo stuff"]` --> if none found, run a container and commit the results --> generates a new image ID
```

If you tell it to build with `--no-cache` you are telling it to skip the step to see if any image exists that matches the desired configuration (parent ID is ID from previous command, runconfig matches resolved config from the build step) and to always generate a new image, which will always generate a new image ID.
Image ID's are **not** checksum values.

**Comment by cristiklein** [comment]
Thank you for the clarification. I now understand that the image ID has nothing to do with the content itself. I expected image IDs to have a more "git-esque" property, something like:

> image_id = deterministic_algo( parent_image_id, new_content )

Do you happen to know if this property has ever been discussed?

**Comment by cpuguy83** [comment]
Content addressable tags are something thats available today, but are not incredibly easy to get at the digest to use.
TBH I'm not really sure where to get this info... but it's possible.... `docker pull <repo>/<image>@sha256:<checksum>`

**Comment by cristiklein** [comment]
Thanks for the info! I wish Docker would also use content-addressable docker image IDs. It seems to me quite easy to bust the cache if multiple build machines are involved and you forget to pull before building.
