### ISSUE TITLE
Re-open of #8942: Unable to use --volumes-from with an unstarted container made with `docker create`

### ISSUE THREAD

**Issue by nickwilliams-eventbrite** [docker/docker#17878]
We were using Docker 1.6.2. We created a new container called `geo-data` whose sole purpose was to publish a volume. We created another container called `mysql-geo`, and that container uses `volumes-from geo-data`.

At first, when starting `mysql-geo`, we got this error: 

```
Error: 500 Server Error: Internal Server Error ("Cannot start container 5427b24cc540b18ebe48f2137b028357a2bc0586f28a26c9bfc0caa318134cc8: Could not apply volumes of non-existent container "yadayada.geo-data.1".")
```

However, after trying to start `geo-data` (which failed, because there's no executable, but that failure didn't stop it from working), we were then able to start `mysql-geo` without error and use the volume from `geo-data`. So, it was odd enough that we couldn't use a data volume container without "starting" it, but it was odder still that pretending to start it (it dies immediately) is enough to get it to work. And it keeps working, unless the `geo-data` container/image gets deleted.

Having found issue #8942, it appeared that the issue had been fixed. So we updated to Docker 1.9.0. To ensure that the issue had been resolved (instead of the previous start masking it), I deleted all my containers and images so that I was starting from scratch. I created a new container called `geo-data` whose sole purpose was to publish a volume. I created another container called `mysql-geo`, and that container uses `volumes-from geo-data`. I did this identically to the first time. Now, starting `mysql-geo` just gave me a new error:

```
Error: 404 Client Error: Not Found ("no such id: yadayada.geo-data.1")
```

And, once again, pretending to start `geo-data` does the trick. `geo-data` dies immediately after starting, but it's enough. Now I can start `mysql-geo` without error and use the volume from `geo-data`.

Would really love an update on / solution to this problem. In the mean time, what's the best workaround?

**Comment by nickwilliams-eventbrite** [comment]
BUG REPORT INFORMATION

```
$ docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64
$ docker info
Containers: 27
Images: 379
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 448
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-62-generic
Operating System: Ubuntu 14.04 LTS
CPUs: 2
Total Memory: 5.829 GiB
Name: docker-dev
ID: DB22:EKPR:WBF4:UP3W:XVAR:VM2C:26SJ:M65S:HWYC:4PDK:DQVQ:A7MF
$ uname -a
Linux docker-dev 3.13.0-62-generic #102-Ubuntu SMP Tue Aug 11 14:29:36 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

This is running on an Ubuntu 14.04 Vagrant VirtualBox machine atop Mac OS X 10.9.5.

List the steps to reproduce the issue:
1. Create a Docker container with a volume but no executable, don't start it.
2. Create a Docker container using volumes-from the container created in Step 1.
3. Start the container created in Step 2, which fails with an error that the container created in Step 1 wasn't found.
4. After that fails, start the container created in Step 1, which dies immediately.
5. After that fails, start the container created in Step 2, which now succeeds.

Describe the results you received:
Cannot start container 2 until container 1 is started (even though it dies immediately).

Describe the results you expected:
Should not need to start container 1. The volume should be created on create. Container 2 should start and use the volume from container 1 without ever having to start container 1.

**Comment by phemmer** [comment]
> So we updated to Docker 1.9.0. ... I created a new container called `geo-data` whose sole purpose was to publish a volume

If you're using >=1.9.0, you don't need data-only containers any more. `docker volume` was introduced which solves this: https://docs.docker.com/engine/reference/commandline/volume_create/

**Comment by nickwilliams-eventbrite** [comment]
That's helpful to know, but does not fully meet our use case. I simplified things so that it's easy to replicate for this bug, but our environment is much more complex. In this case, the data volume container we're using isn't _just_ a dumb container. We use a tug tool around Docker that "builds" containers, and as part of "building" this container, we populate data in the shared volume that it creates. The container still doesn't need to start, but it does need to "build." We would have to significantly change our tooling to use `docker volume` instead of data volume containers. While we may in the future come up with new tooling for `docker volume`, for now, we need `volumes-from` to work properly.

**Comment by thaJeztah** [comment]
I'm not able to reproduce this; this is what I tried;

```bash
$ docker create -v /foobar --name data-only hello-world
8dac4b6fb775be61c21e5746c6d5096d2e9892e7596bd747644cbdf56d82a57f

$ docker create --volumes-from=data-only --name=app -it ubuntu
fd369a74c1f440381d22cc07a0209d1c376755362a4d2006a5a2154ea1d35934

$ docker start app
app

$ docker attach app
root@fd369a74c1f4:/# ls
bin  boot  dev  etc  foobar  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
```

**Comment by nickwilliams-eventbrite** [comment]
Indeed. I misunderstood when our tug tooling called build vs when it called create. The data volume containers were getting `docker build`ed, but not `docker create`ed, hence why I was experiencing this problem. I have refactored our tooling to call `docker create` on all the data volume containers as well, and the problem went away. My apologies for wasting any of your time, and thank you for the help.

**Comment by thaJeztah** [comment]
Thanks for reporting back @nickwilliams-eventbrite, good to hear to resolved your issue!
