### ISSUE TITLE
Issues using /bin/sh in CMD command in scratch docker container

### ISSUE THREAD

**Issue by prashantabkari** [docker/docker#17896]
I am facing the same problem when i try to create a base image from scratch
Following is the dockerfile
FROM scratch
ADD a.out /home/abkari/docker_file/server_docker/server.o
CMD ["/bin/bash"]

On running the container with the above image i get the following error
Error response from daemon: Cannot start container 29891a11a5915a3c81d9a3c4800c8a1b33ea32fad00da2335ece69e3dd856458: [8] System error: exec: "/bin/bash": stat /bin/bash: no such file or directory

1. Docker version is : 
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64

2. Docker info 
Containers: 6
Images: 8
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 20
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 976.8 MiB
Name: ubuntu
ID: F3Q4:WQ7V:Y4CT:FGJ7:U3NP:24A2:UXJI:GYN2:CU2V:4OLL:P52C:XRXX
WARNING: No swap limit support

3. uname -a
Linux ubuntu 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mountkin** [comment]
There's no `/bin/bash` in the scratch image.
To use bash you have to create your image from ubuntu, debian, etc.

**Comment by prashantabkari** [comment]
My requirement is to run with scratch. 
I changed the dockerfile now to just run the binary file i.e a.out. Still it says

b2a5db430ce86629b76a322d43423457b09831f03fceab6365cf668516f14f75
Error response from daemon: Cannot start container b2a5db430ce86629b76a322d43423457b09831f03fceab6365cf668516f14f75: [8] System error: no such file or director

**Comment by mountkin** [comment]
There's no files in the scratch image. But perhaps your `a.out` is dynamically linked and requires external shared objects. The " no such file or director" error is saying that the required libraries can't be found.
Your can confirm that by running `ldd a.out` on the host.
To make it work you have to add all the required libraries to the image.

**Comment by thaJeztah** [comment]
Reading the above, I don't think this is a bug in Docker, but more a support question.

For that reason, I'm closing this issue, but feel free to continue the discussion.

For future support questions, please use one of these;

1) the forums: https://forums.docker.com/
2) the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user
3) the #docker IRC channel on Freenode.

**Comment by jakirkham** [comment]
It is worth noting that not having `/bin/sh` means that the `RUN` command will not work. IMHO that does present a problem. So, why is it that this shell is not included?

**Comment by thaJeztah** [comment]
The reason here is that, `FROM scratch` *literally* is an empty, zero-byte image / filesystem, where you add everything yourself. See for example, the https://github.com/docker-library/hello-world which, produces an image that's 860 bytes total.

**Comment by prashantabkari** [comment]
If i am not wrong the above scratch dockerfile was supported  in earlier docker version. 
Was it changed only later?

**Comment by vdemeester** [comment]
@prashantabkari I don't know what "supported in earlier version" means there. As @mountkin and @thaJeztah said, the `scratch` image is litteraly empty, not `/bin/sh` or `test` binary so the above `Dockerfile` does not work and pretty sure it never "worked".

**Comment by thaJeztah** [comment]
I seriously doubt it worked in an older version. The only difference made is that previously, "scratch" was an actual image, consisting of just an empty directory/filesystem. In more recent docker versions, "scratch" has become a special case and doesn't download the empty image.

```bash
docker version
Client version: 1.0.0
Client API version: 1.12
Go version (client): go1.2.1
Git commit (client): 63fe64c
Server version: 1.0.0
Server API version: 1.12
Go version (server): go1.2.1
Git commit (server): 63fe64c
root@a3bc2f6ae821:/test# docker build -t foo .
Sending build context to Docker daemon  2.56 kB
Sending build context to Docker daemon
Step 0 : FROM scratch
Pulling repository scratch
511136ea3c5a: Download complete
 ---> 511136ea3c5a
Step 1 : RUN echo foo
 ---> Running in 03541e2abd6e
2015/11/12 09:26:13 exec: "/bin/sh": stat /bin/sh: no such file or directory
2015/11/12 09:26:13 The command [/bin/sh -c echo foo] returned a non-zero code: 1
```

**Comment by jakirkham** [comment]
Fair enough, though it would be nice if the user was warned of this behavior somehow. Maybe through a linter. Are there any other commands that won't work without some command line tools being available?

**Comment by k4kratik** [comment]
Ok Let's try this - 
as We all know(I hope)  that "Scratch File system is nothing but just an empty / "root" File system"
For make it work you have to add things accordingly.
`**ADD a.out /home/abkari/docker_file/server_docker/server.o** 
`In this line there are three errors- 
1. a.out won't work because -- Scratch don't have any kind of compiler to run that output file. OK
2. and the path man! it doesn't even exists in your scratch image.
3. you can't run bash on scratch because it doesn't have, Simple!
Solutions:-
1. instead of a.out ADD the static compile file,
which can be generated by following command 
` g++ -o hello -static a.cc`
this will generate a file named just a 
2. instead of copying it to that path just copy to root, because it has only this.
3. you should installed bash first.

Modified Dockerfile in my POV - 

> FROM scratch
> ADD a / 
> CMD ["/a"]

then you can be able to run your file.
Thanks. 
Correct me wherever you feel like.
Peace :)

**Comment by chrisharrisonkiwi** [comment]
Is there someway of adding/importing shell to the Scratch image from within the docker file?
I get that Scratch is totally empty, but surely theres a way to add at least shell to provide some kind of instruction after startup?

**Comment by thaJeztah** [comment]
You can either use a multi-stage build, and use an intermediate stage to do manipulation that requires a shell;

```Dockerfile
FROM alpine AS build
COPY foo /somewhere
RUN do something with files

FROM scratch AS final
# copy the artefacts of the build stage that you want in the final image
COPY --from=build /somewhere/. /
```


Or if you want to be creative, enable buildkit (recommended for build even if you don't use the experimental features), and the experimental Dockerfile syntax, which allows you to `RUN --mount` (e.g.) busybox in a `FROM scratch` stage; https://gist.github.com/thaJeztah/cfd929a31976b745e3f7515ae37eb192#silly-experiment-with-mounting-utilities-into-scratch

**Comment by thaJeztah** [comment]
> to provide some kind of instruction after startup?

if you want the image to be runnable without any executable in it, no, that's not really possible. in that case, you'd rather use a minimal base-image for your Dockerfile, or add a static binary to it that you can run

**Comment by therealak12** [comment]
Is there an example in on how to copy /bin/sh to a scratch image?

**Comment by thaJeztah** [comment]
@therealak12 if you want that to work, it'd has to be some static binary, but it's "basically" what `busybox` provides (which is a single multi-call binary, which provides `sh`, builtins and some other commands. There's some other projects that do similar things.

Might be better to start a discussion in https://github.com/moby/moby/discussions though, and describe what you're trying to do.

**Comment by therealak12** [comment]
Busybox is the right solution. What I was missing was using the libc variant, i.e., ` busybox:1.35.0-uclibc`.
Thanks.
