### ISSUE TITLE
Could not find image when running containers

### ISSUE THREAD

**Issue by jerryking58** [docker/docker#17895]
docker version:
Docker version 1.7.1, build 786b29d

docker info:
Containers: 5
Images: 195
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 322
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-32-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 3.859 GiB
Name: iZ258bbryywZ
ID: HJAT:DLI4:U46V:5TZW:K7C6:3ILE:XMY5:UYEK:UKYT:PAA5:BJ5I:VOSL
WARNING: No swap limit support

uname -a:
Linux iZ258bbryywZ 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Additional information:
aliyun(similar to aws).
I have started the rethinkdb container. But after that another guy clean up our private registry service and restart it. Now I can't start the container anymore.

Steps to reproduce the issue:
docker run -ti -d --restart=always --name shipyard-rethinkdb rethinkdb

Results I received:
Error response from daemon: could not find image: no such id: 684ad5d758db439c925b426c2d74f88e3eecb562af6980ee1e2eca1c721e251a

Results I expected:
Run the container successfully.

**Comment by mountkin** [comment]
Please run `docker inspect --format='{{.Id}}' rethinkdb` to see if the ID of the image `rethinkdb` is `684ad5d758db439c925b426c2d74f88e3eecb562af6980ee1e2eca1c721e251a`.
In theory, if the image doesn't exist locally docker will pull the image from docker hub. But it seems that your docker didn't pull the image.
I suspect the rethinkdb image is broken, perhaps some of its parent layers are missing.

**Comment by jerryking58** [comment]
@mountkin 
The id of rethinkdb is not 684ad5d758db439c925b426c2d74f88e3eecb562af6980ee1e2eca1c721e251a. I think your suspection is reasonable. Do you how how to solve this? Besides, I have tried pulling the rethinkdb manually.

**Comment by mountkin** [comment]
The log file in `/var/log/upstart/docker.log` might be useful for the developers to dig into such problems.

You can try to remove the image, pull it from docker hub, then try to start a container from the new image. If it doesn't work either, I'd suggest you upgrade docker to 1.9.0.

**Comment by HackToday** [comment]
I tried 
docker run -ti -d --restart=always --name shipyard-rethinkdb rethinkdb

it works on docker 1.9. I think something with your docker host. and as @mountkin  docker logs can help you

**Comment by falcon15500** [comment]
Have had this after a failed run operation. Stop all containers and delete your linkgraph.db file (somewhere under /var/lib/docker).

After that your run will work properly again.

**Comment by thaJeztah** [comment]
@jerryking58 is this still an issue?

**Comment by jerryking58** [comment]
@thaJeztah nope, plz close it.

**Comment by thaJeztah** [comment]
Thanks @jerryking58!

**Comment by floion** [comment]
@jerryking58 @thaJeztah how was this fixed?

I am getting the exact same issue on

$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:16:54 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:16:54 UTC 2015
 OS/Arch:      linux/amd64
