### ISSUE TITLE
repos user guide bad link on docker docs site

### ISSUE THREAD

**Issue by d4v3y0rk** [docker/docker#17905]
https://github.com/docker/docker/blob/master/docs/userguide/dockerrepos.md#pushing-a-repository-to-docker-hub (the "here" link in that section)

this link works on github viewing the .md files but not on the docker docs site

https://github.com/docker/docker/blob/master/docs/userguide/dockerimages.md

http://docs.docker.com/v1.7/userguide/userguide/userguide/dockerimages

on [this](http://docs.docker.com/v1.7/userguide/dockerrepos/) page you get a 404 clicking on that link

**Comment by HackToday** [comment]
hi @d4v3y0rk it seems you used old link, please check latest link, I check it works

https://docs.docker.com/engine/userguide/dockerrepos/

**Comment by d4v3y0rk** [comment]
cool, thanks!
