### ISSUE TITLE
[OSX client] Output with --debug causes terminal encoding to go sideways

### ISSUE THREAD

**Issue by nathanleclaire** [docker/docker#17914]
If you run `docker` commands on OSX with `--debug`, this happens:

![screen shot 2015-11-11 at 12 41 01 pm](https://cloud.githubusercontent.com/assets/1476820/11102455/7f405f78-8871-11e5-9852-de7dd2e82459.png)

I'm on iTerm2.

**Comment by nathanleclaire** [comment]
While I do appreciate the extra Unicode snowmen, it's a bit hard to read.

**Comment by thaJeztah** [comment]
Just tried, and this is what I got (also iTerm 2, using fish shell);

```
docker --debug version                              Wed Nov 11 23:11:24 2015
DEBU[0000] Trusting certs with subjects: [010U

sebastiaan]
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64
```

No snowmen, but the debug message looks a bit odd

**Comment by eskaaren** [comment]
iterm2 reports incompatibility with the docker quick start terminal.

https://gitlab.com/gnachman/iterm2/wikis/dockerquickstartincompatible

**Comment by nathanleclaire** [comment]
I can't really dupe this anymore
