### ISSUE TITLE
Broken link in docs about capabilities

### ISSUE THREAD

**Issue by Blaisorblade** [docker/docker#17927]
The page https://docs.docker.com/engine/articles/security/#linux-kernel-capabilities links to the removed https://github.com/docker/docker/blob/master/daemon/execdriver/native/template/default_template.go instead of https://github.com/docker/docker/blob/master/daemon/execdriver/native/template/default_template_linux.go.

## Possible solution to the maintenance problem

You might want to use a link to a specific version (which is never going to break) and update it as needed/wanted; if updates are forgotten, users can at least try to navigate through to a more recent version. Additionally, when pointing to a specific version, it becomes possible to link to specific lines *robustly*, that is, without having to update line numbers at each change.

https://github.com/docker/docker/blob/87de5fdd5972343a11847922e0f41d9898b5cff7/daemon/execdriver/native/template/default_template_linux.go#L16-L29

**Comment by thaJeztah** [comment]
Thanks for reporting @Blaisorblade, I like the suggestion of using a sha, are you interested in creating a PR, or want us to fix this?

**Comment by Blaisorblade** [comment]
My PR's in. It's a pleasure to work with you; sorry I keep forgetting signoffs.

**Comment by thaJeztah** [comment]
Haha, no worries, many people forget them at first.

Thanks for the PR!

**Comment by Blaisorblade** [comment]
More in general: what would you think about linking from each doc page to its source? Is it worth an issue, or do you avoid that on purpose to avoid too many low-quality doc PRs? (I don't expect I can contribute a fix).

The main reason I didn't submit a PR right away weren't the 10 seconds to replace the link, but the potential overhead around those 10 seconds: I didn't know how long it'd take to find the docs, what was their format, whether I needed to install tools to build them, etc.

That's why I started contributing docs around GitHub so often only after they added PRs from the browser — or, after they gamified development ;-).

**Comment by thaJeztah** [comment]
I *think* we actually had those links in the past, but they got removed in the new layout.

I agree that it can sometimes be difficult to find the right location (and repository) for the docs; we're actually in the process of collecting improvements that can be made to the docs, including making it easier to contribute or report changes. This may take some time though :smile:
