### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by sbasyal** [docker/docker#17920]
In this page: http://docs.docker.com/engine/userguide/dockerimages/

Instead of "Tip: You recommend you always use a specific tagged image, for example ubuntu:12.04. That way you always know exactly what variant of an image is being used.", it should be "Tip: We recommend you always use a specific tagged image, for example ubuntu:12.04. That way you always know exactly what variant of an image is being used."

**Comment by thaJeztah** [comment]
Thanks! We try to remove "we" from the documentation, but this was probably a find & replace slip-up :smile:

**Comment by moxiegirl** [comment]
Tip: You should always specify an image tag, for example ubuntu:12.04. That way, you always know exactly what variant of an image your using.  This is useful for troubleshooting and debugging."

**Comment by thaJeztah** [comment]
Created a PR in https://github.com/docker/docker/issues/17921
