### ISSUE TITLE
Update check-config.sh with kernel requirements for overlay network

### ISSUE THREAD

**Issue by Djelibeybi** [docker/docker#17922]
It would be super peachy keen if `contrib/check-config.sh` were updated to include checks for the kernel modules required to support the new `overlay` network driver in Docker 1.9.

**Comment by thaJeztah** [comment]
Yes! I think that's an excellent idea. Are you planning on creating a PR for that, or want me to "ping" the network team to make those changes?

**Comment by Djelibeybi** [comment]
If I knew what the checks should be, I would create the PR. I think we need to ping the network team to provide us with details of which kernel modules are required (and any other networking/kernel configuration).

**Comment by thaJeztah** [comment]
Oh, of course, sgtm

ping @aboch, @mrjana if you have suggestions on how to check for support in the scripts :heart:

**Comment by LK4D4** [comment]
I think that there are checks there now.
@mrjana @mavenugo @sanimej feel free to close this if it's true
