### ISSUE TITLE
Feature request: add labels to volumes

### ISSUE THREAD

**Issue by villlem** [docker/docker#17936]
Problem to solve:
When I'm running/destroying bunch of container docker create a lot of volumes. From time to time I'd like to clean up those, but there is no way to distinguish between autocreated volumes and those that I created via `docker volume create`.  

Proposed solution:
Allow add labels to volumes. Then I can label my volumes (or if those autocreated ones have its own label I can use those).

I know this solution is very generic, but I'm just proposing what was done for containers.

**Comment by cpuguy83** [comment]
Use `--name` on `docker volume create`?

**Comment by villlem** [comment]
That is my current solution. And I create some regexp that filter out my volumes. But I don't like this solution at all. regexp is very error prone and its not usable after volume is created with name that does not match my regexp.

Better solution may be create container that keep volume from beeing deleted. Then I can label those so they are not deleted during my container cleanups.

**Comment by HackToday** [comment]
@villlem I did not get the labels propose here. For labels is it just string ?
If that, What's the difference between name and labels  ? Or you mean one volume can have multiple labels ?

**Comment by pdonorio** [comment]
+1 for multiple labels to volumes as a solution for filter and cleaning

**Comment by villlem** [comment]
For @HackToday and other that suggest to just use name.
Using name is just workaround. I have around 20 volumes that I want to keep around. But just now I have 200 volumes (just after 2 days). I create and burn container frequently and it this container has volume in its manifest (i.e. dockerfile) this volume is created and is not (as it sholdn't be) destroyed after container is destroyed. So from time to time I want do cleanup. That why name is not good solution. Because it difficult to encode flag `don't cleanup` into it. Not to mention when its used, it looks just ugly.

**Comment by LK4D4** [comment]
@cpuguy83 still opposed to it? Would garbage collection fix that?

**Comment by cpuguy83** [comment]
Labels were added to volumes in 1.11.
