### ISSUE TITLE
Uppercase environment variables trigger validation error

### ISSUE THREAD

**Issue by fpereiro** [docker/docker#17943]
Hi there,

Using docker 1.8.3, I get an error when trying to pass an environment variable (through the -e flag) with a value that contains uppercase characters. The error is the following:

repository name component must match "[a-z0-9]+(?:[._-][a-z0-9]+)*"

Could you please change this validation so that uppercase characters can also be valid values of environment variables?

**Comment by duglin** [comment]
can you show us your command line? I suspect you have a typo because we don't restrict env var names. I think your env var is being read as the image name.

**Comment by fpereiro** [comment]
Hi there. Thanks for the quick reply!

This deployment is done through a bash script. Here goes the relevant sections:

EMAIL_ADDRESS="email@domain.com"
EMAIL_SUBJECT="A subject with Uppercase Letters"

docker run -t -i -d -e "EMAIL_ADDRESS=$EMAIL_ADDRESS" -e "EMAIL_SUBJECT=$EMAIL_SUBJECT" --name some-container api

**Comment by duglin** [comment]
I'm not see that error when I try your comments - it just tries to download "api".  Are you sure that's the exact syntax of what you're doing?

**Comment by fpereiro** [comment]
It is not the exact syntax, but it contains the overall idea. For you to
actually run the command that generated this error you would need a
proprietary repo that I cannot make public. The actual command that I use
has many other environment variables declared *after* the one that
generates the issue, so there's no way it is confused with the image name.

I just realized that the problem wasn't the uppercase/lowercase. Rather,
the problem is that the variable value contained a dash. Maybe its presence
affects the command somehow?

2015-11-12 16:54 GMT-03:00 Doug Davis <notifications@github.com>:

**Comment by duglin** [comment]
its possible but I just tried it and it worked.  I think you need to find a way to reproduce this w/o being specific to your environment.  Your repo/image isn't part of the issue - I'm almost certain this is just a syntax typo - so look for a missing "=" or a space in a value that isn't quoted, etc...

Take:
```
docker run -ti ubuntu env
```
and add "-e" flags (from your scenario) until you reproduce it.

**Comment by fpereiro** [comment]
Hi Doug,

I realized this might be because we're running this through ssh. Here's the
command that triggers the error, stripped to the barest:

      ssh -t $USER@HOSTIP bash -c "'
         docker run -t -i -d -e "NAME=VALUE -" --name FOO BAR'"


2015-11-12 17:57 GMT-03:00 Doug Davis <notifications@github.com>:

**Comment by duglin** [comment]
@fpereiro I'd ssh/login to the box directly so you can run the command just to verify things work as expected w/o ssh or quoting getting in the way.  Then once you have that I'd try again via ssh escaping and quoting the heck out of things  :-)

**Comment by fpereiro** [comment]
Hi Doug,

I confirm that the issue has to do with bash escapes, not with docker
itself. I apologize for the confusion. You can close the issue.

Thank you very much for your time!

2015-11-13 16:04 GMT-03:00 Doug Davis <notifications@github.com>:

**Comment by duglin** [comment]
@fpereiro will do - thanks
