### ISSUE TITLE
Error running deviceCreate (createSnapDevice) dm_task_run failed

### ISSUE THREAD

**Issue by bussiere** [docker/docker#17956]
When trying to create a simple dockerfile :   

root@ns333968:~/DockerBuild# docker build .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM ubuntu:trusty
 ---> 91e54dfb1179
Step 2 : MAINTAINER Bussiere
 ---> Using cache
 ---> 911dab2dbd76
Step 3 : RUN locale-gen fr_FR.UTF-8
Error running deviceCreate (createSnapDevice) dm_task_run failed

root@ns333968:~/DockerBuild# docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64
root@ns333968:~/DockerBuild# 

The dockerfile :  
FROM ubuntu:trusty
MAINTAINER  Bussiere
RUN locale-gen fr_FR.UTF-8
ENV LANG fr_FR.UTF-8
ENV LANGUAGE fr_FR.UTF-8
ENV LC_ALL fr_FR.UTF-8
RUN apt-get update && apt-get -y upgrade && apt-get -y dist-upgrade
RUN apt-get -y install encfs wget
RUN mkdir -p /home/qpso
CMD ["/bin/bash"]

**Comment by crosbymichael** [comment]
@bussiere can you please provide your host system information?

**Comment by thaJeztah** [comment]
closing because we need more information (as mentioned by @GordonTheTurtle above), but happy to reopen once that information is added
