### ISSUE TITLE
Proposal: Set environment variables for published ports

### ISSUE THREAD

**Issue by nnordrum** [docker/docker#17968]
While setting the `--advertise 10.xxx.xxx.xxx:12375` argument on Swarm, I realized that this information already exists and Swarm could read it by default, if it was easily available to the container.

I propose the following:
```
PORT_80_TCP=tcp://<published IP>:<published port>
PORT_80_TCP_ADDR=<published IP>
PORT_80_TCP_PORT=<published port>
PORT_80_TCP_PROTO=tcp
```

obviously adjust for port and protocol, but I took these from a container with a --link and just removed the linked name. Follow all rules that --link uses to create the variables for the port mappings, so at least it's consistent.

**Comment by crosbymichael** [comment]
I think the general model that we are trying to get away from is discovery information in the environment.  This is more of a swarm issue so I would suggest opening this proposal on the swarm repo because the code changes required would happen there.  

https://github.com/docker/swarm

Thanks!
