### ISSUE TITLE
[1.9.1-rc1] Could not delete local endpoint ... during endpoint cleanup: endpoint with name ... id a67a87... has active containers 

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#17984]
While stress testing for #17720 I think this error which is preventing the daemon from starting now.  What I was doing starting containers as fast as I could in a loop (which is about 1 per second), and then I was switch back and forth between 1.9.0 and 1.9.1-rc1.  So run the daemon for a bit, hit CTRL-C and then start the other.  Now I hit this error and the daemon won't start on either version now.

```
WARN[0000] Could not delete local endpoint loving_nobel during endpoint cleanup: endpoint with name loving_nobel id a67a8768680792b5d5b22158d6720e466b92747f89422b487f5fb44af54639df has active containers 
DEBU[0000] Cleaning up old shm/mqueue mounts: start.    
FATA[0000] Error starting daemon: Error initializing network controller: could not delete the default bridge network: network bridge has active endpoints 
```

**Comment by LK4D4** [comment]
ping @mavenugo @mrjana

**Comment by mavenugo** [comment]
@ibuildthecloud do you have the complete daemon logs ? It seems there is a race between the container start and ungraceful daemon restarts causing this issue.
Will take a look at the possible cause. daemon logs (with debugs) will be helpful.

**Comment by mavenugo** [comment]
@mrjana i see a possible race condition in the scenario that @ibuildthecloud mentioned. will push a PR in libnetwork and we can discuss on that.

**Comment by mavenugo** [comment]
@ibuildthecloud could you please try the master and confirm if it solves the issue that you were seeing ?
