### ISSUE TITLE
Unable to connect to docker registry

### ISSUE THREAD

**Issue by mahehss** [docker/docker#17990]
When I try connecting to docker private registry(trail version install in one of my AWS servers) from a docker host I get the following error:

FATA[0000] Error response from daemon: v1 ping attempt failed with error: Get https://docker-registry.xyz.com/v1/_ping: x509: certificate signed by unknown authority. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry docker-registry.nearbuytools.com` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/docker-registry.xyz.com/ca.crt 

I tried docker login <registry url> command. the registry has a valid certificate and it is placed in the mentioned location.(i.e. etc/docker/certs.d/docker-registry.xyz.com/ca.crt )

Docker details: 
 sudo docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64
ubuntu@ip-172-20-0-9:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.7", GitCommit:"6234d6a0abd3323cd08c52602e4a91e47fc9491c", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.7", GitCommit:"6234d6a0abd3323cd08c52602e4a91e47fc9491c", GitTreeState:"clean"}

**Comment by mahehss** [comment]
uname -a
Linux ip-172-20-0-9 3.19.0-33-generic #38-Ubuntu SMP Fri Nov 6 18:18:12 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

It is an EC2 instance. Other details are already given.

**Comment by thaJeztah** [comment]
Just checking up; have you been able to solve this issue @mahehss? Wondering if this is related to https://github.com/docker/docker/issues/9118

**Comment by LK4D4** [comment]
I think this was fixed.
