### ISSUE TITLE
huge php performance drop after upgrade to 1.9

### ISSUE THREAD

**Issue by greg0ire** [docker/docker#17994]
Since I upgraded to docker 1.9, I have noticed a huge performance drop when running php in a container of mine.

Steps to reproduce : 

```
docker run -it greg0ire/php /bin/bash
time php -r "phpinfo();"
```

Expected results: instant output

Actual results : 
```
real	0m3.476s
user	0m0.057s
sys	0m0.045s
```

Here is [the dockerfile](https://hub.docker.com/r/greg0ire/php/~/dockerfile/)

I'm running docker 1.9 on Fedora 23, and I had no choice but to use the *testing* repository for F23 to do that (the main repo does not exist yet, it seems). I am using 1.9.1-rc1. I first observed the problem at work, on an Ubuntu 15.04

```
docker version
Client:
 Version:      1.9.1-rc1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   aba5981
 Built:        Fri Nov 13 10:13:53 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1-rc1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   aba5981
 Built:        Fri Nov 13 10:13:53 UTC 2015
 OS/Arch:      linux/amd64

```

```
Containers: 121
Images: 294
Server Version: 1.9.1-rc1
Storage Driver: devicemapper
 Pool Name: docker-253:1-24248323-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 8.758 GB
 Data Space Total: 107.4 GB
 Data Space Available: 98.62 GB
 Metadata Space Used: 18.76 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.129 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /mnt/data/disposable/docker/devicemapper/devicemapper/data
 Metadata loop file: /mnt/data/disposable/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107 (2015-09-05)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.5-300.fc23.x86_64
Operating System: Fedora 23 (Workstation Edition)
CPUs: 2
Total Memory: 3.86 GiB
Name: liche
ID: TEF4:LIQK:IENW:K2GR:VZWU:ZPHC:FIWU:4BEF:3MQK:ZETW:PMTZ:CDJ6
Username: greg0ire
Registry: https://index.docker.io/v1/
```

Kernel info : 

```
uname -a
Linux liche 4.2.5-300.fc23.x86_64 #1 SMP Tue Oct 27 04:29:56 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by LK4D4** [comment]
It might be devicemapper :) But I'm not sure.

**Comment by greg0ire** [comment]
Can you point me to a doc describing how to use something else ? (overlay ?)

**Comment by LK4D4** [comment]
@greg0ire never read myself, but something here https://docs.docker.com/engine/userguide/storagedriver/selectadriver/ :)

**Comment by greg0ire** [comment]
Thanks, I'm going to try that, but I might be interrupted soon, sorry if I don't report back for a while.

**Comment by greg0ire** [comment]
I just tried with overlayfs (I checked docker info to be sure), and the results are just as bad : 

```
real	0m3.080s
user	0m0.050s
sys	0m0.021s
```

**Comment by greg0ire** [comment]
BTW, shell commands like cd or ls are fast…

**Comment by LK4D4** [comment]
@greg0ire Thanks, I'll try too.

**Comment by greg0ire** [comment]
Oh wait, I think I found the answer : 

```
cat /tmp/xdebug.log 
Log opened at 2015-11-15 17:02:56
I: Connecting to configured address/port: 172.17.42.1:9000.
E: Could not connect to client. :-(
Log closed at 2015-11-15 17:02:59
```

**Comment by LK4D4** [comment]
@greg0ire What does it mean? :) Is it problem on your side?

**Comment by greg0ire** [comment]
XDebug is an extension to do remote debugging. And I am still using the old IP, as you can see, so yes definitely on my side, sorry for that.

**Comment by greg0ire** [comment]
For the record, XDebug tries to connect on the host on port 9000, finds nothing and stops. Since upgrading to 1.9, the ip is not the same so this is not as quick as it was before. Really sorry for the noise.
