### ISSUE TITLE
Unable to cd into directory after chown

### ISSUE THREAD

**Issue by Flavien** [docker/docker#18006]
I am just trying to copy some files in the container and ``chown`` them so that the non-root user can access them.

The problem is even though the permissions are set correctly, I am still unable to ``cd`` into the directory.

```
openchain@e1f19b15c9c1:/openchain.server/approot/src$ ls -al
total 28
drwx------ 17 openchain openchain 4096 Nov 16 10:02 .
drwx------  5 openchain openchain 4096 Nov 16 10:02 ..
drwx------  2 openchain openchain 4096 Nov 16 10:02 Openchain.Abstractions
drwx------  5 openchain openchain 4096 Nov 16 10:02 Openchain.Ledger
drwx------  2 openchain openchain 4096 Nov 16 10:02 Openchain.Ledger.Blockchain
drwx------ 14 openchain openchain 4096 Nov 16 10:02 Openchain.Server
drwx------  2 openchain openchain 4096 Nov 16 10:02 Openchain.Sqlite
openchain@e1f19b15c9c1:/openchain.server/approot/src$ cd Openchain.Abstractions/
bash: cd: Openchain.Abstractions/: Permission denied
```

I am using Docker 1.9.0:

```
flavien@docker-vm:/media/sf_share$ sudo docker -D info
Containers: 157
Images: 519
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 833
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-32-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 994 MiB
Name: docker-vm
ID: 7AA4:R75H:MFJU:WJI5:YEK2:VTNE:7G7F:LI67:AA2F:NEI2:BSHQ:QMUU
Username: [redacted]
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

flavien@docker-vm:/media/sf_share$ sudo docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

flavien@docker-vm:/media/sf_share$ uname -a
Linux docker-vm 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by crosbymichael** [comment]
@Flavien can you post a reproducible case so that I can try it out and see what is going on?  Maybe a simple dockerfile with your steps on dummy data?

**Comment by Flavien** [comment]
Ok I will try to provide a dockerfile reproducing that, but I manage to get around the issue by switching to devicemapper.

**Comment by crosbymichael** [comment]
ahh, i think this is an aufs bug that the permissions at a lower layer cannot be overriden by a higher layer.  Not much we can do for this other than try devicemapper or overlayfs to fix this.  You could also try changing the permission on the lower layers instead. 

This PR should fix your issue:

https://github.com/docker/docker/pull/11799

but I see that in your `docker info` dirperm1 is not supported.  

```
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 833
 Dirperm1 Supported: false
```

I believe you need a more recent version of aufs for this option though but it will fix the issue you are seeing.  I tested on an ubuntu 15.04 system and it does have the new aufs dirperm1 support so if you are able to upgrade you will get the fix and be able to stay on aufs.  

Sorry I cannot be more help but I think upgrading to 15.04 would be your best bet if you are able to do that.
