### ISSUE TITLE
Cannot mount disk images in container

### ISSUE THREAD

**Issue by koehn** [docker/docker#18018]
Description of problem:
If I create a disk image in a container, I get "mount failed: Unknown error -1" when I try to mount it inside said container. 

`docker version`:
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64

(also tried this from Ubuntu 14.04 with the same results)

`docker info`:
(again got same results on Ubuntu 14.04)

Containers: 3
Images: 84
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 90
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.12-boot2docker
Operating System: Boot2Docker 1.9.0 (TCL 6.4); master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: NAVT:Z5CR:H7AV:MPOB:HJY7:O6BO:UBVB:6FO3:X4EY:J6LL:3CIV:EEK5
Debug mode (server): true
 File Descriptors: 31
 Goroutines: 102
 System Time: 2015-11-16T16:42:45.666763012Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

`uname -a`:
Darwin CRP11254M 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64

Environment details (AWS, VirtualBox, physical, etc.):
VirtualBox on MacOSX El Capitan, but also occurs on Ubuntu 14.04.

How reproducible:
Always.

Steps to Reproduce:
1. `IMAGE_FILE=/tmp/databaseimage.img`
2. `MOUNTPOINT=/tmp/mountpoint`
3. `SIZE=1000M`
4. `mkfs -t ext4 $IMAGE_FILE`
5. `mkdir -p $MOUNTPOINT && mount -t auto -o loop $IMAGE_FILE $MOUNTPOINT`

Actual Results:
`mount failed: Unknown error -1`

Expected Results:
Mounts successfully.

Additional info:
These same commands work just fine on straight linux outside the container.

**Comment by phemmer** [comment]
Did you start your container with `--privileged` or `--cap-add=CAP_SYS_ADMIN`?

See https://docs.docker.com/engine/articles/security/#linux-kernel-capabilities

**Comment by koehn** [comment]
Ahh. Trying to do this from a `RUN` command. Looks like I've run into this issue:

https://github.com/docker/docker/issues/1916

**Comment by cpuguy83** [comment]
Ok, looks like this is a dup, closing.
