### ISSUE TITLE
Issue with docker login & push with Docker Default Registry - Windows ENV - 1.9.1-RC1

### ISSUE THREAD

**Issue by Miguel-Fontes** [docker/docker#18019]
# Description of problem
Issues with ‘docker login’ on Windows.
The command returns Status Code 403 – Request forbidden by administrative rules.

# Docker version
1.9.1-rc1

# Docker info

<img width="742" alt="docker_meta" src="https://cloud.githubusercontent.com/assets/15656072/11188137/8fcff33c-8c70-11e5-93e1-dadfa0446683.png">

# Environment details (AWS, VirtualBox, physical, etc.):
Vritual Box Provider

# How reproducible:
Just input ‘docker login’ into CLI without adding any providers.

# Steps to Reproduce:
1. open CLI on Windows
2. docker login <your login info>
3. check return

### Actual Results:

    Error response from daemon: "Unexpected status code [403] - <html><body><h1> 403 Fobidden</h1> Request forbidden by administrative rules. </body></html>"

<img width="742" alt="login_forbidden_all" src="https://cloud.githubusercontent.com/assets/15656072/11188201/dbcf76b8-8c70-11e5-9f07-e66c4d50b1b5.png">

### Expected Results:
Successful login into Docker default registry for Windows and full integration with docker hub.

# Additional info:
After some analysis of the source code I’ve detected that we have different registry URLs for Windows and UNIX.

* Windows: https://registry-win-tp3.docker.io/v1/
* Unix: https://index.docker.io/v1/

I’m using the freshly baked 1.9.1-rc1

While both urls are responding to requests, playing with docker login and those data, i could notice two different behaviors.
- Environment Windows + Docker Login with https://registry-win-tp3.docker.io/v1/
  - Returns Request forbidden by administrative rules
- Environment Windows + Docker Login with https://index.docker.io/v1/
  - Login succeeds.
  - Still can’t docker push. Command returns: unauthorized: access to the requested resource is not authorized.

Actually, checking the code, I could not detect an actual problem with the docker/docker but maybe it’s an registry issue.

I'm proceed into double checking the functionality with other Registry.

My examples used the basic Getting Started Guide for the sake of understanding: http://docs.docker.com/mac/step_six/

Actually I’m a docker newbie but in love with the project and looking forward into contributing. I could be missing something so, feel free to shed some light into my ramblings.

**Comment by stevesri** [comment]
I have the same issue.

**Comment by Dinosys** [comment]
Same problem here.

When using docker login --username=**** --password=**** --email=****
format:

```
$ docker login --username=frankbouma --password=<pass> --email=<email>
Error response from daemon: Unexpected status code [403] : <html><body><h1>403 Forbidden</h1>
Request forbidden by administrative rules.
</body></html>
```

When using simple docker login:

```
$ docker login
Username: frankbouma
The handle is invalid.
```



**docker version:** 
```
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64
```

**docker info:**
```
Containers: 38
Images: 33
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 109
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.12-boot2docker
Operating System: Boot2Docker 1.9.0 (TCL 6.4); master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: default
ID: DIQV:M65R:NVEQ:ZOSQ:SR2O:UP6J:JI3D:MXCJ:MJQF:SFKN:AOOX:QBDE
Debug mode (server): true
 File Descriptors: 13
 Goroutines: 19
 System Time: 2015-11-17T08:19:48.385329072Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```
**uname -a**
```
MINGW64_NT-6.1 BA91-CND5268397 2.1.0(0.288/5/3) 2015-06-28 18:57 x86_64 Msys
```

**Comment by JigSawFr** [comment]
Same issue too.

**Comment by likfarmenhet** [comment]
Same issue here

**Comment by JigSawFr** [comment]
Registry problem confirmed.
Test with tutum.co registry with no problems,
Docker image pushed correctly.

**Comment by aaronbarzilai** [comment]
I have the same issue as well.  Looking forward to seeing this corrected, otherwise docker is working quite well for me.

Thanks,
Aaron

**Comment by Miguel-Fontes** [comment]
@JigSawFr Same here!

Considering the auth options supported by Registry (Native Basic, Proxy or Delegated as explained [here](https://github.com/docker/distribution/blob/master/docs/deploying.md#native-basic-auth)), i'm inclined the believe that this issue is not related to Registry's code - maybe we're just facing an infraestructure problem on the 'authentication layer' of https://registry-win-tp3.docker.io/v1/.

That said, i think this problem should be reported at 'hub-feedback' as well.

<img width="705" alt="sem titulo" src="https://cloud.githubusercontent.com/assets/15656072/11215748/f3d780de-8d2e-11e5-90c4-f8631b0d0a2f.png">

**Comment by diamxus** [comment]
I am having the same issues as others have mentioned above when following Windows demo\example.

**Comment by reyabreu** [comment]
same issue here as well.

uname@hostname MINGW64 /c/work/hello-docker
$ docker login -u <uname> -p <password> -e <email>
Error response from daemon: Unexpected status code [403] : <html><body><h1>403 F
orbidden</h1>
Request forbidden by administrative rules.
</body></html>

uname@hostname MINGW64 /c/work/hello-docker
$ docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64

uname@hostname MINGW64 /c/work/hello-docker
$ docker info
Containers: 0
Images: 22
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 22
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.12-boot2docker
Operating System: Boot2Docker 1.9.0 (TCL 6.4); master : 16e4a2a - Tue Nov  3 19:
49:22 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: default
ID: R2LG:LMA5:BAAY:YTZB:RB4P:N5L7:MDOI:DI6O:33V2:X35I:OKHW:XV7X
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 20
 System Time: 2015-11-18T12:03:46.800984642Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

**Comment by lvendrame** [comment]
same issue here too

$ docker version
>Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      windows/amd64

>Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64

$ docker info
>Containers: 7
Images: 14
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 28
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.12-boot2docker
Operating System: Boot2Docker 1.9.0 (TCL 6.4); master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: default
ID: RXO4:BZTI:NLLT:42X3:U7OD:2QIF:GP73:DI3H:4JBO:WAYZ:OOJV:Y4DL
Debug mode (server): true
 File Descriptors: 11
 Goroutines: 20
 System Time: 2015-11-18T16:29:10.800814501Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

$ uname -a
>MINGW64_NT-10.0 DESKTOP-NHI74HQ 2.1.0(0.288/5/3) 2015-06-28 18:57 x86_64 Msys

**Comment by JigSawFr** [comment]
Related to : https://github.com/docker/hub-feedback/issues/473 :arrow_right: 
With work around

**Comment by VathsalaAchar** [comment]
@JigSawFr Thanks the above fix worked!

**Comment by FacioRatio** [comment]
Didn't work for me. I had a Docker Hub account that I created a while back, but forgot my password for. I changed my password today, created a new private repo, and I get all the variety of issues described above. I have tried creating a .dockercfg manually (since I never had one to begin with), but that did not work, either. Trying to pull the repo I created says it's not found as well.

**Comment by Miguel-Fontes** [comment]
Thanks for the info @JigSawFr!

Using that workaround i can login successfully at DockerHub using the default unix registry but, when i try to push, docker doesn't  my repos.

**Comment by thedole** [comment]
+1 for this workaround, it saved the day!

**Comment by lucasvc** [comment]
@FacioRatio The correct configuration file is `%USERPROFILE%\.docker\config.json`. It worked for me.

**Comment by tyagian** [comment]
Found the solution: 
http://networkengg.com/docker-login-failed-on-windows-403-forbidden-error/

**Comment by siripuramrk** [comment]
Thanks  @JigSawFr! Working :+1: 

#######
docker login --username=myuser --password=mypassword --email=myemail https://index.docker.io/v1/
WARNING: login credentials saved in C:\Users\myuser\.docker\config.json
Login Succeeded
#######

**Comment by onlinespaces** [comment]
To get docker to create the config.json file, I had to first run:

docker login --username=<username> --email=<email address> https://index.docker.io/v1/

Then, I was able to modify the config.json file as shown here:

http://networkengg.com/docker-login-failed-on-windows-403-forbidden-error/

Everything is now working.

**Comment by tshepotema** [comment]
https://github.com/docker/hub-feedback/issues/473 <-- This worked for me

![docker-push](https://cloud.githubusercontent.com/assets/4511288/12641853/bf1a7260-c5ba-11e5-9ca1-fe0da5c6976b.JPG)

**Comment by reyabreu** [comment]
Overdue thanks to @JigSawFr. Got it working :+1:

**Comment by Wind4Greg** [comment]
Still broken as of 2/2/2016, with brand new docker install on windows.

**Comment by tiborvass** [comment]
@Wind4Greg it's merged and will be released in 1.10

**Comment by Wind4Greg** [comment]
When will it be released/where can I get it?

**Comment by thaJeztah** [comment]
@Wind4Greg we're planning on releasing docker 1.10.0-rc3 today; hopefully, final release on Thursday

**Comment by gerrytan** [comment]
Also affected by this problem. Pretty bad because everyone who's following the getting started tutorial would've been stuck by this

**Comment by atipal** [comment]
Strange issue. Can't finish the tutorial :-1:

**Comment by friism** [comment]
@gerrytan @atipal @Wind4Greg 1.10 is ready now and fixes this problem, you can get it here: https://github.com/docker/toolbox/releases/tag/v1.10.0

**Comment by cvugrinec** [comment]
docker-machine upgrade <name of your instance>
