### ISSUE TITLE
Dockerfile caching behavior for build-args is not documented

### ISSUE THREAD

**Issue by trcarden** [docker/docker#18017]
The official dockerfile reference doesn't speak to how changing a build argument will affect the docker build cache.

http://docs.docker.com/engine/reference/builder/#arg

I did a little experiment and i believe the behavior is as follows:

1. If the argument changes then the cache is busted at the first usage of that argument (not at the argument declaration)
2. The cache remembers previous invocations (not just the last one). So switching a build arg from A to B to C to B to A (all else held equal) will force new layers for the first A, B and C and then will use the cache for the second B and A.

**Comment by duglin** [comment]
See #18161

**Comment by thaJeztah** [comment]
Thanks for finding this omission, @trcarden !

**Comment by pnovotnak** [comment]
Hey all, I don't believe the documentation pushed in #18161 this is correct (anymore?) On my machine it seems like the cache is busted at declaration, not usage. Could someone verify?

**Comment by pnovotnak** [comment]
Here's a demonstration; https://github.com/pnovotnak/docker-build-arg-caching

**Comment by duglin** [comment]
@pnovotnak I see the cache being used in both cases for the ARG lines.  Isn't that correct?

**Comment by pnovotnak** [comment]
Here's what I get on my machine;

 Running with arg before...

    ---- run 1 ----
    Sending build context to Docker daemon 51.71 kB
    Step 1 : FROM python:3
     ---> a08871375fac
    Step 2 : ARG TEST_ARG
     ---> Running in 7cdec0e7e562
     ---> 22f0b5923c02
    Removing intermediate container 7cdec0e7e562
    Step 3 : ADD requirements.txt /requirements.txt
     ---> 1f694b60bdd0
    Removing intermediate container 24d8464ea3c4
    Step 4 : RUN pip install -r /requirements.txt
     ---> Running in 51ece6883396
    Collecting django (from -r /requirements.txt (line 1))
      Downloading Django-1.10.1-py2.py3-none-any.whl (6.8MB)
    Installing collected packages: django
    Successfully installed django-1.10.1
     ---> 28260172ca20
    Removing intermediate container 51ece6883396
    Successfully built 28260172ca20
    ---- run 2 ----
    Sending build context to Docker daemon 51.71 kB
    Step 1 : FROM python:3
     ---> a08871375fac
    Step 2 : ARG TEST_ARG
     ---> Using cache
     ---> 22f0b5923c02
    Step 3 : ADD requirements.txt /requirements.txt
     ---> Using cache
     ---> 1f694b60bdd0
    Step 4 : RUN pip install -r /requirements.txt
     ---> Running in 152f42b21a1d
    Collecting django (from -r /requirements.txt (line 1))
      Downloading Django-1.10.1-py2.py3-none-any.whl (6.8MB)
    Installing collected packages: django
    Successfully installed django-1.10.1
     ---> ff1f7635431e
    Removing intermediate container 152f42b21a1d
    Successfully built ff1f7635431e


Running with arg after...

    ---- run 1 ----
    Sending build context to Docker daemon 51.71 kB
    Step 1 : FROM python:3
     ---> a08871375fac
    Step 2 : ADD requirements.txt /requirements.txt
     ---> e308e75b154c
    Removing intermediate container 9bb795e75378
    Step 3 : RUN pip install -r /requirements.txt
     ---> Running in 0a3be29f2244
    Collecting django (from -r /requirements.txt (line 1))
      Downloading Django-1.10.1-py2.py3-none-any.whl (6.8MB)
    Installing collected packages: django
    Successfully installed django-1.10.1
     ---> 9fd6e6baa9c2
    Removing intermediate container 0a3be29f2244
    Step 4 : ARG TEST_ARG
     ---> Running in 707bf1de4a86
     ---> 92f62a47cded
    Removing intermediate container 707bf1de4a86
    Successfully built 92f62a47cded
    ---- run 2 ----
    Sending build context to Docker daemon 51.71 kB
    Step 1 : FROM python:3
     ---> a08871375fac
    Step 2 : ADD requirements.txt /requirements.txt
     ---> Using cache
     ---> e308e75b154c
    Step 3 : RUN pip install -r /requirements.txt
     ---> Using cache
     ---> 9fd6e6baa9c2
    Step 4 : ARG TEST_ARG
     ---> Using cache
     ---> 92f62a47cded
    Successfully built 92f62a47cded

The docs specifically state: '...a "cache miss" occurs upon its first usage, not its declaration.' `pip install -r requirements.txt` runs both times in the first Dockerfile, while only running once in the second one. Am I misunderstanding how the build cache is supposed to work?

**Comment by duglin** [comment]
Ah ok - its because in the 2nd one you don't declare the ARG until after the RUN. The list of envs for the RUN isn't impacted by any ARGs defined after it.

**Comment by SystemParadox** [comment]
For anyone else stumbling upon this, the documentation appears to have disappeared so this is now undocumented again.

Furthermore, from my testing (docker 24.0.5) it also appears that the documention is indeed no longer correct - `ARG` invalidates the cache based on where the `ARG` declaration appears in the dockerfile, not based on where it is used. So if you put all your ARGs at the top your entire cache will be invalidated every time your args change.

**Comment by thaJeztah** [comment]
> For anyone else stumbling upon this, the documentation appears to have disappeared so this is now undocumented again.

Looks like the section added by https://github.com/moby/moby/pull/18161 is still there (but the documentation source moved to a different repository); https://docs.docker.com/engine/reference/builder/#impact-on-build-caching

> Furthermore, from my testing (docker 24.0.5) it also appears that the documention is indeed no longer correct - ARG invalidates the cache based on where the ARG declaration appears in the dockerfile, not based on where it is used. So if you put all your ARGs at the top your entire cache will be invalidated every time your args change.

I don't think that changed, but the behavior can be subtle depending on how / where your build-args are used (for example, build-args can be used as part of `FROM` statements.

@SystemParadox If you have a specific example where you see this happening, and think it doesn't match the documentation, it's better to open a new ticket for this, as this ticket is nearly 10 Years old, and given that this is related to the Dockerfile syntax (which is now maintained as part of the BuildKit project), it might be best to open a ticket in the BuildKit issue tracker; https://github.com/moby/buildkit/issues
