### ISSUE TITLE
FIle system of container become read-only

### ISSUE THREAD

**Issue by ivokotev** [docker/docker#18015]
Hello friends,

We are having strange problem with file system of a container. We observed this issue in following running containers – opensuse, ubuntu (official) and sles12 all latest versions. Containers are run on VMWare VM host with SLES12.

Issue is following: After we run the container /proc/mounts file shows that FS is read/write

cat /proc/mounts 
… 
/dev/mapper/docker-254:5-1452-701284ae46bd92f54ddaa7914e9043ecb678c450f208dc1074fd2ba1a8865508 
/ ext4 rw,relatime,discard,stripe=16,data=ordered 
0 0

Then when I run an application that is using massively FS for writing some files on it, file system of the container become read-only and /proc/mounts shows following

cat /proc/mounts 
… 
/dev/mapper/docker-254:5-1452-701284ae46bd92f54ddaa7914e9043ecb678c450f208dc1074fd2ba1a8865508 
/ ext4 ro,relatime,discard,stripe=16,data=ordered 
0 0

Simple way to reproduce the issue is execution of below script. It turns read/write FS mode 
to read-only.The idea of script is to simulate mass writing of files to FS of the container (in this case it creates 50000 text files each one having 100 lines) on file system. After a while FS of the container stands read-only and script stops working. By the way I observed that similar faire you can reproduce if you just echo some text many times (50000 ) on the console.

Here is script source.

#!/bin/bash 
for (( c=1; c<=5000000; c++ )) 
do 
echo "Some text $c" >> outfile$(( c / 100 )).out 
done

**Comment by phemmer** [comment]
This is likely going to be because of a bug in the kernel (filesystem driver, lvm driver, etc).
Check `dmesg`. You'll likely find a message about filesystem corruption and the filesystem getting remounted read-only.

**Comment by crosbymichael** [comment]
This is not docker that is doing this, it is something else.  are you using any type of quotas or other programs on the server that would limit IO or disk usage?

**Comment by crosbymichael** [comment]
lets close this one as a dup of #18010 and keep all the information there.  it looks like a kernel issue
