### ISSUE TITLE
Add daemon-wide flag for container cgroups parent

### ISSUE THREAD

**Issue by LK4D4** [docker/docker#18022]
ping @vishh

**Comment by icecrime** [comment]
Assigning to @anusha-ragunathan as I understand you'll be carrying #18379 during @LK4D4 absence.

**Comment by icecrime** [comment]
Oh well, I can't because assigning requires write-access =/ You get the idea though!

**Comment by anusha-ragunathan** [comment]
I'm carrying this forward after a rebase in https://github.com/docker/docker/pull/19062

**Comment by icecrime** [comment]
Thanks!
