### ISSUE TITLE
Docs: Docker guide engine/userguide/networkingcontainers/ - missing --format flag in example

### ISSUE THREAD

**Issue by dmitris** [docker/docker#18039]
https://docs.docker.com/engine/userguide/networkingcontainers/ - one of the examples is missing --format (or -f) parameter.  In the "Add containers to a network" section, after the words:
"Then, get the IP address of your web", there is an example:
```
$ docker inspect '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' web
```
It should be, similar to the one above:
```
$ docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' web
```
otherwise the user gets an error:
```
$ docker inspect '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' certsignd
Error: No such image or container: {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}
```
and a very long JSON blob with the full config.

**Comment by thaJeztah** [comment]
Thanks for reporting @dmitris I checked and this looks to be fixed in this PR https://github.com/docker/docker/pull/17973

Thanks for paying attention! :+1:
