### ISSUE TITLE
Cannot close stdin when connected to docker swarm cluster using "docker run" with TLS.

### ISSUE THREAD

**Issue by yoshiokatsuneo** [docker/docker#18035]
When I just connected to normal docker server, stdin is closed as expected.
But, when I connected to docker swarm cluster, stdin is not closed and "docker run" never exit.

```
$ eval $(docker-machine env master)
$ echo aaa | docker run -i ubuntu cat |grep aaa
aaa
$ eval $(docker-machine env --swarm master)
$ echo aaa | docker run -i ubuntu cat |grep aaa
aaa
^C^C^C^C
^C^C^C^C
^C^C^C
Connection to docker.paiza.io closed.
```

**Comment by yoshiokatsuneo** [comment]
docker version:
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/1.0.0
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   087e245
 Built:        
 OS/Arch:      linux/amd64



docker info:
$ docker info
Containers: 22
Images: 3
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 1
 master: 52.68.106.74:2376
  └ Containers: 22
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.018 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.13.0-53-generic, operatingsystem=Ubuntu 14.04.2 LTS, provider=amazonec2, storagedriver=aufs
CPUs: 1
Total Memory: 1.018 GiB
Name: 873b02fada2d



uname -a:
$ uname -a
Linux ip-172-30-1-65 3.13.0-65-generic #106-Ubuntu SMP Fri Oct 2 22:08:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Provide additional environment details (AWS, VirtualBox, physical, etc.):
AWS

List the steps to reproduce the issue:
1. "docker run" to normal node, and it exit as expected.
$ echo aaa | docker run -i ubuntu cat |grep aaa
aaa

2. "docker run" to swarm cluster, and it never exit.
$ echo aaa | docker run -i ubuntu cat |grep aaa
aaa
^C^C^C^C
^C^C^C^C
^C^C^C
Connection to docker.paiza.io closed.

Describe the results you received:
"docker run" never exit when stdin is closed.

Describe the results you expected:
"docker run" exit when stdin is closed.

**Comment by yoshiokatsuneo** [comment]
And, it turned out that the never exiting issue happens only on TLS mode with swarm(docker-proxy), and does not happen without TLS, or direct connection to docker node (with/without TLS).

**Comment by yoshiokatsuneo** [comment]
Also, it turned out that normal docker daemon implement CloseWrite() function for half close and use own "dial"("tlsDial") instead of "crypt/tls"'s "Dial" function.
  https://github.com/docker/docker/blob/master/api/client/hijack.go
How about using the same "dial" implementation at the swarm module ?

**Comment by cpuguy83** [comment]
Closing since this is a swarm issue.

Thanks!
