### ISSUE TITLE
UI Application on MAc

### ISSUE THREAD

**Issue by cemary** [docker/docker#18040]
So I'm new to docker and am playing with containers.  The ultimate goal would be to have N number of containers with the dev tools I normally use.  I chose sublime text 3 as the first tool.  I ran this:

docker run katelibbey/sublime-text-3

The error is:

(sublime_text:1): Gtk-WARNING **: cannot open display:

After poking around on the web it looks like a X issue.  I ran this:

echo $DISPLAY
/private/tmp/com.apple.launchd.u0i90HB6Uq/org.macosforge.xquartz:0

I then tried various options of docker -e DISPLAY=xxx and nothing seemed to work.  So the question is what is the magic to get GUI apps to run on a Mac?

**Comment by cemary** [comment]
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64

docker info
-----------------------
Containers: 5
Images: 27
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 37
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.12-boot2docker
Operating System: Boot2Docker 1.9.0 (TCL 6.4); master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: RYZQ:E6EZ:LUBM:DFNE:LBK6:YWEX:YQV5:R3ZB:EWW3:L6SA:YEZD:G62Z
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 20
 System Time: 2015-11-17T15:24:45.729786314Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

uname -a
-------------------------------------------------
Darwin Chucks-MacBook-Pro.local 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64

steps to reproduce:
1.  docker run katelibbey/sublime-text-3

Results:
(sublime_text:1): Gtk-WARNING **: cannot open display:

Expected:
1.  The sublime text 3 GUi application should have launched

**Comment by tophj-ibm** [comment]
I start up socat in a different terminal, and pass the display to my container as explained [here](https://github.com/docker/docker/issues/8710#issuecomment-71113263). Note you can use 'docker-machine ls' to get the IP address you need.

You should also check out the #Docker irc channel on freenode :)

**Comment by cemary** [comment]
So I have installed socat.  I launched it per the article you linked:

lsof -i :6000
COMMAND   PID   USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
socat   56714 sensei    5u  IPv4 0x61d021b2fb4c4d0b      0t0  TCP *:6000 (LISTEN)

----------------------------
docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM
default   *        virtualbox   Running   tcp://192.168.99.100:2376

-----------------------------
run -e DISPLAY=192.168.99.100:0 katelibbey/sublime-text-3

(sublime_text:1): Gtk-WARNING **: cannot open display: 192.168.99.100:0

---------------------------
echo $DISPLAY
/private/tmp/com.apple.launchd.u0i90HB6Uq/org.macosforge.xquartz:0

I opened a new docker terminal window after starting socat.  Any thoughts on how I should proceed?

**Comment by tophj-ibm** [comment]
Oh, that's my bad. You need the inet address of virtualbox from ifconfig, not the docker-machine one.

**Comment by cemary** [comment]
Hi,
That did the trick, thanks so much for responding so quickly!  I have to
say that this technology seems to be way cool and way useful!

Cheers,
Chuck

Solutions Architect,
Chuck Emary

**Comment by tophj-ibm** [comment]
NP. Docker is definitely cool and useful, have fun messing around with containers!. Also please close this issue, it should be a button at the bottom.

**Comment by cemary** [comment]
The steps outlined in this ticket took care of the issue.
