### ISSUE TITLE
--fixed-cidr=172.17.1.0/24 , but docker0 and container ip‘s  net mask are 255.255.0.0

### ISSUE THREAD

**Issue by xuxilei** [docker/docker#18042]
set  --fixed-cidr=172.17.1.0/24  to start docker daemon
docker0 and container ip‘s  net mask are 255.255.0.0
why not 255.255.255.0

**Comment by phemmer** [comment]
`--fixed-cidr` does not change the interface's network. Thats the purpose of `--bip`. `--fixed-cidr` restricts the address range docker picks IPs from.

**Comment by aboch** [comment]
@xuxilei What you see is the expected behavior as explained by @phemmer

**Comment by mavenugo** [comment]
Closing the issue as this is an expected behavior.
