### ISSUE TITLE
exec start return error code when the container is stopped

### ISSUE THREAD

**Issue by wenchma** [docker/docker#18054]
Description of problem:

I created the exec instance, then stop the container, exec start should return 409 http.StatusConflict,
but not, reproduce steps as follows:

	$ docker ps
	CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
	e86cf50fde54        busybox             "top"                    8 days ago          Up 46 hours                             top1
	$ curl -i -H "Accept: application/json" -H "Content-Type: application/json" -X POST -d '{"AttachStdin":false,"AttachStdout":true,"AttachStderr":true,"Tty":false,"Cmd":["date"]}' --unix-socket /var/run/docker.sock http:/containers/e86cf50fde54/exec HTTP/1.1
	HTTP/1.1 201 Created
	Content-Type: application/json
	Server: Docker/1.9.0 (linux)
	Date: Wed, 18 Nov 2015 05:23:07 GMT
	Content-Length: 74

	{"Id":"0f9ae2a4e7def35f173ca4fc5a6e8223d98a956dbd90d9648d6fa94203645d67"}
	$ docker stop top1
	top1
	$ curl -i -H "Accept: application/json" -H "Content-Type: application/json" -X POST -d '{"Detach":true}' --unix-socket /var/run/docker.sock http:/exec/0f9ae2a4e7def35f173ca4fc5a6e8223d98a956dbd90d9648d6fa94203645d67/start HTTP/1.1
	HTTP/1.1 404 Not Found
	Content-Type: text/plain; charset=utf-8
	Server: Docker/1.9.0 (linux)
	Date: Wed, 18 Nov 2015 05:24:05 GMT
	Content-Length: 105

	No such exec instance '0f9ae2a4e7def35f173ca4fc5a6e8223d98a956dbd90d9648d6fa94203645d67' found in daemon

`docker verison`:

    Client:
	 Version:      1.9.0
	 API version:  1.21
	 Go version:   go1.4.2
	 Git commit:   76d6bc9
	 Built:        Tue Nov  3 17:43:42 UTC 2015
	 OS/Arch:      linux/amd64

	Server:
	 Version:      1.9.0
	 API version:  1.21
	 Go version:   go1.4.2
	 Git commit:   76d6bc9
	 Built:        Tue Nov  3 17:43:42 UTC 2015
	 OS/Arch:      linux/amd64

`docker info`:

    Containers: 13
	Images: 25
	Server Version: 1.9.0
	Storage Driver: aufs
	 Root Dir: /var/lib/docker/aufs
	 Backing Filesystem: extfs
	 Dirs: 51
	 Dirperm1 Supported: false
	Execution Driver: native-0.2
	Logging Driver: json-file
	Kernel Version: 3.13.0-43-generic
	Operating System: Ubuntu 14.04.1 LTS
	CPUs: 4
	Total Memory: 15.67 GiB
	Name: docker
	ID: UT5D:M5ZY:IEXQ:6LCU:YX6J:ZMWM:BLNJ:MTXH:PRHO:ETVF:3FHH:6LC4
	WARNING: No swap limit support

`uname -a`:

    Linux docker 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):OpenStack Cloud instance

**Comment by cpuguy83** [comment]
This is because the exec instance is removed when the container is stopped, if I recall correctly.

**Comment by wenchma** [comment]
@cpuguy83 the removed `exec instance` can be restored ?
as the link http://docs.docker.com/engine/reference/api/docker_remote_api_v1.21/#exec-start
409 - container is stopped or paused, it's not corredt.
"container is stopped" should return 404. right ?

**Comment by cpuguy83** [comment]
You can create an exec instance against a stopped container. I don't know which (if either) is a big here.

**Comment by wenchma** [comment]
@cpuguy83  it will fail to create an exec instance against a stopped container,

    root@fc0c432d625c:/go/src/github.com/docker/docker# docker stop container1
    container1
    root@fc0c432d625c:/go/src/github.com/docker/docker# curl -i -H "Accept: application/json" -H     "Content-Type: application/json" -X POST -d  '{"AttachStdin":false,"AttachStdout":true,"AttachStderr":true,"Tty":false,"Cmd":["date"]}' --unix-socket  /var/run/docker.sock http:/containers/678e786f7f1c/exec HTTP/1.1
    HTTP/1.1 500 Internal Server Error
    Content-Type: text/plain; charset=utf-8
    Server: Docker/1.10.0-dev (linux)
    X-Content-Type-Options: nosniff
    Date: Thu, 19 Nov 2015 02:15:21 GMT
    Content-Length: 38
    
    Container 678e786f7f1c is not running

**Comment by wenchma** [comment]
PR is merged, so close this.
