### ISSUE TITLE
Dockerfile suggestion : AFTERBUILD

### ISSUE THREAD

**Issue by vipconsult** [docker/docker#18063]
Most images have some sort of a final cleanup process or other commands that run on every image.

I think it as a supplement of the ONBUILD command it would be great if we had the AFTERBUILD as well so we could run it on every image the uses the FROM inheritance

for example 

AFTERBUILD RUN apt-get purge -y --auto-remove && rm -rf /var/lib/apt/lists/* && apt-get clean

these would be for commands that would be run only after the final command in the dockerfile

please share your ideas and suggest improvements.

**Comment by MHBauer** [comment]
From my understanding, that wouldn't actually make the final image smaller, right? The files are still embedded in the earlier layers. It would clean up the filesystem from a `looking at it in the current state` perspective, but it would not save space. The `purge` and `rm` would still need to be attached directly to an `RUN apt-get install`.

**Comment by vipconsult** [comment]
Can someone else confirm this ?

Maybe later I can run some tests as well

**Comment by duglin** [comment]
Per https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax I'm going to close this because modifications to the Dockerfile syntax are not allowed, for now.

@MHBauer is correct that this will just shrink how the rootFS will look, not the actual image itself.

**Comment by vipconsult** [comment]
How about some final security enhancements at the end of the build 

as describbed here
https://gallery.mailchimp.com/979c70339150d05eec1531104/files/Docker_Security_Red_Hat.pdf

Remove setuid/setgid Binaries

page 23

**Comment by duglin** [comment]
Yes, you can certainly do those things and from a "final root filesystem" perspective its fine.  All @mhbauer was pointing out is that while the actions you take in this kind of "post build step" might be useful, if you're looking to shrink the side of your image then it won't work.

**Comment by vipconsult** [comment]
that was just one example, 

I think there were few more cases where I needed to do the same task on all images after the build , but I will post back if I remember any worth mentioning

**Comment by duglin** [comment]
@vipconsult yea, and I think something like an AFTERBUILD feature might be interesting, but until the embargo is lifted on new Dockerfile commands we can't even really think about it.
