### ISSUE TITLE
cannot start container through docker remote API

### ISSUE THREAD

**Issue by juniwang** [docker/docker#18066]
Hi guys, I CANNOT start container through docker remote API but I CAN run the same image from commandline.  The error message from [start container API call](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.18/#start-a-container) is `Cannot start container bc88d3e257252f7fcaf69c0ddc008d7b8d8eee2ba3bcb422112ea873d18f23a1: [8] System error: exec: "": executable file not found in $PATH`. I used image [rastasheep/ubuntu-sshd](https://hub.docker.com/r/rastasheep/ubuntu-sshd/) for tests.

Results of `docker ps -a`:
```
CONTAINER ID        IMAGE                    COMMAND                CREATED              STATUS              PORTS                  NAMES
bc88d3e25725        rastasheep/ubuntu-sshd   ""                     About a minute ago   Created                                    38-ubuntu-sshd-3sju8tek
8b33e6649fb8        rastasheep/ubuntu-sshd   "/usr/sbin/sshd -D"    50 minutes ago       Up 50 minutes       0.0.0.0:2222->22/tcp   reverent_lumiere
d7f0fea869e6        rastasheep/ubuntu-sshd   " /usr/sbin/sshd -D"   About an hour ago    Created                                    34-ubuntu-sshd-ljoy27ht
```

- `bc88d3e25725` created through [API](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.18/#create-a-container), **cannot start**. `CMD` was set to `[]` while creating
- `8b33e6649fb8` created in command line `docker run -d -it -p 2222:22 rastasheep/ubuntu-sshd`, **work well**
- `d7f0fea869e6` also created via API, **cannot start**. `CMD` was set to `["/usr/sbin/sshd", "-D"]` while creating

As you can see, `COMMAND` are different. Only the second row runs well which was created from command line `docker run -d -it -p 2222:22 rastasheep/ubuntu-sshd`. While the other two are created through remote API.  The COMMAND of first row is empty. The third row has a extra leading space. Both two fails because of ` [8] System error: exec: "": executable file not found in $PATH`.  Neigher API nor comandline works for the same error.

I used python `requests` to send requests(debug in PyCharm). There are two steps. First a request to create a new container, get the `id` from the response. And second send a request to start the container:

**The first step to create container:**
```
req = requests.post(containers_url, data=json.dumps(container_config), headers={'content-type': 'application/json'})
```
The `containers_url` is `u'http://localhost:4243/containers/create?name=41-ubuntu-sshd-gzu684uj'`

And container_config= ```{'Hostname': u'', 'SecurityOpts': [u''], 'Entrypoint': u'', 'Env': [], 'MacAddress': u'', 'User': u'', u'provider': u'0', 'OpenStdin': True, 'AttachStderr': True, 'AttachStdout': True, 'NetworkDisabled': False, 'WorkingDir': u'', 'StdinOnce': True, 'AttachStdin': False, 'Volumes': {}, 'Tty': True, 'Domainname': u'', 'Image': u'rastasheep/ubuntu-sshd', 'Labels': {}, 'HostConfig': {u'Dns': [], u'Memory': 0, u'DnsSearch': [], u'Privileged': False, u'CpusetCpus': u'', u'CgroupParent': u'', u'RestartPolicy': {u'MaximumRetryCount': 0, u'Name': u''}, u'PublishAllPorts': False, u'ReadonlyRootfs': False, u'CpuShares': 0, u'NetworkMode': u'', u'LxcConf': {}, u'Devices': [], u'VolumesFrom': [], u'Binds': [], u'MemorySwap': 0, u'ExtraHosts': [], u'Ulimits': [], u'CapDrop': [], u'Links': [], u'PortBindings': {u'22/tcp': [{'HostPort': '10022', 'HostIp': ''}]}, u'CapAdd': [], u'LogConfig': {u'Type': u'json-file', u'Config': {}}}, 'ExposedPorts': {u'22/tcp': {}}}```

A better formatted version of `json.dumps(container_config)`:
```
{
  "Hostname":"",
  "SecurityOpts":[
    ""
  ],
  "Entrypoint":"",
  "Env":[
  ],
  "MacAddress":"",
  "User":"",
  "provider":"0",
  "OpenStdin":true,
  "AttachStderr":true,
  "AttachStdout":true,
  "NetworkDisabled":false,
  "WorkingDir":"",
  "StdinOnce":true,
  "AttachStdin":false,
  "Volumes":{
  },
  "Tty":true,
  "Domainname":"",
  "Image":"rastasheep/ubuntu-sshd",
  "Labels":{
  },
  "HostConfig":{
    "Dns":[
    ],
    "Memory":0,
    "DnsSearch":[
    ],
    "Privileged":false,
    "CpusetCpus":"",
    "CgroupParent":"",
    "RestartPolicy":{
      "MaximumRetryCount":0,
      "Name":""
    },
    "PublishAllPorts":false,
    "ReadonlyRootfs":false,
    "CpuShares":0,
    "NetworkMode":"",
    "LxcConf":{
    },
    "Devices":[
    ],
    "VolumesFrom":[
    ],
    "Binds":[
    ],
    "MemorySwap":0,
    "ExtraHosts":[
    ],
    "Ulimits":[
    ],
    "CapDrop":[
    ],
    "Links":[
    ],
    "PortBindings":{
      "22/tcp":[
        {
          "HostPort":"10022",
          "HostIp":""
        }
      ]
    },
    "CapAdd":[
    ],
    "LogConfig":{
      "Type":"json-file",
      "Config":{
      }
    }
  },
  "ExposedPorts":{
    "22/tcp":{
    }
  }
}
```
The request succeeds with code `[201]` and content `'{"Id":"8e075f05c8b549c67ec891855d0d4061aa819e4d76b40e8fa85969e064f0e2ce","Warnings":null}
'`

Code and parameters for **the second step to start the container**. 
```
req = requests.post(url, headers={'content-type': 'application/json'})
```
the `url` is `u'http://localhost:4243/containers/8e075f05c8b549c67ec891855d0d4061aa819e4d76b40e8fa85969e064f0e2ce/start'` where the id got from response of the first step varies every time. This time, the response is `<Response [404]>` and content `'Cannot start container 8e075f05c8b549c67ec891855d0d4061aa819e4d76b40e8fa85969e064f0e2ce: [8] System error: exec: "": executable file not found in $PATH
'`

My docker version:
```
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:40:42 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:40:42 UTC 2015
 OS/Arch:      linux/amd64
```

docker info:
```
Containers: 2
Images: 13
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 17
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-26-generic
Operating System: Ubuntu 15.04
CPUs: 1
Total Memory: 4.812 GiB
Name: junbo
ID: TBBN:ZGN4:LAJW:3ZSJ:K5AM:3ARP:KFBE:QCCO:RC2S:5HZT:DDRH:HRKH
WARNING: No swap limit support
```

uname -a:
```
Linux junbo 3.19.0-26-generic #28-Ubuntu SMP Tue Aug 11 14:16:32 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by cpuguy83** [comment]
Can you please provide your actual API call (like via curl).

The docker client uses the remote API too, so there must be something that's not quite right with the API call you are making.

**Comment by juniwang** [comment]
@cpuguy83 updated my comment

**Comment by cpuguy83** [comment]
@juniwang This looks like it's because you are setting `Entrypoint` to an empty string.
When `Entrypoint` is changed at all, it overrides any value of `Cmd` from the image.
Can you confirm by removing `Entrypoint`?

**Comment by thaJeztah** [comment]
ping @juniwang have you been able to test @cpuguy83's suggestion?

**Comment by juniwang** [comment]
@thaJeztah @cpuguy83  Yes, it succeeds when `EntryPoint` was removed.  

Also I tested using an older version of docker:
```
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.3.3
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.3.3
Git commit (server): a8a31ef
```
I can run the same image successfully with docker 1.5.0 in both cases: **with** or **without** `EntryPoint` who's value is an empty string.   So it the change a reggresion or desired?  We set may default values, in many cases `None` or empty string, for docker options in our programs. Is it better I remove them all?

**Comment by thaJeztah** [comment]
@juniwang yes, I'd suggest to only provide what you actually need. w.r.t changes since 1.5, I don't remember exactly, but I think we did indeed change behavior because otherwise there was no way to distinguish "I want this property to be empty" vs "I didn't specify this property, use the default or don't modify"

**Comment by thaJeztah** [comment]
@juniwang I'm going to close this issue, because I think your question is answered, but feel free to continue the discussion here. :+1:

**Comment by cpuguy83** [comment]
Yes, behavior was changed such that if `Entrypoint` is changed, `CMD` is cleared.
