### ISSUE TITLE
Set additional container hostname for use in /etc/hosts/ in user-defined networks

### ISSUE THREAD

**Issue by delfuego** [docker/docker#18068]
When a container is run connected to a new Docker 1.9 user-defined network (e.g., `docker run --net user-net ...`), the `/etc/hosts` files of all other containers connected to that network are updated with a mapping between the new container's IP address and its hostname. Would it be possible to add some way to set an alias to be used as an additional entry in the `/etc/hosts` file for that new container? The ideal would be to be able to do this in the `docker run` command itself as well as in a `docker-compose.yml` file.

The use case here is when a bunch of containers are managed together with Docker Compose, but expect to find each other at well-known hostnames — e.g., Kibana needs to know what the hostname of Elasticsearch is so that it can connect to it. The preferred method of using Docker Compose is to let it set container names when it starts up new containers... but then these names aren't known until runtime.

So the ideal would be something like: `docker run --net=user-net --hostnamealias=elasticsearch -d elasticsearch:1.6.2`, and then the corresponding language for Docker Compose.

**Comment by cpuguy83** [comment]
Closing as this is really a dup of #17805, and is being tracked in libnetwork here: docker/libnetwork#737

Thanks!

**Comment by delfuego** [comment]
Sorry @cpuguy83 — I searched and searched for dupes, but clearly didn't find that one.

**Comment by cpuguy83** [comment]
Totally, no worries.
GH search is the worst.
