### ISSUE TITLE
docker exec into a stopped container

### ISSUE THREAD

**Issue by vikstrous** [docker/docker#18078]
It looks like `docker run` is an order of magnitude slower than `docker exec`. However, if the container is not running, you can't `exec` in its context and there is no way to re-run it with a different starting command.

We are using `docker run` many times in a Makefile and if we were able to replace it with `docker exec` we would reduce the docker related overhead significantly. The only workaround I can think of is to run a container with `sleep 100000`, use `docker exec` throughout the build, then try to `docker kill` at the end. This is likely to occasionally leave a container running if the build fails to clean up properly, so I would much rather have a way to `exec` into a stopped container or re-start it with a different entrypoint/arguments.

**Comment by vikstrous** [comment]
After further investigation, it looks like starting is the slow part and this wouldn't solve my original problem.

**Comment by duglin** [comment]
Can we close this then?

**Comment by vikstrous** [comment]
I still want to know why you can't simply start a container with a different entry point. Can we add an option to start that lets you do that? Is there any reason not to?

**Comment by MHBauer** [comment]
You could take the container back to an image and then re-`run` or re-`create` it with a different entrypoint. Once a container is created there isn't much you can do to it besides start it as it is.

**Comment by crosbymichael** [comment]
The main reason why is because containers are supposed to be immutable.  You cannot exec into a stopped container because it has be be running first.  Most container starts are in the area of 200ms, no overlay filesystems ( non- devicemapper ) so it would be interesting to see your Makefile and what you are doing to suggest a different way if it is too slow.

**Comment by bmangold** [comment]
Exactly what @MHBauer said:
Commit the stopped container:
`docker commit $STOPPED_CONTAINER user/test_image`

Start/run with a different entry point:
`docker run -ti --entrypoint=sh user/test_image`

**Comment by nyetwurk** [comment]
This fails for me if there are mounted volumes.
```docker: Error response from daemon: cannot mount volume over existing file, file exists /var/lib/docker/overlay2/fd7a61e00fa2670536b28fd20c74ac6e3ccd5c6d4ad3bfb93995cd0d19c95cff/merged/......```

**Comment by Chealer** [comment]
> For me the best solution was this:
> https://github.com/jpetazzo/nsenter/issues/27#issuecomment-386490356

The https://github.com/jpetazzo/nsenter repository is now archived and the above link yields a 404 error.

**Comment by Chealer** [comment]
Thank to @Yajo, this issue is now tracked by ticket #30361.

**Comment by bam80** [comment]
> Commit the stopped container:
`docker commit $STOPPED_CONTAINER user/test_image`

> Start/run with a different entry point:
`docker run -ti --entrypoint=sh user/test_image`

That would create new container without original container's configuration (volumes, etc.).
This solution is more than 6 years old now.
Do we have a better solution?
