### ISSUE TITLE
/etc/udev/rules.d/80-docker.rules with +x?

### ISSUE THREAD

**Issue by aanm** [docker/docker#18071]
I just saw that file `80-docker.rules` have permissions set to 755.
It is supposed to be like that? It's the only rule that I have like that, the other ones are only 644.
```
$ ls -la /etc/udev/rules.d/80-docker.rules
-rwxr-xr-x. 1 root root 343 Nov  3 17:26 /etc/udev/rules.d/80-docker.rules
```

**Comment by vdemeester** [comment]
ping @jfrazelle @tianon
