### ISSUE TITLE
Docker Registry API v2: Deleting images and tags does not work

### ISSUE THREAD

**Issue by eembsen** [docker/docker#18088]
I am using the Docker Registry 2.2.0 (Docker Hub image) as part of a continuous integration/deployment setup. My Jenkins creates a new image on every successful build and pushes it to the private registry. That sums up to an average of say 20 builds/images a day. To keep the registry server nice and tidy I need to do some automatic cleanup of images that never make it to the acceptance environment. I did a lot of experiments this week and have come to the conclusion that the API v2 does not handle deletion of images nor does it handle deletion of tags. This makes the docker registry nearly unusable for me, but I need it badly. To clean up, I have to shutdown the registry and run a housekeeping script. Unfortunately, the tags are still there :-(. I see output like this:

curl --insecure -XDELETE https://localhost.localdomain:5000/v2/be/manifests/ad2dc50509b0855bb91cc898d40c05ceee57491fca08e59612168c4f6a1e8baf
{"errors":[{"code":"UNSUPPORTED","message":"The operation is unsupported."}]}

Anyone who can help me with this? Am I doing something wrong? Why is the "operation unsupported"? 

Here are my coordinates:

`docker version`:

Version:      1.9.0
API version:  1.21
Go version:   go1.4.2
Git commit:   76d6bc9
Built:        Tue Nov  3 17:37:20 UTC 2015
OS/Arch:      linux/amd64

`docker info`:

Containers: 3
Images: 40
Server Version: 1.9.0
Storage Driver: devicemapper
 Pool Name: docker-253:0-2354982-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.821 GB
 Data Space Total: 107.4 GB
 Data Space Available: 11.45 GB
 Metadata Space Used: 4.346 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.143 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.74 (2012-03-06)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.2.69-xnt-nogr-1.5.3
Operating System: Debian GNU/Linux 7 (wheezy)
CPUs: 16
Total Memory: 7.875 GiB
Name: localhost.localdomain
ID: F4IG
WARNING: No memory limit support
WARNING: No swap limit support

`uname -a`:

Linux dev03.xxxxxx.xx 3.2.69-xnt-nogr-1.5.3 #1 SMP Thu May 14 21:03:15 CEST 2015 x86_64 GNU/Linux

**Comment by binhex** [comment]
we are running a similar setup using jenkins and an internal registry and fell foul of this issue, basically they have yet to include the ability to delete images from the registry for v2, even though its shown in the docker registry v2 api documentation, pretty nasty eh!. This caused us to have tp revert back to registry 0.9, as this does include the ability to delete images, awaiting hopeful inclusion of this in docker registry v2.3

see here https://github.com/docker/distribution/issues/422

**Comment by thaJeztah** [comment]
@eembsen can you open this issue on the https://github.com/docker/distribution issue tracker (or look for existing issues)? This is an issue for the registry (distribution) project, and not something that can be solved in this repository.

I'm going to close this issue here for the reason given above, but thanks for reporting :+1:
