### ISSUE TITLE
Failed to verify the CA cert

### ISSUE THREAD

**Issue by goupeng212** [docker/docker#18086]
I found one problem during install docker on ubuntu 14.04 trusty 
1. the server have to set the http_proxy and https_proxy before hand. And then I execute:
> curl -sSL https://get.docker.com/ | sh
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.         

curl --version
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP 

uname -a
Linux 9e1a085b-4f12-4c01-a399-26847f90b113 3.19.0-30-generic #34~14.04.1-Ubuntu SMP Fri Oct 2 22:09:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by thaJeztah** [comment]
could this be an issue with the proxy you're using?

**Comment by patcito** [comment]
I think I have the same problem, using ubuntu 15.10 with docker 1.9.1 but it even happens with curl: 

    curl  https://apt.dockerproject.org/repo/dists/ubuntu-wily/main/binary-amd64/Packages
    curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none


http://pastebin.com/ySVquMZH

**Comment by thaJeztah** [comment]
@patcito are you using a proxy?

**Comment by patcito** [comment]
I'm connected to an open wifi at MS office in Paris, not sure if the wifi itself is using a proxy. However, all other ssl servers I tested with curl did work fine.

**Comment by patcito** [comment]
Tried again with debug if that helps:

$ wget -S -d -O - https://cdn-registry-1.docker.io/cdn-cgi/trace
Setting --output-document (outputdocument) to -
DEBUG output created by Wget 1.16.1 on linux-gnu.

URI encoding = ‘UTF-8’
--2015-11-25 21:51:49--  https://cdn-registry-1.docker.io/cdn-cgi/trace
Resolving cdn-registry-1.docker.io (cdn-registry-1.docker.io)... 52.2.99.166, 54.236.245.47, 54.174.139.205, ...
Caching cdn-registry-1.docker.io => 52.2.99.166 54.236.245.47 54.174.139.205 54.209.180.89 52.5.155.194 54.84.69.173
Connecting to cdn-registry-1.docker.io (cdn-registry-1.docker.io)|52.2.99.166|:443... connected.
Created socket 3.
Releasing 0x00007f12ea20f940 (new refcount 1).
Initiating SSL handshake.
Handshake successful; connected socket 3 to SSL handle 0x00007f12ea20fdb0
certificate:
  subject: CN=*.docker.io,OU=Domain Control Validated - RapidSSL(R),OU=See www.rapidssl.com/resources/cps (c)15,OU=GT98568428
  issuer:  CN=RapidSSL SHA256 CA - G3,O=GeoTrust Inc.,C=US
ERROR: cannot verify cdn-registry-1.docker.io's certificate, issued by ‘CN=RapidSSL SHA256 CA - G3,O=GeoTrust Inc.,C=US’:
  Unable to locally verify the issuer's authority.
To connect to cdn-registry-1.docker.io insecurely, use `--no-check-certificate'.
Closed 3/SSL 0x00007f12ea20fdb0

**Comment by thaJeztah** [comment]
is your ca-certificates package up to date? (Just thinking out loud here), I'll ask around if anyone has other ideas, suggestions.

**Comment by patcito** [comment]
Ok, I fixed this issue by doing the following:

I realized that the file /etc/ca-certificates.conf was empty, but fortunately there was a /etc/ca-certificates.conf.dpkg-old file in there, so I did:

    cd /etc/
    sudo cp ca-certificates.conf.dpkg-old ca-certificates.conf

Then I did:

    sudo update-ca-certificates

Finally I also had to restart docker cause pulling images still wasn't working:

    sudo service docker restart

That did the trick, docker pull works again. Also, to give some context, things broke when updating from ubuntu 15.04 to 15.10, I guess it failed to generate the new /etc/ca-certificates.conf at some point during the upgrade. Hope this helps.

**Comment by thaJeztah** [comment]
Thanks for reporting back @patcito, good to hear it was resolved for you.

**Comment by thaJeztah** [comment]
@goupeng212 are you still having this issue?

**Comment by goupeng212** [comment]
I used an alternative way to walk around. 
1. curl the sciprt and redirect to one shell script:  curl -sSL https://get.docker.com > docker_install.sh
2. replace all https to http for (wget, curl ) :  
    sed -i 's/curl\ \-sSL/curl\ \-sSL \-k/g' docker_install.sh
    sed -i 's/wget\ \-qO\-/wget\ \-qO\-\ \-\-no\-check\-certificate/g' docker_install.sh
    sed -i 's/apt-get\ /apt-get\ \-\-allow\-unauthenticated\ /g' docker_install.sh

**Comment by thaJeztah** [comment]
@goupeng212 I'd discourage doing that, have you tried to update your ca-certificates to make sure your certificates are up to date?

However, I'll close this issue, as it does not look to be an issue we can solve, but an issue with your network setup, or certificates not being up to date. Feel free to continue the discussion though, after I've closed.

**Comment by rajasec** [comment]
With 16.04, the certificate fails.
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
