### ISSUE TITLE
2TB Docker container?

### ISSUE THREAD

**Issue by jbauer180266** [docker/docker#18110]
Dear Sir or Madam,

I'm currently familiarizing myself with Docker and I would like to wrap several database applications into Docker containers the biggest of which is around 2TB in size. I'm confused by the base size that is apparently limited to 100GB ( cmp. https://github.com/docker/docker/pull/14709 and https://github.com/docker/docker/issues/5151 ), so before I waste a couple of hours trying to build this: Is it possible or will I run into problems? And could someone kindly outline or link to how to achieve this? Can I just use a normal ADD in my Dockerfile?

Thanks in advance.

Best wishes,
Joe

**Comment by cpuguy83** [comment]
Yes, it's possible.
My general rule of thumb is, if you are writing data to disk, it should be in a volume(https://docs.docker.com/engine/userguide/dockervolumes/).
Volumes live outside the container FS and don't have any such restrictions.

Also note that the afformentioned 100GB restriction is for the default configuration when using devicemapper as the storage driver.
