### ISSUE TITLE
Devicemapper fails to grow loopback file on a real device with docker 1.9

### ISSUE THREAD

**Issue by julienvey** [docker/docker#18122]
**Description of problem**

I used to do the procedure described [here](https://jpetazzo.github.io/2014/01/29/docker-device-mapper-resize/), section *"We need a faster pool"*, in order to use a real device for devicemapper storage. With the Docker version 1.8.3, this used to work without any trouble.

I recently started creating new instances with docker 1.9.0 and, using the same install procedure, the docker daemon won't start. I tried downgrading docker to 1.8, on the same machine, and it works fine again.

**docker version**

```
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 18:00:05 UTC 2015
 OS/Arch:      linux/amd64
```

**docker info**
Not available because daemon is not started

**uname -a**
```
Linux dockercluster2 3.10.0-229.11.1.el7.x86_64 #1 SMP Thu Aug 6 01:06:18 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Environment details**
GCE Instance using a slightly modified centos7 image to handle correctly resize2fs and some other stuff.
SELinux is disabled
Created with an additional disk at /dev/sdb

**How reproducible**

* Create a machine with an additional disk that will be used as devicemapper storage
* Stop the Docker daemon `systemctl stop docker`
* Wipe out /var/lib/docker `rm -rf /var/lib/docker`
* Create the storage directory `mkdir -p /var/lib/docker/devicemapper/devicemapper`
* Create a data symbolic link in that directory, pointing to the device `ln -s /dev/sdb /var/lib/docker/devicemapper/devicemapper/data`
* Restart Docker `systemctl stop docker`

**Actual Results**

Docker daemon fails with an `invalid argument` error with truncate

The result of `systemctl status docker.service -l`:

```
docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled)
   Active: failed (Result: exit-code) since ven. 2015-11-20 14:27:02 CET; 11min ago
     Docs: https://docs.docker.com
  Process: 17067 ExecStart=/usr/bin/docker daemon -H fd:// (code=exited, status=1/FAILURE)
 Main PID: 17067 (code=exited, status=1/FAILURE)

nov. 20 14:27:02 dockercluster2 systemd[1]: Starting Docker Application Container Engine...
nov. 20 14:27:02 dockercluster2 docker[17067]: time="2015-11-20T14:27:02.735863462+01:00" level=info msg="API listen on /var/run/docker.sock"
nov. 20 14:27:02 dockercluster2 docker[17067]: time="2015-11-20T14:27:02.736612838+01:00" level=error msg="[graphdriver] prior storage driver \"devicemapper\" failed: Unable to grow loopback file /var/lib/docker/devicemapper/devicemapper/data: truncate /var/lib/docker/devicemapper/devicemapper/data: invalid argument"
nov. 20 14:27:02 dockercluster2 docker[17067]: time="2015-11-20T14:27:02.736649451+01:00" level=fatal msg="Error starting daemon: error initializing graphdriver: Unable to grow loopback file /var/lib/docker/devicemapper/devicemapper/data: truncate /var/lib/docker/devicemapper/devicemapper/data: invalid argument"
nov. 20 14:27:02 dockercluster2 systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
nov. 20 14:27:02 dockercluster2 systemd[1]: Failed to start Docker Application Container Engine.
nov. 20 14:27:02 dockercluster2 systemd[1]: Unit docker.service entered failed state.
```

**Expected Results**

The daemon should start and the `Data Space Total` in Docker Info should be the size of the additional device

**Comment by cpuguy83** [comment]
@julienvey 1.9 will attempt to automatically resize.  I imagine there is likely a conflict between the two approaches.

**Comment by thaJeztah** [comment]
I haven't compared the instructions, but we recently added a new section to our documentation, that describes more in depth how to use the various storage drivers; this section describes setting up devicemapper for production; http://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#configure-direct-lvm-mode-for-production

**Comment by chenchun** [comment]
@julienvey I think this is because `ln -s /dev/sdb /var/lib/docker/devicemapper/devicemapper/data` is very tricky. Can you try the way as @thaJeztah 's document describes?

**Comment by polds** [comment]
I had this same error and the suggestion from @thaJeztah resolved my issue.

**Comment by LK4D4** [comment]
I'm closing this issue as it seems inactive. Feel free to open new if the problem persists.
