### ISSUE TITLE
docker v1.9.0 build failed in aarch64 

### ISSUE THREAD

**Issue by jefby** [docker/docker#18121]
Hi,
I use the apm machine(armv8-a), and installed the centos7 system.Now i want to build docker from source code,but it failed, some error like below :
AUTO_GOPATH=1 ./hack/make.sh dynbinary
```
/home/work/go1.5/pkg/tool/linux_arm64/link: running gcc failed: exit status 1 
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
```

go version is go1.5.1 linux/arm64

uname -r
4.1.0-0-rc2.git0.1.el7.aarch64

**Comment by DieterReuter** [comment]
Right now, we don't have an official ARM64 support included in Docker. So you will encounter some strange problems and issues as this isn't tested at all. But please feel free to test it and file PR's as soon as you have some improvements to share.

But we're just working hard to get ARM32 support included first, see #17802. Later on, ARM64 support is already planned, but this will take some time to get finished.

**Comment by crosbymichael** [comment]
Yes, we are still working on arm support right now and have a few more prs open to fix these issues.

**Comment by jefby** [comment]
Hello, i know the reason: because docker compile dynbinary need libpthread.a and libc.a ,and in centos glibc-static rpm package provide these libraries,so i installed this.But i think dynamic build really does not need this, i think it's a docker dynbinary build bug.

```
# _/home/work/docker/dockerinit
/home/work/go1.5/pkg/tool/linux_arm64/link: running gcc failed: exit status 1
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status

[root@localhost docker]# ls /usr/lib64/ | grep pthread
libgpgme-pthread.so.11
libgpgme-pthread.so.11.8.1
libpthread-2.17.so
libpthread_nonshared.a
libpthread.so
libpthread.so.0

```
