### ISSUE TITLE
Better default shortcut for windows "Docker Quickstart Terminal"

### ISSUE THREAD

**Issue by fungos** [docker/docker#18139]
The current terminal uses git-bash.exe to launch the console and run the script start.sh. This console fallbacks to the basic cmd.exe where there are plenty of limitations (like window resizing, copy-paste, scrolling, etc.).

A better alternative would skip the git-bash.exe wrapper shipped with Git for windows and going directly to the alternative console that git for windows uses internally.

This console is called mintty.exe and it is an implementation based on putty to replace cmd.exe. This console fixes all these annoying problems and enables more customization.

The fix is very simple, only need to run this way (the installer should take care of the hard-coded paths obviously):

```
"C:\Program Files\Git\usr\bin\mintty.exe" -i "c:\Program Files\Docker Toolbox\docker-quickstart-terminal.ico" /usr/bin/bash --login -i  "c:\Program Files\Docker Toolbox\start.sh"
```

```
fungos@fungos-w7  ~
$ uname -a
MSYS_NT-6.1 fungos-w7 2.1.0(0.288/5/3) 2015-06-28 18:57 x86_64 Msys

fungos@fungos-w7  ~
$ docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64

fungos@fungos-w7  ~
$ docker info
Containers: 0
Images: 0
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.12-boot2docker
Operating System: Boot2Docker 1.9.0 (TCL 6.4); master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: default
ID: MYTM:OJ3C:ZEUG:TSDR:7DIP:5EM2:C7XR:UYC2:OGV6:6ZHA:WO3F:XUBF
Debug mode (server): true
 File Descriptors: 11
 Goroutines: 18
 System Time: 2015-11-21T03:49:59.701972393Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

fungos@fungos-w7  ~
```

**Comment by MHBauer** [comment]
This should probably go to [toolbox](https://github.com/docker/toolbox).

**Comment by thaJeztah** [comment]
yup, @fungos could you open this issue in the docker toolbox issue tracker? That's the appropriate place for this (sorry for that, we have so many repos, I understand it's hard to find the right one).

Thanks for suggesting, though!

I'll close this issue here

**Comment by fungos** [comment]
Done.

**Comment by thaJeztah** [comment]
Thanks!
