### ISSUE TITLE
Changing variable in entrypoint does not affect `docker exec`

### ISSUE THREAD

**Issue by jakirkham** [docker/docker#18136]
Given the following example files. I can build this as an image like so `docker build --rm -t test .`.

##### Dockerfile

-------------------------------------------------------------------------

    FROM centos:6.6
    ADD entrypoint.sh /entrypoint.sh
    ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]

-------------------------------------------------------------------------

##### entrypoint.sh

-------------------------------------------------------------------------

    #!/bin/bash
    unset VAR
    exec "${@}"

-------------------------------------------------------------------------

If I try to run the following, I find that the variable has been removed as intended.

    $ docker run --rm -it -e VAR=5 test /bin/bash
    [root@<CONTAINER ID> /]# env | grep VAR
    [root@<CONTAINER ID> /]# 

However, if I run this in another terminal, I find the variable still exists.

    $ docker exec -it $(docker ps -lq) /bin/bash
    [root@<CONTAINER ID> /]# env | grep VAR
    VAR=5
    [root@<CONTAINER ID> /]#

I think most people and myself included would not want to see the entrypoint scripts run twice as this might cause serious problems. However, the fact that the same environment isn't shared is a bit interesting. Is there a reason for this? Would it be possible to change it?

**Comment by cpuguy83** [comment]
Vars are per-process.
When you use `docker exec`, it's creating a new process with the same settings the container was created with.
This is expected behavior.
