### ISSUE TITLE
docker build ends with "no space left on device"

### ISSUE THREAD

**Issue by melonista** [docker/docker#18144]
I am using Ubuntu 14.04, docker version 1.9.1.

I had installed an older version with the curl command and now I upgraded it following the instructions in https://github.com/docker/docker/blob/master/docs/installation/ubuntulinux.md. However I did not installed ```linux-image-extra``` because I did not find the one for my kernel version.

I run ```docker build --no-cache=true -t my_debian ./``` and it ends with ```"no space left on device"```.

But this is the output of df -h once the build has failed:

```
root@localhost:~/generate_docker_images/7# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda        24G   12G   12G  49% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
devtmpfs        492M  4.0K  492M   1% /dev
none             99M  200K   99M   1% /run
none            5.0M     0  5.0M   0% /run/lock
none            494M     0  494M   0% /run/shm
none            100M     0  100M   0% /run/user
```

The partially built image:
```
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
<none>              <none>              312407e50337        8 hours ago         2.527 GB
```

I was able to successfully build this image in other computer (this one runs Ubuntu 14.04 with docker 1.9.0 installed via curl):
```
user@computer:~$ docker images
REPOSITORY             TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
my_debian           latest              b68eea4524d6        33 hours ago        4.128 GB
```

So I should have enough disk space. One difference between both computers is that the one that is failing has only 1Gb of memory. Could the "no space left" be caused because there is not enough memory?
```
root@localhost:~# docker info
Containers: 5
Images: 217
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.5-x86_64-linode61
Operating System: Ubuntu 14.04.1 LTS
CPUs: 1
Total Memory: 987.3 MiB
Name: localhost
ID: AKFU:S7UT:D76X:UE74:MN5F:ZXSJ:A7HC:7JPK:W7XQ:35UC:NYNE:VHP6
WARNING: No swap limit support
```

```
root@localhost:~# docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
```
```
root@localhost:~# uname -a
Linux localhost 4.1.5-x86_64-linode61 #7 SMP Mon Aug 24 13:46:31 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Thank you!

**Comment by cpuguy83** [comment]
Not likely a memory issue.
How big is this image all together? Note that the "virtual size" is just the size of that invidual layer, and this really depends on what all you are doing.
Also you should check inode exhaustion `df -i`

**Comment by melonista** [comment]
It seems inode exhaustion is the problem, thanks a lot.

```
root@localhost:~# df -i
Filesystem      Inodes   IUsed  IFree IUse% Mounted on
/dev/xvda      1556480 1554566   1914  100% /
none            126373      13 126360    1% /sys/fs/cgroup
devtmpfs        125906    1381 124525    2% /dev
none            126373     784 125589    1% /run
none            126373       1 126372    1% /run/lock
none            126373       1 126372    1% /run/shm
none            126373       3 126370    1% /run/user
```

**Comment by doronkatz** [comment]
What was the resolution for this

**Comment by AkihiroSuda** [comment]
@doronkatz
https://github.com/docker/docker/issues/18144#issuecomment-158649008

It seems inode exhaustion. So, specifying `-i` to `mkfs` would be the solution. 

Note that in recent versions of Docker, switching the storage driver to overlay2 would be better solution, since overlay2 consumes fewer inodes.
https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/

**Comment by doronkatz** [comment]
Hi, im not sure what you mean. How do I use it actually?

**Comment by AkihiroSuda** [comment]
```console
$ echo '{"storage-driver":"overlay2"}' > /etc/docker/daemon.json 
$ systemctl restart docker
$ docker info
..
Storage Driver: overlay2
...
```

**Comment by ORESoftware** [comment]
@AkihiroSuda that seems like a bad solution - I'd rather not mess with configuration if I can do something temporarily with the command line  - is there a way to give `docker build` more space?

**Comment by AkihiroSuda** [comment]
A crazy solution: 
```
$ qemu-img create -f raw varlibdocker.img 100G
$ mkfs.ext4 varlibdocker.img
$ mount -o loop varlibdocker.img /mnt/dind-varlibdocker
$ docker run -d --name dind --privileged -v /mnt/dind-varlibdocker:/var/lib/docker -v /mnt/dind-varrun:/var/run docker:dind
$ DOCKER_HOST=unix:///mnt/dind-varrun/docker.sock
```
