### ISSUE TITLE
Bash completion error

### ISSUE THREAD

**Issue by luhkevin** [docker/docker#18140]
Hi, 

I installed bash completion via homebrew and installed bash completion for docker via this command: 

curl -XGET https://raw.githubusercontent.com/docker/docker/master/contrib/completion/bash/docker > `brew --prefix`/etc/bash_completion.d/docker

I'm getting this error when I try to tab complete:

    bash: _get_comp_words_by_ref: command not found
    bash: [: 1: unary operator expected
    bash: [: 1: unary operator expected
    bash: [: -eq: unary operator expected

It seems to throw this error no matter what I'm completing: docker rm, ls, run, etc...
The version of bash complete I have installed is 1.3, the version of bash is 'GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)', and as you can see, I'm running OS X, 10.11 Capitan

**Comment by albers** [comment]
@luhkevin `_get_comp_words_by_ref` is a function defined in the _bash completion_ package.
From the error message I guess you do not have this package installed. Please check this.

**Comment by luhkevin** [comment]
Actually, it seems like the issue is my version of bash. 
I'm assuming _get_comp_words_by_ref is actually a shell function? I don't see it defined anywhere in my bash completion files. 

In any case, the bash completion works fine with bash 4.3

**Comment by ain** [comment]
Having the same problem regardless of the Bash version:
```
$ bash --version
GNU bash, version 4.3.42(1)-release (x86_64-apple-darwin15.2.0)
```
Callling for reopening the issue.

**Comment by albers** [comment]
@ain You are either missing the _bash completion_ package or using an outdated version.
_bash_ and _bash completion_ are two separate packages. I can't tell yout the exact package names because I do  not have a mac.

**Comment by ain** [comment]
I missed the specific configuration of Terminal as advised on MacPorts https://trac.macports.org/wiki/howto/bash-completion#Terminal.app

All is running fine now, thanks.

**Comment by albers** [comment]
Thanks for sharing the solution.

**Comment by stevvooe** [comment]
[This](https://github.com/bobthecow/git-flow-completion/wiki/Install-Bash-git-completion]) provides full instructions for installation and getting this working.

Consider re-opening this as a docs issue. cc @thaJeztah @sfsmithcha @SvenDowideit

**Comment by sfsmithcha** [comment]
@stevvooe , edited your comment to fix link
