### ISSUE TITLE
docker systemd service definition on ubuntu isn't configurable

### ISSUE THREAD

**Issue by johnl** [docker/docker#18153]
The old upstart and initscript docker management methods allowed you to configure custom arguments for the daemon in /etc/default/docker

But the new systemd service definition does not honour this config file.

And worse, if I edit /lib/systemd/system/docker.service to change the arguments, the service definition is overwritten the next time the package is upgraded.

In my case, I'm using btrfs so need to add the "-s btrfs" option. Every package upgrade overwrites the service defintion and breaks docker.

I'm not sure of the right way to fix this for systemd, but at minimum it might be a good idea to mark the service definition as a config in the debian/ubuntu package, so it's not automatically overwritten each upgrade.

**Comment by johnl** [comment]
this is with docker-engine package version 1.9.1-0~wily

docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64

Containers: 65
Images: 208
Server Version: 1.9.1
Storage Driver: btrfs
 Build Version: Btrfs v4.0
 Library Version: 101
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.0-16-generic
Operating System: Ubuntu 15.10
CPUs: 4
Total Memory: 7.505 GiB
Name: dogen
ID: G2RV:SXOU:TWY6:WYZA:TRQK:7OM2:W443:Y4P6:4A6P:YET7:U5O5:VOBS
Username: johnl
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

**Comment by vdemeester** [comment]
Hi @johnl,

There is something in the documentation about this : [Control and configure Docker with systemd](https://docs.docker.com/engine/articles/systemd/). It should help :wink:

**Comment by johnl** [comment]
@vdemeester thanks very much for the systemd lesson! My bad then - rather embarrassing, sorry.

I can't think how this might have been best avoided now tbh, so perhaps just leaving it to the docs is enough. Thanks again.

**Comment by philBrown** [comment]
The [Ubuntu - Optional configurations - Configure a DNS server for use by Docker](https://docs.docker.com/engine/installation/ubuntulinux/#configure-a-dns-server-for-use-by-docker) docs seem to indicate that you only need to edit `/etc/default/docker` so which is correct?

**Comment by vdemeester** [comment]
@philBrown this page should be updated in fact ; but all in all it really depends on the version of Ubuntu you are using : if it's a version that does not use systemd (before 15.xx I think) then `/etc/default/docker` is the right place to do the edits ; if it's a version that does use systemd (like 15.10), then options have to be put into a dropin file.
