### ISSUE TITLE
Failed to remove multiple networks with one docker network rm command

### ISSUE THREAD

**Issue by lmesz** [docker/docker#18160]
Hy,

I create multiple bridge network and wanted to remove them with one command but it failed with
"docker: "network rm" requires 1 argument.".
Okay I can workaround it with for example "docker network ls | grep "almafa\|kortefa" | xargs docker network rm", but I think it should work the same way how it works in case of images or containers.

How reproducible:

Steps to reproduce:
1. Run docker daemon
2. Create two default networks: docker network create csillamponi && docker network create unicorn
2. Try to remove them: docker network rm csilamponi unicorn

Actual result:

"docker: "network rm" requires 1 argument"

Expected result:

The daemon removes both of the networks.

`docker version`:

Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

`docker info`:

Containers: 0
Images: 25
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 25
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-30-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 993.7 MiB
Name: lmesz-node1
ID: XNAE:LJE6:MS6U:BPSA:I4LG:5AK6:HNBH:G4A7:2TTI:OSFH:JOOS:QHVY
Debug mode (server): true
 File Descriptors: 18
 Goroutines: 47
 System Time: 2015-11-12T12:26:07.781316158-05:00
 EventsListeners: 0
 Init SHA1: 787da34bb103f11fd6114d8782217bc4f7032e3e
 Init Path: /usr/lib/docker/dockerinit
 Docker Root Dir: /var/lib/docker
WARNING: No swap limit support
Cluster store: etcd://10.121.1.66:2379/dockerNetwork
Cluster advertise: 10.121.1.66:22222

`uname -a`:

Linux lmesz-node1 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):

I guess doesn't matter. But it is a virtualbox virtual machine.

**Comment by thaJeztah** [comment]
Correct, docker 1.9.x does not have this feature, however, 1.10 *will*; A pull request was just merged to implement this, and will be part of 1.10; https://github.com/docker/docker/pull/17489 :smiley: 

Thanks for suggesting, I'm going to close this issue, because this is already resolved and will be in 1.10

**Comment by coolljt0725** [comment]
#17489  fix this
