### ISSUE TITLE
Improve metadata of `/events` API endpoint

### ISSUE THREAD

**Issue by TomasTomecek** [docker/docker#18164]
Follow-up issue after discussion with @calavera and @thaJeztah at dockercon.

At the moment, it's not trivial to see if an event is connected to container, image, volume or network:

```json
{"status":"create","id":"5745704abe9caa5","from":"busybox","time":1442421716,"timeNano":1442421716853979870}
{"status":"delete","id":"7f05242655562b48fec7dc838074d0023db80c69f750cb41ab2544596c015d49","time":1448281959}
```

It would be awesome if the event could contain object type, e.g.:

```
"type": "container"
```

or

```
"type": "volume"
```

I am planning to consume this in TUI for engine I wrote: https://github.com/TomasTomecek/sen

**Comment by thaJeztah** [comment]
Thanks for opening this issue, and it was great meeting you during DockerCon!

**Comment by MHBauer** [comment]
I thought only containers and images had events. Are there new ones for volumes and networks? I don't see anything about it in the documentation (but I am probably looking in the wrong place).

**Comment by thaJeztah** [comment]
@MHBauer don't think there are (yet), but having a "type" field would allow this to be added in future. We briefly discussed this proposal at DockerCon and thought it'd be useful to add some extra information to events in any case.

**Comment by calavera** [comment]
I agree that adding a type element would be good. Adding events to new CRUD operations would also be really helpful. All the network and volume commands should generate events.

**Comment by TomasTomecek** [comment]
Thanks for your feedback. I would love to work on this myself but it's very likely I won't have time in coming days/week(s). I'll update this issue as soon as time lord grants me some free time.
