### ISSUE TITLE
docker network inspect shows only the current node's container in case of overlay driver

### ISSUE THREAD

**Issue by lmesz** [docker/docker#18163]
Description of problem:

So when I create and overlay network driver and create two containers in that network  but on two different node and inspect the created network on one of the nodes I got only those containers which is on the same node on which I executed the inspect command.
It can be said it is expected, but I think in this case I would like to see all the containers in the network for example debugging purposes or else.
I think it is important both containers can ping each other. So it is just I don't know how should I call it just an ouput error, I think I am not sure in that.

`docker version`:

Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

`docker info`:

Containers: 1
Images: 16
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 18
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-30-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 993.7 MiB
Name: lmesz-node2
ID: 5MBM:ZF4N:BDID:M6AW:5R3P:6E5L:43GR:LTLO:BLKM:DFRW:UNVI:F42J
Debug mode (server): true
 File Descriptors: 31
 Goroutines: 71
 System Time: 2015-11-23T13:07:37.273825687+01:00
 EventsListeners: 1
 Init SHA1: 
 Init Path: /usr/bin/docker
 Docker Root Dir: /var/lib/docker
WARNING: No swap limit support
Cluster store: etcd://10.121.1.66:2379/dockerNetwork
Cluster advertise: 10.121.1.60:22222

`uname -a`:

Linux lmesz-node2 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details:
Both node are virtualbox virtual machine

Additional info:

I use etcd for backend.

Reproduction steps:

1. Start two docker daemon on different host. (/usr/bin/docker daemon -D -H unix:///var/run/docker.sock -H tcp://0.0.0.0:5454 --cluster-store=etcd://10.121.1.66:2379/dockerNetwork --cluster-advertise=eth0:2222)
2. Create and overlay network (docker network create -d overlay multi-host)
3. On node one run a simple container with exposed port (docker run -d -p 24240:24240 --net=multi-host --name almafa tutum/hello-world )
4. On node one run a simple container with exposed port (docker run -d -p 24241:24241 --net=multi-host --name kortefa tutum/hello-world )
5. On the node when you created the first container inspect the previously created network driver (docker network inspect multi-host)
6. Check the Containers part:

Actual result:

Result contains only those containers in the network which created on the current node.

Expected result:

inspect contains all the containers which are in the same network

Additional info:

Doh! I forget to mention in case of swarm the result is the same I see only those containers which are created on the node on which I executed the command.

**Comment by mavenugo** [comment]
@lmesz @thaJeztah As of 1.9.x, docker engine manages only those containers that are local to self. Multi-host networking just provides connectivity between containers across hosts and doesn't necessarily means that docker engine manages containers across host. That's Swarm's responsibility & would be an appropriate issue in docker/swarm project.

**Comment by thaJeztah** [comment]
@mavenugo thanks, and yes, I was thinking along that way; @lmesz can you reopen this issue in the https://github.com/docker/swarm repository?

I'll close the issue here

**Comment by lmesz** [comment]
Hm... I think when I say "docker network inspect" I expect to see all the Network related containers. E.g.: what if I check if there is a container belongs to this network if the answer is no I destroy the Network. If without the Network the containers work properly then okay no need to show all the containers else I think it is necessary.
And okay I create in issue in swarm

**Comment by cpuguy83** [comment]
Already exists: docker/swarm#1373

**Comment by darrenlong** [comment]
hello，i have problem ,i only use docker ,etcd, i create overlay is name ovr0 ,i docker run 3 containers on 2 hosts,i Immediately docker network inspect ovr0 ,the inspect contains theses containers,after time, i want to 
inspect ovr0's containers.but no these containers .but 3 conntainers can ping ok. and ,after time,the multi_host contains can not ping ok ,the 1 host's 2 containers can ping ok. why?
