### ISSUE TITLE
--shm-size: inconsistencies

### ISSUE THREAD

**Issue by runcom** [docker/docker#18172]
```
$ docker run -d ubuntu top
09606c3c2e31df6c9c5c67783ef2d950c8ac836d9b734329cb6eddf0eb425b1a
$ docker inspect 096 | grep -i shm
        "ShmSize": 67108864,
```
So far, so good CLI side...
```
$ docker run -d --shm-size="-1" ubuntu top
docker: --shm-size: invalid SHM size.
See 'docker run --help'.
```
`-1` is not even parseable by `units.RAMInBytes` so we get `invalid SHM size.`. This can be good maybe.
```
docker run -d --shm-size=0 ubuntu top
docker: --shm-size: SHM size must be greater than 0 . You specified: 0 .
See 'docker run --help'.
```
With `0`, `RAMInBytes` passes but `0` is not valid. We are hitting https://github.com/docker/docker/blob/master/runconfig/parse.go#L211 and the condition cannot be clearly catch the strictly `< 0` because it's catched by the error in `RAMInBytes` two lines above..

So the CLI applies the default `64MB` only if the flag is not passed. It will error out (with different errors?!) if the value is invalid. 

API side
```
$ curl -X POST -H "Content-Type: application/json" -d '{"Image":"busybox", "Cmd": "mount", "HostConfig":{"ShmSize": -1}}' http://localhost:2375/containers/create
{"Id":"975c16bf9e3fd94eb9afb1f7737f1c78bc90ff4d0939dc7090e5b979d1277923","Warnings":null}
$ docker start -i 975 | grep shm
shm on /dev/shm type tmpfs (rw,seclabel,nosuid,nodev,noexec,relatime,size=65536k)
```
On the API I can pass `-1` and it won't bother about the fact it's invalid so it applies the default `64MB`. Should it error out instead much like on the cli?
Plus:
```
$ docker inspect 7c125 | grep -i shm
        "ShmSize": -1,
```
Inspect shows an shm size of `-1` which seems incorrect..(to me)
Same goes if I provide `0` to the API, inspect will report `0` and `64MB` will be applied (instead of erroring out)

Lastly, if you don't provide an HostConfig at all it will default to `64MB` and report `64MB` in inspect :
```
$ curl -X POST -H "Content-Type: application/json" -d '{"Image":"busybox", "Cmd": "mount"}' http://localhost:2375/containers/create
{"Id":"975c16bf9e3fd94eb9afb1f7737f1c78bc90ff4d0939dc7090e5b979d1277923","Warnings":null}
$ docker start -i 975 | grep shm
shm on /dev/shm type tmpfs (rw,seclabel,nosuid,nodev,noexec,relatime,size=65536k)
$ docker inspect 975 | grep -i shm
        "ShmSize": 67108864,
```
(I'm sure I've even forgot something to report lol, but we'll see)

I think validation should be either the same for cli and API or API side only.. (much like we're currently doing with things in `verifyPlatformContainerSettings`, which will save the overwritten value so inspect is consistent)
ping @LK4D4 @calavera @duglin @cpuguy83  WDYT we should go with this? is the current behavior ok? I'll fix it if we find a common ground and this is not ok.

**Comment by calavera** [comment]
I vote for API side only, but I'm open to check both sides.

**Comment by LK4D4** [comment]
@calavera I agree with API side only.

**Comment by cpuguy83** [comment]
+1 API

**Comment by thaJeztah** [comment]
+1 to API side validations, keep the client thin and don't duplicate validation logic (which can result in getting out of sync)

**Comment by runcom** [comment]
What about what `inspect` should show? I think the issue here lies in the fact we let invalid values to use the default value.
IMO:
- it should not be possible to *fallback* to the default if value provided is invalid, just error out everytime (no fallback) **unless**:
- if no value is provided in the CLI, use the default, and inspect will show the default (64MB)
- if no value is provided in the API (this is tricky), use the default, and inspect will show the default (64MB)
- if no hostConfig is provided (which is a case above), use the default and inspect will show the default

I hope I have covered everything (I'll add integration tests as well since none are present right now)
