### ISSUE TITLE
Filtered list images API doesn't work with registry port

### ISSUE THREAD

**Issue by RickyCook** [docker/docker#18181]
**Description of problem:**
The [list images API](http://docs.docker.com/engine/reference/api/docker_remote_api_v1.21/#list-images) seems to not work when adding the `filter` parameter that includes a registry with a port.

**`docker version`:**
```
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   76d6bc9
 Built:        Tue Nov  3 21:18:00 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64
```

**`docker info`:**
```
Containers: 3
Images: 275
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 291
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.12-boot2docker
Operating System: Boot2Docker 1.9.0 (TCL 6.4); master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015
CPUs: 1
Total Memory: 996.1 MiB
Name: dockci
ID: DAXI:SNXH:NRG3:2ZHQ:KO6R:6BPW:KNLU:QZ74:TRU7:46DS:YRPU:NAMK
Debug mode (server): true
 File Descriptors: 32
 Goroutines: 66
 System Time: 2015-11-23T12:36:51.105258529Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: thatpanda
Registry: https://index.docker.io/v1/
Labels:
 provider=vmwarefusion
```

**`uname -a`:**
```
Darwin Rickys-MacBook-Pro.local 15.0.0 Darwin Kernel Version 15.0.0: Wed Oct 28 11:41:13 PDT 2015; root:xnu-3248.20.42~5/RELEASE_X86_64 x86_64
```
```
Linux dockci 4.1.12-boot2docker #1 SMP Tue Nov 3 06:03:36 UTC 2015 x86_64 GNU/Linux
```

**Environment details (AWS, VirtualBox, physical, etc.):**
Docker Machine with VMWare Fusion provider running on OSX El Capitan

**How reproducible:**
100%, across docker CLI, docker-py, and raw HTTP

**Steps to Reproduce:**
- Dockerfile containing:
```
FROM scratch
ADD Dockerfile /
```

- `docker build -t just-built .`
- `docker tag just-built:latest localhost:5000/just-built:latest`
- `docker images`
```
REPOSITORY                          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
localhost:5000/just-built           latest              a5e832e1966b        13 hours ago        30 B
just-built                          latest              a5e832e1966b        13 hours ago        30 B
[ ... removed more images ... ]
```

- `docker images just-built`
```
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
just-built          latest              a5e832e1966b        13 hours ago        30 B
```

- `docker images 'localhost:5000/just-built'`
```
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
```

_From here on is just more examples_

**Using raw HTTP**

- `http --verify no --cert $DOCKER_CERT_PATH/cert.pem --cert-key $DOCKER_CERT_PATH/key.pem "https://$(docker-machine ip $(docker-machine active)):2376/images/json?filter=just-built"` (where the `http` command is HTTPie)
```
HTTP/1.1 200 OK
Content-Length: 202
Content-Type: application/json
Date: Tue, 24 Nov 2015 01:46:54 GMT
Server: Docker/1.9.0 (linux)

[
    {
        "Created": 1448281661,
        "Id": "a5e832e1966bad9ca5821738ff70f37d737ec79779c98fe36ef477ad603d8c9d",
        "Labels": null,
        "ParentId": "",
        "RepoDigests": [],
        "RepoTags": [
            "just-built:latest"
        ],
        "Size": 30,
        "VirtualSize": 30
    }
]
```
- _no escape_ `http --verify no --cert $DOCKER_CERT_PATH/cert.pem --cert-key $DOCKER_CERT_PATH/key.pem "https://$(docker-machine ip $(docker-machine active)):2376/images/json?filter=localhost:5000/just-built"`
- _: escaped_ `http --verify no --cert $DOCKER_CERT_PATH/cert.pem --cert-key $DOCKER_CERT_PATH/key.pem "https://$(docker-machine ip $(docker-machine active)):2376/images/json?filter=localhost%3A5000/just-built"`
- _: and / escaped_ `http --verify no --cert $DOCKER_CERT_PATH/cert.pem --cert-key $DOCKER_CERT_PATH/key.pem "https://$(docker-machine ip $(docker-machine active)):2376/images/json?filter=localhost%3A5000%2Fjust-built"`
```
HTTP/1.1 200 OK
Content-Length: 3
Content-Type: application/json
Date: Tue, 24 Nov 2015 01:48:08 GMT
Server: Docker/1.9.0 (linux)

[]
```

**Using docker-py**

- `python -c 'import docker; k = docker.utils.kwargs_from_env(); k["tls"].assert_hostname = False; c = docker.Client(**k); import pprint; pprint.pprint(c.images(name="just-built"))'`
```
[{'Created': 1448281661,
  'Id': 'a5e832e1966bad9ca5821738ff70f37d737ec79779c98fe36ef477ad603d8c9d',
  'Labels': None,
  'ParentId': '',
  'RepoDigests': [],
  'RepoTags': ['just-built:latest'],
  'Size': 30,
  'VirtualSize': 30}]
```

- ` python -c 'import docker; k = docker.utils.kwargs_from_env(); k["tls"].assert_hostname = False; c = docker.Client(**k); import pprint; pprint.pprint(c.images(name="localhost:5000/just-built"))'`
```
[]
```

**Actual Results:**
No results returned for `localhost:5000/just-built`, where results returned for `just-built`

**Expected Results:**
Exactly the same results returned for `localhost:5000/just-built`, as results returned for `just-built`

**Comment by mountkin** [comment]
I think it's a bug.
#dibs
