### ISSUE TITLE
Docker 1.7 is unable to pull the RHEL5 image from registry.access.redhat.com

### ISSUE THREAD

**Issue by ashwanisingh28** [docker/docker#18193]
Is RHEL5 or RHEL5.6/5.9/5.11 images are available to pull from docker and what is the path?

**Comment by ashwanisingh28** [comment]
[root@<ServerHostName> chef-repo]# docker version
Client version: 1.7.1
Client API version: 1.19
Package Version (client): docker-1.7.1-115.el7.x86_64
Go version (client): go1.4.2
Git commit (client): 446ad9b/1.7.1
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Package Version (server): docker-1.7.1-115.el7.x86_64
Go version (server): go1.4.2
Git commit (server): 446ad9b/1.7.1
OS/Arch (server): linux/amd64
[root@<ServerHostName> chef-repo]# docker info
Containers: 25
Images: 239
Storage Driver: devicemapper
 Pool Name: docker-253:0-70314800-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 4.944 GB
 Data Space Total: 107.4 GB
 Data Space Available: 12.53 GB
 Metadata Space Used: 11.25 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.136 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.14.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.1 (Maipo)
CPUs: 2
Total Memory: 1.955 GiB
Name: <ServerHostName>
ID: EK7O:QUJQ:BVIU:UNNG:EK7K:DPCI:XRBT:ZDAT:YLPE:DCFY:RQFZ:J3RE
[root@<ServerHostName> chef-repo]# uname -a
Linux <ServerHostName> 3.10.0-229.14.1.el7.x86_64 #1 SMP Tue Aug 25 11:21:22 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

List the steps to reproduce the issue:
The pull is working for rhel 6 but not for rhel5
[root chef-repo]# docker pull rhel6.6
Trying to pull repository registry.access.redhat.com/rhel6.6 ...
f5f0b338bbd6: Download complete 
Status: Image is up to date for registry.access.redhat.com/rhel6.6:latest
[root chef-repo]# docker pull rhel6
Trying to pull repository registry.access.redhat.com/rhel6 ...
05c3d56ba777: Download complete 
Status: Image is up to date for registry.access.redhat.com/rhel6:latest

[root chef-repo]# docker pull rhel5
Trying to pull repository registry.access.redhat.com/rhel5 ... not found
Trying to pull repository docker.io/rhel5 ... not found
Error: image library/rhel5:latest not found

**Comment by thaJeztah** [comment]
RHEL images are only available from RedHat's repository, so this is expected. CentOS and Fedora images are available though on Docker Hub (https://hub.docker.com/r/library/centos/tags/)

**Comment by sgmadurai** [comment]
Is it possible to create docker images for rhel5.x...?  Or is it not supported at all..? Since the redhat registry for containers doesn't list rhel5.x, i tried creating from an iso file i downloaded for rhel5.6. But it doesn't work like one would expect (no /bin/bash or /bin/sh and other stat errors)

Since somewhere its noted that rhel5.x doesn't support docker, i can't create the docker image from a box running this. So i guess the only option is iso image..? or even that won't work..?

**Comment by thaJeztah** [comment]
@sgmadurai I think this page would be a starting point; https://docs.docker.com/engine/articles/baseimages/, together with this script; https://github.com/docker/docker/blob/master/contrib/mkimage-yum.sh

**Comment by thaJeztah** [comment]
@sgmadurai also, there are these ancient CentOS 5 images; https://hub.docker.com/r/tianon/centos/

**Comment by sgmadurai** [comment]
@thaJeztah thanks for checking this, all those pages talk about CentOS (NOT rhel)  versions where we can have docker running.

While this page on RHEL (not CentOS) clearly says Docker is not supported for rhel versions below 7.
https://access.redhat.com/solutions/1378023

I am just looking for some official confirmation (either from redhat or docker community..)  that we can NOT have docker image with rhel5.x (not CentOS) for base image.

@ashwanisingh28 incase you figured a solution for your questions, can you pls post/ share here.

Red Hat Enterprise Linux 6.5 Installation
You will need 64 bit RHEL 6.5 or later, with a RHEL 6 kernel version 2.6.32-431 or higher as this has specific kernel fixes to allow Docker to work.

Docker is available for RHEL6.5 on EPEL. Please note that this package is part of Extra Packages for Enterprise Linux (EPEL), a community effort to create and maintain additional packages for the RHEL distribution.

**Comment by thaJeztah** [comment]
@sgmadurai running docker *on* RHEL/CentOS 5 is something different than running a RHEL/CENTOS 5 *image* on Docker. You should be able to run such image with Docker (basically, those images only contain the user land tools of the distribution; the kernel is shared with the host)

**Comment by sgmadurai** [comment]
@thaJeztah ok, the question was how one can create a docker image for rhel5.x

**Comment by thaJeztah** [comment]
@sgmadurai see my earlier comment; https://github.com/docker/docker/issues/18193#issuecomment-178486536 those are the instructions for making a base image yourself.
