### ISSUE TITLE
Mount device in the container failed

### ISSUE THREAD

**Issue by drngsl** [docker/docker#18191]
Hi, guys!

I create a container with command 
root@ubuntu:/# docker run -it --device /dev/dm-0:/dev/xdm0 ubuntu /bin/bash

and in the container, I can see the block /dev/xdm0, but when I mount it on /mnt, it does not work.

root@fadbf1607992:/dev# mount -t ext3 -o rw /dev/xdm0 /mnt
mount: block device /dev/xdm0 is write-protected, mounting read-only
mount: cannot mount block device /dev/xdm0 read-only

and then, I create another container with adding --cap-add SYS_ADMIN to the cmd
root@ubuntu:/# docker run -it --device /dev/dm-0:/dev/xdm0 --cap-add SYS_ADMIN ubuntu /bin/bash
however, the result is the same.

Here is the information about docker on the host
root@ubuntu:/# docker info
Containers: 14
Images: 61
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 89
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-32-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 16
Total Memory: 47.16 GiB
Name: ubuntu
ID: LZTA:AOAG:2X7V:SPXR:FFUP:VEFO:GIAM:3NCV:ISSG:VZVE:B4SB:KAD6
Username: nkzhangni
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

I'm waiting for you help, thanks a lot!

**Comment by drngsl** [comment]
of course, I can do some mount with --privileged according the guide https://github.com/docker/docker/issues/16429, but in this mode, i can not see the device /dev/xdm0 in the container.

**Comment by cpuguy83** [comment]
Closing as this is a dup of #16429
You can resolve this by using `--security-opt apparmor:unconfined` along with `--cap-add SYS_ADMIN`

**Comment by drngsl** [comment]
thanks for you help, it's really what's i want.
and I'm sorry for this dup.

**Comment by drngsl** [comment]
thanks for you help @cpuguy83 , it's really what's i want.
and I'm sorry for this dup.
