### ISSUE TITLE
Docker 1.9 --build-arg not working

### ISSUE THREAD

**Issue by jas0n1ee** [docker/docker#18205]
My machines lay behind a firewall and I tried to set up a build proxy like this:
```
docker build  \
  --build-arg https_proxy=$HTTP_PROXY --build-arg http_proxy=$HTTP_PROXY 
  --build-arg HTTP_PROXY=$HTTP_PROXY --build-arg HTTPS_PROXY=$HTTP_PROXY -t test .
```
and when I run this command it will first try to pull the ubuntu images, and then failed for network timed out.

I used tcpdump to capture all packages during that and I didn't find any package whose destination is the proxy server ip, so I figured that probably because the proxy settings in the command are not working.

**Comment by duglin** [comment]
Add `RUN env` to your Dockerfile so we can see the list of env vars that are defined.
Are you sure those env vars are defied in the shell in which you're running the docker cli?

**Comment by thaJeztah** [comment]
If I understand correctly, pulling of Ubuntu fails? I don't think that's related to the build args

**Comment by jas0n1ee** [comment]
I may not describe this problem clearly. I have set up the system proxy and it's working(I'm able to download docker installation script and doing all apt-get).  And when I try `docker pull` or `docker build` bases on Ubuntu images, it fails on network connection. Since `docker pull` doesn't has an argument option, I tried `docker build --build-arg` and still doesn't work so I thought it might be the build args' problem. 
Do you what system settings that docker needs when pulling images? I already set `HTTP_PROXY`, `HTTPS_PROXY`, `http_proxy`, `https_proxy`.

**Comment by duglin** [comment]
But are those proxy env vars defined such that the docker daemon uses them?

**Comment by thaJeztah** [comment]
If you're using SystemD, instructions for setting a proxy can be found here; http://docs.docker.com/engine/articles/systemd/#http-proxy

**Comment by jas0n1ee** [comment]
I find the proxy settings in `/etc/default/docker`, it will solve this problem. But I don't find any cli or other system environment setting solution.

**Comment by jas0n1ee** [comment]
Anyway thank you guys! 👍

**Comment by thaJeztah** [comment]
You're welcome! Good luck, and if you have suggestions on improving the documentation around this, feel free to open an issue for that (or even a pull request :heart:)

**Comment by loretoparisi** [comment]
I'm building with `build-arg` like

```
docker build -t $BASE_CONTAINER --build-arg AWS_ACCESS_KEY=xxxxxxxxx --build-arg AWS_SECRET_KEY=xxxxxxxxxxxxx .
```

but the `RUN env` does not report those build arguments at all:

```
NODE_VERSION=5.5.0
HOSTNAME=6b3797ab1e90
HOME=/root
MAVEN_HOME=/usr/share/maven
JAVA_VERSION=8u111
CA_CERTIFICATES_JAVA_VERSION=20140324
JAVA_DEBIAN_VERSION=8u111-b14-2~bpo8+1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LANG=C.UTF-8
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
PWD=/
MAVEN_CONFIG=/root/.m2
```

**Comment by thaJeztah** [comment]
@loretoparisi you need to include `ARG AWS_ACCESS_KEY` in your Dockerfile, otherwise the build args are not used.

**However**, please be aware that build-args should NOT be used for secrets; https://docs.docker.com/engine/reference/builder/#/arg. The build-args will be visible in the image's history, and therefore publicly visible by anyone that has access to the image; here is an example;

```Dockerfile
FROM alpine
ARG AWS_SECRET_KEY
RUN echo "hello world"
```

```
docker build -t secret --build-arg AWS_SECRET_KEY=eba121da975bd368848223e69d303ad14d75a3626cfe4011b45c8e4c68211aaa .
```

```
docker history --no-trunc secret

IMAGE                                                                     CREATED             CREATED BY                                                                                                         SIZE                COMMENT
sha256:f6ad313e9cdd995ab788df3b9f51b9a5eba6c840828120cf0dd7da8e498430a9   4 seconds ago       |1 AWS_SECRET_KEY=eba121da975bd368848223e69d303ad14d75a3626cfe4011b45c8e4c68211aaa /bin/sh -c echo "hello world"   0 B
sha256:9e3010be1b269a431332d5a0d2fe370ab987145dc5aa915d442eaa2130dd610a   46 seconds ago      /bin/sh -c #(nop)  ARG AWS_SECRET_KEY                                                                              0 B
sha256:baa5d63471ead618ff91ddfacf1e2c81bf0612bfeb1daf00eb0843a41fbfade3   8 weeks ago         /bin/sh -c #(nop) ADD file:7afbc23fda8b0b3872623c16af8e3490b2cee951aed14b3794389c2f946cc8c7 in /                   4.8 MB
```

**Comment by loretoparisi** [comment]
@thaJeztah thanks a lot, this should does not affect private images. By the way if this is not safe, and I assume also the template option acts the same way when doing like:

```
sed -e "s,SUBST_AWS_ACCESS_KEY,${AWS_ACCESS_KEY},g;s,SUBST_AWS_SECRET_KEY,${AWS_SECRET_KEY},g" Dockerfile.tpl > Dockerfile.temp
```

as someone is doing, which is a better solution at build time to pass those vars to a script within the `RUN`:

```
RUN myScript.sh $AWS_ACCESS_KEY $AWS_SECRET_KEY
```

Thanks!
