### ISSUE TITLE
Option to make Docker log have real timestamps (or do it by default)

### ISSUE THREAD

**Issue by stevenschlansker** [docker/docker#18200]
The Docker log file is very frustrating to cross reference with other system logs.

Quick!  What time did this error happen at?

```
ESC[31mERROESC[0m[2809574] Handler for GET /images/{name:.*}/json returned error: No such image: mesos-20151014-195414-3878100490-5050-18653-S5.f3db11b8-459c-476a-8520-f8cff385c445 
```

Having an option to produce either an ISO-standard date or some shortened form would make the logs that much more usable.

P.S. The ANSI color codes in the log file are also very annoying.

**Comment by cpuguy83** [comment]
When stdout is not a tty, it is automatically formated like so: `time="2015-11-24T20:37:06.860251202Z" level=debug msg="..."`

**Comment by stevenschlansker** [comment]
Hm.  We use the default Docker installation:

```
root@mesos-slave1-qa-uswest2:~# dpkg-query -s docker-engine
Package: docker-engine
Status: install ok installed
Installed-Size: 27805
Maintainer: Docker <support@docker.com>
Architecture: amd64
Version: 1.8.3-0~trusty
```
running under Upstart, Ubuntu 14.04.3.

How would this tty detection fail?  I assume this is a fairly common setup...

**Comment by cpuguy83** [comment]
https://github.com/Sirupsen/logrus/blob/418b41d23a1bf978c06faea5313ba194650ac088/terminal_notwindows.go#L16-L21

I've seen someone else using upstart have a problem as well... not sure what upstart could be doing differently here.

**Comment by stevenschlansker** [comment]
http://askubuntu.com/questions/579215/upstart-and-issttystdout-fileno

:cry:

**Comment by stevenschlansker** [comment]
Maybe the appropriate fix is a daemon option to override autodetect?  My previous experience with Upstart maintainers is that they consider it an effectively dead project and will not make changes, despite its "Long Term Support" status...

**Comment by LK4D4** [comment]
#19794 fixed this
