### ISSUE TITLE
 Docker update script breaks apt-get update on multiarch debian installs

### ISSUE THREAD

**Issue by martingkelly** [docker/docker#18207]
Hi,

I've noticed an issue on my machine, which is an amd64/armhf multiarch setup (with amd64 as the default architecture). After running Docker install, apt-get update errors out because it can't find armhf packages in the Docker repo. The correct way to fix this is to qualify the repo line in the source.list file with [arch=amd64] or similar, as described in https://wiki.debian.org/Multiarch/HOWTO.

I have written up a patch to fix this and will send a pull request soon.

**Comment by thaJeztah** [comment]
If this is needed, we may need to update the install instructions as well http://docs.docker.com/engine/installation/ubuntulinux/

**Comment by LK4D4** [comment]
Looks like fixed.
