### ISSUE TITLE
Intermittent incomplete /etc/hosts entries with user-defined bridge networking

### ISSUE THREAD

**Issue by am8987578** [docker/docker#18214]
Description of problem:

When starting multiple containers concurrently, the /etc/hosts files are sometimes incompletely populated. This doesn't occur if containers are started sequentially.

This has been reproduced with 1.9.0 and 1.9.1.

`docker version`:
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:
```
Containers: 3
Images: 639
Server Version: 1.9.1
Storage Driver: btrfs
 Build Version: Btrfs v3.16.2
 Library Version: 101
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.20.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 4
Total Memory: 31.26 GiB
```

`uname -a`:
```
Linux cip172 3.10.0-229.20.1.el7.x86_64 #1 SMP Tue Nov 3 19:10:07 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.):

CentOS 7 VM running within VMWare.

How reproducible:

This issue is intermittent, but is readily reproducible using a script such as that shown below.

Steps to Reproduce:

1: Create an image "dnshosts":

`Dockerfile`:
```
FROM buildpack-deps:vivid-scm
MAINTAINER Someone <someone@example.com>

COPY resources/runTest.sh /
CMD ["tail", "-f", "/dev/null"]
```

`resources/runTest.sh` (chmod 755):
```
#!/bin/bash

set -e
for hostname in "$@"
do
  grep $hostname /etc/hosts
done
```

`docker build --tag dnshosts .`

2: Create a network "hosttest":

`docker network create hosttest`

3: Create a test script "checkall.sh"

```
#!/bin/bash

set -e
for server in {1..500}
do
  echo $server
  docker run -d --net hosttest --name hostA-${server} dnshosts &
  docker run -d --net hosttest --name hostB-${server} dnshosts &
  docker run -d --net hosttest --name hostC-${server} dnshosts &
  sleep 2
  docker exec hostA-${server} ./runTest.sh hostB-${server} hostC-${server}
  docker exec hostB-${server} ./runTest.sh hostA-${server} hostC-${server}
  docker exec hostC-${server} ./runTest.sh hostA-${server} hostB-${server}
  docker rm -f hostA-${server}
  docker rm -f hostB-${server}
  docker rm -f hostC-${server}
done
```

4: Run the test script:

`./checkall.sh`

5: The script will either finish successfully after 500 iterations, or will fail and leave the docker containers running:

`docker ps -a |grep dnshosts`

6: Verify that the hosts file is incomplete in at least one image:

```
for cid in `docker ps -q -f "ancestor=dnshosts"`; do echo $cid; docker exec $cid cat /etc/hosts; echo; done
```

Actual Results:

Containers intermittently have /etc/hosts file incompletely populated.

Expected Results:

Containers always have /etc/hosts file fully populated.

Additional info:

**Comment by phemmer** [comment]
Smells like #17190 rearing its ugly head again.

**Comment by mavenugo** [comment]
@am8987578 @phemmer is this seen if the container is NOT started in the background ? (remove the `&` from the `docker run` command) ?
For example, Is there a guarantee that `hostB-${server}` and `hostC-${server}` will be fully up and running before `  docker exec hostA-${server} ./runTest.sh hostB-${server} hostC-${server}` is executed ?
to me `sleep 2` is a poor mechanism to guarantee that. Instead can you confirm it by inspect the container status before executing the `runTest.sh` ?

**Comment by mavenugo** [comment]
@am8987578 btw, PTAL https://github.com/docker/libnetwork/issues/767. We are working on replacing the /etc/hosts mechanism with embedded DNS to solve the issue that @phemmer pointed out.

**Comment by am8987578** [comment]
@mavenugo I cannot reproduce this problem if the ampersand is removed.

Actually, we first saw this when running integration tests orchestrated by the Jenkins Workflow plugin, which allows more-or-less parallel container creation using the "parallel" mechanism (and which assures that the container is fully created before continuing with subsequent steps).

The script shown (and especially the hacky "sleep 2") is just to readily reproduce the problem without all the Jenkins clutter. The sixth step shown above confirms that the hosts file isn't fully populated even several seconds/minutes after container creation.

A change of approach to use embedded DNS rather than /etc/hosts would be very welcome, but I wonder how long this would take to be developed and production-ready.

**Comment by mavenugo** [comment]
@am8987578 thanks. missed step 6 & that confirms an issue I guess. @mrjana resolved any race conditions in updating /etc/hosts across multiple threads of the daemon process. But it seems we still have a condition to be addressed. 
The plan is to get https://github.com/docker/libnetwork/issues/767 for 1.10 release.

@phemmer FYI, this is not #17190 as the race is not between an external process (in the container) manipulating with /etc/hosts while docker daemon is updating it.

**Comment by phemmer** [comment]
@mavenugo #17190 is not about an external process editing the file.

**Comment by mavenugo** [comment]
@phemmer I meant after https://github.com/docker/libnetwork/pull/689 made it to 1.9.0, we should ideally not have this issue unless external process manipulates it.
ping @mrjana.

**Comment by mrjana** [comment]
#docker/libnetwork#777 fixes this issue. This is not related corruption in /etc/hosts file so it not #17190. This test case was exposing a couple of edge cases which are fixed that PR

**Comment by LK4D4** [comment]
Closed by #18486

**Comment by andreychernih** [comment]
I am having the same problem with docker 1.9.1 and a bunch of containers starting at the same time. Eager to see if 1.9.2 fixes this problem. When do you plan to release it?

**Comment by LK4D4** [comment]
@andreychernih we plan to release 1.10 in January
