### ISSUE TITLE
Race condition on API server initialization and connection accept

### ISSUE THREAD

**Issue by crawford** [docker/docker#18212]
When using Docker with socket activation, there is a race condition between the API server initializing and accepting connections. The result is that the first command (e.g. `docker pull ubuntu`) results in `Error response from daemon: 404 page not found`.

It looks like this was broken by 281a48d092fa84500c63b984ad45c59a06f301c4, though the actual reason it fails is because TCP and Unix servers use the listenbuffer, but not the file descriptor (which is used for socket activation). I'm curious why it is desirable to go through the effort of listenbuffers vs just running `ServeAPI()` after `InitRouters()`.

```
$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   4df5e15-dirty
 Built:        Wed Nov 25 01:59:03 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   4df5e15-dirty
 Built:        Wed Nov 25 01:59:03 UTC 2015
 OS/Arch:      linux/amd64
```

```
$ docker info
Containers: 0
Images: 4
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.3.0-coreos
Operating System: CoreOS 870.1.0+2015-11-24-1759
CPUs: 4
Total Memory: 997 MiB
Name: coreos_production_qemu-870-1-0-2
ID: DRMK:OENM:O4XX:FZDB:XLLS:LLQN:RRLT:HH5O:IV5U:DDT6:PSEY:VERU
```

```
$ uname -a
Linux coreos_production_qemu-870-1-0-2 4.3.0-coreos #2 SMP Tue Nov 24 12:17:16 PST 2015 x86_64 Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz GenuineIntel GNU/Linux
```

This can be reproduced every time by doing a Docker pull:

```
$ docker pull ubuntu
Using default tag: latest
Error response from daemon: 404 page not found
```

I would expect:

```
$ docker pull ubuntu
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
c63fb41c2213: Pull complete 
99fcaefe76ef: Pull complete 
5a4526e952f0: Pull complete 
1d073211c498: Pull complete 
```

**Comment by LK4D4** [comment]
@crawford listenbuffer needed to collect requests in infinite queue(in oppose to limited kernel queue) while daemon starting. Daemon start can take pretty long time :/ Maybe we misunderstood how socket activation should work.

**Comment by crawford** [comment]
The listenbuffer doesn't collect requests in an infinite queue.; it just delays the `Accept()`. You are still limited by the socket backlog. That being said, you don't want an infinite queue anyway (nor is it even possible to implement).
