### ISSUE TITLE
User-defined networks cause container socket connections to report the wrong IP address

### ISSUE THREAD

**Issue by mmurdoch** [docker/docker#18224]
Running two containers with `--net=bridge` and executing a netcat server:

    nc -v -l 9000

in the first container and a netcat client in the other:

    nc 172.17.0.2 9000

causes the first container to correctly print:

<pre>
Connection from <b>172.17.0.3</b> port 9000 [tcp/9000] accepted
</pre>

But creating a user-defined network:

    sudo docker network create --driver bridge test

and executing the same commands in containers started with `--net=test` incorrectly prints the IP address of the gateway/user-defined network interface:

<pre>
Connection from <b>172.18.0.1</b> port 9000 [tcp/9000] accepted
</pre>

I would expect this to output:

<pre>
Connection from <b>172.18.0.3</b> port 9000 [tcp/9000] accepted
</pre>

There's a lot of additional information in [this stackoverflow question](http://stackoverflow.com/questions/33860478/why-is-dockerized-hadoop-datanode-registering-with-the-wrong-ip-address).

**`docker version`**

    Client:
      Version:      1.9.1
      API version:  1.21
      Go version:   go1.4.2
      Git commit:   a34a1d5
      Built:        Fri Nov 20 13:12:04 UTC 2015
      OS/Arch:      linux/amd64

    Server:
      Version:      1.9.1
      API version:  1.21
      Go version:   go1.4.2
      Git commit:   a34a1d5
      Built:        Fri Nov 20 13:12:04 UTC 2015
      OS/Arch:      linux/amd64

**`docker info`**

    Containers: 2
    Images: 70
    Server Version: 1.9.1
    Storage Driver: aufs
      Root Dir: /var/lib/docker/aufs
      Backing Filesystem: extfs
      Dirs: 74
      Dirperm1 Supported: true
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 3.19.0-33-generic
    Operating System: Ubuntu 14.04.3 LTS
    CPUs: 4
    Total Memory: 11.73 GiB
    Name: <redacted>
    ID: ZHPN:QYVV:2GHW:JOAP:2ZJN:RCGC:TRHU:ONAE:7ABU:UFSN:U32O:KEFJ
    WARNING: No swap limit support

**`uname -a`**

    Linux <redacted> 3.19.0-33-generic #38~14.04.1-Ubuntu SMP Fri Nov 6 18:17:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by thaJeztah** [comment]
thanks for reporting @mmurdoch 

/cc @aboch @mrjana @mavenugo ptal

**Comment by mavenugo** [comment]
@mmurdoch @thaJeztah this is a dupe of https://github.com/docker/docker/issues/18169 and thanks to @WeiZhang555 we have an open PR (https://github.com/docker/libnetwork/pull/591).

@mmurdoch can you please confirm this by manually cleaning up the iptables rules (in your test environment) and trying it out again ? 

The easiest way to do that is to 

1. remove all the user-created networks using `docker network rm`
2. stop the docker daemon
3. cleanup iptables : `iptables -F && iptables -F -t nat`
4. start the docker daemon
5. create user-defined network
6. try out your use-case.

@WeiZhang555 WDYT ?

**Comment by mmurdoch** [comment]
@mavenugo cleaning up the iptables rules as you describe fixes the problem, thank you!

I'll close this as a duplicate of #18169.
