### ISSUE TITLE
Azure multi-host networking

### ISSUE THREAD

**Issue by jamesmeen** [docker/docker#18229]
Hello

Using Docker 1.9.1 on Ubuntu 15.10.

I'm having trouble getting multi-host networking working with Azure VMs with the default overlay driver.  It works well on hyper-v.

I'm using Docker Machine to create the VMs. This means they each having their own cloud service so do not have direct internal access to each other.  Communication has to be via the public IPs.

I have opened the ports for VXLAN, Service Discovery, Serf, Engine etc on all hosts as per #17709.

I manually update the cluster-advertise IP address to be the Public IP for the Cloud Service because eth0 is an internal IP address so no use.  I have no way of knowing what the public IP address will be when running docker-machine to create the VM. So I have to manually update the value.

When I create an overlay network, run containers and attempt to connect to containers on other host VMs, I get "ping: Destination Host Unreachable" or "telnet: can't connect to remote host (10.0.0.2): No route to host".

Is there something I'm missing to get overlay vxnet working over public IP/port forwards?

Thanks

James

**Comment by mavenugo** [comment]
the IP Address specified in the cluster-advertise option must belong to one of the interfaces in that particular VM/Host. Since you specified that eth0 ip-address is pvt and you are trying to assign the public IP manually, i assume that the public-ip is an externally managed IP that gets NATed in & out to be translated to & from the pvt-ip in eth0. Is that correct ?
If yes, this configuration is not supported. You will have to find a way to have the public-ip assigned to your VM's eth0 and make use of that.

**Comment by jamesmeen** [comment]
Correct. That makes sense.

I don't think there is a way with Azure to assign the public IP as an interface.

I believe docker-machine needs some enhancements to allow multi-host networking to work in Azure with VMs created from docker-machine.  It adds each VM to their own Cloud Service which means they cannot talk to each other directly/internally via the internal IPs assigned to the interfaces.

If docker-machine provided an option for me to specify an existing Cloud Service, then I can add the VMs to a single Cloud Service and they will be able to talk to each other using IP on the interface.

Thanks for the information.  Unless I missed it, it might be good to add this detail to the documentation.

James

**Comment by mavenugo** [comment]
if am not wrong, @abronan @vieux @nathanleclaire @dave-tucker  got this working in Azure as well (in the multi-cloud environment as well). It will be good to know the details.

**Comment by jamesmeen** [comment]
I'm sure I can make it work in Azure if I create the VMs manually myself, but I doubt it with VMs created using docker-machine.  I would love to know the details. Thanks : )

**Comment by jamesmeen** [comment]
Okay, so I've created an Azure Virtual Network and recreated the same VMs connected to this.
Now the VMs both have an interface with an internal IP on the same subnet which means they can talk to each other.  I can ping each host from each other and telnet into the docker engine port too.  So I have set the cluster advertise to this interface and it has picked up the correct IP.

I still have the same problem with container to container communication across the hosts.  Name resolution is working just not connecting.

Thanks

James

**Comment by jamesmeen** [comment]
For some reason after re-deleting the Azure VMs and re-creating them with the same VHD and starting the same containers, the connectivity works.

Nothing has changed in terms of configuration afaik.  I will recreate and keep an eye on it, but for the moment this is resolved.

It just remains for docker-machine to allow creating VMs with an Azure Virtual Network specified or support sharing the same cloud service.

Thanks

James

**Comment by rafabene** [comment]
How was these Azure VMs for Swarm created? Manually, any ARM templates or using docker-machine? Thanks

I can't make it work with docker-machine swarm hosts in Azure

**Comment by jamesmeen** [comment]
@rafabene  I was only the Docker overlay networking functionality with kv store, not swarm.

I understand, the Docker Machine Azure driver is being updated to support new configuration features for Azure VMs and the newer Resource Manager Deployment Model.  See #2742 and #496 and #2408 in the Docker Machine project

**Comment by rafabene** [comment]
Thanks. Linking the right issues: https://github.com/docker/machine/issues/2742 , https://github.com/docker/machine/issues/496 and https://github.com/docker/docker/issues/2408
