### ISSUE TITLE
Newer client version vs API version

### ISSUE THREAD

**Issue by hyingyang** [docker/docker#18248]
I just did apt-get docker-engine on my ubunbu machine, but when I checked the version, I got this 
docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
Error response from daemon: client is newer than server (client API version: 1.21, server API version: 1.19)

**Comment by duglin** [comment]
Is your daemon running on the same machine?  And if so, are you sure you're running the updated version?

**Comment by hyingyang** [comment]
Yes, it's on same machine, and I am trying to setup a private docker registry today and got this error.

**Comment by duglin** [comment]
were you installing docker from scratch or upgrading? If upgrading, did you restart the daemon?
Can you check the daemon logs to see what version it says is running?

**Comment by hyingyang** [comment]
trying to install docker from scratch. where I can find docker daemon log ?

**Comment by HackToday** [comment]
For ubuntu, I think logs are in /var/log/upstart/docker.log

**Comment by calavera** [comment]
I'm closing this as we don't have any more information. Please, feel free to reopen if you have more details to investigate further.
