### ISSUE TITLE
Docker can't be compiled in FreeBSD because of netlink

### ISSUE THREAD

**Issue by miguel250** [docker/docker#18249]
netlink doesn't have support for freebsd so when compiling the docker daemon it fails with `vendor/src/github.com/vishvananda/netlink/netlink.go:14:2: no buildable Go source files in /go/src/github.com/docker/docker/vendor/src/github.com/vishvananda/netlink/nl`. 

https://github.com/docker/docker/blob/master/daemon/daemon_unix.go#L35

`docker version`: master branch

Steps to Reproduce:
1. Clone Docker repository on a FreeBSD box
2. Run `export AUTO_GOPATH=1` follow by `./hack/make.sh binary`

**Comment by miguel250** [comment]
There is also https://github.com/docker/docker/blob/master/daemon/daemon_unix.go#L28 which also needs `netlink`.

https://github.com/docker/libnetwork/blob/master/drivers/bridge/bridge.go#L26

**Comment by LK4D4** [comment]
I think this was fixed by vendoring new version.
