### ISSUE TITLE
Experimental Feedback - user namespaces (userns)

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#18247]
This issue is for collecting feedback on the experimental user namespace (userns) feature, created in https://github.com/docker/docker/pull/12648. Experimental builds can be installed using the instructions found in the ["Docker Experimental Features" section](https://github.com/docker/docker/tree/master/experimental).

> **Note**: that the Experimental builds are not tied to the regular release schedule
> and are built nightly, so it's important to keep your install up-to-date to get the latest
> features and fixes.

Issues related to userns;

- userns: rm: cannot remove '/var/lib/apt/lists/partial': Operation not permitted #18151
- rolling back docker to non-userns docker breaks: https://github.com/docker/docker/issues/18334

**Comment by HackToday** [comment]
@thaJeztah  how to try experimental feature ?(docker 1.9.1 ?)  maybe I should not ask in this thread.

**Comment by thaJeztah** [comment]
@HackToday I added a link to the instructions, thanks for the feedback!

**Comment by HackToday** [comment]
I will try have this experimental test if it worked as designed.  @thaJeztah

**Comment by thaJeztah** [comment]
Cool, thanks @HackToday!
