### ISSUE TITLE
Having multiple NICs (network interfaces) on a Docker image before it boots

### ISSUE THREAD

**Issue by MarkNijhof** [docker/docker#1824]
I have a Docker image with ubuntu:latest and a few other dependencies. The script it starts automatically expects 2 NIC's eth0 (which is there by default) and eth1. Because this second NIC isn't there the script crashes and the container is stopped. So using Pipeworks doesn't work as the container isn't there anymore.

I tried adding this to the Dockerfile:

RUN echo "auto eth1" >> /etc/network/interfaces
RUN echo "iface eth1 inet dhcp" >> /etc/network/interfaces
But that didn't work either.

Is there a proper way to achieve this, or else a hack to begin with :-)

Maybe later having something like "NIC eth1 dhcp" in the Dockerfile would be cool.

-Mark

**Comment by alinz** [comment]
For multiple nics with docker

**Comment by hibooboo2** [comment]
:+1: for multiple nics as well. Something rancher would love to have.

**Comment by xaionaro** [comment]
It's required to use bountysource for this issue, IMHO :)

**Comment by jorgemoralespou** [comment]
:+1: For multiple nics with docker

**Comment by amalagaura** [comment]
This is necessary in a lot of cases because if doing a host network we cannot link to other containers. Sometimes we need to be on the host network and at the same time link to other containers.

**Comment by drbokko** [comment]
:thumbsup: or  +1

**Comment by vijayendrabvs** [comment]
Has this work been completed? Any pointers to how to plumb multiple NICs inside docker containers?

**Comment by cpuguy83** [comment]
@vijayendrabvs close, but not quite yet. #13441
Also this will (probably) never be supported for build time since there would be no need to

**Comment by cpuguy83** [comment]
Closing as #14023 was merged, which provides an API for managing networks and #14051 for discovery

**Comment by tangicolin** [comment]
It is possible to have some tutorial or pointer about how to set this features ? 
I understand that docker network command can create command but i don't understand how to "bind" docker instance to new network (and how to create second NIC).

**Comment by kujiy** [comment]
+1  For multiple nics with docker

I red the docker network docs then thought the same as @tanglicolin.
 
Should we still use jpetazzo/pipework ?

**Comment by mavenugo** [comment]
@tangicolin @kujiy please refer to https://github.com/docker/docker/blob/master/docs/userguide/networking/work-with-networks.md.
one can create multiple networks (using bridge or any other driver) and connect a container to multiple networks. As the container is connected to these networks, it will automatically create the necessary interfaces inside the container. In order to have multiple interface to be available before the container starts, our recommendation is to 

1. create multiple networks using `docker network create` command
2. create a container in a particular network using `--net` : `docker create --net=network1 --name=foo ...`
3. connect the container to other network : `docker network connect network2 foo`
4. start the container `docker start foo`

This will start the container connected to multiple networks with multiple interfaces in the container on each of these networks. Will that satisfy your requirement ?

**Comment by nvachhar** [comment]
I just gave this a try on docker 1.9.1 and it doesn't seem to work. The network connect on the not-yet-running container fails. Here's the error I get:
```
$ docker -v
Docker version 1.9.1, build a34a1d5
$ docker network connect mgmt test
Error response from daemon: Container 159304e33634fe4a555b1fa8cb81690de09f0d7ecf2fe7450fc530c8526baf14 is not running
```

If I launch the container, and then connect, it works fine.
```
$ docker start test
test
$ docker network connect mgmt test
$ docker inspect test | awk '/Networks/,EOF{print}'
        "Networks": {
            "bridge": {
                "EndpointID": "fa80ff1d2aac2b872736df15a77bc913b6718fd9a8ae782730e052bd6e6cde0b",
                "Gateway": "172.17.42.1",
                "IPAddress": "172.17.0.1",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "MacAddress": "02:42:ac:11:00:01"
            },
            "mgmt": {
                "EndpointID": "c5f013d74e8e3f1a057a218d808ae87349ef0aff2980fa11e541eddaa5144375",
                "Gateway": "172.18.0.1",
                "IPAddress": "172.18.0.2",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "MacAddress": "02:42:ac:12:00:02"
            }
        }
    }
}
```

Is there anyway to do the connect before the container is running?

**Comment by kujiy** [comment]
@mavenugo @nvachhar Thank you guys, it seems what I want. I'll try later.

**Comment by thaJeztah** [comment]
@nvachhar see this PR, which is scheduled for docker 1.10; https://github.com/docker/docker/pull/18906
