### ISSUE TITLE
Windows Installation guide not working

### ISSUE THREAD

**Issue by Daxten** [docker/docker#18258]
Hi, I have the latest win 10 build and got some problems following the guide:

Add ssh.exe to your PATH
$Env:Path = "${Env:Path};c:\Program Files (x86)\Git\bin"

should be

$Env:Path = "${Env:Path};c:\Program Files (x86)\Git\bin;C:\Program Files\Git\mingw64\bin"

and the "eval" command isn't working in my PS. I setuped the ENV variables by hand

**Comment by thaJeztah** [comment]
Are you interested in creating a pull request to fix this? The Markdown files to generate the documentation can be found here; https://github.com/docker/docker/blob/master/docs/installation/windows.md#using-docker-from-windows-command-prompt-cmdexe

also;

ping @jeffdm to check, because I don't have access to a Windows machine myself :blush:

**Comment by Daxten** [comment]
Yeah I would do that if someone can confirm it, since it's the first time for me working with docker it might be that I got something wrong

**Comment by thaJeztah** [comment]
@Daxten thanks! I'll see if I can find someone to check the procedure on Windows, perhaps @jhowardmsft when he's back from vacation :heart:

**Comment by pvasek** [comment]
@Daxten Could you check which version of git you have in your `C:\Program Files\Git`? I guess it has to be older version which included `eval` utility. I have git version 2.6 in both locations but don't have `eval` utility there at all.

**Comment by pvasek** [comment]
Found workaround for powershell, but I think the similar approach could be used for cmd.
I run `docker-machine env default` I got the following output:
```
C:\tmp> docker-machine env default
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.102:2376"
export DOCKER_CERT_PATH="C:\Users\me\.docker\machine\machines\default"
export DOCKER_MACHINE_NAME="default"
# Run this command to configure your shell:
# eval "$(c:\Program Files\Docker Toolbox\docker-machine.exe env default)"
```
So I set these variables for my console:
```
C:\tmp> $env:DOCKER_TLS_VERIFY="1"
C:\tmp> $env:DOCKER_HOST="tcp://192.168.99.102:2376"
C:\tmp> $env:DOCKER_CERT_PATH="C:\Users\me\.docker\machine\machines\default"
C:\tmp> $env:DOCKER_MACHINE_NAME="default"
```

**Comment by jhowardmsft** [comment]
Unfortunately I know nothing about toolbox, machine or virtual box. Everything I do is directly Windows native using the engine 'raw'. When I test against Linux, I have a couple of wrapper scripts I've written myself. So I don't think I can help here much.

**Comment by Daxten** [comment]
the workaround I used in PS is
``
$t = docker-machine env default
Invoke-Expression t
``

which most likely is also doable in 1 line, I just don't use ps features so much.. I will take a deeper look later

**Comment by pvasek** [comment]
@Daxten you are right. Actually, it was my mistake that I didn't checked the output from previous command:
` docker-machine env --shell powershell default`
which says what to do next 
```
$Env:DOCKER_TLS_VERIFY = "1"
$Env:DOCKER_HOST = "tcp://192.168.99.100:2376"
$Env:DOCKER_CERT_PATH = "C:\Users\me\.docker\machine\machines\default"
$Env:DOCKER_MACHINE_NAME = "default"
# Run this command to configure your shell:
# c:\Program Files\Docker Toolbox\docker-machine.exe env --shell powershell default | Invoke-Expression
```
When I run `docker-machine env --shell powershell default | Invoke-Expression` console is set up properly.

**Comment by LK4D4** [comment]
@thaJeztah do you think we can close this now?

**Comment by thaJeztah** [comment]
Yes, this can be closed; this part of the docs has changed a lot since this was reported, so looks to be no longer relevant
