### ISSUE TITLE
docker volume rm fails: volume is in use

### ISSUE THREAD

**Issue by gtirloni** [docker/docker#18250]
If a container is created with a volume and then afterwards it's removed without removing the volume in the same operation, it becomes impossible to remove the volume with `docker volume rm`:

    # docker volume rm 8a782a5e19f79a663b4cd808f7bb752368aae27e3e54841ff8438ee9788a675f
    Error response from daemon: Conflict: volume is in use

I'm able to reproduce this scenario every time, even after removing all files from `/var/lib/docker` and restarting the Docker daemon.

Docker was installed from the official RPM packages for CentOS and disabling SELinux does not help.

Standalone volume creation/removal works:

    # docker volume create --name test
    test
    # docker volume ls
    DRIVER              VOLUME NAME
    local               test
    # docker volume rm test
    test
    # docker volume ls
    DRIVER              VOLUME NAME
    #

Removing container and volume simultaneously works:

    # docker run -v /test2 -d centos /bin/bash -c "while true; do ping 8.8.8.8; done"
    f27e78a68430bd467e843aea1e1e9f6e0319c65143009b33302cecd9911d514f
    # docker ps
    CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
    f27e78a68430        centos              "/bin/bash -c 'while "   38 seconds ago      Up 36 seconds                           tiny_blackwell
    # docker stop f27e78a68430
    f27e78a68430
    # docker rm -v f27e78a68430
    f27e78a68430
    # docker volume ls
    DRIVER              VOLUME NAME
    #

Removing container and leaving volume behind results in error when trying to remove the volume later:

    # docker run -v /test3 -d centos /bin/bash -c "while true; do ping 8.8.8.8; done"
    803e8aba798381663712a52f7646d02013e90a457f0d6010281e8dca4876e276
    # docker ps
    CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
    803e8aba7983        centos              "/bin/bash -c 'while "   12 seconds ago      Up 11 seconds                           awesome_hoover
    # docker stop 803e8aba7983
    803e8aba7983
    # docker volume ls
    DRIVER              VOLUME NAME
    local               8a782a5e19f79a663b4cd808f7bb752368aae27e3e54841ff8438ee9788a675f
    # docker volume rm 8a782a5e19f79a663b4cd808f7bb752368aae27e3e54841ff8438ee9788a675f
    Error response from daemon: Conflict: volume is in use
    # docker volume ls
    DRIVER              VOLUME NAME
    local               8a782a5e19f79a663b4cd808f7bb752368aae27e3e54841ff8438ee9788a675f
    # docker volume inspect 8a782a5e19f79a663b4cd808f7bb752368aae27e3e54841ff8438ee9788a675f
    [
        {
            "Name": "8a782a5e19f79a663b4cd808f7bb752368aae27e3e54841ff8438ee9788a675f",
            "Driver": "local",
            "Mountpoint": "/var/lib/docker/volumes/8a782a5e19f79a663b4cd808f7bb752368aae27e3e54841ff8438ee9788a675f/_data"
        }
    ]
    # find /var/lib/docker/volumes/
    /var/lib/docker/volumes/
    /var/lib/docker/volumes/8a782a5e19f79a663b4cd808f7bb752368aae27e3e54841ff8438ee9788a675f
    /var/lib/docker/volumes/8a782a5e19f79a663b4cd808f7bb752368aae27e3e54841ff8438ee9788a675f/_data

Strace output from `docker volume rm`:

    socket(PF_LOCAL, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 6
    setsockopt(6, SOL_SOCKET, SO_BROADCAST, [1], 4) = 0
    connect(6, {sa_family=AF_LOCAL, sun_path="/var/run/docker.sock"}, 23) = 0
    epoll_ctl(5, EPOLL_CTL_ADD, 6, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=369534640, u64=140389965538992}}) = 0
    getsockname(6, {sa_family=AF_LOCAL, NULL}, [2]) = 0
    getpeername(6, {sa_family=AF_LOCAL, sun_path="/var/run/docker.sock"}, [23]) = 0
    read(6, 0xc2084e5000, 4096)             = -1 EAGAIN (Resource temporarily unavailable)
    write(6, "DELETE /v1.21/volumes/8a782a5e19f79a663b4cd808f7bb752368aae27e3e54841ff8438ee9788a675f HTTP/1.1\r\nHost: /var/run/docker.sock\r\nUser-Agent: Docker-Client/1.9.1 (linux)\r\n\r\n", 168) = 168
    epoll_wait(5, {{EPOLLIN|EPOLLOUT, {u32=369534640, u64=140389965538992}}}, 128, 0) = 1
    read(6, "HTTP/1.1 409 Conflict\r\nContent-Type: text/plain; charset=utf-8\r\nServer: Docker/1.9.1 (linux)\r\nDate: Wed, 25 Nov 2015 22:40:04 GMT\r\nContent-Length: 27\r\n\r\nConflict: volume is in use\n", 4096) = 180

Additional system information

    # cat /etc/redhat-release 
    CentOS Linux release 7.1.1503 (Core) 

    # uname -a
    Linux centos-docker-devbox 3.10.0-229.14.1.el7.x86_64 #1 SMP Tue Sep 15 15:05:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

    # getenforce 
    Enforcing

    # docker version
    Client:
     Version:      1.9.1
     API version:  1.21
     Go version:   go1.4.2
     Git commit:   a34a1d5
     Built:        Fri Nov 20 13:25:01 UTC 2015
     OS/Arch:      linux/amd64
    
    Server:
     Version:      1.9.1
     API version:  1.21
     Go version:   go1.4.2
     Git commit:   a34a1d5
     Built:        Fri Nov 20 13:25:01 UTC 2015
     OS/Arch:      linux/amd64
    
    
    # docker info
    Containers: 1
    Images: 5
    Server Version: 1.9.1
    Storage Driver: devicemapper
     Pool Name: docker-253:0-508930-pool
     Pool Blocksize: 65.54 kB
     Base Device Size: 107.4 GB
     Backing Filesystem: xfs
     Data file: /dev/loop0
     Metadata file: /dev/loop1
     Data Space Used: 265.2 MB
     Data Space Total: 107.4 GB
     Data Space Available: 42.39 GB
     Metadata Space Used: 815.1 kB
     Metadata Space Total: 2.147 GB
     Metadata Space Available: 2.147 GB
     Udev Sync Supported: true
     Deferred Removal Enabled: false
     Deferred Deletion Enabled: false
     Deferred Deleted Device Count: 0
     Data loop file: /var/lib/docker/devicemapper/devicemapper/data
     Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
     Library Version: 1.02.93-RHEL7 (2015-01-28)
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 3.10.0-229.14.1.el7.x86_64
    Operating System: CentOS Linux 7 (Core)
    CPUs: 2
    Total Memory: 1.797 GiB
    Name: centos-docker-devbox
    ID: F3YU:D4YI:F4AC:XMK6:2V2K:VJKS:IOYU:YVSX:CZ6V:H3MR:2TVN:QT2Q

    # yum info docker-engine
    Loaded plugins: fastestmirror
    Loading mirror speeds from cached hostfile
     * base: mirror.globo.com
     * epel: mirror.globo.com
     * extras: mirror.globo.com
     * updates: mirror.globo.com
    Installed Packages
    Name        : docker-engine
    Arch        : x86_64
    Version     : 1.9.1
    Release     : 1.el7.centos
    Size        : 36 M
    Repo        : installed
    From repo   : docker
    Summary     : The open-source application container engine
    URL         : https://dockerproject.org
    License     : ASL 2.0

**Comment by thaJeztah** [comment]
Perhaps I'm overlooking, but I see you *stop* the container, but don't actually *remove* it?

```
docker stop 803e8aba7983
803e8aba7983
```

Have you tried `docker rm 803e8aba7983` and then `docker volume rm ...`?

**Comment by gtirloni** [comment]
You're right, I didn't run `docker rm` in the test case I was really worrying about (but I did in the others, go figure). I just tried it again here and it works. every. single. time.

Oh well, sorry about this. More sleep, less coffee I guess. Thanks for catching that mistake.

**Comment by cpuguy83** [comment]
More coffee, we sleep when we're dead! :)

**Comment by thaJeztah** [comment]
Haha, thanks for confirming @gtirloni, and happy to hear it's working correctly. Here's more :coffee:
