### ISSUE TITLE
Are there unneed step in  Dockerfile when build Docker in ubuntu 15.04

### ISSUE THREAD

**Issue by tanguofu** [docker/docker#18254]
It take a very long time to build docker when i am behind a proxy from net.  The most the cost is download or git clone some package, so  could docker can simplify the Dockerfile  ? It is very important for me to develop~

**Comment by thaJeztah** [comment]
I don't think there's much we can optimize here, unfortunately, all those packages are needed. But if you have suggestions, feel free to create a pull request with the changes you think can be made.

Thanks for asking! I'm going to close this issue, but feel free to comment after I've closed, and again, if you have suggestions on how we can improve the Dockerfile, don't hesitate and create a PR :+1:
