### ISSUE TITLE
Docker-in-Docker: unable to delete container

### ISSUE THREAD

**Issue by scf37** [docker/docker#18265]
Description of problem:
When running Docker inside docker container, container cannot be deleted on exit

`docker version`:
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

`docker info`:
Containers: 13
Images: 207
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 233
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-45-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 8
Total Memory: 15.63 GiB
Name: host
ID: EAHP:SVL5:NE5G:76OH:PXYS:KJ2K:5R5W:MAGU:4R2Q:PVPW:E62X:LHFV
WARNING: No swap limit support

`uname -a`:
Linux host 3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):Physical

How reproducible: Always

Steps to Reproduce:
Dockerfile:
```
FROM ubuntu:14.04

# Let's start with some basic stuff.
RUN apt-get update && apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    iptables \
    ssh


RUN curl -sSL https://get.docker.com/ | sh
```

Run docker build -t mydocker .

Then run container, start docker service and exit:
```
user@host:~$ docker run -it --rm -privileged mydocker /bin/bash
Warning: '-privileged' is deprecated, it will be replaced by '--privileged' soon. See usage.
root@160d04d793ef:/# service docker start
 * Starting Docker: docker                                                                                                                                                                                                      [ OK ] 
root@160d04d793ef:/# exit
exit
Error deleting container: Error response from daemon: Driver aufs failed to remove root filesystem 160d04d793efe704af0f6394a5b02c3ea19635c460ffe74760a07b874be2187d: rename /var/lib/docker/aufs/diff/160d04d793efe704af0f6394a5b02c3ea19635c460ffe74760a07b874be2187d /var/lib/docker/aufs/diff/160d04d793efe704af0f6394a5b02c3ea19635c460ffe74760a07b874be2187d-removing: device or resource busy
```

Actual Results:
Error message

Expected Results:
No error message

Additional info:
Will this mess my Docker installation?

**Comment by scf37** [comment]
Why do I need this:

I want to build sshd+docker image so I can test automated deployment using ansible w/o test boxes or VMs

**Comment by hashmap** [comment]
@scf37 does `jpetazzo/dind` image work for you? http://blog.docker.com/2013/09/docker-can-now-run-within-docker/

**Comment by thaJeztah** [comment]
Also note; https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/

**Comment by scf37** [comment]
@thaJeztah thanks for the link. 
It looks like nested Docker configuration is known to be broken and is NOT supported at all.
So this ticket could be considered as feature request and not as a bug

**Comment by thaJeztah** [comment]
@scf37 I think overall, running layered filesystems on top of layered filesystems is problematic; I don't think we'll ever be able to support that reliably. Using a volume for `/var/lib/docker` can be a solution for those cases (i.e. `-v /var/lib/docker`). Having said that, running docker-in-docker may be low on the priority list :innocent:

**Comment by PMarkovski** [comment]
@scf37 make sure you run the second docker as pid 1 in the container. By this, the second docker will receive correct SIGTERM signnal and will stop correctly. When its stopped correctly it will not hang up the aufs folder of the container.

**Comment by unclejack** [comment]
Running Docker in Docker requires proper configuration of the graph drivers. This is a setup which is for more advanced users as it's not that easy to debug.

This isn't a Docker bug. It really seems to be an issue with how the graph drivers are being set up for docker in docker.

I'm going to close this issue now as there's no need to keep the issue open and the discussion can continue. Please feel free to comment.
