### ISSUE TITLE
Cannot build from branch with invalid chars anymore 

### ISSUE THREAD

**Issue by runcom** [docker/docker#18268]
I think this is wanted (I'm sure before the Content Addressable PR I could do this, not sure if that was the pr which broke this though) but we can try to sanitize the branch name in the make process so I don't rename my branch back and forth just to make.
```
runcom @ fedora ~/koding/docker ‹pr/upstream/17021› » make                                                       2 ↵
docker build -t "docker-dev:pr/upstream/17021" -f Dockerfile .
invalid value "docker-dev:pr/upstream/17021" for flag -t: invalid reference format
See 'docker build --help'.
Makefile:71: recipe for target 'build' failed
make: *** [build] Error 125
```
ping @aaronlehmann @tonistiigi @jfrazelle @tianon

**Comment by thaJeztah** [comment]
:+1: sounds good to me :-)

**Comment by runcom** [comment]
fail regexp is this https://github.com/docker/distribution/blob/8aec18217a67fc34a905380c40123aff87aebb98/reference/regexp.go#L45

**Comment by thaJeztah** [comment]
I think that replacing any non a-zA-Z0-9 with `-` and using that for tag-name could work?

**Comment by aaronlehmann** [comment]
Yes, this is part of the content addressability PR. It changes the validation logic for tags to be more consistent. Previously, the validation was lax, and it was possible to create tags that could not be pushed because they contained invalid characters.

cc @dmcgowan
