### ISSUE TITLE
Using monochrome icon?

### ISSUE THREAD

**Issue by FezVrasta** [docker/docker#18264]
Hello,

I'd like to know if is it allowed in a commercial product to use a monochrome version (for example https://github.com/wesbos/Font-Awesome-Docker-Icon) to refer to Docker.

I'm asking this because I need to use this icon in a narrow space (about 20x20px) and the original icon when scaled down looks blurred, and, in your documentation, you ask developers to use the original icon with even the "Docker" text below it.

Thanks.

**Comment by thaJeztah** [comment]
@FezVrasta good question, the guidelines for using the Docker trademarks are described on this page; https://www.docker.com/brand-guidelines, but I can try to find the right person to ask for details

**Comment by FezVrasta** [comment]
@thaJeztah thanks I was referring to them when I've mentioned the documentation.

It would be awesome if you could help me getting a response about my question, thanks!

**Comment by thaJeztah** [comment]
@FezVrasta I've posted the question on the internal slack channel, but due to thanksgiving in the united states, there may be some delay in getting an answer.

Thanks for reaching out though! And feel free to "ping" me here if you haven't heard back next week, then I'll try to ask again :+1:

**Comment by thaJeztah** [comment]
The FontAwesome icon is pretty cool though, didn't know someone created one :smile:

**Comment by FezVrasta** [comment]
Thank you! I see I'm not the only one working during thanksgiving :stuck_out_tongue: 

Will wait for a reply then, thanks!

**Comment by thaJeztah** [comment]
Apparently we're not the only one. I got a reply and, unfortunately, it's not allowed to use altered versions of the logo, only the logo's officially provided. Sorry for that!

I'll /cc @bettyjunod to check if there are plans to offer more variations of the trademarks for public use

**Comment by FezVrasta** [comment]
Thanks for the reply!

It would be great to have a monochrome version for special uses, I've noticed that you use a monochrome version as well on bottom of your website. So I guess that even your designer needed such kind of icon :sweat_smile: 

![image](https://cloud.githubusercontent.com/assets/5382443/11427291/123e6daa-9462-11e5-826b-300075bd01cd.png)

**Comment by thaJeztah** [comment]
Yes, I was just discussing it with some designers and, although some monochrome logo's exist, they're currently only allowed to be used by Docker itself, perhaps that will change in future, but unfortunately, that's out of my hands

**Comment by FezVrasta** [comment]
Just to be sure, can I use the original icon without the text below it?

I mean, just this part:
![image](https://cloud.githubusercontent.com/assets/5382443/11431002/82274e20-948f-11e5-9a8c-1c8960454aa9.png)

Without:
![image](https://cloud.githubusercontent.com/assets/5382443/11431007/935cf73a-948f-11e5-8a95-9f80e6f10b16.png)

**Comment by thaJeztah** [comment]
I think that's considered modifying the logo, so my best guess would be that it's not allowed. I fully understand your situation here (I feel the pain), but it's something that needs to be decided on, and that may take time.

t.b.h. This really isn't my area, and I don't know if exceptions are made to the guidelines, but feel free to contact me at sebastiaan [at] docker with some more information (perhaps a description of the product and a mockup of the way the logo will be used), then I can try to get it to the right people. No promises, just trying to see if there's a way to get this solved.

**Comment by FezVrasta** [comment]
Ok I'll send you an email after the thanksgiving/blackfriday/weekend! Thanks for the availability.

**Comment by thaJeztah** [comment]
You're welcome! Enjoy your weekend!

**Comment by thaJeztah** [comment]
I'll close this issue, because it's not really a Docker bug and to keep our issue tracker "clean", but feel free to continue the discussion here

**Comment by wesbos** [comment]
So I just got an email from your Lawyers. Any update on how to properly use the docker icon when it's so small? 

![](http://wes.io/e1a0/content)

**Comment by manojlds** [comment]
+1 to @wesbos

**Comment by egberts** [comment]
#headdesk

**Comment by jamescun** [comment]
Wow @wesbos. For a company that highly values open source, I think this is a pretty poor show from Docker Inc. I hope to hear that the lawyers are working on behalf of Docker Inc for brand protection services, than at the direction of Docker Inc.

**Comment by wesbos** [comment]
Yeah Lawyers gonna lawyer :)  I don't think the folks behind the software mean any harm.

They have got in touch and we will figure something out.  I think it it all boils down to this: Docker needs to make a single colour SVG of their logo available for when users need a docker icon or to display the docker logo at a small size. 

Also note how many people ask asking for this here:

https://github.com/FortAwesome/Font-Awesome/issues/3316

**Comment by leommoore** [comment]
It gives a poor impression of Docker Inc's values.

**Comment by stevegraham** [comment]
@jamescun this is a function of trademark law. If Docker doesn't proactively protect their mark, they lose it.

**Comment by jamescun** [comment]
@stevegraham "actively protect" does not mean direct to lawyers. Lawyers are for dispute resolution in the case of failure to resolve.

**Comment by thedrow** [comment]
At least they are being kind instead of bringing the usual "I'll sue your ass" attitude.
Still, what's up with that?

**Comment by mgenereu** [comment]
The lawyers don't check with the company first.  They just pursue in automatic mode.

**Comment by demarant** [comment]
nobody can forbid the use of a :whale: as an icon, it is created by nature evolution and does not belong to any company ;)
so, for the time being, until docker inc makes his mind on this silly issue (if they will ever do), imo if we just use a monochromatic whale the same way as it is done by docker, without the text "docker" i think that would work just fine for [FontAwesome](https://github.com/FortAwesome/Font-Awesome/issues/3316) @wesbos just call it ```fa-whale``` and make it look like a whale only :)

**Comment by davegandy** [comment]
@thaJeztah Docker is a fantastic tool I use all the time. I'd love to add the icon to core Font Awesome, but the lack of a version that works at small sizes will keep it from happening. And I'll admit, your legal team makes me a bit wary.

[FYI, you're breaking your own brand guidelines on that very [brand guidelines page](https://www.docker.com/brand-guidelines). Down in the footer, there's a nice simple version of the logo. And it looks great. Simple, identifiable. Iconic, if you will. :smile: Also, it's being misused in a different way on the [Docker Hub](https://hub.docker.com).]

**Comment by wesbos** [comment]
@davegandy I've got signoff from Docker's legal team that makes this  kosher: 

https://github.com/wesbos/Font-Awesome-Docker-Icon

**Comment by davegandy** [comment]
@wesbos That's the full version of the logo, correct? Is there a smaller, approved version?

**Comment by wesbos** [comment]
The version I've got on Github is slightly modified so it works well at
small sizes as far as I remember - I made it 2+ years ago.

*Wes Bos *
*━━━━━━━*
wesbos.com
Skype: wes.bos
Phone: 416 833 3641
Twitter: @wesbos <http://twitter.com/wesbos>

**Comment by davegandy** [comment]
@wesbos Oh, interesting. I didn't realize there wasn't already a plain black and white logo. Hopefully there's a simpler version that can be used. :smile:

**Comment by FezVrasta** [comment]
So now it can be used without problems?

**Comment by wesbos** [comment]
yep

**Comment by davegandy** [comment]
Found another logo variation while installing Docker Toolbox:
<img width="151" alt="screenshot 2016-04-12 12 40 54" src="https://cloud.githubusercontent.com/assets/1076721/14468029/0171054e-00ac-11e6-8616-83e9b8b04fc7.png">

Looks like that logo's getting used in a couple of places. Here's hoping it becomes an approved, single color simplification. :smile:

**Comment by thaJeztah** [comment]
@wesbos oh, that's great news! Happy to hear it got sorted out in the end :tada: 

@davegandy yes, there are some variations on the logo; I asked about that when this issue was opened, and it basically comes down to Docker, Inc, itself (being the trademark owner), is allowed to use the trademarks in any form; even if others are not allowed to do so (without permission). I guess that's fair.

**Comment by davegandy** [comment]
@thaJeztah Yep. Absolutely fair. We'll just skip adding it to Font Awesome in the meantime. :)

**Comment by davegandy** [comment]
Just as a heads up, it appears that https://www.docker.com/brand-guidelines has been updated. There's an excellent simplified logo that looks great.

**Comment by thaJeztah** [comment]
Ah, yes; I _do_ see that there's a requirement to keep the `docker` name in the logo, so looks like it's still not allowed (well, without written permission I guess) to use _just_ the Whale icon

<img width="471" alt="screen shot 2017-07-13 at 13 48 26" src="https://user-images.githubusercontent.com/1804568/28187037-1dad2808-67d2-11e7-95b3-a606c4dd039f.png">

**Comment by andradei** [comment]
Too bad one can't even change the plain logo's color to white or black so it matches the hundreds of other logos legally provided for icon/footer use.

**Comment by thaJeztah** [comment]
@andradei sorry for that, I understand it's frustrating; also not something I can influence. There's a section that mentions exceptions - could be worth reaching out;

<img width="920" alt="screen shot 2017-07-13 at 21 48 29" src="https://user-images.githubusercontent.com/1804568/28198725-2a6d8040-6815-11e7-89cc-f86f1b9fd03e.png">

**Comment by andradei** [comment]
@thaJeztah Thank you for pointing that out. The best solution would be for Docker to add some of those logos to the package they provide. But I understand they wouldn't add the black and white versions because of the risk of those being used more than the ones they already provide.

I'll send the email with the artwork.
