### ISSUE TITLE
docker pull fails with image not found although authentication failed

### ISSUE THREAD

**Issue by sslavic** [docker/docker#18263]
docker pull can give a misleading error, that image is not found, even though root cause is that authentication failed (no credentials provided or invalid credentials were used). Please fix it to report more appropriate error message.

**Comment by thaJeztah** [comment]
Hi @sslavic, thanks for reporting, but I think this is a duplicate of https://github.com/docker/docker/issues/17721 and I think this is better discussed in the "distribution" repository as explained https://github.com/docker/docker/issues/17721#issuecomment-159933438

**Comment by sslavic** [comment]
Closing, duplicate
