### ISSUE TITLE
Remote API `/version` request `BuildTime` field weird date format

### ISSUE THREAD

**Issue by zoechi** [docker/docker#18276]
I'm maintaining the remote API client for Dart and wonder why there are different date/time formats used.
I have a `parseDate()` function where I parse a format like 
- `'0001-01-01T00:00:00Z'` (near ISO 8601 but not quite)
- milliseconds since epoche

and now in Docker 1.9 I again encounter a new format in the `/version` response `BuildTime` field `'Fri Nov 20 17:56:04 UTC 2015'` which I find expecially cumbersome to parse.

Please stick at least to the former two or switch everything to ISO 8601 or some other proper format.

**Comment by thaJeztah** [comment]
I agree, we should try to stick to a single formats for date-fields in the API where possible. I think we use RFC3339 format (not ISO8601) for the dates. I actually think BuildTime is passed on from the shell during build, but I'm not sure here

@vdemeester I think you made the last changes there implementing the "dockerversion" package?

**Comment by WeiZhang555** [comment]
+1 on single format.
Maybe we can stick to one single format for all API, but show it in a more friendly way when user execute `docker version`.

**Comment by thaJeztah** [comment]
@WeiZhang555 yes, I think that's how it should be; API should return a standardized format, the software "consuming" the API (the docker client in your example) should be responsible for formatting it for presentation.

**Comment by WeiZhang555** [comment]
I just made a reference PR for doing this in case this issue is accepted, also feel free to close my PR if you feel something is nonrational... :smile:

**Comment by vdemeester** [comment]
@thaJeztah true, it is passed at build time but the changes on `dockerversion` should not be in 1.9 I think :stuck_out_tongue_closed_eyes:. Anyway I do agree, thanks @WeiZhang555 for the PR :wink:
