### ISSUE TITLE
Allow access to container from Dynamic IP, but blocked everywhere else

### ISSUE THREAD

**Issue by JoyceBabu** [docker/docker#18278]
I am having a dynamic IP connection. I have configured CSF (Config Server Firewall) on my server to block all requests except those coming from a few whitelisted IPs (including my dynamic IP, auto updated using Dynamic DNS). For all services installed directly on the host machine, this is working as expected. But services on docker containers and open to everyone. I found documentation for whitelisting services by IP. How can I make this work with dynamic ip?

**Comment by JoyceBabu** [comment]
It was a configuration issue, Sorry.

**Comment by thaJeztah** [comment]
No problem! Thanks for reporting back :+1:

**Comment by JoyceBabu** [comment]
It was not a configuration issue. I have solved it by writing a script to automatically update iptables, whenever my ipaddress is updated.

The script and procedure for setting it up is available at
http://www.joycebabu.com/blog/limiting-access-to-docker-containers-to-dynamic-ips.html

It is working for me. But I would really appreciate if someone with better knowledge of iptables would check it and confirm if it is okay.

**Comment by LK4D4** [comment]
I'm closing it as views on docker networking changed since reporting. Feel free to open new.
