### ISSUE TITLE
[Docker Engine]: User defined number of GoThreads

### ISSUE THREAD

**Issue by MarcoLotz** [docker/docker#18275]
Currently GoLang limits the number of GoThreads to 10k. From what I have measured so far, each container consumes between 3 and 4 GoThreads. For pools of several thousands of containers per host, this is a problem. It limits the number of containers to about 3k.

There are two possibilities:
1) Change the number of GoThreads on your Go Runtime and recompile it - which is a bad option since docker uses GoLang straight from google repository. Changing this would need every user with this need to recompile Docker and create a make flag for it/ or will increase for every user without need. 
2) Add support for that on Docker Daemon (e.g. create a launch option that increases the OsThreads by calling debug.SetMaxThreads([user defined threads]) - I assume that this is the preferred option.

**Comment by MarcoLotz** [comment]
I just have recompiled my docker daemon to solve it, so the information requested above would not be congruent with what produces the problem. I am running ubuntu 14.04.3 LTS, 4 TiB of RAM, 80 cores, docker server and client 1.9.1

You can reproduce this trying to spin 10k containers. It will fail between 3.5k and 2.5k. Any vanilla release docker-engine will have this problem. I suggest to try on 1.9.1

The logs it produce on /var/log/upstart/docker are the following:

runtime: program exceeds 10000-thread limit
fatal error: thread exhaustion

runtime stack:
runtime.throw(0x1cc0901)
        /usr/local/go/src/runtime/panic.go:491 +0xad
checkmcount()
        /usr/local/go/src/runtime/proc.c:185 +0x60
mcommoninit(0xc24d2b0380)
        /usr/local/go/src/runtime/proc.c:200 +0xbb
runtime.allocm(0xc208010000, 0xc208000360)
        /usr/local/go/src/runtime/proc.c:901 +0x72
newm(0x4d04e0, 0xc208010000)
        /usr/local/go/src/runtime/proc.c:1142 +0x28
startm(0xc208010000, 0x100000001)
        /usr/local/go/src/runtime/proc.c:1220 +0xd0
handoffp(0xc208010000)
        /usr/local/go/src/runtime/proc.c:1245 +0x1e6
retake(0xe3a3da29d8e, 0x0)
        /usr/local/go/src/runtime/proc.c:3007 +0x142
sysmon()
        /usr/local/go/src/runtime/proc.c:2930 +0x20c
mstart()
        /usr/local/go/src/runtime/proc.c:859 +0xe1
runtime.mstart()
        /usr/local/go/src/runtime/proc.c:836 +0xa4

goroutine 1 [chan receive, 217 minutes]:
main.(*DaemonCli).CmdDaemon(0xc2084fd260, 0xc20800a020, 0x9, 0x9, 0x0, 0x0)
        /usr/src/docker/docker/daemon.go:308 +0x20a7
reflect.callMethod(0xc2084ddfb0, 0xc2088fbce8)
        /usr/local/go/src/reflect/value.go:605 +0x179
reflect.methodValueCall(0xc20800a020, 0x9, 0x9, 0x1, 0xc2084ddfb0, 0x0, 0x0, 0xc2084ddfb0, 0x0, 0x4e207f, ...)
        /usr/local/go/src/reflect/asm_amd64.s:29 +0x36
github.com/docker/docker/cli.(*Cli).Run(0xc2084ddef0, 0xc20800a010, 0xa, 0xa, 0x0, 0x0)
        /usr/src/docker/.gopath/src/github.com/docker/docker/cli/cli.go:89 +0x38e
main.main()
        /usr/src/docker/docker/docker.go:65 +0x418

goroutine 5 [syscall, 218 minutes]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, 218 minutes, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 11 [IO wait, 217 minutes]:
net.(*pollDesc).Wait(0xc208084f40, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208084f40, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208084ee0, 0x0, 0x7f5297355500, 0xc20869b300)
        /usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc2080363f8, 0xc208040638, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc2080363f8, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:244 +0x4c
github.com/docker/docker/pkg/listenbuffer.(*defaultListener).Accept(0xc2085121e0, 0x0, 0x0, 0x0, 0x0)
        /usr/src/docker/.gopath/src/github.com/docker/docker/pkg/listenbuffer/buffer.go:71 +0x67
github.com/docker/docker/pkg/listenbuffer.(*defaultListener).Accept(0xc2085121e0, 0x0, 0x0, 0x0, 0x0)
        /usr/src/docker/.gopath/src/github.com/docker/docker/pkg/listenbuffer/buffer.go:75 +0xcf
net/http.(*Server).Serve(0xc2080407e0, 0x7f52943e4620, 0xc2085121e0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1728 +0x92
github.com/docker/docker/api/server.(*HTTPServer).Serve(0xc2085122c0, 0x0, 0x0)
        /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:113 +0x4d
github.com/docker/docker/api/server.func·006(0xc2085122c0)
        /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:86 +0x163

**Comment by luxas** [comment]
What a machine! 
80 cores and 4 TiB of RAM!

Glad you at least got it working, although it would be great with default support for more than 2-3k containers.
I am running kubernetes on the Pi [link](https://github.com/luxas/kubernetes-on-arm), so we play in somewhat different leagues :smile:
But people has been hitting the 10k goroutine limit on the Pi also.

**Comment by thaJeztah** [comment]
up until recently we actually compiled the Go runtime instead of downloading binaries, so if it's the *best* solution, I think that could be considered.

Thanks for looking into this! Much appreciated

/cc @jeremyeder @unclejack @LK4D4, who may be interested in this :+1:

**Comment by MarcoLotz** [comment]
Good to know! Should you decide to return golang compiling, you just need to modify proc.go (proc1.go on 1.5 or higher). There's a line there setting the maximum threads to 10k.

**Comment by phemmer** [comment]
There's also a third option. Reduce the number of goroutines needed.

**Comment by MarcoLotz** [comment]
Yes. But that would just hold only until a user want more than 10k containers. There are several companies with more than 10k containers/host, including IBM (they were showing it on dockercon).

**Comment by phemmer** [comment]
...unless we make it so that it takes 0 goroutines to manage a container.

**Comment by cpuguy83** [comment]
Closing as this is a dup of #15256.
Can you move the discussion over there?
Thanks!

**Comment by MelGHub** [comment]
How did you re-compile the docker daemon?
