### ISSUE TITLE
Error starting daemon: Error initializing network controller: could not delete the default bridge network: network bridge has active endpoints

### ISSUE THREAD

**Issue by caseca** [docker/docker#18283]
When I try to start docker container I receive the error:
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
Error: failed to start containers: [74858bfce398ceaa132559ed5dd1d88934c6c45e413f047791f1096d6679e695]

I found in /var/log/upstart/docker.log:
^[[34mINFO^[[0m[0000] API listen on /var/run/docker.sock
^[[34mINFO^[[0m[0000] [graphdriver] using prior storage driver "aufs"
^[[34mINFO^[[0m[0000] Firewalld running: false
^[[31mFATA^[[0m[0000] Error starting daemon: Error initializing network controller: could not delete the default bridge network: network bridge has active endpoints
/var/run/docker.sock is up

**Comment by caseca** [comment]
docker version:
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

docker info:
An error occurred trying to connect: Get http:///var/run/docker.sock/v1.21/info: read unix /var/run/docker.sock: connection reset by peer

uname -a:
Linux visagio-0466 3.13.0-68-generic #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

I think this is a bug but I don't know.
This error occour after install this upgrades:
2015-11-26 21:29:58 upgrade dpkg:amd64 1.17.5ubuntu5.4 1.17.5ubuntu5.5
2015-11-26 21:30:05 upgrade libmm-glib0:amd64 1.0.0-2ubuntu1 1.0.0-2ubuntu1.1
2015-11-26 21:30:06 upgrade openjdk-7-jdk:amd64 7u85-2.6.1-5ubuntu0.14.04.1 7u91-2.6.3-0ubuntu0.14.04.1
2015-11-26 21:30:08 upgrade openjdk-7-jre:amd64 7u85-2.6.1-5ubuntu0.14.04.1 7u91-2.6.3-0ubuntu0.14.04.1
2015-11-26 21:30:10 upgrade icedtea-7-jre-jamvm:amd64 7u85-2.6.1-5ubuntu0.14.04.1 7u91-2.6.3-0ubuntu0.14.04.1
2015-11-26 21:30:10 upgrade openjdk-7-jre-headless:amd64 7u85-2.6.1-5ubuntu0.14.04.1 7u91-2.6.3-0ubuntu0.14.04.1
2015-11-26 21:30:15 upgrade dpkg-dev:all 1.17.5ubuntu5.4 1.17.5ubuntu5.5
2015-11-26 21:30:16 upgrade libdpkg-perl:all 1.17.5ubuntu5.4 1.17.5ubuntu5.5
2015-11-26 21:30:17 upgrade libunity-control-center1:amd64 14.04.3+14.04.20140922-0ubuntu1.1 14.04.3+14.04.20150916-0ubuntu1
2015-11-26 21:30:18 upgrade modemmanager:amd64 1.0.0-2ubuntu1 1.0.0-2ubuntu1.1
2015-11-26 21:30:19 upgrade unity-control-center:amd64 14.04.3+14.04.20140922-0ubuntu1.1 14.04.3+14.04.20150916-0ubuntu1

**Comment by caseca** [comment]
Sorry!

**Comment by thaJeztah** [comment]
@caseca has it been resolved for you?

**Comment by caseca** [comment]
Nop, I found the solution in other ticket.

**Comment by dronov** [comment]
@caseca it would be great if you put the link for your solution here.

**Comment by jjscarafia** [comment]
me too, @caseca can you share the solution?

**Comment by caseca** [comment]
The link for solution https://github.com/docker/docker/issues/17083

**Comment by jkasaudhan** [comment]
I went through the solution provided above and removed  /var/lib/docker/network and it worked.

sudo rm -r /var/lib/docker/network 

Thanks @caseca

**Comment by rogaha** [comment]
It happened with me as well: 
<pre>
docker@boot2docker:~$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

time="2016-01-11T18:46:00.193523668Z" level=debug msg="Registering ipam provider: default"
time="2016-01-11T18:46:00.235543617Z" level=debug msg="Cleaning up old shm/mqueue mounts: start."
time="2016-01-11T18:46:00.235685146Z" level=fatal msg="Error starting daemon: Error initializing network controller: could not delete the default bridge network: network bridge has active endpoints"

</pre>

**Comment by rogaha** [comment]
Deleting the `/var/lib/docker/network` directory solved the issue.

**Comment by dminca** [comment]
My problem was fixed after reinstalling docker:
```bash
$ sudo apt-get remove docker-engine
$ sudo chown me:me /var/lib/docker
$ rm -rfv /var/lib/docker
```
then proceed with the [install process](https://github.com/dminca/dotfiles/blob/master/init#L94-L107)

**Comment by kvashishta** [comment]
So, rm /var/lib/docker/network did not work for me. What woked was deleting the bridged interface named "docker0", this can be done on RHEL/CentOS by: 1)ip link set docker0 down 2)brctl delbr docker0 and then systemctl start docker

**Comment by mavenugo** [comment]
We resolved this issue in 1.9.0 (for docker0 bridge). If anyone else is seeing this issue in 1.10.0, Pls copy the entire startup log and share that information here.

**Comment by kvashishta** [comment]
This is the order of the steps:

[root@system network-scripts]# ip link set docker0 down
[root@system network-scripts]# brctl delbr docker0
[root@system network-scripts]# rm -fr /var/lib/docker/network
[root@system network-scripts]# systemctl start docker
[root@system network-scripts]# ps -ef | grep -i docker
root     62193     1  5 15:25 ?        00:00:00 /usr/bin/docker daemon -H fd://
root     62273 48562  0 15:25 pts/1    00:00:00 grep --color=auto -i docker
[root@system network-scripts]#

**Comment by noelyahan** [comment]
sudo `rm -r /var/lib/docker/network` worked for me thanks @jkasaudhan & @caseca

**Comment by iam-peekay** [comment]
@mavenugo I have this error in 1.10.2
```
root@tta:/# docker version
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
root@tta:/#  sudo service docker start
docker start/running, process 23362
root@tta:/# sudo docker run hello-world
docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
See 'docker run --help'.
root@tta:/# docker info
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
root@tta:/# uname -a
Linux tta 4.2.0-30-generic #35~14.04.1-Ubuntu SMP Fri Feb 19 14:48:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
root@tta:/# /usr/bin/docker daemon -H unix:///var/run/docker.sock
INFO[0000] [graphdriver] using prior storage driver "aufs"
INFO[0000] Graph migration to content-addressability took 0.00 seconds
INFO[0000] Firewalld running: false
FATA[0000] Error starting daemon: Error initializing network controller: Error creating default "bridge" network: failed to parse pool request for address space "LocalDefault" pool "" subpool "": could not find an available predefined network
```

**Comment by iam-peekay** [comment]
I also tried to remove ```/var/lib/docker/network``` but that didn't fix the issue for me

**Comment by kvashishta** [comment]
try this:
#ip link set docker0 down
# brctl delbr docker0
rm /var/lib/docker/network
restart docker

**Comment by iam-peekay** [comment]
@kvashishta thank you..but didn't work
```
root@tta:~# ip link set docker0 down
Cannot find device "docker0"
```

**Comment by kvashishta** [comment]
maybe your docker interface is named differently, please send  o/p of:
ip ad sh

**Comment by iam-peekay** [comment]
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: em1: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master bond0 state UP group default qlen 1000
    link/ether 00:25:90:7b:59:9d brd ff:ff:ff:ff:ff:ff
3: p4p1: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master bond0 state UP group default qlen 1000
    link/ether 00:25:90:7b:59:9d brd ff:ff:ff:ff:ff:ff
4: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 00:25:90:7b:59:9d brd ff:ff:ff:ff:ff:ff
    inet6 fe80::225:90ff:fe7b:599d/64 scope link
       valid_lft forever preferred_lft forever
5: bond0.2764@bond0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether fa:16:3e:7c:ae:cc brd ff:ff:ff:ff:ff:ff
    inet 63.251.224.244/28 brd 63.251.224.255 scope global bond0.2764
       valid_lft forever preferred_lft forever
    inet6 fe80::f816:3eff:fe7c:aecc/64 scope link
       valid_lft forever preferred_lft forever
6: bond0.3739@bond0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether fa:16:3e:83:b3:e5 brd ff:ff:ff:ff:ff:ff
    inet 172.31.9.212/28 brd 172.31.9.223 scope global bond0.3739
       valid_lft forever preferred_lft forever
    inet6 fe80::f816:3eff:fe83:b3e5/64 scope link
       valid_lft forever preferred_lft forever
```

**Comment by kvashishta** [comment]
Not sure, docker by default creates a docker0 interface, so it will not be
named anything else....

**Comment by iam-peekay** [comment]
@kvashishta @mavenugo yeah. it looks like something with the Docker install is failing. 

I followed the exact step by step instructions here (https://docs.docker.com/engine/installation/linux/ubuntulinux/). I tried:
1) To create a docker group with a user, then log out and log in and restart docker deamon
2) To uninstall and reinstall Docker
3) Remove the ```/var/lib/docker/network``` folder

and neither of these worked for me.

**Comment by boussou** [comment]
on Manjaro (Arch) :

`rm /var/lib/docker/network/files/*`

and then it worked immediately (I had "Error starting daemon: Error initializing network controller: could not delete the default bridge network: network bridge has active endpoints")

**Comment by DamionWaltermeyer** [comment]
Hi. Having the same issue.   Thoughts?
It was running, got a hard reset and now this:
"An error occurred trying to connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.22/info: read unix @->/var/run/docker.sock: read: connection reset by peer"


/var/log/upstart/docker.log is full of this loop. 
/var/run/docker.sock is up
INFO[0000] [graphdriver] using prior storage driver "aufs" 
INFO[0000] Graph migration to content-addressability took 0.00 seconds 
INFO[0000] Firewalld running: false                     
FATA[0000] Error starting daemon: Error initializing network controller: could not delete the default bridge network: network bridge has active endpoints 
/var/run/docker.sock is up
INFO[0000] [graphdriver] using prior storage driver "aufs" 
INFO[0000] Graph migration to content-addressability took 0.00 seconds 
INFO[0000] Firewalld running: false                     
FATA[0000] Error starting daemon: Error initializing network controller: could not delete the default bridge network: network bridge has active endpoints 
/var/run/docker.sock is up
INFO[0000] [graphdriver] using prior storage driver "aufs" 
INFO[0000] Graph migration to content-addressability took 0.00 seconds 
INFO[0000] Firewalld running: false                     
FATA[0001] Error starting daemon: Error initializing network controller: could not delete the default bridge network: network bridge has active endpoints 

uname -a
Linux docker-hostnameremoved 3.16.0-62-generic #83~14.04.1-Ubuntu SMP Fri Feb 26 22:52:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

docker version
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

/etc/issue
"Ubuntu 14.04.4 LTS \n \l"

**Comment by DamionWaltermeyer** [comment]
Fixed:  
''' ls /var/lib/docker/network/files | wc -l
20937'''

Clearing this out corrected the issue, but this still seems like a bug in 1.10.2 that should be fixed.

**Comment by DamionWaltermeyer** [comment]
Hi, This is still happening in 1.10.2,   What additional information can I provide to help get this fixed? I just cleared a few thousand containers off multiple servers.

**Comment by caussourd** [comment]
I got the same issue with Docker 1.10.3

I could fixed it with `sudo rm -r /var/lib/docker/network`

Here are the daemon logs: 

```
/var/run/docker.sock is up
^[[34mINFO^[[0m[0020] Graph migration to content-addressability took 0.00 seconds
^[[33mWARN^[[0m[0020] Running modprobe bridge br_netfilter failed with message: modprobe: WARNING: Module br_netfilter not found.
insmod /lib/modules/3.13.0-85-generic/kernel/net/llc/llc.ko
insmod /lib/modules/3.13.0-85-generic/kernel/net/802/stp.ko
insmod /lib/modules/3.13.0-85-generic/kernel/net/bridge/bridge.ko
, error: exit status 1
^[[34mINFO^[[0m[0020] Firewalld running: false
^[[31mERRO^[[0m[0020] getEndpointFromStore for eid 4bf1266f9520685c1467592223abef97199711b77d7f7bf2a5e5845cd5f74af3 failed while trying to build sandbox for cleanup: could not find endpoint 4bf1266f9520685c1467592223abef97199711b77d7f7bf2a5e5845cd5f74af3: []
^[[33mWARN^[[0m[0020] Failed deleting endpoint 4bf1266f9520685c1467592223abef97199711b77d7f7bf2a5e5845cd5f74af3: failed to get endpoint from store during Delete: could not find endpoint 4bf1266f9520685c1467592223abef97199711b77d7f7bf2a5e5845cd5f74af3: []

^[[31mFATA^[[0m[0020] Error starting daemon: Error initializing network controller: could not delete the default bridge network: network bridge has active endpoints
/var/run/docker.sock is up
^[[34mINFO^[[0m[0000] Graph migration to content-addressability took 0.00 seconds
^[[34mINFO^[[0m[0000] Firewalld running: false
^[[31mFATA^[[0m[0000] Error starting daemon: Error initializing network controller: could not delete the default bridge network: network bridge has active endpoints
/var/run/docker.sock is up
^[[34mINFO^[[0m[0000] Graph migration to content-addressability took 0.00 seconds
^[[34mINFO^[[0m[0000] Firewalld running: false
^[[31mFATA^[[0m[0000] Error starting daemon: Error initializing network controller: could not delete the default bridge network: network bridge has active endpoints
```

**Comment by angeloluciani** [comment]
I had the same issue. Thank you guys for share

**Comment by equivalent** [comment]
had same problem with Ubuntu 15.04 after updating kernel to  `Linux  4.2.0-36-generic`

solution is to remove `sudo rm -rf /var/lib/docker/network/files` and after that restart the machine 

...one other thing I've done was to do ` sudo ifconfig docker0 down` before restart, maybe that helped too 

ping @iam-peekay, try this maybe it will work

**Comment by pbsvp** [comment]
Thanks. The solution: `sudo rm -rf /var/lib/docker/network/files` works for me too.

Docker Version 1.9.1 on **CentOS 7**.

**Comment by metal3d** [comment]
Same issue here, tried to remove /var/lib/docker/network/files and the whole solution yo gave here and nothing works.

```
systemctl restart docker
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
```

```
sept. 06 12:59:16 smilelab-host1 docker-current[19062]: time="2016-09-06T12:59:16.321497277+02:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
sept. 06 12:59:16 smilelab-host1 docker-current[19062]: time="2016-09-06T12:59:16.327971464+02:00" level=info msg="Firewalld running: false"
sept. 06 12:59:16 smilelab-host1 docker-current[19062]: time="2016-09-06T12:59:16.399576656+02:00" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: Failed to setup IP tables, cannot acquire Interface address: Interface lbr0 has no IPv4 addresses"
sept. 06 12:59:16 smilelab-host1 systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
sept. 06 12:59:16 smilelab-host1 systemd[1]: Failed to start Docker Application Container Engine.
```

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: em1: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond0 state UP qlen 1000
    link/ether 78:2b:cb:41:a5:b5 brd ff:ff:ff:ff:ff:ff
3: em2: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond0 state UP qlen 1000
    link/ether 78:2b:cb:41:a5:b5 brd ff:ff:ff:ff:ff:ff
4: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP 
    link/ether 78:2b:cb:41:a5:b5 brd ff:ff:ff:ff:ff:ff
    inet 10.20.64.11/24 brd 10.20.64.255 scope global bond0
       valid_lft forever preferred_lft forever
6: lbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP 
    link/ether 36:c2:44:a6:90:41 brd ff:ff:ff:ff:ff:ff
7: vovsbr@vlinuxbr: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc pfifo_fast master ovs-system state UP 
    link/ether 2e:90:c9:e1:4f:0c brd ff:ff:ff:ff:ff:ff
8: vlinuxbr@vovsbr: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc pfifo_fast master lbr0 state UP 
    link/ether 36:c2:44:a6:90:41 brd ff:ff:ff:ff:ff:ff
9: ovs-system: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN 
    link/ether 22:55:81:ce:e6:14 brd ff:ff:ff:ff:ff:ff
10: br0: <BROADCAST,MULTICAST> mtu 1450 qdisc noop state DOWN 
    link/ether 8a:f8:1a:2a:ff:48 brd ff:ff:ff:ff:ff:ff
11: tun0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN 
    link/ether a2:ed:97:25:3c:78 brd ff:ff:ff:ff:ff:ff
    inet 10.1.2.1/24 scope global tun0
       valid_lft forever preferred_lft forever
```

```
rpm -qa docker
docker-1.10.3-46.el7.centos.10.x86_64
```

Very complicated... Note that I'm installing openshift and docker is installed by openshift-ansible via RPM.

**Comment by joelgriffiths** [comment]
I had this problem and resolved it my turning off my vpn before starting docker.

**Comment by kuche1991** [comment]
This fixed it for me:

`head -n -1 /etc/resolv.conf | sudo tee /etc/resolv.conf`

([sdujancourt.me/2017/02/07/dockerd-error-initializing-network-controller-list-bridge-addresses-failed-no-available-network/](sdujancourt.me/2017/02/07/dockerd-error-initializing-network-controller-list-bridge-addresses-failed-no-available-network/))

**Comment by nikoo56** [comment]
Am I mission something where is sudo rm -r /var/lib/docker/network?    where should I run it? when I ran it? I am getting same error after I created a transparent network. I deleted everything and install docker again but I still get this error after I switch to windows container.

**Comment by DamionWaltermeyer** [comment]
@nikoo56 You should run it from the host, not inside the container.    Is this a windows host or a linux host?

**Comment by nikoo56** [comment]
@DamionWaltermeyer  its Windows host, I run everything in windows powershell. Like Docker info. but I never seen sudo

**Comment by tomholub** [comment]
Was getting this error when installing docker-ce on Ubuntu 17.10 artful.

Turning off vpn & installing again fixed it, thanks.
