### ISSUE TITLE
Proposal: extend Dockerfile syntax with UNVOLUME

### ISSUE THREAD

**Issue by frank-dspeed** [docker/docker#18287]
I see the need for a UNVOLUME syntax in Dockerfile for overwriting Volumes from used  Images.

**Comment by thaJeztah** [comment]
Also see https://github.com/docker/docker/pull/8177. However, because of the moratorium that's in place on the Dockerfile syntax https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax, we currently cannot make changes there.

**Comment by frank-dspeed** [comment]
I see the need to code a external builder plz can you give me a method to find all open issus related to docker build like open future requests? so i can implament all that in the external builder?

**Comment by thaJeztah** [comment]
Searching for https://github.com/docker/docker/labels/area/builder would be a start, but I don't have a full list at hand for all feature requests; most of them are not yet decided on as well. Sorry :relaxed:

**Comment by calavera** [comment]
As @thaJeztah, we're not going to implement this in the near future. The external builder work is in progress, we will have more concrete information about it soon, but it will have a separated repo so all the issues around it are isolated.

I'm going to close this issue, though, because we're not going to do that in docker.
Thanks for your feedback.

**Comment by ememisya** [comment]
Certain projects require UNVOLUME, for example, if you look at wordpress fpm-alpine

https://github.com/docker-library/wordpress/blob/5bad0cb022513fc9bb3bbc72c62db2bac0f5e84a/php7.2/fpm-alpine/Dockerfile

I was unable to change the default volume to anything other than /var/www/html, which does not play well with a heterogeneous setup.

**Comment by theundefined** [comment]
Any progress on that? It would be extremly usefull to possibility of unvolume directories and allow fill content on build stage.

**Comment by loeffel-io** [comment]
+1

**Comment by frank-dspeed** [comment]
@theundefined @loeffel-io Sorry for you guys this will not happen the solution is to create a Custom Builder.

**Comment by thaJeztah** [comment]
https://github.com/moby/moby/issues/3465 is still open; 

https://github.com/moby/moby/issues/3465#issuecomment-356988520

> since reopening this issue, nobody started working on a pull-request; the existing pull request did no longer apply cleanly on the code-base so a new one has to be opened; if anyone is interested in working on this, then things can get going again.
>
> See my earlier comment(s); https://github.com/moby/moby/issues/3465#issuecomment-247405438
>
> > We discussed this issue in the maintainers meeting, and generally, we're OK to start working on this again.
> >
> > @ duglin are you perhaps interested in working on this?
>
> And https://github.com/moby/moby/issues/3465#issuecomment-313549657
>
> > As to why it isn't there yet; simply because nobody has had time to start working on it, but if someone is interested, it most likely will be accepted.

With BuildKit being used as the next generation builder, as start for this would be to include it in the "experimental" front-end (https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/experimental.md), which would make the feature available to any docker version that has buildkit support (docker 18.06 and up with "experimental" enabled, and docker 18.09 and up). After that it could move to the non-experimental Dockerfile syntax.
