### ISSUE TITLE
iptables in Docker 1.9.

### ISSUE THREAD

**Issue by reputet** [docker/docker#18280]
I haven't found any information about iptables in Docker 1.9.
Within  `man docker` there is no information about iptables too.
The last reference about iptables was in Docker 1.8 documentation
http://docs.docker.com/v1.8/articles/networking/#between-containers

##### But, in Docker 1.9
I can use this option `--iptables=false` in order to force Docker never make changes to my system iptables rules.

Is it option deprecated?
Or is it incomplete description?
Or is it a bug?

**Comment by thaJeztah** [comment]
No this options is not deprecated. The information is still there, but moved to a different URL; see http://docs.docker.com/engine/userguide/networking/default_network/container-communication/

And the option is still documented in the list of daemon options; http://docs.docker.com/engine/reference/commandline/daemon/

Does the `--iptables` option not work correctly for you? Or were you just unsure if it was deprecated?

**Comment by reputet** [comment]
Oh, thank you!
I used to the information is located in "Network configuration".
Unfortunately, google couldn't find your links by query "docker iptables".
>Does the --iptables option not work correctly for you? Or were you just unsure if it was deprecated?

I was just unsure.

And i see that information about iptables is in `man docker-daemon`.
I don’t have any questions.

Thanks.

**Comment by thaJeztah** [comment]
thanks! perhaps we should have a look at google not properly indexing that

/cc @moxiegirl
