### ISSUE TITLE
Cannot run Tensorflow in Docker, SH: docker machine not found, Windows 7

### ISSUE THREAD

**Issue by ahwc88** [docker/docker#18291]
I am new to docker. I am trying to use docker to run Tensorflow. I created the machine with the instruction online: b.gcr.io/tensorflow/tensorflow. But, when I use $ docker run, it said local image not found.

![capture](https://cloud.githubusercontent.com/assets/16060802/11453039/b5faff2c-95c9-11e5-8363-85aaac9bbd8f.PNG)

 Then, I realized that my docker is not connected to the outside world. So, I tried to set it up so that it can connect to the outside world using the instruction. http://www.netinstructions.com/how-to-install-docker-on-windows-behind-a-proxy/.

But, it gave me an error: -sh: docker-machine: not found

![capture2](https://cloud.githubusercontent.com/assets/16060802/11453048/17ebe944-95ca-11e5-8a83-7755a0c1de58.PNG)

Can anyone help please? I really want to learn about tensorflow and docker. I am really excited.

I am using Windows 7. Please let me know if you need anymore information!

**Comment by thaJeztah** [comment]
Looks like you're still logged in to your boot2docker virtual machine (through ssh) and docker-machine is not installed inside the virtual machine, but on your windows host. Try to "exit" the ssh session (just type `exit`, to return to your windows machine

**Comment by ahwc88** [comment]
Thank you for your reply! I typed exit and logged into the docker. But docker machine is still not found. Would you kindly help me to navigate?

![capture](https://cloud.githubusercontent.com/assets/16060802/11453276/b3e0d884-95d2-11e5-888a-0b32c43d05fb.PNG)

**Comment by thaJeztah** [comment]
It looks like you're still trying to execute `docker-machine` from inside the boot2docker virtual machine; those commands should be executed on the windows machine, not inside the VM. I suggest to;
a) restart your computer (sometimes VirtualBox is unable to reach a DNS server, rebooting the computer can resolve that)
b) check the steps in the linked article again to check if the proxy is properly configured

**Comment by ahwc88** [comment]
By Windows machine, do you mean CMD of Windows 7?

**Comment by thaJeztah** [comment]
yes, or the quick start terminal of docker toolbox

**Comment by ahwc88** [comment]
I tried. It seems like my Windows is not recognizing the docker-machine command either. 

What should I do?

![capture](https://cloud.githubusercontent.com/assets/16060802/11454519/64834a22-95fc-11e5-9bfe-55030efe5f47.PNG)

**Comment by thaJeztah** [comment]
Hm, looks like you don't have a full setup. Have you tried using our installation manual instead of the one tensor flow describes? The easiest way is installing Docker Toolbox. Here's the installation steps; http://docs.docker.com/engine/installation/windows/#installation and a "getting started" https://docs.docker.com/windows/started/

**Comment by LK4D4** [comment]
I'm closing this because time passed and there is docker 4 windows now.
