### ISSUE TITLE
docker network create with IPv6 subnets using iptables fails

### ISSUE THREAD

**Issue by oszi** [docker/docker#18297]
Description of problem:
The docker network create command does not work with IPv6 subnets using iptables.

`docker version`:
```
Client:
 Version:         1.9.1-fc23
 API version:     1.21
 Package version: docker-1.9.1-2.git78bc3ea.fc23.x86_64
 Go version:      go1.5.1
 Git commit:      f7c1d52-dirty
 Built:           Fri Nov 20 21:07:14 UTC 2015
 OS/Arch:         linux/amd64

Server:
 Version:         1.9.1-fc23
 API version:     1.21
 Package version: docker-1.9.1-2.git78bc3ea.fc23.x86_64
 Go version:      go1.5.1
 Git commit:      f7c1d52-dirty
 Built:           Fri Nov 20 21:07:14 UTC 2015
 OS/Arch:         linux/amd64

```

`docker info`:
```
Server Version: 1.9.1-fc23
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: journald
Kernel Version: 4.2.6-301.fc23.x86_64
Operating System: Fedora 23 (Cloud Edition)
```

`uname -a`:
`Linux 4.2.6-301.fc23.x86_64 #1 SMP Fri Nov 20 22:22:41 UTC 2015 x86_64 GNU/Linux`

Environment details (AWS, VirtualBox, physical, etc.):
Fedora 23, DigitalOcean

How reproducible:
100%

Steps to Reproduce:
1. `dnf --enablerepo=updates-testing install docker`
2. `docker network create --subnet=2001:470::/64 test`

Actual Results:
```
Error response from daemon: unable to add inter-network communication rule: \
iptables failed: iptables --wait -I FORWARD -s 2001:470::1/64 -d 2001:1337::1/64 \
-j DROP: iptables v1.4.21: invalid mask `64' specified
```

Expected Results:
Docker currently does not deal with IPv6 rules so it could just not do anything in this case either.

Additional info:
On the other hand, IPv6 subnets do work on my workstation that's running with firewalld.

**Comment by mavenugo** [comment]
@oszi can you please confirm that the problem is seen only with `-icc=false` option ?

**Comment by cdauth** [comment]
I have the same issue. The error comes both with `--icc=false` and `--icc=true`. It only comes when another network with an IPv6 subnet already exists (as it is trying to prevent the communication between those two subnets).

With `--iptables=false` the error doesn't come up.

**Comment by aboch** [comment]
Thanks @cdauth for reporting this.

I think the issue is because bridge driver blindly uses the iptables package (which relies on `iptables` command) for both ipv4 and ipv6 rules.

I think the proper change would be to enhance the iptables package to switch to `ip6tables` when dealing with IPv6 rules.

In case firewalld is installed, instead, iptables defers to it the programming request and, I guess, firewalld already handles properly the ipv6 rules.

**Comment by oszi** [comment]
@aboch Yeah, I think so too. But if you go that route - using ip6tables - you might as well implement everything else that's missing like forward rules. :)
So I think the consistent behavior would be to skip firewall rules for IPv6 for now.

**Comment by aboch** [comment]
Thanks @oszi for the wise suggestion.
