### ISSUE TITLE
"docker run --detach=false" weird documentation explanation

### ISSUE THREAD

**Issue by redhatlinux10** [docker/docker#18300]
when i type `docker run --help`, it gives:
>-d, --detach=**false**              Run container in background and print container ID

i know this is called detached mode, but shouldn't it be the following ?
>-d, --detach=**true**              Run container in background and print container ID

there are a lot similar problems about other options, such as `-t=false`, `--rm=false`, `--help=false`. do i misunderstand these options?

docker version: `Docker version 1.9.1, build a34a1d5`
docker info:
>Containers: 0
Images: 4
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 4
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 1.954 GiB
Name: ubuntu
ID: VNFK:3L2W:JOFP:6L3B:FN6Y:JVDN:QSGJ:N4IJ:6JOE:M57L:J4SX:LHCT
WARNING: No swap limit support

uname -a:`Linux ubuntu 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by thaJeztah** [comment]
Actually, the documentation is correct, but may be confusing. The `=false` is the way that the defaults for (boolean) flags is documented, i.e., `--detach=false` is the default.

I raised this issue some time ago; https://github.com/docker/docker/issues/9406, but perhaps we should change this after all

**Comment by MHBauer** [comment]
With the patch from  it looks like #18082
```
  -d, --detach                    Run container in background and print container ID
```

**Comment by thaJeztah** [comment]
@MHBauer yes, I just spotted it was merged, but not yet in the current release. Maybe we should update the documentation to match the new output, and remove the `=false` defaults from boolean flags?

**Comment by MHBauer** [comment]
Oooh, yea, that's a good point. The docs need to be updated. :sob: I'm responsible for that...

**Comment by thaJeztah** [comment]
haha, also see https://github.com/docker/docker/issues/18311, which was just created

**Comment by LK4D4** [comment]
was fixed
