### ISSUE TITLE
[Question] How to figure out how much layers and their size I need to download before docker pull?

### ISSUE THREAD

**Issue by resouer** [docker/docker#18304]
My use case is, my images are huge (java web, GB), download a fresh image to a host is painful.

So I was thinking, how can I tell out how much layers and their sizes I need to download before `docker pull`, so I can make better decisions like use another node with more ready layers.

**Comment by thaJeztah** [comment]
Thanks for asking. I think currently the best option is to look at the sizes specified at docker hub; https://hub.docker.com/r/library/ubuntu/tags/

However, this looks like a duplicate of https://github.com/docker/docker/issues/1512

I'm going to close this issue as a duplicate of https://github.com/docker/docker/issues/1512, please continue the discussion on that issue, thanks!
