### ISSUE TITLE
How to change docker0's IP address?

### ISSUE THREAD

**Issue by xiekuncn** [docker/docker#18307]
The network bridge docker0's default IP address is ```172.18.0.1``` on my computer, but this address conflicts with our company's gateway. And I want to change this address such as ```10.0.42.1```. 
I try to follow the documentation as https://github.com/docker/docker/blob/master/docs/userguide/networking/default_network/build-bridges.md. it is __temporal__ until reboot the host OS. 
What would it be the __permanent__ procedure?  

```
$ docker --version
Docker version 1.9.1, build a34a1d5
$ docker info
Containers: 1
Images: 25
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 27
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-63-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 15.57 GiB
Name: aoi-B85-HD3-A
ID: 36MB:5CYD:EPMO:FV4M:BSBC:C4EF:GBDZ:CIMY:XVK5:HY3W:BLM3:TWGT
Http Proxy: http://127.0.0.1:3128/
WARNING: No swap limit support
```

PS:
And the Docker 1.6.2 works fine, and docker0's default IP address is ```10.0.42.1```.

**Comment by thaJeztah** [comment]
hm, this page may be of interest as well https://docs.docker.com/engine/userguide/networking/default_network/custom-docker0/

**Comment by cpuguy83** [comment]
@xiekuncn The easiest solution is to use `--bip 10.0.42.1/<subnet>` on the daemon options.
You'll first have to delete the existing docker0 bridge for this setting to take effect.

**Comment by sswierczyna** [comment]
` You'll first have to delete the existing docker0 bridge for this setting to take effect.`
@cpuguy83 what do You mean saying "delete"?
What command should I use?

**Comment by vide** [comment]
@sswierczyna `ip link del docker0` on Linux should do the trick

**Comment by windery** [comment]
The better solution is create a new newtwork with the command :
```
docker network create --subnet=10.0.42.1/24 --opt com.docker.network.bridge.name=my_bridge mybridge
```
Then specify it with `-network=my_bridge` when you **first run** an docker instance.

**Comment by yurenchen000** [comment]
NOTE: seems if `live-restore` is true, bip may not apply when restart docker.service
