### ISSUE TITLE
Review MAINTAINERS files

### ISSUE THREAD

**Issue by icecrime** [docker/docker#18319]
We need to refresh the MAINTAINERS files as they do not reflect reality anymore. In particular:

- The MAINTAINERS file in each repository should strictly reflect the people maintaining this specific sub-project.
- The MAINTAINERS files should follow a common TOML formatting.
- A Docker-wide MAINTAINERS file should be assembled in a neutral repository (I'm thinking [docker/opensource](https://github.com/docker/opensource).

I suggest the following plan:

- [x] Submit PR to the main Docker sub-projects to make the format more consistent.
- [x] Clean-up the `docker/docker` MAINTAINERS file to remove deprecated elements.
- [x] Create the assemblage script in `docker/opensource` to produce the "master" file.

**Comment by thaJeztah** [comment]
sgtm!

**Comment by MHBauer** [comment]
How do we feel about this, considering all the merged references?

**Comment by thaJeztah** [comment]
Yup, I think it's all done; closing. Thanks!
