### ISSUE TITLE
`docker run`/`docker rm` extremely slow in Docker 1.9.1 with devicemapper

### ISSUE THREAD

**Issue by samuelkarp** [docker/docker#18314]
Description of problem: `docker run`/`docker rm` extremely slow in Docker 1.9.1 with devicemapper

`docker version`:
```
ubuntu@ip-172-31-39-228:~$ sudo docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:
```
ubuntu@ip-172-31-39-228:~$ sudo docker info
Containers: 1000
Images: 14
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-202:1-401324-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.369 GB
 Data Space Total: 107.4 GB
 Data Space Available: 26.44 GB
 Metadata Space Used: 47.08 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.1 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-48-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 992.5 MiB
Name: ip-172-31-39-228
ID: ZLSZ:CSSF:WXIO:KKKE:XMIE:JQGJ:ET27:2Z5Z:ABXI:XQBY:76UY:NHTO
WARNING: No swap limit support
```

`uname -a`:
```
ubuntu@ip-172-31-39-228:~$ uname -a
Linux ip-172-31-39-228 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.):
Amazon EC2 instance running Ubuntu 14.04 (ami-5189a661 in us-west-2)

How reproducible:

Steps to Reproduce:
1. Launch an instance with userdata as [this script](https://gist.github.com/samuelkarp/cab8f8bfd50a99df8959)
2. Let it run until it finishes
3. Observe that `docker run` and `docker rm` both grow to take around 90s to complete

Actual Results:
```
ubuntu@ip-172-31-39-228:/opt/test$ tail run-only.out
Ran in 5.17
Running 999/1000
hello, container
Ran in 87.74
Running 1000/1000
hello, container
Ran in 85.55
Ran 1000; the longest-running container took 92.66 to run.
ubuntu@ip-172-31-39-228:/opt/test$ tail run-delete.out 
2507862ce325f509367fcf070858705bd92885654401037a00f2722812598647
Removing 2507862ce325f509367fcf070858705bd92885654401037a00f2722812598647
2507862ce325f509367fcf070858705bd92885654401037a00f2722812598647
Removed in 72.49
Running 1000/1000: a87283b31e3d8b0e4a5207d4261c04340998a56b4414547cbcb72cd19d17ee0b
a87283b31e3d8b0e4a5207d4261c04340998a56b4414547cbcb72cd19d17ee0b
Removing a87283b31e3d8b0e4a5207d4261c04340998a56b4414547cbcb72cd19d17ee0b
a87283b31e3d8b0e4a5207d4261c04340998a56b4414547cbcb72cd19d17ee0b
Removed in 74.74
Removed 1000; the longest removal took 94.42
```

Expected Results:
`docker run` should take under 1s and `docker rm` should take under 3s (this is what I observe with Docker 1.7.1).

Additional info:  I don't see the same behavior with aufs, so it looks like it's something specific to devicemapper.  I do see this same behavior with Docker 1.9.1 (and Docker 1.9.0) on the Amazon Linux AMI using devicemapper (aufs is not available).  This may be related to #17720 and #17448.

**Comment by cookandy** [comment]
Thank you for opening this. I am experiencing the exact same issue on CentOS 7.1 using devicemapper and Docker 1.9.1.

**Comment by thaJeztah** [comment]
I know the default size for device mapper was changed from 10GB to 100GB in 1.9, which affects the initial creation time, but not sure if that affects performance after the device is created. Having said that, using loop-lvm for production is really discouraged, as it has quite an impact on performance, also see http://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#configuring-docker-with-device-mapper, but that should be the same on docker 1.9 and 1.7

**Comment by thaJeztah** [comment]
ping @rhvgoyal any ideas here?

**Comment by rhvgoyal** [comment]
I think this slowness is observed only in case of loop devices. If one uses proper block devices for thin pool or lvm thin pool on top of block devices, this slowness is not observed.

I suspect it has something to do with discards. I will spend some time debugging this in an attempt to narrow down the problem.

In the mean time, one can move away from loop devices to avoid this problem.

**Comment by rhvgoyal** [comment]
So I did some basic testing on Fedora 23 with docker 1.9.1 and I can't notice any regression w.r.t container creation time. But I can see a very visible difference with container removal. (100G thin device on top of loop devices). Every container removal is taking around 3 seconds and close to 2 seconds is being consumed in discard operation. There have been some improvement in this area in kernel recently and I need to see if those improvements make it better.

**Comment by rhvgoyal** [comment]
Ok, I took a regular SATA disk, and carved out a thin pool from it and docker rm is pretty fast. By default discards are disabled in this configuration and removal of 5 containers took total of .5 seconds. I forced enabled discards using `--storage-opt dm.blkdiscard=true` and then total deletion time went to around 3 seconds. Still not bad.

But on top of loop devices, it takes 16 seconds to delete 5 containers (with 100G device), while it takes around 3-4 seconds with 10G thin devices.

So discards on top of loop devices are very slow and bigger the device longer it takes to issue discards on the device.

**Comment by samuelkarp** [comment]
@rhvgoyal Did you try reproducing with the script I provided?  The run slowness takes a while to kick in (seems to be petty noticeable by the time the script runs ~200 containers), but concurrent mutating operations seem to be related.

**Comment by samuelkarp** [comment]
@rhvgoyal I'm seeing better performance with `--storage-opt dm.blocksize=2097152`.

```
$ sudo docker info
Containers: 572
Images: 14
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-202:1-401311-pool
 Pool Blocksize: 2.097 MB
 Base Device Size: 107.4 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 14.26 GB
 Data Space Total: 107.4 GB
 Data Space Available: 15.83 GB
 Metadata Space Used: 19.23 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.128 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-68-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 992.5 MiB
Name: ip-172-31-40-238
ID: 6EZA:2ML3:3PCT:KZR4:WRCG:MKYK:JXBY:MGKD:PJCJ:P6FQ:Y6XK:ASCQ
WARNING: No swap limit support
```
However it does seem to be consuming more disk than expected.  By changing the blocksize, does that mean each layer consumes at least a full block?

**Comment by rhvgoyal** [comment]
@samuelkarp I have not tried running your script yet. Have you tried running your script without loop devices? Can you use real block devices instead of using loop devices and run your script again.

So one problem I am aware of is container removal takes longer since we increased default size to 100G (from 10G) on top of loop devices. Primary reason is that discards take a long time even if thin device is not used much.

dm-thin developers are already working on improving discard performance when blocks are not mapped. (CC @snitm @jthornber). 

As of now, discard time of whole thin device is proportional to number of blocks. (Even if blocks are not mapped). So to workaround this problem one can do some things.

- Don't use loop devices. By default docker forces issuing discards if loop devices are in use. Once you
  move to proper block devices, discards are not issued, and this delay in device removal is not
  incurred.

- Reduce container size to 10G. Use --storage-opt dm.basesize=10G when docker starts for the
  first time.

- Stop issuing discards using --storage-opt dm.blkdiscard=false. Side effect of this is that once loop
  files have grown, these will not shrink in size when images and containers are deleted.

**Comment by rhvgoyal** [comment]
@samuelkarp Increasing block size of thin pool will help as it reduces the number of virtual blocks to be discarded and currently discard time is proportional to number of virtual blocks being discarded. Currently docker-storage-setup uses a block size of 512K by default.

**Comment by samuelkarp** [comment]
@rhvgoyal I was able to test a separate block device with `direct-lvm` and the performance does look better.  However, this is still a pretty big performance difference using `loop-lvm` between Docker 1.7.1 and Docker 1.9.1.

**Comment by thaJeztah** [comment]
@samuelkarp the difference between 1.7.1 and 1.9.1 is measured using the same base size? (`--storage-opt dm.basesize=10G`)

**Comment by rhvgoyal** [comment]
Ok, I did some testing with container creation time. Wrote a simple script to create containers from an image in loop.

'docker create fedora bash'

I monitored container creation and deletion time of 300 containers both with 1.7.1 and 1.9.1. And as per my numbers 1.9.1 is better than 1.7.1. in terms of container creation time. Container deletion is little slower but not much difference.

1.7.1 (300 containers)
==
Time taken to create containers is 339.088083665
Time taken to delete containers is 31.934699429

1.9.1 (300 containers)
==
Time taken to create containers is 197.987584474
Time taken to delete containers is 37.422725210

I am using an lvm thin pool of block size 512K on real block devices. No loop devices are involved. Here is docker info output.

[root@vm4-f23 docker-tests]# docker info
Containers: 0
Images: 2
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker--vg-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 266.3 MB
 Data Space Total: 6.178 GB
 Data Space Available: 5.912 GB
 Metadata Space Used: 61.44 kB
 Metadata Space Total: 12.58 MB
 Metadata Space Available: 12.52 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.109 (2015-09-22)
Execution Driver: native-0.2
Logging Driver: journald
Kernel Version: 4.2.6-301.fc23.x86_64
Operating System: Fedora 23 (Cloud Edition)
CPUs: 8
Total Memory: 7.797 GiB
Name: vm4-f23.localdomain

ID: EXMN:AVQR:2MQN:SHIC:RBXI:4PAX:WHUC:HHZL:A5I5:5UTS:PMBG:DRLS
Debug mode (server): true
 File Descriptors: 15
 Goroutines: 35
 System Time: 2015-12-04T15:48:32.235223218Z
 EventsListeners: 0
 Init SHA1: e4bd62ab75040f3c408089d3d174f41b0dc7c200
 Init Path: /root/git/rhvgoyal-docker/bundles/latest/dynbinary/dockerinit
 Docker Root Dir: /var/lib/docker

**Comment by rhvgoyal** [comment]
@samuelkarp we need to narrow down the problem a bit. May be it is a configuration difference issue. I am using lvm thin pool on real block devices with xfs as root filesystem for containers.

**Comment by rhvgoyal** [comment]
I ran same 300 container creation/deletion test on top of loop devices. I have used dm.basesize=10G as we know deletion of 100G device is a problem on loop devices. Creation time has gone up in 1.9.1 while deletion time remains or or less same.

Not sure why container creation time has improved with real block devices while it has deteriorated with loop devices.

1.7.1 (300 containers)
--
Time taken to create containers is 113.445792074
Time taken to delete containers is 226.638179428

1.9.1 (300 containers) (dm.basesize=10G)
--
Time taken to create containers is 164.654990169
Time taken to delete containers is 217.204179913

**Comment by samuelkarp** [comment]
@thaJeztah @rhvgoyal I'm testing with the defaults for devicemapper on both Docker 1.7.1 and 1.9.1.  This means loop-lvm, 64kb blocksize, and basesize of 10G for 1.7.1 and 100G for 1.9.1.  @rhvgoyal, I don't see your bash script attached here, but an important part of [my test](https://gist.github.com/samuelkarp/cab8f8bfd50a99df8959) is that there are creates and deletes happening concurrently.

**Comment by rhvgoyal** [comment]
@samuelkarp I am using following script.

https://gist.github.com/rhvgoyal/7def207b8cdada650056

**Comment by rhvgoyal** [comment]
@samuelkarp can you use dm.basesize=10G for 1.9.1 and re-run your script and see if you notice any difference between 1.7.1 and 1.9.1

**Comment by samuelkarp** [comment]
@rhvgoyal Performance looks better with `dm.basesize=10G` or with `direct-lvm`.

**Comment by calavera** [comment]
I guess we should consider then if we want to revert #14709 or not. What do we consider more important?

a/ having space enough to create containers out of the box.
b/ optimal performance to remove containers.

**Comment by thaJeztah** [comment]
Perhaps we should go for less space; given that loopbacks are basically only useful for testing / non-production use, having a smaller size may encourage people to look into "how do I increase the size", and have them discover that `direct-lvm` is a better option.

Having said that; we may need to look into better handling of running out of space :/

**Comment by icecrime** [comment]
@calavera Can you take this one? This seems like something we should clarify sooner then later for 1.10.0.

**Comment by rhvgoyal** [comment]
I guess going back to 10G (or possibly 20G) size is reasonable. And those who need bigger sizes will use dm.basesize=100G for now.

Will be good to also provide capability to specify container size during creation. That way those who need bigger containers can specify per container size. Shishir has a working patch to specify per container size during create time.

@shishir-a412ed can you please generate a PR with that patch.

**Comment by shishir-a412ed** [comment]
@rhvgoyal 
#19123 

Shishir

**Comment by rhvgoyal** [comment]
BTW, following kernel commit fixes the issue of slower discards for 100G thin devices on loop.

https://git.kernel.org/cgit/linux/kernel/git/device-mapper/linux-dm.git/commit/?h=dm-4.5&id=3d5f67332ad9a500857a45397b69a27198720410

This is targeted for 4.5 kernel.

@snitm suggested that we could make default base size dependent on thin-pool target version. If fix is available then use 100G size otherwise use 10G size.

**Comment by baaltommysu** [comment]
Hi all, 

I have similar issue here, Docker v1.9.1 is running on CentOS7 with all default settings, i.e. basesize=100GB, loopback mode. 

But in my case the time needed to remove a container is much longer than the time you guys posted. For example, I start 300 containers with all launching an infinite loop echoing something. Then I stop one container and keep all the other containers running. After this container is stopped, it takes about 8 seconds to remove this container.

With the number of active container decreasing, the time needed to remove a container is also dropping. The last container can be removed in 2.5 seconds.

I guess this time difference (from 8s to 2.5s) is because of device mapper, but I am not sure why the difference is so big. Can someone please enlighten me.

Thanks!
