### ISSUE TITLE
[regression] Cgroups are now forced

### ISSUE THREAD

**Issue by purpleidea** [docker/docker#18323]
I run docker inside of virt-builder to build images that have pre-cached docker containers. This used to work great, but now newer versions of docker fail with an error about how cgroups aren't setup. It would be nice if the virt-builder environment had cgroups, but it's not the type of environment that requires this, and until it can do this, it's a docker regression.

I'm okay with it being the new default. I can patch around that breakage. But I would appreciate some sort of flag to avoid this fatal warning if I decide I don't want to force it. Here is the upstream bug report:
https://bugzilla.redhat.com/show_bug.cgi?id=1284191

Thanks,
James

**Comment by purpleidea** [comment]
@GordonTheTurtle Hi bot. My bug report is complete. Go away please.

**Comment by LK4D4** [comment]
@purpleidea Hmm, I thought that device cgroup was always required, what version do you used before? :/ It's pretty dangerous to use docker without devices cgroup, also it's not hard to mount too.

**Comment by crosbymichael** [comment]
This has always been required.  Maybe the regression is that the error propagates at daemon startup instead of on the first time you run a container.  We can check around and see if something has changed recently.  Thanks!

**Comment by cpuguy83** [comment]
Hard requirement for devices cgroup on daemon init was added by #11882, which first appeared in Docker 1.7.

**Comment by purpleidea** [comment]
@LK4D4 It's not dangerous because it's running without *only* for virt-builder.
@crosbymichael I think you're correct. Since I only was running `docker pull` it was never a problem with the other operations.
@cpuguy83 This looks like the issue! Thanks!

**Comment by crosbymichael** [comment]
I would be ok with changing this log message from Fatal to a Warn to fix this type of issue.

**Comment by purpleidea** [comment]
On Tue, Dec 1, 2015 at 4:15 PM, Michael Crosby <notifications@github.com>
wrote:

> I would be ok with changing this log message from Fatal to a Warn to fix
> this type of issue.



Great idea! I will send this patch if you are okay with this.

**Comment by purpleidea** [comment]
FWIW: this seems to be happening here now, and not in the same location as the previous commit suggested by @cpuguy83 
https://github.com/purpleidea/docker/blob/master/daemon/daemon.go#L817

**Comment by cpuguy83** [comment]
That is correct, the implementation was changed completely.

**Comment by hqhq** [comment]
I don't think change fatal log to warning on daemon start makes much difference. It still can't create any containers. If remove fatal log on container create, could leak a hole.
If we really want to do this, a new option could be better, let user use this option if they really know what they are doing.

**Comment by purpleidea** [comment]
On Thu, Dec 3, 2015 at 10:10 PM, Qiang Huang <notifications@github.com>
wrote:

> I don't think change fatal log to warning on daemon start makes much
> difference. It still can't create any containers. If remove fatal log on
> container create, could leak a hole.
> If we really want to do this, a new option could be better, let user use
> this option if they really know what they are doing.
>


That's fine if you're okay with it. I don't want to create any containers.
I only want to docker pull. If there is a better way (even perhaps using
the systemd dkr code instead?) lmk!

Thanks,
James

**Comment by hqhq** [comment]
@purpleidea If change fatal log to warning on daemon create works for you, you can open a PR for that, I think it won't affect others. It's the easiest way to make everyone happy :)

**Comment by LK4D4** [comment]
Issue spent a long time without attention. Feel free to rephrase it and open new!

**Comment by tryauuum** [comment]
if someone still wants to run docker in virt-customize / other libguestfs tools it's doable, you just need to mount cgroups manually. I needed it to pull docker images in `virt-customize`. A working example

script.sh:
```
#!/bin/bash

set -o errtrace # to inherit trap
set -o errexit
set -o nounset

function terminate_docker() {
    kill $( cat /var/run/docker.pid )
    wait
}
trap 'terminate_docker' ERR INT

mount -t cgroup2 none /sys/fs/cgroup

dockerd --iptables=false --bridge=none --ip-forward=false &
sleep 3
docker pull your-image-specification-here

terminate_docker
```
virt-customize command:
```
virt-customize --network --add image.qcow2 --smp 4 --copy-in script.sh:/tmp --run-command /tmp/script.sh
```
