### ISSUE TITLE
feature request: integrate unbuffer functionality into docker to make apps use line buffering

### ISSUE THREAD

**Issue by stapelberg** [docker/docker#18327]
Issue #1385 is related.

Given that not all applications one wants to run with Docker necessarily support configuring the line buffering of stdout, what do you think of integrating the functionality of [unbuffer](http://man7.org/tlpi/code/online/dist/pty/unbuffer.c.html) into docker, so that one can get meaningful logs from applications?

**Comment by phemmer** [comment]
you can already accomplish the same thing as the `unbuffer` utility by launching your container with `-t`.

**Comment by stapelberg** [comment]
Ah, thanks for pointing that out, that indeed works. Closing this issue then.
