### ISSUE TITLE
Issue with docker Inter container communication on the isolated bridge

### ISSUE THREAD

**Issue by prashantabkari** [docker/docker#18324]
I have created two containers, a sender and a receiver on the the same network. The network i have created is using the following procedure

docker network create --driver bridge isolated_nw
Each of my containers are run in the above isolated_nw using --net option. 

My receiver code has the following 
   " int rc = zmq_bind(responder, "tcp://*:16");"
And sender has the following line 
   "int rc = zmq_connect(requester, "tcp://*:16");"

Even though they are in the same "isolated_nw", they are unable to communicate.
So what am i missing here? 

I have even tried the following
1. Run the receiver container with -p option to expose the port
2. Run it on the default network and not on "isolated nw", but still it doesn't work

**Comment by prashantabkari** [comment]
Please find the required info
abkari@ubuntu:~/zmq/sender_sock$ sudo docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64
abkari@ubuntu:~/zmq/sender_sock$ sudo docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64

abkari@ubuntu:~/zmq/sender_sock$ sudo docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64

**Comment by cpuguy83** [comment]
Can you please provide a full repro case, including `docker run` commands,  output from containers, etc?
Also perhaps a simpler case (like ping or nc).

**Comment by prashantabkari** [comment]
Hi - I found the issue finally . Following are the findings
1. Even if the both of them are on the same network communication fails even if the sender is trying to reach receiver on "localhost" 

2. * as a wildcard cannot be resolved inside the container. Not sure if this is an issue with the docker or zero mq . 

3. Even if the IP address of the receiver is hardcoded and the both containers are not linked, the communication still fails. Looks like the container on receiver side is not discoverable. 

However communication is possible if and only if 
1. the IP address of the receiver is hardcoded in the client container 
2. Both are containers are linked.

**Comment by LK4D4** [comment]
It's possible now to talk by names in networks. Closing issue.
