### ISSUE TITLE
experimental docker install on ubuntu 14.04 failed with package conflict

### ISSUE THREAD

**Issue by HackToday** [docker/docker#18326]
First,  follow this(to make sure install aufs support)

Update your package manager.

$ sudo apt-get update

Install the recommended package.

$ sudo apt-get install linux-image-extra-$(uname -r)

Then 
When followed this:
https://github.com/docker/docker/tree/master/experimental

curl -sSL https://experimental.docker.com/ | sh

it failed with

Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 docker-engine : Depends: init-system-helpers (>= 1.18~) but 1.14 is to be installed
                 Depends: libdevmapper1.02.1 (>= 2:1.02.90) but 2:1.02.77-6ubuntu2 is to be installed
                 Recommends: aufs-tools but it is not going to be installed
                 Recommends: cgroupfs-mount but it is not installable or
                             cgroup-lite but it is not going to be installed
                 Recommends: git but it is not going to be installed
                 Recommends: yubico-piv-tool (>= 1.1.0~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by HackToday** [comment]
ping @thaJeztah

**Comment by HackToday** [comment]
From http://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=init-system-helpers&searchon=names

it seems ubuntu 14.04 LTS not allow initi-system-helpers to install 1.14 newer.


So the experimental guide is not clear what os version should use. And requrements need.

For me, I did not know what to use

**Comment by HackToday** [comment]
This was test against with #18247

**Comment by thaJeztah** [comment]
Thanks @HackToday, I think I've seen this happen on regular builds as well, but not sure why the dependencies fail on some systems. I think one of the other issues had some more info, I'll try to find that one.

**Comment by thaJeztah** [comment]
@HackToday I think this is a duplicate of  https://github.com/docker/docker/issues/17063, and see this comment for a possible solution; https://github.com/docker/docker/pull/13680#issuecomment-122369631

Can you try if that helps?

**Comment by HackToday** [comment]
Hi @thaJeztah  tried the ubuntu 15.04, and it have new init-helper related packages.


For you mentioned  #13680 (comment)  I not try it yet.  My whole point is do we have related such comments in docker official guide(whether user guide or install guide) Could you give me the link  ? Since when I try experimental build , I would refer docker official link and instrcutions

**Comment by thaJeztah** [comment]
@HackToday we do mention purging the old packages here; https://docs.docker.com/engine/installation/ubuntulinux/#update-your-apt-sources (see step 9). Perhaps we should add it to the https://get.docker.com / https://experimental.docker.com scripts as well, but we're trying to encourage people to use the manual install procedure

**Comment by HackToday** [comment]
Hi @thaJeztah  I think two difference things:

1. for experiemental guide, it is the only one given 
https://github.com/docker/docker/tree/master/experimental
And it not said how to configure the apt source for experimental build .

And that experimental used script  curl -sSL https://experimental.docker.com/ | sh
it seems not need manual configure apt source steps. 


2. Second. if you mean configure like this (notice experimental)
 echo deb https://apt.dockerproject.org/repo debian-jessie experimental
I could try if it works. If you mean this, it would be confused to users and inconsistent. 
in one point you asked use script to install, and thought users know how to configure experimental apt source, and ask them to better use apt-get install ways.

**Comment by HackToday** [comment]
And for ubuntu 15.04, I can use this curl -sSL https://experimental.docker.com/ | sh directly. No issues.

But ubuntu 14.04 not work.

**Comment by HackToday** [comment]
The latest experimental script worked. so close it now
