### ISSUE TITLE
Docs broken link and broken 404 error page

### ISSUE THREAD

**Issue by fntlnz** [docker/docker#18339]
On the [Docker Hub API](https://docs.docker.com/v1.7/reference/api/docker-io_api/) documentation page is stated

```
 see the Docker Hub API in the 1.7 documentation.
```

Unfortunately the link to the new API is broken so I tried with: https://docs.docker.com/v1.9/reference/api/docker-io_api/

and I ended up with a 404 error that looked like this:
![2015-12-01_1730x1005_scrot](https://cloud.githubusercontent.com/assets/3083633/11506304/2302ee72-984f-11e5-99f2-fb9a08ae65da.png)

**Comment by thaJeztah** [comment]
Hi @fntlnz thanks for reporting! I created an issue earlier today for fixing that weird 404 page; https://github.com/docker/docker/issues/18333

I'll check the link to the old Docker Hub api on this page; http://docs.docker.com/engine/reference/api/docker-io_api/ which should point to http://docs.docker.com/v1.7/docker/reference/api/docker-io_api/

**Comment by thaJeztah** [comment]
Created a pull-request to fix the link https://github.com/docker/docker/issues/18341
