### ISSUE TITLE
docs: 404 pages referencing local boot2docker IP address

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#18333]
Found this when reading docs.docker.com;
https://docs.docker.com/engine/reference/

That page is published using 192.168.99.100 as domain name

<img width="1738" alt="screen shot 2015-12-01 at 13 00 13" src="https://cloud.githubusercontent.com/assets/1804568/11500207/e6f469ba-982b-11e5-8941-0d11a86d876f.png">

**Comment by thaJeztah** [comment]
Perhaps we should have a script that checks if the uploaded documentation contains boot2docker IP addresses

**Comment by SvenDowideit** [comment]
yup, or even better, have the upload.sh script poke around and refuse to upload html that has them..... 

:+1: - I'll look at that after i figure out the empty `index.html` files.

**Comment by thaJeztah** [comment]
This is resolved, so closing
