### ISSUE TITLE
use env in the run command file from the env_file

### ISSUE THREAD

**Issue by krasimir-georgiev** [docker/docker#18346]
I follow up from the docker-compose issue
https://github.com/docker/compose/issues/2482

I use docker compose to deploy 2 servers with the same compose file and the only difference are some ENV variables set in an external env file which is not tracked in git

docker run -p ${INTERNAL_IP}:222:222 --env-file ./env.list lsyncd 
where INTERNAL_IP is set in the env file

$ cat ./env.list
INTERNAL_IP=170.0.0.1

in docker-compose it makes a lot more sense , but do you think this would could be implemented in docker so that docker-compose can use the same principal ?

The case is that I use the same docker-compose file to run 2x lsyncd containers to keep some files synced between 2 hosts and the only difference is the ip address they need to connect and listen to.

**Comment by thaJeztah** [comment]
I think you mean that `-p ${INTERNAL_IP}:222:222` uses the ip-address that's defined in the env-file?

**Comment by duglin** [comment]
This would be kind of tricky because in this case ${INTERNAL_IP} is process by the shell, before `docker` ever gets a chance to see it.  In order to support something like this we'd need to invent some other kind of env var syntax to would be ignored by the shell, or I guess just have you escape the "$" so docker sees it.

I suspect this won't get much traction when I think you can do something like:
```
eval $(cat env.list) ; docker run -p ....
```

**Comment by vipconsult** [comment]
It makes much more sense in docker-compose where you can maintain the same file for more than one host and just change the env variables in the external file.
the eval is good workaround but error prone.

**Comment by thaJeztah** [comment]
I think docker-compose is a more logical place to handle this. If we would implement this in docker, it'd probably be client-side; given that compose communicates via the API, it would still need to be implemented in docker-compose as well.

**Comment by vipconsult** [comment]
I thought the same , but @dnephin suggested docker should implement first.

**Comment by vipconsult** [comment]
working on building a  mariadb image and here it would also be useful to use env variables from the env file 
something like 
docker run -d user/mariadb mysqld --wsrep_cluster_address=gcomm://${LB_SERVER}

**Comment by thaJeztah** [comment]
just wondering what your objection is to the example @duglin gave; https://github.com/docker/docker/issues/18346#issuecomment-161091288. In what perspective is the eval error prone?

**Comment by vipconsult** [comment]
that I have to remember to start every image using that extra command.

**Comment by dnephin** [comment]
I think you could use that command as long as you escape the `$` on the command line:

```
docker run -d user/mariadb mysqld '--wsrep_cluster_address=gcomm://${LB_SERVER}'
```

**Comment by vipconsult** [comment]
Thanks I will try

**Comment by vipconsult** [comment]
@duglin - tried your approach but it doesn't work , it needs export name=value instead of just name=value

**Comment by duglin** [comment]
@vipconsult sorry, not sure what I did last time, but this seems to work:
`env $(cat env.list) docker run ...`

**Comment by vipconsult** [comment]
so it wouldn't make sense to have this implemented in docker itself ? 
how do you handle ip bindings in the compose files ? 
I find myself editing the compose file everytime I switch from dev to prod , I can't think of any other way to handle the host ip bindings properly 

for example on my dev machine I can bind nginx to all interfaces as it runs in a VM , but on prod it has more than one ip address so need to specify it in the compose file.

**Comment by LK4D4** [comment]
I think this issue should be handled in compose with some "runtime variables". It would be much more challenging to implement it in docker.
