### ISSUE TITLE
remove dockerinit

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#18355]
the only thing relying on it is https://github.com/docker/libnetwork/blob/9fb7ba8fa01f0ddce99713799e760223c842fb4b/drivers/bridge/setup_bridgenetfiltering.go#L159

cc @rhatdan I think you wanted this as well

cc @tianon

**Comment by jfrazelle** [comment]
ping @mrjana @mavenugo

**Comment by jfrazelle** [comment]
ping @LK4D4 just to make sure that was the only thing hanging for removal

**Comment by jfrazelle** [comment]
gettting this for https://github.com/docker/docker/pull/17989 will help us not need libseccomp.a when compiling the binaries because dockerinit is static, it is trying to find it now

**Comment by rhatdan** [comment]
I am all for this, the only problem I have is a side effect.  Currently one of my patches uses the location of dockerinit to figure out where alternate docker binaries are stored.  /usr/libexec/docker on Red Hat based OS.  /usr/lib/docker on others.

If we had a standard directory for helper executables to be installed...

**Comment by jfrazelle** [comment]
woohooooo we want the same thing <3

**Comment by LK4D4** [comment]
@jfrazelle Yeah, I don't see other places. I never build dockerinit and `/.dockerinit` in container is just empty file.

**Comment by zelahi** [comment]
I would like to take on this issue, but please correct me if I am misinterpreting it

The following file needs to be removed: 
https://github.com/docker/docker/blob/master/dockerinit/dockerinit.go

and the following file needs to be updated to not reference .dockerinit:
https://github.com/docker/libnetwork/blob/9fb7ba8fa01f0ddce99713799e760223c842fb4b/drivers/bridge/setup_bridgenetfiltering.go#L159

**Comment by jfrazelle** [comment]
it touches a lot of places a lot of things will need to be changed in
engine, but awesome you are willing to take it on

**Comment by sammyshj** [comment]
Is anyone working on this issue currently? If no, I would like to work on it.

**Comment by thaJeztah** [comment]
@zelahi are you working on this?

**Comment by zelahi** [comment]
@sammyshj  go ahead and take this one =)

**Comment by sammyshj** [comment]
The dockerinit file is mentioned in [many files](https://github.com/docker/docker/search?q=dockerinit). Should all these references be handled and then the dockerinit file be removed?

**Comment by LK4D4** [comment]
@sammyshj yeah, I think so

**Comment by sammyshj** [comment]
The `dockerinit` file is also referenced in the file https://github.com/docker/docker/blob/master/daemon/container_operations_unix.go#L234
By removing the `dockerinit` file, all of these files also has to be modified. Can I know what the `InitPath` has to be modified into?

**Comment by LK4D4** [comment]
@sammyshj InitPath shouldn't be needed after removing.

**Comment by jfrazelle** [comment]
Ya the files I specified weren't obviously the only ones like I've said
before it's a deep rabbit hole in terms of things it touches and InitPath
is just another thing that removed by removing dockerinit ;) have fun

**Comment by jfrazelle** [comment]
The original file path was merely the only one not in docker/docker so you
might want to start w the PR to libnetwork ;)
THEN you can vendor that change into docker
THEN you can worry about all the other stuff dockerinit touches

**Comment by sammyshj** [comment]
Thanks for making things clear @jfrazelle . Working on it right now!

**Comment by gianarb** [comment]
Maybe this issue should be closed? :) 
The pull is merged :+1:

**Comment by LK4D4** [comment]
@gianarb I think only in libnetwork. There is a long road ahead.

**Comment by mpl** [comment]
@jfrazelle Hi.  I I have some code that used to rely on the presence of /.dockerinit to detect whether it is run in a docker container (If not, log.Fatal with a warning so the users know they're not supposed to run that out of docker). What is the correct/suggested way to perform that sort of detection nowadays please?

**Comment by LK4D4** [comment]
@mpl there is `.dockerenv` file, have no idea what it does though :)

**Comment by thaJeztah** [comment]
@LK4D4 may actually be for that; https://github.com/docker/docker/blob/3d13fddd2bc4d679f0eaa68b0be877e5a816ad53/vendor/src/github.com/docker/libnetwork/drivers/bridge/setup_bridgenetfiltering.go#L159-L162

**Comment by mpl** [comment]
@LK4D4 sgtm, thx. @thaJeztah good point, thanks.

**Comment by tianon** [comment]
Originally, ".dockerenv" was for transmitting the environment variables of
the container across the container boundary -- I would not recommend
relying on its existence either (IIRC, that code you've linked to is the
only reason it still exists).  There's likely something incriminatory
inside /sys/fs/cgroup, but I haven't checked recently.

**Comment by thaJeztah** [comment]
@tianon yes, I thought it was indeed, but doesn't seem to be propagated now

**Comment by mika** [comment]
@tianon so when you've code which previously checked for presence of `/.dockerinit ` what's the proper way to handle this with recent versions of docker nowadays? Should `/proc/1/cgroup` be parsed (as done e.g. by puppet's facter tool) or is there any better/easier way? Thanks for any input :)

**Comment by LK4D4** [comment]
@mika there is `/.dockerenv` :)

**Comment by mika** [comment]
@LK4D4 which tianon recommended to not rely on: " I would not recommend
relying on its existence either (IIRC, that code you've linked to is the
only reason it still exists)" (quoting from https://github.com/docker/docker/issues/18355#issuecomment-220484748)
