### ISSUE TITLE
error running docker-machine env command on Windows

### ISSUE THREAD

**Issue by tonyvu2014** [docker/docker#18359]
I am trying to set up docker machine on Windows and this problem has annoyed me for a few days.

I downloaded and installed DockerToolbox-1.9.1a on my Windows, so it came with Virtual Box version 5.0.10. After that I ran this command to create my virtual machine:

**docker-machine create --driver virtualbox --engine-insecure-registry docker.pre-prod.ss.local:5000 --virtualbox-hostonly-cidr 192.168.99.100/24 mymachine**

Here is what I got:

```
Waiting for machine to be running, this may take a few minutes...
Machine is running, waiting for SSH to be available...
Detecting operating system of created instance...
Detecting the provisioner...
Provisioning created instance...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
WARNING >>>
This machine has been allocated an IP address, but Docker Machine could not
reach it successfully.

SSH for the machine should still work, but connecting to exposed ports, such as
the Docker daemon port (usually <ip>:2376), may not work properly.

You may need to add the route manually, or use another related workaround

This could be due to a VPN, proxy, or host file configuration issue.

You also might want to clear any VirtualBox host only interfaces you are not using
```
The machine was created successfully. So I ran the docker-machine env command:

**docker-machine env --shell=powershell mymachine| Invoke-Expression**

and I got:

```
Error running connection boilerplate: Error checking and/or regenerating the certs: There was
icates for host "192.168.99.100:2376": dial tcp 192.168.99.100:2376: connectex: No connection
target machine actively refused it.
You can attempt to regenerate them using 'docker-machine regenerate-certs name'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.
```

Running **docker version** returned

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      windows/amd64
An error occurred trying to connect: Get http://localhost:2375/v1.21/version: dial tcp
 connection could be made because the target machine actively refused it.
```

Can someone help to point out the direction to fix this issue? It is really annoying to set up docker on Windows. Thank you very much.

**Comment by thaJeztah** [comment]
Thanks for reporting, and sorry that you're having a bad experience getting docker to run on Windows.

I see docker toolbox 1.9.1b with docker-machine 0.5.2 was released a couple of hours ago; https://github.com/docker/toolbox/releases perhaps this issue is fixed, could you give it a try?

Overall, I think this issue is better discussed in the docker-machine issue tracker, because this is an issue with docker-machine, not docker (engine). If 1.9.1b does not resolve your issue, could you open this issue in the docker-machine issue tracker? https://github.com/docker/machine/issues

**Comment by tonyvu2014** [comment]
Hi 
I downloaded the new docker toolbox 1.9.1b and did not encounter this problem any more.  

Thanks

**Comment by thaJeztah** [comment]
Good to hear, @tonyvu2014 thanks for reporting back.

I'll close this issue
