### ISSUE TITLE
Globally exposed ports are unreachable from isolated networks

### ISSUE THREAD

**Issue by oszi** [docker/docker#18354]
Description of problem:
Globally (0.0.0.0) exposed ports are unreachable from isolated networks.

`docker version`:
```
Client:
 Version:         1.9.1-fc23
 API version:     1.21
 Package version: docker-1.9.1-2.git78bc3ea.fc23.x86_64
 Go version:      go1.5.1
 Git commit:      f7c1d52-dirty
 Built:           Fri Nov 20 21:07:14 UTC 2015
 OS/Arch:         linux/amd64

Server:
 Version:         1.9.1-fc23
 API version:     1.21
 Package version: docker-1.9.1-2.git78bc3ea.fc23.x86_64
 Go version:      go1.5.1
 Git commit:      f7c1d52-dirty
 Built:           Fri Nov 20 21:07:14 UTC 2015
 OS/Arch:         linux/amd64

```

`docker info`:
```
Server Version: 1.9.1-fc23
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: journald
Kernel Version: 4.2.6-301.fc23.x86_64
Operating System: Fedora 23 (Cloud Edition)
```

`uname -a`:
`Linux 4.2.6-301.fc23.x86_64 #1 SMP Fri Nov 20 22:22:41 UTC 2015 x86_64 GNU/Linux`

Environment details (AWS, VirtualBox, physical, etc.):
Fedora 23 with iptables, DigitalOcean
Fedora 23 with firewalld, physical 

How reproducible:
100%

Steps to Reproduce:
0. `docker network create test`
1. `docker run -it -p 5000:5000 busybox nc -lp 5000`
3. `docker run -it --net=test busybox nc 172.17.0.1 5000`

Actual Results:
The connection times out. Even if I use a physical interface's IP instead of docker0's.
The inter-network FORWARD DROP rules take precedence over everything so I can't even have a static rule to allow specific traffic.

Expected Results:
The above scenario works if both containers use the default bridge.
I expect the same regardless of which network they're in.
I think those DROP rules should be inserted after the DOCKER chain.

Additional info:
The daemon is running with --icc=false.

If this is the intended behavior, how can I expose a port to all networks using a static IP?

**Comment by coolljt0725** [comment]
I think this should be intended behavior, 
`docker run -it -p 5000:5000 busybox nc -lp 5000` runs a container in network `bridge` and
`docker run -it --net=test busybox nc 172.17.0.1 5000` runs a container in network `test`, these two containers are in different network.

**Comment by mavenugo** [comment]
well.. the intention is to provide the isolation.
But, not for the case where the container exposes a service "externally".
Ideally, this exposed service should be reachable from a container in another network.
But the iptables entries seems to be stricter for networks defined in the same host. We must fix this.
cc @sanimej @aboch

**Comment by sanimej** [comment]
Yes, this is a problem only from within the same host because of the way iptable rules are setup. [libnetwork #776] (https://github.com/docker/libnetwork/issues/776) is opened for the same issue.

**Comment by aboch** [comment]
Is a container running on network 1 only supposed to know the IP address of a container running on network2 only ? 

I think the name resolution has to be considered when evaluating this issue.
AFAIK, until now the containers name resolution is confined to networks where the querying container is attached to.

Just trying to consider all aspects before agreeing that access to exposed services from another network on the same host has to behave as if the service was exposed on another host.

**Comment by oszi** [comment]
@aboch Consider this use-case:
I run a DNS resolver in the default network and forward port 53 to it (-p 53:53/{udp,tcp}). Then every container has its dns server set to the default bridge's static IP (using the --dns option for the daemon).

I'm not saying that the resolver's container should be directly reachable from another network.
Just the forwarded ports on static IPs on the host.

**Comment by aboch** [comment]
@oszi Thanks for the clarification, I understand now the use case.

**Comment by thaJeztah** [comment]
@mavenugo do you know if this is being worked on in libcontainer? (just browsing through the issues on the milestone)

**Comment by aboch** [comment]
@thaJeztah 
I am working on it. Goal is to get it in for 1.10.

**Comment by mavenugo** [comment]
@oszi as discussed before, the intention of user-defined network is to provide isolation by default and that is interfering with the exposed-ports between these networks. The change that is required to make it happen is : https://github.com/docker/libnetwork/issues/875. But,  given the fact that it is adjusting the filter tables ordering, we are not too comfortable taking the change for 1.10 few days before the release (given that we are in RC phase).

But the good news is that, we have a clean workaround and a better news is that, it may already work in your case.

With the recent addition to support embedded DNS, every container connected to a user-defined network will automatically given a DNS server that is managed by docker daemon. This embedded DNS server also accepts additional external servers to help resolve the names not managed by the embedded server. You can pass it by editing the host's `/etc/resolv.conf` with an IP in the host or via the `--dns` flag in daemon opts or per-container opts. This will result in the name resolution request  from within a container to be handled by your container connected to the bridge network. Please give it a try and let us know if that works.

As you can see, we got lucky with your exact case (of sharing the same DNS resolver for multiple user-defined networks).

But for other cases, the workaround is to connect the service offered by the container (that is used by other containers in other networks) to all the network that needs that service using `docker network connect` command. This will make the service reachable via all the containers in other networks as well.

**Comment by mavenugo** [comment]
based on my above comment, we can move this to next release and remove the 1.10 milestone.

@oszi feel free to comment if you have any questions.

**Comment by oszi** [comment]
@mavenugo That's reasonable.
I tried out the embedded DNS and it works well for my use-case.

Just one thing to add: Connecting a container to a network is a bit racey. If `network connect` executes too soon, it fails. If it executes too late, the app might miss it. But that's unrelated to this issue.

**Comment by mavenugo** [comment]
@oszi with 1.10, `network connect` can be used on a created container and not started yet.
i.e, for your case, you can
* create the container using `docker create`
* connect to all other networks that you are interested in using `docker network connect`
* finally start the container using `docker start`

This will eliminate the application timing issue that you mentioned above.

**Comment by oszi** [comment]
Nice, thank you.

**Comment by oszi** [comment]
So I'm using 1.11.2 now and this issue isn't completely fixed.
Forwarded ports can be accessed now but only on the docker bridges' internal IP (e.g. 172.17.42.1).
The same ports cannot be accessed on the host's public IP - not even from the default network.
I can work around this with DNS rebinding but it isn't ideal. :)

**Comment by thaJeztah** [comment]
@mavenugo ^^
