### ISSUE TITLE
Changing the ZFS Parent Dataset

### ISSUE THREAD

**Issue by Schlesiger** [docker/docker#18356]
docker version:

    1.9.1

docker info: 

    Containers: 0
    Images: 0
    Server Version: 1.9.1
    Storage Driver: zfs
     Zpool: rpool
     Zpool Health: ONLINE
     Parent Dataset: rpool/root
     Space Used By Parent: 1302740992
     Space Available: 45657931776
     Parent Quota: no
     Compression: lz4
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 4.2.0-1-amd64
    Operating System: Debian GNU/Linux stretch/sid (containerized)
    CPUs: 8
    Total Memory: 31.33 GiB
    Name: media
    ID: A7CG:V76D:SAQD:IVLS:AXUJ:KORA:CIWS:W3ZE:4JT6:OBTP:A5OI:KCIJ
    WARNING: No memory limit support
    WARNING: No swap limit support

uname -a:

    Linux media 4.2.0-1-amd64 #1 SMP Debian 4.2.6-1 (2015-11-10) x86_64 GNU/Linux

This is running on a physical machine.

I am following this guide to change the ZFS parent dataset under Debian Stretch and a root ZFS pool:

https://docs.docker.com/engine/userguide/storagedriver/zfs-driver/#configure-zfs-for-docker

The instructions, however, do not work. Docker always seems to use the root dataset and this causes issues with GRUB and other applications for me. I believe the instructions are either incorrect or this is a bug.

**Comment by thaJeztah** [comment]
ping @Mic92 (who implemented the graphdriver) and @nigelpoulton (who wrote the guide in the docs)

Thanks for reporting @Schlesiger! (I don't have experience with the zfs driver myself :blush:)

**Comment by nigelpoulton** [comment]
@Schlesiger if you let me know a bit more about your config etc I'll run through it and see if I can see any potential issue with the docs and plan some updates etc...

**Comment by Mic92** [comment]
Was the zfs dataset actually mounted?
Please give me the output of:

```
$ zfs mount
```

The parent dataset can be also specified by passing zfs.fsname to the docker daemon:

```
docker --storage-opt zfs.fsname=zroot/root/docker
```

**Comment by Schlesiger** [comment]
@Mic92 Bingo! I had purged docker-engine before trying to change the dataset but `/var/lib/docker` wasn't removed by `apt-get purge docker-engine`. I tried 

    rm -R /var/lib/docker
    zfs mount -a
    apt-get install docker-engine
    service docker start
    docker info

and the parent data set is correct:

     Parent Dataset: rpool/docker

I had tried passing the `--storage-opt` as well and tried adding it to `/etc/default/docker`, but neither seemed to work.

In any case, it's working now. Thanks!

**Comment by thaJeztah** [comment]
@Schlesiger does the documentation need updating? Or is it something you missed in the docs?

**Comment by nigelpoulton** [comment]
I reckon the docs could do with a note or a bullet in the pre-reqs that says something along the lines of - 

"if /var/lib/docker already exists this needs to be blown away. And also... if you've got images you want to keep.... make sure to push them to Docker Hub/DTR before blowing this away".

LMK if you agree.

**Comment by thaJeztah** [comment]
@nigelpoulton sgtm, won't hurt to warn people there.

**Comment by Mic92** [comment]
@nigelpoulton I like the docs btw.

**Comment by nigelpoulton** [comment]
@Mic92 the damage is done, I'm crying in the corner ;-)  To be fair though we need need feeback like this to make them better.  

Thanks BTW.

**Comment by Schlesiger** [comment]
I'm not an APT packaging expert, but I thought a `apt-get purge docker-engine` would have removed all docker files, including `/var/lib/docker`.

**Comment by thaJeztah** [comment]
@Schlesiger nope, it doesn't in this case; iirc there was some discussion on that, but I think the outcome was that user created files should not be deleted by apt-get purge. Also see; http://docs.docker.com/engine/installation/ubuntulinux/#uninstallation

**Comment by Schlesiger** [comment]
Ahh very good; makes sense. Could that also be linked somewhere in the ZFS docs? That would be useful in a situation like mine where ZFS was installed and an individual decided later to change the dataset. The expectation is that `apt-get purge` would remove those files. Thanks!
