### ISSUE TITLE
syslog logging does not seem to work over TLS (TCP)

### ISSUE THREAD

**Issue by cancan101** [docker/docker#18358]
I have set up a syslog [log destination with TLS support](http://help.papertrailapp.com/kb/configuration/encrypting-remote-syslog-with-tls-ssl/), but log data does not make it to the destination. I am using:
```
docker run -it --log-driver=syslog --log-opt syslog-address=tcp://logsXXX.papertrailapp.com:YYYYYY  busybox echo "alex"
```
If I change the destination from `Accepting TCP (TLS)` to `Accepting TCP (plain text)`, then I do see log data appearing.

```
$ docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 18:01:15 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 18:01:15 UTC 2015
 OS/Arch:      linux/amd64
```
```
$ docker info
Containers: 28
Images: 38
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 94
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.10-boot2docker
Operating System: Boot2Docker 1.8.3 (TCL 6.4); master : af8b089 - Mon Oct 12 18:56:54 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: dev
ID: T33K:5CAM:IHRC:4XUK:ZLPE:ECCK:7Z5Y:QNUF:KW66:K3RU:23FB:ATFC
Debug mode (server): true
File Descriptors: 11
Goroutines: 18
System Time: 2015-12-02T03:38:28.079290194Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: dnadocker
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```
```
$ uname -a
Darwin Alexs-MacBook-Pro-4.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
```

**Comment by LK4D4** [comment]
Golang syslog package doesn't seem to have TLS support. Also in your link it's seems that you should use local syslog daemon to send logs over TLS to remote.

**Comment by cancan101** [comment]
Okay, I just posted the issue with gloang.

**Comment by LK4D4** [comment]
@cancan101 thanks! Feel free to open feature request when it'll be available.

**Comment by cancan101** [comment]
@LK4D4 upstream does not seem interested in adding TLS support.

**Comment by thaJeztah** [comment]
Hm;

> We have no plans to further develop the log/syslog package in the standard library.
> We welcome the community to fork it and give it features elsewhere. It was probably a mistake putting > it in the standard library to begin with.

That sounds troublesome on its own, looks like they don't plan to really maintain the package.

**Comment by sirsean** [comment]
Here is a Golang syslog library that has TLS support: https://github.com/RackSec/srslog

We forked the original package from the standard library and added TLS support.

**Comment by thaJeztah** [comment]
@sirsean can you comment that on this issue: https://github.com/docker/docker/issues/18364?

**Comment by thaJeztah** [comment]
oh, see you just did, sorry!
