### ISSUE TITLE
networking API: bad HTTP status reporting on errors

### ISSUE THREAD

**Issue by fsouza** [docker/docker#18363]
Currently the networking API always report 500 on failures (except in [special cases when the error message matches certain patterns](https://github.com/docker/docker/blob/e75da4b6fffbcf9dab86cd581e962a19d3efa35a/api/server/httputils/httputils.go#L129-L151)). Should HTTP handlers in the networking API use the [errcode package](https://godoc.org/github.com/docker/distribution/registry/api/errcode)? If so, I can prepare a patch for that.

**Comment by thaJeztah** [comment]
heh, that code has been topic of quite some discussions :smile:

I'l /cc @mavenugo (for libnetwork / networking API) and @duglin (who's been busy on changing error-handling)

**Comment by duglin** [comment]
yea, in general it would be better to have more well defined error types

**Comment by cpuguy83** [comment]
@fsouza I don't think libnetwork should use errcode itself, but we should inspect the errors returned (which are pretty well typed from libnetwork from what I've seen recently) and produce errcode errors for the HTTP API.

**Comment by fsouza** [comment]
@cpuguy83 sure. In this part of the code, for example, for handling 409 on network creation: https://github.com/docker/docker/blob/e75da4b6fffbcf9dab86cd581e962a19d3efa35a/api/server/router/network/network_routes.go#L99-L101.

**Comment by cpuguy83** [comment]
@fsouza Correct.

**Comment by fsouza** [comment]
@cpuguy83 should I prepare a patch then? Or is anyone else going to work on that?

**Comment by thaJeztah** [comment]
I think it'd be great if you want to contribute, thanks! I did ask on the internal Slack channel to check if no-one of the network team was working on this already, just to be sure

**Comment by mavenugo** [comment]
@fsouza @thaJeztah thanks. we are not currently working on this. Will certainly help review a PR if made available.

**Comment by fsouza** [comment]
Would something like that work?

```patch
diff --git a/api/server/router/network/network_routes.go b/api/server/router/network/network_routes.go
index f639481..28613c1 100644
--- a/api/server/router/network/network_routes.go
+++ b/api/server/router/network/network_routes.go
@@ -8,6 +8,7 @@ import (
        "golang.org/x/net/context"

        "github.com/Sirupsen/logrus"
+       "github.com/docker/distribution/registry/api/errcode"
        "github.com/docker/docker/api/server/httputils"
        "github.com/docker/docker/api/types"
        "github.com/docker/docker/daemon"
@@ -93,7 +94,10 @@ func (n *networkRouter) postNetworkCreate(ctx context.Context, w http.ResponseWr
        }
        if nw != nil {
                if create.CheckDuplicate {
-                       return libnetwork.NetworkNameError(create.Name)
+                       return errcode.Error{
+                               Code:    http.StatusConflict,
+                               Message: libnetwork.NetworkNameError(create.Name).Error(),
+                       }
                }
                warning = fmt.Sprintf("Network with name %s (id : %s) already exists", nw.Name(), nw.ID())
        }
```

Asking before applying such a solution to other handlers and send the pull request.

**Comment by thaJeztah** [comment]
ping @mavenugo @cpuguy83 ^^ thanks!

**Comment by cpuguy83** [comment]
@fsouza Looks good!
One thing is we currently register errors in the package in `errors/`, and then call something like `return derr.NetworkNameConflict.WithArgs(create.Name)`

**Comment by fsouza** [comment]
@cpuguy83 what's the preferred way of detecting that a network doesn't exist in this http handler, for example: https://github.com/fsouza/docker/blob/master/api/server/router/network/network_routes.go#L58-L68?

I already did the conflict change on postNetworkCreate, but I'm confused about other errors. Thank you!

**Comment by cpuguy83** [comment]
@fsouza 
```go
if _, ok := err.(libnetwork.ErrNoSuchNetwork); ok {
     ... 
}
```

or
```go
switch err.(type) {
case libnetwork.ErrNoSuchNetwork:
    ...
}
```

**Comment by LK4D4** [comment]
I'm closing this issue in efforts to make issues list cleaner. Feel free to open PR.
