### ISSUE TITLE
Enhancement: docker images --format

### ISSUE THREAD

**Issue by sumkincpp** [docker/docker#18360]
Would be great to have a similar one to [docker ps --format](https://docs.docker.com/engine/reference/commandline/ps/#formatting) option.

**Comment by thaJeztah** [comment]
Thanks for suggesting!

Actually, this is already being worked on for docker 1.10; see the pull request here; https://github.com/docker/docker/pull/17692

I'll link that PR to this issue so that it'll automatically close once the PR is merged! \o/

**Comment by sumkincpp** [comment]
Great, thanks! 
Strangely I missed to find this case.
