### ISSUE TITLE
Replace Golang log/syslog pkg because it's no longer actively developed

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#18364]
Following the discussion on https://github.com/docker/docker/issues/18358, it appears that Golang has decided to stop development of the log/syslog package;

From https://github.com/golang/go/issues/13449;

>We have no plans to further develop the log/syslog package in the standard library.
> We welcome the community to fork it and give it features elsewhere.
> It was probably a mistake putting it in the standard library to begin with.

We should look for another package to replace it.

**Comment by unclejack** [comment]
I think it should be removed from the stdlib if no further (maintenance and development) is planned for it. There's no point to have it in there if it's known to have serious problems and shortcomings.

**Comment by thaJeztah** [comment]
@unclejack yup I agree, but not really our concern.

I thought it was worth considering to move to something else, because of that decision though, so if you have suggestions for a good package that can be used instead, that'd be great. Possibly we can solve https://github.com/docker/docker/issues/18358 at the same time

**Comment by calavera** [comment]
is there any alternative package already? we can always keep our own, but it makes me sad.

**Comment by thaJeztah** [comment]
@calavera I haven't looked yet

**Comment by sirsean** [comment]
Here's an alternative if you still need it: https://github.com/RackSec/srslog

We forked the original syslog package from the standard library and added TLS support to it.

**Comment by LK4D4** [comment]
@sirsean looks cool, I think we can use it.

**Comment by calavera** [comment]
I opened a PR to replace it and add TLS support #18998
