### ISSUE TITLE
Content addressability migration takes way too long to be serial

### ISSUE THREAD

**Issue by tianon** [docker/docker#18370]
I've got a machine with thousands of layers on it (and it's actually at a low right now because I recently nuked `/var/lib/docker`; in my experience with enterprise clients this volume of images isn't really unusual, especially if they've been doing a lot of `docker build`s, etc) that I finally upgraded to latest master today, and the migration process took a full hour and 23 minutes.  Even a really dramatic increase in speed is not going to be enough to make the amount of downtime palpable, so we need to come up with other options.

```console
$ docker info
Containers: 4
Images: 3842
```

What I'd personally love to see (if it's plausible) is to have some kind of async migration queue, and have images get pushed to the top of the queue as they're necessary/requested, but I don't know whether that's even feasible.

At the bare minimum, we'll need to communicate this issue very widely with the 1.10 release, and hopefully have some kind of online migration tool that can be run before restarting.  I think we'll also need to include some way to go the other direction, if we can, to ensure users can downgrade if they run into other related or unrelated issues with the 1.10 release.

cc @tonistiigi @vbatts @LK4D4

**Comment by LK4D4** [comment]
ping @aaronlehmann also

**Comment by tonistiigi** [comment]
I've optimized the migration process in https://github.com/docker/docker/compare/master...tonistiigi:migration-opt . In my test with 4GB test-data the improvement is ~55%. Its waiting on https://github.com/vbatts/tar-split/pull/22 before I make a PR. Note that direct access for overlay is currently not working as well.

The alternative we hope to provide is a migration tool that can be ran while daemon is still running with old version. The initial version is in https://github.com/tonistiigi/docker-v1.10-migrator

**Comment by tonistiigi** [comment]
@tianon What graphdriver do you use and how big was the graph directory?

**Comment by cpuguy83** [comment]
I'd also say +1 to the queue as I mentioned elsewhere.
Especially for built images, we don't really need the sha until it's pushed -- seems like we can get around this.

**Comment by aaronlehmann** [comment]
> Especially for built images, we don't really need the sha until it's pushed -- seems like we can get around this.

I'm actually not sure that's the case. The new model is built around content addressable layers. Walking that back to make exceptions for layers that haven't been migrated yet might make the code a lot more complex and introduce bugs. Even if we pulled it off, it would cause weird behaviors, like image IDs changing underneath a running system as images are migrated. Maybe there's a clever way to do this that doesn't introduce too much weirdness, but I'm concerned about handling all the corner cases correctly.

**Comment by tianon** [comment]
@tonistiigi not sure how large it was before the migration, but after it's 122G; this machine is overlayfs, but I remember my AUFS machine had a pretty long migration time too (although that migration was longer ago, so I don't have useful stats on it anymore :disappointed:)

**Comment by tonistiigi** [comment]
@tianon You can try `https://github.com/tonistiigi/docker-v1.10-migrator` for a comparison(if you haven't upgraded to #18399). Still I think, the big problem here is the diff algorithm for self-built images.

**Comment by ibuildthecloud** [comment]
+1 Just experienced this myself.  It would be nice if migration was a background task where if needed the migration will happen on demand if the image needs to be used now.

**Comment by icecrime** [comment]
Labeling this as P0 to make sure we come up with a satisfactory answer in time for 1.10.

Currently, the strategy is to provide an out-of-band migration tool and communicate that you should be using it in order to bring upgrade downtime down to a couple seconds. I don't think we'll need background migration or anything that fancy, but I might be wrong.

**Comment by icecrime** [comment]
This is the [draft of a document](https://gist.github.com/icecrime/77757cdc80a40e920982) we'd like to publish alongside 1.10 (ideally RC1) to assist people with the migration. Can you please let us know if you think that's a good enough answer?

**Comment by tianon** [comment]
Nice, I think that's a really excellent summary of all the cool background
information about why this is important and answers the most important
question(s) of "what does this mean for me/what should I do with my servers
to ensure minimized downtime?" :smile: :+1:

**Comment by icecrime** [comment]
@tianon Cool thanks! (_and now you know we might soon ask for a new official image_ :innocent:)

**Comment by tianon** [comment]
Heh, what's wrong with leaving it under `/u/docker` or `/u/dockercore` so it's really obvious that it's specific to Docker itself?

**Comment by tianon** [comment]
ie, IMO `docker run docker/v1.10-image-migrator` is much more clearly "provided by Docker" than `docker run docker-v1.10-image-migrator` or similar is

**Comment by thaJeztah** [comment]
good point; `docker/` already makes it "official"

**Comment by icecrime** [comment]
Oh yes, SGTM.

**Comment by cyphar** [comment]
I feel like if we made migrations occur when the layers are required (on-demand) it would massively reduce downtime. You could optionally then run the migration tool to fully migrate all remaining layers. The only question is whether it's entirely practical to implement it this way.

**Comment by icecrime** [comment]
@cyphar It would surely reduce the initial startup time, but the trade-off for lazy migration is that the first container for that giant image that you haven't migrated yet might take minutes.

Ultimately, I think it really boils down to this question: can I accept a non-deterministic migration hit or not? If yes, regular upgrade is fine. If not, you _will_ want to run the migration tool. I'm not convinced yet we need to account for anything in between.

**Comment by cyphar** [comment]
@icecrime Fair enough. To be honest, on my dev machine (where I've been bisecting Docker quite a lot recently), I've opted to nuke `/var/lib/docker` quite a lot because of the really slow start up time when jumping between `1.9.1` and `1.10-dev`. But that's not a common usecase :smile_cat:.

**Comment by icecrime** [comment]
Thank you all <3 I'll close this one and will see what RC testers have to say about it.

**Comment by thaJeztah** [comment]
Wiki page on this is here; https://github.com/docker/docker/wiki/Engine-v1.10.0-content-addressability-migration
