### ISSUE TITLE
Proxy changed, but docker doesn't change it

### ISSUE THREAD

**Issue by drngsl** [docker/docker#18386]
Hi, I'd like to make a question.
My host need a proxy to connect to external network, and proxy 192.199.100.123 is distributed to it.
Now, for some reason, the proxy changed, and I modify the config file to adapt to it. However, when I execute cmd 
docker pull mysql
I get the following error
root@ubuntu50:~# docker pull  mysql
Using default tag: latest
Pulling repository docker.io/library/mysql
Error while pulling image: Get https://index.docker.io/v1/repositories/library/mysql/images: http: error nnecting to proxy http://192.199.100.138:808: dial tcp 192.199.100.138:808: i/o timeout
The proxy that Docker uses doesn't change.
Even if I restart the Docker service, it doesn't make any sense.

So, What need I to do to resolve it?

`docker version`:
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

**Comment by thaJeztah** [comment]
So, if I understand correctly, 192.199.100.138 is not the IP address of the proxy you configured in the configuration file? Are you sure you modified the right file?

If your system is using systemd, did you `systemctl daemon-reload` before restarting the service? Otherwise systemd won't pick up changes you made

**Comment by drngsl** [comment]
@thaJeztah ,sorry, it's my fault. the proxy now is 192.199.100.123.
but my host is ubuntu, so what command can replace systemctl daemon-reload ?

**Comment by thaJeztah** [comment]
It depends on the version of Ubuntu if that uses systemd or upstart ununtu 14.10 and lower use upstart, higher use systemd

**Comment by drngsl** [comment]
@thaJeztah , thanks!
I may resolve it.
Previously, I just kill docker daemon process, now I use cmd "service docker restart", it make sense.
I forget whether used this cmd ever.

**Comment by thaJeztah** [comment]
Cool, good to hear you resolved it; killing the docker is not the best way to do that, because it may lead to corruption of files that the daemon writes to, also there's a chance that child processes are not "reaped" properly.
