### ISSUE TITLE
Proposal: ARCH statement in builder

### ISSUE THREAD

**Issue by jhowardmsft** [docker/docker#18383]
Currently, it's not possible to have a cross-architecture dockerfile. This can be evidenced by the docker CI itself where the main image built downloads busybox (linux/amd64) in the dockerfile. Subsequently hoops are jumped through during test-integration-cli which ends up in .ensure-frozen-images to download/update/tag the linux/arm images to ARM specific ones.

This architecture problem obviously also applies to Windows as well, but is not a Windows specific proposal. I suggest using golang build-style directive-type syntax as a preface to a command. So a dockerfile might contain something like

```
ARCH !windows: COPY linux.sh /runthis.sh
ARCH windows: COPY windows.cmd /runthis.cmd
ARCH !windows: ENTRYPOINT /runthis.sh
ARCH windows: ENTRYPOINT /runthis.cmd
```
or some more complex examples using the golang type and/or syntax

```
ARCH linux,freebsd 386: <somecommand>
```

**Comment by duglin** [comment]
if we're going to add some kind of conditional logic I would prefer if we made it more feature-rich and add real `if`-like statements so that the conditions can be based on what's meaningful to the Dockerfile developer and not just what *we* as Docker devs consider important.  Even just simple comparison of env vars would be good enough for lots of uses.

But of course, the Dockerfile syntax is frozen for now  :-)

**Comment by jhowardmsft** [comment]
@tiborvass Interested in your opinion here too. Thanks.

**Comment by jhowardmsft** [comment]
@jfrazelle @mikedougherty as this was thought of in the context of CI flakiness debugging.

**Comment by mikedougherty** [comment]
@jhowardmsft thanks for the ping. This is interesting! There definitely seems to be a need for this functionality, but something about the boolean/conditional syntax has a bad smell to me. Even sprinkling in `if`s as @duglin mentioned also doesn't sound right. My first instinct would be that there should be different Dockerfiles for each arch, but that also seems wrong as it would just result in duplicated Dockerfiles (except for the `FROM` line) in many cases. Unfortunately I've got no real alternative to offer, so I guess I'll look forward to following this discussion :)

**Comment by thaJeztah** [comment]
I think having multiple architectures (the example here looks more related to different operating systems) might become very confusing in a single Dockerfile, especially in cases where windows and linux are mixed. I think so far consensus was to use different Dockerfiles.

Having said that; if only small differences are needed, could we resolve this with build-time args? https://github.com/docker/docker/pull/15182

**Comment by LK4D4** [comment]
I'm going to close it because everyone lost interest. Feel free to open again if it's still a problem.

**Comment by jhowardmsft** [comment]
@LK4D4 Absolutely, right call :smile:
