### ISSUE TITLE
panic: nil pointer dereference when waiting on a container

### ISSUE THREAD

**Issue by jake-low** [docker/docker#18380]
I don't have a consistent repro for this one but I'm seeing it occasionally when `^C`-ing containers attached to overlay networks.

Novice question: is this bug even in the docker engine? Maybe I should open this bug against libnetwork, or perhaps serf?

```
$ uname -a
Linux thumper 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux
```

```
$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   a34a1d5-dirty
 Built:        Sun Nov 22 00:15:15 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   a34a1d5-dirty
 Built:        Sun Nov 22 00:15:15 UTC 2015
 OS/Arch:      linux/amd64
```

```
$ docker info
Containers: 43
Images: 182
Server Version: 1.9.1
Storage Driver: btrfs
 Build Version: Btrfs v4.3.1
 Library Version: 101
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.5-1-ARCH
Operating System: Arch Linux (containerized)
CPUs: 32
Total Memory: 31.33 GiB
Name: thumper
ID: 5QXK:WEEY:BFL4:TPNR:3K7E:SQHG:3NXO:7BYZ:H3V2:4OZW:E7L3:RHP7
Username: jakelow
Registry: https://index.docker.io/v1/
Cluster store: consul://127.0.0.1:8500
```

Docker daemon logs:
```
time="2015-12-02T14:13:33.076154755-08:00" level=info msg="POST /v1.21/containers/43dc5cffd38da97465ae01790e251c3ff7bf6a4575cb7c0e812e9868033e722d/wait"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0xd223d4]
goroutine 265 [running]:
github.com/hashicorp/serf/serf.(*Serf).Query(0x0, 0x1489690, 0xa, 0xc820a8b590, 0x46, 0x50, 0x0, 0x3, 0x0, 0x0)
/build/docker/src/docker/vendor/src/github.com/hashicorp/serf/serf/serf.go:443 +0x44
github.com/docker/libnetwork/drivers/overlay.(*driver).resolvePeer(0xc820238c80, 0xc82089b0c0, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/build/docker/src/docker/vendor/src/github.com/docker/libnetwork/drivers/overlay/ov_serf.go:155 +0x2bb
github.com/docker/libnetwork/drivers/overlay.(*network).watchMiss(0xc82083ae10, 0xc820bc82a0)
/build/docker/src/docker/vendor/src/github.com/docker/libnetwork/drivers/overlay/ov_network.go:272 +0x6e8
created by github.com/docker/libnetwork/drivers/overlay.(*network).initSandbox
/build/docker/src/docker/vendor/src/github.com/docker/libnetwork/drivers/overlay/ov_network.go:241 +0x50b
```

Nothing interesting in the consul agent logs.

**Comment by LK4D4** [comment]
ping @mrjana @aboch

**Comment by mrjana** [comment]
@jake-low Thanks for the bug report. It's not a bug in `serf`. It's a bug in `libnetwork`. We will fix it shortly. Out of curiosity, what kind of container where you running in overlay network (or more specifically what kind of traffic was the app generating)?

**Comment by mrjana** [comment]
@jake-low Also, are you running your daemon without the `cluster-advertise` option? It seems like a problem which will happen in that case

**Comment by jake-low** [comment]
@mrjana the application was generating HDFS traffic (TCP-based file access protocol related to Hadoop), and not a whole lot of it: the container is a protocol unit test app written in Python's pytest framework, so it runs serially and only executes a few (thousand) operations.

I was not using the `cluster-advertise` option. I'm under the impression this option is only needed for multi-host overlay networking. I'm using overlay networks because I need the 'magic' DNS semantics, but for now I'm only running containers on a single host.

**Comment by mrjana** [comment]
@jake-low If you just want the 'magic' DNS, and your workloads are in a single host you can just create a network with bridge driver (which is the default if you didn't provide the `-d` option while creating a network) and you won't get into the problem that you reported(which we will fix nevertheless)

**Comment by jake-low** [comment]
@mrjana To clarify, by "magic" I mean this:

```
# disclaimer: untested, might have typos

foo:
  image: busybox:latest
  command: sleep 60

bar:
  image: busybox:latest
  command: ping foo
```

`docker-compose --x-networking --x-network-driver overlay up` will result in `bar` being able to resolve (and ping) `foo`; but this doesn't work on the default bridge network (unless I did something wrong in my ad-hoc test).

I'll work around the problem for now; thanks for your help!

**Comment by thaJeztah** [comment]
@jake-low it doesn't work on the *default* bridge network, but should work on a custom network `docker network create mybridge`. Alternatively, you can still use "links"

**Comment by thaJeztah** [comment]
@mrjana is there an issue in libnetwork tracking this?

I'll add this to the 1.9.2 milestone, which we will be discussing later today

**Comment by mrjana** [comment]
@thaJeztah Just pushed https://github.com/docker/libnetwork/pull/799 to fix this

**Comment by thaJeztah** [comment]
Thanks @mrjana

**Comment by jake-low** [comment]
> it doesn't work on the default bridge network, but should work on a custom [bridge] network

@thaJeztah: Wow, I wasn't aware of that distinction, and it's immensely useful to me. Thanks for explaining!
