### ISSUE TITLE
git tag issue in upstream

### ISSUE THREAD

**Issue by hqhq** [docker/docker#18390]
When I want to know a patch was introduced in which version, `git describe` is a wonderful way, but I noticed that in upstream, almost all commits I checked with `git describe` returned v1.4.1-xxx-xxx.

I found it's because after v1.4.1, we never add tags in upstream, all tags are in separate branches, and most of them are no longer existed.

Is there any chance we can retag upstream so we can use `git describe` again? I think tags like `1.9.0` can be tagged on upstream, while we can leave `1.9.1` in release branches.

**Comment by calavera** [comment]
Sorry, we don't have any plan to do this in the near future. I'm going to close this issue.
