### ISSUE TITLE
Setting --kernel-memory value too low can make the parent process crash

### ISSUE THREAD

**Issue by abronan** [docker/docker#18405]
Related to #18272 

So, setting the `--kernel-memory` to a ridiculously low value (like 10/100 bytes) will either end up with `cannot start container: broken pipe` or occasionally make a random process crash (triggers the OOM killer). Ultimately we saw that on Jenkins because it was regularly killing the Jenkins Slave process after the behavior was fixed in docker (value seemed to be ignored before) and after accidentally forgetting the unit (M) for the `--kernel-memory` value.

We should probably check with a better error saying that the kernel-memory value is set too low. Ultimately it's common sense to set this to an acceptable value but adding a better error scheme would help troubleshoot in case this value is set too low as it will likely trigger the OOM killer. Or a warning? (even though we have too many of them already). Don't know if this makes sense. Feel free to close if this is the expected behavior.

**Some more infos**:
```
$ uname -a
Linux archbox 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux
```

**docker info**:
```
$ docker info
Containers: 1
Images: 196
Server Version: 1.10.0-dev
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.5-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.6 GiB
Name: archbox
ID: XK7O:JOMU:IYUU:DYT5:XND2:ZIQT:NY36:IKQX:C4MY:JWZP:MFAL:ABNP
Username: abronan
Registry: https://index.docker.io/v1/
Experimental: true
Cluster store: consul://localhost:8500
Cluster advertise: 127.0.0.1:2375
```

**docker version**:
```
$ docker version
Client:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   580534b
 Built:        Thu Dec  3 01:49:17 2015
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   580534b
 Built:        Thu Dec  3 01:49:17 2015
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by hqhq** [comment]
#debs 
Yeah we should check the minimum as memory limit does.
