### ISSUE TITLE
Docker image tags start with slash (`/`)

### ISSUE THREAD

**Issue by sedrubal** [docker/docker#18406]
Description of problem:
------------------------------

Docker always adds a `/``in front of the tag names.

- When I run `docker build -t image .`, a image called `/image` will be visible in `docker images`:

```
REPOSITORY                              TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
/image                                  latest              38ffe511a292        8 minutes ago       271.5 MB
```

- `docker rmi /image` returns:

```
EOF
Error: failed to remove images: [/image]
```
and failes

`docker version`:
----------------------

```
Client:
 Version:         1.9.1-fc23
 API version:     1.21
 Package version: docker-1.9.1-2.git78bc3ea.fc23.x86_64
 Go version:      go1.5.1
 Git commit:      f7c1d52-dirty
 Built:           Fri Nov 20 21:07:14 UTC 2015
 OS/Arch:         linux/amd64

Server:
 Version:         1.9.1-fc23
 API version:     1.21
 Package version: docker-1.9.1-2.git78bc3ea.fc23.x86_64
 Go version:      go1.5.1
 Git commit:      f7c1d52-dirty
 Built:           Fri Nov 20 21:07:14 UTC 2015
 OS/Arch:         linux/amd64
```

`docker info`:
-----------------

```
Containers: 2
Images: 181
Server Version: 1.9.1-fc23
Storage Driver: devicemapper
 Pool Name: docker-253:2-5770-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 9.917 GB
 Data Space Total: 107.4 GB
 Data Space Available: 17.2 GB
 Metadata Space Used: 13.64 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.134 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.109 (2015-09-22)
Execution Driver: native-0.2
Logging Driver: journald
Kernel Version: 4.2.6-301.fc23.x86_64
Operating System: Fedora 23 (Twenty Three)
CPUs: 4
Total Memory: 7.682 GiB
```

`uname -a`:
---------------

```
Linux <hostname> 4.2.6-301.fc23.x86_64 #1 SMP Fri Nov 20 22:22:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.):
--------------------------------------------------------------------

*On my physical Laptop.*

How reproducible:
-----------------------

*Every time*

Steps to Reproduce:
---------------------------

1. Run `docker build -t test .` with a Dockerfile like this: `FROM ubuntu:14.04`
2. Run `docker images`
3. Run `docker build -t foo .` with a Dockerfile like this: `FROM test`
4. Run `docker images`
5. Run `docker rmi /test`
6. Run `docker rmi test foo`

Actual Results:
-------------------

1. works, but:
2. you can see `/test`
3. works, it takes `/test` or `test`
4. you can see `/test` and `/foo`
5. failes with message:

```
EOF
Error: failed to remove images: [/test]
```

6 . works and removes both images and neither `test` nor `/test` is visible...

Expected Results:
-----------------------

2. image should be named `test`
4. image should be named `foo`

Additional info:
-------------------

 I think since I have upgraded from `docker.x86_64 1:1.8.2-14.git8f9eabc.fc23` -> `docker.x86_64 1:1.9.1-2.git78bc3ea.fc23`

**Comment by thaJeztah** [comment]
I think you're running a docker version that's build by Red Hat; `f7c1d52-dirty` (the `-dirty` indicates that modifications/patches were made to the source)

@rhatdan is this a known issue?

**Comment by rhatdan** [comment]
Please open a bugzilla on this.  Don't know if this is a known issue or not.

**Comment by sedrubal** [comment]
@rhatdan do  you mean this bugzilla: https://bugzilla.redhat.com ? If so, to which [classification](https://bugzilla.redhat.com/enter_bug.cgi?classification=__all) belongs this issue?

**Comment by rhatdan** [comment]
Yes, just open a bug on docker in Fedora, and I will get someone to look at it.

**Comment by sedrubal** [comment]
Ok. Here it is: https://bugzilla.redhat.com/show_bug.cgi?id=1289792

**Comment by thaJeztah** [comment]
Given that this looks to be an issue in the Fedora packaged version, are you okay with closing this issue here, @sedrubal?

**Comment by sedrubal** [comment]
Yes of course, if you think so... Thanks for your help.
