### ISSUE TITLE
Same container but different run behaviour

### ISSUE THREAD

**Issue by sgonzalezO** [docker/docker#18407]
Description of problem:
I've builded an image and then I exported (docker save) to a .tar file. Then I loaded (docker load) the image from the .tar file to two different hosts. When I run the container on host1 everything works the right way, but it doesn't on host2.

Docker version, Docker info and Kernel version on Host1:  (This is a KVM Debian 8 virtual machine)

>VERSION

>Client:
 >Version:      1.8.3
 >API version:  1.20
 >Go version:   go1.5.1
 >Git commit:   f4bf5c7
 >Built:        
 >OS/Arch:      linux/amd64

>Server:
 >Version:      1.8.3
 >API version:  1.20
 >Go version:   go1.5.1
 >Git commit:   f4bf5c7
 >Built:        
 >OS/Arch:      linux/amd64

>INFO

>Containers: 2
>Images: 18
>Storage Driver: devicemapper
> Pool Name: docker-8:1-2-pool
 >Pool Blocksize: 65.54 kB
 >Backing Filesystem: extfs
 >Data file: /dev/loop0
 >Metadata file: /dev/loop1
 >Data Space Used: 2.559 GB
 >Data Space Total: 107.4 GB
 >Data Space Available: 5.744 GB
 >Metadata Space Used: 2.548 MB
 >Metadata Space Total: 2.147 GB
 >Metadata Space Available: 2.145 GB
 >Udev Sync Supported: true
 >Deferred Removal Enabled: false
 >Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 >Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 >Library Version: 1.02.110 (2015-10-30)
>Execution Driver: native-0.2
>Logging Driver: json-file
>Kernel Version: 4.2.0-040200-generic
>Operating System: Debian GNU/Linux stretch/sid (containerized)
>CPUs: 1
>Total Memory: 993.1 MiB
>Name: debian8
>ID: KTIV:MOFC:KS3G:SQNY:3BRW:SQFT:YX62:E33Z:FANE:2YM7:OMJ3:Q3VD

>IMAGES

>REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
><none>              <none>              906974ea0c0a        33 hours ago        655.1 MB

>CONTAINERS

>CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                    NAMES
>d208f42677c8        9069                "bash"              8 minutes ago       Up 8 minutes        0.0.0.0:4567->4567/tcp   thirsty_heisenberg

>UNAME -A

>Linux debian8 4.2.0-040200-generic #201508301530 SMP Sun Aug 30 19:31:40 UTC 2015 x86_64 GNU/Linux

Docker version, Docker info and Kernel version on Host2: (This is a Google Compute Engine Debian 8 virtual machine)

>VERSION

>Client:
 >Version:      1.8.2
 >API version:  1.20
 >Go version:   go1.4.2
 >Git commit:   0a8c2e3
 >Built:        Thu Sep 10 19:10:10 UTC 2015
 >OS/Arch:      linux/amd64

>Server:
 >Version:      1.8.2
 >API version:  1.20
 >Go version:   go1.4.2
 >Git commit:   0a8c2e3
 >Built:        Thu Sep 10 19:10:10 UTC 2015
 >OS/Arch:      linux/amd64

>INFO

>Containers: 12
>Images: 40
>Storage Driver: overlay
> Backing Filesystem: extfs
>Execution Driver: native-0.2
>Logging Driver: json-file
>Kernel Version: 4.2.0-0.bpo.1-amd64
>Operating System: Debian GNU/Linux 8 (jessie)
>CPUs: 1
>Total Memory: 3.618 GiB
>Name: nodo1
>ID: VJ2B:3FLU:QQJR:W7KF:H2C7:3WQH:GQ2G:2FF2:7MC5:IFSB:Z3K6:SYGH

>IMAGES

>REPOSITORY                           TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
>xxxxxx/javatest                     latest              906974ea0c0a        33 hours ago        655.1 MB

>CONTAINERS

>CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS              PORTS                    NAMES
>c363d08c9676        9069                                        "bash"                   24 hours ago        Up 24 hours         0.0.0.0:4567->4567/tcp   nostalgic_kowalevski

>UNAME -A

>Linux nodo1 4.2.0-0.bpo.1-amd64 #1 SMP Debian 4.2.3-2~bpo8+1 (2015-10-20) x86_64 GNU/Linux

Steps to Reproduce:
1. Build image from dockerfile:

>FROM cogniteev/oracle-java:java8
>MAINTAINER me@xxxxxx.xxx
>RUN mkdir /opt/siscloudrepositoryapy
>WORKDIR /opt/siscloudrepositoryapy
>COPY ./target/siscloudreposirotyapi*.jar /opt/siscloudrepositoryapy/
>COPY ./startup.sh /opt/siscloudrepositoryapy/
>RUN chmod +x /opt/siscloudrepositoryapy/startup.sh
>RUN mkdir /opt/siscloudrepositoryapy/lib
>COPY ./target/lib/*.jar /opt/siscloudrepositoryapy/lib/
>EXPOSE 4567
>CMD /opt/siscloudrepositoryapy/startup.sh

2. Run container on one host (docker run -d -p 4567:4567 ContainerID)
3. Test container (http://localhost:4567/api/me@opencanarias.es/projects)
4. Run container on the host (docker run -d -p 4567:4567 ContainerID)
5. Test container (http://localhost:4567/api/me@opencanarias.es/projects)

Result on host1: {"user":"me@opencanarias.es","applications":[]} 
Result on host2: Alert!: HTTP/1.1 500 class java.lang.NoSuchMethodError

I can upload the container image if anyone want to try.

Thanks.

**Comment by HackToday** [comment]
check your related jvm if quite same version for the two hosts ? seems your program java.lang.NoSuchMethodError.

Did such container cogniteev/oracle-java:java8 not have requirements for host?

**Comment by sgonzalezO** [comment]
What I move from host to host is the docker image and then I run a container. If I'm not wrong, the jvm must be inside the container so it must be the same on both hosts.

I've also tried to make my image from ubuntu and them installed the oracle jvm8 with the same result.

Thanks.

**Comment by thaJeztah** [comment]
What happens if you build the image directly on the failing host (i.e. don't use save/load)? I also see the failing host is using a different docker version (1.8.2 vs 1.8.3), also overlay vs devicemapper.

**Comment by sgonzalezO** [comment]
I have tried building the image on the failing host, the same docker version and the same storage driver with the same result. As soon as I can I'll upload the java files you need to build the image so anyone can test the container.

Thank you very much.

**Comment by sgonzalezO** [comment]
If anyone want to test to see the error:

https://github.com/benitojcv/dockerjavaexample

**Comment by LK4D4** [comment]
Wasn't reported since. Feel free to open new issue if problem still persists. New issue has more chances to get an attention.
