### ISSUE TITLE
There's no info anywhere that Docker doesn't work with Windows x86 and requires x64

### ISSUE THREAD

**Issue by zeird** [docker/docker#18401]
I was quite surprised and disappointed when the installer said that it requires x64.

You should specify this "little" detail somewhere on the Docker site: in filename and on a couple of pages, like [here](https://docs.docker.com/windows/step_one/) and [here](https://www.docker.com/docker-toolbox), I think, so people know that it won't work on their x86 Windows BEFORE they download and try to install Docker.

**Comment by aditirajagopal** [comment]
#dibs
