### ISSUE TITLE
docs: document options for default network driver

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#18410]
The default network driver (I.e. Bridge) has additional options that can be passed when creating a custom network, these options aren't documented (unless I overlooked). We should add the options to the documentation.

For reference, see https://github.com/docker/docker/issues/18237#issuecomment-161737492

**Comment by thaJeztah** [comment]
ping @aboch if you have a document in the libnetwork repository that describes the available options :+1:

**Comment by wenchma** [comment]
@thaJeztah I can claim this :smile:

**Comment by thaJeztah** [comment]
@wenchma feel free to do so! :+1:

**Comment by wenchma** [comment]
I want to wait for this PR: https://github.com/docker/docker/pull/18928 , so `inspect network` can display the complete info.

**Comment by wenchma** [comment]
@thaJeztah can this issue be closed ?

**Comment by thaJeztah** [comment]
@wenchma yes, it can; no idea why GitHub didn't close it automatically. Thanks!
