### ISSUE TITLE
docker reference guide image can not be started

### ISSUE THREAD

**Issue by HackToday** [docker/docker#18429]
$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Follow this guide  https://docs.docker.com/engine/reference/run/
PID setting part: it has reference run "docker run --pid=host rhel7 strace -p 1234"

$ docker run --pid=host rhel7 strace -p 1234
Unable to find image 'rhel7:latest' locally
Pulling repository docker.io/library/rhel7
6883d5422f4e: Download complete 
Status: Downloaded newer image for rhel7:latestr.io/library/rhel7 
docker.io/library/rhel7: this image was pulled from a legacy registry.  Important: This registry version will not be supported in future versions of docker.
exec: "strace": executable file not found in $PATH
Error response from daemon: Cannot start container ed48301d82536e4ff30d83f4c15a146661252fe60ddac50943de21572e01881e: [8] System error: exec: "strace": executable file not found in $PATH

**Comment by HackToday** [comment]
This was test against with #18247

**Comment by HackToday** [comment]
This was test against with #18247

**Comment by thaJeztah** [comment]
Thanks! 

I see the text above that example mentions;

> For example, you could build a container with debugging tools like strace or gdb ....

But we don't actually show that step; I think we should add a small Dockerfile example

Also interesting, a `rhel7` image is used in that example, but it's not listed on Docker hub; https://hub.docker.com/_/rhel7/

Afaik all RHEL images are now hosted on Red Hat's repository because of licensing (but I should check that), so we should update that example to use an image that's actually maintained.

Thanks for finding this!

**Comment by HackToday** [comment]
OK @thaJeztah please let know what is good example can be used

**Comment by HackToday** [comment]
@thaJeztah  I'like to fix it, just make sure do we need still use this image or can use other image as example in the doc ?

**Comment by thaJeztah** [comment]
@HackToday oh, sorry! I just pushed a simple PR to update the example; see https://github.com/docker/docker/issues/18499

**Comment by HackToday** [comment]
OK @thaJeztah

**Comment by thaJeztah** [comment]
@HackToday let me know if that example is better, feel free to comment if you have additional suggestions :+1:
