### ISSUE TITLE
docker inspect --type=container reports "no such id.."

### ISSUE THREAD

**Issue by wenchma** [docker/docker#18424]
Description of problem:

    $ docker inspect 2b81d178e32a
    Error: No such image or container: 2b81d178e32a
    []
    $ docker inspect --type image 2b81d178e32a
    Error: No such image: 2b81d178e32a
    []
    $ docker inspect --type container 2b81d178e32a
    Error response from daemon: no such id: 2b81d178e32a[]
    $ docker inspect --type=container testttt
    Error response from daemon: no such id: testttt[]

To be more precise, I think it should return "no such conatiner" error message.

`docker version`

        Client:
	 Version:      1.9.1
	 API version:  1.21
	 Go version:   go1.4.2
	 Git commit:   a34a1d5
	 Built:        Fri Nov 20 13:12:04 UTC 2015
	 OS/Arch:      linux/amd64

	Server:
	 Version:      1.9.1
	 API version:  1.21
	 Go version:   go1.4.2
	 Git commit:   a34a1d5
	 Built:        Fri Nov 20 13:12:04 UTC 2015
	 OS/Arch:      linux/amd64

`docker info`

        Containers: 21
	Images: 82
	Server Version: 1.9.1
	Storage Driver: aufs
	 Root Dir: /var/lib/docker/aufs
	 Backing Filesystem: extfs
	 Dirs: 124
	 Dirperm1 Supported: false
	Execution Driver: native-0.2
	Logging Driver: json-file
	Kernel Version: 3.13.0-43-generic
	Operating System: Ubuntu 14.04.1 LTS
	CPUs: 4
	Total Memory: 15.67 GiB
	Name: docker
	ID: UT5D:M5ZY:IEXQ:6LCU:YX6J:ZMWM:BLNJ:MTXH:PRHO:ETVF:3FHH:6LC4
	WARNING: No swap limit support

`uname -a`

    Linux docker 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):OpenStack Cloud instance

**Comment by calavera** [comment]
It looks like this has been fixed already by #18425. Closing this issue :tada: :space_invader:
