### ISSUE TITLE
docker daemon crash when netmode = overlay

### ISSUE THREAD

**Issue by leejansq** [docker/docker#18423]
$ uname -a
Linux localhost.localdomain 4.1.8-200.fc22.x86_64 #1 SMP Tue Sep 22 12:13:21 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ docker version
Client:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5
 Git commit:   c920895-dirty
 Built:        Thu Dec  3 09:31:16 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5
 Git commit:   c920895-dirty
 Built:        Thu Dec  3 09:31:16 UTC 2015
 OS/Arch:      linux/amd64

$ docker info
Containers: 2
Images: 36
Server Version: 1.10.0-dev
Storage Driver: devicemapper
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93 (2015-01-30)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.8-200.fc22.x86_64
Operating System: Fedora 22 (Twenty Two)
CPUs: 4
Total Memory: 11.46 GiB
 Docker Root Dir: /var/lib/docker
Username: sqleejan
Registry: https://index.docker.io/v1/
Cluster store: etcd://127.0.0.1:2379/globalstore

I modify the docker source code,but I don't think it could make this bug....

the docker daemon crash stack info:
 
goroutine 201 [running]:
github.com/hashicorp/serf/serf.(*Serf).Query(0x0, 0x14b8960, 0xa, 0xc820dd8690, 0x46, 0x50, 0x0, 0x3, 0x0, 0x0)
	/gopath/src/github.com/docker/docker/vendor/src/github.com/hashicorp/serf/serf/serf.go:443 +0x44
github.com/docker/libnetwork/drivers/overlay.(*driver).resolvePeer(0xc820bcf0e0, 0xc820b91900, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/gopath/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/drivers/overlay/ov_serf.go:155 +0x2bb
github.com/docker/libnetwork/drivers/overlay.(*network).watchMiss(0xc820b9aea0, 0xc820c9d360)
	/gopath/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/drivers/overlay/ov_network.go:272 +0x6e8
created by github.com/docker/libnetwork/drivers/overlay.(*network).initSandbox
	/gopath/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/drivers/overlay/ov_network.go:241 +0x50b

**Comment by aboch** [comment]
Likely dupe of https://github.com/docker/docker/issues/18380

**Comment by thaJeztah** [comment]
Thanks @aboch; @leejansq can you have a look at #18380 and see if that looks like the same issue? Then we can close this one and keep the discussion there

**Comment by leejansq** [comment]
@thaJeztah;I thought the cluster-advertise option is related to swarm (substitute for `swarm join`).
So,cant't the cluster-advertise option  be ignored with globalscope?

**Comment by vdemeester** [comment]
@leejansq if you want to use the `overlay` multi-host network plugin (built-in) you need to setup `cluster-advertise` and `cluster-store` ; but it should error out not panic if not present I think :stuck_out_tongue_closed_eyes:

**Comment by leejansq** [comment]
@vdemeester ; You know me![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f61d.png)

**Comment by leejansq** [comment]
@vdemeester ;You know me...

**Comment by aboch** [comment]
This issue should be closed. It's a dupe and the bug has been fixed long ago.
ping @LK4D4
