### ISSUE TITLE
unexpected EOF when running docker build

### ISSUE THREAD

**Issue by dgutierrez1287** [docker/docker#18421]
docker version 1.9.1 when I run a docker build on a CentOS machine I keep seeing an unexpected EOF error. I tried the same build (same docker file and all contributing files) on an Ubuntu machine and there is no unexpected EOF error.

**Comment by dgutierrez1287** [comment]
Both machines are Vagrant boxes running in Virtualbox.

CentOS 7 machine: 
docker version: 
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

docker info:
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

uname -a:
Linux docker-host 3.10.0-229.14.1.el7.x86_64 #1 SMP Tue Sep 15 15:05:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Ubuntu 14.04 machine:
docker version:
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.2.1
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.2.1
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

docker info:
Containers: 0
Images: 26
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 26
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 489.2 MiB
Name: docker-host
ID: NTQF:LIUN:TGJR:3EEW:4LEH:H7QW:LWI3:4DJV:DUQT:KNPI:SOU4:XWW6
WARNING: No swap limit support

uname -a:
Linux docker-host 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Additional information:
I can run docker ps and other docker commands on the CentOS 7 Machine without issue however i do see daemon issues every once in a while, especially after the EOF error. I used the installation instructions on the docker website to install docker on both hosts.

**Comment by dgutierrez1287** [comment]
I did some more testing it was an issue with the install that is resolved.

**Comment by thaJeztah** [comment]
Thanks for reporting back @dgutierrez1287, and great that it's resolved for you!
