### ISSUE TITLE
Possibly flaky new test: TestInspectByPrefix

### ISSUE THREAD

**Issue by estesp** [docker/docker#18437]
Seems this has been intermittently failing on master on quite a few PRs, which is confusing as the busybox image is queried to get its ID (and that never fails).  Can't reproduce locally so hard to determine what part of this is failing.

```
----------------------------------------------------------------------
FAIL: docker_cli_inspect_test.go:346: DockerSuite.TestInspectByPrefix

docker_cli_inspect_test.go:352:
    c.Assert(err, checker.IsNil)
... value *errors.errorString = &errors.errorString{s:"failed to inspect container sha256:aa5: Error: No such image or container: sha256:aa5\n"} ("failed to inspect container sha256:aa5: Error: No such image or container: sha256:aa5\n")


----------------------------------------------------------------------
```

ping @tonistiigi @aaronlehmann

**Comment by estesp** [comment]
Full example run with failure: https://jenkins.dockerproject.org/job/Docker-PRs-experimental/11850/console

**Comment by aaronlehmann** [comment]
Perhaps the problem here is that the tests aren't isolated, so depending what happened before, busybox could either be loaded from a tar or pulled from the hub. I would expect this behavior to be relatively deterministic, though.

Another possibility is that network glitches are causing some busybox pulls to fall back to v1, which would lead to a different ID.

**Comment by tonistiigi** [comment]
@aaronlehmann why would the ID matter though? Any ID should work.

**Comment by estesp** [comment]
What was confusing to me is that you've asked the daemon to give you the `Id` of busybox in test 1; so the ID should be valid on this daemon. My wonder was what if the 3 chars is not unique--but I didn't dig far enough to your prefix lookup code to see what it returns if the length is not unique (I know the container lookup code very well with the pkg/truncindex stuff but didn't know if you use that or some other package..?)  Given the `Id` should be valid because inspect just gave it to you, I didn't know of many other options for failure..

**Comment by aaronlehmann** [comment]
Ah, I thought it was assuming a specific ID based on the version of busybox in the tar. It looks like that's not the case.
