### ISSUE TITLE
Support additional logging streams beyond stdout/stderr

### ISSUE THREAD

**Issue by wrouesnel** [docker/docker#18431]
Applications which have multiple output streams to files in many cases cannot be easily or at all reconfigured to log to stdout/stderr.

Docker should be able to expose additional FDs to containers which could be collected as logging streams, tagged with a name and FD number. This would let multiple log streams from dockerized applications point their log streams to predictable fifo's to receive them into the docker daemon for aggregation.

A portable implementation would require a Dockerfile syntax change - adding a LOG directive would be most appropriate i.e.
```
LOG /log/main
LOG /log/app
LOG /log/scheduler
LOG /log/auth
```
This would create fifo's at the given paths, that would be collected as structured logs with that name, or an optional given name with a second directive
```
LOG /log/cron scheduler
```

To allow users to harmonize the configuration, equivalent `docker run` directives would also be appropriate:
`docker run --log /log/cron:scheduler` would override the tagging on the log-stream, to allow log processing to deal with foreign containers.

This would greatly ease migrating applications to run on the docker platform, and handling logging from containers where multiple apps are needed in the same namespace.

**Comment by LK4D4** [comment]
Closing it as it didn't meet expected interest from the community. Implementation would be very challenging in a current state of things IMO, also.
