### ISSUE TITLE
Userns: run with --pid=host failed with unfriendly message

### ISSUE THREAD

**Issue by HackToday** [docker/docker#18430]
according to 
https://github.com/docker/docker/blob/master/experimental/userns.md

the user namespace have restriction with sharing namespaces with the host (--pid=host, --net=host, etc.), but I tried this pid example:
https://docs.docker.com/engine/reference/run/

```
$ docker run --pid=host rhel7 strace -p 1234
Unable to find image 'rhel7:latest' locally
Pulling repository docker.io/library/rhel7
6883d5422f4e: Download complete 
Status: Downloaded newer image for rhel7:latestr.io/library/rhel7 
docker.io/library/rhel7: this image was pulled from a legacy registry.  Important: This registry version will not be supported in future versions of docker.
Timestamp: 2015-12-04 09:21:15.193245437 +0000 UTC
Code: System error

Message: operation not permitted
Frames

0: setupRootfs
Package: github.com/opencontainers/runc/libcontainer
File: rootfs_linux.go@40

1: Init
Package: github.com/opencontainers/runc/libcontainer.(*linuxStandardInit)
File: standard_init_linux.go@57

2: StartInitialization
Package: github.com/opencontainers/runc/libcontainer.(*LinuxFactory)
File: factory_linux.go@243

3: initializer
Package: github.com/docker/docker/daemon/execdriver/native
File: init.go@35

4: Init
Package: github.com/docker/docker/pkg/reexec
File: reexec.go@26

5: main
Package: main
File: docker.go@18

6: main
Package: runtime
File: proc.go@111

7: goexit
Package: runtime
File: asm_amd64.s@1696
docker: Error response from daemon: Cannot start container 7f97cdeb4d4254526ee0ca1fd4faf73601d0f4d087e6fa39856885a3e1be3f53: [8] System error: operation not permitted.
```

It not tell us what's failed with because of user namespace or not. Is it designed ? If yes, it is very confusing

```
$ docker version
Client:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   94997e5
 Built:        Mon Nov 30 23:37:05 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   94997e5
 Built:        Mon Nov 30 23:37:05 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true
~$ uname -a
Linux dockerexper 3.19.0-30-generic #33-Ubuntu SMP Mon Sep 21 20:58:04 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by HackToday** [comment]
ping @thaJeztah

**Comment by HackToday** [comment]
This was test against with #18247

**Comment by thaJeztah** [comment]
Thanks @HackToday, could you perhaps also add the output of `docker info`, and the options you set on the daemon?

If you run a normal build of docker (non-experimental) on the same host, does that work without problems?

also ping @estesp for UserNS

**Comment by HackToday** [comment]
Hi @thaJeztah 

ubuntu@dockerexper:~$ docker info
Containers: 13
Images: 4
Server Version: 1.10.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/165536.165536/aufs
 Backing Filesystem: extfs
 Dirs: 46
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.19.0-30-generic
Operating System: Ubuntu 15.04
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.797 GiB
Name: dockerexper
ID: PMZK:QRON:RRD3:SK4N:7BFP:POHI:NTYN:42YG:RH34:TEXR:XZXN:25WF
WARNING: No swap limit support
Experimental: true
ubuntu@dockerexper:~$ ps -ef | grep docker
root     12961     1  0 Dec02 ?        00:03:52 /usr/bin/docker daemon -H fd:// --userns-remap=default
root     30107 12961  0 Dec04 ?        00:00:29 docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 32768 -container-ip 172.17.0.2 -container-port 5000
ubuntu   31742 29776  0 13:42 pts/0    00:00:00 grep --color=auto docker

**Comment by thaJeztah** [comment]
Thanks @HackToday! I'll leave this to @estesp who is probably better able to look into this, thanks for reporting! (Phil, I'll assign this to you, because you're "Mr. Userns"  :+1: )
