### ISSUE TITLE
Remote API version listing is not incremental #54

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#18440]
https://docs.docker.com/reference/api/docker_remote_api/

![image](https://cloud.githubusercontent.com/assets/668860/10025840/2b075478-6113-11e5-8b6c-b07477b1e507.png)

**Comment by HackToday** [comment]
This issue seems already fixed

**Comment by thaJeztah** [comment]
yup, this was fixed in https://github.com/docker/docker/pull/17583, thanks @HackToday
