### ISSUE TITLE
"flag provided but not defined: --exec-driver"

### ISSUE THREAD

**Issue by alivt** [docker/docker#18445]
Docker version:
--------------------
Docker version 1.8.0-dev, build a031b64

Docker Info:
---------------
Containers: 38
Images: 77
Storage Driver: devicemapper
 Pool Name: docker-8:2-16122109-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.762 GB
 Data Space Total: 107.4 GB
 Data Space Available: 105.6 GB
 Metadata Space Used: 5.382 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.142 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.95-RHEL6 (2015-09-08)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 2.6.32-504.8.1.el6.x86_64
Operating System: <unknown>
CPUs: 32
Total Memory: 62.9 GiB
Name: hulk2
ID: 3VTI:RPJT:C3V2:2QCE:FKYI:KTWU:KV6I:JXC7:ZK55:FABY:KBRR:FXHO

uname:
----------
Linux hulk2 2.6.32-504.8.1.el6.x86_64 #1 SMP Wed Jan 28 21:11:36 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Problem Scenario 1:
---------------------------
[11:56:08] root@hulk2 ~ # docker run --exec-driver=lxc --lxc-conf="lxc.cgroup.net_cls.classid=0x00100001" ubuntu -it /bin/bash
flag provided but not defined: --exec-driver
See 'docker run --help'.

Expected Result:
Should recognize the flag

Problem Scenario 2:
---------------------------
[11:55:57] root@hulk2 ~ # docker -e lxc run --lxc-conf="lxc.cgroup.net_cls.classid=0x00100001" ubuntu -it /bin/bash
Error response from daemon: Cannot use --lxc-conf with execdriver: native-0.2

Expected Result:
Should recognize the flag

-------------------------
Help says:
  -e, --exec-driver=native             Exec driver to use

**Comment by LK4D4** [comment]
@alivt It's daemon-wide flag, you can specify it only when you're starting daemon.

**Comment by alivt** [comment]
[12:09:28] root@hulk0 ~ # docker run -d -p 12345:8080 --exec-driver=lxc --lxc-conf="lxc.cgroup.net_cls.classid=0x00100001" --volumes-from SWIFT_DATA2 -t morrisjobke/docker-swift-onlyone
flag provided but not defined: --exec-driver
See 'docker run --help'.

**Comment by phemmer** [comment]
@alivt that's not daemon mode. daemon mode is when you're starting the docker daemon, not starting a container. E.G `docker daemon --exec-driver=lxc ...`

**Comment by alivt** [comment]
@phemmer I do not see daemon as a possible command, may be docker version problem (1.8.0-dev):
[17:15:21] root@hulk2 ~ # docker daemon --exec-driver=lxc
docker: 'daemon' is not a docker command.

Anyways, I was able to use lxc driver using following approach:

1) I started docker daemon: "docker -e lxc -d"
2) And separately launched the image: "docker -e lxc run -d -p 12346:8080 --cap-add=NET_ADMIN --lxc-conf="lxc.cgroup.net_cls.classid=0x00100001"  --volumes-from SWIFT_DATA2 -t morrisjobke/docker-swift-onlyone"

**Comment by thaJeztah** [comment]
@alivt 1.8.0-dev is really outdated. Also are you running that command on the host that the daemon runs on? If you're running that on (e.g.) an OS X client, you'll get that message, because the OS X client is a "client-only" build (I.e., doesn't have the daemon built in)

**Comment by alivt** [comment]
@thaJeztah  I am on CentOS 6.5 and yes I am running these commands on same host.
I tried to update the docker-engine by removing and reinstalling but yum installed this one. Is there any document other than following?
https://docs.docker.com/engine/installation/centos/

I want to reinstall docker to newer version.

**Comment by thaJeztah** [comment]
@alivt docker 1.7.1 is the latest version that's supported on CentOS 6; http://yum.dockerproject.org/repo/main/centos/6/Packages/. We no longer support CentOS 6 for newer releases.

**Comment by alivt** [comment]
@thaJeztah  Thanks I had 1.7.1 but I updated to 1.8.0-dev. I will revert back. 

Thanks for the info.

**Comment by thaJeztah** [comment]
@alivt if possible, I'd recommend to upgrade your system, CentOS 6 is really getting old, and the kernel used (2.6) is ancient. Of course, it really depends on your situation if you're able to do that, but if possible....
