### ISSUE TITLE
The current working directory cannot be mounted onto Docker container

### ISSUE THREAD

**Issue by upendrak** [docker/docker#18457]
I am trying to mount the current working directory onto Docker container but isn't working. When i run the following to mount the current working directory to make sure everything is doing ok, what i see is that all those dependencies are getting installed in the current working directory.

docker run --rm -v $(pwd):/working-dir -w /working-dir ubuntu/evolinc:2.0 -c cuffcompare_out_annot_no_annot.combined.gtf -g Brassica_rapa_v1.2_genome.fa -r Brassica_rapa_v1.2_cds.fa -b TE_RNA_transcripts.fa

I thought, they should only be installed on the container and only the output is going to generate in the current working directory. Sorry, i am very new to Docker and i would need some help with this....

**Comment by thaJeztah** [comment]
Are you running docker on windows or Mac (I.e., is docker running in VirtualBox)?

**Comment by thaJeztah** [comment]
Oh. Wait, I think I misread your issue; mounting the directory works, but you're seeing files being written to the current directory?

What's the `ubuntu/evolinc` image? Is that something you built yourself?

**Comment by upendrak** [comment]
Hi,

Yes, that's the image i built by myself on the VirtualBox.

Thanks
Upendra

**Comment by thaJeztah** [comment]
By bind-mounting the current directory in the container (as a volume), anything that's in that directory becomes visible in the container, and if a process inside the container writes files to that directory, they become written to the directory on the host. That's expected behavior, but perhaps I'm misunderstanding your issue.

Also see; http://docs.docker.com/engine/userguide/dockervolumes/#mount-a-host-directory-as-a-data-volume

**Comment by upendrak** [comment]
I have posted my question on Stackflow (http://stackoverflow.com/questions/34122270/how-to-mount-the-current-working-directory-onto-docker-container?noredirect=1#comment55996002_34122270) and there i explained my question better. Can you please take a look at it?

**Comment by thaJeztah** [comment]
I left some comments there, but it's still not entirely clear to me what you're trying to achieve, and/or why you're using the `-v $(pwd):/workdir`

**Comment by upendrak** [comment]
I'm following the tutorial in here - https://pods.iplantcollaborative.org/wiki/display/HDFDE/Using+Docker+and+creating+Docker+Images+and+Containers. My intention is to bind host's directory that contains the input files onto Container and let the output files written to the host's directory that is mounted.

**Comment by thaJeztah** [comment]
And what happens? Are the files *not* written to the directory on the host?

**Comment by upendrak** [comment]
At the moment, the files can neither be detect nor written to directory because the mounting is not working properly..

**Comment by upendrak** [comment]
Ok, i have figured out what is going on. There is a problem with the run script and nothing is wrong with Dockerfile or mounting.
