### ISSUE TITLE
`docker events --filter container=foo` is broken as of 1.9.0

### ISSUE THREAD

**Issue by bjaglin** [docker/docker#18453]
When running `docker events` with a `container` filter, nothing is received, even though events from a container with that name are received by the daemon. This is a regression from 1.8.3.

```
bjaglin@t440s:/tmp$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```
```
bjaglin@t440s:/tmp$ docker info
Containers: 1
Images: 14
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.0-18-generic
Operating System: Ubuntu 15.10
CPUs: 4
Total Memory: 11.64 GiB
Name: t440s
ID: 4CO2:NGIJ:KC6L:MBYG:BXNH:DRJK:GM5J:LQHT:H6QD:7RA2:FX2O:NRXF
WARNING: No swap limit support
```
```
bjaglin@t440s:/tmp$ uname -a
Linux t440s 4.2.0-18-generic #22-Ubuntu SMP Fri Nov 6 18:25:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Actual:
```
bjaglin@t440s:/tmp$ docker events --filter container=foo &
[1] 17134
bjaglin@t440s:/tmp$ docker run --rm --name foo alpine echo hello world
hello world
bjaglin@t440s:/tmp$ fg
docker events --filter container=foo
```

Expected (1.8.3 behavior):
```
bjaglin@t440s:/tmp$ docker events --filter container=foo &
[1] 30008
bjaglin@t440s:/tmp$ docker run --rm --name foo alpine echo hello world2015-12-06T00:24:18.000000000+01:00 9c683202e1fe738111261e9601421c31bfe53b7926f52bbcb941238da0a96cc8: (from alpine) create
2015-12-06T00:24:18.000000000+01:00 9c683202e1fe738111261e9601421c31bfe53b7926f52bbcb941238da0a96cc8: (from alpine) attach
2015-12-06T00:24:19.000000000+01:00 9c683202e1fe738111261e9601421c31bfe53b7926f52bbcb941238da0a96cc8: (from alpine) start
hello world
2015-12-06T00:24:19.000000000+01:00 9c683202e1fe738111261e9601421c31bfe53b7926f52bbcb941238da0a96cc8: (from alpine) die
bjaglin@t440s:/tmp$ fg
docker events --filter container=foo
```

Issue reproducible on 1.9.0, 1.9.1 & experimental (20151205).

**Comment by bjaglin** [comment]
Related to https://github.com/docker/docker/commit/08b117517d6d6b5daebe4c056c135e1598f44385 ?

**Comment by thaJeztah** [comment]
Confirmed that this doesn't work on 1.9.1; It *does* work if the `docker events` command is run *after* a container was created, i.e.

```
docker run -d --name foo nginx
docker events --filter container=foo
# this will correctly filter events and only show events foor foo
```

/cc @dnephin

**Comment by LK4D4** [comment]
@bjaglin @thaJeztah it's fixed in master. I think by some of @calavera patches.

**Comment by coolljt0725** [comment]
@thaJeztah  The event filter use `container.ID` to filter when user pass `container=xxx`( `xxx` will convert to `container.ID`). The difference between `1.9.1` and previous versions is that `1.9.1` doing the convert on `docker event` start and at this time the container is not exist, but previous version doing the convert on event happening, and at this time the container is already exits. So  it does work if the `docker events` command is run after a  container was created.

**Comment by coolljt0725** [comment]
@LK4D4  I don't think `master` has fixed this correctly. It will show all the containers' events
<pre><code>[lei@fedora docker]$ docker run -ti --rm --name=bar busybox echo hello world
hello world</code></pre>
<pre><code>$ docker events --filter container=foo
2015-12-07T01:55:49.058488848-05:00 5869511f1db5e47bb51032e946249f6940eb58072c8ae12b4f981e232822b83c: (from busybox) create
2015-12-07T01:55:49.059888658-05:00 5869511f1db5e47bb51032e946249f6940eb58072c8ae12b4f981e232822b83c: (from busybox) attach
2015-12-07T01:55:49.421738476-05:00 5869511f1db5e47bb51032e946249f6940eb58072c8ae12b4f981e232822b83c: (from busybox) start
2015-12-07T01:55:49.542467643-05:00 5869511f1db5e47bb51032e946249f6940eb58072c8ae12b4f981e232822b83c: (from busybox) resize
2015-12-07T01:55:49.574351167-05:00 5869511f1db5e47bb51032e946249f6940eb58072c8ae12b4f981e232822b83c: (from busybox) die
2015-12-07T01:55:50.193155688-05:00 5869511f1db5e47bb51032e946249f6940eb58072c8ae12b4f981e232822b83c: (from busybox) destroy </code></pre>
As you can see, I want the events of container `foo`, the events of container `bar` are also received.

**Comment by coolljt0725** [comment]
@thaJeztah  @LK4D4  I have open a PR #18464 to fix this

**Comment by thaJeztah** [comment]
Thank you @coolljt0725!
