### ISSUE TITLE
Container Inspect does not return "Name" in "Mounts" for volumes created before 1.9.0

### ISSUE THREAD

**Issue by pchico83** [docker/docker#18467]
Description of problem: when inspecting a container with api v1.21, a "Mounts" property is returned with the information about volumes. Each "mount" has a "Name" property, which has a default value based on the volume source path. The issue is that this field is not returned for volumes created before docker 1.9.0, if the daemon is upgraded to 1.9.0.
It does not look to be intentional, because these volumes are accessible by name, and their name is returned by the LIST Volume API. 

How reproducible: easy

Steps to Reproduce:
1. Create a container with volumes in docker 1.8.3
2. Upgrade the docker daemon to 1.9.0 (or 1.9.1)
3. Inspect the previous container and check the "Mounts" property

Actual Results:
```
    "Mounts": [
        {
            "Source": "/mnt/sda1/var/lib/docker/volumes/f2f6eed3380ca33de037c83b1c89b753c8eae082539f3b0c34c2cd7b9ea21055/_data",
            "Destination": "/etc/mysql",
            "Mode": "",
            "RW": true
        }
    ]
```
Expected Results:
```
    "Mounts": [
        {
            "Name": "f2f6eed3380ca33de037c83b1c89b753c8eae082539f3b0c34c2cd7b9ea21055",
            "Source": "/mnt/sda1/var/lib/docker/volumes/f2f6eed3380ca33de037c83b1c89b753c8eae082539f3b0c34c2cd7b9ea21055/_data",
            "Destination": "/etc/mysql",
            "Driver": "local",
            "Mode": "",
            "RW": true
        }
    ]
```
I think it also happens for the "Driver" property. @cpuguy83 any idea?

**Comment by cpuguy83** [comment]
Is this including 1.7 and 1.8, or is this pre-1.7?

**Comment by cpuguy83** [comment]
Just tried with 1.8 and it's fine. 1.7 and less is a little more difficult to get these days since it's not in the releases section and isn't easily compilable due to code.google.com stopping.

I suspect this is from < 1.7, and it's because we aren't storing a name on the container struct for these migrated volumes.

**Comment by pchico83** [comment]
@cpuguy83 It was from 1.8.3 to 1.9.1, don't know if it still happens in 1.10

**Comment by LK4D4** [comment]
oooh, it's pretty old
Closing this as not active.
