### ISSUE TITLE
Docker version 1.8.2 does not send auth header with PATCH HTTP request when pushing to default port

### ISSUE THREAD

**Issue by melkamar** [docker/docker#18469]
This issue is related to https://github.com/docker/docker/issues/16728 , but bear with me please.
(bug report at the bottom)

**Environment:** 
Docker registry (Artifactory) behind NginX. Port 443 (standard HTTPS) redirects to the Docker endpoint and should be used to access it. I am logged in through `docker login`

**The problem:** 
* `docker push docker.int.domain.com:443/some-image` works
* `docker push docker.int.domain.com/some-image` **does not**. The output:

  ```
    The push refers to a repository [docker.int.domain.com/testtest/ubuntu] (len: 1)
    8d885ef1e201: Pushing [==================================================>]  30.9 MB
    unauthorized: The client does not have permission to push to the repository.
  ```
  

I had a look at NginX's access logs and this is what I found:
* When pushing to the "port-less" address, the request *is* directed to the port 443, so those commands should behave the same way.
* The PATCH HTTP request does not contain auth header, yet all other requests do. This causes the push command to fail with `unauthorized: The client does not have permission to push to the repository.`

This issue is present in version 1.8.2. With version 1.7.x pushing without explicitly specifying the port was possible.

**NginX's access log:**
* The second column is the name of the authenticated user
* p: denotes port
* The last number is response HTTP code

`docker push docker.int.domain.com/some-image`
```
192.168.33.3 , - , [07/Dec/2015:14:32:04 +0100] , p:443 , "GET /v2/", 401
192.168.33.3 , melka , [07/Dec/2015:14:32:06 +0100] , p:443 , "HEAD /v2/testtest/ubuntu/(...)", 404
192.168.33.3 , melka , [07/Dec/2015:14:32:07 +0100] , p:443 , "POST /v2/testtest/ubuntu/(...)", 202
192.168.33.3 , - , [07/Dec/2015:14:33:08 +0100] , p:443 , "PATCH /v2/testtest/ubuntu/(...)" , 403
```

`docker push docker.int.domain.com:443/some-image`
```
192.168.33.3 , - , [07/Dec/2015:14:43:23 +0100] , p:443 , "GET /v2/", 401
192.168.33.3 , melka , [07/Dec/2015:14:43:24 +0100] , p:443 , "HEAD /v2/testtest/ubuntu/(...)", 404
192.168.33.3 , melka , [07/Dec/2015:14:43:24 +0100] , p:443 , "POST /v2/testtest/ubuntu/(...) HTTP/1.1", 202
192.168.33.3 , melka , [07/Dec/2015:14:43:27 +0100] , p:443 , "PATCH /v2/testtest/ubuntu/(...)", 202
192.168.33.3 , melka , [07/Dec/2015:14:43:27 +0100] , p:443 , "PUT /v2/testtest/ubuntu/(...)", 201
(...)
```

As you can see, for some reason when pushing without specifying port, the name is empty. That causes the push to fail. When a port is set, the push continues with more log messages below.

Just to be on the safe side, here is my NginX config:
(I have tried removing the X-Forwarded-headers as suggested here https://docs.docker.com/registry/nginx/ - that did not help).
```
    server {
        listen 80;
        server_name docker.int.domain.com;
        return 301 https://$server_name$request_uri;
    }
    
    server {
        listen 443;
        server_name docker.int.domain.com;

        ssl on;
        ssl_certificate /etc/nginx/cert/artifactory-ca.crt;
        ssl_certificate_key /etc/nginx/cert/artifactory-ca.key;

        access_log  /var/log/nginx/docker.int.domain.com.443.access.log  myformat;
        error_log  /var/log/nginx/docker.int.domain.com.443.error.log;

        proxy_set_header Host $host:443;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Original-URI $request_uri;
        proxy_pass_header Server;  # To help debugging, list the server that actually did the reply rather than nginx
        proxy_read_timeout 900;

        client_max_body_size 0; # disable any limits to avoid HTTP 413 for large image uploads

        # required to avoid HTTP 411: see Issue #1486 (https://github.com/docker/docker/issues/1486)
        chunked_transfer_encoding on;

        location /v2 {
            proxy_pass http://localhost:8081/artifactory/api/docker/docker/v2;
        }
    }
```

We want to be able to refer to the repository just by the server name, without having to specify the port. But right now, that is only possible using the older docker client.

Thanks for taking a look at this
    
    
**BUG REPORT INFORMATION**

**docker version:**
```
Client:
 Version:      1.8.2
 API version:  1.20
 Package Version: docker-1.8.2-7.el7.centos.x86_64
 Go version:   go1.4.2
 Git commit:   bb472f0/1.8.2
 Built:        
 OS/Arch:      linux/amd64
```
**docker info:**
```
Containers: 3
Images: 17
Storage Driver: devicemapper
 Pool Name: docker-253:0-69269427-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 4.353 GB
 Data Space Total: 107.4 GB
 Data Space Available: 8.753 GB
 Metadata Space Used: 3.731 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.14.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 3.703 GiB
Name: localhost.localdomain
ID: UGHD:SKNU:RRGU:GERL:KGDA:3Q7I:T5L5:LWGO:AM2Z:LTRX:MIX4:XBK3
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**uname -a:**
```
Linux localhost.localdomain 3.10.0-229.14.1.el7.x86_64 #1 SMP Tue Sep 15 15:05:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Running in VirtualBox.

List the steps to reproduce the issue:
1. Have a registry behind NginX (I have Artifactory-based)
2. Set up NginX so that the registry is accessible on port 443.
3. Push an image to the registry, **without** specifying the port number

Describe the results you received:
* I expect the image to be pushed successfully, because port 443 is the default.

Describe the results you expected:
* The push fails with an error: `unauthorized: The client does not have permission to push to the repository.`

----------END REPORT ---------

**Comment by thaJeztah** [comment]
Just a very wild guess; My guess is that `~/.docker/config.json` stores the credentials per URL, i.e. it possibly contains credentials for `docker.int.domain.com:443`, but *not* for `docker.int.domain.com`, and therefore doesn't send credentials for that URL

**Comment by crania** [comment]
Having a similar issue on 1.9.1 - no auth on the PATCH so a push dies off.

**Comment by melkamar** [comment]
@thaJeztah 
I did login to both addresses - with and without specified port. In my config.json file there are auth tokens for both as well. 

The credentials are sent for *some* requests, which is why the image gets uploaded (I see the progress bar and have to wait some time) - but after the upload (POST request), a PATCH request *without* credentials is sent. (details in the issue body, *NginX's access log*.

**Comment by crania** [comment]
Just an FYI - my issue on 1.9.1 was not related.  There was a LB in the path that was replacing the X-Forwarded-Proto such that any secondary requests were not being passed correctly in.

**Comment by shiqiyang-okta** [comment]
having the same issue with artifactory pro 3.9.4 and docker client 1.9.1, I tried different version of docker client and seems the problem start happening since 1.8.0 (both 1.6 and 1.7 worked fine)

**Comment by melkamar** [comment]
Changing NginX config entry `proxy_set_header Host $host:443;` to `proxy_set_header Host $host;` (dropping the port) seems to fix the issue for me. Not sure if this is just a workaround, or if it means it is not a bug.

**Comment by thaJeztah** [comment]
@melkamar thanks. I'm no too familiar with configuring a registry in this setup; @dmp42 can you have a quick look?

**Comment by dmp42** [comment]
The documentation reads: 
`    proxy_set_header  Host              \$http_host;   # required for docker client's sake`

https://github.com/docker/distribution/blob/master/docs/nginx.md

@melkamar the issue at this point is not clear to me - can you maybe sum it up?

Thanks.

**Comment by shiqiyang-okta** [comment]
just FYI: there is also an artifactory bug https://www.jfrog.com/jira/browse/RTFACT-8043 that's in play here for my case, we are upgrading to 3.9.5 this weekend to see if that will resolve it

**Comment by simonsm1** [comment]
I had the same issue described here. After some playing with the registry config I found that changing REGISTRY_HTTP_HOST: https://address:443 to https://address solved the issue and PATCH and PUT both sent the credentials, whereas before only POST would.

**Comment by stanhu** [comment]
We ran into this problem yesterday, which caused some downtime with the Docker registry on GitLab.com. Fix is here: https://github.com/docker/distribution/issues/1868

**Comment by thaJeztah** [comment]
@stanhu @RichardScothern should this be closed here, or wait until it's vendored in?

**Comment by sudhanshu-garg** [comment]
I am still hitting the exact same issue where the docker engine is not sending the Authorization header with PATCH request.

I am using "Docker version 1.12.0, build b9264d4" as the client.
I am using docker-distribution which contains the above fix. I have picked up the latest master from Jan 2017.

Here is the list of HTTP headers coming through to the docker registry when pushing an image.

GET /v2/ HTTP/1.1
X-Real-IP: 10.229.148.134
X-Forwarded-For: 10.229.148.134
true-client-ip: 10.229.148.134
X-Forwarded-Proto: https
Host: sgtest91-4750a4d4ec14dcc8aaa97df1f26380a.uscom-central-1.c9dev1.oraclecorp.com:443
WL-Proxy-SSL: true
IS_SSL: ssl
User-Agent: docker/1.12.0 go/go1.6.3 git-commit/b9264d4 kernel/4.1.12-61.1.10.el6uek.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.0 \(linux\))
Accept-Encoding: gzip
 
POST /v2/redis/blobs/uploads/ HTTP/1.1
X-Real-IP: 10.229.148.134
X-Forwarded-For: 10.229.148.134
true-client-ip: 10.229.148.134
X-Forwarded-Proto: https
Host: sgtest91-4750a4d4ec14dcc8aaa97df1f26380a.uscom-central-1.c9dev1.oraclecorp.com:443
WL-Proxy-SSL: true
IS_SSL: ssl
Content-Length: 0
User-Agent: docker/1.12.0 go/go1.6.3 git-commit/b9264d4 kernel/4.1.12-61.1.10.el6uek.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.0 \(linux\))
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ikc3SjI6MkhYVzpTV1RVOkg2N1I6VkpWSDpXR1haOjYzWEI6M0RUNDpUVldUOkVKUkc6NFRKSTpNNDZaIn0.eyJpc3MiOiJBdXRoIFNlcnZpY2UiLCJzdWIiOiJhZG1pbiIsImF1ZCI6IkRvY2tlciByZWdpc3RyeSIsImV4cCI6MTQ4MTkxMjY2MywibmJmIjoxNDgxOTExNzUzLCJpYXQiOjE0ODE5MTE3NjMsImp0aSI6IjY3NTU3MDIxOTY1MDEwMTg3NDIiLCJhY2Nlc3MiOlt7InR5cGUiOiJyZXBvc2l0b3J5IiwibmFtZSI6InJlZGlzIiwiYWN0aW9ucyI6WyJwdWxsIiwicHVzaCJdfV19.JsiWRkPFospFPiJYpX9TB_4e3b3WsN3EH6GGa3r_o2M7YmNyg0RateKlj7isUnRqAulnemKmcBzUzy4Dv-xVEDiLwDPgj0weIB2jzMgz4NTMf74c7IL7xJfFhmTMawmAq3-n85OgNUyk27-ilJ7mMkqZQ5j-hSE_vDUpvERvM_PutiH2RDissmqmS7iGMu5ZVUyFXkTQMKUAv_fjq4xO_MppYfVJTuO06KpLvfjlK4ngnyYVnl-2ZEKmYRVPln5QCEU7kpUw-RBmI1x2IA85uN8e91Dqv2SVrfe0UmEVkTXqPHzLS1eQqpeN_a41oPrnQ5_z6LsUxvK_RaF5TpjPacP93V4BoxvA_0ZFiQxogEyozekSvINeqhW4Yx5KvmD-HZqbEiChKv3DSsTZifnA2k_hpgN6PWBiCPZPz9IpndQ58PzQJJA1tfDqZcyVuIWrFPRyrbCUmciaEWCw_QxRcghG_XyWtuT0jYeF3r03ay2wZX7cCLqxuBlyvvUo6i54VoBP5VaCC6Ktcu_ucSsqVmvCvGyulZF9tn7wqw2ahkMf9BoJFilIl50Ve1uub6tcMFJBofE1tngRM_N7b6NOHuSDZBYPn6IdcWJCiaS6N0oP-vxXYfk1KGrmZkACOb-cunKogtzYGcM9l6O1XDlhAG7CbeXRiWPO09imh1X3WXo
Content-Type: 
Accept-Encoding: gzip

... a few more POSTs all of which have the Authorization header ...

PATCH /v2/redis/blobs/uploads/2de84fed-d15a-45fe-bb9b-61bd7bb975f1?_state=s1EYj7nES5ZAnwWT4eS51gjEFBHnnu3gcx_7bzPfrKl7Ik5hbWUiOiJyZWRpcyIsIlVVSUQiOiIyZGU4NGZlZC1kMTVhLTQ1ZmUtYmI5Yi02MWJkN2JiOTc1ZjEiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMTYtMTItMTZUMTg6MDk6MjMuODUzNTQzMTIzWiJ9 HTTP/1.1
X-Real-IP: 10.229.148.134
X-Forwarded-For: 10.229.148.134
true-client-ip: 10.229.148.134
X-Forwarded-Proto: https
Host: sgtest91-4750a4d4ec14dcc8aaa97df1f26380a.uscom-central-1.c9dev1.oraclecorp.com:443
WL-Proxy-SSL: true
IS_SSL: ssl
Content-Length: 96
User-Agent: docker/1.12.0 go/go1.6.3 git-commit/b9264d4 kernel/4.1.12-61.1.10.el6uek.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.0 \(linux\))
Accept-Encoding: gzip
 
See the above PATCH has missing Authorization header.

**Comment by sudhanshu-garg** [comment]
Based on the investigation I have done so far, it seems like it is because the Host header container the default port of 443, the docker registry sends back a Location header container a URL which also contains the port 443 thereby making docker client/engine to think this is a different registry. I think the fix should be to not have the default ports when sending back the Location headers.

**Comment by thaJeztah** [comment]
@sudhanshu-garg looks like this was fixed by https://github.com/docker/distribution/issues/1868, which got vendored into this repository through https://github.com/docker/docker/pull/28235, and is part of the upcoming docker 1.13 release. If you have a system to test on, release candidates for docker 1.13 are available

**Comment by sudhanshu-garg** [comment]
Sure @thaJeztah, I will give it a try with docker 1.13.
Question - What's the solution if I want to stay on older versions (between 1.6 and 1.12) of docker? Is the fix going to be backported to those versions?

**Comment by thaJeztah** [comment]
@sudhanshu-garg no, no back porting currently, we only maintain the "current" release.
