### ISSUE TITLE
Cannot use docker as non-root user

### ISSUE THREAD

**Issue by brhahlen** [docker/docker#18466]
Description of problem:
Cannot use docker as a non-root user

`docker version`:
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:39:26 UTC 2015
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```
`sudo docker version`:
```
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:39:26 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:39:26 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:
```
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```
`sudo docker info`:
```
Containers: 0
Images: 0
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-253:0-411685-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 53.74 MB
 Data Space Total: 107.4 GB
 Data Space Available: 23.09 GB
 Metadata Space Used: 606.2 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.109 (2015-09-22)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.6-301.fc23.x86_64
Operating System: Fedora 23 (Twenty Three)
CPUs: 8
Total Memory: 15.64 GiB
Name: XebTop
ID: 6JVQ:EMQE:VJRY:4H5U:ZKFC:PRWJ:HMLQ:NURZ:OI3L:NMSB:MZPT:GGLI
```

`uname -a`:
`Linux XebTop 4.2.6-301.fc23.x86_64 #1 SMP Fri Nov 20 22:22:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

Environment details (AWS, VirtualBox, physical, etc.):
Laptop (Dell Precision M3800) running Fedora 23. Used to work without problems on Fedora 22.

How reproducible:
Install Fedora 23, add Docker repo.

Steps to Reproduce:
1. Install Fedora 23
2. Add Docker Repo
3. Add user to group 'docker'
4. Log out/reboot
5. Try to run `docker version` as own user

Actual Results:
```
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

Expected Results:
That it works

Additional info:
Service is running:
```
service docker status
Redirecting to /bin/systemctl status  docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: active (running) since Mon 2015-12-07 10:48:42 CET; 5s ago
     Docs: https://docs.docker.com
 Main PID: 20724 (docker)
   CGroup: /system.slice/docker.service
           └─20724 /usr/bin/docker daemon -H fd://
```
I am in the group:
```
groups
ben2404 docker vboxusers bumblebee
```
Rebooted, logged out, logged in, reinstalled using docker repo for Fedora, all to no avail.

**Comment by thaJeztah** [comment]
Does `sudo docker version` work? Also I see `disabled` in the output of `docker status`; I'm no systemd expert, but are you sure the daemon is actually running?

**Comment by brhahlen** [comment]
Yes, sudo works, as posted above.
The disabled part from systemd is for whether or not it should be started on boot. By default, this is disabled when doing a fresh install.
The line that starts with "Active" is the line where it shows the state, and it also shows the PID.

**Comment by thaJeztah** [comment]
oh! yeah, I actually knew that :blush:

I just spun up a fedora23 box on DigitalOcean, installed docker, and:

```bash
[root@issue-18466 ~]# useradd foo
[root@issue-18466 ~]# usermod -aG docker foo
[root@issue-18466 ~]# su - foo
[foo@issue-18466 ~]$ groups
foo docker
[foo@issue-18466 ~]$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:39:26 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:39:26 UTC 2015
 OS/Arch:      linux/amd64

[foo@issue-18466 ~]$ docker info
Containers: 0
Images: 0
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-252:1-262242-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.821 GB
 Data Space Total: 107.4 GB
 Data Space Available: 29.1 GB
 Metadata Space Used: 1.479 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107 (2015-09-05)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.3-300.fc23.x86_64
Operating System: Fedora 23 (Cloud Edition)
CPUs: 1
Total Memory: 993.5 MiB
Name: issue-18466
```

So, I'm not able to reproduce?

**Comment by brhahlen** [comment]
Fair point. I just tested on a VM with a clean install and that works without problem as well, so now, I'm back to the drawing board.
Removed docker, removed the group from my user, and all docker-files.

**Comment by thaJeztah** [comment]
@brhahlen good luck, I hope you're able to resolve the issue. Are you okay with closing this issue?

**Comment by brhahlen** [comment]
Yes, I am, because I just found out the problem.
I had secured my docker via the instructions here: http://docs.docker.com/engine/articles/https/ 
I added $DOCKER_HOST and $DOCKER_TLS_VERIFY to my .bashrc
Apparently, something got broken, so it tried to connect secure to an unsecured docker. Or so...

Thansk for the help and sorry for the confusion!

**Comment by brhahlen** [comment]
@thaJeztah Hi there.
I know what the problem is:
When starting docker with `systemctl start docker`, it does not start in secure mode, while I am assuming that it is, with `DOCKER_HOST=` and `DOCKER_TLS_VERIFY=1` in my .bashrc
How can I make sure the docker daemon is started with in secured mode automatically? The docs don't go into this...
Thanks!

**Comment by thaJeztah** [comment]
@brhahlen I think the best option is to create a drop-in file for systemd that overrides the default settings; https://docs.docker.com/engine/articles/systemd/#custom-docker-daemon-options

If you're provisioning the VM with docker-machine, you can also pass in custom daemon options when creating the machine, and those will be used during provisioning; https://docs.docker.com/machine/reference/create/#specifying-configuration-options-for-the-created-docker-engine

**Comment by brhahlen** [comment]
@thaJeztah I created a /etc/default/docker file, assuming (I know, I know...) that it would be picked up by default by the systemd unit file.
Oh well, I'll look into it :-)
Thanks again!

**Comment by thaJeztah** [comment]
@brhahlen no, the `/etc/default/docker` file is no longer used by systemd. Older incarnations of the unit-file did indeed include that, but that was changed; the recommended way to configure systemd is using drop-ins
