### ISSUE TITLE
Maximum number of ENV variables in docker versin 1.9.0

### ISSUE THREAD

**Issue by eemin** [docker/docker#18471]
Hi,

When I user more than 10 environment variables in docker file and pass them to the bash scripts as command line arguments it is messing the environment variables that are over 10.

But when I use less then 10 every thing is working as it is supposed to.

Is there a limitation on the number of ENV variables or is it a bug?

Docker version is 1.9.0
Host is CentOS 7.1

**Comment by duglin** [comment]
@eemin can you share with us your Dockerfile and exact command line you use to build, and/or run the image?  I'm not seeing this issue.

**Comment by eemin** [comment]
Well to figure out what is going on I made a very simple script and the  test the situation in clean Ubuntu base image . Every thing there is working as it is supposed to be.
So this is something else I have to figure it out, either from the image or the scripts  that are used in it. Image was prepared by a colleague for the company.   
Sorry to waste some space.

**Comment by thaJeztah** [comment]
@eemin no problem, hope you're able to resolve your issue!
