### ISSUE TITLE
Network not connecting when using -b option for docker service

### ISSUE THREAD

**Issue by Stroppel** [docker/docker#18475]
As requested here the missing informations:

# BUG REPORT INFORMATION

```
docker --version
Docker version 1.9.1, build a34a1d5
```

```
docker info
Containers: 108
Images: 63
Server Version: 1.9.1
Storage Driver: devicemapper
Pool Name: docker-253:4-263074-pool
Pool Blocksize: 65.54 kB
Base Device Size: 107.4 GB
Backing Filesystem:
Data file: /dev/loop0
Metadata file: /dev/loop1
Data Space Used: 3.153 GB
Data Space Total: 107.4 GB
Data Space Available: 1.531 GB
Metadata Space Used: 8.868 MB
Metadata Space Total: 2.147 GB
Metadata Space Available: 1.531 GB
Udev Sync Supported: true
Deferred Removal Enabled: false
Deferred Deletion Enabled: false
Deferred Deleted Device Count: 0
Data loop file: /var/lib/docker/devicemapper/devicemapper/data
Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
Library Version: 1.02.107-RHEL7 (2015-10-14)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
CPUs: 2
Total Memory: 1.79 GiB
Name: mo-05782c99c
ID: OPWV:ZASL:WH7G:NUL3:TTQZ:5HYN:KYEF:MHDY:B25G:WUDR:VGYG:EBFW
Http Proxy: http://proxy.intern:8080
Https Proxy: http://proxy.intern:8080
No Proxy: localhost,127.0.0.1,169.254.169.254,repo,mo-05782c99c
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```
No idea yet what this warnings mean:
```
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

```
uname -a
Linux mo-05782c99c.intern 3.10.0-327.el7.x86_64 #1 SMP Thu Oct 29 17:29:29 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.):
All Machines are hosted in a private cloud so I am not sure what hypervisor or cloud is below...

## Reproduction steps:
I have a docker environment where i use my own generated bridge. The docker deamon is started via:
```
/usr/bin/docker daemon -b=kbr0 --exec-opt native.cgroupdriver=cgroupfs
```

## Steps to reproduce
Where kbr0 is the custom bridge. Every container is working fine except for all docker build calls. I cant build my containers as long as i have the -b option for the daemon.

here the configurations:

```
brctl show kbr0
bridge name     bridge id               STP enabled     interfaces
kbr0            8000.d2c9542db143       yes             obr0
```

I used this dockerfile to generate some analytics:
```
FROM test

RUN ip route > /var/log/route.log
RUN set > /var/log/variables.log
RUN ip a > /var/log/network.log
RUN traceroute 10.97.138.82 > /var/log/traceroute.log
RUN ping -c 10 172.17.1.1 > /var/log/ping.log
RUN curl www.google.de > /var/log/wget.out
RUN yum -y update > /var/log/yumupdate.log
```

While test is an centos Image with an traceroute installed before.

Output of the docker build command:
Current Result

```
docker build --build-arg http_proxy=$http_proxy -t test1 .
Sending build context to Docker daemon 3.072 kB
Step 1 : FROM test
 ---> 94c673d3e76e
Step 2 : RUN ip route > /var/log/route.log
 ---> Running in d9b2d549733e
 ---> 826821d81e90
Removing intermediate container d9b2d549733e
Step 3 : RUN set > /var/log/variables.log
 ---> Running in bf4eb302c355
 ---> 19715fb6e5ef
Removing intermediate container bf4eb302c355
Step 4 : RUN ip a > /var/log/network.log
 ---> Running in 9bfbf388f493
 ---> 1dbde0f46d1f
Removing intermediate container 9bfbf388f493
Step 5 : RUN traceroute 10.97.138.82 > /var/log/traceroute.log
 ---> Running in b3888408d0f5
 ---> ae30829ed05f
Removing intermediate container b3888408d0f5
Step 6 : RUN ping -c 10 172.17.1.1 > /var/log/ping.log
 ---> Running in c0e405eeb757
The command '/bin/sh -c ping -c 10 172.17.1.1 > /var/log/ping.log' returned a non-zero code: 1
```

## Expected results:
No Failure and a successful build

## Additional Info:

after the run i connect to it via:
```
docker run -it ae30829ed05f /bin/bash 
```
(Notice the ID was the last succesful step)

Now here the input of the different log files:

```
cat network.log
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
87: eth0: <NO-CARRIER,BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state DOWN
    link/ether 02:42:ac:11:01:02 brd ff:ff:ff:ff:ff:ff
    inet 172.17.1.2/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe11:102/64 scope link tentative
       valid_lft forever preferred_lft forever
```
```
cat route.log
default via 172.17.1.1 dev eth0
172.17.1.0/24 dev eth0  proto kernel  scope link  src 172.17.1.2
```
```
 cat traceroute.log
traceroute to 10.97.138.82 (10.97.138.82), 30 hops max, 60 byte packets
 1  7aa5783a47d5 (172.17.1.2)  3006.075 ms !H  3005.996 ms !H  3005.981 ms !H
```
```
ip a host:
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 00:50:56:83:49:47 brd ff:ff:ff:ff:ff:ff
    inet 10.97.138.82/18 brd 10.97.191.255 scope global dynamic eth0
       valid_lft 583110sec preferred_lft 583110sec
    inet6 fe80::250:56ff:fe83:4947/64 scope link
       valid_lft forever preferred_lft forever
5: kbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN
    link/ether d2:c9:54:2d:b1:43 brd ff:ff:ff:ff:ff:ff
    inet 172.17.1.1/24 brd 172.17.1.255 scope global kbr0
       valid_lft forever preferred_lft forever
    inet6 fe80::d0c9:54ff:fe2d:b143/64 scope link
       valid_lft forever preferred_lft forever
```

**Comment by Stroppel** [comment]
As requested here the missing informations:
docker --version
Docker version 1.9.1, build a34a1d5

docker info
Containers: 108
Images: 63
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-253:4-263074-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem:
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.153 GB
 Data Space Total: 107.4 GB
 Data Space Available: 1.531 GB
 Metadata Space Used: 8.868 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 1.531 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
CPUs: 2
Total Memory: 1.79 GiB
Name: mo-05782c99c
ID: OPWV:ZASL:WH7G:NUL3:TTQZ:5HYN:KYEF:MHDY:B25G:WUDR:VGYG:EBFW
Http Proxy: http://proxy.intern:8080
Https Proxy: http://proxy.intern:8080
No Proxy: localhost,127.0.0.1,169.254.169.254,repo,mo-05782c99c
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

No idea yet what this warnings mean:
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

Linux mo-05782c99c.intern 3.10.0-327.el7.x86_64 #1 SMP Thu Oct 29 17:29:29 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

All Machines are hosted in a private cloud so I am not sure what hypervisor or cloud is below...

**Comment by Stroppel** [comment]
included the needed information in the description

**Comment by Stroppel** [comment]
Hmmm seems no one can help here...

**Comment by narqo** [comment]
Me got the same behaviour with the default `bridge` network of docker >= 1.9x. My current guess is that the source of the problem is somewhere near this line from your logs (note `state DOWN`):

~~~
87: eth0: <NO-CARRIER,BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state DOWN
~~~

Somehow container had been started before `eth0` was upped.

**Comment by LK4D4** [comment]
It's strange issue. I'm closing it because it was inactive for too long. Feel free to open new. New issues have much more attention.
