### ISSUE TITLE
No way to disable trust-on-first-use for 'docker pull' with Content Trust

### ISSUE THREAD

**Issue by mrled** [docker/docker#18474]
As far as I can tell, there's no way to tell Docker not to trust the first Content Trust certificate it finds. This is something I'd prefer to do manually, rather than have it done for me, because I want to ensure that my keys aren't tampered with on the notary. 

Is this possible? If not - would you consider adding the feature? 

(For the record, I'd prefer to distribute my root key certificate myself over the management infrastructure I already use, which is currently SSH and Ansible. For my use, I don't mind if Docker automatically trusts a repository key, so long as it doesn't automatically trust a root key, AND provided that it checks the root key along with the repository key and will fail if either one fails to match.)

**Comment by cpuguy83** [comment]
ping @diogomonica @NathanMcCauley

**Comment by thaJeztah** [comment]
also cc @endophage (for notary)

**Comment by endophage** [comment]
@mrled this is a use case on our near future TODO list. We absolutely intend to support it in Notary as it's a hard requirement from enterprise users. I'd suggest the [Notary](https://github.com/docker/notary) repository is the correct place to track this feature request as the implementation will be done there.

**Comment by thaJeztah** [comment]
Thanks @endophage!

@mrled can you reopen this in the notary repository/issue tracker? (also search for existing issues, perhaps there's one already).

I'm going to close this issue here, because it's better tracked in the notary issue tracker. Thanks for opening this issue!
