### ISSUE TITLE
duplicated text in https://docs.docker.com/engine/userguide/networking/get-started-overlay/

### ISSUE THREAD

**Issue by vipconsult** [docker/docker#18482]
steps 7 and 8 are duplicated as 9 and 10

https://docs.docker.com/engine/userguide/networking/get-started-overlay/

**Comment by WeiZhang555** [comment]
Hmmm, it's weird that the source file is correct https://github.com/docker/docker/blob/master/docs/userguide/networking/get-started-overlay.md#step-6-extra-credit-with-docker-compose,  maybe the website need some updates according to the source.

**Comment by thaJeztah** [comment]
Looks like this went wrong when cherry picking; the steps are indeed duplicated in the docs branch; https://github.com/docker/docker/blob/a3e00dc588cb30d85167e144f89ae91310d08c95/docs/userguide/networking/get-started-overlay.md

Looks like the same PR was cherry-picked twice 
https://github.com/docker/docker/blame/docs/docs/userguide/networking/get-started-overlay.md

**Comment by aditirajagopal** [comment]
ping @thaJeztah -- this issue can be closed

**Comment by thaJeztah** [comment]
@aditirajagopal thanks! Github didn't auto-close for some reason. Yup this can be closed
