### ISSUE TITLE
docker daemon crashes on invalid pull response from registry

### ISSUE THREAD

**Issue by allbinmani** [docker/docker#18481]
I tried pulling from my own repository impl, which returned an invalid response (that I cannot reproduce), and the docker daemon crashed with `http: panic serving @: runtime error: index out of range`, and a stack trace. After this, docker daemon is unresponsive to any further requests, and needs to be killed and restarted.

This is not an issue for me, simply reporting it because crash dumps may help debug more sinister problems, and because a crashed docker daemon simply does no good.

>$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:16:54 UTC 2015
 OS/Arch:      linux/amd64

>Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:16:54 UTC 2015
 OS/Arch:      linux/amd64

>$ docker info
Containers: 14
Images: 181
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-37-generic
Operating System: Ubuntu 15.04
CPUs: 2
Total Memory: 3.389 GiB
Name: vubuntu
Debug mode (server): true
 File Descriptors: 21
 Goroutines: 36
 System Time: 2015-12-08T01:08:37.205427009+01:00
 EventsListeners: 0
 Init SHA1: cb6202012127c6358fb9103142085152725b116f
 Init Path: /usr/lib/docker/dockerinit
 Docker Root Dir: /work/docker
Username: anonymous
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

Full debug output:
> $ sudo docker daemon --storage-driver=overlay --dns 8.8.8.8 --storage-driver=overlay -D -H tcp://127.0.0.1:4243 -H unix:///var/run/docker.sock
WARN[0000] /!\ DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING /!\ 
DEBU[0000] Server created for HTTP on tcp (127.0.0.1:4243) 
DEBU[0000] docker group found. gid: 134                 
DEBU[0000] Server created for HTTP on unix (/var/run/docker.sock) 
INFO[0000] API listen on 127.0.0.1:4243                 
INFO[0000] API listen on /var/run/docker.sock           
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using default logging driver json-file       
DEBU[0000] Creating images graph                        
DEBU[0000] Restored 181 elements                        
DEBU[0000] Creating repository list                     
DEBU[0000] Option DefaultDriver: bridge                 
DEBU[0000] Option DefaultNetwork: bridge                
INFO[0000] Firewalld running: false                     
DEBU[0000] /sbin/iptables, [--wait -t nat -D PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t nat -D PREROUTING] 
DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT]    
DEBU[0000] /sbin/iptables, [--wait -t nat -F DOCKER]    
DEBU[0000] /sbin/iptables, [--wait -t nat -X DOCKER]    
DEBU[0000] /sbin/iptables, [--wait -t nat -n -L DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t nat -N DOCKER]    
DEBU[0000] /sbin/iptables, [--wait -t filter -n -L DOCKER] 
DEBU[0000] Registering ipam provider: default           
DEBU[0000] releasing IPv4 pools from network bridge (3c1bd0e2a49a43f55f8738f85be6f950bd99e8a39c7a92dc1b422c99f9f25e36) 
DEBU[0000] ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.1) 
DEBU[0000] Retrieving bitmask (LocalDefault/172.17.0.0/16, 172.17.0.0/16) 
DEBU[0000] ReleasePool(LocalDefault/172.17.0.0/16)      
INFO[0000] Default bridge (docker0) is assigned with an IP address 172.17.0.1/16. Daemon option --bip can be used to set a preferred IP address 
DEBU[0000] Allocating IPv4 pools for network bridge (6a63acda1147ffb39973ae57546cc9b6e608de19cafc49e359635419245eaea8) 
DEBU[0000] RequestPool(LocalDefault, 172.17.0.1/16, , map[], false) 
DEBU[0000] RequestAddress(LocalDefault/172.17.0.0/16, 172.17.0.1, map[]) 
DEBU[0000] /sbin/iptables, [--wait -t nat -C POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE] 
DEBU[0000] /sbin/iptables, [--wait -D FORWARD -i docker0 -o docker0 -j DROP] 
DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -i docker0 -o docker0 -j ACCEPT] 
DEBU[0001] /sbin/iptables, [--wait -t filter -C FORWARD -i docker0 ! -o docker0 -j ACCEPT] 
DEBU[0001] /sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT] 
DEBU[0001] /sbin/iptables, [--wait -t nat -C PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0001] /sbin/iptables, [--wait -t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0001] /sbin/iptables, [--wait -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8] 
DEBU[0001] /sbin/iptables, [--wait -t nat -A OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8] 
DEBU[0001] /sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -j DOCKER] 
WARN[0001] Your kernel does not support swap memory limit. 
DEBU[0001] Cleaning up old shm/mqueue mounts: start.    
DEBU[0001] Cleaning up old shm/mqueue mounts: done.     

.. starting a few containers here

> INFO[0002] Daemon has completed initialization          
INFO[0002] Docker daemon                                 commit=a34a1d5 execdriver=native-0.2 graphdriver=overlay version=1.9.1
DEBU[0002] Registering routers                          
DEBU[0002] Registering HEAD, /containers/{name:.*}/archive 
DEBU[0002] Registering OPTIONS, /                       
DEBU[0002] Registering GET, /_ping                      
DEBU[0002] Registering GET, /events                     
DEBU[0002] Registering GET, /info                       
DEBU[0002] Registering GET, /version                    
DEBU[0002] Registering GET, /images/json                
DEBU[0002] Registering GET, /images/search              
DEBU[0002] Registering GET, /images/get                 
DEBU[0002] Registering GET, /images/{name:.*}/get       
DEBU[0002] Registering GET, /images/{name:.*}/history   
DEBU[0002] Registering GET, /images/{name:.*}/json      
DEBU[0002] Registering GET, /containers/json            
DEBU[0002] Registering GET, /containers/{name:.*}/export 
DEBU[0002] Registering GET, /containers/{name:.*}/changes 
DEBU[0002] Registering GET, /containers/{name:.*}/json  
DEBU[0002] Registering GET, /containers/{name:.*}/top   
DEBU[0002] Registering GET, /containers/{name:.*}/logs  
DEBU[0002] Registering GET, /containers/{name:.*}/stats 
DEBU[0002] Registering GET, /containers/{name:.*}/attach/ws 
DEBU[0002] Registering GET, /exec/{id:.*}/json          
DEBU[0002] Registering GET, /containers/{name:.*}/archive 
DEBU[0002] Registering GET, /volumes                    
DEBU[0002] Registering GET, /volumes/{name:.*}          
DEBU[0002] Registering POST, /auth                      
DEBU[0002] Registering POST, /commit                    
DEBU[0002] Registering POST, /build                     
DEBU[0002] Registering POST, /images/create             
DEBU[0002] Registering POST, /images/load               
DEBU[0002] Registering POST, /images/{name:.*}/push     
DEBU[0002] Registering POST, /images/{name:.*}/tag      
DEBU[0002] Registering POST, /containers/create         
DEBU[0002] Registering POST, /containers/{name:.*}/kill 
DEBU[0002] Registering POST, /containers/{name:.*}/pause 
DEBU[0002] Registering POST, /containers/{name:.*}/unpause 
DEBU[0002] Registering POST, /containers/{name:.*}/restart 
DEBU[0002] Registering POST, /containers/{name:.*}/start 
DEBU[0002] Registering POST, /containers/{name:.*}/stop 
DEBU[0002] Registering POST, /containers/{name:.*}/wait 
DEBU[0002] Registering POST, /containers/{name:.*}/resize 
DEBU[0002] Registering POST, /containers/{name:.*}/attach 
DEBU[0002] Registering POST, /containers/{name:.*}/copy 
DEBU[0002] Registering POST, /containers/{name:.*}/exec 
DEBU[0002] Registering POST, /exec/{name:.*}/start      
DEBU[0002] Registering POST, /exec/{name:.*}/resize     
DEBU[0002] Registering POST, /containers/{name:.*}/rename 
DEBU[0002] Registering POST, /volumes/create            
DEBU[0002] Registering PUT, /containers/{name:.*}/archive 
DEBU[0002] Registering DELETE, /containers/{name:.*}    
DEBU[0002] Registering DELETE, /images/{name:.*}        
DEBU[0002] Registering DELETE, /volumes/{name:.*}       
DEBU[0002] Registering GET, /networks                   
DEBU[0002] Registering GET, /networks/{id:.*}           
DEBU[0002] Registering POST, /networks/create           
DEBU[0002] Registering POST, /networks/{id:.*}/connect  
DEBU[0002] Registering POST, /networks/{id:.*}/disconnect 
DEBU[0002] Registering DELETE, /networks/{id:.*}        
DEBU[0002] Registering routers                          
DEBU[0002] Registering HEAD, /containers/{name:.*}/archive 
DEBU[0002] Registering OPTIONS, /                       
DEBU[0002] Registering GET, /_ping                      
DEBU[0002] Registering GET, /events                     
DEBU[0002] Registering GET, /info                       
DEBU[0002] Registering GET, /version                    
DEBU[0002] Registering GET, /images/json                
DEBU[0002] Registering GET, /images/search              
DEBU[0002] Registering GET, /images/get                 
DEBU[0002] Registering GET, /images/{name:.*}/get       
DEBU[0002] Registering GET, /images/{name:.*}/history   
DEBU[0002] Registering GET, /images/{name:.*}/json      
DEBU[0002] Registering GET, /containers/json            
DEBU[0002] Registering GET, /containers/{name:.*}/export 
DEBU[0002] Registering GET, /containers/{name:.*}/changes 
DEBU[0002] Registering GET, /containers/{name:.*}/json  
DEBU[0002] Registering GET, /containers/{name:.*}/top   
DEBU[0002] Registering GET, /containers/{name:.*}/logs  
DEBU[0002] Registering GET, /containers/{name:.*}/stats 
DEBU[0002] Registering GET, /containers/{name:.*}/attach/ws 
DEBU[0002] Registering GET, /exec/{id:.*}/json          
DEBU[0002] Registering GET, /containers/{name:.*}/archive 
DEBU[0002] Registering GET, /volumes                    
DEBU[0002] Registering GET, /volumes/{name:.*}          
DEBU[0002] Registering POST, /auth                      
DEBU[0002] Registering POST, /commit                    
DEBU[0002] Registering POST, /build                     
DEBU[0002] Registering POST, /images/create             
DEBU[0002] Registering POST, /images/load               
DEBU[0002] Registering POST, /images/{name:.*}/push     
DEBU[0002] Registering POST, /images/{name:.*}/tag      
DEBU[0002] Registering POST, /containers/create         
DEBU[0002] Registering POST, /containers/{name:.*}/kill 
DEBU[0002] Registering POST, /containers/{name:.*}/pause 
DEBU[0002] Registering POST, /containers/{name:.*}/unpause 
DEBU[0002] Registering POST, /containers/{name:.*}/restart 
DEBU[0002] Registering POST, /containers/{name:.*}/start 
DEBU[0002] Registering POST, /containers/{name:.*}/stop 
DEBU[0002] Registering POST, /containers/{name:.*}/wait 
DEBU[0002] Registering POST, /containers/{name:.*}/resize 
DEBU[0002] Registering POST, /containers/{name:.*}/attach 
DEBU[0002] Registering POST, /containers/{name:.*}/copy 
DEBU[0002] Registering POST, /containers/{name:.*}/exec 
DEBU[0002] Registering POST, /exec/{name:.*}/start      
DEBU[0002] Registering POST, /exec/{name:.*}/resize     
DEBU[0002] Registering POST, /containers/{name:.*}/rename 
DEBU[0002] Registering POST, /volumes/create            
DEBU[0002] Registering PUT, /containers/{name:.*}/archive 
DEBU[0002] Registering DELETE, /containers/{name:.*}    
DEBU[0002] Registering DELETE, /images/{name:.*}        
DEBU[0002] Registering DELETE, /volumes/{name:.*}       
DEBU[0002] Registering GET, /networks                   
DEBU[0002] Registering GET, /networks/{id:.*}           
DEBU[0002] Registering POST, /networks/create           
DEBU[0002] Registering POST, /networks/{id:.*}/connect  
DEBU[0002] Registering POST, /networks/{id:.*}/disconnect 
DEBU[0002] Registering DELETE, /networks/{id:.*}        

> INFO[0400] POST /v1.21/images/create?fromImage=my.private.repo%2Flibrary%2Fbusybox%3Alatest 
DEBU[0400] Trying to pull my.private.repo/library/busybox from https://my.private.repo v2 
DEBU[0400] Pulling tag from V2 registry: "latest"       
2015/12/08 00:55:13 http: panic serving @: runtime error: index out of range
goroutine 483 [running]:
net/http.func·011()
	/usr/local/go/src/net/http/server.go:1130 +0xbb
github.com/docker/docker/registry.ContinueOnError(0x7f4b5c4372c8, 0xc20902e2c0, 0x6)
	/usr/src/docker/.gopath/src/github.com/docker/docker/registry/registry.go:215 +0xfc
github.com/docker/docker/graph.(*v2Puller).Pull(0xc208e48820, 0xc2088b14ef, 0x6, 0x16, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/graph/pull_v2.go:46 +0x302
github.com/docker/docker/graph.(*TagStore).Pull(0xc208805140, 0xc2088b14d0, 0x1e, 0xc2088b14ef, 0x6, 0xc208c5bd40, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/graph/pull.go:109 +0x6e9
github.com/docker/docker/daemon.(*Daemon).PullImage(0xc20807f400, 0xc2088b14d0, 0x1e, 0xc2088b14ef, 0x6, 0xc208c5bd40, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/daemon.go:1035 +0x73
github.com/docker/docker/api/server/router/local.(*router).postImagesCreate(0xc2085d1000, 0x7f4b5c4ca9f0, 0xc2088b1290, 0x7f4b5c4ca9b8, 0xc208e48780, 0xc208b4a9c0, 0xc2088b0f00, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/local/image.go:129 +0xd19
github.com/docker/docker/api/server/router/local.*router.(github.com/docker/docker/api/server/router/local.postImagesCreate)·fm(0x7f4b5c4ca9f0, 0xc2088b1290, 0x7f4b5c4ca9b8, 0xc208e48780, 0xc208b4a9c0, 0xc2088b0f00, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/local/local.go:125 +0x7b
github.com/docker/docker/api/server.func·004(0x7f4b5c4ca9f0, 0xc2088b1290, 0x7f4b5c4ca9b8, 0xc208e48780, 0xc208b4a9c0, 0xc2088b0f00, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware.go:87 +0x7c7
github.com/docker/docker/api/server.func·003(0x7f4b5e991a50, 0xc208028f28, 0x7f4b5c4ca9b8, 0xc208e48780, 0xc208b4a9c0, 0xc2088b0f00, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware.go:66 +0x10e
github.com/docker/docker/api/server.func·002(0x7f4b5e991a50, 0xc208028f28, 0x7f4b5c4ca9b8, 0xc208e48780, 0xc208b4a9c0, 0xc2088b0f00, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware.go:49 +0x47c
github.com/docker/docker/api/server.func·001(0x7f4b5e991a50, 0xc208028f28, 0x7f4b5c4ca9b8, 0xc208e48780, 0xc208b4a9c0, 0xc2088b0f00, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware.go:27 +0x1dc
github.com/docker/docker/api/server.func·007(0x7f4b5c4ca9b8, 0xc208e48780, 0xc208b4a9c0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:156 +0x265
net/http.HandlerFunc.ServeHTTP(0xc208aaef20, 0x7f4b5c4ca9b8, 0xc208e48780, 0xc208b4a9c0)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc208570c80, 0x7f4b5c4ca9b8, 0xc208e48780, 0xc208b4a9c0)
	/usr/src/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x297
net/http.serverHandler.ServeHTTP(0xc208048a20, 0x7f4b5c4ca9b8, 0xc208e48780, 0xc208b4a9c0)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208e48640)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e

**Comment by aaronlehmann** [comment]
Thanks for the report. I'll look into this.
