### ISSUE TITLE
syslog priority: severity is not tuneable

### ISSUE THREAD

**Issue by tzz** [docker/docker#18480]
I couldn't find this reported elsewhere, so... sorry if it's a duplicate.

I'm looking at the `master` branch.  This is not a bug hence I can't provide any bug report data.

In the message priority, currently the Docker syslog driver can only do severity `ERR` or `INFO`, depending on whether the message was in `STDERR` or `STDOUT`.

A "soft" way to add severity would be to follow the spec in the `--prio-prefix` logger option, which is in newer implementations. See http://man7.org/linux/man-pages/man1/logger.1.html but basically you prefix with `<3> ` to indicate numeric severity 3.

However it's done, it would be really helpful to have at least 4 severity levels.

**Comment by thaJeztah** [comment]
interesting read on log levels http://dave.cheney.net/2015/11/05/lets-talk-about-logging (just remembered this coming up recently)

**Comment by LK4D4** [comment]
I think this was superseded by #22736
