### ISSUE TITLE
[Question] Is it possible to specify a container IP address on `docker run`

### ISSUE THREAD

**Issue by robbrockbank** [docker/docker#18489]
I'm using my own docker network and ipam driver, and am wondering if it is possible to request a particular IP address rather than having IPAM auto-assign one.

For example, I'd like to specify an IP address on the `docker run` command. 

Is this possible?

dev:~$ docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64
dev:~$ docker info
Containers: 4
Images: 102
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 118
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-15-generic
Operating System: Ubuntu 15.04
CPUs: 1
Total Memory: 3.86 GiB
Name: dev
ID: H2E7:VK52:6P4T:A2X5:ZZPQ:CAPE:63GT:F2JB:QSG6:UDTQ:6GWN:BF4T
WARNING: No swap limit support
dev:~$ uname -a
Linux dev 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cpuguy83** [comment]
Nope, but see #6743 for tracking this.

**Comment by mzayikin** [comment]
Is there any workaround for version prior **1.10** where` --ip `flag was introduced?

**Comment by thaJeztah** [comment]
not that I know; upgrade to the current release to get new features.
