### ISSUE TITLE
Container inspect Volumes&Binds inconsistencies

### ISSUE THREAD

**Issue by runcom** [docker/docker#18494]
Noticed the following behavior:
```
$ docker volume create --name avolume
avolume
$ docker create -v avolume:/test busybox true
d038044ada5ad8213155a51123792b385bf3207bc2cef632b9000741a9a2c055
$ docker inspect d038044ada5ad8213155a51123792b385bf3207bc2cef632b9000741a9a2c055 | jq ".[0].Config.Volumes"
null
$ docker inspect d038044ada5ad8213155a51123792b385bf3207bc2cef632b9000741a9a2c055 | jq ".[0].HostConfig.Binds"
[
  "avolume:/test"
]
```
while:
```
$ docker create -v /test busybox true        
3e72436ad97143776ff6aafefea5b22f6da5acc17b70873b7a75dfe920ca236b
$ docker inspect 3e72436ad97143776ff6aafefea5b22f6da5acc17b70873b7a75dfe920ca236b | jq ".[0].Config.Volumes"
{
  "/test": {}
}
$ docker inspect 3e72436ad97143776ff6aafefea5b22f6da5acc17b70873b7a75dfe920ca236b | jq ".[0].HostConfig.Binds"
null
```
Is there any reason why the first volume is shown in `HostConfig.Binds` and not in `Config.Volumes` and viceversa? I thought I would see both in `Config.Volumes` given the first was created with `docker volume` and the second auto add a volume. I think the same happens with `docker run` but haven't tested it yet.

**Comment by runcom** [comment]
ping @cpuguy83 @calavera

**Comment by cpuguy83** [comment]
This is expected, IMO.
This is effectively a bind.

**Comment by runcom** [comment]
both are ` /var/lib/docker/0.0/volumes/CONTAINERID/_data` and both are listed under `docker volume ls`. To me seems weird the first one isn't listed in `Volumes`

**Comment by calavera** [comment]
I agree that it looks inconsistent. `docker run -v /test` creates an "anonymous" volume that should be listed in the same way that name volumes are listed. I don't think it's worth adding to 1.9.2 since it's not a regression in the 1.9.x series, I'm pretty sure it was there in 1.8 too.

**Comment by runcom** [comment]
My need here is to understand if there are any volumes for the container. I can count on `Config.Volumes` first but didn't want to go through the logic of understanding if the bind is from an *anonymous* volume reading `HostConfig.Binds`.
@calavera do you have any preference about how to fix this? just duplicating the bind in the volumes seems not the right thing to do. I'll happily take care of this if you have some idea.

**Comment by runcom** [comment]
> I don't think it's worth adding to 1.9.2 since it's not a regression in the 1.9.x series, I'm pretty sure it was there in 1.8 too.

I think this wasn't in 1.8.x because there was no `docker volume` command back then

**Comment by cpuguy83** [comment]
Named volumes existed in 1.7.

The reason this is in Binds is because the API accepts named volumes from binds.
I'd prefer to leave it unless we really fix the issue in the API and provide a mechanism to give a named volume in some other way (HostConfig.Mountpoints???).

tbh, I hate that HostConfig.Binds is implemented as it is in the API.

**Comment by runcom** [comment]
@cpuguy83 so right now if I want to know if someone used `-v volumename:/path` I just need to make sure `volumename` isn't `Abs` (in `Binds`)?

**Comment by cpuguy83** [comment]
At create time? Yes.

**Comment by LK4D4** [comment]
Not sure about whole story, but I see question and I see answer.
