### ISSUE TITLE
docker push is not parallel

### ISSUE THREAD

**Issue by liangmingyuanneo** [docker/docker#18498]
I have read the source code of docker push and docker pull, docker pull is parallel but docker push not. When docker push images, docker client will read layer json first to get metadata, then we can get all layer metadata at a loop to make up manifest. So we can push images parallel. Why docker client does not use this manner instead of pushing images  serial?

**Comment by thaJeztah** [comment]
There are some existing issues on optimizing push. Some optimizations still need to be implemented, or researched if they actually bring a performance improvent. This discussion makes mention on enabling parallel push in the client; https://github.com/docker/docker/issues/13250#issuecomment-102547028


/cc @stevvooe is parallel push still being considered?

**Comment by tonistiigi** [comment]
This is being addressed in #18353.

**Comment by thaJeztah** [comment]
@tonistiigi oh! you're right, I missed the "concurrently" part of the PR :+1:

**Comment by phemmer** [comment]
Also a dup of #9132, which is unfortunately in closed state :-(

**Comment by tonistiigi** [comment]
@phemmer There are 2 cases here. One is to push multiple images on the same time(already addressed), other is to upload layers concurrently for a single push.

**Comment by stevvooe** [comment]
@phemmer That is yet a different variation on "parallel". This issue request layer parallelization, which is not implemented as of yet (until #18353, I believe).

@liangmingyuanneo Going into a little history, the docker client push/pull code was historically single threaded. Additions of parallelization have resulted in dataset corruption. We've been slowly bolstering the code and working those issues out.
