### ISSUE TITLE
some network related files are written to /var/lib/docker even if using the daemon's -g option

### ISSUE THREAD

**Issue by sebi-hgdata** [docker/docker#18508]
I see some files written in /var/lib/docker even if I use the -g option:

$ sudo docker info
Containers: 0
Images: 416
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.3.0-040300-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 8
Total Memory: 7.706 GiB
Name: seb
ID: B2M7:KYAT:FVQA:TA6R:FLAN:DUF5:224N:JFD3:E4UF:KL2Y:FHDM:FPCI
Username: sebihgdata
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Cluster store: consul://localhost:8500
Cluster advertise: 192.168.0.106:2375
$ sudo docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
$ uname -a
Linux seb 4.3.0-040300-generic #201511020949 SMP Mon Nov 2 14:50:44 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ ps -aef|grep docker
root      4634     1  0 22:58 ?        00:00:01 /usr/bin/docker daemon --userland-proxy=false --cluster-advertise=wlan0:2375 --cluster-store consul://localhost:8500 --tlsverify --tlscacert=/etc/ssl/docker/ca.cert --tlscert=/etc/ssl/docker/swarm.cert --tlskey=/etc/ssl/docker/swarm.key -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock --bip=172.17.42.1/16 --dns 8.8.8.8 --dns 8.8.4.4 -s overlay -g /home/seb/hgdata/deployments/docker
$ sudo ls -al /var/lib/docker
total 12
drw-------  3 root root 4096 nov 28 21:50 .
drwxr-xr-x 77 root root 4096 nov 28 21:50 ..
drw-------  3 root root 4096 dec  8 22:58 network
$ sudo ls -al /var/lib/docker/network/files
total 8
drw------- 2 root root 4096 dec  8 22:58 .
drw------- 3 root root 4096 dec  8 22:58 ..
srw------- 1 root root    0 dec  8 22:58 b673f9086e2d183e888d8febe2d75cde644d25ba60263d31c408ebb04834af7d.sock
$ sudo docker network ls
NETWORK ID          NAME                DRIVER
6ef5e8f4bb34        bridge              bridge  
a261ee43d4c6        none                null  
2a0486610826        host                host 
s$ sudo service docker stop
docker stop/waiting
$ sudo ls -al /var/lib/docker/network/files
total 8
drw------- 2 root root 4096 dec  8 23:08 .
drw------- 3 root root 4096 dec  8 22:58 ..

$ sudo service docker start
docker start/running, process 4980

$ sudo ls -al /var/lib/docker/network/files
total 8
drw------- 2 root root 4096 dec  8 23:09 .
drw------- 3 root root 4096 dec  8 22:58 ..
srw------- 1 root root    0 dec  8 23:09 a9b1e47af2a285d4cb024ae29b34f18ae006a490c93460ac86eb979fa8f3458f.sock

**Comment by thaJeztah** [comment]
Yes, the current libnetwork version has these paths hardcoded, but this is being fixed in https://github.com/docker/libnetwork/pull/742

/cc @aboch @calavera

**Comment by tianon** [comment]
This is a massive pain if one is dealing with a read-only `/` filesystem where `/var/lib/docker` cannot be created (and thus `--graph` is used to give Docker a different location to store files in). :cry:

**Comment by thaJeztah** [comment]
Adding this to the milestone, per https://github.com/docker/libnetwork/issues/747#issuecomment-232667222

**Comment by thaJeztah** [comment]
ping @mavenugo I see https://github.com/docker/libnetwork/pull/1328 was merged; was this issue resolved? (and do you know which release?)

**Comment by schokkarapu-rms** [comment]
@thaJeztah : is this issue fixed?

my env on centos 7:
```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64
```

i added the following to :  `/etc/systemd/system/docker.service.d/override.conf`
```
[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon --storage-driver=overlay -H fd:// -g /datadisk/docker```

but still files are here: 
```
ll /var/lib/docker/network/files/
total 0
srw-------. 1 root root 0 Nov 14 14:59 7d43489f7eb0e4f2b1ccdd1e9034ff8b9df4e5fec2fc064086c58c5e4d44f4ba.sock
srw-------. 1 root root 0 Nov 14 17:37 961b4fbb80bd0a2650a4e1f27b03c08ae2cdba7ce7a3b6974854dcd6b0f10032.sock
```

**Comment by thaJeztah** [comment]
Looks like it's not in 1.11; https://github.com/docker/docker/blob/v1.11.2/vendor/src/github.com/docker/libnetwork/sandbox_externalkey_unix.go#L18

But the change is in 1.12; https://github.com/docker/docker/blob/v1.12.3/vendor/src/github.com/docker/libnetwork/sandbox_externalkey_unix.go#L18

Merged in https://github.com/docker/docker/pull/24237, and cherry-picked into 1.12 through; https://github.com/docker/docker/pull/25045

So looks like this can be closed

**Comment by schokkarapu-rms** [comment]
thanks for your response @thaJeztah. 

when i move to docker version 1.12, when I use `-g /datadisk/docker` flag, will it create those network socket files to `/run/docker/libnetwork/`, right?

**Comment by cueedee** [comment]
For future visitors who like me are wondering what that `-g` option (or its `--graph` long form cousin) does; [apparently](/docker/docs/blob/0721d8a719df6ca3b728a680ea11fc9b2193f5f0/content/engine/release-notes/17.05.md?plain=1#L44), it is the former nomer for what is now `--data-root`;

**Comment by thaJeztah** [comment]
(let me x-post here as well); https://github.com/moby/moby/issues/21988#issuecomment-1720865253

> Yes, correct. storage drivers used to be referred to as graph drivers. It was later changed to a more generic "storage drivers", because the "graph driver" name was based on how they were _implemented_, not what they did (and there were already plans to change the implementation; which is what became `snapshotters` in containerd.
> 
> (there's still a lot of references to "graph drivers" - at least in the code though!)
