### ISSUE TITLE
Docker volumes with Z option fail if the host directory is missing

### ISSUE THREAD

**Issue by jfindley** [docker/docker#18528]
Description of problem:
Docker volumes with Z option fail if the host directory is missing.  This is unique to the Z modes - RW/RO create the directory if it's not present.

`docker version`:
Client:
 Version:         1.9.1-fc23
 API version:     1.21
 Package version: docker-1.9.1-2.git78bc3ea.fc23.x86_64
 Go version:      go1.5.1
 Git commit:      f7c1d52-dirty
 Built:           Fri Nov 20 21:07:14 UTC 2015
 OS/Arch:         linux/amd64

Server:
 Version:         1.9.1-fc23
 API version:     1.21
 Package version: docker-1.9.1-2.git78bc3ea.fc23.x86_64
 Go version:      go1.5.1
 Git commit:      f7c1d52-dirty
 Built:           Fri Nov 20 21:07:14 UTC 2015
 OS/Arch:         linux/amd64

`docker info`:
Containers: 4
Images: 58
Server Version: 1.9.1-fc23
Storage Driver: devicemapper
 Pool Name: atomicos-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 2.919 GB
 Data Space Total: 15.77 GB
 Data Space Available: 12.86 GB
 Metadata Space Used: 1.065 MB
 Metadata Space Total: 46.14 MB
 Metadata Space Available: 45.07 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.109 (2015-09-22)
Execution Driver: native-0.2
Logging Driver: journald
Kernel Version: 4.2.6-301.fc23.x86_64
Operating System: Fedora 23 (Twenty Three)
CPUs: 2
Total Memory: 1.954 GiB
Name: ip-10-0-2-15.eu-west-1.compute.internal
ID: X46Y:VYPI:E6BC:JFBF:WLJO:LCFF:7KG5:BQFX:GFFW:MTTD:A5RT:AEF4

`uname -a`:
Linux ip-10-0-2-15.eu-west-1.compute.internal 4.2.6-301.fc23.x86_64 #1 SMP Fri Nov 20 22:22:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
VirtualBox (OSX), OS is fedora-atomic-23

How reproducible:
Always

Steps to Reproduce:
1. docker run -v /path/that/does/not/exist:/path:Z image
2.
3.

Actual Results:
Error response from daemon: no such file or directory

Expected Results:
Docker creates /path/that/does/not/exist and runs the image.  This is the normal behaviour when using RW or RO modes.

**Comment by thaJeztah** [comment]
I'm unable to reproduce this on our docker 1.9.1 release; I just spun up a Fedora 23 droplet on DigitalOcean, installed docker and this seems to work.

I see you're running a RedHat build of docker, can you try if you're able to reproduce this using our builds http://docs.docker.com/engine/installation/fedora/, or open this issue in the RedHat issue tracker; https://bugzilla.redhat.com/ ?


```
$ docker run -v /path/that/does/not/exist:/path:Z -it --rm ubuntu
root@50f190256da1:/# exit
exit
[root@issue-18528 ~]# sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      29
```
```
[root@issue-18528 ~]# docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:39:26 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:39:26 UTC 2015
 OS/Arch:      linux/amd64
[root@issue-18528 ~]# docker info
Containers: 0
Images: 4
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-252:1-262174-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.058 GB
 Data Space Total: 107.4 GB
 Data Space Available: 28.85 GB
 Metadata Space Used: 1.72 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107 (2015-09-05)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.3-300.fc23.x86_64
Operating System: Fedora 23 (Cloud Edition)
CPUs: 1
Total Memory: 993.5 MiB
Name: issue-18528
ID: 23TD:YNDV:PCB5:73ID:5445:K6A7:P34U:TZOQ:6F3J:IZ7R:SVWC:VDQJ
```

**Comment by runcom** [comment]
I'm able to reproduce this on rawhide with rh docker. Looking

**Comment by cpuguy83** [comment]
This is most certainly a dup. I know @rhatdan fixed this at least on master.

**Comment by thaJeztah** [comment]
@cpuguy83 ah, you're right; looks like a duplicate of https://github.com/docker/docker/issues/17262, and the issue tracking this at redhat https://bugzilla.redhat.com/show_bug.cgi?id=1274210

Not sure if it's resolved though seeing that that one was closed as "not a bug"

**Comment by thaJeztah** [comment]
Also this one; https://github.com/docker/docker/issues/17240

**Comment by rhatdan** [comment]
It was closed as not a bug because SELinux code was handling this correctly.  Failing on non existing directory.

**Comment by jfindley** [comment]
Yep, I see that now - apparently this will fail for all volumes in docker 0.11+.  That's alarming as it will break all sorts of things, but this isn't the place to discuss that.

Thanks for looking at this everyone - closing the issue.
