### ISSUE TITLE
Commands not found during launch of Docker QuickStart Terminal (zsh)

### ISSUE THREAD

**Issue by ThomasChambonDev** [docker/docker#18537]
I installed the Docker toolbox, and it went fine (note : it skipped the "VM" step).

But when I launch the Docker Quickstart Terminal, I get these errors :

>bash --login '/Applications/Docker/Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh'
/Applications/Docker/Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh: line 14: clear: command not found
Creating Machine default...
/Applications/Docker/Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh: line 27: rm: command not found
Driver "virtualbox" not found. Do you have the plugin binary accessible in your PATH?
Host does not exist: "default"
Starting machine default...
Host does not exist: "default"
/Applications/Docker/Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh: line 37: yes: command not found
Regenerate TLS machine certs?  Warning: this is irreversible. (y/n): EOF
Setting environment variables for machine default...
/Applications/Docker/Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh: line 41: clear: command not found
/Applications/Docker/Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh: line 43: cat: command not found
Host does not exist: "default"
docker is configured to use the default machine with IP 
For help getting started, check out the docs at https://docs.docker.com

>Host does not exist: "default"
/Applications/Docker/Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh: line 63: dscl: command not found
/Applications/Docker/Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh: line 63: awk: command not found
/Applications/Docker/Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh: line 63: head: command not found

It seems to try to launch bash commands, though on mac OS X I get a zsh shell by default.

Does someone got the same error ?

**Comment by thaJeztah** [comment]
What version of OS X are you using? I think they changed to bash by default at some point, but not sure.

However, this issue is better handled in the Docker Toolbox issue tracker. Can you reopen that issue there? You can find the issue tracker here; https://github.com/docker/toolbox/issues. It may be worth searching for existing issues, possibly there's one already.

Thanks for reporting this, I'm going to close this issue here, because we cannot fix this in this repository.
