### ISSUE TITLE
Breaking change in HostConfig.NetworkMode between Docker v1.7.1 and v1.8.3

### ISSUE THREAD

**Issue by berndv** [docker/docker#18532]
For containers that was run without any `--net` configuration, docker inspect now behaves differenty, since Docker version 1.8.3 and api version 1.20.

Docker v1.7.1, api v1.19 returnes: `"HostConfig.NetworkMode":"bridge"`

Docker v1.8.3, api v1.20 returnes: `"HostConfig.NetworkMode":"default"`

The change was introduced with commit 083300168fb0f42e022e9fa2ce47a7b2aac9967a

Actually, this has broken one of my applications that inspects docker containers and does different things for network mode bridge and host...

I also think it is not a good idea to let the clients decide what "default" means.

**Comment by thaJeztah** [comment]
Just a quick check; If you're using API 1.19 with docker 1.8.3, did that value also change?

**Comment by berndv** [comment]
Client v1.8.3 (API v1.20) is not compatible with Server v1.7.1 (API v1.19)

```
core@localhost ~ $ docker -H 192.168.56.11:2375 version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   cedd534-dirty
 Built:        Sat Dec  5 05:57:26 UTC 2015
 OS/Arch:      linux/amd64
Error response from daemon: client is newer than server (client API version: 1.20, server API version: 1.19)
```

But the other way round - Client v1.7.1 (API v1.19) and Server v1.8.3 (API v1.20) - the answer is yes.

```
core@localhost ~ $ docker -H 192.168.56.11:2375 version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): df2f73d-dirty
OS/Arch (client): linux/amd64
Server version: 1.8.3
Server API version: 1.20
Go version (server): go1.4.2
Git commit (server): cedd534-dirty
OS/Arch (server): linux/amd64
```

```
core@localhost ~ $ docker -H 192.168.56.11:2375 inspect nginx
[{
    ...
    "HostConfig": {
        ...
        "NetworkMode": "default",
		...
    },
	...
}]
```

**Comment by LK4D4** [comment]
It was a long time :( Closing issue because nothing can be done now.
