### ISSUE TITLE
Add `docker whoami` command

### ISSUE THREAD

**Issue by mohsen1** [docker/docker#18547]
Following [npm](https://docs.npmjs.com/cli/whoami) convention a `docker whoami` will be helpful for figuring our which account is logged in if any.

**Comment by calavera** [comment]
I'd rather not do this. The registry configuration is stored in the client, so something as simple as `cat ~/.docker/config.json` will give you the answer you're looking for.

**Comment by mohsen1** [comment]
Well, I for one didn't know I can do that. Other benefit of `docker whoami` is that you can easily use it in scripts.

**Comment by mountkin** [comment]
iirc the username of the current user is shown in the output of "docker info"

**Comment by thaJeztah** [comment]
Yup, `docker info | grep Username` should give you this information. I'm also not sure we need to add this; it feels like a minor enhancement, and we'd still need to maintain it

**Comment by calavera** [comment]
Indeed, plenty of options!

I'm sorry @mohsen1 but I think we should close this issue.

**Comment by mohsen1** [comment]
No reason to be sorry. I understand. Learned a bunch of command! :smile:

**Comment by spence** [comment]
@thaJeztah @calavera Can we do something here beyond `cat ~/.docker/config.json`? This file gives only the repository you had access to at one point. What it doesn't do:
1. Tell you if your token is expired
2. Give you the username that was used to login

I'm dealing with both cases at the moment and the best option is to assume you don't have access, wipe the file and re-authenticate.

**Comment by thaJeztah** [comment]
Docker doesn't know if the token expired, it's the registry that will return an error if it did, so that's gonna be quite difficult to get; tokens are also scoped to specific actions,  which makes it even more complicated

**Comment by thaJeztah** [comment]
In addition, if a credentials helper is used, no login information is managed by docker, but external to docker

**Comment by spence** [comment]
Ah ok thanks @thaJeztah
