### ISSUE TITLE
Image ID changes after 1.10 upgrade

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#18554]
If I have an image ID=X after 1.10 upgrade that ID become sha256:Y.  This causes issues with external systems (like mine) where the image ID just magically changed.  So handling and upgrade from 1.9 to 1.10 is going to be tricky.  Is there any way to avoid this?

**Comment by LK4D4** [comment]
ping @tonistiigi

**Comment by tonistiigi** [comment]
@ibuildthecloud No, sorry. Generated IDs do not have any meaning in `v1.10`. We could store the mapping somewhere if that helps(although there are possible cases where 2 images become one). All tags and container IDs are preserved.

**Comment by ibuildthecloud** [comment]
@tonistiigi If they don't having any mean, why did they change?  Does that mean X is just as valid as sha256:Y?  Does this mean if I pull an image multiple times I will get a different ID or the same ID?

**Comment by tonistiigi** [comment]
@ibuildthecloud `X` is generated, `sha256:Y` is not. Old IDs don't have any meaning because they are gone and can't be used for anything. `sha256:Y` or `Y` are only valid IDs after `v1.10`. `sha256:Y` is very stable and doesn't change on pulls or different hosts.

**Comment by thaJeztah** [comment]
For reference, see this PR that introduced this change https://github.com/docker/docker/pull/17924

**Comment by ibuildthecloud** [comment]
Ok, didn't hurt to ask.
