### ISSUE TITLE
The specified user settings file does not exist: /settings.xml

### ISSUE THREAD

**Issue by anacarlagb** [docker/docker#18551]
I'm starting docker, so I create a docker image to my application that it's using image maven to. (FROM maven). But my problem is when run maven install  that call settings.xml with  username and  password of .m2/repository, but on this step it's throw these ERROR: 
[ERROR] The specified user settings file does not exist: /settings.xml
The command '/bin/sh -c mvn install --settings settings.xml -DskipTests=true' returned a non-zero code: 1
I unknown if docker image use my password and my username. 
Can you help me?
Follow my Dockerfile:
FROM maven
ADD . /usr/src/
RUN curl -L http://jodconverter.googlecode.com/files/jodconverter-core-3.0-beta-4-dist.zip \
		-o /usr/src/jodconverter-core-3.0-beta-4-dist.zip && \
	unzip /usr/src/jodconverter-core-3.0-beta-4-dist.zip && \
	rm -f /usr/src/jodconverter-core-3.0-beta-4-dist.zip
RUN cd /usr/src/
RUN mvn install:install-file -Dfile=jodconverter-core-3.0-beta-4/lib/jodconverter-core-3.0-beta-4.jar -DgroupId=org.artofsolving.jodconverter -DartifactId=jodconverter-core -Dversion=3.0-beta-4 -Dpackaging=jar
RUN mvn install --settings settings.xml -DskipTests=true //error on this step
ENTRYPOINT ["java", "-jar", "/usr/src/target/clip-converter-1.0.jar"]

**Comment by thaJeztah** [comment]
Is the settings.xml file actually added to the image somewhere? I see `ADD . /usr/src/` which adds files to the `/usr/src/` directory, but `mvn install` seems to be looking for a file in the root directory.

Perhaps provide the full path (`--settings=/usr/src/setting.xml`) or adding a `WORKDIR /usr/src/` before that step would work?

I don't have experience with maven, but keep in mind that adding a file with credentials to an image is not advisable if you're planning to distribute that image. Even if you remove that file afterwards, it will still be present in intermediate images (each step in a Dockerfile produces a layer/image)

**Comment by anacarlagb** [comment]
Ok, thanks thaJeztah. 
So, I try with WORKDIR and run correctly.

**Comment by Pickacho** [comment]
> Ok, thanks thaJeztah. So, I try with WORKDIR, and run correctly.

Hi, @anacarlagb  did it solve your problem?
