### ISSUE TITLE
Docker Automated Build with tag not working with Bitbucket

### ISSUE THREAD

**Issue by ntquyen** [docker/docker#18556]
I have setup Docker automated build to linked with my private Bitbucket repo and try to trigger the build with default setting as "Branch". It works fine, even with automatically trigger by pushing changes to Bitbucket. But it doesn't work with tag. It doesn't trigger when I pushed a tag to Biubucket. Below is what I did:

1. In Docker Hub repo, tab "Build Details",  Tag Name set as `/^[0-9.]+$/` and Docker Tag Name set as `release-{sourceref}`. Saved.
2. Push tag changes:

```
$ git tag -a 1.0.1 -m "new tag 1.0.1"
$ git push --follow-tags
```
At this step, the build must have been triggered, but it wasn't.

One more notice, when I linked docker hub repo with Bitbucket repo, the link `https://registry.hub.docker.com/hooks/bitbucket` wasn't added automatically as it should be according to the docs https://docs.docker.com/docker-hub/bitbucket/. I had to add it manually to work with "Branch" build.

**Comment by calavera** [comment]
Hi @ntquyen!

I'm very sorry you're having issues with Docker Hub. Unfortunately, this is not the best place to redirect questions about automated builds.

Please feel free to contact support, they have more expertise about Hub and automated builds and they'll be happy to assist you:

https://support.docker.com/hc/en-us/restricted?return_to=https%3A%2F%2Fsupport.docker.com%2Fhc%2Fen-us

I'm going to close this issue so other maintainers don't get dragged into it. I hope you get the issue solved!

Cheers,
David
