### ISSUE TITLE
docker-registry:docker push 192.168.1.2:5000/hello-world

### ISSUE THREAD

**Issue by quanenmin** [docker/docker#18567]
docker version:Docker version 1.7.1, build 786b29d/1.7.1
docker info : 
   Containers: 9
   Images: 55
   Storage Driver: devicemapper
   Pool Name: docker-253:0-262596-pool
   Pool Blocksize: 65.54 kB
   Backing Filesystem: extfs
   Data file: /dev/loop0
   Metadata file: /dev/loop1
   Data Space Used: 2.778 GB
   Data Space Total: 107.4 GB
   Data Space Available: 45.2 GB
   Metadata Space Used: 4.379 MB
   Metadata Space Total: 2.147 GB
   Metadata Space Available: 2.143 GB
   Udev Sync Supported: true
   Deferred Removal Enabled: false
   Data loop file: /var/lib/docker/devicemapper/devicemapper/data
   Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
   Library Version: 1.02.95-RHEL6 (2015-09-08)
  Execution Driver: native-0.2
  Logging Driver: json-file
  Kernel Version: 3.10.93-1.el6.elrepo.x86_64
  Operating System: <unknown>
  CPUs: 8
  Total Memory: 7.691 GiB
  Name: localhost
  ID: MPHS:O5YO:4KFP:CDJG:D2CD:SXO4:RQKK:OYRL:RNMV:I6DV:S337:DPFC
  Username: quanenmin
  Registry: https://index.docker.io/v1/
  WARNING: No swap limit support

uname -a:
   Linux localhost 3.10.93-1.el6.elrepo.x86_64 #1 SMP Tue Nov 10 13:45:47 EST 2015 x86_64 x86_64 x86_64 GNU/Linux

the steps:
1、docker pull hello-world
2、docker tag hello-world 192.168.1.2:5000/hello-world
3、add '--insecure-registry 192.168.1.2:5000' to  /etc/default/docker
4、restart docker & registry

when I push image to registry ,the result:
Error response from daemon: invalid registry endpoint https://192.168.1.2:5000/v0/: unable to ping registry endpoint https://192.168.1.2:5000/v0/
v2 ping attempt failed with error: Get https://192.168.1.2:5000/v2/: dial tcp 192.168.1.2:5000: connection refused
 v1 ping attempt failed with error: Get https://192.168.1.2:5000/v1/_ping: dial tcp 192.168.1.2:5000: connection refused. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry 192.168.1.2:5000` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/192.168.1.2:5000/ca.crt

I just started studying Docker,so don't know how to solve this problem.
I tried some methods，Finally failed.

Who can help me?
 Thank you very much

                                                              Marico quan

**Comment by thaJeztah** [comment]
Please keep in mind that GitHub isn't a general support forum. This is an issue tracker for Docker bugs,
features and pull requests. Please take this into account when opening an issue.

This isn't a Docker bug, this is a question which is more appropriate for
1) the forums: https://forums.docker.com/
2) the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user
3) the #docker IRC channel on Freenode.

Could you ask your question in one of those channels? I'll close this issue here, but feel free to comment after I've closed.
