### ISSUE TITLE
parallel build RUN command

### ISSUE THREAD

**Issue by jkurz** [docker/docker#18581]
how does a command like 

```
RUN_P ["cd app1/; npm install", "cd app2; npm install"]
```

Both of these commands would run on separate threads asynchronously.

sound to you all? I think it would be cool to be able to run commands and parallelize build time.

**Comment by phemmer** [comment]
Why not use the shell?

     RUN ( cd app1/; npm install ) & ( cd app2; npm install ) & wait

**Comment by qq690388648** [comment]
Sorry, but the Dockerfile syntax belongs to frozen features. You can see the roadmap of docker here: https://github.com/docker/docker/blob/master/ROADMAP.md

**Comment by thaJeztah** [comment]
Thanks for suggesting @jkurz, I'm going to close this issue for the reasons mentioned above.
