### ISSUE TITLE
File contents inconsistent when volume is a vboxsf mount

### ISSUE THREAD

**Issue by doozr** [docker/docker#18584]
When using vboxsf to share a folder to a VM and that folder is mounted as a volume in a container, the contents of the files is inconsistent depending which program is used to view it.

BUG REPORT INFORMATION

Use the commands below to provide key information from your environment:

docker version:
Docker version 1.9.1, build a34a1d5

docker info: 
Containers: 1
Images: 7
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-8:1-262862-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem:
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.877 GB
 Data Space Total: 107.4 GB
 Data Space Available: 38.8 GB
 Metadata Space Used: 1.704 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-71-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 1.955 GiB
Name: vagrant-ubuntu-trusty-64
ID: VLLW:JXC3:YE3O:NOEL:AJTS:2IAN:KXMG:PR6H:O2D5:PEMH:C4FO:DRRV
WARNING: No swap limit support

uname -a: Linux vagrant-ubuntu-trusty-64 3.13.0-71-generic #114-Ubuntu SMP Tue Dec 1 02:34:22 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Provide additional environment details (AWS, VirtualBox, physical, etc.): VirtualBox 5.0.4 on Mac OS X 10.11.1 host.

List the steps to reproduce the issue:
1. Mount vboxfs share as a volume in a container
2. Edit a file in the volume outside the container
3. Observe that some processes in the container see different content to others

Describe the results you received:

Some processes (e.g. python, cat) always see the files as if they had not been edited, but others (e.g. vi, less) always see the current version.

Describe the results you expected:

All processes see the latest version of the files.

Provide additional info you think is important:

Working example using Docker 1.9.1
-------------------------------------------------

Install VirtualBox 5.0.4 and build a VM with Ubuntu 14.04 x64. This bug has also been reproduced with CentOS 7.1 on the VM. The test hosts were Mac OS X 10.11.1 El Capitan.

Create a Dockerfile as follows

```
FROM alpine:3.2

RUN apk add --update python

ENTRYPOINT ["sh", "-c"]
CMD ["while true; do sleep 10; done"]
```
```
$ docker build -t testimage .
```

Mount a directory via into a VirtualBox VM using vboxfs containing a single file, test.py:

```
print "HELLO"
```

```
$ ls /path/to/mount
test.py
```

Run a container, mounting the shared folder:

```
$ docker run -d -v /path/to/mount:/files testimage
a7741514db36343c7f9df7f94685555a75072e6eb3c9de72ddec983f050ec401
```

Exec a shell on the container and run the python script, and cat its contents:

```
$ docker exec -it a7741514db36 sh
# cd /files
# python test.py
HELLO
# cat test.py
print "HELLO"
# less test.py
(contents are: print "HELLO")
# vi test.py
(contents are: print "HELLO")
```

Edit the file on the host machine, changing HELLO to GOODBYE. Then use docker exec again:

```
$ docker exec -it a7741514db36 sh
# cd /files
# python test.py
HELLO
# cat test.py
print "HELLO"
# less test.py
(contents are: print "GOODBYE")
# vi test.py
(contents are: print "GOODBYE")
```

At demonstrated, the python and cat executables still see the original contents of the file, but the less and vi executables see the new contents. 

One final demonstration; edit the file inside the container using vi, then execute it with python:

```
# vi /files/test.py
(change GOODBYE to TESTING)
# python /files/test.py
HELLO
# cat /files/test.py
print "HELLO"
# less /files/test.py
(contents are: print "TESTING")
```

Python again executes the original contents of the file, and cat sees the same. Vi and less see, again, the edited files.

```
$ docker --version
Docker version 1.9.1, build a34a1d5
```

**Comment by nathanleclaire** [comment]
Isn't it more like a VBox SF bug than a docker bug?  If same results can't be duped with normal (native Linux) mount, maybe it should be filed in Oracle bug tracker instead?

**Comment by doozr** [comment]
Maybe, but Docker volumes are the only scenario I can find where this
happens.

**Comment by doozr** [comment]
Also, given that Boot2Docker/docker-machine relies on VirtualBox it's likely to become a bigger issue. If it can be fixed in Docker then great. If not then it might have to be fixed in VboxSF or aufs.

**Comment by cpuguy83** [comment]
This is not a Docker issue.
Volumes are nothing fancy, just bind-mounts, which are handled by the kernel.

Note there are similar issues when using nginx+sendfile on vbox shared folders.
See https://www.virtualbox.org/ticket/9069

**Comment by doozr** [comment]
It looks like this is a VirtualBox issue. I've raised a new bug on their tracker because I couldn't find an existing one, but will link it to the bug @cpuguy83 refers to.

**Comment by cpuguy83** [comment]
Thanks @doozr

**Comment by cpuguy83** [comment]
@thaJeztah Should we (or do we?) have some docs around this?
