### ISSUE TITLE
docker removing container image repo name after 5 or so minutes. v1.9.1

### ISSUE THREAD

**Issue by drocsid** [docker/docker#18588]
docker version:
`docker --version Docker version 1.9.1, build a34a1d5-dirty`

docker info:
```
docker info
Containers: 159
Images: 99
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-8:5-1447372-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 18.69 GB
 Data Space Total: 107.4 GB
 Data Space Available: 7.713 GB
 Metadata Space Used: 20.54 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.127 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.112 (2015-11-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.5-1-ARCH
Operating System: Arch Linux (containerized)
CPUs: 4
Total Memory: 7.71 GiB
Name: erista
ID: AXOM:UFSY:W2HJ:YFJA:5QOX:WMC3:KKSM:XDEJ:OJ6D:GLLX:Q3RB:A7OP
Username: discord
Registry: https://index.docker.io/v1/
````

uname -a:

```
uname -a
Linux erista 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux
````

Provide additional environment details (AWS, VirtualBox, physical, etc.):
```
physical workstation
```

List the steps to reproduce the issue:

```
1.docker build -t tm-sm2
2.docker rmi -f [tm-sm2_image_id]
3.docker build -t tm-sm2
4.docker images
5.docker tag [new tm-sm2_image_id] tmsm2
6.docker images
```
Describe the results you received:
```
none as repo name.
```
Describe the results you expected:
```
tm-sm2 as repo name
```
Provide additional info you think is important:

<detail>
I removed an image that had repo name `tm-sm2` from my local workstation, using `docker rmi -f image_id`. After that I built an image using the same repo name: `docker build -t tm-sm2 .` The image builds and I can at first see it with docker images: 
`tm-sm2                                 latest               id_hash        13 seconds ago      394.9 MB`

A short while later ~5-10 minutes, the repo name disappears:
`<none>                                 <none>               id_hash        17 minutes ago      394.9 MB`

I set the repo name back on the image: `docker tag id tm-sm2`

Then I see the repo name applied on the image
`tm-sm2                                 latest               id_hash        19 minutes ago      394.9 MB`

Again about 5-10 minutes, the repo name disappears:

`<none>                                 <none>               id_hash        35 minutes ago      394.9 MB`

</detail>

----------END REPORT ---------

#ENEEDMOREINFO

**Comment by qq690388648** [comment]
Please reformat you issue with block mark <code>```</code>, it will look better.

**Comment by drocsid** [comment]
It's already formatted with ```.

**Comment by drocsid** [comment]
It appears to be an issue created externally. My bad. Closing.

**Comment by thaJeztah** [comment]
> It's already formatted with ```. I added a few more, but I think it's perfectly readable.

I edited it for you earlier :innocent:

> It appears to be an issue created externally. My bad. Closing.

Thanks for reporting back! Good to hear you resolved the issue :+1:
