### ISSUE TITLE
docker start ____ says "Error response from daemon: Cannot start container ____: Unable to setup mount point, neither source nor volume defined", after a reboot

### ISSUE THREAD

**Issue by mickael-kerjean** [docker/docker#18593]
Hello,

After a hard reboot on centos, 
```
docker start container_name
```
 would trigger this strange error:
```
"Error response from daemon: Cannot start container ____: Unable to setup mount point, neither source nor volume defined"
```
Firering a docker inspect, I went into some oddities:
```
  "Id": "6561383760adeef2a8ee402d095a0691a449974034b76336d9a66aed129fa652",
  .........
  "Mounts": [
        {
            "Name": "a3d26bcdc5d1cd3be763f260fddf6bd80d3a12c4e0a58196fb9756a4245d909c",
            "Source": "",
            "Destination": "/var/lib/mysql",
            "Driver": "local",
            "Mode": "",
            "RW": true
        }
    ],
```

There is nothing under the source field anymore? I had some intense time trying to retrieve the data which was still leaving under:
```
/var/lib/docker/volumes/a3d26bcdc5d1cd3be763f260fddf6bd80d3a12c4e0a58196fb9756a4245d909c/_data/
```
I assumed it worth trying to update it by:
```
 vi /var/lib/docker/containers/6561383760adeef2a8ee402d095a0691a449974034b76336d9a66aed129fa652/config.json
```
and updating the MountPoints -> Source to the actual volume location:
```
/var/lib/docker/volumes/58e062e0841114898aee129e87325808be9c608d0ac9b2ec87dc2b907b5d64c1/_data/
```
Everything is fix by now but it was quite a stressful moment, as I really thought all the containers were completely broken and the data would never be back.

Anyway, it was possible to fix the issue, but it tooks me a couple hours to figured out how to fix it and follow the process above for a few dozens of containers.

I don't understand what has happened and I haven't seen any documentation regarding this specific issue and had some hard time to fix it.

Any idea of the underlying cause?

**Comment by thaJeztah** [comment]
I wonder if this was caused by an unclean shutdown, and the changes weren't written to disk properly. You also mention "After a hard reboot on centos,"

**Comment by mickael-kerjean** [comment]
docker version:
```
Client:
 Version:      1.8.2
 API version:  1.20
 Package Version: docker-1.8.2-7.el7.centos.x86_64
 Go version:   go1.4.2
 Git commit:   bb472f0/1.8.2
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Package Version:
 Go version:   go1.4.2
 Git commit:   bb472f0/1.8.2
 Built:
 OS/Arch:      linux/amd64
```
docker info:
```
Containers: 32
Images: 371
Storage Driver: devicemapper
 Pool Name: docker-253:0-202822053-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 13.52 GB
 Data Space Total: 107.4 GB
 Data Space Available: 14.26 GB
 Metadata Space Used: 18.97 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.129 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.20.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 3.578 GiB
Name: localhost.localdomain
ID: V4QM:3QZK:6OJU:GTQ4:PJYJ:FPXX:5CDJ:WWL2:7ZFG:ZXZ4:JBOI:67AR
Http Proxy: xxxxxxxxxxxxxxxxxxxxx
Https Proxy: xxxxxxxxxxxxxxxxxxxxx
```
uname -a:
```
Linux localhost.localdomain 3.10.0-229.20.1.el7.x86_64 #1 SMP Tue Nov 3 19:10:07 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mickael-kerjean** [comment]
A hard reboot as the only thing that was done is: 
```
reboot
```

without doing:
```
service docker stop && \
reboot
```

It seems strange the json was still valid and the only missing part was under Mounts->Source
Anyway, if somebody have the same issue, hopefully a google search will help to fix it now.

**Comment by jualvarez** [comment]
I am experiencing the same issue with docker 1.8.3

This happened after an unclean reboot (power failure)

docker inspect failing_container:

    [...]
    "Mounts": [
        {
            "Source": "/usr/bin/docker",
            "Destination": "/bin/docker",
            "Mode": "",
            "RW": true
        },
        {
            "Name": "b81305dfc41456dbdfc9df21578871a5e868bdbdd7381828e4bd85dbe07c3db4",
            "Source": "",
            "Destination": "/home/git/data",
            "Driver": "local",
            "Mode": "",
            "RW": true
        },
        {
            "Source": "/var/run/docker.sock",
            "Destination": "/run/docker.sock",
            "Mode": "",
            "RW": true
        },
        {
            "Name": "bf01d4950d4fa6d143f97ba319f4f0da57ac4998330cc0cd6f0b627740494fc0",
            "Source": "",
            "Destination": "/var/log/gitlab",
            "Driver": "local",
            "Mode": "",
            "RW": true
        }
    ],

docker version:

    Client:
       Version:      1.8.3
       API version:  1.20
       Go version:   go1.4.2
       Git commit:   cedd534-dirty
       Built:        Wed Jan 20 05:36:30 UTC 2016
       OS/Arch:      linux/amd64
      
    Server:
       Version:      1.8.3
       API version:  1.20
       Go version:   go1.4.2
       Git commit:   cedd534-dirty
       Built:        Wed Jan 20 05:36:30 UTC 2016
       OS/Arch:      linux/amd64


docker info:

    Containers: 8
    Images: 527
    Storage Driver: btrfs
     Build Version: Btrfs v4.0.1
     Library Version: 101
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 4.2.2-coreos-r2
    Operating System: CoreOS 835.10.0
    CPUs: 6
    Total Memory: 3.601 GiB
    Name: TrimServer1
    ID: IVEM:AFNH:7GB7:DQPA:XSQS:MD7Z:V6UA:KM46:OYQO:PM7I:QR2O:QOV7
