### ISSUE TITLE
Docker container network drops intermittently

### ISSUE THREAD

**Issue by rajasec** [docker/docker#18602]
With base Ubuntu 15.04, I've launched the 3 Ubuntu containers(14.04), I'm able to acquire the dhcp ip for each of the container. IP address, netmask and gateway seems to be correct. I'm able to reach the containers from external IP. But few minutes later one of the container's IP is not reachable. Other 2 are reachable..  
Later one of the IP which was not reachable became active, other 2 are down..
I'm not able to ping or reach 3 containers simultaneously using it dhcp IP
I've created via bridge and started the docker daemon using bridge option.

docker info
Containers: 41
Images: 53
Server Version: 1.9.0
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.5
Operating System: Ubuntu 15.04

Not sure whether it is related to MAC address  being generated from Container

**Comment by LK4D4** [comment]
Issue is pretty old. Sad that it had not attention, but code changed so much since.
Feel free to open new issue if problem still persists.
