### ISSUE TITLE
Logging driver plugins

### ISSUE THREAD

**Issue by bfirsh** [docker/docker#18604]
It should be possible for logging drivers to be external plugins, similar to how volumes and networks work.

This will allow people to write and update logging drivers without having to get them merged upstream and wait for a Docker release. It'll also allow users to write custom logging drivers for their infrastructure without having to build custom versions of Docker.

We will probably still want to ship some popular drivers by default (e.g. json, syslog, and fluentd).
### Related
- [Proposal: Logging drivers](https://github.com/docker/docker/issues/7195)
- [Add Splunk logging driver](https://github.com/docker/docker/pull/16488)
- [Add log-driver for logstash](https://github.com/docker/docker/issues/14949)

(ping people interested: @sirupsen)

**Comment by Sirupsen** [comment]
@bfirsh yesss! \cc @kvs @burke @andremedeiros

**Comment by LK4D4** [comment]
#18001 also

**Comment by andremedeiros** [comment]
:tada: :confetti_ball:

**Comment by thaJeztah** [comment]
IIRC, there were concerns w.r.t performance if the drivers were external, is this still the case? I'm thinking were that discussion was, but there were some features that would arrive in Go 1.6? (Sorry, bit hazy on the details)

**Comment by LK4D4** [comment]
@thaJeztah I think it's still a concern.

**Comment by bitsofinfo** [comment]
+1

**Comment by cpuguy83** [comment]
Yeah, I think we'd need to do #18001 where we blast out logs to whatever the requested endpoint is and use the native message structure... this would be instead of utilizing the current plugin RPC mechanism we currently use.
I think it will be easier to consume, can probably even be able to move some of the built-in drivers to be external (and reduce a **bunch** of vendored-in code).

**Comment by vdemeester** [comment]
This is related to #20363 :stuck_out_tongue_closed_eyes:

**Comment by thaJeztah** [comment]
Linking https://github.com/docker/docker/issues/20370 which may also be relevant here

**Comment by subfuzion** [comment]
Rather than add every conceivable logging driver possible to the engine (see #21271), provide a logging driver that lets you specify an image to run with supplied driver configuration options. Logs could be streamed to this container, which would be responsible for implementing whatever logic necessary as part of shipping logs to some other destination.

**Comment by subfuzion** [comment]
I'm thinking along these lines for a hypothetical custom logger to stream logs to kafka:

```
docker daemon --log-driver=custom \
  --log-opt image=atomiq/kafka-logging:latest
  --log-opt bootstrap.servers=host1:port1,host2:port2
  --log-opt acks=0
  --log-opt client.id=1

docker run -d --log-driver=custom \
  --log-opt image=atomiq/kafka-logging:latest
  --log-opt bootstrap.servers=host1:port1,host2:port2
  --log-opt acks=0
  --log-opt client.id=2
  alpine echo hello
```

![custom-logging-driver](https://cloud.githubusercontent.com/assets/159738/13903070/fe1e143c-ee26-11e5-8892-16bd93c56e40.png)

**Comment by subfuzion** [comment]
@bfirsh @thaJeztah I realize that my proposal is not based on whatever will be the ultimate plugin solution nor will it ever be able to provide the performance of a true plugin, but nevertheless it does provide a workable solution that at lease allows for selecting custom logging agents/shims via the `log-driver` option -- plus supports plugins *not* written in go. It would be nice to have some workable sooner than something perfect later. I currently need to use the gelf driver to send to a shim for kafka, which most definitely is even less ideal.

**Comment by subfuzion** [comment]
Will https://github.com/docker/docker/pull/23446 (which fixes https://github.com/docker/docker/issues/20363) be the general solution that helps with this issue? That would be great.

**Comment by liuchong** [comment]
Looks great! Also https://github.com/docker/docker/pull/18001 :joy_cat:

**Comment by cpuguy83** [comment]
Logging driver plugins is in! #28403
