### ISSUE TITLE
feature request: verify and/or update

### ISSUE THREAD

**Issue by mhennings** [docker/docker#1860]
when you work locally with images it can happen that your local state differs to the remote state.

i see the following causes:
- local build, never pushed, older than remote
- local checksum not valid (local change/ fscorruption, whatever)
- newer remote

for this i would like to have some kind of "verify" or "update" command to get in sync.

i am aware that pull will fetch the newest remote, but it will overwrite local images even if they are newer. 

also pull will not verify checksums.

beside this, it would be nice if there was an option to run that will verify before running.

what do you think?

**Comment by LK4D4** [comment]
@thaJeztah @tonistiigi Do you think it's possible to do now? Still worth it?

**Comment by thaJeztah** [comment]
Isn't this what Docker Content Trust basically does? https://docs.docker.com/engine/security/trust/content_trust/

/cc @endophage

**Comment by tonistiigi** [comment]
At least some of this was addressed with content addressability in `v1.10`

**Comment by LK4D4** [comment]
@thaJeztah @tonistiigi let's then close it and if someone interest will open new issue with current concerns.
