### ISSUE TITLE
BitBucket Integration Setup Not Working if Logged In

### ISSUE THREAD

**Issue by aytawn** [docker/docker#18609]
The "Link Bitbucket" button on https://hub.docker.com/account/authorized-services/ works properly if you are not already logged in to Bitbucket. However if you ARE logged in it just pops open a new window with the same page.

The temporary workaround is to log out of Bitbucket first, but clearly this is a bug that you might want to address.

**Comment by thaJeztah** [comment]
Thanks for reporting @aytawn. Unfortunately, hub.docker.com is handled by a different team and we cannot help you here.

For support issues on hub.docker.com, please contact support@docker.com. There's also an issue tracker for feedback here; https://github.com/docker/hub-feedback/issues?utf8=✓&q=is%3Aissue+is%3Aopen+bitbucket

Can you report this issue using either one of the above? Thanks!
