### ISSUE TITLE
Logging driver to log to plain text file

### ISSUE THREAD

**Issue by scf37** [docker/docker#18619]
Problem: I have Docker image that logs to stdout. I want to capture them to plain text file to parse later. Surprisingly I was not able to found any solution that works on large log volume and do not require image tampering.

Why not docker json logger: Consumes a lot of CPU and memory under high load.

Why not syslog/other networking drivers: I want to get stdout as-is and I want to have local storage in case log server becomes unavailable.

**Comment by phemmer** [comment]
Unfortunately this has already been proposed, and rejected. See #17020

**Comment by thaJeztah** [comment]
Yes, closing this as a duplicate of https://github.com/docker/docker/issues/17020, see the discussion on that issue for reasons why it was rejected.
