### ISSUE TITLE
docker inspect seems to be broken w.r.t graph drivers

### ISSUE THREAD

**Issue by rhvgoyal** [docker/docker#18614]
I create a container using devicemapper graph driver and when I run docker inspect on same container, I get the details of wrong device in the output.

For example I did `docker inspect c7bad1614839`, then at graph driver level I am getting Id `e15a048cd50243dc305c3713d20fa7d3743446e3ca464da3ae31adb9c9b37e3a' and this id does not belong to the container. This id belongs to an image.

Something seems to be wrong w.r.t docker inspect and how it is correlating container names with the graph driver id for the same container.

**Comment by rhvgoyal** [comment]
cc @rhatdan @vbatts @runcom

**Comment by rhvgoyal** [comment]
cc @dmcgowan

**Comment by thaJeztah** [comment]
@rhvgoyal is this on master or 1.9.1?

**Comment by rhvgoyal** [comment]
@thaJeztah this is on master branch. I suspect something to do with new layer code.

**Comment by thaJeztah** [comment]
Thanks, that's why is asked :smile:

ping @tonistiigi @aaronlehmann

**Comment by rhvgoyal** [comment]
I think following code is the suspect.

        graphDriverData, err := l.Metadata()
        if err != nil {
                return nil, err
        }

I think here `l` refers to rootfs of image of container and not the container himself. And that's why I see the data of container image and not the container.

**Comment by tonistiigi** [comment]
@rhvgoyal What do you mean by " at graph driver level". Do you mean the `GraphDriver.Data.DeviceName`? RW layer for ID is not same as contain ID anymore, but it is not image ID either. It's just temporary random ID.

Are you sure it is the image ID? Can you reproduce always or only with this specific ID?

**Comment by rhvgoyal** [comment]
@tonistiigi When I do inspect on container, GraphDriver, section of output is reporting details of image device. It should instead report the details of container rootfs device.

**Comment by rhvgoyal** [comment]
@tonistiigi It is reproducible always. I am aware that container id does not directly map to graph driver ID.  But If you launch two containers from same image, and do docker inspect on these, You will notice that GraphDriver section is same for both the containers and they both are reporting the details of the image they have been launched from.

**Comment by runcom** [comment]
1.9.x correctly relates `DeviceName` to the container - inspect shows the `DeviceName` the container is on.
```
[root@rawhide docker]# docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                      PORTS               NAMES
ec7aad4823d1        busybox             "true"              38 seconds ago      Exited (0) 37 seconds ago                       drunk_lalande
2001894fe8f4        busybox             "top"               44 seconds ago      Up 43 seconds                                   elegant_hawking

[root@rawhide docker]# docker inspect -f '{{json .GraphDriver }}' ec7
{"Name":"devicemapper","Data":{"DeviceId":"14","DeviceName":"docker-252:3-12870678-ec7aad4823d1f24e82b5a95f1637c949132d1c3bd247fd151ef8c84264f33c78","DeviceSize":"107374182400"}}

[root@rawhide docker]# docker inspect -f '{{json .GraphDriver }}' 200
{"Name":"devicemapper","Data":{"DeviceId":"12","DeviceName":"docker-252:3-12870678-2001894fe8f4487c8ce48076bf2b765ca5ed6e46d3cf7d5d1389c619ccf5555e","DeviceSize":"107374182400"}}

[root@rawhide docker]# docker images -a
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
docker.io/busybox   latest              ac6a7980c6c2        4 days ago          1.113 MB
<none>              <none>              c00ef186408b        4 days ago          1.113 MB

[root@rawhide docker]# docker inspect -f '{{json .GraphDriver }}' ac6
{"Name":"devicemapper","Data":{"DeviceId":"10","DeviceName":"docker-252:3-12870678-ac6a7980c6c2fb4d29e406efb4f9784b3c67e161eb68a97ffb428d07e3e97693","DeviceSize":"107374182400"}}
```
while on 1.10.x:
```
[root@rawhide docker]# docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                     PORTS               NAMES
b3a7539efc9d        busybox             "true"              6 seconds ago       Exited (0) 4 seconds ago                       tender_liskov
309dea6a3cd1        busybox             "true"              2 minutes ago       Exited (0) 2 minutes ago                       sharp_mclean

[root@rawhide docker]# docker inspect -f '{{json .GraphDriver }}' b3a
{"Name":"devicemapper","Data":{"DeviceId":"3","DeviceName":"docker-252:3-116521-a4b4cd316be64e61a913ed76d65985dfa886234513af47a1bd95004eab8ce04b","DeviceSize":"107374182400"}}

[root@rawhide docker]# docker inspect -f '{{json .GraphDriver }}' 309
{"Name":"devicemapper","Data":{"DeviceId":"3","DeviceName":"docker-252:3-116521-a4b4cd316be64e61a913ed76d65985dfa886234513af47a1bd95004eab8ce04b","DeviceSize":"107374182400"}}

[root@rawhide docker]# docker images -a
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
docker.io/busybox   latest              d9551b4026f0        4 days ago          1.113 MB

[root@rawhide docker]# docker inspect -f '{{json .GraphDriver }}' d955
{"Name":"devicemapper","Data":{"DeviceId":"3","DeviceName":"docker-252:3-116521-a4b4cd316be64e61a913ed76d65985dfa886234513af47a1bd95004eab8ce04b","DeviceSize":"107374182400"}}
```

I'm marking this as a bug/regression and @rhvgoyal seems right in that the change which cause this is https://github.com/docker/docker/pull/17924/files#diff-9d7e088e8ca8f96f2ac0af044001ae04L152 (from Content Addressability patches)

**Comment by runcom** [comment]
This is also happening with other graph drivers.
Just tested on overlay, `RootDir` of the container is the root dir of the image the container is run from (not the container itself)
```
$ docker run -d busybox true
b940c5c1524ec6630a656a2bc3097338d83d54645bd2010c22f235183f7ab903
$ docker inspect -f '{{json .GraphDriver }}' b94
{"Name":"overlay","Data":{"RootDir":"/var/lib/docker/0.0/overlay/48372b83eea4fbb4f6575a1c12ff913b0efeeacb85db418223f25122c57f5520/root"}}
$ docker images -a
REPOSITORY          TAG                      IMAGE ID            CREATED
busybox             latest                   d9551b4026f0        4 days ago          1.113 MB
$ docker inspect -f '{{json .GraphDriver }}' d9551b4026f0
{"Name":"overlay","Data":{"RootDir":"/var/lib/docker/0.0/overlay/48372b83eea4fbb4f6575a1c12ff913b0efeeacb85db418223f25122c57f5520/root"}}
```

**Comment by tonistiigi** [comment]
@dmcgowan Any suggestion for the best way to fix this? Don't want to call `Mount` for every inspect. Exposing `RWLayerMetadata()` that is windows-only atm seems ugly also. Looks more likely that we would need to split up `store.Mount` to `store.Get()` and `rwlayer.Mount()`. `store.Changes()` is also better as `rwlayer.Changes()`

**Comment by dmcgowan** [comment]
We should just add a `Metadata()` to the `RWLayer` interface and use that for the inspect.

**Comment by tonistiigi** [comment]
@dmcgowan And call mount/unmount on every `docker inspect` call? Likely a performance regression.

**Comment by dmcgowan** [comment]
The `RWLayer` is in scope when the current `Metadata` is called https://github.com/docker/docker/blob/master/daemon/inspect.go#L177. My understanding is this would save us from an unnecessary get/release of the image layer by going directly to the already mounted layer. Is there other locations that would require an explicit mount?
