### ISSUE TITLE
Remove nested BTRFS subvolumes on volume removal automatically

### ISSUE THREAD

**Issue by nazar-pc** [docker/docker#18624]
When container creates BTRFS subvolumes inside its volume, on volume removal I'm getting errors like this:
> Error response from daemon: Error while removing volume 49421227467c8a672460916412508f31322b809078705d58d459a9fc007de81d: remove /var/lib/docker/volumes/49421227467c8a672460916412508f31322b809078705d58d459a9fc007de81d/_data/osd/ceph-0/snap_1: operation not permitted

Example above happens when running Ceph OSD inside container.

I'd like to see all nested subvolumes to be removed automatically rather than removing them manually.

#### docker version
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64
```
#### docker info
```
Containers: 0
Images: 340
Server Version: 1.9.1
Storage Driver: btrfs
 Build Version: Btrfs v4.0
 Library Version: 101
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.4.0-rc4-haswell
Operating System: Ubuntu 16.04 (containerized)
CPUs: 8
Total Memory: 15.59 GiB
Name: nazar-pc
ID: ...
WARNING: No swap limit support
```

#### uname -a
```
Linux nazar-pc 4.4.0-rc4-haswell #1 SMP Tue Dec 8 01:20:05 CET 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by cpuguy83** [comment]
I believe this was fixed by #18686
Can you by chance test with master? https://master.dockerproject.org

**Comment by nazar-pc** [comment]
I'm using Docker Compose and it stopped creating records for all containers in `/etc/hosts`, which is why I can't actually run my containers at all with current master build
Anyway, it seems that mentioned PR should fix the issue, I'll reopen issue if it will be still the case after release.

**Comment by cpuguy83** [comment]
@nazar-pc Yes, docker will not use /etc/hosts anymore, instead there is DNS-based resolution.

**Comment by nazar-pc** [comment]
I know, still waiting how aliases and stuff will stabilize with Docker Compose to adjust accordingly. I've used `/etc/hosts` changes to fill Consul with services, but now Consul container is unable to find any containers, so everything just stopped working.

**Comment by thaJeztah** [comment]
@nazar-pc also note that 1.10 brings a much improved events system, including (e.g.) `network connect` and `network disconnect` https://github.com/docker/docker/pull/18888

**Comment by nazar-pc** [comment]
Looks awesome, but requires access to Docker engine from within container.

My implementation was entirely self-contained. Moreover, images other than Consul were able to find Consul instance(s) withing network, add them to `/etc/resolv.conf` and everything just works automagically, from changes I see in Docker currently - they will be not less than disaster for my images.

If you have few minutes - take a quick look here: https://github.com/nazar-pc/docker-webserver/blob/master/docs/advanced.md#combined-example

That repo contains images that can form cluster of various services completely automagically (MariaDB Galera cluster, Consul cluster, HAProxy load balancing across cluster services, etc.) that scales gracefully up and down and in simple cases require literally zero configuration (CephFS image also available, but WIP, waiting for some fixes on Compose side to make it convenient).
