### ISSUE TITLE
Proposal of adding  SUBNETS info for  docker network inspect user-defined network

### ISSUE THREAD

**Issue by wenchma** [docker/docker#18626]
When we `inspect` a user-defined network, cannot show the subnet info, in fact it is allocated with Ip pool. Make a proposal to add  `SUBNETS` info for `docker network inspect user-defined-network` , the output looks like the follows:

Actual results:

     $ docker network inspect simple-network
	[
	    {
		"Name": "simple-network",
		"Id": "dcec95685b861477950947709450686dc833933038491f55025f6ee21034b1bf",
		"Scope": "local",
		"Driver": "bridge",
		"IPAM": {
		    "Driver": "default",
		    "Config": [
		        {}
		    ]
		},
		"Containers": {},
		"Options": {}
	    }
	]

Expected results:

    $ docker network inspect simple-network
	[
	    {
		"Name": "simple-network",
		"Id": "dcec95685b861477950947709450686dc833933038491f55025f6ee21034b1bf",
		"Scope": "local",
		"Driver": "bridge",
		"IPAM": {
		    "Driver": "default",
		    "Config": [
		        {
                            "Subnet": "172.19.0.0/16",
                            "Gateway": "172.19.0.1"
                        }
		    ]
		},
		"Containers": {},
		"Options": {}
	    }
	]
If the network has subnets, print all the subnets , if it has no subnet, print nothing.

`docker version`

        Client:
	 Version:      1.9.1
	 API version:  1.21
	 Go version:   go1.4.2
	 Git commit:   a34a1d5
	 Built:        Fri Nov 20 13:12:04 UTC 2015
	 OS/Arch:      linux/amd64

	Server:
	 Version:      1.9.1
	 API version:  1.21
	 Go version:   go1.4.2
	 Git commit:   a34a1d5
	 Built:        Fri Nov 20 13:12:04 UTC 2015
	 OS/Arch:      linux/amd64

`docker info`

        Containers: 21
	Images: 82
	Server Version: 1.9.1
	Storage Driver: aufs
	 Root Dir: /var/lib/docker/aufs
	 Backing Filesystem: extfs
	 Dirs: 124
	 Dirperm1 Supported: false
	Execution Driver: native-0.2
	Logging Driver: json-file
	Kernel Version: 3.13.0-43-generic
	Operating System: Ubuntu 14.04.1 LTS
	CPUs: 4
	Total Memory: 15.67 GiB
	Name: docker
	ID: UT5D:M5ZY:IEXQ:6LCU:YX6J:ZMWM:BLNJ:MTXH:PRHO:ETVF:3FHH:6LC4
	WARNING: No swap limit support

`uname -a`

    Linux docker 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):OpenStack Cloud instance

**Comment by wenchma** [comment]
@thaJeztah @mavenugo @calavera  what do you think about this proposal ? It is a small improvement. :smile:

**Comment by thaJeztah** [comment]
Could make sense, yes. Perhaps we should make a list of all properties of a network, and decide which ones we want to include in `docker network ls` by default. Exposing other (non-default) fields can then be controlled via a `--format` flag

**Comment by mavenugo** [comment]
Thanks. I think the proposal make sense. But I think it would make sense to add this (and other fields like @thaJeztah mentioned) to `docker network inspect` instead of `ls`. Especially because, the Subnet field alone wouldnt make sense if there is a corresponding `ip-range` configured by the user. Hence I think it would be more useful if we use `docker network inspect` for such information.
BTW, `docker network inspect` already carries these info (only if the user configures it). I think it would be good to enhance it to also include auto-created subnets for user-defined networks.
@wenchma wdyt ?

**Comment by wenchma** [comment]
@thaJeztah @mavenugo good idea to move this to `docker network inspect`, so users can customize their output info, it also makes sense to leave `docker network ls` to be simplified, :+1:

**Comment by wenchma** [comment]
Update the title and the description to improve `docker network inspect user-defined-network`.

**Comment by wenchma** [comment]
Add IpamInfo() function to libnetwork/network.go , so docker can call this func to `inspect` the subnet of user-defined networks.

**Comment by wenchma** [comment]
https://github.com/docker/docker/issues/18928 is merged, this issue should be closed.

**Comment by wenchma** [comment]
https://github.com/docker/docker/issues/18928 is merged, this issue should be closed.
