### ISSUE TITLE
"WARNING: Error loading config file:EOF" when running any docker command

### ISSUE THREAD

**Issue by sgerace** [docker/docker#18634]
I just upgraded Docker to 1.9.1 using the [Docker Toolbox](https://www.docker.com/docker-toolbox) on OS X (first time installing using the Toolbox), and now anytime I run any `docker` command I get the following message as the first line of output:
```
WARNING: Error loading config file:EOF
```
For instance, this is the output when I run `docker version`:
```
$ docker version
WARNING: Error loading config file:EOF
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```
All the commands seem to run fine, but it would be nice to get rid of that warning, and I'm not sure if it will effect any functionality.

**Comment by thaJeztah** [comment]
Looks similar to https://github.com/docker/docker/issues/17727

**Comment by thaJeztah** [comment]
Error is generated here; https://github.com/docker/docker/blob/375f754f49ee6e9de942816a47a21a715fe3bacb/api/client/cli.go#L90

**Comment by sgerace** [comment]
Could this be as simple as removing an outdated configuration file somewhere?

**Comment by thaJeztah** [comment]
@sgerace I've not ran into this issue myself, but you can try moving that file (if it exists), I think it should be in `~/.docker/config.json`. It's a hidden directory, so you can navigate to the directory using CMD+SHIFT+G in the finder, and entering `~/.docker/` to open the directory

**Comment by sgerace** [comment]
So, I moved the file and when I ran `docker version` again a new `config.json` was created in `~/.docker/` and it was empty. Just out of curiosity, I modified the file to be valid json by simply making the contents:
```
{}
```
and sure enough that fixed the issue. I'm not sure why an empty `config.json` file is created, but at least the warnings are gone ;-)

**Comment by thaJeztah** [comment]
hm interesting indeed. removing the file should also be OK (I think), but strange that an *empty* file ended up there

**Comment by chipironcin** [comment]
I found this issue too.
Deleting the empty file in `~/.dockercfg` solved the problem.
This came when I updated from Docker 1.8.1 to Docker 1.9.1 using `wget -qO- https://get.docker.com | sh`

**Comment by thaJeztah** [comment]
thanks @chipironcin

**Comment by thaJeztah** [comment]
ping @duglin any idea how we end up with an empty `.dockercfg` file?

**Comment by duglin** [comment]
@chipironcin did you see the `EOF` error message or did it say something like `The Auth config file is empty` ?

@sgerace what version of Docker were you upgrading from?

**Comment by chipironcin** [comment]
@duglin `Invalid Auth configuration` or `Could not open the config file` I dont remember well.
It can also happened when I rant out of space, Docker couldnt write to the file leaving it blank, leading to these errors.

**Comment by sgerace** [comment]
@duglin I'm not 100% sure, but I know it was a version before the Docker Tookbox was introduced (since I still have `boot2docker` installed). I want to say it was something around `1.6` (I know, its been awhile).

**Comment by thaJeztah** [comment]
@sgerace do you think it's ok if we close this issue? I see @duglin improved the error message so that it's easier to find which file is empty; https://github.com/docker/docker/pull/18694

**Comment by sgerace** [comment]
@thaJeztah Yep, okay with me to close. Thanks!

**Comment by thaJeztah** [comment]
Thanks @sgerace!
