### ISSUE TITLE
docker pull fails for several minutes after registry setup from same host

### ISSUE THREAD

**Issue by jbaramidze** [docker/docker#18632]
hello, I'm using docker 1.9 and machine 0.5.2

I have scripts that download registry from repos, install, it, generate certs for it, propagate 
/etc/docker/certs.d of several hosts (including host where I run registry) and pull test images. 

all other hosts pull test images from registry succesfully, but host where I have registry running gives such error:
stderr: Error response from daemon: unable to ping registry endpoint https://192.168.1.210:5000/v0/
v2 ping attempt failed with error: Get https://192.168.1.210:5000/v2/: x509: certificate has expired or is not yet valid

and the strange thing is, after several minutes it starts working well. what am I missing?

**Comment by cpuguy83** [comment]
@jbaramidze It looks like you're generating certs that are valid only in the future.

**Comment by jbaramidze** [comment]
@cpuguy83 
thanks! that was the problem

**Comment by thaJeztah** [comment]
Looks like this is resolved, so I'll close it. Thanks!
