### ISSUE TITLE
Long Wait Times For Push To S3 Backed V2 Registry

### ISSUE THREAD

**Issue by ibuys** [docker/docker#18636]
## Description of problem:

Docker push from Hudson to Registry V2 is taking over a half hour for an Ubuntu image with a Java application installed. With V1 the push took one to three minutes. 

`docker version`: 

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:

```
Containers: 5
Images: 30
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 40
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-68-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 3.859 GiB
Name: regv2
ID: MQDT:ABTN:7UPF:VZZA:LJWB:MELY:M7IQ:YW4D:52A2:JK37:KBAP:ZUZW
WARNING: No swap limit support
```

`uname -a`:

`Linux ip-10-16-1-139 3.13.0-68-generic #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

Environment details (AWS, VirtualBox, physical, etc.):

AWS, S3 backed Registry v2, started with this command:

```
docker run -d -p 5000:5000 --restart=always --name registry \
-e "REGISTRY_STORAGE=s3" \
-e "REGISTRY_STORAGE_S3_ACCESSKEY=SECRET” \
-e "REGISTRY_STORAGE_S3_SECRETKEY=SECRET” \
-e "REGISTRY_STORAGE_S3_REGION=us-west-2" \
-e "REGISTRY_STORAGE_S3_BUCKET=my-bucket“ \
-e REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR=redis \
-e REGISTRY_REDIS_ADDR=10.10.10.10:6379 \
-v `pwd`/auth:/auth \
-e "REGISTRY_AUTH=htpasswd" \
-e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" \
-e "REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd" \
-v `pwd`/certs:/certs \
-e "REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt" \
-e "REGISTRY_HTTP_TLS_KEY=/certs/domain.key" \
registry:2
```

## How reproducible:

Happens every time.

## Steps to Reproduce:
1. Build new Docker image on remote client.
2. Run `docker push` to V2 registry.
3. Wait. 

## Actual Results:

Hudson reports a 10x increase in upload time for images when compared to previous uploads to v1 registry.

Build 5 -> 36 minutes
Build 3 -> 3 minutes 5 seconds
Build 2 -> 1 minute 23 seconds
Build 1 -> 2 minutes 10 seconds

## Expected Results:

I would expect the V2 registry to be a little slower, but not this much. I’m not sure if there’s an issue in my specific registry setup, or if there’s any known issues with using S3 as a backend. 

## Additional info:

The Redis server the registry is using is running in another Docker container on the same instance. 

Docker version for Hudson client:

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
```

Docker info for Hudson client:

```
Containers: 0
Images: 331
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /opt/docker/aufs
 Backing Filesystem: extfs
 Dirs: 331
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-35-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 7.305 GiB
Name: hudson
ID: LYVD:KR2M:TNHJ:XD55:YQYY:6UY2:OSJD:HAJP:3VJY:IV3F:PUIP:QPGS
WARNING: No swap limit support
```

What can I do to speed things up? Is this the right forum for asking for help?

**Comment by thaJeztah** [comment]
Are you seeing comparable slowdown when pushing to Docker Hub, or only to your own registry?
Perhaps this issue is better files in the "distribution" repository if it's only to your own registry; https://github.com/docker/distribution/issues?utf8=✓&q=is%3Aissue+is%3Aopen+s3

**Comment by ibuys** [comment]
It's just for my own registry, I can't use Docker Hub in our organization. Thanks for the comment, I'll move my question over.

**Comment by thaJeztah** [comment]
@ibuys make sure to search existing issues (also closed ones), I think there's quite some issues related to s3

**Comment by ibuys** [comment]
@thaJeztah, will do, thanks.
