### ISSUE TITLE
Docker 1.9.1 + aufs driver delets files on host mount

### ISSUE THREAD

**Issue by frank-dspeed** [docker/docker#18646]
docker info
Containers: 7
Images: 38
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 52
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.0-18-generic
Operating System: Ubuntu 15.10
CPUs: 16
Total Memory: 57.6 GiB
Name: s5
ID: 57S3:AFMS:TF2J:647U:EXIW:JRGF:UL3P:O26E:MZ7A:XT7O:5OXH:BXXR

docker run -v /host/dir/file:/container/dir/file results in host file getting directory that is empty and gets fully overwritten error from docker:

imestamp: 2015-12-14 20:14:56.082366642 +0000 UTC
Code: System error

Message: not a directory

Frames:
---
0: setupRootfs
Package: github.com/opencontainers/runc/libcontainer
File: rootfs_linux.go@40
---
1: Init
Package: github.com/opencontainers/runc/libcontainer.(*linuxStandardInit)
File: standard_init_linux.go@57
---
2: StartInitialization
Package: github.com/opencontainers/runc/libcontainer.(*LinuxFactory)
File: factory_linux.go@242
---
3: initializer
Package: github.com/docker/docker/daemon/execdriver/native
File: init.go@35
---
4: Init
Package: github.com/docker/docker/pkg/reexec
File: reexec.go@26
---
5: main
Package: main
File: docker.go@18
---
6: main
Package: runtime
File: proc.go@63
---
7: goexit
Package: runtime
File: asm_amd64.s@2232
Error response from daemon: Cannot start container a951580fae53f63b85b607a7da0a3c28a39dfe0a643bb53454c95ad5743f1738: [8] System error: not a directory

**Comment by frank-dspeed** [comment]
ah no was fail with host volume but anyway docker gives this error if you whant to mount a file that not exists and it creates dirs for it

**Comment by cpuguy83** [comment]
This is expected behavior.
There is not anything Docker can do if the host side doesn't exist and you wanted the file.
Docker 1.11 will no longer even create the host-side when non-existent.
