### ISSUE TITLE
How do run docker exec with user and password?

### ISSUE THREAD

**Issue by aalbadeb** [docker/docker#18640]
I feel there is a security issue in running docker exec --user=root -i -t container_name /bin/bash without any password. Is there any way to secure this? I need to ask for the password of the user when exec is run.

**Comment by cpuguy83** [comment]
No.
By convention, any user with access to docker has full root access to the host, which makes root access to the container moot.

Docker now has an authorization framework in master, which can be used to limit this sort of access. It will be available in Docker 1.10.

**Comment by m-abramovich** [comment]
> No.
> By convention, any user with access to docker has full root access to the host, which makes root access to the container moot.
> 
> Docker now has an authorization framework in master, which can be used to limit this sort of access. It will be available in Docker 1.10.

There is no such convention. Any user in the docker group has an access to Unix-socket of docker daemon and can reach a container without having any privileges on the parental OS.

**Comment by cpuguy83** [comment]
If you have access to the Docker socket, then that gives you effectively full root access to the host.

There is an exception these days since dockerd can run without root privileges. It requires some setup, but it can.

**Comment by m-abramovich** [comment]
> If you have access to the Docker socket, then that gives you effectively full root access to the host.
> 
> There is an exception these days since dockerd can run without root privileges. It requires some setup, but it can.

Of course no! 

<img width="726" alt="Screen Shot 2020-10-14 at 11 04 25" src="https://user-images.githubusercontent.com/5167854/95961045-3286f080-0e0d-11eb-87d7-b2ee32f22c12.png">

**Comment by cpuguy83** [comment]
docker run --rm -v /root:/root busybox ls /root

**Comment by m-abramovich** [comment]
> docker run --rm -v /root:/root busybox ls /root

This is a container OS, not parental (host). Of course you have a full access to container OS.
You said before: "has full root access to the host"

**Comment by cpuguy83** [comment]
No, that is the host's /root mounted into the container.
The ls is listing the host's /root.

**Comment by m-abramovich** [comment]
> No, that is the host's /root mounted into the container.
> The ls is listing the host's /root.

Ah, I understood what you mean. Indeed, you just reached host root system. But this is only because you started Docker service as root which is clear security violation.

**Comment by cpuguy83** [comment]
Right. That's how docker runs.
You can make it work with an unprivileged user now, but this is relatively new and non-trivial.

**Comment by m-abramovich** [comment]
> Right. That's how docker runs.
> You can make it work with an unprivileged user now, but this is relatively new and non-trivial.

What is new? 
Root privileges in OS? It was implemented in first UNIX at January, 1970. 
Ability to choose user in Linux upon service start? Most recent time it was done in March 30, 2010 (systemd).
Docker just created systemd config (/lib/systemd/system/docker.service) with root inside that anybody can change on his own by altering only one string - year 2013.

Nothing new introduced ever since regarding that issue :-) 
You just didn't know about that because never cared about privileges aspect of any service in Linux. It is not related to Docker anyhow.

**Comment by cpuguy83** [comment]
Dockerd requires root privileges to do much of what it does (setting up cgroups, applying seccomp profiles, mounting things).

A lot of work has gone into making it work without root privileges, and that is new.

I do not know why you are arguing with me. I know full well how Docker works. I am a top committer and help maintain this project.

Again, for anyone who comes on this issue: anyone who has access to the Docker API can escalate privileges.
There are ways around this (rootless mode, see the docs for setting this up as well as the limitations).

**Comment by cpuguy83** [comment]
Locking this issue since there is no need to discuss this further.
