### ISSUE TITLE
docs: reference/api/docker-io_api deprecated links back to itself

### ISSUE THREAD

**Issue by lloydde** [docker/docker#18656]
Description of problem:
https://docs.docker.com/engine/reference/api/docker-io_api/ links right back to itself

~~~
<p>This API is deprecated as of 1.7. To view the old version, see the <a href="../../../../engine/reference/api/docker-io_api/">Docker Hub API</a> in the 1.7 documentation.</p>
~~~

`docker version`: n/a

`docker info`: n/a

`uname -a`: n/a

Environment details (AWS, VirtualBox, physical, etc.): 
https://docs.docker.com/

How reproducible:
always

Steps to Reproduce:
1. Go to https://docs.docker.com/engine/reference/api/docker-io_api/

Actual Results:
- "Docker Hub API" is a link back to the same page, https://docs.docker.com/engine/reference/api/docker-io_api/

Expected Results:
- A link to the v1.7 docs.

Additional info:
None

**Comment by thaJeztah** [comment]
Thanks for reporting! This was actually fixed recently in this PR; https://github.com/docker/docker/pull/18341, but not yet published on the website.

I'll close this issue, because this is fixed, but feel free to comment after I've closed :+1:

**Comment by lloydde** [comment]
Thanks @thaJeztah .

**Comment by lloydde** [comment]
@thaJeztah I just had another thought, could also include add another sentence

> The new API is [Docker Registry HTTP API V2](https://docs.docker.com/registry/spec/api/).

**Comment by thaJeztah** [comment]
@lloydde adding a reference to the new (V2) API as well could make sense; if you're interested, feel free to open a pull request :+1:
