### ISSUE TITLE
Proposal: Support --cgroups:container:<id>

### ISSUE THREAD

**Issue by mrunalp** [docker/docker#18654]
It should be possible to run two containers that run under the exact same cgroup. One easy and natural way to support that is similar to how namespaces are supported by allowing one to use the cgroups of another container.

@LK4D4 @crosbymichael WDYT?

**Comment by mrunalp** [comment]
@vishh ping

**Comment by cpuguy83** [comment]
Or `--cgroup-parent=container:<container>`.
Also +1 to this.

**Comment by mrunalp** [comment]
@cpuguy83 Actually cgroup parent and what this is proposing are different. cgroup parent means one level up in the hierarchy. This proposal is for exact same cgroups like how docker exec gets the same cgroups as the original container.

**Comment by vishh** [comment]
@mrunalp: How about explicitly specifying cgroups for a container? `--cgroup=/foo/bar`

**Comment by mrunalp** [comment]
Yes, was planning to open a separate issue for that.

**Comment by coolljt0725** [comment]
Also +1 to this. 
`--cgroup=/foo/bar` or `--cgroup=container:<container>`

**Comment by hqhq** [comment]
@mrunalp I don't think the middle `container` is necessary, how about we support `--cgroup=/foo/bar` and `--cgroup=name`, just like what `--cgroup-parent` does. I think that'll meet all our needs.

**Comment by dqminh** [comment]
Interesting. I'm kinda on the fence for this one and would like to know the use case for this. Hierarchy placement often results in clearer semantics and equivalent resource restrictions.

Also what should we do when we shares cgroups with a container that has pid=host i.e. we depends on cleaning the cgroups to cleanup the container ?

**Comment by mrunalp** [comment]
@hqhq This is for similarity with namespaces like how one can give --ipc:container:fadfaf for e.g. So, we should be able to support that for containers as well. Also, we can support --cgroup-path = /path/to/cgroup. This is different than cgroup-parent which specifies the parent directory but not the entire path. --cgroups=container:<id> will basically join the cgroups of the specified id just like we do in docker exec.

**Comment by mrunalp** [comment]
@dqminh The use case is running two containers in exact same cgroups like with docker exec. Yes, we will have handle edge cases such as pid=host and document the behavior so it is well understood.

**Comment by mrunalp** [comment]
I have it working on a branch here https://github.com/mrunalp/docker/tree/cgroup_container. I will create PRs to runc/docker.

**Comment by LK4D4** [comment]
@mrunalp This wasn't implemented? Are you still interested?

**Comment by mrunalp** [comment]
@LK4D4 I am not actively working on this. I ran into issues trying to cleanly kill the processes with pid=host. We decided to just use cgroup parent instead. If I find a good workaround, I will open a PR.

**Comment by crosbymichael** [comment]
I think cgroup-parent solves these problems and does it much more robust without having to require some running container to share cgroups.  Too much overhead for what you can already do with cgroup-parent
