### ISSUE TITLE
Incorrect detail status of pull new image

### ISSUE THREAD

**Issue by linlinlinlin** [docker/docker#18658]
Description of problem:
Using pull API to pull an image. But sometime it response detail information with ```total:-1```.

`docker version`:
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.1
 Git commit:   d997753
 Built:        Thu Nov 26 02:31:23 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.1
 Git commit:   d997753
 Built:        Thu Nov 26 02:31:23 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:
```
Containers: 0
Images: 116
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 116
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-65-generic
```

`uname -a`:
Linux trusty-64abced 3.13.0-65-generic #106-Ubuntu SMP Fri Oct 2 22:08:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details: VirtualBox

How reproducible:
Just pull images by docker-py

Steps to Reproduce:
1. Pull image by docker-py
2. Check the stream output

Actual Results:
```
{u'id': u'379cc190f32e',
 u'progress': u'7.395 MB',
 u'progressDetail': {u'current': 7395421, u'total': -1},
 u'status': u'Downloading'}
```

Expected Results:
total without -1

Additional info:

**Comment by thaJeztah** [comment]
I haven't used docker-py really, but could this be an issue in docker-py?

ping @shin- ^^

**Comment by linlinlinlin** [comment]
docker-py doesn't control the output of the API. 

Ref: https://github.com/docker/docker-py/issues/876

**Comment by thaJeztah** [comment]
Ah, thanks, I wasn't sure if it recalculated things. Would you be able to test if this is still an issue on master? There's been quite some changes in this area (for the 1.10 release). You can get master builds from https://master.dockerproject.org - please note that those should be for testing purposes only, not for production use or use on critical data :smile:

**Comment by HackToday** [comment]
@thaJeztah do we usually install master with https://master.dockerproject.org/  ?
I remember we have one doc for configure docker to install from source or binary.

Could you help show me about it ?  I' like to try it.

**Comment by thaJeztah** [comment]
@HackToday https://master.dockerproject.org is the easiest way for people to test (although they're static builds, so with some limitations). Instructions for building docker can be found https://github.com/docker/docker/blob/master/project/PACKAGERS.md and in our contributors guide; https://docs.docker.com/opensource/project/set-up-dev-env/

**Comment by HackToday** [comment]
#dibs

**Comment by HackToday** [comment]
I tried with docker version 1.9.1
docker-py  1.6.0 (latest)
ubuntu 15.04   Linux tmptest 3.19.0-30-generic

for line in cli.pull('busybox', stream=True):
    print(json.dumps(json.loads(line), indent=4))
   "status": "Downloading", 
    "progressDetail": {
        "current": 2043521, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[====================================>              ] 2.044 MB/2.786 MB"
}
{
    "status": "Downloading", 
    "progressDetail": {
        "current": 2076289, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=====================================>             ] 2.076 MB/2.786 MB"
}
{
    "status": "Downloading", 
    "progressDetail": {
        "current": 2109057, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=====================================>             ] 2.109 MB/2.786 MB"
}
{
    "status": "Downloading", 
    "progressDetail": {
        "current": 2141825, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[======================================>            ] 2.142 MB/2.786 MB"
}
{
    "status": "Downloading", 
    "progressDetail": {
        "current": 2178881, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=======================================>           ] 2.179 MB/2.786 MB"
}
{
    "status": "Downloading", 
    "progressDetail": {
        "current": 2220817, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=======================================>           ] 2.221 MB/2.786 MB"
}
{
    "status": "Downloading", 
    "progressDetail": {
        "current": 2264369, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[========================================>          ] 2.264 MB/2.786 MB"
}
{
    "status": "Downloading", 
    "progressDetail": {
        "current": 2302081, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=========================================>         ] 2.302 MB/2.786 MB"
}
{
    "status": "Downloading", 
    "progressDetail": {
        "current": 2333481, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=========================================>         ] 2.333 MB/2.786 MB"
}
{
    "status": "Downloading", 
    "progressDetail": {
        "current": 2370865, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[==========================================>        ] 2.371 MB/2.786 MB"
}
{
    "status": "Downloading", 
    "progressDetail": {
        "current": 2403633, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[===========================================>       ] 2.404 MB/2.786 MB"
}
{
    "status": "Downloading", 
    "progressDetail": {
        "current": 2436401, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[===========================================>       ] 2.436 MB/2.786 MB"
}
{
    "status": "Downloading", 
    "progressDetail": {
        "current": 2474289, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[============================================>      ] 2.474 MB/2.786 MB"
}
{
    "status": "Downloading", 
    "progressDetail": {
        "current": 2503905, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[============================================>      ] 2.504 MB/2.786 MB"
}
{
    "status": "Downloading", 
    "progressDetail": {
        "current": 2540593, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=============================================>     ] 2.541 MB/2.786 MB"
}
{
    "status": "Downloading", 
    "progressDetail": {
        "current": 2569617, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[==============================================>    ]  2.57 MB/2.786 MB"
}
{
    "status": "Downloading", 
    "progressDetail": {
        "current": 2601289, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[==============================================>    ] 2.601 MB/2.786 MB"
}
{
    "status": "Downloading", 
    "progressDetail": {
        "current": 2637881, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[===============================================>   ] 2.638 MB/2.786 MB"
}
{
    "status": "Downloading", 
    "progressDetail": {
        "current": 2681265, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[================================================>  ] 2.681 MB/2.786 MB"
}
{
    "status": "Downloading", 
    "progressDetail": {
        "current": 2714033, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[================================================>  ] 2.714 MB/2.786 MB"
}
{
    "status": "Downloading", 
    "progressDetail": {
        "current": 2744601, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=================================================> ] 2.745 MB/2.786 MB"
}
{
    "status": "Downloading", 
    "progressDetail": {
        "current": 2780265, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=================================================> ]  2.78 MB/2.786 MB"
}
{
    "status": "Downloading", 
    "progressDetail": {
        "current": 2786486, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[==================================================>] 2.786 MB/2.786 MB"
}
{
    "status": "Verifying Checksum", 
    "progressDetail": {}, 
    "id": "a9f7a6348729"
}
{
    "status": "Download complete", 
    "progressDetail": {}, 
    "id": "a9f7a6348729"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 32768, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[>                                                  ] 32.77 kB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 65536, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=>                                                 ] 65.54 kB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 98304, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=>                                                 ]  98.3 kB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 131072, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[==>                                                ] 131.1 kB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 163840, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[==>                                                ] 163.8 kB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 196608, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[===>                                               ] 196.6 kB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 229376, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[====>                                              ] 229.4 kB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 262144, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[====>                                              ] 262.1 kB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 294912, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=====>                                             ] 294.9 kB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 327680, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=====>                                             ] 327.7 kB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 360448, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[======>                                            ] 360.4 kB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 393216, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=======>                                           ] 393.2 kB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 425984, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=======>                                           ]   426 kB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 458752, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[========>                                          ] 458.8 kB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 491520, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[========>                                          ] 491.5 kB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 524288, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=========>                                         ] 524.3 kB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 557056, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=========>                                         ] 557.1 kB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 589824, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[==========>                                        ] 589.8 kB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 622592, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[===========>                                       ] 622.6 kB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 655360, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[===========>                                       ] 655.4 kB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 688128, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[============>                                      ] 688.1 kB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 720896, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[============>                                      ] 720.9 kB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 753664, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=============>                                     ] 753.7 kB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 786432, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[==============>                                    ] 786.4 kB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 819200, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[==============>                                    ] 819.2 kB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 851968, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[===============>                                   ]   852 kB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 884736, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[===============>                                   ] 884.7 kB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 917504, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[================>                                  ] 917.5 kB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 950272, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=================>                                 ] 950.3 kB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 983040, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=================>                                 ]   983 kB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 1015808, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[==================>                                ] 1.016 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 1048576, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[==================>                                ] 1.049 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 1081344, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[===================>                               ] 1.081 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 1114112, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[===================>                               ] 1.114 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 1146880, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[====================>                              ] 1.147 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 1179648, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=====================>                             ]  1.18 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 1212416, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=====================>                             ] 1.212 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 1245184, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[======================>                            ] 1.245 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 1277952, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[======================>                            ] 1.278 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 1310720, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=======================>                           ] 1.311 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 1343488, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[========================>                          ] 1.343 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 1376256, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[========================>                          ] 1.376 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 1409024, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=========================>                         ] 1.409 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 1441792, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=========================>                         ] 1.442 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 1474560, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[==========================>                        ] 1.475 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 1507328, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[===========================>                       ] 1.507 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 1540096, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[===========================>                       ]  1.54 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 1572864, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[============================>                      ] 1.573 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 1605632, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[============================>                      ] 1.606 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 1638400, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=============================>                     ] 1.638 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 1671168, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=============================>                     ] 1.671 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 1703936, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[==============================>                    ] 1.704 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 1736704, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[===============================>                   ] 1.737 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 1769472, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[===============================>                   ] 1.769 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 1802240, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[================================>                  ] 1.802 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 1835008, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[================================>                  ] 1.835 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 1867776, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=================================>                 ] 1.868 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 1900544, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[==================================>                ] 1.901 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 1933312, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[==================================>                ] 1.933 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 1966080, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[===================================>               ] 1.966 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 1998848, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[===================================>               ] 1.999 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 2031616, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[====================================>              ] 2.032 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 2064384, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=====================================>             ] 2.064 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 2097152, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=====================================>             ] 2.097 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 2129920, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[======================================>            ]  2.13 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 2162688, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[======================================>            ] 2.163 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 2195456, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=======================================>           ] 2.195 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 2228224, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=======================================>           ] 2.228 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 2260992, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[========================================>          ] 2.261 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 2293760, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=========================================>         ] 2.294 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 2326528, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=========================================>         ] 2.327 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 2359296, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[==========================================>        ] 2.359 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 2392064, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[==========================================>        ] 2.392 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 2424832, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[===========================================>       ] 2.425 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 2457600, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[============================================>      ] 2.458 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 2490368, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[============================================>      ]  2.49 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 2523136, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=============================================>     ] 2.523 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 2555904, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=============================================>     ] 2.556 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 2588672, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[==============================================>    ] 2.589 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 2621440, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[===============================================>   ] 2.621 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 2654208, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[===============================================>   ] 2.654 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 2686976, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[================================================>  ] 2.687 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 2719744, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[================================================>  ]  2.72 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 2752512, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=================================================> ] 2.753 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 2785280, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[=================================================> ] 2.785 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 2786486, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[==================================================>] 2.786 MB/2.786 MB"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 2786486, 
        "total": 2786486
    }, 
    "id": "a9f7a6348729", 
    "progress": "[==================================================>] 2.786 MB/2.786 MB"
}
{
    "status": "Pull complete", 
    "progressDetail": {}, 
    "id": "a9f7a6348729"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 32, 
        "total": 32
    }, 
    "id": "1356831708f4", 
    "progress": "[==================================================>]     32 B/32 B"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 32, 
        "total": 32
    }, 
    "id": "1356831708f4", 
    "progress": "[==================================================>]     32 B/32 B"
}
{
    "status": "Extracting", 
    "progressDetail": {
        "current": 32, 
        "total": 32
    }, 
    "id": "1356831708f4", 
    "progress": "[==================================================>]     32 B/32 B"
}
{
    "status": "Pull complete", 
    "progressDetail": {}, 
    "id": "1356831708f4"
}
{
    "status": "Digest: sha256:7d3ce4e482101f0c484602dd6687c826bb8bef6295739088c58e84245845912e"
}
{
    "status": "Pulling from library/busybox", 
    "id": "ubuntu"
}
{
    "status": "Digest: sha256:8f1d9b6168120d917eb8539a8cc590c1161a2aa7cdda8ca62962d9ee012b29ef"
}
{
    "status": "Status: Downloaded newer image for busybox"
}


I did not find your issue @linlinlinlin 
Could you check if your systems issue? Or you can get more logs in with docker daemon -D.  and paste the logs when you call docker-py

**Comment by linlinlinlin** [comment]
@HackToday  please check my gist. https://gist.github.com/linlinlinlin/1bfc4e164083b8518038

python code:
```
import docker
import json

cli = docker.Client(version='1.21')

for line in cli.pull('centos', stream=True):
    print(json.dumps(json.loads(line), indent=4))
```

**Comment by HackToday** [comment]
@linlinlinlin  as i said,  please upload with your docker daemon logs(which enable  debug)
The detailed docker daemon logs can help more

**Comment by linlinlinlin** [comment]
Cannot reproduce it every time. If I got more debug logs. I will post it.

**Comment by thaJeztah** [comment]
@linlinlinlin I'll close this issue in the meantime, let me know if you have more information, then I'll reopen
