### ISSUE TITLE
IPv6 gateway is not configured when using custom networks

### ISSUE THREAD

**Issue by cdauth** [docker/docker#18657]
Description of problem:

When I create a container using the default network, an IPv6 default route (`default via fe80::1 dev eth0`) is set up in the container (as described in the [docs](https://docs.docker.com/engine/userguide/networking/default_network/ipv6/)). This works even when no IPv6 subnet is defined using `--fixed-cidr-v6` and thus the network device inside the container only has a link-local `fe80::/64` address.

When using a custom network, the IPv6 default route seems to be never created, even when the network has a gateway configured.

`docker version`:

Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   a34a1d5-dirty
 Built:        Sun Nov 22 00:15:15 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   a34a1d5-dirty
 Built:        Sun Nov 22 00:15:15 UTC 2015
 OS/Arch:      linux/amd64

`docker info`:

Containers: 7
Images: 82
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-254:43-2359300-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 7.192 GB
 Data Space Total: 107.4 GB
 Data Space Available: 47.2 GB
 Metadata Space Used: 7.565 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.14 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /srv/var/docker/devicemapper/devicemapper/data
 Metadata loop file: /srv/var/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.113 (2015-12-05)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.5-1-ARCH
Operating System: Arch Linux (containerized)
CPUs: 4
Total Memory: 3.28 GiB
Name: edeltraud
ID: 2YS3:2I6R:YDY6:VVEY:D2S7:ZSLF:RD4D:FRUQ:2H4V:NNAE:IBBF:CFWA

`uname -a`:

Linux edeltraud 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux

Steps to Reproduce:
1. `docker network create --subnet=10.92.100.0/24 --subnet=fd82:f2c8:25b7:100::/64 --gateway=fd82:f2c8:25b7:100::1 test100`
2. `docker create --net=test100 -ti debian`
3. `ip -6 route`

Actual Results:

No IPv6 default route is set up. The IPv4 and IPv6 addresses and the IPv4 address are properly set up.

Expected Results:

A default route via the configured IPv6 gateway, or – if none is configured – via the gateway configured as by `docker daemon --default-gateway-v6`, or otherwise via `fe80::1` should be set up.

Additional info:

Using a global subnet didn’t change anything.

**Comment by aboch** [comment]
Thanks @cdauth for reporting this.

I see the issue and I see where the code needs a change.
Will try to get this in 1.9.2. Thanks.
