### ISSUE TITLE
Docker ignores DOCKER_OPTS when started through systemd

### ISSUE THREAD

**Issue by esbenrug** [docker/docker#18663]
Description of problem:
When I setup the DOCKER_OPTS environment variable through a 'Environment' declaration in the systemd configuration file 
'/etc/systemd/system/multi-user.target.wants/docker.service'
or in a dedicated custom file
'/etc/systemd/system/docker.service.d/enableRestRemoteApi.conf'
and starts docker as a service by
'systemctl start docker.service'
docker ignores/doesn't pick up the content of DOCKER_OPTS.

I am running Ubuntu 15.10 wily werewolf
Systemd is version 225

`docker version`:
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64

`docker info`:
Containers: 19
Images: 130
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 168
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.0-19-generic
Operating System: Ubuntu 15.10
CPUs: 4
Total Memory: 3.558 GiB
Name: esben-ThinkPad-T440s
ID: ACN6:P7N7:Z53I:RJAZ:4XDU:2RKK:4XEO:Y2CH:UGWS:RXEG:GSW3:X3E3
WARNING: No swap limit support

`uname -a`:
Linux esben-ThinkPad-T440s 4.2.0-19-generic #23-Ubuntu SMP Wed Nov 11 11:39:30 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
physical laptop

How reproducible:
Every time

Steps to Reproduce:
1. Stop docker service doing 'systemctl stop docker'
2.Add the line 
Environment="DOCKER_OPTS=-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock"
in
'/etc/systemd/system/multi-user.target.wants/docker.service'
in the [Service] section of the file
3. Reload the systemd configuration doing 'systemctl daemon-reload'
4. Start the service again doing 'systemctl start docker'
5. Do a 
curl -X GET http://127.0.0.1:2375/images/json
to verify that the remote API doesn't run and you get a 'connection refused'

Actual Results:
Connection refused

Expected Results:
json-data

**Comment by thaJeztah** [comment]
The `DOCKER_OPTS` env var is only used by upstart, see https://github.com/docker/docker/blob/6417c53c5ac4a066a0743c595e53c599a21c1e7e/contrib/init/upstart/docker.conf#L42

If you want to customize this, look in this section, that describes the use of an environment-file, and how to override the default ExecStart in a drop-in; https://docs.docker.com/engine/articles/systemd/#custom-docker-daemon-options

Hope this will help you further. I'm closing this issue, because I don't think this is a bug, but feel free to comment here if you think I closed this by mistake :+1:
