### ISSUE TITLE
Docker registry doesn't work well for the existing images if the internet is turned off

### ISSUE THREAD

**Issue by freewind** [docker/docker#18678]
I have posted the question here: http://stackoverflow.com/questions/34294996/if-the-docker-registry-cant-visit-the-remote-proxy-url-it-cant-provide-servic

I hope the registry can serve for the existing images even if it can't visit the remote proxy url. For some reasons, the remote proxy url is not stable sometimes.

**Comment by freewind** [comment]
**docker version:**

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```

**docker info:**

```
~ $ docker info
Containers: 2
Images: 122
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 126
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: registry
ID: MJKP:EIA7:EJOH:XPSL:5VVN:GV2K:WJHU:E4ZC:XELL:GFLN:JED4:MBOQ
Debug mode (server): true
 File Descriptors: 25
 Goroutines: 48
 System Time: 2015-12-15T16:49:58.254548191Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: nowind
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```
uname -a:

```
Darwin Freewind.local 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64
```

Provide additional environment details (AWS, VirtualBox, physical, etc.): `Mac OSX 10.11.1 (15B42)` + `VirtualBox Version 5.0.10 r104061`

List the steps to reproduce the issue:
1. `docker run -e REGISTRY_PROXY_REMOTEURL=http://some-remote-proxy-url -d -p 5000:5000 --restart=always --name registry registry:2`
2. `docker pull library/ubuntu` from a docker which uses the registry from previous step
3. It's working well for now
4. `http://localhost:5000/v2/library/ubuntu/manifests/latest` will return a json which contains lot of manifest information
5. Turn off the internet, so my computer can't visit any internet urls
6. Delete the pulled image from the docker which uses the registry: `docker rmi library/ubuntu`
7. Redo step 2, to pull `library/ubuntu` again. It will fail and say "index.docker.io" is not visiable
8. Visit `http://localhost:5000/v2/library/ubuntu/manifests/latest` will show some error like: 

```
{
  "errors": [
    {
      "code": "MANIFEST_UNKNOWN",
      "message": "manifest unknown",
      "detail": {
        "Op": "Get",
        "URL": "http://some-remote-proxy-url/v2/library/ubuntu/manifests/latest",
        "Err": {
          "Op": "dial",
          "Net": "tcp",
          "Source": null,
          "Addr": null,
          "Err": {
            "Err": "read udp 172.17.0.2:57547->192.168.31.1:53: i/o timeout",
            "Name": "some-remote-proxy-url",
            "Server": "192.168.31.1:53",
            "IsTimeout": true
          }
        }
      }
    }
  ]
}
```

Describe the results you received:

"MANIFEST_UNKNOWN", seems like the registry is trying to visit the remote proxy url and failed, returns this error to client.

Describe the results you expected:

The correct manifest information about the image, like the condition that the internet is on. So the `docker pull library/ubuntu` will successfully download the necessary data

Provide additional info you think is important:

I think for the cached images, the registry should ignore the error when visiting remote proxy failed and use the one it has to the client.

**Comment by thaJeztah** [comment]
If I understand your issue correctly, this is about changes to the registry; if it is, I think this issue is better opened in the https://github.com/docker/distribution issue tracker. Can you re-open this issue there?

**Comment by freewind** [comment]
Yes, you are right, thanks!
