### ISSUE TITLE
Named volumes do not copy existing data from image path to volume.

### ISSUE THREAD

**Issue by srust** [docker/docker#18670]
When a container is created, a volume can be used which is mounted on a directory which already contains data from the image.

For anonymous volumes, this data is copied to the volume before mounting over the directory in the image.

However, for named volumes, this data is *not* copied. Even if the volume driver is local.

Here is the anonymous volume case:
````
$ docker run -it --rm -v /home busybox sh
````
````
DEBU[0088] Registering new volume reference: driver , name 9829aab88c7b64631f6472ecb97a18643258389d3027f90192c573f33e32c450 
DEBU[0088] Incrementing volume reference: driver local, name 9829aab88c7b64631f6472ecb97a18643258389d3027f90192c573f33e32c450 
DEBU[0088] Creating dest directory: /var/lib/docker/volumes/9829aab88c7b64631f6472ecb97a18643258389d3027f90192c573f33e32c450/_data 
DEBU[0088] Calling TarUntar(/var/lib/docker/devicemapper/mnt/5704f1232e1ef266ffba028f655d61cbbdc4aeb9726fd3f661d3f2c394d1ebe2/rootfs/home, /var/lib/docker/volumes/9829aab88c7b64631f6472ecb97a18643258389d3027f90192c573f33e32c450/_data) 
DEBU[0088] TarUntar(/var/lib/docker/devicemapper/mnt/5704f1232e1ef266ffba028f655d61cbbdc4aeb9726fd3f661d3f2c394d1ebe2/rootfs/home /var/lib/docker/volumes/9829aab88c7b64631f6472ecb97a18643258389d3027f90192c573f33e32c450/_data) 
````
````
# ls /home
default  ftp
````

And here is the named volume case:
````
$ docker run -it --rm -v myvol:/home busybox sh
````
````
DEBU[57755] Registering new volume reference: driver local, name myvol 
DEBU[57755] Incrementing volume reference: driver local, name myvol 
````
````
# ls /home
# 
````

So the question is: why is this behavior different? This behavior should not be different. And I'm sure this used to work in the past, perhaps in 1.8? Please take a look. Thanks!

It seems to me that **daemon.createContainerPlatformSpecificSettings()** is not even being called for the named volume case.

````
$ bundles/1.10.0-dev/dynbinary/docker version
Client:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.2
 Git commit:   75d69ce-dirty
 Built:        Mon Dec 14 23:27:34 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.2
 Git commit:   75d69ce-dirty
 Built:        Mon Dec 14 23:27:34 2015
 OS/Arch:      linux/amd64
````

**Comment by srust** [comment]
```
$ docker info
Containers: 2
Images: 469
Server Version: 1.10.0-dev
Storage Driver: devicemapper
 Pool Name: docker-253:1-45160620-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 17.61 GB
 Data Space Total: 107.4 GB
 Data Space Available: 2.456 GB
 Metadata Space Used: 29.21 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.118 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-229.4.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 2.782 GiB
Name: srust7-dev
ID: R7WO:GJ7Y:A7P5:PSRI:UGXM:5NAF:3NSR:N7FY:MI3K:YB4M:3IIY:HTFR
Debug mode (server): true
 File Descriptors: 15
 Goroutines: 25
 System Time: 2015-12-15T10:39:06.826074563-05:00
 EventsListeners: 0
 Init SHA1: 49ec76d501506269aa2b3110e6c3e93b4c9abcec
 Init Path: /home/srust/ws/github.com/docker/bundles/1.10.0-dev/dynbinary/dockerinit
 Docker Root Dir: /var/lib/docker
````

**Comment by HackToday** [comment]
tried on docker 1.8.3. and found both have empty, as below:
# docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Wed Dec 16 02:32:41 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Wed Dec 16 02:32:41 UTC 2015
 OS/Arch:      linux/amd64
root@c750f7f675dd:/go/src/github.com/docker/docker# docker run -it --rm -v /home busybox sh
/ # ls -l /home/
total 0
/ # exit
root@c750f7f675dd:/go/src/github.com/docker/docker# docker run -it --rm -v myvol:/home busybox sh
/ # ls -l /home/
total 0
/ #

**Comment by qq690388648** [comment]
It's not a bug, it acted as that because it should be that.
For the anonymous volume, <code>docker</code> know that the volumes is fully controlled by itself, so <code>docker</code> can do anythings it thought correct. But the names volume is designed for the volume plugin, so <code>docker</code> does not know what it should do, then does nothing.

**Comment by srust** [comment]
This has nothing to do with volume plugins, in both cases it is the local volume driver.

**Comment by qq690388648** [comment]
@srust 
What you said is the implement details, yes, both cases called the local volume driver finally. But what I meant is design: anonymous volume is one case, and named volume which usually be used with <code>--volume-driver</code> is another. So these two cases can act differently.

**Comment by HackToday** [comment]
This was a issue discussed before,

it was because, check this;

    "HostConfig": {
        "Binds": [
            "myvol:/home"
        ],



    "HostConfig": {
        "Binds": null,



The named volume case, which have host-bind, which seems override that /home, while annoymous cases seems not override. (I think)

ping @thaJeztah and @cpuguy83

**Comment by mariusGundersen** [comment]
This is also discussed here: https://github.com/docker/docker/issues/17470

I'll repeat what I said there:
`-v /host/path:/container/path` does not copy data
`-v /container/path` will copy data and creates new volume with a random name
`-v name:/container/path` does not copy data but creates a new volume with the name `name`

Wouldn't it be better to have a consistent implementation, so that either data is always copied, or never copied? I'm expecting several duplicates of this issue to pop up, since people might try the second case first (default, random container) and then give the volume a name and find that it behaves different.

**Comment by thaJeztah** [comment]
@mariusGundersen the "bind a host path" (`-v /host/path:/container/path`) case was also discussed in https://github.com/docker/docker/pull/9092, I was on the fence at that time (for cases where the "host path" didn't exist, so the directory was created automatically), but given that we're deprecating that behavior (see https://github.com/docker/docker/pull/16349), I don't think we should change it.

I *do* agree, however that `-v name:/container/path` should copy container data to the volume (if it's empty!), or have an option to allow doing so. Currently, named volumes are not populated, which makes them not a viable alternative to "nameless" volumes. Just my 0.02c :smile:

**Comment by thaJeztah** [comment]
I added both "enhancement" and "feature" labels, guess it depends on the implementation whatever it becomes, haha

**Comment by srust** [comment]
Thanks @HackToday for the pointer! And thanks @mariusGundersen for the comment.

An option to copy the data could make some sense, as long as the defaults are consistent across the volume cases (anonymous, named, plugin). I'm happy to work on a patch, just have to become familiar with this part of the code, so may not be immediate, others are welcome to it. ;)

Thanks @thaJeztah, appreciate the quick turnaround!

**Comment by thaJeztah** [comment]
@srust I expect that there'll still be discussion around this; also interested in input from @cpuguy83 and @calavera.

How should we handle volume-driver plugins that *don't* support this feature?

**Comment by srust** [comment]
Absolutely. Plugins generally complicate matters. :-) BTW, the copy behavior was changed for anonymous volumes to skip non-local drivers just recently, in https://github.com/docker/docker/commit/6b8129d1fe9b1428833e1c38e463a5a4cc204390/daemon/create_unix.go. Having the option to copy even for plugins would be preferred, in my opinion. For our use cases, this would make the most sense.

**Comment by thaJeztah** [comment]
Looks like this partly duplicates https://github.com/docker/docker/issues/18034 btw

**Comment by amirabiri** [comment]
Yes this touches on the same issue I reported as @thaJeztah points out.

I don't think changing the behaviour of `-v name:/container/path` is the best approach, since this forces the user to repeat information that is already present in the base image (and it should be maintained in the image spec IMO).

Instead either the behaviour of `--volumes-from` should change, or something new should be introduced that replaces it for volumes instead of containers.

Are there any news on weather this issue is likely to be addressed or not...?

**Comment by tianon** [comment]
+1 to what @thaJeztah said -- my biggest surprise when I used a named volume for the first time was that it acted in the same "unsupported hack" kind of way as a bind mount instead of acting like a nameless volume to which I could reference in other ways (which is what my understanding of named volumes were supposed to be)

**Comment by tiborvass** [comment]
Let's fix this

**Comment by dmandalidis** [comment]
I believe it's still doesn't work. Consider the following Dockerfile (image foo):

`FROM busybox:latest
RUN mkdir /data && touch /data/atestfile
CMD ls -la /data`

if I do :

`docker create -v foo1:/data foo`, then a volume having the atestfile is created.

but if I do :

`docker volume create --driver local --opt type=tmpfs --opt device=tmpfs --opt o=size=1m,uid=0 --name foo1`

then the first command doesn't copy anything.

Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:57:25 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:57:25 2016
 OS/Arch:      linux/amd64
 Experimental: true

Kernel: 3.19.0-66-generic

Containers: 7
 Running: 1
 Paused: 0
 Stopped: 6
Images: 756
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 591
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.19.0-66-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 993.2 MiB
Name: dock-02
ID: DBYH:VD7W:KJRG:5G2R:E62M:HLXE:4ZG6:GSCI:JIJN:YLXP:6HI2:63O5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://proxyblue.trasys.be:80
Https Proxy: http://proxyblue.trasys.be:80
No Proxy: 172.17.52.20
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 172.17.52.20:9090
 127.0.0.0/8

**Comment by cpuguy83** [comment]
@dmandalidis Please open a new issue.
