### ISSUE TITLE
building oracle linux 6 rpm fails on master 

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#18688]
error:
```
bundles/1.10.0-dev already exists. Removing.

---> Making bundle: dynbinary (in bundles/1.10.0-dev/dynbinary)
# github.com/opencontainers/runc/libcontainer/nsenter
In file included from vendor/src/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c:20:
/usr/include/linux/netlink.h:35: error: expected specifier-qualifier-list before 'sa_family_t'
error: Bad exit status from /var/tmp/rpm-tmp.GmZ0bL (%build)
    Bad exit status from /var/tmp/rpm-tmp.GmZ0bL (%build)
```

@Djelibeybi do you know if the version of C in that image would need something specific

**Comment by Djelibeybi** [comment]
I'll investigate and get back to you. I'm guessing glibc on OL6 is too old.

**Comment by Djelibeybi** [comment]
Actually, it's because we're trying to maintain compatibility with Red Hat's 2.6.32 kernel, so we're shipping kernel-headers and not providing updated headers specifically for the UEK (which is newer). This will require some interesting switching because we've specifically not shipping updated headers.

Let me do some internal research on this.

**Comment by Djelibeybi** [comment]
@jfrazelle can you put this on hold? We're not supporting Docker 1.9 or higher until we release our UEK4 (4.1.12) kernel so it's not going to build with the current OL6 Dockerfile anyway. 

I've opened an internal bug to fix the headers too.

**Comment by jfrazelle** [comment]
thanks so much!

**Comment by icecrime** [comment]
Closing this one as there's nothing more we can do on our end.

**Comment by thaJeztah** [comment]
@icecrime just thinking of this; we may have to add it in the release notes, that Oracle Linux is not supported in this release. I'll add "impact/changelog"

**Comment by Djelibeybi** [comment]
The notes should only list Oracle Linux 6. OL7 is not affected (I assume). Also, this should be resolved shortly with the release of UEK4 based on upstream 4.1 kernel.

**Comment by thaJeztah** [comment]
@Djelibeybi is there a ETA for that release? Code freeze for docker 1.10 is January 14th, and release hopefully 2-3 weeks after that

**Comment by Djelibeybi** [comment]
Target date for GA is 11 January, but we still need to modify our kernel-headers on OL6 to allow Docker to build without breaking kABI for our older kernels. 

I can't guarantee that we'll fix this by January 14th, but I've bumped the internal bug priority up to the highest level. If we don't get it in by 1.10 release, we should have it sometime thereafter.

**Comment by thaJeztah** [comment]
Thanks @Djelibeybi, keep us posted!

**Comment by Djelibeybi** [comment]
We have fixed the issue internally and have submitted a test RPM to our QA team to validate that it works. 

So, once UEK4 is released, I'll submit a PR that restores the contrib/builder/rpm/oraclelinux-6/Dockerfile.
