### ISSUE TITLE
setup-dev guide can be improve with good shell command

### ISSUE THREAD

**Issue by HackToday** [docker/docker#18698]
in the example: https://docs.docker.com/opensource/project/set-up-dev-env/

whenever follow this:

This host has no images. You may have one or more dangling images. A dangling image is not used by a running container and is not an ancestor of another image on your system. A fast way to remove dangling containers is the following:

$ docker rmi -f $(docker images -q -a -f dangling=true)

sometimes, the env not have dangling images, so it would complain like below:

$ docker rmi -f $(docker images -q -a -f dangling=true)
docker: "rmi" requires a minimum of 1 argument.
See 'docker rmi --help'.

Usage:	docker rmi [OPTIONS] IMAGE [IMAGE...]

I propose we improve like this:

$ dangling_images=`docker images -q -a -f dangling=true`; [ -n "$dangling_images" ] &&  docker rmi -f ${dangling_images}

**Comment by HackToday** [comment]
@thaJeztah  what do you think ?

**Comment by HackToday** [comment]
ping @thaJeztah

**Comment by thaJeztah** [comment]
Oh, sorry, I forgot to reply :blush:

I'm not sure we should make this command so complicated. `docker rmi -f $(docker images -q -a -f dangling=true)` is a fairly standard way to remove dangling images.

We could explain that if users get a "docker: "rmi" requires a minimum of 1 argument." message, that there were no dangling images *or* have them first check if there are dangling images.

It's probably better to explain *why* the warning is shown, than to show a really long command that nobody will remember

**Comment by HackToday** [comment]
Hi @thaJeztah so do you suggest let us add explantion about like this:
If you get a "docker: "rmi" requires a minimum of 1 argument." message, that there were no dangling images or have them first check if there are dangling images.

Is it ?

**Comment by HackToday** [comment]
@thaJeztah I am trying to fix this doc, but I did not find it in docker repo . Is it located in docker repo?

**Comment by thaJeztah** [comment]
@HackToday oh, you're right, these docs were moved to the "opensource" repository; https://github.com/docker/opensource/blob/master/docs/project/set-up-dev-env.md

**Comment by HackToday** [comment]
closed via
https://github.com/docker/opensource/pull/49
