### ISSUE TITLE
question - base image on Core OS Or Ubuntu Wily 15.10 ?

### ISSUE THREAD

**Issue by gedw99** [docker/docker#18704]
i need to run docker with overlay networking on:
- ec2
- virtualbox
- metal 

I wil be using compose, swarm, consol, overlay networking. SO basically all the latest stuff.

The question is which bae OS to use ?
Core OS Or
Ubuntu Wily 15.10

I am not sure.
The great think at least with CoreOS, is that the metal machine can automatically upgrade at the OS level. This is pretty important for us.

thansk in advance.

**Comment by thaJeztah** [comment]
I don't think the GitHub issue tracker is the best place to ask this question, and it really depends on your use case. Please note that we *don't* provide builds for CoreOS, and those versions can lag behind the current version of the official docker builds.

Please use either of the below;

1) the forums: https://forums.docker.com/
2) the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user
3) the #docker IRC channel on Freenode.

**Comment by gedw99** [comment]
OK thanks. Did not realise

**Comment by thaJeztah** [comment]
@gedw99 no problem! we're not *always* that strict, but the repository and issue tracker are very active already :smile:
