### ISSUE TITLE
Add support for importing or exporting from volumes

### ISSUE THREAD

**Issue by mariusGundersen** [docker/docker#18718]
Similar to [`docker export`](https://docs.docker.com/engine/reference/commandline/export/), add support for `docker volume export VOLUMENAME`, which is what [this answer does](http://stackoverflow.com/a/23778599). Similarly, it would be useful to be able to import content into a volume.

**Comment by thaJeztah** [comment]
ping @cpuguy83 I think this came up in another discussion, IIRC the opinion was to make that the responsibility of the driver/plugin. Should we make it accessible through the docker cli though? It would make a better UX than to have each driver/plugin having its own way to do this.

**Comment by cpuguy83** [comment]
I'd not be too quick to add this to the CLI.
It would require defining a standard format that all drivers must implement, which will end up being the worst format (tar)... which can be done easily enough by mounting the volume in a container and using `tar -c` on the volume.

**Comment by LK4D4** [comment]
It would be challenging to implement and pretty easy to workaround. Closing as inactive for now.

**Comment by ekkis** [comment]
not all drivers would have to implement it for the cli to offer the feature.  it could just come with caveats that this or that driver doesn't support it, and it would make it a substantially better UX than having to figure out where the volume reside and sudo/cp the files in place

**Comment by cpuguy83** [comment]
@ekkis You don't have to figure out where it is, you run `docker run -v <name>:/data myExportImage > data.tar`.
You could also use `docker cp` against a created container that has the volume.

There's lots of simple work-arounds, but adding something like this is something we have to maintain and again is going to be the worst format possible.

**Comment by ekkis** [comment]
I gather `MyExportImage` is some container? what container? one created just to mount things? as for `docker cp` the problem is that none of your containers may have their volumes mounted to the filesystem.  I just finished writing a docker-compose file for nginx/docker-gen/letsencrypt where the containers share volumes but none of them are mounted (they don't need to be).  so I realised I had no good way to just copy a file

**Comment by cpuguy83** [comment]
@ekkis 
>  what container

One created for the purpose of exporting data with backup tooling, or simply `tar`.

> none of them are mounted

`docker cp` mounts the volumes.

**Comment by mvasin** [comment]
@cpuguy83 What do you mean by mentioning that tar is the worst format for `volume export`? I'm just curious what's wrong with it.

**Comment by pauldraper** [comment]
What's the reason for exporting a container but not a volume?

Don't those have just as many driver complexities?

**Comment by cpuguy83** [comment]
@pauldraper There is no need to support export.
You can already "export" a volume with common tools see above comments.

**Comment by thaJeztah** [comment]
Also see https://github.com/docker/cli/issues/1436

**Comment by mwaeckerlin** [comment]
Please also add: `docker volume cp <volume-name> <path-name>` and vice versa. Optionally allow `docker cp <volume-name> <path-name>` instead.

**Comment by psawa** [comment]
This thread is 3 years old, what is the current status of the development of this feature?

**Comment by FlorianHeigl** [comment]
> @minecraftchest1 please don't comment on closed tickets without searching for other tickets; there's two open tickets about this;
> 
> * [Implement import & export functionality for volumes docker/cli#1436](https://github.com/docker/cli/issues/1436)
> * [Add command for backup and restore of volumes #38752](https://github.com/moby/moby/issues/38752)

if it's been opened in 2015 and the functionality didn't come around one could imagine people want to mention it here.
they didn't decide to track it elsewhere; it's likely more an indication that this was the essense of the missing feature and not the more limited in scope 'backup/restore' functionality...
