### ISSUE TITLE
Proposal: support google Cloud Logging 

### ISSUE THREAD

**Issue by daehyeok** [docker/docker#18726]
Cloud Logging in the Google cloud service(https://cloud.google.com/logging/docs/) is looks similar with AWS Cloud Watch(already supprorted for Docker log).
 It's worth for implement to log driver? if yes, i want to try it.

**Comment by thaJeztah** [comment]
We may need to decide which drivers we want to include by default, and which ones to keep external, once https://github.com/docker/docker/issues/18604 has been decided on

**Comment by calavera** [comment]
The next release will support Google Cloud: https://github.com/docker/docker/pull/18766.

Closing as fixed. :tada:
