### ISSUE TITLE
Content addressability changes break partial "docker load"

### ISSUE THREAD

**Issue by tianon** [docker/docker#18723]
Using Docker 1.9, a partial `docker load` tarball is entirely legal and functional.  To illustrate more clearly:
```Dockerfile
FROM debian@sha256:2a5204f0a00510e9b99d7ec0fe40bea495b8e3630b820b04675488aad4188e06
RUN apt-get update && apt-get install --no-install-recommends -y busybox-static && rm -rf /var/lib/apt/lists/*
```

I build this and tag it as `temp`, then I do a `docker save temp`.  Then I modify the tarball to only contain the final layer (not the `debian` layers), since I know that my target will already have that base layer.  I've pushed the result of doing that to https://gist.github.com/tianon/84ec7fa46eb9b273860b/raw/daa9849e9d8e011f64bfd0f84aacdb54dbba06ca/save.tar, which you can test on Docker 1.9 by doing something like this:
```console
$ docker pull debian@sha256:2a5204f0a00510e9b99d7ec0fe40bea495b8e3630b820b04675488aad4188e06
sha256:2a5204f0a00510e9b99d7ec0fe40bea495b8e3630b820b04675488aad4188e06: Pulling from library/debian
Digest: sha256:2a5204f0a00510e9b99d7ec0fe40bea495b8e3630b820b04675488aad4188e06
Status: Image is up to date for debian@sha256:2a5204f0a00510e9b99d7ec0fe40bea495b8e3630b820b04675488aad4188e06
$ curl -fsSL 'https://gist.github.com/tianon/84ec7fa46eb9b273860b/raw/daa9849e9d8e011f64bfd0f84aacdb54dbba06ca/save.tar' | docker load
```

As you can see, success.  When running from master, here's what you'll see:
```console
$ docker pull debian@sha256:2a5204f0a00510e9b99d7ec0fe40bea495b8e3630b820b04675488aad4188e06
sha256:2a5204f0a00510e9b99d7ec0fe40bea495b8e3630b820b04675488aad4188e06: Pulling from library/debian
d4bce7fd68df: Already exists 
a3ed95caeb02: Already exists 
Digest: sha256:2a5204f0a00510e9b99d7ec0fe40bea495b8e3630b820b04675488aad4188e06
Status: Image is up to date for debian@sha256:2a5204f0a00510e9b99d7ec0fe40bea495b8e3630b820b04675488aad4188e06
$ curl -fsSL 'https://gist.github.com/tianon/84ec7fa46eb9b273860b/raw/daa9849e9d8e011f64bfd0f84aacdb54dbba06ca/save.tar' | docker load
Error response from daemon: open /var/lib/docker/tmp/docker-import-654647903/23cb15b0fcece0623d706e9dbc3d9fce97937fb50ab3fbff8574206d258b6303/json: no such file or directory
```

Now I understand that this may be because `debian@sha256:2a5204f0a00510e9b99d7ec0fe40bea495b8e3630b820b04675488aad4188e06` gets a different ID, so the `load` tarball needs a different ID listed as the parent, so I tried re-creating that tarball from the master build (doing the `docker build -t temp` on my same example `Dockerfile`, followed by `docker save` and then manual tarball munging to remove layers I know my target will have), and the same error occurrs.

From the error message, it _appears_ that the new `load` behavior is instead requiring that _all_ parent layers exist within the tarball, which is a change in behavior -- I've also tried munging the layer `json` file directly to put in the content addressable layer ID instead of whatever `save` spits out for the base layer, but even that's a no-go.

cc @tonistiigi @aaronlehmann @vbatts

**Comment by tonistiigi** [comment]
Old style partial tars that use the parent chain will never work. If image points to a parent that doesn't exist in tar and in docker(it has new ID there) there is no way to connect it. "New-style" tars that use the full image config in tar could work. If they don't atm then it should be fixable.

**Comment by tianon** [comment]
Right, the tar in my example was generated with Docker 1.9 -- I'll go
create a new one generated with 1.10.

**Comment by tianon** [comment]
Since we tell people that "docker save" and "docker load" are the safe
way to move between versions freely (or move images across hosts), I
think the compatibility story there needs to be reasonably strong.

**Comment by tianon** [comment]
For reference, the reason I found this is that using a partial `docker save` tarball is the only way we could figure to strip the `onbuild` property of images (https://github.com/docker-library/official-images/blob/4ec142ab12adc7d8ec4ae544401258b15bee7af3/test/tests/remove-onbuild.sh).

**Comment by tianon** [comment]
So I'm OK with the constraint of layer IDs needing to exist as-is in the local daemon -- that makes perfect sense.

**Comment by tianon** [comment]
With `manifest.json`, I'm not sure how I'm expected to modify it to support a partial tarball -- if I leave layers in the manifest, they obviously fail to load (understandably), but if I remove them, then I get errors about there being a mismatch in the number of layers; any guidance on how I should update would be appreciated.

For reference, the generated `manifest.json` is as follows: (pretty-printed via `jq` for readability)
```json
[
  {
    "Config": "8bc4073af361b4910ce9b4f93446b57090663b99a04b11732247baaece1eeaf9.json",
    "RepoTags": [
      "temp:latest"
    ],
    "Layers": [
      "2c65e251db25bc1f327bf1e43e882893a6f7fd807d7091b0f3776cbbdf20431d/layer.tar",
      "d4f4a01f156042755ef9a3a3d258d347b9fee189dfb632ca6e30748cff1996a8/layer.tar",
      "0c5315d298eb37fc7f5c390d9a0afabdda0ef1fda7219b2d0696a9561f1ae6e3/layer.tar"
    ]
  }
]
```

**Comment by tianon** [comment]
If I remove `manifest.json` and `8bc4073af361b4910ce9b4f93446b57090663b99a04b11732247baaece1eeaf9.json` to force it to use the old-style calculations, I get an error about `parent-layer-id/json` not existing (somewhat expected).

I then tried modifying `./0c5315d298eb37fc7f5c390d9a0afabdda0ef1fda7219b2d0696a9561f1ae6e3/json` to reference the full `sha256:bd94bc3c03b912d00858df07f7c33ab748b3451a9810c59a5084ae578f90e891` version of the parent layer which was also unsuccessful.

**Comment by tonistiigi** [comment]
@tianon Nothing needs to be modified, You should remove the folders that are not needed, and these layers need to exist in docker already.

**Comment by tianon** [comment]
Right OK, makes sense; that's not working currently, which is why I was
looking at what might need to be modified there. :+1: :smile:

**Comment by stevvooe** [comment]
Should we even be supported partial `docker save` files? That just seems dangerous.

**Comment by tonistiigi** [comment]
@stevvooe that's a good point. It depends how much does the user trust the source.
