### ISSUE TITLE
docker operations hang

### ISSUE THREAD

**Issue by danbeaulieu** [docker/docker#18725]
Description of problem:
We spin up Ubuntu 14.04 instances in EC2 dozens of times per day and one of the first things they do is run a docker build. We've noticed about 10% of them result in the build hanging. Restarting docker seems to fix the problem, however this is not ideal. Our docker files are simple with a single COPY command, but we've reproduced the issue with a similarly simple docker file that does a RUN touch /tmp/foo.txt. Nothing indicates a problem in the docker log file or syslog.

`docker version`:
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:
```
Containers: 1
Images: 35
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-202:1-151855-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.726 GB
 Data Space Total: 107.4 GB
 Data Space Available: 2.497 GB
 Metadata Space Used: 4.149 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.143 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.17.8-031708-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 2
Total Memory: 3.676 GiB
Name: ip-10-229-68-94
ID: MBRU:GNHR:TQMN:IKES:H6HE:WMK3:RL7J:XP6M:2IGU:HCFL:E3MX:P362
Debug mode (server): true
 File Descriptors: 14
 Goroutines: 21
 System Time: 2015-12-16T15:20:31.070875482Z
 EventsListeners: 0
 Init SHA1: 4fc7c03a06c675f115b39958c13486d53df10a14
 Init Path: /usr/lib/docker/dockerinit
 Docker Root Dir: /var/lib/docker
WARNING: No swap limit support
```

`uname -a`:
```
3.17.8-031708-generic
```
Environment details (AWS, VirtualBox, physical, etc.):
AWS

How reproducible:
Not reliably reproducible, but a simple docker pull ubuntu:14.04 has shown to hang.

Steps to Reproduce:
docker pull ubuntu:14.04

Actual Results:
operation hangs indefinitely 

Expected Results:
docker pulls the image to the local registry

Additional info:

docker build is not the only command that hangs, docker info, docker run and docker pull all hang. I suspect it is related to devicemapper but there is no hard evidence. 
This coincides with an upgrade from docker 1.7.1 to 1.9.1.

I have the debug log as well that I can attach, however it doesn't look very interesting, these are the last few lines before it hangs (this is a build with a single COPY):

```
DEBU[0034] activateDeviceIfNeeded(f5b23b24b022ef7e9bd687bb1d94340d3a6e9c070602a3157af9634e7c0c8b50) 
DEBU[0035] Creating dest directory: /var/lib/docker/devicemapper/mnt/f5b23b24b022ef7e9bd687bb1d94340d3a6e9c070602a3157af9634e7c0c8b50/rootfs/opt/app/latest/ 
DEBU[0036] Calling TarUntar(/var/lib/docker/tmp/docker-builder791470213, /var/lib/docker/devicemapper/mnt/f5b23b24b022ef7e9bd687bb1d94340d3a6e9c070602a3157af9634e7c0c8b50/rootfs/opt/app/late
st/) 
DEBU[0036] TarUntar(/var/lib/docker/tmp/docker-builder791470213 /var/lib/docker/devicemapper/mnt/f5b23b24b022ef7e9bd687bb1d94340d3a6e9c070602a3157af9634e7c0c8b50/rootfs/opt/app/latest/) 
DEBU[0053] activateDeviceIfNeeded(f5b23b24b022ef7e9bd687bb1d94340d3a6e9c070602a3157af9634e7c0c8b50-init) 
```

**Comment by thaJeztah** [comment]
Is there a particular reason you're using devicemapper? (aufs is the "default" driver for ubuntu 14.04). Using loopback devices on device mapper is really discouraged and will give you really bad performance (including, e.g. deleting containers). If you want to stick with devicemapper, read this documentation, that explains how to run device mapper in "production" and get rid of loopback devices; https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#configure-direct-lvm-mode-for-production

The other parts of the "storage drivers" section in our docs may also be useful for selecting which driver best fits your use case; https://docs.docker.com/engine/userguide/storagedriver/imagesandcontainers/

**Comment by danbeaulieu** [comment]
@thaJeztah i'm not sure but we are taking the default Ubuntu 14.04 AMI and installing via 

```
apt-get -y --force-yes install docker-engine=1.9.1-0~trusty
```

We don't do any further customization to the install to tell it to use devicemapper.

We've used Docker in production like this for the past year and a half without issues, though I am not looking in to using overlayfs but something did change between 1.7 and 1.9.

**Comment by cpuguy83** [comment]
Yes, tons of changes.
@danbeaulieu Would you be able to post an strace when this hangs?

**Comment by danbeaulieu** [comment]
This is an strace while running the docker info command, the last syscall for build is different, so I don't think it is apparmor related. Again this AMI is created dozens of times per day with the exact same configuration.

[info_strace.txt](https://github.com/docker/docker/files/73360/info_strace.txt)

**Comment by danbeaulieu** [comment]
As an update we've been issue free since moving to overlayfs as our storage driver, however it still feels like there is a bug with devicemapper.

**Comment by unclejack** [comment]
@danbeaulieu Your AMI is using kernel `3.17.8-031708-generic` which is unsupported. This isn't a kernel provided through the official package repositories of any LTS kernel for Ubuntu 14.04.

Bugs should be expected when using such a setup. Kernel 3.17 has been deprecated a long time ago and it most likely lacks all the devicemapper bug fixes.

Please make sure you're using official kernels installed and kept up to date through the official package repositories. I'll close this issue since the bug report is from an unsupported setup.
