### ISSUE TITLE
docker images command doesn't work with private registry images after upgrade to 1.9.x

### ISSUE THREAD

**Issue by liang-bin** [docker/docker#18734]
Problem only seen in 1.9.0 and 1.9.1

With docker engine 1.8.0, 1.8.3, this command works:
$ docker images a.b.c.d:5000/my/common
REPOSITORY               TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
a.b.c.d:5000/my/common   latest              b8e35fab763f        2 hours ago         769.9 MB

Upgrade docker engine to 1.9.1, without changing anything else,run same command yield no result:
docker images a.b.c.d:5000/my/common
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
$

Here is output when not specify repository:
$ docker images
REPOSITORY                                    TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
a.b.c.d:5000/my/common                        latest              b8e35fab763f        2 hours ago         769.9 MB
eapm-lnx-30.xxx.com:5000/test/base-common   0.1.1               b8e35fab763f        2 hours ago         769.9 MB
eapm-lnx-30.xxx.com:5000/test/base-common   latest              b8e35fab763f        2 hours ago         769.9 MB
my-common                                     latest              b8e35fab763f        2 hours ago         769.9 MB

$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
$

$ docker info
Containers: 0
Images: 13
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 13
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 8
Total Memory: 62.92 GiB
Name: eapm-lnx-13
ID: 3UHB:YOQN:SFHQ:NXOF:HCQF:SE3T:UKYI:KU23:USZL:MBUG:KYKN:EPFH
$

$ uname -a
Linux eapm-lnx-13 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$

**Comment by thaJeztah** [comment]
Can you;

- Check the daemon logs (preferably when running the daemon in "debug" mode (`-D`)
- Provide more information about your registry setup (version, are you using a nginx proxy, authentication, etc)

**Comment by dmcgowan** [comment]
This issue has been fixed in master. However there are no immediate plans to implement a fix for 1.9.x. This was fixed during the large image/layer refactor. @thaJeztah not sure if you want to keep this one open until 1.10 is released.

**Comment by thaJeztah** [comment]
@dmcgowan this one, I guess? https://github.com/docker/docker/pull/17924

@liang-bin would `grep` solve your case as a workaround until 1.10 is released?

**Comment by dmcgowan** [comment]
Yes #17924, I discovered the same thing last week with 1.9.0 then noticed we fixed it with that change.

**Comment by thaJeztah** [comment]
@liang-bin I'll close this issue; it will be fixed in 1.10. Unfortunately, the changes in https://github.com/docker/docker/pull/17924 are too big to include in a patch release (if we decide to release one). Apologies for the inconvenience. Feel free to comment here after I've closed this issue!
