### ISSUE TITLE
Unable to connect to docker after Win10 Nov Upgrade

### ISSUE THREAD

**Issue by GritBear** [docker/docker#18738]
I have tried for a few hours but still couldn't find the resolution to my issue. Thus I'm hoping someone from the docker team could lend some help.

I'm running default docker on Windows inside Virtualbox VM. I have upgraded to 1.9.1

When I try docker ps on "Quick Start terminal", I got the following info: 
```
An error occurred trying to connect: Get http://localhost:2375/v1.21/containers/
json: dial tcp 127.0.0.1:2375: ConnectEx tcp: No connection could be made becaus
e the target machine actively refused it.
```
Note I could still start my container directly in virtual machine cmd. But docker ps in virtual machine gives empty results. So I assume somehow the physical docker images are still there, just the connection to docker service is lost?

Running docker version, I got:
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      windows/amd64
An error occurred trying to connect: Get http://localhost:2375/v1.21/version: di
al tcp 127.0.0.1:2375: ConnectEx tcp: No connection could be made because the ta
rget machine actively refused it.
```

I tried the set env suggestion: http://stackoverflow.com/questions/32047660/docker-for-windows-not-working but I couldn't open docker-machine env default because of the following error:
```
Error checking TLS connection: Error checking and/or regenerating the certs: There was an error validating certificates
for host "192.168.56.101:2376": dial tcp 192.168.56.101:2376: i/o timeout
```
After running the regen-cert as suggested, I got another error:

```
SSH for the machine should still work, but connecting to exposed ports, such as
the Docker daemon port (usually <ip>:2376), may not work properly.

You may need to add the route manually, or use another related workaround.

This could be due to a VPN, proxy, or host file configuration issue.
```

Now I'm stuck. What is this "VPN, proxy, or host file configuration issue"? Everything is fine until my windows 10 auto Nov upgrade yesterday.

Help appreciated!

**Comment by sb84** [comment]
@GritBear did you resolve this problem? i have the same ;|

**Comment by thaJeztah** [comment]
Since this is an issue with docker machine or docker toolbox, I think this should be opened in that issue tracker; https://github.com/docker/toolbox/issues.

There may already be an open issue for this, for example: https://github.com/docker/toolbox/issues/268, or others: https://github.com/docker/toolbox/issues?utf8=✓&q=is%3Aissue+is%3Aopen+refused

I'll close this issue here, because this is not an issue with docker ("engine"), but with docker machine or toolbox. Feel free to comment here after I've close though :smile:
