### ISSUE TITLE
Docker ignoring defaults file

### ISSUE THREAD

**Issue by jakobmaier** [docker/docker#18746]
I have a fresh XUbuntu 15.04 installation and Docker 1.9.1 installation.

I added the following line into /etc/defaults/docker:
`DOCKER_OPTS="--registry-mirror=http://docker.myComp.com:5000  --insecure-registry=docker.myComp.com"`

However, when pulling docker images, it tries to use https and fails.

**Starting the docker daemon:**
    sudo docker --insecure-registry=docker.myComp.com:5000 --registry-mirror=http://docker.myComp.com -dD

**Pulling images:**
$ sudo docker pull docker.myComp.com/tools
Using default tag: latest
Error response from daemon: unable to ping registry endpoint https://docker.myComp.com/v0/
v2 ping attempt failed with error: Get https://docker.myComp.com/v2/: dial tcp 192.168.0.1:443: connection refused
 v1 ping attempt failed with error: Get https://docker.myComp.com/v1/_ping: dial tcp 192.168.0.1:443: connection refused

**Daemon output:**
INFO[0004] POST /v1.21/images/create?fromImage=docker.myComp.com%2Ftools%3Alatest 
DEBU[0004] hostDir: /etc/docker/certs.d/docker.myComp.com 
DEBU[0004] hostDir: /etc/docker/certs.d/docker.myComp.com 
DEBU[0004] Trying to pull docker.myComp.com/tools from https://docker.myComp.com v2 
WARN[0005] Error getting v2 registry: Get https://docker.myComp.com/v2/: dial tcp 192.168.0.1:443: connection refused 
DEBU[0005] Trying to pull docker.myComp.com/tools from https://docker.myComp.com v1 
DEBU[0005] hostDir: /etc/docker/certs.d/docker.myComp.com 
DEBU[0005] attempting v2 ping for registry endpoint https://docker.myComp.com/v2/ 
DEBU[0006] attempting v1 ping for registry endpoint https://docker.myComp.com/v1/ 
DEBU[0007] Fallback from error: unable to ping registry endpoint https://docker.myComp.com/v0/
v2 ping attempt failed with error: Get https://docker.myComp.com/v2/: dial tcp 192.168..0.1:443: connection refused
 v1 ping attempt failed with error: Get https://docker.myComp.com/v1/_ping: dial tcp 192.168.0.1:443: connection refused 
ERRO[0007] Handler for POST /v1.21/images/create returned error: unable to ping registry endpoint

**Comment by jakobmaier** [comment]
Update: This issue is invalid. The changes had to be added to `/etc/systemd/system/multi-user.target.wants/docker.service`

**Comment by thaJeztah** [comment]
@jakobmaier check this part of the documentation, which describes using drop-ins for configuring the docker service on systemd https://docs.docker.com/engine/articles/systemd/#custom-docker-daemon-options
