### ISSUE TITLE
pkg/version.Version: use the new String() method

### ISSUE THREAD

**Issue by runcom** [docker/docker#18750]
https://github.com/docker/docker/pull/18745 added a new `String()` method to the `Version` type found under `pkg/version`. Before that we used to cast to string when we actually needed a string out of `Version`. Would be good to find and replace all occurrences where we were casting to string and convert them to using the new `.String()` method

**Comment by aditirajagopal** [comment]
#dibs?

**Comment by runcom** [comment]
as an example this https://github.com/docker/docker/blob/master/api/client/cli.go#L106 should become `api.DefaultVersion.String()`
