### ISSUE TITLE
Semantic versioning for image tags

### ISSUE THREAD

**Issue by mcandre** [docker/docker#18755]
I currently, laboriously create tag aliases for my images, to create semantically versioned tag names, so that users can refer to the major (1), minor (1.2), or patch (1.2.3) version, all pointing to the same image. But it would be easier if Docker tags simply offered a semantic versioning syntax, like package managers tend to offer (e.g. `name ~= major[.minor]`).

Could Docker tags get a similar syntax for convenience?

**Comment by thaJeztah** [comment]
No, I don't think that would be possible; tags in docker don't dictate how they should be used, that's completely up to the maintainer of a repository, i.e. `foobar:purple` and `foobar:gold` are just as valid as `foobar:1.2.almost-latest`.

I think the best approach for your use case is the way you're using it now, i.e., update the "latest", major, minor, and patch tags when a patch release is pushed.

Also see this discussion in the distribution repository; https://github.com/docker/distribution/pull/1202

**Comment by LK4D4** [comment]
Yeah, it's too late now :/
