### ISSUE TITLE
Send request to docker repository, and error occurs

### ISSUE THREAD

**Issue by drngsl** [docker/docker#18760]
Hi.
I reinstalled docker on the host. when I executed cmd docker search mongo.
response was printed like this:
Error response from daemon: Get https://index.docker.io/v1/search?q=mongo: malformed HTTP status code "...</h1>"

and docker daemon printed:
INFO[0108] GET /v1.21/images/search?term=mongo          
ERRO[0108] Handler for GET /v1.21/images/search returned error: Get https://index.docker.io/v1/search?q=mongo: malformed HTTP status code "...</h1>" 
ERRO[0108] HTTP Error                                    err=Get https://index.docker.io/v1/search?q=mongo: malformed HTTP status code "...</h1>" statusCode=50
So, why does this error occur?

docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

**Comment by dmcgowan** [comment]
Is this problem persisting and do you have anything in your network such a proxy that may be interfering with your connection to the registry?
