### ISSUE TITLE
IPv6 routing permits corrupt data to be delivered to applications (veth driver bug)

### ISSUE THREAD

**Issue by evanj** [docker/docker#18776]
veth devices mark all packets as "checksums known good." This is wrong if packets came from hardware. If corrupt packets are routed from "real" devices to veth devices, like Docker does for IPv6, applications can receive corrupt data. Docker's standard IPv4 configurations, which use NAT to route packets, are not affected by this.

*Workaround*: Docker should be disabling rx checksum offloading on veth devices inside containers to avoid this bug, for all configurations. Even if typical IPv4 configurations are not affected, since many people use Docker containers with other networking configurations, this will protect all of them.

We were affected by this bug at Twitter, so I've been searching the Internet to determine what else is affected. More Details are in this Kubernetes bug report (which is also affected).

Kubernetes bug: https://github.com/kubernetes/kubernetes/issues/18898
Mesos bug: https://issues.apache.org/jira/browse/MESOS-4105
Linux kernel patch: http://thread.gmane.org/gmane.linux.kernel/2111961

**Comment by evanj** [comment]
I'm copying the detailed description I had originally posted on the (Kubernetes bug)[https://github.com/kubernetes/kubernetes/issues/18898], since I believe this is actually the right place to add the workaround, so the maximum number of users get it.


*Summary*: when packets are routed from hardware to a veth device (as Docker does with IPv6), the veth device marks them as "checksum good". If those packets are corrupt, applications inside containers will receive corrupt data, instead of discarding them.

This is caused a [bug in the Linux kernel we are trying to get patched](http://thread.gmane.org/gmane.linux.kernel/2111961). We were [impacted by this bug at Twitter, on Mesos](https://issues.apache.org/jira/browse/MESOS-4105). In investigating it, we discovered that Docker is also affected. 

*Workaround*: Docker should disable rx checksum offloading on veth devices by invoking `ethtool -K eth0 rx off` on the container side of the veth when creating containers.

How to reproduce the bug on Google Container Engine:

1. Create a new cluster using Google Container Engine.
2. Create a container running something, so it gets its own IP address.
3. Connect to the container's host, and run netcat inside the new container: `docker exec -ti (container id) nc -l -p 12345`
4. Start a separate virtual machine in Google Compute Engine.
5. Copy my tcpping tool to the virtual machine: https://gist.github.com/evanj/4329312f5e27fd34ba90
6. On the new VM, run `./tcpping (container ip):12345`
7. You should see a sequence of "aaaaa 0", "aaaaa 1" etc.
8. On the VM, start corrupting all packets for 10 seconds with: `sudo tc qdisc add dev eth0 root netem corrupt 100%; sleep 10; sudo tc qdisc del dev eth0 root netem`
9. You should now see a sequence of messages with corruption appear for 10 seconds.
10. Turn of rx checksumming with `docker exec -ti (container id) ethtool -K rx off`
11. Repeat the experiment, you should now see the messages "pause" until the corruption is turned off, at which point the entire batch of messages will appear at once after they are retransmitted.

**Comment by thaJeztah** [comment]
Thanks for reporting!

ping @mrjana @mavenugo @aboch

**Comment by thockin** [comment]
It sounds like a net negative if you actually have offloading that works, so maybe we can detect that it is broken by kernel version or something?
￼

**Comment by evanj** [comment]
"turning off" checksumming is a misleading statement. It doesn't actually change how the veth device does or does not do checksums. Turning off the "rx checksum offloading" only has the effect of avoiding this bug. The kernel patch that we submitted (and may be getting accepted?) effectively just [removes the if statement and code](https://github.com/torvalds/linux/blob/v4.1/drivers/net/veth.c#L120), so I'm pretty sure this is harmless. If your actual Ethernet hardware checks the packets, it will not re-check them. It will only cause the kernel to re-check packets that the hardware marked as suspicious.

If you turn of the *tx checksum offloading* then the kernel will compute the checksums in software, which is bad. So don't do that. :) At Twitter we've effectively deployed this across our entire fleet of machines and saw zero impact.

**Comment by evanj** [comment]
Our kernel patch has been backported into most stable branches: 3.10, 3.14, 4.1, 4.3. However, this bug will still exist until everyone upgrades their kernel. I would love it if someone who understands Docker networking could add a "ethrool -K eth0 rx off" when creating the veth for a new Docker container, since network corruption is very bad and in my experience, old kernels will stick around for at least a year.

http://git.kernel.org/cgit/linux/kernel/git/stable/stable-queue.git/commit/?id=873de20d92e36d56d0b2919231621fe74759fcc0

**Comment by thaJeztah** [comment]
ping @mavenugo @mrjana can you have a look at this?

**Comment by vijayp** [comment]
I've posted an article with a more detailed description of the problem and solution here: 

[https://medium.com/vijay-pandurangan/linux-kernel-bug-delivers-corrupt-tcp-ip-data-to-mesos-kubernetes-docker-containers-4986f88f7a19#.ry24np4bc]

It really would be great to get the workaround into docker if possible.

**Comment by jonathanstiansen** [comment]
@mavenugo @mrjana Did either of you guys get a chance to look at this? @thaJeztah had pinged a few months ago it's still an issue I believe, anyways thanks for all you do either way!

**Comment by evanj** [comment]
FWIW: The kernel patch to address this issue has been backported into the stable kernel, so there may be nothing to be done here. Eventually people will upgrade their kernel, or they might receive corrupt packets. I suggest just closing this and recommending people use the latest stable kernel they can.

**Comment by AkihiroSuda** [comment]
+1 @evanj, I suggest closing this issue

**Comment by thaJeztah** [comment]
Agreed; closing this
