### ISSUE TITLE
Pasting commands to terminal doesn't work

### ISSUE THREAD

**Issue by kolodny** [docker/docker#18772]
For example if I paste the following in the terminal:

```
docker-machine ssh default 'echo test1'
echo test2
echo test3
```

I'll only get `test1` printed:

```
$ docker-machine ssh default 'echo test1'
echo test2
echo test3
test1
$
```

consider the expected behavior:

```
sleep 4
echo test1
echo test2
```

result:

```
$ sleep 4
echo test1
echo test2
$ echo test1
test1
$ echo test2
test2
$
```

**Comment by cpuguy83** [comment]
This is the correct behavior because you have quotes around `echo test`
Also, please note the repo for machine is github.com/docker/machine.

Thanks!

**Comment by kolodny** [comment]
hmm still seems to be an issue w/o the quotes, I'll open an issue there when I get a chance

**Comment by cpuguy83** [comment]
@kolodny Sorry, I didn't explain exactly correctly.
You would need to specify the commands as you normally would with shell (or really, this is the same exact behavior of the SSH command).
docker-machine ssh default 'echo 1; echo 2; echo 3'

**Comment by kolodny** [comment]
No, I mean to be able to copy paste a script into the terminal and have it run normally, for example I would do something like:

```
docker rm $(docker ps -aq)
./script-to-generate-new-containers.sh
```

**Comment by cpuguy83** [comment]
@kolodny In such a case you'd need to wrap the whole command you want to pass as quotes.
