### ISSUE TITLE
Instructions for Docker Remote API access with docker-machine out of date

### ISSUE THREAD

**Issue by dalanmiller** [docker/docker#18778]
https://github.com/docker/docker/blob/0f749ad55ab794872e601b4f665b07c0be07abfc/docs/reference/api/docker_remote_api.md#using-docker-machine-with-the-api

Specifically the instructions here. I'm not sure which `cert.pem` and `key.pem` to use within my `~/.docker` folder. As none exist now in the directory shown in the example. 

`docker version`
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   a34a1d5
 Built:        Sat Nov 21 00:49:19 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:08:59 UTC 2015
 OS/Arch:      linux/amd64
```
`docker info`
```
Containers: 807
Images: 355
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1972
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.8.0-36-generic
Operating System: Ubuntu precise (12.04.4 LTS)
CPUs: 12
Total Memory: 5.82 GiB
Name: puzzler
ID: E2HH:TBNA:D37W:M7GD:M6ZU:6PML:GUSE:YEYY:FMLM:ZE2U:HRAN:ENN7
Labels:
 provider=generic
```
`uname -a`
```
Darwin dalanmiller.local 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64
```

**Comment by MHBauer** [comment]
On a per-machine basis, the certs are at `~/.docker/machine/machines/${MACHINE-NAME}` for me.

I need to check if that is documented somewhere. Either way the docs need an update specific to machine. Maybe it would be better to have this info in the machine docs, and have a link.

**Comment by thaJeztah** [comment]
Hm, yes, looks like this section was updated with the new paths for docker-machine https://github.com/docker/docker/blob/master/docs/installation/windows.md#login-with-putty-instead-of-using-the-cmd, but not the API docs.

If you're interested, please open a pull request to fix the example for people that use docker-machine

**Comment by aditirajagopal** [comment]
#dibs

**Comment by dalanmiller** [comment]
May the best PR win! :joy_cat:

**Comment by aditirajagopal** [comment]
@MHBauer said I could work on this!!! I cleared it with him first! :c
