### ISSUE TITLE
inconsistencies in /etc/hosts container discovery

### ISSUE THREAD

**Issue by vieux** [docker/docker#18784]
There are some inconsistencies in the way `/etc/hosts` is populated by libnetwork,
let's star 2 containers with a name & an hostname and look at `/etc/hosts` in the 2nd one:

```
$ docker run --net test -d --name name1 --hostname hostname1 busybox ping google.com
eeaa5f3439203738a517aef3bdcde532cb745c4bfb2e2730c5e4a9a7c104fe2e

$ docker run --net test -d --name name2 --hostname hostname2 busybox ping google.com
8455e8b83f73d128d087425a08ffbf27075b4001e17a3905d19fecb542127874

 $ docker exec -it 8455e8b83f73d128d087425a08ffbf27075b4001e17a3905d19fecb542127874 cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.18.0.3	hostname2
172.18.0.2	name1
172.18.0.2	name1.test
```

We see the container sees itself via hostname but see other containers via their name.

I think it should change it to something like:

```
127.0.0.1	localhost hostname2
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.18.0.3	name2
172.18.0.3	name2.test
172.18.0.2	name1
172.18.0.2	name1.test
```

ping @mavenugo @mrjana 
/cc @mgoelzer

**Comment by vieux** [comment]
@GordonTheTurtle I hate you

**Comment by engine07** [comment]
shouldn't values in hosts file reference docker container hostnames ?

**Comment by mgoelzer** [comment]
I think @vieux is right:  it should be one or the other or both, but not inconsistent between self and other.  Basically, if all your containers are on the same network and were started the same way (with a --hostname arg) you should identical /etc/hosts inside each container, no?

**Comment by thaJeztah** [comment]
ping @mavenugo could you have a look at this?

**Comment by sanimej** [comment]
@thaJeztah @vieux With the transition to DNS based name resolution in 1.10 /etc/hosts is not updated for user defined networks and it is possible to resolve the self name from the same container.. 

vagrant@net-1:~$ docker exec name1 ping name1
PING name1 (172.23.0.2): 56 data bytes
64 bytes from 172.23.0.2: seq=0 ttl=64 time=0.014 ms
64 bytes from 172.23.0.2: seq=1 ttl=64 time=0.111 ms

I think we can close this issue.

**Comment by thaJeztah** [comment]
@sanimej doh! didn't pay attention :relaxed: . Closing.
