### ISSUE TITLE
issue with docker overlay multihost network

### ISSUE THREAD

**Issue by mazembo** [docker/docker#18783]
I have been trying to create an overlay network between two hosts with no success. I keep getting the error message: 
mavungu@mavungu-Aspire-5250:~$ sudo docker -H tcp://192.168.0.18:2380 network create -d overlay myapp
Error response from daemon: 500 Internal Server Error: failed to parse pool request for address space "GlobalDefault" pool "" subpool "": cannot find address space GlobalDefault (most likely the backing datastore is not configured)

mavungu@mavungu-Aspire-5250:~$ sudo docker network create -d overlay myapp
[sudo] password for mavungu: 
Error response from daemon: failed to parse pool request for address space "GlobalDefault" pool "" subpool "": cannot find address space GlobalDefault (most likely the backing datastore is not configured)

My environment details: 
mavungu@mavungu-Aspire-5250:~$ sudo docker info
Containers: 1
Images: 364
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 368
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-26-generic
Operating System: Ubuntu 15.04
CPUs: 2
Total Memory: 3.593 GiB
Name: mavungu-Aspire-5250
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

I have a swarm cluster working well with consul as the discovery mechanism: 

mavungu@mavungu-Aspire-5250:~$ sudo docker -H tcp://192.168.0.18:2380 info
Containers: 4
Images: 51
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 2
 mavungu-Aspire-5250: 192.168.0.36:2375
  └ Containers: 1
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 3.773 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.19.0-26-generic, operatingsystem=Ubuntu 15.04, storagedriver=aufs
 mavungu-HP-Pavilion-15-Notebook-PC: 192.168.0.18:2375
  └ Containers: 3
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 3.942 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.2.0-19-generic, operatingsystem=Ubuntu 15.10, storagedriver=aufs
CPUs: 6
Total Memory: 7.715 GiB
Name: bb47f4e57436

My consul is available at 192.168.0.18:8500 and it works well with the swarm cluster. 

I would like to be able to create an overlay network across the two hosts. I have configured the docker engines on both hosts with this additional settings: 
DOCKER_OPTS="-D --cluster-store-consul://192.168.0.18:8500 --cluster-advertise=192.168.0.18:0"
DOCKER_OPTS="-D --cluster-store-consul://192.168.0.18:8500 --cluster-advertise=192.168.0.36:0"
I had to stop and restart the engines and reset the swarm cluster...
After failing to create the overlay network, I changed the --cluster-advertise setting to this : 

DOCKER_OPTS="-D --cluster-store-consul://192.168.0.18:8500 --cluster-advertise=192.168.0.18:2375"
DOCKER_OPTS="-D --cluster-store-consul://192.168.0.18:8500 --cluster-advertise=192.168.0.36:2375"

But still it did not work. I am not sure of what ip:port should be set for the --cluster-advertise= . Docs, discussions and tutorials are not clear on this advertise thing. 

There is something that I am getting wrong here. Please help.

**Comment by mazembo** [comment]
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:16:54 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:16:54 UTC 2015
 OS/Arch:      linux/amd64

Containers: 1
Images: 364
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 368
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-41-generic
Operating System: Ubuntu 15.04
CPUs: 2
Total Memory: 3.593 GiB
Name: mavungu-Aspire-5250
ID: 6MUZ:QTM5:GEHK:KQF5:4GUD:BQVX:NKCM:XH4M:6ESI:BGB7:6PYS:AEJY
Username: mazembo
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

avungu@mavungu-Aspire-5250:~/dockertutorials$ sudo uname -a
Linux mavungu-Aspire-5250 3.19.0-41-generic #46-Ubuntu SMP Fri Dec 4 18:18:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by thaJeztah** [comment]
Where are you setting those `DOCKER_OPTS`? It looks like you're using systems running on systemd, and `DOCKER_OPTS` (In `/etc/default/docker`) is not used by those systems. Read the section on how to configure systemd using drop-ins here; https://docs.docker.com/engine/articles/systemd/#custom-docker-daemon-options

Not sure if that's your issue, but may be worth checking

**Comment by SydOps** [comment]
+1

I got same error when create a network overlay via docker-compose

```
networks:
  myapp:
```

**Comment by SydOps** [comment]
may relate with this https://github.com/docker/docker/issues/19453

**Comment by anentropic** [comment]
I had a consul server node for my swarm cluster

I wanted to run a couple of other services on it so decided to use docker-compose...

hit this error... #19453 (don't specify any overlay network) was the answer for me :)

**Comment by igorspasic** [comment]
Having the same error.

I have multihost overlay network that works on consul.

```
> docker network create -d overlay joe
Error response from daemon: failed to parse pool request for address space "GlobalDefault" pool "" subpool "": cannot find address space GlobalDefault (most likely the backing datastore is not configured)
```

**Comment by matthub** [comment]
For me the issue was that on a single node I missed to specify the `--cluster-advertise=...` and `--cluster-store=...` parameters within the `DOCKER_OPTS` in `/etc/default/docker`

**Comment by demohi** [comment]
@igorspasic 
```
$ vi /etc/default/docker
```
make sure DOCKER_OPTS  include --cluster-store  --cluster-advertise

restart docker

**Comment by igorspasic** [comment]
Thanx @demohi and @matthub 
It looks i was executing this on master machine, not on a node machine.

**Comment by dixudx** [comment]
Docker Engine supports **multi-host networking** out-of-the-box through the `overlay` network driver. Unlike `bridge` networks, `overlay` networks require some pre-existing conditions before you can create one.

Guys, you can refer to [this guide on multi-host networking](https://docs.docker.com/engine/userguide/networking/get-started-overlay/) and issue #17932 for more information .

**Comment by cpuguy83** [comment]
Closing since this looks like a configuration issue.

You must supply `--cluster-store` and `--cluster-advertise` to the docker daemon for overlay networks to work.

**Comment by yoshiwaan** [comment]
Just to drill this home for future dummies like me that see this thread and don't read it properly.

1. The overlay driver doesn't work out of the box
2. You need to set up a shared KV store first, such as Consul
3. You need to configure the Docker daemon's on each node of your cluster to point to that KV store using the flags in the post above
