### ISSUE TITLE
Provide a way to lock down specific files/folders in an image to avoid undesired overrides

### ISSUE THREAD

**Issue by brunoborges** [docker/docker#18812]
It should be possible for image authors to lock some files/folders in a way that these can't be modified by inherited images. For example:

```
FROM somelinux
RUN mkdir /mysoftware
WORKDIR /mysoftware
COPY mysoftware.tar.gz ./
COPY script.sh ./
ENTRYPOINT sh /mysoftware/script.sh
CMD ["bash"]
```

In the sample above, a user can extend this image and modify the contents of /mysoftware.

```
FROM imageabove
RUN do-whatever-with-mysoftware-contents-like-overriding-scripts.sh
ENTRYPOINT by-pass-entrypoint-of-image-above.sh
CMD ["bash"]
```

One may say this feature request is solved by [Docker Content Trust](https://blog.docker.com/2015/08/content-trust-docker-1-8/), but in reality not only the source of the image must be guaranteed, but also the image content must be secured that if someone wants to extend it, must do it so in a way that some files/folders (chosen by the image author) can't be modified.

The image author must be allowed to define what can be modified and what can't.

**Comment by vdemeester** [comment]
@brunoborges technically, what about the user running the image (as root) and overriding the file ? How would you limit root (inside the container) to do something inside the container ? How would you do that whatever the host (apparmor or not, seccomp or not, …) ?

**Comment by calavera** [comment]
After discussing it with several maintainers, we've decided to not implement this feature.

Thanks for taking your time to write it. It's always good to hear from the community.
