### ISSUE TITLE
unable to start docker with its ID in ubuntu 3.14.57 kernel after kernel code modification.

### ISSUE THREAD

**Issue by SangeethaBusangari** [docker/docker#18819]
docker start 4979a1c62ead
Error response from daemon: Cannot start container 4979a1c62ead: [8] System error: failed to add interface vethcd85712 to sandbox: failed in prefunc: failed to set namespace on link "vethcd85712": invalid argument
Error: failed to start containers: [4979a1c62ead]
previously it used to allow to start and attach containers. after appending code in  kernel to access PWD code. it got stuck. system hangs...
docker version:
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Docker info:
Containers: 16
Images: 88
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-8:1-2490369-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 8.842 GB
 Data Space Total: 107.4 GB
 Data Space Available: 80.91 GB
 Metadata Space Used: 10.61 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.137 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.14.57
Operating System: Ubuntu 14.04.3 LTS
CPUs: 2
Total Memory: 1.946 GiB
Name: sangeetha
ID: X3FI:RZFP:DOXZ:2ZZC:YG52:UFXS:QWSZ:FWH4:NGCA:HTMD:IVMN:H37H
Username: busangarisangeetha
Registry: https://index.docker.io/v1/

uname  -a
Linux sangeetha 3.14.57 #36 SMP Mon Dec 21 12:34:54 IST 2015 x86_64 x86_64 x86_64 GNU/Linux
 
List the steps to reproduce the issue:
1. executed path_get and d_path by creating kernel memory to retrieve the current working directory.
2.after reboot, trying to start docker start image-id. it displayed 
docker start 4979a1c62ead
Error response from daemon: Cannot start container 4979a1c62ead: [8] System error: failed to add interface vethcd85712 to sandbox: failed in prefunc: failed to set namespace on link "vethcd85712": invalid argument.
3. system hangs... just restarted!

Describe the results you expected:
1. start and attach docker ubuntu image.
2. get the process pwd of docker in host machine.

Additional information: i checked after kfree(buf) after getting pwd, and cleaning dmesg ring as well. still same issue.

**Comment by thaJeztah** [comment]
Looks like you're running a custom kernel, as Ubuntu 14.04.3 comes with kernel 3.19; We don't really support that, so I'm not sure this is something we should look into.
