### ISSUE TITLE
containers do not restart after reboot when bound to virtual network interface

### ISSUE THREAD

**Issue by albers** [docker/docker#18826]
The restart policies `always` and `unless-stopped` do not work as expected for containers that have ports published on virtual interfaces if the host gets rebooted:

I have an Ubuntu 14.04 with a virtual interface added in `/etc/network/interfaces`:

```
auto eth0
iface eth0 inet static
        address 10.0.1.49
        netmask 255.255.0.0
        network 10.0.0.0
        broadcast 10.0.255.255
        gateway 10.0.0.1
        dns-nameservers 8.8.8.8 8.8.4.4

auto eth0:0
iface eth0:0 inet static
        address 10.0.81.0
        netmask 255.255.0.0
        broadcast 10.0.255.255
```

If I start a container with a port published on the "real" host IP, the container will restart after reboot:

```
$docker run -d -p 10.0.1.49:80:80 --restart unless-stopped nginx
```

But if I do the same using a virtual network interface IP, the container will not come up after a reboot:

```
$docker run -d -p 10.0.81.0:80:80 --restart unless-stopped nginx
65e2f7f16bfee320bd86b015897cdc62b16377fcaf08171439748e44136c8940
$sudo reboot
[...]
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                       PORTS               NAMES
65e2f7f16bfe        nginx               "nginx -g 'daemon off"   6 minutes ago       Exited (128) 4 minutes ago                       backstabbing_keller

# in docker.log
ERRO[0000] Failed to start container 65e2f7f16bfee320bd86b015897cdc62b16377fcaf08171439748e44136c8940: failed to create endpoint backstabbing_keller on network bridge: Error starting userland proxy: listen tcp 10.0.81.0:80: bind: cannot assign requested address
```

This happens with the restart policies `always` and `unless-stopped`.
Note that the containers do come up after restarting the docker daemon but not after rebooting the host.

My environment:

```
$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
```

```
$ docker info
Containers: 1
Images: 12
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 14
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-71-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 8
Total Memory: 3.858 GiB
Name: docker2
ID: 4AHB:OT2I:Z232:YHIQ:RSVQ:PX3O:57GF:N72P:A2AE:Z2JR:MBNQ:RHPX
Debug mode (server): true
 File Descriptors: 13
 Goroutines: 20
 System Time: 2015-12-21T15:46:07.8196672+01:00
 EventsListeners: 0
 Init SHA1: 4fc7c03a06c675f115b39958c13486d53df10a14
 Init Path: /usr/lib/docker/dockerinit
 Docker Root Dir: /var/lib/docker
Username: albers
Registry: https://index.docker.io/v1/
```

```
$ uname -a
Linux docker2 3.13.0-71-generic #114-Ubuntu SMP Tue Dec 1 02:34:22 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by albers** [comment]
I forgot to mention that this is not a new issue. It's been bothering me for several versions.

**Comment by thaJeztah** [comment]
guess I should ping some of the network maintainers :smile:

ping @aboch @mavenugo @mrjana

**Comment by albers** [comment]
@icecrime This is still an issue with 1.11.1

**Comment by albers** [comment]
Looking a the error status, I get the impression that it's a timing issue. Mabye Docker configures networking before the virutal interfaces are up.

    # docker inspect -f '{{ .State.Error }}' webproxy2_nginx_1
    driver failed programming external connectivity on endpoint webproxy2_nginx_1 (d73b07e934d84f9ac61cad8c0b336cbb22b43951d9479f9ab92b8c994839420e): Error starting userland proxy: listen tcp 10.10.12.1:443: bind: cannot assign requested address

**Comment by thaJeztah** [comment]
ping @aboch @mavenugo ptal

@albers the "version/xx" labels were added automatically using a script, but @icecrime's account was used to set them the first time :smile:

**Comment by albers** [comment]
:bulb:

**Comment by flaviohrocha** [comment]
This issue also applies to version 1.12? I had this problem in my environment:

$ docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

**Comment by mentalMedley** [comment]
I had same problem. In my case it was a collision with NetworkManager.service (i use Debian stretch).
Because of NetworkManager replaces /etc/resolv.conf with link to /var/run/NetworkManager/resolv.conf in same moment when Docker searches this file, containers with virtual networks can't be started.
To solve problem:
1) Copy /lib/systemd/system/docker.service to /etc/systemd/system/docker.service
2) Open copied file in editor as root and replace
`After=network.target docker.socket`
to
`After=network-online.target docker.socket`
3) And reboot.
So Docker will be started after NetworkManager service finished.

P.S.: Thanks Docker developers for your awesome product. It helps me a lot! :-)

**Comment by thaJeztah** [comment]
@mentalMedley are there any side effects to that change, or would it be a change that could be included in the default unit file that docker uses? Otherwise it could me used as default; https://github.com/docker/docker/tree/master/contrib/init/systemd

**Comment by mentalMedley** [comment]
@thaJeztah I proposed the solution after reading [this document](https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/). I think the default unit file must be changed.

**Comment by thaJeztah** [comment]
@mentalMedley makes sense. Would you be interested in opening a pull request for that change? We should probably double-check if it's supported by all versions of systemd (we've run into that at some times)

**Comment by albers** [comment]
Sadly, the fix proposed in #29727 does not work for me (Docker 1.12.6 on Ubuntu 14.04). I still get

    Error starting userland proxy: listen tcp 10.0.81.1:80: bind: cannot assign requested address

Here's what I did to check:
```bash
# modified "After", added "Wants"
$ sudo head -6 /lib/systemd/system/docker.service
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network-online.target docker.socket firewalld.service
Wants=network-online.target
Requires=docker.socket

# 10.0.81.1 is a virtual interface
$ ifconfig eth0:1
eth0:1    Link encap:Ethernet  HWaddr 00:0c:29:70:4f:3f
          inet addr:10.0.81.1  Bcast:10.0.255.255  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

$ docker run -d -p 10.0.81.1:80:80 --restart unless-stopped --name web nginx
e74288dba51a464732980de0e4357f086dd367080ba8234009cae162684b050f
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                           NAMES
e74288dba51a        nginx               "nginx -g 'daemon off"   8 seconds ago       Up 7 seconds        10.0.81.1:80->80/tcp, 443/tcp   web
$ sudo reboot
[...]
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS                        PORTS               NAMES
e74288dba51a        nginx               "nginx -g 'daemon off"   About a minute ago   Exited (128) 41 seconds ago                       web
$ docker inspect --format '{{.State.Error}}' web
driver failed programming external connectivity on endpoint web (ae57cdd420192ce140ab470efc526638ee366f1ddf9f209df4b703d1075a3c36): Error starting userland proxy: listen tcp 10.0.81.1:80: bind: cannot assign requested address
```

@mentalMedley Did I apply your solution correctly?

**Comment by mentalMedley** [comment]
@albers Yes, all correct. Hard to say why you get error. May be because of network-online target is reached when at least one interface is up or virtual interfaces have no effect on network-online target.

**Comment by albers** [comment]
@mentalMedley Did you use virtual interfaces? If not, can you please verify if startup works with virtual interfaces on your box?

**Comment by mentalMedley** [comment]
@albers I tested with your config
```
auto enp3s0f1
iface enp3s0f1 inet static
        address 10.0.1.49
        netmask 255.255.0.0
        network 10.0.0.0
        gateway 10.0.0.1
        broadcast 10.0.255.255
        dns-nameservers 8.8.8.8 8.8.4.4

auto enp3s0f1:0
iface enp3s0f1:0 inet static
        address 10.0.81.0
        netmask 255.255.0.0
        broadcast 10.0.255.255
```

and everything works well!

Check your /etc/resolv.conf. Is it file or link? In case of link try remove it and create file again with
```
echo 'nameserver 8.8.8.8' > /etc/resolv.conf
echo 'nameserver 8.8.4.4' >> /etc/resolv.conf
```
Because of I faced with trouble same as you describe.

If it does not help you then show your `journalctl -b` output.

**Comment by andrewhsu** [comment]
I have a feeling that `systemd` service changes may not have effect for docker users on Ubuntu 14.04 because it uses `upstart` by default and it doesn't look like `systemd` is really supported on 14.04: https://wiki.ubuntu.com/SystemdForUpstartUsers#Support_status

**Comment by thaJeztah** [comment]
@andrewhsu good catch; yes, changes to systemd won't make a difference for ubuntu 14.04

**Comment by albers** [comment]
@mentalMedley `/etc/resolv.conf` is a link to `../run/resolvconf/resolv.conf`.
I replaced it with a file like you suggested (using our internal nameservers).
Sadly, the problem still persists.
`journalctl` is not available on my box.

@andrewhsu, @thaJeztah Good point. I will try whether upgrading Ubuntu 16.04 (and applying your fix) resolves my issues.

**Comment by albers** [comment]
@mentalMedley I installed systemd in order to get journalctl. Here is the requested output.
(Only one container, started with `docker run -d -p 10.0.81.1:80:80 --restart unless-stopped --name web nginx`, then rebooted.)
[journal.txt](https://github.com/docker/docker/files/766355/journal.txt)

**Comment by albers** [comment]
**On Ubuntu 16.04.1 LTS, the problem does not exist.**

Looks like a timing issue related to `initd`. More specific, it seems to be specific to Ubuntu 14.04 LTS.
I migrated my production machines to Ubuntu 16.04, so this issue is no longer relevant for me.

@thaJeztah WDYT, should we keep this issue open because is not resolved or should we close it because I seem to be the only one who is affected and I'm no longer interested?

**Comment by thaJeztah** [comment]
Thanks @albers, I think we can go ahead and close for now; Ubuntu 14.04 is gonna become less used now that a new LTS is out, and I also haven't seen others report this issue.
