### ISSUE TITLE
Feature request: `docker info` should list authorization plug-ins

### ISSUE THREAD

**Issue by albers** [docker/docker#18829]
`docker info` output includes volume and network plugins, e.g.
```
Plugins:
 Volume: local
 Network: null host bridge
```
For consistency (and for use in bash completion :wink:) it should also contain the installed authorization plug-ins.

Ref #15365, #18649

**Comment by vdemeester** [comment]
if nobody's working on it, #dibs :smile_cat:

**Comment by runcom** [comment]
+1

**Comment by runcom** [comment]
Ha, I deserve that :)

**Comment by thaJeztah** [comment]
LOL

**Comment by albers** [comment]
@vdemeester Thanks, Vincent for taking care of that.
