### ISSUE TITLE
Docker commit never finishes and fills disk

### ISSUE THREAD

**Issue by williamsbdev** [docker/docker#18849]
I am attempting to commit a docker container id and in the process of doing so, seeing that it never finishes and continues to fill disk space taking roughly 1 GB every 3 seconds.

I am running Ubuntu 15.10.

docker version:
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:48:04 UTC 2015
 OS/Arch:      linux/amd64

docker info:
Containers: 21
Images: 394
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 447
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-15-generic
Operating System: Ubuntu 15.10
CPUs: 8
Total Memory: 31.36 GiB
Name: my_machine_name
ID: CRO3:UP2J:LX2Z:PVD6:FI64:RTTP:PVDA:BYAW:JYIE:MCUI:OBY5:7KKV
WARNING: No swap limit support

uname -a:
Linux my_machine_name 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

This is happening on dev machine.

This is reproducible every time I am running this docker commit. In my script I am adding a user to the docker container and then when I go to do a docker commit it will hang and slowly eat up the disk. My example it is slow since the container is smaller and shows only the basic problem, when I am doing this at work, our container is larger and seems to fill the disk much faster (at the rate of approximately 1GB/3 seconds).

Here is a link to an [example repo](https://github.com/williamsbdev/docker-commit-issue) of what we are doing to produce this issue.

Steps to Reproduce:
`git clone https://github.com/williamsbdev/docker-commit-issue`
`./build.sh`

Actual Results:
This will result in the `docker commit` command never finishing and filling the disk. In order to stop docker from consuming all available disk space, you will need to kill the docker deamon `service docker stop`.

Expected Results:
I expect this command to finish like it will if I modify the `build.sh` to remove the `/add-user.sh` from the following command:

```bash
CONTAINER_ID=`docker run -d \                                                                                                                     
    -e "EXTERNAL_USER_ID=$EUID" \                                                                                                                 
    some-docker-image \                                                                                                                           
    /add-user.sh                                                                                                                                  
`
```

**Comment by jcttrll** [comment]
It looks like the issue is the user ID--when doing a `useradd -u <uid>` inside a docker container, disk is consumed proportional to the size of `<uid>`. I've submitted a PR to https://github.com/williamsbdev/docker-commit-issue; this uses a two-line Dockerfile that does:

    FROM ubuntu:15.10
    RUN useradd -u 9999999 -m initial

This will produce a Docker image of over 3GB. Adjusting the UID will produce the following image sizes:

    UID            Image Size
    -------------  ----------
    <base-ubuntu>    0.134 GB
             9999    0.137 GB
            99999    0.166 GB
           999999    0.458 GB
          9999999    3.374 GB
         99999999   32.530 GB
        999999999  324.100 GB

**Comment by thaJeztah** [comment]
I think this is a duplicate of (or related to) https://github.com/docker/docker/issues/5419, read the discussion there for more information

**Comment by williamsbdev** [comment]
@jcttrll Thank you for giving the metrics of the problem.

@thaJeztah Thank you for referencing the original issue. I was unable to find it when searching for answers. I will implement the `-l` option and close this issue.

**Comment by thaJeztah** [comment]
Thanks @williamsbdev (and @jcttrll). I hope that helps you solve your issue. And yes, it surprised me as well the first time I read about it :smile:
