### ISSUE TITLE
source IP for UDP packets is  incorrect

### ISSUE THREAD

**Issue by jabirahmed** [docker/docker#18845]
Source  host ip : 

root@-X1 [14:39:49] /Users/jabir/git/puppet/modules/rsyslog/templates> ifconfig en0
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 78:31:c1:c3:e0:be 
	inet6 fe80::7a31:c1ff:fec3:e0be%en0 prefixlen 64 scopeid 0x4 
	inet 192.168.0.105 netmask 0xffffff00 broadcast 192.168.0.255
	nd6 options=1<PERFORMNUD>
	media: autoselect
	status: active

== Docker machine settings 
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="/Users/jabir/.docker/machine/machines/dev"
export DOCKER_MACHINE_NAME="dev"

== Tcp dump of the packets being set to the port 

root@df5b6a9cd35f:/# tcpdump 'port 9090'
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 65535 bytes
09:02:02.099577 IP 192.168.99.1.52734 > df5b6a9cd35f.9090: UDP, length 5

This shows the up address of the docker-machine where as it has to show the  address of the client sending the message.

+ steps to reproduce 

$ docker run -p 9090:9090/udp  ubuntu:14.04 /bin/nc -l -u 9090

$ docker exec -it $dockerid bash 
   apt-get install tcpdump
  tcpdump "port 9090"

$ from any machine send  udp data 

echo "somedata" | nc -u  $docker_base_host 9090

**Comment by jabirahmed** [comment]
its the same behaviour when i use docker-engine instead of the docker-machine on an ubuntu host

**Comment by jabirahmed** [comment]
~> docker -v
Docker version 1.8.2, build 0a8c2e3


 ~> docker info
Containers: 45
Images: 8
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 98
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.2 (TCL 6.4); master : aba6192 - Thu Sep 10 20:58:17 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: dev
ID: 6EKT:EGB2:VQTC:FNVT:7DPS:UHYF:SKAR:XJIE:M3RY:3PSO:CVOA:TTCS
Debug mode (server): true
File Descriptors: 19
Goroutines: 32
System Time: 2015-12-22T12:34:01.890798216Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: jabirahmed
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox

 ~> uname -a
Darwin IM-X1 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64

**Comment by jabirahmed** [comment]
setting userland-proxy=false worked

**Comment by thaJeztah** [comment]
Looks like this is resolved for you, shall I close it?

**Comment by jabirahmed** [comment]
@thaJeztah  sure , should be good to go, just wondering why isn't it a default option.

**Comment by thaJeztah** [comment]
We *wanted* to make it the default, see https://github.com/docker/docker/issues/14856, but there are still some issues if it's not enabled (some are referred to in that discussion)
