### ISSUE TITLE
Add option to disable docker_gwbridge on overlay networks.

### ISSUE THREAD

**Issue by clinta** [docker/docker#18854]
Some containers do not need access to outside networks, and exist only to provide services to other containers via the overlay network. These containers should not have the docker_gwbridge interface and there should be an option to prevent them from getting it. Perhaps with a flag to `docker run` or a property that can be added to the overlay network that indicates that machines started with this network do not need the docker_gwbridge.

**Comment by aboch** [comment]
Please take a look at https://github.com/docker/libnetwork/pull/831
It will allow user to specify the network being created is internal, does not have access to external world.
Docker side changes will came next

**Comment by thaJeztah** [comment]
@aboch is that planned for 1.10? Then I can add it to the milestone

**Comment by chenchun** [comment]
Yes, the feather has been merged yesterday in libnetwork. I'd like to bring that to docker.

**Comment by alvinr** [comment]
+1 I need the ability to decide if each container is attached to the docker_gwbridge network. I'm my case the majority of the containers would not connect to this network, just the outside endpoint (e.g. haproxy).

**Comment by thaJeztah** [comment]
This feature was implemented in https://github.com/docker/docker/pull/19276, so this will be in Docker 1.10
