### ISSUE TITLE
Docker runs out of disk space even though containers are small

### ISSUE THREAD

**Issue by lenadroid** [docker/docker#18869]
Hello dear Docker team,

I have installed Docker Toolbox for Mac OSX and running several containers inside. 

```
$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```

Steps:

First two containers I created were with Cassandra and they were running fine. 
After that I've created 2 Debian containers, connected to bash through docker terminal with the purpose to install Oracle JDK8.
At the point when I was about to extract java from the tarball - I've got a ton of "Cannot write: No space left on device" error messages during the execution of "tar" command.

The df -h on the host gives the following output:

```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
none            1.8G  1.8G     0 100% /
tmpfs          1002M     0 1002M   0% /dev
tmpfs          1002M     0 1002M   0% /sys/fs/cgroup
tmpfs           1.8G  1.8G     0 100% /etc/hosts
shm              64M     0   64M   0% /dev/shm
```

I've checked the space:

    $ docker ps -s
    CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                         NAMES               SIZE
    9d8029e21918        debian:latest       "/bin/bash"              54 minutes ago      Up 54 minutes                                                     deb-2               620.5 MB (virtual 744 MB)
    49c7a0e37475        debian:latest       "/bin/bash"              55 minutes ago      Up 55 minutes                                                     deb-1               620 MB (virtual 743.5 MB)
    66a17af83ca3        cassandra           "/docker-entrypoint.s"   4 hours ago         Up 4 hours          7000-7001/tcp, 7199/tcp, 9042/tcp, 9160/tcp   node-2              40.16 MB (virtual 412.6 MB)

After seeing that output I noticed that one of my nodes with cassandra is missing. In went to check to Kitematic and found out that it is in the DOWN state and I can't start it: "Cannot write node-1. No space left on device" - error message shown for this attempt.

That container for Cassandra is called node-1, which isn't on the list. I have that container, that doesn't show up by the command "docker ps -s". It is present when I run "docker ps -a" - in the "exited" state. It is down. And I can't start it. But I do need it. I think the issue isn't in some unused containers that take space, the issue is more in the amount of space that should be increased.

Are there any limits that Docker has to run the containers?

When I remove all my cassandra ones and leave just a couple of Debian - java is able to be extracted from the tar. So the issue is definitely in some Docker settings related to sizing.

What is the correct way to resolve the issue with space limits here?

Docker images command gives the following output:

```
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
cassandra           latest              13ea610e5c2b        11 hours ago        374.8 MB
debian              jessie              23cb15b0fcec        2 weeks ago         125.1 MB
debian              latest              23cb15b0fcec        2 weeks ago         125.1 MB
```

One more note. When I had just two Cassandra containers and no others... when I attempted to start the 3rd Cassandra one - it won't start either, because of the same error.

My thoughts are - the issue isn't in debian or cassandra containers, the issue seems to be in some sizing limits of docker that are set somewhere. Am I right? If yes - how can I fix that? if no - what else might it be?

Appreciate help.

**Comment by thaJeztah** [comment]
But this looks like some mounts are 100% in use;
```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
none            1.8G  1.8G     0 100% /
```

Can you add the output of `docker info` as well?

Note that docker uses disk space to;

- Store images
- Volumes (persisted data from containers, e.g. the data from your databases)
- The downloaded images before uncompressing
- Temporary files and caches during building and extracting of images

The total of those can be multiple times the size of the images alone

**Comment by BusyByte** [comment]
I've been experiencing the same issue with 1.9.1.
Starting big_dns_1
ERROR: Cannot start container e4ac93c0532ee721c4e2d2f9aa653f44e8aa064b0e59295b9149e7483289f270: write /mnt/sda1/var/lib/docker/containers/e4ac93c0532ee721c4e2d2f9aa653f44e8aa064b0e59295b9149e7483289f270/hash350128313: no space left on device

tmpfs                    4.4G    123.9M      4.2G  3% /
tmpfs                    2.4G      1.4M      2.4G  0% /dev/shm
/dev/sda1                27.8G    27.8G        0 100% /mnt/sda1
cgroup                    2.4G        0      2.4G  0% /sys/fs/cgroup
none                    232.6G    70.0G    162.7G  30% /Users
/dev/sda1                27.8G    27.8G        0 100% /mnt/sda1/var/lib/docker/aufs
none                    27.8G    27.8G        0 100% /mnt/sda1/var/lib/docke

I had tried to install sqlite3 to troubleshoot things and couldn't because tmp was full:
/dev/sda1                27.8G    27.8G        0 100% /mnt/sda1
tmp -> /mnt/sda1/tmp/
I restarted my machine and afterwards I couldn't even ssh in with docker because it didn't come up right.
I had to blow it away and start with a fresh machine.
We have a cleanup script which gets rid of unused stuff but it doesn't seem to help.  The space is still all used up.

We have a lot more containers 20 so definitely try to diagnose with lenadroid's info.
Also mine may be resolved now, still confirming.  I think I upgraded docker-machine which may have fixed it.

**Comment by BusyByte** [comment]
Things look better today:
tmpfs                     4.4G    124.0M      4.2G   3% /
tmpfs                     2.4G      1.7M      2.4G   0% /dev/shm
/dev/sda1                27.8G      6.4G     19.9G  24% /mnt/sda1
cgroup                    2.4G         0      2.4G   0% /sys/fs/cgroup
none                    232.6G     71.0G    161.6G  31% /Users
/dev/sda1                27.8G      6.4G     19.9G  24% /mnt/sda1/var/lib/docker/aufs
none                     27.8G      6.4G     19.9G  24% /mnt/sda1/var/lib/docker

Current setup:
Virtualbox 5.0.6r103037
Docker 1.9.1
docker-machine version 0.5.4
docker-compose 1.5.2

Yesterday I upgraded all of the above but I think only thing that really changed was docker-machine went from 0.5.1 to 0.5.4

**Comment by thaJeztah** [comment]
@BusyByte the number of containers does not have a direct relation to filling up the disk; a container does not take up any space, unless data is written into the writable layer of the container. However, images and volumes may take up space. (Also temp-files and the build-cache).

Point is, so far I haven't seen a bug in this report, apart from the Virtual Machine being filled up, which is not something that can be prevented. So more info is needed if you think there's a bug at hand here.

Please include at least the output of `docker info`, which may contain additional information

**Comment by BusyByte** [comment]
@thaJeztah if I start running of space again I'll include a docker info, I feel like unless the issue is currently happening I'd be reporting false information

**Comment by BusyByte** [comment]
@thaJeztah I took a look at the info, seems like much shouldn't have changed from yesterday:
Containers: 19
Images: 206
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 244
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 8
Total Memory: 4.836 GiB
Name: banno-big
ID: UDW2:SVEU:AS4B:Q7PI:OL2C:D3RI:G6T2:YBQX:BDQQ:SCWB:J4MI:F3HX
Debug mode (server): true
 File Descriptors: 108
 Goroutines: 191
 System Time: 2015-12-23T16:40:23.172426495Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

**Comment by lenadroid** [comment]
@thaJeztah thank you for the comment. Well, I have plenty of space on the disk, about 100 GB free, I can't understand why containers are created (?) so small? Why there is a space limit encountered if I just installed the containers from the Kitematic? Did I not enable some setting to make sure that docker can use the space?

```
$ docker info
Containers: 4
Images: 13
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: tmpfs
 Dirs: 21
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: L3K2:YOXH:5BYQ:62W3:PR7Z:57MC:DLFI:DGJH:HOSF:OUCO:RXOG:XVCM
Debug mode (server): true
 File Descriptors: 28
 Goroutines: 51
 System Time: 2015-12-23T17:04:34.835242737Z
 EventsListeners: 1
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

**Comment by thaJeztah** [comment]
> Well, I have plenty of space on the disk, about 100 GB free

Remember that kitematic runs docker in a VirtualBox virtual machine. The default size of the disk for that machine is 20GB, so if you `docker-machine ssh default` to start a `ssh` session in the virtual machine, and run `df -h` there, you might see that the disk of the virtual machine is full,

```
docker@default:~$ df -h
Filesystem                Size      Used Available Use% Mounted on
tmpfs                     1.8G    123.8M      1.6G   7% /
tmpfs                  1001.3M         0   1001.3M   0% /dev/shm
/dev/sda1                18.2G      3.0G     14.2G  17% /mnt/sda1
cgroup                 1001.3M         0   1001.3M   0% /sys/fs/cgroup
none                      2.8T    942.4G      1.9T  32% /Users
/dev/sda1                18.2G      3.0G     14.2G  17% /mnt/sda1/var/lib/docker/aufs
```

**Comment by lenadroid** [comment]
@thaJeztah thank you for this info. I've looked into Virtualbox and made sure that there is about 20GB issued for the docker. When I run the command I get the following output:

```
Boot2Docker version 1.9.1, build master : cef800b - Fri Nov 20 19:33:59 UTC 2015
Docker version 1.9.1, build a34a1d5
$ sudo df -h
Filesystem                Size      Used Available Use% Mounted on
tmpfs                     1.8G      1.8G         0 100% /
tmpfs                  1001.3M    728.0K   1000.6M   0% /dev/shm
cgroup                 1001.3M         0   1001.3M   0% /sys/fs/cgroup
none                    464.8G    377.3G     87.4G  81% /Users
tmpfs                     1.8G      1.8G         0 100% /mnt/sda1/var/lib/docker/aufs
none                      1.8G      1.8G         0 100% /mnt/sda1/var/lib/docker/aufs/mnt/66a17af83ca3a519ed9301dcd48e360ab4f66e9c33bb272b46f123e69a35a734
shm                      64.0M         0     64.0M   0% /mnt/sda1/var/lib/docker/containers/66a17af83ca3a519ed9301dcd48e360ab4f66e9c33bb272b46f123e69a35a734/shm
none                      1.8G      1.8G         0 100% /mnt/sda1/var/lib/docker/aufs/mnt/49c7a0e37475587b59c42ca413f4ac32b2ded49a0abcf302161d630bc8247c51
shm                      64.0M         0     64.0M   0% /mnt/sda1/var/lib/docker/containers/49c7a0e37475587b59c42ca413f4ac32b2ded49a0abcf302161d630bc8247c51/shm
none                      1.8G      1.8G         0 100% /mnt/sda1/var/lib/docker/aufs/mnt/9d8029e21918ae3177ac54ea9b525163062604dc651df4223ba8a0d5a00f7f7f
shm                      64.0M         0     64.0M   0% /mnt/sda1/var/lib/docker/containers/9d8029e21918ae3177ac54ea9b525163062604dc651df4223ba8a0d5a00f7f7f/shm
```

I've also checked the space occupied by /mnt/sda1, which is 2.9GB..

What else can it be?

**Comment by cpuguy83** [comment]
@lenadroid Two important things here, `/` has no space available, and likewise `/mnt/sda1/var/lib/docker/aufs` also has no space available.... the total size of these are 1.8 GB.

**Comment by lenadroid** [comment]
@cpuguy83 I didn't do anything to limit the space explicitly.. Why if I have a lot of space on my local hard drive, the / has no space?

**Comment by lenadroid** [comment]
I have resolved this memory issue in docker.

By default the memory for the docker is set to be 2048M by default. 

First step I performed is stopping my docker machine:

```
docker-machine stop default
```

Then I went to the  $HOME/.docker/machine/machines/default/config.json file and changed the "Memory" setting to be higher, i.e. 4096.

```
{
    "ConfigVersion": 3,
    "Driver": {
        "VBoxManager": {},
        "IPAddress": "192.168.99.102",
        "MachineName": "default",
        "SSHUser": "docker",
        "SSHPort": 59177,
        "SSHKeyPath": "/Users/lenok/.docker/machine/machines/default/id_rsa",
        "StorePath": "/Users/lenok/.docker/machine",
        "SwarmMaster": false,
        "SwarmHost": "tcp://0.0.0.0:3376",
        "SwarmDiscovery": "",
        "CPU": 1,
        "Memory": 4096, 
        "DiskSize": 204800,
        "Boot2DockerURL": "",
        "Boot2DockerImportVM": "",
        "HostDNSResolver": false,
        "HostOnlyCIDR": "192.168.99.1/24",
        "HostOnlyNicType": "82540EM",
        "HostOnlyPromiscMode": "deny",
        "NoShare": false,
        "DNSProxy": false
    },
    "DriverName": "virtualbox",
    "HostOptions": {
        "Driver": "",
        "Memory": 0,
        "Disk": 0,
        "EngineOptions": {
            "ArbitraryFlags": [],
            "Dns": null,
            "GraphDir": "",
            "Env": [],
            "Ipv6": false,
            "InsecureRegistry": [],
            "Labels": [],
            "LogLevel": "",
            "StorageDriver": "",
            "SelinuxEnabled": false,
            "TlsVerify": true,
            "RegistryMirror": [],
            "InstallURL": "https://get.docker.com"
        },
        "SwarmOptions": {
            "IsSwarm": false,
            "Address": "",
            "Discovery": "",
            "Master": false,
            "Host": "tcp://0.0.0.0:3376",
            "Image": "swarm:latest",
            "Strategy": "spread",
            "Heartbeat": 0,
            "Overcommit": 0,
            "ArbitraryFlags": [],
"config.json" [noeol] 75L, 2560C
            "Overcommit": 0,
            "ArbitraryFlags": [],
            "Env": null
        },
        "AuthOptions": {
            "CertDir": "/Users/lenok/.docker/machine/certs",
            "CaCertPath": "/Users/lenok/.docker/machine/certs/ca.pem",
            "CaPrivateKeyPath": "/Users/lenok/.docker/machine/certs/ca-key.pem",
            "CaCertRemotePath": "",
            "ServerCertPath": "/Users/lenok/.docker/machine/machines/default/server.pem",
            "ServerKeyPath": "/Users/lenok/.docker/machine/machines/default/server-key.pem",
            "ClientKeyPath": "/Users/lenok/.docker/machine/certs/key.pem",
            "ServerCertRemotePath": "",
            "ServerKeyRemotePath": "",
            "ClientCertPath": "/Users/lenok/.docker/machine/certs/cert.pem",
            "ServerCertSANs": [],
            "StorePath": "/Users/lenok/.docker/machine/machines/default"
        }
    },
    "Name": "default" 
}
```

Finally, started my docker machine again:

```
docker-machine start default
```

**Comment by frosario** [comment]
Thanks @lenadroid! This is exactly what i was looking for!

**Comment by pzien** [comment]
If nothing helps try recreating docker machine.

**Comment by bmxyuya** [comment]
Thanx a lot! it was really helpful!

**Comment by gaboesquivel** [comment]
increase memory from command line

```
docker-machine stop
VBoxManage modifyvm default --cpus 2
VBoxManage modifyvm default --memory 4096
docker-machine start
```

no space left error == > https://forums.docker.com/t/no-space-left-on-device-error/10894/17
problem is Docker.qcow2 file is huge, doing some cleanup helps.

```
docker rm $(docker ps -q -f 'status=exited')
docker rmi $(docker images -q -f "dangling=true")
docker volume rm $(docker volume ls -qf dangling=true)
```

**Comment by MKorostoff** [comment]
@gaboesquivel great solution.  That freed up about 11GB for me.  Thanks!

**Comment by cpuguy83** [comment]
btw, docker 1.13 will have `docker system prune` for doing basically this.
Also `docker system df` to get details about disk consumption by docker.

**Comment by Pedramrn** [comment]
I have the same issue, restarting the machine did not help.

```bash
~ > docker info                                                 
Containers: 4                                                   
 Running: 3                                                     
 Paused: 0                                                      
 Stopped: 1                                                     
Images: 7                                                       
Server Version: 1.12.3                                          
Storage Driver: aufs                                            
 Root Dir: /var/lib/docker/aufs                                 
 Backing Filesystem: extfs                                      
 Dirs: 43                                                       
 Dirperm1 Supported: true                                       
Logging Driver: json-file                                       
Cgroup Driver: cgroupfs                                         
Plugins:                                                        
 Volume: local                                                  
 Network: bridge host null overlay                              
Swarm: inactive                                                 
Runtimes: runc                                                  
Default Runtime: runc                                           
Security Options: apparmor seccomp                              
Kernel Version: 4.4.0-47-generic                                
Operating System: Ubuntu 16.04.1 LTS                            
OSType: linux                                                   
Architecture: x86_64                                            
CPUs: 2                                                         
Total Memory: 13.69 GiB                                         
Name: wiz-ir                                                    
ID: 5NVV:34G2:GPAP:5LHM:XTTW:BC5Q:4JCJ:UWMV:RYSX:W5TH:DA6Q:PJQ2 
Docker Root Dir: /var/lib/docker                                
Debug Mode (client): false                                      
Debug Mode (server): false                                      
Username: pedramrn                                              
Registry: https://index.docker.io/v1/                           
WARNING: No swap limit support                                  
Labels:                                                         
 provider=azure                                                 
Insecure Registries:                                            
 127.0.0.0/8                                                    
```

```bash
docker-user@wiz-ir:~$ df -h --total
Filesystem      Size  Used Avail Use% Mounted on
udev            6.9G     0  6.9G   0% /dev
tmpfs           1.4G  8.9M  1.4G   1% /run
/dev/sda1        29G   29G   35M 100% /
tmpfs           6.9G  228K  6.9G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           6.9G     0  6.9G   0% /sys/fs/cgroup
none             64K     0   64K   0% /etc/network/interfaces.dynamic.d
/dev/sdb1        28G   71M   28G   1% /mnt
tmpfs           1.4G     0  1.4G   0% /run/user/1000
total            80G   29G   52G  36% -

docker-user@wiz-ir:/var/lib/docker$ sudo du -d 1 | sort -nr
27389920        .
25743164        ./containers
1407440          ./aufs
235168           ./volumes
4064             ./image
68               ./network
4                ./trust
4                ./tmp
4               ./swarm
```

```
~ > docker ps -s
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                                   NAMES                    SIZE
3402d1275917        pedramrn/xxxxxxxxxx:0.5.4   "java -Djava.security"   2 weeks ago         Up 13 minutes       8080/tcp                                xxxserver_app_4   27 B (virtual 758.7 MB)
35e61c62aede        dockercloud/haproxy:1.5     "/sbin/tini -- docker"   3 weeks ago         Up 13 minutes       443/tcp, 0.0.0.0:80->80/tcp, 1936/tcp   xxx_lb_1    3.909 MB (virtual 44.77 MB)
3319a74e7d13        postgres:9.5                "/docker-entrypoint.s"   3 weeks ago         Up 13 minutes       0.0.0.0:5432->5432/tcp                  dbpostgres               151 B (virtual 263.9 MB)

```
Almost all the root directory space is taken up by docker dir and specifically `/var/lib/docker/containers`

**Comment by thaJeztah** [comment]
@Pedramrn are those containers generating a lot of logs / output, and are you using the default `json-file` logging driver, without `--max-size` and/or `--max-files` set? (see https://docs.docker.com/engine/admin/logging/overview/#/json-file-options). If so, it's possible that space is taken up by those log files.

**Comment by danieldram** [comment]
We have the same issue as Pedramrn. We looked into the log files and the size of them are miniscule. We upgraded to a 100gb HD on AWS to keep things running in prod, but it's already at 85%, we have no idea where the memory is being eaten up. $df shows 85%, but when we do  sudo sudo du -h / | grep '[0-9\.]\+G', it does not even closely account for the disk space usage.

Other than logs, is there anything else that could be eating space with docker?

**Comment by frosario** [comment]
I once hit control + Z during a docker rmi process, and it screwed up my layers as data was not completely unlinked. In extreme cases like that, you might have to uninstall docker, rm the directory where docker stores data (/var/lib/docker), and then reinstall. Best of luck.

**Comment by MuchContact** [comment]
@gaboesquivel Perfect! I got as much as 10G disk space!

**Comment by contactanant** [comment]
Very helpful,  My long pending docker disk space issue gone away by modifying $HOME/.docker/machine/machines/default/config.json
Thanks a million.

**Comment by kog13** [comment]
@gaboesquivel 

`docker volume rm $(docker volume ls -qf dangling=true)`

enormously helpful, thank you for this.

**Comment by thaJeztah** [comment]
With current versions of docker you can also use;

```
docker system prune
```

or (for just volumes)

```
docker volume prune
```

**Comment by khushalvirmani** [comment]
how does increasing the memory fix the disk space issue? btw i am having the same issue!

**Comment by spedy** [comment]
Thanks @lenadroid worked like a charm, also dramatically speed up my builds.

Hail @lenadroid 🙇

**Comment by abdennour** [comment]
This is because you are using **docker machine** which is a virtual machine which has a limit of space.

If you are in OSX, go to this docker machine then preferences then resize the disk of this VM: 

![image](https://user-images.githubusercontent.com/1788384/39036572-917b30e0-4486-11e8-83da-8b69c5d06415.png)
