### ISSUE TITLE
Can't pull ubuntu image 403 from https://registry-1.docker.io/v1/repositories/library/ubuntu/tags

### ISSUE THREAD

**Issue by vicglarson** [docker/docker#18865]
docker pull ubuntu leads to

time="2015-12-23T01:00:46Z" level="debug" msg="Calling POST /images/create"
time="2015-12-23T01:00:46Z" level="info" msg="POST /v1.16/images/create?fromImage=ubuntu%3Alatest"
time="2015-12-23T01:00:46Z" level="info" msg="+job pull(ubuntu, latest)"
time="2015-12-23T01:00:46Z" level="info" msg="+job trust_update_base()"
time="2015-12-23T01:00:47Z" level="debug" msg="Fetched 1 base graphs at 2015-12-23 01:00:47.104404613 +0000 UTC"
time="2015-12-23T01:00:47Z" level="info" msg="-job trust_update_base() = OK (0)"
time="2015-12-23T01:00:47Z" level="debug" msg="Pulling tag from V2 registry: \"latest\""
time="2015-12-23T01:00:47Z" level="debug" msg="[registry] Calling \"GET\" https://registry-1.docker.io/v2/manifest/library/ubuntu/latest"
time="2015-12-23T01:00:47Z" level="debug" msg="https://registry-1.docker.io/v2/manifest/library/ubuntu/latest -- HEADERS: map[User-Agent:[docker/1.4.1 go/go1.3.3 kernel/2.6.32-504.16.2.el6.x86_64 os/linux arch/amd64]]"
time="2015-12-23T01:00:47Z" level="debug" msg="hostDir: /etc/docker/certs.d/registry-1.docker.io"
time="2015-12-23T01:00:47Z" level="debug" msg="Reloaded graph with 3 grants expiring at 2017-03-22 19:04:46.713978458 +0000 UTC"
time="2015-12-23T01:00:48Z" level="debug" msg="[registry] Calling GET https://index.docker.io/v1/repositories/library/ubuntu/images"
time="2015-12-23T01:00:48Z" level="debug" msg="https://index.docker.io/v1/repositories/library/ubuntu/images -- HEADERS: map[User-Agent:[docker/1.4.1 go/go1.3.3 kernel/2.6.32-504.16.2.el6.x86_64 os/linux arch/amd64]]"
time="2015-12-23T01:00:48Z" level="debug" msg="hostDir: /etc/docker/certs.d/index.docker.io"
time="2015-12-23T01:00:49Z" level="debug" msg="Retrieving the tag list"
time="2015-12-23T01:00:49Z" level="debug" msg="https://registry-1.docker.io/v1/repositories/library/ubuntu/tags -- HEADERS: map[User-Agent:[docker/1.4.1 go/go1.3.3 kernel/2.6.32-504.16.2.el6.x86_64 os/linux arch/amd64]]"
time="2015-12-23T01:00:49Z" level="debug" msg="hostDir: /etc/docker/certs.d/registry-1.docker.io"
time="2015-12-23T01:00:50Z" level="debug" msg="Got status code 403 from https://registry-1.docker.io/v1/repositories/library/ubuntu/tags"
time="2015-12-23T01:00:50Z" level="error" msg="Could not reach any registry endpoint"
Could not reach any registry endpoint
time="2015-12-23T01:00:50Z" level="info" msg="-job pull(ubuntu, latest) = ERR (1)"

And (your doc is very sporadic)
https://docs.docker.com/v1.7/docker/reference/api/hub_registry_spec/#get-all-tags

Why this requires auth
https://registry-1.docker.io/v1/repositories/library/ubuntu/tags 

and this doesn't?
https://index.docker.io/v1/repositories/library/ubuntu/tags

**Comment by aaronlehmann** [comment]
You will need to upgrade to a newer version of Docker. Sorry for the inconvenience.

http://blog.docker.com/2015/10/docker-hub-deprecation-1-5/

**Comment by vicglarson** [comment]
Thanks

**Comment by thaJeztah** [comment]
I'll close this issue then. Feel free to comment here after I've closed!
