### ISSUE TITLE
docker -H / --host does not accept an IPv6 address

### ISSUE THREAD

**Issue by shmcfarl** [docker/docker#18879]
Description of problem:
When using docker -H or --host, an IPv6 address cannot be used.  I have tried the industry standard format of [] and that does not work either.  Here are two examples: One with no brackets and one with brackets.  Also, if i use a DNS name vs. IPv6 address, I get an error that the daemon is not running (which it is works fine over IPv4).

root@swarm-master-00:~# docker -H tcp://fd15:4ba5:5a2b:1009:20c:29ff:feaf:81c3:8333 info
invalid value "tcp://fd15:4ba5:5a2b:1009:20c:29ff:feaf:81c3:8333" for flag -H: Invalid bind address format: fd15:4ba5:5a2b:1009:20c:29ff:feaf:81c3:8333
See 'docker --help'.

root@swarm-master-00:~# docker -H tcp://[fd15:4ba5:5a2b:1009:20c:29ff:feaf:81c3]:8333 info
invalid value "tcp://[fd15:4ba5:5a2b:1009:20c:29ff:feaf:81c3]:8333" for flag -H: Invalid bind address format: [fd15:4ba5:5a2b:1009:20c:29ff:feaf:81c3]:8333
See 'docker --help'.

root@swarm-master-00:~# docker -H tcp://swarm-master-v6:8333 info
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

`docker version`:
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

`docker info`:
Containers: 1
Images: 13
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 15
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-74-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 2
Total Memory: 1.948 GiB
Name: swarm-master-00
ID: N2EK:5XBF:XVEG:6O3E:MU5I:PKVN:22SS:3AMT:RHVG:MGFU:DGSV:MJCA
WARNING: No swap limit support

`uname -a`:
Linux swarm-master-00 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
VM running in Fusion 8.1.0

How reproducible:
Easily

Steps to Reproduce:
1. Enable IPv6 on host
2. Install Docker Engine
3. Enable IPv6 for Docker (Use this for reference: https://docs.docker.com/engine/userguide/networking/default_network/ipv6/)
4. Enable docker swarm
5. Try to connect to swarm and get basic info

Actual Results:
docker -H tcp://[fd15:4ba5:5a2b:1009:20c:29ff:feaf:81c3]:2375 info
invalid value "tcp://[fd15:4ba5:5a2b:1009:20c:29ff:feaf:81c3]:2375" for flag -H: Invalid bind address format: [fd15:4ba5:5a2b:1009:20c:29ff:feaf:81c3]:2375

Expected Results:
Full output of docker swarm info

Additional info:

**Comment by blaggacao** [comment]
Hasn't https://github.com/docker/docker/pull/16950 probably made it yet into a release?

**Comment by cpuguy83** [comment]
It's not in a release yet, but will be in 1.10.
Closing as this was fixed already by #16950
