### ISSUE TITLE
After restart: "container already connected to network FOO" with swarm & consul

### ISSUE THREAD

**Issue by robertjung** [docker/docker#18870]
I'm running a 3-node cluster with swarm in replication mode backed by consul 0.6.0 on each server.

Those servers run on Ubuntu 14.04 (`Linux prodx 3.19.0-42-generic #48~14.04.1-Ubuntu SMP Fri Dec 18 10:24:49 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`)

I replaced one of those servers with Ubuntu 15.10 ( `Linux prod1 4.2.0-22-generic #27-Ubuntu SMP Thu Dec 17 22:57:08 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`)

```
docker version (all three)
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
```

```
docker info
Containers: 15
Images: 43
Role: replica
Primary: IP3:3376
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 3
 prod1: IP1:2376
  └ Status: Healthy
  └ Containers: 5
  └ Reserved CPUs: 0 / 8
  └ Reserved Memory: 0 B / 24.72 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.2.0-22-generic, node=prod1, operatingsystem=Ubuntu 15.10, provider=generic, storagedriver=aufs
 prod2: IP2:2376
  └ Status: Healthy
  └ Containers: 5
  └ Reserved CPUs: 0 / 8
  └ Reserved Memory: 0 B / 24.72 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.19.0-42-generic, node=prod2, operatingsystem=Ubuntu 14.04.3 LTS, provider=generic, storagedriver=aufs
 prod3: IP3:2376
  └ Status: Healthy
  └ Containers: 5
  └ Reserved CPUs: 0 / 8
  └ Reserved Memory: 0 B / 24.72 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.19.0-42-generic, node=prod3, operatingsystem=Ubuntu 14.04.3 LTS, provider=generic, storagedriver=aufs
CPUs: 24
Total Memory: 74.17 GiB
Name: b9787390b130
```

The new server `prod1` was set up from scratch again but had containers running on it before. Trying to create and run those containers again (from ansible or `docker-compose`) yields the error `Docker API Error: Cannot start container f0e817b002f6b87aaa6ffb98daef644588b719b5dae2bc7d63dcb9cf735cfc0b: container already connected to network internal`

I found a number of similar issues here that suggested deleting the container, restarting docker or the node and deleting the `local-kv.db`. None of those had any effect. My assumption is, that this info is stored in the consul cluster. Running the node without consul and removing `local-kv.db` might not trigger this issue, but then the network doesn't exist either.

Deleting the network doesn't work either:
```
$ docker network inspect internal
[
    {
        "Name": "internal",
        "Id": "c712ced3d03198465970d4feb5affef5eaad01012643ad0a0857eb9e88a4ba50",
        "Scope": "global",
        "Driver": "overlay",
        "IPAM": {
            "Driver": "default",
            "Config": [
                {}
            ]
        },
        "Containers": {},
        "Options": {}
    }
]
$ docker network rm internal
Error response from daemon: network internal has active endpoints
```

After rebooting a different node I had the same issue with containers connecting to the same network there, too.

Starting the container with a different name or on another network does work but is not something I want to do regularly.

Any ideas of how to remove those stale nodes from consul and how to avoid this issue in the future?

**Comment by thaJeztah** [comment]
So if I understand correctly, the node was replaced, but the containers were not removed beforehand, leading to consul and/or `local-kv.db` being out of sync with the actual situation?

ping @aboch @abronan looks like a situation that people may run into, any thoughts?

**Comment by robertjung** [comment]
Yes, though I'm not sure if the server change really was the trigger for this since it has happened on another, unchanged node, too. So might be a more general syncing problem.

**Comment by thaJeztah** [comment]
ping @aboch if you have some time, could you have a look at this? (Probably after the Holidays :christmas_tree:)

**Comment by robertjung** [comment]
this *could* be related to what *might* be a hardware issue on the original node where all the cores got stuck, some of them with docker-, elasticsearch- and consul process currently running on one of them. Hard to debug, sorry.
Would be happy to find a way of getting the "dead container names" back :)

**Comment by mavenugo** [comment]
@robertjung this could be related to https://github.com/docker/libnetwork/issues/786

**Comment by robertjung** [comment]
@mavenugo Yep, that sounds familiar

**Comment by thaJeztah** [comment]
@mavenugo is that issue planned for docker 1.10, or a later timeframe?

**Comment by vfarcic** [comment]
I have the same error when one node fails. The scenario is following.

* Two instances sharing the same network are running on different nodes; node-1 and node-2.
* Node-2 fails
* Redeployment is initiated through Swarm with intention to deploy the instance from the failed node (node-2) to the healty node (node-1)
* Swarm responds with "Cannot start container CONTAINER_ID: container already connected to network NETWORK_NAME"

I'm running Docker 1.9 with Consul 0.6.

**Comment by mavenugo** [comment]
@vfarcic @thaJeztah @robertjung we resolved this issue in 1.10 by a combination of fixes in both docker/docker and docker/swarm.
1. In docker/docker, we added a feature that provides force disconnect an endpoint/service from a network (`docker network disconnect -f NETWORK-NAME CONTAINER-NAME`}.
2. In docker/swarm, it uses the above force disconnect on the redeployed node and then use the same endpoint/service name.

Also, with the `--ip` support, this redeployment can also reuse the same IP address of the container on the new Host.

**Comment by thaJeztah** [comment]
Thanks @mavenugo, I'll close this issue!

**Comment by vfarcic** [comment]
@mavenugo In my case, redeployment in case of a failure is part of automated scripts. If I understood the fix correctly, I'd need to know which container was running on a failed node and disconnect it. That might be a bit tricky. Imagine the following scenario.

* Three instances of the same container are running (deployed through Docker Compose). The are booksms_app-blue_1, booksms_app-blue_2, and booksms_app-blue_3 and each is running in a different server.
* One server fails and, with it, booksms_app-blue_1.

How would I know that booksms_app-blue_1 should be disconnected (and not, for example, booksms_app-blue_3)? Even if the script should disconnect all of them, it might not even know how many instances are running (maybe someone scaled to 5).

The error I've got when running docker-compose scale, is the following.

ERROR: for 1  Cannot start container 453ced6285809e239e41f814457c1520c76efc2658b5a75aaa14b5af39b62c51: container already connected to network books-ms 
Removing booksms_app-blue_1 ... 
[1A[2K
Removing booksms_app-blue_1 ... done

From what I've seen, Docker Compose unsuccessfully tried to remove that container from Swarm's registry since the same message will popup again if I rerun the same docker-compose scale command.

Since Docker Compose already knows that something went wrong and tried to remove booksms_app-blue_1, maybe it could disconnect it from the network as well.

Also, unless I'm mistaken, the error is printed on the screen but the command does not exist with non-zero code.

**Comment by mavenugo** [comment]
@vfarcic in the case of node-failures swarm will manage the container redeployment automatically. If am not wrong that feature is not in swarm yet, but can be enabled as an experimental feature to try.
@vieux can add more info to it.

Also in 1.10, we support `--net-alias` in docker engine which is used by compose as a way to map service names to the container names during scale. @aanand  @dnephin can add more to it.

Regarding the question of `How would I know that booksms_app-blue_1 should be disconnected (and not, for example, booksms_app-blue_3)?`, will it help if we improve the error message from engine to indicate the container-name in `container already connected` message ?

Unfortunately, in the case of node-failure (and when the node is not brought up again), the states are retained in the distributed store and hence the higher layer systems (such as swarm) should have the details to cleanup and reschedule the containers.

**Comment by vfarcic** [comment]
You really made my day with the Swarm experimental feature. That's what I was looking for.

As for the error message, adding container name would help a lot. In such a case I can parse the output, deduce the name of the failed container, and disconnect it from the network. Can you also make sure that the command exits with a non-zero code?

**Comment by mavenugo** [comment]
@vfarcic experimental feature for swarm container rescheduling : https://github.com/docker/swarm/pull/1626
