### ISSUE TITLE
UX: Attempt to start boot2docker automatically

### ISSUE THREAD

**Issue by kevinSuttle** [docker/docker#18884]
```bash
❯ docker pull gliderlabs/alpine
Using default tag: latest
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

It would be nice to 
- have the docker cli check for the existence of  `boot2docker`, 
    - **true**: attempt to run `boot2docker up` automatically 
    - **false**: a link to this error in a Docker FAQ (can't seem to find one [here](https://docs.docker.com/engine/misc/faq/), surprisingly)

**Comment by kevinSuttle** [comment]
```bash
❯ docker --version
Docker version 1.9.1, build a34a1d5

❯ docker info
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

❯ uname -a
Darwin Kevins-MacBook-Pro.local 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64
```

**Comment by thaJeztah** [comment]
I don't think we'll implement a check if boot2docker / docker-machine is present, and automatically start the machine (and set the environment variables).

However, if you have suggestions on what to add to the FAQ, please do! If you want to contribute a docs change, that'd be awesome: the Markdown file used to generate the FAQ page is in this repository; https://github.com/docker/docker/blob/master/docs/misc/faq.md

If you need more info on our contribution process, please read the contributors guide; https://docs.docker.com/opensource/workflow/make-a-contribution/, but feel free to ping me here if you need help :+1:

**Comment by tkopczynski** [comment]
I'm running into this myself from time to time so I can create a new note to the FAQ since it's not already taken.
#dibs
