### ISSUE TITLE
Missing = in Control and configure Docker with systemd --storage-driver example 

### ISSUE THREAD

**Issue by cpswan** [docker/docker#18898]
Description of problem: adding a systemd config file to /etc/systemd/system/docker.service.d as documented in [Control and configure Docker with systemd](https://docs.docker.com/engine/articles/systemd) doesn't have the desired effect on storage driver used due to a missing =

`docker version`: 

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:

```
Containers: 0
Images: 0
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.0-16-generic
Operating System: Ubuntu 15.10
CPUs: 1
Total Memory: 3.843 GiB
Name: wily
ID: TMDH:I3EU:4QJW:QWOK:D6UV:MHTA:ZETE:THHF:5JAE:MVMW:LN7Q:X6DI
WARNING: No swap limit support
```

`uname -a`:

`Linux wily 4.2.0-16-generic #19-Ubuntu SMP Thu Oct 8 15:35:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

Environment details (AWS, VirtualBox, physical, etc.):

VMware Workstation 11 VM running Ubuntu 15.10 Server

How reproducible:

Consistently reproducible

Steps to Reproduce:

Try to configure as documented:
```
sudo mkdir /etc/systemd/system/docker.service.d`
sudo bash -c 'cat <<EOF > /etc/systemd/system/docker.service.d/overlay.conf
[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon -H fd:// --storage-driver overlay
EOF'
sudo systemctl daemon-reload
sudo systemctl restart docker
sudo docker info
```

Add in the required = at the end of --storage-driver as documented in [daemon options](https://docs.docker.com/engine/reference/commandline/daemon/):
```
sudo mkdir /etc/systemd/system/docker.service.d`
sudo bash -c 'cat <<EOF > /etc/systemd/system/docker.service.d/overlay.conf
[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon -H fd:// --storage-driver overlay
EOF'
sudo systemctl daemon-reload
sudo systemctl restart docker
sudo docker info
```

Actual Results:

`--storage-driver overlay` at the end of ExecStart means that aufs gets used

Expected Results:

overlay should be used

Additional info:

`--storage-driver=overlay` at the end of ExecStart will correctly use overlay
`--storage-driver btrfs` is perhaps a bad example anyway when the Docker team has been encouraging use of overlay since March.

**Comment by thaJeztah** [comment]
Thanks! Would you be interested in contributing, and opening a pull request? The Markdown file to generate that page of the documentation can be found in this repository; https://github.com/docker/docker/blob/master/docs/articles/systemd.md

Let us know if you're interested, otherwise we can take care of it :+1:

**Comment by cpswan** [comment]
dibs
