### ISSUE TITLE
docker volume not vailidate filters for dangling value

### ISSUE THREAD

**Issue by HackToday** [docker/docker#18890]
For docker image it add related validation, but docker volume not validation for that,
we need add check for dangling value
$ docker volume ls -f dangling=trued
DRIVER              VOLUME NAME
local               myvol
local               0e86f41c7db40f1314062b68ba05a03c96ed8b3c6f72e274419ce1621ddad818
local               b2d6be23626b5a73fcef5acbd359ed6ac1a58bcb8fbdf67dbf0d6ad6e717c859
local               420aa8064029961ce34871c587fc0a346c2871cd0be0e410d9bf7730fabf096d

We should do  like this
$ docker volume ls -f dangling=trued
Error response from daemon: Invalid filter 'dangling=trued'

$docker version
Client:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   94997e5
 Built:        Mon Nov 30 23:37:05 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   94997e5
 Built:        Mon Nov 30 23:37:05 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

**Comment by HackToday** [comment]
#dibs

**Comment by HackToday** [comment]
ping @cpuguy83  what do you think of this ?

**Comment by cpuguy83** [comment]
This is already a filter.
https://github.com/docker/docker/blob/master/daemon/list.go#L402-L403

**Comment by HackToday** [comment]
@cpuguy83 it seems not work  for wrong value validation.

I want to add validation for that.  Could you double check that ?
