### ISSUE TITLE
set memory-swap=-1,can't disable swap.

### ISSUE THREAD

**Issue by woshihaoren** [docker/docker#18894]
Hi:

I test memory-swap=-1 to disable swap,but use stress allocations  more then limit memory can success.

    docker version
    Client:
     Version:      1.9.1
     API version:  1.21
     Go version:   go1.4.2
     Git commit:   a34a1d5
     Built:        Fri Nov 20 13:25:01 UTC 2015
     OS/Arch:      linux/amd64

    Server:
     Version:      1.9.1
     API version:  1.21
     Go version:   go1.4.2
     Git commit:   a34a1d5
     Built:        Fri Nov 20 13:25:01 UTC 2015
     OS/Arch:      linux/amd64

    docker info
    Containers: 20
    Images: 167
    Server Version: 1.9.1
    Storage Driver: devicemapper
    Pool Name: docker-8:4-101624-pool
    Pool Blocksize: 65.54 kB
    Base Device Size: 107.4 GB
    Backing Filesystem: 
    Data file: /dev/loop0
    Metadata file: /dev/loop1
    Data Space Used: 17.39 GB
    Data Space Total: 2.684 TB
    Data Space Available: 2.667 TB
    Metadata Space Used: 30.49 MB
    Metadata Space Total: 2.147 GB
    Metadata Space Available: 2.117 GB
    Udev Sync Supported: true
    Deferred Removal Enabled: false
    Deferred Deletion Enabled: false
    Deferred Deleted Device Count: 0
    Data loop file: /var/lib/docker/devicemapper/devicemapper/data
    Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
    Library Version: 1.02.93-RHEL7 (2015-01-28)
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 3.18.24
    Operating System: CentOS Linux 7 (Core)
    CPUs: 24
    Total Memory: 125.9 GiB
    Name: server-10-255-33-102.com
    ID: KZX3:BNCG:ZI2N:VGJ4:X2LW:JAIV:IFPJ:YN6W:7QGE:CEBR:NOE5:QLO6
    Cluster store: etcd://10.255.33.102:2379
    Cluster advertise: 10.255.33.102:2375

    uname  -a
     Linux server-10-255-33-102.com 3.18.24 #1 SMP Wed Nov 25 16:30:20 CST 2015 x86_64 x86_64 x86_64 GNU/Linux

This machine is physical,and system is centos7

reproduce the issue:
1.docker run --name test1 -d  -m 500m --memory-swap=-1 centos6.6
2.docker exec-it test1 bash
3.rpm -Uvh http://pkgs.repoforge.org/stress/stress-1.0.2-1.el7.rf.x86_64.rpm
4.stress --vm 1 --vm-bytes 5000M --vm-hang 0
5.grep -i vmswap /proc/*/status
  /proc/1/status:VmSwap:	     220 kB
  /proc/184/status:VmSwap:	      92 kB
  /proc/185/status:VmSwap:	 4669140 kB
  /proc/203/status:VmSwap:	       0 kB
  /proc/23/status:VmSwap:	 1332496 kB
  /proc/9/status:VmSwap:	     752 kB
  /proc/90/status:VmSwap:	     336 kB
  /proc/self/status:VmSwap:	       0 kB
  /proc/thread-self/status:VmSwap:	       0 kB

This memory-swap=-1 like not limit swap,is not disable swap.

**Comment by cpuguy83** [comment]
Do you have the logs from this?
Can you provide the `inspect` output from this container?

**Comment by woshihaoren** [comment]
@cpuguy83  
yes,/var/log/message doesn't have useful log

this is inspect.
[
{
    "Id": "24f445a721e3ac21f1222d8c9f9c425a41e83e7b22d4e5388aa5b8646cfb9364",
    "Created": "2015-12-24T07:45:50.893484278Z",
    "Path": "/run.sh",
    "Args": [],
    "State": {
        "Status": "running",
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 46685,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2015-12-24T07:54:25.567440974Z",
        "FinishedAt": "2015-12-24T07:54:24.998801455Z"
    },
    "Image": "4fc33f8a29155418432f2d04b3386e04c82fa6aedd3b3f5b9060af655c78bf65",
    "ResolvConfPath": "/var/lib/docker/containers/24f445a721e3ac21f1222d8c9f9c425a41e83e7b22d4e5388aa5b8646cfb9364/resolv.conf",
    "HostnamePath": "/var/lib/docker/containers/24f445a721e3ac21f1222d8c9f9c425a41e83e7b22d4e5388aa5b8646cfb9364/hostname",
    "HostsPath": "/var/lib/docker/containers/24f445a721e3ac21f1222d8c9f9c425a41e83e7b22d4e5388aa5b8646cfb9364/hosts",
    "LogPath": "/var/lib/docker/containers/24f445a721e3ac21f1222d8c9f9c425a41e83e7b22d4e5388aa5b8646cfb9364/24f445a721e3ac21f1222d8c9f9c425a41e83e7b22d4e5388aa5b8646cfb9364-json.log",
    "Name": "/test1",
    "RestartCount": 0,
    "Driver": "devicemapper",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "AppArmorProfile": "",
    "ExecIDs": [
        "cfd54fe58ad12d1233727344bfb85e4672836922208d4b5356c1d6576f1cbb37"
    ],
    "HostConfig": {
        "Binds": null,
        "ContainerIDFile": "",
        "LxcConf": [],
        "Memory": 524288000,
        "MemoryReservation": 0,
        "MemorySwap": -1,
        "KernelMemory": 0,
        "CpuShares": 10,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
        "MemorySwappiness": -1,
        "Privileged": false,
        "PortBindings": {},
        "Links": null,
        "PublishAllPorts": false,
        "Dns": [],
        "DnsOptions": [],
        "DnsSearch": [],
        "ExtraHosts": null,
        "VolumesFrom": null,
        "Devices": [],
        "NetworkMode": "default",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "GroupAdd": null,
        "RestartPolicy": {
            "Name": "no",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
        "CgroupParent": "",
        "ConsoleSize": [
            0,
            0
        ],
        "VolumeDriver": ""
    },
    "GraphDriver": {
        "Name": "devicemapper",
        "Data": {
            "DeviceId": "1236",
            "DeviceName": "docker-8:4-101624-24f445a721e3ac21f1222d8c9f9c425a41e83e7b22d4e5388aa5b8646cfb9364",
            "DeviceSize": "107374182400"
        }
    },
    "Mounts": [],
    "Config": {
        "Hostname": "24f445a721e3",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": {
            "22/tcp": {},
            "8080/tcp": {}
        },
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "MEMORY=1g"
        ],
        "Cmd": [
            "/run.sh"
        ],
        "Image": "centos:6.6",
        "Volumes": null,
        "WorkingDir": "",
        "Entrypoint": null,
        "OnBuild": null,
        "Labels": {},
        "StopSignal": "SIGTERM"
    },
    "NetworkSettings": {
        "Bridge": "",
        "SandboxID": "d1222af4ae08beeac956ae6ad57c6bc304af3464a0a67861c6fbda6691db864b",
        "HairpinMode": false,
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "Ports": {
            "22/tcp": null,
            "8080/tcp": null
        },
        "SandboxKey": "/var/run/docker/netns/d1222af4ae08",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null,
        "EndpointID": "4deed46360e80e9df385e8fd7619f4bb6523893ed6d5e6151bd1a29f3b837e0e",
        "Gateway": "172.17.0.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "172.17.0.7",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "MacAddress": "02:42:ac:11:00:07",
        "Networks": {
            "bridge": {
                "EndpointID": "4deed46360e80e9df385e8fd7619f4bb6523893ed6d5e6151bd1a29f3b837e0e",
                "Gateway": "172.17.0.1",
                "IPAddress": "172.17.0.7",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "MacAddress": "02:42:ac:11:00:07"
            }
        }
    }
}
]

**Comment by woshihaoren** [comment]
@cpuguy83 
When I don't use --memory-swap=-1,It can OOM-kill

**Comment by hqhq** [comment]
@woshihaoren It's a misleading by docs, `--memory-swap=-1` doesn't mean disable swap, it actually means disable memory swap limit, means unlimited. If you want to disable memory swap, you need to assign `--memory-swap` as equal as `--memory`, then the container won't be able to use any swap memory. 

I've opened a PR #18902 to fix the docs.
