### ISSUE TITLE
"Illegal instruction (core dumped)" when loading a saved image

### ISSUE THREAD

**Issue by melonista** [docker/docker#18919]
Hello,

I created a Debian based image using my laptop. Then I saved the image and loaded it in another computer. When I tried to run some code in the new machine I got the following error: ```Illegal instruction (core dumped)``` . In order for it to work I had to re-compile multiple Python libraries.

Is there any way or best practices I can follow in order to be able to save an image in one machine and flawlessly use it in any other machine? Or should I always work with Dockerfiles and make a new build of each image for each different machine? 

Thank you

**Comment by thaJeztah** [comment]
The regular method is pushing the image to a registry, and pulling it from that. However, save/load (or export/import) should work as well. Are both computers comparable/same architecture? If you try to load the saved image on the laptop that you created it on, does that work without problems?

**Comment by melonista** [comment]
Yes, the saved image works without error if I load it in the same computer that I used to generate it.

In case it helps, two of the libraries that are failing are sickit-image and https://github.com/xianyi/OpenBLAS.

And this is the output for lscpu in the first machine.
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 60
Stepping:              3
CPU MHz:               2016.218
BogoMIPS:              5187.98
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              6144K
NUMA node0 CPU(s):     0-7
```

And in the second machine:
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                24
On-line CPU(s) list:   0-23
Thread(s) per core:    2
Core(s) per socket:    6
Socket(s):             2
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 44
Stepping:              2
CPU MHz:               2659.783
BogoMIPS:              5319.98
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              12288K
NUMA node0 CPU(s):     0-23
```

**Comment by unclejack** [comment]
@melonista You haven't provided the following bits of information:
1) the information requested by the bot, @GordonTheTurtle
2) a Dockerfile or any kind of image for us to try out

These bits of information would have helped figure this out sooner and allow more people to try to help you.

Based on the information you've provided above, it seems the two machines don't have the exact same CPU model. While this may not seem entirely relevant, it's very relevant. Those packages you've compiled are most likely enabling newer CPU instructions during compilation and those instructions are causing the `illegal instruction` errors you've seen. The fact that you're saying the image works after you recompile the packages makes me think this is what's happening.

Please check if there are any options you can set during the compilation or the configuration of those packages. You might want to try to build the packages on the oldest x86_64 CPU you've got to ensure they work on all the machines you intend to run this on.

I'm going to close this now as it really doesn't seem to be a Docker issue based on what you've told us and it seems to be a general support issue. Please feel free to comment.
