### ISSUE TITLE
How to inspect devices of a sandbox?

### ISSUE THREAD

**Issue by xiangpengzhao** [docker/docker#18917]
From the source code `libnetwork/drivers/overlay/ov_network.go`, I see that the func `initSubnetSandbox` creates a bridge and vxlan device for one subnet and move it to the sandbox. I wonder how to inspect the bridge and vxlan device of sandbox on my env.

Is there any command like `ip link show` to inspect? Thanks!

@mavenugo @mrjana @aboch

**Comment by mavenugo** [comment]
@xiangpengzhao This network sandbox is supposed to be internal to the overlay driver implementation and it is not expected for the users to manipulate it directly. Infact the overlay driver would behave incorrectly if the user modifies the network-sandbox namespace directly. Is there a reason for you to access this namespace directly ?
If you are determined to do that regardless of the consequences :-) follow these steps -

1. Use `docker network ls` command to identify the network-id of the corresponding network that you are trying to access the sandbox.
2. As a root user, `cd /var/run/docker/netns` and identify the namespace to enter. the namespace is named as `{x}-{first 10 digits of network-id}`. ({x} is a random number assigned by libnetwork).
3. you can use nsenter (easy install : `docker run -v /usr/local/bin:/target jpetazzo/nsenter`). For more info refer to https://blog.docker.com/2014/06/why-you-dont-need-to-run-sshd-in-docker/. 
4. `nsenter --net=/var/run/docker/netns/{x}-{10 digits of network-id} ip link show`

**Comment by xiangpengzhao** [comment]
Thanks @mavenugo 
I have been reading source codes of docker. I'm interested in the details of overlay network, so I want to inspect the devices created for a sandbox. I will not modify anything :-)

**Comment by mavenugo** [comment]
@xiangpengzhao thanks :) BTW, with #18775 overlay network is supported in kernels < 3.16 as well. And we dont use the network-sandbox for kernels < 3.16. Meaning all the bridges and the vxlan devices are created on the host namespace. (Hence my comment above doesnt apply for kernels < 3.16).

Closing this issue.

**Comment by xiangpengzhao** [comment]
OK. Thanks @mavenugo
