### ISSUE TITLE
[1.10] image id column in `docker ps` is too short

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#18914]
Now that all image IDs start with `sha256:`, you only get 5 unique characters in the `docker ps` now, as opposed to 12 before.  Being that `sha256:` seems to be optional when doing `docker inspect` maybe if you have `docker ps --no-trunc=false` then `sha256:` is trimmed.  Then the only time you see `sha256` is doing `docker ps --no-trunc`

**Comment by thaJeztah** [comment]
sgtm (just my 0.02c)

Do you want to open a PR for this, @ibuildthecloud ?

**Comment by tonistiigi** [comment]
New clients already don't show prefix for the truncated ID, I think what you are describing only happens with the old client and new daemon combination. We could try to test the API version to remove prefixes but as the id truncation happens on the client side we would need to do that for full IDs as well and that may be slightly less secure.

**Comment by ibuildthecloud** [comment]
@tonistiigi Ah, that is most likely the case here.  Let me test that.

**Comment by ibuildthecloud** [comment]
@tonistiigi Thanks, that was my issue.  While I run docker daemon from master I'm often using the latest released client.
