### ISSUE TITLE
Default vxlan udp port

### ISSUE THREAD

**Issue by chenchun** [docker/docker#18929]
I tested overlay network on kernel 3.10. It didn't work at first. I found vxlan device listens on 8472 udp port instead of 4789. So I changed vxlan module to use 4789 udp port and it worked.

```
# cat /etc/modprobe.d/vxlan.conf
 
#### Set the VXLAN UDP port ####
options vxlan udp_port=4789

# rmmod vxlan
# modprobe -v vxlan
```

However it seems to work fine on ubuntu kylin 14.10 without the above configuration.
If this is a old kernel version problem, we'd better add some documents talking about this.
ping @mrjana @mavenugo

**Comment by mavenugo** [comment]
@chenchun thanks. This is related to https://github.com/docker/libnetwork/issues/358 when we changed the VXLAN port to use the IANA assigned value of `4789`. where as `8472` is assigned for OTV.
Having said that, we need to find the right balance between the best UX compared to the correctness of Port number. 
Can you please verify if reverting https://github.com/docker/libnetwork/pull/361 works for all kernels 3.10 and up ?

**Comment by mavenugo** [comment]
@chenchun Also, can you pls confirm the distribution that you are trying (is this a particular version of centos / RHEL) ?

**Comment by mavenugo** [comment]
@chenchun I tried Centos7 with kernel `3.10.0-229.el7.x86_64` and I don't see this issue.
```
Linux localhost.localdomain 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

The only problem I saw is that firewalld is not letting the vxlan packets to go through.
when I stopped the firewalld service it worked just fine. Can you please confirm ?

**Comment by mavenugo** [comment]
@chenchun I narrowed down to a single firewalld command to enable VXLAN traffic (instead of disabling firewalld).

`sudo firewall-cmd --zone=public --permanent --add-port=4789/udp`

Can you please give it a try ?

**Comment by chenchun** [comment]
Yes, I just tried Centos7 with kernel 3.10.0-229.el7.x86_64 and confirmed it listens on 4789. Maybe this is because vxlan related code of my kernel have been modified. Still waiting for answers from the kernel team. I should have confirmed with them before open this issue. Sorry for the noisy.
