### ISSUE TITLE
Allow to specify subnet with docker-compose --x-networking

### ISSUE THREAD

**Issue by ashatrov** [docker/docker#18931]
When i use ```docker-compose --x-networking up``` it create subnet for each containers group (for each folder with docker-compose.yml) with 172.18.0.0/16, 172.19.0.0/16 .... etc.

In our office network we already have 172.18.*.* and I can not connect to these machines from containers.

I want to specify subnet when I start containers group with ```docker-compose --x-networking```

**Comment by thaJeztah** [comment]
Since this is a feature request for docker-compose, can you open this issue in that issue tracker? https://github.com/docker/compose/issues

**Comment by ashatrov** [comment]
New issue in docker/compose tracker - https://github.com/docker/compose/issues/2582

**Comment by thaJeztah** [comment]
Thanks @ashatrov

**Comment by aderumier** [comment]
Hi,
docker-compose don't specify any subnet cidr when creating the new bridge.
Is is possible to preconfigure on docker side, all allowed network ranges in a list ?
new bridge creation take the first range available in the list.


I think that currently, the code is in 
docker/libnetwork/ipamutils/utils.go 

var (
        // PredefinedBroadNetworks contains a list of 31 IPv4 private networks with host size 16 and 12
        // (172.17-31.x.x/16, 192.168.x.x/20) which do not overlap with the networks in `PredefinedGranularNetworks`
        PredefinedBroadNetworks []*net.IPNet

....func initBroadPredefinedNetworks() []*net.IPNet {
        pl := make([]*net.IPNet, 0, 31)
        mask := []byte{255, 255, 0, 0}
        for i := 17; i < 32; i++ {

**Comment by BarnumD** [comment]
One option is to add `network_mode: "bridge"` under each service. (so below 'image:' or 'volumes:' of each service)

This forces docker-compose to use the default bridge network docker provides.  Otherwise docker-compose does a docker network create for each compose that is run.  Invariably it creates networks that overlap our corporate range.
