### ISSUE TITLE
seccomp: config provided but seccomp not supported.

### ISSUE THREAD

**Issue by phemmer** [docker/docker#18946]
Building from current master returns the following error any time any container is started:

```
# docker run --rm busybox true
seccomp: config provided but seccomp not supported
docker: Error response from daemon: Cannot start container 43f6e217197d8a286cf38bfef0361e2aafc5251d15da5f5850ea9c63caad7f12: [9] System error: seccomp: config provided but seccomp not supported.
```

daemon logs:
```
WARN[0005] exit status 1                                
WARN[0005] failed to cleanup ipc mounts:
failed to umount /var/lib/docker/containers/43f6e217197d8a286cf38bfef0361e2aafc5251d15da5f5850ea9c63caad7f12/shm: invalid argument
failed to umount /var/lib/docker/containers/43f6e217197d8a286cf38bfef0361e2aafc5251d15da5f5850ea9c63caad7f12/mqueue: invalid argument 
ERRO[0005] Error unmounting container 43f6e217197d8a286cf38bfef0361e2aafc5251d15da5f5850ea9c63caad7f12: not mounted 
ERRO[0005] Handler for POST /v1.22/containers/43f6e217197d8a286cf38bfef0361e2aafc5251d15da5f5850ea9c63caad7f12/start returned error: Cannot start container 43f6e217197d8a286cf38bfef0361e2aafc5251d15da5f5850ea9c63caad7f12: [9] System error: seccomp: config provided but seccomp not supported 
```

The package was built without the `seccomp` build tag. However having it as a build tag implies it is optional, and thus docker should work without it.

```
# docker version
Client:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   78ce43b
 Built:        Mon Dec 28 22:05:30 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   78ce43b
 Built:        Mon Dec 28 22:05:30 2015
 OS/Arch:      linux/amd64

# docker info                 
Containers: 4
Images: 55
Server Version: 1.10.0-dev
Storage Driver: btrfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.0.5-gentoo
Operating System: Gentoo/Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.64 GiB
Name: whistler
ID: 27PU:7FU5:JFWG:62CV:LVZ7:GKDH:5DEC:5I27:QDHP:MNWM:QBY6:BKGR
Username: phemmer
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

```

Built from 78ce43bad85fdf97d7c836315e46b531901c8ae7

**Comment by phemmer** [comment]
Looks like this is being caused by PR #18780

**Comment by jfrazelle** [comment]
sorry my b i can fix that for unsupported, for now you can also use --security-opt seccomp:unconfined

**Comment by pdevine** [comment]
I'm running into:

pdevine@clone1:~$ docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
03f4658f8b78: Pull complete 
a3ed95caeb02: Pull complete 
Digest: sha256:8be990ef2aeb16dbcb9271ddfe2610fa6658d13f6dfb8bc72074cc1ca36966a7
Status: Downloaded newer image for hello-world:latest
conditional filtering requires libseccomp version >= 2.2.1
docker: Error response from daemon: Cannot start container 903af94ae5c57468f9c23b1fc6748d3530eddd99fcce0b3b547ea6edd9b62423: [9] System error: conditional filtering requires libseccomp version >= 2.2.1.

This is on Ubuntu 14.04.3.

**Comment by jfrazelle** [comment]
was this installed from experimental.docker.com, then we probably need to
up the dep for libseccomp

**Comment by jfrazelle** [comment]
this is a different issue than the original but ill take care of it

**Comment by pdevine** [comment]
Yep.  Through experimental.docker.com.

**Comment by jfrazelle** [comment]
opened https://github.com/docker/docker/pull/18949

**Comment by thaJeztah** [comment]
running experimental with `seccomp:unconfined` doesn't seem to solve all;

```
root@ubuntu-1gb-ams3-01:~# docker run -d --security-opt seccomp:unconfined nginx
e832e33300594f49fae69b5c4ce86e44028f9dd47893322f7b259d31a2e6dd3a
root@ubuntu-1gb-ams3-01:~# docker logs e832e33300594f49fae69b5c4ce86e44028f9dd47893322f7b259d31a2e6dd3a
nginx: error while loading shared libraries: libpthread.so.0: cannot open shared object file: Permission denied
```

not sure if it's related to this

**Comment by jfrazelle** [comment]
That's the same fix as above with libseccomp version I believe

**Comment by thaJeztah** [comment]
Cool, I thought I'd better post it, in case it's relevant :)

**Comment by tianon** [comment]
Arg, do we need to do some crazy runtime detection or something? Or is the problem really just that we're linking against too new of a library? The static binaries probably need a solution too, don't they?

**Comment by jfrazelle** [comment]
ya @tianon i opened this PR but I hope we can get ubuntu trusty and debian jessie to up the version maybe soon? or eventually https://github.com/docker/docker/pull/18949

**Comment by akamalov** [comment]
Greetings, 

**Environment:**

```
OS: RHEL 7.2
Kernel: 3.10.0-327.4.4.el7.x86_64
Libseccomp : libseccomp-2.2.1-1.el7.x86_64
Docker Version:
 Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:34:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:34:50 2016
 OS/Arch:      linux/amd64
```

Getting the same error:

```
seccomp: config provided but seccomp not supported
docker: Error response from daemon: Cannot start container 50e3c58a17b24125a5952abd552b4a661b9dfca1bb5b3f3dae2022dbe3292895: [9] System error: seccomp: config provided but seccomp not supported.
```

**Comment by thaJeztah** [comment]
@akamalov is that the default version installed on RHEL 7.2? I think the case with CentOS/RHEL 7, OS that 7.0 and 7.1 don't have the required version, so seccomp is not compiled into those packages (we currently don't have separate builds for 7.2)

**Comment by akamalov** [comment]
Thanks for responding. When you said  "CentOS/RHEL 7, OS that 7.0 and 7.1 don't have the required version" , did you mean libseccomp ? If yes, libseccomp-2.2.1-1 is available through 'yum.' I thought 2.2.1 was the minimum requirement.

Thanks again!

Alex

**Comment by thaJeztah** [comment]
@akamalov I should check if it's available at 7.0 and 7.1; point is that it's enabled/disabled during compile-time, so if the `seccomp` build-flag was not present during compile time of the binaries, it won't be available. In the 1.10.2 tag, the `seccomp` flag is not set for the Dockerfile to build the RPM (see https://github.com/docker/docker/blob/v1.10.2/contrib/builder/rpm/centos-7/Dockerfile#L17), so it won't be available in those RPM's.

I know we originally had this feature enabled for those RPM's but there were issues, so it was removed in this commit: https://github.com/docker/docker/commit/ae54e39c80b8cc071143bfcb99bf80e3b0a0ec93. Possibly the situation has changed in the mean-time, in which case we can re-enable in the next release.

ping @jfrazelle perhaps you remember if CentOS/RHEL had an older version of seccomp at that time? According to the discussion above, 2.2.1 is now available on CentOS/RHEL

**Comment by akamalov** [comment]
@jfrazelle would it be possible to obtain Docker build with SECCOMP enabled for RHEL 7.2? At this point the company is tightly integrated with RHEL as an OS of choice and we cannot (at this moment) use CoreOS or Debian.

Thanks so much!!!

Alex

**Comment by jfrazelle** [comment]
PRs welcome if the rpm for rhel seccomp-dev is of the right version then
it's possible but we don't hold the keys for that

On Tuesday, February 23, 2016, akamalov <notifications@github.com> wrote:

> @jfrazelle <https://github.com/jfrazelle> would it be possible to obtain
> Docker build with SECCOMP enabled for RHEL 7.2? At this point the company
> is tightly integrated with RHEL as an OS of choice and we cannot (at this
> moment) use CoreOS or Debian.
>
> Thanks so much!!!
>
> Alex
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/18946#issuecomment-187711125>.
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by thaJeztah** [comment]
ping @runcom perhaps you'd be able to check? (I know you asked about this as well)

**Comment by akamalov** [comment]
Currently for RHEL7.2 (which I am running) there are following SECCOMP libraries available:

```
> libseccomp-devel-2.1.1-2.el7.i686 : Development files used to build applications with libseccomp support Repo: rhel-x86_64-server-optional-7

> libseccomp-2.1.1-2.el7.x86_64 : Enhanced seccomp library Repo: rhel-x86_64-server-7
```

Thanks,

Alex

**Comment by thaJeztah** [comment]
@akamalov hm 2.1.1, so no 2.2.1 yet?

**Comment by akamalov** [comment]
Sorry, my bad. Here is a complete list:

```
libseccomp-2.2.1-1.el7.x86_64 : Enhanced seccomp library
Repo        : rhel-x86_64-server-7

libseccomp-devel-2.2.1-1.el7.x86_64 : Development files used to build applications with libseccomp support
Repo        : rhel-x86_64-server-optional-7

```

**Comment by akamalov** [comment]
So, any way we can get seccomp for RHEL7.2 ???

**Comment by thaJeztah** [comment]
If someone wants to make a pull request to enable it in the builds, I think we can accept that; then it can be made available in the experimental builds

**Comment by cpuguy83** [comment]
@akamalov #22344
