### ISSUE TITLE
Docker build steps occasionally fail when running in a concurrent CI environment

### ISSUE THREAD

**Issue by aaronjwood** [docker/docker#18976]
I'm seeing a usually rare but strange issue. Maybe once every other day a build or two fails due to messages like this:

```
Removing intermediate container b1b63ca1e55b
Step 4 : ADD entrypoint.sh /home/entrypoint.sh
---> 8636fdf2699f
Removing intermediate container 86091a73834a
Step 5 : ENTRYPOINT /home/entrypoint.sh
---> Running in 403e6404be05
time="2015-12-29T20:53:55Z" level=info msg="lstat /var/lib/docker/overlay/403e6404be05a62c46c9d435ec77182828f7145c5518ed19dc1c15988ad00d6b/merged/usr/share/misc: no such file or directory"
```

I'm also seeing a few other strange issues such as an image not being able to add a file into the container on one build, but will succeed immediately on the next build. The `ADD` is something very simple like this:

```
ADD file.txt /home/file.txt
```

That issue is more rare than the first but they both seem to be triggered more often when concurrent builds are running (I think). We haven't seen these issues when building locally, but I think that is a poor comparison since most of us who will build locally to test use Docker 1.9 with Docker Machine and will not run concurrent builds.

Here's my environment

CoreOS 723.3.0
Docker 1.6.2
Storage diver: overlay
Backing filesystem: extfs
Execution Driver: native-0.2
Kernel: 4.0.5
24 cores/128GB RAM

I'm running the latest version of jenkins as a container on the CoreOS host. Jenkins executes many steps of our build inside of a build container (so it's a container-in-container environment) and is set to use 8 executors at the most. I have mapped in the docker binary, libdevmapper.so.1.02, and /var/run/docker.sock to the jenkins container so that it is able to work with containers.

Any ideas on this?

**Comment by thaJeztah** [comment]
No ideas, but wondering if you're able to reproduce this on the current version of docker. Point is, that if it's a bug in 1.6, chances are it's resolved already, and we don't back port fixes to older releases.

**Comment by aaronjwood** [comment]
I'd have to dedicate some time at work to bring up another small cluster somewhere else running the latest version. Can't say I will be able to get to that soon, but I will try :)

Let me see if I'm good to go with upgrading the cluster that jenkins is on now. Will get back to you on this...

**Comment by thaJeztah** [comment]
@aaronjwood are you okay closing this issue in the meantime? Feel free to reopen once you have more information (it's best to close it yourself, because I don't think you'll be able to reopen if I close it for you)

**Comment by aaronjwood** [comment]
Sure, that's fine. I will get back to you when I can. Thanks!

**Comment by aaronjwood** [comment]
I've upgraded our environment to the latest version of Docker (1.9.1) and so far things seem to be good. I will continue to monitor the situation as it was very intermittent before. Will post back here if I run into any of the original issues again.

**Comment by thaJeztah** [comment]
Nice, thanks!

**Comment by aaronjwood** [comment]
Moving to the newest version (1.9.1 right now) seems to have fixed the issues I was seeing. Guess they really were bugs in the older version :)

Thanks!

**Comment by thaJeztah** [comment]
Great to hear! Thanks for reporting back, really appreciated
