### ISSUE TITLE
Add reference to docker images format

### ISSUE THREAD

**Issue by tonistiigi** [docker/docker#18975]
As a solution to #17304 provide a way to get a reference from `docker images --format` so deleting images could work with:

`docker rmi $(docker images --format {{.ref}})`

cc @vdemeester

**Comment by orlade** [comment]
Seems like this has been implemented and an be closed? v1.12.0-rc3, build 91e29e8, experimental

`docker images --format {{.Repository}}`

**Comment by thaJeztah** [comment]
@orlade thanks! Yes, I think this can be closed
