### ISSUE TITLE
`docker search` filter official images

### ISSUE THREAD

**Issue by fsoppelsa** [docker/docker#18980]
Can we add a simple switch to output only official images for `docker search`, as there is for `--automated=true|false` ?

**Comment by qq690388648** [comment]
I thought it is a good idea, and it is easy to implement.
From the (client code)[https://github.com/docker/docker/blob/master/api/client/search.go#L72], we can find that the response of <code>search</code> command from registry include the <code>IsOfficial</code> attribute.

**Comment by thaJeztah** [comment]
I think it makes sense, so I'm +1 for a feature that support this.

For *consistency* with other commands (e.g. `docker ps`, `docker images`), I would be in favor of implementing a `--filter` option for search in stead of adding more flags, and mark the `--automated` and `-s, --stars` flags as deprecated.

e.g. `docker search --filter is-official=true --filter is-automated=true foobar`

**Comment by qq690388648** [comment]
ping @thaJeztah 
There is a little difference from <code>docker ps</code>, that is where should we do the filter? registry, daemon, or just client?

**Comment by fsoppelsa** [comment]
I think that just client, I intended this as UX. But @thaJeztah knows better :)

**Comment by thaJeztah** [comment]
Yes, my first thought here was to make that change purely from a UX perspective, so no changes in the way "filtering" is implemented now, just a different flag for consistency.

@duglin wdyt?

**Comment by thaJeztah** [comment]
https://github.com/docker/docker/issues/22369 was merged, so this will be in docker 1.12

thanks @fsoppelsa!
