### ISSUE TITLE
Unable to start the docker service

### ISSUE THREAD

**Issue by vikassinghal05** [docker/docker#18995]
I am unable to start the docker service...

while trying  to start docker service using sudo service docker start getting below error :-1: : 
[vagrant@host1 ~]$ sudo service docker start
Redirecting to /bin/systemctl start  docker.service
Job for docker.service failed. See 'systemctl status docker.service' and 'journalctl -xn' for details.

[vagrant@host1 ~]$ sudo service docker status
Redirecting to /bin/systemctl status  docker.service
docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled)
   Active: failed (Result: timeout) since Wed 2015-12-30 14:11:55 UTC; 4min 23s
ago
     Docs: http://docs.docker.com
 Main PID: 6384
   CGroup: /system.slice/docker.service

Dec 30 14:11:08 host1 docker[6384]: time="2015-12-30T14:11:08.474772686Z" l...b"

Dec 30 14:11:11 host1 docker[6384]: time="2015-12-30T14:11:11.299007608Z" l...e"

Dec 30 14:11:16 host1 docker[6384]: time="2015-12-30T14:11:16.551277425Z" l...2"

Dec 30 14:11:21 host1 docker[6384]: time="2015-12-30T14:11:21.294961039Z" l...4"

Dec 30 14:11:32 host1 docker[6384]: time="2015-12-30T14:11:32.026282982Z" l...f"

Dec 30 14:11:35 host1 docker[6384]: time="2015-12-30T14:11:35.593087556Z" l...9"

Dec 30 14:11:40 host1 docker[6384]: time="2015-12-30T14:11:40.714138176Z" l...f"

Dec 30 14:11:54 host1 systemd[1]: docker.service operation timed out. Termi...g.

Dec 30 14:11:55 host1 systemd[1]: Failed to start Docker Application Contai...e.

Dec 30 14:11:55 host1 systemd[1]: Unit docker.service entered failed state.
Hint: Some lines were ellipsized, use -l to show in full.
[vagrant@host1 ~]$

**Comment by vikassinghal05** [comment]
[vagrant@host1 ~]$ docker version
Client version: 1.7.1
Client API version: 1.19
Package Version (client): docker-1.7.1-115.el7.x86_64
Go version (client): go1.4.2
Git commit (client): 446ad9b/1.7.1
OS/Arch (client): linux/amd64
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
[vagrant@host1 ~]$

[vagrant@host1 ~]$ docker info
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
[vagrant@host1 ~]$

I am using VirtualBox

**Comment by thaJeztah** [comment]
- Are you also having this issue on the current release (1.9.1)?
- Do the daemon logs in the virtual machine show anything useful?

Based on the "Git commit"; https://github.com/docker/docker/commit/446ad9bd9e8ec218aff5b22529c0bdc6df69d0e2 if looks like you're installing a version of docker that's packaged by Red Hat, and contains modifications. 

Are you also having this issue if you're installing the docker-distributed version, using the installation instructions in our documentation? https://docs.docker.com/engine/installation/

**Comment by vikassinghal05** [comment]
Please share the command so I can output of that to you...I am quite new to this...

**Comment by thaJeztah** [comment]
I think `journalctl -u docker.service` should probably give you some info.

**Comment by vikassinghal05** [comment]
[vagrant@host1 ~]$ journalctl -u docker.service
No journal files were found.

**Comment by thaJeztah** [comment]
Was it running correctly before on that machine?

**Comment by vikassinghal05** [comment]
I didn't check that...but docker was running perfectly....

**Comment by qq690388648** [comment]
Have you try the below command?
<code>systemctl status -l docker.service</code>

**Comment by unclejack** [comment]
This doesn't seem to be a Docker bug. It seems to be a problem related to the way that particular system is set up and it seems to be more of a support request.

Since this isn't a general support forum and it doesn't seem to be a Docker bug, I'll close this issue now.

Please feel free to continue the discussion on this issue. There's no need to open a new issue as everyone can still comment freely on this issue.

**Comment by Syed1991Abid** [comment]
Hi  @qq690388648 thanks man, I was getting the same issue but it resolve with the command which you sent
