### ISSUE TITLE
Docker daemon is not getting started. docker.service failed

### ISSUE THREAD

**Issue by mohanrao** [docker/docker#18996]
Hi ,

I am not able to start the docker daemon on RHEL with below environment

$>uname -r
3.10.0-327.el7.x86_64
$>docker --version
Docker version 1.9.1, build a34a1d5

I see the following error when i ener journalctl -xe

/usr/bin/docker: relocation error: /usr/bin/docker: symbol dm_task_get_info_with_deferred_remove, version Base not defined in file libdevmapper.so.1.02 with link time reference

**Comment by thaJeztah** [comment]
Did you make sure all your packages were up to date before installing docker? Also see; https://github.com/docker/docker/issues/12108

Which steps did you take to install docker? Dit you use `curl -sSL https://get.docker.com | sh`, or the manual procedure, as described in https://docs.docker.com/engine/installation/rhel/ ?

**Comment by mohanrao** [comment]
I followed the manual procedure as described in https://docs.docker.com/engine/installation/rhel/

**Comment by thaJeztah** [comment]
Could you try installing/updating `device-mapper-event` (that seemed to solve the other issue I linked to),

/cc @rhvgoyal perhaps you have additional suggestions here

**Comment by mohanrao** [comment]
Thanks @thaJeztah . I will try and let you know

**Comment by mohanrao** [comment]
Updated the RHEL to 7.2 and reinstalled the docker. It is working now

**Comment by thaJeztah** [comment]
Thanks! Good to hear you resolved your issue

**Comment by rhvgoyal** [comment]
@mohanrao, good that upgrade to 7.2 resolved your issue. I think there was a short window where libdevmapper had symbol issue and it was fixed later. And that's the reason upgrade fixed the issue for you too.
