### ISSUE TITLE
ubuntu 14.04 installation problems in docs

### ISSUE THREAD

**Issue by kopchik** [docker/docker#19005]
Hi!

I think a couple of things are wrong on https://docs.docker.com/engine/installation/ubuntulinux/ . May be I should have created two separate bugs...

First, I got gpg problems("NO_PUBKEY D8576A8BA88D21E9"), even after "apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D". The solution was to change '--recv-keys' to D8576A8BA88D21E9  (yes, I have read bug https://github.com/docker/docker/issues/16820 and others, proposed solutions didn't work for me).

Second, instead of installing linux-image-extra-$(uname -r) it's better to install linux-image-extra-virtual because it will keep linux-image-extra-* in sync with the kernel on kernel upgrades (some more info here on metapackages and other stuff: http://askubuntu.com/questions/503020/linux-image-virtual-packages-empty-in-14-04-trusty). 

Hope this was useful.

PS system info:

~~~
root@vagrant-ubuntu-trusty-64:~# uname -a
Linux vagrant-ubuntu-trusty-64 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

root@vagrant-ubuntu-trusty-64:~# docker info
Containers: 1
Images: 2
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 4
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-74-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 490 MiB
Name: vagrant-ubuntu-trusty-64
ID: VJU5:EZSP:6YIV:D4FB:VGDY:JGOG:FSFD:UYHR:AOPN:2VOA:N6T3:GXEV
WARNING: No swap limit support

root@vagrant-ubuntu-trusty-64:~# docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

~~~

**Comment by thaJeztah** [comment]
I'm not sure we should pick the `-virtual` package over the current one (see for some background this discussion; https://github.com/docker/docker/pull/10860)

Not sure what the problem with pgp is, it could be a hiccup in the key servers?

/cc @tianon

**Comment by tianon** [comment]
Yeah, the `-virtual` package will only work if the user already has installed the main kernel virtual (`linux-image-amd64`), which we can't guarantee, so we take the safer bet that's less likely to cause side-effects (but this is another one of those places where I hate that this script exists -- we can explain how to decide what to do here via docs in a way the script can't automatically handle).

As for the PGP issues, that's bizarre, because `D8576A8BA88D21E9` isn't the short/long ID for `58118E89F3A912897C070ADBF76221572C52609D`; `F76221572C52609D` would be the appropriate long ID for that key.

**Comment by kopchik** [comment]
I just tried to reprodue the PGP issue and it seems to work fine.

Concerning the -virtual package. Please consider adding a link to the bugreport, that might be helpful to know.
