### ISSUE TITLE
PATH not set for images built from scratch

### ISSUE THREAD

**Issue by guoshimin** [docker/docker#19012]
If you build an image from scratch, and don't use the ENV command in the Dockerfile, Env will be null for this image as shown in `docker inspect`.

If you then build another image that inherits from the first one, Env will contain `PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`

This is unintuitive and I didn't find any documentation about it. It makes it impossible to manipulate PATH in a Dockerfile that starts from scratch.

**Comment by guoshimin** [comment]
docker version: 1.9.1
docker info:
Containers: 69
Images: 1075
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1213
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.0-18-generic
Operating System: Ubuntu 15.10
CPUs: 8
Total Memory: 31.42 GiB
Name: ip-172-31-32-162
ID: ULYJ:2JWG:D47W:2X6I:PKCB:C4SV:RDUP:L67V:HPBY:R5NN:4LIX:QJNW
WARNING: No swap limit support

Provide additional environment details (AWS, VirtualBox, physical, etc.): AWS

List the steps to reproduce the issue:
1. Create a Dockerfile that starts from scratch, e.g., 
```
FROM scratch
ADD empty /
```
2. Build a image from it with `docker build`
3. `docker inspect` the image

Describe the results you received: Config.Env is null

Describe the results you expected: Config.Env is `[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin]`

**Comment by duglin** [comment]
There's an easy fix for this, however, I'd like to confirm with @tianon first that an image from "scratch" should still have its PATH set to the default value.  It would seem more consistent that way.

Although, to be honest, there's part of me that wouldn't mind if we didn't default to anything and forced all base images to define the PATH explicitly.  But that's a pretty big change.

**Comment by thaJeztah** [comment]
To me, `FROM scratch` always has been "bring your own config and files", so I'm not sure if Docker should be setting up those env-vars. Also interested in @tianon's opinion here though :+1:

**Comment by duglin** [comment]
The issue here is that we have different logic based on the value of "FROM".  If you choose "scratch" then PATH is not set, which makes some sense.  But if you choose any other value then we'll set a "PATH" for you whether you want it or not.  This means that if you really want no PATH set for people who use your image you have to explicitly add:
```
ENV PATH=""
```
which is not intuitive to me.

It seems like we should be consistent and either default to a well-known PATH for all images (including "scratch") or force people to define a PATH (meaning default to nil).  Note that defaulting the PATH shouldn't really change much since we'll eventually use that default anyway unless someone sets a PATH themselves, which will override the default.

**Comment by duglin** [comment]
Put another way:
```
FROM scratch
CMD1 ...
CMD2 ...
```
will yield different build result than building it via two build steps:
```
FROM scratch
CMD1 ...
```
plus
```
FROM previous
CMD2 ...
```
because now the 2nd final image will have a PATH set while the first build will not.  That inconsistency doesn't seem right.

**Comment by tianon** [comment]
From the legacy perspective, I think we need to set the default PATH for
images FROM scratch regardless of what instructions follow -- in other
words, I think we are a bit late to pull that rug back out ATM, and that
very little would be gained by doing so.

**Comment by tianon** [comment]
(So IMO this is firm bug territory.)

**Comment by thaJeztah** [comment]
Thanks @tianon! In that case (and if you agree), @duglin, do you want to create a PR to set the PATH also for `FROM scratch`?

**Comment by duglin** [comment]
yup - will do...
