### ISSUE TITLE
when exposing a port range, individual iptables rules instead of port range 

### ISSUE THREAD

**Issue by deitch** [docker/docker#19017]
If I have a compose file with a ports section as follows:

````yml
  ports:
    - "50000-51999:50000-51999"
````

I have exposed 2000 ports with a single line. iptables can process this quite efficiently if I use a ports range. Instead, docker installs individual rules for each and every port. Here is a small clip:

````
DEBU[0062] Firewalld passthrough: ipv4, [-t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport 51252 -j ACCEPT]
DEBU[0063] Firewalld passthrough: ipv4, [-t nat -A POSTROUTING -p tcp -s 172.17.0.2 -d 172.17.0.2 --dport 51252 -j MASQUERADE]
DEBU[0063] Firewalld passthrough: ipv4, [-t nat -A DOCKER -p tcp -d 0/0 --dport 51251 -j DNAT --to-destination 172.17.0.2:51251]
DEBU[0063] Firewalld passthrough: ipv4, [-t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport 51251 -j ACCEPT]
DEBU[0063] Firewalld passthrough: ipv4, [-t nat -A POSTROUTING -p tcp -s 172.17.0.2 -d 172.17.0.2 --dport 51251 -j MASQUERADE]
DEBU[0063] Firewalld passthrough: ipv4, [-t nat -A DOCKER -p tcp -d 0/0 --dport 51250 -j DNAT --to-destination 172.17.0.2:51250]
DEBU[0063] Firewalld passthrough: ipv4, [-t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport 51250 -j ACCEPT]
DEBU[0063] Firewalld passthrough: ipv4, [-t nat -A POSTROUTING -p tcp -s 172.17.0.2 -d 172.17.0.2 --dport 51250 -j MASQUERADE]
DEBU[0063] Firewalld passthrough: ipv4, [-t nat -A DOCKER -p tcp -d 0/0 --dport 51249 -j DNAT --to-destination 172.17.0.2:51249]
DEBU[0063] Firewalld passthrough: ipv4, [-t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport 51249 -j ACCEPT]
DEBU[0063] Firewalld passthrough: ipv4, [-t nat -A POSTROUTING -p tcp -s 172.17.0.2 -d 172.17.0.2 --dport 51249 -j MASQUERADE]
DEBU[0063] Firewalld passthrough: ipv4, [-t nat -A DOCKER -p tcp -d 0/0 --dport 51248 -j DNAT --to-destination 172.17.0.2:51248]
````

It creates 2,000 lines. If I am using userland-proxy, it creates thousands of proxy processes. This slows down iptables processing, can make container start take minutes, and causes firewalld to chew up significant CPU until it is loaded.

Is there any reason not to use iptables port ranges when the yml / `-p` option configures it?

**Comment by thaJeztah** [comment]
Thanks for reporting, I think this is a duplicate of https://github.com/docker/docker/issues/11185. Could you check that issue, and close this if you agree?

**Comment by deitch** [comment]
It looks like it. The original issue there is about the userland proxy, with the `--userland-proxy=false` suggested as a solution, but then this comment https://github.com/docker/docker/issues/11185#issuecomment-129085898 says that it still doesn't work because of lack of block port allocation.

I guess we can consider it a duplicate. I will close this in favour that one. Thanks @thaJeztah

**Comment by thaJeztah** [comment]
And, yes, I think it would be nice if we could optimize this :+1:
