### ISSUE TITLE
Image push failed  Error parsing HTTP response: unexpected end of JSON input: ""

### ISSUE THREAD

**Issue by dschinkel** [docker/docker#19010]
Trying to start my docker service again on my Ubuntu AWS EC2 host and get this.  No idea why it's failing on JSON parsing.

Command I ran:

docker push xxxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/ubuntu:xenial

Error I get in the AWS EC2 Host at the terminal:

The push refers to a repository [xxxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/ubuntu] (len: 1)
2bdece1db94a: Image push failed 
Error parsing HTTP response: unexpected end of JSON input: ""

(Note: I x'd out my real AWS account number for obvious security for the post here)

**Comment by dschinkel** [comment]
No idea if this is a bug but here's more info.  Seems like this might be a common issue with AWS and docker but I can't find anything useful to help resolve it.

docker version: 1.9.1, build a34a1d5/1.9.1
docker info: from where?  Please be specific, what file?

**Comment by thaJeztah** [comment]
The output requested is from the `docker version` and `docker info` commands; run those commands, and add the output to your report :-)

In this case, it's possible that this is an issue with the Amazon ECR; have you try contacting their support? I also found this issue on StackOverflow that looks similar; http://stackoverflow.com/questions/34423873/docker-push-to-aws-ecr-private-repo-failing-with-malformed-json

**Comment by dschinkel** [comment]
Yea I've already done other due diligence.  Hoping someone here has seen the error as I haven't got any response from AWS yet.  I have also already seen that stack thread of course and there isn't even a security group called what the answer says worked anymore so that thread is useless.

**Comment by thaJeztah** [comment]
You might want to search for existing issues; https://github.com/docker/docker/issues?utf8=✓&q=is%3Aissue+%22unexpected+end+of+JSON+input%22+

**Comment by roncohen** [comment]
@dschinkel logging in using `aws ecr get-login --region us-east-1` fixed this for me

**Comment by alfonso-cabrera** [comment]
If you are trying to push to an ECR repository, you need to make sure that the ```ecr:BatchCheckLayerAvailability permission``` is also checked. It is not selected by default when using the default push permissions that ECR sets.

**Comment by thaJeztah** [comment]
Based on the discussion above, this doesn't look to be a bug or issue in docker, but in using the correct settings / steps for Amazon ECR.

For that reason, I'll close this issue, bug feel free to continue the discussion here :+1:

**Comment by msumme** [comment]
I am seeing this issue as well while using the 2.1 version of the docker registry (library/registry:2.1), with docker version 1.9.1

**Comment by msumme** [comment]
I originally had a much earlier version of docker and did not have these problems until I got to the 1.9.1 version - not sure if something in my local repository is screwed up on account of that.

**Comment by msumme** [comment]
Also, I had this problem attempting to push to the registry, version 1 with docker 1.9.1.  So it seems unrelated to registry version?

**Comment by mccabe615** [comment]
By default ECR repositories do not have a policy. Once that's created and includes the permissions needed the issue should be resolved.

**Comment by aboutvale** [comment]
+1 @alfonso-cabrera I fixed adding ecr:BatchCheckLayerAvailability permission

**Comment by RomanMinkin** [comment]
`ecr:BatchCheckLayerAvailability` fixed issue for me as well, here is a working wildcard policy example

```js
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ecr:GetAuthorizationToken",
                "ecr:InitiateLayerUpload",
                "ecr:UploadLayerPart",
                "ecr:CompleteLayerUpload",
                "ecr:BatchCheckLayerAvailability"
            ],
            "Resource": "*"
        }
    ]
}
```
