### ISSUE TITLE
Implement `docker update` for changing container restart policy

### ISSUE THREAD

**Issue by rutsky** [docker/docker#19025]
Since `docker update` for changing quotas of containers is merged for 1.10 in #15078 (thanks @hqhq!) it's time to extend it to other useful parameters.

One of the options that I'm missing is the ability to change a container restart policy, which I mentioned in #15078, it also may cover request in #13743 issue.

Something like `docker update --restart=always` to change `RestartPolicy` to `always` would be great.

**Comment by WeiZhang555** [comment]
`docker update` is a new command which I'm not familiar with, so I want to take this as a practice if no one else is doing on this.

#dibs

**Comment by WeiZhang555** [comment]
Hmm, I just realized that this enhancement may be controversial as discussed in #18957, maybe we should wait a little while...

**Comment by thaJeztah** [comment]
@WeiZhang555 there has been some prior discussion on changing restart policies; https://github.com/docker/docker/issues/11008#issuecomment-118985960. At that time, `docker update` did not yet exist (and probably wouldn't solve that use case).

I'm *personally* not against making this property updateable, but perhaps other maintainers have a different opinion :-)

**Comment by WeiZhang555** [comment]
@thaJeztah I agree with you, this can be a useful feature I think.
I'll push a PR to solve this whatever, so that we can get this immediately once we decide to accept this function.

**Comment by thaJeztah** [comment]
@WeiZhang555 thanks! sounds like a plan :)

**Comment by duglin** [comment]
+1 to making it changeable.  Can't think of a reason why we could want to prevent someone from changing their mind after the container has been created.

**Comment by cpuguy83** [comment]
It would be icky to change this while the container is running.

**Comment by duglin** [comment]
Why would changing the restart policy influence a running container?  Seems like it wouldn't have any impact until the container stopped.  Now, the tricky part would be how to handle a container that's already stopped and then you change the restart policy from "no" to something like "always".  Seems we should restart it - not hard but more than just tweaking a flag.

**Comment by thaJeztah** [comment]
@duglin not sure we should go that far. e.g. `docker create -d --restart always` also won't start the container.

**Comment by duglin** [comment]
I guess there's an argument for it to mean "upon next restart act like this..." - ok I can buy that  :-)

**Comment by WeiZhang555** [comment]
So you guys think updating `RestartPolicy` shouldn't influence a running container?  Then things will be easier because changing `RestartPolicy` for running container is tricky just as @cpuguy83 said. 
But I want to make sure this is enough from user's perspective, imagine that user is running a container with `RestartPolicy: always`, then he changes his mind because it's annoying and he's sure he want to change it to `none`, is this a common scenario?  I can't be sure...

**Comment by duglin** [comment]
from a UX perspective I would think that might be a common scenario. I would expect the change to have an immediate impact on the running container's restart policy.  Doesn't seem right to ask them to restart their container first.

**Comment by dmitry** [comment]
I've created containers very long time ago for running development databases, and each time I'm restarting computer I have to run `docker start` with docker pid numbers from `docker ps -a` again and again. To change this behaviour I have to rebuild containers, but for some of them the Dockerfile was lost.

**Comment by WeiZhang555** [comment]
@dmitry I've pushed a PR for this, it would help solve your problem, maybe like `docker update --restart=always [container_id]`, so your container can restart automatically every time you reboot your computer  without rebuilding containers. :smile:

**Comment by dmitry** [comment]
@WeiZhang555 that's :rocket:, thanks!
