### ISSUE TITLE
Proposal: daemon defaults for runtime constraints

### ISSUE THREAD

**Issue by geovanisouza92** [docker/docker#19023]
Today, the resource constraints values is defined on each ```docker run``` command. Thinking about cloud-scale Docker deployment, could be nice to define this defaults on Docker daemon. I think that ```/etc/default/docker``` / ```DOCKER_OPTS``` could be a nice place to configure it. This way, each container would start with right resources.

**Comment by thaJeztah** [comment]
Yes, I thought about this, but not sure if this is something that should be set on the daemon, or something that belongs in orchestration software; both can make sense, depending how you look at it.

Note that there's this proposal, that would allow applying "profiles" to containers; https://github.com/docker/docker/issues/18647

**Comment by geovanisouza92** [comment]
@thaJeztah You're about about the place. Swarm introduced an additional layer about "the right place" questions...

The proposal for profiles is really interesting.

**Comment by HackToday** [comment]
seems orchestration layer is more meaning instead of add other options in docker daemon

**Comment by LK4D4** [comment]
Seems like we'll have daemon-wide seccomp profiles soon. Implementing daemon wide constraints is indeed a task of orchestration.
