### ISSUE TITLE
[1.10] fail to delete containers: readdirent: no such file or directory

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#19022]
I keep getting errors such as `Error response from daemon: Driver overlay failed to remove root filesystem a4fe1d2bb54b3846c6765c0ffcf7dd1cb1567026a2a5920c76c6bbd80115c349: readdirent: no such file or directory
` when trying to delete containers.  I don't have much more info than that.  Due to #19021, I can't really run master right now because it just keeps panicking.  If somebody needs more info, I'll try but it's tough going on master right now.

```
docker version; docker info
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.2
 Git commit:   3df4a51
 Built:        2015-12-31T06:55:37.322373109+00:00
 OS/Arch:      linux/amd64
Containers: 3
Images: 12
Server Version: 1.10.0-dev
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.5
Operating System: Ubuntu 15.10 (containerized)
CPUs: 4
Total Memory: 15.4 GiB
Name: inotmac
ID: HMGD:MCSR:XSNO:I7OW:2H7X:KE3J:XIUK:FEOU:SR4J:PVBZ:B3KW:2C6V
Debug mode (server): true
 File Descriptors: 20
 Goroutines: 38
 System Time: 2015-12-31T08:35:25.482973866-07:00
 EventsListeners: 1
 Init SHA1: 
 Init Path: /home/darren/src/docker/bundles/latest/binary/docker-1.10.0-dev
 Docker Root Dir: /var/lib/docker
Username: ibuildthecloud
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Comment by dmcgowan** [comment]
This appears to be the same as #14474. At first I thought it might be related to the graph/layer refactor but this coming directly from the graph driver. Is this consistently reproducible and does it happen with every container?

**Comment by dmcgowan** [comment]
@ibuildthecloud now that #19021 have you been able to get more info that may be helpful in reproducing?

**Comment by thaJeztah** [comment]
@arnaud given that this is not a regression in 1.9, and we don't have a reproducible case, are you okay with lowering the priority for this?

**Comment by icecrime** [comment]
@sebastiaan SGTM! (cc @thaJeztah :wink:)

**Comment by ibuildthecloud** [comment]
I'm going to close this issue because I can't reproduce and I haven't seen it in the past week (in running on master updating daily).  I'll reopen if I see it again and can provide some more useful info.

**Comment by thaJeztah** [comment]
Thanks @ibuildthecloud!

**Comment by mountkin** [comment]
I think https://github.com/docker/docker/pull/18907 fixed this :smile:

**Comment by thaJeztah** [comment]
@mountkin does that mean https://github.com/docker/docker/issues/14474 should also be resolved?

**Comment by mountkin** [comment]
I think it should be resolved. But it's quite hard to reproduce the problem :cry:

**Comment by suryagaddipati** [comment]
I've seen this error in our ci builds but i haven't been able to setup a consistent test case for reproducing this error.
