### ISSUE TITLE
Adding an info msg for docker pull <image>

### ISSUE THREAD

**Issue by noppelmax** [docker/docker#19031]
Hey,
as the docker hub is very slow for pulling images sometimes. I would suggest adding a message to "docker pull <image>" indicating that the first download was started. It costs me about 2 hours wondering why there is nothing happening, until i wait long enough to see something. I only waited so long, because i was googleing what i'm doing wrong. The first message printed is something like "download completed". What do you guys think about it?

**Comment by thaJeztah** [comment]
Not sure I understand your request, docker pull shows a progress bar (e.g. https://m.youtube.com/watch?v=ED6lN8OqXoI) what change are you requesting to be made?

**Comment by noppelmax** [comment]
If it would look like in the video it would be awesome! That is more, i expected. Sadly, for me it looks different. 
```
core@core01 ~ $ docker info
Containers: 9
Images: 47
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.3.0-coreos
Operating System: CoreOS 877.1.0
CPUs: 4
Total Memory: 3.808 GiB
Name: core01
ID: KL6V:NIKH:77LK:OSTO:M6NG:TZWE:3MDZ:YGSY:SB3N:4BFV:GHWF:ZSWS
core@core01 ~ $ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
gitlab/gitlab-ce    latest              43aef83b9f72        4 days ago          1.33 GB
jenkins             latest              988e2e1b7418        3 weeks ago         707.8 MB
core@core01 ~ $ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   4419fdb-dirty
 Built:        Thu Nov 26 02:50:10 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   4419fdb-dirty
 Built:        Thu Nov 26 02:50:10 UTC 2015
 OS/Arch:      linux/amd64
core@core01 ~ $ uname -a  
Linux core01 4.3.0-coreos #2 SMP Thu Nov 26 02:49:19 UTC 2015 x86_64 Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz GenuineIntel GNU/Linux
core@core01 ~ $ docker pull ubuntu 
Using default tag: latest
```
This last line lasts for about 10 minutes. Then it prints:
```
Pulling repository docker.io/library/ubuntu
d55e68e6cc9c: Download complete 
9377ad319b00: Download complete 
a82f81f25750: Download complete 
b207c06aba70: Download complete 
Status: Downloaded newer image for ubuntu:latest
docker.io/library/ubuntu: this image was pulled from a legacy registry.  Important: This registry version will not be supported in future versions of docker.
```
I switched to CoreOS Beta because i through it would solve it. Maybe it's somek kind of bug? Hmm...

**Comment by noppelmax** [comment]
I access the server via ssh, but that is not a problem, isn't it?

**Comment by thaJeztah** [comment]
CoreOS distributes their own builds of docker, and apply some modifications, so I think you should try contacting them first; based on the git commit version `4419fdb-dirty`, this is the commit they built from (and applied their patches to it); https://github.com/coreos/docker/commit/4419fdb, perhaps that's what makes a difference here? Can you open this issue in the CoreOS issue tracker?

**Comment by noppelmax** [comment]
Okay, thanks. Maybe thats it

**Comment by crawford** [comment]
We ship a [minimal set of patches](https://github.com/docker/docker/compare/release/v1.9...coreos:coreos-1.9.1) to the Docker we ship in CoreOS. https://github.com/coreos/docker/commit/4419fdb was reverted because it broke socket activation and our fix was [accepted upstream](https://github.com/docker/docker/pull/18213). FWIW, Docker 1.9.1 on CoreOS is behaving the same way as Docker 1.7.1 on my Gentoo system. I don't see the animated progress bar, but I do see the percentages.

**Comment by thaJeztah** [comment]
@crawford is that on a "fresh" pull (i.e., an image that doesn't exist yet locally)?

**Comment by crawford** [comment]
@thaJeztah yes. I cleaned up before I ran the test. `docker rmi $(docker images -aq)`

**Comment by thaJeztah** [comment]
Strange.

@aaronlehmann any idea here why progress bars are not visible?

**Comment by crawford** [comment]
It looks like my terminal was too thin.

```
$ stty -a
speed 38400 baud; rows 58; columns 95; line = 0;
...
```

Apparently, 95 columns is not enough... After widening it, I see the progress bars on both my machine and in CoreOS.

**Comment by thaJeztah** [comment]
ah, interesting :)

**Comment by aaronlehmann** [comment]
Ah, yes. I've been confused by this too in the past. Ideally the progress bar would be formatted in a way that works with 80 column terminals. Not showing it unless the terminal is significantly larger is weird, to say the least.
