### ISSUE TITLE
stats api returns 0

### ISSUE THREAD

**Issue by Aamir010** [docker/docker#19042]
<img width="600" alt="screen shot 2016-01-04 at 12 41 04 pm" src="https://cloud.githubusercontent.com/assets/13231166/12084972/767f73f8-b2e0-11e5-87d8-a5f0911788d3.png">

**Comment by Aamir010** [comment]
docker version : 
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

docker info:

Containers: 4
Images: 4
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 16
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 489.2 MiB
ID: AS66:UGSR:3OVA:5IRB:LWB2:PSSR:66GG:ZSLI:QC3S:5DHW:VUYQ:O7KP
WARNING: No swap limit support

Steps perform : 
echo -ne "GET /containers/9a57fcdd6db2/stats HTTP/1.1\r\n\r\n" | sudo nc -U /var/run/docker.sock

Result received : 
HTTP/1.1 200 OK
Server: Docker/1.9.1 (linux)
Date: Sun, 03 Jan 2016 16:38:01 GMT
Content-Type: text/plain; charset=utf-8
Transfer-Encoding: chunked

0

**Comment by thaJeztah** [comment]
The "stats" endpoint is streaming, have you tried adding `-q -1`?

```bash
echo -ne "GET /containers/9a57fcdd6db2/stats HTTP/1.1\r\n\r\n" | nc -q -1 -U /var/run/docker.sock
```

**Comment by cpuguy83** [comment]
Yes, this is the normal response.
When streaming is on (the default), it sends the response headers and then streams line delimited json to the client.

**Comment by thaJeztah** [comment]
I'll close this issue, because this is working as expected, but feel free to comment after I've closed

**Comment by Aamir010** [comment]
yes, its working now
