### ISSUE TITLE
add shiplift to remote api client library list

### ISSUE THREAD

**Issue by softprops** [docker/docker#19047]
I would like to add https://github.com/softprops/shiplift to the list of remote api client libraries for Rust programming language. The docs on that page said to open an docs issue in this repo so here goes...

**Comment by thaJeztah** [comment]
@softprops can you open a pull-request to add it to the list? The Markdown file that's used to generate that page can be found in this repository; https://github.com/docker/docker/blob/master/docs/reference/api/remote_api_client_libraries.md

**Comment by softprops** [comment]
sure thing. here you go https://github.com/docker/docker/pull/19070/

**Comment by unclejack** [comment]
I'm closing this as #19070 has been merged.
