### ISSUE TITLE
docker start will always allocate new network

### ISSUE THREAD

**Issue by AdoHe** [docker/docker#19040]
FYI. There is such a use case: I use `kill -9` to kill the docker daemon, as for `SIGKILL`, the daemon will not do any clean up functionality, so the `config.json` file for each container will not get updated, the network info is kept. Then I restart the docker daemon, the daemon will call the `restore` procedure to restart containers, for the container start process, it will always call `allocateNetwork` method but ignore the `config.json`. I am wondering is this correct? What if I want to keep the containers' network info when the daemon get restarted?

**Comment by wenchma** [comment]
@AdoHe yes, if you kill the docker daemon, it truly did not cleanup anything. When you restart the daemon, it will allocateNetwork, and not update config.json, but if you start the related  container, `config.json` will be updated correspondingly . My understanding, the container is `Existed` status, its config file is not effective  of course.

**Comment by cpuguy83** [comment]
@AdoHe When the daemon restarts, Docker restarts all containers (actually it does SIGKILL to all running containers, then starts them back up if there is a restart policy).
Restarted containers do not keep network info.

There is also some network cleanup that happens on daemon restart.

**Comment by AdoHe** [comment]
@cpuguy83 ok, I think I know that.
