### ISSUE TITLE
man docker-import: significant space missing from command

### ISSUE THREAD

**Issue by sourcejedi** [docker/docker#19046]
Markdown is OK: `Usage: docker import file|URL|- [REPOSITORY[:TAG]]`

Generated manpage is confusingly wrong:

    docker    import [-c|--change[=[]]] [-m|--message[=MESSAGE]] [--help]
    file|URL|-[REPOSITORY[:TAG]]

because it misses the space between `file|URL|-` and `[REPOSITORY[:TAG]]`.

On a normal project I'd try to debug this, but the docker docs build is a bit mysterious to me, sorry.

**Comment by sourcejedi** [comment]
Ah, I meant to say my Docker version:

docker-1.9.1-4.git6ec29ef.fc23.x86_64

and that I verified the problem is present in 

https://yum.dockerproject.org/repo/main/fedora/23/Packages/docker-engine-1.9.1-1.fc23.x86_64.rpm

**Comment by thaJeztah** [comment]
Actually, it looks like the Markdown that's used is missing the space; the space got accidentally removed here; https://github.com/docker/docker/blame/dd43c23812612987c0cbda0d5c489578ed66d09d/man/docker-import.1.md#L12

If you're interested in creating a pull-request to fix that, let me know :+1: thanks for reporting!

**Comment by aditirajagopal** [comment]
@sourcejedi - I can take care of this if you want!

**Comment by sourcejedi** [comment]
Weird. I was looking in `docs/reference/commandline/import.md`, which has the space even in  dd43c23812612987c0cbda0d5c489578ed66d09d. This is even more mysterious to me :)

I _guess_ you're right about it being an accident.  But it looks like the usage samples are supposed to be generated by running the programs, by `docs-update.py`.  Ideally we should re-run that and check what happens to the spacing, right?  Of course docs-update.py was squirreled away in the `docs/base` image on Docker Hub.

@aditirajagopal If you want to follow this up, you're very welcome to do so.  I don't plan on doing it myself.

**Comment by thaJeztah** [comment]
@sourcejedi I think the `docs-update.py` is no longer used. w.r.t. the `docs/reference/commandline/import.md` file; that file is used to generate the *online* documentation at https://docs.docker.com/engine/reference/commandline/import/. The *man pages* are generated from the file located here; https://github.com/docker/docker/blob/master/man/docker-import.1.md

**Comment by sourcejedi** [comment]
Agreed, looks like the `docs-update.py` script was not moved but just deleted. Thanks again.

**Comment by vdemeester** [comment]
I'm going to close this one as the man page looks good now :angel:
