### ISSUE TITLE
"Stderr: Unable to find image 'distro' locally" using Docker 1.9.1 as a provider for Vagrant 1.7.4

### ISSUE THREAD

**Issue by bmfallon** [docker/docker#19049]
Hello, I have the following images (names slightly changed due to enterprise setting):

⇒  docker images
REPOSITORY              TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
distro/fromtomee       latest              17dbc9a93d2b        12 days ago         658 MB
centos7/tomee           latest              e55a49fbaa87        12 days ago         614.4 MB

I then run:
⇒  vagrant up --provider=docker

and get the following output:
Bringing machine 'default' up with 'docker' provider...
==> default: Docker host is required. One will be created if necessary...
    default: Docker host VM is already ready.
==> default: Syncing folders to the host VM...
    default: The machine you're rsyncing folders to is configured to use
    default: password-based authentication. Vagrant can't script rsync to automatically
    default: enter this password, so you'll likely be prompted for a password
    default: shortly.
    default:
    default: If you don't want to have to do this, please enable automatic
    default: key insertion using `config.ssh.insert_key`.
    default: Rsyncing folder: /Users/bfallon/.m2/ => /var/lib/docker/docker_1451917171_69785
docker@127.0.0.1's password:
    default: Rsyncing folder: /Users/bfallon/projects/repo/distro/ => /var/lib/docker/docker_1451917171_23838
docker@127.0.0.1's password:
==> default: Warning: When using a remote Docker host, forwarded ports will NOT be
==> default: immediately available on your machine. They will still be forwarded on
==> default: the remote machine, however, so if you have a way to access the remote
==> default: machine, then you should be able to access those ports there. This is
==> default: not an error, it is only an informational message.
==> default: Creating the container...
    default:   Name: distro_default_1451917323
    default:  Image: distro/fromtomee
    default: Volume: /var/lib/docker/docker_1451917171_69785:/m2
    default: Volume: /var/lib/docker/docker_1451917171_23838:/vagrant
    default:   Port: 7126:80
    default:   Port: 7127:443
    default:   Port: 7128:8080
    default:   Port: 7129:8443
    default:   Port: 7130:8787
A Docker command executed by Vagrant didn't complete successfully!
The command run along with the output from the command is shown
below.

Command: "docker" "run" "--name" "distro_default_1451917323" "-d" "-p" "7126:80" "-p" "7127:443" "-p" "7128:8080" "-p" "7129:8443" "-p" "7130:8787" "-v" "/var/lib/docker/docker_1451917171_69785:/m2" "-v" "/var/lib/docker/docker_1451917171_23838:/vagrant" "distro/fromtomee"

Stderr: Unable to find image 'distro/fromtomee:latest' locally
Pulling repository distro/fromtomee
Error: image distro/fromtomee:latest not found

Stdout:

Now, we are just starting to move to Docker as an org, so we do not have any kind of private registry, however, the images is created locally as you can see above.

I am running on OS X Yosemite.

**Comment by cpuguy83** [comment]
Are you sure vagrant is talking to the same docker daemon is your shell?

**Comment by bmfallon** [comment]
I do believe so, I have been using the default daemon provided when using the Docker Quickstart Terminal and didn't specify to have Vagrant look at anything different.

**Comment by cpuguy83** [comment]
I believe vagrant sets up it's own stuff... but I'm not sure.

**Comment by bmfallon** [comment]
I could be wrong, but I had thought Vagrant automatically points to that default Docker daemon.  Unfortunately this is my first time using Docker as a provider with Vagrant and can't find much online to solve this issue.

**Comment by cpuguy83** [comment]
Yep, it does... see the "Host VM" section here: https://docs.vagrantup.com/v2/docker/basics.html

**Comment by bmfallon** [comment]
Ahh you would be correct, thanks for that.
