### ISSUE TITLE
Docker unable to use applications which use SIOCGIFNAME

### ISSUE THREAD

**Issue by owenhaynes** [docker/docker#19052]
Hi,

Docker version 1.9.1, build a34a1d5
Os Rhel 7
Linux 3.10.0-327.el7.x86_64 #1 SMP Thu Oct 29 17:29:29 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

Trying to run some applications in docker which do
ioctl(3, SIOCGIFNAME, {ifr_index=1, ifr_name="lo"}) = 0
and 
ioctl(3, SIOCGIFHWADDR, {ifr_name="lo", ifr_hwaddr=00:00:00:00:00:00})

these commands fail when the command get past the loop back device

socket(PF_INET, SOCK_STREAM, IPPROTO_IP) = 3
ioctl(3, SIOCGIFNAME, {ifr_index=0, ifr_name=???}) = -1 ENODEV (No such device)
ioctl(3, SIOCGIFNAME, {ifr_index=1, ifr_name="lo"}) = 0
ioctl(3, SIOCGIFHWADDR, {ifr_name="lo", ifr_hwaddr=00:00:00:00:00:00}) = 0
ioctl(3, SIOCGIFNAME, {ifr_index=2, ifr_name=???}) = -1 ENODEV (No such device)
ioctl(3, SIOCGIFNAME, {ifr_index=3, ifr_name=???}) = -1 ENODEV (No such device)
ioctl(3, SIOCGIFNAME, {ifr_index=4, ifr_name=???}) = -1 ENODEV (No such device)
ioctl(3, SIOCGIFNAME, {ifr_index=5, ifr_name=???}) = -1 ENODEV (No such device)
ioctl(3, SIOCGIFNAME, {ifr_index=6, ifr_name=???}) = -1 ENODEV (No such device)
ioctl(3, SIOCGIFNAME, {ifr_index=7, ifr_name=???}) = -1 ENODEV (No such device)

The application wants to get the SIOCGIFNAME of eth0 and its SIOCGIFHWADDR

Expected output is something like

socket(PF_INET, SOCK_STREAM, IPPROTO_IP) = 3
ioctl(3, SIOCGIFNAME, {ifr_index=0, ifr_name=???}) = -1 ENODEV (No such device)
ioctl(3, SIOCGIFNAME, {ifr_index=1, ifr_name="lo"}) = 0
ioctl(3, SIOCGIFHWADDR, {ifr_name="lo", ifr_hwaddr=00:00:00:00:00:00}) = 0
ioctl(3, SIOCGIFNAME, {ifr_index=2, ifr_name="eno1"}) = 0
ioctl(3, SIOCGIFHWADDR, {ifr_name="eno1", ifr_hwaddr=MAC_ADDRESS}) = 0
ioctl(3, SIOCGIFNAME, {ifr_index=3, ifr_name="enp1s0"}) = 0
ioctl(3, SIOCGIFHWADDR, {ifr_name="enp1s0", ifr_hwaddr=MAC_ADDRESS}) = 0
ioctl(3, SIOCGIFNAME, {ifr_index=4, ifr_name="local"}) = 0
ioctl(3, SIOCGIFHWADDR, {ifr_name="local", ifr_hwaddr=MAC_ADDRESS) = 0
ioctl(3, SIOCGIFNAME, {ifr_index=5, ifr_name="virbr1"}) = 0
ioctl(3, SIOCGIFHWADDR, {ifr_name="virbr1", ifr_hwaddr=MAC_ADDRESS) = 0
ioctl(3, SIOCGIFNAME, {ifr_index=6, ifr_name="virbr1-nic"}) = 0
ioctl(3, SIOCGIFHWADDR, {ifr_name="virbr1-nic", ifr_hwaddr=MAC_ADDRESS}) = 0
ioctl(3, SIOCGIFNAME, {ifr_index=7, ifr_name="virbr0"}) = 0
ioctl(3, SIOCGIFHWADDR, {ifr_name="virbr0", ifr_hwaddr=MAC_ADDRESS}) = 0
close(3)

**Comment by cpuguy83** [comment]
https://lists.linuxcontainers.org/pipermail/lxc-users/2012-May/003672.html seems relavent.

**Comment by LK4D4** [comment]
@cpuguy83 Do you know if this is still issue?

**Comment by cpuguy83** [comment]
I really don't know anything about this, maybe someone from libnetwork can help?

**Comment by cpuguy83** [comment]
ping @aboch

**Comment by aboch** [comment]
@owenhaynes The interface indices of the containers' interfaces are not contiguos, as from the discussion @cpuguy83 linked. 

And they seem to increment at each container run:

```
$ docker run --rm busybox ip link show eth0
17: eth0@if18: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue 
    link/ether 02:42:ac:11:00:04 brd ff:ff:ff:ff:ff:ff
$ docker run --rm busybox ip link show eth0
19: eth0@if20: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue 
    link/ether 02:42:ac:11:00:04 brd ff:ff:ff:ff:ff:ff
}

Also take a  look at http://stackoverflow.com/questions/14264371/how-to-get-nic-details-from-a-c-program where they suggest to first retrieve a list of interfaces then iterate through their indices.

From what I understand, I do not think this is a docker issue.

**Comment by cpuguy83** [comment]
Thanks for looking @aboch.

Going to close this one out, but feel free to continue the discussion.
Thanks!
