### ISSUE TITLE
ISSUE: dm.basesize not taking effect as command line parameter

### ISSUE THREAD

**Issue by beetree** [docker/docker#19061]
I'm starting the daemon with `docker daemon --storage-opt dm.basesize=10G` expecting to see `Base Device Size: 10GB` from `docker info` but instead I see `Base Device Size: 2.147 GB`.

Here is a full session:
```
 # docker info; (docker daemon --storage-opt dm.basesize=10G &); sleep 5; docker info
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
INFO[0000] API listen on /var/run/docker.sock
WARN[0000] Usage of loopback devices is strongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use `man docker` to refer to dm.thinpooldev section.
INFO[0000] [graphdriver] using prior storage driver "devicemapper"
INFO[0000] Firewalld running: false
INFO[0000] Default bridge (docker0) is assigned with an IP address 172.17.0.1/16. Daemon option --bip can be used to set a preferred IP address
WARN[0000] Your kernel does not support swap memory limit.
INFO[0000] Loading containers: start.
....WARN[0000] signal: killed
ERRO[0020] Error unmounting device dc173cc03cc87c51a24463f89533352a79885d68a208805ba447fee6420f2362: Device is Busy
WARN[0020] failed to cleanup ipc mounts:
failed to umount /var/lib/docker/containers/dc173cc03cc87c51a24463f89533352a79885d68a208805ba447fee6420f2362/shm: invalid argument
failed to umount /var/lib/docker/containers/dc173cc03cc87c51a24463f89533352a79885d68a208805ba447fee6420f2362/mqueue: invalid argument
ERRO[0020] Error unmounting device dc173cc03cc87c51a24463f89533352a79885d68a208805ba447fee6420f2362: UnmountDevice: device not-mounted id dc173cc03cc87c51a24463f89533352a79885d68a208805ba447fee6420f2362
ERRO[0020] Failed to start container dc173cc03cc87c51a24463f89533352a79885d68a208805ba447fee6420f2362: [8] System error: Unit docker-dc173cc03cc87c51a24463f89533352a79885d68a208805ba447fee6420f2362.scope already exists.

INFO[0020] Loading containers: done.
INFO[0020] Daemon has completed initialization
INFO[0020] Docker daemon                                 commit=a34a1d5 execdriver=native-0.2 graphdriver=devicemapper version=1.9.1
INFO[0020] GET /v1.21/info
Containers: 2
Images: 26
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-9:2-4458588-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 2.147 GB
 Backing Filesystem:
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 578.6 MB
 Data Space Total: 214.7 GB
 Data Space Available: 214.2 GB
 Metadata Space Used: 1.917 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.99 (2015-06-20)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.8-031908-generic
Operating System: Ubuntu 15.10
CPUs: 12
Total Memory: 125.9 GiB
Name: Ubuntu-1510-wily-64-minimal
ID: AHH6:DLUD:GQ5F:YOP6:GYQS:N6WK:GAGT:A6D4:TM5X:427F:IVJW:IIFQ
WARNING: No swap limit support
```

And other system info:
```
# docker version
INFO[0049] GET /v1.21/version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64

# uname -a
Linux Ubuntu-1510-wily-64-minimal 3.19.8-031908-generic #201505110938 SMP Mon May 11 13:39:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

This made me think that perhaps command line arguments to the "docker daemon" are lower priority than settings in some other configuration file so I put the same data into the config file:
```
# cat /etc/default/docker
# Docker Upstart and SysVinit configuration file

# Customize location of Docker binary (especially for development testing).
#DOCKER="/usr/local/bin/docker"

# Use DOCKER_OPTS to modify the daemon startup options.
DOCKER_OPTS="--storage-opt dm.basesize=10G"

# If you need Docker to use an HTTP proxy, it can also be specified here.
#export http_proxy="http://127.0.0.1:3128/"

# This is also a handy place to tweak where Docker's temporary files go.
#export TMPDIR="/mnt/bigdrive/docker-tmp"
```

Why is it not accepting my 10G parameter?

Thanks!

**Comment by beetree** [comment]
The following solves it:
```
systemctl stop docker
rm -rf /var/lib/docker/
reboot
...
systemctl start
```
Can the dm.basesize only be changed if removing certain files in /var/lib/docker? If so, any way of avoiding wiping everything to change this?

Thanks!

**Comment by beetree** [comment]
I got confirmed on a different thread that you indeed have to wipe everything in /var/lib/docker to reset this. Closing this issue...

**Comment by sellers** [comment]
The above rm-rf /var/lib/docker removal was also needed for my experience on an Ubuntu LTS system.   /etc/default/docker options would not work for --storage-opt dm.basesize=XX and caused docker to go into a restart loop.   rm (or mv) of the above resolved that loop.

**Comment by thaJeztah** [comment]
@sellers depending on what version of Ubuntu you're running, `/etc/default/docker` may not be in use; that file is only used for systems running Upstart, but not on systems using `systemd` (see the comment at the top of that file; https://github.com/docker/docker/blob/v1.12.5/contrib/init/sysvinit-debian/docker.default#L1-L9)

The easiest way to configure daemon options is using a `daemon.json` configuration file; that file is used independent of the init system you use (and even works if manually starting the daemon). See https://docs.docker.com/engine/reference/commandline/dockerd/#/daemon-configuration-file for more information on that

**Comment by sellers** [comment]
@thaJeztah  thanks for the tip, I was able to get the daemon.json file to do most of my configurations but the "storage-opts": ["dm.basesize=1G"] does not seem to be friendly.   I've tried a few JSON formats for that value (e.g. [{dm.basesize": "1G"}] ) and it fails to start.   Is there a reference to the proper format somewhere?

**Comment by sellers** [comment]
For the good of the order, I found this was a problem with my ubuntu /etc/init/docker.conf which caused issues with the startup.   I had to modify that docker.conf to not make references to DOCKER_OPTS which appears it was a conflict. 

for those interested, my format was

```
 "storage-opts": [
    "dm.basesize = 1G"
  ],
  "storage-driver": "devicemapper"

```

**Comment by daixiang0** [comment]
I use docker 17.06.2-ce and find even set basesize in daemon.json, it still shows past size in container.
After i clean up all data(i use devicemapper), this option works.
Clean all data looks so ugly which i think can optimize.
