### ISSUE TITLE
Cannot stop container; status gets out of sync with LXC

### ISSUE THREAD

**Issue by slnovak** [docker/docker#1906]
I came across an interesting behavior where a Docker container's status got out of sync with an lxc container.

1. `docker ps` showed my container (`ae23c705afdb`) with a status of running. However, whenever I try running `docker kill` or `docker stop`, the command hangs indefinitely. `docker rm` says that it cannot remove a container that is running.

2. `docker inspect ae23c705afdb` confirmed the running state and showed a PID of 11780.

3. `ps aux | grep 11780` showed a process that was running (`lxc-start -n ae23c705afdbbcfcd723c7bb17fbdbc7c8632da41e5e8c38bbf714a701b5b536 -f /var/lib/docker/containers/...`), but it's state is shown as `D`, or "uninterruptible sleep". This process thus does not respond to any interrupts.

4. `lxc-list` does not show the corresponding lxc container running, so `lxc-kill xxx` does not work.

I ended up just having to do a reboot. Any thoughts on this?

**Comment by jfrazelle** [comment]
can you try with the latest version of docker and lxc 1.0.7

**Comment by jfrazelle** [comment]
closing as stale please ping me with details to reproduce on latest and I will reopen

**Comment by sadovnikov** [comment]
Seems I can reproduce it consistently with
```
MacBook-Pro:mesos-logstash vik$ docker --version
Docker version 1.9.1, build a34a1d5
MacBook-Pro:mesos-logstash vik$ docker-machine --version
docker-machine version 0.5.1 (7e8e38e)
```

Container, which image is based on `ubuntu:14.04`, starts with Java process as an entry point. Based on logs from the process, it completes. However the container remains `Up`. Attempts to execute any commands in the running container by `docker exec` return without doing anything. Attempts to kill the container hang. 

From SSH of docker-machine VM

```
docker@minimesos:~$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

docker@minimesos:~$ docker ps
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS               NAMES
43a263b7dc87        containersol/minimesos:latest   "java -Dminimesos.hos"   16 minutes ago      Up 16 minutes                           backstabbing_brattain
docker@minimesos:~$ ps -eaf | grep lxc
docker   12769 12421  0 11:25 pts/0    00:00:00 grep lxc
```

What should I do to get some useful debug information?

**Comment by thaJeztah** [comment]
@sadovnikov are you using the LXC driver, or the native driver?

**Comment by sadovnikov** [comment]
I'm not very familiar with these technologies yet. The command I use to create docker-machine VM is `docker-machine create -d virtualbox --virtualbox-memory 2048 --virtualbox-cpu-count 1 minimesos`. It creates
```
Boot2Docker version 1.9.1, build master : cef800b - Fri Nov 20 19:33:59 UTC 2015
Docker version 1.9.1, build a34a1d5
```

How do I know LXC driver?

**Comment by thaJeztah** [comment]
@sadovnikov in that case, you're using the default (native) driver, so your issue is probably unrelated to the issue discussed here
