### ISSUE TITLE
graphdriver - prior storage driver \“btrfs\” failed: prerequisites for driver not satisfied (wrong filesystem?)

### ISSUE THREAD

**Issue by mictadlo** [docker/docker#19065]
Hello, I tried to use the following command:

    > docker run -d -p 8080:80 -p 8800:8800 -p 9002:9002 --privileged=true -e "GALAXY_LOGGING=full" bgruening/galaxy-stable 

and received the following docker error massages (http://0.0.0.0:9002):

    time="2016-01-04T10:31:04.992632146Z" level=error msg="[graphdriver] prior storage driver \"btrfs\" failed: prerequisites for driver not satisfied (wrong filesystem?)" 
    time="2016-01-04T10:31:04.992777695Z" level=fatal msg="Error starting daemon: error initializing graphdriver: prerequisites for driver not satisfied (wrong filesystem?)" 
    time="2016-01-04T10:31:06.329986754Z" level=error msg="[graphdriver] prior storage driver \"btrfs\" failed: prerequisites for driver not satisfied (wrong filesystem?)" 
    time="2016-01-04T10:31:06.330140404Z" level=fatal msg="Error starting daemon: error initializing graphdriver: prerequisites for driver not satisfied (wrong filesystem?)" 
    time="2016-01-04T10:31:09.000757480Z" level=error msg="[graphdriver] prior storage driver \"btrfs\" failed: prerequisites for driver not satisfied (wrong filesystem?)" 
    time="2016-01-04T10:31:09.000911410Z" level=fatal msg="Error starting daemon: error initializing graphdriver: prerequisites for driver not satisfied (wrong filesystem?)" 

Similar error I get with:

    > sudo docker -s btrfs -d -D 
    Warning: '-d' is deprecated, it will be removed soon. See usage.
    WARN[0000] please use 'docker daemon' instead.          
    DEBU[0000] docker group found. gid: 999                 
    DEBU[0000] Server created for HTTP on unix (/var/run/docker.sock) 
    DEBU[0000] [graphdriver] trying provided driver "btrfs" 
    FATA[0000] Error starting daemon: error initializing graphdriver: prerequisites for driver not satisfied (wrong filesystem?)

I am using Linux Mint 17.2 and docker 1.9.1 (build a34a1d5) in a VirtualBox. My host OS is CentOS 6.6.

    $ uname -a
    Linux galaxy-VirtualBox 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

I also updated the kernel with *sudo apt-get install linux-headers-4.2 linux-image-4.2*, but it still did not solve the problem

    $ uname -a
    Linux galaxy-VirtualBox 4.2.0-22-lowlatency #27~14.04.1-Ubuntu SMP PREEMPT Fri Dec 18 12:20:01 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

    > df -hT
    Filesystem     Type      Size  Used Avail Use% Mounted on
    udev           devtmpfs  6.1G  4.0K  6.1G   1% /dev
    tmpfs          tmpfs     1.3G  1.2M  1.3G   1% /run
    /dev/sda1      ext4      1.9T  122G  1.7T   7% /
    none           tmpfs     4.0K     0  4.0K   0% /sys/fs/cgroup
    none           tmpfs     5.0M     0  5.0M   0% /run/lock
    none           tmpfs     6.2G  1.5M  6.2G   1% /run/shm
    none           tmpfs     100M   32K  100M   1% /run/user

    $ docker info
    Containers: 80
    Images: 232
    Server Version: 1.9.1
    Storage Driver: aufs
    Root Dir: /var/lib/docker/aufs
    Backing Filesystem: extfs
    Dirs: 392
    Dirperm1 Supported: true
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 4.2.0-22-lowlatency
    Operating System: Ubuntu 14.04.3 LTS
    CPUs: 6
    Total Memory: 12.23 GiB
    Name: galaxy-VirtualBox
    ID: 7YSZ:MWKF:XJV6:QDJ3:CEA5:IQ2Y:DNJY:RGZB:7CIZ:RMGG:RI5T:XP23
    WARNING: No swap limit support

    $ docker version
    Client:
    Version:      1.9.1
    API version:  1.21
    Go version:   go1.4.3
    Git commit:   a34a1d5
    Built:        Fri Nov 20 17:56:04 UTC 2015
    OS/Arch:      linux/amd64

    Server:
    Version:      1.9.1
    API version:  1.21
    Go version:   go1.4.3
    Git commit:   a34a1d5
    Built:        Fri Nov 20 17:56:04 UTC 2015
    OS/Arch:      linux/amd64

I also posted the problem to http://stackoverflow.com/questions/30669359/docker-with-btrfs-ubuntu .

What did I do wrong?

**Comment by cpuguy83** [comment]
In order to use btrfs, docker storage dir must be on a btrfs partition.

**Comment by thaJeztah** [comment]
For more information on using the btrfs storage driver, please refer to this section of the documentation; https://docs.docker.com/engine/userguide/storagedriver/btrfs-driver/
