### ISSUE TITLE
man pages contain only a subset of the information in the commands ref

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#19088]
In many cases, the man pages are not "self contained" in that they don't contain the full documentation for a command.  All the information is only available on docs.docker.com. (Moved from #19034)

Fixing this problem should be part of a generation task.

**Comment by LK4D4** [comment]
ping @thaJeztah @vdemeester

**Comment by thaJeztah** [comment]
closing this in favor of https://github.com/docker/docker/issues/25615
