### ISSUE TITLE
Devicemapper - loopback file for the “data” device significantly grows during container usage

### ISSUE THREAD

**Issue by karolzmuda** [docker/docker#19083]
Hi!

I've got docker running on remote server with currently only one container running. This container contains Elasticsearch, Logstash and Kibana and is used for collecting and analysis of logs from remote apps. The size of `/var` mount point is 100G.

The problem is that while our data occupies max 10G (mounted as docker volume under `/var/lib/docker/volumes`), devicemapper loopback file for the “data” located in `var/lib/docker/devicemapper/devicemapper/data` keeps growing during container usage until it fills all the remaining space and doesn't allow our log data to be collected (last time this file increased it's size to around 80G).

During this no additional images are downloaded/created - only one container is constantly running.

Is it normal that devicemapper loopback file grows during normal container usage?

I am aware that devicemapper loopback file has the maximum size of 100G and that it also can be decreased/increased. But what happens if I decrease its max size to let's say 50G and then devicemapper loopback file reaches this size?

I am also aware of #3182 issue (Device-mapper does not release free space from removed images) but does this issue also has something to do with running containers without image removal in the meantime?

So final question is:
What should I do to prevent devicemapper from eating all my free space from `/var` mount point?

`Red Hat Enterprise Linux Server release 7.1 (Maipo)`

`docker version`:
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:
```
Containers: 7
Images: 46
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-253:2-918016-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 16.89 GB
 Data Space Total: 107.4 GB
 Data Space Available: 71.13 GB
 Metadata Space Used: 11.15 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.136 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.el7.x86_64
Operating System: Red Hat Enterprise Linux
CPUs: 8
Total Memory: 29.29 GiB
Name: ondemand2.qrios.com
ID: UJXV:6PT6:LTEB:JOLT:BHX2:SQKO:WCZO:HCSL:BAAF:J3TZ:F5UZ:3C54
Username: coutopl
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled`
```

**Comment by thaJeztah** [comment]
I think this is a duplicate of https://github.com/docker/docker/issues/18867. Can you check that issue, and close this one if you think it's a duplicate?

**Comment by karolzmuda** [comment]
Yeah, it seems that you are right. I'll link my case in this issue to provide more data.

**Comment by thaJeztah** [comment]
Thanks!
