### ISSUE TITLE
how can I refresh character devices inside a container ?

### ISSUE THREAD

**Issue by bernardgut** [docker/docker#19087]
The problem doesn't seem very complicated yet I couldn't find an answer anywhere :

Assume some privileged guests, with availability requirements, running in collocation on some host. The host loads some kernel module xyz that provides an interface in /dev/x. I can now see /dev/x on the host but not on the guests. How can I make /dev/x appear on the guests ? 

Right now I have to restart guests to see changes in /dev, which not very practical.

I have seen that when I mount a filesystem with '-v' this one is automatically mirrored between guest(s)/host. However, I don't know how docker manages the /dev mappings in the background but it is somewhat not mirrored. I am not sure it is a good idea to '-v'-override /dev on the guest...

Note : I can provide more details on the exact module and config but I assume it is irrelevant to this problem.

EDIT: (is this a bug ?)
thanks

**Comment by phemmer** [comment]
`-v /dev:/dev` is supported: https://github.com/docker/docker/pull/16639

**Comment by Aamir010** [comment]
-v /dev/xyz:/dev/xyz:ro . This will mount your volume in ReadOnly mode.

**Comment by thaJeztah** [comment]
I'll close this issue, because this should be working with the example @phemmer gave, but feel free to comment here if it's not working for you

**Comment by bernardgut** [comment]
yes thanks it worked

Bernard A. Gütermann
Software Engineer R & D
CEN - Energy Center
EPFL, CH-1015 Lausanne
