### ISSUE TITLE
Proposal: Add network ID to container inspect

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#19089]
Network names are not guaranteed to be unique (https://github.com/docker/docker/issues/18864). This is by design (https://github.com/docker/docker/issues/18864#issuecomment-167006094), but currently, it's not possible to identify *which* network a container is attached to.

I suggest to add the network ID to the output of docker inspect.

**Comment by wenchma** [comment]
I think this is a good idea to use network id instead of name, like network inspect , it uses container-id to differentiate containers.  @thaJeztah  if ok, I can claim this  :smile:

**Comment by thaJeztah** [comment]
@wenchma I think the idea is to add the network-id to the *details* / *properties*. Replacing the name with the ID as "key" would be a breaking change (and a lot more difficult to, e.g. `docker inspect --format ...` to obtain the IP-address for, for example, the `bridge` network). Currently, a container cannot join two networks with the same name, so I think we should keep that as-is for now, so only add it to the details/properties of a network.

Would be great though if you can work on it :+1:

**Comment by thaJeztah** [comment]
So, something like:

```json
  "Networks": {
            "foobar": {
                "NetworkID": "2340984098234204",
                "EndpointID": "5e5cd696f66bfeddea4b26b8466b9bb32b973be10b439e9c6094249fc40d821f",
                "Gateway": "172.18.0.1",
                "IPAddress": "172.18.0.3",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "MacAddress": "02:42:ac:12:00:03"
            }
}
```

**Comment by wenchma** [comment]
@thaJeztah very glad to work on this. :smile:

**Comment by thaJeztah** [comment]
Cool, I see API changes were merged

**Comment by wenchma** [comment]
this PR https://github.com/docker/docker/pull/19243 will vendor the docker/engine-api which contains the https://github.com/docker/engine-api/pull/19 .
wait for the #19243

**Comment by vieux** [comment]
I guess it should be closed by https://github.com/docker/docker/pull/19323

**Comment by vieux** [comment]
ping @thaJeztah

**Comment by vdemeester** [comment]
@vieux you're right, it's merged.
