### ISSUE TITLE
Unable to access local server running on docker

### ISSUE THREAD

**Issue by bipinvaylu** [docker/docker#19096]
I am trying to setting up heroku java app locally using docker. Both container running fine. 1) java web app and 2) postgresql 

```
$ docker logs ottoserver_web_1
...............
INFO  [2016-01-05 17:15:27,477] org.eclipse.jetty.server.handler.ContextHandler: Started i.d.j.MutableServletContextHandler@5d3b58ca{/admin,null,AVAILABLE}
INFO  [2016-01-05 17:15:27,499] org.eclipse.jetty.server.ServerConnector: Started otto-server@2620e717{HTTP/1.1}{0.0.0.0:40014}
INFO  [2016-01-05 17:15:27,499] org.eclipse.jetty.server.Server: Started @5974ms
```

Tried to ping web app running on docker-machine (port 2204 set in docker-compose.yml file)
`$ open "http://$(docker-machine ip default):2204"`

docker container status
```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                              NAMES
f06362ad29cb        ottoserver_web      "bash -c 'java -Djava"   51 minutes ago      Up 15 minutes       0.0.0.0:2204->2204/tcp, 8080/tcp   ottoserver_web_1
1d1dcc7f84e4        postgres            "/docker-entrypoint.s"   4 weeks ago         Up 15 minutes       5432/tcp                           ottoserver_herokuPostgresql_1
```

Please let me know if you need any other details.

**Comment by HackToday** [comment]
check if that port is listening on host, and then try curl related if work. If you can not access that url with curl.  please attach strace logs for that curl.

It is needed to check what blocked that url access.

**Comment by Aamir010** [comment]
Have you change port listening from 8080 to 2204 ? And use netcat command to check whether your docker container is listening on specific port.
nc -zv "ip-address" "port number"

**Comment by thaJeztah** [comment]
Your logs show; 

    Started otto-server@2620e717{HTTP/1.1}{0.0.0.0:40014}

Which seem to indicate it's listening on port 40014, not 2204

I'm going to close this issue, because this doesn't look like a bug, but a configuration issue in your container. Feel free to continue the discussion here though, after I've closed

**Comment by bipinvaylu** [comment]
@HackToday I checked with curl, here is output:

```
Bipins-MacBook-Pro:otto-server bipinvaylu$ docker-machine ip default
192.168.99.100
Bipins-MacBook-Pro:otto-server bipinvaylu$ curl -v http://192.168.99.100:2204/ping
*   Trying 192.168.99.100...
* connect to 192.168.99.100 port 2204 failed: Connection refused
* Failed to connect to 192.168.99.100 port 2204: Connection refused
* Closing connection 0
curl: (7) Failed to connect to 192.168.99.100 port 2204: Connection refused
Bipins-MacBook-Pro:otto-server bipinvaylu$ curl -v http://192.168.99.100:40014/ping
*   Trying 192.168.99.100...
* connect to 192.168.99.100 port 40014 failed: Connection refused
* Failed to connect to 192.168.99.100 port 40014: Connection refused
* Closing connection 0
curl: (7) Failed to connect to 192.168.99.100 port 40014: Connection refused
Bipins-MacBook-Pro:otto-server bipinvaylu$ 
```

**Comment by thaJeztah** [comment]
@bipinvaylu 40014 is the port that the *server* listens on, so you need to remap that to port 2204 if you want to use that as a port, e.g. `docker run -p 2204:40014 .....`

**Comment by bipinvaylu** [comment]
Thanks, @Aamir010 i checked with nc -zv "ip-address" "port number" command. Looks like it's not listening on that port. 

```
Bipins-MacBook-Pro:otto-server bipinvaylu$ docker-machine ip default
192.168.99.100
Bipins-MacBook-Pro:otto-server bipinvaylu$ nc -zv 192.168.99.100 2204
nc: connectx to 192.168.99.100 port 2204 (tcp) failed: Connection refused
Bipins-MacBook-Pro:otto-server bipinvaylu$ nc -zv 192.168.99.100 8080
nc: connectx to 192.168.99.100 port 8080 (tcp) failed: Connection refused
Bipins-MacBook-Pro:otto-server bipinvaylu$ nc -zv 192.168.99.100 40014
nc: connectx to 192.168.99.100 port 40014 (tcp) failed: Connection refused
```


@thaJeztah I checked with 40014 port too but still not working. Any idea how can i know which port is listening or bound with default docker.

**Comment by Aamir010** [comment]
you also need to forward port from your container to your host, using docker run -p flag

**Comment by bipinvaylu** [comment]
@thaJeztah and @Aamir010 , I tried to run docker container using docker run -p flag but it's get exited with 0 and logs is also not showing. Here is output.

```
Bipins-MacBook-Pro:otto-server bipinvaylu$ docker run -p 2204:40014 --name ottoserver_web_1 ottoserver_web
Bipins-MacBook-Pro:otto-server bipinvaylu$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                     PORTS               NAMES
91f635db1773        ottoserver_web      "/bin/bash"              8 seconds ago       Exited (0) 8 seconds ago                       ottoserver_web_1
1d1dcc7f84e4        postgres            "/docker-entrypoint.s"   4 weeks ago         Up 23 hours                5432/tcp            ottoserver_herokuPostgresql_1
Bipins-MacBook-Pro:otto-server bipinvaylu$ docker logs 91f635db1773
Bipins-MacBook-Pro:otto-server bipinvaylu$ docker logs ottoserver_web_1
Bipins-MacBook-Pro:otto-server bipinvaylu$ 
```

**Comment by thaJeztah** [comment]
@bipinvaylu looks like you didn't add `-d` (detached)

**Comment by bipinvaylu** [comment]
@thaJeztah still having same issue with -d too
```
Bipins-MacBook-Pro:otto-server bipinvaylu$ docker run -d -p 2204:40014 --name ottoserver_web_2 ottoserver_web 
13aae7355a486658d7c8f619d2e36074d45adb5804aed50297020714fcb2691d
Bipins-MacBook-Pro:otto-server bipinvaylu$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
1d1dcc7f84e4        postgres            "/docker-entrypoint.s"   4 weeks ago         Up 24 hours         5432/tcp            ottoserver_herokuPostgresql_1
Bipins-MacBook-Pro:otto-server bipinvaylu$ docker ps -a 
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                      PORTS               NAMES
13aae7355a48        ottoserver_web      "/bin/bash"              12 seconds ago      Exited (0) 10 seconds ago                       ottoserver_web_2
91f635db1773        ottoserver_web      "/bin/bash"              8 minutes ago       Exited (0) 8 minutes ago                        ottoserver_web_1
1d1dcc7f84e4        postgres            "/docker-entrypoint.s"   4 weeks ago         Up 24 hours                 5432/tcp            ottoserver_herokuPostgresql_1
Bipins-MacBook-Pro:otto-server bipinvaylu$ 
```
Here i am attaching docker-compose.yml file, if it can help to figure out issue.
docker-compose.yml file:
```
web:
  build: .
  command: 'bash -c ''java $JAVA_OPTS -jar target/otto-server-0.0.2-SNAPSHOT.jar db migrate config.yml && java $JAVA_OPTS -Ddw.server.connector.port=$PORT -jar target/otto-server-0.0.2-SNAPSHOT.jar server config.yml'''
  working_dir: /app/user
  environment:
    PORT: 2204
    DATABASE_URL: 'postgres://postgres:@herokuPostgresql:5432/postgres'
  ports:
    - '2204:2204'
  links:
    - herokuPostgresql
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 2204
    DATABASE_URL: 'postgres://postgres:@herokuPostgresql:5432/postgres'
  ports:
    - '2204:2204'
  links:
    - herokuPostgresql
  volumes:
    - '.:/app/user'
herokuPostgresql:
  image: postgres
```

**Comment by thaJeztah** [comment]
Looks like your compose file is using a completely different command, and you're not specifying a command on the commandline when using docker.

I suggest looking at the logs for that container, also check if the server is listening on the right ports etc.

**Comment by bipinvaylu** [comment]
Hey @thaJeztah, you are right it's something port mapping issue, i fixed it.

Thanks @thaJeztah @Aamir010 @HackToday 

```
Bipins-MacBook-Pro:otto-server bipinvaylu$ curl --verbose http://192.168.99.100:8080/ping
*   Trying 192.168.99.100...
* Connected to 192.168.99.100 (192.168.99.100) port 8080 (#0)
> GET /ping HTTP/1.1
> Host: 192.168.99.100:8080
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Wed, 06 Jan 2016 19:53:49 GMT
< Content-Type: application/json
< Content-Length: 17
< 
* Connection #0 to host 192.168.99.100 left intact
{"reply": "pong"}Bipins-MacBook-Pro:otto-server bipinvaylu$ 
```

**Comment by thaJeztah** [comment]
Cool! Good to hear you got it working :+1:

**Comment by wesleyvicthor** [comment]
@bipinvaylu how you fixed that ?

**Comment by bipinvaylu** [comment]
@wesleyvicthor Fixed my mapping port. On mac, use export to set PORT value.

**Comment by prasanth223344** [comment]
did any of the things above you tried fixed or just exporting PORT value did it? Kindly explain

**Comment by prasanth223344** [comment]
This is what worked for me. Opening up the port. Thanks.

docker run --name my-web  -p 8080:80

**Comment by bipinvaylu** [comment]
Yup, that's it. Great @prasanth223344 👍

**Comment by jhave** [comment]
i'm a newbie: am encountering same error (after iterm updated)
"192.168.99.100 refused to connect."
Kitematic Beta even shows ports listed. But they refuse to connect.
System was working fine thru Docker Quickstart.

# what are the parameters -name and my-web in the following command
# is name the name of the container? 
docker run --name my-web -p 8080:80

**Comment by pharathi25** [comment]
@bipinvaylu 

Can you please let me know how u fixed the mapping port issue.
I tried below command. still no luck

docker run --name my-web -p 8080:80

**Comment by prasanth223344** [comment]
is 8080 on your local free?

**Comment by bipinvaylu** [comment]
hey @prasanth223344, i think just setting PORT environment variable will work. On mac i am running command like `export PORT=8080`.

@thaJeztah said before: look at the logs for that container, also check if the server is listening on the right ports etc.

Please provide some more details with logs.

**Comment by abhinavkorpal** [comment]
please tell me how to set export port  on linux

**Comment by abhinavkorpal** [comment]
how you set export port please tell me ?

**Comment by bipinvaylu** [comment]
@abhinavkorpal please follow this link : https://www.cyberciti.biz/faq/set-environment-variable-linux/

**Comment by abhinavkorpal** [comment]
@bipinvaylu when i runed the set in terminal to address i found one is DOCKER_HOST=tcp://192.168.99.101:2376
DOCKER_HOST_IP=192.168.99.100

**Comment by bipinvaylu** [comment]
hey @abhinavkorpal DOCKER_HOST and DOCKER_HOST_IP should be same, can you please elaborate your issue (with logs if any).

**Comment by abhinavkorpal** [comment]
192.168.99.101 could not connect to 8080
and what should i do to make docke_host and docker_host_ip same. tired and not able to find solution any were

**Comment by bipinvaylu** [comment]
Hey @abhinavkorpal sorry for delay, actually i haven't came across this type of issue and checked out by googling but can't get any proper fix. I think if you try to delete virtual box default machine and recreate it. Not sure but that might help.

**Comment by itohaneregie** [comment]
this is sooo annoying, been trying everything here and still no response

**Comment by itohaneregie** [comment]
please what else can i do, i have tried it all or am i missing something?
