### ISSUE TITLE
docker stats only works for most recently launched container

### ISSUE THREAD

**Issue by patrickbcullen** [docker/docker#19106]
BUG REPORT INFORMATION

docker version:
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64

docker info:
Containers: 17
Images: 284
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-202:1-159383966-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: /dev/vg-docker/data
 Metadata file: /dev/vg-docker/metadata
 Data Space Used: 18.15 GB
 Data Space Total: 210.5 GB
 Data Space Available: 192.3 GB
 Metadata Space Used: 27.92 MB
 Metadata Space Total: 4.291 GB
 Metadata Space Available: 4.263 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.14.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 16
Total Memory: 29.03 GiB
Name: ip-10-128-142-35
ID: X2CL:EUBX:MTHX:O5LO:IRGV:TPLL:WVIU:YTUL:WO75:4YN4:HS6O:XB26
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

Provide additional environment details (AWS, VirtualBox, physical, etc.):
AWS EC2 Centos 7 ami-61bbf104
devicemapper with LVM backend

List the steps to reproduce the issue:
1. Start a docker container then run docker ps --no-trunc. Take note of the container id.
2. List /sys/fs/cgroup/cpu/docker and /sys/fs/cgroup/memory/docker and note the directory with the same container id.
3. Start a second docker container then run docker ps --no-trunc. Take note of both container ids.
4. List /sys/fs/cgroup/cpu/docker and /sys/fs/cgroup/memory/docker again. You will see that memory containers only the new container id while cpu has both container ids.
5. Run docker stat on both containers to confirm that CPU metrics are available for both but memory is only available for the latest container.

Describe the results you received:
Expect to have memory metrics for all containers.

Describe the results you expected:
Only get memory metrics for latest container.

**Comment by patrickbcullen** [comment]
The issue seems to happen after starting a stopping containers for a few days. Unfortunately the log files are gone so I cannot find the error messages associated with the issue. It does appear that the memory cgroup is created after the cpu cgroup because it takes a few minutes for them to converge on the same number. 

I am going to close this issue until I get reproducible steps which may take some time.

**Comment by thaJeztah** [comment]
Cool, thanks!
