### ISSUE TITLE
Documentation - Debian installation needs apt-transport-https

### ISSUE THREAD

**Issue by ajneu** [docker/docker#19101]
Hi,

In the apt installation instruction for Debian, seen here
https://github.com/docker/docker/blob/master/docs/installation/debian.md#update-your-apt-repository
you should add a new point (e.g. after 3.) stating:

Install package `apt-transport-https` which is needed for https repository URIs.
```bash
apt-get install apt-transport-https
```

**Comment by thaJeztah** [comment]
are you interested in opening a pull request? Perhaps we should also explicitly include `ca-certificates`, as that's what the install script does; https://github.com/docker/docker/blob/b0f652fc3892ed85673c79587807a8b9cb6256a4/hack/install.sh#L364

**Comment by ajneu** [comment]
Thanks for pulling.
