### ISSUE TITLE
volumes from Windows 10 do not include the files or subfolders from the source

### ISSUE THREAD

**Issue by W7PEA** [docker/docker#19111]
I posted this in the forums, but I'm convinced this is a bug now.
https://forums.docker.com/t/docker-run-volumes-does-not-include-the-files-within-the-host-directory/5420.

Here's all the stuff from the forum:

This is what I'm seeing, anyone have a workaround or can educated me on what I'm doing wrong. I've figured out the first part which is you have to use the "/" paths as opposed to the windows "\" format. And you have to prepend the HOST and the CONTAINER folders with "//". I got that far, and others seem to say it then worked for them, but for me I don't see any files withing the folders.

Thanks a lot for the help!

**Summary:**
docker run --volume does not work from the docker CLI launched from kitematic NOR does it work when used in the docker quickstart terminal.

## Quickstart Terminal Example
```
MINGW64 /c/CloudStation/Documents/PycharmProjects/YOURAPP
$ docker run --volume=//c/CloudStation/Documents/PycharmProjects/YOURAPP/://source busybox ls -R source
source:
```
No files shown, but they are there... as you can see from the quickstart cli.

```
MINGW64 /c/CloudStation/Documents/PycharmProjects/YOURAPP
$ ls -R
.:
YOURAPP/  manage.py*

./YOURAPP:
__init__.py  settings.py  urls.py  wsgi.py
```

##Docker CLI Example (Launched from Kitematic)

```
PS C:\CloudStation\Documents\PycharmProjects\YOURAPP> docker run --volume=//c/CloudStation/Documents/PycharmProjects/YOU
RAPP/://source busybox ls -R source
source:
```
Again, there are files... but they did not show up when mounted as a volume.
```
PS C:\CloudStation\Documents\PycharmProjects\YOURAPP> dir
    Directory: C:\CloudStation\Documents\PycharmProjects\YOURAPP
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         1/5/2016   1:43 PM                YOURAPP
-a----         1/5/2016   1:43 PM            250 manage.py
```

##Linux Comparison
I should mention, on an Ubuntu VM running on the same Windows 10 host, accessing the same folder via Virtualbox shared folders I can see the files.

```
:~/yourapp$ docker run --rm=true --volume=/media/sf_CloudStation/Documents/PycharmProjects/YOURAPP:/source busybox ls -R source
source:
YOURAPP
manage.py

source/YOURAPP:
__init__.py
settings.py
urls.py
wsgi.py

```

##Environment

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by W7PEA** [comment]
I did search and all the information is already in the bug.

**Comment by thaJeztah** [comment]
This is expected, by default only the C:\users directory is shared with the VirtualBox VM (using VirtualBox shared folders. Anything outside that directory is not shared with the VM, resulting in an empty directory being created inside the VM, and mounted as a volume.

Also see https://github.com/boot2docker/boot2docker#virtualbox-guest-additions

**Comment by W7PEA** [comment]
Hmm.... so I see in that documentation that is says:

"The first of the following share names that exists (if any) will be automatically mounted at the location specified:

Users share at /Users
/Users share at /Users
c/Users share at /c/Users
/c/Users share at /c/Users
c:/Users share at /c/Users"

But when I run the Docker Quickstart Terminal, I see my entire C:\ at /C ... I don't understand how both these things can be true.

**Comment by thaJeztah** [comment]
@W7PEA the QuickStart terminal is a shell on your Windows host, not inside your virtual machine. You can enter the Virtual Machine by opening a ssh session; `docker-machine ssh default`. Inside the VM, you'll see that only /c/Users is available

**Comment by W7PEA** [comment]
Got it. Thank you !
p.s. duh on my part. ;-)

**Comment by thaJeztah** [comment]
@W7PEA no, not really "duh"; it's confusing many people, so no need to apologize :-)
