### ISSUE TITLE
Error attempting heartbeat call to plugin server: connection is shut down

### ISSUE THREAD

**Issue by rkazak** [docker/docker#19117]
docker version:
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

docker info:
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

uname -a:
Darwin kazak.local 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64

Provide additional environment details (AWS, VirtualBox, physical, etc.):
VirtualBox is my provider.

List the steps to reproduce the issue:
1. I had to reinstall everything, VBox, DockerToolBox after I had upgraded from 1.8 to 1.9 and this did not work.
2. When I finally got my default machine going I ssh'ed into it from two sessions
3. I left my terms running and now see the following message repeatedly.

**'Error attempting heartbeat call to plugin server: connection is shut down'**

I disconnected the ssh session from one term and reconnected and the message has stopped.
The other is still reporting the error.

Describe the results you received:
The above error message reported repeatedly.

Describe the results you expected:
No error messages.

Provide additional info you think is important:
This may need to be a seperate report, however, I just now also created a second machine 'dev'
and this worked partially I get the following;

docker-machine create -d virtualbox dev
Running pre-create checks...
Creating machine...
(dev) Copying /Users/rkazak/.docker/machine/cache/boot2docker.iso to /Users/rkazak/.docker/machine/machines/dev/boot2docker.iso...
(dev) Creating VirtualBox VM...
(dev) Creating SSH key...
(dev) Starting VM...
Waiting for machine to be running, this may take a few minutes...
Machine is running, waiting for SSH to be available...
Detecting operating system of created instance...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...

This machine has been allocated an IP address, but Docker Machine could not
reach it successfully.

SSH for the machine should still work, but connecting to exposed ports, such as
the Docker daemon port (usually <ip>:2376), may not work properly.

You may need to add the route manually, or use another related workaround.

This could be due to a VPN, proxy, or host file configuration issue.

You also might want to clear any VirtualBox host only interfaces you are not using.
Checking connection to Docker...

**Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.101:2376": dial tcp 192.168.99.101:2376: i/o timeout**

You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.

Also docker-machine ls shows;
`NAME      ACTIVE   DRIVER       STATE     URL   SWARM   DOCKER   ERRORS`
`default   -        virtual box   Timeout`
`dev       -        virtual box   Timeout`

**Comment by rkazak** [comment]
From 'within' the machine I see
docker@default:~$ w
 04:51:13 up 12:20,  3 users,  load average: 0.00, 0.01, 0.05
USER     TTY        LOGIN@   IDLE   JCPU   PCPU WHAT
root     tty1      Tue10   18:47m  0.00s  0.00s -sh
docker   pts/0     Tue10   11:02   0.00s  0.00s -sh
docker   pts/1     04:38    0.00s  0.00s  0.00s w
docker@default:~$ 
docker@default:~$ docker info
Containers: 0
Images: 0
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: DQCO:BX2H:JAJH:EOQM:TVJM:4CUH:LKMJ:INF3:5T2N:RWFE:MEMB:KKRK
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 18
 System Time: 2016-01-06T05:16:59.555061439Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

**Comment by thaJeztah** [comment]
This looks like a docker-machine issue, can you open this issue in the docker-machine issue tracker? Also there may be existing issues for this, so please search for existing ones first
https://github.com/docker/machine/issues

**Comment by nemonik** [comment]
I'm seeing this same issue.
