### ISSUE TITLE
Install rpm fail 

### ISSUE THREAD

**Issue by Fangfenghua** [docker/docker#19125]
[root@mesos-node ~]# docker -v
Docker version 1.8.2, build bb472f0/1.8.2
[root@mesos-node ~]# 

[root@mesos-node ~]# docker info
Containers: 14
Images: 10
Storage Driver: devicemapper
 Pool Name: docker-253:0-2492111-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.402 GB
 Data Space Total: 107.4 GB
 Data Space Available: 48.66 GB
 Metadata Space Used: 2.72 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 989.9 MiB
Name: mesos-node
ID: IOE4:VM6H:L7K7:FLZZ:PGPO:J7HX:IJKJ:RZMP:I6ZB:XQSY:H3NZ:NYSC
[root@mesos-node ~]# 

[root@19d1f0552756 opt]# rpm -ivh influxdb.rpm 
Preparing...                          ################################# [100%]
Updating / installing...
   1:influxdb-0.8.8-1                 ################################# [100%]
error: unpacking of archive failed on file /opt/influxdb/versions/0.8.8/influxdb;568d2ba4: cpio: read failed - No such file or directory
error: influxdb-0.8.8-1.x86_64: install failed
[root@19d1f0552756 opt]# cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 
[root@19d1f0552756 opt]# :q
bash: :q: command not found
[root@19d1f0552756 opt]# exit
exit

Provide additional environment details (AWS, VirtualBox, physical, etc.):physical

List the steps to reproduce the issue:
1.  use centos:latest image install influxdb.0.8.8
2.[root@mesos-node ~]# docker run -it -v /opt/influxdb.rpm:/opt/influxdb.rpm   centos /bin/bash

**Comment by thaJeztah** [comment]
Looks like you're running a build that's maintained by Red Hat; https://github.com/rhatdan/docker/commit/bb472f05c975b343fb13e55325a985f4ac1d0ca2

Could you open this issue in their issue tracker? https://bugzilla.redhat.com/
