### ISSUE TITLE
Can't start ipv6 daemon twice

### ISSUE THREAD

**Issue by LK4D4** [docker/docker#19139]
I can't start daemon twice with options `--ipv6 --fixed-cidr-v6=2001::/56`. Error:
```
Error starting daemon: Error initializing network controller: Error creating default "bridge" network: failed to add IPv6 address 2001::1/56 to bridge: file exists
```
Destroying bridge `docker0` helps.
ping @mrjana

**Comment by aboch** [comment]
@LK4D4 
Thanks for finding this issue.
I see where the problem is. Will push a fix shortly.

**Comment by LK4D4** [comment]
@aboch thanks!
