### ISSUE TITLE
Archive Notary signatures along with pulled images

### ISSUE THREAD

**Issue by mtrmac** [docker/docker#19130]
In the TUF model, and with the way Notary keeps only the latest versions of metadata within ~/.docker/trust, if the Notary server goes away (due to a hardware failure or intentionally), it is impossible to later directly prove that an image has been signed; and even though there may be an indirect proof (by knowing or assuming that the client was configured to only use properly signed images), keeping the original signed files around can be useful for forensic purposes (e.g. ruling out a client configuration change to disable signature verification, or figuring out which specific key has been used to sign the image, if the role allows using more than one).

In particular, if Docker is verifying signatures when pulling images, it seems prudent for Docker to archive the signature metadata along with the imported image.

**Comment by mtrmac** [comment]
https://github.com/docker/notary/issues/422 is the corresponding Notary issue.

**Comment by endophage** [comment]
This issue feels more appropriate on the notary repo and I'd be happy to see it over there. Notary is responsible for all its own caching and file management. The Docker client has no knowledge of how or where notary stores its files beyond the parent `~/.docker/trust` directory.

**Comment by thaJeztah** [comment]
I'll close this in favor of https://github.com/docker/notary/issues/422 then, please continue the discussion over there

**Comment by mtrmac** [comment]
OTOH the Notary has no knowledge of how or where Docker stores its image manifests. (The above mention of `~/.docker/trust` was not a suggestion that the archived signatures should be stored there, FWIW; they should be managed together with the manifest metadata.)

At best, Notary stand-alone could log all signature verifications that ever happened into a log file, which is not great:
* Humans would have to know that Notary is logging this (without an easy-to-see hint like an option mentioned in `docker inspect`), and would have to manually searcg Notary logs (which would use TUF terms like ”GUN” and “target” instead of Docker terms like ”repository” and “tag”)
* How is the log storage managed? If the log needs to be rotated, without knowing how Docker stores images the best we could do is to delete old entries; with archiving signatures within Docker we could delete the signature archive when deleting the signed image, and keep archived signatures for still used images around forever.
* If Docker knew about the archived signatures, they could possibly be also transferred through `docker save`/`load`.

**Comment by endophage** [comment]
Let's keep the discussion thread on a single issue. It's going to get hard to track otherwise.
