### ISSUE TITLE
Propose dangling filter false to be not same as the meaning of disable filter

### ISSUE THREAD

**Issue by HackToday** [docker/docker#19153]
Right now, the dangling filter in docker images or volumes means as following:

When dangling=true, it would just filter those images with "none"
Like this:
$ docker images -f dangling=true
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
<none>              <none>              cb70b4991cfd        16 minutes ago      133.9 MB

But when dangling=false

$ docker images -f dangling=false
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
<none>              <none>              cb70b4991cfd        17 minutes ago      133.9 MB
centos              latest              61b442687d68        13 days ago         196.6 MB

It is same as docker images:

$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
<none>              <none>              cb70b4991cfd        18 minutes ago      133.9 MB
centos              latest              61b442687d68        13 days ago         196.6 MB

It seems it is very confusing,  I think following maybe more meaningful:
If dangling=true it means just filter out those "none" images
if dangling=false, it means just filter out images without "none"
If without dangling filter, it means not use filter, so all images(include "none" would be listed)

It maybe more meaningful this way.

I just create this issue for discussion if it is meaningful for this propose

**Comment by HackToday** [comment]
ping @cpuguy83 and @thaJeztah and @calavera   Wdyt ?  Thanks

**Comment by thaJeztah** [comment]
Yes, I think that makes sense!
