### ISSUE TITLE
Automated build tag and Dockerfile not updated on successful build

### ISSUE THREAD

**Issue by Soullivaneuh** [docker/docker#19163]
I created a new automated build: https://hub.docker.com/r/dockervan/rrda/

I manually triggered a build from master as you can see here: https://hub.docker.com/r/dockervan/rrda/builds/

The build was successful, but tags and Dockerfile tabs are not updated:

* https://hub.docker.com/r/dockervan/rrda/tags/
* https://hub.docker.com/r/dockervan/rrda/~/dockerfile/

Am I missing something?

**Comment by thaJeztah** [comment]
This is an issue with docker hub, and handled by the support team for hub. Can you open an issue via support@docker.com? Thanks!
