### ISSUE TITLE
unstoppable high cpu zombie processes

### ISSUE THREAD

**Issue by joernhees** [docker/docker#19166]
I seem to have found a way to create high cpu zombie processes inside unstoppable, unkillable docker containers. I tried killing the processes and all their parents as well as the containers themselves with all kinds of kill signals, no success... currently the only thing i can do to stop them is a reboot.

<img width="905" alt="screen shot 2016-01-07 at 20 04 40" src="https://cloud.githubusercontent.com/assets/464192/12180193/71f0fd96-b57b-11e5-8df3-4ab82028c9b7.png">

`docker version`:
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:
```
Containers: 1
Images: 74
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 76
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-74-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 16
Total Memory: 251.9 GiB
Name: censored
ID: censored
WARNING: No swap limit support
```

`uname -a`:
```Linux serv-4101 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux```

Environment details (AWS, VirtualBox, physical, etc.):
physical server, access via ssh

How reproducible:
3 of 3 attempts on our server.

Steps to Reproduce:
1. try to build the debian packages for virtuoso:
`docker run --rm -it -v ~/virtuoso_pkgs:/export/ joernhees/dpkg_build https://github.com/openlink/virtuoso-opensource/archive/59f9b5b8e253b40ff3dfbdde1983123676c9e656.tar.gz -j5` ([source of joernhees/dpkg_build](https://github.com/joernhees/docker-dpkg-build))
2. wait a couple of minutes (~ 10) for the build to get stuck after some VAD package
3. fun fun fun...

Actual Results:
The build process gets stuck after compiling several VAD packages (background knowledge: each VAD package needs to run a virtuoso process to compile, usually they terminate after the package is complete) with this output:
```
=====================================================================
=  COMPLETED VAD PACKAGING
=  Thu Jan 7 18:51:53 UTC 2016
=====================================================================

make[4]: Leaving directory '/tmp/build/virtuoso-opensource-develop-7/appsrc/ODS-Wiki'
make[3]: Leaving directory '/tmp/build/virtuoso-opensource-develop-7/appsrc/ODS-Wiki'
make[3]: Entering directory '/tmp/build/virtuoso-opensource-develop-7/appsrc'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/tmp/build/virtuoso-opensource-develop-7/appsrc'
make[2]: Leaving directory '/tmp/build/virtuoso-opensource-develop-7/appsrc'
make[1]: Leaving directory '/tmp/build/virtuoso-opensource-develop-7'
touch debian/stamp-makefile-build
DEB_MAKE_CHECK_TARGET unset, not running checks
cd debian; find . -name "*.?.xml" -exec docbook2x-man --solinks {} \;
chmod -x binsrc/VirtuosoClient.Net/OpenLink.Data.Virtuoso.dll
```

(You can actually watch with `htop` and try to `CTRL+C` out of the build as soon as you see the first `virtuoso` zombie appearing if you don't want to wait till all the build is done and it gets stuck).

Inspection via `htop` reveals that many virtuoso processes weren't terminated and exist as zombie processes, surprisingly with remaining CPU load of ~ 20 % each... as they're zombies they're not killable, but their parent should be. 

Relevant part of a `sudo ps faux` from the host:
```
root      1787  0.2  0.0 412384 23284 ?        Ssl  19:30   0:03 /usr/bin/docker daemon
root      5149  0.0  0.0  20040  1604 pts/17   Ss+  19:33   0:00  \_ /bin/bash /build.sh https://github.com/openlink/virtuoso-op
root     19627  0.0  0.0  40316 10684 pts/17   S+   19:36   0:00      \_ /usr/bin/perl /usr/bin/dpkg-buildpackage -us -uc -j5
root     20140  0.0  0.0   6936  1436 pts/17   S+   19:37   0:00      |   \_ /usr/bin/make -f debian/rules build
root     49136 43.0  0.0      0     0 ?        Zsl  19:41   6:15      \_ [virtuoso] <defunct>
root      3956 42.4  0.0      0     0 ?        Zsl  19:42   5:45      \_ [virtuoso] <defunct>
root      5359 38.0  0.0      0     0 ?        Zsl  19:42   5:04      \_ [virtuoso] <defunct>
root     22158 34.1  0.0      0     0 ?        Zsl  19:44   4:02      \_ [virtuoso] <defunct>
root     22429 31.4  0.0      0     0 ?        Zsl  19:44   3:34      \_ [virtuoso] <defunct>
root     26268 29.5  0.0      0     0 ?        Zsl  19:45   3:10      \_ [virtuoso] <defunct>
root     26589 27.7  0.0      0     0 ?        Zsl  19:45   2:50      \_ [virtuoso] <defunct>
root     28037 25.0  0.0      0     0 ?        Zsl  19:46   2:27      \_ [virtuoso] <defunct>
root     43540 24.6  0.0      0     0 ?        Zsl  19:46   2:17      \_ [virtuoso] <defunct>
root     44434 23.7  0.0      0     0 ?        Zsl  19:47   2:07      \_ [virtuoso] <defunct>
root     44690 22.5  0.0      0     0 ?        Zsl  19:47   1:54      \_ [virtuoso] <defunct>
root     45961 21.8  0.0      0     0 ?        Zsl  19:48   1:45      \_ [virtuoso] <defunct>
root     47540 22.0  0.0      0     0 ?        Zsl  19:48   1:41      \_ [virtuoso] <defunct>
root     48561 21.4  0.0      0     0 ?        Zsl  19:48   1:33      \_ [virtuoso] <defunct>
root     49403 22.7  0.0      0     0 ?        Zsl  19:49   1:34      \_ [virtuoso] <defunct>
root     50305 20.4  0.0      0     0 ?        Zsl  19:49   1:20      \_ [virtuoso] <defunct>
root     51732 20.3  0.0      0     0 ?        Zsl  19:50   1:15      \_ [virtuoso] <defunct>
root     52892 20.4  0.0      0     0 ?        Zsl  19:50   1:10      \_ [virtuoso] <defunct>
root     53654 20.3  0.0      0     0 ?        Zsl  19:50   1:06      \_ [virtuoso] <defunct>
root     55440 20.6  0.0      0     0 ?        Zsl  19:51   0:58      \_ [virtuoso] <defunct>
```

`docker stop awesome_stallman` (fitting name) gets stalled man, awesome (never returns).
`docker kill awesome_stallman` (from another terminal after waiting for a minute) gets stuck as well.

At this point `sudo ps faux` from yet another terminal looks like this:
```
root      1787  0.2  0.0 546980 29480 ?        Ssl  19:30   0:04 /usr/bin/docker daemon
root      5149  0.0  0.0      0     0 ?        Ss   19:33   0:00  \_ [build.sh]
root     49136 38.6  0.0      0     0 ?        Zsl  19:41   6:58      \_ [virtuoso] <defunct>
... (all still there) ...
root     55440 20.5  0.0      0     0 ?        Zsl  19:51   1:42      \_ [virtuoso] <defunct>
```

`docker kill -s 9 awesome_stallman` gets stuck... 
`sudo kill 5149` no change, getting desparate...
`sudo killall virtuoso`
`sudo killall -9 virtuoso` nothing (well, they're zombies, so not really surprising, but a try before)
`sudo kill -9 5149` nothing...
`docker rm -f awesome_stallman` stuck

`sudo kill 1787` trying to kill the docker daemon, as if this would change anything (it doesn't really:)
```
root      5149  0.0  0.0      0     0 ?        Ss   19:33   0:00 [build.sh]
root     49136 32.1  0.0      0     0 ?        Zsl  19:41   9:03  \_ [virtuoso] <defunct>
... all still there ...
root     55440 20.5  0.0      0     0 ?        Zsl  19:51   3:47  \_ [virtuoso] <defunct>
root     58009  0.7  0.0 320084 23480 ?        Ssl  20:09   0:00 /usr/bin/docker daemon
```

Anything else i could try without rebooting?

Expected Results:
Host should always be able to somehow terminate a docker container, no matter what happens inside.

Additional info:
what do you want to know?

**Comment by phemmer** [comment]
A zombie process using CPU?!?
![](https://media.giphy.com/media/aJnQ9P7JVR25W/giphy.gif)

That's got to be a kernel bug. Look in `dmesg` for anything unusual.

**Comment by cyphar** [comment]
Well, unfortunately there isn't much you can do other than sending a `SIGCHLD` to the `build.sh` process or waiting for init to reap it (which may not happen, I'm not actually sure about the semantics of zombies in a PID namespace and whether they can even be reparented to the parent namespace's init).

However, as @phemmer said, a zombie process using CPU **REALLY** shouldn't be happening. Zombies are processes that have exited and only have left behind some trivial information (the exit code, basically) that still needs to be handed off to the parent.

**Comment by soluwalana** [comment]
You are using the aufs storage driver, there seems to be a livelock condition introduced in a recent patch of aufs that docker 1.9.1 exposed. Massive conversation related to the bug here https://github.com/docker/docker/issues/18180

**Comment by joernhees** [comment]
@phemmer 

<img width="200" alt="high cpu zombies" src="https://cloud.githubusercontent.com/assets/464192/12207096/f46eab00-b644-11e5-8b0a-55f02ef9f87b.png">



`dmesg -T`:
```
[Thu Jan  7 19:30:13 2016] aufs 3.13-20140303
[Thu Jan  7 19:30:13 2016] init: Failed to spawn hybrid-gfx main process: unable to execute: No such file or directory
[Thu Jan  7 19:30:14 2016] init: mongodb main process (2038) terminated with status 1
[Thu Jan  7 19:30:21 2016] Bridge firewalling registered
[Thu Jan  7 19:30:21 2016] nf_conntrack version 0.5.0 (16384 buckets, 65536 max)
[Thu Jan  7 19:30:21 2016] ip_tables: (C) 2000-2006 Netfilter Core Team
[Thu Jan  7 19:30:21 2016] IPv6: ADDRCONF(NETDEV_UP): docker0: link is not ready
[Thu Jan  7 19:30:21 2016] audit_printk_skb: 132 callbacks suppressed
[Thu Jan  7 19:30:21 2016] type=1400 audit(1452191421.696:67): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="docker-default" pid=3186 comm="apparmor_parser"
[Thu Jan  7 19:30:24 2016] init: plymouth-upstart-bridge main process ended, respawning
[Thu Jan  7 19:30:24 2016] init: plymouth-upstart-bridge main process ended, respawning
[Thu Jan  7 19:30:24 2016] cgroup: systemd-logind (781) created nested cgroup for controller "memory" which has incomplete hierarchy support. Nested cgroups may change behavior in the future.
[Thu Jan  7 19:30:24 2016] cgroup: "memory" requires setting use_hierarchy to 1 on the root.
[Thu Jan  7 19:31:18 2016] init: plymouth-stop pre-start process (4940) terminated with status 1
[Thu Jan  7 19:33:54 2016] aufs au_opts_parse:1155:docker[3041]: unknown option dirperm1
[Thu Jan  7 19:33:54 2016] device veth40c4ecb entered promiscuous mode
[Thu Jan  7 19:33:54 2016] IPv6: ADDRCONF(NETDEV_UP): veth40c4ecb: link is not ready
[Thu Jan  7 19:33:54 2016] IPv6: ADDRCONF(NETDEV_CHANGE): veth40c4ecb: link becomes ready
[Thu Jan  7 19:33:54 2016] docker0: port 1(veth40c4ecb) entered forwarding state
[Thu Jan  7 19:33:54 2016] docker0: port 1(veth40c4ecb) entered forwarding state
[Thu Jan  7 19:33:54 2016] IPv6: ADDRCONF(NETDEV_CHANGE): docker0: link becomes ready
[Thu Jan  7 19:34:09 2016] docker0: port 1(veth40c4ecb) entered forwarding state
[Thu Jan  7 20:09:29 2016] init: docker main process ended, respawning
[Thu Jan  7 20:09:29 2016] type=1400 audit(1452193769.693:68): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="docker-default" pid=58054 comm="apparmor_parser"
[Thu Jan  7 23:22:08 2016] perf samples too long (2504 > 2500), lowering kernel.perf_event_max_sample_rate to 50000
```

As you can see the zombies started execution around 19:41, nothing in dmesg around that time. Next output is when i killed the docker main process at 20:09.

I know that this shouldn't happen, but it does for me... Did anyone try and could reproduce this?

**Comment by mikeatlas** [comment]
@joernhees most likely you're hitting #18180 like the rest of so many of us. As a test, can you possibly try downgrading to [Docker 1.8.3 (instructions)](https://github.com/docker/docker/issues/18180#issuecomment-168772166)? Or downgrade to [Linux kernel 3.13.0-71 (instructions) plus linux-image-extra-3.13.0-71-generic](https://github.com/docker/docker/issues/18180#issuecomment-169826675) if you're feeling more daring?

**Comment by joernhees** [comment]
the problem still exists after downgrading to 1.8.3 with aptitude:

`docker version`:
```
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:37:18 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:37:18 UTC 2015
 OS/Arch:      linux/amd64
```

Using Linux Kernel 3.13.0-71 the problem is gone even after upgrading to Docker 1.9.1...

So to me really seems like a Kernel bug.... any idea which kernel version this will be fixed in? I couldn't find that info in #18180 and 3.13.0-76 still shows the problem described here.

**Comment by cyphar** [comment]
Can you try with Linux 4.4 (or any other recent kernel version)?

**Comment by joernhees** [comment]
hmm, i'm on a Ubuntu 14.04 LTS. I can manually install Kernels up to 4.2.0-25 from 15.10 (Wily) without much experimenting (with `sudo apt-get install --install-recommends linux-generic-lts-wily`), but as it's a productive server that we actually use, i don't fancy much more experimentation than that...

i can confirm that this problem is still there in 4.2.0-25

that being said it seems to me that this problem exists in all more recent kernels that are actually officially included in the package managers of debian, ubuntu and suse, meaning it's a HUGE issue for docker...

as it seems the kernel "bug" was backported to >3.13.0-71, it would be cool if the "fix" could also be backported, so that users of those big distributions get that fix without actually doing anything...

so my actual question is: is this gonna happen? any ETA on that? (maybe @AkihiroSuda @tianon @tiborvass )

**Comment by mikeatlas** [comment]
@joernhees backporting a backported patched-patch into kernels for this is out of the scope of Docker's ability to set timelines on the Linux kernel! Although @AkihiroSuda has already posted issues and patches to AUFS and to Canonical's issue trackers and they've been taken up with high priority. Next up, ping @torvalds? (Sorry that might be a serious abuse of an @-mention, and the only time I'd ever even have a reason to do that.... and feel pretty weird at the prospect).

**Comment by cyphar** [comment]
@mikeatlas Don't worry, @torvalds doesn't use GitHub apart from to push to torvalds/linux.

**Comment by AkihiroSuda** [comment]
# LATEST QUICK WORKAROUNDS (no new info)

|Distro         |Workaround                              |
|---------------|----------------------------------------|
|General        | Use devicemapper/overlay/btrfs         |
|Boot2Docker    | Upgrade to [v1.10.0-rc1](https://github.com/tianon/boot2docker-legacy/releases/tag/v1.10.0-rc1)|
|Ubuntu 14.04LTS| Downgrade kernel to 3.13.0-71 or older |
|Ubuntu 15.04   | Downgrade kernel to 3.19.0-39 or older |
|Ubuntu 15.10   | Downgrade kernel to 4.2.0-18  or older |
|RHEL/CentOS    | (does not support AUFS)                |
|Debian         | (does not support AUFS)                |
|openSUSE       | (does not support AUFS)                |

**Comment by AkihiroSuda** [comment]
As AUFS is not included in vanilla kernel, I think we cannot ping torvalds.

We can click "affects me" button in Ubuntu launchpad: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1533043

**Comment by internetstyle** [comment]
Same problem here. How stop unstoppable high cpu zombie processes?

**Comment by joernhees** [comment]
closing this in favor of #18180 . see https://github.com/docker/docker/issues/18180#issuecomment-187583209 for further information, the problem described in this issue cannot be reproduced with docker `1.10.2` on Kernel `4.2.0-30-generic #35~14.04.1-Ubuntu` anymore.
