### ISSUE TITLE
Can't remove container volume with docker rm -v command in 1.9.1

### ISSUE THREAD

**Issue by Tkwon123** [docker/docker#19164]
On docker 1.9.1, I'm hitting issues with compose removing volumes. 

Running `docker inspect busybox` will show the following volumes being used. 
```
    "Mounts": [
        {
            "Source": "/var/lib/docker/volumes/19d153cbc25bc72d90f830f771153808ec8e57b70d1a7e0de345a2d55962f454/_data",
            "Destination": "/data",
            "Mode": "rw",
            "RW": true
        },
        {
            "Source": "/home/user/project-data",
            "Destination": "/opt/data",
            "Mode": "rw",
            "RW": true
        }
    ]
```

I manually removed the directory for the second mount to prevent any lingering dependencies. I then run `docker rm -v busybox` to get rid of the volume as well. 

I run `docker volume ls` and still see the local               19d153cbc25bc72d90f830f771153808ec8e57b70d1a7e0de345a2d55962f454 volume in existance. I confirm this by navigating to /var/lib/docker/volumes and indeed local               19d153cbc25bc72d90f830f771153808ec8e57b70d1a7e0de345a2d55962f454 still exists. 

I'm aware that Compose wont allow me to remove volumes if there are existing linkages to the docker container, but even after rm all containers, I can't seem to rid myself of these dangling volumes.

Am I missing something obvious?

**Comment by thaJeztah** [comment]
Did you remove the remaining containers using `rm -v` as well? Wondering if there was an intermediate container that still used the volume, which caused the volume to not be removed in the first try?

You should still be able to remove the volume using `docker volume rm 19d153cbc25bc72d90f830f771153808ec8e57b70d1a7e0de345a2d55962f454`

**Comment by Tkwon123** [comment]
Thanks for the suggestion. I've tried removing all my containers and have been pretty diligent about using the rm -v whenever disposing of a container (as this issue has been bugging me for a while). As far as I'm aware, I dont have any active or stopped containers as my `docker ps -a` is empty. 

In a similar vein, I'm also having another issue (that I posted on stackoverflow http://stackoverflow.com/questions/34658836/docker-is-in-volume-in-use-but-no-docker-containers) where I have a bunch of containers that are linked somewhere on my `docker volume ls`, but no active/stopped containers that could be tying them up. Paradoxically, when I navigate to the /var/lib/docker/volumes, none of these containers exist. 

I was trying to replicate this issue on another server although it seems like docker rm -v is working correctly there. I'm starting to think I'm in a weird docker state and that a re-install might fix my issues. Will need some time to further explore further...

**Comment by thaJeztah** [comment]
Thanks, I left a comment on the stackoverflow issue; not really sure what the cause may be. It's possible there's a bug or race condition that resulted in the reference counting not matching the actual situation.

I did a quick search, and found these PR, which made changes in this area (and will be in Docker 1.10); https://github.com/docker/docker/pull/17185, https://github.com/docker/docker/pull/18196, https://github.com/docker/docker/pull/17925

**Comment by thaJeztah** [comment]
ping @cpuguy83 looking at this, do you think this is resolved in 1.10?

**Comment by Tkwon123** [comment]
I posted back on stackoverflow but figured I would report here as well. It seems like restarting the daemon cleared out all the issues for me (hoorah no need to reinstall!). I mentioned earlier the only notable difference is that I've been using Compose to spin up the containers on Ubuntu 15.10. 

Until I am able to replicate this issue, I'll go ahead and close this out for now. For others having this problem, a simple `sudo service docker stop` and `sudo service docker start` seems to fix this. Thanks for the help!

**Comment by thaJeztah** [comment]
You're welcome!

**Comment by yuklia** [comment]
@Tkwon123 i also faced the same problem

```
docker info
Containers: 11
 Running: 0
 Paused: 0
 Stopped: 11
Images: 35
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 166
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.19.0-58-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.65 GiB
Name: yuklia
ID: X2GJ:JAQ3:MU3L:44E6:5O45:LHAY:RLRR:FQ25:PZ55:3SDP:KPY5:BQ6H
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Username: yuklia
Registry: https://index.docker.io/v1/
```

```
docker-compose version
docker-compose version 1.7.1, build 0a9ab35
docker-py version: 1.8.1
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
```

**Comment by xidui** [comment]
I also face the same problem at docker 1.12.1 and the restart of docker can not solve this issue:
```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64
```

I did the following:
```bash
docker run -d -v hahaha:/leetcode d1b55fd07600 bash -c "while((1));do sleep 10; done;"
# which will create /var/lib/docker/hahaha directory

docker stop <containerid>

docker rm -v <containerid>
# after that, the hahaha directory still exists

# I had to run the following to remove it manully
docker volume ls -qf dangling=true | xargs -r docker volume rm
```

**Comment by thaJeztah** [comment]
@xidui that is expected; if you explicitly _name_ a volume, docker assumes the data in the volume is important to you, and should not be removed, unless you manually remove the volume (`docker volume rm hahaha`).

If you don't care about the data in a volume, and want it to be removed together with the container, use an "anonymous" volume by leaving out the name;

    docker run -d -v /leetcode d1b55fd07600 bash -c "while((1));do sleep 10; done;"

That will make docker create a volume with a random name, which _is_ deleted if you `docker rm -v ...`

**Comment by xidui** [comment]
@thaJeztah
Thanks for your informative explanation! I have tried your method and works well!
