### ISSUE TITLE
--net=[] (make docker run Accept a List of Networks)

### ISSUE THREAD

**Issue by AlessandroEmm** [docker/docker#19162]
Hey there

As far as I can tell its currently not possible to assign more than networks at starttime. Obivously I can add more interfaces later. Now, this is quite limiting for advanced usecases.

Is there any plan to allow for this?
Thanks!
Alessandro

**Comment by thaJeztah** [comment]
Hi @AlessandroEmm, yes, this would be nice, but unfortunately, there are reasons this is not as easy. We had a PR for that, but we had to reject it for those reasons. Read about it here; https://github.com/docker/docker/pull/17796

Also see these issues, which are duplicates; https://github.com/docker/docker/issues/17750, https://github.com/docker/docker/issues/17289

I'll close this issue for that reason, but thanks for suggesting!
