### ISSUE TITLE
Can not run docker with -it now, it always exits

### ISSUE THREAD

**Issue by HackToday** [docker/docker#19174]
Docker version:
$ docker version
Client:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.2
 Git commit:   374a959
 Built:        Thu Jan  7 18:15:43 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.2
 Git commit:   374a959
 Built:        Thu Jan  7 18:15:43 2016
 OS/Arch:      linux/amd64
 Experimental: true

$ uname -a
Linux temptest 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

ubuntu@temptest:~$ docker run -t -i ubuntu bash
ubuntu@temptest:~$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                       PORTS               NAMES
7a2556bd7b02        ubuntu              "bash"              4 seconds ago       Exited (127) 3 seconds ago                       silly_lamarr
3454155d1c8e        hello-world         "/hello"            12 minutes ago      Exited (0) 12 minutes ago                        ecstatic_visvesvaraya
ubuntu@temptest:~$

**Comment by HackToday** [comment]
ping @thaJeztah  do you know this ? What changes did we do ?

**Comment by HackToday** [comment]
ping @calavera and @LK4D4

**Comment by hqhq** [comment]
This master version works fine for me. Maybe related to experimental version?

```
qhuang@ubuntu-25:~/docker$ docker run -ti --rm ubuntu bash
root@835332e0a996:/# exit
exit
qhuang@ubuntu-25:~/docker$
qhuang@ubuntu-25:~/docker$ docker version
Client:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.2
 Git commit:   374a959
 Built:        Fri Jan  8 03:03:42 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.2
 Git commit:   374a959
 Built:        Fri Jan  8 03:03:42 2016
 OS/Arch:      linux/amd64
```

**Comment by HackToday** [comment]
hi @hqhq  how to configure ubuntu  to try master version ?

**Comment by hqhq** [comment]
@HackToday How did you get this experimental binary? If you built from source code, just build it without experimental flag. Otherwise follow instruction from https://docs.docker.com/engine/installation/ubuntulinux/

**Comment by HackToday** [comment]
@hqhq follow the instruction it asked to configure
deb https://apt.dockerproject.org/repo ubuntu-trusty main

it only installed 1.9.1 release, it not installed master branch version.

**Comment by hqhq** [comment]
@HackToday Yeah I think distros won't support for dev versions but only for release versions, I wonder how did you get the version you described in this issue?

**Comment by HackToday** [comment]
@hqhq I think when you said setup master version, you mean here:

https://docs.docker.com/opensource/project/set-up-dev-env/

Right ?

**Comment by hqhq** [comment]
@HackToday Correct!

**Comment by HackToday** [comment]
@hqhq   I used this ways for binary install,
in https://docs.docker.com/engine/installation/ubuntulinux/
configure apt source as following:
deb https://apt.dockerproject.org/repo ubuntu-trusty experimental

ping @jfrazelle she may know this issue:
https://github.com/docker/docker/pull/13680

**Comment by skairali** [comment]
@HackToday   can you check whether  usr.bin.docker apparmour config has   `/dev/pts/[0-9]* rw ?
If not please try to add this and test  ( I may be wrong as well)

**Comment by HackToday** [comment]
Hi @thaJeztah and @jfrazelle 

I tried the latest RC build, and use this 
curl -fsSL https://test.docker.com/ | sh

to install, it hit same issue.  

```
ubuntu@speedwork:~$ docker version
Client:
 Version:      1.10.0-rc1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   677c593
 Built:        Fri Jan 15 18:42:26 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0-rc1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   677c593
 Built:        Fri Jan 15 18:42:26 2016
 OS/Arch:      linux/amd64
```

```
ubuntu@speedwork:~$ cat /etc/issue
Ubuntu 14.04.1 LTS \n \l

ubuntu@speedwork:~$ uname -a
Linux speedwork 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@speedwork:~$ 
```

**Comment by HackToday** [comment]
It seems same issue happened in #18948

**Comment by jfrazelle** [comment]
this is a dup of https://github.com/docker/docker/issues/18948 we have removed the profile
