### ISSUE TITLE
failure to save an image and zero return code

### ISSUE THREAD

**Issue by wp0pw** [docker/docker#19188]
I just encountered a problem with docker save command

if disk holding docker files in particular /var/lib/docker/tmp is full and I issue docker save command I get following:

    Error response from daemon: write /data/docker/tmp/docker-export-095814297/42557d0e12a89ee38fc98dd6b1da361afe05d12e396c31fc07988568f591be34/json: no space left on device

but the return code from the command is 0 as if nothing bad ever happened however the image is not being saved properly

    docker verision:
    Client version: 1.7.1
    Client API version: 1.19
    Package Version (client): docker-1.7.1-108.el7.centos.x86_64
    Go version (client): go1.4.2
    Git commit (client): 3043001/1.7.1
    OS/Arch (client): linux/amd64
    Server version: 1.7.1
    Server API version: 1.19
    Package Version (server): docker-1.7.1-108.el7.centos.x86_64
    Go version (server): go1.4.2
    Git commit (server): 3043001/1.7.1
    OS/Arch (server): linux/amd64

    docker info:
    Containers: 16
    Images: 156
    Storage Driver: devicemapper
     Pool Name: docker-253:11-206-pool
     Pool Blocksize: 65.54 kB
     Backing Filesystem: xfs
     Data file: /dev/loop0
     Metadata file: /dev/loop1
     Data Space Used: 6.086 GB
     Data Space Total: 107.4 GB
     Data Space Available: 3.686 GB
     Metadata Space Used: 17.24 MB
     Metadata Space Total: 2.147 GB
     Metadata Space Available: 2.13 GB
     Udev Sync Supported: true
     Deferred Removal Enabled: false
     Data loop file: /data/docker/devicemapper/devicemapper/data
     Metadata loop file: /data/docker/devicemapper/devicemapper/metadata
     Library Version: 1.02.93-RHEL7 (2015-01-28)
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 3.10.0-123.el7.x86_64
    Operating System: CentOS Linux 7 (Core)
    CPUs: 1
    Total Memory: 3.704 GiB
    Name: appliance
    ID: P3M5:NFN7:56B7:N3KW:BYUL:H3FX:3GCI:F3BI:FJEB:RXF7:U4TR:O77T

VirtualBox and Physical

Steps to reproduce:

1. fill up /var/lib/docker partition
2. issue: 
    docker save someimage > somefile.tar
  where some file is on a partition with some space left

receved following: 

    Error response from daemon: write /var/lib/docker/tmp/docker-export-095814297/42557d0e12a89ee38fc98dd6b1da361afe05d12e396c31fc07988568f591be34/json: no space left on device

empty tar file
and exit code 0

expected:

same error
empty tar file
and non-zero exit code

**Comment by thaJeztah** [comment]
can you still reproduce this on the current release? (1.9.1 at time of writing)

**Comment by skairali** [comment]
Any update on this yet? I am also planing to use 1.9- of this issue is there then it would need some attention

**Comment by skairali** [comment]
Seems like properly working in 1.9.1

root@innovationb:~# docker save ubuntu:latest >  /sys/fs/cgroup/ubuntu.tar
write /dev/stdout: no space left on device
root@innovationb:~#  echo $?
1
root@innovationb:~# docker save ubuntu:latest > ubuntu.tar
root@innovationb:~# echo $?
0
root@innovationb:~# docker --version
Docker version 1.9.1, build a34a1d5

**Comment by skairali** [comment]
Can this be closed?

**Comment by thaJeztah** [comment]
@skairali yes, I opt for closing this, but @wp0pw, feel free to comment after I've closed and if you're still able to reproduce this on docker 1.9.1 or newer

**Comment by wp0pw** [comment]
sorry for late reply, all works fine in 1.9.1.

**Comment by thaJeztah** [comment]
Thanks @wp0pw!
