### ISSUE TITLE
Docker keeps getting broken on OSX 10.11.2

### ISSUE THREAD

**Issue by maxa4e** [docker/docker#19185]
Installing docker it just keeps getting broken every once in a while.
It totally does not feel solid out of the box.

Is there a documented proven way to replace virtual box with vmware? 
I feel the problems are because of virtual box keeps getting messed up.

One of the problems I keep getting out of the blue is

dev:~ me$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
dev:~ pascal$ docker info
Containers: 0
Images: 0
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: BJID:KQ2X:3LQ2:BLVZ:LN3C:MPKM:EPKL:N7H6:CZ2B:A4FO:DWWV:47OZ
Debug mode (server): true
 File Descriptors: 55
 Goroutines: 75
 System Time: 2016-01-08T12:50:03.995894514Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

Running docker normally
Expected regular behavior. 
Got ad "cannot connect to docker does it run error"

Then investigating it throws an:
Error checking TLS connection: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.100:2376": x509: certificate is valid for 192.168.56.101, not 192.168.99.100

**Comment by maxa4e** [comment]
Again:

After reinstall, just 10 minutes in usage:


```
Error checking TLS connection: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.100:2376": read tcp 192.168.99.1:56629->192.168.99.100:2376: read: connection reset by peer
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.

```

**Comment by thaJeztah** [comment]
@maxa4e can you reopen this issue in the docker machine repository, because this sounds as an issue with docker-machine, not docker (engine); https://github.com/docker/machine/issues

If you want to use VMWare; documentation of the VMWare driver can be found here; https://docs.docker.com/machine/drivers/vm-fusion/

And general documentation on docker machine (i.e. how to create and provision a machine);
https://docs.docker.com/machine/


I'll close this issue here, because this cannot be resolved in this repository, thanks!
