### ISSUE TITLE
Fedora 23, docker 1.9.1 fails to start: FATA[0000] is a directory

### ISSUE THREAD

**Issue by wololock** [docker/docker#19204]
Hello,

It looks like my docker installation stopped working recently. Here are the details:

**docker version**

	Client:
	 Version:         1.9.1-fc23
	 API version:     1.21
	 Package version: docker-1.9.1-4.git6ec29ef.fc23.x86_64
	 Go version:      go1.5.1
	 Git commit:      110aed2-dirty
	 Built:           Wed Dec  9 09:09:16 UTC 2015
	 OS/Arch:         linux/amd64
	Cannot connect to the Docker daemon. Is the docker daemon running on this host?

**uname -a**

    Linux localhost.localdomain 4.2.8-300.fc23.x86_64 #1 SMP Tue Dec 15 16:49:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

When I try to run docker daemon `sudo docker daemon -D`, here is what happens:

	INFO[0000] [graphdriver] using prior storage driver "overlay" 
	DEBU[0000] Using graph driver overlay                   
	DEBU[0000] Using default logging driver json-file       
	DEBU[0000] Creating images graph                        
	DEBU[0000] Restored 0 elements                          
	DEBU[0000] Creating repository list                     
	DEBU[0000] Option DefaultDriver: bridge                 
	DEBU[0000] Option DefaultNetwork: bridge                
	INFO[0000] Firewalld running: false                     
	DEBU[0000] /sbin/iptables, [--wait -t nat -D PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
	DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER] 
	DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL -j DOCKER] 
	DEBU[0000] /sbin/iptables, [--wait -t nat -D PREROUTING] 
	DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT]    
	DEBU[0000] /sbin/iptables, [--wait -t nat -F DOCKER]    
	DEBU[0000] /sbin/iptables, [--wait -t nat -X DOCKER]    
	DEBU[0000] /sbin/iptables, [--wait -t nat -n -L DOCKER] 
	DEBU[0000] /sbin/iptables, [--wait -t nat -N DOCKER]    
	DEBU[0000] /sbin/iptables, [--wait -t filter -n -L DOCKER] 
	DEBU[0000] Registering ipam provider: default           
	DEBU[0000] releasing IPv4 pools from network bridge (f889a98c4410d693de1518f6ba083287cf2c53914f8fb9691dce809ffcd6b879) 
	DEBU[0000] ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.42.1) 
	DEBU[0000] Retrieving bitmask (LocalDefault/172.17.0.0/16, 172.17.0.0/16) 
	DEBU[0000] ReleasePool(LocalDefault/172.17.0.0/16)      
	INFO[0000] Default bridge (docker0) is assigned with an IP address 172.17.42.1/16. Daemon option --bip can be used to set a preferred IP address 
	DEBU[0000] Allocating IPv4 pools for network bridge (5c884a1969bca7acc6aeef35e1dfcf0426fddf949e2661705ab42433c113d6a1) 
	DEBU[0000] RequestPool(LocalDefault, 172.17.42.1/16, , map[], false) 
	DEBU[0000] RequestAddress(LocalDefault/172.17.0.0/16, 172.17.42.1, map[]) 
	DEBU[0000] /sbin/iptables, [--wait -t nat -C POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE] 
	DEBU[0000] /sbin/iptables, [--wait -D FORWARD -i docker0 -o docker0 -j DROP] 
	DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -i docker0 -o docker0 -j ACCEPT] 
	DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -i docker0 ! -o docker0 -j ACCEPT] 
	DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT] 
	DEBU[0000] /sbin/iptables, [--wait -t nat -C PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
	DEBU[0000] /sbin/iptables, [--wait -t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
	DEBU[0000] /sbin/iptables, [--wait -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8] 
	DEBU[0000] /sbin/iptables, [--wait -t nat -A OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8] 
	DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -j DOCKER] 
	DEBU[0000] Cleaning up old shm/mqueue mounts: start.    
	DEBU[0000] Cleaning up old shm/mqueue mounts: done.     
	FATA[0000] is a directory    

I have cleared docker cache, I have also removed all files from `/var/lib/docker` to start with fresh files, but it didn't help. Do you have any idea what does `FATA[0000] is a directory` message points to? I could take a closer look then, but right now I don't know even where to start. Thanks in advance!

**Comment by wololock** [comment]
After restarting system docker started working again. Sorry for interrupting you. Issue closed

**Comment by ivorbrown** [comment]
I was having this same problem with docker 1.9.1 when trying to start the docker daemon.  I would see:

$ sudo docker daemon
FATA[0000] is a directory   

The default docker unix socket -- /var/run/docker.sock -- had somehow turned into a directory.  I removed the directory and re-started the docker daemon and now it's back to running normally.

Thanks to vieux for pointing out the problem behind the cryptic error message.
https://github.com/docker/docker/issues/18521

**Comment by pouicr** [comment]
thx !
