### ISSUE TITLE
Flaky test (?): Panic in 'TestEventsImageUntagDelete' (on experimental)

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#19207]
Again, not sure if this is a flaky test or a bug. Saw this on https://github.com/docker/docker/pull/18906, so thought I'd open an issue to investigate/check

https://jenkins.dockerproject.org/job/Docker-PRs-experimental/13362/console

```
03:58:57 PASS: docker_cli_events_test.go:165: DockerSuite.TestEventsImageTag	1.068s
03:59:17 
03:59:17 ----------------------------------------------------------------------
03:59:17 PANIC: docker_cli_events_unix_test.go:260: DockerSuite.TestEventsImageUntagDelete
03:59:17 
03:59:17 ... Panic: close of closed channel (PC=0x4606EE)
03:59:17 
03:59:17 /usr/local/go/src/runtime/panic.go:423
03:59:17   in gopanic
03:59:17 /usr/local/go/src/runtime/chan.go:303
03:59:17   in closechan
03:59:17 github.com/docker/docker/integration-cli/_test/_obj_test/events_utils.go:159
03:59:17   in matchEventLine.func1
03:59:17 github.com/docker/docker/integration-cli/_test/_obj_test/events_utils.go:125
03:59:17   in eventObserver.CheckEventError
03:59:17 docker_cli_events_unix_test.go:294
03:59:17   in DockerSuite.TestEventsImageUntagDelete
03:59:17 /usr/local/go/src/reflect/value.go:300
03:59:17   in Value.Call
03:59:17 /go/src/github.com/docker/docker/vendor/src/github.com/go-check/check/check.go:772
03:59:17   in suiteRunner.forkTest.func1
03:59:17 /go/src/github.com/docker/docker/vendor/src/github.com/go-check/check/check.go:666
03:59:17   in suiteRunner.forkCall.func1
03:59:17 /usr/local/go/src/runtime/asm_amd64.s:1721
03:59:17   in goexit
03:59:25 
03:59:25 ----------------------------------------------------------------------
03:59:25 PASS: docker_cli_events_test.go:96: DockerSuite.TestEventsLimit	7.435s
```

**Comment by HackToday** [comment]
I run locally the integration test, seems all passed


---> Making bundle: .ensure-httpserver (in bundles/1.10.0-dev/test-integration-cli)
---> Making bundle: .ensure-syscall-test (in bundles/1.10.0-dev/test-integration-cli)
+ go test -check.f TestEventsImage* -test.timeout=120m -check.v github.com/docker/docker/integration-cli
INFO: Testing against a local daemon
PASS: docker_cli_events_test.go:204: DockerSuite.TestEventsImageImport	0.857s
PASS: docker_cli_events_test.go:185: DockerSuite.TestEventsImagePull	2.470s
PASS: docker_cli_events_test.go:165: DockerSuite.TestEventsImageTag	1.151s
PASS: docker_cli_events_unix_test.go:260: DockerSuite.TestEventsImageUntagDelete	0.503s
PASS: docker_cli_events_test.go:505: DockerRegistrySuite.TestEventsImageFilterPush	1.959s
OK: 5 passed
PASS
coverage: 23.9% of statements
