### ISSUE TITLE
Docker Exec just hang on java -h command

### ISSUE THREAD

**Issue by vuminhkh** [docker/docker#19206]
Description of problem:
`docker version`: Docker version 1.9.1, build a34a1d5
`docker info`:
Containers: 2
Images: 83
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 87
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: F2RY:KSB5:AWZM:6WST:FS34:KTNH:CEBU:ICV2:KB3C:GVJT:UWXK:ZBOO
Debug mode (server): true
 File Descriptors: 39
 Goroutines: 82
 System Time: 2016-01-09T10:31:43.512838033Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: toscaruntime
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox

`uname -a`: Darwin t.home 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64

Environment details: Docker Toolbox for Mac OS

Steps to Reproduce:
1. docker pull java
2. CONTAINER_ID=$(docker run -dit java)
3. docker exec $CONTAINER_ID java -h

Actual Results: The command just hang and do not finish except I press Ctrl+C
Expected Results: The command finished normally

Additional info: If executing in interactive mode ‘docker exec -it $CONTAINER_ID java -h‘ , Ctrl+C do not have any more effect, the command will just hang. On another terminal, attempt to remove the container will just hang docker rm -f tiny_mahavira

Thanks,

Minh Khang VU

**Comment by phemmer** [comment]
Sounds like #18180

**Comment by thaJeztah** [comment]
Yes, it does look really similar.

@vuminhkh I'm gonna close this issue, so that we can keep the discussion in a single place. Please subscribe to https://github.com/docker/docker/issues/18180 to stay informed on updates.

https://github.com/docker/docker/issues/18180 also mentions some workarounds (e.g. Changing to another storage driver.

Thanks for reporting! It's really appreciated :+1:
