### ISSUE TITLE
Proposal: Rename `--authz-plugin` to `--authorization-plugin`

### ISSUE THREAD

**Issue by cr7pt0gr4ph7** [docker/docker#19213]
I must admit that I stumbled upon the term `AuthZ Plugin` in the documentation before, but was confused about what it meant. Based on my personal experience, I would therefore suggest that other users have similar problems.

I wanted to note that using an unsually cased acronym like `AuthZ` seems unsual for Docker.
This goes especially for the CLI, which normally seems to prefer fully spelled-out words.

The documentation under [`docs/extend/authorization.md`](https://github.com/docker/docker/blob/master/docs/extend/authorization.md) always uses the term `authorization plugin` when referring to such plugins in prose. It is therefore not clear to me why the Plugin API and the CLI should use the term `AuthZ Plugin`.

(Disclaimer: I mainly dislike the term `AuthZ`, which seems to suggest some specific technology, and would suggest using either `Auth` or `Authorization` instead of it. This would also remove some issues around casing, like in the URL for the endpoint `/AuthzPlugin.AuthZReq`).

----

**References:** PR #15365 introduced the current authorization plugin infrastructure. The general issue for user access control in Docker is #14674.

**Comment by cr7pt0gr4ph7** [comment]
The same goes for the term `AuthN`, which is used instead of `Authentication` in the API, e.g. in `UserAuthNMethod`. The term makes it needlessly hard for new users to understand the API if they are not already aware of the abbreviations.

**Comment by phemmer** [comment]
To play devils advocate, the name is not unique to docker: https://httpd.apache.org/docs/2.4/mod/mod_authz_core.html

**Comment by albers** [comment]
I fully agree with @cr7pt0gr4ph7 here. The current terminology is confusing.
IMHO, the additional amout of typing `--authorization-plugin` is outweighted by the gain in clarity. For users of the shell completions, it wouldn't make any difference.

In the output of `docker info`, the term `Authorization` is used to represent the installed authorization plugins.

**Comment by HackToday** [comment]
Although authz-plugin is ok for me to understand.
authorization-plugin is better to be more understood

**Comment by thaJeztah** [comment]
I'm adding this issue to the 1.10 milestone; if we want to rename this, we'd better make that decision before it's in a release

/cc @calavera @runcom @NathanMcCauley @liron-l @dimastopel

**Comment by runcom** [comment]
Idk, I found authz (and authn) so easy to type. I thought authz was clearly referring to authorization also but seems like it's not :/

**Comment by albers** [comment]
> I found authz (and authn) so easy to type

That's exactly the point. It could be named `authz` as well as `authn` or `AuthZ` or... whatever is also short and understandable and might sound familiar to you with your particular background.

The best option is to use the **real name**, i.e. _authorization plugin_ in code, documentation and API in order to avoid mental mapping. As the term contains a space, it would become `authorizationPlugin` in code or `--authorization-plugin` in options (using common coding conventions). I'm referring to the domain driven design principle of Ubiquitous Language here.

**Comment by albers** [comment]
> familiar to you

or anybody ;-) (not meant to be offending you)

**Comment by tiborvass** [comment]
I didn't have problems with authz, but I do understand that there are a lot of people who don't know what it means. Also, it's not a flag that should be very frequently used, so a little more typing is fine for me.

**Comment by thaJeztah** [comment]
We have @albers, so auto-complete should ease the pain! :heart:

So, add my "+1" as well on renaming

**Comment by runcom** [comment]
I'm fine with renaming as well then (wasn't so find for authz)

**Comment by tiborvass** [comment]
Sorry @chenbo1989, I had already opened the PR. But thanks for trying to fix this issue. I'm sure you can find more, so please continue contributing to Docker! Cheers
