### ISSUE TITLE
overlay backend does not build the image

### ISSUE THREAD

**Issue by bgruening** [docker/docker#19215]
Building this [image](https://github.com/bgruening/docker-galaxy-stable) produces the following error:

```
OSError: [Errno 13] Permission denied: '/tmp/pip-GSL3Gj-uninstall/galaxy-central/.venv/bin'
```

The strange part is that other storage-backends can build this image just fine, including the travis testing in: https://github.com/bgruening/docker-galaxy-stable/tree/dev.

docker version: 
 - Docker version 1.6.2, build 7c8fca2
 - Docker version 1.9.1

```
Containers: 0
Images: 155
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 4.2.0-23-generic
Operating System: Ubuntu 15.10
CPUs: 4
Total Memory: 7.674 GiB
Name: bag
ID: JJHO:BPM7:TA6Q:PBB6:SWXO:NKW7:HKGR:SHD7:ZV2T:ZHHE:IAMB:HDCV
Username: bgruening
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support
```

Build on a physical normal laptop :)
List the steps to reproduce the issue:
 - sudo docker daemon -s overlay
 - git clone --recursive https://github.com/bgruening/docker-galaxy-stable.git
 - cd galaxy
 - docker build -t galaxy .

**Comment by thaJeztah** [comment]
Slightly confused; you're reporting two different docker versions; which version are you using?

**Comment by thaJeztah** [comment]
Looking at the error message, I think this is a duplicate of (or related to) https://github.com/docker/docker/issues/12327 - I.e., pip and overlay don't play together nicely

**Comment by bgruening** [comment]
I tried it with both. Yeah seems a duplicate. Sorry have not seen it earlier.
