### ISSUE TITLE
Doc link error: pachyderme volume plugin not found

### ISSUE THREAD

**Issue by osallou** [docker/docker#19228]
Link at https://docs.docker.com/engine/extend/plugins/ to pachyderme volume plugin  link to 404 Not Found.

**Comment by thaJeztah** [comment]
Thanks for reporting. Do you have the correct link for that plugin? If you do, are you interested in opening a pull request to fix the link? The markdown file to generate that page can be found here; https://github.com/docker/docker/blob/master/docs/extend/plugins.md

**Comment by osallou** [comment]
Hi, I do not have correct link, and not intended to use it. I just saw the
error while going through the doc.

**Comment by thaJeztah** [comment]
No problem! Thanks for reporting

**Comment by HackToday** [comment]
have opened a issue in 3-rd party repo
