### ISSUE TITLE
Update docs as /etc/hosts is no longer used for links/discovery

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#19221]
Now that libnetwork uses DNS-based discovery, we should update the docs, and remove references to `/etc/hosts` being updated, see https://github.com/docker/docker/pull/19198#issuecomment-170384315

/cc @sanimej

**Comment by sanimej** [comment]
@thaJeztah I removed one existing reference to /etc/hosts update. Other than the /etc/hosts update few aspects of the embedded DNS server has to be documented. Will do that.

**Comment by thaJeztah** [comment]
@sanimej yes, Madhu explained; https://github.com/docker/docker/pull/19198#issuecomment-170387732 that the "classic" links still use `/etc/hosts`, and that only "new" links on custom networks will use DNS for the aliases

**Comment by mavenugo** [comment]
@thaJeztah between https://github.com/docker/docker/blob/master/docs/userguide/networking/work-with-networks.md#linking-containers-in-user-defined-networks and https://github.com/docker/docker/pull/19865 I think we covered the required documents for embedded DNS and its usage in links and net-alias. WDYT ?

**Comment by thaJeztah** [comment]
Closing because https://github.com/docker/docker/pull/19865 was merged
