### ISSUE TITLE
Docker: error while loading shared libraries: libsystemd-journal.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by lorenzvth7** [docker/docker#19230]
I'm using Docker version:
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64

```

I have a Jenkins-container running in my Docker Environment.
When I'm accessing the Jenkins-container and try to perform a Docker-command I got this error:

```
libsystemd-journal.so.0: cannot open shared object file: No such file or directory
```

I tried:
```
[root@localhost ~]#  cd /lib64/
[root@localhost lib64]# ln -s /lib64/libdevmapper.so.1.02 /lib64/libdevmapper.so.1.02.1
[root@localhost lib64]# ldconfig 
[root@localhost lib64]# ldconfig -v |grep libdevmapper.so.1.02.1 libdevmapper.so.1.02 -> libdevmapper.so.1.02.1
grep: input file ‘libdevmapper.so.1.02’ is also the output
ldconfig: Can't stat /libx32: No such file or directory
ldconfig: Path `/usr/lib' given more than once
ldconfig: Path `/usr/lib64' given more than once
ldconfig: Can't stat /usr/libx32: No such file or directory
ldconfig: File /lib64/libdevmapper.so.1.02.1 is empty, not checked.
ldconfig: File /lib64/libdevmapper.so.1.02 is empty, not checked.
[root@localhost lib64]# docker
docker: error while loading shared libraries: /lib64/libdevmapper.so.1.02: file too short
```

**Comment by thaJeztah** [comment]
> When I'm accessing the Jenkins-container and try to perform a Docker-command

Can you show the exact steps? Is this error *inside* the container? Are you running docker-in-docker?

**Comment by sebmoule** [comment]
@lorenzvth7, I encountered the same problem while using the image jenkins from rancher catalog where by default they use to bind-mount docker inside the container 

  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
    - '/usr/bin/docker:/usr/bin/docker'

In my case my os was centos and inside the container the os is debian so docker won't work.

I fix this by installing proper docker binary inside the jenkins(debian) container and only bind-mound the docker socket.

**Comment by cpuguy83** [comment]
Yes, if you installed docker from the official apt/yum repos, then it is a dynamically linked binary and just bind-mounting it into the container isn't enough to make it work.

**Comment by thaJeztah** [comment]
I'm going to close this issue, because (as @cpuguy83 explained) this looks like a user error, but feel free to comment here after I've closed

**Comment by kevinsimper** [comment]
@cpuguy83 How can you make it then?

**Comment by lorenzvth7** [comment]
@thaJeztah @cpuguy83 @kevinsimper It was indeed a user-error. I had to copy the shared object files.

**Comment by kevinsimper** [comment]
Yes, but a found the solution. It is just to download the docker binary and use that, since it is only the client you need inside the container :+1:

**Comment by thaJeztah** [comment]
@kevinsimper in case it's useful; there's also official images containing docker; https://hub.docker.com/_/docker/

**Comment by kevinsimper** [comment]
@thaJeztah Nice, thanks you! :)

**Comment by tnguyen14** [comment]
@kevinsimper by just downloading the docker binary, do you mean doing something like `apt-get install docker-engine`?

**Comment by kevinsimper** [comment]
@tnguyen14 It is the opposite you want, you can just grab it from github release https://github.com/docker/docker/releases

**Comment by thaJeztah** [comment]
@kevinsimper @tnguyen14 you can get it even easier; use the official `docker` image on Docker Hub; https://hub.docker.com/_/docker/

**Comment by kevinsimper** [comment]
@thaJeztah I needed the docker client inside my node.js app, so I needed the cli directly :)

**Comment by thaJeztah** [comment]
@tnguyen14 just a heads up; with docker 1.11, docker is shipped as multiple binaries, and static binaries will be shipped as a `.tgz` archive, so it's best to pin your script to a specific version (instead of `docker-latest`), and update your script to work with the archive, once you're switching to 1.11

**Comment by tnguyen14** [comment]
Thanks for the heads up @thaJeztah. I modified my script to be `RUN curl -L https://get.docker.com/builds/Linux/x86_64/docker-1.10.3 > /usr/bin/docker && chmod +x /usr/bin/docker
`
