### ISSUE TITLE
check-config.sh doesn't run under bash 3.2.51

### ISSUE THREAD

**Issue by willsheppard** [docker/docker#19232]
> ./check-config.sh
    ./check-config.sh: line 42: declare: -A: invalid option
    declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
    
    > which bash
    /bin/bash
    
    > /bin/bash --version
    GNU bash, version 3.2.51(1)-release (x86_64-suse-linux-gnu)
    Copyright (C) 2007 Free Software Foundation, Inc.

**Comment by HackToday** [comment]
hi @willsheppard it seems it is better to provide your docker version and linux distro verion and kernel version is needed.


And also for check-config.sh, Which script do you refer ?

**Comment by thaJeztah** [comment]
@HackToday I think he's referring to this script; https://github.com/docker/docker/blob/master/contrib/check-config.sh

Perhaps we can skip colored output on old bash versions?

**Comment by HackToday** [comment]
yes @thaJeztah  we could do that. But is it possible for us to know exactly  which verion work which version not work ?

**Comment by thaJeztah** [comment]
@HackToday I think we should check if the ‘-A` option is working, otherwise skip?

@tianon may have some suggestions for that

**Comment by tianon** [comment]
I've got a simpler solution that doesn't require we give up color -- will have a PR in just a few minutes that could use testing. :smile:

**Comment by tianon** [comment]
https://github.com/docker/docker/pull/19287 could use some testing if anyone's got a second for it :smile:

```console
$ curl -fsSL 'https://raw.githubusercontent.com/tianon/docker/check-config-assoc-array/contrib/check-config.sh' | bash
...
```
or
```console
$ wget -qO- 'https://raw.githubusercontent.com/tianon/docker/check-config-assoc-array/contrib/check-config.sh' | bash
...
```

**Comment by thaJeztah** [comment]
@tianon there's also this image, if you want to test on bash 3.2 :smile: https://hub.docker.com/r/albers/bash-completion-mac/

**Comment by tianon** [comment]
Oh @albers, you hero. :+1:

Thanks @thaJeztah! :smile:

**Comment by albers** [comment]
@tianon :blush:

**Comment by willsheppard** [comment]
Yes that's right, I am referring to this script: https://github.com/docker/docker/blob/master/contrib/check-config.sh

For reference, my system is running Suse 11.2 on Linux 3.0.101-0.7.29-default #1 SMP Thu Jan 29 15:59:13 UTC 2015 (bbc501d) x86_64 x86_64 x86_64 GNU/Linux

@tianon, Thank you - that script now works for me. Here's the output:

    > wget -qO- 'https://raw.githubusercontent.com/tianon/docker/check-config-assoc-array/contrib/check-config.sh' | bash
    info: reading kernel config from /proc/config.gz ...

    Generally Necessary:
    - cgroup hierarchy: nonexistent??
        (see https://github.com/tianon/cgroupfs-mount)
    - CONFIG_NAMESPACES: enabled
    - CONFIG_NET_NS: enabled
    - CONFIG_PID_NS: enabled
    - CONFIG_IPC_NS: enabled
    - CONFIG_UTS_NS: enabled
    - CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled
    - CONFIG_CGROUPS: enabled
    - CONFIG_CGROUP_CPUACCT: enabled
    - CONFIG_CGROUP_DEVICE: enabled
    - CONFIG_CGROUP_FREEZER: enabled
    - CONFIG_CGROUP_SCHED: enabled
    - CONFIG_CPUSETS: enabled
    - CONFIG_MEMCG: missing
    - CONFIG_MACVLAN: enabled (as module)
    - CONFIG_VETH: enabled (as module)
    - CONFIG_BRIDGE: enabled (as module)
    - CONFIG_BRIDGE_NETFILTER: enabled
    - CONFIG_NF_NAT_IPV4: missing
    - CONFIG_IP_NF_FILTER: enabled (as module)
    - CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
    - CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
    - CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
    - CONFIG_NF_NAT: enabled (as module)
    - CONFIG_NF_NAT_NEEDED: enabled
    - CONFIG_POSIX_MQUEUE: enabled

    Optional Features:
    - CONFIG_USER_NS: enabled
    - CONFIG_SECCOMP: enabled
    - CONFIG_MEMCG_KMEM: missing
    - CONFIG_MEMCG_SWAP: missing
    - CONFIG_MEMCG_SWAP_ENABLED: missing
    - CONFIG_RESOURCE_COUNTERS: enabled
    - CONFIG_BLK_CGROUP: enabled
    - CONFIG_IOSCHED_CFQ: enabled
    - CONFIG_BLK_DEV_THROTTLING: enabled
    - CONFIG_CGROUP_PERF: enabled
    - CONFIG_CGROUP_HUGETLB: missing
    - CONFIG_NET_CLS_CGROUP: enabled
    - CONFIG_NETPRIO_CGROUP: missing
    - CONFIG_CFS_BANDWIDTH: enabled
    - CONFIG_FAIR_GROUP_SCHED: enabled
    - CONFIG_RT_GROUP_SCHED: enabled
    - CONFIG_EXT3_FS: enabled (as module)
    - CONFIG_EXT3_FS_XATTR: enabled
    - CONFIG_EXT3_FS_POSIX_ACL: enabled
    - CONFIG_EXT3_FS_SECURITY: enabled
    - CONFIG_EXT4_FS: enabled (as module)
    - CONFIG_EXT4_FS_POSIX_ACL: enabled
    - CONFIG_EXT4_FS_SECURITY: enabled
    - Storage Drivers:
      - "aufs":
        - CONFIG_AUFS_FS: missing
      - "btrfs":
        - CONFIG_BTRFS_FS: enabled (as module)
      - "devicemapper":
        - CONFIG_BLK_DEV_DM: enabled (as module)
        - CONFIG_DM_THIN_PROVISIONING: missing
      - "overlay":
        - CONFIG_OVERLAY_FS: missing
      - "zfs":
        - /dev/zfs: missing
        - zfs command: missing
        - zpool command: missing

**Comment by ericcurtin** [comment]
It's cool that this got fixed for older versions of bash. But I though it was a requirement to have at least version 3.10 of the kernel? A distro running this kernel would never have this older version of bash running!

**Comment by willsheppard** [comment]
Never say never. But in any case, this is the precise script that should inform the user their kernel version is not recent enough!
