### ISSUE TITLE
Container starts before network iface was upped

### ISSUE THREAD

**Issue by narqo** [docker/docker#19238]
I use docker 1.9.1 with bridge network driver on my Ubuntu 14.04 host that is running in our private openstack cloud. It looks that docker container always starts before container's network interface (`eth0` in my case) had been upped.

Here is the minimal test case I've came to which is 100% reproducible for me:

~~~
› docker run --rm -i debian ip link show eth0
300: eth0: <NO-CARRIER,BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default

› docker run --rm -i debian sh -c 'sleep 2;ip link show eth0'
302: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default
~~~

Note "state DOWN" vs. "state UP" in the snippet above.

This leads to situation when network is not accessible during RUN command  from my `Dockerfile` processing. E.g. `RUN apt-get update`.

There are no errors in docker daemon logs, as far as can see.

Details of my system:

~~~
› docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

› docker info
Containers: 0
Images: 4
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.18.22-26
Operating System: Ubuntu 14.04.1 LTS
CPUs: 2
Total Memory: 3.863 GiB
Name: vs-var01h
ID: RXVU:APTP:NNGW:5YYC:WGYX:U3G3:7N7S:ZSXG:W2VL:RAPO:JMXB:MVZK
WARNING: No swap limit support
Labels:
 provider=generic

› uname -a
Linux vs-var01h 3.18.22-26 #17 SMP Wed Oct 28 14:32:46 MSK 2015 x86_64 x86_64 x86_64 GNU/Linux
~~~

On the same system with docker 1.7.1 it works fine.

Currently I don't have any other (hardware) environment outside of the cloud to check the behaviour, and I can't reproduce it with my virtualbox machine.

**Comment by narqo** [comment]
After spending some time digging the source code, my (not very confident, to be honest) guess is that the source of my issue is near `networkNamespace.AddInterface()` method from [libnetwork/osl/interface_linux.go](https://github.com/docker/docker/blob/release/v1.9/vendor/src/github.com/docker/libnetwork/osl/interface_linux.go#L203). I'm absolutely not sure, but after docker 1.7 it was changed to use `nsInvoke()` so maybe this added some additional gap in the network initialisation processes.

I'd be glad to add any addition debug info.

**Comment by narqo** [comment]
> This leads to situation when network is not accessible during RUN command from my Dockerfile processing.

I feel this part is needed some additional comments. My system is IPv6-only and it uses only one DNS server. Somehow the issue i'd described prevents any network connections to work properly.

**Comment by thaJeztah** [comment]
Thanks for reporting @narqo this looks similar to this issue; https://github.com/docker/docker/issues/18871, which should be resolved by https://github.com/docker/docker/pull/19198, which is part of the docker 1.10.0 release.

If you have a system available for testing (not on production yet), would you be able to give the current release candidate a spin and see if this is resolved for you? https://github.com/docker/docker/releases/tag/v1.10.0-rc1 please note that the 1.10 release uses a content-addressable storage, which requires a migration step the first time docker is run. Depending on the number of images and containers on your host, this migration may take a long time to complete. Read more on this in the wiki https://github.com/docker/docker/wiki/Engine-v1.10.0-content-addressability-migration

**Comment by narqo** [comment]
Hey, @thaJeztah, thanks for your reply! I confirm that this issue should be treated as duplicate for #18871 (my bad I didn't find it before opening the issue).

I've checked my usecases on the testing machine (IPv6-only in our private cloud) with docker 1.10-dev (`1.10.0~dev~git20160114.204732.0.7a44265-0~trusty`) and looks like everything works fine.

**Comment by thaJeztah** [comment]
> my bad I didn't find it before opening the issue

no worries! there's so many issues/feature requests, it's easy to miss one :smile:

**Comment by thaJeztah** [comment]
oh, and good to hear it's resolved!
