### ISSUE TITLE
If path is not absalute give warning/error for -v

### ISSUE THREAD

**Issue by samthebest** [docker/docker#19236]
For volumes, paths have to be absolute, but if user provides relative path, docker fails silently.

https://docs.docker.com/engine/userguide/dockervolumes/

**Comment by cpuguy83** [comment]
Docker does not fail silently, it is actually working, just not as you might think....

Relative paths are considered volume names, and you should see a volume in `docker volume ls`.
Note that a bug was recently fixed such that the volume name (when using the `local` volume driver) cannot contain forward slashes, and as such will error out in these cases.

The syntax is `docker run -v <name>:/foo`

**Comment by samthebest** [comment]
Well `docker run -v my-dir:/path/inside/docker/my-dir ...` didn't work and didn't give me an error, I had to do 

```
docker run -v `pwd`/my-dir:/path/inside/docker/my-dir ...
```

**Comment by cpuguy83** [comment]
@samthebest This is because `docker run -v my-dir:/path/inside/docker/my-dir` will yield a new (managed) volume called `my-dir`.
