### ISSUE TITLE
Feature Request: PDF format download of entire docs.

### ISSUE THREAD

**Issue by HariSekhon** [docker/docker#19237]
Useful to read on a kindle or ipad on the daily commute.

**Comment by thaJeztah** [comment]
This is on our list of features we hopefully implement one day (we were also thinking of an .epub download)

**Comment by LK4D4** [comment]
ping @thaJeztah 
Is there still hope?

**Comment by thaJeztah** [comment]
I think this is best opened in the https://github.com/docker/docker.github.io/issues issue tracker, because all the docs are moved there.


@HariSekhon can you reopen this issue there?

**Comment by HariSekhon** [comment]
Raised https://github.com/docker/docker.github.io/issues/289

**Comment by thaJeztah** [comment]
Thanks @HariSekhon!
