### ISSUE TITLE
Not support NO_PROXY for CIDR?

### ISSUE THREAD

**Issue by hpyhacking** [docker/docker#19256]
`docker-machine env [name]` can use `--no-proxy` option to generate docker daemon IP and add it to `NO_PROXY` env. 

I want to set CIDR for `NO_PROXY` but it is not work.

```
~ export no_proxy=10.211.55.17
~ docker ps
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS               NAMES
~ export no_proxy=10.0.0.0/8
~ docker ps
An error occurred trying to connect: Get https://10.211.55.17:2376/v1.21/containers/json: EOF
```

----------

```
~ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   a34a1d5
 Built:        Sat Nov 21 00:49:19 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
~ docker info
Containers: 1
Images: 36
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: tmpfs
 Dirs: 38
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 995.2 MiB
Name: dockers
ID: ZVG6:4GGQ:GZL7:FWPN:NIKO:NCVP:DDXS:R2AO:UFQQ:ADXU:DXKH:SLRW
Debug mode (server): true
 File Descriptors: 16
 Goroutines: 29
 System Time: 2016-01-12T08:46:29.632235071Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=parallels
```

**Comment by IshentRas** [comment]
+1 This functionality is really needed

**Comment by cpuguy83** [comment]
See http://unix.stackexchange.com/questions/23452/set-a-network-range-in-the-no-proxy-environment-variable

Based on everything I've read, NO_PROXY is not intended to take a CIDR

**Comment by IshentRas** [comment]
Thanks very much for the quick reply :+1:

**Comment by thaJeztah** [comment]
I'm closing this; based on the discussion above I don't think we should implement this.

Feel free to comment here after I've closed :+1:

**Comment by ebuildy** [comment]
But  other softwares like curl work fine with no_proxy CIDR

Is it because golang doesnot implement it?

**Comment by svscorp** [comment]
@cpuguy83 @thaJeztah 

Why is this closed? I could not imaging to go for "https://unix.stackexchange.com/questions/23452/set-a-network-range-in-the-no-proxy-environment-variable" solution proposed in an enterprise environment, where are tens of networks and subnetworks you need to consider.

**Comment by thaJeztah** [comment]
@svscorp see https://groups.google.com/forum/m/#!topic/golang-dev/-Zq6u2tJOBQ, and https://github.com/golang/go/issues/16704

This applies to the daemon; For containers themselves, you should be able to set any value
