### ISSUE TITLE
Expose appropriate docker run options to docker build

### ISSUE THREAD

**Issue by superdump** [docker/docker#19259]
If a `Dockerfile` contains a `RUN` directive, it has to create a container of the current state of the image and then run the command in it.

I have hit an interesting case: I have configured the docker daemon to use the fluentd log driver and I run fluentd in a container. This is perfectly fine because I can manually specify `--log-driver json-file` when running my containers that have to be started before the fluentd container.

However, given my first statement, it is possible that if the log driver cannot initialize, you are unable to build images that contain `RUN` directives as `docker build` does not support the `--log-driver` option in order to override the daemon options and therefore the `docker run` to execute the `RUN` directive fails.

I don't know if there are also other options from `docker run` that should be exposed to `docker build` but it would be worth checking that out at the same time I guess.

**Comment by superdump** [comment]
Description of problem:
See original post.

`docker version`:
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

`docker info`:
Containers: 46
Images: 1746
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1844
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: fluentd
Kernel Version: 3.13.0-65-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 6
Total Memory: 7.798 GiB
Name: derp
ID: derp?
Username: derp
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

`uname -a`:
Darwin derp 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64

Environment details (AWS, VirtualBox, physical, etc.):
docker and swarm running on Ubuntu VMs. Using TCP+TLS docker remote API.

How reproducible:
100%

Steps to Reproduce:
1. See
2. original
3. post.

Actual Results:
Building failed due to log driver failing to initialise and there is no way to override it with the docker build command.

Expected Results:
Building is always possible.

Additional info:
Please don't close my issue.

**Comment by thaJeztah** [comment]
ping @cpuguy83 @duglin @tiborvass any thoughts on this?

**Comment by cpuguy83** [comment]
I'd be fine with specifying the log driver here.
It's a weird situation, especially when probably most people don't need to log builds.

**Comment by thaJeztah** [comment]
True, perhaps we can add a default setting in future, that allows setting a different driver for "build"

**Comment by superdump** [comment]
I was also going to suggest a specific default for run during build as JSON-file but it felt inconsistent. Then again, it might be more unexpected that building breaks.

**Comment by thaJeztah** [comment]
Well, I was wondering if we should just default to json-file logs, not sure if there's people expecting other logs during build? Haven't given it a lot of thought yet though.

**Comment by LK4D4** [comment]
It's probably still indeed a problem. We need to default to json-file or none.
@thaJeztah @cpuguy83 thoughts?

**Comment by thaJeztah** [comment]
@LK4D4 I agree, I think defaulting to none, or JSON-file is the best option

**Comment by thaJeztah** [comment]
We see this as a bug, and it should ignore the daemon logging driver options

**Comment by thaJeztah** [comment]
A pull request is opened in https://github.com/docker/docker/issues/29552 for those interested
