### ISSUE TITLE
Error pulling images with docker 1.2

### ISSUE THREAD

**Issue by hooki** [docker/docker#19257]
I'm on docker 1.2 (CentOS7.0[CentOS Linux release 7.0.1406 (Core)])
I'm trying to pull images from docker hub.

$ docker pull debian
Pulling repository debian
2016/01/12 17:42:01 Could not reach any registry endpoint

[ syslog ]
[info] POST /images/create?fromImage=debian&tag=
[9656c570] +job pull(debian, )
[error] pull.go:92 Could not reach any registry endpoint
Could not reach any registry endpoint
[9656c570] -job pull(debian, ) = ERR (1)

$ docker version
Client version: 1.2.0
Client API version: 1.14
Go version (client): go1.3.3
Git commit (client): 2a2f26c/1.2.0
OS/Arch (client): linux/amd64
Server version: 1.2.0
Server API version: 1.14
Go version (server): go1.3.3
Git commit (server): 2a2f26c/1.2.0

$ docker info
Containers: 9
Images: 160
Storage Driver: devicemapper
 Pool Name: docker-253:3-1074645591-pool
 Pool Blocksize: 64 Kb
 Data file: /home/docker/devicemapper/devicemapper/data
 Metadata file: /home/docker/devicemapper/devicemapper/metadata
 Data Space Used: 12684.8 Mb
 Data Space Total: 102400.0 Mb
 Metadata Space Used: 12.2 Mb
 Metadata Space Total: 2048.0 Mb
Execution Driver: native-0.2
Kernel Version: 3.10.0-123.el7.x86_64
Operating System: CentOS Linux 7 (Core)
Username: darkwalts
Registry: [https://index.docker.io/v1/]

**Comment by HackToday** [comment]
not sure if docker still support that old version or not. 

From logs it said:

Could not reach any registry endpoint
Could not reach any registry endpoint

One enable debug level logs and kick same API call. It should log related detailed url.
Then try curl or related URL, if it works.

**Comment by hooki** [comment]
thanks @HackToday :)
I got an error message in debug mode.

{ "error": "Docker Hub no longer accepts pulls from Docker client versions prior to 1.6. Please upgrade your Docker client." }
