### ISSUE TITLE
New install - locale, vps or docer is without css and other static file

### ISSUE THREAD

**Issue by TomasZmek** [docker/docker#19271]
Hi, I have problem. If I installed wger, the application have not css js files. like bootstrap.mini.css (/static/bower_components/bootstrap/dist/css/bootstrap.min.css not found)

now i maked new docer container from github and is same problem.

**Comment by HackToday** [comment]
Hi @TomasZmek  if you want to get help from others, I suggest you make your descriptions more details,  do you think it is a bug or requirements ? For bug, you need input details how to reproduce that, if requirements, input what's that about, and what do you want

**Comment by thaJeztah** [comment]
@TomasZmek I'll close this issue, because we really need more information on what you're asking. Please keep in mind that the GitHub issue tracker is not a general support forum, but for reporting bugs and feature requests.

Closing now, but feel free to comment here after I've closed
