### ISSUE TITLE
No way to setup accesses other than "Collaborator" on teams of a private repo on Docker Hub

### ISSUE THREAD

**Issue by jmaria8** [docker/docker#19270]
Steps to reproduce 
---

On a free Docker Hub account : 

1. Create a private repository (note : creating it only under the logged in user's org works where creating it under any other org gives an error).

2. Confirm that the logged in user is in the Owners team.

3. Go to the Collaborators tag and click Add.

4. Only an input text area appears where you can type in a user ID which is added as "Collaborator". There's no second drop down as per instructions, to select the access type e.g. read-only, write e.t.c.

Reference followed : https://docs.docker.com/docker-hub/orgs/

**Comment by thaJeztah** [comment]
@jmaria8 thanks for reporting. Unfortunately, Docker Hub is handled by a separate team, so we cannot fix that in this repository. Can you open this issue in the "Hub Feedback" issue-tracker? https://github.com/docker/hub-feedback/issues

**Comment by thaJeztah** [comment]
You can also open a support ticket via support@docker.com
