### ISSUE TITLE
Add new field for Swarm in Docker Engine API

### ISSUE THREAD

**Issue by nishanttotla** [docker/docker#19277]
Currently, the `/info` endpoint for the Swarm API uses `DriverStatus` field in the Engine API. We would like to create a new field exclusively for Swarm to use.

Corresponding `docker/swarm` issue: https://github.com/docker/swarm/issues/1625

cc @calavera @vieux

**Comment by nishanttotla** [comment]
Any suggestions for naming the field welcome, especially if we add more Swarm fields in the future.

**Comment by vieux** [comment]
We should use something generic, not related to swarm, like `ExtraStatus` or `CustomStatus`

**Comment by HackToday** [comment]
:+1:  @vieux if need related fields for swarm, please make it generic, as docker is not bind to swarm
