### ISSUE TITLE
run/exec with -it fails on remote 1.10 client with TLS

### ISSUE THREAD

**Issue by dhiltgen** [docker/docker#19280]
Using a top-of-tree daemon, and a remote client, it appears the `-it` flag is broken on the new client.  If you use an old 1.9.X client against the same daemon, it works.

`docker run --rm -it busybox sh` - appears to hang

`docker run -d busybox sleep 1h` works, and if you then `docker exec -it ...` into that container using an older client, you see it started correctly.

My server build:

```
Server:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.2
 Git commit:   09510c7
 Built:        2016-01-12T22:29:53.703167060+00:00
 OS/Arch:      linux/amd64
```

**Comment by HackToday** [comment]
Use master version not found this issue:

root@dccee5a197a7:/go/src/github.com/docker/docker# docker version
Client:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.2
 Git commit:   47d87d3
 Built:        Wed Jan 13 01:27:53 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.2
 Git commit:   47d87d3
 Built:        Wed Jan 13 01:27:53 2016
 OS/Arch:      linux/amd64
root@dccee5a197a7:/go/src/github.com/docker/docker# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
root@dccee5a197a7:/go/src/github.com/docker/docker# docker run -it busybox sh
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
d7e8ec85c5ab: Pull complete 
a3ed95caeb02: Pull complete 
Digest: sha256:e4f93f6ed15a0cdd342f5aae387886fba0ab98af0a102da6276eaf24d6e6ade0
Status: Downloaded newer image for busybox:latest
/ # exit
root@dccee5a197a7:/go/src/github.com/docker/docker# docker run --rm -it busybox sh
/ # 

@dhiltgen  not sure how do you install it ?

**Comment by thaJeztah** [comment]
@HackToday I see @dhiltgen mentions a "remote client"; is your client and version on the same machine?

**Comment by dhiltgen** [comment]
Local (via the docker.sock) works fine in 1.10.  The failure only occurs when the client is remote.

My test rig is using docker-machine, and a custom b2d image that I inject my dev build of docker into.   If I `docker-machine ssh XXX` into the box, then run docker "locally", everything works.  If I `eval "$(docker-machine env XXX)"` the 1.10 client fails, but 1.9 client works.

**Comment by kunalkushwaha** [comment]
I am also facing same issue.

Client version 
```
$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      swarm/1.0.1
 API version:  1.21
 Go version:   go1.5.2
 Git commit:   744e3a3
 Built:
 OS/Arch:      linux/amd64

kunal@kunal-PC ~
$ docker-machine ssh node1
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 1.9.1, build master : cef800b - Fri Nov 20 19:33:59 UTC 2015
Docker version 1.9.1, build a34a1d5
docker@node1:~$ exit

$ docker run -itd --name test ubuntu
a85d475051acd25e5e8202151a945f49a55682c3ae837922e1afaf832b5ccd5f

$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
a85d475051ac        ubuntu              "/bin/bash"         21 seconds ago      Up 19 seconds                           node2/test

$ docker exec -it test bash
cannot enable tty mode on non tty input
```

**Comment by cpuguy83** [comment]
Wonder if the issue is with TLS only?

**Comment by cpuguy83** [comment]
Yep, confirmed to only be happening when using TLS.

**Comment by tonistiigi** [comment]
Bisected to #18730 (ping @calavera)

**Comment by cpuguy83** [comment]
This primarily seems to be an issue with `-i`

`echo hello | docker run -i busybox cat` hangs with TLS cons, and doesn't seem to print anything to stdout, not sure if that's an issue with stdout or stdin, or both.

**Comment by calavera** [comment]
looking into it

**Comment by calavera** [comment]
it looks like there is an issue with the TLS handshake. I see this in the logs:

```
2016/01/13 17:52:51 http: TLS handshake error from 67.188.233.110:63283: tls: oversized record received with length 21536
```

**Comment by calavera** [comment]
#19319 fixes this issue
