### ISSUE TITLE
Document that hostname must be unique when creating an overlay network with Consul

### ISSUE THREAD

**Issue by matevarga** [docker/docker#19301]
I've wasted half a day because after I've created Vagrant-based Docker cluster + overlay networks, then a container could not ping another container even if /etc/hosts was updated properly when a container has joined or left a network. No Docker overlay networking doc or tutorial mentions the requirement that the Docker daemons that join the cluster are identified by the hostname they run on, and if a name clashes, then cross-host container communication is broken.

**Comment by matevarga** [comment]
docker version:
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

docker info:
Containers: 1
Images: 29
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 32
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.0-23-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 3.86 GiB
Name: elastic
ID: 5BF2:E3FY:I5GK:U673:YCU6:HWPV:L5VJ:7GHH:IILQ:JGAR:SX25:HWQ3
WARNING: No swap limit support
Cluster store: consul://192.168.57.101:8500
Cluster advertise: 192.168.57.106:2376
Provide additional environment details (AWS, VirtualBox, physical, etc.):

List the steps to reproduce the issue:
1. Use 3 different hosts. Host1 runs Consul, Host2 and Host3 runs Docker daemon, with cluster-store and cluster-advertise set up properly (pointed at Host1). Host2 and Host3 should have the same hostname.
2. Create an overlay network N1
3. Create containers on Host2 and Host3, connected to N1

Describe the results you received:
Containers on different hosts can't connect.

Describe the results you expected:
Containers on different hosts can connect.

Provide additional info you think is important:
As I've found out, the hostnames of Host2 and Host3 must be different, otherwise Serf gets confused. This should be at least mentioned on the Docker Networking documentation, because in many environments (e.g. Vagrant), hostnames are not initialized by default.

----------END REPORT ---------

**Comment by thaJeztah** [comment]
Thanks for reporting! Are you interested in contributing, and opening a PR with the changes you think are needed? The Markdown files used to generate the documentation can be found in this repository; https://github.com/docker/docker/tree/master/docs

**Comment by matevarga** [comment]
Sure, i'll do it in a few days.

**Comment by aditirajagopal** [comment]
ping @thaJeztah -- having a really unforgiving day with git today, but I got a fix up for this since the other one was closed....just going through some of the open issues to see which ones can be closed!
