### ISSUE TITLE
"Error: Invalid cross-device link" when renaming a directory

### ISSUE THREAD

**Issue by sjackman** [docker/docker#19309]
In a Docker Trusted Build on Docker Hub I'm seeing the error message `Error: Invalid cross-device link` when renaming a directory. I'm renaming `/home/linuxbrew/.linuxbrew/Cellar/binutils/2.25.1` to `/home/linuxbrew/.linuxbrew/Cellar/binutils/2.25.1.reinstall`. The build log is here:
https://hub.docker.com/r/sjackman/linuxbrew-gcc-deps/builds/b9gkq3z58zpvrdinebzkywq/

```
Step 8 : RUN brew reinstall binutils
 ---> Running in ffc2b6349f65
==> Reinstalling binutils
[91mError: Invalid cross-device link - (/home/linuxbrew/.linuxbrew/Cellar/binutils/2.25.1, /home/linuxbrew/.linuxbrew/Cellar/binutils/2.25.1.reinstall)[0m[91m
[0mRemoving intermediate container ffc2b6349f65
The command '/bin/sh -c brew reinstall binutils' returned a non-zero code: 1
```

See also sjackman/docker-linuxbrew#2
@saketkc

# BUG REPORT INFORMATION

Use the commands below to provide key information from your environment:

docker version: Whichever version is running on Docker Hub
docker info: Ditto

Provide additional environment details (AWS, VirtualBox, physical, etc.): Docker Hub

List the steps to reproduce the issue:
1. Trigger a build for sjackman/linuxbrew-gcc-deps

Describe the results you received: `Error: Invalid cross-device link`

Describe the results you expected: A successful build

Provide additional info you think is important:
This error is caused by renaming a directory.

----------END REPORT ---------

**Comment by thaJeztah** [comment]
Thanks for reporting @sjackman. Support for Docker Hub is handled by a different team, so unfortunately we won't be able to help you here. Can you open a ticket at https://support.docker.com or through support@docker.com?

I'm going to close this issue because of the above, but feel free to comment here after I've closed :+1:
