### ISSUE TITLE
Networking stack not ready when building on Windows

### ISSUE THREAD

**Issue by friism** [docker/docker#19314]
I want to be sure we're tracking the problem where the networking stack is not up by the time commands start running during `docker build`.

   Commands may start running in a container before the networking stack has completed initialisation. So in this scenario a wget may fail as the container can't resolve nodejs.org. One workaround here is doing something like start-sleep 1; wget...

 - https://github.com/docker/docker/issues/17509#issuecomment-152642576

According to @jhowardmsft this will be addressed post-TP4.

/cc @StefanScherer @powersplay @uday-shetty @taylorb-microsoft

**Comment by StefanScherer** [comment]
That would be a great improvement to make Dockerfiles more clear without the need for the sleeps. It occurs in `RUN`, but also in `ENTRYPOINT` and probably `CMD`.

I once had to make a workaround to start docker swarm inside a Windows container. Instead of starting the `swarm.exe`I run a small PowerShell script:

```Dockerfile
ENTRYPOINT ["powershell.exe", "-File", "/swarm.ps1"]
```

and then adding a [Sleep](https://github.com/StefanScherer/dockerfiles-windows/blob/master/swarm/swarm.ps1#L1) in the swarm.ps1:

```powershell
Sleep 2
\swarm.exe $args
```

Building the `swarm.exe` in another `Dockerfile` I also had to add a [Sleep](https://github.com/StefanScherer/dockerfiles-windows/blob/master/swarm/build/Dockerfile#L4) before the `go get`call.

**Comment by thaJeztah** [comment]
@friism is this on IPv6 only? Asking because we had some improvements in that area (see https://github.com/docker/docker/issues/18871, https://github.com/docker/docker/pull/19198 and issues linked from that)

> According to @jhowardmsft this will be addressed post-TP4.

Should I add this to the TP5 milestone?

**Comment by StefanScherer** [comment]
I've updated to latest nightly docker.exe on TP4

```
> docker version
Client:
 Version:      1.10.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   82401a4
 Built:        Sat Jan 16 13:57:21 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.10.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   82401a4
 Built:        Sat Jan 16 13:57:21 2016
 OS/Arch:      windows/amd64
```

and ran some tests with `ipconfig`:

```
> docker run -it windowsservercore ipconfig

Windows IP Configuration


Ethernet adapter vEthernet (Virtual Switch-3cea91afe0c245029c1c5897e7972278d140a63f22290753c304940670787c48-0):

   Connection-specific DNS Suffix  . : localdomain
   Link-local IPv6 Address . . . . . : fe80::a819:66f6:5117:46ce%21
   Default Gateway . . . . . . . . . : 172.16.0.1
```

Does not work. But with a sleep 2:

```
> docker run -it windowsservercore "powershell -Command Sleep 2; ipconfig"

Windows IP Configuration


Ethernet adapter vEthernet (Virtual Switch-fc32636057c4873bfd8bb98fdd656114afafef7086acc550bc3035a1e48ef739-0):

   Connection-specific DNS Suffix  . : localdomain
   Link-local IPv6 Address . . . . . : fe80::613b:bc46:6f1e:ae17%21
   IPv4 Address. . . . . . . . . . . : 172.16.0.2
   Subnet Mask . . . . . . . . . . . : 255.240.0.0
   Default Gateway . . . . . . . . . : 172.16.0.1
```

it works, so trying a sleep 1:

```
> docker run -it windowsservercore "powershell -Command Sleep 1; ipconfig"

Windows IP Configuration


Ethernet adapter vEthernet (Virtual Switch-ce1dfbe3e6752e3d5f0e49b71a23615141c1b4f4451a8540826ac2750b9d094d-0):

   Connection-specific DNS Suffix  . : localdomain
   Link-local IPv6 Address . . . . . : fe80::4596:c49a:fa1b:a7b2%21
   IPv4 Address. . . . . . . . . . . : 172.16.0.2
   Subnet Mask . . . . . . . . . . . : 255.240.0.0
   Default Gateway . . . . . . . . . : 172.16.0.1
```

Also works, hm, trying a sleep 0:

```
> docker run -it windowsservercore "powershell -Command Sleep 0; ipconfig"

Windows IP Configuration


Ethernet adapter vEthernet (Virtual Switch-7f11533be47a2d01cd4cab356330a07a551a5981b0f499136bc80dbcd56b5226-0):

   Connection-specific DNS Suffix  . : localdomain
   Link-local IPv6 Address . . . . . : fe80::3d43:1105:269a:5e7b%21
   IPv4 Address. . . . . . . . . . . : 172.16.0.2
   Subnet Mask . . . . . . . . . . . : 255.240.0.0
   Default Gateway . . . . . . . . . : 172.16.0.1
```

Still works, I tried this a dozen times and only got one failing run without an IPv4 address.

Removing the last part from the powershell command always fails:

```
> docker run -it windowsservercore "powershell -Command ipconfig"

Windows IP Configuration


Ethernet adapter vEthernet (Virtual Switch-c297d3f2ba17f62e3b3e18b191f9a94b8a155a62259df70c584dd5f4c6a15250-0):

   Connection-specific DNS Suffix  . : localdomain
   Link-local IPv6 Address . . . . . : fe80::941f:c91:4cd3:1d1%21
   Default Gateway . . . . . . . . . : 172.16.0.1
```

**Comment by StefanScherer** [comment]
Found this [integration test TestRunLookupGoogleDns](https://github.com/docker/docker/blob/4c89b1f72c1259858e243ddbfb00d74dbafeff8a/integration-cli/docker_cli_run_test.go#L66) that should handle this issue.

Running the command manually shows an error:

```
> docker run -t windowsservercore nslookup google.com
Server:  UnKnown
Address:  8.8.8.8

*** UnKnown can't find google.com: No response from server

> $?
True
```

With a sleep everything is fine:

```
> docker run -t windowsservercore "powershell -command sleep 1; nslookup google.com"
Server:  google-public-dns-a.google.com
Address:  8.8.8.8

Non-authoritative answer:
Name:    google.com
Addresses:  2a00:1450:4001:80d::1006
          173.194.116.130
          173.194.116.137
          173.194.116.134
          173.194.116.132
          173.194.116.135
          173.194.116.133
          173.194.116.128
          173.194.116.136
          173.194.116.129
          173.194.116.131
          173.194.116.142

> $?
True
```

**Comment by friism** [comment]
Closing this, not a problem in later releases.
