### ISSUE TITLE
In `docker run IMG COMMAND`, is COMMAND in exec or shell form?

### ISSUE THREAD

**Issue by Blaisorblade** [docker/docker#19315]
Specifying `COMMAND` in `docker run IMG COMMAND` is equivalent passing `COMMAND` to `CMD` in the `Dockerfile`. However, docs don't say if `COMMAND` is interpreted in exec or shell form:
https://docs.docker.com/engine/reference/run/#cmd-default-command-or-options

Docs also don't quite say how Docker distinguishes between exec and parameters form — is that decided just based on whether an `ENTRYPOINT` is specified?

**Comment by HackToday** [comment]
Hi @Blaisorblade  What do you think exec form and shell form ?  Could you specify it more ?

**Comment by Blaisorblade** [comment]
Sorry, I mean as in https://docs.docker.com/engine/reference/builder/#cmd:

> The CMD instruction has three forms:

> CMD ["executable","param1","param2"] (exec form, this is the preferred form)
CMD ["param1","param2"] (as default parameters to ENTRYPOINT)
CMD command param1 param2 (shell form)

**Comment by cpuguy83** [comment]
@Blaisorblade Shell form, just as if you were typing them out on the shell as arguments.

**Comment by cpuguy83** [comment]
ie, `docker run busybox ps faux`

**Comment by Blaisorblade** [comment]
@cpuguy83 Thanks, but beyond learning this, I meant to report a docs bug. Do the docs specify this now?

**Comment by cpuguy83** [comment]
@Blaisorblade There are numerous examples, but it probably doesn't say one way or the other.

I'm not sure that it really needs to. The CLi does not accept JSON syntax anywhere, and would generally be unexpected from a CLI application.

**Comment by Blaisorblade** [comment]
> I'm not sure that it really needs to. The CLi does not accept JSON syntax anywhere, and would generally be unexpected from a CLI application.

The input syntax is clearly specified, that's not the issue; the question is how this is interpreted.

Some of my comments talked about syntax, sorry about that, but this is about how the syntax is interpreted:
> However, docs don't say if COMMAND is _interpreted_ in exec or shell form.
(Emphasis added).

IMHO docs should say that this syntax is interpreted using a shell. Maybe one can interpret the intended behavior out of the current text, but how do you check that was actually implemented?
It's much easier to just spell that out.

This matters in practice — I needed to know this to figure out what is PID 1, when debugging #18758 — see this issue:
https://meta.discourse.org/t/runsv-hanging-on-docker-container-shutdown/36844/38?u=blaisorblade
