### ISSUE TITLE
How to use a external_graphdriver ?

### ISSUE THREAD

**Issue by ptptptptptpt** [docker/docker#19327]
Hi, guys,

I've got  https://github.com/hustcat/docker-graph-driver , build & run it successfully with a ceph cluster. But don't know how to let docker use it for backend storage.

I saw the PR of graphdriver_extpoints from cpuguy83 has been merged:
docker/docker@4c55464
https://github.com/docker/docker/blob/release/v1.9/experimental/plugins_graphdriver.md

And I've got experimental binary:
https://experimental.docker.com/builds/Linux/x86_64/docker-latest
>\# docker -v
Docker version 1.9.1, build f4c9adf, experimental

But just don't know how to enable the feature ...

> \# docker daemon -s rbd
WARN[0000] Running experimental build
INFO[0000] API listen on /var/run/docker.sock
ERRO[0000] Failed to GetDriver graph rbd /var/lib/docker/0.0 
FATA[0000] Error starting daemon: error initializing graphdriver: driver not supported

Thanks for your attention!  Best regards.

**Comment by cpuguy83** [comment]
With this, docker should be looking for a socket in `/run/docker/plugins/rbd.sock`, which is used to communicate with the plugin.
Make sure the plugin is running and listening on a socket there.
You can also add the `-D` flag to the daemon options to get more logging output which may help debug the issue.

**Comment by cpuguy83** [comment]
I'm going to close this since it's not really an issue, but feel free to post here.

**Comment by ptptptptptpt** [comment]
Thanks for reply!

The plugin is already running and listening:
>\# /root/bin/docker-graph-driver -D -s rbd
DEBU[0000] Rbd setup base image                         
INFO[0000] listening on /run/docker/plugins/rbd.sock
>   
DEBU[0000] root group found. gid: 0                     

The output of adding `-D` to docker daemon:
>\# docker daemon -D -s rbd
WARN[0000] Running experimental build                   
DEBU[0000] docker group found. gid: 118                 
DEBU[0000] Server created for HTTP on unix (/var/run/docker.sock) 
INFO[0000] API listen on /var/run/docker.sock           
DEBU[0000] Creating actual daemon root: /var/lib/docker/0.0 
DEBU[0000] [graphdriver] trying provided driver "rbd"   
DEBU[0000] rbd's manifest: &{[GraphDriver]}             
DEBU[0000] rbd implements: GraphDriver                  
ERRO[0000] Failed to GetDriver graph rbd /var/lib/docker/0.0 
FATA[0000] Error starting daemon: error initializing graphdriver: driver not supported


Stop the `docker-graph-driver` pluging and run docker, the output is:
>\# docker daemon -D -s rbd
WARN[0000] Running experimental build                   
DEBU[0000] docker group found. gid: 118                 
DEBU[0000] Server created for HTTP on unix (/var/run/docker.sock) 
INFO[0000] API listen on /var/run/docker.sock           
DEBU[0000] Creating actual daemon root: /var/lib/docker/0.0 
DEBU[0000] [graphdriver] trying provided driver "rbd"   
WARN[0000] Unable to connect to plugin: /run/docker/plugins/rbd.sock, retrying in 1s 
WARN[0001] Unable to connect to plugin: /run/docker/plugins/rbd.sock, retrying in 2s 
WARN[0003] Unable to connect to plugin: /run/docker/plugins/rbd.sock, retrying in 4s 
WARN[0007] Unable to connect to plugin: /run/docker/plugins/rbd.sock, retrying in 8s 
ERRO[0015] Failed to GetDriver graph rbd /var/lib/docker/0.0 
FATA[0015] Error starting daemon: error initializing graphdriver: driver not supported

**Comment by cpuguy83** [comment]
Is the driver crashing?

**Comment by ptptptptptpt** [comment]
No, still running.

**Comment by aliao0019** [comment]
@ptptptptptpt how do you solve this problem then ?  I've got the same error here . 

At first the driver failed to run when using kernel version 3.13.x , and after a dist-upgrade operation , kernel version was 4.2.0-17 .

Now the driver is good to go,  but then docker daemon failed to start . Seems that docker is updated too, `docker version ` got client version `1.11.2`. And I've got the same error msg as yours , `ERRO[0000] Failed to GetDriver graph rbd /var/lib/docker`.

And there is an empty dir `/var/lib/docker/rbd` .

**Comment by ptptptptptpt** [comment]
@aliao0019 It's not solved yet..

**Comment by aliao0019** [comment]
@ptptptptptpt sad..

**Comment by cpuguy83** [comment]
@aliao0019 Are you using the experimental build of docker? It doesn't look like it.

**Comment by cpuguy83** [comment]
@ptptptptptpt Since docker is reporting `Unable to connect to plugin: /run/docker/plugins/rbd.sock` it looks like there's nothing listening there.

**Comment by aliao0019** [comment]
@cpuguy83 yes I found that yesterday. Experimental build running just fine now, and it's working with the graph driver. Thank you!

It seems that the driver is out-of-dated and haven't implemented some APIs that docker daemon requires, such as `GraphDriver.Init` and `GraphDriver.ApplyDiff`, etc.
