### ISSUE TITLE
Docker can't load any container at all

### ISSUE THREAD

**Issue by Bybou** [docker/docker#19331]
Hi,
I'm new on Docker and i'm trying to install it on Debian 7.9 Wheezy.

**Description of problem:**
Docker can't load any conainter at all

**docker version:**
Client:
Version: 1.9.1
API version: 1.21
Go version: go1.4.2
Git commit: a34a1d5
Built: Fri Nov 20 13:06:12 UTC 2015
OS/Arch: linux/amd64

Server:
Version: 1.9.1
API version: 1.21
Go version: go1.4.2
Git commit: a34a1d5
Built: Fri Nov 20 13:06:12 UTC 2015
OS/Arch: linux/amd64

**docker info:**
Containers: 0
Images: 0
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-8:2-783585-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 52.89 MB
 Data Space Total: 107.4 GB
 Data Space Available: 7.942 GB
 Metadata Space Used: 606.2 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.114 (2015-12-14)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.14.27-xxxx-grs-ipv6-64
Operating System: Debian GNU/Linux stretch/sid
CPUs: 4
Total Memory: 7.698 GiB
Name: herakles
ID: B4OG:RZ6F:GAI7:6G2O:G4NT:QPJM:NBW5:25ND:WE7H:6N5N:CLJZ:MY7Z

**OS Information:**
uname -a:
Linux herakles 3.14.27-xxxx-grs-ipv6-64 #1 SMP Wed Dec 17 14:02:42 CET 2014 x86_64 GNU/Linux

lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.9 (wheezy)
Release:	7
Codename:	wheezy

**How reproducible:**
Always

**Steps to Reproduce:**
docker run hello-world

**Actual Results:**
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world

b901d36b6f2f: Extracting 601 B/601 B
0a6ba66e537a: Download complete 
Pulling repository docker.io/library/hello-world
975b84d108f1: Error pulling image (latest) from docker.io/library/hello-world, endpoint: https://registry-1.docker.io/v1/, Error mounting '/dev/mapper/docker-8:2-881285-3f12c794407e68e515ba7f473a744e748ac8a827a2ea8b33855dec564238b2e5' on 975b84d108f1: Error pulling image (latest) from docker.io/library/hello-world, Error mounting '/dev/mapper/docker-8:2-881285-3f12c794407e68e515ba7f473a744e748ac8a827a2ea8b33855dec564238b2e5' on '/var/lib/docker/devicemapper/mnt/3f12c794407e68e515ba7f473a744e748ac8a827a2ea8b33855dec564238b2e5': invalid argument 
Error pulling image (latest) from docker.io/library/hello-world, Error mounting '/dev/mapper/docker-8:2-881285-3f12c794407e68e515ba7f473a744e748ac8a827a2ea8b33855dec564238b2e5' on '/var/lib/docker/devicemapper/mnt/3f12c794407e68e515ba7f473a744e748ac8a827a2ea8b33855dec564238b2e5': invalid argument`

**Trying something to solve the problem**
I tried to do rm -rf /var/lib/docker but no change at all
I tried to use aufs instead of devicemapper without succes.

Sorry for my english it's not my native langage :confused: 

If anyone have a suggestion it will be great.

Thanks

**Comment by cpuguy83** [comment]
Not sure, maybe XFS is a problem here?

ping @rhvgoyal

**Comment by cpuguy83** [comment]
Could also be a problem with devmapper versions or something on Wheezy.

**Comment by HackToday** [comment]
Hi @Bybou  did you follow this guide ?
https://docs.docker.com/engine/installation/debian/

**Comment by Bybou** [comment]
Hi,
Thanks for the answer.
Yes i follow this guide for the installation.

**Comment by rhvgoyal** [comment]
@Bybou What daemon options you are passing to docker daemon? Are you passing any mount options using dm.mountopt?

Also can you check console/dmesg and see if there are any error messages there from kernel.

**Comment by Bybou** [comment]
@rhvgoyal Here is my file /lib/systemd/system/docker.service :

[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target docker.socket
Requires=docker.socket

[Service]
Type=notify
ExecStart=/usr/bin/docker daemon -H fd://
MountFlags=slave
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity

[Install]
WantedBy=multi-user.target


By the way i found this in /var/log/docker.log when i start the daemon docker :
time="2016-01-15T14:44:04.995587477+01:00" level=info msg="API listen on /var/run/docker.sock" 
time="2016-01-15T14:44:05.071278239+01:00" level=warning msg="Usage of loopback devices is strongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use `man docker` to refer to dm.thinpooldev section." 
time="2016-01-15T14:44:05.090199677+01:00" level=info msg="[graphdriver] using prior storage driver \"devicemapper\"" 
time="2016-01-15T14:44:05.092318404+01:00" level=warning msg="Running modprobe nf_nat failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:578 kmod_search_moddep() could not open moddep file '/lib/modules/3.14.27-xxxx-grs-ipv6-64/modules.dep.bin'`, error: exit status 1" 
time="2016-01-15T14:44:05.094632947+01:00" level=info msg="Firewalld running: false" 
time="2016-01-15T14:44:05.212454943+01:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.1/16. Daemon option --bip can be used to set a preferred IP address" 
time="2016-01-15T14:44:05.439179345+01:00" level=warning msg="Your kernel does not support kernel memory limit." 
time="2016-01-15T14:44:05.439356621+01:00" level=warning msg="Your kernel does not support cgroup cfs period" 
time="2016-01-15T14:44:05.439389680+01:00" level=warning msg="Your kernel does not support cgroup cfs quotas" 
time="2016-01-15T14:44:05.440467122+01:00" level=info msg="Loading containers: start." 

time="2016-01-15T14:44:05.440693836+01:00" level=info msg="Loading containers: done." 
time="2016-01-15T14:44:05.440722258+01:00" level=info msg="Daemon has completed initialization" 
time="2016-01-15T14:44:05.440750230+01:00" level=info msg="Docker daemon" commit=a34a1d5 execdriver=native-0.2 graphdriver=devicemapper version=1.9.1

**Comment by rhvgoyal** [comment]
Once docker is running, can you paste output of "systemctl status docker -l"

**Comment by Bybou** [comment]
systemctl status docker -l
Failed to get D-Bus connection: Unknown error -1

But systemctl is on Debian 8 isn't it ?

**Comment by rhvgoyal** [comment]
I don't use debian, so I have no idea when systemd became available. Bottom line is I am trying to figure out if you passed any option to daemon using "--storage-opt dm.mountopt" or not.

Secondly, can you try to pull image and watch your console and see if there are any kernel messages. Kernel seems to be return invalid argument but it is not clear what is invalid.

**Comment by Bybou** [comment]
service docker status
[ ok ] Docker is running.

docker -d --storage-driver=aufs
Warning: '-d' is deprecated, it will be removed soon. See usage.
WARN[0000] please use 'docker daemon' instead.          
INFO[0000] API listen on /var/run/docker.sock           
FATA[0000] Error starting daemon: error initializing graphdriver: driver not supported

It's helping ?
Sorry but my understanding in english is not really good.
Thanks

**Comment by HackToday** [comment]
Hi @Bybou  seems it said


FATA[0000] Error starting daemon: error initializing graphdriver: driver not supported


Which graphdriver do you use ? AUFS or others ?

**Comment by Bybou** [comment]
Hi @HackToday 
It seems the problem is my kernel version. It's a specific driver from OVH.
I think my problem is relativ to https://github.com/docker/docker/issues/6944

**Comment by thaJeztah** [comment]
@Bybou should we close this issue then?

**Comment by Bybou** [comment]
Yes plz.
Thanks to all.
