### ISSUE TITLE
How to change docker storage? Error response from daemon: error creating aufs mount to /..path/aufs/mnt/<sha>-init: invalid argument

### ISSUE THREAD

**Issue by timmytofu** [docker/docker#19336]
I'm trying to store docker's images and sundry items in my home folder rather than in /var/lib/docker which is on my (intentionally small) root partition.

I've symlinked `/var/lib/docker` to where I want it, opened up permissions, etc., and even tried `export DOCKER_OPTS="-g /path/to/where/I/want/it"` interactively, in my shellrc, and in `/etc/default/docker` but I still get an error when running:

```
$ docker info                                                                                                                                      
Containers: 0
Images: 18
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /home/tim/.docker-core/aufs
 Backing Filesystem: <unknown>
 Dirs: 18
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-65-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 8
Total Memory: 7.723 GiB
Name: seitan
ID: ETBA:SEIH:QLJV:OTNP:4ZWY:FRB3:YVWM:777A:A75S:GYID:CESS:KNHA

$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

$ uname -a
Linux seitan 3.13.0-65-generic #106-Ubuntu SMP Fri Oct 2 22:08:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by dmcgowan** [comment]
The `-g` option is the best solution for setting the location for daemon storage.  Based on the `docker info` you linked it looks like the root directory for aufs was updated. You will need to provide more information on what error you are seeing. You may have better luck asking this question on irc or a docker-user forum https://groups.google.com/forum/#!forum/docker-user since it does not appear that you have run into a bug or docker limitation.

**Comment by HackToday** [comment]
Hi @timmytofu check this https://github.com/docker/docker/issues/3127
if it can help you.

**Comment by timmytofu** [comment]
@dmcgowan  The error I am seeing is as in the title (path and sha elided for brevity). And I am indeed using the -g option, amongst many other techniques. All produce this error. When I remove the symlink and use only the `-g` option, I notice that a file is created under the (previously empty) `/var/lib/docker` dir, at `network/files/<sha>.sock`. So, I believe the bug is that the `-g` option does not do what it says on the tin.

@HackToday - the ideas presented there are what I am already doing, but this is the error I get.

**Comment by dmcgowan** [comment]
@timmytofu any information excluded for brevity may be useful. In additional to the docker info it would be helpful to see what what the exact error output it, otherwise it is not clear what the arguments to aufs are. Also you mention a file created under `/var/lib/docker/network/files` after using the `-g` options, this looks like a currently unresolved issue #18508.

**Comment by thaJeztah** [comment]
Actually, those files still being written to `/var/lib/docker` are probably related to https://github.com/docker/libnetwork/pull/742 (and is a duplicate of https://github.com/docker/docker/issues/18508)

**Comment by timmytofu** [comment]
This is the full error:

```
Error response from daemon: error creating aufs mount to /home/tim/.docker-core/aufs/mnt/f4ed73440ad9bf042299a79374c2474427dd80b67bd8d90b04bb69348f7dd51d-init: invalid argument
```

**Comment by unclejack** [comment]
@timmytofu Based on the `docker info` output, I can see you weren't running the latest kernel provided by Ubuntu for your distribution. Please use `apt-get update && apt-get dist-upgrade` to update your system before reporting issues.

Please update your system to check if you're still running into these problems. I'm using a fully patched system with aufs like you are and I'm not seeing these problems.

**Comment by timmytofu** [comment]
`dist-upgrade` isn't the ticket, but I did update my kernel manually.

No change.

**Comment by thaJeztah** [comment]
@timmytofu is `/home/tim/.docker-core` a regular directory, or something mounted there? Wondering, because this in the output of docker info; `Backing Filesystem: <unknown>`

**Comment by timmytofu** [comment]
:facepalm: it's because AUFS can't be mounted on eCryptfs…

**Comment by VictorQueiroz** [comment]
I just changed the storage driver and it worked fine.

**Comment by timmytofu** [comment]
@VictorQueiroz - you changed the storage driver from what to what? There is a filesystem storage driver I see, and a bunch for remote storage, but I see nothing that looks like it'd allow me to mount on eCryptfs…

**Comment by VictorQueiroz** [comment]
@timmytofu I changed from `aufs` to `devicemapper`. My `/etc/docker/daemon.json` looks like this:

```json
{
  "storage-driver": "devicemapper"
}
```

Everything works great now. I just had to redownload all my images but Docker already do that automatically

**Comment by masip85** [comment]
Device mapping resolvers this issue for me (fuseblk format disk), but docker documents specify that this option it is deprecated. Still works, but only by now...

> The devicemapper storage driver is deprecated in Docker Engine 18.09, and will be removed in a future release. It is recommended that users of the devicemapper storage driver migrate to overlay2.

With overlay 2 daemon starts fails when starts:
vmasip@SML-060:/mnt/sda2/work/docker/docker4ds/base-notebook$ sudo dockerd -s overlay2  --data-root=/mnt/sda2/work/rootDocker
INFO[2020-05-15T23:33:14.276847627+02:00] Starting up                                  
INFO[2020-05-15T23:33:14.277589454+02:00] detected 127.0.0.53 nameserver, assuming systemd-resolved, so using resolv.conf: /run/systemd/resolve/resolv.conf 
INFO[2020-05-15T23:33:14.279109724+02:00] parsed scheme: "unix"                         module=grpc
INFO[2020-05-15T23:33:14.279123468+02:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2020-05-15T23:33:14.279135335+02:00] ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] <nil>}  module=grpc
INFO[2020-05-15T23:33:14.279140112+02:00] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2020-05-15T23:33:14.279891046+02:00] parsed scheme: "unix"                         module=grpc
INFO[2020-05-15T23:33:14.279900406+02:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2020-05-15T23:33:14.279909565+02:00] ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] <nil>}  module=grpc
INFO[2020-05-15T23:33:14.279914998+02:00] ClientConn switching balancer to "pick_first"  module=grpc
ERRO[2020-05-15T23:33:14.282773783+02:00] failed to mount overlay: invalid argument     storage-driver=overlay2
INFO[2020-05-15T23:33:14.283112711+02:00] stopping event stream following graceful shutdown  error="context canceled" module=libcontainerd namespace=plugins.moby
failed to start daemon: error initializing graphdriver: driver not supported



It also fails with this option:
`vmasip@SML-060:/mnt/sda2/work/docker/docker4ds/base-notebook$ sudo dockerd -s overlay2 --storage-opt overlay2.override_kernel_check=1 --data-root=/mnt/sda2/work/rootDocker
INFO[2020-05-15T23:30:57.213089985+02:00] Starting up                                  
INFO[2020-05-15T23:30:57.215699788+02:00] detected 127.0.0.53 nameserver, assuming systemd-resolved, so using resolv.conf: /run/systemd/resolve/resolv.conf 
INFO[2020-05-15T23:30:57.216941280+02:00] parsed scheme: "unix"                         module=grpc
INFO[2020-05-15T23:30:57.216951638+02:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2020-05-15T23:30:57.216964908+02:00] ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] <nil>}  module=grpc
INFO[2020-05-15T23:30:57.216970220+02:00] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2020-05-15T23:30:57.217978254+02:00] parsed scheme: "unix"                         module=grpc
INFO[2020-05-15T23:30:57.217989703+02:00] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2020-05-15T23:30:57.217998805+02:00] ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] <nil>}  module=grpc
INFO[2020-05-15T23:30:57.218004157+02:00] ClientConn switching balancer to "pick_first"  module=grpc
ERRO[2020-05-15T23:30:57.220165742+02:00] failed to mount overlay: invalid argument     storage-driver=overlay2
failed to start daemon: error initializing graphdriver: driver not supported
`
