### ISSUE TITLE
Feature Offer: Change image tag only using manifest when dealing with v2 registries

### ISSUE THREAD

**Issue by jasonamyers** [docker/docker#19347]
We had a need to be able to retag an image in a registry without pulling the whole image from the registry, changing the tag locally, and pushing the image back with the new tag to the registry. We have a need to do this operation often to more than 50 containers in serial. We developed a way to just pull just the manifest, change the tag, and push just the manifest for a container, which cuts hours out of our retagging time.

We'd love to share this with the community, but we're wondering if Docker upstream like to have this feature? I've linked to a comparison below of our current hack, and we will happily port this to v2.X.X from v1.9.1, add testing, and properly document this feature via a proper Pull Request. We're also open to other suggestions of how to implement this feature or improve it.

https://github.com/docker/docker/compare/release/v1.9...CiscoSystems:release/v1.9?expand=1

Additional Contributors: @ashmo123
Followers: @rickerc, @signed8bit, @jlothian

**Comment by dmcgowan** [comment]
@jasonamyers  wanting to contribute back your change is much appreciated. Doing direct manifest operations from the docker cli is an often requested feature. We did put a section in the roadmap document explaining why we are currently not accepting these feature requests right now, see https://github.com/docker/docker/blob/729c9a97822ebee2c978a322d37060454af6bc66/ROADMAP.md#23-remote-registry-operations. Essentially the v2 api and new manifest format are currently under active development and we do not want to make changes to the docker cli which may not be compatible with planned changes. Tags in the manifest are a good example of one of these changes as 1.10 will be released with support for a new manifest format which will no longer contain the tag. Not having the tag in the manifest should actually make the feature you are requesting much simpler to implement without docker. It should be as simple as pulling down one tag and pushing it back up as another. Optionally this could also be done directly on the registry storage. Either way we do not believe this needs to be done by docker but rather tooling using the distribution APIs. I might suggest exploring the latest registry changes for 1.10 and opening in issue in the distribution project https://github.com/docker/distribution. 

For reference of the new manifest format see https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-2.md.

Once again thanks for contributing and feel free to work with the distribution team on making sure your use case is supported.

**Comment by jasonamyers** [comment]
Thank you so much for the nice and detailed response. I'll work with the
distribution team to see if we can help in anyway there.

Cheers
Jason

**Comment by thaJeztah** [comment]
Thanks @jasonamyers, much appreciated!

I'll close this issue, based on the discussion above

**Comment by wheleph** [comment]
@jasonamyers , could you share the workaround you used to re-tag images in registry v2?

**Comment by jasonamyers** [comment]
@signed8bit think they would share the final solution that was built?  In the meantime @wheleph, checkout https://github.com/jasonamyers/docker/pull/1/commits/90fe054f08b920d1969c9786836d2481533c5c11 which was the initial concept work. It was fleshed out more later and that's what I'm asking @signed8bit about.
