### ISSUE TITLE
Docker master build for ARM does not have the "daemon" command

### ISSUE THREAD

**Issue by djmaze** [docker/docker#19348]
Description of problem:

The latest ARM build from https://master.dockerproject.org/, called `linux/arm/docker`, doesn't have a `daemon` command. It seems there is no way to run it as a daemon. 

I built master myself on my ARM machine using the `make binary` method, and it does indeed have a `daemon` command. So what is going on here? Can someone shed light on this?

`docker version`:

```
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   3b6a989
 Built:        Thu Jan 14 23:04:44 2016
 OS/Arch:      linux/arm
```

`uname -a`:

    Linux xu4 4.2.0+ #3 SMP PREEMPT Thu Dec 3 08:21:08 UTC 2015 armv7l GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):

- physical (ODROID-XU4)

How reproducible:

- always

Steps to Reproduce:
1. `curl -O https://master.dockerproject.org/linux/arm/docker`
2. `chmod u+x docker`
3. `./docker daemon` / `./docker --help | grep daemon`

Actual Results:

- No result

Expected Results:

    docker daemon [ --help | ... ]

**Comment by HackToday** [comment]
Quite interesting, I did not have Arm machine, so not sure how to reproduce it.


But @djmaze is it only hit in recent docker ? Did it worked before ?


Also how do you install docker from https://master.dockerproject.org/ ?  It seems to me it is just a binary, right ?

**Comment by djmaze** [comment]
> But @djmaze is it only hit in recent docker ? Did it worked before ?

@HackToday I don't know if it was like this before. This is the first time I tried an ARM version from master.dockerproject.org. As far as I know, they only recently began doing these builds for ARM. As I said, when building Docker on ARM myself, it _does have_ a daemon mode. 

So these builds seem to be special somehow. Also, I am unable to find these builds in their Jenkins configuration.

> Also how do you install docker from https://master.dockerproject.org/ ? It seems to me it is just a binary, right ?

As these are statically compiled binaries, trying it out it as easy as downloading the binary, making it executable and running it. See my "steps to reproduce" above.

**Comment by tianon** [comment]
This is expected -- the binaries released there are our standard
cross-compiled binaries, and only the amd64 binaries are daemon-enabled.
We're still working on a good, clean way to build and distribute
fully-functional cross-architecture daemon binaries. :+1:

**Comment by djmaze** [comment]
@tianon, thanks for the clarification.
