### ISSUE TITLE
Docker Daemon connection to https cluster store

### ISSUE THREAD

**Issue by tylerFowler** [docker/docker#19344]
Perhaps this has been covered elsewhere but I can't find it here or in the docs. I'm trying to create an overlay network on a cluster that uses an SSL enabled etcd2 k/v store and Docker doesn't seem to be picking up on the HTTPS part..

Using a systemd drop-in like so:
```bash
Environment="DOCKER_OPTS=--tlsverify \
--tlscacert=/etc/docker/ssl/ca.pem \
--tlscert=/etc/docker/ssl/cert.pem \
--tlskey=/etc/docker/ssl/key.pem \
--cluster-store=etcd://127.0.0.1:2379 \
--cluster-advertise=tcp://$private_ipv4:2376 \
-H=tcp://0.0.0.0:2376 -H=unix:///var/run/docker.sock"
```

I get (in debug mode) the following output:
```log
failed to get endpoints for network bridge scope global: client: etcd cluster is unavailable or misconfigured

failed to get endpoints for scope global: client: etcd cluster is unavailable or misconfigured

could not find network <NETWORK_ID>: client: etcd cluster is unavailable or misconfigured
```

As far as I know there's no special syntax for specifying an HTTPS etcd url so I was under the impression that the presence of the `--tlsverify` flag would tell it to use https for etcd? Additionally that value for `--cluster-advertise` doesn't work & causes a crash but that's another problem altogether.

Docker version:
```bash
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   4419fdb-dirty
 Built:        Fri Dec 18 00:01:03 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   4419fdb-dirty
 Built:        Fri Dec 18 00:01:03 UTC 2015
 OS/Arch:      linux/amd6
```

**Comment by cpuguy83** [comment]
See https://docs.docker.com/engine/reference/commandline/daemon/#nodes-discovery

**Comment by tylerFowler** [comment]
Ah the one page I thought I had covered, thanks!

**Comment by cpuguy83** [comment]
np!
