### ISSUE TITLE
pull and push are slooooow (50kB/s-slow)

### ISSUE THREAD

**Issue by Giszmo** [docker/docker#19352]
both docker 1.6.2 and 1.9.1

On my two local Linux Debian 8.2 64bit SSD machines (both with dm-crypt full disk encryption) docker is unusable. A 1GB image that loads in seconds when pulled by my VPS, takes hours or days locally. `Watch`ing `df -k` looks like 20kB/s to 200kB/s.

Yes, I am aware of

* This [broken debugging script](https://github.com/docker/docker-registry/blob/master/DEBUGGING.md#testing-the-speed-of-the-official-registry)
* This "fixed" and locked [issue](https://github.com/docker/docker/issues/7291)
* This "closed"  [issue](https://github.com/docker/docker/issues/7291) that claims to be fixed with some release (1.2), too.
* Unlike [this issue](https://github.com/docker/docker/issues/17720), `time for i in {1..1000}; do sudo docker ps ; done` runs in 40s here, but I do notice weird hang-ups of my console. (where is the `/var/log/docker.log`? `locate docker | grep log` was not very revealing and google knows all about `docker logs image_id` but nothing about the docker service' logs.)

The affected machines are:

````
$ sudo docker info
Containers: 7
Images: 39
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 54
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 8
Total Memory: 15.55 GiB
Name: debian
ID: U6JV:I56V:NCGS:FFLX:AJBM:SI3X:6DGM:GZYA:VB4L:L2S7:T2UJ:23X7
WARNING: No memory limit support
WARNING: No swap limit support
````

and

````
$ sudo docker info
Containers: 7
Images: 48
Storage Driver: devicemapper
 Pool Name: docker-252:1-4874406-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 6.054 GB
 Data Space Total: 107.4 GB
 Data Space Available: 21.85 GB
 Metadata Space Used: 6.775 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.141 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.90 (2014-09-01)
Execution Driver: native-0.2
Kernel Version: 4.2.0-0.bpo.1-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 4
Total Memory: 7.655 GiB
Name: locurro
ID: ZPV3:OKKI:2AJ7:QGQU:KVWV:QB32:2A74:AAKI:LDKU:SZBJ:ISDZ:W3OZ
WARNING: No memory limit support
WARNING: No swap limit support
````

(this second machine actually lags between 0.5s and 1s with every `docker info` call. It's the laptop I'm sitting at. The other is my laptop across the room)

Lines that look scary in the `docker info` are `WARNING: No memory limit support` and `WARNING: No swap limit support` but as my server has these, too, I assume that's not related.

My guess: dm_crypt on the hosts?

**Comment by HackToday** [comment]
You could debug with stace linux tools, and also enable daemon -D debug level, to check if 
request send quickly and response slow.

Also when you push and pull, you are talking to docker Hub, use other network tools like wget or curl, to check if network speed issue with docker Hub.

**Comment by Giszmo** [comment]
Hi @HackToday . Your first sentence led me to install `strace`. Sorry, I never used that. Might take a while to figure out. `sudo strace docker` gives me tons of Chinese. Can upload it but it doesn't look helpful.

"enable -D debug level" is neither very instructive. What would I do with that? Ah, found it: `docker -d -D`? Ok, no errors there. docker pull nginx gives me the same slow speed with nothing but unsuspicious DEBUG messages. 

Yes, I'm talking about hub.docker.com. [This repository](https://hub.docker.com/r/giszmo/playground/) to be precise. I can't see any big files to download from there, though. I don't see an indicator of where the file

````
DEBU[0669] pulling blob "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" to 140f9bdfeb9784cf8730e9dab5dd12fbd704151cf555ac8cae650451794e5ac2
````

is hosted for example.

Also googling for those hashes, I see some cloudfront links but no canonical file hoster where I could try downloading some example file. (Sorry, you probably know how to figure out where docker is pulling the files from, but I don't. :/ )

**Comment by Giszmo** [comment]
As mentioned in the OP, files got downloaded at around 100kB/s but now when I tried to start with debugging, I noticed that the 2GB download was finished on both machines, although on one machine at least, I had canceled the docker pull command. Is the docker daemon unaffected by the "client" getting killed? Anyway, at some point the progress must have sped up but on the one machine I was literally waiting for it to complete for more than two hours and on the other I "canceled" after half an hour.

**Comment by HackToday** [comment]
Hi @Giszmo 
stace use like this: 

```
strace docker pull busybox

```

it track related linux calls, and can help what is blocking or is your request issue or related network slow.


Also for enable docker debug logs, use

```
docker daemon -D
```
if you start docker by manual, if you start by systemd or service, you could edit that file to make it have -D

**Comment by Giszmo** [comment]
Uhm, weird, now I get like 4MB/s, which is actually ok with the ISP I have. Will have to try to reproduce tomorrow. Will report back with strace results if it happens again.

**Comment by HackToday** [comment]
You said 4MB/s  It seems your network stability issue

**Comment by cpuguy83** [comment]
This could be lots of things, issues with the CDN, network congestion, hub may have been slow (not sure) due to base image updates for the SSH CVE (and everyone downloading).

I'm going to close this since it sounds like you are now getting decent speed and doesn't look like a bug in Docker.

For issues with Hub in particular, in the future it would be great if you can open a ticket @ https://support.docker.com so they can address it there.
