### ISSUE TITLE
Info interface in daemon/execdriver/driver.go implemented twice but only one is in use

### ISSUE THREAD

**Issue by amitkris** [docker/docker#19350]
Problem Description:
daemon/execdriver/driver.go: has an Info interface that defines the IsRunning() method which is implemented in two places.

First place is in each execdriver as a part of the Driver interface. Each execdriver needs to implement the Info interface as a part of the Driver interface. Both native and windows implement it.
The second is in container/state,go where container implements the Info interface.

All the invocations of IsRunning() in the docker source reference the IsRunning() method is invoked with a Container or a Container.State receiver both of which reference the second implementation of IsRunning().

The first implementation, is currently required ONLY because it is a dependency of the Driver interface and the source would not compile if it wasn't there.

Solution:
The solution involves two things:
1. Decoupling the Info interface from the Driver interface in daemon/execdriver/driver.go
2. Remove the implementation of the Info interface from the execdrivers as this seems to have been 
    moved to container/state.go

Docker Version:
1.10.0-dev

Ping: @tonistiigi

**Comment by thaJeztah** [comment]
Thanks for reporting @amitkris; given that you've already given this a lot of thought, would you be interested in opening a pull request to make the suggested changes?

**Comment by amitkris** [comment]
@thaJeztah: Sure, I'd be happy to :). I just wanted to put this out there first to see if the issue (and the proposed fix) made sense to other people too.

**Comment by fangyuan930917** [comment]
It seems that when I remove Info interface from daemon/execdriver/driver.go, remove Info function from daemon/execdriver/native/driver.go and also remove daemon/execdriver/native/info.go, compile OK. so @thaJeztah shall I pull?

**Comment by thaJeztah** [comment]
@fangyuan930917 feel free to create a PR. I'm not sure if this duplication is in purpose of by accident, but we can discuss on the pull request

**Comment by thaJeztah** [comment]
Looks like we can close this one, because https://github.com/docker/docker/issues/19861 was merged :smile: Thanks @fangyuan930917 !
