### ISSUE TITLE
Improve error-handling if git is not installed

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#19375]
Trying to build from a github location if git is not installed, gives a non-informative error, because docker will try to build the HTML response;

    docker build github.com/docker/v1.10-migrator

or

    docker build https://github.com/docker/v1.10-migrator.git

actual result:

```
docker build https://github.com/docker/v1.10-migrator.git
Downloading build context from remote url: https://github.com/docker/v1.10-migrator.git 45.84 kB
Sending build context to Docker daemon 47.62 kB
Step 1 : <!DOCTYPE
Unknown instruction: <!DOCTYPE
```

**Comment by HackToday** [comment]
hi @thaJeztah Like to investigate this issue, although not familiar with build, if no one else pick it. I think it is good to learn that.

**Comment by thaJeztah** [comment]
@HackToday feel free to look into it! I think part of the "special" handling is in this file (was pointed to that this morning); https://github.com/docker/docker/blob/master/pkg/urlutil/urlutil.go; which is used here; https://github.com/docker/docker/blob/131e2bf12b2e1b3ee31b628a501f96bbb901f479/daemon/daemonbuilder/builder.go#L205

**Comment by HackToday** [comment]
OK @thaJeztah  I will take it and update comments further if have more findings

**Comment by thaJeztah** [comment]
oh, looks like @runcom already implemented a fix :cry:

**Comment by HackToday** [comment]
sure.  As 1.10 release is soon. so it is understood. :)
