### ISSUE TITLE
systemd start times out because docker is migrating a large number of containers (1.10.0-rc1)

### ISSUE THREAD

**Issue by vikstrous** [docker/docker#19380]
I'm using arch linux. I don't know if this is specific to the way the docker.service file is written for arch linux, but when I started docker systemd timed out trying to start it because docker was still busy doing migrations to the new manifest format. After starting it again it finished on time and started successfully. Hopefully killing docker unexpectedly in the middle of this migration is safe. Is there a way to convince systemd that docker has started and avoid this timeout? I'm not sure how systemd detects when docker is up. Maybe it checks if the unix socket is up?

My docker.service is below:

```
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target docker.socket
Requires=docker.socket

[Service]
Type=notify
ExecStart=/usr/bin/docker daemon -H fd:// --exec-opt native.cgroupdriver=cgroupfs -s overlay
MountFlags=slave
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity

[Install]
WantedBy=multi-user.target
```

Version:

Client:
 Version:      1.10.0-rc1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   677c593
 Built:        Fri Jan 15 18:17:17 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0-rc1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   677c593
 Built:        Fri Jan 15 18:17:17 2016
 OS/Arch:      linux/amd64

**Comment by thaJeztah** [comment]
Did you write that service file yourself? We recently removed the timeout from our service-file especially for this reason. See this PR; https://github.com/docker/docker/pull/18408

**Comment by vikstrous** [comment]
I just continued to use the one from 1.9. Sorry, disregard this.

**Comment by thaJeztah** [comment]
No problem, thanks!
