### ISSUE TITLE
Missing documentation: How do I register logging driver for docker?

### ISSUE THREAD

**Issue by cppexpert** [docker/docker#19388]
I couldn't find answer in documentation and neither stackoverflow not serverfault gave me answers. Thus I'm posting this question here.

I'm trying to use Amazon CloudWatch Logs logging driver as described in [this doc][1].

But I get following error when I launch my container

    Error response from daemon: Cannot start container 1769b857d0ed51cf30b1c160485c9eb05f68ab07a84eaf861893d9d55e6139c4: 
    Failed to initialize logging driver: 
    Failed to get logging factory: logger: no log driver named 'awslogs' is registered

How do I register driver for docker ? I added `--log-driver=awslogs` parameters to systed script of docker but it gives same error on restart of the daemon.

What should I do ?

---

expert@expert-x220:~$ docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:42:26 UTC 2015
 OS/Arch:      linux/amd64

expert@expert-x220:~$ docker info
Containers: 4
Images: 79
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 87
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.0-23-generic
Operating System: Ubuntu 15.10
CPUs: 8
Total Memory: 15.61 GiB
Name: expert-x220
ID: 3CN5:AOOV:DKXE:5WUH:HFTZ:2744:MU7U:REWH:LFPQ:M5K4:3SM5:WMXA
Username: expert
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

  [1]: https://docs.docker.com/engine/reference/logging/awslogs/

**Comment by cpuguy83** [comment]
awslogs was not added until 1.9.0
Logging drivers are all automatically initialized as they are all compiled in.
