### ISSUE TITLE
On Windows, docker container is not persisting data on stop/start or when committing to another image 

### ISSUE THREAD

**Issue by krishna81m** [docker/docker#19381]
Docker does not seem to be persisting container file changes when I stop/start or when I commit/save to an image and run the image.

Environment: Windows 7 laptop

$ docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
 
$ docker info
Containers: 32
Images: 279
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 343
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: AXXY:B6JJ:6M6W:LXME:VWED:BNEA:4MKU:LDP5:TWKR:CCUH:3SKV:BSBE
Debug mode (server): true
 File Descriptors: 28
 Goroutines: 46
 System Time: 2016-01-16T02:28:33.17774389Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

<code>

Steps:
-- get cassandra image
docker pull poklet/cassandra

-- run an image
docker run -v //c/docker-workspace/shared:/shared 66620dae02f5

-- attach to container

winpty docker exec -it 51434fcc59db bash

-- make a change to yaml file and save it

[root@51434fcc59db /]# vi /etc/cassandra/conf/cassandra.yaml

-- commit changes to container as a separate image

docker commit -a "my" -m "cassandra with schema, data, thrift v2" 51434fcc59db my-cassandra-with-schema-data-thrift-v2

-- run the new image

docker run -v //c/docker-workspace/shared:/shared f27a11694228

-- connect to container

winpty docker exec -it f27a11694228 bash
</code>

-- changes made to the new container image are lost ?
-- even container stop/start does not show my change ?

Repeated the same with pause=true and it does not work :-1: .

https://forums.docker.com/t/docker-container-not-persisting-data-on-stop-start-or-when-committing-to-another-image/5612

**Comment by krishna81m** [comment]
Hmm, I thought I provided most of the information you asked already.

**Comment by thaJeztah** [comment]
Looks like this isn't a bug in docker, but in that image; the command of the image will always overwrite your configuration with the default one upon start; see https://github.com/pokle/cassandra/blob/f46e178f845994b2466a153c2587577354b495bf/cassandra/src/start.sh#L23-L32

**Comment by friism** [comment]
@krishna81m (Gordon is an automated bot that reminds people to add all the required details)

**Comment by HackToday** [comment]
hi @krishna81m  as @thaJeztah  pointed, could you try another image?

**Comment by krishna81m** [comment]
Thanks @GordonTheTurtle :). 

Sorry, @thaJeztah, but I tried changing a parameter that was not in the start.sh script and still does not work :(.

<code>
start_rpc: false
</code>

Let me try adding a random file and repeat the above steps. And thanks for the prompt responses.

**Comment by thaJeztah** [comment]
@krishna81m note that the first step in `start.sh` is to [`rm -rf /etc/cassandra/conf`](https://github.com/pokle/cassandra/blob/f46e178f845994b2466a153c2587577354b495bf/cassandra/src/start.sh#L21-L23)

**Comment by krishna81m** [comment]
@thaJeztah, you are right again, sorry for the confusion. 

Just curious, how do I know which scripts run when I run an image? And when I stop a container, are there any scripts that I can run or know what scripts have run?

**Comment by thaJeztah** [comment]
The script that's run is the script or command that's specified as `CMD` or `ENTRYPOINT`. See the [dockerfile documentation](https://docs.docker.com/engine/reference/builder/), but there's no tool to check what an image is running, or what has run, apart from `docker logs` etc. So it really depends o the image.

**Comment by thaJeztah** [comment]
@krishna81m based on your reply, can I assume that this issue is resolved for you? Note that I'd report this issue in the https://github.com/pokle/cassandra repository; I think the startup script should be modified so that it isn't run again if it has already been run. Take for example, the official images, which always check if any action is needed; https://github.com/docker-library/wordpress/blob/2877506644eec86186d32e5aac19d6737f113efa/docker-entrypoint.sh#L38-L43

**Comment by krishna81m** [comment]
Thanks, so much

**Comment by krishna81m** [comment]
@thaJeztah are there any ways to return options/hints besides documentation to know all parameters that can be passed to run an image and find which script gets executed, at least the entry point? Am concerned when this image is shared with my colleagues, I will get the same questions. And every time some thing changes, I want to know without starting the container itself.

**Comment by thaJeztah** [comment]
@krishna81m no, unfortunately not, that really depends on the maintainer of the image.

If the entrypoint of an image is a binary, perhaps it could show help output with `--help`

Basically, this is the same as installing software the "regular" way; most of the time, you'd have to read some documentation, or a README, to know how to configure and install the software. I don't think Docker can change that.

**Comment by krishna81m** [comment]
Now I see: "unable to resolve host" on my windows containers. I could not find windows specific container issues, but could see that we may have to pass -dns=.. during 'docker run', but in my case the container is already up!


[root@d8174406546b /]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
50: eth0@if51: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP
    link/ether 02:42:ac:11:00:02 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.2/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe11:2/64 scope link
       valid_lft forever preferred_lft forever

[root@d8174406546b cassandradump]# cat /etc/resolv.conf
nameserver 192.168.1.1

[root@d8174406546b cassandradump]# python cassandradump.py --keyspace test --export-file test.cql
Python Cassandra driver not installed. You might try "pip install cassandra-driver".

 [root@d8174406546b cassandradump]# yum install cassandra-driver
Loaded plugins: fastestmirror
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was
14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
http://mirror.solarvps.com/centos/7.2.1511/os/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: mirror.solarvps.com; Unknown error"
Trying other mirror.
http://mirrors.tummy.com/mirrors/CentOS/7.2.1511/os/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: mirrors.tummy.com; Unknown error"
Trying other mirror.

**Comment by krishna81m** [comment]
Never mind, I manually updated resolv.conf to host's dns servers.
