### ISSUE TITLE
api-cors-header - what does it do?

### ISSUE THREAD

**Issue by ctammes** [docker/docker#19398]
docker version:
`Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64`

`Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64`

docker info:
`Containers: 42
Images: 887
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 977
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-74-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 2
Total Memory: 3.794 GiB
Name: chris-HP-Compaq-dc7900-Convertible-Minitower
ID: VU53:6ZWB:OYQE:3EMH:RJ2X:MQ43:JE33:EW5G:FTCM:CVW5:OGQI:ZNKP
WARNING: No swap limit support`

uname:
`3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

Question:
I have a Apache webserver container that runs a Angular app to access the Docker API. To make it work, I added a line to /etc/default/docker: 
`DOCKER_OPTS="-H tcp://192.168.8.11:2375 -H unix:///var/run/docker.sock --api-cors-header=*"`

When I issue GET requests and POST without data (like start/stop a container), it works fine. But when I try to remove a container (DELETE) or start a command (POST with data), I get a CORS related error: 
`OPTIONS http://192.168.8.11:2375/containers/9f0c4aaffc5a/exec 404 (Not Found)` 
followed by
`XMLHttpRequest cannot load http://192.168.8.11:2375/containers/9f0c4aaffc5a/exec. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8880' is therefore not allowed access. The response had HTTP status code 404.`
I used Anguler $http.post, jQuery and Ajax request, with all kind of options.

When I execute these commands with curl (from the host), they all work, so the syntax is correct.

I expected the proper headers to be added by the --api-cors-header option. Is that correct or am I mistaken?

**Comment by aidanhs** [comment]
I'm observing this. I assume the support for the `OPTIONS` method has gone missing somehow?

**Comment by aidanhs** [comment]
Found the culprit - #16539

We went

 - from https://github.com/docker/docker/pull/16539/files#diff-44a527ea72ea9572e1cf71c7f1e2a0f0L382, which has a special case at https://github.com/docker/docker/pull/16539/files#diff-44a527ea72ea9572e1cf71c7f1e2a0f0L399 to always handle OPTIONS with the same function
 - to https://github.com/docker/docker/pull/16539/files#diff-adb4da8df9d70a5f0b69b9afe8a591bcR96, which only handles options for the path at "/"

**Comment by aidanhs** [comment]
PR at #19569.
