### ISSUE TITLE
Don't break "-d" option yet until docker-machine released with "daemon"

### ISSUE THREAD

**Issue by jamshid** [docker/docker#19399]
The "-d" option no longer works, have to use "daemon". Would be cooler if it were kept working until a released version of docker-machine supports the new syntax.

 On a fresh install of 1.10rc1 on digitalocean, with latest docker-machine 0.5.6, 
```
$ docker-machine create --driver digitalocean  --digitalocean-access-token=X --digitalocean-size=4gb --engine-install-url https://test.docker.com docker110
...
Error creating machine: Error running provisioning: Unable to verify the Docker daemon is listening: Maximum number of retries (10) exceeded
$ docker-machine ssh docker110
#  sed --in-place 's/ -d / daemon /g'  /etc/systemd/system/docker.service
# systemctl daemon-reload && service docker restart && systemctl status docker
...
$ eval $(docker-machine env docker110)
```

Then watch out for: https://github.com/docker/docker/issues/19282, trying `--storage-driver overlay` to workaround that

**Comment by HackToday** [comment]
Seems docker machine need update old syntax.  Not sure how long it keep say deprecated for "-d".

Seem 1.9.1 has been said about it.

**Comment by vdemeester** [comment]
@jamshid I'm pretty sure `docker-machine` 0.6.0 has been updated to use `daemon` (see https://github.com/docker/machine/blob/8094d6ce52d7a0634f430a6620b02d6114c672d6/libmachine/provision/systemd.go#L44).

**Comment by jamshid** [comment]
@vdemeester yes, but 0.6.0 hasn't been released yet: https://github.com/docker/machine/releases. Just saying it would be nice if you didn't remove things from docker until a *released* version of docker-machine stops using it. It makes it much easier for users who want (or need) to use docker release candidates.

**Comment by vdemeester** [comment]
@jamshid `docker` engine 1.10 and `docker-machine` will be released the same day (both are in RC I guess). 

But yeah I see your point, the switch on using `daemon` instead of `-d` should probably have been done in `0.5.0` (or keeping the flag deprecated for one more version).

**Comment by nathanleclaire** [comment]
We'll work on getting this functionality in Machine before 0.6.0 / 1.10.

**Comment by nathanleclaire** [comment]
OK I checked on everything in our code and the only provisioner that seems to still be using `-d` is the CoreOS one, which I'll make a PR to revise.  As @vdemeester mentioned 0.6.0 will be released essentially at the same time as 1.10, and I think the `daemon` provisioning code is in 0.5.6 as well IIRC.

**Comment by vdemeester** [comment]
@nathanleclaire :+1: :heart_eyes_cat:

**Comment by jamshid** [comment]
I'm pretty sure I created my docker machine on digital ocean with the latest docker-machine 0.5.6, and if this is the change it's not in there:
https://github.com/docker/machine/commit/28b2fe9ce054d482be0174e5493274f1eab08108
but okay NBD feel free to close.

**Comment by nathanleclaire** [comment]
@jamshid Ah OK, looks like that change is very recent and flew under my radar.  At any rate, it will be in 0.6.0 (we're cutting the first RC soon too if you'd like to test).  Thanks for reporting the issue.

**Comment by thaJeztah** [comment]
@jamshid I see docker-machine 0.6.0-rc1 is available https://github.com/docker/machine/releases/tag/v0.6.0-rc1

**Comment by ethicalhack3r** [comment]
It looks as though both the ```-d``` flag and ```daemon``` flag have been deprecated from the ```docker``` command.

Although the change from ```-d``` to ```daemon``` was mentioned in the Github change logs, the deprecation of ```daemon``` wasn't.

For those like me who tried running ```-d``` (after reading online) then was presented with an error, then found it was deprecated for ```daemon``` in the change log, then got another error. Then could not find what replaced ```daemon```.

Not sure if the change log can be updated for those like me who might be looking to find a way to run the docker daemon.

**Comment by vdemeester** [comment]
@ethicalhack3r in 1.8.0, there is an entry in the changelog "Replace `docker -d` with new subcommand `docker daemon`", and as our deprecation policy state, `-d` been deprecated, it's removed in 1.10 (see https://github.com/docker/docker/blob/master/CHANGELOG.md#180-2015-08-11)

**Comment by ethicalhack3r** [comment]
Yea, ```-d``` was mentioned as being replaced by ```daemon``` but ```daemon``` being deprecated wasn't mentioned in the changelog.

That's what I meant when I said:

```Although the change from -d to daemon was mentioned in the Github change logs, the deprecation of daemon wasn't.```

**Comment by vdemeester** [comment]
The subcommand `daemon` is not deprecated :confused:

**Comment by ethicalhack3r** [comment]
This is what I get when I run the daemon command (on OS X):

```
$ docker daemon
docker: 'daemon' is not a docker command.
See 'docker --help'.
```

```
$ docker -v
Docker version 1.9.0, build 76d6bc9
```

**Comment by vdemeester** [comment]
@ethicalhack3r yes, that's normal if you are under OS X, because the OS X binary is *client only* as the daemon does not run under OS X (it runs inside a VM). A client-only binary does not have the `daemon` subcommand.

**Comment by ethicalhack3r** [comment]
Ah! Now I understand! I'm sure this is documented somewhere but I've not come across it yet. Sorry for hijacking the thread. I came across this thread when searching for a solution.

**Comment by thaJeztah** [comment]
@ethicalhack3r it's in the deprecations document; https://github.com/docker/docker/blob/master/docs/misc/deprecated.md#old-command-line-options

> Deprecated In Release: v1.8.0
> Target For Removal In Release: v1.10
> The flags -d and --daemon are deprecated in favor of the daemon subcommand:

**Comment by jamshid** [comment]
Looks like docker-machine 0.6.0 and later has the fix, so closing this.

**Comment by nathanleclaire** [comment]
Thanks for following up to close @jamshid
