### ISSUE TITLE
Proposal: Bind external source ip for container

### ISSUE THREAD

**Issue by mort1k** [docker/docker#19405]
Hi, 
solution host_ip:host_port:container_port .. good for destination ip binding for container, but what if you need to send packets with a external source ip (host has a few alias ip on interface). It makes sense to replace MASQUERADE with SNAT for such containers?

**Comment by mort1k** [comment]
Posible solution create bridge per alias ip with bridge.host_binding_ipv4 options

**Comment by mort1k** [comment]
Sorry, duplicate with https://github.com/docker/libnetwork/pull/788

**Comment by thaJeztah** [comment]
I'll close this here then
