### ISSUE TITLE
Cannot start container - memory.memsw.limit_in_bytes: invalid argument

### ISSUE THREAD

**Issue by RaphYot** [docker/docker#19406]
I keep getting this error about 10% of the times I try to start a container, I'm running docker 1.9.1 in CoreOS for a project where we need to rapidly create and delete containers.
The condition for this ti happen is to set the memory limit (tried "1g" or "1000000000").

The closest bug I found was #17387 but this one got closed because the memory limit was too low, minimum was 12-16mb, here I have much more.

Here is a step to repro (I sometimes need to run the for loop several times in a row) and more details about my env:

```
core@server ~ $ for i in {1..10}; do docker run -i --rm --memory=1g tianon/true; done
Error response from daemon: Cannot start container df673f834ef10b20ad8fb04b2ae70f2ec70a63fd653f3a451bd9d9d724b6fb57: [8] System error: write /sys/fs/cgroup/memory/system.slice/docker-df673f834ef10b20ad8fb04b2ae70f2ec70a63fd653f3a451bd9d9d724b6fb57.scope/memory.memsw.limit_in_bytes: invalid argument

```

# BUG REPORT INFORMATION

Use the commands below to provide key information from your environment:

``` 
docker version:
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   9894698
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   9894698
 Built:        
 OS/Arch:      linux/amd64
```

```
docker info:
Containers: 125
Images: 220
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.4.0-coreos
Operating System: CoreOS 928.0.0
CPUs: 16
Total Memory: 62.92 GiB
Name: server
ID: M7TQ:GEBC:YBFK:CWEP:6ZYP:YQSZ:3P4K:QT2W:B5T3:PIB6:2IVD:3YIF
```

Provide additional environment details (AWS, VirtualBox, physical, etc.): We are running our own server in CoreOS (we run on top of kubernetes, but I can reproduce this natively)

List the steps to reproduce the issue:
1. Quickly run a container with memory limit, like this I can repro it about once over 10:
```
$ for i in {1..10}; do docker run -i --rm --memory=1g tianon/true; done
Error response from daemon: Cannot start container df673f834ef10b20ad8fb04b2ae70f2ec70a63fd653f3a451bd9d9d724b6fb57: [8] System error: write /sys/fs/cgroup/memory/system.slice/docker-df673f834ef10b20ad8fb04b2ae70f2ec70a63fd653f3a451bd9d9d724b6fb57.scope/memory.memsw.limit_in_bytes: invalid argument
```

Describe the results you received:

Docker run crash, with memory.memsw.limit_in_bytes: invalid argument

Describe the results you expected:

- 

Provide additional info you think is important:

- 

----------END REPORT ---------

#ENEEDMOREINFO

**Comment by thaJeztah** [comment]
I have not yet been able to reproduce this so far, will try on some other machines

**Comment by unclejack** [comment]
I think I've seen this a few times when starting and stopping a lot of containers when using plugins.

**Comment by RaphYot** [comment]
We moved our platform to a new provider, and didn't see the issue for a while, I thought it was resolved.
However, it does occur again. We are indeed starting and stopping a lot of short lived containers in our system.
It seems this issue occurs after a while, but I can't quantify it.

**Comment by RaphYot** [comment]
Thanks to @philips found a workaround for this one, changed the CoreOS default systemd exec driver for cgroups to cgroupfs and I can't reproduce that issue anymore:

`--exec-opt native.cgroupdriver=cgroupfs`

**Comment by thaJeztah** [comment]
@RaphYot ah! We actually changed this to be the default in Docker 1.10 (see https://github.com/docker/docker/pull/17704), given that there's still a lot of issues in systemd cgroups. Also see https://github.com/docker/docker/pull/20633/files

Given the above, I'll close this issue, but feel free to comment after I've closed

**Comment by RaphYot** [comment]
@thaJeztah Thanks! That should work for us at the moment.
