### ISSUE TITLE
Build my own bridge always failed on Debian 8.

### ISSUE THREAD

**Issue by kenchowcn** [docker/docker#19402]
This issue was been published on [here](https://github.com/docker/docker/issues/18793), it seems like no one fixed it, maybe the issue title is not consistent with content, anyway, I'm going to commit it again.

```bash
root@debian:/tmp# docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 12:59:02 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 12:59:02 UTC 2015
 OS/Arch:      linux/amd64
root@debian:/tmp# docker info
Containers: 3
Images: 4
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 10
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 1
Total Memory: 1000 MiB
Name: debian
ID: 6DVR:NQ6T:5QHS:L3EW:4HQM:6JUW:VFV5:4FRS:SC7X:Z3SI:TT34:4DIQ
WARNING: No memory limit support
WARNING: No swap limit support
root@debian:/tmp# uname -a 
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux
root@debian:/tmp# cat /etc/issue
Debian GNU/Linux 8 \n \l
root@debian:/tmp# 
```

[Build your own bridge](https://docs.docker.com/engine/userguide/networking/default_network/build-bridges/), I fellow this article to build my own bridge.

1. I am pretty sure I've deleted succeed the default dev docker0, but when I started docker service, the docker0 will been created automatically with docker startup script.

2. Then I tried to modify  DOCKER_OPTS in  /etc/init.d/docker, the dokcer0 still come up with start script.

Thanks.

**Comment by unclejack** [comment]
@kenchowcn Please don't open another issue if there's an open issue which matches the problem you're seeing. Having multiple duplicate issues makes it difficult to keep track of these issues and it also makes it more difficult to provide help.

I will update the title on the other issue and close this issue now. Thank you for understanding. Please feel free to continue the discussion on the other issue.
