### ISSUE TITLE
Error "unsupported manifest mediatype: application/json" pulling jfrog-docker-reg2.bintray.io (1.10rc1)

### ISSUE THREAD

**Issue by jamshid** [docker/docker#19400]
This is probably an jfrog / artifactory issue, but since it worked in docker 1.9.x maybe something can be done for backwards compatibility.

```
$ docker pull jfrog-docker-reg2.bintray.io/jfrog/artifactory-oss:4.3.3
Error response from daemon: unsupported manifest mediatype: application/json
```
```
$ docker info
Containers: 8
Images: 61
Server Version: 1.10.0-rc1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.0-16-generic
Operating System: Ubuntu 15.10
CPUs: 2
Total Memory: 3.86 GiB
Name: docker110
ID: JKER:Q4EU:JYCI:37P2:TR7B:O4KM:W77J:WJLK:YPS3:JD4G:ZYW5:64LA
WARNING: No swap limit support
Labels:
 provider=digitalocean
```

**Comment by thaJeztah** [comment]
Thanks for reporting, I'll add this to the milestone for now, given that it's a regression from 1.9.x, but we should look into it if it's something that needs fixing in docker or in artifactory

**Comment by thaJeztah** [comment]
ping @aaronlehmann I'll assign you to this one, can you check if this is something to be fixed here, or by artifactory?

**Comment by thaJeztah** [comment]
Prio P1; we need a *decision* before the release (or a fix)

**Comment by jamshid** [comment]
WORKAROUND: if you're blocked by this problem with jfrog artifactory on docker 1.10rc, you can `save` (not `export`) the image on a docker 1.9.x:
```
$ docker pull jfrog-docker-reg2.bintray.io/jfrog/artifactory-oss:4.3.3
...
$ docker save -o /tmp/art.tar jfrog-docker-reg2.bintray.io/jfrog/artifactory-oss:4.3.3
...
```
then in docker 1.10rc just `load` the tar:
```
$ docker load < /tmp/art.tar
$ docker images
...
jfrog-docker-reg2.bintray.io/jfrog/artifactory-oss   4.3.3               sha256:901f5        3 weeks ago         442.1 MB
```

**Comment by aaronlehmann** [comment]
1.10 attempts to handle this case, but it looks like it expects `charset=utf-8` in the content type: https://github.com/docker/distribution/blob/master/manifest/schema1/manifest.go#L54

I will open a PR to make this more flexible.

**Comment by thaJeztah** [comment]
Thanks for looking into this @aaronlehmann :+1:
