### ISSUE TITLE
Support async connections to fluent servers

### ISSUE THREAD

**Issue by pcarrier** [docker/docker#19438]
`github.com/docker/docker/daemon/logger/fluentd` currently blocks on connecting to `fluend`, and fails to start new containers if it cannot be reached.

There are plenty of scenarios where this is not the desired behaviour; the most obvious one is that `fluend` might be started in a local container.

`fluent-logger-golang` got support for async connections through fluent/fluent-logger-golang#25; we simply need to update the dependency and add an option to our logger.

The PR will use a git commit on this dependency unless we get a new release in the meantime; it was requested in fluent/fluent-logger-golang#26.

**Comment by mlaventure** [comment]
@pcarrier can you close this now that #19439 was merged?
