### ISSUE TITLE
Reverse engineering docker container

### ISSUE THREAD

**Issue by stgleb** [docker/docker#19443]
Is there any way how to get Dockerfile from existing containter or image?

**Comment by cyphar** [comment]
Unfortunately, there's some information that's lost (mainly `COPY` commands). However, if you look at the value of `cmd` in `docker inspect` you should be able to figure some of it out.

**Comment by mohan08p** [comment]
I think, this is the best resource for reverse engineering on docker images,
 https://github.com/CenturyLinkLabs/dockerfile-from-image

**Comment by unclejack** [comment]
As was written above, those `docker inspect` and the tool mentioned above can be used to do something like this.

I'll close this issue now since this question was answered. Please feel free to comment and to continue  the discussion.
