### ISSUE TITLE
Named volume is deleted after a first containter using it is run with "autoremove" option.

### ISSUE THREAD

**Issue by ashumkin** [docker/docker#19446]
Steps to reproduce:

1. Create a named volume.
`$ docker volume create --name <named_volume>`

 1.1. It is listed in volumes
`$ docker volume ls`
`DRIVER              VOLUME NAME`
`...`
`local               <named_volume>`
`...`
  1.2. So far in **/var/lib/docker/volumes**:
`$ ls -l /var/lib/docker/volumes/`
`...`
`drwxr-xr-x 3 root root   4096 Jan 19 13:50 <named_volume>`
`...`

2. Then I "put" a file "into it"
`$ echo file content > /var/lib/docker/volumes/<file>`

3. run a container with **--rm** option
`$ docker run -v <named_volume>:/volume --rm busybox sh -c 'ls -l /volume; cat /volume/<file>'`
`total 4`
`-rw-r--r--    1 root     root            13 Jan 19 11:34 file`
`file content`

4. run step 3 again. It fails to find **/volume/file** file:
`$ docker run -v <named_volume>:/volume --rm busybox sh -c 'ls -l /volume; cat /volume/<file>'`
`total 0`
`cat: can't open '/volume/file': No such file or directory`

Listing docker volumes gives no `<named_volume>` volume, so far no `/var/lib/docker/volumes/<named_volume>` directory.

As for me, this goes against [Docker Data Volume docs](https://docs.docker.com/engine/userguide/dockervolumes/)
> Data volumes are designed to persist data, independent of the container’s life cycle. Docker therefore **never automatically delete volumes when you remove a container**, nor will it “garbage collect” volumes that are no longer referenced by a container.

$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:08:59 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:08:59 UTC 2015
 OS/Arch:      linux/amd64

$ docker info
Containers: 8
Images: 38
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 54
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-32-generic
Operating System: Ubuntu precise (12.04.5 LTS)
CPUs: 2
Total Memory: 1.737 GiB
Name: drcis
ID: 7V5F:V5ON:S6MS:7UGI:3NBZ:G76R:CIIJ:N5PS:P7HD:RYAC:5H2M:VTOH
WARNING: No swap limit support

**Comment by coolljt0725** [comment]
@ashumkin  The volume was deleted because you use `--rm` option. With `--rm` option, the volume will be deleted if there is no other container referenced to this volume.

**Comment by ashumkin** [comment]
@coolljt0725, thanks
_here goes [Docker run docs reference](https://docs.docker.com/engine/reference/run/#clean-up-rm)_

But this doc (I consider it important) is missing in `man docker-run` which only contains
>      --rm=true|false
>          Automatically remove the container when it exits (incompatible with -d). The default is false.

**Comment by phemmer** [comment]
See also #17907
The behavior you are experiencing is not the desired behavior. It was just an oversight when volume management was implemented.
