### ISSUE TITLE
[1.10-rc1] "name is reserved" when multiple links are defined with the same alias

### ISSUE THREAD

**Issue by aanand** [docker/docker#19444]
`docker version`:

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.0-rc1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   677c593
 Built:        2016-01-15T18:17:17.209731962+00:00
 OS/Arch:      linux/amd64
```

`docker info`:

```
Containers: 96
Images: 30
Server Version: 1.10.0-rc1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 226
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.15-boot2docker
Operating System: Boot2Docker 1.10.0-rc1 (TCL 6.4.1); master : c4985d5 - Fri Jan 15 19:29:39 UTC 2016
CPUs: 1
Total Memory: 996.2 MiB
Name: 1.10.0-rc1
ID: 5FI2:BCQZ:BB7O:3EOF:B4OB:NNHW:32UJ:UG22:G66I:JTFB:STWC:MH4Z
Debug mode (server): true
 File Descriptors: 27
 Goroutines: 45
 System Time: 2016-01-19T11:09:10.738547534Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: aanand
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Provide additional environment details (AWS, VirtualBox, physical, etc.):**

VirtualBox boot2docker VM created with the following command:

    docker-machine create -d virtualbox --virtualbox-boot2docker-url=https://github.com/tianon/boot2docker-legacy/releases/download/v1.10.0-rc1/boot2docker.iso 1.10.0-rc1

**List the steps to reproduce the issue:**

```
$ docker run -d --name upstream-a busybox top
$ docker run -d --name upstream-b busybox top
$ docker run --link upstream-a:upstream --link upstream-b:upstream busybox cat /etc/hosts
```

**Describe the results you received:**

```
Error response from daemon: name is reserved
```

**Describe the results you expected:**

Contents of hosts file (as happens on Engine 1.9.1)

**Provide additional info you think is important:**

This error is returned when I try and create multiple links with the same alias. Arguably, users should never do this, but unfortunately Compose has been doing it for years.

Engine's previous behaviour was that one link would win out - if I run those commands against Engine 1.9, `upstream-a` seems to win every time, but I don't imagine it matters which one wins.

We can (and probably should) fix it in Compose of course, but that won't help people who, for whatever reason, are stuck with an older version of Compose and a newer version of Engine. So depending on how hard it is, it'd be preferable to have it fixed in Engine.

**Comment by cpuguy83** [comment]
This really should have errored in prior versions of Docker too... and when I say "should" I mean, based on the old code path I'd expect an error in this case... but there were also some race conditions around name registration that masked errors before as well.

I'm not sure that we can really change this as link names (on the default bridge network) are used as container references and must be unique... so one can lookup a container by <parent name>/<alias>.

With user-defined networks it's no problem as link names are not used as container refs.

**Comment by cpuguy83** [comment]
I've added this to the milestone since this is a change in behavior since 1.9 and we should decide if we need to handle this case.

**Comment by thaJeztah** [comment]
Note that this *does* seem to work with a custom network (and DNS based resolution);

```
docker network create foozbar
docker run -d --name upstream-a --net foozbar busybox top
docker run -d --name upstream-b --net foozbar busybox top

docker run --net foozbar --link upstream-a:upstream --link upstream-b:upstream ubuntu ping -w 4 upstream
PING upstream (172.18.0.3) 56(84) bytes of data.
64 bytes from upstream-b.foozbar (172.18.0.3): icmp_seq=1 ttl=64 time=0.171 ms
64 bytes from upstream-b.foozbar (172.18.0.3): icmp_seq=2 ttl=64 time=0.152 ms
64 bytes from upstream-b.foozbar (172.18.0.3): icmp_seq=3 ttl=64 time=0.134 ms
64 bytes from upstream-b.foozbar (172.18.0.3): icmp_seq=4 ttl=64 time=0.157 ms
64 bytes from upstream-b.foozbar (172.18.0.3): icmp_seq=5 ttl=64 time=0.184 ms

--- upstream ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 3997ms
rtt min/avg/max/mdev = 0.134/0.159/0.184/0.021 ms
```

**Comment by cpuguy83** [comment]
@thaJeztah Yes, that's expected. User-defined networks don't have the same semantics, and aren't registered as actual links.
