### ISSUE TITLE
Support sequential log filenames in logger/jsonfilelog

### ISSUE THREAD

**Issue by pcarrier** [docker/docker#19440]
Tools might want to follow log files, for example to forward them centrally.

For some particular needs, there currently isn't a satisfying logging driver in docker itself.

One of our use cases is a log forwarder running in docker locally, performing rate limiting and forwarding to arbitrary backends based on each container's environment.

For those purposes, a simple design is for such service to consume the logs from `logger/jsonfilelog`.

Unfortunately, watching over the JSON files and tracking changes is currently very painful, as every log rotation moves `.log.${N}` to `.log.${N+1}`, `.log.${N-1}` to `.log.${N}`, ..., `.log` to `.log.1`.

In particular:
- it's hard to make sure we don't have a race condition or process the same log file twice;
- it's hard to determine whether we completely missed files that have now been rotated
- any heuristics for the problems below are pretty nasty and rely on persisting a non-trivial amount of state shared across restarts of the log forwarder (notably involving inode numbers), or assuming that the clock is monotonic.

A simple solution would be to have an option for sequential logging, which would log to `.log.0` then `.log.1` then `.log.2`, etc.; log files would never be renamed, only created, appended to then deleted.

**Comment by cpuguy83** [comment]
The current behavior is standard for log rotation. I'm not sure that we'd want to change it.

**Comment by pcarrier** [comment]
@cpuguy83 the suggestion would be to make this an optional behaviour, not change the default behaviour.

**Comment by thaJeztah** [comment]
Not convinced either; as @cpuguy83 mentions, this is the standard way for log-rotation, not specific to docker?

**Comment by pcarrier** [comment]
I understand it's what Unix systems have been doing by default for a long time.
That doesn't make it right for everyone, certainly not an argument to discard offering alternatives.

It's more efficient in environments that churn through a lot of small files, as you avoid a lot of `rename` syscall. But that doesn't really matter all that much.

I've seen many services completely ignore that model `.log`, `.log.1` and use `$name.log.$date` or `$name.log.$date.$hour`. Just in the Docker world, `ecs-agent` behaves that way. I've worked for 2 companies that reconfigured syslog to behave that way.

If you've ever tried to reliably watch-and-tail log files, you should appreciate how much better the create/append/close model is compared to watching all files, try to guess what the last file read is now called, etc.

If you've had to asynchronously replicate logs centrally, you should also understand how nice it is to be able to `cron` an `rsync` and call it a day, later to build something better, but that still relies on filenames being immutable.

I really want to claim that immutable files are better overall, I'll settle on claiming that there are solid reasons to prefer them in some environments.

**Comment by cpuguy83** [comment]
@pcarrier The issue is the use-case of the json logger.
Frankly, nobody should be touching these files directly (or anything at all in `/var/lib/docker`).
Docker provides an API to tail these logs which supports spanning across multiple files.

If you want to get the logs to some other agent, then you shouldn't be using the json log driver. There are many other supported logging drivers that are much better for this.

**Comment by LK4D4** [comment]
Yeah, it's quite dangerous to depend on those files. For collecting use-cases it's better to use syslog driver IMO.
