### ISSUE TITLE
docker 1.9.1 doesn't support --log-opt labels or --log-opt env despite being within an example in the docs.

### ISSUE THREAD

**Issue by ajohnstone** [docker/docker#19450]
docker 1.9.1 doesn't support --log-opt labels or --log-opt env despite it being validated.  

https://github.com/docker/docker/blob/v1.9.1/daemon/logger/jsonfilelog/jsonfilelog.go#L201-L202

```
--log-opt max-size=[0-9+][k|m|g]
--log-opt max-file=[0-9+]
--log-opt labels=label1,label2
--log-opt env=env1,env2
```

logs will only contain the following... missing labels and env

```
{"log":"xxx\r\n","stream":"stdout","time":"2016-01-19T16:03:51.634609436Z"}
```

The log options should

**Comment by HackToday** [comment]
hi @ajohnstone  where do you get docs said support it for 1.9.1 ?

**Comment by ajohnstone** [comment]
@HackToday Thanks for the quick response. https://docs.docker.com/engine/reference/logging/overview/

1. ```docker daemon --log-driver=json-file --log-opt labels=foo --log-opt env=foo,fizz``` In the examples. 
2. Its valid within the validation of the docker jsonfilelog.go
3. json-file opts describe in the above documentation describes
```
--log-opt max-size=[0-9+][k|m|g]
--log-opt max-file=[0-9+]
--log-opt labels=label1,label2
--log-opt env=env1,env2
```

**Comment by vdemeester** [comment]
@ajohnstone how did you start your container ? which `labels` and `env` variables did it have ? We miss a few informations to be able to debug it..

```bash
$ docker daemon --log-driver=json-file --log-opt labels=foo --log-opt env=foo,fizz
# Should put foo=bar in logs (in an attributes map if I recall in `jsonfile` logs)
$ docker run -itd --label foo=bar busybox
```

**Comment by ajohnstone** [comment]
Apologies, i've mis-interpreted the implementation and/or my test environment.

It is working correctly.

**Comment by pablogrs** [comment]
@ajohnstone Hi Andrew, I know this has been closed for a while, but how did you manage to add the labels to your log? I am a bit stuck there. I am deploying with Ansible, and it would look like I have labels by the information provided by docker inspect 

```
            "LogConfig": {
                "Type": "json-file",
                "Config": {
                    "labels": "container=elasticsearch",
                    "max-file": "3",
                    "max-size": "1m"
```

but I don't 😿 
Thank you

**Comment by pablogrs** [comment]
@ajohnstone Hi Andrew, I know this has been closed for a good while, but I am facing the same difficulty. I thought I had solved it by the docker inspect results: 
```
            "LogConfig": {
                "Type": "json-file",
                "Config": {
                    "labels": "logstash",
                    "max-file": "3",
                    "max-size": "1m"
                }
```
but then the label will not appear in the logs? So I definitely haven't solved it 😿 
Any help gladly welcome.

Thanks, Pablo

**Comment by pablogrs** [comment]
I think I managed, not using quotes in Ansible did the trick

```
    log_driver: "json-file"
    log_opt:
      labels: container_name
    labels: container_name=elasticsearch
```
