### ISSUE TITLE
Daemon configuration not preserved on reboots in boot2docker

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#19454]
This is a boot2docker issue, but adding it here so that we can track it in the milestone.

Starting in docker 1.10, a persistent configuration file can be stored (/etc/docker/daemon.json) for daemon options (see https://github.com/docker/docker/pull/18587). However, boot2docker currently doesn't preserve this configuration upon reboot.

To make this feature useful, also when running in boot2docker, boot2docker should be modified to preserve the settings file.

A pull request is currently open to facilitate this; https://github.com/boot2docker/boot2docker/pull/1121

/cc @tianon @SvenDowideit @crosbymichael (for boot2docker)

**Comment by tiborvass** [comment]
Fixed in boot2docker/boot2docker#1121
