### ISSUE TITLE
1.10-rc1 cannot be installed on ubuntu-vivid via `curl -fsSL https://test.docker.com/ | sh`

### ISSUE THREAD

**Issue by awh** [docker/docker#19451]
As above - the vivid package is missing from the pool and the dist metadata.

**Comment by cpuguy83** [comment]
IIRC, is because Vivid goes EOL before 1.10 is released.

ping @thaJeztah

**Comment by awh** [comment]
> IIRC, is because Vivid goes EOL before 1.10 is released.

Ahh, fair enough - of course there are trusty packages because that's an LTS release. Thanks!

**Comment by HackToday** [comment]
Check this
https://github.com/docker/docker/pull/18809


It is EOL, it seems removed

**Comment by awh** [comment]
Thanks folks.

**Comment by thaJeztah** [comment]
Thanks for the inconvenience @awh, we realize we're slightly early removing it already, but didn't want the release to go out with packages for a soon-to-be EOL'd distro.

We're trying to improve communicating this and added a note to the release-notes this time;

> Deprecate docker packages for newly EOL'd Linux distributions: Fedora 21 and Ubuntu 15.04 (Vivid) #18794, #18809

To get some feedback; do you think we should emphasize that more?

**Comment by awh** [comment]
No problem. You might find a few people are surprised by the EOL of vivid (I certainly was!) especially given that the previous release was LTS and so they're not used to things being deprecated so quickly - not sure there's a lot you can do about it upfront though.

**Comment by thaJeztah** [comment]
Cool, thanks!

**Comment by beetree** [comment]
I am troubled by the lack of emphasis on this, let alone the decision to not support 15.04.

Texts like [the main installation instructions for Ubuntu](https://docs.docker.com/engine/installation/ubuntulinux/) state that 15.04 is a supported distribution. Similarly, there is no mentioning of non-support for 15.04 in the actual [release note](https://github.com/docker/docker/releases/tag/v1.10.0-rc1).

15.04 is used by a lot of users and it would be great if you could save us the time of figuring these types of things out for ourselves. It took me a good hour of testing and reading until I ended up on this thread.

**Comment by thaJeztah** [comment]
@beetree I'll make sure we emphasize the deprecation more clearly; we won't he releasing packages for AOL's versions though; they're no longer supported upstream, which would make it very difficult for us to guarantee they keep working during our release cycle. The upcoming 16.04 release is a LTS release, so may he a good choice if stability is desired.

**Comment by beetree** [comment]
@thaJeztah That's okay. Makes sense.

Any chance you could give a recommendation on what base OS I should be using? I started off with CentOS 7.1 to avoid overly frequent OS updates, but I encountered some bugs which moved me to Ubuntu that seems to be more well supported. What base OS would you recommend people use?

**Comment by thaJeztah** [comment]
@beetree oh, that's a difficult question to answer, and really depends a lot on your personal preference. CentOS / RHEL have an extremely long support duration, but that also comes at a cost; you won't get updated packages and kernels, only fixes for the existing ones.

For that reason, I'm more a Debian/Ubuntu person, which gives me a more recent kernel (but then again, that's my preference, feel free to disagree).

Looking at it from another viewpoint; Docker makes your projects a lot less dependent on the system it's running on; apart from docker, and the basic packages that are needed for running it; what do you actually install on the host? Unless you're managing your own (bare metal) servers, replacing docker nodes is easy; if you're regularly updating (replacing) containers, decommissioning a node can be part of that process, and allows you to keep your hosts on an up-to-date system (and kernel).
