### ISSUE TITLE
Docker 1.8.2 doesn't pull tags correctly

### ISSUE THREAD

**Issue by gaga-github** [docker/docker#19461]
When I do a docker pull in 1.7.1(Docker version 1.7.1, build 3043001/1.7.1):
GET|/api/docker/docker-compass/v1/repositories/jenk6/images|HTTP/1.0|200|0
GET|/api/docker/docker-compass/v1/repositories/jenk6/tags|HTTP/1.0|200|0

For some reason in 1.8.2, it add /latest to the tags pull and it getting a 405, it doesn't work

GET|/api/docker/docker-compass/v1/repositories/jenk6/images|HTTP/1.0|200|0
GET|/api/docker/docker-compass/v1/repositories/jenk6/tags/latest|HTTP/1.0|405|0

Is there a way to cut the /latest from the call?

Docker version 1.8.2-el7.centos, build a01dc02/1.8.2

**Comment by tophj-ibm** [comment]
That's because docker pull by default looks for an image with the tag 'latest' if one isn't given.

I can't see the repo / image you are pulling from, but you should be able to check under the tag tab to get a valid one. Then you should be able to do 'docker pull REPONAME/IMAGENAME:TAG'

**Comment by gaga-github** [comment]
When I do a docker pull IMAGE in 1.7.1 the URL I see in the repo is
GET|/api/docker/docker-compass/v1/repositories/jenk6/tags
Which replies with:
{
  "latest" : "5ea654d93265dcf0efcdebcc38cfd932ce7355a35e69b1dd60df9772d09e4b73"
}

In 1.8.2 for some reason the url called is changed when I run docker pull IMAGE
GET|/api/docker/docker-compass/v1/repositories/jenk6/tags/latest

{
  "errors" : [ {
    "status" : 405,
    "message" : "Method Not Allowed"
  } ]
}

**Comment by thaJeztah** [comment]
Are you using a private repository?

Also note that the docker version you're running is a modified version of Docker that's supported through Red Hat, so perhaps this question should be asked in http://bugzilla.redhat.com

**Comment by calavera** [comment]
Sorry, we cannot help you with versions of docker that we don't compile. We don't even know what's in those. Closing.
