### ISSUE TITLE
[1.10]: Invalid auth for pull no longer sends meaningful error message

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#19476]
If I send that wrong credentials for a pull I now get ``Error response from daemon: Get https://registry-1.docker.io/v2/tianon/true/manifests/latest: <nil>`.  Obviously that error is not very helpful.  Previously the error message would say `Authentication is required`.

**Comment by thaJeztah** [comment]
ping @tonistiigi @aaronlehmann

**Comment by aaronlehmann** [comment]
@ibuildthecloud: Do you have a set of steps to reproduce this? If I give bad creds to `docker login`, the login fails, and it doesn't seem to use those credentials when I pull `tianon/true`. The pull suceeds. Are you using the daemon API directly?

**Comment by aaronlehmann** [comment]
Managed to reproduce it by manually editing `~/.docker/config.json` (thanks @tonistiigi for the tip).

**Comment by ibuildthecloud** [comment]
@aaronlehmann sorry for the delay, screwing with the config.json was how I reproduced it also.

**Comment by calavera** [comment]
It's not completely fixed. Reopen

**Comment by tiborvass** [comment]
@calavera The part that's not completely fixed is described in https://github.com/docker/docker/issues/19523.

This current issue was about not having a meaningful error, I think that is now fixed. I'm closing this issue but feel free to correct me if you think i'm wrong.
