### ISSUE TITLE
[1.10] How to disable embedded DNS?

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#19474]
Ask you could probably guess, not everybody wants their DNS requests intercepted.  How does one disable the embedded DNS server?  I'm sure it's in the docs somewhere but I didn't see it.

**Comment by mavenugo** [comment]
@ibuildthecloud we replaced the /etc/hosts based SD (in 1.9) with embedded DNS. We couldn't make it pluggable in this release. Contributions welcome.

**Comment by thockin** [comment]
Wait, so any container that wants to use port 53 will fail?  Is that what I
am reading?

**Comment by mavenugo** [comment]
@thockin I think you should give it a try.

>> Wait, so any container that wants to use port 53 will fail? Is that what I am reading ?

No. You are reading it incorrectly.

**Comment by brendandburns** [comment]
@mavenugo so how do I disable the DNS server?

**Comment by mavenugo** [comment]
@brendandburns DNS server is disabled by default for all the user-defined networks. The embedded DNS server is enabled only for user-defined networks. and it can be expanded with `--dns` for any external DNS servers.

Can you please explain your use-case ? Is it for k8s ? In that case, I guess you are interested in non-user-defined networks ?.

**Comment by thockin** [comment]
We need to consider both "default" network (bridge) and user-defined
networks (bridge, overlay, and 3rd party).  Any incursion on ports inside
the containers seems unacceptable.

**Comment by mrjana** [comment]
@thockin There is no incursion of port 53 inside the container i.e you can run an actual DNS server inside a container if you want regardless

**Comment by thockin** [comment]
Hmm, then I mis-parsed how the embedded DNS server works - how does one
access it?

https://github.com/docker/libnetwork/blob/master/resolver.go#L14

**Comment by ibuildthecloud** [comment]
@thockin `/etc/resolv.conf` is set as follows

```
nameserver 127.0.0.11
options ndots:0
```

And iptables is set to

```
-A OUTPUT -d 127.0.0.11/32 -p udp -m udp --dport 53 -j DNAT --to-destination 127.0.0.11:49669
-A POSTROUTING -s 127.0.0.11/32 -p udp -m udp --sport 49669 -j SNAT --to-source :53
```

And somehow something magically listens in the network namespace of the container.

**Comment by ibuildthecloud** [comment]
@mavenugo Can't we just add a simple flag on network create?  Can custom network drivers opt out of the DNS server?

**Comment by mrjana** [comment]
@ibuildthecloud This just replaces the existing /etc/hosts behavior. There is no functionality change at all. Earlier an /etc/hosts file was intercepting the name resolution requests. Now an embedded DNS server is intercepting the request. What was working before in 1.9 for you that is not going to work now?

**Comment by ibuildthecloud** [comment]
@mrjana The difference just being that you are putting a component in the critical data path.  Editing the host files just uses existing resolver code that has been around for awhile.  Putting a DNS server in the path is a whole different ball game.  At Rancher we've written our DNS server, (just like everyone has these days.  I think it's a new hello world in go), and have already dealt with issues with things we never thought of (compression, odd AAAA records, Windows wackiness).  So the point being, you're asking a lot of users to immediately and always trust that your DNS server works, with no fallback.

@mrjana What actually listens for DNS?  Is this the docker daemon itself?  I'd like to understand how you do the magic of binding to the sock in the networking namespace of the container.

**Comment by brendandburns** [comment]
To be honest, we really wanted to disable the `/etc/hosts` behavior too, since it led to corrupt `/etc/hosts` files (https://github.com/docker/docker/issues/17190) but that didn't happen.

I agree @ibuildthecloud this is about 1000x more complicated than changing the `/etc/hosts` file to add some new static hosts, and even that led to corruption.  If your DNS server breaks, containers basically stop working entirely, that's a pretty severe risk.

For production users, this _has_ to be disableable.

**Comment by thockin** [comment]
Hmm, I misparsed the .11 as .1, I guess.  Sorry for that.  This is ... less
bad in an obvious way, but still has a smell to it.  Consuming an ephemeral
port is far less likely to be a problem, at least.

I don't have an RC installed yet - if I pass my own --dns and --dns-search,
does this DNS server get removed or is it prepended or appended to my own
list?  Given this bug, I assume it is not replaced. Linux has a hard limit
of 3 `nameserver` lines, so this is still a significant incursion.

Also - does this embedded server forward to my own DNS servers?  We learned
the hard way that `nameserver` lines should be interchangeable (i.e. not
have 1 that just serves X while another serves Y) or else suffer the
vagaries of the myriad DNS resolvers (and total lack of a spec).

**Comment by ibuildthecloud** [comment]
@thockin @brendandburns For the default network, the "bridge" network, the embedded DNS server is not enabled.  This is only if you do `docker network create foo`, then `foo` will have the embedded DNS server enabled.  I don't think there is any immediate impact on k8s, just that this stands as another barrier to k8s using Docker network drivers.

**Comment by mrjana** [comment]
The embedded DNS server is really a light weight server only interested in responding to container name/alias queries (which were earlier present as /etc/hosts records) and for everything else it just acts as the proxy to any other DNS server you have configured including Rancher's own DNS server if that's what you want your users to use.

We create a socket in the container namespace and listen on it in the daemon itself and respond queries using that. The socket acts as the demux identifier to identify the network in case of unqualified name queries.

**Comment by thockin** [comment]
@mrjana

a) how do I configure what server(s) it forwards to?
b) how do I configure upstream timeouts?
c) I still don't want it - it's antithetical to our setup, and we really
just want to bypass it

**Comment by ibuildthecloud** [comment]
@mrjana Yeah, I know, it's based on the same library everyone uses https://github.com/miekg/dns.  Still a shame you can't disable it.  If you don't need it, why put the daemon in the critical path.

**Comment by sanimej** [comment]
@thockin 

> Also - does this embedded server forward to my own DNS servers?  

Yes. If you pass your servers embedded server will forward the queries to the configured servers if the name can't be resolved in the docker network domain.

> We learned the hard way that `nameserver` lines should be interchangeable (i.e. not have 1 that just serves X while another serves Y) or else suffer the vagaries of the myriad DNS resolvers (and total lack of a spec).

Yes, you can't have different nameservers in resolv.conf serving different subset of the domains. resolv.conf file will have only the embedded server listed.

> Linux has a hard limit of 3 `nameserver` lines, so this is still a significant incursion.

There is no incursion. Embedded DNS server will allow up to 3 nameservers. PR for this is in the works.

**Comment by mrjana** [comment]
@thockin Whatever you do to configure DNS options in docker will work as is.

**Comment by ibuildthecloud** [comment]
@mrjana I see the endpoint has a flag, `disableResolution`.  Can a network driver set this to true?

**Comment by thockin** [comment]
...but there is not and will not be a way to opt out of this functionality?

**Comment by mrjana** [comment]
@ibuildthecloud Disabling name discovery by docker on a per-network basis is a different question and one which has been brought up even during 1.9 time frame when we were doing it using /etc/hosts. The decision on that still remains the same. If you want name discovery use default bridge network. Else you chose to use the name discovery.

**Comment by mrjana** [comment]
@ibuildthecloud that flag is not exposed as a public api

**Comment by ibuildthecloud** [comment]
> If you want name discovery use default bridge network. Else you chose to use the name discovery.

Harsh, but okay, you make the rules.

**Comment by mavenugo** [comment]
@ibuildthecloud @thockin we all understand that service discovery is a fundamental feature and if I parse your questions correctly, it is not about disabling the feature, but it is about making it pluggable. As per any docker plugin philosophy, we are approaching it as batteries included by swappable. But we couldn't get to implement the "swappable" part in 1.10 as we prioritized replacing /etc/hosts with DNS as pointed by all of you in the 1.9 release. This effort has been underway in libnetwork for more than few weeks, but we didn't receive any contributions regarding the pluggability for SD. 

As seen in the past, providing a way to disable a functionality, just encourages more wrappers and that results in fragmentation & impacts the user experience badly. But, having a pluggable implementation gives the correct balance of functionality and user experience. We are seeing that in action in Volumes and network plugins already.

am highly in favor of a pluggable SD approach and any contributions to that is welcome.

**Comment by ibuildthecloud** [comment]
Closing, sounds like the answer is "You don't" 😄

**Comment by brendandburns** [comment]
@mavenugo in addition to "pluggable service discovery", I think making this "pluggable DNS server" (e.g. replace the built in Docker DNS server with our own implementation) would actually have much greater utility for the majority of end users.

**Comment by mavenugo** [comment]
@brendandburns yes. by `pluggable SD` I did infact mean `pluggable DNS server` as well.

**Comment by ibuildthecloud** [comment]
@mavenugo hate to beat a dead horse but it's kind of hard to define a pluggable Service discovery when their exists no services.  Right now you just have container naming through DNS.  And this is largely why people want to swap out a different DNS server is to plug into something like consul that presents a concept of a service.

**Comment by mavenugo** [comment]
@ibuildthecloud introducing the concept of `service` is a different (but related) discussion I think.
But regardless of that, I agree with the swap out part & that should be defined by the plugin layer.
BTW, we do have a rudimentary support with the `--dns` extension, where the embedded DNS server will delegate the queries to the external DNS server. This external server can do everything that you just mentioned.
Our contention here is not about pluggable SD. Its about providing a way to disable it all together.
I can certainly see it from @ibuildthecloud @brendandburns @thockin POV on how it makes it simpler to have your solution take over this functionality. But, we should be able to get there without sacrificing on the Docker UX through plugins. If we all work towards that, it will be a win-win for docker users and platforms that are built on top of docker.

**Comment by thockin** [comment]
I'm all for giving users a great experience, but it's a bit unfair to
consider this "sacrificing on the Docker UX" when you are changing the UX
underneath existing consumers.  Up until this notion of SD hit Docker, we
had a strictly superset UX. Now you've moved the goalposts and chosen a
design that was not compatible with most higher-order systems, and then
declared that our existing UX is creating fragmentation.  Please pardon my
mild annoyance.

Win-win for users would have been to look at the existing (and very
successful) designs (not just kubernetes, but all of us open and willing to
talk) and try to collaborate or compromise, rather than doing something
different. We all want consistency, that would have benefited everyone.

**Comment by mavenugo** [comment]
@thockin what am I missing here ?

* `docker network` is a new functionality that is introduced in Docker 1.9.
* All the legacy network modes/drivers (bridge, host, container) stays unaffected and the higher layer systems can continue to use them with no changes/impacts. We even disabled SD in default bridge based on your feedback. We infact took extra care not to impact all other functionalities such as `--link` with a primary objective as to not impact existing users/systems.

How is adding a new functionality, that doesn't impact existing users `"not compatible with most higher-order systems`" ?

**Comment by thockin** [comment]
On Tue, Jan 19, 2016 at 11:31 PM, Madhu Venugopal
<notifications@github.com> wrote:
>
> @thockin what am I missing here ?
>
> docker network is a new functionality that is introduced in Docker 1.9.

You're right.  We don't have to use it, and we're not yet, but we are
still trying to find ways to make it work for users (UX is one of our
goals, too)

> All the legacy network modes/drivers (bridge, host, container) stays unaffected and the higher layer systems can continue to use them with no changes/impacts. We even disabled SD in default bridge based on your feedback. We infact took extra care not to impact all other functionalities such as --link with a primary objective as to not impact existing users/systems.
>
> How is adding a new functionality, that doesn't impact existing users "not compatible with most higher-order systems" ?

There are a number of systems like Rancher and Kubernetes and Mesos
that built up from Docker and offered forms of service discovery and
DNS, long before Docker considered that to be part of its
responsibility.  What Docker ended up implementing was compatible with
none of the above, which just gives us yet another way of doing
things.  And now new and useful functionality is inexplicably coupled
to that design, despite it being not useful and/or wrong for the
existing users of these existing systems.

**Comment by mrjana** [comment]
> What Docker ended up implementing was compatible with
none of the above

This statement is not true. The embedded container name discovery solution is not incompatible with Service Discovery solutions of higher order systems. Even if you want to use the new network UI in k8s and discover services it will simply just work. The only conflict is in the container name space i.e in those user defined networks the container names are owned by docker and k8s(or any other higher order system) doesn't even operate at the container level. As long as the higher order systems doesn't step into container names and docker doesn't interfere with service discovery of higher order systems they both can co-exist. I simply don't see the technical issue that you are trying to allude here. And container name discovery provides a pretty useful way to quickly discover containers for docker users who are not using any of these higher order systems. So I don't agree with the assertion that "this is not a useful feature" either.

**Comment by thockin** [comment]
I don't want to belabor this much more - as Darren said, Docker makes
the rules and there's no point arguing them.

>> What Docker ended up implementing was compatible with
>> none of the above
>
> This statement is not true. The embedded container name discovery solution is not incompatible with Service Discovery
> solutions of higher order systems. Even if you want to use the new network UI in k8s and discover services it will simply just
> work. The only conflict is in the container name space i.e in those user defined networks the container names are owned by
> docker and k8s(or any other higher order system) doesn't even operate at the container level. As long as the higher order

That's not true.  Kubernetes DOES operate at the container level and
always has.  We explicitly DO NOT want containers to have names such
as are being assigned.  We have been pretty careful to follow some
hard won lessons in naming, and this comes in and wipes that away.
Don't mistake lack of action for lack of intention.

> systems doesn't step into container names and docker doesn't interfere with service discovery of higher order systems they
> both can co-exist. I simply don't see the technical issue that you are trying to allude here. And container name discovery
> provides a pretty useful way to quickly discover containers for docker users who are not using any of these higher order
> systems. So I don't agree with the assertion that "this is not a useful feature" either.

It's not useful _for_us_, sorry if that wasn't clear. Sure, it is
useful for users who don't have higher order systems yet.  And it's a
nice segue into them, using the same fundamental protocol.  The
problem is that it is schematically incompatible with existing systems
and we have neither the ability to disable it or to fundamentally
alter the schema (unless I am missing it).

**Comment by jainvipin** [comment]
@mavenugo, @mrjana 

> If you want name discovery use default bridge network. Else you chose to use the name discovery.

I am pretty sure this is true for the networks created via remote network drivers too... just wanted to confirm.

**Comment by mrjana** [comment]
@jainvipin yes it's true for all user defined networks regardless of whether they are backed by inbuilt drivers or remote drivers.

**Comment by mrjana** [comment]
> That's not true.  Kubernetes DOES operate at the container level and
always has.  We explicitly DO NOT want containers to have names such
as are being assigned.

Ofcourse k8s manages containers. I just meant that k8s doesn't try to discover services at container level. So far DNS discussions there should not be any conflict.

**Comment by thockin** [comment]
On Wed, Jan 20, 2016 at 12:25 AM, Jana Radhakrishnan
<notifications@github.com> wrote:
>
> That's not true. Kubernetes DOES operate at the container level and
> always has. We explicitly DO NOT want containers to have names such
> as are being assigned.
>
> Ofcourse k8s manages containers. I just meant that k8s doesn't try to discover services at container level. So far DNS discussions there should not be any conflict.

When Docker started stuffing names into /etc/hosts we noticed it
quickly and asked for a way to not do that.  There is a conflict in
philosophy - individual containers should not have DNS names except
for very carefully controlled circumstances.  Those names cause
confusion at best.  I'm not arguing that Docker should adopt our
philosophy, just that you can't suddenly adopt your own naming scheme
and then accuse us of hurting UX.

**Comment by preillyme** [comment]
+1 to @thockin we should set-up a meeting to discuss this approach and find a long term binding solution.

**Comment by ibuildthecloud** [comment]
Let me give you an example of why I wish to disable the embedded DNS server.  At Rancher we have always tried to completely embrace the Docker UX and use all of Docker's functionality.  We've only augmented where Docker doesn't provide a solution.  One gaping hole in Docker has always been service discovery which is a critical feature for production applications.  As such, Rancher augments Docker with SD using DNS.  We built our SD off of the concepts in Docker Compose assuming that is the Docker UX (unfortunately that assumption has proven to been wrong as Docker Compose concepts do not seem to be wholly agreed upon by the rest of the Docker projects).

Trying to stay in line with Docker our DNS does SD plus the container naming scheme that Docker has created.  The problem now is that container naming can conflict with SD.  If I have a service named foo and then I deploy a container named foo on the same network, I don't want to resolve foo to the container, but instead the service.  We ran into this problem in Docker 1.8 where all names were put in the `/etc/hosts` file.

Not being able to disable the embedded DNS server is a slight annoyance, not a show stopper.  Like most things in Docker, we just find a work around, and for this I'll do that same.  The bigger annoyance is that lack of progress on a real service model.  Users need SD, and at Rancher we specifically do not want to introduce any sort of UX.  We would much rather say, just use Swarm or k8s, but Swarm doesn't have a solution and we are forced to do crap like deploying our own to use with Swarm.

The community is basically just waiting for Docker to bless something,  There's nothing the community can contribute here because we have already voiced our opinions.  There's plenty of examples out there to choose from Consul, k8s, registrator, synapse, etc.  Container naming is a toy feature in my mind.  Having a name go to a single container is not too great in my mind because in production that doesn't provide any sense of resiliency.

**Comment by kciepluc** [comment]
One more thing... the RFC1123 states "DNS resolvers and recursive servers MUST support UDP, and SHOULD support TCP, for sending (non-zone-transfer) queries.". The SHOULD doesn't really mean that TCP support is optional, and the RFC5966 clearly states that there are may be (and in fact there are already) some DNS extensions which use longer than 512b packets and therefore use TCP transport. So to avoid potential problems there should be additional iptables configuration for TCP port 53. I've seen many hard to diagnose problems in environments where the TCP/53 port was filtered out because someone thought it is optional or used only for zone transfers...

**Comment by mavenugo** [comment]
@ibuildthecloud 

> Not being able to disable the embedded DNS server is a slight annoyance, not a show stopper.

thanks for the clarity. especially because the embedded DNS is just replacing the existing functionality that was delivered by /etc/hosts in 1.9.0 & also doesn't impact the default bridge driver.
Also, you are very well aware of the experimental feature UX in 1.7, where we tried to introduce the `service` concept, but based on community feedback, we added the network level abstraction and adding the container discovery on top of it.

> Having a name go to a single container is not too great in my mind because in production that doesn't provide any sense of resiliency.

Have you tried the `--net-alias` in `docker run` (or the `--alias` in `docker network connect`) ? This provides a way for multiple containers to share the same alias scoped by the network they belong to. That provides a resiliency for the `alias` name backed by multiple containers in that network. We don't have built-in load-balancer though. It is still a single container at any given time for a `name` / `alias`.

**Comment by tgraf** [comment]
I understand the desire to provide an embedded DNS by default and favour it over hosts file modification but the principle to require every individual user with non-standard needs to write their own plugins is worrying me. Please make it at least configurable as well.

**Comment by mavenugo** [comment]
@tgraf in this context even using the `--dns` option provides a pluggable way to use the external DNS as it was done in the previous releases. All the DNS queries originated from the container is delegated to the external DNS provided by the user if the lookup failed on the embedded DNS. 

The embedded DNS simply provides a default way to provide container reachability by its name (and its alias). If the container is unnamed, it will simply not participate in the discovery, but the requests are still passed on to the external DNS managed and owned by other systems. There is no change to this behavior from 1.9.

**Comment by justincormack** [comment]
@ibuildthecloud DNS has namespaces, surely you should be trying to put services into a different namespace from hosts?

**Comment by ibuildthecloud** [comment]
@mavenugo Can I add an alias to an IP?

**Comment by mavenugo** [comment]
@ibuildthecloud `alias` is for a container & with 1.10, you can use `--ip` to assign an IP to a container so yes, you can add an alias to an IP :)

**Comment by ibuildthecloud** [comment]
What is this `--ip` you speak of :smile:

**Comment by mavenugo** [comment]
PTAL https://github.com/docker/docker/pull/19001 & https://github.com/docker/docker/pull/19242

**Comment by brendandburns** [comment]
@mavenugo @mrjana I understand (though I disagree) your desire to protect your Docker CLI UX.

However, I think that making this a per-container flag (eg. `docker run --dns=false ...`) doesn't affect the CLI UX, it simply adds flexibility that end users will find useful.

**Comment by jainvipin** [comment]
+1 for flexibility of course, will be happy to contribute to the code for this.

@mavenugo - consider my perspective of trying to develop a docker compatible remote plugin:
- So far, I was able provide dns without telling users to use `--dns` with my plugin, with 1.10, I can't.
- Given that, the new behavior has Ux implications (to ask them to use `--dns`), the user of my plugin thinks that I became incompatible/broken, which is true - but I am not sure what could I have done something about it.

**Comment by mavenugo** [comment]
@jainvipin thats strange. can you explain how your remote network plugin become incompatible ?
This is purely handled at libnetwork core level (replacing /etc/hosts with DNS).

**Comment by jainvipin** [comment]
@mavenugo: 
I will take back that `--dns` option is not specified by the user of my plugin today, because it is. It was auto-generated before calling `docker run`, so I missed the fact that docker is indeed called with `--dns` option. Sorry to confuse you.

One more follow-up:
When `--dns` is specified, I assume it would work like it is today, do a lookup in the local dns server and then fall back to what was specified by `--dns`. If yes, I am good.

I am doing some more testing/playing around with the latest...

**Comment by mavenugo** [comment]
@jainvipin thanks for confirming. 

>>  When --dns is specified, I assume it would work like it is today, do a lookup in the local dns server and then fall back to what was specified by --dns.

Yes.

**Comment by bboreham** [comment]
As far as I understand it, the call to the outer DNS serve happens _through_ the Docker DNS, not as a fall-back. Thus it is subject to any limitations in that implementation.

**Comment by thockin** [comment]
Including no TCP support, as someone pointed out (maybe wrong, I have not
tried it myself)

**Comment by sleaze** [comment]
This DNS business still has a bad smell to it if you ask me.  Why so much back and forth over the addition of a single flag?

**Comment by mavenugo** [comment]
TCP support was added as part of https://github.com/docker/docker/pull/19680

**Comment by realulim** [comment]
I am sorry to report that my docker setup was broken by this change.

I have my own bridge network and start two containers in it. In version 1.9 they could see each other (via /etc/hosts), now they can't (via the embedded DNS server). When logging in to one of my containers with --net my-network I find these entries in my /etc/resolv.conf:

search some.local.domain.com
nameserver 127.0.0.11
options ndots:0

I can ping 127.0.0.11, but it doesn't answer to DNS queries:

host www.google.com
;; connection timed out; no servers could be reached

What can I do to fix this?

**Comment by thaJeztah** [comment]
@realulim can you open a separate issue?

**Comment by realulim** [comment]
Sorry, I'm new to GitHub, will find out how to do that.

**Comment by realulim** [comment]
Ok, hope I did it correctly: https://github.com/docker/docker/issues/20029

**Comment by jainvipin** [comment]
@mavenugo - sorry I have to come back to this closed issue; your response is highly appreciated.

> > When --dns is specified, I assume it would work like it is today, do a lookup in the local dns server and then fall back to what was specified by --dns.

> Yes.

Here is what we see:
For Contiv plugin, we provided DNS service per tenant. In order to do so, tenant context in the dns server is derived based on the network where the request is obtained from. However, with 1.10 the network (and source-ip) of the request is replaced with that of host's when embedded-dns-server relays the request. This takes away the hint we used to get in 1.9, creating a compatibility issue for users moving from 1.9 to 1.10 with Contiv.

Can I use something else to provide multi-tenancy here? Please help.

**Comment by mavenugo** [comment]
@jainvipin I think I get your use-case at a high-level. But would like to discuss more to understand how you derive the tenant context, etc... we can update the summary here once we get to talk (/white-board?) the details.

**Comment by blufor** [comment]
Hi there, just a quick question - we've been previously using /etc/hosts as service discovery for our clustered services (multiple containers with same app). our automated HAproxy controller took care of reading the hosts file on change and update HAproxy's config.

Obviously, this functionality is broken now. I'm not against your DNS per-se, quite like it actually, but at this point, I don't see any way to **get list of all containers & their IPs from within a container**. Maybe I'm wrong, and there might be a way to do it (AXFR maybe?). Any suggestions are welcome

**Comment by sanimej** [comment]
@blufor We are looking at the possible options to provide the list of containers/IPs.

For now one option you can consider is to monitor the docker events for container create and do an inspect to get the IPs.

**Comment by thaJeztah** [comment]
We now also have `network connect` and `network disconnect` events, which may be interesting for that

**Comment by blufor** [comment]
because i already rely heavily on ETCD with my projects, i've made a tool to get the data directly from the db https://github.com/prozeta/port-authority/blob/master/gem/lib/port-authority/services.rb

**Comment by kevinxucs** [comment]
See random dns resolve errors with macvlan, an option to disable embedded dns would be greatly appreciated.

**Comment by sanimej** [comment]
@kevinxucs Are the errors for docker service names or external names ? Can you also run the daemon in the debug mode and share the logs when the resolution failure happens ?

If you are using 1.11 images update to the latest RC5 image; which has some bug fixes related to DNS resolution.

**Comment by thaJeztah** [comment]
@kevinxucs also, please open a separate issue with the requested information

**Comment by bboreham** [comment]
I started to ponder the idea of a "DNS plugin" for Docker.  It raised some fundamental questions that I would like to get some reaction to, in advance of making a full proposal.

I work on Weave; my primary concern would be to answer look-ups for containers attached to a Weave network.  But containers may be attached to multiple networks, and DNS doesn't support the concept of multiple servers that know about different sub-spaces, so our plugin has to be able to answer about all containers attached to all networks.

Assuming the previous point holds, where would our plugin get this information from?  Practically, it needs access to the same data that Docker DNS is currently using.  It could be fed this via a subscription mechanism, with some way to re-sync on restart.

On the query side, what are the requirements that a Docker DNS plugin must meet?  For instance, does it have to preserve the behaviour that only container names are used for resolution, not hostnames?  Does it have to answer reverse lookups with container_name.network_name?  Those are two key things I would want to change, so if they are fixed-points in the requirements I don't need to start down this road.

**Comment by sanimej** [comment]
@bboreham We have considered the possibility of having DNS plugins. One of the challenges is that the DNS plugin being a container level entity should be able to resolve the service names for any network the container is connected to. But the service abstraction (service naming, search domain etc.) provided by different vendors (k8s, weave etc.) may not be the same.

A better alternative is to define a schema for service naming that works for majority of the vendors (things like how container name vs host name should be used, what should be the domain name etc.). This might be cleaner approach to address the service naming/discovery in a consistent way across vendors and the Docker inbuilt drivers.

**Comment by bboreham** [comment]
Sorry, I picked up on

> make it pluggable in this release. Contributions welcome.

> having a pluggable implementation gives the correct balance of functionality and user experience

> it is about making it pluggable

My bad.

**Comment by sanimej** [comment]
There might be use cases that are better addressed by a pluggable DNS. I am not disagreeing on that. But without a consistent schema it makes it difficult to implement a pluggable DNS that can provide the same functionality for all networks the container is connected to.

**Comment by wrouesnel** [comment]
So the `--dns` option doesn't seem to do anything the documentation implies - using it it looks like docker is just eating up the option and using the internal DNS server (in 1.12.1) to try and resolve the name...which fails, because the DNS server is only reachable via the network plugin I'm using, and not via my hosts network.

This seems like the culmination of ongoing insanity: there's no parameter to tell docker "don't bind mount resolv.conf", and now there's no option to say "just put this content in resolv.conf". Instead we've got docker trying to be a DNS server and failing at it.

**Comment by antoineco** [comment]
This is still creating a lot of issues as of Docker 1.13, especially with Docker Compose with generates invalid host names (ref docker/compose#229).

DNS resolution from some container started with `--dns=8.8.8.8`:
```sh
:/# cat /etc/resolv.conf
nameserver 127.0.0.11    # <-- wat
options ndots:0

:/# nslookup 172.18.0.3
Name:      172.18.0.3
Address 1: 172.18.0.3 modcluster_lb_1.modcluster_default    # <-- wat
```
And the consequence on a client. Here an Apache httpd server:
```
[core:debug] [pid 280:tid 139910987741872] vhost.c(796): [client 172.18.0.4:57214] AH02415: [strict] Invalid host name 'modcluster_lb_1.modcluster_default', problem near: _lb_
[core:debug] [pid 280:tid 139910987741872] vhost.c(891): [client 172.18.0.4:57214] AH00550: Client sent malformed Host header: modcluster_lb_1.modcluster_default:6666
[core:debug] [pid 280:tid 139910987741872] protocol.c(1385): [client 172.18.0.4:57214] AH00569: client sent HTTP/1.1 request without hostname (see RFC2616 section 14.23): /
```

**Comment by thaJeztah** [comment]
The embedded nameserver acts as a forwarder to the dns you specified with the `--dns` flag, so you'll always see 127.0.0.11 as DNS. Docker compose using underscores is a separate issue (although you can override the hostname for a container)

**Comment by antoineco** [comment]
@thaJeztah thanks for your answer.
I perfectly understand how things work underneath and why they were done that way, however **if** I am explicit with the DNS server I want to use (or don't) I don't see why Docker would forcibly respond to my DNS queries with a hostname I don't expect.

The `hostname` of a container can be set, yes, but in the context of Compose the Docker DNS ignores it completely, which doesn't solve the original problem:
```sh
❯ docker exec modcluster_lb_1 hostname
lb
❯ docker exec modcluster_lb_1 hostname -i
172.18.0.2
```
```sh
❯ docker exec modcluster_backend_1 nslookup 172.18.0.2
Name:      172.18.0.2
Address 1: 172.18.0.2 modcluster_lb_1.modcluster_default  # <- nope. thanks
```

Compose may be the source of the underscores, but it wouldn't be such a big deal if I could bypass the DNS.

**Comment by lierdakil** [comment]
FWIW, I'm running into issues with embedded DNS on a host that uses nftables instead of iptables (iptables are disabled because that conflicts with nftables' dnat). It just doesn't work, plain and simple, for obvious reasons. While being able to disable eDNS won't solve service discovery problem, I could work around that.

**Comment by valentin2105** [comment]
Hi all,

I try to use Docker with Docker-compose in IPv6 only (so in user definited network) and I couldn't make it work due of the embedded DNS. If I pass the --dns flag, it doesn't work because my host don't have any IPv4 connectivity.

Any plan to allow disable embedded DNS in the future ? (for this kind of use case) ?

**Comment by christopherobin** [comment]
To add to the discussion, I wish I could opt-out some networks from the resolution. I am currently running a swarm internally where developers can run their copy of a web app for testing purposes.

Load balancing is done via [Traefik](https://traefik.io/) running as a docker service, containers join the `traefik` network and use labels to declare how they want to be exposed.

The issue with the internal DNS is that 2 copies of app "foobar" might be started via docker stack, they join 2 networks: `<stack_name>_default` and `traefik`. Then the app tries to connect to the `database` host and... actually connect to each other's database through the `traefik` network randomly due to them being both on the `traefik` network.

Being able to say` "this network doesn't allow for resolution"` would solve my issue immediately. Right now my only solutions is either to use network aliases with environment variables (like inserting deploy IDs in the aliases), or to move Traefik out and instead write some sort of external registrator that watches the swarm and create entries in consul.

**Comment by matthiasdg** [comment]
@christopherobin I am experiencing the same issue in docker compose. Only seeing it when the project's default network is alphabetically following the traefik network, though, corresponding to https://docs.docker.com/engine/userguide/networking/

> When a container is connected to multiple networks, its external connectivity is provided via the first non-internal network, in lexical order

Was also thinking about using network aliases as a fix

**Comment by PaulFurtado** [comment]
We are transitioning to use a user-defined bridge so we can use our own IPAM driver since the default docker bridge does not allow you to use a custom IPAM driver. Each of our servers runs 400+ containers, and redundant caching DNS servers on each node. Some of our services are quite heavy on DNS - individual containers can push 60k+ DNS QPS at times, making even bind and dnsmasq CPU-bound; we really can't rely on the built-in docker DNS server. It's disappointing to see docker remain adamant against adding a flag to disable this for user-defined networks when it's on such a critical path, especially since we don't use docker's service discovery features in our infrastructure. We'll have to work around this by adding another patch to our docker build. What is so special about user-defined networks that makes them require this DNS server to be enabled when the default bridge does not? Looking at the code it seems like it'd be very trivial to add such a flag.

**Comment by Gunni** [comment]
I want to use my own DNS servers, no inside-docker name doohickey wanted. Just old simple standardized DNS.

**Comment by thaJeztah** [comment]
@icy where is that resolver running? If you pass `--dns <ip-of-your-resolver>`, the embedded DNS will first try to resolve containers on the attached network, and resolve other domains using the resolver you configured (which can be your custom DNS resolver).

**Comment by icy** [comment]
> @icy where is that resolver running? If you pass `--dns <ip-of-your-resolver>`, the embedded DNS will first try to resolve containers on the attached network, and resolve other domains using the resolver you configured (which can be your custom DNS resolver).

Hi @thaJeztah , thanks for your answer. 

I am using `--dns 192.168.0.10` to tell my container to use the host dns resolver. The problem is that sometimes I got timeout error, and sometimes it just got stuck, and the container's application failed to start:

```
2024/01/08 13:03:02 logtail: dial "log.tailscale.io:443" failed: dial tcp: lookup log.tailscale.io on 192.168.0.10:53: read udp 172.17.0.2:60953->192.168.0.10:53: i/o timeout (in 7.88s), trying bootstrap...
2024/01/08 13:03:02 logtail: dial "log.tailscale.io:443" failed: dial tcp: lookup log.tailscale.io on 192.168.0.10:53: read udp 172.17.0.2:60953->192.168.0.10:53: i/o timeout (in 20.051s), trying bootstrap...
2024/01/08 13:03:06 socks5: client connection failed: lookup special-hostname1-internal.mycompany.co: i/o timeout
2
```
Sometimes I event got timeout with `1.1.1.1` if that's used:

```
Jan 05 11:43:05 hostname.ecxample.net dockerd[1283]: time="2024-01-05T11:43:05.554264239+01:00" level=error msg="[resolver] failed to query DNS server: 1.1.1.1:53, query: ;hostname.example.net.\tIN\t A" error="read udp 172.18.0.2:51905->1.1.1.1:53: i/o timeout"
```

If I restart `docker` daemon it'd be back to normal, and I hope by using a direct connection will help to resolve the issue. 

Thanks a lot.

**Comment by icy** [comment]
> @icy where is that resolver running? If you pass `--dns <ip-of-your-resolver>`, the embedded DNS will first try to resolve containers on the attached network, and resolve other domains using the resolver you configured (which can be your custom DNS resolver).

Hi @thaJeztah and everyone again,

My work-around with some 2nd dns resolver (https://github.com/moby/moby/issues/19474#issuecomment-1880980151) has the same timeout issue again today.  I decide to look more at the issue with `tcpdump`, and have found that though internal docker dns resolver can fetch some dns information from the upstream, it reports some checksum is bad:

```
 172.17.0.2.59943 > 192.168.0.10.53: [bad udp cksum 0x6d30 -> 0x8347!] 29676+ [1au] A? foobar.example.net. ar: . OPT UDPsize=1232 (81)
14:07:24.271463 IP (tos 0x0, ttl 64, id 7466, offset 0, flags [DF], proto UDP (17), length 109)
```

The problem only happens with docker container(s). I think the upstream resolver has done something bad, and/or the internal docker daemon expects something that I haven't known. For this reason, I force all dns queries over `tcp`  protocol and it's working very well now:

Option 1: Via `docker run --dns 192.168.0.10 --dns-option "ndots:1" --dns-option "use-vc" ...`
Option 2: Via `/etc/docker/daemon.json`, as below

```
{
  "dns": ["192.168.0.10"],
  "dns-opts": ["ndots:1", "use-vc"],
  "log-driver": "json-file"
}
```

Hope this helps for anyone who faces the same issue.

**Comment by Radarum** [comment]
We use kata containers with custom network driver. Since those are VM based, localhost DNS address does not work inside the container. Can we please have an option to disable internal resolver?

**Comment by akerouanton** [comment]
@Radarum That's not an option that should be user-facing. Instead, custom network drivers should specify whether they support the embedded DNS server (and those who don't specify anything should have the DNS server started automatically). Could you open a separate ticket for that please?

**Comment by Radarum** [comment]
@akerouanton To be honest, there is nothing wrong with custom network driver, as it works fine with runc. It is kata runtime that does not support internal resolver.
