### ISSUE TITLE
[1.10]: Volume.List Required?

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#19475]
I know `Volume.List` is new in 1.10, but is it actually required?  I just assumed it would be an optional method.  Seems my existing volume plugins are not working now.

**Comment by thaJeztah** [comment]
I *think* it's a requirement now for plugins, but perhaps @cpuguy83 is better to explain

ping @cpuguy83 can you have a look at this?

**Comment by cpuguy83** [comment]
IIRC, List is only called from `docker volume ls`.
So, if you want volumes to be visible, it needs to support `List`, but this should not be critical to the volume actually working.

**Comment by ibuildthecloud** [comment]
@cpuguy83 I believe it's called during the delete flow.  Let me validate as I think that is what is breaking in my tests right now.  I think the method should be optional, I really don't have time to implement this functionality on all my volume plugins in the next week or so.  For even `docker volume ls` it should be optional.  `go-plugins-helpers` doesn't have support for this method so all of @calavera's plugins will be broken too I assume.

**Comment by cpuguy83** [comment]
#19528 adds backwards compat

**Comment by thaJeztah** [comment]
Thanks @cpuguy83
