### ISSUE TITLE
docker commands such as docker tag and docker rmi hangs when its executed from docker binary compiled from docker source code.

### ISSUE THREAD

**Issue by mathewkoshy493** [docker/docker#19489]
I have taken a fresh clone of docker daemon and registry from their respective github repositories and compiled both of them and is running my local daemon and registry and also I have created a symbolic link from the binary compiled from source code to the default docker binary so that i can use the compiled binary as the default one. 
          But once this is done docker commands such as docker tag and docker rmi hangs.

Steps to recreate the issue:-   

1)Compile docker daemon and registry from the latest source code
2)Create a symbolic link between the compiled docker binary and default binary so that  the binary compiled from the source code becomes the default binary.This is done using the following commands
           1) rm -rf  /usr/bin/docker (removes default binary)
           2)ln -s /home/mathew/matrepo/docker-fork/bundles/1.10.0-dev/binary/docker-1.10.0-dev                                                          
              /binary/docker-1.10.0-dev  /usr/bin/docker (makes the binary compiled from source code 
               found at location /home /..... docker-1.10.0-dev the default binary)

     Once thse steps are finished docker is hanging while executing docker tag and docker rmi are hanging and returns the terminal back only on pressing ctrl+c,It is executing these commands but its not returning the terminal back until I press ctrl+c.
    
    Note:- This problem started after updating my local copy of docker and registry code to include todays commits

output of docker version is

Client:
 Version:      1.10.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   7657e23
 Built:        Wed Jan 20 08:54:55 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   7657e23
 Built:        Wed Jan 20 08:54:55 2016
 OS/Arch:      linux/amd64

Output of docker info is

Containers: 17
 Running: 0
 Paused: 0
 Stopped: 17
Images: 113
Server Version: 1.10.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 186
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.13.0-73-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.683 GiB
Name: mathew-ThinkPad-T420
ID: GO5G:KHYY:2JJS:4ST6:7QTV:JPQB:HTVG:OTOZ:EFKP:V3KZ:KHVR:6ICA
WARNING: No swap limit support

Please let me know if you need any logs or any additional information

**Comment by HackToday** [comment]
not sure how do you start docker.  make docker start with -D, I think that daemon should have lots of info to help you what happened

**Comment by mathewkoshy493** [comment]
I have started the daemon using   daemon    ,-D  is not supported in the new docker version

**Comment by HackToday** [comment]
hi @mathewkoshy493  I am not sure why you said _D is not supported,

I used the latest docker master branch, it support that 

docker daemon -D

**Comment by thaJeztah** [comment]
I'm closing this, because this looks to be an issue with your build, and not a docker bug. Feel free to join the #docker-dev IRC channel if you're running into issues with building docker
