### ISSUE TITLE
overlay subnet has conflicts in the host while running in host mode

### ISSUE THREAD

**Issue by rquinnlv** [docker/docker#19499]
I'm testing an overlay network in docker 1.10.0-rc1 that was not working in 1.9.1 (I'm running kernel 13.3)

I run the following:

``` 
docker network create --driver overlay es-bridge
```

I confirm the creation of the network:

```
docker network ls
NETWORK ID          NAME                DRIVER
df89455cbc24        bridge              bridge
94df4ba9ba03        none                null
1c4b0953f828        host                host
4f0069ac54d2        es-bridge           overlay
```

Then add a busybox container to it:

```
docker run -itd --net=es-bridge busybox
3ab7ba1969c4084c9d0f0ed23525b05573405a21188fac67f890d6bdcc506807
docker: Error response from daemon: subnet sandbox join failed for "10.0.0.0/24": overlay subnet 10.0.0.0/24 has conflicts in the host while running in host mode.
```

There are no other containers running on this node, and I've run the same container on several nodes and get the same result

```
docker version
Client:
 Version:      1.10.0-rc1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   677c593
 Built:        Fri Jan 15 18:17:17 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0-rc1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   677c593
 Built:        Fri Jan 15 18:17:17 2016
 OS/Arch:      linux/amd64
```

```
docker info
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 88
Server Version: 1.10.0-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 104
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: overlay bridge null host
Kernel Version: 3.13.0-32-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.41 GiB
Name: c2b1s2.tera4.terascope.io
ID: EP32:TWMN:LIX6:5B2E:X3AR:FJAH:OVSG:PMVF:XQVQ:FUQ2:6NKF:HNH6
WARNING: No swap limit support
Cluster store: zk://zk.host:2181
Cluster advertise: IP:2376
```

**Comment by mavenugo** [comment]
@rquinnlv its expected in kernels < 3.16, If there is an existing interface in the host that uses the same subnet allocated for the network. 

Can you please use of the `--subnet` option while creating the overlay network and make sure the subnet that you are using doesnt overlay with any existing subnets in that host or other hosts (kernels < 3.16) that are part of the overlay network ?

**Comment by mavenugo** [comment]
@mrjana @thaJeztah we may have to enhance the docs to highlight this point clearly.

**Comment by thaJeztah** [comment]
@mavenugo thanks, I'll add this to the milestone so that we should try and get our docs right before the release

**Comment by rquinnlv** [comment]
tried again using a random `--subnet` parameter and it's working fine, thanks for the response.

**Comment by mavenugo** [comment]
thanks @rquinnlv. closing the issue.
