### ISSUE TITLE
Docker context build  should use symbolic links instead of copying files

### ISSUE THREAD

**Issue by Stan-Kladko** [docker/docker#19492]
Currently during a container build the source files are copied to the Docker daemon.

This is inefficient and takes lots of time.

It is absolutely unclear why this architecture has been chosen. The correct way would be to create symbolic links to corresponding files and avoid copying.

**Comment by cpuguy83** [comment]
I'm not sure how symbolic links would help anything.

The reason files are copied to the daemon is because clients are considered remote, and the builder is currently driven by the daemon, not the client.
This is something we hope to have driven by the client in 1.11.
