### ISSUE TITLE
[1.10] can't stop a stopped container

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#19497]
I know the issue title sounds stupid but in 1.9 the stop operation was idempotent.  For example in 1.9 the following prints `OK`

```
docker stop foo && docker stop foo && echo OK
```

In 1.10 you get
```
404 Client Error: Not Found ("No such container: a915")
```

This is change in the API, not just the CLI.  I tested this against the API.

**Comment by thaJeztah** [comment]
I got this;

```bash
$ docker run -d --name foo nginx
9f1071d2eaa94e6699bd4d4634bd751a09b1dc4afe23c72c7bef32d496af4428
$ docker stop foo && docker stop foo && echo OK
foo
foo
OK
```

**Comment by thaJeztah** [comment]
What distro are you running on? There *is* a known issue with AppArmor that causes docker to not run correctly on Ubuntu 14.04 and below fwiw

**Comment by ibuildthecloud** [comment]
@thaJeztah Odd.... let me try this again or give a better test case.  I'm running RancherOS :smile:

**Comment by ibuildthecloud** [comment]
Okay, closing.  No clue what I did to create this issue to begin with.  I swear I tested it a bunch of ways (even through the API).

**Comment by thaJeztah** [comment]
@ibuildthecloud ahhhh RancherOS :trollface: 

Jut kidding, no problem, feel free to reopen if you are able to reproduce :heart:
