### ISSUE TITLE
Docker does not allow to mount root volume, even if not bound to host

### ISSUE THREAD

**Issue by Stan-Kladko** [docker/docker#19493]
Aufs is buggy, so in order to avoid using it we want to mount the entire root filesystem of a countainer,
using -v  / 

This is not allowed - docker returns "Can not mount root"

Not clear why this choice was made and why is it not allowed to do non-bound mounts of volumes.

**Comment by cpuguy83** [comment]
@Stan-Kladko What issue are you having with AUFS?

Also, you can mount the host's rootfs, just not to the container's root.
`docker run -v /:/host` will work.
