### ISSUE TITLE
INIT instruction to be executed prior to ENTRYPOINT at container run time

### ISSUE THREAD

**Issue by CameronGo** [docker/docker#19508]
This is a feature request to provide a means for a set of actions to occur at container launch time, which is not part of or directly related to the container's primary process.  The general purpose of this would be to perform launch time setup or configuration in place of using launcher scripts as the ENTRYPOINT or CMD.  One use case for this would be to pull down config secrets that should not be stored in source code (such as resource credentials).  Another use case might be to pull a configuration settings package that is dependent on the environment in which the container is launched.  (Example of the latter use case : A script to pull one config package from AWS S3 if launched in the DEV environment vs. another config package from a different AWS S3 bucket if launched from the PROD environment.) 

I might envision this implemented in the Dockerfile as an INIT instruction with similar characteristics to the RUN instruction.  Those commands that appear as arguments to the INIT instruction would not be executed during the image build, but would be executed at container launch before the ENTRYPOINT or CMD is executed.  I believe the default behavior of the engine should be to fail the container launch of the INIT arguments exit with an error code, but that this might be modified by an optional parameter at the docker run command line similar to "docker run --failoniniterr hello-world".  

It may also be useful to provide a parameter to instruct the container to run the INIT commands after the ENTRYPOINT or CMD is executed.  This might be appropriate to perform tasks like register the container process with an external management console.

docker version: 
Client: 
Version: 1.9.0 
API version: 1.21 
Go version: go1.4.2 
Git commit: 76d6bc9 
Built: Tue Nov 3 17:43:42 UTC 2015 
OS/Arch: linux/amd64 

Server: 
Version: 1.9.0 
API version: 1.21 
Go version: go1.4.2 
Git commit: 76d6bc9 
Built: Tue Nov 3 17:43:42 UTC 2015 
OS/Arch: linux/amd64 

docker info: 
Containers: 8 
Images: 2 
Server Version: 1.9.0 
Storage Driver: aufs 
Root Dir: /var/lib/docker/aufs 
Backing Filesystem: extfs 
Dirs: 18 
Dirperm1 Supported: false 
Execution Driver: native-0.2 
Logging Driver: json-file 
Kernel Version: 3.13.0-43-generic 
Operating System: Ubuntu 14.04.2 LTS 
CPUs: 1 
Total Memory: 992.5 MiB 
Name: chlorine 
ID: DG52:Y3T4:2BGU:HRHN:TVQK:IFII:X26U:V733:VHX3:YU7Z:ZSRC:4UQI 

uname -a: 
Linux chlorine 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux 

Environment: 
AWS EC2 Container Services running on custom Ubuntu AMI with ecs-agent container.

**Comment by phemmer** [comment]
Can you clarify why you don't want to use ENTRYPOINT for this? This sounds like exactly what ENTRYPOINT is for.

**Comment by CameronGo** [comment]
The way I'm reading the Dockerfile reference, I think ENTRYPOINT is used for the executable that "is" the container, so in the example of apache, you're ENTRYPOINT would be /usr/sbin/apache2ctl.  I know you can use a startup script as the ENTRYPOINT to pull config info and then run exec /usr/sbin/apache2ctl at the end of the script so the final executable receives Unix signals, but to me this feels like a workaround.  One byproduct of this approach is if you want to pass additional parameters to the final executable via CMD at run time, you won't be able to do this without first trapping those via your script and then passing them to the final executable in the end.  That doesn't feel very clean to me.

A crude hypothetical example of the issue using ENTRYPOINT: I want to run an apache site, but want to pull config secrets for SSL private keys and DB credentials, so I write a startup script that performs all the run-time config first, then at the end runs exec /usr/sbin/apache2ctl –D FOREGROUND to run and pass control to apache.  If I was testing, or had any other reason to pass additional parameters to apache at runtime I will have to write something to catch parameters in the startup script, put those into variables and then include conditional logic at the end of the startup script to exec /usr/sbin/apache2ctl with any potential parameters that might be passed to it.  Whereas if /usr/sbin/apache2ctl can remain my ENTRYPOINT I would be able to pass parameters intended for the final executable at run time as CMD.

**Comment by cpuguy83** [comment]
@CameronGo `exec my_executable "$@"` will generally suffice.

I don't feel like this is a work-around. This is how init systems work.

**Comment by CameronGo** [comment]
I hear you, this just feels like a cleaner alternative.  I certainly understand you can get the same result via a startup script.  As a matter of preference perhaps, I would ideally like to see those startup activities described inside the Dockerfile itself rather than a script that is then placed into the image via COPY.

**Comment by unclejack** [comment]
This use case isn't extremely common. Adding this `INIT` instruction would still not provide that much flexibility. What happens if I also want to make `INIT` run something based on the arguments or the command I'm passing to `docker run`? This can be done with `ENTRYPOINT` today and no `INIT` instruction is needed.

`INIT` would also make some think it has something to do with `/sbin/init` and setting the init process for the container.

As @cpuguy83 has also stated, this isn't needed.

I'm going to close this issue now. Please feel free to comment.

**Comment by CameronGo** [comment]
The issue of passing parameters to INIT was something that occurred to me as well and I agree, that could turn into a rabbit hole.  Thanks both of your for taking a look and for your comments.

**Comment by muzammil360** [comment]
I have a usecase which is very similar to what @CameronGo described above. I need to pull some config dynamically whenever container starts and use these running other programs. 

However from your above discussion it seems like `ENTRYPOINT` can achieve that. Now I have a question: can we use multiple `entrypoints` or one `entrypoint` with one `cmd` to achieve initialization? 

If not then how can I pull my configs without writing a (not so clean) script?
