### ISSUE TITLE
Proposal: expose the cgroupfs driver used by docker as part of the daemon's info

### ISSUE THREAD

**Issue by dqminh** [docker/docker#19539]
Currently we have 2 mechanism for cgroupfs, either fs or systemd. FS is used by default even when systemd is available, and there is also a flag to explicitly choose which cgroup driver the daemon will use. But that decision is not exposed anywhere for consumer, which leads to some hacks like https://github.com/google/cadvisor/blob/master/container/docker/factory.go#L64-L84 to detect systemd usage or disable when we use cgroupfs.

Instead, the daemon should expose the cgroupfs driver (or all of the current exec driver options) as part of its info so consumer can skip the detection of cgroupfs

@vishh @LK4D4 @crosbymichael @mrunalp @hqhq

**Comment by hqhq** [comment]
I'm +1 on this. Maybe add an entry `Cgroup Driver` in `docker info`?

**Comment by WeiZhang555** [comment]
This is relevant to exec driver a lot, it's OK for native exec driver, but it will be unmeaning for exec driver which is not using Cgroup at all. We can never say we won't have a second exec driver in the future, right?

**Comment by vishh** [comment]
+1.

**Comment by HackToday** [comment]
It seems proper to expose that info through `docker info`.

**Comment by thaJeztah** [comment]
sgtm, is someone working on this, or interested to work on this?

**Comment by hqhq** [comment]
#dibs, I'll do this :)
