### ISSUE TITLE
Feature: Allow setting syslog log message levels for stderr and stdout messages

### ISSUE THREAD

**Issue by zerthimon** [docker/docker#19542]
I't be really usefull if one could configure their syslog log driver with different specific levels (error, info) for stdout and stderr messages, so they can later be routed by syslog to different destinations based on these levels.

For example:
--log-opt syslog-level-stdout=info
--log-opt syslog-level-stderr=error

**Comment by HackToday** [comment]
sounds reasonable request, So right now, the docker logging not meet your log destination request ?

**Comment by zerthimon** [comment]
I have researched this more and I can confurm that docker's syslog driver assigns err level to stderr messages and info level to stdout messages.

Closing as irrelevant.
