### ISSUE TITLE
"docker" string appeared when I use mflag package.

### ISSUE THREAD

**Issue by koojunho** [docker/docker#19546]
```
fmt.Fprintf(fs.Out(), "docker: %s.\n", str)
```
-- [mflag/flag.go](https://github.com/docker/docker/blob/757d686700b02fa79f7c59edee656b7c35f956f3/pkg/mflag/flag.go#L1166)

I am using the [mflag](https://github.com/docker/docker/tree/master/pkg/mflag) package in my personal project. It's pretty nice, but when I make an argument error, "docker" string will comes out because it is hard coded. Do you have a plan to change this?

Thanks.

**Comment by runcom** [comment]
we can extend `ReportError` to have a `prefix string` argument or print `os.Args[0]: ` as the prefix

**Comment by koojunho** [comment]
Amazing.
