### ISSUE TITLE
Error message unhelpful "Cannot connect to the Docker daemon. Is the docker daemon running on this host?"

### ISSUE THREAD

**Issue by samaimia** [docker/docker#19544]
Would be nice if this would spit out the command(s) I need to run in order to start the docker daemon.  I've tried googling for the command that starts the docker daemon but it's not easy to find, I had a look at https://docs.docker.com/machine/get-started/ but if I do CMD + F and search for "daemon" it does not include any sentence equivalent to "to start the docker daemon run this command".

Anyway, eventually I found the following commands seemed to work, I think it would make sense to include these commands in the docker documentation.

```
brew install boot2docker
boot2docker init
boot2docker up
eval "$(boot2docker shellinit)"
```

**Comment by cpuguy83** [comment]
Really, this is not correct... and I'd recommend not using the `boot2docker` CLI since this is no longer supported. `docker-machine` is the appropriate tool here.
The article you linked to has the exact commands to run to get docker up and running.

The thing to keep in mind is that Docker is 2 parts, client and server.
On Linux this is shipped as a single binary, but it's still two things.
On non-Linux platforms the binary is client-only, since docker engine only runs on Linux... as such these do not include the `daemon` subcommand when calling `--help`

Starting docker is going to be different on every platform, or even depend on the Linux distro.

Maybe we can put a link to the getting started page in the error message? Not sure if that's quite appropriate here or not.
ping @thaJeztah

**Comment by samaimia** [comment]
The issue I have is that no part of that documentation explicitly states what command actually starts the docker daemon, which is necessary in order to respond to that error message.

What SHOULD I be doing then? This:??

```
docker-machine create --driver virtualbox default && eval "$(docker-machine env default)"
```

Now that I've used `boot2docker` what should I do to "undo" that?

**Comment by HackToday** [comment]
Didn't we not have documentation for non-linux platform, how to start daemon ?

**Comment by thaJeztah** [comment]
For Windows and OS X, the installation uses docker-toolbox, which will setup docker-machine without user-interaction; https://docs.docker.com/engine/installation/mac/ https://docs.docker.com/engine/installation/windows/

For other installations, such as on [Ubuntu](https://docs.docker.com/engine/installation/ubuntulinux/#install), or [CentOS](https://docs.docker.com/engine/installation/centos/#install-with-yum), we explain how to start the daemon, because it's part of the installation procedure on those systems.

I don't think this needs changes to the documentation, especially since `boot2docker` (the *cli* tool) is deprecated, and using brew is currently not an officially supported installation method.

**Comment by samthebest** [comment]
**If you are wondering why I'm so pedantic about this, my use case is the automation of setting up developer mac laptops quickly**

@thaJeztah  Having read thoroughly https://docs.docker.com/engine/installation/mac/ it is only implicitly implied that the daemon will start if the "linux vm" is started via `docker-machine`.

The documentation goes to the effort to include screenshots of how to enter a password, explains downloading the toolbox in two separate steps "1.Go to the Docker Toolbox page. 2.Click the installer link to download. ", etc.  99.9% of developers don't want this level of detail and verbosity, and 99% of Docker users are developers right?  Developers wouldn't be on that page if they didn't already have an understanding of the key concepts - that is easy to remember, what developers want is the commands.

The key information, i.e. the actual command to get the daemon running, could just be at the top of the page `docker-machine create --driver virtualbox default && eval "$(docker-machine env default)"`.

I just find it ironic that a tool that makes installing software (albeit virtually) extremely automatic, is itself installed in a somewhat manual way :)

**Comment by samaimia** [comment]
**If you are wondering why I'm so pedantic about this, my use case is the automation of setting up developer mac laptops quickly**

@thaJeztah  Having read thoroughly https://docs.docker.com/engine/installation/mac/ it is only implicitly implied that the daemon will start if the "linux vm" is started via `docker-machine`.

The documentation goes to the effort to include screenshots of how to enter a password, explains downloading the toolbox in two separate steps "1.Go to the Docker Toolbox page. 2.Click the installer link to download. ", etc.  99.9% of developers don't want this level of detail and verbosity, and 99% of Docker users are developers right?  Developers wouldn't be on that page if they didn't already have an understanding of the key concepts - that is easy to remember, what developers want is the commands.

The key information, i.e. the actual command to get the daemon running, could just be at the top of the page `docker-machine create --driver virtualbox default && eval "$(docker-machine env default)"`.

I just find it ironic that a tool that makes installing software (albeit virtually) extremely automatic, is itself installed in a somewhat manual way :)

**Comment by vdemeester** [comment]
> Because the Docker daemon uses Linux-specific kernel features, you can’t run Docker natively in OS X. Instead, you must use docker-machine to create and attach to a virtual machine (VM). This machine is a Linux VM that hosts Docker for you on your Mac.

From my point of view, this is rather explicit (from the documentation you linked).

> 99.9% of developers don't want this level of detail and verbosity, and 99% of Docker users are developers right? Developers wouldn't be on that page if they didn't already have an understanding of the key concepts - that is easy to remember, what developers want is the commands.

I'm note sure about that either… on the 2 points :
- There is no real assumption it's dedicated to developers but to *any* user ; neithr that 99% on Docker users are developers or should be developers…
- Users that are on this page, ultimately, wants docker to run on their machine ; but it doesn't hurt (and even more it can only help) to make sure they understand how it's working, and what are the limitation…

**Comment by samaimia** [comment]
@vdemeester  Well it's the following statements that are required to complete the deduction:

> In an OS X installation, the docker daemon is running inside a Linux VM called `default`.

plus (much much further down) 

> 1. Create a new Docker VM.
> `docker-machine create --driver virtualbox default`
> ...
> Starting VM...

Provided one pays special attention to the command line that includes the term `default` that is mentioned earlier, and the console output that states the VM is "Started", one can deduce that the daemon is now running.

Though technically this isn't sufficient to make that error message go away since one still needs the envs to be set, hence requiring `eval "$(docker-machine env default)"`.

I maintain that the documentation has inversely applied Zipf's law - that is 80% of the effort and text includes pointless screenshots on how to follow setup forms, which since 2010 any 8 year old can do without reading documentation, while burying the 20% of useful information in obscure disparate chains of implicit reasoning.

> Press “Install” to perform the standard installation.
> ...
> Provide your password to continue with the installation.

Really? There is no argument here, let's just put `docker-machine create --driver virtualbox default && eval "$(docker-machine env default)"` at the top of the page.  If you pass me a link to the source for that documentation I'd be happy to PR it myself :)
