### ISSUE TITLE
Unable to stop or kill container

### ISSUE THREAD

**Issue by lupa18** [docker/docker#19543]
docker version: 1.9.1, build a34a1d5

docker info:
Containers: 10
Images: 208
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 228
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-57-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 7.798 GiB
Name: ---
ID: ---
Username: lupa18
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

Provide additional environment details (AWS, VirtualBox, physical, etc.):
It's running in a kvm host

List the steps to reproduce the issue:
1. Run some containers with compose
2. Try to stop them vía ctrl+c

Describe the results you received:
Some times these steps works fine, but this time the problem appear. Can't reproduce it again

Describe the results you expected:
Containers described in docker-compose.yml must stop when ctrl+c

Provide additional info you think is important:

(previously posted at: https://github.com/docker/docker/issues/10528#issuecomment-172932663)
Here I have a container that appear running and I get no response trying to stop or kill it:

2b398951bd7f solr "/opt/solr/bin/solr -" 20 hours ago Up 19 hours dateacomposer_solr_1

docker stop let me waiting, and docker kill the same. And also adding -s 9 and 11

docker logs also answer nothing

Then, viewing process from docker, there are 2 weird process: 

![seleccion_037](https://cloud.githubusercontent.com/assets/463429/12482209/1c475bf8-c02d-11e5-9b92-e2c941bd23fe.jpg)

There are impossible to kill. 

----------END REPORT ---------

#ENEEDMOREINFO

**Comment by cpuguy83** [comment]
When you say `no response`, what does this mean? Is it hanging or is it just returning with no feedback?

**Comment by lupa18** [comment]
The cursor stay there without returning to bash prompt.

**Comment by tianon** [comment]
This looks very suspiciously like #18180. :smile:

**Comment by tianon** [comment]
See especially https://github.com/docker/docker/issues/18180#issuecomment-173436661 for a nice table of who's got the fix. :+1:

**Comment by tiborvass** [comment]
Agree with tianon, closing. @lupa18 let us know if you disagree and can provide more information that shows it's unrelated (e.g. if you see this on something else than AUFS).
