### ISSUE TITLE
Problems with overlay network in docker : could not get pools config from store

### ISSUE THREAD

**Issue by brikeyes** [docker/docker#19554]
I am attempting to get the overlay networking to work on docker 1.9.1 and get this error

bk@atl-node-1:/etc/default$ docker network create -d overlay --subnet 10.10.10.0/24 multinet

Error response from daemon: error getting pools config from store during init: could not get pools config from store: Unexpected response code: 500

thanks !!!!!!!

**Comment by tiborvass** [comment]
@mrjana @mavenugo do you think this is fixed in rc1? or in the coming rc2?

@brikeyes if you are willing to test rc1 and see if you still have the same issue that'd be great.
Please read http://blog.docker.com/2016/01/docker-1-10-rc/ before you do that.

**Comment by mavenugo** [comment]
@brikeyes the error seems like an invalid `--cluster-store` config or the store operation is erroring out.
Can you please make sure it is configured properly as described in https://docs.docker.com/engine/userguide/networking/get-started-overlay/ (swarm and machine instructions are optional, but the `--cluster-store` and `--cluster-advertise` configurations in the engine daemon are mandatory to have overlay networking working).

**Comment by thaJeztah** [comment]
closing because we didn't get a response, but feel free to reply here after I've closed

**Comment by brikeyes** [comment]
yeah I am getting this again , now with docker 1.11 on Ubuntu 15 , I am stuck on this and have never been able to get this to work 

is it is not a keral version issue

**Comment by brikeyes** [comment]
I restarted the host , removed the consul container , rebuilt the container  with 
"docker run -d -p 8500:8500 -h consul --name consul progrium/consul -server –bootstrap"
and it works now

**Comment by Quantum1234** [comment]
for Ubuntu 15 and greater make sure you check the formatting in the docker.service file , if you do not format the EXEC line correctly you can get this error, as well

**Comment by Quantum1234** [comment]
experienced another incident of this kind of issue REBOOT HOST fixed it
