### ISSUE TITLE
Enforce persistency for volumes created using `docker volume create`

### ISSUE THREAD

**Issue by gittycat** [docker/docker#19565]
It is too easy to unintentionally delete a named volume by using `docker run --it --rm -v myvolume:/data someimage sh`, even if the volume was explicitly created long before the docker run command that kills it.

We'd need an option for `docker volume create` that would disallow the `--rm` option from deleting the volume. These volumes would only be deletable through the explicit `docker volume rm myvolume` command.

`docker version: 1.9.1`

**Comment by HackToday** [comment]
For what you mentioned indeed is a potential issue to improve, However, 
According to 

```
To delete the volume from disk, you must explicitly call docker rm -v against the last container with a reference to the volume.
```

Your proposal seems big change to that behavior,  also as you said, if user want to delete volume, he need to use `docker volume rm` command, it is not convenient.  As I want to delete volume when the last container reference is gone.

I think we need more inputs from maintainers. what's the valid user cases , and how to improve that.

**Comment by gittycat** [comment]
The proposed option to `docker create volume` would not change the current behaviour or documentation **unless** the proposed option is specified when creating the volume.

Current behaviour (look at the Note:)
https://docs.docker.com/engine/reference/run/#clean-up-rm

With an option like `docker create volume --sticky` for instance, the volume would only be killed through an explicit `docker volume rm`.

Some data is too important to allow it to be so easily deleted implicitly.

**Comment by coolljt0725** [comment]
see also #17907

**Comment by gittycat** [comment]
@coolljt0725 Yes, that's exactly the problem I have. I would also prefer to change the behaviour of `--rm` as is proposed in [#17907](https://github.com/docker/docker/issues/17907). I'm closing this duplicate.
