### ISSUE TITLE
seccomp filter example for a syscall with arguments

### ISSUE THREAD

**Issue by thesrinivas** [docker/docker#19572]
is there an example showing to specify the syscall with arguments (by value) as a filter?

**Comment by HackToday** [comment]
Not quite understand you real needs. 

check this https://github.com/docker/docker/blob/master/docs/security/seccomp.md if can help you

**Comment by thesrinivas** [comment]
I did go through this already.

My question is about the ability to specify as part of the seccomp filter interface a specific argument to the syscall that I would like to filter.

Example: say we'd like to disallow dup2(1,2) and not just all dup2().

**Comment by cpuguy83** [comment]
See https://github.com/docker/docker/blob/master/daemon/execdriver/native/seccomp_default.go#L126-L136
