### ISSUE TITLE
"--cgroup-parent" argument not working on CentOS 7.2

### ISSUE THREAD

**Issue by linfan** [docker/docker#19577]
Hi Guys,

It seem the latest Docker have problem when "docker run" with any image using "--cgroup-parent" argument:

```
$ sudo docker run --cgroup-parent=/ busybox ls
Error response from daemon: Cannot start container ac5df58682c7aa44fc38f48f5d79614de4b624647b8427258f188ba4dbcf8656: [8] System error: Unit name /-ac5df58682c7aa44fc38f48f5d79614de4b624647b8427258f188ba4dbcf8656.scope is not valid.
```

The same command *works well* on Ubuntu/Debian OS.

Details of systems we have meet this issue:

- Docker version: reproduced on 1.8.0-1.9.1, maybe also exist on earlier version
- OS version: CentOS/RedHat 7.x
- Kernel: 3.10.0
- Platform: reproduced on both Virtualbox and AWS, maybe all platform

Any suggestion/hint ?

**Comment by hqhq** [comment]
It's fixed in 1.10, using fs cgroup by default, `--cgroup-parent` doesn't really work as expected in your version.

**Comment by linfan** [comment]
Test docker v1.10.0-rc2 issue already fixed :+1:

**Comment by thaJeztah** [comment]
@linfan thanks for testing!
