### ISSUE TITLE
docker events return null when I use authorization plugin 

### ISSUE THREAD

**Issue by leejansq** [docker/docker#19575]
Docker Version:

Client:
 Version:      1.10.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   7faff24-unsupported
 Built:        Thu Jan 21 06:06:47 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   7faff24-unsupported
 Built:        Thu Jan 21 06:06:47 2016
 OS/Arch:      linux/amd64

Docker Info:

Containers: 15
 Running: 0
 Paused: 0
 Stopped: 15
Images: 5
Server Version: 1.10.0-dev
Storage Driver: devicemapper
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host overlay bridge
 Authorization: leeProcess
Kernel Version: 4.1.8-200.fc22.x86_64
Operating System: Fedora 22 (Twenty Two)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.46 GiB
Cluster store: etcd://192.168.0.19:4001/docker-cluster1
Cluster advertise: 127.0.0.1:2375

step:
1.docker daemon -s devicemapper  --authorization-plugin=leeProcess
2.docker events
3.at the same time,I command "docker start {CID}"

I don't get any message from events terminal
If I run other docker command ,I get the result that i expected

**Comment by HackToday** [comment]
Hi @leejansq  Could you confirm if just `docker start `  not have event ?

**Comment by leejansq** [comment]
@HackToday  All command not only docker start

**Comment by runcom** [comment]
@leejansq what is your plugin doing? is it preventing containers to start? authz plugins shouldn't interfere with docker events at all - given you aren't preventing containers from starting

**Comment by leejansq** [comment]
@runcom  the problem is ，If I use the authz plugin,I don't get any events via docker events api

**Comment by thaJeztah** [comment]
ping @runcom have you been able to reproduce this?

**Comment by liron-l** [comment]
I've published a possible fix, you can use the [authorization plugin](https://github.com/twistlock/authz) with example policy to validate.

**Comment by thaJeztah** [comment]
@liron-l so this is an issue with the plugin, not docker?

**Comment by liron-l** [comment]
@thaJeztah, no. Unfortunately the issue is with the authorization system (specifically when calling the /events endpoint).

**Comment by thaJeztah** [comment]
@liron-l alright, thanks, I'll add a "bug" label; are you able to look into this?

**Comment by liron-l** [comment]
@thaJeztah already submitted a fix in #20002, waiting for code-review.
