### ISSUE TITLE
cant install on mint LMDE (debian)

### ISSUE THREAD

**Issue by sanguis** [docker/docker#19591]
the install script is not able to detect the OS Linux Mint LMDE. which is the rolling version of mint based on Debian, Jessie.

I will be hacking this just needed to make a place holder

**Comment by sanguis** [comment]
For what ever reason when I cloned the repo and rand the install script it just worked.

I dont have time to fix this right now so leaving open

**Comment by thaJeztah** [comment]
@sanguis have you compared the online script with the one in the repository? Is it possible the script hosted at get.docker.com was still on an older version?

**Comment by LK4D4** [comment]
Closing as it's possibly was transient error.
