### ISSUE TITLE
Feature Request: Dockerfile syntax -test

### ISSUE THREAD

**Issue by HariSekhon** [docker/docker#19593]
Feature Request for ```docker build``` to add a switch to validate a Dockerfile's syntax is correct.

Since ```docker build``` has to parse the Dockerfile anyway, exposing a no op syntax test switch shouldn't be a big deal?

**Comment by bamarni** [comment]
Interesting, should it even be the default (failing early in case the Dockerfile has syntax errors)?

**Comment by thaJeztah** [comment]
duplicate of https://github.com/docker/docker/issues/19644?

**Comment by bamarni** [comment]
I think so 👍  Just moved my comment there.

**Comment by thaJeztah** [comment]
Thanks! closing this one
