### ISSUE TITLE
shell_exec + "Cannot connect to the Docker daemon. Is the docker daemon running on this host?"

### ISSUE THREAD

**Issue by wujozdep** [docker/docker#19609]
Hello,

I can't run docker via shell_exec php.
Docker runs in terminal command line, but not working via php shell_exec

shell_exec('whoami') shows "admin"
User "admin" is added to the docker group (docker runs in command line of user 'admin')
There's problem only in running docker in php script.

Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64

Can anyone help?

**Comment by cpuguy83** [comment]
How is docker running? Via docker-machine?
Most likely you need to setup the env vars correctly for the shell.

Closing since this isn't really an issue.
