### ISSUE TITLE
Remote API: Start exec and wait for process termination

### ISSUE THREAD

**Issue by marcuslinke** [docker/docker#19607]
I stumbled upon a problem when using the docker remote API and the exec functionality. When I start an exec and inspect the exec object afterwards it is undetermined whether the exec is still running or not. I' ve tried all different combinations of the exec start options (detach/tty) without success. Is there something I'm still missing? How does the remote API signal the termination of the started process to the client? Do I need to poll the inspect exec to detect that an exec is not running anymore?

**Comment by cpuguy83** [comment]
The only way is to either stay attached when you start it, or inspect the exec output.
What may help is in 1.10 the `ExitCode` will be unset if the exec has not exited yet (or started).

**Comment by marcuslinke** [comment]
@cpuguy83 Thanks! So as I understand when the exec is started with `"Detach":"false"` the remote API should cancel the upgraded connection AFTER the process terminates? Sorry to bother you but I'm asking because I try to implement an appropriate java API (https://github.com/docker-java/docker-java) and need to know the detailed behavior.
