### ISSUE TITLE
init system issues with shutdown/reboot

### ISSUE THREAD

**Issue by kiorky** [docker/docker#1960]
See also #2276 

I get a vm running upstart (my CMD is /sbin/init).
It now spawns fine processes  but shutdown behaves not correctly.

With a plain lxc-create & start, you can poweroff from with the container resulting in a container shutdown, or a reboot which will restart the container 's init.

With docker, upstart starts fine, and behave correctly with a few tweaks to it init jobs, but at shutdown or reboot, docker doesnt seem to want to kill init at the end, ot it may be init but i dont know yet how to debug that.

What's happenning is that in docker ps, we see the container running even if the only process in top is init, and this init should just be dead at this moment.

I had even once no possiblity to kill the container and must rebooted, but i didnt reproduce this behavior and i think it was just the result of a too much testing session, and do not file a bug for that yet.

You can find a dockerfile to reproduce that here, dont forget to add -p4022:22 to add the ssh port NAT rule & the suoder user is ubuntu:ubuntu: https://github.com/makinacorpus/vms/blob/master/docker/ubuntu/ubuntu

Also see http://pastebin.com/nxYcBK3e

With lxc-attach, i see only the init process, logical...

This is at least the same problem with initserv (the debian init system), init wont also die.

**Comment by jfrazelle** [comment]
is this still an issue, just checking in

**Comment by jfrazelle** [comment]
I am going to close as I believe this has been addressed and is no longer relevant. PLease feel free to ping me on this issue if you feel otherwise
