### ISSUE TITLE
nil pointer pushing on 1.10.0-rc1/master

### ISSUE THREAD

**Issue by vikstrous** [docker/docker#19606]
```
 docker info
Containers: 138
 Running: 9
 Paused: 0
 Stopped: 129
Images: 414
Server Version: 1.10.0-dev
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.3.3-2-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.709 GiB
Name: compooter
ID: GKSI:YHZC:YPNI:PAGO:EYPD:AYME:K6BY:BAIH:EBKQ:SOAK:WUFP:6MJM
Username: viktorstanchev
Registry: https://index.docker.io/v1/
```

```
 docker version
Client:
 Version:      1.10.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   ae8f7c6
 Built:        Fri Jan 22 18:34:29 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   ae8f7c6
 Built:        Fri Jan 22 18:34:29 2016
 OS/Arch:      linux/amd64
```

I was pushing to a registry behind nginx and at the time of the push, I'm not sure what state nginx was in, but the registry was not up yet, so nginx returned some thing random and got the docker daemon stuck. I wasn't able to retry the push until I restarted the daemon. Every time I tried to push after this I got this:

```
docker push localhost/admin/aaaa
The push refers to a repository [localhost/admin/aaaa]

5f70bf18a086: Preparing 
```

Stack trace in this gist:
https://gist.github.com/vikstrous/5870d9266cf19c084a05

**Comment by cpuguy83** [comment]
ping @aaronlehmann

**Comment by HackToday** [comment]
seems nginx returns something which docker could not handle

Jan 23 00:47:57 compooter docker[6480]: time="2016-01-23T00:47:57.559829069-08:00" level=error msg="Upload failed: Error parsing HTTP response: invalid character '<' looking for beginning of value: \"<html>\\r\\n<head><title>404 Not Found</title></head>\\r\\n<body bgcolor=\\\"white\\\">\\r\\n<center><h1>404 Not Found</h1></center>\\r\\n<hr><center>nginx/1.8.0</center>\\r\\n</body>\\r\\n</html>\\r\\n\""
Jan 23 00:47:57 compooter docker[6480]: 2016/01/23 00:47:57 http: panic serving @: close of closed channel
