### ISSUE TITLE
ENTRYPOINT unsets CMD of parent image?

### ISSUE THREAD

**Issue by vincentcr** [docker/docker#19611]
I want to customize an image bootstrap by using the `ENTRYPOINT` to load secrets from a file, then execute the `CMD`. It works fine if I set `CMD` and `ENTRYPOINT` in the same Dockerfile. But it seems like setting `ENTRYPOINT` in a Dockerfile unsets any `CMD` that was set in the image it was `FROM`ed. 

Since I want to do this in many images, it would be nice to be able to just have to set the ENTRYPOINT rather than having to copy/paste the CMD as well.

`docker version`:

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:
```
Containers: 31
Images: 925
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 987
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: default
ID: 3J5W:42CN:ALMZ:EXXQ:E5HL:SPIB:TVDE:35AW:VFBH:F4YP:RTZF:YQPE
Debug mode (server): true
 File Descriptors: 25
 Goroutines: 56
 System Time: 2016-01-23T17:26:27.19992054Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

Steps to reproduce:

1. Create Docker image1, set `CMD`
2. Create Docker image2 `FROM` image1, set `ENTRYPOINT`
3. Run image2, `ENTRYPOINT` does not have `CMD` as arguments.

Repeat, but set `CMD` at step 2, `ENTRYPOINT` will then have `CMD` as arguments.

**Comment by cpuguy83** [comment]
Correct, any time you change the entrypoint, it will clear out the CMD.
This is expected/designed beavior.

**Comment by janeczku** [comment]
@cpuguy83 Just run in similar issue. Overriding the entrypoint in a run command unsets the default CMD declared in the image. How is this expected behavior? This is not documented anywhere, is it?

**Comment by cpuguy83** [comment]
@janeczku `CMD` is passed as an argument to the entrypoint.
If the entrypoint changes, then it can be assumed (generally) that `CMD` is no longer valid.

**Comment by janeczku** [comment]
@cpuguy83 Thanks for the explanation. This clearly needs to be documented. UX-wise this *is* unexpected behavior.

**Comment by cpuguy83** [comment]
@janeczku PR's are welcome... though I'd be surprised if this is not already documented.

**Comment by janeczku** [comment]
It isn't. I literally wasted an hour debugging a container that failed after overriding the ENTRYPOINT not the least expecting that this would override the default CMD/arguments of the image. Will make a PR later tomorrow. Cheers!
