### ISSUE TITLE
Docker Nginx always awaiting response.

### ISSUE THREAD

**Issue by losywee** [docker/docker#19618]
### My docker version:

~ $ sudo docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
### Docker info
```bash
sudo docker info

Containers: 1
Images: 16
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 18
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-32-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 7.283 GiB
Name: loaywee
ID: B3UX:MDTW:UUHI:IQTF:ESFU:Z4W2:ZCQR:DZYA:KZH6:EW3L:7PKC:2RLD
WARNING: No swap limit support

```

### System kernel

```
uname -a
Linux loaywee 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

### Create Dockerfile

FROM nginx
COPY nginx.conf /etc/nginx/nginx.conf
COPY content /usr/share/nginx/html

### Create container

```bash
sudo docker run --name  mynginx  -d -p 127.0.0.1:8080:80 nginx
```

### Wget 

wget 127.0.0.1:8080
--2016-01-24 11:09:17--  http://127.0.0.1:8080/
connecting 127.0.0.1:8080... connected。
HTTP request has been issued and is awaiting response ...

>  When I open it in browser, page hang and not have any respond.

### Localhost network listen
```bash
sudo netstat -anp | grep 8080
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      22526/docker-proxy
tcp        0      0 127.0.0.1:50480         127.0.0.1:8080          ESTABLISHED 24737/wget      
tcp      112      0 127.0.0.1:8080          127.0.0.1:50480         ESTABLISHED 22526/docker-proxy
```

**Comment by thaJeztah** [comment]
Is there a reason you publish on `127.0.0.1`?

Also, what result do you get when running the nginx container *without* custom configuration and files?

**Comment by losywee** [comment]
Yet not, I  try to map without "127.0.0.1" and have the same issue.

**Comment by thaJeztah** [comment]
Hm, unable to reproduce;

```
root@ubuntu-1gb-sfo1-01:~# docker run -d -p 8080:80 nginx
16ecbc85c2313f2cbf1a8ff1c774d75721e2490694fc0f1fc67e0ea899c5e058
root@ubuntu-1gb-sfo1-01:~# curl 127.0.0.1:8080
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

What's in your nginx.conf? You should make sure it's listening on `0.0.0.0`, not `127.0.0.1`, because `127.0.0.1` is **inside** the container, not inside the *host*

**Comment by losywee** [comment]
The nginx.conf is not changed, just for test command COPY.

**Comment by thaJeztah** [comment]
> I had found a phenomenon that when I push Dockerfile to build in cloud server, it works fine.

Does that mean this issue is resolved for you? Or are you still having this issue?

**Comment by losywee** [comment]
Thanks, but the problem is when I build in my localhost.

```
sudo docker inspect mynginx
[
{
    "Id": "7de9c680508c1c2ae2e146db57a07c469b90d14fa3eb4929f0fc328642628769",
    "Created": "2016-01-24T08:20:06.528247276Z",
    "Path": "nginx",
    "Args": [
        "-g",
        "daemon off;"
    ],
    "State": {
        "Status": "running",
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 13118,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2016-01-24T08:20:07.098504733Z",
        "FinishedAt": "0001-01-01T00:00:00Z"
    },
    "Image": "407195ab8b072ce8b237f664b8d032704e8047b8e64139cc2e017163f7161647",
    "ResolvConfPath": "/var/lib/docker/containers/7de9c680508c1c2ae2e146db57a07c469b90d14fa3eb4929f0fc328642628769/resolv.conf",
    "HostnamePath": "/var/lib/docker/containers/7de9c680508c1c2ae2e146db57a07c469b90d14fa3eb4929f0fc328642628769/hostname",
    "HostsPath": "/var/lib/docker/containers/7de9c680508c1c2ae2e146db57a07c469b90d14fa3eb4929f0fc328642628769/hosts",
    "LogPath": "/var/lib/docker/containers/7de9c680508c1c2ae2e146db57a07c469b90d14fa3eb4929f0fc328642628769/7de9c680508c1c2ae2e146db57a07c469b90d14fa3eb4929f0fc328642628769-json.log",
    "Name": "/losywee-nginx",
    "RestartCount": 0,
    "Driver": "aufs",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "AppArmorProfile": "",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": null,
        "ContainerIDFile": "",
        "LxcConf": [],
        "Memory": 0,
        "MemoryReservation": 0,
        "MemorySwap": 0,
        "KernelMemory": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
        "MemorySwappiness": -1,
        "Privileged": false,
        "PortBindings": {
            "80/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "8080"
                }
            ]
        },
        "Links": null,
        "PublishAllPorts": false,
        "Dns": [],
        "DnsOptions": [],
        "DnsSearch": [],
        "ExtraHosts": null,
        "VolumesFrom": null,
        "Devices": [],
        "NetworkMode": "default",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "GroupAdd": null,
        "RestartPolicy": {
            "Name": "no",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
        "CgroupParent": "",
        "ConsoleSize": [
            0,
            0
        ],
        "VolumeDriver": ""
    },
    "GraphDriver": {
        "Name": "aufs",
        "Data": null
    },
    "Mounts": [
        {
            "Name": "f5cc3b0e1e07125426071d386fec1f37e436f798f05cfd6786c05a9544159a25",
            "Source": "/var/lib/docker/volumes/f5cc3b0e1e07125426071d386fec1f37e436f798f05cfd6786c05a9544159a25/_data",
            "Destination": "/var/cache/nginx",
            "Driver": "local",
            "Mode": "",
            "RW": true
        }
    ],
    "Config": {
        "Hostname": "7de9c680508c",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": {
            "443/tcp": {},
            "80/tcp": {}
        },
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "NGINX_VERSION=1.9.9-1~jessie"
        ],
        "Cmd": [
            "nginx",
            "-g",
            "daemon off;"
        ],
        "Image": "nginx",
        "Volumes": {
            "/var/cache/nginx": {}
        },
        "WorkingDir": "",
        "Entrypoint": null,
        "OnBuild": null,
        "Labels": {},
        "StopSignal": "SIGTERM"
    },
    "NetworkSettings": {
        "Bridge": "",
        "SandboxID": "8e2f3c539b1e4204f76154930bfbc7b6714b5c3f7ef275691ccec721a208b20b",
        "HairpinMode": false,
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "Ports": {
            "443/tcp": null,
            "80/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "8080"
                }
            ]
        },
        "SandboxKey": "/var/run/docker/netns/8e2f3c539b1e",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null,
        "EndpointID": "bacfb69e55812789e7f8b0c72d1edb2d409553baf85f446440d14c657d8502e5",
        "Gateway": "172.17.0.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "172.17.0.2",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "MacAddress": "02:42:ac:11:00:02",
        "Networks": {
            "bridge": {
                "EndpointID": "bacfb69e55812789e7f8b0c72d1edb2d409553baf85f446440d14c657d8502e5",
                "Gateway": "172.17.0.1",
                "IPAddress": "172.17.0.2",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "MacAddress": "02:42:ac:11:00:02"
            }
        }
    }
}
]

```

**Comment by thaJeztah** [comment]
What do you get if you just run the official nginx image, without making changes (see my earlier comment https://github.com/docker/docker/issues/19618#issuecomment-174248779), does that work?

The output of docker inspect looks good to me, I don't see strange things in there

**Comment by losywee** [comment]
Thanks for your patience, it run the official nginx image.

**Comment by thaJeztah** [comment]
Strange. Are you using a proxy server? Is there perhaps a firewall active that blocks access? I really wonder if this is a docker bug or an issue in your setup/configuration/network

**Comment by losywee** [comment]
My computer use Cisco anyconnect client, what factor will cause the result?

**Comment by losywee** [comment]
```
service --status-all
 [ + ]  acpid
 [ - ]  anacron
 [ ? ]  atieventsd
 [ + ]  avahi-daemon
 [ ? ]  binfmt-support
 [ + ]  bluetooth
 [ - ]  brltty
 [ - ]  casper
 [ ? ]  console-setup
 [ ? ]  cpufrequtils
 [ + ]  cron
 [ ? ]  cryptdisks
 [ ? ]  cryptdisks-early
 [ + ]  cups
 [ + ]  cups-browsed
 [ - ]  dbus
 [ ? ]  dns-clean
 [ - ]  dnsmasq
 [ - ]  docker
 [ + ]  friendly-recovery
 [ - ]  grub-common
 [ - ]  hddtemp
 [ ? ]  irqbalance
 [ + ]  kerneloops
 [ ? ]  killprocs
 [ ? ]  kmod
 [ - ]  lm-sensors
 [ ? ]  loadcpufreq
 [ + ]  mdm
 [ ? ]  networking
 [ + ]  nmbd
 [ ? ]  ondemand
 [ - ]  openvpn
 [ ? ]  pppd-dns
 [ - ]  procps
 [ - ]  pulseaudio
 [ ? ]  rc.local
 [ + ]  resolvconf
 [ - ]  rsync
 [ + ]  rsyslog
 [ + ]  samba
 [ - ]  samba-ad-dc
 [ + ]  saned
 [ - ]  sendmail
 [ ? ]  sendsigs
 [ + ]  smbd
 [ ? ]  speech-dispatcher
 [ - ]  sudo
 [ - ]  udev
 [ ? ]  umountfs
 [ ? ]  umountnfs.sh
 [ ? ]  umountroot
 [ - ]  unattended-upgrades
 [ - ]  urandom
 [ - ]  virtualbox-guest-utils
 [ ? ]  virtualbox-guest-x11
 [ + ]  vpnagentd
 [ - ]  x11-common

```

**Comment by losywee** [comment]
ifconfig
cscotun0 Link encap: Not specified hardware address 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet address: 192.168.10.231 point: 192.168.10.231 Mask: 255.255.255.0
          inet6 address: fe80 :: 39fa: 675c: 5d72: 5a72 / 128 Scope: Link
          UP POINTOPOINT RUNNING NOARP MULTICAST MTU: 1329 Metric: 1
          Receive packets: 11248 errors: 0 dropped: 0 Overload: 0 frame: 0
          Send packets: 9500 errors: 0 dropped: 0 Overload: 0 carrier: 0
          Collision: 0 Send queue length: 500
          Receive Byte: 10769752 (10.7 MB) Send Byte: 966213 (966.2 KB)

docker0 Link encap: Ethernet hardware address 02: 42: ed: aa: 46: e0
          inet address: 172.17.0.1 Broadcast: 0.0.0.0 Mask: 255.255.0.0
          inet6 address: fe80 :: 42: edff: feaa: 46e0 / 64 Scope: Link
          UP BROADCAST RUNNING MULTICAST MTU: 1329 Metric: 1
          Receive packets: 282 errors: 0 dropped: 0 Overload: 0 frame: 0
          Send packets: 39 errors: 0 dropped: 0 Overload: 0 carrier: 0
          Collision: 0 Send queue length: 0
          Receive Byte: 12000 (12.0 KB) bytes sent: 6110 (6.1 KB)

eth0 Link encap: Ethernet hardware address c8: 60: 00: a7: 25: df
          UP BROADCAST MULTICAST MTU: 1500 Metric: 1
          Receive packets: 0 errors: 0 dropped: 0 Overload: 0 frame: 0
          Send packets: 0 errors: 0 dropped: 0 Overload: 0 carrier: 0
          Collision: 0 Send queue length: 1000
          Receiving bytes: 0 (0.0 B) send byte: 0 (0.0 B)

lo Link encap: Local Loopback
          inet address: 127.0.0.1 Mask: 255.0.0.0
          inet6 address: :: 1/128 Scope: Host
          UP LOOPBACK RUNNING MTU: 65536 Metric: 1
          Receive packets: 33516 errors: 0 dropped: 0 Overload: 0 frame: 0
          Send packets: 33516 errors: 0 dropped: 0 Overload: 0 carrier: 0
          Collision: 0 Send queue length: 0
          Receive Byte: 15292860 (15.2 MB) Send Byte: 15292860 (15.2 MB)

vethd5dc2d3 Link encap: Ethernet hardware address 1a: 4b: 35: 69: cf: 5e
          inet6 address: fe80 :: 184b: 35ff: fe69: cf5e / 64 Scope: Link
          UP BROADCAST RUNNING MULTICAST MTU: 1329 Metric: 1
          Receive packets: 41 errors: 0 dropped: 0 Overload: 0 frame: 0
          Sends the packet: 6 Error: 0 dropped: 0 Overload: 0 carrier: 0
          Collision: 0 Send queue length: 0
          Receiving bytes: 2034 (2.0 KB) bytes sent: 771 (771.0 B)

wlan0 Link encap: Ethernet hardware address 00: 08: ca: 6c: 4c: 0e
          inet address: 192.168.1.117 Broadcast: 192.255.255.255 mask: 255.0.0.0
          inet6 address: fe80 :: 208: caff: fe6c: 4c0e / 64 Scope: Link
          UP BROADCAST RUNNING MULTICAST MTU: 1500 Metric: 1
          Receive packets: 200920 errors: 0 dropped: 0 Overload: 0 frame: 0
          Send packets: 101331 errors: 0 dropped: 0 Overload: 0 carrier: 0
          Collision: 0 Send queue length: 1000
          Receive Byte: 126990844 (126.9 MB) Send Byte: 21146144 (21.1 MB)

**Comment by thaJeztah** [comment]
> My computer use Cisco anyconnect client, what factor will cause the result? Ubuntu ufw not active.

I think that may explain your issue. IIRC, AnyConnect captures all traffic, and sends it through the VPN, resulting in it not being able to connect. Other issues related to AnyConnect can be found here; https://github.com/docker/docker/issues/9434. I don't think this is a bug in docker, or anything we can do to resolve this.

**Comment by losywee** [comment]
Thanks! Let me have a try.

**Comment by losywee** [comment]
I had tried to uninstall Cisco any connect, with the same issue.

**Comment by losywee** [comment]
```
sudo sysctl net.ipv4.ip_forward=1 && sudo sysctl -p
```
When I run above, it works fine. Strange. Thanks for you patience.
