### ISSUE TITLE
[1.10] Content-addressability inconsistent?

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#19623]
I'm not sure this is expected, but the content-addressable store produces different results for a *migrated* store, than a *fresh* store.

### Migrated from 1.9.1 -> 1.10

```bash
$ docker images -a --no-trunc
REPOSITORY          TAG                 IMAGE ID                                                                  CREATED             SIZE
<none>              <none>              sha256:a3e5b6fb3fcedcdc1f7dfca29c7a23d1a1b8714cd75d1c021cc9c296bef0a6d1   3 months ago        960 B
hello-world         latest              sha256:690ed74de00f99a7d00a98a5ad855ac4febd66412be132438f9b8dbd300a937d   3 months ago        960 B

$ tree /var/lib/docker/aufs
.
|-- diff
|   |-- 0a6ba66e537a53a5ea94f7c6a99c534c6adb12e3ed09326d4bf3b38f7c3ba4e7
|   `-- b901d36b6f2fd759c362819c595301ca981622654e7ea8a1aac893fbd2740b4c
|       `-- hello
|-- layers
|   |-- 0a6ba66e537a53a5ea94f7c6a99c534c6adb12e3ed09326d4bf3b38f7c3ba4e7
|   `-- b901d36b6f2fd759c362819c595301ca981622654e7ea8a1aac893fbd2740b4c
`-- mnt
    |-- 0a6ba66e537a53a5ea94f7c6a99c534c6adb12e3ed09326d4bf3b38f7c3ba4e7
    `-- b901d36b6f2fd759c362819c595301ca981622654e7ea8a1aac893fbd2740b4c
```

### Clean pull with docker 1.10

```bash
$ docker images -a --no-trunc
REPOSITORY          TAG                 IMAGE ID                                                                  CREATED             SIZE
hello-world         latest              sha256:690ed74de00f99a7d00a98a5ad855ac4febd66412be132438f9b8dbd300a937d   3 months ago        960 B

$ tree /var/lib/docker/aufs
/var/lib/docker/aufs
|-- diff
|   |-- 3f3b15f8cdc8fe744e8d389bfd3c58d292d3d93a32905c1c4df339af9413bd82
|   |   `-- hello
|   `-- a8403605c77950a2f392ef0182448c26eb373bc0c2cafded6711130721c80ab0
|-- layers
|   |-- 3f3b15f8cdc8fe744e8d389bfd3c58d292d3d93a32905c1c4df339af9413bd82
|   `-- a8403605c77950a2f392ef0182448c26eb373bc0c2cafded6711130721c80ab0
`-- mnt
    |-- 3f3b15f8cdc8fe744e8d389bfd3c58d292d3d93a32905c1c4df339af9413bd82
    `-- a8403605c77950a2f392ef0182448c26eb373bc0c2cafded6711130721c80ab0
```

### Differences;

- Migrated store still shows the intermediate images (`docker images -a` shows two images for `hello-world`)
- ~~Image ID (`sha256:`) is different~~ edit: no, just not all present
- diff/layers/mnt ID's are different

Tested with experimental builds;

```
Client:
 Version:      1.10.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   c91045a
 Built:        Fri Jan 22 11:24:19 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.10.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   c91045a
 Built:        Fri Jan 22 11:24:19 2016
 OS/Arch:      linux/amd64
 Experimental: true
 ```

**Comment by thaJeztah** [comment]
ping @tonistiigi feel free to close if this is expected, I just noticed this, and was wondering if this is *expected*; also this may be confusing for users, so if this is expected, maybe it should be documented as part of  https://github.com/docker/docker/pull/19240

**Comment by tonistiigi** [comment]
@thaJeztah This is expected. Notice the image IDs are the same `sha256:690ed74de00f99a7d00a98a5ad855ac4febd66412be132438f9b8dbd300a937d`. The difference is not from migration but from the change that from `v1.10` pulled images are flat(you only download a single image and not the whole parent chain). On migration, we do not delete any old images so you still keep the parent images as well(without data duplication).

Graphdriver IDs are local only and never leave the system. On pulls, random IDs are always generated. This is mainly to reduce the possibility of container and image IDs colliding in graphdriver level(if someone manages to control container ID for  example). If you want to compare the content addressable IDs for the layers then these are stored in `/var/lib/docker/image/aufs/layerdb/sha256`.

**Comment by thaJeztah** [comment]
> Notice the image IDs are the same sha256:690ed74de00f99a7d00a98a5ad855ac4febd66412be132438f9b8dbd300a937d. 

oh, LOL, I think I had been going back/forth a bit too much and looked at the wrong sha :blush: you're right, it is the same (was checking for https://github.com/docker/docker/pull/19610, downgraded to 1.9, then upgraded to 1.10)

I'll close this one; apart from the intermediate layer not being present, there's no difference, thx
