### ISSUE TITLE
Docker can't run Intel PIN 

### ISSUE THREAD

**Issue by labba** [docker/docker#19626]
i'm trying to use docker and when i install the intel PIN tool (2.13) and run it i get " this linux version is not supported"
but on the native ubuntu 12.04 is does work... only doesn't work on docker image

**Comment by thaJeztah** [comment]
Can you provide a bit more information, steps to reproduce? Currently we don't have enough information to look into your issue

**Comment by cpuguy83** [comment]
Also going to close this since I saw this is cross-posted on the mailing list.

**Comment by labba** [comment]
my bad ... didn't know that docker doesn't expose the kernel version of the built system but exposes the host kernel version 

please close as not a bug .
