### ISSUE TITLE
experimental.docker.com installs regular release on ubuntu/debian

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#19620]
Using `curl -fsSL https://experimental.docker.com | sh` installs the current release (1.9.1) on Ubuntu/Debian, not the experimental build.

To fix this, this line;

    url="https://experimental.docker.com"

Should be changed to (trailing slash)

    url="https://experimental.docker.com/"

Otherwise the wrong repository is selected;

    elif [ "https://experimental.docker.com/" = "$url" ]; then
         repo='experimental'
    fi

**Comment by thaJeztah** [comment]
ping @jfrazelle because you have access to that server :smile:

**Comment by jfrazelle** [comment]
If we merge a PR it will automatically fix itself tomorrow

**Comment by thaJeztah** [comment]
> If we merge a PR it will automatically fix itself tomorrow

Oh! Looks like I interpreted that as "no change needed, it'll fix itself", haha

**Comment by jfrazelle** [comment]
i meant after we fix it it will be magic ;)

**Comment by jfrazelle** [comment]
and its all better :D, thanks for noticing!!! https://experimental.docker.com/

**Comment by thaJeztah** [comment]
wooohoo!
