### ISSUE TITLE
jenkins does not use DOCKER_GRAPHDRIVER

### ISSUE THREAD

**Issue by pandrew** [docker/docker#19637]
Some builds on jenkins.dockerproject.org is not using the DOCKER_GRAPHDRIVER environment variable that is set by default using docker info.

DOCKER_GRAPHDRIVER is set using:
```
: ${DOCKER_GRAPHDRIVER:=$( docker info | awk -F ': ' '$1 == "Storage Driver" { print $2; exit }' )}
...
+ + awk -F :  $1 == "Storage Driver" { print $2; exit }
docker info
WARNING: No swap limit support
+ : btrfs
```
Execution where variable is never used:
```
+ docker run --rm -t --privileged --name docker-master3755 -e DOCKER_GRAPHDRIVER -e DOCKER_EXECDRIVER=native -e TIMEOUT=90m docker:master hack/make.sh
```

Test should use `-e DOCKER_GRAPHDRIVER=$DOCKER_GRAPHDRIVER`

`docker version`:
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

`docker info`:
Containers: 3
Images: 70
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 76
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 2
Total Memory: 1.956 GiB
Name: d
ID: O63J:2JYF:767U:YN7D:YPLV:ZOQH:NZOR:PO5C:PYG3:4F2S:MHVW:6GXB
Debug mode (server): true
 File Descriptors: 18
 Goroutines: 38
 System Time: 2016-01-24T15:55:56.627497953Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=vmwarevsphere

`uname -a`:
Darwin mbp 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64

**Comment by HackToday** [comment]
Did master branch have this issue ? I just not find related code in docker, maybe they are hosted in other repository. @jfrazelle  do you know this ?

**Comment by jfrazelle** [comment]
We run tests on master on ALL graph drivers. We run unit tests with vfs.
This is working as intended so I'm going to close

**Comment by jfrazelle** [comment]
By unit tests I meant PRs

**Comment by pandrew** [comment]
@HackToday You can see this in the jenkins configuration on: https://jenkins.dockerproject.org/view/Docker/job/Docker%20Master/configure


```
: ${DOCKER_GRAPHDRIVER:=$( docker info | awk -F ': ' '$1 == "Storage Driver" { print $2; exit }' )}

if [ ! -z "$GCCGO" ];  then
	echo "Building with gccgo"
	export ARCH=`uname -m`
	docker build --rm --force-rm  -f Dockerfile.gccgo -t docker:master .
	docker run --rm -t --privileged --name docker-master$BUILD_NUMBER -e DOCKER_GRAPHDRIVER -e DOCKER_EXECDRIVER=native -e TIMEOUT="180m" docker:master hack/make.sh gccgo test-unit test-integration-cli     
else
	docker build --rm --force-rm -t docker:master .
	docker run --rm -t --privileged --name docker-master$BUILD_NUMBER -e DOCKER_GRAPHDRIVER -e DOCKER_EXECDRIVER=native -e TIMEOUT="90m" docker:master hack/make.sh
fi
```

I know that it defaults to vfs by looking at .integration-test-start. I thought it was supposed to be used in the execution script by the looks of it. =)

**Comment by jfrazelle** [comment]
We have different master builds _per_ graphdriver, we test all PRs on vfs
to avoid random one off failures. Almost like when conducting a science
experiment, we control the variables.

**Comment by pandrew** [comment]
I guess thats what the label expressions are controlling? Docker does not seem to need the variable set as in the example above as i thoght  but i can only get that working properly with exported variables. Anyway, really thanks for clearing it up.
