### ISSUE TITLE
Add docker stats --all

### ISSUE THREAD

**Issue by omercnet** [docker/docker#19648]
Add docker stats --all or --nice that would essentially run `docker stats $(docker ps --format={{.Names}})`

**Comment by HackToday** [comment]
not sure if --all is good idea.

Since 
`docker stats $(docker ps --format={{.Names}})`  just replace ID with name.

**Comment by omercnet** [comment]
docker stats by itself doesn't output anything, it expects IDs or names
`--all` would indicate listing all the running containers, default format would be names

**Comment by coolljt0725** [comment]
The coming version 1.10.0, `docker stats`  will listing all the running containers and `docker stats --all` will listing all the containers

**Comment by cpuguy83** [comment]
Yep, this already exists for 1.10.
Thanks!

**Comment by omercnet** [comment]
I see now `--all` show all containers, but the functionality I'm looking for is an easy way to show stas with container names instead of IDs just like `docker stats $(docker ps --format={{.Names}})` does

**Comment by thaJeztah** [comment]
@omercnet can you open a new feature request to have stats show container names instead of ID's (or both)?

**Comment by omercnet** [comment]
#20973
