### ISSUE TITLE
docker logs does not handle updating messages well

### ISSUE THREAD

**Issue by athyuttamre** [docker/docker#19645]
`docker logs` only shows messages that have been completely output to stdout, not those that are being replaced in real-time with a carriage return.

For example, many downloading / progress report messages continuously replace a line of output using a carriage return. Docker logs does not show this in real-time.

For a specific example, consider the `meteor update` command for the web framework Meteor. 

I have a container running that command on launch, and the first screenshot shows the output of `docker logs -f signmeup_app_1`. At the very bottom, the loading message, `Selecting package versions   |`, should be shown, but isn't.

<img width="604" alt="screenshot 2016-01-25 01 55 51" src="https://cloud.githubusercontent.com/assets/1485350/12538728/5fbca3c0-c307-11e5-8284-11a9079a3b55.png">

The second screenshot shows me opening up a new `bash` session inside the container to run the command myself. You can see the loading message is shown and is constantly updated as the spinner at the right spins.

<img width="514" alt="screenshot 2016-01-25 01 56 31" src="https://cloud.githubusercontent.com/assets/1485350/12538729/66e54c74-c307-11e5-91e1-54354b71fa57.png">

Any fixes for this?

**Comment by cpuguy83** [comment]
Hi.
This is expected behavior.
The loggers only get the logs when the newline has been hit.
If you want live access, you should use the `attach` endpoint.

**Comment by athyuttamre** [comment]
Gotcha, thanks Brian!






On Sun, Jan 24, 2016 at 5:58 PM -0800, "Brian Goff" <notifications@github.com> wrote:












Closed #19645.
