### ISSUE TITLE
Engine 1.10.0-rc1 returns different error string on image not found, breaks existing clients

### ISSUE THREAD

**Issue by dhiltgen** [docker/docker#19652]
Clients that leverage https://github.com/samalba/dockerclient/blob/master/dockerclient.go#L117  expect the error string coming back from the engine to contain  "No such image" when specifying an invalid image.  It appears that invalid image IDs in 1.10.0-rc1 are now returning errors that look like this:

```
time="2016-01-25T04:04:03.277926426Z" level=error msg="Handler for POST /v1.15/containers/create returned error: open /mnt/sda1/var/lib/docker/image/aufs/imagedb/content/sha256/c23997c23be934d8d7b8ec72436ae734588a0cba8f07995d9317c5aee1d60576: no such file or directory"
```

This appears to break swarm 1.1.0-rc1 which is no longer able to detect a missing image on a node and fall back to image affinity scheduling decisions.  See https://github.com/docker/swarm/blob/master/cluster/engine.go#L700 and https://github.com/docker/swarm/blob/master/cluster/swarm/cluster.go#L134

While the code in swarm could be hardened to look for the new strings, since there are many clients out there that leverage https://github.com/samalba/dockerclient which may not ship a new version aligned with the 1.10 release, it seems like engine should make sure "No such image" shows up in the error message someplace to prevent breaking them.

**Comment by thaJeztah** [comment]
We should at least make sure that older API versions return the old error message. (But looking at the error message we return, it should be fixed for all version, as the new message contains information that's irrelevant to the client)

Do we return a 404 status in these cases? Hardening Swarm to check for the status-code instead of the message sounds like a better approach overall

/cc @calavera @tiborvass

**Comment by thaJeztah** [comment]
Actually, meant to ping @tonistiigi, as I expect this to be related to the new content addressable store

**Comment by dhiltgen** [comment]
I haven't tested it, but just looking at the code in the new engine-api client, I think it too will get tripped up by the change in error message:

https://github.com/docker/engine-api/blob/master/client/container_create.go#L36 and 42

It seems to be looking for 404 && "No such image"

**Comment by dhiltgen** [comment]
To elaborate on my test case a little, as this may be specific to the usage pattern, my test scenario builds images without naming/tagging, then does an inspect, and tries to create containers based on the image ID, which in 1.10 winds up being something like `sha256:c23997c23be934d8d7b8ec72436ae734588a0cba8f07995d9317c5aee1d60576`

In my particular case, I was testing on swarm, which tried to run this container on the wrong node in the cluster first, but since it didn't get the expected error string back, it never retried with image affinity - the image is present on another node in the cluster from the prior build.

**Comment by thaJeztah** [comment]
Thanks for the extra info.

Agreed, the error message clearly looks to be "off". Looking at the engine-api code, there's some code smell; these lines seem to duplicate the other part, and don't check if `serverResp` or `err` are nil;
https://github.com/docker/engine-api/blob/a4ec5b48ecccfd2da5722e304137a8e68d40a30f/client/container_create.go#L42-L48

**Comment by tonistiigi** [comment]
@dhiltgen What am I doing wrong when I try to reproduce this?

```
» curl 0.0.0.0:2345/images/sha256:0cb40641836c461bc97c793971d84d758371ed682042457523e4ae701efe7ec8/json -i
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
Server: Docker/1.10.0-rc1 (linux)
X-Content-Type-Options: nosniff
Date: Mon, 25 Jan 2016 17:46:53 GMT
Content-Length: 87

No such image: sha256:0cb40641836c461bc97c793971d84d758371ed682042457523e4ae701efe7ec8


» curl 0.0.0.0:2345/images/foobar/json -i
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
Server: Docker/1.10.0-rc1 (linux)
X-Content-Type-Options: nosniff
Date: Mon, 25 Jan 2016 17:47:00 GMT
Content-Length: 22

No such image: foobar


» curl 0.0.0.0:2345/images/foobar/json -i
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
Server: Docker/1.9.1 (linux)
Date: Mon, 25 Jan 2016 17:47:13 GMT
Content-Length: 22

No such image: foobar


» curl 0.0.0.0:2345/images/sha256:0cb40641836c461bc97c793971d84d758371ed682042457523e4ae701efe7ec8/json -i
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
Server: Docker/1.9.1 (linux)
Date: Mon, 25 Jan 2016 17:47:23 GMT
Content-Length: 87

No such image: sha256:0cb40641836c461bc97c793971d84d758371ed682042457523e4ae701efe7ec8
```

**Comment by dhiltgen** [comment]
Give me a bit to distill down my test code to a minimalist repro scenario.

**Comment by dhiltgen** [comment]
Here's an example:
```go

package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"

	"github.com/docker/docker/pkg/tlsconfig"
	"github.com/samalba/dockerclient"
)

var (
	Image = "sha256:c23997c23be934d8d7b8ec72436ae734588a0cba8f07995d9317c5aee1d60576"
)

func main() {
	fmt.Printf("Client Version: %s\n", dockerclient.APIVersion)
	certDir := os.Getenv("DOCKER_CERT_PATH")
	if certDir == "" {
		log.Fatalf("This client only works with a TLS enabled endpoint")
	}
	caFilename := filepath.Join(certDir, "ca.pem")
	certFilename := filepath.Join(certDir, "cert.pem")
	keyFilename := filepath.Join(certDir, "key.pem")
	tlsConfig, err := tlsconfig.Client(tlsconfig.Options{
		CAFile:   caFilename,
		CertFile: certFilename,
		KeyFile:  keyFilename,
	})
	if err != nil {
		fmt.Printf("Failed to setup TLS: %s\n", err)
		os.Exit(1)
	}
	c, err := dockerclient.NewDockerClient(os.Getenv("DOCKER_HOST"), tlsConfig)
	if err != nil {
		fmt.Printf("Failed to connect: %s\n", err)
		os.Exit(1)
	}

	// just make sure the connection is happy
	ver, err := c.Version()
	if err != nil {
		log.Fatalf("Failed to get version: %s", err)
	}
	log.Println("Conencted to server version %s", ver.Version)

	// Now set up the container
	cfg := &dockerclient.ContainerConfig{
		Image: Image,
		Cmd: []string{
			"--help",
		},
	}
	hostConfig := &dockerclient.HostConfig{}
	log.Printf("Creating container\n")
	containerId, err := c.CreateContainer(cfg, "", nil)
	if err != nil {
		log.Fatalf("Failed to create container: %s", err)
	}

	//defer c.RemoveContainer(containerId, false, false)

	log.Printf("Starting container %s\n", containerId)
	if err := c.StartContainer(containerId, hostConfig); err != nil {
		log.Fatalf("Failed to launch container: %s\n", err)
	}
	//defer c.StopContainer(containerId, 5)
	log.Printf("Done - docker logs %s\n", containerId)
}
```

When I run it pointed at a machine with 1.10.0-rc1, here's what I see:

```
Client Version: v1.15
2016/01/25 10:06:27 Conencted to server version %s 1.10.0-rc1
2016/01/25 10:06:27 Creating container
2016/01/25 10:06:27 Failed to create container: open /mnt/sda1/var/lib/docker/image/aufs/imagedb/content/sha256/c23997c23be934d8d7b8ec72436ae734588a0cba8f07995d9317c5aee1d60576: no such file or directory
```

**Comment by dhiltgen** [comment]
I should mention, this may not require doing the operation over TLS, but all my rigs are set up that way (using docker-machine) so that's how I have my client code structured.
