### ISSUE TITLE
Volume plug-in that provides mount-points via FUSE yields "operation not supported"

### ISSUE THREAD

**Issue by quofelix** [docker/docker#19662]
Description of problem:
I wrote a volume plug-in that provides volumes via FUSE-backed mount points. All operations work fine, however when I try to start a container on this, I get:

$ sudo docker run --volume-driver mydrv -v myvol:/mnt -ti busybox sh
Error response from daemon: operation not supported

I tried to debug this from below by mounting with -o debug so that I see all calls that FUSE gets, but the FUSE driver for the mount point does not yield a ENOSUPP.

`docker version`:
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64

`docker info`:
ontainers: 176
Images: 708
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-253:1-1075519194-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 37.66 GB
 Data Space Total: 107.4 GB
 Data Space Available: 69.71 GB
 Metadata Space Used: 46.62 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.101 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-327.4.4.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 8
Total Memory: 15.47 GiB
Name: readc
ID: HWVW:3DR5:A6E4:G23S:ERDG:PQ3B:7KNS:Q2ST:SSJG:AFIV:YCUH:MNOS
Username: fehu
Registry: https://index.docker.io/v1/

`uname -a`:
Linux redac 3.10.0-327.4.4.el7.x86_64 #1 SMP Tue Jan 5 16:07:00 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
Physical

How reproducible:

Steps to Reproduce:
1. mount FUSE file system at /run/docker/mymnt.

2. sudo docker run --volume-driver mydrv -v myvol:/mnt -ti busybox sh

3. Respond in plug-in to request  "POST /VolumeDriver.Mount HTTP/1.1" 200 - {'Name': 'myvol'}
Responding with {"Mountpoint": "/run/docker/mymnt", "Err": null}

Actual Results:
$ sudo docker run --volume-driver mydrv -v myvol:/mnt -ti busybox sh
Error response from daemon: operation not supported

Expected Results:
Container runs, mount point contains same data in /mnt just like in /run/docker/mymnt  on the host.

Additional info:

**Comment by thaJeztah** [comment]
could this be an SELinux issue?

**Comment by quofelix** [comment]
Yes, in the meantime I found out that removing --selinux-enabled from the daemon makes it work.
