### ISSUE TITLE
Support pattern in docker start command

### ISSUE THREAD

**Issue by NamPNQ** [docker/docker#19660]
I think `docker start something*` will be awesome feature.

**Comment by NamPNQ** [comment]
```
➜  ~  docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64
➜  ~  docker info
Containers: 3
Images: 61
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 67
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.0-25-generic
Operating System: Ubuntu 15.10
CPUs: 8
Total Memory: 7.684 GiB
Name: FS-CS-DKT04
ID: TRJF:M64E:XBVB:N46N:EVLV:QV4Y:2LRS:6KZS:YOME:PMXF:IYAA:KKJM
WARNING: No swap limit support
➜  ~  

```
I only suggest feature, it's not bug :|

**Comment by HackToday** [comment]
seems easy to programming with shell or other script langugage, like 

containerList=`docker ps | grep -i  smething* `
and then for ** loop; do docker start **; seems very common and easy use.


As docker start ** , still need fetch related containers.  It seems better did it in client side.(user side)


But let' s welcome other docker maintainers' input, I am open for that

**Comment by LK4D4** [comment]
I agree that it's easy to do with bash (I'm doing it all the time) and relatively hard to implement and maintain.
