### ISSUE TITLE
Option to configure gelf compression

### ISSUE THREAD

**Issue by hervenicol** [docker/docker#19665]
I think the Docker GELF log driver lacks a *log-opt* parameter to configure GELF compression.

Docker GELF logs are currently gziped.
Unfortunately, all GELF implementations don't support gzip logs.
For instance, heka GELF input only accepts plain-text gelf logs.

The go-gelf library which Docker relies on actually seems to support:
* CompressGzip
* CompressZlib
* CompressNone

**Comment by thaJeztah** [comment]
Looks like this is being worked on in https://github.com/docker/docker/pull/19831
