### ISSUE TITLE
[1.10-rc1] volume reference logic error

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#19672]
I just got the following error: `409 Client Error: Conflict ("Conflict: remove 9fb498dc7c51ea2a371008fb89e86e4b33f3462bc6d77740137a528b507a191c: volume is in use - [209001478e702f5d5bf59f9604d4584f604a4cda01f4416c81d53d9016034b22]")` but `209001478e702f5d5bf59f9604d4584f604a4cda01f4416c81d53d9016034b22` does not exist.  After daemon restart I was able to delete it.  All I did was launch a couple hundred nginx containers and then delete them.  There was not volumes-from or sharing of volumes.  I will try to reproduce.

**Comment by ibuildthecloud** [comment]
@cpuguy83 Okay, I reproduced it with a container that failed to delete.  So

```
$ docker rm -fv 7755
Failed to remove container (7755): Error response from daemon: Driver overlay failed to remove root filesystem 7755ee59efaaf4f0847e022ad59410da10af489d989b186680fb3950915e2733: readdirent: no such file or directory

$ docker rm -fv 7755
Error response from daemon: No such container: 7755
Error: failed to start containers: 7755
```

```
$ docker volume rm asdfasdf
Error response from daemon: Conflict: remove asdfadsf: volume is in use - [7755ee59efaaf4f0847e022ad59410da10af489d989b186680fb3950915e2733]
```

So apparently the container was failed to removed, but then Docker still removed it and the volume cleanup logic didn't get called?

**Comment by cpuguy83** [comment]
ah, I have an idea, thanks!

**Comment by cpuguy83** [comment]
#19676
