### ISSUE TITLE
[1.10-rc1] `docker ps` is not by default sorted by create time

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#19681]
I'm not sure if this was ever an official feature, but typically the recently created containers would be listed first.  That does not seem to be the case anymore in 1.10.

**Comment by ibuildthecloud** [comment]
Oh, I'm running #19595 on top of rc1 if that makes a difference.

**Comment by calavera** [comment]
> Oh, I'm running #19595 on top of rc1 if that makes a difference.

Yes, it's probably a bug in my PR. The RC1 is fine. The ordering is on purpose and my PR should keep it. I'm closing this issue, we can keep the conversation in the PR. Thanks for checking.
