### ISSUE TITLE
[1.10-rc1] docker inspect compatibility

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#19684]
In `1.9` there was backwards compatibility for `docker inspect` for old API versions, that doesn't seem to the case anymore.  If I call `/v1.18/containers/foo/json` I get the same output as `/v1.22`.  Specifically what broke for me is that Volumes and VolumesRW are missing in the insect.

**Comment by cpuguy83** [comment]
```
$ docker run -v /foo -d --name test busybox top
$ export DOCKER_API_VERSION=v1.18
$ docker inspect test
```
And I see:

```
        "Volumes": {
            "/foo": "/var/lib/docker/volumes/e5561b51364360269bf5e5e55a2d4f2c5a736c21d488c050ecd6c3d28f845c53/_data"
        },
        "VolumesRW": {
            "/foo": true
        },
```

**Comment by ibuildthecloud** [comment]
@cpuguy83 Very interesting.  I'm running a docker 1.6 client though.  I didn't change the env var.  I also tested with the API.

**Comment by ibuildthecloud** [comment]
@cpuguy83 Running the same thing as you I get a different output.  Very odd... let me see if I'm doing something stupid

**Comment by cpuguy83** [comment]
@ibuildthecloud When you say  "running the same thing", you mean by using the master client and setting the env var?

**Comment by ibuildthecloud** [comment]
Ah, sorry.  I've been testing with #19595 all day.  I think that may have broken this.  So I reverted back to rc1, not rc1 + #19595 and it works.  Now I'm just double checking that it is infact #19595 that caused it.

**Comment by calavera** [comment]
Yep, my PR broke this. Closing since it's not an issue (kinda) :grin:
