### ISSUE TITLE
[1.10-rc1] ubuntu 14.04 broken

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#19707]
@imikushin discovered this, but basically not a single container will launch.  They just die.

**Comment by thaJeztah** [comment]
This is a known issue in rc1; basically there's a bug in AppArmor on 14.04 and below, causing our profile to act up; you can unload the profile to fix this;

    /etc/init.d/apparmor stop
    apparmor_parser -R /etc/apparmor.d/docker-engine
    /etc/init.d/apparmor start

See https://github.com/docker/docker/issues/18948 for more information; we'll be removing the profile in 1.10.0-rc2, and see if we can get it fixed for 1.11

**Comment by thaJeztah** [comment]
Let me know if this solved it, then we can close

**Comment by ibuildthecloud** [comment]
@thaJeztah When is rc2?  Or is there a running branch for rc2 that I can test?

**Comment by thaJeztah** [comment]
Hopefully today; checking what issues are remaining when I'm in the office

---
