### ISSUE TITLE
Handcrafting Docker Image with Content Addressable Image Layers

### ISSUE THREAD

**Issue by thriqon** [docker/docker#19718]
I'm trying to create a Docker image compatible with the upcoming version 1.10 by supplying a handcrafted Tarball suitable for `docker load`. This Docker image should have a base image (i.e. I can't use `docker import`), and I generally try to minimize the amount of transferred data between me and the Docker daemon.

Until version 1.9 it is possible quite easily to do this, since Docker allows me to import a layer with a parent image *not* in the tarball, but already present on the computer. Thanks to #18727 it is possible to upload a partial image, but that only solves half the problem.

How can I get the layer checksums that I have to put in the configuration file (from the manifest of the base image)? Is this supported at all?

**Comment by tonistiigi** [comment]
@thriqon So you want to see the layer IDs for an image that Docker already uses? Currently this info is not part of `docker inspect` but adding it has been discussed before(for this use case and for visualizing layer sharing). Atm best possible ways are to look at config on disk, query from registry(2.3+) or `docker save`. But I think best way is to propose a way for adding this info to `docker inspect`.

**Comment by thriqon** [comment]
Yes, I'd like to be able to ask 'What is busybox composed of?', and then the Remote API could tell me: `sha:2830, sha:20282, sha:4828`. Is it possible to amend `docker inspect` for that?

**Comment by cpuguy83** [comment]
@thriqon It (kind of) does that already, really.
See the `Parent` field.

**Comment by tonistiigi** [comment]
@cpuguy83 `Parent` does not help you in this case any more. It's used only for build chain/cache.

**Comment by LK4D4** [comment]
I'm closing this issue in efforts to make issues list cleaner. Feel free to open new issue.
