### ISSUE TITLE
Proposal: Make stop grace period configurable per container

### ISSUE THREAD

**Issue by sabberworm** [docker/docker#19726]
I am concerned with some of my containers taking more than 10s to shutdown gracefully but I also understand that you don’t want breaking changes to the stop command and have thus refused #6446.

I take care to always use `docker stop -t 100` or `docker kill -s TERM` but shutting down my machine will just stop these containers with the default timeout.

I think it should be possible to configure the default grace period when starting the container (e.g. `docker run --stop-timeout=100`).

Going further I think this should also be configurable at the image level (i.e. the `Dockerfile`). Also, there should be an argument to the `docker daemon` to configure the default value (for containers that don’t have an explicit value configured).

**Comment by sabberworm** [comment]
@GordonTheTurtle this is a feature request

**Comment by dcharbonnier** [comment]
it's 2 features requests actually and especially for the daemon option the workaround are dirty

**Comment by thaJeztah** [comment]
This feature is currently being implemented in https://github.com/docker/docker/pull/22566, but unfortunately just missed the cut-off for 1.12, so will be in 1.13

**Comment by sabberworm** [comment]
Closing as duplicate of #22471.
