### ISSUE TITLE
Docker doesn't support dynamic cluster-store configuration; add error message

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#19732]
Docker 1.10 won't support dynamic cluster-store configuration, so we should show an error message if a user is trying to set it dynamically; relates to https://github.com/docker/docker/issues/19692

Note that doing this dynamically is planned for docker 1.11

**Comment by calavera** [comment]
The documentation is very clear about what's supported and what's not, we only need to fix it :smile:
