### ISSUE TITLE
Feature request: allow configuration of a running container's log driver/options 

### ISSUE THREAD

**Issue by donhcd** [docker/docker#19755]
It would be extremely useful to be able to edit the logging driver/options for a container without having to recreate it.

The expected behavior:
1. Run container `foo` with no log driver
2. Hit a daemon API endpoint with `{
"driver": "syslog",
"syslog-address": "udp://syslog.server:12345",
"tag": "{{.Name}}/{{.ID}}",
}`
3. New logs in `foo` will now go to my syslog server.

**Comment by thaJeztah** [comment]
Not entirely sure; this feels like something that needs to be set when creating a container. Is there a specific use-case where the log-driver/configuration cannot be set when creating the container, and must be set afterwards?

**Comment by HackToday** [comment]
Yes, not quite understand what's the typical user case for edit log-driver after contaienr create

**Comment by LK4D4** [comment]
Yeah, sounds quite hard to implement and use-cases is not clear. Closing for lack of interest.
