### ISSUE TITLE
new device node created on host does not get reflected in container when using --device flag.

### ISSUE THREAD

**Issue by rungatgenapsys** [docker/docker#19763]
Hi all,
I'm running a container with the following options:
docker run -d --device=/dev/bus/usb:/dev/bus/usb --device=/dev/ttyS0:/dev/ttyS0 instr_img

Inside the container I have a Python code which resets a USB device that in turn causes a device file in '/dev/bus/usb/002/005' on the host to be removed and a new file (/dev/bus/usb/002/006) created in its place.  The problem is that inside the container '/dev/bus/usb/002/005' still exists, and  '/dev/bus/usb/002/006' is no where to be found.  The directories '/dev/bus/usb/002' on the host and container are now out of sync. As a result, the code execution inside the container throws an exception because it can't talk to the USB device.  I confirmed by manually creating a new device file (mknod) in the container and saw that it did not get sync'ed to the host and vice versa.  Is this an unsupported feature or a bug in Docker?

>docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:48:04 UTC 2015
 OS/Arch:      linux/amd64

>Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:48:04 UTC 2015
 OS/Arch:      linux/amd64

>docker info
Containers: 66
Images: 313
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 445
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-47-generic
Operating System: Ubuntu 15.04
CPUs: 4
Total Memory: 7.69 GiB
Name:my-host-1
ID: VIT4:S2P3:Q4TY:A3I4:L4WH:HFWJ:I36U:PBTV:B3VW:NFXB:LDNM:KY7G
Username: myuser
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

>uname -a
Linux my-host-1 3.19.0-47-generic #53-Ubuntu SMP Mon Jan 18 14:02:48 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by rungatgenapsys** [comment]
Hi all,
Is there anyone who had run into this issue and has a cleaner workaround for it or can give me some pointers on how to proceed?  
My workaround is to issue a mknod command to create a new device file with the minor device number incremented by 1 (from the previous number) every time a device reset happens; however, this is not a clean hack since I need to put in some checks because this program is used in multiple environments outside and inside the Docker container.  I could very well be not using Docker properly for this use case since I'm very green (a noob) with Docker.
Some comments/insights from some experienced Docker users would really be appreciated.  It could be a deal breaker for me to dockerize this program if I can't find a clean workaround for this issue.

Thanks in advance for your comments!

**Comment by rungatgenapsys** [comment]
From all the researches online and some experimentation with using '--device', I've found that ephemeral (hot pluggable) devices are not supported by this option. It's a shame that the Docker documentation did not state this clearly, if at all. I only read one comment online from a user who mentioned it in passing. For those who want to use '--device' for these devices, don't; use the '--privileged' & '-v ' options instead. This will avoid you having to specify the exact device file name, e.g. /dev/bus/usb/002/088, instead you can specify just /dev/bus/usb. The '--device' option requires the actual device file name to work.

**Comment by ddavidebor** [comment]
The problem persists, and the solution also works, on: Docker version 17.03.0-ce, build 3a232c8

**Comment by thaJeztah** [comment]
would this help? Added in docker 17.04 https://github.com/docker/docker/pull/22563

**Comment by ddavidebor** [comment]
@thaJeztah It's not clear to me if it does or does not
