### ISSUE TITLE
Go Path broken in make for docker 1.9.1 stable

### ISSUE THREAD

**Issue by aerodame** [docker/docker#19787]
I used to be able to build docker on my targets using the normal steps:
```
$ git clone -b 'v1.9.1' --single-branch https://github.com/docker/docker.git
$ cd docker
$ curl -L https://github.com/umiddelb/armhf/raw/master/Dockerfile.armv7 > Dockerfile
$ sudo make build
$ sudo make binary
```
Now, I get a make error ...at STEP 41:

+ go get -v -d github.com/cpuguy83/go-md2man
package code.google.com/p/go.net/html: unable to detect version control system for code.google.com/ path

This kills the make.  Is this a known issue?

**Comment by cpuguy83** [comment]
Yes, this is because code.google.com is no more.

**Comment by aerodame** [comment]
I've been trying to wade through the Dockerfile to figure out how to repair this... but because the build is running inside containers it isn't clear... 

```
Step 41 : RUN set -x 	&& export GOPATH="$(mktemp -d)" 	&& git clone -b v1.0.3 https://github.com/cpuguy83/go-md2man.git "$GOPATH/src/github.com/cpuguy83/go-md2man" 	&& git clone -b v1.2 https://github.com/russross/blackfriday.git "$GOPATH/src/github.com/russross/blackfriday" 	&& go get -v -d github.com/cpuguy83/go-md2man 	&& go build -v -o /usr/local/bin/go-md2man github.com/cpuguy83/go-md2man 	&& rm -rf "$GOPATH"
 ---> Running in b3e0df2d6d3c
+ mktemp -d
+ export GOPATH=/tmp/tmp.yDjD8vLHJ2
+ git clone -b v1.0.3 https://github.com/cpuguy83/go-md2man.git /tmp/tmp.yDjD8vLHJ2/src/github.com/cpuguy83/go-md2man
Cloning into '/tmp/tmp.yDjD8vLHJ2/src/github.com/cpuguy83/go-md2man'...
Note: checking out 'e69ac41993d9dad8006559d4e28763d241ab53a6'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

+ git clone -b v1.2 https://github.com/russross/blackfriday.git /tmp/tmp.yDjD8vLHJ2/src/github.com/russross/blackfriday
Cloning into '/tmp/tmp.yDjD8vLHJ2/src/github.com/russross/blackfriday'...
Note: checking out '2e7d690972283d45aadc7a5ea304841e26529433'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

+ go get -v -d github.com/cpuguy83/go-md2man
package code.google.com/p/go.net/html: unable to detect version control system for code.google.com/ path
INFO[2857] The command [/bin/sh -c set -x 	&& export GOPATH="$(mktemp -d)" 	&& git clone -b v1.0.3 https://github.com/cpuguy83/go-md2man.git "$GOPATH/src/github.com/cpuguy83/go-md2man" 	&& git clone -b v1.2 https://github.com/russross/blackfriday.git "$GOPATH/src/github.com/russross/blackfriday" 	&& go get -v -d github.com/cpuguy83/go-md2man 	&& go build -v -o /usr/local/bin/go-md2man github.com/cpuguy83/go-md2man 	&& rm -rf "$GOPATH"] returned a non-zero code: 1 
make: *** [build] Error 1
```

**Comment by tianon** [comment]
Looks like blackfriday needs a bump to remove the code that still references `code.google.com`; politely poked upstream in https://github.com/russross/blackfriday/pull/117#issuecomment-175894405. :+1:

**Comment by tianon** [comment]
Wow, I'm special -- we just need to bump blackfriday to v1.4 (we're on v1.2 currently) and we should be good.

**Comment by tianon** [comment]
Oh, we already did, this is v1.9.1.  Yeah, that's not going to be buildable as-is anymore. :cry:

Not sure there's anything we can do about that.

**Comment by aerodame** [comment]
I've changed my local dockerfile to 1.4 and am able to get through the build now.   Also issued a pull request on Uli's github... But perhaps you are the source maintainer of his Dockerfile?

Sent from my iPhone

On Jan 27, 2016, at 2:44 PM, Tianon Gravi <notifications@github.com<mailto:notifications@github.com>> wrote:


Oh, we already did, this is v1.9.1. Yeah, that's not going to be buildable as-is anymore. [:cry:]

Not sure there's anything we can do about that.

-

**Comment by thaJeztah** [comment]
Alright, so looks like we won't be able to fix this, because it's in the 1.9 release? Should we close this issue then?

**Comment by cpuguy83** [comment]
Yes, we can't fix the old release.

Closing.

**Comment by aerodame** [comment]
Yes confirmed this is **good to go** as long as people know to use the 1.4 release of blackfriday so they don't trip on the code.google deprecation thing.  The Dockerfile refered to in the above 
```
curl -L https://github.com/umiddelb/armhf/raw/master/Dockerfile.armv7 > Dockerfile
```
has been fixed.
