### ISSUE TITLE
1.9.1 mounting over tmp does not work correctly

### ISSUE THREAD

**Issue by lovelycuppatea** [docker/docker#19786]
**docker version:**
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5/1.9.1
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5/1.9.1
 Built:        
 OS/Arch:      linux/amd64

**docker info:**
Containers: 3
Images: 96
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-202:1-263200-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.438 GB
 Data Space Total: 107.4 GB
 Data Space Available: 28.15 GB
 Metadata Space Used: 5.857 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.142 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-19.31.amzn1.x86_64
Operating System: Amazon Linux AMI 2015.09
CPUs: 2
Total Memory: 3.679 GiB

**environment details:**
aws ecs optimised amazon linux 2015.09f 64 bit
root volume: 30gb
ebs /dev/xvdb: 100gb - formatted using 
```
mkfs -t ext4 /dev/xvdb
```
docker container is ubuntu 14.04, updated as part of image creation

**steps to reproduce:**
mount an ebs volume as /tmp inside a docker container

**expected results**
/ would show as default container size of 10gb

**received result**
/ shows as 100gb
df -h output:
```
Filesystem                                                                                        Size  Used Avail Use% Mounted on
/dev/mapper/docker-202:1-263200-e439740dba834851711b11743f9e63368e53b683a734352612dd374d41646e69  100G  1.2G   99G   2% /
tmpfs                                                                                             1.9G     0  1.9G   0% /dev
tmpfs                                                                                             1.9G     0  1.9G   0% /sys/fs/cgroup
/dev/xvdb                                                                                          99G   60M   94G   1% /tmp
/dev/xvda1                                                                                         30G  3.2G   27G  11% /etc/hosts
shm                                                                                                64M     0   64M   0% /dev/shm

```

**Comment by lovelycuppatea** [comment]
updated original post, hope that helps.

**Comment by lovelycuppatea** [comment]
recent amazon ami update appears to of changed the issue, the root container now shows as 100gb, the root volume is 30gb, so would expect this or the default 10gb container size.

**Comment by cpuguy83** [comment]
The default container size is 100GB on Devicemapper in 1.9.. and maybe 1.8, can't remember.

**Comment by thaJeztah** [comment]
Yes, the default changed to 100GB in 1.8 (see https://github.com/docker/docker/pull/14709), but cause a lot of performance issues (see https://github.com/docker/docker/issues/18314), so it was changed back to 10GB by default, https://github.com/docker/docker/pull/19123, and an option was added to increase this on daemon restart.

**Comment by thaJeztah** [comment]
Note that, if you're running on Ubuntu, you may consider using `aufs` as a storage driver

**Comment by lovelycuppatea** [comment]
ok, was surprised to see this change, but glad it's reverted with option to increase in 1.1. will need to wait for that release to see it back to expected values without intervention. Will set to 10gb in my configs, closing.
