### ISSUE TITLE
mkimage script don't work

### ISSUE THREAD

**Issue by a93ushakov** [docker/docker#19807]
https://raw.githubusercontent.com/docker/docker/master/contrib/mkimage.sh

Host OS: debian x64, 8.3, debootstrap installed.

```sh
./mkimage.sh -t root/debian debootstrap --variant=minbase jessie
```
failed:
```sh
error: debootstrap does not exist or is not executable
```

**Comment by a93ushakov** [comment]
`docker` version has no value here.

This bug is concerned to script stored in >this< repo.

And this script just build image, without docker stuff.

**Comment by HackToday** [comment]
From the 
https://github.com/docker/docker/tree/master/contrib

it said

```
The `contrib` directory contains scripts, images, and other helpful things
which are not part of the core docker distribution. Please note that they
could be out of date, since they do not receive the same attention as the
rest of the repository.
```



So not sure who's is the maintainer for that ?

**Comment by thaJeztah** [comment]
I think @tianon is the most likely person for that :heart:

**Comment by tianon** [comment]
I used this script just the other day to update the top-level `debian` images (Jan 25); are you running it as root? (`sudo ./mkimage.sh ...`)

Debootstrap is typically installed in `/usr/sbin/debootstrap`, and `/usr/sbin` isn't in the user `PATH` by default (but running `debootstrap` requires root anyhow).

**Comment by a93ushakov** [comment]
```sh
PATH=$PATH:/usr/sbin ./mkimage.sh -t root/debian debootstrap --variant=minbase jessie```

also dont work.

**Comment by a93ushakov** [comment]
I had create simple image with `debootstrap` - it has 193 mb in size (as `docker images` said).
When I remove ~35 MB in /var/cache, image size don't changes (-1MB).

And, why official debian image has ~125MB, debootstraped verion - 193?

In `mkimage.sh` I found only removing `/dev` and `/proc` - but they don't size a lot.

 I couldn't understand how `mkimage.sh` works.

Maybe someone help me with these questions?
