### ISSUE TITLE
Feature request : Introduce new "ready" status

### ISSUE THREAD

**Issue by greg0ire** [docker/docker#19809]
At the moment, when I try to run my test suite, here is what I run : 

```
docker-compose up -d
docker exec --user=ci my_console_container_1 make test
```

docker-compose starts the containers, and starts the console container last. The entrypoint of this container creates the `ci` user, that should exist when running the tests with docker exec.

My problem is that there is a race condition between the entrypoint and docker exec. Doing this would solve my problem I guess : 

```
docker-compose up -d
sleep 1
docker exec --user=ci my_console_container_1 make test
```

and I have seen [other people](http://stackoverflow.com/questions/21183088/how-can-i-wait-for-a-docker-container-to-be-up-and-running) having similar problems with things that are slow to boot, and solving them with polling, most of the time, which is a bit ugly…

I think a new status could be introduced, named for instance "ready". A container should be able to indicate when it is ready to do its job somehow and its status would go from "up" to "ready". To indicate when it is ready, a new instruction could be added to the `Dockerfile` to specify a script able to detect "readyness". Container that expose ports could be automatically switched to ready when somethings listens on those ports.

What do you think?

**Comment by thaJeztah** [comment]
Note that in this example, you'd be able to use a *numeric* ID for the `ci` user to prevent `docker exec` from failing; e.g. `docker run --user=123:456`. You'd still have to wait for the entrypoint script to finish before actually running the tests

**Comment by greg0ire** [comment]
Yeah, so in fact there are two possible failure points : 

- when running `docker exec`
- when running `make test`

Thanks for the workaround, I'll probably give it a try…

**Comment by LK4D4** [comment]
I think it's mostly problem of running programs and not our runtime. I'm closing this as inactive. Feel free to open new issue if you have idea how to implement it properly.
