### ISSUE TITLE
1.10 Splunk Failed to initialize logging driver

### ISSUE THREAD

**Issue by kitsushadow** [docker/docker#19810]
I am experimenting with using the newly added Splunk Forwarder and getting this error in the console of the daemon:
ERRO[1065] Handler for POST /v1.22/containers/729d706d64ace003a581222745165840845bba4947478177fa32e4cc67c4f20c/start returned error: Failed to initialize logging driver: EOF

- I ran this command to start the daemon
./docker-1.10.0-rc1 daemon

- I ran this command to start my container
sudo ./docker-1.10.0-rc1 run --log-driver=splunk -it -p 80:8080 -p 9997:9997 --log-opt splunk-token=38AA8754-8B66-4CD2-AF47-6D14891366B0 --log-opt splunk-url=https://XX.XXX.XXX.XXX:9997 --log-opt splunk-insecureskipverify=true our_registry:5000/centos

The installed docker version is 1.10.0-dev and also returns the same issue when running the docker version of the above commands.

**Comment by thaJeztah** [comment]
@kitsushadow thanks for reporting, can you test if this is still reproducible on docker-1.10-rc2, just to be sure?

**Comment by kitsushadow** [comment]
Modified Splunk Server to enable the Token Key and the docker run command to use the 8088 port. It seems that I must also disable ssl on the host somehow.   

ERROR: docker: Error response from daemon: Failed to initialize logging driver: tls: oversized record received with length 20527.  

docker run -it -p 80:8080 -p 8088:8088 -p 9997:9997 --log-driver=splunk --log-opt splunk-token=38AA8754-8B66-4CD2-AF47-6D14891366B0 --log-opt splunk-url=https://10.103.128.135:8088 el2-dt-docker.aws.uscis.dhs.gov:5000/centos

**Comment by thaJeztah** [comment]
I see you're using `https://`as protocol?

**Comment by kitsushadow** [comment]
U sir, made my day.

**Comment by kitsushadow** [comment]
Still getting an issue with the forwarded messages showing up in splunk. It doesnt seem like splunk is getting messages. But docker has stopped complaining at least.

**Comment by kitsushadow** [comment]
Do you need to specify a log file for splunk forwarder to look at? or does it send everything ?

**Comment by thaJeztah** [comment]
@kitsushadow unfortunately, I haven't used splunk myself, so I'm not exactly sure, but possibly @outcoldman or @glennblock is able to provide some info

**Comment by outcoldman** [comment]
@kitsushadow have you tried to just post to the Event Collector using `curl` take a look on the examples http://blogs.splunk.com/2015/10/06/http-event-collector-your-direct-event-pipe-to-splunk-6-3/

Splunk Logging Driver does very simple check that it actually can use this URL. 

What kind of Splunk version are you using? Is it a cloud instance or on prem?

**Comment by glennblock** [comment]
If you are running in Splunk cloud you cannot disable SSL. If you have your own Splunk instance you can easily disable SSL from the token management screen by going to global settingd.

**Comment by glennblock** [comment]
@kitsushadow the log driver will capture whateve is sent to stdout. It does not pickup files on disk, for that you need the universal forwarder to be installed.

**Comment by glennblock** [comment]
@kitsushadow were you able to get your events in Splunk?

**Comment by kitsushadow** [comment]
We are using splunk server.
SSL is disabled.
The splunk server logs are showing that the message size is to large?

**Comment by kitsushadow** [comment]
@glennblock I can't use curl because of proxy settings

**Comment by outcoldman** [comment]
@kitsushadow what do you mean? If you cannot use curl, how logger driver suppose to work?

**Comment by kitsushadow** [comment]
Curl would require to setup proxy settings inside of the curl configuration. If the curl command is an absolute must I can figure out how to configure it work.

**Comment by kitsushadow** [comment]
got curl to start connecting and getting new errors now

curl -k --noproxy xx.xxx.xxx.xxx http://xx.xxx.xxx.xxx:8088/services/collector -H 'Authorization: Splunk 38AA8754-8B66-4CD2-AF47-6D14891366B0' -d '{"event":{"Hello from event collector"} {"event":{"message":"Hello from event collector"}}'

returns error message:
{"text":"Invalid data f

**Comment by outcoldman** [comment]
@kitsushadow you have invalid JSON in curl command `{"event":{"Hello from event collector"}` should be `{"event": "Hello from event collector"}`

> The splunk server logs are showing that the message size is to large?
Are you guessing or affirm that you have seen this error message? Could you post exact message?

**Comment by kitsushadow** [comment]
I've got the connection working and logs are coming in. I'm doing a confirmatarory test by removing the splunk universal forwarder embedded in the image. Getting this error now: 

docker: Error response from daemon: Container command could not be invoked..

**Comment by outcoldman** [comment]
> I've got the connection working and logs are coming in.

So it works now? Do you know what was the actual issue?

> docker: Error response from daemon: Container command could not be invoked..

Getting this error from where? Doing what exactly?

**Comment by kitsushadow** [comment]
Fixed! my script needed further modification

Thanks for the help everyone. 

Solved Hints:
make sure your using http vs https
double check the token key settings
if your behind a proxy using --noproxy xx.xxx.xxx.xxx will let you bypass it

Thanks for everyones assistance with this issue

**Comment by outcoldman** [comment]
:+1:

**Comment by thaJeztah** [comment]
Thanks @outcoldman @glennblock for helping out!

**Comment by glennblock** [comment]
Glad we could help. We'll look into some better error messaging to help
with this scenario.

**Comment by kitsushadow** [comment]
@glennblock Thank You, that would be helpful. For the future a list of all the --log-opt commands would be nice. I tried to look through --help in docker but no luck.

**Comment by glennblock** [comment]
@kitsushadow ok, got it. Thanks for your patience.

**Comment by outcoldman** [comment]
@kitsushadow it will be available here https://docs.docker.com/engine/reference/logging/overview/ when 1.10 will be released, right now you can search for docs on this page https://github.com/docker/docker/tree/release/v1.10/docs/reference/logging and specific for Splunk Logging Driver https://github.com/docker/docker/blob/release/v1.10/docs/reference/logging/splunk.md

**Comment by kitsushadow** [comment]
@outcoldman These documents are very helpful and exactly what I was looking for. Thanks for the support!

**Comment by glennblock** [comment]
Hey @thaJeztah can we have inline documentation on the driver in the docker cmd showing the list of params via `--help` or is that not standard?

**Comment by thaJeztah** [comment]
@glennblock we don't it much currently, but we recently added extra info for the filter options; https://github.com/docker/docker/pull/18387/files

However, I don't think we should include options for individual plugins, because that would probably be too long for the help output.

**Comment by glennblock** [comment]
What if you have a special help command that only applies to the driver?
Then you would just get the specific help?

**Comment by kitsushadow** [comment]
An inline --help of some sort would be very helpful.

**Comment by thaJeztah** [comment]
We can improve the man pages, and have more information there?
