### ISSUE TITLE
[v1.10-rc1] Docker daemon getting stuck/irresponsive under high load

### ISSUE THREAD

**Issue by beetree** [docker/docker#19821]
I can't recreate this issue, but it happens regularly in my cluster after I upgraded all nodes to 1.10.

When it happens, the daemon stops responding to any commands without anything in the daemon logs:

```
# time docker ps
^C
real    0m39.687s
user    0m0.180s
sys     0m0.020s
```

`journalctl -fu docker.service` not showing the `docker ps` request.

Looking at what other commands are stuck on the node shows mainly `docker build`, `docker import`, `docker start`, `docker inspect` and `docker create` with `docker create` being the most frequent command. Unclear which of these commands was the "cause" of the blocked daemon though.

What leads up to these crashes is a rapid creation of 50-100 images from Dockerfiles followed by a startup of one container for each image.

Some background information on the setup:

```
# uname -a
Linux m3555.contabo.host 3.19.8-031908-generic #201505110938 SMP Mon May 11 13:39:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

(after restart of daemon to get docker info and version)

```
# docker info
Containers: 66
 Running: 1
 Paused: 0
 Stopped: 65
Images: 38
Server Version: 1.10.0-rc1
Storage Driver: devicemapper
 Pool Name: docker-8:2-5767279-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 32.21 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 36.09 GB
 Data Space Total: 214.7 GB
 Data Space Available: 178.7 GB
 Metadata Space Used: 27.73 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.12 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.99 (2015-06-20)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.19.8-031908-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 125.8 GiB
Name: m3555.contabo.host
ID: MAU4:B6XM:EKHH:UI56:ZQBR:72Q3:EAY5:ZS7S:JEOG:IFEK:YT6G:YFRR
WARNING: No swap limit support

# docker version
Client:
 Version:      1.10.0-rc1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   677c593
 Built:        Fri Jan 15 18:50:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0-rc1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   677c593
 Built:        Fri Jan 15 18:50:07 2016
 OS/Arch:      linux/amd64
```

Please note that the number of containers running in the `docker info` is a reflection of me needing to restart the daemon to get the `docker info`, as the daemon is stuck.

Thanks for looking into this. Without a solution I'll need to revert back to 1.9.1.

/beetree

UPDATE:
On a different Node the running processes (that were stuck) were `docker pull`, `docker import`, `docker build` and `docker create`.

UPDATE2:
Hypothesizing on what in the 1.10 update that could have lead to this the new image layering system would be an idea. In my cluster I'm using fairly heavy docker imports into ~2GB images. When starting up a new Node I start 50-150 containers in a 20 minute time frame most of which start from a docker import. Is the new image layering system more resource intensive? I do see the nodes hitting very high core loads, though not sure what it is driven by (cpu, disk io, or other).

**Comment by thaJeztah** [comment]
Could you try if you're still able to reproduce this on 1.10-rc2 ?

**Comment by tiborvass** [comment]
@beetree can you give us the stacktrace after sending a SIGUSR1 to the daemon?

**Comment by tiborvass** [comment]
Assuming it is running in debug mode

**Comment by beetree** [comment]
@thaJeztah 
I can update a few nodes to 1.10-rc2. Is that the version on test.docker.com?

@tiborvass 
Not sure if it's running debug mode. How do I know?

**Comment by thaJeztah** [comment]
@beetree yes, rc2 was released yesterday

**Comment by tiborvass** [comment]
@beetree `docker info` should show debug mode on. You can add it with `--debug` when starting the daemon.

**Comment by ericxnelson** [comment]
I think we're running into this bug as well. I just bumped our mesos cluster from dev -> rc2 in hopes that this solves things for us.

**Comment by tiborvass** [comment]
@ericxnelson if you could give us more information by sending SIGUSR1 to the daemon and pasting the logs, that'd be really helpful for debugging.

**Comment by beetree** [comment]
I ran a test on rc2 under a fairly high load without any daemon crash. I don't think that makes it conclusive. I'll continue updating nodes to rc2, and if in a few days I haven't seen any more of these crashes I think we can call it fixed.

**Comment by thaJeztah** [comment]
Thanks @beetree, keep us posted!

**Comment by beetree** [comment]
I've had no more of these crashes. Going to close this.

**Comment by thaJeztah** [comment]
Thanks so much for testing, @beetree!
