### ISSUE TITLE
Docker Client with several DOCKER_HOST

### ISSUE THREAD

**Issue by Filirom1** [docker/docker#19828]
Hi,

I setup an HA Swarm Cluster, and unfortunatley the Docker Client only takes one DOCKER_HOST.
It would be great to be able to configure several DOCKER_HOST with retries machanism on the Docker client.

Cheers
Romain

**Comment by cyphar** [comment]
In general, the way this is managed is with [`docker-machine`](https://github.com/docker/machine).

**Comment by Filirom1** [comment]
So even if I don't use Docker Machine to setup my cluster, your recommendation is to use docker-machine to connect to the available swarm manager. That it ?

**Comment by cyphar** [comment]
Well, I'm wondering about how we would implement it from the Docker side, and there's a couple of thorny issues that I'm not sure we should be solving from the Docker side. The first being in which order should they be polled, what if one is unavailable, what if you specify the same daemon through multiple endpoints, what if you have conflicts in information, what should `docker info` and `docker version` do, how about multiple API versions, when you do `docker pull` and `docker push` which docker daemon should it go through (especially if the same image tag but with different IDs are present on the daemons)?

That's just a couple of the things I can see being issues. And `docker-machine` was made expressly to solve the "virtual Docker daemon" problem, so I'd think that `docker-machine` might be able to help you. I wasn't sure if you knew about it (and I'm not sure if it'll fit your usecase).

**Comment by Filirom1** [comment]
Thank you, I will try with docker-machine
