### ISSUE TITLE
Docker container seemingly hung when running Java

### ISSUE THREAD

**Issue by Vaudesir** [docker/docker#19843]
Docker 1.9.1
Windows 10

When running the java executable on a centos:6.6 based container, the process seems to be hung and I can see a java defunct process in the default VM when running ps -ef.
This could be related to https://github.com/docker/docker/issues/18180

How to replicate:
On Windows 10, with Docker 1.9.1
Run: 
docker run -it centos:6.6 /bin/bash

Then from the container shell, Install java:
yum install java7

then:
cd /usr/bin
then
./java

You get a message showing the usage but you never get the prompt back.
If you open VirtualBox, and "show" the VM called "default" and type ps -ef | grep java, you see that there is one defunct java process.

Only option to get out of the situation seems to be to shutdown the vm and close the docker shell.

This is a simplified instance of my real problem: My InstallAnywhere excutable hangs when trying to run it in the container. I traced the issue to the point where the installer tries to start the java vm.

$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

docker info:
 docker info
Containers: 6
Images: 5
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 17
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: KXV4:IACH:M4VB:GQ3G:QLBY:3KER:OLSF:GCGK:72S6:SWSH:4LMF:FZ3O
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 19
 System Time: 2016-01-30T00:06:42.645732684Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox

**Comment by cpuguy83** [comment]
Yep this looks like a dup of the mentioned issue.

Thanks!
