### ISSUE TITLE
engine ignores host trusted CAs when /etc/docker/certs.d is present

### ISSUE THREAD

**Issue by nicolaka** [docker/docker#19845]
Description of problem:

When TLS certs are places in `/etc/docker/certs.d`, engine uses the certs in that dir to establish HTTPS connection with Hub/registry. But if any subsequent requests to get image blobs involve establishing other HTTPS sessions with storage backends (e.g S3), engine only looks in `/etc/docker/certs.d` to establish trust chain with the storage backend and fails to find any trusted cert in that dir so pulls would fails. 

`docker version`: 
$docker version
Client:
 Version:      1.10.0-rc2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c1cdc6e
 Built:        Wed Jan 27 22:31:21 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0-rc2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c1cdc6e
 Built:        Wed Jan 27 22:31:21 2016
 OS/Arch:      linux/amd64

`docker info`: 
$docker info
Containers: 11
 Running: 0
 Paused: 0
 Stopped: 11
Images: 21
Server Version: 1.10.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 64
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.19.0-26-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 993.2 MiB
Name: dev1
ID: OXRP:6VZL:PLXK:Y7SU:EFEI:2KF5:PILP:UKXH:35MK:CUC6:VOP4:G75Q
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 24
 System Time: 2016-01-29T16:52:50.051312707-08:00
 EventsListeners: 0
 Init SHA1: 600495178ec5ae55043800430456b25ab9fba9bb
 Init Path: /usr/lib/docker/dockerinit
 Docker Root Dir: /var/lib/docker
Username: nicolaka
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

`uname -a`:

$ uname -a
Linux dev1 3.19.0-26-generic #28~14.04.1-Ubuntu SMP Wed Aug 12 14:09:17 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):

vagrant with virtualbox

How reproducible:

everytime

Steps to Reproduce:
1. place cert in `/etc/docker/certs.d`
2. docker pull from a registry that is doing redirects to S3

**Comment by phemmer** [comment]
Thanks for the report, but this looks like a dup of #12756

**Comment by thaJeztah** [comment]
Looks the same indeed. I'll close this one; thanks @phemmer
