### ISSUE TITLE
Need a non-destructive way to upgrade from 1.10.0-rc1 to 1.10.0-rc2

### ISSUE THREAD

**Issue by jianghaitao** [docker/docker#19842]
Maybe there is already a way to upgrade the Docker version in a non-destructive manner. I used following command to upgrade 1.10.0-rc1 to 1.10.0-rc2

`curl -fsSL https://test.docker.com/ | sh`

It gave me the opportunity to choose whether to overwrite /etc/default/docker or not, but it silicently wipe the /var/run/docker/netns directory clean. Now, I can not start any of my previous containers. 

However,

`docker inspect network`
`docker network ls`

still show the information of my previously created bridge / overlay networks. But they are not usable, i.e. if I create a container on the overlay network, it will die immediately.
`
docker run --net=overlay-net -itd --name=container-1 busybox
`
I can see following in the docker.log

`
WARN[4303] Failed to retrieve interface link for interface removal on endpoint leave: Link not found 
`

**Comment by thaJeztah** [comment]
ping @jfrazelle any ideas here? I'll assign this to you :heart:

**Comment by HackToday** [comment]
Oh, I never thought we could support RC upgrades , if it did support, it would be good news.

**Comment by jfrazelle** [comment]
Why we don't support this

On Saturday, January 30, 2016, Kai Qiang Wu <notifications@github.com>
wrote:

> Oh, I never thought we could support RC upgrades , if it did support, it
> would be good news.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/19842#issuecomment-177167206>.
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jfrazelle** [comment]
Upgrading between non rc versions we support but not this, I hope you can understand we have better things to do with our time

**Comment by HackToday** [comment]
@jfrazelle  not quite get your comments above, do you mean we not support upgrades between rc versions ?  Or Support  ?

**Comment by jfrazelle** [comment]
We don't support upgrading between RC versions it's not a good use of time

On Saturday, January 30, 2016, Kai Qiang Wu <notifications@github.com>
wrote:

> @jfrazelle <https://github.com/jfrazelle> not quite get your comments
> above, do you mean we not support upgrades between rc versions ? Or Support
> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/19842#issuecomment-177215626>.
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by mavenugo** [comment]
The WARN here is a bug in overlay driver that is not related to the upgrade process.

**Comment by HackToday** [comment]
sure @jfrazelle  yes, I did think RC upgrades not supported. Just confirm that.  Thanks

**Comment by jianghaitao** [comment]
Not supporting non-destructive upgrade between RC at this time is understandable as long as it is clearly stated in the release notes or warning during deployment.

Also , it would be nice if everything can be cleaned up nicely during the deployment. Right now, as reported, networks etc. are still there, just one can not use them. This inevitably caused confusion. I would be happy either way (upgradable or reset / start from clean state).
