### ISSUE TITLE
Unable to find image 'hello-world:latest' locally

### ISSUE THREAD

**Issue by ayogi** [docker/docker#19859]
Description of problem:

I have installed docker in my machine following the official [installation steps](https://docs.docker.com/engine/installation/ubuntulinux/) for ubuntu. At the verification steps it fails. 

When I run the command: `docker run hello-world` it throws following error message:

> Unable to find image 'hello-world:latest' locally
> Pulling repository docker.io/library/hello-world
> Error while pulling image: Get https://index.docker.io/v1/repositories/library/hello-world/images: dial tcp 52.0.10.162:443: connection refused
> 

My machine is behind the corporate proxy. So I tried to download the image manually using `wget` command, as follows:

`wget https://index.docker.io/v1/repositories/library/hello-world/images`

But I still don't know at which location I should place this image. Can we place this images file manually at the docker configuration folder ?

Below are the docker details for my machine.

`docker version`:

> Client:
>  Version:      1.9.1
>  API version:  1.21
>  Go version:   go1.4.2
>  Git commit:   a34a1d5
>  Built:        Fri Nov 20 13:08:59 UTC 2015
>  OS/Arch:      linux/amd64
> 
> Server:
>  Version:      1.9.1
>  API version:  1.21
>  Go version:   go1.4.2
>  Git commit:   a34a1d5
>  Built:        Fri Nov 20 13:08:59 UTC 2015
>  OS/Arch:      linux/amd64

`docker info`:

> Containers: 0
> Images: 0
> Server Version: 1.9.1
> Storage Driver: aufs
>  Root Dir: /var/lib/docker/aufs
>  Backing Filesystem: extfs
>  Dirs: 0
>  Dirperm1 Supported: false
> Execution Driver: native-0.2
> Logging Driver: json-file
> Kernel Version: 3.13.0-69-generic
> Operating System: Ubuntu precise (12.04.5 LTS)
> CPUs: 8
> Total Memory: 15.5 GiB
> Name: ubuntu
> ID: 63UC:H5NE:Y4QE:LMFN:N2YD:EMQL:TLVE:7OSQ:WGUG:QQQ4:7NQH:LO6E
> WARNING: No swap limit support

`uname -a`:

> Linux ubuntu 3.13.0-69-generic #112~precise1-Ubuntu SMP Wed Nov 11 10:57:32 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details:
I am using physical desktop, which is behind the corporate proxy.
OS: Ubuntu-12.04.5 LTS

Problem can be reproduced by following the installation instructions.

If someone knows what is the problem please help ?

**Comment by HackToday** [comment]
try this 
https://github.com/docker/docker/blob/master/docs/reference/commandline/import.md

Could it help ?

If you behind firewall, I think you need configure proxy to make it work

**Comment by ayogi** [comment]
Thanks @HackToday. I specified proxy settings in `/etc/default/docker` file, and restarted the service. Then I am able to run `hello-world` image and do further tasks.

**Comment by juan-jimenez** [comment]
Could someone please tell us what is the name of the configuration file where a proxy can be set? The directory structure is different on Windows but I hope the configuration file will be the same.  Thanks.

**Comment by ayogi** [comment]
For linux it is "/etc/default/docker" file.

**Comment by friism** [comment]
I think you can specify this when creating the machine, see https://github.com/docker/toolbox/issues/102#issuecomment-131715272:

```
docker-machine create -d virtualbox \
    --engine-env HTTP_PROXY=http://example.com:8080 \
    --engine-env HTTPS_PROXY=https://example.com:8080 \
    --engine-env NO_PROXY=example2.com \
    default
```

**Comment by prayagupd** [comment]
yep, if you cat `/etc/default/docker`, you see

```
# Docker Upstart and SysVinit configuration file

#
# THIS FILE DOES NOT APPLY TO SYSTEMD
#
#   Please see the documentation for "systemd drop-ins":
#   https://docs.docker.com/engine/articles/systemd/
#

# Customize location of Docker binary (especially for development testing).
#DOCKERD="/usr/local/bin/dockerd"

# Use DOCKER_OPTS to modify the daemon startup options.
#DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4"

# If you need Docker to use an HTTP proxy, it can also be specified here.
export http_proxy="http://127.0.0.1:3128/"

# This is also a handy place to tweak where Docker's temporary files go.
#export TMPDIR="/mnt/bigdrive/docker-tmp"

```

**Comment by busche** [comment]
For the next ones having problems with an HTTP_PROXY on a systemd host, simply follow these instructions:

https://docs.docker.com/engine/admin/systemd/#/http-proxy

works!

**Comment by srthorat** [comment]
How to get this working , when user is behind proxy and don't know his proxy setting?

**Comment by RupenAnjaria** [comment]
How to set this for Windows 7?

**Comment by thaJeztah** [comment]
@RupenAnjaria On Windows 7 you're probably running docker toolbox, see here for the setting proxies; https://docs.docker.com/toolbox/faqs/troubleshoot/#/http-proxies-and-connectivity-errors

Please keep in mind that the GitHub issue tracker is for reporting bugs and feature requests, but not intended as a general suppprt forum; for questions about _running_ Docker, please use either;

- https://forums.docker.com
- the Docker Community Slack channel https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/
- StackOverflow

**Comment by thaJeztah** [comment]
I'm locking this issue for discussion; see my comment above for where to get help on running docker
