### ISSUE TITLE
what does --memory-reservation do in practice?

### ISSUE THREAD

**Issue by anentropic** [docker/docker#19853]
Explain like I'm five...

> Under this configuration, when the container consumes memory more than 200M and less than 500M, the next system memory reclaim attempts to shrink container memory below 200M.

Let's say I have a container running Solr, and `docker run -m 1G --memory-reservation 768M solr`

What effect does it have on the Solr process inside the container when it starts using 800M memory? Nothing?

Is it only if/when memory usage subsequently drops below 768M... this flag allows docker to reclaim the memory from the `solr` container... otherwise the container would always consume whatever the high-water memory usage was?

How does this relate to swarm scheduling?  If swarm always allocates 1G for the container because of `-m` then is `--memory-reservation` not useful in this context?

**Comment by anentropic** [comment]
@GordonTheTurtle this is just a question not a bug

is it ok to post these here?

**Comment by HackToday** [comment]
Hi @anentropic  this is not right place to ask questions,

Could you use one of the below;

1) the forums: https://forums.docker.com/
2) the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user
3) the #docker IRC channel on Freenode.
4) StackOverflow

**Comment by anentropic** [comment]
ok sorry, no prob

**Comment by phemmer** [comment]
@anentropic if you think the documentation is inadequate, this is however the right place.

**Comment by anentropic** [comment]
@phemmer I guess it's adequate if you know enough linux internals to guess what those flags are doing under the covers and what the implications are

for someone like me who's more dev than ops it didn't really explain things well enough to know how to use them

I have asked here http://serverfault.com/questions/753010/what-does-memory-reservation-flag-do-in-practice
