### ISSUE TITLE
when using docker + linking + golang it doesn't read /etc/hosts properly

### ISSUE THREAD

**Issue by blacktop** [docker/docker#19866]
I have a golang app running in docker with an ubuntu (also tried alpine) image.  The `/etc/hosts` gets changed to (when I link with `--link rethink:rethinkdb`:
```bash
172.17.0.3	2ed4023bd0c4
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.2	rethinkdb aeb6c5b5836b rethink
```
which gorethink can't resolve, it can however resolve `localhost` but when I move the line up by the localhost line like so:
```bash
172.17.0.3	2ed4023bd0c4
127.0.0.1	localhost
172.17.0.2	rethinkdb aeb6c5b5836b rethink
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
```
it does work.

I also tried to force Go to use /etc/hosts first instead of DNS and it still failed using the flag `GODEBUG=netdns=cgo+1` this had no affect because of the way golang is reading the /etc/hosts file it gives up once it gets to the IPv6 stuff I assume?

Thank you for your help.

@dancannon

**Comment by thaJeztah** [comment]
docker 1.10 now uses DNS-based resolution for containers when using a custom network (release candidates are now available here; https://github.com/docker/docker/releases), including an option to add container-scoped, and network-scoped aliases, e.g.;

```
docker network create foo
docker run -d --net=foo --name=myfoo nginx
docker run -it --net=foo --link myfoo:hello ubuntu
```

I'm not sure we should fix this, given that the "old" links are basically replaced with DNS based discovery, and this sounds like a limitation of the software used, not docker

**Comment by blacktop** [comment]
thank you, I look forward to trying the new DNS way of linking containers.

**Comment by wildattire** [comment]
Was this bug ever resolved? We ran into this bug today and really need a solution.

**Comment by wildattire** [comment]
This bug is not fixed by @thaJeztah's suggestion to use network aliases. Resolution of aliases continues to fail.

**Comment by thaJeztah** [comment]
@wildattire do you have the steps to reproduce? are you using a custom network, or the "default" network?

**Comment by wildattire** [comment]
@thaJeztah Yes. I have tried both. You can reproduce by:
1. Creating a new network "foobar"
2. Starting a redis( or really, any network service ) container with its port exposed in the Dockerfile, with --name redis and --net foobar
3. Write a small golang app that connects to the hostname "redis" or "redis.foobar" (both will fail), wrap it in a docker container, and run it, also with --net foobar

Sorry, I don't have a simplified version with container images ready to go since we ran into this with our regular applications, but I could come up with something tomorrow.

**Comment by daxorid** [comment]
@thaJeztah I have a reproducible test case for you.

https://github.com/daxorid/dockerbug

1. Clone this repo
2. ./build.sh the server, then ./run.sh it
3. ./build.sh the client, then ./run.sh it

You should see the error in resolution as the client panics.

**Comment by thaJeztah** [comment]
@daxorid I just tried it on Docker 1.11.0-rc3 I had to pass an argument to the client `./run.sh`, otherwise `$1` would be empty, so I ran:

```
./run.sh buggy_server
2016/04/06 00:23:03 attempting to connect to hostname [buggy_server]
2016/04/06 00:23:03 lol, looks like that actually worked! bug reporter is a lying bastard!
```

I can try reproducing in 1.10.3, but at least it looks like it's fixed in 1.11.0-rc3

**Comment by thaJeztah** [comment]
And thanks for the repro case, much appreciated

**Comment by thaJeztah** [comment]
I'm not able to reproduce on 1.10.3 as well, using the same steps

**Comment by daxorid** [comment]
@thaJeztah Very strange. Current version here is 1.9.1, build ee06d03/1.9.1, which is the stock version in Fedora 23. I will try to reproduce this in a more recent version.

**Comment by thaJeztah** [comment]
@daxorid yes, that's expected; see my comment, and the reason why this issue was closed; https://github.com/docker/docker/issues/19866#issuecomment-177631429

**Comment by thaJeztah** [comment]
@daxorid also, looks like you're running a build of Docker that's modified by Red Hat; some of those changes result in Docker working different from the official version. If you want to install the official builds, you can install from our apt/yum repository, following the instructions in our documentation https://docs.docker.com/engine/installation/linux/fedora/. That should also give you an up-to-date version (1.10.3 currently, but 1.11 soon)

**Comment by daxorid** [comment]
@thaJeztah sorry about that, my reading comprehension is apparently terrible. This does, indeed, work with 1.10. Thanks for the trouble.

**Comment by thaJeztah** [comment]
No problem, thanks for confirming it's indeed fixed!

**Comment by alexforever86** [comment]
I'm still getting this issue. 

Steps to reproduce:
1. Create a docker-compose file as follows:
a. Create a network
```
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
```
b. Create a web server with go
```
  test_server:
    build: ./test_server
    ports:
      - "7000:7000"
    links:
      - target_nginx
    networks:
      static-network:
        ipv4_address: 172.20.128.10
    extra_hosts:
     - "source.com:172.20.128.20"
```
c. Create a nginx server with IP address `172.20.128.20`
```
  target_nginx:
    image: nginx
    volumes:
      - ./target_nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    links:
      - dummy_web_server
    networks:
      static-network:
        ipv4_address: 172.20.128.20
```
2. From Web server, try `http.Get("http://source.com")`

Results received:
Http request is sent to source.com, not to the Nginx container.

Results expected:
source.com should be resolved to 172.20.128.20, ip address of Nginx container.

I tried curl to source.com and it got actually resolved in the correct way, confirming the issue with Go.

**Comment by thaJeztah** [comment]
@alexforever86 all that `extra_hosts` does, is add an entry to `/etc/hosts` inside the container; you can verify if the entry is set by `cat`-ing that file. If the Go web server does not resolve the IP-address, that's likely due to the way the service is created; also see https://golang.org/pkg/net/#hdr-Name_Resolution

**Comment by alexforever86** [comment]
@thaJeztah I verified that /etc/hosts have what we added to `extra_hosts` option. Also, I successfully sent `curl` requests to make sure that it doesn't work happen with Go app only.
