### ISSUE TITLE
docker run with multiple networks

### ISSUE THREAD

**Issue by irsl** [docker/docker#19863]
Please improve the docker run syntax so running a container connected to multiple networks would be possible from the beginnings (no need to run docker network connect x y seperately).

**Comment by mavenugo** [comment]
Pls refer to https://github.com/docker/docker/pull/17796#issuecomment-162612624 and other comments in that issue & https://github.com/docker/docker/pull/18906 which resolves this use-case. Please let us know if https://github.com/docker/docker/pull/18906 satisfies your use-case of running a container in multiple networks before the container `starts`

**Comment by irsl** [comment]
Sorry for the dupe, I will join the referenced threads.
