### ISSUE TITLE
We are handling mqueue incorrectly in docker.

### ISSUE THREAD

**Issue by rhatdan** [docker/docker#19871]
We are leaking the same mqueue to all docker containers. This leads to potential information leak and can cause breakage.

The problem is that we treat mqueue the same as tmpfs, but unlike tmpfs each mount of mqueue is not unigue in the same mnt namespace.    You can see this by doing 

```
#mount -t mqueue none /mnt
#touch /mnt/dan
# ls -lZ /dev/mqueue/
total 0
-rw-r--r--. 1 root root system_u:object_r:tmpfs_t:s0 80 Feb  1 05:07 dan
```

The code for sharing of tmpfs and mqueue in current docker mounts these file systems before the mount namespace is changed. 

We should not be mounting /dev/mqueue by default

Not sure there is a way to share /dev/mqueue between two containers.

**Comment by rhatdan** [comment]
@mrunalp PTAL

**Comment by rhatdan** [comment]
We saw this issue because of SELInux labeling.

https://bugzilla.redhat.com/show_bug.cgi?id=1301693

SELinux will actually block containers from using /dev/mqueue inside of the container, for all but the last container created.

**Comment by calavera** [comment]
Fixed with https://github.com/docker/docker/pull/19876
