### ISSUE TITLE
`docker rmi` tries to delete image with empty string (that does not exist)

### ISSUE THREAD

**Issue by lironess** [docker/docker#19878]
When I'm trying to delete **any** of my images, docker does that thing :

    $ docker rmi 5aeb37c1fd00
    Error response from daemon: image ID '' is invalid
    Error: failed to remove images: [5aeb37c1fd00]

as you can see, it is complaining about an image with empty string name that it cannot delete.
If it matters, my docker is installed on vagrant machine with Red Hat 64-bit OS.
That error came by from yesterday. 2-3 days ago everything worked perfectly.

more additional information:

    $ docker version
    Client version: 1.7.1
    Client API version: 1.19
    Go version (client): go1.4.2
    Git commit (client): 786b29d
    OS/Arch (client): linux/amd64
    Server version: 1.7.1
    Server API version: 1.19
    Go version (server): go1.4.2
    Git commit (server): 786b29d
    OS/Arch (server): linux/amd64

Thanks.

**Comment by HackToday** [comment]
it is quite old docker version.

Could you restart docker ? and check if it works. another maybe check docekr 1.7.0 code and enable docker -D debug level and find more info

**Comment by lironess** [comment]
restarted docker, still not working well

**Comment by thaJeztah** [comment]
What version of Red Hat are you using? Can you add the output of `uname -a` and `docker info`? Are you running out of disk space?

Also, are you able to reproduce this on the current version of docker (1.9.1)?

Given that you mention this worked correctly before, I wonder if this is a bug in docker, or something on your system

**Comment by lironess** [comment]
CentOS Linux release 7.1.1503 (Core)

Linux localhost.localdomain 3.10.0-229.7.2.el7.x86_64 #1 SMP Tue Jun 23 22:06:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

    $ docker info
    Containers: 106
    Images: 714
    Storage Driver: devicemapper
     Pool Name: docker-253:2-67108992-pool
     Pool Blocksize: 65.54 kB
     Backing Filesystem: xfs
     Data file: /dev/loop0
     Metadata file: /dev/loop1
     Data Space Used: 32.45 GB
     Data Space Total: 107.4 GB
     Data Space Available: 18.92 GB
     Metadata Space Used: 55.72 MB
     Metadata Space Total: 2.147 GB
     Metadata Space Available: 2.092 GB
     Udev Sync Supported: true
     Deferred Removal Enabled: false
     Data loop file: /persistence01/devicemapper/devicemapper/data
     Metadata loop file: /persistence01/devicemapper/devicemapper/metadata
     Library Version: 1.02.93-RHEL7 (2015-01-28)
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 3.10.0-229.7.2.el7.x86_64
    Operating System: CentOS Linux 7 (Core)
    CPUs: 6
    Total Memory: 9.215 GiB
    Name: localhost.localdomain

**Comment by lironess** [comment]
just close it. I just deleted all the local docker data storage (containers directory, etc.) and downloaded the images again.

**Comment by thaJeztah** [comment]
I'll close; feel free to comment if you run into this again

**Comment by dpkprasanna** [comment]
I am facing the same issue... 

Error response from daemon: image ID '' is invalid
FATA[0002] Error: failed to remove one or more images

**Comment by sad2project** [comment]
I'm getting the same issue, too.

Idk the specs for the machine; I don't think I have the rights for that

Docker version : 1.8.2
Package version: docker-1.8.2-7.e17.centos.x86_64
Git commit: bb472f0/1.8.2

**Comment by thaJeztah** [comment]
@dpkprasanna docker 1.6.2 is really old now, so this issue may already be resolved (current version is 1.10.2)

@sad2project looks like you have installed a version of Docker that's maintained by Red Hat (see the commit https://github.com/docker/docker/commit/bb472f05c975b343fb13e55325a985f4ac1d0ca2), issues with those versions should be reported in the Red Hat / CentOS issue tracker first, because it's possible it's specific to that version (there's various patches applied to those versions)
