### ISSUE TITLE
[1.10-rc2] docker client awaits user input to detach from interactive container

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#19888]
Ran into this on an OS X client;

```
docker run -it --rm ubuntu
root@a68c30286056:/# exit
exit <---hangs here, until I press "enter"
```

Looks to be a client-side issue, because connecting the same client to a remote 1.9.1 daemon has the same issue

**Comment by tiborvass** [comment]
Also, -rc1 does not have this issue, it's strictly -rc2

**Comment by crosbymichael** [comment]
Master works fine

**Comment by LK4D4** [comment]
I confirm that master works.
