### ISSUE TITLE
Proposal: docker/docker.go should be refactored

### ISSUE THREAD

**Issue by fangyuan930917** [docker/docker#19908]
the code snippet:
`
              help := "\nCommands:\n"

		for _, cmd := range dockerCommands {
			help += fmt.Sprintf("    %-10.10s%s\n", cmd.Name, cmd.Description)
		}

		help += "\nRun 'docker COMMAND --help' for more information on a command."
		fmt.Fprintf(stdout, "%s\n", help)
`

Why use _help_ to do string concatenation, but not fmt.Fprintf ?
I don't know how Golang implements string concat, but in C++ and Java, it is function invoke, and usually needs buffer allocation. But stdout has buffer already.

Maybe useing help does make clear that it's HELP info... but on the other hand, I rarely saw string concatenation in the whole project, so for consistency of coding style, suggest refactor.

**Comment by thaJeztah** [comment]
@fangyuan930917 I don't think this is a top-priority issue, but feel free to open a pull request if you think the code should be updated :+1: 

Closing, because this is not really a bug or a feature-request
