### ISSUE TITLE
seccomp support in v1.10.0-rc2 vs master

### ISSUE THREAD

**Issue by Djelibeybi** [docker/docker#19905]
Hey, I'm hoping someone can help me determine the reason why trying to build `v1.10.0-rc2` with seccomp support fails on OL7, but it works fine with `master`

If I checkout `v1.10.0-rc2` and add `libseccomp-devel` to the packages and `seccomp` to the `DOCKER_BUILDTAGS`, I get the following error:

```
---> Making bundle: dynbinary (in bundles/1.10.0-rc2/dynbinary)
# _/root/rpmbuild/BUILD/docker-engine/dockerinit
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: cannot find -lseccomp
/usr/bin/ld: cannot find -lseccomp
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/libpthread.a(libpthread.o): In function `sem_open':
(.text+0x682b): warning: the use of `mktemp' is dangerous, better use `mkstemp'
collect2: error: ld returned 1 exit status
```

However, if I do the same for `master`, it works fine.  Any ideas of what else needs to be fixed? I'm not entirely sure if `master` will become `v1.10.0-rc3` or not, but I'd like to get this fixed (if possible) before v1.10 is released.

**Comment by jfrazelle** [comment]
Try adding -lpthread to the binary compilation

**Comment by jfrazelle** [comment]
Also master no longer compiles dockerinit which means it no longer requires a libseccomp.a

**Comment by jfrazelle** [comment]
So it looks from your output libseccomp is not installed at all

**Comment by jfrazelle** [comment]
Or there is no libseccomp.a

**Comment by Djelibeybi** [comment]
Except if I build from the HEAD of master, it works fine with zero changes to the Dockerfile used for OL7.

**Comment by Djelibeybi** [comment]
Ok, our seccomp is too old according to generate.sh. Sorry for the noise.

**Comment by jfrazelle** [comment]
Yeah I know that's because we removed dockerinit on master

On Monday, February 1, 2016, Avi Miller <notifications@github.com> wrote:

> Except if I build from the HEAD of master, it works fine with zero changes
> to the Dockerfile used for OL7.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/19905#issuecomment-178291174>.
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>
