### ISSUE TITLE
Why is pulling layer 3a32959397f1 for in2ex/jenkins soooooo slow?

### ISSUE THREAD

**Issue by dzwicker** [docker/docker#19916]
The image in2ex/jenkins:1.642.1.0 (c9ee245fe79b) consist of 20-30 layers. The pull is very good and fast, except for the layer 3a32959397f1. It is by far not the biggest layer. Even after restarting the pull this layer stays to lack or what ever?

Greetings

**Comment by dzwicker** [comment]
Tried on different machines. Mac OS with docker-machine and virtualbox and a nativ ubuntu 14.04....

**Comment by dzwicker** [comment]
docker version:
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
```

docker info:
```
Containers: 0
Images: 150
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 150
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-77-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 8
Total Memory: 15.55 GiB
Name: jenkins
ID: 24Q3:UB34:53NO:EEBP:WAHS:5VMN:YVGF:NJQE:73M5:HVJ5:QV6C:XS3I
Username: dzwicker
Registry: https://index.docker.io/v1/
```

**Comment by thaJeztah** [comment]
Could you open a ticket through support@docker.com? This issue tracker is for tracking bugs in docker; we don't have access to logs in Docker Hub (and it looks like the image you're describing is a private repository), so cannot help you here.
