### ISSUE TITLE
Unable to setup mount point, neither source nor volume defined

### ISSUE THREAD

**Issue by siccovansas** [docker/docker#19925]
**Description of problem:**
I recently upgraded Docker to `Docker version 1.9.1, build a34a1d5` from an old Docker version (1.0.1?). All my containers started fine again after the upgrade except for my two Etherpad Lite containers (one containing MySQL and the other the Etherpad Lite application).

I've originally created the containers as per [these instructions](https://hub.docker.com/r/tvelocity/etherpad-lite/):

    docker run -d -e MYSQL_ROOT_PASSWORD=[PASSWORD] --name ep-mysql mysql
    docker run -d -e ETHERPAD_ADMIN_PASSWORD=[PASSWORD] --link=ep-mysql:mysql --name c-etherpad tvelocity/etherpad-lite

When I now run `docker start ep-mysql` I get the following error:
```
Error response from daemon: Cannot start container ep-mysql: Unable to setup mount point, neither source nor volume defined
Error: failed to start containers: [ep-mysql]
```

Based on [this issue](https://github.com/docker/docker/issues/18593) I used `docker  inspect` and noticed that my `Source` was also empty:
```
    "Mounts": [
        {
            "Name": "7f3f0a294baa5a20a74313d93a5eb56158f4d55090d5beeeffda59dd2d68703e",
            "Source": "",
            "Destination": "/var/lib/mysql",
            "Driver": "local",
            "Mode": "",
            "RW": true
        }
    ],
```

I tried to manually fix this by editing `config.json` (as also suggested in the issue I linked above) and put `/var/lib/docker/volumes/7f3f0a294baa5a20a74313d93a5eb56158f4d55090d5beeeffda59dd2d68703e/_data` into the `Source` field, but after starting the container again I get the same error and the `Source` field in `config.json` is emptied again.

I think I'm on the right track, but I'm not sure how to fix this problem from here on. Any ideas?

More info:
`docker version`:
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:
```
Containers: 122
Images: 730
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 975
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-73-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 31.34 GiB
ID: VFFJ:NFJ4:MPF5:BGZA:EB2I:ZJGD:LKV6:U6I6:CJGI:FCHJ:CKGF:M2MD
WARNING: No swap limit support
```

`uname -a`:

    Linux 3.13.0-73-generic #116-Ubuntu SMP Fri Dec 4 15:31:30 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.): physical

**Comment by thaJeztah** [comment]
Docker 1.0.1 is really really old, so it wouldn't surprise me that updating directly from 1.0.1 to 1.9.1 broke some things. Is the `/var/lib/docker/volumes/7f3f0a294baa5a20a74313d93a5eb56158f4d55090d5beeeffda59dd2d68703e/_data` directory actually present?

You could try running a new container, and using `-v 7f3f0a294baa5a20a74313d93a5eb56158f4d55090d5beeeffda59dd2d68703e:/var/lib/mysql`

**Comment by HackToday** [comment]
yes, @thaJeztah  gives good suggestion.
 I am thinking @siccovansas manually edit the config.json, seems container not saved that. Seems need commit with a new image  and run with that ?

**Comment by siccovansas** [comment]
@thaJeztah `/var/lib/docker/volumes/7f3f0a294baa5a20a74313d93a5eb56158f4d55090d5beeeffda59dd2d68703e/_data` does exist. I tried using the volume as you suggested and it works! Thanks :+1:!
