### ISSUE TITLE
seccomp bpf filter program 

### ISSUE THREAD

**Issue by thesrinivas** [docker/docker#19930]
Is there an example showing how to specify a seccomp bpf filter program to a container? eg. http://man7.org/linux/man-pages/man2/seccomp.2.html

**Comment by thaJeztah** [comment]
You mean, something like https://github.com/docker/docker/pull/17989 ? That's coming in docker 1.10

**Comment by thesrinivas** [comment]
Actually, I am looking for a way to specify a bpf program and not just syscalls w/ arguments. The link http://man7.org/linux/man-pages/man2/seccomp.2.html shows an example bpf program.

**Comment by thaJeztah** [comment]
Ah, sorry, was reading too fast. I don't think that's currently implemented, but @jfrazelle should know

**Comment by jfrazelle** [comment]
yeah that needs to be implemented in runc first

**Comment by thesrinivas** [comment]
Is there an approx timeline for this feature to be added?
Thanks

**Comment by jfrazelle** [comment]
so we would all have to agreee on how they should be defined etc... so not
really, checkout github.com/opencontainers/runc

On Tue, Feb 2, 2016 at 2:16 PM, Srinivas Dharmasanam <
notifications@github.com> wrote:

> Is there an approx timeline for this feature to be added?
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/19930#issuecomment-178855165>.
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jfrazelle** [comment]
and github.com/opencontainers/specs

On Tue, Feb 2, 2016 at 2:18 PM, Jessica Frazelle <me@jessfraz.com> wrote:

> so we would all have to agreee on how they should be defined etc... so not
> really, checkout github.com/opencontainers/runc
>
> On Tue, Feb 2, 2016 at 2:16 PM, Srinivas Dharmasanam <
> notifications@github.com> wrote:
>
>> Is there an approx timeline for this feature to be added?
>> Thanks
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/docker/docker/issues/19930#issuecomment-178855165>.
>>
>
>
>
> --
>
>
> Jessie Frazelle
> 4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
> pgp.mit.edu
> <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by thaJeztah** [comment]
@thesrinivas given that this depends on changes in runc first, I think we should close this issue pending that change/discussion.

(But I'm happy to reopen this once we can move forward). wdyt?

**Comment by jfrazelle** [comment]
sgtm!

On Tue, Feb 2, 2016 at 2:35 PM, Sebastiaan van Stijn <
notifications@github.com> wrote:

> @thesrinivas <https://github.com/thesrinivas> given that this depends on
> changes in runc first, I think we should close this issue pending that
> change/discussion.
>
> (But I'm happy to reopen this once we can move forward). wdyt?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/19930#issuecomment-178865890>.
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by thesrinivas** [comment]
I'd be happy to help develop this. Any advice?

**Comment by jfrazelle** [comment]
You need to make a proposal to opencontainers/specs with how it will work
with the existing Seccomp data structure

On Tue, Feb 2, 2016 at 2:49 PM, Srinivas Dharmasanam <
notifications@github.com> wrote:

> I'd be happy to help develop this. Any advice?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/19930#issuecomment-178871982>.
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by thesrinivas** [comment]
Ok. Thanks!

**Comment by thaJeztah** [comment]
I'll close this issue for now; looking forward to see it moving once implemented in runc. Thanks in advance!

**Comment by thesrinivas** [comment]
Hi,
Sorry about using this thread.

I created this runc issue
<https://github.com/opencontainers/runc/issues/531> based on this thread
and havent received any response yet.
Any advice on how I could take this forward?

Thanks much

**Comment by thaJeztah** [comment]
@thesrinivas my guess is, they didn't have time yet to respond; I'd wait for a few more days, and otherwise "ping" [one of the maintainers](https://github.com/opencontainers/runc/blob/master/MAINTAINERS), or send an e-mail to the mailinglist dev@opencontainers.org
