### ISSUE TITLE
how to remove a container which has been started with "--restart=always"

### ISSUE THREAD

**Issue by surlymo** [docker/docker#19955]
i try "docker rm -f" but it does not works.

**Comment by qq690388648** [comment]
What is the version of your docker and os?
My docker 1.9.1 on Ubuntu 12.04.2 can remove the container running with "--restart=always" successfully.

**Comment by surlymo** [comment]
@qq690388648 
docker version 1.9.1
centos 7
kernel 3.10.0-229.el7.x86_64

**Comment by surlymo** [comment]
finally found that the container is built by marathon rather than docker command...

**Comment by qq690388648** [comment]
晕。。
