### ISSUE TITLE
error creating aufs mount invalid argument

### ISSUE THREAD

**Issue by amulyas** [docker/docker#19956]
We hada disk almost full 97% then restarted docker .. running containers not came back .. deamon throwing below error for all containers 

time="2016-02-03T03:29:08.906695677Z" level=debug msg="Failed to start container 119979f713275c3509677435f2fd0bc041494362c7b7b7e7c814a871f7d7c169: Error getting container 119979f713275c3509677435f2fd0bc041494362c7b7b7e7c814a871f7d7c169 from driver aufs: error creating aufs mount to /xx/xx/xx/docker/docker/aufs/mnt/119979f713275c3509677435f2fd0bc041494362c7b7b7e7c814a871f7d7c169: invalid argument"

Containers: 64
Images: 28
Storage Driver: aufs
 Root Dir: /xx/xx/xx/docker/docker/aufs
 Backing Filesystem: extfs
 Dirs: 156
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 40
Total Memory: 157.4 GiB
Name: af93ecc3-91ea-xxx-82d3-6228d5582b91
ID: 22OT:FSKN:DCHD:X3WQ:3WGA:64HV:ES53:IQY3:6IJE:OZIU:NKM2:NTEJ
Debug mode (server): true
File Descriptors: 10
Goroutines: 15
System Time: 2016-02-03T05:13:42.582285385Z
EventsListeners: 0
Init SHA1:
Init Path: /xx/xx/xx/docker/bin/docker
Docker Root Dir: /xx/xx/xx/docker/docker

Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64

**Comment by thaJeztah** [comment]
Yes, running docker with a full disk is known to result in issues, I'm not sure there's an easy way to work around that

**Comment by amulyas** [comment]
@thaJeztah thanks for confirming .. but all our containers are at state now where we can not recover them .. at all .. without losing containers ..

**Comment by thaJeztah** [comment]
@cpuguy83 do you have any tips here? Is there a way to recover?

**Comment by LK4D4** [comment]
Closing as inactive. Feel free to open new issue - new issues will have much more attention.
