### ISSUE TITLE
"Unrecognized input header" interrupting docker client

### ISSUE THREAD

**Issue by clkao** [docker/docker#19950]
I am seeing this in 1.10.0 rc1 and rc2 about 5~10% of the time.

The `docker run` client exited with "Unrecognized input header" after a few minutes, but the container was still running and you can see new output with `docker logs -f`

The `docker run` cmmand is: (simplified just to show what switches are being used)

```
docker run --entrypoint /sbin/smell-baron --name somename -h somehost --volumes-from somevolume -e BRANCH=foo -v /path/to/devscript:/devscript $IMAGE bash -l /devscript/build.sh
```

I don't have a small reproducible case at the moment though.

`docker inspect` the container shows: (looks very normal)

```
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2016-02-02T21:10:56.5227335Z",
            "FinishedAt": "2016-02-02T21:15:22.471208248Z"
        },
```

**Comment by thaJeztah** [comment]
Could you add some information about your setup? (see the template above)

**Comment by HackToday** [comment]
Also if possible, docker debug level logs show something else ?

**Comment by clkao** [comment]
```
% uname -a
Linux ip-10-0-0-4 3.19.0-47-generic #53~14.04.1-Ubuntu SMP Mon Jan 18 16:09:14 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

% docker info
Containers: 30
 Running: 5
 Paused: 0
 Stopped: 25
Images: 236
Server Version: 1.10.0-rc2
Storage Driver: btrfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.19.0-47-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 29.44 GiB
Name: ip-10-0-0-4
ID: WQ5A:YSST:Q7BM:WDJV:EDRE:YCBF:J2BS:3OYK:Z7DX:U4JS:WHWD:DOUN
WARNING: No swap limit support
```

**Comment by dpiddy** [comment]
Seeing this as well since our systems picked up 1.10.0. We use `docker run` started by upstart on Ubuntu 14.04, with stdout and stderr redirected to a fifo if that helps. Will try and gather more info.

**Comment by cpuguy83** [comment]
@dpiddy Try running the client with debug enabled (i.e `docker -D run <args>`), this should print out some debug info.

**Comment by dpiddy** [comment]
Getting messages in this form:

```
\x00\x00\x00\x00\x00]app=...time="2016-02-05T15:58:56Z" level=debug msg="Error selecting output fd: (104)"
\x00\x00\x00\x00\x00]app=...time="2016-02-05T15:57:23Z" level=debug msg="Error selecting output fd: (104)" 
\x00\x00\x00\x00\x00Happ=...time="2016-02-05T15:49:56Z" level=debug msg="Error selecting output fd: (52)"
\x00\x00\x00\x00\x00Happ=...time="2016-02-05T15:47:07Z" level=debug msg="Error selecting output fd: (52)" 
```

where `app=...` represents what my application is logging. I can share full lines privately if that would help. I've only seen 104 and 52 appear so far.

**Comment by dpiddy** [comment]
Here are hexdumps of the two forms:

104:

```
00000000  01 5c 78 30 30 5c 78 30  30 5c 78 30 30 5c 78 30  |.\x00\x00\x00\x0|
00000010  30 5c 78 30 30 01 5d                              |0\x00.]|
00000017
```

52:

```
00000000  01 5c 78 30 30 5c 78 30  30 5c 78 30 30 5c 78 30  |.\x00\x00\x00\x0|
00000010  30 5c 78 30 30 01 48                              |0\x00.H|
00000017
```

**Comment by dpiddy** [comment]
Ah was missing other `level=debug` stuff. Here's the full debug output from at least one run, will add more files if I find variations:

https://gist.github.com/dpiddy/5e77828c988bb5080b72

**Comment by clkao** [comment]
@dpiddy are you able to reproduce this reliably? this only happened sporadically for me

**Comment by dpiddy** [comment]
If I get enough instances running this particular app it's pretty easy to trigger it. For example, with 10 instances 3-4 might fail like this. It takes some time after the application starts, too, maybe 15 minutes or so.

**Comment by dpiddy** [comment]
Ah you can see from the gist that one lasted ~4 minutes and the other ~10.

**Comment by LK4D4** [comment]
This error is from `stdcopy` package which muxes stdout/stderr streams. It seems like now it writes something weird; I think it can also be  golang version change.

**Comment by tiborvass** [comment]
@dpiddy do you think you can give us a way to reproduce so that we can debug it more easily?

**Comment by Smana** [comment]
https://github.com/kubespray/setup-kubernetes/issues/131

**Comment by anusha-ragunathan** [comment]
@dpiddy : Can you share the docker run command line? I'm specifically interested to know how stdout, stderr are redirected to the fifo (including how the fifo is created). Thanks.

**Comment by tiborvass** [comment]
Ping @dpiddy

**Comment by dpiddy** [comment]
Sorry, at an onsite this week and haven't had time to circle back on this.
Might not be until next week.

**Comment by dpiddy** [comment]
Here is what the `docker run` setup looks like. We use ansible to generate some things but here is a compiled version of how it works:

```
mkdir -p /var/log/docker
output_fifo=/var/log/docker/app-web.fifo
rm -f $output_fifo
mkfifo $output_fifo
instance_id=$(cat /var/lib/cloud/data/instance-id)
( exec setsid envdir /etc/log-shuttle/app/env.d setuidgid log-shuttle /usr/bin/log-shuttle -appname=app -procid=web".$instance_id" < $output_fifo & )
exec >$output_fifo 2>&1
rm $output_fifo
env_d="/etc/docker-containers/app/env.d"
env_args="$(cd "$env_d" && ls | perl -ne 'print "-e ", $_')"
docker rm -f "app-web" 1>/dev/null 2>&1 || true
exec env - \
  envdir "$env_d" \
  docker run --name "app-web" --rm --sig-proxy $env_args --log-driver=none \
  --privileged -p 9999:8080 --net=host -v ... -v ... \
  app-image web
```

If it helps at all, log-shuttle there is [this](https://github.com/heroku/log-shuttle).

**Comment by clkao** [comment]
I added `-t` to the run command, and we haven't seen the sporadic "Unrecognized input header" error for a few days.

**Comment by dpiddy** [comment]
That makes sense, if `-t` is used then ultimately `stdcopy` [is not used](https://github.com/docker/docker/blob/e2a0618fb1f32572f2b5b11f97278634be4ea31c/api/client/hijack.go#L17).

**Comment by dpiddy** [comment]
Working on debugging this, hope to have something in the next few days. Maybe tonight.

**Comment by dpiddy** [comment]
Starting to think this is due to concurrent calls to `Write` by `StdWriter` to the same underlying `io.Writer`. 

If I understand correctly, an attached `docker run` follows this journey to get logs out:

1. [ContainerAttach call in run command](https://github.com/docker/docker/blob/675617bc857910fd3f512f21a7c6ff160d99cd1d/api/client/run.go#L209)
2. [ContainerAttach in engine-api](https://github.com/docker/docker/blob/675617bc857910fd3f512f21a7c6ff160d99cd1d/vendor/src/github.com/docker/engine-api/client/container_attach.go#L32) with stream=1
3. [postContainersAttach uses setupStreams as GetStreams which returns the conn as both out and err](https://github.com/docker/docker/blob/675617bc857910fd3f512f21a7c6ff160d99cd1d/api/server/router/container/container_routes.go#L455)
4. [Daemon.ContainerAttach creates new StdWriters using the conn as the io.Writer for both](https://github.com/docker/docker/blob/675617bc857910fd3f512f21a7c6ff160d99cd1d/daemon/attach.go#L33-L34)
5. [Daemon.containerAttach calls Container.Attach](https://github.com/docker/docker/blob/675617bc857910fd3f512f21a7c6ff160d99cd1d/daemon/attach.go#L111)
6. [Container.Attach calls Container.AttachStreams](https://github.com/docker/docker/blob/675617bc857910fd3f512f21a7c6ff160d99cd1d/container/container.go#L362)
7. [Container.AttachStreams uses attachStream on stdout and stderr in two goroutines, which eventually call io.Copy](https://github.com/docker/docker/blob/675617bc857910fd3f512f21a7c6ff160d99cd1d/container/container.go#L429)

Hope I've traced that properly. I'll try to continue this soon but maybe this helps someone who's familiar with things verify. I hope to also try injecting a (probably hacky) mutex around `conn.Write` in step 3 or so to see if that clears up the issue.

**Comment by dpiddy** [comment]
Even better, I think [this program](https://gist.github.com/dpiddy/0c460a8bb297ee19a7a0) shows the issue. Running it crashes in various ways, including "Unrecognized input header:"

```
% go run main.go  
DEBU[0000] framesize: 4                                 
err
DEBU[0000] framesize: 4                                 
err
DEBU[0000] framesize: 4                                 
err
DEBU[0000] framesize: 4                                 
err
DEBU[0000] framesize: 4                                 
err
...
DEBU[0000] framesize: 4                                 
err
DEBU[0000] framesize: 4                                 
err
DEBU[0000] Error selecting output fd: (111)             
2016/02/22 00:30:10 Unrecognized input header
exit status 1
```

**Comment by cpuguy83** [comment]
Hmm, I guess not very far-fetched since 1.10 is the first version of docker that runs with parallelism by default.

**Comment by stevenschlansker** [comment]
Can confirm that this also affects 1.10.2.  This is a very serious issue for any coordination layers (we run Mesos) -- it causes stale tasks to be lost indefinitely, and then you start to have older versions of code lying around and being nondeterministically used.

**Comment by cpuguy83** [comment]
@stevenschlansker Please explain? This issue is about the client correctly interpreting tty headers.

**Comment by stevenschlansker** [comment]
Mesos invokes `docker run someimage` via the CLI.  It redirects the output of the CLI to stdout / stderr files.  Often, we will observe the characteristic `Unrecognized input header` in the `stderr` file, immediately followed by a `TASK_FAILED` event from Mesos -- even though the `docker run` failed, the container behind it continues to run.  So the task is severed from Mesos coordination, it think the task is dead and provisions a replacement -- but really the task is still running.  I think that fits the behavior of this bug, but if I'm mistaken let me know and I can file a separate issue.  This is with Mesos 0.27.1 and Docker 1.10.2

**Comment by cpuguy83** [comment]
@stevenschlansker Thanks for explaining, that makes sense.

**Comment by AaronDMarasco-VSI** [comment]
I just upgraded from 1.9.1 to 1.10.2 and this is potentially a showstopper. :-1: Since it doesn't happen explicitly at start-up or take-down, it is very difficult for me to try to script around it... I've hit it twice already today.

**Comment by cpuguy83** [comment]
@AaronDMarasco-VSI Thanks for the info. I've opened #20874 to discuss a 1.10.3 release.

**Comment by clkao** [comment]
In #20874 there is discussion about escalating this to a P0 issue for justify a patch release.  I personally think this is P0 because existing tools using docker will break undeterministically after upgrading to 1.10 due to this issue.

**Comment by stevenschlansker** [comment]
+1, this is definitely a P0 from our perspective...

**Comment by stanislavb** [comment]
Running 1.10.2. This is breaking our batch jobs several times per day.

**Comment by AaronDMarasco-VSI** [comment]
> This is breaking our batch jobs several times per day.

Same here, and #20874 was just shot down last night.

**Comment by AaronDMarasco-VSI** [comment]
FYI, since the problem seems to be the muxing of stdout and stderr, here's a workaround that I've tried on a few of my Jenkins jobs:

`command_that_blows_up 2>&1 | tee /dev/null`

This hasn't failed yet, but isn't guaranteed either...

**Comment by alanfranz** [comment]
Simply launching docker run with the '--tty' is a successful workaround.
But requires patching just EVERY piece of software using docker run.

I'm +1 for escalating this issue to P0.

**Comment by drewrobb** [comment]
I feel that this issue should be relabeled as P0 so that a patch release can be made.

Thanks

**Comment by calavera** [comment]
that bug affects `docker run` which is probably the main docker feature, so I'm moving this issue to P0. We'll start working on a patch release on Monday.

**Comment by icecrime** [comment]
Please give me a minute to look into it.

**Comment by pdalpra** [comment]
@calavera +1 we moved back to 1.8.3 because of this, and using the `-t` flag as a workaround is not possible when interacting with machines created by Docker Machine on AWS.

**Comment by icecrime** [comment]
Ok I have to agree, this issue is pretty bad. Re-qualifying as P0, we will look into preparing a patch release.

**Comment by stevenschlansker** [comment]
Thank you!!!

**Comment by thaJeztah** [comment]
@AaronDMarasco-VSI @pdalpra @stanislavb @drewrobb could you drop me an e-mail at sebastiaan@docker.com ? Perhaps you're interested in being added to our "testers" mailing list

**Comment by AaronDMarasco-VSI** [comment]
@alanfranz I just confirmed that "`docker run -td`" did _not_ stop it from happening. :frowning:

**Comment by alanfranz** [comment]
@AaronDMarasco-VSI i don't know what happens when detaching; I am using --tty only in foreground. But while my test suite for docker-rpm-builder would always trigger the issue without --tty, it has never failed so far with --tty. Maybe docker's own behaviour changes if --detach is passed.

**Comment by jimmidyson** [comment]
@icecrime Although you've changed the priority label this issues is still closed - seems like it's worth reopening?

**Comment by thaJeztah** [comment]
@jimmidyson it's closed because it has been resolved by https://github.com/docker/docker/issues/20706, which will be in the 1.10.3 patch release (release candidate for that is up now for testing https://github.com/docker/docker/releases/tag/v1.10.3-rc2)

**Comment by jimmidyson** [comment]
@thaJeztah Ah sorry missed that - thanks!

**Comment by AaronDMarasco-VSI** [comment]
> We're still planning on releasing 1.10.3 tomorrow.

This was sent to the testers mailing list yesterday. :grinning:

**Comment by thaJeztah** [comment]
@AaronDMarasco-VSI yes! If all goes well, 1.10.3 is released today (San Francisco time). Be sure to torture the RC as much as you can :wink:

**Comment by pdalpra** [comment]
All is well on our side, Docker had a very busy day and we didn't encounter that issue with RC2 :)

**Comment by thaJeztah** [comment]
@pdalpra awesome, thanks so much!

**Comment by AaronDMarasco-VSI** [comment]
@thaJeztah I installed 1.10.3 final yesterday about an hour after you released  (sorry, couldn't test because we only use RPMs). Told Jenkins to do two full runs and everything seems rock solid. Thanks!

**Comment by alanfranz** [comment]
@AaronDMarasco-VSI  There're RPMs and DEBs for RCs as well:

this is the RPM testing repo for centos-7:
http://yum.dockerproject.org/repo/testing/centos/7

**Comment by AaronDMarasco-VSI** [comment]
@alanfranz OK, thanks. I didn't see them in time. If I'm in another chomping-at-the-bit scenario like I was for this one, I'll be sure to track them down.

**Comment by thaJeztah** [comment]
@AaronDMarasco-VSI @alanfranz thanks for testing! Happy to hear it's resolved

**Comment by drewrobb** [comment]
I have also tested the issue we saw before with 1.10.2 using mesos/marathon and 1.10.3 has fixed it. Thanks for making this patch release happen!

**Comment by thaJeztah** [comment]
Thank you @drewrobb, and happy to hear it's resolved.

For those on this thread; we all want Docker to be as stable as possible for everyone. Having said that, deciding wether or not a patch release should be created is always tough; it requires a lot of coordination, and freeing up resources in multiple teams. In addition, there's always a risk involved and seemingly "small" changes, can negatively affect other users. Thank you all again for reporting, and testing the release; it's really appreciated!
