### ISSUE TITLE
Docker 1.10 and Amazon Elastic Container Registry

### ISSUE THREAD

**Issue by kitsushadow** [docker/docker#19996]
So I have been using Docker 1.10 to make sure it works well with existing 3rd party products. I am having a serious problem in regards to pushing images to an ECR. The push times out every one min and tries 3 or 5 times, can't remember. I downgrade to 1.9 and the push works just fine. This is a significant blocker for anyone using Amazon ECS as their deployment cluster and hoping to upgrade to Docker 1.10

**Comment by cpuguy83** [comment]
Please try with RC4, which just came out yesterday.
There is a fix for push timeouts.

**Comment by kitsushadow** [comment]
@cpuguy83 I can't find the RC4 file. Can you please point me in its direction?

Thanks

**Comment by cpuguy83** [comment]
https://releases.dockerproject.org/

**Comment by kitsushadow** [comment]
@cpuguy83 thanks, Im getting an auth issue with aws

./docker-1.10.0-rc4 login -u AWS -p super_long_token -e none https://314410645069.dkr.ecr.us-east-1.amazonaws.com

Just hangs

**Comment by kitsushadow** [comment]
ERRO[0886] Handler for POST /v1.22/auth returned error: invalid registry endpoint https://314410645069.dkr.ecr.us-east-1.amazonaws.com/v0/: unable to ping registry endpoint https://314410645069.dkr.ecr.us-east-1.amazonaws.com/v0/
v2 ping attempt failed with error: Get https://314410645069.dkr.ecr.us-east-1.amazonaws.com/v2/: dial tcp 52.21.100.222:443: i/o timeout
 v1 ping attempt failed with error: Get https://314410645069.dkr.ecr.us-east-1.amazonaws.com/v1/_ping: dial tcp 52.21.84.137:443: i/o timeout. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry 314410645069.dkr.ecr.us-east-1.amazonaws.com` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/314410645069.dkr.ecr.us-east-1.amazonaws.com/ca.crt

**Comment by cpuguy83** [comment]
@kitsushadow Do you have the RC4 daemon running?

**Comment by cpuguy83** [comment]
@kitsushadow Should the `https://` be there?

**Comment by kitsushadow** [comment]
@cpuguy83 yes the daemon is running but its running as sudo b/c if i dont use sudo i get this error 

[mminaie@localhost Downloads]$ ./docker-1.10.0-rc4 daemon
unable to configure the Docker daemon with file /etc/docker/daemon.json: open /etc/docker/daemon.json: permission denied

**Comment by cpuguy83** [comment]
@kitsushadow Yes, the daemon must run as root.

**Comment by kitsushadow** [comment]
@cpuguy83 thanks for the help! working now
