### ISSUE TITLE
Usernamespaces skip flag - allow privileged operations

### ISSUE THREAD

**Issue by liron-l** [docker/docker#19995]
Hi,

Currently the existing implementation of user namespaces works as all-or-nothing feature. 
That is, once user namespaces are set in the global daemon level, there is no way to use any of the advance container privileged operations (e.g., pid=host, net==host or --privileged or mounting host folder w/o changing permissions).

There are several scenarios where customers would like use user namespaces in the global level but still allow running a subset of privileged containers for various administrative purposes (e.g., maintenance or security).

We purpose to extend the existing user namespace mechanism by adding a skip flag when creating or attaching to existing containers.
Specifically:
```bash
$ docker run --skip-userns ...
$ docker exec --skip-userns ...
```

Technically, when --skip-userns option is used, the Docker daemon will ignore converting the user id and will respect the actual --user parameter (or root if no user is specified).
Also, when the --skip-userns option is specified, the existing hard-coded daemon limitation (privileged and host/pid namespace) will be removed.

I would be happy to own the design and implementation once we agree on the approach.

**Comment by liron-l** [comment]
@estesp can you please review.

**Comment by estesp** [comment]
Although the discussion has been light on GH, we do already have #17409 discussing that possibility, focusing specifically on `--privileged`.  @mrunalp and I discussed it when we were F2F in SF last month, and the biggest open question I had was whether it was a problem that files created in this mode would not be mapped properly for the userns scenario.  Of course that would only impact if `docker commit` was used and then the result was used in a container running with userns enabled.

Potentially we can just warn about that in docs, but seems like there is general agreement we need some way to have a "privileged" mode when userns is enabled at the daemon level.

**Comment by liron-l** [comment]
Thanks @estesp. I think having an explicit flag to skip the usernamespace mapping is better than only doing it when --privileged is added (since this enables supporting other 'privileged' tags such as pid=host or net=host).

Do you want to close this issue and continue the discussion in #17409?

**Comment by LK4D4** [comment]
I think that it was implemented with `--userns=host`. Feel free to open new issue if not.
