### ISSUE TITLE
Docker x86 Windows

### ISSUE THREAD

**Issue by MikailBag** [docker/docker#20004]
Official installer is for x64 only.
What should I do?
(Windows 7)

**Comment by MikailBag** [comment]
It isn;t a bug, it's just question.
And I couldn't find same issue

**Comment by StefanScherer** [comment]
@MikailBag look at #20012 and then for the 32bit port (really unofficial), but tested this on Win10 32bit today with VirtualBox. :angel:

**Comment by cpuguy83** [comment]
Closing in favor of #20012
