### ISSUE TITLE
files delivered incorrectly from overlay file system

### ISSUE THREAD

**Issue by syntithenai** [docker/docker#20008]
I saw an interesting one last night to make me crazy.
Something to do with the union file system.

Including codemirror caused a script error so I edited its script file and inserted a single line of javascript.

What was delivered from nginx was the original content of the file but only the length of the new content. 

If I changed the file, the length of the original content change was delivered to match.

So I changed the location of the codemirror file and all was good.

**Comment by cpuguy83** [comment]
This is a common problem with using shared mounts from a VM host and `sendfile` in nginx/Apache.
If you turn off `sendfile` it will work just fine.

https://www.virtualbox.org/ticket/9069
