### ISSUE TITLE
Add client-side element to the User-Agent string

### ISSUE THREAD

**Issue by icecrime** [docker/docker#20001]
## Description

As Docker supports more and more platforms, but also cross-platforms use cases (e.g., Windows client interacting with a Linux daemon, OSX client interacting with a Windows daemon, ...), the user-agent string when interacting with Registry should reflect that.

## How to

Have the docker client pass down its own portion of the user-agent string, that the daemon will complete.

Ping @rogaha @thaJeztah @docker/distribution-maintainers @friism

**Comment by friism** [comment]
Pertinent RFC: http://tools.ietf.org/html/rfc7231#section-5.5.3

Code: https://github.com/docker/docker/blob/master/dockerversion/useragent.go#L12

**Comment by thaJeztah** [comment]
> Have the docker client pass down its own portion of the user-agent string, that the daemon will complete

Not entirely sure how to read the "daemon will complete" part; aren't client and daemon two separate components? In which case should the daemon pass-thru information about the client?

**Comment by endophage** [comment]
@icecrime I strongly support this feature :+1: 

@thaJeztah To the server (registry/notary/etc...) a combination of docker client and daemon represent a single "client", so it would be very useful to be able to see high level info about both of those components. It will greatly increase visibility on whether there are bugs that only occur when the client and daemon are running on different OSes (the thing I would expect most is character encoding or path weirdness when one of the two is on Windows and the other is not), and potentially different versions too.

**Comment by stevvooe** [comment]
How do these user agents compose in a consistent manner? How should they be composed when passing through multiple clients?

**Comment by thaJeztah** [comment]
@endophage will it be purely used for analytical / debugging purposes, or are we going to change API behavior based on the User Agent? Because, if we do, that feels like browser-sniffing. If we anticipate that we're going to give different responses, based on the client being used, I think this should be part of the API specs (can we handle all possible clients? cURL? Some random JavaScript client library?)

> How do these user agents compose in a consistent manner? How should they be composed when passing through multiple clients?

Should we use a separate header (e.g. "Forwarded For", and have each component add the User Agent of the calling client(s))?

**Comment by stevvooe** [comment]
@thaJeztah We may be able to phrase this question differently: Do we want to understand the set of processes involved in the request or do we want to trace the processes involved? If it is just the former, which is interesting, this is simple.

Check out https://github.com/docker/docker/issues/10328 for a possibly related idea.

What we need to be careful about here is making decisions about the content served based on the user agent. That is the path to massive future problems. Put more strongly, I will never back a change to the registry or any service that uses the user agent to decide on which content to serve.

**Comment by endophage** [comment]
@thaJeztah @stevvooe the RFC linked by @friism describes how to include multiple "products" in the User-Agent string. With that in mind, The User-Agent string seems to be the right place to include the information and I would expect something like (only a possible example, don't hold me to it):
```
docker-client/1.10.0 (Windows NT 6.1) docker-engine/1.10.0 (Linux x86_64)
```

**Comment by endophage** [comment]
@stevvooe I haven't seen the implementation. How is the registry deciding to rewrite 1.10 manifests for old clients? Is there a new parameter 1.10 sends and absence of that param causes the rewrite?

**Comment by dmcgowan** [comment]
@endophage the registry version which does rewrites uses an HTTP Accept header to make any decisions about which manifest version to serve. When that header is either omitted or set to something unexpected then it defaults to the schema 1 ("old") manifest format.

**Comment by friism** [comment]
I agree with @stevvooe that the user-agent header value should never be used to alter behavior of the registry (the Accept header is better for that). This is a convenience for registries and Hub to gather stats on the clients that are interacting with it.

**Comment by thaJeztah** [comment]
That was my main issue; User Agent should not be used to alter behavior. Accept header is better; If we need more fine-grained control, we could decide on having the client send a "profile" (supported/unsupported options etc), but that would be a big change/effort.

**Comment by endophage** [comment]
In most instances I'd agree, but here's a counter example that I've had to deal with in the past: http://stackoverflow.com/a/6745788/432193 (it's a few years old and I don't know what the state of support is now).

I'm not advocating we use the User-Agent for writing different content, I still think it would be good to include both client and daemon info in it.

**Comment by endophage** [comment]
Should also point out, putting a piece of information in a different location doesn't stop a developer using it for something they shouldn't. The User-Agent is the semantically correct, expected, least surprising place to put the information described. How that information gets used is up to us to police within docker's projects regardless of its location in a request.

**Comment by rogaha** [comment]
I'm with @endophage. According to the documentation that @friism shared (http://tools.ietf.org/html/rfc7231#section-5.5.3), it's expected to use the `user_agent` for that purpose. 

+1 on extending the current `user_a gent` content. I volunteer to work on it, if we agree on this change.

**Comment by stevvooe** [comment]
> Should also point out, putting a piece of information in a different location doesn't stop a developer using it for something they shouldn't. The User-Agent is the semantically correct, expected, least surprising place to put the information described. How that information gets used is up to us to police within docker's projects regardless of its location in a request.

Sure but we shouldn't build this in as a requirement for properly interoperating with the protocol. For example, an HAProxy router to vector requests to an older client would be acceptable, but adopting this as a protocol wide requirement would be problematic.

We should give clients the ability to declare what data they desire and support. Making assumptions based on user agent, as called out in http://tools.ietf.org/html/rfc7231#section-5.5.3, has, can and will lead to convoluted protocol support. It should be avoided at all cost.

**Comment by mgoelzer** [comment]
I think this issue can be closed.  #21306 and #21373 resolved it.

**Comment by thaJeztah** [comment]
Yes! Closing
