### ISSUE TITLE
There aren't enough issues on this project

### ISSUE THREAD

**Issue by aanand** [docker/docker#20000]
20,000 seems kind of small-time.

**Comment by duglin** [comment]
LOL sneaky!

**Comment by thaJeztah** [comment]
Haha

![20000-leagues-under-sea-remake](https://cloud.githubusercontent.com/assets/1804568/12821593/5070880e-cb64-11e5-8bfb-d56b835725a0.jpg)

**Comment by cpuguy83** [comment]
I can't reproduce this.

**Comment by thaJeztah** [comment]
> 20,000 seems kind of small-time

In Europe indeed; three digits after the comma.. :innocent:

**Comment by rysiekpl** [comment]
Wow, that's OVER 9000!

**Comment by vdemeester** [comment]
![minions-tchating](https://cloud.githubusercontent.com/assets/6508/12822295/b90ceec2-cb67-11e5-87fb-9322b674263a.gif)

**Comment by justincormack** [comment]
![houghton_fc8_v5946_869ve_-_verne _frontispiece](https://cloud.githubusercontent.com/assets/482364/12822378/9cf192ec-cb1c-11e5-8863-d9f7b4fc8c2f.jpg)

**Comment by shin-** [comment]
:clap:

**Comment by jfrazelle** [comment]
:confetti_ball:

**Comment by calavera** [comment]
we got plenty in the last 4 days. I'm closing this issue as FIXED. Thanks for reaching out.
