### ISSUE TITLE
Windows installation guide should mention that 64bit Windows is required.

### ISSUE THREAD

**Issue by friism** [docker/docker#20012]
* This is the relevant doc: https://docs.docker.com/engine/installation/windows/

People get confused when Toolbox doesn't install on 32bit Windows:
 * https://github.com/docker/docker/issues/136
 * https://github.com/docker/docker/issues/20004

There's assorted work to either [get 32bit version going](https://github.com/StefanScherer/boot2docker/pull/1) or to run 64bit Linux guest on 32bit Windows host. This should work, according [to Virtualbox docs](https://www.virtualbox.org/manual/ch03.html).

**Comment by thaJeztah** [comment]
@friism the docs mention it in [the requirements](https://docs.docker.com/engine/installation/windows/#requirements);

> To run Docker, your machine must have a 64-bit operating system running Windows 7 or higher.

Note that #136 is an issue from 2013, and is about Docker on Linux, not Windows

**Comment by friism** [comment]
@thaJeztah ah, I guess that went out yesterday with the 1.10 update?

Thanks.

**Comment by thaJeztah** [comment]
@friism I think so, yes. Thanks for the catch though!
