### ISSUE TITLE
docker container port not reachable via macos

### ISSUE THREAD

**Issue by schandrac** [docker/docker#20016]
Hi, I am trying to get connectivity from host to docker container running node-app working.

1. Exposed port in docker file and mapped that port using docker run
docker run --name beemgr_node3 --link beecomput-redis:redis -d -**p 8001:8001 -p 8000:8000** -w /usr/src/beemgr/js/ 59d388eb3d33  node <program>

2. Obtained Ip address using
 docker-machine ip default
192.168.99.100

3. http://192.168.99.100:8000 or http://192.168.99.100:8001 returns connection refused
curl -i 192.168.99.100:8000
curl: (7) Failed to connect to 192.168.99.100 port 8000: Connection refused
curl -i 192.168.99.100:8001
curl: (7) Failed to connect to 192.168.99.100 port 8001: Connection refused

4. Ensure that node app returns http response on same ports, if not run inside container.

Any thing I might be missing? 

ONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                              NAMES
9aeed3369eef        59d388eb3d33        "node beemgr_main.js"    14 minutes ago      Up 14 minutes       0.0.0.0:8000-8001->8000-8001/tcp   beemgr_node3
7b908f91a453        redis               "/entrypoint.sh redis"   About an hour ago   Up About an hour    6379/tcp                           beecomput-redis

> docker inspect 9aeed3369eef
[
{
    "Id": "9aeed3369eef1b4993dfa02b8942677671c19d764fd5c63038846331e3cb2365",
    "Created": "2016-02-05T01:15:58.15936759Z",
    "Path": "node",
    "Args": [
        "beemgr_main.js"
    ],
    "State": {
        "Status": "running",
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 9982,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2016-02-05T01:15:58.329074584Z",
        "FinishedAt": "0001-01-01T00:00:00Z"
    },
    "Image": "59d388eb3d3369ddaa67535b47c54814b9000baa310409b3d18d64ebaf445ab8",
    "ResolvConfPath": "/mnt/sda1/var/lib/docker/containers/9aeed3369eef1b4993dfa02b8942677671c19d764fd5c63038846331e3cb2365/resolv.conf",
    "HostnamePath": "/mnt/sda1/var/lib/docker/containers/9aeed3369eef1b4993dfa02b8942677671c19d764fd5c63038846331e3cb2365/hostname",
    "HostsPath": "/mnt/sda1/var/lib/docker/containers/9aeed3369eef1b4993dfa02b8942677671c19d764fd5c63038846331e3cb2365/hosts",
    "LogPath": "/mnt/sda1/var/lib/docker/containers/9aeed3369eef1b4993dfa02b8942677671c19d764fd5c63038846331e3cb2365/9aeed3369eef1b4993dfa02b8942677671c19d764fd5c63038846331e3cb2365-json.log",
    "Name": "/beemgr_node3",
    "RestartCount": 0,
    "Driver": "aufs",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "AppArmorProfile": "",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": null,
        "ContainerIDFile": "",
        "LxcConf": [],
        "Memory": 0,
        "MemoryReservation": 0,
        "MemorySwap": 0,
        "KernelMemory": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
        "MemorySwappiness": -1,
        "Privileged": false,
        "PortBindings": {
            "8000/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "8000"
                }
            ],
            "8001/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "8001"
                }
            ]
        },
        "Links": [
            "/beecomput-redis:/beemgr_node3/redis"
        ],
        "PublishAllPorts": false,
        "Dns": [],
        "DnsOptions": [],
        "DnsSearch": [],
        "ExtraHosts": null,
        "VolumesFrom": null,
        "Devices": [],
        "NetworkMode": "default",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "GroupAdd": null,
        "RestartPolicy": {
            "Name": "no",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
        "CgroupParent": "",
        "ConsoleSize": [
            0,
            0
        ],
        "VolumeDriver": ""
    },
    "GraphDriver": {
        "Name": "aufs",
        "Data": null
    },
    "Mounts": [],
    "Config": {
        "Hostname": "9aeed3369eef",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": {
            "8000/tcp": {},
            "8001/tcp": {}
        },
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "NPM_CONFIG_LOGLEVEL=info",
            "NODE_VERSION=4.2.6"
        ],
        "Cmd": [
            "node",
            "beemgr_main.js"
        ],
        "Image": "59d388eb3d33",
        "Volumes": null,
        "WorkingDir": "/usr/src/beemgr/js",
        "Entrypoint": null,
        "OnBuild": null,
        "Labels": {},
        "StopSignal": "SIGTERM"
    },
    "NetworkSettings": {
        "Bridge": "",
        "SandboxID": "69646495c2c055ef6878f52e8196245b0654edc9c97bd768ffe2438111eb0c7d",
        "HairpinMode": false,
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "Ports": {
            "8000/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "8000"
                }
            ],
            "8001/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "8001"
                }
            ]
        },
        "SandboxKey": "/var/run/docker/netns/69646495c2c0",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null,
        "EndpointID": "e701b11f30846bde3751e062d5acb34374fbfdbd6b2f5b8993c5f27961f74e26",
        "Gateway": "172.17.0.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "172.17.0.2",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "MacAddress": "02:42:ac:11:00:02",
        "Networks": {
            "bridge": {
                "EndpointID": "e701b11f30846bde3751e062d5acb34374fbfdbd6b2f5b8993c5f27961f74e26",
                "Gateway": "172.17.0.1",
                "IPAddress": "172.17.0.2",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "MacAddress": "02:42:ac:11:00:02"
            }
        }
    }
}
]

**Comment by schandrac** [comment]
Description of problem:
docker container port not reachable via mac host

`docker version`:
cker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64


`docker info`:
docker info
Containers: 77
Images: 163
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 317
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: beecompute-dev
ID: 3IPM:ERGS:FOJM:RKZH:NTSR:HNEF:SPYO:U5BX:TFMM:S6L6:5UOZ:ZM5T
Debug mode (server): true
 File Descriptors: 22
 Goroutines: 38
 System Time: 2016-02-05T02:50:46.520493262Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox


`uname -a`:
darwin MacBook-Pro.local 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64

Environment details (AWS, VirtualBox, physical, etc.):
virtualbox

How reproducible:


Steps to Reproduce:
1. Exposed port in docker file and mapped that port using docker run
docker run --name beemgr_node3 --link beecomput-redis:redis -d -p 8001:8001 -p 8000:8000 -w /usr/src/beemgr/js/ 59d388eb3d33 node

2. Obtained Ip address using
docker-machine ip default
192.168.99.100

3. http://192.168.99.100:8000 or http://192.168.99.100:8001 returns connection refused
curl -i 192.168.99.100:8000
curl: (7) Failed to connect to 192.168.99.100 port 8000: Connection refused
curl -i 192.168.99.100:8001
curl: (7) Failed to connect to 192.168.99.100 port 8001: Connection refused

Ensure that node app returns http response on same ports, if not run inside container.


Actual Results:
curl -i 192.168.99.100:8000
curl: (7) Failed to connect to 192.168.99.100 port 8000: Connection refused
curl -i 192.168.99.100:8001
curl: (7) Failed to connect to 192.168.99.100 port 8001: Connection refused

Expected Results:
Expecting node server inside container to return http response. logs on node server indicate that the http req never reaches the node server

Additional info:

docker inspect 9aeed3369eef
[
{
"Id": "9aeed3369eef1b4993dfa02b8942677671c19d764fd5c63038846331e3cb2365",
"Created": "2016-02-05T01:15:58.15936759Z",
"Path": "node",
"Args": [
"beemgr_main.js"
],
"State": {
"Status": "running",
"Running": true,
"Paused": false,
"Restarting": false,
"OOMKilled": false,
"Dead": false,
"Pid": 9982,
"ExitCode": 0,
"Error": "",
"StartedAt": "2016-02-05T01:15:58.329074584Z",
"FinishedAt": "0001-01-01T00:00:00Z"
},
"Image": "59d388eb3d3369ddaa67535b47c54814b9000baa310409b3d18d64ebaf445ab8",
"ResolvConfPath": "/mnt/sda1/var/lib/docker/containers/9aeed3369eef1b4993dfa02b8942677671c19d764fd5c63038846331e3cb2365/resolv.conf",
"HostnamePath": "/mnt/sda1/var/lib/docker/containers/9aeed3369eef1b4993dfa02b8942677671c19d764fd5c63038846331e3cb2365/hostname",
"HostsPath": "/mnt/sda1/var/lib/docker/containers/9aeed3369eef1b4993dfa02b8942677671c19d764fd5c63038846331e3cb2365/hosts",
"LogPath": "/mnt/sda1/var/lib/docker/containers/9aeed3369eef1b4993dfa02b8942677671c19d764fd5c63038846331e3cb2365/9aeed3369eef1b4993dfa02b8942677671c19d764fd5c63038846331e3cb2365-json.log",
"Name": "/beemgr_node3",
"RestartCount": 0,
"Driver": "aufs",
"ExecDriver": "native-0.2",
"MountLabel": "",
"ProcessLabel": "",
"AppArmorProfile": "",
"ExecIDs": null,
"HostConfig": {
"Binds": null,
"ContainerIDFile": "",
"LxcConf": [],
"Memory": 0,
"MemoryReservation": 0,
"MemorySwap": 0,
"KernelMemory": 0,
"CpuShares": 0,
"CpuPeriod": 0,
"CpusetCpus": "",
"CpusetMems": "",
"CpuQuota": 0,
"BlkioWeight": 0,
"OomKillDisable": false,
"MemorySwappiness": -1,
"Privileged": false,
"PortBindings": {
"8000/tcp": [
{
"HostIp": "",
"HostPort": "8000"
}
],
"8001/tcp": [
{
"HostIp": "",
"HostPort": "8001"
}
]
},
"Links": [
"/beecomput-redis:/beemgr_node3/redis"
],
"PublishAllPorts": false,
"Dns": [],
"DnsOptions": [],
"DnsSearch": [],
"ExtraHosts": null,
"VolumesFrom": null,
"Devices": [],
"NetworkMode": "default",
"IpcMode": "",
"PidMode": "",
"UTSMode": "",
"CapAdd": null,
"CapDrop": null,
"GroupAdd": null,
"RestartPolicy": {
"Name": "no",
"MaximumRetryCount": 0
},
"SecurityOpt": null,
"ReadonlyRootfs": false,
"Ulimits": null,
"LogConfig": {
"Type": "json-file",
"Config": {}
},
"CgroupParent": "",
"ConsoleSize": [
0,
0
],
"VolumeDriver": ""
},
"GraphDriver": {
"Name": "aufs",
"Data": null
},
"Mounts": [],
"Config": {
"Hostname": "9aeed3369eef",
"Domainname": "",
"User": "",
"AttachStdin": false,
"AttachStdout": false,
"AttachStderr": false,
"ExposedPorts": {
"8000/tcp": {},
"8001/tcp": {}
},
"Tty": false,
"OpenStdin": false,
"StdinOnce": false,
"Env": [
"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
"NPM_CONFIG_LOGLEVEL=info",
"NODE_VERSION=4.2.6"
],
"Cmd": [
"node",
"beemgr_main.js"
],
"Image": "59d388eb3d33",
"Volumes": null,
"WorkingDir": "/usr/src/beemgr/js",
"Entrypoint": null,
"OnBuild": null,
"Labels": {},
"StopSignal": "SIGTERM"
},
"NetworkSettings": {
"Bridge": "",
"SandboxID": "69646495c2c055ef6878f52e8196245b0654edc9c97bd768ffe2438111eb0c7d",
"HairpinMode": false,
"LinkLocalIPv6Address": "",
"LinkLocalIPv6PrefixLen": 0,
"Ports": {
"8000/tcp": [
{
"HostIp": "0.0.0.0",
"HostPort": "8000"
}
],
"8001/tcp": [
{
"HostIp": "0.0.0.0",
"HostPort": "8001"
}
]
},
"SandboxKey": "/var/run/docker/netns/69646495c2c0",
"SecondaryIPAddresses": null,
"SecondaryIPv6Addresses": null,
"EndpointID": "e701b11f30846bde3751e062d5acb34374fbfdbd6b2f5b8993c5f27961f74e26",
"Gateway": "172.17.0.1",
"GlobalIPv6Address": "",
"GlobalIPv6PrefixLen": 0,
"IPAddress": "172.17.0.2",
"IPPrefixLen": 16,
"IPv6Gateway": "",
"MacAddress": "02:42:ac:11:00:02",
"Networks": {
"bridge": {
"EndpointID": "e701b11f30846bde3751e062d5acb34374fbfdbd6b2f5b8993c5f27961f74e26",
"Gateway": "172.17.0.1",
"IPAddress": "172.17.0.2",
"IPPrefixLen": 16,
"IPv6Gateway": "",
"GlobalIPv6Address": "",
"GlobalIPv6PrefixLen": 0,
"MacAddress": "02:42:ac:11:00:02"
}
}
}
}
]

**Comment by thaJeztah** [comment]
Is the application in the container listening to all ip-addresses, and not just 127.0.0.1? What happens if you run, for example, `docker run -d -p 8001:80 nginx` and try to connect? If that works, I suspect it's something with the container.

Given that the docker inspect output shows that the ports are correctly published, I suspect this is not a docker bug. I'll close this issue, but feel free to continue the discussion.

**Comment by schandrac** [comment]
Thanks for response. 
1. My app is listening for all ip addresses

2. The issue is not resolved by using ngnix:

docker run -d -p 8001:80 nginx
96dfc7b65e7cbb61c5c4b147a3b64d2711a35040db9cb24644e21484293d9d0b
Santoshs-MacBook-Pro:beecomputing santosh$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                           NAMES
96dfc7b65e7c        nginx               "nginx -g 'daemon off"   15 seconds ago      Up 14 seconds       443/tcp, 0.0.0.0:8001->80/tcp   nostalgic_meitner

I got same error: ERR_CONNECTION_REFUSED
Hide details

The issue gets resolved (workaround) is to add explicit port forwarding rules in virtualbox 
TCP (host)127.0.0.1 8001 ->  (guest) 8001

**Comment by thaJeztah** [comment]
do you get the same issue on a newly created VM? Sounds like a docker-machine / toolbox issue otherwise

**Comment by wesleyvicthor** [comment]
@schandrac @thaJeztah I got the same error. cant connect properly to the ports exposed. any tip for a fix ?

**Comment by schandrac** [comment]
@wesleyvicthor  The workaround is to explicitly configure port forwarding rules in virtualbox config.
Go to settings -> network -> port forwarding. Add one rule for each port you want to be forwarded from host to guest OS.
