### ISSUE TITLE
lxc-docker to docker-engine upgrade on 1.10 is causing docker to hang on trusty

### ISSUE THREAD

**Issue by SamSaffron** [docker/docker#20021]
Upgrading the docker from 1.0.9 in trusty at `deb https://get.docker.io/ubuntu docker main` to 1.10 in `deb https://apt.dockerproject.org/repo ubuntu-trusty main` is hanging for me. 

This seems to happen quite consistently on 3 upgrades I did today. 

In 1/3 installs a reboot made docker start working. 

In 2/3 I had to uninstall, rm -fr `/var/lib/docker` and then re-install.

**Comment by jeremyVignelles** [comment]
Similar issue here on linux mint 17.1 with `deb https://apt.dockerproject.org/repo ubuntu-trusty main` :

After `aptitude upgrade` that installed a new version of `docker-engine` (1.10.0-0~trusty), the docker commands stops working (freeze), and `iotop` shows high disk read usage (~ 100% of disk time) for `docker daemon`, making my computer quite unusable.
My RAM level is normal.

Previous versions (1.9.1-0~trusty I think), worked just fine, and I didn't notice any freeze.

I tried a `service docker stop`, which stopped the service correctly and released my hard drive, but `service docker start` restarts the IO traffic.

Tried a restart without luck, I will try downgrading my docker-engine back to 1.9.1-0 to see if this fixes my issue

**Comment by rqclima** [comment]
I have the same problem. On Linux Mint 17.2, after I updated docker today, CPU usage is very, very high. Restart didn't work, I stopped the service and going to downgrade...

**Comment by SamSaffron** [comment]
Feel free to close, I guess this is just how it goes, if you upgrade 1.9 to
1.10 on digital ocean and have lots of images expect a reasonably long
outage

**Comment by vdemeester** [comment]
@SamSaffron @rqclima @jeremyVignelles There is a reason for the high io/cpu, it's documented there : https://docs.docker.com/engine/migration/.

**Comment by cpuguy83** [comment]
Yes, this is most likely due to the migration to content addressable storage.
Docker 1.10 will block until all images have been migrated (or skipped due to an error).
The above link provides a stand-alone migration tool that can be run against live daemons prior to upgrade to pre-process these images.

**Comment by yorele** [comment]
@cpuguy83 if the daemon is upgraded on one machine, are the images useable on another which has not been upgraded? 
I just tried updating my build machine. I don't want to spend hours waiting for images to migrate to realize they won't work on my hosts.

Thanks.

**Comment by cpuguy83** [comment]
@yorele The images themselves are not changed, the migration is only computing checksums for all the images (and can be run asynchronously via a separate tool, even in a container)

**Comment by yorele** [comment]
@cpuguy83 Great, thanks...
