### ISSUE TITLE
recover key-value-store informations for docker networks

### ISSUE THREAD

**Issue by CarloBlohm** [docker/docker#20024]
**Description of problem/feature:**
If the key-value-store is deleted, all network informations are gone. Only the default networks will be available.
I created a network in docker with the overlay driver and startet my containers. They are working even if the key-value-store is started from scratch (no data inside). 
But I can't setup a new network or see the old onces.

In Docker Swarm the key-value-store can be started from scratch and it is working again (after a short time).

Environment details (AWS, VirtualBox, physical, etc.):
- Mutli-Host-Networking
- docker network
- consul

How reproducible:
Steps to Reproduce:
1. install key-value-store (consul)
2. configure docker against it
3. create overlay network (docker network -d overlay test1)
4. start two or more containers with the network test1 (... --net test1 ...)
5. ping or do some other network stuff
6. let all running but crash the key-value-store (consul) and delete every data from it (like: docker rm -f)
7. start key-value-store from scratch (no data inside)
8. problem:
- now you can not add a new network (docker network create -d overlay test2 -> hangs almost for ever) 
- only the default networks are listed (docker network ls)

**Hoped-for results:**
- it would be awesome if docker can recover the network from the active containers to make it possible to add more containers to these networks
- do not let docker network create crash, now it waits like for ever

**Comment by cpuguy83** [comment]
We cannot recover networks stored in the k/v store if you delete the k/v store.
Assuming that any sort of local state is accurate would be wrong.

However, I agree we do need to handle the case where the k/v store has had an issue (or been blown away, whatever).
Not that we can restore them, but being able to detect that something is awry and notify the user.

**Comment by LK4D4** [comment]
@mrjana @aboch @sanimej is this still actual?

**Comment by aboch** [comment]
In kv-store based multihost networking, a kv-store is an integral part of the solution. The system cannot work without it. 

Based on that and given the new swarm-mode is now availbale, I do not think we are going to look into making changes to address this feature request on the kv-store based multihost networking.

**Comment by LK4D4** [comment]
Okay, I'm closing this because swarm-mode is way to do networking now.
