### ISSUE TITLE
docker links entries in /etc/hosts don't add IPv6 addresses of containers

### ISSUE THREAD

**Issue by JonasT** [docker/docker#20027]
Generated entries in /etc/hosts from docker links don't add IPv6 addresses of containers even if the docker daemon runs with IPv6 enabled.
I tested this in:
```
Docker version 1.9.1, build a34a1d5
```
This should be fixed as soon as possible to improve docker's still somewhat poor IPv6 support.

**Comment by cpuguy83** [comment]
We don't use /etc/hosts anymore, but I agree, the DNS records should include ip6 addresses.

**Comment by aboch** [comment]
I think this is a duplicate of #13228

**Comment by cpuguy83** [comment]
Agreed, closing this one.
Thanks @JonasT
