### ISSUE TITLE
docker run: imagename without tag rejected if colon is present

### ISSUE THREAD

**Issue by ctammes** [docker/docker#20023]
Version:      1.10.0
 API version:  1.22

Containers: 10
 Running: 7
 Paused: 0
 Stopped: 3
Images: 173
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 224
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-63-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.463 GiB
Name: vagrant-ubuntu-trusty-64
ID: FDI3:7ILC:3KVF:NP6T:UD5F:5GMF:3PWK:ZEKZ:QZA2:6C6B:DO47:46MR
WARNING: No swap limit support

1) issue docker run command with image like "repo/imagename:" (ending with colon)
2) error:  "docker: Error parsing reference: "cgm_nl/cgmherhaal:" is not a valid repository/tag."

Expected:
"repo/imagename:" was accepted before v1.10

Problem:
breaks present scripts

Solution: 
add the tag or remove the colon.

**Comment by stevvooe** [comment]
Image names with empty tags and a colon are invalid. Earlier versions that allowed this were a bug. I would recommend fixing the script, as this may reflect a larger bug. In general, its recommended to specify a tag when automating deployments.

**Comment by runcom** [comment]
agree, this was definitely a bug :(

closing this as per @stevvooe comment above, feel free to comment here otherwise
