### ISSUE TITLE
Docker 1.91. : Environment variables of link not updated when a new IP is assigned

### ISSUE THREAD

**Issue by madsnotepad** [docker/docker#20020]
Following is the scenario
Start DB container db1 
Start App Server container with link on db1
Stop DB container db1
Start Web Server container 
Start DB container db1. Here the db1 is assigned a new IP from the previous start. /etc/hosts entries are updated with the new IP but the ENV variables created through link still point to old IP

**Comment by cpuguy83** [comment]
This is to be expected.
Environment variables of a running process cannot be changed except by that process itself.
To have the env vars updated you should restart the container.

**Comment by thaJeztah** [comment]
This is also documented here; https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/#important-notes-on-docker-environment-variables
