### ISSUE TITLE
Standardize default logging tag value

### ISSUE THREAD

**Issue by bobrik** [docker/docker#20033]
Prior discussion: https://github.com/docker/docker/pull/19564#discussion_r50802124

```
daemon/logger/fluentd/fluentd.go:   tag, err := loggerutils.ParseLogTag(ctx, "docker.{{.ID}}")
daemon/logger/gelf/gelf.go: tag, err := loggerutils.ParseLogTag(ctx, "")
daemon/logger/journald/journald.go: tag, err := loggerutils.ParseLogTag(ctx, "")
daemon/logger/splunk/splunk.go: tag, err := loggerutils.ParseLogTag(ctx, "{{.ID}}")
daemon/logger/syslog/syslog.go: tag, err := loggerutils.ParseLogTag(ctx, "{{.ID}}")
```

It seems like it's better to have a single default value for all loggers. Two options:

1. Make it empty. This could break some logging drivers that want mandatory tag (syslog?).
2. Make it some common value: `docker.{{.ID}}` or `{{.ID}}`.

**Comment by afinkenstadt** [comment]
👍  for `{{.ID}}`
