### ISSUE TITLE
storage options (docker volume create --opt) are not being passed to drivers

### ISSUE THREAD

**Issue by erikh** [docker/docker#20040]
Please fix

**Comment by cpuguy83** [comment]
@erikh Please upgrade your volume driver.
Also dup of #19983

**Comment by cpuguy83** [comment]
https://github.com/docker/docker/blob/master/docs/extend/plugins_volume.md

1.10 adds 2 new RPC calls for `List` and `Get`

**Comment by erikh** [comment]
I've already done this.

**Comment by cpuguy83** [comment]
You are hitting the fallback somehow, is `Get` responding with a 404?

**Comment by erikh** [comment]
Ok, I see what the problem was now. Thanks for responding + the help!

**Comment by erikh** [comment]
Yeah, that was it. I had it implemented, just didn't push it to the router yet. Thanks again.

**Comment by cpuguy83** [comment]
:tada:
