### ISSUE TITLE
syslog-address with tcp+tls protocol rejected by docker run

### ISSUE THREAD

**Issue by jbergknoff** [docker/docker#20042]
I see the following behavior trying to use the new tcp+tls transport for the syslog log driver:

```bash
$ docker run --rm --log-driver=syslog --log-opt syslog-address=tcp+tls://logs.papertrailapp.com:1234 alpine:3.3 echo hello world
docker: Error response from daemon: syslog-address should be in form proto://address, got tcp+tls://logs.papertrailapp.com:1234.
$ docker -v
Docker version 1.10.0, build 590d5108
```

It looks like the relevant code is here: [urlutil](https://github.com/docker/docker/blob/729c9a97822ebee2c978a322d37060454af6bc66/pkg/urlutil/urlutil.go#L14).

**Comment by thaJeztah** [comment]
This was added in https://github.com/docker/docker/pull/18998, looks indeed that  `tcp+tls` was added there, but the validation was not updated.

ping @calavera
