### ISSUE TITLE
Allow uppercase characters in image reference hostname

### ISSUE THREAD

**Issue by aaronlehmann** [docker/docker#20056]
Docker 1.9 allowed uppercase characters in registry hostnames. Docker 1.10 does not. This should be fixed, because otherwise there may be images that can't be accessed because their names don't parse correctly under Docker 1.10.

Note that this only applies to hostnames, not remote image names. Previous versions also prohibited uppercase letters after the hostname, but Docker 1.10 extends this to the hostname itself.

Example:

With 1.9:

```
# docker tag registry:2.2.1 OldRegistry:2.2.1
repository name component must match "[a-z0-9](?:-*[a-z0-9])*(?:[._][a-z0-9](?:-*[a-z0-9])*)*"
# docker tag registry:2.2.1 SomeHostname:8080/registry:2.2.1
[success]
```

With 1.10:

```
# docker tag wordpress WordpressImage
Error parsing reference: "WordpressImage" is not a valid repository/tag
# docker tag wordpress SomeHostname:8080/wordpress     
Error parsing reference: "SomeHostname:8080/wordpress" is not a valid repository/tag
```

See https://github.com/docker/distribution/issues/1433

**Comment by calavera** [comment]
Fixed by #20175.
