### ISSUE TITLE
Not open source remote api clients

### ISSUE THREAD

**Issue by dcylabs** [docker/docker#20065]
Does not open source remote api clients can goes in /docs/reference/api/remote_api_client_libraries.md ? 

I mean I would like to add a play store link in it, but not sure if it is the right place.

**Comment by unclejack** [comment]
@dcylabs You are welcome to send a pull request to add an open source client library to the documentation. An open source Android application could be added using the following data for the fields: "Java (Android) mobile app | <app name> | <repository url> | Active".
