### ISSUE TITLE
Unable to strace in container with docker 1.10

### ISSUE THREAD

**Issue by tmds** [docker/docker#20064]
Using strace in a container gives me an 'Operation not permitted' error.

`strace: test_ptrace_setoptions_followfork: PTRACE_TRACEME doesn't work: Operation not permitted`

**Comment by tmds** [comment]
Not a bug, it's a feature!
https://blog.docker.com/2016/02/docker-engine-1-10-security/

**Comment by krzkaczor** [comment]
To turn off security features use: 

`docker run --security-opt seccomp:unconfined ...`

**Comment by SunnySmilez** [comment]
docker run -t -i --cap_add=ALL  container_name /bin/bash
or
docker run -t -i --privileged container_name /bin/bash
