### ISSUE TITLE
docker in docker don't re-use the device-write-bps or device-read-bps parameters from parent docker

### ISSUE THREAD

**Issue by moylop260** [docker/docker#20077]
Steps:

1. Download a docker image with docker 1.10 server installed: 
1. Create a container docker-in-docker with device-write-bps and device-read-bps parameters.
   - `$(serv-phy): docker run --privileged -v /home/mydocker-lib:/var/lib/docker --device-write-bps=/dev/sda:10mb --device-read-bps=/dev/sda:10mb -p 12376:2376 --name=dkr-in-dkr -d my-docker-server:1.10`
1. Run IO tests two times
 - `$(serv-phy): docker exec -it dkr-in-dkr /bin/sh`
 - `#(dkr-in-dkr): time $(dd if=/dev/zero of=testfile0 bs=1000 count=100000 && sync)` <- Result: real 0m0.284s
 - `#(dkr-in-dkr): time $(dd if=/dev/zero of=testfile0 bs=1000 count=100000 && sync)` <- Result: real 0m10.951s
1. Create a container into of `dkr-in-dkr` container
 - `#(dkr-in-dkr): docker run -it --name=subcontainer ubuntu:12.04 bash`
1. Run IO tests two times
 - `##(subcontainer): time $(dd if=/dev/zero of=testfile0 bs=1000 count=100000 && sync)` <- Result: real 0m0.284s
 - `##(subcontainer): time $(dd if=/dev/zero of=testfile0 bs=1000 count=100000 && sync)` <- Result: real 0m0.284s

Expected:
 - That `##(subcontainer)` in the second time running IO test show: `Result: real 0m10.951s` inheriting `device-read-bps` and `device-write-bps` from parent container `#(dkr-in-dkr)`

Saw:
 - That `##(subcontainer)` created in `#(dkr-in-dkr)` don't have restriction of I/O

**Comment by LK4D4** [comment]
@Mashimiao Could you try to answer this question? Thanks!

**Comment by Mashimiao** [comment]
@moylop260  can you support more information by `docker version` and `docker info`

**Comment by thaJeztah** [comment]
Closing as we didn't receive more information, but happy to reopen once provided
