### ISSUE TITLE
Docker toolbox - STATUS_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by matt32106** [docker/docker#20076]
Win7 x64
I installed the program DockerToolbox-1.10.0.exe. No error displayed.
I then launched the Docker Quickstart Terminal for the first time by clicking on the desktop icon.
I get a crash:  
```
Exception: STATUS_ACCESS_VIOLATION at rip=0018007D250
rax=00000000002F0000 rbx=0000000600010448 rcx=000000018030F618
rdx=0000000600010448 rsi=0000000600010448 rdi=000000018030F618
r8 =0000000000000001 r9 =0000000600010660 r10=0000000000230000
r11=00000005FCB4709C r12=0000000000000001 r13=0000000600010448
r14=0000000000000000 r15=0000000000000000
rbp=000000000022C9B0 rsp=000000000022C8B0
program=C:\Program Files\Git\usr\bin\clear.exe, pid 7100, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
0000022C9B0  0018007D250 (001800D1A97, 0000022CA20, 00000000000, 00000000000)
0000022C9B0  00180148C28 (001800D1AAD, 0018031118D, 005FCB45890, 0000022CAC8)
0000022CAC8  0018012681B (001800D1AAD, 0018031118D, 005FCB45890, 0000022CAC8)
0000022CAC8  005FCB4709C (0018012681B, 0018031118D, 00000000000, 006000103D0)
0000022CAC8  005FCB47182 (00000000000, 00180046630, 001801C4C37, 0000022CB60)
0000022CAC8  005FCB3E03F (0000022CBC0, 00000000000, 001800469EA, 04900000000)
0000022CBC0  005FCB3E23A (0000022CBC0, 00000000000, 00000000000, 0000022CB60)
0000022CBC0  00100401799 (00000000020, FF0700010302FF00, 001800482CF, 0000022D68
0)
0000022CBC0  00180048340 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  0018004603C (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  001800460D4 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100401181 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100401010 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  000777059ED (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  0007799B831 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
Looks like something went wrong... Press any key to continue...
```

Other subsequent tries give the same message.

Please see attached screenshot for details (i couldn't OCR it sorry).
[https://dl.dropboxusercontent.com/u/1307844/2016-02-06%2017_27_05-Docker%20Quickstart%20Terminal.png](url)

C:\Users\xyz>docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:18:11 2016
 OS/Arch:      windows/amd64
An error occurred trying to connect: Get http://127.0.0.1:2375/v1.22/version: dial tcp 127.0.0.1:2375: connectex: No connection could be made because the target machine actively refused it.

C:\Users\xyz>docker info
An error occurred trying to connect: Get http://127.0.0.1:2375/v1.22/info: dial tcp 127.0.0.1:2375: connectex: No connection could be made because the target machine actively refused it.

**Comment by thaJeztah** [comment]
Thanks for reporting @matt32106, unfortunately this is the wrong issue tracker because toolbox is in a separate repository; can you open this in that issue tracker? https://github.com/docker/toolbox/issues
