### ISSUE TITLE
Not able to invoke Remote API with curl - OSStatus -25299

### ISSUE THREAD

**Issue by arun-gupta** [docker/docker#20085]
Trying to invoke Docker Remote API using curl as explained at:

https://docs.docker.com/engine/reference/api/docker_remote_api/

Here is the exact command used:

`curl --insecure --cert $DOCKER_CERT_PATH/cert.pem --key $DOCKER_CERT_PATH/key.pem https://192.168.99.100:2376/images/json`

This is giving the error:

`curl: (58) SSL: Can't load the certificate "/Users/arungupta/.docker/machine/machines/couchbase/cert.pem" and its private key: OSStatus -25299`

Curl version is:

`curl --version
curl 7.37.1 (x86_64-apple-darwin14.0) libcurl/7.37.1 SecureTransport zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IPv6 Largefile NTLM NTLM_WB SSL libz`

Could it be related to http://superuser.com/questions/851604/mac-os-x-yosemite-and-client-ssl-certificates?

This could also be related to https://github.com/boot2docker/boot2docker/issues/573.

Possible fix in http://blog.bananacoding.com/blog/how-to-connect-to-the-docker-remote-api-using-kitematic-and-boot2docker-for-mac.

**Comment by arun-gupta** [comment]
Could be related to https://github.com/docker/docker/issues/16107

**Comment by arun-gupta** [comment]
Here is an updated command that's giving the same error:

`curl https://192.168.99.100:2376/images/json --cert $DOCKER_CERT_PATH/cert.pem --key $DOCKER_CERT_PATH/key.pem --cacert $DOCKER_CERT_PATH/ca.pem
curl: (58) SSL: Can't load the certificate "/Users/arungupta/.docker/machine/machines/couchbase/cert.pem" and its private key: OSStatus -25299`

This is documented at: https://docs.docker.com/engine/security/https/#connecting-to-the-secure-docker-port-using-curl

**Comment by thaJeztah** [comment]
Sounds related yes, I think this is an issue with curl on OS X; did you manage to get it working with the workarounds mentioned in those issues?

**Comment by ehazlett** [comment]
@arun-gupta I'm going to close this as it seems there is a workaround.  If you continue to have issues please open a new issue.  Thanks!
