### ISSUE TITLE
Docker ps doesn't show when running the command inside script called from systemctl

### ISSUE THREAD

**Issue by infosatheesh2020** [docker/docker#20084]
I run docker on Fedora 23 and version below:

[root@bigboy ~]# cat /etc/redhat-release 
Fedora release 23 (Twenty Three)
[root@bigboy ~]# docker version
Client:
 Version:      1.8.2-fc23
 API version:  1.20
 Package Version: docker-1.8.2-10.git28c300f.fc23.x86_64
 Go version:   go1.5.1
 Git commit:   cc2d489-dirty
 Built:        Tue Nov  3 06:41:23 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2-fc23
 API version:  1.20
 Package Version: 
 Go version:   go1.5.1
 Git commit:   cc2d489-dirty
 Built:        Tue Nov  3 06:41:23 UTC 2015
 OS/Arch:      linux/amd64
[root@bigboy ~]# 
[root@bigboy ~]# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
713149d4cb0f        debian              "/bin/bash"         2 hours ago         Up 2 hours                              testcontainer
53640aa30418        debian              "/bin/bash"         2 days ago          Up 2 days                               compassionate_aryabhata
[root@bigboy ~]# 

I have a script  /usr/local/bin/dockerps.sh which is below:
set -x
docker ps

Now, I call the script from systemctl service and the service is below:
[root@bigboy ~]# cat /usr/lib/systemd/system/dockerps.service
[Unit]
Description=Run docker ps from service
After=docker.service
Requires=docker.service

[Service]
User=root
ExecStart=/usr/local/bin/dockerps.sh
Restart=on-failure

[Install]
WantedBy=multi-user.target

Now, I am getting the error as below when i start the service

Feb 07 05:14:12 bigboy systemd[1]: Started Run docker ps from service.
Feb 07 05:14:12 bigboy systemd[1]: Starting Run docker ps from service...
Feb 07 05:14:12 bigboy dockerps.sh[18479]: ++ docker ps
Feb 07 05:14:12 bigboy dockerps.sh[18479]: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.20/containers/json: EOF.
Feb 07 05:14:12 bigboy dockerps.sh[18479]: * Are you trying to connect to a TLS-enabled daemon without TLS?
Feb 07 05:14:12 bigboy dockerps.sh[18479]: * Is your docker daemon up and running?

But the same script which i run manually works. Is there any env setting missing?

**Comment by cpuguy83** [comment]
Something about the env or the user doesn't have access to the docker socket.
