### ISSUE TITLE
[question] Is posible define range of port to use in expose `-P`?

### ISSUE THREAD

**Issue by moylop260** [docker/docker#20091]
Is posible something to limit the range of ports to expose with `-P` parameter, like as:
`docker daemon --range-ports=2000-2099...`
`docker run -P...` <- ports used between 2000 and 2099
or
`docker daemon...`
`docker run -P --range-ports=2000-2099...` <- ports used between 2000 and 2099`

**Comment by ozlerhakan** [comment]
hi @moylop260, as far as I know, you can define a range using `-p` and expose those ports with `-P`, here is the doc for [it](https://docs.docker.com/engine/reference/run/#expose-incoming-ports)

**Comment by moylop260** [comment]
With `-p` lowercase, I can use a range of ports.
But my question is with `P` uppercase, I need use a range of port allowed to expose.

Imagine next Dockerfile
```
FROM ubuntu:14.04
EXPOSE 22-24
```

I don't want to define each 22 to 500 ports, but I need force that use just: 2000-4000 host port.
`docker run --name=container1 -Pd --range-ports=2000-4000 myimage`
`docker ps` <- Result: 2001:22, 2005:23, 4000:24

`docker run --name=container2 -Pd --range-ports=2000-4000 myimage`
`docker ps` <- Result: 2008:22, 2010:23, 3999:24

But never use port >=4001 or port <=1999.

Is is possible?

**Comment by ozlerhakan** [comment]
I see, but this could be a workaround I only think of:  `$ docker run .... -P -p 2000-4000:22 -p 2000-4000:23 -p 2000-4000:24 ....`

**Comment by moylop260** [comment]
Thank you @ozlerhakan
I will try it

**Comment by moylop260** [comment]
@ozlerhakan 
This worked for me:
`$ docker run .... -p 2000-4000:22 -p 2000-4000:23 -p 2000-4000:24 ....`
Thank you again.

A future feature, maybe could be that we can define a range.
`docker run ... -P 2000-4000...`

By Now is will close this question.
