### ISSUE TITLE
Add a forbid mount host volume option to docker daemon

### ISSUE THREAD

**Issue by mdevlamynck** [docker/docker#20099]
As mounting any host folder in a container can be a security issue (as say mount /etc and mess with passwd and shadow), it would be nice to be able to forbid mounting host volume in a container as an option for the docker daemon.

Using data volume is most of the time enough, and this option would give a safer environment when non root users need to manage containers.

**Comment by thaJeztah** [comment]
Sounds like something that could be achieved through an authorization plugin; https://docs.docker.com/engine/extend/authorization/

**Comment by phemmer** [comment]
I don't think this type of feature would be a good idea as it encourages a false sense of security. Volume mounts are the easiest way to manipulate the host system, but not the only one.

**Comment by thaJeztah** [comment]
agreed

**Comment by cpuguy83** [comment]
Closing since this would be something to include as an authz plugin.
