### ISSUE TITLE
Mirror option is not finding images after 1.10

### ISSUE THREAD

**Issue by davidkarlsen** [docker/docker#20097]
Hi.

We have Sonatype Nexus 3 server acting as docker registry and mirror: https://support.sonatype.com/hc/en-us/articles/215781148-Nexus-Repository-Manager-3-0-Milestone-7-Release- running at https://servername:8085
It is setup so that we have a virtual "group repository" that federates several registries, two of which are:
-internal repo
-on-the-fly mirror/cache of dockerhub

The daemons are configured with the mirror option:
 --registry-mirror https://servername:8085 

Using docker 1.8.2 (working):

installed sw details:
-bash-4.2$ docker info
dContainers: 0
Images: 6
Storage Driver: btrfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-327.4.4.el7.x86_64
Operating System: Red Hat Enterprise Linux
CPUs: 2
Total Memory: 9.602 GiB
Name: jls-slave29
ID: 2IDF:FG2O:MBF2:NARP:YH6R:N6O4:V3CA:R5KG:6ALA:4TQI:22BA:IJUI
Debug mode (server): true
File Descriptors: 15
Goroutines: 23
System Time: 2016-02-08T08:51:25.339339439+01:00
EventsListeners: 0
Init SHA1: f7bb40c7220474256047ddbd63b447496387e4d2
Init Path: /usr/libexec/docker/dockerinit
Docker Root Dir: /var/lib/docker
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
-bash-4.2$ docker version
Client:
 Version:      1.8.2-el7
 API version:  1.20
 Package Version: docker-1.8.2-10.el7.x86_64
 Go version:   go1.4.2
 Git commit:   a01dc02/1.8.2
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2-el7
 API version:  1.20
 Package Version: 
 Go version:   go1.4.2
 Git commit:   a01dc02/1.8.2
 Built:        
 OS/Arch:      linux/amd64
-bash-4.2$ 

Having a docker-compose file with:
image: myInternalImagePrefix/myImage

it will be pulled (via the mirror) when I do a docker-compose pull.

However - when upgrading to 1.10 (and docker-compose 1.6.0) on my ubuntu box, this will no longer be found.
IF I however prefix the image with servername:8085:
image: servername:8085:myInternalImagePrefix/myImage 
it will be pulled on docker 1.10 - but not on the old docker 1.8.2

1.10 version details:
et2448@ubuntu:~$ docker info
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 24
Server Version: 1.10.0
Storage Driver: btrfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.32 GiB
Name: ubuntu
ID: Q5T2:MOE6:ZQ72:MWDU:EGBH:XHBW:XDZ7:XFSS:RP3Z:5TPF:AUP6:ZSOR
Debug mode (server): true
 File Descriptors: 10
 Goroutines: 31
 System Time: 2016-02-08T08:52:06.288959198+01:00
 EventsListeners: 0
 Init SHA1: e2f80f7797c61007e141f1b60f5b469775a8f712
 Init Path: /usr/lib/docker/dockerinit
 Docker Root Dir: /var/lib/docker
Username: davidkarlsen
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
et2448@ubuntu:~$ 

Steps to reproduce:
1. define the mirror option for the daemon
2. have the mirror serve internal and docker hub images
3. have an image in the internal repo myInternalImagePrefix/myImage:latest
4. have a compose file, with an image definition of myInternalImagePrefix/myImage:latest

Results received:
Will pull on 1.8.2
Will not find image on 1.10

Expected: 
Should still work on 1.10 as it is on 1.8.2

**Comment by thaJeztah** [comment]
Does this work with 1.9.1? Also do the daemon logs show anything useful?

Also; does the mirror successfully work with official images (e.g. is `docker pull ubuntu` successfully pulled from the mirror?)

Basically, if this only fails for pulling internal images, I'm wondering if this was actually supported, and if this relates to https://github.com/docker/docker/issues/18818

**Comment by davidkarlsen** [comment]
It worked on 1.9.1 yes - I forgot to add that.
It does not seem to successfully use the mirror-registry option because if I do netstat's there are no connections to the proxy, and if I tcpdump towards host registry-1.docker.io I see packets during a pull

**Comment by aaronlehmann** [comment]
I'm not able to reproduce this using the official Docker registry as a mirror. When I specify `--registry-mirror`, Docker 1.0 pulls from the specified mirror instead of Docker Hub. I do see that when the specified image doesn't exist on my mirror, Docker fails to pull from it and ends up pulling from Hub. Posting the daemon log running in debug mode (`-D`) may be helpful in diagnosing this.

**Comment by davidkarlsen** [comment]
Here it is (I just cancelled the pull)
[docker.log.txt](https://github.com/docker/docker/files/122301/docker.log.txt)

**Comment by tiborvass** [comment]
it seems like coming from a broken pipe error.

**Comment by davidkarlsen** [comment]
broken pipe?

**Comment by dmcgowan** [comment]
@davidkarlsen based on the logs it looks the mirror was attempted `Trying to pull elasticsearch from https://fsnexus.evry.com:8085/ v2 `  Unfortunately there is no debug logs indicating what failure caused it to be skipped. Is there any indication on the proxy server that a connection was made and the pull was attempted?

**Comment by aaronlehmann** [comment]
I'm still not able to reproduce this. I've tried a few configurations - with/without TLS, official images, non-official images, and so on.

For me, Docker 1.10 always attempts to pull from the mirror first, and only pulls from Hub if the mirror doesn't have the repository.

@davidkarlsen, you mentioned that you tcpdumped towards `registry-1.docker.io` and saw traffic. Did you also tcpdump traffic towards your mirror and confirm that no connection is made?

**Comment by aaronlehmann** [comment]
@davidkarlsen: One more question - do you know if the registry/mirror is using the v1 protocol or v2 protocol? Based on the documentation, it can be configured to support either. The daemon log from Docker 1.8 or 1.9 doing a successful pull would provide this information, and might also shed some light on what it's doing differently from 1.10.

**Comment by davidkarlsen** [comment]
I have dug a bit more in access logs, I see these two on the serverside:
```
139.107.164.5 - - [10/Feb/2016:00:24:15 +0100] "GET /v2/ HTTP/1.1" 401 113
139.107.164.5 - - [10/Feb/2016:00:24:15 +0100] "GET /v2/evryfs/oracle12c/manifests/latest HTTP/1.1" 401 -
```

Also, client side I see:
```
SC[37mDEBUESC[0m[3101] Trying to pull evryfs/oracle12c from https://fsnexus.evry.com:8085/ v2 <-- why the ending slash here??? 
ESC[37mDEBUESC[0m[3102] Trying to pull evryfs/oracle12c from https://registry-1.docker.io v2 

```

**Comment by davidkarlsen** [comment]
Here is log when I address the image fully qualified (prefixed with host and ip), and don't rely on the mirror finding it by itself:
```
ESC[37mDEBUESC[0m[3101] Calling POST /v1.22/images/create            
ESC[37mDEBUESC[0m[3101] POST /v1.22/images/create?fromImage=evryfs%2Foracle12c%3Alatest 
ESC[37mDEBUESC[0m[3101] hostDir: /etc/docker/certs.d/fsnexus.evry.com:8085 
ESC[37mDEBUESC[0m[3101] Trying to pull evryfs/oracle12c from https://fsnexus.evry.com:8085/ v2 
ESC[37mDEBUESC[0m[3102] Trying to pull evryfs/oracle12c from https://registry-1.docker.io v2 
ESC[37mDEBUESC[0m[3105] Increasing token expiration to: 0 seconds    
ESC[37mDEBUESC[0m[3106] Trying to pull evryfs/oracle12c from https://index.docker.io v1 
ESC[37mDEBUESC[0m[3106] hostDir: /etc/docker/certs.d/docker.io       
ESC[37mDEBUESC[0m[3106] [registry] Calling GET https://index.docker.io/v1/repositories/evryfs/oracle12c/images 
ESC[37mDEBUESC[0m[3106] Not continuing with error: Error: image evryfs/oracle12c not found 
ESC[37mDEBUESC[0m[3290] Calling GET /v1.22/images/json               
ESC[37mDEBUESC[0m[3290] GET /v1.22/images/json?filters=%7B%22dangling%22%3A%7B%22true%22%3Atrue%7D%7D 
ESC[37mDEBUESC[0m[3301] Calling POST /v1.22/images/create            
ESC[37mDEBUESC[0m[3301] POST /v1.22/images/create?fromImage=fsnexus.evry.com%3A8085%2Fevryfs%2Foracle%3Alatest 
ESC[37mDEBUESC[0m[3301] hostDir: /etc/docker/certs.d/fsnexus.evry.com:8085 
ESC[37mDEBUESC[0m[3301] hostDir: /etc/docker/certs.d/fsnexus.evry.com:8085 
ESC[37mDEBUESC[0m[3301] Trying to pull fsnexus.evry.com:8085/evryfs/oracle from https://fsnexus.evry.com:8085 v2 
ESC[37mDEBUESC[0m[3303] Trying to pull fsnexus.evry.com:8085/evryfs/oracle from https://fsnexus.evry.com:8085 v1 
ESC[37mDEBUESC[0m[3303] hostDir: /etc/docker/certs.d/fsnexus.evry.com:8085 
ESC[37mDEBUESC[0m[3303] attempting v2 ping for registry endpoint https://fsnexus.evry.com:8085/v2/ 
ESC[37mDEBUESC[0m[3303] [registry] Calling GET https://fsnexus.evry.com:8085/v1/repositories/evryfs/oracle/images 
ESC[37mDEBUESC[0m[3305] Not continuing with error: Error: image evryfs/oracle not found 
ESC[37mDEBUESC[0m[3318] Calling POST /v1.22/images/create            
ESC[37mDEBUESC[0m[3318] POST /v1.22/images/create?fromImage=fsnexus.evry.com%3A8085%2Fevryfs%2Foracle12c%3Alatest 
ESC[37mDEBUESC[0m[3318] hostDir: /etc/docker/certs.d/fsnexus.evry.com:8085 
ESC[37mDEBUESC[0m[3318] hostDir: /etc/docker/certs.d/fsnexus.evry.com:8085 
ESC[37mDEBUESC[0m[3318] Trying to pull fsnexus.evry.com:8085/evryfs/oracle12c from https://fsnexus.evry.com:8085 v2 
ESC[37mDEBUESC[0m[3318] Pulling ref from V2 registry: fsnexus.evry.com:8085/evryfs/oracle12c:latest 
ESC[37mDEBUESC[0m[3318] pulling blob "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" 
ESC[37mDEBUESC[0m[3318] pulling blob "sha256:cfa774c4de28156d392b1b75a76febcad3c1257ef0df1d1c50cd5add43c44a29" 
ESC[37mDEBUESC[0m[3318] pulling blob "sha256:d7ec68632efbec830591ed1415db23b06f2c50280c6d5c00475a044f2354e397" 
ESC[37mDEBUESC[0m[3318] Downloaded a3ed95caeb02 to tempfile /var/lib/docker/tmp/GetImageBlob730570261 
ESC[37mDEBUESC[0m[3318] pulling blob "sha256:53e0929f2be73af0b3340a603657938b1fc392badb3d7c2bf726a4e0f30cc579" 
ESC[37mDEBUESC[0m[3318] Start untar layer                            
ESC[37mDEBUESC[0m[3318] Untar time: 0.04859563s                      
ESC[37mDEBUESC[0m[3318] Applied tar sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef to ff5ee60b254a508f817f1684a41bfd6b6dda66540d5329d2de3316da0bd852f2, size: 0 
ESC[34mINFOESC[0m[3345] Pull session cancelled                       
ESC[37mDEBUESC[0m[3345] Error trying v2 registry: context canceled   
ESC[37mDEBUESC[0m[3345] Not continuing with error: context canceled  
ESC[34mINFOESC[0m[3345] Layer sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef cleaned up 
```

**Comment by davidkarlsen** [comment]
Ah - sorry - now realized that you wanted the log from a 1.8.x or 1.9.x - I can check that tomorrow.

**Comment by aaronlehmann** [comment]
@davidkarlsen: This is still very helpful. The 401 in the first log suggests a credentials handling issue. I'll do some digging and see if I can figure out what's going on.

**Comment by aaronlehmann** [comment]
I still haven't figured out exactly what's going on, but this does appear to be related to credentials. The 401s show that Docker is trying to pull from the mirror, but there's an authentication issue.

Does your mirror require authentication? If so, can you share your ~/.docker/config.json file? (obviously, redacting the base64 strings that contain obfuscated passwords).

I experimented with a mirror that requires authentication, and in all of 1.8, 1.9, and 1.10, I had to edit the config.json file manually to get this setup to work. Docker will use the hub credentials when talking to the mirror, so unless they happen to be the same as the credentials for the mirror, this setup doesn't seem to work without manual intervention.

**Comment by davidkarlsen** [comment]
Yes! There you have it! I created a user in our own registry which matches the docker hub one - and then it worked! But this seems like a regression in 1.10

**Comment by davidkarlsen** [comment]
So to sum up:
Did not work:
```
{
        "auths": {
                "fsnexus.evry.com:8085": {
                        "auth": "REMOVED  - seemed b64 encoded ending in ==",
                        "email": "david.karlsen@evry.com"
                },
                "fsnexus.evry.com:8087": {
                        "auth": "REMOVED - seemed b64 encoded ending in ==",
                        "email": "david.karlsen@evry.com"
                },
                "https://index.docker.io/v1/": {
                        "auth": "REMOVED",
                        "email": "davidkarlsen@gmail.com"
                }
        }
}

```

Will work:
```
{
        "auths": {
                "fsnexus.evry.com:8085": {
                        "auth": "VALUEHEREMATCHES",
                        "email": "david.karlsen@evry.com"
                },
                "https://index.docker.io/v1/": {
                        "auth": "VALUEHEREMATCHES",
                        "email": "davidkarlsen@gmail.com"
                }
        }
}
```

e.g. if the two users "are the same" (name && pw) it will work

**Comment by davidkarlsen** [comment]
Would it not be better if it chose the credentials matching the servername:port, and fall back to dockerhub ones if not given?

**Comment by aaronlehmann** [comment]
@davidkarlsen: Great, I'm glad we're making progress on figuring this out.

Just to make sure I understand, are you saying that in 1.8 and 1.9, the username and password didn't have to match between the two auth entries? I tried this yesterday and couldn't get it to work with any version unless the username and password were the same between the hub and the mirror.

**Comment by davidkarlsen** [comment]
I now tried:

- downgrading to 1.9.1 (apt-get install docker-engine=1.9.1-0~trusty)
- removing my whole ~/.docker
- deleted the user that matched docker.io on the nexus mirror

and then

1) docker login to docker hub
and could still pull

2) docker login to mirror address
and could still pull

Then upgraded to 1.10 and not able to pull

**Comment by aaronlehmann** [comment]
@davidkarlsen: I'm still having trouble reproducing this with 1.9. Can you please take a look at this list of steps and see if it differs in some way from what you're doing:

1) rm ~/.docker/config

2) `docker login` - enter hub credentials

3) `docker pull aaronlehmann/busybox` - doesn't pull from the mirror because I don't have credentials for it; ends up pulling from hub:

```
DEBU[0760] Trying to pull aaronlehmann/busybox from https://registry:5000/ v2 
DEBU[0760] Pulling tag from V2 registry: "latest"       
DEBU[0760] v2 error: errcode.Error unauthorized: authentication required 
DEBU[0760] Error trying v2 registry: unauthorized: authentication required 
DEBU[0760] Trying to pull aaronlehmann/busybox from https://registry-1.docker.io v2 
```

4) `docker pull registry:5000/aaronlehmann/busybox` - this fails because I have not logged in to the mirror yet.

5) `docker login registry:5000` - enter mirror credentials, which are different from hub credentials

6) `docker pull registry:5000/aaronlehmann/busybox` - this succeeds now that I have logged in to the mirror.

This is where it gets interesting:

7) `docker pull aaronlehmann/busybox` - still ends up using the hub, because the credentials associated with the repository `aaronlehmann/busybox` are hub credentials, not credentials for the mirror:

```
DEBU[1053] Trying to pull aaronlehmann/busybox from https://registry:5000/ v2 
DEBU[1053] Pulling tag from V2 registry: "latest"       
DEBU[1053] v2 error: errcode.Error unauthorized: authentication required 
DEBU[1053] Error trying v2 registry: unauthorized: authentication required 
DEBU[1053] Trying to pull aaronlehmann/busybox from https://registry-1.docker.io v2 
```

**Comment by davidkarlsen** [comment]
@aaronlehmann A bit unsure of this - what you are doing is not exactly what is my case (see initial posting). The regression I posted is that the repo federates several repos, among them an internal one with my internal images which I am no longer able to fetch through using the mirror option.

The closest we can get between our two different cases are:
1) OK (but I think you mean .docker/config**.json**)
2) OK
3):
```
root@ubuntu:~# DEBU[1984] Calling GET /v1.22/info
DEBU[1984] GET /v1.22/info
DEBU[1984] Calling POST /v1.22/images/create
DEBU[1984] POST /v1.22/images/create?fromImage=aaronlehmann%2Fbusybox%3Alatest
DEBU[1984] hostDir: /etc/docker/certs.d/fsnexus.evry.com:8085
DEBU[1984] Trying to pull aaronlehmann/busybox from https://fsnexus.evry.com:8085/ v2
DEBU[1984] Trying to pull aaronlehmann/busybox from https://registry-1.docker.io v2 
DEBU[1985] Increasing token expiration to: 0 seconds    
DEBU[1987] Pulling ref from V2 registry: aaronlehmann/busybox:latest 
DEBU[1987] pulling blob "sha256:d7e8ec85c5abc60edf74bd4b8d68049350127e4102a084f22060f7321eac3586" 
DEBU[1987] pulling blob "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" 
DEBU[1988] Downloaded a3ed95caeb02 to tempfile /var/lib/docker/tmp/GetImageBlob952064329 
DEBU[1989] Downloaded d7e8ec85c5ab to tempfile /var/lib/docker/tmp/GetImageBlob541625876 
DEBU[1989] Start untar layer                            
DEBU[1989] Untar time: 0.104060764s                     
DEBU[1989] Applied tar sha256:9508eff2c6877c4ae2275863cc8eae93bdac3d1b1943b0037976024be6af417f to ae78f91b26fd9d0a5a6d3ccc9541c3d0ab06eb48dec5716f0c7a0d911f92755a, size: 1113436 
DEBU[1989] Start untar layer                            
DEBU[1989] Untar time: 0.042709337s                     
DEBU[1989] Applied tar sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef to 23e100d992ddab0738db38c30eadfea5d0b2a35c50326cc0e3862610662b0391, size: 0 
```
4) I can not do that, a similar case would for me be:
et2448@ubuntu:~/projects/tac/jfr/tac-jfr-server$ docker pull fsnexus.evry.com:8085/evryfs/wmq8:fp4
Error response from daemon: Get https://fsnexus.evry.com:8085/v2/evryfs/wmq8/manifests/fp4: no basic auth credentials
5) OK
6) docker pull: docker pull fsnexus.evry.com:8085/evryfs/wmq8:fp4 will now work (but I have to add the server:ip - which I did not have to before - see initial posting)
7):
```
root@ubuntu:~# DEBU[2272] Calling GET /v1.22/info
DEBU[2272] GET /v1.22/info
DEBU[2272] Calling POST /v1.22/images/create
DEBU[2272] POST /v1.22/images/create?fromImage=aaronlehmann%2Fbusybox%3Alatest
DEBU[2272] hostDir: /etc/docker/certs.d/fsnexus.evry.com:8085
DEBU[2272] Trying to pull aaronlehmann/busybox from https://fsnexus.evry.com:8085/ v2
DEBU[2272] Trying to pull aaronlehmann/busybox from https://registry-1.docker.io v2
DEBU[2273] Increasing token expiration to: 0 seconds    
DEBU[2274] Pulling ref from V2 registry: aaronlehmann/busybox:latest 
DEBU[2274] Layer already exists: d7e8ec85c5ab           
DEBU[2274] Layer already exists: a3ed95caeb02           
```


Did you also see my comment in : https://github.com/docker/docker/issues/20097#issuecomment-182243950 ?

**Comment by aaronlehmann** [comment]
@davidkarlsen: Thanks for taking the time to investigate this. I'm sorry for all the back-and-forth!

I'm still at a loss in understanding how this setup worked in Docker 1.9. I've been trying to replicate the setup in Docker 1.9 to understand what changed between Docker 1.9 and Docker 1.10. My testing in https://github.com/docker/docker/issues/20097#issuecomment-182983481 showed that even Docker 1.9 uses credentials based on the repository reference you try to pull... i.e. if you pull a reference without an explicit registry hostname, it will use the credentials for Docker Hub.

But based on https://github.com/docker/docker/issues/20097#issuecomment-182243950, it sounds like when using 1.9, the login and password for the mirror could be different from Docker Hub, even when you pull an image with a command like `docker pull evryfs/oracle12c`. I don't see how this pull would actually use the mirror successfully - it should be trying with the hub login/password and failing, unless the mirror is somehow passing through the username and password to the hub with 1.9 and not with 1.10. There could be some peculiarity of the Sonatype registry involved here.

**Comment by thaJeztah** [comment]
@aaronlehmann @davidkarlsen I just noticed that one of your servers is running Red Hat Enterprise, with the Red Hat modified version of Docker 1.8.2 see the commit; https://github.com/projectatomic/docker/commit/a01dc02d9c369141f8bbbea0f51e8759dd6e5b93 not sure if it's relevant in finding possible difference in behavior here. Differences between the Red Hat version and Docker 1.8.2; https://github.com/projectatomic/docker/compare/v1.8.2...a01dc02d9c369141f8bbbea0f51e8759dd6e5b93

**Comment by davidkarlsen** [comment]
@thaJeztah That's irrelevant - as that's only the server hosting nexus (which is a java app) - and docker is not even installed on it.

**Comment by thaJeztah** [comment]
@davidkarlsen sorry, must've misinterpreted, because you mentioned "Using docker 1.8.2 (working):", referring to the RHEL host.

Did you also check with sonartype; given that we have a hard time reproducing this with the docker registry, wondering if other users using Nexus are running into this issue (if it's a combination of changes in docker 1.10 and Nexus)

**Comment by aaronlehmann** [comment]
I mentioned this GitHub issue to Sonatype, and found out that they're aware of a few compatibility issues between Docker 1.10 and Sonatype Nexus 3. There are fixes in progress for the issues they know about that will be part of their next release.

I'd encourage anyone experiencing problems using Docker 1.10 with Sonatype Nexus to mention them to nexus-feedback@sonatype.com, to get help or at least make sure they are aware of the issue.

**Comment by davidkarlsen** [comment]
@aaronlehmann I'll put it forward to them (we're a paying customer w/ support-contract). They are currently working on another case that surfaced w/ 1.10.

**Comment by thaJeztah** [comment]
@aaronlehmann if you're in contact with them, can you inform if they have people that we can add to our "testers" mailinglist for upcoming releases?

**Comment by peterlynch** [comment]
@thaJeztah I work for Sonatype support. We would very much appreciate being on your testers mailing list. The subscribing email for such a list would be repository-formats@sonatype.com .

Can you add us?

**Comment by thaJeztah** [comment]
@peterlynch absolutely! if you have separate e-mails for individual testers, feel free to email me at 
sebastiaan@docker.com

**Comment by dweomer** [comment]
@davidkarlsen I managed to resolve this problem by
* making sure the `anonymous` user in nexus can read from the group repo
* specifying the `anonymous` user's credentials registry mirror url, e.g. `https://anonymous:anonymous@nexus.local:5001`

**Comment by icecrime** [comment]
I'm closing this: thanks everyone for participating, and feel free to ping me if you feel that it needs reopening.

**Comment by adulescentulus** [comment]
@dweomer Are you still using your workaround (--registry-mirror=https://anonymous:anonymous@nexus.local:5001)? I cannot get it to work. I still keep getting the error:
`time="2016-09-16T12:24:20.615918563Z" level=error msg="Attempting next endpoint for pull after error: Get https://internal.nexus:15000/v2/mycompany/ubuntu/manifests/16.04: no basic
auth credentials"`
@davidkarlsen how are you doing with nexus? still problems?

I am using the docker toolbox for windows:
`docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64`

Thanks in advance!

**Comment by TristanCP** [comment]
@icecrime 
Arnaud, I'm having the same problem with "registry-mirror" and the workaround is not working. See details here : http://stackoverflow.com/questions/42143395/docker-registry-mirror-not-used
