### ISSUE TITLE
Volumes-from does not work with network shares

### ISSUE THREAD

**Issue by olymk2** [docker/docker#20098]
docker version:
```
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:41:30 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:41:30 2016
 OS/Arch:      linux/amd64
```

docker info:
```
Containers: 11
 Running: 10
 Paused: 0
 Stopped: 1
Images: 28
Server Version: 1.10.0
Storage Driver: btrfs
 Build Version: Btrfs v4.0
 Library Version: 101
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.56 GiB
Name: isoly
ID: NNYS:HTN6:3KVB:6XRX:MZD5:SJFM:QVEB:CEVX:BBMT:EZSL:3PB7:VENT
Username: olymk2
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

uname -a
`Linux isoly 4.2.0-27-generic #32-Ubuntu SMP Fri Jan 22 04:49:08 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

I have setup two container, one is setup to be a data volume inside that container I have mounted two network shares, 

```
/etc/fstab
ipaddress:/srv/export/filestore/shared_app_data /srv/shared_app_data  nfs defaults 0 0
ipaddess:/srv/export/filestore/shared_app_data /mnt/shared_app_data  nfs defaults 0 0
```

If I jump inside the container with exec I can see the contents of the container.

In a second container I have mounted the volumes from the container above which should pull in /mnt/shared_app_data and /srv/shared_app_data and in fact it does mount them in the new container how ever these folders are completely blank this has been the case with the current and previous versions

I have created and launched both container with the --priviledged flag, I am sure this used to work on an older version but i have been unable to resolve this issue is it a bug ?

**Comment by cpuguy83** [comment]
This is because mounts created in a container are not seen outside the container unless you do something like `-v /foo:/foo:shared`.  This allows the mounts to propagate to the host and as such be shared with other containers.

**Comment by olymk2** [comment]
@cpuguy83 thanks for the suggestion can you elaborate a little, if I have my data_container with the above mounts mounted inside it how do I then expose it to the second container ?

I though -v was for mapping folder on the host to inside the container not for mapping a folder inside one container to another ? I thought thats what --volumes-from was for ?

so how do i map /srv/shared_app_data mounted inside the data_volume to a new container ?

**Comment by olymk2** [comment]
in further investigation, I think this needs to be reopened this has nothing to do with folders on the host so using -v /foo:/foo:shared will not solve the issue.

The docks say that -v is to mount from the host into the container 

> -v|--volume[=[[HOST-DIR:]CONTAINER-DIR[:OPTIONS]]]
>           Create a bind mount. If you specify, -v /HOST-DIR:/CONTAINER-DIR, Docker
>           bind mounts /HOST-DIR in the host to /CONTAINER-DIR in the Docker
>           container. If 'HOST-DIR' is omitted,  Docker automatically creates the new
>           volume on the host.  The OPTIONS are a comma delimited list and can be:

the volumes-from does not take a shared parameter, as I believe this is a container to container issue can we reopen the issue @cpuguy83 or shall i create a new one ?

**Comment by cpuguy83** [comment]
I think you are misunderstanding.
You cannot share mounts between two containers unless the volume the mounts are in uses the "shared" flag.
A mount created in one container will not propagate otherwise.

**Comment by olymk2** [comment]
@cpuguy83 I think I get you so my data volume has 

```
VOLUME /srv/shared_app_data
VOLUME /mnt/shared_app_data
```
can I make that shared some how ? the format above assumes I am mounting from my host or is this only possible with a volume that lives outside the container ?

Basically what I wanted was a container which has my mounts which I can then make available to all other containers because the apps in the other container all rely on these file on the network share.

**Comment by cpuguy83** [comment]
@olymk2 This is only available on host-mounted volumes.
Alternatively, you may want to use a plugin.

**Comment by olymk2** [comment]
@cpuguy83 thanks perhaps i should put it in as a feature request, I was hoping to make it so every developer would not have to manually setup and mount the shares and then expose them into the container. 

Thanks for clarifying
