### ISSUE TITLE
Unable to umount volume with 1.10 and SYS_ADMIN

### ISSUE THREAD

**Issue by adrienkohlbecker** [docker/docker#20092]
Hello,

I recently updated to the 1.10 release and noticed a change in behaviour when trying to `umount` a volume from inside the container.

 ```shell
# On 1.9
docker run --rm --volume /tmp:/data --cap-add=SYS_ADMIN ubuntu:trusty umount /data
# => OK

# On 1.10
docker run --rm --volume /tmp:/data --cap-add=SYS_ADMIN ubuntu:trusty umount /data
# => umount: /data: must be superuser to umount
docker run --rm --volume /tmp:/data --privileged ubuntu:trusty umount /data
# => OK
```

With the new release, what is the most minimal privileges I need to give the container to be able to `umount` volumes ?
I use this to provide decryption keys to my containers during start-up, with the volume being unmounted and the capabilities reset after decryption.

```
➜  docker info
Containers: 12
 Running: 2
 Paused: 0
 Stopped: 10
Images: 187
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: zfs
 Dirs: 211
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-19-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.67 GiB
Name: REDACTED

➜  docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:41:30 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:41:30 2016
 OS/Arch:      linux/amd64

➜  uname -a
Linux REDACTED 4.2.0-19-generic #23-Ubuntu SMP Wed Nov 11 11:39:30 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by thaJeztah** [comment]
Hm this could actually be similar to https://github.com/docker/docker/issues/20082, and possibly the seccomp profile blocking this. Just to test; does it work if you run the container with `--security-opt seccomp:unconfined`?

**Comment by adrienkohlbecker** [comment]
Yes, `docker run --rm --volume /tmp:/data --cap-add=SYS_ADMIN --security-opt seccomp:unconfined ubuntu:trusty umount /data` does work properly.

What are the implications of this in terms of security ? Is it wise to use it in production ?

**Comment by thaJeztah** [comment]
Docker 1.9 did not have seccomp filtering, so doing so is not less secure than it was in 1.9. However, if you know which Syscall is needed to perform the umount, you could create a custom profile to allow just that.

Giving SYS_ADMIN capabilities to a container can be really dangerous, so I would really overthink if it's actually needed. See https://lwn.net/Articles/486306/, http://linux.die.net/man/7/capabilities

Is there a specific reason you need to give the container privileges to mount/umount?

**Comment by adrienkohlbecker** [comment]
Alright, I'll enable this option in the meantime. Do you have any pointers for creating the custom profile?

It's part of our credentials management scheme. We use an entrypoint that performs the following actions:
- Read a decryption key from the mounted volume
- Decrypt credentials stored as a file in the image and populate configuration files
- Unmount the decryption key
- Switch users and drop all the capabilities

So unmounting the key is really important so the app can't access it, and we ensure all the capabilities are dropped.
Do you see a better way of doing this?

Note: This approach was introduced by Shopify here : https://engineering.shopify.com/79963908-secrets-at-shopify-introducing-ejson (see Key Negotiation)

**Comment by thaJeztah** [comment]
Using a volume driver for secrets could be an option (at least during runtime), but it may depend on your exact use case. E.g. https://github.com/calavera/docker-volume-keywhiz

w.r.t. writing a seccomp profile. General information on the feature is available here http://blog.docker.com/2016/02/docker-engine-1-10-security/, but I think @jfrazelle was planning on writing a tutorial on writing the profiles (no ETA yet)

**Comment by jfrazelle** [comment]
wrt creating a custom profile since all you need is mount and umount, I would base it off the default profile and just add those two to the whitelist, I'm going to make a PR for the docs and for using `go generate` to generate a json version of the default profile at https://github.com/docker/docker/blob/master/profiles/seccomp/seccomp_default.go that people can use as a base

**Comment by jfrazelle** [comment]
this is a dup of https://github.com/docker/docker/issues/20082 so closing
