### ISSUE TITLE
Debian package version is pre-release

### ISSUE THREAD

**Issue by dohnto** [docker/docker#20105]
### Description of problem:

Current version of docker-engine package (from [docker repository](https://apt.dockerproject.org/repo/)) for is are for example: 1.9.1-0~jessie.
Note the tilde and read [debian guideline](https://www.debian.org/doc/debian-policy/footnotes.html#f37).

I package a docker-compose into a debian package for private use. As 1.6.0 emerged, I modified the control file to contain: `Depends: docker-engine (>= 1.9.1)` as stated in the docker-compose release notes.

However the Depends constraint makes it impossible to install docker-compose 1.6.0 with upstream package 1.9.1-0~jessie, because due to the tilde it is treated as a pre-release. 

```
docker-compose depends on docker-engine (>= 1.9.1); however:
Version of docker-engine on system is 1.9.1-0~jessie.
```

Is this an intention? From my point of view, this is bug and I as a packager have to hack the Depends field for docker-depending packages.

###  docker version
```
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:16:19 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:16:19 2016
 OS/Arch:      linux/amd64
```

### docker info
```
Containers: 22
 Running: 6
 Paused: 0
 Stopped: 16
Images: 148
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /www/docker/docker/aufs
 Backing Filesystem: extfs
 Dirs: 246
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.18.19-zen
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 1.96 GiB
Name: td-jessie
ID: RTOO:4YNE:INVH:TTNN:W5YV:2TYZ:NCCT:7SYD:AZFB:EZKT:ZN6R:7L5B
Username: dohnto
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

### uname -a
```
Linux td-jessie 3.18.19-zen #1 SMP Fri Aug 7 12:23:39 CEST 2015 x86_64 GNU/Linux
```

**Comment by jfrazelle** [comment]
ping @tianon but I believe this is by design

**Comment by tianon** [comment]
Yeah, this is by design, and is fairly common (especially in Ubuntu and/or PPAs).  Instead of `Depends: docker-engine (>= 1.9.1)`, try `Depends: docker-engine (>= 1.9.1~)`, and you should get the behavior you're looking for.
