### ISSUE TITLE
Logging events delimited by newline? 

### ISSUE THREAD

**Issue by youngpm** [docker/docker#20119]
I'm not sure if this is a bug or expected behavior, running docker 1.9.1...

Docker appears to be creating separate log entries for every new line it encounters.  Here's a simple example where I run

```
docker run debian:jessie printf "one\ntwo\nthree"
```

and then inspecting the container json logs, I see

```
{"log":"one\n","stream":"stdout","time":"2016-02-08T18:33:16.36791762Z"}
{"log":"two\n","stream":"stdout","time":"2016-02-08T18:33:16.367958027Z"}
{"log":"three\n","stream":"stdout","time":"2016-02-08T18:33:16.381349874Z"}
```

I was expecting something like
```
{"log":"one\ntwo\nthree","stream":"stdout","time":"2016-02-08T18:33:16.36791762Z"}
```

My real use case is related to using the GELF logging driver and dealing with tracebacks.  It [looks like](https://github.com/docker/docker/blob/master/vendor/src/github.com/Graylog2/go-gelf/gelf/writer.go#L286-L295) the GELF logging driver is set up to put a log message into `full_message` if it has new lines in it (e.g. tracebacks), but it appears that no matter what I do, docker is breaking up the message into separate logging events before it gets to the GELF Writer.

The `Message` interface appears to store the log line in `Line` [from the look of it](https://github.com/docker/docker/blob/5525593a681a478dc51d7ce10a8cb3135d39e785/daemon/logger/logger.go#L29), but I don't know where in the code `Message`'s are manufactured.

**Comment by MHBauer** [comment]
Related to #18057?

**Comment by youngpm** [comment]
@MHBauer Yeah looks related, they even found the line where its looking for newline's!

https://github.com/docker/docker/blob/master/daemon/logger/copier.go#L47

#18057 wants to clip the log line if the line exceeds a certain size or if "\n" is encountered, but that wouldn't solve the problem of trying to get a traceback out of docker as one log event.

Maybe what I'm asking is ill posed, i.e. is it even possible for the logger to detect something like `printf "one\ntwo\nthree"` as a single logging event?

**Comment by phemmer** [comment]
While it might be an optimization to group multiple lines into a single json entry, you can't rely on that behavior to separate chunks of output. STDOUT, STDERR, & STDIN are streams, not datagrams.

**Comment by youngpm** [comment]
@phemmer Thanks!  

I see now that the behavior I was expecting to see doesn't make sense in the context of Docker logs.  The application itself knows the boundaries of what it is trying to log, but that piece of info is lost in the abstraction of Docker forwarding stdout/stderr of the application along.

I'm going to close this this one out!
