### ISSUE TITLE
Volume removal not documented correctly

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#20113]
I found some comments on an EMC blog that could point us to a doc error.

http://blog.emccode.com/2016/02/04/what-you-need-to-know-about-storage-in-docker-1-10/#comments

![image](https://cloud.githubusercontent.com/assets/1347209/12894929/b144dfc6-ce4e-11e5-8b70-ac9175a13380.png)

https://docs.docker.com/engine/userguide/containers/dockervolumes/

**Comment by ozlerhakan** [comment]
they mentioned it as a [note ](https://docs.docker.com/engine/reference/run/#clean-up-rm) of the `--rm` flag:   . nevertheless, this may need to be mentioned on the volume page as well.

**Comment by aditirajagopal** [comment]
#dibs?
