### ISSUE TITLE
pkg/archive encodes xattrs in the tar stream differently from everyone else

### ISSUE THREAD

**Issue by jstarks** [docker/docker#20125]
@alexlarsson, @vbatts 

Currently when pkg/archive adds a file to a tar archive, it sometimes adds an xattr "security.capability", which it copies directly from the file's POSIX extended attribute of the same name. When it then extracts this file at some later time, it takes _all_ the xattrs in the tar stream and sets them as POSIX extended attributes.

I think this is incorrect. The tar format's xattrs are _not_ specifically for POSIX extended attributes, and they should not be interpreted as such. They are intended as a general extension mechanism in tar, and they are supposed to be namespaced with a vendor tag for specific uses. For example, GNU tar and star both support POSIX extended attributes but prefix them with "SCHILY.xattr." to specify that they are specifically POSIX EAs and not some other attributes. [libarchive](https://github.com/libarchive/libarchive/wiki/TarExtendedAttributes) uses "LIBARCHIVE.xattr." and base64 encodes the value.

The problem with the code in archive is that it blocks any other use of extended attributes. This is a problem on Windows, where we need to encode additional non-POSIX file metadata into the tar stream, and xattrs is the only place to do it.

I think the fix is to start using the "SCHILY.xattr" or "LIBARCHIVE.xattr" prefix for any new POSIX EAs that need to be supported, or to add a new "DOCKER.xattr" prefix. Maybe we are stuck with "security.capability" specifically for backwards compatibility with existing images, but we should special case this one on unarchive and stop passing all the other xattrs to lsetxattr().

This will free up the namespace for us to add some Windows-specific metadata so that we can stop encoding it in the file stream (which causes problems with tarsum and tar-split).

**Comment by jstarks** [comment]
@swernli FYI

**Comment by unclejack** [comment]
@jstarks Have you got a branch somewhere with changes to fix this?

**Comment by vbatts** [comment]
good catch

**Comment by jstarks** [comment]
Sorry for the spam, everyone. Over the weekend I took a closer look at the archive/tar sources and learned that Xattrs in tar.Header already maps directly to SCHILY.xattr. I wrongly assumed that Xattrs mapped to PAX extended headers directly. So there is no issue here, thankfully.

Unfortunately, this also means that there is no way in the standard archive/tar package to extend the format to include Windows metadata. @vbatts, it looks like you already forked archive/tar as part of tar-split; could we extend it further to include Windows metadata (and then try to get the changes back into go separately?)

**Comment by thaJeztah** [comment]
No problem, thanks @jstarks

**Comment by vbatts** [comment]
@jstarks so windows is looking to use xattrs? where is is this information being tracked?
