### ISSUE TITLE
Cannot update Centos and Ubuntu container after upgrading to docker v1.10 -  repomd.xml: [Errno 12] Timeout

### ISSUE THREAD

**Issue by modernix** [docker/docker#20120]
Cannot use yum update and apt-get update after upgrading to docker v1.10 and docker-machine 0.6

Environment:
OpenStack Kilo
Docker v1.10
docker-machine 0.6
Container: Official Centos 6 and 7 (same result with Ubuntu 14.04)

Error:
yum update
Loaded plugins: fastestmirror
http://mirrors.easynews.com//linux/centos/6.7/os/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://mirrors.easynews.com//linux/centos/6.7/os/x86_64/repodata/repomd.xml: (28, 'Operation too slow. Less than 1 bytes/sec transfered the last 30 seconds')
Trying other mirror.

[root@529078dfeee5 /]# cat /etc/resolv.conf 
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 192.168.1.1
nameserver 8.8.4.4
nameserver 8.8.8.8
search local

---
ping mirrors.easynews.com
PING mirrors.easynews.com (69.16.168.244) 56(84) bytes of data.
64 bytes from mirrors.easynews.com (69.16.168.244): icmp_seq=1 ttl=56 time=77.0 ms
64 bytes from mirrors.easynews.com (69.16.168.244): icmp_seq=2 ttl=56 time=77.0 ms
64 bytes from mirrors.easynews.com (69.16.168.244): icmp_seq=3 ttl=56 time=75.6 ms
^C
--- mirrors.easynews.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2005ms
rtt min/avg/max/mdev = 75.615/76.551/77.025/0.735 ms

Step to reproduce:

1. Use docker-machine to create a docker machine via OpenStack

docker-machine create --driver openstack --openstack-username demo  --openstack-password demo  --openstack-tenant-name demo  --openstack-auth-url http://controller:5000/v2.0  --openstack-ssh-user ubuntu --openstack-image-id 71a06144-82ff-4405-911e-c678513b54ce --openstack-flavor-name m1.medium --openstack-net-name demo-net  --openstack-floatingip-pool ext-net --openstack-sec-groups default dock

2. eval $(docker-machine env dock)

3. docker run -it centos:7 yum update
Loaded plugins: fastestmirror, ovl
http://mirror.umd.edu/centos/7.2.1511/os/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://mirror.umd.edu/centos/7.2.1511/os/x86_64/repodata/repomd.xml: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds')
Trying other mirror.

**Comment by syserrk** [comment]
@modernix, I have the same issue. Did you find a solution?

**Comment by modernix** [comment]
@syserrk 

Yes, here is the solution.

1. # vi /etc/default/docker
DOCKER_OPTS='
-H tcp://0.0.0.0:2376
-H unix:///var/run/docker.sock
**--mtu 1454**
--storage-driver aufs
--tlsverify
--tlscacert /etc/docker/ca.pem
--tlscert /etc/docker/server.pem
--tlskey /etc/docker/server-key.pem
--label provider=openstack

2. Restart docker's engine

3. Check bridge's mtu - # docker network inspect bridge

[
    {
        "Name": "bridge",
        "Id": "14a4b8939cb6ff69ebc19832565e5636c0a2dfcfead5e61b4e6f3d7f1c9efc0f",
        "Scope": "local",
        "Driver": "bridge",
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16"
                }
            ]
        },
        "Containers": {},
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1454"
        }
    }
]

If you use docker-compose, you need to setup add these lines
_networks:
  default:
    external:
      name: bridge_

You also can create a new network:

docker network create --driver bridge -o "com.docker.network.driver.mtu"="1454" -o "com.docker.network.bridge.name"="newNet" -o "com.docker.network.bridge.enable_icc"="true" -o "com.docker.network.bridge.enable_ip_masquerade"="true" -o "com.docker.network.bridge.host_binding_ipv4"="0.0.0.0" newNet

docker network ls

**Comment by thaJeztah** [comment]
this behavior changed in docker 1.10; older versions tried to guess the MTU, but there's various reasons why this may be a bad idea. See the PR that changed this; https://github.com/docker/docker/pull/18108

I'm closing this issue because (looking at the discussion above), this was resolved. Feel free to comment here after I've closed
