### ISSUE TITLE
Windows: Failed to create volume over an existing directory

### ISSUE THREAD

**Issue by darrenstahlmsft** [docker/docker#20127]
List the steps to reproduce the issue:
1. On Windows, create a directory C:\foo, and populate a file C:\foo\file
2. Attach a new volume at C:\foo
3. Observe the contents of C:\foo\file

Alternatively run CI test TestBuildVolumesRetainContents in docker_cli_builder_test.go against a Windows daemon (`testRequires(c, DaemonIsLinux)` needs to be commented out to run against a Windows daemon).

Describe the results you received:
`E:\bin\docker.exe: Error response from daemon: Cannot start container 7d3daab7ecfb827c3bbb61df21d249763606db688b3efa72c6c4bdfeeea61401: HCSShim::CreateComputeSystem- Win32 API call returned error r1=0x80070091 err=The directory is not empty.` while attaching new volume in step 2.

Describe the results you expected:
A new volume is attached at C:\foo, and the contents of C:\foo\file remain the same as initially added.

----------END REPORT ---------

@jhowardmsft @jstarks

**Comment by darrenstahlmsft** [comment]
Looks like this is essentially the Windows bug for <https://github.com/docker/docker/pull/1742>.

**Comment by jhowardmsft** [comment]
Known. Needs platform support (not present in current builds either). See https://github.com/docker/docker/blob/master/daemon/create_windows.go#L48-L52

**Comment by jstarks** [comment]
We're not going to get platform support for shadowing an existing directory with a junction point. I think we're going to hack to hack around it to get this behavior... Let me think on it.

**Comment by thaJeztah** [comment]
Should this be added to a milestone?

**Comment by jhowardmsft** [comment]
@thaJeztah No point yet.

**Comment by LK4D4** [comment]
@jhowardmsft @darrenstahlmsft was it fixed or what?

**Comment by jhowardmsft** [comment]
No.

**Comment by LK4D4** [comment]
@jhowardmsft thanks for update!

**Comment by git-jiby-me** [comment]
@jhowardmsft any work ongoing or planned into this ?

**Comment by jhowardmsft** [comment]
No. This requires platform support and is unlikely to be in RS2 either. I'm going to close this issue on GH, as there's nothing that can be done in Docker to support this. It's a platform issue being tracked internally.

**Comment by matt-richardson** [comment]
Can we keep it open, and close it when the internal issue is closed?
There is no visibility to the community to this internal issue tracker.

**Comment by jhowardmsft** [comment]
@patricklang How do you want to handle these types of issues? I honestly don't think there's any point tracking in the docker repo when there's no bug there, and a Windows change is (if ever) post RS2 and currently not planned as a workitem. It's already documented in the docker docs.

**Comment by JohnMaguire** [comment]
Where can we expect to see a notice that this bug is resolved when (if) it does get resolved?

Additionally, you state that this is documented in the Docker docs however I don't see it listed on any of the following pages (this just bit us):

https://docs.docker.com/engine/reference/builder/#/volume
https://docs.docker.com/engine/tutorials/dockervolumes/#mount-a-host-directory-as-a-data-volume
https://docs.docker.com/engine/reference/commandline/volume_create/
https://docs.docker.com/docker-cloud/apps/volumes/

**Comment by jhowardmsft** [comment]
It's in https://github.com/docker/docker/blob/master/docs/reference/commandline/run.md#mount-volume--v---read-only, the Windows note at the end.

When (if :innocent:) it gets fixed, it'll be in the release notes, and the docs will be updated.

**Comment by JohnMaguire** [comment]
Perhaps it should also be documented here, since the behavior of "Existing files in the container will be copied into the volume" is mentioned, with no caveats: https://docs.docker.com/engine/reference/builder/#volume

**Comment by jhowardmsft** [comment]
@JohnMaguire Reasonable. Want to open a PR?

**Comment by JohnMaguire** [comment]
@jhowardmsft I was willing, but unable to find the file in the docs repository that needed updating.

**Comment by jhowardmsft** [comment]
@JohnMaguire It's would be this file: https://github.com/docker/docker/blob/master/docs/reference/builder.md

**Comment by junvwang** [comment]
Hi @jhowardmsft, i found this statement from [https://github.com/docker/docker/blob/master/docs/reference/commandline/run.md#mount-volume--v---read-only](https://github.com/docker/docker/blob/master/docs/reference/commandline/run.md#mount-volume--v---read-only)

> The following examples will fail when using Windows-based containers, as the destination of a volume or bind-mount inside the container must be one of: a non-existing or empty directory; **or a drive other than C:**. Further, the source of a bind mount must be a local directory, not a file.

How can i get a drive other than C:, for example, drive D:? 
thanks.

**Comment by jhowardmsft** [comment]
`-v c:\somehostdir:d:` ? As per the example in the link you provided....

**Comment by junvwang** [comment]
oh, sorry didn't see that, thanks!
