### ISSUE TITLE
docker history reports missing container ids after upgrade to 1.10

### ISSUE THREAD

**Issue by horkhe** [docker/docker#20131]
After upgrade to docker 1.10.0 output of the `docker history` command started to look like this:
```
sudo docker history -q registry.postgun.com:5000/mailgun/kafka:0.8.2.2
f2ffd5710981
<missing>
<missing>
<missing>
<missing>
<missing>
```
As you can see only the top image id is reported properly. Note that this issue is not image specific, output like that we get for all our images. 

EDIT:

This result has been observed on both VirtualBox and Rackspace Cloud Server.

The following output was obtained from a Rackspace Cloud Server:
```
$ docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:32:05 2016
 OS/Arch:      linux/amd64
Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:32:05 2016
 OS/Arch:      linux/amd64
```
```
$ docker info
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 31
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /var/mailgun/docker/aufs
 Backing Filesystem: extfs
 Dirs: 60
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.13.0-77-generic
Operating System: Ubuntu precise (12.04.4 LTS)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 29.45 GiB
Name: ci.dfw.definbox.com
ID: 45W7:IA4T:XPDT:G4SV:U6XA:KTWY:YVVZ:SD4E:FDXT:SSXY:NAIZ:I46U
WARNING: No swap limit support
```

**Comment by thaJeztah** [comment]
I think this is expected; the content-addressable storage no longer uses "parent" images to chain the image-layers together. Newly pulled images also no longer will show the intermediate images (these "missing" images will only be shown for images that were present on the host, but have been migrated to the new storage)

/cc @tonistiigi just for checking; but I think this is expected.

(perhaps we need to mention this in the migration wiki https://github.com/docker/docker/wiki/Engine-v1.10.0-content-addressability-migration)

**Comment by tonistiigi** [comment]
@thaJeztah Yes, you are correct. We don't pull parent images anymore. You only have them if you built the image yourself or if you migrated your old image chains.

Maybe we should replace `missing` with `none` so it looks less like an error.

**Comment by horkhe** [comment]
Hmm, but those layers still have ids, right (inferred from content or not), so why not show them?

Here is the problem: imagine we have `myimage:latest` that is build of `ubuntu:14.04`. We want to rebuild `myimage:latest` only if `ubuntu:14.04` changes, so before building we pull ubuntu:14.04 and check if its Id is present in the history of `myimage:latest`. If it is not, then `myimage:latest` is rebuilt. Given that now history command of now help, is there a way to check that one image is based of another?

**Comment by tonistiigi** [comment]
@horkhe There is no way to do this securely(the previous method wasn't secure either). We can expose the layer IDs in `docker inspect` (probably will happen in v1.11) but even that would just confirm the origin of the filesystem data and not image configuration. I'd recommend you to include a comment in your build with a parent image ID or manifest digest. Then you can use check when this id changes from registry/notary and rerun your build if needed.

**Comment by marius311** [comment]
Sorry, I don't totally know how the internals work, but does there currently exist a workaround? By that I mean, can I pull an image, then run it at a layer other than the top layer? (I basically use this for testing purposes, its certainly possible to build the image myself then do it, but its slightly less convenient)

**Comment by thaJeztah** [comment]
@marius311 not at this moment, follow the discussion on https://github.com/docker/docker/issues/20316, which talks about this some more

**Comment by thaJeztah** [comment]
I'll close this issue in favor of #20316, so that we don't have too many similar issues open in this subject
