### ISSUE TITLE
Docker does not probe for xt_conntract

### ISSUE THREAD

**Issue by trin-cz** [docker/docker#20145]
Docker does not check, whether the conntrack iptables extension is installed (xt_conntrack kernel modules is loaded). When the conntrack extension is not loaded, docker fails with error like this:

Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: Failed to Setup IP tables: Unable to enable ACCEPT INCOMING rule: iptables failed: iptables --wait -I FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT: iptables: No chain/target/match by that name.\n (exit status 1)

This can also be very confusing for newcomers.

Docker version:
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 12:59:02 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 12:59:02 UTC 2015
 OS/Arch:      linux/amd64

Docker info:
Containers: 1
Images: 2
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: xfs
 Dirs: 8
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 24
Total Memory: 252.4 GiB
Name: will not tell you
ID: B5U6:CBXQ:2QJT:IA6V:ZAPN:UMJV:7BBZ:XEP2:X4KP:XENG:STVM:NIS4

**Comment by trin-cz** [comment]
Updated issue description.

**Comment by aboch** [comment]
Thanks @trin-cz for reporting the issue.
Network drivers in libnetwork are the ones probing for the required modules.
For example, see:
https://github.com/docker/libnetwork/blob/master/drivers/bridge/bridge.go#L133

I think we should be able to add the probing for `xt_conntrack` as well.
