### ISSUE TITLE
Docker seems to leak memory, on Tutum/Ubuntu 15.04 x64, for reasons unknown

### ISSUE THREAD

**Issue by aknuds1** [docker/docker#20149]
The `docker` process is using about 635 MB of swap memory, on a machine with 1 GB of physical memory and 2 GB of swap memory. It rises to this level after about one day, whereupon the machine is borderline unresponsive from swapping. The total usage of swap memory is about 1482 MB at that point.

This is on a Tutum managed Ubuntu 15.04 x64 Digital Ocean VM.

`docker version`:
```
Client:
 Version:      1.9.1-cs2
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   4ade326
 Built:        Mon Nov 30 21:56:07 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1-cs2
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   4ade326
 Built:        Mon Nov 30 21:56:07 UTC 2015
 OS/Arch:      linux/amd64
```

`docker info`:
```
Containers: 44
Images: 189
Server Version: 1.9.1-cs2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 277
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-22-generic
Operating System: Ubuntu 15.04
CPUs: 1
Total Memory: 993.1 MiB
Name: muzhack.com2
ID: IC6S:RE62:77W2:424Q:7OKZ:JDT4:RETI:WQ4A:D23X:B7O5:EWVX:XAQY
Username: aknudsen
Registry: https://index.docker.io/v1/
```

`uname -a`: `Linux muzhack.com2 3.19.0-22-generic #22-Ubuntu SMP Tue Jun 16 17:15:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

How to reproduce:
1. Install [MuzHack stack](https://github.com/muzhack/muzhack/blob/master/docker/tutum-staging.yaml) on Tutum, with corresponding 1 GB Ubuntu 15.04 x64 DO nodes having 2 GB of swap memory
2. Let marinate for a day
3. Log on to `muzhack-green node`
4. Inspect memory usage, where much swap memory should now be consumed

You can see my findings regarding memory usage, system wise and by individual processes in the below screenshot:

<img width="850" alt="screenshot" src="https://cloud.githubusercontent.com/assets/281303/12917446/c9551cca-cf39-11e5-9533-38e135bfb210.png">

**Comment by unclejack** [comment]
@aknuds1 Based on your version string, it seems you're running a commercially supported version of the Docker binaries.

The community can't help you with that version of Docker because it's not something which is available out in the open as far as I know. You might want to get in touch with Docker Inc. to get support for that.

**Comment by aknuds1** [comment]
@unclejack Ah, great :(

**Comment by thaJeztah** [comment]
@aknuds1 I'll close this issue, but happy to hear if you've been able to get it resolved through support@docker.com
