### ISSUE TITLE
Unable to pull docker images from public registry in windows 2016

### ISSUE THREAD

**Issue by luqmanshareef** [docker/docker#20154]
I created a VM in Azure ( Windows Server 2016 Core with Containers Tech Preview 4 )
I tried pulling nginx but it is failing.

**C:\>docker pull nginx
Using default tag: latest
Pulling repository docker.io/library/nginx
manifest unknown: manifest unknown
Error: image library/nginx:latest not found
**

Docker Version is:
**C:\Users\luqmanshareef>docker version
Client:
Version: 1.10.0-dev
API version: 1.22
Go version: go1.5.1
Git commit: 18c9fe0
Built: Mon Nov 23 22:32:50 UTC 2015
OS/Arch: windows/amd64

Server:
Version: 1.10.0-dev
API version: 1.22
Go version: go1.5.1
Git commit: 18c9fe0
Built: Mon Nov 23 22:32:50 UTC 2015
OS/Arch: windows/amd64
**

**Comment by luqmanshareef** [comment]
C:\Users\luqmanshareef>docker info
Containers: 8
Images: 11
Server Version: 1.10.0-dev
Storage Driver: windowsfilter
 Windows:
Execution Driver:
 Name: Windows 1854
 Build: 1.10.0-dev 18c9fe0
 Default Isolation: process
Logging Driver: json-file
Plugins:
 Volume: local
 Network:
Kernel Version: 10.0 10586 (10586.63.amd64fre.th2_release.160104-1513)
Operating System: Windows Server 2016 Technical Preview 4
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 3.5 GiB
Name: MyWin2016
ID: YMZJ:YFWT:II6H:HDU4:6OQ7:73ZN:46UR:HWBN:RZJF:2OFW:SV6L:CPPC
Debug mode (server): true
 File Descriptors: -1
 Goroutines: 16
 System Time: 2016-02-09T17:00:54.1023058Z
 EventsListeners: 0
 Init SHA1:
 Init Path: C:\Windows\System32\docker.exe
 Docker Root Dir: C:\ProgramData\Docker

**Comment by friism** [comment]
@luqmanshareef there's no official `nginx` image for Windows Server yet. Microsoft is maintaining one though, you can pull it with `docker pull microsoft/nginx`

**Comment by StefanScherer** [comment]
@luqmanshareef To see which containers you can pull for TP4 right now, do a `docker search any` and get a list of the images. On Azure you can't use the nano containers.

**Comment by luqmanshareef** [comment]
Tried pulling the microsoft images. No Luck.

C:\Users\luqmanshareef>docker search any
NAME                    DESCRIPTION                                     STARS     OFFICIAL   AUTOMATED
microsoft/aspnet        ASP.NET 5 framework installed in a Windows...   1         [OK]       [OK]
microsoft/django        Django installed in a Windows Server Core ...   1                    [OK]
microsoft/dotnet35      .NET 3.5 Runtime installed in a Windows Se...   1         [OK]       [OK]
microsoft/golang        Go Programming Language installed in a Win...   1                    [OK]
microsoft/httpd         Apache httpd installed in a Windows Server...   1                    [OK]
microsoft/iis           Internet Information Services (IIS) instal...   1         [OK]       [OK]
microsoft/mongodb       MongoDB installed in a Windows Server Core...   1                    [OK]
microsoft/mysql         MySQL installed in a Windows Server Core b...   1                    [OK]
microsoft/nginx         Nginx installed in a Windows Server Core b...   1                    [OK]
microsoft/node          Node installed in a Windows Server Core ba...   1                    [OK]
microsoft/php           PHP running on Internet Information Servic...   1                    [OK]
microsoft/python        Python installed in a Windows Server Core ...   1                    [OK]
microsoft/rails         Ruby on Rails installed in a Windows Serve...   1                    [OK]
microsoft/redis         Redis installed in a Windows Server Core b...   1                    [OK]
microsoft/ruby          Ruby installed in a Windows Server Core ba...   1                    [OK]
microsoft/sqlite        SQLite installed in a Windows Server Core ...   1                    [OK]
microsoft/nano-golang   Go Programming Language installed in a Nan...   1                    [OK]
microsoft/nano-httpd    Apache httpd installed in a Nano Server ba...   1                    [OK]
microsoft/nano-iis      Internet Information Services (IIS) instal...   1         [OK]       [OK]
microsoft/nano-mysql    MySQL installed in a Nano Server based con...   1                    [OK]
microsoft/nano-nginx    Nginx installed in a Nano Server based con...   1                    [OK]
microsoft/nano-node     Node installed in a Nano Server based cont...   1                    [OK]
microsoft/nano-python   Python installed in a Nano Server based co...   1                    [OK]
microsoft/nano-rails    Ruby on Rails installed in a Nano Server b...   1                    [OK]
microsoft/nano-redis    Redis installed in a Nano Server based con...   1                    [OK]
microsoft/nano-ruby     Ruby installed in a Nano Server based cont...   1                    [OK]

C:\Users\luqmanshareef>docker pull microsoft/nginx
Using default tag: latest
Pulling repository docker.io/microsoft/nginx
Error: image microsoft/nginx:latest not found

**Comment by friism** [comment]
That's very strange - are you still on the same client/server version?

You can use a fully qualified registry url: `docker pull registry-win-tp3.docker.io/microsoft/nginx`

**Comment by darrenstahlmsft** [comment]
I've got a repro. Investigating.

**Comment by StefanScherer** [comment]
A `docker pull microsoft/nginx` works fine with nightly docker.exe from https://master.dockerproject.org/windows/amd64/docker.exe. (But updating from original TP4 docker.exe from November 2015 to current is like updating from 1.9 to 1.10 and has some difficulties creating the new layer ID for the windowsservercore base image.)

```
C:\Users\vagrant> docker pull microsoft/nginx
Using default tag: latest
latest: Pulling from microsoft/nginx

03f5fe65cba9: Pull complete
dc5484447903: Pull complete
2811d4083f24: Pull complete
Digest: sha256:c93521495f5f0552b812f8ae8194a0f2fcffb574cfc57d9895fd191124382ed6
Status: Downloaded newer image for microsoft/nginx:latest
C:\Users\vagrant> docker version
Client:
 Version:      1.11.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   9f2f52d
 Built:        Tue Feb  9 17:58:52 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.11.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   9f2f52d
 Built:        Tue Feb  9 17:58:52 2016
 OS/Arch:      windows/amd64
```

**Comment by darrenstahlmsft** [comment]
@luqmanshareef Can you please confirm your docker version when running `docker pull microsoft/nginx`?

The version you initially posted has no known issues pulling images, and works fine on my end. The issue you are seeing is a known issue on the following version, which is the current default for Azure (working on getting this updated):

 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   59a341e
 Built:        Fri Nov 13 17:23:07 UTC 2015
 OS/Arch:      windows/amd64

@StefanScherer The latest nightly builds are not supported on TP4 due to some changes in architecture since then. The image pulled using the latest daemon is not likely to run on a TP4 host. If you are building locally though, instead of pulling from the repository, then the nightys *should* work.

@swernli

**Comment by luqmanshareef** [comment]
Thanks a lot for all the responses.
In one of the VMs I updated docker.exe from https://get.docker.com/windows/tp4/docker.exe.  After the update and restart the service, `docker pull microsoft/nginx ` worked.  With this, I understand that in Win 2016 docker I can pull images only from microsoft's repository.

My question is, can't I pull images from public repository of docker hub?  For example I want to pull tomcat:latest.

**Comment by friism** [comment]
@luqmanshareef Docker hub does not currently contain windows container images (they're in the separate `registry-win-tp3.docker.io` registry). The container images for Linux and Windows are different. 

There's no Tomcat image built for Windows yet that I know of, but you can take a stab at creating your own. These repos have Dockerfiles that may get you started:

 * https://github.com/StefanScherer/dockerfiles-windows
 * https://github.com/brogersyh/Dockerfiles-for-windows

From a Windows daemon, you can also check what images are available with `docker search "*"`, as Stefan mentioned.

We're working on improving this experience.

**Comment by luqmanshareef** [comment]
Got it.  Thanks a lot.
Let's close this issue here.

**Comment by ravindravv** [comment]
HI All, I have created VM windows 2016 TP5 successfully and also Installed Container feature, Dockers, Base container images. BUt I am trying to pull images but getting fail. Here I am sharing my docker information with you. Please go the same and do the needful on my reported issue.
PS C:\Windows\system32> docker info

Containers: 4

 Running: 1

 Paused: 0

 Stopped: 3

Images: 1

Server Version: 1.12.0-dev

Storage Driver: Windows filter storage driver

 Windows: 

Logging Driver: json-file

Plugins: 

 Volume: local

 Network: nat null

Kernel Version: 10.0 14300 (14300.1016.amd64fre.rs1_release_svc.160428-1819)

Operating System: Windows Server 2016 Standard Technical Preview 5

OSType: windows

Architecture: x86_64

CPUs: 4

Total Memory: 12 GiB

Name: win2016

ID: 5Q57:JTSJ:M5JY:UTZT:OCLP:WCXO:KQEG:BHDX:DED4:453Y:NLYY:XMGR

Docker Root Dir: C:\ProgramData\docker

Debug Mode (client): false

Debug Mode (server): false

Registry: https://index.docker.io/v1/

Insecure Registries:

 127.0.0.0/8 

PS C:\Windows\system32> docker ps -a

CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES



5fa263dc190e windowsservercore "powershell" 4 days ago Up 4 days demobase2



d196ddde35ed windowsservercore "powershell" 5 days ago Exited (1067) 5 days ago demobase1



a9df49f4f964 windowsservercore "powershell" 5 days ago Exited (1067) 5 days ago furious_mirza



khani



5a52e30fbf59 windowsservercore "powershell" 5 days ago Exited (1067) 5 days ago demobase 







 PS C:\Windows\system32> docker version

Client:



 Version: 1.12.0-dev



 API version: 1.24



 Go version: go1.5.3



 Git commit: 8e92415



 Built: Thu May 26 17:08:34 2016



 OS/Arch: windows/amd64



Server:



 Version: 1.12.0-dev



 API version: 1.24



 Go version: go1.5.3



 Git commit: 8e92415



 Built: Thu May 26 17:08:34 2016



 OS/Arch: windows/amd64 




 PS C:\Windows\system32> docker images

REPOSITORY TAG IMAGE ID CREATED SIZE



windowsservercore 10.0.14300.1000 dbfee88ee9fd 10 weeks ago 9.344 GB



windowsservercore latest dbfee88ee9fd 10 weeks ago 9.344 GB 


Now, I am  trying to install my first container but not successful. Trying to download a pre-created IIS image from the Docker Hub registry and deploy a simple container running IIS. 

I run the PS docker search Microsoft . docker pull and getting the following error. Pease find the same.

docker : Error response from daemon: Get https://index.docker.io/v1/search?q=microsoft: tls: failed to parse certificate from server: 

x509: negative serial number



At line:1 char:1



+ docker search microsoft



+ ~~~~~~~~~~~~~~~~~~~~~~~



+ CategoryInfo : NotSpecified: (Error response ...e serial number:String) [], RemoteException



+ FullyQualifiedErrorId : NativeCommandError 




I am requesting YOU ALL, could you please do the needful on my reported issue?

 
Could you please confirm , does web server (IIS) feature has to be enabled under Roles and Feature from server manager? I have given proxy settings to get the internet.

**Comment by StefanScherer** [comment]
@ravindravv works fine on my TP5 machine:

```
C:\Users\vagrant> docker version
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   8e92415
 Built:        Thu May 26 17:08:34 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   8e92415
 Built:        Thu May 26 17:08:34 2016
 OS/Arch:      windows/amd64
C:\Users\vagrant> docker search microsoft
NAME                                         DESCRIPTION                                     STARS     OFFICIAL   AUTOMATED
microsoft/sample-django:windowsservercore    Django installed in a Windows Server Core ...   1                    [OK]
microsoft/dotnet35:windowsservercore         .NET 3.5 Runtime installed in a Windows Se...   1         [OK]       [OK]
microsoft/sample-golang:windowsservercore    Go Programming Language installed in a Win...   1                    [OK]
microsoft/sample-httpd:windowsservercore     Apache httpd installed in a Windows Server...   1                    [OK]
microsoft/iis:windowsservercore              Internet Information Services (IIS) instal...   1         [OK]       [OK]
microsoft/sample-mongodb:windowsservercore   MongoDB installed in a Windows Server Core...   1                    [OK]
microsoft/sample-mysql:windowsservercore     MySQL installed in a Windows Server Core b...   1                    [OK]
microsoft/sample-nginx:windowsservercore     Nginx installed in a Windows Server Core b...   1                    [OK]
microsoft/sample-python:windowsservercore    Python installed in a Windows Server Core ...   1                    [OK]
microsoft/sample-rails:windowsservercore     Ruby on Rails installed in a Windows Serve...   1                    [OK]
microsoft/sample-redis:windowsservercore     Redis installed in a Windows Server Core b...   1                    [OK]
microsoft/sample-ruby:windowsservercore      Ruby installed in a Windows Server Core ba...   1                    [OK]
microsoft/sample-sqlite:windowsservercore    SQLite installed in a Windows Server Core ...   1                    [OK]
microsoft/sample-golang:nanoserver           Go Programming Language installed in a Nan...   1                    [OK]
microsoft/sample-httpd:nanoserver            Apache httpd installed in a Nano Server ba...   1                    [OK]
microsoft/sample-mysql:nanoserver            MySQL installed in a Nano Server based con...   1                    [OK]
microsoft/sample-nginx:nanoserver            Nginx installed in a Nano Server based con...   1                    [OK]
microsoft/sample-node:nanoserver             Node installed in a Nano Server based cont...   1                    [OK]
microsoft/sample-python:nanoserver           Python installed in a Nano Server based co...   1
microsoft/sample-rails:nanoserver            Ruby on Rails installed in a Nano Server b...   1                    [OK]
microsoft/sample-redis:nanoserver            Redis installed in a Nano Server based con...   1                    [OK]
microsoft/sample-ruby:nanoserver             Ruby installed in a Nano Server based cont...   1                    [OK]
C:\Users\vagrant> docker pull microsoft/iis:windowsservercore
windowsservercore: Pulling from microsoft/iis

90a7b36461ef: Pull complete
31278b05360c: Pull complete
Digest: sha256:bf7a0bf02dff6fddf53a45ca6f29d0a0a1f08c376832516fa4bc45399ec6f910
Status: Downloaded newer image for microsoft/iis:windowsservercore
```

Maybe some network problem in between like https://github.com/docker/docker/issues/6474?

**Comment by ravindravv** [comment]
Hello Stefan, Could you please explain more ? or can I execute the ps  docker pull microsoft/nginx on my server?

**Comment by go-green** [comment]
I am getting below error
C:\WINDOWS\system32>docker pull stefanscherer/node-windows
Using default tag: latest
Error response from daemon: manifest for stefanscherer/node-windows:latest not found

**Comment by StefanScherer** [comment]
@go-green I don't provide a latest tag let me know in https://github.com/StefanScherer/dockerfiles-windows/issues which version+baseimage you would expect.
