### ISSUE TITLE
docker 1.10, zfs, device or resource busy

### ISSUE THREAD

**Issue by mpiermar** [docker/docker#20153]
This worked in 1.9.1 with zfs driver.  Works fine with devicemapper on 1.10. Have not tried other storage drivers.

# docker run -d -it busybox /bin/sh
5371c4f7e4ba111e3c16797cec60bb3607c31cd289358c2baf37c5913e4f1d64

# docker cp setupNode.sh 5371c4f7e4ba:/tmp/setupANode.sh
Error response from daemon: error creating zfs mount of rock/docker/1d666677f540ca4cc7a1498dabf1f80785cf08d2583fdcc783d0b6dd8025cf1c to /var/lib/docker/zfs/graph/1d666677f540ca4cc7a1498dabf1f80785cf08d2583fdcc783d0b6dd8025cf1c: device or resource busy

# docker stop 5371c4f7e4ba
5371c4f7e4ba
# docker rm 5371c4f7e4ba
Failed to remove container (5371c4f7e4ba): Error response from daemon: Driver zfs failed to remove root filesystem 5371c4f7e4ba111e3c16797cec60bb3607c31cd289358c2baf37c5913e4f1d64: mount still active
# docker rm -f 5371c4f7e4ba
Failed to remove container (5371c4f7e4ba): Error response from daemon: Driver zfs failed to remove root filesystem 5371c4f7e4ba111e3c16797cec60bb3607c31cd289358c2baf37c5913e4f1d64: mount still active
# docker rm -f 5371c4f7e4ba
Failed to remove container (5371c4f7e4ba): Error response from daemon: No such container: 5371c4f7e4ba

Bare metal (Fedora, Archlinux -- happens on both

# docker info
Containers: 10
 Running: 10
 Paused: 0
 Stopped: 0
Images: 289
Server Version: 1.10.0
Storage Driver: zfs
 Zpool: rock
 Zpool Health: ONLINE
 Parent Dataset: rock/docker
 Space Used By Parent: 4182804992
 Space Available: 11007375059456
 Parent Quota: no
 Compression: lz4
Execution Driver: native-0.2
Logging Driver: journald
Plugins: 
 Volume: local
 Network: null host macvlan bridge
Kernel Version: 4.3.4-300.fc23.x86_64
Operating System: Fedora 23 (Server Edition)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 0
CPUs: 24
Total Memory: 125.9 GiB
Name: XXXXXXXXXX
ID: TSX3:TGZ6:FTMX:CPF3:FZA5:OTIM:I4VM:MLG3:2A25:6XJD:NMZ6:W72S
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Registries: docker.io (secure)

# docker version
Client:
 Version:         1.10.0
 API version:     1.22
 Package version: docker-1.10.0-28.gitf392451.fc24.x86_64
 Go version:      go1.6rc1
 Git commit:      3465b10
 Built:           Sun Feb  7 10:34:25 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.0
 API version:     1.22
 Package version: docker-1.10.0-28.gitf392451.fc24.x86_64
 Go version:      go1.6rc1
 Git commit:      3465b10
 Built:           Sun Feb  7 10:34:25 2016
 OS/Arch:         linux/amd64

# uname -a
Linux XXXXXX  4.3.4-300.fc23.x86_64 #1 SMP Mon Jan 25 13:39:23 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

# dnf list installed zfs
Last metadata expiration check performed 0:07:09 ago on Tue Feb  9 11:46:59 2016.
Installed Packages
zfs.x86_64                                 0.6.5.4-1.fc23                                  @zfs

**Comment by mpiermar** [comment]
Here is  Docker debug output.  Note, I changed the zfs pool name (to "test") from the above initial report.

**$ sudo docker run -it -d --name t1 busybox /bin/sh**
242e894ce04abf12b8e91a959390f21b22678c196a6ac119d462904e5aacb55e

```
DEBU[0038] Calling POST /v1.22/containers/create        
DEBU[0038] POST /v1.22/containers/create?name=t1        
DEBU[0038] form data: {"AttachStderr":false,"AttachStdin":false,"AttachStdout":false,"Cmd":["/bin/sh"],"Domainname":"","Entrypoint":null,"Env":[],"HostConfig":{"Binds":null,"BlkioDeviceReadBps":null,"BlkioDeviceReadIOps":null,"BlkioDeviceWriteBps":null,"BlkioDeviceWriteIOps":null,"BlkioWeight":0,"BlkioWeightDevice":null,"CapAdd":null,"CapDrop":null,"CgroupParent":"","ConsoleSize":[0,0],"ContainerIDFile":"","CpuPeriod":0,"CpuQuota":0,"CpuShares":0,"CpusetCpus":"","CpusetMems":"","Devices":[],"Dns":[],"DnsOptions":[],"DnsSearch":[],"ExtraHosts":null,"GroupAdd":null,"IpcMode":"","Isolation":"","KernelMemory":0,"Links":null,"LogConfig":{"Config":{},"Type":""},"Memory":0,"MemoryReservation":0,"MemorySwap":0,"MemorySwappiness":-1,"NetworkMode":"default","OomKillDisable":false,"OomScoreAdj":0,"PidMode":"","PidsLimit":0,"PortBindings":{},"Privileged":false,"PublishAllPorts":false,"ReadonlyRootfs":false,"RestartPolicy":{"MaximumRetryCount":0,"Name":"no"},"SecurityOpt":null,"ShmSize":0,"UTSMode":"","Ulimits":null,"VolumeDriver":"","VolumesFrom":null},"Hostname":"","Image":"busybox","Labels":{},"NetworkingConfig":{"EndpointsConfig":{}},"OnBuild":null,"OpenStdin":true,"StdinOnce":false,"StopSignal":"SIGTERM","Tty":true,"User":"","Volumes":{},"WorkingDir":""} 
DEBU[0038] [zfs] zfs snapshot test/docker/9e363cfe3a84553f53be4f8c6d55175cc60e74e52a038d6a8ad466f71a96feb8@860270224 
DEBU[0039] [zfs] zfs get -Hp all test/docker/9e363cfe3a84553f53be4f8c6d55175cc60e74e52a038d6a8ad466f71a96feb8@860270224 
DEBU[0039] [zfs] zfs clone -p -o mountpoint=legacy test/docker/9e363cfe3a84553f53be4f8c6d55175cc60e74e52a038d6a8ad466f71a96feb8@860270224 test/docker/dd0f85acdda0e97bdd6fcc8121769d189de173b9df0dff8745767be4b5f8f824-init 
DEBU[0040] [zfs] zfs get -Hp all test/docker/dd0f85acdda0e97bdd6fcc8121769d189de173b9df0dff8745767be4b5f8f824-init 
DEBU[0040] [zfs] zfs destroy -d test/docker/9e363cfe3a84553f53be4f8c6d55175cc60e74e52a038d6a8ad466f71a96feb8@860270224 
DEBU[0040] [zfs] mount("test/docker/dd0f85acdda0e97bdd6fcc8121769d189de173b9df0dff8745767be4b5f8f824-init", "/var/lib/docker/zfs/graph/dd0f85acdda0e97bdd6fcc8121769d189de173b9df0dff8745767be4b5f8f824-init", "") 
DEBU[0040] [zfs] unmount("/var/lib/docker/zfs/graph/dd0f85acdda0e97bdd6fcc8121769d189de173b9df0dff8745767be4b5f8f824-init") 
DEBU[0041] [zfs] zfs snapshot test/docker/dd0f85acdda0e97bdd6fcc8121769d189de173b9df0dff8745767be4b5f8f824-init@59453535 
DEBU[0041] [zfs] zfs get -Hp all test/docker/dd0f85acdda0e97bdd6fcc8121769d189de173b9df0dff8745767be4b5f8f824-init@59453535 
DEBU[0041] [zfs] zfs clone -p -o mountpoint=legacy test/docker/dd0f85acdda0e97bdd6fcc8121769d189de173b9df0dff8745767be4b5f8f824-init@59453535 test/docker/dd0f85acdda0e97bdd6fcc8121769d189de173b9df0dff8745767be4b5f8f824 
DEBU[0042] [zfs] zfs get -Hp all test/docker/dd0f85acdda0e97bdd6fcc8121769d189de173b9df0dff8745767be4b5f8f824 
DEBU[0042] [zfs] zfs destroy -d test/docker/dd0f85acdda0e97bdd6fcc8121769d189de173b9df0dff8745767be4b5f8f824-init@59453535 
DEBU[0042] [zfs] mount("test/docker/dd0f85acdda0e97bdd6fcc8121769d189de173b9df0dff8745767be4b5f8f824", "/var/lib/docker/zfs/graph/dd0f85acdda0e97bdd6fcc8121769d189de173b9df0dff8745767be4b5f8f824", "") 
DEBU[0043] container mounted via layerStore: /var/lib/docker/zfs/graph/dd0f85acdda0e97bdd6fcc8121769d189de173b9df0dff8745767be4b5f8f824 
DEBU[0043] [zfs] unmount("/var/lib/docker/zfs/graph/dd0f85acdda0e97bdd6fcc8121769d189de173b9df0dff8745767be4b5f8f824") 
DEBU[0043] Calling POST /v1.22/containers/242e894ce04abf12b8e91a959390f21b22678c196a6ac119d462904e5aacb55e/start 
DEBU[0043] POST /v1.22/containers/242e894ce04abf12b8e91a959390f21b22678c196a6ac119d462904e5aacb55e/start 
DEBU[0043] [zfs] mount("test/docker/dd0f85acdda0e97bdd6fcc8121769d189de173b9df0dff8745767be4b5f8f824", "/var/lib/docker/zfs/graph/dd0f85acdda0e97bdd6fcc8121769d189de173b9df0dff8745767be4b5f8f824", "") 
DEBU[0043] container mounted via layerStore: /var/lib/docker/zfs/graph/dd0f85acdda0e97bdd6fcc8121769d189de173b9df0dff8745767be4b5f8f824 
DEBU[0043] Assigning addresses for endpoint t1's interface on network bridge 
DEBU[0043] RequestAddress(LocalDefault/172.17.0.0/16, <nil>, map[]) 
DEBU[0043] Assigning addresses for endpoint t1's interface on network bridge 

```

**$ sudo docker cp run.sh t1:/tmp/run.sh**

```
DEBU[0088] Calling HEAD /v1.22/containers/t1/archive    
DEBU[0088] HEAD /v1.22/containers/t1/archive?path=%2Ftmp%2Frun.sh 
DEBU[0088] [zfs] mount("test/docker/dd0f85acdda0e97bdd6fcc8121769d189de173b9df0dff8745767be4b5f8f824", "/var/lib/docker/zfs/graph/dd0f85acdda0e97bdd6fcc8121769d189de173b9df0dff8745767be4b5f8f824", "") 
DEBU[0088] container mounted via layerStore: /var/lib/docker/zfs/graph/dd0f85acdda0e97bdd6fcc8121769d189de173b9df0dff8745767be4b5f8f824 
DEBU[0088] [zfs] unmount("/var/lib/docker/zfs/graph/dd0f85acdda0e97bdd6fcc8121769d189de173b9df0dff8745767be4b5f8f824") 
ERRO[0088] Handler for HEAD /v1.22/containers/t1/archive returned error: lstat /var/lib/docker/zfs/graph/dd0f85acdda0e97bdd6fcc8121769d189de173b9df0dff8745767be4b5f8f824/tmp/run.sh: no such file or directory 
DEBU[0088] Calling PUT /v1.22/containers/t1/archive     
DEBU[0088] PUT /v1.22/containers/t1/archive?noOverwriteDirNonDir=true&path=%2Ftmp 
DEBU[0088] [zfs] mount("test/docker/dd0f85acdda0e97bdd6fcc8121769d189de173b9df0dff8745767be4b5f8f824", "/var/lib/docker/zfs/graph/dd0f85acdda0e97bdd6fcc8121769d189de173b9df0dff8745767be4b5f8f824", "") 
ERRO[0088] Handler for PUT /v1.22/containers/t1/archive returned error: error creating zfs mount of test/docker/dd0f85acdda0e97bdd6fcc8121769d189de173b9df0dff8745767be4b5f8f824 to /var/lib/docker/zfs/graph/dd0f85acdda0e97bdd6fcc8121769d189de173b9df0dff8745767be4b5f8f824: device or resource busy 
``

**Comment by estesp** [comment]
I haven't had a chance to understand why Docker 1.9.1 worked, other than a timing/race difference seems like a possible explanation.

Regardless, it seems that one major difference between the zfs storage driver and all the rest is that it doesn't handle the case of a layer already being mounted in the Get()/Put() implementation.  All the other drivers have an "active" hash for the layer ID, and only return the path from Get() instead of mounting the same layer yet-again. The device/resource busy when the container is running seems to be related to the fact that it was just double mounted and then unmounted (to check the target path), and now for the actual copy command, is trying to be mounted again.  An strace seems to show that there may actually be a race regarding the unmount actually completing in time, hence the "busy" response.

I think the right fix is for the Get() and Put() implementation to use the same reference counting/"active" hash implementation in the other storage drivers.  A workaround is to stop the container temporarily and perform the `docker cp`--which works fine as there is no race or double mount/unmount of the container layers.

**Comment by mpiermar** [comment]
@estesp - I will reload 1.9.1 and verify it didnt' work there either.   I *could* be mistaken, as that dev box was using devicemapper (vs. ZFS).  I could have sworn we loaded ZFS in the 1.9.1 timeframe, but might have done both 1.10 and zfs at the same time.  Thanks for looking in this and providing a workaround.
