### ISSUE TITLE
Support EXEC for evaluating commands without /bin/sh available yet

### ISSUE THREAD

**Issue by mcandre** [docker/docker#20159]
In keeping with Docker best practices, I want to avoid using `ADD` during my stage3 Gentoo install, using something like

```
COPY tar /tar
COPY stage3.tar.bz2 /stage3.tar.bz2
EXEC ["/tar", "-C", "/", "-xvf", "/stage3.tar.bz2"]
RUN ... rest && \
    of && \
    Gentoo && \
    install && \
    commands && \
    here ...
```

Could we get a feature like `EXEC`, so we can finally move away from `ADD`?

**Comment by duglin** [comment]
@mcandre not following - why can't you just use RUN instead of EXEC at that spot?

**Comment by LK4D4** [comment]
Closing as it's unclear from issue what feature it should be. Feel free to open new issue.
