### ISSUE TITLE
Environment variable type of array not working

### ISSUE THREAD

**Issue by sirateck** [docker/docker#20169]
I try to set an environment variable as array but it's seem not working.
I tried with -e, --env and --env-file arguments of run command.

I didn't find anything about this case, so I open this issue.

`docker version`: Docker version 1.10.0, build 590d5108

I set a variable like this: `ARRAY=("foo" "bar" "foobar")`

My Dockerfile:
```
FROM debian:jessie

COPY display-array.sh /display-array
ENTRYPOINT ["/display-array"]
```

Entrypoint's script:
```
#!/bin/bash

echo "Test with an environment variable as array passed to run command"
echo "Count elements in ARRAY: "${#ARRAY[*]}
echo "List of elements: "${ARRAY[@]}
if [ ! ${#ARRAY[*]} = 0 ]; then
	cnt_elmt=$((${#ARRAY[*]} - 1))
	for i in `seq 0 $cnt_elmt`
	do
		echo "Element $i = "${ARRAY[$i]}
	done
fi

printf "\nTest with the same environment variable as array assigned directly in bash script\n"
ARRAY=("foo" "bar" "foobar")
echo "Count elements in ARRAY: "${#ARRAY[*]}
echo "List of elements: "${ARRAY[@]}
if [ ! ${#ARRAY[*]} = 0 ]; then
	cnt_elmt=$((${#ARRAY[*]} - 1))
	for i in `seq 0 $cnt_elmt`
	do
		echo "Element $i = "${ARRAY[$i]}
	done
fi

exec "$@"
```

Build command: `docker build -t jessie .`

Run commands tried:
`docker run -it --rm -e "ARRAY=("foo" "bar" "foobar")"  jessie`

`docker run -it --rm --env "ARRAY=("foo" "bar" "foobar")"  jessie`

`docker run -it --rm --env-file ./array.env jessie`

With this content in array.env file:
`ARRAY=("foo" "bar" "foobar")`

Result:

```
Test with an environment variable as array passed to run command
Count elements in ARRAY: 1
List of elements: ("foo" "bar" "foobar")
Element 0 = ("foo" "bar" "foobar")

Test with the same environment variable as array assigned directly in bash script
Count elements in ARRAY: 3
List of elements: foo bar foobar
Element 0 = foo
Element 1 = bar
Element 2 = foobar
```

The variable value has been treated like a string not an array.
I don't understand this behavior.

Note: 
For the moment, I assign a value separated by a comma like this: `ARRAY=foo,bar,foo bar`
And i transform it with this code: `IFS=',' read -r -a ARRAY <<< "$ARRAY"`

Thanks for the help.

**Comment by duglin** [comment]
@sirateck Docker only supports single values env vars, not arrays.

**Comment by sirateck** [comment]
Thanks for your answer @duglin !

But where is this information ?

**Comment by duglin** [comment]
@sirateck probably falls into the category of "we didn't say we support it, therefore we don't".  :-)
But, see if this PR helps any: #20173 
If not let me know and we can work on some more wording.

**Comment by sirateck** [comment]
This is perfect for me.
And yes I am falling into this category type :wink: 

Thanks for your time @duglin

**Comment by sjatgutzmann** [comment]
I would like to see this as a new feature.
So I can use a flexible way to make a envirovent. e.g. if several service containers use one database container. Using in yaml compose config like:
    environment:
      - PG_CREATE_USER:
        - sonar
        - archiva
      - PG_CREATE_PASSWORD:
        - sonar
        - archiva
      - PG_CREATE_DB:
        - sonar
        - archiva_users

**Comment by thaJeztah** [comment]
POSIX shell does not have array types, so we cannot support this.

@sjatgutzmann I would discourage putting those credentials in the docker-compose file itself; perhaps an env-file per service would help there? https://docs.docker.com/compose/compose-file/#/envfile
