### ISSUE TITLE
Document the fact that dotted labels will break the default configuration of logstash

### ISSUE THREAD

**Issue by jpetazzo** [docker/docker#20168]
I have an ELK cluster, configured to accept logs over a GELF socket, reachable on `$GELFADDR:$GELFPORT`.

If I send simple container logs to it, all is fine:

```
docker run --log-driver gelf --log-opt gelf-address=udp://$GELFADDR:$GELFPORT \
  alpine echo hello world
```
→ The `hello world` log line shows up in Kibana. *Alles gut.*

If I annotate the logs with a simple label, it still works:

```
docker run --log-driver gelf --log-opt gelf-address=udp://$GELFADDR:$GELFPORT \
  --log-opt labels=mylabel -l mylabel=myvalue \
  alpine echo hello world
```
→ The log line (with the `mylabel=myvalue` custom field) shows up in Kibana.

However, if I put a dot in the label name:
```
docker run --log-driver gelf --log-opt gelf-address=udp://$GELFADDR:$GELFPORT \
  --log-opt labels=my.label -l my.label=myvalue \
  alpine echo hello world
```
→ The logstash logs show an error, because `.` is forbidden in field names.

This wouldn't be a big deal, if we weren't advocating the use of dotted labels (e.g. `com.docker.compose.project`).

There are multiple workarounds:
- install the `de_dot` filter in logstash (but it doesn't ship by default; so it adds extra hoops compared to just using the stock logstash image from the registry)
- add a custom Ruby filter to mangle the field names (super hackish, but works without authoring new images, just adding a few lines to the logstash config:
```
filter {
  ruby {
    code => "
      event.to_hash.keys.each { |k| event[ k.gsub('.','_') ] = event.remove(k) if k.include?'.' }
     "
  }
}
```

(For the curious: see this [longer thread](https://discuss.elastic.co/t/field-name-cannot-contain/33251/12) about the issue with ElasticSearch))

At the very least, we should document that in the [logging section](https://docs.docker.com/engine/admin/logging/overview/).

If you want help to reproduce this behavior, I can provide Compose files to stage up an ELK cluster in a snap.

/cc @moxiegirl

**Comment by nwright-nz** [comment]
I'm happy to pick this up. Just tested and was able to reproduce without any drama.Should there be a recommended approach here? Or just document the workarounds and leave it up to the individual? Seems that the de_dot filter is a 'last resort' filter, and has performance issues.

**Comment by thaJeztah** [comment]
@jpetazzo could you reopen this in the https://github.com/docker/docker.github.io issue tracker? That's were these docs moved
