### ISSUE TITLE
Cgroup mounting fails in docker, device busy or not available

### ISSUE THREAD

**Issue by thebillkidy** [docker/docker#20162]
`docker version:` 1.10

So currently, I am trying to get a docker image to create and manage virtual environments on the container. So this container has privileged set, the pid flag set to true and the net flag set to host so that I am able to manage my hypervisor.

Now whenever I try to get the cgconfig started it keeps failing with this error message:

```
Starting cgconfig service: Error: cannot mount cpu to /cgroup/cpu: Device or resource busy
/sbin/cgconfigparser; error loading /etc/cgconfig.conf: Cgroup mounting failed
Failed to parse /etc/cgconfig.conf                           [FAILED]
```

Is there someone that has encountered this problem before and can help me with it? Thanks! (P.S. My linux kernel is v3.10)

**Comment by thebillkidy** [comment]
Never mind, solved it. The problem was that the /cgroup/cpu,cpuacct was not mounted. So manually mounting this one solved this problem for me.

**Comment by yanue** [comment]
cgclear
