### ISSUE TITLE
First run detection

### ISSUE THREAD

**Issue by dgommeren** [docker/docker#20189]
Sometimes when a container is run for the first time, it needs to perform some additional tasks (like further configuration). It would be great if there was an environment variable DOCKER_CONTAINER_FIRST_RUN which would return true if it was the first run, or false on any further runs.

Specific case: I have containers that use Tomcat that need special configuration in the server.xml to indicate they are behind a proxy, but not all containers would need that. Those that need I would start with an environment variable BEHIND_PROXY=true and if I could then also check the above variable, I can easily detect if I need to still change the server.xml or not. I could write a file myself as indicator, but that's a bit ugly.

**Comment by thaJeztah** [comment]
Thanks for suggesting. I think the general approach is to do this in an entrypoint script (e.g. https://github.com/docker-library/mysql/blob/ed198ce2e8aa78613c615f20c5c4dd09fa450f66/5.7/docker-entrypoint.sh#L13). Not sure if we should add this as a feature, but perhaps other maintainers have a different opinion.

**Comment by dgommeren** [comment]
That's what I've been doing until now. Even nicer would be to have FIRST_RUN entrypoints :)
That way parent images and child images could have independent scripts executed for initialisation.

**Comment by thaJeztah** [comment]
Well, there's `ON_BUILD` if you're inheriting images :innocent:

**Comment by dgommeren** [comment]
I would need to create separate images for proxied or not. Maybe not such a bad idea in any case. Will use that.

**Comment by skairali** [comment]
@thaJeztah   is this closed based on above comments.?

**Comment by thaJeztah** [comment]
@skairali it's not close yet, but I'm tempted to.

@dgommeren are you able to work with the current options?

**Comment by dgommeren** [comment]
It still would make sense to have it, but if nobody else needs it, it can be closed
