### ISSUE TITLE
Plugins docs: no mention of remote plugins + socket activation

### ISSUE THREAD

**Issue by runcom** [docker/docker#20188]
Quoting the doc:
> A plugin is a process running **on the same docker host** as the docker daemon, which registers itself by placing a file in one of the plugin directories described in Plugin discovery.

This is not entirely true because I can have a plugin listening on a domain/ip which can be located outside the daemon host (using the spec or json file).

Also, systemd socket activation isn't mentioned anywhere in the docs.

**Comment by runcom** [comment]
ping @moxiegirl @thaJeztah

**Comment by yongtang** [comment]
The systemd socket activation seems to have been covered by https://github.com/docker/docker/pull/21043

The remote plugin is not covered yet in the current docs. I can create a pull request to give it a try.
