### ISSUE TITLE
Docker does not start containers in CentOS when user namespaces activated

### ISSUE THREAD

**Issue by SergeyYakubov** [docker/docker#20193]
`docker run hello-world`

**produces message:**

docker: Error response from daemon: Cannot start container b7dddfefa6d35618de34880e5660295d6192dbde035c9f3b3e6ba13d81257364: [9] System error: fork/exec /proc/self/exe: invalid argument.

**when executed on CentOS 7.2 and activated user spacenames. Same task works on Ubuntu without problems.**

**docker version**:
Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:34:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:34:50 2016
 OS/Arch:      linux/amd6

**docker info**:
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 2
Server Version: 1.10.0
Storage Driver: devicemapper
 Pool Name: docker-8:6-389546-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 538.1 MB
 Data Space Total: 107.4 GB
 Data Space Available: 8.871 GB
 Metadata Space Used: 1.053 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/100000.100000/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/100000.100000/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.4.5.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.635 GiB
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

**uname -a:**
Linux host.desy.de 3.10.0-327.4.5.el7.x86_64 #1 SMP Mon Jan 25 22:07:14 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Tried both on physical machine and VirtualBox with fresh installed system.

**User namespaces were activated in**:
/etc/systemd/system/docker.service.d/docker.conf
[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon -H fd:// --userns-remap="default"

**Server starts normally**:
`systemctl` start docker`
`cat /var/log/messages | grep docker`:
Feb 10 16:25:17 it-hpc-fsadm01 docker: time="2016-02-10T16:25:17.748378068+01:00" level=info msg="User namespaces: ID ranges will be mapped to subuid/subgid ranges of: dockremap:dockremap"
Feb 10 16:25:17 it-hpc-fsadm01 docker: time="2016-02-10T16:25:17.760008372+01:00" level=warning msg="devmapper: Usage of loopback devices is strongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use `man docker` to refer to dm.thinpooldev section."
Feb 10 16:25:17 it-hpc-fsadm01 docker: time="2016-02-10T16:25:17.811965472+01:00" level=info msg="[graphdriver] using prior storage driver \"devicemapper\""
Feb 10 16:25:17 it-hpc-fsadm01 docker: time="2016-02-10T16:25:17.814671112+01:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Feb 10 16:25:17 it-hpc-fsadm01 docker: time="2016-02-10T16:25:17.821525089+01:00" level=info msg="Firewalld running: false"
Feb 10 16:25:17 it-hpc-fsadm01 docker: time="2016-02-10T16:25:17.891543173+01:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Feb 10 16:25:17 it-hpc-fsadm01 docker: time="2016-02-10T16:25:17.956053903+01:00" level=info msg="Loading containers: start."
Feb 10 16:25:17 it-hpc-fsadm01 docker: ..
Feb 10 16:25:17 it-hpc-fsadm01 docker: time="2016-02-10T16:25:17.957847288+01:00" level=info msg="Loading containers: done."
Feb 10 16:25:17 it-hpc-fsadm01 docker: time="2016-02-10T16:25:17.957877403+01:00" level=info msg="Daemon has completed initialization"
Feb 10 16:25:17 it-hpc-fsadm01 docker: time="2016-02-10T16:25:17.957914839+01:00" level=info msg="Docker daemon" commit=590d5108 execdriver=native-0.2 graphdriver=devicemapper version=1.10.0
Feb 10 16:25:17 it-hpc-fsadm01 docker: time="2016-02-10T16:25:17.968071552+01:00" level=info msg="API listen on /var/run/docker.sock"

**Then comes the problem**:
`docker run hello-world`
`cat /var/log/messages | grep docker`:
Feb 10 16:28:22 it-hpc-fsadm01 NetworkManager[1263]: <info>  (docker0): bridge port vethf5ca51e was attached
Feb 10 16:28:22 it-hpc-fsadm01 NetworkManager[1263]: <info>  (vethf5ca51e): enslaved to docker0
Feb 10 16:28:22 it-hpc-fsadm01 kernel: docker0: port 1(vethf5ca51e) entered disabled state
Feb 10 16:28:22 it-hpc-fsadm01 kernel: docker0: port 1(vethf5ca51e) entered disabled state
Feb 10 16:28:22 it-hpc-fsadm01 NetworkManager[1263]: <warn>  (docker0): failed to detach bridge port vethf5ca51e
Feb 10 16:28:22 it-hpc-fsadm01 docker: time="2016-02-10T16:28:22.152382944+01:00" level=error msg="error locating sandbox id eee0f455f4be5c7fdebf3c98a711373b13cf1b06820809c004ddae109bad5f96: sandbox eee0f455f4be5c7fdebf3c98a711373b13cf1b06820809c004ddae109bad5f96 not found"
Feb 10 16:28:22 it-hpc-fsadm01 docker: time="2016-02-10T16:28:22.152486255+01:00" level=warning msg="failed to cleanup ipc mounts:\nfailed to umount /var/lib/docker/100000.100000/containers/c67a2391f2be7f6e82b645f2dcb6cf3f67d2e3bdac15963eefeda31141a9164a/shm: invalid argument\nfailed to umount /var/lib/docker/100000.100000/containers/c67a2391f2be7f6e82b645f2dcb6cf3f67d2e3bdac15963eefeda31141a9164a/mqueue: invalid argument"
Feb 10 16:28:22 it-hpc-fsadm01 docker: time="2016-02-10T16:28:22.152521902+01:00" level=error msg="Error unmounting container c67a2391f2be7f6e82b645f2dcb6cf3f67d2e3bdac15963eefeda31141a9164a: not mounted"
Feb 10 16:28:22 it-hpc-fsadm01 docker: time="2016-02-10T16:28:22.152634245+01:00" level=error msg="Handler for POST /v1.22/containers/c67a2391f2be7f6e82b645f2dcb6cf3f67d2e3bdac15963eefeda31141a9164a/start returned error: Cannot start container c67a2391f2be7f6e82b645f2dcb6cf3f67d2e3bdac15963eefeda31141a9164a: [9] System error: fork/exec /proc/self/exe: invalid argument

**Comment by SergeyYakubov** [comment]
/etc/subuid and /etc/subgid had to be created manually (with content), otherwise daemon did not start.
```
echo dockremap:100000:65536 > /etc/subuid
echo dockremap:100000:65536 > /etc/subgid

```

**Comment by cpuguy83** [comment]
@SergeyYakubov Did adding these files fix the issue for you?

**Comment by SergeyYakubov** [comment]
@cpuguy83 No, they just made daemon start

**Comment by estesp** [comment]
I wonder if we will need a documentation comment on this--I just debugged this last week only to find out that it is the `clone()` syscall failing with "Invalid argument", because the RHEL7/CentOS7 kernel configuration disables user namespaces by default as an "experimental only" feature.

To enable you need to follow this comment's instructions: http://rhelblog.redhat.com/2015/07/07/whats-next-for-containers-user-namespaces/#comment-6796

**Comment by thaJeztah** [comment]
@estesp sgtm, perhaps we should also update the check-config script to check for this, if possible? https://github.com/docker/docker/blob/master/contrib/check-config.sh

**Comment by SergeyYakubov** [comment]
Thank you, seems to work. Actually, I tried to set user_namespace.enable=1 via grubby before, but probably I did something wrong. Now I tried once more and docker starts.

Is there a simple way to check if user namespaces are enabled in a kernel?

**Comment by SergeyYakubov** [comment]
@estesp Now it starts and Docker seems to know about user namespaces - at least it does not allow to use --net=host and so on. But it does not seem to replace user id - if I create a file inside a container as a root it has root ownership outside of the container as well. How does it look for you?

**Comment by estesp** [comment]
@SergeyYakubov I don't have that experience (the files created inside a user namespaced container are owned by the remapped root (high UID >100000 usually). Our CI tests for user namespaces actually tests for this with every build, so would be good to understand how you get a different result.  If you post relevant details I can potentially help debug that.

@thaJeztah sorry for the delay--needed some time to dig into how to "query" without building/running a binary for this case on CentOS and RHEL.  I think I have a method now and need to create a PR.

**Comment by SergeyYakubov** [comment]
@estesp Now it seems I understand what's the problem - the host directory that I mount to the container  is part of the beegfs filesystem (we want to use Docker on an HPC cluster where this filesystem is used). When I mount some other one - from ext4 or nfs everything works fine.

Not clear whether this is my fault and I need to somehow setup beegfs inside the container or
just Docker cannot work with beegfs, or beegfs cannot work with user namespaces.

Here is an example:


#create cointainer mounting a beegfs directory
$ docker run -v  /home/test:/shared -it centos bash
$ touch /shared/aaa
$ ls -l /shared/aaa
-rw-r--r-- 1 root root 0 Feb 23 15:17 /shared/aaa

# we leave the container:
$ exit
# and check ownership
$ ls -l /home/test/aaa
-rw-r--r-- 1 root root 0 Feb 23 16:17 /home/test/aaa
# stiil a root!

#same with nfs:

$ docker run -v /data/netapp/test/:/shared -it centos bash
$ touch /shared/aaa
$ ls -l /shared/aaa
-rw-r--r-- 1 root root 0 Feb 23 15:22 /shared/aaa
$ exit
$ ls -la /data/netapp/test/aaa
-rw-r--r-- 1 100010 100010 0 Feb 23 16:22 /data/netapp/test/aaa # not a root!

**Comment by estesp** [comment]
@SergeyYakubov this got auto-closed by the nature we had 2 discussions going on under the same issue.  I realize your beegfs issue is still outstanding, and if you want to open another issue to track that, that's fine with me.

However, I think if you have any contact with the beegfs community, it would be interesting to understand why they don't seem to handle user namespaces properly with whatever their implementation/connection is to the kernel's VFS layer.  As you noted, NFS and local filesystems all work properly with assigning the proper ownership to files created by the remapped root inside the container.

**Comment by beatscode** [comment]
Is it best practice to do what @SergeyYakubov did and just create the subuid,gid files yourself when they don't exist? Or is there a step I am missing.  FYI, i'm using CentOS 7
