### ISSUE TITLE
Remote API, 1.22 generates wrong JSON properties for /events

### ISSUE THREAD

**Issue by megastef** [docker/docker#20194]
Hi, 

when I collect events from Docker API (server reports 1.22) I get e.g. this
```
{
  "Type": "network",
  "Action": "connect",
  "Actor": {
    "ID": "085fea92eefc9b89d7bbb96e7c07b695c81fa3f5248c066088c5fa7e6ae026c3",
    "Attributes": {
      "container": "e83a12c3872f5d4415aaa5ba165cf30268fb229e20dae84686c212a8c05a6220",
      "name": "bridge",
      "type": "bridge"
    }
  },
  "time": 1455115964,
  "timeNano": 1455115964417484500
}
```

But the documentation describes the JSON properties names in lower case:
https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api_v1.22.md#monitor-dockers-events

e.g. 
```
{
    "action": "create",
    "type": "container",
    "actor": {
        "id": "5745704abe9caa5",
        "attributes": {"image": "busybox"}
    }
    "time": 1442421716,
    "timeNano": 1442421716853979870
    }
```

**Comment by davinashreddy** [comment]
#dibs

**Comment by drsect0r** [comment]
What is currently the status of this? I have the same problem.

**Comment by thaJeztah** [comment]
Looks like the API docs wasn't updated correctly for the new response. Let me open a PR to fix that

**Comment by thaJeztah** [comment]
see https://github.com/docker/docker/issues/20194
