### ISSUE TITLE
Installation fails on Ubuntu 16.04 (Xenial Xerus)

### ISSUE THREAD

**Issue by bpierre** [docker/docker#20192]
The reason is that the Ubuntu Xenial packages are not on `apt.dockerproject.org`: https://apt.dockerproject.org/repo/dists/

Shouldn’t the install script provide some “unsupported version” information instead of trying to install a non existent package?

**Comment by daehyeok** [comment]
Can i know how to try install Docker in 16.04? Source comile?

**Comment by thaJeztah** [comment]
We could consider adding xenial to the experimental repository

**Comment by faddat** [comment]
@thaJeztah That'd be very nice.  I like the new ubuntu, but need my docker a wohole bunch!

**Comment by thaJeztah** [comment]
If someone is interested in opening a pull-request for this, then we can see if the other maintainers think we're ready for adding xenial? Dockerfiles for other versions can be found here; https://github.com/docker/docker/tree/master/contrib/builder/deb/amd64. The install script (https://github.com/docker/docker/blob/master/hack/install.sh) and documentation (https://github.com/docker/docker/blob/master/docs/installation/linux/ubuntulinux.md) will need an update as well

**Comment by ruphin** [comment]
I'm facing the same issue. I will try to have a pull-request for this before the end of the weekend. If anyone else is working on it, please leave a message :)

**Comment by faddat** [comment]
@ruphin Interested in working on this with you.  I'd like to see how it all goes down :).

**Comment by ruphin** [comment]
@faddat So far there's nothing much exciting going on. I just made sure the build container for xenial looked like the one for wily, as I don't think much has changed. I'm running the build scripts now to verify that nothing is broken, if everything works I'll be updating the installer script and docs.

You can follow my progress here: https://github.com/ruphin/docker/tree/20192-ubuntu_16.04_installer

I'm by no means an expert, just someone who badly needs Docker installed on their 16.04 system. :)
If you have any suggestions feel free to tag along.

**Comment by ruphin** [comment]
I got a working build. I'll write the install script changes and docs tomorrow, and make a PR.

**Comment by thaJeztah** [comment]
Thanks @ruphin, we may need to check the release schedule (https://wiki.ubuntu.com/XenialXerus/ReleaseSchedule) to decide when we want to start supporting Xenial; I'm good (personally) to have it in experimental builds, but we should be careful adding it to the "stable" (regular) builds if Xenial is not stable yet. I'll let that to the other maintainers for discussion/decide.

For those wanting to install now; downloading a static build (https://docs.docker.com/engine/installation/binaries/) should work; probably using the "Wily" repository should work as well, but I haven't tested (https://docs.docker.com/engine/installation/linux/ubuntulinux/)

**Comment by bpierre** [comment]
Great!

Shouldn’t the install script test if the Ubuntu version is one of the supported one before going further? At the moment, the script tries to install Docker from a non-existent repository, which fails without any explanation. It is pretty common to use a non-released or an outdated version, and explaining why the installation is not possible could provide a better experience.

**Comment by thaJeztah** [comment]
Well, there *is* a warning, but possibly it's not triggered in this case, because it detected the platform, but not the version; https://github.com/docker/docker/blob/5e0b8b99d115bc6b12d930e80aca69fecc7dda78/hack/install.sh#L481-L486

**Comment by jlukic** [comment]
@ruphin it looks like the link to your forked install script is broken. is there a more updated link? Trying to figure out a decent solve for this on new 16.04 machine.

**Comment by ruphin** [comment]
Unfortunately had some delays. I have a working build, but didn't get around to making a pull request yet.

@thaJeztah Last I checked the build scripts fail in the current tip of master, so I based my branch off the latest stable release so I could build and verify it works. If I make a pull request, should I base it off master, even if the build process fails?

@jlukic My current build is here: https://github.com/ruphin/docker/tree/20192-ubuntu-xenial-installer
If you want to build a .deb package for Xenial to install locally, you can check out that branch, and run `make deb` in the project root. It will deliver .deb files in `bundles/latest/build-deb/`.

It will build packages for all supported debian and ubuntu releases, and it will take a long time. To only build the Xenial package and skip other releases, go to `contrib/builder/deb` and remove all folders except `ubuntu-xenial` before running `make deb`.

Do not forget to install the required prerequisites first. You may also need to add your user to the docker group, and perform other small steps outlined in the manual: https://github.com/ruphin/docker/blob/20192-ubuntu-xenial-installer/docs/installation/linux/ubuntulinux.md

**Comment by thaJeztah** [comment]
@ruphin yes, you should base it of master; CI breaking has to do with some flaky tests, and we've been dealing with some issues in the test infrastructure (connection issues between cloud providers etc).

**Comment by jlukic** [comment]
Thanks @ruphin, I will check it out

**Comment by tilgovi** [comment]
1.10.2 is in the Ubuntu repos for Xenial now.

**Comment by thaJeztah** [comment]
@tilgovi we still need it in this repository as well; point is that those packages are built / packaged by Ubuntu; we should have them here as well so that CI can run, and users can download the official packages from apt.dockerproject.org

**Comment by tilgovi** [comment]
Yes, that's well understood. My purpose was only to inform anyone watching this issue, that they may wish to opt for using that when configuring Xenial boxes in the meantime.

**Comment by thaJeztah** [comment]
@tilgovi haha, no problem; just thought I'd be clear, to prevent people thinking "problem solved, we're done"

**Comment by dutch2005** [comment]
Confirming that using the willy repository works on xenial, keep up the good work tho :)

**Comment by jiapei100** [comment]
I've got exactly the same problem... Docker fail to work on Ubuntu 16.04 Xenial so far...

**Comment by kayhu** [comment]
I just follow the steps in installation page https://docs.docker.com/engine/installation/linux/ubuntulinux/, 
command apt-cache policy docker-engine returns: Unable to locate package docker-engine.
This happens when using apt-get install docker-engine as well

**Comment by iqqmuT** [comment]
Now the deb package is found from the repository, installation works well.

**Comment by lubozhan** [comment]
I also has the same issue when following [](https://docs.docker.com/engine/installation/linux/ubuntulinux/).
Command apt-cache policy docker-engine returns: Unable to locate package docker-engine.
This happens when using apt-get install docker-engine as well.

Is there any solution?

**Comment by faddat** [comment]
Try:

wget get.docker.io
sh index.html

Or similar.  This should run an auto install script.  If it doesn't work
then, then unfortunately I don't know enough about your environment to
advise.
