### ISSUE TITLE
Blank Engine User Guide in docs

### ISSUE THREAD

**Issue by toastynerd** [docker/docker#20204]
The current page for https://docs.docker.com/v1.10/engine/userguide/ is blank. It looks like the information that used to be there, such the information found in https://docs.docker.com/v1.8/userguide/ is now located at https://docs.docker.com/engine/userguide/intro/ but the only part of the docs that uses that link is the sidebar. The rest of the links still use either 'userguide/' or 'userguide/index'. I'm having difficulty finding the sidebar code but it seems like an easy fix to move the `userguide/intro.md` to `userguide/index.md` and then point the userguide introduction link found in the sidebar to that end point or change all the links from other documents to point to the intro. Not sure which way it should go but I can make PR if need be.

**Comment by thaJeztah** [comment]
looks like this is solved for the "non-versioned" URL through https://github.com/docker/docker/pull/20285 (see https://docs.docker.com/engine/userguide/);

where did you find the `/v1.10/` URL? I don't think we currently provide a "versioned" URL for the current release, only for previous releases

**Comment by calavera** [comment]
yep, this is solved. Thanks for opening the issue. Closing as fixed.
