### ISSUE TITLE
Golint validation insists on CamelCase for (Windows) constants

### ISSUE THREAD

**Issue by jhowardmsft** [docker/docker#20212]
Windows constants such as errors are universally in ALL_CAPS, for example https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382(v=vs.85).aspx. But the golint validation forces CamelCase which is not appropriate for Windows code.

eg https://github.com/docker/docker/blob/master/daemon/execdriver/windows/run.go#L24-L31

I should point out that golangs syscall implementation uses ALL_CAPS too. Hence I believe that Dockers lint validation check is being overly preventative here. See https://golang.org/src/syscall/ztypes_windows.go

**Comment by LK4D4** [comment]
@jhowardmsft I'm going to close this prematurely. Feel free to reopen if you still have problems. Thanks!
