### ISSUE TITLE
Retrieving network (Veth) name for container

### ISSUE THREAD

**Issue by maran** [docker/docker#20224]
I'm trying to figure out if it's still possible to retrieve the network device name for docker containers in 1.9.

I used to be that the veth device name was giving in the state.json through out the various versions, in various formats. But in 1.9 I can't find any hint of this. 

It's making tracker bandwidth per container a bit harder (if not impossible) in my setup so I was hoping this was still hidden away somewhere.

If anybody is interested see #7510 for more context.

**Comment by runcom** [comment]
is this somehow a duplicate of https://github.com/docker/docker/issues/17064? if yes, can we keep tracking this there? :)

**Comment by maran** [comment]
It might be, depending on how you look at it. 

Mine is more a general question as to if it's still possible to retrieve the veth device from a config hidden away somewhere while the linked issue is about making it easier to get that info from the command-line regardless of where it's saved in the file system.

I would love the second one but for my immediate concern I am mainly looking to know whether the value is still being stored anywhere, even if it's hard to find.

I will leave it up to the powers that be to decide if this is a dup or not :)

**Comment by mavenugo** [comment]
@maran pls refer to my comment in #17064 : https://github.com/docker/docker/issues/17064#issuecomment-183160829. I don't think it is a good idea to provide a generic way at docker level to depend on a specific plumbing behavior of a particular driver. That severely restricts portability.

Having said that, if you are interested in the way the current bridge driver works (in 1.9 & 1.10), you can hack your way and find out the veth pair.

```
$ sudo docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                           NAMES
08b1a5b42aa9        nginx               "nginx -g 'daemon off"   2 hours ago         Up 2 hours          443/tcp, 0.0.0.0:8090->80/tcp   elated_euler

$ sudo docker inspect --format='{{.NetworkSettings.SandboxKey}}' 08b1a5b42aa9
/var/run/docker/netns/aea8f5968946

$ sudo nsenter --net=/var/run/docker/netns/aea8f5968946 ethtool -S eth0
NIC statistics:
     peer_ifindex: 308

$ sudo ip link | grep 308:
308: vetha0c705b: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP mode DEFAULT group default

```

Ofcourse I have `nsenter` & `ethtool` installed in my host.

**Comment by maran** [comment]
Thanks for the suggestion. I agree that this seems a very hacky way to do it and might break again in the future. 

Is there a less convoluted way to do per docker container iptables matching? I'm currently using `PHYSDEV match --physdev-in` so I need the veth device. In Docker 1.5 and 1.6 this was very trivial but I'm running into all kinds of issues now that would be fixed if I find a way to upgrade to more recent versions of docker.

**Comment by mavenugo** [comment]
@maran is there a reason why you are not using the container ip-address as your iptables rule ?

**Comment by maran** [comment]
@mavenugo Thank you, no there is absolutely no reason that shouldn't work. I've been stuck in tunnel vision and I did not even consider it.

I will try to implement it that way.

**Comment by mavenugo** [comment]
@maran thanks. that will be simplest & it is also portable across plugins and is also a reliable way to get the container ip-address(es) if it is connected to multiple networks

```
$ docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $INSTANCE_ID
```

WIth this, I guess we can close this issue ?

**Comment by maran** [comment]
Yes, feel free to close this up and thanks for snapping me out my tunnel :)

**Comment by ladams00** [comment]
I found this thread to be very helpful in locating specific containers through vethxx bridge member device.  Although the issue is closed, I wanted to comment on the thread's usefulness.

**Comment by welikecn** [comment]
I think it's better to use the command `nsenter -t ${PID} -n ethtool -S eth0` instead of `nsenter --net=${SandboxKey} ethtool -S eth0`. 
Because the fields `SandboxID` and `SandboxKey` are empty if the container reuse another container's network stack. However the `Pid` of a container MUST be exist.
For example, in Kubernetes, user's containers reuse the pause container's network stack.
in the pause container:
```bash
$ docker inspect --format='{{.NetworkSettings.SandboxID}}' 091c16481db2
2e9910f0736460a8e807715f325145727ba934e942950c4598bfc74761727d0f
$ docker inspect --format='{{.NetworkSettings.SandboxKey}}' 091c16481db2
/var/run/docker/netns/2e9910f07364
$ nsenter --net=/var/run/docker/netns/2e9910f07364 ethtool -S eth0
NIC statistics:
     peer_ifindex: 9
$ docker inspect --format='{{.State.Pid}}' 091c16481db2       
4011
$ nsenter -t 4011 -n ethtool -S eth0
NIC statistics:
     peer_ifindex: 9
```
in the containers which reusing this pause container's network stack:
```bash
# user's container
$ docker inspect --format='{{.NetworkSettings.SandboxID}}' 1e212b1f2436

$ docker inspect --format='{{.NetworkSettings.SandboxKey}}' 1e212b1f2436

$ docker inspect --format='{{.State.Pid}}' 1e212b1f2436
4088
$ nsenter -t 4088 -n ethtool -S eth0
NIC statistics:
     peer_ifindex: 9
```

**Comment by tribals** [comment]
The container interface peer index is specified directly in interface's name itself:

```console:
$ sudo nsenter --target ${PID_OF_DESIRED_CONTAINER} --net ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
27: eth0@if28: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default 
    link/ether 02:42:ac:12:00:02 brd ff:ff:ff:ff:ff:ff link-netnsid 0
```

Note the interface's name: `eth0@if28`. Let's inspect host interfaces (some containers launched, with both `docker run` and docker compose, and even custom docker network created):

```console
$ ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
<...snip...>
6: br-29b333cf5654: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default 
    link/ether 02:42:b2:3e:59:0d brd ff:ff:ff:ff:ff:ff
8: br-eff58d464a65: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default 
    link/ether 02:42:b9:ee:db:85 brd ff:ff:ff:ff:ff:ff
26: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default 
    link/ether 02:42:56:36:67:57 brd ff:ff:ff:ff:ff:ff
28: veth8531884@if27: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP mode DEFAULT group default 
    link/ether 0a:02:57:53:fc:4b brd ff:ff:ff:ff:ff:ff link-netnsid 0
30: veth7574332@if29: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP mode DEFAULT group default 
    link/ether ba:56:56:18:33:63 brd ff:ff:ff:ff:ff:ff link-netnsid 1
32: vetheb006ba@if31: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP mode DEFAULT group default 
    link/ether ea:1b:51:eb:b9:91 brd ff:ff:ff:ff:ff:ff link-netnsid 2
```

Note there is interface with number 28:

```
28: veth8531884@if27: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP mode DEFAULT group default 
    link/ether 0a:02:57:53:fc:4b brd ff:ff:ff:ff:ff:ff link-netnsid 0
```

That's it! No need for `ethtool`, only `nsenter` from `util-linux` and `ip` from `iproute2` needed, which most likely ship with any Linux distro.
