### ISSUE TITLE
"docker info" should display insecure registries

### ISSUE THREAD

**Issue by jmMeessen** [docker/docker#20236]
When requesting informations (via "docker info") about a docker daemon (or group of daemon in a swarm), an important information is the defined *insecure-registry*. 

Currently the only way (to my knowledge) to find this information is by displaying the command line of the daemon via "ps aux | grep docker".

**Comment by thaJeztah** [comment]
I guess we could include that information (although we recommend people not to use it).

Are you interested in contributing?

**Comment by jmMeessen** [comment]
I understand that this is not a recommended way to use a registry. But not
seeing this info (or be sure that it was picked up) gave me some gray hair
during a Docker on Raspberry Pi workshop.

I would be more then happy to contribute on that issue although I am still
a learner and thus not the fastes one.

Jmm

**Comment by thaJeztah** [comment]
Yes, I think the information could be useful.

No worries if you're not able to contribute yourself, perhaps someone else is interested

**Comment by tkopczynski** [comment]
I could work on this one if it's still available.

**Comment by thaJeztah** [comment]
@tkopczynski thanks, that'd be great! This probably requires changes in https://github.com/docker/engine-api as well, but you could start with making those changes here (which will result in the `vendor` CI check failing for now) and if "design" is approved, make those changes in the engine-api repository.

**Comment by jmMeessen** [comment]
I will not be able to start working on this before 3 weeks so, Tomasz,
you're welcome to pick it up.

Jmm

**Comment by thaJeztah** [comment]
I'd say "Go for it, @tkopczynski!" (thanks in advance, and if you need help, feel free to ping me, or ask somebody in the #docker-dev IRC channel

**Comment by tkopczynski** [comment]
@thaJeztah OK, thanks. I'll look into it later on and probably get back to you with some questions about how to handle those changes in separate repository (engine-epi)
