### ISSUE TITLE
Cannot create a user with custom UID on docker

### ISSUE THREAD

**Issue by bernadinm** [docker/docker#20248]
I have a docker file that pulls from ubuntu:14.04 and there is a step that creates a user with a custom UID that matches the host system.

When this runs on my laptop, my virtual box machine runs out of space. When I runs it against a baremetal server with enough space, it runs forever. 

For example:
Step 16 : RUN useradd -u 2147483632 mapr
 ---> Running in 62d81744c3e6

Does anyone know whats happening and why it does not complete in seconds?

**Comment by phemmer** [comment]
Yes, see #5419

**Comment by bernadinm** [comment]
Thank you @phemmer. I will close this then. Sorry for the duplicate ticket.
