### ISSUE TITLE
login help should not output explicit domain names

### ISSUE THREAD

**Issue by dmp42** [docker/docker#20255]
```
sudo docker login --help

Usage:    docker login [OPTIONS] [SERVER]

Register or log in to a Docker registry.
If no server is specified "https://index.docker.io/v1/" is the default.

 -e, --email=       Email
 --help=false       Print usage
 -p, --password=    Password
 -u, --username=    Username(edited)
```

The domain name or url of the Hub auth server may change overtime (and it did in the past). People tend to copy paste these and hardcode them into their dockerfiles, effectively shooting themselves in the foot and/or generating a lot of unsuspected traffic to deprecated domains / urls (eg: where only v1 registries are exposed).

We should rather replace it with "If no server is specified, this will login against the Docker Hub", or something in the line.

cc @aaronlehmann @dmcgowan

**Comment by YeZhenan** [comment]
#dibs

**Comment by thaJeztah** [comment]
This was updated and now looks like;

```
Usage:	docker login [OPTIONS] [SERVER]

Log in to a Docker registry.

Options:
      --help              Print usage
  -p, --password string   Password
  -u, --username string   Username
```
