### ISSUE TITLE
default apparmor profile is not 2.8 compatible

### ISSUE THREAD

**Issue by jordimassaguerpla** [docker/docker#20269]
How to reproduce it.

Have a box with apparmor 2.8 (not 2.8.95!!!!!)

Install docker 1.10.0

Start docker:
  sudo docker daemon

You'll see a message error regarding apparmor profile

**Comment by cyphar** [comment]
@thaJeztah This has been fixed in #20305.

**Comment by thaJeztah** [comment]
@cyphar thanks, looks like GitHub didn't auto close
