### ISSUE TITLE
Cannot start daemon - Failed to load layer - failed to get diff id - invalid checksum digest format

### ISSUE THREAD

**Issue by bcroq** [docker/docker#20267]
Description of problem: I cannot start the docker daemon:

```
# /usr/bin/docker daemon -H unix:///var/run/docker.sock -D

DEBU[0000] docker group found. gid: 142                 
DEBU[0000] Server created for HTTP on unix (/var/run/docker.sock) 
DEBU[0000] Using default logging driver json-file       
DEBU[0000] devicemapper: driver version is 4.34.0       
DEBU[0000] devmapper: Generated prefix: docker-8:2-3189280 
DEBU[0000] devmapper: Checking for existence of the pool docker-8:2-3189280-pool 
DEBU[0000] devmapper: Pool doesn't exist. Creating it.  
DEBU[0000] devmapper: loadDeviceFilesOnStart()          
DEBU[0000] devmapper: Loading data for file ...
...
DEBU[0000] devmapper: Skipping file /var/lib/docker/devicemapper/metadata/transaction-metadata 
DEBU[0000] devmapper: loadDeviceFilesOnStart() END      
DEBU[0000] devmapper: constructDeviceIDMap()            
DEBU[0000] devmapper: Added deviceId=5201 to DeviceIdMap 
...
DEBU[0000] devmapper: constructDeviceIDMap() END        
WARN[0000] devmapper: Usage of loopback devices is strongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use `man docker` to refer to dm.thinpooldev section. 
DEBU[0000] devmapper: activateDeviceIfNeeded()          
DEBU[0000] devmapper: UUID for device: /dev/mapper/docker-8:2-3189280-base is:8a0d9344-8414-4923-8eca-214e835384d5 
WARN[0000] devmapper: Base device already exists and has filesystem ext4 on it. User specified filesystem  will be ignored. 
DEBU[0000] devmapper: deactivateDevice()                
DEBU[0000] devmapper: removeDevice START(docker-8:2-3189280-base) 
DEBU[0000] devmapper: removeDevice END(docker-8:2-3189280-base) 
DEBU[0000] devmapper: deactivateDevice END()            
INFO[0000] [graphdriver] using prior storage driver "devicemapper" 
DEBU[0000] Using graph driver devicemapper              
DEBU[0000] Failed to load layer sha256:541b14873e1aabcdf967e1205ce3be564d6f4bf7d2c895250ab80a9211390e62: failed to get diff id for sha256:541b14873e1aabcdf967e1205ce3be564d6f4bf7d2c895250ab80a9211390e62: invalid checksum digest format 
DEBU[0000] devmapper: [deviceset docker-8:2-3189280] Shutdown() 
DEBU[0000] devmapper: Shutting down DeviceSet: /var/lib/docker/devicemapper 
DEBU[0000] devmapper: deactivateDevice()                
DEBU[0000] devmapper: deactivateDevice END()            
DEBU[0000] devmapper: deactivatePool()                  
DEBU[0000] devmapper: deactivatePool END                
DEBU[0000] devmapper: [deviceset docker-8:2-3189280] Shutdown() END 
DEBU[0000] Cleaning up old shm/mqueue mounts: start.    
FATA[0000] Error starting daemon: layer does not exist  
```

`docker version`:
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Fri Feb 12 00:52:02 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

`docker info`:
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

Environment details (AWS, VirtualBox, physical, etc.):
physical, Arch Linux, kernel 4.4.1-2-ARCH

Additional info:
The file `/var/lib/docker/image/devicemapper/layerdb/sha256/541b14873e1aabcdf967e1205ce3be564d6f4bf7d2c895250ab80a9211390e62/diff` exists but it is empty. All other `diff` files in `layerdb/sha256` are 71 bytes

**Comment by cpuguy83** [comment]
ping @tonistiigi

**Comment by tonistiigi** [comment]
cc @dmcgowan

**Comment by tonistiigi** [comment]
@bcroq Did this appear right with the first boot of `v1.10.1`? If yes then what was the previous version. Do you have daemon logs for the v1.10 migration? Was the daemon uncleanly shut down, or is there a chance there could have been a problem writing to disk.

**Comment by bcroq** [comment]
@tonistiigi I upgraded to 1.10.0 a few days ago and everything was working without any problem. This issue hapenned this morning before upgrading to 1.10.1.

How could I find the daemon log for the v1.10 migration?

This is a workstation, I shut it down cleanly every evening but I will check the log to see if there was a problem. The disk looks fine, no error in dmesg.

**Comment by tonistiigi** [comment]
> How could I find the daemon log for the v1.10 migration?

These are in the logs from the first boot with `v1.10.0`.

What about the other files in `/var/lib/docker/image/devicemapper/layerdb/sha256/541b14873e1aabcdf967e1205ce3be564d6f4bf7d2c895250ab80a9211390e62/` . Are they empty as well?

**Comment by bcroq** [comment]
@tonistiigi after looking at the system log it appers that:
- the 1.10 migration took place on 08/02 and there is no sha256:541b14873e1aabcdf967e1205ce3be564d6f4bf7d2c895250ab80a9211390e62 in the logs
- I built some images this same day, pushed them on a private registry 
- I also removed some old images
- the next days (09/02) I get "Error starting daemon: layer does not exist" at every boot

It looks like I didn't use docker since then and only saw the error this morning.

**Comment by bcroq** [comment]
> What about the other files in /var/lib/docker/image/devicemapper/layerdb/sha256/541b14873e1aabcdf967e1205ce3be564d6f4bf7d2c895250ab80a9211390e62/ . Are they empty as well?

The other files are not empty. Their timestamps matches the end of the migration.

**Comment by tonistiigi** [comment]
@bcroq Not sure yet what may have caused it. If you want to fix this daemon state you can use this script calculate missing diff IDs based on image configs https://gist.github.com/tonistiigi/d957a4019f8ce4c8cc3d

**Comment by dmcgowan** [comment]
@bcroq  what is the timestamp on the empty diff file. Was this created after migration/after 1.10.1 upgrade?

**Comment by bcroq** [comment]
@dmcgowan the timestamp of the diff file is the same as the other files of the 541b14873e1aabcdf967e1205ce3be564d6f4bf7d2c895250ab80a9211390e62 folder so  it was created during the migration.

**Comment by bcroq** [comment]
@tonistiigi here is what the script gives me:

```
# go run /tmp/compute-diff-ids.go | grep :541
layerdb: sha256:541b14873e1aabcdf967e1205ce3be564d6f4bf7d2c895250ab80a9211390e62 diffid: 
```

This is the only empty diffid given by this script.

**Comment by bcroq** [comment]
@tonistiigi using this script I was able to find the image that uses the *broken* layer. I then moved the corresponding file out of `/var/lib/docker/image/devicemapper/imagedb/content/sha256` and now the docker daemon starts.

**Comment by tonistiigi** [comment]
@dmcgowan Getting empty ID from `compute-diff-ids` means there was already an empty string in the image configuration. At least, this is something that we can add more validation around.

@bcroq Do you know what image this was. Was this image created by migration or something you built/pulled later.

**Comment by bcroq** [comment]
@tonistiigi it looks like an image created on my workstation as I can see a "created_by": "/bin/sh -c #(nop) MAINTAINER bertrand.croq-at-net-ng.com" in its history.

I use a private registry; I cannot tell if this is an image I created on my machine, pushed to the registry, removed on my machine and pulled back from the registry.

**Comment by tonistiigi** [comment]
@bcroq One way to check if image has been built or migrated by local machine is to check if there exists a file `/var/lib/docker/image/<driver>/imagedb/metadata/sha256/<id>/parent`. If this file doesn't exist it was pulled after migration. If it does exist then from the dates in the history items in the image config you should be able to determine if it was created before migration to `v1.10`.

**Comment by bcroq** [comment]
@tonistiigi there is a `parent` file in `/var/lib/docker/image/devicemapper/imagedb/metadata/sha256/02d6b8dbfcb99bcae234e11fc5bc4b3e67df50821cb0c8c33c7467c9cf7db470`.

**Comment by tonistiigi** [comment]
@bcroq Thank you for your help on debugging this. I have an idea what may have caused it, but to check that theory can you send me the output of `ls -laR /var/lib/docker/graph`. Feel free to send it privately if you like.

**Comment by bcroq** [comment]
@tonistiigi output sent by mail.
