### ISSUE TITLE
Driver overlay failed to remove root filesystem: layer not retained since 1.10.0

### ISSUE THREAD

**Issue by gionn** [docker/docker#20268]
Hi,

since upgrading to 1.10.0, I am getting sporadic errors while stopping previously created containers, leaving it in Dead status. This happens also for containers created with the current version.

```
Driver overlay failed to remove root filesystem c6b033b3e4ad290f068164942fe57a6995ee28ddbab99f6511e507fcebed0b03: layer not retained
```

```
$ docker version
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64
```

```
$ docker info
Containers: 21
 Running: 21
 Paused: 0
 Stopped: 0
Images: 233
Server Version: 1.10.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 14.69 GiB
Name: staging-nxt
ID: OP2C:6I2X:XW7V:QKZH:VFBF:YSCN:4CIS:JN3I:ZARC:4VWJ:ARVG:SXES
WARNING: No swap limit support
```

```
Linux staging-nxt 4.2.0-25-generic #30~14.04.1-Ubuntu SMP Mon Jan 18 16:25:56 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by cpuguy83** [comment]
`while stopping previously created containers`, can you expand what you mean by this? CLI commands may help.

Thanks!

**Comment by gionn** [comment]
docker stop <container> on a running container.

For previously created I meant that those container were created when using docker 1.9.1, before upgrading to 1.10.1.

However even with shiny new containers (pulled and created with the current docker version), I am getting the same issue.

**Comment by scalp42** [comment]
Can confirm seeing the same error on 1.10.1, by simply deleting some containers:

```
# docker ps -q | xargs -I% -P1 docker rm -f %
```

**Comment by gionn** [comment]
Yes, I remember I've got the same error message with a subsequent rm -f after trying with stop, but after a few seconds I was able to do rm -f again on the same container with success.

**Comment by beetree** [comment]
I'm having the same error. All my nodes in my cluster are slowly running out of disk due to this issue. It is unclear to me how to properly clean up all disk after a container job is done.

```
# docker rm -f a9153f1ca9d3
Failed to remove container (a9153f1ca9d3): Error response from daemon: Driver devicemapper failed to remove root filesystem a9153f1ca9d37c67acd271dd5c2ebb06f3589b242dce8b1302178655a7bc3037: layer not retained
```

System info:
```
# docker info
Containers: 169
 Running: 77
 Paused: 0
 Stopped: 92
Images: 151
Server Version: 1.10.0
Storage Driver: devicemapper
 Pool Name: docker-8:2-23593209-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 32.21 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 214.7 GB
 Data Space Total: 214.7 GB
 Data Space Available: 0 B
 Metadata Space Used: 129.9 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.018 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.99 (2015-06-20)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.19.8-031908-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 125.8 GiB
Name: m3479.contabo.host
ID: ZDSD:XISW:V6WA:6RDL:556C:6DMB:JCJK:QYBZ:Y7IG:AAQL:MGRO:BEIN
Debug mode (server): true
 File Descriptors: 1258
 Goroutines: 1453
 System Time: 2016-02-13T06:22:19.42919458+01:00
 EventsListeners: 0
 Init SHA1: 0fab8563cbfa5ba7c182919f38b1fac541d116d0
 Init Path: /usr/lib/docker/dockerinit
 Docker Root Dir: /var/lib/docker
WARNING: No swap limit support


# docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:41:30 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:41:30 2016
 OS/Arch:      linux/amd64


# uname -a
Linux m3479.contabo.host 3.19.8-031908-generic #201505110938 SMP Mon May 11 13:39:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

If you can, please up the priority of this issue. Seems to me that the underlying cause could be an issue in the new layering system introduced in 1.10.

/beetree

**Comment by goal043** [comment]
Can confirm. I am experiencing this issue since upgrading to 1.10.1

**Comment by cpuguy83** [comment]
ping @tonistiigi

**Comment by tonistiigi** [comment]
Can anyone seeing this check if the problem goes away after restarting the daemon?

**Comment by goal043** [comment]
> Can anyone seeing this check if the problem goes away after restarting the daemon?

Ok, i think i see a pattern which may help:

First of all, restarting the daemon makes the problem go away.

As an additional observation, two other error messages appear prior to this condition occurring:

> docker rm quizzes-v1
Failed to remove container (quizzes-v1): Error response from daemon: Unable to remove filesystem for 0afff52498fbf17a891e15b3ce20bd0bf3a0bb7c63c0656cdfd771ecabc9484d: remove /var/lib/docker/containers/0afff52498fbf17a891e15b3ce20bd0bf3a0bb7c63c0656cdfd771ecabc9484d/shm: device or resource busy

This seems to resolve by running 'docker rm' again.

Also, less frequent, this error pops up:

> docker rm guilds-v0
Failed to remove container (guilds-v0): Error response from daemon: Driver aufs failed to remove root filesystem c1609770f184df14d109f40a329d2d684cb773d2b9f32d15ff821dd017d6e56c: rename /var/lib/docker/aufs/diff/63fb9874903117bfd5ef1828bee719563217b8d5eb915d96e6b5cbbdff00b412 /var/lib/docker/aufs/diff/63fb9874903117bfd5ef1828bee719563217b8d5eb915d96e6b5cbbdff00b412-removing: device or resource busy

This error does not resolve after a retry, and the reported issue subsequently occurs.

Btw, the `precursor` errors already mess up my restart script. These errors did definitely not occur before my update to 1.10.1 (skipped 1.10.0)

Hope that helps.

**Comment by goal043** [comment]
I've now seen a (probably) related error occur during building as well:

```
building container...
...
Step 1 : FROM nginx
...
Step 6 : EXPOSE 80
 ---> Running in f5697e69749d
 ---> 7bff11d3e0d9
Error removing intermediate container f5697e69749d: rmdriverfs: Driver aufs failed to remove root filesystem f5697e69749d4508f80d89ebea9a5c6d3a18cecd7561cc1a317466b1c8b58f04: rename /var/lib/docker/aufs/mnt/8f89bd4d70de7540cbd886d8c30b2c4e1f12d5fe9f5574a9b5491c055bb420b2 /var/lib/docker/aufs/mnt/8f89bd4d70de7540cbd886d8c30b2c4e1f12d5fe9f5574a9b5491c055bb420b2-removing: device or resource busy
Successfully built 7bff11d3e0d9
```

The resulting container is fine. I do not know what consequences this has. Intermediate files not being cleaned up?
