### ISSUE TITLE
Unable to recover from devicemapper running out of space

### ISSUE THREAD

**Issue by bfirsh** [docker/docker#20272]
When devicemapper with direct-lvm runs out of disk space, the system seems to get in a state of write lock and eventually the daemon locks up. When restarted, it fails to start because the data pool is at 100% and fails to mount.

This has been a big problem with users using devicemapper in production (generally, RHEL and CentOS users). This often happens because most people aren't monitoring the free space on their LV, because the only way seems to be monitoring `/info` on the Engine. Most people are monitoring space usage with `df`, which doesn't include the LV.

Two things which might help, I think:

1) Either make the daemon not lock up or restart cleanly, so users can remove stuff to free space.
2) Document how to monitor devicemapper in production so users are less likely to get into this state.

(Thanks for report, @mbentley)

**Comment by unclejack** [comment]
One thing which can be done is to check how much free space is available and throw an error when doing one of the following:
- attempting to pull images
- attempting to build images
- attempting to commit containers

This would provide some protection against running out of space by warning the user that they need to free up space first.

**Comment by skairali** [comment]
Has anybody claimed it yet?

**Comment by thaJeztah** [comment]
@skairali not that I'm aware of

**Comment by mbentley** [comment]
While I think checking space available when pulling, building, and committing container is great, it may not address some of the biggest failure scenarios.  Unattended systems where users are not manually performing operations and would see the warning messages being a big problem (e.g. - continuous deployment systems where deployment happen without user interaction).  Some other reasons I've seen a LV fill up with devicemapper would be containers where data is being written to the copy on write filesystem.  I know this is a bad practice, smacking hands and saying "don't do that" is the right thing to do but it happens.  That's probably the most dangerous scenario seeing as there isn't any sort of user interaction of performing a task where a failure notice can reach back to the end user, either from the docker client back to a user interactively running a command or to an automated system that will detect that non-zero exit or return from the API indicating a problem.  Its these silent scenarios that can be very problematic in terms of detection and prevention.  If there is any way that these can be addressed, that would be ideal.

**Comment by skairali** [comment]
if checking space available when pulling, building, and committing is the scope- I would like to claim it.  @thaJeztah @mbentley

**Comment by thaJeztah** [comment]
We now have an option to set a minimum amount of space for devicemapper, to prevent getting in this situation, so I'll close this

**Comment by pmsosa** [comment]
Im commenting just to say that we had an issue similar to this and #26015 and the way we solved it by removing all images and containers and then removing everything inside /var/lib/docker. Just our two cents.

**Comment by r3trosteve** [comment]
@pmsosa I'm pretty new to this docker stuff. After removing /var/lib/docker what do you do to get set back up again?

**Comment by teamcity-doubleverify** [comment]
@pmsosa any info you can provide on @r3trosteve 's question would be great..
> I'm pretty new to this docker stuff. After removing /var/lib/docker what do you do to get set back up again?

**Comment by toby5box** [comment]
@r3trosteve This might be relevant https://github.com/moby/moby/issues/18867#issuecomment-169020478
