### ISSUE TITLE
Existing containers may attach to volumes from wrong driver if initial driver is not responding

### ISSUE THREAD

**Issue by clintonskitson** [docker/docker#20276]
cc @cpuguy83 

This relates to using common volume names across storage drivers.

This is another corner case to cover that I just ran into.  If you have a container hat was initially attached to a certain volume driver and the container was not deleted then the following situation can occur.  

If the container is restarted then it will wait for a timeout from the previously used driver that does not exist or is not responding.  If the driver does not respond then "Error: No such volume: newvol2001" is returned.  However, if the docker daemon is restarted then it will retrieve the next responding volume driver.

With the startup of the container or the startup of another container the volume attached will be the wrong one.

I believe that if a volume driver is associated to a volume name, that there should be no time that it would be re-associated to another volume driver.

**Comment by clintonskitson** [comment]
Expanding on this slightly.  A feature that may be nice to have would be a `volume inspect` which would include the containers that are using that volume and `volume clear` to clear the association of the volume to the engine.

The `volume inspect` with associated containers would help to clear out the right unused containers.  And the `volume clear` would enable someone to subsequently do a run with the new volumedriver:volumename association without restarting the engine.

What I'm getting at is that today you can only implicitly get to the behavior described above.  A docker container remove followed by an attempt to manually associate volume to another volume driver results in `create newvol2001: conflict: volume name must be unique`.

**Comment by LK4D4** [comment]
@cpuguy83 any news?

**Comment by cpuguy83** [comment]
This was resolved.
Thanks!
