### ISSUE TITLE
No such image - statusCode=404

### ISSUE THREAD

**Issue by reiz** [docker/docker#20283]
I have a self hosted Docker Registry and some servers pulling from it. On one of my servers pulling an particular images always fails with the error message: 

```
level=error msg="HTTP Error" err="No such image: sol5-docker2-pp.comp.io/evaluate_stockimporter:411b23" statusCode=404
```

docker info on the server says: 

```
Containers: 63
Images: 400
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.3.3-coreos-r2
Operating System: CoreOS 899.6.0
CPUs: 16
Total Memory: 29.44 GiB
```

The odd thing is that I have a couple other server with exactly the same setup and on the other server pulling the image works! I rebooted the server already and spend the whole day with debugging and googleing for it, but now I'm done! Any ideas? What's wrong here? Why can the image not get pulled? The image exists for sure!

**Comment by thaJeztah** [comment]
Do the logs for that registry show anything useful? Also, what version of the registry are you using, what setup? Perhaps this issue is more suitable in https://github.com/docker/distribution/issues

**Comment by reiz** [comment]
Nope! The registry is Docker Distribution 2.2.1 running on Docker Engine 1.9.1 on CoreOS with a BlockStorage for persistence. 

I don't think that it's related to the registry because other Kubernetes Minions can pull the image. Only 2 Minions in the cluster had this issue. In the mean time I solved it! I shut down the Docker daemon and the Kubelet and removed everything under "/var/lib/docker/*". After starting again the Docker Engine and the Kubelet the Minion was able to pull down all Docker Images without any errors. It looks like the Storage Driver was broken. But how could that happen? How can I prevent that? Looks like a bug in the Docker Engine or in the Storage Driver.

**Comment by reiz** [comment]
@thaJeztah Could that happen if there are too many parallel pulls?

**Comment by thaJeztah** [comment]
@reiz worth testing; a lot of improvements have been made in docker 1.10 in that area

/cc @aaronlehmann

**Comment by reiz** [comment]
OK. I have to wait until CoreOS is switching to docker 1.10. I will do further investigations today and keep you informed.

**Comment by reiz** [comment]
@thaJeztah @aaronlehmann Now I got the same error again. `error: No such image`! With `docker images` I can see this: 

```
REPOSITORY          TAG       IMAGE ID               CREATED             VIRTUAL SIZE
<none>              <none>    59df5c8cd942           11 minutes ago      1.339 GB
```

With `docker rmi 59df5c8cd942` I get the error message: 

```
Error response from daemon: conflict: unable to delete 59df5c8cd942 (cannot be forced) - image is held by an ongoing pull or build
Error: failed to remove images: [59df5c8cd942]
```

So it can not be fetch and it can not be removed! The docker daemon keeps try to fetch it in a loop, but always with the same result. 

So pretty much the only thing I can do now is stoping the Docker engine and run `rm -Rf /var/lib/docker/*`. But this is unacceptable for production. 

Any ideas? I appreciate any input!

**Comment by thaJeztah** [comment]
@reiz is that on docker 1.10.x?

**Comment by reiz** [comment]
No. That's all on docker 1.19.1.

**Comment by reiz** [comment]
Here is the output from `docker info`: 

```
Containers: 0
Images: 459
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.3.3-coreos-r2
Operating System: CoreOS 899.6.0
CPUs: 4
Total Memory: 14.69 GiB
```

**Comment by reiz** [comment]
I though maybe it's related to the block storage. Maybe it's too slow and the client runs into some kind of time outs. The last `docker info` output is from a server without block storage. It has a locale disk which is 5 times faster, but still getting the same error.

**Comment by thaJeztah** [comment]
I know there were issues with concurrent push/pull's in docker < 1.10, there's been a lot of changes in that area to better support that.

**Comment by reiz** [comment]
OK. Currently testing a cluster with docker 1.10. I keep you informed!

**Comment by thaJeztah** [comment]
Thanks!

**Comment by reiz** [comment]
Keep testing it tomorrow. After 24 hours we should know more ;)

**Comment by aaronlehmann** [comment]
@reiz: Thanks for testing with Docker 1.10. Hopefully this will correct the problem.

I suspect what is happening in 1.9 is that something goes wrong during the pull, and Docker tries again with the legacy v1 protocol. Since your registry uses the v2 protocol, this results in a 404. This fallback has caused a lot of confusion before.

Unfortunately, I can't know what originally went wrong without seeing a Docker daemon log, preferably in debug mode. If you continue to experience the issue and can capture this log, I'd be happy to take a look at it.

Docker 1.10 includes several improvements to the decision process of whether to switch to the v1 protocol, so I'm hopeful that upgrading will solve the problem, or at least give you a more useful error.

**Comment by reiz** [comment]
@aaronlehmann Thank for the detailed description. I guess you are right with your guess. So far it looks good. Over night no errors popped up. 

```
Containers: 53
 Running: 53
 Paused: 0
 Stopped: 0
Images: 21
Server Version: 1.10.0
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.1-coreos
Operating System: CoreOS 955.0.0
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 29.44 GiB
```

I will monitor this today and if no more errors occur I will close this ticket today!

**Comment by thaJeztah** [comment]
@reiz thanks so much! Fingers crossed

**Comment by reiz** [comment]
@thaJeztah @aaronlehmann This issue seems to be fixed with docker 1.10. But now we have other issues related to docker 1.10 :-/ But this ticket can be closed.

**Comment by thaJeztah** [comment]
@reiz thanks, good to hear; please open separate issues for those, happy to help!

**Comment by reiz** [comment]
Now with docker 1.10 and Kubernetes I have this issue: https://github.com/fsouza/go-dockerclient/issues/455. I just build a cluster with docker 1.8.3. Let's see how stable that is.
