### ISSUE TITLE
Docker hangs

### ISSUE THREAD

**Issue by csaintc** [docker/docker#20282]
BUG REPORT INFORMATION

docker version: 1.10.1
docker info: [ hangs indefinitely ]

Provide additional environment details (AWS, VirtualBox, physical, etc.):
Local installation through apt-get
List the steps to reproduce the issue:
1. Start computer
2. run any docker command
3. observe

Describe the results you received:
The CLI hangs forever, and eventually times out.

Describe the results you expected:
It prints the results I want.
Provide additional info you think is important:
This began happening after I did an upgrade.

**Comment by csaintc** [comment]
Fixed after two reboots

**Comment by cpuguy83** [comment]
Please see https://docs.docker.com/engine/migration/

**Comment by cpuguy83** [comment]
This is most likely due to the 1.10 migration running.
