### ISSUE TITLE
Cannot import tar.gz files anymore

### ISSUE THREAD

**Issue by tlunter** [docker/docker#20296]
```
ubuntu@ip-10-10-0-13:/mnt/tmp$ cat file.tar.gz | docker import -
Error response from daemon: ApplyLayer exit status 1 stdout:  stderr: archive/tar: invalid tar header
```

I'm not sure when this started, but when using docker 1.10 to build images, I've found I can no longer import tar.gz files, but I can import tars just fine.

`docker version`:

ubuntu@ip-10-10-0-13:/mnt/tmp$ docker version
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

`docker info`:

```
ubuntu@ip-10-10-0-13:/mnt/tmp$ docker info
Containers: 9
 Running: 4
 Paused: 0
 Stopped: 5
Images: 134
Server Version: 1.10.1
Storage Driver: btrfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 3.13.0-74-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 240.2 GiB
Name: ip-10-10-0-13
ID: HCVB:JNTI:DPHO:ILZN:5RXB:FP2R:JW4L:4WKF:OHBG:JVBT:ALOZ:TJCW
WARNING: No swap limit support
```

`uname -a`:
Linux ip-10-10-0-13 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.): AWS EC2 HVM

How reproducible: cat a gzipped tar into `docker import -`

Actual Results: stderr: archive/tar: invalid tar header

Expected Results: an image

Additional info: I believe this was working correctly in docker 1.9

**Comment by guruvan** [comment]
Hmmm - I've tried a few different ways, and - generally having trouble importing a tarball at all. 
For a temp work around I'm just quick untarring it, dropping in a Dockerfile

`FROM scratch
ADD ball.tar /`

But this breaks quite a few of my builds

**Comment by thaJeztah** [comment]
How did you create the tar.gz? Could you provide the steps taken to create the tag.gz, or a minimal example file so that we can compare to docker 1.9?

**Comment by thaJeztah** [comment]
Note that there are some existing issues that may provide some hints on debugging/triaging this https://github.com/docker/docker/issues?utf8=✓&q=is%3Aissue+%22invalid+tar+header%22

**Comment by tlunter** [comment]
Sure thing, I'll try and make some examples.

**Comment by thaJeztah** [comment]
Thanks, that will help investigating if this is a regression in 1.10; also wondering if this can be related to the changes for content-addressable storage.

**Comment by tlunter** [comment]
```
ubuntu@ip-10-10-0-10:~$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
ubuntu@ip-10-10-0-10:~$ docker pull tianon/true
Using default tag: latest
latest: Pulling from tianon/true
1d227de5caa5: Pull complete
a3ed95caeb02: Pull complete
Digest: sha256:9e9e5b66ba46512d1dcdb1fd50efe1fc96e04278e2a31c1bd2acc231bb1e724e
Status: Downloaded newer image for tianon/true:latest
ubuntu@ip-10-10-0-10:~$ docker create tianon/true /true
6b8ade481bdfd35c928491469f3b785c36f6fad3ca026b7ba224bd87f042847d
ubuntu@ip-10-10-0-10:~$ docker export 6b8ade481bdfd35c928491469f3b785c36f6fad3ca026b7ba224bd87f042847d | gzip -c > true.tar.gz
ubuntu@ip-10-10-0-10:~$ cat true.tar.gz | docker import - new-true
Error response from daemon: ApplyLayer exit status 1 stdout:  stderr: unexpected EOF
ubuntu@ip-10-10-0-10:~$ docker export 6b8ade481bdfd35c928491469f3b785c36f6fad3ca026b7ba224bd87f042847d > true.tar
ubuntu@ip-10-10-0-10:~$ cat true.tar | docker import - new-true
sha256:200fc4267bde236c6a61f8d55de82c7956cc95a642c045ab3dc1cf5a474f60ce
ubuntu@ip-10-10-0-10:~$ less true.tar.gz
ubuntu@ip-10-10-0-10:~$ ls -la
total 7016
drwxr-xr-x  5 ubuntu ubuntu    4096 Feb 13 10:06 .
drwxr-xr-x 24 root   root      4096 Feb 13 10:05 ..
-rw-rw-r--  1 ubuntu ubuntu    8704 Feb 13 10:06 true.tar
-rw-rw-r--  1 ubuntu ubuntu     392 Feb 13 10:06 true.tar.gz
ubuntu@ip-10-10-0-10:~$ cat true.tar | gzip -c > true.new.tar.gz
ubuntu@ip-10-10-0-10:~$ ls -la
total 7020
drwxr-xr-x  5 ubuntu ubuntu    4096 Feb 13 10:08 .
drwxr-xr-x 24 root   root      4096 Feb 13 10:05 ..
-rw-rw-r--  1 ubuntu ubuntu     392 Feb 13 10:08 true.new.tar.gz
-rw-rw-r--  1 ubuntu ubuntu    8704 Feb 13 10:06 true.tar
-rw-rw-r--  1 ubuntu ubuntu     392 Feb 13 10:06 true.tar.gz
```

This isn't the exact same error, but it still isn't capable of parsing the gzipped tar archive correctly.  I suspect this gzipped tar archive is shorter than what the `Untar` function is expecting to be able to read.

https://tlunter-pub.s3.amazonaws.com/true.tar
https://tlunter-pub.s3.amazonaws.com/true.tar.gz
https://tlunter-pub.s3.amazonaws.com/true.new.tar.gz

Thanks @thaJeztah!

**Comment by tlunter** [comment]
Looks to me like we used to follow this path: (https://github.com/docker/docker/commit/48c7a1618db26568a8841632565f651cea2a8b39 is the parent of https://github.com/docker/docker/commit/500e77bad0b19b3b1c8e6ac195485adcb70daef1)

https://github.com/docker/docker/blob/48c7a1618db26568a8841632565f651cea2a8b39/api/server/router/local/image.go#L146
https://github.com/docker/docker/blob/48c7a1618db26568a8841632565f651cea2a8b39/daemon/daemon.go#L1040
https://github.com/docker/docker/blob/48c7a1618db26568a8841632565f651cea2a8b39/graph/import.go#L60
https://github.com/docker/docker/blob/48c7a1618db26568a8841632565f651cea2a8b39/graph/graph.go#L268
https://github.com/docker/docker/blob/48c7a1618db26568a8841632565f651cea2a8b39/graph/graph.go#L292
https://github.com/docker/docker/blob/48c7a1618db26568a8841632565f651cea2a8b39/graph/graph.go#L344
https://github.com/docker/docker/blob/48c7a1618db26568a8841632565f651cea2a8b39/graph/graph.go#L700
https://github.com/docker/docker/blob/48c7a1618db26568a8841632565f651cea2a8b39/graph/graph.go#L746

Now we end up in `Daemon`s `ImportImage` and do:

https://github.com/docker/docker/blob/master/daemon/import.go#L59
https://github.com/docker/docker/blob/master/layer/layer_store.go#L287
https://github.com/docker/docker/blob/master/layer/layer_store.go#L214
https://github.com/docker/docker/blob/master/daemon/graphdriver/fsdiff.go#L136
https://github.com/docker/docker/blob/master/pkg/chrootarchive/diff.go#L18
https://github.com/docker/docker/blob/master/pkg/chrootarchive/diff_unix.go#L79

In `diff.go`, we get explicitly `decompress: false`, but I'm not actually sure why.  https://github.com/docker/docker/blob/master/pkg/archive/archive.go#L165-L192 Shows that it can handle an uncompressed stream just fine.

**Comment by thaJeztah** [comment]
Ping @aaronlehmann @vbatts @tonistiigi, perhaps you have an idea what changed here

**Comment by tonistiigi** [comment]
This indeed seems to be introduced with the content-addressability changes.

**Comment by tlunter** [comment]
Nice, thanks @tonistiigi
