### ISSUE TITLE
WORKDIR doesn't respect USER when creating directories

### ISSUE THREAD

**Issue by dmolesUC3** [docker/docker#20295]
To reproduce, build an image from the following Dockerfile:

```
FROM centos:7
RUN mkdir -p /apps/foo
RUN useradd -d /apps/foo foo && \
    chown -R foo:foo /apps/foo
USER foo
WORKDIR /apps/foo/bar
RUN mkdir baz
```

Expected:

- directory `/apps/foo/bar` is owned by user `foo`
- directory `/apps/foo/bar/baz` is created

Actual:

- directory `/apps/foo/bar` is owned by `root`

    ```
    $ ls -dal /apps/foo/bar
    drwxr-xr-x 2 root root 4096 Feb 13 00:26 /apps/foo/bar
    ```

- the `RUN mkdir baz` step fails with 

    ```
    mkdir: cannot create directory 'baz': Permission denied
    The command '/bin/sh -c mkdir baz' returned a non-zero code: 1
    ```

**Comment by dmolesUC3** [comment]
Given that it's documented that `USER` only affects `RUN`, `CMD` and `ENTRYPOINT`, I suppose this is a feature request. But the current behavior seems arbitrary and un-obvious, documented or not.

**Comment by AkihiroSuda** [comment]
@dmolesUC3 Is this AUFS specific?
Very similar to https://github.com/docker/docker/issues/20240

**Comment by thaJeztah** [comment]
>  the current behavior seems arbitrary and un-obvious, documented or not.

There are a couple of oversights in the way `USER` interacts with other commands; the same, e.g., applies to `COPY` and `ADD`, which also don't respect `USER`. Unfortunately, we won't be able to change that behavior without causing backward incompatible issue (the Dockerfile format is not versioned), so I'm not sure we can address this

**Comment by dmolesUC3** [comment]
> the Dockerfile format is not versioned

Oops. Configuration flag, maybe? Transition to making it the default over, I don't know, the next three years?

**Comment by dmolesUC3** [comment]
@AkihiroSuda I'm using AUFS (4.1.13-boot2docker on Virtual Box on MacOS) but I couldn't tell you if it's AUFS-specific.

**Comment by LK4D4** [comment]
It's still a pain point. Flags for instructions were introduced, but we still afraid of using them. Probably just better to be aware :/

**Comment by thaJeztah** [comment]
We discussed this, and while we see it's inconvenient, the best option is to create the workdir in advance, with the correct user. For that reason, we think we should close this.

**Comment by phil294** [comment]
@thaJeztah seeing the negative response to this decision, would you mind elaborating on why this was declined?

**Comment by thaJeztah** [comment]
It would be a breaking change https://github.com/moby/moby/issues/20295#issuecomment-184205818, also, workdir should (in hindsight) not have automatically created the directory

**Comment by TonyTromp** [comment]
+1 Add --chown to WORKDIR
