### ISSUE TITLE
docker pull: Display available tags when tag not found

### ISSUE THREAD

**Issue by msabramo** [docker/docker#20306]
```
❯ docker pull python:26.5
Pulling repository docker.io/library/python
Tag 26.5 not found in repository docker.io/library/python
```

It would be nice in this situation if it could show the available tags in the repository.

**Comment by HackToday** [comment]
it seems this need distribute to have API to get all tags 
https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/

Right now, docker search not have related tag information

**Comment by skairali** [comment]
+1

**Comment by skairali** [comment]
has anybody started working on it? if not we would like to take a look at fixing it

**Comment by skairali** [comment]
@gigidwan

**Comment by skairali** [comment]
If no body has claimed it yet - can I claim it?

**Comment by thaJeztah** [comment]
@skairali you can, but I think this will require changes in Docker Hub, so not sure we can implement it in the client?

**Comment by skairali** [comment]
@thaJeztah  yes you are right.

**Comment by LK4D4** [comment]
I think implementation would be challenging. Going to close it for now. Feel free to open new issue if you have ideas how to do that.
