### ISSUE TITLE
navigation in ncurses application (menuconfig of crosstool-ng) not possible

### ISSUE THREAD

**Issue by paulroemer** [docker/docker#20302]
Hey guys,

my image includes crosstool-ng - everything is successfully compiled and crosstool-ng's help can be displayed. I also can start menuconfig but unfortunately navigation is impossible. Using arrow keys only results in displaying escape sequences. I already tried different terminfos but without success.

Can anybody give me a hint? Or is it working for you?

docker run -e TERM=xterm --rm=true -i panderpeter/alpine-crosstool-ng menuconfig

Cheers,
  Peter

The image is based on Alpine Linux

**Comment by cpuguy83** [comment]
Did you add a `-t` there?

**Comment by paulroemer** [comment]
Ooops, I'm feeling very stupid at the moment...

Many thanks @cpuguy83
