### ISSUE TITLE
Re-implement checkpoint/restore after containerd integration

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#20300]
### Add (experimental) support for checkpoint/restore to Docker

Support for C/R has been implemented before (#13602 and #13442), but due to the upcoming move to integrate [`containerd`](https://containerd.tools) in Docker 1.11, the existing checkpoint/restore PR unfortunately had to be closed (see https://github.com/docker/docker/pull/13602#issuecomment-181614492).

This issue is to track progress on the re-implementation of the checkpoint/restore feature after containerd has been integrated.

**Comment by boucher** [comment]
Just as a heads up for people interested in the meantime, here's a compiled version of the now closed pull request you can play around with in the meantime (now with working networking support): 

https://github.com/boucher/docker/releases/tag/v1.10_2-16-16-experimental

**Comment by thaJeztah** [comment]
Cool, thanks @boucher :heart:

**Comment by Jijuan** [comment]
Hi, I was interested in your closed pull requests.
I want to ask a few simple questions.
1. Will this issue be merged to original docker?
2. If I want to use checkpoint/restore functions, 
    2.1. Install docker from original docker codes.
    2.2. stop docker service
    2.3. change binary file which you commented above.
    2.4. re-start docker service

**Comment by mikeatlas** [comment]
@boucher any chance you might consider the awesome forward-thinking work and fork/PR Docker 1.11 with CRIU 2.0? Looking forward to seeing this land!

Also, could you clarify if there is indeed a minimum kernel version required? I'm curious if the suggestion to use `--security-opt seccomp:unconfined` would allow older kernel support.

**Comment by boucher** [comment]
Using --security-opt=seccomp:unconfined should work fine on older kernels.
And things should work transparently with CRIU 2.0. I think doing the work
for final Docker integration has to wait until the containerd work is
finished (or close to finished). I'm not sure what the status of that is
currently.

**Comment by timothysc** [comment]
I'm just going to leave this here and sneak away https://github.com/dmtcp/dmtcp 

/cc @rhatdan @vishh

**Comment by tswift242** [comment]
Any updates on this? It looks like the containerd integration has happened.

**Comment by boucher** [comment]
This is the first step: https://github.com/docker/engine-api/pull/175

**Comment by thaJeztah** [comment]
The basics (API) are merged https://github.com/docker/docker/issues/22049, so I'm closing this issue
