### ISSUE TITLE
Output of docker inspect not JSON valid

### ISSUE THREAD

**Issue by pierlauro** [docker/docker#20301]
According to the [JSON grammar specification](http://json.org/), a key cannot contain special characters like '**/**' and can't start with a number.

The output keys of docker inspect for exposed ports respect the form ```("%d/%s", port, protocol)```

For example, the docker-inspect output for the [nginx container](https://hub.docker.com/_/nginx/) contains:
```json
.........
"ExposedPorts": {
            "443/tcp": {},
            "80/tcp": {}
        },
.........

```

The problem is really annoying if you want to parse the output of docker inspect: there is no json parser (e.g.: [jq](https://stedolan.github.io/jq/)) able to parse that kind of output because it doesn't respect the grammar.

**Comment by duglin** [comment]
they key is a "string" and a "string" is a set of "char"s, which is:
```
char
    any-Unicode-character-
        except-"-or-\-or-
        control-character
    \"
    \\
    \/
    \b
    \f
    \n
    \r
    \t
    \u four-hex-digits 
```
looks like "/" is valid.

**Comment by thaJeztah** [comment]
yup, afaik, it's valid, but cannot be accessed via the "dot" syntax (`obj.Key`, but `obj["Key"]` instead)

**Comment by duglin** [comment]
I'm gonna close this as I don't think its an issue with Docker, but we can reopen if I'm wrong.
