### ISSUE TITLE
Unable to push to v2 registry : client disconnected during blob PATCH

### ISSUE THREAD

**Issue by julienboulay** [docker/docker#20313]
Description of problem:
I'm not able to push some images to the docker registry. I get the following error :

ERRO[0144] client disconnected during blob PATCH         go.version=go1.5.3 http.request.host=localhost:5000 http.request.id=19eb581c-e416-4ce2-a9ca-cbbb7b9c76bb http.request.method=PATCH http.request.remoteaddr=172.17.0.1:46869 http.request.uri=/v2/myrepository/appname/blobs/uploads/3dad9b3a-adb5-4f70-bdd6-8503fd58b8ad?_state=takU0Wrsdxv6zw2ylXs-qS0Pn5borecRO3vk_mxL1RJ7Ik5hbWUiOiJncm91cGUzcy91cnVidS13ZWJhcHAiLCJVVUlEIjoiM2RhZDliM2EtYWRiNS00ZjcwLWJkZDYtODUwM2ZkNThiOGFkIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE2LTAyLTE0VDE1OjM2OjM1LjU2ODEyOTIxM1oifQ%3D%3D http.request.useragent=docker/1.10.1 go/go1.5.3 git-commit/9e83765 kernel/3.13.0-77-generic os/linux arch/amd64 instance.id=5394f528-626b-4687-a2bc-41649d41e778 vars.name=myrepository/appname vars.uuid=3dad9b3a-adb5-4f70-bdd6-8503fd58b8ad version=v2.3.0

docker version : 1.10.1

docker info : 
Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 115
Server Version: 1.10.1
Storage Driver: devicemapper
 Pool Name: docker-9:4-56625466-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 6.471 GB
 Data Space Total: 107.4 GB
 Data Space Available: 100.9 GB
 Metadata Space Used: 10.47 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.137 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-77-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.32 GiB
Name: dockito
ID: OEUM:NMVO:PHCF:O2V2:KXMO:KOIY:CUJG:DB4S:H6BL:KCJD:QRQT:RDSB
WARNING: No swap limit support

`uname -a`:
Linux dockito 3.13.0-77-generic #121-Ubuntu SMP Wed Jan 20 10:50:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by julienboulay** [comment]
Removing all local images seems to have solved this issue. Some images layers were probably corrupted because I cannot reproduce it.

**Comment by sunil3s3** [comment]
Im getting same error, please let me know how did you start docker registry container( options)

**Comment by julienboulay** [comment]
This error did not seems to come from the registry container options.
I could always push newly created image.

I think this error happened because the some of the existing image were corrupted while migrating from V1 to V2 registry format.
I remember that when upgrading to docker 1.10.1, the docker daemon was busy and I _wildly_ kill it.
After reading the release note, I discovered that the daemon was upgrading **automatically** all local images from V1 to V2.
So I unintentionally corrupted some files locally.
After deleting and rebuilding the images, everything was ok.

**Comment by sunil3s3** [comment]
Thanks for info. 

I tried downloading fresh image and tag to my private registry . tried to push image got below error 
11327e04fac0: Pushing [==================================================>]   289 MB
Received unexpected HTTP status: 500 Internal Server Error

and below is the error log from docker logs

time="2016-07-28T06:03:26.357702532Z" level=error msg="response completed with error" environment=development err.code=UNKNOWN err.detail="parsing time \"Thu, 28 Jul 2016 06:02:20 UTC\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"UTC\" as \" GMT\"" err.message="unknown error"

**Comment by sunil3s3** [comment]
Im using openstack swift as the backend storage option

**Comment by julienboulay** [comment]
Hi @sunil3s3,

Your issue doesn't seem to be related to mine. You should try either to find a post related to openstack backend storage configuration, or open a new issue.

**Comment by sunil3s3** [comment]
thanks for help . I will open new issue.
