### ISSUE TITLE
daemon.json and "hosts" under CentOs

### ISSUE THREAD

**Issue by pycloux** [docker/docker#20317]
Hi All,

A tiny issue.
If I want to use the "daemon.json" feature to configure a TCP socket under centOs this does not work.
Indeed, by default, the "docker.service" contains:
```
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target docker.socket
Requires=docker.socket

[Service]
Type=notify
ExecStart=/usr/bin/docker daemon -H fd://
MountFlags=slave
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity
TimeoutStartSec=0

[Install]
WantedBy=multi-user.target
```

If I add a daemon.json configuration with a "hosts" flag (say for instance "tcp://0.0.0.0:2375"), this results in an error:
`unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives are specified both as a flag and in the configuration file: hosts: (from flag: [fd://], from file: [tcp://0.0.0.0:2375])`

This is just a conflict between the "-H" flag of the "ExecStart" and the parameter from the daemon.json. I guess that having a default daemon.json with an appropriate default value for the "hosts" flag would solve the issue.

Best regards,

docker version : 
```
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:18:46 2016
 OS/Arch:      linux/amd64
```

docker info 
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 25
Server Version: 1.10.1
Storage Driver: devicemapper
 Pool Name: docker-253:0-68169951-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 417.1 MB
 Data Space Total: 107.4 GB
 Data Space Available: 36.72 GB
 Metadata Space Used: 1.425 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.3.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.797 GiB
Name: localhost.localdomain
ID: UHA6:WFNC:3RLF:ZOI6:AJGB:WR35:SPII:UZ2X:QJBM:DX4P:MKMC:47SV
```

**Comment by thaJeztah** [comment]
I think this is expected; we decided to output an error if an option is provided both as a flag (`-H` in this case), and in the configuration file (daemon.json), because having the config in both can result in unexpected results (do you expect the value to be overwritten? Merged? Appended?).

In this case, I suggest to use a drop-in file to override the ExecStart, removing the `-H` option, and only configure it using the daemon.json. See https://docs.docker.com/engine/admin/systemd/#custom-docker-daemon-options

Note that I opened an issue to discuss providing a default daemon.json; https://github.com/docker/docker/issues/20151

Does this answer your question? If it does, feel free to close

**Comment by pycloux** [comment]
The error is logical yet from a user experience point of view, actually, I would expect the "deamon.json" file to "work" without any modification of the default service startup configuration (whatever is the OS).
I saw the #20151 and agree that this is certainly what I would propose (simpler and more OS agnostic).
