### ISSUE TITLE
.deb packaging does not respect docker daemon settings

### ISSUE THREAD

**Issue by fommil** [docker/docker#20314]
The official `.deb`s for `docker-engine` at

```
deb https://apt.dockerproject.org/repo debian-stretch main
```

as per https://docs.docker.com/engine/installation/linux/debian/

install a file at `/lib/systemd/system/docker.service` containing

```
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target docker.socket
Requires=docker.socket

[Service]
Type=notify
ExecStart=/usr/bin/docker daemon -H fd://
MountFlags=slave
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity
TimeoutStartSec=0

[Install]
WantedBy=multi-user.target
```

this has a hardcoded `ExecStart`. I personally want to change this, e.g. to

```
ExecStart=/usr/bin/docker daemon -g /mnt/archive/docker --exec-opt native.cgroupdriver=cgroupfs -H fd://
```

to workaround  https://github.com/docker/docker/issues/16256 but your packaging insists on recreating this file afresh on every installation or upgrade.

It would be good if you provided some mechanism to allow persisted site preferences.

**Comment by fommil** [comment]
docker version / info is irrelevant as this relates to updating docker to, e.g. the latest.

Reproduction is to do a `sudo apt-get upgrade` when a new `docker-engine` becomes available and see all customisations to `/lib/systemd/system/docker.service` be wiped out, and the installation fail because the settings were required to get docker to start. Workaround is to do that, then modify the file, and issue another `sudo apt-get upgrade`.

**Comment by phemmer** [comment]
The documentation on systemd contains instructions on how to modify the systemd service: https://docs.docker.com/engine/admin/systemd/#custom-docker-daemon-options

**Comment by fommil** [comment]
Oh, i missed that thanks.

**Comment by fommil** [comment]
(It still fails to install the first time, but that's in the linked ticket)
