### ISSUE TITLE
Docker build fails on arm64 platform that does not support 32-bit mode

### ISSUE THREAD

**Issue by vijaykilari** [docker/docker#20325]
make fails with below error on arm64 with latest master branch.
I am using Dockerfile.aarch64 and below command

#sudo make build

##### Building Go bootstrap tool.
cmd/dist
./make.bash: line 121: /usr/src/go-bootstrap/bin/go: cannot execute binary file: Exec format error
The command '/bin/sh -c mkdir -p /usr/src/go-bootstrap  && curl -fsSL https://storage.googleapis.com/golang/go${BOOT_STRAP_VERSION}.linux-arm6.tar.gz | tar -v -C /usr/src/go-bootstrap -xz --strip-components=1        && mkdir /usr/src/go    && curl -fsSL https://storage.googleapis.com/golang/go${GO_VERSION}.src.tar.gz | tar -v -C /usr/src/go -xz --strip-components=1         && cd /usr/src/go/src   && GOOS=linux GOARCH=arm64 GOROOT_BOOTSTRAP=/usr/src/go-bootstrap ./make.bash' returned a non-zero code: 126
Makefile:82: recipe for target 'build' failed
make: *** [build] Error 1

The issue is armv6 released binaries are used as a GOROOT_BOOTSTRAP.
This might work on arm64 platforms that support 32-bit mode.
However not all arm64 platforms support 32-bit mode. So I would suggest to use gccgo as bootstrap.

# Install gccgo-5 for bootstrap Go 1.5.2
RUN sudo apt-get install -y gccgo-5
RUN update-alternatives --set go /usr/bin/go-5
ENV GOROOT_BOOTSTRAP=/usr

Regards
Vijay

**Comment by hqhq** [comment]
@vijaykilari All my ARM64 server support 32-bit mode, looks like there do have ARM64 platforms which don't support 32-bit. Would you mind open a PR? I can help test it :)

**Comment by vijaykilari** [comment]
Here is the pull request. Please review and test it.

https://github.com/docker/docker/pull/20342

**Comment by mlaventure** [comment]
Closing since #20342 was merged.
