### ISSUE TITLE
mount /var/lib/docker on glusterfs

### ISSUE THREAD

**Issue by bitchecker** [docker/docker#20323]
i've a glusterfs distribuited filesystem and i'm trying to use it to mount docker directory ( /var/lib/docker ) for scaling filesystem dimensions and allow my docker cluster to have images and containers available on all nodes but service doesn't start.

**Comment by thaJeztah** [comment]
> and allow my docker cluster to have images and containers available on all nodes but service doesn't start

I don't think this is a supported setup; also, having multiple daemons trying to write to the same `/var/lib/docker` is asking for trouble, and guaranteed data corruption.

**Comment by bitchecker** [comment]
so isn't possible to distribute storage of physical nodes on a shared storage?

**Comment by thaJeztah** [comment]
Currently, no (afaik). The daemon requires exclusive access to the `/var/lib/docker` directory; having other daemons interfere can lead to unexpected results. For example, downloading an image on one node, will not notify other daemons that the new image has been downloaded (or download is in progress). The same applies to containers.

**Comment by bitchecker** [comment]
it will be implemented?

**Comment by thaJeztah** [comment]
There's currently no plans to implement this as it will require a lot of changes

**Comment by vdemeester** [comment]
@bitchecker An alternative solution is probably to setup a local registry backed by a distributed filesystem (like glusterfs). If you run it in a docker container, you could use the `docker-volume-glusterfs` :stuck_out_tongue:.

**Comment by bitchecker** [comment]
local registry will be the next step on my deployment setup! :stuck_out_tongue_closed_eyes:

**Comment by tomachinz** [comment]
Do you know if the volumes folder in /var/lib/docker could be a shared volume? As in mounted in fstab to `/var/lib/docker/volume`? Or better to use the gluster driver in docker on a case by case basis as per docs?
> Currently, no (afaik). The daemon requires exclusive access to the `/var/lib/docker` directory; having other daemons interfere can lead to unexpected results.

 How about
