### ISSUE TITLE
NoNewPrivileges support in docker 

### ISSUE THREAD

**Issue by mrunalp** [docker/docker#20329]
[NoNewPrivileges](https://www.kernel.org/doc/Documentation/prctl/no_new_privs.txt) support was added to the OCI spec and is in the process of being added to [runc] (https://github.com/opencontainers/runc/pull/557). The purpose of this issue is to discuss options for integrating this into docker. There are two options:

1. Add a flag to enable this setting optionally.
2. Enable this setting by default for all containers.

Any thoughts?

@crosbymichael @LK4D4 @rhatdan

**Comment by rhatdan** [comment]
It should definitely be optional, some people might want to run containers with lower privileges but still allow users to sudo or use setuid apps to raise privileges.  I think Ping would be broken by turning this on by default at this point.

**Comment by mrunalp** [comment]
@rhatdan Yes, I agree that is the safer option and won't break existing applications.

**Comment by thaJeztah** [comment]
Would that be a new option to `--security-opt`? e.g. `--security-opt=no-new-privileges`?

**Comment by mrunalp** [comment]
@thaJeztah That sounds good to me since this is a security setting.

**Comment by rhatdan** [comment]
SGTM

**Comment by tianon** [comment]
This was fixed by #20727 :smile:
