### ISSUE TITLE
"docker network ls" shows output in different order each time

### ISSUE THREAD

**Issue by patrikerdes** [docker/docker#20328]
When doing the command `docker network ls` multiple times, the order of the output is not ordered the same way every time. I suggest that the output is sorted.

To reproduce:
```
# docker network ls
NETWORK ID          NAME                DRIVER
5ebdec72c3bb        host                host
95816560a753        bridge              bridge
949a5c581da7        none                null
# docker network ls
NETWORK ID          NAME                DRIVER
95816560a753        bridge              bridge
949a5c581da7        none                null
5ebdec72c3bb        host                host
```

I would expect the output to be sorted in some way, since that would make it easier to spot any differences in the list between invocations of the command. I don't have any specific suggestion on the sort order.

Docker version: `1.10.0, build 590d5108`

**Comment by ozlerhakan** [comment]
`$docker volume ls` also has the same behavior, but I am not 100% sure whether it's important or not. ı can open an usse for that if you want  @thaJeztah

**Comment by thaJeztah** [comment]
I think it's a "nice to have"; if it can be implemented cleanly, and the overhead is negligible, please go ahead and work on it! \o/

**Comment by ozlerhakan** [comment]
I actually would like to but after having go background  (: @thaJeztah

**Comment by thaJeztah** [comment]
Haha, no problem

**Comment by HackToday** [comment]
I could also help if it is needed. let me know if you cover it or not. @ozlerhakan

**Comment by HackToday** [comment]
#dibs

**Comment by HackToday** [comment]
@patrikerdes  Could you check comments 
https://github.com/docker/docker/pull/20383

What do you think the better ways to meet your requirements?
