### ISSUE TITLE
insecure-registry not working on RHEL7

### ISSUE THREAD

**Issue by Thorndike** [docker/docker#20320]
I have now finally got some machines upgraded to RHEL7 and insecure-registry is not working as expected. 
After installing docker from yum.dockerproject.org I have tried to insert OPTIONS in /etc/sysconfig/docker as described in some answered issues before. Unfortunately that is completely ignored!
As a workaround I added the options to the ExecStart line in /usr/lib/systemd/system/docker.service. That solved the problem but I do not see any link in the service definition to the config file which brings me to the conclusion that the config file is complete obsolete.

**Comment by Thorndike** [comment]
docker version:
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:34:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:34:50 2016
 OS/Arch:      linux/amd64

docker info:
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.10.0
Storage Driver: devicemapper
 Pool Name: docker-253:0-1573684-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.494 GB
 Data Space Total: 107.4 GB
 Data Space Available: 105.9 GB
 Metadata Space Used: 2.474 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.4.5.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.701 GiB
Name: rhscpm003.ecofis.de
ID: ZUPY:PLIJ:JYIR:EZTM:MSLG:PTV5:TEZX:YAPF:XHT4:NJJD:GM5D:YYID
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

List the steps to reproduce the issue:
1. Install docker from yum repo yum.dockerproject.org
2. add OPTIONS to config file
3. try to connect to private registry with self signed cert

**Comment by thaJeztah** [comment]
The "/etc/sysconfig/docker" file is no longer used on systemd systems; the recommended way to update this configuration, is to use a drop-in (not edit the default `docker.service`, as that will complicate updates of docker (where a newer service-file may be installed).

You can read this in the documentation; https://docs.docker.com/engine/admin/systemd/#custom-docker-daemon-options, but if you think additional changes in the documentation need to be made, please comment.

I'm going to close this issue, because this is expected, but feel free to comment if you have suggestions for improvement :+1:
