### ISSUE TITLE
Mounting a volume file breaks filesystem in bizarre ways

### ISSUE THREAD

**Issue by jake-low** [docker/docker#20322]
I thought I was going insane while investigating this.

Here's a file, located in `(pwd)/etc/krb5.conf`, that I was trying to mount into a container. The contents of this file aren't important; you can see I've fiddled with it in the process of trying to resolve this issue.

```
[libdefaults]
default_realm = LOCALDOMAIN

[realms]
LOCALDOMAIN = {
    kdc = kdc:88
    foo = bar
    admin_server = kdc:749
    baz = zip
}
```

The `md5sum` of this file (as reported by the host system) is `e2e55a4ef167b9aab10fd093589a6f9c`. `ls -l` has this to say about it:

```
$ ls -l etc/krb5.conf 
-rw-r--r--  1 jake  staff  142 Feb 15 00:17 etc/krb5.conf
```

Now let's do some exploring. First, no `/etc/krb5.conf` file exists in the Alpine base image:

```
$ docker run --rm -it alpine ls -l /etc/krb5.conf
ls: /etc/krb5.conf: No such file or directory
```

Mounting in the file with `-v` changes that, as expected:

```
$ docker run --rm -it -v (pwd)/etc/krb5.conf:/etc/krb5.conf alpine ls -l /etc/krb5.conf
-rw-r--r--    1 1000     50             142 Feb 15 08:17 /etc/krb5.conf
```

The uid/gid are unknown and the timestamp is different because of the TZ offset, but that's all to be expected.

Note: I use fish shell, which is why you're seeing `(pwd)` where you`d expect `$(pwd)`

**Here's where things go off the rails:**

```
$ docker run --rm -it -v (pwd)/etc/krb5.conf:/etc/krb5.conf alpine cat /etc/krb5.conf
[libdefaults]
default_realm = LOCALDOMAIN

[realms]
LOCALDOMAIN = {
    kdc = kdc.localdomain:88
    admin_server = kdc.localdomain:749
}

```

That's an older version of the file. At one point I saved that version, and I definitely mounted it into the container. I can't remember if I used `-v` or a compose file rule -- probably both, at different times.

But that version of the file no longer exists anywhere under `(pwd)`.

**But wait, there's more.**

Here's what I get when I view the file with `less`:

```
$ docker run --rm -it -v (pwd)/etc/krb5.conf:/etc/krb5.conf alpine less /etc/krb5.conf
[libdefaults]
default_realm = LOCALDOMAIN

[realms]
LOCALDOMAIN = {
    kdc = kdc:88
    foo = bar
    admin_server = kdc:749
    baz = zip
}

~
~
~
/etc/krb5.conf
```

It's the correct version -- what I would have called the _only_ version if not for this bizarre issue.

Furthermore, the MD5 checksum shows that it's the same file!

```
$ docker run --rm -it -v (pwd)/etc/krb5.conf:/etc/krb5.conf alpine md5sum /etc/krb5.conf
e2e55a4ef167b9aab10fd093589a6f9c  /etc/krb5.conf
```

So why does `cat` see a different version of this file than the other utilities do?

I figured it had to be a volumes bug. Somewhere in my `boot2docker` VM there was a copy of the old version of the file, living in some volume, and somehow that volume was getting loaded up... and then maybe the newer version was shadowing the older one.. and some utilities, er... while others...

Ignoring the fact that the above line of reasoning doesn't really hold up, I ran this before reproducing all of the above to post in this issue:

```
$ docker volume rm (docker volume ls -q)
```

At that point, `docker volume ls` showed no volumes, and running `find / -name krb5.conf` on my `boot2docker` VM found no results.

I can't fathom where this older version of the file is hiding, let alone different busybox utils see different versions of it.

**Feedback is welcome** on how I can improve this issue report. I have no idea how to reproduce the above scenario, but I'm leaving everything exactly as it is in the likely event that this needs more investigating. If there's stuff you want me to run, post it.

---

```
$ docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d510
 Built:        Fri Feb  5 08:21:41 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 19:55:25 2016
 OS/Arch:      linux/amd64
```

```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 478
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 264
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.1.17-boot2docker
Operating System: Boot2Docker 1.10.0 (TCL 6.4.1); master : b09ed60 - Thu Feb  4 20:16:08 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.956 GiB
Name: default
ID: UQ75:MAH2:6AVC:ISZO:WLVV:L63B:L2RI:KBVG:SINU:MSZA:6IG4:D4UH
Debug mode (server): true
 File Descriptors: 11
 Goroutines: 23
 System Time: 2016-02-15T08:55:42.020622045Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: jakelow
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Comment by jake-low** [comment]
Further observations:

It still happens if I mount the parent directory, rather than the file.

```
$ docker run --rm -it -v (pwd)/etc:/etc alpine cat /etc/krb5.conf
[libdefaults]
default_realm = LOCALDOMAIN

[realms]
LOCALDOMAIN = {
    kdc = kdc.localdomain:88
    admin_server = kdc.localdomain:749
}

```

And, excitingly, it reproduces on other files.

```
$ echo "Hello, world!" > etc/hello
$ docker run --rm -it -v (pwd)/etc:/etc alpine cat /etc/hello
Hello, world!
$ echo "Bye now." >> etc/hello
$ cat etc/hello 
Hello, world!
Bye now.
$ md5 etc/hello
MD5 (etc/hello) = 39c24d323add15a48dc040966fd4f20d
$ docker run --rm -it -v (pwd)/etc:/etc alpine cat /etc/hello
Hello, world!
$ docker run --rm -it -v (pwd)/etc:/etc alpine md5sum /etc/hello
39c24d323add15a48dc040966fd4f20d  /etc/hello
```

... but *not* with other images.

```
$ docker run --rm -it -v (pwd)/etc:/etc python:latest cat /etc/hello
Hello, world!
Bye now.
$ echo "P.S. no refunds." >> etc/hello
$ cat etc/hello 
Hello, world!
Bye now.
P.S. no refunds.
$ md5 etc/hello
MD5 (etc/hello) = 932e6e471794630446153d1ffa05d4c9
$ docker run --rm -it -v (pwd)/etc:/etc python:latest cat /etc/hello
Hello, world!
Bye now.
P.S. no refunds.
$ docker run --rm -it -v (pwd)/etc:/etc python:latest md5sum /etc/hello
932e6e471794630446153d1ffa05d4c9  /etc/hello
```

**Comment by thaJeztah** [comment]
Almost sounds as an issue with VirtualBox file sharing.

Note that `docker volume rm` won't make a difference in this case, because a bind-mounted directory is not created as a volume; it will bind-mount a directory on the host (the VirtualBox VM in this case) inside the container.

Wondering; which directory are you running this from? Is this directory inside your `/Users` directory?

**Comment by jake-low** [comment]
>  Is this directory inside your /Users directory?

Yes. Give me a few minutes and I'll try to reproduce it outside that path.

**Comment by thaJeztah** [comment]
@jake-low no that shouldn't work; if you're using boot2docker, only the `/Users` directory is shared with the virtual machine, anything outside that isn't, so doesn't exist in the virtual machine.

**Comment by jake-low** [comment]
Running the same repro outside of `/Users` resulted in empty directories instead of files (meaning the files weren't accessible to the docker engine). My assumptions about how `-v` works in conjunction with remote engines was incorrect.

Anyway, I tried the repro from `/tmp` on my VM, and, predictably, the issue did not reappear.

```
$ docker-machine ssh default
Boot2Docker version 1.10.0, build master : b09ed60 - Thu Feb  4 20:16:08 UTC 2016
Docker version 1.10.0, build 590d5108
$ cd /tmp
$ echo "Hello, /tmp." >> hello
$ md5sum hello
2ea1cdb036cd87c54a9b1b147ef3a89a  hello
$ docker run --rm -it -v $(pwd)/hello:/hello alpine md5sum /hello
2ea1cdb036cd87c54a9b1b147ef3a89a  /hello
$ docker run --rm -it -v $(pwd)/hello:/hello alpine cat /hello
Hello, /tmp.
$ echo "Bye now." >> hello
$ md5sum hello
0d4dd084973795af60a65574e9525c20  hello
$ docker run --rm -it -v $(pwd)/hello:/hello alpine md5sum /hello
0d4dd084973795af60a65574e9525c20  /hello
$ docker run --rm -it -v $(pwd)/hello:/hello alpine cat /hello
Hello, /tmp.
Bye now.
```

What mechanism is used to share `/Users` with the `boot2docker` VM? Where would I look on the VM's filesystem to see whether old versions of files are getting persisted?

**Comment by jake-low** [comment]
I should have done a little more digging before I commented again, sorry about that.

You're definitely right about the VM file sharing being the problem.

```
$ docker-machine ssh default
$ cd /Users/jake/.../etc
$ cat krb5.conf
default_realm = LOCALDOMAIN

[realms]
LOCALDOMAIN = {
    kdc = kdc.localdomain:88
    admin_server = kdc.localdomain:749
}

```

If I write to the file from inside the VM, I see no change:

```
$ hostname
default
$ echo "Testing, testing" >> krb5.conf 
$ cat krb5.conf 
[libdefaults]
default_realm = LOCALDOMAIN

[realms]
LOCALDOMAIN = {
    kdc = kdc.localdomain:88
    admin_server = kdc.localdomain:749
}

```

But the change _does_ have effect on the host!

```
$ hostname
Jakes-MBP
$ cat etc/krb5.conf 
[libdefaults]
default_realm = LOCALDOMAIN

[realms]
LOCALDOMAIN = {
    kdc = kdc:88
    foo = bar
    admin_server = kdc:749
    baz = zip
}
Testing, testing
```

It's like a wormhole in the filesystem.

**Comment by jake-low** [comment]
VirtualBox > About VirtualBox:

```
VirtualBox Graphical User Interface
Version 5.0.14 r105127
Copyright © 2016 Oracle Corporation and/or its affiliates. All rights reserved.
```

VirtualBox > Check for Updates:

```
You are already running the most recent version of VirtualBox.
```

**Comment by thaJeztah** [comment]
Wow that's strange indeed, so looks like it's narrowed down to `busybox cat` vs `less`?

Files between the host and VirtualBox are shared using VirtualBox guest additions, I know there's this issue; https://www.virtualbox.org/ticket/9069, but not sure what the issue behind that is, and if the same could affect `cat` here.

**Comment by jake-low** [comment]
I found another utility that suffers the same problem as `cat`: `cp`. On the VM:

```
$ cp krb5.conf krb5.conf.2
$ less krb5.conf  # this agrees with the host machine's view
[libdefaults]
default_realm = LOCALDOMAIN

[realms]
LOCALDOMAIN = {
    kdc = kdc:88
    admin_server = kdc:749
}

~
~
~
krb5.conf
$ less krb5.conf.2
[libdefaults]
default_realm = LOCALDOMAIN

[realms]
LOCALDOMAIN = {
    kdc = kdc:88
    foo = bar
    admin_serve
~
~
~
krb5.conf.2
```

And indeed, on the host machine (Jakes-MBP):

```
$ cat etc/krb5.conf.2
[libdefaults]
default_realm = LOCALDOMAIN

[realms]
LOCALDOMAIN = {
    kdc = kdc:88
    foo = bar
    admin_serve⏎
```

The common thread between `cat` and `cp` is [this function](https://git.busybox.net/busybox/tree/libbb/copyfd.c#n157), `bb_copyfd_eof`. It can (depending on the preprocessor) call `sendfile` under the hood, and it's the only place in Busybox's core utils that does so. I have a feeling the VirtualBox bug has to do with zero-copy syscalls.

**Comment by billmccord** [comment]
@jake-low Can you link to the VirtualBox issue? I just ran into this today and waster waaaaaayyyy too much time trying to figure out what was happening. Perhaps a notice could be made in the Docker documentation?
