### ISSUE TITLE
Can no longer specify registry port with docker tag in 1.10.1

### ISSUE THREAD

**Issue by peikk0** [docker/docker#20340]
This was still working up to Docker 1.9, but no longer in 1.10, docker tag doesn't parse the tag correctly:
```
% docker tag myimage:latest myregistry:5000/myimage:latest
Error parsing reference: "myregistry:5000/myimage:latest" is not a valid repository/tag
```

**Comment by thaJeztah** [comment]
Are you running docker 1.10, or 1.10.1? Some changes were made to this validation, but not sure if this is one of them.

**Comment by peikk0** [comment]
That's 1.10.1

**Comment by aaronlehmann** [comment]
This exact command succeeds for me.

```
root@3796f4228781:/go/src/github.com/docker/docker# docker tag busybox myimage:latest
root@3796f4228781:/go/src/github.com/docker/docker# docker tag myimage:latest myregistry:5000/myimage:latest
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Tue Feb 16 21:27:20 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Tue Feb 16 21:27:20 2016
 OS/Arch:      linux/amd64
```

Is `myregistry` a standin for something else that isn't validating?

**Comment by peikk0** [comment]
Yes it's a stand-in for something else. You've made me realize it's not because of the colon but because of an underscore:
```
% docker tag myimage:latest my_registry:5000/myimage:latest
Error parsing reference: "my_registry:5000/myimage:latest" is not a valid repository/tag
```
And underscore is not a valid character in a domain name indeed (that's a /etc/hosts entry in my case). So I don't know if it should be fixed or not. :)

**Comment by aaronlehmann** [comment]
Indeed, we tightened the validation to only allow valid domains or subdomains. We want to enforce the requirement that registry names be valid DNS names, otherwise there can be inconsistent behavior between different setups. I'm going to close this ticket since the behavior is intentional. Sorry about the unexpected change relative to Docker 1.9.
