### ISSUE TITLE
Error response from daemon: unknown log opt 'splunk-token' for json-file  log driver.

### ISSUE THREAD

**Issue by liuxiaopiao** [docker/docker#20347]
$ docker-machine -v
docker-machine.exe version 0.6.0, build e27fb87

$ docker -v
Docker version 1.10.1, build 9e83765

```
$ docker run -dtl --log-driver=splunk \
 --log-opt splunk-token=93378C06-B240-4F6B-BA4A-EC27FE3C62E3 \
 --log-opt splunk-url=http://192.168.99.100:8000 \
 nginx
694b939f4b23cf0722e40461dab6c637ea7a88d67afad63366a939aec4c44e66
docker: Error response from daemon: unknown log opt 'splunk-token' for json-file
 log driver.
```

Could you please help on this? I am using the latest version for docker toolbox and got the above error.  
Thanks

**Comment by thaJeztah** [comment]
Looks like the problem is in this part: `unknown log opt 'splunk-token' for json-file
 log driver` - for some reason, the default (`json-file`) driver is still being used.

I think I spot the issue; looks like you're using `-dtl` the last letter there looks to be a lowercase `L` (for `--label`) what happens if you change that to `i`?

**Comment by liuxiaopiao** [comment]
Thanks very much for the help @thaJeztah. Here is the output:

$ docker run -ti --log-driver=splunk --log-opt splunk-token=93378C06-B240-4F6B-
BA4A-EC27FE3C62E3 --log-opt splunk-url=http://192.168.99.100:8000 nginx
docker: Error response from daemon: Failed to initialize logging driver: splunk:
 failed to verify connection - 303 See Other - <!doctype html><html><head><meta
http-equiv="content-type" content="text/html; charset=UTF-8"><meta http-equiv="r
efresh" content="1;url=http://192.168.99.100:8000/en-US/services/collector/event
/1.0"><title>303 See Other</title><script type="text/javascript">
var hashTag = '', hashPos = document.location.href.indexOf('#');
if (hashPos > -1) { hashTag = document.location.href.substr(hashPos); }
document.location = "http://192.168.99.100:8000/en-US/services/collector/event/1
.0" + hashTag;
</script>
</head><body><h1>See Other</h1><p>The resource has moved temporarily <a href="ht
tp://192.168.99.100:8000/en-US/services/collector/event/1.0">here</a>.</p></body
></html>.

And I can access the splunk url http://192.168.99.100:8000.  Is there anything I missed?

**Comment by thaJeztah** [comment]
are you able to connect to that from inside the virtual machine? i.e. `docker-machine ssh default` and from inside the VM `curl ..` ?

**Comment by liuxiaopiao** [comment]
Thanks @thaJeztah. I figured this out by using the below command:
$ docker run --publish 80:80 --log-driver=splunk --log-opt splunk-token=93378C06-B240-4F6B-
BA4A-EC27FE3C62E3 --log-opt splunk-url=https://192.168.99.100:8088
--log-opt splunk-insecureskipverify=true nginx
