### ISSUE TITLE
Docker Quickstart no longer detects that VT-x is enabled on Windows 10

### ISSUE THREAD

**Issue by aro-tech** [docker/docker#20351]
I'm adding this issue because no one responded to my comment on issue 166.  I had Docker working fine on Windows 10 (family edition, French language), installed just a few weeks ago using the latest Docker Toolbox. Then a few days ago there was a Windows update, and since then, Docker no longer functions.  I tried removing the default VM and re-launching the quickstart and even upgrading VirtualBox, but so far I'm stuck. The message I get is: 
`(default) Creating VirtualBox VM...
(default) Creating SSH key...
(default) Starting the VM...
Error creating machine: Error in driver during machine creation: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory`

My BIOS and task manager both indicate that virtualization is enabled, I do not find any indication that Hyper-V is available on my machine, and the default machine seems to run okay in VirtualBox, so it seems like the Docker quickstart is falsely detecting that VT-X is not installed.

Output of `docker version`:
`Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      windows/amd64
An error occurred trying to connect: Get http://localhost:2375/v1.21/version: dial tcp 127.0.0.1:2375: ConnectEx tcp: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.`

Output of `docker info`:
`An error occurred trying to connect: Get http://localhost:2375/v1.21/info: dial tcp 127.0.0.1:2375: ConnectEx tcp: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.`

Output of `docker_machine ls`:
`NAME      ACTIVE   URL          STATE     URL   SWARM   DOCKER    ERRORS
default   *        virtualbox   Running                 Unknown   Something went wrong running an SSH command!
command : ip addr show dev eth1
err     : exit status 255
output  :`

**Comment by thaJeztah** [comment]
Have you tried if updating to the latest version of docker toolbox fixes this issue? https://github.com/docker/toolbox/releases

I see you commented on https://github.com/docker/toolbox/issues/166#issuecomment-183631216. Unfortunately, we won't be able to do anything about that in this repository, because the code for "Docker QuickStart" is in the https://github.com/docker/toolbox repository. I'm going to close this issue here for that reason, but feel free to continue the discussion here.
