### ISSUE TITLE
Flaky test: DockerSuite.TestLogsSinceFutureFollow?

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#20357]
Seen failing on win2lin;

https://jenkins.dockerproject.org/job/Docker-PRs-Win2Lin/21788/console
```
13:54:31 ----------------------------------------------------------------------
13:54:31 FAIL: docker_cli_logs_test.go:205: DockerSuite.TestLogsSinceFutureFollow
13:54:31 
13:54:31 docker_cli_logs_test.go:218:
13:54:31     c.Assert(ts >= since, checker.Equals, true, check.Commentf("earlier log found. since=%v logdate=%v", since, ts))
13:54:31 ... obtained bool = false
13:54:31 ... expected bool = true
13:54:31 ... earlier log found. since=1455630854 logdate=1455630853
13:54:31 
```

**Comment by aaronlehmann** [comment]
This is probably similar to #18479.

**Comment by icecrime** [comment]
Thanks for the pointer @aaronlehmann, looks like a similar problem indeed (and explains why it happens in context where client and daemon are not on the same host).

**Comment by estesp** [comment]
sort of.. have been looking at it a bit. I think it may be related to the conversion to epoch seconds and a difference in how the `since` as epoch seconds, and the actual date/logdate output are on some second boundary.  And yes, the fact the "`/info`" endpoint is hit in the remote case seems to trigger it more easily

**Comment by estesp** [comment]
either that or there is an actual bug in the `--since` time handling logic, because the epoch seconds of the container `date +%s` output is actually earlier than the numeric representation of the `since` as epoch seconds

**Comment by aaronlehmann** [comment]
@estesp: I think the problem is that the `date +%s` inside the container executes at a different time than the actual logging (i.e. this is racy). #18479 was the same problem. In that PR, I changed a different test to use the log timestamps instead of separate timestamps.

**Comment by estesp** [comment]
@aaronlehmann that makes sense, and I guess then a similar fix to not rely on the output as a comparator, but add `--timestamps` with a RFC timespec parser as the comparator is the right fix.  The difference in this test is we need a valid time comparison to handle the "future follow" scenario..
