### ISSUE TITLE
Custom formatting for syslog messages

### ISSUE THREAD

**Issue by dlsniper** [docker/docker#20354]
Hi,

There are some services which have their own formatting, such as Loggly, and I wonder if it would be possible to allow the users to format the whole log line not just the tag.
Thank you.

**Comment by HackToday** [comment]
hi @dlsniper  Could you elaborate it more ?  What's the expected format way look like ?
for example, right now, docker have options to specify with ***, but when other service expect it would have options like *** , and so on

**Comment by dlsniper** [comment]
Hi,

Here's more details about this, sorry for not including them in the original description:

```
Syslog Header

We only accept syslog events with a RFC5424 compliant header. Within the header there must be
a structured data set that includes your Customer Token and the Loggly private enterprise number
(PEN) which is 41058. Here’s an example of a compliant syslog header:

<34>1 2003-10-11T22:14:15.003Z server1.com sudo - - [8bf8cc10-4140-4c3e-a2b4-e6f5324f1aea@41058]
If you use syslog, we can guarantee that your syslog headers and structured data will be extracted,
independently of the actual message contents, provided you use our standard syslog configuration.
These configs are based on the Syslog Protocol RFC5424, and we will extract the following fields
(using RFC names):

PRIVAL, Facility, Severity, VERSION, TIMESTAMP, HOSTNAME, APP-NAME, PROCID, MSGID
Our standard config also allows you to define tags in the STRUCTURED-DATA part of the message.
As an example, if your structured data looks like this:

[01234567-89ab-cdef-0123-456789abcdef@41058 tag="foo" tag=bah]
we will extract “foo” and “bah” as tags, which you can then use to refine searches using tag:foo 
for example, and which you can also use in the Trending tab.

Notice that we support unquoted values, even though the RFC says these values must be quoted.
```

The description can also be found here: https://www.loggly.com/docs/streaming-syslog-without-using-files/

As such, a feature that would allow the formatting of the final message that Docker is able to send to syslog would solve issues such as having a `STRUCTURED-DATA` option (unless someone wants to add that specifically ofc).

In their example:
```
PRIVAL, Facility, Severity, VERSION, TIMESTAMP, HOSTNAME, APP-NAME, PROCID, MSGID
```
ideally Docker should provide all the above information so that it can be used and arranged as the user might need.

Please let me know if you need further information / details / help with this.

Thank you.

**Comment by thaJeztah** [comment]
We now have some options `--log-opt syslog-format=[rfc5424|rfc5424micro|rfc3164]` and other options; including facility; does that cover your use case?

https://docs.docker.com/engine/admin/logging/overview/#/syslog-options
```
--log-opt syslog-address=[tcp|udp|tcp+tls]://host:port
--log-opt syslog-address=unix://path
--log-opt syslog-address=unixgram://path
--log-opt syslog-facility=daemon
--log-opt syslog-tls-ca-cert=/etc/ca-certificates/custom/ca.pem
--log-opt syslog-tls-cert=/etc/ca-certificates/custom/cert.pem
--log-opt syslog-tls-key=/etc/ca-certificates/custom/key.pem
--log-opt syslog-tls-skip-verify=true
--log-opt tag="mailer"
--log-opt syslog-format=[rfc5424|rfc5424micro|rfc3164]
--log-opt env=ENV1,ENV2,ENV3
--log-opt labels=label1,label2,label3
```

**Comment by dlsniper** [comment]
@thaJeztah yes, it seems it does it. Thank you! Should I close the issue or should you?

**Comment by thaJeztah** [comment]
@dlsniper excellent! I'll close it

**Comment by dorintt** [comment]
> @thaJeztah yes, it seems it does it. Thank you! Should I close the issue or should you?

Would you mind sharing how exactly the existing log options can be used to add loggly UUID in header or as structured data?
