### ISSUE TITLE
Document and add option for listing only named or unnamed volumes with "docker volume ls -f ..."

### ISSUE THREAD

**Issue by JonasT** [docker/docker#20359]
Please document and add option for listing only named or unnamed volumes:

**How**
I suggest to make something possible like this: `docker volume ls -qf dangling=true,named=false`
If there already is such a filter, please document it on docker volume ls --help

**Why?**
The reasoning is simple: I have a script to clean up all the old stuff I don't need, and for volumes the most common case is that if they are dangling *and unnamed*, I probably didn't create them to be kept. However, if they are *named* I am most certainly interested in keeping them even if they aren't currently used by a container - obviously they were important enough that I bothered to give them a name.

Therefore, the common suggestion which involves deleting everything output by `docker volume ls -qf dangling=true` isn't helping here because that command also lists all named volumes, and a script (unlike a human) cannot easily tell the unnamed from the named ones in the resulting output of that command.

**Comment by thaJeztah** [comment]
I'm not sure it's easy to distinguish "named" vs "unnamed", because basically all volumes are named, but if no name is specified, it's automatically generated.

We've had similar discussions in the past (I.e., "don't delete named containers"), but I'm not sure that *name* is the best property to determine if something is "disposable" or not. Prior discussions were in favor of having something to lock/pin containers (volumes in this case), to prevent them from being accidentally deleted.

See https://github.com/docker/docker/pull/7523, and all issues/PRs linked to that


ping @cpuguy83 any thoughts on this?

**Comment by cpuguy83** [comment]
Yeah, this is not something easy to do right now.
We don't keep state on volumes and I've purposefully been punting on this until we're ready to do distributed state.

Note that you can safely do `docker rm -v` in Docker 1.10 and it will only remove "unnamed" volumes.

**Comment by JonasT** [comment]
Well I'm purely talking about volumes here, not containers. (so I would consider container pinning a separate issue)
As for volume pinning, if you ever add that you should really auto-pin any volume that is named.

However, one alternative way to improve all of this would be to allow volumes to have labels.
This could e.g. improve docker-compose behavior when `using docker-compose rm && docker-compose up -d` (without -v specified!), because I was told in the current state it would fail to pick up unnamed dangling volumes again if they're not directory mounted volumes (so basically VOLUME-induced volumes that aren't listed in the docker-compose.yml): this could lead to either unexpected disappearing data for the user if the user actually expected the volume to remain around, or otherwise if the user wasn't aware of them it could alternatively cause dangling volumes being left around unexpectedly. Both outcomes are somewhat unsatisfactory.
But if docker-compose could label the volumes that belong to a certain service, they could easily survive container recreation in docker-compose without becoming dangling. It would also allow labeling volumes for being explicitly named by the user, or just random throwaway volumes generated at some point.

**Comment by cpuguy83** [comment]
I'm talking about volumes.
"docker rm -v" removes all the attached volumes of a container (in addition to the container), unless they are named volumes.

**Comment by JonasT** [comment]
Sure, I said that because container pinning was mentioned above. However, there is still no global way to remove all unnamed volumes that are dangling, is there?

**Comment by cpuguy83** [comment]
@JonasT I'm not talking about container pinning in any way.

**Comment by JonasT** [comment]
Sorry if I just added to the confusion, I was referring to @thaJeztah 's issue link.

**Comment by HackToday** [comment]
seems named ways is not easy to differenet, and it is user-view of that instead of docker view.

**Comment by JonasT** [comment]
@cpuguy83 just wondering, how would `docker rm -v` know it is a named volume and leave it alone? Since there is no obvious way to print this info out from the command line... (If you know one by the way, that would be very helpful to know) - beyond a human guessing from the volume id whether it is an assigned name manually, of course.

**Comment by cpuguy83** [comment]
@JonasT It knows because we look at how the mount point was specified. `docker run -v /foo` is an unamed mountpoint, `docker run -v <anything>:/foo` is a named mountpoint.
This does not take into account if `<anything>` is generated name vs one that was explicitly set.

**Comment by JonasT** [comment]
Hm I see. My tool does something similar right now, but doing this on a global scale would require me to inspect all containers manually or something to get that info is somewhat unsatisfactory.... but I guess I could do that for now as a hack

**Comment by thaJeztah** [comment]
After an "anonymous" volume is created it has been given a (generated) name, so there's no real difference anymore between "named" and "unnamed".

We discussed this, and think it's not something we want to implement
