### ISSUE TITLE
Improve node.js example in docs

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#20368]
This official documentation on dockerizing a Node.js app is so misleading, and should highlight not for production.

<blockquote class="twitter-tweet" data-partner="tweetdeck"><p lang="en" dir="ltr">This official documentation on dockerizing a Node.js app is so misleading, and should highlight not for production.<a href="https://t.co/ieb0qkIxLK">https://t.co/ieb0qkIxLK</a></p>&mdash; Manoj Mahalingam (@manojlds) <a href="https://twitter.com/manojlds/status/699666115849400320">February 16, 2016</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by YeZhenan** [comment]
I'm the new beginner and I think I can work on this issue if it is not fixed. But I don't understand what "should highlight not for production" means.

**Comment by manojlds** [comment]
Thanks @moxiegirl. Let me elaborate:

1) You don't do npm install in the production container.
2) You don't do just npm install, you have to do `npm install --production` to make sure only production dependencies are installed.

**Comment by YeZhenan** [comment]
I'm going to modify the dockerfile according to your advice and add `npm install --production` into the dockerfile, like this:

FROM   centos:centos6

\# Enable Extra Packages for Enterprise Linux (EPEL) for CentOS
RUN     yum install -y epel-release
\# Install Node.js and npm
RUN     yum install -y nodejs npm

\# Install app dependencies
COPY package.json /src/package.json
RUN cd /src; npm install --production

\# Bundle app source
COPY . /src

EXPOSE  8080
CMD ["node", "/src/index.js"]

@manojlds Is it right?

**Comment by YeZhenan** [comment]
#dibs

**Comment by thaJeztah** [comment]
I wonder if we should use the official nodejs image in this example, in stead of using a (also very outdated) `centos6` image as base. i.e. https://hub.docker.com/_/node/

**Comment by FWirtz** [comment]
@thaJeztah Yes, you should! **centos6 uses Node v0.1**, the **current version is >4.x**! I took the official Node.js Documentation (which is way better on this one, sorry) and updated the example accordingly, see my **pull request** #22128, not the issue.

Node.js Documentation: https://nodejs.org/en/docs/guides/nodejs-docker-webapp/

**Comment by moxiegirl** [comment]
@thaJeztah I'm going to be removing this piece. I'm working on devicemapper stuff at the moment.
