### ISSUE TITLE
Better Plugin Infrastructure

### ISSUE THREAD

**Issue by mlaventure** [docker/docker#20363]
As part of 1.11 we want to allow plugins lifecycle to be easily handled directly via the docker command line.

While using the docker cli, it should be made easy to do the following with plugins:
* discover
* download
* install
* enable/disable
* uninstall
* list installed plugins status

A new `plugin` verb may be added to the docker to cleanly separate the above.

## Impacts
* Unify the interface used to manage all thing docker related
* Make it easier to set a good practice of running plugin within containers
* Would allow auto-restart of crashed/stuck plugins
* One more verb to learn :)

**Comment by jainvipin** [comment]
+1 @mlaventure

It would be good to add some more syntax and description around various commands, for example: would `discover` fetch all supported plugins as specified/uploaded on official hub repository? `docker plugin install plugin_name:version` could be the syntax for installing a plugin

One very useful feature `plugin` verb can provide to the user is a way to provide plugin compatibility based on the APIs supported by a specific version of a plugin and current docker version. Failing install upon incompatible version load will improve Ux. Even better, if discover only returns compatible versions of plugins.

How would 'install' work? What if the plugin requires additional containers to run as a part of plugin install, say its own kv store (for a global network plugin)? What is the user expectation from `install` operation? If it is meant to be a `that's all you'll need to do`? If yes, then plugin itself must be allowed to install other elements i.e. after copying the plugin file, `plugin install` would trigger `install` call to the plugin

What is the purpose of `enable`/`disable` - most of the plugins when starting take some attributes, how are those attributes passed to the containers using `enable/disable` commands?

Authorization plugin is specified during docker daemon start, thus can't be used with this API/CLI/Interface?

**Comment by rhatdan** [comment]
I am not crazy about this idea, Pulling in more privileged code without any proper packaging or security approval.  Enable/disable is fine, but install/uninstall I believe is dangerous.

**Comment by cpuguy83** [comment]
@rhatdan I think "install" here is downloading an image from a registry and running it in a container.

**Comment by rhatdan** [comment]
But even in that case it could be dangerous since it would be modifying the behaviour of docker in unexpected ways.

**Comment by cpuguy83** [comment]
@rhatdan What unexpected way?

**Comment by mlaventure** [comment]
@cpuguy83 exactly.

@jainvipin I didn't mean `discover` as the name of the command per se, it could be called `search`. His function would be to look into the registry for plugins matching a given criteria (e.g. name, type, etc.) . And I agree that it should probably only display compatible version by default (and all of them with a flag explaining why it's been filtered out?)

Regarding letting plugins install their own dependencies, I am not a huge fan of the idea. I would rather have something akin to manifest that describes plugins dependencies and letting docker take care of getting those. That way install would be self sufficient.

For the authz plugins, the cli can be smart enough to require the daemon to restart after upgrading/installing/disabling/enabling such a plugin

**Comment by rhatdan** [comment]
Plugins can have and use the docker socket to examine things like images.  For example we are building authorization plugins that will look at the content of an image before allowing certain users to do activity.   If you are saying this will only work with very locked down non privileged containers, then plugins begin to loose their power.

**Comment by cpuguy83** [comment]
@rhatdan I'm not sure how running the plugin in a container changes this.
The plugin will get the privileges it needs to run, and that's up to the user to allow it.

**Comment by mlaventure** [comment]
@rhatdan we're not planning on forcing plugins to run in a non-privileged container even that would be the preferred mode whenever possible.

**Comment by rhatdan** [comment]
You are also setting up a circular requirement where docker is pulling/running plugins which could be required to run docker.  For example, we want to build a plugin that would block docker from running containers with known CVE's.  If I can't guarantee that that plugin is running, before any other containers are started, my plugin is broken, never mind the fact that my plugin container could have a CVE against it.

**Comment by mlaventure** [comment]
Plugins required for the daemon to run properly would obviously be loaded first before any containers are allowed to be spawned.

Regarding your CVE issue, you have the same situation today if you decide to run it inside a container if I'm not mistaken.

**Comment by bboreham** [comment]
> obviously be loaded first before any containers

Is that covered by this issue?  Its description mostly speaks about the CLI.

Some related discussion at #18724.

**Comment by erikh** [comment]
I would like to see how plugin dependencies are determined, e.g., ceph.

**Comment by jainvipin** [comment]
> Regarding letting plugins install their own dependencies, I am not a huge fan of the idea. I would rather have something akin to manifest that describes plugins dependencies and letting docker take care of getting those. That way install would be self sufficient.

Using a manifest to capture the dependencies will work better/cleaner. Having a reasonable replacement way of specifying dependencies (as in systemctl) would be ideal.

**Comment by jvinod** [comment]
As it stands, on a docker restart, containers that rely on a volume from a plugin container fail to start if the plugin container is not started first. So +1 to a deterministic container startup sequence :) The startup sequence should also ensure that plugin is up (handshake successful) before moving on to dependent containers.  And for a clean docker daemon shutdown, the sequence should be reversed: stop the plugin containers in the end.

**Comment by erikh** [comment]
> Regarding letting plugins install their own dependencies, I am not a 
> huge fan of the idea. I would rather have something akin to manifest 
> that describes plugins dependencies and letting docker take care of 
> getting those. That way install would be self sufficient.

This works for me.

Some additional thoughts:

FWIW my complete use case is simple, and I believe a practical one: I 
need ceph installed before volplugin will succeed at doing anything of 
use, which would be a problem if it became available before ceph did. 
So, I need a way to orchestrate two things:

- Plugins depending on a container startup (ideally a suite of them)
- A way to get said container image(s) installed

Plugins can just be flagged unavailable if dependencies do not start. 
They are all referenced at time an operation occurs and polled so there 
should be no inherent need to interrupt or stop docker. However, I think 
there should be an option to enable blocking behavior if that happens; 
as an administrator I would prefer to fail (or at least have the option 
to) the whole node if any part of it isn't functioning.

I hope this is useful feedback. Thanks.

-Erik

**Comment by rhatdan** [comment]
You are slowly building all of the features of systemd without using systemd, seems like this is likely to be loaded with failures.  Socket activation would be a key feature to handling most of these things.

**Comment by cpuguy83** [comment]
@erikh In such a case, I would make it the responsibility of the plugin to handle this.
One problem to tackle with such an approach though is allowing the plugin to start a container while the daemon is working on starting plugins (first).

**Comment by erikh** [comment]
Yep! I have to do it out there or inside docker. If I have to configure 
the host to get my plugin to work, this whole exercise is not very 
useful to my plugin (and probably a lot of others).

**Comment by aanm** [comment]
@rhatdan What is the difference between using docker to install a plugin and installing the plugin without docker?

**Comment by rhatdan** [comment]
An admin can configure a plugin to control docker.  You have a checken an egg situation.  If I set up an authorziation plugin to say that docker is not allowed to pull unsigned images, but it needs to pull an image before it can run the authorization plugin.  

I actually believe that containers can be used for shipping the plugins.  I am thinking these plugins should run as runc containers or something else, and then could be used by the docker daemon.    You could then take advantage of systemd for starting the unit files in the correct order or even use socket activation for starting the plugins.  

If docker is going to be incharge of running its own plugins  and these plugins can control what docker can do, it is going to get very complicated.  Docker is going to have to build all of the technology for ordering the startup of containers, that systemd has perfected over the last several years.

In my mind, the way to handle this would be for docker pull to potentially pull the container image to the system but then to explode the containers image onto disk and use runc and systemd unit files for running the plugins.

**Comment by cpuguy83** [comment]
@rhatdan I'm really not certain how your solution solves the problem. If docker is going to pull down an image and just have that offloaded to systemd then you still have the issue of ensuring that the pulled down image meets authorization criteria.
Really there is nothing stopping someone from doing exactly as you proposed here today.

Plugins work by engine talking to a service over a socket and some protocol.... it really doesn't matter how that service gets started Docker will still talk to it. But the engine does need to provide a way to make this simpler for its users. It won't change that you can still do this through other means.

**Comment by thaJeztah** [comment]
Linking https://github.com/docker/docker/issues/20370, which is also relevant here

**Comment by bboreham** [comment]
Similar to the comments about volume plugins, if you have a network plugin implemented inside a container, and someone uses it in another container with `--restart=always`, on reboot the network plugin need to get started before the container using it, or at least before Docker gives up trying to talk to the plugin.

Some logs at https://github.com/weaveworks/weave/issues/2222

**Comment by jefflill** [comment]
I'm a Docker newbie, but how about this:

It seems like Docker could consider loading the failure of a container to reference a plugin to be a normal container start failure, resulting in normal container restart attempts in the future.  This seems like it could be a relatively contained change (I haven't looked at the Docker code) that fits with the current model.

That being said, it does seem like it would make sense for Docker to prioritize starting plugin containers.  It would be unfortunate if Docker happened to start a plugin container after maybe 100 other containers that depend on it.

Perhaps Docker could implement a simple priority scheme via a --priority=# run option.  Docker would load containers with priority 0 before 1, etc.  This would be much easier than a full-on dependency scheme.  Plugin containers (like normal containers) would then need to be resilient when required containers haven't been loaded yet or fail to allow Docker to restart them (hoping that the required containers have been loaded by then).

**Comment by jefflill** [comment]
To clarify: It appears that Docker currently aborts restarting a container that needs a plugin that isn't ready, rather than scheduling the container to restart later (as Docker would do for other container failures).

The idea here is treat plugin reference failures as normal container failures.  Doing this would help the plugin container load order scenario and it would also add resilience even for situations where plugins are implemented as normal host processes (i.e. explicit systemd dependencies between Docker and the plugins wouldn't be strictly necessary).

Think of the --priority option as like a hint that optimizes container starts.  Plugins and other containers should still be resilient when dependencies aren't ready, but the priority will make this less likely to occur resulting in containers being ready sooner.

**Comment by TrimBiggs** [comment]
+1

When docker restarts with a network plugin running as a container, all endpoints/containers networked with the plugin will fail to start once docker is back up because the endpoint data remains in the datastore config.  Docker cannot talk to the network plugin because it stops the plugin before syncing.  There should be some sort of resync command or information to pass to docker to indicate where the plugin is running (such as a docker container name).  See more details in this issue: https://github.com/docker/docker/issues/22239

**Comment by bboreham** [comment]
Just leaving a comment referencing #23446 - "experimental support for new plugin management", so that subscribers get an email.
