### ISSUE TITLE
Long builds hang docker client when using TLS

### ISSUE THREAD

**Issue by PatrickLang** [docker/docker#20369]
When doing a specific large build remotely to a small VM, it appears to take around 10 minutes to complete. This may be expected due to disk/cpu constraints. However, the docker client hangs indefinitely. The server logs show that the client disconnected - but the Windows docker client is still running afterwards.

BUG REPORT INFORMATION

Daemon version info:
```
time="2016-02-12T23:03:25.156991300Z" level=info msg="Docker daemon" commit=59a341e execdriver="\n Name: Windows 1854\n Build: 1.10.0-dev 59a341e \n Default Isolation: process" graphdriver=windowsfilter version=1.10.0-dev

OS: Windows Server 2016 TP4 - using Azure gallery image
```

Client:
```
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:14:21 2016
 OS/Arch:      windows/amd64
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):

List the steps to reproduce the issue:
Steps with UI
1. Create an Azure Basic A1 (1 core, 1.75 GB memory) VM, running Windows Server 2016 TP4
2. Create a Core ASP.net application in Visual Studio, using [Visual Studio 2015 Tools for Docker - February Preview](https://visualstudiogallery.msdn.microsoft.com/0f5b2caa-ea00-41c8-b8a2-058c7da0b3e4)
3. Publish a Core ASP.net application to a Docker container on that VM - see download and step by step guide [here](https://visualstudiogallery.msdn.microsoft.com/0f5b2caa-ea00-41c8-b8a2-058c7da0b3e4)
4. The publishing process waits on docker.exe to terminate, so everything looks like its hung.

Steps without UI:
1. Create an Azure Basic A1 (1 core, 1.75 GB memory) VM, running Windows Server 2016 TP4
2. Create and build this Dockerfile, using the files created from the UI steps
```
FROM windowsservercore
ADD . /app
WORKDIR /app/approot
ENTRYPOINT web.cmd
```
3.docker --tlsverify -H tcp://plang-docker-w2.westus.cloudapp.azure.com:2376 build -t webapplication1 -f "C:\...\WebApplication1\Dockerfile" "C:\...\WebApplication169"

Describe the results you received:
The build never completes on the first attempt. If I watch the daemon to finish creating the image, then try again, it succeeds.

Here is where it hangs:
```
VERBOSE: Building Docker image: webapplication1
Executing command [docker --tlsverify -H tcp://plang-docker-w2.westus.cloudapp.azure.com:2376 build -t webapplication1 -f "C:\Users\plang\AppData\Local\Temp\PublishTemp\WebApplication169\approot\src\WebApplication1\Dockerfile" "C:\Users\plang\AppData\Local\Temp\PublishTemp\WebApplication169"]
VERBOSE: Sending build context to Docker daemon 557.1 kB
VERBOSE: Sending build context to Docker daemon 1.114 MB
VERBOSE: Sending build context to Docker daemon 1.671 MB
...
VERBOSE: Sending build context to Docker daemon 165.3 MB
VERBOSE: 
VERBOSE: Step 1 : FROM windowsservercore
VERBOSE:  ---> 6801d964fda5
VERBOSE: Step 2 : ADD . /app
```

Describe the results you expected:
I would expect the build to succeed on the first attempt, even if it takes a long time.

Provide additional info you think is important:

Full daemon logs are attached:
[Full Logs: docker.log_truncated.txt](https://github.com/docker/docker/files/133252/docker.log_truncated.txt)

I think these excerpts may help narrow it down:
```
time="2016-02-16T19:57:18.408610800Z" level=debug msg="Calling POST /v1.22/build" 
time="2016-02-16T19:57:18.408610800Z" level=info msg="POST /v1.22/build?buildargs=%7B%7D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=approot%2Fsrc%2FWebApplication1%2FDockerfile&memory=0&memswap=0&rm=1&shmsize=0&t=webapplication1&ulimits=null" 
```

```
time="2016-02-16T20:06:59.123283200Z" level=debug msg="Calling proc" 
time="2016-02-16T20:06:59.123283200Z" level=debug msg="hcsshim::NameToGuid Name bae19e317af6661e29fd9a5719ff9592e69f98e5986ba0e2dd710a94a3765d53" 
time="2016-02-16T20:06:59.123283200Z" level=debug msg="Calling proc" 
time="2016-02-16T20:06:59.123283200Z" level=debug msg="hcsshim::NameToGuid Name CN=Microsoft_WindowsServerCore_10.0.10586.0" 
time="2016-02-16T20:06:59.123283200Z" level=debug msg="Calling proc" 
time="2016-02-16T20:07:00.285349100Z" level=info msg="Client disconnected, cancelling job: build" 
```

Around that time, the build appears to have completed.
* docker images - lists WebApplication1:latest
* docker ps - nothing else running

If I try the same build again immediately - it succeeds. I presume the caching is making it complete quickly enough to avoid this hang.

```
VERBOSE: Step 1 : FROM windowsservercore
VERBOSE:  ---> 6801d964fda5
VERBOSE: Step 2 : ADD . /app
VERBOSE:  ---> Using cache
VERBOSE:  ---> bae19e317af6
VERBOSE: Step 3 : WORKDIR /app/approot
VERBOSE:  ---> Using cache
VERBOSE:  ---> 9ff140d4537b
VERBOSE: Step 4 : ENTRYPOINT web.cmd
VERBOSE:  ---> Using cache
VERBOSE:  ---> 955d9c33331c
VERBOSE: Successfully built 955d9c33331c
The Docker image "webapplication1" was created successfully.
```

----------END REPORT ---------

**Comment by thaJeztah** [comment]
@PatrickLang haven't heard about this anymore, is this still an issue? @jhowardmsft

**Comment by jhowardmsft** [comment]
I'd be pretty sure this far down the road, it's safe to close this. Please re-open if you can repro on RTM builds.
