### ISSUE TITLE
Apache doens't start 

### ISSUE THREAD

**Issue by CaredduMattia** [docker/docker#20364]
I want to start automatically apache service when container run.
So in my docker file I added : 
RUN service apache2 start
But if i check apache status i get that apache doens't run.
If i start apache manually after container is run apache start without any problem.
How can i solve this?

**Comment by cpuguy83** [comment]
@CaredduMattia processes must stay in the foreground in order to keep the container running.
Please see docs.docker.com which has a few examples, specifically with services like apache and nginx.

**Comment by CaredduMattia** [comment]
@cpuguy83 This is not what i asked.  My question is different.
Container is running but apache doesn't start.

**Comment by cpuguy83** [comment]
@CaredduMattia Please check out the docs.

Also note that `RUN service apache2 start` won't run apache except for within the confines of the single `RUN` command in your Dockerfile.

#docker on IRC and the docker-user mailing list are also both very active with people who can help you get started.

**Comment by doomsbuster** [comment]
i am having a similar issue where i have a very simple docker image that has just apache on `ubuntu:14.04`. I am using an `entrypoint` script to start apache in foreground (I plan to add upon this image with the web app and other dependencies). My container starts and quits instantly. Here are my docker files and `entrypoint.sh` shell script. Can anyone help me understand how to look at why the container is quitting and not starting apache? Here is the Gist:

https://gist.github.com/doomsbuster/bd645076f8a13cc639593eff109043f7
