### ISSUE TITLE
Docker 1.10.1 don't start any container on Centos7 (on OpenVZ)

### ISSUE THREAD

**Issue by stibi** [docker/docker#20376]
Description of problem: Docker daemon doesn't start any container.

`docker version`:
```
[root@stroj ~]# docker version                                                                                                                                                         [0/7444]
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:18:46 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:18:46 2016
 OS/Arch:      linux/amd64
```

`docker info`:
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.10.1
Storage Driver: vfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 2.6.32-042stab108.8
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 4 GiB
Name: stroj
ID: GPTQ:KUM4:VKSA:6XRP:U62H:KYRR:XQ6L:BPYY:6732:OFRE:AZB7:3CRO
WARNING: No oom kill disable support
```

`uname -a`:
`Linux stroj 2.6.32-042stab108.8 #1 SMP Wed Jul 22 17:23:23 MSK 2015 x86_64 x86_64 x86_64 GNU/Linux`

Environment details (AWS, VirtualBox, physical, etc.):

It's openvz virtual machine, with centos7. Nothing more special.

How reproducible: always

Steps to Reproduce:
1. docker run --rm hello-world

Actual Results:
```
Timestamp: 2016-02-17 01:11:12.625716427 +0100 CET
Code: System error

Message: stat /sys/fs/cgroup/system.slice/docker.service: no such file or directory

Frames:
---
0: setupRootfs
Package: github.com/opencontainers/runc/libcontainer
File: rootfs_linux.go@40
---
1: Init
Package: github.com/opencontainers/runc/libcontainer.(*linuxStandardInit)
File: standard_init_linux.go@57
---
2: StartInitialization
Package: github.com/opencontainers/runc/libcontainer.(*LinuxFactory)
File: factory_linux.go@240
---
3: initializer
Package: github.com/docker/docker/daemon/execdriver/native
File: init.go@35
---
4: Init
Package: github.com/docker/docker/pkg/reexec
File: reexec.go@26
---
5: main
Package: main
File: docker.go@18
---
6: main
Package: runtime
File: proc.go@111
---
7: goexit
Package: runtime
File: asm_amd64.s@1721
docker: Error response from daemon: Container command not found or does not exist..
```

Expected Results: a running container ...

Additional info: from the docker.sevice log I can see:

```
Feb 17 01:11:12 stroj docker[481]: time="2016-02-17T01:11:12.672610746+01:00" level=warning msg="exit status 1"
Feb 17 01:11:13 stroj docker[481]: time="2016-02-17T01:11:13.301861899+01:00" level=error msg="error locating sandbox id de883bb97f5421d2880f57404ed1f1851e3cbf7d214deb4dafa4003cddcc9490: sandbox de883bb97f5421d2880f57404ed1f1851e3cbf7d214deb4dafa4003cddcc9490 not found"
Feb 17 01:11:13 stroj docker[481]: time="2016-02-17T01:11:13.301968911+01:00" level=warning msg="failed to cleanup ipc mounts:\nfailed to umount /var/lib/docker/containers/7d90c473c26be57c9d47d75dc468da0bd63fa3fa02584778b2cf1fdfd0922469/shm: invalid argument"
Feb 17 01:11:13 stroj docker[481]: time="2016-02-17T01:11:13.302008679+01:00" level=error msg="Error unmounting container 7d90c473c26be57c9d47d75dc468da0bd63fa3fa02584778b2cf1fdfd0922469: not mounted"
Feb 17 01:11:13 stroj docker[481]: time="2016-02-17T01:11:13.302170978+01:00" level=error msg="Handler for POST /v1.22/containers/7d90c473c26be57c9d47d75dc468da0bd63fa3fa02584778b2cf1fdfd0922469/start returned error: Container command not found or does not exist."
```

**Comment by hqhq** [comment]
I got a similar problem on fedora22, can't start any containers if I start daemon with `systemctl start docker.service`, while if I start daemon with `docker daemon -D -s overlay`, it works as normal.

Is that the same for you?

**Comment by HackToday** [comment]
From the `docker info` output, it show that it use

Storage Driver: vfs

it seems it was not suggested to use that in docker docs, mainly include are
```
aufs
devicemapper
btrfs
zfs
overlay
windows
```

@thaJeztah  do you think vfs is supported in all platform ?

**Comment by stibi** [comment]
It looks that only the `vfs` driver is support on OpenVZ: https://openvz.org/Docker_inside_CT

I can't start the deamon with `overlay` storage driver, not supported :(

```
DEBU[0000] docker group found. gid: 982                 
DEBU[0000] Server created for HTTP on unix (/var/run/docker.sock) 
WARN[0000] Your Linux kernel version 2.6.32-042stab108.8 can be unstable running docker. Please upgrade your kernel to 3.10.0. 
DEBU[0000] Using default logging driver json-file       
DEBU[0000] [graphdriver] trying provided driver "overlay" 
ERRO[0000] 'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded. 
DEBU[0000] Cleaning up old shm/mqueue mounts: start.    
FATA[0000] Error starting daemon: error initializing graphdriver: driver not supported
```

I just tried to create a new, clean centos7 server on the OpenVZ platform and installed docker…and it works. So something is wrong on my server.

**Comment by stibi** [comment]
Maybe I have found why docker works on the new clean Centos7 server I have created…

The new server is placed on a node with newer kernel: https://openvz.org/Download/kernel/rhel6/042stab113.11

The other server, where docker doesn't work, run on a node with older kernel: https://wiki.openvz.org/Download/kernel/rhel6/042stab108.8

That's it I guess...

**Comment by thaJeztah** [comment]
The `vfs` driver should not be used for anything serious/useful. it's supported on all platforms, because it basically just copies all files for each layer, so no copy-on-write etc, just plain duplication of all files.

**Comment by thaJeztah** [comment]
@stibi following the above, I think this can be closed? I'll go ahead and close, but feel free to continue the discussion after I've closed

**Comment by kujiy** [comment]
I had a similar problem and solved with changing the storage driver.
http://serverfault.com/questions/755434/how-to-upgrade-docker-to-1-10-0-on-centos7/757797#757797

If someone has a same trouble, please try this.

#### $ vi /etc/systemd/system/docker.service.d/docker.conf 
```
[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon -s devicemapper -H fd://
```

or

```
[Service]
ExecStart=
ExecStart=docker daemon -D -s overlay
```

If you lost all of your images with `$ docker images`, check your current docker storage driver with `$ docker info` command. And change the driver to what you used.

The storage driver list is in here.
https://docs.docker.com/engine/reference/commandline/daemon/

**Comment by stibi** [comment]
@kujiy as I mentioned above, on the OpenVZ virtualization, **only** supported storage driver is **vfs**, nothing else. My server, where I had the troubles, is actually running on OpenVZ, so there is the limitation with storage drivers support. Anyway, even the storage driver change would not solve the problem, because the root cause is an old OpenVZ kernel.

**Comment by kujiy** [comment]
@stibi sorry for bother you. As you said I didn't use OpenVZ but I could easy to find this similar issue with google and this issue led me to the way to solve. I  appriciate that. So I'd like to share it to someone. There are a few info about Cent OS 7 on internet. All I wanted to share was that the storage driver was important on the OS with docker 1.10, as you mentioned above.
Thank you.
