### ISSUE TITLE
cross repository push fail for token auth registry

### ISSUE THREAD

**Issue by overmike** [docker/docker#20387]
Description of problem:
docker push fail to registry use token auth for first try and fallback to upload whole blobs for second try

`docker version`:

>  docker version
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:14:21 2016
 OS/Arch:      darwin/amd64

> Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 20:39:58 2016
 OS/Arch:      linux/amd64

`docker info`:
>Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 575
Server Version: 1.10.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 645
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 4.1.17-boot2docker
Operating System: Boot2Docker 1.10.1 (TCL 6.4.1); master : b03e158 - Thu Feb 11 22:34:01 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.859 GiB
Name: default
ID: VBEJ:W6VP:ALDO:2JD6:F7XC:WF5W:57YA:3GXP:XQP3:LCND:2CZK:5S7K
Debug mode (server): true
 File Descriptors: 111
 Goroutines: 123
 System Time: 2016-02-17T07:53:05.391192631Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox`

`uname -a`:
>Darwin Weaver.local 14.5.0 Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64 x86_64
>Linux default 4.1.17-boot2docker #1 SMP Thu Feb 11 08:12:31 UTC 2016 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
VirtualBox

How reproducible:
Preparation
>docker pull ubuntu
docker tag ubuntu 127.0.0.1:5000/ubuntu
docker push 127.0.0.1:5000/ubuntu
docker tag 127.0.0.1:5000/ubuntu 127.0.0.1:5000/linux

Actual push
>docker push 127.0.0.1:5000/linux
5f70bf18a086: Preparing
90222f49bc4c: Preparing
708fd576a927: Preparing
4aeeaca5ce76: Preparing
unauthorized: authentication required`

and when I push again
>docker push 127.0.0.1:5000/linux
5f70bf18a086: Pushed
90222f49bc4c: Pushed
708fd576a927: Pushed
4aeeaca5ce76: Pushed
latest: digest: sha256:d89fbabb2256cd7845ac69a11955295e39648863ad36e45b21248e61c97713c1 size: 1129

In registry log, found log
`level=warning msg="error authorizing context: insufficient scope"`
for api
`POST /v2/<name>/blobs/uploads/?mount=<digest>&from=<repository name>`
and for second try, it fallback to push whole blobs

And for the JWT, it only includes the target repository access control info, but no source (from) repository access control info
access=[{name=linux, type=repository, actions=[push, pull]}]}

Actual Results:
unauthorized

Expected Results:
docker push with comment "Mounted from...."
I expect docker client ask for JWT with all related repository before send blobs uploads request to registry. And one more side effect is that docker client fail for first try and success for second try

Additional info:

**Comment by erikswanson** [comment]
This is even worse than just breaking the mount feature. I'm seeing the same layer getting pushed more than once for different tags in the *same* repository. (I'm 99% sure these are the layers it's attempting to mount and failing.)

**Comment by aaronlehmann** [comment]
@BrianBland could you please look into this?

Could this be a compatibility issue with a particular token provider?

**Comment by erikswanson** [comment]
I was using cesanta/docker_auth. From what I remember while I was looking at this, it was granting the  single-repository scope that docker engine was requesting. (Is there some presumption of giving more scope than requested?)

Unfortunately, my logs of the problem gone now (sorry!), as I've had to fail over to a setup using client certificates and nginx to restrict by http method until this gets fixed.

**Comment by BrianBland** [comment]
It looks like there's a few undesirable behaviors going on:

1. cesanta/docker_auth only understands a single scope query parameter, and the docker engine is requesting push/pull for the repository you are pushing to and pull access for the repository you're mounting the blob from. This means you request both scopes and the auth server only returns a token with the single repository scope.

2. The docker engine receives a 401 Unauthorized from the registry when providing only the push/pull scope for the destination repository when attempting a cross-repository blob mount, then refuses to retry the layer push because a 401 is considered a terminal error in the push flow.

I can address issue number 2 so that it immediately falls back to pushing the blob on auth failure, specifically for the case of a cross-repo push, but I'd recommend filing an issue with cesanta/docker_auth to support this workflow.

**Comment by overmike** [comment]
Thanks BrianBland

I did make a mistake on checking access log of the token auth service. and now I find that the token auth request include two scopes(from and to) in the query parameters. So the issue (1) is the problem of the token auth service which does recognise multiple scopes query parameters

**Comment by rojer** [comment]
can someone test `cesanta/docker_auth:scopes` and see if it fixes the issue?

**Comment by thaJeztah** [comment]
I see https://github.com/cesanta/docker_auth/pull/68 was merged; has anyone been able to test if that resolves this issue?

**Comment by rojer** [comment]
i repro'd the original issue, i think it should be fixed.
new image is now in both :latest and :stable, so everything should work.

**Comment by thaJeztah** [comment]
thanks @rojer let me close this issue
