### ISSUE TITLE
container is not picking namesever from host's resolve.conf

### ISSUE THREAD

**Issue by sunilganatra** [docker/docker#20392]
kernel version :
uname -a
Linux <hostname> 3.10.0-327.4.5.el7.x86_64 #1 SMP Mon Jan 25 22:07:14 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

docker --version
Docker version 1.9.1, build a34a1d5

OS version centos 7

On host following are the entries 
[root@hostname]# cat /etc/resolv.conf
nameserver 10.0.80.11
nameserver 10.0.80.12
options single-request

On container it is not picking entries of host's /etc/resolv.conf
[root@test-contaiiner /]
nameserver 172.17.0.1
options single-request

As per documentation, if -dns option is not used it should resolve nameserver from host.
Please help to resolve this issue.

Thanks in advance

**Comment by sunilganatra** [comment]
docker version: Docker version 1.9.1, build a34a1d5
docker info: Containers: 7
Images: 128
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-8:3-2154104711-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 32.21 GB
 Backing Filesystem:
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 24.88 GB
 Data Space Total: 536.9 GB
 Data Space Available: 512 GB
 Metadata Space Used: 23.15 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.124 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-327.4.5.el7.x86_64
Operating System: CentOS Linux 7 (Core)
ID: JOOA:IOXR:D2CV:SM5Q:JMSH:VHUY:SNSV:3JCH:Z4NO:5WQJ:HHXC:H652
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled


Provide additional environment details (AWS, VirtualBox, physical, etc.):

List the steps to reproduce the issue:
1. create container without using docker run -dns option

Describe the results you received:
On host following are the entries
[root@hostname]# cat /etc/resolv.conf
nameserver 10.0.80.11
nameserver 10.0.80.12
options single-request

On container it is not picking entries of host's /etc/resolv.conf
[root@test-contaiiner /]
nameserver 172.17.0.1
options single-request

Describe the results you expected:

content of /etc/resolv.conf should be same on container and host.

**Comment by mavenugo** [comment]
@sunilganatra Can you pls check all the configuration params passed to the docker daemon ? If there is a `--dns` option passed to the daemon, it will also have an impact on the container's DNS resolution.

**Comment by sunilganatra** [comment]
Here is my docker daemon process 
ps -elf | grep docker
4 S root     14422     1  0  80   0 - 98334 ep_pol Jan11 ?        00:09:29 /usr/bin/docker daemon -H fd:// --exec-opt native.cgroupdriver=cgroupfs --insecure-registry docker-repo:5000 --default-ulimit nofile=65536:65536 --icc=false --storage-opt dm.basesize=30G

**Comment by sunilganatra** [comment]
closing issue since it reproducible, with only weave containers.
