### ISSUE TITLE
Different ImageID for same content in Docker 1.10

### ISSUE THREAD

**Issue by mikehaertl** [docker/docker#20399]
The release notes in docker 1.10 claim, that with the new content based ImageIDs images with the same content will get the same ID. 

> Content addressable image IDs: Image IDs now represent the content that is inside an image, in a similar way to how Git commit hashes represent the content inside commits. This means you can guarantee that the content you’re running is what you expect by just specifying that image’s ID.

But that's not what I found.

```
$ cat Dockerfile 
FROM debian:wheezy
COPY Dockerfile /

$ docker build -t test1 .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM debian:wheezy
wheezy: Pulling from library/debian
604d05dfd165: Pull complete 
a3ed95caeb02: Pull complete 
Digest: sha256:476ea5d2cdef80b3f1cf8f5122bc01ca706dac7f7e153a45f7fc15c7bee624c2
Status: Downloaded newer image for debian:wheezy
 ---> 62c828823e40
Step 2 : COPY Dockerfile /
 ---> ae9273c9916b
Removing intermediate container fa21a2bfe68d
Successfully built ae9273c9916b

$ docker build --no-cache -t test2 .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM debian:wheezy
 ---> 62c828823e40
Step 2 : COPY Dockerfile /
 ---> a5ac2b992c07
Removing intermediate container 787954a0d014
Successfully built a5ac2b992c07
```

So even if the content of the images should be the same, I end up with different IDs `a5ac2b992c07` and `ae9273c9916b`.

**Comment by tonistiigi** [comment]
Content addressability on its own does not mean reproducible builds. There are many timestamps created in the image configuration during build what make the configuration different and therefore the image ID different.

If the actual files do not change then the layers of those builds should be still shared. Atm there isn't a way to check this through the API, but you can do it by comparing layers array in the `/var/lib/docker/image/<driver>/imagedb/content/sha256/<id>` files.

**Comment by mikehaertl** [comment]
Ok, that makes sense.

> Atm there isn't a way to check this through the API, but you can do it by comparing layers array in the /var/lib/docker/image/<driver>/imagedb/content/sha256/<id> files

The problem I have here is, that those new hash IDs are hidden from us. At least I couldn't find a way to see them.

Best example is, when you create an automated build on docker hub and then download the image. You'll see `<missing>` all over the place instead of layer IDs. So it's impossible to verify, whether some layers are reused or not. For example I had a couple of automated builds which should ideally share many lower layers in their builds (which was not the case before 1.10 on docker hub). Right now I have no way to verify if they do or not.

So why is this ID hidden? Would it make sense to create a feature request for this to make this visible?

**Comment by tonistiigi** [comment]
@mikehaertl I opened #20451 . Note that `<missing>` does not mean that the layer ID is missing. Layer does not have a strict reference to history item(dockerfile command). `<missing>` means that you don't have the parent image that was created by the dockerfile command shown in `docker history`, meaning the image was not locally built.

**Comment by mikehaertl** [comment]
@tonistiigi Ok, thanks. But honestly, I still don't quite understand the reason for these `<missing>` layers. How can there be a history item without knowing the according layer? To get the final image, doesn't docker always need all the parent layers down to the root layer? Why does it matter whether the image was built locally? Doesn't all the layers have to reside somewhere in a directory in `/var/lib/docker/...`?

It's maybe not the right place to discuss this. But I couldn't really find this documented somewhere, so if you can point me to some docs, that would be helpful. Things where much clearer with the old Layer IDs and IMO are less transparent right now. But maybe things become clearer to me with implementation of #20451. I'll close this for now, as there's nothing to do then.

**Comment by tonistiigi** [comment]
Pre `v1.10` there was no concept of layers or the other way to think about it is that every image only had one layer. You built a chain of images and you pushed and pulled a chain. All these images in the chain had their own config.

Now there is a concept of a layer that is a content addressable filesystem diff. Every image configuration has an array of layer references that make up the root filesystem of the image and no image requires anything from its parent to run. Push and pull only move a single image, the parent images are only generated for a local build to use for the cache.

If you build an image with the Dockerfile, every command adds a history item into the image configuration. This stores to command so you can see it in `docker history`. As this is part of image configuration it also moves with push/pull and is included in the checksum verification.

Here are some examples of content addressable configs: https://gist.github.com/tonistiigi/6447977af6a5c38bbed8

**Comment by mikehaertl** [comment]
@tonistiigi Hmm, thanks, but now I'm even more confused. Maybe because when you talk about *layer* and *image* you mean something else than I do:

How I understand the model from pre 1.10: An image is composed of layers, each layer has a parent layer and the layer content is stored in a directory somewhere in '/var/lib/docker` with the layer ID as directory name. And a layer relates to a command in a Dockerfile. When starting a container from an image, all layers are stacked upon each other. I can also start a container from an arbitrary layer in between.

> Pre v1.10 there was no concept of layers

Given what I said above that's already where my confusion starts.

> You built a chain of images and you pushed and pulled a chain

I guess these are the layers that I described above. And the chain is the path from the top layer following the parents down to the root layer?

> Now there is a concept of a layer that is a content addressable filesystem diff. Every image configuration has an array of layer references that make up the root filesystem of the image and no image requires anything from its parent to run.

OK, here you lost me. I don't understand how this fits into the "chain of parents" picture.

Again: I don't want to abuse github issues to explain basic concepts. But I think having these concepts explained somewhere - maybe with examples pre and post 1.10 - would be very helpful and make docker more transparent. Worth another issue?

**Comment by tonistiigi** [comment]
@mikehaertl I understand that this is easy to mix up. Let's try once more.

Terms in v1.10: (the terms really have not changed in implementation but previously our docs probably simplified things).
- Layer is a filesystem diff. Bunch of files that when stacked on top of each other make up a root filesystem. Layers are managed by graphdrivers, they don't know anything about images.
- Image is something you can run and that shows up in `docker images -a`. Needs to have a configuration object. When container starts it needs some kind of way to generate a root filesystem from image info. On build every Dockerfile command creates a new image.

Busybox in 1.9.1

```
» docker images -a
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
busybox             latest              65e4158d9625        3 days ago          1.114 MB
<none>              <none>              5506dda26018        3 days ago          1.114 MB
```

objects:
```
Image1: id=5506dda26018 layer1: id=5506dda26018 Image1.parent=null
Image2: id=65e4158d9625 layer2: id=65e4158d9625 Image1.parent=5506dda26018
```

When container starts with busybox it takes the config from image2, for root filesystem you walk the parent chain and stack the layers that match image IDs.

Busybox in 1.10.0

```
» docker images -a                                                                 
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
busybox             latest              3240943c9ea3        3 days ago          1.114 MB
```

```
» cat image/overlay/imagedb/content/sha256/3240943c9ea3f72db51bea0a2428e83f3c5fa1312e19af017d026f9bcf70f84b | jq .rootfs
{
  "type": "layers",
  "diff_ids": [
    "sha256:16a7ebd378002f1261dfb5e21cc22d9473aaac7e06a1cd4ff4e26cfd75432e8f",
    "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef"
  ]
}
```

There is a single image that doesn't have a parent(this is the pull case). Its configuration lists all the layers the rootfs contains. These IDs do not match image IDs, but are the checksums of the filesystem diffs.

**Comment by mikehaertl** [comment]
@tonistiigi Thanks, now I understand.

But this also has the limitation, that unlike < 1.10 you now can no longer start a container from any "intermediate" layer, because there's no longer an image for that layer as it was in 1.10, right?

**Comment by duglin** [comment]
@tonistiigi it might help if you could also explain how layers (and images) work w.r.t. sharing. For example, if you build an image (from a Dockerfile that has FROM ubuntu), and then modify just the last Dockerfile command the cache is still used and (I assume) some sharing of layers will happen between both images.  When pushed to DockerHub will each image have its own copy of the shared layers? Or are they just pushed once and referenced from each image? Same question for the base Ubuntu image.  Also, when I look at the metadata I do see a "Parent" field with a value - how is that used?

**Comment by mikehaertl** [comment]
> When pushed to DockerHub will each image have its own copy of the shared layers? Or are they just pushed once and referenced from each image? 

Quote from  https://github.com/docker/docker-registry/issues/1064

> The new content addressable storage feature in Docker 1.10 relates to how a Docker daemon storages images locally.

> There is a different feature in 1.10 called cross-repository push that addresses the use case you're describing. It allows the engine to prove to a registry that it has access to layers in a different repository. This allows it to skip pushing redundant copies of that layer.

> This feature requires registry-side support, which is available in the brand new Registry 2.3. Docker Hub isn't running this new version quite yet, but once they are, pushing custom images to Hub won't require repushing base layers.

**Comment by kiwenlau** [comment]
I understand that image and layer are different things since docker 1.1.0 

We can get all image id using:

```
sudo docker images -a
```

Is there any way to get the layer checksums of all layers of all images in a Docker host?

**Comment by tonistiigi** [comment]
@kiwenlau You can get the layer checksums for an individual image with `docker inspect`. Combine that with xargs if you need a single command.

**Comment by kiwenlau** [comment]
Thx. However, can I get all layer checksum of all images instead an individual image?

**Comment by tonistiigi** [comment]
@kiwenlau 
```
docker images -qa | xargs docker inspect --format "{{range .RootFS.Layers}}{{.}}
{{end}}" | sort -u
```

**Comment by kiwenlau** [comment]
Great! Thank you @tonistiigi

**Comment by masaeedu** [comment]
@tonistiigi Is there a way to "pull" a Dockerfile+context without necessarily building it? If I already have a registry where someone else has built and pushed the content, can I just attempt to pull the built image from there before being forced to build it locally?

I was originally under the same impression as the OP, i.e. that the image identifiers would be in a 1-1 correspondence with the context + lines of Dockerfile they were built from.

**Comment by tonistiigi** [comment]
The Dockerfile and build context are not built into the image. Only if files are copied into an image during build do they appear inside the image. In the case of some simple single stage Dockerfiles, the commands can potentially be reverse engineered based on the history array in the image.

**Comment by masaeedu** [comment]
@tonistiigi Thanks for the quick response. Is there some docker command (or sequence of commands) that I can use to get an immutable hash of everything docker considers to be part of the context?

**Comment by tonistiigi** [comment]
@masaeedu I don't think I understand the question. You mean during build time, the hash to check if files in build context have been changed? If yes, then this is done per-command, not per-context and there is no way to see it without building. It would be visible in the history record for `COPY .` command after build in non-buildkit builders.

**Comment by masaeedu** [comment]
@tonistiigi Sorry, I'll try to clarify. My use case is the following: given some git repo containing a `Dockerfile` and a `.dockerignore` file, I want to determine for each step in the Dockerfile whether the CI system has already built a "functionally equivalent" layer to what my local Docker host would build. Two layers are "functionally equivalent" if all of the inputs used to build them (in terms of build context, Dockerfile steps and ARGs) are identical.

The actual content of two functionally equivalent layers may differ as a result of side effects during the image build process. For example, files downloaded from a non-fixed URL, package manager updates, filesystem timestamps, etc. Normally we don't care about such side effects, or such side effects are a result of accidental looseness in the Dockerfile, so I actually don't want to rebuild the image if the only differences from what's already available in a CI system is going to be file timestamps and apt cache contents.

Instead, I want to be able to "pull" an image using a hash computed from the context and the Dockerfile steps. If pulling in this way directly is impossible, I'm also ok with computing the appropriate hash manually and tagging each layer with the hash, then pushing it to a shared docker registry. The build step will then compute the hash and attempt to pull from there before being forced to do the build itself.

**Comment by tonistiigi** [comment]
@masaeedu This isn't possible atm with current commands and implementing it would only be possible for single-stage Dockerfiles with the current builder(similar method as I described before). It is supported by https://github.com/moby/buildkit though that supports remote cache in the registry. What you are describing is what is called "minimal" cache export mode that only exports the metadata and layers are from final image. Then when building with cache import it can detect based on this metadata if cache is still valid (or partially valid) and pull in the valid parts directly.

If you just want to associate state of files with a specific image you can just tag the image with the git commit(or your own hash). This wouldn't be validated by Docker then in any way though and you can't match individual layers.

**Comment by alobaidan** [comment]
Hi,  when I run docker history image 
I got information for all layer in the image. Is there anyway to run command to get only a specific layer in the image.

**Comment by alobaidan** [comment]
@tonistiigi could you tell me if there is anyway to make ( docker history image ID) provide information for only one layer not all layers. For example , according to layer ID.
