### ISSUE TITLE
Docker yum repos are kind of busted.

### ISSUE THREAD

**Issue by flyinprogrammer** [docker/docker#20404]
We use Artifactory's remote yum repo feature. It scrapes repo html and proxies the available packages - saving you bandwidth!

Unfortunately, the html being generated for files that exist in the repo seem to be broken:

![screenshot](https://www.evernote.com/shard/s9/sh/4eb95be2-e109-4fb4-9fa8-2064be6ae697/6ccf4ecc7d2d2e00/res/900ffbf6-204b-461f-a923-e439fbc05b07/skitch.png)

http://yum.dockerproject.org/repo/main/centos/7/Packages/

And that makes the parsing scraper sad, which means none of those packages show up in my proxy.

As for why artifactory is choosing to scrape html instead of use the 'repodata' which must always be correct, I could not tell you. but it'd be rad if this was fixed.

**Comment by thaJeztah** [comment]
Thanks for reporting; this is already being worked on in https://github.com/docker/docker/pull/20375; due to the longer names, the temptation broke, resulting in this

**Comment by thaJeztah** [comment]
Although scraping the HTML feels a bit brittle
