### ISSUE TITLE
get.docker.com install script does not start Docker engine on CentOS 7.1

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/docker#20409]
` curl https://get.docker.com | sh` command successfully installs docker engine however after the script is executed, the docker daemon is not running on CentOS 7.1

Repro steps:

1. create a CentOS 7.1 VM
2. `sudo -s` to be root
3. `curl -sSL https://get.docker.com/ | sh` (succeeds)
4.  `docker ps` (does not work)

### Output

```
[root@vm1 alp]# curl -sSL https://get.docker.com/ | sh
+ sh -c 'sleep 3; yum -y -q install docker-engine'
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
warning: /var/cache/yum/x86_64/7/docker-main-repo/packages/docker-engine-selinux-1.10.1-1.el7.centos.noarch.rpm: Header V4 RSA/SHA512 Signature, key ID 2c52609d: NOKEY
Public key for docker-engine-selinux-1.10.1-1.el7.centos.noarch.rpm is not installed
Importing GPG key 0x2C52609D:
 Userid     : "Docker Release Tool (releasedocker) <docker@docker.com>"
 Fingerprint: 5811 8e89 f3a9 1289 7c07 0adb f762 2157 2c52 609d
 From       : https://yum.dockerproject.org/gpg

If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker your-user

Remember that you will have to log out and back in for this to take effect!


[root@vm1 alp]# docker ps
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

[root@vm1 alp]# ps aux | grep docker
root      2509  0.0  0.0 112640   964 pts/0    S+   19:33   0:00 grep --color=auto docker
```

### Versions
```
[root@vm1 alp]# docker version
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:18:46 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

[root@vm1 alp]# cat /etc/redhat-release
CentOS Linux release 7.1.1503 (Core)

[root@vm1 alp]# uname -a
Linux vm1 3.10.0-229.7.2.el7.x86_64 #1 SMP Tue Jun 23 22:06:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ahmetalpbalkan** [comment]
@thaJeztah do you remember where that discussion was? I'd love to see it. I'm not really familiar with `yum` myself but it appears like there has been a breaking change in the script.

**Comment by thaJeztah** [comment]
@ahmetalpbalkan don't remember which issue that discussion was on, but the first mention of the install script in the documentation for CentOS already mentions that the service has to be started after installation; https://github.com/docker/docker/blob/v1.8.0/docs/installation/centos.md#install-with-the-script

**Comment by thaJeztah** [comment]
@ahmetalpbalkan for `yum` in general, for example try installing `httpd` with yum, and you'll see that it's not started after installation.

For `apt`, on the other hand, it's standard practice to start the service after installation

**Comment by ahmetalpbalkan** [comment]
@thaJeztah I see, it appears to be right thing to do on CentOS. :-) However it is breaking the code/scripts relying on the prior behavior. I guess we have to fix that downstream. I'll dig more into commit history to see when it changed. Thanks.

**Comment by thaJeztah** [comment]
@ahmetalpbalkan if you know exactly which platform you're targeting, I'd recommend to not use the install script as it's really on a "best effort base" trying to detect the distribution/version. If possible, I'd implement the steps described in the "manual" procedure of the installation guide, and install using yum/dnf directly.

**Comment by ahmetalpbalkan** [comment]
@thaJeztah I am targeting many versions of many distros (ubuntu, debian, centos, rhel, coreos...) using the same script in the downstream, so I intend to keep using get.docker.com script as long as I can. :-)
