### ISSUE TITLE
Consider using the new Issue and PR templates

### ISSUE THREAD

**Issue by jake-low** [docker/docker#20420]
GitHub just introduced templates for new issues and PRs. Read more [here](https://github.com/blog/2111-issue-and-pull-request-templates).

This could be a great way to remind folks to include `docker info` and `docker version` in their bug reports, or to add a `Signed-off-by` to their commits. @GordonTheTurtle already reminds people of these sorts of things, but it might help to have a reminder _before_ you hit the Submit button too.

I'm not well-versed enough in this project's practices to write these guidelines, but perhaps one of the maintainers could take a whack at it?

**Comment by tianon** [comment]
Thanks to @vbatts, we've had https://github.com/docker/docker/blob/776c5ee299b614360cdbcc392a36dd8d15f385a0/contrib/report-issue.sh for a while now -- perhaps worth just updating/moving that template over?

**Comment by vbatts** [comment]
Hahaha yes! 😀

**Comment by thaJeztah** [comment]
There's already a PR open https://github.com/docker/docker/pull/20416, but if it's not signed off, I'll open a follow up

**Comment by jake-low** [comment]
Ah, my mistake - I looked for duplicate issues open but I didn't check for PRs.

For what it's worth, I don't know if this is a good feature to leverage -- those who triage incoming issues probably have a better sense. Is there a quality problem with issues? Will this feature alleviate it? I don't know. Just thought it merited consideration, and maybe a test-drive.

**Comment by thaJeztah** [comment]
@jake-low we currently have a bot (@GordonTheTurtle) leaving comments if it detects that certain information is missing (docker version, docker info); so we're already "partly" covered, but unfortunately there's still many people reporting issues as *"I run `docker build .` and my Dockerfile doesn't work on this computer, but it does on another one"*. So anything that may help reducing those, could be welcome
