### ISSUE TITLE
Docker keep restarting: An error occurred trying to connect

### ISSUE THREAD

**Issue by AJNOURI** [docker/docker#20429]
## BUG REPORT INFORMATION
**docker version:**

> Client:
>  Version:      1.10.1
>  API version:  1.22
>  Go version:   go1.5.3
>  Git commit:   9e83765
>  Built:        Thu Feb 11 19:27:08 2016
>  OS/Arch:      linux/amd64
> An error occurred trying to connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.22/version: read unix @->/var/run/docker.sock: read: connection reset by peer

**docker info:**

> Cannot connect to the Docker daemon. Is the docker daemon running on this host?

**Physical Environment**

> Distributor ID:	Ubuntu
> Description:	Ubuntu 14.04.4 LTS
> Release:	14.04
> Codename:	trusty
> Linux gns3-iouvm 3.13.0-75-generic #119-Ubuntu SMP Mon Jan 11 13:49:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Describe the results you received:**
Any docker command gives the following error

http://%2Fvar%2Frun%2Fdocker.sock/v1.22/containers/json: read unix @->/var/run/docker.sock: read: connection reset by peer

**Describe the results you expected:**
None of docker command works.

**Provide additional info you think is important:**

_sudo  service docker restart_

> docker stop/waiting
> docker start/running, process 6195

Discovered that Docker keeps restarting indefinitely.

_watch --interval=1 tail -n 10 syslog_

> ajn:/var/log$ tail -n 10 syslog
> Feb 18 06:51:05 gns3-iouvm kernel: [47204.215335] init: docker main process (23439) terminated with status 1
> Feb 18 06:51:05 gns3-iouvm kernel: [47204.215350] init: docker main process ended, respawning
> Feb 18 06:51:06 gns3-iouvm kernel: [47204.735716] init: docker main process (23515) terminated with status 1
> Feb 18 06:51:06 gns3-iouvm kernel: [47204.735732] init: docker main process ended, respawning
> Feb 18 06:51:06 gns3-iouvm kernel: [47205.271573] init: docker main process (23591) terminated with status 1
> Feb 18 06:51:06 gns3-iouvm kernel: [47205.271587] init: docker main process ended, respawning
> Feb 18 06:51:07 gns3-iouvm kernel: [47205.796473] init: docker main process (23668) terminated with status 1
> Feb 18 06:51:07 gns3-iouvm kernel: [47205.796489] init: docker main process ended, respawning
> Feb 18 06:51:07 gns3-iouvm kernel: [47206.312582] init: docker main process (23745) terminated with status 1
> Feb 18 06:51:07 gns3-iouvm kernel: [47206.312597] init: docker main process ended, respawning
> ...

This goes indefinitly

_while true; do pgrep docker; sleep 1; done_

> 9879
> 9957
> 10112
> 10269
> 10425
> 10579
> 10735
> ...
> 12280
> 12435
> 12590
> 12746
> 12906
> 13087
> ^C

Removing docker with --purge and reinstalling didn't solve the issue.

----------END REPORT ---------

#ENEEDMOREINFO

**Comment by HackToday** [comment]
@AJNOURI  How did you install docker on Ubuntu?

And also Could you manual start docker with

```
docker daemon -D
```
and append details for that

**Comment by AJNOURI** [comment]
I am using Docker for quite long time now. Back then, I followed Ubuntu section of the installation:
https://docs.docker.com/engine/installation/linux/ubuntulinux/

**sudo docker daemon -D**

> DEBU[0000] docker group found. gid: 135                 
> DEBU[0000] Server created for HTTP on unix (/var/run/docker.sock) 
> DEBU[0000] Using default logging driver json-file       
> INFO[0000] [graphdriver] using prior storage driver "aufs" 
> DEBU[0000] Using graph driver aufs                      
> INFO[0000] Graph migration to content-addressability took 0.00 seconds 
> DEBU[0000] Option DefaultDriver: bridge                 
> DEBU[0000] Option DefaultNetwork: bridge                
> INFO[0000] Firewalld running: false                     
> DEBU[0000] /sbin/iptables, [--wait -t nat -D PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
> DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER] 
> DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL -j DOCKER] 
> DEBU[0000] /sbin/iptables, [--wait -t nat -D PREROUTING] 
> DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT]    
> DEBU[0000] /sbin/iptables, [--wait -t nat -F DOCKER]    
> DEBU[0000] /sbin/iptables, [--wait -t nat -X DOCKER]    
> DEBU[0000] /sbin/iptables, [--wait -t filter -F DOCKER] 
> DEBU[0000] /sbin/iptables, [--wait -t filter -X DOCKER] 
> DEBU[0000] /sbin/iptables, [--wait -t filter -F DOCKER-ISOLATION] 
> DEBU[0000] /sbin/iptables, [--wait -t filter -X DOCKER-ISOLATION] 
> DEBU[0000] /sbin/iptables, [--wait -t nat -n -L DOCKER] 
> DEBU[0000] /sbin/iptables, [--wait -t nat -N DOCKER]    
> DEBU[0000] /sbin/iptables, [--wait -t filter -n -L DOCKER] 
> DEBU[0000] /sbin/iptables, [--wait -t filter -n -L DOCKER-ISOLATION] 
> DEBU[0000] /sbin/iptables, [--wait -t filter -C DOCKER-ISOLATION -j RETURN] 
> DEBU[0000] /sbin/iptables, [--wait -I DOCKER-ISOLATION -j RETURN] 
> DEBU[0000] /sbin/iptables, [--wait -t nat -C POSTROUTING -s 172.18.0.0/16 ! -o br-a557c39d5bbf -j MASQUERADE] 
> DEBU[0000] /sbin/iptables, [--wait -t nat -C DOCKER -i br-a557c39d5bbf -j RETURN] 
> DEBU[0000] /sbin/iptables, [--wait -t nat -I DOCKER -i br-a557c39d5bbf -j RETURN] 
> DEBU[0000] /sbin/iptables, [--wait -D FORWARD -i br-a557c39d5bbf -o br-a557c39d5bbf -j DROP] 
> DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -i br-a557c39d5bbf -o br-a557c39d5bbf -j ACCEPT] 
> DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -i br-a557c39d5bbf ! -o br-a557c39d5bbf -j ACCEPT] 
> DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -o br-a557c39d5bbf -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT] 
> DEBU[0000] /sbin/iptables, [--wait -t nat -C PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
> DEBU[0000] /sbin/iptables, [--wait -t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
> DEBU[0000] /sbin/iptables, [--wait -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8] 
> DEBU[0000] /sbin/iptables, [--wait -t nat -A OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8] 
> DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -o br-a557c39d5bbf -j DOCKER] 
> DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -o br-a557c39d5bbf -j DOCKER] 
> DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -j DOCKER-ISOLATION] 
> DEBU[0000] /sbin/iptables, [--wait -D FORWARD -j DOCKER-ISOLATION] 
> DEBU[0000] /sbin/iptables, [--wait -I FORWARD -j DOCKER-ISOLATION] 
> DEBU[0000] Registering ipam driver: "default"           
> DEBU[0000] Cleaning up old shm/mqueue mounts: start.    
> FATA[0000] Error starting daemon: Error initializing network controller: could not delete the default bridge network: network bridge has active endpoints 
> ajn:~$

**Comment by AJNOURI** [comment]
The resulting error of **sudo docker daemon -D** 



> Error starting daemon: Error initializing network controller: could not delete the default bridge network: network bridge has active endpoints



guided me to another issue #18283 
Where the problem is solved by

1. delete **/var/lib/docker/network** 
2. _sudo service docker restart_

Thanks @HackToday

**Comment by HackToday** [comment]
Yes, That's what the old issue discussed before

**Comment by emegodoyr** [comment]
i'm have the same error, the log command ```sudo docker daemon -D``` is:

DEBU[0000] docker group found. gid: 999                 
DEBU[0000] Listener created for HTTP on unix (/var/run/docker.sock) 
INFO[0000] libcontainerd: new containerd process, pid: 26304 
DEBU[0000] libcontainerd: containerd connection state change: TRANSIENT_FAILURE 
WARN[0000] containerd: low RLIMIT_NOFILE changing to max  current=1024 max=4096
DEBU[0000] containerd: read past events                  count=0
DEBU[0000] containerd: supervisor running                cpus=4 memory=3953 runtime=docker-runc runtimeArgs=[] stateDir=/var/run/docker/libcontainerd/containerd
DEBU[0000] containerd: grpc api on /var/run/docker/libcontainerd/docker-containerd.sock 
DEBU[0001] Using default logging driver json-file       
DEBU[0001] Golang's threads limit set to 56700          
ERRO[0001] [graphdriver] prior storage driver "aufs" failed: driver not supported 
DEBU[0001] Cleaning up old mountid : start.             
FATA[0001] Error starting daemon: error initializing graphdriver: driver not supported

before working properly

delete the network folder, but the error persists

**Comment by thaJeztah** [comment]
@emegodoyr based on this error;

```
prior storage driver "aufs" failed: driver not supported 
```

I suspect you upgraded your kernel, but did not update the linux-image-extra package (which is needed for aufs to work.

Instructions for installing it for your current kernel version can be found here;
https://docs.docker.com/engine/installation/linux/ubuntulinux/#/prerequisites-by-ubuntu-version

**Comment by emegodoyr** [comment]
I found a solution , try ``` rm -rf /var/lib/docker/aufs``` and properly worked, thanks anyway ...

**Comment by thaJeztah** [comment]
@emegodoyr doing so removes all your containers and images; also, you may want to check which storage driver you're now running on; if you switch to device mapper now (which is next on the list of drivers), your performance may really suffer

**Comment by rwdavis513** [comment]
I also had the same issue described above with the docker daemon continuously restarting. After digging around a bit, I discovered that openvpn was still running on my computer (by mistake). Stopping openvpn did the trick for me. Just wanted to share in case anyone else ran into this issue.

`sudo service openvpn stop`
