### ISSUE TITLE
docker info didn't show overlay network plugin

### ISSUE THREAD

**Issue by Fangfenghua** [docker/docker#20421]
**docker -v**
[root@mesos-master ~]# docker -v
Docker version 1.10.1, build 9e83765
[root@mesos-master ~]# 

**docker info**
[root@mesos-master ~]# docker info
Containers: 29
 Running: 0
 Paused: 0
 Stopped: 29
Images: 106
Server Version: 1.10.1
Storage Driver: devicemapper
 Pool Name: docker-253:0-134615493-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 6.763 GB
 Data Space Total: 107.4 GB
 Data Space Available: 33.82 GB
 Metadata Space Used: 8.991 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.138 GB
 Udev Sync Supported: false
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82 (2013-10-04)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.4.5.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.636 GiB
Name: mesos-master
ID: L4Q4:TWQX:IEID:J26G:AIBW:4OCQ:HYQQ:2V4M:4YGE:WPES:O2EH:6IFM
Debug mode (server): true
 File Descriptors: 15
 Goroutines: 37
 System Time: 2016-02-17T21:22:48.23307424-05:00
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/bin/docker
 Docker Root Dir: /var/lib/docker
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Cluster store: zk://192.168.2.64:2181
Cluster advertise: 10.37.129.16:8888
[root@mesos-master ~]# 

[root@mesos-master ~]# ps -ef|grep docker
root      2255     1  0 21:19 ?        00:00:01 /usr/bin/docker daemon -H fd:// -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock -D --cluster-advertise=eth1:8888 --cluster-store=zk://192.168.2.64:2181
root      2511  2236  0 21:23 pts/0    00:00:00 grep --color=auto docker
[root@mesos-master ~]#

**Comment by HackToday** [comment]
hi @Fangfenghua  did you enable overly network plugin? How did you enable it ?

**Comment by Fangfenghua** [comment]
I config according https://docs.docker.com/engine/userguide/networking/get-started-overlay/.   @HackToday

**Comment by mavenugo** [comment]
@Fangfenghua the `Plugins` section in `docker info` is derived out of existing network created. If you create a network using `overlay` driver, then it will show up here. Can you try it out ? 

`docker network create -d overlay test`. Please check the `docker info` command after successfully creating this network. I think this functionality can be improved.

**Comment by Fangfenghua** [comment]
@mavenugo  tks，now it's work
