### ISSUE TITLE
What are the docs /engine/installation/linux/ubuntulinux/ installing exactly?

### ISSUE THREAD

**Issue by srcspider** [docker/docker#20439]
Had to install docker recently. Google-ing actually gave this as first result: 

https://docs.docker.com/engine/installation/linux/ubuntulinux/

This looks like the instalation instructions for ubuntu... but it's actually not. It's several pages of nonsense that errors out with dependency errors on everything (very old instructions?). 

The real installation instructions for ubuntu are just...

    curl -fsSL https://get.docker.com/ | sh

As mentioned in https://docs.docker.com/linux/step_one/

I don't know what those instructions are trying to install (I assume "engine" there is referring to something else entirely) but they're not helpful, especially not as the first result in a search for "install docker".

Please add some warning on top of that page that if you're just trying to install docker on your system all you need is that one curl / sh command. I had installed docker before so remembered the instructions weren't this *dense* (and broken) after a few errors in that page but I'm sure if someone is new they might waste a lot of time with that page.

Incidentally this was second result https://docs.docker.com/engine/installation/ and the correct one was the 3rd result. However in order the titles for the pages are: 

 - Installation on Ubuntu - Docker
 - Install - Docker
 - Install Docker

So if there's some difference, it would help if it was better illustrated in the title

**Comment by thaJeztah** [comment]
The instructions on that page are actually the same steps that the script at get.docker.com does; which dependency errors did you run into?

**Comment by HackToday** [comment]
https://docs.docker.com/engine/installation/linux/ubuntulinux/
is details steps what to do install docker step by step,  To me, it is clear and easy to install

**Comment by LK4D4** [comment]
Ok, I'm closing this because seems like instructions are decent. Feel free to open new issue!
