### ISSUE TITLE
Wrong list on docker ps filter before and since

### ISSUE THREAD

**Issue by wenchma** [docker/docker#20431]
Tests results:

    ubuntu@docker:~$ docker ps -a
	CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                     PORTS               NAMES
	f89b784bd075        busybox             "top"               3 hours ago         Up 3 hours                                     sharp_sammet
	c19371b83b8c        busybox             "top"               3 hours ago         Exited (143) 3 hours ago                       adoring_leakey
	076cdb81fd00        busybox             "top"               3 hours ago         Up 3 hours                                     jolly_brown
	740e1b1487dd        training/webapp     "python app.py"     4 weeks ago         Exited (137) 3 hours ago                       web
	ubuntu@docker:~$ docker ps -f since=adoring_leakey
	CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
	f89b784bd075        busybox             "top"               3 hours ago         Up 3 hours                              sharp_sammet
	076cdb81fd00        busybox             "top"               3 hours ago         Up 3 hours                              jolly_brown
	ubuntu@docker:~$ docker ps -f before=adoring_leakey
	CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

`docker version`

    $ docker version
	Client:
	 Version:      1.10.1
	 API version:  1.22
	 Go version:   go1.5.3
	 Git commit:   9e83765
	 Built:        Thu Feb 11 19:27:08 2016
	 OS/Arch:      linux/amd64

	Server:
	 Version:      1.10.1
	 API version:  1.22
	 Go version:   go1.5.3
	 Git commit:   9e83765
	 Built:        Thu Feb 11 19:27:08 2016
	 OS/Arch:      linux/amd64

`docker info`

    Containers: 4
	 Running: 2
	 Paused: 0
	 Stopped: 2
	Images: 156
	Server Version: 1.10.1
	Storage Driver: aufs
	 Root Dir: /var/lib/docker/aufs
	 Backing Filesystem: extfs
	 Dirs: 164
	 Dirperm1 Supported: true
	Execution Driver: native-0.2
	Logging Driver: json-file
	Plugins: 
	 Volume: local
	 Network: null host bridge
	Kernel Version: 4.2.0-22-generic
	Operating System: Ubuntu 14.04.1 LTS
	OSType: linux
	Architecture: x86_64
	CPUs: 4
	Total Memory: 15.67 GiB
	Name: docker
	ID: UT5D:M5ZY:IEXQ:6LCU:YX6J:ZMWM:BLNJ:MTXH:PRHO:ETVF:3FHH:6LC4
	WARNING: No swap limit support

`uname -a`

    Linux docker 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):OpenStack Cloud instance

**Comment by vdemeester** [comment]
@wenchma This is expected, we fixed that in `1.10.1`. Filters should all act the same way, not showing stopped container by default — `since` and `before` filter are no different (and have been changed that way).

To achieve the same behaviour as `--since` or `--before` you need to use `-a` on your `docker ps`.

**Comment by wenchma** [comment]
@vdemeester yes, filters should not show stopped containers,  as above my test: `docker ps -f before=adoring_leakey`  should return `jolly_brown`, but return nothing,  it is also expected result ?

**Comment by wenchma** [comment]
since #20480 is merged, close this issue.

**Comment by wenchma** [comment]
since #20480 is merged, close this issue.
