### ISSUE TITLE
Fix the puzzled character

### ISSUE THREAD

**Issue by huangzhendong** [docker/docker#20440]
In the source code "diff.go" , the discription of the function "CmdDiff" use the character "C" stand for "modified" and in the inplementation of the function use "C" also, it's very informal. Since i am a newer to docker, hope some one can modify it to make the code more clearly.

**Comment by thaJeztah** [comment]
Perhaps is we change the description to `C (changed/modified)` it makes more sense?

**Comment by huangzhendong** [comment]
I really appreciate what you said, but as an official code i think it's very important to be a good example for docs and codes. thank you !
