### ISSUE TITLE
Journald logging does not accept the "tag" or "syslog-tag" options

### ISSUE THREAD

**Issue by matthewdfuller** [docker/docker#20443]
### Info:
* `docker version`: 1.9.1
* Host: CoreOS
* Infrastructure: AWS

### Problem Summary:
Using the journald log driver does not allow the use of tags in the log lines, seemingly contrary to the code comments and docs.

### Steps to Reproduce
1. Run a container with the syslog driver and the tags option:
    
    `docker run --log-driver=syslog --log-opt tag="{{.ImageName}}/{{.Name}}/{{.ID}}" --name ...`
2. Observe the logs using journalctl: `journalctl CONTAINER_NAME=name` and see that the lines are in the format: `image name/name/id log message`
3. Run the same command but using the journald driver:

    `docker run --log-driver=journald --log-opt tag="{{.ImageName}}/{{.Name}}/{{.ID}}" --name ...`
4. Observe error message:

    `Error response from daemon: Cannot start container abc123...: Failed to initialize logging driver: unknown log opt 'tag' for journald log driver`
5. Attempt to use `syslog-tag` instead and observe the same error:

    `docker run --log-driver=journald --log-opt syslog-tag="{{.ImageName}}/{{.Name}}/{{.ID}}" --name ...`
6. Attempt to use a journald equivalent and observe the same error:

    `docker run --log-driver=journald --log-opt journald-tag="{{.ImageName}}/{{.Name}}/{{.ID}}" --name ...`

### More Details
According to the [release notes for version 1.9.0](https://github.com/docker/docker/blob/v1.9.0/CHANGELOG.md#logging), a standard "--tag" option was added to work generically across log drivers. The setup and usage for this is described in [PR #15384](https://github.com/docker/docker/pull/15384). This is specifically related to the fact that the journald logging driver doesn't print the tags in its log lines the same way that syslog and other drivers do. There are a [few issues](https://github.com/docker/docker/issues/16446) referencing the support of labels and custom fields, but they have been closed. Additionally, [according to this comment in the source code](https://github.com/docker/docker/blob/master/daemon/logger/journald/journald.go#L78), journald should accept the `tag` argument.

Essentially, I need to be able to print, using the journald driver, the following line:

`Feb 17 18:53:32 ip-1-2-3-4.ec2.internal docker/containername/container/id [26356]: ::1 - - log line info`

using the built in: `{{.ImageName}}/{{.Name}}/{{.ID}}` tag templates.

**Comment by cpuguy83** [comment]
It looks like tag support for journald was only recently added and will be in 1.11.

Sorry for the inconvenience.

**Comment by cpuguy83** [comment]
Note, this was added in #19564

**Comment by xuqingfeng** [comment]
Still can't write `tag` to `journald`

more info:
- `docker --version`: `Docker version 1.12.3, build 6b644ec`
- `docker run -i --log-driver=journald --log-opt tag="{{.Name}}" --name journald alpine echo toto`
- `journalctl CONTAINER_NAME=journald`: `Dec 15 15:29:51 xx.xx dockerd[17173]: toto`

**Comment by cllovatto** [comment]
The tag is written to the field `CONTAINER_TAG` for each message, not to the message itself.
If you do:
`journalctl CONTAINER_TAG=<tag>`
then you will see all messages for the specified tag.
In a sense it is working as advertized, but I find it odd not seeing anywhere in the output the tag or container name. 

It is specially confusing when we have many containers outputting to journald as we don't see any indication of who's who in the messages, only the dockerd service common to all of them.

This does not happen when using syslog, but in contrast we loose the ability to get logs via docker command line.
I could not find any way using journalctl to output any field associated with the messages, so I could better parse the messages coming from different containers.

Am I missing something?

**Comment by thaJeztah** [comment]
@cllovatto that's how journald works. There's a feature request in the systemd repository that you may be interested in:

You can use the `-o` option to specify the output format (e.g. to print each log entry as JSON);

```bash
$ journalctl -o json CONTAINER_TAG=mysql1
```
```JSON
{ "__CURSOR" : "s=349c8f9893984ef0bbf1231afb11ffd6;i=22f3;b=609e5a3fed2f4bf29a615ac88e229be0;m=433851ab40;t=55b4c5e6d7fe2;x=9a76f6fe9a046b28", "__REALTIME_TIMESTAMP" : "1507758443429858", "__MONOTONIC_TIMESTAMP" : "288707685184", "_BOOT_ID" : "609e5a3fed2f4bf29a615ac88e229be0", "_UID" : "0", "_GID" : "0", "_CAP_EFFECTIVE" : "3fffffffff", "_SYSTEMD_SLICE" : "system.slice", "_MACHINE_ID" : "a920d7234de74739945794b24bc9b558", "_HOSTNAME" : "ubuntu-2gb-ams3-01", "PRIORITY" : "3", "_TRANSPORT" : "journal", "_PID" : "9008", "_COMM" : "dockerd", "_EXE" : "/usr/bin/dockerd", "_CMDLINE" : "/usr/bin/dockerd -H fd://", "_SYSTEMD_CGROUP" : "/system.slice/docker.service", "_SYSTEMD_UNIT" : "docker.service", "MESSAGE" : "error: database is uninitialized and password option is not specified ", "CONTAINER_TAG" : "mysql1", "CONTAINER_ID" : "141fbe360a87", "CONTAINER_ID_FULL" : "141fbe360a8789eebfcf20674e16669c761a19906c1756461040f80a2d520335", "CONTAINER_NAME" : "mysql1", "_SOURCE_REALTIME_TIMESTAMP" : "1507758443429361" }
{ "__CURSOR" : "s=349c8f9893984ef0bbf1231afb11ffd6;i=22f4;b=609e5a3fed2f4bf29a615ac88e229be0;m=433851acee;t=55b4c5e6d8190;x=d90bd5ae08837a8c", "__REALTIME_TIMESTAMP" : "1507758443430288", "__MONOTONIC_TIMESTAMP" : "288707685614", "_BOOT_ID" : "609e5a3fed2f4bf29a615ac88e229be0", "_UID" : "0", "_GID" : "0", "_CAP_EFFECTIVE" : "3fffffffff", "_SYSTEMD_SLICE" : "system.slice", "_MACHINE_ID" : "a920d7234de74739945794b24bc9b558", "_HOSTNAME" : "ubuntu-2gb-ams3-01", "PRIORITY" : "3", "_TRANSPORT" : "journal", "_PID" : "9008", "_COMM" : "dockerd", "_EXE" : "/usr/bin/dockerd", "_CMDLINE" : "/usr/bin/dockerd -H fd://", "_SYSTEMD_CGROUP" : "/system.slice/docker.service", "_SYSTEMD_UNIT" : "docker.service", "CONTAINER_TAG" : "mysql1", "CONTAINER_ID" : "141fbe360a87", "CONTAINER_ID_FULL" : "141fbe360a8789eebfcf20674e16669c761a19906c1756461040f80a2d520335", "CONTAINER_NAME" : "mysql1", "MESSAGE" : "  You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD", "_SOURCE_REALTIME_TIMESTAMP" : "1507758443430044" }
```

or some other formats:

```bash
$ journalctl -o verbose CONTAINER_TAG=mysql1
-- Logs begin at Sun 2017-10-08 13:35:41 UTC, end at Wed 2017-10-11 21:49:10 UTC. --
Wed 2017-10-11 21:47:23.429361 UTC [s=349c8f9893984ef0bbf1231afb11ffd6;i=22f3;b=609e5a3fed2f4bf29a615ac88e229be0;m=433851ab40;t=55b4c5e6d7fe2;x=9a76f6fe9a046b28]
    _UID=0
    _GID=0
    _CAP_EFFECTIVE=3fffffffff
    _SYSTEMD_SLICE=system.slice
    _BOOT_ID=609e5a3fed2f4bf29a615ac88e229be0
    _MACHINE_ID=a920d7234de74739945794b24bc9b558
    _HOSTNAME=ubuntu-2gb-ams3-01
    PRIORITY=3
    _TRANSPORT=journal
    _PID=9008
    _COMM=dockerd
    _EXE=/usr/bin/dockerd
    _CMDLINE=/usr/bin/dockerd -H fd://
    _SYSTEMD_CGROUP=/system.slice/docker.service
    _SYSTEMD_UNIT=docker.service
    MESSAGE=error: database is uninitialized and password option is not specified
    CONTAINER_TAG=mysql1
    CONTAINER_ID=141fbe360a87
    CONTAINER_ID_FULL=141fbe360a8789eebfcf20674e16669c761a19906c1756461040f80a2d520335
    CONTAINER_NAME=mysql1
    _SOURCE_REALTIME_TIMESTAMP=1507758443429361
Wed 2017-10-11 21:47:23.430044 UTC [s=349c8f9893984ef0bbf1231afb11ffd6;i=22f4;b=609e5a3fed2f4bf29a615ac88e229be0;m=433851acee;t=55b4c5e6d8190;x=d90bd5ae08837a8c]
    _UID=0

$ journalctl -o export CONTAINER_TAG=mysql1
__CURSOR=s=349c8f9893984ef0bbf1231afb11ffd6;i=22f3;b=609e5a3fed2f4bf29a615ac88e229be0;m=433851ab40;t=55b4c5e6d7fe2;x=9a76f6fe9a046b28
__REALTIME_TIMESTAMP=1507758443429858
__MONOTONIC_TIMESTAMP=288707685184
_BOOT_ID=609e5a3fed2f4bf29a615ac88e229be0
_UID=0
_GID=0
_CAP_EFFECTIVE=3fffffffff
_SYSTEMD_SLICE=system.slice
_MACHINE_ID=a920d7234de74739945794b24bc9b558
_HOSTNAME=ubuntu-2gb-ams3-01
PRIORITY=3
_TRANSPORT=journal
_PID=9008
_COMM=dockerd
_EXE=/usr/bin/dockerd
_CMDLINE=/usr/bin/dockerd -H fd://
_SYSTEMD_CGROUP=/system.slice/docker.service
_SYSTEMD_UNIT=docker.service
MESSAGE=error: database is uninitialized and password option is not specified
CONTAINER_TAG=mysql1
CONTAINER_ID=141fbe360a87
CONTAINER_ID_FULL=141fbe360a8789eebfcf20674e16669c761a19906c1756461040f80a2d520335
CONTAINER_NAME=mysql1
_SOURCE_REALTIME_TIMESTAMP=1507758443429361
```

**Comment by dwayne-lee** [comment]
For me the whole reason behind tagging is so that rsyslog can capture these tags and designate which files to place the logs.  I do this with rsyslog templating.  Using journalctl -o json isn't very human readable.  Docker needs to fix this logging issue to provide "yes" answers to the following requirements:

Log-driver   Access to human-readable files?   View logs using “docker logs <container>”?
Syslog                             yes                                                            no
Journald                           no                                                            yes

**Comment by ripcurld0** [comment]
@dwayne-lee do you mind open a ticket for this?
Thanks.
