### ISSUE TITLE
hub.docker.com password reset not working

### ISSUE THREAD

**Issue by localgod** [docker/docker#20445]
BUG REPORT INFORMATION

When I type in my mail at https://hub.docker.com/reset-password/ I receive a mail with a link. 

When I click the link that has the form:
https://hub.docker.com/account/password-reset-confirm/NDQzMjE2/49i-ee4c1576a50fd0b5cab7/
I am however instantly redirected to https://hub.docker.com/

My user name is localgod.

**Comment by rrarunan** [comment]
@localgod thanks for the report. We are working on a fix.

**Comment by rrarunan** [comment]
This is fixed now. @localgod let us know if it works and please close when verified. Thanks!

**Comment by localgod** [comment]
Worked... Thanks
