### ISSUE TITLE
Unable to install docker 1.10.1 on Oracle Enterprise linux

### ISSUE THREAD

**Issue by saxenaks** [docker/docker#20456]
-sh-4.2$ uname -a
Linux <host-name> 4.4.1-1.el7.elrepo.x86_64 #1 SMP Sun Jan 31 16:49:23 EST 2016 x86_64 x86_64 x86_64 GNU/Linux

-sh-4.2$ cat /etc/*release
Oracle Linux Server release 7.1
NAME="Oracle Linux Server"
VERSION="7.1"
ID="ol"
VERSION_ID="7.1"
PRETTY_NAME="Oracle Linux Server 7.1"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:1"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.1
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.1
Red Hat Enterprise Linux Server release 7.1 (Maipo)
Oracle Linux Server release 7.1

sh-4.2$ sudo yum install docker-engine
Loaded plugins: aliases, changelog, kabi, langpacks, tmprepo, verify, versionlock
Loading support for kernel ABI
Resolving Dependencies
--> Running transaction check
---> Package docker-engine.x86_64 0:1.10.1-1.el7 will be installed
--> Processing Dependency: kernel-uek >= 4.1 for package: docker-engine-1.10.1-1.el7.x86_64
--> Finished Dependency Resolution
Error: Package: docker-engine-1.10.1-1.el7.x86_64 (dockerrepo)
           Requires: kernel-uek >= 4.1
           Installed: kernel-uek-3.8.13-55.1.6.el7uek.x86_64 (@anaconda/7.1)
               kernel-uek = 3.8.13-55.1.6.el7uek

Why is this constraint on kernel-uek >= 4.1?

**Comment by elygre** [comment]
I'm seeing the same issue. Upgrading to UEK r4 is a bit of a pain, so it would be good to know if this is a real requirement.

**Comment by thaJeztah** [comment]
I think it's a requirement, also see https://github.com/docker/docker/blob/master/docs/installation/linux/oracle.md#prerequisites

> Docker requires the use of the Unbreakable Enterprise Kernel Release 4 (4.1.12) or higher on Oracle Linux. This kernel supports the Docker btrfs storage engine on both Oracle Linux 6 and 7.


/cc @Djelibeybi (for Oracle)

**Comment by Djelibeybi** [comment]
It's a requirement. We need VxLAN and other bits and pieces which are provided by UEK4 and are not available in previous versions. It also supports the new user namespaces in Docker 1.10.

**Comment by Djelibeybi** [comment]
Note that it's just Oracle Linux. We dropped the "Enterprise" over 5 years ago now. :)

**Comment by thaJeztah** [comment]
Thanks @Djelibeybi!

I'm closing this issue, per the explanation above, thanks for filing this issue @saxenaks !
