### ISSUE TITLE
[proposal] Expose layer IDs for images through the api

### ISSUE THREAD

**Issue by tonistiigi** [docker/docker#20451]
The concept of layers was added in `v1.10` but there is currently no way to ask from the API what layers an image is using. This would make it possible to observe what layers are shared and validate that layers are the same as in registry/load tarball.

Ways to implement this:

1) Add `rootfs` section to the image inspect output. This lists all layer IDs and a baselayer name in windows.

2) Add `docker inspect --raw`. That would show the raw content addressable image config. This has an added benefit that you can verify that sha256 of this config makes up the image ID. Note that not all fields in `docker inspect` are in the raw config(there is no parent, tags etc.).

3) Both 1 and 2?

Asked in:
#17366
#20399
#18727

cc @aaronlehmann @dmcgowan

**Comment by aaronlehmann** [comment]
I think both suggestions are worthwhile.

**Comment by aaronlehmann** [comment]
I would actually suggest this for 1.10.2 (if we release such a version), since there are ongoing problems with tars not matching their content hashes (see #20104). Having an easier way to know what layers an image uses could help us track this down.

**Comment by cpuguy83** [comment]
I don't like `--raw` in 2, but perhaps instead embed the raw config into the inspect output.

**Comment by tianon** [comment]
Does the "raw" metadata you're describing here include bits that would allow us to correlate local images with images on the registry?  For example, right now on 1.10, the only "identification" I can find in common between `docker inspect` on a local image and the same image's manifest fetched from a registry is the ID of the container it was created from, and that's not exactly a great thing for comparing whether two images are the same image. :smile:

Being one of the folks who asked for the ability to access this kind of data, I'm obviously +1 to more data being available. :innocent:

Thanks for filing an issue to discuss this and for looping in the relevant parties! :metal:

**Comment by tianon** [comment]
I would add that I'm with @cpuguy83 though -- what's the rationale for not just including more data in `docker inspect` as-is?

**Comment by tonistiigi** [comment]
@tianon `raw` would return the exact bytes of the image configuration that is in the registry if it's referenced by the schema2 manifest. https://github.com/docker/distribution/pull/1068/files?diff=unified#diff-298c8e761320ff3dde0420467054f000R206 . This includes the layers array and sha256 of those bytes is the image ID.

I have nothing against adding the layers to `docker inspect`. If everyone likes that we can do this first and tackle the other one later. Adding the full config to the docker inspect output may be too confusing because it can be quite big, maybe we include it if you specify a cli option.

**Comment by tianon** [comment]
Ah I see, thanks for the pointer. :smile: :+1:

I'd personally love to see layer data in `docker inspect` as a first step, since that'd still be relatively clean to present to the user.

**Comment by HackToday** [comment]
I like option 1 for clean output with just layerIDs,

**Comment by justone** [comment]
If it's not too much trouble, it would also be nice to have the layerIDs included in the `/images/json?all=1` API as well, for getting all the information in one fetch.
