### ISSUE TITLE
Complete network options information table

### ISSUE THREAD

**Issue by calavera** [docker/docker#20455]
As a follow up of #17513, we should complete the network options table:

https://github.com/aidanhs/docker/blob/d736a9d2c3758fcc4eac0b62e9c7b128388021c1/docs/reference/commandline/network_create.md#bridge-driver-options

/cc @aidanhs

**Comment by aidanhs** [comment]
Thanks for merging and opening a new issue, I've been a bit busy! I'll see about getting to the doc improvements this weekend.
