### ISSUE TITLE
save | load duplicates shared layers?

### ISSUE THREAD

**Issue by huguesb** [docker/docker#20463]
We have a workflow where I generate images on one host and need to get them onto a VM image.

So far we've been using a transient local registry instance but this is *so very very slow*.

Using `docker save <images...> | ssh docker load` is much faster and avoids the trouble of setting up the temporary registry.

Unfortunately it results in a much larger footprint on the target VM. Once the VM is exported into ova form it weighs about 800MB more with `save | load` than when the images are pulled from a v1 registry.

I've also tried using a v2 registry which makes push much faster but for some reason this has a similar effect on the resulting VM size.

Images are generated on a host with docker 1.10.1 and loaded on a host with docker 1.8.3

Upgrading docker on the target VM is not an option at this time.

**Comment by huguesb** [comment]
docker daemon 1.10.1 w/ aufs (boot2docker 1.10.1 on VirtualBox 5.0.14)
docker client 1.9.1 on OS X El Capitan
Target VM is CoreOS. Version doesn't seem to make much difference (tried both stable w/ docker 1.8.3 and alpha w/ docker 1.10.1, both use overlayfs)

Interestingly the output of `docker save` has roughly the expected size (1.6GB, presumably some overhead from the metadata) and the contents of the tar file do not suggest any duplication, which would suggest it's happening during `docker load`

**Comment by LK4D4** [comment]
@tonistiigi would you mind to take a look? It's probably too late to do anything, though.

**Comment by tonistiigi** [comment]
This is fixed but you have to update both machines. Anything below v1.10 can't identify duplicate layers on load. If the saved images share layers they will appear as duplicates in tar with versions less than v1.12. Load on `v1.10+` would correct the duplication in tar but it will still be inefficient.
