### ISSUE TITLE
20 seconds isn't long enough to consider the warning message.

### ISSUE THREAD

**Issue by fuzzbomb** [docker/docker#20461]
The install script (hack/install.sh) can install apt keys, repositories, and packages in a in a non-interactive way. I don't feel this is reasonable behaviour for a script. Can we improve it to proceed more considerately?

To be fair, you will get a warning message in cases where you system already has another version of docker installed. The script prints 3 paragraphs of text describing the situation, but only gives a window of `sleep 20` seconds before continuing. The advice to terminate the process with ctrl+C is given at the end.

I don't feel 20 seconds is enough time to _read, understand, and consider_ what is going on, for a variety of possible reasons:

- Level of English fluency.
- Level of confidence (installing Docker might be a big step for someone, part of a learning curve).
- Cognitive differences, such as dyslexia.
- Random distractions, such a phone ringing.
- There are _two separate things_ to consider in the time available; a vague "can cause trouble" part, and some "migrate your image store" advice.

After this, `sudo` is invoked. This does not offer much protection, as you may not be asked for a password if you have used sudo quite recently. In such a case, the sudo step is passed non-interactively. Since installing Docker is a system admin task, I think there's a reasonably strong chance that the user may have recently used sudo to carry out some other task. (For example, stopping LAMP services on a developer machine, which they intend to replace with a docker-managed version.)

After that, the script carries on with non-interactive `apt-get install -y`.

I found myself in the situation where I was presented with the warning. Before I had completely digested it (but at least realizing this was a warning which I needed to consider) the 20 seconds were up. The sudo stage didn't ask for a password, and we were headed through an `apt-get update`. I recognized the stream of messages about updating package info, and hit ctrl+C, then tried to asses what had happened. As things turned out, no harm was done, but it did make me panic. I was a bit angry at discovering an apt repository had been added.

I think we could improve this process in the following ways:

- Remove the `sleep 20` window of opportunity, and replace it with an interactive prompt. Require an explicit 'yes' to proceed. This will allow everyone as much time as they need to understand what is happening, and make a decision. It will also add some protection for the users who have recently used `sudo`. (For users who often install docker on various machines, this might be an inconvenience, but hopefully just a minor one.) 
- Add some text to inform the user what to expect IF they proceed, i.e. an apt repo will be added, their current version of docker will be replaced, docker engine will be installed, &c. As it stands, the warning says the script "can cause trouble" but doesn't say what kind of trouble, or what will happen if they proceed. Perhaps this can be customized after checking what state their system is already in.
- One of the situations the user is asked to consider is only relevant if they are upgrading to (or from?) certain versions of Docker. Could we check the current Docker version, and only output this part of the message if it does apply to them. I'm not clear if it applies only once, the first time you upgrade to 1.10, or whether it applies to every incremental upgrade after 1.10.

**Comment by tiborvass** [comment]
@fuzzbomb I'm fine doing an interactive prompt, if we do it before the `apt-get update`. However, if it's run non-interactively, it would install it right away? /cc @tianon

**Comment by tianon** [comment]
It would fail in non-interactive settings if we don't use `-y` (just like it does in a `RUN` line when `-y` is missing).

Honestly, I think we really need to finally just add a nice deprecation warning to the output of this script, and slowly transition it to only doing platform detection in order to point to more specific installation documentation than just directing everyone to https://docs.docker.com/engine/installation/ (although that wouldn't be horrible either IMO).

I'm thinking of something like:
```
This script is officially deprecated in favor of following the (simple)
directions for installing Docker in your host OS; please see
https://docs.docker.com/engine/installation/ for details.
```

Followed by some delay and then what it currently does so that after some point we can cut everyone off and have the script do nothing except print the message.  (We should probably also choose a cutoff date and include it in the message, too.)

**Comment by thaJeztah** [comment]
Looks like nobody is working on this, but feel free to open a PR if you think this is still needed. I'll close this as we don't consider this a high priority
