### ISSUE TITLE
Nice error needed when "-H fd://" is used on non-systemd based systems like Ubuntu 14.04.

### ISSUE THREAD

**Issue by vhosakot** [docker/docker#20468]
Docker's documentation at https://docs.docker.com/engine/reference/commandline/daemon/#daemon-socket-option says that the argument `-H fd://`must be used with `docker daemon` on systemd based systems.

When I use `-H fd://` on Ubuntu 14.04 (which is a non-systemd based system), I see the following error which is tough to understand.  Instead, it would be nice if Docker throws a user-friendly error like `Your OS is not a systemd based system. Use "-H fd://" only on systemd based systems` so that the user knows how to use `-H fd://`.

`
$ sudo /usr/bin/docker daemon -H fd:// --insecure-registry 192.168.122.45:4000
FATA[0000] No sockets found                             
`

BUG REPORT INFORMATION:

`$ docker version
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64
`

`$ docker info
Containers: 12
 Running: 1
 Paused: 0
 Stopped: 11
Images: 434
Server Version: 1.10.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 358
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 14.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.42 GiB
Name: kolla-ubuntu
ID: CH5Y:PDT2:ZGWS:F6OG:HNUG:6A2D:DZ3D:M7WZ:2O5W:EFOJ:Y47G:IRDZ
WARNING: No swap limit support
`

Additional environment details:

Ubuntu 14.04 VM using lbvirt for virtualization.

List the steps to reproduce the issue:
1. `sudo /usr/bin/docker daemon -H fd:// --insecure-registry 192.168.122.45:4000`
2. See the output/error that is tough to understand.

Result received:

`FATA[0000] No sockets found`

Results expected:

`Your OS is not a systemd based system. Use "-H fd://" only on systemd based systems` so that the user knows how to use `-H fd://`

**Comment by HackToday** [comment]
@dibs

**Comment by HackToday** [comment]
#dibs

**Comment by dibs** [comment]
@HackToday you summon me?

**Comment by HackToday** [comment]
@dibs  I typo. Sorry :)
