### ISSUE TITLE
Blocked in "make test" progress

### ISSUE THREAD

**Issue by huangzhendong** [docker/docker#20474]
when i do the "make test" encountering somewhat bewildering complexity, the machine always blocked (the only way to active it is forcing restart), i have tried many times but it still happen, the information about my problem  will show by screenshot. can this be my own problem? please give me some advise, thank you !
![qq 20160219094922](https://cloud.githubusercontent.com/assets/16368297/13164276/f44ac5bc-d6ee-11e5-9ee5-d9cf35169a6a.jpg)
![qq 20160219095155](https://cloud.githubusercontent.com/assets/16368297/13164277/f44ac850-d6ee-11e5-8341-427d17b28804.jpg)
![qq 20160219095403](https://cloud.githubusercontent.com/assets/16368297/13164275/f44abfcc-d6ee-11e5-9f83-e7a6b17304f1.jpg)
![qq 20160219095526](https://cloud.githubusercontent.com/assets/16368297/13164278/f46e1990-d6ee-11e5-8239-045b31872b0c.jpg)

**Comment by HackToday** [comment]
I suggest you run any potential blocking test one by one instead run all at one time.

https://docs.docker.com/opensource/project/test-and-docs/

check above linke , that can help you identify issue, and BYW, it would be better apend text logs, as your screen pic is not clear. :(

**Comment by LK4D4** [comment]
Closing this as inactive. Feel free to post new issue.
