### ISSUE TITLE
Simultaneous builds on Ubuntu 14.04 with aufs driver display funny container names in "docker ps -a"

### ISSUE THREAD

**Issue by vhosakot** [docker/docker#20477]
When "docker build" is done simultaneously in a multi-threaded manner on Ubuntu 14.04 with aufs storage driver, I see **funny** container names in "docker ps -a".

$ **docker version**
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

$ **docker info**
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 69
Server Version: 1.10.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 117
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 14.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.42 GiB
Name: kolla-ubuntu
ID: CH5Y:PDT2:ZGWS:F6OG:HNUG:6A2D:DZ3D:M7WZ:2O5W:EFOJ:Y47G:IRDZ
WARNING: No swap limit support

**Additional environment details:**

Ubuntu 14.04, Docker version 1.10.1 (build 9e83765),
Storage Driver: aufs, Kernel version (4.2.0-27-generic)

**Steps to reproduce the issue:**

1. On Ubuntu 14.04 with aufs storage driver, build many images (~80) using "docker build" with a thread pool size of 8 (8 threads created simultaneously each running "docker build"). Make sure that 8 images are built simultaneously in parallel at any point.

2. After all the 80 images are built, check the output of `docker ps -a`.

**Result received:**

`
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                    PORTS                    NAMES
81c3fbcee61b        registry:2          "/bin/registry /etc/d"   2 hours ago         Up 2 hours                0.0.0.0:4000->5000/tcp   registry
1ae4f5c1494c        5edc57f06dd1        "/bin/sh -c '#(nop) U"   23 hours ago        Created                                            tiny_babbage
7e5562642d95        b1d06b74f1c8        "/bin/sh -c 'chmod 75"   23 hours ago        Exited (0) 23 hours ago                            hopeful_sinoussi
bbc3c8ef1822        84f66aab9061        "/bin/sh -c 'ln -s gl"   25 hours ago        Exited (0) 25 hours ago                            stupefied_golick
24cfe11790a4        b30ffe2ee881        "/bin/sh -c 'chmod 75"   25 hours ago        Exited (0) 25 hours ago                            cocky_kare
a1497c017b9f        d6d838532597        "/bin/sh -c 'apt-key "   25 hours ago        Exited (0) 25 hours ago                            loving_kowalevski
851954c8f39d        da35d3245baa        "/bin/sh -c '#(nop) U"   25 hours ago        Created                                            reverent_leavitt
47de2200d225        3f64eee76c04        "/bin/sh -c '#(nop) C"   25 hours ago        Created                                            big_feynman
0c14230dfc59        3e8763a652cd        "/bin/sh -c 'ln -s te"   25 hours ago        Exited (0) 25 hours ago                            ecstatic_pare
a20a53e70cca        3b46a563d8a2        "/bin/sh -c '#(nop) E"   25 hours ago        Created                                            stupefied_hawking
730144ab5c39        500794a3b01c        "/bin/sh -c '#(nop) E"   25 hours ago        Created                                            dreamy_brown
5c58449dbca4        f0ab0b33e31c        "/bin/sh -c 'apt-key "   25 hours ago        Exited (0) 25 hours ago                            sad_leavitt
`

There are **funny** container names above (like **tiny_babbage, hopeful_sinoussi, ...., sad_leavitt**) not created by the user.

**Results expected:**

`
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                    PORTS                    NAMES
81c3fbcee61b        registry:2          "/bin/registry /etc/d"   2 hours ago         Up 2 hours                0.0.0.0:4000->5000/tcp   registry
`

**Comment by thaJeztah** [comment]
If no name is provided, docker generates names for containers, see https://github.com/docker/docker/blob/630a5a23c73276faefaedd0b639ce1525c2bdc24/pkg/namesgenerator/names-generator.go#L78, and the documentation https://docs.docker.com/engine/reference/run/#name-name

I'm going to close this issue, because this is working as expected; containers without a name specified get a randomly generated name.

**Comment by vhosakot** [comment]
I did provide the name using the `--name` argument but docker still generated these funny names in the output of `docker ps -a`.

**Comment by thaJeztah** [comment]
The `--name` flag is for docker run; during build, each step in a Dockerfile is executed in a new container; those containers don't get a name (and are removed after the build-step is completed), so will get a random name assigned
