### ISSUE TITLE
.dockerignore ! pattern results in slow builds on large contexts

### ISSUE THREAD

**Issue by cricklet** [docker/docker#20470]
I have a huge project. I want to include only files like `package.json` and `requirements.txt` in the build context. To do that, I tried adding a `.dockerignore` that excludes `*` and includes specific files (`!foo/requirements.txt`).

If I try to use `*` in `.dockerignore` and `!` to include specific files, it takes a really long time (if the context directory is large).

```
> du -sh .
1.1G . # this is in a BIG context

> cat empty.dock
FROM ubuntu

> cat .dockerignore
*
!foo/requirements.txt

> docker build -f empty.dock .
# HANGS for a really long time
Sending build context... etc etc
```

Now, if I remove the included file `!foo/bar.txt` from `.dockerignore`, then it's super fast!

```
> cat .dockerignore
*

> docker build -f empty.dock .
Sending build context... etc etc # INSTANT! :D
```

Any idea what's up?

**Comment by cricklet** [comment]
Here's my docker version info:
```
~/Work/ent-docker docker version                                                                                         master!
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:18:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 20:39:58 2016
 OS/Arch:      linux/amd64
~/Work/ent-docker docker info                                                                                            master!
Containers: 9
 Running: 0
 Paused: 0
 Stopped: 9
Images: 96
Server Version: 1.10.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 145
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.17-boot2docker
Operating System: Boot2Docker 1.10.1 (TCL 6.4.1); master : b03e158 - Thu Feb 11 22:34:01 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 3
Total Memory: 4.433 GiB
Name: default
ID: CSQF:QSAQ:Y2DP:MRLC:FPH5:6QJZ:D4CA:GREI:IJYB:CPQC:ZKSQ:SBAJ
Debug mode (server): true
 File Descriptors: 10
 Goroutines: 24
 System Time: 2016-02-19T01:08:13.945945686Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

**Comment by cricklet** [comment]
I'm running `virtualbox` on OSX.

**Comment by cricklet** [comment]
So, in my own project, I've circumvented this problem by using the following `.dockerignore`:

```
*/*/*
```

This makes my builds run really fast. It seems that it's the `!` logic that's slowing things down.

**Comment by duglin** [comment]
I think I know what's going on here. I think when we have a "!dir/file" we end up checking all nested dirs no matter what - instead of just what's under "dir/".  Still investigating and checking on a fix....

**Comment by duglin** [comment]
@cricklet I think I have a fix for this - would you be willing to test it out for me before I submit the PR?

**Comment by cricklet** [comment]
Sure thing. I can test it out on Tuesday (going camping till then)

**Comment by duglin** [comment]
@cricklet any chance you could grab my branch and give this a try?

**Comment by cricklet** [comment]
Will try it tonight at the latest!

**Comment by cricklet** [comment]
Hmm... struggling to set it up on my home computer. Will try and check it out on my work machine tomorrow or day after.

**Comment by duglin** [comment]
@cricklet any update? I can provide a binary for you if you let me know your OS.

**Comment by cricklet** [comment]
Ah yes, that would be great. I spent an hour or so yesterday getting a
docker development environment set up (i.e. the whole docker inside a
docker thing). I ended up getting some weird configuration problems that I
wasn't able to figure out.

A binary would be muuch easier :) I'm on a Mac: OS X 10.10.5 (14F27)

**Comment by duglin** [comment]
@cricklet try the version here:  http://soaphub.org/docker/docker

**Comment by duglin** [comment]
@cricklet any luck with the binary I uploaded?

**Comment by cricklet** [comment]
```
> docker build -f console.dock .
(this completely hangs)
^C
> ~/Work/docker ~/Downloads/docker build -f console.dock .
Sending build context to Docker daemon  29.7 kB
Error response from daemon: client is newer than server (client API version: 1.23, server API version: 1.22)
> 
```

I'm not sure how to upgrade my `server` to `1.23`...

However, it does seem like the actual problem is solved-- the build context is successfully sent (and is small, as expected).

**Comment by thaJeztah** [comment]
@cricklet you can override the API version that the client uses through the `DOCKER_API_VERSION` environment var, for example;

    DOCKER_API_VERSION=v1.22 docker version

**Comment by duglin** [comment]
ok let me submit the PR then!
