### ISSUE TITLE
When call hack/make.sh inside a Docker dev container, gcc failed to run.

### ISSUE THREAD

**Issue by hsinko** [docker/docker#20483]
I'm following the  instructions to build a binary inside a Docker development container. When I call hack/make.sh, I see the following output:

---> Making bundle: binary (in bundles/1.10.0-dev/binary)
Building: bundles/1.10.0-dev/binary/docker-1.10.0-dev
\# github.com/docker/docker/docker
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: fork/exec /usr/bin/gcc: cannot allocate memory.

It bothered me for two days. Then I fixed it. In my opinion, there should be some tips or solution in the instructions around the words "call hack/make.sh" . Could I finish it?
@moxiegirl

**Comment by skairali** [comment]
@hsinko   could you please let me know how you fixed it? Would be helpful for us

**Comment by HackToday** [comment]
The command is this


```
root@5f8630b873fe:/go/src/github.com/docker/docker# hack/make.sh binary
```

**Comment by hsinko** [comment]
add swap space @skairali

**Comment by ZJUshuaizhou** [comment]
Do you use the ECS ? I have got the same problem as @hsinko !

**Comment by HackToday** [comment]
@hsinko  please add more info like
`docker info` 
Your system `uname` related  info
and what intructions you did to reproduce such issue

**Comment by hsinko** [comment]
```bash
root@iZ28quaz1hjZ:/# docker info
Containers: 55
Images: 52
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 162
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-32-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 992.5 MiB
Name: iZ28quaz1hjZ
ID: 7M62:ZV5D:FIE3:BYG6:B27Z:6FRK:TF3J:I3VG:MTLG:JMKJ:2ZLP:UYX2
WARNING: No swap limit support
```
the instructions: [Work with a development container](https://docs.docker.com/opensource/project/set-up-dev-env/)
@HackToday

**Comment by HackToday** [comment]
@hsinko  did you run with `hack/make.sh binary`  or with `hack/make.sh` ?

**Comment by hsinko** [comment]
@HackToday  definitely run with ```bash hack/make.sh binary```

**Comment by HackToday** [comment]
@hsinko  not sure if you get you, you host only have memory with 1GB, right ?

During your run that build instruction, is that memory enough to do that job ?

Did you use simple loop to check your meory usage during run that make command ?

**Comment by LK4D4** [comment]
Seems just like gcc is too expensive on memory. Closing this. Feel free to open new issue.
