### ISSUE TITLE
refuse to run on too old kernels

### ISSUE THREAD

**Issue by jap** [docker/docker#20491]
I just hunted a bug where a build would fail on a single machine - whereas it is succeeding on the rest of our build farm.

It turned out this machine was still running the stock debian wheezy kernel (3.2), which is too old and caused issues. (Upgrading it to 3.16 fixed the build).

Would it be possible for docker to complain loudly if it detects a too old kernel version?

This was with: 

$ docker -v
Docker version 1.9.1, build a34a1d5

**Comment by HackToday** [comment]
Could you show us what's your docker error message look like ?

How did you install docker which make you thought hit kernel issue ?

**Comment by jap** [comment]
The feature request is about adding error messages to docker in this scenario; https://docs.docker.com/engine/installation/linux/debian/ states: 

> Docker requires a 64-bit installation regardless of your Debian version. Additionally, your kernel must be 3.10 at minimum. The latest 3.10 minor version or a newer maintained version are also acceptable.

We were running a 3.2 kernel, and our dockerized build-job started successfully, but failed to complete all tests. This seems to be according to specs; I would have liked a warning here though.
(If you care about the errors themselves, I did not do a deep-dive, but something went wrong with writing or reading in /tmp in the container. They disappeared after upgrading the kernel to a supported one)

**Comment by unclejack** [comment]
This has been brought up in the past in pull requests I've sent and issues I've opened:
https://github.com/docker/docker/pull/7681
https://github.com/docker/docker/pull/8036

This was also an issue opened by @SvenDowideit:
https://github.com/docker/docker/issues/8969

Perhaps the time has come to introduce this requirement? Anyone who's not at least on 3.10 should most certainly upgrade to 3.10 or newer. We won't be hurting anyone by introducing this hard requirement.

Please keep in mind this has nothing to do with required features or detecting needed features as that's a separate story and discussion. We know for a fact kernels older than 3.10 will break. I can assure you that you will run into failures if you've got a kernel older than 3.10.

**Comment by LK4D4** [comment]
This was implemented.
