### ISSUE TITLE
Authz plugin enabled with large text/JSON POST payload corrupts body

### ISSUE THREAD

**Issue by estesp** [docker/docker#20508]
While spending time trying to understand why the `docker_cli_authz_unix_test.go` integration test couldn't load **busybox**, I found out that the `drainBody()` implementation is not correct in `pkg/authorization`.

I haven't totally solved it yet, but wanted to get an issue open in case others have ideas and explain what I've seen so far.

First, a bit more explanation about `drainBody`; https://github.com/docker/docker/blob/master/pkg/authorization/authz.go#L124-L141

The code returns `newBody` in two different paths (although I think the middle error path cannot be reached), and that is used to set the actual request body `r.Body`. The problem is that this auto-truncates the body to 1MB, given the new readcloser is based on the buffer created with `maxBodySize`.  To play with how this actually works I created: http://play.golang.org/p/JvBVh_Z5h4

You really will never get an error in the scenario when the sizes are matched on `Peek` and `NewReaderSize`; except for the `EOF` if the data is smaller, which the code handles correctly.

I'm not sure what the right answer is yet, but currently this messes with body data incorrectly and can cause significant problems with REST calls that have binary data.  In a separate PR I'm proposing fixing the content type so that truly binary data doesn't even go through `drainBody()`. See docker/engine-api#98

Secondly, if you modify the [authz integration-cli test](https://github.com/docker/docker/blob/master/integration-cli/docker_cli_authz_unix_test.go#L174-L180) to attempt image load while the plugin is loaded, the Docker REST API panics with a "form has no body"--haven't gotten to the bottom of how `r.Body` is `nil`, but forcing it to not come through `drainBody` (by setting the content type) fixes the problem.

**Comment by estesp** [comment]
@liron-l assume you will want to look at this

**Comment by liron-l** [comment]
Thanks @estesp for the analysis, two questions:
1. If you change the check to ```bufReader.Peek(maxBodySize + 1)```, it should go into the branch, see [your modified snippet](http://play.golang.org/p/GcqvduNkod). Does this fix the issue?
2. Does this means the content length was less than ```maxBodySize```, but the actual message size was larger?

**Comment by estesp** [comment]
@liron-l yes, I noticed that as well when I was playing with the values, but that won't happen in your current code as `maxBodySize` is used as a fixed value in both calls.

Your point 2 is probably the more interesting one here in that content-length may not be set, or be "-1" to signify "chunked encoding". If that's the case, then similar to the httputils drain function, you would have to handle that in your body drain implementation :(

What I'm not sure is why the daemon panics when the size is larger than your `maxBodySize`; it seems to be because of `r.Body` becoming `nil` somewhere in the process, but I can't find that codepath and haven't had time today to add more debug or figure out a simpler way to test where in the flow that fails.

**Comment by liron-l** [comment]
Thanks @estesp , 
1. Can't we just validate the request/response is of JSON type (in ```sendBody```).
From authz perspective, only the content of control messages, which are all application/json in Docker REST API, really matters. 
2. re ```r.Body == nil```, maybe if ```Peek``` returns a different error than ```io.EOF``` and ```bufio.ErrBufferFull```?

**Comment by cpuguy83** [comment]
Peek does return those errors, but yeah it seems we need to peek +1 extra byte.

The reason we can't just check the request type (or the content length) is a request can cause docker to consume large amounts of memory just by saying it's `application/json`.

**Comment by liron-l** [comment]
Thanks @cpuguy83. I just meant that we only pass the body if the content type is `application/json` without modifying the existing protocols. All "interesting" APIs requests already have this type set correctly (interesting with respect to authorization).
Does this makes sense?

**Comment by cpuguy83** [comment]
@liron-l Sure the official docker client does, but what about other clients, or even malicious requests which can cause the daemon to consume all the hosts memory and crash.

**Comment by liron-l** [comment]
Thanks, I agree.
Let me clarify what I meant:
1. Pass body only for messages with ```application/json``` content type (skip text/* message). I think all clients should follow the protocol described in the official [API](https://docs.docker.com/engine/reference/api/docker_remote_api/) no?
2. Fix the the ```Peek``` check and return error if the body is too large.
What do you think?

**Comment by cpuguy83** [comment]
Works for me.

**Comment by liron-l** [comment]
Thank @cpuguy83, @estesp.
Pushed a fix in #20602, I would like to hear what you think.
