### ISSUE TITLE
What does [r] means in "[[r]shared|[r]slave|[r]private]"

### ISSUE THREAD

**Issue by jay-lau** [docker/docker#20502]
Hi,

I saw that docker 1.10 introduced new volumn mount options as "[[r]shared|[r]slave|[r]private]", what does   [r] means here?

Also does there are any detailed explain for the meaning of each type? share, slave and private? 

Thanks!

**Comment by runcom** [comment]
`r` stays for *recursive* IIRC

**Comment by runcom** [comment]
This is what I remember from the original PR in libcontainer https://github.com/opencontainers/runc/pull/208#issuecomment-132318298 which should explain those modes

**Comment by jay-lau** [comment]
Thanks @runcom for the quick help. @thaJeztah any more comments on what does r mean? any document for this?

BTW: I also get some comments from here https://github.com/torvalds/linux/blob/master/Documentation/filesystems/sharedsubtree.txt , it does helps ;-)

**Comment by cpuguy83** [comment]
@jay-lau `r` here means recursive.
It means any mounts that are underneath the mounpoint you specified will also be treated the same way.

For instance, if you have a mount at `/foo` which you then mount with `shared`, this means any new mounts underneath `/foo` will propagate, but only with the mount mode those mounts already have ([r]shared, [r]private, [r]slave).
If you instead mounted `/foo` with `rshared`, all of `/foo`'s submounts will also be mounted with `rshared`

**Comment by jay-lau** [comment]
Thanks @cpuguy83 , clear now. Does there are any document for this part? I cannot find any document for this new feature so has to ask this via issues.

**Comment by cpuguy83** [comment]
Probably not in our docs.

This is good, though:
https://www.kernel.org/doc/Documentation/filesystems/sharedsubtree.txt

**Comment by jay-lau** [comment]
Thanks @cpuguy83 , it does helps! Actually, I also post this link above ;-) OK, I will close this issue. Thanks all fort the great help!

**Comment by php-coder** [comment]
If it's still not documented in the Docker docs then maybe it should be re-opened? Even short explanation and some links would be helpful.

**Comment by timchenxiaoyu** [comment]
@cpuguy83  r here means recursive
can you support mount example ?  show difference between  shared and rshared  
thanks!
