### ISSUE TITLE
Since "docker tag" does not validate IP address, docker adds images that can never be pulled

### ISSUE THREAD

**Issue by vhosakot** [docker/docker#20527]
"docker tag" does not validate IP address and port. Due to this issue, docker adds images that can never be pulled. `192.168.122.41` below is a valid local IP address on the host and can be pinged.

**$ docker version**
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

**$ docker info**
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 344
Server Version: 1.10.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 321
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 14.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.42 GiB
Name: kolla-ubuntu
ID: CH5Y:PDT2:ZGWS:F6OG:HNUG:6A2D:DZ3D:M7WZ:2O5W:EFOJ:Y47G:IRDZ
WARNING: No swap limit support

**Additional environment details:**

Ubuntu 14.04, Docker version 1.10.1 (build 9e83765),
Storage Driver: aufs, Kernel version (4.2.0-27-generic)

**Docker daemon running:**

**$ ps aux | grep docker**
root      3493  1.0  0.1 1156028 59376 ?       Ssl  17:57   0:32 /usr/bin/docker daemon --insecure-registry 192.168.122.41:4000
root      3566  0.1  0.0 510184 30996 ?        Sl   17:57   0:05 docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 4000 -container-ip 172.17.0.2 -container-port 5000
root      3585  0.1  0.0 486156 27640 ?        Ssl  17:57   0:04 /bin/registry /etc/docker/registry/config.yml

**Steps to reproduce the issue:**

1. Run the following commands. `192.168.122.41` below is a valid local IP address on the host and can be pinged.

$ docker tag ubuntu 192.168.122.41:4000/myfirstimage
$ docker tag ubuntu 1111.2222.3333.4444.5555.6666.7777:99999999/myfirstimage
$ docker tag ubuntu 1111.2222.3333.4444.5555.6666.7778:99999999/myfirstimage
$ docker tag ubuntu 1111.2222.3333.4444.5555.6666.7779:99999999/myfirstimage
$ docker tag ubuntu 1111.2222.3333.4444.5555.6666.7780:99999999/myfirstimage
$ docker tag ubuntu 1111.2222.3333.4444.5555.6666.7781:99999999/myfirstimage
$ docker tag ubuntu 1111.2222.3333.4444.5555.6666.7782:99999999/myfirstimage
$ docker tag ubuntu 1111.2222.3333.4444.5555.6666.7783:99999999/myfirstimage
$ docker tag ubuntu 1111.2222.3333.4444.5555.6666.7784:99999999/myfirstimage
$ docker tag ubuntu 1111.2222.3333.4444.5555.6666.7785:99999999/myfirstimage`

**Result received:**

**$ docker images | grep myfirstimage**
1111.2222.3333.4444.5555.6666.7777:99999999/myfirstimage   latest              14b59d36bae0        2 days ago          188 MB
1111.2222.3333.4444.5555.6666.7778:99999999/myfirstimage   latest              14b59d36bae0        2 days ago          188 MB
1111.2222.3333.4444.5555.6666.7779:99999999/myfirstimage   latest              14b59d36bae0        2 days ago          188 MB
1111.2222.3333.4444.5555.6666.7780:99999999/myfirstimage   latest              14b59d36bae0        2 days ago          188 MB
1111.2222.3333.4444.5555.6666.7781:99999999/myfirstimage   latest              14b59d36bae0        2 days ago          188 MB
1111.2222.3333.4444.5555.6666.7782:99999999/myfirstimage   latest              14b59d36bae0        2 days ago          188 MB
1111.2222.3333.4444.5555.6666.7783:99999999/myfirstimage   latest              14b59d36bae0        2 days ago          188 MB
1111.2222.3333.4444.5555.6666.7784:99999999/myfirstimage   latest              14b59d36bae0        2 days ago          188 MB
1111.2222.3333.4444.5555.6666.7785:99999999/myfirstimage   latest              14b59d36bae0        2 days ago          188 MB
192.168.122.41:4000/myfirstimage                           latest              14b59d36bae0        2 days ago          188 MB

The images with invalid IP address and port cannot be pulled ever. See below.

**$ docker pull 1111.2222.3333.4444.5555.6666.7777:99999999/myfirstimage**
Using default tag: latest
Error response from daemon: unable to ping registry endpoint https://1111.2222.3333.4444.5555.6666.7777:99999999/v0/
v2 ping attempt failed with error: Get https://1111.2222.3333.4444.5555.6666.7777:99999999/v2/: dial tcp: unknown port tcp/99999999
 v1 ping attempt failed with error: Get https://1111.2222.3333.4444.5555.6666.7777:99999999/v1/_ping: dial tcp: unknown port tcp/99999999

**$ docker pull 1111.2222.3333.4444.5555.6666.7778:99999999/myfirstimage**
Using default tag: latest
Error response from daemon: unable to ping registry endpoint https://1111.2222.3333.4444.5555.6666.7778:99999999/v0/
v2 ping attempt failed with error: Get https://1111.2222.3333.4444.5555.6666.7778:99999999/v2/: dial tcp: unknown port tcp/99999999
 v1 ping attempt failed with error: Get https://1111.2222.3333.4444.5555.6666.7778:99999999/v1/_ping: dial tcp: unknown port tcp/99999999

**$ docker pull 1111.2222.3333.4444.5555.6666.7785:99999999/myfirstimage**
Using default tag: latest
Error response from daemon: unable to ping registry endpoint https://1111.2222.3333.4444.5555.6666.7785:99999999/v0/
v2 ping attempt failed with error: Get https://1111.2222.3333.4444.5555.6666.7785:99999999/v2/: dial tcp: unknown port tcp/99999999
 v1 ping attempt failed with error: Get https://1111.2222.3333.4444.5555.6666.7785:99999999/v1/_ping: dial tcp: unknown port tcp/99999999

**The image with valid IP address and port can be pulled fine.**

**$ docker pull 192.168.122.41:4000/myfirstimage**
Using default tag: latest
latest: Pulling from myfirstimage
Digest: sha256:cf852d4ef13b95dd3f33dbe19f673e0d45d0716f27eaa8b62964766532f81918
Status: Downloaded newer image for 192.168.122.41:4000/myfirstimage:latest

**Results expected:**

**$ docker images | grep myfirstimage**

192.168.122.41:4000/myfirstimage                           latest              14b59d36bae0        2 days ago          188 MB

No other image with invalid IP address and port should be added as they cannot be pulled.

**Comment by phemmer** [comment]
I don't see anywhere that you did a push. When I try I get an error:

```
# docker tag ubuntu 1111.2222.3333.4444.5555.6666.7777:99999999/myfirstimage

# docker push 1111.2222.3333.4444.5555.6666.7777:99999999/myfirstimage
The push refers to a repository [1111.2222.3333.4444.5555.6666.7777:99999999/myfirstimage] (len: 1)
unable to ping registry endpoint https://1111.2222.3333.4444.5555.6666.7777:99999999/v0/
v2 ping attempt failed with error: Get https://1111.2222.3333.4444.5555.6666.7777:99999999/v2/: dial tcp: lookup 1111.2222.3333.4444.5555.6666.7777: no such host
 v1 ping attempt failed with error: Get https://1111.2222.3333.4444.5555.6666.7777:99999999/v1/_ping: dial tcp: lookup 1111.2222.3333.4444.5555.6666.7777: no such host
```

**Comment by vhosakot** [comment]
I do not have to push manually. I see docker automatically pushes when I run `docker tag`. Check `docker images` after doing `docker tag`.

`
$ docker tag ubuntu 1111.2222.3333.4444.5555.6666.7777:99999999/myfirstimage
`

Docker pushes 1111.2222.3333.4444.5555.6666.7777:99999999/myfirstimage too at this point.

**$ docker images | grep my first**

1111.2222.3333.4444.5555.6666.7777:99999999/myfirstimage                latest              14b59d36bae0        2 days ago          188 MB

**Comment by phemmer** [comment]
Docker does not push images when you tag them.

The `docker images` command shows your local images, not remote ones.

**Comment by vhosakot** [comment]
These images I see in "docker images" cannot be pulled at all. Is there a way to pull these ?

Docker should check if the tag has an invalid IP address or invalid port, and should not add such images (with invalid IP address or invalid port) when tagged ? Right ?

**$ docker images | grep myfirstimage**
1111.2222.3333.4444.5555.6666.7777:99999999/myfirstimage latest 14b59d36bae0 2 days ago 188 MB

1111.2222.3333.4444.5555.6666.7778:99999999/myfirstimage latest 14b59d36bae0 2 days ago 188 MB

1111.2222.3333.4444.5555.6666.7779:99999999/myfirstimage latest 14b59d36bae0 2 days ago 188 MB

1111.2222.3333.4444.5555.6666.7780:99999999/myfirstimage latest 14b59d36bae0 2 days ago 188 MB

1111.2222.3333.4444.5555.6666.7781:99999999/myfirstimage latest 14b59d36bae0 2 days ago 188 MB

1111.2222.3333.4444.5555.6666.7782:99999999/myfirstimage latest 14b59d36bae0 2 days ago 188 MB

1111.2222.3333.4444.5555.6666.7783:99999999/myfirstimage latest 14b59d36bae0 2 days ago 188 MB

1111.2222.3333.4444.5555.6666.7784:99999999/myfirstimage latest 14b59d36bae0 2 days ago 188 MB

1111.2222.3333.4444.5555.6666.7785:99999999/myfirstimage latest 14b59d36bae0 2 days ago 188 MB

**Comment by phemmer** [comment]
I recommend taking a look at the getting started docs: http://docs.docker.com/mac/started/
They should help clear up some of the confusion. I recommend going through the whole thing, but note the "Tag, push, and pull your image" section.

**Comment by vhosakot** [comment]
I read the docs. I see these errors when I pull.

**$ docker pull 1111.2222.3333.4444.5555.6666.7777:99999999/myfirstimage**
Using default tag: latest
Error response from daemon: unable to ping registry endpoint https://1111.2222.3333.4444.5555.6666.7777:99999999/v0/
v2 ping attempt failed with error: Get https://1111.2222.3333.4444.5555.6666.7777:99999999/v2/: dial tcp: unknown port tcp/99999999
v1 ping attempt failed with error: Get https://1111.2222.3333.4444.5555.6666.7777:99999999/v1/_ping: dial tcp: unknown port tcp/99999999

**$ docker pull 1111.2222.3333.4444.5555.6666.7778:99999999/myfirstimage**
Using default tag: latest
Error response from daemon: unable to ping registry endpoint https://1111.2222.3333.4444.5555.6666.7778:99999999/v0/
v2 ping attempt failed with error: Get https://1111.2222.3333.4444.5555.6666.7778:99999999/v2/: dial tcp: unknown port tcp/99999999
v1 ping attempt failed with error: Get https://1111.2222.3333.4444.5555.6666.7778:99999999/v1/_ping: dial tcp: unknown port tcp/99999999

**$ docker pull 1111.2222.3333.4444.5555.6666.7785:99999999/myfirstimage**
Using default tag: latest
Error response from daemon: unable to ping registry endpoint https://1111.2222.3333.4444.5555.6666.7785:99999999/v0/
v2 ping attempt failed with error: Get https://1111.2222.3333.4444.5555.6666.7785:99999999/v2/: dial tcp: unknown port tcp/99999999
v1 ping attempt failed with error: Get https://1111.2222.3333.4444.5555.6666.7785:99999999/v1/_ping: dial tcp: unknown port tcp/99999999

**Comment by cpuguy83** [comment]
You can't `pull` images from another docker instance anyway. You wouldn't be able to `push` these either unless the address is valid.
A tag is just a reference to an image and an image can have many tags.

**Comment by vhosakot** [comment]
It it ok to show images in the output of `docker images` that can neither be pushed nor pulled ?

An image like `1111.2222.3333.4444.5555.6666.7785:99999999/myfirstimage` can neither be pushed nor pulled. Shouldn't there be a **note** about this in the documentation for `docker tag` in https://docs.docker.com/engine/reference/commandline/tag/ ?

**Comment by cpuguy83** [comment]
docker images shows images that exist on the host. Having a push/pull-able tag does not matter.
