### ISSUE TITLE
"make binary" will fail if the git branch name has "/" character in it.

### ISSUE THREAD

**Issue by swernli** [docker/docker#20520]
@jstarks @jhowardmsft 
Currently, the makefile automatically uses the name of the current git branch as a tag for the image created by the build.  However, if the branch uses the "/" character, which is common guidance for making git branches, the build will fail because this character is not allowed in docker tags.  Docker should either accept the same set of characters for tags that is legal for git branch names, or the makefile should do some automatic processing to remove unacceptable characters.

**Comment by LK4D4** [comment]
Just tested. Works now.

**Comment by jhowardmsft** [comment]
Oooh neat :)

**Comment by vdemeester** [comment]
@runcom fixed it a while ago… didn't know there was an issue about that :sweat:

**Comment by jhowardmsft** [comment]
:tada: @runcom
