### ISSUE TITLE
docker container killed

### ISSUE THREAD

**Issue by xssxyby** [docker/docker#20534]
I get this docker log 

> 2016-02-19 20:30:00.516 [http-nio-8080-exec-3] INFO *******
> Killed

and no other error log,where is wrong

**Comment by HackToday** [comment]
@xssxyby  when you open bugs, please follow above info to help deveopers know that.
like `docker info`  and system info `uname -a`

also you couble enable debug level logs like `docker daemon -D `  which can give you good info.

**Comment by thaJeztah** [comment]
I'm closing this issue, because there not a lot for us to work on without additional information, but happy to reopen if more information is added

**Comment by xssxyby** [comment]
Ah,I get these info.

`uname -a`
>Linux 10-4-20-127 3.13.0-55-generic #94-Ubuntu SMP Thu Jun 18 00:27:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

`dcoker verion`
>Client version: 1.7.0
>Client API version: 1.19
>Go version (client): go1.4.2
>Git commit (client): 0baf609
>OS/Arch (client): linux/amd64
>Server version: 1.7.0
>Server API version: 1.19
>Go version (server): go1.4.2
>Git commit (server): 0baf609
>OS/Arch (server): linux/amd64
and my docker info is

> Containers: 109
>Images: 609
>Storage Driver: aufs
> Root Dir: /data/docker_home/docker/aufs
> Backing Filesystem: extfs
> Dirs: 838
> Dirperm1 Supported: false
>Execution Driver: native-0.2
>Logging Driver: json-file
>Kernel Version: 3.13.0-55-generic
>Operating System: Ubuntu 14.04 LTS
>CPUs: 4
>Total Memory: 7.798 GiB
>Name: 10-4-20-127
>ID: XSOY:UQIM:UTGY:OQGZ:NEB5:K242:VIVW:PERZ:ZN3W:H4XL:JRAE:FTJG
>WARNING: No swap limit support

`docker ps -a | grep mgmt`

> 3c52da913bbc        boot_assetmgmt                                                     "/bin/sh -c 'java -j   21 hours ago        Exited (137) 14 hours ago                                       boot_assetmgmt_1
and my docker logs is 

`docker logs 3c52da913bbc`
>2016-02-20 21:29:40.953 [main] INFO  org.apache.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-8080"]
>2016-02-20 21:29:40.963 [main] INFO  org.apache.coyote.http11.Http11NioProtocol - Starting ProtocolHandler ["http-nio-8080"]
>2016-02-20 21:29:40.973 [main] INFO  org.apache.tomcat.util.net.NioSelectorPool - Using a shared selector for servlet write/read
>2016-02-20 21:29:41.111 [main] INFO  o.s.b.c.e.tomcat.TomcatEmbeddedServletContainer - Tomcat started on port(s): 8080 (http)
>2016-02-20 21:29:41.125 [main] INFO  com.creditcloud.assetmgmt.Application - Started Application in 208.133 seconds (JVM running for 222.285)
>2016-02-20 21:29:41.125 [main] INFO  com.creditcloud.assetmgmt.Application -

>***********************************************************************
>*              Server Started           *
>***********************************************************************

>2016-02-20 21:30:01.063 [http-nio-8080-exec-1] INFO  o.a.c.core.ContainerBase.[Tomcat].[localhost].[/] - Initializing Spring FrameworkServlet 'dispatcherServlet'
>2016-02-20 21:30:01.064 [http-nio-8080-exec-1] INFO  org.springframework.web.servlet.DispatcherServlet - FrameworkServlet 'dispatcherServlet': initialization started
>2016-02-20 21:30:01.090 [http-nio-8080-exec-1] INFO  org.springframework.web.servlet.DispatcherServlet - FrameworkServlet 'dispatcherServlet': initialization completed in 25 ms
>Killed

**Comment by HackToday** [comment]
it seems you container internal issue. Did you try other container like hello-world or busybox. is it OK?

And for your container case above, please also show output of docker server logs when such container started
