### ISSUE TITLE
user namespaces problems

### ISSUE THREAD

**Issue by a93ushakov** [docker/docker#20546]
`docker 1.10.1`
`debian 8.3 x64`

I edit `/lib/systemd/system/docker.service` docker systemd service and set 
```sh
ExecStart=/usr/bin/docker daemon  --userns-remap=default -H fd://
```

Now root in container is not root on host system - it's great.

But there are two problems:
1. user namespaces isolation is not enabled by default
2. --net="host" is unavailable now:
```sh
docker: Error response from daemon: Cannot share the host or a container's network namespace when user namespaces are enabled..
```

So, without user namespace isolation containers are totally insecure, and without `--net="host"` flag networking is very slow.

What do you think about it?

**Comment by cpuguy83** [comment]
user namespaces cannot be enabled by default, it would break almost everyone right out of the gate... and I'm not certain that this is even all that necessary. Most services can be run as non-root and do not need root privileges inside the container. If you are running trusted services this is all fine. You can use an authorization framework to make sure containers don't run as root if it's really a problem. The threat model that user namespaces is good for is protecting against getting root in a container... but if you don't run as root in a container the threat is much reduced.

User namespaces are not a security silver bullet but rather one extra layer to help protect the host from untrusted code just like we have seccomp, privilege drops, apparmor/selinux etc.

I also wouldn't call the networking very slow without net=host. I'd guess 95%+ people wouldn't even notice the overhead of bridge networking.
In cases where it is a problem, you can use macvlan or ipvlan which binds directly to a (real) host interface. I would be surprised if there wasn't already a network plugin for these.

**Comment by mkonakan** [comment]
So, are the usernamespaces going to be not enabled by default even in future releases? Also, what is the future plans in terms of namespaces?

**Comment by cpuguy83** [comment]
@mkonakan I don't see a reason to enable them by default. Not everyone needs user namespaces.
Can you explain further what you mean by "what is the future plans in terms of namespaces"? What namespaces?

**Comment by mkonakan** [comment]
Got that. Thank you for quick response. Sorry - I mean user namespaces. Are you planning to incorporate any new feature set to user namespaces?

**Comment by cpuguy83** [comment]
@mkonakan Do you have some suggestion?

**Comment by cpuguy83** [comment]
Closing this since it's not really an issue.

**Comment by mkonakan** [comment]
No Problem. Not actually - I was going through some articles online and found somewhere that Docker will be adding more feature set to this user namespaces in their next release but they did not mention what they were. So thought of just checking here. ( I am sorry , I tried getting that link but could not find it as I was going through tons of links from past couple of days).

**Comment by mkonakan** [comment]
Not sure, if this will be right thread to ask about Project Nautilus. I could not find any information about it online, when is it going to be released or is it released and is in use only for official docker hub users etc? Can you throw some light on this? or else is there any specific thread where I can ask this question?

**Comment by fiksn** [comment]
I've stumbled upon this a few years later (docker 18.6.1). I am fine with user namespaces not being enabled by default. But why can't you combine user namespaces and host networking?
