### ISSUE TITLE
[feature request] docker build with cache option or re-try prompting before exit on failure.

### ISSUE THREAD

**Issue by askb** [docker/docker#20544]
While building a large sized image, in the event that `docker build .` fails due to issue not related to the `dockerfile`, but a temporary "network connectivity issue" or other similar issue unrelated to the `dockerfile`, would it be possible to incorporate re-prompting the user (with a "re-try" option) to try/redo the `RUN` command, instead of abruptly exiting and starting from the beginning. 

This would be quite useful when you have built several layers and failure occurs in the final command. Alternatively, if there some way to cache (`docker build . --cache`) to the built layer/progress allowing the built to restart from point of failure, instead of restart the build from the beginning of the `dockerfile`.     

```
$ docker build .
...
......
...
Get:484 http://ppa.launchpad.net/ubuntu-wine/ppa/ubuntu/ trusty/main wine1.7 amd64 1:1.7.55-0ubuntu1 [1152 kB]
Fetched 306 MB in 1h 27min 53s (58.1 kB/s)
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/o/openexr/libopenexr6_1.6.1-7ubuntu1_amd64.deb  Connection failed [IP: 91.189.92.200 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?                                                                                                            
The command '/bin/sh -c apt-get install -y wine1.7 winetricks' returned a non-zero code: 100


```

**Comment by cpuguy83** [comment]
The build will not start from the beginning, it will start from the build step where the failure occurred.
Docker does cache each build step.

**Comment by askb** [comment]
@cpuguy83 Thanks for clarifying. Will close this now.
