### ISSUE TITLE
"docker run & create" volume help is not right 

### ISSUE THREAD

**Issue by jay-lau** [docker/docker#20553]
The "docker run & create" help info for volume does not include the new volume mode: [[r]shared|[r]slave|[r]private]

But " man docker run" does work well.

root@mesos002:~/src/mesos/m1/mesos# docker version
dClient:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:36:33 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:36:33 2016
 OS/Arch:      linux/amd64
root@mesos002:~/src/mesos/m1/mesos# docker run --help | grep volume
  -v, --volume=[]                 Bind mount a volume
  --volume-driver                 Optional volume driver for the container
  --volumes-from=[]               Mount volumes from the specified container(s)

**Comment by cpuguy83** [comment]
It doesn't include the other available options either, `ro`, `rw`, `z`, and `Z`.
The format of `--help` does not really allow for including so many options.

Closing since I don't think this is something we'll change.
