### ISSUE TITLE
What is the relationship of [rw|ro] and the propagation options for volume

### ISSUE THREAD

**Issue by jay-lau** [docker/docker#20555]
The docker volume now support some propagation options as following:

-v, --volume=[host-src:]container-dest[:<options>]: Bind mount a volume.
The comma-delimited `options` are [rw|ro], [z|Z], or
[[r]shared|[r]slave|[r]private]. The 'host-src' is an absolute path or a
name value.

So if I specified a volume as shared, then does the volume is rw or ro? What is the relationship of [rw|ro] and [[r]shared|[r]slave|[r]private].

Also can anyone help explain what does [z|Z] mean here?

Thanks.

**Comment by JonathonReinhart** [comment]
`-z` and `-Z` tell Docker to relabel the host file/directory for compatibility with SELinux. See [Manage data in containers: Volume labels](https://docs.docker.com/engine/userguide/containers/dockervolumes/#volume-labels).

**Comment by thaJeztah** [comment]
Thanks @JonathonReinhart 

I'll close this issue, because I think this is answered, but feel free to continue the discussion

**Comment by jay-lau** [comment]
Sorry, I also want to know the relationship of [rw|ro] and [[r]shared|[r]slave|[r]private]. I found that I cannot use both options in [rw|ro] and [[r]shared|[r]slave|[r]private] in one command.

**Comment by JonathonReinhart** [comment]
@thaJeztah It seems that shared/slave/private do not seem to be documented... at all.  Places where it is missing or completely underwhelming:

- https://docs.docker.com/engine/reference/run/
- https://docs.docker.com/engine/reference/commandline/run/
- https://docs.docker.com/engine/userguide/containers/dockervolumes/  (which is supposed to be the more-detailed reference for volumes)

Just Ctrl+F for the word "slave" on those pages.  I would re-open this and change the title to "Documentation missing for shared/slave/private volume options".

**Comment by thaJeztah** [comment]
@JonathonReinhart hm looks like you're right; the PR introducing this only added this to the man-pages (https://github.com/docker/docker/pull/17034); there was supposed to be a follow-up PR to revisit those docs and add it to the online-documentation as well; https://github.com/docker/docker/pull/17034#issuecomment-164824550, but I think that never got opened.

Can you open an issue for that? Feel free to ping me there, then I'll see if there's some bandwidth to address the missing docs
