### ISSUE TITLE
[QUESTION]does anybody knows how to compile docker in suse with kernel 3.0.93-0.8-default

### ISSUE THREAD

**Issue by vklonghml** [docker/docker#20568]
as the title said, i want to compile docker in suse with very low kernel version, and have many prolems, if there is someone who has succeeded done this before, thanks.

**Comment by thaJeztah** [comment]
Kernel 3.0.x is too old for docker, as it doesn't have all the requirements to run it. The current absolute minimum version is kernel 3.10
