### ISSUE TITLE
1.10.1 --device broken when "VOLUME /dev" in Dockerfile

### ISSUE THREAD

**Issue by istr** [docker/docker#20563]
When exposing a device using the flag ```--device``` (e.g. ```/dev/vboxdrv```) and the docker image has got the entry

```
VOLUME /dev
```

in the ```Dockerfile``` docker 1.10.1 fails to expose the device node given by the command line flag.

```
[06:46:36 root@trusty64:~] $ docker --version
Docker version 1.10.1, build 9e83765
[06:46:39 root@trusty64:~] $ docker run --device=/dev/vboxdrv --rm -it jubbr/gitlab-ci-runner:0.0.4 ls -lisa /dev/vboxdrv
ls: cannot access /dev/vboxdrv: No such file or directory
```

this works perfectly using docker 1.9.1:

```
[06:41:56 root@trusty64:~] $ docker --version
Docker version 1.9.1, build a34a1d5
[06:44:09 root@trusty64:~] $ docker run --device=/dev/vboxdrv --rm -it jubbr/gitlab-ci-runner:0.0.4 ls -lisa /dev/vboxdrv
2237501 0 crw------- 1 root root 10, 54 Feb 21 14:44 /dev/vboxdrv
```

As a reference I kept the "broken" image online. The next version (0.0.5) has got the  ```VOLUME /dev``` line removed from the ```Dockerfile``` and works like expected both using 1.9.1 and 1.10.1.

The working ```Dockerfile``` (both 1.9.1 and 1.10.1) looks like this:

```
# minimal dockerfile for gitlab CI runners (have git and docker installed)
FROM phusion/baseimage:0.9.18
MAINTAINER istr <docker@ingostruck.de>

# Make APT non-interactive
ENV DEBIAN_FRONTEND noninteractive

# Ensure UTF-8
ENV LANG       en_US.UTF-8
ENV LC_ALL     en_US.UTF-8

# Change this ENV variable to skip the docker cache from this line on
ENV LATEST_CACHE 2016-02-19T12:00-00:00

# Purge packages / services we do not want
RUN apt-get purge -y \
  cron \
  openssh-server \
  openssh-sftp-server \
  && apt-get autoremove -y \
  && rm -rf /etc/service/cron /etc/service/ssh

# Prevent installation of "recommended" packages
COPY etc/apt/apt.conf /etc/apt/apt.conf

# Use fast mirror
COPY etc/apt/sources.list /etc/apt/sources.list

# Copy vagrant package
COPY pkg/vagrant_1.8.1_x86_64.deb /var/tmp/vagrant_1.8.1_x86_64.deb

# Upgrade the system to the latest version
RUN apt-get update \
    && apt-get upgrade -y -o Dpkg::Options::="--force-confold"

# Install git-lfs using packagecloud.io script
RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | /bin/bash

# Install packages needed for this image

RUN apt-get install -y --force-yes \
  git \
  git-lfs \
  virtualbox

# Install vagrant
RUN dpkg -i /var/tmp/vagrant_1.8.1_x86_64.deb

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

CMD ["echo", "run with /bin/bash to inspect this gitlab CI multirunner image"]

# NOTE: if you would like to use virtualbox / vagrant in this image
# you MUST expose the following devices using docker --device flags:
#
# /dev/vboxdrv
# /dev/vboxdrvu
# /dev/vboxnetctl
#
# If, for any reason, you need USB support in your setup, you need
# to expose /dev/vboxusb as well.
#
# As of gitlab-ci-multirunner 1.1 you can set this in your config.toml:
# [runners.docker]
#   privileged = false
#   devices = [
#     "/dev/vboxdrv",
#     "/dev/vboxdrvu",
#     "/dev/vboxnetctl"
#   ]

# EOF Dockerfile for jubbr/gitlab-ci-runner:0.0.5
```

If you add  ```VOLUME /dev``` before ```CMD ...``` this breaks in 1.10.1.

Set  @JonathonReinhart and @ayufan CC like promised.

EDIT:
Affected setup as per  https://github.com/docker/docker/blob/master/CONTRIBUTING.md
```
jc@neo:/opt/jc$ docker version
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

jc@neo:/opt/jc$ uname -a
Linux neo 3.19.0-49-generic #55~14.04.1-Ubuntu SMP Fri Jan 22 11:24:31 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

jc@neo:/opt/jc$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
```

Both on an installation running native and an installation running in a virtualbox container.

**Comment by JonathonReinhart** [comment]
Ah, I didn't know you had a `/dev` volume in the image. This appears to be very much related to #20228.

**Comment by phemmer** [comment]
Why do you want `VOLUME /dev` in your dockerfile? What are you trying to accomplish?

**Comment by istr** [comment]
> Why do you want VOLUME /dev in your dockerfile? What are you trying to accomplish?

In fact the ```VOLUME``` entry was a try to achieve the same like passing the ```--device``` flag, but *without* the need to pass arguments on the command line. Basically I want to keep as much setup information as possible in VM images ("containers"), so they can be run standalone without passing any additional command line options, whatsoever.

It turns out that this seems to be impossible (there are quite a few more command line options that can't be set in the ```Dockerfile```) and this is one of the top reasons why I am moving from docker packages to other container formats where you can package the *complete* setup information needed to run the image into the image itself.

I consider the need for a hint like the following severely broken:

```
# NOTE: if you would like to use virtualbox / vagrant in this image
# you MUST expose the following devices using docker --device flags:
#
# /dev/vboxdrv
# /dev/vboxdrvu
# /dev/vboxnetctl
```

Closing, because like @JonathonReinhart pointed out, this is a duplicate of #20228 I failed to find before opening this issue.

**Comment by thaJeztah** [comment]
> and this is one of the top reasons why I am moving from docker packages to other container formats where you can package the complete setup information needed to run the image into the image itself.

I think one important thing to consider here, is a separation between *runtime* / *operational* settings and other settings. Docker makes a distinction here, so that images are portable. For example, `/dev/vboxnetctl` will only be available on a system that runs VirtualBox, but not in other situations. If an *image* would dictate that `/dev/vboxnetctl` would be mounted when it is run, that image could only be run in particular setups (i.e., when running on VirtualBox).

Docker Compose is more targeted at specifying runtime configuration; i.e., it would allow you to specify that certain devices have to be used when running a container (or stack of containers), e.g. see https://docs.docker.com/compose/compose-file/#devices

**Comment by istr** [comment]
@thaJeztah Exposing ```/dev/vbox*``` of the host to the docker container is a kludge by itself, to run VirtualBox *within* a docker image. Without the need for this kludge the image would be perfectly portable.

To elaborate on the use case:
- a gitlab CI runner (a docker image) shall be used to build / package vagrant boxes
- to achieve this a virtualbox within the runner docker container is needed
- a standalone virtualbox installation in a docker container seems to be impossible
- as a workaround the host has got the virtualbox kernel drivers installed and exposes the devices
- so the host in this case *is known* to have virtualbox installed, but *only* because docker does not support running it "self-contained"

As a consequence, the docker-based runner itself will be dropped asap in favor of another runner type that supports a standalone installation of virtualbox.
