### ISSUE TITLE
CentOS packages do not provide 'docker'

### ISSUE THREAD

**Issue by ross-w** [docker/docker#20567]
Description of problem:
The CentOS packages for docker-engine at yum.dockerproject.org do not provide 'docker', meaning that other CentOS packages which require 'docker' end up conflicting/removing the Docker Project provided RPMs in favour of older, CentOS-provided Docker versions.

`docker version`:
n/a

`docker info`:
n/a

`uname -a`:
n/a

Environment details (AWS, VirtualBox, physical, etc.):
CentOS Linux 7.2.

How reproducible:
Always

Steps to Reproduce:
1. Add yum.dockerproject.org repo to a CentOS 7 system
2. Install docker-engine from yum.dockerproject.org repo
3. Try to install another CentOS-provided package which requires docker (such as kubernetes-node from CentOS extras)

Actual Results:
Installation causes error due to conflict between docker-engine and docker packages. Proceeding downgrades Docker to the CentOS-provided Docker and removal of the yum.dockerproject.org packages.

Expected Results:
Packages relying on 'docker' should install without throwing up an error and/or causing the uninstall of the newer docker-engine packages.

Additional info:

**Comment by HackToday** [comment]
Seems it was also issue of CentOs packaged problem.
What's the result if doing above steps in order of 3, 1, 2 ?  Will docker-engine install remove old version ?

**Comment by ross-w** [comment]
docker-engine will remove docker yes, but it will also remove anything that relies on Docker. There's no way to have (for example) kubernetes-client installed as well as docker-engine. In CentOS Docker is provided by 'docker' rather than 'docker-engine'.

**Comment by HackToday** [comment]
ping @jfrazelle

**Comment by HackToday** [comment]
also @thaJeztah

**Comment by thaJeztah** [comment]
I'm not sure we can do something here; if the "extras" repository contains packages that use the `docker` package from the "extras" repo, then uninstalling `docker-engine` is expected, because `docker` and `docker-engine` are the same packages, but maintained by different packagers.

**Comment by jfrazelle** [comment]
We can't override an existing name

On Monday, February 22, 2016, Sebastiaan van Stijn <notifications@github.com>
wrote:

> I'm not sure we can do something here; if the "extras" repository contains
> packages that use the docker package from the "extras" repo, then
> uninstalling docker-engine is expected, because docker and docker-engine
> are the same packages, but maintained by different packagers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/20567#issuecomment-187091522>.
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jfrazelle** [comment]
Same goes for Debian based, this should be closed

On Monday, February 22, 2016, Sebastiaan van Stijn <notifications@github.com>
wrote:

> I'm not sure we can do something here; if the "extras" repository contains
> packages that use the docker package from the "extras" repo, then
> uninstalling docker-engine is expected, because docker and docker-engine
> are the same packages, but maintained by different packagers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/20567#issuecomment-187091522>.
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by thaJeztah** [comment]
Closing, per the discussion above, but feel free to comment here after I've closed

**Comment by sammcj** [comment]
Bug logged with Redhat - https://bugzilla.redhat.com/show_bug.cgi?id=1310903

**Comment by sammcj** [comment]
Redhat have deemed it a Docker bug that they won't fix: https://bugzilla.redhat.com/show_bug.cgi?id=1310903

**Comment by tianon** [comment]
I think if RPMs have a concept of "Provides", that's probably our best bet
here (as noted in the OP) -- that way our package would advertize that it's
the "same" as the provided "docker" package and would thus satisfy the
dependencies of related packages appropriately.

**Comment by recteurlp** [comment]
any update ?

Same issue with Fedora 23

```
$ rpm -qp --provides docker-engine-1.10.3-1.fc23.x86_64.rpm
docker-engine = 1.10.3-1.fc23
docker-engine(x86-64) = 1.10.3-1.fc23

$ rpm -q --provides docker
config(docker) = 1:1.9.1-6.git6ec29ef.fc23
docker = 1:1.9.1-6.git6ec29ef.fc23
docker(x86-64) = 1:1.9.1-6.git6ec29ef.fc23
docker-io = 1:1.9.1-6.git6ec29ef.fc23
lxc-docker = 1:1.9.1-6.git6ec29ef.fc23

dnf install --allowerasing docker-engine
Dependencies resolved.
=============================================================================================================================================================================================================
 Package                                                Arch                                   Version                                                   Repository                                     Size
=============================================================================================================================================================================================================
Installing:
 docker-engine                                          x86_64                                 1.10.3-1.fc23                                             dockerrepo                                    9.7 M
 docker-engine-selinux                                  noarch                                 1.10.3-1.fc23                                             dockerrepo                                     32 k
 policycoreutils-python                                 x86_64                                 2.4-21.fc23                                               updates                                       400 k
Removing:
 cockpit                                                x86_64                                 0.96-1.fc23                                               @updates                                       36 k
 cockpit-docker                                         x86_64                                 0.96-1.fc23                                               @updates                                       23 k
 docker                                                 x86_64                                 1:1.9.1-6.git6ec29ef.fc23                                 @System                                        38 M
 docker-selinux                                         x86_64                                 1:1.9.1-6.git6ec29ef.fc23                                 @updates                                       25 k
 rpm-ostree-toolbox                                     x86_64                                 2015.8-4.fc23                                             @@commandline                                 361 k

Transaction Summary
=============================================================================================================================================================================================================
Install  3 Packages
Remove   5 Packages
```

Could you test to add the missing dependencies in the docker-engine rpm ?

**Comment by q53** [comment]
Hi all.
I have tried to build virtual rpm which provides docker dependence and install it with kubernets from CentOS extras repository. It failed because your rpm spec include:
`
Conflicts: docker
Conflicts: docker-io
Conflicts: docker-engine-cs
`
So you are saying that is impossible to install any native rpm form CentOS/RHEL  required docker if you install docker-engine? The only question left is what is the meaning of docker-engine rpm? This makes it absolutely useless.

**Comment by mootezbessifi** [comment]
please any idea about this bug ??
Actually i am trying to install a kubernetes-node package and it conflicts with docker-engine and docker-engine-selinux. i want to override this packages.
what is recommended to avoid this issue? is the installation from kubernetes-node github release (kubelet,kube-proxy,etc) or importing another kubernetes-node package from somewhere???
