### ISSUE TITLE
get.docker.com script causes hash sum mismatch

### ISSUE THREAD

**Issue by arekkas** [docker/docker#20564]
Description of problem:

```
> wget -qO- https://get.docker.com/ | sh
....
W: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-vivid/main/b
inary-amd64/Packages  Hash Sum mismatch
```

`docker version`: none (not installed)

`docker info`: none (not installed)

`uname -a`: 

> Linux vagrant-ubuntu-vivid-64 3.19.0-49-generic #55-Ubuntu SMP Fri Jan 22 02:10
:24 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):

Fresh VirtualBox (using vagrant)

How reproducible:

`wget -qO- https://get.docker.com/ | sh`

Steps to Reproduce:
1. Create a Vagrantfile using `ubuntu/vivid64`
2. `vagrant up`
3. `vagrant ssh`
4. `sudo -s`
5. `wget -qO- https://get.docker.com/ | sh`

Actual Results:

> W: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-vivid/main/b
inary-amd64/Packages  Hash Sum mismatch

Expected Results:

The installation should succeed.

Additional info: None

**Comment by HackToday** [comment]
Not sure why choose vivid ubuntu.

From https://github.com/docker/docker/issues/19451  vivid is EOL support in docker.

**Comment by rizotas** [comment]
I get the same hash sum error, from Chef cookbook to install Docker

**Comment by thaJeztah** [comment]
@rizotas also on Ubuntu 15.04, or on another version?

**Comment by rizotas** [comment]
@thaJeztah Yes, Ubuntu 15.04

**Comment by jhohlfeld** [comment]
on Ubuntu 15.04 amd(64) here aswell:

> W: Size of file /var/lib/apt/lists/partial/apt.dockerproject.org_repo_dists_ubuntu-vivid_Release.gpg is not what the server reported 801 454
> W: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-vivid/main/binary-amd64/Packages  Hash Sum mismatch
>

**Comment by brbsix** [comment]
I'n also experiencing this issue in Ubuntu 15.04. I hadn't installed or updated anything recently, simply resynchronizing the package index with `apt-get update` provoked the error. I also cleared out the cached lists in */var/lib/apt/lists* to no avail.

**Comment by Clockyx82** [comment]
same here with 15.04 
Before the 1.10 release I didnt have an issue with those scripts.

**Comment by andreas-kupries** [comment]
Just for the record, I am seeing the same this morning, with a vagrant setup which worked last friday now broken. Ubuntu vivid, 15.04.

**Comment by Kazempour** [comment]
As @HackToday has already mentioned, vivid is EOL support in docker.
Updating Vagrant to use Wily 15.10 will fix the problem.

**Comment by thaJeztah** [comment]
We're looking into this issue; even though we won't be publishing new releases for 15.04 (because it's EOL'd), the Hash Sum Mismatch looks to be the result of an index file being updated while publishing binaries for the other releases.

(@tiborvass assigning you to this one)

**Comment by anusha-ragunathan** [comment]
I was able to repro this issue on a vivid host with non-vagrant setup as well. I was able to workaround the issue by removing /etc/apt/trusted.gpg. I'm not suggesting this as a workaround for this issue. It's a data point to help in debugging.

**Comment by tiborvass** [comment]
@arekkas can you paste the output of `apt-key list` please?

**Comment by tiborvass** [comment]
@arekkas As well as `grep 'installed docker' /var/log/dpkg.log`, that would be very helpful.

**Comment by jfrazelle** [comment]
I can't repro in a container please clear your apt-cache or move to a non EOL distro since you won't get docker updates anyways

**Comment by aleksanyan** [comment]
Hi guys,

It happens on ubuntu 14.04.
Latest version of docker at this moment is v1.11.2.
However in [Package](https://apt.dockerproject.org/repo/dists/ubuntu-vivid/main/binary-amd64/Packages) file, from which apt-get is trying to pull, shows
`Filename: pool/main/d/docker-engine/docker-engine_1.6.0-0~vivid_amd64.deb
Size: 4425284
MD5sum: 4709784de5a8e1759a8fcdd6091cb203`

Shouldn't it point to v1.11.2 package in [here](https://apt.dockerproject.org/repo/pool/main/d/docker-engine/)?

**Comment by thaJeztah** [comment]
@aleksanyan we're aware of this; and hope to have this resolved ASAP see my comment on this issue; https://github.com/docker/docker/issues/23203#issuecomment-223289216

**Comment by aleksanyan** [comment]
@thaJeztah thanks, Your workaround works.
`curl -fsSL https://test.docker.com | sh`

**Comment by thaJeztah** [comment]
@aleksanyan remember to change it back to get.docker.com after the issue is fixed, otherwise you won't get new releases

**Comment by aleksanyan** [comment]
@thaJeztah Yes! Thanks again.

**Comment by jnbnyc** [comment]
+1 affected by this

`
10:44:48 W: Failed to fetch https://apt.dockerproject.org/repo/dists/debian-jessie/main/binary-amd64/Packages  Hash Sum mismatch
`

https://gist.github.com/jnbnyc/8bb4742ada04f1615267450d521e5025
