### ISSUE TITLE
'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded

### ISSUE THREAD

**Issue by 1993hzh** [docker/docker#20573]
Hi guys,

I recently try to install a docker in another docker container, however, I cannot start the inside docker due to some errors. Below is the detail info.
I am worried about whether I can install an inside docker or not? If not, could you pls explain it to me?

### docker version:
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:09:42 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

### docker info:
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

### uname -a:
Linux 7a704532b288 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 GNU/Linux

Provide additional environment details (AWS, VirtualBox, physical, etc.):
A docker container(debian jessie)

### List the steps to reproduce the issue:
1. install the docker-engine(debain jessie) follow the steps in doc
2. after the docker installed successfully, run ```docker daemon```

### Expect result:
Docker start successfully.

### Actual result:
```
ERRO[0000] 'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded. 
INFO[0000] Graph migration to content-addressability took 0.00 seconds 
WARN[0000] Running modprobe bridge br_netfilter failed with message: modprobe: ERROR: ../libkmod/libkmod.c:557 kmod_search_moddep() could not open moddep file '/lib/modules/3.16.0-30-generic/modules.dep.bin'
modprobe: ERROR: ../libkmod/libkmod.c:557 kmod_search_moddep() could not open moddep file '/lib/modules/3.16.0-30-generic/modules.dep.bin'
, error: exit status 1 
WARN[0000] Running modprobe nf_nat failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:557 kmod_search_moddep() could not open moddep file '/lib/modules/3.16.0-30-generic/modules.dep.bin'`, error: exit status 1 
FATA[0000] Error starting daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain: iptables failed: iptables -t nat -N DOCKER: iptables v1.4.21: can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
 (exit status 3) 
```

**Comment by cpuguy83** [comment]
As stated in the logs, you must run docker with root privileges.
You should use `sudo start docker` or `sudo systemctl start docker` (depending on if you have upstart or systemd as your init daemon) to start docker.

**Comment by 1993hzh** [comment]
@cpuguy83 Thanks for focusing.

First, the logged user is root and I had run ```newgrp docker```

Second, ```service docker start``` does not start the docker successfully, ```service docker status``` returned 
> [FAIL] Docker is not running ... failed!

**Comment by cpuguy83** [comment]
@1993hzh `service docker start` will start the sysvinit script, which I wouldn't expect to work well. Must use `start docker` (assuming upstart) and you can check the logs in `/var/log/upstart/docker.log`

**Comment by 1993hzh** [comment]
@cpuguy83 

```systemctl start docker``` returned 
> Failed to get D-Bus connection: Unknown error -1


```/var/log/upstart/docker.log``` cannot be found, but I can see ```/var/log/docker.log```, which looks like
> time="2016-02-22T15:07:46.630248306Z" level=error msg="'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded." 
time="2016-02-22T15:07:46.634711256Z" level=info msg="Graph migration to content-addressability took 0.00 seconds" 
time="2016-02-22T15:07:46.636455859Z" level=warning msg="Running modprobe bridge br_netfilter failed with message: modprobe: ERROR: ../libkmod/libkmod.c:557 kmod_search_moddep() could not open moddep file '/lib/modules/3.16.0-30-generic/modules.dep.bin'\nmodprobe: ERROR: ../libkmod/libkmod.c:557 kmod_search_moddep() could not open moddep file '/lib/modules/3.16.0-30-generic/modules.dep.bin'\n, error: exit status 1" 
time="2016-02-22T15:07:46.638668487Z" level=warning msg="Running modprobe nf_nat failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:557 kmod_search_moddep() could not open moddep file '/lib/modules/3.16.0-30-generic/modules.dep.bin'`, error: exit status 1" 
time="2016-02-22T15:07:46.697709320Z" level=fatal msg="Error starting daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain: iptables failed: iptables -t nat -N DOCKER: iptables v1.4.21: can't initialize iptables table `nat': Permission denied (you must be root)\nPerhaps iptables or your kernel needs to be upgraded.\n (exit status 3)"

**Comment by cpuguy83** [comment]
It also looks like you've got overlay selected as a graph driver which you don't have the kernel module loaded for.

**Comment by 1993hzh** [comment]
@cpuguy83 Yep, I am afraid docker does not support docker in docker which caused the inside docker failed to start

**Comment by cpuguy83** [comment]
@1993hzh Docker does support docker in docker, but you have to use `--privileged`.

**Comment by rustamagasanov** [comment]
@cpuguy83 @1993hzh  I have the same issue, trying to setup `docker` in official `jenkins` image(https://hub.docker.com/_/jenkins/) which runs on `debian jessie`. I followed the installation guide step by step, but `docker` daemon doesn't seem to work.

```
# service docker start
[ ok ] Starting Docker: docker.
# service docker status
[FAIL] Docker is not running ... failed!
# cat /var/log/docker.log
time="2016-03-02T11:44:44.157595213Z" level=error msg="'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded."
time="2016-03-02T11:44:44.162146192Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
time="2016-03-02T11:44:44.164876563Z" level=warning msg="Running modprobe bridge br_netfilter failed with message: modprobe: ERROR: ../libkmod/libkmod.c:557 kmod_search_moddep() could not open moddep file '/lib/modules/3.13.0-77-generic/modules.dep.bin'\nmodprobe: ERROR: ../libkmod/libkmod.c:557 kmod_search_moddep() could not open moddep file '/lib/modules/3.13.0-77-generic/modules.dep.bin'\n, error: exit status 1"
time="2016-03-02T11:44:44.166376138Z" level=warning msg="Running modprobe nf_nat failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:557 kmod_search_moddep() could not open moddep file '/lib/modules/3.13.0-77-generic/modules.dep.bin'`, error: exit status 1"
time="2016-03-02T11:44:44.202937867Z" level=fatal msg="Error starting daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain: iptables failed: iptables -t nat -N DOCKER: iptables v1.4.21: can't initialize iptables table `nat': Permission denied (you must be root)\nPerhaps iptables or your kernel needs to be upgraded.\n (exit status 3)"
```

Could you suggest any solution?
Thanks

**Comment by thaJeztah** [comment]
@rustamagasanov the container still shares the *kernel* with the host, so if the kernel of the host doesn't support it, the container cannot use it.

**Comment by rustamagasanov** [comment]
@thaJeztah thank you for explanation. Seems like I found a solution for anyone with the same problem:
http://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/

**Comment by thaJeztah** [comment]
@rustamagasanov absolutely; that is the better approach overall :+1:

**Comment by Kxrr** [comment]
`sudo apt-get install docker-engine=1.8.0-0~trusty` saved me(ubuntu, 3.16.0-43-generic).

**Comment by jokergaming** [comment]
@1993hzh  I had the same issue on my pc too, and I'm using Arch linux.
So, if you use Arch too, you need to reboot your computer after install docker from AUR,
for some unknown reason, this   worked for me, hope that works for you too.

**Comment by rbenal** [comment]
I have Arch too and after system upgrade docker crash with same issue, reboot my pc works for me too!!

**Comment by AnakTeka** [comment]
I'm using Arch Linux, `'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded` error is fixed after restarting my system

**Comment by arxra** [comment]
Following the footsteps of Isopod , this applies to most arch-based linux distributions as well, for me it was Manjaro linux.
