### ISSUE TITLE
Where and how the docker images are getting stored in host machine

### ISSUE THREAD

**Issue by yogeshjadoun** [docker/docker#20571]

**Comment by HackToday** [comment]
@yogeshjadoun  this is just question not issue, I did not think it is right place for general question here.

Hope this can help you understand lot of.
https://github.com/docker/docker/blob/master/docs/userguide/storagedriver/imagesandcontainers.md

 also you can google/stackflow and use #docker channel to ask

 question

**Comment by thaJeztah** [comment]
Closing; as @HackToday explained, the GitHub issue tracker is for tracking bugs and feature requests, not a general support forum

**Comment by yogeshjadoun** [comment]
Thanks for the info
