### ISSUE TITLE
docker 1.10 regression: does not respond to basic auth 401 challenge as it did for previous versions

### ISSUE THREAD

**Issue by peterlynch** [docker/docker#20582]
I have a private docker registry listening at https://192.168.2.97:19301 

The docker daemon is configured as follows:

```
/usr/bin/docker daemon -H fd:// --insecure-registry 192.168.2.97:19301
```

It is also using an http proxy using this setting:

```
Environment="HTTP_PROXY=http://192.168.2.97:8888/"
```

### 1.9.1 docker client 

```
docker pull 192.168.2.97:19301/ubuntu
```

This completes as expected.
- client makes a request to GET https://192.168.2.97:19301/v2/
- server responds with 401
- client makes a request to GET https://192.168.2.97:19301/v1/repositories/ubuntu/images
- server responds with the various images and eventually pull completes as expected

### 1.10.1 docker client 

While making no changes on the server/registry side, use a docker 1.10.1 client and daemon:

```
docker pull 192.168.2.97:19301/ubuntu
```

This fails:
- client makes a request to GET https://192.168.2.97:19301/v2/
- server responds with 401
- client makes a request to GET http://192.168.2.97:19301/v2/
- server is not listening as HTTP on that port, it is listening as HTTPS so this request fails
- the docker CLI prints this message:

```
osboxes@osboxes:~/dev/docker-test/docker1.10$ docker pull 192.168.2.97:19301/ubuntu
Using default tag: latest
Error response from daemon: Get http://192.168.2.97:19301/v2/: EOF
```

### Expected

- maintain backward compatibility of client behaviour
- do not downgrade from secure connection to insecure connection ( bad practice to perform this downgrade transparently and clearly does not make sense to attempt to use plain http on an already confirmed https port )
- document any incompatible changes and any expected new server behaviour for registry/docker API implementors

**Comment by peterlynch** [comment]
This may be related to #20097

**Comment by peterlynch** [comment]
I wanted to point out that if i do not use the --insecure-registry argument, and copy the CA certificate to the global or docker specific location instead, things work as expected with 1.10.2

**Comment by thaJeztah** [comment]
> and copy the CA certificate to the global or docker specific location instead,

Where were the certificates before?

**Comment by peterlynch** [comment]
> Where were the certificates before?

I used --insecure-registry to avoid putting them anywhere on the host running docker daemon. Isn't that a valid use case of --insecure-registry? to bypass certificate trust problems?

**Comment by thaJeztah** [comment]
Hm, looks like this PR may fix that situation on master; https://github.com/docker/docker/pull/20253

**Comment by aaronlehmann** [comment]
Confirming the comment above; #20253 fixes this behavior.

In the mean time, installing the certs and avoiding `--insecure-registry` can work around this. I try to encourage people not to use `--insecure-registry`, because aside from the terrible security implications, it also has poorly defined semantics, since it means the registry may be using either HTTP or HTTPS.

**Comment by peterlynch** [comment]
thx @aaronlehmann - Sonatype has published an article which discourages use of insecure-registry and provides alternative steps to generate a self-signed certificate.
