### ISSUE TITLE
[1.10.x] AppArmor profile generation failure when `docker` not in `$PATH`

### ISSUE THREAD

**Issue by icecrime** [docker/docker#20584]
### Description

In 1.10.x, when Docker is downloaded as a static binary and run outside of `$PATH`, the daemon won't start on AppArmor enabled system as AppArmor profile generation will fail.

### Analysis

The faulty line is [`daemon/execdriver/native/apparmor.go#98`](https://github.com/docker/docker/blob/v1.10.1/daemon/execdriver/native/apparmor.go#L98).

We need the full path of the docker binary as part of the profile generation, but this line assumes that the binary is called `"docker"` and part of the `$PATH`, which is not guaranteed.

### Possible fixes

One possible fix would be to rely on `/proc/self/exe` for current binary path determination.

**Comment by icecrime** [comment]
@thaJeztah That would be good to document somewhere until we ship a proper fix, but I don't know which is the right place for that.

Also cc @mavenugo.

**Comment by thaJeztah** [comment]
@icecrime perhaps in the installation docs for static binaries; its only an issue the first time it's started, right? After that, the profile is generated? https://github.com/docker/docker/blob/master/docs/installation/binaries.md

**Comment by robvelor** [comment]
@thaJeztah I'm currently experiencing this issue using the static binaries, I'll get back to you about the questions.

**Comment by robvelor** [comment]
@thaJeztah Re running the docker binary on daemon mode did not fix the issue, a file is created on `/etc/apparmor.d/docker` but it is always empty.  Tested on 1.10.0 - 1.10.2

**Comment by thaJeztah** [comment]
@robvelor I think the issue is that the binary must be called `docker`, and (iirc) be located in `/usr/bin/`. If the binary is given another name, the profile won't be created

**Comment by robvelor** [comment]
@thaJeztah I'm installing the binary under the user's home directory, I'll get back to you. By the way I'm updating from `1.9.1` to `1.10.X`, no issues on `1.9.1` with the setup I am describing, but I ran into this while trying to do a clean `1.10.X` install.  If the apparmor profile is there (previously installing `1.9.1`) and then update the binary then obviously there are no issues.

**Comment by cyphar** [comment]
If all we care about is the full path of the binary we can just do `$(readlink /proc/self/exe)` -- which always returns full paths (even if you call it like `./readlink`).
