### ISSUE TITLE
Using Win32-OpenSSH for Docker on Windows

### ISSUE THREAD

**Issue by jpierson** [docker/docker#20583]
Steps to reproduce:

1. Install Win32-OpenSSH (ex. `choco install win32-openssh`)
2. Reboot Windows.
2. Follow Docker Install instructions for Windows from official documentation using the CMD or PowerShell option (https://docs.docker.com/engine/installation/windows/#using-the-docker-quickstart-terminal)

Expected result: Same result as the documentation specifies.

Actual result: `Error creating machine: Error in driver during machine creation: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded`

Following the instructions for installing Docker on Windows I ran into [an issue](https://github.com/PowerShell/Win32-OpenSSH/issues/121) which resulted in an error when creating a machine using the `docker-machine create` command. I narrowed it down to it likely being due to the use of _ssh_ distributed as part of [Win32-OpenSSH](https://github.com/PowerShell/Win32-OpenSSH) as opposed to the copy that is installed along with Git. Since the documentation suggests _appending_ as opposed to _prepending_ `c:\Program Files (x86)\Git\bin` to the `PATH` environment variable the _Win32-OpenSSH_ copy of ssh.exe is always resolved regardless and ends up failing presumably due to either are hard coded dependency on something related to the bundled Git implementation or a deficit in the _Win32-OpenSSH_ implementation. Since I'm unaware of whether the issue is on the Docker or Win32-OpenSSH side of things I'm posting an issue here to investigate and perhaps answer that question.
Ultimately with the prospect that we may have a well supported ssh capability bundled for windows means that we may be able to simplify the story of tools like this on Windows which may have been born out of the Linux/Unix ecosystem so the sooner issues like this are resolved the better experience we will have for all devs that use these tools. Thanks for all the great work!

OS: Windows 10

docker version: 
>Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:14:21 2016
 OS/Arch:      windows/amd64
An error occurred trying to connect: Get http://127.0.0.1:2375/v1.22/version: dial tcp 127.0.0.1:2375: connectex: No connection could be made because the target machine actively refused it.

docker info:
>An error occurred trying to connect: Get http://127.0.0.1:2375/v1.22/info: dial tcp 127.0.0.1:2375: connectex: No connection could be made because the target machine actively refused it.

**Comment by thaJeztah** [comment]
Looks like this is an issue with docker-machine, which has its own repository and issue-tracker. Can you open this issue in the docker-machine issue tracker? You can find it here; https://github.com/docker/machine/issues

I'm going to close this issue here, because unfortunately there's nothing we can do in this repository. But feel free to comment here after I've closed
