### ISSUE TITLE
Docker API doesn't return the running containers

### ISSUE THREAD

**Issue by enlinxu** [docker/docker#20585]
My docker version:
[ec2-user@ip-10-0-0-71 ~]$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64

[ec2-user@ip-10-0-0-71 ~]$ sudo docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
14d78c518504        jess/stress         "stress -c 4"       3 minutes ago       Up 3 minutes                            ecstatic_ramanujan
[ec2-user@ip-10-0-0-71 ~]$ curl http://localhost:4243/containers/json
[]

See above, when run docker ps, I can see the container with jess/stress image running. But if I run the remote rest, then nothing is returning.
If I do: 
[ec2-user@ip-10-0-0-71 ~]$ curl http://localhost:4243/containers/json?all=1

I do get the following containers that have been stopped, but still no running container.

[{"Id":"de672aac8ccaee30a951ba1b4ca3943eb3baee8557b5251ed534019f08101718","Names":["/sharp_kirch"],"Image":"ubuntu:14.04","ImageID":"6cc0fc2a5ee3bc506e9a0c41eb25431b4d163b1e407c927ee3ac18169d53cc1a","Command":"/bin/bash","Created":1454531601,"Ports":[],"Labels":{},"Status":"Exited (137) 8 minutes ago","HostConfig":{"NetworkMode":"default"}},{"Id":"c518fe83633e724494ce6cb4f54c10606ea43261f9b5e865a36b2b51c8fa260e","Names":["/admiring_fermat"],"Image":"ubuntu:14.04","ImageID":"6cc0fc2a5ee3bc506e9a0c41eb25431b4d163b1e407c927ee3ac18169d53cc1a","Command":"/bin/bash","Created":1454531581,"Ports":[],"Labels":{},"Status":"Created","HostConfig":{"NetworkMode":"default"}},{"Id":"bfab3471fead3b07471a5beba6525d3f3a72c37a74f7f2496f649bf841dc094b","Names":["/drunk_shaw"],"Image":"ubuntu:14.04","ImageID":"6cc0fc2a5ee3bc506e9a0c41eb25431b4d163b1e407c927ee3ac18169d53cc1a","Command":"/bin/bash","Created":1454531552,"Ports":[],"Labels":{},"Status":"Created","HostConfig":{"NetworkMode":"default"}},{"Id":"21059e48c2008f45985b7978be453c1f44ae3d90d386ea303e1b6a2412360b42","Names":["/modest_jennings"],"Image":"ubuntu:14.04","ImageID":"6cc0fc2a5ee3bc506e9a0c41eb25431b4d163b1e407c927ee3ac18169d53cc1a","Command":"/bin/bash","Created":1454527298,"Ports":[],"Labels":{},"Status":"Exited (0) 2 weeks ago","HostConfig":{"NetworkMode":"default"}}]

**Comment by enlinxu** [comment]
[ec2-user@ip-10-0-0-71 ~]$ docker version
Client:
Version: 1.9.1
API version: 1.21
Go version: go1.4.2
Git commit: a34a1d5
Built: Fri Nov 20 13:25:01 UTC 2015
OS/Arch: linux/amd64

[ec2-user@ip-10-0-0-71 ~]$ sudo docker info
Containers: 6
Images: 9
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-202:2-17274602-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 480.4 MB
 Data Space Total: 107.4 GB
 Data Space Available: 8.557 GB
 Metadata Space Used: 1.319 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: Red Hat Enterprise Linux
CPUs: 2
Total Memory: 3.451 GiB
Name: ip-10-0-0-71.ec2.internal
ID: 53CB:VFIC:MK4R:QGOQ:CFKI:72CH:PGT3:ZJDM:L7U5:UG4W:46XP:3B2J
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

AWS vm, AMI ID: RHEL-7.2_HVM_GA-20151112-x86_64-1-Hourly2-GP2 (ami-2051294a)

To reproduce the issue:
1. Start the VM in AWS using the above AMI, and set up the secure group for all traffic access.
2. Install docker https://docs.docker.com/engine/installation/linux/rhel/
3. sudo docker daemon -H tcp://0.0.0.0:4243 
4. Start docker service
5. sudo docker run jess/stress -c 4

Describe the results you received:
After the above steps, the rest API is not returning anything for running container query
[ec2-user@ip-10-0-0-71 ~]$ curl http://localhost:4243/containers/json
[]


If I run docker ps, I got:
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
14d78c518504        jess/stress         "stress -c 4"       3 minutes ago       Up 3 minutes                            ecstatic_ramanujan


Describe the results you expected:
I expect to see jess/stress returned from the API.

**Comment by HackToday** [comment]
I used docker 1.10.1, can find it can work

```
[centos@centostest docker]$ docker  -H tcp://0.0.0.0:4243 ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
d23cd69d4df8        jess/stress         "stress -c 4"       5 minutes ago       Up 5 seconds                            focused_austin
[centos@centostest docker]$  curl http://localhost:4243/containers/json
[{"Id":"d23cd69d4df8fe33a84902183ffd561606f6829df3038d4e71b639f2f3b0df4b","Names":["/focused_austin"],"Image":"jess/stress","ImageID":"sha256:e3317ea109cfa6e8648d003afd6f2e90ed8b99cde66023baeb5aa01c37303e2c","Command":"stress -c 4","Created":1456196377,"Ports":[],"Labels":{},"Status":"Up 12 seconds","HostConfig":{"NetworkMode":"default"},"NetworkSettings":{"Networks":{"bridge":{"IPAMConfig":null,"Links":null,"Aliases":null,"NetworkID":"","EndpointID":"8b8ca885d75445a9a8bc00fdebe8a2f27fbc4aca4649ae6647761b82a1f409e8","Gateway":"172.17.0.1","IPAddress":"172.17.0.2","IPPrefixLen":16,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"02:42:ac:11:00:02"}}}}]
```

Not sure how did you hit such issue, Maybe you need enable debug level logs in docker and check related info

**Comment by cpuguy83** [comment]
>3. sudo docker daemon -H tcp://0.0.0.0:4243 
>4. Start docker service
>5. sudo docker run jess/stress -c 4

How come you are doing steps 3 and 4? It should be one or the other.
You can't run two daemons on one host.

The Docker CLI is making the exact request as you've done with `curl`, so my guess is you're hitting a different daemons between the docker CLI and curl.
Check your `env | grep DOCKER` and make sure `DOCKER_HOST` is set to `tcp://localhost:2375`... or explicitly set it like `docker -H tcp://localhost:2375 ps`

**Comment by enlinxu** [comment]
thanks @cpuguy83 for your help. I will close the issue now.
