### ISSUE TITLE
Docker-machine doesn't tell you how to specify a host name

### ISSUE THREAD

**Issue by pcgeek86** [docker/docker#20593]
On my Macbook Pro, running Mac OS X El Capitan, I tried using `docker-machine` to create a new Docker host, and received an error:

> Error: No machine name specified

However, there is absolutely nothing in the help text that tells me how to specify the "machine name."

The "usage" says:

```
Usage: docker-machine create [OPTIONS] [arg...]
```

The error message is helpful, but it doesn't tell you how to resolve the error. I'm using `docker` version:

```
Trevors-MBP:~ trevorsullivan$ docker -v
Docker version 1.10.1, build 9e83765
```

My recommendation is to avoid making assumptions about the end user's knowledge of command line structure, and make it painfully clear how to properly and comprehensively use the command. Upon further inspection, this actually applies to pretty much all of the `docker-machine` sub-commands. None of them specify anywhere, how to specify a Docker host's name, within a command call. It is assumed that the user knows to tack it on at the end of the command line.

There should probably also be a common `--host` parameter on all of the `docker-machine` sub-commands, so that the user can explicitly specify the Docker host using a named parameter, versus a positional parameter.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by thaJeztah** [comment]
Hi @pcgeek86. Thanks for reporting!

Can you reopen this issue in the docker-machine issue tracker? Unfortunately there's nothing we can do in this repository :cry: You can find that issue tracker here; https://github.com/docker/machine/issues

I'm closing this issue here, but feel free to comment here after I've closed

**Comment by pcgeek86** [comment]
@thaJeztah Thanks, sorry I'm new to Docker, and still learning to navigate the waters. Appreciate you pointing me in the proper direction!

Cheers,
Trevor Sullivan

**Comment by thaJeztah** [comment]
@pcgeek86 no worries; it happens to others as well. thanks for taking the time reporting issues, it's appreciated!
