### ISSUE TITLE
Proposal: update to networks_stats for container stats api

### ISSUE THREAD

**Issue by wenchma** [docker/docker#20596]
I think we should unify the display for each metrics of container stats api as follows( change `networks` to `networks_stats`):

    {
     "read" : "2015-01-08T22:57:31.547920715Z",
     "networks_stats": {
             "eth0": {
                 ...
             }
     },
     "memory_stats" : {
     ...
     },
    "blkio_stats" : {},
    "cpu_stats" : {},

`docker version`

    $ docker version
	Client:
	 Version:      1.10.1
	 API version:  1.22
	 Go version:   go1.5.3
	 Git commit:   9e83765
	 Built:        Thu Feb 11 19:27:08 2016
	 OS/Arch:      linux/amd64

	Server:
	 Version:      1.10.1
	 API version:  1.22
	 Go version:   go1.5.3
	 Git commit:   9e83765
	 Built:        Thu Feb 11 19:27:08 2016
	 OS/Arch:      linux/amd64

`docker info`

    Containers: 4
	 Running: 2
	 Paused: 0
	 Stopped: 2
	Images: 156
	Server Version: 1.10.1
	Storage Driver: aufs
	 Root Dir: /var/lib/docker/aufs
	 Backing Filesystem: extfs
	 Dirs: 164
	 Dirperm1 Supported: true
	Execution Driver: native-0.2
	Logging Driver: json-file
	Plugins: 
	 Volume: local
	 Network: null host bridge
	Kernel Version: 4.2.0-22-generic
	Operating System: Ubuntu 14.04.1 LTS
	OSType: linux
	Architecture: x86_64
	CPUs: 4
	Total Memory: 15.67 GiB
	Name: docker
	ID: UT5D:M5ZY:IEXQ:6LCU:YX6J:ZMWM:BLNJ:MTXH:PRHO:ETVF:3FHH:6LC4
	WARNING: No swap limit support

`uname -a`

    Linux docker 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by wenchma** [comment]
@thaJeztah @mavenugo wdyt ?

**Comment by calavera** [comment]
As expressed in docker/engine-api#107, it's unfortunate that we didn't catch this earlier, but I don't think it's worth the change if we have to make it backwards compatible and main both names.

**Comment by thaJeztah** [comment]
I agree (and also feel bad about not catching it) - note that if we ever reconsider, I think the JSON property should be `network_stats`.


I'm closing this issue, thanks for suggesting, but I hope you understand :+1:
