### ISSUE TITLE
shared volume?

### ISSUE THREAD

**Issue by xionglingfeng** [docker/docker#20601]
Docker can mount host directory with shared flag:

docker -v /run:/run:shared

if 'mount /run --make-shared' is run before.
However, if I try to mount a volume with shared flag:

docker -v my_vol:/mnt:shared

the creation is failed.
How shall I do to make it work?

**Comment by cpuguy83** [comment]
This won't work. You must mount a host dir and not a named volume.

**Comment by thaJeztah** [comment]
@cpuguy83 can we produce an error if someone tries to use these options on non bind-mounted volumes?

**Comment by cpuguy83** [comment]
@thaJeztah 

```
docker: Error response from daemon: Invalid bind mount spec "foo:/bar:shared": volumeinvalid: Invalid volume specification: 'foo:/bar:shared'.
See 'docker run --help'.
```

**Comment by thaJeztah** [comment]
@cpuguy83 touché :smile: hm, not very descriptive (would've expected something about the "shared" option not being valid for this). Feel free to close if that's taking it too far

**Comment by cpuguy83** [comment]
Yeah, it's because we're so overloaded on the flag.

**Comment by xionglingfeng** [comment]
If mount a named volume with shared flag is impossible, is there anyway to share mounts within the volume?
For example, a named volume is mounted in a container, then the container mount a NFS share in a directory inside the volume. How can nnother container which also mount the named volume to use that NFS share?

**Comment by thaJeztah** [comment]
@xionglingfeng I think that container would also have to mount the same NFS share. A cleaner option may be to use a volume-plugin that supports NFS, so that you can create a named volume for the NFS mount, and use that in multiple containers. For a list of volume-plugins, see https://docs.docker.com/engine/extend/plugins/ (I think there are some in there that support NFS)

**Comment by xionglingfeng** [comment]
@thaJeztah , thanks for your advice. Unfortunately, the mounting behaviour is out of my control. I cannot use plugins to manually mount NFS shares as volumes.
I am running nova from OpenStack and libvirt in two separate containers, nova_compute and nova_libvirt. Both containers mounted a named volume, nova_compute, at /var/lib/nova. nova_compute automatically mounted a NFS share at /var/lib/nova/mnt/{hash}, and nova_libvirt expects the files available from same path.
Because they are running in two different containers, although both of them mounted a same volume at same path (/var/lib/nova), the NFS share mounted by nova_compute (at /var/lib/nova/mnt/{hash}) is unavailable for nova_libvirt container.
I am looking for a solution for this specific scenario.

**Comment by cpuguy83** [comment]
You have to bind the location to the host in o See to setup shared mounts.

**Comment by cpuguy83** [comment]
*in order to setup
