### ISSUE TITLE
blank screen when command fails?

### ISSUE THREAD

**Issue by ultrasaurus** [docker/docker#20606]
Are there logs that docker puts somewhere that can help me figure out what's going wrong when there is no terminal output?

Description of problem:  I was attempting to [set up a project for local development](https://github.com/18F/openopps-platform/issues/1244) by mounting a local volume in the docker container.  On my way to getting it working, one of the commands seemed to fail and gave me no output.  I looked through the docs and didn't find any hint as to how to discover what was going wrong.  

`docker version`:
```
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:14:21 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 20:39:58 2016
 OS/Arch:      linux/amd64
```

`docker info`:
```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 5
Server Version: 1.10.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 56
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.1.17-boot2docker
Operating System: Boot2Docker 1.10.1 (TCL 6.4.1); master : b03e158 - Thu Feb 11 22:34:01 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: 4KRM:3GEK:VCCN:UR46:VY5A:OGQ7:2JM7:AZQQ:IIPI:KV65:BZDQ:C4HF
Debug mode (server): true
 File Descriptors: 11
 Goroutines: 22
 System Time: 2016-02-23T13:22:16.779727413Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: sarahallen
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

`uname -a`:
```
Darwin awesomeness.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
```

Environment details (AWS, VirtualBox, physical, etc.): local OSX laptop

How reproducible: 100%

Steps to Reproduce:
1. ```docker run -Pti -v `pwd`:/usr/src/app --name local-opps 18fgsa/open-opps```

Actual Results:  I see a blank screen in Kinematic

![image](https://cloud.githubusercontent.com/assets/41906/13252996/8665c968-d9ee-11e5-8f64-5356e5de9fc3.png)

When I press "start" it immediately stops.

Expected Results: Server startup with terminal output

Additional info:  I was able to change the syntax of the command (overriding the entrypoint) to get it to run, but I would like to understand why it didn't work and how to debug this kind of situation.  More context here:  https://github.com/18F/openopps-platform/issues/1244

**Comment by MHBauer** [comment]
I don't use kitematic, so I'm not sure if that's the problem.

Is the image ~6 month old one on dockerhub? Or is it a freshly built one from your repo? I do not have any problem attempting to run the one from hub, but it does not successfully run either. I get a bunch of node & npm debug info.

**Comment by thaJeztah** [comment]
Hi @ultrasaurus, looking at the issue I suspect this is either an issue with the image you're running, or possibly a Kitematic issue. Do other images run successfully?

Please consider that this isn't a general support forum; I think this is more suitable for either of the following;


1) the forums: https://forums.docker.com/
2) the docker-user mailing list https://groups.google.com/forum/#!forum/docker-user
3) the #docker IRC channel on Freenode.
4) StackOverflow (https://stackoverflow.com)

1) and 2) should be better for longer conversations.

I'm going to close this now, but feel free to comment after I've closed

**Comment by ultrasaurus** [comment]
@thaJeztah yes, this was a problem with the image I was running, and an issue with Kitematic rather than Docker.  Sorry about that.  I'll start in the forums...

**Comment by ultrasaurus** [comment]
I still think this is a docker question, in the first line of the summary: "Are there logs that docker puts somewhere that can help me figure out what's going wrong when there is no terminal output?"  but I'll start with the forums:

https://forums.docker.com/t/how-to-debug-a-blank-screen-when-docker-image-fails-to-load/7675

I've figured out the specific problem with my image, but I'd like to know in general how to debug this kind of situation.
