### ISSUE TITLE
Cannot push images

### ISSUE THREAD

**Issue by lukebond** [docker/docker#20614]
```
$ docker --version
Docker version 1.10.2, build c3959b1

$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 43
Server Version: 1.10.2
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.4.1-2-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.684 GiB
Name: luke-arch
ID: VX6W:357V:NHSG:AIUU:KPTR:3JNA:OJEM:U3IJ:IAJ5:L5OC:I2ZY:JLJJ
Username: lukebond
Registry: https://index.docker.io/v1/
```

**Steps to reproduce the issue (replace the target repository below of course):**
1. git clone https://github.com/lukebond/demo-api-redis
2. cd demo-api-redis
3. docker build - lukebond/demo-api-redis .
4. docker push lukebond/demo-api/redis

**Results I received:**
One of the layers didn't push and kept retrying until finally giving up with "unexpected EOF".

```
$ docker push lukebond/demo-api-redis
The push refers to a repository [docker.io/lukebond/demo-api-redis]
547e19189b01: Layer already exists 
cebd9caf2770: Layer already exists 
467f289079de: Layer already exists 
5f70bf18a086: Layer already exists 
267425d7b570: Pushing [==================================================>] 182.8 MB
ffb5284eed8b: Pushing [==================================================>] 5.029 MB/5.029 MB
unexpected EOF
```

**Results I expected:**
The image successfully pushed to the remote repository.

**Additional info I think is important:**
I tried another image (https://github.com/lukebond/demo-api), and it built and pushed fine. I tried rebuilding the image again with `--no-cache` and pushing again, same result.

I created a public repo on quay.io and pushed the image there, with the same result (ie. unsuccessful).

**Comment by cpuguy83** [comment]
ping @aaronlehmann

**Comment by lukebond** [comment]
New information: I tried it on a friends Mac running Docker 1.8.2, and I was able to push successfully.

**Comment by aaronlehmann** [comment]
There was a bug in 1.10.0 and 1.10.1 that affected migration of images from earlier Docker releases (see #20104). This has been corrected in 1.10, but images that were migrated by 1.10.0 or 1.10.1 will still be affected.

Can you try removing `gliderlabs/alpine:3.1` and re-pulling it before building?

**Comment by lukebond** [comment]
That fixed it. Thanks @aaronlehmann!

**Comment by cpuguy83** [comment]
:heart: thanks @aaronlehmann
