### ISSUE TITLE
Dockerfile cannot open assembly

### ISSUE THREAD

**Issue by Rui90** [docker/docker#20616]
Hello

I'm using mono to try to make a docker container of an C# .exe file.

I'm using the following dockerfile: 

FROM mono:4.2.2.30
CMD [ "mono",  "./MSPlatformHost.exe" ]

Then I build the image with: docker build -t platform.
Then I try: docker run platform 

But I'm always getting: Cannot open assembly './MSPlatformHost.exe': No such file or directory.

Any ideia of what is going on?

**Comment by cpuguy83** [comment]
Where is `MSPlatformHost.exe` coming from?

**Comment by Rui90** [comment]
it is in the same place as my dockerfile

**Comment by cpuguy83** [comment]
You need to do a `COPY <file> <target>` in your Dockerfile in order for that file to be added to a container.

**Comment by Rui90** [comment]
so my dockerfile should be:

FROM mono:4.2.2.30
CMD [ "mono",  "./MSPlatformHost.exe" ]

COPY  "./MSPlatformHost.exe" .


?

**Comment by cpuguy83** [comment]
Or rather
```Dockerfile
FROM mono:4.2.2.30
COPY MSPlatformHost.exe ./
CMD [ "mono", "./MSPlatformHost.exe" ]
```

**Comment by Rui90** [comment]
on docker run platform
I'm still getting: Cannot open assembly './MSPlatformHost.exe': No such file or directory.

**Comment by cpuguy83** [comment]
Maybe an issue with the relative path at this point?

**Comment by Rui90** [comment]
yeah it was a relative path problem... i already passed that xd now i'm before:

System.IO.FileNotFoundException: Could not load file or assembly 'MSPlatform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one
 of its dependencies.

**Comment by thaJeztah** [comment]
closing, because I think this is resolved (following the discussion above), but feel free to comment
