### ISSUE TITLE
Request: Better in-line documentation

### ISSUE THREAD

**Issue by pcgeek86** [docker/docker#20615]
The `docker` command line utility doesn't offer much help for its parameters.

For example, consider the following parameter, and help text:

```
> docker run --help
  ...
  --memory-reservation            Memory soft limit
  ...
```

- Is this a switch parameter, or do I need to pass in a value?
- What can / should I specify?
- What are the lower and upper limits?
- What is the data type for input?
- What unit of measure (if integer, float, double, etc.) is it? Megabytes? Litres? Gigabytes? Bytes?
- What does "memory soft limit" mean?

Of course, it doesn't make sense to be excessively wordy, but some basic guidance would be useful for those who are new to Docker. The less friction there is, the more people will be likely to adopt it.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by thaJeztah** [comment]
I think this is a duplicate of https://github.com/docker/docker/issues/18385.

**Comment by pcgeek86** [comment]
@thaJeztah Yep, you're right. Closing this one.
