### ISSUE TITLE
Request: Add JSON output to Docker commands

### ISSUE THREAD

**Issue by pcgeek86** [docker/docker#20625]
In the non-Windows command line, filtering, modifying, and sorting objects can be challenging. It would be great if the `docker` command line were able to emit JSON, instead of pre-formatted, tabular data. Then, utilities such as `jq` could be used to perform filtering, modification, and sorting on the JSON objects that are emitted by the `docker` command. This also works really well in scenarios where you want to perform batch operations with `docker` (eg. kill multiple containers), and want to use `xargs` to assist with that. By emitting JSON, instead of pre-formatted text, you reduce the boilerplate code that's necessary to parse values from output, and improve the confidence that developers have from the output.

The Microsoft Azure Cross-Platform (xPlat) CLI tool is a great example of this. For example, I can list Resource Groups  in a human-readable, tabular format, or I can use the standardized `--json` switch parameter to change the output to machine-readable JSON text. :heart:

https://github.com/Azure/azure-xplat-cli

If this capability already exists, please let me know how I can access it. :smile: 

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by duglin** [comment]
While I think some people who tell you to just use the REST APIs, I would like to +1 this idea. Allowing people to use the easy CLI interface but still get programmatic output would be really useful.

**Comment by cpuguy83** [comment]
Use the API.

**Comment by cpuguy83** [comment]
But seriously, I'd be fine if `--format` supported 'json` on `ps` like it does for inspect.

**Comment by pcgeek86** [comment]
The "use the API" argument kind of falls flat, in the sense that this proposal is intended to improve usability of the tool in its native form.

**Comment by calavera** [comment]
the `--format` flag can probably give you anything you need without using `jq`.

`docker ps --format "{{.ID}}" | xargs docker rm -f` is an alias for `docker ps -q | xargs docker rm -f`.

I agree with @cpuguy83, I'd be fine with adding `--format json` like we already have `--format table` and `--format raw`.

**Comment by pcgeek86** [comment]
The nice thing about emitting JSON is that it's interoperable with more software, whereas this formatting option you're exposing is somewhat proprietary to the Docker CLI. Using `docker` with `xargs` is just one example. What if you wanted to send JSON output from `docker` over to `curl`, so you could send it off to a web API? What if you wanted to add a custom, calculated property to JSON objects emitted from `docker`? The possibilities are endless, and providing this industry standard mechanism would help promote interoperability.

Cheers,
Trevor Sullivan

**Comment by HackToday** [comment]
@pcgeek86 did you want it json output with `docker ps` only ?

**Comment by cpuguy83** [comment]
@pcgeek86 Or you could just use the API.
CLI's are for humans, API's are for machines.

**Comment by pcgeek86** [comment]
@HackToday not just `docker ps`, but other commands that emit useful information, like `docker search` or `docker images`.

@cpuguy83 Just curious, if you are against emitting JSON, then why does `docker network inspect <NetworkName>` emit JSON?

Cheers,
Trevor Sullivan

**Comment by cpuguy83** [comment]
@pcgeek86 Look, I'm not arguing here.
> But seriously, I'd be fine if --format supported json on ps like it does for inspect.

**Comment by HackToday** [comment]
@cpuguy83 and @calavera  @thaJeztah  @duglin  seems we are happy to add this feature.
if we agree that, I 'd like to take it.

**Comment by HackToday** [comment]
Please let me know any disagreements.  Thanks

**Comment by HackToday** [comment]
#dibs

**Comment by cpuguy83** [comment]
Thanks @HackToday

**Comment by duglin** [comment]
@HackToday thanks! And I agree with @pcgeek86, we should do it for all commands.

**Comment by duglin** [comment]
A quick search of the various commands makes me think that we'd really only need to add it for (if not already there):
build (maybe), diff (maybe), history, images, info, logs, network, port, ps, search, stats, top (maybe), version, volume

the "maybe"s are because I'm not sure the current output is well suited for a json encoding.

As a side note, some other cloud tooling I've used have a TRACE type of env var that people can set that captures all tcp/ip traffic to a file. Typically for debugging, but also kind of useful in other situations. Might be worth exploring as well.

**Comment by pcgeek86** [comment]
@duglin @HackToday Nice, thanks.

**Comment by mikedougherty** [comment]
Why would there not be a standard layer of presentation for the CLI that interprets a "--format" parameter?

CLI output is also for piping to other processes. ;) Talking to the API also means duplicating all the TLS logic.

**Comment by seesharprun** [comment]
Another vote on a consistent presentation layer. If "--format" is implemented individually for each command or implemented inconsistently, it will just end up as another issue down the road filed by someone else as soon as someone implements a command without "--format json"

**Comment by HackToday** [comment]
hi All, and  @pcgeek86  for the json output,
take the `docker version` as example 


# docker version --format json

{
	"Client": {
		"Version": "1.11.0-dev",
		"API version": "1.23",
	},
	"Server": {
		"Version": "1.11.0-dev",
		"API version": "1.23"
}



Do we need to make the key same as `docker ps` CLI or make it changed to same as REST API (which means  "API Version" => "ApiVersion"  etc)?


I think your request need related json output same as CLI, so should be "API Version"


What do all you guys think?  Please input

**Comment by pcgeek86** [comment]
Hello @HackToday, thanks for asking this important question. In my opinion, JSON output should actually be consistent with the API. The user-friendly, tabular, pre-formatted output is where "display property" names should be should, not JSON. This is just my opinion, but curious to hear what others think.

Thanks @HackToday!

**Comment by HackToday** [comment]
@pcgeek86  Then it comes to two issues:

1) As I talked above `docker ps --format json` the output json key should be same as REST API json key  or CLI related keys

2) If 1) we make it same as REST API keys(use "ApiVersion"), then what's about the output?  should that keep same as REST API output or we ignore some output (for example,`docker ps` ignore related labels HostConfig which is in REST API /containers/json)

Personally, I think we should not keep the output same REST API, because if that case, user need to
call REST API instead of use CLI to archive that.

  if 1) we use it same as CLI related keys, (use"API Version"), then we need to design related output format for each docker commands, it also need discussed about it before implementation to make sure not waste efforts

**Comment by pcgeek86** [comment]
I understand what you're saying now, I think. Basically, what you are saying, is that there are two separate "keys" that mean the same thing, but they are formatted differently for the CLI than the REST API. When you say "key," are you comparing a REST API JSON property to a command or parameter on the CLI?

Unfortunately I am not involved deeply enough with Docker yet to understand which would be the most appropriate option. However, I do see a need for consistency on both sides.

**Comment by duglin** [comment]
IMO the `--format` flag should only change how the data is shown to the user, not what the data is. Meaning, the keys/columns should be same for json formatting as human-readable formatting. Now, things might change slightly if the format flag allows for the list of keys to be specified (like it does for 'ps') rather than just a "show me json" flag.

**Comment by HackToday** [comment]
@duglin  it seems you said we need keep keys same as CLI human-readable format, take `docker ps -a ` as example, 

Format A:
```
docker ps -a --format json
[
{
    "CONTAINER ID": "a73e86b279ee",
    "IMAGE": "busybox",
    "COMMAND": "sh",
    "CREATED": "15 minutes ago",
    "STATUS": "Up 15 minutes",
    "PORTS": {}
}
{
   ...
}
]
```


Is that case ?


Or you mean following Format B:

```
$ echo -e "GET /containers/json HTTP/1.0\r\n" | sudo nc -U /var/run/docker.sock  | sed -n '7p' | jq '.[0]'
{
  "Id": "0c9a26d208e525342e7765475ac6335c7efc08bb49a69d63d819a48723c39760",
  "Names": [
    "/cranky_goodall"
  ],
  "Image": "busybox",
  "ImageID": "sha256:3240943c9ea3f72db51bea0a2428e83f3c5fa1312e19af017d026f9bcf70f84b",
  "Command": "sh",
  "Created": 1456448091,
  "Ports": [],
  "Labels": {
    "foo": "work"
  },
  "Status": "Up 4 minutes",
  "HostConfig": {
    "NetworkMode": "default"
  }
}
```

This format B can be achieved with REST API or socket, so we should not do that work for users in docker side, I think.



Or you mean other case ? Please show us the example output of `docker ps`.  Thanks, It can help other know what's the expected result, and is it possible to do that in docker side.

**Comment by duglin** [comment]
@HackToday I was thinking of something like your first example (not with the keys in all caps), but you left off:
```
"Names": [ "foo", "bar" ]
```

**Comment by thaJeztah** [comment]
I wonder if that becomes really confusing if we have two different JSON formats

**Comment by HackToday** [comment]
@thaJeztah I agree it seems some confusing if introduced another JSON format. After more thoughts about it, and I suspect if we have many consumers would use that. :(

**Comment by duglin** [comment]
do we have two formats? Can you get json from ps today?

**Comment by thaJeztah** [comment]
@duglin meant the format the API returns (sorry for the confusion)

**Comment by duglin** [comment]
@thaJeztah right but that's a different API and if people want the full JSON they should use the REST API.  I think there are two ways to view the output (and this is just for `ps`):
1) its a subset of the full REST API
2) its just a different way to view the existing `ps` data
When viewed as 1 then having consistency with the REST API makes sense - but then I wonder why people aren't just using the REST API.
When viewed as 2, having some degree of consistency with the REST API might be ok but only if we don't add extra noise (like wrappers) just to enforce the consistency. I say this because the wrapper will probably not make sense to a user of cli ps.
I think we should take it on a field-by-field basis. In the case of `ps` I don't think there's much of a difference for the fields that it current returns so I think grabbing the REST APIs format for those fields will be fine.

**Comment by HackToday** [comment]
So @duglin  from your above comments, it seems you favor following format:
```
docker ps -a --format json
[
{
    "Container Id": "a73e86b279ee",
    "Image": "busybox",
    "Command": "sh",
    "Created": "15 minutes ago",
    "Status": "Up 15 minutes",
    "Ports": {},
    "Names": [ "foo", "bar" ]
}
{
   ...
}
]
```

Is it ? 
At the same time, we know that @duglin , even `ps` still have different format, like `Id` which is `Container Id` here if we follows CLI keys property.

**Comment by duglin** [comment]
In the case of `Id` vs `Container Id` I think `Id` is fine for the json.

**Comment by crosbymichael** [comment]
For something like Docker where the cli is just talking it a daemons remote API it is not ideal to expose all of this via the CLI.  When you want the api json, just hit the api.  

For things like runc, we do expose json via the cli but there is no daemon backing it with an api that a user can hit if they want to parse the output but for docker this is already possible.

**Comment by dnephin** [comment]
We are always interested in specific issues with the API that make it inconvenient to use directly. If you have any such issues please comment in #5893

**Comment by beetree** [comment]
Great feature request, sorry it's not being done. To give an idea, this page is the 6th result on Google if you search for `docker json`. People want this, consider adding it!

**Comment by thaJeztah** [comment]
@beetree looks like this is working with docker 1.13;

```
docker ps --format '{{ json . }}' | jq .
{
  "Command": "\"sh\"",
  "CreatedAt": "2017-01-02 15:45:43 +0000 UTC",
  "ID": "d0868fc33de9",
  "Image": "busybox",
  "Labels": "",
  "LocalVolumes": "0",
  "Mounts": "",
  "Names": "pedantic_yonath",
  "Networks": "bridge",
  "Ports": "",
  "RunningFor": "5 minutes",
  "Size": "0 B",
  "Status": "Up 5 minutes"
}
{
  "Command": "\"sh\"",
  "CreatedAt": "2017-01-02 15:45:27 +0000 UTC",
  "ID": "4e387ea87db7",
  "Image": "busybox",
  "Labels": "",
  "LocalVolumes": "0",
  "Mounts": "",
  "Names": "inspiring_mclean",
  "Networks": "bridge",
  "Ports": "",
  "RunningFor": "5 minutes",
  "Size": "0 B",
  "Status": "Up 5 minutes"
}
```

**Comment by beetree** [comment]
Oh, nice. Thanks @thaJeztah

**Comment by jaytaylor** [comment]
@thaJeztah Does it only work with 1.13+?

```bash
sudo docker ps --format '{{ json . }}'
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
```

```bash
sudo docker version
Client:
 Version:      1.12.6-medallia
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   2a2ad81
 Built:        Sat Jan 14 00:41:17 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6-medallia
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   2a2ad81
 Built:        Sat Jan 14 00:41:17 2017
 OS/Arch:      linux/amd64
```

**Comment by jaytaylor** [comment]
Also, FWIW, this works for getting `PS` data in JSON format nicely, too (even with "older" versions of docker!):

```bash
sudo curl -sS --unix-socket /var/run/docker.sock http:/containers/json
```

**Comment by thaJeztah** [comment]
Correct, that's the Docker API; for full documentation, see https://docs.docker.com/engine/api/, and https://docs.docker.com/engine/api/v1.26/

**Comment by jhoblitt** [comment]
AFAIK, there is no way to get the api's json responses out of `docker build`.  This is a real PITA as that is essentially the most complicated CLI command to implement.

**Comment by eklitzke** [comment]
The current implementation is basically useless because it doesn't many any attempt to make the JSON output machine readable. The command name is truncated with ellipses, and it still includes human formatted relative time fields. The whole point of JSON formatted output is to provide a representation that's useful for machines, instead, this just emits human formatted output stuffed into JSON blocbs.

**Comment by kgeorge314** [comment]
After a bit of googling and considering this is the top result for `docker ps json`. I hope the below will help others looking for a solution. 

On `Docker version 18.06.1-ce, build e68fc7a`
` docker ps --all --no-trunc --format '{{ json . }}'`

**Comment by thaJeztah** [comment]
Yes, see the example higher up this page; https://github.com/moby/moby/issues/20625#issuecomment-269989174

**Comment by kgeorge314** [comment]
> Yes, see the example higher up this page; [#20625 (comment)](https://github.com/moby/moby/issues/20625#issuecomment-269989174)

Thanks, @thaJeztah, your comment is what inspired me and is what I used initially but I had the same problem mentioned [here](https://github.com/moby/moby/issues/20625#issuecomment-412219684) and when I added in the `--no-trunc` it worked perfectly for me.

In the process, I also learned that `--format {{ json . }}` works for other commands too :)

**Comment by artipixel** [comment]
Got also some inspiration from the comments-
If you want this as a valid JSON array - working with string replaces can do the trick.
Example for using docker images (you can change it to whatever)
`images=$(docker images --format "{{json . }}" | jq .) && pat="}{" && rep="},{" && echo \[${images//$pat/$rep}\]
`

It's done using bash replace ` ${parameter//pattern/string} `

**Comment by daytonpa** [comment]
I disagree that this is properly formatted JSON, as referenced [here](https://github.com/moby/moby/issues/20625#issuecomment-269989174).  For use with `jq`s internal functions, this output breaks `jq`.

`docker ps -a --format '{{json .}}'` does return all stopped containers as JSON, but not as a JSON array.   It's returning each JSON object as it's own unique string that `jq` has no clue how to iterate over.

As an example, let's say I have 5 stopped containers across 2 images, and I would like to delete all containers associated to the desired image's ID. Running the following command with `jq` will not work:
```
$ docker rm $(docker ps -a --no-trunc --format '{{json .}' | jq -r '.[] | if (.Image == <DESIRED_ID>) then .ID else empty end'
```

If multiple container IDs are returned with the `--format {{json .}}', it would be ideal to have it returned as an array object.

**Comment by mikedougherty** [comment]
@daytonpa i *think* that would be a good use case for `jq`'s `-s` option -- i've used it in the past for other APIs/output streams that emit a single object on each line. hope that helps

**Comment by daytonpa** [comment]
You're correct.  That worked.  [Thank you for the tip!](https://i.imgur.com/xFrJtHx.gif).

**Comment by pcgeek86** [comment]
Yeah, one JSON object per-line isn't what I'd consider outputting "valid JSON." Both `jq` and PowerShell's native `ConvertFrom-Json` command puke with this. However, if you're using PowerShell to parse objects, you can just pipe the `docker ps ...` output into a `ForEach-Object` (alias: `%`) loop first. That way, you're only feeding one JSON object into `ConvertFrom-Json` each iteration.

Here's an example of how that works on my MacBook:

```
PS /Users/trevor> docker ps --format '{{ json . }}' --all | % { ConvertFrom-Json $_ } | Format-Table -Property ID, Image, Names, Networks

ID           Image                                               Names              Networks
--           -----                                               -----              --------
16183cd8ddd0 docker.elastic.co/beats/filebeat:6.5.4              nostalgic_chaum    host
5db260566f75 docker.elastic.co/beats/filebeat:6.5.4              awesome_johnson    host
6c125f156f58 docker.elastic.co/beats/filebeat:6.5.4              quizzical_easley   bridge
1410a07b2207 docker.elastic.co/beats/filebeat:6.5.4              tender_easley      bridge
a32d1b8472e9 docker.elastic.co/beats/filebeat:6.5.4              elegant_galois     bridge
48411483b13d docker.elastic.co/elasticsearch/elasticsearch:7.1.1 mystifying_meitner bridge
ee4e2ec3ff70 redis                                               redis              bridge
```

**Comment by Radiergummi** [comment]
What is the rationale for returning a list of JSON objects instead of an array..? The way it is, the JSON  output is useful to copy-paste individual containers from the command line, nothing more. This is pretty frustrating - at the dawn of 2019, you'd expect one of the most popular CLI tools to support trivial JSON output.
