### ISSUE TITLE
timeouts pulling images

### ISSUE THREAD

**Issue by keviocastro** [docker/docker#20628]
command: docker pull hello-word
Result: Error parsing HTTP response: invalid character '<' looking for beginning of value: "408 Request Time-out Your browser didn't send a complete request in time"

Problem similar: https://github.com/docker/docker/issues/15949
This problem still occurs to me.
I changed the MTU to 1500 and not solved.

docker --version
Docker version 1.10.1, build 9e83765

docker info
Containers: 0
Running: 0
Paused: 0
Stopped: 0
Images: 0
Server Version: 1.10.1
Storage Driver: aufs
Root Dir: /var/lib/docker/aufs
Backing Filesystem: extfs
Dirs: 0
Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
Volume: local
Network: bridge null host
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.714 GiB
Name: kevio
ID: E26Z:TZU6:MAIS:RNVO:DLH4:MUKD:H3HQ:PRMR:C4YY:POKF:PQL7:KBZL
WARNING: No swap limit support

uname -a
Linux kevio 4.2.0-27-generic #32-Ubuntu SMP Fri Jan 22 04:49:08 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
ubuntu 15.10

ifconfig
docker0 Link encap:Ethernet HWaddr 02:42:14:6b:72:6c

inet addr:172.17.0.1 Bcast:0.0.0.0 Mask:255.255.0.0
UP BROADCAST MULTICAST MTU:1500 Metric:1
RX packets:0 errors:0 dropped:0 overruns:0 frame:0
TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:0 
RX bytes:0 (0.0 B) TX bytes:0 (0.0 B)

wlp1s0 Link encap:Ethernet HWaddr 94:65:9c:6f:68:4b

inet addr:192.168.7.107 Bcast:192.168.7.255 Mask:255.255.255.0
inet6 addr: fe80::9665:9cff:fe6f:684b/64 Scope:Link
UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
RX packets:47 errors:0 dropped:0 overruns:0 frame:0
TX packets:104 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1000 
RX bytes:12517 (12.5 KB) TX bytes:15984 (15.9 KB)

lo Link encap:Local Loopback

inet addr:127.0.0.1 Mask:255.0.0.0
inet6 addr: ::1/128 Scope:Host
UP LOOPBACK RUNNING MTU:65536 Metric:1
RX packets:254 errors:0 dropped:0 overruns:0 frame:0
TX packets:254 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:0 
RX bytes:22692 (22.6 KB) TX bytes:22692 (22.6 KB)

**Comment by HackToday** [comment]
did you restart docker after change the MTU in config file?

**Comment by underoot** [comment]
Similar problem
```
docker --version
Docker version 1.10.2, build c3959b1

docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.10.2
Storage Driver: devicemapper
 Pool Name: docker-8:5-393462-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 11.8 MB
 Data Space Total: 107.4 GB
 Data Space Available: 59.31 GB
 Metadata Space Used: 581.6 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.115 (2016-01-25)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.1-2-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.069 GiB
Name: udesktop
ID: 6ATG:FT7X:MFHY:YEJB:7T22:ZVMZ:L7MQ:4GYR:ZDQX:OHTC:DP7E:RW4H
Username: underoot
Registry: https://index.docker.io/v1/
```

**Comment by keviocastro** [comment]
@HackToday i restarted.

I tried two ways

1:
sudo /sbin/ifconfig wlp1s0 mtu 1500 up
sudo service networking restart
sudo service docker restart

2:
I also changing the setting at /etc/network/interfaces
sudo service networking restart
sudo service docker restart

**Comment by HackToday** [comment]
@keviocastro  I think docker service have options to set MTU, 
```
[centos@centostest ~]$ docker daemon --help | grep mtu
  --mtu                                    Set the containers network MTU
```

You manual change it with ifconfig, I think it is not quite same

**Comment by alanbrent** [comment]
We're seeing the same issue with 1.10.3 on a host running a single container. The container is doing ~1.5Gbps of network traffic, FYI. We are running with `--mtu=1500` and that has not solved the issue. Please see the info linked below.

[Docker commands, Docker Info, and strace](https://gist.github.com/alanbrent/37ff29750b19db7d64c9)

**Comment by alanbrent** [comment]
FYI We fixed this by setting the "physical" interface to `mtu 1500`. It appears that this is a necessary component, though now I'm not sure if the `--mtu=1500` flag is necessary. It's currently on, but again not sure if it's necessary. @keviocastro are you still seeing this issue?

**Comment by keviocastro** [comment]
The problem does not occur to me after I changed my office that has other infrastructure.
I'm not having more problems.
I never investigate what was causing the problem in the old infrastructure.
Anyone here have a problem with it yet?

**Comment by thaJeztah** [comment]
@keviocastro thanks for reporting back. I'll close this issue then, thanks!

**Comment by bumblebeen** [comment]
hi, sorry for long post so here it is
I didnt have any problems yesterday with pulling, just had this issue now. Didnt do anything with my machine but i managed to have a work around it.

First off, I set the /etc/default/docker with the value 
`DOCKER_OPTS="--mtu 1500"`
and restart docker daemon base from docs https://docs.docker.com/engine/reference/commandline/daemon/

Sadly, I still cant pull even setting it. So I was wondering maybe it doesnt see DOCKER_OPTS so
I modified /lib/systemd/system/docker.service and add
```
[Service]
EnvironmentFile=/etc/default/docker
ExecStart=/usr/bin/docker -d -H fd:// $DOCKER_OPTS
```
I still cant pull. So question stays the same, why doesn't it see the docker_opts

BUT when I manualy used the flag
`sudo service docker stop`
`sudo docker daemon --mtu=1500`
open another terminal and docker pull. it works. I'm wondering is this issue with docker or just my setup , im using Docker version 1.10.1 and Ubuntu 14.04

**Comment by alanbrent** [comment]
@bumblebeen The issue didn't resolve for us until we set the actual interface (eth0, p1p2, etc) to MTU 1500. e.g. `ifconfig eth0 mtu 1500 up`

**Comment by thaJeztah** [comment]
@bumblebeen make sure you do `sudo systemctl daemon-reload` after making changes to the systemd unit file or drop-in files, otherwise systemd won't use the updated settings

**Comment by Schwankenson** [comment]
I have the same problem. I set the MTU to 1500, the probolem persists.

I started deamon manually with "sudo docker daemon -D --mtu=1500". Then I called "sudo docker run hello-world". Output of the docker daemon is:

    DEBU[0042] form data: {"AttachStderr":true,"AttachStdin":false,"AttachStdout":true,"Cmd":null,"Domainname":"","Entrypoint":null,"Env":[],"HostConfig":{"AutoRemove":false,"Binds":null,"BlkioBps":0,"BlkioDeviceReadBps":null,"BlkioDeviceReadIOps":null,"BlkioDeviceWriteBps":null,"BlkioDeviceWriteIOps":null,"BlkioIOps":0,"BlkioWeight":0,"BlkioWeightDevice":null,"CapAdd":null,"CapDrop":null,"Cgroup":"","CgroupParent":"","ConsoleSize":[0,0],"ContainerIDFile":"","CpuCount":0,"CpuPercent":0,"CpuPeriod":0,"CpuQuota":0,"CpuShares":0,"CpusetCpus":"","CpusetMems":"","Devices":[],"DiskQuota":0,"Dns":[],"DnsOptions":[],"DnsSearch":[],"ExtraHosts":null,"GroupAdd":null,"IpcMode":"","Isolation":"","KernelMemory":0,"Links":null,"LogConfig":{"Config":{},"Type":""},"Memory":0,"MemoryReservation":0,"MemorySwap":0,"MemorySwappiness":-1,"NetworkMode":"default","OomKillDisable":false,"OomScoreAdj":0,"PidMode":"","PidsLimit":0,"PortBindings":{},"Privileged":false,"PublishAllPorts":false,"ReadonlyRootfs":false,"RestartPolicy":{"MaximumRetryCount":0,"Name":"no"},"SandboxSize":0,"SecurityOpt":null,"ShmSize":0,"StorageOpt":null,"UTSMode":"","Ulimits":null,"UsernsMode":"","VolumeDriver":"","VolumesFrom":null},"Hostname":"","Image":"hello-world","Labels":{},"NetworkingConfig":{"EndpointsConfig":{}},"OnBuild":null,"OpenStdin":false,"StdinOnce":false,"Tty":false,"User":"","Volumes":{},"WorkingDir":""} 
    ERRO[0042] Handler for POST /v1.23/containers/create returned error: No such image: hello-world:latest 
    DEBU[0042] Calling GET /v1.23/info                      
    DEBU[0042] Calling POST /v1.23/images/create?fromImage=hello-world&tag=latest 
    DEBU[0042] Trying to pull hello-world from https://registry-1.docker.io v2 
    DEBU[0043] Increasing token expiration to: 60 seconds   
    ERRO[0418] Error trying v2 registry: error parsing HTTP 408 response body: invalid character '<' looking for beginning of value: "<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n\n" 
    ERRO[0418] Attempting next endpoint for pull after error: error parsing HTTP 408 response body: invalid character '<' looking for beginning of value: "<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n\n" 
    DEBU[0418] Skipping v1 endpoint https://index.docker.io because v2 registry was detected 
    ERRO[0418] Handler for POST /v1.23/images/create returned error: error parsing HTTP 408 response body: invalid character '<' looking for beginning of value: "<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n\n" 
    ERRO[0446] Error trying v2 registry: error parsing HTTP 408 response body: invalid character '<' looking for beginning of value: "<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n\n" 
    ERRO[0446] Attempting next endpoint for pull after error: error parsing HTTP 408 response body: invalid character '<' looking for beginning of value: "<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n\n" 
    DEBU[0446] Skipping v1 endpoint https://index.docker.io because v2 registry was detected 
    ERRO[0446] Handler for POST /v1.23/images/create returned error: error parsing HTTP 408 response body: invalid character '<' looking for beginning of value: "<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n\n" 

ifconfig shows:

    docker0   Link encap:Ethernet  HWaddr 02:42:ef:c5:87:4c  
              inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
              UP BROADCAST MULTICAST  MTU:1500  Metric:1
              RX packets:0 errors:0 dropped:0 overruns:0 frame:0
              TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
              collisions:0 txqueuelen:0 
              RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

    eth0      Link encap:Ethernet  HWaddr bc:5f:f4:98:2d:6d  
              inet addr:192.168.0.10  Bcast:192.168.0.255  Mask:255.255.255.0
              inet6 addr: 2a02:908:1860:d140:f0de:a038:d372:c535/64 Scope:Global
              inet6 addr: fe80::be5f:f4ff:fe98:2d6d/64 Scope:Link
              inet6 addr: 2a02:908:1860:d140:be5f:f4ff:fe98:2d6d/64 Scope:Global
              UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
              RX packets:123538 errors:0 dropped:0 overruns:0 frame:0
              TX packets:94210 errors:0 dropped:0 overruns:0 carrier:0
              collisions:0 txqueuelen:1000 
              RX bytes:115345852 (115.3 MB)  TX bytes:17724675 (17.7 MB)
              Interrupt:28 

    lo        Link encap:Local Loopback  
              inet addr:127.0.0.1  Mask:255.0.0.0
              inet6 addr: ::1/128 Scope:Host
              UP LOOPBACK RUNNING  MTU:65536  Metric:1
              RX packets:9810 errors:0 dropped:0 overruns:0 frame:0
              TX packets:9810 errors:0 dropped:0 overruns:0 carrier:0
              collisions:0 txqueuelen:0 
              RX bytes:1059025 (1.0 MB)  TX bytes:1059025 (1.0 MB)

    vboxnet0  Link encap:Ethernet  HWaddr 0a:00:27:00:00:00  
              inet addr:192.168.50.1  Bcast:192.168.50.255  Mask:255.255.255.0
              inet6 addr: fe80::800:27ff:fe00:0/64 Scope:Link
              UP BROADCAST MULTICAST  MTU:1500  Metric:1
              RX packets:0 errors:0 dropped:0 overruns:0 frame:0
              TX packets:78 errors:0 dropped:0 overruns:0 carrier:0
              collisions:0 txqueuelen:1000 
              RX bytes:0 (0.0 B)  TX bytes:10833 (10.8 KB)


docker --version

    Docker version 1.11.0, build 4dc5990

docker info
    Containers: 0
     Running: 0
     Paused: 0
     Stopped: 0
    Images: 0
    Server Version: 1.11.0
    Storage Driver: aufs
     Root Dir: /var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 0
     Dirperm1 Supported: true
    Logging Driver: json-file
    Cgroup Driver: cgroupfs
    Plugins: 
     Volume: local
     Network: bridge null host
    Kernel Version: 4.2.0-34-generic
    Operating System: Ubuntu 14.04.4 LTS
    OSType: linux
    Architecture: x86_64
    CPUs: 8
    Total Memory: 15.63 GiB
    Name: jo-desktop
    ID: QIEV:TZWL:6WXU:VFEX:ZUQT:N5TI:L5Y3:TEVD:FDB6:Y7S2:V55D:MDI2
    Docker Root Dir: /var/lib/docker
    Debug mode (client): false
    Debug mode (server): true
     File Descriptors: 11
     Goroutines: 35
     System Time: 2016-04-15T11:46:26.552545037+02:00
     EventsListeners: 0
    Registry: https://index.docker.io/v1/
    WARNING: No swap limit support

uname -a

    Linux jo-desktop 4.2.0-34-generic #39~14.04.1-Ubuntu SMP Fri Mar 11 11:38:02 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Schwankenson** [comment]
Ok, I solved it: I had to set the MTU of my network interface down to 900.

**Comment by vyachkonovalov** [comment]
@Schwankenson Thank you, setting mtu to 900 solved the problem in my case too

**Comment by nikolasd** [comment]
I had the same problem, but in my case I had no debug information on the console. I managed to get the error message from syslog. The problem appeared on Ubuntu 16.04 with docker version

    Client:
     Version:      1.12.1
     API version:  1.24
     Go version:   go1.6.3
     Git commit:   23cf638
     Built:        Thu Aug 18 05:33:38 2016
     OS/Arch:      linux/amd64
    
    Server:
     Version:      1.12.1
     API version:  1.24
     Go version:   go1.6.3
     Git commit:   23cf638
     Built:        Thu Aug 18 05:33:38 2016
     OS/Arch:      linux/amd64

I am commenting just to inform that changing MTU on my physical interface from 1500 to 900 worked for me.

    enp1s0    Link encap:Ethernet  HWaddr 00:00:00:00:00:00
              inet addr:192.168.0.10  Bcast:192.168.0.255  Mask:255.255.255.0
              UP BROADCAST RUNNING MULTICAST  MTU:900  Metric:1
              RX packets:65471 errors:0 dropped:0 overruns:0 frame:0
              TX packets:49495 errors:0 dropped:0 overruns:0 carrier:0
              collisions:0 txqueuelen:1000
              RX bytes:37831214 (37.8 MB)  TX bytes:8578823 (8.5 MB)
              Interrupt:16

**Comment by wzhaojin** [comment]
> BUT when I manualy used the flag
> sudo service docker stop
> sudo docker daemon --mtu=1500
> open another terminal and docker pull. it works. I'm wondering is this issue with docker or just my setup , im using Docker version 1.10.1 and Ubuntu 14.04

I changed the /etc/init.d/docker file, added the mtu flag using:
`DOCKER_OPTS=" --mtu=1500 " `
After reboot the ubuntu, the problem was not exist.

**Comment by hiddengearz** [comment]
> The issue didn't resolve for us until we set the actual interface (eth0, p1p2, etc) to MTU 1500. e.g. ifconfig eth0 mtu 1500 up

4 years later and this resolved my issue. Thanks!
