### ISSUE TITLE
How do you mount sub-containers volumes from a CI server container ? 

### ISSUE THREAD

**Issue by Julio-Guerra** [docker/docker#20624]
Hi,

I an using docker for my dev environment: I have a dev image and I mount my source files as a volume. It works perfectly and it's awesome ;)

But then I wanted to do the same on my continuous integration server (gitlab ci) and I carefully read @jpetazzo https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/ but the solution of bind-mounting docker's unix socket makes impossible mounting volumes from a container.

So basically my question is how would you solve this (given I am in a docker ci server/runner): I need to run the following command from a container (a gitlab runner).

> $ git clone ... my-sources && cd my-sources
> $ docker run my-dev-image -v $PWD:$PWD -w $PWD gcc main.c

Because obviously, the volume is taken from docker's "native" host and not the current container.

Related: http://stackoverflow.com/questions/31381322/docker-in-docker-cannot-mount-volume

Thanks

**Comment by cpuguy83** [comment]
Don't use volumes-from. Instead use "named" volumes for important data that you need to share.

Closing as this isn't really an issue.
