### ISSUE TITLE
Docker 1.10 Clients getting invalid checksum digest format

### ISSUE THREAD

**Issue by kitsushadow** [docker/docker#20622]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

Client Version: Docker version 1.10.2, build c3959b1

Client Info: 
docker info
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 35
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 151
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.19.0-32-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.828 GiB
Name: kitsu-vm
ID: PA5B:F4WI:OSK6:5QK3:SL4U:TEPN:AIOZ:DQ5K:TIDS:O44U:4AZB:7A5A
Http Proxy: http://xx.xxx.xxx.xx:XXXX/
WARNING: No swap limit support

ADDITIONAL INFORMATION:
We are using Nexus Registry 3.0 Milestone 7

List the steps to reproduce the issue:
1. docker push DNS.NAME/myimage
docker push DNS.NAME/myimage
The push refers to a repository [DNS.NAME/myimage]
bdd002057d95: Layer already exists 
9c58d769b51b: Layer already exists 
455288a965c7: Layer already exists 
a9c99cf8986e: Layer already exists 
d559eb689658: Layer already exists 
e7ad9846a11c: Layer already exists 
00cdb46fd1c7: Layer already exists 
5f70bf18a086: Layer already exists 
invalid checksum digest format

Describe the results you expected:
Expecting a rehash of the checksum by the client and the Docker Nexus Registry to approve just like when I pushed from a 1.10 client to a 1.9 Private Registry

**Comment by thaJeztah** [comment]
Have you also opened an issue at Sonatype?

/cc @peterlynch for sonatype

**Comment by kitsushadow** [comment]
yes https://issues.sonatype.org/browse/NEXUS-9766
someone else opened it but i added on to it

**Comment by kitsushadow** [comment]
@peterlynch Any update or comment on this issue or 
https://issues.sonatype.org/browse/NEXUS-9766
would be greatly welcome. We haven't heard any news regarding the status of this issue.

**Comment by peterlynch** [comment]
Sonatype is working on a fix for nexus 3. See [issue update](https://issues.sonatype.org/browse/NEXUS-9766?focusedCommentId=347853&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-347853)

**Comment by thaJeztah** [comment]
Thanks for the update, @peterlynch

**Comment by thaJeztah** [comment]
I'll close this issue as this should be  / will be fixed in the sonatype registry
