### ISSUE TITLE
linux32 emulation fails in docker build (v1.10+)

### ISSUE THREAD

**Issue by injectives** [docker/docker#20634]
Hello everyone.

Starting from Docker v1.10 my build has stopped building the right image, it installs the wrong packages.
The problem is that I need to install some 32bit packages and I am using `RUN linux32 yum install.....` in my Dockerfile.
On Docker v1.9.1 `linux32 arch` command returns i686 and yum installation works fine.
But staring from Docker v1.10 `linux32 arch` returns x86_64.
There are also 32bit images on the Hub that use linux32 as an Entrypoint, as I understand they won't work as well.

Output of `docker version`:

Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        2016-02-22T22:37:33.778002647+00:00
 OS/Arch:      linux/amd64

Output of `docker info`:

Containers: 0
Images: 1
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 4
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.18-boot2docker
Operating System: Boot2Docker 1.10.2 (TCL 6.4.1); master : 611be10 - Mon Feb 22 22:47:06 UTC 2016
CPUs: 1
Total Memory: 996.1 MiB
Name: default
ID: KEC5:K5P7:VKR7:YBLP:YS2L:NLTY:2PII:GKHH:RRCQ:JBSZ:QOJM:HNX6
Debug mode (server): true
 File Descriptors: 14
 Goroutines: 22
 System Time: 2016-02-23T23:24:08.889412265Z

Steps to reproduce:
1. Create Docker Machine from Boot2Docker version 1.10.2 (Docker version 1.10.2)
2. docker run --rm -ti centos bash
3. linux32 arch

Expected: i686
Actual: x86_64

It is possible to make it work by using docker run option `--security-opt=seccomp:unconfined` or `--privileged`. BUT none of those is available for the docker build command.

On the Boot2Docker version 1.9.1 (Docker version 1.9.1), the build works fine.

I believe it might be related to the [default seccomp profile](https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities), that was introduced in v1.10.
Would it be possible to use a custom profile for the build command or turn the feature off without recompiling the kernel configuration? There can be other cases when the installation requires some additional features and it would help to have the opportunity to override the default profile for the build command.

**Comment by justincormack** [comment]
The `linux32` command calls `setarch` which uses the `personality(2)` syscall, which is indeed not permitted in the default seccomp profile; this is partly because there have been several security issues related to `personality`. I don't think this was noticed in testing as I guess no one built or ran anything tat uses the wrapper.

So I guess there are three questions:
(a) should `personality` be allowed (or some arguments to it) in the default profile
(b) should build be allowed to specify seccomp flags

I think for (a) there may be a valid subset we could allow (ie the 32 bit switch), I need to look at the code of the `setarch` program and see what it is using (I think it is only this syscall which is the issue), and check the relevant CVEs (which I think are mainly against non-Linux emulations).

For (b) I hadnt really considered it, I am not sure I thought the `build` code was using seccomp, will look more closely.

**Comment by cpuguy83** [comment]
@justincormack the build code uses a default container config + the available customizations like cgroup settings and such.

My original thought is security-opts on build should be ok... but after some thought I'm worried that a build (even if it has to be explicitly set) could modify the host in some way that would make the image non-portable... which such host modifications is really what the default seccomp profile is helping to prevent.

**Comment by justincormack** [comment]
@cpuguy83 I could imagine some useful security rules on build, and even a more restrictive security profile being useful eg you can't run a network server, or even no network traffic at all, or drop capabilities so you could not do say `mknod`. But weakening confinement on build seems bad.

**Comment by justincormack** [comment]
I think it would be ok to whitelist the following values for `personality(2)`:

```
0xffffffff - read
0x0  - PER_LINUX (default)
0x0008 - PER_LINUX32
```

I think these are all that are actually needed, and this does not allow the dubious things (like turn off ASLR!) that `personality` also allows. I will test a patch with these added.

**Comment by injectives** [comment]
Thank you for looking at this.
If it is safe to whitelist this in the default profile then it is great.
But on the other hand I suppose there might be other cases when people will want to use certain syscalls in the build phase. Maybe it makes sense to consider opportunity to supply custom profiles for the build commands? In such case it will be up to the user to think about security and portability issues.

**Comment by justincormack** [comment]
The pull request linked here seems to resolve this for me, and I think it is fine from the security point of view.

In terms of the general issue, yes maybe, but some specific examples would help; there are other issues eg would it be supported for automated builds on hub? If we can avoid it then it is much simpler.

**Comment by injectives** [comment]
Thank you very much :+1:

**Comment by injectives** [comment]
Here is one example in terms of general issue. :)
Oracle-XE 10g won't start in the build phase.
```
sqlplus -s /nolog
connect "SYS"/"&&sysPassword" as SYSDBA
startup no mount
ORA-27125: unable to create shared memory segment
Linux Error: 1: Operation not permitted
```
So basically it is not possible to start the DB and populate it with data in a build phase.

**Comment by justincormack** [comment]
I think the Oracle startup is fixable, looks like (without testing) it is either trying to the required set `sysctl` options or mount `hugetlbfs`, but if you make sure these are set up first it should be ok. There should not be directly any issue with setting up shared memory, this is a supported operation.

**Comment by injectives** [comment]
I can see your point, but on the other hand how to achive opportunity to build something with Oracle 10? Maybe I haven't understood completely what you meant, could you explain please? What to do when the DB must be modified in the build?

**Comment by cpuguy83** [comment]
Why would you want to modify the db during build? This is not good practice.

**Comment by injectives** [comment]
Correct me if I am wrong, but images are about software and there is a question what is a software in each case. In the case I am discussing it is not just about having a DB. It is about going through imports and possibly other configurations to build image that you can just run and use. Having only plain DB means that you have to move all other parts into the run phase and in such case the build is not very useful....

**Comment by justincormack** [comment]
I think the issue of doing builds with Oracle is slightly off topic, as it remains to be demonstrated that it is not possible with the right configuration anyway, for reasonable use cases, and if it doesnt it is unclear what the fix is, and there are good reasons for not adding a lot of options to build if it is not needed.

**Comment by unclejack** [comment]
Oracle has been brought up a while ago as well. Perhaps it might be a good idea for the Oracle DBMS to not make the assumption that it's able to change all those settings on its own.

**Comment by injectives** [comment]
Unfortunately startup strace log doesn't show anything suspicious and on the other hand if the default profile is disabled everything works fine. Is it worth creating a dedicated issue for this?

**Comment by justincormack** [comment]
Yes, that would be better on a different issue. If you could paste the `strace -f` log that would be helpful. My guess would be `sysctl`, `mount` or possibly something around sizing of shared memory

**Comment by justincormack** [comment]
This should be resolved in master now.

**Comment by thaJeztah** [comment]
@justincormack fixed by https://github.com/docker/docker/pull/20672, I guess?

**Comment by thaJeztah** [comment]
@injectives if you want to give it a spin, master builds can be found at https://master.dockerproject.org for testing

**Comment by injectives** [comment]
@thaJeztah Checked on current version using the new profile from master, it works.
@justincormack Thank you for the fix! :)
Thank you all very much!

**Comment by thaJeztah** [comment]
Great! Thanks for reporting and testing :+1:
