### ISSUE TITLE
Relationship of [rw|ro] and the propagation options for volume

### ISSUE THREAD

**Issue by jay-lau** [docker/docker#20645]
Can anyone please show me the relationship of [rw|ro] and [[r]shared|[r]slave|[r]private]? I found that I cannot use both options in [rw|ro] and [[r]shared|[r]slave|[r]private] in one command.

**Comment by thaJeztah** [comment]
How did you provide the options? This seems to work fine for me;

    docker run -v /foobar:/foobar:ro,private -it --rm ubuntu

**Comment by jay-lau** [comment]
thanks, I should use "," instead.
