### ISSUE TITLE
Bridge Docker Network between Linux and Windows Hosts

### ISSUE THREAD

**Issue by teknowmics** [docker/docker#20650]
Hello,

Could someone please let me know if I can setup Bridge network between Linux docker Host and Windows Host.

Scenario : 

Linux Machine : IP assigned to eth0 is 192.168.1.10
Windows Machine : IP assigned to Network Interface is 192.168.1.20

Say, I have installed docker on Linux Host. IP assigned by docker daemon on Linux Host is 172.17.0.1

IP assigned by docker on Application container is 172.17.0.2

Is there any way I can configure Bridge network in Windows Machine and assign a IP lets say, 172.17.0.4 so it can communicate with docker application container directly ?

**Comment by cpuguy83** [comment]
If the two machines can talk to each other, then all you need do is setup routes so host 1 knows how to reach the container network on host 2 (and vice-versa).
