### ISSUE TITLE
how to change docker machine ip

### ISSUE THREAD

**Issue by 404Ghost99** [docker/docker#20667]
hi i am new to docker, i am confused to change default ip address given when iam create a new Docker Machine and a local VM, anybody can help me please, sorry for my bad english :)

**Comment by cpuguy83** [comment]
Hello, this is not the right place for such an issue.
The please file issues with machine in github.com/docker/machine.

As far as changing a machine's IP -- this is going to be dependant upon the driver being used to create the machine and would generally be exposed as an option while creating the machine.
