### ISSUE TITLE
Docker bridge network, HTTP calls between containers VERY slow (after docker upgrade)

### ISSUE THREAD

**Issue by CollinEstes** [docker/docker#20661]
Output of `docker version`:

```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64
```

Output of `docker info`:

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 51
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 50
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 3.13.0-76-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.676 GiB
Name: ip-138-76-35-34
ID: KS7N:MKHD:CHF6:LIQX:ANZW:AJ4R:6EJX:HJXJ:B4IL:ME3N:WBZP:4VNR
Http Proxy: http://proxy.myproxy.com:8888/
Username: myusername
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):

Running on AWS gov Cloud.

List the steps to reproduce the issue:
**Specific to my ENV at the moment will work on a reproducible setup.**

DESCRIPTION OF ISSUE:
Just recently upgraded from 1.9 to 1.10 and added docker-compose (not using compose yet however).  The slowness issue didn't occur prior to upgrade.
    
Also Docker is configured with my DNS IP and proxy like so in '/etc/default/docker'

```
    DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4 --dns 138.XX.XX.X"
    export http_proxy="http://proxy.myproxy.com:8888/"
```
(*my ip is fully spelled out there, just using X's for question*)

I have two containers (container_a, container_b) both running HTTP servers (Node.js), both containers are running on a bridge network (--net=mynetwork) I created via:
```
    docker network create mynetwork
```

The two containers make HTTP calls between one another using the container_name as the "host" for the HTTP calls like so:
```
    container_b:3000/someurl
```

These calls made between the two containers over the docker bridge network are taking a very long time to complete (~5 seconds).  These calls typically run under 100ms.  

When I change the networking from --net=mynetwork on those containers and instead run them both as --net=host, while also modifying my http calls to use "localhost" as the host instead of the container name and exposing their ports via a -p flag... The calls run in the expected time of < 100ms.

It appears that the docker bridge network is causing my calls between containers to take a very long time.  

Any ideas of where I can look to diagnose/correct this issue?

**Comment by CollinEstes** [comment]
So I believe my issue has to do with the DNS resolve that occurs.  I have created two screenshots here that show the difference.

The first screenshot is of the HTTP request being made from the HOST via "localhost" and hitting the exposed port of my web server running in a container.  This request takes < 80ms.

```
curl localhost:3000/api/lookups
```
![screen shot 2016-02-24 at 2 54 31 pm](https://cloud.githubusercontent.com/assets/1966803/13300684/f2535d5c-db06-11e5-9cb1-ca1901745fec.png)


The second screenshot here is of the HTTP request being made from within a docker container running on the same network as the web server (container name of eva_web_api).  The request first prints that top line "Hostname was NOT found in DNS cache", then after about 4 seconds it completes the rest of the request as shown

```
curl eva_web_api:3000/api/lookups
```

![screen shot 2016-02-24 at 2 55 58 pm](https://cloud.githubusercontent.com/assets/1966803/13300806/6819f4b0-db07-11e5-9db4-4f6ad2dcf383.png)

**Comment by sanimej** [comment]
@CollinEstes In 1.10 we introduced Docker embedded DNS server for name resolution for user defined networks. In previous releases the resolution was happening through /etc/hosts file updates.

I think the reason for delay is curl by default first tries to resolve the name to IPv6 and then to IPv4. Can you try with -4 which will force a direct v4 resolution ?

`curl -4 eva_web_api:3000/api/lookups`

**Comment by CollinEstes** [comment]
So that for sure made it faster!.  So for me I'm using Node.js' HTTP module to make requests between two containers which I'm guessing is doing something similar as curl by first trying IPv6.  So is the resolution to this issue just configuring my Node.js HTTP calls to use IPv4 as well?  Or is there some other configuration setting I can do on the host to default to IPv4 or add IPv6 in some way?

**Comment by sanimej** [comment]
@CollinEstes 
Do you have ipv6 enabled in the host and/or in the docker daemon ?

**Comment by CollinEstes** [comment]
@sanimej Thanks for the help.

Here is the container's /etc/resolv/conf.file:

```
search us-gov-west-1.compute.internal
nameserver 127.0.0.11
options ndots:0
```

I'll start the daemon in debug mode as well and try that.

**Comment by CollinEstes** [comment]
IPv6 is enabled on my host (Ubuntu14.04), I ran: 
```
cat /proc/sys/net/ipv6/conf/all/disable_ipv6
```
 and it produced '0'

Not sure how to check my docker daemon, I'm not running with the --ipv6

**Comment by CollinEstes** [comment]
@sanimej 

I enabled the debug mode on the daemon and looked through the log as I made requests.  I could see it first try "8.8.8.8" before going on to "8.8.4.4" and then finally coming to the DNS IP I added for my host and resolving.  My guess is my corporate proxy is causing those first two requests (8.8.*.*) to hang and eventually timeout, causing the slowness to resolve at the correct IP which was the the third one in the list.  

My solution was to change the DNS order in my /etc/default/docker file to have my internal IP first. 

```
DOCKER_OPTS="--dns 138.XX.XX.X --dns 8.8.8.8 --dns 8.8.4.4 "
```

This seems to fix our issue as it resolves our container_name based HTTP requests between containers first to that host DNS IP.  

I will go ahead and close this issue but just curious @sanimej do you know will this have some unintended consequence that I'm not accounting for?

**Comment by jgsqware** [comment]
I got the same problem on Debian.

I don't have access to internet from my machine, but the DNS resolving take a while inside the container.

@CollinEstes What do you mean by "Internal IP". Because I only have the localhost ?

**Comment by sanimej** [comment]
@CollinEstes Yes, if your host network doesn't have access to google DNS servers then it can cause the delay. Since you have the internal DNS server (138.xx) you might as well remove 8.8.8.8 and 8.8.8.4 from DOCKER_OPTS

**Comment by CollinEstes** [comment]
@jgsqware Sorry I have zero experience with Debian so can't help too much.  On Ubuntu I was able to get my internal DNS IP with:

```
cat /etc/resolv.conf 
```

If you system does not have external access then I would do what Sanimej commented today, check your DOCKER_OPTS file (not sure where that is on Debian) and remove the google IPs from that list.  See if that speeds things up for you.

**Comment by jgsqware** [comment]
@CollinEstes @sanimej I'l on Debian jessie and I have nothing in my
resolve.conf.
I have no Internet access and no option set to the Docker deamon. (no
Google dns in opts)

Any idea of what to add as dns to make it work ?
curl -4 work perfectly but not curl without option ?

PS sorry for the formatting I'm on my mobile :/

Le lun. 29 févr. 2016 18:01, Collin Estes <notifications@github.com> a
écrit :

**Comment by F21** [comment]
I was experiencing the same problem where lookups on network aliases would take around 15 seconds and lookup on FQDNs took up some amount of time (but much less than 15 seconds) on 1.10.3.

After upgrading to 1.11.0, it appears to have been fixed and all lookups are now in the order of milliseconds.

**Comment by jgsqware** [comment]
It's a good news! I will test it soon!

Le jeu. 14 avr. 2016 02:04, Francis Chuang <notifications@github.com> a
écrit :

**Comment by terbooter** [comment]
Got same issue on 
`Docker version 1.9.1, build a34a1d5`
~5 seconds lookup
Going to update docker to 1.11
