### ISSUE TITLE
"ONBUILD ADD" cache invalidation

### ISSUE THREAD

**Issue by felixSchl** [docker/docker#20676]
I think there could possibly be a bug in the behaviour of `ONBUILD ADD` in that it fails to invalidate the cache when building downstream images. It seems as if when building the downstream image, the cache for `ADD` won't be invalidated as it would without `ONBUILD`. I have confirmed it works fine without `ONBUILD`. Details follow.

Output of `docker version`:

```
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   76d6bc9
 Built:        Tue Nov  3 21:17:48 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   76d6bc9
 Built:        Tue Nov  3 19:20:09 UTC 2015
 OS/Arch:      linux/amd64
```

Output of `docker info`:

```
Containers: 10
Images: 116
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 136
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.12-boot2docker
Operating System: Boot2Docker 1.9.0 (TCL 6.4); master : 16e4a2a - Tue Nov  3 19:49:22 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: dev
ID: EKO2:K55Q:QJNW:2DI5:2JMS:SRIV:MU7V:GEVV:CO4A:VEOV:RAP7:2YYR
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 20
 System Time: 2016-02-24T22:07:40.321894847Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: felixschl
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
1
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):

Virtualbox

List the steps to reproduce the issue:

1. Create an image with `ONBUILD ADD . .`
2. Use the image created in (1) using FROM.
3. Build the image
4. Change a file
5. Re-build the image

Describe the results you received:

```
Step 1 : ADD . .
 ---> Using cache
```

Describe the results you expected:

```
Step 1 : ADD . .
 ---> Removed intermediate image
```

(or similar)

Provide additional info you think is important:

I am on OSX, using docker-machine with the virtualbox provider.

**Comment by duglin** [comment]
@felixSchl when you say "change a file" - did you actually modify a file or just "touch" it?
A change in timestamps won't trigger a re-running of the ADD because mtime isn't taken into account.
I tried it myself and it does seem to work.

**Comment by felixSchl** [comment]
I have definitely modified the file in both cases.

**Comment by duglin** [comment]
can you prove me with your Dockerfile and the exact steps you did on the cmd line so I can try to reproduce it?

**Comment by felixSchl** [comment]
Absolutely, should be able to do so later today

**Comment by felixSchl** [comment]
Huh, now I am actually also unable to reproduce this in the simplest case. It must be something else causing this in other image. Seems like this can be closed until proven otherwise.

**Comment by duglin** [comment]
@felixSchl ok, feel free to reopen it if you're able to give us a testcase that shows it.
