### ISSUE TITLE
container reports host memory when started with memory constraints

### ISSUE THREAD

**Issue by thechile** [docker/docker#20688]
Docker version 1.10.2, build c3959b1

As per this post from 2014 http://fabiokung.com/2014/03/13/memory-inside-linux-containers/ is there any plans for Docker to address the problem where containers started with memory limits such as `docker run -m 300M --memory-swap -1 -t -i ubuntu /bin/bash` still see the hosts memory ? Such as LXCFS.  

There are various programs that on start will use a percentage of the available memory to calculate cache sizes or on disk file size. If you have a 64GB host and start a container with 512M limit then this will be really bad. Some programs offer the option to overwrite the automatic calculations but not all. It also implies you know about this behavior in the first place. 

Are there any plans or roadmap where this is discussed ?

**Comment by thechile** [comment]
..also if the container still thinks it has 60G RAM when actuality has 512M as set by the cgroup then isn't there a much higher risk of the OOM killer wrongly terminating containers who thought they have much more memory to play with then they actually do ? This seems to be the default behavior unless you specify `--oom-kill-disable` when specifying the memory constraint.

**Comment by thaJeztah** [comment]
The linked article explains that this is a kernel limitation, and that the workarounds are probably *worse* than the current situation. I don't think there's much we can do here, unless it is changed in the kernel

**Comment by cpuguy83** [comment]
Note that Docker (as of 1.9??) will mount the container's cgroup to `/sys/fs/cgroup` and you can read memory limits and such from there... for instance memory limits would be in `/sys/fs/cgroup/memory/memory.limit_in_bytes`

As @thaJeztah mentioned, there is not really a good way to solve this.
Here is a great article on the problem from Heroku: http://fabiokung.com/2014/03/13/memory-inside-linux-containers/

**Comment by thechile** [comment]
I know it's a great article.. that's why i included it in the opening line of my issue. And i don't think closing the issue will make it go away. Maybe Docker should invest some resources in solving this problem.

**Comment by thechile** [comment]
if anyone stumbles across this issue and wants to quickly get an idea of how actively there container is macing calls to `/proc` info that is actually returning host details then something like this can be used: `docker exec -it <container_id> strace -f -p 1 -e file,sysinfo |& egrep '/proc/|sysinfo'`

**Comment by axelbodo** [comment]
I think this ticket should not be close saying there is sys/fs/cgroup/memory/memory.limit_in_bytes to decide what to do as 99.9999% of application can't use that as they are running under an execution framework, like dotnetcore, java etc. Application developers cannot control well fw's memorymanagement, and tell them how what to use for their heap management decisions. Though we can set our aws ecs java applications the max heapsize on commandline, but it makes unflexible our huge autoscaling systems, and dotnet fw doesn't have the possibility to control heap size.

**Comment by thaJeztah** [comment]
@axelbodo why keep the issue open? It's not something that can be solved here

**Comment by axelbodo** [comment]
https://dzone.com/articles/java-and-memory-limits-in-containers-lxc-docker-an
https://github.com/opencontainers/runc/issues/400
https://github.com/opencontainers/runc/pull/452

I think may be solved, I don't well the docker architecture, I didn't dig into the source code yet, but as I know docker uses runc cloned runtime, and the y solved to put to whitelist some /proce files, so docker-containerd-shim would be able to fuse bind mount meminfo, etc.

**Comment by axelbodo** [comment]
Any updates?
If we create runc setup with bundle and rootfs at known place, it's easy to bind fuse mount e.g /proc/meminfo into the container mount namespace, and of course the custome fuse daemon runs outside the container, but if we uses runc indirectly though docker it's hard to determine where is the bundle, and where is the rootfs, so hard to setup the fuse process with proper arguments.

So to summarize partially it is a problem the can and should be solved here. At least at create and run request, the api should be able to expose the location of the rootfs (e.g. with a symlink), that can be used to setup a fuse process. In our case Runc will ensure that our bind mount will happen, when procfs is already mounted. Is there anyway in thus time, that calling api create/run we may know where the relevant files/directories, that we want to bind mount, either out of a safe place or replace with fuse?

Thanks in advance 
alex

**Comment by thaJeztah** [comment]
@axelbodo may be better to open a new feature request for discussion; I wonder though if it should be in this repository, or in the containerd repository

**Comment by axelbodo** [comment]
Thanks for the answer. I think it would affect containerd as well, however I think some changes needed here to propagate setting in the stack's lower layers. I try to collect more information to how it effects the containerd, runc setup, and how it can be implemented well in the appropriate repos.
