### ISSUE TITLE
Linux mint docker 10.0.0.2 build fails

### ISSUE THREAD

**Issue by pollyrobin** [docker/docker#20696]
Creating a container on linux mint fails with DNS errors. 
I am following the quickstart / tutorial from [Docker - build your own image](https://docs.docker.com/linux/step_four/)
Might be related to issue [docker/docker#20026](https://github.com/docker/docker/issues/20026)

Output of `docker version`:

```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64

```
Output of `docker info`:

```
Containers: 9
 Running: 0
 Paused: 0
 Stopped: 9
Images: 2
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 30
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.19.0-32-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.773 GiB
Name: robin-K73E
ID: Q7FL:6LJ7:BUUU:5UVX:T7VP:V5UR:4ZRF:PUBR:KXP6:6HOK:DUIT:G54W
WARNING: No swap limit support
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):
Using Virtualbox on a crappy laptop

List the steps to reproduce the issue:
## 1. I am running the following Dockerfile
```
FROM docker/whalesay:latest
RUN apt-get -y update && apt-get install -y fortunes
CMD /usr/games/fortune -a | cowsay
```
## 2. Command i use is: 
```
docker -D build -t docker-whale .
```

## Describe the results you received:
```
Sending build context to Docker daemon 64.51 kB
Step 1 : FROM docker/whalesay:latest
 ---> 6b362a9f73eb
Step 2 : RUN apt-get -y update && apt-get install -y fortunes
 ---> Running in 33ab092e1119
Err http://archive.ubuntu.com trusty InRelease
  
Err http://archive.ubuntu.com trusty-updates InRelease
  
Err http://archive.ubuntu.com trusty-security InRelease
  
Err http://archive.ubuntu.com trusty Release.gpg
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com trusty-updates Release.gpg
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com trusty-security Release.gpg
  Could not resolve 'archive.ubuntu.com'
Reading package lists...
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease  

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/InRelease  

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/InRelease  

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Some index files failed to download. They have been ignored, or old ones used instead.
```

## Describe the results you expected:

Doing a wget on any of the urls works just fine.
Obviously a container that could connect to to urls as well.

# Provide additional info you think is important:
## What i tried so far

After some issue tracking i found 2 ways to help with dns
doing: 
```
 docker -dns 8.8.8.8 build -t docker-whale . 
```
and 
```
adding DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4"
to the /etc/default/docker file. 
```
Both ways still fail.

Then i found ticket [docker/docker#20026](https://github.com/docker/docker/issues/20026)
But sadly Linux Mint is not using firewalld. It is using ufw.
I disabled ufw, restarted the docker daemon but sadly still no luck when running the docker file.

Any clue if this is related to the 20026 issue or might this be something different?

## Some os info 
```
➜  cat lsb-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.3
DISTRIB_CODENAME=rosa
DISTRIB_DESCRIPTION="Linux Mint 17.3 Rosa"
➜  cat os-release 
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.4 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
➜  uname -a
Linux robin-K73E 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by pollyrobin** [comment]
Hmm this looks like a corporate network issue. Looks like dns request to not-corporate dns servers is blocked. So i had to disable dnsmasq so it got the corporate dns server details in my container. So using the default public dns servers is not really the best option imho.

**Comment by thaJeztah** [comment]
@pollyrobin did it work correctly after changing to the corporate DNS servers?

**Comment by pollyrobin** [comment]
Luckily it did so it does not really look like an issue. Except if something can be done at Dockers side not to automatically use public DNS servers but try to find the locally used ones first(but i think i my case this was a dnsmasq issue)

**Comment by thaJeztah** [comment]
The default dns configured is 8.8.8.8, to prevent issues in cases where (e.g.) 127.0.0.1 is used as DNS, which won't work inside the container (where 127.0.0.1 points to the container itself).

I'll close this issue
