### ISSUE TITLE
docker-engine 1.10.2-0~trusty can't install on clean Ubuntu 64-bit 14.04.3

### ISSUE THREAD

**Issue by dad-is-grat** [docker/docker#20698]
After a clean install of Ubuntu 14.04.3 64-bit server, I attempted to apt-get install docker-engine.  The version that is queued up to install is:

```
peterc@vm267211-01:~$ aptitude show docker-engine
Package: docker-engine            
State: not installed
Version: 1.10.2-0~trusty
Priority: optional
Section: admin
Maintainer: Docker <support@docker.com>
Architecture: amd64
Uncompressed Size: 43.2 M
Depends: iptables, init-system-helpers (>= 1.13~), sysv-rc (>= 2.88dsf-24) | file-rc (>= 0.8.16), libapparmor1 (>=
         2.6~devel), libc6 (>= 2.17), libdevmapper1.02.1 (>= 2:1.02.63), libsystemd-journal0 (>= 201)
Recommends: aufs-tools, ca-certificates, cgroupfs-mount | cgroup-lite, git, xz-utils, apparmor, yubico-piv-tool (>= 1.1.0~)
Conflicts: docker (< 1.5~), docker (< 1.5~), docker-engine-cs, docker-engine-cs, docker.io, docker.io, lxc-docker,
           lxc-docker, lxc-docker-virtual-package, lxc-docker-virtual-package
Description: Docker: the open-source application container engine
 Docker is an open source project to build, ship and run any application as a lightweight container 
 
 Docker containers are both hardware-agnostic and platform-agnostic. This means they can run anywhere, from your laptop to
 the largest EC2 compute instance and everything in between - and they don't require you to use a particular language,
 framework or packaging system. That makes them great building blocks for deploying and scaling web apps, databases, and
 backend services without depending on a particular stack or provider.
Homepage: https://dockerproject.org

peterc@vm267211-01:~$ 

```

I've checked necessary dependencies as documented in the Docker install docs for Ubuntu 14, for example:

```
peterc@vm267211-01:~$ aptitude search linux-image-extra
i A linux-image-extra-3.19.0-25-generic                   - Linux kernel extra modules for version 3.19.0 on 64 bit x86 SMP
peterc@vm267211-01:~$ 
```

When I run the apt-get install, I get the following output:

```
peterc@vm267211-01:~$ sudo apt-get install docker-engine
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 docker-engine : Depends: libsystemd-journal0 (>= 201) but it is not installable
                 Recommends: aufs-tools but it is not installable
                 Recommends: cgroupfs-mount but it is not installable or
                             cgroup-lite but it is not installable
                 Recommends: git but it is not installable
                 Recommends: yubico-piv-tool (>= 1.1.0~) but it is not installable
E: Unable to correct problems, you have held broken packages.
peterc@vm267211-01:~$ 

```

This is a repeatable error.

**Comment by thaJeztah** [comment]
Hm, wonder what that is, because just about any package (including really standard ones, e.g, `git`) is marked as "not installable"

**Comment by HackToday** [comment]
@dad-is-grat  how did you configure related docker repo ?  is it done by ubuntu official repo or docker repo?

**Comment by j16sdiz** [comment]
What is the output for `apt-cache policy  libsystemd-journal0` ?

**Comment by albers** [comment]
Under certain conditions, _sources.lst_ is not updated at the end of the install process. It then just contains the reference to the installer CD. Your sources selection from the installer is kept in _/etc/apt/sources.list.apt-setup_.
I experienced this several times with minimal virtual installations of Ubuntu 14.04 and fixed it with

    cat /etc/apt/sources.list.apt-setup > /etc/apt/sources.list

**Comment by thaJeztah** [comment]
Oh, thanks @albers, that's useful information!

**Comment by OpakAlex** [comment]
Same problem for me with ubuntu:
```
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 docker-engine : Depends: libsystemd-journal0 (>= 201) but it is not installable
                 Recommends: yubico-piv-tool (>= 1.1.0~) but it is not installable
E: Unable to correct problems, you have held broken packages.
root@api-hogs-main:~# apt-cache policy libsystemd-journal0
libsystemd-journal0:
  Installed: (none)
  Candidate: (none)
  Version table:
```

**Comment by LDX-MCPE** [comment]
Same problem here upon attempting to install docker-engine. I closely followed [this](https://docs.docker.com/engine/installation/linux/ubuntulinux/) installation guide.

I'm running Ubuntu 15.04 Vivid Vervet (3.19.0-51-generic).

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 docker-engine : Depends: libsystemd-journal0 (>= 201) but it is not installable
                 Recommends: aufs-tools but it is not going to be installed
                 Recommends: cgroupfs-mount but it is not going to be installed or
                             cgroup-lite but it is not going to be installed
                 Recommends: yubico-piv-tool (>= 1.1.0~) but it is not installable
```

**Comment by Fredjet** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  fredjet15@gmail.com
    Domain ventureacceleration.com has exceeded the max emails per hour (56/50 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:51448 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by eaglepeak.ovasp.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1aarmE-0008BG-4c
	for fred@ventureacceleration.com; Tue, 01 Mar 2016 16:24:18 -0500
Date: Tue, 01 Mar 2016 11:28:48 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1456860528;
	bh=cvmoTPtppCcjPDPMSS8EFzUrqnMQx+riIvWValftSKw=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=o8fBYOhSSfZKXGjD2JIx+kqUl+vKLCsu4LJB74fciyADOWbyocBgWuWvB/5blfzrf
	 1FvHeHr+zu7BrOlgw7RlUtzujUxVHx7ZCVVRSKAN4d3ztZPUAQoyHVvMfrHaASerf7
	 fMaZtmyK24P5Y+3fxouxCr2aY4M3oem5bP7ZzeJw=

**Comment by ksrimatk** [comment]
This is happening when there is incompatibility in Ubuntu version and entry in docker.list

Ex:
I have faced this when i have deb https://apt.dockerproject.org/repo ubuntu-trusty main in docker.list  with my Ubuntu Wily 15.10

**Comment by thaJeztah** [comment]
@LDX-MCPE Ubuntu 15.04 is EOL and no longer supported, so that's likely the issue you're running into. I suggest to upgrade to 15.10, because you also won't be getting security patches from Ubuntu on that version.

**Comment by jordancrawfordnz** [comment]
I seem to have resolved this by putting ``deb http://cz.archive.ubuntu.com/ubuntu trusty main `` in ``/etc/apt/sources.list`` (as mentioned on the Ubuntu site at http://packages.ubuntu.com/trusty/i386/libsystemd-journal0/download), then doing ``apt-get update``, ``apt-get install libsystemd-journal0`` and ``apt-get install docker-engine``.

**Comment by newswim** [comment]
Same issue. I followed the previous instructions by @jordancrawfordnz and got docker-engine installed and the hello-world fired up. My concern is that this method differs from the current [official instructions](https://docs.docker.com/engine/installation/linux/ubuntulinux/).

**Comment by dad-is-grat** [comment]
1.10.3-0~trusty installs successfully.

**Comment by advanderveer** [comment]
Still fails for me on clean 15.10, jordancrawfordns solution works but deviates significantly from the offcial instructions...

root@ip-10-20-3-89:/home/ubuntu# apt-get install docker-engine
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 docker-engine : Depends: libsystemd-journal0 (>= 201) but it is not installable
                 Recommends: aufs-tools but it is not installable
                 Recommends: cgroupfs-mount but it is not installable or
                             cgroup-lite but it is not installable
                 Recommends: yubico-piv-tool (>= 1.1.0~) but it is not installable

**Comment by NJ37** [comment]
@jordancrawfordnz Thanks a lot. I was finally able to get it installed in my Trusty.

**Comment by karb0n13** [comment]
@jordancrawfordnz You are a lifesaver, Thanks for posting that fix.

**Comment by alexmonroe87** [comment]
It would appear that the suggestion in this topic have now broken my apt-et update...

$ sudo apt-get update
Hit:1 https://apt.dockerproject.org/repo ubuntu-trusty InRelease
Reading package lists... Done

**Comment by yourNameIsGood** [comment]
@jordancrawfordnz   also works for me in my Xenial. Thank u soooo much

**Comment by ssebbass** [comment]
Same problem here, fix with:

```sh
sudo shutdown -r now
```

**Comment by fredkan** [comment]
same problem meet, I got success from below actions:
1. download libsystemd-journal0_204-14-bpo70+1_amd64.deb
http://ftp.cn.debian.org/debian/pool/main/s/systemd/libsystemd-journal0_204-14~bpo70+1_amd64.deb
2. dpkg -i libsystemd-journal0_204-14-bpo70+1_amd64.deb
3. apt-get install libltdl7
4. dpkg -i docker-engine_.....deb

**Comment by zultron** [comment]
Ahh, @fredkan's comment revealed the problem to me:  `bpo` means the package is from backports.  This command will install the elusive `libsystemd-journal0` on Trusty:

```
sudo apt-get install -t trusty-backports libsystemd-journal0
```

**Comment by dshook** [comment]
This also is a problem on Ubuntu 17.04 Zesty but unfortunately at time of writing there is no published sysv-rc package for zesty :(
https://packages.ubuntu.com/search?keywords=sysv-rc

**Comment by dadansatria** [comment]
thanks @jordancrawfordnz that's work for ubuntu 12.04 :smile:
