### ISSUE TITLE
Enhancement:  Docker Shell Integration (call images from the shell as applications)

### ISSUE THREAD

**Issue by helios** [docker/docker#20702]
Pull Request #20704 
With the Docker Shell Integration you can run an image diretly typing the name of the image. 
Bash completion works out of the box and you can browse them, depending on your settings.
You can run a container simply calling the name of the image, i.e.

  `ubuntu`

  `ubuntu echo "Hello World"`

a container will be started with default parameters:

  `--rm -u $(id -u):$(id -g)  -i  -t`

The user can set common parameters for all containers using the env variable DOCKER_OPTS_USER.

Why this? If you have images that are considered "applications" you can run them directly form 
the shell as normal application but running inside a container; look at CMD or ENTRYPOINT in the Docker
official docs.

These are your images now available from the shell:

ubuntu_14.04
ubuntu_14.04.1
ubuntu_latest
ubuntu_trusty
jruby_1.7.16
jruby_1.7.16.2

Images tagged as latest can be called omitting "latest".
If you create an image that run as application and you tag it with the name of the binary, you can call it directly as the local application. If the system is configured with swarm it could deploy the app remotely.

**Comment by thaJeztah** [comment]
I don't think this is something that should be implemented as core functionality of docker; you can already easily achieve this in your shell, by writing some shell scripts/functions.

For example, see https://github.com/jfrazelle/dotfiles/blob/a0b0ca56070e4cd9fbc0c9f5837e5fb8c145c06e/.dockerfunc#L259

**Comment by HackToday** [comment]
I agree with @thaJeztah  is it not responsibility for docker core to do, it can be achieved by 3-rd pary or shell scipts and related.

**Comment by thaJeztah** [comment]
Closing this, following the discussion above, and on the related PR https://github.com/docker/docker/pull/20704#issuecomment-189050210. Thanks again @helios
