### ISSUE TITLE
Issues with override entrypoint

### ISSUE THREAD

**Issue by mrsanuk** [docker/docker#20701]
Output of `docker version`:
docker version
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:27:08 2016
 OS/Arch:      linux/amd64

Output of `docker info`:
Containers: 37
 Running: 0
 Paused: 0
 Stopped: 37
Images: 54
Server Version: 1.10.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 329
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.58 GiB
Name: sanuk-K53SD
ID: 2JBV:RKD6:6EE3:FO7O:4GYK:JZZA:GH5E:HXBN:VDC2:YBKW:6M5X:B2YI
WARNING: No swap limit support
Provide additional environment details (AWS, VirtualBox, physical, etc.):
Ubuntu 14.04

List the steps to reproduce the issue:

Hi, I build image from Dokerfile:
FROM java
WORKDIR /opt/docker
ADD opt /opt
RUN ["chown", "-R", "daemon:daemon", "."]
USER daemon
ENTRYPOINT ["bin/script_name"]
CMD []

sometimes I need to override ENTRYPOINT (add different keys to script), I tried to use this commands:

sudo docker run  --entrypoint="/opt/docker/bin/script_name -Dcom.sun.management.jmxremote "  192.168.1.2:5000/image:1.0

sudo docker run  --entrypoint='"/bin/sh", "-c", "/opt/docker/bin/script_name -Dcom.sun.management.jmxremote "'  192.168.1.2:5000/image:1.0

sudo docker run  --entrypoint='/bin/sh -c /opt/docker/bin/script_name -Dcom.sun.management.jmxremote '  192.168.1.2:5000/image:1.0

sudo docker run  --entrypoint='"/bin/bash", "-c", "/opt/docker/bin/script_name -Dcom.sun.management.jmxremote "'  192.168.1.2:5000/image:1.0

sudo docker run  --entrypoint='/bin/bash -c /opt/docker/bin/script_name -Dcom.sun.management.jmxremote '  192.168.1.2:5000/image:1.0

 (script_name - it is bash script)

containers don`t start and always has this error:

exec: "/bin/bash -c /opt/docker/bin/script_name": stat /bin/bash -c /opt/docker/bin/script_name: no such file or directory
docker: Error response from daemon: Container command not found or does not exist..
 
without keys it works good:
sudo docker run  --entrypoint="/opt/docker/bin/script_name"  192.168.1.2:5000/image:1.0

also works, if i connect to docker and run this "/opt/docker/bin/script_name -Dcom.sun.management.jmxremote " manually

What I am doing wrong? How should I run the containers?

Thanks!

**Comment by cpuguy83** [comment]
You can't combine the values that way.
Notice that it is treating the whole string as something to execute rather than arg[0] being the executable things and the args after that as args to arg[0].
