### ISSUE TITLE
starting service in debian docker container kicks out

### ISSUE THREAD

**Issue by 573** [docker/docker#20714]
Output of `docker version`:

```
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        2016-02-22T22:37:33.778002647+00:00
 OS/Arch:      linux/amd64
```

Output of `docker info`:

```
Containers: 0
Images: 0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.18-boot2docker
Operating System: Boot2Docker 1.10.2 (TCL 6.4.1); master : 611be10 - Mon Feb 22
22:47:06 UTC 2016
CPUs: 1
Total Memory: 996.1 MiB
Name: default
ID: SOEA:YIG6:2GGR:SDK5:4LNS:D7HX:ZZJU:3CWE:RS44:HJUY:GITZ:FDQD
Debug mode (server): true
File Descriptors: 10
Goroutines: 21
System Time: 2016-02-26T07:14:09.292077779Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):
Working on a Windows 7 box with the following installed (https://github.com/docker/toolbox/releases/tag/v1.10.2a):

  *  docker 1.10.2
  *  docker-machine 0.6.0
  *  docker-compose 1.6.2
  *  Kitematic 0.10.0
  *  Boot2Docker ISO 1.10.2
  *  VirtualBox 5.0.14

List the steps to reproduce the issue:
1. `docker pull debian`
2. `docker run -p 80:80 -i -t debian /bin/bash`
3. `/# apt-get update`
4. `/# apt-get install apache2`
5. `/# service apache2 start`

Describe the results you received:

> [....] Starting web server: apache2AH00558: apache2: Could not reliably determin
e the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerNam
e' directive globally to suppress this message
panic: runtime error: slice bounds out of range
>
goroutine 12 [running]:
bufio.(*Reader).fill(0xc08201a7e0)
        /usr/local/go/src/bufio/bufio.go:86 +0x2e2
bufio.(*Reader).WriteTo(0xc08201a7e0, 0x373ac0, 0xc082008550, 0xbcd2, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:449 +0x285
io.Copy(0x373ac0, 0xc082008550, 0x375f90, 0xc08201a7e0, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:354 +0xb9
github.com/docker/docker/api/client.func┬À012(0x0, 0x0)
        /go/src/github.com/docker/docker/api/client/hijack.go:217 +0x1e0
github.com/docker/docker/pkg/promise.func┬À001()
        /go/src/github.com/docker/docker/pkg/promise/promise.go:8 +0x36
created by github.com/docker/docker/pkg/promise.Go
        /go/src/github.com/docker/docker/pkg/promise/promise.go:9 +0x102
>
goroutine 1 [chan receive, 2 minutes]:
github.com/docker/docker/api/client.(*DockerCli).CmdRun(0xc08208e000, 0xc08200e0
a0, 0x6, 0x6, 0x0, 0x0)
        /go/src/github.com/docker/docker/api/client/run.go:213 +0x1178
reflect.callMethod(0xc08209dda0, 0xc08204fd38)
        /usr/local/go/src/reflect/value.go:605 +0x180
reflect.methodValueCall(0xc08200e0a0, 0x6, 0x6, 0x1, 0xc08209dda0, 0x0, 0x0, 0xc
08209dda0, 0x0, 0x44a196, ...)
        /usr/local/go/src/reflect/asm_amd64.s:29 +0x3d
github.com/docker/docker/cli.(*Cli).Run(0xc08207b140, 0xc08200e090, 0x7, 0x7, 0x
0, 0x0)
        /go/src/github.com/docker/docker/cli/cli.go:89 +0x395
main.main()
        /go/src/github.com/docker/docker/docker/docker.go:69 +0x322
>
goroutine 5 [syscall, 4 minutes]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x26
created by os/signal.init┬À1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x3c
>
goroutine 11 [chan receive, 2 minutes]:
github.com/docker/docker/api/client.(*DockerCli).hijack(0xc08208e000, 0x97b9b0,
0x4, 0xc0820ba500, 0x76, 0x1, 0x372a60, 0xc082008dc0, 0x373ac0, 0xc082008550, ..
.)
        /go/src/github.com/docker/docker/api/client/hijack.go:244 +0xee1
github.com/docker/docker/api/client.func┬À018(0x0, 0x0)
        /go/src/github.com/docker/docker/api/client/run.go:173 +0x1c6
github.com/docker/docker/pkg/promise.func┬À001()
        /go/src/github.com/docker/docker/pkg/promise/promise.go:8 +0x36
created by github.com/docker/docker/pkg/promise.Go
        /go/src/github.com/docker/docker/pkg/promise/promise.go:9 +0x102
>
goroutine 9 [IO wait, 2 minutes]:
net.(*pollDesc).Wait(0xc0820ca170, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc08204c538, 0xc0820ca060, 0x97e5d0, 0x7, 0xa92b50, 0xb0, 0
x0, 0x0)
        /usr/local/go/src/net/fd_windows.go:188 +0x305
net.(*netFD).Read(0xc0820ca000, 0xc08209b000, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/fd_windows.go:470 +0x180
net.(*conn).Read(0xc08204c550, 0xc08209b000, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:121 +0xe3
crypto/tls.(*block).readFromUntil(0xc0820bf5f0, 0x3757e8, 0xc08204c550, 0x5, 0x0
, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:454 +0xed
crypto/tls.(*Conn).readRecord(0xc0820c82c0, 0x17, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:539 +0x2e1
crypto/tls.(*Conn).Read(0xc0820c82c0, 0xc08201d000, 0x1000, 0x1000, 0x0, 0x0, 0x
0)
        /usr/local/go/src/crypto/tls/conn.go:904 +0x16d
net/http.noteEOFReader.Read(0x375d50, 0xc0820c82c0, 0xc0820aa7e8, 0xc08201d000,
0x1000, 0x1000, 0xc0820a8c40, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1270 +0x75
net/http.(*noteEOFReader).Read(0xc0820ac480, 0xc08201d000, 0x1000, 0x1000, 0xc08
2020000, 0x0, 0x0)
        <autogenerated>:125 +0xdb
bufio.(*Reader).fill(0xc082098300)
        /usr/local/go/src/bufio/bufio.go:97 +0x1d5
bufio.(*Reader).Peek(0xc082098300, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xf7
net/http.(*persistConn).readLoop(0xc0820aa790)
        /usr/local/go/src/net/http/transport.go:842 +0xab
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:660 +0xca6
>
goroutine 10 [select, 2 minutes]:
net/http.(*persistConn).writeLoop(0xc0820aa790)
        /usr/local/go/src/net/http/transport.go:945 +0x424
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:661 +0xcc3
>
goroutine 13 [runnable, locked to thread]:
syscall.(*Proc).Call(0xc0820a4880, 0xc082107c60, 0x4, 0x4, 0x4, 0x814840, 0x0, 0
x0)
        /usr/local/go/src/syscall/dll_windows.go:136 +0x5c2
syscall.(*LazyProc).Call(0xc082042b40, 0xc082107c60, 0x4, 0x4, 0x0, 0x0, 0x0, 0x
0)
        /usr/local/go/src/syscall/dll_windows.go:279 +0x74
github.com/docker/docker/pkg/term/winconsole.readConsoleInputKey(0x3, 0xc082094a
00, 0x80, 0x80, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/pkg/term/winconsole/console_windows.go:
510 +0xfe
github.com/docker/docker/pkg/term/winconsole.getAvailableInputEvents(0x3, 0xc082
094a00, 0x80, 0x80, 0x2, 0x0, 0x0)
        /go/src/github.com/docker/docker/pkg/term/winconsole/console_windows.go:
1001 +0x5f
github.com/docker/docker/pkg/term/winconsole.(*WindowsTerminal).ReadChars(0xc082
079b20, 0x3, 0x373b90, 0xc08204c000, 0xc08210a000, 0x8000, 0x8000, 0x0, 0x0, 0x0
)
        /go/src/github.com/docker/docker/pkg/term/winconsole/console_windows.go:
1025 +0x86
github.com/docker/docker/pkg/term/winconsole.(*terminalReader).Read(0xc082008dc0
, 0xc08210a000, 0x8000, 0x8000, 0x1, 0x0, 0x0)
        /go/src/github.com/docker/docker/pkg/term/winconsole/term_emulator.go:15
4 +0x14f
io.Copy(0x376370, 0xc0820a4580, 0x376490, 0xc082008dc0, 0x49, 0x0, 0x0)
        /usr/local/go/src/io/io.go:362 +0x1fd
github.com/docker/docker/api/client.func┬À013(0x0, 0x0)
        /go/src/github.com/docker/docker/api/client/hijack.go:228 +0xe3
github.com/docker/docker/pkg/promise.func┬À001()
        /go/src/github.com/docker/docker/pkg/promise/promise.go:8 +0x36
created by github.com/docker/docker/pkg/promise.Go
        /go/src/github.com/docker/docker/pkg/promise/promise.go:9 +0x102
>
goroutine 14 [sleep]:
github.com/docker/docker/api/client.func┬À028()
        /go/src/github.com/docker/docker/api/client/utils.go:331 +0x69
created by github.com/docker/docker/api/client.(*DockerCli).monitorTtySize
        /go/src/github.com/docker/docker/api/client/utils.go:340 +0x163

Describe the results you expected:
The apache2 or any service should start without disattaching from the container session.

Provide additional info you think is important:
For i. e. the mysql service it is the same issue.

**Comment by HackToday** [comment]
I used `client and server both 1.9.1`, it can work

```
root@e6aa1d9a17c5:/# service apache2 start
[....] Starting web server: apache2AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message
. ok 
root@e6aa1d9a17c5:/# service apache2 status
[ ok ] apache2 is running.
```

I am thinking if related client and server compatibility issue like that ? Could you try new client version if work or not ?

**Comment by thaJeztah** [comment]
This is a continuation of the report started here; https://github.com/docker/toolbox/issues/429

**Comment by 573** [comment]
@HackToday, I actually wonder why `docker version` shows 1.8.1 for the client version although I'm using the downloaded package from https://github.com/docker/toolbox/releases/tag/v1.10.2a, which suggests client version would  be 1.10.2.
Where could I find the right client version for Windows?

**Comment by 573** [comment]
I had an old docker installation in the path, which explains the version mismatch and also the initial issue. Tested `service apache2 start` with the real current docker client version (download mentioned above) now and it works without any problems! Confirmed.

**Comment by thaJeztah** [comment]
Nice, good to hear!
