### ISSUE TITLE
Docker Fails to push and requests Auth

### ISSUE THREAD

**Issue by kitsushadow** [docker/docker#20728]
Docker Push fails and requests auth when pushing to DTR

docker login dtr.cicddevops.com
Username: mminaie
Password: 
Email: 
WARNING: login credentials saved in /home/kitsu/.docker/config.json
Login Succeeded
kitsu@kitsu-vm ~ $ docker tag hello-world dtr.cicddevops.com/hello-world
kitsu@kitsu-vm ~ $ docker push dtr.cicddevops.com/hello-world
The push refers to a repository [dtr.cicddevops.com/hello-world]
5f70bf18a086: Preparing 
b652ec3a27e7: Preparing 
unauthorized: authentication required
kitsu@kitsu-vm ~ $ docker tag hello-world dtr.cicddevops.com/dev-test/hello-world
kitsu@kitsu-vm ~ $ docker push dtr.cicddevops.com/dev-test/hello-world
The push refers to a repository [dtr.cicddevops.com/dev-test/hello-world]
5f70bf18a086: Preparing 
b652ec3a27e7: Preparing 
unauthorized: authentication required
kitsu@kitsu-vm ~ $ docker push dtr.cicddevops.com/mminaie/dev-test/hello-world
The push refers to a repository [dtr.cicddevops.com/mminaie/dev-test/hello-world]
5f70bf18a086: Preparing 
b652ec3a27e7: Preparing 
unauthorized: authentication required

Output of `docker version`:docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 71
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 234
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.19.0-32-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.828 GiB
Name: kitsu-vm
ID: PA5B:F4WI:OSK6:5QK3:SL4U:TEPN:AIOZ:DQ5K:TIDS:O44U:4AZB:7A5A
Http Proxy: http://10.237.118.25:8080/
WARNING: No swap limit support

DOCKER VERSION
kitsu@kitsu-vm ~ $ docker version
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64
Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64

DTR has a cert. Very Vanilla settings
My client has the cert.
No variations of docker login and docker pushes work

Looking for some assistance please!

**Comment by thaJeztah** [comment]
Can you send an email to support@docker.com - support for DTR is handled by the commercial team.

I'll close this issue, but happy to reopen if there's something to be done here
