### ISSUE TITLE
Network hostname as log driver address

### ISSUE THREAD

**Issue by otbe** [docker/docker#20735]
Hi everyone,

maybe Im missing something, but are hostnames not supported for logging drivers?

What I try to do is:
```$ docker run --rm --net=logger --log-driver=fluentd --log-opt fluentd-address=logger:24224 ubuntu echo "Test"```
where net=logger is a docker network running a fluentd instance as ```logger```. But all I get form this is:
```docker: Error response from daemon: Failed to initialize logging driver: dial tcp: lookup logger on 10.0.2.3:53: server misbehaving.```

If I change ```logger:24224``` to ```172.23.0.2:24224``` (container ip) it works as expected. Thats strange for me because: 
```
$ docker run --rm --net=logger ubuntu ping logger
PING logger (172.23.0.2) 56(84) bytes of data.
64 bytes from vserver_logger_1.logger (172.23.0.2): icmp_seq=1 ttl=64 time=0.053 ms
```
Whats wrong with my attempt? Is this expected behavior?
Thank you.
```
$ docker info
Containers: 49
 Running: 1
 Paused: 0
 Stopped: 48
Images: 343
Server Version: 1.10.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 547
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 4.1.17-boot2docker
Operating System: Boot2Docker 1.10.1 (TCL 6.4.1); master : b03e158 - Thu Feb 11 22:34:01 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.956 GiB
Name: dinghy
ID: ENMM:CSGF:DTN4:L2ZQ:XBYP:FJUM:7WA3:NNUJ:HDXP:Z35V:QYST:43WF
Debug mode (server): true
 File Descriptors: 20
 Goroutines: 32
 System Time: 2016-02-26T22:28:23.980888821Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

```
$ docker version
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Fri Feb 12 22:11:40 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 20:39:58 2016
 OS/Arch:      linux/amd64
```

**Comment by thaJeztah** [comment]
Thanks for reporting @otbe. This is a duplicate of https://github.com/docker/docker/issues/20370, and unfortunately currently not supported. For additional info, see this comment https://github.com/docker/docker/issues/20370#issuecomment-185229591

I'll close this issue for housekeeping, please continue the discussion on https://github.com/docker/docker/issues/20370
