### ISSUE TITLE
Fine-grained aufs graphdriver locks cause aufs failures

### ISSUE THREAD

**Issue by estesp** [docker/docker#20738]
Not sure why yet, but worth reporting that since commit 2f797bb1d9826f1aba242965b611b71b81fd152e the aufs graphdriver fails in most cases to properly mount all layers.  This usually manifests itself with a "can't find binary" from the `stat` calls trying to find the CMD/ENTRYPOINT and finding empty layers:
```
docker run busybox ls
exec: "ls": executable file not found in $PATH
docker: Error response from daemon: Container command not found or does not exist..
```

I tested master on Ubuntu 14.04.4 and Ubuntu 15.10 and both fail in the same way.  Switching graph drivers gets rid of the failures.  Building a binary one commit prior to 2f797bb1d9826f1aba242965b611b71b81fd152e works fine with the aufs graphdriver.

ping @cpuguy83 re #20275 as this probably needs further research as I assume you didn't see this in your setup.

The CI doesn't exhibit any failures I believe because vfs is the graphdriver in use, and the CI host systems are probably not on latest master; and this was just merged today 2/26/2016.  @crosbymichael this was the failure I was getting earlier.

**Comment by cpuguy83** [comment]
:( and I'm running vfs when I run integration tests locally as well.
Can't immediately see why the layers aren't being mounted properly, so reverting.

Revert PR is #20742
