### ISSUE TITLE
Container doesn't adapt the given IPv4Address when connecting to a Network via Remote API

### ISSUE THREAD

**Issue by elchris82** [docker/docker#20732]
Description of problem:
The container doesn't adapt the given IPv4Address when connecting to a Network via Remote API.
Noticed while trying to adjust the code in docker-py and docker-compose.

`docker version`:
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64

`docker info`:
Containers: 85
 Running: 1
 Paused: 0
 Stopped: 84
Images: 35
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 228
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-79-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.796 GiB
Name: worksation
ID: OKI4:IK3I:5C6F:BC4I:HCI6:PQAZ:IVN6:AFGW:GMUJ:MRUC:JICT:WB5I
WARNING: No swap limit support

`uname -a`:
Linux worksation 3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
Physical system with Ubuntu 14.04
VirtualBox with Ubuntu 15.10 

Steps to Reproduce:
1. docker pull nginx
2. docker network create --driver=bridge --subnet=192.168.0.0/24 --gateway=192.168.0.1 chrisnet
3. docker run --ip=192.168.0.10 --net=chrisnet -d nginx  (nginx is now reachable on 192.168.0.10)
4. curl --unix-socket /var/run/docker.sock http:/networks/ [id or network name here] /disconnect -H "Content-Type: application/json" -X POST -d '{"Container": "[container id here]"}'
5. curl --unix-socket /var/run/docker.sock http:/networks/ [id or network name here] /connect -H "Content-Type: application/json" -X POST -d '{"Container": "[container id here]", "EndpointConfig": {"chrisnet": {"IPv4Address": "192.168.0.10"}}}'

Actual Results:
The container now has the IP: 192.168.0.2 

Expected Results:
The container should have the IP: 192.168.0.10

Additional info:
Tested with Docker dev-Version as well:
Client:
 Version:      1.11.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   aa1fdf4
 Built:        Fri Feb 19 18:41:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   aa1fdf4
 Built:        Fri Feb 19 18:41:11 2016
 OS/Arch:      linux/amd64

Also tried to access the Remote Api with specific version: http:/v1.22/networks/...

**Comment by aboch** [comment]
@elchris82 

You need to modify your json on connect to:

` '{"Container":"[container id here]", "EndpointConfig": {"IPAMConfig":{"IPv4Address": "192.168.0.10"}}}'`

**Comment by elchris82** [comment]
Thank you very much @aboch ! 
That solves the issue.

I was oriented on the Remote API v1.22 reference to connect a container to a network, whitch seems to pass the network-name instead of "IPAMConfig".
