### ISSUE TITLE
Oracle XE 10g startup fails on Docker v.1.10+

### ISSUE THREAD

**Issue by ksusasd** [docker/docker#20733]
Starting from Docker v.1.10 the DB v.10 fails to start in a build phase.

Output of `docker version`:
```
Client:
 Version:      1.10.2
 API version:  1.22

Server:
 Version:      1.10.2
 API version:  1.22
```
Output of `docker info`:
```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 30
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.18-boot2docker
Operating System: Boot2Docker 1.10.2 (TCL 6.4.1); master : 611be10 - Mon Feb 22 22:47:06 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.956 GiB
Name: default
Debug mode (server): true
 File Descriptors: 10
 Goroutines: 22
Labels:
 provider=virtualbox
```

Unfortunately `service oracle-xe start` just prints the standard output and it is not obvious that there is a problem before checking processes. So the steps to reproduce will use `sqlplus` directly.

STR:
1. docker run --rm -ti image bash <- anything having 10g should reproduce the issue
2. sqlplus /nolog
3. connect sys/password as sysdba
4. startup

Expected: 
    successful startup.
Actual:
    ORA-27125: unable to create shared memory segment
    Linux Error: 1: Operation not permitted

It is not a problem for `docker run`, because passing `--security-opt seccomp:unconfined` fixes the problem. But there is no such option for the `docker build`. So any build that requires interaction with the DB will fail. As an example, the interaction may be required when some data or PL/SQL scripts must be deployed in a certain way.

[strace.zip](https://github.com/docker/docker/files/148972/strace.zip)
[strace_stat.zip](https://github.com/docker/docker/files/148998/strace_stat.zip)

**Comment by kikitux** [comment]
@ksusasd have a look at the paramter shm

ie:
https://blogs.oracle.com/OracleWebCenterSuite/entry/oracle_database_xe_as_docker

**Comment by ksusasd** [comment]
@kikitux Thank you very much it is a very useful post indeed. But unfortunately it doesn't seem to change anything for the XE version 10.
The result is still:
```
SQL> startup
ORA-27125: unable to create shared memory segment
Linux Error: 1: Operation not permitted
```

**Comment by kikitux** [comment]
@ksusasd I have tested XE 11G and works.

For 10G I would suggest check the parameters. memory_target can be causing issues, AMM, etc.
I think by Containers in Oracle DB space, they meant to be run in LXC Containers, it may or may not run in Docker as you have found.

**Comment by ksusasd** [comment]
@kikitux Yeah, 11G works, but unfortunately 10G refuses at the moment.
Kernel options doesn't seem to change anything, still `Linux Error: 1: Operation not permitted`.
BUT if you specify `--security-opt seccomp:unconfined` it obviously works.

**Comment by thaJeztah** [comment]
Could indeed be an seccomp "issue"; see this discussion https://github.com/docker/docker/issues/20634#issuecomment-188470869

/cc @injectives @justincormack @unclejack

**Comment by justincormack** [comment]
Looking through the `strace` log, the cases of `EPERM` don't seem to be seccomp related. However there is `shmget(0x880f3334, 597688320, IPC_CREAT|IPC_EXCL|SHM_HUGETLB|0600) = -1 EPERM (Operation not permitted)`.  The man page for `shmget` says use of `SHM_HUGETLB` requires capability `CAP_IPC_LOCK`, presumably as the hugetlb shm pages are unswappable. Can you try `docker run --cap-add ipc_lock ...` and see if that fixes it?

**Comment by ksusasd** [comment]
@justincormack Yeah, `seccomp:unconfined` fixes it.
Unfortunately `--cap-add ipc_lock` didn't help. Even `--cap-add ALL` didn't help. It is very confusing at the moment.

**Comment by justincormack** [comment]
Does it make any difference if you set `export DISABLE_HUGETLBFS=1` in the container?

Also it looks like that `strace` output was from a 32 bit binary, as it has 32 bit only system calls in it, which is a bit odd for Oracle. Which may also be related to other things. Which kernel version are you running on?

**Comment by justincormack** [comment]
Can you download https://raw.githubusercontent.com/justincormack/seccomp_examples/master/ptrace.json - this is the default profile but allowing ptrace. You should then be able to run with this profile `docker run --security-opt=seccomp:ptrace.json` and then run strace on oracle in the container and see where it fails.

**Comment by ksusasd** [comment]
@justincormack Unfortunately `export DISABLE_HUGETLBFS=1` didn't change anything, still `Linux Error: 1: Operation not permitted`.
Strace log contains 32 because XE is 32bit app, things like sqlplus is 32bit.
Different base images tested, but any should reproduce the issue. The Docker Hub even has one [public image](https://hub.docker.com/r/dkfi/docker-oracle-xe-10g/).

Attaching strace log for `/etc/init.d/oracle-xe start`
[strace2.zip](https://github.com/docker/docker/files/149557/strace2.zip)

**Comment by justincormack** [comment]
I can't replicate this with the one on hub.

**Comment by ksusasd** [comment]
@justincormack Hm :) It is very strange then.
If you just run it with the default profile `docker run -d`
What does `docker top` container return?

**Comment by justincormack** [comment]
Ah yes, there is a difference, but I couldn't see an error so it is hard to know where it is failing. Hmm.

**Comment by ksusasd** [comment]
@justincormack Please try reproduction steps, it should show the error on screen.

**Comment by ksusasd** [comment]
@justincormack Have you been able to reproduce the issue on screen? I am still struggling to find out the source of the problem.....

**Comment by justincormack** [comment]
Sorry, been a bit busy, will have another look.

**Comment by justincormack** [comment]
Yes, I can replicate it.

Unfortunately it seems to have a different behaviour when run under strace which is unhelpful.

**Comment by ksusasd** [comment]
@justincormack Yeah, it won't be easy to catch...
Sorry, I am not a security expert, but. I think, if the call gets blocked - it should appear in audit log, right?
I have installed Debian 9, seccomp is enabled there. I can see audit log with syscall, but only for docker daemon itself, for some reason there are no logs from container. Is it possible to configure something to see them? In such case we should be able to catch the call that is blocked in the logs.....

**Comment by ksusasd** [comment]
@justincormack Tried `auditctl -a exit,always -S all -F success=0`. Unfortunately cannot find anything suspicious. If you can please have a look at [logs](https://github.com/docker/docker/files/157895/audit.zip).

**Comment by ksusasd** [comment]
@justincormack Small update.
I'm trying to figure out what is blocked using audit logging.
The test aim is sqlplus `startup` command, since that is where such output happens:
```
ORA-27125: unable to create shared memory segment
Linux Error: 1: Operation not permitted
```
So the audit logging was enabled only while executing this command.
I started with excluding all sys calls that exist in the default profile. Eventually I came up with the following audit rules:
```
-a never,exit -S 12 -S 13 -S 232 -S 23 -S 14 -S 228 -S 1 -S 66 -S 117 -S 240 -S 102 -S 195 -S 5 -S 33 -S 0 -S 42 -S 6 -S 257 -S 83 -S 2 -S 3 -S 4 -S 21 -S 16 -S 54 -S 59 -S 202 -S 61 -S 47 -S 133 -S 137 -S 269 -S 91 -S 213 -S 91 -S 192 -S 197 -S 200 -S 201 -S 28 -S 199 -S 140 -S 221 -S 78 -S 120 -S 191 -S 75 -S 60 -S 46 -S 231 -S 22 -S 109 -S 9 -S 10 -S 158 -S 11 -S 35 -S 45 -S 85 -S 252 -S 125 -S 220 -S 243 -S 258 -S 43 -S 41 -S 7 -S 64 -S 99 -S 100 -S 122 -S 19 -S 39 -S 245 -S 15
-a always,exit -S all
```
Here are the logs: [audit.log.zip](https://github.com/docker/docker/files/159946/audit.log.zip)
Unfortunately the logs confuse me even more, because I can see 6 sys call types what are not in the default profile, but have `success=yes` and `exit=0`:
1. 173 ioperm
2. 174 create_module
3. 175 init_module
4. 180 nfsservctl
5. 183	afs_syscall
6. 311 process_vm_writev
I tried to extend the default profile with these types. The log became smaller, but still the result is `Linux Error: 1: Operation not permitted`. 
[audit2.log.zip](https://github.com/docker/docker/files/159950/audit2.log.zip)
I am also confused by sys call **117**, it doesn't have success and exit fields.....
There must be some call that is blocked, because if you provide the profile with `"defaultAction":"SCMP_ACT_ALLOW"` everything works fine.

**Comment by ksusasd** [comment]
`**type=SECCOMP** msg=audit(1457213360.089:321630): auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=8239 comm="oracle" exe="/usr/lib/oracle/xe/app/oracle/product/10.2.0/server/bin/oracle" sig=0 arch=40000003 **syscall=117** compat=1 ip=0xf7700be0 code=0x50000`
Does it mean that this call has been blocked by the seccomp? Such lines don't appear when running with `seccomp:unconfined`.

**Comment by justincormack** [comment]
Aha! Yes that is it! There is an odd syscall on 32 bit x86 called `ipc`, which is number 117, which is like `socketcall` for System V IPC, eg `shmget`. The seccomp library really ought to work around this like it does for `socketcall`. If you allow `ipc` it works!

I will prepare a patch, thanks for finding the log message!

**Comment by ksusasd** [comment]
@justincormack YES! Excellent! Thank you very much! It is very good news!
Checked with `ipc` enabled, now it all expected process can start up.
