### ISSUE TITLE
Image not showing up on docker hub despite successful push

### ISSUE THREAD

**Issue by mspanc** [docker/docker#20743]
Output of `docker version`:

```
Docker version 1.6.2, build 7c8fca2
```

Output of `docker info`:

```
Containers: 9
Images: 47
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 65
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 14.04.4 LTS
CPUs: 4
Total Memory: 3.859 GiB
Name: aksolotl
ID: CZEI:R4VG:4IBA:4KAA:FPZD:WQMC:KHZN:HMHR:LTSY:BIUQ:LPT5:CYPB
Username: mspanc
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):

Ubuntu 14.04, bare metal.

List the steps to reproduce the issue:

1. Create the image
2. Push the image

Describe the results you received:

1. $ sudo docker push radiokit/cerbero-win32-recipes:latest-squashed
The push refers to a repository [radiokit/cerbero-win32-recipes] (len: 1)
3489f2acf546: Image already exists 
c45e5b22b459: Image already exists 
6115c5d94f02: Image already exists 
27a4d9cee604: Image already exists 
d5e2dd3f4969: Image already exists 
5549154b6b00: Image already exists 
Digest: sha256:207a64b578c1254215f69bb7b9b08b81e051be25209f610f2855c2ac71939104

2. Image is not showing up on docker hub, and there's no way to pull it 

Describe the results you expected:

Image shows up on Docker Hub as usual.

Provide additional info you think is important:

Previous attempt to push failed with error 500 at the very end:

```
FATA[4638] Error pushing to registry: Server error: 500 trying to push radiokit/cerbero-win32-recipes blob - sha256:df23c58394c5511095330ab7980a57bb082ec5766507a30e7b4813b9cf8b08c4
```

All attempts were made in last 6h.

**Comment by thaJeztah** [comment]
can you contact support@docker.com? possibly the Hub team can look into this

**Comment by vrenjith** [comment]
I am also observing the same issue.

**Comment by mspanc** [comment]
I've sent them an email

**Comment by thaJeztah** [comment]
thanks all; contacting support may be the best option here; it's possible there's a temporary issue, but the maintainers here have no access to that data

**Comment by thaJeztah** [comment]
I'll close this issue for housekeeping, but happy to hear if Hub Support was able to resolve the issue

**Comment by MichaelJCole** [comment]
Also getting this issue.  Maybe it was closed before it was fixed?

**Comment by thaJeztah** [comment]
@MichaelJCole the issue was closed because this is an issue with Docker Hub, not the "docker engine" source code.

I just checked https://status.docker.com, and it looks like there's an active issue causing tags to take longer than usual before showing up on Docker Hub;

<img width="927" alt="screen shot 2017-01-12 at 00 23 21" src="https://cloud.githubusercontent.com/assets/1804568/21870583/5eef28e8-d85d-11e6-9153-aedcc5bc537e.png">
