### ISSUE TITLE
docker run --rm do not auto clean when container stop after docker daemon restart

### ISSUE THREAD

**Issue by wu0407** [docker/docker#20744]
If container already running with --rm when restart docker daemon, container will auto stop. 
Then restart the stop container and exit it.But the container that running with --rm not auto clean after container stop..  
 
Output of `docker version`:

```
[root@centos7-node4 docker-systemd]# docker version
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 16:16:33 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 16:16:33 2016
 OS/Arch:      linux/amd64
```

Output of `docker info`:

```
[root@centos7-node4 docker-systemd]# docker info
Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 31
Server Version: 1.10.2
Storage Driver: devicemapper
 Pool Name: docker-253:1-100931327-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.755 GB
 Data Space Total: 107.4 GB
 Data Space Available: 17.55 GB
 Metadata Space Used: 2.38 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.10.0-229.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.703 GiB
Name: centos7-node4
ID: YAFU:XTDB:LHWO:33EQ:DE56:6HY4:R7EI:B2BB:73NO:DXBR:HKID:T4HO
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):

running under KVM.

List the steps to reproduce the issue:
```
1.start --rm container
     docker run -it --rm centos7-xq-nosystemd:v1.2 --name net1  /bin/bash  
2.restart docker daemon
    systemctl daemon-reload &&  systemctl restart docker.service (now container stoped)
3.restart stoped container
    docker start net1
    docker attach net1
      exit
# docker ps -a      
CONTAINER ID        IMAGE                       COMMAND             CREATED             STATUS                      PORTS               NAMES
24eec1f78d9e        centos7-xq-nosystemd:v1.2   "/bin/bash"         5 hours ago         Up 59 minutes                                   net2
8397c7995192        centos7-xq-nosystemd:v1.2   "/bin/bash"         5 hours ago         Exited (0) 4 seconds ago                        net1
```

**Comment by cpuguy83** [comment]
This is expected. `--rm` is implemented on the client. There currently is no way to handle this. And I'm sure if it was daemon side even this would produce some unexpected results currently since docker kills all containers when it restarts.

There are a few open issues related to this, so closing this one.

**Comment by thaJeztah** [comment]
There's a proposal here https://github.com/docker/docker/issues/20334, and https://github.com/docker/docker/issues/16575

**Comment by wu0407** [comment]
addtion some situation it cause container under status of "Removal In Progress".that containers can not remove and start,other container not exit but file exist in /var/lib/docker/containers.

1. start three container and do something in container

`docker run -it --rm --name test-option-bridge-1 --net=option-bridge centos7-xq-nosystemd:v1.2 /bin/bash
docker run -it --rm --name default-bridge-1 centos7-xq-nosystemd:v1.2  /bin/bash
docker run -it --rm --name test-option-bridge-2 --net=option-bridge centos7-xq-nosystemd:v1.2 /bin/bash
`
2.restart daemon
3.list daemon
`[root@centos7-node4 ~]# docker  ps -a
CONTAINER ID        IMAGE                       COMMAND             CREATED             STATUS                PORTS               NAMES
123f69fef04a        centos7-xq-nosystemd:v1.2   "/bin/bash"         8 minutes ago       Removal In Progress                       test-option-bridge-2
e8315d6e3cfb        centos7-xq-nosystemd:v1.2   "/bin/bash"         8 minutes ago       Removal In Progress                       default-bridge-1`
4.daemon log
`Feb 29 17:34:41 centos7-node4 systemd[1]: Stopping Docker Application Container Engine...
Feb 29 17:34:41 centos7-node4 docker[26813]: time="2016-02-29T17:34:41.290538264+08:00" level=info msg="Processing signal 'terminated'"
Feb 29 17:34:51 centos7-node4 docker[26813]: time="2016-02-29T17:34:51.291460928+08:00" level=info msg="Container e8315d6e3cfb76048142889fd7591606e586ab2c759a8c4595572aef630d76
Feb 29 17:34:51 centos7-node4 docker[26813]: time="2016-02-29T17:34:51.291797154+08:00" level=info msg="Container 123f69fef04afb7118adc2a46310b046d8f32b3379c82640826e605ea65e15
Feb 29 17:34:51 centos7-node4 docker[26813]: time="2016-02-29T17:34:51.291880927+08:00" level=info msg="Container 6b356a4d17c7f448c1f63fc40fa12269a038705b2dd2f304dc2a86a90c6980
Feb 29 17:34:52 centos7-node4 systemd[1]: Starting Docker Application Container Engine...
Feb 29 17:34:52 centos7-node4 docker[27516]: time="2016-02-29T17:34:52.329370076+08:00" level=warning msg="devmapper: Usage of loopback devices is strongly discouraged for prod
Feb 29 17:34:52 centos7-node4 docker[27516]: time="2016-02-29T17:34:52.348800980+08:00" level=warning msg="devmapper: Base device already exists and has filesystem xfs on it. U
Feb 29 17:34:52 centos7-node4 docker[27516]: time="2016-02-29T17:34:52.373812455+08:00" level=info msg="[graphdriver] using prior storage driver \"devicemapper\""
Feb 29 17:34:52 centos7-node4 docker[27516]: time="2016-02-29T17:34:52.390095097+08:00" level=error msg="migrate container error: open /var/lib/docker/containers/6b356a4d17c7f4
Feb 29 17:34:52 centos7-node4 docker[27516]: time="2016-02-29T17:34:52.390139870+08:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Feb 29 17:34:52 centos7-node4 docker[27516]: time="2016-02-29T17:34:52.396535034+08:00" level=info msg="Firewalld running: false"
Feb 29 17:34:52 centos7-node4 docker[27516]: time="2016-02-29T17:34:52.758937283+08:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. D
Feb 29 17:34:53 centos7-node4 docker[27516]: time="2016-02-29T17:34:53.046067619+08:00" level=info msg="Loading containers: start."
Feb 29 17:34:53 centos7-node4 docker[27516]: ..time="2016-02-29T17:34:53.046685412+08:00" level=error msg="Failed to load container 6b356a4d17c7f448c1f63fc40fa12269a038705b2dd2
Feb 29 17:34:53 centos7-node4 docker[27516]: .
Feb 29 17:34:53 centos7-node4 docker[27516]: time="2016-02-29T17:34:53.087133170+08:00" level=info msg="Loading containers: done."
Feb 29 17:34:53 centos7-node4 docker[27516]: time="2016-02-29T17:34:53.087182397+08:00" level=info msg="Daemon has completed initialization"
Feb 29 17:34:53 centos7-node4 docker[27516]: time="2016-02-29T17:34:53.087198126+08:00" level=info msg="Docker daemon" commit=c3959b1 execdriver=native-0.2 graphdriver=devicema
Feb 29 17:34:53 centos7-node4 systemd[1]: Started Docker Application Container Engine.
Feb 29 17:34:53 centos7-node4 docker[27516]: time="2016-02-29T17:34:53.092736733+08:00" level=info msg="API listen on /var/run/docker.sock"
lines 614-652/652 (END)`
