### ISSUE TITLE
What is the FQDN of my container with the internal DNS Service running 

### ISSUE THREAD

**Issue by Vad1mo** [docker/docker#20769]
I am running nginx together with the new internal Docker DNS.
From inside the nginx container I can ping my target service `ping user-service` 

Nginx has its own DNS resolution. This is why providing a simple `user-service` hostname won't do it.

I also tried `user-service.zservices_default` which is service name + network in expectation that this is the FQDN. But also this configuration does not work so I guess this is no the FQDN. 

So the question is what is the default FQDN with the new DNS Service or how can make this nginx configuration make work again after switching from dnsdock to docker internatl dns service. 

```
...
	resolver 127.0.0.11 valid=120s; 
	resolver_timeout 5s;
  set $userservice user-service.zservices_default; # <---
  
  location /login {
    proxy_pass              http://$userservice:8887;
    proxy_set_header        Host $host;
    proxy_set_header        X-Real-IP $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_connect_timeout   150;
    proxy_send_timeout      100;
    proxy_read_timeout      100;
    proxy_buffers           16 64k;
    proxy_busy_buffers_size 64k;
    client_max_body_size    256k;
    client_body_buffer_size 128k;
  }
```

Output of `docker version`:
```
Client:
 Version:      1.10.2-rc1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   89dafc4
 Built:        Sat Feb 20 04:43:45 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2-rc1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   89dafc4
 Built:        Sat Feb 20 04:43:45 2016
 OS/Arch:      linux/amd64

```

Output of `docker info`:

```
$ docker info
Containers: 45
 Running: 23
 Paused: 0
 Stopped: 22
Images: 310
Server Version: 1.10.2-rc1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-30-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 20.91 GiB
Name: elaaiun
ID: DPPI:CGB3:6IGE:BOZR:5R5Z:RQER:L3ZQ:QA3I:FLQU:GICK:RR5D:B7KD
Debug mode (server): true
 File Descriptors: 257
 Goroutines: 415
 System Time: 2016-02-29T01:59:30.430641181+01:00
 EventsListeners: 0
 Init SHA1: 4ab2894d774b4a1ff53ce399a6fafd4b2a68b39e
 Init Path: /usr/lib/docker/dockerinit
 Docker Root Dir: /var/lib/docker
WARNING: No swap limit support
```

**Comment by Svenskunganka** [comment]
Hey @Vad1mo I'm in the exact same position. Just wanted to check with you if you found a solution or did you resolve to the old `--link`'ing method?

**Comment by marcelmfs** [comment]
From my experience, those HEX characters are related to HTTPS requests being made in HTTP port.

**Comment by Vad1mo** [comment]
So the FQDN is this one

`set $userservice user-service.zservices_default;`

where `user-service` is the container name and `zservices_default` is the network name.
