### ISSUE TITLE
Large file uploading issue

### ISSUE THREAD

**Issue by qzenchik** [docker/docker#20761]
I'm using multer to upload files to a server. Everything was fine before I started using docker for deployment. After applying docker - when uploading big files - I got an issue, where a file is starting to be uploaded, and after some time restarts again. I've added logging on multer: there is no error, it just starts to upload the file again, and in some period of time ( > 3 minutes) the connection is dropped. Maybe there is some timeout in docker?

**Comment by thaJeztah** [comment]
Please keep in mind that the GitHub issue tracker is for reporting bugs and feature requests,not a general support forum for using docker; can you use either one of;

- forums.docker.com
- the docker-user Google group
- the #docker IRC channel on freenode
- StackOverflow

I'll close this issue for the reasons above, but feel free to comment here after I've closed
