### ISSUE TITLE
iptables work with mapped ports from containers to host

### ISSUE THREAD

**Issue by fahimeh2010** [docker/docker#20762]
Hello All
I am using Docker version 1.10.1.
I have some containers that have mapped their ports on the host(docker create --name blah -p 1000:3306 and others). I want to block world access to some of this kind of ports.( just want world have access to port 80 and other is mapped to host for our company not the world).
how can block these kind of ports by iptables? I used lots of rules but sounds I can not block.
any help?
Thanks a lot

**Comment by thaJeztah** [comment]
Please keep in mind that the GitHub issue tracker is for reporting bugs and feature requests, not a general support forum for using docker; can you use either one of;

- forums.docker.com
- the docker-user Google group
- the #docker IRC channel on freenode
- StackOverflow

I'll close this issue for the reasons above, but feel free to comment here after I've closed
