### ISSUE TITLE
upgrade to 1.10.2 fails at /etc/default/docker

### ISSUE THREAD

**Issue by anentropic** [docker/docker#20765]
Output of `docker version`:

```
1.9.something
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):

Ubuntu 14.04 on Digital Ocean

List the steps to reproduce the issue:
1. `docker-machine ssh <node>`
2. `curl -fsSL https://get.docker.com/ | sh`
3. it stops at:
```
Configuration file '/etc/default/docker'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
```
4. ok, but then I tried to 'show differences' and it hung

Describe the results you received:

```
Installing new version of config file /etc/init/docker.conf ...

Configuration file '/etc/default/docker'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** docker (Y/I/N/O/D/Z) [default=N] ? d

D

```

I pressed `d`. Nothing happens.  Oh, I should have pressed `D`... no, nothing happens, it's broken.

Now I've `ctrl+c` to kill it and tried again:

```
...
Ign http://mirrors.digitalocean.com trusty/universe Translation-en_US
Fetched 3,899 kB in 7s (512 kB/s)
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
```

Borked.

**Comment by anentropic** [comment]
Following advice here: http://askubuntu.com/a/315791/62915

I tried again, it ends with:

```
E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem.
```

Following that suggestion brings me back here:

```
root@consul:~# dpkg --configure -a
Setting up docker-engine (1.10.2-0~trusty) ...

Configuration file '/etc/default/docker'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** docker (Y/I/N/O/D/Z) [default=N] ? D
```

...this time the diff viewer worked. It turned out the differences were simply the addition of some helpful comments so I hit `Y` to accept the new version.

```
Installing new version of config file /etc/default/docker ...
Installing new version of config file /etc/bash_completion.d/docker ...
docker start/running, process 3513
Processing triggers for ureadahead (0.100.0-16) ...
Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
```

I wasn't sure at this point but guessed I should run the installer script again now that hopefully all the dpkg blockage was sorted.

It ran to completion. But  `docker-machine ls` said _"Unable to query docker version: Cannot connect to the docker engine endpoint"_...

Eventually `docker-machine env` provided the clue:

```
Error checking TLS connection: Error checking and/or regenerating the certs: There was an error validating certificates for host "46.101.91.32:2376": dial tcp 46.101.91.32:2376: getsockopt: connection refused
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.
```

After regenerating the certs now all is well, `docker-machine ls` reports it running 1.10.2

All of the above in case it helps someone else.

The main thing was the original problem though... choosing the "show diff" option hung the install script.

**Comment by anentropic** [comment]
Output of `docker info`:

```
Containers: 3
Images: 26
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 37
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-71-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 490 MiB
Name: consul
ID: FFCA:FAMZ:TP5M:2F4R:A5BN:L2LL:5KPO:PODM:RL4G:A26I:G6JP:PQHP
WARNING: No swap limit support
Labels:
 provider=digitalocean
```

**Comment by thaJeztah** [comment]
I know the get.docker.com script is meant for *installing*, not updating an installation, but I wonder if this is because the script sets `DEBIAN_FRONTEND=noninteractive`, therefore ignoring input here.

Also read this PR for additional information https://github.com/docker/docker/issues/20524

**Comment by anentropic** [comment]
seems likely

I probably should have done `docker-machine upgrade`... but this method was stuck in my head as I'd previously used it to upgrade to an `-rc` version not available via the upgrade command

**Comment by thaJeztah** [comment]
Yeah, the standard approach (not using docker-machine), is just `apt-get upgrade`, but I think I've been in that situation as well at some point. Perhaps the `DEBIAN_FRONTEND` var could be skipped in the script, but I'm not sure if that may complicate other situations.

I think we should close this one, but if you have thoughts on how this could be improved, feel free to suggest

**Comment by LK4D4** [comment]
I'm going to close this because it's inactive. Feel free to open new issue.
