### ISSUE TITLE
Proposal: Overlay Network DNS Configuration

### ISSUE THREAD

**Issue by maoxianquan** [docker/docker#20779]
When using the Docker Overlay Network, I want to use my own dns nameserver (eg: 8.8.8.8) while start network with my own overlay network.  Following the guide https://docs.docker.com/engine/userguide/networking/configure-dns/ 
I have to use the "--dns" option to before my running each containers. So far, only the "bridge" networks can inherit the "/etc/resolve.conf" from host if I didn't specify the dns options.

My proposal would be :
1. If the net work is overlay, can it also have this function " In the absence of the --dns=IP_ADDRESS..., --dns-search=DOMAIN..., or --dns-opt=OPTION... options, Docker uses the /etc/resolv.conf of the host machine (where the docker daemon runs). "
2. while create the overlay network, is it possible to add those dns options. And those dns options can be used as default while starting a container. Those options can be of course overwritten while starting containers.

Thanks

**Comment by thaJeztah** [comment]
@maoxianquan I think the embedded DNS server will automatically forward DNS requests that don't resolve to other containers on the network to your configured DNS server; does this not work for you?

**Comment by maoxianquan** [comment]
@thaJeztah , when use overlay , it works only you set "--DNS" before you run a container, but it is not so convenient to add this parameter each time you start a container. Why not we set this in the overlay network settings as default value for the overlay network ? 

For the bridged mode, the container will include the name servers in host machine's /etc/resolve.conf

**Comment by thaJeztah** [comment]
@maoxianquan why not set the `--dns` option on the daemon? https://docs.docker.com/engine/reference/commandline/daemon/#daemon-dns-options or won't that work for your use-case?

**Comment by maoxianquan** [comment]
@thaJeztah, in my case, we want to share the same docker daemon for different overlay networks. In each overlay networks, we need to set different external DNS servers. 
So set options in the daemon is not suitable for me.

**Comment by sanimej** [comment]
@maoxianquan A container can be connected to more than one network but the external DNS servers being used is a property of the container and not specific to a particular network. Hence its not correct to pass --dns on network create.

Overlay network doesn't provide external connectivity. When a container is connected only to an overlay network docker adds an endpoint in a bridge network, docker_gwbridge, which provides external connectivity. So if you are starting a container on a overlay network it should also inherit the DNS server config from host's /etc/resolv.conf and the DNS resolution for external names should go to that server. Is this not happening for you ?

**Comment by maoxianquan** [comment]
@sanimej  thanks for the explain. I would expect this happen to me, unfortunately, it not happen to me when I use overlay networks like "--net=myoverlay".  In Container, the file doesn't include my host's nameservers, only "127.0.0.11":
_**root@d3810b44c6a5:/linker# cat /etc/resolv.conf
search bj803.ln
nameserver 127.0.0.11
options ndots:0**_
But it happens when I use bridged mode "--net=bridge"... 
Maybe it is a bug?

**Comment by maoxianquan** [comment]
BTW, my docker command is 

**_docker run -d --net-alias=deployer2 --net=overlay1 myrepository:5000/linker_deployer_**

**Comment by sanimej** [comment]
@maoxianquan When connecting to a user defined network you will see only 127.0.0.11 in the resolv.conf file. This is the address of docker embedded DNS server. The external DNS servers you had in the host's resolv.conf file will be maintained in a per container config in the docker daemon. If the embedded server can't resolve a name (ie: any name that is outside the docker network domain) it will forward the query to the external DNS servers. If you run the docker daemon in debug mode (-D option) you can see the logs for DNS queries being forwarded to external servers.

When you are connecting to --net=bridge, its the default bridge network. As mentioned in the documents, embedded DNS server is not used in the default bridge network. So the external DNS servers will be directly populated in resolv.conf file.

**Comment by maoxianquan** [comment]
@sanimej thanks for the help, I found the debug info and it do forward the request.  I think it is because my name server has 3 records, so the last record 8.8.8.8 is not reached.  Maybe because the 127.0.0.11 and only 2 name records will take effect. 
PS: current linux /etc/resolv.conf only support max 3 records. 
http://man7.org/linux/man-pages/man5/resolv.conf.5.html 
Thanks all for help, I will close the issue.
