### ISSUE TITLE
Exception "invalid value "... ..." for flag --tag" doesn't guide user to correct it

### ISSUE THREAD

**Issue by pcgeek86** [docker/docker#20788]
When I tried running `docker build --tag Trevor:FlaskCompose`, I received an exception:

> invalid value "Trevor:FlaskCompose" for flag --tag: Error parsing reference: "Trevor:FlaskCompose" is not a valid repository/tag
See 'docker build --help'.

Unfortunately, when running `docker build --help`, as suggested by the tool, there is no additional guidance provided.

> -t, --tag=[]                    Name and optionally a tag in the 'name:tag' format

How does a user know what a valid "tag" is? I fiddled with the name, and apparently the `name` must be all lowercase, and the `tag` portion can have capital letters. However, I am not aware of what the other requirements are.

The less friction, and more clarity, that is provided by Docker, the more likely users will be to adopt it and be delighted by the experience of working with it. :smile: 

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by thaJeztah** [comment]
Looks like this is indeed not documented, adding the accepted characters would be a good start; possibly 

- https://github.com/docker/docker/blob/master/docs/reference/commandline/build.md#tag-image--t
- https://github.com/docker/docker/blob/master/docs/reference/commandline/tag.md
- https://github.com/docker/docker/blob/master/docs/reference/commandline/commit.md

And the associated man pages

- https://github.com/docker/docker/blob/master/man/docker-build.1.md
- https://github.com/docker/docker/blob/master/man/docker-tag.1.md
- https://github.com/docker/docker/blob/master/man/docker-commit.1.md

Perhaps we can make a description in a single place, and link to that from the other pages.

Possibly we can improve the error message;
https://github.com/docker/docker/blob/acd8baccff10642e1d44a342414cd196b81a4605/reference/reference.go#L58

Rules for valid formats are defined in https://github.com/docker/docker/blob/acd8baccff10642e1d44a342414cd196b81a4605/vendor/src/github.com/docker/distribution/reference/reference.go#L6

**Comment by isubuz** [comment]
@thaJeztah I am looking to get involved and pick up a documentation task first. If this is a documentation task only, I will be happy to work on this.

**Comment by thaJeztah** [comment]
@isubuz awesome! As mentioned above, I think adding it to the documentation would be a good start, so if you want to work on that, that'd be great.

Maybe @aaronlehmann has some input on improving the error-message and with some guidance you can incorporate those code changes as well, but I'm fine with doing those in a separate pull request if you're not comfortable making those changes.

If you need some info on the contribution process, you can find our contributors guide here; 
https://docs.docker.com/opensource/workflow/make-a-contribution/

**Comment by isubuz** [comment]
Great. I will get to the documentation part first and then to error message/code changes.

**Comment by isubuz** [comment]
#dibs

**Comment by isubuz** [comment]
@thaJeztah now that the changes are merged, how do we progress the status? Is it done by an automated process?

**Comment by thaJeztah** [comment]
@isubuz oh! you used `Addresses #20788` instead of `Fixes #20788`, so GitHub didn't close automatically. I'll close this one, because it's fixed now :tada:

**Comment by isubuz** [comment]
Ah ok. Something to remember next time. Thanks!
