### ISSUE TITLE
docker info reports wrong image count: Not a bug, just need more elaborate description in the docs.

### ISSUE THREAD

**Issue by shishir-a412ed** [docker/docker#20783]
https://bugzilla.redhat.com/show_bug.cgi?id=1304808

Output of `docker version`:
Client:
 Version:      1.8.2-el7
 API version:  1.20
 Package Version: docker-1.8.2-10.el7.x86_64
 Go version:   go1.4.2
 Git commit:   a01dc02/1.8.2
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2-el7
 API version:  1.20
 Package Version: 
 Go version:   go1.4.2
 Git commit:   a01dc02/1.8.2
 Built:        
 OS/Arch:      linux/amd64

List the steps to reproduce the issue:
1. docker images --all | tail -n +1 | wc -l
2. docker info | grep 'Images'

Provide additional info you think is important:
Discussions around this issue:
*******************************************************************************************************
When you do `docker info` SystemInfo (https://github.com/docker/docker/blob/master/daemon/info.go#L26) method is called, which gets the images count from imageStore.

daemon.imageStore.Map()
https://github.com/docker/docker/blob/master/daemon/info.go#L72

This map returns information about the images. (Tags are not part of this store).
Hence when you do `docker images --all|wc -l` you see a different count as tags are also included in the output.

Hope that clears up the confusion.

Shishir
*********************************************************************************************************
FROM: Chris Evich
Okay, just checked.  The man-page for 'docker info' is in need of some love.  Clarifying the 'Images' and 'Containers' count with what they actually represent would be 'nice to have'.  On F22, it has this blurb:

This  command  displays  system  wide information regarding the Docker installation. Information displayed includes the number of containers and images, pool name,  data file,  metadata file, data space used, total data space, metadata space used , total metadata space, execution driver, and the kernel version.

and the example section is really out of date (OS: Ubuntu 14 and Kernel 3.13).  Would make the guys in marketing happier if it showed Fedora/CentOS/RHEL instead and maybe showed the typical devicemapper details instead of aufs (not used any more, anywhere IIRC).

Here's a suggestion for the description blurb:

This  command  displays  system  wide information regarding the Docker installation. Information displayed includes the number of containers and (non-tagged) images, pool name,  image storage details, space available and used, execution driver, OS and the kernel versions.
********************************************************************************************************

**Comment by thaJeztah** [comment]
Thanks for the suggestion; Were you planning to open a PR to make those changes?

**Comment by shishir-a412ed** [comment]
@thaJeztah yeah will open a PR soon.
I won't mind if someone from the community (new to docker) wants to pick it up :)

Shishir

**Comment by jayunit100** [comment]
aah this has burnt me before to.
i can put a PR in :)

**Comment by srikanthpeetha** [comment]
#20783

**Comment by shishir-a412ed** [comment]
@jayunit100 Did you get a chance to look at this ?

**Comment by geekylucas** [comment]
#dibs
