### ISSUE TITLE
Synchronize files with container

### ISSUE THREAD

**Issue by F21** [docker/docker#20795]
I am setting up a workflow to use docker containers for development. My host machine is a Windows machine and I plan to use CoreOS as the docker host (because it's lightweight). I also plan to keep my source code on my host machine and mount or sync them into the container.

Images like CoreOS unfortunately do support VirtualBox extensions, which means you can't use the shared folders functionality to mount the source code into the container. Setting up an NFS server or rsync on Windows is also not trivial.

Since docker now has a `docker cp` command to provide a cross platform way to easily copy files into a docker container, it would be extremely useful to have a `docker syncfiles` command. This command can diff the local folder and the one within the docker container and synchronize the folder in the container with the one on the client.

**Comment by thaJeztah** [comment]
If "lightweight" is the reason for using CoreOS, why not use the standard boot2docker? Boot2docker is 32mb which is, IMO pretty lightweight https://github.com/boot2docker/boot2docker/releases. Also, boot2docker supports the latest docker versions at all times, whereas CoreOS doesn't (and doesn't have official docker builds)

**Comment by thaJeztah** [comment]
To get it up and running, simply download Docker Toolbox https://github.com/docker/toolbox/releases, which should set everything up on your machine

**Comment by HackToday** [comment]
+1 @thaJeztah  .CoreOS is just OS, just use boot2docker setup a containers and use docker command to mount related host files could archive your goal.

**Comment by F21** [comment]
@thaJeztah my docker daemon will be running boot2docker or CoreOS on a different machine (not my dev machine), so mounting my development environment as a shared folder is not feasible. It maybe possible to share my dev environment (Windows) across the network and maybe share them into the boot2docker environment, but then you get all sort of quirks and filesystem events do not work correctly.

**Comment by thaJeztah** [comment]
@F21 using a volume driver plugin that syncs local changes to a volume mounted in your containers could be a good solution for that some plugins can be found here https://docs.docker.com/engine/extend/plugins/#finding-a-plugin (but there's more that are not listed there)
