### ISSUE TITLE
docker install script claims ppc64le isn't 64bit

### ISSUE THREAD

**Issue by stewart-ibm** [docker/docker#20799]
As per the usual install instructions:

$ curl -fsSL https://get.docker.com/ | sh
Error: you are not using a 64bit platform.
Docker currently only supports 64bit platforms.
$ arch
ppc64le

**Comment by thaJeztah** [comment]
I'll close this one in favor of https://github.com/docker/docker/issues/20801

**Comment by tophj-ibm** [comment]
ahh this issue is *slightly* different. looks like this regex isn't catching ppc64le:
```sh
case "$(uname -m)" in
		*64)
```
and causing it go to the default case. Still isn't going to do much without a proper target from #20801 though. I'll ask around the other power folks and see what we are doing there.

**Comment by thaJeztah** [comment]
Agreed, let's await the outcome of #20801 and see if we need to update this script
