### ISSUE TITLE
Manually specified path to the default Docker registry - docker 1.10.2

### ISSUE THREAD

**Issue by dohnto** [docker/docker#20804]
Output of `docker version`:

```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 16:22:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 16:22:08 2016
 OS/Arch:      linux/amd64
```

Output of `docker info`:

```
Containers: 24
 Running: 2
 Paused: 0
 Stopped: 22
Images: 308
Server Version: 1.10.2
Storage Driver: devicemapper
 Pool Name: docker-253:2-413393-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 10.48 GB
 Data Space Total: 107.4 GB
 Data Space Available: 26.63 GB
 Metadata Space Used: 15.14 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.132 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93 (2015-01-30)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.3.4-200.fc22.x86_64
Operating System: Fedora 22 (Twenty Two)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.721 GiB
Name: tomas-dohnalek.brno.seznam.cz
ID: L3SZ:VAVV:WVWH:K37D:QTXP:A3QC:J3LU:OANJ:25A7:J2AR:OYHA:RWEF
Username: dohnto
Registry: https://index.docker.io/v1/
```

List the steps to reproduce the issue:
1. Follow the documentation: (https://docs.docker.com/engine/reference/commandline/pull/ - `docker pull registry.hub.docker.com/debian` or https://github.com/docker/docker/blob/master/man/docker-pull.1.md - `docker pull registry.hub.docker.com/fedora:20`)
2. Run `docker pull registry.hub.docker.com/debian`

Describe the results you received:
The actual output is  `Error response from daemon: Error parsing HTTP response: invalid character '<' looking for beginning of value: "\n\n\n<!DOCTYPE html><!....404: The page you were looking for is not here...`

Describe the results you expected:
Pull the image

Provide additional info you think is important:
**When I use docker 1.9.1 everything works as expected.**

**Comment by HackToday** [comment]
I used docker 1.10.0 it can work, but warning with that
```
$ docker pull registry.hub.docker.com/debian
Using default tag: latest
Pulling repository registry.hub.docker.com/debian
a0e9fe2f8803: Download complete 
1e58eecba27a: Download complete 
Status: Downloaded newer image for registry.hub.docker.com/debian:latest
registry.hub.docker.com/debian: this image was pulled from a legacy registry.  Important: This registry version will not be supported in future versions of docker.
```


also master docker seems not work as the issue described, I suspect is it means that images not supported anymore in distribution or  one docker issue ?

**Comment by thaJeztah** [comment]
I'm able to reproduce on docker 1.10.2, so either the documentation should be updated, or there's a regression

**Comment by thaJeztah** [comment]
Looks to work in docker 1.9 indeed, so looks like a bug to me; perhaps due to "text/html" being accepted as content type? idk

ping @aaronlehmann can you take a look?

**Comment by aaronlehmann** [comment]
This is a mix of incorrect documentation and inconsistent server-side behavior.

`docker pull registry.hub.docker.com/library/debian` does work.

For some reason, the v1 registry doesn't require the `library/` prefix to pull Debian. Old versions of Docker retried using the v1 protocol after almost any error. This was tightened up in 1.10 because unjustified switches to the v1 protocol were causing a lot of problems.

It's fine that `registry.hub.docker.com` gives a 404 for a nonexistent image. But 404s under the /v2 URL hierarchy should conform to the Docker registry protocol error schema. Producing HTML here seems like a misconfiguration.

In any case, we shouldn't be telling people to pull from `registry.hub.docker.com`. So let's fix the docs.

**Comment by HackToday** [comment]
@aaronlehmann  Just one question, when you said
" Producing HTML here seems like a misconfiguration", I am not sure is it github configuration or image configuration issue?  Thansk

**Comment by aaronlehmann** [comment]
@HackToday: It looks like a Docker Hub misconfiguration on that subdomain.

**Comment by aaronlehmann** [comment]
I checked with the Docker Hub team and found out there's an unresolved issue with v2 APIs on `registry.hub.docker.com`. This is being fixed and should be resolved soon. However, they recommend using `registry-1.docker.io` for v2 APIs (this is what Docker uses by default). We should update the docs to remove the explicit hostname.

**Comment by thaJeztah** [comment]
@aaronlehmann hm looks like that didn't work as well. I think that part of the docs is to show that you can specify a registry-url instead of just the repo/image name

```
docker pull registry-1.docker.io/debian
Using default tag: latest
Pulling repository registry-1.docker.io/debian
Error: Status 405 trying to pull repository debian: "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\n<title>405 Method Not Allowed</title>\n<h1>Method Not Allowed</h1>\n<p>The method is not allowed for the requested URL.</p>\n"
```

**Comment by aaronlehmann** [comment]
@thaJeztah: I think `docker.io` would work for an example like this.

But it should be `docker.io/library/debian`.
