### ISSUE TITLE
docker rm spend about 10s and takes 90% cpu when remove a exited container in Ubuntu 14.04.2

### ISSUE THREAD

**Issue by njuicsgz** [docker/docker#20802]
# docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:37:18 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:37:18 UTC 2015
 OS/Arch:      linux/amd64

root@AMZ-xx:/home/ops# cat /etc/issue
Ubuntu 14.04.2 LTS \n \l

root@AMZ-xxx:/home/ops# uname -r
3.13.0-48-generic

I am on a AWS EC2 instance.

List the steps to reproduce the issue:
root@AMZ-xx:/home/ops# docker run -d busybox echo 'ok'
d9b4fdb5053c20d04f6e5f69874f5767416d479c32df99215093f1e4e98672ff
root@AMZ-xx:/home/ops# docker ps -a |grep Exit
d9b4fdb5053c        busybox                                                                                         "echo ok"                9 seconds ago       Exied (0) 8 seconds ago                       happy_jones
root@AMZ-xx:/home/ops# date; docker rm -v d9b4fdb5053c; date
Tue Mar  1 06:03:38 UTC 2016
d9b4fdb5053c
Tue Mar  1 06:03:45 UTC 2016  ==> it takes 7s

Describe the results you received:
In above 7s when docker rm container, the kworker process will take 90%+ CPU usage.
This problem happens Ubuntu 14.04.2 which has kernel version 3.13.0-48, however 14.04 and 14.04.1 are OK.
This problem appears when docker version is either 1.8.3 or latest (1.10.2).

Describe the results you expected:
I am not sure whether it is a problem of Linux Kernal or not. But it is really a bug using docker which need to be fixed or work around.

Provide additional info you think is important:

**Comment by thaJeztah** [comment]
Can you add the output of `docker info` as well? Are you using the `devicemapper` storage driver?

**Comment by njuicsgz** [comment]
root@AMZ-SIN-xxxx:/home/ops# docker info  ===> this is the problem AMI
Containers: 7
Images: 113
Storage Driver: devicemapper
 Pool Name: docker-202:1-787040-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 5.383 GB
 Data Space Total: 107.4 GB
 Data Space Available: 21.8 GB
 Metadata Space Used: 8.217 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.139 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-48-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 8
Total Memory: 14.69 GiB
Name: AMZ-SIN-OpsResPool-33-33
ID: 3ZQZ:FXIF:CRGO:LUPL:EN2V:2GZ6:GLT5:IPMK:24MH:SF3N:AZPL:F5PH
WARNING: No swap limit support

root@AMZ-SIN-OpsResPool-33-28:/home/ops# docker info  ====> this AMI has no problem
Containers: 4
Images: 48
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 56
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-36-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 4
Total Memory: 7.305 GiB
Name: AMZ-SIN-OpsResPool-33-28
ID: M762:W772:UWRJ:OECD:XFWF:4DFM:TCA4:Q2PH:QGWD:6W6E:AZVA:RXOL
WARNING: No swap limit support

I believe your suggest is right. But how I can work around this problem? 

root@AMZ-SIN-xxx:/opt/yaas/1.0/bin# docker daemon  --mtu=8973 --insecure-registry aa.com:5000 --insecure-registry xx.com:25000 --insecure-registry gcr.io --insecure-registry gcr.io:5000 --log-level=warning --storage-driver=aufs
FATA[0000] Error starting daemon: error initializing graphdriver: driver not supported 
root@AMZ-SIN-xx:/opt/yaas/1.0/bin# mount
/dev/xvda1 on / type ext4 (rw,discard)
proc on /proc type proc (rw,noexec,nosuid,nodev)
sysfs on /sys type sysfs (rw,noexec,nosuid,nodev)
none on /sys/fs/cgroup type tmpfs (rw)
none on /sys/fs/fuse/connections type fusectl (rw)
none on /sys/kernel/debug type debugfs (rw)
none on /sys/kernel/security type securityfs (rw)
udev on /dev type devtmpfs (rw,mode=0755)
devpts on /dev/pts type devpts (rw,noexec,nosuid,gid=5,mode=0620)
tmpfs on /run type tmpfs (rw,noexec,nosuid,size=10%,mode=0755)
none on /run/lock type tmpfs (rw,noexec,nosuid,nodev,size=5242880)
none on /run/shm type tmpfs (rw,nosuid,nodev)
none on /run/user type tmpfs (rw,noexec,nosuid,nodev,size=104857600,mode=0755)
none on /sys/fs/pstore type pstore (rw)
systemd on /sys/fs/cgroup/systemd type cgroup (rw,noexec,nosuid,nodev,none,name=systemd)
/dev/xvdf on /data type ext4 (rw,_netdev)

**Comment by njuicsgz** [comment]
resolve this problem with: 
`# apt-get install -y linux-image-extra-$(uname -r) linux-image-extra-virtual`
and restart docker daemon with `--storage-driver=aufs`

Close this issue, since it has be handled by [pull/10860](https://github.com/docker/docker/pull/10860)
