### ISSUE TITLE
apt repository instructions fail with http_proxy

### ISSUE THREAD

**Issue by stewart-ibm** [docker/docker#20800]
If you have http_proxy set in your environment, the following command on https://docs.docker.com/engine/installation/linux/ubuntulinux/ fails:

apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

While the following will succeed:
 (gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D; gpg -a --export 2C52609D)|sudo apt-key add -

**Comment by thaJeztah** [comment]
are you still having this issue? or have you found a way to get this working?

**Comment by stewart-ibm** [comment]
I used the alternate command and it worked, although the documentation is still the same, so it'll fail for others in the situation of only having internet access behind a http proxy that they've set just by setting an enironment variable (it's not transferred to the command run through sudo)

**Comment by thaJeztah** [comment]
@stewart-ibm could you open a pull request with the changes you think are required to the docs? The installation docs were moved to a central repository; http://github.com/docker/docker.github.io
