### ISSUE TITLE
Error response from daemon: error creating aufs mount: read-only file system.

### ISSUE THREAD

**Issue by dididado** [docker/docker#20805]
Output of `docker version`:

```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64

```

Output of `docker info`:

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 8
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.16.0-62-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 2.939 GiB
Name: kowalsky
ID: OBOI:MFAB:W56Y:IDCU:WGJK:WDHA:ALJU:DUYJ:4C2N:WI3C:WRWO:3BKG
WARNING: No swap limit support

```
I'm trying to create an image and i always got this error message 

`docker: Error response from daemon: error creating aufs mount to /var/lib/docker/aufs/mnt/620674e960aeccd817471c2bbb1c8df0ce0f58d8ab6c1ff6b87e7cf7919e48c2-init: read-only file system. See 'docker run --help'.`

Of course every time with a different _/var/lib/docker/aufs/mnt/{id}-init/_ folder, I thought of a permission problem but root is able to create and delete files or folder in /mnt/ path.
I tried to remove, install and reboot but I'm out of new ideas.

Provide additional environment details (AWS, VirtualBox, physical, etc.):

```
This is a vm under vmware infrastructure with Ubuntu 14.04.4 LTS
```

List the steps to reproduce the issue:
1. docker run hello-world

Describe the results you received:
docker: Error response from daemon: error creating aufs mount to /var/lib/docker/aufs/mnt/620674e960aeccd817471c2bbb1c8df0ce0f58d8ab6c1ff6b87e7cf7919e48c2-init: read-only file system.
See 'docker run --help'.

Describe the results you expected:
I'm expecting that docker create a container from hello-world image and i'm able to run it.

Provide additional info you think is important:
I'm facing this problem with any image i try to build or run

**Comment by HackToday** [comment]
1 .How did you install that docker in vmware vm ?
2. What's the debug level logs in docker daemon ?

**Comment by dididado** [comment]
I installed it following this guide: https://docs.docker.com/engine/installation/linux/ubuntulinux/
and also using the script with `curl -sSL https://get.docker.com/ | sh`

The daemon is started from ubuntu init script  `services docker start`

To generate daemon debug log i firstly run it with `sudo docker daemon -D` and then `docker run hello-world`

> DEBU[0000] docker group found. gid: 999                 
> DEBU[0000] Server created for HTTP on unix (/var/run/docker.sock) 
> DEBU[0000] Using default logging driver json-file       
> INFO[0000] [graphdriver] using prior storage driver "aufs" 
> DEBU[0000] Using graph driver aufs                      
> INFO[0000] Graph migration to content-addressability took 0.00 seconds 
> DEBU[0000] Option DefaultDriver: bridge                 
> DEBU[0000] Option DefaultNetwork: bridge                
> INFO[0000] Firewalld running: false                     
> DEBU[0000] /sbin/iptables, [--wait -t nat -D PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
> DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER] 
> DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL -j DOCKER] 
> DEBU[0000] /sbin/iptables, [--wait -t nat -D PREROUTING] 
> DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT]    
> DEBU[0000] /sbin/iptables, [--wait -t nat -F DOCKER]    
> DEBU[0000] /sbin/iptables, [--wait -t nat -X DOCKER]    
> DEBU[0000] /sbin/iptables, [--wait -t filter -F DOCKER] 
> DEBU[0000] /sbin/iptables, [--wait -t filter -X DOCKER] 
> DEBU[0000] /sbin/iptables, [--wait -t filter -F DOCKER-ISOLATION] 
> DEBU[0000] /sbin/iptables, [--wait -t filter -X DOCKER-ISOLATION] 
> DEBU[0000] /sbin/iptables, [--wait -t nat -n -L DOCKER] 
> DEBU[0000] /sbin/iptables, [--wait -t nat -N DOCKER]    
> DEBU[0000] /sbin/iptables, [--wait -t filter -n -L DOCKER] 
> DEBU[0000] /sbin/iptables, [--wait -t filter -n -L DOCKER-ISOLATION] 
> DEBU[0000] /sbin/iptables, [--wait -t filter -C DOCKER-ISOLATION -j RETURN] 
> DEBU[0000] /sbin/iptables, [--wait -I DOCKER-ISOLATION -j RETURN] 
> DEBU[0000] Registering ipam driver: "default"           
> DEBU[0000] releasing IPv4 pools from network bridge (5ca2c167e983ee2b12873769023b6882adcc97649ce7076650ace94e01b7ea1d) 
> DEBU[0000] ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.1) 
> DEBU[0000] ReleasePool(LocalDefault/172.17.0.0/16)      
> INFO[0000] Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address 
> DEBU[0000] Allocating IPv4 pools for network bridge (6bcb0b0fd38a8fa4db19905b96aade51362f4871c5da4da9a251cb8cf8f23773) 
> DEBU[0000] RequestPool(LocalDefault, 172.17.0.0/16, , map[], false) 
> DEBU[0000] RequestAddress(LocalDefault/172.17.0.0/16, 172.17.0.1, map[RequestAddressType:com.docker.network.gateway]) 
> DEBU[0000] /sbin/iptables, [--wait -t nat -C POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE] 
> DEBU[0000] /sbin/iptables, [--wait -t nat -C DOCKER -i docker0 -j RETURN] 
> DEBU[0000] /sbin/iptables, [--wait -t nat -I DOCKER -i docker0 -j RETURN] 
> DEBU[0000] /sbin/iptables, [--wait -D FORWARD -i docker0 -o docker0 -j DROP] 
> DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -i docker0 -o docker0 -j ACCEPT] 
> DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -i docker0 ! -o docker0 -j ACCEPT] 
> DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT] 
> DEBU[0000] /sbin/iptables, [--wait -t nat -C PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
> DEBU[0000] /sbin/iptables, [--wait -t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
> DEBU[0000] /sbin/iptables, [--wait -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8] 
> DEBU[0000] /sbin/iptables, [--wait -t nat -A OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8] 
> DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -j DOCKER] 
> DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -j DOCKER] 
> DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -j DOCKER-ISOLATION] 
> DEBU[0000] /sbin/iptables, [--wait -D FORWARD -j DOCKER-ISOLATION] 
> DEBU[0000] /sbin/iptables, [--wait -I FORWARD -j DOCKER-ISOLATION] 
> WARN[0000] Your kernel does not support swap memory limit. 
> DEBU[0000] Cleaning up old shm/mqueue mounts: start.    
> DEBU[0000] Cleaning up old shm/mqueue mounts: done.     
> INFO[0000] Daemon has completed initialization          
> INFO[0000] Docker daemon                                 commit=c3959b1 execdriver=native-0.2 graphdriver=aufs version=1.10.2
> DEBU[0000] Registering routers                          
> DEBU[0000] Registering HEAD, /containers/{name:.*}/archive 
> DEBU[0000] Registering GET, /containers/json            
> DEBU[0000] Registering GET, /containers/{name:.*}/export 
> DEBU[0000] Registering GET, /containers/{name:.*}/changes 
> DEBU[0000] Registering GET, /containers/{name:.*}/json  
> DEBU[0000] Registering GET, /containers/{name:.*}/top   
> DEBU[0000] Registering GET, /containers/{name:.*}/logs  
> DEBU[0000] Registering GET, /containers/{name:.*}/stats 
> DEBU[0000] Registering GET, /containers/{name:.*}/attach/ws 
> DEBU[0000] Registering GET, /exec/{id:.*}/json          
> DEBU[0000] Registering GET, /containers/{name:.*}/archive 
> DEBU[0000] Registering POST, /containers/create         
> DEBU[0000] Registering POST, /containers/{name:.*}/kill 
> DEBU[0000] Registering POST, /containers/{name:.*}/pause 
> DEBU[0000] Registering POST, /containers/{name:.*}/unpause 
> DEBU[0000] Registering POST, /containers/{name:.*}/restart 
> DEBU[0000] Registering POST, /containers/{name:.*}/start 
> DEBU[0000] Registering POST, /containers/{name:.*}/stop 
> DEBU[0000] Registering POST, /containers/{name:.*}/wait 
> DEBU[0000] Registering POST, /containers/{name:.*}/resize 
> DEBU[0000] Registering POST, /containers/{name:.*}/attach 
> DEBU[0000] Registering POST, /containers/{name:.*}/copy 
> DEBU[0000] Registering POST, /containers/{name:.*}/exec 
> DEBU[0000] Registering POST, /exec/{name:.*}/start      
> DEBU[0000] Registering POST, /exec/{name:.*}/resize     
> DEBU[0000] Registering POST, /containers/{name:.*}/rename 
> DEBU[0000] Registering POST, /containers/{name:.*}/update 
> DEBU[0000] Registering PUT, /containers/{name:.*}/archive 
> DEBU[0000] Registering DELETE, /containers/{name:.*}    
> DEBU[0000] Registering GET, /images/json                
> DEBU[0000] Registering GET, /images/search              
> DEBU[0000] Registering GET, /images/get                 
> DEBU[0000] Registering GET, /images/{name:.*}/get       
> DEBU[0000] Registering GET, /images/{name:.*}/history   
> DEBU[0000] Registering GET, /images/{name:.*}/json      
> DEBU[0000] Registering POST, /commit                    
> DEBU[0000] Registering POST, /images/create             
> DEBU[0000] Registering POST, /images/load               
> DEBU[0000] Registering POST, /images/{name:.*}/push     
> DEBU[0000] Registering POST, /images/{name:.*}/tag      
> DEBU[0000] Registering DELETE, /images/{name:.*}        
> DEBU[0000] Registering GET, /networks                   
> DEBU[0000] Registering GET, /networks/{id:.*}           
> DEBU[0000] Registering POST, /networks/create           
> DEBU[0000] Registering POST, /networks/{id:.*}/connect  
> DEBU[0000] Registering POST, /networks/{id:.*}/disconnect 
> DEBU[0000] Registering DELETE, /networks/{id:.*}        
> DEBU[0000] Registering OPTIONS, /{anyroute:.*}          
> DEBU[0000] Registering GET, /_ping                      
> DEBU[0000] Registering GET, /events                     
> DEBU[0000] Registering GET, /info                       
> DEBU[0000] Registering GET, /version                    
> DEBU[0000] Registering POST, /auth                      
> DEBU[0000] Registering GET, /volumes                    
> DEBU[0000] Registering GET, /volumes/{name:.*}          
> DEBU[0000] Registering POST, /volumes/create            
> DEBU[0000] Registering DELETE, /volumes/{name:.*}       
> DEBU[0000] Registering POST, /build                     
> INFO[0000] API listen on /var/run/docker.sock           
> DEBU[0035] Calling POST /v1.22/containers/create        
> DEBU[0035] POST /v1.22/containers/create                
> DEBU[0035] form data: {"AttachStderr":true,"AttachStdin":false,"AttachStdout":true,"Cmd":null,"Domainname":"","Entrypoint":null,"Env":[],"HostConfig":{"Binds":null,"BlkioDeviceReadBps":null,"BlkioDeviceReadIOps":null,"BlkioDeviceWriteBps":null,"BlkioDeviceWriteIOps":null,"BlkioWeight":0,"BlkioWeightDevice":null,"CapAdd":null,"CapDrop":null,"CgroupParent":"","ConsoleSize":[0,0],"ContainerIDFile":"","CpuPeriod":0,"CpuQuota":0,"CpuShares":0,"CpusetCpus":"","CpusetMems":"","Devices":[],"Dns":[],"DnsOptions":[],"DnsSearch":[],"ExtraHosts":null,"GroupAdd":null,"IpcMode":"","Isolation":"","KernelMemory":0,"Links":null,"LogConfig":{"Config":{},"Type":""},"Memory":0,"MemoryReservation":0,"MemorySwap":0,"MemorySwappiness":-1,"NetworkMode":"default","OomKillDisable":false,"OomScoreAdj":0,"PidMode":"","PidsLimit":0,"PortBindings":{},"Privileged":false,"PublishAllPorts":false,"ReadonlyRootfs":false,"RestartPolicy":{"MaximumRetryCount":0,"Name":"no"},"SecurityOpt":null,"ShmSize":0,"UTSMode":"","Ulimits":null,"VolumeDriver":"","VolumesFrom":null},"Hostname":"","Image":"hello-world","Labels":{},"NetworkingConfig":{"EndpointsConfig":{}},"OnBuild":null,"OpenStdin":false,"StdinOnce":false,"StopSignal":"SIGTERM","Tty":false,"User":"","Volumes":{},"WorkingDir":""} 
> ERRO[0035] Couldn't run auplink before unmount: exit status 22 
> ERRO[0035] Clean up Error! Cannot destroy container 055f8f4a96c0a848d3147583d25e1c7ea400b887d3305d616e45893580e67b41: nosuchcontainer: No such container: 055f8f4a96c0a848d3147583d25e1c7ea400b887d3305d616e45893580e67b41 
> ERRO[0035] Handler for POST /v1.22/containers/create returned error: error creating aufs mount to /var/lib/docker/aufs/mnt/82a88073636e7c543c2079e2b3f3eee3076c1adb869894276a301b1c6e4ad00d-init: read-only file system

**Comment by thaJeztah** [comment]
Hm, possibly this is the error; `Couldn't run auplink before unmount: exit status 22`

`read-only file system` could also mean a general issue with the filesystem have you tried `fsck` just to be sure?

**Comment by AkihiroSuda** [comment]
Similar to this?
https://github.com/flynn/flynn/issues/2044

**Comment by dididado** [comment]
i may had made some progress, i found some partitions automatically mounted on /etc/fstab in read-only mode: `none     /run/shm     tmpfs     defaults,ro     0     0`

removing that now i solve the previous problem but now i'm facing a new one:

> # docker run hello-world
> Unable to find image 'hello-world:latest' locally
> latest: Pulling from library/hello-world
> 03f4658f8b78: Pull complete 
> a3ed95caeb02: Pull complete 
> Digest: sha256:8be990ef2aeb16dbcb9271ddfe2610fa6658d13f6dfb8bc72074cc1ca36966a7
> Status: Downloaded newer image for hello-world:latest
> no such file or directory
> docker: Error response from daemon: Container command not found or does not exist..

**debug log:**

> DEBU[0012] Calling GET /v1.22/info                      
DEBU[0012] GET /v1.22/info                              
DEBU[0012] Calling POST /v1.22/images/create            
DEBU[0012] POST /v1.22/images/create?fromImage=hello-world&tag=latest 
DEBU[0012] Trying to pull hello-world from https://registry-1.docker.io v2 
DEBU[0017] Increasing token expiration to: 0 seconds    
DEBU[0018] Pulling ref from V2 registry: hello-world:latest 
DEBU[0018] pulling blob "sha256:03f4658f8b782e12230c1783426bd3bacce651ce582a4ffb6fbbfa2079428ecb" 
DEBU[0018] pulling blob "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4" 
DEBU[0018] Downloaded 03f4658f8b78 to tempfile /var/lib/docker/tmp/GetImageBlob278046642 
DEBU[0018] Downloaded a3ed95caeb02 to tempfile /var/lib/docker/tmp/GetImageBlob349297513 
DEBU[0019] Applied tar sha256:b652ec3a27e758f30de4742156b5d096bb19c82f2dc836e96e430323ba166ffe to 5c054f8b772f14762581292239bce49d5cac3b04afb96ffbe4caf66a1e44a76e, size: 960 
DEBU[0019] Applied tar sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef to 3fb9f111f26b4822484ab4709a66539efe64e672fbfe4be6b5ef3a5fa070dfc0, size: 0 
DEBU[0019] Calling POST /v1.22/containers/create        
DEBU[0019] POST /v1.22/containers/create                
DEBU[0019] form data: {"AttachStderr":true,"AttachStdin":false,"AttachStdout":true,"Cmd":null,"Domainname":"","Entrypoint":null,"Env":[],"HostConfig":{"Binds":null,"BlkioDeviceReadBps":null,"BlkioDeviceReadIOps":null,"BlkioDeviceWriteBps":null,"BlkioDeviceWriteIOps":null,"BlkioWeight":0,"BlkioWeightDevice":null,"CapAdd":null,"CapDrop":null,"CgroupParent":"","ConsoleSize":[0,0],"ContainerIDFile":"","CpuPeriod":0,"CpuQuota":0,"CpuShares":0,"CpusetCpus":"","CpusetMems":"","Devices":[],"Dns":[],"DnsOptions":[],"DnsSearch":[],"ExtraHosts":null,"GroupAdd":null,"IpcMode":"","Isolation":"","KernelMemory":0,"Links":null,"LogConfig":{"Config":{},"Type":""},"Memory":0,"MemoryReservation":0,"MemorySwap":0,"MemorySwappiness":-1,"NetworkMode":"default","OomKillDisable":false,"OomScoreAdj":0,"PidMode":"","PidsLimit":0,"PortBindings":{},"Privileged":false,"PublishAllPorts":false,"ReadonlyRootfs":false,"RestartPolicy":{"MaximumRetryCount":0,"Name":"no"},"SecurityOpt":null,"ShmSize":0,"UTSMode":"","Ulimits":null,"VolumeDriver":"","VolumesFrom":null},"Hostname":"","Image":"hello-world","Labels":{},"NetworkingConfig":{"EndpointsConfig":{}},"OnBuild":null,"OpenStdin":false,"StdinOnce":false,"StopSignal":"SIGTERM","Tty":false,"User":"","Volumes":{},"WorkingDir":""} 
DEBU[0019] container mounted via layerStore: /var/lib/docker/aufs/mnt/74656fa68f385d594fdc40691e8c3def37bc4ecbc01d951b906276cf317c01ec 
DEBU[0019] Calling POST /v1.22/containers/d3d2ceebdea4dc141a9d1f8a0e47c022c349a061564afd46a54a37a96b896210/attach 
DEBU[0019] POST /v1.22/containers/d3d2ceebdea4dc141a9d1f8a0e47c022c349a061564afd46a54a37a96b896210/attach?stderr=1&stdout=1&stream=1 
DEBU[0019] attach: stdout: begin                        
DEBU[0019] attach: stderr: begin                        
DEBU[0019] Calling POST /v1.22/containers/d3d2ceebdea4dc141a9d1f8a0e47c022c349a061564afd46a54a37a96b896210/start 
DEBU[0019] POST /v1.22/containers/d3d2ceebdea4dc141a9d1f8a0e47c022c349a061564afd46a54a37a96b896210/start 
DEBU[0019] container mounted via layerStore: /var/lib/docker/aufs/mnt/74656fa68f385d594fdc40691e8c3def37bc4ecbc01d951b906276cf317c01ec 
DEBU[0019] Assigning addresses for endpoint thirsty_carson's interface on network bridge 
DEBU[0019] RequestAddress(LocalDefault/172.17.0.0/16, <nil>, map[]) 
DEBU[0019] Assigning addresses for endpoint thirsty_carson's interface on network bridge 
WARN[0019] exit status 1                                
DEBU[0019] attach: stdout: end                          
DEBU[0019] attach: stderr: end                          
DEBU[0019] Releasing addresses for endpoint thirsty_carson's interface on network bridge 
DEBU[0019] ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.2) 
ERRO[0019] error locating sandbox id 12e101c9dd2d32a24621db7b9c391db83fe3148a399258eb230479842e807c80: sandbox 12e101c9dd2d32a24621db7b9c391db83fe3148a399258eb230479842e807c80 not found 
WARN[0019] failed to cleanup ipc mounts:
failed to umount /var/lib/docker/containers/d3d2ceebdea4dc141a9d1f8a0e47c022c349a061564afd46a54a37a96b896210/shm: invalid argument 
ERRO[0019] Error unmounting container d3d2ceebdea4dc141a9d1f8a0e47c022c349a061564afd46a54a37a96b896210: not mounted 
ERRO[0019] Handler for POST /v1.22/containers/d3d2ceebdea4dc141a9d1f8a0e47c022c349a061564afd46a54a37a96b896210/start returned error: Container command not found or does not exist.

**Comment by dididado** [comment]
I finally solve my problem, last one was caused by me messing with AppArmor.
I simply unlink `/etc/apparmor.d/disable/docker`
