### ISSUE TITLE
Dockerfile and change control management

### ISSUE THREAD

**Issue by adowner** [docker/docker#20811]
After using docker for a while across a number of projects, we ran into a bottleneck in the way docker works for us.

We have a number of layers for each project.
Example:

1. FROM centos
2. FROM base:1
3. FROM appSystem:1
4. Application Specific Layer

Our change control process means that (in the event we change layer 1) generating branches and pull requests for every layer that uses the base image (1). Even if the base image is only shared by 5 projects, that is 15 separate branches and pull requests in order to roll this out.

**Using 'From base:latest' in dockerfiles**
This would solve the issue of having to generate all those branches and PR's. However, it also destroys the ability to go back to previous versions of code and regenerate a specific version of an image for investigation. This is because when you have checked out the code and run the build, you get the latest, which might not actually work any more depending on the intervening changes.

**What would be nice/ Feature request**
A mechanism to translate the 'latest' in a dockerFile into the actual version being used at time of the build. This is very similar to what is provided in [maven versions plugin](http://www.mojohaus.org/versions-maven-plugin/use-releases-mojo.html) but with a much more focused scope. The updated dockerFile could then be easily committed to a tag in git allowing for master to continue using latest and the tagged version serving recreation purposes and no one having to raise multiple pull requests for small changes. I have searched the currently open (and closed) issues and can not find a duplicate of this, but please let me know if there is one (or if a way to do this already exists without super fancy scripting)

**Comment by thaJeztah** [comment]
You can use the digest / immutable tag to get a specific version, for example:

```bash
docker pull hello-world
Using default tag: latest
latest: Pulling from library/hello-world
03f4658f8b78: Pull complete
a3ed95caeb02: Pull complete
Digest: sha256:8be990ef2aeb16dbcb9271ddfe2610fa6658d13f6dfb8bc72074cc1ca36966a7
Status: Downloaded newer image for hello-world:latest
```

Which also is visible if you use `docker images --digests`:

```
REPOSITORY            TAG                         DIGEST                                                                    IMAGE ID            CREATED             SIZE
hello-world           latest                      <none>                                                                    690ed74de00f        4 months ago        960 B
hello-world           <none>                      sha256:8be990ef2aeb16dbcb9271ddfe2610fa6658d13f6dfb8bc72074cc1ca36966a7   690ed74de00f        4 months ago        960 B
```

You can use that digest as your FROM to pin to a specific version, e.g.

```Dockerfile
FROM hello-world@sha256:8be990ef2aeb16dbcb9271ddfe2610fa6658d13f6dfb8bc72074cc1ca36966a7
```

You may be interested in Docker content trust: https://docs.docker.com/engine/security/trust/content_trust/

I'm not sure if automatically modifying a Dockerfile should be core functionality of docker, but with the information above, I think it should be possibly to achieve that using a simple shell script

**Comment by adowner** [comment]
ahhh V2 goodness. I can confirm that this approach would using using a simple script like the example below. Thanks
`IMAGENAME="$(head -n 1 Dockerfile | cut -c6-)"                     # get everything after the FROM
PULLOUTPUT="$(docker pull $IMAGENAME)"
IMAGEDIGEST="$(echo $PULLOUTPUT | grep Digest | cut -c9-)"                        # grab the digest for the pulled image
sed -i '1s/.*/FROM $IMAGENAME@$IMAGEDIGEST/' Dockerfile   # replace the original from with the digest specific one`
