### ISSUE TITLE
docker attach all for container output

### ISSUE THREAD

**Issue by rca** [docker/docker#2082]
During Docker Hack Day we discussed options around Docker having the ability to automatically attach to all containers and provide their output to a single stream that can then be sent to an external service such as syslog.

A couple of scenarios came about:

- leave it up to a client application to attach to the streams; but this needs to be done with care in order to not lose any output between starting the container and attaching to the log stream

- implement the logic within docker; but how to provide it in a general enough way so it can be used for miscellaneous use-cases

Additionally, Docker has two facilities for getting information: `events` and `attach`.  The `events` command output appears to be for logging docker actions and `attach` appears to be for output generated by the containerized application.  Is extending attach the right place for this feature?

Finally, attaching to `stdin` doesn't seem to apply here, should "attach all" explicitly exclude stdin?

Please share your thoughts.

Thanks!

**Comment by cpuguy83** [comment]
I think the solution here is the docker logging drivers. In 1.6 you can send all container logs to syslog.
Journald has been added sense then, and others are being developd by other parties (such as fluentd).

I think we can close this one now.

**Comment by cpuguy83** [comment]
In fact, I think I'm going to go ahead and close it, but can discuss if you don't feel like this solves the issue.
