### ISSUE TITLE
Docker daemon can't start after upgrading from ver1.9.0 to ver ver1.10.2

### ISSUE THREAD

**Issue by hujb2000** [docker/docker#20849]
root@hjb:/home/hjb# docker version
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:30:48 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

root@hjb:/home/hjb# docker info
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

root@hjb:/home/hjb# docker daemon -D
DEBU[0000] docker group found. gid: 999                 
DEBU[0000] Server created for HTTP on unix (/var/run/docker.sock) 
DEBU[0000] Using default logging driver json-file       
INFO[0000] [graphdriver] using prior storage driver "aufs" 
DEBU[0000] Using graph driver aufs                      
INFO[0001] Graph migration to content-addressability took 0.03 seconds 
DEBU[0001] Option DefaultDriver: bridge                 
DEBU[0001] Option DefaultNetwork: bridge                
INFO[0001] Firewalld running: false                     
DEBU[0001] /sbin/iptables, [-t nat -D PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0001] /sbin/iptables, [-t nat -D OUTPUT -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER] 
DEBU[0001] /sbin/iptables, [-t nat -D OUTPUT -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0001] /sbin/iptables, [-t nat -D PREROUTING]       
DEBU[0001] /sbin/iptables, [-t nat -D OUTPUT]           
DEBU[0001] /sbin/iptables, [-t nat -F DOCKER]           
DEBU[0001] /sbin/iptables, [-t nat -X DOCKER]           
DEBU[0001] /sbin/iptables, [-t filter -F DOCKER]        
DEBU[0001] /sbin/iptables, [-t filter -X DOCKER]        
DEBU[0001] /sbin/iptables, [-t filter -F DOCKER-ISOLATION] 
DEBU[0001] /sbin/iptables, [-t filter -X DOCKER-ISOLATION] 
DEBU[0001] /sbin/iptables, [-t nat -n -L DOCKER]        
DEBU[0001] /sbin/iptables, [-t nat -N DOCKER]           
DEBU[0001] /sbin/iptables, [-t filter -n -L DOCKER]     
DEBU[0001] /sbin/iptables, [-t filter -n -L DOCKER-ISOLATION] 
DEBU[0001] /sbin/iptables, [-t filter -C DOCKER-ISOLATION -j RETURN] 
DEBU[0001] /sbin/iptables, [-I DOCKER-ISOLATION -j RETURN] 
DEBU[0001] /sbin/iptables, [-t nat -C POSTROUTING -s 172.18.0.0/16 ! -o br-1f8f9aeda596 -j MASQUERADE] 
DEBU[0001] /sbin/iptables, [-t nat -C DOCKER -i br-1f8f9aeda596 -j RETURN] 
DEBU[0001] /sbin/iptables, [-t nat -I DOCKER -i br-1f8f9aeda596 -j RETURN] 
DEBU[0001] /sbin/iptables, [-D FORWARD -i br-1f8f9aeda596 -o br-1f8f9aeda596 -j DROP] 
DEBU[0001] /sbin/iptables, [-t filter -C FORWARD -i br-1f8f9aeda596 -o br-1f8f9aeda596 -j ACCEPT] 
DEBU[0001] /sbin/iptables, [-t filter -C FORWARD -i br-1f8f9aeda596 ! -o br-1f8f9aeda596 -j ACCEPT] 
DEBU[0001] /sbin/iptables, [-t filter -C FORWARD -o br-1f8f9aeda596 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT] 
DEBU[0001] /sbin/iptables, [-t nat -C PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0001] /sbin/iptables, [-t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0001] /sbin/iptables, [-t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8] 
DEBU[0001] /sbin/iptables, [-t nat -A OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8] 
DEBU[0001] /sbin/iptables, [-t filter -C FORWARD -o br-1f8f9aeda596 -j DOCKER] 
DEBU[0001] /sbin/iptables, [-t filter -C FORWARD -o br-1f8f9aeda596 -j DOCKER] 
DEBU[0001] /sbin/iptables, [-t filter -C FORWARD -j DOCKER-ISOLATION] 
DEBU[0001] /sbin/iptables, [-D FORWARD -j DOCKER-ISOLATION] 
DEBU[0001] /sbin/iptables, [-I FORWARD -j DOCKER-ISOLATION] 
DEBU[0001] Registering ipam driver: "default"           
DEBU[0001] Cleaning up old shm/mqueue mounts: start.    
FATA[0001] Error starting daemon: Error initializing network controller: could not delete the default bridge network: network bridge has active endpoints 
root@hjb:/home/hjb# 

docker engine install in the debian wheezy
root@hjb:/home/hjb# uname -r
3.16.0-0.bpo.4-amd64

List the steps to reproduce the issue:
1. work in the version 1.9.0 of docker engine,   
2. I want to upgrade the docker engine's version from 1.9.0 to  version 1.10.2, sudo run  apt-get install docker-engine 
3. docker daemon -D

the result is that the new version daemon can't start normaly, the above information as debug info

I  think in advance that run docker version to look docker client and docker daemon's new version information.

Then,  It do work after rm -rf /var/lib/docker , why ?????

**Comment by hujb2000** [comment]
@vlerenc it seems like the local db (/var/lib/docker/network/files/local-kv.db) is corrupted. Could you pls take a backup of that file (and share it with us ?). once its backed up, pls remove this file and restart the daemon.
We have to identify how and when the file is corrupted.      It works  referece  #20694

**Comment by niko** [comment]
Had the same issue on Arch Linux. I updated some packages and rebooted several times. Maybe the reboot interrupted the image migration process? Removing /var/lib/docker/network/files/local-kv.db fixed it, though.
