### ISSUE TITLE
requesting "disable-content-trust" equivalent for docker api when pulling an image

### ISSUE THREAD

**Issue by dteeter** [docker/docker#20840]
I would like to do the equivalent of setting "disable-content-trust=false" when calling the docker API and pulling an image (i.e. when posting to /images/create) 

This is the only aspect of the CLI that is not supported in the API AFAIK.

**Comment by cpuguy83** [comment]
Seems like a dup of #16654, WDYT?

**Comment by thaJeztah** [comment]
Yes, let's close this one and keep the discussion in a single place. I'll close this issue in favor of https://github.com/docker/docker/issues/16654, please continue the discussion there

**Comment by dteeter** [comment]
I did see #16654, but it was unclear if "Notary signature verification" was referring to what Docker commonly calls "Content Trust". The title of #16654 is misleading i.e. the setting is not "ineffective", its missing entirely. Would it be possible to alter the title to something like "Content Trust setting capability missing for Remote API users"?

**Comment by cpuguy83** [comment]
@dteeter The issue here is it's not missing, it's purely a client-side implementation, meaning the docker daemon itself does nothing at all with content trust.

**Comment by dteeter** [comment]
It's not clear to me how the capabilities of the docker cli and remote api can be almost identical in every respect except in the case of this feature (would be great to understand this better).

For use cases where a docker machine is being managed via the api, this missing capability prevents adoption of the content trust capability (especially if you wish to use a mix of signed and unsigned images).

**Comment by cpuguy83** [comment]
@dteeter You should check out the content of the mentioned issue.
Really there's lot of things that the docker CLI does that the daemon doesn't do on it's own.

Content trust is a feature of the docker client since it is a user concern, and other clients can also implement content trust as well.
Not saying that it won't ever be possible to do this via the API, but currently it's fully implemented client side. There is nothing being hidden from the API, it just doesn't exist at all except in the client.

**Comment by dteeter** [comment]
OK that explains it, I had just assumed that both the api and the cli sat on top of the same client code base (i.e. I assumed that whether I was doing a "docker ps" or a "GET /containers/json", the result was ultimately coming from the same client code base ).

Why the separation?

**Comment by cpuguy83** [comment]
@dteeter the client is calling `GET /containers/json` and all that.
The client is calling the same API that you do.

**Comment by dteeter** [comment]
You mean, when I run "docker ps" in the cli that is, in turn, calling "GET /containers/json"? 

In that case, what is the cli sending to the api when I run "docker pull --disable-content-trust=false imageName:tagName" ?

**Comment by cpuguy83** [comment]
@dteeter See https://github.com/docker/docker/blob/master/api/client/trust.go#L305
