### ISSUE TITLE
Running a container becomes slower when a large number of containers are alive

### ISSUE THREAD

**Issue by inatatsu** [docker/docker#20851]
The time to run and also stop one container increases in proportion to the number of live containers in a daemon (please see the numbers below). The primary overhead is processor cycles to sequentially parse `/proc/self/mountinfo`. Since the rootfs mount points of all of the live containers are visible to the daemon, the file size of `mountinfo` grows proportionally to the number of live containers.

Docker daemon and RunC parse `/proc/self/mountinfo` for various purposes. Docker daemon parses `mountinfo` to:
* [Check](https://github.com/docker/docker/blob/b18f9cc29b8977bc003fd47aa35e8836345c301d/daemon/graphdriver/aufs/aufs.go#L461) whether or not a rootfs is mounted.

RunC parses `mountinfo` to:
* [Locate](https://github.com/opencontainers/runc/blob/177f2c405cc0f4fc027f7210675350e9be2b515c/libcontainer/cgroups/utils.go#L26) the mount point of a cgroup subsystem (opencontainers/runc#496 reduces this overhead),
* [Locate](https://github.com/opencontainers/runc/blob/177f2c405cc0f4fc027f7210675350e9be2b515c/libcontainer/selinux/selinux.go#L61) the mount point of SELinux, and
* Check the mount flags of the [parent mount](https://github.com/opencontainers/runc/blob/177f2c405cc0f4fc027f7210675350e9be2b515c/libcontainer/rootfs_linux.go#L478) of a rootfs.

Since the current Linux kernel does not yet provide convenient system calls to get full information of and mapping to a specific mount point, we need a different solution for each usage of `mountinfo`, to eliminate this parsing overhead.

Output of `docker version`:

```
Client:
 Version:      1.11.0-dev
 API version:  1.23
 Go version:   devel +8bfd600 Thu Feb 25 15:02:24 2016 -0500
 Git commit:   5ef74c6-unsupported
 Built:        Tue Mar  1 02:22:14 2016
 OS/Arch:      linux/s390x

Server:
 Version:      1.11.0-dev
 API version:  1.23
 Go version:   devel +8bfd600 Thu Feb 25 15:02:24 2016 -0500
 Git commit:   5ef74c6-unsupported
 Built:        Tue Mar  1 02:22:14 2016
 OS/Arch:      linux/s390x
```

Output of `docker info`:

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.11.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/graph-0/aufs
 Backing Filesystem: xfs
 Dirs: 3
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.3.3_aufs
Operating System: Red Hat Enterprise Linux Server 7.1 (Maipo)
OSType: linux
Architecture: s390x
CPUs: 4
Total Memory: 31.44 GiB
Name: inagaki
ID: Z4GL:4KNZ:LB3Z:FIJF:32WT:C25M:3AOT:3C72:FWR7:VHSG:VUAJ:67GP
Docker Root Dir: /var/lib/docker/graph-0
Debug mode (client): false
Debug mode (server): false
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):

The operating system is RHEL 7.1 with a custom kernel (i.e. stable 4.3.3 + aufs), configured with RHEL 7.1. Docker Engine is a recent master branch compiled with [the Go language ported on z Systems](https://github.com/linux-on-ibm-z/go). While my measurement was done on s390x, this issue will reproduce on any platform.

List the steps to reproduce the issue:

Run a number of containers successively with keeping them alive, and measure the mean time to run one container. An example script is `echo $({ /usr/bin/time -f "%e" bash -c "for i in $(seq -s ' ' 1 $NUM_CONTAINERS); do docker run -d -t busybox > /dev/null; done"; } 2>&1) / $NUM_CONTAINERS | bc -l`.

Describe the results you received:

Number of total containers | Mean time to run one container (seconds)
----------------------------- | --------------------------------------------------
64 | .29015625
2048 | .9103125

Describe the results you expected:

Ideally, the time to run one container should be constant and irrelevant to the number of live containers. While Linux kernel and systemd also have some overheads, the primary overhead comes from userland cycles in Docker daemon and RunC.

Provide additional info you think is important:

**Comment by thaJeztah** [comment]
Thanks @inatatsu for doing the research and an excellent bug-report

**Comment by inatatsu** [comment]
To make opencontainers/runc#608 merged into RunC and imported into Docker, should I submit a separate issue report and a pull request?

**Comment by inatatsu** [comment]
The latest master with opencontainers/runc#608 reduces the time to run 2k busybox containers down to .4331689453125 seconds (2.1x faster).

**Comment by thaJeztah** [comment]
@inatatsu yes, please open a separate issue or pull request, but you can refer to / mention this one

**Comment by inatatsu** [comment]
@thaJeztah Opened opencontainers/runc#631 as a replicated issue. Thanks!
