### ISSUE TITLE
Whether the docker clound agent only work in the Debian 8(jessie)

### ISSUE THREAD

**Issue by hujb2000** [docker/docker#20850]
root@hjb:/home/hjb# docker version
Client:
Version: 1.10.2
API version: 1.22
Go version: go1.5.3
Git commit: c3959b1
Built: Mon Feb 22 21:30:48 2016
OS/Arch: linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

root@hjb:/home/hjb# docker info
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

root@hjb:/home/hjb# curl -Ls https://get.cloud.docker.com/ | sudo -H sh -s f7f2bbe744044442b34ae0b2624d156a
-> Adding Docker Cloud's GPG key...
gpg: directory `/root/.gnupg' created
gpg: new configuration file `/root/.gnupg/gpg.conf' created
gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/root/.gnupg/secring.gpg' created
gpg: keyring `/root/.gnupg/pubring.gpg' created
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key EF170D1C: public key "Tutum Inc. (tutum) <info@tutum.co>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
-> Installing required dependencies...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package linux-image-extra-3.16.0-0.bpo.4-amd64
E: Couldn't find any package by regex 'linux-image-extra-3.16.0-0.bpo.4-amd64'
!! Failed to install linux-image-extra package. AUFS support (which is recommended) may not be available.
-> Installing dockercloud-agent...
Reading package lists...
Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
  init-system-helpers libevent-2.0-5
Use 'apt-get autoremove' to remove them.
The following packages will be REMOVED:
  docker-engine
The following NEW packages will be installed:
  dockercloud-agent
0 upgraded, 1 newly installed, 1 to remove and 8 not upgraded.
Need to get 2401 kB of archives.
After this operation, 34.4 MB disk space will be freed.
Get:1 http://repo.cloud.docker.com/ubuntu/ dockercloud/main dockercloud-agent amd64 1.0.0 [2401 kB]
Fetched 2401 kB in 11s (204 kB/s)
(Reading database ... 99135 files and directories currently installed.)
Removing docker-engine ...
[....] Stopping Docker: dockerstart-stop-daemon: warning: failed to kill 5491: No such process
No process in pidfile '/var/run/docker-ssd.pid' found running; none killed.
invoke-rc.d: initscript docker, action "stop" failed.
dpkg: error processing docker-engine (--remove):
 subprocess installed pre-removal script returned error exit status 1
dpkg: error while cleaning up:
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 docker-engine
E: Sub-process /usr/bin/dpkg returned an error code (1)

expected:   install docker cloud agent successful.

Whether the docker clound agent only work in the Debian 8(jessie) and not  support debian 7(wheezy)?

**Comment by thaJeztah** [comment]
Yes, requirements state that Debian 8 is required; https://docs.docker.com/docker-cloud/tutorials/byoh/

**Comment by unclejack** [comment]
I'll close this issue now as it's documented in the official docs and it's also not a Docker engine issue. This repository is mostly for Docker engine issues.
