### ISSUE TITLE
"Your kernel does not support kernel memory limit" on debian jessie

### ISSUE THREAD

**Issue by sharminakteranee** [docker/docker#20856]
For default debian-jessie [ kernel --> 3.16.0] 
If we enable memory and swap [[GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"]]
and update the grub, we find the following results------- 
$ docker info
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

$ journalctl -u docker
"Your kernel does not support cgroup memory limit: mountpoint for memory not found"
"Your kernel does not support cgroup cfs period"
"Your kernel does not support cgroup cfs quotas"
![journalctl -u docker](https://cloud.githubusercontent.com/assets/14119830/13458046/78eaf8d2-e095-11e5-81f0-a06ad463759e.png)

Then we upgrade the kernel to 4.3.0, and docker info shows no warning, but
$ journalctl -u docker
"Your kernel does not support kernel memory
![docker info](https://cloud.githubusercontent.com/assets/14119830/13458037/6ea79c36-e095-11e5-8f06-04af1217adb1.png)
 limit"
![journalctl -u docker-for-kernel-4 3 0](https://cloud.githubusercontent.com/assets/14119830/13458058/8da0327e-e095-11e5-80af-5a9f7e77ac8c.png)

Now, how can I realize that the memory controller is actually working here or not, any suggestions??

**Comment by Nitro-N** [comment]
How you did resolve this problem?

**Comment by jodumont** [comment]
@Nitro-N It's probably link to your kernel version
With kernel 4.9.20 I don't have the memory error

**Comment by viossat** [comment]
To resolve memory limit support I edited the GRUB config, see #396.
I resolved CPU limit support by upgrading the kernel to 4.9.
