### ISSUE TITLE
"Your kernel does not support kernel memory limit" on debian jessie

### ISSUE THREAD

**Issue by sharminakteranee** [docker/docker#20857]
For default debian-jessie [ kernel --> 3.16.0] 

If we enable memory and swap [[GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"]]
and update the grub, we find the following results------- 

docker version: 1.10.2
$ docker info
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
![docker info](https://cloud.githubusercontent.com/assets/14119830/13458173/39b47368-e096-11e5-9cb5-a313f3d8eb24.png)

$ journalctl -u docker
"Your kernel does not support cgroup memory limit: mountpoint for memory not found"
"Your kernel does not support cgroup cfs period"
"Your kernel does not support cgroup cfs quotas"
![journalctl -u docker](https://cloud.githubusercontent.com/assets/14119830/13458209/5c51e96e-e096-11e5-8901-eef30a4589d6.png)

Then we upgrade the kernel to 4.3.0, and docker info shows no warning, but
$ journalctl -u docker
"Your kernel does not support kernel memory limit"
![journalctl -u docker-for-kernel-4 3 0](https://cloud.githubusercontent.com/assets/14119830/13458213/61d9ac1e-e096-11e5-948a-f90d9b4671f7.png)

Now, how can I realize that the memory controller is actually working here or not, any suggestions??

**Comment by thaJeztah** [comment]
I think these options need to be enabled in your kernel config, also, I see kernel memory is still marked "experimental" http://cateee.net/lkddb/web-lkddb/MEMCG_KMEM.html

Note that there's also this script to check which features are enabled in your kernel, and if all the required options are present; https://github.com/docker/docker/blob/master/contrib/check-config.sh

**Comment by thaJeztah** [comment]
Looks like we have this information available; https://github.com/docker/docker/blob/c91045a78bf138aa32acd215fed4084d3b912bec/pkg/sysinfo/sysinfo_linux.go#L82-L110,
so we can add a warning for kernel memory to be consistent https://github.com/docker/docker/blob/80187df25708782db20846e63aef7ddb0419c7cf/api/client/info.go#L101-L130

**Comment by ehazlett** [comment]
I'm going to close this as #20863 is merged.  Please open a new issue if you feel this is not resolved.  Thanks!

**Comment by cnrmck** [comment]
Note: prior to running the [script to check which features are enabled in your kernel](https://github.com/docker/docker/blob/master/contrib/check-config.sh) recommended by @thaJeztah, run 
`sudo modprobe configs`
