### ISSUE TITLE
docker build image failed, failed to fetch xxx size mismatcth

### ISSUE THREAD

**Issue by suiyuan2009** [docker/docker#20867]
Output of `docker version`:

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:16:54 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:16:54 UTC 2015
 OS/Arch:      linux/amd64

```

Output of `docker info`:

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:16:54 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:16:54 UTC 2015
 OS/Arch:      linux/amd64
suiyuan2009@suiyuan2009-Lenovo-Product:~/repos/docker-fork$ docker info 
Containers: 16
Images: 127
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 159
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-50-generic
Operating System: Ubuntu 15.04
CPUs: 4
Total Memory: 7.738 GiB
Name: suiyuan2009-Lenovo-Product
ID: D2OJ:DSYE:X4SB:XF7H:2HYF:RH6D:EYPX:JX4C:CAWK:SIMZ:KYMH:MOYV
Username: suiyuan2009
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

```

Provide additional environment details (AWS, VirtualBox, physical, etc.):
ubuntu15.04 desktop amd64

List the steps to reproduce the issue:
1.docker build -t 20801-add-ubuntu-notice .

Describe the results you received:
E: Failed to fetch http://httpredir.debian.org/debian/pool/main/p/python3.4/python3.4-minimal_3.4.2-1_amd64.deb  Size mismatch

E: Failed to fetch http://httpredir.debian.org/debian/pool/main/p/python3.4/python3.4_3.4.2-1_amd64.deb  Size mismatch

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c apt-get update && apt-get install -y 	apparmor 	aufs-tools 	automake 	bash-completion 	btrfs-tools 	build-essential 	clang-3.8 	createrepo 	curl 	dpkg-sig 	gcc-mingw-w64 	git 	iptables 	jq 	libapparmor-dev 	libcap-dev 	libltdl-dev 	libsqlite3-dev 	libsystemd-journal-dev 	libtool 	mercurial 	net-tools 	pkg-config 	python-dev 	python-mock 	python-pip 	python-websocket 	s3cmd=1.5.0* 	ubuntu-zfs 	xfsprogs 	libzfs-dev 	tar 	--no-install-recommends 	&& ln -snf /usr/bin/clang-3.8 /usr/local/bin/clang 	&& ln -snf /usr/bin/clang++-3.8 /usr/local/bin/clang++' returned a non-zero code: 100

Describe the results you expected:

Provide additional info you think is important:

**Comment by thaJeztah** [comment]
Looking at that error, I doubt this is a bug in Docker, It looks like there's an issue downloading packages from the debian apt repository, or a mirror doesn't have that file

**Comment by suiyuan2009** [comment]
`sudo dpkg -i python3.4_3.4.2-1_amd64.deb 
dpkg: warning: downgrading python3.4 from 3.4.3-3 to 3.4.2-1
(Reading database ... 524614 files and directories currently installed.)
Preparing to unpack python3.4_3.4.2-1_amd64.deb ...
Unpacking python3.4 (3.4.2-1) over (3.4.3-3) ...
dpkg: dependency problems prevent configuration of python3.4:
 python3.4 depends on python3.4-minimal (= 3.4.2-1); however:
  Version of python3.4-minimal on system is 3.4.3-3.
 python3.4 depends on libpython3.4-stdlib (= 3.4.2-1); however:
  Version of libpython3.4-stdlib:amd64 on system is 3.4.3-3.

dpkg: error processing package python3.4 (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.10.1-0ubuntu5) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu3) ...
Processing triggers for bamfdaemon (0.5.1+15.04.20150202-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mime-support (3.58ubuntu1) ...
Processing triggers for man-db (2.7.0.2-5) ...
Errors were encountered while processing:
 python3.4
`

**Comment by thaJeztah** [comment]
Is that done inside the container, or on your host? Also note that Ubuntu 15.04 is EOL, so no updates are published anymore for 15.04 (both docker and by Ubuntu)

I don't see anything in there that's possibly related to Docker; in your Dockerfile, so you have `apt-get update` and `apt-get install` on the same line? Otherwise you may be using outdated caches for apt

**Comment by suiyuan2009** [comment]
@thaJeztah   on my host, `apt-get update` and `apt-get install` is on the same line.  I have python3.4 version 3.4.3-3 in my host, but it seems that I should use python3.4 version 3.4.2-1?

**Comment by thaJeztah** [comment]
@suiyuan2009 I wouldn't know, could be. However, if that previous example was run on your host, not inside a container, then it confirms that this really isn't a docker bug.

I'll close this issue, because it really isn't a docker bug here, but feel free to comment after I've closed

**Comment by suiyuan2009** [comment]
@thaJeztah   I find the version of ubuntu in the docker container is 14.04, can I use container as my dev environment to solve this issue?
