### ISSUE TITLE
Detaching from a container in Mac OS X

### ISSUE THREAD

**Issue by pcgeek86** [docker/docker#20864]
I'm struggling to detach from a running container on Mac OS X. From the Docker documentation, I understand that `CTRL + P, CTRL + Q` is used to detach from a container.

- The container was *not* started with the `-d` argument
- Using iTerm2 and the native Mac OS X Terminal app
- `^P` is printed to the terminal, but `CTRL + Q` prints nothing

<img width="378" alt="screen shot 2016-03-02 at 7 34 32 am" src="https://cloud.githubusercontent.com/assets/466713/13463429/6dc4bfc0-e049-11e5-8821-b5473186f8f5.png">

I suspect that this is simply a terminal configuration issue, or perhaps a misunderstanding of ASCII control codes on my part. At this point, I don't suspect a bug, but I figured this would be the best place to get some help (sorry if that's not right). Any guidance please?

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by thaJeztah** [comment]
Did you start the container with `-it`I think otherwise the detach may not work

**Comment by HackToday** [comment]
Yes, -it is needed to hot-key to work for that

**Comment by pcgeek86** [comment]
@thaJeztah Thanks, didn't realize that. So it has to be started in interactive mode, in order for the hotkey to work. :+1:

**Comment by jamshid** [comment]
I would file a third bug about this issue but I guess it will be closed? 
Seems you should be able to exit a `docker run ...` (without doing an OS kill), even if `-it` is not used.
