### ISSUE TITLE
Flaky Test: TestBuildApiDoubleDockerfile

### ISSUE THREAD

**Issue by sainath14** [docker/docker#20886]
Test is looking for StatusOK message, but receiving 500 "Internal Server Error".

----------------------------------------------------------------------
FAIL: docker_api_build_test.go:204: DockerSuite.TestBuildApiDoubleDockerfile

docker_api_build_test.go:218:
    c.Assert(res.StatusCode, checker.Equals, http.StatusOK)
... obtained int = 500
... expected int = 200

Client:
 Version:      1.11.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   286a272-unsupported
 Built:        Wed Mar  2 23:11:54 2016
 OS/Arch:      linux/amd64

**Comment by thaJeztah** [comment]
This test is no longer there, so closing
