### ISSUE TITLE
Lots of Zombie processes created by Docker

### ISSUE THREAD

**Issue by pjebs** [docker/docker#20893]
1) I have a program written in Go that operates along side the Docker host.

2) The Go program kick starts containers that run a program ( eg ipm).

`err := exec.Command("docker", "run", "-P", "-d", "--name="+token, "ipm").Run()`

3) The program (ipm) sometimes (intentionally) automatically exits. That is normal behaviour and does not *seem* to result in zombies.

4) However, if the program does not exit (also normal behaviour), my Go program destroys the container that operates the program after a fixed duration of T seconds.

`err := exec.Command("docker", "rm", "-f", token).Start()`

5) When the Go program terminates the container running ipm, then the container seems to become a zombie.

6) If I run `ps auxf` you can see that the Docker containers that I destroyed get adopted by the Go program that executed the command to destroy it:

![screen shot 2016-03-03 at 2 08 03 pm](https://cloud.githubusercontent.com/assets/5377970/13483578/adedf43a-e149-11e5-9ee0-c9c70af98fa4.png)

More info: Read: https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/

**Comment by pjebs** [comment]
BUG REPORT INFORMATION

**Comment by pjebs** [comment]
I believe `docker stop` and then `docker rm` seems to solve the problem.

**Comment by pjebs** [comment]
But why is `docker rm -f` doing this in the first place? This must be a bug.

**Comment by phemmer** [comment]
This looks like a bug in your program, not docker. In your screenshot, those aren't the containers becoming zombies, those are the `docker rm -f` commands.
You're using `(*exec.Cmd).Start()`, so unless you call `(*exec.Cmd).Wait()`, you're going to get zombies.

**Comment by pjebs** [comment]
No.
.start() starts the command and doesn't wait for response from program. In my case I don't care what the results are from the docker command. In fact `docker ps -a` shows that the containers have been destroyed.

Secondly I tried it with .Run() which does wait for command to finish and it's the same result - zombies.

Bear in mind the containers ARE DESTROYED in both cases.

**Comment by phemmer** [comment]
No.

```
package main

import (
	"fmt"
	"os/exec"
	"time"
)

func main() {
	for i := 0; i < 30; i++ {
		exec.Command("/bin/true").Start()
	}
	time.Sleep(time.Second)
	out, err := exec.Command("/bin/sh", "-c", "ps ax|grep true").Output()
	fmt.Printf("out: %s\nerr: %s\n", out, err)
}
```

```
go run main.go
out: phemmer  26237  19   0  0.0  0.0 Z+         00:01 [true] <defunct>
phemmer  26238  19   0  0.0  0.0 Z+         00:01 [true] <defunct>
phemmer  26239  19   0  0.0  0.0 Z+         00:01 [true] <defunct>
phemmer  26240  19   0  0.0  0.0 Z+         00:01 [true] <defunct>
phemmer  26241  19   0  0.0  0.0 Z+         00:01 [true] <defunct>
phemmer  26243  19   0  0.0  0.0 Z+         00:01 [true] <defunct>
phemmer  26244  19   0  0.0  0.0 Z+         00:01 [true] <defunct>
phemmer  26245  19   0  0.0  0.0 Z+         00:01 [true] <defunct>
phemmer  26246  19   0  0.0  0.0 Z+         00:01 [true] <defunct>
phemmer  26248  19   0  0.0  0.0 Z+         00:01 [true] <defunct>
phemmer  26249  19   0  0.0  0.0 Z+         00:01 [true] <defunct>
phemmer  26250  19   0  0.0  0.0 Z+         00:01 [true] <defunct>
phemmer  26251  19   0  0.0  0.0 Z+         00:01 [true] <defunct>
phemmer  26252  19   0  0.0  0.0 Z+         00:01 [true] <defunct>
phemmer  26253  19   0  0.0  0.0 Z+         00:01 [true] <defunct>
phemmer  26254  19   0  0.0  0.0 Z+         00:01 [true] <defunct>
phemmer  26255  19   0  0.0  0.0 Z+         00:01 [true] <defunct>
phemmer  26256  19   0  0.0  0.0 Z+         00:01 [true] <defunct>
phemmer  26257  19   0  0.0  0.0 Z+         00:01 [true] <defunct>
phemmer  26258  19   0  0.0  0.0 Z+         00:01 [true] <defunct>
phemmer  26259  19   0  0.0  0.0 Z+         00:01 [true] <defunct>
phemmer  26260  19   0  0.0  0.0 Z+         00:01 [true] <defunct>
phemmer  26261  19   0  0.0  0.0 Z+         00:01 [true] <defunct>
phemmer  26262  19   0  0.0  0.0 Z+         00:01 [true] <defunct>
phemmer  26263  19   0  0.0  0.0 Z+         00:01 [true] <defunct>
phemmer  26264  19   0  0.0  0.0 Z+         00:01 [true] <defunct>
phemmer  26265  19   0  0.0  0.0 Z+         00:01 [true] <defunct>
phemmer  26266  19   0  0.0  0.0 Z+         00:01 [true] <defunct>
phemmer  26267  19   0  0.0  0.0 Z+         00:01 [true] <defunct>
phemmer  26268  19   0  0.0  0.0 Z+         00:01 [true] <defunct>
phemmer  26269  19   0  0.0  0.0 S+         00:00 /bin/sh -c ps ax|grep true
phemmer  26271  19   0  0.0  0.0 S+         00:00 grep true
```
