### ISSUE TITLE
docker 1.10.2 crashed on arm64

### ISSUE THREAD

**Issue by zhangyichao** [docker/docker#20899]
Output of `docker version`:
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.6 gccgo (20150806) 6.0.0 20160218 (experimental)
 Git commit:   389a38e1e5145e89dd0f36cc232d5d7c269aed3b
 Built:        
 OS/Arch:      linux/unknown
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

Output of `docker info`:
segfault with docker daemon,  so there is no output with 'docker info'

(paste your output here)
INFO[0000] [graphdriver] using prior storage driver "overlay" 
INFO[0000] Graph migration to content-addressability took 0.00 seconds 
INFO[0000] Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address 
acquirep: p->m=0x0(0) p->status=256
fatal error: acquirep: invalid p state

runtime stack:
runtime_dopanic
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/panic.c:135
runtime_throw
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/panic.c:193
acquirep
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:2797
stopm
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:1466
startlockedm
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:1604
schedule
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:1854
goexit0
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:1977
runtime_mstart
	/usr1/zhangyichao/src/gcc-newest/libgo/runtime/proc.c:1076

[1]+  Segmentation fault         docker-1.10.2-debug daemon

Provide additional environment details (AWS, VirtualBox, physical, etc.):
use gccgo 6.0, go 1.6, on arm64 big-endian.   
and little endian arm64 run fine, no any error.

Describe the results you received:
crashed on big endian arm64

Describe the results you expected:

Provide additional info you think is important:
segfault in libgo, does any one run docker on big endian arm64 successfully??

**Comment by thaJeztah** [comment]
I think our arm builds are still using Go 1.4.3 and older gccgo for various reasons as well https://github.com/docker/docker/blob/master/Dockerfile.armhf

However, given that we currently do not support this platform, and this is a question about compiling docker yourself, I'm closing this issue; the GitHub issue tracker is probably not the best place to discuss this.

Can you please use the docker-dev Google group? https://groups.google.com/forum/#!forum/docker-dev
