### ISSUE TITLE
Feature: git add <filename> like feature

### ISSUE THREAD

**Issue by bhuwang** [docker/docker#20897]
Suppose I have 10 files changes in my existing docker image. I would like to have a feature to select only 2 files in commit out of 10 changes.

Something Like:
docker commit -am file1 file2

**Comment by thaJeztah** [comment]
I don't think we'll be supporting this, as it will add a lot of complexity, which also has to be maintained.

However you *can* copy files out of a container and add it to another one and commit that;

```
docker cp mycontainer:/file1 .
docker cp mycontainer:/file2 .
docker create --name newbie freshcontainer

docker cp file1 freshcontainer:/
docker cp file2 freshcontainer:/

docker commit freshcontainer ....
```

Copying between containers directly [isn't supported right now](https://github.com/docker/docker/blob/da58ee42bb1d4e17c5b525d161f29ad8efc0569e/api/client/cp.go#L89-L91)

**Comment by calavera** [comment]
I agree with @thaJeztah. you could even script that by copying he's script and a few small modifications.

Thanks for the suggestion, but I'm going to close this issue.
