### ISSUE TITLE
Show "seccomp" in docker info

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#20909]
Seccomp support is currently enabled/disabled during compile time, so even if a user has installed the required seccomp version (2.2.1 or higher), they still won't be able to use this feature, if it's not enabled in the installed binary.

This is confusing, because there's no way for the user to check if seccomp is enabled in the binary. To improve this;

- Have the daemon return a `Seccomp` property in the `GET /info` output, that shows if seccomp is enabled (perhaps this should be the *version* of seccomp?)
- Show seccomp as part of `docker info`
- Show a warning if seccomp is built-in, but not enabled in the kernel
- Show a warning if seccomp is built-in, but does not have the right version

**Comment by justincormack** [comment]
Definitely the first two, the last two may not be so easy, I will have to look how/if we ended up doing runtime detection. Certainly agree that a notification is very useful, as quite a few people may think they have it but dont, (or might want to use a custom filter if it is enabled but not otherwise), and it would give us info for bug reports. I think there is a Go library call to get the C library version.

**Comment by yongtang** [comment]
Hi @justincormack are you currently work on this issue? If not I would like to give it a try and work on an implementations for it.

**Comment by justincormack** [comment]
No, I have some more seccomp-related issues to fix so feel free to work on it!

**Comment by yongtang** [comment]
@justincormack Thanks!

**Comment by yongtang** [comment]
#dibs

**Comment by justincormack** [comment]
Getting the current version of the seccomp library is only supported in the latest release of libseccomp, see https://github.com/seccomp/libseccomp/commit/58a7c20d4c2defc1c984c5c7391ecc60093f85fa - which does not yet have a Go binding. I need to upgrade us to this though, to fix some other issues, so will be looking at updating the bindings, but at present I don't think you can show the version.

**Comment by yongtang** [comment]
@justincormack Thanks for the information. I will keep track and make a pull request after the bindings have been updated.

**Comment by thaJeztah** [comment]
@yongtang perhaps we can start with just showing if seccomp is compiled in the binary? (@justincormack wdyt?)

**Comment by yongtang** [comment]
@thaJeztah Sure I may do it in an incremental way. A PR to cover the existence of seccomp first, then another PR to show the version.

**Comment by thaJeztah** [comment]
@yongtang that'd be great; possibly we can still get it into 1.11 (code freeze is next Thursday)

**Comment by yongtang** [comment]
@thaJeztah Thanks I will give it a try.

**Comment by yongtang** [comment]
@thaJeztah I am ready to do a PR but realized that in ```engine-api/types/types.go```, the variable ```Seccomp``` in ```type Info struct {``` could be either a bool (if we want to just show if seccomp is compiled or not, for now) or a string (if we want to show the version of the seccomp, for the future).

If we use bool now then later it might have some issues to change from bool to string.
If we use string now then I am not sure what should be the value when seccomp exists and what should be the value when seccomp does not exist. Should we use the string "true" and "false" for those situations?

Would like to get some input from you for the variable type and the associated values of the ```Seccomp``` in  ```type Info struct {```.

**Comment by justincormack** [comment]
@yongtang I don't like using string "true" and "false" thats confusing, and changing would not be a good idea. The version of the library is probably less important, so maybe go for a boolean anyway. Another option would be to go for a list of supported security profiles, so it could read "Security profiles: seccomp" and we could add eg apparmor?

You might get more feedback in the pull request discussion, so maybe pick an option and discuss it there.

**Comment by yongtang** [comment]
@justincormack Thanks for the comment. Let me have a pull request with `seccomp bool ` initially, and we could start from there.

**Comment by yongtang** [comment]
@justincormack @thaJeztah I created a pull request https://github.com/docker/docker/pull/21172 to try to cover this issue, with `seccomp bool` added in the Info field initially. Please let me know if there are any issues, and any feedback will be greatly appreciated.
