### ISSUE TITLE
Is it expected that a docker layer might have no content?

### ISSUE THREAD

**Issue by rseddon** [docker/docker#20917]
Output of `docker version`:

```
$ docker version
Client:
 Version:      1.8.2-el7.centos
 API version:  1.20
 Package Version: docker-1.8.2-10.el7.centos.x86_64
 Go version:   go1.4.2
 Git commit:   a01dc02/1.8.2
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2-el7.centos
 API version:  1.20
 Package Version: 
 Go version:   go1.4.2
 Git commit:   a01dc02/1.8.2
 Built:        
 OS/Arch:      linux/amd64

```

Output of `docker info`:

```
Containers: 1
Images: 14
Storage Driver: devicemapper
 Pool Name: docker-253:0-394064-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.982 GB
 Data Space Total: 107.4 GB
 Data Space Available: 44.32 GB
 Metadata Space Used: 3.928 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-327.10.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 3.699 GiB
Name: unknown001C42425BFC
ID: ZDCO:ZBTO:FQVB:N2QK:UU7V:KSZY:DZ2G:BB5L:PPYD:VSTX:US6R:T7XN
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):

List the steps to reproduce the issue:
1.  Build and push a simple docker file using the version of Docker above running on CentOS 7.2

```
$ cat Dockerfile
FROM docker/whalesay:latest
RUN apt-get -y update && apt-get install -y fortunes
RUN apt-get install dos2unix
CMD /usr/games/fortune -a | cowsay

$ docker build .
$ docker tag dfe7611d91f8 192.168.1.83:18440/test/docker-whale2
$ docker push 192.168.1.83:18440/test/docker-whale2
```

Describe the results you received:

The first layer uploaded for this has 1024 bytes of nothing but zeros sent in the PATCH request.

Describe the results you expected:

I don't know if this is a problem or not, so I have no expectations. :-)  FWIW I haven't seen this occur with later versions of Docker.  

The reason I am filing this is that we have an open issue against the Docker implementation in Nexus, pushing of Docker images from Docker 1.82 to Nexus is failing due to this empty layer:

https://issues.sonatype.org/browse/NEXUS-9847

Is it expected that a layer might consist of nothing but 1024 bytes of zeros?  Issue #18226 seems to indicate that this is expected, although there isn't any explanation of why this might happen.   If this is expected I'll recommend that we change Nexus to handle this case.

**Comment by thaJeztah** [comment]
Do you also see this with docker 1.8.3 ?

**Comment by thaJeztah** [comment]
(just wondering if the 1.8.3 made changes in this area, as there were some fixes in that release related to "distribution" and image layers)

**Comment by rseddon** [comment]
Well this is really odd.   I can't reproduce it using 1.8.3.

And surprisingly,  I can't reproduce it using the Docker 1.8.2 from the docker site either (https://get.docker.com/builds/Linux/x86_64/docker-1.8.2.tgz).   

But I can reproduce it every time using the Docker 1.8.2 from the CentOS 7.2 distribution.   I wonder if they've made some changes to your distribution?

Seems I need to investigate this some more.   

So would it be fair to say that docker sending an empty layer isn't something that is expected to happen?  If so I might just handle this with a knowledge base article, letting affected users who are using the 1.8.2 from RHEL/CentOS know they should disable file validation in Nexus.

**Comment by thaJeztah** [comment]
Unfortunately, they *do* make a lot of changes to the docker binaries on Red Hat / Fedora, some of those have side-effects, or make docker behave completely different from the official docker binaries; 
these are the changes between their 1.8.2, and vanilla docker 1.8.2; https://github.com/docker/docker/compare/v1.8.2...projectatomic:a01dc02

And an explanation of patches they carry
https://github.com/projectatomic/docker/blob/fedora-1.10.2/README.md

**Comment by aaronlehmann** [comment]
> Is it expected that a layer might consist of nothing but 1024 bytes of zeros?

Yes. Historically, Docker images have had a filesystem diff for each layer. Many layers don't have any changes from the previous one; for example, an ENV statement in the Dockerfile won't change the filesystem. So these end up wih empty tars, which are padded to 1024 bytes with zeros.

One of the improvements from the schema2 manifest format is that images built with Docker 1.10 and pushed with a schema2 manifest generally won't include these empty layers.

**Comment by rseddon** [comment]
@aaronlehmann Thanks very much for that information, I'm going to recommend we change Nexus to handle this case.

**Comment by peterlynch** [comment]
@aaronlehmann @thaJeztah thanks guys for the timely responses - you are helping us out big time with these implementation details

**Comment by thaJeztah** [comment]
You're welcome! Good luck on the implementation
