### ISSUE TITLE
Engine log curation / rotation

### ISSUE THREAD

**Issue by ac111** [docker/docker#20915]
Noticed on some test systems the docker daemon log file itself can grow substantially if left unmanaged, and Docker engine does not appear to support the ability to curate or rotate this log data currently.  Not sure if this is a planned enhancement to the built-in logging framework?

Output of `docker version`:

```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      linux/amd64
```

Output of `docker info`:

```
Containers: 22
 Running: 3
 Paused: 0
 Stopped: 19
Images: 309
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 472
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: overlay bridge null host
Kernel Version: 4.1.18-boot2docker
Operating System: Boot2Docker 1.10.2 (TCL 6.4.1); master : 611be10 - Mon Feb 22 22:47:06 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 4.837 GiB
Name: ucplocal-node
ID: GF4E:PPXW:YGVX:L3ZN:3Z26:CFDN:BQKT:WSNA:AZA6:T3XI:DTH5:SEMS
Debug mode (server): true
 File Descriptors: 67
 Goroutines: 109
 System Time: 2016-03-03T14:43:00.780969141Z
 EventsListeners: 1
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
Cluster store: etcd://192.168.99.100:12379
Cluster advertise: 192.168.99.101:12376
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):
Currently testing in virtualbox environment

List the steps to reproduce the issue:
1. Run docker daemon on target host

Describe the results you received:
Generated daemon log file is not curated or rotated by default

Describe the results you expected:
Options to restrict max daemon log file size, backup count, compression

Provide additional info you think is important:

**Comment by Fredjet** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  fredjet15@gmail.com
    Domain ventureacceleration.com has exceeded the max emails per hour (51/50 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 5383 characters long; only the first
------ 5000 or so are included here.
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:54468 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by eaglepeak.ovasp.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1abUiQ-0001tN-4R
	for fred@ventureacceleration.com; Thu, 03 Mar 2016 09:58:58 -0500
Date: Thu, 03 Mar 2016 06:58:17 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457017097;
	bh=qzvbsX9PJ+1YehgYH7zuQEAz6Bwb6meWp6xwEgPgAok=;
	h=From:Reply-To:To:Subject:List-ID:List-Archive:List-Post:
	 List-Unsubscribe:From;
	b=0d3fXwVYrQBaVQgRazgKCdrfBwV1WhFvWYpFltt1a+MvCNy36UCGkkM1By5TtO0td
	 LCnXG9aWkxWRPK2b0brkLVsM2EhwulTiBFXE67n0jISCGfPhZH6E1DoyLAkCqiP4sD
	 KkEOYLamWBL0Y3ZJA5EYUGQBVYMa/ARkRBhdYZJI=

**Comment by AndrewGuenther** [comment]
Docker writes to `/var/log` on **most distros** which is automatically rotated on **most distros**. This doesn't seem to be the case with `boot2docker` which is based off of [Tiny Core Linux](http://tinycorelinux.net/). Since I don't imagine you would be using `boot2docker` in production, I can almost guarantee you this won't be a problem anywhere else.

**Comment by thaJeztah** [comment]
Agreed, this is something that shouldn't be handled by docker, but by the system it's running on.

I'll close this issue, but feel free to comment if I misunderstood the issue

**Comment by AndrewGuenther** [comment]
Also, if you aren't using the daemon logs, you could raise the log level to reduce noise.

`--log-level=warn`
