### ISSUE TITLE
Pull inside the daemon when doing a run ?

### ISSUE THREAD

**Issue by MatMaul** [docker/docker#20919]
Is there any reason why the pulling is not done in the daemon itself when an image is currently not present locally ?
Currently it returns a 404 and then the client do a pull before retrying, I tried to mimic this approach in Swarm manager however @vieux make a pertinent remark :
https://github.com/docker/swarm/pull/1892

You can find here a branch with a new --pull argument for the run.
https://github.com/MatMaul/docker/tree/registry-auth-on-run

Even if this is not desirable would it be possible to just keep the client modifications to send the correct auth header on run too ? for Swarm it would avoid duplicating the creds 2 times in config.json, support more than one registry credentials and would also allow to support any following auth mechanism if supported by pull.

**Comment by thaJeztah** [comment]
Can you explain the issue you're running into? For swarm mode, we're storing the authentication information in the service definition, and have each node pull an image when needed.

**Comment by thaJeztah** [comment]
Given that this is best discussed on the "Swarm" repository if it's for "classic" Swarm, I'll close this issue here, as for SwarmKit / Swarm mode it should be resolved.
