### ISSUE TITLE
Flaky test: TestUpdateRestartPolicy

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#20922]
Seen failing on WindowsTP4 https://jenkins.dockerproject.org/job/Docker-PRs-WoW-TP4/2038/console

```
16:41:43 
16:41:43 ----------------------------------------------------------------------
16:41:43 FAIL: docker_cli_update_test.go:11: DockerSuite.TestUpdateRestartPolicy
16:41:43 
16:41:43 docker_cli_update_test.go:24:
16:41:43     c.Assert(err, checker.IsNil)
16:41:43 ... value *errors.errorString = &errors.errorString{s:"condition \"\"running\" == \"exited\"\" not true in time"} ("condition \"\"running\" == \"exited\"\" not true in time")
16:41:43 
16:41:43 
16:41:43 ----------------------------------------------------------------------
```

**Comment by thaJeztah** [comment]
This test was added in https://github.com/docker/docker/pull/19116, and further tuned in https://github.com/docker/docker/pull/20870 so /cc @WeiZhang555 @jhowardmsft 

Perhaps it was just a one-off, but opening an issue to keep track

**Comment by WeiZhang555** [comment]
Hmmm, maybe 150 seconds is still not longer enough on Windows, guess this should be a one-off. If not, we can try to bump up the timeout again.

**Comment by thaJeztah** [comment]
SGTM, let's keep an eye on it and decide if we need to bump the timeout based on that

**Comment by thaJeztah** [comment]
Looks like it's still flaky

**Comment by thaJeztah** [comment]
Windows TP4 is no longer, so closing
