### ISSUE TITLE
Local volumes driver behaviour with a network mount and multiple docker engines

### ISSUE THREAD

**Issue by sayash** [docker/docker#20921]
Output of `docker version`:

```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64
 
Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64
```

Output of `docker info`:

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 189
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 230
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.16.0-46-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.768 GiB
Name: minionA
ID: EBGI:3EZW:52OM:3OLW:3KRU:CLZF:NYMX:5HI4:PSJP:PHHE:KUGU:T4OE
WARNING: No swap limit support
Labels:
 dept=april
 geo=us
 provider=generic
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):
Physical machines

**List the steps to reproduce the issue:**

1. Mount an NFS location as /var/lib/docker/volumes on 2 docker engines
2. Create a volume, named `example` when running a container on 1st docker engine
3. Perform `docker volume ls` on the other docker engine - the volume will not be listed. `volume rm` or `volume inspect` will not work either.
4. Create a new container on the 2nd docker engine with the `-v example:/path` - this container on the second host is able to read the volume.
5. Restart 2nd docker engine, `docker volume ls` will list this volume.

**Describe the results you received:**

A docker engine only scans the volumes directory upon startup, as seen [here](https://github.com/docker/docker/blob/master/volume/local/local.go#L79). After that, the data structure used by the local driver knows only about volumes that were created, deleted by the docker engine running on that particular host. If changes happened from another docker-engine to this shared network location, the docker engine doesn't seem to pick it up.

**Describe the results you expected:**

If behaviour were changed to listing all volumes under that folder, and not only the ones created by the docker-engine running on that particular host, multi-host volume management will probably become much easier and not need much more than the local volume plugin.

There is probably additional complexity here which I'm not appreciating, but just wanted to raise this anyway.

**Comment by thaJeztah** [comment]
This is *not* something we want to support; the `/var/lib/docker` directory should *not* be accessed directly, and is intended to be managed by a single daemon, and *exactly* for the reasons you described here. For example, two daemons creating volumes in the same path are not aware of the other daemon using such a volume (a container on the other host could be using that volume), resulting in the daemon *deleting* the volume, because it thinks it's no longer in use.

If you want to have volumes using NFS, or other mechanisms to be shared by multiple hosts, use a volume-plugin that adds this feature, some plugins are listed on this page: https://docs.docker.com/engine/extend/plugins/

I'm going to close this issue, because this is not something we support, or intend to support

**Comment by Fredjet** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  fredjet15@gmail.com
    Domain ventureacceleration.com has exceeded the max emails per hour (61/50 (122%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:56860)
	by eaglepeak.ovasp.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <bounces+848413-c2da-fred=ventureacceleration.com@sgmail.github.com>)
	id 1abd4u-0000fo-K7
	for fred@ventureacceleration.com; Thu, 03 Mar 2016 18:54:44 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=1bhM5uP3j1Wz8tcKA+R7pPqCd6A=; b=pdIPnF1KLJh9WFYB
	7VVR9+NdsmJpSpFd6qnUoYyoiPoxAWXsRKonENNYdbG1+ldG0ki7/xnbIBkMNhny
	IvamiWqjw6yxv7zaAq+7tlr1Sllu0PAOqR5HuKG1rGCQ7wgUVcDFN+6xsKkE68s4
	82oaMPJugYjUl9eJ6upse5wvsDY=
Received: by filter0475p1mdw1.sendgrid.net with SMTP id filter0475p1mdw1.13165.56D8CE9916
        2016-03-03 23:54:01.43553192 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0006p1iad1.sendgrid.net (SG) with ESMTP id CYna7uBbTuKQy9s_81_IGg
	for <fred@ventureacceleration.com>; Thu, 03 Mar 2016 23:54:01.483 +0000 (UTC)
Date: Thu, 03 Mar 2016 15:54:01 -0800

**Comment by Fredjet** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  fredjet15@gmail.com
    Domain ventureacceleration.com has exceeded the max emails per hour (62/50 (124%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o3.sgmail.github.com ([192.254.112.98]:46513)
	by eaglepeak.ovasp.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <bounces+848413-c2da-fred=ventureacceleration.com@sgmail.github.com>)
	id 1abd4w-0000fq-12
	for fred@ventureacceleration.com; Thu, 03 Mar 2016 18:54:46 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=rY3ptQ9LNTKQnwpw8/fSMEq3kfg=; b=GDRZVitdJmFvBmN8
	9LzNNkzfIJZKm2tng5YazeQF3J9aoZ+0C6An/2tDVf3CWCEjmk1ubBGJ8ayEB+nY
	06t3c3fFYsDoazX4b/IUPjYAKfNORbpsm3vTyB0/j2T315CSHoruuwlV885TBQxC
	6vJMktozbrE3AR8IMfVL9wwkbqA=
Received: by filter0471p1mdw1.sendgrid.net with SMTP id filter0471p1mdw1.19521.56D8CE9C19
        2016-03-03 23:54:04.242279081 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id fJZsrIkjR7SvUUPMDn9KTQ
	for <fred@ventureacceleration.com>; Thu, 03 Mar 2016 23:54:04.225 +0000 (UTC)
Date: Thu, 03 Mar 2016 15:54:04 -0800
