### ISSUE TITLE
Downloads recommend using `curl | sh`

### ISSUE THREAD

**Issue by kpande** [docker/docker#20933]
It's a really bad idea to pipe code straight to `sh` from `curl`. Why not do it the right way, save and execute? Potentially with a verification check in between to make sure you're running the right thing? You do want it to run as root, correct?

**Comment by thaJeztah** [comment]
The installation guide in the documentation describes how to perform a manual installation https://docs.docker.com/engine/installation/linux/ubuntulinux/, which is the recommended approach overall, because (for example) the installation script attempts to detect the distribution, which is always on a "best effort" base.

I don't think we can include all that information on the GitHub releases page, but perhaps for upcoming releases we can include a link to the installation guide.

**Comment by HackToday** [comment]
I think it was an quick script magic ways to install docker, it is for fresh try. For distro official installs, it follows link given by @thaJeztah  above.

**Comment by kpande** [comment]
https://www.seancassidy.me/dont-pipe-to-your-shell.html

https://news.ycombinator.com/item?id=6650987

**Comment by MicahChambers** [comment]
:+1: @kpande

**Comment by HackToday** [comment]
@kpande if you think you have better ways. a PR is welcome.  More maintainers would review that and vote that. Make sense ?

**Comment by raesene** [comment]
One possible approach here to provide a decent mix of security and usuability (i.e. more usuable than the manual installation that @thaJeztah  mentions and more secure than curl-bashing) would be to offer the automated script alongside a cryptographic signature of that script and instructions to confirm that it is a valid signature.

It might be a good idea to combine this with something like a key in [Keybase](https://keybase.io) that could be validated by users before making use of the script. The advantage of keybase is that it allows for "proofs" to be posted on github amongst others, so users could satisfy themselves that the key that signed the installation script was the same one that owns the relevant github repository (docker/docker).

Obviously this still relies on users to actually carry out the validation and is a somewhat more manual process than curl|bash, but ultimtately that's down to the individual risk appetite of the user.

The other downside of this is that it would involve the docker team in some more key management process overhead to manage the signing key and maintain the signing process as the install script gets updated.

**Comment by cpuguy83** [comment]
@raesene Really, this should be `curl ... | notary | sh`, where notary stores the trust info of the particular script.

**Comment by raesene** [comment]
@cpuguy83 yeah, something like that could work well where the user already has notary available, so ideally offering that and something like a GPG signed option for the times where the user has no existing docker software install to leverage.

The advantage of GPG/Keybase is that GPG is (almost) always available on Linux distros and keybase allows for the user to attempt to establish that initial trust point to get them to a point where they can start working with signed Docker packages.

**Comment by thaJeztah** [comment]
The docs have moved to the central repository https://github.com/docker/docker.github.io. If you still think this should be changed, could you open an issue there?
