### ISSUE TITLE
Docker push fails with most builds on my home machine

### ISSUE THREAD

**Issue by dts** [docker/docker#20936]
Since docker 1.9 or so, `docker push` pushes 5 or so layers simultaneously, which on my local machine causes many of the larger ones to timeout and fail (and retry), repeatedly, until the push fails completely.  On a VPS or other well-connected machine, things work great, but I can no longer do any development on my home computer.  I would love an option that limited to 1 or 2 layers at a time, `docker push --max-concurrency=1` or something similar.

**Comment by dts** [comment]
Phrased as a feature request:  please allow me to specify the concurrency level of `docker push`.  I do not care about total time to send to the server, and I would like to slow it down (ideally also with a bitrate throttle).  I have seen feature requests for bitrate throttle, but not for concurrency level.

**Comment by dts** [comment]
For completeness, though:
``` $ docker version
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.0-rc2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c1cdc6e
 Built:        Wed Jan 27 21:06:37 2016
 OS/Arch:      linux/amd64
```

```
$ docker version
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.0-rc2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c1cdc6e
 Built:        Wed Jan 27 21:06:37 2016
 OS/Arch:      linux/amd64
 $ docker info
Containers: 57
 Running: 6
 Paused: 0
 Stopped: 51
Images: 257
Server Version: 1.10.0-rc2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 480
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.17-boot2docker
Operating System: Boot2Docker 1.10.0-rc2 (TCL 6.4.1); master : b1ddf2c - Mon Feb  1 17:31:43 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.956 GiB
Name: dinghy
ID: DE6D:XIBC:WYE5:3Z5C:7S4D:CWIA:KFZT:X2GC:XJ7X:FU65:HBN7:IGPI
Debug mode (server): true
 File Descriptors: 53
 Goroutines: 72
 System Time: 2016-03-04T05:26:37.711302734Z
 EventsListeners: 1
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: thehumaneffort
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

List the steps to reproduce the issue:
1.  Build a large application on a poorly-connected home computer
2.  docker push that image
3.  after trying for a while, the individual 

Describe the results you received:
Repeated timeouts on larger layers occur, causing the overall push to fail.

Describe the results you expected:
Retries should start where they left off, instead of starting over, or fewer items should be simultaneously sent, so as to prevent timeouts etc.

Provide additional info you think is important:
This is a common screen:
```
 $ docker push thehumaneffort/yogitunes-api:base2
The push refers to a repository [docker.io/thehumaneffort/yogitunes-api]
8db33c547051: Layer already exists 
631ffd742432: Layer already exists 
7d44ba21dc04: Layer already exists 
d234768ce0df: Retrying in 7 seconds 
5f70bf18a086: Layer already exists 
16f60cf262e2: Pushed 
0070658fdf8b: Retrying in 10 seconds 
4c09e1c3bed1: Retrying in 5 seconds 
3d9a7bde211f: Retrying in 8 seconds 
656120ad8c56: Retrying in 3 seconds 
30f9a83f20f3: Waiting 
78dbfa5b7cbc: Waiting 
```

**Comment by FrenchBen** [comment]
Similar issue here, although not as bad as @dts  - 10MBPS/1MBPS
I get DC'd from everything during the `docker push` - If I do an `scp` to a server of the exported `.tar` the connection is slower but doesn't kill the entire bandwidth.

**Comment by FrenchBen** [comment]
Some error after waiting for layers to be pushed:
```
The push refers to a repository [docker.io/frenchben/web]
5337962fb724: Retrying in 1 seconds
98adb06e69de: Retrying in 1 seconds
49ecea76e30a: Layer already exists
5f70bf18a086: Layer already exists
0d0fa4de8acb: Layer already exists
043931f236f1: Layer already exists
41d3fc1df098: Layer already exists
a8b175ca575f: Pushing 31.11 MB/283.6 MB
03b230c843be: Layer already exists
598247df110f: Pushing  20.3 MB/122.2 MB
73f5baaa4cd9: Retrying in 1 seconds
eb5e3e1e7351: Retrying in 1 seconds
net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

Unless you have a strong enough connection, pushing seems to be very difficult :(

**Comment by thaJeztah** [comment]
let me add this to the 1.11 milestone to see if there's a chance on finding a reasonable solution before that release (time is short before code freeze, so no promises whatsoever)

**Comment by mwm** [comment]
Let me add my vote for this. Docker push pretty much fries my rural DSL connection (~6mb/s). Starting a docker push causes my ping RTT's to go from ~50ms (slow but not unreasonable) to > 2 seconds. This inevitably results in the push timing out and needing to be restarted, hoping that at least one layer manages to succeed after the initial smaller ones get done. It also means I can't even browse the web in the middle of a docker push.

As a temporary workaround, anyyone got a suggested QoS router setting that can be used to throttle docker a docker push?

**Comment by byrnedo** [comment]
Same problem here, we're a cash-strapped startup with crappy net connection due to restrictions with the building we're in and our pushes for some big images nearly always fail. And suck up nearly all our bandwidth.

**Comment by thaJeztah** [comment]
We most likely won't be able to address this before the 1.11 release, so I'm updating this to 1.12

**Comment by abawany** [comment]
This doesn't appear to be fixed on OSX with Docker v1.12.0-a. `docker daemon` is not a supported command on OSX and its help suggests using `dockerd`, which is also not present. Should I open a new issue? It is sad that that it appears that the fix has skipped over OSX.

**Comment by FrenchBen** [comment]
@abawany What changes are you trying to make to the docker daemon? Most of the settings are available from within the pref panel. 
The daemon runs within the stateless vm.

**Comment by abawany** [comment]
@FrenchBen I am trying to adjust the `maxDownloadConcurrency` and `maxUploadConcurrency` parameters as specified in the above changes (e.g. https://github.com/boynux/docker/commit/44284ec27fe18701ce93a1bf0b5d1a51805991f5). I have looked at the preferences panel but there appears to be no mechanism to adjust these parameters. In short, I would like control on the number of simultaneous uploads that `docker push` starts on OSX.

**Comment by thaJeztah** [comment]
@abawany adding more options to the GUI for Docker for Mac is something that's still being worked on, there's probably an issue tracking that in the docker for mac issue tracker; https://github.com/docker/for-mac/issues

**Comment by abawany** [comment]
@theJeztah I don't see anything in that list. Would you like me to add it and close this issue?

**Comment by thaJeztah** [comment]
oh! that's because it's in the issue tracker for docker "engine", the "docker for mac" issue tracker is a separate issue tracker for issues that are specific to docker for mac (so cannot be solved / worked on in this repository). If you can open a new issue in the Docker for Mac issue tracker, so that we can close https://github.com/docker/docker/issues/26386 here, that'd be appreciated.

**Comment by abawany** [comment]
Thanks: I have re-logged this as https://github.com/docker/for-mac/issues/621 and suggested at #26386 - will close the latter shortly as well if @icecrime or @LK4D4 don't beat me to it first.
