### ISSUE TITLE
Docker calls "unmount" operation even for containers that failed to start

### ISSUE THREAD

**Issue by erikh** [docker/docker#20939]
ping @cpuguy83 

Sorry if this is a dupe! I peeked but might have missed this one.

```
docker volume create -d remote foo # Create
docker run -itd -v foo:/bar ubuntu # Mount
```

now, because of our 'remote' driver the second command twice fail to start because the volume cannot be shared. However, what will actually happen is that both Mount (which fails) and Unmount (!!!) will get reported to the volume plugin, which without specific container information in the api makes it impossible to track backwards where the mount came from. 

Since the volume never got mounted in the first place, it seems that it should not be required to be unmounted.

Relevant volplugin log with the activations and json payloads shown: https://gist.github.com/14730f2c7c1ab35a95c6

Here's a docker log. I'll run another in debug mode in a minute. This mess locks up my whole cluster as it stands right now (not your fault). https://gist.github.com/c8d1e5d10c9fd675b336

Thanks!

**Comment by erikh** [comment]
I need to get you guys some better logging clearly. I'm working on that.

**Comment by erikh** [comment]
Here's a docker debug log. I'm going to add some more API output logging to volplugin tonight or early tomorrow to help resolve this: https://gist.github.com/4b2b7ae435435210935a

**Comment by thaJeztah** [comment]
Thanks @erikh

**Comment by cpuguy83** [comment]
I don't think we should prevent the Unmount from being called, but we could send an opaque ID.

**Comment by erikh** [comment]
Why? if the mount returns error, we have pretty good feedback that the mount did not succeed; is there a specific case you're worried about?

**Comment by cpuguy83** [comment]
Relative complexity vs reward?
Why would a call to `Unmount` be harmful in this case?

**Comment by erikh** [comment]
let's just do the unique ID.

**Comment by cpuguy83** [comment]
Is this something you want to work on?

**Comment by erikh** [comment]
I can give it a shot. Let me take a stab at it tomorrow, unless you've 
already done so.

**Comment by cpuguy83** [comment]
@erikh Yeah, see the PR above.
