### ISSUE TITLE
Proposal: recursive .dockerignore files

### ISSUE THREAD

**Issue by c24w** [docker/docker#20944]
I can't find anything which relates to this, but it would be useful if `.dockerignore` files could exist in any directory, defining paths relative to themselves (like `.gitignore`).

Example:

**Working dir**
```
.
├── add-dir
│   ├── add-me
│   ├── .dockerignore
│   └── ignore-me
├── add-me
├── Dockerfile
├── .dockerignore
└── ignore-me
```

**Dockerfile**
```dockerfile
FROM alpine
WORKDIR /workdir
COPY . .
CMD ls -R
```

**both .dockerignore files**
```
ignore-me
```

**Commands**
```shell
$ docker build -t dockerignore-test .
$ docker run dockerignore-test
.:
Dockerfile
add-dir
add-me

./add-dir:
add-me
ignore-me # this file would not be inside the container
```

**Comment by thaJeztah** [comment]
Given that we try to have `.dockerignore` act similar to `.gitignore`, I think this would make sense, but we should really guard against feature creep, and see if this doesn't add too much complexity.

Someone wrote up a nice approach using `.gitignore` here https://github.com/docker/docker/issues/12971#issuecomment-138134947 that may be useful for your use case.

/cc @duglin

**Comment by ObsessiveOrange** [comment]
Are we thinking of implementing this? If so, i would like to work on it.

**Comment by c24w** [comment]
@ObsessiveOrange I won't have a chance to any time soon, so feel free :)

**Comment by ObsessiveOrange** [comment]
Great. Thanks. I'll just leave this here, and start looking at implementing this: #dibs

**Comment by duglin** [comment]
idea sounds ok to me

**Comment by devinus** [comment]
I *literally* just started looking for this. Serendipitous that it was opened two days ago.

**Comment by ObsessiveOrange** [comment]
This will be my first time contributing, so I just want to make sure I cover all the bases. I've taken a look around the code that applies to this, and come to a few conclusions. I wanted to check with everyone before moving forward, to make sure there's nothing that I'm missing.

So, looking at the current way `.dockerignore` files are handled, it seems that the file pointer is handled directly to the `builder/dockerignore/dockerignore.go's ReadAll` method. This doesn't give any further information about the current directory it is in, and allows for no way to recursively search into subdirectories in the ReadAll method. 

I'm thinking of having the `ReadAll` method accept a string path, which would be the directory to start recursing from. I took a quick peek, and it sees that this is only used in 4 places, and shouldn't break  anything. The responsibility for opening and reading the actual `.dockerignore` files would then fall on the `ReadAll` method. 

Does this sound good to everyone?

**Comment by jakirkham** [comment]
Would really love to see something like this.

**Comment by tiborvass** [comment]
What's the usecase for this? Why isn't the root .dockerignore enough? Also this could be a breaking change for people like @justincormack who already have multiple .dockerignore files in their tree.

**Comment by thaJeztah** [comment]
We just discussed this in the maintainers review session and decided to not implement this, for reference, see my short summary here: https://github.com/docker/docker/pull/21020#issuecomment-210106299

Thanks for suggesting this feature (I actually liked the idea), but unfortunately, we cannot accept it.

**Comment by jakirkham** [comment]
Will this get revisited at some future time when having a large break in backwards compatibility might be acceptable? Is there any way this might be proposed where it is not (or less of) a break in backwards compatibility.

**Comment by thaJeztah** [comment]
@jakirkham I don't think this will be implemented in the near future; for the meantime, perhaps this approach works for you https://github.com/docker/docker/issues/12971#issuecomment-138134947, but otherwise no.

**Comment by BBonifield** [comment]
Given the rise of monorepos and docker, I wonder if this feature request would be reconsidered.

**Comment by thaJeztah** [comment]
@BBonifield you may be interested in this proposal; https://github.com/moby/moby/issues/37129

**Comment by chrisjohnson** [comment]
I would want this file for the other direction -- reading from parents of my repo. Or failing that, reading from $HOME/.dockerignore. There are some large tooling artifacts in my repo directories that slow down my docker builds. Those files are already .gitignore'ed by creating $HOME/.gitignore but I have no such option for $HOME/.dockerignore

**Comment by thaJeztah** [comment]
@chrisjohnson sounds more like https://github.com/moby/moby/issues/12843. That said; have you tried building with BuildKit enabled? (set the `DOCKER_BUILDKIT=1` environment variable). BuildKit uses an interactive session to only send to the daemon what's used in the Dockerfile, so if your Dockerfile does not `COPY` / `ADD` those directories, they won't be sent

**Comment by bcheidemann** [comment]
> If anyone is interested in an approach to solving this for people already using git, I've created a tool that convert `.gitignore`-files inside a repository into a single `.dockerignore` file:
> 
> https://github.com/LinusU/gitignore-to-dockerignore

This is really cool! It inspired me to make [flatten-ignorefiles](https://jsr.io/@bcheidemann/flatten-ignorefiles).

It does the same as [gitignore-to-dockerignore](https://github.com/LinusU/gitignore-to-dockerignore) but with the following additions:

- Additional CLI flags and options
  - Allow specifying globs for included / excluded ignorefiles (doesn't need to be just .gitignore files)
  - Flag to remove recursive .gitignore files (if you just want to flatten your .gitignore into one file)
  - Some formatting options
- Supports installing via `npm install`, `deno add` and `deno install`
- First-class support for Deno (via JSR package manager)
