### ISSUE TITLE
Error response from daemon: open [path to file]: operation not permitted.

### ISSUE THREAD

**Issue by onorua** [docker/docker#20950]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

Output of `docker version`:

```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:22:53 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:22:53 2016
 OS/Arch:      linux/amd64
```

Output of `docker info`:

```
Containers: 132
 Running: 0
 Paused: 0
 Stopped: 132
Images: 812
Server Version: 1.10.2
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.5.0-rc6
Operating System: Debian GNU/Linux stretch/sid
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.458 GiB
Name: x
ID: N6IS:I7FC:XPXM:4SFP:FUCX:OOZH:WYWZ:IXKS:H74T:PLNL:DO6X:2PSJ
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):
Physical laptop, with Debian 8

List the steps to reproduce the issue:
```
root@x:/var/lib/docker# docker run -i -t debian:sid /bin/bash 
docker: Error response from daemon: open /var/lib/docker/overlay/b1d6ad39aae1648cfff0c7617a4c3e4a95e73c1a56aff784fcf88a40c87c83c4-init/merged/dev/console: operation not permitted.
See 'docker run --help'.
```
The files with wrong permission always changes:
```
root@x:/var/lib/docker# docker run -i -t debian:sid /bin/bash 
docker: Error response from daemon: open /var/lib/docker/overlay/99227ae8206cdf58c80f537346192a403d053d587ee7f1caff7ab2781021a9af-init/merged/.dockerenv: operation not permitted.
See 'docker run --help'.
root@x:/var/lib/docker# docker run -i -t debian:sid /bin/bash 
docker: Error response from daemon: open /var/lib/docker/overlay/3cffb3dc806c74423b98611b5ba8af532713bd57332a593ba337879d73478e58-init/merged/.dockerinit: operation not permitted.
See 'docker run --help'.
root@x:/var/lib/docker# docker run -i -t debian:sid /bin/bash 
docker: Error response from daemon: open /var/lib/docker/overlay/affa6bd239356c179994854bef85559a31779cb1f8a300befd796055ddd92118-init/merged/.dockerinit: operation not permitted.
See 'docker run --help'.
root@x:/var/lib/docker# docker run -i -t debian:sid /bin/bash 
docker: Error response from daemon: open /var/lib/docker/overlay/d6b9b2b1f469dae6d877d58330dbf0ea25a049654a9a28287bf697e3e8d9591e-init/merged/dev/console: operation not permitted.
See 'docker run --help'.
root@x:/var/lib/docker# docker run -i -t debian:sid /bin/bash 
operation not permitted
docker: Error response from daemon: Cannot start container 0feac672d9fdf50e050b8df75db0987a01223b89c3ad2f28e5dacaa60d0a5632: [9] System error: operation not permitted.
root@x:/var/lib/docker# docker run -i -t debian:sid /bin/bash 
operation not permitted
docker: Error response from daemon: Cannot start container 822df34e95bcb25ac595879889d80c3affac2bcc4332bd3929e1bdeaaa69c448: [9] System error: operation not permitted.
root@x:/var/lib/docker# docker run -i -t debian:sid /bin/bash 
docker: Error response from daemon: open /var/lib/docker/overlay/13015a440aaa98764efe99fd5c2ee731e7c1519e9a1c0e1b46d05571850e99f3-init/merged/.dockerinit: operation not permitted.
See 'docker run --help'.
root@x:/var/lib/docker# docker run -i -t debian:sid /bin/bash 
docker: Error response from daemon: open /var/lib/docker/overlay/350be1a152aabfe8901f26de4943e7de388d60154bbdd4fa3b05ef974492c162-init/merged/dev/console: operation not permitted.
See 'docker run --help'.
root@x:/var/lib/docker# 
```

it may even start once in a while

**Comment by thaJeztah** [comment]
Is this a fresh install, or was docker running before on this machine?

**Comment by onorua** [comment]
docker was running on that machine since 1.6

**Comment by thaJeztah** [comment]
@onorua and you upgraded from 1.6 to 1.10, or all versions in between? Wondering if there's something that went wrong during a migration step.

**Comment by onorua** [comment]
Yes, all the versions where just fine... I had 1.10.0 which was working fine, then I've upgrade to 1.10.2, it was even working for some time, then I've rebooted - and the result is in the bug description ;)

**Comment by onorua** [comment]
I was thinking that the problem is on overlay structure, maybe something is wrong it the filesystem. So I've stopped docker daemon, moved `/var/lib/docker` -> `/var/lib/docker.back` started daemon pulled busybox image, tried to start - but no luck:(

**Comment by thaJeztah** [comment]
Interesting, so it could be related to overlay, or the overlay driver. When you previously ran docker, was this on the same kernel version? I see you're on a really recent kernel, so wondering if it's caused by changes in the kernel

**Comment by onorua** [comment]
It is even more interesting, I've update the kernel, compiled in the overlay driver to make sure it is not due to some missing module in the kernel. Then, as soon as I've started up my machine I changed back to overlay driver:
```
root@x:/home/onorua# systemctl daemon-reload
root@x:/home/onorua# systemctl restart docker
root@x:/home/onorua# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
root@x:/home/onorua# docker pull busybox 
Using default tag: latest
latest: Pulling from library/busybox
f810322bba2c: Pull complete 
a3ed95caeb02: Pull complete 
Digest: sha256:97473e34e311e6c1b3f61f2a721d038d1e5eef17d98d1353a513007cf46ca6bd
Status: Downloaded newer image for busybox:latest
root@x:/home/onorua# docker run -i -t busybox:latest /bin/sh 
/ # 
root@x:/home/onorua#
```
That was with empty `/var/lib/docker`, I decided wow, there is something with the kernel probably, so I must try with full of my images `/var/lib/docker`:
```
root@x:/home/onorua# systemctl stop docker
root@x:/home/onorua# rm -rf /var/lib/docker
root@x:/home/onorua# mv /var/lib/docker.backup /var/lib/docker
root@x:/home/onorua# systemctl start docker
root@x:/home/onorua# docker images
....
root@x:/home/onorua# docker run -i -t debian:sid /bin/bash 
bash: /etc/bash.bashrc: Operation not permitted
bash-4.3# exit
root@x:/home/onorua# docker run -i -t debian:sid /bin/bash 
operation not permitted
docker: Error response from daemon: Cannot start container 2232129c68a56601feb891d99b8302205acd4d8dc5e74a2fb68dd29bfeeffc3d: [9] System error: operation not permitted.
root@x:/home/onorua# docker run -i -t debian:sid /bin/bash 
docker: Error response from daemon: open /var/lib/docker/overlay/cee5ebd5332d99c67433ae5c0a1a64410aba3e504700add59fd81e319e9f7ca6-init/merged/etc/hosts: operation not permitted.
See 'docker run --help'.
root@x:/home/onorua# docker run -i -t debian:sid /bin/bash 
bash: /etc/bash.bashrc: Operation not permitted
bash-4.3# 
bash-4.3# 
bash-4.3# 
bash-4.3# exit
```
Which means some times it is working, some times not. 
Then I decided that probably there is something about amount of images I have (I had quite a lot I would say), so I've cleaned up all the "unnamed" images, all stopped containers everything which might affect it. But still did not work.
Then I've tried to check it with empty `/var/lib/docker` again:
```
root@x:/home/onorua# systemctl stop docker
root@x:/home/onorua# mv /var/lib/docker /var/lib/docker.backup
root@x:/home/onorua# systemctl start docker
root@x:/home/onorua# docker run -i -t busybox /bin/sh 
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
f810322bba2c: Pull complete 
a3ed95caeb02: Pull complete 
Digest: sha256:97473e34e311e6c1b3f61f2a721d038d1e5eef17d98d1353a513007cf46ca6bd
Status: Downloaded newer image for busybox:latest
docker: Error response from daemon: open /var/lib/docker/overlay/4ea00fd374b275348b51861d7215b81cc78b65dbae7f751068d3e719a6414ff0-init/merged/etc/hosts: operation not permitted.
See 'docker run --help'.
```
You see, at the very beginning it was working, and now when I've did the same - it doesn't any more. I run out of ideas... 
One more interesting thing:
```
root@x:/home/onorua# docker save -o skype.image skype 
Error response from daemon: unexpected EOF
```

**Comment by thaJeztah** [comment]
the `unexpected EOF` *could* be if something went wrong during the migration from docker 1.9 to 1.10. I don't think there's a way to recover from that if that image is actually damaged

**Comment by onorua** [comment]
okay, I've removed everything from `/var/lib/docker` but it still doesn't work each second time. Can we debug it somehow to actually see what is wrong? Just let me know what to do, and I'll try my best

**Comment by BlackIkeEagle** [comment]
I have a similar issue after updating my kernel to 4.5-rc7 from 4.4.4. I'm also using the overlay driver.

~~~
docker: Error response from daemon: open /var/lib/docker/overlay/bb3879d94740c3145693cc152b1c0795a45de3c27d5f4842867618da48f51601-init/merged/dev/console: operation not permitted.
~~~

Once I rolled back to linux 4.4.4 the issue was gone

**Comment by thaJeztah** [comment]
Thanks @BlackIkeEagle; based on the above this sounds like a kernel issue to me; I'll label it as that for now, but any input is appreciated

**Comment by RRAlex** [comment]
Same here, I've just upgraded to 4.5.0 final yesterday from mainline (Ubuntu 15.10) and now I'm getting this at the beginning of our build:

ERROR: Service 'base' failed to build: open /var/lib/docker/overlay/09ea86c423444f73de0962d9feb1dd59e68a3d9d598d97e11b5d1ca37769e9ff-init/merged/dev/console: operation not permitted

So, it _might_ indeed be something new in the kernel that Docker needs to handle, or a kernel bug...

**Comment by fedya** [comment]
Same here:
First time i revealed this issue on 4.4.1 kernel, latest working version is 4.4.0

**Comment by prahal** [comment]
Fixed in 4.4.6 here (debian linux kernel).
A few overlay (ovl) fixes went in upstream. Here they did the job.

**Comment by fedya** [comment]
@prahal could you point a patch?

**Comment by robxu9** [comment]
This LKML thread might be helpful: https://lkml.org/lkml/2016/3/10/682

**Comment by Grief** [comment]
I have similar problem on (.../merged/.dockerinit: operation not permitted) with kernel `4.5` while everything works as expected when I only switch it to `4.4.5`. Docker version 1.10.3.

**Comment by onorua** [comment]
According to: https://lkml.org/lkml/2016/3/14/274 there is a patch present. I've checked and it was not merged into mainline yet. There is nothing docker can do about it. For some reason overlayfs on ext4 treated by kernel as "encrypted" volume in new kernels.  

> This could only happen if the EXT4_ENCRYPT_FL flag is set.  (I assume
> you weren't actually trying to use ext4 encryption.)  The flag can't
> be set using the FS_IOC_SETFLAGS ioctl.  It can only be set using
> EXT4_IOC_SET_ENCRYPTION_POLICY.

So, I'm going to close this for now, as patch is on the way.

**Comment by thaJeztah** [comment]
Thanks for the heads-up @onorua!

**Comment by Grief** [comment]
I confirm that the issue is not reproducible in kernel 4.5.2 anymore

**Comment by shtrom** [comment]
I can confirm that upgrading to linux-image-amd64 4.5.0-2-amd64 (now in testing) on Debian fixes the issue.
