### ISSUE TITLE
Fails to restart containers occasionally, but often.

### ISSUE THREAD

**Issue by chakshugoyal** [docker/docker#20964]
command: docker start cs50ide
An error occured trying to connect: Post http://127.0.0.1:2375/v1.22/containers.cs50ide/start: dial tcp 127.0.0.1: connectex: No connection could be made because the target machine actively refused it.
Error: failed to start containers: cs50ide

**Comment by unclejack** [comment]
More information is required to investigate this issue. There's no way to investigate without the requested information. 

I'll close this now. This issue will be re-opened if the required information is provided. There's no need to open a new issue.
