### ISSUE TITLE
Proposal: container startup notification socket

### ISSUE THREAD

**Issue by Xenopathic** [docker/docker#20968]
Once a container has been 'started' by Docker, the services within the container may still be initializing (or in the case of a development container, performing provisioning). There is currently no way of determining when a container is actually ready, which it may not be even if the service has already started listening on a port.

My proposal is to implement systemd's sd_notify mechanism, where a socket file is placed within the container at some location and the environment variable NOTIFY_SOCKET is set to the path of that socket. The container can then indicate readiness by writing `READY=1` to the socket (see https://www.freedesktop.org/software/systemd/man/sd_notify.html for more information). Using systemd's approach also has the benefit that a systemd-aware application in the container will interface transparently, reporting status as necessary.

Then, Docker listens to the socket, and can report to the caller when the container reports readiness. I suggest a new command line option to complement detach mode which waits until the container is 'ready' before detaching. This will be primarily useful when using Docker in scripted environments such as CI.

In addition, Docker could itself look for a NOTIFY_SOCKET env variable, and would pass any messages from the internal container socket through to it, allowing Docker containers to become first-class citizens in systemd by reporting readiness and status.

Using sd_notify also lays the foundation for status reporting from containers, as defined by the sd_notify spec, a service in the container could send `STATUS=...` which could be show in `docker ps` output. That's something for the future, the initial implementation would simply ignore all other messages.

**Comment by Xenopathic** [comment]
Here's a real-world example of why this is important to me, and an example of how it might be implemented:

https://github.com/Xenopathic/ceph-keystone.docker/blob/2f5c04c74d7668b0327b21ac123392c7efcf6ef8/entrypoint.sh#L274-L276

https://github.com/owncloud/core/blob/078cc3b3f0ac34919b4b30cfa08799ce7743bc87/apps/files_external/tests/env/start-swift-ceph.sh#L66-L72

**Comment by thaJeztah** [comment]
We have health checks in 1.12, which should be able to provide this
