### ISSUE TITLE
API: DELETE network/:id should return a response with code StatusNoContent if successful

### ISSUE THREAD

**Issue by allencloud** [docker/docker#20976]
Hi, all,

Today, I found that when I deleted a network from docker daemon via API,  API returned a response with status code 200 if successful. And I think it is better to return 204 (no content). 
While I search other delete apis, below is the result.
```
204: DELETE volumes;
204: DELETE containers; 
200: DELETE networks;
200: DELETE images;
```

[https://github.com/docker/docker/blob/master/api/server/router/network/network_routes.go#L149-L151](https://github.com/docker/docker/blob/master/api/server/router/network/network_routes.go#L149-L151)

while `DELETE images` returns a list, so 200 not 204 seems reasonable.

And `DELETE networks` should return 204 , i think.

**Comment by HackToday** [comment]
Thanks for report. for `DELTE images` I am not sure why have a list ?  It seems API design not follow same style. Which I think maybe not a good idea.

**Comment by allencloud** [comment]
@HackToday 
Result is like below,
```
HTTP/1.1 200 OK
Content-type: application/json
[
 {"Untagged": "3e2f21a89f"},
 {"Deleted": "3e2f21a89f"},
 {"Deleted": "53b4f83ac9"}
]
```

Also in [https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api_v1.22.md](https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api_v1.22.md)
