### ISSUE TITLE
Allow networks to overlap subnet (using option)

### ISSUE THREAD

**Issue by flungo** [docker/docker#20986]
**Output of `docker version`:**

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   9894698
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   9894698
 Built:        
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 10
Images: 289
Server Version: 1.9.1
Storage Driver: btrfs
 Build Version: Btrfs v4.2.2
 Library Version: 101
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.3.6-coreos
Operating System: CoreOS 899.9.0
CPUs: 4
Total Memory: 7.655 GiB
Name: media-srv-1.lungo.co.uk
ID: ANSS:L2RV:YMWL:ZS3X:VYHV:GGQC:HGXQ:YUZS:LGFT:4OXN:QC4P:63G4
```

**Provide additional environment details (AWS, VirtualBox, physical, etc.):**

Physical

**List the steps to reproduce the issue:**

1. Use `brctl` or any other means to create a bridge to an existing network, in my case the bridge is called `br-services`
1. Run `docker network create -o com.docker.network.bridge.name=br-services --subnet 172.16.32.0/20 --ip-range 172.16.46.0/23 services-1` to create a bridge network using the existing bridge device.
1. Run `docker network create -o com.docker.network.bridge.name=br-services --subnet 172.16.32.0/20 --ip-range 172.16.44.0/23 services-2` to create a bridge network using the existing bridge device.

**Describe the results you received:**

```
Error response from daemon: cannot create network br-services (4bf149f53ecaf0d03e70a26831c8b179283bb50d0e5e723e05222b13566059d0): conflicts with network fe130e9edce3c3e7a3fb64ac6703aa15bd77206c683a23829743bdf1e3357281 (br-services): networks have overlapping IPv4
```

**Describe the results you expected:**

It makes sense for the check to be done in most cases as overlapping networks would be an issue, if I wasn't connecting both networks to the same bridge device. There should be an option to override this behaviour and force the creation of the network.

**Provide additional info you think is important:**

Relates to and probably requires #20985. Either different gateways would have to be specified or the same gateway should be used without docker allocating the gateway address.

**Comment by mavenugo** [comment]
@flungo `docker network` provides default isolation guarantees between the containers connected to a network. Driver plays a huge role in providing the isolation. 2 different `bridge` networks having to share the same bridge will break that guarantee. Today we use iptable rules sparingly to provide that isolation only based on the bridge identifier (as of v1.10.x). Hence 2 different networks sharing the same device will break the isolation.

Can you please explain the use-case so that we can try and get a proper solution (rather than trying to workaround the situation).

BTW, pls also take a look at the proposed experimental macvlan/ipvlan drivers : https://github.com/docker/libnetwork/pull/964.

**Comment by flungo** [comment]
@mavenugo Thanks for getting back to me. The main goal was to be able to put machines into certain IP ranges by using separate Docker networks. I understand the guarantees that are intended and to be honest, this would just be a hack around not being able to specify an exact IP within the network. I am fairly confident there is already an issue somewhere for a `--ip` flag on `docker run` which would allow per machine static IP allocation - which I currently achieve using `ip netns` to add an IP to the containers networking namespace. The other possibly useful feature could be to allow multiple 'ranges' in a network which could be referenced using something like `--net=network:range` to specify a named range within the subnet for allocation. The use/need for this is to allow source based firewall rules on a router.

What I have done now (which probably works better for me) is create networks with an unallocated block of network addresses and setup static routing to the host machine for this range. Although this would work for the aforementioned use case, it is a little more complicated to set up and will not provide Layer 2 communication if that is required - for me not an issue.

**Comment by cpuguy83** [comment]
@flungo `--ip` is part of Docker 1.10.

**Comment by mavenugo** [comment]
@flungo as @cpuguy83 mentioned Docker 1.10 supports `--ip` in `docker run` which enables static IP assignment to containers connected to user-defined networks. Does that solve your problem ?

Also PTAL : https://github.com/docker/docker/pull/21122, which brings in native underlay integration using macvlan and ipvlan drivers that makes use of linux kernel capabilities. That might interest you as well.

Should we close this issue ?

**Comment by flungo** [comment]
Thanks both for the info about the 1.10 addition of the `--ip` flag. This will prove extremely useful and could probably mitigate any use case of this. The only scenario where this would be needed would be where convenience of not having to allocate the ip and just having it given from a pool/range but I expect it is probably extremely niche.

I will also take a look at the macvlan and ipvlan drivers. They will be extremely useful where allocating a subnet and routing to each docker host would be unfeasible and particularly useful if they provide support for linking between container on the same VLAN but on different hosts as well.
