### ISSUE TITLE
Got trapped into the aufs folder

### ISSUE THREAD

**Issue by mahmoodn** [docker/docker#20989]
Excuse me, I know this is not a discussion forum, but indeed I asked my question on SO and the mailing list. However, I didn't receive any answer and I am stuck at this problem.

Short description: I don't know why the `docker exec` command eventually fall in to the aufs folder which should be avoided. The commands I use are
```

docker load -i /home/mahmood/cloudsuite_v3/ubuntu.tar
docker build -t data-analytics:dataset ./data-analytics/dataset
docker create --name data data-analytics:dataset
docker build -t data-analytics:base ./data-analytics/base
docker build -t data-analytics:master ./data-analytics/master 
docker run -d -t --dns 127.0.0.1 -P --name master -h master.cloudsuite.com --volumes-from data data-analytics:master
docker exec -it master bash
```

The full output is available at [pastebin](http://pastebin.com/m4LqFRAY)

Some more info:

```
mahmood@orca:cloudsuite_v3$ uname -a
Linux orca 3.2.0-99-generic #139-Ubuntu SMP Mon Feb 1 23:16:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

mahmood@orca:cloudsuite_v3$ docker info
Containers: 4
 Running: 1
 Paused: 0
 Stopped: 3
Images: 74
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 161
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.2.0-99-generic
Operating System: Ubuntu precise (12.04.5 LTS)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 31.36 GiB
Name: orca
ID: SEWM:SSEX:I74Y:47IT:QXHS:2MLV:FQ27:WI4Q:7UZ6:OE6U:DNNR:QLZJ
Http Proxy: http://127.0.0.1:8123/
Https Proxy: http://127.0.0.1:8123/

mahmood@orca:cloudsuite_v3$ docker version
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:33:45 2016
 OS/Arch:      linux/amd64
Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:33:45 2016
 OS/Arch:      linux/amd64
mahmood@orca:cloudsuite_v3$

```

P.S: If you want, I can provide the docker files and the images

**Comment by thaJeztah** [comment]
Your kernel version is too old, and misses various features that docker needs to run. The absolute minimum version to run Docker is kernel 3.10. Ubuntu 12.04 is also getting quite old, if possible, upgrade to 14.04 and a more modern kernel.

**Comment by thaJeztah** [comment]
I'll close this issue, because this is not a supported kernel, but feel free to comment here after I've closed

**Comment by mahmoodn** [comment]
I don't know what do you mean by "unsupported kernel". If it is not a supported one, then I think docker package should be unavailable for that. So, when I am able to install that, I think it is a supported one. Do you think I missed something in the steps?

**Comment by thaJeztah** [comment]
From the installation docs; https://docs.docker.com/engine/installation/linux/ubuntulinux/

> Docker requires a 64-bit installation regardless of your Ubuntu version. Additionally, your kernel must be 3.10 at minimum. The latest 3.10 minor version or a newer maintained version are also acceptable.

> Kernels older than 3.10 lack some of the features required to run Docker containers. These older versions are known to have bugs which cause data loss and frequently panic under certain conditions.

And for Ubuntu 12.04 (same page)

> Ubuntu Precise 12.04 (LTS)
> For Ubuntu Precise, Docker requires the 3.13 kernel version. If your kernel version is older than 3.13, you must upgrade it. Refer to this table to see which packages are required for your environment:
