### ISSUE TITLE
Docker Cloud no "right click on the terminal and select Paste" option

### ISSUE THREAD

**Issue by dvohra** [docker/docker#20980]
_ Docker version:_
Docker 1.9.1-cs2

_Provide additional environment details (AWS, VirtualBox, physical, etc.):_
Cloud Provider AWS
1 Container  52.91.228.54  Amazon Web Services  us-east-1b  t2.micro  Docker 1.9.1-cs2

 

 

_List the steps to reproduce the issue:_
1.Create or Buy a Docker Cloud account
2.Create a Node
3.Create a Service with Docker image 'mysql' tag latest

Start the Terminal. According to usage "**In order to copy text from the terminal, select the text to copy, right click on it and select Copy In order to paste text to the terminal, right click on the terminal and select Paste**"

_Describe the results you received:_
No "right click on the terminal and select Paste" option is available.

_Describe the results you expected:_

A right click on the terminal and select Paste option

_Provide additional info you think is important:_
Docker Cloud $15 / node / month

**Comment by thaJeztah** [comment]
Thanks for reporting @dvohra. Docker Cloud is managed by a different team, so unfortunately, we can't solve this issue here, but I'll pass on this information to the Docker Cloud team to look into

**Comment by thaJeztah** [comment]
@dvohra just got a reply; because you have a paid account; there should be a "support" button in the app; that should bring you in contact with the support team. For non-paid accounts there's https://forums.docker.com/c/docker-cloud.

**Comment by dvohra** [comment]
A Help button is provided. Is it 'Help' or 'Support'.

**Comment by unclejack** [comment]
This issue seems to be about a project which isn't managed by the Docker engine open source project.

I'll close this issue now. The discussion can continue as needed.

**Comment by dvohra** [comment]
No one replied from paid support either.

**Comment by j-rewerts** [comment]
@dvohra You ever hear anything about this? I have this issue as well.

**Comment by dvohra** [comment]
Not yet.
