### ISSUE TITLE
Option to not allocate the default gateway

### ISSUE THREAD

**Issue by flungo** [docker/docker#20985]
**Output of `docker version`:**

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   9894698
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   9894698
 Built:        
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 10
Images: 289
Server Version: 1.9.1
Storage Driver: btrfs
 Build Version: Btrfs v4.2.2
 Library Version: 101
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.3.6-coreos
Operating System: CoreOS 899.9.0
CPUs: 4
Total Memory: 7.655 GiB
Name: media-srv-1.lungo.co.uk
ID: ANSS:L2RV:YMWL:ZS3X:VYHV:GGQC:HGXQ:YUZS:LGFT:4OXN:QC4P:63G4
```

**Provide additional environment details (AWS, VirtualBox, physical, etc.):**
Physical

**List the steps to reproduce the issue:**

1. Use `brctl` or any other means to create a bridge to an existing network, in my case the bridge is called `br-services`
1. Run `docker network create -o com.docker.network.bridge.name=br-services --subnet 172.16.32.0/20 --ip-range 172.16.46.0/23 --gateway 172.16.32.1 services` to create a bridge network using the existing bridge device.

**Describe the results you received:**

Network is created and `172.16.32.1` is allocated to the bridge device on the host.

**Describe the results you expected:**

There should be an option to not allocate the default gateway address to the host machine. In my case I have created the bridge to a vlan network which has a router running on `172.16.32.1` which I would like to be used as the default gateway.

**Provide additional info you think is important:**

Enabling such option should automatically set `com.docker.network.bridge.enable_ip_masquerade` to `false`.

Let me know if you need any more details.

**Comment by aboch** [comment]
This functionality was eventually also requested in https://github.com/docker/docker/issues/20758.

**Comment by flungo** [comment]
Seems to be requesting the same functionality, this may be closed as duplicate if deemed so.

**Comment by thaJeztah** [comment]
Yes, let's close this one to keep the conversation in a single location, thanks!
