### ISSUE TITLE
Relative VOLUME declarations are always relative to "/"

### ISSUE THREAD

**Issue by djmaze** [docker/docker#20988]
Output of `docker version`:

```
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Thu Feb 25 09:29:05 2016
 OS/Arch:      linux/amd64
```

Output of `docker info`:

```
Containers: 167
 Running: 2
 Paused: 0
 Stopped: 165
Images: 902
Server Version: 1.10.2
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.4.3-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.716 GiB
Name: xxx
ID: xxx
Username: xxx
Registry: https://index.docker.io/v1/
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):

Physical Linux machine.

List the steps to reproduce the issue:

1.) Create a Docker image with the following Dockerfile:

```Dockerfile
FROM ubuntu
WORKDIR /usr/src/app
VOLUME ./data
```

2.) Run the following command:

```bash
docker run -it --rm <imagename> sh -c "mount | grep /data"
```

Describe the results you received:

Volume is mounted at `/data`:

```
/dev/sda9 on /data type ext4 (rw,relatime,data=ordered)
```

Describe the results you expected:

Volume should be mounted at `/usr/src/app/data`.

```
/dev/sda9 on /usr/src/app/data type ext4 (rw,relatime,data=ordered)
```

Provide additional info you think is important:

Relative VOLUME declarations should either become relative to the WORKDIR or raise an error instead.

**Comment by thaJeztah** [comment]
Thanks for reporting. While I can see this being consistent, I'm not sure we'd be able to change this without introducing backward-incompatible changes, resulting in Dockerfiles no longer being built as they were before.

**Comment by phemmer** [comment]
Docker changes things that result in backwards incompatibility all the time. (Just playing Devil's advocate, I don't agree or disagree with the change)

Perhaps we should start a document somewhere with all the proposed changes that would result in significant breakage. Just a list of issue numbers or something. And then when docker 2 comes around, we pull out the document and decide which ones we want to implement.
If the document gets big enough, it might even be used as the driving force for bumping the version number to 2.0.

**Comment by thaJeztah** [comment]
@phemmer yup, one of the first issues I opened https://github.com/docker/docker/issues/4907.

w.r.t. a list of proposed changes; I try to label each issue with "area/builder" so that we should be able to create such list at some point

**Comment by thaJeztah** [comment]
We haven't seen more requests for this, and this is consistent with the `--volume` flag also requiring to specify the full path in the container. Given that this would be a breaking change, and not a high priority, I'm closing this. But as always, feel free to comment if you don't agree
