### ISSUE TITLE
docker login broken in master

### ISSUE THREAD

**Issue by runcom** [docker/docker#20993]
```
$ docker login

Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: runcom
Password: 
Error response from daemon: parse https://https:%2F%2Findex.docker.io%2Fv1%2F/v1/users/: percent-encoded characters in host
```
Broken in https://github.com/docker/docker/pull/20832, will be fixed by https://github.com/docker/docker/pull/20970

**Comment by thaJeztah** [comment]
Do we have a test, or can we add one so that we don't regress in future? This should've been picked up by a test IMO

**Comment by runcom** [comment]
@thaJeztah it hasn't :) read more here https://github.com/docker/docker/pull/20984
