### ISSUE TITLE
[1.10.2 ] docker rmi fails when removing images that tag is none

### ISSUE THREAD

**Issue by glaivelee** [docker/docker#20991]
desc. of problem:

`docker version:`
`Client:`
 `Version:      1.10.2`
 `API version:  1.22`
 `Go version:   go1.5.3`
`Git commit:   c3959b1`
 `Built:        Mon Feb 22 16:16:33 2016`
 `OS/Arch:      linux/amd64`

`Server:`
 `Version:      1.10.2`
 `API version:  1.22`
 `Go version:   go1.5.3`
 `Git commit:   c3959b1`
 `Built:        Mon Feb 22 16:16:33 2016`
` OS/Arch:      linux/amd64`

`docker info:` 
`Containers: 0`
 `Running: 0`
 `Paused: 0`
 `Stopped: 0`
`Images: 132`
`Server Version: 1.10.2`
`Storage Driver: devicemapper`
 `Pool Name: docker-202:17-51642371-pool`
 `Pool Blocksize: 65.54 kB`
 `Base Device Size: 107.4 GB`
 `Backing Filesystem: ext4`
 `Data loop file: /var/lib/docker/devicemapper/devicemapper/data`
 `Library Version: 1.02.107-RHEL7 (2015-12-01)`
`Execution Driver: native-0.2`
`Logging Driver: json-file`
`Plugins: `
 `Volume: local`
 `Network: bridge null host`
`Kernel Version: 4.4.0-1.el7.elrepo.x86_64`
`Operating System: CentOS Linux 7 (Core)`
`OSType: linux`
`Architecture: x86_64`
`CPUs: 4`

`uname -a`
`Linux iZ2555feo7tZ 4.4.0-1.el7.elrepo.x86_64 #1 SMP Sun Jan 10 21:17:16 EST 2016 x86_64 x86_64 x86_64 GNU/Linux`

`docker images -a`
`REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE`
`redis                latest              c0345b7e8306        11 days ago         151.3 MB`
`<none>               <none>              f6f76490a798        11 days ago         151.3 MB`
`<none>               <none>              03d98758abfa        11 days ago         151.3 MB`
`<none>               <none>              cd6870cb03f5        11 days ago         151.3 MB`

I want to rmi a image that the tag is none : f6f76490a798
`docker rmi f6f76490a798`
result is :
`Failed to remove image (f6f76490a798): Error response from daemon: conflict: unable to delete f6f76490a798 (cannot be forced) - image has dependent child images`

Expected Results:
 images that tag is none  deleted successfully.

How can I do?

**Comment by HackToday** [comment]
you have many other images, which seems have dependence, also seems redis image need some following <none>

suggest you check  `docker inspect <image-id>`  if related images have cross reference

**Comment by glaivelee** [comment]
@HackToday 

`docker inspect c0345b7e8306`
```
[
    {
        "Id": "sha256:c0345b7e830642383eb98c7c6e947fab4b106999a5152949d023cfc2e498c2ea",
        "RepoTags": [
            "redis:latest"
        ],
        "RepoDigests": [],
        "Parent": "sha256:f6f76490a798b98af97a56c547bc07cef2c78432b939ef450b17221d04781887",
        "Comment": "",
        "Created": "2016-02-24T23:15:43.896204231Z",
        "Container": "bf13923c553d3751c0f57f0f45ed9b19a1feb0fba0f8d9279fe9874340b96635",
        "ContainerConfig": {
            "Hostname": "4ef519a8cdd7",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "6379/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "REDIS_VERSION=3.0.7",
                "REDIS_DOWNLOAD_URL=http://download.redis.io/releases/redis-3.0.7.tar.gz",
                "REDIS_DOWNLOAD_SHA1=e56b4b7e033ae8dbf311f9191cf6fdf3ae974d1c"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) CMD [\"redis-server\"]"
            ],
            "Image": "cd2f51e684003d89d0e6de931d6ab4198bb932fed603aea4623316682a887ac2",
            "Volumes": {
                "/data": {}
            },
            "WorkingDir": "/data",
            "Entrypoint": [
                "/entrypoint.sh"
            ],
            "OnBuild": [],
            "Labels": {}
        },
        "DockerVersion": "1.9.1",
        "Author": "",
        "Config": {
            "Hostname": "4ef519a8cdd7",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "6379/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "REDIS_VERSION=3.0.7",
                "REDIS_DOWNLOAD_URL=http://download.redis.io/releases/redis-3.0.7.tar.gz",
                "REDIS_DOWNLOAD_SHA1=e56b4b7e033ae8dbf311f9191cf6fdf3ae974d1c"
            ],
            "Cmd": [
                "redis-server"
            ],
            "Image": "cd2f51e684003d89d0e6de931d6ab4198bb932fed603aea4623316682a887ac2",
            "Volumes": {
                "/data": {}
            },
            "WorkingDir": "/data",
            "Entrypoint": [
                "/entrypoint.sh"
            ],
            "OnBuild": [],
            "Labels": {}
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 151282510,
        "VirtualSize": 151282510,
        "GraphDriver": {
            "Name": "devicemapper",
            "Data": {
                "DeviceId": "168",
                "DeviceName": "docker-202:17-51642371-56b1d94012a94090c62b3b607c283737d0f508b0ecc6bbcbf9297b2876b86a95",
                "DeviceSize": "107374182400"
            }
        }
    }
]
```

**Comment by coolljt0725** [comment]
@glaivelee  The output of `docker inspect c0345b7e8306` shows the image `f6f76490a798 ` is the parent of `redis:latest`, so you can't delete `f6f76490a798 `. Not all the images with tag `none` can be deleted,  only the dangling images(  output of `docker images -f dangling=true` ) could.

**Comment by glaivelee** [comment]
@coolljt0725 
You mean if I want to use the `redis:latest`, they* must be retained  ?

*<none> <none> f6f76490a798 11 days ago 151.3 MB
*<none> <none> 03d98758abfa 11 days ago 151.3 MB
*<none> <none> cd6870cb03f5 11 days ago 151.3 MB

**Comment by coolljt0725** [comment]
@glaivelee  yes

**Comment by thaJeztah** [comment]
@glaivelee correct; the images without a tag here, are intermediate images; basically they're the layers of an image, created during build. Each step in a Dockerfile creates an image-layer which, in older versions of docker (up until 1.10) also created an image without name/tag.

This changed in docker 1.10, where only the layer data itself is kept, but no "images" are visible for those layers (only for images that were present before upgrading to 1.10, and have been migrated to the new "content addressable" storage structure)

I'm going to close this issue, because this is working as expected, but feel free to comment after I've closed

**Comment by glaivelee** [comment]
@coolljt0725 thank you for your answers

**Comment by truatpasteurdotfr** [comment]
maybe related to https://github.com/moby/moby/issues/21764 ?
```
docker tag f6f76490a798 redis:del
docker rmi redis:del
```
