### ISSUE TITLE
`docker ps` Names column is better replaced with Name 

### ISSUE THREAD

**Issue by HackToday** [docker/docker#20992]
Output of `docker version`:

```
Latest docker
```

Output of `docker info`:

```
docker volume, network all use following format

`NAME` or `VOLUME NAME`

So in order to keep CLI style consistent, it is better rename with NAMES to NAME

```

Provide additional environment details (AWS, VirtualBox, physical, etc.):

List the steps to reproduce the issue:
1. docker ps
2. 
```
root@1c9affa56351:/go/src/github.com/docker/docker# docker ps -a    
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
bb713485fb68        busybox             "sh"                44 minutes ago      Up 44 minutes                           desperate_hodgkin
```

Describe the results you expected:
NAMES to be NAME

Provide additional info you think is important:

**Comment by HackToday** [comment]
ping @thaJeztah  Let me know what you thoughts about it. Thanks

**Comment by HackToday** [comment]
If you think it is OK, I could provide a PR about it

**Comment by thaJeztah** [comment]
Actually, this was proposed before, and there's a reason it's called `NAMES`; see https://github.com/docker/docker/pull/14128#issuecomment-121948256

So, for that reason, I think we should keep this as it is. Thanks for suggesting though!

**Comment by HackToday** [comment]
Glad to know that,  
```
For those still confused, containers get a new name for each container they're linked to (/my-app/db, for example).
```

yes, I was confused if not read them. Thanks

**Comment by thaJeztah** [comment]
Perhaps we can still change this at some point, given that the new `--link` on custom networks no longer creates "links" but only aliases / entries for the embedded DNS. But for now, I think we should keep it as-is. :smile:
