### ISSUE TITLE
Ctrl-C doesn't send SIGINT properly

### ISSUE THREAD

**Issue by Vanuan** [docker/docker#21008]
Output of `docker version`:

```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64
```

Output of `docker info`:

```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64
john@john-laptop:~/git/ui/missioncontrol$ docker info
Containers: 6
 Running: 1
 Paused: 0
 Stopped: 5
Images: 33
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 68
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-57-generic
Operating System: Ubuntu 14.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.68 GiB
Name: john-laptop
ID: LH2W:7MXN:JYYW:NO5F:CTTJ:KDJP:BHLJ:62IC:4EIJ:IUQY:Q3E3:PODW
WARNING: No swap limit support
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):

physical

List the steps to reproduce the issue:
1. `docker run --rm -it alpine sleep 5`
2. Press "Ctrl-C"

Describe the results you received:

Ctrl-C is ignored.

Describe the results you expected:

The `sleep` process terminates immediately.

Provide additional info you think is important:

When executing the same in bash process, `sleep` is terminated by Ctrl-C.

**Comment by Vanuan** [comment]
Could be duplicated of #2838, but it's closed. And I don't know why. Is it expected behavior? I thought `-ti` options should make docker processes to behave the same as usual bash processes.

**Comment by Vanuan** [comment]
Found another duplicate: #3793

**Comment by thaJeztah** [comment]
Have you tried

    docker run --rm -it alpine sh -c "sleep 5"

So that "sleep" is a process in the shell?

**Comment by Vanuan** [comment]
It works. How can I make it a default behavior, so that any CMD would be executed in a shell?

**Comment by thaJeztah** [comment]
No, it never is a default option, because the command you're running may itself be a shell. You could build your own image using a shell as an "entrypoint", e.g. https://github.com/jfrazelle/dockerfiles/blob/master/fish/Dockerfile

**Comment by Vanuan** [comment]
Tried this:

    ENTRYPOINT ["sh"]

Didn't work:

    $ docker run --rm -it  shell-image ls
    sh: can't open 'ls'

**Comment by Vanuan** [comment]
Ok, this works:

    ENTRYPOINT ["sh"]

**Comment by Vanuan** [comment]
Well, it requires quoting arguments, which is not good:

    $ docker run --rm -it  shell-image echo test
    # empty line

Is there a solution to that?

**Comment by Vanuan** [comment]
I thought this is a bug (#21014), but it's a valid behavior. So I need an "sh" option to interpret all arguments as arguments to the first argument-command.

**Comment by cpuguy83** [comment]
@Vanuan You basically need to setup whatever gets run in the container with signal handlers.
A lot of things, when run as PID1, drop their signal handlers.

You can do something like:

```sh
#!/bin/sh
trap "exit 0" SIGINT

sleep 5
```

**Comment by Vanuan** [comment]
I want to be able to use docker as a proxy to dev tools. Some (it not all) dev tools don't have SIGINT handlers. So I need a global solution. For now, only this workaround is suitable:

    ENTRYPOINT ["tini", "--"]

**Comment by Vanuan** [comment]
Other reasons to use tini as your entrypoint: https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/

**Comment by cpuguy83** [comment]
That'll go away in 1.11 when we move to using containerD as the execution runtime.

**Comment by Vanuan** [comment]
Oh, thanks!

**Comment by Vanuan** [comment]
Will Ctrl-C issue go away too?

**Comment by cpuguy83** [comment]
@Vanuan No, we won't be doing anything to make a pid be not be PID 1, this will be totally up to the what gets started in the container.

**Comment by Vanuan** [comment]
IMHO, it's much more common to run program that doesn't expect to be run as PID 1. Vagga creator thinks the same: http://vagga.readthedocs.org/en/latest/pid1mode.html
This issue makes it particularly annoying to use Docker for any development tools.

**Comment by cpuguy83** [comment]
@Vanuan Docker starts a process in a container for you, it's up to you to decide how it should run.
