### ISSUE TITLE
Cannot run hello-world off fresh install of docker Mac OSX

### ISSUE THREAD

**Issue by jpiv** [docker/docker#21012]
Having trouble getting Docker to pull base images, or anything for that matter from the docker hub or github.  It's unable to resolve the host, I've attempted many fixes with no success, I feel like I'm missing something obvious.

Output of `docker version`:

```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
```

Output of `docker info`:

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.1.18-boot2docker
Operating System: Boot2Docker 1.10.2 (TCL 6.4.1); master : 611be10 - Mon Feb 22 22:47:06 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: KSC3:ESFA:VI2V:YYZW:TCDU:HNSM:NQF6:WYKR:TY2M:IC2F:E54C:UEHA
Debug mode (server): true
 File Descriptors: 10
 Goroutines: 21
 System Time: 2016-03-07T23:14:46.861389228Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

Provide additional environment details (AWS, VirtualBox, physical, etc.): Mac OSX Yosemite 10.10.1

List the steps to reproduce the issue:
1. Fresh install docker
2. Start quick start terminal
3. docker run hello-world

Describe the results you received:
Received this error:
```
docker: Error while pulling image: Get https://index.docker.io/v1/repositories/library/hello-world/images: dial tcp: lookup index.docker.io on 10.1.10.1:53: no such host.
```

Describe the results you expected:
Hello world docker image to run.

Provide additional info you think is important:
Attempted multiple fresh installs of docker each time deleting docker quickstart terminal and kinematic, deleting ~/.docker and finally deleting /usr/local/bin/docker, docker-compose and docker-machine.  Followed by installing from DockerToolbox-1.10.2

![Terminal image docker quickstart](http://s17.postimg.org/4gj96ol5b/Screen_Shot_2016_03_07_at_6_13_53_PM.png)

**Comment by Vanuan** [comment]
Why is it trying to reach DNS on 10.1.10.1:53? Is it your default dns?

**Comment by HackToday** [comment]
It seems you have configured proxy, is it ?

**Comment by jpiv** [comment]
We have no proxy server and I'm able to `curl https://index.docker.io/v1/repositories/library/hello-world/images` and get a response

**Comment by jpiv** [comment]
The issue was that we were hitting Amazon DNS and then falling back to Google DNS if the domain wasn't found.  Using Google DNS first fixed the issue.
