### ISSUE TITLE
[1.8.3] Docker container logging blew up host

### ISSUE THREAD

**Issue by vincentwoo** [docker/docker#21010]
Output of `docker version`:

```
Docker version 1.8.3, build f4bf5c7
```

Output of `docker info`:

```
Containers: 107
Images: 144
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: none
Kernel Version: 3.19.0-51-generic
Operating System: Ubuntu 14.04.4 LTS
CPUs: 8
Total Memory: 29.45 GiB
Name: execute-1457337606
ID: QRYP:WXAR:ML3Y:XSE2:3LNG:3W55:TSQE:6ZWG:GU2A:LFZZ:3LXY:OBVQ
WARNING: No swap limit support
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):
GCE ubuntu 14.04

List the steps to reproduce the issue:
no clue - as usual probably just making/destroying a ton of containers

Describe the results you received:

My host started suffering degraded performance and I noticed that the logging daemon that I use to persist `/var/log/upstart/docker.log` was pegging a whole core (and so was the docker daemon). Inspecting said log showed the following over and over:

```
ERRO[52527] Failed to log msg "\r" for logger json-file: write /var/lib/docker/containers/24dec44ac56fb33ffbc3944a8bb3c49b26024b18f25651a35c2f8780ac5c862f/24dec44ac56fb33ffbc3944a8bb3c49b26024b18f25651a35c2f8780ac5c862f-json.log: bad file descriptor
ERRO[52527] Failed to log msg "\r" for logger json-file: write /var/lib/docker/containers/24dec44ac56fb33ffbc3944a8bb3c49b26024b18f25651a35c2f8780ac5c862f/24dec44ac56fb33ffbc3944a8bb3c49b26024b18f25651a35c2f8780ac5c862f-json.log: bad file descriptor
ERRO[52527] Failed to log msg "\r" for logger json-file: write /var/lib/docker/containers/24dec44ac56fb33ffbc3944a8bb3c49b26024b18f25651a35c2f8780ac5c862f/24dec44ac56fb33ffbc3944a8bb3c49b26024b18f25651a35c2f8780ac5c862f-json.log: bad file descriptor
ERRO[52527] Failed to log msg "\r" for logger json-file: write /var/lib/docker/containers/24dec44ac56fb33ffbc3944a8bb3c49b26024b18f25651a35c2f8780ac5c862f/24dec44ac56fb33ffbc3944a8bb3c49b26024b18f25651a35c2f8780ac5c862f-json.log: bad file descriptor
ERRO[52527] Failed to log msg "\r" for logger json-file: write /var/lib/docker/containers/24dec44ac56fb33ffbc3944a8bb3c49b26024b18f25651a35c2f8780ac5c862f/24dec44ac56fb33ffbc3944a8bb3c49b26024b18f25651a35c2f8780ac5c862f-json.log: bad file descriptor
```

I've since disabled per-container logging (I didn't even know I had to **do** that!).

Describe the results you expected:

For uh, this to not happen.

Provide additional info you think is important:

Sorry, not a lot of insight here. I'm on an older docker daemon so apologies if you've addressed this already but I couldn't find an existing issue. I'll go back up to 1.10.x soon again, hopefully.

**Comment by thaJeztah** [comment]
There's been a lot of improvement in json-file logging, including log rotation. So I'll close this, but let me know if there's still an issue
