### ISSUE TITLE
Remote API: rename container responds with HTTP 500, should be HTTP 409

### ISSUE THREAD

**Issue by johnflavin** [docker/docker#21016]
Output of `docker version`:

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.3
 Git commit:   a34a1d5
 Built:        Sun Jan 17 16:14:45 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```
and
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.3
 Git commit:   a34a1d5
 Built:        Sun Jan 17 16:14:45 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        2016-02-22T22:37:33.778002647+00:00
 OS/Arch:      linux/amd64
```

Output of `docker info`:

```
Containers: 2
Images: 2
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 6
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: 1.9.1
ID: GRUE:YKCV:GNSM:XKMI:PUVD:TVCN:5DNV:FCFU:BKBI:INQB:YVHQ:EY7I
Debug mode (server): true
 File Descriptors: 13
 Goroutines: 18
 System Time: 2016-03-08T03:23:05.126551663Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```
and
```
Containers: 2
Images: 1
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 6
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.18-boot2docker
Operating System: Boot2Docker 1.10.2 (TCL 6.4.1); master : 611be10 - Mon Feb 22 22:47:06 UTC 2016
CPUs: 1
Total Memory: 996.1 MiB
Name: 1.10
ID: MFJG:IH2Q:XNRP:YIT6:PC7C:H4QB:HRAA:HFHZ:7C7F:DCH4:3DZ5:FB6N
Debug mode (server): true
 File Descriptors: 10
 Goroutines: 21
 System Time: 2016-03-08T03:19:22.153873407Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):
boot2docker VMs in VirtualBox, created with `docker-machine`.

List the steps to reproduce the issue:
1. Create two containers.
2. Rename one container. (For example, to "foo".) 
3. Using the remote API, `POST` to `/containers/(id or name)/rename?name=foo`, i.e. rename the second container to the same name as the first.

Describe the results you received:
The request fails with `HTTP 500 Internal Server Error`.

Describe the results you expected:
The request fails with `HTTP 409 Conflict`, message `name already assigned`, as described in the [remote API docs](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#rename-a-container).

Provide additional info you think is important:
I verified this behavior in the latest boot2docker iso running 1.10.2, and in an older iso running 1.9.1. See full version information above.

**Comment by coolljt0725** [comment]
@johnflavin  Thank you for your report, this has been fixed on master branch by PR #20699
Below is what I tried on master branch.
<pre><code>$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
d8ad839a79fd        busybox             "sh"                2 seconds ago       Up 1 seconds                            foo
478dc79c8705        busybox             "sh"                38 seconds ago      Up 37 seconds                           bar
$ curl -v -XPOST http://127.0.0.1:2375/containers/bar/rename?name=foo
* About to connect() to 127.0.0.1 port 2375 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 2375 (#0)
> POST /containers/bar/rename?name=foo HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:2375
> Accept: */*
>
< HTTP/1.1 409 Conflict
< Content-Type: text/plain; charset=utf-8
< Server: Docker/1.11.0-dev (linux)
< X-Content-Type-Options: nosniff
< Date: Tue, 08 Mar 2016 04:02:15 GMT
< Content-Length: 232
<
Error when allocating new name: Conflict. The name "/foo" is already in use by container d8ad839a79fd696028c49e8883333453c9c605965b195619b2b4e27def5f5057. You have to remove (or rename) that container to be able to reuse that name.
* Connection #0 to host 127.0.0.1 left intact</code></pre>

**Comment by johnflavin** [comment]
Ok. Thanks for checking that out for me.

**Comment by thaJeztah** [comment]
@coolljt0725 I think that is too much of a change for a patch release, so let's keep it for 1.11.
