### ISSUE TITLE
docker push

### ISSUE THREAD

**Issue by AFnRFCb7** [docker/docker#21028]
This bug can be seen in https://forums.docker.com/t/docker-push-not-working-in-1-8-1-not-logged-in/2894/17
and I experienced it in version 1.9.1

I was unable to push until I performed the workaround
described by Adriano Laranjeira

> In fact, it could be related to an issue in your config file.
> 
> Open your config.json, if they looks like this:
> 
> `
> 
> {
> "auths": {
>     "docker.io": {
>         "auth": "your_encoded_password",
>         "email": "your_email_address"
>     }
> }
> Change the endpoint of the login operations:
> 
> {
> "auths": {
>     "https://index.docker.io/v1/": {
>         "auth": "your_encoded_password",
>         "email": "your_email_address"
>     }
> }

Output of `docker version`:

```
(paste your output here)
```

Output of `docker info`:

```
(paste your output here)
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):

List the steps to reproduce the issue:
1.
2.
3.

Describe the results you received:

Describe the results you expected:

Provide additional info you think is important:

**Comment by thaJeztah** [comment]
wondering if this could be related to https://github.com/docker/docker/issues/21004#issuecomment-193475927. Can you check if there's a `.dockercfg` file in your home directory?

**Comment by thaJeztah** [comment]
I haven't received a response from OP, so I'm closing
