### ISSUE TITLE
Problem setting proxy for 1.10.2-cs1

### ISSUE THREAD

**Issue by jianghaitao** [docker/docker#21021]
I was doing an evaluation of DDC and following the instruction of manually install Docker CS engine on Unbutu 14.04. The Docker host is behind firewall and needs a HTTP/HTTPS proxy to get to the Internet.

However, it seems that the same proxy settings I put in /etc/default/docker has no effect  on the Docker CS engine, unlike Docker 1.9.1 or 1.10.1 open source versions.

Output of `docker version`:

```
Client:
 Version:      1.10.2-cs1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   8e23741
 Built:        Mon Feb 22 20:50:57 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2-cs1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   8e23741
 Built:        Mon Feb 22 20:50:57 2016
 OS/Arch:      linux/amd64
```

Output of `docker info`:

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 9
Server Version: 1.10.2-cs1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 13
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.16.0-50-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.798 GiB
Name: ddc-1
ID: VEDO:3U4Y:DY3I:XRPV:EQY6:B7ZV:CDI2:4AYP:WCVT:IXR7:HEYB:6WVU
WARNING: No swap limit support
```

proxy settings  for daemon (supposedly):
```
# grep http /etc/default/docker
export http_proxy=http://xxx:8080                                                                                             
export https_proxy=http://xxx:8080
```
http://xxx:8080 is our proxy. As one can see from above, docker info show no trace of proxy env setting for the daemon. 

As expected, I can not pull any image from Internet.  What's missing here??

**Comment by HackToday** [comment]
try curl and get related trace.

Also I am thinking if it is because you not set NO_PROXY for your host ?

**Comment by unclejack** [comment]
Docker Engine CS isn't supported by the Docker community on this issue tracker because it's not something provided by the Docker open source project. The reason behind this is quite simple: we can't look at that code to provide support.

Please get in touch with Docker support. I'll close this issue now since it's not an issue which affects the open source Docker and we can't help any further. Please feel free to continue the discussion.

**Comment by cpuguy83** [comment]
Are you certain /etc/default/docker is being evaluated when you start Docker?

**Comment by jianghaitao** [comment]
Docker ask everyone to do a trial / test run of DDC, thus no Docker support yet :)

Anyway, the problem is clearly due to the Docker CS daemon not take the proxy setting in /etc/default/docker (as indicated by docker info). Just answer to above:

- there is no proxy setting for the host

- Docker daemon did read the /etc/default/docker and get -H option specified, just not the proxy settings in the same file

curl and docker images runs fine, just can not pull new images from Internet.

**Comment by cpuguy83** [comment]
@jianghaitao How do you are start docker?

**Comment by jianghaitao** [comment]
```
service docker restart | stop | start

root      2111  0.0  0.4 427764 36060 ?        Ssl  Mar07   0:33 /usr/bin/docker daemon -D -H tcp://0.0.0.0:2375
```
-D and -H came from /etc/default/docker.

**Comment by cpuguy83** [comment]
Is this upstart, systemd, or stability?

**Comment by cpuguy83** [comment]
*sysvinit damn autocorrect

**Comment by HackToday** [comment]
@jianghaitao  I think you need set NO PROXY setting for localhost and your host run docker
