### ISSUE TITLE
Docker is not respecting groups on Arch Linux

### ISSUE THREAD

**Issue by christiandalsvaag** [docker/docker#21029]
I am unable to run `docker ps` etc. without running this via sudo. I have added my user to the group and it shows up when doing `groups`.

I have completed the following steps
`usermod -aG docker username`
`sudo systemctl restart docker`

I have tried logging out and rebooting the computer.

I also tried doing chown on both the socket and the binary to make sure that docker is the group owner of both. Neither helped.

I have tried building the most recent version from git as well as the version I am using now (1.10.2). But this does not change anything.

Docker version: 
$ docker version
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Thu Feb 25 09:29:05 2016
 OS/Arch:      linux/amd64

Docker info:
$ sudo docker info
Containers: 10
 Running: 2
 Paused: 0
 Stopped: 8
Images: 74
Server Version: 1.10.2
Storage Driver: devicemapper
 Pool Name: docker-8:6-265332-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 4.199 GB
 Data Space Total: 107.4 GB
 Data Space Available: 16.48 GB
 Metadata Space Used: 6.881 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.141 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.118 (2016-02-26)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.3-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.45 GiB
Name: discover
ID: XHE7:ADLD:QG3Z:ZQLB:GO5V:XLAX:YNWW:WLP4:5Z6S:J23Y:25ZL:2YWL

**Comment by HackToday** [comment]
when 'usermod -aG docker username'  did you use sudo ?
and any info for 'docker ps'

**Comment by christiandalsvaag** [comment]
You wouldn't be able to lock /etc/passwd without sudo when running usermod I believe; so yes I ran it with sudo.

`sudo docker ps` doesn't output any errors. It's just that it won't run without sudo even with me being in the docker group. The bin and sock are also owned by `root : docker`

**Comment by cpuguy83** [comment]
If it's not giving you any errors then the issue is not permissions.
Note that this is purely file system permissions, nothing to do with Docker directly.
Do you have a "DOCKER_HOST" envvar set?

**Comment by christiandalsvaag** [comment]
Running `docker` without `sudo docker` will yield
```
$ docker ps
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```
Yes. I had a DOCKER_HOST envvar set to an IP address: inet 172.17.0.1/16 which I found with `ip addr`

**Comment by thaJeztah** [comment]
If you're connecting to a daemon on the same host, the default is to connect to the daemon through `/var/run/docker.sock`, not through the IP address. Could you try if you're able to connect if the `DOCKER_HOST` env var is not set?

**Comment by christiandalsvaag** [comment]
Here we go. It's actually because of the environment variables, yes.

Thanks a lot for fast response.

Closing this issue.

**Comment by thaJeztah** [comment]
Cool, great it's resolved
