### ISSUE TITLE
group 'docker' does not exist

### ISSUE THREAD

**Issue by trishnaguha** [docker/docker#21031]
When I am trying to create `docker` group and add my user to it for non-root access, I'm getting this in my linux distro(fedora22):

Output of `sudo usermod -aG docker your_username`:

        ```usermod: group 'docker' does not exist```

**Comment by thaJeztah** [comment]
Wondering; how did you install docker; did you use the `yum.dockerproject.org` repository, or the Red Hat / Fedora packages? The RPM should create this group during installation; https://github.com/docker/docker/blob/57025bd58821a6972185fb4c0a5559289d769ef6/hack/make/.build-rpm/docker-engine.spec#L203

**Comment by trishnaguha** [comment]
I installed docker with dnf.
 `sudo dnf install docker-engine`

**Comment by thaJeztah** [comment]
@jfrazelle perhaps you have an idea; did I interpret the RPM spec incorrectly?

**Comment by jfrazelle** [comment]
You could try creating the group yourself maybe that binary is missing

**Comment by trishnaguha** [comment]
Yes I did that. So I think I can close #21032 :).
Thanks @thaJeztah and @jfrazelle

**Comment by TCarmine** [comment]
This happened randomly to yet another Virtual Machine with Ubuntu 22.04.05 but I had before created others and did not get that.
