### ISSUE TITLE
Cannot set dm.basesize until docker has been started

### ISSUE THREAD

**Issue by masonoise** [docker/docker#21037]
When using terraform to bring up a new EC2 instance with Docker, I wanted to modify the dm.basesize option before starting Docker. To do this, my script adds a line to the /etc/sysconfig/docker-storage file:

    DOCKER_STORAGE_OPTIONS= --storage-opt dm.basesize=50G

However, when it then tries to start Docker with `systemctl start docker.service` I was getting an error:

    Error starting daemon: error initializing graphdriver: Unknown option dm.basesize

I had used this same line before, but realized that it was after Docker had been started at least once on the server. So then I changed things to:

1. systemctl start docker.service
2. Add the line to /etc/sysconfigdocker-storage
3. systemctl restart docker.service

This works fine. Maybe Docker needs to be started at least once on the server in order to initialize the storage subsystem somehow? Before that's done, it doesn't recognize the storage option. This is sort of crazy, so is there a proper fix/workaround?

Output of `docker version`:

```
Docker version 1.7.1, build 446ad9b/1.7.1
```

This is on AWS EC2, running `CentOS Linux release 7.1.1503 (Core)`.

**Comment by ghodgkinson** [comment]
I had the same issue.
After modifying my storage options to increase docker container size from 10G (to 20G) my docker daemon would not start. To be specific, it said it started OK, but the daemon was not running and I found the same error you mentioned in my log file.
I then started docker using **docker -d &** from the command line, then killed this process, and from that point I can now successfully start my docker using **service docker start**.
HOWEVER...
My containers are still limited to 10G in size.

**Comment by thaJeztah** [comment]
@masonoise it looks like you're running a Red Hat supported build of Docker, not the version of docker from this repository; https://github.com/rhatdan/docker/commit/446ad9b. Can you ask this question in the Red Hat / CentOS issue tracker? https://bugzilla.redhat.com

Our packages don't use the `DOCKER_STORAGE_OPTION` environment variable, so unfortunately we cannot help out here.
