### ISSUE TITLE
docker daemon: we need a way to specify the default network somehow

### ISSUE THREAD

**Issue by dreamcat4** [docker/docker#21039]
Hi!
Am very excited and pleased about new docker networking features, as introduced in version 1.10.x. However something is missing:

For every new container I create, if no `--net` flag was specified, the container's network defaults to the default `docker0` bridge network. Or legacy docker0 / no network / whatever.

What would be more helpful than that is if user can specify their own custom docker network to be the default option when `--net` was not specified. To save having to put the same `--net my_custom_docker_network` flags in each time over for every container.

Now I did have a go today on docker v1.10.2 / ubuntu wily 15.10. But no luck :(

a) There has always been a legacy startup flag `docker daemon --bridge br-my-docker-bridge`. To specify some other bridge interface instead of `docker0`. However that doesnt seem to be aware of the new docker networks or set any kind of default internal `--net` flag inside the go code. What happens is that docker will startup allright, but then omiting the `--net` flag from docker run results in some error:

```sh
docker: Error response from daemon: User specified IP address is supported on user defined networks only
```

b) Alternatively there is also some bridge driver flag named `com.docker.network.bridge.default_bridge`. Which is visible on the docker0 `bridge` network. You can see it by running the `docker network inspect bridge`. However creating a new network with that flag doesnt work either. And results in some other error message. So I am stumped as things currently stand.

If theres not a way to do it yet, then I guess this would be a new feature request!

**Comment by cpuguy83** [comment]
This was intentionallity left out (and actually removed from the implementation in experimental).
I'll let @mavenugo explain.

**Comment by wenchma** [comment]
@dreamcat4  can you startup `docker daemon` with specifying the docker custom network ?

**Comment by mavenugo** [comment]
as @cpuguy83 commented, we infact had that feature during the experimental version and we later removed that mainly due to UX concerns. For example, if we decide to provide a custom network as a default network and if that network is backed by a multi-host network driver, should we make it a cluster-wide configuration or is it per-daemon ? If it is a cluster-wide configuration, it must be done at swarm level. If it is a per-daemon configuration, then how would we determine the correct one when each of the daemons have different default-networks ? and so forth...
Also, for backward compatibility reasons the default network for a container has always been docker0 bridge. Some of the features aren't compatible between user-defined networks and docker0 bridge. By introducing a default custom network, it might change some of the application assumptions on some of the features (originally assumed for docker0 bridge).
We didn't see a good justification for introducing a feature that causes more confusion and compatibility issues.

**Comment by dreamcat4** [comment]
> it might change some of the application assumptions on some of the features (originally assumed for docker0 bridge).

Hmm interesting. My assumption was that those touched features will not really be missed by those who are determined to override the network configuration. Because (like me) they never used `docker0` to begin with anyway. Since a lot of those prior legacy features are inferior to the new libnetwork solutions / alternatives.

But yes: Ineed if someone was needing to use one of those features from time-to time they would then need to manually override the selected docker network with a `--net bridge` flag. Which perhaps is not present / of exposed for some of the auxillary cmds that would call for it. For example if only `docker run` that has the `--net` flag, and that needed flag is not present on other sucommands (or no way to be able to tell it).

> If it is a cluster-wide configuration, it must be done at swarm level. If it is a per-daemon configuration, then how would we determine the correct one when each of the daemons have different default-networks ?

Well could the docker daemon ever get to a point where it can startup, and run perfectly without assuming any such default network, or default docker0 bridge? I get the impression that would be the 'ideal' long-term solution to all these things. Anyhow nevermind now:

It merely proves to us that the level of rework is more than can be justified to fulfil a single issue alone (in isolation). I now appreciate and understand why this particular feature has been recently dropped / deemed not clean enough / potential to break other bits of docker. So thank you for the commentary @mavenugo. It must be tricky... figuring out the best path for replacing legacy code / features while people still continue to use those features and depend upon them.

Please close this issue if no-one has nothing else to say / nobody wants to have it back.

**Comment by thaJeztah** [comment]
> It must be tricky... figuring out the best path for replacing legacy code / features while people still continue to use those features and depend upon them.

It is! With every change we need to consider that one users' enhancement, is another users' breaking change. I might have suggested adding a `--default-network` option myself at some point (hey! It seemed handy), forgetting the implications that Madhu mentioned above.

I'll close this issue, but thanks for suggesting!

Perhaps, if you start a lot of containers by hand, a simple Bash function / alias could be a solution? Adding a default `--net=xyz` option to each `docker run` or `docker create` command should probably be easy to write.

**Comment by cpuguy83** [comment]
As a side note, allowing to set the default network daemon-wide breaks consistency between daemons.

**Comment by dreamcat4** [comment]
> Perhaps, if you start a lot of containers by hand, a simple Bash function / alias could be a solution?

@thaJeztah Thanks for the suggestion. Ah if only was using bash then indeed I would be very happy to solve it that way.

However I am using the [Crane](https://github.com/michaelsauter/crane) orchestration tool. Sadly it does not support a single central declaration of default options flags. As the project has decided to make do purely with YAML's standard << * templating constructs. And unfortunately those are very user-friendly. So I just can't seem to figure out / understand how to use them for this.

**Comment by thaJeztah** [comment]
@dreamcat4 I know Docker Compose automatically creates a per-app custom network, when using the 2.0 docker-compose.yml format; https://docs.docker.com/compose/compose-file/#versioning. Perhaps open a feature request at Crane to do the same

(Or switch to using Docker Compose :innocent: )
