### ISSUE TITLE
v1.10 not clearing links to removed containers

### ISSUE THREAD

**Issue by finneganh** [docker/docker#21049]
Output of `docker version`:

Docker version 1.10.1, build 9e83765

Output of `docker info`:

Containers: 23
 Running: 10
 Paused: 0
 Stopped: 13
Images: 201
Server Version: 1.10.1
Storage Driver: aufs
 Root Dir: /mnt/docker/aufs
 Backing Filesystem: extfs
 Dirs: 471
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 3.13.0-79-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.305 GiB
ID: 4THR:HNFP:2UH6:PJOB:5VEB:LJTM:TJBM:XQRP:6UKD:H7HG:TFQ6:TVLU
WARNING: No swap limit support
Provide additional environment details (AWS, VirtualBox, physical, etc.):

List the steps to reproduce the issue:
1. docker run --name container-a -it -d ubuntu:14.04 bash
2. docker run --name container-b --link container-a:container-a -it -d ubuntu:14.04 bash
3. docker rm -fv container-a
3. docker inspect container-b

Describe the results you received:

The `HostConfig` contains:

```
            "Links": [
                "/container-a:/container-b/container-a"
            ],
```

Describe the results you expected:

With Docker 1.8.1, the "Links" became `null`.

Provide additional info you think is important:

Previous versions removed Links entries to containers that no longer existed. Galley used this information to know if it needed to recreate a container in order to reestablish links.

Now, there's no way to tell from inspecting a container whether it will start up because the Links are all returned, even if they are to removed containers. Since they're presented as name aliases rather than IDs, you can't check for their existence, because same-named containers might be present (but are different from the previously linked containers).

Is there some way to either return the old behavior or somehow make it introspectable which _specific_ container is being linked to (by ID)? That way tools could judge whether a container can be started or whether it needs to be recreated to regenerate the links.

**Comment by cpuguy83** [comment]
Wouldn't this be racey behavior anyway?
Also note that you can't re-create a container and have the links work. Links only work against a single container ID, not a container's name.

**Comment by phopkins** [comment]
You're right, the goal is not to recreate the linked-to container to re-establish the link. The goal is to know that the linking container needs to be recreated to link to a new version of the linked-to container.

The use case is container B depends on container A. Container A gets recreated (its image changes or something like that) so the tooling needs to know to recreate container B to point to the new A. This used to be possible because Galley could see that container B no longer had a link to a container A. Now the links describe a link to a "container A" that is not necessarily the container that currently has that name.

**Comment by phopkins** [comment]
And unfortunately it seems that creating a link via ID (e.g. `docker run --name container-b --link 7019dc06d07bd23b4155547ec768b6472f39a3cf31ebb663ca8dc25076b4257a:container-a -it -d ubuntu:14.04 bash`) doesn't preserve that ID in inspect’s `Links`. Docker replaces it with that container's current name.

(Otherwise, a workaround would be to use an ID that could then be checked for existence later.)

**Comment by thaJeztah** [comment]
I noticed this recently as well;

Docker 1.9.1:

    docker run -d --name api nginx
    docker run -d --name web --link api:myapi nginx

    docker inspect --format '{{ .HostConfig.Links }}' web
    [/api:/web/myapi]


    docker stop api && docker rm api

    docker inspect --format '{{ .HostConfig.Links }}' web
    []



Docker 1.10.3 and 1.11.0:

    docker run -d --name api nginx
    docker run -d --name web --link api:myapi nginx

    docker inspect --format '{{ .HostConfig.Links }}' web
    [/api:/web/myapi]

    docker stop api && docker rm api

    docker inspect --format '{{ .HostConfig.Links }}' web
    [/api:/web/myapi]


However, looking at the discussion above, I agree and not sure if it's worth changing this back to the old behavior, given that "classic" links cannot be re-attached after they're disconnected.

The new (DNS based) discovery for custom networks *does* allow doing so, so may be the best way forward.

**Comment by thaJeztah** [comment]
ping @mavenugo do you think it would be worth changing, or should we close this issue?

**Comment by finneganh** [comment]
I'm interested in a mechanism that would let me inspect a not-running
container and see if it would refuse to start due to missing links.
Currently checking just by linked container name doesn't work, since the
current container with that name might not be the one originally linked to.
Providing the original ids of the linked containers would, since I could
look up those to see if they're running.

**Comment by thaJeztah** [comment]
I don't think we'll change that, as "classic" linking is being deprecated in favor of DNS-based discovery / linking. If you use a custom network, checking if the linked container (with that name) exists, and is running would work. I don't see us adding the ID of the originally linked container to the API output.

**Comment by LK4D4** [comment]
I think we can close this as links are "deprecated".
