### ISSUE TITLE
Dockerfile parser should handle strings properly

### ISSUE THREAD

**Issue by SvenDowideit** [docker/docker#2105]
I was trying something out too quickly, and put

   WORKDIR "/mnt"

and docker build says:

   Step 6 : WORKDIR "/mnt"

into my Dockerfile

turns out that sets $pwd to /"/mnt", which doesn't exist.

doing the right thing

   WORKDIR /mnt

works and docker build outputs the desired:

   Step 6 : WORKDIR /mnt

so - can docker tell me that my WORKDIR is possibly rubbish, or perhaps stripping the " makes sense?

Sven

**Comment by TylerMills** [comment]
+1

**Comment by duglin** [comment]
FYI https://github.com/docker/docker/pull/10431 will fix this for any Dockerfile cmd that allows env vars in them.  So "$foo" will have the quotes removed and $foo replaced, while '$foo" will remove the quotes but use $foo as-is.

**Comment by duglin** [comment]
```
FROM ubuntu
WORKDIR "/$foo"
RUN pwd
WORKDIR '/$foo'
RUN pwd
```
shows / and then /$foo as the 'pwd'

**Comment by calavera** [comment]
@duglin can we close this issue now that 1.6 has shipped and #10431 was merged in?

**Comment by duglin** [comment]
@calavera I think so but perhaps @SvenDowideit is in a better position to say for sure.

**Comment by duglin** [comment]
I just tried this:
```
FROM ubuntu
RUN mkdir "/tmp tmp"
WORKDIR "/tmp tmp"
RUN pwd
```
and it worked as expected so I'm going to close this.
However, this doesn't guarantee that all Dockerfile commands deal with quotes properly but we can open additional issues as people run into problems because I suspect we may need to deal with each one independently.
