### ISSUE TITLE
Detect container crashes regardless of restart policy

### ISSUE THREAD

**Issue by domdom82** [docker/docker#21057]
__This is not a bug report, rather a feature request.__

During daily operations we encounter crashing containers from time to time.

Thanks to `--restart=always` those come back up again immediately.

However if a bug in the code let the container crash I still want to be able to dump traces (ideally the entire crashed container) and maybe open an incident automatically. 

`--restart=always` bites you here because it prevents you from pulling stacktraces.

So I am asking: Is there a way to detect a crashed container and execute some code _before_ the container gets restarted? I am thinking along the lines of consul registrator: a container that detects if other containers get started and executes logic accordingly.

Thanks for your input.

**Comment by thaJeztah** [comment]
Haven't tried for "exiting", but have you looked at `docker events`? https://docs.docker.com/engine/reference/commandline/events/ (Also available through the API; https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#monitor-docker-s-events)

**Comment by domdom82** [comment]
Good point. Maybe a "die" event without "kill" (i.e. deliberate stop of the container) could be interpreted as "crash".

The question that remains: If I subscribe to that event and maybe pipe that into a

`docker export <crashed container id> > /tmp/<crashed container id>.tar`

Would it work if the container gets restarted by docker immediately due to restart policy?

**Comment by thaJeztah** [comment]
Docker export won't work, because that exports an *image*, not a container. `docker logs` may give you some information as to why the container crashed, and docker 1.11 will allow you to change the restart policy of an existing container (see https://github.com/docker/docker/pull/19116), so that you can tell it to no longer try to restart

**Comment by domdom82** [comment]
https://docs.docker.com/engine/reference/commandline/export/

the readme claims `docker export` exports the filesystem of a container, so I assumed that should work. I tried it and it works even on stopped containers. So I suppose it would work on crashed ones, too.

`docker save` should save images I think.

Anyway thanks for the input I shall play around with events for a bit.

**Comment by thaJeztah** [comment]
Doh! I keep mixing those up, my bad, haha

**Comment by thaJeztah** [comment]
Let me close this issue, but interested to hear how things work out for you
