### ISSUE TITLE
Cross-Repository mounting causes 401 on Push if same client used by multiple users

### ISSUE THREAD

**Issue by bainsy88** [docker/docker#21059]
**Output of `docker version`:**

Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64

Output of `docker info`:

Containers: 24
 Running: 0
 Paused: 0
 Stopped: 24
Images: 401
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 482
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-49-generic
Operating System: Ubuntu 14.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 6.244 GiB
Name: vagrant-ubuntu-trusty-64
ID: MQOF:SAL6:NEQ2:7ILG:MLCV:7JAW:ISAE:LS5L:AGPH:E34R:3TNB:GGJP
WARNING: No swap limit support

**Provide additional environment details (AWS, VirtualBox, physical, etc.):**

Physical box talking to a registry 2.3

**List the steps to reproduce the issue:**

1. 'docker login' to the registry as User1 and push registryurl.com/user1/image1
2. Re-tag image registryurl.com/user2/image1
3. 'docker login' to the same registry as User2 and attempt to Push registryurl.com/user2/image1

**Describe the results you received:**

The second push fails with 401 Unauthorized. This is due to the layer mounting implemented at 1.10. 

"The push refers to a repository [registryurl.com/user2/image1]
5f70bf18a086: Preparing 
ddef881aeaff: Preparing 
unauthorized: Unauthorized"

As the client knows it previously pushed the layers during the push of the image registryurl.com/user1/image1 it will try and mount the layers rather than re-pushing the layer data. This will fail as User2 does not have read access to the resources of User1

**Describe the results you expected:**

I would expect the client to fall back to re-pushing the layer data if the intial attempt to mount failed.

In the original spec in https://github.com/docker/distribution/issues/908

It states the following which does not appear to be the case: 

"In the event of a failure or inability to perform a cross repository push, the system should fallback to the traditional upload scheme."

**Provide additional info you think is important:**

An example of the access records that get passed through to be auth'd in this scenario is:

 [{{repository user2/image1} pull} {{repository user2/image1} push} {{repository user1/image1} pull}]

The 401 is because user2 is not auth'd to pull repository user1/image1

**Comment by jhart1685** [comment]
Hello - has anyone had a chance to look at this yet? It clearly looks like a bug in the Docker client, with cross-repo mounts not falling back to traditional pushes as documented. This is impacting our users right now as they upgrade to the latest client and push to our (2.3) private registry.

**Comment by cpuguy83** [comment]
ping @aaronlehmann

**Comment by aaronlehmann** [comment]
@bainsy88: Thanks for the report. This does look like a bug in Docker 1.10.x.

I had a look at the current code on master, and it looks like this would have been fixed as part of https://github.com/docker/docker/pull/20580. Could you please a build of Docker from the `master` branch and see if it solves the problem?

**Comment by bainsy88** [comment]
@aaronlehmann Thanks for the response. Just tried what you suggested and can confirm I do not see the issue with a Docker built from master, so looks to be fixed upstream as suspected

**Comment by thaJeztah** [comment]
Thanks for testing @bainsy88, let me close this issue then; but feel free to continue the discussion after I closed
