### ISSUE TITLE
--volumes-from cannot use on some container

### ISSUE THREAD

**Issue by S-YOU** [docker/docker#21052]
Output of `docker version`:

```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:22:53 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:22:53 2016
 OS/Arch:      linux/amd64

```

Output of `docker info`:

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 47
Server Version: 1.10.2
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.4.3-040403-generic
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.716 GiB
Name: dev2
ID: VANS:NNTS:5USD:GUK6:63R4:ZRH7:HKGK:OJBE:KZUU:RWTP:Y5X5:244N
WARNING: No swap limit support

```

Provide additional environment details (AWS, VirtualBox, physical, etc.):
Physical

List the steps to reproduce the issue:
1. docker create -v /var/lib/mysql --name data1 tianon/true
2. docker run -it --rm --volumes-from data1 --entrypoint=bash debian:jessie
3. df

Describe the results you received:
```
Filesystem     1K-blocks     Used Available Use% Mounted on
overlay         28794872 21364668   5944432  79% /
tmpfs            2996916        0   2996916   0% /dev
tmpfs            2996916        0   2996916   0% /sys/fs/cgroup
/dev/sda6       28794872 21364668   5944432  79% /etc/hosts
shm                65536        0     65536   0% /dev/shm
```

Describe the results you expected:
```
Filesystem     1K-blocks     Used Available Use% Mounted on
overlay         28794872 21364668   5944432  79% /
tmpfs            2996916        0   2996916   0% /dev
tmpfs            2996916        0   2996916   0% /sys/fs/cgroup
/dev/sda6       28794872 21364668   5944432  79% /etc/hosts
shm                65536        0     65536   0% /dev/shm
...
/dev/sda6       ... ....   ...  ..% /var/lib/mysql
```

Provide additional info you think is important:
- May be container issue, but I am seeing that **debian:wheezy** can mount --volumes-from, but **debian:jessie** cannot mount it.
- Or may be something went broken on this machine

May be not directly related to docker itself, but any Idea why?

**Comment by mlaventure** [comment]
It may be an issue with the `df` tool (jessie has version 8.23, wheezy has version 8.13). If you look at the content of `/proc/mounts` or `/proc/self/mountinfo` you will see that the volume is correctly mounted.

Also, adding a file within `/var/lib/mysql` once inside a container will correctly be reflected within the volume on my test setup.

**Comment by mlaventure** [comment]
I'm closing this for now. If the volume is indeed not mounted for you, please feel free to re-open it with your findings.

**Comment by S-YOU** [comment]
Thanks for the explanations. Didn't ever realize that df has issues. 
I can confirm that it correctly reflected too. 
Sorry for not confirming details, but just by looking at df output.

**Comment by thaJeztah** [comment]
Yes, I recently saw another issue that also acted different, depending on what you were running inside the container, see https://github.com/docker/docker/issues/20322#issuecomment-184362622, I think I've seen similar things with running `mount` inside a container as well (not all mounts showing up, but they're actually there)

**Comment by S-YOU** [comment]
Thanks for information @thaJeztah. Good to know that.
