### ISSUE TITLE
Add error messaging for the --detach-keys flag

### ISSUE THREAD

**Issue by moxiegirl** [docker/docker#21064]
Reported by @jpetazzo

If I pass an invalid sequence it just accepts it without showing an error (and silently reverts to `^P^Q`) also, I don't think that `[a-Z]` is a valid glob entry

**Comment by mlaventure** [comment]
Note: the warning is actually shown in the daemon log.

**Comment by moxiegirl** [comment]
@mlaventure That's good to know. Does your response mean you think a CLI message is unnecessary?

**Comment by mlaventure** [comment]
I think it would be good to have it on the CLI side. I don't think many people would have the reflex to look at the daemon log, and they will just wonder why is their detach combination is not work.

I just wanted to point that we actually were reporting it somewhere :)

**Comment by moxiegirl** [comment]
Ah, cool. I was hoping you'd say that.  IDK if we have anything where we state our policy for adding these things like --- need a cli error and a log; I think having both are the ideal.

**Comment by WeiZhang555** [comment]
:+1: 
Client should report an error instead of swallow it, I want to pick up this if no one is working on this.

#dibs
