### ISSUE TITLE
docker-compose skipping first step

### ISSUE THREAD

**Issue by justechn** [docker/docker#21065]
I have a docker compose file

    version: '2'
    
    services:
        base:
            build: ./base
        api:
            build: ./api
            ports:
                - "3000:3000"
        mysql:
            build: ./mysql
            ports:
                - "3306:3306"
            environment:
                - MYSQL_ROOT_PASSWORD=d3v3nv
                - MYSQL_DATABASE=dialer_list_definitions

when I run docker-compose up, or docker-compose build I get this error

    $ docker-compose build
    Building api
    Step 1 : FROM dialerlistdefinitions_base
    Pulling repository docker.io/library/dialerlistdefinitions_base
    ←[31mERROR←[0m: Service 'api' failed to build: Error: image library/dialerlistdefinitions_base not found

it looks like it is skipping the base, and jumping directly to building the api.

Here is my base dockerfile

    # Pull base image.
    FROM ubuntu:16.04
    # Install the software needed for all other containers
    RUN \
      sed -i 's/# \(.*multiverse$\)/\1/g' /etc/apt/sources.list && \
      apt-get update && \
      apt-get -y upgrade && \
      apt-get install -y build-essential software-properties-common curl git man unzip vim wget tofrodos && \
      rm -rf /var/lib/apt/lists/*
    # Set environment variables.
    ENV HOME /root
    # Define working directory.
    WORKDIR /root
    # Define default command.
    CMD ["bash"]

here is my api dockerfile

    FROM dialerlistdefinitions_base
    
    # Update package list
    RUN apt-get update
    
    # Install Node.js and npm
    RUN apt-get install -y nodejs
    RUN apt-get install -y npm
    
    # Install supervisor
    RUN apt-get install -y supervisor
    
    # create node symlink
    RUN ln -s `which nodejs` /usr/bin/node
    
    # Install app dependencies
    COPY package.json /src/package.json
    RUN cd /src; npm install
    
    # Bundle app source
    COPY . /src
    RUN cd /src/config; cp config.sample.json config.json
    
    # Move supervisor config to correct dir
    RUN mkdir -p /var/log/dialerlist
    RUN mv /src/config/supervisor.dialerlist.conf /etc/supervisor/conf.d/supervisor.dialerlist.conf
    
    CMD ["/usr/bin/supervisord"]

I have cleared out all existing containers, and images to make sure nothing was conflicting.

Also I am running on windows 7 with docker version 1.10.1, build 9e83765

**Comment by justechn** [comment]
if I remove all the other service from the docker-compose.yml except for base then it builds. I am then able to add all the other services back and they finally build together. However if I remove all the containers and images and try building again I get the same error.

**Comment by HackToday** [comment]
observed two issue
1, does docker support 16.04 ?
Since I noticed your dockerfile include `16.04`

2. also what's `dialerlistdefinitions_base` ? is it pushed by yourself to github ?  Or local image ?

**Comment by justechn** [comment]
> 1. does docker support 16.04 ?
Since I noticed your dockerfile include `16.04`

You tell me https://hub.docker.com/_/ubuntu/

> 2. also what's `dialerlistdefinitions_base` ? is it pushed by yourself to github ?  Or local image ?
if you look at the docker-compose file I posted above you will see that I have a service called base. When that service is built it is called dialerlistdefinitions_base.

**Comment by justechn** [comment]
ok, here is something strange. If I rename 'base' to 'blah' it builds. Is base a reserved word?

**Comment by justechn** [comment]
Nevermind, I figured it out. It seems that docker-compose does not build the services in any specific order, unless you specify a depends_on. After putting that in everything build correctly.

Thanks for all your support and help, it was very useful (eyeroll)
