### ISSUE TITLE
Is it possible to run command on running container with docker remote api

### ISSUE THREAD

**Issue by RGFnaGFuIEd1bmF5** [docker/docker#21061]
I'm using stilliard/pure-ftpd. I would like to open ftp users with remote api. I couldn't find any example about this on remote api documentation.

Output of `docker version`:

```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.2.1
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
```

Output of `docker info`:

```
Containers: 1
Images: 19
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 21
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-79-generic
Operating System: Ubuntu 14.04.4 LTS
CPUs: 1
Total Memory: 490 MiB
Name: ubuntu-512mb-fra1-01
ID: ESQR:OTJT:T3KB:EE77:CZLO:PUVR:ZR7N:6J66:3OLN:YHSU:ZAMC:LALR
```

**Comment by mlaventure** [comment]
I am not sure I understand what you mean by "open ftp users", but you can use the `exec` endpoint to run extra commands in a running container, see [here](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#exec-create)

**Comment by mlaventure** [comment]
Also, the IRC channel #docker on freenode is probably the best place for this kind of question since it's not really an issue or a feature request :)

See [here](https://docs.docker.com/opensource/get-help/#irc-quickstart) for a quick intro to IRC if needed.

**Comment by RGFnaGFuIEd1bmF5** [comment]
Thank you.
