### ISSUE TITLE
Dockerfile ENV instruction does not use previously defined env variables on the same line in construction

### ISSUE THREAD

**Issue by sheldonkwok** [docker/docker#21072]
Output of `docker version`:

Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

Output of `docker info`:

Containers: 10
Images: 616
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 636
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: local
ID: X6MF:HEPM:OQIR:LVKQ:K6OF:EKSC:ETPW:DQPI:7PVO:OJIB:LVVC:W25X
Debug mode (server): true
 File Descriptors: 17
 Goroutines: 29
 System Time: 2016-03-09T19:34:16.033513707Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: ssiadmin
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox

Provide additional environment details (AWS, VirtualBox, physical, etc.):
I'm using Docker Machine with default settings. 

List the steps to reproduce the issue:
1. Create some environment variables that use each other. Example:
ENV FOO="hello"
ENV BAR="world"
ENV FOOBAR="$FOO$BAR"
This works as intended.
2. Squash environment variables into a single ENV instruction.
FOO="hello" BAR="world" FOOBAR="$FOO$BAR"
3. Observe that FOOBAR is an empty because it can't find $FOO and $BAR.

Describe the results you received:
The ENV instruction does not let you create environment variables from other environment variables defined on the same line.

Describe the results you expected:
It should let me create environment variables from previously defined ones on the same instruction line.

Provide additional info you think is important:

**Comment by duglin** [comment]
We did this on purpose because we wanted to align with how `export` worked.
See: https://github.com/docker/docker/pull/10431#issuecomment-77898658 and the following discussions
