### ISSUE TITLE
gpgkeys: key 58118E89F3A912897C070ADBF76221572C52609D not found on keyserver

### ISSUE THREAD

**Issue by austinzh** [docker/docker#21079]
sudo apt-key adv --keyserver hkp://pgp.mit.edu:80  --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --secret-keyring /tmp/tmp.YidMDIRB28 --trustdb-name /etc/apt/trustdb.gpg --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg  --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
gpg: requesting key 2C52609D from hkp server pgp.mit.edu
gpgkeys: key 58118E89F3A912897C070ADBF76221572C52609D not found on keyserver
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0

**Comment by HackToday** [comment]
Not sure if you install docker in ubuntu or not, I found it included in

sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

Not same keyserver as yours given

**Comment by HackToday** [comment]
I checked doc here, I thought you use ubuntu here, please correct me if not,

```
https://docs.docker.com/engine/installation/linux/ubuntulinux/
```

**Comment by thaJeztah** [comment]
I think this must have been a temporary hiccup with that keyserver, or an issue with your network connection. I'm unable to reproduce this, both with the MIT and the sks-keyservers;

```
root@foobar:~# sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.fpbO8lo2i9 --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/fish-shell-release-2.gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
gpg: requesting key 2C52609D from hkp server p80.pool.sks-keyservers.net
gpg: key 2C52609D: "Docker Release Tool (releasedocker) <docker@docker.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
root@foobar:~# sudo apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.RhqSLGBW8f --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/fish-shell-release-2.gpg --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
gpg: requesting key 2C52609D from hkp server pgp.mit.edu
gpg: key 2C52609D: "Docker Release Tool (releasedocker) <docker@docker.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
root@foobar:~#
