### ISSUE TITLE
1.10.2: keeps pushing same layers to the hub

### ISSUE THREAD

**Issue by dgageot** [docker/docker#21085]
I'm pushing two images to the hub. Both images share some layers.
 + If I push the first image twice, no layer is pushed the second time. This is expected.
 + If I push the second image, the shared layers are pushed again. This is expected.
 + If I push the first image again, some shared layers are pushed again. This I didn't expect!

```
docker pull busybox
docker tag busybox:latest dgageot/busybox
docker tag busybox:latest dgageot/busybox2

docker push dgageot/busybox
The push refers to a repository [docker.io/dgageot/busybox]
5f70bf18a086: Pushed
16a7ebd37800: Pushed

docker push dgageot/busybox
The push refers to a repository [docker.io/dgageot/busybox]
5f70bf18a086: Layer already exists
16a7ebd37800: Layer already exists

docker push dgageot/busybox2
The push refers to a repository [docker.io/dgageot/busybox2]
5f70bf18a086: Pushed
16a7ebd37800: Pushed

docker push dgageot/busybox
The push refers to a repository [docker.io/dgageot/busybox]
5f70bf18a086: Layer already exists
16a7ebd37800: pushed
```

**Comment by thaJeztah** [comment]
@dgageot I think this may be a duplicate of https://github.com/docker/docker/issues/18866, and may be due to Docker Hub not yet being on registry 2.3 (see https://github.com/docker/docker/issues/18866#issuecomment-192768001). Can you reproduce this if you're pushing to a private 2.3 registry?

**Comment by dgageot** [comment]
Yes it's a duplicate. Thanks @thaJeztah
