### ISSUE TITLE
What is Docker container exit code 137?

### ISSUE THREAD

**Issue by 1605200517** [docker/docker#21083]
Is there an official exit code list?

![image](https://cloud.githubusercontent.com/assets/1834666/13665170/560c7e46-e6ab-11e5-8589-b883fa2ea821.png)

**Comment by HackToday** [comment]
I think it is linux standard, check here

http://tldp.org/LDP/abs/html/exitcodes.html

if it is your needs?

**Comment by cpuguy83** [comment]
The exit code is not from Docker, it is from the process in the container.

**Comment by cjellick** [comment]
Commenting because this shows up in google searches.
You'll see this exit code when you do a docker stop and the initial graceful stop fails and docker has to do a sigkill. Per @HackToday's comment/link it is a standard: 128 + 9 = 137 (9 coming from SIGKILL).

**Comment by chiraglakhani69** [comment]
To takel, you might want to try changing memory allocation in Docker > Preference > Memory. Probably increase will work.

**Comment by j3pic** [comment]
Also commenting because I ended up here from Google. If you're getting this error from Docker 4 Mac, it's likely because the Linux OOM killer is getting triggered. Allocating more RAM to Docker solves it.

**Comment by monowai** [comment]
I came across this page when ElasticSearch failed to start. I was trying to keep it's memory low so had configured `mem_limit=384m` and it was terminating with this error code.  Setting the limit to 512m fixed it. So perhaps the issue is memory related.

**Comment by thaJeztah** [comment]
The exit status is documented in https://docs.docker.com/engine/reference/run/#exit-status (source: https://github.com/docker/cli/blob/master/docs/reference/run.md#exit-status), but may need some additional explanation; if someone is interested in opening a pull request, that would be welcome

**Comment by svetob** [comment]
Repeating what's said above, this happens on OSX because of Docker 4 Mac's hard memory cap. You can increase your memory limit in Docker App > Preferences > Advanced.

**Comment by hrshakshit** [comment]
You can also try increasing the disc image size, Docker > Preference > Memory

**Comment by Zima04** [comment]
I think the problem can be solve by this https://bobcares.com/blog/error-137-docker

**Comment by imnishant** [comment]
The solution that worked for me: In “Docker -> Preferences-> Advanced” I have increased the Memory from 2 to 3 and it fixed the Error 137. If it doesn't work, then try increasing Swap also.
