### ISSUE TITLE
Docker Daemon in Network Namespace

### ISSUE THREAD

**Issue by HamidEDD** [docker/docker#21090]
Output of `docker version`:

```
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:16:19 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:16:19 2016
 OS/Arch:      linux/amd64

```

Output of `docker info`:

```
docker info
Containers: 10
 Running: 8
 Paused: 0
 Stopped: 2
Images: 16
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 110
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1000 MiB

```

Provide additional environment details (AWS, VirtualBox, physical, etc.):

List the steps to reproduce the issue:
1. ip netns add test
2. ip netns exec test bash
3. docker daemon -D -H unix:///var/run/docker.sock -H tcp://0.0.0.0:2376 --debug=true --dns 8.8.8.8 --dns 8.8.4.4 --userland-proxy=true --userns-remap default

DEBU[0000] docker group found. gid: 999                 
DEBU[0000] Server created for HTTP on unix (/var/run/docker.sock) 
WARN[0000] /!\ DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING /!\ 
DEBU[0000] Server created for HTTP on tcp (0.0.0.0:2376) 
INFO[0000] User namespaces: ID ranges will be mapped to subuid/subgid ranges of: dockremap:dockremap 
DEBU[0000] Creating user namespaced daemon root: /var/lib/docker/755360.755360 
DEBU[0000] Using default logging driver json-file       
DEBU[0000] Using graph driver aufs                      
INFO[0000] Graph migration to content-addressability took 0.00 seconds 
DEBU[0000] Option DefaultDriver: bridge                 
DEBU[0000] Option DefaultNetwork: bridge                
WARN[0000] Running modprobe bridge br_netfilter failed with message: modprobe: WARNING: Module br_netfilter not found.
, error: exit status 1 
INFO[0000] Firewalld running: false                     
DEBU[0000] /sbin/iptables, [--wait -t nat -D PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t nat -D PREROUTING] 
DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT]    
DEBU[0000] /sbin/iptables, [--wait -t nat -F DOCKER]    
DEBU[0000] /sbin/iptables, [--wait -t nat -X DOCKER]    
DEBU[0000] /sbin/iptables, [--wait -t filter -F DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t filter -X DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t filter -F DOCKER-ISOLATION] 
DEBU[0000] /sbin/iptables, [--wait -t filter -X DOCKER-ISOLATION] 
DEBU[0000] /sbin/iptables, [--wait -t nat -n -L DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t nat -N DOCKER]    
DEBU[0000] /sbin/iptables, [--wait -t filter -n -L DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t filter -n -L DOCKER-ISOLATION] 
DEBU[0000] /sbin/iptables, [--wait -t filter -C DOCKER-ISOLATION -j RETURN] 
DEBU[0000] /sbin/iptables, [--wait -I DOCKER-ISOLATION -j RETURN] 
DEBU[0000] Registering ipam driver: "default"           
INFO[0000] Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address 
DEBU[0000] Allocating IPv4 pools for network bridge (ff3f762848052f9cf60d3e376d539d34a925b9c91c0621834baee2e8844fbf84) 
DEBU[0000] RequestPool(LocalDefault, 172.17.0.0/16, , map[], false) 
DEBU[0000] RequestAddress(LocalDefault/172.17.0.0/16, 172.17.0.1, map[RequestAddressType:com.docker.network.gateway]) 
DEBU[0000] /sbin/iptables, [--wait -t nat -C POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE] 
DEBU[0000] /sbin/iptables, [--wait -t nat -C DOCKER -i docker0 -j RETURN] 
DEBU[0000] /sbin/iptables, [--wait -t nat -I DOCKER -i docker0 -j RETURN] 
DEBU[0000] /sbin/iptables, [--wait -D FORWARD -i docker0 -o docker0 -j DROP] 
DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -i docker0 -o docker0 -j ACCEPT] 
DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -i docker0 ! -o docker0 -j ACCEPT] 
DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT] 
DEBU[0000] /sbin/iptables, [--wait -t nat -C PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8] 
DEBU[0000] /sbin/iptables, [--wait -t nat -A OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8] 
DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -j DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -j DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -j DOCKER-ISOLATION] 
DEBU[0000] /sbin/iptables, [--wait -D FORWARD -j DOCKER-ISOLATION] 
DEBU[0000] /sbin/iptables, [--wait -I FORWARD -j DOCKER-ISOLATION] 
WARN[0000] Your kernel does not support cgroup memory limit: mountpoint for memory not found 
WARN[0000] mountpoint for cpu not found                 
WARN[0000] mountpoint for blkio not found               
WARN[0000] mountpoint for cpuset not found              
DEBU[0000] Unix socket /var/lib/docker/network/files/e837021956760d90438e792638c57f85a73c4045848a2e92a045e9cb74c8cb75.sock doesnt exist. cannot accept client connections 
DEBU[0000] Cleaning up old shm/mqueue mounts: start.    
FATA[0000] Error starting daemon: Devices cgroup isn't mounted 

Any idea ?

**Comment by HackToday** [comment]
I am not sure if you have really full privilege to start a docker daemon in just a new network space here.

What do you want to archive?

**Comment by HamidEDD** [comment]
Mixing the network Namespace with user namespace in the last Docker Release (v1.10), we get a inexpensive multi-tenancy by creating isolated environments (containers & networks) for each tenant.

**Comment by cpuguy83** [comment]
`FATA[0000] Error starting daemon: Devices cgroup isn't mounted`

Without this cgroup container security would be compromised, so Docker will refuse to start.

**Comment by mlaventure** [comment]
Closing this issue since it's a environment configuration issue.

**Comment by HamidEDD** [comment]
`ip netns exec test cat /proc/mounts` is showing that  `test /sys sysfs rw,relatime 0 ` 
so by default, `/sys` is already mounted. 
Just for information, docker daemon start correctly outside the network namspace.

**Comment by mlaventure** [comment]
@HamidEDD, please look at my previous [comment](https://github.com/docker/docker/issues/21090#issuecomment-195011420)

`/sys` is indeed mounted, but none of the `cgroup` are. And the `device` cgroup is mandatory for the daemon to start.

Like I said before, `ip netns exec` remount `/sys` which has for effect to hide the `cgroup` mounts in the new namespace.
