### ISSUE TITLE
Docker Hub automated build fails all the time

### ISSUE THREAD

**Issue by domibarton** [docker/docker#21093]
Output of `docker version`:

```
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:09:42 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:09:42 2016
 OS/Arch:      linux/amd64
```

Output of `docker info`:

```
Containers: 12
 Running: 12
 Paused: 0
 Stopped: 0
Images: 182
Server Version: 1.10.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 204
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 31.32 GiB
Name: homo
ID: IVJK:UUQI:LZCX:BH6F:ZLZV:ENDP:JVVV:CJOI:V4J7:MJPY:YE5R:W7Q5
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):

* physical machine

List the steps to reproduce the issue:
1. Build the Docker image on the local host
2. Build the Docker image via Automated Build on Docker Hub

Describe the results you received:
1. The build on the local host works fine and w/o any issues
2. The build on the Docker Hub doesn't work

Describe the results you expected:
* The Build on the Docker Hub should work

Provide additional info you think is important:

Hi there!

I've created a [Docker image on Github](https://github.com/domibarton/docker-sabnzbd/blob/develop/Dockerfile) and linked it via automated build to the [Docker Hub](https://hub.docker.com/r/dbarton/sabnzbd/). Unfortunately the image won't build on the Hub and I'm trying it now for over a week! I don't know what's going on there, because I don't get a proper error message. It just says `Build failed:` or the connection while `apt-get` is dropped (see also http://cloud.confirm.ch/fNbK and http://cloud.confirm.ch/fNU7).

As mentioned before, the image ALWAYS builds fine on my local host and I never get an error (exactly the same git commit). It's really frustrating because there are no errors on the Hub and it always fails silently. I already wrote to `support@docker.com` but didn't get a response.

Do you know what's wrong with the build?

Cheers
Domi

**Comment by fauzanariffin** [comment]
Usually the problem we are seeing is that the Docker Automated Build (AB) was unable to publish logs when the build process timeout. Since you mentioned that the build is successful locally, I believe this due to the current limitation on Automated Builds:

- 2 hours
- 2 GB RAM
- 1 CPU
- 30 GB Disk Space

For larger builds you should either break them into several Automated Builds connected by FROM statements and Repository Links.

**Comment by The-Compiler** [comment]
I have the same issue: https://hub.docker.com/r/thecompiler/qutebrowser/builds/bsethmvqyhyvdtvjmnwuooj/

I see "Build failed:" without any logs, after it was on "building" for 2 hours.

The build should respect all those limits - locally, it takes around 5 minutes and produces a 700MB-image. It's essentially a Debian Jessie with some package installs.

**Comment by programmerq** [comment]
This issue with the automated build system where logs are not being populated should be remediated. In the future, definitely shoot support@docker.com an email if it's a question about the automated build system. :)

**Comment by The-Compiler** [comment]
Thank you! I indeed see logs now, even for past failed builds.

Nitpick: The error box at the top says "Build failed: -----------------------" [in my build](https://hub.docker.com/r/thecompiler/qutebrowser/builds/bkmjuxs4izad4adxeww4wvk/) - something like "Build failed: timed out" would be more appropriate.
