### ISSUE TITLE
Please add network name to docker ps output

### ISSUE THREAD

**Issue by pcgeek86** [docker/docker#21094]
The `docker ps` command would probably benefit from outputting the Docker network that a container instance is running within. Having this output readily available would make monitoring containers easier from an operational perspective.

Also, what about the `docker-compose ps`?

@vieux What do you think about this?

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by thaJeztah** [comment]
Hm, wondering if this is already possible using the [`--format` option](https://docs.docker.com/engine/reference/commandline/ps/#formatting); it looks like `NetworkSettings` is already available through the API; https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#list-containers

**Comment by thaJeztah** [comment]
We discussed this and don't think it's a high priority; using `curl` with `jq` would probably be a good alternative

**Comment by thaJeztah** [comment]
see https://github.com/docker/docker/issues/27564 :smile:
