### ISSUE TITLE
Allow restart_syscall in the default seccomp profile (or allow custom seccomp profiles to docker build)

### ISSUE THREAD

**Issue by SeanHeelan** [docker/docker#21104]
Output of `docker version`:

```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:40:35 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:40:35 2016
 OS/Arch:      linux/amd64
```

Output of `docker info`:

```
Containers: 12
 Running: 1
 Paused: 0
 Stopped: 11
Images: 419
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 437
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.82 GiB
Name: ubuntu
ID: HUBV:QRCF:EMYT:DZPW:6ZR4:ICF3:JKAH:M2M2:4NW2:AAJC:KFOT:6TUE
WARNING: No swap limit support
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):

List the steps to reproduce the issue:
1. Build an image on which an attempt is made to compile a target application and link it with LTTng's user space tracing library. 

Describe the results you received:

Compiling the target application fails due to an error in LTTng. 

Describe the results you expected:

LTTng to function correctly and compilation to succeed

Provide additional info you think is important:

As mentioned in the thread on the LTTng mailing list at [1], LTTng requires the `restart_syscall` syscall and docker blacklists it. When using `docker run` I can provide a custom seccomp profile that allows this syscall but this does not seem to be possible during the build process. Is it possible to allow `restart_syscall` by default? This would seem to be the easiest fix and according to [2] it should not be problematic from a security point of view (I have not independently verified this but if their reasoning is correct then the original commit to blacklist it was fixing a non-issue). 

Alternatively, if it was possible to specify a custom profile at build time, as it is with `docker run`, that would also allow me to solve the problem. 

[1] https://lists.lttng.org/pipermail/lttng-dev/2016-March/025573.html
[2] https://lists.lttng.org/pipermail/lttng-dev/2016-March/025575.html

**Comment by cpuguy83** [comment]
I'm going to close this in favor of #21105
