### ISSUE TITLE
Flush on os.stdout in pkg/chrootarchive/diff_unix.go in error, should be removed

### ISSUE THREAD

**Issue by amitkris** [docker/docker#21103]
HI,

This is to flag a bug in the pkg/chrootarchive/diff_unix.go file. In the function applyLayer() we do a flush on stdout, where flush is defined as:
flush(r io.Reader) {
io.copy(ioutil.Discard, r)
}

io.Copy is supposed to:
"Copy copies from src to dst until either EOF is reached on src or an error occurs." 

If we print the return values of io.Copy in flush(os.Stdout) we get
now written : 0 and err : read /dev/stdout: bad file descriptor

The code works in its current form by accident because it errors out. 
I tested the above on Ubuntu and I believe this is because pipes are uni-directional on Linux. stdout is not meant to be read from. (?)

If you were to run the above on a platform where pipes are bi-directional, Solaris for example the call would hang indefinitely waiting on an EOF.

SOLUTION: In either case the call to flush(os.Stdout) is in error and must be removed. Also having an error return for flush might be in order to prevent future occurences of this issue?

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->

Output of `docker version`:

```Client:
 Version:      1.11.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   d687023-unsupported
 Built:        Thu Feb 25 18:13:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   d687023-unsupported
 Built:        Thu Feb 25 18:13:07 2016
 OS/Arch:      linux/amd64


```

Output of `docker info`:

```Containers: 13
 Running: 1
 Paused: 0
 Stopped: 12
Images: 68
Server Version: 1.11.0-dev
Storage Driver: zfs
 Zpool: dockerpool
 Zpool Health: ONLINE
 Parent Dataset: dockerpool/docker
 Space Used By Parent: 4.87G
 Space Available: 73.4G
 Parent Quota: none
 Compression: off
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.67 GiB
Name: vzl-071
ID: S54H:WVNA:IJAG:NEIG:YXK5:D5PK:6XJI:MFIM:564T:ZS3V:I2B4:WT5T
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 18
 Goroutines: 39
 System Time: 2016-03-10T15:54:08.897173614-08:00
 EventsListeners: 0
 Docker Root Dir: /var/lib/docker
Http Proxy: http://www-proxy:80/
WARNING: No swap limit support
```

Steps to reproduce:
This code is touched in the "docker pull <image>" path.

Thanks,
Amit Krishnan

**Comment by thaJeztah** [comment]
Thanks @amitkris, would you be interested in opening a pull request, given that you know exactly what needs to be done?

**Comment by amitkris** [comment]
@thaJeztah sure! I'll submit it shortly.
