### ISSUE TITLE
Containers not deleting in 1.10.2

### ISSUE THREAD

**Issue by DamionWaltermeyer** [docker/docker#21101]
Hi, I ran some searches and I didn't come up with anything for 1.10.2.  

I'm cleaning thousands of containers off my systems every few days. Docker leaks a bunch of memory, can't clear containers, eventually locks up and then I need to reboot.  

I haven't cleaned this one up since early this morning so it's got containers, but not an excessive amount yet.  They are all behaving the same though.     

Please let me know what I can do to help get this resolved. 

```
Failed to remove container (2dfb091384a8): Error response from daemon: Driver aufs failed to remove root filesystem 2dfb091384a898702f95bb8403bc150c4e3fdba3f3a4994d2599b0b91bc7fc58: rename /var/lib/docker/aufs/mnt/887697abc761a775caed34deb305d6e42fbdda49ef6c2bdddb3b0d03b5363575-init /var/lib/docker/aufs/mnt/887697abc761a775caed34deb305d6e42fbdda49ef6c2bdddb3b0d03b5363575-init-removing: device or resource busy
Failed to remove container (6fe21a4dab1c): Error response from daemon: Driver aufs failed to remove root filesystem 6fe21a4dab1c40524dff3b94e9107f76c6f1fba33f342011cb15930923730b30: rename /var/lib/docker/aufs/mnt/aca6d31628b186945659ac3cc24db9ea892b0548c48f5937949d9b3adc4f9683-init /var/lib/docker/aufs/mnt/aca6d31628b186945659ac3cc24db9ea892b0548c48f5937949d9b3adc4f9683-init-removing: device or resource busy
Failed to remove container (1e7bfcbcc42c): Error response from daemon: Driver aufs failed to remove root filesystem 1e7bfcbcc42c4d51f5785206468b7227c8757765bac0f142cdbfba55a4058813: rename /var/lib/docker/aufs/mnt/5badd509790a928fa5f10748c6d220aece4e014a6290e1ec1071069be0bac957-init /var/lib/docker/aufs/mnt/5badd509790a928fa5f10748c6d220aece4e014a6290e1ec1071069be0bac957-init-removing: device or resource busy
```

```
uname -a
Linux docker-hostnameremoved 3.16.0-62-generic #83~14.04.1-Ubuntu SMP Fri Feb 26 22:52:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
docker version
Client:
Version: 1.10.2
API version: 1.22
Go version: go1.5.3
Git commit: c3959b1
Built: Mon Feb 22 21:37:01 2016
OS/Arch: linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

```
docker info
Containers: 151
 Running: 24
 Paused: 0
 Stopped: 127
Images: 13
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 432
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-79-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.861 GiB
Name: docker-at-vienna-2.connectify.me
ID: V62X:EVQW:OHKS:CQYL:NADC:AC74:5FYD:OZOU:ASIM:YJV5:UXH6:2NZX
WARNING: No swap limit support
```

/etc/issue

```
Ubuntu 14.04.4 LTS \n \l
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):

Multiple VPS of the same type across a handful of providers. 

Working on better reproduction steps. But essentially create on demand containers for users and then exit from them, after many have been created and deleted, docker resident memory starts to rise and deletions fail and then eventually docker cli stops responding and making new containers.

```
root       722     1 55 Mar01 ?        5-01:13:15 /usr/bin/docker daemon --dns 8.8.8.8 --dns 8.8.4.4 --userland-proxy=false --bip=172.17.42.1/16
```

We are currently using the none logging driver.

**Comment by HackToday** [comment]
Not quite sure if it same as this issue: https://github.com/docker/docker/issues/21078 ?

**Comment by HackToday** [comment]
It seems both hit that docker dameon panic in 1.10.2

**Comment by thaJeztah** [comment]
Did you install a custom kernel? Because I think Ubuntu 14.04.4 ships with kernel 4.2 by default (older versions were on 3.13) https://wiki.ubuntu.com/TrustyTahr/ReleaseNotes. Asking because I know kernel 3.16 is known for having some quirks on its own

**Comment by thaJeztah** [comment]
Oh, I see you reported output from different machines?

**Comment by bprodoehl** [comment]
Thanks for looking at this.  @DamionWaltermeyer and I are seeing this on a number of boxes, so very believable that output from different machines is above.  We're running a normal kernel out of the repo, though.  Ubuntu 14.04.4 can wind up with patched 3.13, 3.16 or I guess 4.2, depending on the install and upgrade path you follow.  Most of our boxes are running 3.13.0-79 which was released on Feb 22nd.  We'll try a test matrix of the 1.11.0-dev build and 4.2 LTS kernel early this week.

**Comment by sporokh** [comment]
I got the same problem often, running Ubuntu 14.04 LTS with `3.13.0-83-generic`

**Comment by LK4D4** [comment]
#21704 looks the same issue and still not resolved.
Am I right @thaJeztah @cpuguy83

**Comment by cpuguy83** [comment]
Yep, it's the same. Let's close this as a dup.
