### ISSUE TITLE
I can't see changes with my Image after Commit,Push and Pull for Next time.

### ISSUE THREAD

**Issue by upendra503** [docker/docker#21116]
I am new to docker,try to build a new image
I have created an image **upendra/apacheserver2** in [(https://hub.docker.com)]
I Pull it and made some changes like the below

         /# docker pull upendra/apacheserver2
         /# docker run -it -d -P upendra/apacheserver2
         /# docker exec -it 1c8c537a074d bash
i got like this
         root@1c8c537a074d:/var/www/html# 
here i created a file 
          root@1c8c537a074d:/var/www/html#  touch index.html
          root@1c8c537a074d:/var/www/html#  ls
        total 8
        -rw-r--r-- 1 root root   0 Mar 11 09:54 index.html
        -rw-r--r-- 1 root root 867 Mar 10 09:08 index.nginx-debian.html
        -rw-rw-r-- 1 root root  20 Jul  3  2015 index.php

         root@1c8c537a074d:/var/www/html# exit

         /# docker commit `docker ps -q -l` upendra/apacheserver123:latest > 2.0
         /# docker tag upendra/apacheserver123:latest upendra/apacheserver123:3.0
         /# docker push upendra/apacheserver123:3.0

Now I want to see the changes,so i pulled it and run.
         /# docker run -it -d -P upendra/apacheserver123      

       /# docker exec -it ab5fdcf8bbd0 bash
      root@ab5fdcf8bbd0:/var/www/html# ls -l
           total 8
           -rw-r--r-- 1 root root 867 Mar 10 09:08 index.nginx-debian.html
           -rw-rw-r-- 1 root root  20 Jul  3  2015 index.php
       root@ab5fdcf8bbd0:/var/www/html#

but the file created by is not showing,please help me to get new image content and
If i made any mistakes please let me know.
what are the steps that i need to follow when making changes to an image.

**Comment by upendra503** [comment]
**root@upendra-DL-A55M:/home/upendra# docker --version**
Docker version 1.10.3, build 20f81dd
**root@upendra-DL-A55M:/home/upendra# docker info**
Containers: 5
 Running: 4
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 28
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-30-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.731 GiB
Name: upendra-DL-A55M
ID: U3JI:6R3Q:OWAC:IDFC:L4CQ:3OZY:GUUM:5O75:WJNK:PKHP:5J6P:ZTLP
Username: upendra
Registry: https://index.docker.io/v1/

**Comment by thaJeztah** [comment]
Hi, thanks for asking @upendra503; without knowing what's actually inside the container/Dockerfile it's hard to tell. My suspicion is that the /var/www directory may be a volume, so not part of the containers filesystem.

However, please consider that our issue tracker is not a general support forum, but for tracking bugs and feature requests. For other type of questions, please use one of these;

- forums.docker.com
- the #docker IRC channel on freenode
- StackOverflow


I'll close this issue here because of the above, but feel free to comment here after I've closed.
