### ISSUE TITLE
Docker's documentation references config.json only for Linux users 

### ISSUE THREAD

**Issue by lirantal** [docker/docker#21119]
The online documentation, which is served by this file specifically https://github.com/docker/docker/blob/master/docs/userguide/containers/dockerrepos.md is only referring Linux users to their Docker's `config.json` file.
Example:

![image](https://cloud.githubusercontent.com/assets/316371/13702062/95e35bea-e794-11e5-9ed8-4147d4df8bbd.png)

It would be great to add this for other OSs, like Windows so that users are aware of where to look for this file.

**Comment by lirantal** [comment]
On Windows, the actual path should be `$HOME/.docker/config.json`

**Comment by HackToday** [comment]
so windows would know `$HOME` but not know `~` ?  Seems strange :0

**Comment by lirantal** [comment]
@HackToday see discussion on the actual PR
