### ISSUE TITLE
hack/make/.detect-daemon-osarch fails on linux/arm

### ISSUE THREAD

**Issue by jacksgt** [docker/docker#21125]
**Output of `docker version`:**
```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): 7c8fca2
OS/Arch (client): linux/arm
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): 7c8fca2
OS/Arch (server): linux/arm
```

**Output of `docker info`:**
```
Storage Driver: btrfs
 Build Version: Btrfs v3.17
 Library Version: 101
Execution Driver: native-0.2
Kernel Version: 4.4.1-sunxi
Operating System: Debian GNU/Linux 8 (jessie)
```

When trying to build the docker-dev image (with `make build`) I noticed that the script was using the usual Dockerfile instead of the Dockerfile.armhf, which of course resulted in a failure. (Can't run the AMD64 image on armhf)
I looked into the Makefile and saw that it is pulling the "DOCKER_OSARCH" variable from the script hack/make/.detect-daemon-osarch, which exports DOCKER_ENGINE_OSARCH, DOCKER_ENGINE_GOOS, DOCKER_ENGINE_GOARCH and DOCKER_CLIENT_OSARCH

**Describe the results you received:**
```
/bin/bash
$ source hack/make/.detect-daemon-osarch
$ echo $DOCKER_ENGINE_OSARCH
(empty line)
$ echo $DOCKER_CLIENT_OSARCH
(empty line)
```
The variables DOCKER_ENGINE_GOOS and DOCKER_ENGINE_GOARCH both depend on DOCKER_ENGINE_OSARCH, therefore they are false, too.

**Describe the results you expected:**
```
/bin/bash
$ source hack/make/.detect-daemon-osarch
$ echo $DOCKER_ENGINE_OSARCH
linux/arm
$ echo $DOCKER_CLIENT_OSARCH
linux/arm
```

**Additional information you deem important (e.g. issue happens only occasionally):**
```
$ uname -srmo
Linux 4.4.1-sunxi armv7l GNU/Linux
$ cat /etc/debian_version
8.3
```

**Comment by mlaventure** [comment]
arm support was officially added in master towards the end of last year. If I'm not mistaken 1.10 was the first release with arm support.

You would need to update your docker version or run a newer version in a container to build the image

**Comment by tianon** [comment]
Wanna give https://github.com/docker/docker/pull/21108 a go and see if I managed to get this in there? It might be because your host is only 1.6 and our script needs something a little newer, iirc.

**Comment by jacksgt** [comment]
The script you pushed doesn't work for me:
```bash
> docker version | awk '
 $1 ~ /^(client|server):$/ { section = 0 }
 $1 == "'"$target"':" { section = 1; next }
 section && $1 == "OS/Arch:" { print $2 }
 '
(no output)
>
```
Here is one that works (for the docker version output shown in my original post):
```
docker version | grep 'OS/Arch (server)' | cut -d' ' -f 3
linux/arm
```

@mlaventure Oh sure, I would love to [#20675](https://github.com/docker/docker/issues/20675)

**Comment by tianon** [comment]
@jacksgt ok, what about if we add this patch:
```diff
diff --git a/hack/make/.detect-daemon-osarch b/hack/make/.detect-daemon-osarch
index 9a51267..b77053f 100644
--- a/hack/make/.detect-daemon-osarch
+++ b/hack/make/.detect-daemon-osarch
@@ -12,6 +12,9 @@ docker-version-osarch() {
 		$1 ~ /^(Client|Server):$/ { section = 0 }
 		$1 == "'"$target"':" { section = 1; next }
 		section && $1 == "OS/Arch:" { print $2 }
+
+		# old versions of Docker
+		$1 == "OS/Arch ('"${target,,}"'):" { print $2 }
 	'
 }
```

(explicitly supporting older versions that don't have either `docker version -f` or the new indented output)

**Comment by jacksgt** [comment]
I do not have any major experience with awk, but the following works for me:
```bash
        docker version | awk '
                $1 ~ /^(client|server):$/ { section = 0 }
                $1 == "'"$target"':" { section = 1; next }
                section && $1 == "OS/Arch:" { print $2 }
                # old versions of Docker
                /OS\/Arch \('"${target}"'\):/ { print $3 }
        '
```

**Comment by tianon** [comment]
Ahh right, I forgot to account for the extra spaces:
```diff
diff --git a/hack/make/.detect-daemon-osarch b/hack/make/.detect-daemon-osarch
index 9a51267..571e802 100644
--- a/hack/make/.detect-daemon-osarch
+++ b/hack/make/.detect-daemon-osarch
@@ -12,6 +12,9 @@ docker-version-osarch() {
 		$1 ~ /^(Client|Server):$/ { section = 0 }
 		$1 == "'"$target"':" { section = 1; next }
 		section && $1 == "OS/Arch:" { print $2 }
+
+		# old versions of Docker
+		$1 == "OS/Arch" && $2 == "('"${target,,}"'):" { print $3 }
 	'
 }
 
```

**Comment by jacksgt** [comment]
Works like a charm, thanks @tianon !
Please close this issue when your PR is merged into master
