### ISSUE TITLE
Boot2Docker disappear, deleting it in hyperv

### ISSUE THREAD

**Issue by archergod** [docker/docker#21121]
**Output of `docker version`:**

Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      windows/amd64
An error occurred trying to connect: Get http://127.0.0.1:2375/v1.22/version: dial tcp 127.0.0.1:2375: connectex: No connection could be made because the target machine actively refused it.

**Output of `docker info`:**

An error occurred trying to connect: Get http://127.0.0.1:2375/v1.22/version: dial tcp 127.0.0.1:2375: connectex: No connection could be made because the target machine actively refused it.

I install a boot2docker, on my Windows 10 Pro 64bit along with Hyper-v. It run good, and I was able to run `gitlab` on it. Then I shutdown my Host machine, and next day I have Boot2Docker working fine, then on third day, I run `cmd.exe` as admin, run following command

# `docker-machine ls`

I see my `default` boot2loader is listed as Docker v.1.10.2

# `docker

it produce usage parameter.. as I mistype and press enter.

# `docker run`

docker: "run" requires a minimum of 1 argument.
See 'docker run --help'.

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Run a command in a new container

# docker-machine env

it produce error that no machine name is define and "default" machine doesn't exists.

By this time, my machine was deleted even from hard disk. that is all I did, under cmd.exe.

It happen to me that my boot2loader was deleted 2-3 times, but initially I thought I was doing something wrong, but my boot2loader is not sustained. Not sure if it is bug or still I did some messing.

**Comment by thaJeztah** [comment]
Can you open this issue in the docker-machine issue tracker (https://github.com/docker/machine/issues) because this sounds related to docker machine, not docker 

I also found this issue in the docker toolbox issue tracker, w.r.t. incompatibility between Hyper-V and VirtualBox; https://github.com/docker/toolbox/issues/349

Closing this issue here, because this is about docker machine, which is a different project
