### ISSUE TITLE
Allow specifying of a dockerfile as a path, not piping in.

### ISSUE THREAD

**Issue by peterbraden** [docker/docker#2112]
Would be nice to be able to specify `docker build -t my/thing -f my-dockerfile .` so I could ADD files, and also have multiple dockerfiles.

**Comment by martinraison** [comment]
+1

**Comment by rokcarl** [comment]
+1

**Comment by duglin** [comment]
@crosbymichael I believe this can be closed now due to #9707 being merged

**Comment by crosbymichael** [comment]
VICTORY.

If you all want to try this new feature out you can download the binaries for master on:

master.dockerproject.com

**Comment by crosbymichael** [comment]
Thanks @duglin !

**Comment by jakehow** [comment]
:clap:

**Comment by zedtux** [comment]
Thank you @crosbymichael for the binary ! :+1:

**Comment by palladius** [comment]
Well done guys! :clap:

**Comment by olalonde** [comment]
So it's `docker build -f Dockerfile.dev .`?
