### ISSUE TITLE
dockremap user shows up for as a valid login id under ubuntu trusty

### ISSUE THREAD

**Issue by RsrchBoy** [docker/docker#21137]
Output of `docker version`:

```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64
```

Output of `docker info`:

```
Containers: 6
 Running: 4
 Paused: 0
 Stopped: 2
Images: 952
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: xfs
 Dirs: 965
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.2.0-30-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.55 GiB
Name: athena
ID: QIBW:XTEW:EYMZ:ELGG:3WBS:5ATK:PKWA:BW25:A7WE:FWZA:DCF4:NTR7
WARNING: No swap limit support
```

Provide additional environment details (AWS, VirtualBox, physical, etc.):

List the steps to reproduce the issue:
1. Install docker 1.10+
2. Reboot / reload lightdm
3. Check login users presented :)

Describe the results you received:

`dockremap` is presented as a user to log in as.

Describe the results you expected:

`dockremap` is ignored, as a system user that cannot be used to log in,

Provide additional info you think is important:

The uid `dockremap` uses is high enough to be outside the range of ids that the system flags as being a system id.

One solution is to this would be to create `/var/lib/AccountsService/users/dockremap` that contains:

```
[User]
SystemAccount=true
```

This may be a ubuntu-specific solution; solving it generally is beyond the scope of this bug report ;)

**Comment by estesp** [comment]
ah--yes, I need to add some flags to the useradd/adduser scenario to make sure this is a system account (across distros, which looks to be possible with standard flags to those tools)

**Comment by thaJeztah** [comment]
@estesp I'll add this to the 1.11 milestone, sounds like we should be able to get that done in time?

**Comment by cyphar** [comment]
@estesp Actually "system accounts" are defined by what their UID is. If the UID is between SYS_UID_MIN and SYS_UID_MAX (this is usually a range `<1000`), then the account is a "system" account. Using `useradd -r` (which is the "system account" flag) just makes the UID generation try to make an account in that range -- so I'm not sure if there's an actually distro agnostic way of doing it.

**Comment by RsrchBoy** [comment]
IMHO, using the right flags to `useradd` to tell it that the id is a system id is preferable, as it both uses the next uid available in the system range and does some other things (like set the shell to a "nope!" shell -- `/usr/sbin/nologin` on my trusty box) as well.

In my experience on RHEL, Debian, and their derivatives, using `useradd` to designate a user as a system user is preferable and reliable.  (I'd trust it over meddling with AccountsService, FWIW, but that'll probably have to be the route taken if making it a system id right off the bat isn't practical for any reason.)

Just my $0.02 :)

**Comment by cyphar** [comment]
@RsrchBoy the problem is that we use `dockremap` for remapping root to *that* UID (as well as remapping a section of the UID space). So, if we don't want overlaps with actual user IDs on the system, the UID of `dockremap` needs to be **larger** than the "system UID range". I'm not sure if some distributions have fields for "system users", but on my machine the docs clearly say that a "system UID" is in a particular range (500 <= x < 1000 in my case).

**Comment by estesp** [comment]
Note that to test this solution that was just merged, you will have to remove the user created by prior Docker engine releases.  Only when the user is re-created will it be created as a system user--there is no official way to "migrate" an existing user to a system user.
