### ISSUE TITLE
Proposal - Image defined probe

### ISSUE THREAD

**Issue by icecrime** [docker/docker#21143]
## Problem statement

This is a followup to #21142 to discuss the idea of adding a way to specify a default "alive probe" for all containers started from a particular image.

## Proposal

Introduce a new Dockerfile instruction to specify the probe. The (yet to be used) support for instructions options could be leveraged to model the design proposed for the CLI.

- An image would optionally have a single probe definition, and any new occurrence of that instruction (either in the same Dockerfile, or in a child image) would override the previous one.
- The default probe could be overridden through the command-line.

## Open questions:

- Ping @tianon: what's your opinion on that in the context of official images?

*Ping @crosbymichael @tonistiigi @mgoelzer @aluzzardi @ehazlett*

**Comment by tianon** [comment]
I definitely think that this is useful to be able to set a default in the image metadata, given that the image author is going to be in the best position to say what conditions _generally_ make a given service be considered "available" (especially if they need to write and include in the image a potentially complex script for determining as much), and then the operator can decide whether they want to use those as-is, define their own, or disable such checks entirely.

The place I see instant value for this is for images like databases and their consumers -- for example, the official `wordpress` image has a really boring "retry" loop to just keep trying to hit MySQL until it's actually initialized, configured, and up and ready for connections.

I've got some other comments/thoughts for the implementation itself, but I'll go post those on the issue discussing the runtime feature. :+1:

**Comment by dnephin** [comment]
I wonder if the configuration for these "probes" is really consistent enough between environments and different users that it would belong in the image. An image author could still provide the necessary scripts or endpoints, and document that they are available, without having to provide the probe configuration.

It also seems likely that images that are extended would be forced to modify the probe configuration quite often, which could make it more work to extend these images.

**Comment by thaJeztah** [comment]
There's a pull request opened to implement this, so anyone that's interested, PTAL at https://github.com/docker/docker/issues/22719

**Comment by AkihiroSuda** [comment]
@thaJeztah Is this issue closable? https://github.com/docker/docker/pull/23218

**Comment by thaJeztah** [comment]
Yes! If forgot the "closes" mention in my carry, thanks!

implemented in https://github.com/docker/docker/pull/23218
