### ISSUE TITLE
File/Connection Leak with volume plugins

### ISSUE THREAD

**Issue by pryorda** [docker/docker#21163]
Looks like docker is leaking connections/open files when using custom volume drivers (glusterfs and others).

docker    10562   root 1095u  IPv4  57512      0t0  TCP localhost:33685->localhost:8979 (ESTABLISHED)
docker    10562   root 1096u  IPv4  58540      0t0  TCP localhost:33688->localhost:8979 (ESTABLISHED)
docker    10562   root 1097u  IPv4  58544      0t0  TCP localhost:33690->localhost:8979 (ESTABLISHED)
.....

ubuntu@swarm-demo-2:~$ sudo lsof -i TCP |grep 8979 |wc -l
2047
ubuntu@swarm-demo-2:~$ sudo lsof -i TCP |grep :8979 |wc -l

ubuntu@swarm-demo-2:~$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
ubuntu@swarm-demo-2:~$

ubuntu@swarm-demo-2:~$ docker info
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 19
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-253:1-393244-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 10.61 GB
 Data Space Total: 107.4 GB
 Data Space Available: 28.87 GB
 Metadata Space Used: 16.58 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.131 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local glusterfs
 Network: overlay null host bridge
Kernel Version: 3.19.0-49-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.86 GiB
Name: swarm-demo-2
ID: VWYW:TI7W:QJRG:773K:WGGS:EMVH:RZV4:NIVM:G2CP:KWLF:UEEO:Z6DG
WARNING: No swap limit support
Cluster store: consul://127.0.0.1:8500
Cluster advertise: 172.20.7.122:2376
ubuntu@swarm-demo-2:~$

**Steps to reproduce the issue:**
1. Setup up gluster servers
2. Install gluster volume plugin on docker node/host
3. restart docker and wait

**Comment by HackToday** [comment]
It seems this was fixed in 
https://github.com/docker/docker/pull/20686

**Comment by cpuguy83** [comment]
Yes, this is fixed.
Thanks!
