### ISSUE TITLE
Unknown option dm.loopdatasize (Docker 1.7.1 on CentOS 6.7)

### ISSUE THREAD

**Issue by pdericson** [docker/docker#21171]
**Output of `docker version`:**

```text
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```

**Output of `docker info`:**

```text
Containers: 0
Images: 0
Storage Driver: devicemapper
 Pool Name: docker-253:0-786851-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 305.7 MB
 Data Space Total: 107.4 GB
 Data Space Available: 38.45 GB
 Metadata Space Used: 729.1 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.95-RHEL6 (2015-04-15)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 2.6.32-573.el6.x86_64
Operating System: <unknown>
CPUs: 1
Total Memory: 1.833 GiB
Name: node-1
ID: QRU2:7U3E:MSVU:2LM2:HDD5:PAJY:WBJB:XFQS:O5AZ:OA64:K3QK:QKRH
Http Proxy: http://10.0.2.2:3128/
Https Proxy: http://10.0.2.2:3128/
No Proxy: .localdomain
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

- VirtualBox
- CentOS 6.7

**Steps to reproduce the issue:**
1. Set `other_args` in `/etc/sysconfig/docker` to include `--storage-opt dm.loopdatasize=200G`
2. Start docker

**Describe the results you received:**

Docker cannot start:

```text
time="2016-03-14T00:43:32.619815742Z" level=fatal msg="Error starting daemon: error initializing graphdriver: Unknown option dm.loopdatasize"
```

**Describe the results you expected:**

`/var/lib/docker/devicemapper/devicemapper/data` should be 200gb

**Additional information you deem important (e.g. issue happens only occasionally):**

The code and docs from 1.7.1 seem to support this so I'm unsure why it's not working

https://github.com/docker/docker/blob/v1.7.1/daemon/graphdriver/devmapper/deviceset.go#L1730

https://docs.docker.com/v1.7/docker/reference/commandline/daemon/#storage-driver-options

**Comment by HackToday** [comment]
I did not think your kernel version meet the requirements here:

https://docs.docker.com/v1.7/docker/installation/centos/

**Comment by pdericson** [comment]
@HackToday 

Sure it does :)

from https://docs.docker.com/v1.7/docker/installation/centos/

2.6.32-431.el6.x86_64

I'm running:

2.6.32-573.el6.x86_64

**Comment by pdericson** [comment]
Specifying storage driver in addition to the storage option made it work for me.

```text
--storage-driver devicemapper --storage-opt dm.loopdatasize=200G
```

**Comment by HackToday** [comment]
oh strange, from `docker info`, I thought you did configure devicemapper option :0
