### ISSUE TITLE
docker stats panics especially when removing containers: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by lindt** [docker/docker#21182]
Could be similar to that bug, but for me it reads different: [https://github.com/docker/docker/pull/11343](url)

**Output of `docker version`:**

```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 82
 Running: 31
 Paused: 0
 Stopped: 51
Images: 218
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 653
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-32-generic
Operating System: Ubuntu 14.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67 GiB
Name: kari-docker1
ID: NNHB:B4AX:Q73C:CEDD:VQ32:32FU:MNWN:T2YE:RHGP:J4YX:IYTY:2U7F
WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. docker-compose up -d   for a larger project
2. docker stats
3. docker-compose up -d with some changes that require new/other containers
4. docker stats will crash

**Describe the results you received:**

see the attached stdout file.
[docker_stats_panic_slice_bounds_out_of_range.txt](https://github.com/docker/docker/files/171830/docker_stats_panic_slice_bounds_out_of_range.txt)

**Describe the results you expected:**

no crash. and even if this is not supported, please give a user friendly error message instead of a stack trace.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment]
This should be fixed on master already.
The client side code was quite racey.
Any chance you can try this from a master build?

**Comment by lindt** [comment]
master worked so far; anyway I just checked it for a few hours.
So I'm going to close this issue.
If there is another panic, I'm going to reopen it.
Thanks for your help.
