### ISSUE TITLE
Docs: Incorrect information about size of debian image

### ISSUE THREAD

**Issue by cs-shadow** [docker/docker#21195]
> Whenever possible, use current Official Repositories as the basis for your image. We recommend the Debian image since it’s very tightly controlled and kept extremely minimal (currently under 100 mb), while still being a full distribution.

The docs suggest that the Debian image is under 100 mb. While this may have been true at some time point in the past, it's incorrect at present. https://github.com/docker-library/docs/blob/master/debian/tag-details.md#debianlatest suggests that the size is around 125 mb now - for latest and jessie.

**Comment by thaJeztah** [comment]
Thanks for reporting; are you perhaps interested in contributing and opening a pull request? The Markdown file used to generate that page of the documentation can be found in this repository; https://github.com/docker/docker/blob/master/docs/userguide/eng-image/dockerfile_best-practices.md

If you're new to contributing to docker, the [contribution guide](https://docs.docker.com/opensource/workflow/make-a-contribution/) explains all the steps

**Comment by geekylucas** [comment]
#dibs
