### ISSUE TITLE
Allow docker logs to work when using journald logging driver

### ISSUE THREAD

**Issue by wrouesnel** [docker/docker#21204]
Currently the journald logging driver does *not* work with the docker logs command. This is fine on a host level, but interferes with services interacting with docker via the API interface.

This seems somewhat incongruous as journald by default provides excellent support for searching and filtering logs. It would be good if docker could support retrieving container log files from the systemd journal when the journal logging driver is in use.

**Comment by cpuguy83** [comment]
This is already in place in docker 1.9
There may be some issue with linking to journald... I think there's an issue for that, but currently on mobile.

**Comment by LK4D4** [comment]
Yup, it works. It might be a problem with packaging(it requires dynamic linking with systemd libs as @cpuguy83 said).

**Comment by runcom** [comment]
closing - journald works with docker logs

**Comment by hholst80** [comment]
Documentation was never updated to reflect this.

**Comment by cpuguy83** [comment]
@hholst80 Did you have somewhere in mind?

I see it here: https://docs.docker.com/engine/admin/logging/overview/#supported-logging-drivers
![screen shot 2017-03-09 at 3 57 49 pm](https://cloud.githubusercontent.com/assets/799078/23770474/2eb47c68-04e1-11e7-8b4e-371bbc560e2d.png)

**Comment by hholst80** [comment]
Aha. My installation in Centos only said json-file (but supported journald).
