### ISSUE TITLE
Streamline Ubuntu installation instructions

### ISSUE THREAD

**Issue by atrauzzi** [docker/docker#21214]
I've gone through a few Docker installs on Ubuntu both myself as well as with some new developers on my team.  I've noticed a fairly consistent series of missed steps or mistakes that keep happening during each setup.  This is not because the document is incomplete, but because the necessary steps are spread out and hidden amongst other **optional** steps.

https://github.com/docker/docker/blob/master/docs/installation/linux/ubuntulinux.md

It would be nice if the following steps were put at the top of the instructions and noted as a "typical" flow for installation:

---
1. Add the new `GPG` key.
   
   ```
   sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
   ```
2. Add an entry for your Ubuntu operating system to `/etc/apt/sources.list.d/docker.list`
   - On Ubuntu Precise 12.04 (LTS)
         `deb https://apt.dockerproject.org/repo ubuntu-precise main`
   - On Ubuntu Trusty 14.04 (LTS)
         `deb https://apt.dockerproject.org/repo ubuntu-trusty main`
   - Ubuntu Wily 15.10
         `deb https://apt.dockerproject.org/repo ubuntu-wily main`
   - Ubuntu Wily 16.04
         `deb https://apt.dockerproject.org/repo ubuntu-xenial main`
3. Update the `APT` package index.
   
   ```
   sudo apt-get update
   ```
4. Install Docker
   
   ```
   sudo apt-get install docker-engine
   ```
5. Add your user to the `docker` group
   
   ```
   sudo usermod -aG docker ubuntu
   ```
   ---

This series of steps is sufficient for the majority of the installations that happen.  While it's fine to keep the extended information - as it's helpful - burying the important parts has required me to assist every person I've instructed to install docker.

It's worth noting I think given the number of steps needed to install the Ubuntu package, would it not make sense for Docker to publish an official PPA?  Much of this would be mitigated by just doing that.

**Comment by nwright-nz** [comment]
#dibs

**Comment by LK4D4** [comment]
@thaJeztah Can you pls take a look?

**Comment by thaJeztah** [comment]
Was discussing this with @mstanleyjones recently, it's still on the map (but probably in a rewrite that makes the flow "express install" (uniform for all distro's) -> advanced / production install.

**Comment by LK4D4** [comment]
@thaJeztah should we close this and move to docs repo?

**Comment by thaJeztah** [comment]
Oh, yes, you're right, these docs moved there, we can close the issue here
