### ISSUE TITLE
Docker network in internal mode will not use IPv4 by default and is very slow.

### ISSUE THREAD

**Issue by yongtang** [docker/docker#21224]
**Output of `docker version`:**

```
Client:
 Version:      1.11.0-dev
 API version:  1.23
 Go version:   go1.6
 Git commit:   6f2d8b4
 Built:        Tue Mar 15 17:55:34 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0-dev
 API version:  1.23
 Go version:   go1.6
 Git commit:   6f2d8b4
 Built:        Tue Mar 15 17:55:34 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 8
 Running: 5
 Paused: 0
 Stopped: 3
Images: 1
Server Version: 1.11.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 149
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-74-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: ip-172-28-3-38
ID: OC3W:F5HD:OHOB:KRO2:2PF5:DFJZ:77D7:CVGC:QTKY:PCDW:H5LQ:WLYW
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS EC2 instance.

**Steps to reproduce the issue:**
1. Create a network in internal mode.
```
docker network create --driver=bridge --internal internal
```
2. Create two containers.
```
docker run -d --net=internal --name=box1 busy box top
docker run -d --net=internal --name=box2 busybox top
```
3. Invoke ping from one container to outside, and from one container to another container
```
time docker exec box1 ping -c 1 www.google.com
ping: bad address 'www.google.com'

real	0m30.896s
user	0m0.034s
sys	0m0.013s

time docker exec box2 ping -c 1 box1
PING box1 (172.20.0.2): 56 data bytes
64 bytes from 172.20.0.2: seq=0 ttl=64 time=0.080 ms

--- box1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.080/0.080/0.080 ms

real	0m15.886s
user	0m0.039s
sys	0m0.010s
```

3. Invoke ping from one container to outside, and from one container to another container, (set IPv4 explicitly)
```
time docker exec box1 ping -c 1 -4 www.google.com
ping: bad address 'www.google.com'

real	0m15.879s
user	0m0.038s
sys	0m0.010s


time docker exec box2 ping -c 1 -4 box1
PING box1 (172.20.0.2): 56 data bytes
64 bytes from 172.20.0.2: seq=0 ttl=64 time=0.054 ms

--- box1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.054/0.054/0.054 ms

real	0m0.865s
user	0m0.038s
sys	0m0.013s
```

**Describe the results you received:**

As is shown in the above, when a bridge network is created with option `--internal`, a simple ping test is very slow unless IPv4 option (`-4`) is specified explicitly.

In addition, even if `-4` is specified, it takes a long time (15s) for a ping to return 
`ping: bad address 'www.google.com'`.

**Describe the results you expected:**
A simple ping test should return fairly quickly.

**Additional information you deem important (e.g. issue happens only occasionally):**
See https://github.com/docker/docker/pull/21200 for reference.

**Comment by thaJeztah** [comment]
@sanimej I assigned you to this, to make it easier to find back, and because you were already looking into this :+1:

**Comment by sanimej** [comment]
Its not really specific to internal networks. But embedded DNS server originally was forwarding all the queries that can't be resolved in docker domain to external DNS servers. In the case of `internal` networks since there is no external connectivity the queries will timeout which is typically 5 seconds.

https://github.com/docker/libnetwork/pull/1039 fix was made to not forward the IPv6 queries externally if its a valid name in the docker domain.

This issue cab be closed.
