### ISSUE TITLE
Docker. No such file or directory

### ISSUE THREAD

**Issue by katalonne** [docker/docker#21227]
I have some files which I want to move them to a docker container.
But at the end docker can't find a file..

The folder with the files on local machine are at **/home/katalonne/flask4**

**File Structure** if it matters:

[![File Structure if it matters](http://i.stack.imgur.com/VMRAF.jpg)](http://i.stack.imgur.com/VMRAF.jpg)
The **Dockerfile**:

```
#
# First Flask App Dockerfile
#
#

# Pull base image.
FROM centos:7.0.1406

# Build commands
RUN yum install -y python-setuptools mysql-connector mysql-devel gcc python-devel
RUN easy_install pip
RUN mkdir /opt/flask4
WORKDIR /opt/flask4
ADD requirements.txt /opt/flask4
RUN pip install -r requirements.txt
ADD . /opt/flask4

# Define deafult command.
CMD ["python","hello.py"]

# Expose ports.
EXPOSE 5000
```

So I built the image with this command :

```
docker build -t flask4 .
```

I ran the container with volume by :

```
docker run -d -p 5000:5000 -v /home/Katalonne/flask4:/opt/flask4 --name web flask4
```

---

And when I want to run the file on the container :

```
docker logs -f web
```

I get this error that it can not find my hello.py file :

```
python: can't open file 'hello.py': [Errno 2] No such file or directory
```

What is my fault? 

P.S. : I'm a Docker and Linux partially-noob.

**Comment by vdemeester** [comment]
@katalonne with a long delay in the answer (:sweat_smile:), does this happen with recent docker version ? what was your version at that time (client, server version, kernel version, linux distribution) ?

**Comment by thaJeztah** [comment]
closing because we didn't receive more information
