### ISSUE TITLE
Streaming logs, json driver "Error streaming logs: unexpected EOF"

### ISSUE THREAD

**Issue by Soulou** [docker/docker#21220]
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 165
 Running: 147
 Paused: 0
 Stopped: 18
Images: 293
Server Version: 1.10.3
Storage Driver: btrfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.2.0-34-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 31.42 GiB
Name: <edited>
ID: AZNH:RYE6:EPU2:OM3H:RQGL:E6GL:3PCA:BJJP:JVQO:ILYS:G7B4:TWOZ
Username: <edited>
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
 
physical server

**Steps to reproduce the issue:**
1. Container configuration:

```js
            "LogConfig": {
                "Type": "json-file",
                "Config": {
                    "max-file": "1",
                    "max-size": "1m"
                }
            },
```

2. Run a container with a lot of output
3. Wait

**Describe the results you received:**

Docker daemon logs:

```
time="2016-03-15T18:13:29.573092612+01:00" level=error msg="Error streaming logs: unexpected EOF"
```

**Describe the results you expected:**

No error

I assume it's when the 1M buffer is full. But accoding to the docs it's a rolling buffer isn't it ?

**Comment by ripcurld00d** [comment]
@Soulou did you try to do
`docker logs -f <container-name>`

**Comment by Soulou** [comment]
@ripcurld00d Not at all, I'm actually following the logs of all containers on the host (using directly the API).

Using Go with the package `fsouza/go-dockerclient`

This happens a bit randomly for containers generating a lot of logs, we have no error returned by the client, it seems to be as if the container is stopping normally, but definitely it's not, the container is still present and the log line is added to docker logs.

```
time="2016-03-15T18:13:29.573092612+01:00" level=error msg="Error streaming logs: unexpected EOF"
```

**Comment by ripcurld00d** [comment]
Uh huh, I see now.
Can you provide more details like the code-lines and such?
Also, the `docker inspect` output of one of the containers.

I would like to reproduce it again on my machine.

Thanks.

**Comment by cpuguy83** [comment]
#21301 makes the jsonlog reader quite a bit more stable.
I'm somewhat suprised you get an unexpected EOF, though.

**Comment by Soulou** [comment]
@ripcurld00d No I don't have any 'waiting for events' messages on the daemon side

Here is the implicated code:  https://gist.github.com/Soulou/ac9f3ff92bf15670ab59

And the docker inspect: https://gist.github.com/Soulou/7c895587a5e49d05ce70

**Comment by iwidanalage** [comment]
@Soulou I had the same issue on similar setup (1mb, single file). The log stream stops (probably due to file role-over. 

Ended up wrapping the docker.Logs call on a for loop so it restarts log stream.


`
       
    defer out.Close()
	for {
		select {
		case <-done:
			debug("Docker log stream stopped for:", name)
			return
		default:
			debug("starting log stream for", name, ", since:", sinceTime)
			err := client.Logs(docker.LogsOptions{
				Container:    id,
				OutputStream: out,
				ErrorStream:  out,
				Stdout:       true,
				Stderr:       true,
				Follow:       true,
				Tail:         "all",
				Since:        sinceTime.Unix(),
			})
			if err != nil {
				debug("Failed docker log stream for:", name, " error:", err.Error())
			} else {
				debug("Docker log stream ended for:", name)
			}
			sinceTime = time.Now()

		}
	}`

Hope this helps

**Comment by mkscrg** [comment]
Any movement here? It's bad behavior for `docker logs -f` to exit cleanly when the the container is still running.

We've hit this issue in an AWS ElasticBeanstalk system, which does this in an init script after running a container:

```
# EB assumes that `docker logs` will exit cleanly only when the container is finished:
docker logs -f CONTAINER_ID >> LOGFILE 2>&1
exec docker wait CONTAINER_ID
```

So when `docker logs` exits cleanly and the container is still running, our logs stream breaks.

**Comment by thaJeztah** [comment]
@mkscrg would the AWS CloudWatch logs driver be a solution for your use case? https://docs.docker.com/engine/admin/logging/awslogs/

**Comment by mkscrg** [comment]
@thaJeztah I don't think so. EB automatically rotates log files (redirected from `docker logs -f` output) and copies them to S3. We rely on that S3 copy for cold log storage, and this docker issue breaks that too.

(We do send logs to CWL for monitoring, and we use the standard EB+CWL config to do it. It works fine except for this issue.)

I've talked to AWS support about this. They said roughly "hope docker fixes it, or fix it yourself via a custom init script".

**Comment by veqryn** [comment]
I too have run into this issue, in our AWS Beanstalk multi-docker-container deployments.
When there is significant output to stdout, `docker logs -f` fails, despite the container still running just fine.

**Comment by SoAG** [comment]
Running into the same issue with version 1.9.1. Any update on this?

**Comment by paralin** [comment]
Happening now with version v1.12.0-rc3: 

```
Client:
 Version:      v1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   unknown
 Built:        Tue Jul  5 12:07:13 PDT 2016
 OS/Arch:      linux/arm64

Server:
 Version:      v1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   unknown
 Built:        Tue Jul  5 12:07:13 PDT 2016
 OS/Arch:      linux/arm64
```

and

```
Jul 11 17:37:07 base1 dockerd[282]: time="2016-07-11T17:37:07.294182000Z" level=error msg="Error streaming logs: EOF"
```

**Comment by mkscrg** [comment]
Our workaround, in case this helps anybody:

To fix this in our Elastic Beanstalk apps, we wrote a CloudFormation setup script to edit the init script that normally calls `docker logs`.

The init script (`/etc/init/eb-docker.conf`) does this by default:

```sh
docker logs -f $EB_CONFIG_DOCKER_CURRENT_APP >> /var/log/eb-docker/containers/eb-current-app/$EB_CONFIG_DOCKER_CURRENT_APP-stdouterr.log 2>&1
```

Our edited version drops that line, instead runs `docker logs --timestamps --since` in a loop, holding the last timestamp and redirecting the normal output (timestamps stripped) to the usual log file. We risk an occasional duplicated log event when `docker logs` misbehaves, but at least our log stream doesn't break:

```sh
since='0'
while true; do
  since="$(
    docker logs -f -t --since="$since" $EB_CONFIG_DOCKER_CURRENT_APP 2>&1 |
      tee >(stdbuf -i0 -o0 cut -d' ' -f1 --complement >> /var/log/eb-docker/containers/eb-current-app/$EB_CONFIG_DOCKER_CURRENT_APP-stdouterr.log) |
      cut -d' ' -f1 | tail -n1
  )"

  if [ "$(docker inspect --format='{{ .State.Running }}' $EB_CONFIG_DOCKER_CURRENT_APP)" = 'true' ]; then
    true
  else
    break
  fi
done
```

**Comment by cpuguy83** [comment]
Could you please test with #24514? Thanks!
