### ISSUE TITLE
Inconsistent streaming formats on some API calls like /build ?

### ISSUE THREAD

**Issue by jankeromnes** [docker/docker#21248]
This is more a question than an issue, but I'm wondering why the `/build` Remote API call returns JSON-formatted chunks like `{"stream":"..."}` and `{"error":"..."}` instead of multiplexing `stdout` and `stderr` like other API calls.

As documented in: https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#build-image-from-a-dockerfile

**Output of `docker version`:**

```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

**Output of `docker info`:**

```
Containers: 48
Images: 1016
Storage Driver: aufs
 Root Dir: /data2/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1146
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 16
Total Memory: 63.11 GiB
Name: irill2
ID: GRUJ:4V5T:KSWG:L5HV:5JKV:RW5L:CYSK:ZBMG:GXSZ:W5JG:Q3CX:H2RP
WARNING: No memory limit support
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical server running `Linux 3.16.0-4-amd64` and `Debian 8.3 jessie`.

**Steps to reproduce the issue:**
1. Send a properly formatted request with tar stream to the `/build` API endpoint.
2. Listen for Docker's response.

**Describe the results you received:**

A series of JSON-formatted chunks like `{"stream":"..."}` (and `{"error":"..."}` if the build failed).

**Describe the results you expected:**

A stream with multiplexed `stdout` and `stderr`.

**Additional information you deem important (e.g. issue happens only occasionally):**

Reproduces 100%.

**Comment by thaJeztah** [comment]
These endpoints return more information than just stdout/stderr, such as progress bars, and for that reason use a different format.

I'll close this issue, because it's not really a bug, but feel free to comment after
