### ISSUE TITLE
Flaky test: TestRunAttachFailedNoLeak

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#21247]
Hm flaky test? seen failing on https://github.com/docker/docker/pull/21203 (https://jenkins.dockerproject.org/job/Docker-PRs-WoW-TP4/2941/console)

```
05:40:38 PASS: docker_cli_run_test.go:536: DockerSuite.TestRunApplyVolumesFromBeforeVolumes	42.889s
05:41:34 
05:41:34 ----------------------------------------------------------------------
05:41:34 FAIL: docker_cli_run_test.go:4223: DockerSuite.TestRunAttachFailedNoLeak
05:41:34 
05:41:34 docker_cli_run_test.go:4230:
05:41:34     c.Assert(err, checker.NotNil)
05:41:34 ... value = nil
05:41:34 
05:41:56 
05:41:56 ----------------------------------------------------------------------
```

**Comment by yongtang** [comment]
The issue seems to be that,
```
runSleepingContainer(c, "--name=test", "-p", "8000:8000")
```
may not be truly in running state when another container 
```
out, _, err := dockerCmdWithError("run", "-p", "8000:8000", "busybox", "true")
```
runs and publishes the port 8000.

In docker, iptables associated with the published port is only added when a container is started (running), not when the container is created.
A test of
```
docker create --name=test -p 8000:8000 busybox top
iptables-save
```
will reveal this scenario.

#dibs

**Comment by yongtang** [comment]
@thaJeztah @vdemeester This issue seems to be still hanging:
```
15:43:14 PASS: docker_cli_run_test.go:536: DockerSuite.TestRunApplyVolumesFromBeforeVolumes	45.612s
15:44:11 
15:44:11 ----------------------------------------------------------------------
15:44:11 FAIL: docker_cli_run_test.go:4223: DockerSuite.TestRunAttachFailedNoLeak
15:44:11 
15:44:11 docker_cli_run_test.go:4233:
15:44:11     c.Assert(err, checker.NotNil)
15:44:11 ... value = nil
15:44:11 
15:44:36 
15:44:36 ----------------------------------------------------------------------
```
https://jenkins.dockerproject.org/job/Docker-PRs-WoW-TP4/3205/console


Let me do some further investigation on it.

**Comment by thaJeztah** [comment]
Thanks @yongtang, yes, I was already keeping an eye on that test, but just saw it again, so I'll reopen

**Comment by thaJeztah** [comment]
I think we haven't seen this in a while, but we can reopen if it returns
