### ISSUE TITLE
Proposal - Add filters for volume command about name and driver

### ISSUE THREAD

**Issue by HackToday** [docker/docker#21243]
Right now, docker volume only support dangling filter, it would be good to support name and driver filter (network has kinds of support, like name and id etc)

What will do like below:

```
root@bf86488287ac:/go/src/github.com/docker/docker# docker volume ls -f driver=local
DRIVER              VOLUME NAME
local               testd
local               wokrd
root@bf86488287ac:/go/src/github.com/docker/docker# 
root@bf86488287ac:/go/src/github.com/docker/docker# docker volume ls -f name=testd
DRIVER              VOLUME NAME
local               testd

```

**Comment by HackToday** [comment]
ping @cpuguy83 and @thaJeztah  or others (quite not sure for volume filter, who to ping)

Let me know if it OK for that, I could send PR for that. Thanks

**Comment by thaJeztah** [comment]
I like it; it's consistent with the other commands we have, so +1 from me

**Comment by vdemeester** [comment]
I have nothing against it either so +1 for me too :wink:

**Comment by mgreau** [comment]
I just try to use it today, so +1 :smiley:

BTW, there is no label yet about the experience required to implement it, is it ok for a beginner?
Thanks.

**Comment by HackToday** [comment]
@mgreau I would implement :) Forget to mark it with #dibs

**Comment by mgreau** [comment]
ok :+1:
