### ISSUE TITLE
Feature: Allow configuring UID (or username) and GID (or groupname) when creating volumes with 'volume create' using "local" volume driver

### ISSUE THREAD

**Issue by zerthimon** [docker/docker#21259]
Currently the volume is created as owned by root:root
```
# docker volume create --driver local --name foo
foo
# ls -ld /var/lib/docker/volumes/foo/_data/
drwxr-xr-x 2 root root 4096 march 16 18:46 /var/lib/docker/volumes/foo/_data/
```

I'd like to be able to override the ownership of the volume, for example:
```
docker volume create --driver local --opt uid=948 --opt gid=948 --name foo
foo
# ls -ld /var/lib/docker/volumes/foo/_data/
drwxr-xr-x 2  948  948 4096 march 16 18:46 /var/lib/docker/volumes/foo/_data/
```
or
```
docker volume create --driver local --opt user=foouser --opt group=foogroup --name foo
foo
# ls -ld /var/lib/docker/volumes/foo/_data/
drwxr-xr-x 2 foouser foogroup 4096 march 16 18:46 /var/lib/docker/volumes/foo/_data/
```

Having this option I'd be able to access the volume in a container running as a specific user without additional manipulations.

EDIT:
This is a matter or internal user ownership (and access permissions) of the effective user inside the container.

**Comment by HackToday** [comment]
Not quite understand the user case here, do you mean you have a container, you want run some commands in that container as non-root ?  And as non-root you could not access the volume ?

**Comment by zerthimon** [comment]
@HackToday 

From Dockerfile:
```
...
RUN addgroup --system --gid 980 apps && \
         adduser --system --uid 980 --gid 980 --home /home/apps apps && \

USER apps
WORKDIR /home/apps
...
```
I want to make data in user's home directory persistent to survive container rebuilds, so I make a named volume:
```
# docker volume create --driver local --name apps_home
apps_home
# ls -ld /var/lib/docker/volumes/apps_home/_data/
drwxr-xr-x 2 root root 4096 march 16 18:46 /var/lib/docker/volumes/foo/_data/
```
Nottice the ownership of this volume is **root:root**
When I run the container with 
```
-v apps_home:/home/apps
```
User's home directory is mounted, but ownership is **root:root** so app_user cannot write anything in there.

The idea of this feature is to pre-set ownership of the volume at volume creation.
Currenlty I have to change ownership manually (after running 'docker volume create'):
```
chown 980:980 /var/lib/docker/volumes/[volume_name]/_data
```

**Comment by Simon-L** [comment]
Totally seconding this.
Particularly tricky part for a newcomer.
Haven't tried with datacontainer though. Should be the same?

Personal example: bitlbee container.

**Comment by HackToday** [comment]
@zerthimon  yes, volume is special in docker, as it all mapped to root, which has some security related consideration before,.

ping @cpuguy83  if we have any ways to support non-root cases for volume ?

**Comment by cpuguy83** [comment]
Volumes get uid/gid of the content at the path in the image.

**Comment by vberruchon** [comment]
Hi @cpuguy83 , could you precise that in the case of a bind on a created named volume?


I was searching to replace the use of a data-only container by a named volume (using docker 1.9.1) so my use case seems to be the same as @zerthimon.

With a data-only container, I just have to assign the uid:gid on the directory of the volume in the Dockerfile. In my case, useradd is creating the directory with the right uid/gid.:
`RUN useradd -r -u 200 -m -c "my role account" -d ${MYUSER_DATA} -s /bin/false myuser
`
I do create the running container and the data-only container from this same image. It works quite well. The only issue is probably that ops team have to understand that this is normal that this container is "Exited" and should be keeped like that.

With a named volume, the only way I've found to have the good permissions is to explicitly "chown" the volume "_data" directory to the wanted uid where on the host .. as root...
`chown 200:200 /var/lib/docker/volumes/myuser-named-volume/_data/`

For the moment it seems easier to manage everything from Dockerfile/docker commands with data-only container to avoid to play with chown on host directory!

**Comment by cpuguy83** [comment]
@vberruchon If you upgrade Docker this will just work... I think in 1.10.

**Comment by HackToday** [comment]
@cpuguy83  I did not think volume support non-root case ? which PR include such support in 1.10 ?

**Comment by cpuguy83** [comment]
@HackToday I'm really not sure, but any time docker copies data from the image path to the container, the volume will be setup with the same exact uid/gid.

**Comment by zerthimon** [comment]
@HackToday I just asked for a feature, so I can change the ownership of the volume root at command line in the same command. As a user, I'd like to have and option not to care much about security, but have more productability instead.

**Comment by cpuguy83** [comment]
I'm going to close because I do not think there is a need for this.
Docker already copies uid/gid from the container that consumes the volume from the image path contents.

Feel free to discuss, but again this is handled by the nature of how volumes work when you mount them in a container.

**Comment by HackToday** [comment]
@cpuguy83  I did not catch the above comments,  for @zerthimon  comments for
running as non-root user in container, the named volumes are root privileged which prevent that user to write any data to that volume, why not need this ?

**Comment by cpuguy83** [comment]
@HackToday The named volumes are privileged with whatever the the dir in the container is privileged as.

**Comment by richardjr** [comment]
The reason this is needed is for (in my case) dev environments. If you want to make changes to a shared volume as a non-root user it means breaking the file systems security, IE /var/lib/docker/volumes/.

We use IDE's to deploy files when developing and so the shared external volume is the best way to achieve this, specifically when using compose to scale the apps in dev its the only way to ensure they all are up to date.

The problem is that create volume even when run as non root is created as root with 700 under  /var/lib/docker/volumes/

What would be better is to allow the volume to be created in a specified location EG /home/user/dockervolume and that gid be set able.

**Comment by dfeyer** [comment]
> The named volumes are privileged with whatever the the dir in the container is privileged as.

This work fine if the directory exist in the container, but sometimes the directory does not exist in the container. By ex. for local development I have container that offer SSH/SFTP access and map aussi volume under the user home directory. So docker create the directory when mounting the volume and in this case the permission are root:root ... 

Other question, what is multiple container mount a single volume but have different permissions for the target directory does Docker change the volume permission on each mount ? The last win ? Smell like a hell to manage, and having a way in the docker-compose to configure uid, gid and perms look like a more solid and predictable solution

**Comment by cpuguy83** [comment]
@dfeyer first wins, and you can tell docker to not set perms as well. If the dir doesn't exist, why not just create it as part of the build? This is crazy simple.

Agreed what you suggest is ideal, but not technically possible right now... At least not without making significant assumptions about loaded kernel modules as well as performance problems.

Note that right now docker4mac does map ownership to the user in the container automatically.

**Comment by docteurklein** [comment]
@cpuguy83 oh my god you just learn me some good stuff here:

```
cat Dockerfile
FROM alpine
RUN mkdir /testdata && chown 1000:82 /testdata
```

and then I run a container like this:

```
docker build -t test .
docker run -v /testdata test ls -al /testdata
total 8                                                                                                                                                                     
drwxr-xr-x    2 1000     82            4096 Jul 24 15:47 .                                                                                                                  
drwxr-xr-x    1 root     root          4096 Jul 24 15:47 ..
```

So yes, uid/gid **are** inherited from the original target! so cool! thanks.

**Comment by Hubro** [comment]
In my case, the Docker image I'm using (enonic/xp-app) creates the folder in question on first run. If I create a named volume and map it to the container as I create it, it will crash on startup because it can't write to the folder.

Example:

```bash
$ docker run -d --name exp -v exp-home:/enonic-xp/home --port 8080:8080 enonic/xp-app:6.15.4
```

Output is full of errors like this:

>/enonic-xp/home/config does not exist, copying files from distro ( /enonic-xp/home.org/config )...
>cp: cannot create directory ‘/enonic-xp/home/config’: Permission denied
>/enonic-xp/home/deploy does not exist, copying files from distro ( /enonic-xp/home.org/deploy )...
>cp: cannot create directory ‘/enonic-xp/home/deploy’: Permission denied
>/enonic-xp/home/logs does not exist, copying files from distro ( /enonic-xp/home.org/logs )...
>cp: cannot create directory ‘/enonic-xp/home/logs’: Permission denied

I'm guessing this would be fixed if Enonic created `/enonic-xp/home` in their Dockerfile?

In this case it would be very useful for me if there was an option to specify uid/gid and permissions when creating the named volume.

**Comment by parameshjava** [comment]
@zerthimon  it seems `uid` and `gid` options were removed recently for volume creation, is there any other approach?

**Comment by KoltesDigital** [comment]
I also have this issue. In my case, setting permissions in the Dockerfile is impossible because it is part of the runtime configuration of the application, not of the application itself.

FWIW according to https://docs.docker.com/engine/reference/commandline/volume_create/ and http://man7.org/linux/man-pages/man8/mount.8.html it's possible to set uid and gid at volume creation for a local device with most drivers. The drawback is that the path has to be set explicitly, which is otherwise handled by the command. I haven't tried because of this drawback.
