### ISSUE TITLE
Flaky Test : DockerSuite.TestBuildNotVerboseFailure

### ISSUE THREAD

**Issue by vdemeester** [docker/docker#21252]
Happenend on `janky`.

```
16:58:59 FAIL: docker_cli_build_test.go:4872: DockerSuite.TestBuildNotVerboseFailure
16:58:59 
16:58:59 docker_cli_build_test.go:4892:
16:58:59     c.Fatal(fmt.Errorf("Test[%s] expected that quiet stderr and verbose stdout are equal; quiet [%v], verbose [%v]", te.TestName, qstderr, vstdout+vstderr))
16:58:59 ... Error: Test[quiet_build_not_exists_image] expected that quiet stderr and verbose stdout are equal; quiet [Sending build context to Docker daemon 2.048 kB


16:58:59 Step 1 : FROM busybox11
16:58:59 Get https://registry-1.docker.io/v2/library/busybox11/manifests/latest: EOF
16:58:59 ], verbose [Sending build context to Docker daemon 2.048 kB


16:58:59 Step 1 : FROM busybox11
16:58:59 Pulling repository docker.io/library/busybox11
16:58:59 Error: image library/busybox11 not found
16:58:59 ]
```

See https://jenkins.dockerproject.org/job/Docker-PRs/25232/console

**Comment by ripcurld00d** [comment]
#claim

**Comment by vdemeester** [comment]
@ripcurld00d it's #dibs usually :wink:

**Comment by ripcurld00d** [comment]
Ummm... I have no idea but it looks like this problem isn't reproducible.
I tried to reproduce it by running tests on HEAD and later on #21217 but unsuccessful.

It is odd that in one time it returned the correct error message (image not found) and in other time, it tried to fetch it but got EOF (I assume).

In addition, looking on other PRs and builds, this happened only on #21217 builds.

I am clueless about what to do next.

**Comment by thaJeztah** [comment]
looks like it failed once on https://github.com/docker/docker/pull/20775, but couldn't find others

**Comment by ripcurld00d** [comment]
@thaJeztah thanks a lot...
Try to see what happened there. :smile:

**Comment by ripcurld00d** [comment]
@thaJeztah,

This cli-integration test is definitely problematic.

In one hand, we would like to verify that when the image doesn't exist the same error message will be received by the cli in both modes (w or w/o `-q`).
On the other hand, this test is tightly coupled to the daemon. so if it doesn't pass, it doesn't mean that the `-q` flag is the problem.

Therefore, we need to think whether we are going to decouple this and if so, how to do that correctly.

Feedback?

**Comment by thaJeztah** [comment]
Probably no longer an issue
