### ISSUE TITLE
Encountered Syntax Error while installing Docker-Compose through pip in Ubuntu 14.04 server

### ISSUE THREAD

**Issue by ackris** [docker/docker#21255]
**Environment Details:**

VirtualBox
Networking through NAT (adapter 1) and intnet (adapter 2)

**Docker Version:**

```
Client:
version: 1.10.2

Server:
version: 1.10.2
```

I followed the below installation procedure of `docker-compose`

    sudo apt-get update

    sudo apt-get install python-pip

    pip install docker-compose

    docker-compose version

I am facing the below mentioned error while trying to check the installation `docker-compose`. 

    /usr/local/bin/docker-compose: line 1: syntax error near unexpected token 'newline'
    
    /usr/local/bin/docker-compose: line: '<!DOCTYPE html>'

Has anyone encountered this error? How to resolve this?

_
**PS**: I also tried to install `docker-compose` through `curl`. Still faced the same error_

**Comment by ripcurld00d** [comment]
@ackris, I have a feeling docker-compose wasn't installed successfully.
can you copy-paste the output of the following command:
```shell
$ head -1  $(which docker-compose)
```

BTW, I think this issue should be here https://github.com/docker/compose

**Comment by ackris** [comment]
@ripcurld00d , I have removed the VM, and will begin the process from the scratch. Hopefully, it shouldn't give the same error :)

**Comment by ackris** [comment]
@ripcurld00d I have tried CentOS 7 instead of Ubuntu Trusty. I have installed Docker in CentOS. My observation- CentOS rocks!!! :100: It is simple. Smooth as a silk. Ubuntu is a bit complicated to handle.

**Comment by cpuguy83** [comment]
Closing since compose has it's own repo: github.com/docker/compose
Thanks for reporting!
