### ISSUE TITLE
Cache HTTP requests made during build

### ISSUE THREAD

**Issue by bigblind** [docker/docker#21260]
I'm often writing code while on the bus/train, where I don't have a (stable) internet connection. Many of my docker builds rely on package managers or other programs that rely on network access.

Could docker intercept network requests made during the build, and if there's no network connection, return a cached version? The resources that these network requests point to usually don't change often, so this could really improve the development experience;

**Comment by cpuguy83** [comment]
All build steps are already cached.

**Comment by thaJeztah** [comment]
agreed; docker already caches layers, so won't make these requests, unless the cache is busted (in which case, making these requests is a sensible thing to do).

If you want to cache these requests, use a caching proxy, or (e.g. for `apt`), `apt-cacher` https://docs.docker.com/engine/examples/apt-cacher-ng/
