### ISSUE TITLE
Which port does docker use while pulling images down?

### ISSUE THREAD

**Issue by hhsnopek** [docker/docker#21264]
I'm unable to locate which port is being used while pulling down from docker, I'm running into the network proxy error at my university. Unless there's an easy way to set the port to 80, I'll need to port number so I can request a network rule be made for my computer. Thank you for the assistance! :smile: 

**Output of `docker version`:**

```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 8
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 22
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.1.18-boot2docker
Operating System: Boot2Docker 1.10.2 (TCL 6.4.1); master : 611be10 - Mon Feb 22 22:47:06 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: Y7U4:AK5K:PSDU:FGQK:ZU6J:53HF:VGVY:XNE2:CD2W:UEBB:KHEV:UCLW
Debug mode (server): true
 File Descriptors: 11
 Goroutines: 24
 System Time: 2016-03-16T21:36:23.619266664Z
 EventsListeners: 1
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: hsnopek
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox

```

**Comment by HackToday** [comment]
Is it a issue or question ?  I suggest question found in IRC channel, stackflow, or docker forum.

The issue tracker is for bugs. :)


What errors do you get ? How do you config the proxy?

Also I think v2 protocol for example registry-1.docker.io/v2, all use 80 port. Correct me if others think it is not right.

**Comment by hhsnopek** [comment]
it was just a question! 😀 I didnt know there was a irc channel - I'll ask
there next time, thank you!
-- 
Henry Snopek

**Comment by cpuguy83** [comment]
@hhsnopek port for pulling from a registry? It's whatever the port that is specified in the image tag. Default is 443 if no port is specified.

**Comment by HackToday** [comment]
@hhsnopek please check @cpuguy83  comments, I forget registry default use HTTPS, so it is 443. Not 80 for HTTP

**Comment by hhsnopek** [comment]
@HackToday @cpuguy83 thank you :grinning:
