### ISSUE TITLE
Question: Mounting a sshfs folder and share it with host

### ISSUE THREAD

**Issue by yarmenti** [docker/docker#21278]
Hi guys,

I'm currently trying to run a container that start a sshfs process to mount a shared file system.
I would like to mount it and share it with the host (and then with other containers).

I saw a github discussion on that problem and understood that it was solved. If I got that, I need to pass the `shared` argument when specifying the volume. Unfortunately, it does not work.

`docker run -it --privileged -v /empty_host_data_dir/:/container_volume_to_mount/:shared my_container`

afterwards, when I list `/container_volume_to_mount` in my container, it's OK, I get my files, but when go back to the host and list `/empty_host_data_dir` it is still empty.

I'm using docker v 1.6.2 in a Ubuntu 15.10 host.

Could you help me?

Thanks,

**Comment by yarmenti** [comment]
```
$docker info

Containers: 13
Images: 64
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 90
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 4.2.0-34-generic
Operating System: Ubuntu 15.10
CPUs: 1
Total Memory: 1.636 GiB
Name: my-host
ID: V37Z:QEZT:DOLV:2AG6:6TYM:3CKW:CTMU:HA3Q:MJUM:JLII:4FCP:OJQN
WARNING: No swap limit support
```

```
$docker version

Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.5.1
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.5.1
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

**Comment by HackToday** [comment]
that command means, it will 
mount  /empty_host_data_dir to container directory. As you host directory is empty, so after mount, it is still empty. Any issue for this ?

**Comment by yarmenti** [comment]
I didn't understand your answer. 

My `/empty_host_data_dir` is empty at the beginning yes, but once mounted in the container directory, I want to mount inside it the content of my sshfs network folder.

Thus, if I was not enough explicit, I'd like to mount something from the container into a mounted volume.

Thanks,

**Comment by cpuguy83** [comment]
@yarmenti You need to upgrade to Docker 1.10 to have this funtionality.
Containers are in their own mount namespace and mounts are not propagated back the host.
WIth 1.10 you can specify that you do want to share mounts back to the host, like this: `-v /foo:/bar:shared`... but this is only supported in since 1.10.
