### ISSUE TITLE
docker inspect for mount propagation throws errors

### ISSUE THREAD

**Issue by praving5** [docker/docker#21277]
**Output of `docker version`:**

```
# docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:39:25 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:39:25 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
# docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 5
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-253:1-67129347-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.24 GB
 Data Space Total: 107.4 GB
 Data Space Available: 41.31 GB
 Metadata Space Used: 3.453 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.18.17-13.el7.x86_64
Operating System: Red Hat Enterprise Linux
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 7.812 GiB
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Set a mount propagation mode for volume during container run
2. Try to do docker inspect to extract out mount propagation mode

**Describe the results you received:**
On my container, mount propagation mode is set as below:

```
"Mounts": [
            {
                "Source": "/home",
                "Destination": "/home",
                "Mode": "shared",
                "RW": true,
                "Propagation": "shared"
            }
        ],

```

The output of docker inspect on whole Mounts works as expected.

```
# docker inspect --format '{{ .Mounts }}' 0091
[{ /home /home  shared true shared}]
```

But, when I try to be precise, it breaks:
```

# docker inspect --format '{{ .Mounts.Propagation }}' 0091

Template parsing error: template: :1:10: executing "" at <.Mounts.Propagation>: can't evaluate field Propagation in type interface {}

```

**Describe the results you expected:**
That should have just returned shared as it does for other docker inspect entries for example below works just fine:

```
# docker inspect --format '{{ .HostConfig.Privileged }}' 0091
false

```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by ozlerhakan** [comment]
Hi @praving5 ,

`HostConfig` is a JSON object but `Mounts` is a JSON array containing one JSON object. You need to try something like the following one to reach  key-value pairs of the first element:

`$ docker inspect --format '{{(index .Mounts 0).Propagation}}' <container-id-or-name>`

**Comment by praving5** [comment]
Yes, that works!

Is there a way I can have it to work without specific index (I mean show all mounts and their respective propagation modes irrespective of what index they are on)

**Comment by ozlerhakan** [comment]
I have this command getting all the mount objects

`$  docker inspect --format '{{range $mnt := .Mounts}} {{json $mnt}} {{end}}' <c-name>`

List all propagation modes of the mounts

`$  docker inspect --format '{{range $mnt := .Mounts}}  {{json $mnt.Propagation}} {{end}}' <c-name>`

Have you looked at this [doc](https://docs.docker.com/engine/reference/commandline/inspect/) ?

**Comment by praving5** [comment]
Thanks again. I will try this out.
