### ISSUE TITLE
Feature: Log Driver for Kafka

### ISSUE THREAD

**Issue by markdav** [docker/docker#21271]
The ask here is for a native log driver for Kafka 0.8+.  Kafka is a high volume open source distributed messaging framework, which is very popular in the logging community.  It would be widely useful to be able to stream logs from a particular container to a given kafka topic.  This would be analogous to the logspout-kafka adapter for logspout.  For the many environments with kafka in place, this would be a more robust and easier method of docker log collection to e.g. elk stack than the rsyslog/logspout/etc approaches.

The features of this log driver should be:

1) Configurable with kafka topic, broker list and kafka producer properties.
2) Fail gracefully if kafka is unavailable

*_Note: *_ A potential stumbling block with this item may be in terms of the number of statically compiled external dependencies on docker itself - it would be nicer if there were some way to develop log drivers as plugins.  In this case, it is likely that one of the established go kafka clients would need to be added as a dependency.

**Comment by subfuzion** [comment]
Very timely. I was just searching to see if a log driver for Kafka already existed, which led me to this issue.

**Comment by subfuzion** [comment]
The last part of @markdav's issue got me wondering about plugin support rather than adding every conceivable logging driver possible to the engine. What about an "image" logging driver that lets you specify an image to run (forwarding driver configuration parameters)? Logs could be streamed to this container, which is responsible for implementing whatever logic necessary as part of shipping logs to some other destination.

**Comment by subfuzion** [comment]
I've proposed a solution that lets docker stream the logs to a container you specify with the image option for a "custom" logging driver [here](https://github.com/docker/docker/issues/18604#issuecomment-198786889). The container can implement whatever logic it wants to forward the logs to another destination.

**Comment by markdav** [comment]
That's a really nice idea @subfuzion .. I guess it's not *too* far from the logspout, logspiout-kafka approach.  A neat way of streaming from containers to kafka would be great, and I started it locally.. but not sure of the timing due to a) hints that logging will be changed to avoid the dependency bloat and b) kafka 0.9 and it's immature security (non-java clients not supported yet on secure kafka servers).

**Comment by subfuzion** [comment]
@markdav Thanks. I would still love to see an actual kakfa driver as a first class citizen with the engine. I see my proposal more as a way of allowing anyone to leverage the official logging driver mechanism to pass along options to any container they want to have started up for custom handling/forwarding logs, without being forced to wait for a specialized driver to prove its merit and get merged into upstream, and without having to wait for a plugin design to become finalized.

**Comment by dvenza** [comment]
I am also very interested in a native kafka log driver.

**Comment by LK4D4** [comment]
I hope this will be fixed by #28403

**Comment by jmcewan127** [comment]
Would be awesome, kafka has many advantages.

**Comment by rsvancara** [comment]
Would you want the log format to be just bare logs or some kind of format (maybe JSON)?

**Comment by dvenza** [comment]
I would want all the metadata.

Basically take the gelf messages and put them into a kafka topic could be one solution.

**Comment by AkihiroSuda** [comment]
FYI: The PR for logging plugin infra will be merged in short
https://github.com/docker/docker/pull/28403

Kafka plugin could be implemented using this

**Comment by jmcewan127** [comment]
JSON would preferable.

Jon

**Comment by cpuguy83** [comment]
Log plugin support is now merged and should be part of 17.05.
I do not think we'll be accepting any new built-in log drivers.

Closing this. Any new log drivers should be implemented as a plugin at this point. If anyone wants to discuss this feel free to ping me on Slack, or come see me @ DockerCon!
