### ISSUE TITLE
Binding network bridge to externally accesible interface

### ISSUE THREAD

**Issue by carlskii** [docker/docker#21289]
Hi,

I know this is a usage question but I'm stuck on this. I see that theres some new features in Docker that now enables this: 

```
# create a new bridge network with your subnet and gateway for your ip block
$ docker network create --subnet 203.0.113.0/24 --gateway 203.0.113.254 iptastic
```

This created a new bridge network interface on my Docker host that looks like this:

```
br-b255cf4703fc Link encap:Ethernet  HWaddr 02:42:66:B6:77:D3  
inet addr:203.0.113.254  Bcast:0.0.0.0  Mask:255.255.255.0
UP BROADCAST MULTICAST  MTU:1500  Metric:1
RX packets:0 errors:0 dropped:0 overruns:0 frame:0
TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:0 
RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
``` 

I then created a new container with a static IP address like this:
```
$ docker run --rm -it --net iptastic --ip 203.0.113.2 nginx
```

Since I'm running my Docker host machine (RancherOS) in Virtualbox, is there a next step to bind the newly created network and associated container to the existing externally accessible interface, in this case eth1 ?

So far so good.

**Comment by carlskii** [comment]
OK - for those who hit this issue. This post worked perfectly for me.

http://ispyker.blogspot.co.uk/2014/04/accessing-docker-container-private.html?showComment=1458315067913#c1119300992631997718

**Comment by thaJeztah** [comment]
looks like you found your answer, so I'll close this. For these kind of questions, forums.docker.com may be a better location

**Comment by carlskii** [comment]
Thanks, actually it was even simpler than the blog. I just did this from my Mac's OS. 

`sudo route -n add 172.17.0.0/16 ` boot2docker ip``
