### ISSUE TITLE
pull image :failed to register layer: link

### ISSUE THREAD

**Issue by freelingchang** [docker/docker#21285]
Description of problem:
docker pull  my.com/test:master
...
9cb3f0a48cf4: Already exists 
d0714d42ff45: Already exists 
60a7835ac5f5: Pull complete 
1378db14c73c: Pull complete 
5cf74e70f824: Extracting    133 B/133 B
failed to register layer: link /var/lib/docker/overlay/0c3d96719941d56f4d2ec24c17373699b8f09534f54649b9f3aa4c0b91bd0967/root/var/lib/yum/yumdb/p/da2fa0265ff301afa8591f7a7269ea95dd5d70e3-pygpgme-0.3-9.el7-x86_64/installed_by /var/lib/docker/overlay/886ad560613a8caf04725e74823e2f1a74a7af9f308d0ed574ea134ea1664749/tmproot415088144/var/lib/yum/yumdb/p/da2fa0265ff301afa8591f7a7269ea95dd5d70e3-pygpgme-0.3-9.el7-x86_64/installed_by: too many links

docker version:1.10.1

docker info:
Containers: 76
 Running: 65
 Paused: 0
 Stopped: 11
Images: 421
Server Version: 1.10.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.0
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 38.35 GiB

`uname -a`: Linux localhost.localdomain 4.4.0 #1 SMP Wed Jan 27 18:03:30 CST 2016 x86_64 x86_64 x86_64 GNU/Linux
Environment details : xenserver vm

df -i
/dev/mapper/centos-root 14361600 2453698 11907902      18% /

**Comment by thaJeztah** [comment]
It looks like you're not running the standard kernel for CentOS 7 (which, ships with kernel 3.10), which is not a supported setup, and can be related

**Comment by thaJeztah** [comment]
closing because this is not a supported configuration, but feel free to comment after I closed
