### ISSUE TITLE
Proposal: Be more verbose about stopping and deleting containers

### ISSUE THREAD

**Issue by Daxda** [docker/docker#21281]
I would love to see a more verbose output when stopping and deleting containers.
Currently only the name of the container is printed out, but not what operation was
executed.

e.g. 
```shell
$ docker stop gogs && docker rm gogs
gogs
gogs
```

Would then look something like this:
```shell
$ docker stop gogs && docker rm gogs
Stopping container: 'gogs'
Removing container: 'gogs'
```

**Comment by HackToday** [comment]
When you propose it, we need to consider interface consistency, it means other commands also need such change, like container pause etc. , network, volume resource. 
What's the special user case for print stopping and removing ?  Is it for user-aware something happening  for just CLI ?

**Comment by Daxda** [comment]
Yea it's pretty much just an addition to the output of the CLI.

**Comment by thaJeztah** [comment]
The reason for outputting just the name is so that it can be used to script the result, think of (for example)

    cid=$(docker stop 5e7469ee013f7d2af3f07d71a614a1765b2714198ea4ce07690cfa47e4a58965)
    echo $cid
    5e7469ee013f7d2af3f07d71a614a1765b2714198ea4ce07690cfa47e4a58965

So, I'm not sure we should change that

**Comment by HackToday** [comment]
IMO, Add such seems not much helpful, as user would finally check container status with another CLI or API call, such temp status is not reliable.

**Comment by thaJeztah** [comment]
Well, it's the way all commands work to make them easily scriptable / chain able, think of other situations, where you don't know the ID up-front, such as `docker rm -fv $(docker ps -aq -n 1)`. Changing this would break things for many people, so I don't think we should do this

**Comment by lujiwen** [comment]
I am agree with HackToday .If so,that will brings a lot of work for other interfaces.,and it seems really unnecessary that other interfaces can do  to make sure what the status of the container is .

**Comment by AndrewGuenther** [comment]
I completely agree with @thaJetzah. The exit code of the operation will tell you if it succeeded or not. And you shouldn't be relying on STDOUT output to determine success. If this were to be printed anywhere, it should go to STDERR, but I would say even that is unnecessary.

You gain no additional information but doing this.

**Comment by thaJeztah** [comment]
I'll go ahead and close this. Thanks for suggesting, @Daxda - I hope you understand :+1:

**Comment by arunasank** [comment]
Sometimes, docker hangs when `docker stop` or `docker rm` is run. A more verbose output will help a developer understand what's going on. Also, you could trigger the verbosity only if the `--verbose` flag is applied and not change the default behaviour, so that the change is backwards-compatible.

**Comment by cpuguy83** [comment]
@arunasank These hangs are straight up bugs that should be reported (if you are running on a currently supported release). More verbosity won't really help here. You can get a stack trace from dockerd in this case, though, which is incredibly helpful for fixing the problem.
