### ISSUE TITLE
Is docker suitable for running untrusted code?

### ISSUE THREAD

**Issue by anik786** [docker/docker#21314]
Is docker suitable for running untrusted code?

I want to create a educational web app that compiles and runs code for the user similar to: https://ideone.com/

Thus I need a secure sandboxing technique.
Is docker suitable for this?

**Comment by cpuguy83** [comment]
Unless you understand the underlying technologies involved, I'd say no it's not (and really VM's aren't either, but I digress).

Closing since this isn't really an issue.

**Comment by anik786** [comment]
So how would you go about doing this. It's clearly been done numerous times! The fact that ideone.com and sphere-engine exists is testiment to that.
