### ISSUE TITLE
Would Docker DNS support Load Balance?

### ISSUE THREAD

**Issue by sqleejan** [docker/docker#21320]
I have some question about docker network
     1.Would Docker DNS support Load Balance?
     2.Is Buildin Overlay Driver of Docker ready for Production?

**Comment by sqleejan** [comment]
Output of docker version:

Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      linux/amd64


Output of docker info:

Containers: 10
 Running: 2
 Paused: 0
 Stopped: 8
Images: 57
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 110
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: overlay bridge null host
Kernel Version: 3.19.0-51-generic
Operating System: Ubuntu 15.04
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.77 GiB
Name: leejan-eleme
ID: DGKE:K4DO:EX7B:3WTL:KIBI:6MKQ:ZW67:MISR:K7XZ:5Z4P:74OD:DWDH
WARNING: No swap limit support
Cluster store: etcd://10.192.40.86:2379/docker-cluster
Cluster advertise: 172.16.28.102:4000


I have some question about docker network
1.Would Docker DNS support Load Balance?
2.Is Buildin Overlay Driver of Docker ready for Production?

**Comment by thaJeztah** [comment]
To answer your questions:

1. The DNS currently does not do "round robin", if that's what you're asking. There's plans to add it, but also realize that "round robin" isn't the best way to do load balancing
2. Absolutely! No need to install other solutions or networking plugins, the built-in networking should all work out of the box for production.

/cc @mavenugo for additional thoughts on your first question

**Comment by mavenugo** [comment]
1. We added the multiple A Records support for 1.11 release. So, when there are multiple containers have the same `--net-alias`, the embedded DNS's response will container multiple A records pointing to IP-Addresses of the containers matching the same alias. Also, we randomize the list. For clients capable of handling multiple A records, they can handle the load-balancing with its own algorithm. And for clients who can lookup just the first record, the randomized list will act similar to load-balancing.
But in the long-term we will go with a service level abstraction with Virtual-IP based proper load-balancing. But that is for future releases.

2. Yes. Anything built-in and that is not experimental is typically ready for production use.

**Comment by sqleejan** [comment]
@thaJeztah @mavenugo this would really help me

**Comment by mavenugo** [comment]
@sqleejan pls try docker master and let us know if that works for you. I think this issue can be closed now.

**Comment by thaJeztah** [comment]
let me close; but comment if you're still having this issue on 1.11 once that's released
