### ISSUE TITLE
'no such directory' actual message for docker cp to remote host when the (vpn) connection is down

### ISSUE THREAD

**Issue by FireballDWF** [docker/docker#21328]
**Output of `docker version`:**

Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:59:07 2016
 OS/Arch:      linux/amd64

**Output of `docker info`:**
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 25
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 100
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-30-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.675 GiB
Name: testbed2
ID: V66T:LWBI:QYSE:RLRM:VBZA:GATN:7III:GIOW:455T:UC2C:MPG2:TEEU
Username: fireballdwf
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=amazonec2

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VPN connection between client and server

**Steps to reproduce the issue:**
1. Install docker-toolbox
2. Connect client VPN to (AWS VPC) VPN server 
3.  docker-machine create an instance on AWS, start a container
4.  VPN drops (user, doesn't notice)
5. docker cp localfile container:remotepath

**Describe the results you received:**
'no such directory'

**Describe the results you expected:**
'Connection to $DOCKER_HOST failed'  (due to step 4)

**Additional information you deem important (e.g. issue happens only occasionally):**
100% repeatable

**Comment by programmerq** [comment]
When your VPN disconnects, what sort of network level error do you get? I tried to simulate this by simply turning off my docker virtualbox VM, but I get the message you expected:

    $ docker cp index.html admiring_nobel:/usr/share/nginx/html/index.html
    Cannot connect to the Docker daemon. Is the docker daemon running on this host?

If I try to ping, I get a timeout:

    $ ping -c 1 192.168.99.100
    PING 192.168.99.100 (192.168.99.100): 56 data bytes
    Request timeout for icmp_seq 0
    --- 192.168.99.100 ping statistics ---
    1 packets transmitted, 0 packets received, 100.0% packet loss

A few minutes after I turn off the VM, the timeout turns into a "no route to host" on the ping, and I get 

    $docker cp index.html admiring_nobel:/usr/share/nginx/html/index.html
    An error occurred trying to connect: Put https://192.168.99.100:2376/v1.22/containers/admiring_nobel/archive?noOverwriteDirNonDir=true&path=%2Fusr%2Fshare%2Fnginx%2Fhtml: dial tcp 192.168.99.100:2376: connect: host is down

This suggests that you aren't necessarily getting a timeout nor a "no route to host" error.

**Comment by FireballDWF** [comment]
Have not been able to reproduce after upgrading to 1.10.3, so closing issue
