### ISSUE TITLE
docker default iptables rules not created on system startup/restart

### ISSUE THREAD

**Issue by delfuego** [docker/docker#21327]
Somewhere between docker 1.8 and 1.10.3, I've noticed that when I restart any of my Docker hosts (all Ubuntu 14.04 LTS x64), docker's iptables rules don't get created, leading to me having to wait until the system is fully up and then stopping and starting the docker daemon/service in order for them to be created properly.

For all the world, it feels like this is an issue with service startup order; the hosts all have `iptables` (obviously), but they also have `iptables-persistent` to restore things like the default-drop policy and the rules allowing SSH and the like. As I mentioned above, it used to not be a problem; on restart, the hosts would properly reload the saved iptables rules and docker wouldn't have any problem inserting/appending its own needed rules.

Here's one of the host's `/etc/iptables/rules.v4` files, which is representative of all of the hosts:

```
# more /etc/iptables/rules.v4
# Generated by iptables-save v1.4.21 on Thu Feb 18 13:32:57 2016
*nat
:PREROUTING ACCEPT [1:229]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [11:830]
:POSTROUTING ACCEPT [11:830]
:DOCKER - [0:0]
COMMIT
# Completed on Thu Feb 18 13:32:57 2016
# Generated by iptables-save v1.4.21 on Thu Feb 18 13:32:57 2016
*filter
:INPUT DROP [133:8290]
:FORWARD ACCEPT [874:804710]
:OUTPUT ACCEPT [458:64740]
:DOCKER - [0:0]
-A INPUT -i lo -j ACCEPT
-A INPUT -s [redacted]/24 -p icmp -m icmp --icmp-type 8 -m comment --comment "OIT subnet ping access" -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p tcp -m tcp --dport 2376 -j ACCEPT
-A INPUT -s [redacted]/32 -p tcp -m tcp --dport 7946 -m comment --comment "docker overlay networking" -j ACCEPT
-A INPUT -s [redacted]/32 -p udp -m udp --dport 7946 -m comment --comment "docker overlay networking" -j ACCEPT
-A INPUT -s [redacted]/32 -p udp -m udp --dport 4789 -m comment --comment "docker overlay networking" -j ACCEPT
-A INPUT -s [redacted]/32 -p tcp -m tcp --dport 7946 -m comment --comment "docker overlay networking" -j ACCEPT
-A INPUT -s [redacted]/32 -p udp -m udp --dport 7946 -m comment --comment "docker overlay networking" -j ACCEPT
-A INPUT -s [redacted]/32 -p udp -m udp --dport 4789 -m comment --comment "docker overlay networking" -j ACCEPT
COMMIT
# Completed on Thu Feb 18 13:32:57 2016
```

```
$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
```

```
$ docker info
Containers: 12
 Running: 8
 Paused: 0
 Stopped: 4
Images: 315
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /data/docker/aufs
 Backing Filesystem: extfs
 Dirs: 419
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: host overlay bridge null
Kernel Version: 3.13.0-83-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.861 GiB
Name: FR-S-CCR-DOCK1
ID: U6GD:4OTY:KDJL:5STF:P4QH:RTIU:Q7KZ:WMUP:KT3P:P2KL:7EXI:PA6X
Cluster store: consul://[redacted]:8500
Cluster advertise: [redacted]:2376
```

Docker host environment: Ubuntu 14.04.4 LTS running on vSphere virtualized infrastructure, `Linux FR-S-CCR-DOCK1 3.13.0-83-generic #127-Ubuntu SMP Fri Mar 11 00:25:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by phemmer** [comment]
Sounds like a simple race condition between the start of the `iptables-persistent` service and the `docker` service.
Since it looks like you're using Ubuntu 14.04, I'd try adding the following to the upstart config for docker:

    start on started iptables-persistent

That should result in upstart not trying to start `docker` until `iptables-persistent` is up.

**Comment by delfuego** [comment]
Perfect. (Although since `iptables-persistent` isn't managed by upstart, I had to add signaling to the `iptables-persistent` init.d script that let upstart know it was finished; the details are well-documented here: https://groups.google.com/d/msg/docker-dev/4SfOwCOmw-E/vo0tRCL2BgAJ)
