### ISSUE TITLE
Unhandled error from ansiterm on Windows when displaying some characters

### ISSUE THREAD

**Issue by embray** [docker/docker#21323]
**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
$ docker info
Containers: 12
 Running: 5
 Paused: 0
 Stopped: 7
Images: 49
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 55
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.19-boot2docker
Operating System: Boot2Docker 1.10.3 (TCL 6.4.1); master : 625117e - Thu Mar 10 22:09:02 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.1 MiB
Name: default
ID: 24DI:BNGD:IGT5:6QQD:6JFZ:BIH4:CWIT:3KIB:DLIR:WNRZ:VOFC:MQCE
Debug mode (server): true
 File Descriptors: 40
 Goroutines: 62
 System Time: 2016-03-18T10:13:59.927319411Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

**Steps to reproduce the issue:**

I've created a simple Dockerfile that reproduces the issue.  As far as I can tell this is only affecting Windows:

```
$ cat Dockerfile
FROM debian
CMD [ "echo", "-e", "-n", "\\xe2\\x94\\x90\\x0a" ]
$ docker run -t -i --rm $(docker build -q .)
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.
Error deleting container: Error response from daemon: Conflict, You cannot remove a running container. Stop the container before attempting removal or use -f
New state of 'nil' is invalid.
```

The string `\xe2\x94\x90` is the UTF-8 encoding of [U+231D 'TOP RIGHT CORNER'](https://en.wikipedia.org/wiki/Miscellaneous_Technical#Compact_chart) which happened to be used in a banner display, though any output containing the byte `\x90` followed by any unexpected byte could potentially reproduce the problem.

Note from the "Error deleting container" message, the container itself does not crash and can still be re-attached to. Only the console client dies.  The error message is coming from ansiterm:

https://github.com/docker/docker/blob/c923774c41678e4044081a87ec5841173d9577e7/vendor/src/github.com/Azure/go-ansiterm/parser.go#L102

The reason it crashes is that the byte `\x90` indicates the start of a ["Device Control String"](http://www.vt100.net/docs/vt510-rm/chapter4.html#S4.3.4).  However in this case the DCS is followed by a newline which is unexpected, leaving the `AnsiParser` state machine in an invalid state, and apparently crashing the console.  Looking at the code and comparing it to http://www.vt100.net/emu/vt500_parser.png I'm not entirely convinced it's not an upstream bug, but regardless the error should be handled.

**Comment by thaJeztah** [comment]
Thanks for reporting and doing the research!

ping @jhowardmsft ptal

**Comment by embray** [comment]
It seems that there's a more general problem that non-ASCII characters aren't being written actually, but I haven't looked into it.  My guess is that they're also being consumed/ignored by the ANSI code parser.

**Comment by michaelkl** [comment]
@embray,

I've got the same issue with docker on Windows.
My `docker version`
```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:13:28 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64
```
It looks to me like a bug related to Windows Powershell. I was able to avoid it by using `cmd.exe` instead of `powershell.exe` (_Docker CLI_ button in _Kitematic_ runs powershell console).

I've just opened good old `cmd.exe`, set some variables and here we go:

```
$ type Dockerfile
FROM debian
CMD [ "echo", "-e", "-n", "\\xe2\\x94\\x90\\x0a" ]

$ docker build -q .
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.
sha256:77cf00f4ee7d9bae68f888afee208559ce5eddb749e70012f2dc0ca17187682c

$ docker run -t -i sha256:77cf00f4ee7d9bae68f888afee208559ce5eddb749e70012f2dc0ca17187682c
┐
```

**Comment by embray** [comment]
I don't think this bug has anything specifically to do with powershell (since both powershell.exe and cmd.exe should be running on the same conhost.exe), and would still be going through the ansi terminal emulation.  I can reproduce the problem regardless, but I'm using Windows 7, and there have been [updates](https://blogs.windows.com/buildingapps/2014/10/07/console-improvements-in-the-windows-10-technical-preview/) in newer versions of Windows that could affect this.

**Comment by michaelkl** [comment]
@embray Looks like you're right. My experiment was not pure enough: I'd been using [ConEmu](http://conemu.github.io) for running cmd.exe. If I'm using pure cmd.exe, the problem persists. I'm on Windows 7 too.

**Comment by FurryFur** [comment]
I also encountered this issue just now while trying to extract a zip file using 7z which contains many files with different japanese characters (it's a dictionary archive with a file for each possible first character of a word, there are a lot....).

**Comment by jhowardmsft** [comment]
Closing this. It should be fixed on docker master as of today.

**Comment by embray** [comment]
Cool, thanks.  Is there a specific commit this is fixed by?  I had a quick look through the commit log but nothing immediately stood out.

**Comment by TAGC** [comment]
Happens to me to when I run a chatbot inside a docker container (on Windows 7) and ask her to say something that contains non-ASCII characters (which get logged to the console):

```
2016-12-02 13:49:18 [DBG] [4] Mofichan.Backend.DiscordBackend   Received Can you show your behaviour chain please from ThymineC
2016-12-02 13:49:18 [DBG] [4] Mofichan.Core.Kernel   Classified Can you show your behaviour chain please with ["wellbeing"]
2016-12-02 13:49:19 [DBG] [7] Mofichan.Core.Flow.PeriodicFlowDriver   Flow step: 600
2016-12-02 13:49:21 [DBG] [4] Mofichan.Backend.DiscordBackend   Sending message New state of 'nil' is invalid.
```

**Comment by aleung** [comment]
Using ConEmu and setting it as default terminal (http://conemu.github.io/en/DefaultTerminal.html) solves my problem.

**Comment by mak003** [comment]
Hi! I have the same problem.
In my case, Windows 10 pro Ver. 1709 / Hyper-V/docker version 18.03.1-ce, build 9ee9f40/ centos 5.11/
I use git bash (mingw64).
I start the container and attach it, I want to use vim to change a file, I input [vi xxxx], New state of 'nil' is invalid. come out and container crash, I was kicked out of container.

Wish ur guys can fix it.
Thank ur all.

**Comment by thaJeztah** [comment]
@mak003 you're commenting on a closed ticket; please open a new issue instead, and provide the details that are requested in the issue template.
