### ISSUE TITLE
Remote API docs give incorrect example for creating a container with volumes

### ISSUE THREAD

**Issue by johnflavin** [docker/docker#21335]
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6
 Git commit:   20f81dd
 Built:        Sat Mar 12 04:07:44 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 2
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.19-boot2docker
Operating System: Boot2Docker 1.10.3 (TCL 6.4.1); master : 625117e - Thu Mar 10 22:09:02 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.1 MiB
Name: 1.10
ID: XS37:USGK:BVPL:4KKK:K6HN:EMVM:43DG:W2CY:JFO3:I6KX:OITN:E5F2
Debug mode (server): true
 File Descriptors: 10
 Goroutines: 21
 System Time: 2016-03-19T01:28:14.590797867Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VirtualBox

**Steps to reproduce the issue:**
1. Look up remote API docs to create a container (for example, [API version 1.22](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#create-a-container)).
2. Issue a `curl` call to create a container with mounts.
```
$ curl -XPOST -H 'Content-Type: application/json' http://${docker}/containers/create?name=foo -d '{"Image": "busybox", "Mounts": [{ "Destination": "/foo" }]}'
```
3. Inspect the container. See that no `Mounts` were created.
```
$ curl http://${docker}/containers/foo/json | jq '.Mounts'
[]
````
4. Ignore the docs, search on the issues, find #15908, specifically [this comment](https://github.com/docker/docker/issues/15908#issuecomment-137749134).
5. Create a container using the undocumented `Volumes` key.
```
$ curl -XPOST -H 'Content-Type: application/json' http://${docker}/containers/create?name=foo -d '{"Image": "busybox", "Volumes": { "/foo": {}}}'
```
6. Inspect the container. See that `Mounts` were created.
```
$ curl http://${docker}/containers/foo/json | jq '.Mounts'
[  
    {
        "Name": "ee6a4252b747356d74e71c952401420af00dbfc704b9d560000dec0df5ea095b",
        "Source": "/mnt/sda1/var/lib/docker/volumes/ee6a4252b747356d74e71c952401420af00dbfc704b9d560000dec0df5ea095b/_data",
        "Destination": "/foo",
        "Driver": "local",
        "Mode": "",
        "RW": true,
        "Propagation": ""
    }
]
```

**Describe the results you received:**
Remote API docs describe an incorrect way to create a container with volumes. And the correct way is inconsistent in that the deprecated `"Volumes"` key must be used to create containers with volumes, but the newer `"Mounts"` key is used to deliver information on a container inspect.

**Describe the results you expected:**
Either the Remote API docs would correctly describe how to create a container with volumes, or the actual API would be fixed to be consistent between creating/inspecting.

**Additional information you deem important (e.g. issue happens only occasionally):**
The example in the docs is incorrect in every version going back to when the `Mounts` key was introduced in API 1.20.

**Comment by yongtang** [comment]
@johnflavin I created a pull request #21712 to cover the issue raised here. Let me know if there are any issues.
