### ISSUE TITLE
Logging driver plugin proposal

### ISSUE THREAD

**Issue by subfuzion** [docker/docker#21339]
Rather than add every conceivable logging driver possible to the engine (see #21271), provide a logging driver that lets you specify an image to run with supplied driver configuration options. Logs could be streamed to this container, which would be responsible for implementing whatever logic necessary as part of shipping logs to some other destination.

**Comment by thaJeztah** [comment]
Thanks for suggesting @subfuzion, actually, there's already an issue opened for this; https://github.com/docker/docker/issues/18604

I'll close this one, please continue the discussion on https://github.com/docker/docker/issues/18604

**Comment by subfuzion** [comment]
Wow, I need to work on my search-fu. I somehow missed that issue, but thanks.

**Comment by thaJeztah** [comment]
Haha, no worries, GitHub search is the worst, and we have a lot of tickets/PRs. I just happened to know where to search for

**Comment by subfuzion** [comment]
Thanks, @thaJeztah. I've gone ahead and submitted my proposal [here](https://github.com/docker/docker/issues/18604#issuecomment-198786889) for the existing issue you suggested. Appreciate the link. :+1:
