### ISSUE TITLE
Making Docker I/O performant when using container STDIN and STDOUT

### ISSUE THREAD

**Issue by dunk** [docker/docker#21346]
I work in the field of bioinformatics and like many of my fellow practitioners I have a workload which requires data to be piped from one process to another, sometimes through several steps. While it would be wonderful if the bioinformatics community at large could do something smarter like shared memory, sadly the extant (and very large) toolset does not facilitate this. I would like to, as per standard docker practice, wrap single commands in single docker containers and pipe the data between these. I do not want to have to put all commands into one large container as beyond violating the underlying philosophy these containers become big-balls-of-mud exceptionally quickly. Further, I do not see putting the commands in a particular pipeline into a particular container as a viable option either; this is because many different pipelines share common commands, and so the setup of these commands would be duplicated across those containers. While it is possible to do some sort of manual Dockerfile generation, stitching together other Dockerfiles with individual components, this would be a brittle approach and, to be honest, a problem much better solved by a configuration manager. I have considered a "hack", whereby I mount a common volume and set up named pipes in place of the actual pipes. However, there is a *lot* of programmatic overhead in doing this - not least writing a shell parser in order to work out where the pipes are, and the setup/cleanup of those fifos before/after the scripts run.

I have included some timings below, which were performed on a completely unloaded server. 2.5 seconds vs 6 minutes.

```
$ ls -lh
-rw-rw-r-- 1 dunk dunk 3.0G Mar 19 22:17 Homo_sapiens.GRCh37.75.dna.primary_assembly.fa
```
```
time cat Homo_sapiens.GRCh37.75.dna.primary_assembly.fa > test1
real = 0m2.544s, user = 0m0.004s, sys = 0m2.537s
```
```
time cat Homo_sapiens.GRCh37.75.dna.primary_assembly.fa | docker run -i --rm ubuntu:trusty bash -c 'cat' > test2
real = 5m51.383s, user = 0m1.783s, sys = 0m16.789s
```

**Comment by mitchcapper** [comment]
Would not a somewhat viable option be to instead use network communication which is baked into docker? It has the ability of not requiring taking over the STDIN/STDOUT streams, a more clear interface, completely avoids any disk IO and is highly performant.   If you wanted a cheap hack you could even emulate what you are wanting right now using netcat to pipe right into your existing processes.

**Comment by dunk** [comment]
An update: Thanks to the advice of @cpuguy83 I got an performance improvement to somewhere about the 10 second mark by using --log-driver=none. This prevents docker from doing a whole bunch of extra processing on your data (presumably primarily to STDOUT). Originally I was worried about data going via the HTTP interface, but of course this is only a problem on a mac, as the data has to be sent inside the VM. On linux, it goes straight to the local docker socket instead. I checked how long this would take going via the network stack instead (before finding the --log-driver=none fix), doing the following:

```
nc -l -p 7002 > /dev/null
docker run -i --rm --net=host --log-driver=none ubuntu:trusty bash -c 'nc -l -p 7001 | nc 172.17.0.1 7002'
time cat genome.fa | nc 127.0.0.1 7001
```

This is slightly less performant than the direct socket approach, as one might expect with  the overhead of navigating the TCP stack.

I think that it would be great to find out where the remaining performance bottlenecks are, and potentially be able to pipe in and out of containers with no overhead at all.

**Comment by thaJeztah** [comment]
We cannot really optimize this further, because the docker client and daemon can be running on a different host, so all the data that's piped will be sent over the API. As a possible solution, you could consider using bind-mounts for sharing data between the host and the container.

I'll close this issue, but feel free to comment after

**Comment by cpuguy83** [comment]
Also note we did improve perf quite a bit here by reducing allocations in the relevant code.
