### ISSUE TITLE
disk space not release after rm -rf & reboot

### ISSUE THREAD

**Issue by polym** [docker/docker#21348]
**Output of `docker version`:**

```
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:18:46 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:18:46 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 10
 Running: 0
 Paused: 0
 Stopped: 10
Images: 11
Server Version: 1.10.1
Storage Driver: devicemapper
 Pool Name: docker-8:3-8126468-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 43.88 GB
 Data Space Total: 107.4 GB
 Data Space Available: 63.5 GB
 Metadata Space Used: 26.94 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.121 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /disk/ssd1/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /disk/ssd1/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.10.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 46.98 GiB
Name: DOCKER-46
ID: ZYHB:ZYPS:XAIX:HGIR:LBS6:7XNA:PY2M:7F5K:MG3V:T2SD:WQG2:2S53
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Linux DOCKER-46 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

/usr/bin/docker daemon -g /disk/ssd1/docker -H tcp://127.0.0.1:2375 -H fd://

**what happened**
When Docker API hang up，I found devicemapper's data space was used up, little free memory is left, and `strace docker ps` was waiting for the docker socket. Then I stoped docker service difficultly, `rm -rf /disk/ssd1/docker`, and `reboot`. After system started, `df -h`:

```
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       9.8G  8.8G  415M  96% /
devtmpfs         24G     0   24G   0% /dev
tmpfs            24G     0   24G   0% /dev/shm
tmpfs            24G   17M   24G   1% /run
tmpfs            24G     0   24G   0% /sys/fs/cgroup
/dev/sda3       258G   42G  203G  17% /disk/ssd1
tmpfs           4.7G     0  4.7G   0% /run/user/0
```

It's very funny .....

![image](https://cloud.githubusercontent.com/assets/2860926/13902393/0243b76a-ee81-11e5-8423-1e5c2d1da924.png)

**Comment by polym** [comment]
du -sk /*
```
0	/bin
130572	/boot
0	/dev
43268052	/disk
57828	/etc
4	/home
0	/lib
0	/lib64
16	/lost+found
4	/media
4	/mnt
3680	/opt
du: cannot access '/proc/17172/task/17172/fd/4': No such file or directory
du: cannot access '/proc/17172/task/17172/fdinfo/4': No such file or directory
du: cannot access '/proc/17172/fd/4': No such file or directory
du: cannot access '/proc/17172/fdinfo/4': No such file or directory
0	/proc
5372	/root
17256	/run
0	/sbin
4	/srv
0	/sys
92	/tmp
1079512	/usr
66408	/var
```

**Comment by AndrewGuenther** [comment]
Are you sure that your `rm -rf` call succeeded? If the daemon wasn't running then I'm not sure if this is a Docker problem...

**Comment by drucci** [comment]
I am experiencing the same issue. docker daemon was running when I deleted. After reboot I still see the disk as full.

**Comment by cpuguy83** [comment]
I believe you need to run `fstrim` after deleting files when using devicemapper in order to reclaim space.

**Comment by drucci** [comment]
@cpuguy83  While that did not work for me, it did send me on the path to eventually fixing this. Thank you!

Some notes:
`fstrim` would say operation not permitted for discard or something along those lines. This was because my EC2 Instances storage volume type was gp2.

I then learned of `zerofree`, but this tool is only meant for ext2/3 file systems. I was on xfs.

Finally came accross xfs_repair

`xfs_repair -f /dev/xvdf1 `

While the above doesn't reclaim the space, it does put all unreachable data into lost+found so you can actually delete it.

**Comment by thaJeztah** [comment]
@polym does that solve your case as well? ^^

**Comment by polym** [comment]
I walked around the problem by changing devicemapper to overlayfs.

**Comment by thaJeztah** [comment]
In that case, let me close this issue, thanks @polym
