### ISSUE TITLE
docker run dns configuration option should be able to take a container name

### ISSUE THREAD

**Issue by stevenboyd** [docker/docker#21352]
I have a container running (lets name it dns_server) that is running a dns server and exposes port 53.

I have another server (lets name it app) that wants to use the dns_server container as it's dns server. It would be nice if I could pass in a container name to the docker run dns parameter. Something like this:

`docker run -d --name app --link dns_server --dns dns_server my-app`

Currently I have to do

``docker run -d --name app --link dns_server --dns `docker inspect  --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' dns_server` my-app``

However this will not update if the dns_server's ip changes.

**Comment by sanimej** [comment]
@stevenboyd From 1.10 docker provides the --ip option for containers on user defined networks to assign a fixed IP to the container. You can use this to assign an IP to the dns_server that doesn't change on restarts.

**Comment by thaJeztah** [comment]
@stevenboyd do you think that resolves your issue? I understand your use-case, but adding logic to resolve the DNS's IP-address (and automatically update it) may add a lot of complexity, so not sure we should do so

**Comment by stevenboyd** [comment]
I think the --ip workaround is sufficient. While being able to assign the dns parameter to a container is still  a nice to have, I can understand that it would be complex to pull off.

**Comment by thaJeztah** [comment]
Yes, I agree it would definitely be nice, just don't think we should add the complexity.

I'll close this issue, but thanks so much for suggesting, it's appreciated. And if we ever find an easy way to implement it, I'm definitely +1 :innocent:
