### ISSUE TITLE
Executing script results in "--ignore invalid command name"

### ISSUE THREAD

**Issue by WeirdCircumstances** [docker/docker#21350]
**Output of `docker version`: **

```
Docker version 1.10.3, build 20f81dd
```
**Output of `docker info`:**

```
Docker version 1.10.3, build 20f81dd
[ben@archserver dokr]$ docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 4
Server Version: 1.10.3
Storage Driver: btrfs
 Build Version: Btrfs v4.4.1
 Library Version: 101
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.5-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 988.1 MiB
Name: archserver
ID: S7EZ:JHMO:HGZW:LLNM:3BFW:7EAU:ZA6U:XN62:IYIM:PQIU:YRWH:YA7W
Username: docr
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. execute script
`[user@archserver dokr]$ ./mkimage-arch.sh 
spawn pacstrap -C ./mkimage-arch-pacman.conf -c -d -G -i /var/tmp/rootfs-archlinux-uxOLDriSFm base haveged
invalid command name "--ignore"
    while executing
"--ignore cryptsetup,device-mapper,dhcpcd,iproute2,jfsutils,linux,lvm2,man-db,man-pages,mdadm,nano,netctl,openresolv,pciutils,pcmciautils,reiserfsprogs..."
`

**Comment by thaJeztah** [comment]
Probably this is related to the version of pacstrap used and the script may need to be updated. Arch linux can be a running target, as they update quite frequently, but if you found a solution, please open a pull request to update the script
