### ISSUE TITLE
"docker attach" not working in Powershell ISE (but regular PS) while Enter-PSSession working fine

### ISSUE THREAD

**Issue by mathiasconradt** [docker/docker#21368]
As discussed on here: https://github.com/Microsoft/Virtualization-Documentation/issues/156#issuecomment-199363112:

It's not clear why Docker containers cannot be attached to via Powershell ISE but only in Powershell, while Windows containers can and should be mentioned on https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/manage_docker.

With "attach" I mean "`docker attach`" and "`Enter-PSSession`", attaching to a container session.

I get these errors when trying to attach to a docker container via Powershell ISE: http://snag.gy/EehYI.jpg

Host System: `Windows Server 2016 TP4`
Docker Version: `Docker version 1.10.0-dev, build 18c9fe0`

@StefanScherer replied:

> The error shows something with docker/pkg/term/windows/ansi_reader.go - perhaps a problem with the different kind of terminal in ISE instead of vanilla PowerShell?
> Seems to me like an error in docker.exe client.
> 

@PatrickLang

> Thanks for bringing this up. Can you open an issue on the main Docker project for this? We should discuss the impact & workarounds there with the larger community there. 
> https://github.com/docker/docker/issues/

**Comment by LK4D4** [comment]
Closed by #22951
