### ISSUE TITLE
Race condition encountered during docker overlay network creation

### ISSUE THREAD

**Issue by cookieisaac** [docker/docker#21371]
**Output of `docker version`:**

```
~]# docker version
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 16:16:33 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 16:16:33 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
~]# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 1.10.2
Storage Driver: devicemapper
 Pool Name: docker-253:0-1444421-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.479 GB
 Data Space Total: 107.4 GB
 Data Space Available: 21.8 GB
 Metadata Space Used: 2.74 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host overlay bridge
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.703 GiB
Name: asc-16
ID: TLMN:J23V:XVHY:KPFT:QSXD:BK56:IS5T:5R72:URGE:SJFO:6OH5:KKZR
Http Proxy: http://<my-proxy>:3128/
Https Proxy: http://<my-proxy>:3128/
WARNING: bridge-nf-call-ip6tables is disabled
Cluster store: consul://127.0.0.1:8500
Cluster advertise: <neighbor IP>:2375
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Start two physical machines or VMs `HostA` and `HostB` with docker daemon and consul properly configured so that I can run `docker network create -d overlay testnw` successfully
2. Develop following executable `Master.sh`
```
#!/bin/bash
ssh HostA docker network create -d overlay sharednet
ssh HostB docker network create -d overlay sharednet
```
3.Run `./Master.sh`

**Describe the results you received:**
Two overlay networks with the name sharednet are created, indicating docker daemon was out of sync.
```
[HostA]# docker network ls
NETWORK ID          NAME                 DRIVER
ad492bba9efa        sharednet            overlay
ba53d4e7b739        sharednet            overlay

[HostB]# docker network ls
NETWORK ID          NAME                 DRIVER
ad492bba9efa        sharednet            overlay
ba53d4e7b739        sharednet            overlay
```

**Describe the results you expected:**
Only one of host should be able to create the network and the other host should fail with error response from daemon
```
[HostB]# docker network ls
68994f95cd67        testnw               overlay
[HostB]# docker network create -d overlay testnw
Error response from daemon: network with name testnw already exists
```

**Additional information you deem important (e.g. issue happens only occasionally):**
The problem described is the backbone of the following use case.
I have a python script talking only to docker daemon to monitor and orchestrate container on the local machine. On each machine in my cluster, I have a copy of this python script which is invoked by a master daemon that is unaware of what the script is doing. 

I want to make sure `Container A` on `Host A` can communicate with `Container B` on `Host B` via network `sharednet`. The script will first check with local docker daemon and will create the network if not exists. That's when I noticed that two networks with the same name are created.

I had conceptualized `docker daemon + consul` as one large docker cluster engine, and assumed the network information will be synced at real time. (But it seems that there are  delays when docker daemon propagates information to each other and docker daemons are not always in sync. From the logs, I found one network was created on HostA, and three seconds later, a network with the same name got created on a different Host)

**Comment by thaJeztah** [comment]
I think this is a duplicate of https://github.com/docker/docker/issues/20648, or at least closely related. If you agree, can you close this one and continue the discussion on https://github.com/docker/docker/issues/20648?

**Comment by cookieisaac** [comment]
Thanks for the pointer @thaJeztah . I will close this ticket.
