### ISSUE TITLE
[doc] include more inforation about seccomp?

### ISSUE THREAD

**Issue by frioux** [docker/docker#21378]
Loving the new seccomp BPF stuff; thanks for making it more "within reach" for typical users.

[I wrote a little thing to allow ptrace in my containers](https://blog.afoolishmanifesto.com/posts/how-to-enable-ptrace-in-docker-1.10/) and while it worked I started getting these warnings:

```
2016/03/21 22:05:18 Error resolving syscall name copy_file_range: could not resolve name to syscall - ignoring syscall.
2016/03/21 22:05:18 Error resolving syscall name mlock2: could not resolve name to syscall - ignoring syscall.
```

Not a huge deal, but I figured out I would go ahead and automate the exclusion of system calls that are "unknown."  After scripting that there were five other system calls that were excluded:

1. recv - this is, as far as I understand the exact same as recvfrom, seems safe to leave out
2. send - same as recv, but sendto
3. cacheflush - this is for a non-x86 arch (MIPS) which I'd be surprised if Go even worked on, but either way also seems safe (for me, but maybe not docker proper) to leave out
4. breakpoint - I have no manpage for this; perhaps it is the same as 3 but undocumented?
5. set_tls - same situation as 4.

Honestly I am not super sure where to go from here.  Some documentation on why all of these are included might be nice.  The weirder thing to me was that I got a warning for mlock2 and copy_file_range but not cacheflush, breakpoint, and set_tls.

Sorry to have such a vague report, but I figured more information can't hurt.

**Comment by justincormack** [comment]
`copy_file_range` and `mlock2` are new, you need libseccomp 2.3.0 to know about them, and a 4.4 or so kernel to actually have these working. Older versions will not know about them.

`breakpoint` and `set_tls` are only on non-x86 architectures, yes.

`send` and `recv` are old syscalls, I think they do not exist on "modern" architectures like x86_64 as they are trivially implemented using `sendto`, `recvfrom` - they correspond to `send(3)` and `recv(3)` in libc but as direct syscalls. They do exist on x86 32 bit still though, and maybe some other architectures. People do run 32 bit code on docker quite a bit, so it might use these.

The warnings are deliberately ignored in the default profile, as it is somewhat easier than having lots of architecture conditionals, and we do support running 32 bit code.

Hope that helps.

**Comment by frioux** [comment]
Thanks!  Very helpful
