### ISSUE TITLE
Docker build freezes and removing build container fail with mount still active

### ISSUE THREAD

**Issue by kuruoujou** [docker/docker#21379]
When I build any Dockerfile, after skipping any steps it has cached, the build does not complete. It appears to hang after creating a container to perform a step of the build. I assume it is having issues deleting the container, but I am not certain - this is just an assumption based on the fact that I also cannot delete the container. Here are my details:

**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:59:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:59:07 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 27
 Running: 18
 Paused: 0
 Stopped: 9
Images: 602
Server Version: 1.10.3
Storage Driver: btrfs
 Build Version: Btrfs v4.0
 Library Version: 101
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.2.0-34-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 7.762 GiB
Name: chiyuki
ID: Z6EK:6D4P:3EH2:KI3L:3WDQ:WYPX:53XC:AXHF:6IXW:Y7EN:54FQ:3PMC

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical machine running Ubuntu 15.10

**Steps to reproduce the issue:**
1. Run `docker build -t blah/blah .`
2. After several minutes, sometimes upward of 30, with nothing happening after cached images are loaded, ^C the build.
3. Run `docker stop [build container] && docker rm [build container]`

**Describe the results you received:**
Build does not complete, and removing container yields error similar to:

    Failed to remove container (thirsty_franklin): Error response from daemon: Driver btrfs failed to remove root filesystem 5e8dca4cddda5a77d81fcb34b8bdec33bec2889dccf74956763517127c587563: mount still active

**Describe the results you expected:**
Build successfully completing, and removing containers working.

**Additional information you deem important (e.g. issue happens only occasionally):**
This issue happens consistently, but only recently. It started after an upgrade from Ubuntu 14.10 and docker 1.8.3. There was not an intermediate step to docker 1.9.1 or Ubuntu 15.04. Additionally, I am using the btrfs driver, though I never selected it myself - it appears that was selected automatically.

**Comment by npcode** [comment]
Same error occurs occasionaly to me after a container stopped accidently, with docker v1.11.2.

**Comment by dorflex150mg** [comment]
Same problem here.

**Comment by cpuguy83** [comment]
Please try on 1.12.
Actually this error is never returned anymore, so may be a different error at least.

**Comment by cpuguy83** [comment]
Actually, I'm going to close this because the error in question is no longer possible since 1.12.
Please open a new issue if you run into problems on 1.12

Thanks!
