### ISSUE TITLE
docker 1.10 migration issue

### ISSUE THREAD

**Issue by abilash222** [docker/docker#21391]
i am getting error when trying to run the migration container for docker 1.10 version

docker run --privileged --rm -v /var/lib/docker:/var/lib/docker docker/v1.10-migrator 

time="2016-03-22T08:02:53Z" level=debug msg="layer eff9922ad47c3fa9d350b7959f08f28172624eadec8e62ba1febf8e55ee259d9 took 0.01 seconds" 
time="2016-03-22T08:02:53Z" level=debug msg="devmapper: activateDeviceIfNeeded(d84fd19c22ca9e54b41d332b01ee3d7067624f2a9271acc707f779d2bdf0ade7)" 
time="2016-03-22T08:02:53Z" level=error msg="could not calculate checksum for \"d84fd19c22ca9e54b41d332b01ee3d7067624f2a9271acc707f779d2bdf0ade7\", \"Can't create snap device: devmapper: Error activating devmapper device for 'd84fd19c22ca9e54b41d332b01ee3d7067624f2a9271acc707f779d2bdf0ade7': devicemapper: Error running deviceCreate (ActivateDevice) dm_task_run failed\"" 

**Output of `docker version`:**

Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): ba1f6c3/1.6.2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): ba1f6c3/1.6.2
OS/Arch (server): linux/amd64
(paste your output here)
```
**Output of `docker info`:**

```

Containers: 0
Images: 33
Storage Driver: devicemapper
 Pool Name: docker-202:2-1705646-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.412 GB
 Data Space Total: 107.4 GB
 Data Space Available: 50.84 GB
 Metadata Space Used: 2.204 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Kernel Version: 3.10.0-327.10.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 3.451 GiB
Name: zdocker-test
ID: P36S:DFNJ:VGWR:4P72:5PZS:2NII:FI6D:YSA6:YRFF:BV74:TPYX:P6MD
(paste your output here)
**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. install docker 1.6.2 in centos 7 and pull any image
2. execute docker run --privileged --rm -v /var/lib/docker:/var/lib/docker docker/v1.10-migrator
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
thanks for reporting @abilash222 could you reopen this issue in the issue tracker for the migrator? You can find the issue tracker here; https://github.com/docker/v1.10-migrator/issues

I'll close this issue here, because the migrator is a separate project, but feel free to comment here after I've closed
