### ISSUE TITLE
Docker daemon doesn' start on CentOS 7.2.1511

### ISSUE THREAD

**Issue by jahantech** [docker/docker#21392]
**Output of `docker version`:**

```
Client:
 Version:      1.8.2-el7.centos
 API version:  1.20
 Package Version: docker-1.8.2-10.el7.centos.x86_64
 Go version:   go1.4.2
 Git commit:   a01dc02/1.8.2
 Built:
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
```

**Output of `docker info`:**

```
[root@masterserver ~]# docker info
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VPS

**Steps to reproduce the issue:**
1. systemctl start docker
2. docker -d

**Describe the results you received:**
```
[root@masterserver ~]# systemctl start docker
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
[root@masterserver ~]# docker -d
Warning: '-d' is deprecated, it will be removed soon. See usage.
WARN[0000] please use 'docker daemon' instead.
WARN[0000] You are running linux kernel version 2.6.32-042stab111.12, which might be unstable running docker. Please upgrade your kernel to 3.10.0.
ERRO[0000] 'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded.
INFO[0000] Option DefaultDriver: bridge
INFO[0000] Option DefaultNetwork: bridge
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
WARN[0000] Running modprobe bridge nf_nat br_netfilter failed with message: , error: exit status 1
INFO[0000] Firewalld running: true
FATA[0000] Error starting daemon: Error initializing network controller: Error creating default "bridge" network: inappropriate ioctl for device
````
**Describe the results you expected:**
I would expect the docker daemon to run. I don't see this issue on ubuntu machines.

**Additional information you deem important (e.g. issue happens only occasionally):**
Permanent issue.

**Comment by phemmer** [comment]
The cause is in the output you provided:

    WARN[0000] You are running linux kernel version 2.6.32-042stab111.12, which might be unstable running docker. Please upgrade your kernel to 3.10.0.

Docs also mention this: https://docs.docker.com/engine/installation/linux/centos/

Also, CentOS 7 comes with kernel 3.10, so you're running an unsupported kernel on the OS as well. (this can cause incompatibilities between userspace and kernel space)

**Comment by jahantech** [comment]
I think this issue can be closed now. I will update the kernel on my VPS. Thank you for clarification.
