### ISSUE TITLE
Unable to pass forward slashes  in enviornment varialbe to docker host from windows

### ISSUE THREAD

**Issue by plastikman** [docker/docker#21409]
**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
$ docker info
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 60
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 55
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.18-boot2docker
Operating System: Boot2Docker 1.10.2 (TCL 6.4.1); master : 611be10 - Mon Feb 22 22:47:06 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 995.7 MiB
Name: default
ID: BBNJ:XXMN:GT3F:ZNT5:JDNO:WUSK:2YUF:JKF2:LPTN:4UXC:RRLN:2P7W
Debug mode (server): true
 File Descriptors: 30
 Goroutines: 62
 System Time: 2016-03-22T21:34:24.999178606Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: movotodeploy
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox


```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. start docker container with an environment variable with a url in it ex: -e "APP_URL=http://foo.com"
2. Check output of env when you are in the container

**Describe the results you received:**
the output of the enviornment is APP_URL=http:\foo.com

**Describe the results you expected:**

The expected output shuold be APP_URL=http://foo.com

**Additional information you deem important (e.g. issue happens only occasionally):**

This ONLY happens when you start the container with the mingw64 bash shell on windows.

if I connect directly to the boot2docker host  via virtualbox and pass the variable via bash on the docker host the variable is passed as expected.

**Comment by HackToday** [comment]
is it mingw64 bash shell  issue ? Have you checked with them ?

**Comment by plastikman** [comment]
I am not sure if it is only an issue with the mingw64 bash shell, I can tell you that the only time I see this issue is when I pass 'docker run -e "BAR=http://foo.com" xxxxxxxx ' through the "Docker Quickstart Terminal"

**Comment by thaJeztah** [comment]
Yes, I think this is mingw64 trying to be smart; I think you can add a double at the start of the string (or the value) `//` to prevent this from happening. I'm not on Windows, so it may need some experimenting

see http://www.mingw.org/wiki/Posix_path_conversion
http://stackoverflow.com/questions/7250130/how-to-stop-mingw-and-msys-from-mangling-path-names-given-at-the-command-line

**Comment by jhowardmsft** [comment]
Closing - this appears to be a mingw escaping issue rather than a docker issue.
