### ISSUE TITLE
Proposal - Add label filters for volume

### ISSUE THREAD

**Issue by HackToday** [docker/docker#21416]
This is the request from the new change of 
https://github.com/docker/docker/pull/21270  which added label for volume

**Comment by HackToday** [comment]
#dibs

**Comment by HackToday** [comment]
ping @thaJeztah  and @vdemeester  Let me know WDYT.  Thanks

**Comment by thaJeztah** [comment]
Sounds good to me :+1:

**Comment by vdemeester** [comment]
@HackToday Sounds good to me, go ahead :wink:

**Comment by crosbymichael** [comment]
This has been fixed by #25628
