### ISSUE TITLE
about docker's embedded dns

### ISSUE THREAD

**Issue by bonafideyan** [docker/docker#21426]
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:38:58 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:38:58 2016
 OS/Arch:      linux/amd64

Containers: 16
 Running: 13
 Paused: 0
 Stopped: 3
Images: 267
Server Version: 1.10.3
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.508 GiB
Name: ryan
ID: 4LTB:7HQM:JNOG:6F4P:3DFG:MIOR:QI4I:MDQO:SWOS:INAG:YOU7:RWVH
WARNING: No swap limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

physical,debian,jessie

1. start two container with the same bridge, such as with the option --net=gt
2. got one's ip, then in other container, edit my attachment java source with the ip
3. compile and excute it

i saw the one from docker dns have a network name suffix
i expect got the hostname without network name

(in some app, such as hbase,  will compare local hostname with what the peer seen, if not the same, it exit)

for better format about this, read below.
(attachment dont support a file with extension name .java, so i will paste it sometimes.)

**Comment by bonafideyan** [comment]
docker 1.10.3
debian jessie

NOTICE:  this is NOT a hbase bug, it DOES from docker. read continue...

"2016-03-23 09:14:03,928 ERROR [regionserver/r1/172.18.0.11:16020] regionserver.HRegionServer: **Master passed us a different hostname to use; was=r1, but now=r1.gt**"

(omit ...)

root@mr:/opt/hbase/logs# java a
**r1.gt
mr**
root@mr:/opt/hbase/logs# more a.java 
```
import java.net.*;
public class a {
public static void main(String[] args) throws Exception {
byte[] bs = new byte[] { (byte)172,(byte)18,(byte)0,(byte)11 };
String s = java.net.InetAddress.getByAddress(bs).getHostName();
System.out.println(s);
String s1 = java.net.InetAddress.getLocalHost().getHostName();
System.out.println(s1);
}
}
```



what?
the app(hbase) have file node(each live in its container), named mr, r1..., when r1 request the mr, mr return r1 its hostname by lookup the docker's dns, so r1 have two different hostname, one got from getLocalHost().getHostName(), the other got from mr which from docker's dns.


# note: if i name the host as r1.gt, i guess mr lookup and got the result is r1.gt.gt

> 
docker run -dit  --name r1  -h r1  --net=gt  -e HBASE_MASTER=mr  -e HBASE_BACKUP_MASTER=bm  -e HBASE_REGIONSERVER1=r1  -e HBASE_REGIONSERVER2=r2  -e HBASE_REGIONSERVER3=r3  -e HBASES_PASSWORD=123456  -e HDFS_SITE=nn:8020  -e ZK_HOSTS=zk1,zk2,zk3 ryan/hbases

**Comment by bonafideyan** [comment]
import java.net.*;
public class a {
public static void main(String[] args) throws Exception {
byte[] bs = new byte[] { (byte)172,(byte)18,(byte)0,(byte)11 };
String s = java.net.InetAddress.getByAddress(bs).getHostName();
System.out.println(s);
String s1 = java.net.InetAddress.getLocalHost().getHostName();
System.out.println(s1);
}
}

**Comment by sanimej** [comment]
This is the expected behavior currently. service names in docker (from --name) are resolved in the context of the networks the container is connected to. In your case since the network name is gt, the IP to name mapping is r1.gt.

**Comment by bonafideyan** [comment]
ok, 
`docker run -dit --name r1 -h r1.gt --net=gt ...`
works. 
thank you for your reply.
