### ISSUE TITLE
Proposal: Adding Live Migration of Docker by DFS

### ISSUE THREAD

**Issue by sktzwhj** [docker/docker#21427]
I am planning to replace the unionfs of docker with a distributed file system(DFS) which also provide incremental snapshot feature. Is that worthwhile? 
Because in my understanding, if docker could run on a DFS, then when live migration, the majority of data need not to be transferred between hosts. We can just read the data from DFS.

**Comment by Lennie** [comment]
Sounds to me like you are suggesting a new storagedriver which handles container/images storage.

But most of the data of a container should be stored in a volume, not in the container itself. And thus the bulk of the data would be handled by the volumedriver/-plugin (see: https://docs.docker.com/engine/extend/plugins/ ), not the storagedriver (which does overlayfs), right ? In that case most of the parts of a the container itself should be pulled as an image.

**Comment by thaJeztah** [comment]
We have not intentions of adding this as a feature, but you can implement a custom graph driver as a plugin, or try using nfs (which works in some cases), or use the suggestions @Lennie provided
