### ISSUE TITLE
Consul gossip encryption doesn't work with swarm join (nodes can join without encryption key)

### ISSUE THREAD

**Issue by slawekgh** [docker/docker#21442]
**Output of `docker version`:**

```
Node-10# docker -H tcp://10.3.0.6:2376 version
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:40:35 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:40:35 2016
 OS/Arch:      linux/amd64
Node-10#

```

**Output of `docker info`:**

```
Node-10# docker -H tcp://10.3.0.6:2376 info
Containers: 66
 Running: 6
 Paused: 0
 Stopped: 60
Images: 5
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 163
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-23-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.636 GiB
Name: WolakUbuntu10
ID: EFUN:FMSQ:ZQSD:GEPO:IGAP:IP3K:XVFZ:EGKV:Y5OO:62XM:24VT:Z2Z6
WARNING: No swap limit support
Node-10#


```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

2 azure Ubuntu servers - on 1st consul docker image up& running
on 2nd there is one node of swarm joining swarm cluster with consul 

I'm trying to run basic gossip encryption for swarm join with consul

I expected that node without secret encryption key WILL NOT connect BUT they still can (!)

Here is my very simple consul.json config (based on progrium/consul docker image with few additional lines for protocols and encryption):

{
        "data_dir": "/data3",
        "ui_dir": "/ui",
        "encrypt": "3gYEbrA/yFo9bSUuJQDhZA==",
        "client_addr": "0.0.0.0",
        "ports": {
                "dns": 9600,
                "http": 9500,
                "rpc": 9400,
                "serf_lan": 9301,
                "serf_wan": 9302,
                "server": 9300,
                "https": 9999
        },
        "recursor": "8.8.8.8",
        "disable_update_check": true
}

When I run consul it seems that "Gossip encrypt is true":

# /bin/consul agent -config-dir=/config3  -server -bootstrap -log-level=debug
==> WARNING: LAN keyring exists but -encrypt given, using keyring
==> WARNING: WAN keyring exists but -encrypt given, using keyring
==> WARNING: Bootstrap mode enabled! Do not enable unless necessary
==> WARNING: It is highly recommended to set GOMAXPROCS higher than 1
==> Starting raft data migration...
==> Starting Consul agent...
==> Starting Consul agent RPC...
==> Consul agent running!
         Node name: 'consul04'
        Datacenter: 'dc1'
            Server: true (bootstrap: true)
       Client Addr: 0.0.0.0 (HTTP: 9500, HTTPS: 9999, DNS: 9600, RPC: 9400)
      Cluster Addr: 172.17.0.2 (LAN: 9301, WAN: 9302)
    Gossip encrypt: true, RPC-TLS: false, TLS-Incoming: false
             Atlas: <disabled>

==> Log data will now stream in as it occurs:

    2016/03/23 18:51:14 [INFO] serf: EventMemberJoin: consul04 172.17.0.2
    2016/03/23 18:51:14 [INFO] serf: EventMemberJoin: consul04.dc1 172.17.0.2
    2016/03/23 18:51:14 [INFO] raft: Node at 172.17.0.2:9300 [Follower] entering Follower state
    2016/03/23 18:51:14 [INFO] consul: adding server consul04 (Addr: 172.17.0.2:9300) (DC: dc1)
    2016/03/23 18:51:14 [INFO] consul: adding server consul04.dc1 (Addr: 172.17.0.2:9300) (DC: dc1)
    2016/03/23 18:51:14 [ERR] agent: failed to sync remote state: No cluster leader
    2016/03/23 18:51:15 [WARN] raft: Heartbeat timeout reached, starting election
    2016/03/23 18:51:15 [INFO] raft: Node at 172.17.0.2:9300 [Candidate] entering Candidate state
    2016/03/23 18:51:15 [DEBUG] raft: Votes needed: 1
    2016/03/23 18:51:15 [DEBUG] raft: Vote granted. Tally: 1
    2016/03/23 18:51:15 [INFO] raft: Election won. Tally: 1
    2016/03/23 18:51:15 [INFO] raft: Node at 172.17.0.2:9300 [Leader] entering Leader state
    2016/03/23 18:51:15 [INFO] consul: cluster leadership acquired
    2016/03/23 18:51:15 [INFO] consul: New leader elected: consul04
    2016/03/23 18:51:15 [INFO] raft: Disabling EnableSingleNode (bootstrap)
    2016/03/23 18:51:15 [DEBUG] raft: Node 172.17.0.2:9300 updated peer set (2): [172.17.0.2:9300]
    2016/03/23 18:51:15 [DEBUG] raft: Node 172.17.0.2:9300 updated peer set (2): [172.17.0.2:9300]
    2016/03/23 18:51:15 [DEBUG] raft: Node 172.17.0.2:9300 updated peer set (2): [172.17.0.2:9300]
    2016/03/23 18:51:15 [DEBUG] raft: Node 172.17.0.2:9300 updated peer set (2): [172.17.0.2:9300]
    2016/03/23 18:51:15 [DEBUG] raft: Node 172.17.0.2:9300 updated peer set (2): [172.17.0.2:9300]
    2016/03/23 18:51:15 [DEBUG] raft: Node 172.17.0.2:9300 updated peer set (2): [172.17.0.2:9300]
    2016/03/23 18:51:15 [DEBUG] raft: Node 172.17.0.2:9300 updated peer set (2): [172.17.0.2:9300]
    2016/03/23 18:51:15 [DEBUG] consul: reset tombstone GC to index 59
    2016/03/23 18:51:15 [DEBUG] agent: Service 'consul' in sync

But on another swarm node I can join without any consul tokens:

Node-10# docker -H tcp://10.3.0.6:2376 run swarm join --advertise=10.3.0.6:2376 consul://10.3.0.4:9500                                                                                                 
time="2016-03-23T18:49:10Z" level=info msg="Initializing discovery without TLS"
time="2016-03-23T18:49:10Z" level=info msg="Registering on the discovery service every 1m0s..." addr="10.3.0.6:2376" discovery="consul://10.3.0.4:9500"
time="2016-03-23T18:50:10Z" level=info msg="Registering on the discovery service every 1m0s..." addr="10.3.0.6:2376" discovery="consul://10.3.0.4:9500"
time="2016-03-23T18:51:10Z" level=info msg="Registering on the discovery service every 1m0s..." addr="10.3.0.6:2376" discovery="consul://10.3.0.4:9500"
time="2016-03-23T18:52:10Z" level=info msg="Registering on the discovery service every 1m0s..." addr="10.3.0.6:2376" discovery="consul://10.3.0.4:9500"
time="2016-03-23T18:53:10Z" level=info msg="Registering on the discovery service every 1m0s..." addr="10.3.0.6:2376" discovery="consul://10.3.0.4:9500"
time="2016-03-23T18:54:11Z" level=info msg="Registering on the discovery service every 1m0s..." addr="10.3.0.6:2376" discovery="consul://10.3.0.4:9500"

**Comment by thaJeztah** [comment]
Can you reopen this issue in the Swarm issue tracker? Looks like this is a swarm issue; https://github.com/docker/swarm/issues

**Comment by thaJeztah** [comment]
I'll close this issue here, but feel free to comment after I've closed
