### ISSUE TITLE
docker inspect -f '{{.}}' not returning json

### ISSUE THREAD

**Issue by putnamhill** [docker/docker#21447]
Hello,

I was under the impression that the go template, `{{.}}`, should cause `docker inspect` json to be returned as is, but I'm getting some hex values enclosed with curly brackets instead. Exit status is 0.

**Output of `docker version`:**
```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:40:35 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:40:35 2016
 OS/Arch:      linux/amd64```
```

**Output of `docker info`:**
```
Containers: 8
 Running: 1
 Paused: 0
 Stopped: 7
Images: 30
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 83
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-16-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 865.8 MiB
Name: putnamhill-ubuntu
ID: 6IHL:E4TO:W6S3:75U3:EZSL:R2DD:WAOR:BBCN:FUJV:7VKP:4HDS:W2NK
Username: putnamhill
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Steps to reproduce the issue:**
1. `docker run --name hello-test ubuntu /bin/echo 'Hello world'`
2. `docker inspect -f '{{.}}' hello-test`

**Describe the results you received:**
`{0xc82009e000 [] 0xc820150000 0xc820150100}`

**Describe the results you expected:**
I expected to see the complete json output of `docker inspect`. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by vdemeester** [comment]
@putnamhill Go template returns the Go representation of the structure. You have to use the `json` keyboard to have the json object : `docker inspect -f '{{ json . }}' hello-test`.

**Comment by putnamhill** [comment]
Thanks!
