### ISSUE TITLE
more descriptive error when running a container with a too long hostname

### ISSUE THREAD

**Issue by damirv** [docker/docker#21445]
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 20
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 85
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 4.1.19-boot2docker
Operating System: Boot2Docker 1.10.3 (TCL 6.4.1); master : 625117e - Thu Mar 10 22:09:02 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.955 GiB
Name: default
ID: QLTM:SOPG:AKQK:MMBG:6RCU:SYWF:YQCR:OOB3:RSRA:ZUIN:N23O:MKPD
Debug mode (server): true
 File Descriptors: 11
 Goroutines: 25
 System Time: 2016-03-23T19:20:31.689206792Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: damirv
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Virtualbox (default docker-machine)

**Steps to reproduce the issue:**
1. Run `docker run --hostname this-is-a-way-too-long-hostname-but-it-should-give-a-nice-error.local -ti --rm debian:jessie echo 'hi'`

**Describe the results you received:**
```
invalid argument
docker: Error response from daemon: Cannot start container 4202ac11fdba06270c9c50c20c160020c38af08ec9cbbf6fe73153008ab97e5f: [9] System error: invalid argument.
```

**Describe the results you expected:**
A more descriptive error, indicating that the specified hostname is too long? It took me quite some time to figure this one out (in our situating we were dealing with docker-compose config files).

**Additional information you deem important (e.g. issue happens only occasionally):**
This issue occurs also with other images, not just with `debian:jessie`.

**Comment by cpuguy83** [comment]
It's even better now -- `docker: Error response from daemon: rpc error: code = 2 desc = "could not synchronise with container process".`

**Comment by duglin** [comment]
LOL ship it!

**Comment by cpuguy83** [comment]
We should just need a check that validates the hostname length here.

**Comment by yongtang** [comment]
I can create a pull request to fix it. #dibs

**Comment by thaJeztah** [comment]
@yongtang we recently merged https://github.com/docker/docker/pull/20566, perhaps it's even possible to combine, and add length to the RegExp

**Comment by HackToday** [comment]
https://github.com/opencontainers/runc/pull/677/files add more info about 

> docker: Error response from daemon: rpc error: code = 2 desc = "could not synchronise with container process".

**Comment by yongtang** [comment]
Was trying to modify regex directly but it seems that golang only support RE2. So I just do a length check in the pull request https://github.com/docker/docker/pull/21463
Let me know if there are any issues and thanks for the help in this thread.

**Comment by thedebugger** [comment]
Hi, Is there a reason that docker allows hostname up to 64 chars? I understand 64 chars is MUST as per [RFC](https://tools.ietf.org/html/rfc1123#section-2) but why not 255 chars?

**Comment by thaJeztah** [comment]
IIRC, longer hostnames fail on Windows

**Comment by thedebugger** [comment]
ahh. it is dominos all the way. thank you sir for the prompt reply.

**Comment by thaJeztah** [comment]
things may have changes, so feel free to open an issue (explaining MUST, SHOULD in the rfc) for discussion. we would have to be careful changing though, taking mixed version swarm clusters into account
