### ISSUE TITLE
Single Binary for 1.11

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#21455]
Docker 1.11 is now composed of 4 binaries (docker, docker-containerd, docker-containerd-shim and docker-runc).  For me this creates a huge headache in moving from Docker <= 1.10 to 1.11 and impedes my ability to support it.  I'm creating this issue for the purpose of finding out if I'm alone in this regard or if more people feel that they will be impacted.  Hopefully this will gauge if theres any merit to creating a single binary again.

![](http://memecreator.org/static/images/memes/3940097.jpg)

**Comment by crosbymichael** [comment]
@ibuildthecloud what specifically makes it a pain for you?

**Comment by ibuildthecloud** [comment]
You know what, I'm probably not representative of a regular user.  I'll just close this.

**Comment by stuart-warren** [comment]
On a related note, are you not following [Semantic Versioning](http://semver.org/)?
Seems like this should really be a docker 2.0 change as it's going to break a lot of scripts/systems by splitting it out.

**Comment by crosbymichael** [comment]
@ibuildthecloud awe, I really care about the issues that this causes for you so if you still want to expand more go ahead.
