### ISSUE TITLE
Unable to open the database file: unable to open database file

### ISSUE THREAD

**Issue by eobeidamadeus** [docker/docker#21467]
Cheers,
I have been running my VM for less than 24h and it seems that docker crashed out of nowhere.

When I try to restart it, I get the following error:

[root@tec-openshift-node-bow0 ~]# systemctl restart docker
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.

Then, I checked the systemctl status docker.service and journalctl -xe commands and here is their outputs:

**Output of `docker -d`:**

```
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
INFO[0000] [graphdriver] using prior storage driver "overlay"
WARN[0000] Running modprobe bridge nf_nat br_netfilter failed with message: , error: exit status 1
INFO[0000] Firewalld running: false
FATA[0000] Error starting daemon: Unable to open the database file: unable to open database file
```

**Output of `docker version`:**

```
Client version: 1.7.1
Client API version: 1.19
Package Version (client): docker-1.7.1-115.el7.x86_64
Go version (client): go1.4.2
Git commit (client): 446ad9b/1.7.1
OS/Arch (client): linux/amd64
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
```

**Output of `docker info`:**

```
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
```

**Output of `uname -a`:**

```
Linux tec-openshift-node-bow0.figaro.amadeus.net 3.10.0-229.4.2.el7.x86_64 #1 SMP Wed May 13 10:06:09 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Additional information you deem important (e.g. issue happens only occasionally):**
The logs of "journalctl -xe" will be attached shortly

**Comment by eobeidamadeus** [comment]
[DockerCrash.txt](https://github.com/docker/docker/files/187687/DockerCrash.txt)

**Comment by cpuguy83** [comment]
Not sure what the attached logs are from but that's not the docker daemon.

The version of docker you are using is very old, and probably doesn't use the database that's being referred to here (although tbh I'm not sure, I've not seen that particular error, so not sure what database it would be referring to).

**Comment by thaJeztah** [comment]
closing for the same reason as your other report, also https://github.com/docker/docker/issues/21440#issuecomment-200964479
