### ISSUE TITLE
Connecting to container via HTTP stops working randomly

### ISSUE THREAD

**Issue by mutex007** [docker/docker#21462]
I am running about 50+ containers on a host, all listening on random ports. I noticed an issue where the container stops responding to request randomly. There are no errors with the code base running in the containers. These are simply hello world node.js (Express) echo servers. However if i am to restart the unresponsive container and issue a request, the container quickly responds as it should. 

This is on Ubuntu 14. - Docker 1.91.
Docker info:

Containers: 130
Images: 33
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 447
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 8
Total Memory: 31.36 GiB
Name: buf460

Is there some sort of limit which is been hit or is docker simply dropping connections to the containers.

Your response is much appreciated.

**Comment by ping035627** [comment]
yyy
