### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by arun-gupta** [docker/docker#21472]
Broken links at: https://docs.docker.com/docker-hub/overview/

Webhooks link to https://docs.docker.com/docker-hub/builds/#webhooks instead of https://docs.docker.com/docker-hub/webhooks/.

**Comment by thaJeztah** [comment]
Thanks @arun-gupta opening a PR now

**Comment by arun-gupta** [comment]
dang, I should've submitted the PR. Silly of me to file the bug instead :)

**Comment by thaJeztah** [comment]
@arun-gupta no, unfortunately that part of the documentation is in a private repository, so you can't. :smile:

**Comment by arun-gupta** [comment]
@thaJeztah aha, I don't feel that bad now :)

**Comment by thaJeztah** [comment]
You shouldn't be feeling bad at all, just reporting is important as well, never can have too many eyes :+1:

**Comment by sanscontext** [comment]
Hey @arun-gupta, thanks for the report. I've fixed it and it'll go live in the next docs update.

**Comment by thaJeztah** [comment]
Thanks! I'll close this issue
