### ISSUE TITLE
[1.11-RC1] OS X client binary is broken, not statically  linked

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#21494]
Looks like the OS X client binary is not statically linked;

```
docker-1.11.0-rc1 --version
dyld: Library not loaded: /usr/local/opt/libtool/lib/libltdl.7.dylib
  Referenced from: /usr/local/bin/docker-1.11.0-rc1
  Reason: image not found
Trace/BPT trap: 5
```
libltdl seems to be related to pkcs11 signing, which was added in https://github.com/docker/docker/commit/141369457ffaeee79154f4b649525f5c8b3d5f2e, but now moved out of experimental, and the script has changed a bit https://github.com/docker/docker/blob/master/hack/make/binary#L39-L48

```
otool -L /usr/local/bin/docker-1.11.0-rc1
/usr/local/bin/docker-1.11.0-rc1:
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1253.0.0)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 57336.1.9)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)
	/usr/local/opt/libtool/lib/libltdl.7.dylib (compatibility version 11.0.0, current version 11.1.0)
```

**Comment by endophage** [comment]
Already on it

**Comment by thaJeztah** [comment]
@endophage thanks, @cyli was also looking

**Comment by riyazdf** [comment]
docker-machine should be unaffected based on its dependencies; one solution we're exploring could be to update toolbox and docker for mac to install libtool, and to add documentation for those who download the binary directly

**Comment by cyli** [comment]
And update the brew formula to require libtool be installed.  It might be possible to statically link it in, but then if there are any CVEs in libtool we'd have to repackage.  Although we'd have to do that for docker toolbox too.

**Comment by thaJeztah** [comment]
documentation changes could be added to https://github.com/docker/docker/issues/21334. this will probably only affect people that don't have docker-toolbox installed, and try to download a binary, so it's a limited group of users.

having the right instructions on installing the requirements would be good though

**Comment by endophage** [comment]
We're looking at toolbox and it will need an update. The non-experimental toolbox does not currently include the necessary libs

**Comment by endophage** [comment]
TODOs in order to close this issue:

- [ ] Update toolbox to include libltdl (possibly also libykcs11, libykpiv and libcrypto, currently included in experimental toolbox)
- [ ] Submit PR to brew to update both docker and add the libtool dependency.
- [ ] Update Docker for Mac to add libltdl
- [ ] Update windows packages to include libtool (http://gnuwin32.sourceforge.net/packages/libtool.htm)

Deb/RPMs do not need updates because docker for linux is statically compiled:
```
➜  bin$ ldd docker
	not a dynamic executable
```

**Comment by thaJeztah** [comment]
@endophage debs/rpms actually are dynamically linked

**Comment by cyli** [comment]
https://github.com/Homebrew/homebrew/compare/master...cyli:docker-yubikey-support?expand=1 waiting for tag bump and revision change.  Although these changes should work fine with 1.10.3, and everyone's just going to download the bottle anyway.

Wondering if I should submit this as a WIP PR, or just wait until 1.11 is out of RC.
