### ISSUE TITLE
latest docker binary start failed with docker-default profile could not be loaded

### ISSUE THREAD

**Issue by HackToday** [docker/docker#21505]
**Output of `docker version`:**

```
1.10.3
latest binary 
https://get.docker.com/builds/Linux/x86_64/docker-latest
```

**Output of `docker info`:**

```
docker can not start, so can not give info
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. have a ubuntu 14.04 installed
2. download https://get.docker.com/builds/Linux/x86_64/docker-latest
3. and install apparmor
4. start docker
   `sudo ./docker  daemon -D `

**Describe the results you received:**
cannot accept client connections 
DEBU[0001] devmapper: deactivateDevice()                
DEBU[0001] devmapper: deactivateDevice END()            
DEBU[0001] devmapper: deactivatePool()                  
DEBU[0001] devmapper: deactivatePool END                
DEBU[0001] devmapper: [deviceset docker-253:1-131089] Shutdown() END 
DEBU[0001] Cleaning up old shm/mqueue mounts: start.    
FATA[0001] Error starting daemon: AppArmor enabled on system but the docker-default profile could not be loaded. 

**Describe the results you expected:**

docker can start

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by HackToday** [comment]
Found similar issue here https://github.com/docker/docker/issues/15340

**Comment by HackToday** [comment]
ping @thaJeztah  do you know this issue ? 
Or @jfrazelle since you know much about security related

**Comment by thaJeztah** [comment]
I think this is https://github.com/docker/docker/issues/20584

**Comment by HackToday** [comment]
hi @thaJeztah  I did not find 1.11 have binary build,  How could verify that ?

**Comment by thaJeztah** [comment]
@HackToday for 1.11, docker needs four binaries to run, so the static binaries will now be distributed as a `.tgz`;

The procedure below assumes Docker is not installed or running on the host
you're testing on. 

Download and extract the binaries:

    curl -sSL -O https://test.docker.com/builds/Linux/x86_64/docker-1.11.0-rc1.tgz
    tar zxvf docker-1.11.0-rc1.tgz -C /

This will put the four binaries inside `/usr/local/bin/` (`docker`,
`docker-containerd-ctr`, `docker-runc`, `docker-containerd-shim`)

You can now manually start Docker Engine in debug mode using;

    sudo docker daemon -D

You *can* extract to another location, but docker will search for the other binaries in the `PATH` (iirc)

**Comment by jfrazelle** [comment]
we dont even pass the path anymore so this shouldnt be an issue on 1.11

On Fri, Mar 25, 2016 at 10:40 AM, Sebastiaan van Stijn <
notifications@github.com> wrote:

> @HackToday <https://github.com/HackToday> for 1.11, docker needs four
> binaries to run, so the static binaries will now be distributed as a .tgz;
>
> The procedure below assumes Docker is not installed or running on the host
> you're testing on.
>
> Download and extract the binaries:
>
> curl -sSL -O https://test.docker.com/builds/Linux/x86_64/docker-1.11.0-rc1.tgz
> tar zxvf docker-1.11.0-rc1.tgz -C /
>
> This will put the four binaries inside /usr/local/bin/ (docker,
> docker-containerd-ctr, docker-runc, docker-containerd-shim)
>
> You can now manually start Docker Engine in debug mode using;
>
> sudo docker daemon -D
>
> You *can* extract to another location, but docker will search for the
> other binaries in the PATH (iirc)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/21505#issuecomment-201381493>
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by HackToday** [comment]
@thaJeztah and @jfrazelle 
the new docker-1.11.0  can not work with that tgz, 
I download that tgz and extract that, 

$ sudo docker daemon --storage-driver=aufs -D

DEBU[0000] Using default logging driver json-file       
DEBU[0000] Golang's threads limit set to 114840         
DEBU[0000] containerd connection state change: READY    
DEBU[0000] received past containerd event: &types.Event{Type:"live", Id:"", Status:0x0, Pid:"", Timestamp:0x56f88c4b} 
DEBU[0000] [graphdriver] trying provided driver "aufs"  
DEBU[0000] Cleaning up old container shm/mqueue/rootfs mounts: start. 
FATA[0000] Error starting daemon: error initializing graphdriver: driver not supported 

so it seems this page `https://github.com/docker/docker/blob/master/docs/installation/binaries.md` is very old which could not be right anymore

**Comment by jfrazelle** [comment]
You started w graph driver aufs and it's saying it's not supported for your
computer so you may need to install the kernel header extras to get aufs or
choose another driver regardless it's unrelated to this original issue

On Sunday, March 27, 2016, Kai Qiang Wu <notifications@github.com> wrote:

> @thaJeztah <https://github.com/thaJeztah> and @jfrazelle
> <https://github.com/jfrazelle>
> the new docker-1.11.0 can not work with that tgz,
> I download that tgz and extract that,
>
> $ sudo docker daemon --storage-driver=aufs -D
>
> DEBU[0000] Using default logging driver json-file
>
> DEBU[0000] Golang's threads limit set to 114840
>
> DEBU[0000] containerd connection state change: READY
>
> DEBU[0000] received past containerd event: &types.Event{Type:"live",
> Id:"", Status:0x0, Pid:"", Timestamp:0x56f88c4b}
> DEBU[0000] [graphdriver] trying provided driver "aufs"
>
> DEBU[0000] Cleaning up old container shm/mqueue/rootfs mounts: start.
> FATA[0000] Error starting daemon: error initializing graphdriver: driver
> not supported
>
> so it seems this page
> https://github.com/docker/docker/blob/master/docs/installation/binaries.md
> is very old which could not be right anymore
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/21505#issuecomment-202187975>
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by HackToday** [comment]
hi @jfrazelle  I used aufs, because when directly run `docker daemon -D` it could not run, because default it use devicemapper.


For binary install before, https://github.com/docker/docker/blob/master/docs/installation/binaries.md
it also not have asked you to configure devicemapper or something. 


So I think that's the still install issue.

**Comment by HackToday** [comment]
Have tried a new install os, and the latest 1.11.rc2 binary can executed. Close it now
