### ISSUE TITLE
DockerSuite.TestDiffEnsureDefaultDevs failing consistently on systemd system

### ISSUE THREAD

**Issue by vdemeester** [docker/docker#21507]
Related to https://github.com/docker/docker/pull/21465, this test is consistently failing on systemd system it seems.

Quoting @runcom (https://github.com/docker/docker/pull/21465#issuecomment-200774615)

> ping @crosbymichael @LK4D4 @calavera I don't have any clue about who's mounting /run/systemd/notify  (I'm on fedora 23 and docker built from master)
> 
> I get this in every container:
> ```
> # mount | grep /run
> tmpfs on /run/systemd/notify type tmpfs (rw,seclabel,nosuid,nodev,mode=755)
> ```
> it's mounted from the host (same inode also)

```
$ docker run -itd busybox sh
$ docker diff a95
A /run
A /run/systemd
A /run/systemd/notify
```

* Docker version

```
Client:
 Version:      1.11.0-dev
 API version:  1.24
 Go version:   go1.6
 Git commit:   b64627b
 Built:        Thu Mar 24 08:31:20 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0-dev
 API version:  1.24
 Go version:   go1.6
 Git commit:   b64627b
 Built:        Thu Mar 24 08:31:20 2016
 OS/Arch:      linux/amd64
```

* Docker info

```
Containers: 16
 Running: 1
 Paused: 0
 Stopped: 15
Images: 262
Server Version: 1.11.0-dev
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.5-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.56 GiB
Name: hokkaido
ID: YEDF:TDNS:RY6Q:D6RB:OH7S:EPBP:DBZ5:BAVO:HPEH:ALXT:PLP2:FLDM
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 22
 Goroutines: 47
 System Time: 2016-03-24T11:15:20.211478419+01:00
 EventsListeners: 0
Username: vdemeester
Registry: https://index.docker.io/v1/
Labels:
 type=laptop
```

* Kernel

```
Linux hokkaido 4.4.5-1-ARCH #1 SMP PREEMPT Thu Mar 10 07:38:19 CET 2016 x86_64 GNU/Linux
```

**Comment by runcom** [comment]
happening on my Fedora 23 host

**Comment by runcom** [comment]
ping @LK4D4 you might also experience this one (seems systemd related :confused: )

**Comment by rhatdan** [comment]
I think this might be related to the sdNotify patch in runc.

```
// If systemd is supporting sd_notify protocol, this function will add support
// for sd_notify protocol from within the container.
func setupSdNotify(spec *specs.Spec, notifySocket string) {
	spec.Mounts = append(spec.Mounts, specs.Mount{Destination: notifySocket, Type: "bind", Source: notifySocket, Options: []string{"bind"}})
	spec.Process.Env = append(spec.Process.Env, fmt.Sprintf("NOTIFY_SOCKET=%s", notifySocket))
}
```

**Comment by rhatdan** [comment]
```
 echo  $NOTIFY_SOCKET 
/run/systemd/notify
```

**Comment by rhatdan** [comment]
If you unset $NOTIFY_SOCKET, the tests will probably pass.

**Comment by runcom** [comment]
yes, that's the issue, I think tests should/could be updated

**Comment by rhatdan** [comment]
Now I have no idea why NOTIFY_SOCKET is set for login sessions on Fedora.

**Comment by rhatdan** [comment]
Actually this is set for docker, also, but should probably be cleared before executing subcontainers.

**Comment by crosbymichael** [comment]
Do you think i should clear this in containerd then?

**Comment by rhatdan** [comment]
I actually think docker should clear it, before executing containerd. Basically the NOTIFY_SOCKET is for the process running within the unit file, not for its children and grand children.

We need to eventually handle this in runc running with a different UserNamespace, if it is indeed broken.  But we should not be leaking this Environment variable down the the containers.

**Comment by crosbymichael** [comment]
ok, that works for me
