### ISSUE TITLE
Scaling DB container does not expose env vars to the linked containers, using Docker Compose

### ISSUE THREAD

**Issue by debroop** [docker/docker#21502]
I have a deployment scenario where I have 3 containers: DB container(DB), Web Container(WEB) and a Load Balancer container(LB). The LB links to WEB which in turn links to DB.

Now I am using "docker-compose scale WEB=2". This is creating a new container for WEB service as expected. The env for this new container also contains the env vars of the DB as expected.

However the LB which contains the env vars of WEB_1 does not contain the env vars of the newly created WEB_2.

Please suggest if this is an issue with Docker-Compose or is there a way to solve this?

**Comment by thaJeztah** [comment]
I'd recommend not relying on the environment variables that are set by `--link`, and use custom networks instead, as they are more suitable for dynamically connecting/starting and disconnecting containers. https://docs.docker.com/engine/userguide/networking/

We only maintain the existing "links" for backward compatibility and are not planning to make any enhancements in that area, so I'll close this issue
