### ISSUE TITLE
Docker connection issue - connection timeout while connecting to https://index.docker.io

### ISSUE THREAD

**Issue by jatins** [docker/docker#21524]
**Output of `docker version`:**

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        2016-02-22T22:37:33.778002647+00:00
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 8
Images: 3
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 35
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.18-boot2docker
Operating System: Boot2Docker 1.10.2 (TCL 6.4.1); master : 611be10 - Mon Feb 22 22:47:06 UTC 2016
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: AV52:G4SD:EIAQ:UXXJ:D3DR:33PQ:56IG:P37G:RXT3:GI2S:7ZFC:K4WM
Debug mode (server): true
 File Descriptors: 11
 Goroutines: 24
 System Time: 2016-03-25T18:46:40.280651277Z
 EventsListeners: 1
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

I was following along with Docker tutorial over here: https://docs.docker.com/mac/step_three/

I am able to run the `docker run hello-world` implying the initial set up in working.

**Output of `docker search whalesay`**

    Error response from daemon: Get https://index.docker.io/v1/search?q=whalesay: dial tcp: lookup index.docker.io on 192.168.0.1:53: read udp 10.0.2.15:58317->192.168.0.1:53: i/o timeout

**Output of `docker pull hello-world`**

    Using default tag: latest
    Pulling repository docker.io/library/hello-world
    Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/hello-world/images. You may want to check your internet connection or if you are behind a proxy.

**Output of `curl -v https://index.docker.io:443`**

	* Adding handle: conn: 0x7f9c01002200
	* Adding handle: send: 0
	* Adding handle: recv: 0
	* Curl_addHandleToPipeline: length: 1
	* - Conn 0 (0x7f9c01002200) send_pipe: 1, recv_pipe: 0
	* About to connect() to index.docker.io port 443 (#0)
	*   Trying 52.72.231.247...
	* Connected to index.docker.io (52.72.231.247) port 443 (#0)
	* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
	* Server certificate: *.docker.io
	* Server certificate: RapidSSL SHA256 CA - G3
	* Server certificate: GeoTrust Global CA
	> GET / HTTP/1.1
	> User-Agent: curl/7.30.0
	> Host: index.docker.io
	> Accept: */*
	>
	< HTTP/1.1 301 MOVED PERMANENTLY
	* Server nginx/1.6.2 is not blacklisted
	< Server: nginx/1.6.2
	< Date: Fri, 25 Mar 2016 11:19:56 GMT
	< Content-Type: text/html; charset=utf-8
	< Transfer-Encoding: chunked
	< X-Frame-Options: SAMEORIGIN
	< Location: https://registry.hub.docker.com/
	< Strict-Transport-Security: max-age=31536000
	<
	* Connection #0 to host index.docker.io left intact

I am not sure what's the issue here. Any network settings I need to look into?

I tried to check if I am behind a **proxy** on http://whatismyipaddress.com/proxy-check and http://amibehindaproxy.com/  Both of them say `Proxy server not detected`

**Comment by cpuguy83** [comment]
Looks like it can't reach the DNS server? `read udp 10.0.2.15:58317->192.168.0.1:53: i/o timeout`
I'd try restarting the VM.

**Comment by jatins** [comment]
I did a fresh install of Docker toolbox. However, now I am not able to start the daemon.

**Output of `docker run hello-world`**
```
docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
See 'docker run --help'.
```

**Output of `docker-machine ls`**
```
NAME      ACTIVE   DRIVER       STATE     URL   SWARM   DOCKER    ERRORS
default   -        virtualbox   Stopped                 Unknown   
```

**Output of `docker-machine start default`**
```
Starting "default"...
(default) Check network to re-create if needed...
(default) Creating a new host-only adapter produced an error: /usr/local/bin/VBoxManage hostonlyif create failed:
(default) 0%...
(default) Progress state: NS_ERROR_FAILURE
(default) VBoxManage: error: Failed to create the host-only adapter
(default) VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
(default) VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
(default) VBoxManage: error: Context: "RTEXITCODE handleCreate(HandlerArg*)" at line 71 of file VBoxManageHostonly.cpp
(default) 
(default) This is a known VirtualBox bug. Let's try to recover anyway...
Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue
```

**Comment by HackToday** [comment]
it said this

```
(default) This is a known VirtualBox bug. Let's try to recover anyway...
Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue

```

**Comment by jatins** [comment]
@HackToday I was doing a fresh install with the latest version of Docker Toolbox.
Also, VirtualBox version is 5.0.16

**Comment by joegross** [comment]
I've seen this happen on OSX when my laptop IP changes. Restarting docker-machine fixes it.

The error message should be more informative.

**Comment by thaJeztah** [comment]
@jatins can you open an issue for this in the docker machine issue tracker (https://github.com/docker/machine) to improve the error message? This looks like an issue with docker-machine, so not something we can fix in this repository.

Thanks for reporting!

I'll close the issue here, but feel free to comment after I closed

**Comment by kuccello** [comment]
I had this issue while trying to dockerize a nodejs app.
Was able to correct the problem by restarting the docker-machine - see https://docs.docker.com/machine/reference/restart/ 

Host Machine: Win10
Docker-toolbox running in MING64
