### ISSUE TITLE
Error creating aufs mount: invalid argument

### ISSUE THREAD

**Issue by teogelles** [docker/docker#21531]
I am running an instance of Ubuntu 14.04 booted via iPXE whose filesystem is mounted on a remote EC2 server. I have installed docker to the system as per instructions here 

[https://docs.docker.com/engine/installation/linux/ubuntulinux/]

However when i run

`sudo docker run hello-world`

I obtain the output

```
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
03f4658f8b78: Pull complete 
a3ed95caeb02: Pull complete 
Digest: sha256:8be990ef2aeb16dbcb9271ddfe2610fa6658d13f6dfb8bc72074cc1ca36966a7
Status: Downloaded newer image for hello-world:latest
docker: Error response from daemon: error creating aufs mount to /var/lib/docker/aufs/mnt/c9dbd535cabdd737607a76480bd7a08b68ac0da4f393d1516f69257a5c802f97-init: invalid argument.
See 'docker run --help'.
```

This issue seems to be different from #13742.

I have tried the solution presented here

[ http://stackoverflow.com/questions/30984569/error-error-creating-aufs-mount-to-when-building-dockerfile ]

which did not affect the command.

**Output of `mount`:**
```
/cow on / type overlay (rw)
proc on /proc type proc (rw,noexec,nosuid,nodev)
sysfs on /sys type sysfs (rw,noexec,nosuid,nodev)
udev on /dev type devtmpfs (rw,mode=0755)
devpts on /dev/pts type devpts (rw,noexec,nosuid,gid=5,mode=0620)
tmpfs on /run type tmpfs (rw,noexec,nosuid,size=10%,mode=0755)
54.84.7.1:/home/ubuntu/nfs/ubuntu1404 on /cdrom type nfs (ro,relatime,vers=3,rsize=524288,wsize=524288,namlen=255,hard,nolock,proto=tcp,port=2049,timeo=7,retrans=3,sec=sys,local_lock=all,addr=54.84.7.1)
/dev/loop0 on /rofs type squashfs (ro,noatime)
none on /sys/fs/cgroup type tmpfs (rw)
none on /sys/fs/fuse/connections type fusectl (rw)
none on /sys/kernel/debug type debugfs (rw)
none on /sys/kernel/security type securityfs (rw)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev)
none on /run/lock type tmpfs (rw,noexec,nosuid,nodev,size=5242880)
none on /run/shm type tmpfs (rw,nosuid,nodev)
none on /run/user type tmpfs (rw,noexec,nosuid,nodev,size=104857600,mode=0755)
none on /sys/fs/pstore type pstore (rw)
systemd on /sys/fs/cgroup/systemd type cgroup (rw,noexec,nosuid,nodev,none,name=systemd)
gvfsd-fuse on /run/user/999/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,user=ubuntu)
```

**Output of `sudo docker version`:**
```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
```

**Output of `sudo docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /home/ubuntu/docker/aufs
 Backing Filesystem: <unknown>
 Dirs: 2
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 31.39 GiB
Name: ubuntu
ID: 3OJS:46OC:GQQS:OK6J:UFKB:G2J7:7VID:IUQK:7RYA:4YSE:4HIF:L3VP
WARNING: No swap limit support
```

**Comment by HackToday** [comment]
what's your filesystem type of /home/ubuntu/docker/aufs ? I found it said backing fileystem is unknown.

is it NFS ? or something ?

**Comment by teogelles** [comment]
The backing filesystem is NFS.

**Comment by HackToday** [comment]
@teogelles  I did not think docker support NFS for containers and images.

ping @thaJeztah may know clearly about it.

**Comment by thaJeztah** [comment]
Yeah, I don't think running on NFS works, see for example https://github.com/docker/docker/issues/15239 and https://github.com/docker/docker/issues/21086

**Comment by teogelles** [comment]
Would it be possible to make docker run in RAM, perhaps with a tmpfs ramdisk mounted to, say, /mnt/ramdisk? For my applications the containers would be relatively small and should fit in memory. @thaJeztah I noticed you answered a similar question in #10490 where you suggested
`docker -d -g /path/to/ramdisk`
but mentioned it was highly experimental. Has this solution gotten any more stable?

**Comment by thaJeztah** [comment]
@teogelles it's not something we worked on as a use-case so I think that'd be still "at your own risk". Any reason to mount it in memory though? If there's not much disk activity, I don't think it'll bring much advantage

**Comment by unclejack** [comment]
I'm closing this in favour of #21086. Please comment on that issue instead.
