### ISSUE TITLE
Created a container but can’t see files in the Windows host folder 

### ISSUE THREAD

**Issue by julianonunes** [docker/docker#21535]
I've run the following command to create a container base on this image: https://hub.docker.com/_/rails/

$ docker run -it --rm --user "$(id -u):$(id -g)" -v "$PWD":/usr/src/app -w /usr/src/app rails rails new --skip-bundle webapp

The message says that the rails project has been created, however, I can't find where did the files go in the host machine. I mean, shouldn't they go to $PWD?

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Output of `docker version`:**

```
Docker version 1.10.3, build 20f81dd
```

**Output of `docker info`:**

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 21
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 96
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.19-boot2docker
Operating System: Boot2Docker 1.10.3 (TCL 6.4.1); master : 625117e - Thu Mar 10 22:09:02 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.1 MiB
Name: default
ID: PJB3:2HTS:GH4U:F4ZX:DYTC:DQBX:O5DE:BJK4:6XDX:XXML:ZQE5:KWRD
Debug mode (server): true
 File Descriptors: 10
 Goroutines: 21
 System Time: 2016-03-26T02:27:28.947779376Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Windows 10 x64

**Steps to reproduce the issue:**
1.
2. docker run -it --rm --user "$(id -u):$(id -g)" -v "$PWD":/usr/src/app -w /usr/src/app rails rails new --skip-bundle webapp
3.

**Describe the results you received:**
Container is created, however the local folder does not list the synced files

**Describe the results you expected:**
Local and container folders with the same files

**Additional information you deem important (e.g. issue happens only occasionally):**
Always happen

**Comment by thaJeztah** [comment]
Is the local folder inside C:\Users ? Because by default, only C:\Users is shared with the Virtual Machine that the daemon runs in. If any other directory is used, the daemon will create an empty directory inside the VM, and use that as a bind-mounted volume

**Comment by thaJeztah** [comment]
You may be interested in this blog post though; https://blog.docker.com/2016/03/docker-for-mac-windows-beta/

**Comment by julianonunes** [comment]
I tried both inside and outside the Users folder (C:\Users\MyUser\Documents\Docker\projName).

**Comment by carrete** [comment]
We're using Docker for Windows (beta) and `docker run -v //Users/project://project` produces an empty /project directory in the container.

**Comment by thaJeztah** [comment]
For Docker for Windows, this section may be relevant; https://beta.docker.com/docs/windows/troubleshoot/#host-filesystem-sharing

**Comment by thaJeztah** [comment]
@julianonunes a similar issue just came up in https://github.com/docker/docker/issues/22981 are you perhaps not using VirtualBox, but Hyper-V?

**Comment by julianonunes** [comment]
@thaJeztah I used to have Hyper-V installed, but it was disabled using different boot profiles (like this: http://www.hanselman.com/blog/SwitchEasilyBetweenVirtualBoxAndHyperVWithABCDEditBootEntryInWindows81.aspx).

**Comment by thaJeztah** [comment]
@julianonunes alright, so your docker daemon is running in a VirtualBox VM?

**Comment by julianonunes** [comment]
Exactly.

**Comment by thaJeztah** [comment]
@julianonunes if you `docker inspect` the container that's started, does it should the correct paths for the mounted directories? Wondering if it's an issue with shell-expansion of `$PWD` or mingw trying to do "smart" things (also looking at https://github.com/docker/docker/issues/20517)

**Comment by caylorme** [comment]
http://docker-saigon.github.io/post/Docker-Beta/ -- check out the Mounting Volumes section on this page

**Comment by laurencee** [comment]
@julianonunes  I'm not sure if you've done this already but this caught out my team mates and myself the first time.

On windows you have to configure the drive to be shared before the files from the volume mount will actually work (settings -> shared drives -> tick c drive).

There needs to be a warning/error on the windows version of docker to tell the user that they've tried to setup a volume mount without sharing the underlying drive first as I have seen this catch out everyone of my teammates.

**Comment by thaJeztah** [comment]
I'm closing this issue, as we need more information; most likely this is a configuration issue, but let us know if you still have this issue @julianonunes

**Comment by nmarkey10** [comment]
Is there any way to mount the volume without sharing the drive?  I've been scouring the internet for a workaround.  I am trying to prepare for all use cases (for instance, the user doesn't have permission to share their drive).  Is there a default shared folder where I can store temporary data?  Or is there a command I can run on Windows' end that will share a specific folder.  Every time I look for a workaround I end up reading a bunch of threads on other issues and not this one.  Any help is greatly appreciated!!

**Comment by thaJeztah** [comment]
No, unfortunately that's the only way to have it working currently on Windows

**Comment by nmarkey10** [comment]
Ah shoot.  Well, thanks for the quick response!  I guess my search stops here.  Time to rethink some things.  Thanks again.

**Comment by laurencee** [comment]
Well there should still be a change to show a warning or prompt to share the folder if that's required for mounting to work on windows.

**Comment by thaJeztah** [comment]
@laurencee could you open a feature request for that in the issue tracker fir Docker for Windows? https://github.com/docker/for-win/issues

**Comment by laurencee** [comment]
Done

**Comment by thaJeztah** [comment]
Thanks!
