### ISSUE TITLE
Docker Volume Size

### ISSUE THREAD

**Issue by akamalov** [docker/docker#21534]
This is a question: AFAIK currently 'docker volume' does not support  volume size option. Are there any plans to (or is it already ongoing) to incorporate it into a next release.

Thanks,

Alex

**Comment by thaJeztah** [comment]
There are no plans to add quota support to the default ("local") volume driver. I don't think we want to add to many options to the default driver, but this should be achievable with a volume-driver plugin.

**Comment by akamalov** [comment]
Thanks for the prompt reply. I understand that it should be achievable with a volume-driver. I am using REX-Ray, and using REX-Rey in conjunction with ScaleIO + Apache Mesos + Mesos containerizer, I can supply volume size + IOPS + thin or thick (all via Mesos DVDI). However, I cannot supply the same parameters if I use docker containerizer. This is a major pain, because we plan to deploy Postgres + Mongo on Docker containers, and I cannot provide desired volume size.

**Comment by thaJeztah** [comment]
But if the default driver had a size option, it would still need to be passed on by Docker containerizer ?

**Comment by coolljt0725** [comment]
@akamalov AFAIK, `docker volume create ` provide interface to pass driver specific options. I think if your volume-driver plugin has quota support , you can provide desired volume size with `--opt=map[]` option in your `docker volume create` cli, something like `docker volume create -d YOUR_DRIVER -o volume.size=10G`, it's depend on your volume-driver implementation

**Comment by senk** [comment]
as @coolljt0725 said you can pass "--opt size 10" to docker volume according to http://rexray.readthedocs.org/en/stable/#rex-ray-with-docker

**Comment by akamalov** [comment]
Sorry, I have to reformulate my question: Will it be possible to have ```docker run``` command and provide docker volume options ? As per previous replies (thanks so much), I can get  away with ```docker volume create``` and pass the options to ScaleIO. However, when I am submitting a container to be spawn up from Marathon, I have to provide options that will work with ```docker run``` command. Here is my conversation with REX-Ray engineer:

https://github.com/emccode/rexray/issues/283

Thanks!!!

Alex

**Comment by thaJeztah** [comment]
No, we most likely won't be adding that as an option; these options can vary between volumes, and having even more options in the `-v` flag will make up for a really bad/complicated UX.

When running from the command-line, using a sub-shell should do the trick, but I don't know how that translates to containerizer;

    docker run \
      -v $(docker volume create --name=myvolume --driver=foo --opt bar=baz):/foo \
      -v $(docker volume create --name=other --driver=other --opt baz=foo):/bar

**Comment by akamalov** [comment]
Hmmm...the environment is ran from Marathon. Here is a sample JSON file that is used to spawn up a container in conjunction with REX-Ray:

```
{
        "id": "mongodb5",
        "container": {
                "docker": {
                        "image": "tutum/mongodb:3.2",
                        "network": "BRIDGE",
                        "portMappings": [{
                                        "containerPort": 27017,
                                        "hostPort": 37017,
                                        "protocol": "tcp"
                                }, {
                                        "containerPort": 28017,
                                        "hostPort": 38017,
                                        "protocol": "tcp"
                                }
 
                        ],
                        "parameters": [{
                                "key": "volume-driver",
                                "value": "rexray"
                        }, {
                                "key": "volume",
                                "value": "mongo005:/data/db"
                        }, {
                                "key": "env","value": "MONGODB_PASS=XXXXXXX"
                       }]
                }
        },
        "cpus": 0.2,
        "mem": 128.0,
        "instances": 1,
        "constraints": [
                ["hostname", "UNIQUE"]
        ]
}
```

Tried to nest the command, such as:

```"value": "$(docker volume create --name=mongotest --opt size 10):/data/db"```

However, REX-Ray already does do "volume create" directive based on values in "parameters" section. So, it didn't work...

With Mesos DVDI, I can  specify the following settings:

```
"env": {
  "DVDI_VOLUME_NAME": "testing",
  "DVDI_VOLUME_DRIVER": "platform1",
  "DVDI_VOLUME_OPTS": "size=5,iops=150,volumetype=io1,newfstype=ext4,overwritefs=false",
  "DVDI_VOLUME_NAME1": "testing2",
  "DVDI_VOLUME_DRIVER1": "platform2",
  "DVDI_VOLUME_OPTS1": "size=6,volumetype=gp2,newfstype=xfs,overwritefs=true"
}
```

...all within the same JSON file and volume automatically created of assigned size and mounted

:(

Alex

**Comment by cpuguy83** [comment]
@akamalov We won't support volume opts on `docker run` or `docker create`
