### ISSUE TITLE
[1.11] inconsistent install path for binaries

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#21530]
When installing docker from deb/yum, the docker binaries are installed in `/usr/bin`. The static binaries in the `.tgz` use `/usr/local/bin`, potentially leading to docker being installed in two different locations

I think we should be consistent and use the same path for both

**Comment by tiborvass** [comment]
I would prefer putting a `docker-$VERSION` folder in the tgz and just have the binary/binaries in that folder.

**Comment by thaJeztah** [comment]
Yes, I think that would be good, that way people can decide where to put it.

**Comment by kencochrane** [comment]
Yes, agreed, and also, remove the /usr/local/bin from the windows bundle, and switch to a gzip instead of tgz for windows.

**Comment by icecrime** [comment]
+1 for a flat `docker-$VERSION` folder in the tgz with all binaries in there.

**Comment by calavera** [comment]
why do we need a directory called `docker-$VERSION` inside a tarball called `docker-$VERSION.tgz`?

**Comment by thaJeztah** [comment]
+1 to @calavera's comment; I think having a directory name with `-$VERSION` in it may be making it harder to automate? But I'm not strong against having it if it has other advantages

**Comment by kencochrane** [comment]
I can make the change once we agree on what we want. Let me know what everyone decides and I'll make the change

**Comment by icecrime** [comment]
Fine by me, this is not of huge importance. Let's agree on this one then (go-style)?

```
docker-$VERSION.tgz
    |_ docker/
        |_ docker
        |_ docker-containerd
        |_ docker-containerd-ctr
        |_ docker-containerd-shim
        |_ docker-runc
```

**Comment by thaJeztah** [comment]
SGTM

**Comment by kencochrane** [comment]
Cool, I'll work on the PR first thing tomorrow.

**Comment by icecrime** [comment]
The `ADD` use case mentioned in #21621 in interesting: you should take a look.

**Comment by thaJeztah** [comment]
So that means -no- wrapping folder probably?

**Comment by kencochrane** [comment]
Once again, I'm fine with either. I'm testing my PR now, I'll submit once done, and we can comment from there, if there are any more changes.

**Comment by kencochrane** [comment]
PR: #21625 has the changes.
