### ISSUE TITLE
1.11.0-rc2: Missing `containerd` flag  in contrib/completion

### ISSUE THREAD

**Issue by coolljt0725** [docker/docker#21539]
Containerd integration add a `containerd` flag for docker daemon
<pre><code>--containerd                             Path to containerD socket</code></pre>
it missing in  contrib/completion.
Maybe there are some other flag missing for this release, it needs a check.

ping @albers

**Comment by albers** [comment]
Thanks for the notice, I'll look into this.
#dibs
