### ISSUE TITLE
Flaky test: TestDockerNetworkHostModeUngracefulDaemonRestart

### ISSUE THREAD

**Issue by WeiZhang555** [docker/docker#21545]
See https://jenkins.dockerproject.org/job/Docker-PRs/25857/console

06:07:34 ----------------------------------------------------------------------
06:07:34 FAIL: docker_cli_network_unix_test.go:1028: DockerNetworkSuite.TestDockerNetworkHostModeUngracefulDaemonRestart
06:07:34 
06:07:34 [d55386482] waiting for daemon to start
06:07:34 [d55386482] daemon started
06:07:34 [d55386482] exiting daemon
06:07:34 [d55386482] waiting for daemon to start
06:07:34 [d55386482] daemon started
06:07:34 docker_cli_network_unix_test.go:1054:
06:07:34     c.Assert(err, checker.IsNil)
06:07:34 ... value *errors.errorString = &errors.errorString{s:"condition \"\"false\" == \"true\"\" not true in time"} ("condition \"\"false\" == \"true\"\" not true in time")
06:07:34 
06:07:34 [d55386482] exiting daemon
06:07:34 
06:07:34 ----------------------------------------------------------------------

Reported before: https://github.com/docker/docker/issues/19368
Not sure if they are the same.

**Comment by icecrime** [comment]
Thanks! I believe @tonistiigi is already looking into this one.

**Comment by runcom** [comment]
Reopening since I'm constantly seeing this test either failing normally or failing with a huge traceback

ping @tonistiigi

**Comment by runcom** [comment]
here is the traceback I'm getting https://paste.fedoraproject.org/413238/

**Comment by tonistiigi** [comment]
@runcom Can you post logs for daemon and stacktrace of the daemon while the test is timing out. It seems to be stuck on daemon startup. Maybe also worth making a separate issue because although the same test fails it doesn't do it in the same way.

**Comment by thaJeztah** [comment]
ping @runcom ^^
