### ISSUE TITLE
 Error resolving syscall name breakpoint and  syscall name set_tls

### ISSUE THREAD

**Issue by Ch3ck** [docker/docker#21557]
**Output of `docker version`:**

```
Docker version 1.10.3, build 20f81dd
```

**Output of `docker info`:**

```
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 3
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-253:1-1057835-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 384.7 MB
 Data Space Total: 107.4 GB
 Data Space Available: 24.13 GB
 Metadata Space Used: 1.335 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93 (2015-01-30)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.0.4-301.fc22.x86_64
Operating System: Fedora 22 (Twenty Two)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.327 GiB
Name: localhost.localdomain
ID: SN3L:CUIC:XRDI:LH7Q:M6YY:JZTY:HBZ3:PR4X:26I2:MDUT:NR3H:LKXC


```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical Fedora 22 Linux system.

**Steps to reproduce the issue:**
1.docker pull alpine
2. docker images
3. docker run ls -l

**Describe the results you received:**
2016/03/27 13:27:57 Error resolving syscall name breakpoint: could not resolve name to syscall - ignoring syscall.
2016/03/27 13:27:57 Error resolving syscall name set_tls: could not resolve name to syscall - ignoring syscall.
total 16
drwxr-xr-x    2 root     root          4096 Mar  2 16:20 bin
drwxr-xr-x    5 root     root           360 Mar 27 13:27 dev
drwxr-xr-x   13 root     root          4096 Mar 27 13:27 etc
drwxr-xr-x    2 root     root             6 Mar  2 16:20 home
drwxr-xr-x    5 root     root          4096 Mar  2 16:20 lib
lrwxrwxrwx    1 root     root            12 Mar  2 16:20 linuxrc -> /bin/busybox
drwxr-xr-x    5 root     root            41 Mar  2 16:20 media
drwxr-xr-x    2 root     root             6 Mar  2 16:20 mnt
dr-xr-xr-x  272 root     root             0 Mar 27 13:27 proc
drwx------    2 root     root             6 Mar  2 16:20 root
drwxr-xr-x    2 root     root             6 Mar  2 16:20 run
drwxr-xr-x    2 root     root          4096 Mar  2 16:20 sbin
dr-xr-xr-x   13 root     root             0 Mar 27 12:24 sys
drwxrwxrwt    2 root     root             6 Mar  2 16:20 tmp
drwxr-xr-x    7 root     root            61 Mar  2 16:20 usr
drwxr-xr-x   10 root     root            93 Mar  2 16:20 var

**Describe the results you expected:**
drwxr-xr-x    2 root     root          4096 Mar  2 16:20 bin
drwxr-xr-x    5 root     root           360 Mar 27 13:27 dev
drwxr-xr-x   13 root     root          4096 Mar 27 13:27 etc
drwxr-xr-x    2 root     root             6 Mar  2 16:20 home
drwxr-xr-x    5 root     root          4096 Mar  2 16:20 lib
lrwxrwxrwx    1 root     root            12 Mar  2 16:20 linuxrc -> /bin/busybox
drwxr-xr-x    5 root     root            41 Mar  2 16:20 media
drwxr-xr-x    2 root     root             6 Mar  2 16:20 mnt
dr-xr-xr-x  272 root     root             0 Mar 27 13:27 proc
drwx------    2 root     root             6 Mar  2 16:20 root
drwxr-xr-x    2 root     root             6 Mar  2 16:20 run
drwxr-xr-x    2 root     root          4096 Mar  2 16:20 sbin
dr-xr-xr-x   13 root     root             0 Mar 27 12:24 sys
drwxrwxrwt    2 root     root             6 Mar  2 16:20 tmp
drwxr-xr-x    7 root     root            61 Mar  2 16:20 usr
drwxr-xr-x   10 root     root            93 Mar  2 16:20 var

**Additional information you deem important (e.g. issue happens only occasionally):**
Every time I run a docker image. I always get these two errors:
2016/03/27 13:27:57 Error resolving syscall name breakpoint: could not resolve name to syscall - ignoring syscall.
2016/03/27 13:27:57 Error resolving syscall name set_tls: could not resolve name to syscall - ignoring syscall.
total 16

**Comment by runcom** [comment]
That's seccomp, and probably the seccomp golang pkg can't resolve the syscall in the kernel, ping @jfrazelle

**Comment by Ch3ck** [comment]
Thanks @runcom I am using a Fedora 22 system. Each time I run a docker image I usually have this error before anything pops up. @jfrazelle could you help me out here?

**Comment by justincormack** [comment]
I am looking at this, also related to #21533

**Comment by jfrazelle** [comment]
I believe Michael remove the logging

On Sunday, March 27, 2016, Justin Cormack <notifications@github.com> wrote:

> I am looking at this, also related to #21533
> <https://github.com/docker/docker/issues/21533>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/21557#issuecomment-202104649>
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jfrazelle** [comment]
Ya https://github.com/opencontainers/runc/pull/691

On Sunday, March 27, 2016, Jessica Frazelle <me@jessfraz.com> wrote:

> I believe Michael remove the logging
>
> On Sunday, March 27, 2016, Justin Cormack <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> I am looking at this, also related to #21533
>> <https://github.com/docker/docker/issues/21533>
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/docker/docker/issues/21557#issuecomment-202104649>
>>
>
>
> --
>
>
> Jessie Frazelle
> 4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
> pgp.mit.edu
> <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>
>
>

-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by thaJeztah** [comment]
Hm, but this is docker 1.10

@Ch3ck what version of libseccomp is installed on your machine?

**Comment by jfrazelle** [comment]
I just meant the logging was remove so in 1.11 this is fixed

On Sunday, March 27, 2016, Sebastiaan van Stijn <notifications@github.com>
wrote:

> Hm, but this is docker 1.10
>
> @Ch3ck <https://github.com/Ch3ck> what version of libseccomp is installed
> on your machine?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/21557#issuecomment-202123203>
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by justincormack** [comment]
@thaJeztah er yes, good point, although the logging is in libcontainer, I don't understand how it could not affect everyone, so it is very odd.

@Ch3ck if you can upgrade to libseccomp 2.3.0 that should fix this I think, but that is only available in fedora 23. Also it will be fixed in 1.11 as @jfrazelle says. 

Will install some Fedora machines for testing.

**Comment by Ch3ck** [comment]
Hello @thaJeztah @justincormack @jfrazelle the version of libseccomp I'm using is:

Version     : 2.2.0
Release     : 0.fc22

**Comment by Ch3ck** [comment]
Issue fixed with update of libseccomp to 2.3 :smile_cat:

**Comment by thaJeztah** [comment]
good to hear! let me close this issue as a dup of https://github.com/docker/docker/issues/21533, so that we can track it there. Thanks so much for reporting!

**Comment by justincormack** [comment]
I couldn't replicate this with docker 1.10.3, fc22 and libseccomp 2.2.3 which seems to be the current seccomp version in fc22 - this could be due to 2.2.0 vs 2.2.3 though adding these syscalls.

**Comment by Ch3ck** [comment]
@justincormack that's the update with fc22 if you use libseccomp 2.2.0 it causes this error. But apparently with libseccomp 2.2.3 this issue is fixed.

**Comment by justincormack** [comment]
Yes, that was a bit confusing! I think that is why it was missed before, as it was only checked after update.

**Comment by Ch3ck** [comment]
I think so too.
