### ISSUE TITLE
Image layer contents are unstable

### ISSUE THREAD

**Issue by RomanSaveljev** [docker/docker#21555]
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Sat Mar 12 19:18:57 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Sat Mar 12 19:18:57 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 34
Server Version: 1.10.3
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.4.5-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.533 GiB
Name: arch-t530
ID: 4JN7:HILV:O7E4:VSQX:6T67:BSMT:GQEA:G27K:67TD:UIAF:ZRO5:QUBQ
Username: romansaveljev
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

* physical
* Additional files are in https://gist.github.com/RomanSaveljev/55b81155531803d68c52

**Steps to reproduce the issue:**
1. Grab `file-missing.bats` from the gist (see above for the link)
2. Install [bats](https://github.com/sstephenson/bats) (I had it through npm)
3. `yes test/file-missing.bats | head -n 100 | xargs node_modules/.bin/bats | tee test.log`
4. Study the log

**Describe the results you received:**
Test failed 24/100 times (see `test.log`). The reason is that `echo 456 >/a` in the last layer does not create any modifications to `layer.tar`. As we can see this is some sort of flakiness in the image builder.

The issue does not manifest, when I split the troubled command into two, like so:

```
RUN echo 456 >/a
RUN echo def >>/b
```

100 rounds of the same testcase went fine (see `split.log`).

I have attached one faulty image (based on `alpine`) to the same gist for you to examine.

**Describe the results you expected:**

Both `a` and `b` entries exist in the top layer and `a` contents are `456`.

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens 24/100

**Comment by icecrime** [comment]
Thank you for this great issue report! Tentatively adding to the 1.11 milestone.

**Comment by thaJeztah** [comment]
I tried reproducing on a fresh Ubuntu 15.10 droplet on DigitalOcean, but wasn't able to; I tried both aufs and overlay. Info on this machine;

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:59:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:59:07 2016
 OS/Arch:      linux/amd64
```

```
root@ubuntu-2gb-sfo1-01:~/test# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.10.3
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.954 GiB
Name: ubuntu-2gb-sfo1-01
ID: KOOR:OSY4:BHCZ:PDOI:SQFM:MPA7:A6XN:HZ4Z:FN5V:WDIF:J2AX:3THW
Debug mode (server): true
 File Descriptors: 11
 Goroutines: 25
 System Time: 2016-03-28T14:09:52.14303984-04:00
 EventsListeners: 0
 Init SHA1: 277b5324faa1bf512a6fe229d02a3ae0d756a7ef
 Init Path: /usr/lib/docker/dockerinit
 Docker Root Dir: /var/lib/docker
WARNING: No swap limit support
```

**Comment by dmcgowan** [comment]
Just reproduced, only got failure 2/300 though

```
docker version
Client:
 Version:      1.11.0-rc2
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   388f544
 Built:        Fri Mar 25 20:30:45 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0-rc2
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   388f544
 Built:        Fri Mar 25 20:30:45 2016
 OS/Arch:      linux/amd64
```

```
$ docker info
Containers: 11
 Running: 0
 Paused: 0
 Stopped: 11
Images: 248
Server Version: 1.11.0-rc2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.5-300.fc23.x86_64
Operating System: Fedora 23 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.58 GiB
Name: m3800.drizz.net
ID: 2NMV:4JTA:DSQW:X6EP:WPET:BFM7:QJXI:B6J5:YBS7:COCT:4K2D:OCT6
Docker Root Dir: /home/docker/graph-1.10
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 13
 Goroutines: 39
 System Time: 2016-03-28T15:03:19.284123315-07:00
 EventsListeners: 0
Username: dmcgowan
Registry: https://index.docker.io/v1/
```

**Comment by thaJeztah** [comment]
could it be kernel dependent? I'll try a few more times

**Comment by AkihiroSuda** [comment]
| #Experiments | #Reproduced | Storage | Daemon | Kernel | Environment |
| ------------ | ----------- | ------- | ------ | ------ | ----------- |
| 1,000        | 5           | Overlay |1.11.0-dev(79edcc5)| 3.10.0-327.10.1.el7.x86_64 (CentOS 7) | AWS t2.medium |
| 100          | 0           | DM      | ditto | ditto | ditto |
| 1,000         | 0           | Overlay |1.10.3|4.2.0-34-generic (Ubuntu 15.10) | Physical 4-CPU machine |
| 500         | 0           | AUFS    | ditto|ditto | ditto |

It seems to be an overlay bug, but I could not hit on Ubuntu kernel.

**Comment by AkihiroSuda** [comment]
Not sure related or not, but #19647 is a flaky overlay issue as well

**Comment by thaJeztah** [comment]
I also tried another few rounds, and in 600, I got one failure, so I'm able to reproduce (1.10.3 on Ubuntu 15.10 with overlay), but not as frequent as the original reporter

**Comment by dmcgowan** [comment]
Captured the logs for a failure and put it next to a successful run. Nothing too surprising but does support the case that this is not a builder issue but rather an overlay issue. See logs here https://gist.github.com/dmcgowan/f1449140cd060be3ed9755bb55f7b5e5.

The most interesting different is the reported commit size, the failed test reports a smaller size on the second commit indicating that the graphdriver diff operation failed to include any change as we expected. However I see no other diff that the build commands were executed differently.

Successful run
```
time="2016-03-29T11:19:56.961269825-07:00" level=debug msg="Applied tar sha256:86103e72e69fd1e8f2c4a8d41d2caa737ef6eb2336ba9a305d3744e4046accb6 to 5c1456786996c83bc79fc693853
016351a0b8cf5e8bfa54f42a1bc098fce88ba, size: 11" 
```

Failed run
```
time="2016-03-29T11:20:00.487032093-07:00" level=debug msg="Applied tar sha256:2f7d451d85682537e9c590f2721e3a0f4b89d6851356bbb1a55ef9a1fbd518de to e0768822f8f29b21a3f008e23b9
ed2d33842c030de88a349366b797fa03447a5, size: 7" 
```

**Comment by RomanSaveljev** [comment]
I could not reproduce it in 1000 rounds with devicemapper driver in the otherwise same setup. I can not try with AUFS (need to rebuild kernel).

**Comment by icecrime** [comment]
Thanks @dmcgowan @RomanSaveljev for all the information. This seems like a tricky problem indeed.

As far as I can tell, this is not a regression from 1.10.3, so I'll remove it from the 1.11 milestone. This doesn't mean that we'll just forget about the issue, but I'm afraid the next step will involve diving into the kernel to figure out if it's overlay specific.

Ping @tonistiigi for info, and ping @runcom if you have a good idea (or the time to bisect that).

**Comment by AkihiroSuda** [comment]
I made a shorter reproducer:
```dockerfile
# One-line bats-less reproducer for docker/docker#21555 (overlay issue)
#
# Locally 50% reproducible on my B2D v1.10.3 on VirtualBox
#
# Usage:
#  host$ docker-machine create -d virtualbox --engine-storage-driver overlay dm1
#  host$ docker-machine ssh dm1
#   dm1$ git clone https://github.com/AkihiroSuda/test21555 && cd test21555 && (for f in $(seq 1 100); do docker build -t test21555 -q --no-cache .; echo Exp $f: $?; docker rmi test21555 > /dev/null; done) | tee /tmp/test21555.log
FROM alpine:latest
ARG X=foo
ARG Y=bar
RUN echo ${X} > /testfile
RUN echo ${Y} > /testfile
RUN cat /testfile; [ $(cat /testfile) == "${Y}" ]
```

I tested on Boot2Docker v1.10.3:

|X|Y|Reproducibility(tested 100 times)|
|---|---|---|
|foo|bar|54%|
|foo|bar1|0%|
|foo1|bar|0%|

The result suggests that __the cause of the issue is related to the file length__;
we can (perhaps always) avoid the issue when the file is resized.
But we intermittently hit the issue when the file size is kept.

I hope my result is helpful for identifying the cause.

**Comment by RomanSaveljev** [comment]
@AkihiroSuda excellent job!

**Comment by tonistiigi** [comment]
This is happening because the `NaiveDiffDriver` uses full second precision in its changes algorithm(because tar doesn't have subseconds).

A couple of ways to fix this. First is a very hacky way to sleep until a next second between the layers. https://github.com/docker/docker/compare/master...tonistiigi:sleep-between-layers?expand=1

Other solution would be to start comparing the nanoseconds. https://github.com/docker/docker/compare/master...tonistiigi:naivediff-compare-nanosec?expand=1 This is riskier but should work because everything that uses non-zero nanosecond should be on a fresh layer anyway. Problem with this solution is also that it breaks most of the archive packages unit tests(for good reasons on the first look).

**Comment by AkihiroSuda** [comment]
+1 @tonistiigi 

The issue is reproducible with other storage drivers that use `NaiveDiffDriver`.
I confirmed that the issue is locally 60% reproducible with the VFS driver (on B2D v1.10.3).
So `area/storage/overlay` tag should be removed.


Even on VFS, I could not reproduce the issue when the file is resized. https://github.com/docker/docker/issues/21555#issuecomment-203311261
I'm still not sure why the file size affects the reproducibility.

**Comment by thaJeztah** [comment]
ping @aaronlehmann what do you think would be the best solution? "1" or "2" https://github.com/docker/docker/issues/21555#issuecomment-203707574?

**Comment by aaronlehmann** [comment]
I'm not sure I'm qualified to give an opinion on this, since I'm not very familiar with the graph drivers.

But TBH I don't like either solution. It seems fundamentally wrong to rely on timestamps to check if files have different contents.

Presumably the kernel knows which files have changed between the parent layer and the child layer of an overlayfs. Is there a way to query this directly instead of using `NaiveDiffDriver`?

If we must use `NaiveDiffDriver`, I would consider combining the two approaches. Sleep for, say, 1 ms, between layers to improve the chances that the mtimes will be different, and also use a higher resolution comparison of mtimes.

**Comment by dmcgowan** [comment]
@AkihiroSuda The function you pointed to is actually only used for AUFS, the same code which is relevant to NaiveDiffDriver is https://github.com/tonistiigi/docker/blob/b1d597498f7d64ad912a986c4b881a4dae4b04fd/pkg/archive/changes.go#L250 and here for size comparison
https://github.com/tonistiigi/docker/blob/b1d597498f7d64ad912a986c4b881a4dae4b04fd/pkg/archive/changes_unix.go#L20

**Comment by AkihiroSuda** [comment]
Thanks!
