### ISSUE TITLE
Add Docker command completion to docs

### ISSUE THREAD

**Issue by arun-gupta** [docker/docker#21551]
Just like https://docs.docker.com/compose/completion/, it would be useful to have https://docs.docker.com/engine/completion/

This is already answered at:

http://stackoverflow.com/questions/26132451/how-to-add-bash-command-completion-for-docker-on-mac-os-x

**Comment by thaJeztah** [comment]
Yes, I think something like that can be helpful. Actually on Linux we *do* install the zsh and fish completion scripts, but (unless it's done somewhere else) the Bash completion scripts are not installed? https://github.com/docker/docker/blob/master/hack/make/.build-deb/docker-engine.install#L6-L7

For Windows and OS X, perhaps these should be installed by Docker Toolbox, and Docker for Mac / Docker for Windows

**Comment by justincormack** [comment]
There is an outstanding/in progress issue to install these in docker4mac/windows, its a bit complicated as the install method depends on local setup and there are no standard ways to install completion on these OSs.

**Comment by thaJeztah** [comment]
@jfrazelle do you know why the zsh and fish completion scripts are installed by the debs, but not the bash ones? Or am I looking at the wrong place?

**Comment by jfrazelle** [comment]
It is installed by the debs I believe they are talking about osx

**Comment by jfrazelle** [comment]
https://github.com/docker/docker/blob/master/hack/make/.build-deb/docker-engine.bash-completion

**Comment by thaJeztah** [comment]
Oh, it's in a separate file, confusing

**Comment by arun-gupta** [comment]
The command in StackOverflow did not work for me. I was expecting `docker r<TAB>` to show me the list of available commands. What am I doing incorrectly?

**Comment by arun-gupta** [comment]
@justincormack @thaJeztah any updates on this?

**Comment by craighurley** [comment]
I'm running docker 1.11.1 beta 12
```
$ docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   8b63c77
 Built:        Tue May 10 10:39:20 2016
 OS/Arch:      linux/amd64
```

... and homebrew solved this for me:

```
brew install docker-completion
brew install docker-compose-completion
```

**Comment by justincormack** [comment]
Docker for mac installs the completions but does not (yet) configure them automatically as it is a bit complicated (they have external dependencies). The install instructions are at https://docs.docker.com/docker-for-mac/#/installing-bash-completion

I am going to close this as it is now documented. We hope to install more automatically in future.
