### ISSUE TITLE
mipsel or mips64el support?

### ISSUE THREAD

**Issue by vanloswang** [docker/docker#21569]
I find some one use gccgo to build docker for PPC or MIPS machines, and I find out that golang 1.6 is support to compile mipsel and mips64el binarys.
The way of official docker build is to build docker in docker, and there is not official Dockerfile for MIPS.
is there some way to build docker for mipsel or mips64el machines BY USING GOLANG binarys?

**Comment by tiborvass** [comment]
@vanloswang https://github.com/docker/docker/blob/master/project/PACKAGERS.md should help you build docker outside docker. Hope this helps.
