### ISSUE TITLE
What is the command for integration tests of userns check?

### ISSUE THREAD

**Issue by sunyuan3** [docker/docker#21565]
8 checks(docker/dco-signed,documentation,experimental,gccgo,janky,userns,win2lin,windowsTP4) would be executed when a pull request is created.

I can execute integration tests of janky check in the following command.
docker run -d --privileged -v `pwd`:/go/src/github.com/docker/docker rnd-dockerhub.huawei.com/library/dockercore-docker:latest bash -c "cd /go/src/github.com/docker/docker && ./hack/make.sh binary test-integration-cli"

What is the command for integration tests of userns check?

**Comment by coolljt0725** [comment]
Set `DOCKER_REMAP_ROOT`  environment to enable the userns integration test

**Comment by sunyuan3** [comment]
Many thanks.
