### ISSUE TITLE
Dockerfile Kate synatax definition uses deprecated syntax

### ISSUE THREAD

**Issue by AlexCzar** [docker/docker#21571]
Kate
Version 3.14.9
Using KDE Development Platform 4.14.9
Dockerfile.xml: https://github.com/docker/docker/raw/master/contrib/syntax/kate/Dockerfile.xml latest commit: https://github.com/docker/docker/commit/3781cde61ff10b1d9114ae5b4c5c1d1b2c20a1ee

**Steps to reproduce the issue:**
1. put Dockerfile.xml into $KDEDIR/share/apps/katepart/syntax
2. open a Dockerfile

**Actual results:**
Kate shows a warning:
```
/home/username/.kde4/share/apps/katepart/syntax/Dockerfile.xml:Deprecated syntax. Context dollar not addressed by a symbolic name
/home/username/.kde4/share/apps/katepart/syntax/Dockerfile.xml:Deprecated syntax. Context dollar not addressed by a symbolic name
```

**Expected results:**
Syntax highlighted Dockerfile opens without warnings or errors

**Dirty fix:**

`sed -i 's/dollar/#stay/' Dockerfile.xml`

**Comment by AlexCzar** [comment]
All that information is irrelevant as this issue does not concern Docker engine or utilities themselves but instead applies to a contrib syntax highlight script.

**Comment by thaJeztah** [comment]
@AlexCzar since I don't use KDE Development Platform (and I don't think anyone of the maintainers), would you be interested in providing an updated version for that file, and opening a PR?

**Comment by thaJeztah** [comment]
If there's no interest in updating, it's probably better to remove that file, but just my 0.02c

**Comment by jamtur01** [comment]
I don't use Kate anymore so if someone wants to update fine otherwise remove seems reasonable.

**Comment by thaJeztah** [comment]
Thanks @jamtur01, we'll go for removing it as nobody here is using it as well, and we couldn't find an up-to-date version elsewhere
