### ISSUE TITLE
no --subnetwork option as specified in docs for work-with-networks.md

### ISSUE THREAD

**Issue by kamigerami** [docker/docker#21581]
As specified in the docs/userguide/networking/work-with-networks.md.

one might think there is an actual --subnetwork option to specify on the cli.

Fixing typo.

line 81 +In addition to the `--subnetwork` option, you also specify the `--gateway` `--ip-range` and `--aux-address` options.

It should most likely be '--subnet' option.

**Comment by kamigerami** [comment]
#dibs

**Comment by thaJeztah** [comment]
fixed by https://github.com/docker/docker/issues/21582, but GitHub didn't auto-close

thanks @kamigerami!
