### ISSUE TITLE
start container without mounting shm into container

### ISSUE THREAD

**Issue by allencloud** [docker/docker#21609]
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
root@ubuntu:~# docker info
Containers: 6
 Running: 4
 Paused: 0
 Stopped: 2
Images: 8
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 63
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-46-generic
Operating System: Ubuntu 14.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: ubuntu
ID: 2HT4:3WC7:54TS:REFK:TREC:FK5A:JVX7:7JVW:JAYV:KGQL:JURW:6HXV
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
root@ubuntu:~# uname -a
Linux ubuntu 3.13.0-46-generic #76-Ubuntu SMP Thu Feb 26 18:52:13 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Describe the results you received:**
Error deleting container: Error response from daemon: Unable to remove filesystem for 36bd1b1d3660775ab7de8c8ac0f11870ec55f7ad4f6bc82488c07988c3681130: remove /var/lib/docker/containers/36bd1b1d3660775ab7de8c8ac0f11870ec55f7ad4f6bc82488c07988c3681130/shm: device or resource busy

issue same as 
#21111
#17902 

I hope we can support an option in `docker run`, and this option is named by `--no-shm`.
If we use this option, we can start a container without mounting shm. 

This way can help docker users have more rights to customize their container environment which I think is very reasonable.

And maybe shm is a kind of example, something else can be added to this consideration, too.

**Comment by phemmer** [comment]
Why not just fix the issue instead of removing shm?

**Comment by thaJeztah** [comment]
I don't think we should do this, and indeed try to get the issue fixed. I'll close this, because I don't see us implementing this

**Comment by marszhe** [comment]
why we must need shm enabled in a container ? ping @thaJeztah

**Comment by thaJeztah** [comment]
@marszhe see https://github.com/moby/moby/pull/34087 (which allows setting the default), and https://github.com/moby/moby/pull/35621
