### ISSUE TITLE
API: GET /volumes should return a list

### ISSUE THREAD

**Issue by johnflavin** [docker/docker#21605]
Every part of the remote API that returns a collection of objects (`GET /images/json`, `GET /containers/json`, `GET /events`, etc.) returns its values as a JSON list of objects: `[{...}, {...}, ...]`. Every part, that is, except `GET /volumes`. That endpoint returns an object of one element whose value is a list: `{ "Volumes": [{...}, {...}, ...] }`. This is still the case in the [most recent dev Remote API Docs](https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api_v1.24.md#list-volumes).

Is there a reason `GET /volumes` is inconsistent with the rest of the API? If there is no reason, I ask that it be made to return a flat list.

**Comment by cpuguy83** [comment]
It also returns a list of warnings/errors.

**Comment by johnflavin** [comment]
Two follow-up questions:
1. Shouldn't the `"Warnings"` key in the returned value be documented? It currently isn't.
2. The only other places I know of in the API where the return is `{..., "Warnings": [...]}` is on creation events: [container](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#create-a-container), [exec](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#exec-create), and [network](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#create-a-network). Why return it here when getting a list of volumes, but nowhere else in the API when getting lists? And why not return `"Warnings"` when creating a volume, like all the other POSTs to create things?

**Comment by cpuguy83** [comment]
On create, there is no chance of a warning. You either get a volume, or you get an error.

On List, we query every loaded volume driver, and need a way to notify the user that we couldn't query a specific driver.

Yep, it should get documented. Warnings were added after the initial implementation (though planned for) but the API docs were not updated.

**Comment by HackToday** [comment]
I think @johnflavin some comment make sense, as network also use plugin driver ways.

It is better for volume and network use consistent API to handle that. Different API response is confusing and not friendly. We only need to think about what's the best practice

**Comment by cpuguy83** [comment]
We won't change the API. It's in multiple released versions.

**Comment by yongtang** [comment]
I just created a pull request #21638 to add the "Warnings" field in the related documentations. I tried with several versions of the Docker. It seems that this field is only available in 1.10 (v1.22), not in 1.9 (v1.21). So only the documentations in v1.22, v1.23, and v1.24 are updated.

**Comment by thaJeztah** [comment]
I'll close now that the changes to the documentation have been merged
