### ISSUE TITLE
 Base Device UUID and Filesystem verification failed upon restarting docker

### ISSUE THREAD

**Issue by jonseymour** [docker/docker#21606]
**Output of `docker version`:**

Captured from similar machine

```
DEBU[2971] Calling GET /v1.22/version                   
DEBU[2971] GET /v1.22/version                           
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
# docker isn't starting
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running in Ubuntu 14.04.4 VM under Azure.

Output of uname -a:

```Linux hems-hub 3.19.0-49-generic #55~14.04.1-Ubuntu SMP Fri Jan 22 11:24:31 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux```

**Steps to reproduce the issue:**
1. attempted to restart docker

**Describe the results you received:**

```
....
DEBU[0000] devmapper: Added deviceId=682 to DeviceIdMap 
DEBU[0000] devmapper: Added deviceId=213 to DeviceIdMap 
DEBU[0000] devmapper: Added deviceId=56 to DeviceIdMap  
DEBU[0000] devmapper: Added deviceId=271 to DeviceIdMap 
DEBU[0000] devmapper: Added deviceId=723 to DeviceIdMap 
DEBU[0000] devmapper: constructDeviceIDMap() END        
DEBU[0000] devmapper: activateDeviceIfNeeded()          
DEBU[0000] devmapper: Error device setupBaseImage: devmapper: Base Device UUID and Filesystem verification failed.devicemapper: Error running deviceCreate (ActivateDevice) dm_task_run failed 
DEBU[0000] Cleaning up old shm/mqueue mounts: start.    
FATA[0000] Error starting daemon: error initializing graphdriver: devmapper: Base Device UUID and Filesystem verification failed.devicemapper: Error running deviceCreate (ActivateDevice) dm_task_run failed 
```

**Describe the results you expected:**

Docker starts

**Additional information you deem important (e.g. issue happens only occasionally):**

`DOCKER_OPTS=--storage-driver=devicemapper --storage-opt dm.datadev=/dev/datavg/docker-data --storage-opt dm.metadatadev=/dev/datavg/docker-meta`

Output of blkid

```
...
/dev/sdc: UUID="MkggW3-1uxH-eDYF-L7w2-AvFf-aus0-P2UMpl" TYPE="LVM2_member" 
/dev/mapper/datavg-spherestack: UUID="1cb2c312-33a5-4b21-a32f-240d5cd8006e" TYPE="ext4" 
/dev/mapper/datavg-backups: UUID="10c711ff-e24c-4fbd-9747-5c59abefe4c7" TYPE="ext4" 
```

Output of ls -ltr /dev/mapper:

```
ls -ltr /dev/mapper
total 0
crw------- 1 root root 10, 236 Mar 29 01:32 control
lrwxrwxrwx 1 root root       7 Mar 29 01:32 datavg-backups -> ../dm-3
lrwxrwxrwx 1 root root       7 Mar 29 01:32 datavg-spherestack -> ../dm-2
lrwxrwxrwx 1 root root       7 Mar 29 02:13 docker-8:1-1052708-pool -> ../dm-4
lrwxrwxrwx 1 root root       7 Mar 29 02:13 datavg-docker--meta -> ../dm-1
lrwxrwxrwx 1 root root       7 Mar 29 02:13 datavg-docker--data -> ../dm-0
```

Output of blkid /dev/dm-4:

```
```

(e.g. empty)

Output of dmesg:

```
[   14.074762] device-mapper: thin: Data device (dm-0) discard granularity larger than a block: Disabling discard passdown.
[   14.277748] device-mapper: table: 252:5: thin: Couldn't open thin internal device
[   14.277749] device-mapper: ioctl: error adding target to table

```

Output of `cat /var/lib/docker/devicemapper/metadata/deviceset-metadata`:

```
{"next_device_id":731,"BaseDeviceUUID":"ccdb3627-6f38-44cd-afaf-7d03c519abb4","BaseDeviceFilesystem":"ext4"}
```

Output of `ls blk`:
```
NAME                               MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda                                  8:0    0  29.3G  0 disk 
└─sda1                               8:1    0  29.3G  0 part /
sdb                                  8:16   0    14G  0 disk 
└─sdb1                               8:17   0    14G  0 part /mnt
sdc                                  8:32   0   512G  0 disk 
├─datavg-docker--data (dm-0)       252:0    0   128G  0 lvm  
│ └─docker-8:1-1052708-pool (dm-4) 252:4    0   128G  0 dm   
├─datavg-docker--meta (dm-1)       252:1    0     4G  0 lvm  
│ └─docker-8:1-1052708-pool (dm-4) 252:4    0   128G  0 dm   
├─datavg-spherestack (dm-2)        252:2    0   128G  0 lvm  /var/lib/sphere-stack
└─datavg-backups (dm-3)            252:3    0   128G  0 lvm  /var/lib/backups
sdd                                  8:48   0   128G  0 disk 
└─sdd1                               8:49   0   128G  0 part 
sr0                                 11:0    1   1.1M  0 rom  
```

Some output from ```dmesg | egrep "sdc|scsi":

```
[    8.221588] scsi host5: storvsc_host_t
[    8.224955] scsi 5:0:0:0: Direct-Access     Msft     Virtual Disk     1.0  PQ: 0 ANSI: 4
[    8.228258] scsi 5:0:0:1: Direct-Access     Msft     Virtual Disk     1.0  PQ: 0 ANSI: 4
[    8.299357] sd 5:0:0:0: Attached scsi generic sg3 type 0
[    8.301006] sd 5:0:0:0: [sdc] 1073741824 512-byte logical blocks: (549 GB/512 GiB)
[    8.302887] sd 5:0:0:1: Attached scsi generic sg4 type 0
[    8.317444] sd 5:0:0:0: [sdc] 4096-byte physical blocks
[    8.320316] sd 5:0:0:0: [sdc] Write Protect is off
[    8.322285] sd 5:0:0:0: [sdc] Mode Sense: 0f 00 10 00
[    8.322427] sd 5:0:0:0: [sdc] Write cache: enabled, read cache: enabled, supports DPO and FUA
[    8.326340]  sdc: unknown partition table
[    8.329291] sd 5:0:0:0: [sdc] Attached SCSI disk
```

The issue occurred when I restarted the docker service while investigating an unrelated issue. 

There have not been any attempts to resize lvs and AFAIK there devices all have plenty of room.

Output of dmsetup table:

```
docker-8:1-1052708-pool: 0 268435456 thin-pool 252:1 252:0 128 32768 1 skip_block_zeroing 
datavg-spherestack: 0 268435456 linear 8:32 276826112
datavg-docker--data: 0 268435456 linear 8:32 2048
datavg-backups: 0 268435456 linear 8:32 545261568
datavg-docker--meta: 0 8388608 linear 8:32 268437504
```

**Comment by DingGuodong** [comment]
CentOS Linux release 7.2.1511 (Core) **has same question.**
output of 'uname -a' command:
`Linux example_fqdn_name 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
Output of docker daemon's log message:
`FATA[0000] Error starting daemon: error initializing graphdriver: devmapper: Base Device UUID and Filesystem verification failed.devicemapper: Error running deviceCreate (ActivateDevice) dm_task_run failed `
Boot opions:
`ls /dev/sdb
pvcreate /dev/sdb
pvs
vgcreate vg-docker /dev/sdb
vgs
lvcreate -L 4G -n lv-docker_metadata vg-docker
lvcreate -l 100%FREE -n lv-docker_data vg-docker
/usr/bin/docker daemon --log-level=info \
    --storage-driver=devicemapper \
    --storage-opt dm.datadev=/dev/vg-docker/lv-docker_data \
    --storage-opt dm.metadatadev=/dev/vg-docker/lv-docker_metadata`

**Comment by jonseymour** [comment]
I am going to close this issue since I suspect the thin pool device got damaged by my attempts to repair it with this_repair after the initial problem arose. I will open another report if the spontaneous failure occurs again.

**Comment by jonseymour** [comment]
I have an inkling about how the situation arose. 

I used ansible (in particular, this role - https://github.com/angstwad/docker.ubuntu)  to setup the disks and the install docker. I think the issue arose that docker was initially started in the loop-lvm mode and was then reconfigured to use with direct-lvm mode without an intervening restart of docker. Docker was then extensively configured with the thin pool device bound to the loopback devices rather than the actual LVM logical volumes. Of course, when docker was eventually restarted with the intended storage options, the new thin pool device was effectively uninitialised.

I am going to see if I can reproduce the issue and will consider raising an issue against the ansible role.

**Comment by jonseymour** [comment]
For completeness, my issues were caused by the failure of the ansible role I was using to fully restart the docker daemon when new storage options were configured as part of the docker setup process. This resulted in the daemon adding new images to the loop back thin pool device, rather than the intended volume group backed thin pool device. When the daemon was eventually restarted with the configured storage options, the meta data no longer matched the (still uninitialised thin pool device), so that daemon refused to start.

The issue is documented here: https://github.com/angstwad/docker.ubuntu/issues/89 and a PR is documented here https://github.com/angstwad/docker.ubuntu/pull/90
