### ISSUE TITLE
Need better handling/error path from tar/untar failures (especially in userns)

### ISSUE THREAD

**Issue by estesp** [docker/docker#21626]
When using user namespaces, it is easier to hit tar/untar failures due to permissions or ownership issues that affect the remapping code.  Most of these errors are easy to spot in daemon logs, but usually lead to confusing errors on the client-side.

For example, if a layer is created which has an ID owner or group outside the remapping range specified for the daemon, the remapping code won't be able to handle what uid/gid to use when writing that file to local cache.  An example of this from a daemon log:

```
ERRO[0006] Handler for POST /v1.24/images/load returned error: Untar re-exec error: exit status 1: output: Container ID 208203 cannot be mapped to a host ID
```

On the client side, this ends up causing an error in interpreting this error output string as a JSON object and getting something like this:

```
5e868bdcb028: Loading layer [==================================================>] 16.27 MB/16.27 MB
3c35e36d8df2: Loading layer [==================================================>] 23.04 MB/23.04 MB
invalid character 'U' looking for beginning of value
```

These errors need to be correctly brought all the way back to the user so appropriate action can be taken.

**NOTE**: _The mapping ID out of range issue is only an example and could be seen as a separate issue, which can be temporarily corrected by providing the remapping user a larger range that includes all possible uid/gid values for container images being loaded or pulled from a registry. Some guidance should also be provided to image creators on the default range for an ID space, especially when using distro defaults for `/etc/subuid` and `/etc/subgid` which are always 64K today._

**Comment by pnovotnak** [comment]
I'm encountering this in real-world usage. In my case a user built an image on their MacBook in a docker-machine VM. I asked him to do a `docker version` and this is the output;

    Client:
    Version:      1.8.3
    API version:  1.20
    Go version:   go1.4.2
    Git commit:   f4bf5c7
    Built:        Mon Oct 12 18:01:15 UTC 2015
    OS/Arch:      darwin/amd64

    Server:
    Version:      1.8.3
    API version:  1.20
    Go version:   go1.4.2
    Git commit:   f4bf5c7
    Built:        Mon Oct 12 18:01:15 UTC 2015
    OS/Arch:      linux/amd64

They then pushed it to the hub. Now, on a box where I have multiple `docker` 1.11 daemons running under user namespaces, pulling the container produces the following output;

    $ docker pull cyrusbio/a-container

    Using default tag: latest
    latest: Pulling from cyrusbio/a-container

    xxxxxxxxxxxx: Pull complete
    xxxxxxxxxxxx: Pull complete
    xxxxxxxxxxxx: Pull complete
    xxxxxxxxxxxx: Pull complete
    xxxxxxxxxxxx: Pull complete
    xxxxxxxxxxxx: Pull complete
    xxxxxxxxxxxx: Pull complete
    xxxxxxxxxxxx: Pull complete
    xxxxxxxxxxxx: Pull complete
    xxxxxxxxxxxx: Pull complete
    xxxxxxxxxxxx: Pull complete
    xxxxxxxxxxxx: Pull complete
    xxxxxxxxxxxx: Pull complete
    xxxxxxxxxxxx: Pull complete
    xxxxxxxxxxxx: Extracting [==================================================>] 982.4 kB/982.4 kB
    failed to register layer: Untar re-exec error: exit status 1: output: Container ID xxxxxxxxxx cannot be mapped to a host ID

Where the docker daemon is not remapping permissions everything seems to work as expected. We've tried totally wiping out the docker data directory to no effect.

Going to see if this works;
cc @javierbq
cc @yfsong

**Comment by LK4D4** [comment]
@estesp by any chance do you know if anything was done?

**Comment by estesp** [comment]
It was on my list of things to revisit "someday".. but given the message above from way back in 1.8.3, maybe a change in flow of messages back to the client already happened, as the user is getting an appropriate message about ID translation failure.

Maybe I just need to re-test on 1.13-rc and verify there isn't something to fix.

**Comment by LK4D4** [comment]
@estesp would be cool, thanks!

**Comment by estesp** [comment]
Hmm..seems like this can be closed. This is 1.12.3:
```
latest: Pulling from estesp/highid
56bec22e3559: Pull complete
db1fc09de40c: Extracting [==================================================>]    136 B/136 B
failed to register layer: Error processing tar file(exit status 1): Container ID 1000000 cannot be mapped to a host ID
```

Which has a totally reasonable message about why

**Comment by LK4D4** [comment]
@estesp nice! Thanks!
