### ISSUE TITLE
[1.11-rc2] provide raw binary downloads

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#21621]
It would be nice if I could still `curl` the four binaries I need now for Docker.  The reason being is that I have a lot of dockerfiles like the below that run in scratch or a similar environment that doesn't have tar.

`RUN curl -o ./docker_amd64 -L https://get.docker.com/builds/Linux/x86_64/docker-1.10.2`

I know it's possible to `ADD http://....tgz` but that puts the files at `/usr/local/bin` which is not where my existing script may expect it to be.  It would be a nice convenience to have the raw download URLs available.

**Comment by icecrime** [comment]
See 321530.

**Comment by thaJeztah** [comment]
@ibuildthecloud if the .tgz didn't have a wrapping directory for the binaries, would that solve your use-case? i.e.

    ADD https://get.docker.com/builds/Linux/x86_64/docker-1.11.0.tgz /some/path

@kencochrane opened a PR for this, perhaps you can comment on the PR? https://github.com/docker/docker/pull/21625

**Comment by ibuildthecloud** [comment]
@thaJeztah I think if there was no wrapping directory in the tar that would be sufficient for my use case.

**Comment by icecrime** [comment]
Closed by #21625.

**Comment by cpuguy83** [comment]
Fixed by #21625

**Comment by cpuguy83** [comment]
Damn!

**Comment by cpuguy83** [comment]
Race condition on checking if issue is closed before closing.

**Comment by ibuildthecloud** [comment]
@thaJeztah @icecrime I'd like to reopen this issue.  I tried this with rc3 and found two issues.

1) The directory in the tar is `docker/` so I can't place the binaries in `/usr/bin` for example using `ADD`
2) `ADD https://test.docker.com/builds/Linux/x86_64/docker-1.11.0-rc3.tgz ...` doesn't actually work but instead creates a called `docker-1.11.0-rc3.tgz`.  Does extracting of tgz not work with URLs and only local files?

**Comment by cpuguy83** [comment]
@ibuildthecloud Correct... One of the many magic wonders of the builder.
