### ISSUE TITLE
Cant access Web UI's application tracker link - Spark on Docker

### ISSUE THREAD

**Issue by MahalakshmiL** [docker/docker#21635]
I installed Spark using docker on MAC. I ran into the issue that I wasn't able to access resource manager web ui. 
 but resolved after adding ports: for i in {10000..10999}; do
VBoxManage modifyvm "boot2docker-vm" --natpf1 "tcp-port$i,tcp,,$i,,$i";
VBoxManage modifyvm "boot2docker-vm" --natpf1 "udp-port$i,udp,,$i,,$i";
done

But I have another issue: In the resource manager web ui for spark , there is another link: application tracker - but I am not able to access it. Any help with this ?

**Comment by thaJeztah** [comment]
@MahalakshmiL ehm, just to prevent confusion, you say you installed "docker on MAC", with that you mean http://github.com/docker/toolbox or the new "Docker for Mac" which is now in beta? https://blog.docker.com/2016/03/docker-for-mac-windows-beta/

**Comment by thaJeztah** [comment]
Also, I don't have experience with Spark, and a link not working in the control panel may not be an issue with Docker; could you give some more information? What error are you getting then opening that link, what URL does it try to open?

Perhaps you could add the steps needed to reproduce (e.g., is this a custom Dockerfile you built, or is there an image on Docker Hub that you're using?)

**Comment by thaJeztah** [comment]
Closing as we didn't get a response
