### ISSUE TITLE
DOCKER_RAMDISK no longer supported in 1.11.0-rc2

### ISSUE THREAD

**Issue by justincormack** [docker/docker#21631]
DOCKER_RAMDISK is documented still for a system root running on a ramdisk. Since the 1.11 runc changes this no longer exists, although it is still in the docs. runc does have a mechanism to support this with a NoPivotRoot option, but it is not wired through.

I don't know how many people are using this, it has been raised in various issues. Docker for Mac and Windows are but I am planning to pivot away from this(!).

Have now removed requirements for this there, but other people might be using it possibly. AT least the docs should be updated if we decide to drop support.

**Comment by justincormack** [comment]
```
docker version
Client:
 Version:      1.11.0-rc2
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   388f544
 Built:        Fri Mar 25 20:30:45 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0-rc2
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   388f544
 Built:        Fri Mar 25 20:30:45 2016
 OS/Arch:      linux/amd64
docker:~# docker info
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 1
Server Version: 1.11.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 7
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.1.19
Operating System: Alpine Linux v3.3
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 997.1 MiB
Name: docker
ID: AH23:RYNY:HJVK:E7UA:OC66:JRP7:32J4:CXKH:7ADY:KBGL:YS2A:WQYB
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Comment by thaJeztah** [comment]
nice catch!

**Comment by ibuildthecloud** [comment]
I use it, extensively.  This will be a major issue if I can't run from an initrd.

**Comment by ibuildthecloud** [comment]
@crosbymichael Is there a particular reason why we might want to drop support for switch root?  Being able to run from an initrd is a pretty fundamental thing for PXE booted servers, even if it is just to bootstrap installation to disk.

**Comment by justincormack** [comment]
@ibuildthecloud I assume it was accidental, it is a weird option being the only environment variable that configures docker - it should perhaps be a command line option for the daemon. There are also no tests I think, it is a bit hard to test. Also I was wondering a while back if the `mount --bind` behaviour should just be the default anyway, regardless of whether you are using a ramdisk, I don't really see an advantage in `pivot_root` (which seems to be semi-deprecated), but I haven't looked in detail if there are any differences.

You can run from an initrd without a physical disk and not use this - you need to switch root to anything that is not the initrd, eg a tmpfs. For example adding the following shell script as `/init` will fix the issue on pretty much any setup (that is how I fixed docker for mac/win):

```
#!/bin/sh
/bin/mount -t tmpfs tmpfs /mnt
/bin/cp -a / /mnt 2>/dev/null
exec /sbin/switch_root /mnt /sbin/init
```

**Comment by tonistiigi** [comment]
> runc does have a mechanism to support this with a NoPivotRoot option, but it is not wired through.

This is a libcontainer option. Docker has no dependency on libcontainer any more.

Runc PR to add support for `no-pivot` https://github.com/opencontainers/runc/pull/710

**Comment by thaJeztah** [comment]
@tonistiigi https://github.com/opencontainers/runc/pull/710 was merged :+1:

**Comment by ibuildthecloud** [comment]
Thanks!
