### ISSUE TITLE
Does docker save / load work cross all versions?

### ISSUE THREAD

**Issue by half-dead** [docker/docker#21647]
Like "docker save" a image on docker 1.9.1, then transfer the file to another "docker 1.3" host, or the contrary.

I've tested 'docker save' on docker 1.9.1, then 'docker load' it on docker 1.3.2, then docker run, it seems that nothing went wrong.

Just to make sure, cause there are almost all versions from docker 1.3 to docker 1.9 running in our production environment, and we are considering distributing docker images in a new fashion, using BitTorrent.

**Comment by HackToday** [comment]
I think before content-addressable image introduced in 1.10.0,  images `docker save /load` would work cross versions, because it is standard image format.

for content-addressable image, which means if you had one from 1.10.0  to load in 1.3.2, I am not quite sure if it work. 

But @thaJeztah  may know more about it

**Comment by thaJeztah** [comment]
I don't think there's a guarantee that will work as (as @HackToday mentioned), the local format changed between versions.

@stevvooe may be able to provide more information, but I think the short answer is "no"

**Comment by stevvooe** [comment]
For the most part, it should be backwards compatible but I think we only guarantee compatibility a few versions back. The formats aren't _that_ different and we maintain the same files in the save/load files to ensure this works. I do have to warn that you are opening yourself up to a number of security issues pre-1.9, but that may be less of a problem if you are distributing through a different mechanism than push/pull. The actually security will be driven by the level of content verification in whatever bittorrent system you cook up (hint: md5 in bt won't be enough).

@half-dead As with anything, I'd recommend you try it and test it out.

**Comment by thaJeztah** [comment]
Let me close this issue, as it's not a bug report, but feel free to continue the conversation
