### ISSUE TITLE
can not delete own bridge interface

### ISSUE THREAD

**Issue by gqtc** [docker/docker#21644]
my docker version is:
`Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:39:25 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:39:25 2016
 OS/Arch:      linux/amd64`

I has created own bridge:
`docker network create -d bridge my-bridge-network`

and the birdge interface is 
`br-c6198f9bb78a: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.18.0.1  netmask 255.255.0.0  broadcast 0.0.0.0
        ether 02:42:f1:93:af:38  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0`

but when I delete the my-bridge-network, delete the interface br-c6198f9bb78a,while reboot the docker ,the interface br-c6198f9bb78a is auto created by docker!!!

**Comment by aboch** [comment]
@gqtc Can you please explain a little more the steps to reproduce the issue.
You issued a `docker network rm my-bridge-network` while you were restarting the docker daemon. Is that correct ? 
Also, if you can reproduce, please also post the debug level logs. That would clarify what is happening.

Thanks

**Comment by gqtc** [comment]
sorry, i can not reproduce the issue now, close it!
