### ISSUE TITLE
[NFR] Mount container dir to host

### ISSUE THREAD

**Issue by nejtr0n** [docker/docker#21646]
Let me introduce my case.
There is an nodejs app, which install markup development environment. Thereis no "entry directory",
where I could work. All structure is in use.

And if we mount host folder to container, it just replace it.
It would be greate to point some container dir to specific host dir (symlink), work with it, and than commit changes to container.
I think I could mount this directory manually, but it should be "legal" mount.

**Comment by thaJeztah** [comment]
Thanks for opening this issue @nejtr0n, I'm not fully sure I understand what you're proposing; could you show a practical (but simple) example on what you would like to see implemented?

**Comment by nejtr0n** [comment]
We have debian container for exmple. Home dir contains some folders, pictures, etc.
I need any key to start application like
docker run -d -P --name web -new_key /container_dir:/host_dir training/webapp python app.py
For example:
docker run -d -P --name web -new_key /home:/mnt/container_home python app.py
(The opposite key for -v key)

I'm trying to dockerize this suite - https://en.bem.info/technology/bemhtml/v2/intro/ (Installing nodejs and npm). It contains some directories with pre-installed config files, libraries after installation.
And I don't know, how to point them to host machine (with content) to start working with them. (SSH is urgly way)

From my point of view, there are various applications like that.

**Comment by thaJeztah** [comment]
I think you'll already be able to do this using a volume-driver plugin. There's some plugins that allow you to mount a shared filesystem (see https://docs.docker.com/engine/extend/plugins/), and there's a really simple plugin, [local-persist](https://github.com/CWSpear/local-persist) that allows you to specify where docker should store the volume's data on the host; that way you could (for example) have docker store the volume-data in `/home/myproject`

**Comment by nejtr0n** [comment]
Thank you very much!! I think problem is solved.

**Comment by thaJeztah** [comment]
You're welcome! Let me close this issue then, but feel free to comment after I've closed :+1:
