### ISSUE TITLE
"docker export" does not include everything.  (Not about volume data)

### ISSUE THREAD

**Issue by markjreed** [docker/docker#21643]
I'm using "docker export" to create an artifact I can turn into a chroot tree so I can run the app outside of Docker itself, but the tar file doesn't include everything on the file system.  In particular, it's missing the /dev/random and /dev/urandom device nodes, meaning I can't do anything with encryption until I re-create those on the target system or manually add them to the tar file.  How can I control or at least predict what gets exported?  The command doesn't seem to have any options to speak of.

**Comment by programmerq** [comment]
docker export exports only the `/` filesystem of the container.

`/dev` in a container is actually its own mount, and not part of the `/` filesystem. See the output of 'mount' in the container:

    ...
    tmpfs on /dev type tmpfs (rw,nosuid,mode=755)
    ...

**Comment by cpuguy83** [comment]
Only the container FS is exported, /dev, /proc, volumes, etc are not part of the container FS.
I would not expect anything from `/dev` to be exported ever.

There is a feature request somewhere to allow exporting volume data along with the container FS, I'm not sure of the issue number.

**Comment by markjreed** [comment]
Thanks for the info, didn't realize /dev was a separate filesystem. All is now clear.  

docker exec tar... well, currently it needs to be docker exec stdbuf tar .. works for now.
