### ISSUE TITLE
Documentation unclear on auto creating missing host paths for bind mounts deprecation

### ISSUE THREAD

**Issue by aschrijver** [docker/docker#21652]
For integration and acceptance testing I want access to data from the container. I would like to use `volumes` in docker-compose file to specify the relative host path. In many occasions the host path of the volume may need to be auto-created.

**Problem**

Auto-creation of the host path in a volume appears to be DEPRECATED, as stated in documentation [here](https://docs.docker.com/engine/userguide/containers/dockervolumes/#auto-creating-missing-host-paths-for-bind-mounts):

> The directory on the host must be specified as an absolute path and if the directory doesn’t exist Docker will automatically create it for you. This auto-creation of the host path has been deprecated.

The documentation does not explain what will be the future behaviour. Will we get an error, or will the volume just not mount? Is there an additional flag to get auto-creation back, etc?

**Desired outcome**

* Describe the new behaviour in more detail. What should we use?
* Update the documentation page at https://docs.docker.com/engine/userguide/containers/dockervolumes/ accordingly

Thanks!

**Comment by thaJeztah** [comment]
Thanks for reporting; we recently made the decision to "undeprecate" that feature, because (unfortunately) it would be too much of a backward incompatible change; see https://github.com/docker/docker/pull/19953.

I'll update the documentation and remove the note from the "deprecated features" list

**Comment by aschrijver** [comment]
Thank you! I am actually happy you 'undeprecated', useful feature ;)

**Comment by thaJeztah** [comment]
Well, that feature causes a lot of headaches for many people, so I would've preferred to have it optional, but alas, that's not possible anymore :innocent:

**Comment by ravn** [comment]
I am using volumes to map in Java jar files created by maven.  If those for any reason have not been created yet, docker creates a directory instead owned by root, which neither maven nor myself can remove.  Only root can.    I would really appreciate having a flag that disables the auto-create feature and cause docker to fail if the host side files/dirs are not present.  It is fine if it defaults to the old behavior as long as it can be enabled.

**Comment by thaJeztah** [comment]
@ravn you can now do that with the new `--mount` flag on `docker run` (and `docker service create`); that flag provides you to bind mount host directories, but doesn't carry the legacy of auto-creating host directories.

It used a different syntax than `-v`, and uses a "CSV" format of key/value pairs, for example

    --mount  type=bind,src=/host/path,dst=/container-path/

(I'm typing from my phone, so double-check the options in the documentation :smile:)
