### ISSUE TITLE
Error when trying to commit container

### ISSUE THREAD

**Issue by peetonn** [docker/docker#21670]
**Output of `docker version`:**

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 30
Images: 123
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 184
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: J6MC:UQUM:SQ4I:5DT3:6OCK:SGWD:WNZC:LVOC:ORW2:MIAI:EEUR:5N54
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 18
 System Time: 2016-03-31T00:44:07.109661488Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: peetonn
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical, OSX 10.10

**Steps to reproduce the issue:**
1. `docker run -t -i peetonn/docker-ndnrtc-ubuntu14.04:prereq-checkout /bin/bash`
2. In the container, run:
2.1. `sudo apt-get install gtk+-2.0 pkg-config` 
2.2. `cd && cd webrtc-checkout && export PATH=$(pwd)/../depot_tools:$PATH`
2.3 `cd src && gclient sync`
2.4 `ninja -C out/Release`
2.5 `exit`
3. `docker commit -m "built webrtc" <container-id>  peetonn/docker-ndnrtc-ubuntu14.04:built-webrtc`

**Describe the results you received:**

Process hangs for ~30min and then exits with the following error:

`An error occurred trying to connect: Post https://192.168.99.100:2376/v1.21/commit?author=&comment=built+webrtc&container=e0bc3b22e319&repo=peetonn%2Fdocker-ndnrtc-ubuntu14.04&tag=built-webrtc: EOF`

**Describe the results you expected:**

Commit completes succesffully.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
I'm not able to reproduce, but it's quite a large image; is it possible the Virtual Machine was running out of disk space?

**Comment by peetonn** [comment]
The problem happened due to low disk space on my machine. Closing the issue.

**Comment by peetonn** [comment]
@thaJeztah is there a way to see actual size of container in docker?

**Comment by thaJeztah** [comment]
Size of a container is not visible afaik, because that would mean checking the size of the writable layer. `docker diff <some-container>` may give some hints as to *which* files were added/modified.

Size of images is shown in `docker images`, but that doesn't take into account that some images may share the same layers, so don't take up disk space twice

**Comment by peetonn** [comment]
trying to push the image, got this:

```
The push refers to a repository [docker.io/peetonn/docker-ndnrtc-ubuntu14.04] (len: 1)
473292604b3f: Pushing [==================================================>] 11.84 GB
Received unexpected HTTP status: 500 Internal Server Error
````
does it mean I exceeded image size limits on the server?

**Comment by peetonn** [comment]
I screwed even more: tried to push again, then interrupted by pressing "Ctrl+C" and then made few changes to the image of previous tag (`prereq-checkout`) and commited them under different tag. Now trying to push this tag and getting error:

```
$ docker push peetonn/docker-ndnrtc-ubuntu14.04:webrtc-head44
The push refers to a repository [docker.io/peetonn/docker-ndnrtc-ubuntu14.04] (len: 1)
push or pull peetonn/docker-ndnrtc-ubuntu14.04 is already in progress
```

Tried restarting docker terminal - didn't help.

**Comment by peetonn** [comment]
`docker-machine restart default` helped
