### ISSUE TITLE
add DESCRIPTION instruction to Dockerfile

### ISSUE THREAD

**Issue by dhrp** [docker/docker#2167]
It would be useful if Dockerfiles had a DESCRIPTION instruction

The instruction would use this line of text to add a description to every docker image it commits. Optimally the field in the Docker image would be named "description" but if we cannot change the current image format, the "comment" field would do just fine.

This data can then be extracted in the repository to show as meta-data for users to see.

**Comment by thaJeztah** [comment]
Related; https://github.com/docker/docker/pull/9882

Which will add support for adding custom meta-data to containers and images via the `LABEL` instruction, for example;

    LABEL description="some description"

The specified label will be visible via `docker inspect`

**Comment by duglin** [comment]
I think the 'comment' field on Images is unused.  Adding a "DESCRIPTION" command to set it should be fairly straightforward.  But, the question is whether we want to do it.  It is odd though to have a field in the image metadata that we can't set.  Aside from the obvious use of just adding a human readable description of the image (which people seem to have lived without so far), is there another reason?

/ping @crosbymichael @tiborvass

**Comment by thaJeztah** [comment]
I'm for closing, as mentioned in my previous comment, we now have `LABEL` which could probably fulfil this, albeit slightly less convenient than a plain `DESCRIPTION` instruction.

**Comment by duglin** [comment]
If we didn't have a "comment" field in the image metadata it would make it easier to decide, but alas, we do and so the idea of having a field that we can't set just feels too weird.  :-)

**Comment by thaJeztah** [comment]
> If we didn't have a "comment" field in the image metadata it would make it easier to decide

Hm, you're right there. There's other oddities as well, I think, e.g. The `-m/--message` for `docker commit`, which (at least, on the CLI) isn't really visible after setting.

**Comment by duglin** [comment]
you should see the 'comment' field when you do 'docker history' on the resulting image.

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.
