### ISSUE TITLE
What does Windows Subsystem for Linux mean for docker?

### ISSUE THREAD

**Issue by au-phiware** [docker/docker#21689]
https://insights.ubuntu.com/2016/03/30/ubuntu-on-windows-the-ubuntu-userspace-for-windows-developers/

I'm not about to run `apt-get install docker-engine` on ["Bash on Ubuntu on Windows"](http://www.hanselman.com/blog/DevelopersCanRunBashShellAndUsermodeUbuntuLinuxBinariesOnWindows10.aspx) just yet (as if it were actually that simple!) Because I realise that docker doesn't run exclusively in userspace, i.e. it needs specific kernel modules that are only available in the linux kernel. But does this new windows feature provide any sort of promise for a better "docker on windows" experience?

**Comment by au-phiware** [comment]
One problem that I continually encounter between me (on Linux) and my Windows colleagues is file permissions and the max path limit when mounting local directories as docker volumes. This seems slightly convoluted but I think it may be possible to have, say, a disk partition (or similar) that can be easily mounted to the same path into both the boot2docker VM and the Ubuntu on Windows environment (where Windows need have nothing to do with it). And then running docker-compose from Ubuntu on Windows would just work... maybe? Perhaps a separated (from Windows) disk partition would not be needed, just mounting the `%localappdata%\Lxss\rootfs\home` to `/home` in the VM would be enough or maybe mounting the C drive to `/mnt/c` in the VM is the way to go?

**Comment by cpuguy83** [comment]
I don't think it will mean anything other than potentially making the client a little bit easier to implement ...though probably not even that since the client will still need to be supported when the posix subsystem is not enabled.

AFAIK, the containerization bits in Windows will only be in the server editions, so there is nothing for the required calls to be translated into.

For issues you currently have with docker+windows, please check out https://blog.docker.com/2016/03/docker-for-mac-windows-beta/

**Comment by lightmanca** [comment]
I tried this tonight, and got the following:

root@DESKTOP-MK55F29:~/docker# service docker start
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
 * Starting Docker: docker                                                                                       [ OK ]
root@DESKTOP-MK55F29:~# docker daemon
FATA[0000] can't create unix socket /var/run/docker.sock: listen unix /var/run/docker.sock: setsockopt: invalid argument

**Comment by wmbonfiglio** [comment]
>  initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused

This is almost the same problem I've using Nginx and php-fpm, then nginx show this error when I try to reach a php file:
`connect() failed (22: Invalid argument) while connecting to upstream`

Did you find a solution?

**Comment by etatus** [comment]
Here is a workaround for the Upstart issue: [https://www.nesono.com/node/368]

**Comment by smalike** [comment]
I'm not about to run apt-get install docker-engine on "Bash on Ubuntu on Windows"
`$ sudo /usr/bin/dockerd`
`FATA[0000] can't create unix socket /var/run/docker.sock: listen unix /var/run/docker.sock: setsockopt: invalid argument`

**Comment by azutake** [comment]
I'm installated "Docker-Engine" on "WSL".
but, can't start dockerd.
(Windows10 IP Build 14971)
```
azutake@DESKTOP-DQ8FIB2:~$ sudo /usr/bin/dockerd
FATA[0000] Failed to connect to containerd. Please make sure containerd is installed in your PATH or you have specificed the correct address. Got error: fork/exec /usr/bin/containerd: invalid argument
azutake@DESKTOP-DQ8FIB2:~$
```

**Comment by AkihiroSuda** [comment]
WSL is not a complete Linux implementation.
It lacks essential features such as namespaces, cgroups. .

So you won't be able to start the Docker daemon on WSL
