### ISSUE TITLE
Cannot open more than 60 TCP connections from one container to another with docker networks

### ISSUE THREAD

**Issue by rafaeldff** [docker/docker#21706]
**Output of `docker version`:**

```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.4.3
 Git commit:   a34a1d59
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.4.3
 Git commit:   a34a1d59
 Built:        
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 120
 Running: 2
 Paused: 0
 Stopped: 118
Images: 290
Server Version: 1.10.2
Storage Driver: devicemapper
 Pool Name: docker-8:4-9187177-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 17.42 GB
 Data Space Total: 107.4 GB
 Data Space Available: 89.96 GB
 Metadata Space Used: 31.02 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.116 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.114 (2016-01-16)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.0
Operating System: NixOS 16.03pre75806.77f8f35 (Emu)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.56 GiB
Name: rffnix
ID: 4FER:TIHU:3ZTT:EIGN:TW6P:DAJK:KPOX:ELI2:DXW6:NSFG:IYQU:J4J5
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Using docker on linux

**Steps to reproduce the issue:**
1. Bring up a server container. 
My tests were done with the zookeeper server container brought up via docker-compose with the following config snippet:
```
version: "2"
services:
  zookeeper:
    image: netflixoss/exhibitor:1.5.2
    ports:
      - "2181:2181"
```

2. Bring up a client container. My tests were done with `debian:latest`: 
```
docker run  --net=env_default  --rm -ti  debian bash
``` 
I installed netcat inside the container via `apt-get update ; apt-get -y install netcat net-tools`.

3. Open 59 connections to the server
I used a bash loop spawning `nc` on the background, not exactly elegant, but did the job:
```
# for i in {1..59} ; do echo $i; nc zookeeper 2181 &  done
```

4. Test that we successfully open a _60th_ ephemeral connection:
```
# echo ruok | nc zookeeper 2181
imok
```

5. Open a new background connection to be the `60th`.
```
# nc zookeeper 2181 &
```

6. Check that further attempted connections do not succeed:
```
# echo ruok | nc zookeeper 2181
#
```

**Describe the results you received:**
The last attempt should have received an `imok` reply according to  Zookeeper's protocol, same as we saw on step *4*. If count connections on the server container (with `netstat -natp   | wc -l`) we can see this new attempt doesn't even register.

**Describe the results you expected:**
The last attempt should have received an `imok` reply.

**Additional information you deem important (e.g. issue happens only occasionally):**
Output of *docker-compose -v*:
```
docker-compose -v
docker-compose version 1.6.2, build 4d72027
```

**Comment by thaJeztah** [comment]
ping @mavenugo could you have a look?

**Comment by rafaeldff** [comment]
Any news? Anything I can do to help narrow down the issue?

**Comment by sanimej** [comment]
@rafaeldff I tried with a simple TCP server and nc as client..works just fine..

server is on port 3333; with 100 nc clients..

````
vagrant@net-1:~$ sudo nsenter --net=/var/run/docker/netns/a470ae93daa8 netstat -an | grep 3333 | wc -l
101
````

May be its an issue with zookeeper ? Can you try with some TCP server or a test code ?

**Comment by rafaeldff** [comment]
Seems to be an issue with zookeeper, I'm closing this now.
