### ISSUE TITLE
False caching with docker:build from tar

### ISSUE THREAD

**Issue by rhuss** [docker/docker#21715]
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6
 Git commit:   20f81dd
 Built:        Sat Mar 12 04:07:44 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 20:39:58 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 9
 Running: 0
 Paused: 0
 Stopped: 9
Images: 313
Server Version: 1.10.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 513
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.17-boot2docker
Operating System: Boot2Docker 1.10.1 (TCL 6.4.1); master : b03e158 - Thu Feb 11 22:34:01 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.859 GiB
Name: default
ID: A3MX:GV5U:BPUI:D5MK:NUE5:OSG2:4QIC:BQ46:ZPER:ZCWN:7252:A7CN
Debug mode (server): true
 File Descriptors: 11
 Goroutines: 22
 System Time: 2016-04-01T06:56:34.579020913Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: rhuss
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

docker-machine with VirtualBox on OS X

**Steps to reproduce the issue:**

Please use the attached tar archive which contains Dockerfile + content and which are clearly different. 

Then:

```
$ cat jolokia-1.2.3.tar | docker build -t test -
Sending build context to Docker daemon 665.6 kB
Step 1 : FROM consol/tomcat-7.0:latest
 ---> 7c34bafd1150
Step 2 : COPY maven /maven/
 ---> ea6f3b06163b
Removing intermediate container 41d60250f1c7
Successfully built ea6f3b06163b

$ cat jolokia-1.3.2.tar | docker build -t test -
Sending build context to Docker daemon 675.8 kB
Step 1 : FROM consol/tomcat-7.0:latest
 ---> 7c34bafd1150
Step 2 : COPY maven /maven/
 ---> Using cache
 ---> ea6f3b06163b
Successfully built ea6f3b06163b
```

**Describe the results you expected:**

The second step must not cache because the content of the tar is different.

**Additional information you deem important (e.g. issue happens only occasionally):**

The tar file looks like 

```
$ tar tvf jolokia-1.2.3.tar
-rw-r--r--  0 roland staff  307617 Apr  1 08:30 maven/./jolokia.war
-rw-r--r--  0 roland staff  345487 Apr  1 08:30 maven/./jolokia-it.war
-rw-r--r--  0 roland staff      49 Apr  1 08:44 Dockerfile

$ tar tvf jolokia-1.3.2.tar
-rw-r--r--  0 roland staff  315524 Feb 13 21:19 maven/./jolokia.war
-rw-r--r--  0 roland staff  353833 Oct 13 11:31 maven/./jolokia-it.war
-rw-r--r--  0 roland staff      49 Apr  1 08:47 Dockerfile
```

So albeit this is a completely valid tar archive, it could be that the extra dot confuses Docker. If the tar is rearrange to look like 

```
drwxr-xr-x  0 roland staff       0 Apr  1 09:05 maven/
-rw-r--r--  0 roland staff      49 Apr  1 09:05 Dockerfile
-rw-r--r--  0 roland staff  353833 Oct 13 11:31 maven/jolokia-it.war
-rw-r--r--  0 roland staff  315524 Feb 13 21:19 maven/jolokia.war
```

then caching works as expected.

The tar-archive above which prevents caching is created by a tool (Maven) and can't be changed easily. See also https://github.com/fabric8io/docker-maven-plugin/issues/422 where this issue was reported the first time.

**Comment by rhuss** [comment]
Test data containe tars mentioned above: [test-data.zip](https://github.com/docker/docker/files/199109/test-data.zip)

**Comment by thaJeztah** [comment]
ping @aaronlehmann @tonistiigi PTAL

thanks for reporting and investigating @rhuss

**Comment by aaronlehmann** [comment]
Yes, I think this is due to the extra `.` in the tar.

Tarsum maintains a map of hashes by file path. It removes a leading `./` from the path but doesn't do any additional normalization to remove extra `./` components from the path: https://github.com/docker/docker/blob/master/pkg/tarsum/tarsum.go#L238

Then the builder walks the untarred directory and queries each file by in this map by relative path: https://github.com/docker/docker/blob/master/builder/tarsum.go#L141. It won't find these files because they will be stored in the map under `maven/./...` instead of `maven/...`.

To fix this, I think https://github.com/docker/docker/blob/master/pkg/tarsum/tarsum.go#L238 should not just strip a leading `./` - it should do a full normalization.
