### ISSUE TITLE
network sub commands in help text are not in a consistent order

### ISSUE THREAD

**Issue by MHBauer** [docker/docker#21710]
This is more of nit than anything, but I thought I was going crazy for a second, so it surprised me.

The standard help is always in order, and the volume subcommands are always in order. I can see a sort for the standard commands, so I'm not sure if volume just doesn't have enough subcommands to trigger this, or if it's being sorted somewhere. I'm not familiar with the CLI code or I'd fix it myself.

**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6
 Git commit:   20f81dd
 Built:        Sat Mar 12 04:07:44 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 22
 Running: 1
 Paused: 0
 Stopped: 21
Images: 177
Server Version: 1.10.2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 256
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.18-boot2docker
Operating System: Boot2Docker 1.10.2 (TCL 6.4.1); master : 611be10 - Mon Feb 22 22:47:06 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 2.936 GiB
Name: docker-build
ID: BBS5:AL2Y:2PZI:5VS7:MAH2:EIOK:GKP2:LQB5:XRQJ:NTBV:VTAH:6RXZ
Debug mode (server): true
 File Descriptors: 18
 Goroutines: 37
 System Time: 2016-04-01T01:02:07.159198424Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: mhbauer
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. run `docker network --help` repeatedly

**Describe the results you received:**
The `Commands:` section is not sorted the same way every time.

**Describe the results you expected:**
The `Commands:` section should be sorted the same way every time, as it is for `docker volume --help` and for `docker --help`.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
Hm, possibly the Go randomizer at work? http://nathanleclaire.com/blog/2014/04/27/a-surprising-feature-of-golang-that-colored-me-impressed/

**Comment by senk** [comment]
@thaJeztah exactly! I will fix it #dibs
