### ISSUE TITLE
Feature Request: Add label filters for networks and volumes

### ISSUE THREAD

**Issue by albers** [docker/docker#21717]
Since #21270, labels can be added to networks and volumes.
To be consistent with `docker  ps`, `docker images` and `docker events`, `docker network ls` and `docker volume ls` should also have a `--filter label=` option.

**Comment by HackToday** [comment]
hi @albers 

The featured was address in following PRs:
`volume filter for label`   https://github.com/docker/docker/pull/21567
`network filter for label`  https://github.com/docker/docker/pull/21495

But seems maintainers are busy with 1.11 release, so not have time to review that  :0

Thanks

**Comment by albers** [comment]
@HackToday Thanks for pointing me to these PRs and corresponding issues.
Closing in favour of #21416 and #21417
