### ISSUE TITLE
UDP/TCP packets getting dropped by container

### ISSUE THREAD

**Issue by ArshiaSayed** [docker/docker#21720]
docker info
Containers: 4
Images: 124
Storage Driver: devicemapper
 Pool Name: docker-253:0-88356-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 7.43 GB
 Data Space Total: 107.4 GB
 Data Space Available: 99.94 GB
 Metadata Space Used: 9.302 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.138 GB
 Udev Sync Supported: true
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Kernel Version: 3.10.0-123.el7.x86_64
Operating System: Oracle Linux Server 7.2
CPUs: 2
Total Memory: 7.641 GiB
Name: ispaaaems1
ID: 6MUK:HS3D:OQTS:QMWY:WCKE:AZT6:COJP:F7EA:RPNX:7RHY:TKFB:D4LT

uname -a
Linux ispaaaems1 3.10.0-123.el7.x86_64 #1 SMP Wed Jul 9 18:59:11 PDT 2014 x86_64 x86_64 x86_64 GNU/Linux

Container OS is OEL6.6

I am sending a request from radius client , TCP/UDP packets are  reaching my host machine but not few packets(3 out of 5) are getting dropped by the container.

**Comment by LK4D4** [comment]
@ArshiaSayed can you pls try with the newer version of docker and open new issue?
This issue lacks activity due to missing `docker version` output and networking is changing at very fast pace.
