### ISSUE TITLE
when you create a directory while bind-mounting it, it's owned by root

### ISSUE THREAD

**Issue by vikstrous** [docker/docker#21738]
When I'm using user namespaces with docker and I bind-mount a directory into a container with `-v` but it doesn't exist yet, it gets created for the root user instead of the user that the container is about to run as. I think this is a bug because such a directory is inaccessible to the container, so this behaviour seems unhelpful. It should be created as the container's user.

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.11.0-rc3
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   eabf97a
 Built:        Sat Apr  2 08:31:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0-rc3
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   eabf97a
 Built:        Sat Apr  2 08:31:07 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
$ docker info
Containers: 10
 Running: 8
 Paused: 0
 Stopped: 2
Images: 32
Server Version: 1.11.0-rc3
Storage Driver: aufs
 Root Dir: /var/lib/docker/1000.1000/aufs
 Backing Filesystem: extfs
 Dirs: 123
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.5-1-docker-aufs
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.709 GiB
Name: compooter
ID: GKSI:YHZC:YPNI:PAGO:EYPD:AYME:K6BY:BAIH:EBKQ:SOAK:WUFP:6MJM
Docker Root Dir: /var/lib/docker/1000.1000
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 59
 Goroutines: 100
 System Time: 2016-04-02T22:06:38.715057195-07:00
 EventsListeners: 0
Username: viktorstanchev
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical laptop

**Steps to reproduce the issue:**
1. Edit /etc/subuid and /etc/subgid to include `dockremap:1000:65536`
2. Start the daemon with `--userns-remap default`
3. run `docker run --rm -it -v $(pwd)/new:/test busybox sh`
4. run `ls -lha new`
5. `new` is owned by root

**Describe the results you received:**
The new directory was owned by  root

**Describe the results you expected:**
The new directory should be owned by the default docker container user

**Additional information you deem important (e.g. issue happens only occasionally):**
n/a

**Comment by estesp** [comment]
We've usually shied away from affecting file ownership on the host for user namespaces with the mantra that "user namespaces are an advanced feature" and the admin or creator should consider initial requirements for externally mounted resources (re: ownership, access, etc.).  However, in this case Docker is affecting creation of a new directory on the host, so maybe it is a gray area given we know if the daemon has user mapping enabled?

Of course, the prep requirements for this case **could** be done here with a small change to startup: `mkdir $(pwd)/new && chown 1000:1000 $(pwd)/new` and then the same `docker run`

**Comment by thaJeztah** [comment]
@estesp perhaps when *creating* the directory, docker should use what's "root" inside the container, i.e. "root" in a non-userns container, and remapped root if it is?

**Comment by vikstrous** [comment]
The workaround is simple and it's not a big issue for anyone. This is my reasoning: There is no use case where one would want to create a directory owned by root and then bind-mount it into a container that can't access it. Therefore, Docker should implement the more common use case of creating a directory owned by the root user of the container by default.
