### ISSUE TITLE
[1.11-rc3] Two Dockers are better than one

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#21736]
Docker now needs a to talk to containerd over /var/run/docker/libcontainerd/docker-containerd.sock.  What if I want to run two Docker daemons?  (I happen to know a use case like that :smile:).  In the past if you ran two Docker daemons they would share /var/run/docker but because of non-overlapping IDs it didn't matter.  Now both daemons want to talk to the same containerd.  Whats the expectation here?  I'd rather not share the same containerd.

**Comment by thaJeztah** [comment]
You can provide the `--containerd` daemon option to specify a path; https://github.com/docker/docker/blob/master/docs/reference/commandline/daemon.md

**Comment by thaJeztah** [comment]
We added that option, because we knew there would be someone, somewhere, who happened to know a use case for just that. :wink:

**Comment by ibuildthecloud** [comment]
@thaJeztah Sweet!  I'll try it out.  I haven't quite gotten to putting 1.11 in RancherOS yet.

**Comment by ibuildthecloud** [comment]
@thaJeztah It's a bit odd the help for `--containerd` doesn't say `--containerd=/var/run/docker/libcontainerd/docker-containerd.sock`.

**Comment by senk** [comment]
@ibuildthecloud i think that was discussed in #21576 

/cc @coolljt0725

**Comment by cyphar** [comment]
I really, **really** don't like the fact that Docker starts daemons of it's own accord.

**Comment by icecrime** [comment]
It seems this one can be closed? Let me know if it needs reopening. Thanks!
