### ISSUE TITLE
Docker 1.11-rc2 performance regression

### ISSUE THREAD

**Issue by vincentwoo** [docker/docker#21734]
As requested by @thaJeztah I am reporting a suspected regression in Docker performance when testing 1.11-rc2 as compared to 1.10. Here's a screenshot (the line is when we made the upgrade to rc2):

![ss1](https://www.dropbox.com/s/h6td5yqy68evyfw/Screenshot%202016-04-01%2020.17.03.png?raw=1)

That was a trailing 3-day graph. Here's a 7-day if you want one too:

![ss2](https://www.dropbox.com/s/vksqectl8otgs70/Screenshot%202016-04-02%2002.28.49.png?raw=1)

The peak on the right is pretty noticeable. Our app doesn't do anything too specific - runs a ton of containers, attaches some as TTYs, deletes, etc.

**Output of `docker version`:**

```
Client:
 Version:      1.11.0-rc2
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   eabf97a
 Built:        Fri Apr  1 22:26:46 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0-rc2
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   eabf97a
 Built:        Fri Apr  1 22:26:46 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
ontainers: 14
 Running: 14
 Paused: 0
 Stopped: 0
Images: 22
Server Version: 1.11.0-rc2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: none
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 3.19.0-56-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 29.45 GiB
Name: execute-1459580406
ID: ZYHJ:PS3I:SNMO:APRR:ZYXH:GXUR:5CKY:2NTE:J72N:2ICX:FZ6U:W5OC
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running GCE 8-core machines with a local SSD scratch disk for `/var/lib/docker`

**Comment by cpuguy83** [comment]
Thanks for testing and reporting on this!

**Comment by vincentwoo** [comment]
This appears to be improved on rc3, so I'm comfortable closing for now.
