### ISSUE TITLE
Is it possible to connect docker containers to OVS bridge using user space vhost  sockets. Does docker support the use of vhost ? If not is their any plan to implement it?

### ISSUE THREAD

**Issue by bijutalukdar** [docker/docker#21747]
**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
I'm not aware of plans in this direction, but this is probably more a question for libnetwork; you could try and ask in the #docker-network IRC channel on freenode. I'll close this here, but feel free to comment after I've closed

**Comment by mavenugo** [comment]
This is an OVS plugin specific question. https://github.com/gopher-net/docker-ovs-plugin
