### ISSUE TITLE
Volume in container started after read-write remount remains read-only

### ISSUE THREAD

**Issue by jblomer** [docker/docker#21748]
After a read-write remount of a mount point on the host a container would still see the read-only version of that mount point brought into the container through the `-v` option.  I can reproduce this on Ubuntu 15.10 / docker 1.6.2 and Fedora 23 / docker 1.9.1.  I cannot reproduce it with docker 1.6.1 on a custom 4.1 kernel.

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->

**Output of `docker version`:**

```
Client:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-6.git6ec29ef.fc23.x86_64
 Go version:      go1.5.3
 Git commit:      7206621
 Built:           Mon Jan 25 20:52:22 UTC 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-6.git6ec29ef.fc23.x86_64
 Go version:      go1.5.3
 Git commit:      7206621
 Built:           Mon Jan 25 20:52:22 UTC 2016
 OS/Arch:         linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
Images: 4
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-8:1-524436-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 285.8 MB
 Data Space Total: 107.4 GB
 Data Space Available: 40.73 GB
 Metadata Space Used: 749.6 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.109 (2015-09-22)
Execution Driver: native-0.2
Logging Driver: journald
Kernel Version: 4.2.3-300.fc23.x86_64
Operating System: Fedora 23 (Cloud Edition)
CPUs: 8
Total Memory: 3.859 GiB
Name: localhost.localdomain
ID: B7O7:3LU7:2CIH:AJK4:32DS:JMIG:CBAH:SQHP:RNM6:ZDWD:LEI5:EJG6
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker host is VirtualBox VM on Mac.

**Steps to reproduce the issue:**

The following commands executed on the host show the problem:

    mkdir -p /tmpfs
    mount -t tmpfs tmpfs -o ro /tmpfs
    mount -o remount,rw /tmpfs
    docker pull centos
    docker run -i --rm -v /tmpfs:/tmpfs centos cat /proc/mounts

**Describe the results you received:**

The mount point /tmpfs inside the container is read-only.

**Describe the results you expected:**

The mount point /tmpfs inside the container should be writable.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment]
How is the docker daemon being started?

**Comment by jblomer** [comment]
It's started with `systemctl start docker`.

**Comment by cpuguy83** [comment]
@jblomer Check your unit file, what does it have for `MountFlags`?

**Comment by jblomer** [comment]
@cpuguy83 For both Ubuntu and Fedora the setting is `MountFlags=slave`.

**Comment by jblomer** [comment]
@cpuguy83 This seems to me the right `MountFlags` settings, no?  Can you clarify if this is an issue in docker or with systemd?

**Comment by cpuguy83** [comment]
@jblomer I cannot reproduce this on master

**Comment by cpuguy83** [comment]
Being that all Docker is doing is a `mount --rbind /tmpfs /container/path/tmpfs`, the mount is just inheriting whatever is already set.

**Comment by jblomer** [comment]
Many thanks!  Must be something related to the distributions then, I'll check with Ubuntu and/or Fedora folks.

**Comment by natefoo** [comment]
@cpuguy83 Just curious, could you let me know what your host OS is?
