### ISSUE TITLE
golang panic: if I do docker create/run with --storage-opt size=5G (something less than the base device size)

### ISSUE THREAD

**Issue by shishir-a412ed** [docker/docker#21753]
On current docker master branch:
1) If I do 
    `docker run -it --storage-opt size=5G fedora /bin/bash`. 
     In this example, my base device size is 10G. Since size passed (5G) < Base Device Size (10G)      docker should return this error to the CLI.
     Error Message: https://github.com/docker/docker/blob/master/daemon/graphdriver/devmapper/deviceset.go#L1876

However this is what I am getting right now:

Docker CLI: docker: An error occurred trying to connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create: EOF.
See 'docker run --help'.

Docker Daemon:  ERRO[0471] Error saving dying container to disk: open /var/lib/docker/containers/da2c4cd4cf02137217c6206e79397f02c52bd1d3474cef1846dfaa552cfcb35c/config.v2.json: no such file or directory 
2016/04/04 18:06:26 http: panic serving @: runtime error: invalid memory address or nil pointer dereference
goroutine 86 [running]:
net/http.(*conn).serve.func1(0xc82030e0b0, 0x7f93380910c8, 0xc8202ea010)
	/usr/lib/golang/src/net/http/server.go:1287 +0xb5
github.com/docker/docker/layer.(*layerStore).ReleaseRWLayer(0xc820908180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/smahajan/docker/.gopath/src/github.com/docker/docker/layer/layer_store.go:520 +0xc3
github.com/docker/docker/daemon.(*Daemon).cleanupContainer(0xc820065680, 0xc820ab8000, 0xc82054f501, 0x0, 0x0)
	/home/smahajan/docker/.gopath/src/github.com/docker/docker/daemon/delete.go:126 +0x918
github.com/docker/docker/daemon.(*Daemon).create.func1(0xc8209873b0, 0xc820065680, 0xc820ab8000)
	/home/smahajan/docker/.gopath/src/github.com/docker/docker/daemon/create.go:77 +0x4c
github.com/docker/docker/daemon.(*Daemon).create(0xc820065680, 0x0, 0x0, 0xc820a10480, 0xc820108380, 0xc8202ea018, 0x0, 0x0, 0x7f933c946028, 0xc820b84080)
	/home/smahajan/docker/.gopath/src/github.com/docker/docker/daemon/create.go:91 +0x3a8
github.com/docker/docker/daemon.(*Daemon).ContainerCreate(0xc820065680, 0x0, 0x0, 0xc820a10480, 0xc820108380, 0xc8202ea018, 0x0, 0x0, 0x0, 0x0, ...)
	/home/smahajan/docker/.gopath/src/github.com/docker/docker/daemon/create.go:43 +0x496
github.com/docker/docker/api/server/router/container.(*containerRouter).postContainersCreate(0xc8202cdac0, 0x7f9338092a28, 0xc820a92480, 0x7f9338025cd0, 0xc82030e370, 0xc82009e000, 0xc820a92180, 0x0, 0x0)
	/home/smahajan/docker/.gopath/src/github.com/docker/docker/api/server/router/container/container_routes.go:353 +0x351
github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.postContainersCreate)-fm(0x7f9338092a28, 0xc820a92480, 0x7f9338025cd0, 0xc82030e370, 0xc82009e000, 0xc820a92180, 0x0, 0x0)
	/home/smahajan/docker/.gopath/src/github.com/docker/docker/api/server/router/container/container.go:47 +0x74
github.com/docker/docker/api/server/middleware.NewVersionMiddleware.func1.1(0x7f9338092a28, 0xc820a92480, 0x7f9338025cd0, 0xc82030e370, 0xc82009e000, 0xc820a92180, 0x0, 0x0)
	/home/smahajan/docker/.gopath/src/github.com/docker/docker/api/server/middleware/version.go:42 +0xa43
github.com/docker/docker/api/server/middleware.NewUserAgentMiddleware.func1.1(0x7f9338092a28, 0xc820a92270, 0x7f9338025cd0, 0xc82030e370, 0xc82009e000, 0xc820a92180, 0x0, 0x0)
	/home/smahajan/docker/.gopath/src/github.com/docker/docker/api/server/middleware/user_agent.go:34 +0x6b8
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7f9338025cd0, 0xc82030e370, 0xc82009e000)
	/home/smahajan/docker/.gopath/src/github.com/docker/docker/api/server/server.go:132 +0x138
net/http.HandlerFunc.ServeHTTP(0xc820a6e940, 0x7f9338025cd0, 0xc82030e370, 0xc82009e000)
	/usr/lib/golang/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc82097cfa0, 0x7f9338025cd0, 0xc82030e370, 0xc82009e000)
	/home/smahajan/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc820bcbc80, 0x7f9338025cd0, 0xc82030e370, 0xc82009e000)
	/home/smahajan/docker/.gopath/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
net/http.serverHandler.ServeHTTP(0xc8201e4a20, 0x7f9338025cd0, 0xc82030e370, 0xc82009e000)
	/usr/lib/golang/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc82030e0b0)
	/usr/lib/golang/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/usr/lib/golang/src/net/http/server.go:1910 +0x3f6

Shishir

**Comment by coolljt0725** [comment]
I'm working on the fix.

**Comment by coolljt0725** [comment]
This will be fixed by #21716

**Comment by vieux** [comment]
Fixed in #21802
