### ISSUE TITLE
"docker run" takes command from the host?

### ISSUE THREAD

**Issue by AndreKR** [docker/docker#21752]
##### What I did
```
$ docker pull ubuntu:14.04
14.04: Pulling from library/ubuntu

203137e8afd5: Pull complete ================================================>] 65.69 MB/65.69 MBB
2ff1bbbe9310: Pull complete ================================================>] 71.48 kB/71.48 kBB
933ae2486129: Pull complete ================================================>]    681 B/681 BB
a3ed95caeb02: Pull complete ================================================>]     32 B/32 BB
Digest: sha256:1c8b813b6b6656e9a654bdf29a7decfcc73b92a62b934adc4253b0dc2be9d0a2
Status: Downloaded newer image for ubuntu:14.04

$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
ubuntu              14.04               97434d46f197        2 weeks ago         188 MB

$ docker run -t -i ubuntu:14.04 /bin/bash
exec: "C:/Program Files (x86)/Git/bin/bash": stat C:/Program Files (x86)/Git/bin/bash: no such file or directory
docker: Error response from daemon: Container command not found or does not exist..

$ docker run -t -i ubuntu:14.04 ls
bin   dev  home  lib64  mnt  proc  run   srv  tmp  var
boot  etc  lib   media  opt  root  sbin  sys  usr

$ docker run -t -i ubuntu:14.04 uname -a
Linux f7cbc1affa44 4.1.19-boot2docker #1 SMP Mon Mar 7 17:44:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

##### What I got
```
$ docker run -t -i ubuntu:14.04 /bin/bash
exec: "C:/Program Files (x86)/Git/bin/bash": stat C:/Program Files (x86)/Git/bin/bash: no such file or directory
docker: Error response from daemon: Container command not found or does not exist..
```

##### What I expected

I thought `docker run` will run the command *inside* the container, so why does it try to look it up on the host machine?

##### Version info

DockerToolbox-1.10.3.exe

```
$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
```

**Comment by thaJeztah** [comment]
Ah, yes, this is probably mingw trying to be smart again, and automatically expanding / converting to a windows path before it's sent to the docker daemon; see some similar issues (and workarounds) here; https://github.com/docker/docker/issues/18290 and https://github.com/docker/toolbox/issues/282

Hope that helps (and yes, it's nasty)

**Comment by AndreKR** [comment]
Yes, it helps, thanks. I was using msysgit 1.9.5 which did not support the `MSYS_NO_PATHCONV` environment variable.

**Comment by thaJeztah** [comment]
Cool, good to hear it helped. Many people tripped over this (sometimes very weird) behavior :sweat_smile:

**Comment by dsebastien** [comment]
Just in case it can help someone, I solved it using the following:

```
docker()
{
    export MSYS_NO_PATHCONV=1
    ("$DOCKER_HOME/docker.exe" "$@")
    export MSYS_NO_PATHCONV=0
}
```
(with DOCKER_HOME pointing to the folder where I have docker.exe)

**Comment by thaJeztah** [comment]
@dsebastien could you check if that solution is already mentioned in https://github.com/docker/toolbox/issues/282 ? It may help other as well to work around msys being "smart" :smile:

**Comment by AndreKR** [comment]
Strange, that should not be necessary because it is already included in start script of the Docker Quickstart Terminal: https://github.com/docker/toolbox/blob/master/windows/start.sh#L83

**Comment by dsebastien** [comment]
@thaJeztah you've just made the link, perfect :p

@AndreKR I'm not using docker toolbox anymore. I've only grabbed docker.exe from the releases here as I now use the Docker beta for Windows based on Hyper-V. Previously I was using some home cooked scripts to interact with Docker on Virtualbox, but I'm glad if I can drop all that now:
* https://www.dsebastien.net/2015/04/20/a-bit-of-windows-docker-bash-fu/
* https://www.dsebastien.net/2015/04/22/a-bit-more-windows-docker-bash-fu/
