### ISSUE TITLE
invalid character 'H' looking for beginning of value when working with volumes

### ISSUE THREAD

**Issue by iangcarroll** [docker/docker#21758]
**Output of `docker version`:**

```
# docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:59:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:59:07 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
# docker info
Containers: 16
 Running: 8
 Paused: 0
 Stopped: 8
Images: 14
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 216
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local convoy-gluster
 Network: null host bridge
Kernel Version: 4.2.0-34-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.796 GiB
Name: rancher3
ID: SNGF:<censored>
Labels:
 provider=rackspace
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Rackspace with Rancher

**Steps to reproduce the issue:**
1. Create a volume with the `convoy-gluster` driver
2. Reboot a host
3. Try to inspect it

**Describe the results you received:**
```
# docker volume inspect postgresql
[]
Error response from daemon: get postgresql: invalid character 'H' looking for beginning of value
```

**Describe the results you expected:**
The volume to function correctly.

**Additional information you deem important (e.g. issue happens only occasionally):**
Not sure if this is a Convoy or Docker issue.

**Comment by cpuguy83** [comment]
Looks likely to be a convoy issue

**Comment by ibuildthecloud** [comment]
@iangcarroll Can you open this against https://github.com/rancher/rancher.  There's a good chance your running version of convoy that isn't compatible with 1.10+.

**Comment by iangcarroll** [comment]
Already did; will close this one.

**Comment by ndarilek** [comment]
Which Convoy issue describes this? Just hit this one as well, wondering if it's fixed?
