### ISSUE TITLE
`docker run -m 100MB` while `docker stats` show a limit of 104.9 MB 

### ISSUE THREAD

**Issue by allencloud** [docker/docker#21765]
**Output of `docker version`:**

```
root@ubuntu:/sys/fs/cgroup/memory/foobar# cd ~
root@ubuntu:~# docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:36:33 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:36:33 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
root@ubuntu:~# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 54
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 357
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: ubuntu
ID: RDEJ:ZCV6:CJH5:UCNB:P5RR:66LB:JZSO:YACX:TBL3:PYMV:2F77:KBUA
WARNING: No swap limit support
```

**uname:**
```
root@ubuntu:~# uname -a
Linux ubuntu 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Steps to reproduce the issue:**
1.
```
root@ubuntu:~# docker run -d -m 100MB ubuntu:14.04 sleep 1000
WARNING: Your kernel does not support swap limit capabilities, memory limited without swap.
3084100ba6a5bd4b010c3f8ee9b5e25d2d7e54e1d00c5e31aff5381087c7d537
```
2.
```
root@ubuntu:~# docker stats 3084100
CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O
3084100             0.00%               110.6 kB / 104.9 MB   0.11%               648 B / 648 B       0 B / 0 B
```

**Describe the results you received:**
limit a container's memory with 100MB, while docker engine shows that limitation is 104.9MB

**Describe the results you expected:**
docker engine shows that limitation is 100MB

**Additional information you deem important (e.g. issue happens only occasionally):**
Maybe when we deals memory size in docker cli, we can distinguish  MB and MiB, and so on.

**Comment by phemmer** [comment]
Looks like the CLI parser is using `github.com/docker/go-units.RAMInBytes()` which parses input as mibibytes, but the stats output is using `github.com/docker/go-units.HumanSize()` which uses megabytes.

**Comment by allencloud** [comment]
Yes, just now I searched code related to this issue.
I dive into the cgroup and find the value is 
```
root@ubuntu:/sys/fs/cgroup/memory/foobar/ffb082df6289394f4d285ef2ea31051deed699f6b352cf4109fb7e97fd15237a# cat memory.limit_in_bytes
104857600
```

seems `github.com/docker/go-units.RAMInBytes()` treated MB to be MiB.

While nothing goes wrong in `docker stats`, since 104857600 is 104.9MB=100MiB

**Comment by yongtang** [comment]
The issue is that, when `docker run` is invoked, `RAMInBytes` (parse.go) was used to pass the memory size as input. But when `docker stats` is running, `HumanSize` (stats_helpers.go) is used for display as output. Yet `RAMInBytes` corresponds to `BytesSize`, and `HumanSize` corresponds to `FromHumanSize`.

We could change to `BytesSize` in stats_helper.go so that the input and the output is consistent. (Or change `RAMInBytes` to `FromHumanSize` in parse.go). Either way, the input and output will be consistent.

Though this is a behavior change so I am not sure this is the way to do.

Nevertheless, I think I could create a pull request first to open further discussion about this issue.

**Comment by yongtang** [comment]
@allencloud @phemmer A PR #21773 was created. Please let me know if you have any thought on it.
