### ISSUE TITLE
The behavior of the prefix of the detachkey, it is undocumented intended behavior or BUG ?

### ISSUE THREAD

**Issue by laijs** [docker/docker#21769]
If I set the escapekeys to 'ctrl-p,ctrl-q', and

type(press) | result 
---- | ------
ctrl-p A | A 
ctrl-p ctrl-p | ctrl-p 
ctrl-p ctrl-p ctrl-q | ctrl-p ctrl-q 

it seems excellent, 'ctrl-p' is the escapekey of the escapekeys, it means typing 'ctrl-p' at first give us a way to send the whole escapekeys into container. But it is **undocumented**! Is it *intended* or **BUG**?
And it('ctrl-p') is always eaten.

If it is intended, escapekeys 'A,B,C,D' will give me another shock,
any prefixes of the 'A,B,C,D' will become the escapekeys of the escapekeys, any prefix will be eaten and any prefix will help to send the full escapekeys into container. (this example is at the end of this issue)

IMO, if we allow escapekeys of the escapekeys, it is better ONLY to use the first key as the escapekey of the escapekeys, rather than any prefix. But, again, it requires documentation.

But if we only use the first key as the escapekey of the escapekeys, and the user set the escapekeys to "A,A" or "ctrl-p,ctrl-p", we have no way to send A or ctrl-p into container.

 ==========
other solution (I prefer this one, it matches the document but it changes the current behavior): disallow any way to send escapekeys into container
if the type sequeue is the  escapekeys, we do the detach
if the type sequeue is any prefix of the escapekeys, we put it into container, rather than eat(discard) it.

**Output of `docker version`:**

```
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:18:46 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:18:46 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 28
 Running: 3
 Paused: 0
 Stopped: 25
Images: 2
Server Version: 1.10.1
Storage Driver: overlay
 Backing Filesystem: xfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.4.5.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.694 GiB
Name: sbox
ID: X3HY:KHO6:CAFD:R4D6:QIFV:MS5H:HLXS:4QT7:MYIR:4PM3:OJZV:JJEZ
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. docker run -ti --detach-keys 'A,B,C,D' ubuntu
2. press 'Atesta'
3. press 'ABtestab'
4. press 'ABCtestabc'
5. press 'AABCD'
6. press 'ABABCD'
7. press 'ABCABCD'

**Describe the results you received:**
testa
testab
testabc
ABCD
ABCD
ABCD

**Describe the results you expected:**
I don't know.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment]
I think it probably makes sense to buffer these keys and return them if the escape sequence is not completed.

**Comment by laijs** [comment]
@cpuguy83 in your comments, I found that you support the "other solution" in the issue.
```
other solution (I prefer this one, it matches the document but it changes the current behavior): disallow any way to send escapekeys into container
if the type sequeue is the escapekeys, we do the detach
if the type sequeue is any prefix of the escapekeys, we put it into container, rather than eat(discard) it.
```

it is very easy to implement any solution, what we need to do is to determine which solution.

**Comment by laijs** [comment]
If any one want a way to send escapekeys into container, the following is a solution:

1) escapekeys should be two keys
2) the two keys should be different
3) key1+any key(not key1 nor key2): send key1 and the followed key into container
4) key1+key1 send only key1 into container, especially, key1+key1+key2, send the escapekesy into container.
5) key1+key2 detach from container.

**Comment by laijs** [comment]
please choose one, @docker-team
