### ISSUE TITLE
resolv.conf don't match with `--net=host` used

### ISSUE THREAD

**Issue by AndriiOmelianenko** [docker/docker#21761]
**Output of `docker version`:**

```
Docker version 1.9.1, build 78ee77d/1.9.1
```

**Output of `docker info`:**

```
Containers: 1
Images: 37
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-253:1-126893-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem:
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.792 GB
 Data Space Total: 107.4 GB
 Data Space Available: 102.3 GB
 Metadata Space Used: 3.375 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.20.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 4
Total Memory: 20.11 GiB
Name: aomelian.example.com
ID: DDJ4:UUVO:FNZD:FXIL:LI34:T5CS:6QEA:DIDH:5I5Y:WVUS:Q54B:CEFU
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Instance created in Openstack.

**Steps to reproduce the issue:**
* Check resolv.conf of the host: 
```
[cloud-user@aomelian ~]$ cat /etc/resolv.conf
search node.consul
nameserver 127.0.0.1
```
* Run docker container with `--net=host`
```
[cloud-user@aomelian ~]$ sudo docker run --net=host --privileged -d ...
```
* check that container is running, get id:
```
[cloud-user@aomelian ~]$ sudo docker ps
CONTAINER ID        IMAGE                      COMMAND             CREATED             STATUS              PORTS               NAMES
cc3959122888       aomelian/aomelian   "/usr/sbin/init"    6 minutes ago       Up 6 minutes                            stoic_mietner
```
* enter container filesystem:
```
[cloud-user@aomelian ~]$ sudo docker exec -i -t cc3959122888 bash
```
* Check resolv conf in container:
```
[root@aomelian /]# cat /etc/resolv.conf
search node.consul

nameserver 8.8.8.8
nameserver 8.8.4.4
```

**Describe the results you received:**

```
nameserver 8.8.8.8
nameserver 8.8.4.4
```

**Describe the results you expected:**

I expect that container's resolv.conf will match the host's one.
```
nameserver 127.0.0.1
```

**Additional information you deem important (e.g. issue happens only occasionally):**
it was working fine in older version:
```
Docker version 1.8.2-el7.centos, build a01dc02/1.8.2
```

**Comment by HackToday** [comment]
could you give the full command 
`sudo docker run --net=host --privileged -d` ?

I could not reproduce it on docker 1.9.1 and 1.01.*

**Comment by thaJeztah** [comment]
It looks like you're running a Red Hat version of Docker (this is the commit that it's built from: https://github.com/projectatomic/docker/commit/78ee77d). Their version contains a lot of changes that makes Docker work different than the official builds, and we don't have the source for those changes in this repository

Can you report this issue in the Red Hat issue tracker; https://bugzilla.redhat.com ?
