### ISSUE TITLE
Fully embrace daemon.json when installing docker

### ISSUE THREAD

**Issue by programmerq** [docker/docker#21778]
1.10 introduced the daemon.json config file. Currently, there is no daemon.json that is included when you install using the get.docker.com method. Additionally, the command line options can override their corresponding configs in daemon.json should a user choose to create one.

Let's favor the new daemon.json config file over command line options in our packages:

For example, instead of my debian `/lib/systemd/system/docker.service` including the `-H fd://` in the `ExecStart` line, it would look like this:

    ExecStart=/usr/bin/docker daemon

The `.dpk` file would also include a daemon.json that looks something like this:

    {
            "hosts": ["fd://"]
    }

**Comment by thaJeztah** [comment]
@programmerq duplicate of https://github.com/docker/docker/issues/20151 ?

**Comment by programmerq** [comment]
@thaJeztah this does indeed seem to be a duplicate of #20151. I totally missed it in my search. Thanks!
