### ISSUE TITLE
Failed to attach container to multiple network on start.

### ISSUE THREAD

**Issue by saladinkzn** [docker/docker#21775]
Hello
Is there a way to attach container to multiple networks at start?
duplicating --net flag doesn't work as expected.

**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 32
 Running: 8
 Paused: 0
 Stopped: 24
Images: 187
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 299
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-83-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 2.931 GiB
Name: Suleiman
ID: 6LOP:WL4M:6U4L:SJ6Y:ZAFL:UI5X:JZ2S:66PV:4VJH:F7EP:F7CR:OCQ4
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Create two networks (net1 and net2)
2. docker run --net net1 --net net2 IMAGE

**Describe the results you received:**
docker inspect shows that container is attached to net2 only

**Describe the results you expected:**
docker inspect shows that container is attached to net1 and net2

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment]
No way to do this with `docker run`
`--net` is (intentionally) for a single network.

You can do this with `docker create ... && docker network connect ... && docker start`

**Comment by thaJeztah** [comment]
Also see the discussion on https://github.com/docker/docker/pull/17796 for more information about why we decided not to accept multiple `--net` options on `docker run`
