### ISSUE TITLE
Volume names shouldn't have invalid character restrictions 

### ISSUE THREAD

**Issue by suryagaddipati** [docker/docker#21786]
Volumes dealt by volume plugins should not have these restrictions 

```
[~]# docker run  -it -v abc@45:/images busybox sh
volume name invalid: "abc@45" includes invalid characters
for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed.

```

Api seems to allow this but command line fails with that error message but only for mounting, not for volume create, rm ect.

**Comment by thaJeztah** [comment]
We restricted the Volume names for the local driver to make sure names are compatible with any host/system that Docker can run on.

See some examples that we want to prevent here https://github.com/docker/docker/pull/16140#issuecomment-141254127, and the discussion on https://github.com/docker/docker/issues/16132 and https://github.com/docker/docker/pull/17213

Note that this restriction is only put on the default ("local") volume driver

Is there a specific reason you need to have other characters in your volume names?

**Comment by vpereira** [comment]
I have a related problem when a local directory has ":" on the name. Even escaping it with \: doesn't work. how to reproduce it:

````
mkdir MY:SUPERDIR
cd MY:SUPERDIR
docker run -it -v $PWD:/images busybox sh
# or
docker run -it -v "${PWD}":/images busybox sh
# or
docker run -it -v "$PWD":/images busybox sh
# or 
docker run -it -v /home/foo/MY\:SUPER:/images busybox sh
# or
docker run -it -v "/home/foo/MY:SUPER":/images busybox sh

````

if I rename the dir to something like MY-SUPERDIR it works like charm.

**Comment by cpuguy83** [comment]
@vpereira This is not related, and I'm certain there is an open issue for that one.

**Comment by cpuguy83** [comment]
Testing on 1.11-rc3, `volume create` is rejecting this as well.
`Error response from daemon: create abc@45: "abc@45" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed`

Not sure that I'm comfortable allowing `@` as it's been a suggested syntax for targeting driver names on `docker run` (even if we may never support it).

**Comment by suryagaddipati** [comment]
> Testing on 1.11-rc3, volume create is rejecting this as well.

 I think thats fair. Closing this issue.

**Comment by cpuguy83** [comment]
Thanks @suryagaddipati

**Comment by vpereira** [comment]
@cpuguy83 I couldn't find an open issue about it.. should I open a new one?

**Comment by cpuguy83** [comment]
@vpereira So sad Google search is better than GH issue search... Here's the open issue #8604

**Comment by nbastin** [comment]
This ticket is closed, but I want to register my strong disappointment.  I don't understand why paths can't be anything that can be valid in your filesystem - shooting for a "least common denominator" system just creates an endless stream of problems.  Even different filesystems on the exact same host can't use the same path names.

We have ZFS pools that are labeled by URN (as they are globally coordinated across administrative boundaries), and to use them in docker is practically impossible (it requires absurd orchestration hijinx that then need to be separately tracked).  I know the complaints of users have to be weighed against various impacts, but this will probably slowly mean the end of our support for docker (as all newly deployed systems use these ZFS mounts), and I don't believe this restriction has any practical benefit (if you can't find the path we're referencing, it's the same as any other failure, the validation is not docker's problem).

**Comment by thaJeztah** [comment]
@nbastin could you please open a new issue / feature request with your use case; also describe what format you would like to see supported. The reason for restricting this is to prevent cases like https://github.com/docker/docker/pull/16140#issuecomment-141254127, which could lead to docker not being able to run consistently across platforms/hosts
