### ISSUE TITLE
Log driver error after upgrading docker from 1.62 to 1.9.1

### ISSUE THREAD

**Issue by MrMMorris** [docker/docker#21781]
**Output of `docker version`:**

```
Docker version 1.9.1, build a34a1d5
```

**Output of `docker info`:**

```
Containers: 5
Images: 245
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 255
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-18-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 3.858 GiB
Name: blah
ID: 47EM:TJ4Q:GQUD:32ZF:7G7B:OIFY:B6GO:7W75:TNTX:IGPC:5BV7:O7AU
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

EC2

**Steps to reproduce the issue:**
1. Have containers running with docker 1.6.2 installed
2. Stop docker daemon
3. uninstall lxc-docker-1.6.2 
4. install docker-engine=1.9.1-0~trusty
5. start docker  and make sure containers come back up
6. add `--log-driver=fluentd` to DOCKER_OPTS
7. restart docker 

**Describe the results you received:**

Containers will fail with `"logs" command is supported only for "json-file" and "journald" logging drivers (got: fluentd)` even though the fluentd log driver was added in `1.8.0`

**Describe the results you expected:**

New Fluentd driver is used

**Additional information you deem important (e.g. issue happens only occasionally):**

It seems like the old containers that were moved from 1.6.2 still think they are running on 1.6.2? Do I have to kill and recreate them in order to get them to use the "new" docker version?

**Comment by thaJeztah** [comment]
Yes, the `fluentd` log-driver was added, but not all logging drivers can be used to fetch logs through `docker logs`. The documentation mentions this as well; https://docs.docker.com/engine/reference/commandline/logs/

In case of the fluentd driver, the logs are sent [directly to a fluentd collector](https://docs.docker.com/engine/admin/logging/fluentd/), so the docker daemon no longer has those logs available to output them through `docker logs`.

I'm not sure why your containers start to fail; are you running docker-in-docker, and is a container calling the `docker logs` command?

Other than that, this is expected, as mentioned above.

**Comment by MrMMorris** [comment]
@thaJeztah I am not running docker-in-docker and I am not calling `docker logs`. The containers fail with that error right after adding the options to DOCKER_OPTS and restarting (I have confirmed this on other hosts that were previously using 1.6.2). 

As I said, it almost seems like the containers that were previously run on 1.6.2 still "think" they are running on 1.6.2 and that's why they fail with that error.

**Comment by thaJeztah** [comment]
Strange; I searched the code, and it looks like that message is only triggered if the `docker logs` command is called (https://github.com/docker/docker/blob/v1.9.1/api/client/logs.go#L45-L47).

How are your containers started? Do you use some orchestration tool to run your containers?

**Comment by MrMMorris** [comment]
@thaJeztah I can reproduce the problem with the following steps:

```
$ docker --version 
Docker Version 1.6.2, build 7c8fca2

$ docker ps
CONTAINER ID        IMAGE                         COMMAND                CREATED             STATUS                  PORTS                     NAMES

$ docker run -d --restart=always --name redis redis:3.0.3
7e752b4790bd1a30a04ada46e2c09b9de5e6f2ad

$ docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS               NAMES
7e752b4790bd        redis:3.0.3         "/entrypoint.sh redi   2 seconds ago       Up 1 seconds        6379/tcp            redis

$ service docker stop
docker stop/waiting

$ apt-get remove --purge -y lxc-docker-1.6.2 lxc-docker
<APT OUTPUT>

$ apt-get install -y docker-engine=1.9.1-0~trusty
<APT OUTPUT>
docker start/running, process 9268

$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
7e752b4790bd        redis:3.0.3         "/entrypoint.sh redis"   12 minutes ago      Up 3 seconds        6379/tcp            redis

$ docker logs redis
<NORMAL REDIS STARTUP>

$ echo DOCKER_OPTS=\"--log-driver=fluentd\" >> /etc/default/docker

$ service docker restart
docker stop/waiting
docker start/running, process 10047

$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                        PORTS               NAMES
7e752b4790bd        redis:3.0.3         "/entrypoint.sh redis"   18 minutes ago      Exited (128) 59 seconds ago                       redis

$ docker logs redis
"logs" command is supported only for "json-file" and "journald" logging drivers (got: fluentd)
```

**Comment by MrMMorris** [comment]
@thaJeztah I think I figured it out. The containers were failing because they were looking for the fluentd instance locally and it wasn't there yet 👅

**Comment by thaJeztah** [comment]
Oh! I just saw your other comment, thanks!

Still strange that it gives that error message, it's confusing, and I'm not sure how to explain that :blush:
