### ISSUE TITLE
NanoServer not found after 5 minutes

### ISSUE THREAD

**Issue by valof** [docker/docker#21784]
Attempted to set up windows container per instruction [https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/container_setup]

PS C:\Users\ofshtev> wget -uri https://aka.ms/tp4/New-ContainerHost -OutFile c:\New-ContainerHost.ps1
PS C:\Users\ofshtev> powershell.exe -NoProfile c:\New-ContainerHost.ps1 -VMName testcont -WindowsImage ServerDatacenterCore -Hyperv

**The output is:**

cmdlet New-ContainerHost.ps1 at command pipeline position 1
Supply values for the following parameters:
Password: *************
Before installing and using the Windows Server Technical Preview 4 with Containers virtual machine you must:
    1. Review the license terms by navigating to this link: http://aka.ms/tp4/containerseula
    2. Print and retain a copy of the license terms for your records.
By downloading and using the Windows Server Technical Preview 4 with Containers virtual machine you agree to such
license terms. Please confirm you have accepted and agree to the license terms.
[N] No  [Y] Yes  [?] Help (default is "N"): Y
Using VHD path C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks
Using external switch External VM Switch
The latest ServerDatacenterCore VHD is already present on this system.
ServerDatacenterCore Container OS Image (WIM) is already present on this system.
Creating VHD files for VM testcont...
VHD mount must be synchronized with other running instances of this script.  Waiting for exclusive access...
Mounting ServerDatacenterCore VHD for offline processing...
Enabling Containers feature on drive G...
Enabling Hyper-V feature on drive G...
Copying Docker into ServerDatacenterCore VHD...
Copying NSSM into ServerDatacenterCore VHD...
This script uses a third party tool: NSSM. For more information, see https://nssm.cc/usage
Downloading NSSM...
Extracting NSSM from archive...
Writing default unattend.xml...
Copying Install-ContainerHost.ps1 into ServerDatacenterCore VHD...
Dismounting VHD...
Creating VM testcont...
Configuring VM testcont...
Connecting VM to switch External VM Switch
WARNING: Nested virtualization is an unsupported preview feature. Hypervisors other than the Hyper-V hypervisor
running in a guest virtual machine are likely to fail. Furthermore, some Hyper-V features are incompatible with
nested virtualization, such as dynamic memory, checkpoints, and save/restore.
Starting VM testcont...
Waiting for VM testcont to boot...
Connected to VM testcont Heartbeat IC.
Waiting for specialization to complete (this may take a few minutes)...
Executing Install-ContainerHost.ps1 inside the VM...
Completing container install...
Querying status of Windows feature: Containers...
Feature Containers is already enabled.
Querying status of Windows feature: Hyper-V...
Feature Hyper-V is already enabled.
Waiting for Hyper-V Management...
Enabling container networking...
Creating container switch (NAT)...
Creating NAT for 172.16.0.0/24...
Installing Container OS image from D:\WindowsServerCore.wim (this may take a few minutes)...
Container base image install complete.  Querying container images...
C:\Install-ContainerHost.ps1 : **Image NanoServer not found after 5 minutes**
At line:1 char:1
+ C:\Install-ContainerHost.ps1 -PSDirect -NATSubnetPrefix 172.16.0.0/24 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Install-ContainerHost.ps1

C:\New-ContainerHost.ps1 : Install-ContainerHost.ps1 failed in the VM
At line:1 char:1
+ c:\New-ContainerHost.ps1 -VMName testcont -WindowsImage ServerDatacen ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-ContainerHost.ps1

**the log file at the VM show**
PS C:\Users\Administrator> type C:\Install-ContainerHost.log
Querying status of Windows feature: Containers...
Feature Containers is already enabled.
Querying status of Windows feature: Hyper-V...
Feature Hyper-V is already enabled.
Waiting for Hyper-V Management...
Enabling container networking...
Creating container switch (NAT)...
Creating NAT for 172.16.0.0/24...
Installing Container OS image from D:\WindowsServerCore.wim (this may take a few minutes)...
Container base image install complete.  Querying container images...
C:\Install-ContainerHost.ps1 : Image NanoServer not found after 5 minutes
At line:1 char:1
+ C:\Install-ContainerHost.ps1 -PSDirect -NATSubnetPrefix 172.16.0.0/24 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Install-ContainerHost.ps1

**Additional environment details (AWS, VirtualBox, physical, etc.):**
On my physical box I run Windows 10 Enterprise
Version 1511
Build 10586.164

**Comment by vdemeester** [comment]
ping @valof is this still happening ?
/cc @jhowardmsft ptal maybe (or close :angel:)

**Comment by jhowardmsft** [comment]
That script no longer exists. Closing.
