### ISSUE TITLE
Syslog timestamp should include fractional time

### ISSUE THREAD

**Issue by deadbeef84** [docker/docker#21793]
It would be nice if the syslog driver would include sub-second precision. I dont think it's a limitation of syslog since it uses [rfc3339](https://www.ietf.org/rfc/rfc3339.txt) for the timestamp, which does support fractional time. 

The reason I would like this is because I'm forwarding the logs to logstash, which indexes each log entry and then orders them using the timestamp. This means log events which happen on the same second loses its ordering.

I think the change would be quite simple:
https://github.com/docker/docker/blob/bb9b17314df3/daemon/logger/syslog/syslog.go#L72
Replace
```timestamp := time.Now().Format(time.RFC3339)```
With
```timestamp := time.Now().Format(time.RFC3339Nano)```

Another alternative is to make it a syslog driver option.

**Comment by thaJeztah** [comment]
Given that we added an option to specify the format in Docker 1.11 (see https://github.com/docker/docker/pull/20121), perhaps this could be an option that could be selected?

**Comment by yongtang** [comment]
@deadbeef84 I take a look at rfc5424 it seems that there are additional restrictions on top of rfc3339:
https://tools.ietf.org/html/rfc5424#section-6.2.3
```
   Example 5 - An Invalid TIMESTAMP

         2003-08-24T05:14:15.000000003-07:00

   This example is nearly the same as Example 4, but it is specifying
   TIME-SECFRAC in nanoseconds.  This results in TIME-SECFRAC being
   longer than the allowed 6 digits, which invalidates it.
```
So it looks like rfc5424 only allows microsecond resolution.

**Comment by yongtang** [comment]
I added a pull request #21844 to try to address this issue. Don't know if it meets the expectation though would be glad to hear any comment or feedbacks.

**Comment by deadbeef84** [comment]
This is exactly what I want! I only added nanoseconds because go had a built-in constant for that ;) anyway, awesome work!
