### ISSUE TITLE
GELF logging driver trims milliseconds from @timestamp field

### ISSUE THREAD

**Issue by wkruse** [docker/docker#21791]
**Output of `docker version`:**

```
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   cedd534-dirty
 Built:        Thu Feb 18 16:25:16 UTC 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   cedd534-dirty
 Built:        Thu Feb 18 16:25:16 UTC 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 10
Images: 72
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.2-coreos-r2
Operating System: CoreOS 835.13.0
CPUs: 32
Total Memory: 31.38 GiB
```

**Steps to reproduce the issue:**

```
--log-driver=gelf --log-opt gelf-address=udp://your-server:12201
```

**Describe the results you received:**

```
{
            "version" => "1.1",
               "host" => "default",
              "level" => 6,
           "facility" => "",
           "@version" => "1",
         "@timestamp" => "2016-02-18T13:25:38.000Z",
                  ... => ...
 }
```

What is the reason to trim milliseconds from `@timestamp` field in GELF logging driver?

```
		TimeUnix: float64(msg.Timestamp.UnixNano()/int64(time.Millisecond)) / 1000.0,
```
https://github.com/docker/docker/blob/3d13fddd2bc4d679f0eaa68b0be877e5a816ad53/daemon/logger/gelf/gelf.go#L137

Is it because of the strange format with decimal places for milliseconds?

> timestamp number
Seconds since UNIX epoch with optional decimal places for milliseconds; SHOULD be set by client library. Will be set to NOW by server if absent.

http://docs.graylog.org/en/latest/pages/gelf.html#gelf-format-specification

**Comment by mariussturm** [comment]
It's not trimming the milliseconds, the mentioned code is simply generating the decimal places in the correct form. I get a timestamo like this when I send a log message to Graylog: `2016-04-07T14:03:40.077Z`

**Comment by thaJeztah** [comment]
looks like this isn't an issue then, I'll close this, but feel free to comment if you think I closed this by mistake

**Comment by wkruse** [comment]
@mariussturm You're completely right. Sorry for the noise, [Logstash GELF Input Plugin](https://github.com/elastic/logstash/issues/4565) was kidding me.
