### ISSUE TITLE
[1.11.0-rc3] Mounting /dev breaks the host tty

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#21808]
**Steps to reproduce the issue:**
1. docker run -v /dev:/dev busybox
2. start new terminal (e.g. run `xterm`)

**Describe the results you received:**
Unable to start new terminal, strace shows there's no pty's available.
So far I can see that when mounting `/dev` as in step 1, `/dev/ptmx` is changed to a symlink
All the pts mounts are in place, everything else seems to be normal.

**Describe the results you expected:**
mounting `/dev` into a container should not break the host's pty

**Additional information you deem important (e.g. issue happens only occasionally):**
This does not happen on 1.10

**Comment by cpuguy83** [comment]
Confirmed, it does seem to be this new symlink which replaces `/dev/ptmx` and points to `/dev/pts/ptmx` which has no perms: `c---------`

**Comment by crosbymichael** [comment]
What patch?

**Comment by cpuguy83** [comment]
@crosbymichael patch?

btw, cannot repro on docker for mac.
Seeing this on debian jessie.

```
Containers: 16
 Running: 0
 Paused: 0
 Stopped: 16
Images: 36
Server Version: 1.11.0-rc3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 137
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.871 GiB
Name: deb
ID: RVSK:ICZK:FZKT:2VUO:NWBA:4NJC:BM4I:FWPX:2Q7Z:UBTP:BCC4:4AL4
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Comment by crosbymichael** [comment]
This is not really a new issue, its always been a bad idea to mount host dev because of the tty and we have to create things inside it so its happens.  I don't recall anything changing around it recently.

**Comment by cpuguy83** [comment]
Well, I can uninstall rc3 and install 1.10 and it doesn't happen, re-upgrade to rc3 and it happens :(

**Comment by AkihiroSuda** [comment]
Identical to #20670?

**Comment by cpuguy83** [comment]
@AkihiroSuda Maybe similar symptoms, but ultimately this is a new issue in 1.11.

**Comment by AkihiroSuda** [comment]
@cpuguy83 Thank you for information.
I also confirmed it is even reproducible with 1.11-rc4 on Ubuntu 15.10 (MountFlags=slave), and it is completely differs from #20670.

As mentioned in the original report, /dev/ptmx became a weird symlink:
```
lrwxrwxrwx   1 root root             8  Apr  8 10:29 ptmx -> pts/ptmx
```

(Original ptmx was as follows:)
```
crw-rw-rw-   1 root tty         5,   2  Apr  8 10:29 ptmx
```

**Comment by AkihiroSuda** [comment]
This code seems symlinking ptmx. Perhaps should be tracked as a containerd issue?
https://github.com/docker/containerd/blob/b4c901f34a8cd5b892796732a4e5c34d70dc6ec1/vendor/src/github.com/opencontainers/runc/libcontainer/rootfs_linux.go#L554

**Comment by cpuguy83** [comment]
ping @mrunalp Maybe you have some idea where this change may have occurred.
The best I can see is potentially `config.Devices` was populated in 1.10 and now it's not populated since `/dev/ptmx` is not symlinked when mounting `/dev` in 1.10.

**Comment by cpuguy83** [comment]
In https://github.com/opencontainers/runc/blob/master/libcontainer/rootfs_linux.go#L35

**Comment by mrunalp** [comment]
@cpuguy83 We used to set this to `config.Devices` to nil when we had a user mount over `/dev`. See https://github.com/docker/docker/pull/16639/files. We need an equivalent fix for 1.11.

**Comment by mrunalp** [comment]
@cpuguy83 I think we should move the /dev detecting logic to runc/libcontainer since we introduced default devices.

**Comment by AkihiroSuda** [comment]
@cpuguy83 Could you PTAL https://github.com/opencontainers/runc/pull/732 ?

**Comment by thaJeztah** [comment]
Reopening, because the required changes are not yet vendored here

**Comment by tiborvass** [comment]
they are now
