### ISSUE TITLE
daemon/logger/fluentd: unused configuration

### ISSUE THREAD

**Issue by LK4D4** [docker/docker#21803]
I found some unused configuration options in the fluentd driver. Here is list

```
    defaultTagPrefix   = "docker"
    defaultTimeout                = 3 * time.Second
    defaultReconnectWaitIncreRate = 1.5
```

I dunnot what to do with them for now. ping @tagomoris

**Comment by tagomoris** [comment]
`defaultTagPrefix` seems that I thought we can use it to configure tags for logs, but now we can use `log-tag` option and loggerutils. It can be simply removed.

Rest two are also in configuration option of `fluent-logger-golang`. If someone want to make it configurable from docker layer, these are useful as default values.
If we don't do it right now, we can remove them (and will add these again when making them configurable).

**Comment by milindchawre** [comment]
#dibs 
@tagomoris So its OK to remove these three options?

**Comment by tagomoris** [comment]
Yes, it's ok.
