### ISSUE TITLE
Debian container caching ip address

### ISSUE THREAD

**Issue by jeffjohnston** [docker/docker#21823]
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 6
 Running: 4
 Paused: 0
 Stopped: 2
Images: 19
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 100
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.13.0-37-generic
Operating System: Ubuntu 14.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 23.24 GiB
Name: jjohnston-workstation
ID: AGFX:6GM3:G4KR:3LR2:7MQY:K7XX:DCNC:YDZP:S2SG:3QUN:FIGZ:Q5PM
WARNING: No swap limit support
```

**Steps to reproduce the issue:**

When using ping I am not able to rotate through the ip addresses using a debian:jessie container. I am using Consul as the DNS server and Registrator to get my containers registered into Consul. When debugging this it appears that there is some sort of caching going on that I cannot see when using the debian:jessie image. If I use the ubuntu image things work as expected. I keep checking nslookup and dig and it looks like Consul is totally fine. It is returning both ip addresses (in my example) and rotating them like you would expect. 

I did get this down to a simple and totally reproducible example (below). What you do is fire up Consul, Registrator and a few Redis containers. Then you bash into debian:jessie and see that when pinging it is not doing a round robin. When you go into the ubuntu image it does what you would expect. If you install nslookup or dig in those containers you can see that Consul returns both Redis ip addresses just like you would expect. You can also curl into Consul to get the Redis ip addresses.

Its not just ping that is not working either. I am using the httpd (apache) container which extends debian:jessie and it is preventing apache from doing the round robin as well. Also, we do have "disablereuse=On" when using ProxyPass when using apache and that should prevent any caching from apache.

I tried this on my machine and we tried it on somebody else's computer and it has the same problem. I did, however, try this on a fresh Redhat 7 install and it does work there with debian:jessie.

In this example my docker engine is using 172.17.0.1 for the ip.

```
# fire up consul
$ docker run -d \
    -p 8400:8400 \
    -p 8500:8500 \
    -p 172.17.0.1:53:8600/udp \
    -h node1 gliderlabs/consul-server \
    -bootstrap    

# fire up registrator    
$ docker run -d \
    --name=registrator \
    --net=host \
    --volume=/var/run/docker.sock:/tmp/docker.sock \
    gliderlabs/registrator:latest -internal \
      consul://localhost:8500


# load up a few containers   
$ docker run -d -P -h redis redis
$ docker run -d -P -h redis redis


# you can see the ip addresses used here
$ curl 172.17.0.1:8500/v1/catalog/service/redis


# using debian:jessie and running 'ping redis' only ever returns one ip address
$ docker run -i -t --dns=172.17.0.1 --dns-search service.consul debian:jessie /bin/bash

# using ubuntu and running 'ping redis' round robins the ip addresses
$ docker run -i -t --dns=172.17.0.1 --dns-search service.consul ubuntu /bin/bash  
```

**Additional information you deem important (e.g. issue happens only occasionally):**

I found one other person that has this problem on the forums.

https://forums.docker.com/t/consul-dns-round-robin-works-for-host-but-not-for-containers/6663

**Comment by jeffjohnston** [comment]
@mrjana and @mavenugo I was told to put you in the loop by nathanleclaire on the forums.

https://forums.docker.com/t/consul-dns-round-robin-works-for-host-but-not-for-containers/6663

**Comment by mavenugo** [comment]
@jeffjohnston thanks for raising the issue. But am not sure if it belongs in docker/docker. Please correct me if am wrong, this seems to be a behavior of the software running inside the container, which docker daemon doesn't control.

**Comment by jeffjohnston** [comment]
I'm not sure. I do not know how much the host effects the containers. Researching this it looks like the only tools in Linux that do caching is nscd and dnsmasq, but neither of those tools are in this container. That makes me think somehow it is the problem of the containers running on a given host machine. If I set --net=host on the container and have my local /etc/resolve.conf point to the docker ip (where the dns is bound to) then it works. Also, it works on our server running Redhat 7 but not my development box running Linux Mint. I thought it could be just my computer, but then we ran this on another developer's box with a fresh install of Docker and had the same issue. It does not look like it is Consul because when I use dig or nslookup inside the container it is behaving exactly like you would expect, which is returning the ip addresses in a random order.

My example is pretty bare bones and easy to duplicate so I was hoping you might have some theories to what it might be. The debian image is very stripped down so it is interesting that the ubuntu image works better in this case. It does seem like a lot of projects extend the debian image too.

**Comment by mavenugo** [comment]
@sanimej has been doing a lot of investigation on this area and he might have some insights.

**Comment by thaJeztah** [comment]
ping @sanimej

**Comment by h4wkmoon** [comment]
Hi, I did some tests.
I have 4 containers with a consul round-robin DNS.
Pinging from a centos container, things seem to be well balanced.

Here are the stats : 
164 for the 1st
178 for the 2nd
186 for the 3rd
153 for the last
As excpectd, actually.

On a debian container, I did a lot more requests. Stats are not so good: 
around 10k for the 1st
around 20k for the 2nd
None for the 3rd and 4th.

As you can see, one of the entries gets 2/3 of the requests, another one the last 1/3, and the other entries are never considered.

I tried as well using a non-docker install of ubuntu (my laptop). Same results.
I'm not sure this is a Docker issue. It looks to me more related to debian, and ubuntu (for obvious reasons).

**Comment by sanimej** [comment]
@jeffjohnston 

When you do ping it invokes system's name resolution function, typically `getaddrinfo()`. If the DNS server returns multiple IP addresses for the name [RFC 3484](https://www.ietf.org/rfc/rfc3484.txt) specifies the rules how the destination address should be selected. Based on this `getaddrinfo()` can reorder the IPs returned to the client. If ping chooses the first IP from the list it will look like all successive ping invocations go to the same IP. Note that the destination address selection details laid out RFC 3484 take the client IP also in to consideration. So when you run in `host` mode because of the source IP being different it could change the order of IPs returned.

The glibc library used in `debian:jessie` and `ubuntu` are not the same.. There could be differences in the `getaddrinfo` implementation which could be a factor.

```` 
ubuntu
root@c15ab120d890:/# ldd --version
ldd (Ubuntu EGLIBC 2.19-0ubuntu6.6) 2.19

debian
root@b7eb25029781:/# ldd --version
ldd (Debian GLIBC 2.19-18+deb8u7) 2.19
````
If your intent is to verify DNS based load balancing ping is not the tool.

In the same consul/registrator setup I tried a nginx reverse proxy, it does loadbalance between two backend containers.

````
vagrant@net-2:~$ docker run -d -p 8000 jwilder/whoami
eb6ec7d76b446e53f8c775e02ec6d1104ea98cc21f3ef8153941491b8d229c72
vagrant@net-2:~$ docker run -d -p 8000 jwilder/whoami
5d0c08074dc8103658139f150bd43071a8c13fa77bfb6f41449b53c050854d24

And the nginx config file

http {
    server {
        location / {
            proxy_pass http://whoami:8000;
        }
    }
}

curl the host IP from another host..

vagrant@net-1:~$ curl 192.168.59.106
I'm 5d0c08074dc8
vagrant@net-1:~$ curl 192.168.59.106
I'm eb6ec7d76b44
vagrant@net-1:~$ curl 192.168.59.106
I'm 5d0c08074dc8
vagrant@net-1:~$ curl 192.168.59.106
I'm eb6ec7d76b44
vagrant@net-1:~$ 
````

**Comment by h4wkmoon** [comment]
Hi, 
I used your method (same containers, including a nginx RP), but with more nodes  of whoami (9), and more than 4 queries (a lot more).
Results with debian based nginx: Only the 3 nodes are used.
Results with centos based nginx: Only the 3 nodes are used.
The weird thing is the DNS TTL is set to 0. I guess nginx caches stuff as well.
Forcing the [resolver](http://nginx.org/en/docs/http/ngx_http_core_module.html#resolver) parameter in nginx solves the issue. I guess it prevents nginx from asking the system to resolve the entry and forces it to it itself.

curl does not seem to suffer from the issue and respects the TTL set to 0. On both centos and debian, repeated queries on the DNS entry are balanced on all the nodes. (as expected, actually)

I'm not sure where the issue resides, and if it is even a docker issue. The thing is : One has to be carefull when using dns load-balancing.

**Comment by thaJeztah** [comment]
I think it's a known issue that the free version of nginx only resolves once, and caches the result until restart, if that's what you're seeing

**Comment by thaJeztah** [comment]
per https://github.com/docker/docker/issues/21823#issuecomment-275829152, this does not appear to be a docker issue, so let me close this issue
