### ISSUE TITLE
"Understanding container communication" in docs iptables advice doesn't work in 1.10.x

### ISSUE THREAD

**Issue by jbfink** [docker/docker#21833]
On the [official networking documentation page](https://docs.docker.com/engine/userguide/networking/default_network/container-communication/), there's a paragraph that addresses using iptables to restrict access to containers by IP:

> Docker’s forward rules permit all external source IPs by default. To allow only a specific IP or network to access the containers, insert a negated rule at the top of the DOCKER filter chain. For example, to restrict external access such that only source IP 8.8.8.8 can access the containers, the following rule could be added:

>`$ iptables -I DOCKER -i ext_if ! -s 8.8.8.8 -j DROP`

This may have been true for older versions of Engine but I can't get this to work in 1.10.3. The rule is applied as advertised, it comes first in iptables -L DOCKER, but the containers are still reachable from the whole outside world. If the docs could be upgraded for the current version of Docker, that'd be very helpful. Thanks!

**Comment by thaJeztah** [comment]
Thanks @jbfink!


@aboch, I'll assign you to this, but let me know if someone else was planning to work on it

**Comment by aboch** [comment]
@jbfink 
I followed the steps you highlighted in the documentation, but I could verify they still hold true.
I am running the docker version 1.11.0-rc4. I am posting below what I did.
I ran a minimal test, so I might have missed what is actually not working. Please take a look at it and let me know.
Thanks.

I am running a container on host1 which exposes a certain port and run a netcat instance on it:
```
host1$ docker run --rm -it -p 9000:90 busybox 
/ # nc -lp 90
```
At this time only the following has been programmed for the `DOCKER` chain:
```
host1$ sudo iptables -S DOCKER
-N DOCKER
-A DOCKER -d 172.17.0.2/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 90 -j ACCEPT
```

And a netcat client running on another host can reach the container's netcat server:
```
host2$ nc 192.168.100.119 9000
Hi, this is host2
```
```
host1$ docker run --rm -it -p 9000:90 busybox 
/ # nc -lp 90
Hi, this is host2
```

If now I repeat this but first I add the restrictive rule as specified in the docs (wlp3s0 is the interface currently providing external connectivity on host1):
```
host1$ sudo iptables -I DOCKER -i wlp3s0 ! -s 8.8.8.8 -j DROP
host1r$ sudo iptables -S DOCKER
-N DOCKER
-A DOCKER ! -s 8.8.8.8 -i wlp3s0 -j DROP
-A DOCKER -d 172.17.0.2/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 90 -j ACCEPT
```
I am trying to reach the container from host2 again:
```
host2$ nc 192.168.100.119 9000
Hi, this is host2 again
```
but nothing is received on host1's container:
```
host1$ docker run --rm -it -p 9000:90 busybox
/ # nc -lp 90
```

A tcpdump on the veth interface connecting the `docker0` bridge to the container also reveals no packets being sent to the container.

And the restrictive rule shows it is dropping packets:
```
host1$ sudo iptables -nvL DOCKER 1
   14   840 DROP       all  --  wlp3s0 *      !8.8.8.8              0.0.0.0/0 
```

Another way to see this is to check the container can now effectively receive packets only from 8.8.8.8 (the Google public IPv4 DNS). A query to another resolver would not complete:
```
host1$ docker exec a901cc5f67bd nslookup www.docker.com 8.8.8.8
Server:    8.8.8.8
Address 1: 8.8.8.8 google-public-dns-a.google.com

Name:      www.docker.com
Address 1: 104.239.220.248
host1$ 
host1$ docker exec a901cc5f67bd nslookup www.docker.com 8.8.4.4
[ does not complete ]
```

**Comment by jbfink** [comment]
Hi @aboch, thanks for the prompt reply!

I can confirm that I ran the examples you've given and the nslookup behaves as you've indicated, and a test I've run with an nginx container does too! Thanks so much -- my problem was that I interpreted `ext-if` as a literal instead of the interface name. Dumb mistake on my part, but maybe put it like `<ext-if>` in the docs so it's a little clearer.

**Comment by aboch** [comment]
Thanks @jbfink for confirming.
Agree, the examples in the documentation should not be open to interpretation. Will make the change as per your advice.
