### ISSUE TITLE
Apparmor  seems not work in ubuntu

### ISSUE THREAD

**Issue by HackToday** [docker/docker#21838]
**Output of `docker version`:**

```
1.11.rc3
```

**Output of `docker info`:**

```
Containers: 13
 Running: 1
 Paused: 0
 Stopped: 12
Images: 4
Server Version: 1.11.0-rc3
Storage Driver: vfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-43-generic
Operating System: Ubuntu 14.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.798 GiB
Name: workone
ID: PJ4B:5XJT:QCLI:KI4Y:6ZFT:HNJQ:KIUH:ZTMH:QLEC:DR3M:6XRH:2BLY
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 17
 Goroutines: 35
 System Time: 2016-04-07T03:04:23.447413079Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.  create a apparmor profile as following
```


#include <tunables/global>


profile docker-default-test2 flags=(attach_disconnected,mediate_deleted) {

  #include <abstractions/base>


  network,
  capability,
  file,
  umount,

  deny @{PROC}/* w,   # deny write for all files directly in /proc (not in a subdir)
  # deny write to files not in /proc/<number>/** or /proc/sys/**
  deny @{PROC}/{[^1-9],[^1-9][^0-9],[^1-9s][^0-9y][^0-9s],[^1-9][^0-9][^0-9][^0-9]*}/** w,
  deny @{PROC}/sys/[^k]** w,  # deny /proc/sys except /proc/sys/k* (effectively /proc/sys/kernel)
  deny @{PROC}/sys/kernel/{?,??,[^s][^h][^m]**} w,  # deny everything except shm* in /proc/sys/kernel/
  deny @{PROC}/sysrq-trigger rwklx,
  deny @{PROC}/mem rwklx,
  deny @{PROC}/kmem rwklx,
  deny @{PROC}/kcore rwklx,

  deny mount,

  deny /sys/firmware/efi/efivars/** rwklx,
  deny /sys/kernel/security/** rwklx,

  deny @{HOME}/** mrwkl,

  # suppress ptrace denials when using 'docker ps' or using 'ps' inside a container
  ptrace (trace,read) peer=docker-default,

}
```
2. the load it
3. check if load or not
```
~$ sudo aa-status 
apparmor module is loaded.
6 profiles are loaded.
6 profiles are in enforce mode.
   /sbin/dhclient
   /usr/lib/NetworkManager/nm-dhcp-client.action
   /usr/lib/connman/scripts/dhclient-script
   /usr/sbin/tcpdump
   docker-default
   docker-default-test2
0 profiles are in complain mode.
1 processes have profiles defined.
1 processes are in enforce mode.
   docker-default (3714) 
0 processes are in complain mode.
0 processes are unconfined but have a profile defined.
```
4.
``` 
$ sudo docker run --rm -it -v $HOME:/test   --security-opt apparmor=docker-default-test2 busybox sh
/ # cd /home
/home # ls
/home # mkdir kods
/home # 
```

**Describe the results you received:**
it still can access /home directory

**Describe the results you expected:**
container could not access it

**Additional information you deem important (e.g. issue happens only occasionally):**
Maybe I missed something for apparmor, but https://github.com/docker/docker/blob/master/docs/security/apparmor.md really not have much details for an example for that.

**Comment by HackToday** [comment]
ping @jfrazelle  Could you help this ?

**Comment by thaJeztah** [comment]
@HackToday did this work on 1.10?

**Comment by jfrazelle** [comment]
The tunable "HOME" is not what you think it is you want HOMEDIRS 

@{HOMEDIRS}=/home/

HOME is  /home/*/

Which in apparmor lobbing land is behaving appropriately 

Instead of using the tunable do :

/home/** 

For your desired behavior

**Comment by jfrazelle** [comment]
/home/**

Is what I think you want tho let me know

**Comment by HackToday** [comment]
hi @jfrazelle  yes, above comment /home/** seems work.
Another issue for that, as you can seen, I removed docker-default default rules for /sys/fs

```
  deny /sys/[^f]*/** wklx,
  deny /sys/f[^s]*/** wklx,
  deny /sys/fs/[^c]*/** wklx,
  deny /sys/fs/c[^g]*/** wklx,
  deny /sys/fs/cg[^r]*/** wklx,
```

In my profile, /sys/fs/ not have any deny, but seems I still can not create 
/ # mkdir /sys/fs/cgroup/jioids
mkdir: can't create directory '/sys/fs/cgroup/jioids': Read-only file system
/ # 

Do you know why ?  Is it controllered by seccomp? I did not quite sure

**Comment by jfrazelle** [comment]
/sys/fs/cgroup is mounted as readonly by default
https://github.com/docker/docker/blob/40dc921da21e4f1fd165f1d7da87d600e3eb8609/oci/defaults_linux.go#L50

On Wed, Apr 6, 2016 at 9:00 PM, Kai Qiang Wu <notifications@github.com>
wrote:

> hi @jfrazelle <https://github.com/jfrazelle> yes, above comment /home/**
> seems work.
> Another issue for that, as you can seen, I removed docker-default default
> rules for /sys/fs
>
>   deny /sys/[^f]*/** wklx,
>   deny /sys/f[^s]*/** wklx,
>   deny /sys/fs/[^c]*/** wklx,
>   deny /sys/fs/c[^g]*/** wklx,
>   deny /sys/fs/cg[^r]*/** wklx,
>
> In my profile, /sys/fs/ not have any deny, but seems I still can not
> create
> / # mkdir /sys/fs/cgroup/jioids
> mkdir: can't create directory '/sys/fs/cgroup/jioids': Read-only file
> system
> / #
>
> Do you know why ? Is it controllered by seccomp? I did not quite sure
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/21838#issuecomment-206686756>
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by HackToday** [comment]
Thanks @jfrazelle 

Close this issue now

**Comment by jfrazelle** [comment]
Do you think there is anything we can add to the docs to help future people
:)

On Wed, Apr 6, 2016 at 9:40 PM, Kai Qiang Wu <notifications@github.com>
wrote:

> Closed #21838 <https://github.com/docker/docker/issues/21838>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/21838#event-617822790>
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by HackToday** [comment]
Basically, I think whether apparmor or seccomp is introduction is simple,
https://github.com/docker/docker/blob/master/docs/security
it not have simple user cases or examples, which not easy to understand what could do with that except  just know docker adopt that :0  
As a user(developer or administrator), The doc said it is secure, but not know how could that secure. 

Maybe add some simple user-case or examples, could help more to understand what could do with them besides magic happened in docker internal world.

**Comment by jfrazelle** [comment]
I agree, I can work on it :) thanks!


On Wed, Apr 6, 2016 at 10:25 PM, Kai Qiang Wu <notifications@github.com>
wrote:

> Basically, I think whether apparmor or seccomp is introduction is simple,
> https://github.com/docker/docker/blob/master/docs/security
> it not have simple user cases or examples, which not easy to understand
> what could do with that except just know docker adopt that :0
>
> As a user(developer or administrator), The doc said it is secure, but not
> know how could that secure.
>
> Maybe add some simple user-case or examples, could help more to understand
> what could do with them besides magic happened in docker internal world.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/21838#issuecomment-206702693>
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>
