### ISSUE TITLE
Docker volume cannot be deleted even if container exit

### ISSUE THREAD

**Issue by jay-lau** [docker/docker#21846]
**Output of `docker version`:**

```
root@mesos002:~/src/mesos/m1/mesos/build# cd
root@mesos002:~# docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:36:33 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:36:33 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
root@mesos002:~# docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 1.10.0
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local convoy
 Network: bridge null host
Kernel Version: 4.2.3-040203-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 10.11 GiB
Name: mesos002
ID: FX5N:2ZXP:H4E5:O6UQ:ORWH:GSVO:CDWL:MSY3:WUNI:TY5B:253U:UAVU
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Create a docker volume
root@mesos002:~# docker volume create --name=mesos
mesos
2. Create a docker container using volume mesos.
root@mesos002:~# docker run -it -v mesos:/tmp ubuntu:14.04 /bin/bash
root@c747cc93a038:/# cat /proc/self/mountinfo | grep mesos
105 87 8:1 /var/lib/docker/volumes/mesos/_data /tmp rw,relatime - ext4 /dev/disk/by-uuid/017a354d-62b9-4ca2-aca2-12df8da6c82e rw,errors=remount-ro,data=ordered
root@c747cc93a038:/#
3. Exit the container, and the container will exit.
root@c747cc93a038:/# exit
exit
root@mesos002:~# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
root@mesos002:~#
4. Delete the volume mesos, failed.
root@mesos002:~# docker volume rm mesos
Error response from daemon: Conflict: remove mesos: volume is in use - [c747cc93a038665c8ee5acb0a862324d67208e8711eda725b01e760c654bc412]
root@mesos002:~#

**Questions:**
Why I cannot delete this volume? Does it still in use? How can I check the mouninfo of this volume after the container exit?
root@mesos002:~# docker volume inspect mesos
[
    {
        "Name": "mesos",
        "Driver": "local",
        "Mountpoint": "/var/lib/docker/volumes/mesos/_data"
    }
]
**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by mYmNeo** [comment]
`docker ps -a` will show all containers, your container is just stopped but not removed so `docker volume rm mesos` gives you error

**Comment by jay-lau** [comment]
Except `docker ps -a`, does their are any other ways to check the mountinfo for the volume? Such as mountinfo, namespace etc? The reason that I ask this is because the docker container is stopped, then the `mountinfo` in the container's namespace should be cleaned, then why does docker still report the volume was in use?

When the container is running, I can check the mountinfo as following, but how to check if the container is down?
```
root@c747cc9:/# cat /proc/self/mountinfo | grep mesos
105 87 8:1 /var/lib/docker/volumes/mesos/_data /tmp rw,relatime - ext4 /dev/disk/by-uuid/017a354d-62b9-4ca2-aca2-12df8da6c82e rw,errors=remount-ro,data=ordered
```

**Comment by cpuguy83** [comment]
@jay-lau The volume is in use because a container is referencing it.
Since a container can be started again we don't allow removing these volumes.
