### ISSUE TITLE
Cannot create new network

### ISSUE THREAD

**Issue by serjvanilla** [docker/docker#21847]
**Output of `docker version`:**
```
Client:
 Version:      1.11.0-rc4
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   f5e2b40
 Built:        Thu Apr  7 10:02:04 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0-rc4
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   f5e2b40
 Built:        Thu Apr  7 10:02:04 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**
```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.11.0-rc4
Storage Driver: btrfs
 Build Version: Btrfs v3.17
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.5-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.938 GiB
Name: home
ID: KPGC:72UK:SY4W:CGZO:4KEA:UPBH:F4HN:XK4J:DUZ5:2BON:AYZS:M4JN
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Steps to reproduce the issue:**
1. docker network create test_net

**Describe the results you received:**
Error response from daemon: failed to parse pool request for address space "LocalDefault" pool "" subpool "": could not find an available predefined network

**Describe the results you expected:**
 new network

**Additional information you deem important (e.g. issue happens only occasionally):**
same with 1.10.3 engine

**Comment by mavenugo** [comment]
@serjvanilla can you also include the output for `docker network ls` ?

**Comment by serjvanilla** [comment]
**Output of `docker network ls`:**
```
NETWORK ID          NAME                DRIVER
5eb11a0b3b96        bridge              bridge
e3b0bafc8588        host                host
7f5ee587851c        none                null
```
@mavenugo

**Comment by mavenugo** [comment]
thanks @serjvanilla. 

^^ @aboch

**Comment by aboch** [comment]
@serjvanilla Can you post the routes programmed on your host. Thanks.

**Comment by serjvanilla** [comment]
```
default via 192.168.1.1 dev enp9s0  proto dhcp  src 192.168.1.2  metric 1024 
10.0.0.0/8 via 10.18.0.1 dev tun0 
10.18.0.0/24 dev tun0  proto kernel  scope link  src 10.18.0.41 
172.16.0.0/12 via 10.18.0.1 dev tun0 
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 linkdown 
192.168.0.0/16 via 10.18.0.1 dev tun0 
192.168.1.0/24 dev enp9s0  proto kernel  scope link  src 192.168.1.2 
192.168.1.1 dev enp9s0  proto dhcp  scope link  src 192.168.1.2  metric 1024
```
I see my mistake. When I turn off openvpn `docker network create` works as expected. I think issue can be closed, but I will be happy to get advice how to get it works together(I have no control over OpenVPN server).

**Comment by aboch** [comment]
Thanks @serjvanilla for confirming.
Yes, when trying to self assign a subnet for a bridge network, docker checks whether any pool  from its predefined list can be used. It does so checking that the pool does not overlaps with any route on the system.
Usually vpn connections install a route which capture all the traffic, therefore it overlaps with all predefined pools.

What you can do is to create your networks first and then re-enable your vpn interface.
(Also see https://github.com/docker/libnetwork/issues/779)

**Comment by jmcadden** [comment]
Alternatively, you can configure your VPN client to ignore the IP ranges that docker uses for the local pool. For example I've added the following lines to `/etc/openvpn/client.conf` which configures OpenVPN to ignore the address ranges 172.16.0.0 - 172.31.255.255:

```
route 0.0.0.0 128.0.0.0  
route 128.0.0.0 224.0.0.0
route 160.0.0.0 248.0.0.0
route 168.0.0.0 252.0.0.0
route 172.0.0.0 255.240.0.0
route 172.32.0.0 255.224.0.0
route 172.64.0.0 255.192.0.0
route 172.128.0.0 255.128.0.0
route 173.0.0.0 255.0.0.0
route 174.0.0.0 254.0.0.0
route 176.0.0.0 240.0.0.0
route 192.0.0.0 192.0.0.0
```
