### ISSUE TITLE
How to check the mouninfo of this volume after the container exit

### ISSUE THREAD

**Issue by jay-lau** [docker/docker#21856]
**Output of `docker version`:**

```
root@mesos002:~/src/mesos/m1/mesos/build# cd
root@mesos002:~# docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:36:33 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:36:33 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
root@mesos002:~# docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 1.10.0
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local convoy
 Network: bridge null host
Kernel Version: 4.2.3-040203-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 10.11 GiB
Name: mesos002
ID: FX5N:2ZXP:H4E5:O6UQ:ORWH:GSVO:CDWL:MSY3:WUNI:TY5B:253U:UAVU
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Create a docker volume
root@mesos002:~# docker volume create --name=mesos
mesos
2. Create a docker container using volume mesos.
root@mesos002:~# docker run -it -v mesos:/tmp ubuntu:14.04 /bin/bash
root@c747cc93a038:/# cat /proc/self/mountinfo | grep mesos
105 87 8:1 /var/lib/docker/volumes/mesos/_data /tmp rw,relatime - ext4 /dev/disk/by-uuid/017a354d-62b9-4ca2-aca2-12df8da6c82e rw,errors=remount-ro,data=ordered
root@c747cc93a038:/#
3. Exit the container, and the container will exit.
root@c747cc93a038:/# exit
exit
root@mesos002:~# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
root@mesos002:~#
4. Delete the volume mesos, failed.
root@mesos002:~# docker volume rm mesos
Error response from daemon: Conflict: remove mesos: volume is in use - [c747cc93a038665c8ee5acb0a862324d67208e8711eda725b01e760c654bc412]
root@mesos002:~#

**Questions:**
How can I check the mouninfo of this volume after the container exit? From `docker volume inspect mesos` I can see the mount point, does there are any other ways which can enable me to check the mount point via mountinfo or mounts?
```
root@mesos002:~# docker volume inspect mesos
[
    {
        "Name": "mesos",
        "Driver": "local",
        "Mountpoint": "/var/lib/docker/volumes/mesos/_data"
    }
]
```
**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment]
Pretty much the only way to check is if `Mountpoint` is populated.
With the `local` volume driver this will always be populated because these are just files on the host FS (there is no actual mount other than a bind when a container is started).

**Comment by thaJeztah** [comment]
Note that in this case, the volume cannot be removed because the container you created is still there. Try running `docker ps -a`, and you'll probably see that the container is still there, just `exited`. If you remove the container, you should be able to remove the volume

**Comment by jay-lau** [comment]
@cpuguy83 So how to check the mount bind info when a container exit except `docker inspect containerid`, I believe that the system should have the bind mount persisted in some files such as `mountinfo` etc. Thanks.

**Comment by jay-lau** [comment]
@thaJeztah  Yes, same as my above question, how to check the bind mount info from system's view but not using docker command?

Can I check the bind mount info in `/proc/self/mountinfo`, `/proc/mounts` or some other system files? In which namespace can I find them? Thanks.

**Comment by thaJeztah** [comment]
@jay-lau see @cpuguy83's comment;

> there is no actual mount other than a bind when a container is started

If the container is not started, there is no mount. What do you need the mountinfo for?

**Comment by jay-lau** [comment]
@thaJeztah Then why cannot I delete the volume? Docker always report the container was in use.

Whah I want to do is I was doing a project want to integrate docker volume driver with Mesos in https://issues.apache.org/jira/browse/MESOS-4355 and I was leveraging the `dvdcli` from https://github.com/emccode/dvdcli , I want to check the mount info after the `dvdcli mount` finished, the `dvdcli mount` is actually calling docker volume driver API `mount` to generate a mount point, so I just want to know where does the mount point is from system namespace view, make sense? Thanks.

**Comment by thaJeztah** [comment]
@jay-lau because the container is still there; see my earlier comment: https://github.com/docker/docker/issues/21856#issuecomment-207033935

The container is exited/stopped, but can be restarted (`docker start the-container`). When starting the container again, it needs the volume, so it cannot be removed. Docker keeps track which containers use the volume, both running, and stopped containers.

So to remove the volume; first remove the container (`docker rm the-container`), then remove the volume `docker volume rm mesos`

**Comment by jay-lau** [comment]
@thaJeztah thanks! Can you please show me some detail for how does docker volume driver works when it try to mount an external storage to a container? 

In my understanding, it should have 2 steps:
1) Mount external storage to the local host.
2) Mount from local host to container.

If my assumption is right, then in step one, where can I check the mount info?

**Comment by thaJeztah** [comment]
You can bind-mount a directory, but then content from the container is not copied into the mounted directory (e.g. `-v /some/path/on/host:/path/in/container`) or use a volume-driver plugin that allows you to use external storage as a volume: https://docs.docker.com/engine/extend/plugins/#finding-a-plugin

Please try to read the documentation; keep in mind that the issue tracker is not a support forum, but for reporting bugs and feature requests. For other type of questions, either use;

- https://forums.docker.com
- the #docker IRC channel on freenode
- StackOverflow

**Comment by jay-lau** [comment]
@thaJeztah thanks, got it. ;-)
