### ISSUE TITLE
Cannot push local image to local repository

### ISSUE THREAD

**Issue by JFarzan** [docker/docker#21858]
**Output of `docker version`:**
```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**
```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 23
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.19.0-56-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 47.17 GiB
Name: devstack01
ID: DI6U:KDJ7:NTNV:U3T4:ZHA4:JR4N:GLOH:VOZK:LDQ4:425S:7BBP:V7V7
Http Proxy: http://<proxy>:8080/
Https Proxy: http://<proxy>:8080/
No Proxy: localhost,127.0.0.1
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Ubuntu 14.04 VM

**Steps to reproduce the issue:**
1. As in [this guide](https://docs.docker.com/registry/deploying/), run registry using `docker run -d -p 127.0.0.1:8000:8000 --restart=always --name againregistry registry:2`
2. `docker tag ubuntu 127.0.0.1:8000/ubuntu`
3. `sudo docker push 127.0.0.1:8000/ubuntu`

**Describe the results you received:**
Docker push gives 

```
The push refers to a repository [127.0.0.1:8000/ubuntu]
Put http://127.0.0.1:8000/v1/repositories/ubuntu/: read tcp 127.0.0.1:38235->127.0.0.1:8000: read: connection reset by peer
```
or 
```
The push refers to a repository [127.0.0.1:8000/ubuntu]
Put http://127.0.0.1:8000/v1/repositories/ubuntu/: EOF
```
Registry logs:
```
time="2016-04-07T15:19:31Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." go.version=go1.5.3 instance.id=6391e3dc-6644-4a45-8e8b-a08c8ff798a6 version=v2.3.1
time="2016-04-07T15:19:31Z" level=info msg="redis not configured" go.version=go1.5.3 instance.id=6391e3dc-6644-4a45-8e8b-a08c8ff798a6 version=v2.3.1
time="2016-04-07T15:19:31Z" level=info msg="Starting upload purge in 1m0s" go.version=go1.5.3 instance.id=6391e3dc-6644-4a45-8e8b-a08c8ff798a6 version=v2.3.1
time="2016-04-07T15:19:31Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.5.3 instance.id=6391e3dc-6644-4a45-8e8b-a08c8ff798a6 version=v2.3.1
time="2016-04-07T15:19:31Z" level=info msg="listening on [::]:5000" go.version=go1.5.3 instance.id=6391e3dc-6644-4a45-8e8b-a08c8ff798a6 version=v2.3.1
time="2016-04-07T15:20:31Z" level=info msg="PurgeUploads starting: olderThan=2016-03-31 15:20:31.061864096 +0000 UTC, actuallyDelete=true"
time="2016-04-07T15:20:31Z" level=info msg="Purge uploads finished.  Num deleted=0, num errors=1"
time="2016-04-07T15:20:31Z" level=info msg="Starting upload purge in 24h0m0s" go.version=go1.5.3 instance.id=6391e3dc-6644-4a45-8e8b-a08c8ff798a6 version=v2.3.1
```

**Describe the results you expected:**

Expected image to push to registry

**Additional information you deem important (e.g. issue happens only occasionally):**
I'm running behind a corporate proxy which I have accounted for in `env`, `bash.bashrc`, `/etc/systemd/system/docker.service.d/http-proxy.conf` and `/etc/default/docker`.

When I try to curl 127.0.0.1:8000 (the port for the registry), I receive a `connection reset by peer` error. However, the port is listed as listening with `netstat -ntlp`.

**Comment by thaJeztah** [comment]
What kind of proxy do you use? Does if work if you don't have a proxy enabled?

Just to test; can you try if you can run an nginx server, and curl that?

    docker run -d -p 127.0.0.1:4321:80 nginx
    curl 127.0.0.1:4321

**Comment by JFarzan** [comment]
I'm honestly not sure what kind it is, and I can't disable it. 

I ran an nginx server as you asked and I can curl it just fine.
```
$ curl 127.0.0.1:4321
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

**Comment by programmerq** [comment]
You showed that you started the registry with `-p 8000:8000`, but you probably need `-p 8000:5000`.

**Comment by thaJeztah** [comment]
@programmerq nice catch!

**Comment by JFarzan** [comment]
After a week of tearing my hair out, that one number was causing all my problems. Thanks for the tip! Why must that particular port be mapped?

**Comment by thaJeztah** [comment]
Port 5000 is the port that the registry inside the container is listening on. By doing `127.0.0.1:8000:5000` you are mapping port 5000 inside the container to port 8000 on 127.0.0.1.

Also see: https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/#connect-using-network-port-mapping

**Comment by thaJeztah** [comment]
I'll close this issue, because it looks to be resolved, but feel free to comment here after I closed
