### ISSUE TITLE
The spunk docker driver library uses a poorly named `source` field

### ISSUE THREAD

**Issue by afinkenstadt** [docker/docker#21866]
@ https://github.com/docker/docker/blob/master/daemon/logger/splunk/splunk.go#L58

@outcoldman

**Comment by thaJeztah** [comment]
@afinkenstadt what's the exact issue; what do you suggest as an alternative?

**Comment by afinkenstadt** [comment]
@thaJeztah 
Exact issue:  duplicated fields named `source` create an impediment to searching by the Splunk special tag named `source` versus the user-level tag in the event proper.

Suggested fix:  rename the `source` field on L58 to `origin`.  The hard-coded values of `origin` as `stdout` and `stderr` clarify which file descriptor was the origin of the log text.

**Comment by afinkenstadt** [comment]
Trivial change provided.  Please don't ask me to sign a CLA, and please feel welcome to make a similar change.  I disclaim all moral rights.

**Comment by outcoldman** [comment]
@afinkenstadt yes, agree terminology is overlapping, but there should not be any issues with doing search over these fields, to use splunk's source you just do

```
source=http:docker 
```

To search over docker's source you can do

```
source="http:docker" | spath path=source output=dsource | search dsource=stdout
```

**Comment by outcoldman** [comment]
@afinkenstadt please let me know if this resolves your issue

**Comment by afinkenstadt** [comment]
It does.  It's what I was trying to avoid doing, though, with a simple change in word.

**Comment by glennblock** [comment]
To change it now would be a breaking change for others that are using the
driver. I agree in hindsight we probably could have done a diff name.
