### ISSUE TITLE
docker events "until" parameter doesn't handle durations or past timestamps

### ISSUE THREAD

**Issue by aaronlehmann** [docker/docker#21865]
If I specify a timestamp in the past as a parameter for `docker events --until`, I still see events that took place after that timestamp:

```
$ docker events --since 2016-04-07T13:54:43.184116882-07:00 --until 2016-04-07T13:54:43.184116882-07:00
2016-04-07T13:54:43.184116882-07:00 testtag:: tag

2016-04-07T14:00:51.643577477-07:00 testtag2:: tag
```

The same thing applies when `--until` is a duration. If I run something like `docker events --since 1m --until 10s`, I would expect the behavior to be "print events logged between 1 minute ago and 10 seconds ago". In fact, any positive `until` parameter specified as a duration is ignored (if you use a negative `until` like `--until -6s`, it waits that amount of time for new events, which *sort of* makes sense).

To understand this, see the `getEvents` function here: https://github.com/docker/docker/blob/master/api/server/router/system/system_routes.go#L45. The `until` parameter is used to start a timer, which only makes sense if that timestamp is in the future. If the timestamp is in the past, it does not filter event stream based on that.

cc @LK4D4

**Comment by calavera** [comment]
I'm working on adding this improvement. Please check #21939.

**Comment by aaronlehmann** [comment]
Awesome!
