### ISSUE TITLE
Question:  Is there a recommended way to automate docker to use a cluster store

### ISSUE THREAD

**Issue by robbrockbank** [docker/docker#21890]
Docker 10.3.1
All OSs

I'm looking at automating docker installation with multi-host networking.  I was wondering if there was a recommended way to do this.  I have had a look through the issues and online and couldn't see anything, so apologies if I've missed something glaringly obvious!

Is it possible to install Docker (just Docker - so not using swarm) so that it automatically points to a cluster store?  (e.g. by setting some env variables before running the install).  At the moment it seems you install and then hand modify your service/init scripts to add the `--cluster-store` flag - I was hoping it's possible to automatically configure the init scripts to include the cluster store.

Thanks!

**Comment by cpuguy83** [comment]
@robbrockbank You can supply these in a config file.
The default location is `/etc/docker/daemon.json`

**Comment by thaJeztah** [comment]
Documentation for that configuration file can be found here; https://docs.docker.com/engine/reference/commandline/daemon/#daemon-configuration-file

**Comment by robbrockbank** [comment]
Awesome guys!  Thanks for your help!
