### ISSUE TITLE
DUCP docs to be clarified

### ISSUE THREAD

**Issue by arun-gupta** [docker/docker#21899]
https://docs.docker.com/ucp/evaluation-install/ are great! Some steps that need to be clarified:

- Step 6, bullet 2, its important to mention to use `https://` protocol and then `<MACHINE-IP>`. Otherwise just giving `<MACHINE-IP>` will give a HTTP 404. I figured out by seeing the mapped ports.

- Step 9, bullet 2, Edit icon is no longer available. Double click on the row shows details about the container.

- Step 10, bullet 5 seems slightly inconsistent. It should show `node1` and `node2` and instead shows `test` and `moxiegirl` machines.

- Step 10, bullet 7, zip file name is `ucp-bundle-admin.zip`, not `bundle.zip`.

**Comment by ehazlett** [comment]
@arun-gupta thanks for the feedback!  we'll get this updated.

**Comment by thaJeztah** [comment]
I see an issue is opened in the UCP repository for tracking, so I'll close it here. Thanks @arun-gupta!

**Comment by arun-gupta** [comment]
@thaJeztah can you link to the UCP repository bug?

**Comment by thaJeztah** [comment]
Hi @arun-gupta, I could, but it's a private repository, so you won't be able to see it :blush:

**Comment by thaJeztah** [comment]
It's #1213 in the UCP issue tracker

**Comment by arun-gupta** [comment]
Aha, thanks!

I trust you guys will fix it. Please update this bug when the changes are committed.
