### ISSUE TITLE
Volumes don't seem to work on windows with hyperv

### ISSUE THREAD

**Issue by justinmchase** [docker/docker#21909]
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 13
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 41
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.19-boot2docker
Operating System: Boot2Docker 1.10.3 (TCL 6.4.1); master : 625117e - Thu Mar 10 22:09:02 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 995.2 MiB
Name: default
ID: E2CN:OM3A:PQH3:TXRR:BXAN:7INY:IB37:WAW5:CCS3:QVBK:UGVH:NO7L
Debug mode (server): true
 File Descriptors: 11
 Goroutines: 25
 System Time: 2016-04-09T16:34:43.8302333Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=hyperv
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
hyperv

**Steps to reproduce the issue:**
1. Create a new machine using `--driver hyperv`
2. Add to docker-compose.yml: 
```
  command: ls -la /test
  volumes:
    - .:/test
```
3. `docker-compose up`

**Describe the results you received:**
```
web_1 | drwxr-xr-x  2 root root   40 Apr  9 16:33 .
web_1 | drwxr-xr-x 52 root root 4096 Apr  9 16:37 ..
```

**Describe the results you expected:**
```
drwxr-xr-x    1 justin   Administ     4096 Apr  9 11:03 .
drwxr-xr-x    1 justin   Administ     8192 Apr  9 10:59 ..
-rw-r--r--    1 justin   Administ       39 Apr  9 10:59 .eastrc
drwxr-xr-x    1 justin   Administ     4096 Apr  9 11:37 .git
-rw-r--r--    1 justin   Administ       89 Apr  9 10:59 .gitignore
drwxr-xr-x    1 justin   Administ        0 Apr  9 10:59 .vscode
-rw-r--r--    1 justin   Administ     1073 Apr  9 10:59 Dockerfile
-rw-r--r--    1 justin   Administ     1541 Apr  9 10:59 README.md
drwxr-xr-x    1 justin   Administ        0 Apr  9 10:59 app
-rw-r--r--    1 justin   Administ      331 Apr  9 11:37 docker-compose.yml
-rw-r--r--    1 justin   Administ     3362 Apr  9 10:59 gulpfile.js
drwxr-xr-x    1 justin   Administ        0 Apr  9 10:59 images
drwxr-xr-x    1 justin   Administ        0 Apr  9 10:59 migrations
drwxr-xr-x    1 justin   Administ    81920 Apr  9 11:03 node_modules
-rw-r--r--    1 justin   Administ     1603 Apr  9 10:59 package.json
drwxr-xr-x    1 justin   Administ        0 Apr  9 10:59 server
-rw-r--r--    1 justin   Administ      364 Apr  9 10:59 tsconfig.json
-rw-r--r--    1 justin   Administ     1896 Apr  9 10:59 tslint.json
drwxr-xr-x    1 justin   Administ        0 Apr  9 11:03 typings
-rw-r--r--    1 justin   Administ     1057 Apr  9 10:59 typings.json
```

**Additional information you deem important (e.g. issue happens only occasionally):**
This exact same code runs fine on osx with parallels.

**Comment by thaJeztah** [comment]
which directory are you trying to use as a volume (bind mount)? because boot2docker only shares content inside the c:\Users directory, not directories outside. (see https://github.com/boot2docker/boot2docker/#virtualbox-guest-additions).

You may be interested in https://blog.docker.com/2016/03/docker-for-mac-windows-beta/, which resolves most of these issues

**Comment by friism** [comment]
I don't think volumes are expected to work with the hyper-v driver.  You should use the (default) virtualbox driver.

**Comment by thaJeztah** [comment]
@friism oh! you're right this is not on VirtualBox, my bad

**Comment by justinmchase** [comment]
I tried to install virtualbox but it continually stalls out saying I have to enable something in my BIOS. I have enabled it and Hyper-V works but virtualbox still fails.

That was a while back though, maybe I'll try virtualbox again, perhaps it was just a bug. Or maybe do I have to uninstall Hyper-v first, in a there-can-be-only-one sort of situation?

Also, why doesn't hyperv support volumes? It seems like a pretty important feature.

**Comment by friism** [comment]
@justinmchase Hyper-V and Virtualbox cannot co-exist so you would have to disable Hyper-V: https://www.virtualbox.org/ticket/12350

As you've found, the experience of using non-default drivers (and even the VirtualBox driver) can be a bit patchy. That's why we're working on Docker for Mac and Windows: https://blog.docker.com/2016/03/docker-for-mac-windows-beta/

**Comment by justinmchase** [comment]
@friism Thanks for the reply! I signed up for the beta, I will just work on my mac until that is available. Keep up the good work!

**Comment by carrete** [comment]
We have this problem with the docker beta on Windows. `-v //Users/project://project` doesn't work. There is no error message but nothing is mounted under /project inside the container. But we can do `docker create -v //Users/project://project --name project-volume` and then `docker run --volumes-from project-volume`
