### ISSUE TITLE
overlay network driver fails to program iptables on network connect on master/1.11.0-dev/4ac59a1

### ISSUE THREAD

**Issue by vikstrous** [docker/docker#21912]
Our Jenkins just failed to install DTR with this error on docker master:

```
19:27:13 INFO[0024] Connecting to network: dtr-ol                
19:27:13 ERRO[0024] Couldn't attach phase2 container to d922a08966dc59184481cfbc6bbc38c22cf23c5f10a9ab0491760ee5083e3e07: Error response from daemon: subnet sandbox join failed for "10.0.0.0/24": failed to insert overlay hook in chain OUTPUT:  (iptables failed: iptables --wait -I OUTPUT -j DOCKER-OVERLAY: iptables v1.4.21: Couldn't load target `DOCKER-OVERLAY':No such file or directory
19:27:13 
19:27:13 Try `iptables -h' or 'iptables --help' for more information.
19:27:13  (exit status 2)) 
19:27:13 ERRO[0024] Error response from daemon: subnet sandbox join failed for "10.0.0.0/24": failed to insert overlay hook in chain OUTPUT:  (iptables failed: iptables --wait -I OUTPUT -j DOCKER-OVERLAY: iptables v1.4.21: Couldn't load target `DOCKER-OVERLAY':No such file or directory
19:27:13 
19:27:13 Try `iptables -h' or 'iptables --help' for more information.
19:27:13  (exit status 2)) 
19:27:13 time="2016-04-09T19:27:14Z" level=error msg="Phase 2 returned non-zero status: 1" 
```

**Output of `docker version`:**

```
19:24:17 + docker version
19:24:17 Client:
19:24:17  Version:      1.10.3
19:24:17  API version:  1.22
19:24:17  Go version:   go1.5.3
19:24:17  Git commit:   20f81dd
19:24:17  Built:        Thu Mar 10 15:54:52 2016
19:24:17  OS/Arch:      linux/amd64
19:24:17 
19:24:17 Server:
19:24:17  Version:      1.11.0-dev
19:24:17  API version:  1.24
19:24:17  Go version:   go1.5.3
19:24:17  Git commit:   4ac59a1
19:24:17  Built:        Sat Apr  9 17:43:42 2016
19:24:17  OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
19:24:17 + docker info
19:24:17 Containers: 0
19:24:17  Running: 0
19:24:17  Paused: 0
19:24:17  Stopped: 0
19:24:17 Images: 0
19:24:17 Server Version: 1.11.0-dev
19:24:17 Storage Driver: aufs
19:24:17  Root Dir: /var/lib/docker/aufs
19:24:17  Backing Filesystem: extfs
19:24:17  Dirs: 0
19:24:17  Dirperm1 Supported: false
19:24:17 Logging Driver: json-file
19:24:17 Plugins: 
19:24:17  Volume: local
19:24:17  Network: bridge null host
19:24:17 Kernel Version: 3.13.0-53-generic
19:24:17 Operating System: Ubuntu 14.04.2 LTS
19:24:17 OSType: linux
19:24:17 Architecture: x86_64
19:24:17 CPUs: 2
19:24:17 Total Memory: 7.305 GiB
19:24:17 Name: jenkins-dtr-integration-2516
19:24:17 ID: N3SJ:ITQA:2RXN:PAY2:YTYY:7B3V:DFU7:6GVO:ZSO6:J23I:ISD7:O3RU
19:24:17 Username: dockerbuildbot
19:24:17 Registry: https://index.docker.io/v1/
19:24:17 WARNING: No swap limit support
19:24:17 Labels:
19:24:17  provider=amazonec2
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
aws

**Steps to reproduce the issue:**
unknown

**Describe the results you received:**
see above

**Describe the results you expected:**
no error

**Additional information you deem important (e.g. issue happens only occasionally):**
It just happened for the first time now, I'll update this issue as I learn more about it.

Daemon logs:

```
[34mINFO[0m[0018] Loading containers: done.                    
[34mINFO[0m[0018] Daemon has completed initialization          
[34mINFO[0m[0018] Docker daemon                                 [34mcommit[0m=4ac59a1 [34mgraphdriver[0m=aufs [34mversion[0m=1.11.0-dev
[34mINFO[0m[0018] API listen on /var/run/docker.sock           
[34mINFO[0m[0018] API listen on [::]:2376                      
[34mINFO[0m[0021] 2016/04/09 19:26:42 [INFO] serf: EventMemberJoin: jenkins-dtr-integration-2516 172.17.0.1

[31mERRO[0m[0053] Handler for POST /v1.22/networks/d922a08966dc59184481cfbc6bbc38c22cf23c5f10a9ab0491760ee5083e3e07/connect returned error: subnet sandbox join failed for "10.0.0.0/24": failed to insert overlay hook in chain OUTPUT:  (iptables failed: iptables --wait -I OUTPUT -j DOCKER-OVERLAY: iptables v1.4.21: Couldn't load target `DOCKER-OVERLAY':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
 (exit status 2)) 
```

Update: I don't have a repro and I've see this bug exactly once :(

**Comment by aboch** [comment]
I have been trying to reproduce with 1.11.0-rc4 image. So far I did I was not able to hit the issue.
If possible to collect the debug level logs, that would help characterize the problem.

**Comment by vikstrous** [comment]
This jenkins machine is long gone and this is the only time I've ever seen this bug. I can't give you any more info than what's already here :(

**Comment by thaJeztah** [comment]
@vikstrous do you think we should close then?

**Comment by vikstrous** [comment]
I'll reopen if I see it again

**Comment by vikstrous** [comment]
I just got this again:
```
ERRO[0401] could not create global overlay chain:  (iptables failed: iptables --wait -N DOCKER-OVERLAY: iptables: Chain already exists.
 (exit status 1)) 
```

**Comment by vikstrous** [comment]
This time I did it on docker 1.10.

1. I installed UCP on machine 1. (I should have restarted it, but didn't)
2. I added a second UCP node (machine 2), restarted docker
3. I added a third UCP node (machine 3), restarted docker
4. I installed DTR on machine 2; it created an overlay network
5. I tried to add a second DTR node on machine 3
6. It failed because when after running a container on the overlay network, it started and DNS worked, but it failed to connect / ping. I reproduced the issue by just manually starting a container on the overlay network on machines 1 and 3 and neither could connect.
7. I restarted machine 1
8. I saw this log message on machine 1.

**Comment by vikstrous** [comment]
I can give access to anyone interested in debugging this to the 3 AWS instances I used for this. Ping me on Slack.

**Comment by aboch** [comment]
@vikstrous 
Regarding the new error you posted, 
```
ERRO[0401] could not create global overlay chain:  (iptables failed: iptables --wait -N DOCKER-OVERLAY: iptables: Chain already exists.
```
it should not cause the driver to fail, the error is not checked by the caller.
If the daemon failed to start, it must have been for another subsequent error.
Can you please check the logs. Thanks.

In the meanwhile I will push a patch to not bump into this error: A stale chain from a previous ungraceful shutdown of the daemon should be handled gracefully by overlay driver.

**Comment by vikstrous** [comment]
It did not cause the daemon to fail to start. Only overlay networks broke.

**Comment by aboch** [comment]
Thanks for confirming.

How did you determine overlay network driver broke ? You were not able to launch containers on the overlay network ?

**Comment by vikstrous** [comment]
After launching containers on the overlay network (on different machines), they were able to resolve each other's IP addresses, but were not able to communicate with each other.

**Comment by aboch** [comment]
Discussed offline with submitter and gathered some more information.
His setup has lately been very unstable, and connectivity issue across overlay network has been there for a while and cannot be imputed to the issue reported here.
We will meet to see if any requirement is missing in his environment.

Regarding this issue, I feel it is not a P1 given it tracks a yet non-reproducible error from an unstable environment and a second issue which is operationally harmless (just a misleading error print) for which a fix has been pushed to libnetwork.

I am going ahead then and remove the P1 flag.

**Comment by icecrime** [comment]
Thanks for the followup @aboch. I'll remove it from the milestone too.

**Comment by LK4D4** [comment]
@vikstrous @aboch still an issue? Can we close this?

**Comment by vikstrous** [comment]
I haven't seen this again in recent versions. I'll reopen if I see it again I guess.
