### ISSUE TITLE
mount hierarchy bug with tmpfs: tmpfs /tmp is mounted after -v /tmp/.X11

### ISSUE THREAD

**Issue by djtm** [docker/docker#21916]
**Issue:**
If you run an image with tmpfs and a -v mount, docker first mounts -v, then tmpfs, making the -v mount disappear.
`docker run -it --tmpfs /tmp:rw -v /tmp/.X11-unix:/tmp/.X11-unix alpine ls -a /tmp/`
only shows `. ..`
while
`docker run -it -v /tmp/.X11-unix:/tmp/.X11-unix alpine ls -a /tmp/`
shows `.   ..   .X11-unix`.

This makes it harder to use --read-only in production. It does not matter whether tmpfs is before or after the -v mount on the command line.

**Proposed Fix:**
mount according to directory hierarchy, also for tmpfs.

**Output of `docker version`:**
```
docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:59:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:59:07 2016
 OS/Arch:      linux/amd64
```

**Comment by j16sdiz** [comment]
Same if /tmp is a volume

**Comment by djtm** [comment]
I couldn't confirm the bug two -v mounts. Could you provide a `docker run` example please? What version do you use?

**Comment by rhatdan** [comment]
Yes host bind mounts should always happen last.
