### ISSUE TITLE
Can Docker DNS be used for  service discovery Now?

### ISSUE THREAD

**Issue by sqleejan** [docker/docker#21923]
I want to use Docker DNS for service discovery
eg: 
      1.docker run --name=web1 --net-alias=service-name -d webapp:1.0
      2.docker run --name=web2 --net-alias=service-name -d webapp:1.0

I want to use Dockcer DNS to provide long polling for changes in the backend ip list, which enables haproxy to efficiently detect changes and update the configuration for HAProxy in real-time

eg: docker run -d --name=ld -e backendweb=service-name -e staticport=80 myngnix:1.0

Can Docker DNS be used for  service discovery,as shown above

**Comment by sanimej** [comment]
@sqleejan Docker DNS doesn't provide a long polling service monitor kind of functionality. But in the upcoming 1.11 release Docker embedded DNS server will return multiple A records if the same alias (ie: service name) is configured for more than one container. Please see if you can make use of this to achieve what you want.

**Comment by thaJeztah** [comment]
Note that docker events can be used to detect network connect / disconnect; https://docs.docker.com/engine/reference/commandline/events/, and could be used to reconfigure HAProxy with, e.g. https://github.com/jwilder/docker-gen or https://hub.docker.com/r/jwilder/docker-register/

**Comment by sqleejan** [comment]
@thaJeztah @sanimej  LGTM

**Comment by thaJeztah** [comment]
Thanks @sqleejan, let me close this issue, because I think your question is answered, but feel free to continue the discussion :+1:

**Comment by sqleejan** [comment]
So,will the Docker  provide load-balance or service discovery Solution in Roadmap? I think the above solution make  schedule complicated

**Comment by thaJeztah** [comment]
@sqleejan I don't think load balancing will become a core functionality of docker "engine"; there's no one-size-fits-all solution for that. Possibly more suitable for Swarm. You may be interested in https://traefik.io, which is a very nice solution as well
