### ISSUE TITLE
Non-Interactive Sessions Swallows Input on Nano/Hyper-V Container

### ISSUE THREAD

**Issue by taylorb-microsoft** [docker/docker#21932]
Host:  Windows 10 
Runtime:  Hyper-V Container
Docker Cmd:  docker run nanoserver cmd

Expected:  Runs and exits the container immediately 
Actual:  Holds the console window until you force close it (ctrl-C doesn't work)

**Comment by vdemeester** [comment]
ping @jhowardmsft is this still an issue ?

**Comment by jhowardmsft** [comment]
Nope. Closing.
