### ISSUE TITLE
Docker image specification should be updated for content addressability

### ISSUE THREAD

**Issue by aaronlehmann** [docker/docker#21938]
The image spec at https://github.com/docker/docker/blob/3d13fddd2bc4d679f0eaa68b0be877e5a816ad53/image/spec/v1.md hasn't been updated for the content addressability changes that went into Docker 1.10. This spec also seems to contain some outdated fields like "image checksum". It shouldn't be very hard to bring this up to date. The changes in 1.10 are described in https://gist.github.com/aaronlehmann/b42a2eaf633fc949f93b#new-image-config.

cc @stevvooe @tonistiigi @dmcgowan

**Comment by vdemeester** [comment]
@aaronlehmann @thaJeztah still an issue ? :angel:

**Comment by aaronlehmann** [comment]
Was fixed by #22264.
