### ISSUE TITLE
.dockerignore in windows server throws "illegal UTF-8 encoding" and "illegal character NUL" error

### ISSUE THREAD

**Issue by powersplay** [docker/docker#21940]
**Output of `docker version`:**
```
PS C:\> docker version
Client:
 Version:      1.11.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   517c18f
 Built:        Mon Apr 11 14:41:04 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.11.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   517c18f
 Built:        Mon Apr 11 14:41:04 2016
 OS/Arch:      windows/amd64```

**Output of `docker info`:**
```
PS C:\> docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 8
Server Version: 1.11.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null
Kernel Version: 10.0 14316 (14316.1000.amd64fre.rs1_release.160402-2217)
Operating System: Windows Server 2016 Datacenter Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 4 GiB
Name: WIN-RV8IAMVBSFK
ID: 7IDZ:EJBX:O75H:PHI3:U2KH:DGEV:YJ4S:J4II:BNJI:MBRR:2K5H:CFQV
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 21
 System Time: 2016-04-11T11:57:50.5930709-07:00
 EventsListeners: 0
Username: powersplay
Registry: https://index.docker.io/v1/
Insecure registries:
 127.0.0.0/8```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
TP5 running in VirtualBox with current Master of Docker 1.11

**Steps to reproduce the issue:**
1. Move a working .dockerignore file from Linux to Windows
2.Attempt `docker build`
**Describe the results you received:**
```PS C:\hugo> docker build -t powersplay/testdockerignore .
1:1: illegal UTF-8 encoding
1:2: illegal UTF-8 encoding
1:4: illegal character NUL
1:6: illegal character NUL
1:8: illegal character NUL
1:10: illegal character NUL
1:12: illegal character NUL
1:14: illegal character NUL
1:1: illegal UTF-8 encoding
1:2: illegal UTF-8 encoding
1:4: illegal character NUL
1:6: illegal character NUL
1:8: illegal character NUL
1:10: illegal character NUL
1:12: illegal character NUL
1:14: illegal character NUL
1:1: illegal UTF-8 encoding
1:2: illegal UTF-8 encoding
1:4: illegal character NUL
1:6: illegal character NUL
1:8: illegal character NUL
1:10: illegal character NUL
1:12: illegal character NUL
1:14: illegal character NUL
1:1: illegal UTF-8 encoding
1:2: illegal UTF-8 encoding
1:4: illegal character NUL
1:6: illegal character NUL
1:8: illegal character NUL
1:10: illegal character NUL
1:12: illegal character NUL
1:14: illegal character NUL
1:1: illegal UTF-8 encoding
1:2: illegal UTF-8 encoding
1:4: illegal character NUL
1:6: illegal character NUL
1:8: illegal character NUL
1:10: illegal character NUL
1:12: illegal character NUL
1:14: illegal character NUL
1:1: illegal UTF-8 encoding
1:2: illegal UTF-8 encoding
1:4: illegal character NUL
1:6: illegal character NUL
1:8: illegal character NUL
1:10: illegal character NUL
1:12: illegal character NUL
1:14: illegal character NUL```
**Describe the results you expected:**


**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
can you attach the .dockerignore file in case it's needed for debugging? Or does it contain sensitive information?

**Comment by powersplay** [comment]
Here it is...   Sorry I had to label it as dockerignore.txt
[dockerignore.txt](https://github.com/docker/docker/files/213795/dockerignore.txt)

**Comment by thaJeztah** [comment]
LOL, that's a large file, :joy:

/cc @jhowardmsft @jstarks

**Comment by yongtang** [comment]
Here is the content of the .dockerignore:
```
0000000: fffe 7400 6500 7300 7400 0d00 0a00       ..t.e.s.t.....
```
It looks like this is a Windows UTF16 text file (See the BOM 0xfffe at the beginning). I haven't check how Docker handles the dockerignore though I would assume Docker is expecting an ASCII or UTF8 file (most likely case in Linux).

**Comment by jstarks** [comment]
Was this produced via > redirection in PowerShell? E.g.

    echo test > .dockerignore

PowerShell unfortunately outputs UTF-16 by default. I think you can use 

    echo test | Out-File -Encoding UTF8 .dockerignore

That will still output a UTF8 BOM. I don't know if Docker can handle that.

PowerShell text handling is kind of a problem.

**Comment by jhowardmsft** [comment]
Or do this: `[System.IO.File]::WriteAllText('.dockerignore', 'some test', (New-Object System.Text.UTF8Encoding($False)))`. Or use `cmd` ;)

**Comment by powersplay** [comment]
Thanks.   Just confirmed that the .dockerignore file was produced with powershell.   I tested one that originated with linux and it works fine.
