### ISSUE TITLE
docker inspect gave default log options when the option is emtpy 

### ISSUE THREAD

**Issue by frostynova** [docker/docker#21956]
The code in https://github.com/docker/docker/blob/master/daemon/inspect.go#L117 show `docker inspect` will override the log config options with default option when you not specify it. But actually docker container still use the empty option

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:39:25 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:39:25 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 12
 Running: 10
 Paused: 0
 Stopped: 2
Images: 27
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-253:0-33760998-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/docker/data
 Metadata file: /dev/docker/metadata
 Data Space Used: 3.025 GB
 Data Space Total: 20 GB
 Data Space Available: 16.97 GB
 Metadata Space Used: 7.463 MB
 Metadata Space Total: 1.053 GB
 Metadata Space Available: 1.045 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: syslog
Plugins:
 Volume: local
 Network: host bridge null calico
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.797 GiB
Name: node1
ID: PLUV:C6FS:SIKS:4EAA:TZZ7:6ZK6:3CLB:A2G7:WQMN:5KR5:3W35:VPF7
Debug mode (server): true
 File Descriptors: 107
 Goroutines: 1184
 System Time: 2016-04-12T08:01:14.366475026Z
 EventsListeners: 1
 Init SHA1: eb0f466d1d125be1d5800e262e0758e1b54ed69a
 Init Path: /usr/libexec/docker/dockerinit
 Docker Root Dir: /data/docker
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Cluster store: etcd://192.168.77.21:4001
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Vagrant with VirtualBox

**Steps to reproduce the issue:**
1. start docker daemon with default log options: --log-driver=syslog --log-opt syslog-address=tcp://127.0.0.1:514
2. start a container only with log driver but empty option: --log-driver=syslog
3. docker inspect the container show it use the daemon log-opt

**Describe the results you received:**
In fact the container use the empty log option not as inspect shows

**Describe the results you expected:**
inspect also show empty option

**Comment by yongtang** [comment]
I can take a look at this issue. #dibs

**Comment by yongtang** [comment]
@frostynova I just create a pull request #21961. Let me know if there are any issues.

**Comment by frostynova** [comment]
@yongtang LGTM
