### ISSUE TITLE
 --dns and --net=host should not be mutually exclusive

### ISSUE THREAD

**Issue by ketzacoatl** [docker/docker#21976]
I understand that docker will attempt to do what it thinks is best with my container's `/etc/resolv.conf`, such as when in --net=host mode and using the host's `resolv.conf`, or by replacing `127.0.0.1` when that is seen. I also understand that `--dns` is a wonderful way to be explicitly sure about what's in your container's `resolv.conf`:

```
# docker run -it --dns=1.2.3.4 ubuntu cat /etc/resolv.conf                             
search ...
nameserver 1.2.3.4
```

However, I would like to run a container with `--net=host`, and I want to tell the container what it's upstream DNS servers are, so I go to use the `--dns` parameter with `docker run`/etc, but docker errors out:

```
# docker run --dns=127.0.0.1 --net=host -it ubuntu bash
WARNING: Localhost DNS setting (--dns=127.0.0.1) may fail in containers.
Error response from daemon: Conflicting options: --dns and the network mode (--net)
```

Why does docker get confused about which detail is more important, but then goes on to block me from resolving its confusion. Or am I overlooking something painfully obvious?

To add to the insult from docker, it'll happily accept `DOCKER_OPTS="--dns=127.0.0.1"` provided to the daemon, and even use that as expected when in `--net=host` mode. 

Here is an example with an empty `DOCKER_OPTS`:
```
$ docker run -it --net=host ubuntu cat /etc/resolv.conf                                
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
search ...

nameserver 8.8.8.8
nameserver 8.8.4.4
```

Versus this, when `DOCKER_OPTS` has `--dns=127.0.0.1`:

```
$ docker run -it --net=host ubuntu cat /etc/resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 127.0.0.1
search ...
```

From my perspective, blocking users from using `--dns` with `--net=host` seems arbitrary and wrong, do others agree?

**Comment by bboreham** [comment]
Yes, I agree.  See https://github.com/docker/docker/issues/10384 for some previous discussion.

**Comment by ketzacoatl** [comment]
IDK how I missed that ticket in my searching for dups. Thanks for the reference, I'll read up on that history.

**Comment by ketzacoatl** [comment]
OK, reading that over, I understand why this was put in place originally, but it seems overwhelmingly clear that the limitation is out-dated and no longer helpful, but actually hurtful.

Given that  `--net=host` works _fine_ when `--dns=...` is set on the docker _daemon_, `--dns=...` should work on the command line, and the lack of consistency if a bug. I believe docker should be updatd so `--dns=...` works with `--net=host` on the cli.

**Comment by tianon** [comment]
I think https://github.com/docker/docker/issues/12076 and https://github.com/docker/docker/pull/20177 are also relevant here (allowing `--hostname` with `--net=host`, which is pretty similar)

**Comment by ketzacoatl** [comment]
@tianon, OK, should I rename this ticket to "allow `--dns` with `--net=host`" ?

**Comment by ketzacoatl** [comment]
I updated the title, as this is no longer a question, and I think there are plenty of us who realize and agree that the current setup blocks valid use of the two options together.

**Comment by yongtang** [comment]
I take a look at the container_operations.go in Docker 1.11. It seems `--dns`, `--dns-search`, and `--dns-opt` are all related to `/etc/resolv.conf`. If `--net=host` is passed, then the original `/etc/resolv.conf`will be used so none of the `--dns`, `--dns-search`, and `--dns-opt` will be in effect.

This is the case for both `docker run` and `docker daemon` in 1.11.

If we want `--dns` and `--net=host` to be used together, then `/etc/resolv.conf` will change. Obviously, we could also allow `--net=host` to work with `--dns-search`, and `--dns-opt`. And this could be applied to options in `docker daemon`, too.

I can help create a pull request though this is quite a big change in behavior so I am wondering if any docker maintainers could provide some insight on this issue:
Do we want to allow `--net=host` and `--dns` to work together?
Should we allow `--net=host` to work with  `--dns-search` and `--dns-opt` as well?
If a user provides `--dns`, `--dns-search`, or `--dns-opt` in daemon options, will passing `--net=host` change the `/etc/resolv.conf` too?

**Comment by ketzacoatl** [comment]
Hi @yongtang, thanks for poking around here and the offer to help create a PR. It seems like this should actually be a very simple PR.

I do not believe this is a big change in behavior, because, quite simply, `--net=host` works fine when `--dns=...` is set via the docker daemon opts (like in `/etc/default/docker`). `--dns=...` should work on the command line just the same, there is no desire to make massive changes to docker's behavior.. the only desire is to ensure the cli can do what is already possible when configured via `/etc/default/docker`.

**Comment by yongtang** [comment]
Thanks @ketzacoatl. I didn't check earlier version of the Docker though in 1.11, if `--dns=...` is passed in `/etc/default/docker`, running `docker run --net=host ...` will not change the name server in `/etc/resolv.conf`.

I don't know enough history of the networking model in docker so would like to get some confirmation.

A PR (#22408) has been created and hopefully it opens further discussions about this issue.

**Comment by ketzacoatl** [comment]
That's fantastic! Thanks @yongtang!

**Comment by ketzacoatl** [comment]
Ping @tianon / @thaJeztah - do you have any feedback on this? Thanks!

**Comment by thaJeztah** [comment]
@ketzacoatl not yet, but I pinged some people on the pull request, to ask what they think

**Comment by ketzacoatl** [comment]
Thanks, I appreciate it!

**Comment by ketzacoatl** [comment]
@thaJeztah any input on this? It seems silly that we can use `--dns` through the config file, but not on the command line..

**Comment by ketzacoatl** [comment]
@yongtang, super gratitude for carrying this through on the code side of things!
