### ISSUE TITLE
UX proposal: refer to "docker login" on "authentication required"

### ISSUE THREAD

**Issue by majewsky** [docker/docker#21985]
I just pushed my first image to the Docker Hub. I tried a simple `docker tag && docker push`, and it failed:

```bash
$ docker push majewsky/registry:2.3.0.p2.1
The push refers to a repository [docker.io/majewsky/registry]
8c0e53384bda: Preparing
405c510929bc: Preparing
a55407ed0e63: Preparing
464e324f99b9: Preparing
5f70bf18a086: Preparing
c12ecfd4861d: Waiting
unauthorized: authentication required
```

This message is not particularly helpful. A bit of googling revealed that I need to `docker login` first, but it would be nicer if the error message included that information directly. In fact, it would be even nicerer if it did the `docker login` automatically at this point and then restarted the push operation after successful authentication.

**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Sat Mar 12 19:18:57 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Sat Mar 12 19:18:57 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 14
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-8:2-136561-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 552.3 MB
 Data Space Total: 107.4 GB
 Data Space Available: 3.703 GB
 Metadata Space Used: 1.135 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.121 (2016-03-26)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 4.4.5-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.833 GiB
Name: rupert
ID: DQMG:AXEM:E2AQ:2COJ:NJJE:B2WH:F55A:YKVC:6P2I:M2AE:2GOW:EJWL
Http Proxy: http://proxy.wdf.sap.corp:8080
No Proxy: localhost,sap,corp,127.0.0.1
Username: majewsky
Registry: https://index.docker.io/v1/
```

**Comment by cristina-grosu** [comment]
I have the same issue. After successfully logging in with docker login, I am trying to push an image to an existing registry and i get the following error message:

'unauthorized: authentication required'

**Comment by majewsky** [comment]
@cristina-grosu That's not the same issue. After `docker login`, `docker push` went through. I'm criticizing the UX of `docker push` *before* `docker login`.

**Comment by thaJeztah** [comment]
@majewsky thanks for the suggestion. Looks like this message [originates from the "distribution"](https://github.com/docker/docker/blob/3d13fddd2bc4d679f0eaa68b0be877e5a816ad53/vendor/src/github.com/docker/distribution/registry/api/errcode/register.go#L40) package, so it either needs to be improved there, or perhaps translated to a more "friendly" message in the client

@aaronlehmann wdyt?

**Comment by aaronlehmann** [comment]
@thaJeztah: I actually received a similar request a few weeks ago and was working on a change to mention `docker login` in the error message. However, it occurred to me that `docker pull` without proper credentials is actually supposed to prompt for credentials. This is currently broken - see https://github.com/docker/docker/issues/21054, particularly https://github.com/docker/docker/issues/21054#issuecomment-202652272. So I think we should fix this prompt instead of adding text that mentions `docker login`.

**Comment by thaJeztah** [comment]
@aaronlehmann oh, you're right @majewsky I'll close this issue in favor of #21054, which is tracking this

**Comment by runcom** [comment]
@aaronlehmann do you have any plan on restoring the old "prompt for login" feature (#21054)? I can work it out

**Comment by aaronlehmann** [comment]
@runcom: I'm not actively working on it. It would be great if you are interested in looking into it.

**Comment by runcom** [comment]
I will, I'll make a PR soon
