### ISSUE TITLE
docker php curl reads from hosts /etc/hosts file

### ISSUE THREAD

**Issue by masterod13** [docker/docker#21986]
Description of problem:
i have followed the following tutorial http://fabiorehm.com/blog/2014/09/11/running-gui-apps-with-docker/   in order to run firefox through the container.
The only difference is that we use centos 6.6  to create the image.
So. I  have created a docker image based on centos 6.6 with lamp stack installed. 
In order to create a container i need to docker run  with  --net=host command.

Lets assume that exists a website  example.com with ip  174.17.74.124 developed in php.

The container's vhost.conf is configured  like this:

```
<VirtualHost *:80>  
     ServerName  example.com	
     ServerAlias *.example.com
     DocumentRoot /var/www/html/example.com/
</VirtualHost>
```
And the containers /etc/hosts
```
127.0.0.1   example.com
```
so the container knows that the ip of example.com is 127.0.0.1
 
The hosts /etc/hosts  has commended that line, 

```
#127.0.0.1   example.com
```
so the host  knows that the ip of example.com is 174.17.74.124

I then try to navigate to example.com through  the containers firefox, and the  php code of 127.0.0.1 is executed correctly.

I then try to navigate to example.com through  host's  firefox, and the  php code of  74.17.74.124
 is executed correctly.

The problem occurs when i write a php script that is executed from the container and tries  to curl  example.com.

If so, example.com is resolved according to host's /etc/hosts and not the containers /etc/hosts.

I understand that php's curl makes some dns queries, but shouldn't  these resolve according to container's /etc/hosts? 
 
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 14
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /media/it/More_Space/docker/aufs
 Backing Filesystem: extfs
 Dirs: 33
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-83-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.684 GiB
Name: it-HP-Pro-3500-Series
ID: 7DLR:EEAD:NY7J:TQZX:BW6H:OH7P:NMMD:CYMZ:DZME:SWYL:RP4E:VQG7
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. 
2. 
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
This isn't a bug in docker, but the way cURL and PHP using cURL works; see http://stackoverflow.com/questions/9276114/php-curl-doesnt-see-the-etc-hosts-file and http://stackoverflow.com/a/10218482/1811501
