### ISSUE TITLE
Docker run 是否可以映射指定的端口范围

### ISSUE THREAD

**Issue by Yunlong2cn** [docker/docker#21995]
如题，目前的需求是希望能把宿主机的 5000-8000映射到某个容器的5000-8000端口，请问这个有实现方式么？

**Comment by coolljt0725** [comment]
使用docker run -p 5000-8000:5000-8000就可以，这个是你想要的吗？
在github上提问最好用英文哈~

**Comment by Yunlong2cn** [comment]
So easy ? Let me to cry....

**Comment by coolljt0725** [comment]
so I'm going to close this since it's not an issues :)

**Comment by thaJeztah** [comment]
So happy we have maintainers from all around the world now; no need to use Google Translate :smile:

**Comment by Yunlong2cn** [comment]
thanks all firend to help me , the IT groups need this kinds of "精神", ofcause, it is so.

**Comment by elesos** [comment]
Nice post

**Comment by Daopr** [comment]
nice post

**Comment by ztmdsbt** [comment]
nice post
