### ISSUE TITLE
Proposal: add aliyun logdriver

### ISSUE THREAD

**Issue by panyufeng920** [docker/docker#21992]
**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
We try to go towards a plugin-system for logging drivers, because we cannot cover all possible options, but I'll keep this issue open if someone wants to work on implementing it as a plugin once that is in place. For reference, see https://github.com/docker/docker/issues/18604

**Comment by panyufeng920** [comment]
thx，I will try to implement it

**Comment by LK4D4** [comment]
I'm closing this, as we don't want new built-in logging drivers. #28403 is way to go.
