### ISSUE TITLE
Problem with install docker:

### ISSUE THREAD

**Issue by dekros987** [docker/docker#21997]
https://docs.docker.com/engine/installation/linux/debian/
i made all step from this tutorial
and when i try:
 sudo apt-get install docker-engine (on root)
i have this error:
[...] docker-engine
E: Sub-process /usr/bin/dpkg returned an error code (1)
when i try:
sudo service docker start
Job for docker.service failed. See 'systemctl status docker.service' and 'journalctl -xn' for details.
i have debian 8 Jessie
2.6.32-042stab111.12

**Comment by thaJeztah** [comment]
Is `2.6.32-042stab111.12` your kernel version?

**Comment by dekros987** [comment]
is uname -r output

**Comment by thaJeztah** [comment]
In that case, make sure to run an up to date kernel; docker requires kernel 3.10 as a minimum; https://docs.docker.com/engine/installation/linux/debian/#prerequisites

**Comment by dekros987** [comment]
i run this cmd:apt-get install linux-image-3.16.0-4-amd64
but uname -r output is still 2.6.32-042stab111.12

**Comment by thaJeztah** [comment]
Are you running bare-metal, on a cloud provider?

**Comment by programmerq** [comment]
This kernel version looks like an openvz kernel. Is this an OpenVZ VPS?

If so, it is unlikely that you'll be able to switch what kernel you are running. A VPS host that does full virtualization should be able to give you a VPS that boots a kernel that you control.
