### ISSUE TITLE
Dockerfile parsing issues

### ISSUE THREAD

**Issue by xificurC** [docker/docker#21999]
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 346
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /home/UX/pnagyux/docker/aufs
 Backing Filesystem: extfs
 Dirs: 338
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-85-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.6 GiB
Name: pnagyubupc
ID: 6ISS:ZOS6:DTPJ:7Z3M:QP73:FHLH:B452:XHQW:GCBP:UKHG:RAK3:SGEB
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. create Dockerfile
```Dockerfile
FROM ubuntu:14.04.4

RUN groupadd -g 10001 tester \
    && useradd -d /home/tester -u 10001 -g 10001 -G sudo -m -s /bin/bash tester # \

USER tester
```
2. `docker build -t parse-issues .`
3. `docker run --rm -it parse-issues bash`

**Describe the results you received:**
`id` shows root

**Describe the results you expected:**
`id` shows tester

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by duglin** [comment]
Dockerfile processing is a bit odd.
Comments must start at the first column - so  ... # \  reads the next line as a continuation.
Then the blank line is treated as a continuation too - go figure  :-)
Can you verify that "USER tester" is passed to your "sudo -m -s /bin/bash tester" cmd?

**Comment by xificurC** [comment]
Wow, ok, that is a lot of unexpected, and mostly counterintuitive behavior for me. I would even argue this should be changed, I don't know of any mainstream language that wouldn't allow inline comments. But I guess that change is out of the question as it would be a breaking one.

Thank you for your quick response!
