### ISSUE TITLE
Dockerfile.s390x: notary server does not compile

### ISSUE THREAD

**Issue by michael-holzheu** [docker/docker#22007]
Building docker on s390x with Dockerfile.s390x currently fails when compiling notary-server with error messages like "cannot find package "github.com/Sirupsen/logrus/hooks/bugsnag"".

See also: (https://jenkins.dockerproject.org/job/Docker%20Master%20%28power,%20z%29%20Binaries/label=z/1315/consoleFull)

**Steps to reproduce the issue:**
1. git clone https://github.com/docker/docker.git
2. cd docker
3. docker build --rm --force-rm -t docker:build -f Dockerfile.s390x .

```
Step 16 : RUN set -x && export GO15VENDOREXPERIMENT=1 && export GOPATH="$(mktemp -d)" && git clone https://github.com/docker/notary.git  "$GOPATH/src/github.com/docker/notary" && (cd "$GOPATH/src/github.com/docker/notary" && git checkout -q "$NOTARY_VERSION") && GOPATH="$GOPATH/src/github.com/docker/notary/vendor:$GOPATH" go build -o /usr/local/bin/notary-server github.com/docker/notary/cmd/notary-server && rm -rf "$GOPATH"
---> Running in 220ac8c8543f
+ export GO15VENDOREXPERIMENT=1
+ mktemp -d
+ export GOPATH=/tmp/tmp.MmfSLEvL7R
+ git clone https://github.com/docker/notary.git /tmp/tmp.MmfSLEvL7R/src/github.com/docker/notary
Cloning into '/tmp/tmp.MmfSLEvL7R/src/github.com/docker/notary'...
+ cd /tmp/tmp.MmfSLEvL7R/src/github.com/docker/notary
+ git checkout -q docker-v1.11-3
+ GOPATH=/tmp/tmp.43uItm940a/src/github.com/docker/notary/vendor:/tmp/tmp.43uItm940a go build -o /usr/local/bin/notary-server github.com/docker/notary/cmd/notary-server                                                                                                                              
tmp/tmp.43uItm940a/src/github.com/docker/notary/cmd/notary-server/config.go:9:2: cannot find package "github.com/Sirupsen/logrus" in any of:       

tmp/tmp.43uItm940a/src/github.com/docker/notary/utils/configuration.go:12:2: cannot find package "github.com/Sirupsen/logrus/hooks/bugsnag" in any of:                                                                                                                                                

tmp/tmp.43uItm940a/src/github.com/docker/notary/tuf/data/keys.go:16:2: cannot find package "github.com/agl/ed25519" in any of:                     
```
The reason seems to be that since version "docker-v1.11-1" the notary git repository contains a vendor directory that contains all dependencies.

The following commit has done this:

```
commit 51dc1747e4ab5738039fc21f8a082cba5a6e4f78
Author: Ying Li <ying.li@docker.com>
Date:   Tue Mar 8 11:28:04 2016 -0800

    Move the godeps workspace to the vendor directory to be compliant with Go 1.6
    
    Signed-off-by: Ying Li <ying.li@docker.com>
```

Since the vendor sources are directly under "vendors" and not under "vendors/src" go build does not find them.

We use gcc 5.3 in the image:
```
# go version  
go version go1.4.2 gccgo (GCC) 5.3.0 linux/s390x
```

The following workaround patch that adds a "src" softlink solves the problem:

```
diff --git a/Dockerfile.s390x b/Dockerfile.s390x
index 4edd40e..c678968 100644
--- a/Dockerfile.s390x
+++ b/Dockerfile.s390x
@@ -113,7 +113,7 @@ RUN set -x \
        && export GO15VENDOREXPERIMENT=1 \
        && export GOPATH="$(mktemp -d)" \
        && git clone https://github.com/docker/notary.git "$GOPATH/src/github.com/docker/notary" \
-       && (cd "$GOPATH/src/github.com/docker/notary" && git checkout -q "$NOTARY_VERSION") \
+       && (cd "$GOPATH/src/github.com/docker/notary" && git checkout -q "$NOTARY_VERSION" && ln -s . vendor/src) \
        && GOPATH="$GOPATH/src/github.com/docker/notary/vendor:$GOPATH" \
                go build -o /usr/local/bin/notary-server github.com/docker/notary/cmd/notary-server \
        && rm -rf "$GOPATH"
```
But I assume this can't be the final solution.

Please advise how to correctly fix this problem.

**Comment by brahmaroutu** [comment]
ping @cyli @duglin

**Comment by cyli** [comment]
cc @docker/security-team

**Comment by endophage** [comment]
Not a solution but a few things that jump out and comments:
- As of docker 1.10 (and in experimental from 1.9), notary uses the crypto.Signer interface, it was necessary to add Yubikey support, introduced in go 1.5 so we wouldn't expect it t ever build with go 1.4. I'm not sure how this was working before.
- The structure of the `vendor` directory is correct for go's native vendoring, it should not contain a `src` directory unless one's imports are in the format `import "src/my_pacakge"`. Also only supported from go 1.5 onwards (1.5 requiring the `GO15VENDOREXPERIMENT` env var and 1.6 onwards detecting the vendor dir by default).

**Comment by michael-holzheu** [comment]
> The structure of the vendor directory is correct for go's native vendoring,
> it should not contain a src directory unless one's imports are in the format import "src/my_pacakge".
> Also only supported from go 1.5 onwards (1.5 requiring the GO15VENDOREXPERIMENT
> env var and 1.6 onwards detecting the vendor dir by default).

Does this mean that gcc 5.3 is no longer supported by notary?
```
# go version  
go version go1.4.2 gccgo (GCC) 5.3.0 linux/s390x
```

**Comment by cyli** [comment]
> Does this mean that gcc 5.3 is no longer supported by notary?

Notary does work on 1.4, but the Yubikey functionality does rely on interfaces that are only on 1.5+.

In fact, if you don't plug a Yubikey in at all, Notary with pkcs11 support still seems to work, but probably we should disable it for gccgo, if gccgo only supports the 1.4 go standard library.

**Comment by michael-holzheu** [comment]
> In fact, if you don't plug a Yubikey in at all, Notary with pkcs11 support still seems to work, but
> probably we should disable it for gccgo, if gccgo only supports the 1.4 go standard library.

Sorry, I am not very familiar with notary. How can we disable Yubikey?
Will you do that?

**Comment by cyli** [comment]
@michael-holzheu:  Apologies, the Docker client uses [Notary](https://github.com/docker/notary) as a library to do content trust.  One of the features Notary (and hence Docker client) supports is using Yubikeys to sign.  I can definitely disable it by removing the `pkcs11` tag from `Dockerfile.s390x`.

That doesn't address the original point about `GOPATH` though.  I have a couple questions (sorry I'm not familiar at all with how the s390 is used - I am seeing a 404 from the jenkins.dockerproject.org link above):

- Are the docker daemon and the docker client both built for the s390?  Or just one or the other?  Just asking because content trust checking happens only on the client, which may simplify some things.

- Are integration tests run on the s390, particularly the content trust tests?  If not, then Notary Server is not needed at all for the Dockerfile.

I otherwise don't know of a way to build on go1.4 other than (1) this symlink solution, or (2) for Notary to not support 1.5+ type vendoring.  :|

**Comment by michael-holzheu** [comment]
@cyli : Thanks for the explanation!

> Are the docker daemon and the docker client both built for the s390? Or just one or the other?

Yes both are built. In principle s390 is not different to other platforms like x86, power, or arm.

> Are integration tests run on the s390, particularly the content trust tests?

The integration tests run on s390. Also the content trust tests (DockerTrustSuite).

> If not, then Notary Server is not needed at all for the Dockerfile.

I already discussed with Srini Brahmaroutu (@brahmaroutu) to remove notary from "Dockerfile.s390x". But since the s390 (Mainframe) customers are very focused on security I assume that we want to have this.

> I otherwise don't know of a way to build on go1.4 other than (1) this symlink solution, or (2) for
> Notary to not support 1.5+ type vendoring. :| 

I assume (1) is probably easier ;-), I have to discuss this with Srini.
