### ISSUE TITLE
Docker create doesn't work with full image id's, but does with partial

### ISSUE THREAD

**Issue by conslo** [docker/docker#22012]
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6
 Git commit:   20f81dd
 Built:        Mon, 04 Apr 2016 16:27:28 +1200
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6
 Git commit:   20f81dd
 Built:        Mon, 04 Apr 2016 16:27:28 +1200
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 10
Server Version: 1.10.3
Storage Driver: zfs
 Zpool: docker
 Zpool Health: ONLINE
 Parent Dataset: docker/docker
 Space Used By Parent: 1143891456
 Space Available: 102786927648
 Parent Quota: no
 Compression: lz4
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-15-generic
Operating System: Ubuntu 16.04
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.42 GiB
Name: ip-10-2-3-36
ID: QNUV:72CF:XGZA:Y2MT:SQ5B:IE7O:HB7J:MOS2:AFNH:6LME:G7EF:6XCL
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
* On AWS, client+server on the same machine

**Steps to reproduce the issue:**
1. build an image with `docker build -q .`
2. use the image-id from step one in `docker create ${IMAGEID}` (you have to trim "sha256:" which is confusing, but that's seperate)
3. watch it fail
4. use the image-id from step one, but with a *single* character removed from the end
5. watch it succeed
6. profit

**Describe the results you received:**
```shell
$ docker create ...e6fc # fails
Invalid repository name (...e6fc), cannot specify 64-byte hexadecimal strings
$ docker create ...e6f # succeeds
...591a
$
```

**Describe the results you expected:**
If partial ID's are accepted, I don't understand why full ID's aren't.

**Additional information you deem important (e.g. issue happens only occasionally):**
Relatively easy to work around, but having a random "trim one character" piece of code seems... pretty silly (i.e.: `${IMAGEID::-1}`).

**Comment by thaJeztah** [comment]
Looks like a duplicate of https://github.com/docker/docker/issues/20972, which is fixed in Docker 1.11 through https://github.com/docker/docker/pull/21002

**Comment by conslo** [comment]
wow, how did I not find that. Ok, thanks!

**Comment by thaJeztah** [comment]
GitHub search can be really bad sometimes, I just knew there was an issue, and how to find it :-)

**Comment by conslo** [comment]
suppose it's a consequence of being so popular (1400 issues makes me dizzy)
