### ISSUE TITLE
Don't show containerd connection closing as error

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#22010]
When the daemon shuts down, an error message is shown that is "expected" but probably redundant

To reproduce;

- manually start the docker daemon in the foreground; `docker daemon -D`
- after the daemon has finished starting, press `ctrl-c` to stop

This error is shown:

    ERRO[0117] failed to receive event from containerd: rpc error: code = 13 desc = "transport is closing"`

Docker version:

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:13:28 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:13:28 2016
 OS/Arch:      linux/amd64
```

**Comment by WeiZhang555** [comment]
Hi @thaJeztah , I pushed an PR to do this, hope it will help :smile:
