### ISSUE TITLE
Docker reports the last image that uses a sha rather than the originating image.

### ISSUE THREAD

**Issue by envygeeks** [docker/docker#22014]
# Docker Version

```
Client:
 Version:      1.11.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   bb9b173
 Built:        Wed Apr  6 10:20:07 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.11.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   bb9b173
 Built:        Wed Apr  6 10:20:07 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

---
# Docker Info

```
docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 1.11.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 3
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-18-generic
Operating System: Ubuntu 16.04
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.639 GiB
Name: laptop
ID: XIJZ:ZZGW:KKSE:2LIH:P5DB:SYGX:6IYF:5ZRI:EM7U:7CDM:WLTD:6QEE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: envygeeks
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure registries:
 127.0.0.0/8
```

---

When buillding and pushing an image (with or without the Docker Remote API) Docker reports the last image that uses a given SHA for a layer rather than the originating image.  For example, we have `envygeeks/prosody` and `envygeeks/alpine`, and `envygeeks/prosody` uses `envygeeks/alpine`, however, when we build and push `jekyll/jekyll` it reports that `envygeeks/alpine` image layers come from `envygeeks/prosody` because it was built **after** `envygeeks/alpine:latest`.

It would be nice if layers could be reported from their originator, not the last image that used it.

**Comment by HackToday** [comment]
Not quite understand the description here, could you show your build and push `jekyll/jekyll` result ?

**Comment by thaJeztah** [comment]
closing because this issue is quite old now, but let us know if you're still having this, and can provide a full example
