### ISSUE TITLE
Dockerhub: impossible to reach support.

### ISSUE THREAD

**Issue by xplicit** [docker/docker#22024]
This is not a docker issue, but I could not find a ways how to send it to dockerhub support.

I tried to create new login on dockerhub (login name: xplicit), but the registration mail with link did not send to me. I tried to login with login/password without activation, but could not do it. Then I try to get my account to work, but have not success again. What I did:

1. Tried to register again with same login/password. I've got a message: could not register, username is taken.
2. Tried to click on button "Cannot login" and then "Forget password". I've got a message "The email has been sent", but did not receive mail again.
3. Tried to click "Support" button. https://support.docker.com/. Support requires me to log in, what is actually is issue.
4. Tried to click on "Forums" https://forums.docker.com/ and post and issue there. Cannot do it, becase forums requires log in.
5. Tried to post a message on google grooups. https://groups.google.com/forum/#!forum/docker-user. Could not do it because it looks that the group is closed and I cannot create new threads or anwser to existing threads.
6. Tried to click on IRC https://botbot.me/freenode/docker/ Looks like it's a read only mirror and I could not find a way how to post a question into channel.

So I gave up and don't know how to reach support. To do it I must login, but I cannot login and this is an issue why I want talk with support. Circular dependency.

**Comment by thaJeztah** [comment]
Hi @xplicit, sorry to hear you're running into this; let me try to contact the support team to see if they can find what's the cause here. Just the obvious; have you checked your spam box?

> Tried to click on IRC https://botbot.me/freenode/docker/

That's correct; the botbot.me site is the "read-only" logs of the IRC channel, but here's our "IRC getting started" guide; https://docs.docker.com/opensource/get-help/#irc-quickstart. I'm not sure the Docker Hub support team is on there though (that channel is for the open source projects, not for Docker Hub, which is a separate team, run by Docker, Inc., not the open source maintainers)

**Comment by xplicit** [comment]
@thaJeztah Yes, I checked spam box, there are no letters here.

**Comment by fauzanariffin** [comment]
hi @xplicit I have checked your account and it seems that the email you provided does not exist.
Can you please email support[at]docker.com?

**Comment by xplicit** [comment]
@fauzanariffin I've just sent an email from my registration email to support.

**Comment by xplicit** [comment]
@fauzanariffin Thank you, my issue is resolved, it would be great if users who can not login to dockerhub will be able to contact to support too.

**Comment by thaJeztah** [comment]
Thanks for following up, @fauzanariffin, and good to hear it's resolved!

**Comment by jakirkham** [comment]
Was recently having trouble contact support as well. Had used `support[at]docker.com`, but it's been quiet for two days (excepting some bot receiving the issue). Is there a better way to get in contact with support?

**Comment by lcharette** [comment]
FYI, for anyone ending up here from Google, looks like the support can now be reached using this form : https://hub.docker.com/support/contact/
