### ISSUE TITLE
[doc] `docker cp` gives surprising result with tmpfs

### ISSUE THREAD

**Issue by AkihiroSuda** [docker/docker#22020]
When `tmpfs` is mounted on a container, `docker cp` copies the content of the underlying directory rather than the content of the `tmpfs`.

I'm not sure this is expected result or not.
But even if this is expected result, I think it is worth explictly mentioning this on the documentation.

**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Thu Apr 14 05:05:19 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Thu Apr 14 05:05:19 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**
```
Containers: 58
 Running: 1
 Paused: 0
 Stopped: 57
Images: 294
Server Version: 1.11.0
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-30-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.796 GiB
Name: ip-172-31-8-43
ID: 5HJM:SQPO:3NEM:ZYX7:3LME:WIHB:E3BN:RNMZ:6K4F:JCQ6:UY2Z:CR26
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 17
 Goroutines: 43
 System Time: 2016-04-14T05:11:22.886582661Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS (not related to this issue)

**Steps to reproduce the issue:**
On Terminal 1:
```
host$ (cd DOCKER_SRC_DIR; make shell)
root@78e5073cf591:/go/src/github.com/docker/docker# ls /tmp
root@78e5073cf591:/go/src/github.com/docker/docker# echo foo > /tmp/foo.txt
root@78e5073cf591:/go/src/github.com/docker/docker# ls /tmp
foo.txt
```

On Terminal 2:
```
host$ docker cp 78e5:/tmp xtmp
host$ ls xtmp
pip_build_root/  tmp.KrRLOzisMN/  tmp.bRFDLAOQtb/
```

**Describe the results you received:**
`pip_build_root/  tmp.KrRLOzisMN/  tmp.bRFDLAOQtb/`

**Describe the results you expected:**
`foo.txt`

**Additional information you deem important (e.g. issue happens only occasionally):**
- `hack/dind` mounts `/tmp` on a container and causes this surprising result.
- Even reproducible by running `docker run -it --tmpfs=/tmp --rm busybox` instead of `make shell`.
- Not reproducible by just running `docker run -it --rm busybox` instead of `make shell`.

- Reproducible with Docker 1.10.3 + AUFS. So this is not new to 1.11 nor specific to Overlay.

**Comment by HackToday** [comment]
I tried with your example
`docker run -it --tmpfs=/tmp --rm busybox`, the cp would get empty content,

it also hit same like docker volume mount directory, and the `--tmpfs=` is volume ways, so 
`/var/lib/docker/aufs/mnt/b2414179d3eccb636eaf18298ace7c234b28102ceff5ed9b1629973295358b84/tmp` like that is empty.
so cp not get anything.


if you want to copy related files from volume, it sames a new feature request,  Is it ?

**Comment by AkihiroSuda** [comment]
@HackToday  Thank you for looking into this.

I think this is not a new feature request, because `docker exec foo tar cf /tmp | tar xf -` is enough if the behavior is explicitly documented.

If the behavior is expected, I would like to open PR just for documentation improvement.

**Comment by HackToday** [comment]
@AkihiroSuda I mean if you want to use `docker cp` for that.

ping @cpuguy83

**Comment by cpuguy83** [comment]
This is most likely because the tmpfs is not mounted during the `docker cp`.
Might be a little weird use tmpfs in this way.

If you really want to do this, you can create a tmpfs volume like so:
```
 docker volume create --opt type=tmpfs --opt device=tmpfs --opt o=size=10M,nodev,nosuid
```
This is just an example, you can use whatever opts you like here. Only need to specify `type=tmpfs` and `device=tmpfs`

**Comment by HackToday** [comment]
not sure if above can be used with `docker cp` 
@AkihiroSuda Could you verify it can meet your requirements and still issue ?

**Comment by AkihiroSuda** [comment]
@cpuguy83 @HackToday 
Thank you for information.
Yes, `docker volume` worked for me, although actually `docker exec foo tar cf /tmp | tar xf -` also meets my requirement as well.

If the community can make a consensus that this is not a bug, I would like to just set `kind/docs` the tag, and open PR for mentioning this tips on the document.

**Comment by HackToday** [comment]
perhaps should ask this question to @rhatdan  why volume can work, while tmpfs can not work for cp.

**Comment by cpuguy83** [comment]
The reason is we don't mount the tmpfs when doing the `cp` most likely, I haven't checked yet.

**Comment by rhatdan** [comment]
I think dockor cp is just mounting a separate copy of the container image, and it could not do this with a tmpfs.  It is not entering the mnt namespace of the container, and the tmpfs is private to this namespace.  docker exec is actually entering the mnt namespace of the container and then it can see the tmpfs.  Using docker volumes, the tmpfs is mounted outside of the container mnt namespace and only bind mounted into the container, so if docker cp can bind mount in the same tmpfs in it should be able to see the tmpfs.
