### ISSUE TITLE
Could not reach any registry endpoint

### ISSUE THREAD

**Issue by diezcode** [docker/docker#22027]
I'm getting this : Could not reach any registry endpoint
Every time I will make this command:

> sudo docker run -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo --name db postgres

> sudo docker run -p 0.0.0.0:8070:8070 --name odoo --link db:db -t odoo

on ubuntu 14.04 , why? can someone help me

I have docker version 1.3.1

Is there a possible to download the images from this command and to build the image first and then to run the containers from the images?

the problem is that I don't knowwhat the update does to all my containers, if all my other containers and databases will crash or not.

Is there any danger from the docker update?

**Comment by HackToday** [comment]
it seems ok with new docker

```
ubuntu@proxyserver:~$ docker run -p 0.0.0.0:8070:8070 --name odoo --link db:db -t odoo
2016-04-14 10:05:12,295 1 INFO ? openerp: OpenERP version 9.0c-20160324
2016-04-14 10:05:12,296 1 INFO ? openerp: addons paths: ['/var/lib/odoo/addons/9.0', u'/mnt/extra-addons', u'/usr/lib/python2.7/dist-packag]
2016-04-14 10:05:12,297 1 INFO ? openerp: database: odoo@172.17.0.2:5432
2016-04-14 10:05:12,778 1 INFO ? openerp.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
```

And your docker version 1.3.1 is too old. what's the benefits to use old version here ?

**Comment by diezcode** [comment]
this docker build was setup in 2015 , the problem is that I don't know if I can update the docker version, without troubble with all the existing containers or images.

**Comment by thaJeztah** [comment]
This is expected; Docker 1.5 and older is no longer supported by Docker Hub; see the announcement here:  https://blog.docker.com/2015/10/docker-hub-deprecation-1-5/ (but you should also have received e-mails during that period)

So, the resolution is to update to a more recent version, because 1.3.1 is no longer supported on Docker Hub.

I'll close this issue, but feel free to continue the discussion
