### ISSUE TITLE
[1.11.0] Labels set on the command line don't override labels in Dockerfile

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#22036]
**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64
```
**Steps to reproduce the issue:**

```
FROM scratch
LABEL foo=from-dockerfile
```

    docker build -t scratchy --label foo=from-flag --label bar=from-flag .

**Describe the results you received:**

inspect the resulting image;

    docker inspect --format "{{ json .Config.Labels }}" scratchy
    {"bar":"from-flag","foo":"from-dockerfile"}

**Describe the results you expected:**

I expected the `foo` label on the commandline to override the `foo` label that 
was set in the Dockerfile.

**Additional information you deem important (e.g. issue happens only occasionally):**

This was implemented in https://github.com/docker/docker/pull/21270, and additional changes in https://github.com/docker/docker/pull/21664

**Comment by calavera** [comment]
I think this was by design. They do not override labels with a value. Or it's how I interpreted the code.

**Comment by justincormack** [comment]
I am not clear if it was by design or not, there seems to be an inconsistency that you can override labels inherited via `FROM` on the command line but not direct ones:

```
whale:labels justin$ docker build -t from .
Sending build context to Docker daemon 3.072 kB
Step 1 : FROM scratch
 ---> 
Step 2 : LABEL foo from-dockerfile
 ---> Using cache
 ---> 27ee87a3691b
Successfully built 27ee87a3691b
whale:labels justin$ docker inspect --format "{{ json .Config.Labels }}" from
{"foo":"from-dockerfile"}
whale:labels justin$ vi Dockerfile.2 
whale:labels justin$ docker build  --label foo=new -f Dockerfile.2 -t new  .
Sending build context to Docker daemon 3.072 kB
Step 1 : FROM from
 ---> 27ee87a3691b
Step 2 : LABEL bar from-dockerfile2
 ---> Running in 3a4c4f273ef8
 ---> f5bbfd1c4b00
Removing intermediate container 3a4c4f273ef8
Successfully built f5bbfd1c4b00
whale:labels justin$ docker inspect --format "{{ json .Config.Labels }}" new
{"bar":"from-dockerfile2","foo":"new"}
```

So I think that maybe it was accidental?

**Comment by yongtang** [comment]
Hi @thaJeztah @calavera @justincormack the label override via `FROM` happens in:
https://github.com/docker/docker/blob/v1.11.0/builder/dockerfile/internals.go#L47-L49
I create a pull request #22184 so that the command line option will not overwrite labels via `FROM` image.

If we want the behavior to be otherwise (command line option will always override labels both in Dockerfile and in `FROM` images), please let me know and I will update the pull request accordingly.

**Comment by thaJeztah** [comment]
Thanks @yongtang, let's get clear what the intended behavior should be. I personally think that command-line options should override options in the Dockerfile. If that's not the intended behavior, then we should produce an error ("conflicting options"), instead of silently ignoring the command-line flag.

ping @ehazlett @tiborvass PTAL if there's any reason we don't want a label on the command-line to override/update a `LABEL` that's present in the Dockerfile

**Comment by vdemeester** [comment]
100% agree with @thaJeztah 😇

**Comment by tiborvass** [comment]
Sure, i'll send a PR

**Comment by yongtang** [comment]
Since there is already a pull request #22184 in place, @tiborvass would you mind if I update the existing pull request #22184 and make changes to fit the expected behavior as discussed above?

**Comment by tiborvass** [comment]
@yongtang sure will review it today

**Comment by yongtang** [comment]
Thanks @tiborvass I will update the pull request shortly.
