### ISSUE TITLE
Installation stuck behind proxy

### ISSUE THREAD

**Issue by rinrinne** [docker/docker#22035]
**Output of `docker version`:**
N/A

**Output of `docker info`:**
N/A

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Machine: Physical
Arch: x86_64
OS: Ubuntu 14.04 desktop
Network: behind proxy, reachable to *.docker.com via proxy

**Steps to reproduce the issue:**
I'm behind proxy, so according to https://docs.docker.com/linux/step_one/
```
$ curl -fsSL https://get.docker.com/gpg | sudo apt-key add -
$ curl -fsSL https://get.docker.com/ | sh
```

**Describe the results you received:**
```
$ curl -fsSL https://get.docker.com/ | sh
apparmor is enabled in the kernel and apparmor utils were already installed
+ sudo -E sh -c apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.V8fm8r2Jla --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/somc-ring.gpg --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
gpg: requesting key 2C52609D from hkp server ha.pool.sks-keyservers.net
```
Then installation stuck.

**Describe the results you expected:**
Installation completed.

**Additional information you deem important (e.g. issue happens only occasionally):**
Installation script should check already imported key before getting it from remote service.

**Comment by thaJeztah** [comment]
@tianon @jfrazelle I know you preferred to not add more complexity to this script, but any thoughts on this?

@rinrinne in the meantime, I suggest to follow the manual procedure; https://docs.docker.com/engine/installation/linux/ubuntulinux/

**Comment by jfrazelle** [comment]
I think the goal is to remove the script completely one day so im still
pretty much down to not add thingns

On Thu, Apr 14, 2016 at 9:55 AM, Sebastiaan van Stijn <
notifications@github.com> wrote:

> @tianon <https://github.com/tianon> @jfrazelle
> <https://github.com/jfrazelle> I know you preferred to not add more
> complexity to this script, but any thoughts on this?
>
> @rinrinne <https://github.com/rinrinne> in the meantime, I suggest to
> follow the manual procedure;
> https://docs.docker.com/engine/installation/linux/ubuntulinux/
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/22035#issuecomment-210046380>
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by rinrinne** [comment]
@thaJeztah OK, I will use it.

Actually, I have a patch to solve this. But it would not be needed.

**Comment by thaJeztah** [comment]
@rinrinne a patch for the installation script? You're still free to open a PR for that, but (given the discussion above) no guarantee it will be accepted.
