### ISSUE TITLE
"shim error: invalid argument" when trying to run a container after upgrading to v1.11

### ISSUE THREAD

**Issue by x3ro** [docker/docker#22037]
**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:17:17 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:17:17 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 1
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 12
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.2.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 17.68 GiB
Name: d1
ID: DRUU:7R2I:CVOG:RAS5:UI73:ZI54:DARD:YUU7:GII2:JBMT:ANCS:G4VR
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Steps to reproduce the issue:**
1. Upgrade v1.10 to v1.11 on Debian Jessie (Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.73-2+deb7u2 x86_64 GNU/Linux).
2. Execute docker run hello-world

**Describe the results you received:**
```
$ docker -D run hello-world
DEBU[0000] Corrupted prefix: []
DEBU[0000] [hijack] End of stdout
docker: Error response from daemon: rpc error: code = 2 desc = "shim error: invalid argument".
```

daemon.log:
```
Apr 14 14:55:28 d1 systemd-udevd[4008]: failed to execute '/lib/udev/socket:@/org/freedesktop/hal/udev_event' 'socket:@/org/freedesktop/hal/udev_event': No such file or directory
Apr 14 14:55:28 d1 systemd-udevd[4010]: failed to execute '/lib/udev/socket:@/org/freedesktop/hal/udev_event' 'socket:@/org/freedesktop/hal/udev_event': No such file or directory
Apr 14 14:55:28 d1 systemd-udevd[4018]: failed to execute '/lib/udev/socket:@/org/freedesktop/hal/udev_event' 'socket:@/org/freedesktop/hal/udev_event': No such file or directory
Apr 14 14:55:28 d1 systemd-udevd[4016]: failed to execute '/lib/udev/socket:@/org/freedesktop/hal/udev_event' 'socket:@/org/freedesktop/hal/udev_event': No such file or directory
Apr 14 14:55:28 d1 systemd-udevd[4019]: failed to execute '/lib/udev/socket:@/org/freedesktop/hal/udev_event' 'socket:@/org/freedesktop/hal/udev_event': No such file or directory
Apr 14 14:55:28 d1 systemd-udevd[4020]: failed to execute '/lib/udev/socket:@/org/freedesktop/hal/udev_event' 'socket:@/org/freedesktop/hal/udev_event': No such file or directory
Apr 14 14:55:28 d1 docker[3196]: time="2016-04-14T14:55:28+02:00" level=error msg="containerd: start container" error="shim error: invalid argument" id=9c17448db69fc62c68dc09fb6c52437a2faa8d01ba8c6018ee17dbe24734a303
Apr 14 14:55:28 d1 systemd-udevd[4033]: failed to execute '/lib/udev/socket:@/org/freedesktop/hal/udev_event' 'socket:@/org/freedesktop/hal/udev_event': No such file or directory
Apr 14 14:55:28 d1 systemd-udevd[4034]: failed to execute '/lib/udev/socket:@/org/freedesktop/hal/udev_event' 'socket:@/org/freedesktop/hal/udev_event': No such file or directory
Apr 14 14:55:28 d1 systemd-udevd[4036]: failed to execute '/lib/udev/socket:@/org/freedesktop/hal/udev_event' 'socket:@/org/freedesktop/hal/udev_event': No such file or directory
Apr 14 14:55:28 d1 systemd-udevd[4037]: failed to execute '/lib/udev/socket:@/org/freedesktop/hal/udev_event' 'socket:@/org/freedesktop/hal/udev_event': No such file or directory
Apr 14 14:55:28 d1 systemd-udevd[4040]: failed to execute '/lib/udev/socket:@/org/freedesktop/hal/udev_event' 'socket:@/org/freedesktop/hal/udev_event': No such file or directory
Apr 14 14:55:28 d1 systemd-udevd[4042]: failed to execute '/lib/udev/socket:@/org/freedesktop/hal/udev_event' 'socket:@/org/freedesktop/hal/udev_event': No such file or directory
Apr 14 14:55:29 d1 docker[3196]: time="2016-04-14T14:55:29.095680354+02:00" level=error msg="Handler for POST /v1.23/containers/9c17448db69fc62c68dc09fb6c52437a2faa8d01ba8c6018ee17dbe24734a303/start returned error: rpc error: code = 2 desc = \"shim error: invalid argument\""
Apr 14 14:55:37 d1 ntpd_intres[1893]: ntp_intres.request: permission denied
Apr 14 14:55:37 d1 ntpd_intres[1893]: ntp_intres.request: permission denied
```

**Describe the results you expected:**
The hello-world text is displayed.

**Additional info:**
I'm assuming this is not a general Debian Jessie issue, but purging/reinstalling Docker has not helped. Building an image fails with the same message after pulling the layers.

**Comment by stw** [comment]
+1 same issue on debian jessie upgrade, let me know if you figure anything out. I'll do the same.

**Comment by rustamagasanov** [comment]
same here

**Comment by thaJeztah** [comment]
Are you all running on a 3.2 kernel? Because the minimum kernel version for Docker to run is 3.10

**Comment by thaJeztah** [comment]
(not sure if it's related to this issue)

**Comment by rustamagasanov** [comment]
@thaJeztah the kernel version is 3.13.0-79-generic

**Comment by thaJeztah** [comment]
@rustamagasanov that's on debian jessie, or ubuntu? (3.13.0-79 is the default for Ubuntu 14.04 IIRC)

**Comment by rustamagasanov** [comment]
@thaJeztah  it's the Debian Jessie, this image: https://hub.docker.com/_/postgres/

**Comment by thaJeztah** [comment]
@rustamagasanov trying to reproduce; I did a fresh install on Debian Jessie (but kernel 3.16.0-4-amd64), but no issues. Also tried running the postgres image; not able to reproduce so far :cry:

**Comment by stw** [comment]
I was actually on wheezy on the machine w/ the issue, thought it was jessie, upgrading to jessie to see if that resolves it. Kernel was 3.2.0-4-amd64, so most likely my issue. Thanks @thaJeztah

**Comment by jeek120** [comment]
me too,
14.04.4 LTS
Linux MyServer 3.2.0-29-generic #46-Ubuntu SMP Fri Jul 27 17:03:23 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

run command:docker run hello-world
docker: Error response from daemon: rpc error: code = 2 desc = "shim error: invalid argument".

**Comment by rustamagasanov** [comment]
@thaJeztah sorry, seems like I use 9.5 and you checked the latest version, I will try it later and tell the results

**Comment by cpuguy83** [comment]
@jeek120 Docker is not supported on the 3.2 kernel...

**Comment by icecrime** [comment]
So far it seems all impacted people were in a 3.2 kernel **except** @rustamagasanov: please tell us when you know more!

**Comment by rustamagasanov** [comment]
@thaJeztah you are right, I installed from scratch and can't reproduce it either for some reason. 
@icecrime I tested on Ubuntu boxes now. 

Both are:
```
$ uname -a
Linux movinga 3.2.0-23-generic #36-Ubuntu SMP Tue Apr 10 20:39:51 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
```

In one box:
```
$ docker -v
Docker version 1.10.3, build 20f81dd
$ docker run postgres:9.5
...everything is fine
```

In the other box:
```
$ docker -v
Docker version 1.11.0, build 4dc5990
$ docker run postgres:9.5
...pulling
docker: Error response from daemon: rpc error: code = 2 desc = "shim error: invalid argument".
```

So, starting from 1.11, you dropped support for the old kernel versions?

**Comment by pikespeak** [comment]
Linux malta1356 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u2 x86_64 GNU/Linux

docker -D run hello-world
DEBU[0000] Corrupted prefix: []                         
DEBU[0000] [hijack] End of stdout                       
docker: Error response from daemon: rpc error: code = 2 desc = "shim error: invalid argument".

**Comment by icecrime** [comment]
@rustamagasanov Thanks for the new info!

We didn't drop support for 3.2 as this kernel was never supported: it just happens that 1.11 is the first "obviously" incompatible release. @crosbymichael confirmed that this is due to containerd-shim usage of [`PR_SET_CHILD_SUBREAPER`](http://man7.org/linux/man-pages/man2/prctl.2.html) (introduced in 3.4).

Thank you all for reporting, we can only recommend to upgrade to a newer kernel.

**Comment by MiquelMarino** [comment]
Same here!
Vagrant + ansible + docker

config.vm.box = "chef/debian-7.8”
uname -a
Linux badges-io-dev 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u1 x86_64 GNU/Linux
msg: Docker API Error: rpc error: code = 2 desc = "shim error: invalid argument"
Error!

config.vm.box = "debian/jessie64”
uname -a
Linux badges-io-dev 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) x86_64 GNU/Linux
It works!

sudo docker version
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:17:17 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:17:17 2016
 OS/Arch:      linux/amd64

Thanks!

**Comment by cpuguy83** [comment]
@MiquelMarino Thanks for the report.
As stated above, 3.2 is not a supported kernel (nor has it ever been).
The minimum support kernel is 3.10.

**Comment by MiquelMarino** [comment]
ok!
Thanks for the information.

**Comment by thaJeztah** [comment]
@MiquelMarino great avatar! :+1:

**Comment by ZYNCMA** [comment]
@icecrime 
It seems that PR_SET_CHILD_SUBREAPER also depends on the **glibc** version? 
`linux/prctl.h` from kernel-herders-3.10.0 has PR_SET_CHILD_SUBREAPER defined while `sys/prctl.h` from glibc-headers-2.12 doesn't. 
I think this is the reason why containerd-shim didn't work well although I had updated the kernel of a customized centos 6.2 to 3.10. It recorded the "invalid argument" error in its log in `/run/contained/{container_id}/init/shim-log.json`.

**Comment by gutsal-arsen** [comment]
+1
```
archer@capitan ~ $ docker -D run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
a9d36faac0fe: Pull complete 
Digest: sha256:e52be8ffeeb1f374f440893189cd32f44cb166650e7ab185fa7735b7dc48d619
Status: Downloaded newer image for hello-world:latest
DEBU[0007] Corrupted prefix: []                         
DEBU[0007] [hijack] End of stdout                       
docker: Error response from daemon: docker-containerd-shim not installed on system.

```
```
archer@capitan ~ $ uname -a
Linux capitan 4.6.2-gentoo #3 SMP Thu Jun 16 15:31:10 EEST 2016 x86_64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz GenuineIntel GNU/Linux
```
```

archer@capitan ~ $ docker -v
Docker version 1.12.0-rc2, build 906eacd

```

**Comment by cpuguy83** [comment]
@gutsal-arsen This is not related at all.
Your error is because the `docker-containerd-shim` binary is not in PATH.

**Comment by serofir** [comment]
The same problem.

root@vp:~# docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
c04b14da8d14: Pull complete
Digest: sha256:0256e8a36e2070f7bf2d0b0763dbabdd67798512411de4cdcf9431a1feb60fd9
Status: Downloaded newer image for hello-world:latest
docker: Error response from daemon: rpc error: code = 2 desc = "shim error: invalid argument".
root@vp:~# uname -a
Linux vp 3.2.0-4-amd64 #1 SMP Debian 3.2.81-1 x86_64 GNU/Linux
root@vp:~# docker -v
Docker version 1.11.2, build b9f10c9

**Comment by thaJeztah** [comment]
@serofyr looks like you're running on a 3.2 kernel; docker requires 3.10 as a minimum to run; https://docs.docker.com/engine/installation/linux/debian/
