### ISSUE TITLE
How to run a go with rsyslog in docker?

### ISSUE THREAD

**Issue by jacks808** [docker/docker#22034]
Hi I am trying to run a go program in docker，this program using rsyslog to log some info. when I start my container，ERROR happens. 

**Output of `docker version`:**

```
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 06:06:01 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 06:06:01 UTC 2015
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 45
Images: 89
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 179
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.94-1-tlinux2-0036.tl2
Operating System: Tencent tlinux 2.0 (Final)
CPUs: 24
Total Memory: 62.54 GiB
Name: docker-pass00.bh
ID: H5EF:3WNL:JMZP:BTLX:W4DX:FUJQ:TYTK:FGPF:CNI6:2K3W:AXQM:BJFA
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
My linux is Tencent linux, this linux is based on Centos7
uname -a : Linux SLDKJ 3.10.94-1-tlinux2-0036.tl2
rsyslogd is version 7.4.7-7.el7_0

**Steps to reproduce the issue:**
1.build a docker image with a go program, the go program using rsyslog to log some infos.
2.the docker file is pretty simple. build from CentOs only
3.then start this image. docker run -d --net=host IMAGE_NAME /bin/bash /workspace/start.sh bh

**Describe the results you received:**

begin to start xxxx
TTicketPermPath is: ./xxxx
RsaPriKeyPath is: ./xxxx
RsaPublicKeyPath is: .xxxxx
DummiesPath is : ./xxxxxx
dummies length are : 126
TTicketPermPath is: ./xxxxx
RsaPriKeyPath is: ./xxxx
RsaPublicKeyPath is: ./xxxx
DummiesPath is : ./xxxx
dummies length are : 12691
panic: Unix syslog delivery error

the last line shows our error.
Same binary files running on host, 

**Describe the results you expected:**
Start success

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment]
I suppose it's probably looking to log to `/dev/log` and it's not available in the container.
You either need to setup rsyslog in the container, or mount `/dev/log` (or wherever the syslog socket lives for you).
