### ISSUE TITLE
Device appeared twice

### ISSUE THREAD

**Issue by aga20** [docker/docker#22041]
Hi! 

We use docker 1.10.3. If we check `journalctl` we see this line twice:

> systemd[1]: Device dev-disk-by\x2duuid-51c6bdc7\x2d7687\x2d46fb\x2da549\x2d1721236ad93d.device appeared twice with different sysfs paths /sys/devices/virtual/block/loop0 and /sys/devices/virtual/block/dm-11

And If check `/dev/mapper` I see this:

> docker-253:5-33595520-68937cc5c5009d5257155c05776802eb3313ba4501e8561f1272f175f80230c6 -> ../dm-11

We can run docker but we want to know what is this message exactly and how can we fix it if this is an issue. Thanks for your help!

**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:39:25 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:39:25 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 14
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-253:5-33595520-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 588.2 MB
 Data Space Total: 107.4 GB
 Data Space Available: 22.72 GB
 Metadata Space Used: 1.249 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.3.3-1.el7.elrepo.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859 GiB
Name: singlevm-1
ID: LDQG:AT7B:SDCS:M55F:EP7A:KGRY:JTPZ:BRMC:IQZ3:YFB2:D3HQ:DM3K
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

```

**Comment by cpuguy83** [comment]
ping @rhvgoyal 

THis doesn't really sound like an error, but I'm really not familiar with devmapper.

**Comment by thaJeztah** [comment]
I've seen it in a [couple of other issues](https://github.com/docker/docker/issues?q=is%3Aissue+%22appeared+twice%22), but don't think it was the cause of trouble

**Comment by rhvgoyal** [comment]
I think this might not be a problem. But reason for this seems to be that systemd is reading uuid (I am not sure which uuid it is reading) and it finds same uuid on loop0 and dm thin device (container rootfs). I think  loop devices are being used for thin pool so whatever uuid is in thin device also shows in loop device which is being used as data device of thin pool. IOW, if uuid is stored in first sector say, then it can happen that a thin device gets allocated its first sector which is also first sector of loop device and then it will appear that loop also has same uuid. 

This is my understanding of the issue.

**Comment by aga20** [comment]
Hm, I see. Thanks for your reply.
