### ISSUE TITLE
How to build a Image on a "No-network" docker daemon?

### ISSUE THREAD

**Issue by jacks808** [docker/docker#22064]
Hi 
I am running docker daemon using command below：
`/usr/bin/docker daemon --bridge=none --ip-forward=false --iptables=false --insecure-registry=10.10.10.1`

And I am trying to build a image using docker build.

my docker file is like this:

> FROM centos:7
> RUN echo "nameserver 8.8.8.8" >> /etc/resolv.conf
> RUN echo "nameserver 8.8.4.4" >> /etc/resolv.conf
> RUN yum install wget

then some error info show:

> Loaded plugins: fastestmirror, ovl
> 
> 
>  One of the configured repositories failed (Unknown),
>  and yum doesn't have enough cached data to continue. At this point the only
>  safe thing yum can do is fail. There are a few ways to work "fix" this:
> 
>      1. Contact the upstream for the repository and get them to fix the problem.
> 
>      2. Reconfigure the baseurl/etc. for the repository, to point to a working
>         upstream. This is most often useful if you are using a newer
>         distribution release than is supported by the repository (and the
>         packages for the previous distribution release still work).
> 
>      3. Disable the repository, so yum won't use it by default. Yum will then
>         just ignore the repository until you permanently enable it again or use
>         --enablerepo for temporary usage:
> 
>             yum-config-manager --disable <repoid>
> 
>      4. Configure the failing repository to be skipped, if it is unavailable.
>         Note that yum will try to contact the repo. when it runs most commands,
>         so will have to try and fail each time (and thus. yum will be be much
>         slower). If it is a very temporary problem though, this is often a nice
>         compromise:
> 
>             yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true
> 
> Cannot find a valid baseurl for repo: base/7/x86_64
> Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was
> 14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
> The command '/bin/sh -c yum install -y wget' returned a non-zero code: 1

I guess is because docker daemon is set to no network by `--bridge=none --ip-forward=false --iptables=false`

because some reason，our machine can't run docker daemon on NAT model，so we have to use host  network. And then, how can I build a image on my linux?

**Output of `docker version`:**

```
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 06:06:01 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 06:06:01 UTC 2015
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 66
Images: 152
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 284
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.94-1-tlinux2-0036.tl2
Operating System: Tencent tlinux 2.0 (Final)
CPUs: 24
Total Memory: 62.54 GiB
Name: docker-pass00.bh
ID: H5EF:3WNL:JMZP:BTLX:W4DX:FUJQ:TYTK:FGPF:CNI6:2K3W:AXQM:BJFA
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I am running this docker daemon on tencent Linux kernel, this kernel is based on CentOs7 
uname -a shows:

> Linux docker-pass00.bh 3.10.94-1-tlinux2-0036.tl2 #1 SMP Thu Jan 21 03:40:59 CST 2016 x86_64 x86_64 x86_64 GNU/Linux

**Steps to reproduce the issue:**
1.write a Dockerfile
2.try to build a image using this docker file
3.Error is coming

**Describe the results you received:**

> Step 10 : RUN yum install -y python-setuptools
>  ---> Running in 2f4b176f56a3
> Loaded plugins: fastestmirror, ovl
> 
> 
>  One of the configured repositories failed (Unknown),
>  and yum doesn't have enough cached data to continue. At this point the only
>  safe thing yum can do is fail. There are a few ways to work "fix" this:
> 
>      1. Contact the upstream for the repository and get them to fix the problem.
> 
>      2. Reconfigure the baseurl/etc. for the repository, to point to a working
>         upstream. This is most often useful if you are using a newer
>         distribution release than is supported by the repository (and the
>         packages for the previous distribution release still work).
> 
>      3. Disable the repository, so yum won't use it by default. Yum will then
>         just ignore the repository until you permanently enable it again or use
>         --enablerepo for temporary usage:
> 
>             yum-config-manager --disable <repoid>
> 
>      4. Configure the failing repository to be skipped, if it is unavailable.
>         Note that yum will try to contact the repo. when it runs most commands,
>         so will have to try and fail each time (and thus. yum will be be much
>         slower). If it is a very temporary problem though, this is often a nice
>         compromise:
> 
>             yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true
> 
> Cannot find a valid baseurl for repo: base/7/x86_64
> Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was
> 14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
> The command '/bin/sh -c yum install -y python-setuptools' returned a non-zero code: 1

**Describe the results you expected:**

docker image is build and return a image id 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by justincormack** [comment]
Yes, if you want to build with no networking you will not be able to use any networking in the build process, which is not what you want if you have a yum repo on the network.

The best thing to do is to fix docker so it is working with normal networking. What appears to be the problem if you use the default docker daemon setup?

**Comment by jacks808** [comment]
Our linux kernel is a self made kernel, it was cut some models. So we have to run docker daemon with `--bridge=none --ip-forward=false --iptables=false` If we want to run docker network in bridge model, we must apply to add iptables NAT model to our machine. 

by the way, is there some way to add a param like --net=host to `docker build` command ? 

If there is no way to build a image on docker daemon like us, we have two backup plan
1.build a image on other standard linux like centos7, and push the image to our private registry.
2.we could run a basic image like centos:7 and install our dependencies, and commit this change.

**Comment by justincormack** [comment]
There is currently no way to specify custom networks for `build`, see #10324. I would recommend using a separate build machine and a registry, that is a good solution for builds anyway.

**Comment by jacks808** [comment]
Thanks for your help. I will try to split our build machine and product machine.

**Comment by thaJeztah** [comment]
Looks like this is answered, thanks @justincormack for helping out! I'll close this issue, but feel free to comment after I closed :+1:
