### ISSUE TITLE
The registry   Query Parameters of the Create an image in  Docker Remote  API   is  useless ?

### ISSUE THREAD

**Issue by char1st** [docker/docker#22061]
PLZ  forgive my poor english

I used Docker Remote API to  Create an image , and post registry value (my private registry dockerregistry:5000 ) to the docker api server  like that 

`curl -v  -d "fromImage=hl%2Fspark&registry=dockerregistry:5000&tag=v1.3"     --unix-sock   /var/run/docker.sock http:/images/create`

But  the value of the registry  not worked,  and docker searchs  image from docker hub still .

So I  had to  use fromImage Query Parameter  like this

`curl -v  -d "fromImage=dockerregistry:5000/hl%2Fspark&tag=v1.3"     --unix-sock   /var/run/docker.sock http:/images/create `

and can pull image from my private registry  .

Then l  go to the [https://github.com/docker/docker/blob/master/api/server/router/image/image_routes.go#L76](url) ,  and found the server did not handled Query Parameters registry .

WHY ?

**Comment by thaJeztah** [comment]
Which version of Docker are you using? We removed this from the documentation for Docker 1.9 (and possibly it was not even used in versions before that); see https://github.com/docker/docker/pull/17085

**Comment by thaJeztah** [comment]
I went back through old versions, and it's not even used in version 1.0.0; https://github.com/docker/docker/blob/v1.0.0/api/server/server.go#L452-L503

Looks like it was added  in https://github.com/docker/docker/commit/10c0e990371e065d4fc1c9b680f03a46e5bacc5e#diff-625ca7a182c9ad568828798271b0c168R536, https://github.com/docker/docker/commit/10c0e990371e065d4fc1c9b680f03a46e5bacc5e#diff-651a84f8ad6a38c1f7ccdf63f2692410R357

And removed in docker 0.5.0 https://github.com/docker/docker/commit/66a9d06d9fa7a382c6852cf047e1448e0d3e1782#diff-651a84f8ad6a38c1f7ccdf63f2692410L345

So, I think we can remove it from the documentation in all versions of the API

**Comment by char1st** [comment]
I get it .  Thanks . I will close the issue

**Comment by thaJeztah** [comment]
I opened a pull request to fix the documentation here; https://github.com/docker/docker/pull/22085
