### ISSUE TITLE
Create tree-like view of images

### ISSUE THREAD

**Issue by xificurC** [docker/docker#22073]
When building images with `Dockerfile`s one has a clear view of the parent image one is building it on (`FROM foo`). This image `foo` might be built from another image `bar` etc. One might not be the owner of all these images, some of them can be private and some official. Is there a way to get a clear view of this dependency? We are looking for a way to create a graph view like `dockviz` does (which doesn't work for me right now). It uses the `Parent` property of an image which seems to be empty with the changes from 1.10 or 1.11, not sure. Getting a view of the images is an important exercise to look for improvements in the way one builds docker images. It would be beneficial to have this information available, regardless of whether the image(s) are private or public.

**Comment by cpuguy83** [comment]
Closing as a dup of #17366

Thanks!
