### ISSUE TITLE
Repeating rootfs layers

### ISSUE THREAD

**Issue by xificurC** [docker/docker#22072]
**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 16
 Running: 0
 Paused: 0
 Stopped: 16
Images: 175
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /home/UX/pnagyux/docker/aufs
 Backing Filesystem: extfs
 Dirs: 308
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.13.0-85-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.6 GiB
Name: pnagyubupc
ID: 6ISS:ZOS6:DTPJ:7Z3M:QP73:FHLH:B452:XHQW:GCBP:UKHG:RAK3:SGEB
Docker Root Dir: /home/UX/pnagyux/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. `docker pull nginx:alpine`
2. `docker inspect`
3.

**Describe the results you received:**
The rootfs layers are repeating

**Describe the results you expected:**
Different rootfs layers.

**Additional information you deem important (e.g. issue happens only occasionally):**

I found many, really many images sharing an actual sha digest - `sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef` . Is this a bug of the inspect command or is there some dark magic happening in the background that creates layers with the same digest?

**Comment by icecrime** [comment]
Interesting:

```
~ $ docker inspect nginx:alpine | jq .[0].RootFS.Layers
[
  "sha256:c56b7dabbc7aa730eeab07668bdcbd7e3d40855047ca9a0cc1bfed23a2486111",
  "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
  "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
  "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
  "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
  "sha256:fd945dffa76958555a937ffa894aaa98a98d75f133ad702f66c2a1a63b9eb5e2",
  "sha256:8f8f9820b321ad637d0dae629b404a91e0621b65cc1493d75e9a46005b843578",
  "sha256:c5b60f3a002ffc84f928d7845ff03104084b8d7b2e4477f7669d0d8ee542b666",
  "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
  "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef"
]
```

Ping @aaronlehmann @dmcgowan @tonistiigi: I'm not sure if that's expected.

**Comment by tonistiigi** [comment]
`5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef` is the hash for empty tar, 1024 zero bytes. This happens for images built before `v1.10`, after that empty layers are not put into image configuration any more.

**Comment by aaronlehmann** [comment]
Yes, this is normal for images built before Docker 1.10.

**Comment by icecrime** [comment]
Nice :+1: Thanks for the report, I'm closing this.

**Comment by xificurC** [comment]
I see, I thought it will have something to do with the layers that don't change the filesystem. Thank you all!

**Comment by thaJeztah** [comment]
Thanks for reporting @xificurC - it could've been a bug, so really appreciated! :+1:
