### ISSUE TITLE
Cant pull images or run containers --- docker: open /var/lib/docker/tmp/GetImageBlob245739441: no such file or directory.

### ISSUE THREAD

**Issue by dsifford** [docker/docker#22074]
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Sat Mar 12 19:18:57 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Sat Mar 12 19:18:57 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-8:33-32244576-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 6.141 GB
 Data Space Total: 107.4 GB
 Data Space Available: 101.2 GB
 Metadata Space Used: 6.943 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.141 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.121 (2016-03-26)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.5-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.61 GiB
Name: desktop
ID: KNTQ:UYLE:7XFE:TVXG:GPVV:VBCW:P7JU:F4YX:JCF4:ZVOJ:J5M4:77MQ
Username: dsifford
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Run any command that pulls an image or runs a container. My docker is completely bricked and even a complete uninstall and reinstall didn't fix it.

**Describe the results you received:**
I get the same message over and over:

`ERROR: docker: open /var/lib/docker/tmp/GetImageBlob245739441: no such file or directory.`

(the sha is different each time)

**Describe the results you expected:**
Docker working properly.

**Additional information you deem important (e.g. issue happens only occasionally):**
I completely removed docker, docker-machine, and docker-compose, and completely deleted `/var/lib/docker` and reinstalled and the issue still persists.

**Comment by dsifford** [comment]
I suppose another helpful piece of information might be that this all started when I tried to run a compose file and it stated that a container name existed, when in all actuality it didn't. 

If there is any way that I can just remove every trace of docker and restart, let me know. I have no volumes that I'm concerned with losing.

**Comment by dsifford** [comment]
```
$ docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world

03f4658f8b78: Downloading [==================================================>]    601 B/601 B
a3ed95caeb02: Downloading [==================================================>]     32 B/32 B
docker: open /var/lib/docker/tmp/GetImageBlob549217035: no such file or directory.
See 'docker run --help'.
```

**Comment by dsifford** [comment]
**Update:** 

I made absolutely zero changes since when I first posted this issue other than deciding to do a good old-fashioned reboot and that resolved all my issues. 😖 

No idea why this would have happened, but whatever, we can call it good! Sorry for the bother.

**Comment by stephenwithav** [comment]
Another option is to restart the docker daemon, which just solved this problem for me.

`systemctl restart docker`

**Comment by agherzan** [comment]
I encounter something similar with docker 1.10.3 too. It's not persistent but it happens pretty often. I use a docker in docker setup and pulling images using the docker in container, fails sometimes with:

`open /var/lib/docker/tmp/GetImageBlobXXX: no such file or directory`

**Comment by lifeeth** [comment]
If you have come here seeing this error in a DIND container cleaning up the dangling volumes fixes this.

Delete unused (dangling) volumes (v1.9 and up):
`docker volume ls -qf "dangling=true" | xargs docker volume rm`

**Comment by kamal94** [comment]
Similar to @stephenwithav , this worked for me:
```
sudo service docker stop
sudo service docker start
```

**Comment by meiremans** [comment]
@kamal94 many thanks, that solved the problem indeed :) (Docker version 18.03.1-ce, build 9ee9f40)

**Comment by stolmen** [comment]
Just encountered this issue - host system time was incorrect. I corrected the system time and got this error upon attempting a `docker pull`. Restarting the docker daemon did it for me. `sudo systemctl restart docker`. (Docker version 20.10.6, build 370c289)

**Comment by MallegowdaKM** [comment]
hello guys
delete some volume dir
rm -rf <volumedirname>

**Comment by TMf124857** [comment]
This was missing issue 
$ sudo apt-get install docker-compose-plugin

Doc from 
https://docs.docker.com/compose/install/linux/#install-using-the-repository

**Comment by wastu01** [comment]
https://github.com/moby/moby/issues/22074#issuecomment-224921134

tks for help. it works for me

**Comment by zhangguanzhang** [comment]
I encountered the same problem in one of my environments, and after checking the relevant source code, I confirmed that it was caused by the absence of the `/var/lib/docker/tmp` directory. Creating the directory resolved the issue.

```
$ docker pull hello-world
v1: Pulling from hello-world
e9abf7e9593f: Pulling fs layer 
open /var/lib/docker/tmp/GetImageBlob159490514: no such file or directory

$ mkdir -p /var/lib/docker/tmp # 👈

$ docker pull hello-world
xxx: Pull complete 
Digest: sha256:xxx
Status: Downloaded newer image for hello-world:latest
hello-world:latest
```

[more info](https://zhangguanzhang.github.io/2025/11/06/docker-GetImageBlob-no-such/)
