### ISSUE TITLE
RUN and ENTRYPOINT exec forms don't work on Windows

### ISSUE THREAD

**Issue by friism** [docker/docker#22083]
**Output of `docker version`:**

```
docker version
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.11.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   577adcc
 Built:        Mon Apr 11 17:20:50 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
docker info
Containers: 29
 Running: 1
 Paused: 0
 Stopped: 28
Images: 44
Server Version: 1.11.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: null nat
Kernel Version: 10.0 14316 (14316.1000.amd64fre.rs1_release.160402-2217)
Operating System: Windows Server 2016 Datacenter Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 1.136 GiB
Name: WIN-8F5EG07ROBB
ID: VKYM:E5F7:CMIT:4ZMS:OGUG:W43U:API4:ATWI:3S5X:RO54:DU4Q:YOFD
Docker Root Dir: C:\ProgramData\docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: -1
 Goroutines: 29
 System Time: 2016-04-15T16:06:26.1980441-07:00
 EventsListeners: 0
Username: friism4test
Registry: https://index.docker.io/v1/
```

**Steps to reproduce the issue:**

```
> "FROM windowsservercore`n RUN [""echo"", ""hi""]" | docker build -
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM windowsservercore
 ---> e1e5fb4dbc32
Step 2 : RUN echo hi
 ---> Running in de28f78d07cf
Container command 'echo' not found or does not exist
```

```
> "FROM windowsservercore`n RUN echo hi" | docker build -
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM windowsservercore
 ---> e1e5fb4dbc32
Step 2 : RUN echo hi
 ---> Running in bcf111e455b9
hi
 ---> a4c8026f5ecd
Removing intermediate container bcf111e455b9
Successfully built a4c8026f5ecd
```

**Describe the results you received:**

Error

**Describe the results you expected:**

`hi`

**Additional information you deem important (e.g. issue happens only occasionally):**

Note that "shell" form works fine. The example shown above is for `RUN` but the problem is also extant for `ENTRYPOINT`. I haven't tested `CMD`.

cc @jhowardmsft

**Comment by jhowardmsft** [comment]
Same as you opened the other day. Windows does not have echo.exe.

**Comment by friism** [comment]
@jhowardmsft how then is it that this works?

```
docker run windowsservercore cmd /c echo hi
hi
```

**Comment by jhowardmsft** [comment]
echo is a built in command to the cmd command interpreter.

**Comment by jhowardmsft** [comment]
http://ss64.com/nt/syntax-internal.html. There's probably an MSDN equivalent doc somewhere.

**Comment by friism** [comment]
@jhowardmsft alright, that was a bad repro. I found the behavior when building these two images:

The first one becomes `microsoft/aspnet:1.0.0-rc1-update1-coreclr`

```
FROM windowsservercore

ENV DNX_VERSION 1.0.0-rc1-update1
ENV DNVM_BRANCH "dev"
ENV DNVM_DOWNLOAD_URL "https://raw.githubusercontent.com/aspnet/Home/$DNVM_BRANCH/dnvm.ps1"

RUN @powershell -NoProfile \
	-Command \
	$ErrorActionPreference = 'Stop'; \
	(New-Object System.Net.WebClient).DownloadFile('%DNVM_DOWNLOAD_URL%', 'dnvm.ps1') ; \
	.\dnvm.ps1 install %DNX_VERSION% -global -persistent -alias default -r coreclr ; \
	Remove-Item dnvm.ps1
```

The app Dockerfile.windows

```
FROM microsoft/aspnet:1.0.0-rc1-update1-coreclr

COPY project.json /c/app/project.json
WORKDIR c/app
RUN dnu restore

COPY . /c/app/

EXPOSE 5004
ENTRYPOINT ["dnx.exe", "-p", "project.json", "web", "--server.urls", "http://0.0.0.0:5004"]
```

If I use "shell form" in ENTRYPOINT it works, but not with exec form. `dnx.exe` is in the path. From a running container:

```
C:\c\app>where dnx
C:\ProgramData\Microsoft DNX\runtimes\dnx-coreclr-win-x64.1.0.0-rc1-update1\bin\dnx.exe

C:\c\app>echo %PATH%
C:\Windows\system32;C:\Windows;%localappdata%\Microsoft\WindowsApps;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\Microsoft DNX\runtimes\dnx-coreclr-win-x64.1.0.0-rc1-update1\bin
```

**Comment by jhowardmsft** [comment]
Run the daemon with -D and grab the log around both the successful and failing calls to CreateProcessInComputeSystem and verify that it's invoking what you expect

**Comment by jhowardmsft** [comment]
I'm also amazed it's working at all with /c/app. I don't think it will be doing at all what you think it is. This is not Linux as I keep repeating.

**Comment by jhowardmsft** [comment]
Closing. With docker master, use of `#escape=` and `SHELL ["powershell", "-command"], I don't believe this is an issue any longer. Remember a Windows daemon requires Windows-semantic file paths. Linux paths will not be accepted by the daemon. If the shell in use (as in not cmd/PowerShell) is altering them, there's nothing that can be done by the daemon.

**Comment by masaeedu** [comment]
@lowenna It's still an issue. At the very least the fact that none of the documentation pertaining to the "exec form" of RUN is relevant to Windows should be documented. I'm using:

```
RUN ["C:/windows/system32/cmd.exe", "/S", "/C", ...]
```

and getting the error message:

```
  The command 'cmd /S /C ["C:/windows/system32/cmd.exe", "/S", "/C", ...]' returned a non-zero code: 1
```

**Comment by lowenna** [comment]
@masaeedu I retired a long while back, but it looks like you a combination of shell form and exec form. What's the exact entire, Dockerfile contents, plus output of both `docker info` and `docker version`

**Comment by masaeedu** [comment]
@lowenna Congratulations! I don't have the old Dockerfile anymore, I ended up munging it using the shell form, but I'm not quite following what you mean about combination of shell form and exec form. Isn't `RUN [...]` supposed to be the "exec form"? That's the RUN statement that I was running into issues with when building. (Feel free to ignore this btw, it's not really that important and I've already worked around it).

**Comment by lowenna** [comment]
@masaeedu Did you possibly have an earlier she’ll form ENTRYPOINT? If so, IIRC this is expected, and you would have seen a warning during the build step.

**Comment by dgnuff** [comment]
I'm also having this issue.

Host OS: Windows 10 Pro 20H2

Docker Desktop:
Version 2.5.0.0(49427)
Engine: 19.03.13
Composer: 1.27.4
Kubernetes: v1.19.3
Notary: 0.6.1
Credential Helper: 0.6.3
Snyk: v1.421.1

Dockerfile:
`FROM mcr.microsoft.com/windows/servercore:2009-amd64
ENTRYPOINT ["CMD.EXE", "/c", "echo", "hello", "world"]
`

Expected output: "hello world"

Observed output: '["CMD.EXE"' is not recognized as an internal or external command,
operable program or batch file.
