### ISSUE TITLE
"docker-machine ssh" should use active machine, not default

### ISSUE THREAD

**Issue by scarlac** [docker/docker#22096]
**Output of `docker version`:**

```
➜  ~  docker version
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:13:28 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:38:59 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
➜  ~  docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 12
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 488.9 MiB
Name: docker-sandbox
ID: OR4N:XLTM:QDDK:TJBI:D4IB:GYVA:2YB2:I5XN:2G3V:KOST:7JQR:DBMX
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Username: scarlac
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=digitalocean
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
➜  ~  docker-machine ls
NAME             ACTIVE   DRIVER         STATE     URL                         SWARM   DOCKER    ERRORS
default          -        virtualbox     Running   tcp://192.168.99.100:2376           v1.11.0   
docker-sandbox   *        digitalocean   Running   tcp://***.***.***.***:2376           v1.11.0   
```
(note that docker-sandbox is active, which was done by setting env with `docker-machine env docker-sandbox`)

**Steps to reproduce the issue:**
1. Add a docker-machine other than your default machine using `docker-machine create (...) docker-sandbox`
2. Set the newly created machine as 'active' by using `eval $(docker-machine env docker-sandbox)`
3. Check that it's active by calling `docker-machine ls`. You should see an asterisk in the "ACTIVE" column of the newly created row, similar to my example output.
4. Run `docker-machine ssh` to enter your machine

While it's not directly documented in docker-machine ssh, the 'active' flag should naturally be an indication of what machine should be used as the default target for commands, if relevant.

**Describe the results you received:**
In my case I'm connected to my virtualbox (name 'default') machine instead of the active digitalocean machine (name 'docker-sandbox').

**Describe the results you expected:**
I should be connected to the 'active' machine, not the machine with the 'default' name.

**Additional information you deem important (e.g. issue happens only occasionally):**
This could be considered a feature addition, but given that the environment is already set according to the standard, I'd be so bold to call this a bug/unexpected behaviour.

**Comment by thaJeztah** [comment]
Hi @scarlac, thanks for opening, but can you open this in the Docker Machine issue tracker? Unfortunately, GitHub doesn't have an option to move it there, so I'll have to close it here :cry: 

You can find the Docker Machine issue tracker here; https://github.com/docker/machine/issues

**Comment by scarlac** [comment]
Of course! I'll do that, thanks.
