### ISSUE TITLE
Containers lost after upgrading docker

### ISSUE THREAD

**Issue by JoyceBabu** [docker/docker#22092]
**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:38:59 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:38:59 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 13
 Running: 10
 Paused: 0
 Stopped: 3
Images: 253
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 393
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host weavemesh bridge
Kernel Version: 4.2.0-35-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.7 GiB
Name: ennexa
ID: ZJIB:ZUVY:X7GR:R44F:UMW5:4MDV:PKFK:TYAU:OCFI:T55C:4J6F:Q2AK
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical installation on Ubuntu 15.10

I upgraded docker on a server system today (I am not sure of the old version) using apt-get. The upgrade got stuck trying to upgrade docker and I finally had to restart the server. After restarting some of the containers are missing. I can still see the files from the containers under /var/lib/docker/ but the containers are not listed when running `docker ps -a`.

Is there any hope of recovering the containers and the data?
Where does docker save the list of containers and their meta data?

**Comment by JoyceBabu** [comment]
`docker ps -a` shows 13 containers. I can find 13 `config.v2.json` files under /var/lib/docker. The config file for the missing services are still named `config.json`, could this be the problem?

**Comment by JoyceBabu** [comment]
I downloaded the docker binary with `v1.9.1` downloaded from docker website and now it is showing all the lost containers (but not the new ones). I am now exporting/backing up the containers and trying to import it into the new version.

**Comment by thaJeztah** [comment]
Possibly docker "hanging" was actually due to it being busy with the migration to content-addressable storage; see https://github.com/docker/docker/wiki/Engine-v1.10.0-content-addressability-migration

I think there's a file somewhere that indicates that migration was completed, and removing that file restarts the migration, but not sure if that recovers the containers that you started after you rebooted

**Comment by JoyceBabu** [comment]
Thank you Sebastiaan. I tried running `docker/v1.10-migrator`, but it did not work. Maybe it was due to the file you mentioned. Anyway, I have exported all the data volumes by temporarily switching to v1.9 and imported them into v1.11.

**Comment by thaJeztah** [comment]
Well, good to hear you managed to get it working :+1:
