### ISSUE TITLE
Invalid JSON when removing referenced image with docker remote API

### ISSUE THREAD

**Issue by Silex** [docker/docker#22104]
Hello,

Trying to remove a referenced image with the docker remote API return non-JSON:

``` shell
silex@silex-laptop:~$ curl -X DELETE --unix-socket /var/run/docker.sock http:/images/7a5866c2edbf
conflict: unable to delete 7a5866c2edbf (must be forced) - image is referenced in one or more repositories
```

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:38:59 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:38:59 2016
 OS/Arch:      linux/amd64

```

**Comment by thaJeztah** [comment]
Confirmed; I also tried explicitly setting an `Accept:` header to force JSON, but get a `plain/text` response;

```
curl -v -H "Accept: application/json" -X DELETE --unix-socket /var/run/docker.sock http:/images/d7a513a663c1
*   Trying /var/run/docker.sock...
* Connected to http (/var/run/docker.sock) port 80 (#0)
> DELETE /images/d7a513a663c1 HTTP/1.1
> Host: http
> User-Agent: curl/7.43.0
> Accept: application/json
>
< HTTP/1.1 409 Conflict
< Content-Type: text/plain; charset=utf-8
< Server: Docker/1.11.0 (linux)
< X-Content-Type-Options: nosniff
< Date: Mon, 18 Apr 2016 10:52:33 GMT
< Content-Length: 115
<
conflict: unable to delete d7a513a663c1 (cannot be forced) - image is being used by running container 366e04473582
* Connection #0 to host http left intact
```


The same seems to happen when removing a container;

```
curl -v -H "Accept: application/json" -X DELETE --unix-socket /var/run/docker.sock http:/containers/366e04473582
*   Trying /var/run/docker.sock...
* Connected to http (/var/run/docker.sock) port 80 (#0)
> DELETE /containers/366e04473582 HTTP/1.1
> Host: http
> User-Agent: curl/7.43.0
> Accept: application/json
>
< HTTP/1.1 409 Conflict
< Content-Type: text/plain; charset=utf-8
< Server: Docker/1.11.0 (linux)
< X-Content-Type-Options: nosniff
< Date: Mon, 18 Apr 2016 10:56:14 GMT
< Content-Length: 159
<
You cannot remove a running container 366e04473582456cbe93db4103fdff57e2e37ba96ab61c044dbe965ea68e0632. Stop the container before attempting removal or use -f
* Connection #0 to host http left intact
```

Similar issue for "docker load"; https://github.com/docker/docker/issues/21957 (fixed in https://github.com/docker/docker/pull/21959)

Note that this is not a regression in 1.11; Docker 1.10 looks to behave the same, so we may need to consider versioning this (to prevent older clients breaking)

**Comment by thaJeztah** [comment]
ping @vdemeester @calavera ^^

**Comment by Silex** [comment]
While we are at it, why is it `GET /images/json` and not `GET /images` if the whole api is meant to be JSON anyway?

**Comment by thaJeztah** [comment]
I don't know why it was picked like that, but here's some prior discussion; https://github.com/docker/docker/issues/7671

**Comment by Silex** [comment]
Thanks for the link :+1:

**Comment by justincormack** [comment]
Docker does not take any notice of `Accept:` headers, which is valid, they are just advisory. None of the 4xx or 5xx responses return JSON - they are all `text/plain` as the headers say. So I think this is just a documentation issue perhaps not a bug. #21957 was saying it was returning json but not doing so, which was a bug.

**Comment by yongtang** [comment]
Error messages in Docker are handled by:
https://github.com/docker/docker/blob/91e5bb954131904af150b06bd22b007559a8ce27/api/server/httputils/errors.go#L79
In `net/http` it will just return plaintext:
https://golang.org/pkg/net/http/#Error

Changing the error message to be in json format (in case there is `Accept:  application/json` in request) might be quite easy in `httputils.WriteError`. However, that is a big behavior change that will affect all returned error responses.

**Comment by Silex** [comment]
@justincormack: that makes sense. Should I close this then?

**Comment by justincormack** [comment]
Yes, you can close it, it is here for reference if anyone else runs into the same issue or wants to change the API to support `Accept:` later.

**Comment by Silex** [comment]
:+1:
