### ISSUE TITLE
Docs: Container creation param descriptions not under HostConfig

### ISSUE THREAD

**Issue by johnflavin** [docker/docker#22100]
As of API 1.17, creating a container with `POST /containers/create`, you could set some cpu and memory params on the top level of the posted object. These were `Memory`, `MemorySwap`, `CpuShares`, and `CpuSet`. See the [example request](https://github.com/docker/docker/blame/master/docs/reference/api/docker_remote_api_v1.17.md#L126); the params' respective [description texts](https://github.com/docker/docker/blame/master/docs/reference/api/docker_remote_api_v1.17.md#L192) were correctly placed at the top level with the other descriptions.

In API 1.18, these CPU and memory parameters were moved into `HostConfig`. However, the description text kept the parameters at the top level, i.e. they did not move into the corresponding `HostConfig` section of the description. See the [example object](https://github.com/docker/docker/blame/master/docs/reference/api/docker_remote_api_v1.18.md#L168), where the params are inside `HostConfig`, and the [description text](https://github.com/docker/docker/blame/master/docs/reference/api/docker_remote_api_v1.18.md#L209), where they are not.

This should be a pretty easy fix, right? Just move those descriptions under the `HostConfig` section. But it gets a little funnier than that.

In API 1.19, some new CPU params—`CpuPeriod`, `CpuQuota`, `CpusetMems`—were added that could be set in the `HostConfig` (see [example object](https://github.com/docker/docker/blame/master/docs/reference/api/docker_remote_api_v1.19.md#L170)). But their descriptions (brand new in this version, so they should go in the right place, right?) were added [next to the other incorrectly placed parameters](https://github.com/docker/docker/blame/master/docs/reference/api/docker_remote_api_v1.19.md#L216). :joy:

...Ok, well, I think it's funny.

This problem just keeps growing with each API version. New parameters get added to `HostConfig`, and the container creation documentation shows them inside `HostConfig` for the example request, but not under `HostConfig` in the descriptions. I haven't made a comprehensive survey of exactly which parameters' descriptions should be moved in each version of the docs, but it will be a lot, and more in recent versions than older versions.

Lastly, while I'm pointing out issues with these parameter descriptions, I noticed another small problem that could be cleaned up at the same time. `Cpuset` has been deprecated since API 1.18, and yet it still gets documented in every version of the API docs as 
> **Cpuset** - Deprecated please don't use. Use `CpusetCpus` instead. 

Could this just be removed from the docs? At least the more recent versions. It has been deprecated for several versions now.

**Comment by yongtang** [comment]
@johnflavin Just added a pull request #22135. Let me know if there are any issues.
