### ISSUE TITLE
docker 1.11 restart always policy issue

### ISSUE THREAD

**Issue by RRAlex** [docker/docker#22113]
Up to Docker 1.10.3, exiting docker containers were restarted with policy "always".
Since 1.11.0, our service that exit to get restarted never gets restarted.

**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:38:59 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:38:59 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 30
 Running: 30
 Paused: 0
 Stopped: 0
Images: 38
Server Version: 1.11.0
Storage Driver: devicemapper
 Pool Name: docker-252:0-525747-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 20.28 GB
 Data Space Total: 107.4 GB
 Data Space Available: 87.1 GB
 Metadata Space Used: 26.96 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.121 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.99 (2015-06-20)
Logging Driver: syslog
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-35-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.67 GiB
Name: djd
ID: MYTR:G2WK:32TJ:UYFZ:5PBY:CXF7:3ZCL:ZR7P:3ICF:Y4DT:ZH7P:LGZG
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
KVM

**Steps to reproduce the issue:**
1. Run containers like before with restart policy set to "always".
2. Some containers' process exit and stay stuck in restarting mode.
3. Doing a `docker restart <container id>` does work though.

**Describe the results you received:**
container are never run again

**Describe the results you expected:**
container are restarted after they exit

**Additional information you deem important (e.g. issue happens only occasionally):**

docker inspect --format '{{ .HostConfig.RestartPolicy.Name }}' crawler_1 :
always

docker ps will show something like this:
66073d74ff57        registry.example.com/crawler          "python2 run_crawler."   20 hours ago        Restarting (0) About an hour ago                                                   crawler_1

The daemon's log also show a bunch of these:
Apr 18 10:06:31 server docker[720]: time="2016-04-18T10:06:31.152210600-04:00" level=error msg="restartmanager canceled"

(Doesn't seem related to #22042)

**Comment by thaJeztah** [comment]
@RRAlex wondering; what does

    docker inspect --format "{{ .RestartCount }}"  <containerid>

give you? does it not restart, or is it failing to restart, and now restarting with a really long hold-off delay?

**Comment by thaJeztah** [comment]
@RRAlex also; do the logs for that container show anything why it's failing to start? (`docker logs <containerid>`)?

**Comment by RRAlex** [comment]
@thaJeztah the RestartCount was 19 on one host, 22 on another... So it did try, without success.
docker restart worked like a charm on both.

As for docker logs, I have them split out via rsyslog, but the only things in the container's log are our own python output strings, but on the daemon's log, I still see a few "restartmanager canceled" log lines.

**Comment by thaJeztah** [comment]
@RRalex so, it could be the hold-off time then indeed; 20 restarts would be a long time. Although not clear why it would restart so many time if there isn't a failure

**Comment by RRAlex** [comment]
@thaJeztah I've reset the counter and will try to take a look the next time it won't restart to see if it is closer to 0 retry...
But indeed, it's simply not restarting "in practice" as this containers runs well for many hours, until it has to exit, but won't restart now like with 1.10.3 (unless done by hand).

If you have any specific tests you'd like me to run, I'd be glad to assist!

**Comment by crosbymichael** [comment]
@RRAlex i think #22125 should fix your issue you are having

**Comment by RRAlex** [comment]
@crosbymichael It might indeed be the issue as I'm seeing working restarts that increase the counter.
Once it fails to restart once after, say, 20 restarts, it could explain why it stays stuck for a few hours... 
cheers!

**Comment by RRAlex** [comment]
On a probably unrelated note, the two machines lost all the containers tonight to what seems to be a daemon crash? 
... And none got restarted, they were all in the `Exited` status.

```
syslog:Apr 19 17:45:46 server systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
syslog:Apr 19 17:47:16 server systemd[1]: docker.service: State 'stop-sigterm' timed out. Killing.
syslog:Apr 19 17:47:16 server systemd[1]: docker.service: Unit entered failed state.
syslog:Apr 19 17:47:16 server systemd[1]: docker.service: Failed with result 'timeout'.
...
syslog:Apr 19 18:12:34 otherserver systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
syslog:Apr 19 18:14:04 otherserver systemd[1]: docker.service: State 'stop-sigterm' timed out. Killing.
syslog:Apr 19 18:14:04 otherserver systemd[1]: docker.service: Unit entered failed state.
syslog:Apr 19 18:14:04 otherserver systemd[1]: docker.service: Failed with result 'timeout'.
```

At the moment, I rolled both back to 1.10.3.
