### ISSUE TITLE
Unable to start containers when syslog endpoint unavailable

### ISSUE THREAD

**Issue by programmerq** [docker/docker#22129]
**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   a5315b8
 Built:        Thu Apr 14 10:19:52 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 65
 Running: 10
 Paused: 0
 Stopped: 55
Images: 180
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 687
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.6
Operating System: Alpine Linux v3.3
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.956 GiB
Name: docker
ID: WRRO:GDHQ:2YKH:7VBD:QWM4:ZCIA:LQ7P:QUQX:K5U5:AII7:WZLY:UHL5
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 73
 Goroutines: 118
 System Time: 2016-04-18T21:53:29.71878939Z
 EventsListeners: 1
Username: programmerq
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Docker for Mac Beta (but other environments are affected)

**Steps to reproduce the issue:**

In some cases, I might start a container that is trying to log against a syslog server that is not resolvable in DNS.

**Describe the results you received:**

Currently, this results in a failure:

    docker run --log-driver=syslog --log-opt syslog-address=udp://mysyslog:5000 -d -P nginx:alpine
    Error response from daemon: Cannot start container docker: Error response from daemon: Failed to initialize logging driver: dial udp: lookup mysyslog on 192.168.64.1:53: no such host.

**Describe the results you expected:**

It would be ideal if the docker daemon could gracefully handle this situation rather than fail with an error.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by mlaventure** [comment]
Do you mean having an option simalar to the one that was added for `fluentd` in 1.11 via #19439 (i.e. `fluentd-async-connect`)?

The difference here is that this would have to be implemented on docker side as the library we are using have no support for this kind of behavior.

**Comment by thaJeztah** [comment]
@mlaventure @programmerq shall we close this one in favor of https://github.com/docker/docker/issues/21966, because it's basically the same issue?

**Comment by mlaventure** [comment]
@thaJeztah Happy to close either of them, I actually mis-clicked and didn't close #21966 :)
