### ISSUE TITLE
failed to set to initial namespace

### ISSUE THREAD

**Issue by vanloswang** [docker/docker#22136]
**Output of `docker version`:**

# docker version
Client:
 Version:      1.8.2.fc21
 API version:  1.20
 Package Version: docker-io-1.8.2-2.gitcb216be.fc21.mips64el
 Go version:   go1.6
 Git commit:   227ca88-dirty
 Built:        Wed Apr 13 07:43:45 UTC 2016
 OS/Arch:      linux/mips64le

Server:
 Version:      1.8.2.fc21
 API version:  1.20
 Package Version: 
 Go version:   go1.6
 Git commit:   227ca88-dirty
 Built:        Wed Apr 13 07:43:45 UTC 2016
 OS/Arch:      linux/mips64le

**Output of `docker info`:**

# docker info
Containers: 0
Images: 0
Storage Driver: devicemapper
 Pool Name: docker-8:1-420827-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop2
 Metadata file: /dev/loop3
 Data Space Used: 1.821 GB
 Data Space Total: 107.4 GB
 Data Space Available: 9.661 GB
 Metadata Space Used: 1.479 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.90 (2014-09-01)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.19-1.fc21.1.mips64el
Operating System: <unknown>
CPUs: 4
Total Memory: 3.615 GiB
Name: localhost
ID: G6GJ:FBOP:Y3CE:CCAV:XPZS:VMOV:ZOV5:QSCS:ETLQ:LMZM:YEOC:FTDB

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Steps to reproduce the issue:**
1.run docker -D -d 
2.then check the logs

**Describe the results you received:**
ERRO[0022] failed to set to initial namespace, net:[4026532005], initns fd 8: function not implemented

**Describe the results you expected:**
No such error reports.

**Additional information you deem important (e.g. issue happens only occasionally):**
I know there is no offical support for mips, but i want to run docker on mips platform, and now i compiled it , run it successfully. But the docker daemon show such a error to me, is it important? maybe it will cause network problems.

**Comment by vanloswang** [comment]
It do cause problem to start container. The error info is as follow:
DEBU[0009] Calling GET /containers/json                
INFO[0009] GET /v1.20/containers/json                  
DEBU[0014] Calling GET /containers/json                
INFO[0014] GET /v1.20/containers/json?all=1            
DEBU[0020] Calling POST /containers/{name:.*}/start    
INFO[0020] POST /v1.20/containers/d91afcaa9c92/start   
DEBU[0020] activateDeviceIfNeeded(d91afcaa9c92f5e1b2cd96f6e23b5cfe00167345f68437352a3f7ba7045ed367)
ERRO[0020] failed to set to initial namespace, net:[4026532005], initns fd 8: function not implemented
ERRO[0020] failed to set to initial namespace, net:[4026532005], initns fd 8: function not implemented
ERRO[0020] failed to set to initial namespace, net:[4026532005], initns fd 8: function not implemented
ERRO[0020] failed to set to initial namespace, net:[4026532005], initns fd 8: function not implemented
ERRO[0020] failed to set to initial namespace, net:[4026532005], initns fd 8: function not implemented
DEBU[0020] [devmapper] UnmountDevice(hash=d91afcaa9c92f5e1b2cd96f6e23b5cfe00167345f68437352a3f7ba7045ed367)
DEBU[0020] [devmapper] Unmount(/var/lib/docker/devicemapper/mnt/d91afcaa9c92f5e1b2cd96f6e23b5cfe00167345f68437352a3f7ba7045ed367)
DEBU[0020] [devmapper] Unmount done                    
DEBU[0020] [devmapper] deactivateDevice(d91afcaa9c92f5e1b2cd96f6e23b5cfe00167345f68437352a3f7ba7045ed367)
DEBU[0020] [devmapper] removeDevice START(docker-8:1-420827-d91afcaa9c92f5e1b2cd96f6e23b5cfe00167345f68437352a3f7ba7045ed367)
DEBU[0020] [devmapper] removeDevice END(docker-8:1-420827-d91afcaa9c92f5e1b2cd96f6e23b5cfe00167345f68437352a3f7ba7045ed367)
DEBU[0020] [devmapper] deactivateDevice END(d91afcaa9c92f5e1b2cd96f6e23b5cfe00167345f68437352a3f7ba7045ed367)
DEBU[0020] [devmapper] UnmountDevice(hash=d91afcaa9c92f5e1b2cd96f6e23b5cfe00167345f68437352a3f7ba7045ed367) END
ERRO[0020] Handler for POST /containers/{name:.*}/start returned error: Cannot start container d91afcaa9c92: failed sandbox add: failed to add interface vethe1a6565 to sandbox: function not implemented
ERRO[0020] HTTP Error                                    err=Cannot start container d91afcaa9c92: failed sandbox add: failed to add interface vethe1a6565 to sandbox: function not implemented statusCode=500

**Comment by vanloswang** [comment]
my mistake, assign the wrong system call number.so close it.

**Comment by jcxian** [comment]
How did you solve it?
