### ISSUE TITLE
Docker-in-docker should work, even without privileged mode

### ISSUE THREAD

**Issue by michaelsafyan** [docker/docker#22139]
Docker version 1.11.0, build 4dc5990
Environment: Cloud9 IDE (c9.io)

Installation process / "docker run hello-world" ultimately fails (as does "sudo docker daemon"), apparently due to the fact that Cloud9 itself is running within a Docker container:
http://stackoverflow.com/questions/27728449/cant-get-docker-running-on-cloud9-ide

When running inside a Docker container, docker should not be able to allocate arbitrary resources, but should at least be able to further subdivide the resources allocated to the container in which it is running. (And it should be possible to do this securely).

**Comment by cpuguy83** [comment]
It's not just about subdividing resources.
Docker needs to be able to mount things (CAP_SYS_ADMIN), configure network interfaces (CAP_NET_ADMIN) and a slew of other things. The only thing `--privileged` does is make sure Docker _doesn't_ drop caps/filter syscalls/apply apparmor templates, etc.

**Comment by michaelsafyan** [comment]
Can it do this by IPC communication with the containing daemon instead of
having these privileges directly, however? That would at least ensure that
other programs in the container don't arbitrarily have these privileges
(with the outer daemon being able to validate calls from inside the
container).

**Comment by cpuguy83** [comment]
@michaelsafyan We're actively looking at how we can break up the daemon further, but no containerd can't really handle everything that would allow the docker daemon to drop privileges... but even so, it's just moving the pieces around. You'd still have to run containerd in the docker-in-docker scenario and it would still require certain privileges.

**Comment by justincormack** [comment]
There is ongoing work on getting `runc` to work (almost) unprivileged using user namespaces, see https://github.com/opencontainers/runc/issues/38 - this could potentially lead to the ability to run docker like that too, although there are still some outstanding issues to be resolved, and many providers do not provide user namespaces either.

We do not want to special case docker in docker. I know it is annoying that many CI and similar services do not provide proper docker support, but this is outside our control.

**Comment by cpuguy83** [comment]
I'm not sure we should close this as this is definitely a desirable goal.
I will note #20902 is created with the intention to run docker from an unprivileged user, but will still likely need privileged mode due to requiring CAP_SYS_ADMIN, CAP_NET_ADMIN, and being able to make certain syscalls blocked by the default seccomp profile (and access to /proc and other things).

**Comment by justincormack** [comment]
Maybe we should create a tracking issue for run unprivileged with userns support, rather than using this one? We can use this one if you like though. There will need to be quite a few more PRs to fix the various things as you say.

**Comment by cyphar** [comment]
While runC as an unprivileged user is an attainable goal (though some features require kernel patches), I don't think that the Docker daemon will be able to run completely as an unprivileged user (all of the network setup and filesystem mounting requires full system `root`).

**Comment by Cobi** [comment]
Given that https://github.com/opencontainers/runc/pull/774 was merged, does that unblock this?

**Comment by lvangool** [comment]
Still seeing `privileged` as a requirement for docker-in-docker:
https://hub.docker.com/_/docker/
```
docker run --privileged --name some-docker -d docker:stable-dind
Note: --privileged is required for Docker-in-Docker to function properly
```
Is there any other workaround/or ongoing work to run Docker-in-Docker without `privileged`
....or do other dependencies mean it is not going to happen?

**Comment by cpuguy83** [comment]
@lvangool Docker requires many privileged things to run, including but not neccessarily limited to mounts and network configuration.

**Comment by cyphar** [comment]
(Though as part of https://rootlesscontaine.rs/, I've been working with @AkihiroSuda to get unprivileged networking. Mounting is already doable with `umoci` but Docker's storage drivers don't support it.)

**Comment by lvangool** [comment]
Thank you @cpuguy83 and @cyphar for your responses - re: privileges it makes sense that docker requires these - however can I assign those explicitly via `--cap-add` (and if so, is there a definitive list anywhere to be found?). Alternatively, how about the inverse with `--privileged=true` and then `--cap-drop`?

**Comment by elgalu** [comment]
Should this be re-opened? dind still requires privileged mode or exposing /var/run/docker.sock which is a security concern.

**Comment by cpuguy83** [comment]
@elgalu https://get.docker.com/rootless
https://engineering.docker.com/2019/02/experimenting-with-rootless-docker/

**Comment by mo-saeed** [comment]
Hello, I need clarification understanding the risk of using dind-rootfull vs dind-rootless. Is that correct understanding, both need to run with `privileged=true` but in the end, rootless is not running as root so even if the container has all the host capabilities the attacker can't perform any harm using these capabilities and eventually will get access denied?

**Comment by bangzhuzhu** [comment]
[Is there any way to replace --privileged with --security-opt and --cap-add in docker?

**Comment by bangzhuzhu** [comment]
> [Is there any way to replace --privileged with --security-opt and --cap-add in docker?

@cpuguy83, thank you.

**Comment by zhsj** [comment]
> [Is there any way to replace --privileged with --security-opt and --cap-add in docker?

https://zhsj.me/blog/view/dind-without-privileged
