### ISSUE TITLE
Issue with Ubuntu Xenial

### ISSUE THREAD

**Issue by bastienvinh** [docker/docker#22132]
**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      linux/386

Cannot connect to Docker daemon. Is it the docker docker running on this host ? 
```

**Output of `docker info`:**

```
Cannot connect to Docker daemon. Is it the docker docker running on this host ? 
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

* VMWare 11
* Ubuntu Xenial Beta 2

**Steps to reproduce the issue:**
1. Add apt package on source.d.list
2. Update
3. Try install docker-engine , find nothing
4. Download and copy the bin on /usr/local/bin

**Describe the results you received:**

* I don't have docker daemon command.
* I had only docker bin file and not the others like describing in your tutorials : [here](https://docs.docker.com/engine/installation/binaries/)
```
docker/
docker/docker
```

**Describe the results you expected:**

* Docker daemon should exists ...
* Docker-engine should existed on apt lists packages
* I should have this on my tgz : 
```
docker/
docker/docker-containerd-ctr
docker/docker
docker/docker-containerd
docker/docker-runc
docker/docker-containerd-shim

```

**Additional information you deem important (e.g. issue happens only occasionally):**

* **Should I compile the Docker from git ?**

**Comment by HackToday** [comment]
Did you try this ?
`https://get.docker.com/builds/Linux/x86_64/docker-1.11.0.tgz`

**Comment by bastienvinh** [comment]
It is worse 😵 .

```
bash: /usr/local/bin/docker: cannot execute binary file: Exec format error 
```

**Comment by HackToday** [comment]
I did not have ubuntu xenial at hand, so can not confirm now if binary issue or environment issue now

**Comment by thaJeztah** [comment]
There's currently an issue indeed with the .deb packages for Xenial that we're looking into (they were available for the release-candidates, but the actual 1.11.0 isn't available). See the discussion on https://github.com/docker/docker/pull/21461

The static binary should work as an alternative for now, or you can use the Wily repository (which also works for Xenial).

    bash: /usr/local/bin/docker: cannot execute binary file: Exec format error 

Looking at your output in your first comment: `OS/Arch: linux/386` are you running on a 64-bit system? Docker requires 64-bit for the daemon to run on

**Comment by HackToday** [comment]
hi @thaJeztah one question for above comment
> Docker requires 64-bit for the daemon to run on

From https://github.com/docker/docker/blob/master/docs/installation/binaries.md I could find that we have

https://get.docker.com/builds/Linux/i386/docker-1.11.0.tgz
Seems it is i386, did I misunderstood something ?

**Comment by thaJeztah** [comment]
@HackToday yes, but that's only a *client*, the daemon requires 64-bit

**Comment by bastienvinh** [comment]
Ok I see. I install a the wrong version OS. I will reinstall everything.
It should be working.

**Comment by thaJeztah** [comment]
Let me close this issue, thanks!
