### ISSUE TITLE
Docker image parent is empty

### ISSUE THREAD

**Issue by HackToday** [docker/docker#22140]
**Output of `docker version`:**

```
docker 1.10.2 1.10.3 and 1.11
```

**Output of `docker info`:**

```
setup docker on ubuntu 14.04
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**

1. docker pull busybox

2. check Parent field

  ```bash
$ docker inspect busybox | grep Parent
        "Parent": "",
```

3. check history
 
    ```bash
$ docker history  busybox
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
  47bcc53f74dc        4 weeks ago         /bin/sh -c #(nop) CMD ["sh"]                    0 B                 
  <missing>           4 weeks ago         /bin/sh -c #(nop) ADD file:47ca6e777c36a4cfff   1.113 MB
  ```      

Above issue would fail integration test
> https://github.com/docker/docker/blob/master/integration-cli/docker_cli_rmi_test.go#L317

But not sure how jenkins passed before ?

**Describe the results you received:**
 parent field is empty

**Describe the results you expected:**
I should find parent id instead of missing here

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by HackToday** [comment]
ping @thaJeztah and @tonistiigi

**Comment by thaJeztah** [comment]
This is expected; the new content-addressable storage (introduced in docker 1.10) no longer uses `Parent` images to chain together the layers that make up an image.

Prior to 1.10, each image had a single layer, and to get the "complete" image, the Parent field was used to fetch the Parent image, and get its layer.

In Docker 1.10 and above, each image is self-contained, and has a reference to all the layers it needs to create the final image. So;

**Docker 1.9;**

```
my-image  = parent:image-456 + "layer-data aabbcc"
image-456 = parent:image-123 + "layer-data ccddee"
image-123 = parent:none      + "layer-data aabbcc"
```

So after pulling all the "parent" images (to know which layer-data they use), downloading the layer-data for each image, and reconstructing the layers, "my-image" becomes:

```
my-image = "none" + "layer-data aabbcc" + "layer-data ccddee" + "layer-data eeffgg"
```

**In Docker 1.10, docker uses this:**

```
my-image  = "layer-data [aabbcc, ccddee, eeffgg]"
image-456 = "layer-data [aabbcc, ccddee]"
image-123 = "layer-data [aabbcc]"
```

So if you *pull* an image, all docker has to do, is pull "my-image" and, download the layers, and combine them ("aabbcc" +  "ccddee" + "aabbcc")


The "history" in the pulled image is only a textual representation, and the `<missing>` tells you that only the *layer* data is there, but not the actual image that created that layer data.

Note that this all applies if you *pull* an image. If you build an image locally, the "parent" images are there locally, so for example;

```Dockerfile
FROM busybox
RUN echo "hello"
```

```bash
docker build -t from-busybox .
```

And you'll see that `docker history` shows that the parent image (`busybox`) *is* present locally;

```
docker history from-busybox                                                                                                                                          IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
2ac8bc834387        24 minutes ago      /bin/sh -c echo "hello"                         0 B
3240943c9ea3        8 weeks ago         /bin/sh -c #(nop) CMD ["sh"]                    0 B
<missing>           8 weeks ago         /bin/sh -c #(nop) ADD file:7cdf7a89f6a004b2e9   1.114 MB
```

And `docker inspect` also shows that the parent field is set;

```
docker inspect --format "{{ .Parent }}"  from-busybox                                                                                                                sha256:3240943c9ea3f72db51bea0a2428e83f3c5fa1312e19af017d026f9bcf70f84b
```

However, if you `docker push` that image, docker only pushes the last image, and the image-layers, but not the parent images.

**Comment by HackToday** [comment]
But @thaJeztah how could it pass this jenkins test ?

https://github.com/docker/docker/blob/master/integration-cli/docker_cli_rmi_test.go#L317

as it fetch parent field, and it " ", and `docker rmi " "`, I hit that in jenkins test it would fail for that

**Comment by thaJeztah** [comment]
Good question, possibly because it's using a "frozen" image. @runcom (think you wrote that test); any ideas? Should that test be rewritten?

**Comment by HackToday** [comment]
I asked this, because I hit in my code (add support for load/save image event PR)

details here
https://jenkins.dockerproject.org/job/Docker-PRs-gccgo/4579/console

But my code not related with this failed TEST
```
06:19:51 docker_cli_rmi_test.go:322:
06:19:51     c.Fatalf("rmi should have failed because it's a parent image, got %s", out)
06:19:51 ... Error: rmi should have failed because it's a parent image, got Error response from daemon: image name cannot be blank
```

I am curious why other PRs jenkins test not hit such issue ?  😿

**Comment by tonistiigi** [comment]
Busybox is loaded via `docker load` endpoint in the tests. This endpoint allows restoring parent chain from `v1.11`. More importantly, this is using the tar format used before `v1.10` (non-content addressable) and full compatibility was kept with this format in `v1.10` update. You can get parent images from build, migration, loading pre-v1.10 tars and loading v1.11 tars that have multiple images in them.

**Comment by HackToday** [comment]
thanks @tonistiigi for your explanation, I did not find my code 
https://github.com/docker/docker/pull/22137/files
touched load logic, basically, it just called as daemon method compared with separate package way before.

Could you give a quick review what changed the underlying behavior ?

**Comment by HackToday** [comment]
Close it as frozen image used load ways(which had parent field)
