### ISSUE TITLE
RFC: deprecate old graphdb migration / move to an external tool?

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#22146]
Just some thought; the mattn/go-sqlite3 package is a big vendored package, and only used [to migrate the legacy graphdb](https://github.com/docker/docker/blob/19a453e6b40177af31703f107131aae5ca81adf2/daemon/daemon.go#L321-L341) links (Docker 1.9 and older) to the new "runtime" links (https://github.com/docker/docker/pull/16032)

Should we;
- mark the option to migrate from 1.9 versions as "deprecated" (to be removed in 1.14)?
- move the migration to an external tool?

**Comment by justincormack** [comment]
There already is the external tool https://github.com/docker/v1.10-migrator

It is not particularly easy to use if you are running docker4mac/win but we could incorporate it if necessary, or not support migration from older toolbox.

I think removing it from 1.12 would be fine.

**Comment by justincormack** [comment]
Ah, oh I see, yes that seems reasonable too. The tool can be 1.10 or 1.11 - just don't support direct migration to 1.12 if you want that upgrade to take place seems reasonable.

**Comment by cpuguy83** [comment]
I don't think we can remove this unless we really want to break people upgrading from older versions.
A migration tool, while possible, must also be done offline.

**Comment by thaJeztah** [comment]
I was thinking if it would be safe to deprecate it, and remove in 1.14, but agreed that we shouldn't make this change without thinking

**Comment by LK4D4** [comment]
Not sure if people will migrate from 1.9 soon.

**Comment by cpuguy83** [comment]
Yeah let's do this for 1.14 and add a note "you must upgrade to version X first." And exit out early.
