### ISSUE TITLE
docker run failed on mips

### ISSUE THREAD

**Issue by vanloswang** [docker/docker#22143]
**Output of `docker version`:**

```
Client:
Version: 1.8.2.fc21
API version: 1.20
Package Version: docker-io-1.8.2-2.gitcb216be.fc21.mips64el
Go version: go1.6
Git commit: 227ca88-dirty
Built: Wed Apr 13 07:43:45 UTC 2016
OS/Arch: linux/mips64le

Server:
Version: 1.8.2.fc21
API version: 1.20
Package Version: 
Go version: go1.6
Git commit: 227ca88-dirty
Built: Wed Apr 13 07:43:45 UTC 2016
OS/Arch: linux/mips64le
```

**Output of `docker info`:**

```
Containers: 0
Images: 0
Storage Driver: devicemapper
Pool Name: docker-8:1-420827-pool
Pool Blocksize: 65.54 kB
Backing Filesystem: extfs
Data file: /dev/loop2
Metadata file: /dev/loop3
Data Space Used: 1.821 GB
Data Space Total: 107.4 GB
Data Space Available: 9.661 GB
Metadata Space Used: 1.479 MB
Metadata Space Total: 2.147 GB
Metadata Space Available: 2.146 GB
Udev Sync Supported: true
Deferred Removal Enabled: false
Data loop file: /var/lib/docker/devicemapper/devicemapper/data
Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
Library Version: 1.02.90 (2014-09-01)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.19-1.fc21.1.mips64el
Operating System: 
CPUs: 4
Total Memory: 3.615 GiB
Name: localhost
ID: G6GJ:FBOP:Y3CE:CCAV:XPZS:VMOV:ZOV5:QSCS:ETLQ:LMZM:YEOC:FTDB
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Steps to reproduce the issue:**
1.run docker -D -d 
2.docker run --hostname='fedora-container' fedora uname -a

**Describe the results you received:**

1).The docker client reports as follow:
function not implemented
Error response from daemon: Cannot start container 468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2: [8] System error: function not implemented
2).The docker daemon reports as follow:
DEBU[0444] Calling POST /containers/create              
INFO[0444] POST /v1.20/containers/create                
DEBU[0445] [deviceset] AddDevice(hash=468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2-init basehash=4645f5a78d93a625ba0c89b75d97b67a0df78200f67217d3c3e06bc18339b60b) 
DEBU[0445] registerDevice(9, 468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2-init) 
DEBU[0445] [deviceset] AddDevice(hash=468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2-init basehash=4645f5a78d93a625ba0c89b75d97b67a0df78200f67217d3c3e06bc18339b60b) END 
DEBU[0445] activateDeviceIfNeeded(468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2-init) 
DEBU[0445] [devmapper] UnmountDevice(hash=468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2-init) 
DEBU[0445] [devmapper] Unmount(/var/lib/docker/devicemapper/mnt/468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2-init) 
DEBU[0446] [devmapper] Unmount done                     
DEBU[0446] [devmapper] deactivateDevice(468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2-init) 
DEBU[0446] [devmapper] removeDevice START(docker-8:1-420827-468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2-init) 
DEBU[0446] [devmapper] removeDevice END(docker-8:1-420827-468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2-init) 
DEBU[0446] [devmapper] deactivateDevice END(468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2-init) 
DEBU[0446] [devmapper] UnmountDevice(hash=468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2-init) END 
DEBU[0446] [deviceset] AddDevice(hash=468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2 basehash=468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2-init) 
DEBU[0446] registerDevice(10, 468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2) 
DEBU[0446] [deviceset] AddDevice(hash=468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2 basehash=468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2-init) END 
DEBU[0446] activateDeviceIfNeeded(468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2) 
DEBU[0446] [devmapper] UnmountDevice(hash=468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2) 
DEBU[0446] [devmapper] Unmount(/var/lib/docker/devicemapper/mnt/468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2) 
DEBU[0447] [devmapper] Unmount done                     
DEBU[0447] [devmapper] deactivateDevice(468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2) 
DEBU[0447] [devmapper] removeDevice START(docker-8:1-420827-468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2) 
DEBU[0447] [devmapper] removeDevice END(docker-8:1-420827-468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2) 
DEBU[0447] [devmapper] deactivateDevice END(468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2) 
DEBU[0447] [devmapper] UnmountDevice(hash=468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2) END 
DEBU[0447] Calling POST /containers/{name:.*}/attach    
INFO[0447] POST /v1.20/containers/468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2/attach?stderr=1&stdout=1&stream=1 
DEBU[0447] attach: stdout: begin                        
DEBU[0447] attach: stderr: begin                        
DEBU[0447] Calling POST /containers/{name:.*}/start     
INFO[0447] POST /v1.20/containers/468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2/start 
DEBU[0447] activateDeviceIfNeeded(468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2) 
**WARN**[0447] exit status 1                                
DEBU[0447] attach: stderr: end                          
DEBU[0447] attach: stdout: end                          
DEBU[0448] [devmapper] UnmountDevice(hash=468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2) 
DEBU[0448] [devmapper] Unmount(/var/lib/docker/devicemapper/mnt/468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2) 
DEBU[0448] [devmapper] Unmount done                     
DEBU[0448] [devmapper] deactivateDevice(468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2) 
DEBU[0448] [devmapper] removeDevice START(docker-8:1-420827-468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2) 
DEBU[0448] [devmapper] removeDevice END(docker-8:1-420827-468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2) 
DEBU[0448] [devmapper] deactivateDevice END(468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2) 
DEBU[0448] [devmapper] UnmountDevice(hash=468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2) END 
DEBU[0448] [devmapper] UnmountDevice(hash=468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2) 
DEBU[0448] [devmapper] UnmountDevice(hash=468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2) END 
**ERRO**[0448] Error unmounting device 468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2: UnmountDevice: device not-mounted id 468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2 
**ERRO**[0448] Handler for POST /containers/{name:.*}/start returned error: Cannot start container 468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2: [8] System error: function not implemented 

**ERRO**[0448] HTTP Error                                    err=Cannot start container 468c0d132877fb08b644bc82b0e57fdb8fd45fb4c124f8ac668cd92d113134e2: [8] System error: function not implemented statusCode=500

**Describe the results you expected:**
No such error report and run docker container successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**
I know there is no offical support for mips, but i want to run docker on mips platform, and now i compiled it , run it successfully. But the docker daemon show such a error to me, I want to fix it, but the error info is too less for me to debug it.Could any one give me some suggestion?

**Comment by chrisliu529** [comment]
@vanloswang 
Could you provide more info about HOST OS and backend FS you are using?
According to the error message 'function not implemented', it doesn't seem something wrong related to CPU arch but to some missing feature in backend FS. Or you can give a try on 'aufs' instead of 'devicemapper'.

BTW, I'm very curious about your context to run dockers on MIPS platform. Is it some kind of wireless router or PlayStation?

**Comment by vanloswang** [comment]
@chrisliu529 
Host os is fedora 21 mips64le, the backend FS is ext3, devicemapper with loop device. My kernel have no aufs support, but have btrfs, maybe I can try it.

**Comment by vanloswang** [comment]
@chrisliu529 
I tried btrfs, reports the same error info. Maybe there is something wrong related to CPU arch. But I am not familiar with debug docker.

**Comment by vanloswang** [comment]
The log with btrfs is:
DEBU[0026] Calling POST /images/create                  
INFO[0026] POST /v1.20/images/create?fromSrc=-&repo=fedora 
DEBU[0026] Start untar layer                            
DEBU[0042] Untar time: 15.915698s                       
DEBU[0069] Calling GET /images/json                     
INFO[0069] GET /v1.20/images/json                       
DEBU[0073] Calling POST /containers/create              
INFO[0073] POST /v1.20/containers/create                
DEBU[0076] Calling POST /containers/{name:.*}/attach    
INFO[0076] POST /v1.20/containers/fd1f9666ae309b96eea76aaa3e383b81aa49ea5be983716cbddf6deb7095a1be/attach?stderr=1&stdout=1&stream=1 
DEBU[0076] Calling POST /containers/{name:.*}/start     
INFO[0076] POST /v1.20/containers/fd1f9666ae309b96eea76aaa3e383b81aa49ea5be983716cbddf6deb7095a1be/start 
DEBU[0076] attach: stdout: begin                        
DEBU[0076] attach: stderr: begin                        
**WARN**[0077] signal: killed                               
DEBU[0077] attach: stdout: end                          
DEBU[0077] attach: stderr: end                          
**ERRO**[0077] Handler for POST /containers/{name:.*}/start returned error: Cannot start container fd1f9666ae309b96eea76aaa3e383b81aa49ea5be983716cbddf6deb7095a1be: [8] System error: function not implemented 
**ERRO**[0077] HTTP Error                                    err=Cannot start container fd1f9666ae309b96eea76aaa3e383b81aa49ea5be983716cbddf6deb7095a1be: [8] System error: function not implemented statusCode=500

**Comment by chrisliu529** [comment]
@vanloswang 
As far as I know, the performance of btrfs storage driver is *very* poor on non-btrfs backing fs. But you can still give it a try to see if would work at least.
Another option is switching fs to ext4.

**Comment by justincormack** [comment]
There is currently no official MIPS support, I am slightly surprised that you got a build at all, it is not currently a supported platform and I am not surprised there are issues. There has been some interest, and there is Go support now, so it may become a supported platform at some point.

**Comment by vanloswang** [comment]
Could any one give me some suggestions or some infos  to debug this out?
@justincormack
made some change to docker and its deps, but the code can not merge into master now.

**Comment by chrisliu529** [comment]
According to this post: http://blog.hypriot.com/getting-started-with-docker-on-your-arm-device/
It's probably related the fedora image you are trying to run is an x86 image which is not runnable on mips cpu.. Therefore, unless you can find/create some mips docker image, it's pointless to run docker on mips even if you have a docker mips binary..

**Comment by vanloswang** [comment]
@chrisliu529
Thx. I create a minimal mips64le docker images by follow this article http://cloudgeekz.com/625/howto-create-a-docker-image-for-rhel.html

**Comment by justincormack** [comment]
To debug it you need to try to find out exactly where "System error: function not implemented" is coming from, it is not clear from the logs. I would try running the `check-config` script https://raw.githubusercontent.com/docker/docker/master/contrib/check-config.sh and see if the kernel config is appropriate, it may well be an issue there.

**Comment by vanloswang** [comment]
@justincormack
Thx. I already run check-config.sh before it reports such a problem, now I am adding some msg in the source code to locate it.
check-config.sh report as follow:
# ./check-config.sh 
warning: /proc/config.gz does not exist, searching other paths for kernel config ...
info: reading kernel config from /boot/config-4.1.19-1.fc21.mips64el ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MEMCG: enabled
- CONFIG_KEYS: enabled
- CONFIG_MACVLAN: enabled (as module)
- CONFIG_VETH: enabled (as module)
- CONFIG_BRIDGE: enabled (as module)
- CONFIG_BRIDGE_NETFILTER: enabled (as module)
- CONFIG_NF_NAT_IPV4: enabled (as module)
- CONFIG_IP_NF_FILTER: enabled (as module)
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
- CONFIG_NF_NAT: enabled (as module)
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_USER_NS: enabled
- CONFIG_SECCOMP: enabled
- CONFIG_CGROUP_PIDS: missing
- CONFIG_MEMCG_KMEM: enabled
- CONFIG_MEMCG_SWAP: enabled
- CONFIG_MEMCG_SWAP_ENABLED: enabled
- CONFIG_BLK_CGROUP: enabled
- CONFIG_IOSCHED_CFQ: enabled
- CONFIG_BLK_DEV_THROTTLING: missing
- CONFIG_CGROUP_PERF: enabled
- CONFIG_CGROUP_HUGETLB: missing
- CONFIG_NET_CLS_CGROUP: missing
- CONFIG_CGROUP_NET_PRIO: missing
- CONFIG_CFS_BANDWIDTH: enabled
- CONFIG_FAIR_GROUP_SCHED: enabled
- CONFIG_RT_GROUP_SCHED: enabled
- CONFIG_EXT3_FS: enabled
- CONFIG_EXT3_FS_XATTR: enabled
- CONFIG_EXT3_FS_POSIX_ACL: enabled
- CONFIG_EXT3_FS_SECURITY: enabled
- CONFIG_EXT4_FS: enabled
- CONFIG_EXT4_FS_POSIX_ACL: enabled
- CONFIG_EXT4_FS_SECURITY: enabled
- Network Drivers:
  - "overlay":
    - CONFIG_VXLAN: missing
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: missing
  - "btrfs":
    - CONFIG_BTRFS_FS: enabled (as module)
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: enabled (as module)
    - CONFIG_DM_THIN_PROVISIONING: enabled (as module)
  - "overlay":
    - CONFIG_OVERLAY_FS: enabled (as module)
  - "zfs":
    - /dev/zfs: missing
    - zfs command: missing
    - zpool command: missing

**Comment by cpuguy83** [comment]
Closing since this is not supported, but feel free to continue the discussion.
Thanks!

**Comment by vanloswang** [comment]
@justincormack 
I trace the code and find out that the error is cause by in libcontainer/process_linux.go. func start call json.NewDecoder(p.parentPipe).Decode(&ierr), but ierr return nil.
json.NewDecoder seems to be completed in golang/src/encoding/json/stream.go. It is difficult to debug now.

**Comment by vanloswang** [comment]
@justincormack 
Maybe the container image return nothing to the parent, so the input is nil for Decode, and Decode return nil?

**Comment by ryanmaclean** [comment]
@vanloswang - where did you get with this? Also quite interested in MIPS Docker.

**Comment by gesellix** [comment]
same here @ryanmaclean @vanloswang

**Comment by taylorhoward92** [comment]
Also interested, @vanloswang can you provide more detail on how you got to this point or if you ever had any success?
