### ISSUE TITLE
Volume created with volume plugin couldn't be used, recreated or deleted after plugin restart

### ISSUE THREAD

**Issue by IIIEII** [docker/docker#22155]
**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 59
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 63
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local cifs
 Network: bridge null host
Kernel Version: 4.1.19-boot2docker
Operating System: Boot2Docker 1.11.0 (TCL 7.0); HEAD : 32ee7e9 - Wed Apr 13 20:06:49 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.79 GiB
Name: default
ID: IP3A:ADCB:FJOB:CCLX:MOND:AZLI:O6B5:DVAN:BZJO:T4SL:RPC4:CTDT
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 14
 Goroutines: 32
 System Time: 2016-04-19T15:02:14.324784194Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I'm using docker-machine version 0.6.0, build e27fb87 with virtualbox

**Steps to reproduce the issue:**
1. Start `sudo docker-volume-netshare cifs` plugin
2. Create new volume with cifs driver and some options (username/password) - in plugin log I can see that Create is called with my options
3. Use volume with new container - works correctly
4. Restart plugin
5. `docker volume ls` shows no volumes for cifs driver
6. Create volume with cifs driver with same name and options as in point 2 - in plugin log now we have no Create call
7. Use volume with new container - tries to mount volume without my options - no success
8. `docker volume ls` still shows no volumes for cifs driver
9. `docker volume rm name` says that we have no such volume

**Describe the results you received:**
Volume created with volume plugin couldn't be used, recreated or deleted after plugin restart

**Describe the results you expected:**
After plugin restart I could create volume again

**Additional information you deem important (e.g. issue happens only occasionally):**
It seems that docker remembers already created volumes and doesn't send Create signal to plugin on next calls. Maybe we should firstly ask plugin if it knows such a volume before deciding to call Create or not.

**Comment by thaJeztah** [comment]
thanks! (I removed your comments from the other issue)

**Comment by cpuguy83** [comment]
A volume not being available after a plugin restart is a problem with the plugin.

That said we can certainly improve some of the behavior, like having a `force` flag on `volume rm` to clean up the local cache.

**Comment by IIIEII** [comment]
@cpuguy83 I agree, having `force` flag could be a solution. I just want to have any way to recreate my volume.

**Comment by thaJeztah** [comment]
@cpuguy83 is this still an issue?

**Comment by cpuguy83** [comment]
Final nail will be #28994
Though `--force` was added to `volume rm` already, but the aforementioned PR will do a best effort to resolve the situation without user intervention.
