### ISSUE TITLE
Additional dns to overlay network

### ISSUE THREAD

**Issue by nejtr0n** [docker/docker#22154]
Could I add additional dns service (for example consul) to overlay embeded dns service?

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
@nejtr0n thanks for asking, but the GitHub issue tracker is to track bugs and review PR's, not a general support forum. Can you ask your question on one of the below instead?

- forums.docker.com
- the #docker IRC channel on freenode
- StackOverflow

I'll close this issue here
