### ISSUE TITLE
Removal of email field has broken engine 1.11.0↔docker-compose 1.5 pulling private images

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/docker#22165]
The removal of email prompt in `docker login` (and therefore the lack of "email" field in `.docker/config.json`) is causing docker-compose 1.5 (_released on Dec 3, 2015_) to fail **pulling images from private repositories** (incl. Docker Hub) with `"image [...] not found"` error during `compose up` against docker-engine v1.11.0.

Here is the error:

```
$ /usr/local/bin/docker-compose -p compose -f /etc/docker/compose/docker-compose.yml up -d
Pulling privaterepo (privateuser/privaterepo:v1.1)...
Error: image privateuser/privaterepo not found
```

More details at https://github.com/Azure/azure-docker-extension/issues/80#issuecomment-210176464

We fixed the issue by upgrading to docker-compose 1.6.2 however it is concerning that a product releases less than 5 months ago is not supported... Any comments? Perhaps the email field can be kept (as empty string) for backwards-compatibility reasons?

**Comment by thaJeztah** [comment]
Sorry @ahmetalpbalkan, I discussed this with @dnephin (docker compose team), and he mentioned that this actually is a bug in docker compose 1.5, and should be fixed in in 1.6.2 and later. We decided to not make changes to the engine side
