### ISSUE TITLE
do not show plugin in docker info if plugin is empty

### ISSUE THREAD

**Issue by allencloud** [docker/docker#22161]
Docker CLI can be used to interact with docker engine. And it can be used to interact with swarm, too.

when executing `docker info` via swarm, no plugins details shows in output:
```
root@ubuntu:~# docker -H tcp://127.0.0.1:2375 info
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 41
Server Version: swarm/1.1.2
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 1
 ubuntu: 192.168.0.103:2376
  └ Status: Healthy
  └ Containers: 6
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 2.052 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.19.0-25-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-04-19T16:38:26Z
Plugins:
 Volume:
 Network:
Kernel Version: 3.19.0-25-generic
Operating System: linux
Architecture: amd64
CPUs: 1
Total Memory: 2.052 GiB
Name: ubuntu
```

```
Plugins:
 Volume:
 Network:
```
Because in swarm's info api, no detail in plugins, so print empty.

Maybe Docker CLI should handle this case, if empty, don not show Plugins.

**Comment by thaJeztah** [comment]
I'll close this for the reasons stated in https://github.com/docker/docker/pull/22163#issuecomment-212398714. Thanks!

**Comment by thaJeztah** [comment]
w.r.t Swarm, I'm not sure what the best way would be to solve that; I can imagine "plugins" should be shown for each node individually
