### ISSUE TITLE
docker-load is not  friendly

### ISSUE THREAD

**Issue by int32bit** [docker/docker#22177]
I wanted to load a local image tar file  to docker as follow:
```
docker load my_image.tar
```
Unexpectedly, it didn't work! So I exec `docker load --help` for help, I find I have to  append `-i` option before my file(behind not work, too),It's not friendly?

**Comment by HackToday** [comment]
you can also use this way

`docker load < my_image.tar`

**Comment by int32bit** [comment]
Yes，I know this method, but I think `docker load my_image.tar` is more direct！

**Comment by HackToday** [comment]
sure @int32bit  I suggest said another way

wait for more inputs if we want to change CLI interface

**Comment by thaJeztah** [comment]
I'm not sure we'd be able to change this without breaking backward compatibility. For example, this will be a breaking change for people that currently do;

```
cat test.tar | docker load                                                                                                                                             wo 20 apr 16:25:13 2016
0db64c357a88: Loading layer [==================================================>]  10.5 MB/10.5 MB
80bc5e63e4e8: Loading layer [==================================================>] 20.99 MB/20.99 MB
```

Or variations thereof. 

> I find I have to append -i option before my file(behind not work, too),It's not friendly?

That's a known limitation of the way docker parses flags/options. I think the main reason we cannot support adding `-i` after the filename, is that for other commands, this may not be a trivial change;

    docker run --option image --option-for-entrypoint-inside-container

So, to keep this consistent, we standardized on requiring all options first.

**Comment by thaJeztah** [comment]
I'm closing this issue. I get where you're coming from, and I agree it could be a "nice to have", but I don't think we should do this, because there are quite some implications for a minor enhancement. But feel free to continue the discussion after I've closed
