### ISSUE TITLE
Docker allows you to launch 2 containers with the same mac address

### ISSUE THREAD

**Issue by SamSaffron** [docker/docker#22174]
In window 1

```
docker run -it --rm --mac-address 00:11:22:33:44:55 ubuntu /bin/bash
```

In window 2

```
docker run -it --rm --mac-address 00:11:22:33:44:55 ubuntu /bin/bash
```

Actual result: 

Both containers launch, both have the same mac address. 

Desired result: 

Second container does not launch and instead returns the error:

```
Container "raging_bob" is already configured to use 00:11:22:33:44:55
```

**Comment by icecrime** [comment]
Thanks @SamSaffron: cc @mavenugo @aboch.

**Comment by aboch** [comment]
@SamSaffron 
Yes, docker does not protect user from configuring same mac address to different containers.
Same in linux you are allowed to assign the same MAC to different interfaces.

I think it boils down to the fact you do not know where those interfaces are going to be placed. They will not necessarily end up in the same L2 domain. As in docker you do not know where this container will be attached in future.

In general being an explicit user configuration, we leave the responsibility to the user.

**Comment by thaJeztah** [comment]
@aboch in the given example, both are attached to the same network, would that be an issue?

**Comment by thaJeztah** [comment]
I opened https://github.com/docker/docker/pull/22196 to explain this in the documentation, but happy to close that if we decide to use a different approach

**Comment by aboch** [comment]
Thanks @thaJeztah, agree on documenting.

MAC address setting is a low level configuration. Usually, once applications allow the user control over low level knobs, they do not oversee over it. It's like "Ok, you asked me access to that, I'll give it to you but you are on your own". IOW, if user really needs to manipulate the container's MAC, it is expected he knows the implications. 
One popular use-case in docker for setting the MAC is to define the IPv6 address assigned to the container on the default bridge network when daemon is started with the `--fixed-cidr-v6` option. Here user picking unique addresses is a given.

**Comment by SamSaffron** [comment]
Fair enough! thanks!

**Comment by pfaffman** [comment]
I've been trying to figure out why containers had networking problems for months and finally realized that I had multiple containers with the same Mac address. It would seem like a test could be done to see if the address were on the same network.
