### ISSUE TITLE
mount.cifs within a container

### ISSUE THREAD

**Issue by psi-4ward** [docker/docker#22197]
Trying to `mount.cifs` results in `Unable to apply new capability set`

Tested `docker run --cap-add SYS_ADMIN --cap-add MKNOD --device /dev/fuse`
but with `--privileged` its working.

Can anyone tell my how to track down which CAPs i need?

**Comment by cpuguy83** [comment]
@psi-4ward This is likely being filtered by seccomp.
You'd need to either turn off seccomp for the container or provide a new seccomp profile (which blocks mount, among other things, by default).

FYI, I believe `MKNOD` is available by default.

**Comment by psi-4ward** [comment]
I tried that: `--cap-add SYS_ADMIN --security-opt seccomp=unconfined --device /dev/fuse` but i still get the error.

Can i log the blocked calls?

**Comment by cpuguy83** [comment]
It's really difficult to tell what mount.cifs needs. It might be `CAP_DAC_READ_SEARCH`

**Comment by psi-4ward** [comment]
Works ! THANKS! :+1: 

```
docker run ... \
  --cap-add SYS_ADMIN \
  --cap-add DAC_READ_SEARCH \
  --security-opt seccomp=unconfined \
 shoifele/bareos-sd
```

**Comment by samuela** [comment]
I'm trying the `--cap-add SYS_ADMIN --cap-add DAC_READ_SEARCH` config which got rid of the capability errors, but I'm still stuck with
```
mount error(11): Resource temporarily unavailable
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
```
even though the exact same mount command works fine in a VM.

**Comment by gekmcfh** [comment]
> 
> 
> I'm trying the `--cap-add SYS_ADMIN --cap-add DAC_READ_SEARCH` config which got rid of the capability errors, but I'm still stuck with
> 
> ```
> mount error(11): Resource temporarily unavailable
> Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
> ```
> 
> even though the exact same mount command works fine in a VM.

Originally it's was 
`
mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
`
I trying to achieve same with docker-compose.yml:
`
services:
  app:
    build: .
    container_name: app
    networks:
      net:
        ipv4_address: 10.0.10.10
    volumes:
      - .:/code
    ports:
      - 80:80
    depends_on:
      - db
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
`
when i inspect container after `docker-compose up` for the capabilities - here they are:
`
docker inspect a8afc275544a | grep -i cap -B 3
            "CapAdd": [
                "SYS_ADMIN",
                "DAC_READ_SEARCH"
            ],
            "CapDrop": null,
            "Capabilities": null,

`
but when trying to mount via mount -t or fstab, still getting
`
mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
`

**Comment by pustekuchen91** [comment]
hey,

same error "no permission" like @gekmcfh. 

`--privileged` seems to add any capability. So it seems that one is missing? I tried some, but didnt found out which could be missing.

dmesg shows this error `CIFS: VFS: \\xyz.mydomain\IPC$ ioctl error in smb2_get_dfs_refer rc=-112`. Could this be an hint?
