### ISSUE TITLE
Panic, possibly related to use of thin pool on Centos 7

### ISSUE THREAD

**Issue by mschristiansen** [docker/docker#22198]
**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:40:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:40:36 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 12
 Running: 0
 Paused: 0
 Stopped: 12
Images: 11
Server Version: 1.11.0
Storage Driver: devicemapper
 Pool Name: vg0-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 16.14 GB
 Data Space Total: 107.4 GB
 Data Space Available: 91.23 GB
 Metadata Space Used: 3.42 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.13.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.39 GiB
Name: rheo-one
ID: DXCY:3RG6:ADZW:WGHF:AAUG:VAFC:EOIC:EKJ6:6QVS:K52K:UL4J:6X5I
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Username: mschristiansen
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical Server

**Steps to reproduce the issue:**
1. Spin up a number of different containers.
2. Create disk load like restoring a mongodb dump to a replica set.
3. Hope attached stack trace can help.

**Describe the results you received:**
panic: runtime error: invalid memory address or nil pointer dereference
(see attached file for full output from journalctl including go stack trace.
[journalctl.txt](https://github.com/docker/docker/files/228238/journalctl.txt)

**Describe the results you expected:**
No panic

**Additional information you deem important (e.g. issue happens only occasionally):**
This happens only occasionally. Can run for hours and then suddenly crash. Seems to be related to use of thin pool. Also very slow device mapper performance.

**Comment by thaJeztah** [comment]
Did you run into this on docker 1.10 as well (before upgrading), or is this a fresh host / install?

**Comment by cpuguy83** [comment]
This is a dup of #22194

**Comment by sanimej** [comment]
@mschristiansen This panic happens in certain cases when you have more than one external nameservers configured. You can change it to one as a temporary work around. If you are not passing any nameserver (either though --dns or from hosts's resolv.conf) docker will use 8.8.8.8 and 8.8.4.4 by default. In that is the case you can pass one server though the daemon's --dns option.

**Comment by mschristiansen** [comment]
@thaJeztah It occurred after upgrading from 1.10 and again after starting on a fresh install. Not sure if the `dns` option helped. Still having trouble with thin driver on Centos 7.
