### ISSUE TITLE
Cannot use --tmpfs options on mac client

### ISSUE THREAD

**Issue by cjellick** [docker/docker#22205]
**Output of `docker version`:**

```
docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 21
 Running: 5
 Paused: 0
 Stopped: 16
Images: 251
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 350
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.19-boot2docker
Operating System: Boot2Docker 1.10.3 (TCL 6.4.1); master : 625117e - Thu Mar 10 22:09:02 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.955 GiB
Name: docker10
ID: 4FOA:7EK3:JYC4:UNXI:AAGA:T7CQ:SSUC:NT3G:ZU5N:7EE7:DZ6H:JIR4
Debug mode (server): true
 File Descriptors: 127
 Goroutines: 162
 System Time: 2016-04-20T19:22:58.127725296Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: cjellick
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
- Reproduced on vmware b2d and vmware rancherOS
- Requires running docker commands from Mac 

**Steps to reproduce the issue:**
1. From Mac, run this: `docker run --tmpfs /tmp:exec -it ubuntu` and you get
```
docker: Invalid tmpfs option ["exec"].
See 'docker run --help'.
```
2. SSH into you docker VM and run the exact same command and it works just fine. Container is created with a tmpfs filesystem mounted at /tmp.

**Describe the results you received:**
I can't use tmpfs options because it is not supported on Mac.

**Describe the results you expected:**
The OS from which the docker CLI is used should not impact which tmpfs options are allowed.

**Additional information you deem important (e.g. issue happens only occasionally):**
It looks like the problem is that os specific validation is being called on the client side:
https://github.com/docker/docker/blob/3d13fddd2bc4d679f0eaa68b0be877e5a816ad53/pkg/mount/flags.go#L73

**Comment by icecrime** [comment]
Ping @gdevillele @aduermael!

**Comment by thaJeztah** [comment]
oh, actually, I think this is a duplicate of https://github.com/docker/docker/issues/20740, but looks like it was not looked into yet

**Comment by cjellick** [comment]
Ah yes, definitely a dupe @thaJeztah. I swear I searched before submitting! :-P

Closing.

**Comment by thaJeztah** [comment]
Haha, no problem, I just remembered it came up before, but forgot about it.
