### ISSUE TITLE
Proposal: "Add/Remove device" feature to docker update

### ISSUE THREAD

**Issue by SleepyMan** [docker/docker#22206]
Currently, docker does not allow users to make devices accessible by the containers, other than at the start of the container (with "docker run --device=/dev/blah image").
This forces a restart whenever a new device needs to be accessed by the container.
It would be useful, if not necessary for a few enterprise use-cases, to have the ability to add devices at runtime.

I have a few simple personal use-cases:
- Running security software, like a security monitor, in a container and needs to attach new devices without stopping the whole software. It would be unacceptable to lose a video feed for a few seconds every time a new camera is to be installed/replaced. (Using GigE Vision cameras here, which are USB, not network cameras)
- Running Chrome in a container, but due to sporadic USB disconnection, the USB webcam gets identified as a new v4l2 device. Chrome just needs access to the new device, but it is extremely annoying to restart the whole browser just because one page needs video from the webcam. (I'm testing to see if I can use docker for EVERYTHING, including GUI)

It might be possible to circumvent this by running it in privileged-mode and giving the container access to the entire /dev, but this gives way too much access to the container.

I haven't looked at docker's code to see if it's feasible/difficult or not. But I'd think the developers would know this right away.
What do you think?

**Comment by thaJeztah** [comment]
I know there's been a proposal some time ago; https://github.com/docker/docker/pull/8826 (and issues linked to that PR). Overall, the idea is to keep containers "immutable", and not change the configuration of an existing container. would using `docker exec --privileged .....` be a solution? This allows you to execute a privileged command in an existing container.

**Comment by SleepyMan** [comment]
Exec'ing in privileged mode does not allow the process to access the devices outside its container (tested this trying to access /dev/sda, after mknod'ing it, since it doesn't magically list them, it should behave similarly with other USB devices). If there is another way of adding the device while running in privileged mode, correct me, please.

Also, running in privileged mode would not make much sense in Chrome's case, as it was started specifically for containerization reasons, IOW, for sandboxing. I know it might not be as safe as a VM, but much safer than running it completely bare.

I'm not sure if here is the best place to discuss design choices, so I'll be brief:

Immutability is definitely good at times, specially for deployment, but we can't determine every person's needs, hence the ability to map volumes, ports, devices, etc. at container creation time, instead of image creation time. But even a person doesn't fully know all his/her needs, specially when it comes to the changing world.

Take nginx as an example. Sometimes we have a server that uses port X, but we suddenly need to also serve the same content on port Y, maybe for a transition stage. Whatever the reason may be, we definitely don't want to experience downtime, or simply, connection drops from active HTTP2 or WebSocket users. Nginx recognizes this, and allow smooth configuration reloading without dropping active connections, but unfortunately, Docker does not allow exposing new ports to running containers, thus the container still needs to be restarted.

This example uses ports for simplicity's sake, but it may apply to many things, like devices. The point is, things change, for better or for worse, and we need to adapt to these changes as smoothly as possible.

Sometimes, restarting a container is tolerable, but when it isn't, we should have a way of achieving the end result smoothly.

**Comment by LK4D4** [comment]
I'm closing this because of lack of interest from community.

**Comment by jacknlliu** [comment]
A very useful device management proposal from #8826 in docker container runtime.

**Comment by chris-33** [comment]
I would definitely be interested in this feature. 

I'm trying to dockerize a print server on a Raspberry Pi, which right now would require that printer to always be on. Not acceptable to me.

**Comment by jacknlliu** [comment]
@thaJeztah   @LK4D4  in many use cases, especially on most embedded device(like robots and other machine works on the real physical world), applications running in containers should keep connecting with the device. 

But embedded device always has a noise environment and more uncertainties, it may not always have a good connection with the host. And sometimes we should disconnect and reconnect some devices in some operation mode which is a normal operation mode.

If `Docker` does not have this feature, we should change our program logic and more programs and operations on host, so container lost its box! In other words, applications in `Docker` container can not work robustly with the hardware device. It's a drawback and failure design.

**Comment by nicklaseklund** [comment]
Please re-open this case. This functionallity is needed. Maybe the community interest is higher now?

**Comment by Josh-TapNoa** [comment]
Please re-open this, the whole embedded community is having a docker related nose bleed due to poor USB device management in container! 

I have a way of attaching USB devices to a running container, but no way of removing those already attached!
