### ISSUE TITLE
Container crashes with code 137 when given high load

### ISSUE THREAD

**Issue by Omnipresent** [docker/docker#22211]
I have a docker container running python Flask REST service. The REST service takes a URL of an image as input, does processing on it using OpenCV, and returns the result. When I test the container with sending 15 to 20 requests, it eventually crashes with error code 137

**Output of `docker version`:**

```
➜  ~ docker --version
Docker version 1.10.2, build c3959b1
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 48
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 39
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.19-boot2docker
Operating System: Boot2Docker 1.10.3 (TCL 6.4.1); master : 625117e - Thu Mar 10 22:09:02 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.1 MiB
Name: ocrcontainer
ID: 5W4O:DASF:QRLN:AEIA:DFES:3ZFW:UXQC:Y6VX:GO2Z:IDWU:K34Y:SYTK
Debug mode (server): true
 File Descriptors: 18
 Goroutines: 30
 System Time: 2016-04-21T00:57:25.237096937Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VirtualBox on OSx

**Steps to reproduce the issue:**
1. Show container running:

```bash
➜  ~ docker ps
CONTAINER ID        IMAGE                      COMMAND             CREATED             STATUS              PORTS                    NAMES
2c63128e729b        mytest   "python service.py"    10 hours ago        Up 9 minutes        0.0.0.0:5000->5000/tcp   mycontainer
```

2. Send 15 to 20 requests to the server
3. constantly keep running `ps -aux` inside the container to monitor the metrics. Also monitor the statistics with `docker stats`

**Describe the results you received:**
Eventually the container crashes:

Crash monitoring with `ps -aux`

```
root@2c63128e729b:/flask_server# ps -aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1 10.9 86.6 3014032 883488 ?      Dsl  01:05   0:30 python service.py
^[[Aroot         9  0.0  0.0  18152   192 ?        Ss   01:05   0:00 bash
root       159  9.0  0.0  15572   196 ?        R+   01:09   0:00 ps -aux
root@2c63128e729b:/flask_server# ps -auxError response from daemon: Container 2c63128e729bcf7cd796289132e39149086ac9e8b3bbd624fc980f7ff123cc42 is not running: Exited (137) Less than a second ago
```

Crash monitoring with `docker stats`. I'm showing the last few stats before the container crashes. 

```
2c63128e729b        59.68%              905.2 MB / 1.044 GB   86.67%              12.56 MB / 455 kB   22.85 GB / 60.74 MB
CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O
2c63128e729b        59.68%              905.2 MB / 1.044 GB   86.67%              12.56 MB / 455 kB   22.85 GB / 60.74 MB
CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O
2c63128e729b        55.35%              905.8 MB / 1.044 GB   86.72%              12.56 MB / 455 kB   23.63 GB / 60.74 MB
CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O
2c63128e729b        55.35%              905.8 MB / 1.044 GB   86.72%              12.56 MB / 455 kB   23.63 GB / 60.74 MB
CONTAINER           CPU %               MEM USAGE / LIMIT   MEM %               NET I/O             BLOCK I/O
CONTAINER           CPU %               MEM USAGE / LIMIT   MEM %               NET I/O             BLOCK I/O
CONTAINER           CPU %               MEM USAGE / LIMIT   MEM %               NET I/O             BLOCK I/O
CONTAINER           CPU %               MEM USAGE / LIMIT   MEM %               NET I/O             BLOCK I/O
CONTAINER           CPU %               MEM USAGE / LIMIT   MEM %               NET I/O             BLOCK I/O
CONTAINER           CPU %               MEM USAGE / LIMIT   MEM %               NET I/O             BLOCK I/O

```

**Describe the results you expected:**
I expected the container to not crash. 

**Additional information you deem important (e.g. issue happens only occasionally):**
I believe this happens every time the `%MEM` is between 86% to 87% for an extended period of time.

**Comment by phemmer** [comment]
Sounds like you're likely getting hit by the OOM killer. Run `dmesg` and look for messages from the kernel telling you it's killing your stuff.

Exit code 137 means your process was sent a SIGKILL. http://tldp.org/LDP/abs/html/exitcodes.html

**Comment by Omnipresent** [comment]
@phemmer I've added the output for dmesg as a gist here: https://gist.github.com/Omnipresent/17c12d415385f84bc3b5103af529a875

I can see the following in the output

> Out of memory: Kill process 10183 (python) score 873 or sacrifice child
> Killed process 10183 (python) total-vm:3026880kB, anon-rss:868740kB, file-rss:0kB
> docker0: port 1(vethbd301f9) entered disabled state
> veth99072dc: renamed from eth0
> docker0: port 1(vethbd301f9) entered disabled state

So it does look like am OOM killer. But my question is, how do I solve this? I've tried giving a memory limit while running the container but that doesn't help either. 

FWIW and in-case this is not considered a docker issue, I've opened a question on SO about this http://stackoverflow.com/questions/36759132/why-does-docker-crash-on-high-memory-usage

**Comment by cpuguy83** [comment]
Just looks like you're running out of memory on the machine.
Is it normal for your python process to consume a gig of memory under such a load?

**Comment by thaJeztah** [comment]
Setting a memory-limit only prevents the kernel from randomly killing *other* processes (e.g. the docker daemon), but doesn't prevent your container from running out of memory.  If the process in your container requires more memory, increase the amount of memory for the Virtual Machine (or add swap), or tweak / change the application to consume less memory.

Note that this is not different from running the application outside of a docker container; if the system is running out of memory, the kernel *will* kill processes. With Docker, those processes just happen to be in a container.

I'm closing this issue, because I don't think there's a bug here, but feel free to continue the discussion

**Comment by avisri** [comment]
Had code 127 with JAVA based elasticsearch.


( partly my bad  for running a few of the mem hogs at once .
Containers: 10
 Running: 5
 Paused: 0
 Stopped: 5
) 

My vm mem  : 
Total Memory: 1.952 GiB

However adding add this env config to fix it : 
ENV ES_JAVA_OPTS "-Xms1g -Xmx1g"


Wonder how to reserve "a" container (process)  more memory.  Conventional wisdom says this should not work but the above observation did put a dent in my understanding of how memory mgmt was handled inside vm/container/process  ..

**Comment by dwolsey** [comment]
I also was getting the 137 exit code with elasticsearch container.  For me, the easiest solution was to give docker more memory (it was set to the default of 2GB, I moved it up to 8GB).

Thanks for the info.

**Comment by melkamar** [comment]
Since this issue comes up when searching for Elasticsearch in Docker and exit code 137, I'll leave this here:

The docker-compose provided by Dlasticsearch used to contain two memory limits - JVM parameters passed through environment variables, and `mem_limit` Docker parameter. Either make sure that `mem_limit` is higher than the JVM heap space parameter, or just do not use it at all (Elasticsearch documentation does not have it anymore).

Otherwise you will get the 137 exit code and no output whatsoever.

**Comment by alexsmartens** [comment]
In case you are still wondering how to increase the memory limit in docker, you can do so in the `Advanced` tab in docker settings, like that:

![docker_settings](https://user-images.githubusercontent.com/26261714/63275469-95174780-c26f-11e9-9707-a1d41b1382be.png)

More info:
https://docs.docker.com/docker-for-windows/#advanced

**Comment by prescindivel** [comment]
I increased it to 4GB and now it works.

**Comment by praggmatica** [comment]
This solved my problem - upping memory limits, which was commonly suggested, did not work for me, but I had JVM parameters. I removed those and now it's working.

> Since this issue comes up when searching for Elasticsearch in Docker and exit code 137, I'll leave this here:
> 
> The docker-compose provided by Elasticsearch used to contain two memory limits - JVM parameters passed through environment variables, and `mem_limit` Docker parameter. Either make sure that `mem_limit` is higher than the JVM heap space parameter, or just do not use it at all (Elasticsearch documentation does not have it anymore).
> 
> Otherwise you will get the 137 exit code and no output whatsoever.

**Comment by Kevin-Zhang-SYSU** [comment]
When I apply pgsql and sonarqube in k8s, container sonarqube crashes with code 137, than I add these:
------------------
In pgsql.yaml
resources:
          limits:
            cpu: 1000m
            memory: 2048Mi
          requests:
            cpu: 500m
            memory: 1024Mi
--------------------
In sonarqube.yaml
resources:
          limits:
            cpu: 2000m
            memory: 2048Mi
          requests:
            cpu: 1000m
            memory: 1024Mi
then it worked !

**Comment by KevinCheung2259** [comment]
When I apply pgsql and sonarqube in k8s, container sonarqube crashes with code 137, than I add these:

In pgsql.yaml

```yaml
resources:
          limits:
            cpu: 1000m
            memory: 2048Mi
          requests:
            cpu: 500m
            memory: 1024Mi
```

In sonarqube.yaml
```yaml
resources:
          limits:
            cpu: 2000m
            memory: 2048Mi
          requests:
            cpu: 1000m
            memory: 1024Mi
```

then it worked !

**Comment by 1982D** [comment]
Docker

**Comment by Kevin-Zhang-SYSU** [comment]
已收到，谢谢！

**Comment by fracicalopes967-jpg** [comment]
e bom de mas mano 👍👍👍😊😊😊
