### ISSUE TITLE
An unknown new branch v1.8.2

### ISSUE THREAD

**Issue by hqhq** [docker/docker#22214]
What's this new branch for?

ping @vdemeester @thaJeztah 
I don't see any discussion or PR in community, anything new or just a mistake?

I guess it's kind of docker issue that can post issues :wink:

**Comment by thaJeztah** [comment]
Hm, looking at what's in there, I suspect it's a branch for updating / syncing an older version of the documentation

ping @SvenDowideit @moxiegirl were you working on refreshing old documentation?

**Comment by hqhq** [comment]
My first thought is: Is Docker trying to maintain LTS for an old version?
Then I realize there are already 1.8.3 and codes in that branch doesn't seem like for v1.8. I think it must be some mistake or for temporary usage, that doesn't bother and users don't care, I'm going to close it, thanks for attention.

**Comment by thaJeztah** [comment]
Thanks, and thanks for paying attention! 👍

**Comment by SvenDowideit** [comment]
i don't ​_think_​ its likely to be me
I delete my computer and reinstall too often
yeah, i don't have a v1.8.2 branch in my fork either

**Comment by thaJeztah** [comment]
ping @docker/core-engine-maintainers anyone?

**Comment by vbatts** [comment]
looks like someone with push privilege may have accidentally made a branch called `v1.8.2` from master and pushed it. Most recent commit in this branch is ac7e011ec90b110e62aafd3a1b2963634c9976a3

and it's not the same as the v1.8.2 tag
```bash
$ git log v1.8.2...docker/v1.8.2 | grep ^commit | wc -l
6758
```

**Comment by moxiegirl** [comment]
Very easy to set `no_push` which I have as part of my setup routine on all repos.  Prevents this kind of thing.

`git remote set-url --push upstream no_push`

**Comment by thaJeztah** [comment]
@moxiegirl yup, my first step as well; I just wanted to check it wasn't intended for some reason :smile:

**Comment by vdemeester** [comment]
hum.. weird :sweat:

**Comment by tonistiigi** [comment]
@thaJeztah We should delete it as it is not `1.8.2`. It is likely from the github search box. When you search a branch and press enter, if branch doesn't exist it is created. The user may not even notice it.

**Comment by tonistiigi** [comment]
Removed it.

**Comment by vbatts** [comment]
@tonistiigi that was my thought

**Comment by thaJeztah** [comment]
Thanks all, mystery solved! Bad bad UX, GitHub
