### ISSUE TITLE
read docker log error closed pipe

### ISSUE THREAD

**Issue by yqguodataman** [docker/docker#22215]
I use docker go api read docker log   (docker.LogsOptions{
        Container:    id,
        OutputStream: outwr,
        ErrorStream:  errwr,
        Stdout:       true,
        Stderr:       true,
        Follow:       true,
        Tail:         "0",
    }), when the pressure is too large,output read have a error: buf readstring stop: read/write on closed pipe,what is wrong?

**Comment by LK4D4** [comment]
Issue is really old and there is no info or version provided. Feel free to open new issue with reproduction case.
