### ISSUE TITLE
Running Docker network driver plugin as a Docker container

### ISSUE THREAD

**Issue by TrimBiggs** [docker/docker#22239]
Does Docker support running a Docker network driver plugin as a container?

I am running a networking plugin as a container within Docker.  I'm using etcd as a cluster store.  With containers running and networked with my plugin, I end up running into an issue when I stop and restart the Docker daemon.

With Docker running, I start my network plugin, then I run the following:

```
$ docker network create --driver calico --subnet=192.168.0.0/24 my_net
1542184fac9c6b7753452ca2342eb25c8e7f8f2246f840ec5c7537922e45f368
$ docker run --net my_net --name test_container -tid busybox
5f5789cd58ac897bd5d92301427d66745f8515d99f9ef95d6c1885faf2ae1e3c
```

When I stop the Docker daemon:
- All Docker containers stop (as expected)
- The endpoint information for each container is not released/cleaned up (unexpected?)

Since the network plugin container is stopped, the plugin cannot clean up endpoint data. The etcd datastore still contains endpoints under `/docker` as well (possibly because Docker cannot communicate with the network plugin and just stops endpoint cleanup upon finding this?)

When I restart the Docker daemon:
- The endpoint information for each container is not released/cleaned up
- Starting a previously running Docker container fails with error:

```
$ docker start test_container
Error response from daemon: service endpoint with name test_container already exists
Error: failed to start containers: test_container
```

Is there a way to run the Docker daemon with any additional parameters to specify a containerized network plugin?  Will Docker support this at some point if not?

---
## BUG REPORT INFORMATION

**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:40:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:40:36 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 5
 Running: 2
 Paused: 0
 Stopped: 3
Images: 3
Server Version: 1.11.0
Storage Driver: devicemapper
 Pool Name: docker-253:0-525078-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 296.4 MB
 Data Space Total: 107.4 GB
 Data Space Available: 38.3 GB
 Metadata Space Used: 987.1 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null calico
Kernel Version: 3.10.0-327.10.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.797 GiB
Name: calico-mesos-02
ID: FTZU:V6XJ:RPIJ:I77H:KOZN:YO3A:BVNB:GSWD:OWPE:W2YH:KW6V:Z7V2
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Cluster store: etcd://172.24.197.101:2379
```

**Steps to reproduce the issue:**
1. Run Docker
2. Start networking plugin as Docker container
3. Create network
4. Create container

uname output:

```
Linux calico-mesos-02 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by icecrime** [comment]
Ping @anusha-ragunathan @tiborvass (cc @mavenugo).

**Comment by mavenugo** [comment]
@TrimBiggs we added a workaround for such issues via the `docker network disconnect -f {network} {container_name}`. In this case, `docker network disconnect -f my_net test_container`. If you start the container after the forced disconnect, the container must come up fine.

Docker daemon tries its best to perform the stale endpoints (left in the kv-store due to ungraceful daemon shutdown) when the daemon starts. But if the kv-store & plugins are containerized, it could so happen that during the bootup, these containers were not up and that will prevent the daemon to perform full cleanup of these stale endpoints.

Such issues will ideally be addressed when these plugin containers are treated special (as system containers) and brought up sooner than other containers.

Can you try the forced disconnect option and let us know if that works ?

**Comment by bboreham** [comment]
See also https://github.com/docker/libnetwork/issues/882

**Comment by bboreham** [comment]
@mavenugo is there a new proposal for "system containers"?  #18724 was closed.

**Comment by TrimBiggs** [comment]
@mavenugo I tried the following:
- Create `test_con` on network `test_net`
- Create `test_con2` on network `test_net2`

I wasn't sure when to disconnect either from the network, so I:
 - Disconnected `test_con` from the `test_net`
 - Restarted docker
 - Disconnected `test_con2` from `test_net2`

Results below:

```
$ docker network disconnect -f test_net test_con

$ sudo systemctl stop docker
$ sudo systemctl start docker                                                                                                                                                                                                                                                                    

$ docker ps         # libnetwork plugin driver is running
CONTAINER ID        IMAGE                           COMMAND               CREATED             STATUS              PORTS               NAMES
b73c019c2948        calico/node-libnetwork:latest   "./start.sh"          10 minutes ago      Up 25 seconds                           calico-libnetwork
bc94ae8b3069        calico/node:latest              "/sbin/start_runit"   10 minutes ago      Up 25 seconds                           calico-node

$ docker start test_con
Error response from daemon: rpc error: code = 2 desc = "oci runtime error: exit status 1: time=\"2016-04-22T12:20:36-04:00\" level=fatal msg=\"no sandbox present for 86cbbc1689b92831383572d5f19bec20e844490c4260d76d49dc2bffd799d13f\" \n"
Error: failed to start containers: test_con

$ docker start test_con2        # (expected to fail given original issue)
Error response from daemon: service endpoint with name test_con2 already exists
Error: failed to start containers: test_con2

$ docker network disconnect -f test_net2 test_con2
$ docker start test_con2
Error response from daemon: rpc error: code = 2 desc = "oci runtime error: exit status 1: time=\"2016-04-22T12:20:49-04:00\" level=fatal msg=\"no sandbox present for fa87ae4579bbc45fc39034c1ef615b458acd2452be26417e525b05980b559436\" \n"
Error: failed to start containers: test_con2
```

I think it is expected to have at least one of the two containers start normally after having disconnected each from their networks.

I then removed the containers entirely and restarted each:
```
$ docker rm -f test_con2                                                                                                                                                                                                                                                                         
test_con2
$ docker run --net test_net2 --name test_con2 -tid busybox
75858d9b00464f4273cacca0c00e176f2c7951c3cba2854bbbc5c1e6f411b03f
docker: Error response from daemon: service endpoint with name test_con2 already exists.

$ docker rm -f test_con
test_con
$ docker run --net test_net --name test_con -tid busybox
7095a495e544b55d785e2fe86fa9e306ab6fb779f9db297db22ce568a7f03133
```

Looks like I was able to create a new `test_con` container (disconnected before stopping docker), but I could not create a new `test_con2`.  I don't think either of these is actually "right" since I think I should have been able to just start the containers after disconnecting the networks above instead of recreating them, but I think this is still useful info.

**Comment by TrimBiggs** [comment]
I've been thinking about this a bit more.

The workaround isn't really that useful:
 - This action would have to be run on every container in the cluster
 - You have to know the name/id of every container as well as the name of the network of that container

I think one of the following options could be a better solution, alongside or before system containers are implemented:
 - Docker daemon could periodically sync with the driver in the container (check if it's running and resync)
 - Provide a docker command to resync with the network plugin
 - Provide an API into Docker from the remote network driver plugin to allow the plugin to resync with docker at the request of the driver

What do you think?

**Comment by bboreham** [comment]
Referencing #20363 which talks about some other requirements to support plugins inside containers.

**Comment by TrimBiggs** [comment]
Any more thoughts on this? Is anything in the works to improve network plugin support?

**Comment by cpuguy83** [comment]
@TrimBiggs Yes, see #20363 as @bboreham mentioned.

**Comment by TrimBiggs** [comment]
Yes, I had also commented on that issue, but I have not seen any PR or work in progress for the change, so I wanted to check in. Thanks for the note.

**Comment by thaJeztah** [comment]
Plugin support for network plugins has been added in docker 1.13, see https://github.com/docker/docker/blob/master/docs/extend/index.md. I don't think the calico driver has been updated for the new plugin infrastructure yet though

I'll close this issue because this is now supported, but feel free to comment

**Comment by bboreham** [comment]
That page says nothing about network plugins.

**Comment by anusha-ragunathan** [comment]
Network plugins are supported in Pluginv2. A sample network plugin (albeit being a mock plugin) is available at https://hub.docker.com/r/tiborvass/test-docker-netplugin. Basic integration test available at https://github.com/docker/docker/blob/master/integration-cli/docker_cli_network_unix_test.go#L773
