### ISSUE TITLE
orphaned images with repository and tag as none when docker build fails

### ISSUE THREAD

**Issue by sainath14** [docker/docker#22235]
When docker build fails some way in the middle of a dockerfile, for e.g. make test in docker build from source code environment, it leaves a image with repo and tag name as none. When we restart the build with changes to the environment or the Dockerfile looks like it starts to build from the same image, but a copy of the partially built image is left behind.

![image](https://cloud.githubusercontent.com/assets/6599957/14720998/f5de2720-07b8-11e6-8103-3d4f89d47d8f.png)

uname -r
3.13.0-40-generic

docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 52
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 39
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.13.0-40-generic
Operating System: Ubuntu 14.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.54 GiB
Name: sainath-70A4001MUX
ID: U7NG:CVJW:VGOB:N5IE:LG7H:OGVP:37IM:XX4E:NNGC:A2FU:COAD:KQVK
Debug mode (server): true
 File Descriptors: 11
 Goroutines: 27
 System Time: 2016-04-21T12:05:29.358562652-07:00
 EventsListeners: 0
 Init SHA1: e2f80f7797c61007e141f1b60f5b469775a8f712
 Init Path: /usr/lib/docker/dockerinit
 Docker Root Dir: /var/lib/docker
Http Proxy: http://proxy-chain.intel.com:911
Https Proxy: http://proxy-chain.intel.com:911
No Proxy: intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16,/var/run/docker.sock
WARNING: No swap limit support

**Comment by cpuguy83** [comment]
These images are the intermediate steps used for the build cache.

**Comment by sainath14** [comment]
@cpuguy83 True. Let's name this intermediate image from failed docker build attempt as A. This just hanging around there after the docker build failed abruptly. Looks like the next attempt to build from the same dockerfile uses this intermediate image and a successful attempt would create a final image B. But this intermediate image A from the failed attempt still needs to be present? I tried to remove the image A and still able to run a container from the final image B.

**Comment by cpuguy83** [comment]
@sainath14 The image itself, no. The underlying rootfs that the image uses, yes.

**Comment by HackToday** [comment]
What did those none image show ? 
`docker images -f dangling=true` did the output include that ?

Also could you `docker inspect <image id>`, and check what's relationship does it have ? it should have one `Parent` field.

**Comment by sainath14** [comment]
@HackToday Yes the output of docker images -f dangling=true includes all those images
and all the "none" tag images have the same parent image. This parent image is the same for the image created from successful attempt.

Where are these image layers stored on the host? /var/lib/docker ?

**Comment by HackToday** [comment]
do you mean the `dangling` images include your `none` tag images ?

**Comment by sainath14** [comment]
yes dangling filter in docker images command showed all the none tag images
parent image of "none" tag images are not in the list of dangling images. Sorry for the confusion.

All these dangling images are created in the process of running several times make test/test-integration-cli in the docker source code. Some attempts of make failed due to various reasons. Looks like whenever the last container in the build process exits with a failure, the intermediate image it is using to run just gets to stay there.

**Comment by HackToday** [comment]
yes, @sainath14 I agree those dangling images should not be there during a failed build, But I am not sure if docker could address if found build failed and help clean those dangling images, as if you not change Dockerfile, those images would be for build cache for next run.

**Comment by thaJeztah** [comment]
They are left there for caching; the next time you build, Docker looks for images in the cache and reuses the previously built (intermediate) image. You can see that during build as "Using cache". If you want to cleanup those images, run

    docker rmi $(docker images -aq --filter dangling=true)

The intermediate images are not needed to run the final image (which contains all the "layers" of the intermediate images).

I hope this answers your questions. I don't think there's a bug here, as this is working as designed, so I'll close the issue. Feel free to continue the discussion if you still have questions.

**Comment by mcpoppy** [comment]
oooooooooooooo
