### ISSUE TITLE
apt-ftparchive does not mkdir -p

### ISSUE THREAD

**Issue by tiborvass** [docker/docker#22238]
The issue in #22182 was that since xenial was a new package, the `repo/dists/ubuntu-xenial/main/binary-amd64` and `repo/dists/ubuntu-xenial/main/binary-i386` directories were not created at the time apt-ftparchive is called in `hack/make/release-deb`. I dont know why apt-ftparchive doesn't handle this on its own but we should fix it in our scripts as a workaround.

**Comment by kencochrane** [comment]
@tiborvass Not sure why this isn't working, it looks like it already has the mkdir's

https://github.com/docker/docker/blob/master/hack/make/release-deb#L140
and
https://github.com/docker/docker/blob/master/hack/make/release-deb#L120

**Comment by tiborvass** [comment]
@kencochrane because https://github.com/docker/docker/blob/master/hack/make/release-deb#L126 is called before https://github.com/docker/docker/blob/master/hack/make/release-deb#L140. The mkdir at https://github.com/docker/docker/blob/master/hack/make/release-deb#L120 is not enough, the `binary-$arch` is needed for the apt-ftparchive command.

**Comment by tiborvass** [comment]
@kencochrane 
inserting 

```
for arch in "${arches[@]}"; do
		mkdir -p "$APTDIR/dists/$codename/$component/binary-$arch"
done
```

instead of https://github.com/docker/docker/blob/master/hack/make/release-deb#L120 should do it

**Comment by tiborvass** [comment]
we can then delete it from https://github.com/docker/docker/blob/master/hack/make/release-deb#L140

**Comment by kencochrane** [comment]
@tiborvass see https://github.com/docker/docker/pull/22262
