### ISSUE TITLE
Implicit pull on run broken on master

### ISSUE THREAD

**Issue by tonistiigi** [docker/docker#22240]
Doing `docker run busybox ls` on empty daemon starts pulling all the tags of busybox repo.

Regression point should be #21657 

ping @vdemeester

**Comment by HackToday** [comment]
yes, hit that in dev master branch

**Comment by vdemeester** [comment]
@tonistiigi ah damn, was wondering if it was just libcompose and other user of engine-api or even the engine. 

I've sent a fix here https://github.com/docker/engine-api/pull/205 that could be revisited without the 'all' part. Or I can do the same fix I did in libxompose. I'll look at this later today ;-)

**Comment by HackToday** [comment]
docker/engine-api#205 could be one option, also in docker before, we did
https://github.com/docker/docker/pull/21657/files#diff-3d537578e5c3f29c85ab371eb727e7c8L28
which docker side pass default tag if not specified.

**Comment by vdemeester** [comment]
@HackToday As said on docker/engine-api#205 :
> @stevvooe It would also be possible to not change anything in the engine, just handle the `all` attribute in `engine-api` and append or not the default tag — but I feel it makes it clearer by passing all to engine (although it changes the API and might be tricky to handle daemon wise for backward compatibilites..).

So the basic idea is making more clear than just "no tag == all tag" on the client api side, and, later on if we don't want to change the API, update the server API to be more clear.
