### ISSUE TITLE
Proposal add native zero-downtime update container mechanism

### ISSUE THREAD

**Issue by zh99998** [docker/docker#22249]
## Problem

update an app without downtime is a common requirement nowadays.
for now, smooth update a running container is complex.

I know docker firstly build for big business and there must be a load-balancer already then docker don't need to care about it. But docker is being a "standard" software distribution format and many small studio could also benefit from docker by platform independence and easier maintenance. 
For a single-node service, run a haproxy or nginx just to deal with the restart problem is unnecessary complex.
user request -> docker proxy -> haproxy -> docker proxy -> app server.
to deal with different ip, port and container name, maybe need extra service discovery mechanism.

it could be much simplify if docker proxy itself has a smooth restart function.
## Proposal

Add a native update image and container mechanism, which could do these things:
1. Rename old container to a temporary name (if necessary)
2. Stop listen old container. Already existed connections will go to these container, but don't accept new connections.
3. Run a new container with same parameters and expose ports.
4. Wait until all old connections finish(for UDP, timeout), close old container.

cli interface for example

``` bash
docker reload myapp
```

Since docker use iptables NAT to do forwarding, it could be easy to do "stop listen" things. iptables will only match first packet of each connection in NAT. then just process it by connection track. even iptables rule changes, already existed connection will be forward as old rules.

**Comment by cpuguy83** [comment]
This is already easily possible outside docker (and implemented in many different ways).

Also, since docker 1.10 already supports having a discovery name be backed by multiple containers.
To accomplish this you provide multiple containers on a network with the same network alias.
In Docker 1.10 it picks one randomly and uses that until it goes down.
In Docker 1.11 it does round-robin DNS.

**Comment by zh99998** [comment]
@cpuguy83 could you give some further more advice such as recommend some open source project implementation?

**Comment by cpuguy83** [comment]
https://github.com/kobolog/gorb
https://github.com/ehazlett/interlock

**Comment by zh99998** [comment]
Seems interlock uses haproxy/nginx, as gorb slide says it will cause 40% slower.
GORB... seems complex to use... maybe it's a good solution for me. and still much complex than a native one.

**Comment by vdemeester** [comment]
@zh99998 there is also tools like [traefik](https://github.com/containous/traefik), etc.. If we *follow* the separation on concern principles, a way to update with zero-downtime an app' is not the responsability of the docker engine but some tools over it (and morover, zero-downtime updates are different dependenty on the app & co. so really difficult to standardize).

**Comment by LK4D4** [comment]
It's possible with swarm mode I believe.
