### ISSUE TITLE
Docker stats showing container names (optionally?)

### ISSUE THREAD

**Issue by aanisimov** [docker/docker#22246]
What do you think of adding _container name_ to the output of docker stats command?

Adding a container name could be more informative to user and there will be no need to use workarounds like:
```
docker stats $(docker ps | awk '{if(NR>1) print $NF}')
```

```
docker --version
Docker version 1.11.0, build 4dc5990
```

**Comment by cpuguy83** [comment]
I think there's an open issue to add a `--format` to `docker stats` specifically for this.

**Comment by thaJeztah** [comment]
Looks like a duplicate of https://github.com/docker/docker/issues/20973, so I'll close this one

**Comment by faunus** [comment]
docker ps | awk '{if(NR>1) print $NF}' | xargs docker stats

**Comment by thaJeztah** [comment]
I opened a new PR for changing the default format to show `CONTAINER ID` (truncated) and `NAME` by default, and add a `--no-trunc` flag to docker stats. The PR was just merged, so will be in an upcoming Docker release (17.10 or 17.11); https://github.com/docker/cli/pull/565
