### ISSUE TITLE
Error response from daemon failed to create endpoint <> on network bridge: failed to set MTU on host interface vethxxxxx: invalid argument

### ISSUE THREAD

**Issue by AntAreS24** [docker/docker#22243]
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   8acee1b
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   8acee1b
 Built:
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 2
Server Version: 1.10.3
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.5.0-coreos-r1
Operating System: CoreOS 1010.1.0 (MoreOS)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 997.2 MiB
Name: master
ID: QNQT:L2CW:ROUB:GLKX:V5UV:DKJI:EPAT:A5TG:B5KL:UOFQ:JTNC:MVNS
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Vagrant script creating 1 master (running Kubernetes and a Docker registry) and 2 nodes (running docker images). All through VirtualBox.

**Steps to reproduce the issue:**
1. Do a 'vagrant up' at work.
2. Go home and do 'vagrant halt', then 'vagrant up'
3. in Master image, I run 'docker run -d -p 5000:5000 registry:2'

**Describe the results you received:**
I'm  getting a 
```
a3918b8c23286f4a46565edd562fb716bc025d4b2d7b040c29eeae8669b2a21d
docker: Error response from daemon: failed to create endpoint berserk_newton on network bridge: failed to set MTU on host interface veth45f9316: invalid argument.
```

While I can understand the network as changed between the work and home, I would expect the guest machine to "reset" the network config update halt/up of the vagrant script.

**Describe the results you expected:**
Is there a way to reset the network in the guest OS to avoid the "vagrant destroy" and "vagrant up" which takes a long time as I need to pull some (big) images from my company's docker registry.

**Comment by thaJeztah** [comment]
I don't think we can help you much here; you're using Vagrant, CoreOS and VirtualBox; none of these are something from this repository, so I suggest to ask this question in the issue tracker for one of those

**Comment by AntAreS24** [comment]
Thanks. I agree it's a mix of different products and therefore hard to figure out...

One work around is to stop the Vagrant VMs, restart my latop and start them again. It seems the hibernation I was doing on my laptop causes this issue.

**Comment by thaJeztah** [comment]
Yes, I think this is a VirtualBox issue, so not sure how it can be resolved in a different way

**Comment by aissat** [comment]
Output of `docker version`:
`Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   5604cbe
 Built:        Mon May  2 00:06:51 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   5604cbe
 Built:        Mon May  2 00:06:51 2016
 OS/Arch:      linux/amd64

`
Output of `docker info`:
`
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 5
Server Version: 1.11.1
Storage Driver: devicemapper
 Pool Name: docker-8:6-3160898-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.541 GB
 Data Space Total: 107.4 GB
 Data Space Available: 94.24 GB
 Metadata Space Used: 2.322 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.122 (2016-04-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.5.1-1-ARCH
Operating System: Antergos Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.609 GiB
Name: archost
ID: NPBP:MZFF:ISB7:6SSN:PU6H:GBF6:NWSO:F3KL:UV5M:S4S2:VLST:WTU7
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/

`
Output of `docker start b550b490a45f `:
`
Error response from daemon: failed to create endpoint admiring_darwin on network bridge: failed to add the host (vethe955b0a) <=> sandbox (veth250aedd) pair interfaces: operation not supported
Error: failed to start containers: b550b490a45f
`

**Comment by unixbhaskar** [comment]
I am encountering same error like mentioned above ...heck

`bhaskar@ArchLinux_12:58:31_Mon Jul 18:~>sudo docker run -d -p 5000:5000 --name registry registry:2
[sudo] password for bhaskar: 
ccf9156579dc4673d689aa101f896275163921d917b1143aac74008dfcdf4067
docker: Error response from daemon: failed to create endpoint registry on network bridge: failed to add the host (veth3995dd3) <=> sandbox (vethe432b93) pair interfaces: operation not supported.
`

**Comment by unixbhaskar** [comment]
Well , it was damn "virtualbox" module not loaded properly causing that troube after kernel update. 

Fix:
reboot the machine and voila!

`bhaskar@ArchLinux_13:56:39_Mon Jul 18:~>docker run -d -p 5000:5000 --name registry registry:2
c091161e01ee751b13c6136b7f3dc84e563704dcea4b435bcd17b2d70a30cb46
bhaskar@ArchLinux_13:56:47_Mon Jul 18:~>docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
c091161e01ee        registry:2          "/bin/registry serve "   7 seconds ago       Up 4 seconds        0.0.0.0:5000->5000/tcp   registry`

**Comment by csyntax** [comment]
I use Docker on RaspberryPi. On build image I have error 'failed to create endpoint gracious_archimedes on network bridge: failed to add the host (vethc33f967) <=> sandbox (vethc453c00) pair interfaces: operation not supported
'
