### ISSUE TITLE
docker 1.11 run container failed

### ISSUE THREAD

**Issue by vanloswang** [docker/docker#22250]
**Output of `docker version`:**

```
Client:
 Version:         1.11.0
 API version:     1.23
 Package version: docker-1.11-6.git69e6294.f21.mips64el
 Go version:      go1.6
 Git commit:      69e6294/1.11
 Built:           
 OS/Arch:         linux/mips64le

Server:
 Version:         1.11.0
 API version:     1.23
 Package version: docker-1.11-6.git69e6294.f21.mips64el
 Go version:      go1.6
 Git commit:      69e6294/1.11
 Built:           
 OS/Arch:         linux/mips64le
```

**Output of `docker info`:**

```

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Steps to reproduce the issue:**
1. wget http://mipsfedora.imgtec.com/development/22/mips64el/images/20150601/rootfs.tar.gz
2.tar xvf ../rootfs.tar.gz
3.tar -C ${rootfs}/ -c . | docker import - fedora-22
4.docker run --hostname='fedora-container' fedora-22 uname -a

**Describe the results you received:**
```
INFO[0229] {Action=start, ID=8ef8cec6993c5c0fe16d1b5afd351012604ce07a3882cf1d08068618c8db0e4e, LoginUID unknown, PID unknown, Config={Hostname=fedora-container, AttachStdin=false, AttachStdout=true, AttachStderr=true, Tty=false, OpenStdin=false, StdinOnce=false, Cmd=[uname -a], ArgsEscaped=false, Image=fedora-22, NetworkDisabled=false, Labels=map[]}, HostConfig={LogConfig={Type:journald Config:map[]}, NetworkMode=default, PortBindings=map[], RestartPolicy={Name:no MaximumRetryCount:0}, AutoRemove=false, DNS=[], DNSOptions=[], DNSSearch=[], Privileged=false, PublishAllPorts=false, ReadonlyRootfs=false, ShmSize=67108864, Resources={CPUShares:0 Memory:0 CgroupParent: BlkioWeight:0 BlkioWeightDevice:[] BlkioDeviceReadBps:[] BlkioDeviceWriteBps:[] BlkioDeviceReadIOps:[] BlkioDeviceWriteIOps:[] CPUPeriod:0 CPUQuota:0 CpusetCpus: CpusetMems: Devices:[] DiskQuota:0 KernelMemory:0 MemoryReservation:0 MemorySwap:0 MemorySwappiness:0xc820eb0df0 OomKillDisable:0xc820eb0dfa PidsLimit:0 Ulimits:[] CPUCount:0 CPUPercent:0 BlkioIOps:0 BlkioBps:0 SandboxSize:0}}} 
DEBU[0229] Calling POST /v1.23/containers/8ef8cec6993c5c0fe16d1b5afd351012604ce07a3882cf1d08068618c8db0e4e/start 
DEBU[0229] devmapper: activateDeviceIfNeeded(76ad21adffdbc452fa0dc0b1739e28f88d4ec9db71a9a72f213a25d09323b296) 
DEBU[0229] container mounted via layerStore: /var/lib/docker/devicemapper/mnt/76ad21adffdbc452fa0dc0b1739e28f88d4ec9db71a9a72f213a25d09323b296/rootfs 
DEBU[0229] Assigning addresses for endpoint serene_goldberg's interface on network bridge 
DEBU[0229] RequestAddress(LocalDefault/172.17.0.0/16, <nil>, map[]) 
DEBU[0229] Assigning addresses for endpoint serene_goldberg's interface on network bridge 
DEBU[0229] Programming external connectivity on endpoint serene_goldberg (5cab744f76947ed01329c169c1b4a3d52c1c4396425fd1b39cdbfff938eb254a) 
DEBU[0229] createSpec: cgroupsPath: system.slice:docker:8ef8cec6993c5c0fe16d1b5afd351012604ce07a3882cf1d08068618c8db0e4e 
DEBU[0230] Revoking external connectivity on endpoint serene_goldberg (5cab744f76947ed01329c169c1b4a3d52c1c4396425fd1b39cdbfff938eb254a) 
DEBU[0230] attach: stdout: end                          
DEBU[0230] attach: stderr: end                          
DEBU[0230] Releasing addresses for endpoint serene_goldberg's interface on network bridge 
DEBU[0230] ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.1) 
DEBU[0230] devmapper: UnmountDevice(hash=76ad21adffdbc452fa0dc0b1739e28f88d4ec9db71a9a72f213a25d09323b296) 
DEBU[0230] devmapper: Unmount(/var/lib/docker/devicemapper/mnt/76ad21adffdbc452fa0dc0b1739e28f88d4ec9db71a9a72f213a25d09323b296) 
DEBU[0231] devmapper: Unmount done                      
DEBU[0231] devmapper: deactivateDevice(76ad21adffdbc452fa0dc0b1739e28f88d4ec9db71a9a72f213a25d09323b296) 
DEBU[0231] devmapper: removeDevice START(docker-8:1-543519-76ad21adffdbc452fa0dc0b1739e28f88d4ec9db71a9a72f213a25d09323b296) 
DEBU[0231] devmapper: removeDevice END(docker-8:1-543519-76ad21adffdbc452fa0dc0b1739e28f88d4ec9db71a9a72f213a25d09323b296) 
DEBU[0231] devmapper: deactivateDevice END(76ad21adffdbc452fa0dc0b1739e28f88d4ec9db71a9a72f213a25d09323b296) 
DEBU[0231] devmapper: UnmountDevice(hash=76ad21adffdbc452fa0dc0b1739e28f88d4ec9db71a9a72f213a25d09323b296) END 
ERRO[0231] Handler for POST /v1.23/containers/8ef8cec6993c5c0fe16d1b5afd351012604ce07a3882cf1d08068618c8db0e4e/start returned error: rpc error: code = 2 desc = "oci runtime error: Cannot set property Delegate, or unknown property."
```
**Describe the results you expected:**
run docker container success.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by HackToday** [comment]
@vanloswang  could that  tar file be import and run successfully in docker `1.10.3` ? if that case, it maybe a regression issue for new containered integration issue.

**Comment by vanloswang** [comment]
@HackToday tried docker-1.9.1, report an similar error as follow:
DEBU[0000] devicemapper: driver version is 4.31.0       
DEBU[0000] Generated prefix: docker-8:1-543519          
DEBU[0000] devmapper: Checking for existence of the pool docker-8:1-543519-pool 
DEBU[0000] Pool doesn't exist. Creating it.             
DEBU[0000] [deviceset] loadDeviceFilesOnStart()         
DEBU[0000] Skipping file /var/lib/docker/devicemapper/metadata/.tmp859696340 
DEBU[0000] Loading data for file /var/lib/docker/devicemapper/metadata/0741c36f0de2de71bebdf039eed5a315bc027f69163512473c3f9a60733bfd4e 
DEBU[0000] Loading data for file /var/lib/docker/devicemapper/metadata/0741c36f0de2de71bebdf039eed5a315bc027f69163512473c3f9a60733bfd4e-init 
DEBU[0000] Loading data for file /var/lib/docker/devicemapper/metadata/1721ce431f71ffea141bb02fb92579be9a21deb9c35e18bc76e6fe8f67e5e657 
DEBU[0000] Loading data for file /var/lib/docker/devicemapper/metadata/5d84133652c592658b4fcc3120edaf9f619b2fc6587f7fc6fa91c8115be5d1a1 
DEBU[0000] Loading data for file /var/lib/docker/devicemapper/metadata/76ad21adffdbc452fa0dc0b1739e28f88d4ec9db71a9a72f213a25d09323b296 
DEBU[0000] Loading data for file /var/lib/docker/devicemapper/metadata/76ad21adffdbc452fa0dc0b1739e28f88d4ec9db71a9a72f213a25d09323b296-init 
DEBU[0000] Loading data for file /var/lib/docker/devicemapper/metadata/a7ca2ee429e2ba69dd184932e4a3185cf0320017995351c2af61f4185b1767d2 
DEBU[0000] Loading data for file /var/lib/docker/devicemapper/metadata/a7ca2ee429e2ba69dd184932e4a3185cf0320017995351c2af61f4185b1767d2-init 
DEBU[0000] Loading data for file /var/lib/docker/devicemapper/metadata/base 
DEBU[0000] Skipping file /var/lib/docker/devicemapper/metadata/deviceset-metadata 
DEBU[0000] Loading data for file /var/lib/docker/devicemapper/metadata/f664aae02ad09e03b06c192ef4f6360ce02b032022a6ce2ad6116e15399968e1 
DEBU[0000] Skipping file /var/lib/docker/devicemapper/metadata/transaction-metadata 
DEBU[0000] [deviceset] loadDeviceFilesOnStart() END     
DEBU[0000] [deviceset] constructDeviceIDMap()           
DEBU[0000] Added deviceId=7 to DeviceIdMap              
DEBU[0000] Added deviceId=2 to DeviceIdMap              
DEBU[0000] Added deviceId=8 to DeviceIdMap              
DEBU[0000] Added deviceId=3 to DeviceIdMap              
DEBU[0000] Added deviceId=5 to DeviceIdMap              
DEBU[0000] Added deviceId=4 to DeviceIdMap              
DEBU[0000] Added deviceId=6 to DeviceIdMap              
DEBU[0000] Added deviceId=1 to DeviceIdMap              
DEBU[0000] Added deviceId=10 to DeviceIdMap             
DEBU[0000] Added deviceId=9 to DeviceIdMap              
DEBU[0000] [deviceset] constructDeviceIDMap() END       
WARN[0000] Usage of loopback devices is strongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use `man docker` to refer to dm.thinpooldev section. 
DEBU[0000] activateDeviceIfNeeded()                     
DEBU[0000] UUID for device: /dev/mapper/docker-8:1-543519-base is:7089604f-69ac-40db-954c-499ef20bfe11 
DEBU[0000] [devmapper] deactivateDevice()               
DEBU[0000] [devmapper] removeDevice START(docker-8:1-543519-base) 
DEBU[0000] [devmapper] removeDevice END(docker-8:1-543519-base) 
DEBU[0000] [devmapper] deactivateDevice END()           
INFO[0000] [graphdriver] using prior storage driver "devicemapper" 
DEBU[0000] Using graph driver devicemapper              
DEBU[0000] Using default logging driver json-file       
DEBU[0000] Creating images graph                        
DEBU[0000] Restored 1 elements                          
DEBU[0000] Creating repository list                     
DEBU[0000] Option DefaultDriver: bridge                 
DEBU[0000] Option DefaultNetwork: bridge                
INFO[0000] Firewalld running: false                     
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -D PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -D PREROUTING] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -D OUTPUT] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -F DOCKER] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -X DOCKER] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -n -L DOCKER] 
DEBU[0000] /usr/sbin/iptables, [--wait -t nat -N DOCKER] 
DEBU[0000] /usr/sbin/iptables, [--wait -t filter -n -L DOCKER] 
DEBU[0000] Registering ipam provider: default           
DEBU[0000] releasing IPv4 pools from network bridge (46c4f5ced024b2f682390477db7066b635627c149d77fcccf1746e0f5bbcc163) 
DEBU[0000] ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.42.1) 
DEBU[0000] Retrieving bitmask (LocalDefault/172.17.0.0/16, 172.17.0.0/16) 
DEBU[0000] ReleasePool(LocalDefault/172.17.0.0/16)      
INFO[0000] Default bridge (docker0) is assigned with an IP address 172.17.42.1/16. Daemon option --bip can be used to set a preferred IP address 
DEBU[0000] Allocating IPv4 pools for network bridge (df065fbdb210f464533055c7ba40414bcd7cf4851ed2d7d76688ce03f4df382c) 
DEBU[0000] RequestPool(LocalDefault, 172.17.42.1/16, , map[], false) 
DEBU[0001] RequestAddress(LocalDefault/172.17.0.0/16, 172.17.42.1, map[]) 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -C POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE] 
DEBU[0001] /usr/sbin/iptables, [--wait -D FORWARD -i docker0 -o docker0 -j DROP] 
DEBU[0001] /usr/sbin/iptables, [--wait -t filter -C FORWARD -i docker0 -o docker0 -j ACCEPT] 
DEBU[0001] /usr/sbin/iptables, [--wait -t filter -C FORWARD -i docker0 ! -o docker0 -j ACCEPT] 
DEBU[0001] /usr/sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT] 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -C PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8] 
DEBU[0001] /usr/sbin/iptables, [--wait -t nat -A OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8] 
DEBU[0001] /usr/sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -j DOCKER] 
DEBU[0001] Cleaning up old shm/mqueue mounts: start.    
DEBU[0001] Cleaning up old shm/mqueue mounts: done.     
DEBU[0001] Loaded container 0741c36f0de2de71bebdf039eed5a315bc027f69163512473c3f9a60733bfd4e 
ERRO[0001] Failed to load container 8ef8cec6993c5c0fe16d1b5afd351012604ce07a3882cf1d08068618c8db0e4e: open /var/lib/docker/containers/8ef8cec6993c5c0fe16d1b5afd351012604ce07a3882cf1d08068618c8db0e4e/config.json: no such file or directory 
ERRO[0001] Failed to load container ed9d0ca50cfb4778cadeb07c4766a7182c102a24055e5d7cabdb142a96a0f10f: open /var/lib/docker/containers/ed9d0ca50cfb4778cadeb07c4766a7182c102a24055e5d7cabdb142a96a0f10f/config.json: no such file or directory 
DEBU[0001] docker group found. gid: 1001                
DEBU[0001] Server created for HTTP on unix (/var/run/docker.sock) 
INFO[0001] Daemon has completed initialization          
INFO[0001] Docker daemon                                 commit=ee06d03/1.9.1 execdriver=native-0.2 graphdriver=devicemapper version=1.9.1
INFO[0001] API listen on /var/run/docker.sock           
DEBU[0001] Registering routers                          
DEBU[0001] Registering HEAD, /containers/{name:.*}/archive 
DEBU[0001] Registering OPTIONS, /                       
DEBU[0001] Registering GET, /_ping                      
DEBU[0001] Registering GET, /events                     
DEBU[0001] Registering GET, /info                       
DEBU[0001] Registering GET, /version                    
DEBU[0001] Registering GET, /images/json                
DEBU[0001] Registering GET, /images/search              
DEBU[0001] Registering GET, /images/get                 
DEBU[0001] Registering GET, /images/{name:.*}/get       
DEBU[0001] Registering GET, /images/{name:.*}/history   
DEBU[0001] Registering GET, /images/{name:.*}/json      
DEBU[0001] Registering GET, /images/{name:.*}/tags      
DEBU[0001] Registering GET, /containers/json            
DEBU[0001] Registering GET, /containers/{name:.*}/export 
DEBU[0001] Registering GET, /containers/{name:.*}/changes 
DEBU[0001] Registering GET, /containers/{name:.*}/json  
DEBU[0001] Registering GET, /containers/{name:.*}/top   
DEBU[0001] Registering GET, /containers/{name:.*}/logs  
DEBU[0001] Registering GET, /containers/{name:.*}/stats 
DEBU[0001] Registering GET, /containers/{name:.*}/attach/ws 
DEBU[0001] Registering GET, /exec/{id:.*}/json          
DEBU[0001] Registering GET, /containers/{name:.*}/archive 
DEBU[0001] Registering GET, /volumes                    
DEBU[0001] Registering GET, /volumes/{name:.*}          
DEBU[0001] Registering POST, /auth                      
DEBU[0001] Registering POST, /commit                    
DEBU[0001] Registering POST, /build                     
DEBU[0001] Registering POST, /images/create             
DEBU[0001] Registering POST, /images/load               
DEBU[0001] Registering POST, /images/{name:.*}/push     
DEBU[0001] Registering POST, /images/{name:.*}/tag      
DEBU[0001] Registering POST, /containers/create         
DEBU[0001] Registering POST, /containers/{name:.*}/kill 
DEBU[0001] Registering POST, /containers/{name:.*}/pause 
DEBU[0001] Registering POST, /containers/{name:.*}/unpause 
DEBU[0001] Registering POST, /containers/{name:.*}/restart 
DEBU[0001] Registering POST, /containers/{name:.*}/start 
DEBU[0001] Registering POST, /containers/{name:.*}/stop 
DEBU[0001] Registering POST, /containers/{name:.*}/wait 
DEBU[0001] Registering POST, /containers/{name:.*}/resize 
DEBU[0001] Registering POST, /containers/{name:.*}/attach 
DEBU[0001] Registering POST, /containers/{name:.*}/copy 
DEBU[0001] Registering POST, /containers/{name:.*}/exec 
DEBU[0001] Registering POST, /exec/{name:.*}/start      
DEBU[0001] Registering POST, /exec/{name:.*}/resize     
DEBU[0001] Registering POST, /containers/{name:.*}/rename 
DEBU[0001] Registering POST, /volumes/create            
DEBU[0001] Registering PUT, /containers/{name:.*}/archive 
DEBU[0001] Registering DELETE, /containers/{name:.*}    
DEBU[0001] Registering DELETE, /images/{name:.*}        
DEBU[0001] Registering DELETE, /volumes/{name:.*}       
DEBU[0001] Registering GET, /networks                   
DEBU[0001] Registering GET, /networks/{id:.*}           
DEBU[0001] Registering POST, /networks/create           
DEBU[0001] Registering POST, /networks/{id:.*}/connect  
DEBU[0001] Registering POST, /networks/{id:.*}/disconnect 
DEBU[0001] Registering DELETE, /networks/{id:.*}        
DEBU[0004] Calling POST /v1.21/containers/create        
DEBU[0004] POST /v1.21/containers/create                
INFO[0004] {Action=create, Username=root, LoginUID=0, PID=18802} 
DEBU[0004] [deviceset] AddDevice(hash=79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822-init basehash=1721ce431f71ffea141bb02fb92579be9a21deb9c35e18bc76e6fe8f67e5e657) 
DEBU[0005] registerDevice(11, 79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822-init) 
DEBU[0005] [deviceset] AddDevice(hash=79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822-init basehash=1721ce431f71ffea141bb02fb92579be9a21deb9c35e18bc76e6fe8f67e5e657) END 
DEBU[0005] activateDeviceIfNeeded(79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822-init) 
DEBU[0005] [devmapper] UnmountDevice(hash=79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822-init) 
DEBU[0005] [devmapper] Unmount(/var/lib/docker/devicemapper/mnt/79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822-init) 
DEBU[0006] [devmapper] Unmount done                     
DEBU[0006] [devmapper] deactivateDevice(79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822-init) 
DEBU[0006] [devmapper] removeDevice START(docker-8:1-543519-79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822-init) 
DEBU[0006] [devmapper] removeDevice END(docker-8:1-543519-79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822-init) 
DEBU[0006] [devmapper] deactivateDevice END(79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822-init) 
DEBU[0006] [devmapper] UnmountDevice(hash=79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822-init) END 
DEBU[0006] [deviceset] AddDevice(hash=79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822 basehash=79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822-init) 
DEBU[0006] registerDevice(12, 79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822) 
DEBU[0006] [deviceset] AddDevice(hash=79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822 basehash=79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822-init) END 
DEBU[0006] activateDeviceIfNeeded(79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822) 
DEBU[0007] [devmapper] UnmountDevice(hash=79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822) 
DEBU[0007] [devmapper] Unmount(/var/lib/docker/devicemapper/mnt/79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822) 
DEBU[0008] [devmapper] Unmount done                     
DEBU[0008] [devmapper] deactivateDevice(79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822) 
DEBU[0008] [devmapper] removeDevice START(docker-8:1-543519-79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822) 
DEBU[0008] [devmapper] removeDevice END(docker-8:1-543519-79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822) 
DEBU[0008] [devmapper] deactivateDevice END(79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822) 
DEBU[0008] [devmapper] UnmountDevice(hash=79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822) END 
DEBU[0008] Calling POST /v1.21/containers/79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822/attach 
DEBU[0008] POST /v1.21/containers/79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822/attach?stderr=1&stdout=1&stream=1 
INFO[0008] {Action=attach, ID=79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822, Username=root, LoginUID=0, PID=18802} 
DEBU[0008] attach: stdout: begin                        
DEBU[0008] attach: stderr: begin                        
DEBU[0008] Calling POST /v1.21/containers/79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822/start 
DEBU[0008] POST /v1.21/containers/79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822/start 
INFO[0008] {Action=start, ID=79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822, Username=root, LoginUID=0, PID=18802, Config={Hostname=fedora-container, AttachStdin=false, AttachStdout=true, AttachStderr=true, Tty=false, OpenStdin=false, StdinOnce=false, Cmd={parts:[/bin/bash -c echo 111]}, Image=fedora-22, NetworkDisabled=false, Labels=map[], StopSignal=SIGTERM}, HostConfig={LxcConf={values:[]}, OomKillDisable=false, MemorySwappiness=-1, Privileged=false, PortBindings=map[], PublishAllPorts=false, DNS=[], DNSOptions=[], DNSSearch=[], Devices=[], NetworkMode=default, RestartPolicy={Name:no MaximumRetryCount:0}, ReadonlyRootfs=false, LogConfig={Type:json-file Config:map[]}, ShmSize=67108864}} 
DEBU[0008] activateDeviceIfNeeded(79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822) 
DEBU[0008] Assigning addresses for endpoint thirsty_hodgkin's interface on network bridge 
DEBU[0008] RequestAddress(LocalDefault/172.17.0.0/16, <nil>, map[]) 
DEBU[0008] Assigning addresses for endpoint thirsty_hodgkin's interface on network bridge 
WARN[0009] signal: killed                               
DEBU[0009] attach: stderr: end                          
DEBU[0009] attach: stdout: end                          
DEBU[0009] Releasing addresses for endpoint thirsty_hodgkin's interface on network bridge 
DEBU[0009] ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.1) 
DEBU[0009] [devmapper] UnmountDevice(hash=79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822) 
DEBU[0009] [devmapper] Unmount(/var/lib/docker/devicemapper/mnt/79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822) 
DEBU[0010] [devmapper] Unmount done                     
DEBU[0010] [devmapper] deactivateDevice(79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822) 
DEBU[0010] [devmapper] removeDevice START(docker-8:1-543519-79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822) 
DEBU[0010] [devmapper] removeDevice END(docker-8:1-543519-79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822) 
DEBU[0010] [devmapper] deactivateDevice END(79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822) 
DEBU[0010] [devmapper] UnmountDevice(hash=79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822) END 
WARN[0010] failed to cleanup ipc mounts:
failed to umount /var/lib/docker/containers/79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822/shm: invalid argument
failed to umount /var/lib/docker/containers/79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822/mqueue: invalid argument 
DEBU[0010] [devmapper] UnmountDevice(hash=79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822) 
DEBU[0010] [devmapper] UnmountDevice(hash=79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822) END 
ERRO[0010] Error unmounting device 79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822: UnmountDevice: device not-mounted id 79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822 
ERRO[0010] Handler for POST /v1.21/containers/79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822/start returned error: Cannot start container 79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822: [8] System error: Cannot set property Delegate, or unknown property. 
ERRO[0010] HTTP Error                                    err=Cannot start container 79cf0dc4ce10af23827e842bd4099d54374134a392b6a2041380dd121a94e822: [8] System error: Cannot set property Delegate, or unknown property. statusCode=500

**Comment by vanloswang** [comment]
@HackToday 1.10.2 also report such an error.

**Comment by thaJeztah** [comment]
mips64le is currently not a supported architecture, and we cannot help you with that, because we don't build, test, or have access to that architecture. If you're trying to build docker for mips64le, the docker-dev Google group, or the #docker-Dev IRC channel may be better locations to discuss, although I'm not sure if there's anyone there testing on mips64 as well
