### ISSUE TITLE
"docker volume ls" slow since Docker Engine 1.10

### ISSUE THREAD

**Issue by mcanevet** [docker/docker#22251]
**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:38:59 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:38:59 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /mnt/data/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.2.0-34-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.56 GiB
Name: wrk43
ID: JOXK:CVEL:COP7:VAPM:XQT6:2K3E:MFVW:OKTF:CUNA:XRNR:VPH5:BGGS
Docker Root Dir: /mnt/data/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Desktop machine on Ubuntu 15.10

**Steps to reproduce the issue:**
1. Ugrade docker-engine from 1.9.1 to any newer version
2. Run `time docker volume ls`

**Describe the results you received:**

It takes 15 seconds to list 0 volumes (fresh Docker installation)

**Describe the results you expected:**

It should return instantaneously

**Additional information you deem important (e.g. issue happens only occasionally):**

A downgrade to 1.9.1 fixes the issue.
I also tried with 1.10.0, 1.10.1, 1.10.2, 1.10.3 and 1.11.0, all releases are broken.

**Comment by cpuguy83** [comment]
Do you have any volume plugins loaded?
This would be the only reason it would be slow.

**Comment by mcanevet** [comment]
@cpuguy83 I didn't do something special. At least I want to use only `local` volume driver. How can I check if I accidentally loaded a volume plugin?

**Comment by cpuguy83** [comment]
@mcanevet Check if there are any files/sockets in `/var/run/docker/plugins` or `/etc/docker/plugins`

**Comment by mcanevet** [comment]
@cpuguy83 that was it! Thanks
