### ISSUE TITLE
Copy file from client

### ISSUE THREAD

**Issue by AndreKR** [docker/docker#22284]
I am not sure if this is a support question, a documentation bug or a feature request...

When I use `docker cp` I get an error: `Error response from daemon: not a directory`. I am using docker on Windows, so the docker daemon is inside the *docker-machine*-managed VM.

The docs for `cp` talk about copying files "between a container and the local filesystem", but from the error message I suspect this might mean the "local" filesystem of the docker daemon and not of the client?

Is there a way to copy files from the client to the container?

**Comment by AndreKR** [comment]
Nevermind, it does copy from the client.

My problem seems to be related to #20517.

**Comment by AndreKR** [comment]
The problem was that the file wasn't found on the local machine because the path was mangled by some part of that bash emulation cruft (might be MSYS, MinGW, bash, I have no idea). I fiddled around with `MSYS_NO_PATHCONV=1` and somehow got it working for that path.

**Comment by kidapu** [comment]
This also happnes to me on Ubuntu 14.04.

```
$ sudo docker cp test.png 8f08a846d259:/usr/test.png
Error response from daemon: not a directory
````
