### ISSUE TITLE
Unable to copy over hosts file into container: "device or resource busy"

### ISSUE THREAD

**Issue by Pysis868** [docker/docker#22281]
**Output of `docker version`:**

```
 docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 18:01:15 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 18:01:15 UTC 2015
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
~ docker info
Containers: 19
Images: 425
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 463
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.10-boot2docker
Operating System: Boot2Docker 1.8.3 (TCL 6.4); master : af8b089 - Mon Oct 12 18:56:54 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: NFC6:EMX4:IDVT:CLXD:M3O2:K4AM:QQTN:JEX5:CU6S:7HUC:M63D:VXYU
Debug mode (server): true
File Descriptors: 20
Goroutines: 45
System Time: 2016-04-24T17:22:06.908994288Z
EventsListeners: 1
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: pysis
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
~ docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM
default   *        virtualbox   Running   tcp://192.168.99.100:2376

~ docker-machine status default
Running
```

Running VirtualBox 5.0.6 r103037 on a MacBook Pro with OS X El Capitan 10.11.1.
There is 1 other virtual machine running alongside the Docker default machine.

**Steps to reproduce the issue:**
```
~ docker run -d -t -i --name ubuntu ubuntu
804a0f9cbf89fe02b28a562961519ccaec1981d72cca43ca171f039b6d889226

~ docker ps --filter "name=ubuntu"
CONTAINER ID        IMAGE               COMMAND             CREATED              STATUS              PORTS               NAMES
804a0f9cbf89        ubuntu              "/bin/bash"         About a minute ago   Up About a minute                       ubuntu

~ docker cp ubuntu:/etc/hosts ./
~

~ docker cp ./hosts ubuntu:/etc/hosts
Error response from daemon: Untar re-exec error: exit status 1: output: remove /hosts: device or resource busy

~ docker stop ubuntu
ubuntu

~ docker ps --filter "name=ubuntu"
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

~ docker cp ./hosts ubuntu:/etc/hosts
Error response from daemon: Untar re-exec error: exit status 1: output: remove /hosts: device or resource busy

~ docker cp ./hosts ubuntu:/etc/hosts2
~
```

**Describe the results you received:**
The second copy command did not work, with the following error: "device or resource busy".

**Describe the results you expected:**
For the second copy command to simply work.

**Additional information you deem important (e.g. issue happens only occasionally):**
Consistent with a target container I had wanted to initially perform this on, and also the sample container I used just for this issue.
Note I tried stopping the container to see if that would help, but it did not.
Copying over a file that does not already exist works fine.  Also works if it's not a file the system is using.
I tried finding duplicates of this issue, but only found the same error message in different situations.
Hopefully this issue should be simplistic enough to answer, so it can help understand why exactly this single part is failing.

**Comment by cpuguy83** [comment]
You cannot copy over `/etc/hosts`.
Docker provides the container with a custom `/etc/hosts` file.

You can overwrite this by using `-v /some/file:/etc/hosts` when creating the container.
You can also write to the file from inside the container.
You can also use the `--add-host` option when creating the container to add your own custom entries.

But you cannot copy over it. This is not something we can support, so closing.

**Comment by DavidAlexanderW** [comment]
In case anyone stumbles upon this: You can just copy over the hosts file on your host filesystem. This can be found using docker inspect under the "HostsPath" attribute(`/var/lib/docker/containers/<container_id>/hosts` for me). Just be aware that removing the default hosts might have some unwanted consequences.
