### ISSUE TITLE
how to run container with non-root user

### ISSUE THREAD

**Issue by yanren** [docker/docker#22292]
I expect run container with a non-root user, So I use the following command:
docker run -it -v /work:/work -v /remote:/remote --expose 55555 --user=2000 yanren/suse12:1.0 /bin/bash
I execute the script "run_agent", then I check the process
I have no name!@1bc1e0c079f6:/work> ps -ef | grep agent
2000        17     1  0 09:55 ?        00:00:00 /bin/sh /remote/quasr4/quasr/release/agents_2.7/linux/bin/run_agent
root        38    17  0 09:55 ?        00:00:00 /remote/quasr4/quasr/release/agents_2.7/linux/bin/agent -I /tmp/agent_interfaces.55555 -S agent_1

why the owner of run_agent is 2000 that is my assigned user, but the owner of subprocess is root?

**Comment by thaJeztah** [comment]
What does the `run_agent` script look like? Also, can you provide information about your setup (`docker version` and `docker info`)

**Comment by yanren** [comment]
docker version:
 Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64


docker info:
  Containers: 6
Images: 23
Storage Driver: devicemapper
 Pool Name: docker-254:2-1802243-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 11.52 GB
 Data Space Total: 107.4 GB
 Data Space Available: 20.47 GB
 Metadata Space Used: 7.651 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.14 GB
 Udev Sync Supported: true
 Data loop file: /docker/devicemapper/devicemapper/data
 Metadata loop file: /docker/devicemapper/devicemapper/metadata
 Library Version: 1.03.01 (2011-10-15)
Execution Driver: native-0.2
Kernel Version: 3.12.48-52.27-default
Operating System: SUSE Linux Enterprise Server 12
CPUs: 6
Total Memory: 11.75 GiB
Name: mo-27fee68c8
ID: HMWL:7MDL:HCFE:GKXI:WDHT:JTW4:KZ3I:TVJ6:2FLB:UEE7:QNXL:A2IO
WARNING: No swap limit support

the script looks like:
 # Close stdin because some shells try to read unnecessarily, causing
# run_agent to hang
exec < /dev/null
# Set umask in case agent is restarted by different user
umask 002
#write interface file
echo "***********************" >> interfaces 
HOSTNAME=`hostname`
agent_name=agent_$HOSTNAME
/remote/quasr4/quasr/release/agents_2.7/linux/bin/agent -I $interfaces_file -S $agent_name >> run_agent.out 2>&1

**Comment by yanren** [comment]
ok, It seems about my script, because i set 's' bit on agent program. 

thanks
