### ISSUE TITLE
logs-opts seems broken in daemon.json

### ISSUE THREAD

**Issue by pcarrier** [docker/docker#22311]
Docker 1.10.3, binary from https://get.docker.com/builds/Linux/x86_64/docker-1.10.3

```
# cat /etc/docker/daemon.json
{ "log-opts": [ "env=FOO" ] }
# docker daemon
unable to configure the Docker daemon with file /etc/docker/daemon.json: json: cannot unmarshal array into Go value of type map[string]string
```

See https://github.com/docker/docker/issues/22309 for a similar issue.

**Comment by brandonstevens** [comment]
The following works on master:

```
{ "log-opts": { "env": "FOO" } }
```

```
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   ba372df
 Built:        Tue May 31 13:26:49 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   ba372df
 Built:        Tue May 31 13:26:49 2016
 OS/Arch:      linux/amd64
```

Also, I'm currently using this successfully to set syslog options on `1.11.1`:

```
{
  "log-driver": "syslog",
  "log-opts": {
    "tag": "{{.Name}}"
},
  "userland-proxy": false
}
```

```Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64
```

Is this an implementation or a documentation issue?

**Comment by pcarrier** [comment]
Well, whether it's an implementation or documentation issue depends on which you think should be right.

The documentation at https://docs.docker.com/engine/reference/commandline/daemon/#daemon-configuration-file says `	"log-opts": [],` and the code takes maps.

Pick whichever it should be and fix the other? :)

**Comment by uditjh** [comment]
not working on Windows. Any ideas? RUnning latest 18.09.0 version

![image](https://user-images.githubusercontent.com/7944262/54327730-80a89200-45e1-11e9-80d7-10d719f70481.png)

**Comment by thaJeztah** [comment]
@uditjh could you open a ticket in the docker for windows issue tracker? https://github.com/docker/for-win/

That message comes from the validation in the docker for windows UI, so it looks like there may be a regression in that validation.
