### ISSUE TITLE
Make --insecure-registry option to be reconfigurable without restart

### ISSUE THREAD

**Issue by apakhomov** [docker/docker#22332]
Due to issue comment https://github.com/docker/docker/issues/8887#issuecomment-214714813

As far as now there is no mechanism of working (adding, pulling) with insecure registries without docker and containers restarting, It would be useful if --insecure-registry option was added to the list of configuration changes that can be updated without restarting (https://docs.docker.com/engine/reference/commandline/daemon/#configuration-reloading) 

Thank you in advance for considering this issue!

**Comment by thaJeztah** [comment]
Thanks for opening!

**Comment by justincormack** [comment]
@thaJeztah there was a discussion about making it a `docker run` option but I can't find it right now. I don't think it would be very difficult to add it to the options that can be changed without a restart as it does not have to do very much; it was not in the `daemon.json` at all until 1.11 so I guess it was not considered until now.

**Comment by allencloud** [comment]
Now, docker 1.11.0 supports 3 kinds of configuration in config reload:
* debug
* labels
* cluster discovery
It is not very hard to support `insecure-registry`.
