### ISSUE TITLE
Build  hello-sample timeout

### ISSUE THREAD

**Issue by tezhao** [docker/docker#22349]
**Output of `docker version`:**
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.2.1
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.2.1
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

```
(paste your output here)
```
root@terry-VirtualBox:/home/terry/docker/docker-node-hello-master# docker build -t example/docker-node-hello:latest . 
Sending build context to Docker daemon  16.9 kB
Sending build context to Docker daemon 
Step 0 : FROM node:0.10
Pulling repository node
INFO[0132] Get https://index.docker.io/v1/repositories/library/node/images: dial tcp 52.72.231.247:443: connection timed out

**Output of `docker info`:**
root@terry-VirtualBox:/home/terry/docker/docker-node-hello-master# docker build -t example/docker-node-hello:latest . 
```
(paste your output here)
```
Sending build context to Docker daemon  16.9 kB
Sending build context to Docker daemon 
Step 0 : FROM node:0.10
Pulling repository node
INFO[0132] Get https://index.docker.io/v1/repositories/library/node/images: dial tcp 52.72.231.247:443: connection timed out
**Additional environment details (AWS, VirtualBox, physical, etc.):**
VirtualBox

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
Connection timed out

**Describe the results you expected:**
Successfully build

**Additional information you deem important (e.g. issue happens only occasionally):**
When I use "git clone" command to get hello-sample, it return the same error message "Connection timeout".Maybe Virtual machine can't build image?

**Comment by programmerq** [comment]
Are you able to do `curl https://index.docker.io/v1/repositories/library/node/images` ? I am able to get to that URL. Usually a connection timeout is related to a temporary issue somewhere between your computer and the server you are reaching, and not necessarily with the server itself.

**Comment by thaJeztah** [comment]
Yes, looking at this error, I suspect this is something in your network configuration, or the configuration of your Virtual Machine. Also note that you're running quite an old version of Docker, and if possible, I'd consider upgrading to a newer version.

I'll close this issue, because this isn't a bug in Docker, but feel free to comment after I closed

**Comment by tezhao** [comment]
Thank you
