### ISSUE TITLE
assigned container IPs respond within docker-machine, but not from docker-host.. 

### ISSUE THREAD

**Issue by jwdeitch** [docker/docker#22341]
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 98
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 167
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.19-boot2docker
Operating System: Boot2Docker 1.10.3 (TCL 6.4.1); master : 625117e - Thu Mar 10 22:09:02 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.1 MiB
Name: default
ID: JI7I:SIJQ:K2KA:BIVS:74NT:P4BF:6MO6:4Z4X:BBVS:KZWK:6ESK:FQRA
Debug mode (server): true
 File Descriptors: 70
 Goroutines: 95
 System Time: 2016-04-26T19:24:01.779823203Z
 EventsListeners: 1
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbo
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

virtual box

**Steps to reproduce the issue:**
1. run a container on a custom network with an assigned IP (`--net=isolated_nw --ip=172.25.3.3`), have a http handler respond on port 80 or something
2. curl (assigned IP) from WITHIN docker-machine and observe a good response
3. curl (assigned IP) from HOST and observe that IP lookup fails

**Additional information you deem important (e.g. issue happens only occasionally):**
The network should be shared with the host machine. If I can hit an IP from within docker-machine, I should be able to from within the host. VirtualBox really should be network transparent (?)

**Comment by ehazlett** [comment]
@jwdeitch the issue you are running into is because the machine is using a network that is not accessible by your host.  you can create a new host only network that the machines will use to access.  here is an issue describing something similar. https://github.com/docker/machine/issues/710.  if you continue to access issues please open an issue there.  thanks!
