### ISSUE TITLE
Centos 7.2.1511 Write permission denied  in container host mounted directory

### ISSUE THREAD

**Issue by AlehFiliutsich** [docker/docker#22348]
In last updated Centos 7 I got trouble with docker 1.8.2 and 1.9.1 in read only access to container host mounted directories. Some time ago all work fine but not now.
With  --privileged option I got successful read-write but it not solution.

**Output of `docker version`:**

```
Client:
 Version:      1.8.2-el7.centos
 API version:  1.20
 Package Version: docker-1.8.2-10.el7.centos.x86_64
 Go version:   go1.4.2
 Git commit:   a01dc02/1.8.2
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2-el7.centos
 API version:  1.20
 Package Version:
 Go version:   go1.4.2
 Git commit:   a01dc02/1.8.2
 Built:
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 2
Images: 32
Storage Driver: devicemapper
 Pool Name: docker--vg-docker--pool
 Pool Blocksize: 524.3 kB
 Backing Filesystem: extfs
 Data file:
 Metadata file:
 Data Space Used: 890.8 MB
 Data Space Total: 21.45 GB
 Data Space Available: 20.56 GB
 Metadata Space Used: 462.8 kB
 Metadata Space Total: 54.53 MB
 Metadata Space Available: 54.06 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-327.13.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 4
Total Memory: 14.69 GiB
Name: ECSC001046CD
ID: MQ2P:VRRW:IQXS:YCCH:U3ME:BQCH:XI7A:K7ZC:X37N:6ZQA:UUXG:3T7N
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I use Centos 7.2.1511

**Steps to reproduce the issue:**
0. yum update
1. yum install docker-1.8.2-10.el7.centos
2. systemctl start docker
3.  # mkdir 123
4. # docker run -it --rm -v `pwd`/123:/bla postgres:9.4.4 bin/bash                                                    
5. root@ca6f1ba6ce22:/# mkdir /bla/sdfsdf

**Describe the results you received:**
mkdir: cannot create directory ‘/bla/sdfsdf’: Permission denied

**Describe the results you expected:**
created folder

**Comment by fy2462** [comment]
Please add the parameter --privileged for root permission.

**Comment by AlehFiliutsich** [comment]
It's good practice for production?

**Comment by AlehFiliutsich** [comment]
It's cause selinux enabled in my centos. 
How I can use one host directory for two or more containers?

**Comment by cpuguy83** [comment]
@AlehFiliutsich On docker 1.8 you'll have to setup the labels on the host dir manually using chcon.
On docker 1.9 (?)+ you can use `docker run -v /foo:/bar:z`, where you can use either `z` or `Z`, one is for shared access, the other is to restrict it to only that container.

Closing as this is a non-issue.
