### ISSUE TITLE
At the same time perform 'docker exec' will fail

### ISSUE THREAD

**Issue by ztetfger** [docker/docker#22354]
**Output of `docker version`:**

```
Docker version 1.9.0, build 76d6bc9
```

**Output of `docker info`:**

```
Containers: 0
Images: 1
Server Version: 1.9.0
Storage Driver: devicemapper
 Pool Name: docker-253:1-1835919-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: extfs
 Data file: /dev/loop1
 Metadata file: /dev/loop2
 Data Space Used: 1.822 GB
 Data Space Total: 107.4 GB
 Data Space Available: 44.2 GB
 Metadata Space Used: 1.503 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.1.el7.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.create two containers
2.docker exec  container1
3.docker exec  container2

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment]
Please provide more details.

Neither the issue title or the issue description explain what's wrong, how to repro, or what you expected to see.

Thanks!

**Comment by thaJeztah** [comment]
Closing as we didn't receive more information
