### ISSUE TITLE
How to isolate the time of container and host

### ISSUE THREAD

**Issue by ztetfger** [docker/docker#22351]
**Output of `docker version`:**

```
Docker version 1.9.0, build 76d6bc9

```

**Output of `docker info`:**

```
Containers: 0
Images: 1
Server Version: 1.9.0
Storage Driver: devicemapper
 Pool Name: docker-253:1-1835919-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: extfs
 Data file: /dev/loop1
 Metadata file: /dev/loop2
 Data Space Used: 1.822 GB
 Data Space Total: 107.4 GB
 Data Space Available: 45.14 GB
 Metadata Space Used: 1.503 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.1.el7.x86_64
Operating System: ZTE Virtulization Environment i
CPUs: 2
Total Memory: 3.619 GiB
Name: A23207468
ID: TTVW:BON6:NA23:VECK:IMES:VOFN:A65U:M3B6:ZBHA:O6JN:KFFF:5OZX

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
centos7

**Steps to reproduce the issue:**
now，the time of container and host is is the same。
How to isolate the time of container and host?

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by hqhq** [comment]
I'm afraid it's not possible yet, it needs kernel support for time namespace, which is been discussed several years ago, and declined by community.

**Comment by cpuguy83** [comment]
Yep, not possible. Time is provided by the kernel. Unless there is some time namespacing in the future, this will not work.

In general though, I'm not sure what the use case would be around having different times between the container and the host.
You can set a custom timezone in a container (just follow the normal methods for the distro in the container to set that).
