### ISSUE TITLE
systemd: Consider supporting EnvironmentFile for configurable daemon options

### ISSUE THREAD

**Issue by jdub** [docker/docker#22359]
I have added the following fragment (which can serve as a diff of sorts!) to allow the use of an optional EnvironmentFile and OPTIONS environment variable to customise the Docker daemon parameters:

```ini
# /etc/systemd/system/docker.service.d/options.conf
[Service]
EnvironmentFile=-/etc/default/docker
ExecStart=
ExecStart=/usr/bin/docker daemon -H fd:// $OPTIONS
```

Here's my environment file, switching the log driver to journald:

```bash
# /etc/default/docker
OPTIONS="--log-driver=journald"
```

Something like this would come in handy for users who need to customise the daemon configuration. It's easier than adding a fragment, plus, a fragment would override any future upstream changes to ExecStart.

**Comment by phemmer** [comment]
The documentation covers how to customize the daemon options: https://docs.docker.com/engine/admin/systemd/#custom-docker-daemon-options

**Comment by jdub** [comment]
Yes, that page describes how to add a fragment (as you can see, it's way more involved), and how to check for an `EnvironmentFile=` line. But the [upstream-provided Debian/Ubuntu packages](https://docs.docker.com/engine/installation/linux/ubuntulinux/) do not include the `EnvironmentFile=` line or $OPTIONS variable on the `ExecStart=` line.

**Comment by cpuguy83** [comment]
As @phemmer said, you should use systemd dropins for this.
You can also provide daemon configuration in `/etc/docker/daemon.json`

**Comment by jdub** [comment]
Guys, my report *literally included* a fragment drop-in, as you've suggested.

But it *also* pointed out a disadvantage to that solution, especially when modifying the `ExecStart=` line: If upstream ever changes `ExecStart=`, anyone who modifies theirs with a fragment won't benefit from the change, and probably won't even notice it. Supporting `EnvironmentFile=` makes it easier for users to change daemon behaviour, and reduces the likelihood of missing future upstream changes.

Thanks for the alternative `/etc/docker/daemon.json` solution -- it's probably worthy of a comment in the service file, to discourage the use of fragments.
