### ISSUE TITLE
 container already connected to network host

### ISSUE THREAD

**Issue by ztetfger** [docker/docker#22355]
# docker run -itd --name=daisy --net=host 3d520813bc23
Error response from daemon: Cannot start container a45562812ee51574997aea5c4f2fbf2efcf2e7e724d1ec520d7a74add092ac60: container already connected to network host

# docker version 
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 18:00:05 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 18:00:05 UTC 2015
 OS/Arch:      linux/amd64

# docker info 
Containers: 1
Images: 2
Server Version: 1.9.0
Storage Driver: devicemapper
 Pool Name: docker-253:0-3016350-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.315 GB
 Data Space Total: 107.4 GB
 Data Space Available: 42.74 GB
 Metadata Space Used: 2.482 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-123.el7.x86_64
Operating System: ZTE Virtulization Environment i
CPUs: 32
Total Memory: 251.4 GiB
Name: host-62-1-1-4
ID: 3767:NGHI:U7LY:TO3V:BDFF:Y3HK:VPTF:BHOR:YOJO:IL2Y:F2GL:NDA7
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

# uname  -a 
Linux host-62-1-1-4 3.10.0-123.el7.x86_64 #1 SMP Tue Sep 15 09:49:32 CST 2015 x86_64 x86_64 x86_64 GNU/Linux

my machine is bare metal

reproduce procedure
1.Everytime when I create a container by  command "docker run -itd --name=daisy --net=host 3d520813bc23"

It seems that when i delete the container "daisy " last time,the engine did not  clean it in host  network.And I can create any other container without "--name=daisy".My solution is restart docker.service,and it works.I think it is a bug, anybody can help me  resolve it by fixing code?

**Comment by cpuguy83** [comment]
Any chance you can try upgrading to docker 1.11?
docker 1.9 is quite old, especially for networking related issues.

Also ping @aboch

**Comment by aboch** [comment]
@ztetfger I cannot reproduce this issue in latest docker (1.11.2, 1.12.1, master).
Can you confirm you are not able to reproduce as well, thanks.

**Comment by mavenugo** [comment]
ping @ztetfger. can you pls confirm ?

**Comment by thaJeztah** [comment]
I'll go ahead and close, but let us know if it's still an issue
