### ISSUE TITLE
Big IO make CONTAINER and docker daemon dead

### ISSUE THREAD

**Issue by cnsinger** [docker/docker#22363]
Hi, I’m in trouble.

When i `cat` some very big files in a container, i lost the container. And the greater trouble is that i can't `kill` or `stop` this container.
When i run `docker ps`, it hangs there,with nothing output.

I cant't `kill` or `stop` or `rm`. And no log or any error printed in the file `docker.log`.

But, restart the docker daemon can solve the problem which will kill all containers.

My docker info is here.
```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 323
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-254:0-9437188-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 5.398 GB
 Data Space Total: 107.4 GB
 Data Space Available: 76.15 GB
 Metadata Space Used: 13.18 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.134 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /home/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /home/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93 (2015-01-30)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.1.12-gentoo-ks
Operating System: Gentoo/Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.65 GiB
Name: cluster
ID: 4EQX:KLZW:LNML:7GRB:LIJE:RZ72:6O4Y:I7JB:2K4D:RHVR:PWOT:TBZ4
```
What can i do to prevent this problem? Or,just kill the trouble container not all containers.

Wish you help.

**Comment by vugit** [comment]
Perhaps if you keep the large files out on the host? This does not address
the underlying issue though!

-vu

**Comment by cpuguy83** [comment]
Can you provide an example?
When you say "cat a large file", I assume you mean catting it to the container's stdout?
What's the contents of this file?

**Comment by thaJeztah** [comment]
Closing, as we did not receive more information
