### ISSUE TITLE
oci runtime error: could not synchronise with container process: could not create session key: too many links

### ISSUE THREAD

**Issue by Ars27** [docker/docker#22366]
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:11:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:11:07 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 15
 Running: 0
 Paused: 0
 Stopped: 15
Images: 49
Server Version: 1.11.1
Storage Driver: vfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 2.6.32-openvz-042stab113.21-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 64
Total Memory: 4 GiB
Name: guest
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
WARNING: No oom kill disable support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Output of ```uname -r```
```
2.6.32-openvz-042stab113.21-amd64
```

**Steps to reproduce the issue:**
1.apt-get upgrade (from docker version 1.10.2)
2.run or build any container with docker

**Describe the results you received:**
ERROR: rpc error: code = 2 desc = "oci runtime error: could not synchronise with container process: could not create session key: too many links"

**Describe the results you expected:**
A sucessfully build docker container.

**Additional information you deem important (e.g. issue happens only occasionally):**
Tried to reboot system, restart docker, reinstall docker. Nothing worked.

On previous version 1.10.2 everything worked fine.

**Comment by cpuguy83** [comment]
I'm sorry, but this is not a supported kernel.
Looks like it's happening here: https://github.com/opencontainers/runc/blob/master/libcontainer/keys/keyctl.go#L30

You may want to run `https://github.com/docker/docker/blob/master/contrib/check-config.sh` on your system to see what may be missing (possibly `CONFIG_KEYS`
