### ISSUE TITLE
Docker 1.11.1 Start up containers using docker-compose, and container can't ping each other

### ISSUE THREAD

**Issue by ninchan8328** [docker/docker#22377]
**Output of `docker version`:**

Docker version 1.11.1, build 5604cbe
Same for Docker version 1.10.1, build 9e83765

**Output of `docker info`:**

```
docker info
Containers: 30
 Running: 2
 Paused: 0
 Stopped: 28
Images: 13
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 303
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.16.0-43-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 5.829 GiB
Name: rcdn6-vm81-112
ID: QINN:7PK3:HG3I:ZFAZ:XEDD:QEHB:E7JD:H3VU:CVXT:CJF4:TLQX:VMWE
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Http Proxy: http://proxy-wsa.esl.cisco.com:80
Https Proxy: https://proxy-wsa.esl.cisco.com:80
No Proxy: localhost, 127.0.0.1, ::1, /var/run/docker.sock, .docker, /var/run/docker.sock, .docker
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Ubuntu
Linux rcdn6-vm81-112 3.16.0-43-generic #58~14.04.1-Ubuntu SMP Mon Jun 22 10:21:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Steps to reproduce the issue:**
1. >>docker-compose -p testing -f testing.yml up -d
Creating testing_server01_1
Creating testing_server02_1

**Describe the results you received:**
Going in to one of the container, i can't ping other other container while they are on the same network.
ping IP address is okay but not the hostname.

```
docker exec -it testing_server01_1 bash
[root@server01 /]# ping server02
ping: unknown host server02
[root@server01 /]# ping server01
PING server01 (172.18.0.2) 56(84) bytes of data.
64 bytes from server01 (172.18.0.2): icmp_seq=1 ttl=64 time=0.030 ms
64 bytes from server01 (172.18.0.2): icmp_seq=2 ttl=64 time=0.058 ms
[root@server01 /]# ping 172.18.0.3
PING 172.18.0.3 (172.18.0.3) 56(84) bytes of data.
64 bytes from 172.18.0.3: icmp_seq=1 ttl=64 time=0.113 ms
64 bytes from 172.18.0.3: icmp_seq=2 ttl=64 time=0.097 ms
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
```
docker network inspect testing_default
[
    {
        "Name": "testing_default",
        "Id": "2177002b34276ff24c1b3e9aab5e4ddd5ec16f304f5a8a730c3209df0edbdc58",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1/16"
                }
            ]
        },
        "Internal": false,
        "Containers": {
            "0df8ac91c4be7c2c1421166e1413fd3aaafd806522d7210e625ed86ec58f1c40": {
                "Name": "testing_server01_1",
                "EndpointID": "a35a7a9bdbf26d26fc983e67a36f258b39fb41e264e1423eefbc28e450056304",
                "MacAddress": "02:42:ac:12:00:02",
                "IPv4Address": "172.18.0.2/16",
                "IPv6Address": ""
            },
            "970cdd09104ad8463a1f90a3278d0830afde136323f1167c60b0927f7f1d6216": {
                "Name": "testing_server02_1",
                "EndpointID": "3aaee561c82dc69868f00c2dd91b1a62552d194f9285dc50c9f0d74e8481baf6",
                "MacAddress": "02:42:ac:12:00:03",
                "IPv4Address": "172.18.0.3/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
```

**Comment by thaJeztah** [comment]
Can you try if;

pinging the other container by it's container-name (instead of alias) works? e.g.

    ping testing_server02_1

Inside the container, what does `cat /etc/resolv.conf` give you?

Trying to take docker-compose out of this, does this work correctly?

```
docker network create foobar
docker run -d --net foobar --name repro-22377 nginx:alpine
```

then, pinging that container from inside another container;

```
docker run -it --rm --net foobar alpine sh -c "ping -c 3 repro-22377"
```

**Comment by sanimej** [comment]
@ninchan8328 Are you seeing the same issue in 1.10.1 and 1.11.1 ?

**Comment by ninchan8328** [comment]
Here is the result:
[root@server01 /]# ping testing_server02_1
ping: unknown host testing_server02_1

[root@server01 /]# cat /etc/resolv.conf
search docker
nameserver 127.0.0.11
options timeout:1 attempts:1 ndots:0

Yes i am seeing the same issue on 1.10.1 and 1.11.1.

The try of creating the docker network and bring up the container using docker command works:
>>docker run -d --net foobar --name repro-22377 nginx:alpine
Unable to find image 'nginx:alpine' locally
alpine: Pulling from library/nginx
420890c9e918: Pull complete
a3ed95caeb02: Pull complete
74b9cd17dfd4: Pull complete
720dd8e79d74: Pull complete
2f9898934ae0: Pull complete
Digest: sha256:7e7b690fa25cbab8307295cf9673934c874a112cdac37b786b70a91dcd6da8f8
Status: Downloaded newer image for nginx:alpine
a5caf762d585536da89bf359ec3e651c7414b04ccb3cd72c8c7408408fad4a6e

rcdn6-vm81-112 ninchan
/users/ninchan
>>docker run -it --rm --net foobar alpine sh -c "ping -c 3 repro-22377"
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
420890c9e918: Already exists
Digest: sha256:9cacb71397b640eca97488cf08582ae4e4068513101088e9f96c9814bfda95e0
Status: Downloaded newer image for alpine:latest
PING repro-22377 (172.27.0.2): 56 data bytes
64 bytes from 172.27.0.2: seq=0 ttl=64 time=0.075 ms
64 bytes from 172.27.0.2: seq=1 ttl=64 time=0.121 ms
64 bytes from 172.27.0.2: seq=2 ttl=64 time=0.119 ms

--- repro-22377 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.075/0.105/0.121 ms


Just in case I do something stupid (i am new to this docker network thing), here is my yml file:
version: '2'

services:
  server01:
    image: local_image
    privileged: true
    hostname: server01
    stdin_open: true
    tty: true
    entrypoint: /root/init_container.sh
    command: /bin/bash
    ports:
      - 22
      - 5432
    expose:
      - "8030"
      - "9102"
      - "9103"
      - "2812"
      - "6001"
      - "6109"
      - "8037"
    external_links:
      - common_cassandra:cassandra

  server02:
    image: local_image
    privileged: true
    hostname: server02
    stdin_open: true
    tty: true
    entrypoint: /root/init_container.sh
    command: /bin/bash
    ports:
      - 22
      - 5432
    expose:
      - "8030"
      - "9102"
      - "9103"
      - "2812"
      - "6001"
      - "6109"
      - "8037"
    external_links:
      - common_cassandra:cassandra

networks:
  default:
    external:
      name: testing_default

**Comment by ninchan8328** [comment]
just in case you need this info:

>>docker-compose --version
docker-compose version 1.7.0, build 0d7bf73

**Comment by ninchan8328** [comment]
any update?

**Comment by sanimej** [comment]
I am able to recreate this. It might be something specific to your setup.

Can you run the daemon in debug mode (-D flag) and capture the logs when you ping across containers?

**Comment by ninchan8328** [comment]
sure i can do that, did you try the yml file i provided above?

**Comment by ninchan8328** [comment]
No log generated when i ping from container A to container B

Here is the yaml file i used:
>>cat example.yml
version: '2'
services:
    service_a:
        image: local_image
        container_name: server01
        hostname: server01
        entrypoint: /root/init_container.sh
        command: /bin/bash
        privileged: true
        stdin_open: true
        tty: true
        ports:
           - 8080:80
        networks:
          - front-tier
    service_b:
        image: local_image
        container_name: server02
        hostname: server02
        entrypoint: /root/init_container.sh
        command: /bin/bash
        privileged: true
        stdin_open: true
        tty: true
        ports:
            - 8081:80
        networks:
          - front-tier

networks:
  front-tier:
    driver: bridge

Here is the debug log when i bring up the container pairs
DEBU[0001] Registering routers
DEBU[0001] Registering HEAD, /containers/{name:.*}/archive
DEBU[0001] Registering GET, /containers/json
DEBU[0001] Registering GET, /containers/{name:.*}/export
DEBU[0001] Registering GET, /containers/{name:.*}/changes
DEBU[0001] Registering GET, /containers/{name:.*}/json
DEBU[0001] Registering GET, /containers/{name:.*}/top
DEBU[0001] Registering GET, /containers/{name:.*}/logs
DEBU[0001] Registering GET, /containers/{name:.*}/stats
DEBU[0001] Registering GET, /containers/{name:.*}/attach/ws
DEBU[0001] Registering GET, /exec/{id:.*}/json
DEBU[0001] Registering GET, /containers/{name:.*}/archive
DEBU[0001] Registering POST, /containers/create
DEBU[0001] Registering POST, /containers/{name:.*}/kill
DEBU[0001] Registering POST, /containers/{name:.*}/pause
DEBU[0001] Registering POST, /containers/{name:.*}/unpause
DEBU[0001] Registering POST, /containers/{name:.*}/restart
DEBU[0001] Registering POST, /containers/{name:.*}/start
DEBU[0001] Registering POST, /containers/{name:.*}/stop
DEBU[0001] Registering POST, /containers/{name:.*}/wait
DEBU[0001] Registering POST, /containers/{name:.*}/resize
DEBU[0001] Registering POST, /containers/{name:.*}/attach
DEBU[0001] Registering POST, /containers/{name:.*}/copy
DEBU[0001] Registering POST, /containers/{name:.*}/exec
DEBU[0001] Registering POST, /exec/{name:.*}/start
DEBU[0001] Registering POST, /exec/{name:.*}/resize
DEBU[0001] Registering POST, /containers/{name:.*}/rename
DEBU[0001] Registering POST, /containers/{name:.*}/update
DEBU[0001] Registering PUT, /containers/{name:.*}/archive
DEBU[0001] Registering DELETE, /containers/{name:.*}
DEBU[0001] Registering GET, /images/json
DEBU[0001] Registering GET, /images/search
DEBU[0001] Registering GET, /images/get
DEBU[0001] Registering GET, /images/{name:.*}/get
DEBU[0001] Registering GET, /images/{name:.*}/history
DEBU[0001] Registering GET, /images/{name:.*}/json
DEBU[0001] Registering POST, /commit
DEBU[0001] Registering POST, /images/create
DEBU[0001] Registering POST, /images/load
DEBU[0001] Registering POST, /images/{name:.*}/push
DEBU[0001] Registering POST, /images/{name:.*}/tag
DEBU[0001] Registering DELETE, /images/{name:.*}
DEBU[0001] Registering OPTIONS, /{anyroute:.*}
DEBU[0001] Registering GET, /_ping
DEBU[0001] Registering GET, /events
DEBU[0001] Registering GET, /info
DEBU[0001] Registering GET, /version
DEBU[0001] Registering POST, /auth
DEBU[0001] Registering GET, /volumes
DEBU[0001] Registering GET, /volumes/{name:.*}
DEBU[0001] Registering POST, /volumes/create
DEBU[0001] Registering DELETE, /volumes/{name:.*}
DEBU[0001] Registering POST, /build
DEBU[0001] Registering GET, /networks
DEBU[0001] Registering GET, /networks/{id:.*}
DEBU[0001] Registering POST, /networks/create
DEBU[0001] Registering POST, /networks/{id:.*}/connect
DEBU[0001] Registering POST, /networks/{id:.*}/disconnect
DEBU[0001] Registering DELETE, /networks/{id:.*}
INFO[0001] API listen on /var/run/docker.sock
DEBU[0003] containerd connection state change: READY
docker ps -a
DEBU[0073] Calling GET /v1.23/containers/json?all=1
DEBU[0119] Calling GET /v1.22/networks/ninchanupdm_front-tier
DEBU[0119] Calling GET /v1.22/containers/json?all=0&limit=-1&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dninchanupdm%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&size=0
DEBU[0119] Calling GET /v1.22/containers/json?all=1&limit=-1&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dninchanupdm%22%2C+%22com.docker.compose.service%3Dservice_a%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&size=0
DEBU[0119] Calling GET /v1.22/containers/2d33b5b32014af7e4a7be151eed9da3cec69b47186c03f5c2f939dba6ffefa31/json
DEBU[0119] Calling GET /v1.22/containers/json?all=1&limit=-1&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dninchanupdm%22%2C+%22com.docker.compose.service%3Dservice_b%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&size=0
DEBU[0119] Calling GET /v1.22/containers/a3f5965cfe301327de36df7ee66fd7689fbd7fba0fd37660b60fa19ff4bbd810/json
DEBU[0119] Calling GET /v1.22/images/local_image/json
DEBU[0119] Calling GET /v1.22/images/local_image/json
DEBU[0119] Calling GET /v1.22/containers/json?all=1&limit=-1&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dninchanupdm%22%2C+%22com.docker.compose.service%3Dservice_a%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&size=0
DEBU[0119] Calling GET /v1.22/containers/json?all=1&limit=-1&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dninchanupdm%22%2C+%22com.docker.compose.service%3Dservice_b%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&size=0
DEBU[0119] Calling POST /v1.22/containers/2d33b5b32014af7e4a7be151eed9da3cec69b47186c03f5c2f939dba6ffefa31/stop?t=10
ERRO[0119] Handler for POST /v1.22/containers/2d33b5b32014af7e4a7be151eed9da3cec69b47186c03f5c2f939dba6ffefa31/stop returned error: Container 2d33b5b32014af7e4a7be151eed9da3cec69b47186c03f5c2f939dba6ffefa31 is already stopped
DEBU[0119] Calling POST /v1.22/containers/a3f5965cfe301327de36df7ee66fd7689fbd7fba0fd37660b60fa19ff4bbd810/stop?t=10
ERRO[0119] Handler for POST /v1.22/containers/a3f5965cfe301327de36df7ee66fd7689fbd7fba0fd37660b60fa19ff4bbd810/stop returned error: Container a3f5965cfe301327de36df7ee66fd7689fbd7fba0fd37660b60fa19ff4bbd810 is already stopped
DEBU[0119] Calling POST /v1.22/containers/2d33b5b32014af7e4a7be151eed9da3cec69b47186c03f5c2f939dba6ffefa31/rename?name=2d33b5b32014_server01
DEBU[0119] Calling POST /v1.22/containers/a3f5965cfe301327de36df7ee66fd7689fbd7fba0fd37660b60fa19ff4bbd810/rename?name=a3f5965cfe30_server02
DEBU[0119] Calling GET /v1.22/containers/2d33b5b32014af7e4a7be151eed9da3cec69b47186c03f5c2f939dba6ffefa31/json
DEBU[0119] Calling GET /v1.22/containers/a3f5965cfe301327de36df7ee66fd7689fbd7fba0fd37660b60fa19ff4bbd810/json
DEBU[0119] Calling GET /v1.22/images/local_image/json
DEBU[0119] Calling GET /v1.22/images/local_image/json
DEBU[0119] Calling GET /v1.22/images/sha256%3A73e4e41bcb560903eafc53ec2a1c0bafff0c434f4766c5b21ae416d98b39d4a1/json
DEBU[0119] Calling GET /v1.22/images/local_image/json
DEBU[0119] Calling GET /v1.22/images/sha256%3A73e4e41bcb560903eafc53ec2a1c0bafff0c434f4766c5b21ae416d98b39d4a1/json
DEBU[0119] Calling GET /v1.22/images/local_image/json
DEBU[0119] Calling POST /v1.22/containers/create?name=server02
DEBU[0119] form data: {"AttachStderr":false,"AttachStdin":false,"AttachStdout":false,"Cmd":["/bin/bash"],"Entrypoint":["/root/init_container.sh"],"Env":["affinity:container==a3f5965cfe301327de36df7ee66fd7689fbd7fba0fd37660b60fa19ff4bbd810"],"ExposedPorts":{"80/tcp":{}},"HostConfig":{"Binds":["0cca9c4fc01bbb74e53af034d0e9bd3b1507871c02bdb04e5419039d41ad660f:/workspace:rw"],"Links":[],"LogConfig":{"Config":{},"Type":""},"NetworkMode":"ninchanupdm_front-tier","PortBindings":{"80/tcp":[{"HostIp":"","HostPort":"8081"}]},"Privileged":true,"VolumesFrom":[]},"Hostname":"server02","Image":"local_image","Labels":{"com.docker.compose.config-hash":"80f6c371f7f82faf53356d83625dbb8ea6d912f6158e79ceb9507f177bd702c6","com.docker.compose.container-number":"1","com.docker.compose.oneoff":"False","com.docker.compose.project":"ninchanupdm","com.docker.compose.service":"service_b","com.docker.compose.version":"1.7.0"},"NetworkDisabled":false,"OpenStdin":true,"StdinOnce":false,"Tty":true,"Volumes":{}}
DEBU[0119] Calling POST /v1.22/containers/create?name=server01
DEBU[0119] form data: {"AttachStderr":false,"AttachStdin":false,"AttachStdout":false,"Cmd":["/bin/bash"],"Entrypoint":["/root/init_container.sh"],"Env":["affinity:container==2d33b5b32014af7e4a7be151eed9da3cec69b47186c03f5c2f939dba6ffefa31"],"ExposedPorts":{"80/tcp":{}},"HostConfig":{"Binds":["21382367e71ea15bea56b9f53c6a031a3b99417a724d3166a6fe78c812a9f874:/workspace:rw"],"Links":[],"LogConfig":{"Config":{},"Type":""},"NetworkMode":"ninchanupdm_front-tier","PortBindings":{"80/tcp":[{"HostIp":"","HostPort":"8080"}]},"Privileged":true,"VolumesFrom":[]},"Hostname":"server01","Image":"local_image","Labels":{"com.docker.compose.config-hash":"d7b5c589857d2abe8437aa5043f0e4cc14e8bf1edeb59832c331d031af0428ce","com.docker.compose.container-number":"1","com.docker.compose.oneoff":"False","com.docker.compose.project":"ninchanupdm","com.docker.compose.service":"service_a","com.docker.compose.version":"1.7.0"},"NetworkDisabled":false,"OpenStdin":true,"StdinOnce":false,"Tty":true,"Volumes":{}}
DEBU[0119] container mounted via layerStore: /var/lib/docker/aufs/mnt/83e62094e720dde3b89a3e6c9c61192a53c34917b60abc11699eec06fa40628f
DEBU[0119] copying image data from 7bbd81406a854b4a7bef2b361ebf031589028928fd54027ede66b75b38d25a01:/workspace, to 0cca9c4fc01bbb74e53af034d0e9bd3b1507871c02bdb04e5419039d41ad660f
DEBU[0119] Calling GET /v1.22/containers/7bbd81406a854b4a7bef2b361ebf031589028928fd54027ede66b75b38d25a01/json
DEBU[0119] Calling POST /v1.22/networks/ninchanupdm_front-tier/disconnect
DEBU[0119] form data: {"container":"7bbd81406a854b4a7bef2b361ebf031589028928fd54027ede66b75b38d25a01"}
DEBU[0119] Calling POST /v1.22/networks/ninchanupdm_front-tier/connect
DEBU[0119] form data: {"Container":"7bbd81406a854b4a7bef2b361ebf031589028928fd54027ede66b75b38d25a01","EndpointConfig":{"Aliases":["7bbd81406a85","service_b"],"Links":null}}
DEBU[0119] Calling POST /v1.22/containers/7bbd81406a854b4a7bef2b361ebf031589028928fd54027ede66b75b38d25a01/start
DEBU[0119] form data: {}
DEBU[0119] container mounted via layerStore: /var/lib/docker/aufs/mnt/2811cbbc229622f8fec5c10f34872a2f92eb6503cbd12896f6a55a1747d96955
DEBU[0119] copying image data from 18d78fd6685e4b45d37c6b706b2df90e0c5a4a0cf7abad6df370f5edba485304:/workspace, to 21382367e71ea15bea56b9f53c6a031a3b99417a724d3166a6fe78c812a9f874
DEBU[0119] container mounted via layerStore: /var/lib/docker/aufs/mnt/83e62094e720dde3b89a3e6c9c61192a53c34917b60abc11699eec06fa40628f
DEBU[0119] Assigning addresses for endpoint server02's interface on network ninchanupdm_front-tier
DEBU[0119] RequestAddress(LocalDefault/172.29.0.0/16, <nil>, map[])
DEBU[0119] Calling GET /v1.22/containers/18d78fd6685e4b45d37c6b706b2df90e0c5a4a0cf7abad6df370f5edba485304/json
DEBU[0119] Assigning addresses for endpoint server02's interface on network ninchanupdm_front-tier
DEBU[0119] Calling POST /v1.22/networks/ninchanupdm_front-tier/disconnect
DEBU[0119] form data: {"container":"18d78fd6685e4b45d37c6b706b2df90e0c5a4a0cf7abad6df370f5edba485304"}
DEBU[0119] Programming external connectivity on endpoint server02 (b14825034aa90bf46adcaaa0b894799a581aeda11767604c5e3b3ecd34fc51cb)
DEBU[0119] /sbin/iptables, [--wait -t nat -A DOCKER -p tcp -d 0/0 --dport 8081 -j DNAT --to-destination 172.29.0.2:80 ! -i br-f157d7d7c298]
DEBU[0119] Calling POST /v1.22/networks/ninchanupdm_front-tier/connect
DEBU[0119] form data: {"Container":"18d78fd6685e4b45d37c6b706b2df90e0c5a4a0cf7abad6df370f5edba485304","EndpointConfig":{"Aliases":["18d78fd6685e","service_a"],"Links":null}}
DEBU[0119] Calling POST /v1.22/containers/18d78fd6685e4b45d37c6b706b2df90e0c5a4a0cf7abad6df370f5edba485304/start
DEBU[0119] form data: {}
DEBU[0119] /sbin/iptables, [--wait -t filter -A DOCKER ! -i br-f157d7d7c298 -o br-f157d7d7c298 -p tcp -d 172.29.0.2 --dport 80 -j ACCEPT]
DEBU[0119] /sbin/iptables, [--wait -t nat -A POSTROUTING -p tcp -s 172.29.0.2 -d 172.29.0.2 --dport 80 -j MASQUERADE]
DEBU[0119] container mounted via layerStore: /var/lib/docker/aufs/mnt/2811cbbc229622f8fec5c10f34872a2f92eb6503cbd12896f6a55a1747d96955
DEBU[0119] Assigning addresses for endpoint server01's interface on network ninchanupdm_front-tier
DEBU[0119] RequestAddress(LocalDefault/172.29.0.0/16, <nil>, map[])
DEBU[0119] Assigning addresses for endpoint server01's interface on network ninchanupdm_front-tier
DEBU[0119] Programming external connectivity on endpoint server01 (62af2e37001497c3448356896ada9788c3d726623dc78cc449901dd862f856a0)
DEBU[0119] /sbin/iptables, [--wait -t nat -A DOCKER -p tcp -d 0/0 --dport 8080 -j DNAT --to-destination 172.29.0.3:80 ! -i br-f157d7d7c298]
DEBU[0119] /sbin/iptables, [--wait -t filter -A DOCKER ! -i br-f157d7d7c298 -o br-f157d7d7c298 -p tcp -d 172.29.0.3 --dport 80 -j ACCEPT]
DEBU[0119] /sbin/iptables, [--wait -t nat -A POSTROUTING -p tcp -s 172.29.0.3 -d 172.29.0.3 --dport 80 -j MASQUERADE]
DEBU[0119] sandbox set key processing took 58.784637ms for container 7bbd81406a854b4a7bef2b361ebf031589028928fd54027ede66b75b38d25a01
DEBU[0119] received containerd event: &types.Event{Type:"start-container", Id:"7bbd81406a854b4a7bef2b361ebf031589028928fd54027ede66b75b38d25a01", Status:0x0, Pid:"", Timestamp:0x572d7867}
DEBU[0119] event unhandled: type:"start-container" id:"7bbd81406a854b4a7bef2b361ebf031589028928fd54027ede66b75b38d25a01" timestamp:1462597735
DEBU[0119] Calling DELETE /v1.22/containers/a3f5965cfe301327de36df7ee66fd7689fbd7fba0fd37660b60fa19ff4bbd810?link=False&force=False&v=False
DEBU[0119] sandbox set key processing took 97.185228ms for container 18d78fd6685e4b45d37c6b706b2df90e0c5a4a0cf7abad6df370f5edba485304
DEBU[0120] received containerd event: &types.Event{Type:"start-container", Id:"18d78fd6685e4b45d37c6b706b2df90e0c5a4a0cf7abad6df370f5edba485304", Status:0x0, Pid:"", Timestamp:0x572d7867}
DEBU[0120] event unhandled: type:"start-container" id:"18d78fd6685e4b45d37c6b706b2df90e0c5a4a0cf7abad6df370f5edba485304" timestamp:1462597735
DEBU[0120] Calling DELETE /v1.22/containers/2d33b5b32014af7e4a7be151eed9da3cec69b47186c03f5c2f939dba6ffefa31?link=False&force=False&v=False
DEBU[0181] Calling POST /v1.23/containers/server02/exec
DEBU[0181] form data: {"AttachStderr":true,"AttachStdin":true,"AttachStdout":true,"Cmd":["bash"],"Container":"server02","Detach":false,"DetachKeys":"","Privileged":false,"Tty":true,"User":""}
DEBU[0181] Calling POST /v1.23/exec/d8473e3f0ea13d08072cae818b0ff2489600cb7595e54046c8bfb75fa17f7029/start
DEBU[0181] form data: {"AttachStderr":true,"AttachStdin":true,"AttachStdout":true,"Cmd":["bash"],"Container":"server02","Detach":false,"DetachKeys":"","Privileged":false,"Tty":true,"User":""}
DEBU[0181] starting exec command d8473e3f0ea13d08072cae818b0ff2489600cb7595e54046c8bfb75fa17f7029 in container 7bbd81406a854b4a7bef2b361ebf031589028928fd54027ede66b75b38d25a01
DEBU[0181] Calling POST /v1.23/exec/d8473e3f0ea13d08072cae818b0ff2489600cb7595e54046c8bfb75fa17f7029/resize?h=44&w=99
DEBU[0181] attach: stdin: begin
DEBU[0181] attach: stdout: begin
DEBU[0181] received containerd event: &types.Event{Type:"start-process", Id:"7bbd81406a854b4a7bef2b361ebf031589028928fd54027ede66b75b38d25a01", Status:0x0, Pid:"d8473e3f0ea13d08072cae818b0ff2489600cb7595e54046c8bfb75fa17f7029", Timestamp:0x572d78a5}
DEBU[0181] event unhandled: type:"start-process" id:"7bbd81406a854b4a7bef2b361ebf031589028928fd54027ede66b75b38d25a01" pid:"d8473e3f0ea13d08072cae818b0ff2489600cb7595e54046c8bfb75fa17f7029" timestamp:1462597797

**Comment by ninchan8328** [comment]
I found the problem. If using privileged: true, then container cannot ping each other.

**Comment by thaJeztah** [comment]
@ninchan8328 is something in the container making changes to `/etc/resolv.conf` or `/etc/hosts`? This sounds like something in your container is trying to make changes it shouldn't, and those changes are blocked by default (but allowed, when `--privileged` is used)

**Comment by ninchan8328** [comment]
we set privileged=true but not modifying any of the resolve.conf or hosts file

**Comment by ninchan8328** [comment]
Seems like the problem specifically to setting privileged=true on our image with this new docker engine. Taking the setting out work just fine. 

Thanks for helping!

**Comment by ninchan8328** [comment]
it happens that i need to use privileged: true in my environment. Is there any reason why this problem (container A cannot ping container B and vice versa) happen when i use privileged:true with my image?

**Comment by thaJeztah** [comment]
@ninchan8328 see my answer on https://github.com/docker/docker/issues/20026#issuecomment-219662720. If privileged results in making this fail, then it's most likely an issue with your container/image making changes that are otherwise blocked. Running with `--privileged` is really discouraged, as it allows processes in the containers doing all kind of actions that you usually *don't* want. Try to find out what the container needs, and what changes it makes that cause this problem

**Comment by mavenugo** [comment]
@ninchan8328 could you confirm if this happens only with your image or does this happen with any other generic image (such as nginx:alpine as you described above), even with `--privileged` flag set ?
As @thaJeztah mentioned, if it happens only in your image, it is clear that your image is interfering with Docker's name-resolution mechanisms. Do you know what are the privileged operations that your image perform ?

**Comment by ninchan8328** [comment]
@mavenugo @thaJeztah thanks for your response, and I agree this may be something specific to my image, however, I also try to do the same with our base image which has serviceability tools installed like rsyslog, collectd, lumberjack, etc... and still dont work with privileged:true ( i leave out the process that needs cap NET_ADMIN). Do you have any suggestion how i can troubleshoot further?

**Comment by mavenugo** [comment]
@ninchan8328 most likely one of the serviceability tools is causing this. Can you share the DockerFile file for your base image ?

**Comment by sanimej** [comment]
When you run in privileged mode check if any app is clearing the IP tables.. docker daemon sets up some iptable rules required for DNS to work..

````
root@1d0a539b0a8a:/# iptables -t nat -L 
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
DNAT       udp  --  anywhere             127.0.0.11           udp dpt:domain to:127.0.0.11:52491
DNAT       tcp  --  anywhere             127.0.0.11           tcp dpt:domain to:127.0.0.11:46801

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
SNAT       udp  --  127.0.0.11           anywhere             udp spt:52491 to::53
SNAT       tcp  --  127.0.0.11           anywhere             tcp spt:46801 to::53
root@1d0a539b0a8a:/# 
````

**Comment by ninchan8328** [comment]
Sure, first we have a cbase, just a bare minimum centos image download from public docker registry

cbase Dockerfile
FROM centos:centos6

RUN yum -y update
RUN yum -y install wget tar gdb

serviceability Dockerfile
FROM cbase:latest
# change this if this file is copied and then modified.

# Workaround for epel repo fix
RUN yum -y install epel-release
RUN sed -i "s/mirrorlist=https/mirrorlist=http/" /etc/yum.repos.d/epel.repo
RUN yum -y update && yum install -y \
     monit \
     libuv

ADD ./files/* /tmp/files/

ADD ./monit.d/* /etc/monit.d/
ADD ./plugins /etc/monit.d/plugins

ADD ./files/lumberjack.conf /etc/lumberjack.conf
ADD ./certs/* /etc/ssl/certs/
ADD ./files/green_ansible_base.repo /etc/yum.repos.d/green_ansible_base.repo

RUN yum clean all && yum --setopt=obsoletes=0 -y install libksi-3.2.2.0-1.el6.x86_64
RUN yum -y install rsyslog-8.11.0-1.el6.x86_64

RUN yum clean all && yum install -y \
    perl \
    perl-Module-Pluggable \
    perl-Pod-Escapes \
    perl-Pod-Simple \
    perl-libs \
    perl-version \
    pyOpenSSL \
    python-lxml \
    python-twisted-core \
    python-zope-filesystem \
    python-zope-interface \
    vim \
    openssh-clients \
    openssh-server \
    sudo \
    tar \
    yum-utils \
    vixie-cron

# Install JDK 1.7.0 (download online)
RUN yum -y install java-1.7.0-openjdk-1.7.0.65-2.5.1.2.el6_5.x86_64

# Lumberjack hack (download online)
RUN yum -y install lumberjack-0.1.2-1.x86_64
RUN cp -f /tmp/files/lumberjack /etc/init.d/lumberjack

# Install cassd related package (download online)
RUN yum -y install libcassandra-2.0.1-9.el6.x86_64
RUN yum -y install cassandra12-1.2.19-1.noarch

# Install collectd (download it from http://dl.marmotte.net/rpms/redhat/el6/x86_64/collectd-5.4.0-1.el6/)
RUN yum -y install collectd-5.4.0-1.el6.x86_64
RUN yum -y install collectd-postgresql-5.4.0-1.el6.x86_64

# Install glib
RUN yum -y install glibc-2.12-1.166.el6_7.7.x86_64

# SSH configuration
RUN ssh-keygen -q -N "" -t dsa -f /etc/ssh/ssh_host_dsa_key
RUN ssh-keygen -q -N "" -t rsa -f /etc/ssh/ssh_host_rsa_key
RUN sed -i "s/#UsePrivilegeSeparation.*/UsePrivilegeSeparation no/g" /etc/ssh/sshd_config
RUN sed -i "s/UsePAM.*/UsePAM no/g" /etc/ssh/sshd_config
RUN echo 'root:abc123' | chpasswd
RUN mkdir -p /root/.ssh


RUN service rsyslog start
RUN chmod 777 /tmp
RUN /etc/init.d/sshd restart

## start crond
RUN service crond start

# Cleanup repos then add default repo
RUN rm -f /etc/yum.repos.d/*

## overwrite /etc/monit.conf
ADD ./files/monit.conf /etc/monit.conf
RUN chmod 700 /etc/monit.conf

RUN mkdir -p /opt/sec/certs
RUN mkdir -p /opt/sec/keys

ADD ./ssl_sec/certs/* /opt/sec/certs/
ADD ./ssl_sec/keys/* /opt/sec/keys/

ADD ./files/99-saevent.conf /etc/rsyslog.d/99-saevent.conf
ADD ./init_docker.sh /root/init_container.sh
RUN chmod +x /root/init_container.sh

**Comment by ninchan8328** [comment]
I think we found the problem , one of our script restart iptables and clear out the docker settings in iptables for routing. Will that be a good idea to output the rule to /etc/sysconfig/iptables-config? so restarting iptables wont cause any problem?

Anyway, thanks for much for quick help!

**Comment by thaJeztah** [comment]
Looks like we can close this one then :+1:
