### ISSUE TITLE
Build hello-sample failed

### ISSUE THREAD

**Issue by tezhao** [docker/docker#22382]
**Output of `docker version`:**
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.2.1
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.2.1
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```
(paste your output here)
```
root@terry-VirtualBox:/home/terry/docker-node-hello# docker build -t example/docker-node-hello:latest .
Sending build context to Docker daemon 15.87 kB
Sending build context to Docker daemon 
Step 0 : FROM node:0.10
 ---> 4830a2dc3054
Step 1 : MAINTAINER Anna Doe <anna@example.com>
 ---> Using cache
 ---> ca8f29b4fd0c
Step 2 : USER root
 ---> Using cache
 ---> 714e6e2c655c
Step 3 : ENV AP /data/app
 ---> Using cache
 ---> f2d256fa9c97
Step 4 : ENV SCPATH /etc/supervisor/conf.d
 ---> Using cache
 ---> 8ee095ab98da
Step 5 : RUN apt-get -y update
 ---> Using cache
 ---> 8e1e42cf52ad
Step 6 : RUN apt-get -y install supervisor
 ---> Running in c08ac07ed226
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package supervisor
INFO[0000] The command [/bin/sh -c apt-get -y install supervisor] returned a non-zero code: 100 

**Output of `docker info`:**

Containers: 4
Images: 14
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 22
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 4.2.0-35-generic
Operating System: Ubuntu 14.04.4 LTS
CPUs: 1
Total Memory: 2.995 GiB
Name: terry-VirtualBox
ID: SFHK:VFDL:VVPW:5T53:YYYY:DL6Y:BOLV:HJ2U:EJC5:MAIF:JOK6:YSGD
```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VirtualBox

**Steps to reproduce the issue:**
1. start docker server
2. build hello-docker image 
3. the issue occurs

**Describe the results you received:**
E: Unable to locate package supervisor
INFO[0000] The command [/bin/sh -c apt-get -y install supervisor] returned a non-zero code: 100 

**Describe the results you expected:**
Build Successful

**Additional information you deem important (e.g. issue happens only occasionally):**
I tested "sudo apt-get -y install supervisor"  command,it works fine

**Comment by thaJeztah** [comment]
Have you tried running `apt-get -y install supervisor` from inside a container? Are you using a proxy? This looks related to your previous issue https://github.com/docker/docker/issues/22349

Also note that you should never use `apt-get -y update` in a separate `RUN` instruction; as can be seen in the output, docker is caching that statement, and you may be running `apt-get install` with an outdated apt cache (see [Dockerfile best practices](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#apt-get)) It's best to combine `apt-get update` and `apt-get install` in a single `RUN`.

**Comment by tezhao** [comment]
Thank you for your reply.
【Q】
Have you tried running apt-get -y install supervisor from inside a container? 
【A】
Yes
【Q】
Are you using a proxy? 
【A】
Yes

I  deleted the "RUN" lines in my dockerfile and successful build image, but when I run the image,there is another error occured. So I'll close this ticket and create a new one.
