### ISSUE TITLE
could not install docker after upgrading  the linux kernel ('overlay' not found, Udev sync is not supported)

### ISSUE THREAD

**Issue by DanielDai0805** [docker/docker#22381]
**Output of `docker version`:**
docker-1.11.0.tgz（https://get.docker.com/builds/Linux/x86_64/docker-1.11.0.tgz）

**Additional environment details (AWS, VirtualBox, physical, etc.):**

cat /etc/issue :  Red Hat Enterprise Linux Server release 6.6 (Santiago)
uname -a:  Linux node1 3.10.101 #1 SMP Thu Apr 21 22:16:21 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux  (just upgrade the kernel from the source code)
iptables --version : v1.4.7
mount :    /dev/sda3 on / type ext4 (rw)
proc on /proc type proc (rw)
sysfs on /sys type sysfs (rw)
devpts on /dev/pts type devpts (rw,gid=5,mode=620)
tmpfs on /dev/shm type tmpfs (rw,rootcontext="system_u:object_r:tmpfs_t:s0")
/dev/sda1 on /boot type ext4 (rw)
none on /proc/sys/fs/binfmt_misc type binfmt_misc (rw)
vmware-vmblock on /var/run/vmblock-fuse type fuse.vmware-vmblock (rw,nosuid,nodev,default_permissions,allow_other)
/dev/sr0 on /mnt/redhat type iso9660 (ro)
cgroup on /sys/fs/cgroup type tmpfs (rw,uid=0,gid=0,mode=0755,rootcontext="system_u:object_r:sysfs_t:s0")

**Steps to reproduce the issue:**
1.tar -xvzf docker-latest.tgz
2.mv docker/* /usr/bin/
3.sudo docker daemon &

**Describe the results you received:**
INFO[0000] New containerd process, pid: 70408
          
WARN[0000] containerd: low RLIMIT_NOFILE changing to max  current=1024 max=4096
ERRO[0001] devmapper: Udev sync is not supported. This will lead to data loss and unexpected behavior. Install a dynamic binary to use devicemapper or select a different storage driver. For more information, see https://docs.docker.com/engine/reference/commandline/daemon/#daemon-storage-driver-option 
ERRO[0001] 'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded. 
INFO[0001] Graph migration to content-addressability took 0.00 seconds 
WARN[0001] Running modprobe nf_nat failed with message: `WARNING: Module nf_nat not found.`, error: exit status 1 
INFO[0001] Firewalld running: false                     
FATA[0001] Error starting daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain: iptables failed: iptables -t nat -N DOCKER: iptables v1.4.7: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
 (exit status 3) 

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by justincormack** [comment]
The static builds from `get.docker.com` do not have devicemapper support, you need to install via RPM or build yourself from source if you want to use devicemapper, which is the normal storage driver to use under Red Hat distros as they do not ship overlay or aufs.

**Comment by dhoucgitter** [comment]
Hi, if possible, it would be a great idea to mention that limitation on the [docker releases page](https://github.com/moby/moby/releases). I didn't realize that limitation for builds from `get.docker.com` did not have devicemapper support so I wasted time trying to get that working when I stumbled across the same error.
