### ISSUE TITLE
Image Specification v1.0.0 has ambiguities that are very problematic for users of the REST APIs

### ISSUE THREAD

**Issue by cliffbdf** [docker/docker#22399]
1 - Image ID

The spec defines “Image ID”, but then explains what a layer ID is. An image is not a layer - an image is a set of layers (per the definition of “Layer” in the same document).

2 - Tag

The spec defines “Tag” as,

"A tag serves to map a descriptive, user-given name to any single image ID. An image name suffix (the name component after :) is often referred to as a tag as well, though it strictly refers to the full name of an image."

a. This is ambiguous, because the term “image ID” is ambiguous, as a result of #1.

b. The term “full name of an image” is ambiguous. Does it include the namespace? The hostname/port of the registry? (e.g., when one “tags an image into a repository”)

3 - Repository

It is not clear if a repository refers to an image name, or an actual image stored in a registry. It is also not clear if the “repository” is the full image name - including the repository host name - or just the name part preceding the colon at the end of the name. It is not clear if the “repository” includes the “namespace”. In fact, the term “namespace” is not mentioned in the spec, but it is clearly an important element of an image name - or is it? (This is not clear.)

4 - Tagging into a repository

The image spec does not mention this, but the phrase is used in other documentation, without explanation, and it is not clear what this means, especially given the lack of clarity on what “repository” means.

5 - Image "name"

This term is used loosely in the spec and in other documentation - including the various REST APIs, and it is highly ambiguous. Many REST APIs have “name” parameters, and it is not clear if the parameter is a repository name, or can include a final tag (with semicolon) or not - and if it can include a registry host as part of the name. The term “image name” really needs to be precisely defined and used consistently throughout the documentation - especially the REST APIs since those APIs are untyped and thus there is ample opportunity for a programmer to get it wrong.

**Comment by vbatts** [comment]
@cliffbdf for starters, see if any issues are resolved in https://github.com/docker/docker/pull/22264

**Comment by cliffbdf** [comment]
This is indeed an improvement. It better explains Image ID, and Repository.

There is still some ambiguity however that could be resolved around what it means to “tag an image into a repository”. Based on v 1.10, it seems like in a name like myregistry:5000/abc/def/ghi:foo, the “repository” is “myregistry:5000/abc/def/ghi”. That agrees with the spec statement that a repository is a collection of tags - which implies that a tag is what uniquely identifies an image - all good.

Also, allowing the host name to be part of the repsitory name means that the image name is really an image path - that the same image (same signature) in two different registries have distinct names. Thus, name = location. That’s ok - just pointing it out.

It will be helpful to users of the REST APIs if this improved nomenclature finds its way into the API docs. I have been doing some programming against those APIs (registry and docker daemon) and have found myself often confused about names, tagging, and pushing from the daemon to a registry. It seems that there is no way to tag an image in a registry - so tagging must be purely a docker daemon concept. This implies that there is a one-to-one relationship between an image and a tag, but that relationship does not seem to be spelled out anywhere that I have found. It seems like a fundamental concept that could be explained - unless I misunderstand the model. Perhaps it would be helpful to have a diagram showing the full taxonomy and relationship between name components, image/layer instances, and tags?

Cliff

**Comment by cliffbdf** [comment]
Another thing that is not clear is when it is ok to abbreviate an image name. E.g., when it is ok to use

abc/def/ghi:foo

instead of

myregistry:5000/abc/def/ghi:foo

or perhaps even,

ghi:foo

or

def/ghi:foo

I.e., there is a namespace/name scoping and visibility ruleset that needs to be defined, perhaps.

Cliff

**Comment by cliffbdf** [comment]
One more thought and I will stop posting - too much on this already:

If an image name incudes the registry in which it exists, e.g.,

myregistry:5000/abc/def/ghi:foo

this it is puzzling why one would name an image as such in a docker client environment. One would think that one could push an image to multiple registries - thus, naming the image based on the registry is possibly problematic.

I.e., the concept of “tagging into a repository” is puzzling to me: why does one have to name an image according to where it is being sent for storage? Seems like we are mixing up name and path as the same thing. E.g., I can store an rpm in any number of systems, but the name of the rpm is the same.

I think it would be clearer to decouple naming with repsitory location.

I will resist posting on this now unless someone asks me to clarify something.

Thanks!

**Comment by cliffbdf** [comment]
Ok, one more post, to illustrate the ambiguity in the REST specs, and how it could be improved:

E.g., the Distribution REST API spec (https://github.com/docker/distribution/blob/master/docs/spec/api.md) provides this for the API call that retrieves a list of tags for an image:

/v2/<name>/tags/list

Can “name” be,

myregistry.com:5000/abc/def/ghi:foo

One would presume not, since then it would not name sense to be retrieving the tags - but that is a guess.

Can it be,

myregistry.com:5000/abc/def/ghi

Can it be,

ghi

or must it be the full name path?

What if it is,

def/ghi

or

abc/def/ghi

or

/abc/def/ghi

or

/abc/


Thus, the term “name” is highly ambiguous. This could be clarified by defining BNF style grammar for image names and using the appropriate name part in the REST specs.

Regards,

Cliff

**Comment by stevvooe** [comment]
@cliffbdf There are indeed a lot of things that need to be worked out. The specification is still in progress, so I'd appreciate some patience from the community as we get these issues resolved. There are long standing problems, such as the coupling between registry and naming, that need to be worked out. Nomenclature has always been a problem.

What you call a "REST" API, is not actually a REST API. It is an HTTP API. There is a lot of information on how naming and urls work that are available in github.com/docker/distribution. Reading the docs and specifications there may clarify many of your questions. Many of the ambiguities are painstakingly handled in the design of that API. I'd appreciate if you'd take the time to fill in the details. Albeit, I'm not sure if much, if any of this, belongs in an image specification, as they are really part of distribution of images.

For reference, the image naming for _Docker_ has the grammar specified [here](https://github.com/docker/distribution/blob/master/reference/reference.go#L4). This grammar should probably make its way into the specification, but we need it to stabilize first (there is only the outstanding issue of `+`, I think).

I understand that the process of filing issues is painstaking and appreciate your feedback, but there are several mutually exclusive issues called out here. In general, issues submitted in this format tend not to be very constructive. It would be great if you could organize this issue or break it down into sub issues. It would also be appreciated if you could submit PRs where possible, as we can ensure we are discussing specific problems and solutions.

**Comment by cliffbdf** [comment]
> On Apr 28, 2016, at 6:00 PM, Stephen Day <notifications@github.com> wrote:
> 
> @cliffbdf <https://github.com/cliffbdf> There are indeed a lot of things that need to be worked out. The specification is still in progress, so I'd appreciate some patience from the community as we get these issues resolved. There are long standing problems, such as the coupling between registry and naming, that need to be worked out. Nomenclature has always been a problem.
> 
> What you call a "REST" API, is not actually a REST API. It is an HTTP API. There is a lot of information on how naming and urls work that are available in github.com/docker/distribution. Reading the docs and specifications there may clarify many of your questions. Many of the ambiguities are painstakingly handled in the design of that API.
> 
It seems to me, on reflection, that some of the difficulty might arise from using HTTP as the API specification language. As a result, concepts such as API method parameters and HTTP headers are inter-mixed. The result is a very complex API spec. It might clarify things to abstract the API using a request/response grammar. The Google “protocol buffers” syntax (they call it “proto” syntax) might be useful for that purpose, although I am not sure that it can handle stream type data, which is important for docker. In any case, I think that HTTP might be getting in the way of settling many of the semantic API issues. Think about it: the Distribution v2 API has 13 methods, but if printed in page format, it is 72 pages (I just printed it as a PDF to see). Something is wrong - that is too long for 13 methods, and I think that HTTP is the reason. For comparison, if I go to AWS’s APIs and pick one of their classes - say the Java class “AbstractAmazonEC2”, the docs for that class (if printed as PDF) are 64 pages for 252 methods. That is a density that is 22 times the density fo the registry v2 API, and it is because the AWS programmatic APIs don’t have to mess with the intricacies of HTTP. All we are trying to do here with HTTP is make remote method calls, so we should be able to express it in simple terms like a programmatic API.

I.e., it should be possible to separate the logical API from the HTTP binding of the API. I am not suggesting you do this now - you are far down the road you are on, but it might be something to think about for v3.

The use of JSON adds to the complexity, because JSON is a run-time syntax - not a specification sytax. Perhaps JSON schema definitions would be a better choice. The problem is not knowing what fields are requried in certain circumstances, and not having a way to verify one’s JSON except by running one’s code against a live service. If the JSON evolves over time, people will have issues of “this used to work but perhaps there is a new JSON field that I am missing”. This is the problem with dynamically bound structures like JSON. Using JSON schema to define the required JSON would give users of the APIs a way to verify their JSON before running it.


> I'd appreciate if you'd take the time to fill in the details. Albeit, I'm not sure if much, if any of this, belongs in an image specification, as they are really part of distribution of images.
> 
Indeed, I would expect the API and image specs to be distinct. There are some ambiguities about where one ends and another begins, particularly with regard to the concepts of namespace and registry name. I hope that the evolving specs are able to clarify these areas.



> For reference, the image naming for Docker has the grammar specified here <https://github.com/docker/distribution/blob/master/reference/reference.go#L4>. This grammar should probably make its way into the specification, but we need it to stabilize first (there is only the outstanding issue of +, I think).
> 
That will be immensely helpful if it goes into the spec. The spec should really be based around that IMO. I speak as someone who used to build compilers early in my career. Having a stable grammar brings great clarity to any effort to define/refine semantic rules. A typical language reference manual is built around the grammar.



> I understand that the process of filing issues is painstaking and appreciate your feedback, but there are several mutually exclusive issues called out here. In general, issues submitted in this format tend not to be very constructive. It would be great if you could organize this issue or break it down into sub issues. It would also be appreciated if you could submit PRs where possible, as we can ensure we are discussing specific problems and solutions.
> 
I am not familiar with the PR process. Is that a github thing that I should obviously know? A pointer will help and I am happy to try to organize my thoguhts on this if it will help in any way.

Very best,

Cliff

**Comment by stevvooe** [comment]
@cliffbdf What are you trying to achieve? Is there something that you're trying to accomplish but are running into these issues as road blocks?

I am also not aware of what universe of engineering where comparing PDF size is any kind of valid measurement. Most the bulk of our specification uses auto-generated request vectors for each request response variation so one can simply read through and see what the expected values are to be. If you don't like that, the prose section at the start explains a number of concepts. I'm not even going to get into the problems with the AWS API but I don't think these are comparable.

Yes, HTTP is a terrible specification format and JSON doesn't help. But, these are the tools we have an they work fantastically, some how.

If you have a suggestion for improving ours, submit a PR. If you are not familiar with the process, look at other PRs to that code and see what those people did. When you read enough, you'll better understand what makes a PR or issue successful over another. If you are still confused, ask people in IRC or attend a docker meetup event and ask there. There are also documents at the root of this repo that can provide guidance.

If you choose to listen to none of what I said, please, please, please at least save a tree and stop printing specifications. 🌲🌳🌳🌲

**Comment by cliffbdf** [comment]
> On Apr 28, 2016, at 7:03 PM, Stephen Day <notifications@github.com> wrote:
> 
> @cliffbdf <https://github.com/cliffbdf> What are you trying to achieve? Is there something that you're trying to accomplish but are running into these issues as road blocks?
> 
I am finding that the ambiguities are making it slow going for me, in using the APIs. That is all. I find that I spend a-lot of time wondering if I have things right, instead of running my code. So roadblocks no. I am just trying to be helpful - I know that you are dealing with live systems while trying to improve the specs - not an easy task.


> I am also not aware of what universe of engineering where comparing PDF size is any kind of valid measurement.
> 
Indeed. It was intended just as a rough comparison. It is certainly not scientific. However, it seemed to me that a-lot of the content of the spec revolves around HTTP and JSON constructs instead of the logical API elements of what methods are there, what are their logical arguments, and what is the semantic effect of each method. I was just making an observation that might be useful or might not be. I see this difficulty all the time these days with systems that use REST APIs. REST is actually a very terrible API regime. Protocol buffers is finally a return to a remote API approach that is more convenient for application programmers.


> Most the bulk of our specification uses auto-generated request vectors for each request response variation so one can simply read through and see what the expected values are to be. If you don't like that, the prose section at the start explains a number of concepts. I'm not even going to get into the problems with the AWS API but I don't think these are comparable.
> 
> Yes, HTTP is a terrible specification format and JSON doesn't help. But, these are the tools we have an they work fantastically, some how.
> 
Yes, they work. Although as Alan Kay put it, the Web (i.e., HTTP and HTML) was built by amateurs ;-)


> If you have a suggestion for improving ours, submit a PR. If you are not familiar with the process, look at other PRs to that code and see what those people did. When you read enough, you'll better understand what makes a PR or issue successful over another. If you are still confused, ask people in IRC or attend a docker meetup event and ask there. There are also documents at the root of this repo that can provide guidance.
> 
Yes, that is the norm for much of the code in github, and it works. However, compare what, say, Amazon does: they have very expertly documented APIs. They are a modern company with some of the most widely used technology, and apparently feel that looking at code is not an effective way for users of APIs to learn those APIs. Look also at the Java APIs - really excellently documented and that might have played a role in the meteoric rise of Java in the late 90s. APIs as tribal knowledge is not as effective as APIs well documented ;-) I can see that you folks are making an effort to document things well and you are going a million miles an hour on many fronts and creating some fantastic game-changing technology - technolgy that I use becasue it is great. When things move fast, some i’s don’t get dotted.


> If you choose to listen to none of what I said, please, please, please at least save a tree and stop printing specifications. 🌲🌳🌳🌲
> 
I didn’t actually print them to paper - I printed them to PDF ;-)

I will look into the PR process - I want to help.

Thank you for taking the time to explain things. The name BNF is especially helpful.

Best regards,

Cliff

**Comment by stevvooe** [comment]
If you're comparing Javadoc APIs, please compare with [Godoc](https://godoc.org/github.com/docker/distribution). All of the distribution related APIs are well-documented.

I'm going to close this issue, as while I'd love to debate these points, it is not a constructive use of anyone's time.
