### ISSUE TITLE
Request for JSON schema

### ISSUE THREAD

**Issue by cliffbdf** [docker/docker#22401]
It would be really helpful to have JSON schema (http://json-schema.org/) for the various JSON structures that are used by the APIs and image formats - that way one could syntactically verify one's JSON without having to run it through the API and diagnose the failures that result.

**Comment by thaJeztah** [comment]
I think this is a duplicate of https://github.com/docker/engine-api/pull/78, but was closed in favor of using Swagger; https://github.com/docker/engine-api/issues/77

**Comment by cliffbdf** [comment]
Indeed, it appears to discuss the same issue. Shall I close this? I am a bystander so I am not sure of the protocol...

**Comment by thaJeztah** [comment]
Let me close it here, because this change has to me made in the other repository, so probably no need to keep it open here. Thank!
