### ISSUE TITLE
Unable to pull images on Windows Server 2016 TP5

### ISSUE THREAD

**Issue by lfarnell** [docker/docker#22404]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   2b97201
 Built:        Tue Apr 26 23:51:36 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   2b97201
 Built:        Tue Apr 26 23:51:36 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 1.12.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null
Kernel Version: 10.0 14300 (14300.1010.amd64fre.rs1_release_svc.160415-2143)
Operating System: Windows Server 2016 Standard Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 4 GiB
Name: WIN-LLLQ675JB3A
ID: VSVH:X5U3:FUA4:6BJ5:3OK2:FTCV:QZVB:GXCW:4CBQ:FEGG:VDDI:KMPS
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Windows Server 2016 TP5 running in VMWare Workstation 9 

**Steps to reproduce the issue:**
1. Follow [instructions](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/deployment/deployment) for installation
2. docker pull microsoft/dotnet35:latest

**Describe the results you received:**
latest: Pulling from microsoft/dotnet35

1cf51c47c298: Extracting [==================================================>] 72.03 MB/72.03 MB
849b9bdf7071: Download complete
failed to register layer: convert O:BAG:DUD:(A;OICI;0x1200a9;;;S-1-5-83-0)(A;OICI;FA;;;BA)(A;OICI;FA;;;SY)(A;;FA;;;BA)(A;OICIIO;GA;;;CO)(A;OICI;0x1200a9;;;BU)(A;CI;LC;;;BU)(A;CI;DC;;;BU): The security ID structure is invalid.

**Describe the results you expected:**
docker image to be pulled down

**Additional information you deem important (e.g. issue happens only occasionally):**
cant seem to pull any docker image from docker hub. also cant build any image using docker build on windows

**Comment by thaJeztah** [comment]
ping @jhowardmsft @jstarks

**Comment by versofate** [comment]
I've also encountered with this problem.

**Comment by jhowardmsft** [comment]
Known. @patricklang can explain :smile_cat:

**Comment by PatrickLang** [comment]
We figured out the issue, and are currently working to update the images on Docker Hub to fix the problem. As a temporary workaround, you can join your Windows Server 2016 TP5 machine to any domain, then attempt the pull again and it should succeed.

I'll resolve this issue once the new images are pushed.

**Comment by PatrickLang** [comment]
This should be resolved now. If you have problems with any of the Microsoft/.. images, please go ahead and open a new issue and include:
- failed `docker pull` output
- Relevant errors from C:\ProgramData\docker\daemon.log
- `docker version`

Thanks!

**Comment by thaJeztah** [comment]
Thanks @PatrickLang I'll close this issue
