### ISSUE TITLE
help

### ISSUE THREAD

**Issue by elie89** [docker/docker#22414]
three aspects that indicates whether a certificate is valid or not ?

**Comment by thaJeztah** [comment]
can you provide some more information? this doesn't look like an issue/bug in docker, so I'll close

**Comment by elie89** [comment]
i need information only

**Comment by thaJeztah** [comment]
In what context? Your question doesn't have a lot of information to go on, if you want help

**Comment by elie89** [comment]
what are the three aspects that indicates whether a certificate is valid or not ?
1- date (expire or not )
2-????
3-???
i can find the second and the third 
the question in other way : what are the characteristic of a valid certificate ?
and thanks :)

**Comment by thaJeztah** [comment]
http://security.stackexchange.com/a/20833
http://security.stackexchange.com/questions/31975/why-are-ssl-certificates-valid-only-from-a-certain-date

**Comment by elie89** [comment]
thanks a lot it's sow helpful :)
