### ISSUE TITLE
--pid=host triggers "Security options" warning

### ISSUE THREAD

**Issue by bboreham** [docker/docker#22413]
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 594
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /home/docker/aufs
 Backing Filesystem: extfs
 Dirs: 600
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host null
Kernel Version: 3.13.0-85-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.861 GiB
Name: bbvlx1
ID: IVMU:DIYM:GNIF:DNSW:GCHY:42Z5:R573:MDYB:YWOK:W57O:P4WY:2LQS
Docker Root Dir: /home/docker
Debug mode (client): false
Debug mode (server): false
Username: bboreham
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**

    $ docker run -ti --pid=host alpine /bin/sh

**Describe the results you received:**

Seen in Docker logs:

    time="2016-04-29T12:07:10.269363381+01:00" level=warning msg="Security options with `:` as a separator are deprecated and will be completely unsupported in 1.13, use `=` instead."

**Describe the results you expected:**

No warning.

**Additional information you deem important (e.g. issue happens only occasionally):**

The `:` is coming from https://github.com/opencontainers/runc/blob/master/libcontainer/selinux/selinux.go#L498, which is now in conflict with #21232

**Comment by thaJeztah** [comment]
Thanks! I see you already opened a PR to fix it 👍

**Comment by crosbymichael** [comment]
This was updated and resolved in runc
