### ISSUE TITLE
Set Environment Variable to always read from executing shell

### ISSUE THREAD

**Issue by j3p0uk** [docker/docker#22412]
I have a use case where I am creating an image that requires a number of environment variables for operation.  It is an image that is to be shared among many users.  To execute correctly the command line becomes unwieldy with the number of environment variables to pass in.

If I could specify a number of environment variables in the Dockerfile like:

ENV OS_AUTH_URL
ENV OS_CLOUD_NAME
ENV OS_PASSWORD
ENV OS_TENANT_ID
ENV OS_TENANT_NAME
ENV OS_USERNAME

And then have any execution of that image automatically set those environment variables from the current shell variables (if set), it would make the execution much more user-friendly.

**Comment by thaJeztah** [comment]
Docker already copies the value of the environment variable if you don't set a value yourself, for example;

```bash
BLABLA=heyhey  docker run -it --rm -e BLABLA ubuntu
root@57c63e26aef4:/# echo $BLABLA
heyhey
```

Alternatively, you can use an [`env-file`, containing a list of "name=value" pairs](https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables-e-env-env-file_;

```bash
docker run --env-file=/my/env-file ubuntu
```

If you need to specify a lot of options for your `docker run`, I suggest to look into Docker Compose. Docker Compose allows you to specify all options that are needed to run your container(s) and start that container using a single `docker-compose up -d`. You can also have it set environment variables from your host; see the docker-compose.yml reference here; https://docs.docker.com/compose/compose-file/#environment

> And then have any execution of that image automatically set those environment variables from the  current shell variables (if set), it would make the execution much more user-friendly.

That may not be a smart thing to do; using the environment variables from the host should be an explicit action at all times. Consider something like;

```bash
docker run some-image-someone-told-me-to-run

Hi!
We just uploaded your OS_CLOUD_NAME and OS_CLOUD_PASSWORD
to our servers, so that others can benefit from them as well

Thanks for running some-image-someone-told-me-to-run!
```


I hope the suggestions above help you further. We're not planning to make more changes / add more features in this area, so I'll close this, but feel free to comment after I closed 👍

**Comment by j3p0uk** [comment]
Yes - the security issue is interesting, but then you should really only run images you can trust anyway.

Looks like docker compose will do what I want, so I will look into that, thanks.

**Comment by thaJeztah** [comment]
Yup fully agree "you should".

Glad I could help!
