### ISSUE TITLE
let DOCKER_TLS_VERIFY=0 disable TLS

### ISSUE THREAD

**Issue by gesellix** [docker/docker#22411]
It's somewhat surprising that we cannot explicitly disable TLS connectivity. The docs state that the existence of `DOCKER_TLS_VERIFY` already enables TLS. It's actual value is ignored.

Would it be possible to change that behaviour to handle falsy values (`0`, `false`, `no`) like expected? If so, I'd be happy to provide a PR.

related: https://github.com/docker/docker/issues/14129

**Comment by phemmer** [comment]
My own $0.02:

While I think empty is an acceptable method of turning TLS off, I don't think "off" should disable TLS, just the verification of the cert.
I think DOCKER_TLS_VERIFY should behave similar to the TLS verification settings of other software. For example, OpenLDAP's TLS verification settings:

> TLSVerifyClient { never | allow | try | demand }
>
> This directive specifies what checks to perform on client certificates in an incoming TLS session, if any. This option is set to never by default, in which case the server never asks the client for a certificate. With a setting of allow the server will ask for a client certificate; if none is provided the session proceeds normally. If a certificate is provided but the server is unable to verify it, the certificate is ignored and the session proceeds normally, as if no certificate had been provided. With a setting of try the certificate is requested, and if none is provided, the session proceeds normally. If a certificate is provided and it cannot be verified, the session is immediately terminated. With a setting of demand the certificate is requested and a valid certificate must be provided, otherwise the session is immediately terminated.

*([Principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment))*

So I think it should either remain as is (empty turns TLS off), or we get a new variable, such as $DOCKER_TLS.

**Comment by gesellix** [comment]
@phemmer Where do you read that an _empty_ setting leads to actually verify anything? For me it still reads as `DOCKER_TLS_VERIFY=0` is similar to `TLSVerifyClient=never`, with both settings having exactly those values as defaults when not set.

I'm with you that it's better to distinguish between TLS-verification and TLS-toggling, though. Yet, disabling verification leads effectively to a non-secured connection, doesn't it?

**Comment by gesellix** [comment]
So much about least astonishment - I needed to edit my last comment. I hope I got it right now.

**Comment by phemmer** [comment]
> Where do you read that an empty setting leads to actually verify anything? 

It doesn't verify anything. It disables the feature.
https://docs.docker.com/engine/reference/commandline/daemon/

> Setting the `DOCKER_TLS_VERIFY` environment variable to any value other than the empty string is equivalent to setting the --tlsverify flag.

**Comment by gesellix** [comment]
Alright, the surprise lies in the enabled verification when the setting is "0". "Empty" is disabling.
So this is wrong on my side:
> It's somewhat surprising that we cannot explicitly disable TLS connectivity.

But again, it's at least surprising to me that it's no actual toggle and only works on presence. Compared to OpenLDAP I only miss the possibility to set a value more explicit - or "readable" - instead of relying on existence.

I'm going to close this issue now, because:
- most people seem to be used to it
- we _have_ the chance to disable the feature
- I'm going to think about it and maybe come up with a clearer approach

Thanks for the discussion and correcting my wrong impression!

**Comment by 40a** [comment]
Current behaviour is extremely annoying and is the show stopper in several environments.
There is NO EXCUSE for such dumb error.

**Comment by hickeng** [comment]
Even if keeping DOCKER_TLS_VERIFY=0 meaning verify, the following should disable it, but doesn't:
```
DOCKER_TLS_VERIFY=
```

You actually have to use `unset` or similar which makes it immediately much more difficult to have a semi portable environment file.

**Comment by exjimsk** [comment]
I was surprised to see that explicitly setting

    DOCKER_TLS_VERIFY=0

still performs the tls checking.  The meaning of an explicit 0 value should be no surprise.

**Comment by bussiere** [comment]
If you have also lost many hours of your life on this issue, write a +1 here ...

**Comment by FlorianHeigl** [comment]
why is this closed anyway? It's not as if stuff works in a sensible way?
