### ISSUE TITLE
Inconsistent --tmpfs behavior

### ISSUE THREAD

**Issue by mmarzantowicz** [docker/docker#22420]
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Sat Mar 12 19:18:57 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Sat Mar 12 19:18:57 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 57
Server Version: 1.10.3
Storage Driver: btrfs
 Build Version: Btrfs v4.4.1
 Library Version: 101
Execution Driver: native-0.2
Logging Driver: journald
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.5.1-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.784 GiB
Name: royalarch
ID: 4QHC:NNCF:4N6F:XAXA:CUXL:Y6ZX:YIW5:DPDJ:AXHI:5VPR:DFNZ:ZXV5
Debug mode (server): true
 File Descriptors: 43
 Goroutines: 71
 System Time: 2016-04-29T17:39:26.474624153+02:00
 EventsListeners: 0
 Init SHA1: b8a56fbe8389e4086811723064e36c136fc31d27
 Init Path: /usr/lib/docker/dockerinit
 Docker Root Dir: /var/lib/docker
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical

**Steps to reproduce the issue:**
1. `docker run --rm -it --tmpfs /tmp:rw fedora:23 findmnt /tmp`

**Describe the results you received:**
```
TARGET SOURCE FSTYPE OPTIONS
/tmp   tmpfs  tmpfs  rw,relatime
```

**Describe the results you expected:**
```
TARGET SOURCE FSTYPE OPTIONS
/tmp   tmpfs  tmpfs  rw,nosuid,nodev,noexec,relatime,size=65536k
```

What is wrong? Nothing is mentioned in `--tmpfs` options about `nosuid`, `nodev`, `noexec`, `size` but the values get changed. So it looks like trying to explicitly make `/tmp` `rw` it also changes executability, suidity etc. I expect that only option changed is the one that is put in `--tmpfs` argument list and others are untouched.

**Additional information you deem important (e.g. issue happens only occasionally):**
Nothing I can add here, sorry.

**Comment by thaJeztah** [comment]
hm, did that not produce an error? running on 1.11.1, I get

```bash
$ docker run --rm -it --tmpfs /tmp:rw fedora:23 findmnt /tmp                                                                                            docker: Invalid tmpfs option ["rw"].
See 'docker run --help'.
```

And it looks like `rw` is not a valid option for tmpfs;
https://github.com/docker/docker/blob/3d13fddd2bc4d679f0eaa68b0be877e5a816ad53/pkg/mount/flags.go#L73-L92

**Comment by mmarzantowicz** [comment]
No, there is no error, but pleas note that I'm using 1.10.3 and things might have changed. I'm more concerned about how changing one mount option affects other, not mentioned options. The default is `rw,nosuid,nodev,noexec,relatime,size=65536k` when nothing is given after `:`. Maybe it should be just `rw` and other options should be added on demand? I don't know what is the best way but now it is slightly unpredictable. I originally wanted to allow execution of scripts placed in `/tmp` and I incidentally achieved it by adding `rw` not `exec`! I also removed all other goodies that docker placed there.

**Comment by thaJeztah** [comment]
hm, alright I ran that on Docker for Mac, and may be an issue there. Running the same on ubuntu 14.04

```
docker run --rm -it --tmpfs /tmp:rw fedora:23 findmnt /tmp
TARGET SOURCE FSTYPE OPTIONS
/tmp   tmpfs  tmpfs  rw,nosuid,nodev,noexec,relatime
```

And without `:rw`;
```
docker run --rm -it --tmpfs /tmp fedora:23 findmnt /tmp
TARGET SOURCE FSTYPE OPTIONS
/tmp   tmpfs  tmpfs  rw,nosuid,nodev,noexec,relatime,size=65536k
```

**Comment by mmarzantowicz** [comment]
So, is it intentional that by adding `:rw`, `size=65536k` is also removed from default options or is it an error?

From what I see, it looks like it is not possible to add/remove only a single mount option. Either you have all by default (by why not just none of them?) or when you decide to change something all other options are lost and you must specify them explicitly.

There is also that issue with `rw` in 1.10.3 which might already have been fixed according to your output but I'm currently unable to try any later version of Docker.

**Comment by yongtang** [comment]
I take a look at the source code, here is the current behavior:

* `noexec,nosuid,nodev,rprivate` is the pre-propagated mode before further processing

* If no options is specified by the user, append `size=65536k` so we have
`noexec,nosuid,nodev,rprivate,size=65536k`

* If options (e.g., `op1,op2,...`)have been specified by the user, append user options so we have
`noexec,nosuid,nodev,private,op1,op2...`

I could see the inconsistency comes from the different treatment of `size=65536k`. On the other hand, if I provided duplicate options with different values, the latest value will always take precedence over the previous one. e.g., 
```
docker run --rm -it --tmpfs /tmp:rw,suid,size=65536k,size=8192k,exec,nosuid fedora:23 findmnt /tmp
TARGET SOURCE FSTYPE OPTIONS
/tmp   tmpfs  tmpfs  rw,nosuid,nodev,relatime,size=8192k
```

I think the inconsistency issue could be simply resolved by always pre-progate `size=65536k` as this value will be overridden if user provide another `size=...` anyway.

**Comment by yongtang** [comment]
@mmarzantowicz @thaJeztah I created a PR #22438 to address the inconsistency issue for `size=65536k` so that we have the same behavior even when `rw` is specified. Please let me know if there are any issues.

**Comment by mmarzantowicz** [comment]
Thank you, I will give it a try. Nice work, I hope it will be merged soon.
