### ISSUE TITLE
remote api escaping environment variables

### ISSUE THREAD

**Issue by herikx2k3** [docker/docker#22437]
Hi, 

i possibly might be missing something but i cannot seem to find documentation on this.

Could you please advice.

I am using the remote api to create a container and i have an environment variable of the sort:
uri=http://meow.com/?p=1&c=2

Once the container is created the character & is changed to \u0026.

Could you pls advice on how i could fix this.

Thanks

**Output of `docker version`:**

```
Docker version 1.11.1, build 5604cbe
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /home/docker/aufs
 Backing Filesystem: extfs
 Dirs: 28
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-21-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.32 GiB

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
Do you still have this issue, or was it resolved? I tried to reproduce, but it seems to work ok for me;

```bash
docker run --rm -e uri="http://meow.com/?p=1&c=2" alpine sh -c "echo \$uri"
http://meow.com/?p=1&c=2
```

**Comment by herikx2k3** [comment]
I do not have this issue anymore as well. Thanks very much for your response.
