### ISSUE TITLE
docker pull fails because of a concurrent connection failing

### ISSUE THREAD

**Issue by parhamdoustdar** [docker/docker#22443]
**Output of `docker version`:**

```
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:14:21 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 20:39:58 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.10.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 5
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 4.1.17-boot2docker
Operating System: Boot2Docker 1.10.1 (TCL 6.4.1); master : b03e158 - Thu Feb 11
22:34:01 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.2 MiB
Name: default
ID: NO2I:IT3M:H23O:D5GS:PEQY:GADX:WCGC:HVBU:BVV6:ZPI2:6HGQ:5UON
Debug mode (server): true
 File Descriptors: 10
 Goroutines: 21
 System Time: 2016-05-01T18:03:11.184715369Z
 EventsListeners: 0
 Init SHA1:
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Username: parhamdoustdar
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I have set an HTTP proxy for my docker daemon. The proxy works, but is slow.

**Steps to reproduce the issue:**
1. On a slow connection, pull the `nginx:latest` image by typing `docker pull nginx`.
2. After about 30 seconds, the output will be something like this:
    
    ```
    Using default tag: latest
    latest: Pulling from library/nginx
    efd26ecc9548: Downloading 523.2 kB/51.34 MB
    a3ed95caeb02: Download complete
    a48df1751a97: Downloading 212.1 kB/19.82 MB
    8ddc2d7beb91: Retrying in 1 seconds
    ```

**Describe the results you received:**

After a while, the Docker engine will give up downloading all those layers, even though 2 of them are in progress and only one of them has failed:

```
net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**Describe the results you expected:**

A download failure should not stop the whole build while concurrent gorutines are already downloading data. Instead, it should wait until the other threads have finished downloading. Either that, or there should be a way to provide a maximum concurrent downloads limit.

**Additional information you deem important (e.g. issue happens only occasionally):**

As I said, this issue happens on network connections that don't support multiple downloads.

**Comment by thaJeztah** [comment]
Thanks for reporting; I think this is closely related to https://github.com/docker/docker/issues/22443, which is for `docker push`

**Comment by parhamdoustdar** [comment]
Thanks!

It seems you gave the wrong issue ID; #22443 is this issue, not a different one.

**Comment by yongtang** [comment]
Might be related to #20936?

**Comment by yongtang** [comment]
It seems that the number of concurrent connections in `docker push` or `docker pull` is controlled by
https://github.com/docker/docker/blob/v1.11.0/daemon/daemon.go#L77-L85
The value is set with `maxDownloadConcurrency = 3` and `maxUploadConcurrency = 5`.

Maybe those two values could be changed to adjustable and passed as arguments from `docker daemon`?

**Comment by thaJeztah** [comment]
Oh! Wrong link on my clipboard; meant to refer to https://github.com/docker/docker/issues/20936 indeed

**Comment by yongtang** [comment]
@parhamdoustdar @thaJeztah I just added a PR #22445 to add the option for max upload/download concurrency. Hopefully the issue could be resolved.

**Comment by parhamdoustdar** [comment]
Awesome! Thank you!
