### ISSUE TITLE
Cannot overwrite file through volume - rpc error: code = 2 desc = "oci runtime error: could not synchronise with container process: not a directory"

### ISSUE THREAD

**Issue by bizmate** [docker/docker#22447]
**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   a5315b8
 Built:        Mon Apr 18 19:19:21 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 5
 Running: 2
 Paused: 0
 Stopped: 3
Images: 113
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 234
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.6
Operating System: Alpine Linux v3.3
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.956 GiB
Name: docker
ID: WC3R:KYCY:HVVL:HRWK:AV2K:HBZV:ZJQ5:PW5R:ZECN:H6X4:FH2H:SPS5
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 43
 Goroutines: 67
 System Time: 2016-05-02T09:18:33.996759783Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
phisical native beta on OSX, as per docker version output

**Steps to reproduce the issue:**
1.enable a file mount on my docker compose file, for instance this line - https://github.com/bizmate/nutch/blob/master/docker-compose.yml#L13
2. run `docker-compose up -d`

**Describe the results you received:**
Starting data_mounts
nutch_hbase_1 is up-to-date
Recreating nutch

ERROR: for nutch  rpc error: code = 2 desc = "oci runtime error: could not synchronise with container process: not a directory"

**Describe the results you expected:**
I expect file mounts to overwrite existing files in the container using the host file content

**Additional information you deem important (e.g. issue happens only occasionally):**
I have checked other issues and since i am on beta i suspect it might be something specific with it

**Comment by thaJeztah** [comment]
I'm unable to reproduce this (also running on Docker for Mac), and after un-commenting that line.

```
Creating network "nutch_default" with the default driver
Creating data_mounts
Creating nutch_hbase_1
Creating nutch
```

Can you try `docker-compose down` first, to remove the existing containers, and run `docker-compose up -d` again after that?

Also note that bind-mounting single files (not directories) can sometimes be problematic; some software writing to files do so by writing to a temp-file, and then replacing the file with the new file. If the file it's replacing is bind-mounted, this may not work as expected. Is something inside the container, or on your host editing one of those files (perhaps you were editing this file yourself)? I'm not sure that's what causing it, but may be something to take  into account. (see [Mount a host file as a data volume](https://docs.docker.com/engine/userguide/containers/dockervolumes/#mount-a-host-file-as-a-data-volume))

Can you double-check if the files you're bind-mounting are present on your OS X machine? If the files are missing, Docker may try to create an empty-directory and bind-mount that directory (where the container expects a file)

**Comment by bizmate** [comment]
@thaJeztah i had tried downing containers also with -v and then recreating them. Just retried to make sure but I am still getting the same error.

I have also got a linux host machine. I cloned my repo on my linux machine and after commenting out the one line config file i could create the containers with no problems.

I can only see the problem on my OSX laptop. It is strange you cannot reproduce if you have the same setup. 
The file is there as visible on the git repo on both host machines. Also the running process is able to edit the file fine if needs to. 
What else can I try?

**Comment by thaJeztah** [comment]
hm, strange. Just some weird thought; it's not a memory issue? I have my Docker Mac configured to use slightly more memory (3GB)

**Comment by bizmate** [comment]
I see it using 1.87 gb (kernel using another 950~MB) out of 8GB where more than half of the memory is free/available. I quickly googled but could not see how to increase/set a limit. Could you suggest how? Is this something i can add in the compose file?

I would assume docker scales up to the minimum required per container or throws a memory error then but nothing to do with files/directories.

**Comment by cpuguy83** [comment]
To me, it looks like docker does not see a file that you are trying to mount and it is likely creating a dir, meanwhile in the container you have a file, and when it tries to bind-mount that the kernel throws the error 'not a directory'.

**Comment by bizmate** [comment]
@cpuguy83 i guess that could be it if the file was not there. But gora.properties is there and indeed does not fail on the ubuntu machine

```
ls -la docker/nutch/
total 24
drwxrwxr-x 2 bizmate bizmate 4096 May  2 14:46 .
drwxrwxr-x 4 bizmate bizmate 4096 May  2 14:46 ..
-rw-rw-r-- 1 bizmate bizmate 3097 May  2 15:00 gora.properties
-rw-rw-r-- 1 bizmate bizmate 5979 May  2 14:46 ivy.xml
-rw-rw-r-- 1 bizmate bizmate 3657 May  2 14:46 nutch-site.xml
```

**Comment by cpuguy83** [comment]
@bizmate Have you tried to mount the file manually with the docker CLI?

**Comment by cpuguy83** [comment]
Also is compose talking to the same daemon as your CLI?

**Comment by bizmate** [comment]
@cpuguy83 regarding loading it from cli
```
docker run  -d -v /Applications/XAMPP/htdocs/nutch/docker/nutch/gora.properties:/opt/nutch/conf/gora.properties  --name nutch meabed/nutch
dbf6cd3d1bb4fd35988f2fe44cc5e0513372223b8516433dee022f9a9cde119b
docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: could not synchronise with container process: not a directory".
```

I am not sure on how to check the deamon, but the error on cli and compose are the same.

**Comment by cpuguy83** [comment]
@bizmate I'd instead bind that file into busybox or something like so:


```
$ docker run --rm -v /Applications/XAMPP/htdocs/nutch/docker/nutch/gora.properties:/foo busybox cat /foo
```

**Comment by cpuguy83** [comment]
Yeah, it doesn't look like docker sees anything in `/Applications`

**Comment by bizmate** [comment]
it doesnt complain about folder mounts under /Applications

```
docker run  -d -v /Applications/XAMPP/htdocs/nutch/docker/hbase/data/:/data  --name nutch meabed/nutch
368f2ba95efaa72a8d04879213c0b070637db62bf32fd94896520d30f82fad71

docker ps | grep nutch
368f2ba95efa        meabed/nutch        "/etc/bootstrap.sh -d"   About a minute ago   Up About a minute   8899/tcp                                                 nutch
```

**Comment by cpuguy83** [comment]
Yes, this is because docker automatically creates missing dirs.

The error you are seeing above is specifically because docker is creating a dir where you are expecting a file.

**Comment by thaJeztah** [comment]
I suspect (but not behind my computer at the moment), that it creates an empty directory inside the Docker for Mac VM.

If a folder doesn't exist, the daemon will create an empty folder, and mounts that. However if a file is expected, and doesn't exist, the daemon will create a directory, and  try to mount that on top of a file (which results in an error).

If Docker for Mac doesn't support mounting files or directories from /Applications/, then that's either a bug, or something that should be documented.

**Comment by thaJeztah** [comment]
Oh, see that @cpuguy83 just answered :smile:

**Comment by bizmate** [comment]
@cpuguy83 so it is a bug on docker?
I have tested by checking out other projects where i am using file mounts and I am experiencing the same problem on those projects too.

**Comment by thaJeztah** [comment]
Yes, this is either a bug in Docker for Mac, or something that needs to be documented. Basically, bind-mounting `/Applications/` doesn't seem to do anything on Docker for Mac. Try this;

```bash
docker run  -t --rm -v /Applications/:/my-applications/ alpine sh -c "ls -la /my-applications/"
total 4
drwxr-xr-x    2 root     root            40 May  3 11:18 .
drwxr-xr-x   24 root     root          4096 May  3 11:21 ..
```

@justincormack any ideas? Is this by design, a technical limitation, a bug?

**Comment by thaJeztah** [comment]
@bizmate ok, so it looks like this is documented (perhaps there should be a bigger "note");

https://beta.docker.com/docs/mac/osxfs/#namespaces:39586464d90068604d9e01bcca2f48e1

> You can share files in `/Users`, `/Volumes`, `/private`, and `/tmp` directly. **For the Beta only, the rest of the user-accessible file system is mounted under `/Mac`**.

Basically, XAMPP is using a not-so-good-practice of storing your files inside the Applications directory (it should *really* store these outside of that, e.g. inside your `~/Documents` or `~/Sites` directory - storing data inside `/Applications` is "bad".

If you're no longer using XAMPP (now that you have Docker, which is much more awesome® 😇), I suggest to move your files to a more sane location.

However, if you don't want to move those files there *is* a trick, but **don't rely on this**, as it will probably change in the future. As mentioned above, the Docker for Mac VM currently has a `/Mac` mount that allows you to access any directory on the OS X filesystem. In your case, for example;

    docker run  -t --rm -v /Mac/Applications/XAMPP/htdocs/:/htdocs alpine sh -c "ls -la /htdocs"

Should show the contents of your `/Applications/XAMPP/htdocs/` directory.

Again; don't rely on this, and the other options (moving those files) are a better approach, but I hope it helps 👍

**Comment by bizmate** [comment]
@thaJeztah thanks for pointing that out. I use the XAMPP location as a path that has been there for at least 8 years. Havent used XAMPP for at least 5 years now. Vagrant (puppet, ansible) has been fine for a few years and docker recently makes it all much faster. Moving away from that location is easy enough and i prefer to avoid workarounds when easy enough.

Regarding this issue, i still think a more precise warning/error could be thrown just to make is easier to avoid it.

I will close it now. Thanks for your time

**Comment by thaJeztah** [comment]
You're welcome, and thanks for testing the Beta!
