### ISSUE TITLE
docker swarm overlay network load balancing without docker-machine

### ISSUE THREAD

**Issue by mmkonrad** [docker/docker#22451]
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 40
 Running: 38
 Paused: 0
 Stopped: 2
Images: 54
Server Version: swarm/1.2.0
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 3
 ip-10-43-116-145: 10.43.116.145:2375
  └ Status: Healthy
  └ Containers: 14
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 16.46 GiB
  └ Labels: executiondriver=, kernelversion=3.13.0-74-generic, operatingsystem=Ubuntu 14.04.4 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-05-02T13:57:33Z
  └ ServerVersion: 1.11.0
 ip-10-43-116-146: 10.43.116.146:2375
  └ Status: Healthy
  └ Containers: 13
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 4.052 GiB
  └ Labels: executiondriver=, kernelversion=3.13.0-74-generic, operatingsystem=Ubuntu 14.04.4 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-05-02T13:57:41Z
  └ ServerVersion: 1.11.0
 ip-10-43-116-189: 10.43.116.189:2375
  └ Status: Healthy
  └ Containers: 13
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 4.052 GiB
  └ Labels: executiondriver=, kernelversion=3.13.0-74-generic, operatingsystem=Ubuntu 14.04.4 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-05-02T13:57:26Z#
  └ ServerVersion: 1.11.0
Plugins:
 Volume:
 Network:
Kernel Version: 3.13.0-74-generic
Operating System: linux
Architecture: amd64
CPUs: 8
Total Memory: 24.56 GiB
Name: d462ab2aaa6f
Docker Root Dir:
Debug mode (client): false
Debug mode (server): false
WARNING: No kernel memory limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
 Everything is in AWS -> in a VPC -> in a Subnet.
Every machine runs Ubuntu 14.04.
Instances:
- 3-Worker-Nodes (running containers: consul (client) + registrator + swarm as node)
- 3 Swarm Manager (running containers: consul (client) + swarm as manager)
- 3 Consul Server (running consul natively...work as discovery-backend)
- overlay network created -> all containers run in overlay network

**Steps to reproduce the issue:**
1. on swarm manager have docker-compose-v2-file 
2. run docker-compose file

**Describe the results you received:**
ERROR: for lb  Could not get container for "ourcontainername"

**Describe the results you expected:**
We expected that docker creates the load balancers and balances between services that are running on different hosts (swarm schedules them) on the overlay network.

**Additional information you deem important (e.g. issue happens only occasionally):**
1.  all containers/services are described in compose-file-version-2
2.  all containers run in overlay network
3.  all containers have only internally exposed ports
4.  each service-type has a load balancer (is intended to have....by now it hasn't)
5.  no docker-machine ...just native ubuntu 14.04 instances in aws
6.  load balancer configured like describe here: https://github.com/docker/dockercloud-haproxy

**What actually is intended:**
Remark: Everything runs in AWS on Ubuntu 14.04 machines. It is not intended for production, just for exploration.

So far Swarm works fine. 
We have 3 nodes we can deploy containers to. On each node runs a consul agent and registrator as well as a swarm node container. 
Instead of just a single manager, we have 3 manager running with `--replication` flag. So there is redundancy for the managers...just in case. 
Additionally we have three separate servers with native Consul installation...redundancy...just in case and for testing.
When we are on a swarm manager, we have the descriptions of all our containers (services, databases, message-queues, kv-stores) within docker-compose files of version 2.
Swarm schedules them along our three nodes, they get registrated, find each other and work as intended.

But now we want to add load balancing to the system using dockercloud/haproxy as described here: https://github.com/docker/dockercloud-haproxy.

(But so far, our three nodes have three different IP-addresses, that are used for service discovery. Internally every node has its docker bridge at 172.17.0.1 and every container has a docker ip address like 172.17.0.4. Since there are three nodes, each docker ip might be used three times.)

**Since dockercloud/haproxy uses links and cross node linking is not part of the system out of the box, it was our intention to create a unified view of the cluster with an overlay network. Then we want to run all containers in that overlay network and load balance between services that will be scaled.** 

Maybe that is the first point where we make mistakes or misunderstand how docker and networking works.

For the creation of the overlay network we followed this guide:https://docs.docker.com/engine/userguide/networking/get-started-overlay/
..but without docker-machine and virtual-box. Just ubuntu.

The creation of the overlay network worked and all containers were scheduled among the nodes. But when starting the load-balancers (one for each service that will be scaled) we receive the following error:
**ERROR: for lb  Could not get container for "ourcontainername"**

Our suspicion is that e.g. the `--swarm-discovery="consul://$(docker-machine ip mh-keystore):8500" \` flag, that is used with docker-machine when setting up the swarm, has something to do with that. So far we haven't found an equivalent for a native setup....That is the reason for the headline.

But it is more likely that we have some conceptual misunderstandings...don't we?

Do these information give a sufficient overview of what the situation is and what our intentions are?

**Comment by thaJeztah** [comment]
I suspect this was opened by mistake, but provide more information if this was a feature request. I'll close this issue for now.

**Comment by mmkonrad** [comment]
@thaJeztah  At first yes....I clicked on create to soon, but now the informations are included...please reopen

**Comment by thaJeztah** [comment]
I'll reopen, but you should be able to edit your post if it's closed

**Comment by mmkonrad** [comment]
@thaJeztah thx

**Comment by mmkonrad** [comment]
updated post at the bottom with sub-headline: **What actually is intended:**

**Comment by mmkonrad** [comment]
@thaJeztah @cpuguy83 are these information sufficient or do you need other specifics?

**Comment by thaJeztah** [comment]
@mmkonrad I think it's clear, if I understand correctly, you want to know;

- how to setup an overlay network for Swarm, without using docker-machine?
- how to configure a load-balancer (e.g. dockercloud-haproxy) to load-balance between containers on different nodes?

Correct?

**Comment by mmkonrad** [comment]
@thaJeztah yes, a combination of these points....an overlay-network on all my cluster-nodes, that will be part of a swarm with the ability to perform load-balancing of containers(services) no matter what node of the swarm they are located on

**Comment by mmkonrad** [comment]
Any idea?

**Comment by mavenugo** [comment]
@mmkonrad can you pls confirm if the containers in the overlay network (across the swarm hosts) can communicate with each other ? If they do, then you have configured swarm with overlay networking properly.
BTW, as of 1.11 release, one can run a simple internal load-balancer using the built-in DNS implementation. Read more about it : https://medium.com/@lherrera/poor-mans-load-balancing-with-docker-2be014983e5#.5ri288muo. This works for overlay networks as well.

But if you are looking to use HA-Proxy mechanism, then make sure the HA-Proxy container also runs in the overlay network. If not, the load-balancer will not be able to reach the containers inside the overlay network using the IP-Addresses in the overlay network.

**Comment by mmkonrad** [comment]
@mavenugo I can confirm that **NOW** all containers across our hosts, which are part of the swarm, can communicate with each other.
That is tested with 
a) an ubuntu:14.04 container that got deployed on all involved nodes on the overlay network that is started with bash and can successfully ping to all other containers on the overlay network no matter what node they are located on (swarm node/manager)
and b) our services (especially the rabbitMQs) find each other with links while being deployed on another node

That hasn't been this way until today....What has changed you might ask?

We changed the `cluster-store` from a `consul` to and `etcd` server in version 2.3.3:
Content of `/etc/default/docker`: `DOCKER_OPTS="-H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock --cluster-advertise eth0:2375 --cluster-store etcd://10.43.116.188:2379"`
 (Today we also tried etcd version 2.2.3 (because of a typo) and that "old" version of etcd didn't work as well)

Only one machine (.188) runs an etcd server. All other nodes point with their `DOCKER_OPTS` to that machine.

**So far the overlay network works.**

But yet I haven't been able to test the load balancing. Maybe I can start to try today or I will do it on monday. Then I will make reports.

Even though the plain containers work and can communicate with each other (lb not tested yet) there is another issue. When checking the logs of docker (`/var/log/upstart/docker.log`) on every involved node, they are full with:
```
time="2016-05-19T13:31:04.920464350Z" level=error msg="could not resolve peer \"10.43.116.179\": timed out resolving peer by querying the cluster"
time="2016-05-19T13:31:05.920776346Z" level=error msg="could not resolve peer \"10.43.116.157\": timed out resolving peer by querying the cluster"
time="2016-05-19T13:31:10.680380269Z" level=error msg="could not resolve peer \"10.43.116.135\": timed out resolving peer by querying the cluster"
time="2016-05-19T13:31:11.680759990Z" level=error msg="could not resolve peer \"172.18.0.11\": timed out resolving peer by querying the cluster"
time="2016-05-19T13:31:12.681061818Z" level=error msg="could not resolve peer \"10.43.116.151\": timed out resolving peer by querying the cluster"
time="2016-05-19T13:31:13.681349340Z" level=error msg="could not resolve peer \"172.18.0.2\": timed out resolving peer by querying the cluster"
time="2016-05-19T13:31:18.296336445Z" level=error msg="could not resolve peer \"10.43.116.155\": timed out resolving peer by querying the cluster"
time="2016-05-19T13:31:21.176306545Z" level=error msg="could not resolve peer \"172.18.0.9\": timed out resolving peer by querying the cluster"
time="2016-05-19T13:31:22.176604242Z" level=error msg="could not resolve peer \"172.18.0.10\": timed out resolving peer by querying the cluster"
time="2016-05-19T13:31:23.176860337Z" level=error msg="could not resolve peer \"172.18.0.6\": timed out resolving peer by querying the cluster"
time="2016-05-19T13:31:24.177194011Z" level=error msg="could not resolve peer \"10.43.116.149\": timed out resolving peer by querying the cluster"
```
There are IP addresses of involved nodes of the swarm (10.43.XXX.YYY), `docker_gwbridge`s of various nodes (172.18.XXX.YYY) and even other machines our services push files to with filebeat (but are not part of swarm or overlay network) and a machine that previously held the etcd-server but now is not connected to our cluster in any way (no one is pointing at him and vice versa).

As far as they don't show critical failures we are fine but such a massive amount of identical messages across all our nodes does not look like a healthy cluster/system.

So far thanks for responding and I will keep you up to date on the load-balancing.

**Comment by mmkonrad** [comment]
@mavenugo Thx for hint with dns. At a first glance it seems to be the solution we needed.
`dockercloud/haproxy` has a solution for swarm and overlay as well, but still has some issues. But that does not belong here and will be taken care of.

If today's tests work well, I am going to close this issue.

Cheers
mmkonrad

**Comment by mmkonrad** [comment]
The Docker DNS-Solution for user-defined networks (overlay) work and satisfy our needs
