### ISSUE TITLE
Broken link in the README.md

### ISSUE THREAD

**Issue by aurelien-git** [docker/docker#22467]
**Output of `docker version`:**

Git version
(paste your output here)
Docker began as an open-source implementation of the deployment engine which powers dotCloud, a popular Platform-as-a-Service. It benefits directly from the experience accumulated over several years of large-scale operation and support of hundreds of thousands of applications and databases.

**Output of `docker info`:**

```
broken link about dotCloud
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. click the link
2. get the https to http
3. that bring to the right page

**Describe the results you received:**
Broken link

**Describe the results you expected:**
Right page: https://cloud.docker.com/

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
hm, actually, since this is referring to the original "dotCloud" (not the new cloud.docker.com), perhaps we should change it to the wikipedia page https://en.wikipedia.org/wiki/DotCloud, or an archive link http://web.archive.org/web/20130530031104/https://www.dotcloud.com/

**Comment by thaJeztah** [comment]
opened a pull request; https://github.com/docker/docker/issues/22468
