### ISSUE TITLE
Should docker configuration reloading emit an event?

### ISSUE THREAD

**Issue by allencloud** [docker/docker#22463]
Hi, All,

Configuration Reloading is an awesome feature for users to dynamically configure docker daemon.

And docker event api can be used to monitor how docker works. With docker event api plugin in my application, I can do lots of things automatically without doing the roll polling.

And currently, we can reload docker daemon's configuration. However we have no way to get reloaded configuration, and even worse our program has no way to be noticed that config has changed. And I think this is not a good way to experience Docker.

Can docker emit an event when configuration reload?

**Comment by vdemeester** [comment]
I think it make sence yes :wink: 
/cc @calavera @thaJeztah @icecrime

**Comment by thaJeztah** [comment]
Hm, thinking what kind of event that would be; basically, all events we have right now are related to things that *run* in docker (networks, images, containers), not docker *itself*. Adding this would add a whole new "class" of events (`daemon start`, `daemon stop`, `daemon reload`). Perhaps it makes sense, just trying to think how it would fit in

**Comment by HackToday** [comment]
Not sure if I can get any doc about daemon reload, Have we supported daemon config dynamic reload ?

**Comment by thaJeztah** [comment]
@HackToday a limited number of configuration settings can be reloaded without restarting the daemon; see https://docs.docker.com/engine/reference/commandline/daemon/#configuration-reloading

**Comment by yongtang** [comment]
I created a PR #22590 to add daemon events (`daemon start`, `daemon stop`, `daemon reload`). Please let me know if there are any issues or there is any changes that need to make.

**Comment by yongtang** [comment]
#dibs
