### ISSUE TITLE
--log-driver fluentd fails with "getsockopt: connection refused" on OS X Beta

### ISSUE THREAD

**Issue by atamon** [docker/docker#22464]
Hi, I'm having trouble with the fluentd log driver on my Docker for OS X Beta. Filing this as a bug as I can't find any information that helps me with this issue.

Thanks in advance for your time!

**Output of `docker version`:**

```
> docker version
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   a5315b8
 Built:        Tue Apr 26 15:23:39 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
> docker info
Containers: 9
 Running: 0
 Paused: 0
 Stopped: 9
Images: 451
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 405
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 4.4.6-moby
Operating System: Alpine Linux v3.3
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.956 GiB
Name: docker
ID: IQ3N:FMLI:XBE7:2KIE:5VHM:2RDU:JDIR:XRDN:XGDE:YFNE:TNRZ:ZAEG
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 202
 Goroutines: 318
 System Time: 2016-05-03T06:59:17.593115487Z
 EventsListeners: 85
Username: atamon
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Docker Beta on OS X El Capitan (10.11.1 (15B42))

**Steps to reproduce the issue:**
1. `docker run -p 24224:24224 fluent/fluentd:latest`
2. `docker run --log-driver fluentd docker/whalesay cowsay boo`

**Describe the results you received:**
```
docker: Error response from daemon: Failed to initialize logging driver: dial tcp 127.0.0.1:24224: getsockopt: connection refused.
```

**Describe the results you expected:**
A successful run of the whalesay container.

**Additional information you deem important (e.g. issue happens only occasionally):**
The fluentd container reports no errors, and its logs end with `2016-05-03 07:09:04 +0000 [info]: listening fluent socket on 0.0.0.0:24224`.

If I check the syslog after starting fluentd I get:
```
> syslog -k Sender Docker
May  3 09:05:29 Antons-MacBook-Pro Docker[59382] <Notice>: Creating resource Entry(tcp:0.0.0.0:24224)
May  3 09:05:29 Antons-MacBook-Pro Docker[59382] <Notice>: Write offset=0 data=[tcp:0.0.0.0:24224:00015ea0] to file
May  3 09:05:29 Antons-MacBook-Pro Docker[59382] <Notice>: Created instance tcp:0.0.0.0:24224:00015ea0
```

Please tell me if I'm doing something wrong or if this might actually be a bug with the OS X Beta. I've tried using the different logging options that fluentd supports according to https://docs.docker.com/engine/admin/logging/fluentd/ but to no avail.

Thanks for your time,
Cheers!

**Comment by thaJeztah** [comment]
Yes, it seems that Docker for Mac acts a bit different here, and doesn't work with localhost / 127.0.0.1 here. Some quick 'n dirty ways to make it work;

- use the external IP-address of your machine as `--log-opt fluend-address=<external-ip>: 24224`
- use the IP address of the container that fluentd runs in (this is tricky, because the IP address will change if that container restarts)
- use the Gateway address for the bridge network; `docker inspect --format "{{ .NetworkSettings.Gateway }}" fluentd-container`

**Comment by justincormack** [comment]
Hi, this works on the master branch of Docker for Mac, we will be doing a release later today, if you could re-check that would be great. I think this was a known issue with the last beta that we have now fixed.

**Comment by atamon** [comment]
Thanks @thaJeztah and @justincormack. I'll check get back to you with more info as soon as I get the new Docker release.

**Comment by atamon** [comment]
Yeah everything works now that I got the 1.11.1-beta10 upgrade!

Way to go guys!

```sh
> docker run --log-driver fluentd docker/whalesay cowsay boo
 _____
< boo >
 -----
    \
     \
      \
                    ##        .
              ## ## ##       ==
           ## ## ## ##      ===
       /""""""""""""""""___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
       \______ o          __/
        \    \        __/
          \____\______/
```

**Comment by rolele** [comment]
I am having an error while using fluentd-address
````
docker run --log-driver=fluentd --log-opt fluend-address=192.168.99.100:24224 -d -p 80:80 nginx                                                     14:17
docker: Error response from daemon: unknown log opt 'fluend-address' for fluentd log driver.
See 'docker run --help'.
````

/etc/td-agent/td-agent.conf
````
<source>
type forward
port 24224
bind 0.0.0.0
</source>
<match docker.**>
type stdout
</match>
`````

**Comment by rolele** [comment]
I am having trouble to setup fluentd as well
````
docker run --log-driver=fluentd --log-opt fluentd-address=192.168.99.100:24224 -d -p 80:80 nginx                                                    14:22
949c2f637b67f810ff3cd0b6be96b5453fa061ee18ac904edddc83b2c0bed927
docker: Error response from daemon: Failed to initialize logging driver: dial tcp 192.168.99.100:24224: getsockopt: connection refused.
````
docker-machine ls                                                                                                                                                                                                                                                                     
```
14:23
NAME              ACTIVE   DRIVER       STATE     URL                         SWARM             DOCKER    ERRORS
bigmachine1       *        virtualbox   Running   tcp://192.168.99.100:2376                     v1.12.1
````

 /etc/td-agent/td-agent.conf
```
<source>
type forward
port 24224
bind 0.0.0.0
</source>
<match docker.**>
type stdout
</match>
````
docker version                 
````
                                                                                                                     14:24
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep  8 10:31:18 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
````

**Comment by rolele** [comment]
my mistake was that I installed fluentd on my mac (host) but I was pointing fluentd to boot2docker (192.168.99.100). for now I just used a fluentd-container to try it in development mode
````
docker run -it -p 24224:24224 -d -v fluentd.conf:/fluentd/etc/fluentd.conf fluent/fluentd:latest
docker run --log-driver=fluentd -d -p 80:80 nginx
`````

**Comment by jnathanh** [comment]
I also got this error, but I just needed to map the port in my docker-compose file:

```
ports:
  - 24224:24224
```

**Comment by arbutt1010** [comment]
Hi all I'm getting same issue in 2024 after 8 years even I have by-passed docker client version from 1.12.1 to all the way **26.1.0**

`docker version`

> Client: Docker Engine - Community
>  Version:           26.1.3
>  API version:       1.453",
>  Go version:        go1.21.10
>  Git commit:        b72abbb
>  Built:             Thu May 16 08:34:39 2024
>  OS/Arch:           linux/amd64
>  Context:           default
> 
> Server: Docker Engine - Community8",
>  Engine:
>   Version:          26.1.3
>   API version:      1.45 (minimum version 1.24)etc/host                                                                                        
>   Go version:       go1.21.10etc/hosts                                                                             Modified  
>   Git commit:       8e96db1etc/hosts                                                                                       
>   Built:            Thu May 16 08:33:34 2024
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          1.6.32
>   GitCommit:        8b3b7ca2e5ce38e8f31a34f35b2b68ceb8470d89
>  runc:
>   Version:          1.1.12
>   GitCommit:        v1.1.12-0-g51d5e94
>  docker-init:
>   Version:          0.19.0
>   GitCommit:        de40ad0

`docker info`

> Client: Docker Engine - Community
>  Version:    26.1.3
>  Context:    default
>  Debug Mode: false
>  Plugins:
>   buildx: Docker Buildx (Docker Inc.)
>     Version:  v0.14.0
>     Path:     /usr/libexec/docker/cli-plugins/docker-buildx
>   compose: Docker Compose (Docker Inc.)
>     Version:  v2.27.0
>     Path:     /usr/libexec/docker/cli-plugins/docker-compose
> 
> Server:
>  Containers: 11
>   Running: 9
>   Paused: 0
>   Stopped: 2                                                                                 docker:default
>  Images: 13                                                                                           0.0s
>  Server Version: 26.1.3                                                                                           0.0s
>  Storage Driver: overlay2                                                                                           0.1s
>   Backing Filesystem: xfs                                                                                           0.0s
>   Supports d_type: true                                                                                           0.0s
>   Using metacopy: falsefe90a34a975508d79991c54a6b8ea22d4                                                          0.0s
>   Native Overlay Diff: trueual .build-deps     sudo build-base ruby-dev     && sudo gem install fluent-plugin-graylo  0.0s
>   userxattr: false                                                                                           0.0s
>  Logging Driver: json-file                                                                                           0.0s
>  Cgroup Driver: cgroupfs                                                                                           0.0s
>  Cgroup Version: 1                                                                                           0.0s
>  Plugins:
>   Volume: local                                                                                           0.0s 
>   Network: bridge host ipvlan macvlan null overlay                                                                                           0.0s 
>   Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog                                                                                           0.0s 
>  Swarm: inactive                                                                                           0.0s 
>  Runtimes: io.containerd.runc.v2 runc                                                                                           0.0s 
>  Default Runtime: runc                                                                                           0.0s 
>  Init Binary: docker-init                                                                                           0.0s 
>  containerd version: 8b3b7ca2e5ce38e8f31a34f35b2b68ceb8470d89                                                                                           0.0s 
>  runc version: v1.1.12-0-g51d5e94                                                                                           0.0s 
>  init version: de40ad0ginx, opensearch, portainer, postgres
>  Security Options:driver: dial tcp 192.168.10.10:24224: connect: connection refused
>   seccomp
>    Profile: builtinATUS                   PORTS                                                                    
>  Kernel Version: 4.18.0-553.22.1.el8_10.x86_64
>  Operating System: Red Hat Enterprise Linux 8.10 (Ootpa) 2 hours               5140/tcp, 0.0.0.0:24224->24224/tcp, 0.0.0.0:24224->24224/udp             
>  OSType: linux
>  Architecture: x86_64 2 hours (unhealthy)   27017/tcp                                                                
>  CPUs: 4
>  Total Memory: 15.23GiB 9 hours (healthy)     0.0.0.0:3000->3000/tcp                                                   
>  Name: smallchickens
>  ID: 3d76047d-57e7-4e51-bbc3-9fc284d9ad6f 9 hours (healthy)     0.0.0.0:1514->1514/tcp, 0.0.0.0:9000->9000/tcp, 0.0.0.0:1514->1514/udp, 0
>  Docker Root Dir: /var/lib/docker
>  Debug Mode: true 9 hours               8443/tcp, 0.0.0.0:8080->8080/tcp, 9000/tcp                               
>   File Descriptors: 312
>   Goroutines: 1160 9 hours               0.0.0.0:9200->9200/tcp, 9300/tcp                                         
>   System Time: 2024-10-04T12:16:48.865594665Z
>   EventsListeners: 0 9 hours               0.0.0.0:5432->5432/tcp                                                   
>  Experimental: false
>  Insecure Registries: 9 hours               8000/tcp, 9000/tcp, 0.0.0.0:9443->9443/tcp                               
>   127.0.0.0/8
>  Live Restore Enabled: false 9 hours (healthy)     0.0.0.0:3306->3306/tcp                                                   
>  Default Address Pools:
>    Base: 192.168.46.0/16, Size: 24

Below is my **docker-compose.yml** file

> services:
>   nextcloud:
>     image: nextcloud:latest
>     container_name: nextcloud
>  #   links:
>  #     - fluentd
>     logging:
>       driver: "fluentd"
>       options:
>         fluentd-address: fluentd:24224
>         tag: nextcloud.logs
>     restart: unless-stopped
>     volumes:
>       - ./global_logs/nextcloud_logs:/var/www/html/data/nextcloud.log
>       - ./nextcloud:/var/www/html
>       - ./sociallogin:/tmp/apps/sociallogin
>       - ./theming_customcss:/tmp/apps/theming_customcss
>       - ./theming:/tmp/theming
>       - ./app-hooks/before-starting:/docker-entrypoint-hooks.d/before-starting
>     depends_on:
>       mariadb:
>         condition: service_healthy
>     networks:
>       - nextcloud-net
> 
>   fluentd:3",
>     build:
>       context: ./fluentd
>       dockerfile: Dockerfile
>     container_name: fluentd
>     depends_on:
>       - graylog
>       - opensearch8",
>     volumes:
>       - ./global_logs/nextcloud_logs:/var/log/containers/nextcloud_logs
>       - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf 
>       - ./fluentd/fluentd_log:/fluentd/log
>     ports:
>      - "24224:24224"
>      - "24224:24224/udp"
>     environment:
>       FLUENTD_CONF: "fluent.conf"
>     networks:
>      - nextcloud-net
>      
> networks:
>   nextcloud-net:
>     driver: bridge

Below is my **fluent.conf** file

> <source>
>   @type forward
>   port 24224
>   bind 0.0.0.0
> </source>
> 
> <source>
>     @type tail
>     @label @nextcloud_logs
>     path /var/log/containers/nextcloud_logs/*nextcloud*.log
>     pos_file /var/log/containers/nextcloud.log.pos
>     tag nextcloud.logs
>     read_from_head true
>     <parse>
>       @type json
>       time_format %Y-%m-%dT%H:%M:%S.%NZ
>     </parse>
> </source>
> 
> <label @nextcloud_logs>
>   <match nextcloud.logs>
>     @type gelf
>     host graylog:9000
>     port 12201
>     protocol udp
>     <buffer>
>       flush_interval 5s
>     </buffer>
>   </match>
> </label>


When I run **docker compose up --build** 

Getting below error
**Error response from daemon: failed to create task for container: failed to initialize logging driver: dial tcp: lookup fluentd on my-ec2-instance-public-ip-address:53: no such host**


I have tried to these solutions in this issue
https://github.com/moby/moby/issues/22464#issuecomment-216546128

Can someone please help me. Thanks
