### ISSUE TITLE
Support sharing pid namespaces between containers

### ISSUE THREAD

**Issue by mrunalp** [docker/docker#22479]
Allow sharing pid namespaces between container like we do for ipc, network, etc today.
This allows one to create debug containers that can attach to a running container and ptrace them.
The syntax will be similar to `--ipc`, i.e. `--pid:container:<container_id>`

**Comment by mrunalp** [comment]
@crosbymichael @LK4D4 @thaJeztah ping

**Comment by thaJeztah** [comment]
Sounds good to me :+1:

**Comment by HackToday** [comment]
Seems reasonable case, and I remembered this feature was discussed before ? 😺

**Comment by justincormack** [comment]
This is useful to work around some of the lack of control of eg security features such as seccomp on `exec` until this is reworked, eg https://github.com/docker/docker/issues/21984

**Comment by hqhq** [comment]
I did it before in https://github.com/docker/docker/pull/13453 , not have a chance to rework that. Glad to see we already have a WIP pr for that, thanks @mrunalp

**Comment by IanLewis** [comment]
This is a dup of #10163

**Comment by thaJeztah** [comment]
@IanLewis ah, yes, it was mentioned in the PR, but I see the PR didn't have the right `closes #xx`.

This feature is implemented in https://github.com/docker/docker/pull/22481, and will be in docker 1.12, so we can close this 👍
