### ISSUE TITLE
[Feature Request] Add config parameter to change stop timeout for containers or globally

### ISSUE THREAD

**Issue by notes-jj** [docker/docker#22471]
The default timeout for `docker stop <container>` is 10 seconds.

This time sometimes not enough to reach consistency on the file space for databases like MySQL or InfluxDB. This is not a problem for manual start and stop, so you can define the timeout with e.g. `docker stop -t 60 <container>

**Problem**: If you stop the docker daemon or reboot the machine the timeout will be 10 seconds by default and that might screw up databases, because the time is to short to reach database file space consistency.

**Suggestion 1**: Implement a parameter for the docker daemon to change the global default timeout.
**Suggestion 2**: Implement a parameter for the docker containers to change the container default timeout.

I'm using Docker version 1.11.0, build 4dc5990

**Comment by cpuguy83** [comment]
Docker 1.12 should have the ability to restart without killing containers.

**Comment by pataquets** [comment]
+1 to an ```/etc/default/docker``` configurable parameter to specify a different default timeout.
There are some cloud servers where I would like to just fire an ACPI shutdown (from crontab or externally) at any time without the risk of killing the containers too early. Supporting the -1 value to wait undefinitely would be great for some cases, too (at the obvious risk of hanging too much on shutdown).

**Comment by cpuguy83** [comment]
@pataquets As stated above, this situation is not likely to be a problem on 1.12 since the daemon will be able to be shutdown w/o killing containers.

**Comment by pataquets** [comment]
Great! I wasn't sure if it was meant only for Engine service restart or for service stopping, too.
Thanks.

**Comment by tarantegui** [comment]
Definetly it will be an awesome feature @cpuguy83!

**Comment by yongtang** [comment]
I added a PR #22500 so that a timeout value to stop containers during the daemon shutdown could be specified. Note this only applies when daemon is being shutdown with SIGINT or SIGTERM.

**Comment by yongtang** [comment]
I just created another new PR #22566 to address this issue.

**Comment by wjimenez5271** [comment]
+1

**Comment by notes-jj** [comment]
+1

**Comment by syepes** [comment]
+1

**Comment by skipor** [comment]
Actully, no `config parameter to change stop timeout for containers or globally` was added. `--stop-timeout` per-container flat works well, but daemon `shutdown-timeout` option is not working as expected. Discussed in https://github.com/moby/moby/issues/32357
