### ISSUE TITLE
Problem with ulimit docker 1.11.1 on Ubuntu 16.04

### ISSUE THREAD

**Issue by jplu** [docker/docker#22476]
Hello,

I have an issue with the ulimit values in all my containers. Accordingly to the documentation, the docker daemon and its containers takes the ```ulimits``` values from the host. Surprisingly, for me, this is currently the case except for the ```max locked memory``` property.

**Output of `docker version`:**

```
Docker version 1.11.1, build 5604cbe
```

**Output of `docker info`:**

```
Containers: 12
 Running: 0
 Paused: 0
 Stopped: 12
Images: 37
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 45
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.0-21-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 20
Total Memory: 62.94 GiB
Name: data
ID: SUKP:6AXK:Y74H:TUVZ:4FGL:E67F:OV3E:YHHC:HF55:KVLE:AVGI:MCXV
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Steps to reproduce the issue:**
1. On the host run: ```ulimit -a```
2. On the host run: ```docker run -it ubuntu:14.04 /bin/bash``` 
3. In the container run: ```ulimit -a```

**Describe the results you received:**

With the command in 1. I get:

```
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 369645
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 40960
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 369645
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Describe the results you expected:**

With the command in 3. I get:

```
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 369645
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1048576
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

As one can see, the value of the ```max locked memory``` is different. The properties ```max user processes``` and ```open files``` are different as apparently they are redefined in the ```/etc/init.d/docker``` script.

**Additional information you deem important (e.g. issue happens only occasionally):**

My ```/etc/security/limits.conf``` configuration file looks like this:

```
*               soft    core            unlimited
*		hard	core		unlimited
*		soft	nofile		40960
*		hard	nofile		40960
*		soft	memlock		unlimited
*		hard	memlock		unlimited
root            soft    core            unlimited
root            hard    core            unlimited
root            soft    nofile          40960
root            hard    nofile          40960
root            soft    memlock         unlimited
root            hard    memlock         unlimited
```

I would like to know if this behavior is an error that comes from my side because I may have forget to do something in particular, or if it is an issue from Docker?

Thanks in advance.

**Comment by cpuguy83** [comment]
Values of `ulimit -a` from a shell are going to be different than values started from the init system.
Note that on 16.04, unless otherwise configured, docker is probably being started by systemd. The unit file for systemd is `/lib/systemd/system/docker.service`

Closing as this is really a non-issue.

**Comment by jplu** [comment]
Thanks, updating the ```/lib/systemd/system/docker.service``` file solved the problem.
