### ISSUE TITLE
Docker for Mac beta status

### ISSUE THREAD

**Issue by JoyceBabu** [docker/docker#22484]
I am sorry, I have been trying my best not to post this here, but finally my eagerness got the better of me. I signed up for the beta within 24 hours of the announcement, and have been checking my email every day expecting an invite. I haven't received one yet and I keep seeing tweets and posts from people saying how good it is.

How is the beta going? How long is the beta invite list? How often does docker send out beta invites? Are the invitees selected on first come first serve basis? And most importantly, is there an end in sight to this waiting?

**Comment by JoyceBabu** [comment]
Closing the issue as it is off-topic. But if anyone has answers to my questions above, please respond.

**Comment by FrenchBen** [comment]
🐳 📨

**Comment by JoyceBabu** [comment]
Any update on this? 😞

**Comment by unclejack** [comment]
@JoyceBabu Please get in touch with Docker Inc using this form https://goto.docker.com/contact-us.html

This issue tracker is for the open source Docker Engine. Generally speaking, you'll find the Docker Engine community on this issue tracker and we can't help with Docker for Mac beta/Docker for Windows beta.

Docker Inc. should also be able to provide more information after your inquiry.

**Comment by JoyceBabu** [comment]
I had already tried contacting them by replying to the confirmation email. I was hoping someone here would be having information on how it is going.

**Comment by JoyceBabu** [comment]
I just found out that I had received the invitation earlier. Gmail tagged it as 'Promotion' and hid it somewhere. A search for mails from docker.com turned it up. 😃

**Comment by styfle** [comment]
> A search for mails from docker.com turned it up.

@JoyceBabu I just realized I got an invite a month ago! Thanks for pointing that out 😄
