### ISSUE TITLE
Dockerfile instructions for run -i and -t

### ISSUE THREAD

**Issue by AndreKR** [docker/docker#22480]
Right now every Dockerfile has to be distributed with a run script or a readme that documents whether it needs to be `run` with `-it`, `-i` or neither.

There should be a way to store this in the image by an instruction in the Dockerfile.

There was already an issue #1870 for this, but it was closed in favor of #4955 and then in turn #4882. I think this was by accident because the MR is not actually related to this feature, it just removes a buggy, incomplete implementation of a similar feature.

**Comment by thaJeztah** [comment]
I understand your thinking, but I don't think we should do this. I think we should keep "runtime" configuration separate from the image. Although *some* images may require you to run them interactively, most images can actually be used in multiple ways. For example, the MySQL image can both be used as a server (non interactively), or as a client (interactively). The image should not dictate how to use it, and specifying that a TTY or "interactive" is required, would limit the usefulness of such an image.

Adding this would be a sliding slope; should we add Dockerfile instructions for the image requiring certain environment variables to be set, a network connection, a different container to be started first?

For runtime configuration, docker-compose can fulfill most of those things; providing a (sample) `docker-compose.yml` with the right settings, or just good documentation for the image is probably a better approach.

**Comment by AndreKR** [comment]
I see your point. The difference to network and dependency etc. options is that `-i` and `-t` feel like workarounds. Ideally they would just work automatically, but I'm not sure that's possible.

In fact I haven't looked into using docker-compose for this, I should do that. Maybe we should rename `docker`to `docker-client` and `docker-compose` to `docker` then. :)

For now I have resorted to running an SSHd in my containers anyway, because the docker terminal is extremely unreliable, with its random crashes (#22345) and broken arrow keys (because the terminal ignores some ESC sequences) and such.

**Comment by thaJeztah** [comment]
> For now I have resorted to running an SSHd in my containers anyway, because the docker terminal is extremely unreliable

Yes, I think there's still issues around terminal emulation on Windows
