### ISSUE TITLE
Enable digest authentication on pull by tag

### ISSUE THREAD

**Issue by dnwake** [docker/docker#22492]
As far as I can tell, [docker pull by tag skips digest authentication](https://github.com/docker/docker/blob/c18d03a7783bb78b7568bf3c23644888995e9a5d/distribution/pull_v2.go#L762) (assuming Content Trust is not enabled). 

This means that, if I want to get the verified digest of an image originally pulled by tag, I have to:
1. repull the image by tag (hoping that the tag hasn't changed reference)
2. capture the "Digest" output from the command line output of the pull
3. repull explicitly by digest

It would be great if there were an option to require authentication of the digest found in the manifest, even when pulling by tag.  That authenticated digest could then be visible on "docker inspect" as already [requested in this issue](https://github.com/docker/docker/issues/17670).

**Output of `docker version`:**
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      linux/amd64

**Additional environment details (AWS, VirtualBox, physical, etc.):**
docker-machine version 0.6.0, build e27fb87

**Comment by aaronlehmann** [comment]
> It would be great if there were an option to require authentication of the digest found in the manifest, even when pulling by tag. That authenticated digest could then be visible on "docker inspect" as already requested in this issue.

The digest you see from `docker pull` is a digest of the manifest itself, not a digest that appears inside the manifest. The manifest has various digests inside it for items it references, such as filesystem layers. These digests are always checked, whether you pull by tag or by digest.

When pulling by tag without Content Trust, we can't securely verify the manifest's digest, because we don't have a trusted digest to compare it to.

I think Content Trust is the right way to securely pull by tag.

**Comment by dnwake** [comment]
> The digest you see from docker pull is a digest of the manifest itself, not a digest that appears inside the manifest

In my own testing, the digest that appears on "docker pull" without Content Trust is the same as the digest that pulled explicitly when using Content Trust.  I can also get the same digest by calling the docker registry API.  For example:


## pull without content trust
**unset DOCKER_CONTENT_TRUST
docker pull registry-server:5000/bad_image:latest**
latest: Pulling from bad_image
Digest: sha256:fc9b672afaee2f93eda190e0a686d9c56c01d00d8a0701db2193f0f0e1d0c1d5
Status: Downloaded newer image for registry-server:5000/bad_image:latest

## pull with content trust
**export DOCKER_CONTENT_TRUST=1
export DOCKER_CONTENT_TRUST_SERVER=https://notary-server:4443
docker pull registry-server:5000/bad_image:latest**             '
Pull (1 of 1): registry-server:5000/bad_image:latest@sha256:fc9b672afaee2f93eda190e0a686d9c56c01d00d8a0701db2193f0f0e1d0c1d5
sha256:fc9b672afaee2f93eda190e0a686d9c56c01d00d8a0701db2193f0f0e1d0c1d5: Pulling from bad_image
Digest: sha256:fc9b672afaee2f93eda190e0a686d9c56c01d00d8a0701db2193f0f0e1d0c1d5
Status: Image is up to date for registry-server:5000/bad_image@sha256:fc9b672afaee2f93eda190e0a686d9c56c01d00d8a0701db2193f0f0e1d0c1d5

## use the Registry API
**curl -vvv -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
  http://registry-server:5000/v2/bad_image/manifests/latest 2>&1 | grep Docker-Content-Digest**
< Docker-Content-Digest: sha256:fc9b672afaee2f93eda190e0a686d9c56c01d00d8a0701db2193f0f0e1d0c1d5

> When pulling by tag without Content Trust, we can't securely verify the manifest's digest, because we don't have a trusted digest to compare it to.

I'm probably misunderstanding something here:  why would it ever be insecure to verify the digest of an image?

**Comment by aaronlehmann** [comment]
> I'm probably misunderstanding something here: why would it ever be insecure to verify the digest of an image?

To properly verify it, you need to know what digest to expect. It doesn't add any security to check against the `Docker-Content-Digest` returned by the registry, since if the manifest is replaced with a malicious one, the `Docker-Content-Digest` will also change to match that malicious manifest.

**Comment by dnwake** [comment]
> _I'm probably misunderstanding something here: why would it ever be insecure to verify the digest of an image?_

> To properly verify it, you need to know what digest to expect. It doesn't add any security to check against the Docker-Content-Digest returned by the registry, since if the manifest is replaced with a malicious one, the Docker-Content-Digest will also change to match that malicious manifest.

But you would still have the knowledge that the image did or did not match the digest, right?  If both the image and the digest were altered by a malicious actor, you would still be able to compare the digest with a known good digest (e.g. on a cron job) to find out that the image is malicious.

**Comment by endophage** [comment]
@dnwake in your example pulls above I think you're misinterpreting the output. In the case that content trust is _disabled_, the line `Digest: sha256:fc9b672afaee2f93eda190e0a686d9c56c01d00d8a0701db2193f0f0e1d0c1d5` is showing you the digest generated from the downloaded content, not a digest you already had and could use for verification. It's nonsensical to "validate" this digest because it was literally generated from the downloaded content, you need something else to compare it to and without content trust, there is nothing else.

This is where content trust comes in. In the case with content trust _enabled_, you're using Notary (under the hood) to retrieve a trusted digest. Now that you have a digest, you can use if for verification against a digest generated from the downloaded content.

**Comment by thaJeztah** [comment]
@endophage perhaps @dnwake means that the calculated digest should be compared to a digest sent by the registry to validate that it was downloaded without issues (as a checksum to check if the content arrived correctly), not taking into account "malicious" intent?

**Comment by endophage** [comment]
@thaJeztah that makes sense. We should definitely be clear though it's not a security measure at that point.

**Comment by thaJeztah** [comment]
@endophage I don't think we need to explicitly mention it, but we can "fail" if the calculated digest doesn't match the expected digest. If they don't match, something is wrong (at least, I would expect something is wrong then)

**Comment by dnwake** [comment]
@endophage 

> In the case that content trust is disabled, the line Digest: sha256:fc9b672afaee2f93eda190e0a686d9c56c01d00d8a0701db2193f0f0e1d0c1d5 is showing you the digest generated from the downloaded content,

When you say "generated from the downloaded content" -- you mean that the digest is generated from the entire image, just like the digest that is used in Content Trust?

Perhaps it would help if I spell out a potential use-case:

-  Kubernetes pulls from a potentially untrusted registry (by tag)
- Since Kubernetes interacts directly with the Docker daemon without using the CLI, there is no way to leverage Content Trust from Kubernetes
- As a second-best solution, we are thinking of having a cronjob that verifies the integrity of the images that Kubernetes has already pulled
- The idea is that the cronjob will run on the same machine as Kubernetes, and pull the same tagged images using Content Trust, and then compare the images to see whether anything changed.

The problem is knowing the digest of the image initially pulled (without Content Trust) by Kubernetes.  When pulling without Content Trust, the digest field of "docker inspect" does not get set, even though the digest appears to be available.

Thanks for any input.

**Comment by endophage** [comment]
To be absolutely specific, the "downloaded content" is the image manifest, and yes, that is the same digest used by Content Trust. Have you thought about simply using the Notary client library the same way the docker client does? Kubernetes and Notary are both in Go after all :-)

**Comment by dnwake** [comment]
> Have you thought about simply using the Notary client library the same way the docker client does? Kubernetes and Notary are both in Go after all :-)

I tried that, but the dependencies were so entangled I ended up having to import almost the entire Docker source code into Kubernetes.

**Comment by endophage** [comment]
Ah, well that's good feedback for us. We can look at our imports and see if they can be arranged better.

**Comment by dnwake** [comment]
So, if I understand things correctly:

- the manifest contains various digests for the file layers, and we _always_ verify that these correspond to the bits that are actually pulled
- when we pull explicitly by digest (including when we use Content Trust), we also verify that the requested digest corresponds to the bits of the manifest itself.  The requested digest gets put in the image JSON returned by "docker inspect".
- when we pull by tag (without Content Trust) we still calculate the digest of the bits of the manifest and  echo this information to the console output but we then discard it (see https://github.com/docker/docker/issues/17670)

Would it be possible to use the image ID as a kind of proxy for the manifest's digest?  It looks as if the image ID is generated directly from the manifest (at least for schema 2).  I could then 

- get the ID after an insecure pull by tag
- pull the same tag with Content Trust
- reread the ID of the image
- if the IDs are the same, I know that the original image was secure.

Does this sound like a reliable algorithm?  Thanks.

**Comment by aaronlehmann** [comment]
As of Docker 1.10, image IDs are secure hashes of the image's filesystem and configuration. So as long as you are running at least Docker 1.10, this does sound reasonable.

**Comment by dnwake** [comment]
@aaronlehmann  Great -- thanks!

**Comment by endophage** [comment]
@dnwake you would need to push that image ID to notary though, as opposed to the manifest checksum it's currently using.

**Comment by dnwake** [comment]
@endophage Would it not be sufficient to check that the image ID for the tag remains the same before and after a pull with Content Trust?

**Comment by thaJeztah** [comment]
@endophage @aaronlehmann what's the status here? is there something to be done?

**Comment by aaronlehmann** [comment]
@dnwake: Yes, the image ID is a hash of its contents.

I think this can be closed.
