### ISSUE TITLE
dm.min_free_space requires % suffix even though it's present.

### ISSUE THREAD

**Issue by datacarl** [docker/docker#22517]
**Output of `docker version`:**

```
Docker version 1.11.1, build 5604cbe
```

**Output of `docker info`:**
Cant start docker with this setting, but when I remove it and start docker I get 
```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.11.1
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 258.5 MB
 Data Space Total: 15.55 GB
 Data Space Available: 15.29 GB
 Metadata Space Used: 184.3 kB
 Metadata Space Total: 163.6 MB
 Metadata Space Available: 163.4 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.10.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.518 GiB
Name: ip-<redacted>
ID: 3DFB:6B37:GIIQ:CN3Z:23HP:5VAT:OO5S:JL2B:AKPO:VNX2:6KGM:ZLU4
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS centos 7 

**Steps to reproduce the issue:**
1. set `dm.min_free_space=10%`, e.g.
```
[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon --storage-driver=devicemapper --storage-opt=dm.thinpooldev=/dev/mapper/docker-thinpool --storage-opt dm.use_deferred_removal=true --storage-opt dm.min_free_space=10%

[Install]
Also=docker.socket
```
2. Start docker `systemctl start docker`

**Describe the results you received:**
Docker does not start.
`journalctl -u docker` outputs
```
May 04 22:26:38 ip-10-197-232-97 systemd[1]: docker.service failed.
May 04 22:26:40 ip-10-197-232-97 systemd[1]: Started docker.service.
May 04 22:26:40 ip-10-197-232-97 systemd[1]: Starting docker.service...
May 04 22:26:40 ip-10-197-232-97 docker[28037]: time="2016-05-04T22:26:40.875526079Z" level=info msg="New containerd process, pid: 28042\n"
May 04 22:26:40 ip-10-197-232-97 docker[28037]: time="2016-05-04T22:26:40Z" level=warning msg="containerd: low RLIMIT_NOFILE changing to max" current=1024 max=4096
May 04 22:26:41 ip-10-197-232-97 docker[28037]: time="2016-05-04T22:26:41.878838481Z" level=fatal msg="Error starting daemon: error initializing graphdriver: devmapper: Option dm.min_free_space requires % suffix"
May 04 22:26:41 ip-10-197-232-97 systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
May 04 22:26:41 ip-10-197-232-97 docker[28037]: time="2016-05-04T22:26:41Z" level=info msg="stopping containerd after receiving terminated"
May 04 22:26:41 ip-10-197-232-97 systemd[1]: Unit docker.service entered failed state.
May 04 22:26:41 ip-10-197-232-97 systemd[1]: docker.service failed.
```

**Describe the results you expected:**
Docker daemon starts

**Additional information you deem important (e.g. issue happens only occasionally):**
Removing the 10% option, i.e. running with `--storage-opt dm.min_free_space` also errors but with 
`level=fatal msg="Error starting daemon: error initializing graphdriver: Unable to parse key/value option: dm.min_free_space"`.

According to [the documentation](https://docs.docker.com/engine/reference/commandline/daemon/#storage-driver-options) it should default to 10%.

Adding an extra `%` (`--storage-opt dm.min_free_space=10%%`) does not give any errors. The daemon starts. Not sure if the setting is picked up.

**Comment by thaJeztah** [comment]
Yes, this is because `%` characters have a special meaning in systemd unit files, see https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Specifiers, so have to be escaped (using `%%` if you want a literal `%`).

I'll close this issue, because this is not a docker bug, but feel free to comment after I closed

**Comment by datacarl** [comment]
Ah, thanks! 

Shouldn't `--storage-opt dm.min_free_space` still work though? Or am I reading the docs wrong? They say "If user does not specify a value for this option, the Engine uses a default value of 10%."

**Comment by thaJeztah** [comment]
docs could possibly be slightly clearer, and say "if the option is not provided". Although, possibly `--storage-opt dm.min_free_space=` would work (not sure, haven tested)

**Comment by datacarl** [comment]
`--storage-opt dm.min_free_space=` didnt work.

Ok, so 10% is the default and to unset the option you have to pass 0%? Yeah that could be clearer :)

Thanks for the help!

**Comment by thaJeztah** [comment]
Or, don't set the option

**Comment by thaJeztah** [comment]
Oh, you meant to don't have a minimum limit. Hm, I'd discourage doing that, if you run out of space you may get corruption, and you cannot recover from tnat

**Comment by datacarl** [comment]
I want the limit :) By reading the docs I just thought I had to set the option to enforce any limit at all. I guess that interpretation was enforced by reading another issue where this option was discussed and some strong opinions on the admins responsibility to monitor disk space (rather than docker's responsibility to keep the admin from doing dumb things) were shared. But I think the docs could be a bit clearer too.

**Comment by thaJeztah** [comment]
Perhaps you're interested in contributing and opening a pull request to update that documentation; the Markdown file to generate that page is in this repository, and can be found here; https://github.com/docker/docker/blob/master/docs/reference/commandline/dockerd.md#storage-driver-options

And the associated Man page https://github.com/docker/docker/blob/master/man/dockerd.8.md#devicemapper-options
