### ISSUE TITLE
`docker run` documentation could be improved with respect to using digests

### ISSUE THREAD

**Issue by michaelbarton** [docker/docker#22514]
I had some trouble working out the correct way to use `docker run` with the sha256 digest. I found the documentation a little confusing with regard to this. For example the [run reference page][ref] has the following example:

[ref]: https://docs.docker.com/engine/reference/run

```
$ docker run [OPTIONS] IMAGE[:TAG|@DIGEST] [COMMAND] [ARG...]
```
However I had problems trying to run my image this way. For example:

``` bash
docker run namespace/image@digest # Wrong - parse error
docker run namespace/image@sha256:digest # Correct
```
I had to work this out from trial and error. The link to the [Image[@digest]][digest] section anchor doesn't have an example, which I think might have been useful. I believe therefore it might be beneficial to update the documentation regarding using digests.

I suggest the **General Form** section to be:

[digest]: https://docs.docker.com/engine/reference/run/#image-digest

```
$ docker run [OPTIONS] IMAGE[:TAG|@sha256:DIGEST] [COMMAND] [ARG...]
```
If there are other possible digests, then sha256 could be changed to DIGEST_TYPE or something similar.

Secondly I suggest that the [Image[@digest]][digest] anchor have the following example of using the digest:

```
docker run alpine@sha256:9cacb71397b640eca97488cf08582ae4e4068513101088e9f96c9814bfda95e0 date
```

This is my feedback from initially trying to get digests to run with `docker run`. If this was confusing to me, it might possibly be confusing to other users.

**Comment by thaJeztah** [comment]
Thanks!

We do have an example in https://docs.docker.com/engine/reference/commandline/pull/#pull-an-image-by-digest-immutable-identifier, perhaps there are others, but I agree that an example in this case would be useful.

**Comment by sbose78** [comment]
#dibs

**Comment by sbose78** [comment]
Hi @thaJeztah  
Let me know your thoughts on the merge request. 

Thanks,
Shoubhik
