### ISSUE TITLE
Cgroups info on host not updated with cgroupfs

### ISSUE THREAD

**Issue by depay** [docker/docker#22525]
**Output of `docker version`:**

```
Client:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-1000.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      26797f7/1.9.1
 Built:           
 OS/Arch:         linux/amd64

Server:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-1000.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      26797f7/1.9.1
 Built:           
 OS/Arch:         linux/amd64
```

**Output of `docker info`:**

```
Containers: 75
Images: 221
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-8:3-11141173-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 9.603 GB
 Data Space Total: 107.4 GB
 Data Space Available: 97.77 GB
 Metadata Space Used: 26.4 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.121 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /data/docker/devicemapper/devicemapper/data
 Metadata loop file: /data/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-327.13.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 24
Total Memory: 31.25 GiB
Name: xxxxxx
ID: xxxxxx
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
physical
systemd-219-19.el7_2.7.x86_64
libcgroup-0.41-8.el7.x86_64
```

**Steps to reproduce the issue:**
1. update os to latest centos 7.2
2. start docker with `--exec-opt native.cgroupdriver=cgroupfs`
3. cat `/sys/fs/cgroup/cpuacct/system.slice/docker.service/system.slice/<cid>/cpuacct.usage`
4. wait for a moment, then cat that file again

**Describe the results you received:**

data in `cpuacct.usage` is never changed.

**Describe the results you expected:**

data changes as container running.

**Additional information you deem important (e.g. issue happens only occasionally):**

- the same result using `/proc/<pid>/root/sys/fs/cgroup/cpuacct/cpuacct.usage`
- data on host will be modified when using `docker exec`
- `docker exec -it <cid> cat /sys/fs/cgroup/cpuacct/cpuacct.usage` can get the correct result

**Comment by depay** [comment]
Finally i've found the reason, what systemd made the trick.

Add `Delegate=true` or using other cgroup slice except `system.slice` in systemd docker unit will solve this problem.

**Comment by thaJeztah** [comment]
The `Delegate=yes` option was added to our systemd unit file in docker 1.11 (see https://github.com/docker/docker/pull/20633), so I'm closing this then, as I think it's resolved :+1:
