### ISSUE TITLE
Unable to pull windows NET3.5 image

### ISSUE THREAD

**Issue by versofate** [docker/docker#22523]
**Output of `docker version`:**
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   2b97201
 Built:        Tue Apr 26 23:51:36 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   2b97201
 Built:        Tue Apr 26 23:51:36 2016
 OS/Arch:      windows/amd64

**Output of `docker info`:**
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 15
Server Version: 1.12.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: null nat
Kernel Version: 10.0 14300 (14300.1010.amd64fre.rs1_release_svc.160415-2143)
Operating System: Windows Server 2016 Datacenter Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 3.5 GiB
Name: qserver
ID: GLN3:JDAY:X7W6:OCXU:FL3N:4DHH:LPWP:ERH3:CW7N:MN3K:TC2E:CFHH
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**
WS2016TP5 on cloudapp.net

**Steps to reproduce the issue:**
1.Enable container feature in windows server 2016 tp5
2.Get dockerfiles from https://github.com/brogersyh/Dockerfiles-for-windows/archive/master.zip
3.docker build -t sqlexpress .

**Describe the results you received:**
Step 1 : FROM docker.io/microsoft/dotnet35:windowsservercore
windowsservercore: Pulling from microsoft/dotnet35
23ab2a8ad987: Pull complete
a050e0c49af6: Extracting [==================================================>] 246.6 MB/246.6 MB
failed to register layer: convert O:S-1-5-93-2-1G:DUD:P(A;OICI;FA;;;SY)(A;OICI;FA;;;BA)(A;OICI;FA;;;S-1-5-93-2-1): The s
ecurity ID structure is invalid.

and for the all next times it's getting stuck on 23/95 MB:
a050e0c49af6: Extracting [====>                                              ] 23.95 MB/246.6 MB

**Additional information you deem important (e.g. issue happens only occasionally):**
This part of daemon.log seems important:
time="2016-05-05T05:59:00.967544100Z" level=info msg="API listen on //./pipe/docker_engine" 
time="2016-05-05T05:59:29.252857900Z" level=error msg="hcsshim::ImportLayer failed in Win32: The system cannot find the path specified. (0x3) layerId=\\\\?\\C:\\ProgramData\\docker\\windowsfilter\\9e8e1b12633a5983db7742d2838d423e4376a578b7dbe7797cb2c62ce00594b1 flavour=1 folder=C:\\Windows\\TEMP\\hcs696675109" 
time="2016-05-05T05:59:31.847444300Z" level=info msg="Windows default isolation mode: process" 
time="2016-05-05T05:59:31.849443000Z" level=info msg="[graphdriver] using prior storage driver \"windowsfilter\"" 
time="2016-05-05T05:59:36.341659700Z" level=info msg="Graph migration to content-addressability took 0.00 seconds" 
time="2016-05-05T05:59:40.454747800Z" level=info msg="Loading containers: start."

**Comment by thaJeztah** [comment]
Are you still having this issue? I think there were some intermittent issues with this repository, but may be resolved now

**Comment by versofate** [comment]
@thaJeztah Now it's resolved, thank you.

**Comment by thaJeztah** [comment]
Cool, thanks for checking!

I'll close this issue then, but feel free to ping me if you run into this again!
