### ISSUE TITLE
Documentation: Supervisor uses unsupported ubuntu version (13.04)

### ISSUE THREAD

**Issue by jdfolino** [docker/docker#22524]
**Output of `docker version`:**

```
Docker version 1.10.2, build c3959b1
```

**Steps to reproduce the issue:**
1. Create the Dockerfile as specified in docs/admin/using_supervisord.md and the supervisors.conf
2. Run docker build  --no-cache  -t <your name here>/supervisord .

**Describe the results you received:**
Failed to fetch http://archive.ubuntu.com/ubuntu/dists/raring/main/source/Sources  404  Not Found [IP: 91.189.91.23 80]

**Describe the results you expected:**

Expected the container to be built successfully

**Additional information you deem important (e.g. issue happens only occasionally):**

Looks as though ubuntu:13.04 repositories are no longer available. Changing the container to ubuntu:15.04 allowed the docker build to run successfully

**Comment by thaJeztah** [comment]
Opened a pull request to update those docs: https://github.com/docker/docker/pull/22542

thanks for reporting!
