### ISSUE TITLE
NFS share on /var/lib/docker/volumes not working anymore

### ISSUE THREAD

**Issue by deviantony** [docker/docker#22539]
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 489.1 MiB
Name: swarm-node1
ID: SXU4:62L5:ADCK:5AYS:KU5C:YELF:B6FP:E543:OXCZ:CONY:JAAU:2XOX
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Ubuntu 14.04 nodes in Virtualbox (vagrant setup, available here: https://github.com/deviantony/vagrant-swarm-cluster/tree/nfs)

**Steps to reproduce the issue:**
1. Create a NFS share on a NFS server and export it
2. Mount this share on /var/lib/docker/volumes on the Docker engine 1 and start the docker engine
3. Mount this share on /var/lib/docker/volumes on the Docker engine 2 and start the docker engine, it won't start.

**Describe the results you received:**

Unable to start the second docker engine.

**Describe the results you expected:**

I expected the second docker engine to start, and the ability to share volumes between  the two docker engines using the NFS share.

**Additional information you deem important (e.g. issue happens only occasionally):**

This was working perfectly with Docker 1.10.x. Seems that Docker 1.11 introduces a file `/var/lib/docker/volumes/metadata.db` which is created when started a docker engine.

**Comment by thaJeztah** [comment]
The `/var/lib/docker` directory, including `/var/lib/docker/volumes` is designed to be exclusively accessed by a single daemon. This directory is used to keep state (in this case metadata about a volume, for the daemon that manages those volumes), so should **never** be used by multiple daemons.

If you want to have volumes that can be shared between daemons / nodes, you should use a volume driver plugin that implements that. Some plugins (some of which offer NFS), can be found here
https://docs.docker.com/engine/extend/plugins/

I'm sorry that this broke your setup, but we don't support this, so I'll have to close this issue, but feel free to comment after I closed.

**Comment by deviantony** [comment]
Thanks for the answer @thaJeztah ! Is there any way to update Docker/Swarm to use another default plugin volume than local?

E.g, each time I would type `docker volume create --name my-volume` it would actually pass `-d another_driver` ?

**Comment by thaJeztah** [comment]
no, you'll have to specify the driver. Setting a custom default was discussed at some point, but was decided against (at least for now), because it could lead to inconsistencies (think of situations where daemon A has a different default than daemon B).

**Comment by deviantony** [comment]
Thanks for the answer.

If anybody is interested, found a workaround for my setup using the following plugin: https://github.com/CWSpear/local-persist

The Swarm cluster setup in Vagrant is available here: https://github.com/deviantony/vagrant-swarm-cluster/tree/nfs-local-persist

**Comment by AndrewCRMartin** [comment]
It would be good if docker would tell you explicitly that making /var/lib/docker a link to an NFS share doesn't work / isn't allowed. If you try this, docker starts fine, but as soon as you try to download an image you get cryptic errors about tar unpacking operation not permitted. This took me a while to figure out today!
