### ISSUE TITLE
userns-remap=default causes command '/bin/bash' could not be invoked

### ISSUE THREAD

**Issue by zunayed** [docker/docker#22533]
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:45:32 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:45:32 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 6
 Running: 2
 Paused: 0
 Stopped: 4
Images: 23
Server Version: 1.11.1
Storage Driver: devicemapper
 Pool Name: docker-252:1-384279-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.277 GB
 Data Space Total: 107.4 GB
 Data Space Available: 11.71 GB
 Metadata Space Used: 3.486 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/100000.100000/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/100000.100000/devicemapper/devicemapper/metadata
 Library Version: 1.02.93 (2015-01-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.3-201.fc22.x86_64
Operating System: Fedora 22 (Twenty Two)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 489.2 MiB
Name: fedora-512mb-nyc3-01
ID: T73W:C4T2:ELB3:OYAS:V34F:7JV4:F66H:QHRI:QKU2:6ZZL:YUPU:VGON
Docker Root Dir: /var/lib/docker/100000.100000
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
digitalocean droplet

**Steps to reproduce the issue:**
1. set userns-remap=default flag for the docker daemon
2. rebuild with docker-compose build
3 .docker-compose up 

**Describe the results you received:**
ERROR: Container command '/bin/bash' could not be invoked.

**Describe the results you expected:**
This dockerfiles + compose works without the userns-remap flag

**Additional information you deem important (e.g. issue happens only occasionally):**
dummy project I'm testing with https://github.com/zunayed/movie_db

**Comment by zunayed** [comment]
Looks like when I mount a a volume 

```yaml
    volumes:
        - .:/code
```

it doesn't work. If I removed that bit the bash command runs. I also noticed on this box the ubuntu image was recently updated whereas I have it working on another box with a ubuntu image from a few days ago. Hmm

**Comment by thaJeztah** [comment]
You're bind-mounting a directory from your host inside the container. Any files in that directory may have a different owner than the user inside the container (i.e., the uid/gid on the host no longer match the uid/gid inside the container), making them inaccessible by the process in the container.

If I understand your case correctly, then this is *exactly* where userns-remap was designed for; if a process inside the container "breaks out" (in this case through a bind-mounted directory), it doesn't have permissions to do any harm, as the "root" user inside the container is not "root" outside.

I don't think there's a bug here, but let me know if there's something I misinterpreted 👍

**Comment by zunayed** [comment]
@thaJeztah Thanks for the reply! I'm just trying to execute bash in the container though. Even when I give compose `command: bash -c "ls -la"`  I get the same error. I don't really understand why mounting a volume would cause the containers bash not to work.

**Comment by thaJeztah** [comment]
@zunayed which container is failing? the `db` service is also using that volume, so possibly that one tries to access the files? https://github.com/zunayed/movie_db/blob/master/docker-compose.yml#L9-L13

**Comment by zunayed** [comment]
@thaJeztah The  web worker is failing 
https://github.com/zunayed/movie_db/blob/master/docker-compose.yml#L26

The celery worker however seems to work fine and is using the same dockerfile build 
https://github.com/zunayed/movie_db/blob/master/docker-compose.yml#L37

**Comment by sean-jc** [comment]
Any chance this is the same issue as #22633?

**Comment by LK4D4** [comment]
closing as #22633 contains even more detailed description
