### ISSUE TITLE
logging broken on existing when upgrading from 1.11

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#22536]
**Output of `docker version`:**
master

**Steps to reproduce the issue:**
1. create container with no logging options (and no logging options on the daemon) in 1.11
2. upgrade the daemon to master
3. try to start the container

**Describe the results you received:**
container start fails with:
```
Error response from daemon: Failed to initialize logging driver: Failed to get logging factory: logger: no log driver named '' is registered
```

**Describe the results you expected:**
Container should start

**Additional information you deem important (e.g. issue happens only occasionally):**

Found this while looking at another issue, logging here to make sure it doesn't get forgotten.

**Comment by mountkin** [comment]
Opened PR #22575 to fix this bug.
