### ISSUE TITLE
Docker push does not recognize layers existing in private repo after rebuild

### ISSUE THREAD

**Issue by creativeux** [docker/docker#22531]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:13:28 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 72
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 104
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.19-boot2docker
Operating System: Boot2Docker 1.11.0 (TCL 7.0); HEAD : 32ee7e9 - Wed Apr 13 20:06:49 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: CYU3:EMBI:EV7C:2J7B:ZANQ:76GY:LKO2:WRT4:CLQE:T46E:CVOU:PKCE
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 25
 Goroutines: 64
 System Time: 2016-05-05T14:58:49.903907084Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VirtualBox 5.0.16 r105871 running on Mac OSX 10.10.5
Private Artifactory 4.3.2 Docker registry running in AWS

**Steps to reproduce the issue:**
1. Build image locally
2. Use `docker push` to push to private registry
3. Use identical `docker push` command

**Describe the results you received:**
Upon first push, Docker will upload all layers even though the layer ID is clearly shared across all images.  This results in uploading ~500MB with every image push, and in our environment it takes about an hour to make my images available to other developers on the team.  Repeating the push, I receive "Layer already exists" and everything exits quickly.

```
astone@LT-F34516-MAC ~/Development/gci/app/blaster/webapi [feature/managed-firewall]
± % docker push art.gcihub.com/lockbox-api:1.1.0-SNAPSHOT                                                                                                                                                                      !6634
The push refers to a repository [art.gcihub.com/lockbox-api]
43a6fe358f15: Pushed 
6aa19d15a739: Pushed 
1a088df46942: Pushed 
d129205732c3: Pushed 
f1b43a882bad: Pushed 
809a08cf307d: Pushed 
33d3554fa132: Pushed 
5f70bf18a086: Pushed 
e2b2904a9a96: Pushed 
d9d21098c2d5: Pushed 
85d1af2496cb: Pushed 
2d182ad21eab: Pushed 
c1ab8e4cf9c2: Pushed 
1.1.0-SNAPSHOT: digest: sha256:5a033a4a0d80df84af5080647da04c8f8d308bed24c167502c52e35d2505a5d1 size: 12292

astone@LT-F34516-MAC ~/Development/gci/app/blaster/webapi [feature/managed-firewall]
± % docker push art.gcihub.com/lockbox-api:1.1.0-SNAPSHOT                                                                                                                                                                      !6635
The push refers to a repository [art.gcihub.com/lockbox-api]
43a6fe358f15: Layer already exists 
6aa19d15a739: Layer already exists 
1a088df46942: Layer already exists 
d129205732c3: Layer already exists 
f1b43a882bad: Layer already exists 
809a08cf307d: Layer already exists 
33d3554fa132: Layer already exists 
5f70bf18a086: Layer already exists 
e2b2904a9a96: Layer already exists 
d9d21098c2d5: Layer already exists 
85d1af2496cb: Layer already exists 
2d182ad21eab: Layer already exists 
c1ab8e4cf9c2: Layer already exists 
1.1.0-SNAPSHOT: digest: sha256:5a033a4a0d80df84af5080647da04c8f8d308bed24c167502c52e35d2505a5d1 size: 12292

```

**Describe the results you expected:**
I would expect that Docker would know that the layer IDs are identical and skip the upload.

**Additional information you deem important (e.g. issue happens only occasionally):**
I am the only one on my team experiencing this issue -- even on the same version.  Seems like an environment configuration incompatibility.

**Comment by creativeux** [comment]
PLEASE DELETE. SUBMITTED DUE TO FOCUS BEING ON THE BROWSER NOT THE TERMINAL...

(sorry)

**Comment by creativeux** [comment]
Sorry about the close/reopen - submitted by mistake with a window focus issue between the seat and the keyboard.

**Comment by cpuguy83** [comment]
IIRC, this is related to how the registry handles layers, and the open source docker registry should handle this properly in the latest version.

ping @aaronlehmann who probably knows a bit more about this

**Comment by aaronlehmann** [comment]
As @cpuguy83 mentioned, the open source registry is able to track identical layers across different repositories. This was added in Docker Registry 2.3. The reason a specific feature is needed is that permissions are handled on the repository level. The Docker engine needs to show the registry that it has permission to use a layer from repository X, when pushing to repository Y.

I don't know if Artifactory supports this, but it would appear that your version doesn't.

**Comment by creativeux** [comment]
Thanks for the replies, guys.  Since I am the only one on the team that is experiencing this issue, it doesn't appear that the problem is that Artifactory doesn't support the feature.

**Comment by creativeux** [comment]
Spoke to someone at DockerCon today about this issue (still seeing it), and here is my docker.log for reference.

At the very end of the log, you can see that layer "ad3d637246f0" was pushed repeatedly for each service that uses it.

[docker.log.txt](https://github.com/docker/docker/files/326665/docker.log.txt)

**Comment by thaJeztah** [comment]
ping @aaronlehmann ptal

**Comment by aaronlehmann** [comment]
@creativeux: Thanks for the log. It looks like a registry-side issue to me. In Docker 1.10 we added "cross-repository push", which allows Docker to reuse a layer that has been pushed to a different repository instead of pushing it again. You can see from the log that Docker knows that the layer already exists on this registry and is trying to reuse it:

````
time="2016-06-21T21:35:34.836392187Z" level=debug msg="attempting to mount layer sha256:ad3d637246f023a37d16f9681f151075c3d5b25b1740924e72475f0f036fbe5a (sha256:c9a8464b2289620227f8a40a3ad87b0c02328232f6e9d751b524dbe68686ab82) from art.gcihub.com/filestore-service" 
````

However this does not succeed, and it has to upload the layer:

```
time="2016-06-21T21:35:50.609612340Z" level=debug msg="uploaded layer sha256:ad3d637246f023a37d16f9681f151075c3d5b25b1740924e72475f0f036fbe5a (sha256:c9a8464b2289620227f8a40a3ad87b0c02328232f6e9d751b524dbe68686ab82), 62381703 bytes" 
```

I don't think Artifactory supports the cross-repository push feature. I would contact the makers of Artifactory and ask them to add support for it. The protocol flow is documented at https://github.com/docker/distribution/blob/master/docs/spec/api.md#cross-repository-blob-mount.

You mentioned that other people on your team aren't seeing the same problem. I would need to know more about their setups to figure out where the difference comes from. One possibility is that they are pushing multiple tags in the same repository instead of pushing different repositories. The permissions model allows image tags in the same repository to share layers without any extra steps, so pushing `exampleregistry.com/a/b:foo` and `exampleregistry.com/a/b:bar` behaves differently than pushing `exampleregistry.com/a/b` and `exampleregistry.com/a/c`. It's also possible that Artifactory does support cross-repository push, and there's some issue either with Docker or Artifactory that prevents it from working for you. Do any other people on your team see `Mounted from ...` in the push progress output when they push images that skip pushing layers that exist elsewhere on the registry?

**Comment by creativeux** [comment]
To put a bow on this, I followed up with Artifactory and they found and fixed this bug.  It was an issue on their end!  Thanks for following through on this, all!

For reference: [https://www.jfrog.com/jira/browse/RTFACT-9591](https://www.jfrog.com/jira/browse/RTFACT-9591)

**Comment by thaJeztah** [comment]
Thanks for the update @creativeux
