### ISSUE TITLE
Error building image: Error relabeling merged directory: operation not supported

### ISSUE THREAD

**Issue by Jeronimo-Garcia-Loygorri** [docker/docker#22548]
**Output of `docker version`:**
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   8acee1b
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   8acee1b
 Built:        
 OS/Arch:      linux/amd64

**Output of `docker info`:**

Containers: 33
 Running: 13
 Paused: 0
 Stopped: 20
Images: 1776
Server Version: 1.10.3
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.5.0-coreos-r1
Operating System: CoreOS 1010.1.0 (MoreOS)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.42 GiB
Name: coreos2
ID: GURX:YYN7:PCMQ:KJD7:DCWX:BFIT:SKEH:PQLS:EUU3:ICFI:QFWV:DW6

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS machine.

**Steps to reproduce the issue:**
1. docker build -t torch-test .

It happens with several Dockerfiles and not always in the same step of the Dockerfile.

**Describe the results you received:**
 ---> 3f0b5a95d227
Step 2 : RUN mkdir -p /opt/service
 ---> Running in ff60efe72a34
Error relabeling merged directory: operation not supported

**Describe the results you expected:**
I expected to see a successful build

**Additional information you deem important (e.g. issue happens only occasionally):**
This issue happens only in one of our dockerhosts so I assume is an issue related with our configuration and may or may not be caused by docker. There are no obvious configuration errors in the server nor reported errors in the file file system.  What I'd like to know is what the error means and when it happens. I have not found any reference to the error message in github or even google.

**Comment by justincormack** [comment]
It looks like it might be an issue with overlay and selinux. I am not sure the status of this, there were issues before related to this eg see https://lwn.net/Articles/619195/ need to look and see when/if they got merged.

**Comment by Jeronimo-Garcia-Loygorri** [comment]
Thanks we will try to find out the cause.

**Comment by thaJeztah** [comment]
can you open this issue in the CoreOS issue tracker? You're running a CoreOS build, and they made some modifications in this area; see the commit that this version was built from; https://github.com/coreos/docker/commit/8acee1bc06813191ba5ea396137e1c17a7120bdf

**Comment by thaJeztah** [comment]
Actually, we don't have this error in our builds at all, because we explicitly disable overlay with SELinux enabled; https://github.com/docker/docker/blob/v1.10.3/daemon/daemon_unix.go#L466-L482 in Docker 1.10.3, so I don't think we'll be able to help you, because this is an issue in the CoreOS version of Docker.

I'll close this issue, but feel free to comment here after I closed

**Comment by victorgp** [comment]
@Jeronimo-Garcia-Loygorri we are hitting the same bug, did you report it to CoreOS?
