### ISSUE TITLE
Windows libcontainerd should call TerminateComputeSystem on failed ShutdownComputeSystem

### ISSUE THREAD

**Issue by rohitjaini** [docker/docker#22543]
**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.Start Hyper-v container 
2. Make sue container bugcheck
3. Now query the containers using docker ps command 

**Describe the results you received:**
The command hangs.

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by jhowardmsft** [comment]
#dibs
