### ISSUE TITLE
hack/install.sh on Debian detecting stretch when it should be detecting jessie?

### ISSUE THREAD

**Issue by nathanleclaire** [docker/docker#22540]
On a Debian Jessie VM where I've booted a fairly recent kernel (`4.6.0-rc3-amd64`) the `get.docker.com` script bails due to broken dependencies.

```console
$ curl -SsL get.docker.com | sh
...
+ sudo -E sh -c echo deb [arch=amd64] https://apt.dockerproject.org/repo debian-stretch main > /etc/apt/sources.list.d/docker.list
+ sudo -E sh -c sleep 3; apt-get update; apt-get install -y -q docker-engine
...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 docker-engine : Depends: libltdl7 (>= 2.4.6) but 2.4.2-1.11 is to be installed
                 Recommends: aufs-tools but it is not going to be installed
                 Recommends: cgroupfs-mount but it is not going to be installed or
                             cgroup-lite but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Can't install a higher version of `libltdl7` through `apt-get`, so I'd be stuck here except that updating the `/etc/apt/sources.list.d/docker.list` to use `jessie` instead of `stretch` fixed it.

@tianon What do you think the right thing to do here is?  Is `stretch` a valid assumption, even though it's technically a Jessie install with a more recent kernel? I actually don't know enough about Debian versioning to say.  I'm happy to try and update `hack/install.sh` if desired to be more robust in detecting this, for instance `lsb_release -a` still reports the codename as `jessie`.

If this is acceptable behavior from the packages (since e.g. the configuration is more towards "bleeding edge" end of the spectrum), please feel free to close the issue, but wanted to make sure it was on your periphery.

**Comment by tianon** [comment]
If the VM is Jessie, that seems like a bug in the detection. (Reason number N why I'm gunning to remove the autodetection entirely...)  Using the Stretch package on Jessie is definitely going to be broken in ways we can't easily overcome (as you've discovered).  Any ideas for where the script's detection code went wrong?

**Comment by nathanleclaire** [comment]
Going to close this on the grounds of "too old" / "I was too lazy to fix so it myself so it shouldn't be your problem anymore"
