### ISSUE TITLE
Docker Image not running on ARM64 Odroid-C2

### ISSUE THREAD

**Issue by insatiableben** [docker/docker#22552]
I have run into an issue with docker on an Odroid C2 with not being able to run certain containers.

**`docker version`**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6.1
 Git commit:   20f81dd
 Built:        Wed, 20 Apr 2016 14:19:16 -0700
 OS/Arch:      linux/arm64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6.1
 Git commit:   20f81dd
 Built:        Wed, 20 Apr 2016 14:19:16 -0700
 OS/Arch:      linux/arm64
```

**`docker info`**

```
Containers: 11
 Running: 0
 Paused: 0
 Stopped: 11
Images: 8
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 67
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.14.29-56
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: aarch64
CPUs: 4
Total Memory: 1.679 GiB
Name: odroid64
ID: BOZK:7XHN:6G3M:ZXIM:42XX:6CGU:KI33:6CCP:B5N7:AXB4:4FHZ:YQQG
```

**`uname -a`**

```
Linux odroid64 3.14.29-56 #1 SMP PREEMPT Wed Apr 20 12:15:54 BRT 2016 aarch64 aarch64 aarch64 GNU/Linux
```

**Steps to reproduce the issue:**
1. update and upgrade apt-get
2. install docker.io (with apt-get)
3. sudo docker run hello-world

**Describe the results you received:**
Here is the error message i received in the standard output:
```
exec format error
docker: Error response from daemon: Cannot start container a924081bb73d180a1b917c96fa8f1b2ef500385258c4356828c17c22d737162f: [10] System error: exec format error.
```

**Additional thoughts:**
This issue only happens with images that are not built on an arm architecture. So if i build a container with ubuntu-core-15.04-core-arm64 docker works as expected (this has been tested with this [image](https://hub.docker.com/r/ericvh/arm64-ubuntu/ )) but if i try to run the hello-world container it fails. This is a bit confusing I was under the impression that a container could work in any environment that has docker support regardless of architecture. Is there something I’m doing wrong or not understanding?

**Comment by justincormack** [comment]
No, containers are still required to be of the right CPU architecture. You will have to rebuild all the containers yourself, or use ones built for arm64. At some point there will be more images available we hope.

(there are ways to get around this with emulation, but thats another issue).

**Comment by thaJeztah** [comment]
Yes, you should be able to find some images on Docker Hub, but there's no official ones (yet).

I'll close this issue, but feel free to comment here after I closed

**Comment by StefanScherer** [comment]
@insatiableben Try one of these images https://hub.docker.com/u/aarch64/

**Comment by insatiableben** [comment]
thank you for your input this makes sense and i'll keep an ear out for the official docker imagesfor arm devices

**Comment by hqhq** [comment]
@thaJeztah https://hub.docker.com/u/aarch64/  is official now!! :wink:

**Comment by thaJeztah** [comment]
@hqhq I'd like them to be, but they're not official yet, and it still has to be sorted out how they'll be rolled into the official images (e.g., will those become multi-arch images)

**Comment by hqhq** [comment]
@thaJeztah ok, then do you mean that there are only official images for x86-64 for now?

I know there are some thoughts about how to support multi-arch images for dockerhub, do you know how that goes now?

**Comment by thaJeztah** [comment]
@hqhq yes, at this point there's only official images for x86-64. @tianon may know more about progress / current status for other architectures

**Comment by tianon** [comment]
https://github.com/docker-library/official-images#architectures-other-than-amd64
:+1:

**Comment by justincormack** [comment]
@hqhq the support is now on hub for fat manifests and there is an experimental tool to create them by hand see https://integratedcode.us/2016/04/22/a-step-towards-multi-platform-docker-images/
