### ISSUE TITLE
Unable to find user

### ISSUE THREAD

**Issue by frncmx** [docker/docker#22553]
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   5604cbe
 Built:        Mon May  2 00:06:51 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   5604cbe
 Built:        Mon May  2 00:06:51 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 20
Server Version: 1.11.1
Storage Driver: devicemapper
 Pool Name: docker-8:3-1312479-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.561 GB
 Data Space Total: 107.4 GB
 Data Space Available: 53.26 GB
 Metadata Space Used: 5.046 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.142 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.122 (2016-04-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.5.1-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.709 GiB
Name: centurio
ID: GUBP:B6DI:4YUT:OXQU:2OQB:QZHJ:BC43:U275:6L5P:5W33:HD6V:UT25
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Steps to reproduce the issue:**
1. `docker run -it --rm -v /etc/passwd:/etc/passwd -v /etc/group:/etc/group -u "${USER}" debian:jessie`

**Describe the results you received:**
`docker: Error response from daemon: linux spec user: Unable to find user <current-user>.`

**Describe the results you expected:**
The container starts with my current user on the host without an error.

**Additional information you deem important (e.g. issue happens only occasionally):**
docker 1.11.1-1  - NOK
docker 1.11.0-1  - NOK
docker 1.10.3-1 - OK

I use this kinda hack to produce artifacts on the host machine. I pass my whole project folder to the container as a volume and I run the build inside, when the container exits I've the artifacts outside.

Without the trick above, I would not be able to delete and modify the content of the multi-layer folders produced by the container on the host (with a regular user).

Note: The issue can be reproduced with overlay storage driver, too.

Let me know, if you need more information.

**Comment by thaJeztah** [comment]
this is a duplicatie of https://github.com/docker/docker/issues/22323. Using a uid instead of username is the recommended approach here; also read the linked issue for how to do this, and some more info.

I'll close this issue, but feel free to comment after I closed

**Comment by frncmx** [comment]
@thaJeztah I don't know, how did I miss the other one; I tried to look through. Sorry about the duplicate.

**Comment by thaJeztah** [comment]
@frncmx no worries!
