### ISSUE TITLE
specific docker search request

### ISSUE THREAD

**Issue by bgrissin** [docker/docker#22557]
Is there a way to perform a search of docker hub for official images only 

docker search image_name(s) --official-images

**Comment by bgrissin** [comment]
Also might consider expanding to search specific private/public repos as well

**Comment by chiisaihayashi** [comment]
I found similar issue.
You could refer this [link](https://github.com/docker/docker/issues/18980).

**Comment by thaJeztah** [comment]
Yes, this is a duplicate of https://github.com/docker/docker/issues/18980
and is currently worked on in https://github.com/docker/docker/pull/22369 (which will be in docker 1.12)
