### ISSUE TITLE
Two containers from the same image cause each other to fail in v1.11

### ISSUE THREAD

**Issue by nahuellofeudo** [docker/docker#22556]
Up until a week ago, I was running Docker 1.10.3 on a Debian Jessie, running two copies of the image jenserat/samba-publicshare, each copy had its ports forwarded from a different VLAN network interface in the host. 
After upgrading to Docker 1.11.1, both containers refuse to run together and restart continously.

Here is all the relevant information: 
Host: Debian Jessie (8.4). 4-core i5, 16GB RAM
Docker: 1.10.3-0~jessie installed through APT from https://apt.dockerproject.org/repo debian-jessie main
Image: jenserat/samba-publicshare
Networking: Single Ethernet adapter with three 802.1q VLANs
    eth1.2: 10.1.2.10
    eth1.4: 10.1.4.10
    eth1.8: 10.1.8.10

These are the command lines I use to start the containers:

 docker run --restart=always --publish 10.1.4.10:445:445 --publish 10.1.4.10:137:137/udp --publish 10.1.4.10:138:138/udp --publish 10.1.4.10:139:139 --volume /storage/bulk/internal:/srv  --name smbd-int -D jenserat/samba-publicshare

and 

 docker run --restart=always --publish 10.1.8.10:445:445 --publish 10.1.8.10:137:137/udp --publish 10.1.8.10:138:138/udp --publish 10.1.8.10:139:139 --volume /storage/bulk/external:/srv  --name smbd-ext -D jenserat/samba-publicshare

The result is that Docker constantly restarts these containers. THIS DID NOT HAPPEN IN 1.10:
root@server:~# docker ps
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS                            PORTS                                                                                         NAMES
86788592a158        jenserat/samba-publicshare       "/bin/sh -c '/usr/sbi"   23 hours ago        Restarting (143) 52 seconds ago   10.1.8.10:139->139/tcp, 137-138/tcp, 10.1.8.10:137-138->137-138/udp, 10.1.8.10:445->445/tcp   smbd-ext
0355b5038688        jenserat/samba-publicshare       "/bin/sh -c '/usr/sbi"   23 hours ago        Restarting (143) 53 seconds ago   10.1.4.10:139->139/tcp, 137-138/tcp, 10.1.4.10:137-138->137-138/udp, 10.1.4.10:445->445/tcp   smbd-int

I only see these errors in any of the log files under /var/log:
Apr 22 12:51:01 server docker[28911]: time="2016-04-22T12:51:01-07:00" level=error msg="containerd: notify OOM events" error="open memory.oom_control: no such file or directory"
Apr 22 12:51:01 server docker[28911]: time="2016-04-22T12:51:01-07:00" level=error msg="containerd: notify OOM events" error="open memory.oom_control: no such file or directory"

repeated again and again. I'm not sure if these errors were there for 1.10

The containers seem to be terminated by docker, and don't show errors themselves:
root@server:~# docker logs smbd-int
smbd version 4.2.10-Debian started.
Copyright Andrew Tridgell and the Samba Team 1992-2014
STATUS=daemon 'smbd' finished starting up and ready to serve connections
Terminated
smbd version 4.2.10-Debian started.
Copyright Andrew Tridgell and the Samba Team 1992-2014
STATUS=daemon 'smbd' finished starting up and ready to serve connections
Terminated

and

root@server:~# docker logs smbd-ext
smbd version 4.2.10-Debian started.
Copyright Andrew Tridgell and the Samba Team 1992-2014
STATUS=daemon 'smbd' finished starting up and ready to serve connections
Terminated
smbd version 4.2.10-Debian started.
Copyright Andrew Tridgell and the Samba Team 1992-2014
STATUS=daemon 'smbd' finished starting up and ready to serve connections
Terminated

Any ideas of what could have changed between 1.10 and 1.11 that could have caused the problem? Again, the exact same containers were working fine until I upgraded.

Thank you in advance

**Comment by justincormack** [comment]
Hi, that container appears to need the `workgroup` environment variable set, it seems to not terminate if I add `-e workgroup=test ` to the command line.

**Comment by nahuellofeudo** [comment]
Let me try that, thank you.

**Comment by nahuellofeudo** [comment]
The problem was stdin.
This command line works:

docker run -d --restart=always --publish 10.1.4.10:445:445 --publish 10.1.4.10:137:137/udp --publish 10.1.4.10:138:138/udp --publish 10.1.4.10:139:139 --volume /storage/bulk/internal:/srv  -i --name smbd-int  jenserat/samba-publicshare

whereas this one kills the smbd process as soon as it's done loading:

docker run -d --restart=always --publish 10.1.4.10:445:445 --publish 10.1.4.10:137:137/udp --publish 10.1.4.10:138:138/udp --publish 10.1.4.10:139:139 --volume /storage/bulk/internal:/srv  --name smbd-int  jenserat/samba-publicshare

The only difference between the two is the -i flag. Does that make sense? Has the stdin behavior changed between 1.10 and 1.11?

**Comment by justincormack** [comment]
Are you sure? As I said this container does need the environment variable. Using `-i -d` can keep the container from terminating as stdin remains open in some situations, but I think you will find it is not actually working.

**Comment by nahuellofeudo** [comment]
Well... I just tested the two command lines and that's what I observed. The lack of -i causes smbd to terminate immediately, whereas the container with -i has been running happily for days now. Anyway, if the problem is the container itself and not Docker, I guess you can close the bug, with my apologies for the trouble I caused you.

**Comment by thaJeztah** [comment]
I'll close this then, but feel free to comment after I closed
