### ISSUE TITLE
Misleading error when docker run specifies non-existent AppArmor profile

### ISSUE THREAD

**Issue by tswift242** [docker/docker#22560]
**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 5
 Running: 3
 Paused: 0
 Stopped: 2
Images: 20
Server Version: 1.11.0
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.6-040406-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.675 GiB
Name: ip-10-182-62-167
ID: OAXN:UWSX:GWKO:HWP7:VZY6:HU6T:HFAD:2LJ7:57Y3:5SC7:4BIT:C4GO
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 36
 Goroutines: 63
 System Time: 2016-05-06T20:45:15.573769419Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS

**Steps to reproduce the issue:**
1. docker run -d --security-opt apparmor:foo busybox /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 3; done'.
Note: AppArmor profile "foo" does not exist on the host.

**Describe the results you received:**
"docker: Error response from daemon: Container command '/bin/sh' not found or does not exist.."

**Describe the results you expected:**
Error should indicate that the AppArmor profile does not exist. Instead, it indicates that the command does not exist, which is very misleading.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by justincormack** [comment]
Yes that is pretty confusing, will look and see what the interface does.

**Comment by runcom** [comment]
Rolled out a fix https://github.com/docker/docker/pull/22586

**Comment by justincormack** [comment]
Well, it turns out that despite the man page claiming that it will return `ENOENT` if the apparmor profile does not exist, there is in fact no error checking at all. See http://bazaar.launchpad.net/~apparmor-dev/apparmor/master/view/head:/libraries/libapparmor/src/kernel.c#L481 - we have error handling but in fact no error is returned.

I am inclined to change the message though, as there are several reasons at this point why the `exec` could fail, and I think the file not existing is the least likely...

**Comment by justincormack** [comment]
Ok, have created a PR to fix this https://github.com/docker/docker/pull/22658

**Comment by justincormack** [comment]
This is fixed by https://github.com/opencontainers/runc/commit/ec77200ceb30ea6379c893d7b55c5a590ac7d82a 

This was not in the last bump of runc, but should be in the next one.

**Comment by justincormack** [comment]
Reminder to me to add a test when this lands, before this issue is closed...

**Comment by runcom** [comment]
runc  has been updated to include the related commit to fix this

**Comment by thaJeztah** [comment]
@runcom do you know which PR bumped RunC in this repository?
