### ISSUE TITLE
Docker won't start on linux kernal 4.5.00

### ISSUE THREAD

**Issue by rnavagamuwa** [docker/docker#22573]
I have recently installed ubuntu 16.04 with kernal 4.5.0.  I have followed this one to install docker [https://docs.docker.com/engine/installation/linux/ubuntulinux/](https://docs.docker.com/engine/installation/linux/ubuntulinux/). After doing all the previous steps I have used `sudo apt-get install docker-engine` to install docker-engine but it gets stucked when

> Setting up docker-engine (1.11.1-0~xenial)

After killing that process and I tried starting the docker service but still getting an error.
Output of `systemctl status docker.service` is as follows

> May 07 21:26:55 rnavagamuwa-XPS-15-9550 systemd[1]: Starting Docker Application Container Engine...
> May 07 21:26:55 rnavagamuwa-XPS-15-9550 docker[12615]: time="2016-05-07T21:26:55.852709434+05:30" level=info msg="New containerd process, pid: 12621\n"
> May 07 21:26:56 rnavagamuwa-XPS-15-9550 docker[12615]: time="2016-05-07T21:26:56.907773827+05:30" level=warning msg="devmapper: Usage of loopback devices is strongly discouraged for production use. Please
> May 07 21:26:56 rnavagamuwa-XPS-15-9550 docker[12615]: time="2016-05-07T21:26:56.914722298+05:30" level=error msg="[graphdriver] prior storage driver \"devicemapper\" failed: devicemapper: Can't set task 
> May 07 21:26:56 rnavagamuwa-XPS-15-9550 docker[12615]: time="2016-05-07T21:26:56.914775815+05:30" level=fatal msg="Error starting daemon: error initializing graphdriver: devicemapper: Can't set task name 
> May 07 21:26:56 rnavagamuwa-XPS-15-9550 systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
> May 07 21:26:56 rnavagamuwa-XPS-15-9550 docker[12615]: time="2016-05-07T21:26:56+05:30" level=info msg="stopping containerd after receiving terminated"
> May 07 21:26:56 rnavagamuwa-XPS-15-9550 systemd[1]: Failed to start Docker Application Container Engine.
> May 07 21:26:56 rnavagamuwa-XPS-15-9550 systemd[1]: docker.service: Unit entered failed state.
> May 07 21:26:56 rnavagamuwa-XPS-15-9550 systemd[1]: docker.service: Failed with result 'exit-code'.

**Comment by rnavagamuwa** [comment]
Fixed this by `dmsetup mknodes`

**Comment by thaJeztah** [comment]
Since you're on a modern kernel, I'd suggest to give overlay a try as alternative; decicemapper really isn't the best option (performance wise); have a look at this section of the docs; https://docs.docker.com/engine/userguide/storagedriver/imagesandcontainers/

**Comment by rnavagamuwa** [comment]
@thaJeztah Thanks for the tip. :+1:
