### ISSUE TITLE
Why install a different  version use the command "RUN npm install -g webpack" use the same dockerfile?

### ISSUE THREAD

**Issue by hujb2000** [docker/docker#22571]
Develop Machine:

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
```

Server Physical Machine:

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:48:06 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:48:06 2016
 OS/Arch:      linux/amd64
```

The Dockerfile's content:

```
FROM node:5.5.0-wheezy

MAINTAINER hujb

RUN npm cache clean

RUN npm install -g cnpm --registry=https://r.cnpmjs.org

RUN npm install -g node-gyp

RUN npm install -g babel-cli

RUN npm install -g webpack

RUN mkdir -p /usr/src/app

COPY package.json /usr/src/app

WORKDIR /usr/src/app

RUN cnpm install

COPY . /usr/src/app

WORKDIR /usr/src/app/plugins

RUN webpack --config webpack.prod.config.js

WORKDIR /usr/src/app/bin

CMD ["./start.sh"]

```

**Steps to reproduce the issue:**
1.at develop machine,  I execute the command:
 docker  build -t hub.c.163.com/hujb2000/icp:0.0.37 .

I know that the command "RUN npm install -g weback" to install the version 1.13.0 for webpack.

```
Version: webpack 1.13.0
Time: 13636ms
              Asset       Size  Chunks             Chunk Names
  ./build/bundle.js     475 kB       0  [emitted]  main
1../build/bundle.js       5 kB       1  [emitted]  
2../build/bundle.js  872 bytes       2  [emitted]  
3../build/bundle.js    1.19 kB       3  [emitted]  
4../build/bundle.js  870 bytes       4  [emitted]  
5../build/bundle.js    1.33 kB       5  [emitted]  
6../build/bundle.js    1.19 kB       6  [emitted]  
7../build/bundle.js  873 bytes       7  [emitted]  
   [0] multi main 28 bytes {0} [built]
    + 250 hidden modules

ERROR in ../~/.npminstall/react-router/1.0.3/react-router/lib/Router.js
Module not found: Error: Cannot resolve module 'history/lib/createHashHistory' in /usr/src/app/node_modules/.npminstall/react-router/1.0.3/react-router/lib
 @ ../~/.npminstall/react-router/1.0.3/react-router/lib/Router.js 23:35-75

ERROR in ../~/.npminstall/react-router/1.0.3/react-router/lib/useRoutes.js
Module not found: Error: Cannot resolve module 'history/lib/Actions' in /usr/src/app/node_modules/.npminstall/react-router/1.0.3/react-router/lib
 @ ../~/.npminstall/react-router/1.0.3/react-router/lib/useRoutes.js 15:25-55

ERROR in ../~/.npminstall/react-router/1.0.3/react-router/lib/useRoutes.js
Module not found: Error: Cannot resolve module 'history/lib/useQueries' in /usr/src/app/node_modules/.npminstall/react-router/1.0.3/react-router/lib
 @ ../~/.npminstall/react-router/1.0.3/react-router/lib/useRoutes.js 17:28-61

ERROR in ../~/.npminstall/react-router/1.0.3/react-router/lib/match.js
Module not found: Error: Cannot resolve module 'history/lib/createMemoryHistory' in /usr/src/app/node_modules/.npminstall/react-router/1.0.3/react-router/lib
 @ ../~/.npminstall/react-router/1.0.3/react-router/lib/match.js 13:37-79

ERROR in ../~/.npminstall/react-router/1.0.3/react-router/lib/match.js
Module not found: Error: Cannot resolve module 'history/lib/useBasename' in /usr/src/app/node_modules/.npminstall/react-router/1.0.3/react-router/lib
 @ ../~/.npminstall/react-router/1.0.3/react-router/lib/match.js 17:29-63
 ---> 5a85ea14c912
```
1. at server machine,  I execute the command:
   docker  build -t hub.c.163.com/hujb2000/icp:0.0.37 .

I know that the command "RUN npm install -g weback" to install the version 1.12.14 for webpack.

```
Hash: 6f5ecba062a64ec37514
Version: webpack 1.12.14
Time: 29374ms
              Asset       Size  Chunks             Chunk Names
  ./build/bundle.js     496 kB       0  [emitted]  main
1../build/bundle.js       5 kB       1  [emitted]  
2../build/bundle.js  872 bytes       2  [emitted]  
3../build/bundle.js    1.19 kB       3  [emitted]  
4../build/bundle.js  870 bytes       4  [emitted]  
5../build/bundle.js    1.33 kB       5  [emitted]  
6../build/bundle.js    1.19 kB       6  [emitted]  
7../build/bundle.js  873 bytes       7  [emitted]  
   [0] multi main 28 bytes {0} [built]
    + 273 hidden modules
 ---> 41454d41eed7
Removing intermediate container 8fce9dd27501
Step 13 : WORKDIR /usr/src/app/bin
```
1. I expected install the same version for webpack use the same dockerfile, but now defacto, install a different version for webpack .  

I guess one factor is that the develop machine and the server machine are in a different network environment ,  

Do you can help me ?

**Comment by thaJeztah** [comment]
Some things that can influence this;

- make sure your base image is up to date; in your case you're building from `node:5.5.0-wheezy` so you're pinning to a specific version (which -should- ideally not change), but to exclude this, do a `docker pull node:5.5.0-wheezy` to be sure. Also, note it seems 5.5.0 is no longer listed on Docker Hub, so may not be maintained anymore.
- build cache; if you don't make changes to your Dockerfile, docker uses the local build cache. Steps like `RUN npm cache clean` will thus not be executed (you'll see "using cache" during `docker build`, and subsequent `RUN` steps use a "cached" version of the cache). To disable the build cache during `docker build` (and to force every step to be run again, even if there's a local cache), use `docker build --no-cache`.
- You did not specify a specific version to install, so `npm install -g webpack` will install the version that's currently known in the cache. Due to the points above, this may be an outdated version (because the cache is outdated). If you want repeatable builds, make sure you specify an explicit version, e.g. `npm install -g webpack@1.13.0`
- Finally, it's possible that npm uses a mirror that's not up-to-date, you can try using a different mirror.

I don't have a lot of experience with npm, so you may need to do some additional research, but these things could play a role here. Hope this helps

**Comment by hujb2000** [comment]
@thaJeztah ,  thank you!

I make a mistake that I'm still using a previous dockerfile  have no "RUN npm  cache clean" command.   So docker build always use the cache image untill the "RUN webpack --config webpack.prod.config.js" at server machine.  server machine have had the tag "hub.c.163.com/hujb2000/icp:0.0.36",   develop machine have no any image about "hub.c.163.com/hujb2000/icp:*", this is first build on develp machine

previous dockerfile
```
FROM node:5.5.0-wheezy

MAINTAINER hujb

RUN npm install -g cnpm --registry=https://r.cnpmjs.org

RUN npm install -g node-gyp

RUN npm install -g babel-cli

RUN npm install -g webpack

RUN mkdir -p /usr/src/app

COPY package.json /usr/src/app

WORKDIR /usr/src/app

RUN cnpm install

COPY . /usr/src/app

WORKDIR /usr/src/app/plugins

RUN webpack --config webpack.prod.config.js

WORKDIR /usr/src/app/bin

CMD ["./start.sh"]
```

**Comment by thaJeztah** [comment]
In what way does it fail? Does it fail to install webpack 1.3.0? Perhaps you should update to a newer version of the base image?

**Comment by LK4D4** [comment]
Looks like original issue was resolved.
