### ISSUE TITLE
Failing MTU autodetection in official registry

### ISSUE THREAD

**Issue by est31** [docker/docker#22585]
I had problems with `docker pull` from the official `https://registry-1.docker.io` registry. Many other people had them too (see #22495,  #20628, #20628, many others). I had to apply the workaround that was mentioned there to manually set the MTU for my whole interfaces down to 900. Also I had to set the MTU for the docker network interface to 900 as well what made me wonder a bit, as I've thought that the network communication went over the wlan/eth port not over the docker network interface.

There are ICMP protocols to automatically find out the optimal MTU. Thanks to tcpdump I can see that these protocols get invoked when docker tries to reach the registry, but fails with the well known time out error message. It seems from comments in the threads that the root cause of the problem may be that your AWS has turned off the ICMP MTU auto detection. I think it should be turned on, and that is in my eyes the only proper fix for the issue.

**Comment by phemmer** [comment]
What is it you want docker to do here? If the problem is that your network isn't allowing ICMP fragmentation needed packets, there's nothing docker can do about that (if you're using AWS, you would need to adjust your security group).

**Comment by est31** [comment]
Well MTU autodiscovery seems to work, as I am getting messages like:

```
IP router-ip > localhost-ip: ICMP 52.5.48.248 unreachable - need to frag (mtu 1474), length 36
```

Just the docker daemon does not seem to react by sending a shorter packet, which in turn lets the registry send the error:
```
<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n\n
```
as the request packet does not reach the registry.

So the failure is on the docker side here, am I wrong?

**Comment by phemmer** [comment]
> Just the docker daemon does not seem to react by sending a shorter packet, which in turn lets the registry send the error:

ICMP fragmentation needed packets are handled by the kernel, not userspace (docker). Userspace applications only see a filehandle which the send bytes into, and read bytes out of. Breaking this stream of bytes up is the kernel's job.

Thus, I'd bet you have an overzealous iptables firewall on the box with a rule that is dropping all ICMP packets.

**Comment by OrKoN** [comment]
I have problems related to MTU as well. I am running a desktop version of Ubuntu 16.04 with the default configuration. I cannot pull any images from the registry till I set mtu to 900 on docker and wlan interface as well, restart docker and open a new terminal session. 

I am not sure actually where the problem is. I guess it can be smth in Ubuntu, smth in my network, smth in my ISP or on the registry side.

**Comment by OrKoN** [comment]
Why I think this may not be the registry problem is me having connectivity issues on some other websites: uploading a picture to slack in a web client is timing out; submitting registration requests in stripe is timing out. Yes, just particular requests on particular services. And docker pull. Everything else works fine. MTU seems to be fixing both Stripe and Slack. Can it be that docker registry, Stripe and Slack is being hosted on the same infrastructure?

**Comment by justincormack** [comment]
You will only notice MTU issues on some sites as sometimes most requests or
replies are small (but then you try pictures on slack and that will use
large packets), and you may have different routes with different
properties. But it is not an issue with the sites that are serving content.

Unfortunately it is not very easy to debug, you should speak to your
network and/or VPN provider to see if they can help.

**Comment by est31** [comment]
Yeah I think its most likely my ISP is to blame here.

**Comment by OrKoN** [comment]
The strange thing though is that all problematic services are on AWS. I guess docker registry is there too?

**Comment by OrKoN** [comment]
ISP says it is not their problem.
