### ISSUE TITLE
When does docker evoke volume plugin unmount interface?

### ISSUE THREAD

**Issue by drngsl** [docker/docker#22584]
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 10
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 80
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.13.0-85-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: docker-trusty
ID: TXJI:WTIZ:VKMM:IZ2J:4XTV:HUVH:LE4B:4MAH:YBOQ:ET6X:7CUU:PA35
Debug mode (server): true
 File Descriptors: 17
 Goroutines: 32
 System Time: 2016-05-08T08:47:47.441404023Z
 EventsListeners: 0
 Init SHA1: 14bbd54b64d2a737269118ce4f1613787e2d0ce8
 Init Path: /usr/lib/docker/dockerinit
 Docker Root Dir: /var/lib/docker
WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
An virtual machine created by nova.

**Steps to reproduce the issue:**
1. `run` two containers with volume create by my self define volume plugin;
2. `stop` one of them;
3. `stop` the another container.

**Describe the results you received:**
Every time I stop an container, docker daemon will evoke interface `/VolumeDriver.Unmount`.
If I clear the volume info (created by cinder, attached and mounted) the first time it evoke, then other containers with volume references to it will not work normally.
All in all, I want to know,
1. Will docker daemon evoke interface `/VolumeDriver.Unmount` every time I execute command `docker stop`?
2. If several containers have same volume, i want other containers work normally with volume, when stop one of them, So i should not umount block device util no container uses this volume, and then execute command `docker volume rm ` to clear mountpoint and block device?

Thanks!

**Comment by cpuguy83** [comment]
`Unmount` is called when the container exits.
The volume plugin needs to recount these if they intend to support multiple consumers of the volume.

In Docker 1.12 `Mount` and `Unmount` will be called with an opaque ID per call so that the plugin can track `Mount`/`Unmount` pairs.
