### ISSUE TITLE
docker daemon start failed after host reboot

### ISSUE THREAD

**Issue by junneyang** [docker/docker#22591]
1. /usr/bin/docker daemon -D
^[[34mINFO^[[0m[0000] [graphdriver] using prior storage driver "aufs"
^[[31mERRO^[[0m[0000] invalid image sha256:30925fb0c4c31dac654dc76903cf84e3e3d103dc822dcde33902f3e3a7b7fd62, failed to verify image: sha256:30925fb0c4c31dac654dc76903cf84e3e3d103dc822dcde33902f3e3a7b7fd62
^[[31mERRO^[[0m[0000] invalid image sha256:3712c88461083d49aa94a4645c9d1d315ff00138e8b3928c40ca4ff0da6f663c, failed to verify image: sha256:3712c88461083d49aa94a4645c9d1d315ff00138e8b3928c40ca4ff0da6f663c
^[[31mERRO^[[0m[0000] invalid image sha256:49465ab45f806e22921dbd51dca118a74d6260317459d9334921900f4d8043fa, failed to verify image: sha256:49465ab45f806e22921dbd51dca118a74d6260317459d9334921900f4d8043fa
^[[31mERRO^[[0m[0000] invalid image sha256:49d695c6c69ed13bbd4ca1147d1a1309f49233b9ec9f2aa336f07a67deb86529, failed to verify image: sha256:49d695c6c69ed13bbd4ca1147d1a1309f49233b9ec9f2aa336f07a67deb86529
^[[31mFATA^[[0m[0000] Error starting daemon: layer does not exist    

2. docker version 
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64
 
 Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64          

3. uname -a
Linux ubuntu-k8s02 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux    

4. cat /etc/issue
Ubuntu 14.04.2 LTS \n \l    

thanks!

**Comment by HackToday** [comment]
it may helpful for you provide details how do you hit such case, like reproduce steps

**Comment by junneyang** [comment]
if this host reboot,  problems come.
i found the /var/log/upstart/docker.log has "Force shutdown daemon" error:
![qq 20160509134233](https://cloud.githubusercontent.com/assets/6802322/15104499/e992d0e2-15eb-11e6-8c1e-d1f444f73785.png)


the whole  /var/log/upstart/docker.log attached below.

thanks!

**Comment by martingartonft** [comment]
is this resolved? What is/was the resolution? Is there a know workaround?

**Comment by dothebart** [comment]
just had that with a docker 1.12.1 on an Ubuntu 16.04 - good that I use ansible to set up shit.
