### ISSUE TITLE
same image and same command but the result is not the same

### ISSUE THREAD

**Issue by yikyo** [docker/docker#22607]
sorry for my english.

when i use docker version 1.11.1 and os centos 7/fedora 23
`docker run yikyo/samba` 
the container will exit

`docker ps -a`

|CONTAINER ID       | IMAGE             |  COMMAND            | CREATED       |      STATUS                    |PORTS               |NAMES|
|---|---|---|---|---|---|---|
|880fe0d858ca       | yikyo/samba    |     "smbd -FS"  |        5 minutes ago    |   Exited (0) 5 minutes ago       |          |       serene_gates|

but when i use docker version 1.9.1 os fedora 23 or docker version 1.6.2 os elementary
`docker run yikyo/samba` 
the container is running

`docker ps `

|CONTAINER ID       | IMAGE             |  COMMAND            | CREATED       |      STATUS                    |PORTS               |NAMES|
|---|---|---|---|---|---|---|
|xxxxxxxxxxxxxx| yikyo/samba    |     "smbd -FS"  |        5 minutes ago    |   Up 5 seconds       |          |       name_xxxxxx|

why my image not run when docker version 1.11.1

Can you help me

thank you.

**Comment by thaJeztah** [comment]
Do the logs for that container show anything useful? Could also be an issue with SELinux (I see it uses a volume)

**Comment by yikyo** [comment]
thank thaJeztah.

there nothing logs  and selinux is disabled.
but docker version 1.11.1 still not run my docker image

**Comment by justincormack** [comment]
It seems to be working for me on a couple of different machines with 1.11.1. Can you run it with `docker run -it  yikyo/samba -d 10` to get the `smbd` debug information, that might help.

**Comment by thaJeztah** [comment]
Closing because we didn't receive feedback from OP
