### ISSUE TITLE
Use docker inside docker with jenkins user

### ISSUE THREAD

**Issue by lorenzvth7** [docker/docker#22608]
version:
```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64
```

I have a docker container (jenkins). I've mounted the sockets to my container so that I can perform docker commands inside my jenkins container. This works fine when I am root user in my container:

    docker run -d -v /var/run/docker.sock:/var/run/docker.sock -v
    /usr/bin/docker:/usr/bin/docker:ro -v
    /lib64/libdevmapper.so.1.02:/usr/lib/x86_64-linux-gnu/libdevmapper.so.1.02
    -v /lib64/libudev.so.0:/usr/lib/x86_64-linux-gnu/libudev.so.0
    -p 8080:8080 --name jenkins -u root --privileged=true -t -i
    my-jenkins:1.0

My dockerfile now looks like this: I add my jenkins user to the docker group so I can perform docker commands with my jenkins user:
```

My dockerfile:
FROM jenkins:1.651.1
COPY plugins.txt /usr/share/jenkins/plugins.txt
RUN /usr/local/bin/plugins.sh /usr/share/jenkins/plugins.txt
 USER root 
 RUN apt-get update 
 RUN groupadd docker && gpasswd -a jenkins docker 
 USER jenkins
```

When I start this container I'm not able to perform the docker commands with my jenkins user. But jenkins is in the dockergroup:
```
docker run -d -v /var/run/docker.sock:/var/run/docker.sock -v
/usr/bin/docker:/usr/bin/docker:ro -v
/lib64/libdevmapper.so.1.02:/usr/lib/x86_64-linux-gnu/libdevmapper.so.1.02
-v /lib64/libudev.so.0:/usr/lib/x86_64-linux-gnu/libudev.so.0
-p 8080:8080 --name jenkins -u jenkins --privileged=true -t -i
my-jenkins:1.0
```

But than it does not work
```
jenkins@bc145b8cfc1d:/$ docker ps
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
jenkins@bc145b8cfc1d:/$ whoami
jenkins
```

This is the content of my /etc/groupon my container
```

jenkins:x:1000:
docker:x:1001:jenkins
```

my jenkins user is in the docker group

```
jenkins@bc145b8cfc1d:/$ groups jenkins
jenkins : jenkins docker
```

**Comment by justincormack** [comment]
The group numbers may not match. In a container you may as well make the docker socket world read and write, with `RUN chmod 666 /var/run/docker.sock` as `USER root`.

**Comment by thaJeztah** [comment]
Don't think that will work, because that would probably change the permissions of the docker.sock on the host (as it is bind-mounted).

But I think jenkins may already have the right uid, so may have access out of the box, let me check

**Comment by lorenzvth7** [comment]
@thaJeztah Thanks for taking a look. I wrote a fast dockerfile (can be written more efficient, I know):
```
FROM jenkins:1.651.1
COPY plugins.txt /usr/share/jenkins/plugins.txt
RUN /usr/local/bin/plugins.sh /usr/share/jenkins/plugins.txt
USER root
RUN apt-get update
RUN apt-get install sudo
RUN echo "jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers
RUN gpasswd -a jenkins root
USER jenkins

```
With this dockerfile I'm able to use the jenkins user in the container and executing docker commands with `sudo docker ...` but this isn't a real good solution.

**Comment by thaJeztah** [comment]
Looks like it;

```bash
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock jenkins:1.651.1 sh -c "ls -la /var/run/docker.sock"
srw-rw---- 1 root jenkins 0 Apr 27 21:40 /var/run/docker.sock
```

Only have some issues, because it's dynamically linked, so using a dynamic client inside the container doesn't work well;

    docker: error while loading shared libraries: libapparmor.so.1: cannot open shared object file: No such file or directory

Bind-mounting a statically linked `docker` client works though

**Comment by justincormack** [comment]
@thaJeztah ah yes of course you are right, not a good idea.

**Comment by thaJeztah** [comment]
Okay, this works for me; I have a statically linked `docker` binary in my local directory, then;

```bash
docker run -it --rm -u jenkins -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/docker:/usr/bin/docker:ro jenkins:1.651.1 bash
jenkins@be12860ad6fa:/$ docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64
```

So, looks like no changes are needed to that image, and it should just work

**Comment by lorenzvth7** [comment]
@thaJeztah 
I tried just the same command:
```
docker run -it --rm -u jenkins -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/docker:/usr/bin/docker:ro jenkins:1.651.1 bash
jenkins@6b0e2305db47:/$ whoami
jenkins
jenkins@6b0e2305db47:/$ docker ps
bash: docker: command not found
jenkins@6b0e2305db47:/$ docker version
bash: docker: command not found
```

**Comment by thaJeztah** [comment]
@lorenzvth7 you should have a static docker binary in your local directory, otherwise docker creates an empty directory called "docker". You can download these here; https://get.docker.com/builds/Linux/x86_64/docker-1.11.1.tgz

Or create a container using the official docker image, and copy it from there

```
# create a temporary container containing the docker binary
docker create --name=tempcontainer docker

# copy the docker binary from the container to your local host
docker cp tempcontainer:/usr/local/bin/docker .

# remove the temp container
docker rm -f tempcontainer
```

**Comment by lorenzvth7** [comment]
Thanks. I tried to install the static binary but did probably something wrong?:
```
sudo yum install -y wget
sudo wget https://get.docker.com/builds/Linux/x86_64/docker-1.11.0.tgz
sudo tar -xvzf docker-1.11.0.tgz
docker/
docker/docker-containerd-ctr
docker/docker
docker/docker-containerd
docker/docker-runc
docker/docker-containerd-shim
$ sudo mv docker/* /usr/bin/
$ sudo docker daemon &

docker ps
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
sudo docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

```
sudo docker run -it --rm -u jenkins -v /var/run/docker.sock:/var/run/docker.sock -v /usr/bin/docker:/usr/bin/docker:ro jenkins:1.651.1 bash
jenkins$ docker ps
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Comment by thaJeztah** [comment]
Oh, you don't need to install them on your host; you just need a static binary in your container (see the comment I showed above)

**Comment by lorenzvth7** [comment]
@thaJeztah Okay, I'm sorry. I'm pretty new to Docker. Is it possible to perform those steps in a Dockerfile? Can you maybe give a short example for that?

**Comment by thaJeztah** [comment]
Well you need that binary added to your image, so either do the steps you did above, but then in your Dockerfile, or use a bind-mount as I showed.

**Comment by lorenzvth7** [comment]
@thaJeztah Still have the same issue when I try to perform the steps in my dockerfile:
```
FROM jenkins:1.651.1
USER root
RUN apt-get install -y wget
RUN wget https://get.docker.com/builds/Linux/x86_64/docker-1.11.0.tgz
RUN tar -xvzf docker-1.11.0.tgz
RUN mv docker/* /usr/bin/
RUN docker daemon &
USER jenkins
```

**Comment by thaJeztah** [comment]
Oh, you don't need the daemon inside the container, so you can skip the `docker daemon &` The daemon runs outside the container, and you communicate with it through the bind-mounted docker.sock. All you need is a docker client binary to communicate with the socket

**Comment by lorenzvth7** [comment]
@thaJeztah  I've performed the following steps:
`docker build -t test/jenkins:1.0 .`

Dockerfile:
```
FROM jenkins:1.651.1
USER root
RUN apt-get install -y wget
RUN wget https://get.docker.com/builds/Linux/x86_64/docker-1.11.0.tgz
RUN tar -xvzf docker-1.11.0.tgz
RUN mv docker/* /usr/bin/
USER jenkins
```

`docker run -it --rm -u jenkins -v /var/run/docker.sock:/var/run/docker.sock test/jenkins:1.0 bash`
```
docker version
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Comment by thaJeztah** [comment]
I can't reproduce, slightly different Dockerfile to skip installing wget but works for me;

```Dockerfile
FROM jenkins:1.651.1
ADD https://get.docker.com/builds/Linux/x86_64/docker-1.11.0.tgz /
USER root
RUN tar -xvzf /docker-1.11.0.tgz \
 && mv docker/* /usr/bin/
USER jenkins
```

```bash
docker run -it --rm -u jenkins -v /var/run/docker.sock:/var/run/docker.sock foo bash
jenkins@d04a2ade8696:/$ docker version
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64
```

Is your hosts's daemon listening on  `/var/run/docker.sock`?

**Comment by lorenzvth7** [comment]
I tried your dockerfile and your commands but did not help.
Maybe this can help:

```
Redirecting to /bin/systemctl status  docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: active (running) since Mon 2016-05-09 19:00:51 UTC; 2s ago
     Docs: https://docs.docker.com
 Main PID: 3611 (docker)
   Memory: 14.5M
   CGroup: /system.slice/docker.service
           ├─3611 /usr/bin/docker daemon -H fd://
           └─3616 docker-containerd -l /var/run/docker/libcontainerd/docker-containerd.sock --runtime docker-runc

May 09 19:00:51 ip-172-31-24-189 docker[3611]: time="2016-05-09T19:00:51.379713026Z" level=info msg="Firewalld running: false"
May 09 19:00:51 ip-172-31-24-189 docker[3611]: time="2016-05-09T19:00:51.428581310Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option ...d IP address"
May 09 19:00:51 ip-172-31-24-189 docker[3611]: time="2016-05-09T19:00:51.473703695Z" level=warning msg="mountpoint for pids not found"
May 09 19:00:51 ip-172-31-24-189 docker[3611]: time="2016-05-09T19:00:51.473939919Z" level=info msg="Loading containers: start."
May 09 19:00:51 ip-172-31-24-189 docker[3611]: ......
May 09 19:00:51 ip-172-31-24-189 docker[3611]: time="2016-05-09T19:00:51.476758925Z" level=info msg="Loading containers: done."
May 09 19:00:51 ip-172-31-24-189 docker[3611]: time="2016-05-09T19:00:51.476772525Z" level=info msg="Daemon has completed initialization"
May 09 19:00:51 ip-172-31-24-189 docker[3611]: time="2016-05-09T19:00:51.476784986Z" level=info msg="Docker daemon" commit=5604cbe graphdriver=devicemapper version=1.11.1
May 09 19:00:51 ip-172-31-24-189 docker[3611]: time="2016-05-09T19:00:51.481919377Z" level=info msg="API listen on /var/run/docker.sock"
May 09 19:00:51 ip-172-31-24-189 systemd[1]: Started Docker Application Container Engine.
Hint: Some lines were ellipsized, use -l to show in full.
```

**Comment by thaJeztah** [comment]
What distribution are you running on? Could this be SELinux blocking access?

**Comment by lorenzvth7** [comment]
I'm running on Centos7. Is it possible to disable it?

**Comment by thaJeztah** [comment]
Hm, you could start with checking if it's labeled indeed; `ls -Z /var/run/docker.sock`. I'm not really good at SELinux labels :blush:

**Comment by lorenzvth7** [comment]
output:
```
ls -Z /var/run/docker.sock
srw-rw----. root docker system_u:object_r:var_run_t:s0   /var/run/docker.sock
```

Wouldn't this be an issue if I try this on for example: Ubuntu?

**Comment by thaJeztah** [comment]
On Ubuntu, SELinux isn't enabled by default, so you don't run into that issue. :smile:

Haven't tried, but you can add `--security-opt=label:type:docker_t` or `--security-opt label=disable`


Looks like someone actually wrote a custom policy for this https://github.com/dpw/selinux-dockersock

**Comment by lorenzvth7** [comment]
@thaJeztah I disabled it and restarted it but didn't work. I tried the same steps which worked for you on Ubuntu14.04 and also didn't work.
