### ISSUE TITLE
 Failed in running docker 1.9.1 & docker 1.11.1 in CORE on Fedora23 

### ISSUE THREAD

**Issue by ztguang** [docker/docker#22604]
Dear Mr. Sebastiaan,

I have failed in running docker 1.9.1 & docker 1.11.1 in CORE on Fedora23
I have taken more than a week to solve it, but I failed.
Could you help me and give some suggestions?
please look at [https://forums.docker.com/t/unable-to-run-docker-images-in-core-on-fedora23/10846]

Best regards,
Tongguang Zhang

**Comment by ztguang** [comment]
now, I make testing again.

//on the host
[root@localhost ~]# systemctl start core-daemon.service
[root@localhost ~]# core-gui

//within a running node

**[root@n1 n1.conf]# docker daemon -s overlay &**
[1] 78
[root@n1 n1.conf]# INFO[0000] New containerd process, pid: 83
             
WARN[0000] containerd: low RLIMIT_NOFILE changing to max  current=1024 max=4096
INFO[0001] Graph migration to content-addressability took 0.00 seconds 
INFO[0001] Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address 
WARN[0001] Your kernel does not support swap memory limit. 
WARN[0001] Your kernel does not support memory reservation. 
WARN[0001] Your kernel does not support oom control.    
WARN[0001] Your kernel does not support memory swappiness. 
WARN[0001] Your kernel does not support kernel memory limit. 
WARN[0001] Your kernel does not support cgroup cpu shares 
WARN[0001] Your kernel does not support cgroup cfs period 
WARN[0001] Your kernel does not support cgroup cfs quotas 
WARN[0001] Your kernel does not support cgroup blkio weight 
WARN[0001] Your kernel does not support cgroup blkio weight_device 
WARN[0001] Your kernel does not support cgroup blkio throttle.read_bps_device 
WARN[0001] Your kernel does not support cgroup blkio throttle.write_bps_device 
WARN[0001] Your kernel does not support cgroup blkio throttle.read_iops_device 
WARN[0001] Your kernel does not support cgroup blkio throttle.write_iops_device 
INFO[0001] Loading containers: start.                   
...
INFO[0001] Loading containers: done.                    
INFO[0001] Daemon has completed initialization          
INFO[0001] Docker daemon                                 commit=5604cbe graphdriver=overlay version=1.11.1
INFO[0001] API listen on /var/run/docker.sock           
**[root@n1 n1.conf]# docker images                                                                                         **
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
busybox             core                47bcc53f74dc        7 weeks ago         1.113 MB
busybox             latest              47bcc53f74dc        7 weeks ago         1.113 MB
**[root@n1 n1.conf]# docker run --rm -it busybox /bin/sh**
ERRO[1245] containerd: start container                   error=oci runtime error: mkdir /sys/fs/cgroup/cpuset: no such file or directory id=cf230dc842200141ab7126161c19b2419b5452714a741a341e6e161d101edb11
 ERRO[1245] Handler for POST /v1.23/containers/cf230dc842200141ab7126161c19b2419b5452714a741a341e6e161d101edb11/start returned error: Container command '/bin/sh' not found or does not exist. 
        docker: Error response from daemon: Container command '/bin/sh' not found or does not exist..
[root@n1 n1.conf]#

**Comment by ztguang** [comment]
**root@n1 n1.conf]# docker info**
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 1
Server Version: 1.11.1
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.8-300.fc23.x86_64
Operating System: Fedora 23 (Twenty Three) (containerized)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.527 GiB
Name: n1
ID: SBWK:GW6I:EMT7:3FZE:DMIU:UYBH:BF3R:C7MB:SDBH:OW4C:ZCCM:2BHF
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No cpu shares support
WARNING: No cpuset support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

**[root@n1 n1.conf]# docker version**
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:57:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:57:43 2016
 OS/Arch:      linux/amd64
[root@n1 n1.conf]#

**Comment by thaJeztah** [comment]
I'm trying to understand what CORE is doing; is CORE also creating a container, and you're trying to run docker inside that? (you mention "within a running node") I don't have any experience with CORE, so wondering what it actually does here

**Comment by ztguang** [comment]
I am using the latest CORE, that is version 4.8.

Here, [http://www.finmars.co.uk/blog/9-core-and-docker-together-at-last] , use  CORE 4.7.

Here, [http://www.finmars.co.uk/blog/6-common-open-research-emulator-core] , gives introduce to CORE.

The official web site, [http://www.nrl.navy.mil/itd/ncs/products/core]

**Comment by thaJeztah** [comment]
Have you tried to run the daemon in debug mode (`docker daemon --debug ....`) to see if there's any useful output? The tutorial you're linking to is over a year old, and a *lot* has changed in Docker that may influence this. Have you tried contacting the CORE developers, is Docker still supported in CORE? I had a quick look at their GitHub repo, and there doesn't seem to be a lot of activity; there's one pull request to improve the stability of docker in CORE, but that's also created a year ago

**Comment by ztguang** [comment]
yes, maybe you are right. I am contacting  the CORE developers. Thank you for your help very much.

[root@localhost core]# ll kernel/
总用量 48
drwxr-xr-x. 3 root root 4096 4月  27 16:02 core-kernel-2.6.38
drwxr-xr-x. 3 root root 4096 4月  27 16:02 core-kernel-3.0
drwxr-xr-x. 3 root root 4096 4月  27 16:02 core-kernel-3.2
drwxr-xr-x. 3 root root 4096 4月  27 16:02 core-kernel-3.5
drwxr-xr-x. 3 root root 4096 4月  27 16:02 core-kernel-3.8
drwxr-xr-x. 5 root root 4096 4月  27 16:02 freebsd
[root@localhost core]#

**Comment by thaJeztah** [comment]
If it's using kernel 3.8, that may well be the issue; docker needs kernel 3.10 as a minimum (although 3.8 may somewhat work).

I'll close this issue for now, but feel free to comment after I closed

**Comment by ztguang** [comment]
thanks for your help again.
