### ISSUE TITLE
Stdin not returned in logs when attaching

### ISSUE THREAD

**Issue by parisk** [docker/docker#22616]
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:44:17 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.8-boot2docker
Operating System: Boot2Docker 1.11.1 (TCL 7.0); HEAD : 7954f54 - Wed Apr 27 16:36:45 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8 MiB
Name: test
ID: FH2L:RUTL:BSCS:2QXV:GTYC:QIJ6:ORIT:2PJH:2SXQ:HUSG:ZH3O:VYMI
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 29
 System Time: 2016-05-09T19:21:09.760320848Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=vmwarefusion
```

**Additional environment details (AWS, VirtualBox, physical, etc.):** Running locally on my OS X laptop

**Steps to reproduce the issue:**
1. Open two terminal tabs (A and B)
2. Run `docker run -ti ubuntu bash` in tab A
3. Get the container id (e.g. `1161105cb75c`)
4. Run `docker attach 1161105cb75c` in tab B
5. Initial output is empty, while I would expect the initial output to be `root@1161105cb75c:/#`

**Describe the results you received:**
- Output of **2.** was `root@1161105cb75c:/#`
- Output of **4.** was **empty**

**Describe the results you expected:**
I would expect output of **4.** to be exactly the same with the output of **2.**.

**Additional information you deem important (e.g. issue happens only occasionally):**
- I would expect this to happen because this is the way tmux handles output when attaching to existing session
- Made a screencast, in order to give you a better picture of how this looks like: https://www.dropbox.com/s/w2dcj6217hhv0sb/docker-attach-sync.mov?dl=0

**Update**: Added the screencast URL, which I forgot at first 😅

**Comment by LK4D4** [comment]
That line already was written to stdout. There is no way to obtain it again.
Tmux sessions is sorta different type of beast, our attach is way simpler.
