### ISSUE TITLE
Docker mongos Link Container: /etc/hosts getting filled up

### ISSUE THREAD

**Issue by dhanugupta** [docker/docker#22610]
**Output of `docker version`:**

```
Client:
 Version:      1.9.1-cs3
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   28d463f
 Built:        Mon Jan  4 21:57:36 UTC 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1-cs3
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   28d463f
 Built:        Mon Jan  4 21:57:36 UTC 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
Images: 46
Server Version: 1.9.1-cs3
Storage Driver: devicemapper
 Pool Name: docker-253:0-12065-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.644 GB
 Data Space Total: 107.4 GB
 Data Space Available: 79.25 GB
 Metadata Space Used: 2.679 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.14.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 4
Total Memory: 15.52 GiB
Name: xxxxx.com
ID: xxxxxx
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Start 2 Container, 1 app and 1 mongos, linked with together
2. Login to app container after your app consuming lots of traffic
3. docker exec -it app bash
4. df -h
5. /etc/hosts file will show consuming lots of disk space, which is unrecoverable, unless you restart the app container.

**Describe the results you received:**
/etc/hosts file get filled up slowly and slowly, not able to free the diskspace.

**Describe the results you expected:**
+ /etc/hosts file should not grow.
+ Not sure where the disk space is going.
**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
Are you seeing new hosts being added to `/etc/hosts`, or is it only growing in size?

**Comment by dhanugupta** [comment]
No new hosts are added, over the course of time, just growing in size..

**Comment by thaJeztah** [comment]
In docker 1.9.1, the `/etc/hosts` file is updated with changes when new containers are started. I wonder if this may be cause by devicemapper keeping track of those changes, but not releasing the disk size.

ping @mavenugo have you seen this before?

**Comment by dhanugupta** [comment]
Agreed! i was expecting that if NEW containers started, /etc/hosts will be updating...but in this case i haven't started the containers atleast for 3 weeks, then 4th week noticing disk space issue. and when i restart the app container all back to normal.

**Comment by steve-gray** [comment]
I've tried restarting the entire box, all the containers, I've got multiple hosts exhibiting this issue. The full details are at #22677 - is there a quick mitigation/way to reclaim the space? The space usage for /etc/hosts is immediately high in my case (check the issue I'd reported) - with over 95% of the space used immediately and then filling/bombing out the child containers at run-time.

-Steve

**Comment by thaJeztah** [comment]
If it's indeed devicemapper causing this, then these two issues may give some info https://github.com/docker/docker/issues/18867 and https://github.com/docker/docker/issues/3182

ping @rhvgoyal any idea if devicemapper could be the culprit here?

**Comment by steve-gray** [comment]
We had to add another disk and expand the LVM underpinning the root filesystem of the *host*, despite all docker volumes existing on the devicemapper on a seperate LVM pool as evidenced by my docker info. This is pretty screwed though, and another few days and we're going to have to do it again. I've tried the flag some other folks have suggested around reclaiming discarded space and no luck - not even a trickle of background cleanup.

Is there some way to force-flush that we can do this on a cron schedule at least?

**Comment by thaJeztah** [comment]
@steve-gray not sure if it works (did a quick test and it seems to run ok), but can you try making `/etc/` a volume, so that it is not using the container's filesystem (thus, not using devicemapper), e.g.;

    docker run -d -v /etc/ --name foo nginx:alpine

Not a fix, but possibly a workaround for now

**Comment by justincormack** [comment]
Does it fix it if you use the daemon option `--storage-opt dm.mountopt=discard` (as discussed in #18867)?

**Comment by justincormack** [comment]
Also can you give the output of `docker run -it alpine mount | grep etc` this issue is quite odd...

**Comment by justincormack** [comment]
What is really odd is that `/etc/hosts` is bind mounted form the host, and not on a device mapper filesystem, so this can't be related to device mapper as far as I can see. How are you measuring the space used by `/etc/hosts` by the way? From the container or the host? Using which command?

**Comment by dhanugupta** [comment]
@justincormack inside the app container, command: df -h and notice /etc/hosts grown over the course of time.

**Comment by justincormack** [comment]
That will actually (confusingly) show the disk usage on the host filesystem, as that is a bind mount. So I think this is just the host filesystem filling up, and completely unrelated to `/etc/hosts`.

**Comment by dhanugupta** [comment]
we have this inside the container 
`/dev/mapper/vg0-srv                                                                                  144G  106G   39G  74% /etc/hosts`

and if you do on host:
`/dev/mapper/vg0-srv   144G  106G   39G  74% /srv`

as far the application is concern we are off loading all the logs to external resource. 
we are running mongos inside the another container, don't see what is consuming the space ..

**Comment by steve-gray** [comment]
The discard option does not work for me at all. I've had to grow the host root volume. What's more frustrating is that the starting from limited space on that mount inexplicably means exhaustion happens as I write to the container at runtime - despite all my container volumes being device mappers running off a completely separate instance of LVM volume group with hundreds of GB free.

From the host side the volume itself never shows it's actually exhausting the space either, it just seems to be constantly near full, and then the containers themselves have issues.

Is there some chance that if the host etc/hosts resides on LVM that somehow we are creating snapshots on that LVM group and never releasing them, so the issue only occurs to people who's root file system for their underlying Kernel is on LVM?

**Comment by steve-gray** [comment]
Sure: it's 3am here though, so give me a few hours till I get to work.

**Comment by steve-gray** [comment]
Host output:

````
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime,seclabel)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
devtmpfs on /dev type devtmpfs (rw,nosuid,seclabel,size=24637820k,nr_inodes=6159455,mode=755)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,seclabel)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,seclabel,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,seclabel,mode=755)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,seclabel,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpuacct,cpu)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls)
configfs on /sys/kernel/config type configfs (rw,relatime)
/dev/mapper/centos-root on / type ext4 (rw,relatime,seclabel,data=ordered)
selinuxfs on /sys/fs/selinux type selinuxfs (rw,relatime)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=28,pgrp=1,timeout=300,minproto=5,maxproto=5,direct)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
mqueue on /dev/mqueue type mqueue (rw,relatime,seclabel)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,seclabel)
/dev/sda1 on /boot type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
tmpfs on /run/user/996 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=4929668k,mode=700,uid=996,gid=992)
tmpfs on /run/user/1001 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=4929668k,mode=700,uid=1001,gid=1001)
````

**Comment by steve-gray** [comment]
@icecrime - Please untag 1.9 from this, unless that meaning is 1.9+ - because we've had this issue on 1.10 and 1.11. It is not 1.9 specific.

**Comment by thaJeztah** [comment]
@steve-gray added the other versions; were trying out an automated script to label issues with the version issues were reported with

**Comment by icecrime** [comment]
@steve-gray Nothing in the issue mentions that it's not 1.9 specific as far as I can tell.

**Comment by steve-gray** [comment]
I'm having it on 1.10/1.11: exact same issue. My issue was closed as a duplicate but there's a cluster of very similar issues that all appear to be same. The /etc/hosts mount in containers fills - even independently of it changing, causing containers to fail with out of space error.

**Comment by justincormack** [comment]
As the `/etc/hosts` file is on the host filesystem, that is just showing that your root filesystem is filling up. I don't think anyone has shown there is actually an issue with Docker.

**Comment by steve-gray** [comment]
Citation needed: These boxes are nothing but a barebones image with docker installed. Doing cat /etc/hosts shows the file is physically only a few lines and the only software that's been updated on them is the docker engine itself.

It seems like docker is potentially not releasing something in Devicemapper-land, because the rate of space consumption is proportional to the amount of containers - so our high churn drone.io servers end up hitting this pretty hard - but we can see the space creeping up on other servers. It's proportional to container creation/destruction rate.

Is docker doing some magic to map the hosts file into the container and not releasing it when the storage for the hosts file is on a different LVM group to the containers? From user land on the host side there is no obvious explanation as to why the disk space is being consumed.

**Comment by justincormack** [comment]
It is nothing to do with the hosts file, this is completely misleading. The root filesystem is filling up, which may well be to do with a devicemapper issue. Can you see if you can see where/if the space is being used under `/var/lib/docker`?

**Comment by steve-gray** [comment]
Is there some specific command you want to be run? It'll need to wait till Monday but I can throw the results up here when it's done.

The usual df/du output doesn't show anything obvious from memory, but can rerun.

**Comment by justincormack** [comment]
Maybe check with `du`, maybe try to get summary info from it, not sure what is the best way exactly.

**Comment by lucke84** [comment]
@justincormack I tried and validate your idea, here's the outcome.

Currently running on AWS 64bit Amazon Linux 2016.03 v2.1.1 running Multi-container Docker 1.9.1 (Generic). Each instance run 3 containers: an app, nginx, and the amazon ecs agent.

The host machine's disk usage:
```
[ec2-user@ip-blablabla ~]$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda1      7.8G  7.8G     0 100% /
devtmpfs        994M  120K  994M   1% /dev
tmpfs          1002M     0 1002M   0% /dev/shm
```

The container's disk usage:
```
[ec2-user@ip-blablabla ~]$ sudo docker exec -ti 3c64a7db1802 df -h
Filesystem                                                                                        Size  Used Avail Use% Mounted on
/dev/mapper/docker-202:1-263797-3c64a7db1802dc5a4468e935acecf54dd19b28daed13fd6b9977775fdc12d62d  100G  683M  100G   1% /
tmpfs                                                                                            1002M     0 1002M   0% /dev
tmpfs                                                                                            1002M     0 1002M   0% /sys/fs/cgroup
/dev/xvda1                                                                                        7.8G  7.8G     0 100% /etc/hosts
shm                                                                                                64M     0   64M   0% /dev/shm
tmpfs                                                                                            1002M     0 1002M   0% /proc/kcore
tmpfs                                                                                            1002M     0 1002M   0% /proc/latency_stats
tmpfs                                                                                            1002M     0 1002M   0% /proc/timer_stats
```

The disk usage for `/var/lib/docker`:
```
[ec2-user@ip-blablabla ~]$ sudo du -sh /var/lib/docker/
6.2G	/var/lib/docker/
```

And specifically (3 entries per each of the 3 container, the app's the biggest):
```
[ec2-user@ip-blablabla ~]$ sudo du -h /var/lib/docker/containers
4.0K	/var/lib/docker/containers/ee288c7da18e813d2f8b4cec28251a75b85d621ddc19f0305116105e49f33d5b/mqueue
4.0K	/var/lib/docker/containers/ee288c7da18e813d2f8b4cec28251a75b85d621ddc19f0305116105e49f33d5b/shm
229M	/var/lib/docker/containers/ee288c7da18e813d2f8b4cec28251a75b85d621ddc19f0305116105e49f33d5b
4.0K	/var/lib/docker/containers/3c64a7db1802dc5a4468e935acecf54dd19b28daed13fd6b9977775fdc12d62d/mqueue
4.0K	/var/lib/docker/containers/3c64a7db1802dc5a4468e935acecf54dd19b28daed13fd6b9977775fdc12d62d/shm
6.0G	/var/lib/docker/containers/3c64a7db1802dc5a4468e935acecf54dd19b28daed13fd6b9977775fdc12d62d
4.0K	/var/lib/docker/containers/8f488b9888d1e377bcfc6cf12cce7b07c50155fb25f2d22ec1ca646607681074/mqueue
4.0K	/var/lib/docker/containers/8f488b9888d1e377bcfc6cf12cce7b07c50155fb25f2d22ec1ca646607681074/shm
40K	/var/lib/docker/containers/8f488b9888d1e377bcfc6cf12cce7b07c50155fb25f2d22ec1ca646607681074
6.2G	/var/lib/docker/containers
```

And, finally, the largest file in the app's container:
```
[ec2-user@ip-blablabla ~]$ sudo ls -lah /var/lib/docker/containers/3c64a7db1802dc5a4468e935acecf54dd19b28daed13fd6b9977775fdc12d62d
total 6.0G
drwx------ 4 root root 4.0K Aug  5 00:01 .
drwx------ 5 root root 4.0K Aug  5 03:01 ..
-rw------- 1 root root 6.0G Sep  3 11:36 3c64a7db1802dc5a4468e935acecf54dd19b28daed13fd6b9977775fdc12d62d-json.log
-rw-r--r-- 1 root root 4.5K Aug  5 00:01 config.json
-rw-r--r-- 1 root root  750 Aug  5 00:01 hostconfig.json
-rw-r--r-- 1 root root   13 Aug  5 00:01 hostname
-rw-r--r-- 1 root root  174 Aug  5 00:01 hosts
drwx------ 2 root root 4.0K Aug  5 00:01 mqueue
-rw-r--r-- 1 root root  122 Aug  5 00:01 resolv.conf
-rw------- 1 root root   71 Aug  5 00:01 resolv.conf.hash
drwx------ 2 root root 4.0K Aug  5 00:01 shm
```

With its `head` and `tail`: 
```
[ec2-user@ip-blablabla ~]$ sudo head /var/lib/docker/containers/3c64a7db1802dc5a4468e935acecf54dd19b28daed13fd6b9977775fdc12d62d/3c64a7db1802dc5a4468e935acecf54dd19b28daed13fd6b9977775fdc12d62d-json.log
{"log":"*** Starting uWSGI 2.0.12 (64bit) on [Fri Aug  5 00:01:18 2016] ***\n","stream":"stderr","time":"2016-08-05T00:01:18.950754626Z"}
{"log":"compiled with version: 4.8.4 on 28 January 2016 10:59:16\n","stream":"stderr","time":"2016-08-05T00:01:18.950822967Z"}
{"log":"os: Linux-4.4.8-20.46.amzn1.x86_64 #1 SMP Wed Apr 27 19:28:52 UTC 2016\n","stream":"stderr","time":"2016-08-05T00:01:18.950837654Z"}
{"log":"nodename: 3c64a7db1802\n","stream":"stderr","time":"2016-08-05T00:01:18.950849177Z"}
{"log":"machine: x86_64\n","stream":"stderr","time":"2016-08-05T00:01:18.950860423Z"}
{"log":"clock source: unix\n","stream":"stderr","time":"2016-08-05T00:01:18.950871624Z"}
{"log":"detected number of CPU cores: 1\n","stream":"stderr","time":"2016-08-05T00:01:18.95088277Z"}
{"log":"current working directory: /project\n","stream":"stderr","time":"2016-08-05T00:01:18.950909699Z"}
{"log":"detected binary path: /project/.venv/bin/uwsgi\n","stream":"stderr","time":"2016-08-05T00:01:18.95092343Z"}
{"log":"!!! no internal routing support, rebuild with pcre support !!!\n","stream":"stderr","time":"2016-08-05T00:01:18.950976578Z"}
```

```
[ec2-user@ip-blablabla ~]$ sudo tail /var/lib/docker/containers/3c64a7db1802dc5a4468e935acecf54dd19b28daed13fd6b9977775fdc12d62d/3c64a7db1802dc5a4468e935acecf54dd19b28daed13fd6b9977775fdc12d62d-json.log
{"log":"[pid: 1|app: 0|req: 32640199/32640665] 172.31.32.111 () {40 vars in 529 bytes} [Fri Sep  2 06:35:02 2016] GET / =\u003e generated 1526 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 148 bytes (1 switches on core 0)\n","stream":"stderr","time":"2016-09-02T06:35:02.769640975Z"}
{"log":"[pid: 1|app: 0|req: 32640200/32640666] 172.31.30.212 () {40 vars in 529 bytes} [Fri Sep  2 06:35:02 2016] GET / =\u003e generated 1526 bytes in 2 msecs (HTTP/1.1 200) 3 headers in 148 bytes (1 switches on core 0)\n","stream":"stderr","time":"2016-09-02T06:35:02.817847179Z"}
{"log":"[pid: 1|app: 0|req: 32640201/32640667] 172.31.32.111 () {40 vars in 590 bytes} [Fri Sep  2 06:35:02 2016] GET /related_places/?place_id=158920 =\u003e generated 6295 bytes in 65 msecs (HTTP/1.1 200) 3 headers in 148 bytes (1 switches on core 0)\n","stream":"stderr","time":"2016-09-02T06:35:02.888470869Z"}
{"log":"[pid: 1|app: 0|req: 32640202/32640668] 172.31.30.212 () {40 vars in 529 bytes} [Fri Sep  2 06:35:02 2016] GET / =\u003e generated 1526 bytes in 2 msecs (HTTP/1.1 200) 3 headers in 148 bytes (1 switches on core 0)\n","stream":"stderr","time":"2016-09-02T06:35:02.891268709Z"}
{"log":"[pid: 1|app: 0|req: 32640203/32640669] 172.31.30.212 () {40 vars in 529 bytes} [Fri Sep  2 06:35:02 2016] GET / =\u003e generated 1526 bytes in 2 msecs (HTTP/1.1 200) 3 headers in 148 bytes (1 switches on core 0)\n","stream":"stderr","time":"2016-09-02T06:35:02.907287406Z"}
{"log":"[pid: 1|app: 0|req: 32640204/32640670] 172.31.32.111 () {40 vars in 529 bytes} [Fri Sep  2 06:35:02 2016] GET / =\u003e generated 1526 bytes in 2 msecs (HTTP/1.1 200) 3 headers in 148 bytes (1 switches on core 0)\n","stream":"stderr","time":"2016-09-02T06:35:02.97825709Z"}
{"log":"[pid: 1|app: 0|req: 32640205/32640671] 172.31.30.212 () {40 vars in 529 bytes} [Fri Sep  2 06:35:02 2016] GET / =\u003e generated 1526 bytes in 2 msecs (HTTP/1.1 200) 3 headers in 148 bytes (1 switches on core 0)\n","stream":"stderr","time":"2016-09-02T06:35:02.981448384Z"}
{"log":"[pid: 1|app: 0|req: 32640206/32640672] 172.31.30.212 () {40 vars in 529 bytes} [Fri Sep  2 06:35:03 2016] GET / =\u003e generated 1526 bytes in 2 msecs (HTTP/1.1 200) 3 headers in 148 bytes (1 switches on core 0)\n","stream":"stderr","time":"2016-09-02T06:35:03.033351437Z"}
{"log":"[pid: 1|app: 0|req: 32640207/32640673] 172.31.32.111 () {40 vars in 529 bytes} [Fri Sep  2 06:35:03 2016] GET / =\u003e generated 1526 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 148 bytes (1 switches on core 0)\n","stream":"stderr","time":"2016-09-02T06:35:03.056092633Z"}
```

**Comment by rhvgoyal** [comment]
Are these container logs? May be logging to host journald might help instead of keeping logging per container.

**Comment by lucke84** [comment]
@rhvgoyal yes, they seem to be container logs accumulated over time. Is there a particular setting to tweak or it's internal to Docker?

**Comment by cpuguy83** [comment]
@lucke84 You can configure the max file size of container logs, as well as number of rotations to keep.

https://docs.docker.com/engine/admin/logging/overview/#/json-file-options

**Comment by rhvgoyal** [comment]
Or use a different logging driver. Say --log-driver=journald

**Comment by justincormack** [comment]
Ok as this was just a large container log I am closing this issue as resolved.
