### ISSUE TITLE
/var/lib/docker.sock not created when docker restarts after plugins fail

### ISSUE THREAD

**Issue by erikh** [docker/docker#22615]
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 16
 Running: 1
 Paused: 0
 Stopped: 15
Images: 36
Server Version: 1.11.1
Storage Driver: devicemapper
 Pool Name: contiv-dockerthin
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 974.1 MB
 Data Space Total: 10.49 GB
 Data Space Available: 9.512 GB
 Metadata Space Used: 1.581 MB
 Metadata Space Total: 12.58 MB
 Metadata Space Available: 11 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local volplugin
 Network: bridge null host
Kernel Version: 3.10.0-327.13.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.64 GiB
Name: mon0
ID: K7UW:YMX3:HU3B:GBOC:XURC:ZTLJ:HJKV:RKKC:PSDZ:ZMUW:GSR7:PDIO
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
No Proxy: 192.168.24.50,192.168.24.10,192.168.24.11,192.168.24.12
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Cluster store: etcd://localhost:2379
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

centos7.2 with -dm.thinpooldev enabled (and it's working properly.)

**Steps to reproduce the issue:**
1. make a volume plugin, and mount some stuff to it via `docker run`
2. kill said volume plugin
3. restart docker (with the containers still existing)

**Describe the results you received:**

Chaos and misery, death and betrayal!

Actually just /var/run/docker.sock doesn't exist. Sometimes docker just shits the bed and won't restart, and the `docker-containerd-shim` processes linger (which I presume is docker hanging trying to kill these) and kill -9 gets angry.

**Describe the results you expected:**

Solace and peace.

/var/run/docker.sock should probably exist.

**Additional information you deem important (e.g. issue happens only occasionally):**

I'm running a `curl | sh` against systemd with a custom service. Here's the service file:

```
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target docker.socket
Requires=docker.socket

[Service]
TimeoutStartSec=5m
Type=notify
ExecStart=/usr/bin/docker daemon --storage-opt dm.thinpooldev=/dev/mapper/contiv-dockerthin -H fd:// --cluster-store=etcd://localhost:2379
MountFlags=slave
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity

[Install]
WantedBy=multi-user.target
```

Hope all this helps, have a good day peoples.

**Comment by erikh** [comment]
Oh and here's my systemd log: https://gist.github.com/5cc7141b91e79281dca64bd4f2426d6e

You can see the failures as it polls volplugin (which is down at that point, this is my test env). This is on startup. I think this should not be a problem , but feel free to disagree i suppose.

command: `sudo systemctl status docker -l -n 10000`

**Comment by anusha-ragunathan** [comment]
I tried to reproduce the issue using the "Local Persist Plugin" (https://github.com/CWSpear/local-persist). The plugin runs as a container. I `docker kill <pluginContainerID>`, when the named volume exported by the plugin is mounted in another container. Docker daemon restarts just fine, recreating the docker API socket (/var/run/docker.sock) on start.

The posted log snippet shows that the daemon is indeed listening on "/var/run/docker.sock".This log doesnt correspond with the actual error symptoms.

May 09 19:20:52 mon0 docker[33905]: time="2016-05-09T19:20:52.575871508Z" level=info msg="Loading containers: done."
May 09 19:20:52 mon0 docker[33905]: time="2016-05-09T19:20:52.575885257Z" level=info msg="Daemon has completed initialization"
^^^^^^^^^^^^^^^^^ (By now, the socket has been successfully created. Else we would not see this message. Socket is created early during the init process.
docker/daemon.go: CmdDaemon -> listeners.Init()
docker/docker/pkg/listeners/listeners_unix.go: Init() -> sockets.NewUnixSocket)

May 09 19:20:52 mon0 docker[33905]: time="2016-05-09T19:20:52.575893938Z" level=info msg="Docker daemon" commit=5604cbe graphdriver=devicemapper version=1.11.1
May 09 19:20:52 mon0 docker[33905]: time="2016-05-09T19:20:52.579087498Z" level=info msg="API listen on [::]:2385"
May 09 19:20:52 mon0 docker[33905]: time="2016-05-09T19:20:52.579087499Z" level=info msg="API listen on /var/run/docker.sock"
May 09 19:20:52 mon0 systemd[1]: Started Docker Application Container Engine.

If you can reproduce the issue, please provide details on:
- What volume plugin are you using? Does it run as a container? How do you kill it?
- Did this work in an earlier release or with a different volume plugin before?
- Provide daemon logs corresponding to when you observe this issue.

**Comment by erikh** [comment]
Ok, let's close it then.

**Comment by erikh** [comment]
The issue happens when the volume plugin fails to respond to docker during startup.

you should be able to write a small program that only creates a unix socket that nothing is listening to, to accomplish this. I, again, have not distilled the use case.

I don't really want to argue if I saw the bug or not. :)

**Comment by erikh** [comment]
and has existing containers with mounts, I think

**Comment by erikh** [comment]
ok, can't reproduce anymore. feel free to close this if you can't either.

**Comment by thaJeztah** [comment]
Looks like we weren't able to, but ping me if you see it again @erikh 👍

**Comment by erikh** [comment]
Proof!

```
root     18389  1.2  1.8 2547844 71764 ?       Ssl  21:44   0:48 /usr/bin/docker daemon --storage-opt dm.thinpooldev=/dev/mapper/contiv-dockerthin -H fd:// --cluster-store=etcd://localhost:2379
root     18394  0.0  0.3 438340 13648 ?        Ssl  21:44   0:02 docker-containerd -l /var/run/docker/libcontainerd/docker-containerd.sock --runtime docker-runc
root     20387  0.0  0.0 275476  2200 ?        Sl   21:45   0:00 docker-containerd-shim d6933c7c83e4a01c3b94c64e23238c6846dd064a702ec411c2a189dbf239bd1f /var/run/docker/libcontainerd/d6933c7c83e4a01c3b94c64e23238c6846dd064a702ec411c2a189dbf239bd1f docker-runc
root     20597  0.0  0.1 341524  4248 ?        Sl   21:45   0:00 docker-containerd-shim 1280dfef6800d84170742f1b26ba5f2d2af79fff88a0936d50773e30b5d99e40 /var/run/docker/libcontainerd/1280dfef6800d84170742f1b26ba5f2d2af79fff88a0936d50773e30b5d99e40 docker-runc
root     21023  0.0  0.0 275732  2180 ?        Sl   21:45   0:02 docker-containerd-shim 77e849cd3f513e1d3c12cd8c52b23b59c0c34b873cf7c5603279cc07b3c8b257 /var/run/docker/libcontainerd/77e849cd3f513e1d3c12cd8c52b23b59c0c34b873cf7c5603279cc07b3c8b257 docker-runc
root     21090  0.0  0.1 267536  4288 ?        Sl   21:45   0:00 docker-containerd-shim bbf930bd76af19478c4e8f7362409747efb52a24871d193f048f0815326d1a75 /var/run/docker/libcontainerd/bbf930bd76af19478c4e8f7362409747efb52a24871d193f048f0815326d1a75 docker-runc
root     21160  0.0  0.0 266736  2388 ?        Sl   21:45   0:00 docker-containerd-shim d456bf8751d78d2858027d16ef054146b5ff61a1c562e247485a8f06b786d570 /var/run/docker/libcontainerd/d456bf8751d78d2858027d16ef054146b5ff61a1c562e247485a8f06b786d570 docker-runc
vagrant  24687  0.0  0.0 112652   976 pts/0    S+   22:49   0:00 grep --color=auto docker
[vagrant@mon0 ~]$ docker ps
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Comment by erikh** [comment]
Here's the docker logs:

https://gist.github.com/354d676bfa4581a3ca8399b8ae7bcc38

I'll try to avoid trashing the VMs until someone can get back to me; also can provide more if you want, including test logs and other data.

**Comment by thaJeztah** [comment]
Let me reopen :smile:

**Comment by erikh** [comment]
I'm sorry to press, but I need to shutdown these VMs so I can continue my own work. Can someone give me a list of what they want before EOD?

**Comment by erikh** [comment]
I know it's been a long weekend, I just need this box back is all. :D

**Comment by thaJeztah** [comment]
Let me try to rattle some cages. Sorry Erik!

**Comment by thaJeztah** [comment]
@erikh quick update; @tiborvass just landed in SF, and will try to make time to have a look today

**Comment by anusha-ragunathan** [comment]
@erikh : Does the issue happen without systemd involved in startup? Can you retry by starting daemon manually rather than using a systemd service file? Daemon always creates the socket on Init and throws an error if it is unable to create one. https://github.com/docker/docker/blob/master/pkg/listeners/listeners_unix.go#L35. So I'm not sure how we end-up not seeing the expected error.

**Comment by anusha-ragunathan** [comment]
What does your docker.socket unit file look like? When systemd handles startup, docker.socket is created and maintained by systemd, as part of socket activation.

**Comment by erikh** [comment]
@anusha-ragunathan I will try to repro later without systemd but it is very hard to trigger at all, so be aware it may take some time.

Here is the systemd unit running docker:

```
[vagrant@mon0 ~]$ cat /usr/lib/systemd/system/docker.service
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target docker.socket
Requires=docker.socket

[Service]
TimeoutStartSec=5m
Type=notify
ExecStart=/usr/bin/docker daemon --storage-opt dm.thinpooldev=/dev/mapper/contiv-dockerthin -H fd:// --cluster-store=etcd://localhost:2379
MountFlags=shared
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity

[Install]
WantedBy=multi-user.target
```

And the socket file:

```
[Unit]
Description=Docker Socket for the API
PartOf=docker.service

[Socket]
ListenStream=/var/run/docker.sock
SocketMode=0660
SocketUser=root
SocketGroup=docker

[Install]
WantedBy=sockets.target
```

Unfortunately, because I am trying to get a volume plugin working, I have to keep the mount flags the way they are (so we can propagate mounts back up to the root namespace)

**Comment by erikh** [comment]
I'll keep the VMs up for another day so we can suitably exchange what's necessary. I'll try to get you guys a shell into it too, it's on my home network.

**Comment by erikh** [comment]
I've sent @tiborvass credentials to his work email. Please share with anyone who needs to diagnose the system. I'll try to keep it up through tomorrow.

**Comment by anusha-ragunathan** [comment]
@erikh: docker.socket unit file looks normal. Failure to create the docker listen socket should throw the "can't create unix socket" error message. So, I'd highly recommend trying the test case in a loop without systemd.

**Comment by erikh** [comment]
OK. I will try to do what I can soon. Do you still need the VMs?

**Comment by anusha-ragunathan** [comment]
If its a consistent repro environment, uploading the VM image could help.

**Comment by anusha-ragunathan** [comment]
Also, please run daemon in debug mode. "ExecStart=/usr/bin/docker daemon --debug"

**Comment by erikh** [comment]
Can you email me @ h-e@hollensbe.org? I will give you access to the 
machine directly.

**Comment by anusha-ragunathan** [comment]
Daemon cli start creates listening socket using listeners.Init(). In your setup, the daemon is started using "-H fd://", which implies that daemon will use the listening socket created by systemd. Also, there are no errors from daemon init as seen in the posted logs.

Daemon as part of initialization in NewDaemon, calls configureVolumes(). This function initializes volume drivers, both local and otherwise. For volume drivers such as contiv/volplugin, store.New looks up metadata.db, opens boltdb connection and initializes volumes bucket (refer to volume/store/store.go). If there are errors in this path, NewDaemon returns error and exits. Again this is not witnessed in the logs.

A scan of the plugin socket directory (/run/docker/plugins) happens lazily and not on daemon startup. If there's a volume to be created for the first time using a specific volume driver, then the plugin socket is activated (aka socket activation). This is something that is not part of daemon initialization.

Thanks for providing the VM setup. I tried to repro the error by killing the "volplugin" container and restarting the daemon. Daemon restarted fine.

As next steps, I would suggest running the test setup in a loop with:
- Running daemon with -d
- Starting daemon independent of systemd.

**Comment by erikh** [comment]
SGTM. I will try to do this over the weekend.

Thanks for the extra mile on this to help get it resolved.

**Comment by tiborvass** [comment]
Hey @erikh do you have any news on this one? We might not be able to fix it for 1.12.0 :(

**Comment by erikh** [comment]
It's ok. Let's close it or set it aside, I haven't been able to 
reproduce lately.

**Comment by thaJeztah** [comment]
@erikh can you close it yourself? then you can reopen when needed (I think you won't be able to if I close it)

**Comment by erikh** [comment]
sgtm

**Comment by tiborvass** [comment]
Thanks!
