### ISSUE TITLE
docker stats - aggregation and output to file

### ISSUE THREAD

**Issue by sammcj** [docker/docker#22618]
Two part related feature request for `docker stats`:
1. It would be fantastic if you were able to stream the output from `docker stats` to a CSV or similar simple output file for processing.
2. Stats aggregation would be very helpful, i.e. add the ability to get the average for each stat as long as the command (or daemon perhaps?) was run.

**Comment by thaJeztah** [comment]
I don't think this is something that should be in the core functionality of docker; I can see it being useful, but can be implemented as an external tool that connects to the remote API.

**Comment by sammcj** [comment]
OK, thank you for your input @thaJeztah, while I somewhat agree with you, I think that the stats command by itself is not very useful unless it has these features.

**Comment by cpuguy83** [comment]
@sammcj The CLI should not be used for automated tasks.
This is what the API is for, which streams the stats as json and can be consumed by other services.

What might be interesting is support for metrics backends that metrics can be forwarded to.

**Comment by sammcj** [comment]
That may be, but there are plenty of situations where people use docker and just want to get metrics much like nmon + htop are used. Not every implementation of use case is a large deployment with people hosting and supporting monitoring tools - some times the old way of going deep and seeing what's really going on straight on a docker host is the fastest way to understand a situation.

**Comment by thaJeztah** [comment]
You'd already be able to capture it in a file; with a bit of extra scripting, you should be able to automate that to run every xx seconds, e.g.;

```bash
docker stats -a --no-stream >> mystats.csv
```

**Comment by LK4D4** [comment]
I think it would be too much for us to implement.

**Comment by andycampbell92** [comment]
while true; do sudo docker stats -a --no-stream >> stats.txt; done

This will log until you kill it

**Comment by KEMBL** [comment]
for windows 
docker stats  | find /V "CONTAINER" >> dstats.txt
(!) sometimes connection with daemon could crash but as a fast solution it works fine

**Comment by zwbetz-gh** [comment]
Building off of @campbell-codes's snippet, this will append stats to a file (and stdout) every 1 second:

```
while true; do docker stats --no-stream | tee --append stats.txt; sleep 1; done
```

**Comment by sparrc** [comment]
I wrote a thing to output the docker cpu stats in json/csv in case anyone finds it useful: https://github.com/sparrc/containermon/

**Comment by maghsk** [comment]
> Building off of @campbell-codes's snippet, this will append stats to a file (and stdout) every 1 second:
> 
> ```
> while true; do docker stats --no-stream | tee --append stats.txt; sleep 1; done
> ```

Since docker stats costs some time on my VPS... We could use multiprocessing to get better timing.

```bash
INTERVAL=5
OUTNAME=filename.txt

update_file() {
  docker stats --no-stream --format "table {{.Name}},{{.CPUPerc}},{{.MemUsage}},{{.NetIO}},{{.BlockIO}},{{.PIDs}}" | tee --append $OUTNAME;
  echo $(date +'%s.%N') | tee --append $OUTNAME;
}

while true;
do
  update_file &
  sleep $INTERVAL;
done
```
