### ISSUE TITLE
How to use the docker restful api  POST /build

### ISSUE THREAD

**Issue by luguangzhen** [docker/docker#22629]
When I follow the guide https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#build-image-from-a-dockerfile, and the post url is http://xxxx:4243/build?t=test&remote=http://xxxx:8910/app/tmp/Dockerfile.tar.gz . The request is always timout, even thought changer the timeout setting longer.

**Comment by thaJeztah** [comment]
I don't think using a remote Dockerfile supports `.tar.gz`

> "remote" - A Git repository URI or HTTP/HTTPS URI build source. If the URI specifies a filename, the file’s contents are placed into a file called Dockerfile.

In this case, the `Dockerfile.tar.gz` will be saved as Dockerfile, but docker doesn't expect a compressed Dockerfile.

Can you try if it works if the remote Dockerfile is not compressed?

**Comment by luguangzhen** [comment]
When I change the remote value to Dockerfile, this question is still exist.
However, this api can be used by the Jersey client, like below, the request file name ends with .tar.gz.

`Client client = buildClient();
 WebTarget target = client.target(apiUrl);
 Response response = target.request().post(Entity.entity(new File(filePath), "application/tar"));
 String result = response.readEntity(String.class);`

So, maybe something wrong when I use the restful tool to post this api.
