### ISSUE TITLE
[doc] aufs must not be incompatibile with itself

### ISSUE THREAD

**Issue by kosaki** [docker/docker#22624]
Select a storage driver guide (https://docs.docker.com/engine/userguide/storagedriver/selectadriver/) has a following table.

|Storage driver |Must match backing filesystem |Incompatible with   |
|---------------|------------------------------|--------------------|
|`overlay`      |No                            |`btrfs` `aufs` `zfs`|
|`aufs`         |No                            |`btrfs` `aufs`      |
|`btrfs`        |Yes                           |   N/A              |
|`devicemapper` |No                            |   N/A              |
|`vfs`          |No                            |   N/A              |
|`zfs`          |Yes                           |   N/A              |

But aufs must not be incompatible with itself. I suspect the auther intended to:

|`aufs`         |No                            |`btrfs` `overlay`      |

Thought?

**Comment by HackToday** [comment]
No, @kosaki 
From https://github.com/docker/docker/blob/master/daemon/graphdriver/aufs/aufs.go#L98
you could check that, aufs can not run on top of aufs.(it means incompatible here)

**Comment by kosaki** [comment]
Oh, I misunderstood what the table mean. Please close this ticket then.

**Comment by thaJeztah** [comment]
Correct, running layered filesystems on top of layered filesystems (e.g. when running docker-in-docker) is known to cause issues.

Looking at the table, I think overlay should also be added to that table (i.e. don't run overlay on overlay, or aufs on overlay)
