### ISSUE TITLE
Proposal: Support for docker ps filter to accept network name and list containers

### ISSUE THREAD

**Issue by sainath14** [docker/docker#22639]
Support for docker ps command to accept network as filter

docker ps --filter network=mynet

Output should contain all the containers inside the network "mynet"

**Comment by sainath14** [comment]
@thaJeztah Can I submit a PR or should I wait for some acceptance?

**Comment by thaJeztah** [comment]
You can open a pull request, and we can discuss the design during design review (but no guarantee it gets accepted, it may depend on the implementation / changes required)

**Comment by sainath14** [comment]
#dibs

**Comment by LK4D4** [comment]
Was implemented.
