### ISSUE TITLE
Docker can only start on the default bridge IP range

### ISSUE THREAD

**Issue by borzwazie** [docker/docker#22638]
root@stuckjobs:/var/log# docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:43:49 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

Ubuntu Gnome 16.04

**Steps to reproduce the issue:**
1. Install Docker in the normal way on Ubuntu 16.04 (via the shell script from docker.com)
2. Try to change the bip value to anything at all
3. Docker will fail to start with the error:

FATA[0001] Error starting daemon: Error initializing network controller: Error creating default "bridge" network: failed to allocate gateway (192.168.17.0): Address already in use 

root@stuckjobs:/var/log# docker daemon --debug --bip=192.168.17.0/24
DEBU[0000] docker group found. gid: 999                 
DEBU[0000] Listener created for HTTP on unix (/var/run/docker.sock) 
INFO[0000] previous instance of containerd still alive (3946) 
DEBU[0000] containerd connection state change: READY    
DEBU[0000] Using default logging driver json-file       
DEBU[0000] Golang's threads limit set to 113130         
DEBU[0000] received past containerd event: &types.Event{Type:"live", Id:"", Status:0x0, Pid:"", Timestamp:0x57323750} 
INFO[0000] [graphdriver] using prior storage driver "aufs" 
DEBU[0000] Using graph driver aufs                      
INFO[0000] Graph migration to content-addressability took 0.00 seconds 
DEBU[0000] Option DefaultDriver: bridge                 
DEBU[0000] Option DefaultNetwork: bridge                
INFO[0000] Firewalld running: false                     
DEBU[0000] /sbin/iptables, [--wait --version]           
DEBU[0000] /sbin/iptables, [--wait -t nat -D PREROUTING -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL -j DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t nat -D PREROUTING] 
DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT]    
DEBU[0000] /sbin/iptables, [--wait -t nat -F DOCKER]    
DEBU[0000] /sbin/iptables, [--wait -t nat -X DOCKER]    
DEBU[0000] /sbin/iptables, [--wait -t filter -F DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t filter -X DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t filter -F DOCKER-ISOLATION] 
DEBU[0000] /sbin/iptables, [--wait -t filter -X DOCKER-ISOLATION] 
DEBU[0000] /sbin/iptables, [--wait -t nat -n -L DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t nat -N DOCKER]    
DEBU[0000] /sbin/iptables, [--wait -t filter -n -L DOCKER] 
DEBU[0000] /sbin/iptables, [--wait -t filter -n -L DOCKER-ISOLATION] 
DEBU[0000] /sbin/iptables, [--wait -t filter -C DOCKER-ISOLATION -j RETURN] 
DEBU[0000] /sbin/iptables, [--wait -I DOCKER-ISOLATION -j RETURN] 
DEBU[0000] Registering ipam driver: "default"           
DEBU[0000] Registering ipam driver: "null"              
DEBU[0000] Allocating IPv4 pools for network bridge (bf37c4e53ecf09b00146bb9a7aae62c9475a6cd4a7611a37629896f9b1c99115) 
DEBU[0000] RequestPool(LocalDefault, 192.168.17.0/24, , map[], false) 
DEBU[0000] RequestAddress(LocalDefault/192.168.17.0/24, 192.168.17.0, map[RequestAddressType:com.docker.network.gateway]) 
DEBU[0000] ReleasePool(LocalDefault/192.168.17.0/24)    
DEBU[0000] Cleaning up old mountid : start.             
FATA[0000] Error starting daemon: Error initializing network controller: Error creating default "bridge" network: failed to allocate gateway (192.168.17.0): Address already in use 

This errors occurs no matter what bridge IP I choose, after a reboot, anytime at all. I tried deleting the local-kv.db, but this was of no use. I tried deleting the bridge with brctl delbr docker0, but this also did not help.

Since we have assets on the 172.17 network, I can't reach them after Docker starts up, and so therefore I can't use Docker.

**Comment by wenchma** [comment]
@borzwazie  you can try `docker daemon -D --bip 192.168.17.1/24` , the daemon will start successfully.
you should specify a valid ip address for the bridge ip.  
My starting daemon result: (it works)
```
$ ifconfig docker0
docker0   Link encap:Ethernet  HWaddr 02:42:58:7a:47:05  
          inet addr:192.168.17.1  Bcast:0.0.0.0  Mask:255.255.255.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

$ docker network inspect bridge
[
    {
        "Name": "bridge",
        "Id": "866cc03bd93d4faeb827905dcd0bf06787ef9c021a299da9f1df7c2892109260",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "192.168.17.1/24",
                    "Gateway": "192.168.17.1"
                }
            ]
        },
        "Internal": false,
        "Containers": {},
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1500"
        },
        "Labels": {}
    }
]

**Comment by borzwazie** [comment]
Thank you!

**Comment by davidchappelle** [comment]
Why is specifying `-D` the accepted workaround? I am also running into the same issue but relying on `-D` seems weak.

**Comment by vide** [comment]
@davidchappelle No, the problem is that you have to specify an *IP*/netmask address, not a subent/netmask address. Basically, it cannot end with `.0`

**Comment by yorickdewid** [comment]
@vide No one has mentioned that yet, thank you that indeed solved the problem.

**Comment by DerFlatulator** [comment]
Thanks so much, @vide. I would never have noticed that.

**Comment by ouroboros8** [comment]
Good grief, thanks @vide I thought I was going insane.

**Comment by nychollas88** [comment]
It is very easy to be confused after reading the Docker documentation about setting up the _docker0_ interface. It would be an idea to make it more obvious that the IP address you assign to _bip_ property should not be a subnet address. Glad I was able to solve!

**Comment by FBIanderson** [comment]
> @borzwazie you can try `docker daemon -D --bip 192.168.17.1/24` , the daemon will start successfully. you should specify a valid ip address for the bridge ip. My starting daemon result: (it works)
> 
> ```
> $ ifconfig docker0
> docker0   Link encap:Ethernet  HWaddr 02:42:58:7a:47:05  
>           inet addr:192.168.17.1  Bcast:0.0.0.0  Mask:255.255.255.0
>           UP BROADCAST MULTICAST  MTU:1500  Metric:1
>           RX packets:0 errors:0 dropped:0 overruns:0 frame:0
>           TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:0 
>           RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
> 
> $ docker network inspect bridge
> [
>     {
>         "Name": "bridge",
>         "Id": "866cc03bd93d4faeb827905dcd0bf06787ef9c021a299da9f1df7c2892109260",
>         "Scope": "local",
>         "Driver": "bridge",
>         "EnableIPv6": false,
>         "IPAM": {
>             "Driver": "default",
>             "Options": null,
>             "Config": [
>                 {
>                     "Subnet": "192.168.17.1/24",
>                     "Gateway": "192.168.17.1"
>                 }
>             ]
>         },
>         "Internal": false,
>         "Containers": {},
>         "Options": {
>             "com.docker.network.bridge.default_bridge": "true",
>             "com.docker.network.bridge.enable_icc": "true",
>             "com.docker.network.bridge.enable_ip_masquerade": "true",
>             "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
>             "com.docker.network.bridge.name": "docker0",
>             "com.docker.network.driver.mtu": "1500"
>         },
>         "Labels": {}
>     }
> ]
> ```

Can I user an ipv6  to the bip?
