### ISSUE TITLE
file

### ISSUE THREAD

**Issue by spoulson** [docker/docker#22646]
**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by spoulson** [comment]
Sorry, I have no idea how this got submitted!  My apologies.

**Comment by thaJeztah** [comment]
Heh, no worries; I suspect you tried "search" and the "create issue" is easy to click :smile:
