### ISSUE TITLE
Unstoppable Zombie Processes

### ISSUE THREAD

**Issue by onursoyer** [docker/docker#22648]
I'm currently facing with some unstoppable zombie processes I believe it is related to #19166 and #18180. 
docker stop/kill does not solve the problem at all. All I get bunch of zombies and the only solution is to restart the computer.

Is there any solution for this?

```
Docker version 1.11.1, build 5604cbe
```

```
Containers: 12
 Running: 11
 Paused: 0
 Stopped: 1
Images: 34
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 82
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 62.81 GiB
Name: onurhp
ID: FVMI:2IVL:PISC:BRI7:SCYX:FU3Z:HTDF:CITP:KZZU:PD7E:TLYQ:4GSM
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Testing on my own workstation.

```
$ uname -a
Linux onurhp 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Steps to reproduce the issue:**
Here is the how I reproduce the error. I have a script to perform the following steps in an infinite loop to reproduce the issue. It may take some time to reproduce the issue. It hangs at 4th step.

1. Start a new containter. -> docker run ...
2. Execute a script that runs some java apps. -> docker exec {container_name} /manage.sh start
3. Stop java apps. -> docker exec {container_name} /manage.sh stop
4. Stop containers. -> docker stop {container_name}

**manage.sh** is a script of mine to execute some Java and other apps.

## Additional Info
This is how it looks like inside of the container. There is a one Java **zombie process** eating all cpu resources.
```
top - 01:55:31 up  1:59,  0 users,  load average: 7.76, 8.05, 10.20
Tasks:  15 total,   1 running,   5 sleeping,   0 stopped,   9 zombie
%Cpu(s): 27.1 us, 21.1 sy,  0.0 ni, 49.9 id,  0.0 wa,  0.0 hi,  2.0 si,  0.0 st
KiB Mem:  65864412 total,  8797604 used, 57066808 free,   151568 buffers
KiB Swap:        0 total,        0 used,        0 free.  3669272 cached Mem

   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
   190 root      20   0       0      0      0 Z  99.8  0.0  19:42.72 java
    55 root      20   0 6266960 941896  16664 S   2.0  1.4   0:45.41 java
     1 root      20   0   18168   3088   2792 S   0.0  0.0   0:00.01 bash
    23 root      20   0 3860008  91020  16672 S   0.0  0.1   0:01.25 java
   147 root      20   0       0      0      0 Z   0.0  0.0   0:11.30 GoPacketProduce
   148 root      20   0       0      0      0 Z   0.0  0.0   0:00.00 grep
   149 root      20   0       0      0      0 Z   0.0  0.0   0:00.00 cut
   150 root      20   0       0      0      0 Z   0.0  0.0   0:00.00 manage.sh
   160 root      20   0       0      0      0 Z   0.0  0.0   0:03.37 packetFilter
   161 root      20   0       0      0      0 Z   0.0  0.0   0:00.00 grep
   162 root      20   0       0      0      0 Z   0.0  0.0   0:00.00 cut
   163 root      20   0       0      0      0 Z   0.0  0.0   0:00.00 manage.sh
   174 root      20   0   18060   3048   2704 S   0.0  0.0   0:00.00 manage.sh
   242 root      20   0   18180   3272   2784 S   0.0  0.0   0:00.00 bash
   261 root      20   0   19904   2432   2040 R   0.0  0.0   0:00.59 top
```

```
$ ps faux
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root        242  0.0  0.0  18180  3272 ?        Ss   01:47   0:00 bash
root        262  0.0  0.0  15568  2132 ?        R+   02:07   0:00  \_ ps faux
root        174  0.0  0.0  18060  3048 ?        Ss   01:35   0:00 /bin/bash /pub/manage.sh stop
root        190 98.1  0.0      0     0 ?        Zl   01:35  31:41  \_ [java] <defunct>
root        163  0.0  0.0      0     0 ?        Z    01:34   0:00 [manage.sh] <defunct>
root        162  0.0  0.0      0     0 ?        Z    01:34   0:00 [cut] <defunct>
root        161  0.0  0.0      0     0 ?        Z    01:34   0:00 [grep] <defunct>
root        160  0.1  0.0      0     0 ?        Z    01:34   0:03 [packetFilter] <defunct>
root        150  0.0  0.0      0     0 ?        Z    01:34   0:00 [manage.sh] <defunct>
root        149  0.0  0.0      0     0 ?        Z    01:34   0:00 [cut] <defunct>
root        148  0.0  0.0      0     0 ?        Z    01:34   0:00 [grep] <defunct>
root        147  0.5  0.0      0     0 ?        Z    01:34   0:11 [GoPacketProduce] <defunct>
root         55  2.7  1.4 6266960 942352 ?      Sl   01:34   0:55 /usr/lib/jvm/java-8-oracle/bin/java -Xmx1G -Xms1G -ser
root         23  0.0  0.1 3860008 93860 ?       Sl   01:34   0:01 /usr/lib/jvm/java-8-oracle/bin/java -Xmx512M -Xms512M
root          1  0.0  0.0  18168  3088 ?        Ss+  01:34   0:00 bash
```

**docker.log**
```
time="2016-05-11T11:20:15.113593167+09:00" level=info msg="Container 94117ed0eac22f09f6b27575ba8aa10f5dce629a8b43e448bbd8504ef3cf201f failed to exit within 10 seconds of signal 15 - using the force"
time="2016-05-11T11:20:25.114184925+09:00" level=info msg="Container 94117ed0eac2 failed to exit within 10 seconds of kill - trying direct SIGKILL"
```

When I try to enter the container, get the following error.
```
docker exec -it stream-04 bash
rpc error: code = 2 desc = "oci runtime error: exec failed: exit status 1"
```

**Comment by thaJeztah** [comment]
Are you seeing the same issue if you switch to a different storage driver? I see you're running kernel 4.2, so overlay should be an option. 

The easiest way is to use a daemon configuration file; https://docs.docker.com/engine/reference/commandline/daemon/#daemon-configuration-file

Create a `/etc/docker/daemon.json` file, with this content;

```JSON
{"storage-driver":"overlay"}
```

And restart docker. Note that this will create an additional storage location inside /var/lib/docker, so you won't see your current images and containers after restarting. You can switch back to "aufs" by editing that file, setting it to use "aufs"

**Comment by onursoyer** [comment]
@thaJeztah Switching to OverlayFS solved my problem. Thank you for your help.

**Comment by thaJeztah** [comment]
Alright, that at least solves the direct issue.

Actually, it looks like this may indeed be the same issue as https://github.com/docker/docker/issues/18180#issuecomment-187583209. You're using kernel `4.2.0-27-generic`, and this issue should be resolved in kernel 4.2.0-30.35 and above. So if you want to use aufs, upgrading your kernel is probably the best resolution.

Let me close this issue

**Comment by daikaixian** [comment]
@thaJeztah  I followed your comment 'Create a /etc/docker/daemon.json file'  and restart docker .
then i can't see my docker images and containers.
so i try to change it to 'aufs' or just remove the file ,however the docker service can't start up.

**Comment by thaJeztah** [comment]
@daikaixian if you're switching to another storage driver (switching from aufs to overlay in your case), you're also switching to a different location to store data (e.g. `/var/lib/docker/overlay` instead of `/var/lib/docker/aufs`), so it's expected that you don't see any of your existing images or containers.

Without logs, I can't tell why the daemon refuses to start when you switch back (did it start successfully before switching?)

**Comment by daikaixian** [comment]
@thaJeztah  
the docker service successfully actually,but it tell me it failed in console. maybe it was another little bug.just ignore it.

Whatever,thx.
