### ISSUE TITLE
Embedded DNS and Nginx custom resolver

### ISSUE THREAD

**Issue by akashihi** [docker/docker#22652]
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:11:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:11:07 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 15
 Running: 0
 Paused: 0
 Stopped: 15
Images: 76
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 184
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 986.9 MiB
Name: docker
ID: 3I2J:CCBP:EJR3:FMU2:HXE5:HOMK:VUR7:6GEH:H62L:COKH:UZRZ:DKRS
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Debian GNI/Linux stable

**Steps to reproduce the issue:**
1. Install nginx and Lua scripting
2. Use redis lua connector in nginx script like: 

    local redis, err = rc:connect{
        url = "sentinel://filestream:a/0",
          sentinels = {
            { host = "sentinel", port = "26379" },
        }
    }

Where sentinel is, obviously, name of container with sentinel.

3. When you access that script, error will arise "no resolver defined to resolve sentinel".

The problem is that nginx uses it's own DNS resolver, which needs to be configured directly in the nginx config with "resolver i.p.add.ress" options. But what ip address should i use to access embedded dns server?

**Comment by mavenugo** [comment]
@akashihi it isn't clear from your description on what exactly is the issue. Are you trying to use the embedded dns server from within the nginx container ?
If you are trying to access the embedded DNS server from within the container, you can use `127.0.0.11`.

**Comment by akashihi** [comment]
Yes, i have nginx running in docker container and nginx runs embedded lua script, that uses embedded DNS to resolve other container's ip. And it doesn't works :(

Is 127.0.0.11 a fixed address that will not change?

**Comment by sanimej** [comment]
@akashihi For the container 127.0.0.11 will be the IP of the resolver and it will not change. I am assuming you are using user defined networks (docker network create ...). embedded DNS server is not used by containers in the default bridge network.

**Comment by akashihi** [comment]
Yes, i'm using with user defined networks. Thank, i'll try it and in case it doesn't work will reopen the issue :)
