### ISSUE TITLE
Docker Security Scanning safeguards the container content lifecycle(binary level scanning )

### ISSUE THREAD

**Issue by JackXuF** [docker/docker#22654]
As your public cloud customers，I want to know the binary-level analysis of every layer,and match the underlying signatures of each binary to known components and cross reference that with a database of known vulnerabilities.  what is the "a database of known vulnerabilities"? I know the CVE have no SHA of the package.

**Comment by thaJeztah** [comment]
Can you send your question to support@docker.com? Docker Security Scanning is managed by a different team, and unfortunately, we can't answer that in this repository
