### ISSUE TITLE
docker daemon throws bad listen address format error

### ISSUE THREAD

**Issue by mkumatag** [docker/docker#22670]
**Output of `docker version`:**

```
[root@jupiter-vm1181 docker]# ./docker-1.11.0-dev version
Client:
 Version:      1.11.0-dev
 API version:  1.24
 Go version:   go1.5.4
 Git commit:   9e4b5e0
 Built:        Thu Apr 14 20:09:31 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
[root@jupiter-vm1181 docker]#
```

**Output of `docker info`:**

```
[root@jupiter-vm1181 docker]# ./docker-1.11.0-dev info
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
[root@jupiter-vm1181 docker]# 

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Download the binaries from docker master binaries like below:
wget https://master.dockerproject.org/linux/amd64/docker-1.11.0-dev
wget https://master.dockerproject.org/linux/amd64/docker-containerd
wget https://master.dockerproject.org/linux/amd64/docker-runc
wget https://master.dockerproject.org/linux/amd64/docker-containerd-shim
2. Start the daemon:
./docker-1.11.0-dev daemon -D

**Describe the results you received:**
```
[root@jupiter-vm1181 docker]# ./docker-1.11.0-dev daemon -D
DEBU[0000] docker group found. gid: 993                 
DEBU[0000] Listener created for HTTP on unix (/var/run/docker.sock) 
INFO[0000] New containerd process, pid: 20386
          
DEBU[0000] containerd connection state change: TRANSIENT_FAILURE 
WARN[0000] containerd: low RLIMIT_NOFILE changing to max  current=1024 max=4096
DEBU[0000] containerd: read past events                  count=4
DEBU[0000] containerd: supervisor running                cpus=2 memory=3784 runtime=docker-runc runtimeArgs=[] stateDir=/run/containerd
FATA[0000] bad listen address format /var/run/docker/libcontainerd/docker-containerd.sock, expected proto://address 
DEBU[0003] containerd connection state change: TRANSIENT_FAILURE 
DEBU[0006] containerd connection state change: TRANSIENT_FAILURE 
INFO[0006] New containerd process, pid: 20393
          
WARN[0000] containerd: low RLIMIT_NOFILE changing to max  current=1024 max=4096
DEBU[0000] containerd: read past events                  count=0
DEBU[0000] containerd: supervisor running                cpus=2 memory=3784 runtime=docker-runc runtimeArgs=[] stateDir=/run/containerd
FATA[0000] bad listen address format /var/run/docker/libcontainerd/docker-containerd.sock, expected proto://address 
^C[root@jupiter-vm1181 docker]#
```
**Describe the results you expected:**
docker daemoin should be started instead throwing error message starting the containerd and runs infinite.

**Additional information you deem important (e.g. issue happens only occasionally):**
This is happening all the time in my environment.

**Comment by cpuguy83** [comment]
This looks like a bug in an old dev version (or a change in how containerd expects the format at least... I know I saw a PR in this regard on containerd).

Closing as this is a non-issue.

**Comment by mkumatag** [comment]
Can you please point me to the PR you are talking about?

**Comment by cpuguy83** [comment]
I can't find it, but probably related to docker/containerd#178

**Comment by duglin** [comment]
Latest containerd checks the listener string/URL and those this error for me too.
The engine isn't putting "unix://" at the start of the string/URL.  
Seen this myself, just haven't had time to submit a PR(s).

**Comment by duglin** [comment]
I should point out that if you use the git commit level mentioned in the Dockefile for containerd then it works ok.
