### ISSUE TITLE
Why I can't set DNS to 8.8.8.8?

### ISSUE THREAD

**Issue by Rohlik** [docker/docker#22686]
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64
```

**Steps to reproduce the issue:**
1. docker run -ti --rm --dns=[8.8.8.8] debian

**Describe the results you received:**
invalid value "[8.8.8.8]" for flag --dns: [8.8.8.8] is not an ip address

**Describe the results you expected:**
I expect container with extra DNS 8.8.8.8

**Comment by coolljt0725** [comment]
@Rohlik  Hi, the correct format is `--dns=8.8.8.8`, not `--dns=[8.8.8.8]`, if you want add more than one dns, the format like `--dns=8.8.8.8 --dns=4.4.4.4`

**Comment by Rohlik** [comment]
Thx, my bad.
--help for docker run command show `--dns=[]`so I think `--dns=[8.8.8.8]` is right syntax.

**Comment by coolljt0725** [comment]
@Rohlik  `[]` means this flag can specified multiple times . I going to close this since it's not an issue
