### ISSUE TITLE
docker-compose "rolling deploy" (restart containers one after another instead of all at once)

### ISSUE THREAD

**Issue by duraiz** [docker/docker#22696]
I am running a redis cluster on 200 containers which are placed on different nodes using docker-compose and docker and docker-swarm.

Now if i want to restart service on some containers instead of restarting all 200 containers at once how can i do it ? or how can i stop the service on some containers instead on stoping whole service?

**Comment by cpuguy83** [comment]
This really belongs in github.com/docker/compose and maybe as a problem statement rather than a general question?
