### ISSUE TITLE
docker network create problem   

### ISSUE THREAD

**Issue by 332054781** [docker/docker#22693]
docker version 1.9.1 
linux ubuntu 14.04     3.19.0-59-generic

root@docker1:~# docker network create --driver calico --ipam-driver calico net1
d90f4408f554285aa31820c5cb36333df07ce8a1ac9c37d66cdcf398f4af4179

I configre  docker network seemingly is ok but when  show network is not ok ,
root@docker1:~# docker network ls
NETWORK ID          NAME                DRIVER
4c882880b656        bridge              bridge
4adc3d57f3a9        none                null
b9cf3db56a5e        host                host

root@docker1:~# tail /var/log/upstart/docker.log
INFO[1834] POST /v1.21/networks/create
WARN[1834] datastore for scope global not initialized. kv object docker/network/v1.0/network/d90f4408f554285aa31820c5cb36333df07ce8a1ac9c37d66cdcf398f4af4179/ is not added to the store
WARN[1834] datastore for scope global not initialized. kv object docker/network/v1.0/endpoint_count/d90f4408f554285aa31820c5cb36333df07ce8a1ac9c37d66cdcf398f4af4179/ is not added to the store

**Output of `docker version`:**
root@docker1:~# docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```
(paste your output here)
```

**Output of `docker info`:**
root@docker1:~# docker info
Containers: 2
Images: 17
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 40
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-59-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 2
Total Memory: 989.4 MiB
Name: docker1
ID: 4E3H:SGDI:XPW2:ERCL:HEJR:KGWU:CLBJ:UGI6:ARDS:ZF3X:KDIL:IVR3
WARNING: No swap limit support

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment]
ping @aboch

**Comment by dminca** [comment]
Problem still persists in `Docker version 1.12.0, build 8eab29e, experimental`

```shell
sh$ docker network create -d overlay mynetwork
Error response from daemon: datastore for scope "global" is not initialized
```

**Comment by thaJeztah** [comment]
@dminca are you using an external k/v store?

**Comment by dminca** [comment]
@thaJeztah nope, this is my `docker network ls`
```shell
➜  ~  docker network ls 
NETWORK ID          NAME                DRIVER              SCOPE
0e16dffaef94        bridge              bridge              local               
1f2085608e53        host                host                local               
e5e3efacfc84        none                null                local               
```

**Comment by thaJeztah** [comment]
@dminca in that case, it's expected; for overlay networking you need to either setup an external k/v store or (if you want the new services feature in 1.12) use swarm mode; but swarm scopes overlay networks cannot be used for "docker run", only for services

**Comment by thaJeztah** [comment]
You can read here about overlay networking with an external k/v store; https://docs.docker.com/v1.11/engine/userguide/networking/get-started-overlay/

And about swarm mode here;
https://docs.docker.com/engine/swarm/

**Comment by dminca** [comment]
Thank you very much @thaJeztah :+1:

**Comment by TheWall89** [comment]
Hello. Please forgive me if it is inappropriate to re-open the discussion.

I and another user are experiencing the same problem. See this [forum thread](https://forums.docker.com/t/docker-1-12-with-swarm-1-2-5-consul-issue/21017).
We just followed the ["Build a Swarm cluster for production"](https://docs.docker.com/swarm/install-manual/) guide where consul is used as a k/v store.

**Comment by pcgeek86** [comment]
@thaJeztah Any chance of improving the user experience here? I just ran into this same issue, and wasn't really sure where to turn, except Google. Perhaps guiding the user to understanding the scenario would be an improvement, versus simply throwing the error message without any contextual information.

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by pootow** [comment]
+1 same issue here, and no way to go. 💔

**Comment by fredkan** [comment]
same issue meet

**Comment by pcgeek86** [comment]
@thaJeztah Any thoughts on this user experience that you could contribute? Seems that quite a few people are encountering this scenario.

**Comment by codercotton** [comment]
This hurts :(

**Comment by bhaskarcloudyuga** [comment]
I am having the same issue ...bumped...heck..anyone care to explain..

docker-lf@docker-demo-lf:~$ docker network create -d overlay lf-overlay-net
Error response from daemon: datastore for scope "global" is not initialized

**Comment by mavenugo** [comment]
@pcgeek86 @codercotton @bhaskarcloudyuga The issue was originally filed for 1.9.1 . To begin with, it will help if you can share the docker version that you are trying. The error message `Error response from daemon: datastore for scope "global" is not initialized` indicates that external kv-store is not configured or not reachable.

Having said that, docker 1.12 introduced swarm-mode and with that, overlay network doesnt require an external kv-store any more. So, if you are trying 1.12 and you are encountering this error, that means you might have missed `docker swarm init` command to initialize the swarm-mode.

**Comment by herbrandson** [comment]
I am having a similar issue. I run the following script to create a swarm

```
docker-machine create -d virtualbox local
eval "$(docker-machine env local)"
TOKEN=$(docker run swarm create)

docker-machine create \
    -d virtualbox \
    --swarm \
    --swarm-master \
    --swarm-discovery token://$TOKEN \
    swarm-manager

docker-machine create \
    -d virtualbox \
    --swarm \
    --swarm-discovery token://$TOKEN \
    swarm-node-01

eval "$(docker-machine env --swarm swarm-manager)"

docker network create \
	--driver overlay \
	multi-host-network
```

The result is the following error

`Error response from daemon: Error response from daemon: datastore for scope "global" is not initialized`

Running `docker-machine ls` gives the following

```
NAME            ACTIVE      DRIVER       STATE     URL                         SWARM                    DOCKER    ERRORS
local           -           virtualbox   Running   tcp://192.168.99.100:2376                            v1.12.1   
swarm-manager   * (swarm)   virtualbox   Running   tcp://192.168.99.101:2376   swarm-manager (master)   v1.12.1   
swarm-node-01   -           virtualbox   Running   tcp://192.168.99.102:2376   swarm-manager            v1.12.1 
```

Running `docker -v` gives the following

```
Docker version 1.12.1, build 6f9534c
```

**Comment by lawrlee** [comment]
I too am having issues creating an overlay network. Instead of `docker-machine` I have followed the directions on https://docs.docker.com/swarm/install-manual/ for creating hosts in AWS (except only creating 1 manager node). I managed to successfully run `swarm manage` on the manager node and `swarm join` on the worker nodes, passing a functional consul backend to each of them.

From the manager node:
```
$ docker -H :4000 info
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 3
Server Version: swarm/1.2.5
Role: primary
Strategy: spread
Filters: health, port, containerslots, dependency, affinity, constraint
Nodes: 2
 biomed-swarm-node0: ****:2375
  └ ID: LM2A:YYM4:KNPE:66DS:2GGU:5VBT:5H25:7MSQ:FCKH:Q2NY:FKP6:GP2G
  └ Status: Healthy
  └ Containers: 2 (1 Running, 0 Paused, 1 Stopped)
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 7.67 GiB
  └ Labels: kernelversion=3.13.0-92-generic, operatingsystem=Ubuntu 14.04.5 LTS, storagedriver=aufs
  └ UpdatedAt: 2016-09-24T02:08:34Z
  └ ServerVersion: 1.12.1
 biomed-swarm-node1: ****:2375
  └ ID: HRAG:I5HI:2U76:HIXO:YPZG:OJ6S:YNIW:Q2Y6:SXBZ:RIGX:SFRE:TUAW
  └ Status: Healthy
  └ Containers: 1 (1 Running, 0 Paused, 0 Stopped)
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 7.67 GiB
  └ Labels: kernelversion=3.13.0-92-generic, operatingsystem=Ubuntu 14.04.5 LTS, storagedriver=aufs
  └ UpdatedAt: 2016-09-24T02:08:27Z
  └ ServerVersion: 1.12.1
Plugins:
 Volume: 
 Network: 
Swarm: 
 NodeID: 
 Is Manager: false
 Node Address: 
Security Options:
Kernel Version: 3.13.0-92-generic
Operating System: linux
Architecture: amd64
CPUs: 4
Total Memory: 15.34 GiB
Name: 5a6b2000ebc2
Docker Root Dir: 
Debug Mode (client): false
Debug Mode (server): false
WARNING: No kernel memory limit support
```
`docker -H :4000 run hello-world` works fine and I can tell that the `swarm` containers are communicating with the Consul server
```
$ curl http://<consul_ip>:8500/v1/kv/?recurse
[{"LockIndex":4,"Key":"docker/swarm/leader","Flags":3304740253564472344,"Value":"MTAuMTAuNC44OjQwMDA=","Session":"81369ec3-d286-ad35-2951-4755b51e05f1","CreateIndex":16587273,"ModifyIndex":16612134},{"LockIndex":0,"Key":"docker/swarm/nodes","Flags":3304740253564472344,"Value":null,"CreateIndex":16587271,"ModifyIndex":16587271},{"LockIndex":0,"Key":"docker/swarm/nodes/****:2375","Flags":3304740253564472344,"Value":"MTAuMTAuNC43OjIzNzU=","Session":"ef33494d-7514-7c3f-55d8-6dbdafdbf0a6","CreateIndex":16609487,"ModifyIndex":16613217},{"LockIndex":0,"Key":"docker/swarm/nodes/****:2375","Flags":3304740253564472344,"Value":"MTAuMTAuNC45OjIzNzU=","Session":"cd453857-69b4-5414-b284-ef3eb81da515","CreateIndex":16609483,"ModifyIndex":16613216}]
```
However, when I try to create the network:
```
$ docker -H :4000 network create -d overlay swarm_network
Error response from daemon: Error response from daemon: datastore for scope "global" is not initialized
```
All nodes are running the same docker version with `-H 0.0.0.02375` passed to dockerd.
```$ docker -v
Docker version 1.12.1, build 23cf638```

**Comment by herbrandson** [comment]
Based on the comment of @mavenugo above, I've decided to open a new ticket for this.

https://github.com/docker/docker/issues/27098

**Comment by mavenugo** [comment]
@herbrandson @lawrlee As explained above, if you use swarm-mode, then you dont need external KV-Store. But if you are not using the new swarm-mode (`docker swarm init`), then Pls check if you are using `--cluster-store` and `--cluster-advertise` daemon configurations. More information : https://docs.docker.com/engine/userguide/networking/get-started-overlay/#/create-a-swarm-cluster

**Comment by resouer** [comment]
Met this for several times. 

Besides some people can not distinguish `swarm mode` to `swarm`, another possible reason is: you should do `docker swarm init` first to make the build-in K-V store working, or, check the log to see why your `manager` is not working.
