### ISSUE TITLE
daemon.json documentation sample is not valid on Windows

### ISSUE THREAD

**Issue by neilpeterson** [docker/docker#22709]
The list of allowed configuration options in [this document](https://docs.docker.com/engine/reference/commandline/daemon/#daemon-configuration-file) is not applicable to Windows. Several of the options do not work on Windows. I think this requires minor clarification, perhaps a sample that is applicable to Windows:

When used as is, the following is returned:

```none
PS C:\> dockerd
time="2016-05-12T15:40:59-07:00" level=fatal msg="unable to configure the Docker daemon with file C:\\ProgramData\\docker\\config\\daemon.json: the following directives don't match any configuration option: iptables, bip, icc, api-cors-headers, exec-root, default-gateway-v6, ipv6, cgroup-parent, ip-mask, ip, userland-proxy, default-gateway, ip-forward, selinux-enabled, userns-remap, fixed-cidr-v6\n"
```

Here is a working sample:

```json
{
    "authorization-plugins": [],
    "dns": [],
    "dns-opts": [],
    "dns-search": [],
    "exec-opts": [],
    "storage-driver": "",
    "storage-opts": [],
    "labels": [],
    "log-driver": "", 
    "mtu": 0,
    "pidfile": "",
    "graph": "",
    "cluster-store": "",
    "cluster-advertise": "",
    "debug": true,
    "hosts": ["tcp://0.0.0.0:2376", "npipe://"],
    "log-level": "",
    "tlsverify": true,
    "tlscacert": "C:\\ProgramData\\docker\\certs.d\\ca.pem",
    "tlscert": "C:\\ProgramData\\docker\\certs.d\\server-cert.pem",
    "tlskey": "C:\\ProgramData\\docker\\certs.d\\server-key.pem",
    "group": "",
    "default-ulimits": {},
    "bridge": "",
    "fixed-cidr": "",
    "raw-logs": false,
    "registry-mirrors": [],
    "insecure-registries": [],
    "disable-legacy-registry": false
}

```
If this makes sense, and is in line with the docs scope / purpose, I am happy write up and propose the changes.

neilp

**Comment by thaJeztah** [comment]
I think it would make sense to have an example for Windows as well (is there a way to `SIGHUP` the daemon?).

There's still much work to do in that area, because the same applies to the flags (we don't mention which ones are supported on Windows, and which not)

**Comment by neilpeterson** [comment]
Thanks Sebastiaan - I can help with the Windows specific documentation. For future clarification, should I open an issue each time I find a place for doc contribution? Looking at the workflow [here](https://docs.docker.com/opensource/workflow/make-a-contribution/), this appears to be the case.

neilp

**Comment by justincormack** [comment]
You can just open a  pull request directly if you like, so long as you explain the problem you are trying to resolve, without opening an issue as well.

**Comment by thaJeztah** [comment]
@neilpeterson great!

Perhaps we should schedule a meeting someday (when I'm visiting SF) to discuss how we're going to document the Windows/Linux differences. Currently, the Windows daemon is still "beta", and follows a release schedule separate from the Linux releases, which complicates things w.r.t documentation. However, once Windows Server 2016 is release (I assume) the same release schedule will be used, and we should account for that in the documentation.

The tooling and "theme" we use for the documentation is a bit restricted in this area. Ideally we'd have something similar to the .Net docs, where (code) samples can be viewed in different languages;

<img width="884" alt="screen shot 2016-05-13 at 12 53 49" src="https://cloud.githubusercontent.com/assets/1804568/15245976/0a0ddcf6-190a-11e6-962a-589978770905.png">

I'm not sure if that's possible somehow (so just a thought)

ping @patrickqnguyen @SvenDowideit

**Comment by neilpeterson** [comment]
@thaJeztah - yep happy to talk. Also, totally get it, there is a bunch of info in the Docker docs, we will need to figure out logistics so as not to add cruft / sloppy patches.

I've spoken a bit with @moxiegirl and @friism around the need to weave in some Windows specific items. Adding both here for awareness and contribution.

As for the specific issue (daemon.json), it is likely that this file will be the recommended daemon configuration option on Windows. Ill propose a subtle change to the current doc to note that not all directives are applicable to Windows, and provide some Windows specific guidance.

**Comment by neilpeterson** [comment]
#dibs

**Comment by thaJeztah** [comment]
Sounds good, thanks for contributing!
