### ISSUE TITLE
rpc error: code = 2 desc = "oci runtime error: exec failed: exit status 1"

### ISSUE THREAD

**Issue by liamawhite** [docker/docker#22705]
The error seems pretty generic, but after reading through several other issues with a similar error I believe this is a different issue.

**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 239
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 256
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-36-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.38 GiB
Name: liam-ThinkPad-W550s
ID: RDZM:76O7:PLR4:AKIU:QK23:SQ3T:UDGB:SX4Z:DUDY:VYZV:SQDC:ZGBZ
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Username: liamwhite
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running locally.

**Steps to reproduce the issue:**
1.  `docker run -dP websphere-liberty` 
2.  `docker exec -it <container-id> bash`
(also occurs when 'exec-ing' into a ubuntu container)

**Describe the results you received:**
`rpc error: code = 2 desc = "oci runtime error: exec failed: exit status 1"`

**Describe the results you expected:**
A bash prompt for the specified container

**Additional information you deem important (e.g. issue happens only occasionally):**
I don't see the issue when pointed at a boot2docker machine. I am also seeing intermittent similar errors when running containers.

**Comment by justincormack** [comment]
Does this happen every time for you or only occasionally?

**Comment by liamawhite** [comment]
Every time.

**Comment by HackToday** [comment]
really interesting issue, could not reproduce on my local ubuntu env
```
ubuntu@testinstance:~/playone$  docker run -dP websphere-liberty 
Unable to find image 'websphere-liberty:latest' locally
latest: Pulling from library/websphere-liberty
6599cadaf950: Pull complete 
23eda618d451: Pull complete 
f0be3084efe9: Pull complete 
52de432f084b: Pull complete 
a3ed95caeb02: Pull complete 
314485e5ea1e: Pull complete 
2a67000643f0: Pull complete 
f70b703c2280: Pull complete 
735349754ced: Pull complete 
aab13790773d: Pull complete 
9c27285cbc8b: Pull complete 
f002ec43cc01: Pull complete 
da9d3deceabd: Pull complete 
b620b356f5d2: Pull complete 
73f8e90e21a4: Pull complete 
b2b7a70e61f4: Pull complete 
Digest: sha256:084f869e5f9a3b27781c6dbe639a9a1aba71188a04ba8e560867a4c497ae3c54
Status: Downloaded newer image for websphere-liberty:latest
e551fccfb3ef2a19dad756cd81d52d7c6c4eb56ecaaa586edd1ec063e12b1667
ubuntu@testinstance:~/playone$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                              NAMES
e551fccfb3ef        websphere-liberty   "/opt/ibm/docker/dock"   4 seconds ago       Up 3 seconds        0.0.0.0:32769->9080/tcp, 0.0.0.0:32768->9443/tcp   loving_shaw
598683516a88        ubuntu              "bash"                   2 hours ago         Up 2 hours                                                             evil_swirles
86df8eae97c5        busybox             "sh"                     2 hours ago         Up 2 hours                                                             determined_noether
ubuntu@testinstance:~/playone$ docker exec -it e551fccfb3ef  bash
root@e551fccfb3ef:/# 
```

@liamawhite  could you enable debug level logs and show the debug logs errors ?

**Comment by liamawhite** [comment]
@HackToday so run `docker -D exec -it <containter-id> bash` right?

```
time="2016-05-13T09:46:31.214834136+01:00" level=error msg="Error running exec in container: rpc error: code = 2 desc = \"oci runtime error: exec failed: exit status 1\"\n" 
time="2016-05-13T09:46:31.215028165+01:00" level=error msg="Handler for POST /v1.23/exec/fad4b82a94cf1345eb955b5da9b56047dd7f00ac29162105e60115c83bf12b2e/start returned error: rpc error: code = 2 desc = \"oci runtime error: exec failed: exit status 1\"" 
2016/05/13 09:46:31 http: response.WriteHeader on hijacked connection
2016/05/13 09:46:31 http: response.Write on hijacked connection
time="2016-05-13T09:46:31.215604815+01:00" level=error msg="Handler for POST /v1.23/exec/fad4b82a94cf1345eb955b5da9b56047dd7f00ac29162105e60115c83bf12b2e/resize returned error: rpc error: code = 2 desc = \"containerd: processs not found for container\""
```

**Comment by mlaventure** [comment]
@liamawhite could you replace `/usr/local/bin/docker-runc` with this script (after renaming it to something like `/usr/local/bin/docker-runc`):

```bash
#!/bin/bash

strace -f -o /tmp/docker-runc-$$.trace /usr/local/bin/docker-runc-orig
```

 and send us the generated trace?

Hopefully that'll let us know which syscall, if any, is failing.

**Comment by liamawhite** [comment]
@mlaventure so my docker-runc isn't located in /usr/local/bin/ it is in /usr/bin/. However, when I do the same to the one located in /usr/bin/ (and change the paths) then restart the docker service I can't run a container as I get the following error:

`rpc error: code = 2 desc = "shim error: docker-runc not installed on system"`

I did it first without restarting and there was no log generated so I assumed I was supposed to restart the service.

**Comment by justincormack** [comment]
@liamawhite did you make the script executable? It should be fine without restarting, as it is re-execed each time a new container is started.

**Comment by liamawhite** [comment]
@justincormack that solved that issue (probably should have checked and not assumed it had transferred the same permissions).

Now the error I get when running a container (not my original problem) is : `docker: Error response from daemon: rpc error: code = 2 desc = "containerd: container did not start before the specified timeout".`

And I get the following two trace files: 

[docker-runc-9570.trace](http://pastebin.com/raw/Pw8mcmQ8)

[docker-runc-10184.trace](http://pastebin.com/raw/QhvUauaa)

**Comment by mlaventure** [comment]
@liamawhite 

Sorry, I forgot this was likely to happen.

This occurs because the container takes much longer to start now.

You'll need to start `containerd` separately:

```
docker-containerd --start-timeout "1m" --metrics-interval 0
docker daemon --debug --containerd /run/containerd/containerd.sock
```

**Comment by liamawhite** [comment]
@mlaventure I'm now back to the `docker: Error response from daemon: rpc error: code = 2 desc = "shim error: runc not installed on system".`

Just to prove that my runc is executable - ` ls -al /usr/bin/ | grep docker`
```
-rwxr-xr-x  1 root root    34966352 Apr 27 00:31 docker
-rwxr-xr-x  1 root root    14679803 Apr 27 00:30 docker-containerd
-rwxr-xr-x  1 root root    11058797 Apr 27 00:30 docker-containerd-ctr
-rwxr-xr-x  1 root root     2626940 Apr 27 00:30 docker-containerd-shim
-rwxr-xr-x  1 root root          83 May 13 23:37 docker-runc
-rwxr-xr-x  1 root root     9317577 May 13 23:35 docker-runc-backup
-rwxr-xr-x  1 root root       18832 Jun 12  2014 wmdocker

```

**Comment by mlaventure** [comment]
@liamawhite sorry, I forgot to specify the runtime in my sample!

add `--runtime $(which docker-runc)` to `containerd` arguments.

**Comment by liamawhite** [comment]
@mlaventure I now get the following error `docker: Error response from daemon: rpc error: code = 2 desc = "shim error: NAME: not installed on system".`

Bit more information from the containerd process
```
ERRO[0022] containerd: start container                   error=shim error: NAME: not installed on system id=ade2aecb2add136c582287ecd5da1d14e3b2b2700d2553025a2c54ca6d85dd3a
ERRO[0022] containerd: deleting container                error=exec: "NAME:": executable file not found in $PATH
```

**Comment by mlaventure** [comment]
@liamawhite I think `$(which docker-runc)` didn't work on your system, just pass it the full path `/usr/bin/docker-runc`

**Comment by liamawhite** [comment]
I'm back to the timeout error. I even increased the timeout to 2m. Here are the logs:
```
INFO[0000] API listen on /var/run/docker.sock           
DEBU[0005] Calling POST /v1.23/containers/create        
DEBU[0005] form data: {"AttachStderr":false,"AttachStdin":false,"AttachStdout":false,"Cmd":null,"Domainname":"","Entrypoint":null,"Env":[],"HostConfig":{"AutoRemove":false,"Binds":null,"BlkioBps":0,"BlkioDeviceReadBps":null,"BlkioDeviceReadIOps":null,"BlkioDeviceWriteBps":null,"BlkioDeviceWriteIOps":null,"BlkioIOps":0,"BlkioWeight":0,"BlkioWeightDevice":null,"CapAdd":null,"CapDrop":null,"Cgroup":"","CgroupParent":"","ConsoleSize":[0,0],"ContainerIDFile":"","CpuCount":0,"CpuPercent":0,"CpuPeriod":0,"CpuQuota":0,"CpuShares":0,"CpusetCpus":"","CpusetMems":"","Devices":[],"DiskQuota":0,"Dns":[],"DnsOptions":[],"DnsSearch":[],"ExtraHosts":null,"GroupAdd":null,"IpcMode":"","Isolation":"","KernelMemory":0,"Links":null,"LogConfig":{"Config":{},"Type":""},"Memory":0,"MemoryReservation":0,"MemorySwap":0,"MemorySwappiness":-1,"NetworkMode":"default","OomKillDisable":false,"OomScoreAdj":0,"PidMode":"","PidsLimit":0,"PortBindings":{},"Privileged":false,"PublishAllPorts":true,"ReadonlyRootfs":false,"RestartPolicy":{"MaximumRetryCount":0,"Name":"no"},"SandboxSize":0,"SecurityOpt":null,"ShmSize":0,"StorageOpt":null,"UTSMode":"","Ulimits":null,"UsernsMode":"","VolumeDriver":"","VolumesFrom":null},"Hostname":"","Image":"websphere-liberty","Labels":{},"NetworkingConfig":{"EndpointsConfig":{}},"OnBuild":null,"OpenStdin":false,"StdinOnce":false,"Tty":false,"User":"","Volumes":{},"WorkingDir":""} 
DEBU[0005] container mounted via layerStore: /var/lib/docker/aufs/mnt/2d30e9619920499618859e7e409957f9d245c8a2a2d94b725dc43f37d7f6f083 
DEBU[0005] Calling POST /v1.23/containers/90de0b5636177e7f429bc24bc5765a0de4e3f158bd36c7724ae26a9f4369131d/start 
DEBU[0005] container mounted via layerStore: /var/lib/docker/aufs/mnt/2d30e9619920499618859e7e409957f9d245c8a2a2d94b725dc43f37d7f6f083 
DEBU[0005] Assigning addresses for endpoint jovial_engelbart's interface on network bridge 
DEBU[0005] RequestAddress(LocalDefault/172.17.0.0/16, <nil>, map[]) 
DEBU[0005] Assigning addresses for endpoint jovial_engelbart's interface on network bridge 
DEBU[0005] Programming external connectivity on endpoint jovial_engelbart (964dc01315edb96c74cf0f601b4e200d78d47e54d6d5c956bf565c1375b3ab27) 
DEBU[0005] /sbin/iptables, [--wait -t nat -A DOCKER -p tcp -d 0/0 --dport 32768 -j DNAT --to-destination 172.17.0.2:9443 ! -i docker0] 
DEBU[0005] /sbin/iptables, [--wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport 9443 -j ACCEPT] 
DEBU[0005] /sbin/iptables, [--wait -t nat -A POSTROUTING -p tcp -s 172.17.0.2 -d 172.17.0.2 --dport 9443 -j MASQUERADE] 
DEBU[0005] /sbin/iptables, [--wait -t nat -A DOCKER -p tcp -d 0/0 --dport 32769 -j DNAT --to-destination 172.17.0.2:9080 ! -i docker0] 
DEBU[0005] /sbin/iptables, [--wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport 9080 -j ACCEPT] 
DEBU[0005] /sbin/iptables, [--wait -t nat -A POSTROUTING -p tcp -s 172.17.0.2 -d 172.17.0.2 --dport 9080 -j MASQUERADE] 
DEBU[0005] sandbox set key processing took 39.588044ms for container 90de0b5636177e7f429bc24bc5765a0de4e3f158bd36c7724ae26a9f4369131d 
DEBU[0125] Revoking external connectivity on endpoint jovial_engelbart (964dc01315edb96c74cf0f601b4e200d78d47e54d6d5c956bf565c1375b3ab27) 
DEBU[0125] /sbin/iptables, [--wait -t nat -D DOCKER -p tcp -d 0/0 --dport 32768 -j DNAT --to-destination 172.17.0.2:9443 ! -i docker0] 
DEBU[0125] /sbin/iptables, [--wait -t filter -D DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport 9443 -j ACCEPT] 
DEBU[0125] /sbin/iptables, [--wait -t nat -D POSTROUTING -p tcp -s 172.17.0.2 -d 172.17.0.2 --dport 9443 -j MASQUERADE] 
DEBU[0125] /sbin/iptables, [--wait -t nat -D DOCKER -p tcp -d 0/0 --dport 32769 -j DNAT --to-destination 172.17.0.2:9080 ! -i docker0] 
DEBU[0125] /sbin/iptables, [--wait -t filter -D DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport 9080 -j ACCEPT] 
DEBU[0125] /sbin/iptables, [--wait -t nat -D POSTROUTING -p tcp -s 172.17.0.2 -d 172.17.0.2 --dport 9080 -j MASQUERADE] 
DEBU[0125] Releasing addresses for endpoint jovial_engelbart's interface on network bridge 
DEBU[0125] ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.2) 
ERRO[0125] Handler for POST /v1.23/containers/90de0b5636177e7f429bc24bc5765a0de4e3f158bd36c7724ae26a9f4369131d/start returned error: rpc error: code = 2 desc = "containerd: container did not start before the specified timeout" 


```

**Comment by mlaventure** [comment]
can you check if there's any runc/strace processes still alive and if so kill them and try again?

Sometimes strace get stuck in that configuration (haven't figured out why yet).

**Comment by liamawhite** [comment]
Done, still the same issue. I have to run the command in sudo which obviously creates a second docker-runc process but that's not a problem right?

**Comment by liamawhite** [comment]
FYI - If I rollback to Docker version 1.10.3, build 20f81dd then it works fine.

**Comment by mlaventure** [comment]
@liamawhite what do you mean you have to run the command in sudo? Which command are you referring to?

Docker is running as a privileged process, it doesn't need sudo to execute docker-runc.

**Comment by sboagibm** [comment]
I'm having this same problem with just a ubuntu:14.04 container, where I can not `docker exec -it <id> /bin/bash` to it.  But my Ubuntu kernel is 3.13.0-86-generic.  If I `sudo apt-get install docker-engine=1.11.0-0~trusty` I still get the bug.  If I `sudo apt-get install docker-engine=1.10.3-0~trusty` I do not get the bug, as per @liamawhite.

**Comment by liamawhite** [comment]
@mlaventure I had to run the containerd command in sudo.

@sboagibm are you an IBMer? If you are then this is probably an internal issue as there are three other people in my team with this issue.

**Comment by mlaventure** [comment]
@liamawhite oh, yes, the sudo for containerd shouldn't matter.

Also, could you please provide the strace for the instance where it timeout after 2 mins? Maybe it'll give some insight as to where it's getting stuck so long.

**Comment by liamawhite** [comment]
@mlaventure I've spoke to @sboagibm internally and this is a [re-occurrence](https://github.com/docker/docker/issues/15772#issuecomment-142627591) of an issue caused by Symantec Antivirus and appears to be internal to IBM. I'm happy to go ahead and close this issue.

**Comment by niclas-w** [comment]
Had this issue as well. Running docker 1.11.2 on Ubuntu 14.04. All seemed to work fine, except that I couldn't exec in to a running container. Disabled SAV autoprotect and rebooted and the problem is gone.

**Comment by liamawhite** [comment]
@niclas-w this was the solution that works for me as well. I assume it was the runtime separation introduced in 1.11 that gets flagged up by SAV; I think this problem is probably Symantec's responsibility to fix through an exception or other means.

**Comment by typekpb** [comment]
@niclas-w you're a magician! thanks!
@thaJeztah sounds like you're gonna get a bunch of similar ones on sav updates in IBM :)

anyway, sav+docker stuff seems to be getting better as originally the last time I tried docker didn't start at all with sav enabled, see #15772

**Comment by thaJeztah** [comment]
@niclas-w @estesp @duglin is there an internal IBM mailing list that could be used to inform people?

**Comment by liamawhite** [comment]
@thaJeztah there is a post in the internal Ubuntu/Debian forum about it

**Comment by duglin** [comment]
not only that but I believe the Symantec folks know about it as well

**Comment by thaJeztah** [comment]
Cool, thanks!

**Comment by ltjdym** [comment]
i entered this command and fixed it: /bin/bash
