### ISSUE TITLE
Suggested change to 'run' command help

### ISSUE THREAD

**Issue by gamesbook** [docker/docker#22721]
The current text:

> when that variable’s current value is passed through (i.e. `$MYVAR1` from the host is set to `$MYVAR1` in the container).

could be usefully be changed to:

> when that variable’s current value, set via `export`, is passed through (i.e. `$MYVAR1` from the host is set to `$MYVAR1` in the container, where `export MYVAR1="foo"` was used).

**Comment by thaJeztah** [comment]
Would you be interested in contributing, and opening a pull request? The Markdown file used to generate that page in the documentation can be found here;
https://github.com/docker/docker/blob/master/docs/reference/commandline/run.md

**Comment by mansinahar** [comment]
Hi @thaJeztah , I am a beginner in OSS contribution and would like to start with something small like this. Can I call dibs on this one?

**Comment by thaJeztah** [comment]
@mansinahar absolutely! You may be interested in our contributors guide, which explains the process https://docs.docker.com/opensource/workflow/make-a-contribution/

**Comment by gamesbook** [comment]
You snooze, you lose... :(

**Comment by mansinahar** [comment]
Thank you @thaJeztah and sorry @gamesbook!

**Comment by mansinahar** [comment]
#dibs

**Comment by thaJeztah** [comment]
@gamesbook haha, sorry! But.... there's lots of other issues that may still require documentation PR's https://github.com/docker/docker/labels/kind%2Fdocs :smile:

**Comment by mansinahar** [comment]
PR: https://github.com/docker/docker/pull/22768
