### ISSUE TITLE
Why named volume with User Namespaces uses nobody:nogroup instead of subuid 

### ISSUE THREAD

**Issue by beatscode** [docker/docker#22725]
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 2
Server Version: 1.11.1
Storage Driver: devicemapper
 Pool Name: docker-202:1-3665878658-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 185.7 MB
 Data Space Total: 107.4 GB
 Data Space Available: 107.2 GB
 Metadata Space Used: 839.7 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 3.10.0-327.13.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.26 GiB
Name: ip-172-31-42-255.ec2.internal
ID: 2BL2:FWHF:G5R7:DX64:FDIJ:5LS7:PIQG:QKDK:JIFI:QFLB:3DHM:GQL3
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS,Centos 7 (3.10.0-327.13.1.el7.x86_64)

**Steps to reproduce the issue:**
1. Turn on user namespaces
2. add docker daemon directive --userns-remap 
3. reboot
4. docker create -v /home/{remap user}:/dbdata --name dbstore busybox /bin/true
5. docker run -it --volumes-from dbstore ubuntu /bin/bash
6. ls -la /dbdata
7. touch /dbdata/test.log 

**Describe the results you received:**
Permission Denied
I get a list of files that have nobody:no group ownership

**Describe the results you expected:**
I expected to get root ownership or at least have read/write access to the same directories as the remap user.

**Additional information you deem important (e.g. issue happens only occasionally):**
When I remove the user namespace feature the files have 1001:1001 ownership.

**Comment by cpuguy83** [comment]
That's not a named volume, it's a host bind.
Docker does not touch the permissions/ownership on host binds.

**Comment by beatscode** [comment]
How do i share read/write access to host binded data or is this frowned upon?

**Comment by cpuguy83** [comment]
It would defeat the purpose of user namespaces.

It's not really possible unless you map the UID/GID to the same as the host ones.

**Comment by pavgup** [comment]
Is the suggestion by @cpuguy83 still the ideal best practice?

**Comment by cpuguy83** [comment]
Sadly yes.
I started work on supporting a mapping filesystem to make this stuff work transparently... hopefully I can pick it up again soon.
Probably it would require a custom kernel with Ubuntu's shiftfs or a fuse filesystem (which I wrote one for testing purposes).

**Comment by pavgup** [comment]
oh drat, that's okay; where could someone googling this problem potentially join you in helping to find a better alternative? :)

**Comment by cpuguy83** [comment]
https://github.com/moby/moby/pull/38795

**Comment by Nakilon** [comment]
I don't really understand why `chown -R dockremap:dockremap the_dir_i_mount` does not work. I see the same "nobody nogroup" thing but considering the container user is root it should try to do something and have success in that since I made dockremap own the directory I mount but nope, it fails.
