### ISSUE TITLE
Docker kill doesn't send SIGINT to process in container

### ISSUE THREAD

**Issue by cefn** [docker/docker#22723]
**Output of `docker version`:**

```
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Fri Feb 12 22:11:40 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 12
 Running: 1
 Paused: 0
 Stopped: 11
Images: 4
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 31
 Dirperm1 Supported: true
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.8-boot2docker
Operating System: Boot2Docker 1.11.1 (TCL 7.0); HEAD : 7954f54 - Wed Apr 27 16:36:45 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: default
ID: SS2X:2LA7:I7M5:SOWH:3MJZ:OJ25:MWAJ:4JKU:RQAO:MVLW:VZGS:UGEE
Debug mode (server): true
 File Descriptors: 15
 Goroutines: 38
 System Time: 2016-05-13T14:25:11.519760933Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: 
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

Macbook Air running Docker against Docker-Machine on latest Virtualbox from homebrew.

**Steps to reproduce the issue:**
1. Launch a container running bash as follows...
```docker run --rm -it -p 3000:3000 -p 1883:1883 -e DOCKERHOST=$(ifconfig(route -n get $(docker-machine ip default) | grep interface: | awk '{print $2}') | grep inet | awk '{print $2}') -v /Users/cefn/Documents/code/myapp:/opt/myapp myapphost bash```
2. Run the command line nodejs /opt/myapp/app.js from within bash to launch a node process.
3. Use the CTRL+C shortcut to send SIGINT and the application shuts down gracefully.

4. Run the same command, but pass the command line directly instead of launching bash, like....
```docker run --rm -it -p 3000:3000 -p 1883:1883 -e DOCKERHOST=$(ifconfig(route -n get $(docker-machine ip default) | grep interface: | awk '{print $2}') | grep inet | awk '{print $2}') -v /Users/cefn/Documents/code/myapp:/opt/myapp myapphost nodejs /opt/myapp/app.js```
5. Try to send CTRL+C, does nothing (perhaps no surprise because of layered TTYs)
6. Check container id with ```docker ps```
7. Try to use ```docker kill --signal=SIGINT [containerid]``` also does nothing (this was a surprise, since there's no reason the process can't send SIGINT in the same way bash does.

This then forces the use of a ```docker kill``` operation to shut down the nodejs server process (all other signals are ignored). 

~~After using docker kill it seems to be the case that the docker image or some other part of the docker-machine daemon container setup pipeline then gets corrupted and it's impossible to reliably run commands in the image again (e.g. bash launches, but ```pwd``` hangs). This issue survives a restart of the docker-machine daemon.~~

~~The only choice is then to run ```docker-machine rm -f default && docker-machine --debug create -d virtualbox default``` to wipe everything.~~

~~Can someone share how we can reliably send SIGINT via docker kill please, as this would help us work around apparent image-corruption bugs in docker-machine from using kill.~~

N.B. The above strikethrough lines came from not having the -i option selected, which meant that terminal commands were not being sent to the terminal. However the SIGINT issue remains.

**Comment by justincormack** [comment]
The signal is definitely sent, the application may be ignoring it though. The first case is because the shell does not forward signals to child processes. You may have to explicitly add a signal handler though if your program is running as pid 1, as signals are disabled by default in this case, eg something like 
```
process.on('SIGINT', function () {
  process.exit(1);
});
```

**Comment by cefn** [comment]
Indeed I have proven this is the case, but still puzzled that when invoked in ```bash``` CTRL+C shuts down the node process, but when invoked in a docker process SIGINT sent to it does nothing. Something must be different in the signal handling pathways between the two, and now I'm guessing it's to do with ```bash``` instead and potentially that the route to shutting down the process isn't SIGINT at all.

Test code proving the signals were getting to a node process as follows...

```javascript
function heartBeat(){
    console.log("Node process still running");
}

heartBeat();
setInterval(heartBeat, 5000);

["SIGUSR1", "SIGINT", "SIGTERM", "SIGPIPE", "SIGHUP", "SIGBREAK", "SIGWINCH",].map(function(sigName){
    process.on(sigName, function(){
        console.log("Received " + sigName);
    });
});
```

Adding an explicit handler for SIGINT is the next port of call, thanks for the example code.
