### ISSUE TITLE
[Docs] Docker images missing for content trust documentation

### ISSUE THREAD

**Issue by BenHall** [docker/docker#22730]
This document discusses two image tags that do not exist on the hub (https://hub.docker.com/r/docker/trusttest/tags/).

https://github.com/docker/docker/blob/861815a3252b88a118a91a164246401fa24fa549/docs/security/trust/content_trust.md

```
docker pull --disable-content-trust docker/trusttest:untrusted
Pulling repository docker.io/docker/trusttest
Tag untrusted not found in repository docker.io/docker/trusttest
```

```
docker pull docker/seaside
Using default tag: latest
Pulling repository docker.io/docker/seaside
Error: image docker/seaside not found
```

I'm guessing docker/trusttest:untrusted has become docker/trusttest:latest.  docker/seaside seems to have been removed.

**Comment by thaJeztah** [comment]
Oh, nice find

ping @docker/core-notary-maintainers PTAL

**Comment by cyli** [comment]
@thaJeztah I'm wondering if we should just change those repo names to non-`<username>/trusttest` and `<username/seaside>` etc., since someone following those instructions can't actually push to `docker/trusttest` and `docker/seaside` anyway?

**Comment by thaJeztah** [comment]
@cyli sounds like a good idea; wondering about the `docker pull` examples; would it be useful if people could actually pull a trusted/untrusted image?

**Comment by riyazdf** [comment]
@thaJeztah: great idea, we can even point to official images

**Comment by mansinahar** [comment]
@thaJeztah Hey, I am new with this but can't people already actually pull trusted/untrusted images?

**Comment by thaJeztah** [comment]
@mansinahar see the documentation on "content trust"; https://docs.docker.com/engine/security/trust/content_trust/

Note that 'content trust' is something different than "official" images (see the docs I like to above)

**Comment by thaJeztah** [comment]
@mansinahar my comment was merely to improve the docs and use some actual images that people could use to try.

**Comment by mansinahar** [comment]
@thaJeztah Oh okay. Thanks for the clarification. I would like to work on this one.

**Comment by mansinahar** [comment]
#dibs
