### ISSUE TITLE
DNS round-robin seems not working as containers are caching ip addresses 

### ISSUE THREAD

**Issue by lherrera** [docker/docker#22744]
**Output of `docker version`:**
```
client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   8b63c77
 Built:        Tue May 10 10:39:20 2016
 OS/Arch:      linux/amd64
```
**Output of `docker info`:**
```
Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 175
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 310
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.9-moby
Operating System: Alpine Linux v3.3
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.954 GiB
Name: moby
ID: YUAR:D5YG:XIDE:YXZS:HOT4:DVOX:ZIJV:FYSO:JYRU:2O2M:MYGE:T4AF
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 320
 Goroutines: 586
 System Time: 2016-05-14T23:41:53.559935481Z
 EventsListeners: 244
Registry: https://index.docker.io/v1/
```
**Additional environment details (AWS, VirtualBox, physical, etc.):**
OS X El Capitan (Version 10.11.1)
Docker for Mac Beta - Version 1.11.1-beta11 (build: 6974)

**Steps to reproduce the issue:**
1. git clone https://github.com/lherrera/lb/
2. docker-compose up -d
4. docker-compose scale server=5
6. docker-compose scale client=2
7. docker-compose logs | grep client_1
8. docker-compose logs | grep client_2

**Describe the results you received:**
The docker-compose.yml has two services: 
a) server, that runs a infinite loop 
b) client, that 1) obtains the DNS A records of the server name 2) pings the server by name

When scaling the server (after step 4), although the client could see the new A records, keeps using the same one. However, if I launch a new client (step 6), it uses all A addresses and DNS round-robin seems to work as expected.
``` 
$ docker-compose logs | grep client_1
....
client_1  | PING server (172.18.0.3)
client_1  | server has address 172.18.0.5
client_1  | server has address 172.18.0.6
client_1  | server has address 172.18.0.3
client_1  | server has address 172.18.0.4
client_1  | server has address 172.18.0.7
client_1  | PING server (172.18.0.3)
client_1  | server has address 172.18.0.5
client_1  | server has address 172.18.0.3
client_1  | server has address 172.18.0.4
client_1  | server has address 172.18.0.6
client_1  | server has address 172.18.0.7
...
$ docker-compose logs | grep client_2
...
client_2  | PING server (172.18.0.5)
client_2  | server has address 172.18.0.6
client_2  | server has address 172.18.0.3
client_2  | server has address 172.18.0.4
client_2  | server has address 172.18.0.5
client_2  | server has address 172.18.0.7
client_2  | PING server (172.18.0.3)
client_2  | server has address 172.18.0.3
client_2  | server has address 172.18.0.7
client_2  | server has address 172.18.0.5
client_2  | server has address 172.18.0.4
client_2  | server has address 172.18.0.6
...

$ docker-compose logs client | grep client_1 | grep PING | sort | uniq -c
1963 client_1  | PING server (172.18.0.3)

$ docker-compose logs client | grep client_2 | grep PING | sort | uniq -c
 117 client_2  | PING server (172.18.0.3)
 125 client_2  | PING server (172.18.0.4)
 103 client_2  | PING server (172.18.0.5)
 111 client_2  | PING server (172.18.0.6)
 120 client_2  | PING server (172.18.0.7)
....


**Describe the results you expected:**
I´d expected both clients to have a similar output after scaling the server. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by yongtang** [comment]
I am wondering if this is related to #22389?

**Comment by sanimej** [comment]
Yes; its similar to #22389 

@lherrera Docker DNS server returns all the IPs for a given service name in random order. But the order in which its presented to the client app depends on the resolver library/API being used at the client end. getaddrinfo() for example tries to order the entries based on RFC 3484.

**Comment by thaJeztah** [comment]
I'll close this issue;  please continue the discussion on https://github.com/docker/docker/issues/22389. Thanks for reporting though!

**Comment by lherrera** [comment]
Thank you @thaJeztah and @sanimej sanimej!. Actually, that´s exactly what´s happening...for both containers client_1 and client_2, Docker DNS server is returning all the IPs in random order....that works as expected and as documented  However, the same ping command uses just one in client_1 and all of them (in random order) on the second one....as if somehow the container cached the IP that Docker DNS provided the first time. Although the host command returns in both cases all the new IPs..., its ARP table contains just one IP/MAC and second all of them (not surprisingly).
