### ISSUE TITLE
Running a container from within a container (via mounting docker.sock) fails to preserve volume mount changes

### ISSUE THREAD

**Issue by jramapuram** [docker/docker#22752]
**Output of `docker version`:**

```
Client:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-25.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      78ee77d/1.9.1
 Built:
 OS/Arch:         linux/amd64

Server:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-25.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      78ee77d/1.9.1
 Built:
 OS/Arch:         linux/amd64
```

**Output of `docker info`:**

```
Containers: 80
Images: 453
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-253:1-293612214-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem:
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 32.07 GB
 Data Space Total: 107.4 GB
 Data Space Available: 48.45 GB
 Metadata Space Used: 35.35 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.112 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.1.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 4
Total Memory: 7.64 GiB
Name: databus-jramapuram
ID: 5SPZ:LWT5:XYC3:2C7N:VM3C:KZFF:WRN3:5B27:BNBO:PFHL:XCXS:TQPR
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
```bash
docker run -it -v mydir:/mydir -v /var/run/docker.sock:/var/run/docker.sock centos:7 bash
# do stuff to install docker
docker run -it -v /mydir:/mydir -v /var/run/docker.sock:/var/run/docker.sock centos:7 bash
touch /mydir/tmp
exit # exit container 1
exit # exit container 0
ls mydir # has no results here on original host
```

**Describe the results you received:**
No `tmp` in mydir

**Describe the results you expected:**
I would have expected `tmp` to exist inside mydir

**Additional information you deem important (e.g. issue happens only occasionally):**
This happens for containers run within containers using the docker.sock mounted from the original host.

**Comment by thaJeztah** [comment]
Your first container is started with a named volume, not a bind-mounted directory; a bind-mounted directory should always be an absolute path, if not, (and the volume doesn't start with a slash) then docker creates a volume with that name to store the data.

You'll likely find a volume named "mydir" if you run `docker volume ls` (See https://docs.docker.com/v1.9/engine/reference/commandline/volume_ls/), that contains the tmp you created.

You can check if that volume contains the `tmp` file, by using the same volume again; doing;

    docker run -it -v mydir:/mydir centos:7 bash

And then check the contents of "mydir" inside the container

**Comment by jramapuram** [comment]
Hi @thaJeztah , thanks for your comment.
This issue happens even with volume mounting (i.e. with a fully qualified path):

```bash
[centos@jramapuram ~]$ docker run -v /tmp/rpmbuild:/rpmbuild -v /var/run/docker.sock:/var/run/docker.sock -v /usr/bin/docker:/usr/bin/docker -it centos:7 bash
Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
[root@46a5434248c6 /]# ls
anaconda-post.log  bin  dev  etc  home  lib  lib64  lost+found  media  mnt  opt  proc  root  rpmbuild  run  sbin  srv  sys  tmp  usr  var
[root@46a5434248c6 /]# docker run -v /rpmbuild:/rpmbuild -v /var/run/docker.sock:/var/run/docker.sock -v /usr/bin/docker:/usr/bin/docker -it centos:7 bash
Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
[root@9edbc3b922f4 /]# touch /rpmbuild/test
[root@9edbc3b922f4 rpmbuild]# ls /rpmbuild
test
[root@9edbc3b922f4 rpmbuild]# exit
exit
[root@46a5434248c6 /]# ls rpmbuild/
[root@46a5434248c6 /]#
```

the `test` file does not persist into the host container.

**Comment by thaJeztah** [comment]
Oh, actually, I understand what's happening. You're not running docker-in-docker, but even though you're running inside a container, you're still controlling the docker daemon that's running *on the host*.

The `-v /some/path:/container/path` is always using the filesystem that *the daemon* runs on, which in this case, is `/rpmbuild` on your host. If you run `ls /rpmbuild/` on your host (not inside a container), do you see the `test` file there?

**Comment by jramapuram** [comment]
@thaJeztah : Yes, you are correct! Thank you! :)

**Comment by thaJeztah** [comment]
You're welcome!
