### ISSUE TITLE
-v flag in docker rm does not work

### ISSUE THREAD

**Issue by xlgao-zju** [docker/docker#22760]
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 70
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 125
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.13.0-86-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.719 GiB
Name: xlgao-pc
ID: TDMI:FSOX:JCO3:LIXU:QLK7:PJGD:KQR2:IRV3:DXEH:IG7D:DXTQ:773I
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Username: xlgao
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.docker volume create --name test
2.docker run -d -v test:/data --name vol_rm_test busybox
3.docker volume ls

**Describe the results you received:**
I can stall find the volume named test

**Describe the results you expected:**
can't find the volume named test

**Additional information you deem important (e.g. issue happens only occasionally):**
v1.10.3 has this issue too

**Comment by runcom** [comment]
> Steps to reproduce the issue:
> 1.docker volume create --name test
> 2.docker run -d -v test:/data --name vol_rm_test busybox
> 3.docker volume ls

where is `docker rm` here? I think this is expected behavior though ping @cpuguy83

**Comment by vdemeester** [comment]
I think so too. `docker rm -v` do not remove named volumes, by design.

**Comment by cpuguy83** [comment]
Correct, this is intended behavior.

**Comment by xlgao-zju** [comment]
thanks, I get it.
