### ISSUE TITLE
How to compose a container from a Image and layer in Docker 1.10

### ISSUE THREAD

**Issue by JackChen255** [docker/docker#22766]
Two questions. Thanks in advance.
1: In V 1.10, how to retrieve new layer ID after creating a new container from a image? In previous version, the layer ID is the same as container ID which is returned from RestAPI "POST /containers/create"? Looks like the new layer ID is saved in the last item in manifest.json, but this assumption is not safe.
2: How to restore a container from an Image and above layer.tar? RestAPI "PUT /containers/(id or name)/archive" can't extract the tar ball to root directory /, and it can't handle the deleted files in the new container.

**Comment by zrss** [comment]
hi @JackChen255 , do u find a solution for the questions 2 ?
