### ISSUE TITLE
Expose libnetwork's CreateEndpoint options in docker cli

### ISSUE THREAD

**Issue by fkautz** [docker/docker#22776]
The libnetwork API has an optional "options" map which can be passed into the CreateEndpoint call.

Docker CLI does not have a way to pass any custom options to CreateEndpoint

So... I propose:

```sh
% docker run --net-opt=[]
```

which is inline with:
```sh
% docker run --help | grep -i "\-opt"
  --dns-opt=[]                    Set DNS options
  --log-opt=[]                    Log driver options
  --security-opt=[]               Security Options
```

One use case is to support multi-tenant calls to kuryr through docker in openstack environments where users should provide an openstack token.

Alternative use cases include passing runtime information to the runtime for operational purposes such as additional resource provisioning, QOS, firewall params.

**Comment by mavenugo** [comment]
I think this is going down the path of https://github.com/docker/docker/pull/21663#issuecomment-217428605 . WDYT ?

**Comment by fkautz** [comment]
Would a policy work for those tokens though? The main problem is there is necessary runtime info that cannot be expressed purely at network creation time.

The policy idea could work as long as we have a way to accurately select which containers should be assigned a given set of keys and if policy can be changed over time e.g. we shouldn't need to rebuild a container cluster because an auth token was recycled and network policy had no way to reflect this change.

Policies seem harder to implement than passing down a set of options though, since policies imply that updating the policy would update all current running containers. A network opt passed in at run would not imply such behavior.

**Comment by fkautz** [comment]
@mavenugo would you like me to spec out a draft api for a policy based approach?

**Comment by mavenugo** [comment]
@fkautz I guess you can start to review the work by @jainvipin & @tgraf : https://github.com/docker/docker/issues/11187 and work with them if possible to define such a policy layer.

**Comment by thaJeztah** [comment]
Should we close this in favor of a proposal, related to https://github.com/docker/docker/issues/11187?

**Comment by jainvipin** [comment]
@fkautz +1
I like the simplicity of basic `docker run --net-opt=[]`; We discussed this in the past and were taken down (need to recall the proposal with @dave-tucker on policy proposal)

**Comment by fkautz** [comment]
@thaJeztah Since we have a path to move forward, closing this. 

For reference, the path is to set up a policy spec that can be applied at run time. Please contact me directly if you want to help with this spec.

**Comment by thaJeztah** [comment]
Thanks @fkautz!
