### ISSUE TITLE
Java hangs in containers running in boot2docker

### ISSUE THREAD

**Issue by nicoleneo** [docker/docker#22773]
I built this just fine on my Ubuntu machine using the exact instructions and pulling the newest centos:centos7 base image today. [This](https://github.com/nicoleneo/neo-centos7-docker/blob/master/build/Dockerfile) is the Dockerfile.

On a container running in boot2docker on OSX, Java can't exit or hangs. E.g. running the command 'java' which doesn't work and will display the man with the appropriate commands can be quit by Ctrl-C but the Docker container can't be stopped because the java process is still there.

When I install NetBeans using silent install, it's stuck forever. Removing the silent install flag, I can see it's stuck at:
`root@docker:/home/nicole# ./netbeans.sh 
Configuring the installer...
Searching for JVM on the system...
Preparing bundled JVM ...`

Processes showing the stray java process.
`root      1256     1  0 20:49 ?        00:00:00 /bin/sh ./netbeans.sh
root      1257  1256 99 20:49 ?        00:02:27 [java] <defunct>
`

**Comment by nicoleneo** [comment]
#18180 shows the same issue happens on other java processes on boot2docker.

**Comment by cpuguy83** [comment]
Yes, this looks like a dup of #18180

Can you provide the output of `docker info` and `docker version` please?
Thanks!

**Comment by nicoleneo** [comment]
docker version
	Client:
	 Version:      1.9.1
	 API version:  1.21
	 Go version:   go1.4.3
	 Git commit:   a34a1d5
	 Built:        Fri Nov 20 17:56:04 UTC 2015
	 OS/Arch:      darwin/amd64

	Server:
	 Version:      1.9.1
	 API version:  1.21
	 Go version:   go1.4.3
	 Git commit:   a34a1d5
	 Built:        Fri Nov 20 17:56:04 UTC 2015
	 OS/Arch:      linux/amd64

	docker info
	Containers: 1
	Images: 120
	Server Version: 1.9.1
	Storage Driver: aufs
	 Root Dir: /mnt/sda1/var/lib/docker/aufs
	 Backing Filesystem: extfs
	 Dirs: 122
	 Dirperm1 Supported: true
	Execution Driver: native-0.2
	Logging Driver: json-file
	Kernel Version: 4.1.13-boot2docker
	Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
	CPUs: 1
	Total Memory: 5.376 GiB
	Name: default
	ID: YIFU:YV6W:2YY5:J6RY:XB5P:DOKN:DRF7:IRSI:Z76B:JPYW:7UOX:LYYH
	Debug mode (server): true
	 File Descriptors: 12
	 Goroutines: 18
	 System Time: 2016-05-16T21:09:40.262950905Z
	 EventsListeners: 0
	 Init SHA1: 
	 Init Path: /usr/local/bin/docker
	 Docker Root Dir: /mnt/sda1/var/lib/docker
	Labels:
	 provider=virtualbox

**Comment by cpuguy83** [comment]
Yeah, sounds like a dup. You'll need to upgrade the boot2docker version.

**Comment by thaJeztah** [comment]
Agreed, this most likely is a dup of https://github.com/docker/docker/issues/18180. I'll go ahead and close this issue, but feel free to comment after I closed

**Comment by nicoleneo** [comment]
@thaJeztah @cpuguy83 Yep thanks, it resolved itself with an upgrade of Docker Toolbox.
