### ISSUE TITLE
mkimage-yum.sh: unable to install desired groups and packages in one step

### ISSUE THREAD

**Issue by n0mik0s** [docker/docker#22783]
**Output of `docker version`:**
```
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d/1.7.1
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d/1.7.1
OS/Arch (server): linux/amd64
```

**Output of `docker info`:**

```
Containers: 14
Images: 1
Storage Driver: devicemapper
 Pool Name: docker-253:1-1576860-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.856 GB
 Data Space Total: 107.4 GB
 Data Space Available: 38.91 GB
 Metadata Space Used: 2.228 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.95-RHEL6 (2015-09-08)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 2.6.32-573.12.1.el6.x86_64
Operating System: <unknown>
CPUs: 8
Total Memory: 11.63 GiB
Name: bsm-test1
ID: IJQN:A3MZ:5BQZ:FLU7:F7YG:35OF:C3JC:XKPG:R34Y:2CRA:IQNC:WNRE
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
vm on VMWare 5.x

**Steps to reproduce the issue:**
1. ./mkimage-yum.sh -p "yum.noarch yum-utils.noarch vim-common.noarch" -g "Base" rhel6_base

**Describe the results you received:**
The only Base group installed, the packages failed to be installed:
+ yum --installroot=/tmp/mkimage-yum.sh.0YUO2V --releasever=/ --setopt=tsflags=nodocs --setopt=group_package_types=mandatory -y install yum.noarch yum-utils.noarch vim-common.noarch
Loaded plugins: product-id, security, subscription-manager
Setting up Install Process
No package yum.noarch available.
No package yum-utils.noarch available.
No package vim-common.noarch available.
Error: Nothing to do

But these packages could be installed, they trully persists in the repos I use, I could search them and install manually.
When I've switched group install and the packages install sections I successfully installed desired packages with dependencies but was failed to install Base group with the same outpus as in the first example.

**Describe the results you expected:**
I expect that the group Base and the packages yum.noarch yum-utils.noarch vim-common.noarch will be installed

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
ping @stpierre perhaps you know what can cause this?

**Comment by n0mik0s** [comment]
What works for me is:

<<<
if [[ -n "$install_groups" ]];
then
    yum -t --installroot="$target" --setopt=tsflags=nodocs \
        --setopt=group_package_types=mandatory -y groupinstall $install_groups
    **rm -rf "$target"/etc/yum.repos.d && rm -rf "$target"/etc/yum.conf && rm -rf "$target"/etc/yum**
fi

if [[ -n "$install_packages" ]];
then
    yum -t --installroot="$target" --setopt=tsflags=nodocs \
        -y install $install_packages
    **rm -rf "$target"/etc/yum.repos.d && rm -rf "$target"/etc/yum.conf && rm -rf "$target"/etc/yum**
fi
>>>

Pretty ugly but works fine...

**Comment by thaJeztah** [comment]
I never used the script myself, but if there's improvements that can be made, feel free to open a PR, then we can review/discuss those changes

**Comment by n0mik0s** [comment]
I do not think that my changes are so important that there is should be created new PR for them. I posted my changes for those who will (or have been) faced with the problems like I did.
Thanks!

**Comment by thaJeztah** [comment]
Alright, I'll close this issue then. Thanks!

**Comment by JoseTomasTocino** [comment]
I've been faced with the exact same problem and the solution provided by n0mik0s works like a charm. I'd suggest to merge it, because it's a common issue.

**Comment by n0mik0s** [comment]
This issue persists only on RHEL systems. On CentOS the script works fine without any additional configuration.
