### ISSUE TITLE
Might be something wrong with docker-ssd.pid

### ISSUE THREAD

**Issue by wangxing1517** [docker/docker#22786]
Here is a docker-ssd.pid in my machine, when I run:
`dockerd -s overlay`
I notice that pid in docker.pid is right, while pid in docker-ssd.pid is wrong.

And when I try to remove docker, let's say v1.9.1 for example. I got
```
Removing lxc-docker-1.9.1 ...
[....] Stopping Docker: dockerNo process in pidfile '/var/run/docker-ssd.pid' found running; none killed.
```
I guess maybe docker-ssd.pid isn't useless, so is there anything wrong with docker-ssd.pid?

**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.4
 Git commit:   af60a9e-unsupported
 Built:        Tue May 17 02:04:00 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.4
 Git commit:   af60a9e-unsupported
 Built:        Tue May 17 02:04:00 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 62
Server Version: 1.12.0-dev
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.18.20-nce-amd64
Operating System: Debian GNU/Linux 7 (wheezy)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.818 GiB
Name: github
ID: WHKL:7W4G:OV6K:LBH5:M2UL:UIWR:257S:JWB5:QU74:5WYE:4FUE:VW3I
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Steps to reproduce the issue:**
1. dockerd -s overlay
2. cat /var/run/docker.pid
3. cat /var/run/docker-ssd.pid

**Describe the results you received:**
pid in docker-ssd.pid is wrong

**Describe the results you expected:**
pid in docker-ssd.pid is right

**Additional information you deem important (e.g. issue happens only occasionally):**
This problem also exists in any lower docker version.

**Comment by HackToday** [comment]
Not found `docker-ssd.pid` file  on docker 1.11.1 with overlay

**Comment by thaJeztah** [comment]
this may be something from the old version; the `lxc-docker` package, was that installed from out repositories, or from the debian repositories? I found this old report in the Debian bug tracker; https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=815246, and some other reports https://www.google.nl/search?rls=en&q=%22docker-ssd.pid%22&ie=UTF-8&oe=UTF-8&gfe_rd=cr&ei=TTs7V_T1LufG8AfG64P4CQ#q=%22docker-ssd.pid%22&start=0

**Comment by wangxing1517** [comment]
@thaJeztah , thanks for your help, it's surely sth from old version.

**Comment by chipironcin** [comment]
It happens to me while doing DIND with overlay.
```
root@f8af2af6d427:/# service docker stop
 * Stopping Docker: docker                                                                                                                      
No process in pidfile '/var/run/docker-ssd.pid' found running; none killed.

root@f8af2af6d427:/# ls /var/run/docker-ssd.pid
ls: cannot access '/var/run/docker-ssd.pid': No such file or directory

root@f8af2af6d427:/# ls /var/run/docker.pid
/var/run/docker.pid
```

`ps -aux` output:
```
root          7  0.0  0.0 1376040 43592 ?       Sl   16:56   0:00 dockerd --host=unix:///var/run/docker.sock --storage-driver=overlay
root         31  0.0  0.0 414672 10420 ?        Ssl  16:56   0:00 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.so
```
