### ISSUE TITLE
docker failing to start when ports being mapped

### ISSUE THREAD

**Issue by matthbull** [docker/docker#22792]
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:43:49 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:43:49 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 21
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 90
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.4.0-22-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 11.67 GiB
Name: ENVY
ID: 5E2B:2NGP:DART:EAJI:FXXR:QUTF:ZYOV:BACM:T2LZ:SLAU:YRHC:Z6JO
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Username: matthb
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

- Ubuntu 16.04 running on a laptop.
- uwf disabled
- docker restarted
- nothing is running on 3306

**Steps to reproduce the issue:**
```
$ docker run -e MYSQL_USER=mysql -e MYSQL_PASSWORD=mysql -e MYSQL_DATABASE=sample -e MYSQL_ROOT_PASSWORD=supersecret -it -p 3306:3306 mysql
```

**Describe the results you received:**
> docker: Error response from daemon: driver failed programming external connectivity on endpoint small_brown (c45f5b44e5862d2f3a9d064352fe463a31b55b178c4c8a36460951aa3c903cc2): iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 3306 -j DNAT --to-destination 172.17.0.2:3306 ! -i docker0: iptables: No chain/target/match by that name.

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
this happens whenever I run anything that maps a port

**Comment by thaJeztah** [comment]
This sounds as https://github.com/docker/docker/issues/16816 (and https://github.com/docker/docker/issues/17320), and could be related to other software interacting with iptables.

**Comment by matthbull** [comment]
urrg.  Ubuntu asked to install some updates this evening and now all is well.  I wish I could be more help. 

thanks for reading.
