### ISSUE TITLE
 ubuntu 16.04 x64 --Temporary failure resolving archive.ubuntu.com container  i386/ubuntu 

### ISSUE THREAD

**Issue by chrisber** [docker/docker#22797]
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:43:49 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:43:49 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 4
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 9
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-22-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.503 GiB
Name: lpt
ID: DPPO:663B:P43K:Q27E:EHMV:3VUO:5CKT:6SFB:SJTO:LMHI:F6XP:C4KE
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
- `Ubuntu 16.04`
- `Linux lpt 4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

**Steps to reproduce the issue:**
1.docker run -it --rm i386/ubuntu apt-get update
2. does not work

1.docker run --privileged -it --rm i386/ubuntu apt-get update
2.does work

**Describe the results you received:**
```
docker run -it --rm i386/ubuntu apt-get update
Err:1 http://archive.ubuntu.com/ubuntu xenial InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:2 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:3 http://archive.ubuntu.com/ubuntu xenial-security InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Reading package lists... Done
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-security/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.

```

**Describe the results you expected:**
`apt-get should update the container without privileged flag`.
Not able to build a container from a Dockerfile because privileged flag not available on `docker build`.

**Additional information you deem important (e.g. issue happens only occasionally):**
`docker run -it --rm ubuntu apt-get update` works
`docker run -it --rm i386/ubuntu apt-get update`does not work

**Comment by thaJeztah** [comment]
Can you try using `--security-opt seccomp=unconfined` instead of `--privileged`? This may be resolved on master

**Comment by chrisber** [comment]
`docker run --security-opt seccomp=unconfined -it --rm i386/ubuntu apt-get update` works also instead of `--privileged` but how to use it in a Docker file with `Docker build -t .`

**Comment by thaJeztah** [comment]
@chrisber did that work for you?

**Comment by chrisber** [comment]
yes docker version 1.11.0 worked. thanks
