### ISSUE TITLE
VOLUME declared in Dockerfile created if using `--volume-driver` causes issues

### ISSUE THREAD

**Issue by wallnerryan** [docker/docker#22793]
**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
$ docker info
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 35
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local flocker
 Network: bridge null host overlay
Kernel Version: 3.13.0-85-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 989.9 MiB
Name: mha-demo0
ID: HSZZ:ORSA:ECYV:XEOG:5YFD:7GKA:2KMI:NXKW:DK7E:BQL3:GBEA:N4JH
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=rackspace
Cluster store: consul://<IP>:8500
Cluster advertise: <IP>:0
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Rackspace Ubuntu 14.04 VMs.

**Steps to reproduce the issue:**
1. Create docker machine VM on rackspace or aws
2. install flocker and flocker volume plugin (or other external storage plugins)
3. reference the driver without the reference to the volume.

The issue is that I expect for referencing a volume driver that ONLY the volumes defined with `-v` and not the volumes defined with VOLUME in the image would be created.

This can cause unnecessary external volumes that a user may not want for their container. Even if I defined a `-v` volume that wasn't [the /data directory in the Dockerfile](https://github.com/dockerfile/redis/blob/master/Dockerfile#L28) then it would still be created in both cases.

**Example**

No volume defined, but volume-driver is there.
```
docker run -d --volume-driver flocker redis
ce155a13417f651499887fe1a93c087ab24c607365de762ca74565ff8e6a0b50
```

```
$ docker ps | grep redis
ce155a13417f        redis               "docker-entrypoint.sh"   About a minute ago   Up 58 seconds       6379/tcp                           mad_murdock
```

A volume was created from the external volume even though is was not referenced. This is the volume that is defined in https://github.com/dockerfile/redis/blob/master/Dockerfile#L28. The problem with this is that when these containers MOVE, RESTART or are RESCHEDULED then docker does not remember to use them because they are defined with `-v`, and an entire new volume is created externally. This causes unnecessary volume bloat and usage for users.
```
docker inspect -f "{{.Mounts}}" ce155a13417f
[{9f793b82f6c8f53ebc1b9960e9059d6ea7b4501191de6f55d1c1261538368e65 /flocker/c831cf02-5526-4a50-8830-2d598b467303 /data flocker  true }]
```

```
root@mha-demo0:~# docker volume ls | grep 9f793b82f6c8f53ebc1b9960e9059d6ea7b4501191de6f55d1c1261538368e65
flocker             9f793b82f6c8f53ebc1b9960e9059d6ea7b4501191de6f55d1c1261538368e65
```

cc @cpuguy83

**Comment by thaJeztah** [comment]
This was actually changed at some point (see https://github.com/docker/docker/pull/15507), but reverted in https://github.com/docker/docker/pull/19190

The best way to use two different drivers is to explicitly create the volume with that driver, instead of using the `--volume-driver` flag on docker run, e.g.;

    docker run -v $(docker volume create --volume-driver=flocker):/foo myimage

I actually proposed to deprecate the `--volume-driver` option on `docker run` for this reason (see https://github.com/docker/docker/issues/16069), but it was voted against.

Unfortunately I'll have to close this issue, because it was decided to keep this behavior. But feel free to continue the discussion

**Comment by wallnerryan** [comment]
thanks @thaJeztah i see. Avoiding it run makes sense, but in some cases, for instance with Mesos using the volume driver it takes volume-driver as a parameter. Therefore you must define ALL volumes even if you do not want to use the one defined in the image. Otherwise it will created one during restarts/reschedules. I guess the other option is to define an image that works for the usecase without VOLUME defined. I think folks still like using this flag during `run` so im glad it stayed for now until other integrations are ironed out.

**Comment by thaJeztah** [comment]
@wallnerryan yes, it's a difficult one, and I can see both options having advantages (and disadvantages).

`VOLUME` in Dockerfiles also has its share of positives/negatives; good to be able to define what really should be a volume, but they also tripped up people due to their behavior during build; in addition, we currently don't have an option to "reset" a `VOLUME`, once defined.
