### ISSUE TITLE
Support multiple --net/--ip specifications per container?

### ISSUE THREAD

**Issue by wrouesnel** [docker/docker#22798]
When using a network plugin like Calico which can support ECMP/Anycast style configurations, it's a big limitation at the moment not being able to configure via the docker run command multiple IP addresses / interfaces to be added to a container (i.e. multiple libnetwork calls).

Is this likely to be supported in the future? The use case would be adding a regular network interface for connectivity, and a separate possibly shared IP at the same time - ideally handled through a launch.

The use case would be when launching haproxy/load-balancer type containers which should be anycasted across a Swarm / other orchestrator network.

**Comment by coolljt0725** [comment]
Currently, we support `docker network connect ` to a non-running container,  so you can create a container and then add multiple interfaces to the container via `docker network connect`, and then the container will be started with multiple interfaces.

**Comment by thaJeztah** [comment]
This has been discussed before in https://github.com/docker/docker/pull/17796, https://github.com/docker/docker/issues/17750 and https://github.com/docker/docker/issues/17289, and is not something we'll implement; see https://github.com/docker/docker/pull/17796#issuecomment-172009986

I'll close this issue, but feel free to comment here after I closed

**Comment by pauldraper** [comment]
@coolljt0725 that means I would have to create multiple networks, right?
