### ISSUE TITLE
[1.11] ‘Spurious IPv4 forwarding disabled’ warning with --net='host'

### ISSUE THREAD

**Issue by sanmai-NL** [docker/docker#22805]
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   5604cbe
 Built:        Mon May  2 00:06:51 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   5604cbe
 Built:        Mon May  2 00:06:51 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**
Unnecessary.

**Steps to reproduce the issue:**
```
# Start Docker daemon systemd service like so:
# ExecStart=/usr/bin/docker daemon --ip-forward=false -H fd://

sudo docker run --net='host' --rm -it alpine /bin/sh
```

**Describe the results you received:**

Outputs:
```
WARNING: IPv4 forwarding is disabled. Networking will not work
```

**Describe the results you expected:**
No such warning. Networking, including container <-> WAN routing, works fine.

**Comment by thaJeztah** [comment]
Ah, yes, that warning doesn't make much sense for containers running with `--net=host`

I'll see if I can make a PR to fix that.

**Comment by thaJeztah** [comment]
Thanks @sanmai-NL, my PR was merged, so you won't be spammed with this message anymore in Docker 1.12 :smile:

**Comment by sanmai-NL** [comment]
@thaJeztah:
Thanks, but the patch needed some more thought I'm afraid.
In case networking is disabled, `--net=none`, the message is also displayed.

**Comment by thaJeztah** [comment]
@sanmai-NL oh! good point, I only tried the `--net=host` case. I'll draft up a follow-up PR

**Comment by thaJeztah** [comment]
@sanmai-NL see https://github.com/docker/docker/pull/22856
