### ISSUE TITLE
[1.11.1] Use `ip-masq` everywhere instead of both `ip-mask` and `ip-masq`.

### ISSUE THREAD

**Issue by sanmai-NL** [docker/docker#22807]
The Docker Engine daemon CLI param is `--ip-masq`, so do not use `ip-mask` parameter instead in `daemon.json`.

**Comment by thaJeztah** [comment]
Also see https://github.com/docker/docker/pull/22756

**Comment by far-blue** [comment]
In v1.11.1 the docker daemon.json file is documented as using ip-mask but, in fact, that doesn't work and you need to use ip-masq despite what the docs say.

**Comment by thaJeztah** [comment]
@far-blue are you sure? Because it reads that value from `ip-mask` in the JSON; https://github.com/docker/docker/blob/v1.11.1/daemon/config_unix.go#L43

**Comment by far-blue** [comment]
I know, it surprised me as well. I used ip-mask initially in daemon.json after questioning it and then looking in the source code but then the docker daemon wouldn't start, complaining that ip-mask was not a recognised key:

> May 18 13:51:24 orca5 systemd[1]: Starting Docker Application Container Engine...
> May 18 13:51:24 orca5 docker[12257]: unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives don't match any configuration option: ip-mask
> May 18 13:51:24 orca5 systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
> May 18 13:51:24 orca5 systemd[1]: Failed to start Docker Application Container Engine.
> May 18 13:51:24 orca5 systemd[1]: docker.service: Unit entered failed state.
> May 18 13:51:24 orca5 systemd[1]: docker.service: Failed with result 'exit-code'.

Switching it over to ip-masq worked. In my case I was turning ip masq off and can confirm that it did have the correct impact on the iptables setup.

This is with:
- Docker version 1.11.1, build 5604cbe
- Ubuntu 16.04 (64bit)

**Comment by sanmai-NL** [comment]
I can confirm @far-blue's experience with 1.11.1.

**Comment by thaJeztah** [comment]
Wow, surprised as well, let me try. If that's the case, then updating the docs and renaming the option would be easier 😇

**Comment by thaJeztah** [comment]
Ah! Mystery solved; the validation looks at the actual *flag* names, not the JSON names, which probably explains this; see https://github.com/docker/docker/blob/e9117578a7837eda31d690d5e51d09d43a6a8fca/daemon/config.go#L320-L348

And especially, these lines, which convert them to "flag" names, by prepending a `-`; https://github.com/docker/docker/blob/e9117578a7837eda31d690d5e51d09d43a6a8fca/daemon/config.go#L323-L324
