### ISSUE TITLE
Docker login with non-root artifactory path

### ISSUE THREAD

**Issue by oncletom** [docker/docker#22809]
This issue is about using `docker login` in combination with a private registry hosted on `https://xxx/artifactory/docker-registry/`.

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.6.1
 Git commit:   4dc5990
 Built:        Thu Apr 14 00:24:28 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 105
 Running: 1
 Paused: 0
 Stopped: 104
Images: 113
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 410
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.19-boot2docker
Operating System: Boot2Docker 1.11.0 (TCL 7.0); HEAD : 32ee7e9 - Wed Apr 13 20:06:49 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.1 MiB
Name: default
ID: 5NOJ:34RG:XLCK:JKGF:GU6Y:JQPM:CHFX:VJ73:6MB7:KWYE:Z43I:XGQO
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 17
 Goroutines: 37
 System Time: 2016-05-18T10:56:14.23235802Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

OSX on Macbook Pro

**Steps to reproduce the issue:**
1. `$ docker login https://xxx/artifactory/docker-registry/`
2. Type username and password
3. Got the following response:

```
Error response from daemon: Get https://xxx/v1/users/: remote error: handshake failure
```

**Describe the results you received:**

Forget about the `handshake failure`, this is because the `SSLVerifyClient` policy in use.

What I am rather surprised of is Docker tries to fetch data from `https://xxx/v1/users/` rather than `https://xxx/artifactory/docker-registry/v1/users/`.

Because we use artifactory, hubs and registries are not hosted at the root of the URL. 

Is that the intended result?

**Comment by thaJeztah** [comment]
As far as I'm aware, those paths are not configurable, and having them at the "root" is part of the specification; https://docs.docker.com/registry/spec/api/

Have you contacted Jfrog/Artifactory about this?

**Comment by jheiss** [comment]
@oncletom: I think you've configured your Artifactory install incorrectly. The standard reverse proxy setup for Apache or Nginx in front of Artifactory redirects the Docker URLs as Docker expects them. As noted on https://www.jfrog.com/confluence/display/RTF/Configuring+a+Reverse+Proxy using a reverse proxy is required with Docker.

E.g. here's a snippit out of the Artifactory reverse proxy configuration generator for nginx:

```
    rewrite ^/$ /webapp/ redirect;
    rewrite ^//?(/webapp)?$ /webapp/ redirect;
    rewrite ^/(v1|v2)/(.*) /api/docker/$repo/$1/$2;
```

**Comment by oncletom** [comment]
That's correct — plus we were facing an issue with cert-based authentication with a field containing an email address.

Thanks for your support :-)
