### ISSUE TITLE
device-mapper-driver documentation update looses thinpool configuration info

### ISSUE THREAD

**Issue by HenningWagner** [docker/docker#22817]
Referring to #22166

The [last commit of the device-mapper documentation](https://github.com/docker/docker/commit/a7b2f87b0637a3711e90c0f1d0a99dd5d32bd60f#diff-52525eec69924c13d098f5d19b2d79adL254) by @chenchun clarified the overall use.
But as I go through the steps, I'm missing the part where the thinpool configuration on /data and /metadata is done.

The [diff shows that the previous version ](https://github.com/docker/docker/pull/22662/commits/3cf8c53515ff8144a63c6d4418738b5d4f4416a7)had this covered in lines 254 and following

**Comment by thaJeztah** [comment]
ping @mbentley could you have a look what's missing?

**Comment by mbentley** [comment]
There are a number of steps missing from this; looks like someone wrote docs on an old version and it was merged.  From what I can see of the [history](https://github.com/docker/docker/commits/master/docs/userguide/storagedriver/device-mapper-driver.md), a7b2f87b0637a3711e90c0f1d0a99dd5d32bd60f seems to have reverted some old docs.  The last time to docs were correct was 24ec73f754da16e37726a3f1c6a59de508e255fc.  I'd suggest we revert to 24ec73f754da16e37726a3f1c6a59de508e255fc and have the updates done in a7b2f87b0637a3711e90c0f1d0a99dd5d32bd60f rebased.

**Comment by thaJeztah** [comment]
Hm, may become tricky, because the changes in https://github.com/docker/docker/commit/24ec73f754da16e37726a3f1c6a59de508e255fc are for 1.12 (which renames `docker daemon` to `dockerd`), so those cannot go live yet

**Comment by mbentley** [comment]
Then we'll need to revert to b21d90c28faaa9f906c4e3b2145ddf661a19e994 for now.

**Comment by mbentley** [comment]
OK, I gave it a stab.  That was more of a pain than I realized.  I believe I also included the formatting changes made in other commits since the dm docs were messed up.
