### ISSUE TITLE
Chown command in docker file adds a new layer when used to change the ownership of the copied directory/file

### ISSUE THREAD

**Issue by ameyrk** [docker/docker#22810]
**Output of `docker version`:**

```
$ docker --version
Docker version 1.9.1, build a34a1d5/1.9.1

```

**Output of `docker info`:**

```
$ docker info
Containers: 4
Images: 180
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-202:48-131076-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem:
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 5.911 GB
 Data Space Total: 107.4 GB
 Data Space Available: 9.915 GB
 Metadata Space Used: 10.95 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.137 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /mnt/docker/devicemapper/devicemapper/data
 Metadata loop file: /mnt/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.19-24.31.amzn1.x86_64
Operating System: Amazon Linux AMI 2015.09
CPUs: 1
Total Memory: 3.679 GiB
Name: ip-10-10-10-22
ID: V25U:OHKU:HIOQ:AW2A:V2HA:7OIB:EA4V:OTYO:CTAA:2SD4:KMXY:O536

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Create a docker file as below 
FROM tomcat
RUN useradd -d /home/test test
ADD test123 /home/test/test123
RUN chown -R test:test /home/sdpuser/test123
2. mkdir test123 && cd test123 
3. cp <somefile> test123 
4. docker build -t test .

**Describe the results you received:**

When you do a docker history add the last you see chown is getting duplicated thus adding up 28.72 MB space. Ideally should run as a command but its a new layer of the same size. I figured this when I was building a custom image for my project and creating non root user within my containers.  Is this an expected behavior ?

I have applied a workaround by changing the ownership within the hostOs.

docker history test
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
**ec6211788d5f        52 seconds ago      /bin/sh -c chown -R sdpuser:sdpuser /home/sdp   28.72 MB
aa53295d188d        58 seconds ago      /bin/sh -c #(nop) ADD dir:f9bbeebffd367903e94   28.72 MB**
10c5e8e82d47        41 minutes ago      /bin/sh -c useradd -d /home/sdpuser sdpuser     329.1 kB
cdc78b94a897        6 months ago        /bin/sh -c #(nop) CMD ["catalina.sh" "run"]     0 B
82f58c961431        6 months ago        /bin/sh -c #(nop) EXPOSE 8080/tcp               0 B
34d8147d3641        6 months ago        /bin/sh -c set -x  && curl -fSL "$TOMCAT_TGZ_   12.91 MB
73deaaca356b        6 months ago        /bin/sh -c #(nop) ENV TOMCAT_TGZ_URL=https://   0 B
a1deecf5c68e        6 months ago        /bin/sh -c #(nop) ENV TOMCAT_VERSION=8.0.28     0 B
8384577d6bb9        6 months ago        /bin/sh -c #(nop) ENV TOMCAT_MAJOR=8            0 B
a99360bba5f9        6 months ago        /bin/sh -c gpg --keyserver pool.sks-keyserver   111 kB
7f0c5db847d7        6 months ago        /bin/sh -c #(nop) WORKDIR /usr/local/tomcat     0 B
92bbf8c9f01c        6 months ago        /bin/sh -c mkdir -p "$CATALINA_HOME"            0 B
7d22540101dc        6 months ago        /bin/sh -c #(nop) ENV PATH=/usr/local/tomcat/   0 B
864b08468887        6 months ago        /bin/sh -c #(nop) ENV CATALINA_HOME=/usr/loca   0 B
30d5a52e17ca        6 months ago        /bin/sh -c apt-get update && apt-get install    173.8 MB
75fc529176f0        6 months ago        /bin/sh -c #(nop) ENV JAVA_DEBIAN_VERSION=7u8   0 B
9ca451982f56        6 months ago        /bin/sh -c #(nop) ENV JAVA_VERSION=7u85         0 B
927bc2c0c1e5        6 months ago        /bin/sh -c #(nop) ENV LANG=C.UTF-8              0 B
b38503f73b41        6 months ago        /bin/sh -c apt-get update && apt-get install    680.7 kB
4c0cc976b7bb        6 months ago        /bin/sh -c apt-get update && apt-get install    44.27 MB
1d6f63d023f5        6 months ago        /bin/sh -c #(nop) CMD ["/bin/bash"]             0 B
ef2704e74ecc        6 months ago        /bin/sh -c #(nop) ADD file:3037fa9e903e9ae533   125.1 MB

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment]
Yes, this is expected.
The filesystem has to copy up the the file into the new layer so that it can be chowned.

**Comment by ameyrk** [comment]
Thanks for the info

**Comment by MaRuifeng** [comment]
@ameyrk Afaik, `chown` commond does not introduce additional disk usage when the storage driver is chosen as _devicemapper_.
