### ISSUE TITLE
https://apt.dockerproject.org down again?

### ISSUE THREAD

**Issue by jianghaitao** [docker/docker#22819]
I saw an earlier issue filed related to this that was closed last year, but it seems that the issue still exists and I can not install docker on my Ubuntu machines. 
```
apt-get update
:
Ign https://apt.dockerproject.org ubuntu-trusty Release
Err https://apt.dockerproject.org ubuntu-trusty/main amd64 Packages
  Operation timed out after 0 milliseconds with 0 out of 0 bytes received
Ign https://apt.dockerproject.org ubuntu-trusty/main Translation-en_US
Ign https://apt.dockerproject.org ubuntu-trusty/main Translation-en
Fetched 200 kB in 3min 0s (1,110 B/s)
W: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-trusty/main/binary-amd64/Packages  Operation timed out after 0 milliseconds with 0 out of 0 bytes received

E: Some index files failed to download. They have been ignored, or old ones used instead.
```
Do we have any remedy for this?

**Comment by thaJeztah** [comment]
I'm not aware of it being down (or having been down). Are you still having this issue?

**Comment by unclejack** [comment]
I'm going to close this issue as there doesn't seem to be any issue with this. Please make sure there's no corporate proxy or some kind of firewall which is blocking access to certain websites.
