### ISSUE TITLE
Docker IPv6 cluster setup & documentation

### ISSUE THREAD

**Issue by schinzelh** [docker/docker#22831]
I've tried to wrap my head around the [Docker IPv6 cluster documentation](https://docs.docker.com/engine/userguide/networking/default_network/ipv6/), but something does not work out.

It seems that both graphics for [Switched network environment](https://docs.docker.com/engine/userguide/networking/default_network/images/ipv6_switched_network_example.svg)
![image](https://cloud.githubusercontent.com/assets/636669/15391455/90ccb634-1dc1-11e6-917f-a1da758b3777.png)
and [Routed network environment](https://docs.docker.com/engine/userguide/networking/default_network/images/ipv6_routed_network_example.svg)
![image](https://cloud.githubusercontent.com/assets/636669/15391479/aa4a9cfc-1dc1-11e6-8a56-db728d0be83e.png)
 are identical (beside some typos) and are not helping with my issue.

My use case:

I have a /48 network (`2001:XXXX:45::/48`) and routed two /64 subnetworks (`2001:XXXX:45:2::/64` and `2001:XXXX:45:3::/64 `) to my host and assigned one of it to the host and the other to the containers. So Host1 has

```
$ # ip -6 addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qlen 1000
    inet6 2001:XXXX:45:2::2/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::ec4:7aff:fe06:5830/64 scope link
       valid_lft forever preferred_lft forever
181: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500
    inet6 2001:XXXX:45:3::1/64 scope global tentative
       valid_lft forever preferred_lft forever
    inet6 fe80::1/64 scope link tentative
       valid_lft forever preferred_lft forever


$ ip -6 route
2001:XXXX:45:2::/64 dev eth0  proto kernel  metric 256
2001:XXXX:45:3::/64 dev docker0  proto kernel  metric 256
2001:XXXX:45:3::/64 dev docker0  metric 1024
fe80::223:9cff:fefc:6ff0 dev eth0  metric 1024
fe80::/64 dev eth0  proto kernel  metric 256
fe80::/64 dev docker0  proto kernel  metric 256
default via fe80::223:9cff:fefc:6ff0 dev eth0  metric 1024
```
while Container1-1, Container1-2, Container1-X get started with

```
DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4 --fixed-cidr-v6=2001:XXXX:45:3::/64 --ipv6"
```

and result in this

```
$ docker run -it ubuntu:14.04 bash -c 'ip -6 addr; echo '====' ; ip -6 route'
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
190: eth0: <NO-CARRIER,BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500
    inet6 2001:XXXX:45:3:0:242:ac11:2/64 scope global nodad
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe11:2/64 scope link tentative
       valid_lft forever preferred_lft forever
====
2001:XXXX:45:3::/64 dev eth0  proto kernel  metric 256
fe80::/64 dev eth0  proto kernel  metric 256
default via 2001:XXXX:45:3::1 dev eth0  metric 1024
```

My issue is: I can't make this work without a NDP proxy on the host. The containers are not able to reach outside world, unless i manually add a NDP proxy on my host, e.g.:

```
$ sysctl net.ipv6.conf.eth0.proxy_ndp=1
$ ip -6 neigh add proxy 2001:XXXX:45:3:0:242:ac11:2 dev eth0
```

What am i missing? The documentation gives the impression that NDP proxying is only necessary if using a single /64 - and switches/routed environments should work without NDP proxy.

**Comment by schinzelh** [comment]
It turned out that i had a typo in my routing table:

The above setup works without NDP proxy IF your second /64 gets routed to a (host) address inside the first /64, so i had to route  `2001:XXXX:45:3::/64` to `2001:XXXX:45:2::2`

**Comment by thaJeztah** [comment]
Thanks for reporting back @schinzelh. If you think there's improvements to be made to this section of the docs, let us know as well 👍
