### ISSUE TITLE
"docker daemon -H fd://" fails with message "No sockets found" under Ubuntu 15.10

### ISSUE THREAD

**Issue by elifarley** [docker/docker#22847]
Docker used to work fine, but after I ran the official PostgreSQL image (postgres:9.5.3), commands like `docker ps`, `docker images` and `systemctl start docker` would hang.

I had to kill -9 all docker-related processes and `apt-get remove docker-engine`, and then `rm -rf /var/lib/docker`. After that, I installed docker-engine via `apt-get install docker-engine` and also via get.docker.com, but I couldn't get Docker to run again.

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:38:55 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Output of `docker info`:**

```
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```
However, If I run Docker by typing `docker daemon` (instead of `systemctl start docker`), `docker info` gives this:
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.2.0-34-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.56 GiB
Name: thundera
ID: KF4T:5CCO:DUDH:ECCB:3CYT:KMNJ:K7LI:LIXM:HZHP:WU74:ZK6C:YO5Y
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Username: myuser
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical Ubuntu 15.10
Linux thundera 4.2.0-34-generic #39-Ubuntu SMP Thu Mar 10 22:13:01 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
$> free -m
             total       used       free     shared    buffers     cached
Mem:         15934       3663      12270         76       2275        906
-/+ buffers/cache:        481      15452
Swap:        16269          0      16269

$> df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            7,8G     0  7,8G   0% /dev
tmpfs           1,6G  9,3M  1,6G   1% /run
/dev/sda2       213G  6,9G  196G   4% /
tmpfs           7,8G     0  7,8G   0% /sys/fs/cgroup
/dev/sda1       511M  3,4M  508M   1% /boot/efi
```

**Steps to reproduce the issue:**
```
$> apt-get install docker-engine 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  docker-engine
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/14,5 MB of archives.
After this operation, 73,4 MB of additional disk space will be used.
Selecting previously unselected package docker-engine.
(Reading database ... 216726 files and directories currently installed.)
Preparing to unpack .../docker-engine_1.11.1-0~wily_amd64.deb ...
Unpacking docker-engine (1.11.1-0~wily) ...
Processing triggers for man-db (2.7.4-1) ...
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for systemd (225-1ubuntu9) ...
Setting up docker-engine (1.11.1-0~wily) ...

$> docker daemon
INFO[0000] New containerd process, pid: 6963
           
WARN[0000] containerd: low RLIMIT_NOFILE changing to max  current=1024 max=65536
INFO[0001] Graph migration to content-addressability took 0.00 seconds 
INFO[0001] Firewalld running: false                     
INFO[0001] Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address 
WARN[0001] Your kernel does not support swap memory limit. 
WARN[0001] mountpoint for pids not found                
INFO[0001] Loading containers: start.                   

INFO[0001] Loading containers: done.                    
INFO[0001] Daemon has completed initialization          
INFO[0001] Docker daemon                                 commit=5604cbe graphdriver=aufs version=1.11.1
INFO[0001] API listen on /var/run/docker.sock     

(type <CTRL>-C)

$> docker daemon -H fd://
FATA[0000] No sockets found. Make sure the docker daemon was started by systemd. 

$> systemctl start docker
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.

$> systemctl status docker -l
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Qui 2016-05-19 22:03:41 BRT; 22s ago
     Docs: https://docs.docker.com
  Process: 7057 ExecStart=/usr/bin/docker daemon -H fd:// (code=exited, status=1/FAILURE)
 Main PID: 7057 (code=exited, status=1/FAILURE)

Mai 19 22:03:41 thundera systemd[1]: Starting Docker Application Container Engine...
Mai 19 22:03:41 thundera docker[7057]: time="2016-05-19T22:03:41.436568496-03:00" level=fatal 
msg="No sockets found. Make sure the docker daemon was started by systemd."
Mai 19 22:03:41 thundera systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Mai 19 22:03:41 thundera systemd[1]: Failed to start Docker Application Container Engine.
Mai 19 22:03:41 thundera systemd[1]: docker.service: Unit entered failed state.
Mai 19 22:03:41 thundera systemd[1]: docker.service: Failed with result 'exit-code'.

$> journalctl -xe
-- Unit docker.service has begun starting up.
Mai 19 22:03:41 thundera docker[7057]: time="2016-05-19T22:03:41.436568496-03:00" level=fatal 
msg="No sockets found. Make sure the docker daemon was started by systemd."
Mai 19 22:03:41 thundera systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Mai 19 22:03:41 thundera systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
```

**Describe the results you received:**
Docker daemon doesn't run

**Describe the results you expected:**
Docker daemon should be running

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by HackToday** [comment]
did you follow this guide ?
https://github.com/docker/docker/blob/master/docs/installation/linux/ubuntulinux.md

**Comment by elifarley** [comment]
Docker won't run if I install via `curl -sSL https://get.docker.com/ | sh`, and when following that guide, it won't run either, showing the exact same error on both methods.

**Comment by thaJeztah** [comment]
Hm, wondering if this has to do with socket activation. What does

    systemctl status docker.socket

Give you?

**Comment by elifarley** [comment]
```
● docker.socket
   Loaded: masked (/dev/null)
   Active: inactive (dead)

Mai 20 10:45:27 thundera systemd[1]: docker.socket: Cannot add dependency job, ignoring: Unit docker.socket is masked.
Mai 20 10:45:28 thundera systemd[1]: docker.socket: Cannot add dependency job, ignoring: Unit docker.socket is masked.
Mai 20 10:45:32 thundera systemd[1]: docker.socket: Cannot add dependency job, ignoring: Unit docker.socket is masked.
Mai 20 10:45:32 thundera systemd[1]: docker.socket: Cannot add dependency job, ignoring: Unit docker.socket is masked.
Mai 20 10:45:36 thundera systemd[1]: docker.socket: Cannot add dependency job, ignoring: Unit docker.socket is masked.
Mai 20 10:45:59 thundera systemd[1]: docker.socket: Cannot add dependency job, ignoring: Unit docker.socket is masked.
Mai 20 10:49:32 thundera systemd[1]: docker.socket: Cannot add dependency job, ignoring: Unit docker.socket is masked.
Mai 20 10:50:30 thundera systemd[1]: docker.socket: Cannot add dependency job, ignoring: Unit docker.socket is masked.
Mai 20 10:50:31 thundera systemd[1]: docker.socket: Cannot add dependency job, ignoring: Unit docker.socket is masked.
Mai 20 10:51:35 thundera systemd[1]: docker.socket: Cannot add dependency job, ignoring: Unit docker.socket is masked.
```

**Comment by elifarley** [comment]
After issuing `systemctl unmask docker.socket`, I was able to start docker normally (`systemctl start docker`).

Here's a suggestion to improve the error message when the socket is masked:

```
$> systemctl start docker
Unable to start docker.service, since it depends on a masked unit (docker.sock). Try unmasking it first (systemctl unmask docker.sock).
```

**Comment by thaJeztah** [comment]
Hm, any idea how to get such a message? Do you know if systemd allows you to detect if a dependent service is masked?

**Comment by elifarley** [comment]
BTW, my suggestion to improve the error message should be implemented in systemd itself, so I'll investigate if this is currently possible in systemd or if I should create an issue for them to make it possible.

As for the docker installation process, I guess it would be easy to perform a check during installation to verify if any of the needed units (docker.service and docker.sock) were installed in a masked state or not, and try to unmask them.

**Comment by thaJeztah** [comment]
@elifarley yes, having such a message from systemd would definitely be an improvement.

As to changing the installation procedure. The `curl | sh` installation script is designed for fresh installs, so I guess it was never developed with that situation in mind (although some people use if to update as well). I'm a bit in doubt as to which extend we should go for possible things that may block a successful installation. Perhaps some kind of knowledgebase would be a good place for this

**Comment by thaJeztah** [comment]
ping @kencochrane any thoughts on the installation procedure?

**Comment by elifarley** [comment]
I uninstalled docker (`apt-get remove docker-engine`) before attempting get.docker.com, so it's a _weak_ fresh install at least.

Perhaps the uninstallation process should remove more files than it is currently removing then.

**Comment by thaJeztah** [comment]
Ok, looks like `apt-get remove` keeps those unit-files around, whereas `apt-get purge` removes them

```
apt-get remove docker-engine
...
...
systemctl status docker.socket
● docker.socket
   Loaded: masked (/dev/null; bad)
   Active: inactive (dead) since Fri 2016-05-20 10:46:48 EDT; 25s ago
```

and apt-get purge;

```
apt-get purge docker-engine
...
...
systemctl status docker.socket
● docker.socket
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
```

**Comment by kencochrane** [comment]
@thaJeztah it looks like the underlying cause is that apt-get remove leaves some files along, I wonder if that is something we can control on our side, or if that is strictly an apt-get feature.

Doing some quick searches, it looks like the ``apt-get --purge remove`` and ``apt-get clean`` are the recommended ways to remove a package, and you can even use `deborphan` and `debfoster`

> $ apt-get install deborphan debfoster 
> $ apt-get remove --purge package
> $ apt-get clean

> the later will clean the /var

> $ debfoster

> will show files and libraries still left after the apt-get remove --purge, if you don't recognize a library, keep it, later on, deborphan will give you a list of 'orphaned' libraries that are hanging with no use, and are safe to nuke.

> if you make a mistake with debfoster, type 'u' and will ask you again if you want to keep it. When you are thru with it, invoke deborphan.

>$ deborphan

> will give a list of libraries that are hanging just taking space, to get rid of them:

> $ deborphan | xargs apt-get -y remove purge

> when thru with that:

> $ apt-get clean

**Comment by thaJeztah** [comment]
@kencochrane yes, reason may be that to my understanding, `apt-get remove` shouldn't  remove user-created / modified files (possibly systemd unit files fall in that category). But it's surprising that after a re-install, it's not automatically un-masking the docker.socket.

And yes, systemd not showing a useful warning/error is bad

**Comment by elifarley** [comment]
I've not changed any of the unit files, so apt-get should have noticed this and removed them (at least ArchLinux's package manager, Pacman, does it).

Could it be a bug on apt-get itself or a misconfiguration on Docker's package?

**Comment by thaJeztah** [comment]
> Could it be a bug on apt-get itself or a misconfiguration on Docker's package?

I had a look in the configuration used to build the .deb packages, but I see no explicit mention of things to remove / not remove; https://github.com/docker/docker/tree/master/hack/make/.build-deb

@tianon any idea if this is under our control, or something apt-get does by itself?

**Comment by ahawkins** [comment]
Is this possibly related to #23793?

**Comment by gregdurham** [comment]
I am having this same issue on centos 7 "docker-engine-1.12.0-1.el7.centos.x86_64" where it worked properly on "docker-engine-1.11.2-1.el7.centos.x86_64"

**Comment by thaJeztah** [comment]
@gregdurham did you make modifications to the unit file, or using a drop-in file? Docker 1.12 on CentOS no longer uses socket activation, so you need to remove the `-H fd://` from the systemd unit file

**Comment by ashneo76** [comment]
I have this on a CentOS 7:

```
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target

[Service]
Type=notify
# the default is not to use systemd for cgroups because the delegate issues still
# exists and systemd currently does not support the cgroup feature set required
# for containers run by docker
ExecStart=/usr/bin/dockerd
ExecReload=/bin/kill -s HUP $MAINPID
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
# Uncomment TasksMax if your systemd version supports it.
# Only systemd 226 and above support this version.
#TasksMax=infinity
TimeoutStartSec=0
# set delegate yes so that systemd does not reset the cgroups of docker containers
Delegate=yes
# kill only the docker process, not all processes in the cgroup
KillMode=process

[Install]
WantedBy=multi-user.target
```

**Comment by ashneo76** [comment]
Further debugging: `dockerd` works just fine. This only fails when starting via systemd.

**Comment by ashneo76** [comment]
Further digging revealed the following in: `/etc/systemd/system/docker.service.d/docker_options.conf`
```
[Service]
EnvironmentFile=-/etc/sysconfig/docker
ExecStart=
ExecStart=/usr/bin/docker daemon -H fd:// $INSECURE_REGISTRY
```

Perhaps a left over of an older docker installation.

Hopefully this helps.

**Comment by thaJeztah** [comment]
@ashneo76 that doesn't look like a unit file from our packages; did you / do you have the Red Hat fork of Docker installed? I think they distribute a unit file that looks like that

**Comment by thaJeztah** [comment]
@ashneo76 ignore my comment; I missed that's not your main unit file, but a drop in

**Comment by thaJeztah** [comment]
@ashneo76 you can change that drop-in file, change `docker daemon` to `dockerd` and remove `-H fd://`

**Comment by ashneo76** [comment]
Yes. That is a drop-in file. I think a leftover from the CentOS docker package. I just removed the file and it started working.

**Comment by ashneo76** [comment]
The only way for me to find it was via: `systemctl status docker`

**Comment by upccup** [comment]
@ashneo76 @thaJeztah maybe you can try this 
```
ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock
```

**Comment by dailyherold** [comment]
@thaJeztah your comment, "Docker 1.12 on CentOS no longer uses socket activation", and suggestion on removing `-H fd://` worked for me! Thank you very much. Curious though if that bit of wisdom is documented anywhere? I searched the release notes, saw the client daemon split #20639 (another recommendation of yours here), but didn't see any other good leads to your solution. 

`dockerd` [docs](https://docs.docker.com/engine/reference/commandline/dockerd/) has a wealth of info on the systemd config options, but don't see anything related to your tip apart from the solid socket activation [article link](http://0pointer.de/blog/projects/socket-activation.html) which I'm still processing and didn't see your tip either. I then thought it might be a RedHat change, and my google fu might not be strong today, but didn't find anything conclusive. I also have seen all the socket removal tickets that were closed with `1.12` GA, but most of the remnant problems are people with drop-ins they forgot about.

I'd love to help out and add a note into any documentation (been wanting to contribute for a while now) if you agree it should be there. Thanks!

**Comment by lansheng228** [comment]
docker 1.12 

sudo vim /etc/systemd/system/docker.service.d/override.conf

[Service]
ExecStart=
ExecStart=/usr/bin/dockerd --storage-driver=overlay --bip=10.10.30.40/16


run  ok.

**Comment by dailyherold** [comment]
This issue was started under an Ubuntu context, so I don't want to derail the discussion (which I probably already did, apologies). Let's keep it focused on Ubuntu. I found some related Redhat/Centos discussion going on here: https://github.com/docker/docker/issues/25098#issuecomment-236821808

**Comment by centminmod** [comment]
as outlined above for centos 7.2, removing `-H fd://` from `/etc/systemd/system/docker.service.d/docker.conf` fixed it for me too

**Comment by brunofitas** [comment]
I came across the same problem on centos 7.2. Removing the ``` -H fd:// ``` does fix the problem and docker runs fine.
Yet, my problem is a bit different, since I'm trying to install DC/OS and the installer keeps changing the file.
I'm following [this instructions](https://dcos.io/docs/1.7/administration/installing/custom/system-requirements/install-docker-centos/) and the installation fails every time.
Here's the output for ``` systemctl status docker ```

```
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─override.conf
   Active: failed (Result: exit-code) since Qua 2016-08-10 21:10:20 BST; 2min 47s ago
     Docs: https://docs.docker.com
  Process: 2049 ExecStart=/usr/bin/docker daemon --storage-driver=overlay -H fd:// (code=exited, status=1/FAILURE)
 Main PID: 2049 (code=exited, status=1/FAILURE)

Ago 10 21:10:19 mst01 systemd[1]: Starting Docker Application Container Engine...
Ago 10 21:10:20 mst01 docker[2049]: time="2016-08-10T21:10:20.142801096+01:00" level=fatal msg="no sockets found via socket activation: make sure the service was started by systemd"
Ago 10 21:10:20 mst01 systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Ago 10 21:10:20 mst01 systemd[1]: Failed to start Docker Application Container Engine.
Ago 10 21:10:20 mst01 systemd[1]: Unit docker.service entered failed state.
Ago 10 21:10:20 mst01 systemd[1]: docker.service failed.
```
Output for ```systemctl status docker.socket```

```
● docker.socket
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
```

Here's the result file, after DC/OS changing it back ( adding back the ``` -H fd:// ```)
```
[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon --storage-driver=overlay -H fd://
```

I'm not sure what to do... any help would be much appreciated.
Thanks

**Comment by thaJeztah** [comment]
@brunofitas step 7. in those instructions change that; just modify those instructions and run them without the `-H fd://`

**Comment by brunofitas** [comment]
@thaJeztah Thanks for your reply.
I've done that before, it didn't work. I've done it again, this time saving the output.

On every mode, before DC/OS:

**$ vi /etc/systemd/system/docker.service.d/override.conf**
```
[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon --storage-driver=overlay
```
**$ yum list installed | grep docker**
```
docker-engine.x86_64                 1.12.0-1.el7.centos             @dockerrepo
docker-engine-selinux.noarch         1.12.0-1.el7.centos             @dockerrepo
```

```
[root@mst01 ~]# systemctl daemon-reload
[root@mst01 ~]#  systemctl start docker
[root@mst01 ~]# systemctl enable docker
Created symlink from /etc/systemd/system/multi-user.target.wants/docker.service to /usr/lib/systemd/system/docker.service.
```

Everything is ok, docker is running normally 

 **Installing DC/OS**

**Step01**
![dc01](https://cloud.githubusercontent.com/assets/698545/17569435/271a7fb2-5f40-11e6-9899-613be00bd510.png)
**Step02**
![dc02](https://cloud.githubusercontent.com/assets/698545/17569455/45ed5086-5f40-11e6-9f00-0d5c183a07e2.png)
**Step03**
![dc03](https://cloud.githubusercontent.com/assets/698545/17569461/4e39e150-5f40-11e6-9b0e-65859256abf8.png)

**Step04**
![dc044](https://cloud.githubusercontent.com/assets/698545/17569468/53aefeea-5f40-11e6-948c-354c239ff51e.png)

**Ouput from 1 node ( the others are the same**)

```
Connection to 192.168.28.21 closed.

Starting DC/OS Install Process

Running preflight checks

Checking if DC/OS is already installed: PASS (Not installed)

PASS Is SELinux disabled?

Checking if docker is installed and in PATH: PASS 

Checking docker version requirement (>= 1.6): PASS (1.12.0)

Checking if curl is installed and in PATH: PASS 

Checking if bash is installed and in PATH: PASS 

Checking if ping is installed and in PATH: PASS 

Checking if tar is installed and in PATH: PASS 

Checking if xz is installed and in PATH: PASS 

Checking if unzip is installed and in PATH: PASS 

Checking if ipset is installed and in PATH: PASS 

Checking if systemd-notify is installed and in PATH: PASS 

Checking if systemd is installed and in PATH: PASS 

Checking systemd version requirement (>= 200): PASS (219)

Checking if group 'nogroup' exists: PASS 

Checking if port 80 (required by mesos-ui) is in use: PASS 

Checking if port 53 (required by mesos-dns) is in use: PASS 

Checking if port 15055 (required by dcos-history) is in use: PASS 

Checking if port 5050 (required by mesos-master) is in use: PASS 

Checking if port 2181 (required by zookeeper) is in use: PASS 

Checking if port 8080 (required by marathon) is in use: PASS 

Checking if port 3888 (required by zookeeper) is in use: PASS 

Checking if port 8181 (required by exhibitor) is in use: PASS 

Checking if port 8123 (required by mesos-dns) is in use: PASS 

Checking Docker is configured with a production storage driver: WARNING: bridge-nf-call-iptables is disabled

WARNING: bridge-nf-call-ip6tables is disabled

PASS (overlay)

Creating directories under /etc/mesosphere

Creating role file for slave

Configuring DC/OS

Setting and starting DC/OS

Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.

192.168.28.21:22
```
$ systemctl status docker.service 
```
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─override.conf
   Active: failed (Result: exit-code) since Qua 2016-08-10 21:10:18 BST; 3min 29s ago
     Docs: https://docs.docker.com
  Process: 13855 ExecStart=/usr/bin/docker daemon --storage-driver=overlay -H fd:// (code=exited, status=1/FAILURE)
 Main PID: 13855 (code=exited, status=1/FAILURE)

Ago 10 21:10:18 node02 systemd[1]: Starting Docker Application Container Engine...
Ago 10 21:10:18 node02 docker[13855]: time="2016-08-10T21:10:18.663546586+01:00" level=fatal msg="no sockets found via socket activation: make sure the service was started by systemd"
Ago 10 21:10:18 node02 systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Ago 10 21:10:18 node02 systemd[1]: Failed to start Docker Application Container Engine.
Ago 10 21:10:18 node02 systemd[1]: Unit docker.service entered failed state.
Ago 10 21:10:18 node02 systemd[1]: docker.service failed.
```

On every mode, after DC/OS:

```
[root@mst02 ~]# docker ps
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**$ vi /etc/systemd/system/docker.service.d/override.conf**
``` 
[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon --storage-driver=overlay -H fd://
```

See how the file changed back...

**Comment by thaJeztah** [comment]
Looks like something to be fixed in their installer. Not sure if systemd loads overrides in alphabetical order, but may be worth a try adding a `zz-override.conf` with the correct content as a workaround?

**Comment by brunofitas** [comment]
I was speaking to DC/OS dev team, and they told me docker 1.12.0 is not supported.
The DC/OS installer has this line on it
```
yum install -y docker-engine
```
which installs docker 1.12.0, when they should have something like
```
yum install -y docker-engine-selinux-1.11.0 && yum install -y docker-engine-1.11.0
```
This has been fixed on version 1.8.
@thaJeztah Thanks for your help.

**Comment by thaJeztah** [comment]
@brunofitas thanks for the update! If you're still discussing changes with them, I suggest to use 1.11.2 (which contains various bug fixes since 1.11.0)

**Comment by azhagarasu** [comment]
@thaJeztah changing `docker daemon` to `dockerd ` and removing `-H fd://` worked. But could you explain what is the function of `-H fd://` ? 

I created a dropin file to change Docker Root Dir. Before it was like,

`ExecStart=/usr/bin/docker daemon -H fd:// --graph="/mnt/block_drive/docker" --storage-driver=devicemapper`

Now it is,

`ExecStart=/usr/bin/dockerd --graph="/mnt/block_drive/docker" --storage-driver=devicemapper`

What is the impact of altering this? Thanks.

**Comment by thaJeztah** [comment]
@azhagarasu the `-H fd://` is only used for "socket activation" (basically, it allows connecting to `/var/run/docker.sock` and docker is automatically started if it's not running), however, is the `docker.socket` service isn't running, that doesn't work. The feature caused issues on RPM based installs, so was removed from the systemd unit files on those systems.

In practice, removing `-H fd://` won't make any difference, unless you were using socket activation

**Comment by azhagarasu** [comment]
@thaJeztah Thanks!

**Comment by tonistiigi** [comment]
@elifarley Can we close this? Seems your issue is not in our control and all other people with yum issues got their problems solved.

**Comment by tonistiigi** [comment]
Closing. Note that socket activation was removed in rpm installs in `v1.12` so this error is expected if `-H fd://` is used inside a custom unit file in these systems.

**Comment by man2nainwal** [comment]
Why --storage-driver=overlay is not working with Centos7 in virtual system. I remove that statement then it's start working.

cat > /etc/systemd/system/docker.service.d/override.conf << 'EOF'
[Service] 
ExecStart= 
ExecStart=/usr/bin/dockerd --storage-driver=overlay --insecure-registry 172.30.0.0/16
EOF

Could you please explain about this option --storage driver ?

**Comment by mdzidic** [comment]
If You upgraded to Docker v1.12.2 from older version and it won't start service, this helped me:
`rm /etc/systemd/system/docker.service.d/docker-defaults.conf`

**Comment by dmilind** [comment]
Here How I solved this issue On centos 7. 
In  /etc/systemd/system/docker.service.d/override.conf 
ExecStart=
ExecStart=/usr/bin/docker daemon --storage-driver=overlay -H fd://
I replaced docker daemon by dockerd and removed -H fd:// then restarted the docker service.

**Comment by thaJeztah** [comment]
@dmilind you need to reload the configuration with systemd; `sudo systemctl daemon-reload`, then restart the service `sudo systemctl restart docker` (see https://github.com/docker/docker/releases/tag/v1.12.5)

**Comment by dmilind** [comment]
@thaJeztah That solved my issue. Thank you

**Comment by e-user** [comment]
Even though this appears to be an old issue, if anyone else comes here they should know that adding `-H unix://` will actually allow docker to start because that's what provides `/var/lib/docker.sock` and is the default in absence of any `-H` option.

**Comment by Redsandro** [comment]
I also had this problem just now after an update.

Removing `-H fd://` from my configuration that used to work, fixed the issue. Not sure why.

**Comment by reloxx13** [comment]
@Redsandro but this kills `docker ps` (and more) on rasbian.

**Comment by Redsandro** [comment]
@reloxx13 Hmm, perhaps I was too quick to respond.

My docker service was having issues. Google brought me here. @e-user pointed me in the right direction and now everything works again.

* Ubuntu 18.04
* Docker version 18.09.0, build 4d60db4
* I have no idea what I am doing, but I got it working again. I don't know what `-H fd://` does, why it was there, and why it suddenly stopped working.

**Comment by Redsandro** [comment]
@reloxx13 you are right though. I now have this situation:

* Using `-H fd://` I cannot `service start docker` anymore.
* Using `-H unix://` I can start the service, but I cannot `docker ps` anymore.

So with the second one, at least all my containers are running, but command line control has become crippled. I feel like I'm keeping a nuclear power plant running so people don't complain, but I can't control it anymore. And I still don't know what I'm doing. Hmm, I better stop with this analogy or I get nightmares.

**Comment by wumpz** [comment]
Replacing `-H fd://` with `-H unix://` worked for me. (Don't forget to reload the service daemon :))

**Comment by reloxx13** [comment]
i use this and everything is fine:

https://github.com/docker/for-linux/issues/476#issuecomment-437423363

**Comment by thaJeztah** [comment]
If you're running on Docker 18.09, this is being tracked through https://github.com/docker/for-linux/issues/476 and https://github.com/moby/moby/issues/38119, and will be fixed through https://github.com/docker/docker-ce-packaging/pull/257 as part of the 18.09.1 patch release, which should become available soon.

**Comment by thistleknot** [comment]
this did it for me
https://stackoverflow.com/questions/65213831/failed-to-start-daemon-error-initializing-network-controller-error-creating-de
firewall-cmd --zone=docker --change-interface=docker0
