### ISSUE TITLE
Multiple OCI Runtime Support

### ISSUE THREAD

**Issue by mlaventure** [docker/docker#22845]
# Goals

Now that the actual creation of a container is handled by `runc` via `containerd`, it should technically be possible to swap out `runc` for any other binary providing they are exposing the same command line interface and accepting an OCI bundle. This could allow to use docker to manage more than containers (e.g. vms) and allow for users to use slightly different implementations than runc with added features.

# Suggested Implementation

The proposed implementation would require users to register the runtimes they want to be available with the daemon. Once this is done, users would be able to select which runtime to use per container every time they start them. If no runtime are specified, the default one, which would ship with the docker official installation, will be used.

It should be possible for the user to define which runtime should be the `“default”` one, meaning which one is to be used if none is specified at container creation/start.

# Runtime Registration

In order to expose available runtime to docker user, it is proposed to first have them register the available runtimes through docker either by a command line switch or via its configuration file (`daemon.json`).

**Note**: the `“default”` name would be always reserved and mapped to the runtime coming with the docker package.

## Command Line

The proposed switch option would be `--add-runtime` followed by a tuple `<runtime-name>=<runtime-path>`.

e.g. `docker daemon --add-runtime ”oci=/usr/local/sbin/runc” --add-runtime ”vm=/usr/local/bin/vm-manager”`

## Daemon Configuration

The daemon.json configuration would accept a new runtimes field as follow:

```json
{
  "runtimes": {
    "oci": {
      "path": "/usr/bin/docker-runc",
      "runtimeArgs": [
        "--debug"
      ]
    },
    "vm": {
      "path": "/usr/local/bin/vm-manager",
      "runtimeArgs": [
        "--debug"
      ]
    }
  }
}
```

This format as the ability to also allow specifying extra runtime arguments compared to the command line version.

## Runtimes list

A list of available runtimes would be returned via the `info` endpoint (and displayed by `docker info`). That list would only include the runtimes name/alias (i.e. only the map keys are returned).

# Default Runtime

To allow the user to define a different “default” runtime (as a separate attribute, not as a name). The following interfaces could be used.

## Command Line

A new `--default-runtime=”<runtime-name>”` would be added. `<runtime-name>` would have to be one of the name added via the `--add-runtime` flag described above. To revert to the runtime shipped by docker, a user would simply have to pass the value `“default”` to the flag.

e.g. `docker daemon --add-runtime ”oci=/usr/local/sbin/runc” --add-runtime ”vm=/usr/local/bin/vm-manager” --default-runtime="vm"`

## Daemon Configuration

The default runtime would be stored in a new `“default-runtime”` attribute in `daemon.json`:

```json
{
  "defaultRuntime": "vm",
  "runtimes": {
    "oci": {
      "path": "/usr/bin/docker-runc",
      "runtimeArgs": [
        "--debug"
      ]
    },
    "vm": {
      "path": "/usr/local/bin/vm-manager",
      "runtimeArgs": [
        "--debug"
      ]
    }
  }
}
```

# Container runtime selection

Explicitly selecting a runtime at container creation would be done using the new  `--runtime` flag:

`docker create <create-options> --runtime=vm <container-name>`
or
`docker run <run-options> --runtime=vm <container-name>`

# Container State

## Option 1: Included

The last used runtime would be stored on disk within the container config (the whole tuple `<name>:<path>`). Meaning, the next time the container is started without a `--add-runtime` argument, the old value would be used. 

In the case where the runtime is no longer registered with the daemon, an error shall be displayed so the user can correctly specify a correct runtime.

This option would also allow to specify this flag at container creation instead (i.e. `docker create`) to be used as the default every time a container get started.

## Option 2: Not Included

If we choose not to persist that choice on the disk, a next start of the container would revert to the default runtime if no runtime is specified

# Limitations

This added options would not be available on Windows

**edit**: Fix usage example for `--runtime`
**edit**: renamed `--runtime` to `--add-runtime`
**edit**: fixed example for selecting runtime, it can only be done during `create` or `run` operations

**Comment by thaJeztah** [comment]
Given that dockerd does not directly communicate with these runtimes, would it make sense to make this a configuration for containerd, and have containerd expose which runtimes it knows? I.e., dockerd can request available runtimes from containerd. (Perhaps I'm wrong, just thinking out loud)

**Comment by mlaventure** [comment]
@thaJeztah You're actually right, containerd will have to be modified to allow handling several runtimes at once.

When I initially wrote this, I wasn't allowing for runtime to be changed per container run, but only daemon wide (which is what containerd support atm). I didn't realize the impact when I changed it.

However, the list of runtimes would still need to be stored on the `docker` side as `dockerd` is the one starting `containerd` in our default setup and thus must pass it the needed parameters. This gives a single configuration entrypoint for users instead of having them configure `containerd` **and** `dockerd`.

If/When `containerd` get support for a config file, I guess we could then have `dockerd` generate the file and pass it to containerd instead, but it's not the case atm.

**Comment by thaJeztah** [comment]
Yes, hence me thinking that dockerd could request that information from containerd :wink: (so that you don't need to configure in two places). You're right about containerd not having a configuration file though

**Comment by WeiZhang555** [comment]
I'm also wondering if it will be more appropriate to put runtime related setting in containerd, or docker command line will be a little bit complicated. For example:
```
 // start containerd with specified socket, using runc as default runtime with some custom runtime args.
$ containerd --l "unix:///some/containerd.sock"  -r "runc" --runtime-args "xxxx"  
// support per-container runtime API in containerd, e.g.
$ ctr --runtime "vm-manager" --runtime-args "xxxxx" containers start ....

// if the API is ready, then we can add commandline args to docker
$ dockerd --containerd "unix:///some/containerd.sock"  .....
$ docker run --runtime "vm-manager" --runtime-args "xxxxx"  -d busybox top
```

It's true that we need to manually start the containerd, but I think this can be regarded as an advanced feature, besides that the docker command will be simplier.  

Just my 2 cents. :smile:

**Comment by HackToday** [comment]
it seems very interesting topic for multiple OCI support, but this support should explore possibilities like impact of container-cluster management(swarm, k8s, mesos),  different OCI container migration, life-cycle similities, and user cases, Perhaps OCI spec have covered that, but address those use cases in this spec could help other understood it more.

**Comment by duglin** [comment]
I think @thaJeztah's comment about configuring containerd instead of dockerd makes a lot of sense. Imagine we get to the point where containerd is replaceable - one replacement may not even have the notion of a separate runc-like executable, so having dockerd itself trying to configure something that may not exist or is an impl detail of the containerd choice doesn't make sense.

**Comment by thaJeztah** [comment]
> Perhaps OCI spec have covered that, but address those use cases in this spec could help other understood it more.

@HackToday For Swarm, I guess Swarm could see which runtimes are supported on a node, and that could be used as a constraint when scheduling a container

**Comment by sqleejan** [comment]
LGTM
