### ISSUE TITLE
Connectivity issues

### ISSUE THREAD

**Issue by martinvw** [docker/docker#22841]
My previous installation had issues with the connectivity timeouts from the docker-engine to, since I was running ubuntu 14.04 I saw it as good moment to upgrade. But now I upgraded I still have the same problems. 

A docker pull ends in a timeout 10 minutes later.

**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:43:49 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:43:49 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.11.1
Storage Driver: zfs
 Zpool: meru
 Zpool Health: ONLINE
 Parent Dataset: meru/docker
 Space Used By Parent: 96817152
 Space Available: 115362865152
 Parent Quota: no
 Compression: on
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.0-22-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 15.55 GiB
Name: elbrus
ID: 4TS7:FHWG:RHDF:USIP:OP26:S5P2:3BGT:USEH:35OI:VVZ4:EC5L:62P5
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 14
 Goroutines: 33
 System Time: 2016-05-19T20:53:05.346482644+02:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
The machine is a physical machine with two network adapters on-board one Intel one Realtek.

**Steps to reproduce the issue:**
1. Installed Ubuntu 16.04 from scratch
2. Installed some other software zfs/crashplan/iscs-itarget (I disabled both of them as a test)
3. Installed docker according to the guide https://docs.docker.com/engine/installation/linux/ubuntulinux/
4. Added my user to the docker group
5. Run `docker run hello-world`

**Describe the results you received:**
Unable to find image 'hello-world:latest' locally
   **very long time later**
docker: Error response from daemon: Get https://registry-1.docker.io/v2/library/hello-world/manifests/latest: read tcp 192.168.1.20:41998->52.3.83.159:443: read: connection timed out.
See 'docker run --help'.

**The debug log states:**
```
DEBU[0004] Calling POST /v1.23/containers/create
DEBU[0004] form data: {"AttachStderr":true,"AttachStdin":false,"AttachStdout":true,"Cmd":null,"Domainname":"","Entrypoint":null,"Env":[],"HostConfig":{"AutoRemove":false,"Binds":null,"BlkioBps":0,"BlkioDeviceReadBps":null,"BlkioDeviceReadIOps":null,"BlkioDeviceWriteBps":null,"BlkioDeviceWriteIOps":null,"BlkioIOps":0,"BlkioWeight":0,"BlkioWeightDevice":null,"CapAdd":null,"CapDrop":null,"Cgroup":"","CgroupParent":"","ConsoleSize":[0,0],"ContainerIDFile":"","CpuCount":0,"CpuPercent":0,"CpuPeriod":0,"CpuQuota":0,"CpuShares":0,"CpusetCpus":"","CpusetMems":"","Devices":[],"DiskQuota":0,"Dns":[],"DnsOptions":[],"DnsSearch":[],"ExtraHosts":null,"GroupAdd":null,"IpcMode":"","Isolation":"","KernelMemory":0,"Links":null,"LogConfig":{"Config":{},"Type":""},"Memory":0,"MemoryReservation":0,"MemorySwap":0,"MemorySwappiness":-1,"NetworkMode":"default","OomKillDisable":false,"OomScoreAdj":0,"PidMode":"","PidsLimit":0,"PortBindings":{},"Privileged":false,"PublishAllPorts":false,"ReadonlyRootfs":false,"RestartPolicy":{"MaximumRetryCount":0,"Name":"no"},"SandboxSize":0,"SecurityOpt":null,"ShmSize":0,"StorageOpt":null,"UTSMode":"","Ulimits":null,"UsernsMode":"","VolumeDriver":"","VolumesFrom":null},"Hostname":"","Image":"hello-world","Labels":{},"NetworkingConfig":{"EndpointsConfig":{}},"OnBuild":null,"OpenStdin":false,"StdinOnce":false,"Tty":false,"User":"","Volumes":{},"WorkingDir":""}
ERRO[0004] Handler for POST /v1.23/containers/create returned error: No such image: hello-world:latest
DEBU[0004] Calling GET /v1.23/info
DEBU[0004] [zfs] zpool get all -p meru
DEBU[0004] Calling POST /v1.23/images/create?fromImage=hello-world&tag=latest
DEBU[0004] Trying to pull hello-world from https://registry-1.docker.io v2
DEBU[0005] Increasing token expiration to: 60 seconds
ERRO[1016] Error trying v2 registry: Get https://registry-1.docker.io/v2/library/hello-world/manifests/latest: read tcp 192.168.1.20:42136->52.3.83.159:443: read: connection timed out
ERRO[1016] Attempting next endpoint for pull after error: Get https://registry-1.docker.io/v2/library/hello-world/manifests/latest: read tcp 192.168.1.20:42136->52.3.83.159:443: read: connection timed out
DEBU[1016] Skipping v1 endpoint https://index.docker.io because v2 registry was detected
ERRO[1016] Handler for POST /v1.23/images/create returned error: Get https://registry-1.docker.io/v2/library/hello-world/manifests/latest: read tcp 192.168.1.20:42136->52.3.83.159:443: read: connection timed out
```

**Describe the results you expected:**
Hello from Docker.
This message shows that your installation appears to be working correctly.

**Additional information you deem important (e.g. issue happens only occasionally):**
What surprises me most as this this same problem occurs with the fresh install, which would almost suggest hardware dependent troubles or something. And I do not use a proxy of any kind. The only special thing might be some NAT.

**Comment by martinvw** [comment]
BTW the installation of Ubuntu 14 did not use the zfs storage driver, so I'm als not considering that as a likely cause.

**Comment by martinvw** [comment]
To make things even more complicated I have an (old) windows machine in the same network running virtualbox with Ubuntu xenial. There it works perfectly :(

**Comment by martinvw** [comment]
Hooray my problem is getting somewhere I caused it by increasing the MTU on my network adapters, the outside world isnot able to handle my higher MTU so I should convert it somewhere if I want to enable it. Thanks for reading my issue, I'll close it for now.

**Comment by thaJeztah** [comment]
oh! good to hear; I was actually thinking if it could be MTU related, should've posted that when I had the thought :blush:
