### ISSUE TITLE
How to determine dangling state of image via remote API

### ISSUE THREAD

**Issue by otbe** [docker/docker#22859]
Hi everyone,

posted this question already on gitter but did not get a response. So maybe this is the right place for me :)

I have an image ID and want to determine if its dangling or not. Is there any way to do that via ```GET /images/{id}/json```? 
There is no extra ```dangling``` property in the response json, but can I derive it from something other?

My current workaround is to query all images with a specific ```filter``` for dangling images and compare the response to my input ID. Not an ideal solution I think.

Thanks!

**Comment by justincormack** [comment]
I don't think you can get this, it is a property of the image store not the images themselves, ie whether the image is a head, so you need to do it indirectly like you are.

**Comment by otbe** [comment]
Sounds reasonable. Thank you for explanation!

**Comment by thaJeztah** [comment]
@justincormack is right that it's not a "property" of an image, but you can use a *filter* to find all images that are dangling; see the "filters" in this section; https://docs.docker.com/engine/reference/api/docker_remote_api_v1.23/#list-images

**Comment by otbe** [comment]
@thaJeztah 
Thank you. Thats what I call "my current workaround is to query all images with a specific filter for dangling images" :)

**Comment by thaJeztah** [comment]
Oh! I should learn to read :wink:
