### ISSUE TITLE
containers failed to start(Aleady active)

### ISSUE THREAD

**Issue by anannaya** [docker/docker#22851]
Hi,

Issue: Container failed to start once i restart the docker service.
Steps to reproduce:
I am using below docker options to run my configcontainer.

#docker run -t --privileged --restart=unless-stopped --net=host -v /opt/swrepo/vmtools.conf:/opt/swrepo/vmtools.conf -v /var/run/docker.sock:/var/run/docker.sock -v /etc/sysconfig/network-scripts:/etc/sysconfig/network-scripts -v /etc/sysconfig/docker:/etc/sysconfig/docker -v /root/.ssh:/host/ssh --name configcontainer 10.43.44.217:5000/config_configurator

#systemctl restart docker

THis issue is seen 80% of the time when i restart the docker service. Attcahed the snapshot and /var/log/messages from the RHEL7.2 host.
![image](https://cloud.githubusercontent.com/assets/19487932/15423811/de729d82-1e9c-11e6-9e11-2861fb8be810.png)

[AleadyActiveContainerIssue.txt](https://github.com/docker/docker/files/274272/AleadyActiveContainerIssue.txt)

**Comment by thaJeztah** [comment]
Can you provide the output of `docker version` and `docker info`, also might be worth checking the daemon logs to see if there's anything interesting in there

**Comment by anannaya** [comment]
[root@dockerhost ~]# docker version 
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64
[root@dockerhost ~]# 

[root@dockerhost ~]# docker info
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 1.11.1
Storage Driver: devicemapper
 Pool Name: docker-253:0-135083487-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.095 GB
 Data Space Total: 107.4 GB
 Data Space Available: 47.82 GB
 Metadata Space Used: 2.544 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.64 GiB
Name: dockerhost
ID: LVR4:JHJD:7K6N:QAWZ:WPYI:NMLV:2Y3N:AEZ6:EQ37:5STY:VYQT:76KT
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
[root@dockerhost ~]#

**Comment by anannaya** [comment]
Initially i was suspecting that issue might be because of restart option used for the container(wait call from code).  I also tried using without restart option. Same issue seen. Attached the daemon log

**Comment by anannaya** [comment]
[daemon.log.txt](https://github.com/docker/docker/files/274668/daemon.log.txt)

**Comment by cpuguy83** [comment]
Yes, I've seen this. Seems like the state is out of sync, it may already be fixed as there was another issue with state sync that is indeed fixed.... but this is hard to reproduce until you actually get the error.

**Comment by anannaya** [comment]
I am able to reproduce 8/10 attempts....As i am using latest docker version..will this be fixed in future releases?

**Comment by cpuguy83** [comment]
@anannaya You can test by using the current master branch of containerd/containerd-shim

**Comment by anannaya** [comment]
I think you are referring to https://github.com/docker/containerd/commit/b68bc651a8c2fda84f09e25a258557659ecb8c03

Looks like mine issue is different. and moreover i am seeing this issue on particularly on only one container out of few more container on the same Host.

**Comment by anannaya** [comment]
Ok..Issue will be fixed in 1.11.2? but meanwhile i am able figure out whats wrong with my container.
Actually i was using SIGINT in my  entry point script. I removed it now the issue is not reproducible.

 
![image](https://cloud.githubusercontent.com/assets/19487932/15498233/678fa156-21bc-11e6-9a39-0f697cbc9ce6.png)

**Comment by tonistiigi** [comment]
Closing, fix for #22913 was also included for v1.12 in #23213
