### ISSUE TITLE
oci runtime error: could not synchronise with container process: could not create session key: disk quota exceeded

### ISSUE THREAD

**Issue by dchen1107** [docker/docker#22865]
Output of docker version:
```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:20:46 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:20:46 2016
 OS/Arch:      linux/amd64
```

Output of docker info:

```
# docker info
Containers: 555
 Running: 197
 Paused: 0
 Stopped: 358
Images: 109
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1242
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 7 (wheezy)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.324 GiB
Name: e2e-test-dawnchen-minion-18ah
ID: UZMP:J3YN:4AHS:RHBP:SSQH:EKFD:PRQR:HGFN:DRPL:JWZR:RJZL:TEQR
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

Additional environment details (AWS, VirtualBox, physical, etc.):

Just a standard Kubernetes node with docker 1.11.1

Steps to reproduce the issue:

I just simply run the command and quickly hit the cap (~200)
```
for i in {1..500}; do echo $i; docker run -d --name container$i gcr.io/google_containers/pause:2.0; done
```
The error message:

```
1
410d715441504b1e93d77cdec531b338631fcafd637215376df2e8e65d27484e
...
ec5255dc7d1b69624f9f3cc4687708286cc7aefb6b3cd32024d0e41701678337
177
ab99e85ac7b67204ba0c3ff0214dd319bd79fcb06285925c936614a43aa34416
178
dfddfc1ac3bc43625616677385ad68137295af69bfd7274691448476f4cbe675
179
741e2d5708b95469afa65967fafaaf04175ae792eaf6fb3284a5209dcfd71a1c
180
90242513e32aa465ce8fe0df5ab79a0bcd3af4cb32723470f589bff943748c30
181
d77c7e9f06724b1aee0e98f587dba04212a7449723786c5ea7a5bdf623896a38
182
e5631849be2cbe9ced9d463cd00267f8185a9df776f40e9015825a899f755028
docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: could not synchronise with container process: could not create session key: disk quota exceeded".
183
e542d7ed3cdfe61add072d47abc23f41f2386ea4df82491415c76cb4ed168326
docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: could not synchronise with container process: could not create session key: disk quota exceeded".
184
cc6034b216e191242dfa825d37c5b514ff5133e26dc00c3fa1ea8c6b9fbb5871
docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: could not synchronise with container process: could not create session key: disk quota exceeded".
185
53c0b3d65d9f1b6d87cd385cf7d90d79983b518dd4f5d57779e615e9a23d4220
docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: could not synchronise with container process: could not create session key: disk quota exceeded".
186
8f74f50ea15dee4dd286189de828ec2333644e1552d5436976ad0e458da5604d
docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: could not synchronise with container process: could not create session key: disk quota exceeded".
187
a7ed9ce29299e70414390490b4f8c103b284d12ef7e85d20efa182211b356a1f
docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: could not synchronise with container process: could not create session key: disk quota exceeded".
...
500
237e185ab8b5b0774b09c058bed74f0331da8a1c999ec614bac69ad98106bf77
docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: could not synchronise with container process: could not create session key: disk quota exceeded".
```

I believe we are hitting at this issue: https://github.com/opencontainers/runc/issues/726, but an attempt solution (https://github.com/opencontainers/runc/pull/727) was closed and the suggestion is the issue should be handled at the higher layer, which I believe it should be docker engine here.

**Comment by dchen1107** [comment]
cc/ @kubernetes/goog-node

**Comment by crosbymichael** [comment]
@dchen1107 why do you think docker should set this setting?  This is a security feature, shouldn't it be left up to the admin? How would we know what the correct number is that should be set?

**Comment by dchen1107** [comment]
Honestly I didn't think docker should set this configuration. But from the release note of docker 1.11.1, there is no such cap being announced, which makes me think docker as an daemon want to handle this silently, gracefully, and automatically, instead like what we are having today: the user is bit badly at runtime then has to dig into the source code deeply. 

Shouldn't at least this kind of change which requires extra attention from the admin should be announced through release note? Along with the suggestion on how to updates such setting? And also included in docker info output?

**Comment by justincormack** [comment]
Curious about which distros have a low limit as the default for `/proc/sys/kernel/keys/root_maxkeys` seems to be 1000000 unless you override it, eg using a stock recent kernel, or Ubuntu 15.10 or Centos 7.2, but it is only 200 on Debian Jessie. I think as it is just a few distros that change this we should just change the documentation.

**Comment by dchen1107** [comment]
Yes, it is Debian. I checked both Wheezy and Jessie, both are 200 by default. My co-worker checked on trusty 14.04.4, the default value is also 200. Anyway I am going to bump the default value to bigger number, but thought this is a behavior change for user upgrading to 1.11 release, we should document it.

**Comment by justincormack** [comment]
I think it may have changed in more recent kernels, as I couldn't find anywhere where Debian was setting it specifically.

**Comment by timstclair** [comment]
I was looking at the wrong value on the trusty instance. `maxkeys` was 200, but `root_maxkeys` was 1000000

**Comment by justincormack** [comment]
Added a check for this in the check config script https://github.com/docker/docker/pull/22867

**Comment by crosbymichael** [comment]
I think we should just set max root keys to 1000000 in docker if its not set by the distro.  What do you think?

**Comment by cyphar** [comment]
@crosbymichael I don't like that, because we're changing global distribution policy. There's almost certainly some side-effects -- I'd prefer if we made the keyring joining optional (as you mentioned in opencontainers/runc#818).

**Comment by morphyno** [comment]
I came across the same error message while attempting to launch 500 docker containers. I have set both root_maxkeys and maxkeys to 1000000 to no avail.
I'm curious if this issue existed in previous version of docker? Is there any other workarounds available?

**Comment by morphyno** [comment]
Below is output of "docker info"

`Containers: 500
 Running: 285
 Paused: 0
 Stopped: 215
Images: 12
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1020
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 3.16.0-30-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 20
Total Memory: 125.9 GiB
Name: UTraffic100
ID: Y2U3:57NC:NMBU:BYAE:PHRK:PRMF:ODUC:LR3I:KSOI:UKTT:XMLP:HVYD
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support`

**Comment by morphyno** [comment]
Interestingly, I updated to Ubuntu 16.04 and now I can get over 1000 containers. I'm also seeing the same limit you are seeing.

**Comment by crosbymichael** [comment]
@morphyno there are not other work arounds.  This is not exist in the prior versions but this change is a security measure allocating new session keys to the containers so they don't inherit the parents.  

16.04, atleast on my machine, already has 1m root keys as the max so that is why you are seeing that.

**Comment by crosbymichael** [comment]
@morphyno you also have to update `root_maxbytes` on your original system.  It looks common to allocate 25 bytes per key that should make your original system work. I updated my PR to do this if you want to check out the code 

https://github.com/docker/docker/pull/23182
