### ISSUE TITLE
[Proposal] Data management command

### ISSUE THREAD

**Issue by icecrime** [docker/docker#22871]
## Problem statement

One of the issues we hear about the most is how to reclaim disk space used by docker. I suggest to start small by adding a way to **understand and visualize** how disk space is used, before building additional support for managing this data.

## Possible solution

One simple idea would by to provide the equivalent of a `docker df`, which would show you:

- Space used by images (tagged versus untagged?)
- Space used by containers (running versus stopped?)
- Space used by volumes (referenced versus dangling?)

A natural evolution of that would be to offer one-liners to reclaim space consumed by unused images, dangling volumes, or stopped containers.

Ping @docker/core-maintainers: I'm interested to hear what you think!

**Comment by icecrime** [comment]
Other idea: space consumed in *other* (inactive) storage drivers (e.g., I'm using overlay, but I have images pulled as I was running aufs).

**Comment by coolljt0725** [comment]
How about this information show in `docker info`? Add a field in docker info something like
````
Space used:
   images:  20G
   containers: 10G
   volumes: 5G
````
but calculating the space used would take a long time, so it may make `docker info` slow

**Comment by thaJeztah** [comment]
@icecrime also see the discussion on this one; https://github.com/docker/docker/issues/22510

**Comment by thaJeztah** [comment]
> Space used by containers (running versus stopped?)

Would be interesting to see if we can find leftover files of containers that have actually been removed; I seem to remember this can happen if a container failed to be fully removed (filesystem in use). We should have something for that

**Comment by icecrime** [comment]
Another data point worth looking at: [grahame/wrfy](https://github.com/grahame/wrfy/) (cc @dmcgowan @tonistiigi @aaronlehmann @dnephin)

**Comment by dmcgowan** [comment]
> Space used by images (tagged versus untagged?)

This would likely need storage driver specific implementations to get accuracy here. Hard link usage across layers (such as overlay) make it tricky to show how much data could be cleaned up by removing untagged images. An initial step of getting the total usage would be useful then later expanding that to figuring out the real usage per layer, which would allow a better picture for what can be reclaimed through cleanup.

**Comment by mickep76** [comment]
Information when an image was last used is interesting for cleanup, since then you can cleanup least used first.
