### ISSUE TITLE
vim with ruby has problems installing plugins in docker

### ISSUE THREAD

**Issue by Jeansen** [docker/docker#22883]
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:16:22 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:16:22 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 11
 Running: 0
 Paused: 0
 Stopped: 11
Images: 510
Server Version: 1.11.1
Storage Driver: devicemapper
 Pool Name: docker-8:1-5375695-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 30.56 GB
 Data Space Total: 107.4 GB
 Data Space Available: 76.81 GB
 Metadata Space Used: 39.1 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.108 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.124 (2016-05-07)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.5.0-2-amd64
Operating System: Debian GNU/Linux stretch/sid
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.863 GiB
Name: debian8
ID: RSMS:2TI7:TEE4:N5YC:SSGG:7IBA:QY7S:OXUD:VPD3:H4T3:DOYT:PTUT
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

OS is Debian stretch/sid

**Steps to reproduce the issue:**
1. Dockerfile:
FROM debian
RUN apt-get update
RUN apt-get install -y curl vim-gnome git
COPY .vim_inc /root/.vim_inc

RUN curl -fLo $HOME/.vim/autoload/plug.vim --create-dirs "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"

RUN vim -E -u NONE -S /root/.vim_inc +PlugInstall +qall > /dev/null

2..vim_inc:
set rtp+=~/.vim/autoload/plug.vim
call plug#begin()
Plug 'ctrlpvim/ctrlp.vim'
call plug#end()

3.Put .vim_inc and Dockerfile in a folder and run:
docker build -t=vim .

**Describe the results you received:**
Step 7 : RUN curl -fLo $HOME/.vim/autoload/plug.vim --create-dirs "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
 ---> Running in c5b44fc105a8
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 65442  100 65442    0     0   185k      0 --:--:-- --:--:-- --:--:--  185k
 ---> 90917ccc21ec
Removing intermediate container c5b44fc105a8
Step 8 : RUN vim -E -u NONE -S /root/.vim_inc +PlugInstall +qall > /dev/null
 ---> Running in 23649e98513d
The command '/bin/sh -c vim -E -u NONE -S /root/.vim_inc +PlugInstall +qall > /dev/null' returned a non-zero code: 1

**Describe the results you expected:**
Sucessfully built docker image with vim and installed plug-in.

**Additional information you deem important (e.g. issue happens only occasionally):**
when I do: docker run -it --rm 90917ccc21ec
and then run: vim -E -u NONE -S /root/.vim_inc +PlugInstall +qall > /dev/null
all works. 

I am also that far to tell (after 2 days fiddling around with all the configure flags, that it works when I compile vim myself but leave out the flag --enable-rubyinterp.

That is, using the following instead of using the package vim-gnome from the distribution, everything works as expected:

RUN apt-get build-dep -y vim
RUN git clone https://github.com/vim/vim.git
WORKDIR vim
RUN ./configure --prefix=/usr --with-features=huge \
        --enable-pythoninterp \
        --enable-perlinterp \
        --enable-luainterp \
        --enable-gui=no
RUN make && make install

But, adding --enable-rubyinterp in the above excerpt results in the same error as with the initially presented Dockerfile!

Interestingly whatever vim version I use (vim-gnome or custom build), I can always run the last successfully built layer and issue the failed command by hand - which then works fine. But since this ONLY happens in the build process of the docker image, I suspect a bug somewhere in Docker's ecosystem.

**Comment by unclejack** [comment]
@Jeansen Based on previous discussions and my own experiments, it seems vim has some issues when it's not running in a TTY. `docker build` doesn't allocate a TTY for the containers and some tools can't handle that properly.

You can check this is related to the lack of a TTY by running the exact same command in a container started with `-it`.

**Comment by Jeansen** [comment]
@unclejack I sort of thought so. That would explain why to command works with -it but not in a Dockerfile. Anyway it struck me odd since it only happens with some compilation flags set (or not set). But I do not know (and did not dig deeper into) what side effects the ruby interpreter flag has.

**Comment by HackToday** [comment]
it seems I used ` vim +PluginInstall +qall && \` it works in my build process

**Comment by justincormack** [comment]
Yes, we do not create a tty for build, in general build processes do not need a tty, so glad you found a solution in this case.

**Comment by thaJeztah** [comment]
Alright, let's close this, happy to see there's a way to make it work

**Comment by Jeansen** [comment]
@HackToday: Oh wow! Adding && really did the trick! No it works, no matter how I compile it or which compiled distro version I use. Many thanks! :+1:
