### ISSUE TITLE
Dockerfile support for pulling from git/hg/other scms

### ISSUE THREAD

**Issue by bmurphy1976** [docker/docker#2289]
It would be nice if Dockerfile supported syntax similar to the following:

```
FROM ubuntu
GIT https://github.com/dotcloud/docker.git:89a2c8e2cd /opt/docker 
```

This would export files from a specified (optional) revision of a git repository and add them to the target location in the container.  This would make it easy to export code into a container without having to inject security credentials and/or scm software.

There would of course be analogs for other scm's like mercurial or subversion.

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.
