### ISSUE TITLE
-help

### ISSUE THREAD

**Issue by drunz** [docker/docker#22903]
**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
looks like this was opened by mistake, but let me know if you were trying to open an issue

**Comment by drunz** [comment]
Totally by mistake, sorry. Was typing in the wrong window.

**Comment by thaJeztah** [comment]
It happens :smile: you're not the first person accidentally opening an issue that way
