### ISSUE TITLE
Create chocolatey install

### ISSUE THREAD

**Issue by velo** [docker/docker#22929]
This is just a feature request.

So, would be nice to have docker beta as part of chocolatey:
https://chocolatey.org/packages?q=docker

**Comment by justincormack** [comment]
Hi, currently the best place for feature requests for Docker for Windows is at https://forums.docker.com/c/docker-for-windows

**Comment by jfrazelle** [comment]
I thought @ahmetalpbalken did this

**Comment by jfrazelle** [comment]
er @ahmetalpbalkan 

(where is autocomplete when you need it I was SO CLOSE)

**Comment by justincormack** [comment]
For docker? Or for docker for windows beta? I would hope there is one for
docker client at least.

**Comment by jfrazelle** [comment]
Docker client for sure, but I bet he would know how to add another

On Mon, May 23, 2016 at 11:10 PM, Justin Cormack <notifications@github.com>
wrote:

> For docker? Or for docker for windows beta? I would hope there is one for
> docker client at least.
> On 23 May 2016 11:07 p.m., "Jess Frazelle" <notifications@github.com>
> wrote:
>
> > I thought @ahmetalpbalken did this
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/docker/docker/issues/22929#issuecomment-221174830>
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/22929#issuecomment-221175379>
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by velo** [comment]
Docker client and docker machine already exists...

I was thinking more about "docker for windows beta"

**Comment by ahmetalpbalkan** [comment]
Yeah I just did the docker client binary and I believe Stefan did the machine (although he also now maintains the client binary).

I suggest creating a separate package for "docker for windows"

**Comment by justincormack** [comment]
I have created an internal issue 3373 to track this, and also the requested homebrew support for docker for mac. This won't happen until GA at the earliest as the distribution process for binaries will change at this point to open access.

**Comment by thaJeztah** [comment]
I'll close this issue in this repository, as it's now being tracked in the Docker for Mac/Windows issue tracker. Thanks all for the suggestion!
