### ISSUE TITLE
Cannot install FXCop/.NET 4.5.2 dev pack in Windows Containers (TP5)

### ISSUE THREAD

**Issue by timotei** [docker/docker#22921]
Hello,

So, I'm trying to create a docker image with some software to be used for Continuous Integration purposes. Among the packages I have fxcop. I downloaded the setup from https://fxcopinstaller.codeplex.com/ and tried installing it in a new docker container instance:

`docker run --rm -it windowservercore cmd`

And then:

```
> powershell (New-Object System.Net.WebClient).DownloadFile('http://download-codeplex.sec.s-msft.com/Download/Release?ProjectName=fxcopinstaller&DownloadId=821386&FileTime=130407655516000000&Build=21031', 'C:\setup.exe')
> C:\setup.exe /q /l:log.txt
```

However, the install will never complete for some reason, but quickly exits. Doing the same thing in a "normal" (non containerized Windows version) works just fine (it also shows some progress windows). The same issue happens for example, for the .NET 4.5.2 devpack/setup (http://download.microsoft.com/download/4/3/B/43B61315-B2CE-4F5B-9E32-34CCA07B2F0E/NDP452-KB2901951-x86-x64-DevPack.exe installed with arguments `/Quiet /NoRestart /Log C:\netfx-4.5.2-devpack.log`)

Do you have any idea on how to further debug this issue? (I just saw that the setup also has some further setup.exe/install.msi, I'm gonna give them a try)

Might the fact that the container doesn't have any "UI" break somehow the installer, even if it's in "quiet" mode? This doesn't seem to be an issue of specific programs, but maybe the way the setups are done?

**Output of `docker version`:**

```
PS C:\Users\Administrator> docker version
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   2b97201
 Built:        Tue Apr 26 23:51:36 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   2b97201
 Built:        Tue Apr 26 23:51:36 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
PS C:\Users\Administrator> docker info
Containers: 4
 Running: 1
 Paused: 0
 Stopped: 3
Images: 4
Server Version: 1.12.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null
Kernel Version: 10.0 14300 (14300.1016.amd64fre.rs1_release_svc.160428-1819)
Operating System: Windows Server 2016 Standard Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 7.941 GiB
Name: WIN-7FOOHO67EP8
ID: X2GU:377P:EF42:2UT4:7MGX:UP6A:NQ7W:H3H7:CFSX:WNWN:BJDR:UI5Q
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Comment by friism** [comment]
Yeah, Windows installers can be a pain in the butt. First off, I think you want to run with `/x:setup` (`setup` is where the archive will be extracted).

Second, you have to wait for the extraction to complete (running the `.exe` returns immediately to the shell). Here's one way (in powershell):

   Start-Process setup.exe -ArgumentList "/q /x:setup" -Wait

**Comment by thaJeztah** [comment]
@friism think we should have some examples in our docs?

**Comment by friism** [comment]
@thaJeztah or we can try to get it in here: https://msdn.microsoft.com/en-us/virtualization/windowscontainers/docker/manage_windows_dockerfile

/cc @neilpeterson

**Comment by friism** [comment]
This also appears to work `start /wait setup.exe /q /x:setup`

**Comment by timotei** [comment]
Yay. That seems to have worked.

https://gist.github.com/timotei/7aa60ef640e87ee88445f22821f50e0e

I can write some info on that page if PRs are accepted :)

**Comment by friism** [comment]
@timotei  I'm sure @neilpeterson would love a PR: https://github.com/Microsoft/Virtualization-Documentation/blob/master/virtualization/windowscontainers/docker/manage_windows_dockerfile.md

**Comment by timotei** [comment]
OK, updated the docs with a PR. I think this issue can be closed, right?

**Comment by neilpeterson** [comment]
Thanks @timotei, I will see the PR and will check it out today.

**Comment by thaJeztah** [comment]
Looks like the PR was merged, so closing
