### ISSUE TITLE
Feature/betterment of people's lives: Generated docs

### ISSUE THREAD

**Issue by jessfraz** [docker/docker#22931]
Kube's is somehow generating docs, I didn't look into the details but it's prettty cool, even if its slow as eff to run (maybe we can make it better, I didn't really dig deep). Then maybe we don't have to think about so many things :)

https://github.com/kubernetes/kubernetes/blob/master/hack/update-generated-docs.sh

**Comment by thockin** [comment]
Our doc-gen process is insanely painful.  Please, at most borrow the idea,
but not the implementation :)

**Comment by thaJeztah** [comment]
Haha, thanks for the warning @thockin. I do wonder if we should be able to generate more parts, if we switch to cobra https://github.com/docker/docker/pull/22769.

Also, although generating docs for trivial parts is good, we probably still need the additional examples, etc to be combined with that.

**Comment by dnephin** [comment]
REST API docs, and CLI reference docs should be very easy to generate if we're using the right libraries (some form of interface specification like swagger).  I agree there is little value in generating narrative documentation from the source.

**Comment by bfirsh** [comment]
Here's the current state of auto-generating API docs: https://github.com/docker/engine-api/issues/77

**Comment by SvenDowideit** [comment]
I have a go tool I'm writing that makes building the docs (from I don't have any repos checked out) as simple as

```
$ gendoc clone
$ gendoc build
listening on port 8000
```

or if you want to do something on the non-master docs

```
$ gendoc clone
$ gendoc checkout v1.11
$ gendoc build
listening on port 8000
```

it "works for me" already - without modifying the existing stuff (because atm, it shells out to a local install of hugo)

and ya - weaving the API docs should happen inside that.

**Comment by bfirsh** [comment]
Here is my work in progress on automatically generating API docs:

https://bfirsh.github.io/docker-api-reference/
https://github.com/bfirsh/docker-api-reference (to-do list is in issues)

It's obviously unfinished. At the moment I'm just ploughing through it porting the existing API docs to a Swagger spec. Turns out a lot of the API docs are incomplete/wrong/poorly written/inconsistent, so I'm also using this opportunity to tidy that up!

It's all generated from a manually written Swagger spec. For more background about that, see https://github.com/docker/engine-api/issues/77

I would be interested in all of your feedback. It's particularly useful to get it early.

**Comment by thaJeztah** [comment]
@bfirsh looks really nice already! Some thoughts; 

- do we need to explain the various value types (e.g. explain that boolean query parameters accept `true`, `1`, `0`, `false`)?
- how easy is it to add "custom" content to those docs? (just wondering)
- current implementation is fully generated client-side, although I really love the way it looks and works; is there a way to also generate a static version? Both to allow it being searchable / indexable, and also for keeping it future proof (wouldn't be the first time I got hit by a fancy JavaScript library stopping to work with certain browser versions)

Awesome work, and definitely looking forward to this

**Comment by bfirsh** [comment]
Boolean: agreed. We should have a section explaining that and other formats. I've created an issue: https://github.com/bfirsh/docker-api-reference/issues/13

Custom content: All of the fields accept GitHub Flavored Markdown so this is pretty straight forward. Custom sections can be added at the top too.

Generated client-side: Yes, agreed, I hate this. One of the first issues I created. ;) https://github.com/bfirsh/docker-api-reference/issues/3

**Comment by thaJeztah** [comment]
@bfirsh oh, I noticed you're using the `#/something` notation for the anchor references in your Swagger; https://github.com/bfirsh/docker-api-reference/blob/81a3ff897484fa1ea40387de0ba1b8492652294c/swagger.json#L209

I think the *actual* anchors are without the slash after `#`, but it's a client side JavaScript that replaces those to add the slash on docs.docker.com

**Comment by thaJeztah** [comment]
Oh, perhaps that's how Swagger expects it, in that case, ignore

**Comment by bfirsh** [comment]
Yep – that's a JSON Schema thing, not a URL anchor.

**Comment by bfirsh** [comment]
Updates! The Swagger definition is now mostly complete:

https://github.com/bfirsh/docker-api-reference/blob/master/swagger.yaml
https://bfirsh.github.io/docker-api-reference/

I've also gone through and improved lots of the descriptions of things, and added descriptions where there were none (e.g. for most response objects). This was constructed half from the existing API docs, half from the source code.

I'm now working with @dnephin to figure out how we might incorporate this into the docs and get it built. It certainly makes sense for the `swagger.yaml` to live in this repository, so it can be updated when there are API changes. There will then need to be some kind of build process to build the HTML docs.

**Comment by bfirsh** [comment]
The Swagger file is now in, thanks to @dnephin's work on generating types from it! https://github.com/docker/docker/blob/master/api/swagger.yaml :tada:

The work for automatically generating API docs from it is going on here: https://github.com/docker/docker.github.io/pull/210

**Comment by bfirsh** [comment]
A real PR! https://github.com/docker/docker.github.io/pull/606

**Comment by bfirsh** [comment]
https://docs.docker.com/engine/api/v1.25/ :cake:

(Can somebody close this? I no longer have access to!)

**Comment by SvenDowideit** [comment]
success :)
