### ISSUE TITLE
Windows - docker attach causes error: 'invalid memory address or nil pointer dereference'

### ISSUE THREAD

**Issue by shuoyenl** [docker/docker#22934]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   2b97201
 Built:        Tue Apr 26 23:51:36 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   2b97201
 Built:        Tue Apr 26 23:51:36 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.12.0-dev
Storage Driver: windowsfilter
 Windows: 
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: nat null
Kernel Version: 10.0 14300 (14300.1016.amd64fre.rs1_release_svc.160428-1819)
Operating System: Windows Server 2016 Datacenter Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 3.5 GiB
Name: Brian
ID: PAPN:HH6S:7EBF:CQSU:CNOS:M3YW:QVWU:BMC7:2OX5:QATJ:2UEU:DTZL
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Azure VM

**Steps to reproduce the issue:**
docker run -it windowsservercore cmd

**Describe the results you received:**
docker : panic: runtime error: invalid memory address or nil pointer dereference
At line:1 char:1
+ docker run -it windowsservercore cmd
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (panic: runtime ...ter dereference:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
[signal 
0xc0000005
 code=
0x0
 addr=
0x28
 pc=
0x4a1d06
]
goroutine 
16
 [
running
]:
github.com/Sirupsen/logrus.(*Logger).Debugf
(
0x0
, 
0xb97e00
, 
0x4e
, 
0xc0822b3b88
, 
0x3
, 
0x3
)
	
/go/src/github.com/docker/docker/vendor/src/github.com/Sirupsen/logrus/logger.go
:
74
 +
0x26
github.com/docker/docker/pkg/term/windows.readInputEvents
(
0x76c
, 
0x8000
, 
0x0
, 
0x0
, 
0x0
, 
0x0
, 
0x0
)
	
/go/src/github.com/docker/docker/pkg/term/windows/ansi_reader.go
:
115
 +
0x262
github.com/docker/docker/pkg/term/windows.(*ansiReader).Read
(
0xc082184e60
, 
0xc0822ba000
, 
0x8000
, 
0x8000
, 
0x8000
, 
0x0
, 
0x0
)
	
/go/src/github.com/docker/docker/pkg/term/windows/ansi_reader.go
:
74
 +
0x47b
io.copyBuffer
(
0x1219a28
, 
0xc08226bea0
, 
0x1219e50
, 
0xc082184e60
, 
0xc0822ba000
, 
0x8000
, 
0x8000
, 
0x0
, 
0x0
, 
0x0
)
	
/usr/local/go1.5.3/src/io/io.go
:
381
 +
0x24e
io.Copy
(
0x1219a28
, 
0xc08226bea0
, 
0x1219e50
, 
0xc082184e60
, 
0xc082184e60
, 
0x0
, 
0x0
)
	
/usr/local/go1.5.3/src/io/io.go
:351 +0x6b
github.com/docker/docker/api/client.(*DockerCli).holdHijackedConnection.func3(0x1218e28, 0xc082184e60, 0xc08226bfa0, 0xc0822aa401, 0xc0822aa440, 0xc08216cf80, 
0xc08226daa0)
	/go/src/github.com/docker/docker/api/client/hijack.go:55 +0xdd
created by github.com/docker/docker/api/client.(*DockerCli).holdHijackedConnection
	/go/src/github.com/docker/docker/api/client/hijack.go:70 +0x24c
goroutine 1 [select]:
github.com/docker/engine-api/client/transport/cancellable.Do(0x1218ac8, 0xc082003580, 0x1219950, 0xc08226a0a0, 0xc08206f180, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:56 +0x4a3
github.com/docker/engine-api/client.(*Client).sendClientRequest(0xc08226c9c0, 0x1218ac8, 0xc082003580, 0xabb060, 0x4, 0xc08226d680, 0x52, 0x0, 0x1219df8, 0xc08229a990, 
...)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/engine-api/client/request.go:95 +0x461
github.com/docker/engine-api/client.(*Client).sendRequest(0xc08226c9c0, 0x1218ac8, 0xc082003580, 0xabb060, 0x4, 0xc08226d680, 0x52, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/engine-api/client/request.go:73 +0x2e1
github.com/docker/engine-api/client.(*Client).post(0xc08226c9c0, 0x1218ac8, 0xc082003580, 0xc08226d680, 0x52, 0x0, 0x0, 0x0, 0x0, 0x10, ...)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/engine-api/client/request.go:36 +0xbb
github.com/docker/engine-api/client.(*Client).ContainerStart(0xc08226c9c0, 0x1218ac8, 0xc082003580, 0xc08225f680, 0x40, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/engine-api/client/container_start.go:7 +0xdf
github.com/docker/docker/api/client.(*DockerCli).CmdRun(0xc08216cf80, 0xc08200c110, 0x3, 0x3, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/client/run.go:234 +0x1481
reflect.callMethod(0xc082269110, 0xc082115c88)
	/usr/local/go1.5.3/src/reflect/value.go:628 +0x203
reflect.methodValueCall(0xc08200c110, 0x3, 0x3, 0x1, 0xc082269110, 0x0, 0x0, 0xc082269110, 0x0, 0x46631b, ...)
	/usr/local/go1.5.3/src/reflect/asm_amd64.s:29 +0x3d
github.com/docker/docker/cli.(*Cli).Run(0xc082231e00, 0xc08200c100, 0x4, 0x4, 0x0, 0x0)
	/go/src/github.com/docker/docker/cli/cli.go:89 +0x38a
main.main()
	/go/src/github.com/docker/docker/cmd/docker/docker.go:58 +0x384
goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go1.5.3/src/os/signal/signal_unix.go:22 +0x1f
created by os/signal.init.1
	/usr/local/go1.5.3/src/os/signal/signal_unix.go:28 +0x3e
goroutine 12 [select]:
github.com/docker/docker/api/client.(*DockerCli).holdHijackedConnection(0xc08216cf80, 0x1219db8, 0xc08225f740, 0x7cf801, 0x1218e28, 0xc082184e60, 0x1214390, 
0xc082022010, 0x1214390, 0xc082022010, ...)
	/go/src/github.com/docker/docker/api/client/hijack.go:72 +0x704
github.com/docker/docker/api/client.(*DockerCli).CmdRun.func2(0x0, 0x0)
	/go/src/github.com/docker/docker/api/client/run.go:217 +0x120
github.com/docker/docker/pkg/promise.Go.func1(0xc08226d620, 0xc08216d400)
	/go/src/github.com/docker/docker/pkg/promise/promise.go:8 +0x24
created by github.com/docker/docker/pkg/promise.Go
	/go/src/github.com/docker/docker/pkg/promise/promise.go:9 +0x64
goroutine 13 [select]:
net/http.(*persistConn).roundTrip(0xc08200ed10, 0xc0822aa390, 0x0, 0x0, 0x0)
	/usr/local/go1.5.3/src/net/http/transport.go:1164 +0xb14
net/http.(*Transport).RoundTrip(0xc082058510, 0xc08206f180, 0xd8, 0x0, 0x0)
	/usr/local/go1.5.3/src/net/http/transport.go:235 +0x537
net/http.send(0xc08206f180, 0x1214600, 0xc082058510, 0xc08216d500, 0x0, 0x0)
	/usr/local/go1.5.3/src/net/http/client.go:220 +0x533
net/http.(*Client).send(0xc0822690b0, 0xc08206f180, 0x7d, 0x0, 0x0)
	/usr/local/go1.5.3/src/net/http/client.go:143 +0x161
net/http.(*Client).doFollowingRedirects(0xc0822690b0, 0xc08206f180, 0xbda100, 0x0, 0x0, 0x0)
	/usr/local/go1.5.3/src/net/http/client.go:380 +0xbc7
net/http.(*Client).Do(0xc0822690b0, 0xc08206f180, 0x0, 0x0, 0x0)
	/usr/local/go1.5.3/src/net/http/client.go:178 +0x18f
github.com/docker/engine-api/client/transport/cancellable.Do.func1(0x1219
950, 0xc08226a0a0, 0xc08206f180, 0xc08226d860)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:49 +0x3c
created by github.com/docker/engine-api/client/transport/cancellable.Do
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:52 +0x106
goroutine 8 [syscall, locked to thread]:
syscall.Syscall6(0x7ffa3bae6f90, 0x5, 0x1c4, 0xc0822a7f54, 0xc0822a7f58, 0xc0822a7f60, 0xffffffff, 0x0, 0xc0822a7f78, 0x1, ...)
	/usr/local/go1.5.3/src/runtime/syscall_windows.go:139 +0x5c
github.com/Microsoft/go-winio.getQueuedCompletionStatus(0x1c4, 0xc0822a7f54, 0xc0822a7f58, 0xc0822a7f60, 0xffffffff, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/zsyscall.go:72 +0x99
github.com/Microsoft/go-winio.ioCompletionProcessor(0x1c4)
	/go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/file.go:127 +0x7c
created by github.com/Microsoft/go-winio.initIo
	/go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/file.go:55 +0xb3
goroutine 9 [chan receive]:
github.com/Microsoft/go-winio.(*win32File).asyncIo(0xc08226f720, 0xc08229a600, 0x0, 0x0, 0x0, 0xc000000000, 0x1210050, 0xc0822aa0a0, 0x412d49, 0x0, ...)
	/go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/file.go:165 +0x176
github.com/Microsoft/go-winio.(*win32File).Read(0xc08226f720, 0xc082267000, 0x1000, 0x1000, 0x8d16c0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/file.go:188 +0x15f
github.com/Microsoft/go-winio.(*win32MessageBytePipe).Read(0xc08226bba0, 0xc082267000, 0x1000, 0x1000, 0x404fe5, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/pipe.go:114 +0x94
net/http.noteEOFReader.Read(0x12199d8, 0xc08226bba0, 0xc08200ed68, 0xc082267000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go1.5.3/src/net/http/transport.go:1370 +0x6e
net/http.(*noteEOFReader).Read(0xc08226bbc0, 0xc082267000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd7
bufio.(*Reader).fill(0xc08226d080)
	/usr/local/go1.5.3/src/bufio/bufio.go:97 +0x1f0
bufio.(*Reader).Peek(0xc08226d080, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go1.5.3/src/bufio/bufio.go:132 +0xd3
net/http.(*persistConn).readLoop(0xc08200ed10)
	/usr/local/go1.5.3/src/net/http/transport.go:876 +0xfe
created by net/http.(*Transport).dialConn
	/usr/local/go1.5.3/src/net/http/transport.go:685 +0xc7f
goroutine 10 [select]:
net/http.(*persistConn).writeLoop(0xc08200ed10)
	/usr/local/go1.5.3/src/net/http/transport.go:1009 +0x413
created by net/http.(*Transport).dialConn
	/usr/local/go1.5.3/src/net/http/transport.go:686 +0xca4
goroutine 14 [runnable]:
github.com/docker/docker/pkg/term.restoreAtInterrupt.func1(0xc08226d9e0, 0x76c, 0xc08226bfc0)
	/go/src/github.com/docker/docker/pkg/term/term_windows.go:296
created by github.com/docker/docker/pkg/term.restoreAtInterrupt
	/go/src/github.com/docker/docker/pkg/term/term_windows.go:300 +0xee
goroutine 15 [runnable]:
github.com/docker/docker/api/client.(*DockerCli).holdHijackedConnection.func2(0xc08226da01, 0x1214390, 0xc082022010, 0xc0822aa430, 0xc08226bfa0, 0x1218e28, 
0xc082184e60, 0xc0822aa440, 0xc08216cf80, 0x1214390, ...)
	/go/src/github.com/docker/docker/api/client/hijack.go:32
created by github.com/docker/docker/api/client.(*DockerCli).holdHijackedConnection
	/go/src/github.com/docker/docker/api/client/hijack.go:49 +0x7a1

**Describe the results you expected:**
No error

**Additional information you deem important (e.g. issue happens only occasionally):**
A container was started even though the error was thrown... 
PS C:\docker> docker ps -al
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                  PORTS               NAMES
52e688817ba8        windowsservercore   "cmd"               9 seconds ago       Up Less than a second                       thirsty_galileo

Trying to attach to the container got the same error...
PS C:\docker> docker attach 52e688817ba8
docker : panic: runtime error: invalid memory address or nil pointer dereference
At line:1 char:1
+ docker attach 52e688817ba8
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (panic: runtime ...ter dereference:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
[signal 
0xc0000005
 code=
0x0
 addr=
0x28
 pc=
0x4a1d06
]
goroutine 
14
 [
running
]:
github.com/Sirupsen/logrus.(*Logger).Debugf
(
0x0
, 
0xb97e00
, 
0x4e
, 
0xc082293b88
, 
0x3
, 
0x3
)
	
/go/src/github.com/docker/docker/vendor/src/github.com/Sirupsen/logrus/logger.go
:
74
 +
0x26
github.com/docker/docker/pkg/term/windows.readInputEvents
(
0x76c
, 
0x8000
, 
0x0
, 
0x0
, 
0x0
, 
0x0
, 
0x0
)
	
/go/src/github.com/docker/docker/pkg/term/windows/ansi_reader.go
:
115
 +
0x262
github.com/docker/docker/pkg/term/windows.(*ansiReader).Read
(
0xc08218cdc0
, 
0xc082294000
, 
0x8000
, 
0x8000
, 
0x8000
, 
0x0
, 
0x0
)
	
/go/src/github.com/docker/docker/pkg/term/windows/ansi_reader.go
:
74
 +
0x47b
io.copyBuffer
(
0xf990f8
, 
0xc08226b180
, 
0xf99728
, 
0xc08218cdc0
, 
0xc082294000
, 
0x8000
, 
0x8000
, 
0x0
, 
0x0
, 
0x0
)
	
/usr/local/go1.5.3/src/io/io.go
:
381
 +
0x24e
io.Copy
(
0xf990f8
, 
0xc08226b180
, 
0xf99728
, 
0xc08218cdc0
, 
0xc08218cdc0
, 
0x0
, 
0x0
)
	
/usr/local/go1.5.3/src/io/io.go
:351 +0x6b
github.com/docker/docker/api/client.(*DockerCli).holdHijackedConnection.func3(0xf98d10, 0xc08218cdc0, 0xc08226b1c0, 0xc08227cb01, 0xc08227cb80, 0xc08216cf80, 
0xc08226d2c0)
	/go/src/github.com/docker/docker/api/client/hijack.go:55 +0xdd
created by github.com/docker/docker/api/client.(*DockerCli).holdHijackedConnection
	/go/src/github.com/docker/docker/api/client/hijack.go:70 +0x24c
goroutine 1 [select]:
github.com/docker/docker/api/client.(*DockerCli).holdHijackedConnection(0xc08216cf80, 0xf989b0, 0xc082003540, 0xc082002201, 0xf98d10, 0xc08218cdc0, 0xf942c0, 
0xc082022010, 0xf942c0, 0xc082022018, ...)
	/go/src/github.com/docker/docker/api/client/hijack.go:72 +0x704
github.com/docker/docker/api/client.(*DockerCli).CmdAttach(0xc08216cf80, 0xc082005ee0, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/client/attach.go:94 +0xf35
reflect.callMethod(0xc082267170, 0xc082115c88)
	/usr/local/go1.5.3/src/reflect/value.go:628 +0x203
reflect.methodValueCall(0xc082005ee0, 0x1, 0x1, 0x1, 0xc082267170, 0x0, 0x0, 0xc082267170, 0x0, 0x46631b, ...)
	/usr/local/go1.5.3/src/reflect/asm_amd64.s:29 +0x3d
github.com/docker/docker/cli.(*Cli).Run(0xc082231e60, 0xc082005ed0, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/docker/docker/cli/cli.go:89 +0x38a
main.main()
	/go/src/github.com/docker/docker/cmd/docker/docker.go:58 +0x384
goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go1.5.3/src/os/signal/signal_unix.go:22 +0x1f
created by os/signal.init.1
	/usr/local/go1.5.3/src/os/signal/signal_unix.go:28 +0x3e
goroutine 12 [runnable]:
github.com/docker/docker/pkg/term.restoreAtInterrupt.func1(0xc08226d200, 0x76c, 0xc08226b1e0)
	/go/src/github.com/docker/docker/pkg/term/term_windows.go:296
created by github.com/docker/docker/pkg/term.restoreAtInterrupt
	/go/src/github.com/docker/docker/pkg/term/term_windows.go:300 +0xee
goroutine 13 [runnable]:
github.com/docker/docker/api/client.(*DockerCli).holdHijackedConnection.func2(0xc08226d201, 0xf942c0, 0xc082022010, 0xc08227cb70, 0xc08226b1c0, 0xf98d10, 0xc08218cdc0, 
0xc08227cb80, 0xc08216cf80, 0xf942c0, ...)
	/go/src/github.com/docker/docker/api/client/hijack.go:32
created by github.com/docker/docker/api/client.(*DockerCli).holdHijackedConnection
	/go/src/github.com/docker/docker/api/client/hijack.go:49 +0x7a1
goroutine 8 [syscall, locked to thread]:
syscall.Syscall6(0x7ffa3bae6f90, 0x5, 0x1c4, 0xc082275f54, 0xc082275f58, 0xc082275f60, 0xffffffff, 0x0, 0xc082275f78, 0x1, ...)
	/usr/local/go1.5.3/src/runtime/syscall_windows.go:139 +0x5c
github.com/Microsoft/go-winio.getQueuedCompletionStatus(0x1c4, 0xc082275f54, 0xc082275f58, 0xc082275f60, 0xffffffff, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/zsyscall.go:72 +0x99
github.com/Microsoft/go-winio.ioCompletionProcessor(0x1c4)
	/go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/file.go:127 +0x7c
created by github.com/Microsoft/go-winio.initIo
	/go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/file.go:55 +0xb3
goroutine 9 [chan receive]:
github.com/Microsoft/go-winio.(*win32File).asyncIo(0xc08218dcc0, 0xc082267530, 0x0, 0x0, 0x0, 0xc000000000, 0xf90050, 0xc0822609e0, 0x412d49, 0x0, ...)
	/go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/file.go:165 +0x176
github.com/Microsoft/go-winio.(*win32File).Read(0xc08218dcc0, 0xc082265000, 0x1000, 0x1000, 0x8d16c0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/file.go:188 +0x15f
github.com/Microsoft/go-winio.(*win32MessageBytePipe).Read(0xc08226a460, 0xc082265000, 0x1000, 0x1000, 0x404fe5, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/Microsoft/go-winio/pipe.go:114 +0x94
net/http.noteEOFReader.Read(0xf990a8, 0xc08226a460, 0xc08200ecb8, 0xc082265000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go1.5.3/src/net/http/transport.go:1370 +0x6e
net/http.(*noteEOFReader).Read(0xc08226a480, 0xc082265000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd7
bufio.(*Reader).fill(0xc08226cd80)
	/usr/local/go1.5.3/src/bufio/bufio.go:97 +0x1f0
b
ufio.(*Reader).Peek(0xc08226cd80, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go1.5.3/src/bufio/bufio.go:132 +0xd3
net/http.(*persistConn).readLoop(0xc08200ec60)
	/usr/local/go1.5.3/src/net/http/transport.go:876 +0xfe
created by net/http.(*Transport).dialConn
	/usr/local/go1.5.3/src/net/http/transport.go:685 +0xc7f
goroutine 10 [select]:
net/http.(*persistConn).writeLoop(0xc08200ec60)
	/usr/local/go1.5.3/src/net/http/transport.go:1009 +0x413
created by net/http.(*Transport).dialConn
	/usr/local/go1.5.3/src/net/http/transport.go:686 +0xca4

**Comment by thaJeztah** [comment]
ping @jstarks @jhowardmsft

**Comment by jhowardmsft** [comment]
What environment are you running this from? The PowerShell ISE by any chance?

**Comment by shuoyenl** [comment]
Yes - I ran this in the PowerShell ISE. Is that a problem?

**Comment by jhowardmsft** [comment]
Yes, known problem (there's another issue on this, but can't locate it). Will fix. Solution is not to run -it, or run outside of the ISE. The ISE presents stdout/stderr as pipes, not char file types.

**Comment by shuoyenl** [comment]
Got it. Thanks.

**Comment by jhowardmsft** [comment]
Let's leave this open - I'll open a PR shortly to fix it.
