### ISSUE TITLE
docker says "level=debug msg="event unhandled: type:\"start-container\" when start a container

### ISSUE THREAD

**Issue by TheBeeMan** [docker/docker#22939]
I started dockerd with "--debug" option.
then i run client command "docker start ID", dockerd says "level=debug msg="event unhandled: type:\"start-container\", but the container is already started

**Comment by cpuguy83** [comment]
This is just a debug message.

Are you experiencing some problem?

**Comment by TheBeeMan** [comment]
I just do not understand that.
The debug info here seems not to make sense, so, could you tell me which module or function really handle event "start-container" for docker?
tks

**Comment by cpuguy83** [comment]
It's just messages from containerd, and unimportant.

Closing as this is not an issue.
