### ISSUE TITLE
Docker images, volumes, containers disappeared

### ISSUE THREAD

**Issue by hgill** [docker/docker#22944]
Hi

This closed issue comes close, but couldn't resolve my issues, apologies if this is a repeat https://github.com/docker/docker/issues/21718

My data volumes, images and existing containers have all disappeared! The data volumes had all my databases, local cache data, etc. 

How do I retrieve/reinstate them? 
Any data volume backup strategies to mitigate this? Will using flocker resolve this?

Version and OS history below - this is on Win 8.1

```
$ docker version
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:13:28 2016
 OS/Arch:      windows/amd64

 Server:

 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64

```
```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 4.4.8-boot2docker
Operating System: Boot2Docker 1.11.1 (TCL 7.0); HEAD : 7954f54 - Wed Apr 27 16:36:45 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: default
ID: CFBP:WS4S:E6TE:ZPSN:ATG3:5YMI:GPRA:MBOO:OVIJ:KOQK:ZK6N:P5G4
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 29
 System Time: 2016-05-24T14:46:02.365165011Z
 EventsListeners: 0
Username: harpreetsg
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```
`

**Comment by thaJeztah** [comment]
I don't think this is related to https://github.com/docker/docker/issues/21718, that was a device mapper issue.

I see you're running Docker Toolbox / boot2docker; Your images and containers are stored inside the VirtualBox VM. Did you happen to remove/recreate the virtual machine, or create a new one? If you're running `docker-machine ls` do you see just a single machine configured, or multiple? Also see https://github.com/boot2docker/boot2docker/#persist-data

**Comment by hgill** [comment]
Thanks for the quick response, really appreciate it - 

I usually run 3-4 services - 2 DB containers with 2 mounted data volumes, and 1-2 webapp containers. Sometimes when the system crawls, I do 2 docker-compose downs and then kill VirtualBox instances from Windows Task Manager, before starting Quickstart terminal again

docker-machine ls below, but just opened the VIrtualBox GUI - never noticed this before - there is a 'default' and a 'TESTENV' instance there - the first is a linux and the second a Win7? Not sure if that is related?

About the link - I do not have boot2docker - installed the toolbox, so I have docker-machine. tried docker-machine provision but no effect.

```
$ docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
default   *        virtualbox   Running   tcp://192.168.99.100:2376           v1.11.1

```

**Comment by thaJeztah** [comment]
True, although docker-machine uses boot2docker Linux inside the VM, and I think some parts are still the same (i.e. the way the persistent storage is setup). The Win7 machine is not related to Docker, possibly something you tried in the past?

I'm not really sure what happened in your case. You could try logging into the VM (`docker-machine ssh default`) and check if the `/var/lib/docker` directory contains directories for other storage drivers (e.g. if there's an `overlay` driver there); that could explain your containers/images not being there if you happened to use the `overlay` driver before

**Comment by hgill** [comment]
Thanks - the networks I set up are unaffected in my docker-machine, but everything else is invisible - this mirrors the permissions below. Tried changing permissions to 755 for all the folders, but didn't work. Hopefully it is related to folder permissions below, and hope someone can show the way.

```
docker@default:/mnt/sda1/var/lib/docker$ sudo ls -al
total 36
drwx--x--x    9 root     root          4096 May 24 14:16 .
drwxr-xr-x    4 root     root          4096 May 24 14:16 ..
drwx------    5 root     root          4096 May 24 14:16 aufs
drwx------    2 root     root          4096 May 24 14:16 containers
drwx------    3 root     root          4096 May 24 14:16 image
drwxr-x---    3 root     root          4096 May 24 14:16 network
drwx------    2 root     root          4096 May 24 14:46 tmp
drwx------    2 root     root          4096 May 24 14:16 trust
drwx------    2 root     root          4096 May 24 14:16 volumes
```

```
Harpreet@HSG-PC MINGW64 ~
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

Harpreet@HSG-PC MINGW64 ~
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE

Harpreet@HSG-PC MINGW64 ~
$ docker volume ls
DRIVER              VOLUME NAME

Harpreet@HSG-PC MINGW64 ~
$ docker network ls
NETWORK ID          NAME                DRIVER
fc8dcdcb223a        bridge              bridge
5eed1dfa0d4a        host                host
e022f5816a7e        none                null
afc211e599bb        npml_npmlnet        bridge
4e327cf6fc1b        reactflux_rrnet     bridge
```

**Comment by thaJeztah** [comment]
sorry, I don't have other ideas at this point. perhaps @nathanleclaire has some thoughts?

**Comment by hgill** [comment]
Ok, thanks for looking at it. For anyone who looks at this next, I did a "sudo chmod -R 755 ." in the docker folder to see what's inside. Hope this helps with a debug.

```
docker@default:/mnt/sda1/var/lib/docker$ sudo ls -al -R
.:
total 36
drwxr-xr-x    9 root     root          4096 May 24 14:16 .
drwxr-xr-x    4 root     root          4096 May 24 14:16 ..
drwxr-xr-x    5 root     root          4096 May 24 14:16 aufs
drwxr-xr-x    2 root     root          4096 May 24 14:16 containers
drwxr-xr-x    3 root     root          4096 May 24 14:16 image
drwxr-xr-x    3 root     root          4096 May 24 14:16 network
drwxr-xr-x    2 root     root          4096 May 24 14:46 tmp
drwxr-xr-x    2 root     root          4096 May 24 14:16 trust
drwxr-xr-x    2 root     root          4096 May 24 14:16 volumes

./aufs:
total 20
drwxr-xr-x    5 root     root          4096 May 24 14:16 .
drwxr-xr-x    9 root     root          4096 May 24 14:16 ..
drwxr-xr-x    2 root     root          4096 May 24 14:16 diff
drwxr-xr-x    2 root     root          4096 May 24 14:16 layers
drwxr-xr-x    2 root     root          4096 May 24 14:16 mnt

./aufs/diff:
total 8
drwxr-xr-x    2 root     root          4096 May 24 14:16 .
drwxr-xr-x    5 root     root          4096 May 24 14:16 ..

./aufs/layers:
total 8
drwxr-xr-x    2 root     root          4096 May 24 14:16 .
drwxr-xr-x    5 root     root          4096 May 24 14:16 ..

./aufs/mnt:
total 8
drwxr-xr-x    2 root     root          4096 May 24 14:16 .
drwxr-xr-x    5 root     root          4096 May 24 14:16 ..

./containers:
total 8
drwxr-xr-x    2 root     root          4096 May 24 14:16 .
drwxr-xr-x    9 root     root          4096 May 24 14:16 ..

./image:
total 12
drwxr-xr-x    3 root     root          4096 May 24 14:16 .
drwxr-xr-x    9 root     root          4096 May 24 14:16 ..
drwxr-xr-x    5 root     root          4096 May 24 14:16 aufs

./image/aufs:
total 24
drwxr-xr-x    5 root     root          4096 May 24 14:16 .
drwxr-xr-x    3 root     root          4096 May 24 14:16 ..
drwxr-xr-x    2 root     root          4096 May 24 14:16 distribution
drwxr-xr-x    4 root     root          4096 May 24 14:16 imagedb
drwxr-xr-x    2 root     root          4096 May 24 14:16 layerdb
-rwxr-xr-x    1 root     root            19 May 24 14:16 repositories.json

./image/aufs/distribution:
total 8
drwxr-xr-x    2 root     root          4096 May 24 14:16 .
drwxr-xr-x    5 root     root          4096 May 24 14:16 ..

./image/aufs/imagedb:
total 16
drwxr-xr-x    4 root     root          4096 May 24 14:16 .
drwxr-xr-x    5 root     root          4096 May 24 14:16 ..
drwxr-xr-x    3 root     root          4096 May 24 14:16 content
drwxr-xr-x    3 root     root          4096 May 24 14:16 metadata

./image/aufs/imagedb/content:
total 12
drwxr-xr-x    3 root     root          4096 May 24 14:16 .
drwxr-xr-x    4 root     root          4096 May 24 14:16 ..
drwxr-xr-x    2 root     root          4096 May 24 14:16 sha256

./image/aufs/imagedb/content/sha256:
total 8
drwxr-xr-x    2 root     root          4096 May 24 14:16 .
drwxr-xr-x    3 root     root          4096 May 24 14:16 ..

./image/aufs/imagedb/metadata:
total 12
drwxr-xr-x    3 root     root          4096 May 24 14:16 .
drwxr-xr-x    4 root     root          4096 May 24 14:16 ..
drwxr-xr-x    2 root     root          4096 May 24 14:16 sha256

./image/aufs/imagedb/metadata/sha256:
total 8
drwxr-xr-x    2 root     root          4096 May 24 14:16 .
drwxr-xr-x    3 root     root          4096 May 24 14:16 ..

./image/aufs/layerdb:
total 8
drwxr-xr-x    2 root     root          4096 May 24 14:16 .
drwxr-xr-x    5 root     root          4096 May 24 14:16 ..

./network:
total 12
drwxr-xr-x    3 root     root          4096 May 24 14:16 .
drwxr-xr-x    9 root     root          4096 May 24 14:16 ..
drwxr-xr-x    2 root     root          4096 May 24 16:16 files

./network/files:
total 52
drwxr-xr-x    2 root     root          4096 May 24 16:16 .
drwxr-xr-x    3 root     root          4096 May 24 14:16 ..
srwxr-xr-x    1 root     root             0 May 24 16:04 6b99ddc773f7b10f0617f9a6816768b8d7404fe37afc717a24979fca15d20905.sock
srwxr-xr-x    1 root     root             0 May 24 16:16 9a15adb71f0c00b72d7f232eb79b2d94b0bc6e9f3f37e4d7b6f0a4aebdd9ff29.sock
srwxr-xr-x    1 root     root             0 May 24 14:31 eb50abffd0b8cd3b9cfbb0391c2b248fbbdd2d75c990027b2f8b6da5e101fb72.sock
-rwxr-xr-x    1 root     root         65536 May 24 16:16 local-kv.db

./tmp:
total 62288
drwxr-xr-x    2 root     root          4096 May 24 14:46 .
drwxr-xr-x    9 root     root          4096 May 24 14:16 ..
-rwxr-xr-x    1 root     root            32 May 24 14:28 GetImageBlob227923459
-rwxr-xr-x    1 root     root          1442 May 24 14:28 GetImageBlob466840454
-rwxr-xr-x    1 root     root      39161720 May 24 14:30 GetImageBlob539803700
-rwxr-xr-x    1 root     root           215 May 24 14:28 GetImageBlob871104301
-rwxr-xr-x    1 root     root      24599606 May 24 14:30 GetImageBlob905365160

./trust:
total 8
drwxr-xr-x    2 root     root          4096 May 24 14:16 .
drwxr-xr-x    9 root     root          4096 May 24 14:16 ..

./volumes:
total 32
drwxr-xr-x    2 root     root          4096 May 24 14:16 .
drwxr-xr-x    9 root     root          4096 May 24 14:16 ..
-rwxr-xr-x    1 root     root         32768 May 24 16:16 metadata.db
```

**Comment by nathanleclaire** [comment]
Did you _switch_ storage drivers?  This can re-set the state of your container images.

Since it sounds like you may have been shutting down the VMs in an "unsafe" manner, that could also potentially contribute to data loss, although it seems unlikely.

Flocker is for migrating volumes across hosts IIRC, so I don't know if it will help you here, but backups should always be possible using the usual utilities (`mysqldump` etc.) and a bit of glue.

If you can't `find` the files you're after from the root directory of the VM, it's likely the data is just gone.  Generally we recommend that you should aim to be able to do a from-scratch restore of your application (including seeding and migrating the database) with relative ease, specifically to prevent coupling the application's state to one particular machine.

**Comment by hgill** [comment]
I 'tried' using a --driver flocker option about a week back on a new disposable data container, but the data didn't go then, think it went just yesterday. But the driver command errored, so doubt that could have caused it.

But as the issue cannot be easily reproduced, and no one else has reported similar, I guess you can consider this a one-off case and close the issue. The explanations above have given enough perspectives, will be better prepared if it happens again. 

Thanks a ton for your help. Docker is amazing by the way, very liberating.


PS:
Feature suggestion: For non-glue backups,  'docker volume export/import <data_volume>' > tar? Just a thin wrapper around the [recommended backup method](https://docs.docker.com/v1.8/userguide/dockervolumes/#backup-restore-or-migrate-data-volumes) - this will promote named volumes, i feel definitely a good practice over container backups.

**Comment by thaJeztah** [comment]
@hgill yes volume export/import or `cp` command was suggested a while back; it was rejected first, but perhaps we could give it another though (although the official method works indeed) 

Let me close this issue then
