### ISSUE TITLE
docker daemon throws bad listen address format error arm64

### ISSUE THREAD

**Issue by kobessas** [docker/docker#22950]
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   5604cbe
 Built:        Mon May  2 17:58:46 2016
 OS/Arch:      linux/arm64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

```

**Output of `docker info`:**

```
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
[root@alarm /]# uname -a
Linux alarm 3.14.29-21-ARCH #1 SMP PREEMPT Thu Apr 28 19:18:04 MDT 2016 aarch64 GNU/Linux
[root@alarm /]# docker -v
Docker version 1.11.1, build 5604cbe
[root@alarm /]# containerd -v
containerd version 0.2.0 commit: 121437994cb2f91c45b15039f0d6b077435d95f2

```

**Steps to reproduce the issue:**
1. Compile containerd commit 121437994cb2f91c45b15039f0d6b077435d95f2
1.1 (latest master as of 24/05/2016 throws the same error)
2. Try to start docker daemon
3. Docker throws FATA[0000] bad listen address format /var/run/docker/libcontainerd/docker-containerd.sock, expected proto://address

**Describe the results you received:**
[root@alarm /]# docker daemon                                                              
INFO[0000] New containerd process, pid: 5293
           
WARN[0000] containerd: low RLIMIT_NOFILE changing to max  current=1024 max=4096
FATA[0000] bad listen address format /var/run/docker/libcontainerd/docker-containerd.sock, expected proto://address

**Describe the results you expected:**
Daemon should start normally

**Additional information you deem important (e.g. issue happens only occasionally):**

```
# Used this PKGBUILD
pkgname=containerd
pkgver=0.2.0
pkgrel=1
pkgdesc='A daemon to control runC, built for performance and density'
url='https://containerd.tools/'
depends=('glibc' 'runc')
makedepends=('go' 'git')
arch=('aarch64')
source=("git+https://github.com/docker/containerd.git#commit=121437994cb2f91c45b15039f0d6b077435d95f2")
license=("APACHE")
md5sums=('SKIP')

build() {
  export GOPATH="$srcdir"
  mkdir -p src/github.com/docker
  ln -rsf containerd src/github.com/docker
  cd src/github.com/docker/containerd
  LDFLAGS= make
}

package() {
  cd src/github.com/docker/containerd/bin
  for file in $(find . -type f -print); do
    install -Dm755 $file $pkgdir/usr/bin/$file
  done
}
```

**Comment by james10174** [comment]
@kobessas I was trying to get beaglebone with archlinux to work with docker. I think I had some issues with starting the daemon due to it trying to use aufs. Try the following.

mv /var/lib/docker/aufs/ /var/lib/docker/aufs-temp

**Comment by justincormack** [comment]
I don't currently have an arm64 build environment, but hoping to get mine back up soon and can look at this. How did you build docker? Does it work if you build from source using the official build process?

**Comment by james10174** [comment]
I think using archlinux I just installed the package . pacman -S docker . Then you move the folder with aufs so docker cannot use it by default. Again been awhile since getting it to work on beaglebone 32 bit arm. I think I had to do some other things to. I will if tomorrow if I can log in to beaglebone to see the startup script.

**Comment by coolljt0725** [comment]
I think containerd `0.2.0` is not supported on arm64, it will throw error 
`FATA[0000] containerd: epoll wait                        error=function not implemented`
the master branch support run on arm64.

**Comment by cpuguy83** [comment]
IIRC, this format changed since 1.11, you'd need to use docker master to have this interact properly.

**Comment by kobessas** [comment]
@james10174 I will try later today.

@coolljt0725 What you are saying is indeed true but for version 0.1.0. The commit of containerd I am using solves exactly this problem. See https://github.com/docker/containerd/commit/121437994cb2f91c45b15039f0d6b077435d95f2

@cpuguy83 Do you mean that I have to compile the latest master in order for it to work? 

@justincormack @cpuguy83 I am already using the latest 1.11.1 tag. See https://github.com/archlinuxarm/PKGBUILDs/blob/master/community/docker/PKGBUILD

**Comment by cpuguy83** [comment]
I mean it looks like you are using a containerd that is not compatible with docker 1.11.
You can probably start containerd manually and then tell docker where the containerd socket is so it doesn't try to start it up automatically.

**Comment by kobessas** [comment]
Latest docker master (1.12.0-dev) starts up correctly with latest containerd master on my ODROID C2 (armv8).

**Comment by clnperez** [comment]
We hit this as well (and the issue was we were using a docker dev container in a 1.11 branch, which we'd built against master earlier - so that was an easy rebuild to fix).

FYI: This commit appends the proto to the path: docker/docker@6889c3276c6895a8440dc8883b8cd608793199f3  -- though I'm not suggesting you just cherry-pick that as a workaround. I was just curious so I looked it up.
