### ISSUE TITLE
Please update for AWS-SDK-GO v1.1.*

### ISSUE THREAD

**Issue by onlyjob** [docker/docker#22961]
It would be nice to update Docker for [latest release of aws-sdk-go](https://github.com/aws/aws-sdk-go/releases) v1.1.* as Docker still uses [v0.9.9](https://github.com/docker/docker/blob/master/hack/vendor.sh#L126).

Thanks.

**Comment by phemmer** [comment]
Is there any particular reason? Skimming through the releases, it looks like they all just add new features.

**Comment by onlyjob** [comment]
Staying up to date is one reason. Also it would help us to Build Docker in Debian where (at the moment) we have to reuse _aws-sdk-go_ v1.1.14.
Unfortunately there were incompatible changes. For example compilation of Docker 1.11.0 fails as follows with _aws-sdk-go_ v1.1.14:

~~~~
# github.com/docker/docker/daemon/logger/awslogs 
src/github.com/docker/docker/daemon/logger/awslogs/cloudwatchlogs.go:72: undefined: defaults.DefaultConfig in defaults.DefaultConfig.Region 
src/github.com/docker/docker/daemon/logger/awslogs/cloudwatchlogs.go:72: cannot assign to defaults.DefaultConfig.Region 
src/github.com/docker/docker/daemon/logger/awslogs/cloudwatchlogs.go:124: undefined: defaults.DefaultConfig 
src/github.com/docker/docker/daemon/logger/awslogs/cloudwatchlogs.go:126: undefined: defaults.DefaultConfig in defaults.DefaultConfig.Merge 
~~~~

**Comment by thaJeztah** [comment]
ping @samuelkarp could you have a look?

**Comment by yongtang** [comment]
I created a pull request to update the aws-sdk-go to v1.1.30. The `defaults.DefaultConfig` build error has been fixed in the pull request.

**Comment by onlyjob** [comment]
Thank you. :)
