### ISSUE TITLE
Internal server error (500) on page https://docs.docker.com/opensource/workflow/make-a-contribution/

### ISSUE THREAD

**Issue by shanavas786** [docker/docker#22977]
Internal server error (500) on page https://docs.docker.com/opensource/workflow/make-a-contribution/
![docker](https://cloud.githubusercontent.com/assets/5337197/15537431/03d37df4-227f-11e6-805e-23fc20ab095c.png)

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by phemmer** [comment]
Works for me. You still seeing it?

**Comment by shanavas786** [comment]
Nope. Its fine now.
