### ISSUE TITLE
excessive traffic generated from overlay networking on kernels <3.16

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#22975]
This issue is for tracking https://github.com/docker/libnetwork/issues/1189, which is still being investigated.

/cc @mavenugo @mlaventure

**Comment by thaJeztah** [comment]
After discussion with @mavenugo / @vikstrous, moving this to the 1.12 milestone

**Comment by tiborvass** [comment]
Ping @mavenugo what's up with this?

**Comment by tiborvass** [comment]
Seems to have been fixed by libnetwork vendoring after https://github.com/docker/libnetwork/pull/1246 was merged.
