### ISSUE TITLE
[Minor] -h option not supported in `docker run`. It should be similar everywhere e.g `docker build` which supports both -h/--help.

### ISSUE THREAD

**Issue by codevulture** [docker/docker#22972]
**Output of `docker version`:**

```
Docker version 1.11.1, build 5604cbe
```

**Output of `docker info`:**

```
root@janonymous-virtual-machine:/home/janonymous/Desktop# docker info
Containers: 11
 Running: 9
 Paused: 0
 Stopped: 2
Images: 11
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 68
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.13.0-86-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 11.49 GiB
Name: janonymous-virtual-machine
ID: XTKE:M36G:XMIJ:XZ4X:6TBP:M7BH:UCX6:QFLA:7IID:LBJ4:HM3D:ZKDT
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.Steps shown below

**Describe the results you received:**
root@janonymous-virtual-machine:/home/janonymous/Desktop# docker images -h

Usage:	docker images [OPTIONS] [REPOSITORY[:TAG]]

List images

  -a, --all          Show all images (default hides intermediate images)
  --digests          Show digests
  -f, --filter=[]    Filter output based on conditions provided
  --format           Pretty-print images using a Go template
  --help             Print usage
  --no-trunc         Don't truncate output
  -q, --quiet        Only show numeric IDs
root@janonymous-virtual-machine:/home/janonymous/Desktop# docker run -h
flag needs an argument: -h
See 'docker run --help'.

**Describe the results you expected:**
Same as docker build as shown above.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by phemmer** [comment]
> Same as docker build as shown above.

I think you missed something. But I know what you meant :-)

What are your thoughts on just removing `-h`? I find `--help` is pretty standard across utilities. `-h` is not.

**Comment by thaJeztah** [comment]
Yes, we discussed removing `-h` a while back (also a reason for not actually *printing* it in the Usage output), because we cannot use it consistently on all commands (e.g., it conflicts with `docker create -h`).

I opened a pull-request to officially deprecate `-h`; https://github.com/docker/docker/pull/22980

**Comment by codevulture** [comment]
Thanks for replies and fixes, i was starting to setup and play with dockers when i saw some minor things i thought to mention.  i like to use -h personally bcs its easier to type ;) , but the main point was to maintain consistency all over so its cool wth me :)

**Comment by yongtang** [comment]
I think this is related to #20093 as well.
