### ISSUE TITLE
Is there any possibilities to update the running container when the image having new changes? 

### ISSUE THREAD

**Issue by ewallteam** [docker/docker#23013]
Hi All,

I have installed the docker and run the container with my Magento docker image on digitalocean droplet. I want my running container will update automatically when I have made any changes on image. Is it possible? Please let me know way to achieve the same.

**Comment by cpuguy83** [comment]
Not possible, sorry.

**Comment by cpuguy83** [comment]
The best way to handle this is for any writes you do, do it in a volume, then you can attach the volume to a new container with the updated image.

**Comment by thaJeztah** [comment]
You can use webhooks though, to automate things when a new image is built on docker hub; https://docs.docker.com/docker-hub/webhooks/. Docker Cloud can make this even easier, and redeploy services if a new images is ready; https://docs.docker.com/docker-cloud/apps/auto-redeploy/
