### ISSUE TITLE
Docker run fails to create directories in mapped volumes when chained with other commands

### ISSUE THREAD

**Issue by cookandy** [docker/docker#23027]
**Output of `docker version`:**

```
Docker version 1.9.1, build 9894698
```

**Output of `docker info`:**

```
Containers: 8
Images: 150
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.3.6-coreos
Operating System: CoreOS 899.17.0
CPUs: 2
Total Memory: 5.833 GiB
Name: xxx.domain.com
ID: XRY2:CD6R:SVHR:J4NR:VVNR:2M6X:UBED:7TOP:LWIE:Q4ZN:7H2V:JUZY
```

**Steps to reproduce the issue:**

Run an image with a mapped volume and try to create a directory in a chained command.  It will fail.

For example, in the example below I am mapping the local `/data` directory to `/opt/test` in the container, and the creating the `/opt/test/abc` directory with the `run` command.  **This works**:

```docker run --rm -v /data/:/opt/test/ fedora mkdir /opt/test/abc```

However, if I try to add a command before it (`echo hello`), and the daisy chain the command with `&&`, **it fails**:

```docker run --rm -v /data/:/opt/test/ fedora echo hello && mkdir /opt/test/abc```

Output:
```
hello
mkdir: cannot create directory '/opt/test/abc': No such file or directory
```

**Note:** this bug only seems to affect mapped volumes.  For example, creating a directory in the root of the file system after the echo command seems to work:

```docker run --rm -v /data/:/opt/test/ fedora echo hello && mkdir /abc```

Additionally, this doesn't seem to be restricted to just `mkdir`.  Other commands fail when chained together and are operating on the mapped volume.  For example in the example below, the `/opt/test/abc` directory gets created...

```docker run --rm -v /data/:/opt/test/ fedora mkdir /opt/test/abc && echo hello > /opt/test/abc/1.txt```

but the echo fails with this error:

```bash: /opt/test/abc/1.txt: No such file or directory```

**Describe the results you received:**

```mkdir: cannot create directory '/opt/test/abc': No such file or directory```

**Describe the results you expected:**

I expected the `/opt/test/abc` directory to get created after the `echo` command.

**Comment by cpuguy83** [comment]
This is because the `&&` is a new shell command on the client system.
Use `docker run --rm -v /data:/opt/test/ fedora /bin/sh -c 'mkdir /opt/test/abc && echo hello > /opt/test/abc/1.txt'`
