### ISSUE TITLE
Docker diff showing entire rootfs

### ISSUE THREAD

**Issue by shishir-a412ed** [docker/docker#23021]
On docker upstream binary, when I run a  new container and do a `docker diff`. It shows the entire rootfs.
Ideally it should show nothing. I think the diff is comparing to nothing. 

**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.4
 Git commit:   a41e823
 Built:        Wed May 25 15:46:25 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.4
 Git commit:   a41e823
 Built:        Wed May 25 15:46:25 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.12.0-dev
Storage Driver: devicemapper
 Pool Name: docker-8:19-16121939-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 255.5 MB
 Data Space Total: 107.4 GB
 Data Space Available: 107.1 GB
 Metadata Space Used: 753.7 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.109 (2015-09-22)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.2-301.fc23.x86_64
Operating System: Fedora 23 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.72 GiB
Name: dhcp-10-19-62-127.boston.devel.redhat.com
ID: M4W2:KN7L:WVHC:KGXZ:ZNAN:CJJJ:5PWS:V7VV:GPHO:65Y3:4UEP:MCUX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: shm32
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora 23

**Steps to reproduce the issue:**
1. docker run -it fedora /bin/bash
2. docker ps (Get the container ID)
3. docker diff {container_id}

**Describe the results you received:**
Entire rootfs is listed as diff.
https://gist.github.com/shishir-a412ed/6de38a2aa5beeea30381e634fae706ce

**Describe the results you expected:**
docker diff should show nothing.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
Wondering if this is related to your other report (inconsistent file paths). What happens if you use a different graph-driver? e.g. `dockerd --debug --storage-driver=overlay`?

**Comment by shishir-a412ed** [comment]
@thaJeztah you are right. Both the problems (Issue #22992 and this one) are not there with overlay.
It looks like these problems are only there for devicemapper.

**Comment by thaJeztah** [comment]
@shishir-a412ed is this issue also fixed with https://github.com/docker/docker/pull/23067?

**Comment by shishir-a412ed** [comment]
@thaJeztah Yes this is fixed now. Closing this.

**Comment by thaJeztah** [comment]
Thanks @shishir-a412ed
