### ISSUE TITLE
Not erroring if security profile requested but not possible to apply

### ISSUE THREAD

**Issue by justincormack** [docker/docker#23031]
This came up on the booth at Oscon. If you request applying a seccomp profile (or apparmor) but you are talking to an engine that does not have the ability to do that as it was not compiled with support, it is silently ignored. I think it should probably error out if you explicitly ask for a profile, but not error if you ask for `unconfined`. It is a really easy change but wanting feedback as this is a behaviour change.

cc @jfrazelle

**Comment by thaJeztah** [comment]
SGTM better be explicit and fail, otherwise people may incorrectly think they're "protected" by the profile

**Comment by justincormack** [comment]
Yes, in this case the user was just confused as was trying to test it worked, but it never did anything.

I guess it might also be worth being able to explicitly ask for `default` as a profile, so that you can guarantee that you are running with the default profile and error if not as well.

**Comment by jfrazelle** [comment]
good call! error out is good

**Comment by jfrazelle** [comment]
_if_ of course they explicitly pass a custom one
