### ISSUE TITLE
Сan not install Docker on Debian 7.10 VPS with Docker-Machine

### ISSUE THREAD

**Issue by boramod** [docker/docker#23034]
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:44:17 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 94
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 87
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.8-boot2docker
Operating System: Boot2Docker 1.11.1 (TCL 7.0); HEAD : 7954f54 - Wed Apr 27 16:36:45 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: default
ID: EQHX:XD4H:FNDT:ADK4:T2RP:OVW2:FQSX:UGES:UBJC:IKZ7:YG5K:HBOC
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 30
 System Time: 2016-05-26T22:33:51.30457097Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

***1. Mac OS X 10.11 Desktop with installed Docker Toolbox***

***2. VPS:***
CPU: Intel Xeon, 1
RAM: 1024 Mb
SSD: 20 000 Mb

OS (fresh install):
Debian-7-amd64 Wheezy
Kernel: 3.2.0-4-amd64
Ver.: 7.10

**Steps to reproduce the issue:**
1. Setup VPS, user, rules, ssh keys.
2. Try to install Docker by Docker-Machine from Desktop Mac:
`docker-machine -D create
--driver generic
--generic-ip-address=93.170.253.41
--generic-ssh-user al
--generic-ssh-key ~/.ssh/id_rsa testVM`

**Describe the results you received:**
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 docker-engine : Depends: init-system-helpers (>= 1.18~) but it is not installable
                 Recommends: aufs-tools but it is not going to be installed
                 Recommends: cgroupfs-mount but it is not installable or
                             cgroup-lite but it is not installable
                 Recommends: git but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

Error creating machine: Error running provisioning: error installing docker: 

Opting out of crash reporting.
```
<details> 
  <summary>Detailed debug information</summary>
Alexs-iMac:php-dockerized al$ docker-machine -D create --driver generic --generic-ip-address=93.170.253.41 --generic-ssh-user al --generic-ssh-key ~/.ssh/id_rsa testVM
Docker Machine Version:  0.7.0, build a650a40
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver generic
Plugin server listening at address 127.0.0.1:51008
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetMachineName
(flag-lookup) Calling .DriverName
(flag-lookup) Calling .GetCreateFlags
Found binary path at /usr/local/bin/docker-machine
Launching plugin server for driver generic
Plugin server listening at address 127.0.0.1:51012
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(testVM) Calling .GetMachineName
(testVM) Calling .DriverName
(testVM) Calling .GetCreateFlags
(testVM) Calling .SetConfigFromFlags
Running pre-create checks...
(testVM) Calling .PreCreateCheck
(testVM) Calling .GetConfigRaw
Creating machine...
(testVM) Calling .Create
(testVM) Importing SSH key...
(testVM) Calling .GetConfigRaw
(testVM) DBG | IP: 93.170.253.41
(testVM) Calling .DriverName
(testVM) Calling .DriverName
Waiting for machine to be running, this may take a few minutes...
(testVM) Calling .GetState
Detecting operating system of created instance...
Waiting for SSH to be available...
Getting to WaitForSSH function...
(testVM) Calling .GetSSHHostname
(testVM) Calling .GetSSHPort
(testVM) Calling .GetSSHKeyPath
(testVM) Calling .GetSSHKeyPath
(testVM) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /Users/al/.docker/machine/machines/testVM/id_rsa (-rw-------)
&{[-F /dev/null -o BatchMode=yes -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none al@93.170.253.41 -o IdentitiesOnly=yes -i /Users/al/.docker/machine/machines/testVM/id_rsa -p 22] /usr/bin/ssh <nil>}
About to run SSH command:
exit 0
SSH cmd err, output: <nil>: 
Detecting the provisioner...
(testVM) Calling .GetSSHHostname
(testVM) Calling .GetSSHPort
(testVM) Calling .GetSSHKeyPath
(testVM) Calling .GetSSHKeyPath
(testVM) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /Users/al/.docker/machine/machines/testVM/id_rsa (-rw-------)
&{[-F /dev/null -o BatchMode=yes -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none al@93.170.253.41 -o IdentitiesOnly=yes -i /Users/al/.docker/machine/machines/testVM/id_rsa -p 22] /usr/bin/ssh <nil>}
About to run SSH command:
cat /etc/os-release
SSH cmd err, output: <nil>: PRETTY_NAME="Debian GNU/Linux 7 (wheezy)"
NAME="Debian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support/"
BUG_REPORT_URL="http://bugs.debian.org/"

found compatible host: debian
Provisioning with debian...
(testVM) Calling .GetSSHHostname
(testVM) Calling .GetSSHPort
(testVM) Calling .GetSSHKeyPath
(testVM) Calling .GetSSHKeyPath
(testVM) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /Users/al/.docker/machine/machines/testVM/id_rsa (-rw-------)
&{[-F /dev/null -o BatchMode=yes -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none al@93.170.253.41 -o IdentitiesOnly=yes -i /Users/al/.docker/machine/machines/testVM/id_rsa -p 22] /usr/bin/ssh <nil>}
About to run SSH command:
stat -f -c %T /var/lib
SSH cmd err, output: <nil>: ext2/ext3

No storagedriver specified, using aufs

installing sudo
(testVM) Calling .GetSSHHostname
(testVM) Calling .GetSSHPort
(testVM) Calling .GetSSHKeyPath
(testVM) Calling .GetSSHKeyPath
(testVM) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /Users/al/.docker/machine/machines/testVM/id_rsa (-rw-------)
&{[-F /dev/null -o BatchMode=yes -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none al@93.170.253.41 -o IdentitiesOnly=yes -i /Users/al/.docker/machine/machines/testVM/id_rsa -p 22] /usr/bin/ssh <nil>}
About to run SSH command:
if ! type sudo; then apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y sudo; fi
SSH cmd err, output: <nil>: sudo is /usr/bin/sudo

setting hostname
(testVM) Calling .GetMachineName
(testVM) Calling .GetSSHHostname
(testVM) Calling .GetSSHPort
(testVM) Calling .GetSSHKeyPath
(testVM) Calling .GetSSHKeyPath
(testVM) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /Users/al/.docker/machine/machines/testVM/id_rsa (-rw-------)
&{[-F /dev/null -o BatchMode=yes -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none al@93.170.253.41 -o IdentitiesOnly=yes -i /Users/al/.docker/machine/machines/testVM/id_rsa -p 22] /usr/bin/ssh <nil>}
About to run SSH command:
sudo hostname testVM && echo "testVM" | sudo tee /etc/hostname
SSH cmd err, output: <nil>: testVM

(testVM) Calling .GetSSHHostname
(testVM) Calling .GetSSHPort
(testVM) Calling .GetSSHKeyPath
(testVM) Calling .GetSSHKeyPath
(testVM) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /Users/al/.docker/machine/machines/testVM/id_rsa (-rw-------)
&{[-F /dev/null -o BatchMode=yes -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none al@93.170.253.41 -o IdentitiesOnly=yes -i /Users/al/.docker/machine/machines/testVM/id_rsa -p 22] /usr/bin/ssh <nil>}
About to run SSH command:

		if ! grep -xq .*testVM /etc/hosts; then
			if grep -xq 127.0.1.1.* /etc/hosts; then 
				sudo sed -i 's/^127.0.1.1.*/127.0.1.1 testVM/g' /etc/hosts; 
			else 
				echo '127.0.1.1 testVM' | sudo tee -a /etc/hosts; 
			fi
		fi
SSH cmd err, output: <nil>: 
installing base packages
(testVM) Calling .GetSSHHostname
(testVM) Calling .GetSSHPort
(testVM) Calling .GetSSHKeyPath
(testVM) Calling .GetSSHKeyPath
(testVM) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /Users/al/.docker/machine/machines/testVM/id_rsa (-rw-------)
&{[-F /dev/null -o BatchMode=yes -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none al@93.170.253.41 -o IdentitiesOnly=yes -i /Users/al/.docker/machine/machines/testVM/id_rsa -p 22] /usr/bin/ssh <nil>}
About to run SSH command:
sudo apt-get update
SSH cmd err, output: <nil>: Hit http://ftp.debian.org wheezy Release.gpg
Hit http://ftp.debian.org wheezy Release
Hit http://security.debian.org wheezy/updates Release.gpg
Hit http://security.debian.org wheezy/updates Release
Hit http://ftp.debian.org wheezy/main Sources
Hit http://ftp.debian.org wheezy/contrib Sources
Hit http://security.debian.org wheezy/updates/main Sources
Hit http://ftp.debian.org wheezy/main amd64 Packages
Hit http://security.debian.org wheezy/updates/contrib Sources
Hit http://ftp.debian.org wheezy/contrib amd64 Packages
Hit http://ftp.debian.org wheezy/contrib Translation-en
Hit http://security.debian.org wheezy/updates/main amd64 Packages
Hit http://ftp.debian.org wheezy/main Translation-en
Hit http://security.debian.org wheezy/updates/contrib amd64 Packages
Hit http://security.debian.org wheezy/updates/contrib Translation-en
Hit http://security.debian.org wheezy/updates/main Translation-en
Reading package lists...

package: action=install name=curl
(testVM) Calling .GetSSHHostname
(testVM) Calling .GetSSHPort
(testVM) Calling .GetSSHKeyPath
(testVM) Calling .GetSSHKeyPath
(testVM) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /Users/al/.docker/machine/machines/testVM/id_rsa (-rw-------)
&{[-F /dev/null -o BatchMode=yes -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none al@93.170.253.41 -o IdentitiesOnly=yes -i /Users/al/.docker/machine/machines/testVM/id_rsa -p 22] /usr/bin/ssh <nil>}
About to run SSH command:
DEBIAN_FRONTEND=noninteractive sudo -E apt-get install -y  curl
SSH cmd err, output: <nil>: Reading package lists...
Building dependency tree...
Reading state information...
curl is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

installing docker
(testVM) Calling .GetSSHHostname
(testVM) Calling .GetSSHPort
(testVM) Calling .GetSSHKeyPath
(testVM) Calling .GetSSHKeyPath
(testVM) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /Users/al/.docker/machine/machines/testVM/id_rsa (-rw-------)
&{[-F /dev/null -o BatchMode=yes -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none al@93.170.253.41 -o IdentitiesOnly=yes -i /Users/al/.docker/machine/machines/testVM/id_rsa -p 22] /usr/bin/ssh <nil>}
About to run SSH command:
if ! type docker; then curl -sSL https://get.docker.com | sh -; fi
SSH cmd err, output: exit status 100: bash: line 0: type: docker: not found
+ sudo -E sh -c apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --secret-keyring /tmp/tmp.cxUQBNJUF9 --trustdb-name /etc/apt//trustdb.gpg --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d//debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d//debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d//debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d//debian-archive-squeeze-automatic.gpg --keyring /etc/apt/trusted.gpg.d//debian-archive-squeeze-stable.gpg --keyring /etc/apt/trusted.gpg.d//debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d//debian-archive-wheezy-stable.gpg --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
gpg: requesting key 2C52609D from hkp server ha.pool.sks-keyservers.net
gpg: key 2C52609D: "Docker Release Tool (releasedocker) <docker@docker.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
+ break
+ sudo -E sh -c apt-key adv -k 58118E89F3A912897C070ADBF76221572C52609D >/dev/null
+ sudo -E sh -c mkdir -p /etc/apt/sources.list.d
+ dpkg --print-architecture
+ sudo -E sh -c echo deb [arch=amd64] https://apt.dockerproject.org/repo debian-wheezy main > /etc/apt/sources.list.d/docker.list
+ sudo -E sh -c sleep 3; apt-get update; apt-get install -y -q docker-engine
Hit http://security.debian.org wheezy/updates Release.gpg
Hit http://security.debian.org wheezy/updates Release
Hit http://security.debian.org wheezy/updates/main Sources
Hit http://security.debian.org wheezy/updates/contrib Sources
Hit http://security.debian.org wheezy/updates/main amd64 Packages
Hit http://security.debian.org wheezy/updates/contrib amd64 Packages
Hit http://security.debian.org wheezy/updates/contrib Translation-en
Hit http://security.debian.org wheezy/updates/main Translation-en
Get:1 https://apt.dockerproject.org debian-wheezy Release.gpg [801 B]
Get:2 https://apt.dockerproject.org debian-wheezy Release [19.7 kB]
Get:3 https://apt.dockerproject.org debian-wheezy/main amd64 Packages [4,643 B]
Hit http://ftp.debian.org wheezy Release.gpg
Hit http://ftp.debian.org wheezy Release
Hit http://ftp.debian.org wheezy/main Sources
Hit http://ftp.debian.org wheezy/contrib Sources
Hit http://ftp.debian.org wheezy/main amd64 Packages
Hit http://ftp.debian.org wheezy/contrib amd64 Packages
Hit http://ftp.debian.org wheezy/contrib Translation-en
Hit http://ftp.debian.org wheezy/main Translation-en
Ign https://apt.dockerproject.org debian-wheezy/main Translation-en_US
Ign https://apt.dockerproject.org debian-wheezy/main Translation-en
Fetched 25.2 kB in 3s (7,331 B/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 docker-engine : Depends: init-system-helpers (>= 1.18~) but it is not installable
                 Recommends: aufs-tools but it is not going to be installed
                 Recommends: cgroupfs-mount but it is not installable or
                             cgroup-lite but it is not installable
                 Recommends: git but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

Error creating machine: Error running provisioning: error installing docker: 

Opting out of crash reporting.

</details>

**Comment by thaJeztah** [comment]
Note that Debian 7 requires the back ports to be installed, and kernel 3.10 or higher is required for Docker to run; see https://docs.docker.com/engine/installation/linux/debian/#debian-wheezy-stable-7-x-64-bit.

Looking at the information you provided, that machine doesn't look to meet those requirements

**Comment by boramod** [comment]
@thaJeztah Many thanks for the quick response!
I thought that installing Docker to the VPS through Docker-Machine automatically check & adds a dependency such as Back Ports. Docker-Machine has a sudo privileges for it...
It was my delusion.
Thanks again for your answer!

**Comment by thaJeztah** [comment]
@boramod perhaps it's possible, but the best place to report that is the docker-machine issue tracker, where that code is maintained; https://github.com/docker/machine
