### ISSUE TITLE
Proposal/Enhancement: Dockerfile RUN should use sh -cl instead of sh -c

### ISSUE THREAD

**Issue by tarunlalwani** [docker/docker#23044]
Currently on the RUN command docker used sh -c 

https://github.com/docker/docker/blob/master/builder/dockerfile/dispatchers.go#L295

```go
 	if !attributes["json"] {
		if runtime.GOOS != "windows" {
			args = append([]string{"/bin/sh", "-c"}, args...)
		} else {
			args = append([]string{"cmd", "/S", "/C"}, args...)
		}
	}
```
Can we used sh -lc instead? What that does is it loads .profile or .shrc file as well. Currently there is no way to override host file for Build command and we are working on base images which need some updated entries in /etc/hosts 

Currently we have to ask all our developers to use below

```Dockerfile
FROM centos:7
RUN echo "echo This is a loaded from shell profile message" >> ~/.profile
ENV ENV=~/.profile
RUN sh -cl "yum update -y"
```

I know the change is manageable, bit wanted to know what's everyones opinion on changing the default behavior to sh -cl?

**Comment by cpuguy83** [comment]
I'd say have a look at #22489 and make sure we can set arguments for the shell command there.

**Comment by justincormack** [comment]
Yes #22489 will allow you to do `SHELL /bin/sh -cl` in your Dockerfile to achieve this. I don't think we want to change the default globally, as it could change the behaviour of existing files.

**Comment by tarunlalwani** [comment]
@justincormack , Looks exactly like what I wanted.
