### ISSUE TITLE
adding interface veth to bridge ovsbr0 failed: operation not supported.

### ISSUE THREAD

**Issue by peterwillcn** [docker/docker#23047]
adding interface veth5682e69 to bridge ovsbr0 failed: operation not supported.

**Comment by cpuguy83** [comment]
Please provide more details.
The issue template is there for a reason, unfortunately we cannot help with so little to go on.

**Comment by cpuguy83** [comment]
https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md

**Comment by cpuguy83** [comment]
Closing for now until we can get more detail.
