### ISSUE TITLE
Mysql container Fail to init DB with volume mount

### ISSUE THREAD

**Issue by sebglon** [docker/docker#23053]
**Output of `docker version`:**

```
(paste your output here)Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:38:55 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:38:55 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 57
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 54
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-22-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 740.5 MiB
Name: docker
ID: PRFJ:MIZ6:XOWX:2SU7:6MXS:PQOG:DZWC:NRJX:BE5H:WGYB:QJH4:AZXI
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
On physical Ubuntu and Centos

**Steps to reproduce the issue:**
1. create File $(pwd)/init-db/test.sh
```
#!/bin/bash
echo "HELLO ......."
 ```
2. docker run --rm -v $(pwd)/init-db:/docker-entrypoint-initdb.d -e MYSQL_ROOT_PASSWORD=toto   mysql

**Describe the results you received:**
On log i can see ```/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*```
But test.sh is on mounted volume

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
This work on docker 1.10.0 with this log:
```
/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/test.sh
HELLO .......
```

If i test my script with ``` run -it --rm -v $(pwd)/init-db:/docker-entrypoint-initdb.d -e MYSQL_ROOT_PASSWORD=toto --entrypoint /docker-entrypoint-initdb.d/test.sh  mysql``` the HELLO is shown

**Comment by cpuguy83** [comment]
Can you help me understand the problem. I'm not following here.
What are you trying to do?
Is the file mounted in the container?

**Comment by sebglon** [comment]
My ovjectif is to initialise DB with an external script that i wan't to mount with volume.

**Comment by sebglon** [comment]
Thist work with postgres Image but not with mysql or mariadb

**Comment by cpuguy83** [comment]
@sebglon Ok, this does not sound like a docker issue.

Please check the docs for the images you are using, and potentially you can open issues in the respective repos.
You can usually find the repos from the DockerHub page.

**Comment by sebglon** [comment]
This work on docker 1.10 but not on 1.11
