### ISSUE TITLE
Feature Request: docker search --limit

### ISSUE THREAD

**Issue by HariSekhon** [docker/docker#23055]
Feature Request to add a ```--limit``` option to the ```docker search``` command to allow returning a configurable number of results.

Currently it caps at 25 and there is no way I can see of changing the number of returned results (eg. if I wanted to list all of my docker repos and I have more than 25 there is no way to see them all in the docker search command).

I've written a quick tool to be able to do this for now with output similar to the official ```docker search``` command - it's in my [PyTools](https://github.com/harisekhon/pytools) github repo:

```
dockerhub_search.py --limit 50 TERM
```

```
dockerhub_search.py --help
Hari Sekhon - https://github.com/harisekhon/pytools

dockerhub_search.py version 0.3

Tool to search DockerHub repos and return a configurable number of results

Usage: dockerhub_search.py [options] TERM

Options:
  -n NUM, --num=NUM, --limit=NUM
                        Number of results to return (default: 50)
  -t secs, --timeout=secs
                        Timeout in secs (default: 10)
  -v, --verbose         Verbose mode (-v, -vv, -vvv)
  -V, --version         Show version and exit
  -h, --help            Show full help and exit
```

**Comment by yongtang** [comment]
@HariSekhon I created a pull request #23107 to add the flag `--limit` to `docker search`, based on the python script mentioned. Please take a look and let me know if there are any issues.
