### ISSUE TITLE
rpc err occurs when sending request to docker-containerd by container-ctr

### ISSUE THREAD

**Issue by TheBeeMan** [docker/docker#23052]
I setup docker-containerd manually with command"docker-containerd -l  unix:///var/run/docker/libcontainerd/docker-containerd.sock --runtime docker-runc --debug --metrics-interval=0"

Then I send container querying request to the containerd by "containerd-ctr --address unix:///var/run/docker/libcontainerd/docker-containerd.sock containers"

however, strange err occured like this:
[ctr] rpc error: code = 13 desc = get all pids for container: invalid character 'N' looking for beginning of value

what is wrong with it?

any help will be preciated.

**Comment by TheBeeMan** [comment]
in addtion, docker-containerd and containerd-ctr version is 0.2.0. I compile them with source code.

**Comment by cpuguy83** [comment]
Please open on github.com/docker/containerd where these live.
Thanks!
