### ISSUE TITLE
Windows proposal: implement single-host service discovery with `c:\Windows\System32\drivers\etc\hosts` rewrites

### ISSUE THREAD

**Issue by friism** [docker/docker#23068]
This is a proposal to add simple service discovery for containers on the single-host bridge network (which I think is NAT on Windows server) by rewriting the `c:\Windows\System32\drivers\etc\hosts` file. This is also how [service discovery works on Linux on the bridge network](https://docs.docker.com/engine/userguide/networking/default_network/configure-dns/).

The IPAddress of started containers is a available and I've checked that they're routable from other containers:

```
docker inspect --format '{{ json .NetworkSettings.Networks.nat.IPAddress }}' 8dccf7d0a4f0441820f6cb7991390b1b0b3ac8c660c1db514e6435e404dcca5e
"172.27.160.54"
```

Stefan has some old hackery, but I think that was necessary because `inspect` was not working on older Windows releases (eg. TP4): https://github.com/docker/docker-birthday-3/pull/165/files#diff-32b1d4f4a16110f0207b0c356fb94f48R2

cc @JMesser81 @taylorb-microsoft @StefanScherer @mavenugo

**Comment by StefanScherer** [comment]
Interesting. From a user's perspective it would help now to work with links and simple docker-compose.yml's until there are more sophisticated network features or helpers like registrator/traefik/...

The birthday hack was needed with TP4, retrieving the IP addresses is possible with `docker inspect` with TP5.

A related issue is #21762 with a fixed hostname inside each container. Many golang binaries, eg. `consul.exe`, are using this hostname to register services. I managed a workaround for a Consul agent with these commands in an entrypoint cmd script.

```
reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters" /v Hostname /t REG_SZ /d "%COMPUTERNAME%" /f
reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters" /v "NV Hostname" /t REG_SZ /d "%COMPUTERNAME%" /f
```

**Comment by JMesser81** [comment]
In principle I support this as a short-term solution for single node clusters / deployments.

How would the name:IP mapping be written to the C:\Windows\System32\drivers\etc\hosts file? I understand we could query the IP for all endpoint using docker inspect but not sure how these mappings would be placed inside each individual containers' hosts file.

**Comment by StefanScherer** [comment]
Here is an example with two Linux containers and a `docker-compose.yml` file to link from container `web` to container `db.

```
$ mkdir twonodes && cd twonodes
$ vi docker-compose.yml
```

Here is the sample yml file:

```yaml
db:
  image: ubuntu
  command: bash -c "sleep 360"

web:
  image: ubuntu
  command: bash -c "sleep 360"
  links:
    - db
```

Start the two containers with

```
$ docker-compose up -d
```

The container `web` has `/etc/hosts` entries like this:

```
$ docker-compose exec web cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.2	db 00a37030439b twonodes_db_1
172.17.0.2	db_1 00a37030439b twonodes_db_1
172.17.0.2	twonodes_db_1 00a37030439b
172.17.0.3	c93c94c05e66
```

Docker Compose adds `db` as well as the other forms `db_1`and `twonodes_db_1` (with the directory prefix).
And each container has its own hostname (in this case `c93c94c05e66`) as well in it.

**Comment by friism** [comment]
Closing, deprecated by https://github.com/docker/docker/pull/25987
