### ISSUE TITLE
master: build output comes before pull output...?

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#23064]
**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   6e721f6
 Built:        Fri May 27 16:12:02 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   6e721f6
 Built:        Fri May 27 16:12:02 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
$ docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 39
Server Version: 1.12.0-dev
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.6.0-fsociety
Operating System: Debian GNU/Linux stretch/sid
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.52 GiB
Name: debian
ID: LWLG:XJIB:M6QI:K4J2:JAIZ:6H4Q:E7FE:KZZU:VTSA:D2UH:Y7SO:YNMH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 15
 Goroutines: 29
 System Time: 2016-05-27T09:59:31.363440285-07:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Linux obvs, debian, you know the dealio

**Steps to reproduce the issue:**
1. Build a dockerfile
2.
3.

**Describe the results you received:**
Expected `pull` output then `build` output.

**Describe the results you expected:**

Got `build` output then `pull` info. And I already had `alpine` locally :/

```
$ make run
docker build --rm --force-rm -t r.j3ss.co/contained .
Sending build context to Docker daemon 17.11 MB
Step 1 : FROM alpine
 ---> 13e1761bf172
Step 2 : MAINTAINER Jessica Frazelle <jess@docker.com>
 ---> Using cache
 ---> 3a3611a0a666
Step 3 : ENV PATH /go/bin:/usr/local/go/bin:$PATH
 ---> Using cache
 ---> 8d32bc8c7523
Step 4 : ENV GOPATH /go
 ---> Using cache
 ---> feef1ccd128f
Step 5 : ENV GO15VENDOREXPERIMENT 1
 ---> Using cache
 ---> 2295970b7788
Step 6 : RUN apk update && apk add 	ca-certificates 	&& rm -rf /var/cache/apk/*
 ---> Using cache
 ---> 4a1705b913be
Step 7 : COPY *.go /go/src/github.com/jfrazelle/contained/
 ---> Using cache
 ---> 392068973145
Step 8 : COPY vendor /go/src/github.com/jfrazelle/contained/vendor
 ---> Using cache
 ---> 97378d929ba9
Step 9 : RUN buildDeps=' 		go 		git 		gcc 		libc-dev 		libgcc 	' 	set -x 	&& apk update 	&& apk add $buildDeps 	&& cd /go/src/github.com/jfrazelle/contained 	&& go build -o /usr/bin/contained . 	&& apk del $buildDeps 	&& rm -rf /var/cache/apk/* 	&& rm -rf /go 	&& echo "Build complete."
 ---> Using cache
 ---> cd3ed0cf50b7
Step 10 : COPY static /usr/src/contained/
 ---> Using cache
 ---> f24c7e4a7043
Step 11 : WORKDIR /usr/src/contained
 ---> Using cache
 ---> 594ba36e6461
Step 12 : ENTRYPOINT contained
 ---> Using cache
 ---> 3d6a4b48eca7
Successfully built 3d6a4b48eca7
docker run --rm -it \
	--net container:contained-dind \
	r.j3ss.co/contained -d
latest: Pulling from library/alpine
d0ca440e8637: Pull complete 
Digest: sha256:9dd95238d7f6ac0fabafd7b52e52d8a7c63a5e5b390d27e13cb5da8ddd2f0d98
Status: Downloaded newer image for alpine:latest
DEBU[0002] Server listening on 10000                    
```

**Additional information you deem important (e.g. issue happens only occasionally):**

I can look into it later, just don't really have time right now

**Comment by jfrazelle** [comment]
Also this makes no sense because how can it pull a latest image and yet use the cache....

**Comment by thaJeztah** [comment]
Could it be you had a "alpine:some-version" that matched `alpine:latest`? (Re: using cache)

**Comment by jfrazelle** [comment]
yeah maybe but this is what my current docker images output looks like :/
```
jessie at debian in ~
$ docker images
REPOSITORY                TAG                                     IMAGE ID
           CREATED             SIZE
r.j3ss.co/contained       latest
 3d6a4b48eca7        16 hours ago        21.35 MB
r.j3ss.co/contained       dev
d02db3bed646        16 hours ago        655.2 MB
r.j3ss.co/docker          userns
 6be3e8fa53a7        16 hours ago        82.77 MB
mesosphere/dcos-docker    latest
 93306121787f        19 hours ago        612.7 MB
mesosphere/dcos-docker    base
 2bd3f6ccf8fc        19 hours ago        577.7 MB
mesosphere/dcos-docker    centos
 2bd3f6ccf8fc        19 hours ago        577.7 MB
mesosphere/dcos-docker    centos-7
 2bd3f6ccf8fc        19 hours ago        577.7 MB
mesosphere/dcos-genconf   b2f9559b654bf5f2bf-fb268d10a77b1dde5c
5a7dd57df2a0        20 hours ago        721.2 MB
node                      latest
 a6b9ffdcf522        2 days ago          651.4 MB
docker                    1.11.1-dind
283d58943c98        2 weeks ago         80.39 MB
alpine                    latest
 13e1761bf172        3 weeks ago         4.793 MB
centos                    7
d0e7f81ca65c        11 weeks ago        196.6 MB
centos                    <none>
 d0e7f81ca65c        11 weeks ago        196.6 MB
```

On Fri, May 27, 2016 at 10:09 AM, Sebastiaan van Stijn <
notifications@github.com> wrote:

> Could it be you had a "alpine:some-version" that matched alpine:latest?
> (Re: using cache)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/docker/docker/issues/23064#issuecomment-222201270>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABYNbElW8BsBs6IT2mhj-t5ObvCrIby3ks5qFyVmgaJpZM4Ior3E>
> .
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by thaJeztah** [comment]
@tonistiigi could that (cache) be if all the layers were already present, from other images, but the actual "repo:tag" not?

**Comment by justincormack** [comment]
I have had 1.12 do something odd when if I pull or run say `ubuntu` it tries to pull every tag of that that exists. I can't replicate it with an empty image store, but its kind of annoying. It is fine if I just pull `:latest` explicitly.

**Comment by vdemeester** [comment]
@justincormack huh, there was a bug like that but it should have been fixed… there is even an integration test for it.

**Comment by justincormack** [comment]
@vdemeester when was it fixed? This was probably from a few days back but I can't quite remember which machine I saw it on to check. But if you know how to replicate it please check...

**Comment by vdemeester** [comment]
@jfrazelle I'm not sure how to reproduce though, on a clean docker daemon  :sweat:

**Comment by jfrazelle** [comment]
yeah i have been trying to, this might just be one of those weird things
that hppens once and then disappears, we could blame it on a ghost in the
machine

On Fri, May 27, 2016 at 11:44 AM, Vincent Demeester <
notifications@github.com> wrote:

> @jfrazelle <https://github.com/jfrazelle> I'm not sure how to reproduce
> though, on a clean docker daemon 😓
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/docker/docker/issues/23064#issuecomment-222223418>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABYNbCRZZ1AZnca6EdFgZx5aMBg4xAy7ks5qFzt7gaJpZM4Ior3E>
> .
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jfrazelle** [comment]
figured i would see if anyone else saw it first before ignoring entirely

On Fri, May 27, 2016 at 11:45 AM, Jessica Frazelle <me@jessfraz.com> wrote:

> yeah i have been trying to, this might just be one of those weird things
> that hppens once and then disappears, we could blame it on a ghost in the
> machine
>
> On Fri, May 27, 2016 at 11:44 AM, Vincent Demeester <
> notifications@github.com> wrote:
>
>> @jfrazelle <https://github.com/jfrazelle> I'm not sure how to reproduce
>> though, on a clean docker daemon 😓
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/docker/docker/issues/23064#issuecomment-222223418>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/ABYNbCRZZ1AZnca6EdFgZx5aMBg4xAy7ks5qFzt7gaJpZM4Ior3E>
>> .
>>
>
>
>
> --
>
>
> Jessie Frazelle
> 4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
> pgp.mit.edu
> <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>
