### ISSUE TITLE
fetching tags of php repository fails

### ISSUE THREAD

**Issue by jjohnstn** [docker/docker#23065]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Output of `docker version`:**
```
</html>bash $ docker version
Client:
 Version:      1.8.2-fc22
 API version:  1.20
 Package Version: docker-1.8.2-7.gitcb216be.fc22.x86_64
 Go version:   go1.5.1
 Git commit:   cb216be/1.8.2
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2-fc22
 API version:  1.20
 Package Version: 
 Go version:   go1.5.1
 Git commit:   cb216be/1.8.2
 Built:        
 OS/Arch:      linux/amd64

```
**Output of `docker info`:**

```
(bash $ docker info
Containers: 153
Images: 103
Storage Driver: devicemapper
 Pool Name: docker-253:0-657129-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 12.12 GB
 Data Space Total: 107.4 GB
 Data Space Available: 8.829 GB
 Metadata Space Used: 16 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.131 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93 (2015-01-30)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.3.4-200.fc22.x86_64
Operating System: Fedora 22 (Twenty Two)
CPUs: 8
Total Memory: 11.69 GiB
Name: dhcp-10-15-16-136.yyz.redhat.com
ID: OXN5:UJRS:VGO6:RZKW:V4ZU:JUCY:2UPF:LSXK:VAK4:FCDU:CDWQ:ZPEA

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. curl -v https://index.docker.io/v1/repositories/php/tags
2.
3.

**Describe the results you received:**

Request takes a long time and then issues "oops there was an error"

**Describe the results you expected:**

I expect to see the list of tags of the php repository.

**Additional information you deem important (e.g. issue happens only occasionally):**

This problem happens consistently but yesterday after a bunch of tries by multiple users, it finally started working.  It fails again today.

**Comment by thaJeztah** [comment]
Are you seeing this only when using curl, or does pulling PHP images from Docker Hub with Docker? Does `docker pull php` work?

Note that the registry V1 protocol was deprecated/removed in December 2015 (https://blog.replicated.com/2015/12/02/docker-hub-deprecates-registry-v1/, https://blog.docker.com/2015/10/docker-hub-deprecation-1-5/) so I'm actually surprised this would work.

If `docker pull php` doesn't work for you, could you try with the official docker builds? I see you're using a build of docker that's built by Red Hat, and contains a lot of modifications that can affect this behavior (https://github.com/projectatomic/docker/commit/cb216be)

**Comment by jjohnstn** [comment]
This occurs using curl or directly via a browser.  We are using this
logic as part of a search UI for Eclipse Docker Tooling.  The user searches for a term
and we show the resulting list of repositories.  The user then selects a repository and we
try to show tags so the user can pick a particular image to pull.  There is no API AFAIK to
get the tags for a repository from a registry so we get the tags using the JSON data returned
from the URL.

I noticed that when the php url was working yesterday, the output was fairly large.  The docker pull (which works) gets
13 images.  Fetching tags from other repositories works fine: e.g. php-zendserver, fedora.

-- Jeff J.

----- Original Message -----

**Comment by thaJeztah** [comment]
@jjohnstn perhaps I'm mistaken and this part of the V1 API is still active. In any case, it looks to be an issue with Docker Hub, so not something we can help with in this repository (Docker Hub is managed by a separate team). Can you report this issue through support@docker.com? That should get you in touch with the right people.

I'll close this issue here, because of the above, but feel free to comment after I closed
