### ISSUE TITLE
Docs incorrectly state seccomp facts for Ubuntu 14.04

### ISSUE THREAD

**Issue by envygeeks** [docker/docker#23083]
**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 18
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-22-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.784 GiB
Name: rey.envygeeks.io
ID: GO5K:XCSE:DB65:WJHH:WMM7:NV4R:7P4U:32DG:CV6Z:SKGN:42UQ:5DWM
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

* Physical Machine.

**Additional information you deem important (e.g. issue happens only occasionally):**

https://github.com/docker/docker/blob/master/docs/security/seccomp.md states that Seccomp 2.2.1 is required for seccomp on Ubuntu, and it's only available on 15.10+ but that's not true, via Backports one can get 2.2.3 https://launchpad.net/ubuntu/trusty/arm64/seccomp/2.2.3-2ubuntu1~ubuntu14.04.1.

I'm happy to send a pull request clarifying that if you wish.

**Comment by thaJeztah** [comment]
Unfortunately, we compile our static binaries for what's available by default (without back ports), so for Ubuntu 14.04, seccomp is disabled during compilation. So even if you install seccomp 2.2.1, you won't get seccomp filtering (only with the static binaries)

**Comment by thaJeztah** [comment]
also see https://github.com/docker/docker/issues/22870 for a related discussion, and background.

I'll close this issue, but thanks so much for paying attention, it's appreciated :+1:

**Comment by thaJeztah** [comment]
oh first comment -> static binaries should be "debs" / dynamic binaries - can't edit, coz I'm on my phone, sorry for that
