### ISSUE TITLE
Proposal/Improvement: docker daemon --allow-latest-images=false

### ISSUE THREAD

**Issue by samber** [docker/docker#23088]
In production environment, I think nobody should ever use images tagged with ```latest```.

Adding a new parameter to the docker daemon command allowing (or not) to use ```latest``` images would make a deployment workflow more reliable and safer.

WDYT about ```--allow-latest-images``` set to ```true``` by default ?

This could be implemented in Docker Swarm as well.

**Comment by thaJeztah** [comment]
Although I understand your though behind this (it's best to be explicit, use a specific version, and not `:latest`), I don't think we should implement this. introducing such flag would introduce the *impression* of protecting you against bad practice, but won't protect against many other things. Also consider that `:latest` is just a convention, but someone may use `:master` for the same purpose, which won't be caught by this flag.

Also think of other things that won't be covered by this, such as;

- untrusted images (`some-registry.com/shady-repository:1.0.0`)
- an untrusted image publisher deciding to replace image `repo:1.0` with a different image (note that image tags are mutable)

There's many more things to take into account, and policies for that may differ a lot between companies / use-cases.

Using [digests (immutable identifiers)](https://docs.docker.com/engine/reference/commandline/pull/#pull-an-image-by-digest-immutable-identifier) and [Docker Content Trust](https://docs.docker.com/engine/security/trust/content_trust/) is probably a better solution for this. If you want to enforce certain policies, then possibly you can implement an [authorization plugin](https://docs.docker.com/engine/extend/plugins_authorization/) for that.

I don't think this proposal will be flexible enough to cover all use cases, and just disabling `:latest` is only covering a really small portion of those.

**Comment by cpuguy83** [comment]
Yes, the correct place to implement something like this is in an authorization plugin.
