### ISSUE TITLE
[zsh completion] list all containers with `docker rm -f`

### ISSUE THREAD

**Issue by capkurmagati** [docker/docker#23097]
[zsh completion] list all containers with `docker rm -f`

I noticed that bash and fish have been fixed.
I have fixed it, so if this is wanted I can create a pull request.

`$docker ps -a`
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                         PORTS               NAMES
8233464b85e5        redis               "docker-entrypoint.sh"   About an hour ago   Exited (0) About an hour ago                       adoring_cray
36c828ec4809        redis               "docker-entrypoint.sh"   4 hours ago         Exited (0) 4 hours ago                             focused_golick
bc67c6bff99d        redis               "docker-entrypoint.sh"   5 days ago          Up 5 hours                     6379/tcp            re
```
---
before:
`docker rm -f`
```
adoring_cray    8233464b85e5  --   About an hour, redis
focused_golick  36c828ec4809  --         4 hours, redis
```
---
after:
```
bc67c6bff99d
re
--          5 days, redis
adoring_cray
focused_golick
8233464b85e5
36c828ec4809
--   About an hour, redis
--         4 hours, reds
```

Line breaks while outputting all containers' information.
To change this behavior requires to refactor `__docker_get_containers` function which is used by other functions (such as `docker inspect`), so I prefer not to change it in this issue.

**Comment by thaJeztah** [comment]
yes, `docker rm -f` should also complete running containers, so pull request is welcome :-)

**Comment by capkurmagati** [comment]
@thaJeztah 
Thanks for the quick rely.
PR is https://github.com/docker/docker/pull/23098.
Naive implementation, so please help me polish it. 🌊
