### ISSUE TITLE
OSX Docker Beta failed to get default registry endpoint.

### ISSUE THREAD

**Issue by jaredestroud** [docker/docker#23104]
Hello,
    Docker Beta on OSX El Captain cannot find default registry point. I've included additional information below.

### Error Message

Warning: failed to get default registry endpoint from daemon (Error response from daemon: Bad response from Docker engine). Using system default: https://index.docker.io/v1/

### Recreating Issue
```
$> docker search ubuntu
```

**Comment by thaJeztah** [comment]
Hi! Thanks for reporting; have you also reported this through https://forums.docker.com/c/docker-for-mac?

**Comment by jaredestroud** [comment]
I have not. Is this the preferred method?

**Comment by thaJeztah** [comment]
At this moment, I think that's still the preferred way. The Docker for Mac project is lead by a separate team, and by posting in that forum, other Beta users can also participate in the discussion

**Comment by jaredestroud** [comment]
Excellent, if anyone runs across this also looking for help I've provided a link below. It does appear however that this is a known issue.

https://forums.docker.com/t/connection-to-docker-beta-fails-with-time/8517/8

**Comment by thaJeztah** [comment]
Thanks @jaredestroud !
