### ISSUE TITLE
get.docker.com install issues with RHEL and CentOS

### ISSUE THREAD

**Issue by kencochrane** [docker/docker#23101]
Here is an email we received from _Tristan Chabredier_ about issues with RHEL and Centos installs using the [get.docker.com script](https://github.com/docker/docker/blob/master/hack/install.sh) along with some suggestions on a fix.

> I could experience few failures with the install script at
> https://get.docker.com/ when running on RHEL or CentOS.
> 
> First, on a CentOS6 or 7 system, both /etc/centos-release
> and /etc/redhat-release files are present, but the package
> redhat-release is NOT present, it's centos-release. Thus,
> the command:
> 
`># rpm -q --whatprovides redhat-release --queryformat "%{VERSION}\n" | sed 's/\/.*//' | sed 's/\..*//' | sed 's/Server*//`
> 
> will fail, generating an erroneous repo file in /etc/yum.repos.d/, then
> the installation cannot continue.
> 
> Also, on some RH6/7 where the base system is an upgrade from a previous
> version (say, a RHEL5 that has been upgraded to RHEL6 for instance),
> the following command will return several lines instead of the expected
> one:
> 
```
># rpm -q --whatprovides redhat-release --queryformat "%{VERSION}\n" | sed 's/\/.*//' | sed 's/\..*//' | sed 's/Server*//
> 5
> 6
```
> 
> because:
> 
```
># rpm -q --whatprovides redhat-release
> redhat-release-5Server-5.3.0.3.x86_64
> redhat-release-server-6Server-6.5.0.1.el6.x86_64
> 
```
> and the dist_version then the generated /etc/yum.repos.d/docker-main.repo
> will be wrong.
> 
> 
> Please find attached the suggested fixed version, that makes a
> distinction between redhat and centos systems and is enforced in
> detecting package version, and below, the diff between both versions:
> 
```
$ diff -burN get.docker.com-orig get.docker.com
   --- get.docker.com.sh-orig 2016-04-27 02:39:43.000000000 +0200
   +++ get.docker.com.sh      2016-05-30 10:40:51.000000000 +0200
   @@ -239,10 +239,11 @@
        if [ -z "$lsb_dist" ] && [ -r /etc/oracle-release ]; then
                lsb_dist='oracleserver'
        fi
   -       if [ -z "$lsb_dist" ]; then
   -               if [ -r /etc/centos-release ] || [ -r /etc/redhat-release ]; then
   +       if [ -z "$lsb_dist" ] && [ -r /etc/centos-release ]; then
                        lsb_dist='centos'
                fi
   +       if [ -z "$lsb_dist" ] && [ -r /etc/redhat-release ]; then
   +               lsb_dist='redhat'
        fi
        if [ -z "$lsb_dist" ] && [ -r /etc/os-release ]; then
                lsb_dist="$(. /etc/os-release && echo "$ID")"
   @@ -279,8 +280,8 @@
                        dist_version="$(rpm -q --whatprovides redhat-release --queryformat "%{VERSION}\n" | sed 's/\/.*//' | sed 's/\..*//' | sed 's/Server*//')"
                ;;
   -               fedora|centos)
   -                       dist_version="$(rpm -q --whatprovides redhat-release --queryformat "%{VERSION}\n" | sed 's/\/.*//' | sed 's/\..*//' | sed 's/Server*//')"
   +               fedora|centos|redhat)
   +                       dist_version="$(rpm -q --whatprovides ${lsb_dist}-release --queryformat "%{VERSION}\n" | sed 's/\/.*//' | sed 's/\..*//' | sed 's/Server*//' | sort | tail -1)"
                ;;
                *)
  @@ -435,7 +436,7 @@
                        exit 0
                        ;;
  -               fedora|centos|oraclelinux)
  +               fedora|centos|redhat|oraclelinux)
                        $sh_c "cat >/etc/yum.repos.d/docker-${repo}.repo" <<-EOF
                        [docker-${repo}-repo]
                        name=Docker ${repo} Repository
```
> Please also notice that on RH-based distros (RHEL, centos, fedora) and
> every distro where yum is used, several $variables can be used in files
> used /etc/yum.repos.d/, like $releasever, $basearch, etc., which could
> be placed and then no need to compute magics to determine the dist
> version (5, 6, 7 -> use $releasever instead). Using $releasever in the
> install script would enforce it greatly with regards to both issues I'm
> reporting in this email, BTW.
> 
> 
> Regards,
> Tristan Chabredier

Attachments

[get.docker.com.sh.txt](https://github.com/docker/docker/files/289520/get.docker.com.sh.txt)
[get.docker.com.sh-orig.txt](https://github.com/docker/docker/files/289521/get.docker.com.sh-orig.txt)

**Comment by runcom** [comment]
Great, do you mind making a PR with that diff? We can work from there to replace the way we compute version with predefined variables provided by yum (and dnf in newer fedora). Otherwise I'll take care of this.

**Comment by runcom** [comment]
Ping @tianon also

**Comment by kencochrane** [comment]
I'm planning on making a PR, but won't be able to get to it until tonight or tomorrow, if someone else wants to do it before than, feel free.

**Comment by runcom** [comment]
I think there's no rush so feel free to do it whenever you want to.

**Comment by kencochrane** [comment]
@runcom PR added #23124
