### ISSUE TITLE
Accessing docker API behind a reverse proxy

### ISSUE THREAD

**Issue by BLaurent** [docker/docker#23123]
Hi 

I have a docker swarm cluster setup on some VMs.
I've put in place a HAProxy in front of my swarm master that forward all my requests to my swarm masters.
I can contact a swarm master using curl to list running container through haproxy.
But accessing docker daemon using curl is a bit difficult.
is there a way to setup the docker cli to use my ha proxy server to interact with the docker daemon?

Thanks in advance
Regards.
Ben

**Comment by justincormack** [comment]
You should be able to set `DOCKER_HOST=tcp:<address of proxy>` to do this.

**Comment by BLaurent** [comment]
I tried but I get read tcp xxxx->yyyy: read: connection reset by peer

**Comment by justincormack** [comment]
As this is not an issue with Docker I am going to close it, but feel free to continue the discussion. Docker just uses an http or https connection, on the specified IP address and port, so you shoyuld be able to get this working, but I can't easily debug it for you.
