### ISSUE TITLE
Consider modification of the default seccomp policy regarding sysctl

### ISSUE THREAD

**Issue by NathanMcCauley** [docker/docker#23147]
sysctl() may allow information leaks such as which distro the host is running. Consider modification of our default seccomp filter to disable sysctl() fully. CC: @endrazine

**Comment by justincormack** [comment]
The `_sysctl` syscall is disabled fully in the default profile.

**Comment by jfrazelle** [comment]
so close?

**Comment by thaJeztah** [comment]
@justincormack was still looking into this
