### ISSUE TITLE
Too much memory used by docker_proxy processes for port intervals

### ISSUE THREAD

**Issue by amunhoz** [docker/docker#23166]
**Output of `docker version`:**
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   8acee1b
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   8acee1b
 Built:
 OS/Arch:      linux/amd64

**Output of `docker info`:**
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 15
Server Version: 1.10.3
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.5.0-coreos-r1
Operating System: CoreOS 1010.5.0 (MoreOS)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.958 GiB
Name: VspAtacado
ID: PYFN:I7PR:ZOK4:3NBL:7GJG:7TG5:AQP6:5X2J:VYB5:ZU3V:C35T:VTVD

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Digital ocean coreos image

**Steps to reproduce the issue:**
1. Create a docker and map some big port interval like 12000:12100
2.
3.

**Describe the results you received:**
The difference in used memory was about 1gb with and without the port map.  
There was a bunch of docker_proxy processes using a good piece of the memory.

**Describe the results you expected:**
You could use only one process for port intervals or only one global process for all ports maped.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment]
Closing as this is a dup of #11185

Note you can set `--userland-proxy=false` on the daemon to disable the proxy, which enables hairpin nat... however there is a known kernel(?) bug with hairpin mode on the bridge interfaces that can cause problems (see "waiting for lo to become free" search term)
