### ISSUE TITLE
Enable seccomp for s390x and ppc

### ISSUE THREAD

**Issue by michael-holzheu** [docker/docker#23171]
As discussed with @justincormack in PR #23057:

For enabling seccomp on s390x and ppc have updates for the following repositories:

 - <a name="libseccomp-golang"></a> libseccomp-golang [1]: seccomp/libseccomp-golang@32f571b [merged]
 - runtime-spec [2]: opencontainers/runtime-spec#475 [merged]
 - runc [3]: opencontainers/runc#864 [merged]
 - engine-api [4]: docker/engine-api#248 [merged]
 - Docker [5]: (s390x part - 5 commits): PR #23172 [merged]

To do everything in the right order, we have to do the following steps:

1) Runc: https://github.com/opencontainers/runc

 - Bump versions in Godeps directory for:  (issue opencontainers/runc#866)
   * libseccomp-golang [1] [merged via opencontainers/runc#894]
   * runtime-spec [2] [merged]
 - Add runc patch
   * runc [3] [merged]

2) Containerd (not sure if needed): https://github.com/docker/containerd

 - Bump versions in vendor directory for:
   * libseccomp-golang [1]
   * runtime-spec [2]
   * runc [3]

3) Docker: https://github.com/docker/docker

 - Bump versions in vendor directory for:
  * runtime-spec [2]
  * libseccomp-golang [1] [merged with #23402]
  * runc [3] and update Dockerfiles RUNC_COMMIT
  * engine-api [4] [merged with #23208]
 - Add s390x part: PR  #23172 [merged]

**Comment by michael-holzheu** [comment]
This is related to PR #22922
ping @tophj-ibm, @estesp, @clnperez , @brahmaroutu

**Comment by tophj-ibm** [comment]
Looks like a plan, thanks for heading this @michael-holzheu! Me or @clnperez will take a look at the power part for the seccomp profile and see if we can get something working on our end. Let me know as well if you need help on anything.

**Comment by justincormack** [comment]
@michael-holzheu have you run the docker tests and a variety of workloads with the seccomp profile enabled? Not sure if s390x has any unusual architecture specific syscalls that need adding?

**Comment by michael-holzheu** [comment]
> @michael-holzheu have you run the docker tests and a variety of workloads with the seccomp profile enabled? 

I have successfully run the _complete_ integration testsuite, especially:

```
+ go test -check.f DockerSuite.TestRunSeccomp* -check.v -check.timeout=120m -test.timeout=360m github.com/docker/docker/integration-cli
INFO: Testing against a local daemon
PASS: docker_cli_run_unix_test.go:1014: TestRunSeccompAllowPrivCloneUserns.pN52_github_com_docker_docker_integration_cli.DockerSuite    2.914s
PASS: docker_cli_run_unix_test.go:1025: TestRunSeccompAllowSetrlimit.pN52_github_com_docker_docker_integration_cli.DockerSuite  3.125s
PASS: docker_cli_run_unix_test.go:1035: TestRunSeccompDefaultProfileAcct.pN52_github_com_docker_docker_integration_cli.DockerSuite      13.497s
PASS: docker_cli_run_unix_test.go:1089: TestRunSeccompDefaultProfileNS.pN52_github_com_docker_docker_integration_cli.DockerSuite        16.174s
PASS: docker_cli_run_unix_test.go:926: TestRunSeccompProfileDenyChmod.pN52_github_com_docker_docker_integration_cli.DockerSuite 1.388s
PASS: docker_cli_run_unix_test.go:990: TestRunSeccompProfileDenyCloneUserns.pN52_github_com_docker_docker_integration_cli.DockerSuite   2.997s
SKIP: docker_cli_run_unix_test.go:898: TestRunSeccompProfileDenyUnshare.pN52_github_com_docker_docker_integration_cli.DockerSuite (Test requires apparmor is enabled.)
SKIP: docker_cli_run_unix_test.go:953: TestRunSeccompProfileDenyUnshareUserns.pN52_github_com_docker_docker_integration_cli.DockerSuite (Test requires apparmor is enabled.)
PASS: docker_cli_run_unix_test.go:1002: TestRunSeccompUnconfinedCloneUserns.pN52_github_com_docker_docker_integration_cli.DockerSuite   3.053s
PASS: docker_cli_run_unix_test.go:1181: TestRunSeccompWithDefaultProfile.pN52_github_com_docker_docker_integration_cli.DockerSuite      3.009s
OK: 8 passed, 2 skipped
PASS
```

In addition to that I ran the following two tests:

```
# cat chmod.json
{
        "defaultAction": "SCMP_ACT_ALLOW",
        "syscalls": [
        {
                "name": "chmod",
                "action": "SCMP_ACT_ERRNO"
        }
        ]
}
# docker run --rm --security-opt seccomp=chmod.json busybox chmod 400 /etc/hostname
chmod: /etc/hostname: Operation not permitted
```

```
# cat socket.json 
{
        "defaultAction": "SCMP_ACT_ALLOW",
        "syscalls": [
        {
                "name": "socket",
                "action": "SCMP_ACT_ERRNO"
        }
        ]
}

# docker run --rm --security-opt seccomp=socket.json busybox ping -c1 127.0.0.1
PING 127.0.0.1 (127.0.0.1): 56 data bytes
ping: permission denied (are you root?)
```

**Comment by michael-holzheu** [comment]
> Not sure if s390x has any unusual architecture specific syscalls that need adding?

This is a very good point:

```
# cd linux/arch/s390
# arch/s390> git grep SYSCALL_DEF | grep -v compat

kernel/runtime_instr.c:SYSCALL_DEFINE1(s390_runtime_instr, int, command)
kernel/signal.c:SYSCALL_DEFINE0(sigreturn)
kernel/signal.c:SYSCALL_DEFINE0(rt_sigreturn)
kernel/sys_s390.c:SYSCALL_DEFINE1(mmap2, struct s390_mmap_arg_struct __user *, arg)
kernel/sys_s390.c:SYSCALL_DEFINE5(s390_ipc, uint, call, int, first, unsigned long, second,
kernel/sys_s390.c:SYSCALL_DEFINE1(s390_personality, unsigned int, personality)
pci/pci_mmio.c:SYSCALL_DEFINE3(s390_pci_mmio_write, unsigned long, mmio_addr,
pci/pci_mmio.c:SYSCALL_DEFINE3(s390_pci_mmio_read, unsigned long, mmio_addr,
```

We checked that list and found three system calls that should probably included in the white lis<-t:

- Other architectures can read/write unprivileged from/to PCI MMIO memory. On s390 we need syste<-m calls for that. In order to have the same behavior than x86, we probably should put the foll<-owing two syscalls to the whitelist:

 * s390_pci_mmio_write (see man s390_pci_mmio_write)
 * s390_pci_mmio_read (see man s390_pci_mmio_read)

- Runtime instrumentation (IMHO used by java on s390):

 * s390_runtime_instr

So I will add a patch that adds the three syscalls to the default profile?

**Comment by justincormack** [comment]
I would guess that the pci ones should be gated by `CAP_SYS_RAWIO`, as normally access to `/proc/bus/pci` is, which I would guess would be the equivalent? Maybe check the source and see? The man page oddly does not mention what permissions are needed. `s390_runtime_instr` looks fine for general use.

**Comment by justincormack** [comment]
Are `s390_personality` and `s390_ipc` actually named differently? They may be needed.

Looking at it, I may need to fix the general `personality` on non x86 though, as I think the flag values are architecture specific.

**Comment by justincormack** [comment]
Ah ok `personality` in general looks ok, although could disable `LINUX32` eg on `ppc64le` but I don't think it is vital, will take a look.

**Comment by justincormack** [comment]
ok the `s390_personality` and `s390_ipc` dont seem to be really different, but maybe you could double check if  `personality` has any different arguments from other architectures?

**Comment by justincormack** [comment]
Hmm, reading the code `s390_pci_mmio_write` does not appear to have any security requirements at all, so any user can write to pci memory? That seems kind of insecure? On other architectures it would be stopped by device permissions or `CAP_SYS_RAWIO`. Maybe you could ping the kernel people maybe I missed something. I would still gate it by `CAP_SYS_ADMIN` for docker I think...

**Comment by justincormack** [comment]
Engine API bump is #23208

**Comment by justincormack** [comment]
Can you just post the output of `strace ls` for reference just to see if anything stands out?

**Comment by michael-holzheu** [comment]
> Can you just post the output of strace ls

[strace.ls.debian-jessie.4.5.0-1-s390x.txt](https://github.com/docker/docker/files/297390/strace.ls.debian-jessie.4.5.0-1-s390x.txt)

**Comment by justincormack** [comment]
Ok nothing unexpected there, thanks.

**Comment by michael-holzheu** [comment]
>Hmm, reading the code s390_pci_mmio_write does not appear to have any security requirements at all, so any user can write to pci memory?

Any user that could create the mapping before. IMHO the creation of the mapping has to be secured.

> On other architectures it would be stopped by device permissions or CAP_SYS_RAWIO. 

Here the complete answer of our PCI expert:

"The system calls are needed because we cannot access MMIO space directly in user space, special instructions are needed and they are also privileged. So the system calls can be regarded as a replacement for the normal load/store instructions that can be used to access MMIO space on other architectures, and therefore any CAP_SYS check would be wrong. The system calls can only be used on successfully mapped MMIO ranges, so the access rights should be checked when creating the mapping."

**Comment by justincormack** [comment]
Ah ok that makes sense then, thanks for checking.

**Comment by michael-holzheu** [comment]
> ok the s390_personality and s390_ipc dont seem to be really different, 

Yes, both system calls have the same numbers (unitstd.h) as on other architectures and also the external name is the same (e.g. "personality" instead of "s390_personality").

> but maybe you could double check if personality has any different arguments from other architectures?

We don't have different arguments for personality(). For ipc() we have only five parameters (instead of six), but since Docker seccomp does not check parameters this should be no problem.

So IMHO the conclusion regarding s390 specific syscalls is that we should add:

 -  s390_pci_mmio_write
 -  s390_pci_mmio_read
 -  s390_runtime_instr

**Comment by justincormack** [comment]
Sounds good.

**Comment by michael-holzheu** [comment]
The next step would be to bump libseccomp-golang [1] in runc: opencontainers/runc#866

Unfortunately I don't know how the vendor update process with "godep" in runc is working. Therefore I did not create a PR up to now. @justincormack please advise :-)

**Comment by michael-holzheu** [comment]
One more question: IIUC the default seccomp profile disables the "ptrace" system call (if not called with --privileged). Therefore debugging tools like strace and gdb will not work. This might confuse / angry some people.

**Comment by justincormack** [comment]
@michael-holzheu yes, for security reasons. From 1.12 onwards you will be able to enable it easily with `docker run --cap-add CAP_PTRACE ...` which will allow it in the seccomp rules. You can use `ptrace` to bypass seccomp filtering by changing the syscall after the check using `ptrace` so it has to be disabled by default really.

**Comment by michael-holzheu** [comment]
> You can use ptrace to bypass seccomp filtering by changing the syscall after the check using ptrace so it has to be disabled by default really.

This is really interesting. So all software that uses seccomp has to disable ptrace, otherwise the rules could be circumvented. I have not thought about that...

**Comment by justincormack** [comment]
@michael-holzheu see https://www.kernel.org/doc/Documentation/prctl/seccomp_filter.txt under `SECCOMP_RET_TRACE`

**Comment by michael-holzheu** [comment]
With opencontainers/runc#894 now runc is up-to-date. We could now bump the runc version.

**Comment by justincormack** [comment]
Ok this will definitely happen before 1.12, probably a few times, will check.

**Comment by justincormack** [comment]
@crosbymichael are you planning to bump runc soon?

**Comment by michael-holzheu** [comment]
> @crosbymichael are you planning to bump runc soon?

FYI: Because we now enabled "seccomp" in DOCKER_BUILDTAGS for Dockefile.s390x and still use RUNC_COMMIT without the seccomp patches we currently get "oci runtime error: unrecognized architecture" for images built with Dockerfile.s390x.

**Comment by crosbymichael** [comment]
Its not ready to be bumped yet, there are still some PRs we need to wait on.  In the future we should wait on the dependencies before merging the calling code.

**Comment by michael-holzheu** [comment]
> In the future we should wait on the dependencies before merging the calling code.

@crosbymichael: I am sorry about that. The original plan was to respect the dependencies (see inital comment "To do everything in the right order, we have to do the following steps:" ...).

**Comment by crosbymichael** [comment]
@michael-holzheu no problem at all.  Was just a mistake, i'm trying to get these last few PRs merged before I do the bump.  Should not take too much longer

**Comment by justincormack** [comment]
Sorry was my fault I didn't think it would fail if we merged early. We need
to fix the CI for Z....

**Comment by crosbymichael** [comment]
We should just remove the build tag for now?  that will fix the ci right?

**Comment by michael-holzheu** [comment]
> We should just remove the build tag for now? that will fix the ci right?

Yes, we could just remove "seccomp" in DOCKER_BUILDTAGS for Dockefile.s390x again :)

**Comment by crosbymichael** [comment]
@michael-holzheu lets do that for now and i'll add that tag back when I bump the runc version

**Comment by michael-holzheu** [comment]
> @michael-holzheu lets do that for now and i'll add that tag back when I bump the runc version

Ok. I created PR #23439

**Comment by justincormack** [comment]
ok so the runc changes were merged in https://github.com/docker/docker/pull/23603 but without the seccomp fix, created a PR https://github.com/docker/docker/pull/23641

cc @crosbymichael @michael-holzheu

**Comment by michael-holzheu** [comment]
Regarding s390x seccomp now everything looks good to me.
Many thanks @justincormack and others for all your help!
