### ISSUE TITLE
add storage limit to overlayfs?

### ISSUE THREAD

**Issue by saiwl** [docker/docker#23187]
I want to add storage limit to overlayfs. Here's my plan:
1. Use lvm to create a storage-limited directory(just create a device&mount directory).
2. Use this directory as the upper layer.

Apparently this needs to do some changes to the code. I wonder whether this plan is feasible or not.This is not a proposal, just for individual use.
Any advice? Thank you!

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by HackToday** [comment]
do you mean feature like this ?

https://github.com/docker/docker/commit/401c8d17674379d9b727d25df2d560a2dfe07f27

**Comment by saiwl** [comment]
@HackToday  yes,  but for overlayfs

**Comment by cpuguy83** [comment]
I don't think this would be possible unless overlay had such a feature built in (which it doesn't afaik).

**Comment by AkihiroSuda** [comment]
I think we can close this
https://github.com/docker/docker/pull/24771

**Comment by Levovar** [comment]
Please re-open this.
If you carefully read the thread you linked, you will see that the feature was only partially implemented.
Yes, it is possible to add quotas on a per-container basis through the docker run and docker create APIs.
However, it is currently not possible to set default quotas for all containers brought up on a cluster; aka. with a docker daemon level configuration data.

**Use-case**: As a Kubernetes/whatever cluster administrator I would like to 1: use overlayfs2 as my docker storage driver 2: would like to limit the maximum disk each container can use in my cluster
If we can already limit this on a per-container basis, it sounds easy enough to automatically add a pre-configured (dockerd level) limit to all docker run / create operations. I guess :)

**Comment by cpuguy83** [comment]
@Levovar it is possible, but probably not released in Docker until 17.07.

**Comment by Levovar** [comment]
that is fine, still I think this would be a very useful feature to have, so we could at least leave this issue open -for administration purposes- until the feature is realized

**Comment by cpuguy83** [comment]
The feature is already merged, we do not need to keep an issue open around it.
