### ISSUE TITLE
APT repository contains bad 'component' in Release file(s)

### ISSUE THREAD

**Issue by akshaymoghe** [docker/docker#23180]
In the apt repository hosted at apt.dockerproject.org , the `Release` file for component `main` contains this:

```
Architectures: amd64 i386
Codename: ubuntu-precise
Components: testing
Date: Wed, 01 Jun 2016 22:19:01 UTC
Label: Docker APT Repository
Origin: Docker
Suite: ubuntu-precise
...
```

(file is at: https://apt.dockerproject.org/repo/dists/ubuntu-precise/main/binary-amd64/Release)

Notice that the components section only contains `testing`. However this is the `Releases` file for component `main`.

The same problem exists for `experimental` as well. 

Some tools seem to trip on this (notably: aptly - which is a handly tool to painlessly mirror repositories). Without this, I cannot mirror the `main` component of the repository. :(

**Comment by akshaymoghe** [comment]
This seems to be true of *all* `Releases` files found for `ubuntu-precise`. For example, even the one at https://apt.dockerproject.org/repo/dists/ubuntu-precise/Release contains:

```
Architectures: amd64 i386
Codename: ubuntu-precise
Components: testing
Date: Wed, 01 Jun 2016 22:19:01 UTC
Label: Docker APT Repository
Origin: Docker
Suite: ubuntu-precise
```

**Comment by akshaymoghe** [comment]
The same is also true for `Distribution: ubuntu-trusty` .

**Comment by thaJeztah** [comment]
ping @mlaventure @tiborvass @kencochrane PTAL!
