### ISSUE TITLE
Docker restart get stuck

### ISSUE THREAD

**Issue by liucw2012** [docker/docker#23189]
**Output of `docker version`:**

```
Docker version 1.12.0-dev, build 4a7715c-unsupported
```

**Output of `docker info`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.4
 Git commit:   4a7715c-unsupported
 Built:        Thu Jun  2 11:17:17 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.4
 Git commit:   4a7715c-unsupported
 Built:        Wed Jun  1 17:17:04 2016
 OS/Arch:      linux/amd64
Containers: 29
 Running: 1
 Paused: 0
 Stopped: 28
Images: 58
Server Version: 1.12.0-dev
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.797 GiB
Name: docker-latest
ID: R4HL:FKZV:YWHU:ENT7:WV7B:AK2Y:TMDE:BASL:GHGI:VBNR:B3G5:QG3D
Docker Root Dir: /mnt/docker-graph
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 15
 Goroutines: 31
 System Time: 2016-06-02T11:20:24.198316039+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. use docker run create a container 
2. docker restart containerid & ,do this for several times.
3. one docker restart process got stuck there.can't exit.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
one restart command go killProcessDirectly ,when it returned,it goes to container.WaitStop(-1\* time.Second) to wait on  s.waitChan. but when other restart command have already start this container at this time,s.waitChan was closed and remake. this'll lead to  container.WaitStop(-1 *time.Second) waiting on a new channel  and nerver return.i fixed this bug as follows:

```
diff --git a/daemon/kill.go b/daemon/kill.go
index 15a22a7..82aa7ae 100644
--- a/daemon/kill.go
+++ b/daemon/kill.go
@@ -130,14 +130,13 @@ func (daemon *Daemon) Kill(container *container.Container) error {
        }

        // 2. Wait for the process to die, in last resort, try to kill the process directly
+       wc := container.GetWaitChan()
        if err := killProcessDirectly(container); err != nil {
                if isErrNoSuchProcess(err) {
                        return nil
                }
-               return err
        }
-
-       container.WaitStop(-1 * time.Second)
+       container.WaitOnChan(wc, -1*time.Second)
        return nil
 }
```

container.GetWaitChan() will get the old channel before container.WaitStop(-1 \* time.Second),
container.WaitOnChan is new, it wait on the channel passed to it.

**Comment by krasi-georgiev** [comment]
@liucw2012 , @thaJeztah  - just tried latest master and seems ok

**Comment by thaJeztah** [comment]
Thanks @krasi-georgiev 

@liucw2012 let me go ahead and close this issue, but please let us know if you're still seeing this on the current release
