### ISSUE TITLE
Cannot RUN sh while building on Windows

### ISSUE THREAD

**Issue by xmalion** [docker/docker#23204]
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 11
 Running: 0
 Paused: 0
 Stopped: 11
Images: 11
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 50
 Dirperm1 Supported: true
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.8-boot2docker
Operating System: Boot2Docker 1.11.1 (TCL 7.0); HEAD : 7954f54 - Wed Apr 27 16:36:45 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: default
ID: QEE4:4XNY:XS2Z:CJWL:64N4:JYQ4:FP6J:CKVR:OLCW:KWVZ:65AL:WCP3
Debug mode (server): true
 File Descriptors: 13
 Goroutines: 30
 System Time: 2016-06-02T13:38:46.337243052Z
 EventsListeners: 0
 Init SHA1:
 Init Path:
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Windows 7 64-bit

**Steps to reproduce the issue:**
1. Dockerfile:
```
FROM mariadb:10.0

COPY mariadb.cnf /etc/mysql/conf.d

# Add script to create default users / vhosts
ADD init.sh /init.sh
ADD run.sh /run.sh

RUN chmod +x /init.sh /run.sh \
 && /init.sh

ENTRYPOINT "/run.sh"
```
2. Then run:
```
docker-compose build db
```
3. And on step running `init.sh`:
![123](http://dl1.joxi.net/drive/2016/06/02/0008/3571/581107/07/e8e288c7cb.png)

If I don't chmod on files, then file exists and Access denied error happened, but when +x, then "not found".

The same config is perfectly work on OSX, but fail on Windows. What a problem?

**Comment by justincormack** [comment]
What is in `init.sh`? That error an mean the `#!` file is not found.

**Comment by thaJeztah** [comment]
or the init.sh is using Windows line ending; make sure it uses UNIX line endings (the error you see is generated by Linux, not docker - and yes, it's really confusing)

**Comment by xmalion** [comment]
> or the init.sh is using Windows line ending; make sure it uses UNIX line endings (the error you see is generated by Linux, not docker - and yes, it's really confusing)

File was developed on OSX, then pushed into Git repo here, on GitHub, and then cloned on Windows machine. File was not changed and in state from repository.

`init.sh` file contains this script:

```
#!/bin/bash

set -e
set -x

mysql_install_db

# Start the MySQL daemon in the background.
/usr/sbin/mysqld &
mysql_pid=$!

until mysqladmin ping &>/dev/null; do
  echo -n "."; sleep 0.2
done


# Set no-password access to root user
mysql -e "GRANT ALL ON *.* TO root@'%' IDENTIFIED BY '' WITH GRANT OPTION"

# Create db for app and tests
mysql -e "CREATE DATABASE IF NOT EXISTS vibrobox CHARACTER SET utf8 COLLATE utf8_general_ci"
mysql -e "CREATE DATABASE IF NOT EXISTS vibrobox_test CHARACTER SET utf8 COLLATE utf8_general_ci"

# Tell the MySQL daemon to shutdown.
mysqladmin shutdown

# Wait for the MySQL daemon to exit.
wait $mysql_pid

# Store db state
tar czvf default_mysql.tar.gz /var/lib/mysql

```

**Comment by thaJeztah** [comment]
> File was not changed and in state from repository.

Correct, but it may have been automatically converted to Windows line-endings by Git; see https://github.com/docker/docker/pull/22395 and https://help.github.com/articles/dealing-with-line-endings/#platform-windows

**Comment by Iristyle** [comment]
While line endings are indeed important (and can easily be addressed with `.gitattributes`), the execute bit is also critical. Since Windows has no way of representing the execute bit on disk, even if it's set in the Git metadata, this ends up being a problem. Of course, you can modify the `Dockerfile` to inject a `chmod`, but this seems like something that should be handled automatically?

We're doing https://github.com/puppetlabs/puppetserver/pull/1796/commits/035b51d1f9a90dd0b08c30f0943d73eb4d431c8f for now, but it would be nice to be able to remove the `chmod` call. It's possible to not have +x set on systems other than Windows and it seems pretty evident if you're using `ENTRYPOINT` that the script should be marked executable, no?
