### ISSUE TITLE
Docker Cloud FAQ mentions Docker Engine 1.7.0 as "yet-to-be-released"

### ISSUE THREAD

**Issue by motin** [docker/docker#23209]
This FAQ entry should be removed or updated to reflect the current stable version of Docker Engine used in Docker Cloud: https://docs.docker.com/docker-cloud/docker-errors-faq/

> Error message: 500 Server Error: Cannot start
> 500 Server Error: Internal Server Error (“Cannot start container : fork/exec /var/lib/docker/init/dockerinit-1.5.0: cannot allocate memory”)
> 
> 500 Server Error: Internal Server Error (“Cannot start container : iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport <port> ! -i docker0 -j DNAT --to-destination <ip>:<port>: (fork/exec /sbin/iptables: cannot allocate memory)“)
> 
> Error pulling image (<tag>) from <image>, Untar fork/exec /usr/lib/dockercloud/docker: cannot allocate memory
> 
> Description
> Your host does not have enough free memory for Docker Engine to perform the operation. If your containers are not responsible for the lack of free memory, it might be a known memory leak on the Docker daemon < 1.7.0, which will be fixed in the yet-to-be-released Docker Engine 1.7.0.
> 
> GitHub link
> docker/docker#12848
> 
> Workaround
> Restart the dockercloud-agent service (sudo service dockercloud-agent restart) on the node, or restart the node. Upgrading to Docker Engine 1.7.1+ solves the issue.
>

**Comment by thaJeztah** [comment]
Thanks! Yes, this should be updated ping @sanscontext can you have a look at this one?

**Comment by sanscontext** [comment]
I'm on it - culling the closed GH issues from the Known Issues file. :)

**Comment by sanscontext** [comment]
Hey @motin, this is removed (and some other cruft as well) and will be live in the next docs push. Thanks for reporting!

**Comment by motin** [comment]
Great, thanks! And I see it is already pushed live. :)
