### ISSUE TITLE
how to clear pull data after pull fail

### ISSUE THREAD

**Issue by lenxeon** [docker/docker#23201]
Mac@MacdeMacBook-Pro  /Volumes/data/workspace/es-demo-cluster   master  docker pull mcascallares/kibana-on-steroids:latest
latest: Pulling from mcascallares/kibana-on-steroids
8b87079b7a06: Already exists
a3ed95caeb02: Already exists
40e41135f2e1: Already exists
0dcedd2327f2: Already exists
652ff20764e4: Already exists
7a4d6ce10890: Already exists
24cf675e5feb: Already exists
1ac116346e28: Already exists
b2a68052ef6b: Already exists
b40842db255a: Already exists
41d5637dd8e9: Already exists
9ce22c9fde8f: Already exists
51e74737f1f1: Already exists
cfcd8955f351: Already exists
63d695cb0cbd: Downloading [====================================>              ] 4.651 MB/6.459 MB
7144e9bfa02e: Download complete

**Comment by HackToday** [comment]
seems a question, not an issue. Could you specify what error do you hit ?

**Comment by thaJeztah** [comment]
Looks like you commented on https://github.com/docker/docker/issues/23115 as well; can you describe the exact issue on that issue? Is the "Download" hanging (i.e., it never finishes?)

I'll close this issue, to keep the discussion in a single place, please continue on https://github.com/docker/docker/issues/23115

**Comment by lenxeon** [comment]
@HackToday @thaJeztah   pull progress stop at  4.651 MB/6.459 MB

**Comment by thaJeztah** [comment]
Is this from Docker Hub, or a private registry?

**Comment by lenxeon** [comment]
@thaJeztah from Docker Hub
