### ISSUE TITLE
Volume ls filter not working for 'name' and 'driver'

### ISSUE THREAD

**Issue by LukasBacigal** [docker/docker#23205]
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 16
 Running: 13
 Paused: 0
 Stopped: 3
Images: 270
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-22-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.54 GiB
Name: bacigalubupc
ID: 4SXZ:24LJ:CLDS:NRQJ:BLRE:WMA3:BVVO:MOGC:DXNW:7COX:L5DX:F4Y6
Docker Root Dir: /home/UX/lbacigalux/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 87
 Goroutines: 145
 System Time: 2016-06-02T16:25:00.463460097+02:00
 EventsListeners: 0
Username: lbacigal
Registry: https://index.docker.io/v1/

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. `docker volume ls -f name=rose` or `docker volume ls -f driver=local`

**Describe the results you received:**
Error response from daemon: Invalid filter 'name'

**Describe the results you expected:**
Based on this https://docs.docker.com/engine/reference/commandline/volume_ls/

DRIVER | VOLUME NAME
--- | ---
local | rosemary

**Additional information you deem important (e.g. issue happens only occasionally):**
filter dangling is working

**Comment by thaJeztah** [comment]
Looks like we published some documentation for the 1.12 release as it's not yet available for docker 1.11. Let me create a pull request to fix that (https://github.com/docker/docker/pull/21361)

**Comment by HackToday** [comment]
It is interesting such issue, @thaJeztah  do you know why #21361 planned in 1.12 while doc still available in 1.11

How do we usually manage such features in master branch? do we have smart ways to do that ? I'd like to learn what we did to achieve that 😸

**Comment by thaJeztah** [comment]
@HackToday I think it's been a mistake on my side; we cherry-pick documentation updates in the "docs" branch (in between releases)

**Comment by thaJeztah** [comment]
Actually, I was looking at the wrong branch, and the online docs are correct. Docker 1.11 only supports `--filter dangling=(true|false)`

```
docker volume ls
DRIVER              VOLUME NAME
local               035696f7e7ecdf277c018f662b98b73a2ace4916a165d415ccabaf3023def502
local               81da16e2d4d27c3bbed3cd82f4c70f7d758d6970995bb76b4b9373a960fc0802
local               data-volume1

docker volume ls --filter dangling=true
DRIVER              VOLUME NAME
local               data-volume1

docker volume ls --filter dangling=false
DRIVER              VOLUME NAME
local               035696f7e7ecdf277c018f662b98b73a2ace4916a165d415ccabaf3023def502
local               81da16e2d4d27c3bbed3cd82f4c70f7d758d6970995bb76b4b9373a960fc0802
```

As far as I can see, that's working correct; only the volume `data-volume1` is currently used by a container, and the others are not


The `--filter name=xyz` and `--filter driver=foo` are coming in docker 1.12, so are not available yet in the current release.

I'm closing this issue, because I don't think there's anything wrong here

FWIW; the documentation is generated from the "docs" branch, and this is what's currently in there:
https://github.com/docker/docker/blob/docs/docs/reference/commandline/volume_ls.md

**Comment by thaJeztah** [comment]
@joshua-barnett did you try it? 

This ticket was closed 5 years ago, as these were implemented; see my last comment

Filtering on name, driver, as well as on labels works (documentation: https://docs.docker.com/engine/reference/commandline/volume_ls/#filtering):


```bash
$ docker volume ls --filter name=hello
DRIVER    VOLUME NAME
local     hello

$ docker volume ls --filter name=myvolume
DRIVER    VOLUME NAME
local     myvolume


$ docker volume ls --filter driver=local --filter name=hello
DRIVER    VOLUME NAME
local     hello

$ docker volume ls --filter driver=foobar --filter name=hello
DRIVER    VOLUME NAME
```

**Comment by joshua-barnett** [comment]
@thaJeztah it is fixed now, you have to use the following syntax to filter by arbitrary labels.

```shell
docker volume ls --filter label=key=value
```
