### ISSUE TITLE
So is tini still needed?

### ISSUE THREAD

**Issue by clavecoder** [docker/docker#23214]
[https://github.com/docker-library/official-images#init](https://github.com/docker-library/official-images#init) says that `TINI` is not needed if #11529 is implemented. That starts a chain of referenced issues:

#20361
PR #20662

Does that mean we don't need TINI any more and the documentation should be updated or should we be waiting for something else?

**Comment by cpuguy83** [comment]
As far as zombies are concerned, Docker still can't clean these up itself.

As far as producing zombies, if you simply call `wait` after you fire off a sub-process you won't get zombies.

**Comment by clavecoder** [comment]
Wow, what a lame response. Your own best practices page for official images recommends it, and I get this lame response. What's your best practice. Jenkins and the image I'm contemplating will create extension processes that they cannot control. That's why your own documentation recommends it. Please provide a reasoned response to my question.

If you are unaware of the context of the question the following article will explain it fully:

https://github.com/krallin/tini/issues/8

**Comment by cpuguy83** [comment]
@clavecoder I'm not sure why you took offense to my response... but Docker still can't clean up zombies, as I stated... and probably won't ever be able to unless there are some changes to the kernel (or some new flag enabling a built-in pid1 reaper).

**Comment by justincormack** [comment]
@clavecoder that benefit of #11529 turned out not to be true, the comments there are still correct.

**Comment by clavecoder** [comment]
Thanks! Very helpful. You may want to remove the caveat in the instructions to https://github.com/docker-library/official-images#init.
