### ISSUE TITLE
'Unknown instruction: FROM' when docker build

### ISSUE THREAD

**Issue by allencloud** [docker/docker#23221]
**Output of `docker version`:**

```
root@ubuntu:~/dockerfiles# docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
root@ubuntu:~/dockerfiles# docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 38
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 376
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: ubuntu
ID: HRBI:EV6M:3NAC:CXZ3:BDS7:UOKL:PD6Y:ZCK4:V3PF:V7MR:CU2Y:3LGG
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 29
 System Time: 2016-06-03T10:57:29.679646373+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
root@ubuntu:~/dockerfiles# uname -a
Linux ubuntu 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Steps to reproduce the issue:**
1.
```
root@ubuntu:~/dockerfiles# docker build -t="test" .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM
Unknown instruction: FROM
```

**Additional information you deem important (e.g. issue happens only occasionally):**
Dockerfile Details
```
root@ubuntu:~/dockerfiles# cat Dockerfile
FROM daocloud.io/ubuntu:trusty
```
This happens on docker 1.8.3 and docker 1.9.1.

And if I copy the content to another Dockerfile, it works fine. So I wonder if this Dockerfile's file format and attributes stop the build procedure.

Unfortunately, Github does not support attachment of Dockerfile.

**Comment by mountkin** [comment]
Perhaps there are some invisible characters (such as BOM) at the beginning of the file? 
Just guessing :innocent:

**Comment by allencloud** [comment]
Thanks. @mountkin 
There is indeed additional content than I think.

I use **HEX** to detect the file, and found that:
```
...FROM daocloud.io/ubuntu:trusty
EFBBBF46 524F4D20 64616F63 6C6F7564 2E696F2F 7562756E 74753A74 72757374 790D0A
```

While the correct one is that:
```
FROM daocloud.io/ubuntu:trusty
46524F4D 2064616F 636C6F75 642E696F 2F756275 6E74753A 74727573 74790A
```

Although something is invisible, we should take care of this as well.

Close it.

**Comment by allencloud** [comment]
I think docker can do some work to avoid this. We can fix this, so reopen it.

**Comment by justincormack** [comment]
That is the UTF8 BOM. Some Windows editors add it, even though it is a pointless thing as UTF8 does not have a choice of byte ordering. I guess we could ignore it - any opinions @jhowardmsft ?

**Comment by yongtang** [comment]
The parsing of the Dockerfile happens in:
https://github.com/docker/docker/blob/v1.11.1/builder/dockerfile/parser/parser.go#L112-L115

So I think it should be relatively easy to skip the UTF-8 BOM.

**Comment by yongtang** [comment]
@allencloud I created a pull request #23234 to skip the UTF-8 BOM bytes. Please take a look and let me know if it solves the issue.

**Comment by jhowardmsft** [comment]
Both notepad.exe and PowerShell add it - the latter being the most 'annoying' one. I'll all for having Docker work around this :+1: 

@swernli FYI

**Comment by spottedmahn** [comment]
I used [`echo $null >> DockerFile`](https://superuser.com/a/502378/40715) to create my DockerFile and I too had this problem.

I used NotePad++ to change the encoding and I was gtg:

![image](https://user-images.githubusercontent.com/14079228/65633499-406f9680-dfaa-11e9-92d5-bcadb94c501d.png)
