### ISSUE TITLE
Is that necessary to Shutdown all contianers when daemon is killed?

### ISSUE THREAD

**Issue by liucw2012** [docker/docker#23223]
**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
As We have already restore a running container after restart docker daemon, is that necessary to Shutdown all contianers when daemon is killed?  i delete the code of Shutdown and find it run well 
after restart  daemon. correct me if i'm wrong.

**Comment by justincormack** [comment]
Hi, we are working on supporting this for the next release, and the changes have been in for a while, the final options to enable it are being added and this should be supported in 1.12.

**Comment by thaJeztah** [comment]
Correct, this is being worked on for the next release. I'll close this issue, because this is being tracked by https://github.com/docker/docker/issues/2658
