### ISSUE TITLE
Ubuntu 16.04: Fail push to private insecure registry  (tls: oversized record...)

### ISSUE THREAD

**Issue by terracott** [docker/docker#23228]
Hello! I have a problem.

**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 19
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 41
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-22-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.705 GiB
Name: home
ID: L22K:ZRW2:L2UT:Q3OA:Z3PW:ULZD:IOFG:36FZ:MQQT:EVDF:2MRD:2HYO
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I have a private insecure registry v2.4, which available at docker-registry:5000

**Steps to reproduce the issue:**
1. Add to docker config `DOCKER_OPTS="--insecure-registry=docker-registry:5000"`
2. Restart docker
3. Try to push image to registry `docker push docker-registry:5000/test`

**Describe the results you received:**
I get error
```
The push refers to a repository [docker-registry:5000/test]
Get https://docker-registry:5000/v1/_ping: tls: oversized record received with length 20527
```
From /var/log/syslog:
```
Jun  3 15:32:27 home docker[4058]: time="2016-06-03T15:32:27.428664730+06:00" level=error msg="Attempting next endpoint for push after error: Get https://docker-registry:5000/v2/: tls: oversized record received with length 20527"
Jun  3 15:32:27 home docker[4058]: time="2016-06-03T15:32:27.432605566+06:00" level=error msg="Attempting next endpoint for push after error: Get https://docker-registry:5000/v1/_ping: tls: oversized record received with length 20527"
```

**Additional information you deem important (e.g. issue happens only occasionally):**
Docker registry was started: `docker run -d -p 5000:5000 --name registry registry:2.4`
There are several virtual machines on Ubuntu 14.04 and docker 1.11.1 which works with this registry successfully.

**Comment by justincormack** [comment]
Hi, have you checked the troubleshooting section here https://docs.docker.com/registry/insecure/ as it mentions this error?

**Comment by terracott** [comment]
@justincormack, yes. From docs: error occurs when no option --insecure-registry.
I set this option in `/etc/default/docker` file

**Comment by dingelish** [comment]
same problem here.
ubuntu 16.04, `--insecure-registry` in /etc/default/docker is set and service restarted. but still 20527

**Comment by mabbasi90** [comment]
Same problem, ubuntu 16.04...
docker version:
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

**Comment by cpuguy83** [comment]
`/etc/default/docker` is specific to upstart.
16.04 uses systemd.

For platform-independent configuration, see `/etc/docker/daemon.json`.
https://docs.docker.com/engine/reference/commandline/daemon/#daemon-configuration-file

**Comment by terracott** [comment]
@cpuguy83, it's working! Thanks
