### ISSUE TITLE
Data volumes deleted with --rm, documentation makes a bad promise

### ISSUE THREAD

**Issue by ToBeReplaced** [docker/docker#23243]
I read the user guide first:
https://github.com/docker/docker/blob/c37ca913ff66b4402aaa8f54e17498a09778be51/docs/userguide/containers/dockervolumes.md#data-volumes

This makes a promise:

```
Data volumes are designed to persist data, independent of the container's life
cycle. Docker therefore *never* automatically deletes volumes when you remove
a container, nor will it "garbage collect" volumes that are no longer
referenced by a container.
```

I did `docker create volume --name test`, then `docker run --rm -v test:/test centos:7`, and voila, my `test` volume is gone. Version 1.9.

Maybe I expect too much, but when the documentation emphasizes "never", I get upset when it turns out to be false. There are a few other issues discussing behavior, like #10545, and I don't know where this issue belongs.

My observation is that `docker run --rm` and `docker rm` are not the same thing, but they overload `rm`, so a difference in behavior is unexpected.

**Comment by shishir-a412ed** [comment]
@ToBeReplaced you mean `docker volume create --name test` :)
Which version of docker are you using ?

Shishir

**Comment by cpuguy83** [comment]
Yes, `--rm` performs a `docker rm -v`, which **does** remove volumes.
However... it should not be removing named volumes.
This was a bug in 1.9. Fixed in 1.10.

**Comment by ToBeReplaced** [comment]
@shishir-a412ed Yes, :). `Docker version 1.9.1, build ab77bde/1.9.1` via CentOS 7.

@cpuguy83 Is it appropriate to modify the documentation for 1.9 and/or edit the head documentation to indicate "as of 1.10"?

**Comment by cpuguy83** [comment]
@ToBeReplaced I'm not sure that the old docs can be modified. It would be perfectly fine to update the head docs to include the info... see https://github.com/docker/docker/blob/c37ca913ff66b4402aaa8f54e17498a09778be51/docs/userguide/containers/dockervolumes.md#removing-volumes
