### ISSUE TITLE
Flaky test: TestBuildDockerignoreComment

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#23246]
This test was added recently, and fails on WindowsTP5; guess this is the issue with Windows not liking filenames named `#1`

```
17:54:09 ----------------------------------------------------------------------
17:54:09 FAIL: docker_cli_build_test.go:6760: DockerSuite.TestBuildDockerignoreComment
17:54:09 
17:54:09 docker_cli_build_test.go:6791:
17:54:09     c.Fatal(err)
17:54:09 ... Error: failed to build the image: Sending build context to Docker daemon 5.632 kB

17:54:09 Step 1 : FROM busybox
17:54:09  ---> 3f1b2939d14c
17:54:09 Step 2 : ADD . /tmp/
17:54:09  ---> 78175a922461
17:54:09 Removing intermediate container e893b2ece047
17:54:09 Step 3 : RUN sh -c "(ls -la /tmp/#1)"
17:54:09  ---> Running in 14e3ac5d6f7e
17:54:09 The command 'cmd /S /C sh -c "(ls -la /tmp/#1)"' returned a non-zero code: 255
```

**Comment by thaJeztah** [comment]
Test was added in https://github.com/docker/docker/pull/23111, but was green when that was merged

**Comment by yongtang** [comment]
@thaJeztah I tried on a PowerShell in Windows TP5 with:
```
cmd /S /C C:\bubybox\busybox.exe sh -c "(ls -la /tmp/#1)"
```
in multiple runs and could not find a problem (`#1` file seems to be OK in PowerShell and busybox.exe as long as it is quoted.).

I did notice that inside the container the cmd was run with a hack to skip the "busybox.exe":
https://github.com/jhowardmsft/busybox/blob/master/Dockerfile
```
RUN powershell busybox.exe --list ^|%{$nul = cmd /c mklink C:\busybox\$_.exe busybox.exe}
```

As a true novice on Windows TP5 and PowerShell I don't know if that will trigger different behaviors.

On a side note, it seems that the above hack to skip 'busybox.exe' is being addressed in:
#22489 Builder shell configuration
I might be able to do more investigation after #22489 is merged in.

**Comment by thaJeztah** [comment]
@yongtang yes, @jhowardmsft mentioned that it may be a Windows bug
