### ISSUE TITLE
/etc/hosts

### ISSUE THREAD

**Issue by rapfigueiredo** [docker/docker#23249]
**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by MHBauer** [comment]
closing as there is no content here for over an hour.
