### ISSUE TITLE
support more types of daemon events besides reload?

### ISSUE THREAD

**Issue by allencloud** [docker/docker#23263]
Hi, All, 

It is really Great for docker to support daemon events (https://github.com/docker/docker/pull/22590) in future's docker 1.12.0. Thank to @yongtang 

Currently docker supports **reload** daemon events which is really important, while in my own opinion, we can enhance this to support more, such as "stop" and "start".
 
Here is my reason:
For one user, he may use event policy to monitor all changes on the docker engine. For example, when service docker restart, user can only get container events such as kill or start, while he has no sense of the scene that docker has restarted. If we can support stop and start daemon events, user can have more info about what indeed happened in the scene.

This is indeed important for Swarm which uses events to get all information of Docker Engine.

**Comment by thaJeztah** [comment]
I can see this working for `stop`, but how would `start` work? Given that you need a running daemon to connect to its even-stream

**Comment by allencloud** [comment]
@thaJeztah 
Here is my case, please check it.

When we got daemon's `stop` event, we can treat it as daemon's exited. Then if daemon starts again, in the period client is always trying to connect with daemon, in some case client receives container's event such as container's `start` event while misses the daemon's `start` event. Then we can treat this as a miss or inconsistency, then do some synchronized things.

**Comment by thaJeztah** [comment]
Yes, but my point was that it would never get the `start` event, because it's not connected at that point

**Comment by allencloud** [comment]
I think it would be better for daemon to emit `start` event after daemon is ready for event stream. In the delta time of : 
* daemon is ready for event stream
* emit a `start` event of daemon

If client succeeds in connection, everything is OK, if fails, we can regard client missed something.

**Comment by runcom** [comment]
I think you can watch dockerd pid with standard Linux facilities to understand daemon events such as start and stop - this means I'm -1 on this. There's no point to me in dockerd providing this functionality as it would be flaky anyway (start and stop being an example)

**Comment by allencloud** [comment]
@runcom 
Yes, I totally agree with you if the client and dockerd are both on a host. We can use other approach to get this. While in my case, Swarm or other remote clients have no right to sense the daemon's stop and start.

**Comment by allencloud** [comment]
Closing this. Seems not so urgent.
