### ISSUE TITLE
https://get.docker.com shell script bug concerning debian based distros

### ISSUE THREAD

**Issue by dimrozakis** [docker/docker#23260]
The shell script from https://get.docker.com/ contains this line for debian/ubuntu based distros:
```
$sh_c "echo deb [arch=$(dpkg --print-architecture)] ${apt_url}/repo ${lsb_dist}-${dist_version} ${repo} > /etc/apt/sources.list.d/docker.list"
```

There's an issue with the `[arch=$(dpkg --print-architecture)]` part. It seems that if there's any file named `a`, `r`, `c`, or `h` in the current working directory, the script will add a line like `deb a https://apt.dockerproject.org/repo debian-jessie main` (if a file named `a` existed) which will cause `apt-get update` to fail later on.

**Steps to reproduce the issue:**
1. Use a debian/ubuntu based distro
2. Touch a file named `a`, `r`, `c` or `h`
3. Run the script served from https://get.docker.com/

See also: https://github.com/docker/docker/issues/20044#issuecomment-223766257

**Comment by dimrozakis** [comment]
I'm not sure, but I think that escaping the brackets with backslashes should fix the issue:
```
\[arch=$(dpkg --print-architecture)\]
```

**Comment by thaJeztah** [comment]
Could well be, I didn't dive into it yet, but the script is in this repository; https://github.com/docker/docker/blob/master/hack/install.sh

If that solves the issue, pull requests are welcome :+1:
