### ISSUE TITLE
oracle12 database fails to run with zfs storage driver

### ISSUE THREAD

**Issue by gerhard6** [docker/docker#23264]
**Output of `docker version`:**

Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

**Output of `docker info`:**

Containers: 15
 Running: 0
 Paused: 0
 Stopped: 15
Images: 17
Server Version: 1.11.2
Storage Driver: zfs
 Zpool: g6
 Zpool Health: ONLINE
 Parent Dataset: g6/docker
 Space Used By Parent: 12362173952
 Space Available: 21250656768
 Parent Quota: no
 Compression: off
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.0-22-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.812 GiB
Name: osboxes
ID: UFG4:2WDE:VSQX:KAVO:4JTI:2HEK:4WQY:W6NL:5QAG:EQDJ:RZMI:D7RD
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

**Additional environment details (AWS, VirtualBox, physical, etc.):**
inside VirtualBox on Win 7

**Steps to reproduce the issue:**
use ZFS storage driver (on AUFS instead of ZFS, everything works as expected.)
use this image: https://github.com/bofm/docker-oracle12c
follow its creation instructions (need to download oracle sw etc)...
running "make test" then fails, relevant part of error output see at the end below

Some explanations follow, more details in this issue, that I created today: 
https://github.com/bofm/docker-oracle12c/issues/10

the failing oracle "listener" and "dbca" both are running with user oracle.
- when running the listener as user "root" (by providing "-u root" on docker run), it works
- when trying to create such a file manually as user oracle, it works, too ("docker exec -it ... bash" etc), seems that the oracle programs do something more than just create/open...
- when running on a non zfs based volume, it also works as expected.

Unfortunately, using "-u root" as a workaround only works for the "listener" process, but not for the  "dbca" process, which rejects "root" user.

relevant error output:

listener: [AutoCreate Relation]: following error encountered and ignored:
listener: DIA-48316: relation [ADR_CONTROL] unavailable or cannot be created
listener: DIA-48210: Relation Not Found
listener: DIA-48166: error with opening ADR block file because file does not exist [/app/oracle/diag/tnslsnr/bc9000c85096/listener/metadata/ADR_CONTROL.ams] [0]
listener: DIA-48122: error with opening the ADR block file [/app/oracle/diag/tnslsnr/bc9000c85096/listener/metadata/ADR_CONTROL.ams] [0]
listener: DIA-27040: Message 27040 not found; product=RDBMS; facility=DIA
listener: Linux-x86_64 Error: 22: Invalid argument
listener: Additional information: 2
...

dbca_log: Creating and starting Oracle instance
dbca_log: DBCA_PROGRESS : 2%
dbca_log: DBCA_PROGRESS : 3%
dbca_log: DBCA_PROGRESS : 5%
dbca_log: ORA-01501: CREATE DATABASE failed
dbca_log: ORA-00200: control file could not be created
dbca_log: ORA-00202: control file: '/data/oracle/oradata/ORCL/control01.ctl'
dbca_log: ORA-27040: file create error, unable to create file

**Comment by gerhard6** [comment]
did another test: run docker itself on aufs, but mount the data volume on a zfs-based host directory. Same error happens
So, in every case, when oracle user with "listener" or "dbca" touch zfs, we get this error.

**Comment by justincormack** [comment]
Ok to rule some things in or out, can you try with various flags to `docker run`:
1. `--security-opt seccomp=unconfined`
2. `--security-opt apparmor=unconfined`
3. `--privileged`
4. `--cap-add sys_admin`
If any of those are different will give a clue, as the error messages are not very helpful.

**Comment by gerhard6** [comment]
--security-opt seccomp=unconfined: same error 
--security-opt apparmor=unconfined: same error
--privileged: same error
--cap-add sys_admin: same error

**Comment by justincormack** [comment]
Ok that rules out some issues. It does look like an ownership or permissions issue on the zfs filesystem then, but it could be something else. Is it possible to run the `dbca` process with `strace -o /tmp/tr -f ...` (you will have to use `--privileged` to do this). This will output a log of the system calls and we can try to work out which one is actually failing, as the error message is not very helpful.

Can you also perhaps try running it in exactly the same way outside docker, as it seems like it might be unrelated.

**Comment by gerhard6** [comment]
did some `strace` based analysis, and it seems that some oracle process tries to open files with `O_DIRECT`, which then fails:

`/tmp/dbca.zfs.230:open("/data/oracle/oradata/ORCL/control01.ctl", O_RDWR|O_DSYNC|O_DIRECT) = -1 EINVAL (Invalid argument)`

this error does not occur, when running on aufs

This led me to this issue https://github.com/zfsonlinux/zfs/issues/224, that is not yet closed, which means that currently the O_DIRECT flag ist not yet supported on ZFS/Linux.

So, therefore I think: unrelated to docker.

Thx Justin for the support !

**Comment by justincormack** [comment]
Ah that makes sense, yes Oracle does need `O_DIRECT`, I did not realise that ZFS does not have support yet, glad you found the reason.
