### ISSUE TITLE
docker -v does not work for directories with one-letter names

### ISSUE THREAD

**Issue by seehuhn** [docker/docker#23275]
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   8acee1b
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   8acee1b
 Built:
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 15
 Running: 14
 Paused: 0
 Stopped: 1
Images: 172
Server Version: 1.10.3
Storage Driver: btrfs
 Build Version: Btrfs v4.2.2
 Library Version: 101
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 4.5.0-coreos-r1
Operating System: CoreOS 1010.5.0 (MoreOS)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 997.2 MiB
Name: seehuhn
ID: U7OX:5KBJ:ESE6:LTI7:ZRNR:DP7Q:ZZTZ:VII5:TIX2:ORZ4:RKYL:TJWU
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This is docker in current CoreOS

**Steps to reproduce the issue:**
1. create a directory with a one-letter name (`/srv/o` in the example below)
2. bind mount this directory into a docker container, using `docker -v ...:...`
3. try to access the directory inside the docker container

**Describe the results you received:**

Something (an empty directory) is mounted inside the container at the location given by the complete argument of the `-v` option, including the host part and the colon:

```
core@seehuhn [/srv] /usr/bin/docker run --rm -it -v /srv/o:/p debian:jessie /bin/bash
root@4ce1889054f1:/# mount | grep '/p '
/dev/vda9 on /srv/o:/p type btrfs (rw,relatime,seclabel,space_cache,subvolid=257,subvol=/root/var/lib/docker/volumes/2a9dc62b01483a2c3153c3502f83721560a91aaf2b2b61325f68792014f7ef5f/_data)
root@4ce1889054f1:~# ls -la "/srv/o:/p"
total 0
drwxr-xr-x. 1 root root 0 Jun  5 17:08 .
drwxr-xr-x. 1 root root 2 Jun  5 17:08 ..
```

**Describe the results you expected:**

I would have expected for the given host directory to be mounted at the given location.  In the example above, I would have expected the contents of the host directory `/srv/o` to be accessible under the name `/p` inside the container like this:

```
core@seehuhn [/srv] /usr/bin/docker run --rm -it -v /srv/o:/p debian:jessie /bin/bash
root@24c9c7e6cb03:/# mount | grep '/p '
/dev/vda9 on /p type btrfs (rw,relatime,seclabel,space_cache,subvolid=257,subvol=/root/srv/or)
```

**Comment by seehuhn** [comment]
Forgot to write: the problem only seems to occur if the directory name consists of a single letter.  Using `/srv/or` in place of `/srv/o` in my original report makes the problem go away for me.

**Comment by thaJeztah** [comment]
Looks like a duplicate of https://github.com/docker/docker/issues/20122, which is fixed by https://github.com/docker/docker/pull/21106 in docker 1.11; can you try on the current release?

**Comment by seehuhn** [comment]
I tried to search for duplicates, not sure how I missed these.  I can't easily try the current version right now, will need to wait until the fix shows up in CoreOS.  Once version 1.11 arrives, I'll check and re-open if needed.

**Comment by thaJeztah** [comment]
Thanks!
