### ISSUE TITLE
Can't start with systemctl - actually, no errors, it just hangs on everything

### ISSUE THREAD

**Issue by tunnckoCore** [docker/docker#23289]
I seen the issue template, but I can't give nothing of wanted. Only a fiew things.

1. I'm on fully upgraded ArchLinux, 64bit processor
2. Installed docker via pacman `pacman -S docker` - no problems
3. Enabled via `systemctl enable docker.service`, reboot
4. Added my username to docker group `sudo usermod -aG docker $(whoami)`, reboot
5. Just hangs on `docker info`, `docker version` and even when `systemctl start docker`, etc.
6. The result of `systemctl status docker.service` is `Active: activating (start)`

```
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: activating (start) since Mon 2016-06-06 04:25:51 EEST; 27min ago
     Docs: https://docs.docker.com
 Main PID: 317 (docker)
    Tasks: 7 (limit: 512)
   Memory: 35.3M
      CPU: 276ms
   CGroup: /system.slice/docker.service
           └─317 /usr/bin/docker daemon -H fd://

Jun 06 04:41:11 voltaire docker[317]:    --debug                                                enable debug output in the logs
Jun 06 04:41:11 voltaire docker[317]:    --state-dir "/run/containerd"                        runtime state directory
Jun 06 04:41:11 voltaire docker[317]:    --metrics-interval "5m0s"                                interval for flushing metrics to the store
Jun 06 04:41:11 voltaire docker[317]:    --listen, -l "/run/containerd/containerd.sock"        Address on which GRPC API will listen
Jun 06 04:41:11 voltaire docker[317]:    --runtime, -r "runc"                                        name of the OCI compliant runtime to use when executing containers
Jun 06 04:41:11 voltaire docker[317]:    --graphite-address                                         Address of graphite server
Jun 06 04:41:11 voltaire docker[317]:    --help, -h                                                show help
Jun 06 04:41:11 voltaire docker[317]:    --version, -v                                        print the version
Jun 06 04:41:11 voltaire docker[317]:    
Jun 06 04:41:11 voltaire docker[317]: time="2016-06-06T04:41:11+03:00" level=fatal msg="flag provided but not defined: -start-timeout"
```

Permissions

```
% ❯ sudo ls -al /var/run/ | grep docker                       June 06, 04:57:54
drwx------  3 root    root      60 Jun  6 04:25 docker
-rw-r--r--  1 root    root       3 Jun  6 04:25 docker.pid
srw-rw----  1 root    docker     0 Jun  6 04:25 docker.sock
```

**Comment by TMily** [comment]
same issue

**Comment by pwhelan** [comment]
this seems to be the commit implementing the flag in containerd: https://github.com/docker/containerd/commit/3742ae3ec888da95554edc7705272bc42d193680. From the looks of it containerd is out of sync with the version of docker on arch.

**Comment by mzry1992** [comment]
Same here, I use `1.11.2, build b9f10c9` and my system is arch linux. I tried restart docker daemon with -D flag, here are what I got:

```
$ sudo docker daemon --debug
DEBU[0000] docker group found. gid: 996
DEBU[0000] Listener created for HTTP on unix (/var/run/docker.sock)
INFO[0000] New containerd process, pid: 4114

DEBU[0000] containerd connection state change: TRANSIENT_FAILURE
Incorrect Usage.

NAME:
   containerd - High performance container daemon

USAGE:
   docker-containerd [global options] command [command options] [arguments...]

VERSION:
   0.1.0 commit: 7e3c007ea30b938561921d0318bc91b7087fbe7d

COMMANDS:
   help, h	Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --debug						enable debug output in the logs
   --state-dir "/run/containerd"			runtime state directory
   --metrics-interval "5m0s"				interval for flushing metrics to the store
   --listen, -l "/run/containerd/containerd.sock"	Address on which GRPC API will listen
   --runtime, -r "runc"					name of the OCI compliant runtime to use when executing containers
   --graphite-address 					Address of graphite server
   --help, -h						show help
   --version, -v					print the version

FATA[0000] flag provided but not defined: -start-timeout
DEBU[0003] containerd connection state change: TRANSIENT_FAILURE
DEBU[0006] containerd connection state change: TRANSIENT_FAILURE
INFO[0006] New containerd process, pid: 4119

Incorrect Usage.

NAME:
   containerd - High performance container daemon

USAGE:
   docker-containerd [global options] command [command options] [arguments...]

VERSION:
   0.1.0 commit: 7e3c007ea30b938561921d0318bc91b7087fbe7d

COMMANDS:
   help, h	Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --debug						enable debug output in the logs
   --state-dir "/run/containerd"			runtime state directory
   --metrics-interval "5m0s"				interval for flushing metrics to the store
   --listen, -l "/run/containerd/containerd.sock"	Address on which GRPC API will listen
   --runtime, -r "runc"					name of the OCI compliant runtime to use when executing containers
   --graphite-address 					Address of graphite server
   --help, -h						show help
   --version, -v					print the version

FATA[0000] flag provided but not defined: -start-timeout
```

**Comment by frol** [comment]
It seems to be an Arch Linux specific bug. I have found this bug report on Arch Linux bug tracker: https://bugs.archlinux.org/task/49582

**Comment by DzikiChrzan** [comment]
This must be an Arch specific bug, my colleague with Mint has no problem with this version and build.

**Comment by NamPNQ** [comment]
Temporary fix is use [downgrader](https://aur.archlinux.org/packages/downgrader/) to downgrade docker to docker-1:1.11.1-1

**Comment by DzikiChrzan** [comment]
Not necessarily downgrader. Just  go to `/var/cache/pacman/pkg/`and use `# pacman -U docker-1:1.11.1-1-x86_64.pkg.tar.xz`.

**Comment by tunnckoCore** [comment]
huh, worked, thanks. Ping when is okey if possible :)

**Comment by BlackIkeEagle** [comment]
If you are more adventerous you can just build containerd 0.2.2 locally and all works fine.

get the pkgbuild from https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/containerd

change the version to 0.2.2 and run `makepkg`

install it with pacman -U containerd..... and restart your docker daemon

**Comment by aleksijohansson** [comment]
@BlackIkeEagle This rebuilding also worked for me!

**Comment by KristjanLuik** [comment]
Rebuilding containerd manually worked for me :P

**Comment by BlackIkeEagle** [comment]
The packages in the repo's have been updated both runc and containerd have the last version now, happy updating :)

**Comment by antonillos** [comment]
@BlackIkeEagle the update worked fast and nice for me!

**Comment by mmoya** [comment]
I'm running latest Arch packages (containerd 0.2.3-1, runc 0.1.1-2, docker 1.11.2-2) and docker fails to start via systemd.

I downloaded the latest release from GH (1.12.1rc2) and ran it as:

    [root@okonkolo mmoya]# docker-containerd --debug
    WARN[0000] containerd: low RLIMIT_NOFILE changing to max  current=1024 max=4096
    DEBU[0000] containerd: read past events                  count=0
    DEBU[0000] containerd: supervisor running                cpus=4 memory=15960 runtime=runc runtimeArgs=[] stateDir=/run/containerd
    DEBU[0000] containerd: grpc api on /run/containerd/containerd.sock 

then

    [root@okonkolo mmoya]# /usr/bin/docker daemon -D -H unix:///var/run/docker.sock --containerd unix:///run/containerd/containerd.sock
    DEBU[0000] docker group found. gid: 996                 
    DEBU[0000] Listener created for HTTP on unix (/var/run/docker.sock) 
    DEBU[0000] containerd connection state change: TRANSIENT_FAILURE 
    DEBU[0016] containerd connection state change: CONNECTING 
    DEBU[0016] containerd connection state change: TRANSIENT_FAILURE 

but `docker ps` or `docker images` hang.

Downgrading docker to [1.11.1-1][1] didn't fix it. Downgrading containerd to [0.2.2-1][2] did.

Upgraded docker again to 1.11.2-2 and everything continued working. So it seems the culprit is containerd 0.2.3-1. 

  [1]: https://archive.archlinux.org/packages/d/docker/
  [2]: https://archive.archlinux.org/packages/c/containerd/

**Comment by BlackIkeEagle** [comment]
@mmoya Its a known issue, Arch Linux must update docker to 1.12 https://github.com/docker/containerd/issues/299
