### ISSUE TITLE
1.11.2 Error on Archlinux

### ISSUE THREAD

**Issue by alfadb** [docker/docker#23288]
When I update docker from 1.11.1 to 1.11.2, docker cannot start.
I use `sudo docker daemon -D`, get this error:

`DEBU[0000] docker group found. gid: 996                 
DEBU[0000] Listener created for HTTP on unix (/var/run/docker.sock) 
INFO[0000] New containerd process, pid: 1181
           
DEBU[0000] containerd connection state change: TRANSIENT_FAILURE 
Incorrect Usage.

NAME:
   containerd - High performance container daemon

USAGE:
   docker-containerd [global options] command [command options] [arguments...]
   
VERSION:
   0.1.0 commit: 7e3c007ea30b938561921d0318bc91b7087fbe7d
   
COMMANDS:
   help, h	Shows a list of commands or help for one command
   
GLOBAL OPTIONS:
   --debug						enable debug output in the logs
   --state-dir "/run/containerd"			runtime state directory
   --metrics-interval "5m0s"				interval for flushing metrics to the store
   --listen, -l "/run/containerd/containerd.sock"	Address on which GRPC API will listen
   --runtime, -r "runc"					name of the OCI compliant runtime to use when executing containers
   --graphite-address 					Address of graphite server
   --help, -h						show help
   --version, -v					print the version
   
FATA[0000] flag provided but not defined: -start-timeout 
`

**Comment by frol** [comment]
#23289 is a duplicate, but it is better formatted, so I suggest to close this issue and follow #23289.
