### ISSUE TITLE
"docker exec sh" hangs with docker 1.11

### ISSUE THREAD

**Issue by gggeek** [docker/docker#23313]
I recently upgraded the 'default VM' which we use to run the Docker stack for our development environments to docker 1.11, docker-compose 1.7.1, and it seems to be less stable than before (running docker 1.6).

The symptoms are:
- the container stack managed by docker-compose does start up successfully
- the 'mysql' container starts on 1st invocation, but the database service does not start (we have a bootstrap script which keeps the container up even if the db service is down)
- I connect to the container running 'bash', then start the mysql service by executing '/etc/init.d/mysql start'
- at this point the command line within the container "hangs"
- from the host machine, I can use 'docker-compose ps' and see that the containers are listed as running
- I can start and stop them as well. They all report as running
- I can run succesfully "docker-exec containername ps"
- but if I try to connect to any of those containers, using eg. "docker-exec containername bash" or , "docker-exec containername sh" all I get is a hung command line
- running "docker-exec containername ls -ltr /var/log" does not show any traces of strange behaviour

Note that this is not 100% reproducible, but since it happened more than a couple of times, I thought I'd report it as bug.

**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:39 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:39 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 18
 Running: 10
 Paused: 0
 Stopped: 8
Images: 215
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 211
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.871 GiB
Name: vulcan_bis
ID: APRC:3GDW:RIFJ:C5WW:GQX4:6JSK:DZ5R:MKJ7:7J6B:AMHE:6PDC:D3XL
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Virtualbox VM.
The VM runs Debian Jessie - 4GB Ram, 2vprocs. It runs on a server also running Debian Jessie.

The Docker images are also based on Jessie.

**Comment by gggeek** [comment]
Most likely something broken in the automation platform had removed '-ti' from the execution of "docker"... re-testing. Sorry for the noise.

**Comment by secangkirkopipanas** [comment]
Same issue happened to me. After some time, I was not able to do 'docker exec bash' to the running container. Not even 'docker ps -a' command.
My temporary workaround is just restart docker service, and restart all containers (and do other actions which applicable).
