### ISSUE TITLE
Docker create in not saving command which has multiple spaces

### ISSUE THREAD

**Issue by rohitjaini** [docker/docker#23329]
**Output of `docker version`:**
Docker Version:
Client:
Version:      1.12.0-dev
API version:  1.24
Go version:   go1.6.2
Git commit:   3d80884
Built:        Mon Jun  6 19:12:50 2016
OS/Arch:      windows/amd64

Server:
Version:      1.12.0-dev
API version:  1.24
Go version:   go1.6.2
Git commit:   3d80884
Built:        Mon Jun  6 19:12:50 2016
OS/Arch:      windows/amd64

**Steps to reproduce the issue:**
1.Docker create –name=test nanoserver ping 127.0.0.1 –t 
2. Docker ps
3. The -t flag is missing.
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS  PORTS               NAMES
27b378e74c25        nanoserver  "ping 127.0.0.1"        13 seconds ago      Created                      test

**Comment by jhowardmsft** [comment]
This regression looks related to the Cobra CLI parsing. This worked before that PR was merged (can't find PR# from phone)

**Comment by justincormack** [comment]
cc @dnephin

**Comment by justincormack** [comment]
also cc @vdemeester

**Comment by vdemeester** [comment]
@justincormack should be fixed here #23338 :angel:
