### ISSUE TITLE
Error while removing volume metadata.db

### ISSUE THREAD

**Issue by jdfless** [docker/docker#23325]
Running a command that cleans up all dangling volumes on a host `docker volume rm`... attempts to clean up the metadata.db volume and fails with an error. It seems to me that this shouldn't be returned as dangling and cleanup shouldn't be attempted on it.

**Output of `docker version`:**

```
docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:51:19 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:51:19 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**
(this is sample output from just one of many nodes affected by this issue)
```
Containers: 8
 Running: 8
 Paused: 0
 Stopped: 0
Images: 68
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 103
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-55-generic
Operating System: Ubuntu precise (12.04.4 LTS)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on our self provisioned VMs.

**Steps to reproduce the issue:**
1. run on a host where the metadata.db volume exists a cleanup volume cmd. ex:
`docker volume ls -qf dangling=true | xargs -r docker volume rm`

**Describe the results you received:**
Error response from daemon: Error while removing volume metadata.db: remove metadata.db: lstat /var/lib/docker/volumes/metadata.db/_data: not a directory

**Describe the results you expected:**
No attempt to delete the metadata.db volume

**Comment by cpuguy83** [comment]
IIRC, metadata.db only exists in docker 1.11
Did you downgrade?

**Comment by HackToday** [comment]
metadata.db also exists in master branch, 1.12-dev 

```
root@5b451cfb7082:/go/src/github.com/docker/docker# ls -l /var/lib/docker/volumes/
total 24
-rw------- 1 root root 32768 Jun  7 05:36 metadata.db
root@5b451cfb7082:/go/src/github.com/docker/docker# docker version
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   ff57220-unsupported
 Built:        Tue Jun  7 05:07:57 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   ff57220-unsupported
 Built:        Tue Jun  7 05:07:57 2016
 OS/Arch:      linux/amd64
```

How do we usually retrieve such db ?  like sqlite cli or other tools ?

**Comment by jdfless** [comment]
ah yes we did have to downgrade. assuming cleanup works in 1.11+ we can close this issue.

**Comment by cpuguy83** [comment]
Indeed, it only lists the dirs, not metadata.db.

Thanks for confirming!

**Comment by HackToday** [comment]
@jdfless  sorry, I am not sure how did you solve the issue ? just `downgrade` docker ?

Is it right fix or workaround ?  Thanks

**Comment by cpuguy83** [comment]
@HackToday The issue is 1.11 creates metadata.db, but 1.10 reads that file as a volume (which it is not).
The fix for  < 1.10 is to delete metadata.db.

**Comment by HackToday** [comment]
@cpuguy83  Thanks for your info. So it means the user upgrade docker, which creates metadata.db. And then downgrade to 1.10.3, It then happened this issue. Is such case ?

**Comment by cpuguy83** [comment]
@HackToday exactly
