### ISSUE TITLE
could not launch any new docker container after 1850 containers launched

### ISSUE THREAD

**Issue by ligc** [docker/docker#23332]
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 1918
 Running: 1853
 Paused: 0
 Stopped: 65
Images: 2
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 3858
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-21-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 188.7 GiB
Name: x3650m4n08
ID: WL45:4OZ5:5ANE:LX2U:HRYA:DEKQ:DNE6:2HY6:CK3E:HJ7I:MAM5:JY6P
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. docker pull yeasy/hyperledger-peer:noops
2. Run the test script as shown below, the script sets the related limits to be bigger numbers and tries to launch 10000 docker containers.  
```
#!/bin/bash

# Prerequisites setup

echo "root soft nofile 1048576" > /etc/security/limits.conf
echo "root hard nofile 1048576" >> /etc/security/limits.conf
echo "root soft nproc 10485760" >> /etc/security/limits.conf
echo "root hard nproc 10485760" >> /etc/security/limits.conf
echo "root soft stack 32768" >> /etc/security/limits.conf
echo "root hard stack 32768" >> /etc/security/limits.conf
echo "kernel.threads-max = 2091845" >> /etc/sysctl.conf
sysctl -p
echo 210000 > /proc/sys/kernel/pty/max
mkdir -p /etc/systemd/system/docker.service.d/

tee /etc/systemd/system/docker.service.d/tasksmax.conf <<-'EOF'
[Service]
TasksMax=infinity
EOF
systemctl daemon-reload
systemctl restart docker

for i in `seq 1 10`;
do
    brctl addbr docker$i
    ifconfig docker$i 172.$i.254.254/16 up
    docker network create --driver=bridge --ip-range=172.$i.0.0/16 --subnet=172.$i.0.0/16 -o "com.docker.network.bridge.name=docker$i" docker$i
done

for i in `seq 1 10`; do
    for j in `seq 1 1000`; do
        let "z=($i-1)*1000+$j"
        echo $z
        docker run --restart=unless-stopped --net=docker$i -d -e CORE_PEER_ID=vp0 -e CORE_VM_ENDPOINT=http://172.$i.254.254:2375 -e CORE_PEER_ADDRESSAUTODETECT=true -e CORE_NOOPS_BLOCK_TIMEOUT=10 yeasy/hyperledger-peer:noops > /dev/null
    done
done
```

3. When launches about 1850 containers, will get "pthread_create failed" error and could not launch any new containers.

**Describe the results you received:**

The output from the script:
```
1844
1845
1846
1847
1848
1849
1850
1851
1852
1853
1854
docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: exit status 2: runtime/cgo: pthread_create failed: Resource temporarily unavailable\nruntime/cgo: pthread_create failed: Resource temporarily unavailable\nSIGABRT: abort\nPC=0x7f9834314418 m=0\n\ngoroutine 0 [idle]:\n\ngoroutine 1 [runnable, locked to thread]:\nruntime.lock(0xc82006c058)\n\t/usr/local/go/src/runtime/lock_futex.go:42 fp=0xc82005fe38 sp=0xc82005fe30\nruntime.chanrecv(0x120dee0, 0xc82006c000, 0x0, 0xc82005ff01, 0x420000)\n\t/usr/local/go/src/runtime/chan.go:401 +0x148 fp=0xc82005fef8 sp=0xc82005fe38\nruntime.chanrecv1(0x120dee0, 0xc82006c000, 0x0)\n\t/usr/local/go/src/runtime/chan.go:349 +0x2b fp=0xc82005ff28 sp=0xc82005fef8\nruntime.gcenable()\n\t/usr/local/go/src/runtime/mgc.go:207 +0x76 fp=0xc82005ff50 sp=0xc82005ff28\nruntime.main()\n\t/usr/local/go/src/runtime/proc.go:73 +0x138 fp=0xc82005ffa0 sp=0xc82005ff50\nruntime.goexit()\n\t/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc82005ffa8 sp=0xc82005ffa0\n\ngoroutine 17 [syscall, locked to thread]:\nruntime.goexit()\n\t/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1\n\nrax    0x0\nrbx    0x7f98346a3700\nrcx    0x7f9834314418\nrdx    0x6\nrdi    0xa20\nrsi    0xa20\nrbp    0x1ad238a\nrsp    0x7fff3bd65218\nr8     0x7f98346a4770\nr9     0x7f98352e5880\nr10    0x8\nr11    0x202\nr12    0x2897320\nr13    0x1a79070\nr14    0x0\nr15    0x8\nrip    0x7f9834314418\nrflags 0x202\ncs     0x33\nfs     0x0\ngs     0x0\n".
1855
docker: Error response from daemon: rpc error: code = 2 desc = "containerd: container not started".
1856
```
**Describe the results you expected:**
As indicated in https://github.com/docker/docker/issues/22978, I could launch more than 9000 containers with the same docker image(different arch of course) and similar hardware configuration on ppc64le platform, I expect to be able to launch similar number of docker containers on x86 also.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by ligc** [comment]
With the busybox docker image, I could launch 2735 containers, which is still a very small number. I was able to launch 13000+ busybox containers on a ppc64le platform with similar hardware configuration.

**Comment by morphyno** [comment]
I seem to be running a hard limit of 285 on my setup. I am fairly new to docker so I don't have a base line comparison. However, I loaded your script from above and reached the exact limit of 285. 

> 281
282
283
284
285
286
docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: could not synchronise with container process: could not create session key: disk quota exceeded".
287
docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: could not synchronise with container process: could not create session key: disk quota exceeded".
288
docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: could not synchronise with container process: could not create session key: disk quota exceeded".
289
docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime
>

I have a pretty heavy duty system, would you happen to have any other configuration recommendations?

> betauser@UTraffic100:/opt/apcon/sbin$ sudo docker info
Containers: 968
 Running: 285
 Paused: 0
 Stopped: 683
Images: 13
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1976
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null
Kernel Version: 3.16.0-30-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 20
Total Memory: 125.9 GiB
Name: UTraffic100
ID: Y2U3:57NC:NMBU:BYAE:PHRK:PRMF:ODUC:LR3I:KSOI:UKTT:XMLP:HVYD
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
>

**Comment by ligc** [comment]
HI,

The error message ""disk quota exceeded"." indicates that you are running out of disk space,  besides disk space, this blockchain container also consumes memory, my observation is that each 1000 container will need 10GB memory. 

I am running my test on a x86 server with 12 CPU cores, 192GB memory and several Tera bytes disk.

**Comment by morphyno** [comment]
Thanks, I did check storage, and there is plenty of storage availabe (3.2TB), I have 20 cores and  128 GB of RAM

`
none            3.5T  116G  3.2T   4% /var/lib/docker/aufs/mnt/dbc8e90dbf56f5cfaa53b59790440c43b09ce11a1e5b9eb575b153edfd950b81
none            3.5T  116G  3.2T   4% /var/lib/docker/aufs/mnt/0dee5c2390b9601b67c8879958266530a929391ee96c7e02b7361dc0bab4bf75
none            3.5T  116G  3.2T   4% /var/lib/docker/aufs/mnt/42492a68bed226d52d892b2449cad599d919fb574fa867025ff16b2edf8ef77d
none            3.5T  116G  3.2T   4% /var/lib/docker/aufs/mnt/4b06a607645a4295860b56a564d3d999fc14d8bbe22c9298aafd9c506496daaf
none            3.5T  116G  3.2T   4% /var/lib/docker/aufs/mnt/76b3a1d2ffba668406b3c4bb2f277046b938f1671d3aabad31efd9558a4672db
none            3.5T  116G  3.2T   4% /var/lib/docker/aufs/mnt/ee737f19e38f91ed1d9268503011c1429e86da25d34dbda16b6db02583ef3a19
none            3.5T  116G  3.2T   4% /var/lib/docker/aufs/mnt/ce7619f3fc9f9add2bf36af0180ebc5f2e65ccc39448d032030d8d18ef60ba0f
none            3.5T  116G  3.2T   4% /var/lib/docker/aufs/mnt/532bc17ebb42e5fffe743a1f4869ce01197512c94cf63e190ed72819d8d33aca
none            3.5T  116G  3.2T   4% /var/lib/docker/aufs/mnt/7e116914f5c501cb3d5a148c5e0958af240d3ce7df8c57759d0c6ef3b7f88199
none            3.5T  116G  3.2T   4% /var/lib/docker/aufs/mnt/d7a830f7ba31c98e272fc8a9c2225da56098f3733d129ae082bd3a4950692bfd
none            3.5T  116G  3.2T   4% /var/lib/docker/aufs/mnt/d8047986a015d9a74395e96ca7550100cc6a1c4b84a4d24ed1e8c1ce8000129c
none            3.5T  116G  3.2T   4% /var/lib/docker/aufs/mnt/42f2261e96f3b222e82fdd11eb757875fd6814c53fe45dbed9272e27a488c133
none            3.5T  116G  3.2T   4% /var/lib/docker/aufs/mnt/afd233345c62fcc737d22911c4972b9f17bb20a36fa6545ad6dbfd749c216dcb
none            3.5T  116G  3.2T   4% /var/lib/docker/aufs/mnt/619814960c2e5a0a0ce7b85405aa1a8b55033adf3e66375903e4a364a96f2663
none            3.5T  116G  3.2T   4% /var/lib/docker/aufs/mnt/2647f0a268dc3dcfe86be02fa5572684793a2bf5307b008f899a4bf2f57484c6
none            3.5T  116G  3.2T   4% /var/lib/docker/aufs/mnt/329f665a46a910941110508e4aba724e99d74ba15fb723d8d581bfe7955f1365
none            3.5T  116G  3.2T   4% /var/lib/docker/aufs/mnt/8663bd58bf07875383bb41b7c6bbbc5621788a77ce87322692d9bb0236037c3b
none            3.5T  116G  3.2T   4% /var/lib/docker/aufs/mnt/a85773a3b4d526362da3ef5a3c4dd0db590876e75e347dea0ad55adc29c902de
none            3.5T  116G  3.2T   4% /var/lib/docker/aufs/mnt/c7667992b56672eda193491ef4cdf21878fe89abdb67d8074bd9791bc4a8ce63
none            3.5T  116G  3.2T   4% /var/lib/docker/aufs/mnt/6800639178ff9c1a3688c59b124467fdc51ec671cad3b7ed3fa10e43e5125746
none            3.5T  116G  3.2T   4% /var/lib/docker/aufs/mnt/b70a7524e5bacaa911f63f215abbd4a5a66a97ee51f6fbfc7c9487e386bfca7d
`

**Comment by morphyno** [comment]
is the a volume quote limit imposed per volume that is independent to actual storage?

**Comment by ligc** [comment]
or, does the user has file system quota? The command "quota <username>" should be able to give some hints.

**Comment by ligc** [comment]
or, does the user has file system quota? The command "quota \<username\>" should be able to give some hints.

**Comment by morphyno** [comment]
Interestingly, I updated to Ubuntu 16.04 and now I can get over 1000 containers. I'm also seeing the same limit you are seeing.

**Comment by justincormack** [comment]
@morphyno your issue is related to this https://github.com/docker/docker/pull/23182 - a few old distros/kernel versions have very low session key limits. You can use `sysctl -w kernel.keys.root_maxkeys=1000000` before running docker to fix this.

**Comment by WeiZhang555** [comment]
I meet the same problem, interestingly I can run about 3300~3400, but never exceed 3400 containers.

Here is docker log:
```
ERRO[3040] containerd: start container                   error=oci runtime error: exit status 2: runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x1221377 m=4

goroutine 0 [idle]:

goroutine 1 [chan receive, locked to thread]:
text/template/parse.(*Tree).peekNonSpace(0xc8200c0540, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/text/template/parse/parse.go:112 +0x169
text/template/parse.(*Tree).itemList(0xc8200c0540, 0xc8202fa8d0, 0x0, 0x0)
	/usr/local/go/src/text/template/parse/parse.go:328 +0xd4
text/template/parse.(*Tree).parseControl(0xc8200c0540, 0x0, 0x180b360, 0x5, 0x0, 0xa, 0xc820204eb0, 0x0, 0x0)
	/usr/local/go/src/text/template/parse/parse.go:452 +0x163
text/template/parse.(*Tree).rangeControl(0xc8200c0540, 0x0, 0x0)
	/usr/local/go/src/text/template/parse/parse.go:494 +0x5c
text/template/parse.(*Tree).action(0xc8200c0540, 0x0, 0x0)
	/usr/local/go/src/text/template/parse/parse.go:368 +0x4c3
text/template/parse.(*Tree).textOrAction(0xc8200c0540, 0x0, 0x0)
	/usr/local/go/src/text/template/parse/parse.go:347 +0x8d
text/template/parse.(*Tree).itemList(0xc8200c0540, 0xc8202fa750, 0x0, 0x0)
	/usr/local/go/src/text/template/parse/parse.go:329 +0x103
text/template/parse.(*Tree).parseControl(0xc8200c0540, 0xc8202f8f00, 0x180b360, 0x5, 0x0, 0x4, 0xc820204dc0, 0x0, 0x0)
	/usr/local/go/src/text/template/parse/parse.go:452 +0x163
text/template/parse.(*Tree).rangeControl(0xc8200c0540, 0x0, 0x0)
	/usr/local/go/src/text/template/parse/parse.go:494 +0x5c
text/template/parse.(*Tree).action(0xc8200c0540, 0x0, 0x0)
	/usr/local/go/src/text/template/parse/parse.go:368 +0x4c3
text/template/parse.(*Tree).textOrAction(0xc8200c0540, 0x0, 0x0)
	/usr/local/go/src/text/template/parse/parse.go:347 +0x8d
text/template/parse.(*Tree).parse(0xc8200c0540, 0xc8202fa660, 0x0, 0x0)
	/usr/local/go/src/text/template/parse/parse.go:292 +0x684
text/template/parse.(*Tree).Parse(0xc8200c0540, 0x1b6df80, 0x172, 0x0, 0x0, 0x0, 0x0, 0xc8202fa660, 0xc8202fc250, 0x2, ...)
	/usr/local/go/src/text/template/parse/parse.go:231 +0x269
text/template/parse.Parse(0x181f7a0, 0x9, 0x1b6df80, 0x172, 0x0, 0x0, 0x0, 0x0, 0xc8202fc250, 0x2, ...)
	/usr/local/go/src/text/template/parse/parse.go:54 +0x14c
text/template.(*Template).Parse(0xc8202f8f80, 0x1b6df80, 0x172, 0xc8201b7bd0, 0x0, 0x0)
	/usr/local/go/src/text/template/template.go:195 +0x2ab
html/template.(*Template).Parse(0xc8202fa630, 0x1b6df80, 0x172, 0x0, 0x0, 0x0)
	/usr/local/go/src/html/template/template.go:158 +0xb8
net/rpc.init()
	/usr/local/go/src/net/rpc/debug.go:39 +0xf8
github.com/ugorji/go/codec.init()
	/go/src/github.com/ugorji/go/codec/time.go:193 +0xa7
github.com/coreos/etcd/client.init()
	/go/src/github.com/coreos/etcd/client/srv.go:65 +0x8d
github.com/docker/libkv/store/etcd.init()
	/go/src/github.com/docker/libkv/store/etcd/etcd.go:593 +0x6a
github.com/docker/libnetwork/datastore.init()
	/go/src/github.com/docker/libnetwork/datastore/mock_store.go:129 +0x74
github.com/docker/libnetwork/config.init()
	/go/src/github.com/docker/libnetwork/config/config.go:251 +0x59
github.com/docker/libnetwork.init()
	/go/src/github.com/docker/libnetwork/store.go:463 +0x6f
github.com/docker/docker/api/server/router/network.init()
	/go/src/github.com/docker/docker/api/server/router/network/network_routes.go:277 +0x47
main.init()
	/go/src/github.com/docker/docker/docker/flags.go:30 +0xb0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 6 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 7 [runnable]:
text/template/parse.lexRightDelim(0xc82020ec80, 0x1b405c0)
	/usr/local/go/src/text/template/parse/lex.go:272 +0xc1
text/template/parse.(*lexer).run(0xc82020ec80)
	/usr/local/go/src/text/template/parse/lex.go:206 +0x52
created by text/template/parse.lex
	/usr/local/go/src/text/template/parse/lex.go:199 +0x15d

rax    0x0
rbx    0x22e3208
rcx    0x1221377
rdx    0x6
rdi    0xe3b
rsi    0x4dda
rbp    0x1b91a75
rsp    0x7fcd654c8838
r8     0xa
r9     0x7fcd654c9700
r10    0x8
r11    0x202
r12    0x7fcd580008c0
r13    0x1b389a8
r14    0x0
r15    0x8
rip    0x1221377
rflags 0x202
cs     0x33
fs     0x0
gs     0x0
 id=2ae84ccac4a3d8680f385c9e72e78a0ad58e185a15e1752fde98998c59599d34
```

docker version: latest master branch.  (can't get in touch of my server, will add HASH later)
OS:   ubuntu 14.04
how to run docker daemon: manually start dockerd on command line, didn't use systemd

I can see there's some related issues: https://github.com/docker/docker/issues/21298  https://github.com/docker/docker/issues/9868 https://github.com/docker/docker/issues/22690,
the suggestion is to set `TasksMax=infinity` in systemd config.  But I didn't use systemd at all, and I can see @ligc already sets this.  

I've tried several days, but get no luck on this.

**Comment by ligc** [comment]
@morphyno, the Linux bridge could only attach 1024 ports,  if we want to attach more ports to the Linux bridge, we will have to update the Linux kernel code and recompile the kernel, using multiple Linux bridges is a simple workaround for this issue.

**Comment by ligc** [comment]
@WeiZhang555,  for the 3300-3400 containers in your environment, are they busybox containers or blockchain containers yeasy/hyperledger-peer:noops?

**Comment by WeiZhang555** [comment]
@ligc  Here's configurations:

```
# ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 514074
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1000000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 514074
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
# sysctl -n kernel.threads-max
1028148
# cat /proc/sys/kernel/pty/max 
210000
```
I've tried Docker version 1.9.0, build 76d6bc9, and Docker version 1.11.0, build bb0e2b2, experimental, they got same result.

I'm tuning the system configurations, and will share to you if I make any progress.

**Comment by WeiZhang555** [comment]
@ligc quick updates, I found the solution of my problem.  docker exhausts `pid` numbers of my system, only need to set a bigger limit for pid_max: `echo 655360 > /proc/sys/kernel/pid_max` . Original number is 32768 which is too small.

Hope this can be helpful to your problem too.

**Comment by ligc** [comment]
HI, 

Yes, I set the /proc/sys/kernel/pid_max 4194304 and then I could launch 10000 blockchain containers on my x86 server now. Thanks a lot. This issue could be closed.

**Comment by thaJeztah** [comment]
@ligc @WeiZhang555 do you think this is important enough to include in the `check-config.sh` script? Similar to https://github.com/docker/docker/blob/master/contrib/check-config.sh#L290-L292 ?

**Comment by ligc** [comment]
@thaJeztah I am not sure if it is important enough to include in the check-config.sh script, this is kind of stress test configuration, running several thousands containers on a single server may not be necessary in most of the customers production systems. Thanks.

**Comment by thaJeztah** [comment]
Thanks for checking, @ligc

**Comment by WeiZhang555** [comment]
@thaJeztah I think it's important, adding a simple check will save users like us a lot of time, at least it gives us some hints about what wrong with it.

I'll do it.

**Comment by morphyno** [comment]
@ligc, can you point to me about the kernel config changes required to exceed 1024 interfaces for 1 bridge?

**Comment by ligc** [comment]
@morphyno I did not attach more than 1024 containers to a single Linux bridge during my test, I was using multiple bridges, attach 1000 containers to each bridge.
