### ISSUE TITLE
userns-remap: default cannot start any containers

### ISSUE THREAD

**Issue by lope** [docker/docker#23337]
**Skip this comment and go to the 2nd comment, it's a much simpler demonstration of the problem**

**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**
```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.8foo+
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 16 GiB
Name: foo
ID: foo
Docker Root Dir: /var/lib/docker/493216.493216
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Host**
Ubuntu 14.04 with self compiled backport 4.4.8 kernel on i7 laptop.

**How the problem occurred**
Docker was working great until I enabled "userns-remap": "default" (adding that to /etc/docker/daemon.json) and restarted docker service.
Then all of my images and containers disappeared. I re-pulled them. Then my custom docker bridges (showing up in `ip addr show`) were neither recognized to exist with `docker run` nor removable with `docker network rm`. I had to remove them with brctl.
Then I loaded my custom docker bridge again but the containers wouldn't start with error:
`docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: could not synchronise with container process: device or resource busy".`

**Steps that might reproduce the issue:**
1. Install docker on a clean ubuntu 16.04 system with only "storage-driver":"overlay" in /etc/docker/daemon.json
2. Pull some images, run containers, stop containers.
3. add "userns-remap": "default" to /etc/docker/daemon.json
4. service docker restart
5. Pull same images.
6. Try start images

The problem seems unrelated to network config. It occurs in every case:
* Custom docker bridge
* (default)
* --net=none

**Failed attempts to solve**

 1. `rm -rf /var/lib/docker` and pulled images fresh.

 2. I saw a slightly similar issue here https://github.com/docker/docker/issues/21702
I didn't have /etc/apparmor.d/docker-engine
But I ran the above the following, it also did not fix the issue.
```
#stop and rm all containers
apparmor_parser -R /etc/apparmor.d/docker
rm /etc/apparmor.d/docker
service docker restart
```

.3. Rebooted.

**Workaround**
If I don't use userns-remap then my containers start without issue.

**Misc info**
This is the 1st time I've tried to use userns-remap:default.

**Kernel Config**
I compiled my 4.4.8 kernel specifically so that I could get all docker features working on my ubuntu 14.04 box. I enabled all of the stuff relevant to cgroups and namespaces.

**Comment by lope** [comment]
I've just tested on a FRESH Ubuntu Xenial 16.04 install (Running inside KVM) with stock kernel and latest docker. It occurs there and is EASY to reproduce in 3 simple steps. It seems like this would happen on many systems?

**Docker info**
```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-21-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 3
Total Memory: 3.859 GiB
Name: foo
ID: foo
Docker Root Dir: /var/lib/docker/165536.165536
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

** Docker version **
```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64
```

Steps to reproduce:
1. Install Ubuntu Xenial 16.04 Desktop (server or netinstall would probably be fine)
2. Install docker as per official instructions
```
apt-get install apt-transport-https ca-certificates
apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" > /etc/apt/sources.list.d/docker.list
apt-get update
apt-get install docker-engine
```
3. 
```
service docker stop
echo '{"storage-driver":"overlay","userns-remap":"default"}' /etc/docker/daemon.json
service docker start
docker pull busybox
docker run -ti busybox bash
docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: could not synchronise with container process: device or resource busy".
```

**Comment by lope** [comment]
I see now this is a duplicate of https://github.com/docker/docker/issues/22633

**Comment by zhanghongce** [comment]
I'm thinking if there is any fix after this. After all, it is now 2018 on Ubuntu 18.04 with 4.15.0-38-generic. Docker  version 18.06.1-ce, build e68fc7a.
