### ISSUE TITLE
er info

### ISSUE THREAD

**Issue by rlouissidney** [docker/docker#23335]
**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by justincormack** [comment]
Assuming this was an error as no information in report.

**Comment by rlouissidney** [comment]
Yes it is an error, sorry, a problem with mouse click in Windows.
