### ISSUE TITLE
Why is docker volume create and rm not symmetrical?

### ISSUE THREAD

**Issue by oleersoy** [docker/docker#23345]
I asked this question here first to make sure that I was not missing something obvious:
http://stackoverflow.com/questions/37684393/why-is-docker-volume-create-and-rm-not-symmetrical

**Comment by cpuguy83** [comment]
1. hindsight
2. volumes don't require a name as one will be generated if not provided.

**Comment by thaJeztah** [comment]
See https://github.com/docker/docker/issues/17194 and https://github.com/docker/docker/issues/18982

**Comment by oleersoy** [comment]
I think I think docker would be more user friendly if the `--name` flag is dropped from, or just made optional, WRT `docker volume create`.

So we could do:
`docker volume create v1` or `docker volume create --name v1`.

**Comment by oleersoy** [comment]
Most other docker commands don't use the --name parameter:
Example
```
$ docker stop test_sshd
$ docker rm test_sshd
$ docker rmi eg_sshd
```

**Comment by cpuguy83** [comment]
Again, this is because name is not required when creating a volume (much like `docker run`).
I'm not saying I don't like it, but have to be very careful about changing the CLI.

**Comment by oleersoy** [comment]
OK I see what you are saying - this actually works:
```
ole@MKI:~$ docker volume create
b11725085cf9614ceba0cf0304eec46219bc41e7df42a82e8311c3d3dd7e4330

ole@MKI:~$ docker volume rm b11725085cf9614ceba0cf0304eec46219bc41e7df42a82e8311c3d3dd7e4330 
b11725085cf9614ceba0cf0304eec46219bc41e7df42a82e8311c3d3dd7e4330
```
But I don't think that doing:

```
ole@MKI:~$ docker volume create v1
docker: "volume create" requires 0 arguments.
See 'docker volume create --help'.

Usage:	docker volume create [OPTIONS]

Create a volume
```
Conflicts with that.  Even though the command line says it does.

**Comment by oleersoy** [comment]
Also the `--name` option can be kept for backward compatibility, while allowing `docker volume create thenameofthevolume`.

**Comment by cpuguy83** [comment]
👍 Are you interested in handling this?
It should be much easier to do now since we've changed to a new CLI backend and can simply mark `--name` as hidden, then check for both `--name` being set and the name argument being set.

**Comment by oleersoy** [comment]
I could give it a shot, although I've never written any go (Mostly java / javascript, etc).  Could you point me to the code.

**Comment by cpuguy83** [comment]
https://github.com/docker/docker/blob/master/api/client/volume/create.go

**Comment by ardnaxelarak** [comment]
If you get stuck I'd like to give it a shot.

**Comment by oleersoy** [comment]
I'm through the code, but it's my first `go` read, so feel free.  I'm sure I'll learn a lot from seeing how it's done.

**Comment by ardnaxelarak** [comment]
In that case I'd like to pick this up and take a shot at it since it doesn't look too hard.

**Comment by oleersoy** [comment]
Just realized that `docker image rm` does not work either ... It would be nice if all commands used the same convention.

**Comment by oleersoy** [comment]
Just sharing some more ideas:

`docker image create image_name`
`docker image rm image_name`

Thoughts?

**Comment by thaJeztah** [comment]
@oleersoy see https://github.com/docker/docker/issues/8829

**Comment by oleersoy** [comment]
@thaJeztah perfect - thanks for pointing that out.

**Comment by ardnaxelarak** [comment]
> "It should be much easier to do now since we've changed to a new CLI backend and can simply mark `--name` as hidden, then check for both `--name` being set and the name argument being set."

@cpuguy83 I couldn't find any way to mark the flag as hidden; would appreciate some guidance if it is possible.

**Comment by dnephin** [comment]
@ardnaxelarak 

```
flags.Lookup("name").Hidden = true
```

Let me know if I can be of any more help

**Comment by cpuguy83** [comment]
@dnephin Thanks, wasn't immediately obvious to me in godoc but I knew I had seen it.
