### ISSUE TITLE
docker pull failed with error pulling image configuration and X.509 cert

### ISSUE THREAD

**Issue by jianghaitao** [docker/docker#23356]
docker info
```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:54:25 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:54:25 2016
 OS/Arch:      linux/amd64
```
docker info
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-16-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.86 GiB
Name: ldap
ID: YAT2:V2M4:UUFZ:K2UZ:MWNZ:JHA4:IHU2:3KYX:WLQD:KALK:3QHH:SFJK
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Http Proxy: http://XXX.com:8080/
Https Proxy: http://XXX.com:8080/
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```
Steps to reproduce the issue:
docker pull cirros
```
error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/f8/f8ce316a37a79a89cb6f9ef65f23b38893fe291b519a8b18cf08af65872f02a9/data?Expires=1465340854&Signature=Q96PmVSybfI23a19jbaeL9VO8Y~vMddft~xNAeff5I1RTpwXl~crLp9Ysmq40vqgan5N8go7Uj40XPbejyodARI6D0VV-CtdtDDJ38BWxkqKDXsbprUMvX2Sw8N258dvMMQo1md13SnyYQeBgsJ0QuEwJeJhZXtmrfI~aDjVsr4_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: x509: certificate signed by unknown authority
```
docker pull busybox
```
Using default tag: latest
latest: Pulling from library/busybox
385e281300cc: Retrying in 9 seconds 
385e281300cc: Retrying in 1 second 
a3ed95caeb02: Downloading 
x509: certificate signed by unknown authority
```

**Comment by DukeDai** [comment]
I have a hint for you: possibly you are working under proxy(enterprise environment). 
I hit your problem when I worked in corp, but no problem in home.

**Comment by jianghaitao** [comment]
This is resolved. Steps taken are
- Obtain a crt from the https://dseasb33srnrn.cloudfront.net with openssl
- Copy the crt to /etc/share/ca-certificates (Ubuntu)
- Restart docker

**Comment by koreshkumar** [comment]
Hi , 

I am facing the same issue, can u please let us know what exactly you have done to solve it ...

**Comment by chadfurman** [comment]
thanks @jianghaitao fixed for me!

**Comment by davesliu** [comment]
@jianghaitao
Could you help to provide the command for how to get the crt from the https://dseasb33srnrn.cloudfront.net with openssl?

**Comment by kamigerami** [comment]
@davesliu  openssl s_client -connect dseasb33srnrn.cloudfront.net:443

**Comment by bouchezb** [comment]
Hello, thanks a lot, I was facing the same issue with docker and finally solved it with your help.
Full command list used is here (note this is for Ubuntu 16.04)

`$ proxytunnel -p proxyhost:8080 -P proxyuser:proxypwd -d dseasb33srnrn.cloudfront.net:443 -a 7000 --verbose & echo -n | openssl s_client -connect localhost:7000 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > ./cloudfront.crt`

proxyhost = IP for your corporation proxy server
proxyuser = user used to connect thru proxy
proxypwd = proxyuser password

This command creates a proxytunnel with clean credentials and creates a daemon on port 7000 in your localhost.
After that you run the openssl s_client command to connect on localhost:7000 and finally extract certificate data to a .crt file in your 

Finally copy .crt file to certificates store
`$ sudo cp cloudfront.crt /usr/local/share/ca-certificates/`

And update certificates
`$ sudo update-ca-certificates`

Hope this helps someone.

**Comment by johnlee** [comment]
Just wanted to say thank you to @jianghaitao ! I had same problem and that worked.

**Comment by symoN5** [comment]
@bouchezb you saved my day!
