### ISSUE TITLE
Alpine based images have a severe issue with mounting volumes when using Docker Machine

### ISSUE THREAD

**Issue by nickjj** [docker/docker#23353]
I'm reporting this on behalf of a bunch of students of mine who are using OSX and Docker Toolbox 1.11 or 1.11.2. This problem does not exist with native Linux (same versions of Docker) but may exist on Windows (untested).

Here's one of their environments where the bug was reproduced (OSX):

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 9
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 13
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.12-boot2docker
Operating System: Boot2Docker 1.11.2 (TCL 7.1); HEAD : a6645c3 - Wed Jun  1 22:59:51 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: saasdocker
ID: QJNX:S3SQ:W6WX:K4AI:VXYI:R6JI:7J42:OAQU:W2FF:HT4S:SFAJ:JNCR
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 25
 Goroutines: 45
 System Time: 2016-06-07T16:33:21.877552369Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
provider=virtualbox
```

**Output of `sw_vers`:**

```
ProductName:    Mac OS X
ProductVersion:    10.11.5
BuildVersion:    15F34
```

### Reproducing the issue

I'm using a Flask application in one of my courses that uses Docker. Some of its source code is open source which you can see here: https://github.com/nickjj/build-a-saas-app-with-flask/.

The master branch above already has a work around applied, but here's the commit that changed it:  
https://github.com/nickjj/build-a-saas-app-with-flask/commit/1754eb5bc920c24a69a21cb5d99713af74f7a05d

Keep in mind that there is a volume mount happening in the `docker-compose.yml` file which allows people to update their code base without having to rebuild the image.

### Bugs reported by students

One student had an issue where every time he saved a file (even if all he did was add a new line), the app would crash with:  `E901 TypeError: compile() expected string without null bytes`.

I was able to reproduce this on my friend's OSX system while I watched him over Google Hangouts.

When attempting to reproduce it while watching my friend's screen, I also had instances where instead of E901 being thrown the file inside of Docker Machine was not being updated.

The interesting thing is that gunicorn (the Python app server) was picking up the change and notifying us in the terminal that it detected a file change and reloaded.

However, the website didn't update (verified with curl / no cache), but more importantly we exec'd into the container and noticed that the files inside of the container were not actually changed.

### Likely cause?

Alpine uses musl libc instead of glib and this may be causing the issue. It's worth reading this issue https://www.virtualbox.org/ticket/9069.

### Work around

For now it seems like ditching Alpine does the trick. I reverted to slim and everything worked as intended.

Over Hangouts we successfully updated the file and saw the changes being reflected in the browser and over dozens of file saves E901 was never thrown again.

2 other students reported that their problems went away with the same work around.

### Scope of the issue

It will probably be a problem with other run times such as Ruby and friends. With the push towards using Alpine as official images, this should be looked into.

**Comment by justincormack** [comment]
It might be better to file this issue against Docker toolbox here https://github.com/docker/toolbox/issues as it seems to be specifically related to Virtualbox file sharing rather than Docker itself.

**Comment by nickjj** [comment]
@justincormack Perhaps https://github.com/docker/machine is even better?

**Comment by justincormack** [comment]
I think toolbox is better, as it looks related to virtualbox specifically.

**Comment by nickjj** [comment]
Thanks, done.

It can be found at https://github.com/docker/toolbox/issues/510.

**Comment by thaJeztah** [comment]
Thanks! let me close this one
