### ISSUE TITLE
inconsistent special character support in old and new style ENV format

### ISSUE THREAD

**Issue by stefanfoulis** [docker/docker#23369]
``ENV ENCODING_CORRECT "Fäncy Ünîcöde"`` works as expected.
``ENV ENCODING_WRONG="Fäncy Ünîcöde"`` seems to mangle the encoding somehow.

IMHO the old format is working correctly and the new format is buggy.

**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:44:17 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 824
 Running: 28
 Paused: 0
 Stopped: 796
Images: 2018
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 4302
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local dvol
 Network: null host bridge
Kernel Version: 4.4.8-boot2docker
Operating System: Boot2Docker 1.11.1 (TCL 7.0); HEAD : 7954f54 - Wed Apr 27 16:36:45 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.858 GiB
Name: default
ID: S64R:75KT:DSTU:7JGN:52LN:IMG6:HPVE:KTBH:Q2BI:DPEG:75KB:F6AL
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 182
 Goroutines: 330
 System Time: 2016-06-08T09:52:01.189725037Z
 EventsListeners: 1
Username: stefanfoulis
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Steps to reproduce the issue:**
build this ``Dockerfile`` in a shell that supports special characters:
```Dockerfile
FROM debian
ENV ENCODING_CORRECT "Fäncy Ünîcöde"
RUN echo $ENCODING_CORRECT
ENV ENCODING_WRONG="Fäncy Ünîcöde"
RUN echo $ENCODING_WRONG
```

**Describe the results you received:**
The output for ``echo $ENCODING_CORRECT`` is: ``Fäncy Ünîcöde``
The output for ``echo $ENCODING_WRONG`` is: ``FÃ¤ncy ÃnÃ®cÃ¶de``

**Describe the results you expected:**
Expected  ``Fäncy Ünîcöde`` in both cases.

**Comment by justincormack** [comment]
Looks like the actual environment variables are also set incorrectly, not just the displayed output.

**Comment by GaretJax** [comment]
It looks like https://github.com/docker/docker/blob/master/builder/dockerfile/parser/line_parsers.go#L62 iterates over each byte instead of each UTF-8 character and causes these errors.

**Comment by GaretJax** [comment]
#dibs
