### ISSUE TITLE
Add ability for container to publish metadata

### ISSUE THREAD

**Issue by kraman** [docker/docker#2336]
I would be very useful to have the ability to publish metadata from a container during runtime that would be retrieved using docker inspect. This might be done via an api call from within the docker container.

Another extension that would be useful is to add a container "state" which is set during runtime. This could be something like initializing -> complete or error. It would offer a quick way to inspect a container using an API to see if the software within the docker container has started successfully and is ready to serve requests.

**Comment by jfrazelle** [comment]
I think this can be closed as a dup of https://github.com/docker/docker/issues/8427 or #9013 or #6839
