### ISSUE TITLE
Installation instructions for RHEL/CentOS should take "Server" version into account 

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#23376]
The installation instructions currently use `$releasever` to configure the right YUM repository to use, however the instructions don't take into account the `Server` releases output the version in a different format (e.g. `7Server` instead of just `7`).

```
$ sudo tee /etc/yum.repos.d/docker.repo <<-'EOF'
[dockerrepo]
name=Docker Repository
baseurl=https://yum.dockerproject.org/repo/main/centos/$releasever/
enabled=1
gpgcheck=1
gpgkey=https://yum.dockerproject.org/gpg
EOF
```

The installation script correctly strips the `Server` before generating the URL, so we should update the documentation to do the same, or show how to;
https://github.com/docker/docker/blob/v1.11.2/hack/install.sh#L283-L285

As reported by Aleksandr Vinokurov on Twitter https://twitter.com/aleksandrvin/status/740548856316858368 (thanks!)

Also;
https://access.redhat.com/discussions/2134691

**Comment by sbose78** [comment]
For RHEL, we have https://docs.docker.com/engine/installation/linux/rhel/

`
baseurl=https://yum.dockerproject.org/repo/main/centos/7
`
Just noticed, and think that's a different issue since we shouldn't be hardcoding version?

**Comment by sbose78** [comment]
As a fix for the documentation of the issue reported,

we should ask the user to execute the command 
`rpm -q --whatprovides redhat-release --queryformat "%{VERSION}\n" | sed 's/\/.*//' | sed 's/\..*//' | sed 's/Server*//'`

and update step 3.

from 
`baseurl=https://yum.dockerproject.org/repo/main/centos/$releasever/`

to
`baseurl=https://yum.dockerproject.org/repo/main/centos/VERSION OUTPUT_OF_PREVIOUS_STEP/`


Let me know if you have a better idea? I could take up this change.

**Comment by sbose78** [comment]
#dibs

**Comment by thaJeztah** [comment]
@sbose78 yes, I've been thinking about that. Although it may not be "best practice", perhaps hard-coding it isn't a bad idea, given that we only support CentOS 7 / RHEL 7 (and no longer CentOS 6), and 8 won't be released in the near future.

`rpm -q` may be the "right" thing to do, but at a risk that people may still copy/paste the output, so perhaps we should not make it harder than necessary and just hardcode;

```
baseurl=https://yum.dockerproject.org/repo/main/centos/7/
```

**Comment by sbose78** [comment]
Thanks @thaJeztah 
In that case, should we hardcode it for Centos as well, or should we add instructions for the user to execute

`rpm -q --whatprovides redhat-release --queryformat "%{VERSION}\n" | sed 's/\/.*//' | sed 's/\..*//' | sed 's/Server*//'`

and replace the output in the yum repo descriptor?

**Comment by thaJeztah** [comment]
@sbose78 I think we should not make it overly complicated, and hardcode for CentOS as well

**Comment by sbose78** [comment]
Cool, will hardcode it then.

**Comment by sbose78** [comment]
Pull request : https://github.com/docker/docker/pull/23510
