### ISSUE TITLE
update win2lin Jenkins setup.sh with latest version

### ISSUE THREAD

**Issue by justincormack** [docker/docker#23379]
cc @jhowardmsft this file does not look like it has been updated:

https://github.com/docker/docker/blob/master/hack/Jenkins/W2L/setup.sh#L187

as it does not copy `dockerd` to the path, only `docker`. Any chance you could update with the actual copy from Jenkins as I may need to make a small change for my PR #23312

**Comment by jhowardmsft** [comment]
Sure. I'll get to this today.

**Comment by jhowardmsft** [comment]
https://github.com/docker/docker/pull/23380 :smile:
