### ISSUE TITLE
OSX 10.11.5 Docker pull extremely slow from private registry for Mac only

### ISSUE THREAD

**Issue by ammianus** [docker/docker#23382]
I looked for existing issues, although some are similar, they are already closed in older versions, so I am creating this new one. Also so far this appears to be specific to my particular combination of OSX + Docker Toolbox (VBox VM + Docker engine) + private docker registry. Similar, but apparently different Issue to #13309 we have a "large" layer in the image I am trying to download (~3+GB).

When I say "slow" it took 6 hrs total time to download this one image. Colleagues on the same internal network downloaded to non-OSX hosts in only 20 minutes or less.

BUG REPORT INFORMATION

Use the commands below to provide key information from your environment:

docker version:
```Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:44:17 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64
```
docker info:
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 21
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.8-boot2docker
Operating System: Boot2Docker 1.11.1 (TCL 7.0); HEAD : 7954f54 - Wed Apr 27 16:36:45 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 9.746 GiB
Name: default
ID: ZAWT:UQY4:FC4N:7DAB:6QTB:BE73:HBJ3:EOBF:NXJW:DEGA:AVAG:ZUR3
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 32
 System Time: 2016-06-08T18:13:30.422397673Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```
uname -a:
```
Darwin *****-mbp.****.com 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016;
root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64
```
Provide additional environment details (AWS, VirtualBox, physical, etc.):
Mac OSX 10.11.5, VirtualBox 5.0.20, Installed with Docker Toolbox

List the steps to reproduce the issue:
1. Using team's private registry, attempt to pull an image for the first time using `docker-compose up`
Image is composed of several layers, one layer in particular was around 3 GB in size.

Describe the results you received:
Pull of image takes approx. 6 hrs to complete

Describe the results you expected:
Colleagues on the same internal network tried to pull the same image from our registry 
Windows Docker Toolbox host: ~20 min
Linux Docker host: ~13 min
Given the Macbook Pro is at least on par with the Windows host in terms of HW specs, would expect something similar.

Provide additional info you think is important:

Disk space does not appear to be an issue on either the Host or the docker-machine VM. (220 GB free)
It seemed as if some layers downloaded extremely rapidly, within a few seconds, but there was one layer of about 3GB in size, where the majority of time was spent. During the time I was waiting for the pull, I observed no significant activity either on CPU, memory or disk/io. Network I/O seemed to average around 100 KB/s received during this period, but I could download other files from FTP or web much faster.
Colleague was able to try to FTP from the private registry server and was getting around 3.0 MB/s download for a simple file transfer.

Not clear if there is some specific configuration required for Docker machine or VirtualBox for Mac?

----------END REPORT ---------

**Comment by thaJeztah** [comment]
Can you open this issue in the Docker Toolbox or Docker Machine issue tracker? Looks like this it an issue with Toolbox. https://github.com/docker/toolbox/issues

Also, perhaps Docker for Mac (beta) would be worth a try; you can register for the beta at beta.docker.com
