### ISSUE TITLE
Hashsum inconsistent in APT repository

### ISSUE THREAD

**Issue by bigeagle** [docker/docker#23396]
Hi there,

Although #23203 seems to be solved, the hash sum mismatching still exists at `/dists/*/*/binary-*/Release` files.

For example, the SHA256 sum of [ubuntu-xenial/main/binary-64/Release](https://apt.dockerproject.org/repo/dists/ubuntu-xenial/main/binary-amd64/Release) is `e2c7e6e7bca81e4d6c124eae595b0d21ab0dd852bd2a49613996ece7de467a9d`  with the size of 1726 bytes,  while according to [itself](https://apt.dockerproject.org/repo/dists/ubuntu-xenial/main/binary-amd64/Release), it's  `e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855` with the size of 0 byte, and according to [ubuntu-xenial/Release](https://apt.dockerproject.org/repo/dists/ubuntu-xenial/Release), it's `3cac35c105375efc58a4e43b2526610fc10ba717c05e3113fbe935d09aeb40fd` with the size of 1726 bytes.

I believe there still exist some bugs in the scripts of building this repo. Please consider fixing this.

Cheers,

**Comment by thaJeztah** [comment]
Thanks @bigeagle, we'll look into this

/cc @mlaventure @tiborvass @tianon @kencochrane

**Comment by MicDeDuiwel** [comment]
I would just like to add, I had a hash sum mismatch issue all of yesterday. Today it seemed to be fixed up until an hour ago when I got the same issue again:

`W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/universe/binary-amd64/Packages  Hash Sum mismatch`

**Comment by bigeagle** [comment]
@MicDeDuiwel your mismatch comes from ubuntu repo, instead of docker.

**Comment by MicDeDuiwel** [comment]
@bigeagle Ah I see. Thank you for clearing that up for me.

**Comment by cpuguy83** [comment]
Yep, looks like a canonical issue.
Closing.

Thanks!

**Comment by cpuguy83** [comment]
My bad, I see the OP is using apt.dockerproject.org

**Comment by mlaventure** [comment]
This should (hopefully) get cleaned up when we find/move to a better solution for generating our apt repo.

Technically only the top most Release/InRelease file matters to apt because it contains the path to the Packages files and from there to the actual debs which is sufficient for apt to find and install them.

**Comment by tiborvass** [comment]
I believe this should be fixed by now. If still not resolved, I believe https://github.com/docker/docker/pull/23824 could have contributed a fix which will be effective after the rc3 release.
