### ISSUE TITLE
docker 1.11.2 inside LXC + userns-remap 

### ISSUE THREAD

**Issue by HamidEDD** [docker/docker#23405]
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:39 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:39 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/493216.493216/aufs
 Backing Filesystem: extfs
 Dirs: 5
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie) (containerized)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 31.47 GiB
Name: deb_t
ID: QFMT:JOXL:CRXN:3AI4:QDE3:EK4R:ASYO:NFDJ:CBKQ:43GE:3VC7:IOSN
Docker Root Dir: /var/lib/docker/493216.493216
Debug mode (client): true
Debug mode (server): true
 File Descriptors: 15
 Goroutines: 45
 System Time: 2016-06-09T14:23:21.820794329+02:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Create LXC Container with all privileges
2. Install docker 1.11.2
3. Configure the docker daemon to use : --userns-remap=default
4. docker run -it --rm --name c1 alpine sh 

**Describe the results you received:**
```
level=error msg="containerd: start container" error="oci runtime error: could not synchronise with container process: no such file or directory" id=9112dc6a2951055fd88f3f98184ef0442158b69097ffc535ae3bbd2317289859
```
The container creation work correctly when I run docker without "--userns-remap=default", 

see http://pastebin.com/6pe96Nk4 for more  debug logs

Do you have any  idea how can I fix that ? 

Thank you

**Comment by thaJeztah** [comment]
Possibly related to https://github.com/docker/docker/pull/20902 ?

**Comment by HamidEDD** [comment]
@thaJeztah I don't think so, because i'm not trying to run the engine daemon inside a userns.
My Daemon is already inside a privileged LXC Container (shares the root userns of the host)  and it start correctly.
My problem here, is when I tell the daemon engine to run containers inside userns, creation fails with a not very clear error messages : 
```
level=error msg="containerd: start container" error="oci runtime error: could not synchronise with container process: no such file or directory" id=9112dc6a2951055fd88f3f98184ef0442158b69097ffc535ae3bbd2317289859
```
I have done the same operations using docker 1.10.3, & it worked properly.

**Comment by justincormack** [comment]
It might help to `strace` the `docker-containerd` process while you do this so we can see where it fails. It might also be worth trying master (there are some improved error messages from containerd issues). I can't think of any reason why this should not work in principle...

**Comment by HamidEDD** [comment]
@justincormack `strace -p $pid_docker-containerd` does not return any output,
However, I get that   http://pastebin.com/nUsppcwc  when I `strace` the `$docker_pid `.

**Comment by justincormack** [comment]
You need `strace -f`, sorry.

**Comment by HamidEDD** [comment]
@justincormack see here [strace.txt](https://github.com/docker/docker/files/309242/strace.txt)
I saw dozens of lines  `openat(AT_FDCWD, "/run/containerd/3dad2fdb67085f20bf4cfa06a289533b6aede9686655f40cfdc5bafbb633c347/init/pid", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)`

**Comment by justincormack** [comment]
It is not very obvious from that trace. It might be worth trying master (or the rc next week) to see if it gives a better error message.

**Comment by HamidEDD** [comment]
@justincormack , I'll let you know once I would have tested the RC version.
thanks

**Comment by HamidEDD** [comment]
@justincormack problem solved.  I've realized that the `/dev/fuse` device isn't automatically mounted inside the container. Add the device has solved my problem.
I close this issue.
thanks

**Comment by justincormack** [comment]
Ah great! Glad it was something fixable if somewhat obscure!
