### ISSUE TITLE
Unable to install Docker Trusted Registry in a UCP node

### ISSUE THREAD

**Issue by ackris** [docker/docker#23414]
@dnephin 

**Environment:** 
4 ec2 instances of Ubuntu 14.04 

I wanted to create High Availability with Docker Data Center (DDC). To achieve this, I have created **_3 UCP controller nodes_** and **_1 UCP node_**. 

**Result till now:**
UCP is working fine. 

**Problem:**
I am facing problem with docker trusted registry. 

`ubuntu@ip-172-31-22-108:~$ docker run -it --rm docker/dtr install --ucp-url https://ec2-54-169-174-151.ap-southeast-1.compute.amazonaws.com:443 --ucp-node ec2-54-169-17-63.ap-southeast-1.compute.amazonaws.com --dtr-external-url ec2-54-169-17-63.ap-southeast-1.compute.amazonaws.com  --ucp-username admin --ucp-password admin --ucp-ca "$(cat ucp-ca.pem)"`

Errors:
```
ERRO[0001] Make sure that there is a node in your UCP cluster where port 80 and port 443 are open. Also confirm that all UCP node have the DTR images or can obtain them from Docker Hub.
FATA[0001] Problem running container 'dtr-phase2' from image 'docker/dtr:2.0.1': Couldn't create container 'dtr-phase2' from image 'docker/dtr:2.0.1': Error response from daemon: Unable to find a node that satisfies the following conditions
[available container slots]
[node==ec2-54-169-17-63.ap-southeast-1.compute.amazonaws.com node!=ip-172-31-28-94 node!=ip-172-31-31-128 node!=ip-172-31-31-80]
```
I did try to find a solution through Google search. But, all the efforts hit a dead end.

Please help me to rectify this problem. :) 

Here is the screenshot

![screenshot 497](https://cloud.githubusercontent.com/assets/17488478/15937807/0544b516-2e8e-11e6-93d8-519037de077e.png)

**Comment by dnephin** [comment]
Did you mean to ping @dhiltgen  ?

**Comment by ackris** [comment]
@dnephin  anyone can help me :)

**Comment by huslage** [comment]
This is not the appropriate place for support queries on Docker Datacenter. There is a forum at: https://forums.docker.com/c/docker-data-center for discussions like this. You can also email support@docker.com for help.

**Comment by huslage** [comment]
The `--ucp-node` flag is used to define which node DTR gets installed onto. It needs port 443 free, but if 443 isn't free (due to UCP running on that port) the install will fail. Try changing the port that UCP is on and you should be good to go.

**Comment by cpuguy83** [comment]
Thanks @huslage!

Closing as this is not really a docker issue.

**Comment by zht452432830** [comment]
hello,I got the same problem.
Could you tell me how to solve it as huslage said ? Thanks

**Comment by mohanpindyala** [comment]
Guys I am also facing same issue . whats going here . My node is successfully registered to UCP though. any ideas ?

**Comment by zht452432830** [comment]
I solved this by using `--controller-port xx(can't be 443)` when installing UCP.
UCP and DTR's default port is 443. If UCP and DTR on the same machine, port conflicts should be solved.
@mohanpindyala
