### ISSUE TITLE
Docker bridge is created with existing IP address

### ISSUE THREAD

**Issue by kuruoujou** [docker/docker#23420]
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:54:25 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:54:25 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 204
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /media/data/docker/aufs
 Backing Filesystem: extfs
 Dirs: 242
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-36-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.63 GiB
Name: Nyaruko
ID: AJ3T:SQAM:73YQ:APMY:WAP7:GRQB:AM4I:3IHX:EXN6:JXRI:FS77:DYAU
Docker Root Dir: /media/data/docker
Debug mode (client): false
Debug mode (server): false
Username: kuroshi
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical host running Ubuntu 15.10.

**Steps to reproduce the issue:**
1. Have a network at 172.17.0.1
2. Make sure the docker0 bridge interface does not exist
3. Run `service docker start` or your equivalent

**Describe the results you received:**
A bridge is created using 172.17.0.1, which already exists in our network as a router, even with a host name!

**Describe the results you expected:**
A bridge being created on an address that is not used in a space that is unused. I jump up to the 172.19/16, for example, and there is nothing. 

**Additional information you deem important (e.g. issue happens only occasionally):**
Docker-compose keys off of this value and simply adds one to the second octet, as if there will never be anything in any /16 above it, which is clearly not valid (I only ever noticed this bug because docker-compose created a network on the 172.18 network, and I have machines I actively use on that network. The 172.17 isn't used by me personally, so I didn't notice until things started failing). The docker-compose bit probably needs to be addressed in a bug to them.

I'm incredibly surprised, though, that the docker daemon doesn't even do a simple reverse-ip lookup to make sure an IP isn't in use already.

**Comment by kuruoujou** [comment]
As an inconsequential note about my docker-compose comment, after using --bip to move the address that docker uses it looks like docker-compose starts creating networks at 172.17, just like docker proper, which causes the same issues I was seeing before. I basically can't trust docker or docker-compose at this point to create a network in a valid space without manually giving each network in docker-compose and docker itself it's own network space. It's not particularly relevant to this ticket, I just thought I should clarify in case this comes up in any google searches or anything.

**Comment by aboch** [comment]
@kuruoujou 

Specfifying `--bip` only affects the default "bridge" network, the one which relays on docker0 bridge.

docker-compose does not play a role is choosing the subnets for your compose defined networks (if no subnet is specified), that is done by docker engine: As for user created networks, docker picks a subnet from a predefined list, after verifying it does not overlap with any route on the host or with any nameserver in `etc/resolv.conf`.

So as a workaround, you can add the route to your 172.xx.xx.xx network on your host or add a bogus nameserver.

**Comment by mavenugo** [comment]
@kuruoujou I agree with @aboch 's comment. If you are depending on the `pre-defined` subnet for a network, then docker does the best it could to not step on existing local subnets or routes or nameserver defined in resolv.conf.

For any such system operations which depends on underlay subnets, we recommend to use user-defined subnets with user choosing the subnet. You can also configure such subnets in compose file for custom networks as well.

I will close this issue now. Pls comment if you cannot make it work with the available options.

**Comment by kuruoujou** [comment]
Apologies for the delay in response.

I see. I have come up with a workaround, unfortunately that basically boils down to disable docker entirely on the machine to do whatever I need to on the local network, and then reactivate it if I need it. This basically means I cannot use docker in production at all if the machine will need to communicate with other machines on that network.

Adding a bogus nameserver isn't really an option, as a real nameserver already exists to respond to requests for that subnet, but the nameserver in question isn't in that subnet - this is a massive university network spanning multiple subnets, so we can't exactly spin up a nameserver up on each one. In addition, on the machine in question, `/etc/resolv.conf` is handled by resolvconf, so the nameservers in /etc/resolv.conf will not necessarily match the nameservers in use (which I don't exactly like, but that's a different problem).

In theory, setting the route could work, except that means in order to insure docker will not select a network that is already in use, I would have to manually (or via config management) set the routes on every machine that needs docker for every subnet we use - that's not a small number, and it basically undermines the entire network setup we already have built, which seems disingenuous. It is certainly a possible workaround, but not exactly a sustainable plan.

In order to have a sustainable plan, I need to be able to tell docker explicitly "These ranges are okay to use" or "these ranges are not okay to use".  I might have missed some docker setting that does this, but if I haven't, consider this a feature request. Relying on the host's networks will not work in general, as the host might be in a much larger network plan then it even "knows". 

Additionally, I realize it's difficult to come up with a network range that isn't being used by someone somewhere, however this particular range seems to be a poor choice, as it's a range that is in quite heavy use on internal corporate (and university) networks globally. I would suggest something much less common, perhaps the 192.168.150/24 range and up, or something similar. That range is generally not used by consumer networks, which is why I assume you were avoiding the 192.168 range in the first place, and is particularly uncommon (though I'm sure not unheard of) on corporate internal networks, which in my experience seem to use 172.* and 10.* addresses.
