### ISSUE TITLE
Automatically create BTRFS subvolumes for Docker volumes

### ISSUE THREAD

**Issue by RikuXan** [docker/docker#23423]
As a preface, I want to say I am not sure whether I have really understood how Docker and BTRFS interact with each other, if there are any errors or misconceptions on my side, please do tell.

I'm running a Docker installation with BTRFS as my storage driver. Now I recently added my backup solution and was somewhat surprised that, as it seems, the volumes created under `/var/lib/docker/volumes` are actually not created as BTRFS subvolumes and the existing subvolumes under `/var/lib/docker/btrfs/subvolumes` are only for images and containers as far as I can tell.

Might it be a good idea to automatically create volumes under a new BTRFS subvolume? I can imagine certain operational advantages, e.g. the ability to create and restore snapshots for the volumes (often containing application configuration or data files), or the ability to sync incremental backups to a remote machine using BTRFS send/receive. While I can see these advantages, I am not sure about technical issues or risks that could arise, so it would be nice if someone more experienced could weigh in.

**Comment by ccomb** [comment]
Hi, I started such a plugin in https://github.com/anybox/buttervolume
Feedback is welcome, one of the goals is to use send/receive to replicate volumes across several hosts

**Comment by thaJeztah** [comment]
Let me close this issue, because this is best implemented as a volume-plugin, but feel free to continue the conversation (and nice to see someone already worked on creating such a plugin).
