### ISSUE TITLE
Always Monolithic Upload

### ISSUE THREAD

**Issue by sunkuet02** [docker/docker#23427]
I am using docker of :
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 OS/Arch:      linux/amd64

While pushing into docker, I need to force the client to always push with Monolithic Upload. If a chunk request is received the registry must tell the client to fall back to Monolithic Upload and send the layer at once.

Is it possible for current version of docker ? If it is, How can it be ?

**Comment by cpuguy83** [comment]
Sounds like a dup of #17841?

**Comment by thaJeztah** [comment]
agreed; let's close this, please continue the discussion on https://github.com/docker/docker/issues/17841
