### ISSUE TITLE
Can't pull logstash 5.0.0-alpha3-1 tag

### ISSUE THREAD

**Issue by mostolog** [docker/docker#23428]
Hi.

Brief and concise:  `docker pull logstash:5.0.0-alpha3-1`
Returns:
**Tag 5.0.0-alpha3-1 not found in repository docker.io/library/logstash**

https://hub.docker.com/_/logstash/
Regards

**Comment by thaJeztah** [comment]
Can you open an issue in the issue tracker for that image? https://github.com/docker-library/logstash/issues, this issue tracker is for the docker software only, not for the official images, thanks!

**Comment by mostolog** [comment]
Done [#48](https://github.com/docker-library/logstash/issues/48)
Thanks.
