### ISSUE TITLE
Docker doesn't release disk space used by `~/Library/Containers/com.docker.docker/`

### ISSUE THREAD

**Issue by kommen** [docker/docker#23437]
**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   8b63c77
 Built:        Fri Jun  3 08:34:52 2016
 OS/Arch:      linux/amd64
```

Trying to update says:
> Docker 1.11.1-beta14 is currently the newest version available.

**Output of `docker info`:**

```
docker info
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 0
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 27
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.11-moby
Operating System: Alpine Linux v3.3
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.955 GiB
Name: moby
ID: TER2:AI3F:QLVM:OMSA:QBZD:3YEG:HRQN:RTJY:7CBO:Q5IY:4OSG:HJMP
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 25
 Goroutines: 43
 System Time: 2016-06-10T15:54:47.675117153Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: nextjournal
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):** OS X 10.11.5 (15F34)

**Steps to reproduce the issue:**
Delete all images, `docker images -a` reports no images installed

**Describe the results you received:**
Docker still uses all the space it once occupied, even after deleting all images:

```
$ du -h -d 1  ~/Library/Containers/com.docker.docker  
 25G	/Users/kommen/Library/Containers/com.docker.docker/Data
 25G	/Users/kommen/Library/Containers/com.docker.docker
```

**Describe the results you expected:**
Used space released after removing images with `docker images -q | xargs docker rmi --force`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
I think this is a known issue with Docker for Mac (although I see it's not listed in https://beta.docker.com/docs/mac/troubleshoot/#known-issues @justincormack). The space is probably occupied by the `Docker.qcow2` file, which is the filesystem for the "vm" that Docker for Mac runs in.

Given that this is a Docker for Mac issue, please report/discuss this on https://forums.docker.com/c/docker-for-mac, so that other users running the beta can also benefit from it. I'll close this issue here, but feel free to continue the discussion 👍

**Comment by thaJeztah** [comment]
Note that you can exclude this file from your Time Machine backups (inside preferences), also, doing a "factory reset" (reset/uninstall) should erase and re-create that file (but you'll loose all your containers and images obviously :smile:)

**Comment by kommen** [comment]
@thaJeztah thanks for the quick reply!

The space is occupied by this file:
`25G /Users/kommen/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux`

Yes, uninstalling and reinstalling does remove the file, but it obviously grows again with continued usage. I will report this in the forums.

Thanks again!

**Comment by kommen** [comment]
For reference the forums thread: https://forums.docker.com/t/docker-doesnt-release-disk-space-used-by-library-containers-com-docker-docker/15194

**Comment by yakticus** [comment]
I am running version 1.12.0-a (build: 11213) and still experiencing this issue. Nothing I have tried has changed the size of the file `Docker.qcow2` (>41GB), including deleting all containers and removing 141 out of 194 images that were cached locally.

The above commit hints it has been resolved, but it doesn't seem to be. I checked out the aforementioned forum thread but it didn't contain any useful information. Is there a good place to report this issue for docker for mac, other than the forum?

version details:
```
$ docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      linux/amd64
```

**Comment by thaJeztah** [comment]
@yakticus we recently opened a separate issue tracker for Docker for Mac; https://github.com/docker/for-mac/issues

**Comment by yakticus** [comment]
Thanks. What's the issue #? I searched for some obvious keywords but couldn't find it in that repo.

**Comment by thaJeztah** [comment]
Oh, I don't know, not sure if there is an issue already for it :blush: @dsheets may know

**Comment by yakticus** [comment]
oh sorry. I read your comment the wrong way. You said "separate issue tracker" and I read "separate issue". The new one is attached (above).

**Comment by christophe-f** [comment]
I barely use Docker and my file size is 61Gb. Crazy

**Comment by nroose** [comment]
Mine was 254GB. Deleted and restarted.

**Comment by freedev** [comment]
57G

**Comment by carminexx** [comment]
Still having this issue. Even if I delete all container and images no disk space is released.
(Note: Docker 1.12.6)

**Comment by dsheets** [comment]
The disk image resizing feature is still only on the Beta channel. It should reach the stable channel this week or next week.

**Comment by freedev** [comment]
great

**Comment by achikin** [comment]
docker --version
Docker version 17.03.1-ce, build c6d412e
Having this issue too. How can I develop for docker if I run out of space every 2 days?

**Comment by thaJeztah** [comment]
@achikin see https://github.com/docker/for-mac/issues/371#issuecomment-298929484

**Comment by eaorak** [comment]
Had the same problem, from UI, Docker > Reset > Remove All Data has reduced the folder size from 11G to 1.8G.

**Comment by thekashifmalik** [comment]
I've been doing what @eaorak suggested. It is not ideal.

**Comment by evgenity** [comment]
I've added
```rm -rf ~/Library/Containers/com.docker.docker/Data/*```
option to my docker Makefiles.
You'll have to sign-in to docker after that, but comparing to 100Gb of trash that's not a big deal.



```
fixqcow:
	rm -rf ~/Library/Containers/com.docker.docker/Data/*
```

**Comment by ssotomayor** [comment]
@diegolaciar You can reduce Docker's disk image size in Docker Menu -> Preferences -> Disk. The default size is 64GB, that's why it appears again when you restart.

**Comment by diegolaciar** [comment]
The other day I found that trick on the web.
That was the solution for me. Now the image size is 16GB.

Thanks @ssotomayor

**Comment by jbburf** [comment]
Reduced my resources to 8gb (showing 3.6gb used) and restarted which fixed this issue. Would be great if this was fixed more globally

**Comment by donovanrichardson** [comment]
I'm having an issue where the size of the Docker.raw file according to `ls` is 8 GB, yet the size of the data folder is 17 GB, and the size of com.docker.docker is 64GB. Docker.raw is the only large file in any of those folders. My Mac is running into space constraints because of the large amount of data this is taking up, even though my disk image size setting is now only 8GB.

**Comment by thaJeztah** [comment]
> the size of com.docker.docker is 64GB. Docker.raw is the only large file in any of those folders. My Mac is running into space constraints because of the large amount of data this is taking up, even though my disk image size setting is now only 8GB.

hmm.. that's odd; following the docs; https://docs.docker.com/docker-for-mac/space/#reduce-the-maximum-size-of-the-file

> 3. Click Apply & Restart.
>
> When you reduce the maximum size, the current disk image file is deleted, and therefore, all containers and images will be lost.

Did it remove and recreate the image after you applied the settings?
