### ISSUE TITLE
Random write errors on osxfs

### ISSUE THREAD

**Issue by andyneff** [docker/docker#23440]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   8b63c77
 Built:        Fri Jun  3 08:34:52 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 22
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 22
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.11-moby
Operating System: Alpine Linux v3.3
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.954 GiB
Name: moby
ID: 2VUW:S2QM:D56O:ZGKI:K3BI:AL3W:BN3E:QL4I:HZCE:7P4Z:CYNJ:J4QI
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 22
 Goroutines: 50
 System Time: 2016-06-10T15:12:42.856376738Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
```

`uname -a` on a MacBook Pro 15.1" Mid 2012

    Darwin new-host-4.home 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64

**Steps to reproduce the issue:**
1. `docker run -it --rm -v ~/blah:/home/dev andyneff/docker_mac_osxfs_error`

**Describe the results you received:**

It fails on one of the extracting debug info from steps, towards the end of the process.

```
extracting debug info from /home/dev/rpmbuild/BUILDROOT/proj-4.9.1-2.el7.centos.x86_64/usr/bin/cs2cs
extracting debug info from /home/dev/rpmbuild/BUILDROOT/proj-4.9.1-2.el7.centos.x86_64/usr/bin/geod
extracting debug info from /home/dev/rpmbuild/BUILDROOT/proj-4.9.1-2.el7.centos.x86_64/usr/bin/nad2bin
extracting debug info from /home/dev/rpmbuild/BUILDROOT/proj-4.9.1-2.el7.centos.x86_64/usr/bin/proj
eu-strip: while writing '/home/dev/rpmbuild/BUILDROOT/proj-4.9.1-2.el7.centos.x86_64/usr/bin/proj': cannot write data to file
```

I have had it fail on cs2cs, geo, and proj, or not fail at all and actually succeed! When I first encountered this error, it happened like 10 times in a row. Now I run this docker proof-of-failure 10 times and sometimes it doesn't fail at all. End result, it's an intermittent issue

**Describe the results you expected:**
It not to fail

**Additional information you deem important (e.g. issue happens only occasionally):**

Issue happens only occasionally, but it NEVER happens when I use a `docker volume` instead of mounting a directory from the host via the `-v` option. For now I have to copy my ENTIRE project into a docker volume, and run from there. This is less then ideal for development as I do not have a way to expose that directory back to the host for code editing (short of running a samba server inside the docker......)

I've tried to make this more reproducible, but I just don't understand enough to make it so. Adding CPU load didn't help or hurt, and adding disk io load... kinda of broke everything.

**Comment by thaJeztah** [comment]
Thanks for reporting! I see that @jeanlaurent created an issue (nr. 3876) to track this in the private "Docker for Mac" issue tracker

**Comment by thaJeztah** [comment]
Could you open a topic on https://forums.docker.com/c/docker-for-mac as well (if it doesn't exist yet), that way other users running the Docker for Mac beta can more easily find it, and stay informed

**Comment by andyneff** [comment]
[Done](https://forums.docker.com/t/random-write-errors-on-osxfs/15215). The closest I could find was [this](https://forums.docker.com/t/unable-to-perform-any-npm-install-inside-a-osxfs-mounted-directory/12590) and I wasn't sure if it was the same or not.

**Comment by thaJeztah** [comment]
Thanks! Sorry it's sometimes a bit confusing, because Docker for Mac is a separate project (and team) from the "docker engine" itself

**Comment by samoht** [comment]
We have a fix for this that we will ship in our next release.

**Comment by dsheets** [comment]
We believe we have fixed this issue and it can now be closed.

**Comment by cpuguy83** [comment]
Awesome, thanks!
