### ISSUE TITLE
RFC: remove distros that we don't ship packages for from the install script

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#23445]
Our installation script on get.docker.com / experimental.docker.com currently contains some distros that we don't ship packages for.

I'm not sure about the background for this, but having the install script install packages that we don't ship ourselves, and cannot provide support for, is confusing.

Removing these distros may need changes in Docker Machine; I tracked down the PR that added SUSE and openSUSE, and reason for adding those was so that Docker Machine could provision using the standard installation script (see https://github.com/docker/docker/pull/13714 and https://github.com/docker/docker/pull/16221)

We can consider having a separate provision script for Docker Machine, that _does_ include these distros, or rewrite the provisioners in Docker Machine to not depend on this installation script.

/cc @mlaventure @tianon @nathanleclaire

**Comment by tianon** [comment]
+1, let's convert all the provisioners in Docker Machine to use a more
specific means of installation in all cases IMO, especially since it
already needs to do platform detection (but the ones we don't officially
support seems like a sane enough place to start)

**Comment by nathanleclaire** [comment]
> +1, let's convert all the provisioners in Docker Machine to use a more
specific means of installation in all cases IMO, especially since it
already needs to do platform detection (but the ones we don't officially
support seems like a sane enough place to start)

Yes, as temporary hacks like the install script method have a tendency to do, it became a permanent hack.

I do feel it's within the liberties of the project to remove them from the install script, as we simply cannot provide anything for users which we cannot verify the quality or integrity of ourselves.  My ask would mainly be to keep @flavio in the loop and hopefully he can update the Machine provisioner to use `zypper` etc. directly.

**Comment by thaJeztah** [comment]
@nathanleclaire agreed; I was about to open a PR, but found out the reason why it was included, so updating docker-machine provisioning before removing it from the script sounds like a sane solution.

also ping @cyphar

**Comment by flavio** [comment]
> My ask would mainly be to keep @flavio in the loop and hopefully he can update the Machine provisioner to use zypper etc. directly.

The docker-machine provisioner can already install docker on openSUSE and SUSE Linux Enterprise machines using the official packages built and maintained by SUSE.

**Comment by flavio** [comment]
Ops, ignore my previous post. I confused this thread with another one.

How do you plan to allow openSUSE/SUSE users to use docker-machine using our packages?

**Comment by thaJeztah** [comment]
@flavio I think this  https://github.com/docker/machine/blob/48554182f13ba73dd96d124f4fdcb6789dec5efe/libmachine/provision/suse.go#L166 needs to be changed to not use the generic install option, but to simply use the steps that the script currently does directly

**Comment by thaJeztah** [comment]
I opened https://github.com/docker/docker/issues/23480 to continue the discussion, but that would rely on having the docker-machine provisioning scripts to be updated first

**Comment by flavio** [comment]
> @flavio I think this https://github.com/docker/machine/blob/48554182f13ba73dd96d124f4fdcb6789dec5efe/libmachine/provision/suse.go#L166 needs to be changed to not use the generic install option, but to simply use the steps that the script currently does directly

Are you proposing to "embed" these steps into docker-machine code? By  doing that  docker-machine will still be able to handle openSUSE/SLE machines (which is great) but will still install the official packges from openSUSE/SLE. Doesn't that bring us back to the initial point?

**Comment by nathanleclaire** [comment]
Yes, @flavio is exactly correct.

I think the best solution would be for SUSE to work with Docker to ensure that they are packaging it in the manner we expect.  So far, that's how we've handled this issue, e.g. RancherOS initially had a slightly modified version of Docker to deal with reaping zombies, but they very graciously worked with us to get back to the direct upstream.  If we (Docker) don't have 100% clear expectations for how it should be packaged, we should get them.

We could roll out these changes for 1.12 and hopefully only need to make small modifications to the install script or to Machine as it stands today.

@thaJeztah Do you think that sounds reasonable / doable?

**Comment by thaJeztah** [comment]
Sounds reasonable for Machine yes; my main concern here was that this script if the "usual" way for people to install Docker, and shouldn't really install third-party packaged versions of Docker.
