### ISSUE TITLE
Dockercon Demo issue - No route to host, docker-compose + overlay

### ISSUE THREAD

**Issue by alexellis** [docker/docker#23451]
This is critical for my Dockercon demo and started failing yesterday. FYI I am running on ARM and Arch Linux, but this has not caused me any issues in the past.

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   b9f10c9
 Built:        Sun Jun  5 16:05:43 2016
 OS/Arch:      linux/arm

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   b9f10c9
 Built:        Sun Jun  5 16:05:43 2016
 OS/Arch:      linux/arm
```

**Output of `docker info`:**

```
$ docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 125
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 117
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.13-1-ARCH
Operating System: Arch Linux ARM
OSType: linux
Architecture: armv6l
CPUs: 1
Total Memory: 479.5 MiB
Name: envir1
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No cpuset support
Labels:
 sensor=1
Cluster store: consul://x:8500
Cluster advertise: x:2375
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Start Swam manager, agents etc
2. Set DOCKER_HOST variable to point at manager
3. Use docker-compose to 'up' the following: https://github.com/alexellis/datacenter-sensor/blob/master/docker-compose.yml

**Describe the results you received:**

sensor_1            | redis.exceptions.ConnectionError: Error 113 connecting to redis:6379. No route to host.

Even when I can see redis running and I start a redis-cli container on the same overlay network I can't get to the instance through IP or dns entries - no route to host. This was working yesterday before updating the system.

**Describe the results you expected:**

Working compose + overlay as yesterday.

Happy to provide more info.

**Comment by thaJeztah** [comment]
We've seen some issues with Arch in the past, because it's usually "bleeding edge", and updating sometimes breaks things. Did you compile docker yourself, or use a package from Arch? Are the daemon logs showing anything useful?

**Comment by thaJeztah** [comment]
ping @mavenugo perhaps you have some suggestions to help out?

**Comment by mavenugo** [comment]
@alexellis 

> This was working yesterday before updating the system.

What part of the system did you upgrade to ?

**Comment by alexellis** [comment]
@thaJeztah that was a big problem back with the move from 1.7 to 1.8 / 1.9 and I had to build Docker myself using 1.7 for every ARM unit I used. Now I'm relying on the package in Arch's package manager. 

@mavenugo  The kernel was updated on each device from 4.4.12 to 4.4.13-1.

```
$ uname -a
Linux envir2 4.4.13-1-ARCH #1 Wed Jun 8 19:31:34 MDT 2016 armv6l GNU/Linux
```

I tried pointing at the manager and then removing all networks possible - this didn't seem to help. I also ran through docker-compose down/up a number of times getting the same error.

Last thing I did was to rename the `frontend` network to `sensing` and it appeared to work at least for the first time I tried it including scaling up the sensor service to 2x.

Happy to go into the logs - do you mean the `systemctl status` output for `docker`?

**Comment by thaJeztah** [comment]
@alexellis are you able to get it working (for now), or need more immediate help?

**Comment by alexellis** [comment]
@thaJeztah I've just powered everything down and started from scratch. It worked for the 2nd time running.

I have about 6 more nodes to add on Mon / Tue and will report back on those. There is a fall-back option of starting the services through `ssh`on each Pi and linking via host IP. Hopefully I won't have to go there, it takes much longer too.

Thanks for coming in on this, I appreciate your suggestions.

**Comment by thaJeztah** [comment]
@alexellis good to hear; let me close this issue for now, but feel free to continue the discussions, email me (sebastiaan@docker) if needed. See you at DockerCon!
