### ISSUE TITLE
fix logrus formatting

### ISSUE THREAD

**Issue by runcom** [docker/docker#23459]
found some with
```
ag --ignore=vendor/ 'logrus\.(Errorf|Warnf|Debugf|Fatalf|Panicf|Infof)\("([^,)]*)"\)$'
```
fixup those and then do the same w/o the `f` at the end :)

**Comment by yongtang** [comment]
@runcom I added a pull request #23461 for this one. Please let me know if there are any issues.

**Comment by runcom** [comment]
@yongtang thanks, let's leave this open until we fix also the call w/o ti  formatting which instead use formatting

**Comment by yongtang** [comment]
Thanks @runcom. I create another pull request #23466 to address the issue where formatting string is present, but `logrus.[Error|Warn|Debug|Fatal|Panic|Info](` is used (without `f`). Please let me know if there are any issues.
