### ISSUE TITLE
ker images -q

### ISSUE THREAD

**Issue by rjrivero** [docker/docker#23463]
**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
Looks like you typed in the wrong window :wink:

**Comment by phemmer** [comment]
What's the story with all these lately? #23335 #23326 #23310 #22903 #22724 #22646 #22360 #22190 #22110 #21989 #21770 #21615
How is it that what looks like people trying to run CLI commands are creating issues on the tracker?

**Comment by thaJeztah** [comment]
@phemmer keyboard focus in the wrong window, and the `c` happens to be a keyboard shortcut for "create issue" on GitHub https://help.github.com/articles/using-keyboard-shortcuts/
