### ISSUE TITLE
Error when trying to run containers on aarch64

### ISSUE THREAD

**Issue by kobessas** [docker/docker#23467]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   96110f3
 Built:        Sun Jun 12 00:27:58 2016
 OS/Arch:      linux/arm64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   96110f3
 Built:        Sun Jun 12 00:27:58 2016
 OS/Arch:      linux/arm64
```

**Output of `docker info`:**

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 3
Server Version: 1.12.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 14
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 3.14.65-8-ARCH
Operating System: Arch Linux ARM
OSType: linux
Architecture: aarch64
CPUs: 4
Total Memory: 1.677 GiB
Name: alarm
ID: IM32:RQ4R:ZWPT:QO5K:477W:RPHA:L4WJ:7NMV:LACF:PWDT:CP4P:2VQF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Odroid C2
Linux alarm 3.14.65-8-ARCH #1 SMP PREEMPT Tue Jun 7 19:18:18 MDT 2016 aarch64 GNU/Linux

**Steps to reproduce the issue:**
1. Install latest docker from master
2. Run any image

**Describe the results you received:**
docker: Error response from daemon: shim error: open pid: no such file or directory.

**Describe the results you expected:**
Container should run normally.

**Additional information you deem important (e.g. issue happens only occasionally):**
[alarm@alarm ~]$ sudo systemctl status docker
* docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2016-06-12 00:40:48 CEST; 4min 24s ago
     Docs: https://docs.docker.com
 Main PID: 231 (dockerd)
   Memory: 56.7M
      CPU: 1.120s
   CGroup: /system.slice/docker.service
           |-231 /usr/bin/dockerd -H fd://
           `-248 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --shim docker-containerd-shim --runtime docker-runc --metrics-interval=0 --start-timeout 2m --s

Jun 12 00:40:48 alarm dockerd[231]: time="2016-06-12T00:40:48.165093000+02:00" level=info msg="Docker daemon" commit=96110f3 graphdriver=aufs version=1.12.0-dev
Jun 12 00:40:48 alarm dockerd[231]: time="2016-06-12T00:40:48.188657000+02:00" level=info msg="API listen on /var/run/docker.sock"
Jun 12 00:40:48 alarm systemd[1]: Started Docker Application Container Engine.
Jun 12 00:41:00 alarm dockerd[231]: time="2016-06-12T00:41:00.322839000+02:00" level=warning msg="Couldn't run auplink before unmount /var/lib/docker/tmp/docker-aufs-union947068142: exec: \"aup
Jun 12 00:41:23 alarm dockerd[231]: time="2016-06-12T00:41:23.348833000+02:00" level=warning msg="Couldn't run auplink before unmount /var/lib/docker/aufs/mnt/665a2fa7e18a9a94e1784131ecd714e37d
Jun 12 00:41:23 alarm dockerd[231]: time="2016-06-12T00:41:23.444099000+02:00" level=warning msg="Couldn't run auplink before unmount /var/lib/docker/aufs/mnt/665a2fa7e18a9a94e1784131ecd714e37d
Jun 12 00:41:25 alarm dockerd[231]: time="2016-06-12T00:41:25.91094+02:00" level=error msg="containerd: start container" error="shim error: open pid: no such file or directory" id=6db80e468cd9f
Jun 12 00:41:25 alarm dockerd[231]: time="2016-06-12T00:41:25.926734000+02:00" level=error msg="Create container failed with error: shim error: open pid: no such file or directory"
Jun 12 00:41:27 alarm dockerd[231]: time="2016-06-12T00:41:27.843745000+02:00" level=warning msg="Couldn't run auplink before unmount /var/lib/docker/aufs/mnt/665a2fa7e18a9a94e1784131ecd714e37d
Jun 12 00:41:27 alarm dockerd[231]: time="2016-06-12T00:41:27.896644000+02:00" level=error msg="Handler for POST /v1.24/containers/6db80e468cd9f5661fb5311987830be2e050415ea5394e0f33d83c67b35421
lines 1-21/21 (END)

**Comment by justincormack** [comment]
Hi I ran master on aarch64 on Friday with no issues, but I see you are
running aufs, which I did not try. Are you sure you have the aufs utilities
installed? In particular auplink.

**Comment by kobessas** [comment]
Using AUFS because it is the default. Not sure whether I am missing a package. Any tips on how I can check whether everything is installed?

In the meantime I tried **overlay** driver and it gives me the same error:
docker: Error response from daemon: shim error: open pid: no such file or directory.

**devicemapper** says:
docker: failed to register layer: devmapper: Error mounting '/dev/mapper/docker-179:1-789534-8e4908d9e24e156d33a3ac7cfac099738254fc56f7093c2e47478f8ec29b6077' on '/var/lib/docker/devicemapper/mnt/8e4908d9e24e156d33a3ac7cfac099738254fc56f7093c2e47478f8ec29b6077': invalid argument.

What are you using @justincormack ?

**Comment by justincormack** [comment]
@kobessas I tested using `vfs` as the machine I had didnt have much installed and I was using the static binaries. I should be able to test overlay at least with it, possibly aufs.

**Comment by justincormack** [comment]
Ok I tested overlay on this system (Centos 7) too and it is fine. It doesn't have drivers for aufs. I should be able to test devicemapper later.

Can you run this script https://raw.githubusercontent.com/docker/docker/master/contrib/check-config.sh and see what it says - maybe your kernel config is missing something that is required?

You are running arm64 images eg `docker run aarch64/ubuntu ls` ?

**Comment by userVK** [comment]
Although I am not using the mainline docker code, I have the same problem. I am using a forked [checkpoint-restore branch from Ross Boucher](https://github.com/boucher/docker/tree/docker-checkpoint-restore) which too is 1.12.0-dev and has the same "shim error: open pid: no such file or directory' error". @kobessas Any luck in figuring out the solution ?
One thing I should add is that I needed to create symbolic links
`ln -s /usr/sbin/containerd /usr/sbin/docker-containerd`
`ln -s /usr/sbin/containerd-shim /usr/sbin/docker-containerd-shim`
`ln -s /usr/bin/runc /usr/sbin/docker-runc`
otherwise, even the docker daemon was failing.

**Comment by justincormack** [comment]
Are you using a version of `containerd` built from the same source as docker? There were some protocol changes recently, so they need to match, we had a few people testing things reporting issues because of that.

**Comment by kobessas** [comment]
In regard to running the check-config.sh, only thye following are missing which all are in the optional features.
`- CONFIG_CGROUP_PIDS: missing`
`- CONFIG_EXT3_FS_XATTR: missing`
`- CONFIG_EXT3_FS_POSIX_ACL: missing`
`- CONFIG_EXT3_FS_SECURITY: missing`
`- "zfs":`
   ` - /dev/zfs: missing`
   ` - zfs command: missing`
   ` - zpool command: missing`

`Limits:`
`- /proc/sys/kernel/keys/root_maxkeys: 200`

I am indeed running aarch64 containers:
`$ docker run aarch64/ubuntu ls`
`Unable to find image 'aarch64/ubuntu:latest' locally`
`latest: Pulling from aarch64/ubuntu`
`1cbfb885630d: Pull complete `
`87d88f7a8097: Pull complete `
`4d8e217e9951: Pull complete `
`3269a97292d6: Pull complete `
`Digest: sha256:01f8762cc52f2f89141bbd9ecd7000f638d6758fa9c5f5dacff60b5ee8be1d94 `
`Status: Downloaded newer image for aarch64/ubuntu:latest `
`docker: Error response from daemon: shim error: open pid: no such file or directory.`

@userVK I also did somethign similar. I am using archlinux and installed docker using this as a template:
[PKGBUILD-Docker](https://github.com/archlinuxarm/PKGBUILDs/blob/master/community/docker/PKGBUILD)
It requires a few changes before it can be used with the master branch as docker has been split into docker and dockerd since 1.11.x

**Comment by kobessas** [comment]
Compiling latest runc from dev solves the previous issue.

Briefly, the latest dev is required for the following:

- Docker
- containerd
- runc
