### ISSUE TITLE
Inconsistent host mounting with docker beta 1.11.2-beta15 on OSX 10.11.5

### ISSUE THREAD

**Issue by johnt337** [docker/docker#23462]
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   56888bf
 Built:        Mon Jun  6 23:57:32 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 114
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 171
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.12-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 49.05 GiB
Name: moby
ID: E6RG:6DQ3:2KKM:CSIF:NGJ5:5LG7:YWJ7:BKJA:YC3N:NCZA:RXGB:73MV
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 16
 Goroutines: 40
 System Time: 2016-06-11T20:58:01.244040046Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: johnt337
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Using AWS environment for S3 related functions, testing on OSX deploying to AWS/CoreOS.
OSX 10.11.5, Docker Beta 1.11.1-beta14 or Docker Beta 1.11.2-beta15

**Steps to reproduce the issue:**
1. Pick a folder on your local disk, in my case /data
2. `docker run -it --rm -v /data:/data ubuntu ls -l /data`
3. `docker run -it --rm -v /Volumes/some_external_ssd/data ubuntu ls -l /data`

**Describe the results you received:**
Placing data on my internal/local disk I could not see its entire contents with -v /data:/data

**Describe the results you expected:**
To see my data regardless of location, or at least that it would see the local partion and not the remote one.

**Additional information you deem important (e.g. issue happens only occasionally):**
``` 
johnt $ docker run -it --rm -v /data/ngram:/data ubuntu ls -l /data                                                                                                                                                                                             total 0
johnt $ docker run -it --rm -v /Volumes/projim-data/Users/johnt/ngram:/data ubuntu ls -l /data                                                                                                                                                                  total 1
drwxr-xr-x 10 root root 340 Jun  7 17:40 sg201302
johnt $ docker run -it --rm -v /data/ngram:/data ubuntu ls -l /data                                                                                                                                                                                             total 0
johnt $ ls -lh /data/ngram /Volumes/projim-data/Users/johnt/ngram                                                                                                                                                                                               /Volumes/projim-data/Users/johnt/ngram:
total 0
drwxr-xr-x  10 johnt  staff   340B Jun  7 13:40 sg201302

/data/ngram:
total 0
drwxr-xr-x  10 johnt  staff   340B Jun  7 13:40 sg201302
johnt $ du -sh /data/ngram /Volumes/projim-data/Users/johnt/ngram                                                                                                                                                                                                  
 44G	/data/ngram
 44G	/Volumes/projim-data/Users/johnt/ngram
```

Do I need to configure what devices are exposed to the docker host? I know with virtualbox and vmware I have to share them explicitly.

**Comment by thaJeztah** [comment]
This is described in the beta documentation

The `/Volumes/` and `/Users` directories are directly accessible, other directories can be accesses by prefixing them with `/Mac` during the beta, but this may change in future; possibly there'll be a control panel/preference pane to specify which additional directories should be shared.


From the documentation; https://beta.docker.com/docs/mac/osxfs/#namespaces

> Much of the OS X file system that is accessible to the user is also available to containers using the -v bind mount syntax. You can share files in `/Users`, `/Volumes`, `/private`, and `/tmp` directly. For the Beta only, the rest of the user-accessible file system is mounted under `/Mac`. All other paths used in -v bind mounts are sourced from the Moby Linux VM running the Docker containers, so arguments such as `-v /var/run/docker.sock:/var/run/docker.sock` should work as expected.

**Comment by johnt337** [comment]
Worked like a charm!
Thanks again!!

**Comment by CWSpear** [comment]
Had this same question... what great timing! This helped me, too. Thanks @johnt337 for asking and @thaJeztah for the answer that helped =)

**Comment by johnt337** [comment]
@CWSpear glad I could help 👍
