### ISSUE TITLE
bash-completion fails syntax check

### ISSUE THREAD

**Issue by onlyjob** [docker/docker#23483]
~~~~
$ bash -n contrib/completion/bash/docker
contrib/completion/bash/docker: line 514: syntax error near unexpected token `('
contrib/completion/bash/docker: line 514: `             syslog-tls-@(ca-cert|cert|key))'
~~~~

~~~~
$ bash --version
GNU bash, version 4.3.42(1)-release (x86_64-pc-linux-gnu)
~~~~

FYI @albers.

**Comment by albers** [comment]
That's no surprise. The completion script ensures that `extglob` is set during execution. But as `bash -c` does not execute any commands, it sees the extended globs without `extglob` being set.
That explains why the script works when being sourced and used (completion works as expected) but not when being verified.

**Comment by onlyjob** [comment]
I'd recommend to fix it anyway because verification can reveal other problems.
At the moment validation stops when stumbles upon this problem so any further errors are ignored. Also IMHO with my patch readability of the code is better...

**Comment by phemmer** [comment]
If you want verification to work, just set the `extglob` option.

    bash -n -O extglob contrib/completion/bash/docker

**Comment by thaJeztah** [comment]
Following the discussion above, I don't think we need to change this, as verification is possible with the instructions @phemmer gave above, and readability is really subjective here. Given that @albers does most of the maintenance of these scripts, I prefer to keep it using the current notation.

**Comment by albers** [comment]
@onlyjob brought up an important point: verification of the completion scripts.
With @phemmer's enhancement, we should be able to include checks into the regular build process, something like this:

```bash
$ docker run --rm --volume $(pwd)/contrib/completion/bash/docker:/docker-completion ubuntu:14.04 bash -O extglob -n /docker-completion && echo OK
$ docker run --rm --volume $(pwd)/contrib/completion/bash/docker:/docker-completion albers/bash-completion-mac bash -O extglob -n /docker-completion && echo OK
```
This would ensure for two reference platforms the scripts are syntactically correct.

Even better, we could source the scripts, something like
```bash
$ docker run --rm --volume $(pwd)/contrib/completion/bash/docker:/docker-completion ubuntu:14.04 bash -c ". /docker-completion" && echo OK
$ docker run --rm --volume $(pwd)/contrib/completion/bash/docker:/docker-completion albers/bash-completion-mac bash -c ". /docker-completion" && echo OK
```

**Comment by thaJeztah** [comment]
@albers perhaps having an extra step for that in our CI would be good to have yes; want to open a separate issue for that?

**Comment by albers** [comment]
Yes, I'll do that.

**Comment by albers** [comment]
@thaJeztah created #23488

**Comment by onlyjob** [comment]
Actually this issue was spotted by Lintian during build of a Debian package where all installed shell scripts are checked automatically. Unfortunately it is not possible to set `-O extglob` so I suppose we'll have to carry that patch anyway. 
Besides extglob nested sub-patterns looks ugly to me so I would expand for readability...

**Comment by albers** [comment]
@onlyjob Well, i'm not really against your patch. I buy your point that nested extglobs are ugly.
I just didn't feel the need for a change because this is not a bug in the completion.

Your change gets rid of extglobs in two places. But extglobs are used all over the script in disguise of the `__docker_to_extglob()` function, see https://github.com/docker/docker/blob/master/contrib/completion/bash/docker#L599 for an example.

I feel uncomfortable to remove extglobs in selected occurrences just because of a limitation in some tool (Lintian). I do not want to get rid of extglobs in general.

But I'm perfectly OK if we re-open and accept the PR **in this particular case**, where extglobs do not add value except for conciseness.
@thaJeztah, @phemmer WDYT?

**Comment by phemmer** [comment]
I can somewhat agree with the nested extglobs being ugly bit. They don't really bother me, but I can see the argument, and think flattening them to a single level would be reasonable.

> I feel uncomfortable to remove extglobs in selected occurrences just because of a limitation in some tool 

Ditto.

However given how small the change would be to get lintian to be quiet, I don't think it's too terrible a price.

**Comment by thaJeztah** [comment]
@albers alright, I'm okay with accepting that patch, I'll reopen
