### ISSUE TITLE
Allow `--entrypoint` to be set to `null` in a `docker run` or `docker create`

### ISSUE THREAD

**Issue by programmerq** [docker/docker#23498]
I would like to be able to "unset" an ENTRYPOINT at the command line when creating a container.

Using this Dockerfile and entrypoint.sh as an example:

Dockerfile:

    FROM alpine
    ADD entrypoint.sh /entrypoint.sh
    RUN chmod 755 /entrypoint.sh
    ENTRYPOINT ["/entrypoint.sh"]
    CMD echo foobar

entrypoint:

    #!/bin/sh
    echo "I am an entrypoint"
    exec "$@"

If I wanted to unset the entrypoint, I would like to be able to run this: `docker run --entrypoint='' --rm -it image echo foo`

I would expect this to produce the following output:

    foo

but it does the following instead:

    I am an entrypoint
    foo

Providing some way for `docker run` or `docker create` to force the ENTRYPOINT to be null without having to create another image would be great.

**Comment by mountkin** [comment]
Try this
`docker run --entrypoint=/bin/echo --rm image foo`

**Comment by programmerq** [comment]
I'm aware that this and other workarounds exist, but that doesn't mean that
this issue couldn't or shouldn't be addressed.

**Comment by yongtang** [comment]
@programmerq I created a pull request #23718 to address this issue. If `--entrypoint=` (with empty string `""`) is passed then `docker run` or `docker create` will unset the entrypoint and rely on the default behavior.

Please let me know if there are any issues.

**Comment by marcodelapierre** [comment]
As regards the entrypoint... should we just ensure that it's unset, and then do everything through the `run` argument? At this point :
```
$ podman run -it --rm --entrypoint '' --env-file /home/ubuntu/singularity-hpc/modules/python/3.9.2-slim/99-shpc.sh -v /data docker.io/library/python:3.9.2-slim echo ciao
ciao
```

The main drawback is that there's no choice over which shell is used

Will keep looking for other ways

**Comment by thaJeztah** [comment]
most images only have a CMD set, no separate ENTRYPOINT, so you won't have to override it, but you can `docker inspect` the image to know what it has configured;

```bash
docker inspect --format '{{json .Config}}' docker.io/library/python:3.9.2-slim | jq .
{
  "Hostname": "",
  "Domainname": "",
  "User": "",
  "AttachStdin": false,
  "AttachStdout": false,
  "AttachStderr": false,
  "Tty": false,
  "OpenStdin": false,
  "StdinOnce": false,
  "Env": [
    "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
    "LANG=C.UTF-8",
    "GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568",
    "PYTHON_VERSION=3.9.2",
    "PYTHON_PIP_VERSION=21.0.1",
    "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/b60e2320d9e8d02348525bd74e871e466afdf77c/get-pip.py",
    "PYTHON_GET_PIP_SHA256=c3b81e5d06371e135fb3156dc7d8fd6270735088428c4a9a5ec1f342e2024565"
  ],
  "Cmd": [
    "python3"
  ],
  "Image": "sha256:09147162b3f325a1bdc0df946f3ac8ed04e7690c7d17a754f88fc640cd1a23d4",
  "Volumes": null,
  "WorkingDir": "",
  "Entrypoint": null,
  "OnBuild": null,
  "Labels": null
}
```
