### ISSUE TITLE
add security (seccomp, apparmor, etc.) info to `docker info`

### ISSUE THREAD

**Issue by vikstrous** [docker/docker#23500]
`docker info` should return the status of seccomp, apparmor or any other information necessary to understand which security features are enabled.

**Comment by HackToday** [comment]
Hi @vikstrous  how do you want to display those ? and those security seems not same layer, just put them in same group seems confusing. 

Also do we have any API to get such info from docker inside to make them expose from `docker info`?

**Comment by vikstrous** [comment]
Ah, I just found out that `SecurityOptions`  was added to engine-api and followed the links to get to https://github.com/docker/docker/pull/21172 . Looks like this is already done.

**Comment by justincormack** [comment]
@vikstrous the only thing I noticed a couple of days ago is that this is only in the remote API and not in the output of `docker info`, but didn't have time to get a patch into 1.12 before the freeze. So I am going to reopen this...

**Comment by justincormack** [comment]
@yongtang thanks!
