### ISSUE TITLE
Support multiple "lower" directories on overlayfs

### ISSUE THREAD

**Issue by wrouesnel** [docker/docker#23502]
Since kernel 4.0, multiple "lower" directories are supported on overlayfs, bringing the feature set much more inline with what `aufs` used to provide.

Docker should support this with it's overlayfs driver, or as a separate driver which works more like the `aufs` driver does, which would help resolve issues with exhausting hardlink and inode limits on filesystems like ext4.

```
Multiple lower layers
---------------------

Multiple lower layers can now be given using the the colon (":") as a
separator character between the directory names.  For example:

  mount -t overlay overlay -olowerdir=/lower1:/lower2:/lower3 /merged

As the example shows, "upperdir=" and "workdir=" may be omitted.  In
that case the overlay will be read-only.

The specified lower directories will be stacked beginning from the
rightmost one and going left.  In the above example lower1 will be the
top, lower2 the middle and lower3 the bottom layer.
```
https://www.kernel.org/doc/Documentation/filesystems/overlayfs.txt

**Comment by AkihiroSuda** [comment]
Perhaps this?  https://github.com/docker/docker/pull/22126

**Comment by wrouesnel** [comment]
Issue resolved!
