### ISSUE TITLE
allow seccomp / privileged option during build

### ISSUE THREAD

**Issue by Fedcomp** [docker/docker#23507]
It would be nice to allow to build image with disabled/changed `seccomp` profile, or at least allow activate `privileged` during build.
For example it would allow to build dedicated server images with steamcmd, which is not working with default seccomp rules (steamcmd is based on wine)

**Comment by justincormack** [comment]
All the steam issues should have been fixed in 1.11.2, what issues are you
having with builds?

**Comment by Fedcomp** [comment]
Oh i'm sorry, i watched for this issue but i missed the update. Sorry, seems to build well now.
