### ISSUE TITLE
Flaky test: TestHealth (timeouts)

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#23519]
This test is taking a long time to complete, but also seems to timeout in some cases. Opening this issue to keep track.

/cc @talex5 

https://jenkins.dockerproject.org/job/Docker%20Master/label=ubuntu%20&&%20btrfs/5714/console

```
3:11:48 --- FAIL: Test (6030.70s)
13:11:48 panic: DockerSuite.TestHealth test timed out after 1h30m0s [recovered]
13:11:48 	panic: DockerSuite.TestHealth test timed out after 1h30m0s
```

**Comment by talex5** [comment]
The per-test timeout should be much shorter than this (about 5 min). Is it possible this is the timeout for all the tests together, and it just happened to be in the middle of the health checks at the time? (clutching at staws maybe...)

**Comment by dnephin** [comment]
Looking at test failures for the last day, there are a lot of different tests that hit this 90min timeout, so I think you're right, it's not related to this specific test.

**Comment by dnephin** [comment]
Replacing this issue with #25028
