### ISSUE TITLE
Run Axiom docker and get `personality change failure 1` message

### ISSUE THREAD

**Issue by nixlehrer** [docker/docker#23514]
**Output of `docker version`:**

```
➜  ~ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 6
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 73
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.4.12-boot2docker
Operating System: Boot2Docker 1.11.2 (TCL 7.1); HEAD : a6645c3 - Wed Jun  1 22:59:51 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: default
ID: FM6L:YMTL:54TP:IIZG:TCEV:DTUR:BU5J:J3VU:KTQG:JLZ5:W3OJ:RWV3
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 23
 Goroutines: 52
 System Time: 2016-06-14T12:24:58.699753684Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
> uname -a
Darwin xxx.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64
```
I use Axiom on docker. I installed the image by `docker pull daly/axiom`. But I cannot run it properly.

**Steps to reproduce the issue:**
1. Install docker-toolbox.
2. run `docker pull daly/axiom`
3. run `docker run -i -t daly/axiom axiom`

**Describe the results you received:**
I get `personality change failure 1`.

**Describe the results you expected:**
By the introduction [here](http://www.axiom-developer.org/axiom-website/download.html), I would have Axiom running. But I get the message above.

**Additional information you deem important (e.g. issue happens only occasionally):**
I have contacted the developer of Axiom, they reply me the message is not coming from Axiom. It is probably because of some incompatibility between docker and OSX.

**Comment by thaJeztah** [comment]
The `personality` syscall is blocked by default, see: https://docs.docker.com/engine/security/seccomp/#significant-syscalls-blocked-by-the-default-profile

You can either create a custom seccomp profile, or disable all seccomp filtering using `--security-opt seccomp=unconfined`. But a custom profile would be better so that you keep the protection for other sys calls that are potentially dangerous

**Comment by nixlehrer** [comment]
@thaJeztah Thank you for your help! I tried `docker run --rm -it --security-opt seccomp=unconfined -i -t daly/axiom axiom` and it started!

**Comment by justincormack** [comment]
Well, most uses of `personality` are blocked, the only allowed ones are to change between 32 and 64 bit mode and to read the mode. The other options are somewhat problematic from the security point of view, so we prefer to disable by default.

**Comment by bryan-lunt** [comment]
I desperately need to be able to disable ASLR in docker containers for supercomputing. (Automatic migration for load balancing, etc.)
