### ISSUE TITLE
Cannot get the WindowsServerCore image when running Install-ContainerHost.ps1

### ISSUE THREAD

**Issue by olafleur** [docker/docker#23529]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   2b97201
 Built:        Tue Apr 26 23:51:36 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   2b97201
 Built:        Tue Apr 26 23:51:36 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null
Kernel Version: 10.0 14300 (14300.1000.amd64fre.rs1_release_svc.160324-1723)
Operating System: Windows Server 2016 Standard Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 1.524 GiB
Name: WIN-JIT6DOCS89Q
ID: FLJW:WKG6:IZFM:SHLY:NYPV:BUG3:MIWD:XIFR:2AD4:MD77:T3DM:THDE
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Hyper-V running a VM with Windows Server 2016 TP5 (downloaded here : https://www.microsoft.com/en-us/evalcenter/evaluate-windows-server-technical-preview)

**Steps to reproduce the issue:**
1. Create the VM in Hyper-V
2. Install Windows Server 2016 TP5
3. wget -uri https://aka.ms/tp5/Install-ContainerHost -OutFile C:\Install-ContainerHost.ps1
4. powershell.exe -NoProfile C:\Install-ContainerHost.ps1

**Describe the results you received:**
Getting Container OS image (WindowsServerCore -MinimumVersion 10.0.14300.1000 -MaximumVersion 10.0.14300.1010) from OneGet (this may take a few minutes)...
WARNING: Save-HTTPItem: Bits Transfer failed. Job State: BG_JOB_STATE_ERROR ExitCode = 0
WARNING: Based on customer feedback, we are updating the Containers PowerShell module to better align with Docker. As
part of that some cmdlet and parameter names may change in future releases. To learn more about these changes as well
as to join in the design process or provide usage feedback please refer to http://aka.ms/windowscontainers/powershell

C:\Install-ContainerHost.ps1 : The system cannot find the file specified.
At line:1 char:1
+ C:\Install-ContainerHost.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Install-ContainerHost.ps1

**Describe the results you expected:**
I expected the script to complete normally, as the script file is at this location. When running with the SkipImageImport flag, it completes.

**Additional information you deem important (e.g. issue happens only occasionally):**
When running the command `Install-ContainerImage -Name NanoServer` it downloads it properly.

**Comment by icecrime** [comment]
Cc @friism.

**Comment by BretFisher** [comment]
Same issue in multiple fresh TP5 installs. Even using `save-containerimage -name windowsservercore -path c:\` gives the same `WARNING: Save-HTTPItem: Bits Transfer failed. Job State: BG_JOB_STATE_ERROR ExitCode = 0`

**Comment by olafleur** [comment]
Is there at least à workaround? For exemple, can I download the image another way?

**Comment by olafleur** [comment]
For the moment, I downloaded the WIM file here : https://az887518.vo.msecnd.net/pshctcontainer/WindowsServerCore-10-0-14300-1000.wim and ran the script with the WimPath parameter.

**Comment by ekbduffy** [comment]
Guys! I've found the solution. https://github.com/OneGet/NanoServerPackage  - here manual said that it's not supported in PSDirect. So you must use "Enter-PSSession -Computername ..." instead of "Enter-PSSession -VMName ..."

**Comment by friism** [comment]
@thaJeztah I recommend closing this issue - the install instructions have changed and now base layers are fetched using normal Docker tools: https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_server#3-install-base-container-images

**Comment by thaJeztah** [comment]
thanks for the update @friism, I'll go ahead and close
