### ISSUE TITLE
Should sanitize docker labels/env when using as journald field names 

### ISSUE THREAD

**Issue by guoshimin** [docker/docker#23528]
**Output of `docker version`:**

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   4419fdb-dirty
 Built:        Fri Dec 18 00:01:03 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   4419fdb-dirty
 Built:        Fri Dec 18 00:01:03 UTC 2015
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 26
Images: 75
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: journald
Kernel Version: 4.3.3-coreos
Operating System: CoreOS 899.1.0
CPUs: 16
Total Memory: 62.91 GiB
Name: ip-10-20-9-13.us-west-2.compute.internal
ID: ZXQE:OKTS:EA6K:2F27:CYMJ:3GQJ:2V3B:CQMG:KIJG:5VW2:P6O3:4QLY
```

**Additional environment details (AWS, VirtualBox, physical, etc.):** AWS

**Steps to reproduce the issue:**
1. Start docker daemon

  ```
docker daemon --log-driver=journald --log-opt labels=io.kubernetes.pod.name
  ```

2. Launch a container that has label `io.kubernetes.pod.name`. For example

  ```
docker run -l io.kubernetes.pod.name=foo -d ubuntu bash -c "while true; do echo 'Hello World'; sleep 5; done"
  ```

**Describe the results you received:**
`io.kubernetes.pod.name=foo` passed to journald for the logs of this container, with the label name changed to `IO_KUBERNETES_POD_NAME` due to the requirements on the field names imposed by journald

**Describe the results you expected:**
Getting `journal error: variable name contains invalid character, ignoring` in the docker daemon log.

**Additional information you deem important (e.g. issue happens only occasionally):**
Seems related to this line: https://github.com/docker/docker/blob/11a24f19c2da88b6c3b50114863f24c06c5ce2fd/daemon/logger/journald/journald.go#L56

The `keyMod` function should change all letters to upper case, any non-alphanumeric character to underscores, and remove any leading underscores.

I couldn't find any definitive documentation on journald field name requirements, but found this: https://github.com/coreos/go-systemd/blob/master/journal/journal.go#L68

**Comment by yongtang** [comment]
@guoshimin I created a pull request #23725 to address the journald field names issue. Please let me know if there are any issues.
