### ISSUE TITLE
Operations on images/storage seem to lock the daemon and prevent it from responding

### ISSUE THREAD

**Issue by thomas-maurice** [docker/docker#23521]
**Output of `docker version`:**

```
root@machine:~# docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:11:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:11:07 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
root@machine:~# docker info
Containers: 12
 Running: 4
 Paused: 0
 Stopped: 8
Images: 11
Server Version: 1.11.1
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: syslog
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.3.0-0.bpo.1-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 6.654 GiB
Name: machine
ID: BUMZ:VA5K:CD32:RFWF:PIIT:RR65:JAHX:HT6M:PQDW:2YJ6:CNYD:X44B
Docker Root Dir: /home/docker/755360.755360
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: No kernel memory limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):** Openstack VMs & Bare metal servers

**Steps to reproduce the issue:**
1. Find a host containing a high number of Docker images
2. Run `docker rmi $(docker images -q)`
3. Try to either run `docker ps` or `docker images` during the `rmi` command is running

**Describe the results you received:**
I recieved *very high* responsed time from the daemon. For instance: 
```
root@machine:~# time docker ps
CONTAINER ID        IMAGE                                     COMMAND                  CREATED             STATUS              PORTS                     NAMES
[ .. some containers, the usual output ...]

real	0m6.773s
user	0m0.016s
sys	0m0.008s
```

It goes even longer for `docker images` up to several minutes. I also notice that the delay, altough it is very long most of the time, is also completely random and I cannot reproduce hangs that last the same time. The only observeable behavior I have being that when a host is not performing operations on images, the above commands return instantly, and when it is playing with images the commands may take several minutes to complete.

**Additional information you deem important (e.g. issue happens only occasionally):**
It happens randomly from a system PoV, meaning that the machines are not noticeably loaded.

**Comment by runcom** [comment]
can this possibly be tied to https://github.com/docker/docker/pull/22918 which is fixed in 1.11.2? ping @thaJeztah

**Comment by thaJeztah** [comment]
Could well be; @thomas-maurice are you able to test if this is still reproducible on the current release (1.11.2?)

**Comment by thomas-maurice** [comment]
Of course ! I'll do that and post an update as soon as I have relevant results.

**Comment by thomas-maurice** [comment]
Yo !

After further testing I observe the following:
```
root@machine # time docker rmi $(docker images -aq)

... Some things ...

real	0m2.436s
user	0m0.016s
sys	0m0.004s
```

As well as
```
root@machine # docker images

... Some images ...

real	0m2.917s
user	0m0.032s
sys	0m0.008s
```

So the issue *seems* to be fixed

I will see on a more longer term how it goes in production

**Comment by thaJeztah** [comment]
Thanks! That's good news!

Let me close this issue for now, but ping me if you still encounter this
