### ISSUE TITLE
Query: why doesn't restarting a container not update linked containers' env vars

### ISSUE THREAD

**Issue by sbose78** [docker/docker#23536]
Hi,
I have a query:

"Unlike host entries in the /etc/hosts file, IP addresses stored in the environment variables are not 
automatically updated if the source container is restarted."

https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/

Any reason why this isn't being automatically updated? Is there a design constraint?

Thanks,
Shoubhik

**Comment by cpuguy83** [comment]
Env vars can only be changed from within the executing process.
For example:
```bashtext
$ export FOO=foo
$ someCommand &
$ export FOO=bar
```

When `someCommand` is started, bash will copy the environment details to the new process for `someCommand`, however when executing `export FOO=bar` the `someCommand` process will not get the updated var.

Env vars are only really suitable for dynamic configuration options.
