### ISSUE TITLE
What is the equivalent of /var/run/docker.sock in Windows container? 

### ISSUE THREAD

**Issue by xied75** [docker/docker#23541]
http://stackoverflow.com/questions/27879713/is-it-ok-to-run-docker-from-inside-docker

So the best practice is to map the sock, but how do we do that in the Windows Server 2016 TP5?

Best,

**Comment by friism** [comment]
@xied75 there's currently no way to do that that I know up. On Windows, the Docker engine is on a named pipe: ` //./pipe/docker_engine`. But it cannot be mounted with `-v`.

**Comment by thaJeztah** [comment]
I'll close this issue, because I think this is answered, but feel free to continue the discussion

**Comment by xied75** [comment]
@friism Thanks for the answer. Is there plan to work around this?
