### ISSUE TITLE
docker: Error response from daemon: Container command '<command>' not found or does not exist.. ALWAYS

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [docker/docker#23571]
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 6
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.4.0-25-lowlatency
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.516 GiB
Name: labs-064
ID: AUXF:FOAH:TAZH:KOJF:CABW:MC4F:UCNT:GZCA:IUSN:5BFF:UHW2:ZD6E
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 11
 Goroutines: 31
 System Time: 2016-06-15T16:05:43.202890723+02:00
 EventsListeners: 0
Username: leandrolucarellasociomantic
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical machine.

**Steps to reproduce the issue:**
1. `docker pull hello-world`
2. `docker run hello-world`

**Describe the results you received:**

For `docker pull hello-world`:
```
Using default tag: latest
latest: Pulling from library/hello-world
a9d36faac0fe: Pull complete 
Digest: sha256:e52be8ffeeb1f374f440893189cd32f44cb166650e7ab185fa7735b7dc48d619
Status: Downloaded newer image for hello-world:latest
```
OK

For `docker run hello-world`:
`docker: Error response from daemon: Container command '/hello' not found or does not exist..`

**Describe the results you expected:**

Same for `docker pull hello-world`, for `docker run hello-world`:
```

Hello from Docker.
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker Hub account:
 https://hub.docker.com

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/

```

**Additional information you deem important (e.g. issue happens only occasionally):**

I know this looks like a duplicate, but I couldn't find any issues where this happens with every run and every image/container, this is why I'm opening a new issue (I hope that's fine).

I have a very similar setup in a server and is working fine, because of this I suspect this must be some environment issue, but I'm out of ideas about how to debug this. I'm trying with the same kernel (4.2.0), linux-image-extra and docker-engine package and it works in the server, but it fails in my workstation.

I'm using Ubuntu trusty (as stated in `docker info`), I've tried with the kernels from wily and xenial too. In total I tried with kernels 3.13.0, 4.2.0 and 4.4.0 (both generic and lowlatency flavours).

Some more info about my system:
```
$ cat /etc/apt/sources.list.d/docker.list
deb https://apt.dockerproject.org/repo ubuntu-trusty main
$ which docker
/usr/bin/docker
$ dpkg -S /usr/bin/docker
docker-engine: /usr/bin/docker
$ debsums -c docker-engine && echo OK
OK
```

Debug mode:
```
$ docker -D run hello-world
DEBU[0000] Corrupted prefix: []                         
DEBU[0000] [hijack] End of stdout                       
docker: Error response from daemon: Container command '/hello' not found or does not exist..
```

Output for the server running in debug mode:
```
time="2016-06-15T16:20:37.813025132+02:00" level=debug msg="Calling POST /v1.23/containers/create" 
time="2016-06-15T16:20:37.813280882+02:00" level=debug msg="form data: {\"AttachStderr\":true,\"AttachStdin\":false,\"AttachStdout\":true,\"Cmd\":null,\"Domainname\":\"\",\"Entrypoint\":null,\"Env\":[],\"HostConfig\":{\"AutoRemove\":false,\"Binds\":null,\"BlkioBps\":0,\"BlkioDeviceReadBps\":null,\"BlkioDeviceReadIOps\":null,\"BlkioDeviceWriteBps\":null,\"BlkioDeviceWriteIOps\":null,\"BlkioIOps\":0,\"BlkioWeight\":0,\"BlkioWeightDevice\":null,\"CapAdd\":null,\"CapDrop\":null,\"Cgroup\":\"\",\"CgroupParent\":\"\",\"ConsoleSize\":[0,0],\"ContainerIDFile\":\"\",\"CpuCount\":0,\"CpuPercent\":0,\"CpuPeriod\":0,\"CpuQuota\":0,\"CpuShares\":0,\"CpusetCpus\":\"\",\"CpusetMems\":\"\",\"Devices\":[],\"DiskQuota\":0,\"Dns\":[],\"DnsOptions\":[],\"DnsSearch\":[],\"ExtraHosts\":null,\"GroupAdd\":null,\"IpcMode\":\"\",\"Isolation\":\"\",\"KernelMemory\":0,\"Links\":null,\"LogConfig\":{\"Config\":{},\"Type\":\"\"},\"Memory\":0,\"MemoryReservation\":0,\"MemorySwap\":0,\"MemorySwappiness\":-1,\"NetworkMode\":\"default\",\"OomKillDisable\":false,\"OomScoreAdj\":0,\"PidMode\":\"\",\"PidsLimit\":0,\"PortBindings\":{},\"Privileged\":false,\"PublishAllPorts\":false,\"ReadonlyRootfs\":false,\"RestartPolicy\":{\"MaximumRetryCount\":0,\"Name\":\"no\"},\"SandboxSize\":0,\"SecurityOpt\":null,\"ShmSize\":0,\"StorageOpt\":null,\"UTSMode\":\"\",\"Ulimits\":null,\"UsernsMode\":\"\",\"VolumeDriver\":\"\",\"VolumesFrom\":null},\"Hostname\":\"\",\"Image\":\"hello-world\",\"Labels\":{},\"NetworkingConfig\":{\"EndpointsConfig\":{}},\"OnBuild\":null,\"OpenStdin\":false,\"StdinOnce\":false,\"Tty\":false,\"User\":\"\",\"Volumes\":{},\"WorkingDir\":\"\"}" 
time="2016-06-15T16:20:37.827207229+02:00" level=debug msg="container mounted via layerStore: /var/lib/docker/aufs/mnt/13f60f63cfc44e7ca150a198b91f7685108fefecbe567b410993f7519a918f4b" 
time="2016-06-15T16:20:37.842396562+02:00" level=debug msg="Calling POST /v1.23/containers/2a0dff9fd0d1b27998f6a4d90267307ec28ab2d27a1c26504601a12bfe329e4f/attach?stderr=1&stdout=1&stream=1" 
time="2016-06-15T16:20:37.842545293+02:00" level=debug msg="attach: stdout: begin" 
time="2016-06-15T16:20:37.842641049+02:00" level=debug msg="attach: stderr: begin" 
time="2016-06-15T16:20:37.842972015+02:00" level=debug msg="Calling POST /v1.23/containers/2a0dff9fd0d1b27998f6a4d90267307ec28ab2d27a1c26504601a12bfe329e4f/start" 
time="2016-06-15T16:20:37.843695397+02:00" level=debug msg="container mounted via layerStore: /var/lib/docker/aufs/mnt/13f60f63cfc44e7ca150a198b91f7685108fefecbe567b410993f7519a918f4b" 
time="2016-06-15T16:20:37.843822449+02:00" level=debug msg="Assigning addresses for endpoint serene_cori's interface on network bridge" 
time="2016-06-15T16:20:37.843849703+02:00" level=debug msg="RequestAddress(LocalDefault/172.17.0.0/16, <nil>, map[])" 
time="2016-06-15T16:20:37.847324182+02:00" level=debug msg="Assigning addresses for endpoint serene_cori's interface on network bridge" 
time="2016-06-15T16:20:37.852984685+02:00" level=info msg="No non-localhost DNS nameservers are left in resolv.conf. Using default external servers : [nameserver 8.8.8.8 nameserver 8.8.4.4]" 
time="2016-06-15T16:20:37.853015681+02:00" level=info msg="IPv6 enabled; Adding default IPv6 external servers : [nameserver 2001:4860:4860::8888 nameserver 2001:4860:4860::8844]" 
time="2016-06-15T16:20:37.858754527+02:00" level=debug msg="Programming external connectivity on endpoint serene_cori (ab15f00dceb8c119c419bf6b15831c51c7ddd5000f1105c70f1b8b651fcfb151)" 
time="2016-06-15T16:20:37.913721021+02:00" level=debug msg="sandbox set key processing took 16.679925ms for container 2a0dff9fd0d1b27998f6a4d90267307ec28ab2d27a1c26504601a12bfe329e4f" 
ERRO[1254] containerd: start container                   error=oci runtime error: could not synchronise with container process: no such file or directory id=2a0dff9fd0d1b27998f6a4d90267307ec28ab2d27a1c26504601a12bfe329e4f
time="2016-06-15T16:20:37.945491775+02:00" level=debug msg="attach: stdout: end" 
time="2016-06-15T16:20:37.945671399+02:00" level=debug msg="attach: stderr: end" 
time="2016-06-15T16:20:37.945895913+02:00" level=debug msg="Revoking external connectivity on endpoint serene_cori (ab15f00dceb8c119c419bf6b15831c51c7ddd5000f1105c70f1b8b651fcfb151)" 
time="2016-06-15T16:20:37.985379769+02:00" level=debug msg="Releasing addresses for endpoint serene_cori's interface on network bridge" 
time="2016-06-15T16:20:37.985440881+02:00" level=debug msg="ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.2)" 
time="2016-06-15T16:20:38.008633099+02:00" level=error msg="Handler for POST /v1.23/containers/2a0dff9fd0d1b27998f6a4d90267307ec28ab2d27a1c26504601a12bfe329e4f/start returned error: Container command '/hello' not found or does not exist." 
```

Files in `/var/lib/docker`:
```
# find /var/lib/docker -name \*2a0dff9fd0d1b27998f6a4d90267307ec28ab2d27a1c26504601a12bfe329e4f\* | xargs ls -l
/var/lib/docker/containers/2a0dff9fd0d1b27998f6a4d90267307ec28ab2d27a1c26504601a12bfe329e4f:
total 28
-rw-r--r-- 1 root root 2290 Jun 15 16:20 config.v2.json
-rw-r--r-- 1 root root 1053 Jun 15 16:20 hostconfig.json
-rw-r--r-- 1 root root   13 Jun 15 16:20 hostname
-rw-r--r-- 1 root root  174 Jun 15 16:20 hosts
-rw-r--r-- 1 root root  213 Jun 15 16:20 resolv.conf
-rw------- 1 root root   71 Jun 15 16:20 resolv.conf.hash
drwx------ 2 root root 4096 Jun 15 16:20 shm

/var/lib/docker/image/aufs/layerdb/mounts/2a0dff9fd0d1b27998f6a4d90267307ec28ab2d27a1c26504601a12bfe329e4f:
total 12
-rw-r--r-- 1 root root 69 Jun 15 16:20 init-id
-rw-r--r-- 1 root root 64 Jun 15 16:20 mount-id
-rw-r--r-- 1 root root 71 Jun 15 16:20 parent
```

I tried reinstalling the package, by completely removing `/var/lib/docker` and same results.

I also tried with plenty of other images, and running custom commands (like in an `ubuntu` image running `docker run ubuntu /bin/sh` or `ls` or `ps`, etc. Always the same results, `docker: Error response from daemon: Container command '<command>' not found or does not exist..` (where `<command>` is the command I used.

Evidently the error message is wrong, because I'm pretty sure the `/hello` command is there in the container (or at least the originating image). (and a very minor detail, there is an extra final dot in the error message :).

I would appreciate at least some help on moving forward with ways to continue debugging this, because I can't get my installation to work and I'm out of ideas on how to get a better error message that tells me what is really actually failing...

**Comment by justincormack** [comment]
That is pretty odd. Can you try `docker run --privileged hello-world` to see if something else is stopping it? The "Corrupted prefix" is nothing abnormal.

**Comment by justincormack** [comment]
Also can you run https://raw.githubusercontent.com/docker/docker/master/contrib/check-config.sh and see if anything odd comes up, like a missing kernel module?

**Comment by leandro-lucarella-sociomantic** [comment]
> That is pretty odd. Can you try docker run --privileged hello-world to see if something else is stopping it?

Works!

**Comment by leandro-lucarella-sociomantic** [comment]
```
$ bash tmp/docker-check-config.sh
warning: /proc/config.gz does not exist, searching other paths for kernel config ...
info: reading kernel config from /boot/config-4.4.0-25-lowlatency ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- apparmor: enabled and tools installed
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MEMCG: enabled
- CONFIG_KEYS: enabled
- CONFIG_MACVLAN: enabled (as module)
- CONFIG_VETH: enabled (as module)
- CONFIG_BRIDGE: enabled (as module)
- CONFIG_BRIDGE_NETFILTER: enabled (as module)
- CONFIG_NF_NAT_IPV4: enabled (as module)
- CONFIG_IP_NF_FILTER: enabled (as module)
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
- CONFIG_NF_NAT: enabled (as module)
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_USER_NS: enabled
- CONFIG_SECCOMP: enabled
- CONFIG_CGROUP_PIDS: enabled
- CONFIG_MEMCG_SWAP: enabled
- CONFIG_MEMCG_SWAP_ENABLED: missing
    (note that cgroup swap accounting is not enabled in your kernel config, you can enable it by setting boot option "swapaccount=1")
- CONFIG_MEMCG_KMEM: enabled
- CONFIG_BLK_CGROUP: enabled
- CONFIG_BLK_DEV_THROTTLING: enabled
- CONFIG_IOSCHED_CFQ: enabled
- CONFIG_CFQ_GROUP_IOSCHED: enabled
- CONFIG_CGROUP_PERF: enabled
- CONFIG_CGROUP_HUGETLB: enabled
- CONFIG_NET_CLS_CGROUP: enabled (as module)
- CONFIG_CGROUP_NET_PRIO: enabled
- CONFIG_CFS_BANDWIDTH: enabled
- CONFIG_FAIR_GROUP_SCHED: enabled
- CONFIG_RT_GROUP_SCHED: missing
- CONFIG_EXT3_FS: missing
- CONFIG_EXT3_FS_XATTR: missing
- CONFIG_EXT3_FS_POSIX_ACL: missing
- CONFIG_EXT3_FS_SECURITY: missing
    (enable these ext3 configs if you are using ext3 as backing filesystem)
- CONFIG_EXT4_FS: enabled
- CONFIG_EXT4_FS_POSIX_ACL: enabled
- CONFIG_EXT4_FS_SECURITY: enabled
- Network Drivers:
  - "overlay":
    - CONFIG_VXLAN: enabled (as module)
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: enabled (as module)
  - "btrfs":
    - CONFIG_BTRFS_FS: enabled (as module)
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: enabled
    - CONFIG_DM_THIN_PROVISIONING: enabled (as module)
  - "overlay":
    - CONFIG_OVERLAY_FS: enabled (as module)
  - "zfs":
    - /dev/zfs: missing
    - zfs command: missing
    - zpool command: missing

Limits:
- /proc/sys/kernel/keys/root_maxkeys: 1000000
```

**Comment by leandro-lucarella-sociomantic** [comment]
For more readability, this is what was shown in **red**:
```
warning: /proc/config.gz does not exist, searching other paths for kernel config ...
- CONFIG_MEMCG_SWAP_ENABLED: missing
- CONFIG_RT_GROUP_SCHED: missing
- CONFIG_EXT3_FS: missing
- CONFIG_EXT3_FS_XATTR: missing
- CONFIG_EXT3_FS_POSIX_ACL: missing
- CONFIG_EXT3_FS_SECURITY: missing
  - "zfs":
    - /dev/zfs: missing
    - zfs command: missing
    - zpool command: missing
```

**Comment by leandro-lucarella-sociomantic** [comment]
(BTW, I'm using ext4)

**Comment by justincormack** [comment]
Ok, none of those things are vital in the kernel config. So `--privileged` works, ok can you try:

 ```
docker run --security-opt seccomp=unconfined hello-world
docker run --security-opt apparmor=unconfined hello-world
docker run --cap-add all hello-world
```

To narrow it down some more...

**Comment by leandro-lucarella-sociomantic** [comment]
> docker run --security-opt seccomp=unconfined hello-world

FAILS

> docker run --security-opt apparmor=unconfined hello-world

WORKS

> docker run --cap-add all hello-world

FAILS

**Comment by justincormack** [comment]
Ok, so apparmor is causing issues. How exactly did you install docker?

**Comment by leandro-lucarella-sociomantic** [comment]
I followed the steps in: https://docs.docker.com/engine/installation/linux/ubuntulinux/
Basically: `apt-get install docker-engine`
(see the `apt/sources.list.d/docker` in the main description)

I tried to reinstall a couple of times, even removing the `/etc/apparmour.d/docker` file (which I checked and was recreated when reinstalling). Damn apparmour :unamused: 

It doesn't seem to come in the package though apparently is recreated when the daemon runs or something...

```
# dpkg -S /etc/apparmor.d/docker
dpkg-query: no path found matching pattern /etc/apparmor.d/docker

```# cat /etc/apparmor.d/docker


#include <tunables/global>


profile docker-default flags=(attach_disconnected,mediate_deleted) {

  #include <abstractions/base>


  network,
  capability,
  file,
  umount,

  deny @{PROC}/* w,   # deny write for all files directly in /proc (not in a subdir)
  # deny write to files not in /proc/<number>/** or /proc/sys/**
  deny @{PROC}/{[^1-9],[^1-9][^0-9],[^1-9s][^0-9y][^0-9s],[^1-9][^0-9][^0-9][^0-9]*}/** w,
  deny @{PROC}/sys/[^k]** w,  # deny /proc/sys except /proc/sys/k* (effectively /proc/sys/kernel)
  deny @{PROC}/sys/kernel/{?,??,[^s][^h][^m]**} w,  # deny everything except shm* in /proc/sys/kernel/
  deny @{PROC}/sysrq-trigger rwklx,
  deny @{PROC}/mem rwklx,
  deny @{PROC}/kmem rwklx,
  deny @{PROC}/kcore rwklx,

  deny mount,

  deny /sys/[^f]*/** wklx,
  deny /sys/f[^s]*/** wklx,
  deny /sys/fs/[^c]*/** wklx,
  deny /sys/fs/c[^g]*/** wklx,
  deny /sys/fs/cg[^r]*/** wklx,
  deny /sys/firmware/efi/efivars/** rwklx,
  deny /sys/kernel/security/** rwklx,


  # suppress ptrace denials when using 'docker ps' or using 'ps' inside a container
  ptrace (trace,read) peer=docker-default,

}
```

**Comment by cpuguy83** [comment]
This looks a little like an issue we had with 1.10 rc1 whereby we had a `docker-engine` apparmor policy that was causing these issues, so we subsequently removed the policy, however any user that had 1.10 rc1 would have to manually clean it up.

**Comment by marqvart** [comment]
FYI: I'm running Ubuntu Wily, and I have the exact same problem (and the same responses to the "narrow down the problem" commands. In other words, the docker apparmor profile installed by docker-engine does not work on Wily either.

**Comment by cpuguy83** [comment]
@marqvart docker does not ship an apparmor profile that is applied to docker itself.
If you are having the same problems, can you check if the `docker-engine` apparmor profile is loaded? This was only ever shipped with docker 1.10-rc1

**Comment by leandro-lucarella-sociomantic** [comment]
I'm not very experienced with apparmor, how can I check that?

**Comment by marqvart** [comment]
@cpuguy83 I'm not the biggest fan of apparmor so maybe my terminology is incorrect. I'm running etckeeper and this got added to /etc/apparmor.d when installing docker-engine 1.11.2-0~wily (according to the git change of /etc):

diff --git a/apparmor.d/docker b/apparmor.d/docker
new file mode 100644
index 0000000..3370c1d
--- /dev/null
+++ b/apparmor.d/docker
@@ -0,0 +1,40 @@
+
+
+#include <tunables/global>
+
+
+profile docker-default flags=(attach_disconnected,mediate_deleted) {
+
+  #include <abstractions/base>
+
+
+  network,
+  capability,
+  file,
+  umount,
+
+  deny @{PROC}/* w,   # deny write for all files directly in /proc (not in a subdir)
+  # deny write to files not in /proc/<number>/** or /proc/sys/**
+  deny @{PROC}/{[^1-9],[^1-9][^0-9],[^1-9s][^0-9y][^0-9s],[^1-9][^0-9][^0-9][^0-9]*}/** w,
+  deny @{PROC}/sys/[^k]** w,  # deny /proc/sys except /proc/sys/k* (effectively /proc/sys/kernel)
+  deny @{PROC}/sys/kernel/{?,??,[^s][^h][^m]**} w,  # deny everything except shm* in /proc/sys/kernel/
+  deny @{PROC}/sysrq-trigger rwklx,
+  deny @{PROC}/mem rwklx,
+  deny @{PROC}/kmem rwklx,
+  deny @{PROC}/kcore rwklx,
+
+  deny mount,
+
+  deny /sys/[^f]*/** wklx,
+  deny /sys/f[^s]*/** wklx,
+  deny /sys/fs/[^c]*/** wklx,
+  deny /sys/fs/c[^g]*/** wklx,
+  deny /sys/fs/cg[^r]*/** wklx,
+  deny /sys/firmware/efi/efivars/** rwklx,
+  deny /sys/kernel/security/** rwklx,
+
+
+  # suppress ptrace denials when using 'docker ps' or using 'ps' inside a container
+  ptrace (trace,read) peer=docker-default,
+
+}

**Comment by leandro-lucarella-sociomantic** [comment]
@cpuguy83 is weird because as I said, the debian package doesn't have with `/etc/apparmor.d/docker` as a file that's part of the package, and is in fact not installed by it (I also use etckeeper and it autocommits after packages are installed, and the file is not there), but when the process finishes, the file magically appears (but is not committed by etckeeper). I checked the `/var/lib/dpkg/info/docker-engine.*` files and there some mentions there to apparmor but the file is called `/etc/apparmor.d/docker-engine` not `/etc/apparmor.d/docker`.

I'm still trying to look at who's creating the file. Is this file (which I also copied in a comment above) not supposed to come with docker-engine?

**Comment by cpuguy83** [comment]
@leandro-lucarella-sociomantic Docker creates an apparmor profile for containers, this is not the thing that's broken.
The `/etc/apparmor.d/docker-engine` is broken and should be removed, it is not distributed with Docker. Likely this system had docker 1.10-rc1 on it at some point.

**Comment by leandro-lucarella-sociomantic** [comment]
I have no `docker-engine` file

**Comment by leandro-lucarella-sociomantic** [comment]
```
# ls -l apparmor.d/docker*
-rw-r--r-- 1 root root 1114 Jun 16 18:22 apparmor.d/docker
```

**Comment by leandro-lucarella-sociomantic** [comment]
```
# find /etc -name docker-engine
```
(no results)

**Comment by leandro-lucarella-sociomantic** [comment]
And yes, this system had 1.10-rc1, but has no `/etc/apparmor.d/docker-engine` anymore.
```
Start-Date: 2016-04-14  15:08:37
Start-Date: 2016-04-14  15:52:54
Commandline: apt full-upgrade
Upgrade: git-hub:amd64 (0.10-rc1-trusty, 0.10.1-trusty)
End-Date: 2016-04-14  15:52:55
```

**Comment by leandro-lucarella-sociomantic** [comment]
Any further ideas on what can be breaking docker? Is that `/etc/apparmor.d/docker` file being generated correctly?

**Comment by martsime** [comment]
I had the same problem. I stole `/etc/apparmor.d/tunables/proc` from some Ubuntu 16.04 onto my 14.04 installation. But hey, the copyright on the file is about 10 years.

```
# ------------------------------------------------------------------
#
#    Copyright (C) 2006 Novell/SUSE
#
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of version 2 of the GNU General Public
#    License published by the Free Software Foundation.
#
# ------------------------------------------------------------------

# @{PROC} is the location where procfs is mounted.
@{PROC}=/proc/
```

I got onto this track by restarting apparmor.

**Comment by leandro-lucarella-sociomantic** [comment]
I'm using trusty and my `/etc/apparmor.d/tunables/proc` looks exactly like that, but I still have this issue.

**Comment by leandro-lucarella-sociomantic** [comment]
I could fix it. I guess there was something broken in my apparmor installation (I don't know why because I never touched it). What I did was reinstalling the `apparmor-profiles` packages and then I noticed apparmor shown some errors when doing a `service apparmor reload`, it complained about a missing directory `/etc/apparmor.d/tunables/multiarch.d`. I created it, reloaded again (this time without errors) and now docker works without hacks.

I'm not sure if this issue should be closed though, because still the error message docker gives makes no sense at all and gives the user no clue about what's wrong.

**Comment by FliiFe** [comment]
On my side, the symptoms were the exact same, but the isssue didn't have the same origin.
I was affected by [this issue](https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/1020662). (Fix at the end of the page).

I totally agree with @leandro-lucarella-sociomantic, this should not be closed and the error message should be more relevant of what is wrong.

**Comment by cpuguy83** [comment]
@leandro-lucarella-sociomantic s/error message docker gives/apparmor :)

Can you test on 1.12-rc2, by chance? The error handling from the container startup was a bit too generic and assuming "not found" was the container command not found.
This was fixed (while doing other things) and may no longer be an issue.
Thanks!

**Comment by leandro-lucarella-sociomantic** [comment]
> @leandro-lucarella-sociomantic s/error message docker gives/apparmor :)

Not from the user's POV :)

> Can you test on 1.12-rc2, by chance? The error handling from the container startup was a bit too generic and assuming "not found" was the container command not found.
> This was fixed (while doing other things) and may no longer be an issue.

(un)fortunately I fixed the issue and I don't even know exactly what was causing it, so I don't know how to reproduce it again. :S

**Comment by thaJeztah** [comment]
We merged a change for docker 1.12 that returns a better error message, instead of masking it as "command not found"; https://github.com/docker/docker/pull/22983/files#diff-3cb140026df40998ea29c5bcb6bb292eR150

I'm closing this issue, because the error message should now be more descriptive in 1.12, but if anyone is able to give the 1.12 release candidate a spin to verify, that would be great http://github.com/docker/docker/releases

**Comment by leandro-lucarella-sociomantic** [comment]
Thanks for addressing this!

**Comment by norlin** [comment]
I have similar issue, but on this stage I have different results:

> docker run --privileged hello-world 

Works!

> docker run --security-opt seccomp=unconfined hello-world

Works!

> docker run --security-opt apparmor=unconfined hello-world

Nope.

> docker run --cap-add all hello-world

Nope.

Ubuntu 16.04
Kernel: `4.8.6-x86_64-linode78`

Docker version (installed from Ubuntu repos):

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   6b644ec
 Built:        Mon, 19 Dec 2016 09:20:48 +1300
 OS/Arch:      linux/386

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   6b644ec
 Built:        Mon, 19 Dec 2016 09:20:48 +1300
 OS/Arch:      linux/386
```

(And I can't install a latest version from Docker's repo because it says `Unable to locate package: docker-engine`)

**Comment by thaJeztah** [comment]
> And I can't install a latest version from Docker's repo because it says Unable to locate package: docker-engine

How did you install docker? Did you install a static binary, or use the instructions from https://docs.docker.com/engine/installation/linux/ubuntu/ ? Is the apt repository (apt.dockerproject.org) configured?

> Kernel: 4.8.6-x86_64-linode78

That looks like a non-standard kernel; can you try running the `check-config.sh` script to verify your setup? https://raw.githubusercontent.com/docker/docker/master/contrib/check-config.sh

Also, can you please open a new issue, because your issue may be unrelated to the issue that's reported here

**Comment by norlin** [comment]
@thaJeztah thank you, I've posted a new issue: #31185 (including answers to your questions).

**Comment by alancapc** [comment]
Ok, in my case it was just a matter of **vbox machine not connected to the internet**. I also ran the command:

> docker run --privileged hello-world
