### ISSUE TITLE
Unable to install MsBuild on a docker image

### ISSUE THREAD

**Issue by olafleur** [docker/docker#23574]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   2b97201
 Built:        Tue Apr 26 23:51:36 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   2b97201
 Built:        Tue Apr 26 23:51:36 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
Containers: 17
 Running: 0
 Paused: 0
 Stopped: 17
Images: 14
Server Version: 1.12.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null
Kernel Version: 10.0 14300 (14300.1000.amd64fre.rs1_release_svc.160324-1723)
Operating System: Windows Server 2016 Standard Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 1.331 GiB
Name: WIN-JIT6DOCS89Q
ID: FLJW:WKG6:IZFM:SHLY:NYPV:BUG3:MIWD:XIFR:2AD4:MD77:T3DM:THDE
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Windows Server 2016 TP5 running in Hyper-V

**Steps to reproduce the issue:**
1. `RUN nuget install MSBuild.Microsoft.VisualStudio.Web.targets` in the Dockerfile
2. `docker build . `

**Describe the results you received:**
Successfully installed 'MSBuild.Microsoft.VisualStudio.Web.targets 14.0.0.1' to C:\
hcsshim::ImportLayer failed in Win32: The filename or extension is too long. (0xce) layerId=\\?\C:\ProgramData\docker\windowsfilter\6972759b516ea4c61df51460b112fe5aad72c5d3cccba3505692cd580bc967cc flavour=1 folder=C:\Windows\TEMP\hcs190795884

**Describe the results you expected:**
I expected the install to complete normally, however, it crashes with this message (that tells that MSBuild was installed, but it is not).

**Additional information you deem important (e.g. issue happens only occasionally):**
It seems to me to be a 32-bit problem, but the Windows Server 2016 TP5 is supposed to be 64-bit and docker is supposed to be 64-bit. I'm using the microsoft/iis base image in the docker file (is that 64 bit?)

**Comment by olafleur** [comment]
I just rebooted the computer after having tried a few things and now it works...

**Comment by thaJeztah** [comment]
Let me close this issue then, but let us know if you're seeing this issue again

**Comment by olafleur** [comment]
ok ;)
