### ISSUE TITLE
[1.12.0-RCx] Review consistency of CLI reference with the code

### ISSUE THREAD

**Issue by icecrime** [docker/docker#23598]
Review consistency of CLI reference with the code on the new commands:
- `docker node`
- `docker service`
- `docker swarm`

**Comment by icecrime** [comment]
Ping @sfsmithcha: are you available to take a pass a this?

**Comment by sfsmithcha** [comment]
@icecrime I'll take a look

**Comment by albers** [comment]
The `docker service` subcommands do not have cli reference pages yet.

**Comment by sfsmithcha** [comment]
`docker node` updates part of https://github.com/docker/docker/pull/23656

@thaJeztah working on `docker service` commands

**Comment by sfsmithcha** [comment]
`docker service` added here https://github.com/docker/docker/pull/23702

**Comment by thaJeztah** [comment]
Looks like these were all done, so closing
