### ISSUE TITLE
mount not working on a block device passed to container

### ISSUE THREAD

**Issue by sainath14** [docker/docker#23591]
docker run -it --rm --device=/dev/sdb:/dev/xdb:rwm ubuntu bash

sdb is a block device on the host

Inside the container
root@aa3807e841a6:/# ls -ls /dev/xdb
0 brw-rw---- 1 root disk 8, 16 Jun 15 20:01 /dev/xdb

root@aa3807e841a6:/home# mount /dev/xdb storage/
mount: permission denied

**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.2
 Git commit:   8510adf-unsupported
 Built:        Wed Jun 15 19:40:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.2
 Git commit:   8510adf-unsupported
 Built:        Wed Jun 15 19:40:43 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 60
Server Version: 1.12.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 67
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: default
Default Runtime: default
Kernel Version: 3.13.0-32-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 88
Total Memory: 62.79 GiB
Name: otc-grantley-03
ID: AEOO:2PMA:WJE7:6S2D:E5GF:OE2P:KGX4:C43Q:RNPH:57XE:6Y35:PDJR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 23
 System Time: 2016-06-15T16:00:17.44757241-04:00
 EventsListeners: 0
Http Proxy: http://proxy-chain.intel.com:911
Https Proxy: http://proxy-chain.intel.com:911
No Proxy: intel.com,.intel.com
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment]
`mount` is blocked by the various security policies.
You'll need to use `--cap-add SYS_ADMIN` or `--privileged`

**Comment by justincormack** [comment]
As @cpuguy83 says. You will also need `--security-opt apparmor=unconfined` for mounting if you do not use `--privileged` as you are on Ubuntu.

**Comment by sainath14** [comment]
thanks @cpuguy83 @justincormack

**Comment by justincormack** [comment]
I will close this as it is expected behaviour. Let us know if you have any more issues though.
