### ISSUE TITLE
/v1.23/containers/json API returns empty string for NetworkID.

### ISSUE THREAD

**Issue by clinta** [docker/docker#23596]
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 62
 Running: 5
 Paused: 0
 Stopped: 57
Images: 57
Server Version: 1.11.2
Storage Driver: zfs
 Zpool: tank
 Zpool Health: ONLINE
 Parent Dataset: tank/docker
 Space Used By Parent: 2981614592
 Space Available: 100508783616
 Parent Quota: no
 Compression: lz4
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: vxlan bridge null host
Kernel Version: 4.4.0-24-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.842 GiB
Name: dc1-dks04
ID: T37Y:UHKY:FDQD:36FE:46U2:I2OV:TPO7:GG5G:KMRA:7FX4:XQRA:TZ5A
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Cluster store: consul://dc1-dks04.in.trilliumstaffing.com:8500
Cluster advertise: 10.1.8.169:2376
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.  `docker run -d busybox sleep 1000`
2. `curl --unix-socket /var/run/docker.sock http:/v1.23/containers/json | jq`

**Describe the results you received:**
```json
[
  {
    "Id": "ce43bbddcd79c43797eed177d18b8a0cbdea4827f18b6a0580947d3d2637f508",
    "Names": [
      "/small_yonath"
    ],
    "Image": "busybox",
    "ImageID": "sha256:47bcc53f74dc94b1920f0b34f6036096526296767650f223433fe65c35f149eb",
    "Command": "sleep 1000",
    "Created": 1466024674,
    "Ports": [],
    "Labels": {},
    "State": "running",
    "Status": "Up 3 minutes",
    "HostConfig": {
      "NetworkMode": "default"
    },
    "NetworkSettings": {
      "Networks": {
        "bridge": {
          "IPAMConfig": null,
          "Links": null,
          "Aliases": null,
          "NetworkID": "",
          "EndpointID": "09bca838a4d3244f2fcc02f3509edd665d75182397e54a8ab0ff12577f8349b3",
          "Gateway": "172.17.0.1",
          "IPAddress": "172.17.0.2",
          "IPPrefixLen": 16,
          "IPv6Gateway": "",
          "GlobalIPv6Address": "",
          "GlobalIPv6PrefixLen": 0,
          "MacAddress": "02:42:ac:11:00:02"
        }
      }
    },
    "Mounts": []
  }
]
```

**Describe the results you expected:**

The  `"NetworkID"` field should contain the networkID, not the empty string. The sample in the [docs](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.23/) has the NetworkID.

**Comment by sainath14** [comment]
I notice it as well

[{"Id":"6171043c7d573854201495710d320a73d44c007de6a16c4155662e48da1de50b","Names":["/stoic_leakey"],"Image":"docker-dev:rename-error","ImageID":"sha256:c65e430fcd406f4d231adb65df8e8c13cb1272821064135919ee470e0e2f7e8b","Command":"hack/dind bash","Created":1466019354,"Ports":[],"Labels":{},"State":"running","Status":"Up 4 hours","HostConfig":{"NetworkMode":"default"},"NetworkSettings":{"Networks":{"bridge":{"IPAMConfig":null,"Links":null,"Aliases":null,**"NetworkID":""**,"EndpointID":"55d8acf72c6f186325ad88bebbb711a1a9280aaa268d5adc631addce7e6f297d","Gateway":"172.17.0.1","IPAddress":"172.17.0.2","IPPrefixLen":16,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"02:42:ac:11:00:02"}}},"Mounts":[{"Source":"/home/sainath/sources/docker-dev/docker","Destination":"/go/src/github.com/docker/docker","Mode":"","RW":true,"Propagation":"rprivate"},{"Name":"48cf622bbc538c1ae8e6b0ba47ef660b39e0792de72c641a9ddd3e5e0beca042","Source":"/var/lib/docker/volumes/48cf622bbc538c1ae8e6b0ba47ef660b39e0792de72c641a9ddd3e5e0beca042/_data","Destination":"/var/lib/docker","Driver":"local","Mode":"","RW":true,"Propagation":""}]}]


Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.4
 Git commit:   2f7c841-unsupported
 Built:        Tue May 10 17:32:30 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.4
 Git commit:   2f7c841-unsupported
 Built:        Tue May 10 17:32:30 2016
 OS/Arch:      linux/amd64

I will take a look.

**Comment by sainath14** [comment]
NetworkID assignment is missing in the daemon code
I will submit a PR #dibs

**Comment by sainath14** [comment]
#dibs
