### ISSUE TITLE
some ipv4 files are missing in the latest ubuntu(with kernel 4.4) docker image

### ISSUE THREAD

**Issue by sli4** [docker/docker#23608]
@olleolleolle #when I was tuning docker(v1.10) container tcp parameter, I found some tcp related files are missing in the container.  The releated operation steps and docker info as below.
**Step1:  go to get docker info **
$ sudo docker info
Containers: 20
 Running: 4
 Paused: 0
 Stopped: 16
Images: 51
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 164
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.4.0-22-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.699 GiB
Name: fas-ci
ID: PXKE:FKHX:XFAV:L7WJ:AL7G:U5X2:USKL:I2PN:2RO4:OHEB:5YQR:PKUL
WARNING: No swap limit support
**Step 2: launch docker container and get the image kernel information **
$ sudo docker run -ti ubuntu bash
root@8dbb49a9b9b1:/# uname -a
Linux 8dbb49a9b9b1 4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Step3: list the ipv4 files in docker**
root@8dbb49a9b9b1:/# cd /proc/sys/net/ipv4/
root@8dbb49a9b9b1:/proc/sys/net/ipv4# ls -l
total 0
dr-xr-xr-x 1 root root 0 Jun 15 06:50 conf
-rw-r--r-- 1 root root 0 Jun 15 06:50 fwmark_reflect
-rw-r--r-- 1 root root 0 Jun 15 06:50 icmp_echo_ignore_all
-rw-r--r-- 1 root root 0 Jun 15 06:50 icmp_echo_ignore_broadcasts
-rw-r--r-- 1 root root 0 Jun 15 06:50 icmp_errors_use_inbound_ifaddr
-rw-r--r-- 1 root root 0 Jun 15 06:50 icmp_ignore_bogus_error_responses
-rw-r--r-- 1 root root 0 Jun 15 06:50 icmp_ratelimit
-rw-r--r-- 1 root root 0 Jun 15 06:50 icmp_ratemask
-rw-r--r-- 1 root root 0 Jun 15 06:50 igmp_link_local_mcast_reports
-rw-r--r-- 1 root root 0 Jun 15 06:50 ip_forward
-rw-r--r-- 1 root root 0 Jun 15 06:50 ip_forward_use_pmtu
-rw-r--r-- 1 root root 0 Jun 15 06:50 ip_local_port_range
-rw-r--r-- 1 root root 0 Jun 15 06:50 ip_local_reserved_ports
-rw-r--r-- 1 root root 0 Jun 15 06:50 ip_no_pmtu_disc
-rw-r--r-- 1 root root 0 Jun 15 06:50 ip_nonlocal_bind
-rw-r--r-- 1 root root 0 Jun 15 06:50 ipfrag_high_thresh
-rw-r--r-- 1 root root 0 Jun 15 06:50 ipfrag_low_thresh
-rw-r--r-- 1 root root 0 Jun 15 06:50 ipfrag_time
dr-xr-xr-x 1 root root 0 Jun 15 06:50 neigh
-rw-r--r-- 1 root root 0 Jun 15 06:50 ping_group_range
dr-xr-xr-x 1 root root 0 Jun 15 06:50 route
-rw-r--r-- 1 root root 0 Jun 15 06:50 tcp_base_mss
-rw-r--r-- 1 root root 0 Jun 15 06:50 tcp_ecn
-rw-r--r-- 1 root root 0 Jun 15 06:50 tcp_ecn_fallback
-rw-r--r-- 1 root root 0 Jun 15 06:50 tcp_fwmark_accept
-rw-r--r-- 1 root root 0 Jun 15 06:50 tcp_mtu_probing
-rw-r--r-- 1 root root 0 Jun 15 06:50 tcp_probe_interval
-rw-r--r-- 1 root root 0 Jun 15 06:50 tcp_probe_threshold
-rw-r--r-- 1 root root 0 Jun 15 06:50 xfrm4_gc_thresh

**Step4: list all the ipv4 files of host**
$ ls -l /proc/sys/net/ipv4
total 0
-rw-r--r-- 1 root root 0 Jun 15 14:19 cipso_cache_bucket_size
-rw-r--r-- 1 root root 0 Jun 15 14:19 cipso_cache_enable
-rw-r--r-- 1 root root 0 Jun 15 14:19 cipso_rbm_optfmt
-rw-r--r-- 1 root root 0 Jun 15 14:19 cipso_rbm_strictvalid
dr-xr-xr-x 1 root root 0 Jun 15 14:19 conf
-rw-r--r-- 1 root root 0 Jun 15 14:19 fwmark_reflect
-rw-r--r-- 1 root root 0 Jun 15 14:19 icmp_echo_ignore_all
-rw-r--r-- 1 root root 0 Jun 15 14:19 icmp_echo_ignore_broadcasts
-rw-r--r-- 1 root root 0 Jun 15 14:19 icmp_errors_use_inbound_ifaddr
-rw-r--r-- 1 root root 0 Jun 15 14:19 icmp_ignore_bogus_error_responses
-rw-r--r-- 1 root root 0 Jun 15 14:19 icmp_msgs_burst
-rw-r--r-- 1 root root 0 Jun 15 14:19 icmp_msgs_per_sec
-rw-r--r-- 1 root root 0 Jun 15 14:19 icmp_ratelimit
-rw-r--r-- 1 root root 0 Jun 15 14:19 icmp_ratemask
-rw-r--r-- 1 root root 0 Jun 15 14:19 igmp_link_local_mcast_reports
-rw-r--r-- 1 root root 0 Jun 15 14:19 igmp_max_memberships
-rw-r--r-- 1 root root 0 Jun 15 14:19 igmp_max_msf
-rw-r--r-- 1 root root 0 Jun 15 14:19 igmp_qrv
-rw-r--r-- 1 root root 0 Jun 15 14:19 inet_peer_maxttl
-rw-r--r-- 1 root root 0 Jun 15 14:19 inet_peer_minttl
-rw-r--r-- 1 root root 0 Jun 15 14:19 inet_peer_threshold
-rw-r--r-- 1 root root 0 Jun 15 14:19 ip_default_ttl
-rw-r--r-- 1 root root 0 Jun 15 14:19 ip_dynaddr
-rw-r--r-- 1 root root 0 Jun 15 14:19 ip_early_demux
-rw-r--r-- 1 root root 0 Jun 15 11:41 ip_forward
-rw-r--r-- 1 root root 0 Jun 15 14:19 ip_forward_use_pmtu
-rw-r--r-- 1 root root 0 Jun 15 14:19 ipfrag_high_thresh
-rw-r--r-- 1 root root 0 Jun 15 14:19 ipfrag_low_thresh
-rw-r--r-- 1 root root 0 Jun 15 14:19 ipfrag_max_dist
-rw-r--r-- 1 root root 0 Jun 15 14:19 ipfrag_secret_interval
-rw-r--r-- 1 root root 0 Jun 15 14:19 ipfrag_time
-rw-r--r-- 1 root root 0 Jun 15 14:19 ip_local_port_range
-rw-r--r-- 1 root root 0 Jun 15 14:19 ip_local_reserved_ports
-rw-r--r-- 1 root root 0 Jun 15 14:19 ip_nonlocal_bind
-rw-r--r-- 1 root root 0 Jun 15 14:19 ip_no_pmtu_disc
dr-xr-xr-x 1 root root 0 Jun 15 14:19 neigh
-rw-r--r-- 1 root root 0 Jun 15 14:19 ping_group_range
dr-xr-xr-x 1 root root 0 Jun 15 14:19 route
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_abort_on_overflow
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_adv_win_scale
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_allowed_congestion_control
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_app_win
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_autocorking
-r--r--r-- 1 root root 0 Jun 15 14:19 tcp_available_congestion_control
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_base_mss
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_challenge_ack_limit
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_congestion_control
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_dsack
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_early_retrans
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_ecn
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_ecn_fallback
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_fack
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_fastopen
-rw------- 1 root root 0 Jun 15 14:19 tcp_fastopen_key
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_fin_timeout
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_frto
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_fwmark_accept
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_invalid_ratelimit
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_keepalive_intvl
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_keepalive_probes
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_keepalive_time
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_limit_output_bytes
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_low_latency
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_max_orphans
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_max_reordering
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_max_syn_backlog
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_max_tw_buckets
**-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_mem**
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_min_rtt_wlen
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_min_tso_segs
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_moderate_rcvbuf
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_mtu_probing
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_no_metrics_save
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_notsent_lowat
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_orphan_retries
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_pacing_ca_ratio
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_pacing_ss_ratio
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_probe_interval
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_probe_threshold
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_recovery
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_reordering
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_retrans_collapse
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_retries1
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_retries2
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_rfc1337
**-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_rmem**
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_sack
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_slow_start_after_idle
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_stdurg
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_synack_retries
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_syncookies
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_syn_retries
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_thin_dupack
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_thin_linear_timeouts
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_timestamps
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_tso_win_divisor
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_tw_recycle
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_tw_reuse
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_window_scaling
**-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_wmem**
-rw-r--r-- 1 root root 0 Jun 15 14:19 tcp_workaround_signed_windows
-rw-r--r-- 1 root root 0 Jun 15 14:19 udp_mem
-rw-r--r-- 1 root root 0 Jun 15 14:19 udp_rmem_min
-rw-r--r-- 1 root root 0 Jun 15 14:19 udp_wmem_min
-rw-r--r-- 1 root root 0 Jun 15 14:19 xfrm4_gc_thresh
Comparing the ipv4 files shown in docker container and host, I found some files are missing in the docker container. I went though the similar existed issues but there's no final solution for it. Is it a known issue which will be improved in the future version ? Or is there already solution for it? 
Any guy can help on it ? Thanks a lot in advance.

**Comment by summerkai** [comment]
+1

**Comment by justincormack** [comment]
The omitted values are global settings, not per container settings, so you have to set them on the host. This is unlikely to change, it is not under control of docker.

**Comment by summerkai** [comment]
@GordonTheTurtle : thanks for your remind and sorry for the wrong comment.

**Comment by sli4** [comment]
@justincormack :👍  Thanks for your reply

**Comment by justincormack** [comment]
I am going to close this as there is nothing we can do, but feel free to continue discussing. You can set them if you run with `--net=host` and you probably also need `--privileged` as the they should be visible if you have to set them, but this will be for all containers.

**Comment by sli4** [comment]
@justincormack : Thanks for you reply. I have tried to run with --net=host, and it works. Now I have another question, how can I distinguish between the global setting and the container setting, and is there  any  reference document for expanding which parameters are global  setting and container setting.
