### ISSUE TITLE
What is the equivalent of /etc/docker/plugins on Windows?

### ISSUE THREAD

**Issue by anaghab12** [docker/docker#23605]
In other words, how do you register a docker plugin on Windows?

**Comment by thaJeztah** [comment]
Plugins are not currently supported on Windows daemons (there's no full parity yet between Windows and Linux daemons)

**Comment by taylorb-microsoft** [comment]
The equivalent directory is C:\programdata\docker\plugins

@thaJeztah this is all common code - should work exactly the same (obviously what the plug in does under the covers will need to account for platform differences)

**Comment by anaghab12** [comment]
The docker daemon on Windows does not recognize the plug-in spec file stored in C:\programdata\docker\plugins. Even though the spec file is present in this directory, the daemon throws "plug-in not found" error.

**Comment by thaJeztah** [comment]
@taylorb-microsoft oops, my mistake there, I thought it was still in development; let me reopen while this discussion is ongoing

**Comment by friism** [comment]
@anaghab12 what's the nature of the plugin you're trying to install? Some plugins rely on unix sockets which don't work on Windows: https://docs.docker.com/engine/extend/plugin_api/

We need to come up with a mode that also works on Windows (maybe based on named pipes). cc @icecrime

**Comment by anaghab12** [comment]
It is a volume plug-in. I am trying to register it using a spec file (not the unix socket approach).
Looking at the code, I am not sure if the docker daemon on Windows looks for plug-ins in the Windows equivalent (ProgramData\Docker\plugins) directory.

**Comment by anaghab12** [comment]
Following up - does the docker daemon on Windows support plug-in discovery via TCP as mentioned above (.spec file method)?

**Comment by anusha-ragunathan** [comment]
Currently, plugin discovery is not supported on Windows, even for spec files. https://github.com/docker/docker/blob/master/pkg/plugins/discovery.go#L19
