### ISSUE TITLE
``--scale`` flag missing from ``docker service create command

### ISSUE THREAD

**Issue by kunalkushwaha** [docker/docker#23615]
**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.12.0-rc1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   1f136c1-unsupported
 Built:        Wed Jun 15 05:28:48 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   1f136c1-unsupported
 Built:        Wed Jun 15 05:28:48 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
$ docker info
Containers: 9
 Running: 1
 Paused: 0
 Stopped: 8
Images: 67
Server Version: 1.12.0-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 139
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: active
 NodeID: 5pnsekuztcm2nuf3ivosak12h
 IsManager: Yes
 Managers: 1
 Nodes: 1
 CACertHash: sha256:bd217263c4c73bdbb83b7a376b86637cca47583c18560e38756cd9e6461b4c0e
Runtimes: default
Default Runtime: default
Kernel Version: 4.4.0-21-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: mac-dev
ID: KQZK:U6ER:EY5G:Y5WK:4N3Q:FQVV:5YW7:E5WF:TOXA:CJBK:A5BU:4NS7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Virtualbox VM

**Steps to reproduce the issue:**
1. ``docker service create --scale 1 --name helloworld alpine ping docker.com``

**Describe the results you received:**
```
$ docker service create --scale 1 --name helloworld alpine ping docker.com
unknown flag: --scale
See 'docker service create --help'.
```
**Describe the results you expected:**
Service should be create with single instance.

**Comment by StefanScherer** [comment]
Use `--replicas`

**Comment by justincormack** [comment]
Yes, it got renamed, are there any places in the docs that still say `scale`?

**Comment by kunalkushwaha** [comment]
Hi,

In these documents too --scale is referred.

- Scale the service in the Swarm
<https://github.com/docker/docker/blob/ea4fef2d875de39044ca7570c35365b75086e8a5/docs/swarm/swarm-tutorial/scale-service.md>
- Apply rolling updates to a service
<https://github.com/docker/docker/blob/ea4fef2d875de39044ca7570c35365b75086e8a5/docs/swarm/swarm-tutorial/rolling-update.md>
- Drain a node on the Swarm
<https://github.com/docker/docker/blob/ea4fef2d875de39044ca7570c35365b75086e8a5/docs/swarm/swarm-tutorial/drain-node.md>

Regards,
Kunal


On Thu, Jun 16, 2016 at 5:27 PM, Justin Cormack <notifications@github.com>
wrote:

> Yes, it got renamed, are there any places in the docs that still say scale
> ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/docker/docker/issues/23615#issuecomment-226420454>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACoXIboqMf1c2jVRCgP5pmDCaN2dVzUIks5qMQj7gaJpZM4I3B8V>
> .
>



-- 
Regards,
Kunal Kushwaha

**Comment by sfsmithcha** [comment]
Thanks @kunalkushwaha , docs refresh to include all the RC 1 CLI changes is WIP.

**Comment by thaJeztah** [comment]
Looks like these documents are fixed on master, can you check, @kunalkushwaha ?

**Comment by kunalkushwaha** [comment]
Confirmed, It is fixed in all documents.

**Comment by thaJeztah** [comment]
Thanks @kunalkushwaha! I'll close this issue
