### ISSUE TITLE
'docker swarm join' failure breaks joining legitimately

### ISSUE THREAD

**Issue by nathanleclaire** [docker/docker#23611]
**Output of `docker version`:**

```
docker@agent0:~$ docker version
Client:
 Version:      1.12.0-rc1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   1f136c1
 Built:        Wed Jun 15 04:49:14 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   1f136c1
 Built:        Wed Jun 15 04:49:14 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
docker@agent0:~$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.0-rc1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host overlay bridge
Swarm: pending
 NodeID:
 IsManager: No
Runtimes: default
Default Runtime: default
Kernel Version: 4.4.13-boot2docker
Operating System: Boot2Docker 1.12.0-rc1 (TCL 7.1); HEAD : d63b52e - Wed Jun 15 15:13:23 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: agent0
ID: UWHX:WBVT:35D2:Y453:OUXO:YYMM:JAIA:UHVE:MOJU:IOP6:LE5D:JHEG
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 34
 System Time: 2016-06-16T02:43:30.647687081Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running on VirtualBox / boot2docker / Docker Machine, toolbox 1.12.0-rc1 release.

**Steps to reproduce the issue:**

Start up 2 machines running Docker.

On one:

```
$ docker swarm init
```

It says it's now part of a Swarm, great.

On another:

```
$ docker swarm join <BOGUS_IP>:2377
Error response from daemon: timeout reached before node was joined
```

OK, fair, I typed the wrong address.  Any non-reachable IP should do.  In my case I accidentally tried to `join` to another agent node instead of the manager.

Now, run: 

```
$ docker swarm join <LEGIT_MANAGER_IP>:2377
Error response from daemon: this node is already part of a Swarm
```

Hey, no fair!  I'm trying to join a swarm, how could I already be a part of one?  And indeed, it doesn't show up on the manager:

```
docker@manager:~$ docker node ls
ID                           NAME     MEMBERSHIP  STATUS  AVAILABILITY  MANAGER STATUS  LEADER
9nizwz837ohj7g1yf36a6ixge *  manager  Accepted    Ready   Active        Reachable       Yes
```

I don't think there's even a way to check the membership status and health on a worker node?  How to recover from this condition?  Users will have to kill their machines and start over or maybe nuke `/var/lib/docker`.

**Describe the results you expected:**

`docker swarm join` should work just fine to join a legitimate manager node after the first call fails.  Or, at least, if there is a good reason for the failure give back a more useful error message.

Logs on the agent:

```console
docker@agent0:~$ tail /var/log/docker.log
time="2016-06-16T02:40:48.674987527Z" level=debug msg="Calling POST /v1.24/swarm/join"
time="2016-06-16T02:40:48.675070216Z" level=debug msg="form data: {\"CACertHash\":\"\",\"ListenAddr\":\"0.0.0.0:2377\",\"Manager\":false,\"RemoteAddrs\":[\"192.168.99.115:2377\"],\"Secret\":\"\"}"
time="2016-06-16T02:40:48.675768563Z" level=debug msg="no valid local CA certificate found: local root CA certificate does not exist"
time="2016-06-16T02:40:58.679406078Z" level=error msg="Handler for POST /v1.24/swarm/join returned error: timeout reached before node was joined"
time="2016-06-16T02:41:08.766548833Z" level=debug msg="Calling POST /v1.24/swarm/join"
time="2016-06-16T02:41:08.766631472Z" level=debug msg="form data: {\"CACertHash\":\"\",\"ListenAddr\":\"0.0.0.0:2377\",\"Manager\":false,\"RemoteAddrs\":[\"192.168.99.116:2377\"],\"Secret\":\"\"}"
time="2016-06-16T02:41:08.766702276Z" level=error msg="Handler for POST /v1.24/swarm/join returned error: this node is already part of a Swarm"
time="2016-06-16T02:43:15.986501975Z" level=debug msg="Calling GET /v1.24/version"
time="2016-06-16T02:43:26.784468172Z" level=debug msg="Calling GET /v1.24/info"
time="2016-06-16T02:43:30.647060977Z" level=debug msg="Calling GET /v1.24/info"
```

Joining with the correct IP the first time around works fine on this setup.  Lemme know if you want more.

@dnephin @aluzzardi @vieux

**Comment by tonistiigi** [comment]
Easy fix in docker side for it is to change the message to `timeout reached before node was joined, attempt to join will continue in the background. current status of the operation can be seen from "docker info"`. Also the `this node is already part of a Swarm` message could suggest that the `swarm leave` operation is required.

Currently swarmkit doesn't consider network errors as fatal and always keeps retrying. Maybe join address should be an exception. Also there will be multiple addresses supported in the future so swarmkit would need to try them all before giving up.

**Comment by jimmyxian** [comment]
Meet the same problem and really confuse.
> docker swarm join should work just fine to join a legitimate manager node after the first call fails. 

+1 for this

**Comment by nathanleclaire** [comment]
For what it's worth, I can see the utility of having a join which continues to persist attempts in the background (although I'd advocate for a configurable "give up" period so that, e.g. after 30 minutes of failure the daemon can stop worrying about it). I wonder how folks feel about `join --sync` (or `join --async`) flag to indicate whether or not to block the CLI with this operation.

Big +1 on the intermediate suggestion to make the help text more informative though.

**Comment by tonistiigi** [comment]
This situation will become better after b40d97676428cc2dc9fe730374363796dacc45b5 , timeouts will only come with actual error cases and messages in commands/statuses are more clear. Currently waiting for a merge of swarmkit pr.

**Comment by nathanleclaire** [comment]
@tonistiigi I think that PR got merged (and consequently this can be closed), right?

**Comment by alaagalal** [comment]
Any solutions for this issue please
