### ISSUE TITLE
Docker registry need help : connection refused

### ISSUE THREAD

**Issue by Black-Butterfly** [docker/docker#23620]
Hello,

As I said, it's not really a bug, but it's more that I don't understand why it doesn't work as it should...

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Output of `docker version`:**

```
Client :
    Version:  1.11.2
    API version: 1.23
    Go version: go1.5.4
    Git commit: b9f10c9
    Built: Wed Jun 1 22:00:43 2016
    OS/Arch: linux/amd64

Server:
    Version: 1.11.2
    API version: 1.23
    Go version: go1.5.4
    Git commit: b9f10c9
    Built: Wed Jun 1 22:00:43 2016
    OS/Arch: linux/amd64
```

**Output of `docker info`:**

```
Containers : 2
    Running: 0
    Paused: 0
    Stopped: 2
Images: 4
Server Version: 1.11.2
StorageDriver: aufs
    Root Dir: /var/lib/docker/aufs
    Backing Filesystem: extfs
    Dirs: 27
    Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
    Volume: local
    Network: bridge null host
Kernel Version: 4.4.0-21-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x89_64
CPUs: 1
Total Memory: 1.215 GiB
Name: lub16cli-VirtualBox
ID: Y5ZD:TCEH:HKXT:4HZJ:VWRI:CP6Q:F5BM:IATH:6GOD:ZA6W:HUPJ:O3DE
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Output of `uname -a`:**

```
Linux lub16cli-VirtualBox 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016x86_64x86_64x86_64 GNU/Linux
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Virtualbox environnement : 
    2 Ubuntu machine with docker
    1 LDAP server (but I don't use it's certificate ...)

**Steps to reproduce the issue:**
Here is all the cmd I did :
0. `sudo -s` 
1. `curl -fsSl https://get.docker.com | sh`
2. `service docker start`
3. `systemctl start docker`
4. `docker pull registry`
5. `nano /etc/hosts`     ( Add :  10.42.0.4  dockerregistry.intranet)
6. `mkdir -p certs && openssl req -newkey rsa:4096 -nodes -sha256 -keyout certs/dockerregistry.key -x509 -days 365 -out certs/dockerregistry.crt`
 --> FR
 --> *my-city*
 --> *my-neighboor*
 --> personal_company
 --> IT
 --> dockerregistry.intranet
 --> Email Address : (I pressed enter)
7. `ls certs  (generation worked)`
8. `mkdir -p /etc/docker/certs.d/dockerregistry.intranet && cp /home/lub16-cli/certs/dockerregistry.crt /etc/docker/certs.d/dockerregistry.intranet/ca.crt`
9. `ls /etc/docker/certs.d/dockerregistry.intranet` (worked well)
10. `service docker stop && service docker start`
11. `systemctl restart docker`
12. `docker run -d -p 5000:5000 --restart=always --name registry -v `pwd`/certs:certs -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/dockerregistry.crt -e REGISTRY_HTTP_TLS_KEY=/certs/dockerregistry.key registry:2`
13. `docker pull ubuntu && docker tag ubuntu dockerregistry.intranet:5000/ubuntu`
14. `docker push dockerregistry.intranet:5000/ubuntu`

**Describe the results you received:**

The push refers to a repository [dockerregistry.intranet:5000/ubuntu]
Get https://dockerregistry.intranet:5000/v1/_ping: dial tcp 10.42.0.4:5000: getsockopt: connection refused

**Describe the results you expected:**

The push should work :/

**Additional information you deem important (e.g. issue happens only occasionally):**

Even if I have an LDAP server or another docker installed on another virtual machine, for now I just test locally. I tried with localhost and that worked well. 

If I miss something or did something that I shouldn't, please tell me. I don't understand why that don't work

**Comment by Black-Butterfly** [comment]
I have reinstalled a virtual machine and redo all the procedure that I wrote. Now I have this error message : 
Get https://dockerregistry.intranet:5000/v1/_ping: x509: certificate signed by unknown authority. I saw some topic about it so I'll try to figured it out how to fix the problem. 
I have a meeting where I have to prove the utility of docker for a healthcare lab. I should be back in 2 hours I think. Thank's by advance in case :)

**Comment by Black-Butterfly** [comment]
Ok so after copying the code to add the certificate, everything works fine. Sorry for the useless opening thread.

**Comment by justincormack** [comment]
ok, glad you solved it!

**Comment by atul1989** [comment]
while building docker image from Dockerfile following error is coming please suggest the required solution
i did not configure ssl 

 docker build -t myregistry/centos7:test1 .
Sending build context to Docker daemon 713.2 MB
Step 1 : FROM 208.103.219.139:80/newcentos:new
Get https://208.103.219.139:80/v1/_ping: dial tcp 208.103.219.139:80: getsockopt: connection refused

**Comment by thaJeztah** [comment]
@atul1989  Please keep in mind that the GitHub issue tracker is not intended as a general support forum, but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

**Comment by toughrice** [comment]
@Black-Butterfly I'm got stuck by the same problem. What do you mean by "copying the code to add the certificate"?

**Comment by zhisheng17** [comment]
@Black-Butterfly 
I'm  got  the same  problem ,   you  had  said   "copying the code to add the certificate",   What do you mean ?  I can't   understand.

**Comment by lviggiano** [comment]
same here. 

```
18:25:18 lvig0001@ITC02PXKJCG8WP:~/var/src/wordpress (master)$ docker version
Client: Docker Engine - Community
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:32:50 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 06:40:58 2019
  OS/Arch:          linux/amd64
  Experimental:     true
18:25:38 lvig0001@ITC02PXKJCG8WP:~/var/src/wordpress (master)$ docker info
Containers: 55
 Running: 2
 Paused: 0
 Stopped: 53
Images: 195
Server Version: 18.09.3
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: e6b3f5632f50dbc4e9cb6288d911bf4f5e95b18e
runc version: 6635b4f0c6af3810594d2770f662f34ddc15b40d
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker Desktop
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.855GiB
Name: docker-desktop
ID: ZEHF:LEHE:WUJZ:IL2G:KQZO:NKWQ:VGQE:GL3O:BAEZ:GCW2:4OBQ:JOZJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 38
 Goroutines: 68
 System Time: 2019-04-17T16:25:41.548441263Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 docker.synchronoss.net
 localhost:5000
 127.0.0.1:5000
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Comment by thaJeztah** [comment]
Looks like the machine resolves to the IPv6 address for localhost; `dial tcp [::1]:5000`. Does pushing to `127.0.0.1:5000` work?

**Comment by lviggiano** [comment]
@thaJeztah  I would say no: "connection refused"

**Comment by thaJeztah** [comment]
Oh! I see you're running on Docker for Mac; I think something changed, and localhost / 127.0.0.1 is not proxied in the VM, so you'll have to use `host.docker.internal` instead.

That domain is not in the default list of insecure-registries though, so if you haven't set-up TLS for that registry, you need to update the daemon configuration and add it there;

Either through the configuration panel:

<img width="500" alt="Screenshot 2019-04-18 at 12 11 52" src="https://user-images.githubusercontent.com/1804568/56354106-3e233800-61d3-11e9-8a26-33848479c2e2.png">

Or by editing `~/.docker/daemon.json`;

```json
{
  "insecure-registries": ["host.docker.internal:5000"],
  "experimental" : true,
  "debug" : true
}
```


After that (the daemon needs a restart/reload to pick up the configuration);

```bash
docker tag busybox host.docker.internal:5000/busybox:latest

docker push host.docker.internal:5000/busybox:latest

The push refers to repository [host.docker.internal:5000/busybox]
0b97b1c81a32: Pushed 
latest: digest: sha256:f79f7a10302c402c052973e3fa42be0344ae6453245669783a9e16da3d56d5b4 size: 527
```


@djs55 @chris-crone I think this changed recently (saw a discussion somewhere); perhaps this needs a mention in the documentation? Also; should we / can we add `host.docker.internal` to the default list of insecure registries on Docker Desktop? (following the same reasoning for having `127.0.0.1` and `localhost` in the default list)?

**Comment by lviggiano** [comment]
Thank you so much; I'll try that asap. It makes sense.

**Comment by JiaweiZhuang** [comment]
Hitting the same issue on Mac. Adding `host.docker.internal:5000` to insecure-registries fixed the problem. Also need to restart Docker (https://stackoverflow.com/a/44555371)
