### ISSUE TITLE
running_ssh_service.Dockerfile doesnt work on latest ubuntu (16.04)

### ISSUE THREAD

**Issue by rafiqkattangere** [docker/docker#23621]
The documentation example of ssh server doesn't work on 16.04. Can you please fix the Dockerfile!
https://docs.docker.com/engine/examples/running_ssh_service/

Some logs from my tests below. Same docker file sourced from 14.04 (eg_sshd_16)and 16.04 (eg_sshd_16 )

[root@mango3 sshd]# docker ps -a
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS                  PORTS                   NAMES
59dd963a766b        eg_sshd_16            "/usr/sbin/sshd -D"      14 minutes ago      Up 14 minutes           0.0.0.0:32788->22/tcp   test_sshd_16
bdef81d7566f        eg_sshd_14            "/usr/sbin/sshd -D"      37 minutes ago      Up 37 minutes           0.0.0.0:32787->22/tcp   test_sshd_14
[root@mango3 sshd]#
[root@mango3 sshd]# ssh root@mango3 -p 32787   ----  *** Login Works ****
root@mango3's password:
Welcome to Ubuntu 14.04.4 LTS (GNU/Linux 3.10.0-123.el7.x86_64 x86_64)

Documentation:  https://help.ubuntu.com/
Last login: Thu Jun 16 09:36:08 2016 from mango3.in.rdlabs.hpecorp.net
root@bdef81d7566f:~# exit
logout
Connection to mango3 closed.
[root@mango3 sshd]#
[root@mango3 sshd]#
[root@mango3 sshd]#
[root@mango3 sshd]# ssh root@mango3 -p 32788    ----  *** Login Doesn't Works ****
root@mango3's password:
Permission denied, please try again.
root@mango3's password:
Permission denied, please try again.
root@mango3's password:
Permission denied (publickey,password).
[root@mango3 sshd]#
[root@mango3 sshd]#

**Comment by mlaventure** [comment]
The Dockerfile is meant for ubuntu trusty (14.04) as shown by the `FROM ubuntu:14.04` line and as such is not broken.

If you want to make the same example on Xenial (16.04) you can replace:
`RUN sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config`

with

`RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config`

**Comment by smileart** [comment]
It would be even better to actualise the documentation article itself, wouldn't it? Found this one by googling 🖖🏻

**Comment by thaJeztah** [comment]
@smileart I updated the example in https://github.com/docker/docker/pull/26699

**Comment by smileart** [comment]
@thaJeztah Great! Thank you. Definitely will help someone. 👍

**Comment by rafiqkattangere** [comment]
Super. Thanks. This helps.

**Comment by thaJeztah** [comment]
@smileart @rafiqkattangere please be aware that that example is just for "illustrational" purposes; in most cases you don't _need_ an SSH service in your containers; for debugging / ad-hoc access to the container, `docker exec` will be a better solution

**Comment by smileart** [comment]
@thaJeztah yep, sure, needless to say. Thank you.
