### ISSUE TITLE
docker swarm leave should not kill my running containers

### ISSUE THREAD

**Issue by samoht** [docker/docker#23629]
Or at least it should warm me.

**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   1f136c1
 Built:        Wed Jun 15 05:11:00 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   1f136c1
 Built:        Wed Jun 15 05:11:00 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 70
Server Version: 1.12.0-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 111
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: default
Default Runtime: default
Kernel Version: 4.2.0-36-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.56 GiB
Name: emu
ID: LKRP:5O4R:KBMJ:MAMD:BDVP:RUTH:SDKP:UNOZ:G44Q:3H3E:HMZ3:5LTH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Steps to reproduce the issue:**
1. run some containers
2. `docker swarm join <random-address`. As the address is unknown, this fails. This let the swarm in an inconsistent state (see #23611)
3. `docker swarm leave` to fix the inconsistent state

**Describe the results you received:**

all your initial containers are killed

**Describe the results you expected:**

either don't kill my containers or at least tell me that you will do it. So I can abort the operation.

**Comment by stevvooe** [comment]
Just clarifying: we do expect this to kill any running container tasks, as they will be rescheduled on the cluster.

**Comment by tonistiigi** [comment]
@stevvooe Yes, there is a bug atm when leaving from a state where `NodeID` has not been acquired yet. Then it fails to identify what containers were started by swarm.
