### ISSUE TITLE
Bug: docker daemon failing to start

### ISSUE THREAD

**Issue by shishir-a412ed** [docker/docker#23630]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6
 Git commit:   6253c29
 Built:        Thu Jun 16 12:29:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6
 Git commit:   6253c29
 Built:        Thu Jun 16 12:29:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.12.0-dev
Storage Driver: devicemapper
 Pool Name: docker-8:19-16121929-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 271.3 MB
 Data Space Total: 107.4 GB
 Data Space Available: 107.1 GB
 Metadata Space Used: 757.8 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.109 (2015-09-22)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: default
Default Runtime: default
Kernel Version: 4.4.9-300.fc23.x86_64
Operating System: Fedora 23 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.72 GiB
Name: dhcp-10-19-62-127.boston.devel.redhat.com
ID: M4W2:KN7L:WVHC:KGXZ:ZNAN:CJJJ:5PWS:V7VV:GPHO:65Y3:4UEP:MCUX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: shm32
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Start the docker daemon (dockerd)
2.
3.

**Describe the results you received:**
Starting docker daemon give me this error message:
 FATA[0001] Error starting daemon: Error initializing network controller: Error creating default "bridge" network: cannot create network c66222aba32575ef83c41187d5980d2f48129c37592915051cfd7b4611353e44 (docker0): conflicts with network a9d637c2a4994c3e19082046092910ba75a3700ce17f05cbc10f6141f565d066 (docker0): networks have same bridge name 

**Describe the results you expected:**
Docker daemon should start successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by shishir-a412ed** [comment]
@LK4D4 gave me a workaround.
`rm -rf /var/lib/docker/network` and restart daemon.

**Comment by LK4D4** [comment]
ping @sanimej @mavenugo

**Comment by justincormack** [comment]
Looks like the same issue as https://github.com/docker/docker/issues/23622

**Comment by sanimej** [comment]
@shishir-a412ed Did you just upgrade to 12.0-dev and ran into this issue or you upgraded to 12.0-dev, went back to an earlier version and moved to 12.0-dev again ? Currently we have a theory for this to happen in the latter scenario.

**Comment by shishir-a412ed** [comment]
@sanimej 
I just build the docker upstream binary from source.
N Start the docker daemon manually (not using systemd unit file).

**Comment by vitassecuriti** [comment]
its help for me
List all network

$ip a
If you see the bridge with br-a675c47764eb and its status is down,delete it

$brctl delbr br-a675c47764eb
Then restart docker

$service docker restart
Run docker-compose Again
