### ISSUE TITLE
journald logging driver records all stderr output with PRIORITY=3 (error)

### ISSUE THREAD

**Issue by mkocikowski** [docker/docker#23645]
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:54:25 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:54:25 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 6
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-35-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.675 GiB
Name: ip-10-10-100-183
ID: CE6F:PVQX:JPQP:XYV3:U2OL:JXUQ:CNAX:EFYK:7MJU:ZDTW:RYIQ:NY7L
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
aws, ubuntu 15.10

**Steps to reproduce the issue:**
1. ```docker run --log-driver journald  ubuntu /bin/bash -c 'echo "ok" >&2'```
2.```journalctl -u docker -o json-pretty -r``` and look at `PRIORITY` field
3.

**Describe the results you received:**
when the process in the container writes to stderr, the message shows up in the host journal with priority 3 (error). when process writes to stdout, priority is 6 (debug).

**Describe the results you expected:**
 usually, applications write logs to stderr, not stdout, even though these are not errors. i would expect all messages written to stderr to have priority 6 (debug) unless otherwise indicated?

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by yongtang** [comment]
The priority is set in:
https://github.com/docker/docker/blob/v1.11.2/daemon/logger/journald/journald.go#L86-L91

I think removing `msg.Source == "stderr"` will address the issue and allow both stdout and stderr of the container process to have the priority 6.

**Comment by yongtang** [comment]
@mkocikowski I created a pull request #23711 to address this issue. Please let me know if there are any issues.

**Comment by thaJeztah** [comment]
Closing this per the discussion on https://github.com/docker/docker/pull/23711
