### ISSUE TITLE
Use --live-restore,stop container can not show exited,after restart docker daemon

### ISSUE THREAD

**Issue by adaiguoguo** [docker/docker#23668]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   1f136c1
 Built:
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   1f136c1
 Built:
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 270
 Running: 1
 Paused: 0
 Stopped: 269
Images: 56
Server Version: 1.12.0-rc1
Storage Driver: devicemapper
 Pool Name: docker-253:17-1441795-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 4.847 GB
 Data Space Total: 107.4 GB
 Data Space Available: 47.67 GB
 Metadata Space Used: 26.08 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.121 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /data/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /data/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: default
Default Runtime: default
Kernel Version: 3.10.0-229.11.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.51 GiB
Name: vpcs-testos-2.vm
ID: ZVXC:P2QU:NF2S:YAGX:Q3IM:7AH7:LGA5:KGMM:57JO:YXD4:E265:MR7O
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 docker-registry.tools.elenet.me:5000
 127.0.0.0/8
```

**Steps to reproduce the issue:**
my docker daemon add OPTIONS='--live-restore'
1.docker run a container(healthcheck status is healthy)
2.systemctl stop docker
3.systemctl start docker
4.docker stop $containerId 

**Describe the results you received:**
docker ps 
the container become  no healthcheck
**Describe the results you expected:**
docker ps 
the container become exited

**Comment by justincormack** [comment]
The healthchecks were changed I think to not exit the containers but just generate an event initially, actions on health status will be added later I think. cc @talex5

**Comment by talex5** [comment]
@justincormack that's correct - we don't automatically terminate containers with failing health checks.

A container that previously had a healthcheck will become "no healthcheck" in the period after you asked it to shut down and before it actually exits. I'd expect it to become "exited" after about 10s (when Docker will `kill -9` it).

**Comment by crosbymichael** [comment]
Also this could be related to an issue with systemd and live restore.  My patch for changing the KillMode in systemd should make it into rc2. I would try that when it is release or you can add `KillMode=process` to your service file and see if that makes things exit properly after reloading your daemon.

**Comment by tiborvass** [comment]
It is released https://github.com/docker/docker/releases/tag/v1.12.0-rc2

**Comment by adaiguoguo** [comment]
LGTM @crosbymichael
