### ISSUE TITLE
Failed to restart docker.service 

### ISSUE THREAD

**Issue by ztetfger** [docker/docker#23662]
**Output of `docker version`:**

```
[root@COM240 ~]# docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 18:00:05 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 18:00:05 UTC 2015
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 0
Images: 3
Server Version: 1.9.0
Storage Driver: devicemapper
 Pool Name: docker-253:1-2492958-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: extfs
 Data file: /dev/mapper/vg_docker-docker_data
 Metadata file: /dev/mapper/vg_docker-docker_metadata
 Data Space Used: 7.162 GB
 Data Space Total: 107.4 GB
 Data Space Available: 100.2 GB
 Metadata Space Used: 4.325 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.143 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.1.el7.x86_64
Operating System: ZTE Virtulization Environment i
CPUs: 16
Total Memory: 23.4 GiB
Name: COM240
ID: UYX4:Y2RP:4KKF:NA6P:PZP3:BPGY:QGBW:COZN:BOYE:4LXV:6XL3:7FSW

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
centos

**Steps to reproduce the issue:**
1.systemctl stop docker 
2.rm /var/lib/docker/* -rf
3.systemctl start docker 

**Describe the results you received:**
 [root@host ]# systemctl status docker -l
docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled)
   Active: failed (Result: start-limit) since Fri 2014-10-03 21:31:43 CST; 1s ago
     Docs: https://docs.docker.com
  Process: 9632 ExecStart=/usr/bin/docker daemon -H fd:// --exec-opt native.cgroupdriver=cgroupfs --storage-opt dm.datadev=/dev/mapper/vg_docker-docker_data --storage-opt dm.metadatadev=/dev/mapper/vg_docker-docker_metadata --bip=172.172.0.1/16 --log-level=fatal (code=exited, status=1/FAILURE)
 Main PID: 9632 (code=exited, status=1/FAILURE)

Oct 03 21:31:43 host docker[9632]: time="2014-10-03T21:31:43.302449444+08:00" level=fatal msg="Error starting daemon: error initializing graphdriver: Base Device UUID verification failed. Possibly using a different thin pool than last invocation:exit status 2"
Oct 03 21:31:43 host systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Oct 03 21:31:43 host systemd[1]: Failed to start Docker Application Container Engine.

**Describe the results you expected:**
the docker service is active (running)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
There are some existing issues about this; most likely an issue in the devicemapper storage pool https://github.com/docker/docker/issues?utf8=✓&q=is%3Aissue+%22Base+Device+UUID+verification+failed%22+

Could you look at the existing issues?
