### ISSUE TITLE
ENTRYPOINT problem using single backslashes

### ISSUE THREAD

**Issue by StefanScherer** [docker/docker#23670]
I wanted to try out #22268 using the 

```
# escape=`
```

comment to build better Windows specific Dockerfiles. I tried to create a Java Docker image based on [this blog post](https://alexandrnikitin.github.io/blog/running-java-inside-windows-container-on-windows-server/#comment-2733961037).

But it seems that there is a problem using backslashes in the `ENTRYPOINT` with braces. The cmd shell will be added.

**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   1f136c1
 Built:        Wed Jun 15 04:49:14 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0-rc1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   1f136c1
 Built:        Wed Jun 15 04:49:14 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 23
Server Version: 1.12.0-rc1
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Kernel Version: 10.0 14300 (14300.1030.amd64fre.rs1_release_svc.160603-1734)
Operating System: Windows Server 2016 Datacenter Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 4 GiB
Name: vagrant-2016
ID: QIHN:JA6P:4W5I:ASMZ:2P5G:3VU3:ILQZ:MTN4:ONGA:BOC7:JBRI:N3NB
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Username: stefanscherer
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Windows Server 2016 TP5 running the 1.12.0-rc1 binaries which contain PR 22268 (checked it in the sources)

**Steps to reproduce the issue:**
1. `docker build -t java-backslash -f Dockerfile-with-backslash .`
2. `docker inspect java-backslash`
3. `docker build -t java-no-backslash -f Dockerfile-no-backslash .`
4. `docker inspect java-no-backslash`

### Dockerfile-with-backslash

```Dockerfile
# escape=`
FROM windowsservercore

RUN powershell -Command `
    wget 'http://javadl.oracle.com/webapps/download/AutoDL?BundleId=210185' -Outfile 'C:\jreinstaller.exe' ; `
    Start-Process -filepath C:\jreinstaller.exe -passthru -wait -argumentlist "/s,INSTALLDIR=c:\Java\jre1.8.0_91" ; `
    del C:\jreinstaller.exe

ENTRYPOINT [ "c:\Java\jre1.8.0_91\bin\java.exe" ]
CMD [ "-version" ]
```

### Dockerfile-no-backslash

```Dockerfile
# escape=`
FROM windowsservercore

RUN powershell -Command `
    wget 'http://javadl.oracle.com/webapps/download/AutoDL?BundleId=210185' -Outfile 'C:\jreinstaller.exe' ; `
    Start-Process -filepath C:\jreinstaller.exe -passthru -wait -argumentlist "/s,INSTALLDIR=c:\Java\jre1.8.0_91" ; `
    del C:\jreinstaller.exe

ENTRYPOINT [ "c:/Java/jre1.8.0_91/bin/java.exe" ]
CMD [ "-version" ]
```

**Describe the results you received:**

Building the Docker image `java-backslash` and inspecting it you will see that there is an entrypoint with "cmd", "/S", "C/" and a wrong path to the exe file.

```
            "Cmd": [
                "-version"
            ],
            "Entrypoint": [
                "cmd",
                "/S",
                "/C",
                "[ \"c:\\java\\bin\\java.exe\" ]"
            ],
```

**Describe the results you expected:**

```
            "Cmd": [
                "-version"
            ],
            "Entrypoint": [
                "c:\\java\\bin\\java.exe"
            ],
```

The other Dockerfile without the backslash is just to compare the other resuilt. The forward slashes are not expected to work running a container with such an image.

So the current solution is still using double backslashes in the entrypoint.

**Comment by StefanScherer** [comment]
I also found out with another Dockerfile without that escape and using double backslashes with entrypoint  + cmd and it seems that the containerconfig is wrong:

```Dockerfile
FROM windowsservercore

ENTRYPOINT [ "c:\\java\\bin\\java.exe" ]
CMD [ "-version" ]
```

1. `docker build -t try -f Dockerfile-try .`
2. `docker inspect try`

```
        "ContainerConfig": {
            "Cmd": [
                "cmd",
                "/S",
                "/C",
                "#(nop) ",
                "CMD [\"-version\"]"
            ],
            "Entrypoint": [
                "c:\\java\\bin\\java.exe"
            ]
        },
        "DockerVersion": "1.12.0-rc1",
        "Config": {
            "Cmd": [
                "-version"
            ],
            "Entrypoint": [
                "c:\\java\\bin\\java.exe"
            ]
        }
```

**Comment by justincormack** [comment]
I think the reason is that `ENTRYPOINT` tries to run the line through the json parser to see if it should be interpreted as json or a string. JSON parsing is not affected by `escape`, so you still need the double backslashes to make it valid json.

**Comment by justincormack** [comment]
cc @jhowardmsft

**Comment by jhowardmsft** [comment]
Interesting. I don't think the extra cmd is unique to Windows. The conversion to backslashes is expected though. Will look when I get a chance (after Dockercon now)

**Comment by StefanScherer** [comment]
Thanks for the explanation.

**Comment by thaJeztah** [comment]
ping @jhowardmsft have you had time to look into this? I was going through issues on the milestone

**Comment by jhowardmsft** [comment]
Pretty sure now looking at this closer it's "by design" and exactly as per what Justin put above - the parser doesn't see valid JSON with a single backslash. It's just unfortunate that is the nature of the JSON specification.

**Comment by jhowardmsft** [comment]
(As an aside, perhaps we should make the "is this JSON" interpreting a little smarter on Windows to allow for the backslash escaping. Or even through a new parser directive that doesn't allow the non-JSON fallback if it is ["something"] but not actually JSON eg a 'strictJSON' option :smiling_imp: now that the dockerfile command set is open again :innocent:. But I wasn't signing up for that.... :see_no_evil: :speak_no_evil: :hear_no_evil: )

**Comment by StefanScherer** [comment]
The docs https://docs.docker.com/engine/reference/builder/ have several notes about the exec format and parsing that as an JSON array so I think it's ok as it is now.
