### ISSUE TITLE
[1.12.0-RCx] Replacing the default runtime is confusing

### ISSUE THREAD

**Issue by icecrime** [docker/docker#23699]
When I replace the default runtime with something else:

```
$> dockerd --add-runtime custom=/bin/ls --default-runtime=custom
```

I have both a `default` and a `custom` runtime, but `default` isn't the default. Did that confuse you? Good! Me too.

```
$> docker info | grep Runtimes
Runtimes: custom default
```

In the end, `docker run --runtime=default busybox` is different than `docker run busybox`, which I think is very misleading. Maybe the builtin default should have a name different than default (e.g., `runc` on Linux).

Cc @mlaventure.

**Comment by mlaventure** [comment]
How do you want to call it?

**Comment by mlaventure** [comment]
I can't revert docker info to display which "path" is associated with each runtime too, would remove the confusion from that side.

**Comment by icecrime** [comment]
@mlaventure Why not call it `runc` on linux?

**Comment by icecrime** [comment]
Cc @crosbymichael too.

**Comment by thaJeztah** [comment]
+1 to renaming to something more descriptive (to prevent similar issues as https://github.com/docker/docker/issues/19421).

**Comment by crosbymichael** [comment]
I think calling it `runc` will work fine or `docker-runc` since that is the actual binary that we use
