### ISSUE TITLE
[1.12-rc] docker doesn't schedule tasks when port becomes available

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#23709]
**Steps to reproduce:**

```
docker service create --name web -p 8008:80 nginx:alpine
docker service create --name web2 -p 8008:80 nginx:alpine
```

Tasks for service `web2` cannot be scheduled, because there's a port conflict.
This is expected:

```
docker service ls
ID            NAME  REPLICAS  IMAGE         COMMAND
0neftfcbnqz1  web   1/1       nginx:alpine
cgoyyk7bmy1z  web2  0/1       nginx:alpine
```

Now, remove service `web`:

```
docker service rm web
web
```

The port is no longer in use, so `docker` should be able to schedule tasks
for `web2`, but doesn't:

```
docker service ls
ID            NAME  REPLICAS  IMAGE         COMMAND
cgoyyk7bmy1z  web2  0/1       nginx:alpine
```

*However*, creating a *new* service *does* schedule its tasks:

```
docker service create --name web3 -p 8008:80 nginx:alpine

docker service ls
ID            NAME  REPLICAS  IMAGE         COMMAND
cgoyyk7bmy1z  web2  0/1       nginx:alpine
dqrsepdwyuoc  web3  1/1       nginx:alpine
```

**Expected results**

I'd expect the tasks for `web2` to be scheduled after the conflict was resolved
(so after `web` was removed).

tested on:

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   a7119de
 Built:        Fri Jun 17 22:09:20 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by mrjana** [comment]
@thaJeztah Yes this is indeed a bug. Will fix it.

**Comment by thaJeztah** [comment]
thanks!

**Comment by tiborvass** [comment]
@mrjana is there a reference to a PR or is it still being worked on?

**Comment by mgoelzer** [comment]
@mrjana Should we just refuse to accept the second service?

**Comment by mrjana** [comment]
@tiborvass @mgoelzer https://github.com/docker/swarmkit/pull/1088 fixes it. So after that change we will continue to accept conflicting services but tasks from them will not be schedulable. But once the resource does become available then the service will be usable.

**Comment by thaJeztah** [comment]
relates to https://github.com/docker/docker/issues/24134

**Comment by cpuguy83** [comment]
Closing since this one is resolved!

**Comment by tiborvass** [comment]
For the record, this UX is conflicting with #24134 which is the real issue. The most frequently encountered usecase is publishing the same port twice by human error, and we should error out instead of scheduling the new service once the old one is removed.
