### ISSUE TITLE
seccomp not working on arch linux / kernel 4.6.2?

### ISSUE THREAD

**Issue by vikstrous** [docker/docker#23715]
I had seccomp working with docker at some point on arch linux, maybe on kernel 4.4.x but somehow it no longer works. I haven't figured out why and I could use some help debugging this. I don't see anything relevant in the daemon logs: https://gist.github.com/vikstrous/730fa30d9624c21e309fbb83a61c8f55

**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   b9f10c9
 Built:        Sun Jun  5 23:17:55 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   b9f10c9
 Built:        Sun Jun  5 23:17:55 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.6.2-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.709 GiB
Name: compooter
ID: GKSI:YHZC:YPNI:PAGO:EYPD:AYME:K6BY:BAIH:EBKQ:SOAK:WUFP:6MJM
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 23
 System Time: 2016-06-18T11:24:00.683391057-07:00
 EventsListeners: 0
Username: vikstrous
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Steps to reproduce the issue:**
1. `docker run --cap-add ALL --rm -it alpine sh`
2. `mount -o bind root mnt`

**Describe the results you received:**
success

**Describe the results you expected:**
mount: permission denied (are you root?)

**Additional information you deem important (e.g. issue happens only occasionally):**
```
$ zcat /proc/config.gz | grep seccomp -i
CONFIG_HAVE_ARCH_SECCOMP_FILTER=y
CONFIG_SECCOMP_FILTER=y
CONFIG_SECCOMP=y
```

One more test:

```
$ docker run --rm alpine grep Seccomp /proc/self/status
Seccomp:	0
```

**Comment by thaJeztah** [comment]
Seccomp needs to be enabled at compile time, otherwise it won't be available. Could you report this in the Archlinux issue tracker? We don't ship packages for Archlinux, so this is something that need to be addressed in their build
