### ISSUE TITLE
Renaming a container started by docker start causes error

### ISSUE THREAD

**Issue by lheckemann** [docker/docker#23716]
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:30:35 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:30:35 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 84
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.6.0-1-amd64
Operating System: Debian GNU/Linux stretch/sid
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.59 GiB
Name: computer
ID: F64Q:TS3X:QKTD:H32K:FH7Z:GMHY:43VK:AQK5:EW6T:2TYX:L3XN:KGHG
Docker Root Dir: /home/docker
Debug mode (client): false
Debug mode (server): false
Username: sphalerite
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Bare metal, macbook pro

**Steps to reproduce the issue:**
1. `docker create -ti --name before busybox`
2. `docker start -a before`
3. (in another shell) `docker rename before after`
4. Exit from container in first shell

**Describe the results you received:**
`docker start` outputs `Error: No such container: before` on exit

**Describe the results you expected:**
`docker start` exits without any complaints

**Comment by yongtang** [comment]
@lheckemann I created a pull request #23720  to address this issue. Please take a look and let me know if there are any issues.

**Comment by lheckemann** [comment]
@yongtang That was quick! Thanks.
