### ISSUE TITLE
[1.12-rc2] no easy way to get logs for a service

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#23710]
In 1.12, I can create services, but there's no easy way to get the logs for either the service as a whole (all tasks), or an individual task;

```
docker service create --name web -p 80:80 nginx:alpine

docker service ls
ID            NAME  REPLICAS  IMAGE         COMMAND
bioa2ndrqp3h  web   1/1       nginx:alpine

docker logs bioa2ndrqp3h
Error: No such container: bioa2ndrqp3h

docker service tasks web
ID                         NAME   SERVICE  IMAGE         LAST STATE         DESIRED STATE  NODE
18t5r6j642rhncm76vbc2s8h5  web.1  web      nginx:alpine  Running 7 minutes  Running        moby

docker logs 18t5r6j642rhncm76vbc2s8h5
Error: No such container: 18t5r6j642rhncm76vbc2s8h5
```

Best I could come up with is;

```
docker logs $(docker inspect --format "{{.Status.ContainerStatus.ContainerID}}" 18t5r6j642rhncm76vbc2s8h5)
```

But this only gives me logs for a single task/container

**Comment by thaJeztah** [comment]
adding to the milestone, but probably out of scope for 1.12

**Comment by dgageot** [comment]
Likewise, it's not possible to get the logs for a stack

**Comment by nathanleclaire** [comment]
Yeah, I'd _really_ like to see this.  Debugging is likely to be very difficult without it.

**Comment by nathanleclaire** [comment]
Getting every single log from every single container on demand seems really expensive and prone to failure and generally in logging/monitoring, "imperfect information right now is better than perfect information that never arrives".

Maybe by default, `docker service logs` could go off and gather a tail of logs from the containers in the service which are actually available, and we could expose methods by which to drill down in more specific detail to the areas that seem problematic?  It's worth keeping in mind how `--log-driver` is intended to fit into this, as well.

**Comment by rogaha** [comment]
+1

**Comment by rogaha** [comment]
It would be interesting to have the logs up to the `task/container` level.

**Comment by beverts312** [comment]
This same challenge exists for getting container stats

**Comment by thaJeztah** [comment]
@beverts312 can you open a new issue for that?

**Comment by beverts312** [comment]
@thaJeztah  sure
#24597

**Comment by stevvooe** [comment]
@thaJeztah Should this be closed?

If we are expecting `docker service logs`, there is no way for that to get in for 1.12.

**Comment by thaJeztah** [comment]
@stevvooe guess we need some docs, and an issue for tracking `docker logs` in Swarm mode, I'm good with closing this one.

For those reading; we know support log-drivers for services, so logs can be sent to a log driver, but reading the logs requires you to collect those logs / use a driver that provides log-aggregation.

**Comment by thaJeztah** [comment]
opened https://github.com/docker/docker/issues/24812, and https://github.com/docker/docker/issues/24813

**Comment by aelsabbahy** [comment]
Here's the hack I used in [miniswarm](https://github.com/aelsabbahy/miniswarm) to tail all tasks of a service:

```bash
# View logs of service
cmd_logs() {
  fail_if_not_connected_to_swarm
  while read line; do
    node=$(sed -e 's/^[^ ]*[ _]*[^ ]* [^ ]* *\([^ ]*\).*/\1/' <<<$line || tue)
    name=$(sed -e 's/^[^ ]*[ _]*\([^ ]*\).*/\1/' <<<$line || tue)
    id=$(sed -e 's/^\([^ ]*\).*/\1/' <<<$line || tue)
    [[ $2 == "-f" ]] && opts="-f"
    (
    eval "$(docker-machine env "$node")"
    docker logs $opts "${name}.${id}" 2>&1 | line_prefix "${node} ${name}.${id}"
    ) &
    add_last_pid
  done < <(docker service ps "$1" | tail -n +2)
  wait_for_pids
}
```

And here's what it looks like in action: https://youtu.be/in1ItGKDr98?t=5m15s

A `docker service logs [-f]` would be a great addition to the `service` abstraction.

**Comment by pcgeek86** [comment]
Thanks for pushing for this @thaJeztah
