### ISSUE TITLE
[1.12-rc2] docker stack tasks and docker stack rm silently ignore invalid stack names

### ISSUE THREAD

**Issue by dgageot** [docker/docker#23727]
In 1.12, I can create list the tasks of a stack with:

```
$ docker stack tasks STACK.
```

When passed an invalid stack name, the output gives no error message. It should say that the stack does not exist.

```
$ docker stack tasks WHATEVER_42
ID  NAME  SERVICE  IMAGE  LAST STATE  DESIRED STATE  NODE
```

Likewise, `docker stack rm UNKNOWN_STACK` succeeds without any error message.

**Comment by allencloud** [comment]
Stack is a concept abstracted above service level in docker's service and swarmkit, currently it is only stored in service's labels things or something like that.
Still a bug docker engine should fix.

**Comment by dnephin** [comment]
`tasks` is like `ps`, it doesn't error when there are no items to list. This is the correct behaviour.

I've made an argument for why I think this remove behaviour  is correct here:https://github.com/docker/docker/pull/24051#issuecomment-229199914

Maybe it makes sense to say "nothing was removed" for that case, but I don't think an error exit status code is correct.
