### ISSUE TITLE
Feature request: separate registry from tag

### ISSUE THREAD

**Issue by pcgeek86** [docker/docker#23748]
Right now, an image "tag" includes its registry location. I would propose separating this out, so that the registry location is not included in the tag. The tag should be independent from where the image is stored. Having the registry location stored as part of the image tag complicates image management commands, for example, pulling from the Docker Hub, and pushing the same image to a different registry.

Currently:

```
docker pull wordpress
docker tag wordpress https://registry:5000/wordpress
docker push
```

Proposed:

```
docker pull wordpress
docker push wordpress --registry https://registry:5000
```

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by stevvooe** [comment]
@pcgeek86 I assume when you say "tag", you mean "image name". This is known problem with docker. Addressing it is subtlety complex.

There are number of issues discussing this concept. Typically, we discuss this under the topic of decoupling naming and location, which is usually discussed in docker/distribution project.

I'm closing this as a duplicate.

**Comment by pcgeek86** [comment]
@stevvooe Yep, that's what I meant. Sounds good -- which issue is it a duplicate of?

**Comment by stevvooe** [comment]
@pcgeek86 This is a massive arch we are following to address several limitations to get this done. There isn't a single issue that I can point to.

This issue is an example of some of the ongoing work: https://github.com/docker/distribution/pull/1778. We may want to add a road map item, but we are still examining solutions.

If you'd feel more comfortable leaving this issue open, let me know.

**Comment by pcgeek86** [comment]
@stevvooe It's all good mate, we don't need to keep this issue open. I appreciate the work you're doing internally to resolve this. I'll just wait to see what happens in the coming weeks and months. Appreciate the additional info! 🐋 🐳
