### ISSUE TITLE
wrong CPU count after cpu hot-plugging

### ISSUE THREAD

**Issue by wmark** [docker/docker#23768]
**Applies…**

… to all Docker versions including `1.12.0-rc2`.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

metal

**Steps to reproduce the issue:**
1. Start Docker. (Call `docker info` yourself or by *Docker Swarm*.)
2. Insert or remove CPUs from the system, …
3. … then observe `docker info` not displaying any changed values.

Without a hot-plugging–capable system you could (mask or) offline CPUs to reproduce this:
```bash
printf 0 >/sys/devices/system/cpu/cpu3/online
```

**Describe the results you received:**
Go's `runtime.NumCPU` is used, which gets its data from an initializer at the beginning of process lifetime. Any changes to CPU count do not get reflected by subsequent calls and return values of aforementioned function.

**Describe the results you expected:**
Docker should query the system itself. On Linux and using C you would utilize `sysconf(_SC_NPROCESSORS_ONLN)`.

**Additional information you deem important (e.g. issue happens only occasionally):**
See also docker/swarm#1949 and docker/swarm#1992.

**Comment by thaJeztah** [comment]
ping @mlaventure

**Comment by yongtang** [comment]
@wmark @thaJeztah @mlaventure I created a PR #23955 to try to address this one. Please let me know if there are any issues.

**Comment by wmark** [comment]
Thanks to @dongluochen, @yongtang, @thaJeztah, @jhowardmsft, and @LK4D4 for fixing this!
