### ISSUE TITLE
--logging-opt option in systemd unit file

### ISSUE THREAD

**Issue by warroyo** [docker/docker#23769]
Is it possible to set logging options at the daemon level? fir example from my systemd unit file? I would like to set the max file size and max files at a more global level, rather than having to do it at a per container run level.

are these options available already?

**Comment by thaJeztah** [comment]
Yes, you can set options on the daemon, either by using a drop-in configuration file for systemd, or perhaps easier, by using a daemon.json configuration file; https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file
