### ISSUE TITLE
npm install does not work in OSX, hangs forever

### ISSUE THREAD

**Issue by csaintc** [docker/docker#23771]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:45:29 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 9
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: default
Default Runtime: default
Security Options: seccomp
Kernel Version: 4.4.13-boot2docker
Operating System: Boot2Docker 1.12.0-rc2 (TCL 7.1); HEAD : 52952ef - Fri Jun 17 21:01:09 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: default
ID: X6HE:KMUB:DIZG:WEJE:M2FW:Y6HV:HNIA:PGC6:NYSD:C7O3:ES6T:V2MD
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 24
 Goroutines: 42
 System Time: 2016-06-20T18:11:52.153260243Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I'm on OSX using boot2docker

**Steps to reproduce the issue:**
1. Create a Dockerfile inside of a nodejs project
2. Call npm install inside of the dockerfile
3. Observe

**Describe the results you received:**
It is insanely slow, and constantly freezes, preventing me from building docker images on OSX

**Describe the results you expected:**
The image builds successfully

**Additional information you deem important (e.g. issue happens only occasionally):**
https://github.com/npm/npm/issues/7862 is relevant

**Comment by thaJeztah** [comment]
do you have a minimal npm project to reproduce? is it only for bigger projects, or also for a small project?

**Comment by csaintc** [comment]
Here you are! https://github.com/csaintc/node-docker-issue/tree/master

**Comment by thaJeztah** [comment]
Thanks!

I just tried to reproduce this, but the build actually completed. Reading the linked issue, it's possible this issue is related to VirtualBox.

Have you tried the new "Docker for Mac beta"? It resolves quite some issues, compared to Docker Toolbox (VirtualBox); https://docs.docker.com/docker-for-mac/
