### ISSUE TITLE
[1.12.0-rc2] Remote joining a swarm as a worker than promoting on leader causes management commands to go offline

### ISSUE THREAD

**Issue by jnoller** [docker/docker#23784]
**Output of `docker version`:**

Client (laptop, OSX)
```
$> docker version
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   a7119de
 Built:        Fri Jun 17 22:09:20 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

Server:

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd-unsupported
 Built:        Fri Jun 17 21:21:56 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd-unsupported
 Built:        Fri Jun 17 21:21:56 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

Client:
```
Containers: 78
 Running: 0
 Paused: 0
 Stopped: 78
Images: 51
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 344
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: inactive
Runtimes: default
Default Runtime: default
Security Options: seccomp
Kernel Version: 4.4.13-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.954 GiB
Name: moby
ID: AX3N:B5KC:6TY6:V5UW:5MAH:JSD3:PXBN:HC3H:GF3L:GC7L:Z35R:KAIW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 33
 Goroutines: 95
 System Time: 2016-06-20T22:09:37.819574454Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

Server (swarm cluster):
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay host null bridge
Swarm: inactive
Runtimes: default
Default Runtime: default
Security Options: apparmor seccomp
Kernel Version: 4.4.0-24-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 991.1 MiB
Name: docker1
ID: LOR7:TUJW:PXCF:SGKX:L5LU:GQCT:UTRN:G72M:JU32:I24J:JN3R:BN34
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Steps to reproduce the issue:**
1. In this permutation, join the client (laptop) without the manager flag and only 1 leader (that's how the default swarm init and join semantics set it up):

```
$> docker swarm join 104.130.140.254:2377
This node joined a Swarm as a worker.
```
2. Perform a `docker node ls` on the manager and promote the new worker:
```
root@docker1:~# docker node ls
ID                           NAME     MEMBERSHIP  STATUS  AVAILABILITY  MANAGER STATUS
1jkzrkblwbdig3l5u29997n00 *  docker1  Accepted    Ready   Active        Leader
3vidt312rbiiq5noisxnw138d    docker3  Accepted    Down    Active        
88wm55i4nn1ojs4uekvgcod2g    docker2  Accepted    Ready   Active        
8vyhfiqj4sh7pwz0yc15gt599    docker4  Accepted    Ready   Active        
b95i7ys0tv1wuc93gsqbjj6qp    docker3  Accepted    Ready   Active        
caco010vc95cp1ycv38ed83w4    moby     Accepted    Ready   Active        
root@docker1:~# docker node promote caco010vc95cp1ycv38ed83w4
Node caco010vc95cp1ycv38ed83w4 promoted to a manager in the swarm.
```
3. Now try other actions on the **leader**:
```
root@docker1:~# docker swarm update
Error response from daemon: rpc error: code = 4 desc = context deadline exceeded
root@docker1:~# docker node ls
ID                           NAME     MEMBERSHIP  STATUS  AVAILABILITY  MANAGER STATUS
1jkzrkblwbdig3l5u29997n00 *  docker1  Accepted    Ready   Active        Leader
3vidt312rbiiq5noisxnw138d    docker3  Accepted    Down    Active        
88wm55i4nn1ojs4uekvgcod2g    docker2  Accepted    Ready   Active        
8vyhfiqj4sh7pwz0yc15gt599    docker4  Accepted    Ready   Active        
b95i7ys0tv1wuc93gsqbjj6qp    docker3  Accepted    Ready   Active        
caco010vc95cp1ycv38ed83w4    moby     Accepted    Ready   Active        Unreachable
root@docker1:~# docker node demote caco010vc95cp1ycv38ed83w4
Error response from daemon: rpc error: code = 4 desc = context deadline exceeded
root@docker1:~# docker node ls
ID                           NAME     MEMBERSHIP  STATUS  AVAILABILITY  MANAGER STATUS
1jkzrkblwbdig3l5u29997n00 *  docker1  Accepted    Ready   Active        Leader
3vidt312rbiiq5noisxnw138d    docker3  Accepted    Down    Active        
88wm55i4nn1ojs4uekvgcod2g    docker2  Accepted    Ready   Active        
8vyhfiqj4sh7pwz0yc15gt599    docker4  Accepted    Ready   Active        
b95i7ys0tv1wuc93gsqbjj6qp    docker3  Accepted    Ready   Active        
caco010vc95cp1ycv38ed83w4    moby     Accepted    Ready   Active        Unreachable
root@docker1:~# docker node promote 3vidt312rbiiq5noisxnw138d
Error response from daemon: rpc error: code = 4 desc = context deadline exceeded
```

4. On the laptop:
```
$> docker node ls
Error response from daemon: This node is not participating as a Swarm manager
```

**Describe the results you received:**
Effectively, with 1 leader, and joining the swarm as a worker from the remote laptop and then promoting that remote swarm to a leader caused all `swarm` commands / leader operations to start throwing `rpc error: code = 4 desc = context deadline exceeded`

**Describe the results you expected:**
I expected that promotion / demotion would not get stuck and a remote machine would be able to connect as a master without the cluster management going offline.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by tonistiigi** [comment]
When you are joining swarm you don't specify a listening address where the raft APIs will be exposed. This defaults to `0.0.0.0:2377`. Special case `0.0.0.0` will be replaced with default route ip. When you promote node to a manager and this address can't be connected from other nodes the added manager will become unreachable. Since you have 2 nodes and one of them is unreachable you have lost the raft quorum.

Can you test with specifying `--listen-addr` on join. If it still doesn't work please report back with daemon logs.

This is still a bug because we should warn about these cases or maybe fail to promote if `listen-addr` is not set for the node. https://github.com/docker/swarmkit/pull/957 should also make this better.

cc @abronan

**Comment by jnoller** [comment]
@tonistiigi 👍  will test - this is definitely surprising through - the promotion has to fail loudly https://github.com/docker/swarmkit/pull/957 looks like it will help. Leaving the cluster in an unusable state because the silent promotion failure :(

**Comment by kelseyhightower** [comment]
@tonistiigi While I was at CoreOS many users had problems with understand raft membership and the differences between `listen-addr` and `advertised-addr`. What I learned from working with etcd users was that the ability to promote and demote nodes in and out of the consensus pool can cause a lot of problems. In the end we highly recommend users setup a static pool of "masters", say 3 - 5 members, for production setups. I know this seems less than optimal, but the users must be careful not to end up with the majority of nodes in the same failure domain or they would lose quorum like @jnoller did in his examples.

If you still want to support dynamic cluster membership then I would suggest a guide to repair a cluster that loses quorum, because without that people will be stuck with blowing away the entire cluster and starting over.

**Comment by npcode** [comment]
I can't remove a manager node because of this error which occurs when I tried to demote the node.

**Comment by abronan** [comment]
docker/swarmkit#957 was merged, now the node is denied membership if the accepting member cannot ping it back through its advertised address, the membership should thus stay consistent and removal should work. Next vendoring should include the change.

**Comment by thaJeztah** [comment]
@abronan if that resolves this issue, please make sure to add a `fixes ...` in the next vendoring PR

**Comment by abronan** [comment]
@thaJeztah Well vendoring went too fast for me :) feel free to close this issue as this is now included.

**Comment by thaJeztah** [comment]
oh, cool, thanks!
