### ISSUE TITLE
test.docker.com script does not work (403) for RHEL7 host (attempting to install 1.12.0-rc2)

### ISSUE THREAD

**Issue by AlexOugh** [docker/docker#23787]
(this is @nathanleclaire reporting from user's laptop at DockerCon)

`test.docker.com` script does not work for RHEL host.

```console
[ec2-user@ip-192-168-0-215 ~]$ cat /etc/os-release 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.2 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.2"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.2 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.2:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.2"

[ec2-user@ip-192-168-0-215 ~]$ curl -fsSL https://test.docker.com/ | sh
+ sudo -E sh -c 'sleep 3; yum -y -q install docker-engine'
https://yum.dockerproject.org/repo/testing/redhat/7/repodata/repomd.xml: [Errno 14] HTTPS Error 403 - Forbidden
Trying other mirror.
To address this issue please refer to the below knowledge base article

https://access.redhat.com/solutions/69319

If above article doesn't help to resolve this issue please open a ticket with Red Hat Support.



 One of the configured repositories failed (Docker testing Repository),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Disable the repository, so yum won't use it by default. Yum will then
        just ignore the repository until you permanently enable it again or use
        --enablerepo for temporary usage:

            yum-config-manager --disable docker-testing-repo

     4. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=docker-testing-repo.skip_if_unavailable=true

failure: repodata/repomd.xml from docker-testing-repo: [Errno 256] No more mirrors to try.
https://yum.dockerproject.org/repo/testing/redhat/7/repodata/repomd.xml: [Errno 14] HTTPS Error 403 - Forbidden
```

@tianon @mikedougherty who maintains these?  Thanks.

**Comment by thaJeztah** [comment]
looks like it's trying "rhel", but the right URL should be https://yum.dockerproject.org/repo/testing/centos/7/repodata/repomd.xml

(we use the same packages for CentOS and RHEL)

**Comment by thaJeztah** [comment]
ping @kencochrane looks like this was introduced in https://github.com/docker/docker/pull/23124

**Comment by kencochrane** [comment]
@thaJeztah Here is a PR, which I believe, will fix the issue: https://github.com/docker/docker/pull/23817

**Comment by thaJeztah** [comment]
Should be fixed by #23817, but the script has not yet been deployed to test.docker.com

/cc @tiborvass @mlaventure ^^

**Comment by Purple90** [comment]
So that fix didn't work for me due to it not finding the RHEL version. 

@AlexOugh I couldn't find why it was not working like it should, but until there is a fix, I made a few changes to the install script and it worked for me

https://github.com/Purple90/default/blob/master/docker-test-install.sh

**Comment by thaJeztah** [comment]
@Purple90 does https://github.com/docker/docker/pull/23867 work for you? You may have to remove the `/etc/yum.repos.d/docker-` files

**Comment by Purple90** [comment]
@thaJeztah So i am getting this. I actually had written the same if statement that you did a while ago, and also received this error
`+ sudo -E sh -c 'sleep 3; yum -y -q install docker-engine'
https://yum.dockerproject.org/repo/testing/redhat/7/repodata/repomd.xml: [Errno 14] HTTPS Error 403 - Forbidden
Trying other mirror.
To address this issue please refer to the below knowledge base article

https://access.redhat.com/solutions/69319

If above article doesn't help to resolve this issue please open a ticket with Red Hat Support.

https://yum.dockerproject.org/repo/testing/redhat/7/Packages/docker-engine-1.12.0-0.2.rc2.el7.centos.x86_64.rpm: [Errno 14] HTTPS Error 403 - Forbidden
Trying other mirror.

`

**Comment by Purple90** [comment]
Oh, its because you need brackets around lsb_dist
So change it to this
```	fedora|centos|redhat|oraclelinux)
			if [ "${lsb_dist}" = "redhat" ]; then
				# we the centos repository for both redhat and centos releases
				lsb_dist='centos'
			fi
