### ISSUE TITLE
Docker build centos fails on Docker for Mac

### ISSUE THREAD

**Issue by enzor** [docker/docker#23788]
Just tried to run this simple Dockerfile:

```
FROM centos:7
RUN yum update
```

This fails with the following error:

`failed to register layer: rename /var/lib/docker/image/aufs/layerdb/tmp/layer-174610251 /var/lib/docker/image/aufs/layerdb/sha256/5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef: directory not empty`

Tried to pull an ubuntu image and the problem didn't represent itself.
I am using the latest docker for mac version, and this is my output of `docker version` : 

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   a7119de
 Built:        Fri Jun 17 22:09:20 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by rothgar** [comment]
Just to confirm this isn't a problem with docker 1.12.0-rc2 on linux.

It works in Fedora so I'm assuming this is an aufs issue on Mac beta.

```
$ sudo docker version
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        
 OS/Arch:      linux/amd64
```

```
$ sudo docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 228
Server Version: 1.12.0-rc2
Storage Driver: devicemapper
...
```

**Comment by justincormack** [comment]
This works fine for me on Docker for Mac. It may be that you have a corrupted aufs filesystem, it has been known to happen. Can you try doing a factory reset from the Preferences menu and see if this fixes the issue?

**Comment by enzor** [comment]
I can confirm @justincormack : aufs fs was corrupted.
Hard reset on the preferences fixed the problem!
