### ISSUE TITLE
[1.12.0-rc2] Joining a remote node without --manager doesn't require acceptance

### ISSUE THREAD

**Issue by jnoller** [docker/docker#23785]
**Output of `docker version`:**

Client (laptop, OSX)
```
$> docker version
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   a7119de
 Built:        Fri Jun 17 22:09:20 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

Server:

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd-unsupported
 Built:        Fri Jun 17 21:21:56 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd-unsupported
 Built:        Fri Jun 17 21:21:56 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

Client:
```
Containers: 78
 Running: 0
 Paused: 0
 Stopped: 78
Images: 51
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 344
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: inactive
Runtimes: default
Default Runtime: default
Security Options: seccomp
Kernel Version: 4.4.13-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.954 GiB
Name: moby
ID: AX3N:B5KC:6TY6:V5UW:5MAH:JSD3:PXBN:HC3H:GF3L:GC7L:Z35R:KAIW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 33
 Goroutines: 95
 System Time: 2016-06-20T22:09:37.819574454Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

Server (swarm cluster):
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay host null bridge
Swarm: inactive
Runtimes: default
Default Runtime: default
Security Options: apparmor seccomp
Kernel Version: 4.4.0-24-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 991.1 MiB
Name: docker1
ID: LOR7:TUJW:PXCF:SGKX:L5LU:GQCT:UTRN:G72M:JU32:I24J:JN3R:BN34
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Set up a remote swarm cluster - mine is 4 remote nodes, 2 leaders
2. On your laptop, run:
```
$> docker swarm join swarmIP:2377
This node joined a Swarm as a worker.
```
3. On the leader:
```
docker node ls
ID                         NAME     MEMBERSHIP  STATUS  AVAILABILITY  MANAGER STATUS
09y7cdu03xmuwhta0ykvd72gb  docker4  Accepted    Ready   Active        Reachable
1jkzrkblwbdig3l5u29997n00  docker1  Accepted    Ready   Active        Leader
41znz1ntskwvvvea8up52wu0m  docker2  Accepted    Ready   Active        
5bt1bcak4tuzm9a39a7ou9upz  docker3  Accepted    Ready   Active        
7ljlfo1zqcid0mc8cmir64i6g  moby     Accepted    Ready   Active 
```

**Describe the results you received:**

My 'rogue' laptop was able to join the swarm cluster as a worker and shows up in the manager list as ready and active.

**Describe the results you expected:**

I expected the join command to require approval from a manager node as it does in manager mode

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by tonistiigi** [comment]
Our current default automatic acceptance policy is to allow workers and deny managers. This can be configured in `docker swarm init/update` by setting `--auto-accept=none` to turn this feature off or `--auto-accept=worker --auto-accept=manager` to allow everything. Another good way to configure this is to set a `--secret` that needs to be provided on join in addition to the policy rules.

I agree that we should communicate more clearly what implications the default policy has, when you would want to use it and when you definitely want to use some extra options.

@diogomonica @aaronlehmann

**Comment by diogomonica** [comment]
Correct, this works as intended. The default policy has managers on manual-approval, and workers on auto-approval. This can be changed by passing parameters to `docker swarm init` that change that behavior, or using `update` after the fact.

**Comment by jnoller** [comment]
> Correct, this works as intended. The default policy has managers on manual-approval, and workers on auto-approval. This can be changed by passing parameters to docker swarm init that change that behavior, or using update after the fact.
> 
This seems like bad behavior by default (even if intended). Unless you know what you're doing and using a private / encrypted network for your entire swarm, I could just join as a worker and be assigned work/containers/etc. 

It would be fairly trivial to port scan a block for the open swarm/manager ports and join up. IMO the default should be to always manual approve *unless* the manager/init is set to 'auto approve workers'

**Comment by jnoller** [comment]
While I know you're balancing security with ease of bootstrapping, if a rogue worker joins without approval it's automatically trusted. It gets the pem files / certs from the rest of the swarm which means if you *did* identify a rogue worker you'd have to revoke/roll the entire clusters certs.

**Comment by diogomonica** [comment]
@jnoller that is not true: you would only have to remove the node from the cluster, and it would lose immediate access to the swarm. No further revocation/rotation would be necessary.

We believe that this currently provides the best balance between security and usability, and the fact that:
- Swarm mode doesn't come turned on by default, it requires an explicit `init`
- The fact that it is absolutely trivial to both setup further barriers to entry of worker nodes (either `auto-accept` or `secret` will work) on swarm mode initialization, or by using `update` at a later time.
- The fact that to remove illegitimate nodes you simply need to run a `docker node rm`

make this an acceptable default for swarm mode.

This said, we're obviously always looking for more data-points and community feedback, and if auto-accepting worker nodes become an issue, we will change the default.

**Comment by jnoller** [comment]
@diogomonica Sure, it is just a node rm - but first *you have to know there is a rogue worker* - take the on-stage example of spinning up 100 ec2 instances with $N managers. The operator would have to have scripting to identify any worker that came online as 'not what I wanted, who is this chap?' and then rm that node. 

Reason I brought this up is that I think we all learned a bit from the redis stuff (http://antirez.com/news/96) balancing security vs. usability, the defaults allow me to join any swarm, get containers / volumes / services assigned to me and so on.

I know swarm mode isn't on by default - with 1.12 though you've changed some fundamental aspects (for the better) but implicit opt-in for workers seems like a bad idea.

**Comment by diogomonica** [comment]
@jnoller In a setup like that you would be deploying all of your managers and workers inside of a VPC, and the ELBs would expose the ports that should actually be accessible from the outside. This means that no one from the outside would be ever be able to propose itself as a member of the swarm.

Even though I understand your basic point with the redis example: we would rather not have open-membership for anything, I think the major issue with redis was that for the longest time there was no way to secure redis, and when it came, it took significant extra effort to configure. I think you'll agree, using `--secret` on the init for a production swarm is absolutely trivial (or even using `update` after the fact).

As of right now, given the following assumptions:
- `auto-accept`, for worker nodes only, significantly improves the developer/ops experience of setting up a new swarm.
- Worker nodes only listen for tasks, and don't have any ability to control/affect the swarm other than running tasks that were scheduled on them.
- It is easy to reconcile the number of nodes you are supposed to have in the system, and the number of nodes you actually have (`docker node ls | wc -l`).
- It is absolutely trivial to change it/add more barriers to entry (via `--secret` or `--auto-accept none`).
- We can never chose to go to `auto-accept` if at a later time we later decide that it would be a good usability trade-off.
- Good documentation around ensuring that either `auto-accept` is turned off or `secret` is turned on is enough to incentivize people to do the right thing (given that it is trivial to do the right thing).

then I believe we should keep the current defaults.

Additionally, the direction that the swarm functionality (and swarmkit) are going in, is to provide the ability for administrators to configure secure labels on hosts, to allow certain containers from only being deployed on hosts with certain tags. This will further reduce the impact a malicious worker node would have in the system, since it wouldn't be able of receiving any task that leaks anything sensitive.

Finally, let me just say that this is simply my opinion. Even though I work for Docker, it is always up to the community to decide the path that the project should take. If other people share the same view as you, that this ultimately will be prejudicial for the security of Docker users in a way that trumps the benefits of having it open by default, I will open the PR to change it myself :)

Thanks for caring about the security of Docker!

**Comment by kelseyhightower** [comment]
@diogomonica From an ease of use standpoint I agree with you. This totally makes things easy to use. I remember having this same debate at Puppet Labs back in the day. Puppet uses a similar method to handle membership and the decision was made to be secure by default and make `auto-accept` opt-in.

What Puppet Labs found back then is that some users were unaware of the dangers behind `auto-accept` until it was too late. Given how well the UX is around the initial setup I think requiring a single flag to opt-in to `auto-accept` only slightly diminishes the user experience and helps people do the right thing out of the box.

If it's determined that `auto-accept` should be on by default, then I would like to suggest that a warning be printed that you are running in `auto-accept` mode for worker nodes, and also print the commands and/or link to documentation that people can use to lock things down and disable `auto-accept`

**Comment by thaJeztah** [comment]
I'm leaning towards having it disabled by default; adding an `--auto-accept` flag or adding it to the `daemon.json` configuration file sounds like an easy task

> We can never chose to go to auto-accept if at a later time we later decide that it would be a good usability trade-off.

Sorry, I didn't really understand this one; could you explain?

**Comment by tiborvass** [comment]
I like the warning upon `swarm init` cc @sfsmithcha

**Comment by tiborvass** [comment]
cc @diogomonica

**Comment by diogomonica** [comment]
I would really like to avoid warnings. They are essentially shifting the blame to the user by allowing us to claim that "they should have read it". Either it is ok that workers are accepted by default in practice (which I still believe it might be), or it is not. If it is ok, we ship with no warnings, and if it is not, we change the default.

I'll take all the feedback and meet with the security team at docker to reconsider. Thanks everyone for jumping in.

**Comment by tiborvass** [comment]
I'd rather change the default, but if we don't then at least a warning with link to docs about securing the swarm. The current situation is worse than any of those 2 IMHO.

**Comment by johnharris85** [comment]
Related: #24140.

After reading the discussion here I switched my opinion to favour disabling all auto-accept by default. There is a related issue though where `docker swarm update --auto-accept` does not allow you to have a scenario where both are auto-accepted (#24140) .

**Comment by sfsmithcha** [comment]
FWIW, I vote for secure default in swarm `--auto-accept=none`. In the docs we can set auto-accept for workers in the tutorial (where users don't want to deal with acceptance) with a warning there, which is better than an in-product warning.

**Comment by SvenDowideit** [comment]
:heart: for `--auto-accept=none` as default.

imagine I'm at a conference and follow the tutorial on my linux (naively setup) notebook, after hearing how Docker is secure by default...

**Comment by raesene** [comment]
FWIW from the perspective of a security person, I'd argue for `--auto-accept=none` as the default (as has been said it's fairly easy to change), following the principle of least privilege and "secure by default".

My reasoning for this is that when a swarm is initialized the engine starts listening on network ports which are accessible to anyone who can route traffic to that system,  and the managers doesn't get any notification of new workers joining from what I've seen, so a rogue worker may not be easily detected before a workload is sent to them.

I can tell you from my experience that a lot/most people will leave things in their default configuration, so if the default is auto-accept and no value for secret, that's what a lot of people will leave in place.

Then all the pen.testers/researchers will start scanning for 2377/TCP and connecting to any swarms that can be located....

**Comment by praving5** [comment]
Totally agree. Else, we add a check in CIS benchmark to make it `none`.

**Comment by praving5** [comment]
Also, not sure if you looked at it. [Current documentation](https://docs.docker.com/engine/reference/commandline/swarm_init/) says that,
_"By default, both `worker` and `manager `nodes are auto accepted by the cluster."_

**Comment by aaronlehmann** [comment]
Thanks for pointing this out @praving5. I opened #24248 to correct the documentation to match present reality.
