### ISSUE TITLE
What different between .dsb vs .dab?

### ISSUE THREAD

**Issue by netroby** [docker/docker#23791]
On your blog, you said the file extension .dab. but in the github repo, your file extension .dsb

what's different with two file extension?

https://blog.docker.com/2016/06/docker-app-bundle/

![selection_034](https://cloud.githubusercontent.com/assets/278153/16214910/a5a46042-378f-11e6-99f8-4d1ed45ba41d.png)

https://github.com/docker/docker/blob/master/experimental/docker-stacks-and-bundles.md
![selection_035](https://cloud.githubusercontent.com/assets/278153/16214913/bb3ce226-378f-11e6-9fe5-72dfebe093ed.png)

**Comment by thaJeztah** [comment]
It's been a last minute change, the extension will be `.dab`, GitHub repo will be updated soon

/cc @friism @dnephin

**Comment by icecrime** [comment]
It's a documentation issue indeed ,thanks for reporting!

The proper naming is: Distributed Application Bundle (hence `.dab`).

**Comment by mavenugo** [comment]
@icecrime its not just documentation issue. today `docker deploy` assumes `.dsb`. We need a fix in docker/docker to default to `.dab`

**Comment by icecrime** [comment]
@mavenugo Correct, I was assuming the code was changed. My bad! (cc @aanand)

**Comment by aanand** [comment]
Fixed in https://github.com/docker/docker/pull/23945.

**Comment by vdemeester** [comment]
We can close this one :angel:
