### ISSUE TITLE
Docker for Windows doesn't work on Server 2016

### ISSUE THREAD

**Issue by jh86** [docker/docker#23796]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   8e92415
 Built:        Thu May 26 17:08:34 2016
 OS/Arch:      windows/amd64
An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version: open //./pipe/docker_engine: Access is denied.
```

**Output of `docker info`:**

```
An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/info: open //./pipe/docker_engine:
Access is denied.
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMware Fusion Professional 8.1.1 running on host OS X 10.11.5 with [VT-x enabled in guest](https://pubs.vmware.com/fusion-7/index.jsp?topic=%2Fcom.vmware.fusion.help.doc%2FGUID-38178690-1234-4843-B135-4063F9AA73E4.html) Windows Server 2016 TP5

**Steps to reproduce the issue:**
1. Try to install Docker for Windows, using Server 2016 TP5 as host OS
2. Error message during setup "This version of Docker requires Windows 10 Pro, Enterprise, or Education edition with a minimum build number of 10586. Please use Docker Toolbox."
3. Use [Orca](https://david-merritt.blogspot.com/2012/08/force-blocked-software-to-install-onto.html) to modify the InstallDocker.msi file, changing LaunchConditions to `Installed OR (WINDOWSCURRENTBUILD >= 10586 AND (WINDOWSEDITION << "Professional" OR WINDOWSEDITION << "Enterprise" OR WINDOWSEDITION << "Education" OR WINDOWSEDITION << "Server"))`
4. Double click on the modified InstallDocker.msi
5. Run Docker for Windows, observe failure to start

**Describe the results you received:**
Docker for Windows is prevented from installing on Windows Server 2016 TP5. I worked around that.

Once installed, Docker for Windows broke my native [Windows Containers Docker setup](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_server), even after uninstallation.

**Describe the results you expected:**
Docker for Windows installs, and launches without errors on Windows Server 2016.

**Additional information you deem important (e.g. issue happens only occasionally):**
Docker for Windows log attached.
[log-2016-06-20_23-48-06.txt](https://github.com/docker/docker/files/324945/log-2016-06-20_23-48-06.txt)

**Comment by jh86** [comment]
By the way I didn't necessarily expect this to work out of the box, but I am interested to gauge how much support this will get in the future as my $work only uses the server editions...

**Comment by rneugeba** [comment]
Hi @jh86, supporting Docker for Windows on Windows Server 2016 is definitely on our radar and we are tracking it internally. In theory, Docker for Windows should work on Windows Server provided the relevant features are installed but we found several subtle differences between different builds and SKUs.

**Comment by jh86** [comment]
@rneugeba Thanks for the info! Please let me know if I can do anything to help test on my end :)

**Comment by thaJeztah** [comment]
Thanks for reporting @jh86, I'm closing this issue here, because this is being tracked in the internal Docker for Windows issue tracker (which is in a different repository), but feel free to continue the discussion

**Comment by IoBes** [comment]
Hi!
On windows Server 2016 you need to use "Elevation" (Run as Administrator) on your cmd or powershell.

Had same error, till tried to run commands from elevated shell. 
Kitematic - started with administrative rights is working also very well.

Is there a possibility to give rights for other users? Possibly through local user groups?

**Comment by ljt91** [comment]
+1 - Having this issue on Windows 10 - Version 10.0.14393 - Build 14393

**Comment by hungvotrung** [comment]
+1 I had the same error on windows 10 as normal user, only work if i run as administrator

**Comment by ishepherd** [comment]
+1

**Comment by renerchen** [comment]
On windows server 2016, When I run as administrator, it is OK.  but if run another user, the same error:

docker ps
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.25/containers/json: open //./pipe/docker_engine: Access is denied.

Does anyone know why？

**Comment by ServiceFabricBlog** [comment]
If your windows server is a VM, you need to enable nested Hyper-V. 
From the VM host machine
While the VM is NOT running
Powershell Set-VMProcessor -VMName [your vm name] -ExposeVirtualizationExtensions $true

Hope this helps
