### ISSUE TITLE
on docker exec: `rpc error: code = 2 desc = "oci runtime error: exec failed: exit status 1"%`

### ISSUE THREAD

**Issue by typekpb** [docker/docker#23795]
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 34
 Running: 0
 Paused: 0
 Stopped: 34
Images: 931
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker-253:2-9830839-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 40.07 GB
 Data Space Total: 107.4 GB
 Data Space Available: 51.17 GB
 Metadata Space Used: 58.9 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.089 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.18.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Workstation 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.06 GiB
Name: oc4003685312.ibm.com
ID: X3FY:ALEL:WABK:76GP:CLC4:CWZP:QMRM:UBU3:5QGS:G2CF:EXJ6:223O
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Installed on a bare metal

**Steps to reproduce the issue:**
1. in one terminal run: `docker run --name ubuntu -it --rm ubuntu:16.04 /bin/bash` => opens prompt just fine
2. in another terminal run: `docker exec -it ubuntu /bin/bash`

**Describe the results you received:**

recieved error:
````
rpc error: code = 2 desc = "oci runtime error: exec failed: exit status 1"%
````

**Describe the results you expected:**

bash to be opened

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by typekpb** [comment]
the strange thing is that is used to work for me without any problems before, until today :(

**Comment by mark-phillips** [comment]
Same problem here :  

docker exec -it ubuntu /bin/bash
rpc error: code = 2 desc = "oci runtime error: exec failed: exit status 1"126

Running the same docker version on Ubuntu Kernel :  

uname -a
Linux myhostname 4.2.0-38-generic #45~14.04.1-Ubuntu SMP Thu Jun 9 09:27:51 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by typekpb** [comment]
as suggested by: https://github.com/docker/docker/issues/22909#issuecomment-221582629 I ran the script: https://github.com/docker/docker/blob/master/contrib/check-config.sh

output follows:

	warning: /proc/config.gz does not exist, searching other paths for kernel config ...
	info: reading kernel config from /boot/config-3.10.0-327.18.2.el7.x86_64 ...

	Generally Necessary:
	- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
	- CONFIG_NAMESPACES: enabled
	- CONFIG_NET_NS: enabled
	- CONFIG_PID_NS: enabled
	- CONFIG_IPC_NS: enabled
	- CONFIG_UTS_NS: enabled
	- CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled
	- CONFIG_CGROUPS: enabled
	- CONFIG_CGROUP_CPUACCT: enabled
	- CONFIG_CGROUP_DEVICE: enabled
	- CONFIG_CGROUP_FREEZER: enabled
	- CONFIG_CGROUP_SCHED: enabled
	- CONFIG_CPUSETS: enabled
	- CONFIG_MEMCG: enabled
	- CONFIG_KEYS: enabled
	- CONFIG_MACVLAN: enabled (as module)
	- CONFIG_VETH: enabled (as module)
	- CONFIG_BRIDGE: enabled (as module)
	- CONFIG_BRIDGE_NETFILTER: enabled
	- CONFIG_NF_NAT_IPV4: enabled (as module)
	- CONFIG_IP_NF_FILTER: enabled (as module)
	- CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
	- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
	- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
	- CONFIG_NF_NAT: enabled (as module)
	- CONFIG_NF_NAT_NEEDED: enabled
	- CONFIG_POSIX_MQUEUE: enabled

	Optional Features:
	- CONFIG_USER_NS: enabled
	  (RHEL7/CentOS7: User namespaces disabled; add 'user_namespace.enable=1' to boot command line)
	- CONFIG_SECCOMP: enabled
	- CONFIG_CGROUP_PIDS: missing
	- CONFIG_MEMCG_SWAP: enabled
	- CONFIG_MEMCG_SWAP_ENABLED: enabled
	- CONFIG_MEMCG_KMEM: enabled
	- CONFIG_RESOURCE_COUNTERS: enabled
	- CONFIG_BLK_CGROUP: enabled
	- CONFIG_BLK_DEV_THROTTLING: enabled
	- CONFIG_IOSCHED_CFQ: enabled
	- CONFIG_CFQ_GROUP_IOSCHED: enabled
	- CONFIG_CGROUP_PERF: enabled
	- CONFIG_CGROUP_HUGETLB: enabled
	- CONFIG_NET_CLS_CGROUP: enabled
	- CONFIG_NETPRIO_CGROUP: enabled (as module)
	- CONFIG_CFS_BANDWIDTH: enabled
	- CONFIG_FAIR_GROUP_SCHED: enabled
	- CONFIG_RT_GROUP_SCHED: enabled
	- CONFIG_EXT3_FS: missing
	- CONFIG_EXT3_FS_XATTR: missing
	- CONFIG_EXT3_FS_POSIX_ACL: missing
	- CONFIG_EXT3_FS_SECURITY: missing
	    (enable these ext3 configs if you are using ext3 as backing filesystem)
	- CONFIG_EXT4_FS: enabled (as module)
	- CONFIG_EXT4_FS_POSIX_ACL: enabled
	- CONFIG_EXT4_FS_SECURITY: enabled
	- Network Drivers:
	  - "overlay":
	    - CONFIG_VXLAN: enabled (as module)
	- Storage Drivers:
	  - "aufs":
	    - CONFIG_AUFS_FS: missing
	  - "btrfs":
	    - CONFIG_BTRFS_FS: enabled (as module)
	  - "devicemapper":
	    - CONFIG_BLK_DEV_DM: enabled (as module)
	    - CONFIG_DM_THIN_PROVISIONING: enabled (as module)
	  - "overlay":
	    - CONFIG_OVERLAY_FS: enabled (as module)
	  - "zfs":
	    - /dev/zfs: missing
	    - zfs command: missing
	    - zpool command: missing

	Limits:
	- /proc/sys/kernel/keys/root_maxkeys: 1000000

**Comment by typekpb** [comment]
dupplicate of: #15772 and #22705 
ibm sav issue here

@mark-phillips if you're not ibm guy, please open a new bug, as my problem was caused by sav, after disabling it, `docker exec` runs for me

**Comment by mark-phillips** [comment]
Thanks - disabling sav worked for me too.
