### ISSUE TITLE
iptables route traffic from containers to a specific IP (proxy)

### ISSUE THREAD

**Issue by leokhoa** [docker/docker#23807]
We use iptables on some hosts to route packets to a proxy (for whitelisting)
It seems that containers running on hosts use auto generated iptables rules from Docker.

Is there anyway to force containers to forward packets to a specific IP (--dport 80) ?

**Comment by cpuguy83** [comment]
@leokhoa, something like
```
iptables -I PREROUTING -i docker0 ...
```
?

**Comment by thaJeztah** [comment]
closing this because this isn't a bug, but feel free to continue the discussion
