### ISSUE TITLE
Docker service scale bug when remove swarm node

### ISSUE THREAD

**Issue by jorge07** [docker/docker#23806]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:45:29 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:45:29 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 28
 Running: 7
 Paused: 0
 Stopped: 21
Images: 140
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 446
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: active
 NodeID: 9b4wspjwk5m6nhwnmn2n4wsrv
 IsManager: Yes
 Managers: 1
 Nodes: 3
 CACertHash: sha256:ea57da3379505e56c244c135de662752e64eacd61651e3b24ece8b318fe8e7e0
Runtimes: default
Default Runtime: default
Security Options: seccomp
Kernel Version: 4.4.13-boot2docker
Operating System: Boot2Docker 1.12.0-rc2 (TCL 7.1); HEAD : 52952ef - Fri Jun 17 21:01:09 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.097 GiB
Name: default
ID: 2JXI:2JZN:E6HT:TBX2:IJBZ:3AQF:LFQH:PYR7:PZ7A:OK5N:LBO6:SKPD
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 86
 Goroutines: 185
 System Time: 2016-06-21T09:24:52.418449567Z
 EventsListeners: 0
Username: jorge07
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Host OSX 10.11.4
Virtual Box

**Steps to reproduce the issue:**
1.Having a `default` boot2docker machine as swarm master (*docker swarm init*)
2.docker-machine create --driver virtualbox minion1
3.docker-machine create --driver virtualbox minion2
3.eval $(docker-machine env minion1)
4.docker swarm join 192.168.99.100:2377
5.eval $(docker-machine env minion2)
6.docker swarm join 192.168.99.100:2377
7.eval $(docker-machine env default)
8.docker service create --name=nginx --replicas=3 nginx:1.9
9.docker service scale nginx=8
10.docker-machine stop minion2
11.docker service tasks nginx

Result:

![result](https://s31.postimg.org/xpogtfltn/Screen_Shot_2016_06_21_at_11_13_56.png)

**Describe the results you received:**
ESP0047:~ jorge.arco$ docker service ls
ID            NAME   REPLICAS  IMAGE      COMMAND
4kj9dx2nvl4i  nginx  11/8      nginx:1.9
![screenshot](https://s31.postimg.org/52lgjmlh7/Screen_Shot_2016_06_21_at_11_22_40.png)

**Describe the results you expected:**
ESP0047:~ jorge.arco$ docker service ls
ID            NAME   REPLICAS  IMAGE      COMMAND
4kj9dx2nvl4i  nginx  8/8      nginx:1.9

**Additional information you deem important (e.g. issue happens only occasionally):**
I also run `docker service scale nginx=3`
Result ![image](https://cloud.githubusercontent.com/assets/4022187/16224812/0174277c-37a4-11e6-8683-ff2f606c23c5.png)

The containers are well relocated, but the counter is displaying the wrong number of replicas.

**Comment by jorge07** [comment]
I forget add this before:
```
ESP0047:~ jorge.arco$ docker service inspect nginx
[
    {
        "ID": "4kj9dx2nvl4isj11gf0cglx63",
        "Version": {
            "Index": 57
        },
        "CreatedAt": "2016-06-21T09:08:29.727227459Z",
        "UpdatedAt": "2016-06-21T09:22:56.266815953Z",
        "Spec": {
            "Name": "nginx",
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "nginx:1.9"
                },
                "Resources": {
                    "Limits": {},
                    "Reservations": {}
                },
                "RestartPolicy": {
                    "Condition": "any",
                    "MaxAttempts": 0
                },
                "Placement": {}
            },
            "Mode": {
                "Replicated": {
                    "Replicas": 3
                }
            },
            "UpdateConfig": {},
            "EndpointSpec": {
                "Mode": "vip"
            }
        },
        "Endpoint": {
            "Spec": {}
        }
    }
]
```

**Comment by kelseyhightower** [comment]
I can confirm this behavior on my setup. Is there a workaround to clean up tasks that are no longer running, or will swarm clean those up automatically?
