### ISSUE TITLE
`docker-compose scale` down doesn't remove DNS RR when swarm enabled.

### ISSUE THREAD

**Issue by ijc25** [docker/docker#23819]
**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd-unsupported
 Built:        Fri Jun 17 20:52:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd-unsupported
 Built:        Fri Jun 17 20:52:36 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
$ docker info
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 801
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 764
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay bridge host
Swarm: active
 NodeID: 887wohpocxd54vzgb932qwbig
 IsManager: Yes
 Managers: 1
 Nodes: 1
 CACertHash: sha256:4847248b638cba0cbf15b8a92fa692d1b84112de9f6e6484e23e41857ec003f4
Runtimes: default
Default Runtime: default
Security Options: seccomp
Kernel Version: 4.6.0-1-amd64
Operating System: Debian GNU/Linux stretch/sid
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.55 GiB
Name: bokrug
ID: AU33:BO7D:7VGM:MOLB:RSDF:IBRV:GCWT:THHM:OEVM:TX3C:BNLM:WHAR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 49
 Goroutines: 124
 System Time: 2016-06-21T16:12:48.35125235+01:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

@dgageot discovered this issue running on Docker for Mac and produced the repro case and has now reproduced on Docker for Windows and Docker Machine too. I've seen it on native Linux (reported here) and Docker for Mac

**Steps to reproduce the issue:**
1. `docker swarm init`
2. `git clone https://github.com/dgageot/dns && cd dns`
3. `docker-compose build`
4. `docker-compose up -d`
5. Visit http://localhost and observe: `I see 1 java container(s)`
6. `docker-compose scale back=5`, refresh http://localhost and observe: `I see 5 java container(s)`
7. `docker-compose scale back=1`, refresh http://localhost and observe: `I see 5 java container(s)`
8. `docker run --rm -it --net=dns_default alpine nslookup back` resolves to 5 addresses

**Describe the results you received:**

In step *#*7 web page reports 5 java containers and *#*8 resolves to 5 addresses.

**Describe the results you expected:**

In step *#*7 web page reports 1 java container and *#* resolves to 1 address.

**Additional information you deem important (e.g. issue happens only occasionally):**

This is only reproducible after a `docker swarm init`. If step *#*1 is replaced with `docker swarm leave --force` then step *#*7 correctly reports one java container and *#*8 resolves to a single address.

**Comment by ijc25** [comment]
In case it is relevant:
```
$ docker-compose --version
docker-compose version 1.8.0-rc1, build 9bf6bc6
```
(I was originally using `docker-compose version 1.6.2, build 4d72027` which also exposed the issue)

**Comment by dnephin** [comment]
`docker-compose` is not compatible with swarm mode. If you want to try out the experimental bundle you can run:

```
docker-compose bundle
docker stack deploy
```

**Comment by ijc25** [comment]
@dnephin thanks for the response. Is that just a current limitation or is it not something which is on the plan?

If it is never going to be compatible then that should be documented (I looked at the time and couldn't find anything about incompatibility) and really `docker-compose up` and friends should provide a warning or maybe even refuse to run without a `--force`.

Should this be reassigned to `docker-compose` then?

**Comment by thaJeztah** [comment]
This is something that should be discussed in the docker compose issue tracker; please open an issue there (or look for an existing one).

I'll close this issue here, because we cannot address that in this repository, thanks!
