### ISSUE TITLE
--storage-opt about shrinking and increasing

### ISSUE THREAD

**Issue by mYmNeo** [docker/docker#23814]
`--storage-opt` is defined as `Set storage driver options per container`, so I used this option to set device size which was smaller than `baseSize` with devicemapper as storage driver. And it failed to create with an error message saying `devmapper: Container size cannot be smaller than xxx`. The error is defined at https://github.com/docker/docker/blob/master/daemon/graphdriver/devmapper/deviceset.go#L1883. Could somebody explain the reason why shrinking is not allowed?
And there is another problem is that if I increasing the device size, and `docker commit` will not be executed successfully only if I set the `dm.basesize` to the the increased size and restart the daemon. Because the `commit` use the old device size (https://github.com/docker/docker/blob/master/layer/layer_store.go#L278) to save the changes
ping @shishir-a412ed

**Comment by shishir-a412ed** [comment]
@mYmNeo 
For your Ques 1)
For this feature to successfully work, we needed to support both XFS and EXT4 filesystems.
XFS filesystems cannot be shrunk using `xfs_growfs`. they can only be expanded. Moreover only online resizing was allowed i.e the filesystem must be mounted to be grown. To keep the implementation in sync for both the filesystems (xfs, ext4), we only allowed the FS to be expanded.

For your Ques 2) 
Please see the discussion going on in this issue:
https://github.com/docker/docker/issues/22701

Shishir

**Comment by mYmNeo** [comment]
Thank you for the explanation
