### ISSUE TITLE
apt.dockerproject.org/repo/dists/ubuntu-$( lsb_release -s -c )/[In]Release files do not have all components listed

### ISSUE THREAD

**Issue by sprd-bena** [docker/docker#23823]
The current "InRelease" and "Relese" files in the apt.dockerproject.org repository for Ubuntu have missing components. I think they should have to list all three of them: 'main', 'testing', and 'experimental', but currently they only have 'testing' listed, although "Content", "Packages", and etc -files have entries for all three components .

`apt`, apt-get` and `aptitude` seams to ignore that and find the packages from "main" nevertheless (if "main" is in the source.list for the docker repo), but in my case ![aptly](https://github.com/smira/aptly/) complained about "main" was not found. I could workaround that, by forcing the operation, but it still seams that the Release and InRelease file are not build well on your side.

It is may related to your current version change.

**Comment by mlaventure** [comment]
Thanks for the report, I introduced that bug in #23206

Didn't pay attention that the {In,}Release files included the path to all the components.

Will make a PR to fix it shortly.
