### ISSUE TITLE
shim error: Not able to run a new container on docker upstream/master binary.

### ISSUE THREAD

**Issue by shishir-a412ed** [docker/docker#23821]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6
 Git commit:   96a58bd
 Built:        Tue Jun 21 11:48:35 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6
 Git commit:   96a58bd
 Built:        Tue Jun 21 11:48:35 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.12.0-dev
Storage Driver: devicemapper
 Pool Name: docker-8:19-16121929-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 271.3 MB
 Data Space Total: 107.4 GB
 Data Space Available: 107.1 GB
 Metadata Space Used: 757.8 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.109 (2015-09-22)
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null bridge overlay host
Swarm: inactive
Runtimes: default
Default Runtime: default
Security Options: seccomp
Kernel Version: 4.4.9-300.fc23.x86_64
Operating System: Fedora 23 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.72 GiB
Name: dhcp-10-19-62-127.boston.devel.redhat.com
ID: M4W2:KN7L:WVHC:KGXZ:ZNAN:CJJJ:5PWS:V7VV:GPHO:65Y3:4UEP:MCUX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: shm32
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
sh-4.3#  cat /etc/redhat-release 
Fedora release 23 (Twenty Three)

**Steps to reproduce the issue:**
1. docker pull fedora (SUCCESSFUL)
2. docker run -it fedora /bin/bash (ERROR)
3.

**Describe the results you received:**
docker CLI: Error response from daemon: shim error: open pid: no such file or directory.
daemon logs:
http://pastebin.com/iZ5upjjf

**Describe the results you expected:**
New container should start successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by shishir-a412ed** [comment]
ping @mrunalp @runcom

**Comment by mlaventure** [comment]
I cannot reproduce, are you using `systemd` to start the daemon? Judging by the log format, I would assume that yes since it seems to be coming from `journalclt`.

Could you try the same by starting the daemon manually from a terminal and see if the error occurs that way too?

**Comment by shishir-a412ed** [comment]
@mlaventure I can start the daemon manually but not using `systemctl`.

**Comment by thaJeztah** [comment]
Are you sill seeing this? Also, did you install both the docker, and containerd / RunC binaries from the same commit?

**Comment by shishir-a412ed** [comment]
@thaJeztah Yes I am still seeing this error. I just build the latest binaries for docker, containerd, containerd-shim, ctr and runc. And tried to run a container and I am still seeing this error.

I tried it with both fedora and ubuntu (latest, 14.04) just to make sure that this issue is not related to red hat distributions. Getting the same error on both the images.

Shishir

**Comment by mlaventure** [comment]
@shishir-a412ed a few questions :)

- are you using systemd to start docker when doing your test or starting them manually?
- are you starting with an empty `/var/lib/docker` or a populated one?
- is this an upgrade? (i.e. was there a previous version of docker installed before?)
- could you try disabling apparmor? Or for that matter does it happens if you run with `--privileged`?

**Comment by shishir-a412ed** [comment]
@mlaventure 

Answers :)

1) I am using systemd to start docker. `systemctl start docker`. After this when I do `docker run -it --rm fedora /bin/bash` I see this error. I don't see this error if I start `dockerd` manually.
2) I just did `rm -rf /var/lib/docker` and did `systemctl start docker` so that docker creates a fresh workspace (/var/lib/docker).
3) I build it from the upstream source code(dockerd, docker) and copied the binaries to my /usr/bin/.
4) `docker run -it --rm --privileged fedora /bin/bash`  still gives me the same error.

Conclusion: I can reproduce the error on all the above (4) scenarios.

Shishir

**Comment by mlaventure** [comment]
So this has to do with the systemd configuration used it seems.

Could you provide the service files you are using?

**Comment by shishir-a412ed** [comment]
@mlaventure 
http://pastebin.com/1cpUmTj4

**Comment by shishir-a412ed** [comment]
@mlaventure @thaJeztah The problem was with the unit file. I was using an older version of systemd unit file with a newer upstream version of docker. @mrunalp helped me debug the issue.

Closing it now. Thanks !

**Comment by thaJeztah** [comment]
Thanks @shishir-a412ed, good to hear!

**Comment by sibuna25** [comment]
I also got the same error while building the docker image from a dockerfile . Below is how I got it fixed,
1. stop the docker daemon, through pkill or systemctl
2. start the docker with systemctl start docker.service
3. do the docker build

**Comment by Deepak-Poojari** [comment]
Create the below link, That should fix your problem 
# **cd /usr/libexec/docker/**
# **ln -s docker-runc-current docker-runc**
