### ISSUE TITLE
docker service refers to volumes as mounts

### ISSUE THREAD

**Issue by mikesimons** [docker/docker#23833]
This feels like a really trivial thing but it's grating. The `docker service` commands (`create` & `update`) have this in the output:
```
 -m, --mount value                  Attach a mount to the service
```
While accurate, I'm confused as to the change in terminology from `-v, --volume` as used by `docker run`. The syntax of this opt also threw me. I was expecting it to default to a bind mount if I passed `/path:/path` but instead it requires the following `type=bind,source=/path,dest=/path`.

I'm basically just double checking that this isn't an unintentional incongruity because it'll be a PITA to fix after 1.12 is released.

```
docker version
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by hilalr** [comment]
It would be great if 'type=bind,source=/path,dest=/path' was documented more appropriately when running docker service create --help.

**Comment by dweomer** [comment]
Following on @hilalr's comment, it would be great to understand why this new format is even needed.

**Comment by jmalloc** [comment]
Additionally, somewhat confusingly, `type=bind` must be used when mounting named volume, rather than `type=volume`.

**Comment by cpuguy83** [comment]
@jmalloc It should not be the bind type. In fact I would expect using a `bind` with a named volume to error out, will have to check this out.

I did notice that the parsing in rc2  for something like `--mount type=volume,source=test,target=/foo` is a bit off, where the target`/foo` becomes `/foo:ro` in the container.

We did not support `-v` as the syntax is extremely difficult to parse, particularly when Windows paths come into play. Basically every time someone uses `-v` we are guessing, and we don't want to guess.

That said we are still looking at this (certainly the CLI flag is a bit atrocious).

**Comment by mikesimons** [comment]
@cpuguy83 That is fair enough; thanks for the explanation.
Hopefully this new syntax will make it to `docker run` in the future :smiley:

**Comment by cpuguy83** [comment]
I found the issue with the volume not being parsed correctly. #23947

**Comment by mikesimons** [comment]
I think this one can be closed since the incorrect type issue is tracked elsewhere and the original question is answered.
