### ISSUE TITLE
nfs mount point cannot be used as volume

### ISSUE THREAD

**Issue by jimmycmh** [docker/docker#23839]
Docker version 1.11.2

Let's say an nfs is mounted on /mnt/nfs using volume plugin with name mynfs, and trying to use mynfs as a volume to an exsiting directory in the image.
docker run -ti -v mynfs:/var/log ubuntu bash
This command will fail with error "docker: Error response from daemon: chown /mnt/nfs: operation not permitted."

The problem is docker trying to copy files in /var/log to the volume and set the ownership accordingly, but chown on mount point is not permitted.

How to deal with this issue?

**Comment by cpuguy83** [comment]
@jimmycmh `-v mynfs:/var/log:nocopy`

**Comment by thaJeztah** [comment]
I'll close this issue, because I think it's answered, but feel free to continue the discussion

**Comment by pacoxu** [comment]
@cpuguy83  
/home/ubuntu# docker run --name mysql -v paco:/var/lib/mysql:nocopy mysql
chown: changing ownership of '/var/lib/mysql/': Operation not permitted

paco is an nfs volume whose ownship cannot be changed.

Is there a suggested solution?

**Comment by cpuguy83** [comment]
@pacoxu What version of docker are you on?

**Comment by pacoxu** [comment]
@cpuguy83 docker 1.12.

BTW, I run with "--user mysql" to avoid "chown problem".

**Comment by cpuguy83** [comment]
@pacoxu Actually, I think you may be hitting this in the mysql image, not in the docker side.

**Comment by cpuguy83** [comment]
https://github.com/docker-library/mysql/blob/master/5.7/docker-entrypoint.sh#L29

**Comment by pacoxu** [comment]
@cpuguy83， agree.  It is a problem with integration between Docker, MySQL, NFS. 
Root cause is：
1. mysql image use 'chown'
2. nfs doesn't allow ‘chown’ by nfs client.
