### ISSUE TITLE
Clearly use "docker ps -a" isolated in "dead" state of the container

### ISSUE THREAD

**Issue by lxp689689** [docker/docker#23836]
Client:
 Version:      1.8.2-el7
 API version:  1.20
 Package Version: docker-1.8.2-10.el7.x86_64
 Go version:   go1.4.2
 Git commit:   a01dc02/1.8.2
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2-el7
 API version:  1.20
 Package Version:
 Go version:   go1.4.2
 Git commit:   a01dc02/1.8.2
 Built:
 OS/Arch:      linux/amd64

7f1f3764141b        edo.easydo.com:5000/console         "/usr/local/bin/run s"   4 weeks ago         Dead                                                   
3651df4d4971        edo.easydo.com:5000/nginx           "/usr/local/bin/run s"   4 weeks ago         Dead                                                   
f4fc118a32f5        edo.easydo.com:5000/nginx           "/usr/local/bin/run s"   4 weeks ago         Dead                                                   
c26e58082b96        edo.easydo.com:5000/nginx           "/usr/local/bin/run s"   4 weeks ago         Dead                                                   
a2bb6afb24b8        edo.easydo.com:5000/nginx           "/usr/local/bin/run s"   4 weeks ago         Dead                                                   
28ee5ca3dd82        edo.easydo.com/console         "/usr/local/bin/run s"   4 weeks ago         Dead                                                   
e3952f072afd       edo.easydo.com/console         "/usr/local/bin/run s"   4 weeks ago         Dead     

Use "docker ps -a" Access to a lot of "dead" state of the container, "docker rm $ (docker ps -a -q)" Delete display "no such file or directory". But I want to clean up, is there any way

**Comment by cpuguy83** [comment]
You are on an very old version of Docker. Could you update to the latest and test again?

**Comment by thaJeztah** [comment]
closing because it looks this went stale, but happy to reopen if you're still able to reproduce on the current version
