### ISSUE TITLE
`docker ps --help` is unpretty

### ISSUE THREAD

**Issue by AkihiroSuda** [docker/docker#23837]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd-unsupported
 Built:        Fri Jun 17 21:12:28 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Steps to reproduce the issue:**
`docker ps --help`

**Describe the results you received:**

`--` is unneeded and misleading

```
Usage:  docker ps [OPTIONS]

List containers

Options:
  -n, -- int            Show n last created containers (includes all states) (default -1)
  -a, --all             Show all containers (default shows just running)
  -f, --filter value    Filter output based on conditions provided (default [])
      --format string   Pretty-print containers using a Go template
      --help            Print usage
  -l, --latest          Show the latest created container (includes all states)
      --no-trunc        Don't truncate output
  -q, --quiet           Only display numeric IDs
```

**Describe the results you expected:**
The following result seems mostly expected:
```
  -n int                            Show n last created containers (includes all states) (default -1)
```

But I don't think it can be easily implemented without making a modification to `spf13/pflag`.
https://github.com/docker/docker/blob/v1.12.0-rc2/api/client/container/ps.go#L58

So I suggest adding `--some-long-flag` (I dont stick to `--latest-n`) like this:
```
  -n, --latest-n int            Show n last created containers (includes all states) (default -1)
```

**Comment by dnephin** [comment]
Sounds right. It probably doesn't hurt to add a long flag for it instead of patching pflag to support short-only-flags

**Comment by sbose78** [comment]
#dibs

**Comment by sbose78** [comment]
Since there's already a **--latest ** flag available, a **--latest-n** looks uniform.
