### ISSUE TITLE
[Suggestion] "Indexed Job" for `docker service create`

### ISSUE THREAD

**Issue by AkihiroSuda** [docker/docker#23843]
For 1.13 and later, I would like to suggest supporting "indexed jobs" in `docker service create`.

There has been a similar proposal in the Kubernetes community (seems not implemented yet)
https://github.com/kubernetes/kubernetes/blob/v1.3.0-beta.2/docs/design/indexed-job.md

Example:

```bash
$ echo "apple banana cherry" > fruits.txt
$ echo "green yellow red" > colors.txt

$ kubectl run say-fruit --image=busybox \
     --per-completion-env=FRUIT="$(cat fruits.txt)" \
     --per-completion-env=COLOR="$(cat colors.txt)" \
     -- \
     sh -c 'echo "Have a nice $COLOR $FRUIT" && sleep 5'
(pod0) Have a nice green apple
(pod1) Have a nice yellow banana
(pod2) Have a nice red cherry
```
   

The corresponding command line for `docker service` will be like this:

```bash
$ docker service create --replicas 3 --name say-fruit \
     --per-completion-env=FRUIT="$(cat fruits.txt)" \
     --per-completion-env=COLOR="$(cat colors.txt)" \
     --restart-condition=on_failure
     busybox
     'echo "Have a nice $COLOR $FRUIT" && sleep 5' 
```

(I feel the name of `--per-completion-env` is too long and unclear.. I prefer something else like `--scatter`)

I would like to hear thoughts from maintainers about having this feature.
I think we need `docker service exec` and perhaps `docker service cp` as well for taking advantage of the feature.

I believe the feature can be also used for effectively executing `test-integration-cli` in parallel across multiple Docker machines.
So there will be significant benefit for developers :smiley:

**Comment by AkihiroSuda** [comment]
As suggested in #24410, the proposal can be applied to not only batch/cron jobs but also services.

For services, we should support `docker service update --replicas`, but it is impossible to update env vars of running containers.
So I think we should also use some DNS record as well for storing updated index values, but maybe it is too complicated.

**Comment by stevvooe** [comment]
@AkihiroSuda I'm not really into the proposed syntax, either (`--per-completion-env`, ick), but there has been discussion of a batch model. This is a natural evolution but I doubt we'll overload the service command to do it (though, this will be a service orchestration type).

Batch jobs usually have three components:

1. Task parameterization.
2. Re-spawn handling.
3. Completion conditions.

Number 1 is of dubious necessity, as the tasks could parameterize themselves with a work coordinator (Job controller, in hadoop lingo). Number 3 is the tricky aspect for swarm mode, but completely doable. Need to be able to express "Want N tasks to be in `COMPLETED`". This gets complex with the "indexed job" approach. Number 2 requires actual code for more sophisticated scenarios.

The main problem we saw with batch job implementations is that re-spawn is very specific to the job. I haven't looked at the hadoop scheduler in a few years, but there is all sorts of special failure handling. One example is the splitting of data sets on repeated failure when encountering an expensive partition. The "indexed jobs" approach doesn't seem to handle this (correct me if I'm wrong). Most of these applications require specialized schedulers.

**Comment by thaJeztah** [comment]
I'll add this to the 1.13 milestone for consideration

**Comment by AkihiroSuda** [comment]
@stevvooe 
OK, your comment in this issue and your suggestion in https://github.com/docker/docker/issues/24110#issuecomment-232848838 make a sense to me, I'll close this issue and move to #24410 for continuing the discussion
