### ISSUE TITLE
Hi, i think you didn't update yum repo (https://yum.dockerproject.org/repo/main/oraclelinux/7/Packages/) with the new docker version 1.12

### ISSUE THREAD

**Issue by yogiGueta** [docker/docker#23841]
**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by mlaventure** [comment]
Please use the issue description instead of the title next time :).

docker-engine 1.12.0 is currently in RC, it is thus found here: https://yum.dockerproject.org/repo/testing/oraclelinux/7/Packages/
