### ISSUE TITLE
This node is not participating as a Swarm manager

### ISSUE THREAD

**Issue by AlessandroEmm** [docker/docker#23845]
Hey there

Referring to 1.12 and SwarmKit here:

I'm getting 
`This node is not participating as a Swarm manager`
upon issuing docker node ls or docker swarm inspect.

Is there a reason that a non-manager node cannot inspect the swarm or list the nodes in the cluster? Is it just not implemented yet?

Thanks!
Alessandro

**Comment by tonistiigi** [comment]
Only nodes that have promoted to a manager can view and modify cluster state. Worker nodes are only allowed to receive task assignments and report back of their status. To see the information about current worker node's connection status you can use `docker info` that has new swarm section.

This is both for performance and security. Only manager nodes participate on raft consensus. Workers and managers use different types of certificates and can be configured to have different acceptance policies for joining new nodes.

**Comment by AlessandroEmm** [comment]
Thank you for the response. 

Making all the sense.
