### ISSUE TITLE
Shell access from Docker API same Rancher

### ISSUE THREAD

**Issue by toanpt3** [docker/docker#23840]
Hi everybody
As I found out somewhat rancher Shell exec. I learned that they use API docker:
**1**. -X POST curl -H 'Content-Type: application / json' -d '{"AttachStderr":true,"AttachStdin":true,"AttachStdout":true,"Cmd":["bash"],"Container":"c246c902a5b6c91105040b71eafff21a3c3c53644fc9544e7b674ba730e8c86a","Detach":true,"Tty":true}' http: // IP: 1234 / containers / c246c902a5b6c91105040b71eafff21a3c3c53644fc9544e7b674ba730e8c86a / exec
Response: { "id": "09249a06292d642c9bd4576cde3c0d418adba97579b76a0dd9862e83fb03d24b"}
**2**. Next, use the ID for API exec: 234 / exec / 5b537bb916dcbd3362ace80d2bb13c289646f7ef7d7a580996b3f9493582d625 / start} 'http
[Root @ docker ~] # curl -X POST -H 'Content-Type: application / json' -d '{"AttachStderr":false,"AttachStdin":false,"AttachStdout":false,"Cmd":null,"Container":"","Detach":false,"Tty":true} 'Http: // IP: 1234 / exec / 19de3d1dc62c0f56ea1e37501e6a9427bd66fa8f054b0f5b2cc78dd67ee7813a / start.
Pls tech me how to use this link: http: // IP: 1234 / exec / 19de3d1dc62c0f56ea1e37501e6a9427bd66fa8f054b0f5b2cc78dd67ee7813a / start and send same command on docker next.
tks all.

**Comment by thaJeztah** [comment]
The issue tracker is not a general support forum, please use either;

- forums.docker.com
- the #docker IRC channel on freenode
- StackOverflow
