### ISSUE TITLE
Network traffic is trimmed on Docker for Mac

### ISSUE THREAD

**Issue by ksuszka** [docker/docker#23851]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   a7119de
 Built:        Fri Jun 17 22:09:20 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 22
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 64
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null host bridge
Swarm: inactive
Runtimes: default
Default Runtime: default
Security Options: seccomp
Kernel Version: 4.4.13-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.954 GiB
Name: moby
ID: QZOO:4CQ4:WK62:M7Y2:T5NF:4JUL:SIMX:5EL2:7GZD:SDIP:W6I4:FUOW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 30
 System Time: 2016-06-22T11:51:27.609518553Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I had the docker toolbox installed with brew on that machine earlier, but I removed it.

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.3
BuildVersion:	15D21
```

**Steps to reproduce the issue:**
1. Run `docker run --name sinopia -p 4873:4873 -d rnbwd/sinopia`

**Describe the results you received:**
Running `curl localhost:4873` gives result:
```
curl: (52) Empty reply from server
```

**Describe the results you expected:**
Running `curl localhost:4873` should give html page.

**Additional information you deem important (e.g. issue happens only occasionally):**
Running command `docker exec -it sinopia curl localhost:4873` gives expected result, so web server is working correctly.

**Comment by samoht** [comment]
Cannot reproduce:

```
$ docker run --name sinopia -p 4873:4873 -it --rm rnbwd/sinopia
 warn  --- config file  - /sinopia/registry/config.yaml
fs.js:565
fs.write = function(fd, buffer, offset, length, position, callback) {
                                                 ^
Error: ENOENT, no such file or directory '/sinopia/registry/storage/cache/.sinopia-db.json'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.writeFileSync (fs.js:1099:15)
    at LocalData.sync (/sinopia/registry/lib/local-data.js:42:6)
    at Config (/sinopia/registry/lib/config.js:49:22)
    at module.exports (/sinopia/registry/lib/index.js:14:17)
    at afterConfigLoad (/sinopia/registry/lib/cli.js:100:13)
    at Object.<anonymous> (/sinopia/registry/lib/cli.js:63:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by thaJeztah** [comment]
@ksuszka are you still having this issue?

**Comment by thaJeztah** [comment]
@ksuszka also; make sure server in the container is listening on `0.0.0.0:4873`, and not just on `localhost`, because `localhost` refers to the localhost of the *container*, which makes the server only accessible from inside the container

**Comment by ksuszka** [comment]
A word of explanation - I'm not the maintainer of rnbwd/sinopia docker image, just a simple user. The image version I used stopped working correctly after docker upgrade to version 1.12.0-rc2, so I decided to report this. It seems that the maintainer was working on the repository lately and what is now tagged as latest is not the same thing I was using.

If you want to reproduce this issue you can run command:
```shell
docker run --name sinopia -p 4873:4873 -it --rm rnbwd/sinopia@sha256:fe7a8aef9ceea644609fe176c92f339530beb0e63aae38b776bc99b26f2a61a5
```

I've just tested in on version 1.12.0 of docker and same issue occured.

However, it seems that the maintainer found a way to fix this inside container as version tagged as "stable" now is working correctly:
```
docker run --name sinopia -p 4873:4873 -it --rm rnbwd/sinopia@sha256:073a1131fd0070f234f80db1201e1388ad9e578fb714eb61c3ad384cce4d71db
```

So from my point of view you can close this, as I, as a user, have working version now.

**Comment by thaJeztah** [comment]
I'd be interested to hear what the maintainer changed in the image and if it was due to a change in Docker, or a general issue; if something in 1.12 makes older images break, that's a bug

**Comment by thaJeztah** [comment]
Note that I mean something / images that worked on 1.11 (not between release candidates)

**Comment by ksuszka** [comment]
I've just checked this previous version on ubuntu with docker 1.11.1 and same issue occurred, so it seems this is not related to version 1.12, but it was strange coincidence/bad timing of me upgrading docker and retrieving new version of image from the hub.

Sorry to make this false report. I'm closing this issue.

**Comment by thaJeztah** [comment]
Thanks for checking @ksuszka
