### ISSUE TITLE
Different container behavior depending on where the image is built

### ISSUE THREAD

**Issue by wtsidney** [docker/docker#23856]
Using the docker hub image (wtsidney/lastpass-cli:ubuntu), the lpass binary core dumps on a RHEL 7.2 system.  

lpass works without a core dump on ubuntu 14.04 and boot2docker docker hosts.

The automated build of this image  (wtsidney/lastpass-cli:latest) works correctly on RHEL, Ubuntu and boot2docker on my Mac.

My build server is a Ubuntu server - and that build fails to run on RHEL 7.2.

It is also interesting, the image size is different from different build hosts. (https://hub.docker.com/r/wtsidney/lastpass-cli/tags/)

- wtsidney/lastpass-cli:ubuntu - 236 MB
- wtsidney/lastpass-cli:latest (automated build) - 233 MB
- wtsidney/lastpass-cli:boot2docker - 255 MB

**Output of `docker version`:**

RHEL 7.2 SYSTEM: AWS - AMI (ami-775e4f16)
```
[ec2-user@ip-10-52-1-247 ~]$ uname -r
3.10.0-327.el7.x86_64

install docker using https://docs.docker.com/engine/installation/linux/rhel/ by adding the yum repo

rhel$ docker version

Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64
```

UBUNTU 14.04 SYSTEM: AWS - AMI (ami-c0c439a0)
```
ubuntu$ uname -r
3.13.0-85-generic

ubuntu$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

RHEL 7.2 SYSTEM: AWS - AMI (ami-775e4f16)
```
rhel$ docker info
Containers: 14
 Running: 1
 Paused: 0
 Stopped: 13
Images: 14
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: xfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 6.897 GiB
Name: ip-10-52-1-247.us-west-2.compute.internal
ID: CBG4:UV67:IBBF:6ER4:5P3D:4IJC:U4CV:2SFU:G46C:XE4Q:M3YA:OFXZ
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Username: kbroughton
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

UBUNTU 14.04 SYSTEM: AWS - AMI (ami-c0c439a0)
```
$ docker info
Containers: 25
 Running: 22
 Paused: 0
 Stopped: 3
Images: 75
Server Version: 1.10.3
Storage Driver: btrfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local convoy-nfs
 Network: null host bridge
Kernel Version: 3.13.0-85-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.42 GiB
Name: ip-10-2-0-234
ID: OHM4:GYTJ:52BG:MUKF:SWUV:CSKF:OQC4:ICR6:A72F:LY44:ECLL:R63L
Username: kbroughton
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS Availability zone: us-west-2a
RHEL 7.2 SYSTEM: AWS - AMI (ami-775e4f16)
UBUNTU 14.04 SYSTEM: AWS - AMI (ami-c0c439a0)

**Steps to reproduce the issue:**:

You will need an aws ubuntu, aws rhel instance and a free account on lastpass.

```
$ docker run -it wtsidney/lastpass-cli:ubuntu bash
# lpass login bill
Success: Logged in as bill

# lpass ls 
Illegal instruction (core dumped)
```

**Describe the results you received:**

From a gdb session of the core dump: blob_parse is in lastpass-cli github
(https://github.com/lastpass/lastpass-cli)

```
Within the container installed gdb

# gdb /usr/bin/lpass core.<29>
# bt

Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `lpass ls'.
Program terminated with signal SIGILL, Illegal instruction.
#0  0x0000000000405a3f in blob_parse ()
(gdb) bt

#0  0x0000000000405a3f in blob_parse ()
#1  0x0000000000407226 in blob_get_latest ()
#2  0x000000000040782b in blob_load ()
#3  0x000000000040e7c6 in init_all ()
#4  0x000000000040b75a in cmd_ls ()
#5  0x00000000004044ea in main () 
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `lpass ls'.
Program terminated with signal SIGILL, Illegal instruction.
#0  0x0000000000405a3f in blob_parse ()
(gdb) bt
#0  0x0000000000405a3f in blob_parse ()
#1  0x0000000000407226 in blob_get_latest ()
#2  0x000000000040782b in blob_load ()
#3  0x000000000040e7c6 in init_all ()
#4  0x000000000040b75a in cmd_ls ()
#5  0x00000000004044ea in main ()
```

**Describe the results you expected:**

Had expected a listing of the lastpass vault items.

**Additional information you deem important (e.g. issue happens only occasionally):**

- Disabling selinux on the RHEL system had no impact
- Running the container in privileged mode had no impact

**Comment by justincormack** [comment]
Illegal instruction normally means it is built for a different CPU arch. Can you get an assembly dump of the code where it crashes from gdb?

**Comment by thaJeztah** [comment]
ping @wtsidney could you provide the info that @justincormack requested?

**Comment by anusha-ragunathan** [comment]
closing issue, due to no traction from reporter regarding requested information. Reopen once needed info is available.
