### ISSUE TITLE
overlay2: builds succeed even though errors show up in the logs and image fails to run on aufs based daemons

### ISSUE THREAD

**Issue by saada** [docker/docker#23863]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:45:29 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:45:29 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 75
Server Version: 1.12.0-rc2
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: default
Default Runtime: default
Security Options: seccomp
Kernel Version: 4.4.11-23.53.amzn1.x86_64
Operating System: Amazon Linux AMI 2016.03
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.679 GiB
Name: ip-10-0-99-26
ID: EHXQ:TLQP:HDFH:FY3W:ZADZ:PCUE:6GHO:NT5D:VAD3:G7J7:G5S6:7WXO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: saada
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
$ cat /etc/*-release
NAME="Amazon Linux AMI"
VERSION="2016.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2016.03"
PRETTY_NAME="Amazon Linux AMI 2016.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2016.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
Amazon Linux AMI release 2016.03
```

**Steps to reproduce the issue:**
1. Use Overlay2 storage driver
2. Build an image
3. Running the image we just built works locally
4. Push image to Docker Hub
5. Pull image on another machine
6. Run image
7. Errors show up

**Describe the results you received:**
```
$ docker pull myuser/myimage
# ... standard docker pull output
$ docker run --rm -it myuser/myimage echo hello
ERROR: staffingnation-1: stat /var/lib/docker/aufs/mnt/3544186c439d1e460ab7c80c8cf79017eabefbce95baa17ca1245d4e2ac6412a-init/etc/resolv.conf: input/output error
```
The file above `/etc/resolv.conf` changes everytime I run a new container. Sometimes it shows `hostname` sometimes it's `/etc/hosts`. Very random.

**Describe the results you expected:**
```
$ docker pull myuser/myimage
# ... standard docker pull output
$ docker run --rm -it myuser/myimage echo hello
hello
```

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue happens consistently on every image built with `overlay2` storage driver.

Lots of errors look like this in `/var/log/docker` which is the daemon log file during `docker build`.
```
time="2016-06-22T17:13:59.049536229Z" level=error msg="Can't add file /var/lib/docker/overlay2/5fb70902e9dc05dfc9a373c123552620057462ddbe465a1e00f19635e41e44d4/diff/var/cache/apt/srcpkgcache.bin to tar: open /var/lib/docker/overlay2/5fb70902e9dc05dfc9a373c123552620057462ddbe465a1e00f19635e41e44d4/diff/var/cache/apt/srcpkgcache.bin: no such device or address"
```

**Comment by vdemeester** [comment]
/cc @dmcgowan 

@saada something weird because the reported error seems to be about *aufs* : 
`ERROR: staffingnation-1: stat /var/lib/docker/aufs/mnt/3544186c439d1e460ab7c80c8cf79017eabefbce95baa17ca1245d4e2ac6412a-init/etc/resolv.conf: input/output error`

**Comment by saada** [comment]
hey @vdemeester, the image is built and pushed in an 'overlay2' environment. But later fails to run on an aufs environment.

**Comment by vdemeester** [comment]
oh my bad :sweat_smile:

**Comment by saada** [comment]
@vdemeester pas de problème 😂 ! I updated the title to make it a little clearer.

**Comment by vdemeester** [comment]
@saada do you happen to update `/etc/resolv.conf` in your `Dockerfile` ? Just tested out real quick with a simple `Dockerfile` and it worked fine (based on busybox and creating a file in `/etc`).

**Comment by saada** [comment]
@vdemeester I do not touch those files. I am however doing lots of RUN and COPY commands, some of which result in the log errors mentioned above such as
```
time="2016-06-22T17:13:59.049536229Z" level=error msg="Can't add file /var/lib/docker/overlay2/5fb70902e9dc05dfc9a373c123552620057462ddbe465a1e00f19635e41e44d4/diff/var/cache/apt/srcpkgcache.bin to tar: open /var/lib/docker/overlay2/5fb70902e9dc05dfc9a373c123552620057462ddbe465a1e00f19635e41e44d4/diff/var/cache/apt/srcpkgcache.bin: no such device or address"

```

I believe the solution lies in fixing those errors since they only show up when using `overlay2`. None of those error logs show up with old `overlay` driver.

**Comment by dmcgowan** [comment]
@saada: can you share any details about the Dockerfile you are using to build these images, base image and commands which may alter `/var/cache/apt` will be useful. I suspect there is an issue with the tar conversion logic added for `overlay2`.

To confirm
- build/push with `overlay2`, pull with `overlay2` gets failure
- build/push with `overlay2`, pull with `aufs` gets failure
- build/push with `aufs`, pull with `overlay2` succeeds
- build/push with `aufs`, pull with `aufs` succeeds

**Comment by saada** [comment]
Here's the dockerfile...
```
FROM ubuntu:16.04
MAINTAINER Mahmoud Saada

# available ports
EXPOSE 443
EXPOSE 80

# Surpress Upstart errors/warning
RUN dpkg-divert --local --rename --add /sbin/initctl
RUN ln -sf /bin/true /sbin/initctl

# Let the conatiner know that there is no tty
ENV DEBIAN_FRONTEND noninteractive

# Set locale for php56 package to work
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8

# Map host uid and gid with www-data
RUN usermod -u 1000 www-data
RUN usermod -G staff www-data

# Install software requirements
RUN apt-get update && \
    apt-get -y install \
        supervisor \
        cron \
        nginx \
        git \
        curl \
        zip \
        ghostscript \

        # php stuff
        php7.0 \
        php7.0-mbstring \
        php7.0-xml \
        php7.0-dom \
        php7.0-opcache \
        php7.0-json \
        php7.0-fpm \
        php7.0-cli \
        php7.0-mysql \
        php7.0-gd \
        php7.0-intl \
        php7.0-mcrypt \
        php7.0-curl \
        php7.0-zip \

        # version agnostic packages
        php-xdebug \

        # imagick
        imagemagick \
        php-imagick && \

    # cleanup
    apt-get autoremove -y && \
    apt-get clean && \
    apt-get autoclean && \
    echo -n > /var/lib/apt/extended_states && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /usr/share/man/?? && \
    rm -rf /usr/share/man/??_* && \
    rm -rf /tmp/* /var/tmp/*

# send nginx logs to stdout
RUN ln -sf /dev/stdout /var/log/nginx/access.log
RUN ln -sf /dev/stderr /var/log/nginx/error.log


# install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
#RUN chown www-data:www-data /usr/local/bin/composer
RUN mkdir /var/www/.composer
RUN chown -Rf www-data:www-data /var/www/.composer
RUN composer global require "fxp/composer-asset-plugin:~1.0"

#default location
USER www-data
WORKDIR /usr/share/nginx/html

# init app
USER root
COPY ./init ./init
COPY ./environments ./environments
RUN php ./init --env=Production --overwrite=Yes

# run composer
COPY ./composer.lock ./composer.lock
COPY ./composer.json ./composer.json
COPY ./vendor ./vendor
RUN composer install --prefer-dist -n -o

USER www-data
COPY ./robots.txt ./robots.txt
COPY ./backend ./backend
COPY ./common ./common
COPY ./console ./console
COPY ./frontend ./frontend

USER root
RUN chown -Rf www-data:www-data /usr/share/nginx/html
COPY ./init.sh /init.sh
CMD ["bash", "/init.sh"]
```

**Comment by dmcgowan** [comment]
@saada: was able to replicate the issue with /var/cache/apt, seems to be an issue with the archive process when it comes across deleted files is not handling it properly.  I will add a test for that and fix the issues.

Not sure the `/etc/resolve.conf` is the same issue though. What do you mean by "The file above /etc/resolv.conf changes everytime I run a new container. Sometimes it shows hostname sometimes it's /etc/hosts. Very random." Is this only occurring on images built with overlay2 and pulled back on aufs?

**Comment by saada** [comment]
@dmcgowan correct! so if you fix the issue with deleted files not being handled properly, the latter shouldn't happen anymore.
Thank you!

**Comment by danlenar** [comment]
I am still able to reproduce this on 1.12.0-rc4.

**docker info**
`
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 140
Server Version: 1.12.0-rc4
Storage Driver: overlay2
 Backing Filesystem: xfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge overlay host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp selinux
Kernel Version: 3.10.0-327.4.5.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 11.56 GiB
Name: sdlvaas01.vail
ID: X44M:QGVB:6WIH:5J5E:56ZN:QCVC:B6OL:DSCI:4L7S:4SL3:3N2S:5SHO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8`

**My dockerfile:**
`FROM centos:7

RUN mkdir -p /var/lib/test
RUN rm -r /var/lib/test
RUN mkdir -p /var/lib/test

VOLUME ["/var/lib/test"]`

The image is built on Centos 7 with overlay2 as a storage driver, pushed to a registry, and then attempted to run on Docker for Mac with aufs as the storage driver.

docker run -it <image>
**The error on Docker for Mac:**
docker: Error response from daemon: lstat /var/lib/docker/aufs/mnt/872119cd8269b0a4df188defc3949998f475d80b0c76c6c9e2a238609202d993/var: input/output error.`

**The docker daemon logs shows the following:**
`DEBU[0016] container mounted via layerStore: /var/lib/docker/aufs/mnt/fb553ce4066076cba0e34ae39e5d378d67a42a8f90427429ebfbb9fdf9b23790
ERRO[0016] Failed to FollowSymlinkInScope BaseFS /var/lib/docker/aufs/mnt/fb553ce4066076cba0e34ae39e5d378d67a42a8f90427429ebfbb9fdf9b23790 cleanPath /var/lib/test path /var/lib/test lstat /var/lib/docker/aufs/mnt/fb553ce4066076cba0e34ae39e5d378d67a42a8f90427429ebfbb9fdf9b23790/var: input/output error

ERRO[0016] Handler for POST /v1.24/containers/create returned error: lstat /var/lib/docker/aufs/mnt/fb553ce4066076cba0e34ae39e5d378d67a42a8f90427429ebfbb9fdf9b23790/var: input/output error`

**Comment by thaJeztah** [comment]
ping @dmcgowan I'm reopening for now, so that we can investigate ^^

**Comment by dmcgowan** [comment]
@danlenar I haven't been able to reproduce this issue so was wondering if you could help me narrow down what your issue is. Can you confirm that this is working using `devmapper` and `overlay` to build the the image. Also  are all steps in the Dockerfile required to make this error occur? Does it change if you skip the `rm -r` or the second `mkdir -p`.

Also were there any other messages in the log. I think this may be a different issue as the original issue was caused by a bad tar being constructed, I don't see any evidence that based on your log message. You can try pushing the image you are having errors with the hub so we can look to see if there is anything strange inside the layer tars.

**Comment by danlenar** [comment]
@dmcgowan 

Steps on how to reproduce this with just Docker for Mac by switchin

1. Switch storage driver from aufs to overlay on Docker for Mac
```
cd ~/Library/Containers/com.docker.docker/Data/database/com.docker.driver.amd64-linux/etc/docker
sed -i 's/aufs/overlay2/' daemon.json
git commit -m "Switch to overlay2" daemon.json
```
2. Construct Dockerfile
```
FROM centos:7

RUN mkdir -p /var/lib/test
RUN rm -r /var/lib/test
RUN mkdir -p /var/lib/test

VOLUME ["/var/lib/test"]
```
3. Build image and push to registry
```
docker build -t lenar/overlay2
docker push lenar/overlay2
```
4. Switch back to aufs after image is built
```
cd ~/Library/Containers/com.docker.docker/Data/database/com.docker.driver.amd64-linux/etc/docker
sed -i 's/overlay2/aufs/' daemon.json
git commit -m "Switch back to aufs" daemon.json
```
5. Attempt to run the image
```
 docker run -it lenar/overlay2
Unable to find image 'lenar/overlay2:latest' locally
latest: Pulling from lenar/overlay2
8c3d77a518cb: Already exists
e17bd6ad37a4: Already exists
47bfc0426350: Already exists
Digest: sha256:ee37bde847c5ae8a58fd829911e140b9d5f690345f844dbe784f61421ef360b4
Status: Downloaded newer image for lenar/overlay2:latest
docker: Error response from daemon: lstat /var/lib/docker/aufs/mnt/39e6a0140290a8cbe8c36efb80baf3addeb1559be0074ac49bf480e13739cb23/var: input/output error.
```

Docker info for Docker for mac 
```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 4
Server Version: 1.12.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 11
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay host bridge null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.954 GiB
Name: moby
ID: NNWJ:XGYA:NRON:2B6U:LX6D:X6YM:4PD5:EBH4:SINP:3IIQ:INK4:YVBB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 30
 System Time: 2016-07-26T00:23:24.887024366Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: lenar
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 shipyard.vail
 127.0.0.0/8
```

**Comment by dmcgowan** [comment]
Thanks @danlenar, I found the bug. The tar process which converts overlay "whiteouts" to aufs "whiteouts" was not correctly handling sub directories, causing aufs to think that `/var` is removed rather than `/var/lib/test`. Working on a fix now.
