### ISSUE TITLE
Docs: Copying of built binaries in dev container needs change in path

### ISSUE THREAD

**Issue by sbose78** [docker/docker#23870]
In https://docs.docker.com/opensource/project/set-up-dev-env/
---> Task 2. Start a development container
---> Step 7.  Copy the binary to the container’s /usr/bin directory.

`root@a8b2885ab900:/go/src/github.com/docker/docker# cp bundles/1.12.0-dev/binary/docker* /usr/bin`

The source path of this `copy` command is incorrect. The directories created as part of the build artifacts are `bundles/binary-client` and `bundles/binary-daemon`.

So the command(s) should be:

`root@a8b2885ab900:/go/src/github.com/docker/docker# cp bundles/1.12.0-dev/binary-client/docker* /usr/bin/`

and

`root@a8b2885ab900:/go/src/github.com/docker/docker# cp bundles/1.12.0-dev/binary-daemon/docker* /usr/bin/`

**Comment by sbose78** [comment]
#dibs

**Comment by sbose78** [comment]
Should go here https://github.com/docker/opensource/blob/master/docs/project/set-up-dev-env.md

**Comment by sbose78** [comment]
Tracking here https://github.com/docker/opensource/issues/75

**Comment by thaJeztah** [comment]
This was fixed, so closing here. Thanks @sbose78!
