### ISSUE TITLE
docker-machine upgrade fails with permission denied

### ISSUE THREAD

**Issue by ReneVallecillo** [docker/docker#23876]
Expected behavior

`docker-machine upgrade default `
server api gets updated to latest version

Actual behavior

`docker-machine upgrade default
`
I get this:

Downloading /Users/reneval/.docker/machine/cache/boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v1.12.0-rc2/boot2docker.iso...

open /Users/reneval/.docker/machine/cache/boot2docker.iso.tmp619339182: permission denied

Information about the Issue

I tried changing the permissions and ~/.docker owner to user:staff. Same issue

Steps to reproduce the behavior

1. Use docker for mac
2. docker create default --driver xhyve
3. docker-machine env default
4. eval $(docker-machine env default)
5. docker ps
6. You will get: Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23)
7. docker-machine upgrade default
8. Ends with open /Users/reneval/.docker/machine/cache/boot2docker.iso.tmp193116981: permission denied

**Comment by cpuguy83** [comment]
Can you open this against github.com/docker/machine?

Thanks!

**Comment by ReneVallecillo** [comment]
Will do, thanks!
