### ISSUE TITLE
suggested improvements for Debian install doc

### ISSUE THREAD

**Issue by sfsmithcha** [docker/docker#23884]
Feedback on Debian install from John Clements <clements@brinckerhoff.org>

On the Debian install page,

https://docs.docker.com/engine/installation/linux/debian/

Step 3 of the “update your apt” section reads:

 $ apt-get purge lxc-docker*
 $ apt-get purge docker.io*

Unfortunately, on some shells, the globber will get ahold of the asterisk and try to find files in the local directory starting with lxc-docker, which isn’t what you want at all. Instead, this should probably read:

 $ apt-get purge "lxc-docker*"
 $ apt-get purge “docker.io*”

Then, later, you suggest obtaining the signing key for the project with

 $ apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118 E89F3A912897C070ADBF76221572C52609D

This timed out for me repeatedly, but I tried

 $ apt-key adv --keyserver hkp://pool.sks-keyservers.net:80 --recv-keys 58118 E89F3A912897C070ADBF76221572C52609D

… and that worked fine. Dunno if this is a transient failure, but I’m guessing the more general address is probably more robust.

Finally, and this is minor, you might want to replace the calls to `service` with calls to `systemctl`.

Thanks!

John Clements

**Comment by paulmenzel** [comment]
I agree with the feedback.

**Comment by justyntemme** [comment]
I have opened a pull request following the guidelines outlined in the repo. All that lacks is a cute animal, although i think my moose makes up for that. If there is anything I need to fix please let me know and i will fix it asap.

**Comment by sfsmithcha** [comment]
fixed by @justyntemme https://github.com/docker/docker/pull/24659
