### ISSUE TITLE
Docker for Windows: when attempting to mount file as volume, an empty directory with the name of the file is mounted instead

### ISSUE THREAD

**Issue by tniswong** [docker/docker#23900]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   a7119de
 Built:        Fri Jun 17 22:09:20 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 6
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 7
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: default
Default Runtime: default
Security Options: seccomp
Kernel Version: 4.4.13-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.951 GiB
Name: moby
ID: 5YKM:V46N:4I6V:NVCG:2HU7:VZFZ:GQDI:CC2A:5CMO:KWRA:XI6M:6FVT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker for Windows on Windows 10 physical machine

**Steps to reproduce the issue:**
1. `echo test > file.txt`
2. `docker run -it -v (absolute path to file.txt):/file.txt alpine:3.4 sh`
3. `ls -la | grep file.txt`

I have tried both forms of the absolute path:

/C/Users/path/to/file.txt
C:\Users\path\to\file.txt

Both had the same result.

**Describe the results you received:**
`file.txt` is a **Directory**

**Describe the results you expected:**
`file.txt` is a **File** that contains the text `test`

**Additional information you deem important (e.g. issue happens only occasionally):**
Fresh install of Docker for Windows. Docker for Mac does not appear to have this issue.

**Comment by zooldk** [comment]
I have exactly same problem for mac. :-(

**Comment by paulsjv** [comment]
Here's the command I used on my Mac and had it working correctly.

```$ docker run -it -v $(pwd)/file.txt:/file.txt alpine:3.4 sh```

```$ docker --version
Docker version 1.12.0-rc2, build 906eacd, experimental```

**Comment by zooldk** [comment]
hmm yeah you are right. my issue is a bit different. I am mounting two volumes and they are one are empty. but it works when I run it on docker-machine...

**Comment by MBauer83** [comment]
Same here on Windows 10 x64. Docker mounts both files and directories on the host as empty folders.

**Comment by MBauer83** [comment]
In my case, I was able to resolve the issue by creating a new Windows-User with `[LocalMachineName]\dockeruser` as name and some `[a-zA-Z0-9]+` password, logging on and off on the machine with the user, getting back to my main account, resetting credentials in docker for windows and entering the name and credentials of the created dockeruser.

I have tried this from two accounts - one whose name is the email address, containing `@`, the other is a active-directory managed account under the company domain, and contains dashes. Passwords, as per usual standards, also contain special characters. Mounting always failed (and created an empty directory in the container) when credentials from either of these accounts were given. Only by setting up the dockeruser-account with a password matching the simple aLnum-pattern was I able to successfully mount anything.

**Comment by MoOx** [comment]
Facing this issue as well. I am new to docker. Is there any place to find for more info about what is happening? Some logs?

**Comment by cpuguy83** [comment]
If you are getting an empty dir instead of a file, it is because docker does not see the file.
what directory/file are you trying to mount?

**Comment by MoOx** [comment]
FYI I solved my case https://github.com/docker/docker/issues/22981#issuecomment-229271622

**Comment by thaJeztah** [comment]
@tniswong are you still having this issue?

**Comment by thom-nic** [comment]
I'm experiencing this issue on a physical Linux machine (CentOS 7) via docker-machine from a Mac client.  I happen to be specifying my host mount with compose.

My docker-compose.yml looks like this:
```
  db:
    image: postgres:9.4
    expose: [5432]
    volumes:
      - db:/var/lib/postgresql/data
      - ./docker/postgres/initdb.d:/docker-entrypoint-initdb.d
```
... the last line being the host mount in question.  There are one (or more) .sql files inside that folder.  On my client:
```
$ ls -l docker/postgres/initdb.d
total 8
-rw-r--r--  1 thom  staff  124 Aug  3 13:05 grafana.sql
```

However on the server:
```
$ docker-compose run db ls -l /docker-entrypoint-initdb.d/
total 0
drwxr-xr-x. 2 root root 6 Jul 29 21:24 grafana.sql
```

Server:
* `Linux hp-server 3.10.0-327.22.2.el7.x86_64 #1 SMP Thu Jun 23 17:05:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
* Docker version 1.12.0, build 8eab29e

Client:
* `Darwin myhost 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64`
* Docker version 1.12.0, build 8eab29e

Worth noting that if I use plain Docker for Mac with the built-in VM the same host mount works correctly.

**Comment by thaJeztah** [comment]
@thom-nic that's expected; bind mounts are created from the host that the *daemon* runs on (your CentOS machine in this case), not from the *client*. Docker for Mac does some "magic" to allow bind mounting your OS X filesystem; it does so by mirroring the OS X filesystem inside the VM that the daemon runs in. When you use a remote machine (the CentOS box), that magic doesn't happen; the daemon receives a request to bind-mount a path from the host into the container; the path doesn't exist, so it creates an empty directory on that location, and then bind mounts that inside the container.

**Comment by thom-nic** [comment]
Ah thanks I understand now. I assumed they acted the same way the Docker build context does, e.g. they were copied to the daemon host. 

In my case I don't want my containers to depend on the state of the Docker host but I can find another way to run those scripts without the host mount. 

Thanks for clearing that up for me!

**Comment by thaJeztah** [comment]
Closing as I don't think there's a bug here, and the original reporter did not reply

**Comment by Chekote** [comment]
For anyone else having this issue: I ran into this today using Docker Machine on Mac. It seemed to be a problem with the Docker Machine, because everything seemed be setup correctly, and the only thing that resolved the issue was stopping and restarting the Docker Machine VM.

**Comment by FredTingaud** [comment]
@Chekote Thanks for your comment!
Spent 2h trying to understand what was wrong with my docker on linux before seing your comment, restarting the daemon and solving my issue.

**Comment by DaneWeber** [comment]
Happened to me on a Windows 10 host machine. Glad I found this thread, because I reseting to factory defaults cleared it up.

My specific symptom was mounting a volume, seeing files in the directory structure, but the file contents were replaced with nul characters.

**Comment by williamfzc** [comment]
Happened to me on a Windows 10 host machine too. After mounting `/usr/bin/docker` on my container, it became a empty directory and can not be used.

**Comment by disasterovich** [comment]
Have same problem
