### ISSUE TITLE
Docker for Mac installer: admin status not properly detected for LDAP users (in group admin, sudo, etc works)

### ISSUE THREAD

**Issue by maxx** [docker/docker#23904]
**Output of `docker version`:**

Running it within the /Applications path by hand:
```
/Applications/Docker.app/Contents/Resources/bin ./docker --version
Docker version 1.12.0-rc2, build 906eacd, experimental
```

From installer GUI:

```
Administrator privileges are required.

You need administrator privileges on this computer to install Docker. Please login as administrator to install the app, then you can use Docker with standard user accounts.
```

**Output of `docker info`:**

N/A - docker does not install.

Instead, here's proof 'admin' is in my groups output:

```
user@host > ~  groups | grep -oh " admin "
 admin
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This host is an Mac which authenticates off an LDAP service.

**Steps to reproduce the issue:**
1. Find a Mac authenticating off LDAP with Administrator privileges via a network group.
2. Copy Docker.app into /Applications
3. Run Docker.app

**Describe the results you received:**

Installer failed with above message.

**Describe the results you expected:**

I expected it to properly detect my administrator status and install (which it does have privileges to do).  My user has sudo access, is in the admin group, and plenty of other apps are able with administrator requirements. 'admin' is in the output of groups.  Docker for Mac is using some other mechanism to check for admin status which seems to only work for local users.

I tried various things to force the installer into detecting my admin status, but to no avail. I'm not sure what mechanism it uses to detect this status, but it seems to only work for local users.

**Additional information you deem important (e.g. issue happens only occasionally):**

This is consistent - please get in touch for more debug info.

**Comment by maxx** [comment]
If an equivalent environment is not available to reproduce, I'm happy to help test a new check for admin status.  I'm unable to determine how it's actually doing this check.

**Comment by craig2017** [comment]
I'm having the same problem.  I'm on a corporate macbook pro and I have root privileges.  I wonder if its Symantec blocking it.

**Comment by maxx** [comment]
It's not likely Symantec - I don't have that installed.

I believe it's just an issue in the way Docker.app checks for privileges.

I'm also on 10.11 (El Capitan).

**Comment by maxx** [comment]
@craig2017: can you confirm your user is auth'd by LDAP?

**Comment by craig2017** [comment]
We use centrify for mac which could use LDAP or AD.  not really sure how I
could tell.

**Comment by maxx** [comment]
That is probably LDAP/AD.. you would know from whatever systems your admins use to manage accounts.

Regardless, I'm guessing any system that assigns admin group via network (not local users/groups) would be affected.

**Comment by thaJeztah** [comment]
ping @gdevillele I think this issue was resolved, or is this different?

**Comment by gdevillele** [comment]
Thanks a lot for pinging me @thaJeztah !

@maxx @craig2017, Docker for Mac is using posix functions to determine if your are an admin or not, but for some reason, the group/user info is not consistent on some corporate computers. I fixed it in our codebase for the upcoming update of Docker for Mac (beta17), using different posix functions to get the same info you are getting with the `groups` command, but I would like to be sure the issue you are having is exactly the same than the one we are aware of.

Could you please execute this command: `dscl . -read /Groups/admin`,
and check that the line starting with `GroupMembership` lists your username?

Here is what I get on my Macbook. You can see that my user ("gaetan") and the root user are part of the admin group. My guess is that your user is not. (This is what some of our Docker for Mac testers experienced)
```
mbp-gaetan:~ gaetan$ dscl . -read /Groups/admin
AppleMetaNodeLocation: /Local/Default
GeneratedUID: ABCDEFAB-CDEF-ABCD-EFAB-CDEF00000050
GroupMembers: FFFFEEEE-DDDD-CCCC-BBBB-AAAA00000000 6418AFEF-F625-4362-AECD-512E60DD88CE
GroupMembership: root gaetan                               <----------------------------
Password: *
PrimaryGroupID: 80
RealName: Administrators
RecordName: admin BUILTIN\Administrators
RecordType: dsRecTypeStandard:Groups
SMBSID: S-1-5-32-544
```

**Comment by craig2017** [comment]
My username is not there.

Even when i run this as root from the terminal it fails.

**Comment by gdevillele** [comment]
@craig2017 thanks. It looks to be the same issue. It will be fixed with the next update in a couple of days.

**Comment by craig2017** [comment]
awesome, thanks!

**Comment by maxx** [comment]
I have _also_ confirmed that `dscl . -read /Groups/admin |grep GroupMembership` does not list my username.. sounds like this upcoming fix will solve the issue.   Looking forward to it.

**Comment by gdevillele** [comment]
@craig2017 @maxx You are welcome, thanks for your patience. Let's see after the update whether we can close this issue. :)

**Comment by gdevillele** [comment]
@craig2017 @maxx In case you missed it, beta17 has been released and can be downloaded here: https://www.docker.com/products/docker#/mac 

In case you install it, please take the time to tell us if your issue is solved. Thank you 🙂

**Comment by maxx** [comment]
Thank you, I can confirm this release has fixed the problem for me!

**Comment by thaJeztah** [comment]
Thanks for testing @maxx! I'll close this issue, but feel free to comment after I closed

**Comment by craig2017** [comment]
Fixed.  You rock!

Thanks.
