### ISSUE TITLE
Service mounts default to read-only

### ISSUE THREAD

**Issue by aaronlehmann** [docker/docker#23915]
There is a "writable" flag inside a mount definition. Unless writable is explicitly set to true on the CLI when creating or updating the service, the mount will be read-only.

Mounts should probably be read/write by default, with `writable=false` or `readonly=true` to make them read-only if desired.

cc @vieux

**Comment by aaronlehmann** [comment]
Also cc @dnephin

**Comment by dnephin** [comment]
This is by design, but we can still change it if we want to. There was a discussion of this somewhere else, but now I can't find it.

**Comment by jodok** [comment]
+1 got bitten by this as well

**Comment by mgoelzer** [comment]
@stevvooe @cpuguy83

**Comment by cpuguy83** [comment]
Do you think the CLI should default to writable, but keep the API opt-in?

**Comment by cpuguy83** [comment]
Opened #24053 to do this.

**Comment by dnephin** [comment]
I think the CLI and the API should be consistent here, we should change it in the API as well.

**Comment by stevvooe** [comment]
@dnephin @cpuguy83 If we're to do this, we should change the field to `ReadOnly`, across the board.

**Comment by stevvooe** [comment]
Really, I'm fine with keeping API defaulting to read only, however.

**Comment by aaronlehmann** [comment]
I would prefer to avoid an API change during the release candidates if we can. Since the GRPC serialization is stored in raft, a change like Writable -> ReadOnly would break the existing cluster state for anyone who downloaded an earlier -rc and played with it. Not the end of the world, but it wouldn't inspire confidence among early adopters. My vote would be to leave the API as-is, and only change it if we find something we really don't want to be stuck with going forward. Changing the CLI could make sense here, though.
