### ISSUE TITLE
Can't start docker service on archlinux

### ISSUE THREAD

**Issue by Uhsac** [docker/docker#23911]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   b9f10c9
 Built:        Sun Jun  5 23:17:55 2016
 OS/Arch:      linux/amd64
An error occurred trying to connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.23/version: read unix @->/var/run/docker.sock: read: connection reset by peer
```

**Output of `docker info`:**

```
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I'm running on my physical laptop using arch linux and 4.6.2 kernel.

**Steps to reproduce the issue:**
1. `sudo pacman -S docker`
2. `sudo systemctl start docker`
3. `sudo systemctl status docker`

**Describe the results you received:**

Output of `sudo systemctl status docker` :

```
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2016-06-23 22:10:21 CEST; 6s ago
     Docs: https://docs.docker.com
  Process: 3311 ExecStart=/usr/bin/docker daemon -H fd:// (code=exited, status=1/FAILURE)
 Main PID: 3311 (code=exited, status=1/FAILURE)
   Memory: 628.0K
      CPU: 165ms
   CGroup: /system.slice/docker.service

Jun 23 22:10:20 arch systemd[1]: Starting Docker Application Container Engine...
Jun 23 22:10:20 arch docker[3311]: time="2016-06-23T22:10:20.282811322+02:00" level=info msg="New containerd process, pid: 3333\n"
Jun 23 22:10:21 arch docker[3311]: time="2016-06-23T22:10:21.352295979+02:00" level=error msg="There are no more loopback devices available."
Jun 23 22:10:21 arch docker[3311]: time="2016-06-23T22:10:21.352601436+02:00" level=fatal msg="Error starting daemon: error initializing graphdriver: 
Jun 23 22:10:21 arch systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Jun 23 22:10:21 arch systemd[1]: Failed to start Docker Application Container Engine.
Jun 23 22:10:21 arch systemd[1]: docker.service: Unit entered failed state.
Jun 23 22:10:21 arch systemd[1]: docker.service: Failed with result 'exit-code'.
```

**Describe the results you expected:**

A docker daemon that work

**Additional information you deem important (e.g. issue happens only occasionally):**

Hello docker,

Today I tried to run a docker container but noticed that my docker daemon was not running anymore, don't know why. So I start to restart it but as you understand it failed. So I tried to uninstall and remove everything from docker on my laptop. After that I reinstall docker and tried to start docker service but it failed. You can see the output of my command above.

If someone know why this happen or how I can find why it would be great.

Thanks for your time.

**Comment by nathanleclaire** [comment]
I'm surprised to not see graph driver mentioned in message: 

```
Jun 23 22:10:21 arch docker[3311]: time="2016-06-23T22:10:21.352601436+02:00" level=fatal msg="Error starting daemon: error initializing graphdriver: 
```

However, due to the mention of loopback device, I suspect it's picking `devicemapper`.

Couple of things you could try:

1. Just use `overlay` for storage driver by editing the systemd service file (`docker daemon -s overlay ...`) and restarting the service (if your kernel is >=3.18 it will include `overlay`)
1. Patch kernel to use AUFS and do the same for `-s aufs` if `overlay` is not viable
1. Investigate why you have no more loopback devices.  Did you or a program on your system create a bunch of loopback devices that you have not cleaned up?

**Comment by Uhsac** [comment]
Ok I will check what is a loopback devices and find if I can cleaned them tonight. If I can't I will try the overlay solution.

Thanks for your help

**Comment by Uhsac** [comment]
In fact loop/block was not activated in my kernel so I recompile it using default config for my distrib and now it works using overlay. (still don't work with device mapper but I don't care)

**Comment by nathanleclaire** [comment]
:+1:

**Comment by eimifukadaa98** [comment]
ga mau cicigan masih erorrr unit docker.service could not be found!!
