### ISSUE TITLE
"docker service update" does not update commands/args properly

### ISSUE THREAD

**Issue by aaronlehmann** [docker/docker#23924]
Running master (`86d5c7e759e099b2662770be82cf9248ab0df5ba`).

I had a service running `top` with no arguments. When I ran `docker service update 533yymyth264 --command sleep --arg 1000`, it updated the service definition as follows:

```
                "ContainerSpec": {
                    "Image": "busybox",
                    "Command": [
                        "1000"
                    ],
                    "Args": [
                        "top"
                    ]
                },
```

This doesn't look right - I'd expect the following:

```
                "ContainerSpec": {
                    "Image": "busybox",
                    "Command": [
                        "sleep"
                    ],
                    "Args": [
                        "1000"
                    ]
                },
```

Before I updated the service, the `ContainerSpec` was:

```
                "ContainerSpec": {
                    "Image": "busybox",
                    "Args": [
                        "top"
                    ]
                },
```

(Why was `Args` set to top rather than `Command`?)

cc @vieux @dnephin

**Comment by dnephin** [comment]
This is because of the deviation from entrypoint/command -> command/args.

If we set command from the `docker service create` command it will not use the entrypoint it the container, so we need to set `Args`, which basically acts like the old `Cmd`.

**Comment by dnephin** [comment]
Oh, the other part of this is that there is a bug in update 

```
updateSlice("arg", &cspec.Command)
```

That is easy to fix

**Comment by mgoelzer** [comment]
ping @stevvooe

**Comment by stevvooe** [comment]
@dnephin For the classic docker experience, only `Args` should be used. Basically, it is flowed through to `Cmd` directly, which will be used as the entrypoint if the `Entrypoint` is not available. A `--entrypoint` option can be added to allow entrypoint override, which would force setting the `Command` field.

> If we want to change this, I think we should have swarmkit revert to using entrypoint/command like the engine does. Otherwise we're left with this confusing behaviour.

I'm sorry, but entrypoint/cmd is the confusing behavior here. IMHO, entrypoint/cmd is poorly defined and is one of the weak points of Docker.

The best way to think of this is that `Command` replaces the entry command, while `Args` is appended to the default `Command`, which becomes `Command`, if the default `Command` is empty. It's wildly simple.

The command/args approach avoids having to know anything about the image when sending `args` or overriding the entrypoint. From an API perspective, it is much clearer to use and all of the existing CLI behavior can be implemented just as easily, if not more so.

**Comment by dnephin** [comment]
So let's say we add `--entrypoint`, and `--args` to `service update`.
We'll also need to add an `--entrypoint` to `service create`.
And of course `docker run` has `--entrypoint` and (and command, which  is equivalent to args now).

The UX of entrypoint/command hasn't changed (with the very minor exception of renaming command to args, which  is arguably worse in the case where the image doesn't have an entrypoint).

Why introduce the extra logic in the client to support this and have swarmkit support completely different behaviour when the user can't actually make use of that new behaviour?

> The command/args approach avoids having to know anything about the image when sending args or overriding the entrypoint

Not if we re-add `--entrypoint`, which seems like it's necessary.

**Comment by stevvooe** [comment]
> Why introduce the extra logic in the client to support this and have swarmkit support completely different behaviour when the user can't actually make use of that new behaviour?

There is no extra logic.
