### ISSUE TITLE
Flakey test: TestApiSwarmManualAcceptance

### ISSUE THREAD

**Issue by tiborvass** [docker/docker#23922]
As encountered on #23824 at https://jenkins.dockerproject.org/job/Docker-PRs-experimental/20388/console

```
20:03:13 ----------------------------------------------------------------------
20:03:13 FAIL: docker_api_swarm_test.go:70: DockerSwarmSuite.TestApiSwarmManualAcceptance
20:03:13 
20:03:13 [d29413186] waiting for daemon to start
20:03:13 [d29413186] daemon started
20:03:13 [d60192840] waiting for daemon to start
20:03:13 docker_api_swarm_test.go:71:
20:03:13 [d60192840] exiting daemon
20:03:13     s.testAPISwarmManualAcceptance(c, "")
20:03:13 check_test.go:212:
20:03:13     c.Assert(err, check.IsNil)
20:03:13 ... value *errors.errorString = &errors.errorString{s:"[d60192840] Daemon exited during startup"} ("[d60192840] Daemon exited during startup")
20:03:13 
20:03:13 [d29413186] exiting daemon
20:03:17 
20:03:17 ----------------------------------------------------------------------
```

**Comment by tonistiigi** [comment]
This is happening because of iptables rules are applied by multiple daemons in the same time and it causes a fatal error:

```
time="2016-06-17T20:39:10.856326751Z" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: unable to remove jump to DOCKER-ISOLATION rule in FORWARD chain:  (iptables failed: iptables --wait -D FORWARD -j DOCKER-ISOLATION: iptables: No chain/target/match by that name.\n (exit status 1))" 
```

We should change the error handling to be more graceful so in case of error it checks if the same rule was already applied by something else.

ping @aboch

**Comment by aboch** [comment]
@tonistiigi We could make this more graceful like you are suggesting, but it would be good for just that code path. Whenever the two daemons would manipulate the same chain (for example when they both are adding/removing a user defined bridge network) a different error would be hit and worse it could not even be detected and be more subtle affecting datapath.
I am not sure we can have two daemon working in the same network namespace.

**Comment by tonistiigi** [comment]
@aboch We do support running multiple daemon processes so this is not only issue for the tests. I think libnetwork even wanted to support same graph dir(I think this was why boltdb doesn't use persistent connections) but that is not supported by other parts of docker. I think tests issues are most important atm, but we should look over the other cases as well later. If there are no other solutions we should consider file locks, or if we need to make sure that daemons use different cli options that would be acceptable also.

**Comment by aboch** [comment]
@tonistiigi I double checked with @mrjana and, in regarding to iptables, the only way N daemons can run in the same host is that at least N-1 daemons are started with `--iptables=false`. We never claimed two or more daemons in the same host all using iptables can work.

**Comment by aboch** [comment]
For the iptables conflicting swarm tests, can we have the daemon start with `--iptables=false` ?
If they are only checking the APIs, it should be fine for now.

**Comment by tonistiigi** [comment]
@aboch Yes, I can do it for the swarm tests because they don't test networking atm. But we also have real networking tests(anything that uses `DockerDaemonSuite`) that run on a separate daemon. I'm not sure if those would pass.
