### ISSUE TITLE
"docker service update" awkward for updating command arguments

### ISSUE THREAD

**Issue by aaronlehmann** [docker/docker#23923]
It looks like if I want to update a service's command from `echo abc def` to `echo abc xyz`, I need to run `docker service update servicename --arg abc --arg xyz`. Inserting `--arg` before each argument doesn't feel right - if I have a command with lots of args, this is going to be really cumbersome and look weird. Could this be done with positional arguments at the end of the command like `docker service create`?

cc @vieux @dnephin

**Comment by dnephin** [comment]
It would probably be better to do it with a single quoted string, but then we need to shlex to split it into the slice in the client.

**Comment by dnephin** [comment]
Maybe this is already handled by the engine, I'll try it out.

**Comment by tiborvass** [comment]
Let's do this: `docker service update --image myimage --replicas 3 myservice ls -l` for updating arguments

And if you want to reset arguments you do: `docker service update --image myimage --replicas 3 myservice ""`

**Comment by tiborvass** [comment]
cc @sfsmithcha

**Comment by dnephin** [comment]
PR with these changes is #24195

**Comment by tiborvass** [comment]
@dnephin @aaronlehmann after discussing with Solomon and others, we'd prefer the original `--args` with shlex. I can't find the PR now.

**Comment by tiborvass** [comment]
I suggest we close #24195 then

**Comment by dnephin** [comment]
I've updated #24195 with the shlex implementation
