### ISSUE TITLE
Conflicting options: --rm and -d

### ISSUE THREAD

**Issue by pcgeek86** [docker/docker#23959]
**Output of `docker version`:**

```
PS C:\windows\system32> docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:44:17 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:54:25 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 29
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-38-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 667.7 MiB
Name: artofshella0
ID: E7RK:KVX4:CEVJ:5FE4:YLJM:SIGD:YGBM:YMFR:7YGQ:SQDD:FD7U:6PIX
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=azure
```

**Steps to reproduce the issue:**
1. Run a container with `-d` and `--rm` options

**Describe the results you received:**

```
Conflicting options: --rm and -d
```

**Describe the results you expected:**

The container should run detached and be removed when it exits.

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by vdemeester** [comment]
Hi @pcgeek86,

Currently `--rm` is client-side only, and that's why these two options are confilcting. There is an issue to keep track of it (https://github.com/docker/docker/issues/20334), and a PR (https://github.com/docker/docker/issues/20848) to make `--rm` service-side and thus remove this conflict.

👼

**Comment by pcgeek86** [comment]
@vdemeester Thanks Vincent! Sorry for the dupe. I did see the issue you reference when I searched, but it didn't mention detached containers, so I figured it might not be an exact dupe. We can close this one.
