### ISSUE TITLE
scaling service down shouldn't put all the nodes on one host

### ISSUE THREAD

**Issue by jhorwit2** [docker/docker#23957]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 21:15:33 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 21:15:33 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 18
 Running: 5
 Paused: 0
 Stopped: 13
Images: 7
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 112
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: active
 NodeID: 1rtix8otorooc797rbf73q3uz
 IsManager: Yes
 Managers: 2
 Nodes: 3
 CACertHash: sha256:57ccb49971b1803615d2b7be3c36f9f2c77335435e19b3f828fb88ce0f995a27
Runtimes: default
Default Runtime: default
Security Options: apparmor seccomp
Kernel Version: 4.2.0-38-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.86 GiB
Name: 1f5d014f-82c0-484c-96b1-bab9c7e40cbd
ID: CYOV:ZAFN:2E66:M6QW:25Y2:GNGC:YCOP:LZFG:WPWI:MX5I:GUYZ:S2Q6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Steps to reproduce the issue:**
1. Create a new service
2. Scale up/down 

**Describe the results you received:**

During some scale downs all the remaining tasks in the service are on one swarm worker. 

**Describe the results you expected:**

Service tasks should be somewhat redundant and not all be on one node. 

**Additional information you deem important (e.g. issue happens only occasionally):**

The scheduler should take into account where the nodes are being scheduled for a given service. I noticed that when I scaled a service to 10 then back to 3 that all the nodes sometimes would be on one swarm node which is less than ideal from a redundancy standpoint. The only way to fix it is to scale up and down again and hope the scheduler does it better.

**Comment by thaJeztah** [comment]
ping @aluzzardi @dongluochen PTAL

**Comment by mgoelzer** [comment]
@aaronlehmann @dongluochen @aluzzardi

**Comment by aaronlehmann** [comment]
I have a fix for this pending in the swarmkit repo: https://github.com/docker/swarmkit/pull/1051

**Comment by aaronlehmann** [comment]
This was included in -rc3.
