### ISSUE TITLE
Add support for openvswitch bridges and specifying VLAN

### ISSUE THREAD

**Issue by Caligatio** [docker/docker#23954]
It would be great if docker natively support openvswitch (ovs) bridges and the ability to specify a VLAN that would be tagged for a container.  There is third party support for this functionality, notably [pipework](/jpetazzo/pipework) and partial support in an [ovs utility script](/openvswitch/ovs/blob/master/utilities/ovs-docker) (I'm trying to get VLAN support added), but they all require either manual management of the IPs or using [some sort of daemon that monitors for container events](/dreamcat4/docker-images/blob/master/pipework/2.%20Usage.md#daemon).  Neither of these options are great.

Here's a possible implementation idea:
- Add "ovs" as an option to `--net`
- Add a `--ovs-bridge` flag that specifies the ovs bridge to use
- Either add a `--ovs-ip` or overload `--ip` to set the container IP address
- Add a `--ovs-vlan` option that tags the veth on the ovs bridge side with the VLAN specified
- Either add `--ovs-gateway` or `--gateway` to specify the container's upstream gateway

I currently have a need for the same container running in different security domains - internal trusted, DMZ, etc - that are separated by VLANs.  Our network admins are not supportive of having a machine with forwarding enabled straddling multiple security domains but, using ovs, I can have multiple VLANs trunked to one machine and use ovs to have individual containers tagged with a single VLAN (and external IP) running on the same machine without forwarding.

I realize this sounds like a niche need but apparently enough people need to do it that at least 2 libraries already support this.

**Comment by cpuguy83** [comment]
Seems like you want something like https://github.com/gopher-net/docker-ovs-plugin

**Comment by Caligatio** [comment]
@cpuguy83 I am admittedly unfamiliar with Docker plugins but, from reading the README, is docker-ovs-plugin a fancier daemon that essentially does the same thing as monitoring the event socket?

It looks like it requires two Docker containers running which is weird since plugins are supposed to be running before Docker starts.  Unless I'm missing something, isn't this is a chicken or the egg problem?

**Comment by cpuguy83** [comment]
@Caligatio This is a limitation of plugins currently, something we are hoping to solve soon... experimental 1.12 release has some enhancements where this is not a problem.
But a container is not required, and will probably even be fine to run as is.

Note the plugin is only the first container, the 2nd container is ovs itself.

**Comment by thaJeztah** [comment]
Looks like the original question is addressed; improvements for plugins are on the roadmap; @Caligatio are you ok with closing this issue?

**Comment by Caligatio** [comment]
Well, the plugin looks like it does some things but doesn't have any support for VLANs.

**Comment by aboch** [comment]
@Caligatio 
> Well, the plugin looks like it does some things but doesn't have any support for VLANs.

I'd suggest you to open an issue on the ovs plugin project to get the proper attention to this feature request.
Given the vlan info would be a driver specific option, you would then be able to pass it to the driver via `--opt` flag during network create.

This is not really a docker/docker issue, I think it should be closed.
