### ISSUE TITLE
Support hyper-v external networking for Docker for Windows

### ISSUE THREAD

**Issue by F21** [docker/docker#23963]
I have been using Docker for Windows on and it has worked really well for me.

In my case, I have a pretty beefy development server which I use to run several development VMs. Development takes place on a weaker laptop which interacts with the VMs over the network.

Previously, I had a Ubuntu VM running the latest version of docker with bridged network enable. Effectively, that makes the VM look like a separate machine on my network with its own IP address to avoid port collisions with the other VMs.

With Docker for Windows, this does not seem to be possible (yet). I added an "external" hyper-v network, and added an extra network adapter to the `MobyLinuxVM` machine and connected it to the external network. However, when I attempt to start Docker for Windows, it does not start or shutdown properly and I have to force the machine to shutdown.

It would be nice if the Docker for Windows networking settings allows us to run the `MobyLinuxVM` in "bridged (VirtualBox term)" / "external (hyper-v terms)" mode.

**Comment by friism** [comment]
@F21 Thanks for the detailed explanation of your use case!

If you don't mind, could I get you to start a thread on the [Docker for Windows Forums](https://forums.docker.com/c/docker-for-windows). This repo is used to track problems with the open source Docker engine.

**Comment by F21** [comment]
@friism 

Thanks! Opened a thread here for those interested: https://forums.docker.com/t/support-hyper-v-external-networking-for-docker-for-windows/16687
