### ISSUE TITLE
Add Avro flume log driver

### ISSUE THREAD

**Issue by sebglon** [docker/docker#23978]
I wan't to add Avro-flume log driver to push all data on log centralizer

**Comment by sebglon** [comment]
I have create à Pull request to this feature.

**Comment by cpuguy83** [comment]
Log plugin support is now merged and should be part of 17.05.
I do not think we'll be accepting any new built-in log drivers.

Closing this. Any new log drivers should be implemented as a plugin at this point. If anyone wants to discuss this feel free to ping me on Slack, or come see me @ DockerCon!
