### ISSUE TITLE
Dockerfile NoCache command

### ISSUE THREAD

**Issue by d2xdt2** [docker/docker#23979]
A common problem is when having
```
RUN git clone https://github.com/...
```
somewhere in the Dockerfile, as Docker won't see when the repo have changed. Using `--no-cache` is the slowest possible option. To solve this I propose a `NOCACHE` command
```
NOCACHE
RUN git clone https://github.com/...
```
which will disable caching when encountered at that point in that particular Dockerfile.

**Comment by bamarni** [comment]
It has already been discussed in #1996

**Comment by cpuguy83** [comment]
Closing since this is a dup.
