### ISSUE TITLE
Docker Commit error: hcsshim::ImportLayer failed in Win32: The filename or extension is too long

### ISSUE THREAD

**Issue by str3tch** [docker/docker#23976]
*Windows containers*

**Output of `docker version`:**

```
PS C:\Users\Administrator\Desktop> docker version
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   8e92415
 Built:        Thu May 26 17:08:34 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   8e92415
 Built:        Thu May 26 17:08:34 2016
 OS/Arch:      windows/amd64

```

**Output of `docker info`:**

```
PS C:\Users\Administrator\Desktop> docker info
Containers: 18
 Running: 1
 Paused: 0
 Stopped: 17
Images: 6
Server Version: 1.12.0-dev
Storage Driver: Windows filter storage driver
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null
Kernel Version: 10.0 14300 (14300.1000.amd64fre.rs1_release_svc.160324-1723)
Operating System: Windows Server 2016 Standard Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 4 GiB
Name: WIN-BU8LQS401SL
ID: NCJK:GUPS:MONS:SYZ3:BNA2:AQR3:2E4F:IWLY:CVSS:EIBP:5WLB:7UJ2
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Username: irlagrange
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

Docker images showing base containers and the one I have issue with (prognosis_exe):

```
PS C:\Users\Administrator\Desktop> docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
prognosis_exe       latest              048a924e32f1        4 hours ago         10.96 GB
prognosis_exe       ready_to_install    048a924e32f1        4 hours ago         10.96 GB
windowsservercore   10.0.14300.1000     5bc36a335344        6 weeks ago         9.354 GB
windowsservercore   latest              5bc36a335344        6 weeks ago         9.354 GB
microsoft/iis       windowsservercore   c26f4ceb81db        7 weeks ago         9.49 GB
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Windows Server TP5 running on Parallels for Mac (Macbook Air 2013, i7)

**Steps to reproduce the issue:**
1. docker pull microsoft/iis:windowsservercore
2. run CMD in above image
3. copy some files across to container 
4. stop container
5. docker commit the container
6. docker run -it .. cmd
7. in the container, install my software. The software DOES generate long file paths
8. stop the container
9. docker commit the container once again
.. at this point I get the error

**Describe the results you received:**

> PS C:\Users\Administrator\Desktop> docker commit dda0048427c9 prognosis_exe:latest
> Error response from daemon: re-exec error: exit status 1: output: time="2016-06-27T16:27:30+10:00" level=error msg="hcss
> him::ImportLayer failed in Win32: The filename or extension is too long. (0xce) layerId=\\\\?\\C:\\ProgramData\\docker\\
> windowsfilter\\efbe0bdc39545089bf3a152a96d94cbdfd64581ef38146bef73e8216cbaeb736 flavour=1 folder=C:\\Windows\\TEMP\\hcs6
> 82367167"
> hcsshim::ImportLayer failed in Win32: The filename or extension is too long. (0xce) layerId=\\?\C:\ProgramData\docker\wi
> ndowsfilter\efbe0bdc39545089bf3a152a96d94cbdfd64581ef38146bef73e8216cbaeb736 flavour=1 folder=C:\Windows\TEMP\hcs6823671
> 67

**Describe the results you expected:**
I expected it to commit, as it did in step 5

**Additional information you deem important (e.g. issue happens only occasionally):**
 
I followed the solutions put forwad in this issue https://github.com/docker/docker/issues/22449 but it did not fix my problem.

**Comment by anweiss** [comment]
Also seeing this issue with the same client/server version

**Comment by mlapierre** [comment]
Seems this is fixed by a Windows update: https://github.com/docker/docker/issues/22449#issuecomment-235803959
Specifically: https://support.microsoft.com/en-us/kb/3157663

I had the same issue until I installed all the available updates. Works fine now with Kernel Version: 10.0 14300 (14300.1045.amd64fre.rs1_release_svc.160705-1059)

**Comment by thaJeztah** [comment]
Thanks for the update @mlapierre 

@str3tch can you confirm that the issue is fixed?

**Comment by Luisa456** [comment]
Long Path tool can resolve error messages like: path too long, cannot delete file, too long path, destination path is too long, etc.

**Comment by thaJeztah** [comment]
i'm assuming this is fixed, but ping me if this is still an issue and needs to be reopened

**Comment by luisa123456** [comment]
Long Path Tool is the best solution for the error 1320. This software can also resolve issues like can’t delete a file, filename too long, too long path etc.
