### ISSUE TITLE
service tasks that aren't healthy are still getting requests

### ISSUE THREAD

**Issue by jhorwit2** [docker/docker#23970]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   a7119de
 Built:        Fri Jun 17 22:09:20 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 125
 Running: 2
 Paused: 0
 Stopped: 123
Images: 236
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 470
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay null host
Swarm: active
 NodeID: 6o19rpi5kx93jt9z6osdxfwfp
 IsManager: Yes
 Managers: 1
 Nodes: 1
 CACertHash: sha256:5711d0745394ebace6e82caa93a943281c0ce201902d4c3b6ba0b12f5d13cb02
Runtimes: default
Default Runtime: default
Security Options: seccomp
Kernel Version: 4.4.13-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.954 GiB
Name: moby
ID: 2PNZ:QY46:DCR2:IAU7:WUU4:Q5FZ:MAVC:KK7U:6JKH:LG2L:ANYI:3JP6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 107
 Goroutines: 281
 System Time: 2016-06-26T17:28:58.594609691Z
 EventsListeners: 32
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

mac beta

**Steps to reproduce the issue:**
1. `docker service create --name hc --replicas 2 --network mynet hc_test`
2. `docker exec -it <container> /bin/bash` 
3. `apt-get update && apt-get -y install curl` -- this will cause health check to pass
3. `curl hc` - do this twice and once you will hit the node that's down. (the node that's up is the no route available one which is tracked https://github.com/docker/docker/issues/23965)

**Describe the results you received:**

Running curl twice gave allowed me to hit both servers

**Describe the results you expected:**

Running curl twice should of only hit the server that is passing the health check. 

**Additional information you deem important (e.g. issue happens only occasionally):**

Dockerfile for test image
```
FROM nginx:latest

HEALTHCHECK --interval=5s --timeout=3s CMD curl localhost
```

**Comment by cpuguy83** [comment]
I do not think the routing mesh is integrated with health checking yet.

ping @mrjana

**Comment by jhorwit2** [comment]
That would explain it. Is there a ticket tracking this? I searched but didn't see anything.

**Comment by cpuguy83** [comment]
Yep, this one! :)

**Comment by mrjana** [comment]
@jhorwit2 @cpuguy83 health checking is not integrated with the swarm mode natively yet. What probably needs to happen is if a container fails health check, we should bring down the task and reschedule it which should make the routing mesh to work seamlessly.

**Comment by vdemeester** [comment]
@mrjana (cc @icecrime) will health checking integrated in 1.12 or goal for it is 1.13 ? :angel:

**Comment by jhorwit2** [comment]
@mrjana will this be in the 1.12 release? I noticed #24545 kind of seems related, but I'm not familiar enough to know if that will solve this issue also.

**Comment by jhorwit2** [comment]
@cpuguy83 @icecrime @mrjana @thaJeztah is this going to be in 1.12? Seems very important to me, I wouldn't call this production ready w/o removing unhealthy nodes immediately so requests don't fail to clients.

**Comment by cpuguy83** [comment]
@jhorwit2 1.12 will kill unhealthy containers and create new ones.

**Comment by jhorwit2** [comment]
@cpuguy83 does the kill event trigger the removal of the vip from ipvs?

**Comment by mavenugo** [comment]
@jhorwit2 it will NOT remove the vip from ipvs. But ideally when the tasks are rescheduled, the backend server (container ip) will be readjusted on the existing IPVS (vip->backend-servers ) configuration.

**Comment by jhorwit2** [comment]
@mavenugo - Sorry when I said VIP i meant container IP from the list of available backend servers. 

So, if I'm understanding the flow correctly; when a container hits the max # of retries for a health check the daemon will immediately send out a kill signal. After the container stops/dies the swarm manager will notice the ideal state is not met and schedule a new task. Once that new task has been setup only then the bad container IP will be removed from the available servers? I'm not very familiar with the swarmkit code yet. 

The issue that I see with not immediately removing the container IP from the available pool is that now you have some amount of time where a container should not be receiving requests but it is.

**Comment by mavenugo** [comment]
@jhorwit2 thanks for the clarification.
I haven't tried this use-case myself. But the container IP should be removed from the IPVS backend server-list as soon as the container is killed. But it might take a few more milliseconds for other daemons in the cluster to know about this event (through gossip). But other than that there shouldnt be any other extra delay. I will give this a try and let you know more on my findings.

**Comment by jhorwit2** [comment]
@mavenugo If it's removed now when the kill event is sent out then this should be fine. I know when I made this ticket the unhealthy restart logic wasn't yet landed.
