### ISSUE TITLE
[1.12-rc2] Service volume mounts in DAB file

### ISSUE THREAD

**Issue by madjam002** [docker/docker#23984]
In Docker 1.12-rc2, it appears to be possible to define volume mounts using:

```
--mount type=bind,source=/some-dir,target=/some-dir
```

(will probably want to use a volume driver like flocker instead of bind mounting a volume)

Will we see the ability to define mounts in a DAB file? And will Docker Compose be able to export volumes as mounts into the DAB file?

**Comment by cpuguy83** [comment]
dabs are still experimental, we don't know what they will be (in full) yet.

However, the main goal is to have a portable way to define services, and being able to specify mounts is not portable.

Thanks for the interest, but I'm going to close this since it's not really an issue.
For questions forums.docker.com may be a better place, for #docker on IRC.

Thanks again!

**Comment by madjam002** [comment]
@cpuguy83 Makes sense, thanks for getting back to me :smile:

Is there any kind of existing chat thread regarding the DAB format or more generally the end goal of having "a portable way to define services"?

It would be nice to follow the progress of this format and what it will become, and how these problems get solved.

Also keeping the environment variables inline in this file could arguably be "not portable". Maybe it's better to have some kind of runtime environment config file which could inherit the DAB file which provides the environment variables and mounts necessary to run the services.

**Comment by cpuguy83** [comment]
@madjam002 As long as the environment vars are static, it should be portable. They are not host dependent and only change things inside the image.

I agree having a file-based runtime config would be nice, but probably only after dab is in stable.

**Comment by madjam002** [comment]
@cpuguy83 Sounds good

**Comment by stychos** [comment]
Why not? It would be the great feature.
