### ISSUE TITLE
Unclear error message when overlay network is created with invalid parameters

### ISSUE THREAD

**Issue by jyrkiput** [docker/docker#23980]
While trying out overlay network and starting containers on it, I got following error:

```
docker: Error response from daemon: invalid bit range [4, 4].
```
I think that the reason was invalid parameters used in network creation (managed to get things working by removing those), but the error message is somewhat unclear.

**Output of `docker version`:**

```
Docker version 1.11.2, build b9f10c9
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host overlay bridge null
Kernel Version: 4.4.0-24-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953 GiB
Name: infra-front
ID: QAPB:EYGZ:K3X2:QKM2:IHYQ:EO7U:VPWM:2XJC:E7KS:W6VY:NFBD:HQ7U
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Cluster store: consul://192.168.80.10:8500
Cluster advertise: 192.168.80.10:2370
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Virtualbox

**Steps to reproduce the issue:**
1. docker network create -d overlay --subnet=192.168.50.0/24 --gateway=192.168.50.1 --ip-range=192.168.50.4/32 test
2. docker run --rm -ti --net test alpine sh

**Describe the results you received:**
Docker reports error,
```
docker: Error response from daemon: invalid bit range [4, 4].
```
**Describe the results you expected:**
More information about what is wrong, and how to fix this.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by allencloud** [comment]
Maybe error happened in libnetwork:
https://github.com/docker/libnetwork/blob/master/bitseq/sequence.go#L201

**Comment by thaJeztah** [comment]
@sanimej any idea what a better message would be?

**Comment by aboch** [comment]
@jyrkiput This is actually a bug. Thanks for the report.

Even though the use-case is strange because a range of only one IP is specified (\32), it should work and only one container would be able to run, with exactly that IP address.

Will push a fix in libnetwork.

**Comment by icecrime** [comment]
@aboch Can you please tell us more about that bug? Is it a regression for 1.12.0, and is it something that absolutely needs to be fixed in 1.12.2? I don't know what priority to put here. Thanks!

**Comment by thaJeztah** [comment]
@icecrime oh, I think I overlooked this was reported with 1.11.2, not 1.12, so perhaps it's not needed for 1.12.2

**Comment by aboch** [comment]
@icecrime It is not a 1.12.0 regression, I am assuming it has existed for quite some time.

It is exposed by creating a network which has an ip-range that contains only one IP address.
Therefore one can only run run one container at the time on such network.

I doubt many people would care for this feature, but I can't tell for sure.
I do not think it is absolutely needed for 1.12.2. The fix is only one line though.

**Comment by icecrime** [comment]
@aboch Thanks, I'll remove from the milestone then (it'll be release "naturally" with 1.13.0)
