### ISSUE TITLE
Cannot start docker engine after upgrade of both fedora & docker-engine due to selinux errors

### ISSUE THREAD

**Issue by jimmidyson** [docker/docker#23981]
Previously running Fedora 23 with docker-engine{,-selinux} 1.10.3 from Docker repos (not Fedora repos) - working fine for months. Upgraded to Fedora 24, updated to Docker 1.11.2 throws an error:

```
Re-declaration of boolean virt_sandbox_use_fusefs
Failed to create node
Bad boolean declaration at line 148 of /var/lib/selinux/targeted/tmp/modules/100/virt/cil
/usr/sbin/semodule:  Failed!
```

Have a colleague with exactly the same problem. Tried uninstalling RPMs & reinstalling but no luck.

**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:31:13 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Output of `docker info`:**

```
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Laptop running Fedora 24

**Steps to reproduce the issue:**
Not sure it's 100% reproducible, but have a couple of colleagues with the same issue.

**Describe the results you received:**
Cannot start docker.

**Describe the results you expected:**
Able to start docker.

**Comment by jimmidyson** [comment]
Running `systemctl start docker` fails with following in logs:

```
Jun 27 12:00:33 jimmi-redhat.localnet audit[1]: AVC avc:  denied  { create } for  pid=1 comm="systemd" scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=unix_stream_socket permissive=0
Jun 27 12:00:33 jimmi-redhat.localnet systemd[1]: docker.socket: Failed to listen on sockets: Permission denied
Jun 27 12:00:33 jimmi-redhat.localnet systemd[1]: Failed to listen on Docker Socket for the API.
-- Subject: Unit docker.socket has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.socket has failed.
-- 
-- The result is failed.
Jun 27 12:00:33 jimmi-redhat.localnet systemd[1]: Dependency failed for Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has failed.
-- 
-- The result is dependency.
Jun 27 12:00:33 jimmi-redhat.localnet systemd[1]: docker.service: Job docker.service/start failed with result 'dependency'.
```

**Comment by jimmidyson** [comment]
I assume this is because the docker selinux module isn't loaded (`sudo semodule -l | grep docker`) returns nothing.

**Comment by gumieri** [comment]
I have the same Issue here.
Can it be related to absence of repo to fedora 24? (https://yum.dockerproject.org/repo/main/fedora/24)
```
docker-engine-selinux.noarch           1.11.2-1.fc23
```

**Comment by cpuguy83** [comment]
@gumieri Seems likely.

**Comment by jimmidyson** [comment]
@gumieri Possibly but it looks OK. It looks to me like an incompatibility between the docker selinux module & selinux on fc24, but I'm not sure of the selinux differences from fc23 tbh.

**Comment by jimmidyson** [comment]
From @rhatdan on [twitter](https://mobile.twitter.com/rhatdan/status/747536135954403328):

> docker-engine-selinux needs to be updated off of the docker-selinux master branch on github!  fedora version should work.

Is that from https://github.com/fedora-cloud/docker-selinux ?

**Comment by jimmidyson** [comment]
Or this repo: https://github.com/projectatomic/docker-selinux ? Not sure...

**Comment by jimmidyson** [comment]
Following discussion in https://github.com/docker/docker/pull/23896 it seems like this will have to wait until 1.12 unfortunately.

**Comment by rhatdan** [comment]
https://github.com/projectatomic/docker-selinux

**Comment by ksylvan** [comment]
Anyone have a sense of when https://yum.dockerproject.org/repo/main/fedora/ will be updated with the Fedora 24 fixes? (Mostly related to SELinux as far as I can see from this discussion).

**Comment by ksylvan** [comment]
You can reproduce the problem by creating a completely vanilla Fedora 24, then put this in /etc/yum.repos.d/docker.repo (yes, using 23 packages on Fedora 24):

    [docker]
    baseurl = https://yum.dockerproject.org/repo/main/fedora/23/
    enabled = 1
    gpgcheck = 1
    gpgkey = https://yum.dockerproject.org/gpg
    name = Docker Repository

Then `sudo dnf install docker-engine` which will install these packages:

    $ rpm -qa | grep docker
    docker-engine-selinux-1.11.2-1.fc23.noarch
    docker-engine-1.11.2-1.fc23.x86_64

With SELinux in enforcing mode, you will see this error in audit.log:

    type=AVC msg=audit(1467565297.287:719): avc:  denied  { create } for  pid=1 comm="systemd" scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=unix_stream_socket permissive=0

With `setenforce 0` then the `sudo service docker start` works and you can use docker-1.11 on Fedora 24.

**Comment by rvernica** [comment]
I can confirm that there is still a problem with SELinux and Docker `1.12.0-rc3` installed from the Fedora `24` repository. It only starts if `setenforce 0`. Otherwise the error is:
```
Jul 06 19:48:10 host sudo[3110]:    user : TTY=pts/4 ; PWD=/home/user ; USER=root ; COMMAND=/sbin/service docker start
Jul 06 19:48:10 host audit[3110]: USER_CMD pid=3110 uid=1000 auid=4294967295 ses=4294967295 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='cwd="/home/user" cmd=7365727669636520646F636B6572207374617274 terminal=pts/4 r
Jul 06 19:48:10 host audit[3110]: CRED_REFR pid=3110 uid=0 auid=4294967295 ses=4294967295 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:setcred grantors=pam_env,pam_unix acct="root" exe="/usr/bin/sudo" hostname
Jul 06 19:48:10 host sudo[3110]: pam_systemd(sudo:session): Cannot create session: Already occupied by a session
Jul 06 19:48:10 host audit[3110]: USER_START pid=3110 uid=0 auid=4294967295 ses=4294967295 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:session_open grantors=pam_keyinit,pam_limits,pam_keyinit,pam_limits,pam_s
Jul 06 19:48:10 host sudo[3110]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jul 06 19:48:10 host polkitd[729]: Registered Authentication Agent for unix-process:3111:29107555 (system bus name :1.350 [/usr/bin/pkttyagent --notify-fd 4 --fallback], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, loca
Jul 06 19:48:10 host audit[1]: USER_AVC pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='avc:  received setenforce notice (enforcing=1)
                                   exe="/usr/lib/systemd/systemd" sauid=0 hostname=? addr=? terminal=?'
Jul 06 19:48:10 host audit[1]: AVC avc:  denied  { create } for  pid=1 comm="systemd" scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=unix_stream_socket permissive=0
Jul 06 19:48:10 host systemd[1]: docker.socket: Failed to listen on sockets: Permission denied
Jul 06 19:48:10 host systemd[1]: Failed to listen on Docker Socket for the API.
-- Subject: Unit docker.socket has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.socket has failed.
-- 
-- The result is failed.
Jul 06 19:48:10 host systemd[1]: Dependency failed for Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has failed.
-- 
-- The result is dependency.
Jul 06 19:48:10 host systemd[1]: docker.service: Job docker.service/start failed with result 'dependency'.
Jul 06 19:48:10 host systemd[1]: docker.socket: Unit entered failed state.
```
```
> docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 65
Server Version: 1.12.0-rc3
Storage Driver: devicemapper
 Pool Name: docker-8:5-658205-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 9.53 GB
 Data Space Total: 107.4 GB
 Data Space Available: 50.97 GB
 Metadata Space Used: 11.77 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.136 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.122 (2016-04-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.6.3-300.fc24.x86_64
Operating System: Fedora 24 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.709 GiB
Name: host
ID: ZWC4:C3PQ:UJUD:RQRS:M2VR:UGMX:LTJP:FBZD:OHUY:5A2J:J7DI:4MPK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```
```
> sudo dnf info docker-engine
Last metadata expiration check: 0:05:38 ago on Wed Jul  6 19:46:02 2016.
Installed Packages
Name        : docker-engine
Arch        : x86_64
Epoch       : 0
Version     : 1.12.0
Release     : 0.3.rc3.fc24
Size        : 76 M
Repo        : @System
From repo   : docker-testing-repo
Summary     : The open-source application container engine
URL         : https://dockerproject.org
License     : ASL 2.0
Description : Docker is an open source project to build, ship and run any application as a
            : lightweight container.
            : 
            : Docker containers are both hardware-agnostic and platform-agnostic. This means
            : they can run anywhere, from your laptop to the largest EC2 compute instance and
            : everything in between - and they don't require you to use a particular
            : language, framework or packaging system. That makes them great building blocks
            : for deploying and scaling web apps, databases, and backend services without
            : depending on a particular stack or provider.

Available Packages
Name        : docker-engine
Arch        : src
Epoch       : 0
Version     : 1.12.0
Release     : 0.3.rc3.fc24
Size        : 26 M
Repo        : docker-testing-repo
Summary     : The open-source application container engine
URL         : https://dockerproject.org
License     : ASL 2.0
Description : Docker is an open source project to build, ship and run any application as a
            : lightweight container.
            : 
            : Docker containers are both hardware-agnostic and platform-agnostic. This means
            : they can run anywhere, from your laptop to the largest EC2 compute instance and
            : everything in between - and they don't require you to use a particular
            : language, framework or packaging system. That makes them great building blocks
            : for deploying and scaling web apps, databases, and backend services without
            : depending on a particular stack or provider.

> sudo dnf info docker-engine-selinux
Last metadata expiration check: 0:05:47 ago on Wed Jul  6 19:46:02 2016.
Installed Packages
Name        : docker-engine-selinux
Arch        : noarch
Epoch       : 0
Version     : 1.12.0
Release     : 0.3.rc3.fc24
Size        : 43 k
Repo        : @System
From repo   : docker-testing-repo
Summary     : SELinux Policies for the open-source application container engine
URL         : https://dockerproject.org
License     : GPLv2
Description : SELinux policy modules for use with Docker

Available Packages
Name        : docker-engine-selinux
Arch        : src
Epoch       : 0
Version     : 1.12.0
Release     : 0.3.rc3.fc24
Size        : 23 k
Repo        : docker-testing-repo
Summary     : SELinux Policies for the open-source application container engine
URL         : https://dockerproject.org
License     : GPLv2
Description : SELinux policy modules for use with Docker
```

**Comment by ksylvan** [comment]
I can verify what @rvernica  said above on a fresh Fedora 24 system.

    type=AVC msg=audit(1467877380.166:736): avc:  denied  { listen } for  pid=1
    comm="systemd" path="/run/docker.sock" scontext=system_u:system_r:init_t:s0
    tcontext=system_u:system_r:unconfined_service_t:s0 tclass=unix_stream_socket

Same packages:

    $ rpm -qa| grep docker
    docker-engine-selinux-1.12.0-0.3.rc3.fc24.noarch
    docker-engine-1.12.0-0.3.rc3.fc24.x86_64

The yum repo file I used is this:

    $ cat /etc/yum.repos.d/docker.repo 
    [docker]
    baseurl = https://yum.dockerproject.org/repo/testing/fedora/24/
    enabled = 1
    gpgcheck = 1
    gpgkey = https://yum.dockerproject.org/gpg
    name = Docker Repository

**Comment by ksylvan** [comment]
The workaround suggested by `sealert` _does_ work:

    # You should report this as a bug.
    # You can generate a local policy module to allow this access.
    # Allow this access for now by executing:
    ausearch -c 'systemd' --raw | audit2allow -M my-systemd
    semodule -X 300 -i my-systemd.pp

Running the above generates the following file (my-systemd.te):

    module my-systemd 1.0;
    
    require {
    	type init_t;
    	type unconfined_service_t;
    	class unix_stream_socket { bind create listen setopt };
    }
    
    #============= init_t ==============
    allow init_t unconfined_service_t:unix_stream_socket { bind create listen setopt };

And now docker runs in enforcing mode.

**Comment by jimmidyson** [comment]
Yes it does but that is a bit of a loose policy: `unconfined_service_t` indicates a wrong labelling still.

**Comment by ksylvan** [comment]
@jimmidyson I agree. What is the correct fix, then?

**Comment by jimmidyson** [comment]
@ksylvan I think it's to do with correct labelling of the files laid down in the Docker RPM but I really don't know I'm afraid. As @rhatdan said we probably need to pull in changes from https://github.com/projectatomic/docker-selinux to here to get it to work but I'm no selinux expert.

**Comment by ksylvan** [comment]
@rhatdan What specifically needs to happen to correct the file contexts, permissions, etc? I'm looking at https://github.com/projectatomic/docker-selinux and at https://github.com/docker/docker/tree/master/contrib/docker-engine-selinux to try to figure out what needs to change so I can make a PR.

**Comment by rhatdan** [comment]
docker-engine-selinux needs to be based on master branch of docker-selinux package on F24 and Rawhide.  Older OS needs to be based on v1.10 branch.

You could also just install docker-selinux.

**Comment by justincormack** [comment]
@rhatdan I also get this error installing from test.docker.com on fc23 as well as fc24...

**Comment by ksylvan** [comment]
What is the best way to create the fedora-24 RPMs for Docker? I'm following the guide here: https://docs.docker.com/opensource/project/set-up-dev-env/

After `make shell`, in the container, I do:

- `make binary`
- ` cp bundles/1.2.0/binary-*/docker* /usr/bin`
- Start the docker daemon, and then...
- `DOCKER_BUILD_PKGS=fedora-24 make rpm`

But the above command fails after a while.

What is the canonical way of doing this?

**Comment by aanm** [comment]
I also have this issue

**Comment by bcambl** [comment]
I attempted an install from the testing repository in attempt to address this issue. 
Unfortunately I experienced the same issues..

```
Downloading Packages:
(1/2): docker-engine-selinux-1.12.0-0.3.rc3.fc24.noarch.rpm                                                                                    33 kB/s |  32 kB     00:00    
(2/2): docker-engine-1.12.0-0.3.rc3.fc24.x86_64.rpm                                                                                           3.2 MB/s |  18 MB     00:05    
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                         3.2 MB/s |  18 MB     00:05     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Upgrading   : docker-engine-selinux-1.12.0-0.3.rc3.fc24.noarch                                                                                                          1/4 
Re-declaration of boolean virt_sandbox_use_fusefs
Failed to create node
Bad boolean declaration at line 148 of /var/lib/selinux/targeted/tmp/modules/100/virt/cil
/usr/sbin/semodule:  Failed!
  Upgrading   : docker-engine-1.12.0-0.3.rc3.fc24.x86_64                                                                                                                  2/4 
  Cleanup     : docker-engine-1.11.2-1.fc23.x86_64                                                                                                                        3/4 
  Cleanup     : docker-engine-selinux-1.11.2-1.fc23.noarch                                                                                                                4/4 
  Verifying   : docker-engine-1.12.0-0.3.rc3.fc24.x86_64                                                                                                                  1/4 
  Verifying   : docker-engine-selinux-1.12.0-0.3.rc3.fc24.noarch                                                                                                          2/4 
  Verifying   : docker-engine-1.11.2-1.fc23.x86_64                                                                                                                        3/4 
  Verifying   : docker-engine-selinux-1.11.2-1.fc23.noarch                                                                                                                4/4 

Upgraded:
  docker-engine.x86_64 1.12.0-0.3.rc3.fc24                                          docker-engine-selinux.noarch 1.12.0-0.3.rc3.fc24                                         

Complete!
[root@redacted ~]# 
```

```
type=AVC msg=audit(1468361383.364:2541): avc:  denied  { create } for  pid=1 comm="systemd" scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=unix_stream_socket permissive=0
```

**Comment by kj54321** [comment]
Same the issue with manual rpm installation and have to disable the selinux.

```
rpm -ivh docker-engine-1.12.0-0.3.rc3.fc24.x86_64.rpm docker-engine-selinux-1.12.0-0.3.rc3.fc24.noarch.rpm --force
warning: docker-engine-1.12.0-0.3.rc3.fc24.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 2c52609d: NOKEY
Preparing...                          ################################# [100%]
Updating / installing...
   1:docker-engine-selinux-1.12.0-0.3.################################# [ 50%]
Re-declaration of boolean virt_sandbox_use_fusefs
Failed to create node
Bad boolean declaration at line 148 of /var/lib/selinux/targeted/tmp/modules/100/virt/cil
/usr/sbin/semodule:  Failed!
   2:docker-engine-1.12.0-0.3.rc3.fc24################################# [100%]

```


Hopes you can fix it when 1.12 GA release.

**Comment by crosbymichael** [comment]
trying to repo now

**Comment by crosbymichael** [comment]
@rhatdan with a fresh install on f24 I tried using the `docker-selinux` package and got the same results.  It seems to be an issue with the `docker.socket` not working but I'm having a hard time finding the reason why in the logs.

If I remove the docker.socket and just run docker form the service file on f24 everything works fine with both selinux packages.  Are we sure this issue is selinux related?

**Comment by metal3d** [comment]
@ksylvan you saved my day.

**Comment by rhatdan** [comment]
What AVCs are you seeing with the docker.socket?  We recommend not using docker.socket, since it block aotorestart in docker.

**Comment by crosbymichael** [comment]
Ok, i am seeing the eperm on the socket now, but it happens with the `docker-selinux` package as well unless dnf is not installing it correctly.  It is only happening with the socket and if you run docker without socket activation everything runs fine in enforcing mode

**Comment by crosbymichael** [comment]
So looking at this more I think i'm going to go with this approach, let me know if you think it's a bad idea.  

We should remove socket activation from the packages, it fixes both this issue and the fact that its worthless with docker and shouldn't have been there in the first place. ( --restart does not work at all with it )  

As far as updating the selinux package, it looks like the issue here #24612 is more specific to the labeling problem so I will fix/update that in a follow up PR after removing SA.

**Comment by crosbymichael** [comment]
@ksylvan the build line that you are looking for is this:

`make DOCKER_BUILD_PKGS=fedora-24 rpm`

I was able to build rpms successfully using that command.  make variables come before the command or whatever you call what is at the end

**Comment by ksylvan** [comment]
@crosbymichael is that run inside the "make shell" container with the docker daemon running? Or on the host?

**Comment by crosbymichael** [comment]
@ksylvan on the host

**Comment by ksylvan** [comment]
@crosbymichael the build chugs along for a while, and then I get this:

    ---> Making bundle: build-rpm (in bundles/1.12.0-dev/build-rpm)
    INFO: Waiting for daemon to start...
    +++ exec dockerd --debug --host unix:///go/src/github.com/docker/docker/bundles/1.12.0-dev/build-rpm/docker.sock --storage-driver devicemapper --pidfile bundles/1.12.0-dev/build-rpm/docker.pid --userland-proxy=true
    ...........................................................
    error: daemon at unix:///go/src/github.com/docker/docker/bundles/1.12.0-dev/build-rpm/docker.sock fails to 'docker version':
    Client:
     Version:      1.12.0-dev
     API version:  1.25
     Go version:   go1.6.2
     Git commit:   80ec9fa
     Built:        Fri Jul 15 15:35:51 2016
     OS/Arch:      linux/amd64
    Cannot connect to the Docker daemon. Is the docker daemon running on this host?
    ---> Making bundle: .integration-daemon-stop (in bundles/1.12.0-dev/build-rpm)
    Makefile:100: recipe for target 'rpm' failed

This is my fork of docker based on `upstream/master`

**Comment by crosbymichael** [comment]
@ksylvan did you oom your machine?  you probably need 2GB to build packages and everything

**Comment by ksylvan** [comment]
@crosbymichael I have 32GB of ram, so no, I don't think it's an out of memory problem.

**Comment by crosbymichael** [comment]
I rebased and rebuilt the RPM with the upsteam selinux changes and its still giving the same errors.

```
Jul 15 20:45:51 cm-fedora-2 audit: SELINUX_ERR op=security_compute_av reason=bounds scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:docker_t:s0 tclass=unix_stream_socket perms=ioctl,read,write,create,getattr,setattr,lock,
Jul 15 20:45:51 cm-fedora-2 audit[1]: AVC avc:  denied  { create } for  pid=1 comm="systemd" scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:docker_t:s0 tclass=unix_stream_socket permissive=0
```

**Comment by rhatdan** [comment]
These are kernel issues and will be fixed in 4.8 I believe.  Basically you can ignore it for now.  Nothing is actually being blocked, as I understand it.

**Comment by crosbymichael** [comment]
@rhatdan what is the best way to ignore them? as they are preventing docker from starting and binding on the unix socket?   Is there a more robust rule we can add in the time being than the one suggested by sealert?

**Comment by rhatdan** [comment]
Actually this looks like something that is blocked.  Are you guys building the docker-selinux package from master?

**Comment by rhatdan** [comment]
docker-selinux master I mean?  This is on Fedora 24?

**Comment by crosbymichael** [comment]
@rhatdan ya, i just build the rpm with the current commit on master for the selinux package and it is on a freash f24 box.

**Comment by rhatdan** [comment]
Ok.  I have that installed on Rawhide, but I am not sure we are using this on F24 yet.  This issue has something to do with seccomp changes, and I am not sure if we have the right packages available on F24 to handle it yet.  I am checking with @lsm5 what version of docker-selinux is installed on F24 at this time.

**Comment by crosbymichael** [comment]
```
[root@cm-fedora-2 ~]# dnf info docker-selinux
Last metadata expiration check: 1:29:07 ago on Fri Jul 15 20:08:54 2016.
Available Packages
Name        : docker-selinux
Arch        : x86_64
Epoch       : 2
Version     : 1.10.3
Release     : 21.git19b5791.fc24
Size        : 72 k
Repo        : updates
Summary     : SELinux policies for Docker
URL         : https://github.com/projectatomic/docker-selinux
License     : ASL 2.0
Description : SELinux policy modules for use with Docker.

```

**Comment by rhatdan** [comment]
Looks like this is an issue with libsepol that is shipped in f24

If I compare the libsepol that is in Rawhide Versus F24 I see these versions.

```
latestf24 libsepol
libsepol-2.5-7.fc25.x86_64
libsepol-2.5-3.fc24                       f24                   plautrba
```

Looking at the changelog of the rawhide version I see.

```
* Fri May 06 2016 Petr Lautrbach <plautrba@redhat.com> - 2.5-6
- Change logic of bounds checking to match change in kernel
- Fix multiple spelling errors

* Mon May 02 2016 Petr Lautrbach <plautrba@redhat.com> - 2.5-5
- Only apply bounds checking to source types in rules
- Fix CIL and not add an attribute as a type in the attr_type_map
```

These changes to the bounds checking would fix the issues you are seeing I believe.

https://bugzilla.redhat.com/show_bug.cgi?id=1357154

**Comment by crosbymichael** [comment]
@rhatdan thanks for the help, i'll track that bugzilla

**Comment by ksylvan** [comment]
Awesome! Looks like we have a fix coming soon. Thanks, @crosbymichael and @rhatdan

**Comment by rhatdan** [comment]
During the night, I remembered there was an issue that might be triggering this problem.  The seccomp patches used to turn on NO_NEW_PRIVS by default.  NO_NEW_PRIVS causes problems with SELinux transitions.  Using Seccomp should not require NO_NEW_PRIVS, does this version of docker turn on NO_NEW_PRIVS by default?

Setting NO_NEW_PRIVS means that you can not transition to a identity with more privs then you currently have, in DAC this means that you can not gain any Capabilities.  In SELinux this means that you can not transition to an SELinux domain that has more access then your current domain has.  Basically docker_t can not transition to the container domain, svirt_lxc_net_t, unless all access available to svirt_lxc_net_t is available to docker_t.  This goes all the way up the transition stack.  Since init_t transitions to docker_t, docker_t must have all of the access of init_t.

The original patches in SELinux to handle this were written wrong.  The way the toolchain and kernel were enforcing this were both on the SRC and DEST.  Meaning all access given to the CHILD domain must also be available to the PARENT domain, which made sense.  But the bug was that all access that used the CHILD domain as a TARGET must also be granted to the PARENT domain.  For example, if you allowed a different process type to send signals to the CHILD, you would also have to allow the different process type to send signals to the PARENT.  This was clearly a bug.  I did might allow a confined domain to kill a container process but I would not want to allow a confined domain to kill the docker daemon.  After we discovered this, we moved to stop the NO_NEW_PRIVS setting with seccomp and got fixes into the kernel and SELinux libraries to handle NO_NEW_PRIVS properly, only requiring the access used for the SRC domain of the CHILD to be a subsection of the access of the PARENT.

The kernel and SELinux libraries were fixed to handle this in Rawhide, but this code has not made it into Fedora yet.

**Comment by justincormack** [comment]
@rhatdan we do not turn on no new privs by default, you still have to explicitly enable it at container run time.

**Comment by rhatdan** [comment]
We had a bug in the seccomp filters that turned this on by default. @mheon looked into it,  But I agree, I think this is fixed in the master code.  I just don't remember if it was fixed in runc or docker.  It was in the seccomp bindings.  But this is what this signature looks like.

**Comment by rhatdan** [comment]
Grepping through my emails, I find a reference to the following.

https://github.com/seccomp/libseccomp/blob/08a682a9f895b8f622499df5ee69fcabe1e3cbab/src/system.c#L140

**Comment by crosbymichael** [comment]
@rhatdan I switched to the testing repos on f24 and tested the versions of the new packages listed here: https://bodhi.fedoraproject.org/updates/FEDORA-2016-84d1f77e58

Here is what I find:

1. Installed docker-engine from the testing repo, 1.12.0-rc3
**same error avc on creating the socket**

2. installed docker-engine from my built rpm with commit `6bc126cae693fad82a09246393f6ed7bfb09b5f4` of atomic's selinux package
**same error avc on creating the socket**

3. Ran `dnf --enablerepo=updates-testing install --allowerasing docker-selinux` to try that
**new error, the socket is created but dockerd will not start.** 
```
Jul 18 21:56:52 cm-fedora-selinux-test audit[1198]: AVC avc:  denied  { execute } for  pid=1198 comm="(dockerd)" name="dockerd" dev="vda1" ino=9715 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=fil
Jul 18 21:56:52 cm-fedora-selinux-test systemd[1198]: docker.service: Failed at step EXEC spawning /usr/bin/dockerd: Permission denied```

**Comment by justincormack** [comment]
@rhatdan no, we have always unset no_new_privs explicitly as far as libseccomp is concerned see https://github.com/opencontainers/runc/blame/master/libcontainer/seccomp/seccomp_linux.go#L58

When it is used it is done explicitly, only if user requests it in `docker run`.

**Comment by crosbymichael** [comment]
@justincormack plus the daemon is not even starting so no way for this code to be hit and cause any type of problem.
