### ISSUE TITLE
 Error starting daemon: Error loading key file /etc/docker/key.json: unable to decode private key JWK: decoding JWK Private Key JSON data: unexpected end of JSON input

### ISSUE THREAD

**Issue by telphan** [docker/docker#23985]
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6
 Git commit:   20f81dd
 Built:        Fri May  6 21:33:59 2016
 OS/Arch:      linux/arm

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6
 Git commit:   20f81dd
 Built:        Fri May  6 21:33:59 2016
 OS/Arch:      linux/arm
```

**Steps to reproduce the issue:**
1. Start docker (e.g. let systemd start it for you)
2. Force docker to stop executing during its boot up sequence (e.g. cut power to the device just after systemd starts activating docker.service)
3. An empty key.json file should appear in /etc/docker/

**Describe the results you received:**

 Error starting daemon: Error loading key file /etc/docker/key.json: unable to decode private key JWK: decoding JWK Private Key JSON data: unexpected end of JSON input

**Comment by thaJeztah** [comment]
If it's really empty, perhaps we should ignore it. otoh, sounds like a legitimate error in this case

**Comment by telphan** [comment]
The file is empty and if we reach that state the code behaves as expected returning an error (fatal one). There needs to be a way of recovering from this failed state, because I do not consider this error fatal. Ignoring the 0 sized file is one way (it's the way we currently deal with this problem in our OS.

**Comment by thaJeztah** [comment]
Ideally, the write should be atomic (either the file is there, and properly written, or not be there), but ignoring an empty file in case it exists could be ok.

/cc @tonistiigi IIRC you handled with something similar as well?
