### ISSUE TITLE
Combined commands in Docker on Windows 1.12 RC2

### ISSUE THREAD

**Issue by ivansieder** [docker/docker#23991]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   a7119de
 Built:        Fri Jun 17 22:09:20 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 31
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host overlay bridge
Swarm: inactive
Runtimes: default
Default Runtime: default
Security Options: seccomp
Kernel Version: 4.4.13-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.951 GiB
Name: moby
ID: JNJ2:PZI2:RXSZ:FP7H:J23F:ZVG6:YQ6Q:UFYR:WH2F:DPNH:ZMMO:2MXL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Steps to reproduce the issue:**
1. `docker run -d ubuntu /bin/bash`
2. ``docker stop ````docker ps -a` `

**Describe the results you received:**
PS C:\> docker stop `docker ps -a`
unknown shorthand flag: 'a' in -a`
See 'docker stop --help'.

**Describe the results you expected:**
All containers should be stopped (works without issue on linux)

**Comment by dgageot** [comment]
Hi @ivansieder, from the `PS` prompt, I guess you are using PowerShell. Unfortunately, the syntax you want to use is bash specific. It will never be supported in PowerShell. It has nothing to do with docker.

@thaJeztah I guess it can be closed as wontfix

**Comment by thaJeztah** [comment]
Agreed, this does not look like an issue with docker, but with the capabilities of the shell you're running those commands in

**Comment by ivansieder** [comment]
@dgageot @thaJeztah oh damn me, sorry, didn't even think about the fact, that this could be the bash itself. Luckily, with upcoming bash on Win10 it will then hopefully also work on WinX. Thanks for clearing my missunderstanding.

**Comment by thaJeztah** [comment]
@ivansieder haha, no worries, no harm done :smile:

**Comment by StefanScherer** [comment]
Backticks are "bad". Use `docker stop $(docker ps -a)` and hey, works in bash an PowerShell :-)

**Comment by ivansieder** [comment]
@StefanScherer That's neat, thanks for that hint!

**Comment by ivansieder** [comment]
@StefanScherer looks like it's not working anymore by now. docker stop $(docker ps -a) results in "unknown shorthand flag: 'c' in -c

**Comment by ivansieder** [comment]
Okay, only needed thing was to add "docker stop $(docker ps -aq)" the 'q' at the end, so I just get the ID's

**Comment by otravers** [comment]
@ivansieder bash on Win10 doesn't help because it cannot "see" Windows apps such as Docker for Windows.

**Comment by ivansieder** [comment]
@otravers not sure about it, maybe the docker team will hack somehow through it like they did with exposing the ports to localhosts ^^
