### ISSUE TITLE
Escape character should not leak into another parse command

### ISSUE THREAD

**Issue by tonistiigi** [docker/docker#23999]
Escape character setting in Dockerfile seems to set a global variable meaning 2 `Parse()` commands will use the same variable with undefined behavior.

Also the unit tests in `builder/dockerfile/parser` do not expect the `tokenEscape` variable to be unset.

@jhowardmsft

**Comment by jhowardmsft** [comment]
It's initialised at https://github.com/docker/docker/blob/master/builder/dockerfile/parser/parser.go#L151 on every call into `Parse()`

**Comment by tonistiigi** [comment]
> Oh hang on - you're referring to two parallel builds for example, right?

Yes

**Comment by tonistiigi** [comment]
@jhowardmsft I think these tests failed because the `tokenEscape` is not set.

https://jenkins.dockerproject.org/job/Docker%20Master/label=ubuntu%20&&%20zfs/5933/console
https://jenkins.dockerproject.org/job/Docker%20Master/label=ubuntu%20&&%20zfs/5941/console

**Comment by thaJeztah** [comment]
Added to the 1.12 milestone, because it's a new feature in 1.12

**Comment by jhowardmsft** [comment]
I'm doubtful those tests failed on account of this as the code has been in a while now. But am working on a PR to remove the global and make it per build.

**Comment by tonistiigi** [comment]
fixed by #25080
