### ISSUE TITLE
TLS client ciphers usable by Docker daemon differ from those usable by Docker client -- makes little sense when using Content Trust with a proxy

### ISSUE THREAD

**Issue by dnwake** [docker/docker#24009]
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   20f81dd
 Built:        Thu May 12 18:41:29 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   20f81dd
 Built:        Thu May 12 18:41:29 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 20
 Running: 8
 Paused: 0
 Stopped: 12
Images: 21
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-8:3-4329060-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.11 GB
 Data Space Total: 107.4 GB
 Data Space Available: 105.3 GB
 Metadata Space Used: 3.875 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.95-RHEL6 (2015-09-08)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 3.10.0-327.18.2.el7.x86_64
Operating System: <unknown>
OSType: linux
Architecture: x86_64
CPUs: 40
Total Memory: 46.96 GiB
Name: compute-node3021
Https Proxy: docker:PASSWORD@web-proxy-vip:3128
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Set up a proxy running Squid 3.4
2. Configure the Docker daemon to use the proxy by setting HTTPS_PROXY in /etc/sysconfig/docker
3. Restart the Docker daemon
4. Try a Docker push / pull.  Result: successful
5. Now set HTTPS_PROXY on the command-line, and  try a Docker push/pull with Content Trust

**Describe the results you received:**
```
[ initial part of push succeeds ]
Signing and pushing trust metadata
ERRO[0001] Could not publish Repository: dial tcp 54.215.251.82:443: getsockopt: connection refused
Error: error contacting notary server: dial tcp 54.215.251.82:443: getsockopt: connection refused
```

Further inspection via tcpdump reveals that the Docker client was unable to handshake with the Proxy because they do not support a common cipher.

**Describe the results you expected:**
Pull succeeds fully

**Additional information you deem important (e.g. issue happens only occasionally):**

The Docker commandline supports only the ciphers TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 and TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256.  These are not supported by Squid 3.4.  However, the Docker daemon supports additional ciphers such as TLS_RSA_WITH_AES_128_CBC_SHA, which are supported by Squid 3.4.  This inconsistency makes no sense in the context of using Content Trust.

**Comment by riyazdf** [comment]
Relevant discussion in #804: we should not be downgrading the security of our supported TLS ciphers to support a deprecated server proxy

**Comment by cpuguy83** [comment]
Thanks @riyazdf! I agree.
