### ISSUE TITLE
Docker 1.12-rc2 complains if CONFIG_IP_VS is not set in kernel, please update contrib/check-config.sh

### ISSUE THREAD

**Issue by williamh** [docker/docker#24005]
A user reported the following error to me when starting docker:
WARN[0089] Running modprobe ip_vs failed with message: `modprobe: WARNING: Module ip_vs not found in directory /lib/modules/4.4.1-vanilla-docker-1`, error:
exit status 1
ERRO[0089] Could not get ipvs family information from the kernel. It is possible that ipvs is not enabled in your kernel. Native loadbalancing will not
work until this is fixed.
ERRO[0000] Failed to write to /proc/sys/net/ipv4/vs/conntrack: open /proc/sys/net/ipv4/vs/conntrack: no such file or directory

Can you please update the checker as requested?

?Also, for my information, is this a required setting, or will Docker work without it?

Thanks for your time,

William

**Comment by cpuguy83** [comment]
@williamh It's required for swarm routing to work.

**Comment by williamh** [comment]
Ok, cool, thanks for the explanation. :-)

**Comment by jbbr** [comment]
Where have you got this error message?
I've setup a swarm-mode cluster without any error messages but load balancing did not work - I later realized that my kernel is compiled without `ip_vs` which likely caused the problems.

**Comment by cpuguy83** [comment]
Adding to check-config in #24047
