### ISSUE TITLE
[1.12-rc2] RFC: should running "swarm init" multiple times be an error?

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#24006]
Currently, running `docker swarm init` [produces an error](https://github.com/docker/docker/blob/7ff546467de3fa3d1c1104e9f40c6d16742ebac0/daemon/cluster/cluster.go#L45-L46);

```bash
$ docker swarm init
Swarm initialized: current node (7gy7e5rqvo74rvyi6vu78jt2d) is now a manager.

$ docker swarm init
Error response from daemon: This node is already part of a Swarm cluster. Use "docker swarm leave" to leave this cluster and join another one.
```

- Should this second call be an Error, or just "info"?
- Given that I don't run `docker swarm join`, is there a reason to mention how to leave this swarm and join another one?

**Comment by tonistiigi** [comment]
1) I think this should give error code. Init is a very specific(and not idempotent) action that involves creating ca/blank raft state etc.
2) Error message could be better but I think mentioning `docker leave` is important.

**Comment by thaJeztah** [comment]
@tonistiigi yes, I wondered about that; perhaps from a *technical* viewpoint it's not idempotent, wondering if it is from a UX perspective; end result of calling it twice is the same

**Comment by tonistiigi** [comment]
@thaJeztah `swarm leave && swarm init` will give you a completely fresh state, it will not get you back to your original state. Also this is only one specific way to get this error and not really detectable from the others. If you joined another cluster, are a worker, were demoted, lost connectivity, lost quorum etc. then the fact that swarm mode is on doesn't mean that you can expect things that user can safely assume atm after running `swarm init`, like being accepted to the cluster, being active manager etc.

**Comment by thaJeztah** [comment]
> Also this is only one specific way to get this error and not really detectable from the others.

Ah, right, clear

**Comment by dnephin** [comment]
The error seems like the correct behaviour to me.

**Comment by thaJeztah** [comment]
Alright, let me close this for now, thanks for looking both!
