### ISSUE TITLE
Docker for Mac - Build dockerfiles than run behind corp firewall proxy

### ISSUE THREAD

**Issue by jjmiv** [docker/docker#24001]
I have reviewed the issues and have not found a concrete resolution for creating a dockerfile than will run behind specific proxy (HTTP_PROXY, etc) settings.

I have tried using ENV HTTP_PROXY, etc in the dockerfile but it does not build.  I would like to create a dockerfile that builds and runs with burned in corp proxy settings.

I am using the Docker for Mac beta to build and run the dockerfile.

**Comment by jonathanstiansen** [comment]
When you say you say you tried to put HTTP_PROXY into the docker file, what do you mean? From the HTTP_PROXY setting seen [here](https://docs.docker.com/engine/admin/systemd/) this option is meant for bootup with the docker daemon, meaning that each public facing service seems like it will need to be using the same proxy. 

Can someone confirm that way of reading it? It's a bit confusing.

**Comment by jjmiv** [comment]
i've use the ENV HTTP_PROXY and HTTP_PROXY variables/flags in the docker file and was able to build successfully but the container could not get internet access.  also tried building with --build-args

**Comment by cpuguy83** [comment]
What version of docker 4 mac are you using? IIRC it should be inheriting proxy settings from OSX.

**Comment by cpuguy83** [comment]
Closing as this should really go in https://forums.docker.com/c/docker-for-mac
It will be much easier to provide support there since this is likely to be a docker4mac issue.

Thanks!

**Comment by jjmiv** [comment]
it pulls from the Network Settings.  my company uses a .pac file.  I monitored that that forum for issues but did not see a specific issue.  i would put my notes in there.
