### ISSUE TITLE
Expose non-Manager external IP through API

### ISSUE THREAD

**Issue by alexmavr** [docker/docker#24017]
Managers are able to retrieve the IP address that is used to contact them through `node inspect` as `Node.ManagerStatus.Addr`, but there is no way for a non-manager to retrieve their own address. 

My recommendation is to add an `Addr` field to the `swarm.Info` struct which exposes the address that managers use to contact the current node in a `host:port` format.

**Comment by dperny** [comment]
I'm working on this.

**Comment by dperny** [comment]
#dibs

**Comment by alexmavr** [comment]
Updated the title and description to better represent that this is irrelevant to `--listen-addr`

**Comment by dperny** [comment]
#undibs

**Comment by alexmavr** [comment]
Relates to https://github.com/docker/swarmkit/issues/972

**Comment by thaJeztah** [comment]
@dperny what's the status on this one?

**Comment by dperny** [comment]
I talked to @alexmavr and @stevvooe about this the other day. It ended up being an XY question, and in either case the solution here is totally nontrivial to implement. I think we can close this? @alexmavr did you still need this?

**Comment by alexmavr** [comment]
Please don't close this issue, the underlying problem of not being able to retrieve a non-manager's external IP is still there. 

I believe there's existing work in implementing an `--advertise-addr`. If so, this issue could be rescoped to "Expose Advertise Address in non-manager nodes"

**Comment by mgoelzer** [comment]
@aluzzardi

**Comment by stevvooe** [comment]
There are several Host/IP fields that are relevant for a swarm (not all of these exist):

1. `Node.RemoteAddr` - IP address as detected by the dispatcher connection.
2. `NodeSpec.Addr` - Host or IP Addr, as set by the operator, should be used over others.
3. `Node.ManagerStatus.Addr` - IP Address as used in raft, seeded by `—advertise-addr` (or arguably, should be a part of `Node.Description`).
4. `Node.Description.Hostname` - The hostname as detected by the operating system.

They are all special and unique and have varying use cases.

I still don't understand the use case for `Node.RemoteAddr`. What are you going to do with it? There aren't any ports accessible from the outside.

**Comment by alexmavr** [comment]
The use case I'm describing would return `NodeSpec.Addr`, if it has been set by an operator, or `Node.RemoteAddr` otherwise.

**Comment by cmingxu** [comment]
All, I want to know is there a way to get node IP address temporarily or not that elegant before the feature publicly available?

**Comment by dperny** [comment]
Hey @cmingxu, right now there isn't. It's being worked on.

**Comment by tonistiigi** [comment]
@alexmavr If this is only for the user set `advertise-addr` I think we can expose it in `docker info` after https://github.com/docker/swarmkit/pull/1150 is merged. But this only works if user manually sets this property on join.

For the other cases there is no guarantee that an IP that is accessible from other nodes even exists and we don't want to show erroneous data. There is no need for the worker to have such IP as it doesn't expose any APIs on the network. With https://github.com/docker/swarmkit/pull/1121 the external IP is detected on manager startup by the other managers.

@aaronlehmann What's your take on this? If we accepted that this can show wrong data, I assume we should do the same thing https://github.com/docker/swarmkit/pull/1121 does, but in `ca.IssueCertificate` and save it as part of the Node object?

**Comment by alexmavr** [comment]
@tonistiigi would `advertise-addr` be exposed both in `docker info` and in `docker node inspect`?

Also, in the case where no `advertise-addr` is manually specified on join, would a `docker node inspect` reveal a `RemoteAddr` field or is that field hidden entirely from the external API?

**Comment by tonistiigi** [comment]
@alexmavr 
> would advertise-addr be exposed both in docker info and in docker node inspect?

Ideally not in `docker node inspect`. As it is implemented in docker/swarmkit#1150 it is not currently stored in raft. I think the current implementation expects docker to save it locally like it does atm with `listen-addr`. First time this address is actually used is with starting the manager.

> Also, in the case where no advertise-addr is manually specified on join, would a docker node inspect reveal a RemoteAddr field or is that field hidden entirely from the external API?

There is no field `RemoteAddr` stored with the `Node` object. In swarmkit/docker code and engine-api `RemoteAddr` refers to the manager address known to a worker.

**Comment by alexmavr** [comment]
@stevvooe how would an operator go about setting `NodeSpec.Addr`?

**Comment by stevvooe** [comment]
@tonistiigi These fields are proposals for fields that don't yet exist. `Node.RemoteAddr` would be a natural place for a field detected via dispatcher connection.

@alexmavr `docker node update --addr myhost.cluster`.

**Comment by aaronlehmann** [comment]
> If we accepted that this can show wrong data, I assume we should do the same thing docker/swarmkit#1121 does, but in ca.IssueCertificate and save it as part of the Node object?

No objection to doing something like this.
