### ISSUE TITLE
kernel version check in overlay2 is too strict

### ISSUE THREAD

**Issue by nathwill** [docker/docker#24023]
the kernel version check in the overlay2 driver appears to be unnecessarily restrictive for the case where the overlay driver support for multiple lower dirs has been backported, as it has in EL 7. from what i can tell, the 3.10 kernel in EL7 *does* support multiple lower directories, so should be supported. Here's my replication of the kernel docs' description of support for this feature in an EL 7.2 test-kitchen VM:

```bash
[root@docker-centos-72 ~]# uname -r
3.10.0-327.el7.x86_64
[root@docker-centos-72 ~]# mkdir -pv /lower1 /lower2 /lower3 /merged
mkdir: created directory ‘/lower1’
mkdir: created directory ‘/lower2’
mkdir: created directory ‘/lower3’
mkdir: created directory ‘/merged’
[root@docker-centos-72 ~]# touch /lower1/1.txt /lower2/2.txt /lower3/3.txt
[root@docker-centos-72 ~]#   mount -t overlay overlay -olowerdir=/lower1:/lower2:/lower3 /merged
[root@docker-centos-72 ~]# ls /merged/
1.txt  2.txt  3.txt
```

but on starting the daemon, it fails with error: `time="2016-06-28T05:17:20.646178896Z" level=fatal msg="Error starting daemon: error initializing graphdriver: driver not supported"`.

**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
[root@docker-centos-72 ~]# docker info
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

tested in VirtualBox

**Steps to reproduce the issue:**
1. install docker 1.12 rc on EL 7.2
2. run docker daemon with `--storage-driver=overlay2`
3. observe error

**Describe the results you received:**

docker daemon start failure due to initialization check for kernel version >= 4.0 when running docker with overlay2 storage driver on EL 7.2

**Describe the results you expected:**

success running docker with overlay2 storage driver on EL 7.2

**Comment by nathwill** [comment]
ok, i went ahead and created a dev-build with the check in question commented out and confirmed that the daemon does work with overlay2 on the EL 7.2 kernel.

Here's the test diff:

```diff
diff --git a/daemon/graphdriver/overlay2/overlay.go b/daemon/graphdriver/overlay2/overlay.go
index b48bcb9..e77db09 100644
--- a/daemon/graphdriver/overlay2/overlay.go
+++ b/daemon/graphdriver/overlay2/overlay.go
@@ -21,7 +21,7 @@ import (
        "github.com/docker/docker/pkg/directory"
        "github.com/docker/docker/pkg/idtools"
        "github.com/docker/docker/pkg/mount"
-       "github.com/docker/docker/pkg/parsers/kernel"
+//     "github.com/docker/docker/pkg/parsers/kernel"
 
        "github.com/opencontainers/runc/libcontainer/label"
 )
@@ -98,13 +98,13 @@ func Init(home string, options []string, uidMaps, gidMaps []idtools.IDMap) (grap
        }
 
        // require kernel 4.0.0 to ensure multiple lower dirs are supported
-       v, err := kernel.GetKernelVersion()
-       if err != nil {
-               return nil, err
-       }
-       if kernel.CompareKernelVersion(*v, kernel.VersionInfo{Kernel: 4, Major: 0, Minor: 0}) < 0 {
-               return nil, graphdriver.ErrNotSupported
-       }
+//     v, err := kernel.GetKernelVersion()
+//     if err != nil {
+//             return nil, err
+//     }
+//     if kernel.CompareKernelVersion(*v, kernel.VersionInfo{Kernel: 4, Major: 0, Minor: 0}) < 0 {
+//             return nil, graphdriver.ErrNotSupported
+//     }
 
        fsMagic, err := graphdriver.GetFSMagic(home)
        if err != nil {
```

and here's the result:

```bash
[root@docker-centos-72 ~]# uname -r
3.10.0-327.el7.x86_64
[root@docker-centos-72 ~]# docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.12.0-dev
Storage Driver: overlay2
 Backing Filesystem: xfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay bridge null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 489 MiB
Name: docker-centos-72
ID: OUEU:JR7F:V6HH:ZGTB:7KNN:HMOQ:ZCXK:NUEU:AC3J:AZ4W:ZUGI:WNUY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
[root@docker-centos-72 ~]# docker run ubuntu date
Tue Jun 28 06:12:22 UTC 2016
```

obviously checking for support for the required functionality is desirable, though, so i'm not really sure what the answer here should be 😕

**Comment by cpuguy83** [comment]
I don't think we can remove the check.... maybe an option to ignore the check... but I'm not too fond of that.

**Comment by nathwill** [comment]
@cpuguy83 yeah, it definitely seems important to check for support one way or another... would it be reasonable to check by exercising the functionality somehow?

**Comment by nathwill** [comment]
or maybe the version check can be downgraded to a warning?

**Comment by unclejack** [comment]
A warning wouldn't be OK. We've had similar issues in the past when we were only warning when the kernel wasn't at least version 3.8 and that turned out to be a time consuming problem, both for users and for the community as a whole. Lots of people had custom kernels which were somehow meant to get by with huge amounts of backports from newer kernels, but these weren't anywhere close to what 3.8 was at the time.

The right thing to do in this case is to attempt to use the features overlay2 requires when the kernel version requirement isn't met. The check for overlay2 support would fail when both the version check and this overlay2 features check code fail.

**Comment by dmcgowan** [comment]
I agree with @unclejack, a warning is not enough and we must enforce by default. The only other options besides doing nothing I see are add an overlay2 specific option to ignore kernel check or attempt to mount with multiple lowers to see if it is supported. If there is another way to probe the kernel to figure out if this is supported I would prefer that, but I just don't see checking for the feature by attempting a mount as a reasonable solution.  I am ok with adding an option which skips the kernel version check since it is explicit. Adding such a flag to the documentation is unfortunate, but don't see that as a good enough reason to not add it.

**Comment by vdemeester** [comment]
I agree with @dmcgowan on everything… I'm also ok with adding an option that would explicitely skip the kernel check, but not removing/lowering the check by default 👼

**Comment by thaJeztah** [comment]
We have the [`dm.override_udev_sync_check`](https://github.com/docker/docker/blob/bd37b8305275946c06793278425f9bb83d0bafa9/docs/reference/commandline/dockerd.md#L459), which also allows a user to override a check that would normally be "fatal", so I guess we could do something similar

**Comment by thaJeztah** [comment]
And, yes, "detection" would definitely be preferred, but if it's not possible

**Comment by dmcgowan** [comment]
thanks for link @thaJeztah, putting together a PR with a new option. I also like the idea of still issuing a warning even with the flag set.

**Comment by nathwill** [comment]
awesome, thanks @dmcgowan! really look forward to testing out the new driver!

**Comment by ssergiienko** [comment]
Confirm problem. I've tried to run overlay2 on CentOS 7 with kernel-ml=4.7.0 and docker reports that driver not supported

**Comment by thaJeztah** [comment]
@ssergiienko did you set `--storage-opt overlay2.override_kernel_check=1` on the daemon?

**Comment by ssergiienko** [comment]
@thaJeztah No... Will retry with it now. Thanks

**Comment by thaJeztah** [comment]
@ssergiienko that would just be a workaround though, because kernel 4.7 should support it, so either the kernel version check has a bug, or something is missing on your host. You can run the `check-config.sh` script to see if something stands out;
https://raw.githubusercontent.com/docker/docker/master/contrib/check-config.sh

**Comment by ssergiienko** [comment]
@thaJeztah Yep, you were right, problem was on our host. Now I retest it with both
kernel-ml 4.6.4 and kernel-ml 4.7.0 and all works fine with overlay2
Thanks for help!
