### ISSUE TITLE
[feature proposal] docker ps status/health UX change

### ISSUE THREAD

**Issue by jhorwit2** [docker/docker#24022]
```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                              PORTS               NAMES
3c16d5f74e39        nginx:latest        "nginx -g 'daemon off"   3 seconds ago       Up 2 seconds                        80/tcp, 443/tcp     test.1.1d2acd2imm80y1zqevcnp8ory
b09df8d0e51e        hc_test:latest      "nginx -g 'daemon off"   4 minutes ago       Up Less than a second (unhealthy)   80/tcp, 443/tcp     hc.5.83rrgliqdfncxoutcp8w5jxgy
00b06c034c65        hc_test:latest      "nginx -g 'daemon off"   4 minutes ago       Up Less than a second (unhealthy)   80/tcp, 443/tcp     hc.3.8q3nhanfyavahabvu53cl3gdf
```

Since services and standalone containers live in the same environment it seems their output should be pretty uniform. For example, why the container at the top of the `docker ps` above has no health check under status isn't clear. I'm proposing that `STATUS` stays the same as it was pre-healthchecks. The health status should be under a new column,`HEALTH` (taken from inspect field name), which can be `starting`, `healthy`, `unhealthy` or `unknown`. `unknown` would be a new enum value for `Health` struct, which simply means there are no health checks so the health can't be determined. 

This _seems_ pretty straightforward looking through the code so if it sounds good I was going to attempt a PR.

**Comment by hervenicol** [comment]
It would be nice if this feature could also enable health filters like this:
`docker ps --filter=health=unhealthy`

**Comment by jhorwit2** [comment]
I like the filter idea. Probably simpler to implement after looking through the code.

**Comment by talex5** [comment]
I think these are both sensible ideas (separate health column and health status filter).

**Comment by jhorwit2** [comment]
@talex5 If a separate health column is made you agree the `(<health_status>)` part of the status string should be removed? The biggest issue I had looking through the code was the coupling between State & Health. The `String()` method on State technically _should_ say something about the Health since it doesn't make sense to omit that. If we make them separate columns it almost makes sense to also make them not as coupled (move Health out of state directly onto the container). Otherwise it feels hacky to treat state/health differently.

**Comment by talex5** [comment]
Yes, I think it can be removed from `state.String` if you add an extra column instead. What uses the state string besides `docker ps`?

**Comment by jhorwit2** [comment]
@talex5 quick search shows only [exec](https://github.com/docker/docker/blob/master/daemon/exec.go#L56) does but it's just for an error message. Doubt it's any concern. 

I'll start working on the PR for multiple columns. 👍

**Comment by jhorwit2** [comment]
@talex5 (or @thaJeztah) - what's the best way to tackle a change in engine-api that's required in this repo? I need to add another field `Health string` to `types.Container` so I can get the health status for `ps`. Open that PR -> reference this ticket -> update vendor in my PR for this repo?

**Comment by thaJeztah** [comment]
@jhorwit2 you can open a PR in this repository, temporarily including the changes to the vendored code. That will make the "vendor" CI go read, but that's fine during design review. Once we're ok with design, and move to code-review, you can open a PR against the engine-api repository, and once merged, do a "vendor" update as part of your PR here.

We know it's a bit more complicated, and are currently discussing alternatives, but for now that's the best approach :smile:

**Comment by jhorwit2** [comment]
Sounds good! thanks @thaJeztah
