### ISSUE TITLE
docker volume sync issue

### ISSUE THREAD

**Issue by moypray** [docker/docker#24038]
Hi, I have run some containers using volumes which provided by volume plugins( e.g. convoy). I found that some tricky behavior under unexpected operation:

 1. create a volume using docker:

       ` docker volume create --name volume1 -d convoy -o size=10G`
 2.  using it in a container:

        `docker run -ti  -v volume1:/test busybox sh`
     And then exit the container.
 3.  delete the volume1 using plugins:

       `convoy delete volume1`
 4.  using docker to list volume.
      ` docker volume ls`
     result: there is no volume1 exists.  as docker will send volumedriver.List API to plugin to get all the volumes.

 5.  but we create a new volume named volume1 with  the same name:

     `docker volume create --name volume1  -d convoy -o size=10G`

expected result:
     create successfully.
but this operation  will fail, as docker thought the volume1 exist, and will not send volumedriver.Create API to plugin. 

**Investigatiion:
  I found that docker saves the volume name and driver to memory(a map), but a volume created by docker and deleted by plugin, in this condition, this volume in docker daemon will go to wrong state.**  

**Output of `docker version`:**

```
root@main-server:~/work/elara# docker version
Client:
 Version:      1.11.0-dev
 API version:  1.23
 Go version:   go1.5.2
 Git commit:   1d09425-unsupported
 Built:        Fri Mar 11 15:53:31 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 21:09:07 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 8
 Running: 0
 Paused: 0
 Stopped: 8
Images: 180
Server Version: 1.12.0-rc2
Storage Driver: devicemapper
 Pool Name: docker-253:1-267226-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 14.42 GB
 Data Space Total: 107.4 GB
 Data Space Available: 15.03 GB
 Metadata Space Used: 27.36 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.12 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local elara
 Network: bridge null host overlay
Kernel Version: 3.13.0-57-generic
Operating System: Ubuntu 14.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.798 GiB
Name: main-server
ID: MFW2:XZQG:XKPJ:HKJ7:7MIW:M4VF:ZCPN:TKAA:MUST:25SC:UYK2:GK5H
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
No Proxy: /var/run/docker.sock,192.168.0.1,rnd-dockerhub.huawei.com
WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
will happen all the time.

**Comment by yongtang** [comment]
I think this might be the same issue as #23367.

**Comment by cpuguy83** [comment]
Yes, this is a dup.
