### ISSUE TITLE
Add containers to a network docs incomplete

### ISSUE THREAD

**Issue by TrySpace** [docker/docker#24031]
I'm following the docs, and up until here everthing is clear:

https://docs.docker.com/v1.11/engine/userguide/containers/networkingcontainers/

Where the example states::

```
docker inspect --format='{{json .NetworkSettings.Networks}}'  db
{"my-bridge-network":{"NetworkID":"7d86d31b1478e7cca9ebed7e73aa0fdeec46c5ca29497431d3007d2d9e15ed99",
"EndpointID":"508b170d56b2ac9e4ef86694b0a76a22dd3df1983404f7321da5649645bf7043","Gateway":"172.18.0.1","IPAddress":"172.18.0.2","IPPrefixLen":16,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"02:42:ac:11:00:02"}}
```

Running this will result in an error, because those ID's do not exist locally.

But it is not clear which ID's I should use.

The previously mentioned ` docker network inspect my-bridge-network` in the doc-page does only output 1 ID.
Before that, with `docker network inspect bridge` it does output some similar IDs and macaddresses, but it is not clear which to use..

Both `7d86d31b1478e7cca9ebed7e73aa0fdeec46c5ca29497431d3007d2d9e15ed99` and `508b170d56b2ac9e4ef86694b0a76a22dd3df1983404f7321da5649645bf7043` are not mentioned before in the docs (at least not on the page), so I have no idea which to use for what...

It would be helpful to have some explanation of that command (i.e. `NetworkID`, which one? `EndpointID`, of what? `Gateway`? `MacAddress`?)

**Comment by joaofnfernandes** [comment]
Maybe you're misinterpreting the instructions. Try only running:
```
docker inspect --format='{{json .NetworkSettings.Networks}}'  db
```

The rest of the snippet is the result of running that command, and it shows that the container you've just launched is attached to the `my-bridge-network`.

**Comment by TrySpace** [comment]
That's probably it, thanks!
Other examples often span multiple lines, and the distinction between a command and the result isn't always clear in the docs, especially this one.

**Comment by joaofnfernandes** [comment]
This is a docs usability issue. I've created #24130, so that we can address this.
