### ISSUE TITLE
stop event is not emited 

### ISSUE THREAD

**Issue by sebi-hgdata** [docker/docker#24036]
**Output of `docker version`:**

```
~$ sudo docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
$ sudo docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64
seb@seb:~$ sudo docker info
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 383
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.3.0-040300-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.16 GiB
Name: seb
ID: 3IIK:AWIX:PLOR:BPQ4:XNEL:SSXQ:2GUL:VEKX:OVCQ:SCCX:MN2U:DTWH
Docker Root Dir: /home/seb/hgdata/deployments/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Cluster store: consul://localhost:8500
Cluster advertise: 192.168.123.209:2375

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical machine 

**Steps to reproduce the issue:**
1.sudo docker run -ti ubuntu:14.04.2 bash
2. ctrl + d  to stop the container

**Describe the results you received:**
 A stop event should be emited.

**Describe the results you expected:**
Seems like the stop event is not emited.

**Additional information you deem important (e.g. issue happens only occasionally):**
```
~$ sudo docker events
2016-06-28T11:57:18.959206039+03:00 container die 250ea3e5ccd0547e7d4b32019c85166cdc51eaf57753ef7ec9201649c6c4f82a (exitCode=0, image=ubuntu:14.04.2, name=jovial_kalam)
2016-06-28T11:57:19.118457334+03:00 network disconnect 948a1f377c073a5d3491610ff45006ce6d3f4623e453b6f0f87ab4a621ace227 (container=250ea3e5ccd0547e7d4b32019c85166cdc51eaf57753ef7ec9201649c6c4f82a, name=bridge, type=bridge)

```

**Comment by vdemeester** [comment]
@sebi-hgdata that is to be expected. The `stop` event is emitted if an explicit call to `stop` (vi cli `docker stop` or via the API) has been done. By exiting using `ctrl-d`, you're exiting the container, but from the docker point of view, the process died, and thus the event you see is `container die` and no `stop`.

**Comment by sebi-hgdata** [comment]
Looking at this diagram https://docs.docker.com/engine/reference/api/docker_remote_api/#docker-events I assumed a stop event should be emitted as the container will go to stopped state because no restart policy is used...

**Comment by vdemeester** [comment]
@sebi-hgdata in the diagram, the events are in *rectangle* boxes. Your case is "container process exited", and in this *flow* there is no rectangle with stop in it, no `stop` event emitted. The diagram is pretty clear, the only way to get a `stop` event, is with `docker stop` (or corresponding API call). 

The reliable way to know if a container has been stopped or not (no matter the way it stopped) is the event `die`.

**Comment by sebi-hgdata** [comment]
To comment around that diagram (probably not the best place here):
* it needs also to account for restart policy ```always``` for the docker stop and kill.
* and imo events should be triggered after reaching a state not before (probably this is how it's implemented) to not generate race condition for tools that rely on them.. that diagram probably should be updated

**Comment by sebi-hgdata** [comment]
What I was tryng to do and there is no clean way using ```docker events``` is to watch for containers that fail with #20398

**Comment by cpuguy83** [comment]
The diagram looks spot on to me.
`stop` event is triggered _only_ when `docker stop` is called -- this is what the diagram suggests. `stop` event is not triggered until the call to `stop` is complete.

I'm not sure I see an issue here.

**Comment by sebi-hgdata** [comment]
So stop,  is not really related to container's lifecycle, but to the commands that the daemon receives and executes upon the container. 
There is some confusion, as to what some of the events mean... like die vs stop.
Anyway, I'm ok to close this if you guys want.
