### ISSUE TITLE
Remote API JSON response wrongly formatted

### ISSUE THREAD

**Issue by eolognt** [docker/docker#24034]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   a7119de
 Built:        Fri Jun 17 22:09:20 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 19
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay bridge host
Swarm: inactive
Runtimes: default
Default Runtime: default
Security Options: seccomp
Kernel Version: 4.4.13-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.954 GiB
Name: moby
ID: GUOI:YNWK:5XKJ:BM7T:5WNG:NXCQ:DDWQ:2UCR:ZTTV:GJYK:WC3A:7USJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 26
 Goroutines: 36
 System Time: 2016-06-28T08:33:25.398230834Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
I use Dockerode to control my Docker with gulp. Thus this is regarding the remote API. So, I had some response from a call to the API that was supposed to be logged, and therefore it would be parsed with `JSON.parse()`, but then I got this error: 
```
undefined:2
{"status":"Status: Image is up to date for <name>/<name>:0.14.0"}
^

SyntaxError: Unexpected token {
    at Object.parse (native)
```
The response in whole looked like this: 
```
{"status":"Digest: sha256:238120725fa1945cd92e3246af2f8834f447c178033da934640923968d54c383"}
{"status":"Status: Image is up to date for <name>/<name>:0.14.0"}
```
**Describe the results you expected:**
I expect that the response should be correctly formatted as JSON, so when I do `JSON.parse()` it will work as expected. Even the example on the API reference site is wrongly formatted: https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/ (look under "Build image from a Dockerfile")

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment]
This is a json stream, not an `application/json` response.
You would need to use a streaming decoder to decode the json, or break at new lines (line delimited json).
