### ISSUE TITLE
Pull problem from Docker UCP

### ISSUE THREAD

**Issue by Flodu31** [docker/docker#24035]
Hello,
I'm contacting you because I have a problem to pull an image from a DTR repo.

From the server itself (in ssh), it works without problem.
From the UCP control panel, I have the following error:

`Get https://dtr.toto.com/auth/token?scope=repository:fappointaire/floapp-website:pull&service=dtr.toto.com: x509: certificate signed by unknown authority`

Any idea?
Thanks.
Florent

**Comment by cpuguy83** [comment]
The SSL cert is not signed by a trusted CA.

Please contact support@docker.com for requests regarding UCP and DTR.

**Comment by Flodu31** [comment]
Hello,

I checked with the support and it's a bug handled by the engineering team.
I'll keep you updated when the fix will be out.

FYI, it's an AD CS PKI.
