### ISSUE TITLE
Install script broken for RHEL 7.2

### ISSUE THREAD

**Issue by adamjk-dev** [docker/docker#24039]
```
# ./install-docker.sh 
in do_install()
debug do_install3 lsb_dist=redhatenterpriseserver

  Either your platform is not easily detectable, is not supported by this
  installer script (yet - PRs welcome! [hack/install.sh]), or does not yet have
  a package for Docker.  Please visit the following URL for more detailed
  installation instructions:

    https://docs.docker.com/engine/installation/
```

The box is a Virtual Machine. 

```
cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.2 (Maipo)
```

**Steps to reproduce the issue:**
1. RHEL 7.2 box
2. curl -fsSL https://test.docker.com/ | sh

**Describe the results you received:**
The install script doesn't handle the RHEL 7.2 distribution correctly. The case statement in do_install() looks for redhat, but in my case lsb_dist=RedHatEnterpriseServer.

**Describe the results you expected:**
The test version of Docker to be installed on my RHEL 7.2 box (1.12.x).

**Comment by thaJeztah** [comment]
Thanks for reporting!

**Comment by streetmapp** [comment]
Can also confirm this being an issue. To get around this issue, brought the script locally to my machine, and hardcoded the URL being created dynamically to check the **centos** branch. This did install docker-engine successfully.

**Comment by wraithfive** [comment]
I'm also running RHEL 7.2 and the install script detects the distrubution just fine. It sets up an invalid YUM repo however. 
lsb_dist is set to redhat without issue. 

However the case starting at line 439 seems to be the bug:

   439                 fedora|centos|redhat|oraclelinux)
    440                         $sh_c "cat >/etc/yum.repos.d/docker-${repo}.repo" <<-EOF
    441                         [docker-${repo}-repo]
    442                         name=Docker ${repo} Repository
    443                         baseurl=${yum_url}/repo/${repo}/${lsb_dist}/${dist_version}
    444                         enabled=1
    445                         gpgcheck=1
    446                         gpgkey=${yum_url}/gpg
    447                         EOF
    448                         if [ "$lsb_dist" = "fedora" ] && [ "$dist_version" -ge "22" ]; then
    449                                 (
    450                                         set -x
    451                                         $sh_c 'sleep 3; dnf -y -q install docker-engine'
    452                                 )
    453                         else
    454                                 (
    455                                         set -x
    456                                         $sh_c 'sleep 3; yum -y -q install docker-engine'
    457                                 )
    458                         fi
    459                         echo_docker_as_nonroot
    460                         exit 0
    461                         ;;


On line 443 you use the value of lsb_dist to build the base url but the only repos available on https://yum.dockerproject.org/repo/testing/ are for centos, fedora, opensuse, and oraclelinux. So when using redhat you will not end up with a valid repo url in the yum repo entered in yum.repos.d. 

The script for get.docker.com just sets lsb_dist to centos if the dist is redhad and doesn't have a case for redhat at all. I suspect that similar logic is needed here.

**Comment by wraithfive** [comment]
It looks like 73d5f0648e430a74cd05ff9fd335611ddc6dd2a1 fixes this but isn't what is pulled from https://test.docker.com

**Comment by thaJeztah** [comment]
@wraithfive correct, https://github.com/docker/docker/pull/23867 is to fix the "redhat" issue, but I don't think it takes `redhatenterpriseserver` into account (yet). That script is not yet published on test.docker.com, and will go out with the RC3 (I can check if we can update it before that)

**Comment by thaJeztah** [comment]
Actually, it may resolve it; @adamjk-dev are you able to test if the current master version of this script works for your case? https://raw.githubusercontent.com/docker/docker/master/hack/install.sh

**Comment by adamjk-dev** [comment]
# ./install.sh 

  Either your platform is not easily detectable, is not supported by this
  installer script (yet - PRs welcome! [hack/install.sh]), or does not yet have
  a package for Docker.  Please visit the following URL for more detailed
  installation instructions:

    https://docs.docker.com/engine/installation/

**Comment by thaJeztah** [comment]
Ah, you're right, I was looking at https://github.com/docker/docker/blob/master/hack/install.sh#L245-L247, but that's not used if `lsb_release` is used; does `lsb_release -si` output `RedHatEnterpriseServer` (camel-case), or `redhatenterpriseserver` (all lowercase)?

**Comment by thaJeztah** [comment]
Oh, never mind, we convert it to lowercase https://github.com/docker/docker/blob/master/hack/install.sh#L252

**Comment by adamjk-dev** [comment]
I am working on a fix and will do a pull request.

**Comment by thaJeztah** [comment]
@adamjk-dev oh, sorry, missed your comment; I think I have something ready, but let me know if it differs from your approach; https://github.com/docker/docker/compare/master...thaJeztah:fix-install-script-for-redhatenterpriseserver

**Comment by adamjk-dev** [comment]
I like it, our code differs but same net effect. Go with yours. I don't know how they push these scripts out to be served (to test|get|experimental.docker.com), but we need to push to all 3 of those. Thanks!

**Comment by thaJeztah** [comment]
Thanks for checking @adamjk-dev, I'll open a PR!

**Comment by adamjk-dev** [comment]
Wait.... I thought I had this working a minute ago... but it still might have an issue. I ran the raw script you had edited and submitted:

```
./install.sh 
+ sh -c 'sleep 3; yum -y -q install docker-engine'
https://yum.dockerproject.org/repo/main/centos/Maipo/repodata/repomd.xml: [Errno 14] HTTPS Error 403 - Forbidden
Trying other mirror.
To address this issue please refer to the below knowledge base article

https://access.redhat.com/solutions/69319

If above article doesn't help to resolve this issue please open a ticket with Red Hat Support.

Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
https://yum.dockerproject.org/repo/main/centos/Maipo/Packages/docker-engine-1.11.2-1.el7.centos.x86_64.rpm: [Errno 14] HTTPS Error 403 - Forbidden
Trying other mirror.
https://yum.dockerproject.org/repo/main/centos/Maipo/Packages/docker-engine-selinux-1.11.2-1.el7.centos.noarch.rpm: [Errno 14] HTTPS Error 403 - Forbidden
Trying other mirror.


Error downloading packages:
  docker-engine-selinux-1.11.2-1.el7.centos.noarch: [Errno 256] No more mirrors to try.
  docker-engine-1.11.2-1.el7.centos.x86_64: [Errno 256] No more mirrors to try.
```

It is currently looking at https://yum.dockerproject.org/repo/main/centos/Maipo/repodata, but I think it should be looking at https://yum.dockerproject.org/repo/main/centos/7/repodata

**Comment by thaJeztah** [comment]
oh, hm, darn. Can you comment on my PR? Let me see if i can find something for that :cry:

**Comment by adamjk-dev** [comment]
I know the issue, its b/c it skips the first case statement, so we need to special case and set it to redhat right after it does the lowercase. I will push to my repo and show you.

**Comment by adamjk-dev** [comment]
This works. We have to set it to 'redhat' earlier on so it makes it into both case statements. Then, below, it will no longer be 'redhatenterpriseserver', so we can just special case 'redhat'.

https://github.com/adamjk-dev/docker/commit/290afda51c3fd238e234f0386bf83d8777b4c6db

**Comment by thaJeztah** [comment]
@adamjk-dev alright, can you open a pull-request for that? I can close mine after you opened it

**Comment by thaJeztah** [comment]
fixed by https://github.com/docker/docker/pull/24069
