### ISSUE TITLE
Question: Is it necessary to support command `docker stack services STACK`?

### ISSUE THREAD

**Issue by allencloud** [docker/docker#24042]
Hi, All, 

I found the experimental feature **STACK** is in docker 1.12-rc2, and I do like this to help me orchestrate  distributed apps.

While when I was experiencing this feature, still met some confusion. The biggest confusion is that when I deploy a stack via `docker stack deploy`, services in a dab will be deployed.

Then I hope to show services in a stack, there is no way. And there is only tasks display.

Here is my confusion and maybe need some discussion: Is it necessary to support command `docker stack services STACK`?

**Comment by allencloud** [comment]
any update?

**Comment by dnephin** [comment]
That seems like it would be appropriate.

**Comment by allencloud** [comment]
I think the related pr is merged. We can close this.
