### ISSUE TITLE
Improved status for docker pull

### ISSUE THREAD

**Issue by mahendra** [docker/docker#2404]
It would be good to have the docker pull return better status messages. For eg: a docker pull can result in following statuses

* command failed
* no new data was pulled
* new data was pulled

This will be effective when docker pull is used in scripts and systems like salt. The user would want to restart the container only if docker pull actually did something. Right now, the output is quite complex and not easily parse-able

It may be good for a command line switch which will dump the REST API json as the output. Scripts can parse it.

**Comment by cpuguy83** [comment]
This was resolved by #8213 but didn't get autoclosed.
