### ISSUE TITLE
[1.12-rc2] Is there a way to configure the `docker_gwbridge` network?

### ISSUE THREAD

**Issue by dtmistry** [docker/docker#24046]
I've a few hosts on AWS running docker 1.12-rc2.  

When I do a `docker swarm init` docker creates a `docker_gwbridge` network in the 171.17.0.0/16 subnet. 

This is an issue for me because I'm on a network which has 172.17.0.0/16 subnet.  

Is there a way for me to configure this bridge network? May be a dockerd option?

**Output of `docker version`:**
```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:45:29 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:45:29 2016
 OS/Arch:      linux/amd64
```
**Output of `docker info`:**
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.0-rc2
Storage Driver: overlay
 Backing Filesystem: xfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: active
 NodeID: bn59osbgdlxzsj2ecv2l2igfa
 IsManager: Yes
 Managers: 1
 Nodes: 1
 CACertHash: sha256:a2ef7bdc734e14d48f34e2b882261be50cf4053d491f30f87bfca9772c4e10b5
Runtimes: default
Default Runtime: default
Security Options: seccomp
Kernel Version: 3.10.0-327.22.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 991.7 MiB
Name: ip-172-28-50-207.cars.comclassifiedventures.comcorp.classifiedve
ID: 4X7G:YMSU:B6OD:EGGB:HMYP:7EUW:BFFB:26AW:VCMA:4VGT:NXMT:5EG4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 41
 Goroutines: 108
 System Time: 2016-06-28T13:05:21.156855875-04:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
 ```
**Additional environment details (AWS, VirtualBox, physical, etc.):**  

Docker 1.12.0-rc2 running on RHEL 7 AMI

/etc/systemd/system/docker.service.d/docker.conf
```
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd -D -H fd:// --bip=10.11.12.1/24
```
$ docker network inspect docker_gwbridge
```
[
    {
        "Name": "docker_gwbridge",
        "Id": "aa9e823759a6909290ade98e80982f44fa9d0e58b927916a46e28f909c7f2f89",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1/16"
                }
            ]
        },
        "Internal": false,
        "Containers": {
            "ingress-sbox": {
                "Name": "gateway_ingress-sbox",
                "EndpointID": "c63f99abcda719bd157a454a717610e23975d020e191ea61a57523b239f439ac",
                "MacAddress": "02:42:ac:11:00:02",
                "IPv4Address": "172.17.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.bridge.enable_icc": "false",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.name": "docker_gwbridge"
        },
        "Labels": {}
    }
]
```

**Comment by aboch** [comment]
@dtmistry Have you tried to delete it, then recreate it with same name and your chosen `--subnet`.
docker should not overwrite it if it already exists.

**Comment by mavenugo** [comment]
@dtmistry the simplest option is for you to create this `default_gwbridge` by hand instead of letting the daemon create it automatically.

You can create it using the following command - 

`docker network create --subnet={Your prefered subnet } -o com.docker.network.bridge.enable_icc=false -o com.docker.network.bridge.name=docker_gwbridge docker_gwbridge`

**Comment by aboch** [comment]
@dtmistry Please follow @mavenugo's suggestion, I forgot about the options.

**Comment by mrjana** [comment]
@dtmistry Can you tell me more about your environment? Does the docker host where you are trying this has a host interface which is in 172.17.x.x/16 subnet? If so, docker_gwbridge should've chosen a different subnet. If this is indeed the case, then it smell like a bug in libnetwork which we should fix

**Comment by dtmistry** [comment]
@mrjana No, the docker host where I'm starting the Swarm cluster does not have a host interface in 172.17.x.x/16 subnet. It just happens that the network from where I'm trying to connect to the manager node is in that subnet.

**Comment by mavenugo** [comment]
@dtmistry if a `docker_gwbridge` network is already present, daemon will not override it.

>> Also, can/should this be configured with daemon options? That way I won't have to create this network on manually on all nodes

Even if we introduce a daemon option, you have to enable it on all the daemons on all the nodes any ways. So, it isn't a huge difference for you either ways. Atleast in the idea suggested above, you dont have to wait for a new docker release :-)

**Comment by dtmistry** [comment]
@mavenugo Fair enough :)

**Comment by mavenugo** [comment]
closing this issue now. Pls let us know if you still see a need to keeping this open.

**Comment by dtmistry** [comment]
@mavenugo All good. I was able to manually create the network on all nodes and init the cluster. Thanks.

**Comment by marceloslacerda** [comment]
Why can't dockerd use --bip to decide on what subnet to create the network? I'm having problems with docker creating more interfaces on that subnet(172.17.0.0/16) depending on the docker service that's being brought up.

**Comment by jalmansor** [comment]
I'm actually running into this being an issue as well. If anything, I don't see why this couldn't be done during the swarm init and join, since that's when docker_gwbridge is getting created.

**Comment by isavcic** [comment]
If I'm not mistaken, the line @mavenugo suggested wouldn't create the network with identical options as Docker would create by itself.

I've used this instead:
```
docker network create \
--subnet={Your preferred subnet} \
--gateway {First IP of your preferred subnet} \
-o com.docker.network.bridge.enable_icc=false \
-o com.docker.network.bridge.name=docker_gwbridge \
-o com.docker.network.bridge.enable_ip_masquerade=true \
docker_gwbridge
```

**Comment by sm1988** [comment]
@mavenugo, Please suggest possible solution to below use-case.

I want my docker container to get the IP address from my org's routed network (lets assume 192.168.10.0/24). There is a DHCP server running within this network outside the docker host (management IP of host is 192.168.10.10/24).
how do I force docker0 or docker_gwbridge to be a part of this network and allocate the IP from the pool. 

Thanks!
Shishir
