### ISSUE TITLE
Docker for Mac: com.docker.docker/Data/*00000003.00000948: connect: connection refused

### ISSUE THREAD

**Issue by johker01** [docker/docker#24045]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   a7119de
 Built:        Fri Jun 17 22:09:20 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 22
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: default
Default Runtime: default
Security Options: seccomp
Kernel Version: 4.4.13-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.788 GiB
Name: moby
ID: XW4O:XEF3:TSZX:XJHQ:W7QB:675K:S5YA:FJ7E:P46X:BBFM:YN53:P5HL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 21
 Goroutines: 29
 System Time: 2016-06-28T15:22:19.160120135Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. `docker pull choerst/centoscppbuild:latest`
2. 'docker run --rm -it -v "$PWD":/workspace -w /workspace/project choerst/centoscppbuild:latest ant'

**Describe the results you received:**
I received an error message stating the following:

````
Error response from daemon: dial unix /Users/johker/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused
```

**Describe the results you expected:**
I expected the ant build to complete without any issues. It worked well when using virtualbox via docker toolbox, but now after switching to Docker for Mac, I experience issues.

**Additional information you deem important (e.g. issue happens only occasionally):**
Docker is set to use 4 CPUs and 8GB of memory.
The ant build first builds a large C++ project by calling make, then runs rpmbuild to package the project as an RPM.

**Comment by davidgibbons** [comment]
I'm having a similar issue running a cpu intensive go process within a docker container on 1.12 with Docker for Mac.  This appears to be crashing the docker daemon process or VM on Mac, as the docker status goes to "Restarting" after the connection message.

**Comment by thaJeztah** [comment]
I opened https://github.com/docker/pinata/issues/4163 for tracking (sorry it's a private issue tracker, so you won't be able to follow that link)

**Comment by justincormack** [comment]
Hi, the reproduction instructions are not sufficient, it is looking for a `build.xml`, do you have a standalone reproduction?

**Comment by johker-wst** [comment]
Unfortunately, I don't. What I observed, however, is that executing make or ant in the container works well if the amount of data to be compiled is small. If it's bigger, I get an error message. Instead of calling ant, this time, I executed make and a very similar thing happend

```
/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/as: BFD version 2.23.52.0.1-10.el6 20130226 assertion fail elf.c:2552
/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/as: BFD version 2.23.52.0.1-10.el6 20130226 assertion fail elf.c:2552
{standard input}: Fatal error: can't close /workspace/daemons/bin/release/daemons/load_scheduler/algorithm/ParallelismManager.o: No space left on device
make[2]: *** [/workspace/daemons/bin/release/daemons/load_scheduler/algorithm/ParallelismManager.o] Error 1
make[1]: *** [daemons-compile-link] Error 2
/workspace/services/sources/services/error/ExternalMessageList.cpp:177:1: fatal error: opening dependency file /workspace/services/bin/release/services/error/ExternalMessageList.d: Transport endpoint is not connected
compilation terminated.
{standard input}: Assembler messages:
{standard input}: Fatal error: can't write /workspace/services/bin/release/services/error/ExternalMessageList.o: No space left on device
/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/as: BFD version 2.23.52.0.1-10.el6 20130226 assertion fail elf.c:2552
/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/as: BFD version 2.23.52.0.1-10.el6 20130226 assertion fail elf.c:2552
...
/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/as: BFD version 2.23.52.0.1-10.el6 20130226 assertion fail elf.c:2552
{standard input}: Fatal error: can't close /workspace/services/bin/release/services/error/ExternalMessageList.o: No space left on device
make[2]: *** [/workspace/services/bin/release/services/error/ExternalMessageList.o] Error 1
make[2]: *** wait: No child processes.  Stop.
make[1]: *** [services-compile-link] Error 2
/workspace/driver/sources/initializer/main.cpp:411:1: fatal error: opening dependency file /workspace/driver/bin/release/initializer/main.d: Transport endpoint is not connected
compilation terminated.
Error response from daemon: dial unix /Users/johker/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused
```

**Comment by davidgibbons** [comment]
` docker run --rm --name nr jfindley/newrelic-exporter /src/newrelic_exporter  -api.key=NEWRELICAPIKEYHERE `

then curl localhost:9126/metrics

The problem with reproducing mine is it requires a new relic api key and new relic account with lots of data in it. I can't very well share my api key.

**Comment by jaronoff97** [comment]
Is there a solution to this issue yet?

**Comment by samoht** [comment]
@jaredhocutt it is very hard to work on a solution without a reliable way to reproduce. Can you also maybe run the diagnostic tool (by clicking on the 🐳  icon) to upload the logs on S3 and give us your diagnostic ID? Thanks!

Or do you have interesting messages in `Console.app` about `com.docker*` process?

**Comment by theartoflogic** [comment]
I'm seeing this same issue using the stable Docker for Mac v1.12.0 (build: 10871). I don't have exact repro steps, but I do have some info from Console.app that may be useful in debugging.

Firstly, I'm starting up a bunch of containers using a Docker Compose file. There are 13 containers and 5 volumes listed in the Docker Compose file. I'm starting them using `docker-compose up -d`.

The first warning I see in Console.app is the following (this happens about 1 minute after I execute the `docker-compose up -d` command):

```
8/1/16 3:05:54.000 PM kernel[0]: process com.docker.hyper[88710] caught causing excessive wakeups. Observed wakeups rate (per sec): 734; Maximum permitted wakeups rate (per sec): 150; Observation period: 300 seconds; Task lifetime number of wakeups: 45001
```

The previous warning may or may not be related to this ticket, so if not then it can be ignored. However, when Docker finally crashes (or at least all the containers crash), I see a bunch of logs output to Console.app, the first 2 being:

```
8/1/16 3:07:11.515 PM Docker[88707]: Error reading /etc/resolv.conf: reading /etc/resolv.conf: Uwt.Uwt_error(Uwt.ENFILE, "uv_fs_open", "/etc/resolv.conf")
8/1/16 3:07:11.515 PM Docker[88707]: DNS[b80f] No upstream DNS server configured: dropping request
```

Those two lines are output together, in pairs, about 5 times, followed by the following:

```
8/1/16 3:07:13.141 PM Docker[88708]: virtio-9p: unexpected EOF reading -- did the 9P server crash?
8/1/16 3:07:13.142 PM Docker[88707]: dispatcher caught Caught EOF on underlying FLOW: no more responses will be handled
8/1/16 3:07:13.142 PM Docker[88707]: Sending disconnection to request with tag 1
8/1/16 3:07:13.142 PM Docker[88707]: transport layer has disconnected
8/1/16 3:07:13.142 PM Docker[88707]: attempting to reconnect to database
8/1/16 3:07:13.142 PM Docker[88708]: Error from config.Wait: %s EOF
8/1/16 3:07:13.142 PM Docker[88708]: I should reboot
8/1/16 3:07:13.142 PM Docker[88706]: dispatcher caught Caught EOF on underlying FLOW: no more responses will be handled
8/1/16 3:07:13.142 PM Docker[88708]: Error from config.Wait: %s EOF
8/1/16 3:07:13.142 PM Docker[88708]: I should reboot
8/1/16 3:07:13.142 PM Docker[88427]: Failed to watch for updates: EOF
8/1/16 3:07:13.142 PM Docker[88708]: Error from config.Wait: %s EOF
8/1/16 3:07:13.143 PM Docker[88708]: I should reboot
8/1/16 3:07:13.143 PM Docker[88708]: sending SIGTERM to com.docker.hyperkit pid 88710
8/1/16 3:07:13.143 PM Docker[85065]: Reap com.docker.db (pid 88424): exit status 2
8/1/16 3:07:13.179 PM Docker[88708]: Error reading vsyslog length: EOF
8/1/16 3:07:13.180 PM Docker[88706]: Fatal unexpected exception: Socket.Closed
8/1/16 3:07:13.181 PM Docker[88707]: PPP.listen: closing connection
8/1/16 3:07:13.188 PM Docker[85065]: Reap com.docker.osxfs (pid 88706): exit status 1
8/1/16 3:07:13.891 PM Docker[88708]: transaction.Write%!(EXTRA []interface {}=[]) closed
8/1/16 3:07:13.896 PM Docker[85065]: Reap com.docker.driver.amd64-linux (pid 88708): exit status 1
8/1/16 3:07:14.145 PM Docker[88427]: Failed to watch the com.docker.driver.amd64-linux/state/ directory in the database: closed
8/1/16 3:07:14.150 PM Docker[85065]: Stop 1 children with order 1: com.docker.driver.amd64-linux (pid 88708)
8/1/16 3:07:14.150 PM Docker[85065]: Stop 2 children with order 2: com.docker.osxfs (pid 88706), com.docker.slirp (pid 88707)
8/1/16 3:07:14.151 PM Docker[85065]: Signal terminated to com.docker.slirp (pid 88707)
8/1/16 3:07:14.187 PM Docker[85065]: Reap com.docker.slirp (pid 88707): signal: terminated
8/1/16 3:07:14.251 PM Docker[85065]: Stop 1 children with order 3: com.docker.osx.hyperkit.linux (pid 88427)
8/1/16 3:07:14.251 PM Docker[85065]: Signal terminated to com.docker.osx.hyperkit.linux (pid 88427)
8/1/16 3:07:14.254 PM Docker[89087]: unexpected EOF
8/1/16 3:07:14.254 PM Docker[85065]: Reap com.docker.osx.hyperkit.linux (pid 88427): signal: terminated
8/1/16 3:07:14.296 PM Docker[85052]: frontend process failed
8/1/16 3:07:14.355 PM Docker[85065]: Stop 1 children with order 4: com.docker.db (pid 88424)
```

It then looks like Docker tries to restart, as the following lines are output:

```
8/1/16 3:07:14.355 PM Docker[85065]: Starting com.docker.db, com.docker.osx.hyperkit.linux, com.docker.osxfs, com.docker.slirp, com.docker.driver.amd64-linux
8/1/16 3:07:14.359 PM Docker[85065]: Start com.docker.db (pid 89101)
8/1/16 3:07:14.362 PM Docker[85065]: Start com.docker.osx.hyperkit.linux (pid 89102)
8/1/16 3:07:14.366 PM Docker[85065]: Start com.docker.osxfs (pid 89103)
8/1/16 3:07:14.370 PM Docker[85065]: Start com.docker.slirp (pid 89104)
8/1/16 3:07:14.374 PM Docker[85065]: Start com.docker.driver.amd64-linux (pid 89105)
8/1/16 3:07:14.377 PM Docker[89102]: API server starting
...
```

There is more output related to the startup, but I'm not sure if it would be beneficial.

**Comment by vielmetti** [comment]
I just saw this error on my Docker for Mac. 

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 810, in __bootstrap_inner
  File "threading.py", line 763, in run
  File "compose/cli/log_printer.py", line 149, in tail_container_logs
  File "compose/cli/log_printer.py", line 179, in wait_on_exit
  File "compose/container.py", line 239, in wait
  File "site-packages/docker/utils/decorators.py", line 21, in wrapped
  File "site-packages/docker/api/container.py", line 441, in wait
  File "site-packages/docker/client.py", line 174, in _raise_for_status
APIError: 500 Server Error: Internal Server Error ("dial unix /Users/emv/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused")
```

I don't know if this does anything more than say "also crashed for me", this is a first time crash in this particular environment.

**Comment by tailhook** [comment]
It looks like this bug is correlated to this bug of ringbuf implementation in hyperkit: https://github.com/docker/hyperkit/issues/50

**Comment by dsheets** [comment]
It is very hard to diagnose this issue without either or both of:

1. Reproduction
2. Docker for Mac diagnostic ID

We currently have a UI issue (internal docker/pinata#4551) with the diagnostic upload process so you will need to post your diagnostic ID and *at least click* the `Open Issues` button in the `Diagnose & Feedback` window. You needn't open a new issue but, currently, diagnostic upload is linked to that button.

It is quite likely that there are multiple different underlying causes for the defects reported in this issue. Diagnostic upload and posting of IDs will help us to understand exactly which components are ultimately at fault (many scary log messages are downstream failure cascades from the source).

Thanks!

**Comment by warik** [comment]
Diagnostic ID: 632FEE50-80F7-457A-9CBD-AFEB320F6577

Diagnostic was made and upload immediately after crash same as one explained earlier.

Actually I can reproduce this behaviour pretty regular sending big response (3-5Mb of static) from web application running in docker.

**Comment by dsheets** [comment]
@warik your crashes look like those that @tailhook identified in docker/hyperkit#50, thanks for posting your diagnostic.

Other passersby, your issue may not have docker/hyperkit#50 as its root cause. It is best to upload your diagnostics and report the diagnostic ID or confirm yourself that the errors in your logs look like the error in docker/hyperkit#50. The high level symptom could be caused by any number of underlying problems.

**Comment by gluxon** [comment]
If anyone needs an immediate solution to this and is willing to manually modify the com.docker.hyperkit binary, I have a small patch that increases the `VTSOCK_REPLYRINGSZ` constant from 512 to 1024.

[vtsock_replyringsz_increase.bsdiff.zip](https://github.com/docker/hyperkit/files/405652/vtsock_replyringsz_increase.bsdiff.zip)

```sh
brew install bsdiff
mv /Applications/Docker.app/Contents/MacOS/com.docker.hyperkit /Applications/Docker.app/Contents/MacOS/com.docker.hyperkit.original
bspatch /Applications/Docker.app/Contents/MacOS/com.docker.hyperkit.original /Applications/Docker.app/Contents/MacOS/com.docker.hyperkit vtsock_replyringsz_increase.bsdiff
```

Important notes:
1. **If you apply this patch, unpredictable behavior can occur.** This is a workaround of the issue tailhook identified and not an official remedy.
2. If you experience crashes after applying this patch, it's possible that your crash was another problem, or was caused by the increased reply ring size. **In respect to docker developers, restore the original hyperkit file before submitting a diagnostic if crashes continue.**
3. This will break code signing of the hyperkit.

This worked well for me, but if it causes excessive problems for others, I can remove this patch (dirty hack) by request.

**Comment by tailhook** [comment]
@gluxon can you provide instructions how to reproduce the patch? I.e. how to build hyperkit from sources and replace it.

**Comment by ijc25** [comment]
I'd just like to reiterate what @dsheets said above (https://github.com/docker/docker/issues/24045#issuecomment-237901919), from the information posted here so far only @warik, @gluxon and @tailhook appear to be suffering from docker/hyperkit#50.

For everyone else (at least @johker-wst, @davidgibbons, @jaronoff97, @theartoflogic and @vielmetti at this point)  there is not enough information to conclude one way or another if you are seeing the same issue, the `com.docker.docker/Data/*00000003.00000948: connect: connection refused` symptom is common to any number of underlying failures (essentially failure to communicate for any reason will show up like this). To reiterate what @dsheets says upthread (https://github.com/docker/docker/issues/24045#issuecomment-237823247):

> It is very hard to diagnose this issue without either or both of:
> 
> * Reproduction
> * Docker for Mac diagnostic ID
>
> We currently have a UI issue (internal docker/pinata#4551) with the diagnostic upload process so you will need to post your diagnostic ID and at least click the Open Issues button in the Diagnose & Feedback window. You needn't open a new issue but, currently, diagnostic upload is linked to that button.

IMHO it would probably be best/least confusing if you were to each create a fresh issue in the docker/for-mac issue tracker (by following the Docker for Mac UI under Diagnose & Feedback) with your individual diagnostic ID and your reproduction steps. It is much easier to reconcile multiple duplicate tickets than it is to split a single ticker which contains multiple issues (even more so when those issues are superficially similar but turn out to have very different root causes).

Thanks,
Ian.

**Comment by gluxon** [comment]
> @gluxon can you provide instructions how to reproduce the patch? I.e. how to build hyperkit from sources and replace it.

That binary patch is actually not the result of compiling hyperkit from sources myself. I created it from disassembling the source of com.docker.hyperkit and finding the assembly instruction that correlated with `if (sc->reply_prod == VTSOCK_REPLYRINGSZ)`. The resulting opcode was `81f900020000` and I changed that to `81f900040000`.

If you would prefer to manually change the file yourself with a hex editor instead of applying the patch using the `bspatch` utility in homebrew, you can find the opcode above at offset `000000010001fb71`.

**Comment by justincormack** [comment]
I don't think there should be any issue building hyperkit from modified
sources and replacing it in the application bundle to see if this fixes the
issue.

**Comment by rvanider** [comment]
I am also hitting docker/hyperkit#50 very consistently. I am able to successfully recreate it in my use case however it is inconsistent in how quickly it will manifest itself.

I am running an nginx:latest container with about 1GB of binary assets that are being served to an ansible installation process that is running in a VirtualBox VM. Access to the localhost http server is via the VirtualBox gateway address.

It does not make a difference if the binary assets are served from a docker volume or from a os x mapped host - both result in the same hyper kit error.

**Comment by ijc25** [comment]
@gluxon since the reply ring is a statically sized buffer in a datastructure it is not sufficient to simply change the bounds check, you should also need to adjust the size of the memory region used. IOW if I understand your description correctly it sounds as if you have introduced memory corruption for the data following the ring!

**Comment by ijc25** [comment]
Building a hyperkit should be possible with something like this (assuming `$REPO` is the root of your https://github.com/docker/hyperkit clone with branch master checked out) (no warranty, untested outside my environment etc etc ;-)):

```
brew install opam
export OPAMROOT=$REPO/build/opam
opam init --yes
opam pin add qcow-format git://github.com/mirage/ocaml-qcow#master --yes
opam install --yes uri qcow-format ocamlfind
cd $REPO
git pull https://github.com/docker/hyperkit af-vsock
opam config exec -- make $j_flag PRI_ADDR_PREFIX=* CONNECT_SOCKET_NAME=@connect
```

Now you should be able to take `$REPO/build/com.docker.hyperkit.sym` and drop it into the right place (i.e. over the existing one) in the Docker bundle.

**Comment by gluxon** [comment]
> @gluxon since the reply ring is a statically sized buffer in a datastructure it is not sufficient to simply change the bounds check, you should also need to adjust the size of the memory region used. IOW if I understand your description correctly it sounds as if you have introduced memory corruption for the data following the ring!

Ouch! Thanks for the heads up and better instructions.

**Comment by jp-gorman** [comment]
I was getting this error: "Error: HTTP code is 500 which indicates error: server error - dial unix /Users/johnuser/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused" - I just quit docker from the top tool bar on OSX and ran the docker beta OSX app again and docker started fine.

**Comment by materliu** [comment]
I encounter the same issue, after I change the docker for mac 's memory to 6GB, things begin to go better. I hope so this can help you.

**Comment by jaywhy13** [comment]
I had this same problem.
See my post at http://stackoverflow.com/questions/39083683/wordpress-causing-docker-to-crash.

 Listing steps for reproducing. Sorry that this is so application specific but it makes no sense why this would be happening and it's the only way I know how to reproduce.

I'm using the following Dockerfile:

    # Dockerfile
    FROM php:7.0-cli
    RUN docker-php-ext-install mysqli
    COPY . /code
    WORKDIR /code

Here's my compose file.

    version: '2'
    services:
      db:
        image: mysql:5.7
        volumes:
          - "./.data/db:/var/lib/mysql"
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: wordpress
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress
      web:
        build: .
        command: php -S 0.0.0.0:8000
        depends_on:
          - db
        links:
          - db
        ports:
          - "8000:8000"
        restart: always
        environment:
          WORDPRESS_DB_HOST: db:3306
          WORDPRESS_DB_PASSWORD: wordpress

I bring up the site using docker-compose up and perform the installation. Then I go to the themes page and reload it one or two times, Docker restarts!

**Comment by materliu** [comment]
@jaywhy13  My program is one php program too.

**Comment by freman** [comment]
We've got a similar problem here, complicated php5-fpm install, nginx, nodejs redis on a ubuntu base image that we've been running for 18 months under vagrant.

**Comment by fooinha** [comment]
Having the same problem here, both with Beta and Stable versions ( Version 1.12.0-a (build: 11213)
ad6ab836187e4111082447b7c0a6a74d01929a5c )

SIGABRT and assertion from crash report 

```c

Process:               com.docker.hyperkit [40314]
Path:                  /Applications/Docker.app/Contents/MacOS/com.docker.hyperkit
Identifier:            com.docker.hyperkit
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        com.docker.driver.amd64-linux [40312]
Responsible:           com.docker.hyperkit [40314]
User ID:               501

Date/Time:             2016-09-08 17:33:49.097 +0100
OS Version:            Mac OS X 10.11.6 (15G1004)
Report Version:        11
Anonymous UUID:        941EFF37-203F-D3B5-5E6F-5CA737051A44

Sleep/Wake UUID:       1545B4B0-D180-4A16-8191-638D30F7DB16

Time Awake Since Boot: 54000 seconds
Time Since Wake:       10000 seconds

System Integrity Protection: enabled

Crashed Thread:        8  vsock:tx

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
Assertion failed: (sc->reply_cons != sc->reply_prod), function send_response_common, file src/pci_virtio_sock.c, line 879.

```

**Comment by whitelynx** [comment]
Just to make sure @dsheets and @ijc25 see this... I'm running into this issue as well. I opened docker/for-mac#690, and my Diagnostic ID is: C622A34B-A4E6-4C6C-8DA5-4B6D96D63BE0

Sadly, as with several others, I can't really give repro steps because the codebase I'm working with is private.

**Comment by materliu** [comment]
any updates ?

**Comment by cwbeck** [comment]
this is a huge issue for us - (one of many at the moment!)

we have a container running Ubuntu 16.04 LTS and Nginx where code is fetch from mounted volume (mounted via -v /a:/b)

```
Version 1.12.1 (build: 12133)
2d5b4d9c3daa089e3869e6355a47dd96dbf39856
```

```
Error response from daemon: dial unix /Users/user/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused
```

**Comment by materliu** [comment]
MacOX, I change the CPUs to 1, but problem still there. After I change to ubuntu, the problem gone.

**Comment by ijc25** [comment]
We have just released v1.21.1-beta27 which includes some upgrades and improvements to the vsock transport code.

Please could everyone test with that and if you are still seeing issues open a fresh ticket against https://github.com/docker/for-mac with the full output of diagnostics (from the whale menu). Providing reproduction steps of any case would also be **very** useful in tracking this down.

I understand that many of the repro cases are when building proprietary software but if someone was able to par their case down to just the basic build system skeleton required to trigger the issue (removing all the proprietary stuff) or find a subset of their code which they were willing/able to post then we'll stand a much better chance of nailing this once and for all.

**Comment by ijc25** [comment]
@jaywhy13 yours is the closest I've seen to a workable reproduction. I created `Dockerfile` and `docker-compose.yml` with the content you posted and ran `docker-compose up`. However when I visit localhost:8000 all I get is a `The requested resource / was not found on this server.`. I expect  this is because the `Dockerfile` has `COPY . /code` but I have no code. If you could provide a basic skeleton which reproduces the issue for you with 1.12.1-beta27 then that would be very useful.

I'm also unsure what you mean by `and perform the installation` but maybe that would be clear if I had some content? In any case if you could walk me through something which reproduces it step by step I'd be grateful (I know nothing about wordpress I'm afraid).

**Comment by justincormack** [comment]
We believe the original issue reported here, around vsock ring buffer corruption is now fixed, with a new release of the vsock virtio protocol. If you are still having issues that maybe seem similar, please open a new issue (or find an existing issue) in https://github.com/docker/for-mac/issues and we will investigate as it is likely unrelated to this, even if the outcome appear similar.

**Comment by siemiatj** [comment]
This started showing for me after last update to : Version 1.12.2-rc1-beta27 (build: 12496). Trying to revert nao.

**Comment by cwbeck** [comment]
Update: - Only way to avoid completely is to us VMware as the engine instead. Dropping to 1 CPU just lowers the error rate for us.

```
docker-machine create --driver vmwarefusion --vmwarefusion-memory-size=2048 vm
```

**Comment by xfxf** [comment]
Same issue here.  Django project with ~7 containers, CPU intensive processes seem to kill everything.

**Comment by JamesKyburz** [comment]
Getting this too

Docker version 1.12.2-rc1, build 45bed2c, experimental

**Comment by rlazoryshchak** [comment]
I've faced with same issue when running my RoR web server in docker and open it in chrome browser I could avoid that when open web server in firefox

**Comment by thaJeztah** [comment]
Per @justincormack's comment above https://github.com/docker/docker/issues/24045#issuecomment-250425707, I'm locking this issue; please open a _new_ issue (or search for existing ones), in the [Docker for Mac](https://github.com/docker/for-mac/issues) issue tracker, as this is specific to Docker for Mac, and cannot be resolved in this repository.
