### ISSUE TITLE
API Docs: inconsistent fields for resource settings on service 

### ISSUE THREAD

**Issue by dhiltgen** [docker/docker#24058]
According to the engine-api Docs, resource settings are "NanoCPUs" and "MemoryBytes" - https://godoc.org/github.com/docker/engine-api/types/swarm#Resources

The corresponding docs for the remote API show simply "CPU" and "Memory" https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api_v1.24.md#create-a-service

**Comment by yongtang** [comment]
@dhiltgen I created a pull request #24729 to update the API docs. Please let me know if there are any issues.
