### ISSUE TITLE
1.12-rc2 undocumented change in exec remote API

### ISSUE THREAD

**Issue by tgross** [docker/docker#24055]
On `Docker version 1.11.2, build b9f10c9`, both `POST /v1.23/containers/<container ID>/exec` and `POST /v1.23/exec/<exec ID>/start` have the following body:

```json
{
  "AttachStderr": true,
  "AttachStdin": true,
  "AttachStdout": true,
  "Cmd": [
    "true"
  ],
  "Container": "<container ID>",
  "Detach": false,
  "DetachKeys": "",
  "Privileged": false,
  "Tty": true,
  "User": ""
}
```

On `Docker version 1.12.0-rc2, build 906eacd, experimental`, both `POST /v1.24/containers/<container ID>/exec` and `POST /v1.24/exec/<exec ID>/start` have the following body:

```json
{
  "AttachStderr": true,
  "AttachStdin": true,
  "AttachStdout": true,
  "Cmd": [
    "true"
  ],
  "Detach": false,
  "DetachKeys": "",
  "Privileged": false,
  "Tty": true,
  "User": ""
}
```

Note that the bodies are different -- the v1.23 body includes the container ID. This change doesn't appear in the Remote API documentation.

**Comment by cpuguy83** [comment]
@vdemeester This was removed in docker/engine-api#162
I assume because it wasn't actually used?

**Comment by vdemeester** [comment]
@cpuguy83 hum if I remember correctly yes. It's not read server side as the `Container` information is already there (in the `URI`) or not needed (for `/exec/…/`), but that's true, missed to update the documentation on that :sweat:.

**Comment by thaJeztah** [comment]
@vdemeester is that change versioned?

**Comment by vdemeester** [comment]
hum definitely not :sweat:

**Comment by cpuguy83** [comment]
I'm not sure why it would matter if it's there or not.
The json decoder will not error out if there is an extra field.

**Comment by vdemeester** [comment]
@cpuguy83 ah yes that's true :wink:

**Comment by tgross** [comment]
> I'm not sure why it would matter if it's there or not.
The json decoder will not error out if there is an extra field.

In this Docker server implementation that's the case. In [Joyent's sdc-docker](https://github.com/joyent/sdc-docker) we've got an alternate implementation of the engine. So we're expecting that the client behavior will match the published Remote API. We're seeing `docker exec` calls fail from 1.12.0-rc2 clients against `sdc-docker`. Obviously we'll need to fix our implementation so that it works correctly, so the reason I opened the issue is because if the client behavior is correct and the docs are wrong (or vice-versa) we want to make sure we're fixing it in the right direction.

**Comment by cpuguy83** [comment]
@tgross Ah, good point. We'll need to make sure to update the docs.

**Comment by tgross** [comment]
It looks like the Remote API docs are strictly correct in that they're leaving out this extra field all the way back to 1.18. So maybe it's just a matter of updating the CHANGELOG for the client to note that the unused field is being removed?

**Comment by thaJeztah** [comment]
I'll open a PR to address that, this note is relevant in this case;

> Docker’s Remote API uses an open schema model. In this model, unknown properties in incoming messages are ignored. Client applications need to take this behavior into account to ensure they do not break when talking to newer Docker daemons.

Although it's not explicit that the opposite is true as well (i.e., the daemon ignores unknown properties)

https://docs.docker.com/engine/reference/api/docker_remote_api/

**Comment by thaJeztah** [comment]
opened a PR https://github.com/docker/docker/pull/24144

**Comment by tgross** [comment]
> I'll open a PR to address that, this note is relevant in this case;
> Although it's not explicit that the opposite is true as well (i.e., the daemon ignores unknown properties)

Yeah, understood. Thanks for pointing that out.
