### ISSUE TITLE
Docker BUILD should support --proxy feature.   Meaning builds should be able to honor a proxy server, so that no proxy information is passed into the Dockerfile.

### ISSUE THREAD

**Issue by rcsavage** [docker/docker#24054]
Feature request:  Docker BUILDS should allow for proxy servers.   For example docker build --proxy "blah" image .

**Comment by cpuguy83** [comment]
@rcsavage `docker build --build-arg HTTP_PROXY=...`
Does this not work for you?

**Comment by rcsavage** [comment]
Not for everything, it covers the majority of my needs, but not some conditional services.

**Comment by cpuguy83** [comment]
@rcsavage Can you give an example?
I don't see how a dedicated flag would be different than `--build-arg`.

**Comment by thaJeztah** [comment]
@rcsavage can you provide some more information? With the current information it's not clear what is missing for your use case

**Comment by thaJeztah** [comment]
closing, because no more information was provided
