### ISSUE TITLE
Promote/demote causes demoted node to hang

### ISSUE THREAD

**Issue by dperny** [docker/docker#24065]
**Output of `docker version`:**
*NOTE: The build says 'unsupported' because I tried vendoring swarmkit to latest version to see if the issue had been fixed upstream. It has not been. This is actually commit `83e6197`* 
```
root@bc27390c3317:/go/src/github.com/docker/docker# docker version
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   6ed921d-unsupported
 Built:        Wed Jun 15 00:41:14 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   6ed921d-unsupported
 Built:        Wed Jun 15 00:41:14 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
root@bc27390c3317:/go/src/github.com/docker/docker# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: active
 NodeID: 2yb6983jd98f6
 IsManager: Yes
 Managers: 2
 Nodes: 2
 CACertHash: sha256:8b807b58aa4d9614e9f3745e04ee52a98428fc05b7674cb77a4935baabaa25dd
Runtimes: default
Default Runtime: default
Kernel Version: 4.4.13-moby
Operating System: Debian GNU/Linux 8 (jessie) (containerized)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.954 GiB
Name: bc27390c3317
ID: OQJH:FDJA:MA2A:L5KU:ZVBO:CUWF:ETEQ:LFQ3:CQLE:UOJF:JCR7:KYRO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Two `make shell` Docker-in-Docker containers. Host OS is Mac OSX.

**Steps to reproduce the issue:**
1. In container 1, `docker swarm init --listen-addr 172.17.0.2:4040`
2. In container 2, `docker swarm join --listen-addr 172.17.0.3:4040 172.17.0.2:4040`
3. In container 1, promote the node running in container 2
4. In container 1, demote the node running in container 2.

**Describe the results you received:**
```
$ docker node ls
ID               NAME          MEMBERSHIP  STATUS  AVAILABILITY  MANAGER STATUS
2yb6983jd98f6 *  bc27390c3317  Accepted    Ready   Active        Leader
3vnf3z6lj7php    be0fb15f03af  Accepted    Ready   Active

$ docker node promote 3vnf3z6lj7php
3vnf3z6lj7php
3vnf3z6lj7php attempting to promote a node to a manager in the swarm.

$ docker node ls
ID               NAME          MEMBERSHIP  STATUS  AVAILABILITY  MANAGER STATUS
2yb6983jd98f6 *  bc27390c3317  Accepted    Ready   Active        Leader
3vnf3z6lj7php    be0fb15f03af  Accepted    Ready   Active        Reachable

$ docker node demote 3vnf3z6lj7php                                                                                                  
3vnf3z6lj7php
3vnf3z6lj7php attempting to demote a manager in the swarm.

$ docker node ls
ID               NAME          MEMBERSHIP  STATUS  AVAILABILITY  MANAGER STATUS
2yb6983jd98f6 *  bc27390c3317  Accepted    Ready   Active        Leader
3vnf3z6lj7php    be0fb15f03af  Accepted    Ready   Active        Unreachable
root@bc27390c3317:/go/src/github.com/docker/docker# docker version
```

In addition, cluster no longer responds to commands like `docker service create`

**Describe the results you expected:**
Manager status column on `3vnf3` should be empty. Cluster should respond to commands

**Comment by abronan** [comment]
@dperny This is interesting because this scenario shouldn't work in the first place. We check the quorum number and you can't demote a node if there are only 2 raft members left. Using master and running docker in VMs while trying the exact same scenario I get:

```
Error response from daemon: rpc error: code = 2 desc = raft: member cannot be removed, because removing it may result in loss of quorum
```

Does this happen everytime you try to promote and demote?

**Comment by dperny** [comment]
I can consistently reproduce this bug on two docker containers with `make shell`

Or, at least, I could yesterday.

**Comment by abronan** [comment]
@dperny Could you please retry with `master`, preferably vendoring the latest `swarmkit` changes? We changed the promotion/demotion to scale back to one and additionally the operation shouldn't block anymore if you issue a remove from the node itself. This would be great if you could confirm that the behavior is fixed. Thanks!

**Comment by thaJeztah** [comment]
ping @dperny have you had a chance to test?

**Comment by dperny** [comment]
Sorry, I forgot to. I'll verify this weekend.

**Comment by dperny** [comment]
Confirmed fixed in RC3.

**Comment by thaJeztah** [comment]
Awesome, thanks @dperny
