### ISSUE TITLE
"docker service create" in swarm mode does not pass labels to the tasks/containers created

### ISSUE THREAD

**Issue by selvik** [docker/docker#24067]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:45:29 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 21:09:07 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:45:29 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 21:09:07 2016
 OS/Arch:      linux/amd64
Selvis-MBP:cx selvikadirvel$ newdocker info
Containers: 6
 Running: 5
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 21
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: active
 NodeID: bhdvickrzvbaw0ixvyszuzyuf
 IsManager: Yes
 Managers: 1
 Nodes: 2
 CACertHash: sha256:f06eaf86ee7c4c6d60e2e6d63857fb4256ad83a4abe4d0c996bc5c01f77ffe3d
Runtimes: default
Default Runtime: default
Security Options: apparmor seccomp
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 4.03 GiB
Name: dev
ID: ICLK:ZYTD:5WGY:PFZL:V7CE:HCWU:EAXO:ASTM:G2DD:PHFZ:3EU5:TLNZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: cxselvi
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=generic
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Swarm manager and worker are Ubuntu 14.04 VMs running on VMware Fusion.

**Steps to reproduce the issue:**
1. On the manager node: docker swarm init --listen-addr [manager_ip]:2378
2. On the worker node: docker swarm join [manager_ip]:2378
3. Starting a service with a label: 
docker service create --replicas 2 --name hello --label mylabel="finance" alpine ping docker.com
4. Check that the service is started

```
docker service ls
ID            NAME         REPLICAS  IMAGE   COMMAND
d60kak259u9q  hello        2/2       alpine  ping docker.com
```

5. Find the container IDs of the tasks:

One is scheduled on the manager:

```
docker ps
CONTAINER ID        IMAGE                    COMMAND                  CREATED              STATUS              PORTS               NAMES
19e981e05375        alpine:latest            "ping docker.com"        About a minute ago   Up About a minute                       hello.2.6yk92jojcwikkijfa9hazj1xo
```

The other is scheduled on the worker:

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
d3611b47acbc        alpine:latest       "ping docker.com"   2 minutes ago       Up 2 minutes                            hello.1.9tb2yj57o1pate7titmir0hmz
```

**Describe the results you received:**
The containers don't have the expected labels:

```
$ docker inspect d3611b47acbc | grep finance
$
```

It only has these labels:
```
            "Labels": {                                                                                            
                "com.docker.swarm.node.id": "66uimldckdxsro9ygd2qu0s4w",                                           
                "com.docker.swarm.service.id": "d60kak259u9qi0v1ih2pksamn",                                        
                "com.docker.swarm.service.name": "hello",                                                          
                "com.docker.swarm.task": "",                                                                       
                "com.docker.swarm.task.id": "9tb2yj57o1pate7titmir0hmz",                                           
                "com.docker.swarm.task.name": "hello.1"                                                            
            }                                                                                                      
```

**Describe the results you expected:**
I expected to see
```
            "Labels": {                                                                                            
                "mylabel": "finance"                                                                               
            },                                                                                                     
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by llitfkitfk** [comment]
same issue

**Comment by cpuguy83** [comment]
Adding this as another P1/UX issue to discuss for 1.12

**Comment by selvik** [comment]
We want to use labels to categorize containers that have different properties. If the label used to start the service doesn't percolate down to the containers that belong to this service, then determining "the label" (or property) for a container becomes difficult.

**Comment by cpuguy83** [comment]
@selvik Categorize in what way? Does moving this categorization up to the service level make sense?

**Comment by selvik** [comment]
@cpuguy83 Yes, you are right, we *will* be moving this categorization to the service level. Even if we do that, when I am on a local docker node, I won't be able to inspect a container and get its label property. It is true that I can get this information indirectly. i.e. From the swarm manager, I can find the association from services -> to tasks -> to containers and then determine what my container's label/property/category is. But this seems a little convoluted. And it seems intuitive (IMHO) to expect labels to be percolated from services to containers. Since I don't know the under-the-hood details of how the service->container associations are being maintained, please feel free to let me know if this is unduly complicated to implement.  Thanks for considering the request! :)

**Comment by tiborvass** [comment]
I'm moving the priority from P1 to P3, since this is something we can always improve in future releases if we find the appropriate use-cases. No is temporary, yes is forever :)

**Comment by llitfkitfk** [comment]
@tiborvass 
user-case:
https://github.com/containous/traefik/blob/master/examples/compose-traefik.yml
need labels in containers

**Comment by vdemeester** [comment]
As @llitfkitfk said, one of the use-case would be what Træfɪk does right now (before actually supporting swarm mode services). Træfɪk listens for containers event and, to make it work with swarm mode we'll need to have services events (but it's another issue though) — and *in the end* Træfɪk aims to support both mode (with and without swarm mode).

Before having and supporting that, having the possibility to get service labels copied to containers would ease the migration between actual docker/swarm to docker swarm mode in 1.12 and later.

I feel this would not only benefit Træfɪk but a lot of the current ecosystem, to be able to use current ecosystem tooling with swarm mode without them supporting it "natively" right now (it's gonna take time for ecosystem tooling to support the new api from swarm mode).

**Comment by emilevauge** [comment]
Hi @cpuguy83, @tiborvass, I think a lot of people will still have the need of container based labels in addition to services labels.
For example, on Traefik, we are using container labels to assign different weights on containers from a service for weighted round robin load-balancing.
I hope Docker 1.12 swarm mode will not break these possibilities :'(

**Comment by thaJeztah** [comment]
@emilevauge containers launched through `docker run` will still work as usual, but *service containers* currently don't receive labels (yet?).

**Comment by cpuguy83** [comment]
@emilevauge Looking at Traefik's case now  (and not saying we shouldn't support labels btw!), I think Traefik could/should be made to understand services.

The service name should be what `traefik.backend` is set to for all the tasks of a replicated service, and then if people really want to use a different name than the service name for some reason, it could read the label from the service.

**Comment by vdemeester** [comment]
> @emilevauge Looking at Traefik's case now (and not saying we shouldn't support labels btw!), I think Traefik could/should be made to understand services.

@cpuguy83 we are gonna support that but in the mean time, there would be no way to use traefik with swarm mode. 

And for any tooling in the ecosystem that make use of labels now (with bare containers), there will be the need for 2 different implementations, wether swarm mode is on or not.

**Comment by thaJeztah** [comment]
I think the important bit is that we don't have a `service create` an `service update` event; those events would be needed for software like traefik to act on (for auto-configuration)

**Comment by stevvooe** [comment]
`--label` sets the labels for the service, not the containers under the service.

SwarmKit and docker swarm-mode supports labeling both. We don't propagate service labels to containers so that one can put sensitive labels on the service and trust those separately from the container labels. While it seems intuitive that they would propagate, there are valid use cases for them not to propagate.

Not sure why these aren't in the CLI. That seems like the major omission here.

**Comment by thaJeztah** [comment]
Should we have a separate `--service-label` or `--container-label`? Point is that other options *do* propagate (memory, CPU constraints, volumes), so at least we should clarify which options are "service level", and which "task" / "container" level

**Comment by stevvooe** [comment]
@thaJeztah Yes.

**Comment by vdemeester** [comment]
@stevvooe ok cool, did a quick lookup in swarmkit and felt there was a way (although not available through the `swarmctl` cli)

> Not sure why these aren't in the CLI. That seems like the major omission here.

Let me try to fix it 👼

**Comment by thaJeztah** [comment]
Naming will be a challenge, as there's still the open discussion about "image labels" (set in the image) and "container labels" (set at runtime), which currently are merged :disappointed:

**Comment by vdemeester** [comment]
As of 1.12.0-rc5 it's now possible to set labels to container (using `--container-labels`).

As @stevvooe said, "We don't propagate service labels to containers so that one can put sensitive labels on the service and trust those separately from the container labels."

So I think this issue can be closed now.

**Comment by thaJeztah** [comment]
implemented in https://github.com/docker/docker/pull/25038

**Comment by llitfkitfk** [comment]
Waiting for Docker for Mac release 1.12.0-rc5...
