### ISSUE TITLE
service update of array/map types requires repeating the entire set 

### ISSUE THREAD

**Issue by dnephin** [docker/docker#24064]
Issue for #23773

Updating array and mapping types by starting with an empty collection is fine when there are a small number of items, but it becomes a large burden for users if they have many ports, labels, or mounts, and would like to add or remove a single one. The case of adding or removing a single item should be a lot more common than removing everything.

We should design the UX around the more common case.

**Comment by tiborvass** [comment]
**Notes from a synchronous discussions**:

Taking the example on labels, but also is the case for ports, mounts, envs:
We agreed on having `service update --label` behave as it does today that is replace the entire array/map and to have the explicit flags `--label-add` and `--label-rm` in addition that respectively add and remove a label.

Adding existing labels would replace their value, behaving as a `set` verb.

Args are a somewhat special case in that we don't provide flags to add and remove them, only replacing the entire set: which is consistent with the behavior for other properties.

As a side effect, this decision unblocks `docker update --label`: https://github.com/docker/docker/pull/18958

**Comment by tiborvass** [comment]
For envs, it seems like we would need to add logic that parses the `=`. Thankfully there is a POSIX standard on how to process that. cc @stevvooe

**Comment by dnephin** [comment]
We already have code in docker which parses envs, it's just a `splitN(env, "=", 2)`.

I'm glad we could agree on `--label-add` and `--label-rm`. With these options it seems unnecessary to include `--label` on update as well. These options wouldn't work together, and in generally aren't really useful.

As long as there is a way to add flags and remove all flags do we actually need a reset as well?

**Comment by tiborvass** [comment]
For 1.12.0 let's not implement reset.
For later, we can do either a nice hack `--label ''` or a `--label-reset` (or a better verb)

**Comment by stevvooe** [comment]
> We already have code in docker which parses envs, it's just a splitN(env, "=", 2).

@dnephin For the most part, don't even parse env parameters. Just pass them straight through. Let the OS sort it out.

**Comment by dnephin** [comment]
@stevvooe unfortunately this is not the case for docker. Env vars are always parsed:

1. `--env` without a value gets the value from the client shell, so it needs to be parsed on the client to see if it has a value or not (`runconfig/opts/opts.go:ValidateEnv`)
2. in `service update` to remove an environment variable a user shouldn't have to know the value of it.  They should be able to remove it from just the key, which requires parsing them.
