### ISSUE TITLE
Permission upgrade between containers

### ISSUE THREAD

**Issue by BLaurent** [docker/docker#24075]
Hi,

I am trying to setup temporary permission elevation for a given container.
I have a container A that "own" some files. I opened a files with RW then I passing this descriptor to container B. This container B does a mmap and write to it.

Container A do have a volume mounted
Container B have no volume mounted.

Is this something wanted or just a temporary hack that will be removed some day?

Thanks for your help.
Regards

**Comment by justincormack** [comment]
If you pass file descriptors you can always do this, the Linux kernel will allow access to files that are only visible in the namespace where the file descriptor originated, so this will always work.

**Comment by BLaurent** [comment]
Thanks a lot Justin.
Regards
