### ISSUE TITLE
Proposal: Eliminate 'docker service scale' before it's too late

### ISSUE THREAD

**Issue by nathanleclaire** [docker/docker#24076]
`docker service scale`... Why is the _the only_ parameter which can be updated through both a first-class command _and_ through `docker service update`?  Isn't that a bit inconsistent?

I know that it was this way in Docker Compose, but is including Docker Compose vestiges in the new `docker swarm` _really_ a good idea?  Will this inclusion of a Docker Compose vestige set a user expectation for `docker swarm` to imitate Compose closely in other ways as well?

Here's our last chance to pull it, before it becomes canon and removing it breaks hundreds of shell scripts.  Feel free to close if I'm way off mark here.

@aluzzardi @vieux @dnephin @abronan

**Comment by dnephin** [comment]
I agree with you, `docker service update --scale SERVICE` feels sufficient to me.

**Comment by vdemeester** [comment]
I also agree with @nathanleclaire and @dnephin, `update --scale n SERVICE` makes more sence to me

**Comment by cpuguy83** [comment]
Except it's `docker service update --replicas` :)

**Comment by vdemeester** [comment]
@cpuguy83 ah right, `--scale` is not even needed then :angel:

**Comment by dnephin** [comment]
Apparently we removed `--replicas` in 72f7cebfb036f0fc74b9fa6fcc0c154f83f1605f , that seems wrong.

**Comment by thaJeztah** [comment]
I think the reasoning here was that `scale` allows you to scale multiple services in a single call, but I haven't been involved in the design decisions

**Comment by aluzzardi** [comment]
@dnephin We removed service change mode (replicat**ed** to global and vice versa) in service update

**Comment by dnephin** [comment]
Yup, I was wrong about that.

**Comment by stevvooe** [comment]
🍌

**Comment by tiborvass** [comment]
We're gonna just make sure `service scale --help` has information about `service update` that has more options and is more powerful. cc @sfsmithcha

**Comment by nathanleclaire** [comment]
There was an offline discussion of this and I seem to have misunderstood the intention of this command.  `docker service scale` is intended to be a "porcelain" wrapper around the "plumbing" of `docker service update --replicas=x` and will indicate that it is so in the help text.  In the future other such aliases, following `git`'s lead, may become used.  Therefore it's not meant to be two separate ways of accessing the same functionality but rather one which is a gateway method to the other.
