### ISSUE TITLE
What is the volume / persistent data story for swarm mode?

### ISSUE THREAD

**Issue by nathanleclaire** [docker/docker#24089]
I haven't had time to look into the source unfortunately, but what is this mysterious `--mount` flag in `docker service create`?

```
  -m, --mount value                  Attach a mount to the service
```

Can't find any docs at https://docs.docker.com/engine/reference/commandline/service_create/

It's not really clear how volumes / data management is intended to fit into the Swarm mode picture in general (how do volume plugins work?  how do you manage distributed volumes for services?), so getting some documentation around that would be great.

**Comment by nathanleclaire** [comment]
cc @sfsmithcha

**Comment by nathanleclaire** [comment]
also @cpuguy83 if you have any input or guidance ... I might write some if you have a few pointers

**Comment by sfsmithcha** [comment]
ping: @tiborvass the way I understand this is still WIP

**Comment by ggtools** [comment]
So far I did manage to make it work with a local directory or a local volume.

For a local directory:

    docker service create --name nginx_hello --mount type=bind,source=/local/directory,target=/data,writable=true nginxdemos/hello


For a volume:

    docker service create --mount type=bind,source=test_volume,target=/data,writable=true,volume-driver=local nginxdemos/hello

Using *volume* gives something "*different*" but not what I'm expecting

**Comment by cpuguy83** [comment]
@ggtools Yes, the internals for volume mounts are a little off. Have a PR to fix, hopefully for RC3.

**Comment by cpuguy83** [comment]
@F21 The way to do this would be to used named volumes. I think it's perfectly correct that volumes are cleaned up when a service is removed.
Note that you really shouldn't be removing a service unless you really want to remove it.  Services should not have the same management semantics as containers. A container is a payload, a service is an orchestration object.  If you want to "stop" a service, you set the replica count to 0.

For 1.12, we are working on some documentation on how to handle real persistent services (e.g. databases)... basically you'll need to use node constraints and named volumes for dealing with these kinds of workloads.  You will *not* be able to use the scaled-replicas feature (which probably you shouldn't for these anyway) with this setup.

We have, as of right now anyway, purposefully left off the `-v` flag for future use... what that looks like is still TBD.

**Comment by thaJeztah** [comment]
There's an issue created for documenting `--mount`; https://github.com/docker/docker/issues/24277, improving the mount-syntax; https://github.com/docker/docker/issues/24190, some issues around using volume plugins: https://github.com/docker/docker/issues/23619, and some other issues IIRC

@nathanleclaire do you want to keep this one open, or do you have enough information to close this?

**Comment by nathanleclaire** [comment]
I think since it's well known issue it's fine to close

**Comment by Linuxing** [comment]
@ggtools 
writable is not support any more, use "readonly", like this

--mount type=bind,source=/data/mysql_data,target=/var/lib/mysql,readonly=false \
--mount type=bind,source=/etc/localtime,target=/etc/localtime,readonly=true \

**Comment by thaJeztah** [comment]
@Linuxing volumes should now be writable by default, so you can remove the `readonly=false`

**Comment by titpetric** [comment]
What exactly is the `best practice` way to set up persistent storage with a docker swarm? Or shared storage, to be exact - that's the point of scaling up a service. Comment by @Linuxing is slightly misleading given servers like `mysql` can't work on the same files in a distributed way, while servers like nginx could take their own /var/www as long as it's provided on the hosts.

I'm pretty sure somewhere it was written that `docker service create` is supposed to be analogous to `docker run`, so I'm not exactly sure what is the reasoning behind dropping `-v` and replacing it with the (imho, more complex) `--mount`?

**Comment by farcaller** [comment]
Docker doesn't do data migration itself, so swarm can't be responsible for having the data on the machine. For stateful apps you need use something like ceph plugin to mount the storage on the node.

**Comment by cpuguy83** [comment]
@titpetric `docker service create` is most definitely not the same as `docker run`.
`-v` was dropped because services don't orchestrate volumes. We specifically use the term `mount` because that is what services do. You can have a service that has a template for creating a volume that the service then mounts in for you, but it does not itself handle volumes, so it's intentionally left out for now.

**Comment by jiaoge** [comment]
docker service create --name example --replicas 2 -p 6001:6001 --mount type=bind,source=/root/logs/example,target=/root/logs  registry-vpc.cn-hangzhou.aliyuncs.com/quancheng/example-web:20160905   

@thaJeztah 

example.2  registry-vpc.cn-hangzhou.aliyuncs.com/quancheng/example-web:20160905  iZ230brnviiZ  Shutdown       Rejected 4 seconds ago  "invalid bind mount source, so…"

**Comment by cpuguy83** [comment]
@jiaoge You can get the full message by inspecting the task.
I suspect it's because the source path doesn't exist on the node.

**Comment by jiaoge** [comment]
@cpuguy83 
you are right! the source path doesn't exist,but i think the error message is not friendly

**Comment by cpuguy83** [comment]
@jiaoge pretty sure the full message is `invalid bind mount source, source path not found`

**Comment by jiaoge** [comment]
@cpuguy83 
ok，how can see the full message？ 
`docker service ps `  only give me the short msg

**Comment by cpuguy83** [comment]
@jiaoge `docker inspect <task id>`

**Comment by jiaoge** [comment]
@cpuguy83 
thanks. so cool!

**Comment by francisbrito** [comment]
Hello,

I'm getting the same error as @jiaoge: `invalid bind mount source, source path not found`. It seems docker is unable to locate my source path, even tho I'm passing it correctly.

Here's the command:
```
docker service create \
--name registry \
--label "registry" \
--publish 5000:5000 \
--mount "type=bind,source=`pwd`/certs,target=/certs,readonly=true" \
--mount "type=bind,source=`pwd`/data,target=/var/lib/registry" \
--env REGISTRY_STORAGE=s3 \
--env REGISTRY_STORAGE_S3_REGION=sa-east-1 \
--env REGISTRY_STORAGE_S3_BUCKET=<bucket name> \
--env REGISTRY_STORAGE_S3_V4AUTH=true \
--env REGISTRY_STORAGE_S3_REDIRECT_DISABLE=true \
--env REGISTRY_STORAGE_S3_SECURE=true \
--env REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt \
--env REGISTRY_HTTP_TLS_KEY=/certs/domain.key \
registry:2
```

`pwd` directory does contains `certs` and `data` directories, so I'm not sure why it is unable to find them.

I'm a newb at docker/docker swarm, so this might sound like a dumb question but, could it be that swarm is creating the container in a node different to where I'm issue the command and thus can't find the directories there? If so, what are the alternatives?

**Comment by cpuguy83** [comment]
@francisbrito Correct. The bind source must be on the node that it's getting scheduled to.

**Comment by pascalandy** [comment]
> The bind source must be on the node that it's getting scheduled to

OMG !! Of course!

**Comment by slooker** [comment]
Is there a way to use the `--mount` flag for an external mount, like in the case of Google Cloud Platform?  I'm trying to figure out how to mount a Google Cloud Platform persistent disk in the container which is deployed as part of a docker swarm.  

So far as I can tell, I can only mount those to the host and not necessarily directly to a container (without first mounting on the host), and that doesn't work because I don't know what Swarm node the container will be on.

**Comment by cpuguy83** [comment]
@slooker Yes, you can use `--mount` with any volume driver.
There is a plugin here: https://github.com/mcuadros/gce-docker
I'm not sure of the quality of this plugin.
RexRay also has a GCE provider.

**Comment by slooker** [comment]
@cpuguy83 Normally I use `docker service create` when creating swarm services.  It doesn't seem like there's any volume flag, nor is there a volume-driver flag.  Am I missing something?  Either there's another way to create swarm services or this can't be used with swarm on GCE?

**Comment by thaJeztah** [comment]
@slooker services use the `--mount` flag. Docs are merged on GitHub, but not published yet; https://github.com/docker/docker/blob/master/docs/reference/commandline/service_create.md#add-bind-mounts-or-volumes

**Comment by slooker** [comment]
@thaJeztah  Bummer.  I still get "Error looking up volume plugin gce" even after installing it via the docker image.  I'll search some more to see if I can figure it out.  Thanks!
