### ISSUE TITLE
Name column of `docker node ls` should be hostname

### ISSUE THREAD

**Issue by stevvooe** [docker/docker#24090]
The following output:

```console
$ docker node ls
ID                           NAME  MEMBERSHIP  STATUS  AVAILABILITY  MANAGER STATUS
c0m79i9ar7nuahegfeak4v8ma *  moby  Accepted    Ready   Active        Leader
```

Should be:

```console
$ docker node ls
ID                           HOSTNAME  MEMBERSHIP  STATUS  AVAILABILITY  MANAGER STATUS
c0m79i9ar7nuahegfeak4v8ma *  moby      Accepted    Ready   Active        Leader
```

Nodes _do_ have a name, but it is not necessarily the hostname.

cc @aluzzardi @dongluochen

**Comment by allencloud** [comment]
@stevvooe 
I found more details that may be useful.

While in this place, code like this:
https://github.com/docker/docker/blob/master/api/client/node/list.go#L79-L85
```
name := node.Spec.Name
availability := string(node.Spec.Availability)
membership := string(node.Spec.Membership)

if name == "" {
	name = node.Description.Hostname
}
```
If node name is empty, it will use hostname instead.

**Comment by stevvooe** [comment]
@allencloud This code is somewhat wrong. I think we were trying to have a "fuzzy name", where it would use name, then fallback to hostname. Unfortunately, the name is 1:1 with node, while hostname provides no such guarantee, as it can be `M:N` (many nodes can have same hostname, many nodes can run on same host).

**Comment by yongtang** [comment]
@stevvooe @allencloud It seems that the `Hostname` is always used in `api/client/node/list.go`.

I created a pull request #24159 to change the title field to `HOSTNAME`. Please let me know if there are any issues.
