### ISSUE TITLE
Document best practices for operating swarm managers

### ISSUE THREAD

**Issue by F21** [docker/docker#24109]
It would be nice if the documentation contains best practices for operating swarm managers.

For example:
- Are swarm managers like mesos masters which needs to be operated in odd numbers to maintain quorum?
- What is the maximum number of managers you should have in a swarm? Are they like Zookeeper ensembles where as the number of members in the ensemble increases, the write performance decreases?
- Is it advisable to make every node a manager, so that we can administrate the swarm from any node?
- Can swarm be run in high availability mode? If so, is there an example?

**Comment by cpuguy83** [comment]
ping @thaJeztah

**Comment by thaJeztah** [comment]
thanks for the ping; let me add @sfsmithcha as well, I think he has this on his list

**Comment by sfsmithcha** [comment]
thanks @thaJeztah , @cpuguy83 , @F21 , these are definitely questions that are slated for the user/admin guide docs that are currently WIP

**Comment by joelchen** [comment]
+1

**Comment by sfsmithcha** [comment]
This is covered here: https://github.com/docker/docker/commit/137261f97ce3f27a8c28a50e286429ead4a6fc18
https://github.com/docker/docker/commit/24f87f26e73a49383e0606813a86ed96da7f5a18
