### ISSUE TITLE
Undefined --build-arg FOO masks default value ARG FOO=1 in Dockerfile

### ISSUE THREAD

**Issue by triccardi-systran** [docker/docker#24101]
`docker build --build-arg FOO` when `FOO` is not defined in environment variables of `docker build` is the same as `--build-arg FOO=`, which overrides potential default value for `FOO` in the `Dockerfile`:

```
$ cat Dockerfile
FROM alpine
ARG FOO=1
RUN ["sh", "-c", "echo '>>>' FOO=${FOO?NotSet} '<<<'"]

# Test 1
$ docker build --no-cache .
Sending build context to Docker daemon 3.072 kB
Step 1 : FROM alpine
 ---> 4e38e38c8ce0
Step 2 : ARG FOO=1
 ---> Running in 233c7eed414b
 ---> 57769cdb8cd7
Removing intermediate container 233c7eed414b
Step 3 : RUN sh -c echo '>>>' FOO=${FOO?NotSet} '<<<'
 ---> Running in e60f94a576ab
>>> FOO=1 <<<
 ---> dbb6171809d4
Removing intermediate container e60f94a576ab
Successfully built dbb6171809d4

# Test 2
$ docker build --build-arg FOO=2 --no-cache .
Sending build context to Docker daemon 3.072 kB
Step 1 : FROM alpine
 ---> 4e38e38c8ce0
Step 2 : ARG FOO=1
 ---> Running in 3b4cd1fb6856
 ---> 4006385461fb
Removing intermediate container 3b4cd1fb6856
Step 3 : RUN sh -c echo '>>>' FOO=${FOO?NotSet} '<<<'
 ---> Running in beee47a05904
>>> FOO=2 <<<
 ---> fc431d9ed6d7
Removing intermediate container beee47a05904
Successfully built fc431d9ed6d7

# Test 3
$ FOO=3 docker build --build-arg FOO --no-cache .
Sending build context to Docker daemon 3.072 kB
Step 1 : FROM alpine
 ---> 4e38e38c8ce0
Step 2 : ARG FOO=1
 ---> Running in 9a3a9e3a4e3e
 ---> 09f8df99bbf9
Removing intermediate container 9a3a9e3a4e3e
Step 3 : RUN sh -c echo '>>>' FOO=${FOO?NotSet} '<<<'
 ---> Running in 0e437a932631
>>> FOO=3 <<<
 ---> 5e3652eacd23
Removing intermediate container 0e437a932631
Successfully built 5e3652eacd23

# Test 4
$ docker build --build-arg FOO --no-cache .
Sending build context to Docker daemon 3.072 kB
Step 1 : FROM alpine
 ---> 4e38e38c8ce0
Step 2 : ARG FOO=1
 ---> Running in 2d807e3cc158
 ---> e126e82707ce
Removing intermediate container 2d807e3cc158
Step 3 : RUN sh -c echo '>>>' FOO=${FOO?NotSet} '<<<'
 ---> Running in 158ce7c7c673
>>> FOO= <<<
 ---> 3d6bdfbe1c02
Removing intermediate container 158ce7c7c673
Successfully built 3d6bdfbe1c02
```

Test 3 shows an undocumented feature where just setting the environment variable name with no `=value` to `--build-arg` makes `docker build` take the value from its own environment variables.
(Not documented in https://docs.docker.com/engine/reference/commandline/build/, or in https://docs.docker.com/engine/reference/builder/).

This is a useful feature that should be documented; it's also mimicked in `docker-compose`.

However, the corner case where the variable is not defined either in the `docker build` own environment could be improved:
Currently, an empty string is used in such case, which is fine except that it masks the potential default value defined in the `Dockerfile`, see test 4.

I think it would be better in this case to let the default value in `Dockerfile` apply: if the `docker build` command-line says to take the value of `FOO` from the environment variables of the process, and this environment variable is not set, then it makes more sense to me to do as if no `--build-arg` was passed, because none was set. 
This would result in not masking the default value from the `Dockerfile`, which I believe is a good thing.

If this behavior change is accepted in docker engine, then it could be mirrored in `docker compose` where there is a second level of default values (`.env`) and a similar issue. See docker/compose#3608.

**Comment by duglin** [comment]
```
$ FOO= docker run -e FOO ubuntu env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=53e66508d17a
FOO=
HOME=/root

$ docker run -e FOO ubuntu env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=cd3bf89a71c0
HOME=/root
```
For consistency it does make sense to treat a missing build-arg env as not having specified `--build-arg` at all.
