### ISSUE TITLE
Document service create constraints

### ISSUE THREAD

**Issue by F21** [docker/docker#24104]
The use of constraints should be documented in the reference. While https://github.com/docker/docker/blob/master/docs/reference/commandline/service_create.md says that the `--constraint` flag exists when creating a service, it is unclear how this is to be used and whether the same usage as docker/swarm applies.

It would also be nice to have a few examples showing how this is to be used.

**Comment by aaronlehmann** [comment]
cc @dongluochen

**Comment by sfsmithcha** [comment]
This should be covered by https://github.com/docker/docker/pull/24507  and https://github.com/docker/docker/pull/24432
