### ISSUE TITLE
Swarm node duplicated if it leaves and rejoins

### ISSUE THREAD

**Issue by F21** [docker/docker#24106]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd-unsupported
 Built:        Fri Jun 17 21:21:56 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd-unsupported
 Built:        Fri Jun 17 21:21:56 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 18
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host overlay bridge
Swarm: active
 NodeID: aohxq79tckraf5gzu273gkcph
 IsManager: No
Runtimes: default
Default Runtime: default
Security Options: apparmor seccomp
Kernel Version: 4.4.0-22-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 3.858 GiB
Name: docker-05
ID: KFMG:NQDE:OD7P:KKDU:XV2A:EDXG:OBUU:YAO5:HPZV:V7CO:BGXQ:W64T
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
vagrant@docker-05:~$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 18
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: active
 NodeID: aohxq79tckraf5gzu273gkcph
 IsManager: No
Runtimes: default
Default Runtime: default
Security Options: apparmor seccomp
Kernel Version: 4.4.0-22-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 3.858 GiB
Name: docker-05
ID: KFMG:NQDE:OD7P:KKDU:XV2A:EDXG:OBUU:YAO5:HPZV:V7CO:BGXQ:W64T
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
5 x Ubuntu 16.04 64-bit VirtualBox VMs

**Steps to reproduce the issue:**
1. Create a swarm and ask all nodes to join.
2. On one of the nodes, make it leave: `docker swarm leave`
3. Confirm on the manager that the node has left: `docker node ls`. It should show the node as down: `159jcfr7qedf6okulp6dmp21j    docker-05  Accepted    Down    Active`
4. Go to the node that has left and make it join: `docker swarm join ...`
5. Go to the manager and see that we now have 2 `docker-05`s: `docker node ls`:
```
159jcfr7qedf6okulp6dmp21j    docker-05  Accepted    Down    Active
7bh3sj08x7nba1ac6fd9w4v5p *  docker-01  Accepted    Ready   Active        Leader
aohxq79tckraf5gzu273gkcph    docker-05  Accepted    Ready   Active
...
```
6. If you run `docker node inspect docker-05`, it complains: `Error response from daemon: node docker-05 is ambigious (2 matches found)`. You'd have to use `docker node inspect aohxq79tckraf5gzu273gkcph`

**Describe the results you received:**
When a node leaves and rejoins, it is treated as 2 nodes.

**Describe the results you expected:**
When a node leaves and rejoins, it should try to rejoin with the original ID, so that it doesn't acquire 2 identities.

**Additional information you deem important (e.g. issue happens only occasionally):**
None

**Comment by IcaroBichir** [comment]
I'm having the same issue here.

```
docker@node1:~$ docker node ls
ID                           NAME   MEMBERSHIP  STATUS  AVAILABILITY  MANAGER STATUS
17vf8hz72rg86rf4fy8dp0nk0 *  node1  Accepted    Ready   Active        Leader
38gxy2vel09meso8m7xqr2082    node2  Accepted    Ready   Active
460buexp0kvmy743p12sjw9g2    node3  Accepted    Ready   Active
7qeywwggqe3vcbxu3qe0u9kgu    node2  Accepted    Down    Active
8nhi5srn374xpc97yxjckbz8v    node2  Accepted    Down    Active
```
```
docker@node1:~$ docker info
Containers: 14
 Running: 3
 Paused: 0
 Stopped: 11
Images: 3
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 55
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: active
 NodeID: 17vf8hz72rg86rf4fy8dp0nk0
 IsManager: Yes
 Managers: 1
 Nodes: 5
 CACertHash: sha256:3dab9fe747aadcab8a825310c9accde013b06c887f6176617ae44091b18fa5ac
Runtimes: default
Default Runtime: default
Security Options: seccomp
Kernel Version: 4.4.13-boot2docker
Operating System: Boot2Docker 1.12.0-rc2 (TCL 7.1); HEAD : 52952ef - Fri Jun 17 21:01:09 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: node1
ID: 6FHJ:7FHF:K4FN:V4XS:GPSR:ZRGU:72BO:SHBT:KF7P:QNDZ:C7D7:44GB
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 61
 Goroutines: 189
 System Time: 2016-06-29T12:54:17.309234739Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8
```

```
docker@node1:~$ docker version
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:45:29 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:45:29 2016
 OS/Arch:      linux/amd64
```

**Comment by cpuguy83** [comment]
I believe this is because a new node ID is generated and needs to be generated.
Basically, this is likely the intended behavior.

Ping @diogomonica @aaronlehmann

**Comment by F21** [comment]
@cpuguy83 Then, I guess this should just be documented. However, if a node leaves and rejoins, it leaves a "phantom node" when we run `docker node ls`. Do the managers automatically prune these nodes, or do we have to remove them manually?

**Comment by thaJeztah** [comment]
Related to https://github.com/docker/docker/issues/24088

**Comment by tonistiigi** [comment]
Yes, this is a dupe of #24088. Managers never remove any nodes, `node rm` needs to be run by the user. 

NodeID is assigned by the cluster on join, not a static identity fixed to a single docker installation.

**Comment by F21** [comment]
@tonistiigi Would it make sense for the manager to automatically prune nodes that have been down for a pre-defined amount of time?

**Comment by thaJeztah** [comment]
I'll close this issue as a duplicate of https://github.com/docker/docker/issues/24088 (thanks for reporting @F21!)

**Comment by tonistiigi** [comment]
@F21 I don't think that would be good. We don't know why the node is down and if will it ever come back. Atm, worker node can not make any changes to the cluster state, that includes even making changes to it's own node object. Maybe in the future we could allow removing own node on leave or marking it some way so that manager knows that it will never come back.

**Comment by F21** [comment]
@tonistiigi Makes sense! :smile:

**Comment by dvohra** [comment]
Another manifestation of a duplicate node is that the node cannot be promoted by hostname but gets promoted by ID.

**Comment by thaJeztah** [comment]
@dvohra yes, IIRC, that's because hostname is considered "untrusted" data, because the hostname can be set by the worker node itself; the ID can only be set by managers/swarm itself, so cannot be "spoofed".

**Comment by dvohra** [comment]
@thaJeztah Thanks for the clarification. Results in "ambiguous node" error if hostname is used.

**Comment by dvohra** [comment]
@thaJeztah But why should a demoted node continue to be listed with Availability as "Active"? "Active" implies tasks can be scheduled on the node. How could the Status be "Down" which implies not ready for use and Availability be "Active"? A demoted node for which a new node id has been created should be removed. The `docker node rm `command should be required.

**Comment by dvohra** [comment]
Same issue as https://github.com/docker/docker/issues/24088

**Comment by thaJeztah** [comment]
"demote" turns a _manager_ node into a _worker_ node. The node can still be used as worker after that.  You can `docker node update --availability=drain <node-id>` to make the node no longer accept workloads (and to move the tasks that are running on the node to other workers).

`docker node rm` removes the node from the cluster

**Comment by dvohra** [comment]
Same issue as in preceding post which has not been answered:

 How could the Status be "Down" which implies not ready for use and Availability be "Active"?

**Comment by dvohra** [comment]
Are two commands really required to make a Swarm node remove or leave a Swarm.

From command description:

`docker swarm leave [OPTIONS]`

"Leave the swarm"

`docker node rm`

"Remove one or more nodes from the swarm"

**Comment by dvohra** [comment]
Is the sequence to remove a manager node the following with using `--force` option the following?

1. Demote the manager node
2. Drain the worker node
3. Make the  worker node leave the Swarm
4. Remove the node

**Comment by dvohra** [comment]
Similar issue to https://github.com/docker/docker.github.io/issues/1451
