### ISSUE TITLE
Support plugins/hooks for swarm service creation

### ISSUE THREAD

**Issue by F21** [docker/docker#24114]
As mentioned in #24113, we want to use [Vault](https://github.com/hashicorp/vault) to provide containers access to secrets like api keys and access to databases. 

We would request that vault generate a temporary token, which is passed to the container, and the process inside exchanges it for a more permanent token (which has to be renewed of course).

It would be nice if docker allows us to hook into the container creation, scaling process (as a plugin) so that we can generate a temporary token and inject it as an environment variable into each task as they are created.

**Comment by mgoelzer** [comment]
Dup of #24113
