### ISSUE TITLE
mount -o bind can't work

### ISSUE THREAD

**Issue by lifubang** [docker/docker#24118]
** docker version: 1.11.0-dev **
** OS: Ubuntu 14.04 platform 64 **
** Image: Ubuntu 14.04 **
When I use mount -o bind /dev dev/, it said permission denied.

I need to use tty in chroot. so I must bind chrootpath/dev to /dev. How to resolve this problem?
thx very much.

```
root@58871553cd65:/home/oj/run4# ls
Main.nodejs    Main.nodejs.2  ce.txt  data.in  df         java.policy  lib64  more    nodejs.0.10.25     user.out
Main.nodejs.1  bin            cookie  dev      error.out  lib          ls     nodejs  predefined.nodejs  usr
root@58871553cd65:/home/oj/run4# ls dev
root@58871553cd65:/home/oj/run4# mount -o bind /dev dev/
mount: permission denied
```

**Comment by cpuguy83** [comment]
You need `--privileged` to use mount.

The `mount` syscall is blocked by the apparmor profile, as well as by dropping CAP_SYS_ADMIN, and seccomp.
In 1.12 you should be able to just use `--cap-add SYS_ADMIN` and the seccomp profile will be loosened up as well... but still apparmor would block this.
