### ISSUE TITLE
Does allowing anonymous access to a private docker registry violate docker spec?

### ISSUE THREAD

**Issue by peterlynch** [docker/docker#24129]
I work on the Sonatype Nexus Repository Manager team and we have support for private docker registries.

I would like to get the official stance from a Docker spec representative on my question.

I know Docker Hub requires authentication. The Docker Trusted Registry product states that it will allow anonymous access until auth is enabled. However it also states you cannot even create a registry until auth is enabled.

Reported end user issues I found inside docker issue tracker are not clear on this and the spec does not seem to be either. Some state it is either all anonymous or all login. Some state anonymous is not valid for certain docker commands other than push.

We have customers who want anonymous read access to docker images, but at the same time require authenticated push / write access to their hosted private registry.

So, does allowing anonymous access to private docker registry violate docker spec? Is it a valid use case according to Docker maintainers? Is there a stance either one way or the other if a private registry implementation allows anonymous pull/read access?

I am filing this as a public issue because it would be a helpful reference to point at for our customers ad dev team.

Thanks.

**Comment by duglin** [comment]
I would think that would be an implementation choice.

**Comment by thaJeztah** [comment]
ping @stevvooe perhaps you could have a look?

**Comment by stevvooe** [comment]
The Docker Registry HTTP API Specification is fairly agnostic on how a registry should be secured.  All of the access models you describe are supported. More complex authorization models work best with a token-based auth, as it is the most granular. We even do all anonymous access through the Hub with tokens.

Most issues arise when trying shoehorn Basic auth and policy enforcement into an HTTP proxy.

Is there a specific problem you are trying to solve with this question?

**Comment by peterlynch** [comment]
@stevvooe thanks for the response.

We are trying to ensure that we do not implement any authentication or authorization logic that violates a policy that Docker fundamentally unsupports. The scenarios we encounter include:

- anonymous read access ( no basic auth required ) to some, but restricted access to specific ( requiring auth ) resources inside the same registry
- denying access to anonymous users,  read only for some users,  and writable for a specific set of others

We are trying to support these scenarios with relatively old Docker clients ( back to 1.8 ) and Docker clients maintained by third parties such as RedHat which often differ from the official Docker client behavior.

>  All of the access models you describe are supported.

We have interpreted open [issue 17317](https://github.com/docker/docker/issues/17317) to mean that [Docker client does not play well after the initial requests when a registry replies with 401](https://github.com/docker/docker/issues/17317#issuecomment-153498762) , at least in older versions of the clients mentioned there. So is the bug valid and not yet fixed?

The main crux of the issue is this quote: 

> Docker client only handles 401 for the "GET /v2/" call, but we don't know yet whether the next call will be a push (would require auth) or a pull (would not require auth).

At one time we concluded this means that a registry can either work always requiring authc or never requiring authc.

We get occasional reports from users about failing anonymous docker pull requests to our implementation, and we want to ensure we have a more complete picture from the official Docker maintainers about when 401 should and should not trigger the Docker client to send credentials or when it triggers special actions inside the client to perform alternate logic. Any updates to #17317 or any further guidance on how and when docker client should behave with 401 responses would be very much appreciated.

**Comment by stevvooe** [comment]
In general, I'd recommend that you setup exhaustive testing against the products you support. That is the only way to provide the assurance that you're selling and ensures that we don't introduce bugs for scenarios that we may not test for. We try to do testing across several versions but there are too many variations for us to test all scenarios.

From a protocol perspective, it is best to stick to token auth and the V2 protocol. It is the most secure and granular approach. This means handing out anonymous tokens. Basic auth is inherently insecure and token auth, even for anonymous scenarios, doesn't cost you anything.

> We have interpreted open issue 17317 to mean that Docker client does not play well after the initial requests when a registry replies with 401 , at least in older versions of the clients mentioned there. So is the bug valid and not yet fixed?

That issue is trying to use nginx config to apply complex policy, which is inadvisable. These scenarios are supported easily with token authentication. If you still need basic auth, you can use it with a token server.

Most of the issues around auth handling have been fixed.

If you could file a specific issue with the actual scenario, we can take a look.

**Comment by peterlynch** [comment]
Thanks for the information.

**Comment by thaJeztah** [comment]
Thanks both! And good luck on the implementation @peterlynch

**Comment by stevvooe** [comment]
@peterlynch No problem. I hope this is sufficient.

Please feel free to reach out to me directly if you have more questions.
