### ISSUE TITLE
Consider using `--format` string instead of `--pretty` flag

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#24122]
docker ps and docker inspect handle all formatting via the --format flag, like so:

docker ps --format 'table {{ .Names }}\t{{ .ID }}' for the table format
docker ps --format '{{.Names}}' for no formating
Could also do something like --format 'pretty'

This also has the benefit of allowing users to customize their output via config file in ~/.docker/config.json

**Comment by tiborvass** [comment]
Related to https://github.com/docker/docker/issues/23689

**Comment by vdemeester** [comment]
@cpuguy83 the `--format` for `ps` is not the same as the one for `inspect` ; the behavior and code path are different though. 
- For `ps` we use `api/client/formatter`, support a pre-defined subset of element and support for client config via `config.json`. For 
- For `inspect` it's more or less only use go templates.

We could add some *formatter-like* support for inspect `--format` and thus implementing an *auto* `pretty` formatter. I'll take a look how feasible this is (in the current time frame :angel:)

**Comment by vdemeester** [comment]
I'm taking a look at that one :wink:

**Comment by tiborvass** [comment]
Closing in favor of #24148
