### ISSUE TITLE
runit installs correctly through a Dockerfile, but not when ran locally on the container

### ISSUE THREAD

**Issue by blakestoddard** [docker/docker#24136]
**Output of `docker version`:**

```
[blake@mbp | ~] $ docker version
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   a7119de
 Built:        Fri Jun 17 22:09:20 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
[blake@mbp | ~] $ docker info
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 65
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 87
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: default
Default Runtime: default
Security Options: seccomp
Kernel Version: 4.4.13-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.954 GiB
Name: moby
ID: UFP5:AIUZ:75MZ:MXHC:ARUO:L3DW:2GZG:H2WZ:3M7X:TOYE:2OLU:L5SO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 30
 System Time: 2016-06-29T19:19:16.279527148Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16, localhost, 127/8
Username: bmstoddard
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This issue occurs through Packer as well.

**Steps to reproduce the issue:**
1. Create a Dockerfile that looks similar to so:

```
FROM ubuntu

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y runit
```
1. Build `docker build .`
2. Observe that the `apt-get install` for runit works great and throws no errors back.
3. Try `docker run -it ubuntu bash` and then once the shell comes up, run `apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y runit`

**Describe the results you received:**

When you run the `apt-get install runit` command from a `RUN` command in a Dockerfile, it works correctly. However, if you try to run the command locally on a container through a bash shell, or through a Packer build, you get an error an apt-get exit code of 1.

**Describe the results you expected:**

I'd expect that no matter if I run the `apt-get install` commands through a `RUN` command in a Dockerfile, locally in a container through a bash shell, or through a Packer build file, that it should work. Any ideas as to why it only works in 1/3 of those methods?

**Additional information you deem important (e.g. issue happens only occasionally):**

The Ubuntu version from the `ubuntu` image is 16.04.

When running the `apt-get install` command locally, this is the output you get:

```
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  fgetty
Suggested packages:
  socklog-run
The following NEW packages will be installed:
  fgetty runit
0 upgraded, 2 newly installed, 0 to remove and 16 not upgraded.
Need to get 121 kB of archives.
After this operation, 567 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu xenial/universe amd64 fgetty amd64 0.7-1 [18.9 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial/universe amd64 runit amd64 2.1.2-3ubuntu1 [102 kB]
Fetched 121 kB in 0s (237 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package fgetty.
(Reading database ... 7256 files and directories currently installed.)
Preparing to unpack .../fgetty_0.7-1_amd64.deb ...
Unpacking fgetty (0.7-1) ...
Selecting previously unselected package runit.
Preparing to unpack .../runit_2.1.2-3ubuntu1_amd64.deb ...
Unpacking runit (2.1.2-3ubuntu1) ...
Setting up fgetty (0.7-1) ...
Setting up runit (2.1.2-3ubuntu1) ...

[1]+  Stopped                 DEBIAN_FRONTEND=noninteractive apt-get install -y runit
```

**Comment by thaJeztah** [comment]
Could the difference be that in the "manual" approach, a TTY is attached? Also, what happens if you omit the `DEBIAN_FRONTEND`?

**Comment by johvet** [comment]
I've hit the same road block. And after looking into the package's `postinst` script, it is clear what happens.
```
...
test ! -d /proc/1 || kill -s HUP 1
...
```
So it sends a SIGHUP to the process with ID 1, and I guess that's nothing docker wants to receive at that point.

**Comment by jacknlliu** [comment]
@blakestoddard  why close this issue? Did you really got the solution about it?
