### ISSUE TITLE
[Swarm mode] Embeded DNS with simple containers on different nodes

### ISSUE THREAD

**Issue by mort1k** [docker/docker#24138]
Hi, may be that think it part of https://github.com/docker/docker/issues/23901
Embeded dns do not resolve simple containers (not as service) located on different nodes.

**Comment by mort1k** [comment]
Embeded dns can use swarm datastore?

**Comment by sanimej** [comment]
@mort1k Can you clarify what you mean by `simple containers` ? If you are referring to the short-id of the container (which is also the container's default hostname) it has been fixed in 1.12.1.

**Comment by sanimej** [comment]
@mort1k Closing this issue. We can reopen it if still see the problem with 1.12.1
