### ISSUE TITLE
[Docs code snippets] Make it obvious what is command what is result

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker#24130]
Sometimes when reading the docs, it's not obvious for some users what part is the command, and what part is the result of running the command.
See #24031 for more context.

Consider adding a blank like between the command and the result, for improving clarity.
We're already doing this in some doc pages. [Example](https://docs.docker.com/ucp/installation/uninstall/).

**Comment by ardnaxelarak** [comment]
#dibs
