### ISSUE TITLE
Running docker run hello-world produces an error on fresh install

### ISSUE THREAD

**Issue by KubqoA** [docker/docker#24131]
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:39 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:39 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.11.2
Storage Driver: vfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.16.6-042stab113.11
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 4 GiB
Name: 2programmers
ID: TYQJ:7PMP:X3RE:A4ZC:3NHN:ZEXW:NXTO:22SU:P5IG:D4XT:M4MK:GWFJ
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VPS server, OpenVZ container

**Steps to reproduce the issue:**
1. Follow the official guide to install Docker on Debian 8
2. As root user run docker run hello-world
3. Observe the results

**Describe the results you received:**
I got an error message: `docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: could not synchronise with container process: could not create session key: too many links".`

**Describe the results you expected:**
I was expecting some Hello world message to confirm that the installation went ok.

**Additional information you deem important (e.g. issue happens only occasionally):**
Tried restarting, installing base system again and then immediately only Docker with it's requirements, every time the same result.

**Comment by KubqoA** [comment]
Could someone help me please?

**Comment by cpuguy83** [comment]
ping @mlaventure

**Comment by mlaventure** [comment]
You need to update the amount of session key allowed on your system. it seems like you already ran out of available slots. You can check `/proc/sys/kernel/keys/root_maxkeys` for the current limit

**Comment by mlaventure** [comment]
`cat /proc/key-users` should show you the global usage. Echo a new limit into `/proc/sys/kernel/keys/root_maxkeys` to update it.

**Comment by mlaventure** [comment]
Oh! My bad, read the error message to fast.

You have a `EMLINK` issue not a `EDQUOT`.

You shouldn't get this with a kernel above `3.6` if I'm not mistaken which make this situation weird.

I'll check your kernel version code to see what can cause this.

**Comment by mlaventure** [comment]
@KubqoA although `docker info` reports `3.16.6` for the kernel, I think the underlying one is actually a `2.6.32` one since this is what is being used by OpenVZ (see https://openvz.org/Download/kernel/rhel6/042stab113.11)

Unfortunately, I do not have a solution or workaround for you.

In 1.12 you will be able to specify different runtime and runtimeargs which would allow you to tell `docker-runc` not to make use of the keyring.

**Comment by thaJeztah** [comment]
correct, OpenVZ is still at kernel 2.6, so it's unlikely to work, also see https://github.com/docker/docker/issues/21570#issuecomment-212413961

**Comment by KubqoA** [comment]
Ah okay thanks for the help anyway :)
