### ISSUE TITLE
Swarm update does not allow both workers and managers to be auto-accepted

### ISSUE THREAD

**Issue by johnharris85** [docker/docker#24143]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      linux/amd64
 Experimental: true

```
**Output of `docker info`:**

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      linux/amd64
 Experimental: true
john@j-think:~/workspace/docker$ docker info
Containers: 8
 Running: 8
 Paused: 0
 Stopped: 0
Images: 228
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 761
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: active
 NodeID: b8436t7uvxuhjbs1v0krssw7h
 IsManager: Yes
 Managers: 1
 Nodes: 1
 CACertHash: sha256:091758bd45885b71ffbcd8ae21cea1b55f4c1d48dc1b17a55683dce16412800c
Runtimes: default
Default Runtime: default
Security Options: apparmor seccomp
Kernel Version: 3.16.0-73-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.06 GiB
Name: j-think
ID: OCMX:LCWD:ZLEO:SGYW:ZWUQ:YLI3:TPPY:4ZLH:GBXC:PKJ2:FNNF:TOOL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: johnharris85
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Steps to reproduce the issue:**
1. `docker swarm init`
2. `docker swarm update --auto-accept manager`
3. `docker swarm update --auto-accept worker`

**Describe the results you received:**
Only the worker is set to auto-accept.

**Describe the results you expected:**
Both worker and manager should be set to auto-accept.

**Additional information you deem important (e.g. issue happens only occasionally):**
Code (`api/client/swarm/opts.go#98`) only allows one or the other to be marked as auto-accept.

Should add a `ALL` option (`docker swarm update --auto-accept all`).

**Comment by dnephin** [comment]
Ya, this changed a few times. Setting the flag resets other flags (which matches the current behaviour of `service update`, but we're trying to change that).

**Comment by dnephin** [comment]
@johnharris85 the way to set both right now is: `docker swarm update --auto-accept worker --auto-accept manager`, but that may not be obvious from the help text.

**Comment by johnharris85** [comment]
Ah OK thanks @dnephin, It isn't ;) I implemented `all` primarily because it fits with `none`. I also like `all` as a better UX. Don't feel super strongly about it now there I know the correct way though. Docs / CLI help needs to be updated after a decision though as it's not clear right now.

**Comment by dnephin** [comment]
I think the problem with `all` is that it doesn't work if we add a third type. We'd have no good way to set two of three.

I think the current behaviour is correct (where you can set ` --auto-accept worker --auto-accept manager`). 

What we need to fix is that setting one resets the entire map. I think we should make this behaviour consistent with how `service update` is going to work, using `--auto-accept-add` and `--auto-accept-rm`, like in #23773

**Comment by johnharris85** [comment]
Strongly agree with the first point. So with the proposed changes you should be able to do things like:

`docker swarm init --auto-accept-add worker --auto-accept-add manager`

```
"AcceptancePolicy": {
                "Policies": [
                    {
                        "Role": "worker",
                        "Autoaccept": true
                    },
                    {
                        "Role": "manager",
                        "Autoaccept": true
                    }
                ]
            },
```

`docker swarm update --auto-accept-rm manager`

```
"AcceptancePolicy": {
                "Policies": [
                    {
                        "Role": "worker",
                        "Autoaccept": true
                    },
                    {
                        "Role": "manager",
                        "Autoaccept": false
                    }
                ]
            },
```
Happy to take a crack at this, want me to update the existing PR (#24146) or create a new one?

**Comment by dnephin** [comment]
Thanks! Existing one would be great.

**Comment by aaronlehmann** [comment]
I don't want to derail this one, but I actually think it's better for `--auto-accept` to overwrite the old value. I can't really imagine any workflow where you would want to make an incremental change to the auto-accept settings. Instead, you want to set it to `worker`, `manager` or both. That feels a lot more intuitive to me.

I see the argument that `--auto-accept-add` and `--auto-accept-rm` would be more consistent with some of the `service update` options, but there are others like `--image` which are not incremental, and I think a setting that has only 3 possible values doesn't really make sense as an incremental one.

**Comment by aluzzardi** [comment]
worker, manager, all, none?

**Comment by dnephin** [comment]
What happens when you add the third type? `all` doesn't work for the "two of three" case any more. I think we're better off accepting a list of values instead of `all`.

If `--auto-accept worker --auto-accept manager` isn't clear we could support `--auto-accept worker,manager`. That would actually be easier to parse.

**Comment by aaronlehmann** [comment]
> If `--auto-accept worker --auto-accept` manager isn't clear we could support `--auto-accept worker,manager`. That would actually be easier to parse.

That would be my preference. I'm actually surprised this takes special support - I thought that's how cobra string slices work.

**Comment by johnharris85** [comment]
Isn't comma-separated inconsistent with how some of the other flags work though? And @dnephin you could still specify --auto-accept worker --auto-accept manager as 'two of three' when also having an 'all' option. 'All' for me is really just a UX shorthand.

**Comment by dnephin** [comment]
It is how `StringSliceVar()` works, but this isn't using `StringSliceVar()` because it was validating the values and adding secret to create the expected API types. 

I guess as long as the comma-separated method works, it doesn't hurt to have `all` as well.

**Comment by johnharris85** [comment]
Updated the PR to include support for comma-separated and `all`. Also refined / simplified the logic for flag conflicts.

**Comment by tiborvass** [comment]
@dnephin @aaronlehmann so did we decide on doing `--auto-accept manager,worker` ?

**Comment by aaronlehmann** [comment]
SGTM

**Comment by tiborvass** [comment]
@aaronlehmann can we error out if we do `--auto-accept none,manager` ? `none` has to be by itself.

**Comment by aaronlehmann** [comment]
yup

**Comment by johnharris85** [comment]
@tiborvass ye, this case is caught (and tested for)

**Comment by tiborvass** [comment]
Related to #24430

**Comment by dnephin** [comment]
I think this can be closed now that #24146 is merged?

We always supported both both, now it's more obvious how to set both.

**Comment by johnharris85** [comment]
Ye, after you showed the correct 'previous' way I could have changed the title I guess. But yes, this can be closed.

**Comment by johnharris85** [comment]
Thanks a lot for all your help btw @dnephin && @aaronlehmann !

**Comment by dnephin** [comment]
Thanks for the PR to improve this!
