### ISSUE TITLE
Why is docker service option '--network' instead of '--net'?

### ISSUE THREAD

**Issue by nathanleclaire** [docker/docker#24145]
1.12.0-rc2

@dnephin @vieux 

Why `--network` instead of `--net` for service (`--net` is consistent with existing `docker run`)?

```console
$ docker service create --name myservers --net mynet nginx
unknown flag: --net
See 'docker service create --help'.
$ docker service create --name myservers --network mynet nginx
0elxqoc2aqhef6cqy3qbfhzgl
```

**Comment by dnephin** [comment]
Some people felt that `--network` was more appropriate now that it's for network names more than just network mode.

See #23324 for the PR to add it to `run`.

**Comment by nathanleclaire** [comment]
Hm, I have to say I'm with Darren here: https://github.com/docker/docker/pull/23324#issuecomment-225093248, I have always assumed `--net` to be short for `--network` and never thought of it as "network mode" (i.e. adjective) vs. "network" (noun) for a while now (since `libnetwork` was brought in).

However, I'm happy to defer to judgement of the team, so feel free to close if it feels superfluous.  As long as everything's consistent, that's my main concern.

**Comment by aaronlehmann** [comment]
I also found the inconsistency confusing, and would prefer that we keep the commands consistent.

**Comment by tiborvass** [comment]
We decided to accept #23324 and add `--network` to create/run, not deprecate `--net`, simply hide it.

**Comment by nathanleclaire** [comment]
Close then?

**Comment by tiborvass** [comment]
@nathanleclaire no. #23324 will fix this issue, it's not merged yet.

**Comment by albers** [comment]
@tiborvass #23324 is merged now, so this can be closed.

**Comment by tiborvass** [comment]
Thanks @albers
