### ISSUE TITLE
Failure to upgrade from 1.12.0-rc-beta16 (build: 4760) to 1.12.0-rc-beta17 (build: 5022)

### ISSUE THREAD

**Issue by konstruktoid** [docker/docker#24142]
**Output of `docker version`:**

```
Docker 1.12.0-rc-beta16 (build: 4760)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

PS C:\Users\thomas> systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.10586 N/A Build 10586

**Steps to reproduce the issue:**

Click `Install Update`, see below images.

**Describe the results you received:**
1. ![Windows](https://i.imgur.com/McWDq50.jpg)
2. ![Windows](https://i.imgur.com/8R5rCCk.jpg)
3. ![Windows](https://i.imgur.com/qHPo0gT.jpgg)
4. ![Windows](https://i.imgur.com/I7jZdwD.jpg)

**Describe the results you expected:**

Upgrade to 1.12.0-rc-beta17 (build: 5022)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
Thanks for reporting! This is an issue with the Docker for Windows beta, so let me ping some people;

ping @dgageot @friism PTAL

**Comment by dgageot** [comment]
Thanks for reporting @konstruktoid, we are to going to fix that for the next release. Sorry for the inconvenience!

**Comment by konstruktoid** [comment]
Same issue when trying to upgrade _and_ when trying to install 1.12.0-RC3-BETA18. 
I'm also unable too uninstall the current version.
![image](https://cloud.githubusercontent.com/assets/7956715/16818322/7160342c-4947-11e6-9169-c22a0b15d85a.png)

![image](https://cloud.githubusercontent.com/assets/7956715/16818191/cef897b0-4946-11e6-87af-e54f54225365.png)

**Comment by dgageot** [comment]
@ebriney Can you help @konstruktoid uninstall his old version? Then it should be possible to install the latest (Beta20) version.

**Comment by ebriney** [comment]
@konstruktoid I'm working on a script to clean everything but there are still some hidden things in the registry ! Need to install twice for now

**Comment by konstruktoid** [comment]
Hi @ebriney , I'm trying to install 1.12.0-BETA21 but I'm still getting the same messages as above.
Looking forward to trying the script out.

**Comment by ebriney** [comment]
Sorry i'm not at the office but you can find it on the link below 

https://forums.docker.com/t/cannot-uninstall-docker-for-windows/15661/9

**Comment by konstruktoid** [comment]
Thanks for the link @ebriney and I ran the script, and tried to reinstall twice as well, without success.
I also removed the Hyper-V Docker VM, then removed C:\Program Files\Docker, and then tried installing Beta InstallDocker.msi. This fails as well.

![image](https://cloud.githubusercontent.com/assets/7956715/17258972/ace44f36-55c9-11e6-9c7d-fbd6b15b4316.png)

**Comment by vinnyfs89** [comment]
Same problema here. I just can't uninstall docker from windows 10 OS...

**Comment by ebriney** [comment]
@vinnyfs89 What version did you install? Did you try to remove it with the uninstall script?

**Comment by thedewi** [comment]
Upgrade, service-stop, and uninstall are still hanging for me in Windows 10 in versions 1.12.3, 1.12.5.

I was prompted to auto-update 1.12.3, which stalled for hours, so I rebooted and tried again. Then I tried running the Powershell commands ebriney linked above, rebooted, and installed the latest version (1.12.5). It would hang on attempts to stop the Windows service, and on uninstall and reinstall. I disabled the Windows service to stop it hanging and disabled automatic start in the tray applet, and after some more reboots and attempts the uninstall has removed part of the app, but it still hangs with no errors in the log, and when I reboot the Windows service comes back, and the files and uninstall listing are still present.

**Comment by PeteBoyRocket** [comment]
I'm also seeing the issue exactly as @thedewi describes.

**Comment by thedewi** [comment]
(I don't know whether the presenting problems are actually related, but they have a few similarities)

**Comment by thaJeztah** [comment]
Thanks for linking that one! Let me close the issue here, please continue the discussion over there
