### ISSUE TITLE
[docs] Swarm mode auto-accept defaults

### ISSUE THREAD

**Issue by johnharris85** [docker/docker#24140]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 8
 Running: 8
 Paused: 0
 Stopped: 0
Images: 228
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 761
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null overlay host
Swarm: active
 NodeID: bzk4vv65idjvtxi09gdqtfwbd
 IsManager: Yes
 Managers: 1
 Nodes: 1
 CACertHash: sha256:c0fdf51a4eaa403e7119c77001349cf6bc025542e166179a7ae3ba50f5b422f9
Runtimes: default
Default Runtime: default
Security Options: apparmor seccomp
Kernel Version: 3.16.0-73-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.06 GiB
Name: j-think
ID: OCMX:LCWD:ZLEO:SGYW:ZWUQ:YLI3:TPPY:4ZLH:GBXC:PKJ2:FNNF:TOOL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: johnharris85
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Steps to reproduce the issue:**
1. `docker swarm init`
2. `docker swarm inspect`

**Describe the results you received:**
I see only the worker marked to auto-accept into the swarm.

**Describe the results you expected:**
I expect to see both manager and work set to auto-accept into the swarm as per the documentation here: https://docs.docker.com/engine/reference/commandline/swarm_init/.

What's the desired behaviour here? I'm happy to submit a PR for either the docs or the swarm defaults. Personally think the current behavior should stay and docs should be updated (seems like a sensible default).

**Comment by cpuguy83** [comment]
Docs are using old output:

```
Usage:	docker swarm init [OPTIONS]

Initialize a Swarm

Options:
      --auto-accept value   Auto acceptance policy (worker, manager, or none)
      --force-new-cluster   Force create a new cluster from current state.
      --help                Print usage
      --listen-addr value   Listen address (default 0.0.0.0:2377)
      --secret string       Set secret value needed to accept nodes into cluster
```
Is the current output.

Right now only worker is auto-accepted -- this may even change before release and default to no auto-acceptance.

**Comment by johnharris85** [comment]
Thanks Brian, ye following that thread as well.

**Comment by aluzzardi** [comment]
@cpuguy83 I think @johnharris85's point is you can't auto-accept both.

@johnharris85: If that's the case, it's purely a CLI issue as the API does support that

/cc @diogomonica @tonistiigi @dnephin

**Comment by johnharris85** [comment]
Subtlety different @aluzzardi. This issue is about the docs not matching behavior. I've created another issue (#24143) for the fact that you can't do both. Working on a PR for that now, looks like a simple CLI change.

**Comment by aaronlehmann** [comment]
@johnharris85: Thanks for pointing out the docs issue. I opened a PR for this here: https://github.com/docker/docker/pull/24248
