### ISSUE TITLE
[1.12] ability to update one or more replicas in a service with a different image

### ISSUE THREAD

**Issue by jhorwit2** [docker/docker#24151]
It would be nice to have the ability to update only some amount of replicas in a service with a different image, so it's easy to test things like canary deploys, etc.

Example: 

```
docker service create --replicas 3 --name awesome_app awesome_img:v5
docker service update --image awesome_img:v6 --flag 1 awesome_app
```

Where flag (couldn't think of a clever name) defaults to the # of replicas. Then the scheduler makes sure that we would have 2 on v5 and 1 on v6.

**Comment by cpuguy83** [comment]
See docker/swarmkit#1045

**Comment by jhorwit2** [comment]
thanks @cpuguy83. i'll close this one and subscribe to that.
