### ISSUE TITLE
Docker engine 1.12 available for Windows Server 2016 TP5 or later?

### ISSUE THREAD

**Issue by selvik** [docker/docker#24160]
Is Docker 1.12 rc available in Windows Server 2016 in TP5?  If not, is there an estimate of when it will be included?  

Thank you!

**Comment by selvik** [comment]
@jhowardmsft Would you be able to help determine the status of this? We are looking forward to being able to use swarm mode of 1.12 on Windows. Thanks!

**Comment by AkihiroSuda** [comment]
https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_server

**Comment by thaJeztah** [comment]
Swarm mode is not yet available on Windows, also see https://github.com/docker/docker/issues/23680

Binaries for docker 1.12-rc2 are linked on the release page (including Windows binaries) https://github.com/docker/docker/releases/tag/v1.12.0-rc2

**Comment by StefanScherer** [comment]
@selvik Here is an update script to update to docker 1.12.0 on Windows https://github.com/StefanScherer/docker-windows-box/pull/6
The swarm mode is not available, but other improvements in `Dockerfile`like the 

```
#escape=`
```

and `SHELL` instruction https://docs.docker.com/engine/reference/builder/#/shell
