### ISSUE TITLE
the log question in swarm mode

### ISSUE THREAD

**Issue by zuhouhu** [docker/docker#24166]
**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by vdemeester** [comment]
@zuhouhu hi :) If this is not a *mistaken* issue creation, could you be more precise ? (both in the title and in the description) :angel:

**Comment by zuhouhu** [comment]
i am sorry,i pressed the wrong button.I am writing the question.




houhu.zu@oceanwing.com
 
From: Vincent Demeester
Date: 2016-06-30 16:28
To: docker/docker
CC: zuhouhu; Mention
Subject: Re: [docker/docker] the log question in swarm mode (#24166)
@zuhouhu hi :) If this is not a mistaken issue creation, could you be more precise ? (both in the title and in the description) ???? 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

-- 
The information in this email and its attachment(s)(if any) is intended for 
the named recipient(s) only and contains privileged and confidential 
information under the property of the sender. Without prior consent, the 
recipient shall not disseminate or disclose this communication to any third 
party. If you are not an intended recipient, you may not peruse,  copy, 
distribute or take any other action on such information. If you have 
received this email in error, please notify the sender immediately by 
e-mail and delete this e-mail from your system. Thanks.

**Comment by dnephin** [comment]
Closing, this was opened as #24167
