### ISSUE TITLE
s390x broken by: Revendor golang.org/x/sys/ to have unix package included

### ISSUE THREAD

**Issue by michael-holzheu** [docker/docker#24168]
Commit 33badc189c4db37ec5e0bc87e2a79332254ec474 "Revendor golang.org/x/sys/ to have unix package included" breaks s390x build because s390x files are missing in golang.org/x/sys/unix:

```
19:01:19 ---> Making bundle: gccgo (in bundles/1.12.0-dev/gccgo)
19:03:04 # golang.org/x/sys/unix
19:03:04 vendor/src/golang.org/x/sys/unix/flock.go:15:30: error: reference to undefined name 'SYS_FCNTL'
19:03:04  var fcntl64Syscall uintptr = SYS_FCNTL
19:03:04                               ^
19:03:04 vendor/src/golang.org/x/sys/unix/sockcmsg_linux.go:15:30: error: reference to undefined name 'SizeofUcred'
19:03:04   b := make([]byte, CmsgSpace(SizeofUcred))
```

See https://jenkins.dockerproject.org/job/Docker%20Master%20(z)%20Binaries/779/console

ping @yongtang

**Comment by yongtang** [comment]
Thanks @michael-holzheu. I created a pull request #24177 and removed golang.org/x/sys/unix. I think this change will fix the s390x build error.

I am not sure how to build and test on s390x. Could you take a look and let me know if the issue still exists?

**Comment by michael-holzheu** [comment]
We need at least commit golang/sys@33267e036fd93fcd26ea95b7bdaf2d8306cb743c.
With this commit docker builds on s390x.

ping @thaJeztah

**Comment by michael-holzheu** [comment]
> I created a pull request #24177 and removed golang.org/x/sys/unix. I am not sure how to build and test on s390x. Could you take a look and let me know if the issue still exists?

Yes, I will retest when your PR is merged. Thanks for the fast response!
