### ISSUE TITLE
Creation of bridge doesn't add iptables rules

### ISSUE THREAD

**Issue by felixsanz** [docker/docker#24176]
When i create a bridge with this command:

`/usr/bin/docker network create --driver bridge --internal --subnet=172.20.0.0/24 br0`

i can see 2 new rules in iptables:

```
-A DOCKER-ISOLATION ! -s 172.21.0.0/24 -o br-12f7b90ae6c0 -j DROP
-A DOCKER-ISOLATION ! -d 172.21.0.0/24 -i br-12f7b90ae6c0 -j DROP
```

And if i start a container using that bridge, the container doesn't have internet connection to the outside.

BUT, if i restart docker service/daemon **AFTER** bridge creation, i can see some new rules added to iptables and the containers now have access to the outside.

Why is going on? How i can fix this? It's expected?

**Comment by cpuguy83** [comment]
@felixsanz `--internal` means no internet connection.
If you can restart docker and get an internet connection with these `--internal` networks, this is a bug.

**Comment by cpuguy83** [comment]
ping @aboch

**Comment by felixsanz** [comment]
@cpuguy83 You're right, i forgot i'm using `--internal`. And yes, this is a bug because restarting docker gives the containers access to the outside.

Regarding to my problem, if i remove the flag those containers can, for example, ping or curl the outside (OUTPUT).

But what about INPUT ? For example, if my container is a database using port 9200, without `--internal` the port is exposed on internet? Or the container still have to deal with my iptables rules from the host? (the host doesn't accept connections on port 9200, DROP policy)

**Comment by aboch** [comment]
@felixsanz 
That would be a bug. I have not ben able to reproduce yet (testing with 1.12 from master).
What docker version are you running ?
Also, do you have other user defined bridge network installed ?
Can you attach the o/p of 
` iptables -S DOCKER-ISOLATION`

Thanks

**Comment by felixsanz** [comment]
I'm running 1.10.3 (coreOS stable)

No more user defined bridges.

Here is the output, but i'm not running anymore `--internal`

```
-N DOCKER-ISOLATION
-A DOCKER-ISOLATION -i docker0 -o br-851bd89bbca2 -j DROP
-A DOCKER-ISOLATION -i br-851bd89bbca2 -o docker0 -j DROP
-A DOCKER-ISOLATION -j RETURN
```

**Comment by aboch** [comment]
@felixsanz 
Ok, what you now see is the expected output, the chain includes the rules to block traffic across the existing bridge networks.

Regarding the internal network no longer being internal after daemon reload, I think you are hitting the issue now fixed by https://github.com/docker/libnetwork/pull/1076

**Comment by felixsanz** [comment]
Probably. coreOS use an old version of docker (1.10.3). Close the issue if you think it's fixed. I can't bump the version yet to confirm :(

**Comment by aboch** [comment]
Thanks @felixsanz, closing.
