### ISSUE TITLE
Swarm mode on Windows

### ISSUE THREAD

**Issue by TheJayMann** [docker/docker#24189]
This really isn't an issue report, nor is it a question, but more a status report of my attempts at getting swarm mode of Docker 1.12 to work with windows container nodes.

Out of the box, any attempt to use swarm mode fails, as the daemon is attempting to create a unix socket for communication, which is not supported. I removed/modified the four pieces of code which attempted to create a listener on control.sock, instead replacing it with tcp listeners, and was able to start making progress on swarm mode.

First, attempting to create a new swarm failed, as the connection is rejected for not specifying a client certificate.  After creating a swarm in Linux, I was able to join the swarm as a worker from Windows without issue.  I was unable to have the Windows node join as a manager.  I tried using the --manager option in the join command, which required me to accept the node.  After accepting, the Linux manager saw the Windows node as a manager, but the Windows node did not see itself as a manager at all.  I also tried to promote the worker to a manager, with the same results.

I then created some services.  When creating a service with an image name that only existed for Linux, half of the replicas would run (the ones assigned to the Linux node), while the others would show as accepted, but not running.  The same opposite behavior occurred when attempting to use an image that only existed for Windows.  I have not yet attempted to try a Linux image which happens to have the same name as a Windows image.  I believe that if I were to initialize a swarm in Linux and immediately set its status to drain, then added Windows worker nodes, this would create a Windows swarm cluster of sorts.

The next thing I wish to try is, instead of removing/modifying the unix socket listeners for tcp listeners, try to implement an npipe listener, similar to what was done for docker API access.

**Comment by friism** [comment]
Pls see this PR from @chanwit too: https://github.com/docker/swarmkit/pull/941

**Comment by TheJayMann** [comment]
I didn't think to check swarmkit for this.  I'll attempt to merge these changes in to see how well it works.

**Comment by friism** [comment]
@TheJayMann awesome, let us know how it goes!

cc @jhowardmsft

**Comment by TheJayMann** [comment]
I have gotten most of the changes in that pull request pulled, but I'm currently having some difficulty dealing with the changes in the cmd folder, as it appears that most of that has been reimplemented and integrated directly into the docker daemon.  It hasn't stopped me yet, but is surely slowing me down now.

**Comment by TheJayMann** [comment]
Now I got to a point where I'm not sure what to do next, mainly due to my lack of knowledge concerning the Go language, as well as my lack of knowledge of how to debug Go applications.  After managing to get all the changes in (and a few failed attempts at doing so), I have gotten to the point where I can do a `docker swarm init`.  After doing so, the client appears to hang.  After connecting another client, I can inspect the swarm and list the nodes.  However, when I list the nodes, it shows the single node without a hostname, membership accepted, status down, active availability, and a leader manager.

**Comment by TheJayMann** [comment]
After a bit of diagnosing, I believe I have found what the error may be.  In the mentioned pull request, the concepts of unix sockets and tcp sockets were abstracted by renaming the indexes on ProtoAddr to be the more generic names of remote and control, and embedding the protocol as the scheme of a url containing the host/port, and then making sure the url was split back into protocol and host/port before being used.  However, the inclusion of swarmkit in docker engine appears to have these addresses used in other places, as I now see in the debug log the following error: `"grpc: Conn.resetTransport failed to create client transport: connection error: desc = \"transport dial tcp: too many colons in address tcp://0.0.0.0:2377\"; Reconnecting to \"tcp://0.0.0.0:2377\""`.  I'm surprised that it is attempting to connect to 0.0.0.0 to begin with.  I'm going to attempt to revert the changes I made importing the pull request and add npipe as a protocol mapping on ProtoAddr when running windows.

**Comment by thaJeztah** [comment]
Looks like overlay networking support for Windows is available now for Windows 10 insider
https://blogs.technet.microsoft.com/virtualization/2017/02/09/overlay-network-driver-with-support-for-docker-swarm-mode-now-available-to-windows-insiders-on-windows-10/

**Comment by friism** [comment]
It's in Windows Server 2016 too: https://support.microsoft.com/en-us/help/4015217/windows-10-update-kb4015217

**Comment by thaJeztah** [comment]
Cool, let me close this issue then 👍

**Comment by panga** [comment]
I just downloaded kb4015217 update and can't make publish work. 

Tasks fail with error:  "Err": "HNS failed with error : The parameter is incorrect. ".

Server Version: 17.03.1-ee-3

"docker network ls" also doesn't show "ingress" network.

**Comment by friism** [comment]
@panga can you try the containerhostnetworking cleanup script from MS? https://github.com/Microsoft/Virtualization-Documentation/tree/master/windows-server-container-tools/CleanupContainerHostNetworking

cc @jmesser82

**Comment by panga** [comment]
@friism This script doesn't work with overlay networks: 

```
Overlay network detected. Id: m9ssd8342ct0
WARNING: This script is not compatible with overlay networking. Before continuing, ensure all overlay networks are removed from your system.
```

I seems that Swarm Mesh network still not working in Windows, even with latest updates. Docs:
https://github.com/Microsoft/Virtualization-Documentation/blob/master/virtualization/windowscontainers/manage-containers/swarm-mode.md

**Comment by JMesser81** [comment]
Swarm routing mesh (ingress network) is not supported on Windows with this update.  You have to use "host" publishing with -publish option.

I'm updating our cleanup script and will have an update soon.
