### ISSUE TITLE
Unified Write Filter for Windows?

### ISSUE THREAD

**Issue by laggingreflex** [docker/docker#24181]
Has [Unified Write Filter](https://msdn.microsoft.com/en-us/library/windows/hardware/mt572001.aspx) (which is seems similar to the Union File System) been considered for Windows? If this were to be implemented, could docker have a truly native solution on Windows without any VM?

**Comment by cpuguy83** [comment]
@laggingreflex Windows already has a native solution which will be part of Windows Server 2016.

**Comment by cpuguy83** [comment]
See the official MS docs on Windows containers here: https://msdn.microsoft.com/en-us/virtualization/windowscontainers/about/about_overview

Also see https://blog.docker.com/2016/04/docker-windows-server-tp5/

tldr; Microsoft is actively porting Docker to Windows, including building all the containerization primitives into the Windows kernel for the server SKU.
