### ISSUE TITLE
Can't run any container after Docker re-install on CentOS7 on AWS

### ISSUE THREAD

**Issue by andreesser** [docker/docker#24184]
**Output of `docker version`:**

```
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-44.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      9419b24-unsupported
 Built:           Fri Jun 24 12:09:49 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-44.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      9419b24-unsupported
 Built:           Fri Jun 24 12:09:49 2016
 OS/Arch:         linux/amd64
```

**Output of `docker info`:**

```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 1
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker--vg-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 264.8 MB
 Data Space Total: 13.72 GB
 Data Space Available: 13.46 GB
 Metadata Space Used: 217.1 kB
 Metadata Space Total: 37.75 MB
 Metadata Space Available: 37.53 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Execution Driver: native-0.2
Logging Driver: journald
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.10.0-327.22.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 2
Total Memory: 7.389 GiB
Name: os-master-0
ID: GVEF:LF3G:VRIH:KU25:AFFA:2LV4:UY4I:IIHA:N3DQ:6MFX:T3YC:7ETI
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Registries: docker.io (secure)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS (ami-7abd0209)

**Steps to reproduce the issue:**
1. Install Docker
2. Configure VM as part of an OpenShift Origin cluster
    (using ansible-playbook openshift-ansible/playbooks/byo/config.yml)
3. Remove OpenShift
    (using ansible-playbook openshift-ansible/playbooks/adhoc/uninstall.yml)
4. Noticed problem for the first time.
5. Removed all Docker-related software and files
    (yum remove docker-common docker-forward-journald docker docker-selinux bridge-utils,
     rm -rf /var/lib/docker /etc/sysconfig/docker*) and rebooted
5. Re-installed Docker
6. Problem persists

**Describe the results you received:**
# docker run -it ubuntu /bin/bash
Unable to find image 'ubuntu:latest' locally
Trying to pull repository docker.io/library/ubuntu ... 
latest: Pulling from docker.io/library/ubuntu
f069f1d21059: Pull complete 
ecbeec5633cf: Pull complete 
ea6f18256d63: Pull complete 
54bde7b02897: Pull complete 
Digest: sha256:bbfd93a02a8487edb60f20316ebc966ddc7aa123c2e609185450b96971020097
Status: Downloaded newer image for docker.io/ubuntu:latest
docker: Error response from daemon: Cannot start container c8d3fa4d9e2d50333c89fc0332886551eaaacfd3e14f7043192c4961ded5e80a: [9] System error: exit status 127.

# tail -n 80 /var/log/messages
Jun 30 16:49:17 os-master-0 kernel: XFS (dm-1): Ending clean mount
Jun 30 16:49:23 os-master-0 kernel: XFS (dm-1): Unmounting Filesystem
Jun 30 16:49:23 os-master-0 kernel: XFS (dm-1): Mounting V4 Filesystem
Jun 30 16:49:23 os-master-0 kernel: XFS (dm-1): Ending clean mount
Jun 30 16:49:23 os-master-0 kernel: XFS (dm-1): Unmounting Filesystem
Jun 30 16:49:23 os-master-0 kernel: XFS (dm-1): Mounting V4 Filesystem
Jun 30 16:49:23 os-master-0 kernel: XFS (dm-1): Ending clean mount
Jun 30 16:49:23 os-master-0 kernel: XFS (dm-1): Unmounting Filesystem
Jun 30 16:49:23 os-master-0 kernel: XFS (dm-1): Mounting V4 Filesystem
Jun 30 16:49:23 os-master-0 kernel: XFS (dm-1): Ending clean mount
Jun 30 16:49:23 os-master-0 kernel: XFS (dm-1): Unmounting Filesystem
Jun 30 16:49:23 os-master-0 journal: time="2016-06-30T16:49:23.806139328Z" level=info msg="{Action=create, Username=root, LoginUID=0, PID=2460}"
Jun 30 16:49:23 os-master-0 kernel: XFS (dm-1): Mounting V4 Filesystem
Jun 30 16:49:23 os-master-0 kernel: XFS (dm-1): Ending clean mount
Jun 30 16:49:23 os-master-0 kernel: XFS (dm-1): Unmounting Filesystem
Jun 30 16:49:23 os-master-0 kernel: XFS (dm-1): Mounting V4 Filesystem
Jun 30 16:49:23 os-master-0 kernel: XFS (dm-1): Ending clean mount
Jun 30 16:49:23 os-master-0 kernel: XFS (dm-1): Unmounting Filesystem
Jun 30 16:49:23 os-master-0 journal: time="2016-06-30T16:49:23.992181162Z" level=info msg="{Action=attach, ID=c8d3fa4d9e2d50333c89fc0332886551eaaacfd3e14f7043192c4961ded5e80a, Username=root, LoginUID=0, PID=2460}"
Jun 30 16:49:23 os-master-0 journal: time="2016-06-30T16:49:23.993703427Z" level=info msg="{Action=start, ID=c8d3fa4d9e2d50333c89fc0332886551eaaacfd3e14f7043192c4961ded5e80a, Username=root, LoginUID=0, PID=2460, Config={Hostname=c8d3fa4d9e2d, AttachStdin=true, AttachStdout=true, AttachStderr=true, Tty=true, OpenStdin=true, StdinOnce=true, Env=[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin], Cmd={parts:[/bin/bash]}, ArgsEscaped=false, Image=ubuntu, NetworkDisabled=false, Labels=map[]}, HostConfig={LogConfig={Type:journald Config:map[]}, NetworkMode=default, PortBindings=map[], RestartPolicy={Name:no MaximumRetryCount:0}, DNS=[], DNSOptions=[], DNSSearch=[], Privileged=false, PublishAllPorts=false, ReadonlyRootfs=false, ShmSize=67108864, Resources={CPUShares:0 CgroupParent: BlkioWeight:0 BlkioWeightDevice:[] BlkioDeviceReadBps:[] BlkioDeviceWriteBps:[] BlkioDeviceReadIOps:[] BlkioDeviceWriteIOps:[] CPUPeriod:0 CPUQuota:0 CpusetCpus: CpusetMems: Devices:[] KernelMemory:0 Memory:0 MemoryReservation:0 MemorySwap:0 MemorySwappiness:0xc208c96788 OomKillDisable:0xc208c96792 PidsLimit:0 Ulimits:[]}}}"
Jun 30 16:49:24 os-master-0 kernel: XFS (dm-1): Mounting V4 Filesystem
Jun 30 16:49:24 os-master-0 kernel: XFS (dm-1): Ending clean mount
Jun 30 16:49:24 os-master-0 kernel: device vethacd861a entered promiscuous mode
Jun 30 16:49:24 os-master-0 kernel: IPv6: ADDRCONF(NETDEV_UP): vethacd861a: link is not ready
Jun 30 16:49:24 os-master-0 kernel: docker0: port 1(vethacd861a) entered forwarding state
Jun 30 16:49:24 os-master-0 kernel: docker0: port 1(vethacd861a) entered forwarding state
Jun 30 16:49:24 os-master-0 kernel: docker0: port 1(vethacd861a) entered disabled state
Jun 30 16:49:24 os-master-0 NetworkManager[534]: <info>  (veth1ae1b57): new Veth device (carrier: OFF, driver: 'veth', ifindex: 4)
Jun 30 16:49:24 os-master-0 NetworkManager[534]: <info>  (vethacd861a): new Veth device (carrier: OFF, driver: 'veth', ifindex: 5)
Jun 30 16:49:24 os-master-0 NetworkManager[534]: <info>  (docker0): bridge port vethacd861a was attached
Jun 30 16:49:24 os-master-0 NetworkManager[534]: <info>  (vethacd861a): enslaved to docker0
Jun 30 16:49:24 os-master-0 NetworkManager[534]: <info>  ifcfg-rh: add connection in-memory (b499ce6a-c7c8-446e-b1cc-04be29f5d957,"vethacd861a")
Jun 30 16:49:24 os-master-0 NetworkManager[534]: <info>  (vethacd861a): device state change: unmanaged -> unavailable (reason 'connection-assumed') [10 20 41]
Jun 30 16:49:24 os-master-0 NetworkManager[534]: <info>  (vethacd861a): device state change: unavailable -> disconnected (reason 'connection-assumed') [20 30 41]
Jun 30 16:49:24 os-master-0 NetworkManager[534]: <info>  (vethacd861a): Activation: starting connection 'vethacd861a' (b499ce6a-c7c8-446e-b1cc-04be29f5d957)
Jun 30 16:49:24 os-master-0 NetworkManager[534]: <info>  (vethacd861a): device state change: disconnected -> prepare (reason 'none') [30 40 0]
Jun 30 16:49:24 os-master-0 NetworkManager[534]: <info>  (vethacd861a): device state change: prepare -> config (reason 'none') [40 50 0]
Jun 30 16:49:24 os-master-0 NetworkManager[534]: <info>  (vethacd861a): device state change: config -> ip-config (reason 'none') [50 70 0]
Jun 30 16:49:24 os-master-0 NetworkManager[534]: <info>  (vethacd861a): device state change: ip-config -> secondaries (reason 'none') [70 90 0]
Jun 30 16:49:24 os-master-0 NetworkManager[534]: <info>  (vethacd861a): device state change: secondaries -> activated (reason 'none') [90 100 0]
Jun 30 16:49:24 os-master-0 NetworkManager[534]: <info>  (vethacd861a): Activation: successful, device activated.
Jun 30 16:49:24 os-master-0 dbus[549]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service'
Jun 30 16:49:24 os-master-0 dbus-daemon: dbus[549]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service'
Jun 30 16:49:24 os-master-0 systemd: Starting Network Manager Script Dispatcher Service...
Jun 30 16:49:24 os-master-0 dbus[549]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
Jun 30 16:49:24 os-master-0 dbus-daemon: dbus[549]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
Jun 30 16:49:24 os-master-0 systemd: Started Network Manager Script Dispatcher Service.
Jun 30 16:49:24 os-master-0 nm-dispatcher: Dispatching action 'up' for vethacd861a
Jun 30 16:49:24 os-master-0 journal: time="2016-06-30T16:49:24.077887996Z" level=info msg="Config: &{CommonCommand:{ContainerPid:0 ID:c8d3fa4d9e2d50333c89fc0332886551eaaacfd3e14f7043192c4961ded5e80a InitPath:/.dockerinit MountLabel:system_u:object_r:svirt_sandbox_file_t:s0:c296,c357 Mounts:[{Source:/var/lib/docker/containers/c8d3fa4d9e2d50333c89fc0332886551eaaacfd3e14f7043192c4961ded5e80a/secrets Destination:/run/secrets Writable:true Data: Propagation:} {Source:/var/lib/docker/containers/c8d3fa4d9e2d50333c89fc0332886551eaaacfd3e14f7043192c4961ded5e80a/resolv.conf Destination:/etc/resolv.conf Writable:true Data: Propagation:rprivate} {Source:/var/lib/docker/containers/c8d3fa4d9e2d50333c89fc0332886551eaaacfd3e14f7043192c4961ded5e80a/hostname Destination:/etc/hostname Writable:true Data: Propagation:rprivate} {Source:/var/lib/docker/containers/c8d3fa4d9e2d50333c89fc0332886551eaaacfd3e14f7043192c4961ded5e80a/hosts Destination:/etc/hosts Writable:true Data: Propagation:rprivate} {Source:/var/lib/docker/containers/c8d3fa4d9e2d50333c89fc0332886551eaaacfd3e14f7043192c4961ded5e80a/shm Destination:/dev/shm Writable:true Data: Propagation:rprivate}] Network:0xc208b1fa10 ProcessConfig:{CommonProcessConfig:{Cmd:{Path: Args:[] Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOSTNAME=c8d3fa4d9e2d TERM=xterm] Dir: Stdin:<nil> Stdout:<nil> Stderr:<nil> ExtraFiles:[] SysProcAttr:0xc20897a770 Process:<nil> ProcessState:<nil> lookPathErr:<nil> finished:false childFiles:[] closeAfterStart:[] closeAfterWait:[] goroutine:[] errch:<nil>} Tty:true Entrypoint:/bin/bash Arguments:[] Terminal:<nil>} Privileged:false User: Console:} ProcessLabel:system_u:system_r:svirt_lxc_net_t:s0:c296,c357 Resources:0xc208c4ab00 Rootfs:/var/lib/docker/devicemapper/mnt/8f94896828bb1b4e3d050072ba9a0393e55682e7816999130ad599abd466bf4a/rootfs WorkingDir: TmpDir:/var/lib/docker/tmp/c8d3fa4d9e2d50333c89fc0332886551eaaacfd3e14f7043192c4961ded5e80a361063268 ContainerJSONPath:/var/lib/docker/containers/c8d3fa4d9e2d50333c89fc0332886551eaaacfd3e14f7043192c4961ded5e80a/config.v2.json} AllowedDevices:[0xc20801e2d0 0xc20801e320 0xc20801e5a0 0xc20801e5f0 0xc20801e640 0xc20801e690 0xc20801e730 0xc20801e780 0x1fc0cc0 0x1fc0d20 0x1fc0d80 0x1fc0de0 0x1fc0e40 0x1fc0ea0] AppArmorProfile: AutoCreatedDevices:[0xc20801e7d0 0x1fc0cc0 0x1fc0d20 0x1fc0d80 0x1fc0de0 0x1fc0e40 0x1fc0ea0] CapAdd:[] CapDrop:[] CgroupParent:system.slice GIDMapping:[] GroupAdd:[] Ipc:0xc208b460a0 OomScoreAdj:0 Pid:0xc20850d5e5 ReadonlyRootfs:false RemappedRoot:0xc20850d610 SeccompProfile: Sysctls:map[] UIDMapping:[] UTS:0xc20850d5e6}"
Jun 30 16:49:24 os-master-0 systemd: Started docker container c8d3fa4d9e2d50333c89fc0332886551eaaacfd3e14f7043192c4961ded5e80a.
Jun 30 16:49:24 os-master-0 systemd: Starting docker container c8d3fa4d9e2d50333c89fc0332886551eaaacfd3e14f7043192c4961ded5e80a.
Jun 30 16:49:24 os-master-0 kernel: SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
Jun 30 16:49:24 os-master-0 systemd: Unit iscsi.service cannot be reloaded because it is inactive.
Jun 30 16:49:24 os-master-0 oci-register-machine[2582]: 2016/06/30 16:49:24 Register machine: prestart c8d3fa4d9e2d50333c89fc0332886551eaaacfd3e14f7043192c4961ded5e80a 2573 /var/lib/docker/devicemapper/mnt/8f94896828bb1b4e3d050072ba9a0393e55682e7816999130ad599abd466bf4a/rootfs
Jun 30 16:49:24 os-master-0 dbus-daemon: dbus[549]: [system] Activating via systemd: service name='org.freedesktop.machine1' unit='dbus-org.freedesktop.machine1.service'
Jun 30 16:49:24 os-master-0 dbus[549]: [system] Activating via systemd: service name='org.freedesktop.machine1' unit='dbus-org.freedesktop.machine1.service'
Jun 30 16:49:24 os-master-0 systemd: Created slice Virtual Machine and Container Slice.
Jun 30 16:49:24 os-master-0 systemd: Starting Virtual Machine and Container Slice.
Jun 30 16:49:24 os-master-0 systemd: Starting Virtual Machine and Container Registration Service...
Jun 30 16:49:24 os-master-0 dbus[549]: [system] Successfully activated service 'org.freedesktop.machine1'
Jun 30 16:49:24 os-master-0 dbus-daemon: dbus[549]: [system] Successfully activated service 'org.freedesktop.machine1'
Jun 30 16:49:24 os-master-0 systemd: Started Virtual Machine and Container Registration Service.
Jun 30 16:49:24 os-master-0 systemd-machined: New machine c8d3fa4d9e2d50333c89fc0332886551.
Jun 30 16:49:24 os-master-0 systemd: Stopping docker container c8d3fa4d9e2d50333c89fc0332886551eaaacfd3e14f7043192c4961ded5e80a.
Jun 30 16:49:24 os-master-0 systemd: Stopped docker container c8d3fa4d9e2d50333c89fc0332886551eaaacfd3e14f7043192c4961ded5e80a.
Jun 30 16:49:24 os-master-0 journal: time="2016-06-30T16:49:24.203733080Z" level=warning msg="exit status 2"
Jun 30 16:49:24 os-master-0 systemd-machined: Machine c8d3fa4d9e2d50333c89fc0332886551 terminated.
Jun 30 16:49:24 os-master-0 kernel: docker0: port 1(vethacd861a) entered disabled state
Jun 30 16:49:24 os-master-0 kernel: device vethacd861a left promiscuous mode
Jun 30 16:49:24 os-master-0 kernel: docker0: port 1(vethacd861a) entered disabled state
Jun 30 16:49:24 os-master-0 NetworkManager[534]: <warn>  (veth1ae1b57): failed to disable userspace IPv6LL address handling
Jun 30 16:49:24 os-master-0 NetworkManager[534]: <info>  (vethacd861a): device state change: activated -> unmanaged (reason 'removed') [100 10 36]
Jun 30 16:49:24 os-master-0 NetworkManager[534]: <warn>  (docker0): failed to detach bridge port vethacd861a
Jun 30 16:49:24 os-master-0 NetworkManager[534]: <warn>  (vethacd861a): failed to disable userspace IPv6LL address handling
Jun 30 16:49:24 os-master-0 nm-dispatcher: Dispatching action 'down' for vethacd861a
Jun 30 16:49:24 os-master-0 kernel: XFS (dm-1): Unmounting Filesystem
Jun 30 16:49:24 os-master-0 journal: time="2016-06-30T16:49:24.315871364Z" level=error msg="error locating sandbox id f734b52aa67d04fbc6b6e7ebd4c1eea213c6e8e56c5c6c0dc74b56a2297a7e07: sandbox f734b52aa67d04fbc6b6e7ebd4c1eea213c6e8e56c5c6c0dc74b56a2297a7e07 not found"
Jun 30 16:49:24 os-master-0 journal: time="2016-06-30T16:49:24.315925373Z" level=warning msg="failed to cleanup ipc mounts:\nfailed to umount /var/lib/docker/containers/c8d3fa4d9e2d50333c89fc0332886551eaaacfd3e14f7043192c4961ded5e80a/shm: invalid argument"
Jun 30 16:49:24 os-master-0 journal: time="2016-06-30T16:49:24.315942163Z" level=error msg="Error unmounting container c8d3fa4d9e2d50333c89fc0332886551eaaacfd3e14f7043192c4961ded5e80a: not mounted"
Jun 30 16:49:24 os-master-0 journal: time="2016-06-30T16:49:24.316042847Z" level=error msg="Handler for POST /v1.22/containers/c8d3fa4d9e2d50333c89fc0332886551eaaacfd3e14f7043192c4961ded5e80a/start returned error: Cannot start container c8d3fa4d9e2d50333c89fc0332886551eaaacfd3e14f7043192c4961ded5e80a: [9] System error: exit status 127"

**Describe the results you expected:**
Container starts  :o)

**Additional information you deem important (e.g. issue happens only occasionally):**
6 VMs were part of the OpenShift Origin installation and all 6 are now showing this issue.

Cheers,

Andre

**Comment by forrestbthomas** [comment]
I ran across a similar issue on RHEL 7 - at least I think it is similar. When I updated to the latest release of docker and docker-common packages (1.10.3-44.el7) for RHEL 7, I could not start any containers. Error messages were identical to the one listed above.

To solve the issue, I had to add a line to the ExecStart section of my docker service unit file
```
--exec-opt native.cgroupdriver=systemd 
```

From my - admittedly very limited - understanding, the cgroupdriver option tells the docker service what to use to allocate resources to containers. The default should be systemd, with the fall back to cgroupfs. If I don't specify anything, what actually happens is that the container mounting fails. If I specify cgroupfs, the container mounting fails. If, however, I specify systemd for the cgroupdriver, the containers will mount and I can start them as normal.

If anyone can explain why the difference between cgroupfs and systemd matters and why the service did not default to systemd (apparently), I would be very grateful.

Cheers.

**Comment by Panidhar** [comment]
we had that line in service file even though we are not able to start the containers ..

Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: rootvg-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 2.821 GB
 Data Space Total: 9.999 GB
 Data Space Available: 7.178 GB
 Metadata Space Used: 1.581 MB
 Metadata Space Total: 37.75 MB
 Metadata Space Available: 36.17 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 3.10.0-327.22.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 4
Total Memory: 15.51 GiB

**Comment by thaJeztah** [comment]
The systemd cgroups have been cause for many issues, depending on the version of systemd installed; some versions of systemd were really broken, and for that reason, the default is cgroupfs.

However, based on the package names (`docker-common`), you're installing the Red Hat fork of Docker, which contains a lot of patches, including changes in this area, and in configuration (systemd unit file); https://github.com/docker/docker/compare/v1.10.3...projectatomic:fedora-1.10.3

Please report these issues in the Red Hat issue tracker https://bugzilla.redhat.com, or try installing the official packages https://docs.docker.com/engine/installation/linux/rhel/

I'm closing this issue, because we can't provide support for these packages, simply because that source code is not in this repository, but feel free to continue the discussion :+1:

**Comment by Panidhar** [comment]
we had that line in service file even though we are not able to start the containers ..

Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: rootvg-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 2.821 GB
 Data Space Total: 9.999 GB
 Data Space Available: 7.178 GB
 Metadata Space Used: 1.581 MB
 Metadata Space Total: 37.75 MB
 Metadata Space Available: 36.17 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 3.10.0-327.22.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 4
Total Memory: 15.51 GiB

**Comment by thaJeztah** [comment]
Also see some info on the choice to use cgroupfs as a default https://github.com/docker/docker/pull/17704 (and issues Linked from that), https://github.com/docker/docker/pull/20633, and https://github.com/docker/docker/pull/20635#issuecomment-188187717

**Comment by andreesser** [comment]
UPDATE:

The CentOS docker was already running with the 'native.cgroupdriver=systemd' option.

After removing CentOS docker packages and installing docker-engine from https://yum.dockerproject.org/repo/main/centos/7 everything is working fine.

Thanks everyone,

Andre

**Comment by thaJeztah** [comment]
Thanks @andreesser, that's good to hear!
