### ISSUE TITLE
Make "TasksMax" setting dependent on systemd version

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#24197]
PR https://github.com/docker/docker/pull/21628 tried to change this setting, dependent on systemd version, but unfortunately added the side-effect that the Docker version reported in `docker info` got the `-unsupported` suffix, because there's uncommitted changes in Git.

For that reason, https://github.com/docker/docker/pull/21628 was reverted in https://github.com/docker/docker/pull/24100, but we need a proper solution, because not setting `TasksMax` will affect a lot of people

/cc @clnperez @tianon

**Comment by HackToday** [comment]
hi  @thaJeztah  is this  https://github.com/moby/moby/pull/24307  for that  TasksMax setting in systemd?

**Comment by thaJeztah** [comment]
@HackToday no it's done in https://github.com/moby/moby/pull/24558 (see https://github.com/moby/moby/blame/32915b1d0a315598edb737785d0357b5a1b8aa11/hack/make/.build-deb/rules#L36-L39)

**Comment by HackToday** [comment]
Hi @thaJeztah  It seems  CentoS 7  not support TasksMax.  How centos 7 do with that ?

Basically, I asked this because of this issue  https://github.com/moby/moby/issues/20096

**Comment by thaJeztah** [comment]
@HackToday As far as I know, this limit is only in place on recent kernels and systemd versions (see https://github.com/moby/moby/pull/19391), so the TaskMax property should not have to be set for older versions (CentOS 7, which uses kernel 3.10 and systemd 219).

**Comment by HackToday** [comment]
Hi @thaJeztah Sorry, still not catch how to solve such issue for CentOS 7

For CentOS 7, if hit issue #20096   Could you tell what's the way to work-around that ?  (If not update kernel and systemd version)

**Comment by thaJeztah** [comment]
What exact issue are you running into? Can you open a separate issue for that? The issue that's being resolved by setting `TaskMax` is to compensate for `systemd` setting a low limit on processes. Older versions of systemd didn't set these limits, so should not be a problem, but possibly the system has low limits configured.

**Comment by thaJeztah** [comment]
For reference, this is the documentation of the `TaskMax` option, which describes what it does (you can also follow that to manually set the same options);

>TasksMax=N
Specify the maximum number of tasks that may be created in the unit. This ensures that the number of tasks accounted for the unit (see above) stays below a specific limit. This either takes an absolute number of tasks or a percentage value that is taken relative to the configured maximum number of tasks on the system. If assigned the special value "infinity", no tasks limit is applied. This controls the "pids.max" control group attribute. For details about this control group attribute, see [pids.txt](https://www.kernel.org/doc/Documentation/cgroup-v1/pids.txt).

> Implies "TasksAccounting=true". The system default for this setting may be controlled with DefaultTasksMax= in [systemd-system.conf(5)](https://www.freedesktop.org/software/systemd/man/systemd-system.conf.html#).
