### ISSUE TITLE
softening the mount syntax

### ISSUE THREAD

**Issue by stevvooe** [docker/docker#24190]
The `--mount` syntax for `docker service` is powerful but complex. We can make a few concessions to simplify usage:

1. Choose default of `volume` for type of mount.
2. Allow value-less keys.
2. Make several aliases for keys (see table below).

### Defaults

The first thing we can do is default the type of a mount to `volume`, eliding the extra type parameter.

Example:

| Old | New |
|-------|-------|
| `--mount type=volume,source=foo,target=/data` | `--mount source=foo,target=/data` |

### Valueless Keys

Allow `type=bind` to be replaced with `bind`, where the presence of the key `bind`, implies `type=bind`.

| Old | New |
|-------|-------|
| `--mount type=bind,source=/mnt/data,target=/data` | `--mount bind,source=/mnt/data,target=/data` |

### Aliases

| Option | Aliases |
|----------|------------|
| `source` | `src`, `name` | `--mount src=/asdf` |
| `target` | `destination`, `dst`, `path` | 

Aliased examples (w/defaults and valueless keys):

| Old | New |
|-------|-------|
| `--mount type=bind,source=/mnt/data,target=/data` | `--mount bind,src=/mnt/data,dst=/data` |
| `--mount type=bind,source=/hostfile,target=/config` | `--mount bind,source=/hostfile,path=/config` |
| `--mount type=volume,source=foo,target=/data` | `--mount name=foo,dst=/data` |

There are probably some other changes we can make, but this will make things slightly better.

cc @dnephin @aanand @aluzzardi @thaJeztah @tiborvass @cpuguy83

**Comment by dnephin** [comment]
I like these suggestions. Defaulting to `type=volume` makes sense.

We already have a valueless key for `writable` (soon to be `readonly`), so having another one for `bind` is fine.

Aliases should do a lot for reducing the verbosity.

**Comment by thaJeztah** [comment]
Not sure about `type=bind` vs `bind`, but definitely see some useful things.

I wonder; is there a reason we use `source` instead of `name` for "named" volumes?

**Comment by aanand** [comment]
Yeah, I guess if we've got separate types for `bind` and `volume`, then we don't need to use the same key for both. We could have:

- `--mount name=foo,dst=data`
- `--mount bind,source=/mnt/data,dst=data`

**Comment by stevvooe** [comment]
@thaJeztah `source` and `target` are from the `mount` syscall, which is the model for the mount API structures. The interpretation of these fields is dependent on type. We can add familiar names that only work in certain contexts, but for the most part it should map to some notion of "left onto right".

**Comment by thaJeztah** [comment]
@stevvooe thanks! I suspected something like that, just didn't like "source" for both "name" or "path". So big 👍 for adding a `name` alias

**Comment by dnephin** [comment]
If we want to accept different aliases for each type we need to require that `bind` is the first argument in the list. That seems like a reasonable requirement to me.

**Comment by cpuguy83** [comment]
Unrecognized key/value pairs could be passed in as `<type>-options`

**Comment by dnephin** [comment]
I'm going to start implementing some of these

**Comment by stevvooe** [comment]
> If we want to accept different aliases for each type we need to require that, if present, bind is the first argument in the list. That seems like a reasonable requirement to me.

No need to do this. Just make aliases.

**Comment by tiborvass** [comment]
@stevvooe would valueless keys have restrictions such as they need to be the first (right after `--mount`) and would always be associated with type? The example you showed could lead to believe it is specific to `bind` only. Just asking for clarifications.

**Comment by stevvooe** [comment]
@tiborvass That was not the intent. These were supposed to be simple, top-level rewrites to the simple grammar.

So, the function would be `convertToMount(rewrite(split(raw)))`. If we want a positional grammar, we should design it as such.

**Comment by mostolog** [comment]
Probably it's more a language problem, but could documentation explain the difference between bind and mount?

**Comment by RotemEmergi** [comment]
There is a way to use the volumes inside of the docker-compose.yml ? I am using command docker-compose bundle and after that I want to deploy the dab file to create a cluster .

**Comment by stevvooe** [comment]
@RotemEmergi This issue has nothing to do with docker compose or DAB. Please open an issue on the docker compose project.

**Comment by thaJeztah** [comment]
ping @stevvooe should this be closed, or do we want to make more improvements for 1.13?

**Comment by tiborvass** [comment]
Closed by #24872

**Comment by frjaraur** [comment]
Using these definitions, how can we create a replicated service with their own volumes?, because source is a must now and can not be the same for all replicas? Or I missed the concept that a replicated service is a service that is the same as parent service (including its volumes).
Maybe adding suffixes for volumes according to service replica suffix?

**Comment by cpuguy83** [comment]
@frjaraur mounts != volumes. You can mount a volume, but swarm is not managing volumes today.

**Comment by frjaraur** [comment]
OK, Thanks, I understand that's why there is a volume type for mounts.

**Comment by stevvooe** [comment]
> Using these definitions, how can we create a replicated service with their own volumes?, 

This is possible today but you have to manage the volumes manually. If you include the options to create the volume as part of the mount, you won't have to create it on all nodes.

> because source is a must now and can not be the same for all replicas?

That really depends on the volume driver you're using and the guarantees required for your service.
