### ISSUE TITLE
[1.12] RFC make Virtual IP's "pingable"

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#24201]
Currently, VIP's are not "pingable", see https://github.com/docker/docker/issues/23855#issuecomment-228905220. This may be "by design", but will confuse a lot of users, and makes debugging more difficult.

Also, all our existing documentation uses `ping` to illustrate how container networks work; none of those examples could be used when working in swarm mode (e.g. https://docs.docker.com/v1.11/engine/userguide/networking/work-with-networks/)

Is there a technical limitation that we don't support this?

**Comment by mavenugo** [comment]
@thaJeztah Ping not working for VIP is as designed. Technically, IPVS is a TCP/UDP load-balancer, while ping uses ICMP and hence IPVS is not going to load-balance the ping request.

I can think of 1 alternative for debuggability. We have an "undocumented" feature (which we can document and make it official), wherein when the user `ping tasks.{service-name}`, the name-resolution actually returns multiple A records of all the backing containers and the ping will succeed to one of the containers. This is true even if the service is backed by a VIP.

I dont think this should be a P1 issue. If someone is really interested in having ping working, then they can always deploy the service with DNS-RR as the endpoint-type and `ping {service-name}` will work.

**Comment by thaJeztah** [comment]
@mavenugo thanks; I mainly added the P1 so that we have a decision on this, and all are on the same page

**Comment by hervenicol** [comment]
Ow, thanks for the `tasks.{service-name}` feature. This DNS feature can be used for simple service-discovery (thinking of it for an ElasticSearch cluster for instance, where nodes need to know of its siblings at init).

However, I'd rather rely on a documented feature, that would seem safer and more stable over releases.

**Comment by cpuguy83** [comment]
Closed by #24573
