### ISSUE TITLE
ikrvugtgndktl

### ISSUE THREAD

**Issue by endophage** [docker/docker#24202]
**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by endophage** [comment]
My laptop literally just output a bunch of random characters... no idea what happened. Ignore.

**Comment by thaJeztah** [comment]
@endophage I know: YubiKey!

**Comment by thaJeztah** [comment]
ccccccevirjdgkgeughgevdbgkvfviuttchriidnuede

^^ because `c` is shortcut for "create new issue" on the issues overview page...

**Comment by endophage** [comment]
ahhh lol, I must have been absentmindedly stroking it

**Comment by thaJeztah** [comment]
happens to me all the time while walking around with my laptop, haha
