### ISSUE TITLE
Fedora 24 was released a while ago, please provide docker-engine repository

### ISSUE THREAD

**Issue by JonasT** [docker/docker#24209]
Fedora 24 was released a while ago, but there is still no respective docker yum repository entry available as you can see here: ```https://yum.dockerproject.org/repo/main/fedora/```

Unless you want to get users stuck without updates after upgrading from 23 to 24, it would be nice if this was fixed in a timely fashion.

**Comment by thaJeztah** [comment]
Official images for Fedora 24 were made available 10 days ago, and a PR was opened and merged after that see https://github.com/docker/docker/issues/23259 and https://github.com/docker/docker/pull/23896

The next release (1.12) will add official support for fedora 24. If you want to install Docker 1.11 on Fedora 24, use the manual installation procedure, and use the Fedora 23 repository; https://docs.docker.com/engine/installation/linux/fedora/
