### ISSUE TITLE
open memory.oom_control: no such file or directory  for docker push

### ISSUE THREAD

**Issue by penhauer-xiao** [docker/docker#24211]
**docker version**  
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:39 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:39 2016
 OS/Arch:      linux/amd64

**when push a images:** 

docker push 992311471111.dkr.ecr.usa-awest-1.amazonaws.com/pjkkk/qa-ccgz:1.2  
The push refers to a repository [992311471111.dkr.ecr.usa-awest-1.amazonaws.com/pjkkk/qa-ccgz]
519d9bbb0316: Layer already exists 
d971804d31b4: Layer already exists 
81f374e09ad1: Layer already exists 
3b50dfb3debe: Layer already exists 
593cb43355e9: Layer already exists 
a5cc9db2e27f: Layer already exists 
737eee27114b: Layer already exists 
9dd3f81fbbc5: Layer already exists 
46e857ff5c9c: Layer already exists 
60c61297c982: Layer already exists 
5f70bf18a086: Layer already exists 
1ef215608c77: Layer already exists 
0cd01e86530e: Layer already exists 
3973e2de72ae: Layer already exists 
724e9db35fe0: Layer already exists 
6650225473f3: Pushing [==========================>                        ] 98.23 MB/188.1 MB
6650225473f3: Preparing 

**It has been stopped waiting, can't upload**

**And the docker daemon log as below:**

$ sudo tail -f /var/log/daemon.log

Jul  1 16:46:57 swarm-node-2 avahi-daemon[681]: Withdrawing workstation service for veth0145ef3.
Jul  1 16:46:58 swarm-node-2 docker[748]: time="2016-07-01T16:46:58+08:00" level=error `msg="containerd: notify OOM events" error="open memory.oom_control: no such file or directory"`
Jul  1 16:46:59 swarmnode-2 avahi-daemon[681]: Joining mDNS multicast group on interface veth9004a65.IPv6 with address fe80::ac64:beff:fe97:6dc4.
Jul  1 16:46:59 swarm-node-2 avahi-daemon[681]: New relevant interface veth9004a65.IPv6 for mDNS.
Jul  1 16:46:59 swarm-node-2 avahi-daemon[681]: Registering new address record for fe80::ac64:beff:fe97:6dc4 on veth9004a65.*.

**Comment by ddeath** [comment]
I got exactly same error.
Docker version : Docker version 1.11.1, build 5604cbe
OS: Debian Jessie 64bit

but it happens when I run
    
    docker-compose up -d nginx

**Comment by imorti** [comment]
This also occurs in 1.12.

**Comment by swan-go** [comment]
Docker company to issue feedback don't care about  this problem appeared as early as version 1.9.

**Comment by thaJeztah** [comment]
This error looks to come from containerd; https://github.com/docker/containerd/blob/0ac3cd1be170d180b2baed755e8f0da547ceb267/supervisor/supervisor.go#L328-L330

@swan-go are you only seeing this for containers that are launched through the Docker Swarm API? Or also when directly working with the Docker API? (I think there was an issue with the Swarm API setting options incorrectly when starting containers)

Also, can you try if this script gives anything that stands out? https://github.com/docker/docker/blob/master/contrib/check-config.sh


ping @mlaventure

**Comment by mlaventure** [comment]
This should be fixed in 1.12. @imorti do you have the relevant docker logs since you seem to see it occurs there? Is this using the latest RC?

This error usually shows up for short lived containers as they die/exit before `containerd` has the time to set up the OOM memory monitor.

**Comment by mlaventure** [comment]
BTW, this error message can be ignored, it should really just be a warning.

The push failure, is not related to this. @swan-go can you provide more logs?

cc @tonistiigi

**Comment by imorti** [comment]
actually I haven't seen this but doesn't mean it's a non-issue.

running Version 1.12.0-rc4-beta20.

-I

**Comment by penhauer-xiao** [comment]
I have been update my docker from 1.11.2 to 1.12.3, This issue is fixed.
