### ISSUE TITLE
Mounting file inside a mounted directory leaves an empty file on the host

### ISSUE THREAD

**Issue by konradkonrad** [docker/docker#24214]
**Output of `docker version`:**

```
Docker version 1.11.2, build b9f10c9
```

**Output of `docker info`:**

```
Containers: 34
 Running: 0
 Paused: 0
 Stopped: 34
Images: 438
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 612
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.13.0-45-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.62 GiB
Name: -redacted-
ID: -redacted-
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical box.

**Steps to reproduce the issue:**
```
/tmp/testenv$ mkdir parent parent/child outside
/tmp/testenv$ date > outside/testfile && cat outside/testfile
Fri Jul  1 12:45:40 CEST 2016
/tmp/testenv$ docker run --rm -v $(pwd)/parent:/inside -v $(pwd)/outside/testfile:/inside/child/testfile ubuntu cat /inside/child/testfile
Fri Jul  1 12:45:40 CEST 2016
/tmp/testenv$ cat parent/child/testfile
/tmp/testenv$ ls -alh parent/child/testfile 
-rwxr-xr-x 1 root root 0 Jul  1 12:45 parent/child/testfile
```

**Describe the results you received:**
In `[host] /tmp/testenv/parent/child` there is now an empty file with the same name as the mounted file.

**Describe the results you expected:**
`[host] /tmp/testenv/parent/child` should still be an empty directory.

**Comment by cpuguy83** [comment]
This is because the file must exist "inside" the container to be able to mount (same with dirs). Since you've mounted a host dir first, the file gets created on the host dir rather than inside the container FS.

I don't think this is something we'll fix.

**Comment by konradkonrad** [comment]
> Since you've mounted a host dir **first**

Are you saying, the order is important here?
First test looks like it is, which is promising:

```
/tmp/testenv$ rm parent/child/testfile 
rm: remove write-protected regular empty file ‘parent/child/testfile’? yes
/tmp/testenv$ docker run --rm -v $(pwd)/outside/testfile:/inside/child/testfile -v $(pwd)/outside/testfile:/inside/child/testfile ubuntu cat /inside/child/testfile
Fri Jul  1 12:45:40 CEST 2016
/tmp/testenv$ cat parent/child/testfile
cat: parent/child/testfile: No such file or directory
```
However, now the contents of `parent` are shadowed away:
```
/tmp/testenv$ echo "I survived the mount" > parent/survivor
/tmp/testenv$ docker run --rm -v $(pwd)/outside/testfile:/inside/child/testfile -v $(pwd)/outside/testfile:/inside/child/testfile ubuntu cat /inside/survivor
cat: /inside/survivor: No such file or directory
```

This is sad -- my use case is reorganizing a source project for a tool inside the container, that expects a strict project structure (different from ours). I was hoping to achieve this via mounts like in my example.

**Comment by cpuguy83** [comment]
@konradkonrad You could create the structure locally first before mounting.
