### ISSUE TITLE
Allow Docker Service Inspect To Return Just Published Ports / Service Url

### ISSUE THREAD

**Issue by AshleyPoole** [docker/docker#24218]
Feature request - Allow published ports to be queries easier when inspecting a service.

Docker Service now stores the published port of a service so joining this with the managers IP, it's possible to no longer need a external service discovery repository.

One issue I've got those is from the terminal is how to return just the published port(s) as a list.

I can successfully filter to just the ports element but cannot access the first element.

`docker service inspect --format='{{.Spec.EndpointSpec.Ports}}' testservice`

Example of what I'm trying to do:
`docker service inspect --format='{{.Spec.EndpointSpec.Ports[0].PublishedPort}}' testservice`

I think adding this would be a big help. Also having another item which combined the managers IP and the published port would be great.

**Comment by dnephin** [comment]
You can do this:

```
docker service inspect -f '{{with index .Spec.EndpointSpec.Ports 0}}{{.PublishedPort}}{{end}}' testservice
```

**Comment by cpuguy83** [comment]
Yep, this is just go template which has some helper functions depending on the type you are looking at.
I don't think there will be any specific changes to do this since the `index` built-in helper should be good.
