### ISSUE TITLE
Docker 1.12 RC3 not in yum experimental repository 

### ISSUE THREAD

**Issue by juliovalcarcel** [docker/docker#24225]
I was trying to get RC3 from the experimental repository on Centos 7 using the script at https://experimental.docker.com/ which installed RC2. To get RC3 I had to use the information at https://experimental.docker.com/builds/. I double checked https://yum.dockerproject.org/repo/experimental/centos/7 and it does not have the RC3 build.

**Comment by thaJeztah** [comment]
RC3 was just released two hours ago, so it should be available now; https://github.com/docker/docker/releases/tag/v1.12.0-rc3
