### ISSUE TITLE
Swarm mode: expose IP for pending nodes

### ISSUE THREAD

**Issue by dhiltgen** [docker/docker#24226]
At present, when a node join is pending, all that is visible is the randomly generated ID. If there are multiple pending nodes, this can make it difficult to know which one is which.  We should expose additional information about the nodes.

**Comment by thaJeztah** [comment]
Ah, yes, I was thinking about that after yesterday's tech talk; even made a note;

>  thought: allow node to set a message when joining (in addition to secret)

Perhaps "engine version" would be interesting to add as well, so that it's possible to "review" the node before accepting

**Comment by thaJeztah** [comment]
Adding to the milestone, but not sure if this makes it for 1.12. We'll move issues to the next milestone if they don't make it

**Comment by dhiltgen** [comment]
The challenge is how much we can trust the information, and trying to avoid a scenario where it can be used to fool an admin into accepting a node they didn't intend to.  The IP address can be somewhat validated by the manager, and I'm assuming implementing this would be fairly straight forward.  With the RC4+ behavior of defaulting to using a secret to join, perhaps this isn't as big a concern, but we should probably make it clear in the API which fields are ~trustworthy and which fields are purely from the remote node and could be easily spoofed.

**Comment by thaJeztah** [comment]
Yes, I agree. The "secret" is still important of course (and needed to be *able* to request to join), additional information is "informational", and purely out of convenience

**Comment by thaJeztah** [comment]
I'm closing this one, because the "pending" status is no longer used, now that we have "join-tokens", but let me know if you think more is needed
