### ISSUE TITLE
Docker Mac (Beta) fails to mount fuse volume from host

### ISSUE THREAD

**Issue by jblomer** [docker/docker#24224]
A mounted fuse volume on the host does not "bind mount" into the container.  Instead, the container shows an empty tmpfs mount point at the destination.

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->

**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   a7119de
 Built:        Fri Jun 17 22:09:20 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 4
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: default
Default Runtime: default
Security Options: seccomp
Kernel Version: 4.4.13-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.954 GiB
Name: moby
ID: YPKB:HNA7:SIJS:6Z5E:67H4:FCYZ:J6EM:3HAQ:5LZM:Z7JF:ZZQM:P26Y
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 30
 System Time: 2016-07-01T08:04:12.850476496Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Mount sshfs on the Mac to, e.g., /my/sshfs
2. `docker run -it --rm -v /my/sshfs:/my/sshfs ubuntu /bin/bash
3. In the container /my/sshfs is there but empty.  It is a tmpfs mount point.

**Describe the results you received:**
Empty /my/sshfs in the container

**Describe the results you expected:**
The contents of /my/sshfs that's available on the host

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by dsheets** [comment]
In Beta 17 and earlier, only `/Users`, `/Volumes`, `/tmp`, and `/private` are available to directly bind mount. All other paths must be prefixed with `/Mac` to be bind mounted. See <https://docs.docker.com/docker-for-mac/osxfs/#/namespaces> for more details.

Taking your report literally, the path `/my/sshfs` will not bind mount as you expect. Your choices, in Beta 17 and earlier, are to either move your path under one of the identity-exported paths or to prefix it with `/Mac`. `/Mac` is deprecated and will be removed before GA.

**Comment by jblomer** [comment]
Many thanks for the pointer!  Indeed, a fuse mount point under `/Users` works. Is there a reason why the list of possible source directories are restricted?  Would it be possible to add a directory in the final version of Docker for Mac, e.g. to make `/cvmfs` bind-mountable in a container?

**Comment by dsheets** [comment]
Yes, I am working today to finish user-configurable directory exports that satisfy exactly that use case. The feature also includes an error message that is returned when a non-system, unexported path is bind mounted in order to prevent the kind of confusion that you initially reported.

Thanks for your report and for using Docker for Mac Beta, without help like your reports, the software would not improve as rapidly. Have a great rest of the weekend!

**Comment by thaJeztah** [comment]
let me close this issue, because I think the question is answered, but feel free to continue the discussion here, thanks @jblomer!
