### ISSUE TITLE
Remove the L3 constraint tip in the getting started Swarm docs

### ISSUE THREAD

**Issue by nerdalert** [docker/docker#24233]
On the [Getting started with swarm mode](https://docs.docker.com/engine/swarm/swarm-tutorial/#/the-ip-address-of-the-manager-machine) page, we just need to remove `Tip: Docker recommends that every node in the cluster be on the same layer 3 (IP) subnet with all traffic permitted between nodes.` towards the bottom of the page since there is no broadcast domain constraint. Ping @thaJeztah 

Thanks!

**Comment by thaJeztah** [comment]
Thanks! Opened https://github.com/docker/docker/pull/24257

**Comment by nerdalert** [comment]
LGTM 👍 Tyvm!
