### ISSUE TITLE
Container command '/hello' not found or does not exist. Getting this error after switching my HDD to SSD

### ISSUE THREAD

**Issue by mandeepm91** [docker/docker#24238]
I searched through the previous issues but I think mine is a bit odd. I am using Ubuntu 14.04 and earlier everything was working fine. I installed an SSD, copied all data from my old HDD to new SSD using `rsync` and then started using the SSD which was a clone of my old hard drive now. Everything is working fine except `docker`. I even tried running the standard `hello-world` image and still getting the error:

```
➜  docker docker run -d hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
c04b14da8d14: Pull complete 
Digest: sha256:0256e8a36e2070f7bf2d0b0763dbabdd67798512411de4cdcf9431a1feb60fd9
Status: Downloaded newer image for hello-world:latest
7572e6372ca1e340f07b267b004ab2d983c9cfbff146655db2317b9ca1542be5
docker: Error response from daemon: Container command '/hello' not found or does not exist..
```

```
➜  docker docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 3
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.13.0-91-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.74 GiB
Name: mandeep-desktop
ID: M4ND:W7WB:FFIZ:BAP4:NDOK:H27M:WPXC:JD4L:S2Q2:GSA3:OO7M:VGIX
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

I read somewhere that it could be due to storage driver. I tried changing the storage drivers in the /etc/default/docker file by modifying the line:

```
# Use DOCKER_OPTS to modify the daemon startup options.
DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4 --storage-driver=devicemapper"
```

And it switched to `devicemapper`. But still getting the same error

**Comment by justincormack** [comment]
Not sure what options you used with `rsync` but maybe you did not copy all the symbolic links correctly? If you do not need your old containers, you can do `rm -rf /var/run/docker` and it should be fine, otherwise you do not want to change the storage driver, but you could try re-syncing `/var/lib/docker` using `rsync -a`.

I am going to close this as it is not an issue with docker but with your machine, but feel free to continue discussing here.
