### ISSUE TITLE
Timestamps in "docker service tasks" missing "ago"

### ISSUE THREAD

**Issue by aaronlehmann** [docker/docker#24252]
```
ID                         NAME          SERVICE     IMAGE    LAST STATE               DESIRED STATE  NODE
8tcg09l72j8pibdfuesvr2yfy  big_darwin.1  big_darwin  restart  Accepted 4 seconds       Accepted       moby
6acxg1fanauvf9qmcdmwzl170  big_darwin.1  big_darwin  restart  Rejected 16 seconds      Shutdown       moby
6rnrnqqj3s4bf4h22tv3wf39d  big_darwin.1  big_darwin  restart  Rejected 28 seconds      Shutdown       moby
4javichei06hvew9jq9al4won  big_darwin.1  big_darwin  restart  Rejected 40 seconds      Shutdown       moby
ece6sk5h5h62xd9ly2red50ul  big_darwin.1  big_darwin  restart  Rejected 52 seconds      Shutdown       moby
7actmfnghjsw5wwodk5gtnaci  big_darwin.1  big_darwin  restart  Rejected About a minute  Shutdown       moby
cqj1rudu1gptc3h7vcqmtntzs  big_darwin.1  big_darwin  restart  Rejected About a minute  Shutdown       moby
awiwaqxsld2uqsrzopicdbp71  big_darwin.1  big_darwin  restart  Rejected About a minute  Shutdown       moby
3idhn6xke1t04e2il5n73vybu  big_darwin.1  big_darwin  restart  Rejected About a minute  Shutdown       moby
```

The timestamps look strange, particularly `Rejected About a minute`.

Contrast `docker ps`, where the format is `Exited (1) 7 minutes ago`.

I think we should add "ago". Ideally this would be formatted as `Rejected about a minute ago`.

(As an aside, why do we intentionally approximate relative times like this? I would **much** rather see "62 seconds ago" when I'm trying to debug something than "About a minute ago").

cc @dnephin

**Comment by thaJeztah** [comment]
if we decide to keep "about", we should fix the capitalization; `About` -> `about`

**Comment by thaJeztah** [comment]
ok, so the "about" is coming from here; and is already used in other locations, so not sure if we should change that; https://github.com/docker/docker/blob/3d13fddd2bc4d679f0eaa68b0be877e5a816ad53/vendor/src/github.com/docker/go-units/duration.go#L12-L33

**Comment by aaronlehmann** [comment]
We could always do something like

```go
if strings.HasPrefix(relative, "About") {
        relative = "about" + strings.TrimPrefix(relative, "About")
}
```

**Comment by thaJeztah** [comment]
I think it's safe to just lowercase the string, let me have a quick look

**Comment by thaJeztah** [comment]
@aaronlehmann something like; https://github.com/docker/docker/pull/24254 ?
