### ISSUE TITLE
dab or dsb in docker stack?

### ISSUE THREAD

**Issue by allencloud** [docker/docker#24265]
Hi, All,

When I use docker-compose 1.8.0-rc1 to create a dab file, actually created a root.dsb file. 
```
root@10-11-17-53:~# docker-compose bundle
...
WARNING: Unsupported key 'network_mode' in services.web - ignoring
WARNING: Unsupported key 'links' in services.web - ignoring
WARNING: Unsupported key 'network_mode' in services.db - ignoring
Wrote bundle to root.dsb
```

While when I use docker stack config root, it showed 
```
root@10-11-17-53:~# docker stack config root
Bundle root.dab not found. Specify the path with -f or --bundle
``` 

Then I hope to make sure: is this a inconsistent bug  **dab or dsb**, or I missed something?

**Comment by vdemeester** [comment]
@allencloud yeah, it has been fixed in current compose master and will be in the next docker-compose RC version. It is `dab`, just compose rc1 has the old extension :angel:

**Comment by allencloud** [comment]
@vdemeester 
Thanks for your reply. Waiting for the rc2 of docker-compose.
Since that, I will close this issue.
