### ISSUE TITLE
Lingering ingress network

### ISSUE THREAD

**Issue by mprivat** [docker/docker#24263]
**Output of `docker version`:**
-bash-4.2$ docker version
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:
 OS/Arch:      linux/amd64
 Experimental: true

**Output of `docker info`:**

-bash-4.2$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 30
Server Version: 1.12.0-rc2
Storage Driver: devicemapper
 Pool Name: docker-8:3-135110698-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.71 GB
 Data Space Total: 107.4 GB
 Data Space Available: 43.59 GB
 Metadata Space Used: 2.544 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: default
Default Runtime: default
Security Options: seccomp
Kernel Version: 3.10.0-327.13.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.703 GiB
Name: agltstdoc01.availity.net
ID: T3YW:I77H:WJQA:ZL3Q:6L65:JTML:UWQW:ZI5F:6LIK:2P7Q:SGH6:WEQN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://proxy.mydomain:8080/
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VMWare Linux servers

**Steps to reproduce the issue:**
1. init swarm
2. join with 1 worker
3. docker create service --replicas=1 -p 2181:2181 --name zookeeper jplock/zookeeper:3.4.8
4. make sure the instance is running on the worker
5. docker service rm
6. redo step 3.

**Describe the results you received:**
-bash-4.2$ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
8c0f0b8b8bd0        bridge              bridge              local
04e37affe2f1        docker_gwbridge     bridge              local
0cc2b3c574a8        host                host                local
e9wuwvcccg75        ingress             overlay             swarm
4upcwp26cuqf        ingress             overlay             swarm
dfd22dae3c6d        none                null                local

**Describe the results you expected:**
Only one ingress network. Also now if I have my instance running on the worker only, I can no longer reach it at manager:2181. I have to hit it at worker:2181 for it to respond.

**Additional information you deem important (e.g. issue happens only occasionally):**
If I dismantle the swarm (i.e. docker swarm leave on the worker, then docker swarm leave --force on the manager), then the ingress network sticks around with no way to get rid of it. That network seems to be tied to a container that doesn't even exist anymore.

Here's some more info:

-bash-4.2$ docker swarm leave
Error response from daemon: You are attempting to leave cluster on a node that is participating as a manager. Leaving last manager will remove all current state of the cluster. Use `--force` to ignore this message.
-bash-4.2$ docker swarm leave --force
Node left the default swarm.
-bash-4.2$ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
8c0f0b8b8bd0        bridge              bridge              local
04e37affe2f1        docker_gwbridge     bridge              local
0cc2b3c574a8        host                host                local
4upcwp26cuqf        ingress             overlay             swarm
dfd22dae3c6d        none                null                local
-bash-4.2$ docker network inspect 4upcwp26cuqf
[
    {
        "Name": "ingress",
        "Id": "4upcwp26cuqf94knjlmq5i8n8",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.255.0.0/16",
                    "Gateway": "10.255.0.1"
                }
            ]
        },
        "Internal": false,
        "Containers": {
            "ep-282d458443d6cb308120ad5380a370d069c1bbc67d988d3f88149ab53f10b44f": {
                "Name": "zookeeper.1.1yrnlpzwsmu2jco7jb8alxy8c",
                "EndpointID": "282d458443d6cb308120ad5380a370d069c1bbc67d988d3f88149ab53f10b44f",
                "MacAddress": "02:42:0a:ff:00:06",
                "IPv4Address": "10.255.0.6/16",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "256"
        },
        "Labels": {}
    }
]
-bash-4.2$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
-bash-4.2$ docker network rm 4upcwp26cuqf
Error response from daemon: ingress is a pre-defined network and cannot be removed

**Comment by thaJeztah** [comment]
ping @mrjana PTAL

**Comment by mavenugo** [comment]
@mprivat can you please try the RC3 (which brought in a bunch of fixes) and provide feedback ?

**Comment by mprivat** [comment]
We installed RC3 a couple of days ago. We haven't seen the problem since.

**Comment by thaJeztah** [comment]
Thanks for testing @mprivat! I'll go ahead and close this issue, but let us know if you encounter this again, then we can reopen
