### ISSUE TITLE
A container with an IPv6 address occupies that address forever, therefore the container can't even be restarted.

### ISSUE THREAD

**Issue by moqmar** [docker/docker#24269]
**Output of `docker version`:**
```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**
```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 4
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.0-28-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 488.7 MiB
Name: ubuntu-512mb-sgp1-01
ID: W53K:JCFL:EWMB:57IO:P6VW:ZENX:5OBL:FJ7O:WTMX:GRPY:OODV:X4E5
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Not related to the issue; happens on DigitalOcean just as locally and on my physical server. So, it was also tested with kernel `3.16.0-4-amd64` and Debian 8 - a completely different system than the one the `docker info` command is coming from - and the issue still persists.

**Steps to reproduce the issue:**
1. Create an IPv6 docker network: `docker network create --ipv6 --subnet fe80:d000::/32 testnetwork`
2. Run a container: `docker run --net testnetwork --ip6 fe80:d000::10 --name testcontainer hello-world`
3. Stop the container - hello-world does this by itself.
4. Start the container again: `docker start testcontainer`

**Describe the results you received:**
The container won't start because its IPv6 address is already in use, or at least Docker thinks it is.

    Error response from daemon: Address already in use
    Error: failed to start containers: testcontainer

**Describe the results you expected:**
The container starts on the same IPv6 address as I chose when running it.

**Additional information you deem important (e.g. issue happens only occasionally):**
This *only* happens if the container has an IPv6 address. Not with IPv4, and I assume the reason it *seems* to work without an IP specified in the run command is because it just gets another one the next time it's getting started - in fact, any IPv6 a container once had (also if you don't specify one) can not be used again (even for the same container) until the whole network is recreated. The IP cannot be used by any docker container from that point until the network is recreated - not even restarting the docker container or even rebooting the system fixes the issue.

Update: it seems like also the IPv4 address is blocked, but this seems to be only the case if an `--ip6` is specified: after creating a container with `docker run --net testnetwork --ip6 fe80:d000::10 --ip 10.0.0.100 --name testcontainer hello-world`, the IP `10.0.0.100` is blocked for new containers even after this container is removed. When the same container is created without the `--ip6` option, the IPv4 can still be used after the container is removed.
**This looks like a pretty major bug for everyone who is using advanced container networking (or even just needs static IP containers) in combination with IPv6!**

**Comment by aboch** [comment]
Known issue when user tries to reserve link-local addresses.
Reference https://github.com/docker/libnetwork/issues/988

**Comment by thaJeztah** [comment]
@aboch is this being looked into?

**Comment by justincormack** [comment]
There is specific link local address support in 1.12 I think, to address
this.

**Comment by aboch** [comment]
@moqmar @thaJeztah The issue is there only for link-local IPv6 addresses, not any IPv6 address.
Before moving forward, I would like to understand the use-case of using IPAM for link-local addresses.

By the nature of link-local addresses, we do not think they should be managed by the IPAM driver, and, as @justincormack pointed out, in docker 1.12 user will be able to specify a (IPv4 or IPv6) link-local address for the container's interface, without IPAM driver knowing about it (`--link-local-ip`).

Also, please note today user already has control over the default link-local IPv6 address assigned to the container's interface, by controlling the container's mac-address via the docker run option `--mac-address`.

**Comment by mavenugo** [comment]
@moqmar can you pls confirm @aboch's suggestion above and does that satisfy your requirement ?

**Comment by moqmar** [comment]
Sorry, totally forgot about this issue - yep, `--link-local-ip` is pretty much exactly what I needed.
