### ISSUE TITLE
[FEATURE] Docker for Windows and Mac: Linux GUI applications?

### ISSUE THREAD

**Issue by NLKNguyen** [docker/docker#24278]
Hello awesome team,

I just watched the keynote on day 1 of DockerCon 2016, and it blew my mind, especially Docker for Windows and Mac. I guess this question was probably asked because of its obviousness, but I couldn't find it, so here it is: 

> What is the state of the art of running Linux's GUI applications through Docker for Mac and Windows?

There is an old blog post about [Running GUI apps with Docker](http://fabiorehm.com/blog/2014/09/11/running-gui-apps-with-docker/) on Ubuntu, but now the playground is much higher with the introduction of Docker for Mac and Windows. So, you guys/gals will be bringing GUI app support for Docker right? right? :pray: 

Imagine deploying a desktop app on a Docker-ready machine simply by sending a shortcut to automatically pull the image and just start running... ahhhhhhh

**Comment by PHLF** [comment]
It is already possible: fire up a X server on OSX/Windows (XQuartz, CygwinX or XMing) and connect your containers to it through TCP or Unix socket sharing. It's a little bit tricky though (I have some issues with it at the moment). 

See this thread:

https://github.com/docker/docker/issues/8710

;)

**Comment by thaJeztah** [comment]
Could you post this feature request in the Docker for Mac feedback forum? https://forums.docker.com/c/docker-for-mac

Docker for Mac / Windows is a separate project and team, so there's not much we can do in this repository; I'll close this issue but feel free to comment after I closed
