### ISSUE TITLE
Documentation: Potentially invalid tag naming specification

### ISSUE THREAD

**Issue by josegonzalez** [docker/docker#24289]
As of https://github.com/docker/docker/commit/4fa0eccd10c5c120fe1f641285db920cf643dbe8, it seems like the specification officially dropped periods and dashes in tag names, but continued to reference tags within the spec as capable of containing periods. 

Is the regex contained in the documentation - `[a-zA-Z_0-9]` - incorrect, or are images indeed no longer allowed to contain characters not in that characterset? Just want to clarify as I am updating some dokku docs and don't want to push people into invalid formats.

**Comment by aaronlehmann** [comment]
The ultimate source of truth for reference parsing is the `distribution/reference` package (https://github.com/docker/distribution/blob/master/reference/regexp.go).

In this case, `TagRegexp` is `[\w][\w.-]{0,127}`.

So you're right - this was documented incorrectly. I'll open a PR to correct it.

**Comment by josegonzalez** [comment]
💥 thanks!

**Comment by thaJeztah** [comment]
Thanks for reporting @josegonzalez, nice catch!
