### ISSUE TITLE
Connection with dockerhub registry hangs

### ISSUE THREAD

**Issue by jas99** [docker/docker#24292]
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 12
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 14
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-28-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.662 GiB
Name: ubuntu-workstation
ID: CAOP:PNZF:2ALM:PYSQ:2KSO:Y7O4:2KYM:CL6B:GDLX:QJK2:R3AZ:EQNX
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I have two internet connections
DSL vendor : Airtel (Have no issues) on all platforms windows, ubuntu and mac 
Fiber vendor : BSNL (my dynamically assigned  ip now is 210.16.109.23) causes issue only on ubuntu 16.04 (also tried live version; same issue)

1. Using fresh ubuntu 16.04
2. Connected with specific internet vendor BSNL(assigned me dynamic ip this time 210.16.109.23 and confirmed issued again). I am adding my ip if this issue is something related to CDN. Every thing works with other dsl vendor.
3. **Can't do docker pull on only dockerhub images; hangs indefinitely without error** 
4. **Can't login at hub.docker.com; hangs indefinitely and keeps showing logging in ** - Chrome inspect shows 502 gateway error 

Thx and let me know if you wanna know something else as problem is pretty tricky.

**Comment by justincormack** [comment]
This might be an issue with the MTU, can you try running the docker daemon with `--mtu=1450` and see if that helps?

**Comment by thaJeztah** [comment]
Ping @jas99

**Comment by jas99** [comment]
@justincormack @thaJeztah 
Hi guys
Sorry for late reply

From yesterday it seems to be healed(both pulling and login to dockerhub are working) and I wasn't able to test at 1450 mtu thus.

I am gonna close this issue for now; if you guys have follow up question be my guest :smile: 

Thx

**Comment by thaJeztah** [comment]
Thank you @jas99 !
