### ISSUE TITLE
unable to distribute load to worker nodes in docker swarm mode

### ISSUE THREAD

**Issue by ashishjain14** [docker/docker#24305]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      linux/amd64
 Experimental: true

```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 14
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 16
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge host null
Swarm: active
 NodeID: 3mu5p5d52oyl6gxxztob97644
 IsManager: Yes
 Managers: 1
 Nodes: 3
 CACertHash: sha256:914e07a167ddf57962b1840ba82eb4fea97efd29f5c5a6c383f806f0cee0bedd
Runtimes: default
Default Runtime: default
Security Options: seccomp
Kernel Version: 4.4.13-boot2docker
Operating System: Boot2Docker 1.12.0-rc2 (TCL 7.1); HEAD : 52952ef - Fri Jun 17 21:01:09 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: smaster
ID: ENTU:KMPY:3P3D:HH7D:PW2B:IFZ7:MLBS:B73R:Z7U5:ZXPK:R5DF:DU6N
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 48
 Goroutines: 138
 System Time: 2016-07-04T11:27:07.409851167Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I am using VirtualBox

**Steps to reproduce the issue:**
1. Use docker-machine to setup 3 nodes - 1 master & 2 worker nodes on a local system using virtual box
2. Set up a swarm cluster using the docker engine swarm mode
3. Create a overlay network mynet
4. Deploy a service using the following command
docker service create --name test_httpd --network mynet --replicas 3 httpd

**Describe the results you received:**
I see that the only 1 instance of the service is created on the master host and on the worker node docker engine keeps retrying, resulting in the following

docker service tasks test_httpd --all
ID                         NAME          SERVICE     IMAGE  LAST STATE               DESIRED STATE  NODE
5mzbmhay31kyemgs2dg9xvk2p  test_httpd.1  test_httpd  httpd  Running 10 minutes       Running        smaster
23ju5lkkwqzqiajj4hdlvx7ez  test_httpd.2  test_httpd  httpd  Preparing 10 seconds     Running        sworker2
2eetgkds2158af39pi3xzu5px  test_httpd.2  test_httpd  httpd  Rejected About a minute  Shutdown       sworker1
3glf2uhjd3rtz9uqm1mp0ysry  test_httpd.2  test_httpd  httpd  Rejected About a minute  Shutdown       sworker2
3uorlch3oktfyh7nwn1umc9hz  test_httpd.2  test_httpd  httpd  Rejected 2 minutes       Shutdown       sworker2
anh04t2jlmseeimu1giocseyg  test_httpd.2  test_httpd  httpd  Rejected 3 minutes       Shutdown       sworker2
6ahnl17ekfdugy7p4upkxw8u6  test_httpd.2  test_httpd  httpd  Rejected 4 minutes       Shutdown       sworker2
8zxy85f39t56cqnbd5xrailkn  test_httpd.2  test_httpd  httpd  Rejected 5 minutes       Shutdown       sworker1
73nf7vjy8jr83cbxdhusjkf05  test_httpd.2  test_httpd  httpd  Rejected 6 minutes       Shutdown       sworker1
2vmsdljvkwk5udadtymntxi07  test_httpd.2  test_httpd  httpd  Rejected 6 minutes       Shutdown       sworker1
2lwpudtz4j39wlc8mtynlil2h  test_httpd.2  test_httpd  httpd  Rejected 7 minutes       Shutdown       sworker1
10rib21g1an72zy907a0nnciq  test_httpd.3  test_httpd  httpd  Preparing 10 seconds     Running        sworker1
8h0a009uhm2kodsz8qy4bz4e2  test_httpd.3  test_httpd  httpd  Rejected About a minute  Shutdown       sworker2
bbfrvh5rc8qoaujlnyljhcoj2  test_httpd.3  test_httpd  httpd  Rejected About a minute  Shutdown       sworker1
7j7ab9kigpcqh9xcpoqwfu9ws  test_httpd.3  test_httpd  httpd  Rejected 2 minutes       Shutdown       sworker1
9d7mqos759z3pb2hlyudkdfr7  test_httpd.3  test_httpd  httpd  Rejected 3 minutes       Shutdown       sworker1
2yeygww3fv7x5nhmae3ip8iht  test_httpd.3  test_httpd  httpd  Rejected 4 minutes       Shutdown       sworker1
d2zabtwcynqbqxxzmehfa6phg  test_httpd.3  test_httpd  httpd  Rejected 5 minutes       Shutdown       sworker2
9x2jtspody3bkdpd2gdvutbkm  test_httpd.3  test_httpd  httpd  Rejected 6 minutes       Shutdown       sworker2
0w5siz4f9jxj6bk1kf57t86gw  test_httpd.3  test_httpd  httpd  Rejected 6 minutes       Shutdown       sworker2
85swptv905gvol2epwain0v8n  test_httpd.3  test_httpd  httpd  Rejected 7 minutes       Shutdown       sworker2

**Describe the results you expected:**
I expected that the service will be run successfully with 3 replicas but only one of them is running.

**Status of swarm and docker-machine nodes**
docker node ls
ID                           NAME      MEMBERSHIP  STATUS  AVAILABILITY  MANAGER STATUS
3mu5p5d52oyl6gxxztob97644 *  smaster   Accepted    Ready   Active        Leader
73yzwqcw425lqgcvys698ndv1    sworker2  Accepted    Ready   Active        
8zp4diofp9sk44k2i7dze94r8    sworker1  Accepted    Ready   Active        

docker-machine ls
NAME             ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
smaster          -        virtualbox   Running   tcp://192.168.99.100:2376           v1.12.0-rc2   
sworker1         -        virtualbox   Running   tcp://192.168.99.101:2376           v1.12.0-rc2   
sworker2         -        virtualbox   Running   tcp://192.168.99.102:2376           v1.12.0-rc2

**Comment by ashishjain14** [comment]
Looks like this is working now, I am suspecting it was the image transfer from one node to another what took time. This is the final output, looks like it took 3 hours for all the services to come in ready state.

docker service tasks test_httpd --all
ID                         NAME          SERVICE     IMAGE  LAST STATE        DESIRED STATE  NODE
5mzbmhay31kyemgs2dg9xvk2p  test_httpd.1  test_httpd  httpd  Running 9 hours   Running        smaster
0k1jgibh4cnqeu4g2c6zk7c01  test_httpd.2  test_httpd  httpd  Running 6 hours   Running        sworker1
5fk9j4zh4846pg3i9wpfx8tnp  test_httpd.2  test_httpd  httpd  Rejected 6 hours  Shutdown       sworker1
55q0l61j2qrqxjf7lmf6pb8j0  test_httpd.2  test_httpd  httpd  Rejected 6 hours  Shutdown       sworker1
4qng4k850s9t04qn2tl9ghvxt  test_httpd.2  test_httpd  httpd  Rejected 6 hours  Shutdown       sworker1
c34jr0ljieuzkdfrt7kayqseg  test_httpd.2  test_httpd  httpd  Rejected 6 hours  Shutdown       sworker1
4k3tx4n28b7rn3ybcefcjwuzs  test_httpd.2  test_httpd  httpd  Rejected 6 hours  Shutdown       sworker1
1lx2re69x0tevukp4gvpa2s1r  test_httpd.2  test_httpd  httpd  Rejected 6 hours  Shutdown       sworker1
awi62g4o8rmadzy6e2jvxm9ns  test_httpd.2  test_httpd  httpd  Rejected 6 hours  Shutdown       sworker1
alleo81f1rbpgs4mryvbmmg2z  test_httpd.2  test_httpd  httpd  Rejected 6 hours  Shutdown       sworker1
3t0v05nosnd2lpxnpw3dejnx9  test_httpd.2  test_httpd  httpd  Rejected 6 hours  Shutdown       sworker1
6weecwm185v052da7he1z80t2  test_httpd.3  test_httpd  httpd  Running 6 hours   Running        sworker2
bb7y00l7j3cwp2nwdtjxqhi82  test_httpd.3  test_httpd  httpd  Rejected 6 hours  Shutdown       sworker2
05fplh07xm7vvx963h383guga  test_httpd.3  test_httpd  httpd  Rejected 6 hours  Shutdown       sworker2
alotzufnkucqxuyfcvj9hh89e  test_httpd.3  test_httpd  httpd  Rejected 6 hours  Shutdown       sworker2
51yd2ssw9adp21sc0g8nc285g  test_httpd.3  test_httpd  httpd  Rejected 6 hours  Shutdown       sworker2
8i6vv0lzie1swcv0dwdjpn8wm  test_httpd.3  test_httpd  httpd  Rejected 6 hours  Shutdown       sworker2
anmgkbuy5qtbmhn4fzndj4hod  test_httpd.3  test_httpd  httpd  Rejected 6 hours  Shutdown       sworker2
ehq45hxq8zh56p1983udjp1af  test_httpd.3  test_httpd  httpd  Rejected 6 hours  Shutdown       sworker2
1i5gb4g54yhaz4jyktoa0dusc  test_httpd.3  test_httpd  httpd  Rejected 6 hours  Shutdown       sworker2
247j1wghboqoiiwraiug20zqx  test_httpd.3  test_httpd  httpd  Rejected 6 hours  Shutdown       sworker2

But subsequent run of docker service create with replicas  was finished in seconds and all came up simultaneously. This points to probably image download time.

**Comment by cpuguy83** [comment]
@ashishjain14 it looks like this is a non-issue then. I'll close but feel free to comment.
