### ISSUE TITLE
Labels reconfiguration failed for daemon if specified in the command line and daemon.json

### ISSUE THREAD

**Issue by malain** [docker/docker#24306]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   91e29e8
 Built:        Sat Jul  2 00:17:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   91e29e8
 Built:        Sat Jul  2 00:17:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.0-rc3
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge host null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.14-boot2docker
Operating System: Boot2Docker 1.12.0-rc3 (TCL 7.1); HEAD : 8d9ee9f - Sat Jul  2 05:02:44 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: test
ID: HU6Z:T5PF:ZCA6:LCTC:64C6:DCXZ:PZIK:MKWX:2ICG:ERIT:CX2W:CEH2
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 13
 Goroutines: 24
 System Time: 2016-07-04T12:42:44.157142413Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker for Mac Version 1.12.0-rc2-beta17 (build: 9779)

**Steps to reproduce the issue:**
1. Create a new machine with docker-machine -d virtual box test
2. Edit /etc/docker/daemon.json on the machine and add {"labels":["mylabel=1"]}
3. Restart daemon with SIGHUP

**Describe the results you received:**

Labels from daemon.json are ignored.
Docker log contains the following message:
```
time="2016-07-04T12:31:43.356902144Z" level=info msg="Got signal to reload configuration, reloading from: /etc/docker/daemon.json"
time="2016-07-04T12:31:43.357524115Z" level=error msg="the following directives are specified both as a flag and in the configuration file: labels: (from flag: [provider=virtualbox], from file: [mylabel=1])"
```

ps aux | grep docker
```
root      2653  0.0  3.8 382520 39172 ?        Sl   12:30   0:00 dockerd -D -g /var/lib/docker -H unix:// -H tcp://0.0.0.0:2376 --label provider=virtualbox --tlsverify --tlscacert=/var/lib/boot2docker/ca.pem --tlscert=/var/lib/boot2docker/server.pem --tlskey=/var/lib/boot2docker/server-key.pem -s aufs
...
```
No ```labels``` flag is specified in the command line only ```label``` but the message is still generated.

**Describe the results you expected:**
Labels must be merged. In case of conflict, labels from config file must be prioritized.

**Comment by vdemeester** [comment]
From documentation:

> The options set in the configuration file must not conflict with options set via flags. The docker daemon fails to start if an option is duplicated between the file and the flags, regardless their value. We do this to avoid silently ignore changes introduced in configuration reloads. For example, the daemon fails to start if you set daemon labels in the configuration file and also set daemon labels via the --label flag. Options that are not present in the file are ignored when the daemon starts.

I think the solution would be that `docker-machine` provision what can be provisionned using the config file (for labels for example).

**Comment by justincormack** [comment]
As this is explicitly documented as being the expected behaviour I am going to close the issue, but feel free to open an issue on docker/machine as @vdemeester suggested.
