### ISSUE TITLE
docker inspect on image should include exposed ports

### ISSUE THREAD

**Issue by silkentrance** [docker/docker#24313]
Feature Request

While ``docker inspect $IMAGE_ID`` does include information on volumes, commands and entry points, it misses required information on exposed network ports. Having that information would make it easier to solve problems such as https://github.com/docker/docker/issues/4635#issuecomment-230319557.

**Output of `docker info`:**
```
Docker version 1.11.2, build b9f10c9
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
n/a

**Steps to reproduce the issue:**
1. docker pull coldrye/debian-jetty:1-9-3-jessie-latest
2. docker inspect coldrye/debian-jetty:1-9-3-jessie-latest

**Describe the results you received:**
JSON report is missing information on exposed ports.

**Describe the results you expected:**
Exposed ports, here 8080/tcp, should be included in the json report.

E.g.

```
...
Networking: {
   "Exposes": [ "8080/tcp" ]
}
```

**Additional information you deem important (e.g. issue happens only occasionally):**
n/a

**Comment by vdemeester** [comment]
@silkentrance I'm not sure I see the problem, `docker inspect` one image expose port that have been declare as exposed (with `EXPOSE` in a `Dockerfile`). For example: 

```bash
λ docker inspect -f "{{json .Config.ExposedPorts}}" traefik
{"80/tcp":{}}
λ docker inspect traefik
# […]
        "Config": {
            "Hostname": "72b805bafe98",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "80/tcp": {}
# […]
```

The `coldrye/debian-jetty` does not declare exposed port it seems (looking at the `Dockerfile`s present on the github repository. If *exposed ports* have not been declared as is when building the image, then Docker can't guess what port the process will expose and thus won't show a thing.

**Comment by silkentrance** [comment]
@vdeneester ups, i will check that right away. thanks for the info!

**Comment by silkentrance** [comment]
@vdemeester yes you are right, the old version of the dockerfile did not include that information. And with the newest dockerfile which does include that information, everything works as expected!

Thank you for pointing this out, must have run the inspect command against an older version of the image.

**Comment by silkentrance** [comment]
Closing this right away.

**Comment by vdemeester** [comment]
:wink: :+1:
