### ISSUE TITLE
Current RC very low IO Speed?

### ISSUE THREAD

**Issue by SantoDE** [docker/docker#24316]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Output of `docker version**
```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   a7119de
 Built:        Wed Jun 29 10:03:33 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 13
 Running: 4
 Paused: 0
 Stopped: 9
Images: 109
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 264
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay bridge null
Swarm: inactive
Runtimes: default
Default Runtime: default
Security Options: seccomp
Kernel Version: 4.4.14-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.857 GiB
Name: moby
ID: RBC3:IAED:2KRP:NCYH:DT7L:JQGJ:UCFS:IJTR:NY3V:DSJR:JGI4:3KAX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 66
 Goroutines: 118
 System Time: 2016-07-04T22:06:46.037424547Z
 EventsListeners: 10
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Regi
```

Local MacBook Pro

**Steps to reproduce the issue:**
1. Run container with an intensive IO Operation (in my case Magento 2 setup:di:compile

**Describe the results you received:**
Very LO IO Speed 

**Describe the results you expected:**
Okay-Ish speed for the IO Operation

I'm encountering a weird io speed permission on my mac. I've a directory (with subdirs) mounted from the host to my container. If I run a magento2 task over that directory, it's super slow (see attached IO Stat Screenshot).

<img width="556" alt="bildschirmfoto 2016-07-04 um 23 17 57" src="https://cloud.githubusercontent.com/assets/1031255/16570423/dc7c1000-4244-11e6-9479-6316131eb188.png">

If I instead at this directory to the image by adding it trough the dockerfile and executing the command afterwards, everything runs around 15x faster. The task then takes 5 mins while when the directory is mounted it's arround 1hour 15m+.

Did anyone encounter that weird behavior before?

Cheers,
SantoDE

**Comment by justincormack** [comment]
Hi, there are known performance issues with docker for mac beta on some types of workloads involving volumes shared from the host. We are working on improving these. If you have a real world benchmark rather than a synthetic one like iostat that might be useful for our internal benchmarking.

**Comment by SantoDE** [comment]
Hey there,

What would be a real World benchmark? Im happy to help and Provide it :)
Am 05.07.2016 7:51 vorm. schrieb "Justin Cormack" <notifications@github.com

**Comment by SantoDE** [comment]
Not sure if double post is allowed or not. Sorry if it's not.

I finally got it working. Following are my results. First one is in the mounted volume, second is just inside the container.

root@1db8736ac64a:/var/www/html# dd if=/dev/zero of=test.dat bs=1024 count=100000
100000+0 records in
100000+0 records out
102400000 bytes (102 MB) copied, 54.424 s, 1.9 MB/s

root@1db8736ac64a:/var/www/html# dd if=/dev/zero of=/test.dat bs=1024 count=100000
100000+0 records in
100000+0 records out
102400000 bytes (102 MB) copied, 0.413944 s, 247 MB/s

**Comment by justincormack** [comment]
We already have benchmarks with `dd`, I meant something that is an actual day to day use case, like the magento task you mentioned.

**Comment by SantoDE** [comment]
Ah, sorry! Here's my task I want to archive:

After redeploying my container I need to run setup:compile:di (http://devdocs.magento.com/guides/v2.1/config-guide/cli/config-cli-subcommands-compiler.html) after start up which is so extremly slow and takes an hour+ on my local environment with the beta.

**Comment by justincormack** [comment]
Have you got a repeatable way to do that, eg a container that can be run to do a comparable run of that?

**Comment by SantoDE** [comment]
Yeah, I could give you temporary access to my registry where you could pull
the image. However, as the source code is mounted from the host you'd ne a
base magento 2 source code installation as well. Is that a problem? Because
an Image with build in source wouldn't help I guess?

2016-07-05 11:20 GMT+02:00 Justin Cormack <notifications@github.com>:

> Have you got a repeatable way to do that, eg a container that can be run
> to do a comparable run of that?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/docker/docker/issues/24316#issuecomment-230428396>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA-8V-4S-qRaSurM5qeCNaKcD5GVchzJks5qSiHpgaJpZM4JEq6F>
> .
>



-- 
Manuel Laufenberg

http://www.manuel-laufenberg.de

**Comment by justincormack** [comment]
Yes, it really needs to be something public on github so we can test on an ongoing basis, we don't really want access to your private code. We can continue to use synthetic tests for now for performance benchmarking.

**Comment by SantoDE** [comment]
Here are some more "real time" benchmarks:

hosted files:

`magento@54aa5a86e0e3:~$ time magento setup:di:compile
Compilation was started.
Application code generator... 3/7 [============>---------------]  42% 16 mins 134.0 MiB34.0 MiB


Interceptors generation... 4/7 [================>-----------]  57% 43 mins 150.0 MiBMiB


Interception cache generation... 7/7 [============================] 100% 2 hrs 240.0 MiB
Generated code and dependency injection configuration successfully.

real	107m52.170s
user	2m11.980s
sys	9m11.830s`

inside container:

`real	3m31.321s
user	0m43.160s
sys	2m48.050s`

I can try to example a simple example which I could put on github. The Magento Example might be a bit oversized? @justincormack

**Comment by piotrekkaminski** [comment]
It's a major issue experienced by many users. Magento has many files, uses many "if exists" and stat calls on them. It might be a good test case but hard to strip down to smaller set.

**Comment by justincormack** [comment]
This issue is being tracked in multiple places - can you move the comments to https://github.com/docker/for-mac/issues/77 as you will get better support there.

@SantoDE we don't mind how big the examples are!

I am going to close this in favour of the other issue to avoid duplication as it is specific to docker for Mac.
