### ISSUE TITLE
Unable to delete images in docker private trusted registry

### ISSUE THREAD

**Issue by nanab4u** [docker/docker#24327]
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 11
 Running: 9
 Paused: 0
 Stopped: 2
Images: 27
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 194
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 4.2.0-38-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 7.797 GiB
Name: docker-app
ID: OOAV:S2TL:RIPW:2N64:TZV3:RINM:BRL5:5SOO:SHN6:7M7O:BB7D:UPKD
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):** Physical

**Steps to reproduce the issue:**
1.curl -k -u 'username:password' -I -H Accept:\* https://localhost:5000/v2/test/apache/manifests/7
2.curl -k -v -u 'username:password' -X DELETE https://myregistrydomain.com:5000/v2/test/apache/manifests/sha256:a8c440e6d892575de35e179bc7b09f23b9a117d4b967eb469d66c5320edc2ee5

**Describe the results you received:**
**Output 1**: HTTP/1.1 200 OK
Content-Length: 10465
Content-Type: application/vnd.docker.distribution.manifest.v1+prettyjws
Docker-Content-Digest: sha256:a8c440e6d892575de35e179bc7b09f23b9a117d4b967eb469d66c5320edc2ee5
Docker-Distribution-Api-Version: registry/2.0
Etag: "sha256:a8c440e6d892575de35e179bc7b09f23b9a117d4b967eb469d66c5320edc2ee5"
X-Content-Type-Options: nosniff
Date: Tue, 05 Jul 2016 11:28:45 GMT

**Output2**: * Hostname was NOT found in DNS cache
*   Trying 192.168.1.142...
* Connected to myregistrydomain.com (192.168.1.142) port 5000 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
*        subject: C=AU; ST=Some-State; O=Internet Widgits Pty Ltd; CN=myregistrydomain.com
*        start date: 2016-06-10 12:07:22 GMT
*        expire date: 2043-10-27 12:07:22 GMT
*        issuer: C=AU; ST=Some-State; O=Internet Widgits Pty Ltd; CN=myregistrydomain.com
*        SSL certificate verify result: self signed certificate (18), continuing anyway.
* Server auth using Basic with user 'username'
> DELETE /v2/test/apache/manifests/sha256:a8c440e6d892575de35e179bc7b09f23b9a117d4b967eb469d66c5320edc2ee5 HTTP/1.1
> Authorization: Basic dGVzdHVzZXI6N3kzZHN5bXBob255MTIz
> User-Agent: curl/7.35.0
> Host: myregistrydomain.com:5000
> Accept: */*
>
< HTTP/1.1 405 Method Not Allowed
< Content-Type: application/json; charset=utf-8
< Docker-Distribution-Api-Version: registry/2.0
< X-Content-Type-Options: nosniff
< Date: Tue, 05 Jul 2016 11:30:25 GMT
< Content-Length: 78
<
{"errors":[{"code":"UNSUPPORTED","message":"The operation is unsupported."}]}
* Connection #0 to host myregistrydomain.com left intact

**Describe the results you expected:**

Unable to delete images in private docker trusted registry.

**Additional information you deem important (e.g. issue happens only occasionally):**

I'm using "registry github.com/docker/distribution v2.4.1" and Docker-Distribution-Api-Version: registry/2.0

**Comment by thaJeztah** [comment]
if this is an issue with DTR (Docker Trusted Registry), please report through support@docker.com. For issue with the open source registry, use this issue tracker; https://github.com/docker/distribution/issues

I'm closing this issue because of the above, but feel free to comment after I closed

**Comment by nanab4u** [comment]
Okay.I have opened an issue in open source registry issue tracker. Thanks much.
