### ISSUE TITLE
DOCKER_OPTS from /etc/default/docker not loaded

### ISSUE THREAD

**Issue by alxtalend** [docker/docker#24331]
Hi,
debian 8.5
Docker version 1.11.2, build b9f10c9

When i was trying to start docker with insecure option (DOCKER_OPTS="--insecure-registry tal-qa158.talend.lan:5000") the access to non https registry was not functionnal.

the $DOCKER_OPTS from /etc/default/decker seems not loaded in /lib/systemd/system/docker.service because not setup in ExecStart variable.

the EnvironmentFile=-/etc/default/docker entry is missing from /lib/systemd/system/docker.service

Best regards

**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:39 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:39 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 4
 Running: 1
 Paused: 0
 Stopped: 3
Images: 5
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 20
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 986.9 MiB
Name: DockerHost1
ID: ZRXR:K2OY:JGUD:JH3L:QAA5:2IUY:VRJR:NFVP:FSE6:CBGW:HQS3:L7GV
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Username: talendinfrastructure
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.7 up debian 8.5
2. 7 up docker from apt
3. try to access a non https registry

**Comment by ginkel** [comment]
Debian 8 is most likely using systemd. See the comment at the top of the `/etc/default/docker` file:

```
# THIS FILE DOES NOT APPLY TO SYSTEMD
#
#   Please see the documentation for "systemd drop-ins":
#   https://docs.docker.com/engine/articles/systemd/
```

**Comment by cpuguy83** [comment]
Yep. Jessie uses systemd.

The best place to put these settings is in `/etc/docker/daemon.json` which will work across any distro, and in many cases the daemon can be reloaded with the new configuration without having to actually restart the daemon.
