### ISSUE TITLE
docker 1.12.0-rc3 doesn't appear to be tagged

### ISSUE THREAD

**Issue by williamh** [docker/docker#24338]
**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
I follow this repository since I'm a maintainer for Gentoo, and I do not see a tag for v1.12.0-rc3. Am Is there something I'm missing?

Thanks,

William

**Comment by vdemeester** [comment]
@williamh it definitely is : https://github.com/docker/docker/tree/v1.12.0-rc3
