### ISSUE TITLE
Daemon can't locate Dockerfile during build due to case sensitive issue on Windows 

### ISSUE THREAD

**Issue by dbreshears** [docker/docker#24348]
When I attempt to build a dockerfile on any drive other than my "C" drive where windows is installed,  then the Daemon fails to find the file due to a case sensitive issue.  Easy to repro, just pass "Dockerfile.Debug" on the command line when the actual file name is "Dockerfile.debug".  Strange that this will fail on my "D" and "E" drive but not on the C drive.    

**Output of `docker version`:**
Docker version 1.12.0-rc2, build 906eacd, experimental

**Output of `docker info`:**
Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 20
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 25
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host overlay bridge
Swarm: inactive
Runtimes: default
Default Runtime: default
Security Options: seccomp
Kernel Version: 4.4.13-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953 GiB
Name: moby
ID: 4GVW:RHEO:QBUC:4KTS:K5ZX:ETOE:BVQW:OKXK:ISJQ:X7DY:J56L:YCEL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Windows 10 Enterprise Insider Preview
Build 14376.rs1_release.160064-1700

**Steps to reproduce the issue:**
1.  Create a new "Dockerfile.debug" with contents "From busybox" and place in d:\temp or e:\temp  (not the C drive and possibly not the system drive)
2.  docker build -f Dockerfile.Debug .

**Describe the results you received:**
D:\temp\repro>docker build -f Dockerfile.Debug .
Sending build context to Docker daemon 2.048 kB
Error response from daemon: Cannot locate specified Dockerfile: Dockerfile.Debug

**Describe the results you expected:**

It should work the same as my "C drive"   

C:\temp\repro>docker build -f Dockerfile.Debug .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM busybox
 ---> 2b8fd9751c4c
Successfully built 2b8fd9751c4c

**Comment by thaJeztah** [comment]
ping @jhowardmsft @duglin perhaps we should resolve the file client-side, then update the filename to the actual case before sending it to the daemon? Sounds like this is an issue with the Linux daemon finding the file with the provided filename, but failing to, because the Linux daemon obviously is case-sensitive

**Comment by duglin** [comment]
@dbreshears On the D and E drives, when you try to access files (from an exe,not the cmd line) by the wrong case does it still find them?  What is special about those drives?  Same hardware as C just different partitions or totally different hardware? Same filesystem?

**Comment by duglin** [comment]
@thaJeztah grabbing the filesystem's version of the Dockerfile name might be the right answer. @jhowardmsft, do we do this already? There's a lot of code in builder/context.go related to Dockerfile processing and wasn't sure if this logic was already added and there's just a bug someplace.

**Comment by dbreshears** [comment]
@duglin Yes,  a console application can access and read the contents of that same file regardless of the case and on any of the drives.   Nothing is jumping out at me with regards to anything special.   C & D partitions share a 250GB drive and E is on a 2TB separate drive.  Just noticed I also have another 2TB F drive and it also repros.     C is the Boot.  All NTFS Bitlocker encrypted

**Comment by jhowardmsft** [comment]
There's nothing special about any of the client drive letters in terms of handling that I can think would affect this. I've got three other issues I'm investigating currently, but see what I can do later this week.

**Comment by thaJeztah** [comment]
ping @dsheets anything you can think of in piñata that could have an influence here? (Don't think so, but just in case)

**Comment by dsheets** [comment]
@thaJeztah not that I know of but @dgageot or @jeanlaurent may know better for Docker for Windows.

**Comment by duglin** [comment]
Where are we on this? Is this still an issue?
@dbreshears

**Comment by jhowardmsft** [comment]
I'm closing this due to no answer. Please re-open if this is still an issue.
