### ISSUE TITLE
docker swarm update without arguments should show usage

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#24352]
While strictly "correct", `docker swarm update` without arguments should show usage instead of "updating" swarm;

current behavior:

```
$ docker swarm update
Swarm updated.
```

expected behavior:

```
$ docker swarm update
Usage:  docker swarm update [OPTIONS]

Update the Swarm

Options:
      --auto-accept value               Auto acceptance policy (worker, manager or none)
      --cert-expiry duration            Validity period for node certificates (default 2160h0m0s)
      --dispatcher-heartbeat duration   Dispatcher heartbeat period (default 5s)
      --external-ca value               Specifications of one or more certificate signing endpoints
      --help                            Print usage
      --secret string                   Set secret value needed to accept nodes into cluster
      --task-history-limit int          Task history retention limit (default 10)
```

**Comment by aaronlehmann** [comment]
I think that once we resolve image digests before passing the image reference to swarm workers, we may want `docker swarm update` with no arguments to repeat the digest resolution and update the digest if it has changed. Then again, showing help output could easily be undone if/when we make this change.

**Comment by thaJeztah** [comment]
For consistency with other commands, I think we should show usage, but agree we can revisit in a future version

**Comment by jhorwit2** [comment]
@thaJeztah just fyi, quite a few commands don't follow this convention. For example:

```
$ docker run
"docker run" requires at least 1 argument(s).
See 'docker run --help'.

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Run a command in a new container
```

**Comment by vdemeester** [comment]
@jhorwit2 I think this is this output @thaJeztah means, as all commands tend to print the *short* usage, which is different from the same command with `--help` flag.

**Comment by jhorwit2** [comment]
@vdemeester My point was that some commands do print the `--help` usage and some don't. 

For example, `docker volume` is the same as `docker volume --help`
```
$ docker volume

Usage:	docker volume COMMAND

Manage Docker volumes

Options:
      --help   Print usage

Commands:
  create      Create a volume
  inspect     Display detailed information on one or more volumes
  ls          List volumes
  rm          Remove a volume

Run 'docker volume COMMAND --help' for more information on a command.```

**Comment by vdemeester** [comment]
@jhorwit2 ah you are right :stuck_out_tongue_closed_eyes: Probably only "leaf" command (with no child commands) are like that :angel:

**Comment by thaJeztah** [comment]
This is still an issue in 1.13-rc1

> I think that once we resolve image digests before passing the image reference to swarm workers, we may want docker swarm update with no arguments to repeat the digest resolution and update the digest if it has changed. Then again, showing help output could easily be undone if/when we make this change.

@aaronlehmann just re-reading this; and I think you were confused with `docker service update`. That command already requires at least 1 argument, and 1.13 added a `--force` flag

I'm moving this to 1.14, but if there's an easy fix for this, we may be able to include it in 1.13

**Comment by yongtang** [comment]
I added a PR #29000 as an attempt to address this issue. In the PR, a `PreRunE` has been added to the `Command` so that the number of flags could be checked. If the number of flags is 0, then help message will be printed.
