### ISSUE TITLE
Incorrect number of replicas reporting when re-balancing services

### ISSUE THREAD

**Issue by johnharris85** [docker/docker#24353]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:45:29 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:45:29 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.0-rc2
Storage Driver: vfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: active
 NodeID: djqphs34m9oviurrq3n8r4jdp
 IsManager: Yes
 Managers: 1
 Nodes: 1
 CACertHash: sha256:56c998e2b8855d62daab7a8f8ae99749598363132fd6a52338ff0351b1a4e71b
Runtimes: default
Default Runtime: default
Security Options: apparmor seccomp
Kernel Version: 3.16.0-73-generic
Operating System: Alpine Linux v3.4 (containerized)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.06 GiB
Name: swarm-manager-1
ID: 5YCU:6OAA:XSHI:SRDW:GUZT:NPXV:3H3M:CFMU:WFT5:R42N:CR3C:L45U
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I'm running the swarm on a single machine using dind but don't think that should have any effect on this issue (not looked any code yet though).

**Steps to reproduce the issue:**
1. Initialise a swarm of 2 nodes.
2. Schedule and scale a service to the swarm (ensuring that each node has a replica).
3. Kill one node, wait for the service to rebalance the desired replicas to the other node.
4. Run `docker service ls`.

**Describe the results you received:**

Incorrect number of replicas reported (3 running, 2 desired), even though there are only 2 running. Looks like it's not removing the ones that were killed as a result of the node going down.

```
/ # docker service ls
ID                     NAME                       REPLICAS     IMAGE         COMMAND
4xajwgjyd589   goofy_stonebraker   3/2                  alpine:3.3     ping docker.com
```

**Describe the results you expected:**

(2/2) replica state.

**Additional information you deem important (e.g. issue happens only occasionally):**

Consistently reproducible.

**Comment by aaronlehmann** [comment]
Can you please try 1.12-rc3? There were a few fixes that may help (especially https://github.com/docker/swarmkit/pull/1059).

**Comment by johnharris85** [comment]
Tested with 1.12-rc3 (again dind), still looks to be failing:

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.0-rc3
Storage Driver: vfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge overlay null
Swarm: active
 NodeID: 9gvdvdxiun2ch2lodyj1yxq9m
 IsManager: Yes
 Managers: 1
 Nodes: 2
 CACertHash: sha256:c0bb721543bfafb482535f3075afdf8e7828d8db59e83819e40dacc2607b7d02
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 3.16.0-73-generic
Operating System: Alpine Linux v3.4 (containerized)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.06 GiB
Name: 4c2e210236b0
ID: 4NMK:CDAB:22IF:YZ3T:JKM6:XTWD:O4PO:YDQA:EJQK:DC2S:OVSO:BZ4I
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: johnharris85
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

```
$ docker service ls
ID            NAME  REPLICAS  IMAGE       COMMAND
3xp63r5zbpd5  test  3/2       alpine:3.3  ping docker.com

```

**Comment by aaronlehmann** [comment]
Setting to 1.12.0 / P1 while this is investigated.

I haven't been able to reproduce this so far. I create a swarm with two docker daemons (dind):

```
# docker daemon -D
# docker swarm init --listen-addr 127.0.0.01:4567
# docker daemon -g /var/lib/docker2 -p /var/run/docker2.pid -H /var/run/docker2.sock
# docker -H unix:///var/run/docker2.sock swarm join --listen-addr 127.0.0.1:4568 127.0.0.1:4567
```

I create a service similar to yours:

```
# docker service create --replicas 2 alpine:3.3 ping docker.com
```

Then I kill the second daemon (the worker). For a few seconds, I see 1/2 replicas in `docker service ls`. Then a replacement task gets scheduled and `docker service ls` shows 2/2 replicas. I can use `docker ps` to confirm two containers are running.

Could you please paste the commands you run to trigger this? Thanks for your help tracking this down.

**Comment by johnharris85** [comment]
OK, so using 'pure' (client and server) dind, this works fine, commands below:
```
$ docker network create test-net
$ docker run --privileged --name swmanager --net test-net -d docker:rc-dind
$ docker run --privileged --name swnode --net test-net -d docker:rc-dind
$ docker run --rm -e DOCKER_HOST=swmanager:2375 --net test-net docker:rc swarm init
$ docker run --rm -e DOCKER_HOST=swnode:2375 --net test-net docker:rc swarm join swmanager:2377
$ docker run --rm -e DOCKER_HOST=swmanager:2375 --net test-net docker:rc service create --name test-service --replicas 2 alpine:3.3 ping docker.com
# make sure they're on different nodes
$ docker run --rm -e DOCKER_HOST=swmanager:2375 --net test-net docker:rc service tasks test-service
$ docker stop swnode
$ docker run --rm -e DOCKER_HOST=swmanager:2375 --net test-net docker:rc service ls
```
2/2, correct output. 

I think my client was at rc2 before, but I figured that wouldn't matter. Downloaded rc3 of the client and now seem to get correct behaviour in both dind and local host to dind daemon. Did get some flip-flopping between Preparing / Accepted states for the tasks, included the Preparing timer constantly resetting. Is that a known issue? Will try and reproduce and file a separate issue if not.

**Comment by aaronlehmann** [comment]
> Did get some flip-flopping between Preparing / Accepted states for the tasks, included the Preparing timer constantly resetting. Is that a known issue? Will try and reproduce and file a separate issue if not.

I don't think this is a known issue, so please file it.

**Comment by tiborvass** [comment]
@aaronlehmann can we close this issue?

**Comment by aaronlehmann** [comment]
Closing - thanks for your help with this @johnharris85, and please reopen if you have further problems.
