### ISSUE TITLE
Ability to set environment variables in exec

### ISSUE THREAD

**Issue by jwendell** [docker/docker#24355]
Currently it's only supported on run

(working on a patch)

**Comment by thaJeztah** [comment]
Before you open a PR; note that there's a feature freeze on the exec command, see https://github.com/docker/docker/blob/master/ROADMAP.md#21-docker-exec

Also, realize that setting env-vars using `exec`, won't change env vars for the main process

**Comment by jwendell** [comment]
@thaJeztah thanks for the explanation, hadn't noticed it before. Kind of frustrating once this is my first experiment in contributing to docker :)

Can this little patch be considered a freeze break? Or can it be seen as just maintenance?

**Comment by thaJeztah** [comment]
We'll see :smile: thanks for opening the PR
