### ISSUE TITLE
Daemon live-restore doesnt perform mount cleanup on stopped containers.

### ISSUE THREAD

**Issue by anusha-ragunathan** [docker/docker#24350]
**Output of `docker version`:**
```
Client:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.2
 Git commit:   c014c9d-unsupported
 Built:        Tue Jul  5 22:43:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.2
 Git commit:   c014c9d-unsupported
 Built:        Tue Jul  5 22:43:08 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
root@42a2dc1cb163:/go/src/github.com/docker/docker# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.0-dev
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: overlay bridge null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 3.19.0-59-generic
Operating System: Debian GNU/Linux 8 (jessie) (containerized)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.38 GiB
Name: 42a2dc1cb163
ID: CB7M:RAGQ:G6KH:KX3R:VWWH:NGK2:L2SQ:SIGP:GM5S:DEWD:R57I:INL5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 13
 Goroutines: 23
 System Time: 2016-07-05T22:45:35.036304639Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Steps to reproduce the issue:**
1. Run a daemon integration test involving live-restore. Ex. TestCleanupMountsAfterDaemonCrash
2. Once test passes, delete the output "bundles" directory. 

**Describe the results you received:**
Removing the directory fails with
"rm: cannot remove 'bundles/1.12.0-dev/test-integration-cli/d67573768/root/overlay': Device or resource busy" message.

**Describe the results you expected:**
Removing directory should have no errors.

**Additional information you deem important (e.g. issue happens only occasionally):**
There should be a clean shutdown of stopped containers in the live-restore case. daemon/daemon.go Shutdown() returns right away for live-restore. It should handle the case of stopped containers, by unmounting through layerStore.

**Comment by anusha-ragunathan** [comment]
cc @crosbymichael @tonistiigi

**Comment by cpuguy83** [comment]
Looks like more simply, start the daemon with `--live-restore`, stop the daemon, and the root graphdriver dir is still mounted.

**Comment by cpuguy83** [comment]
#24435 should fix this
