### ISSUE TITLE
Docker v1.12.0-rc3 looking for dab bundle file

### ISSUE THREAD

**Issue by bobbydeveaux** [docker/docker#24367]
Feedback: Just upgraded to 1.12-rc3 and noticed it not longer looks for a dsb bundle file, even though docker-compose 1.8.0-rc1 is still generating dsb files.

Having to rename my generated dsb files to dab ...

Is this intentional? If so, when will docker-compose be updated to export as dab files by default?

Cheers

**Comment by vdemeester** [comment]
@bobbydeveaux yes this is intentional, compose is now generating `dab` files, but the change is after the `rc1` of compose, so it should land in the next rc or in the final release.

/cc @aanand @dnephin

**Comment by bobbydeveaux** [comment]
Great, thanks for confirming @vdemeester  :)

**Comment by cpuguy83** [comment]
Closing since this isn't really an issue and will be resolved once the new compose RC is generated.
