### ISSUE TITLE
Runc Permission Problem

### ISSUE THREAD

**Issue by senrabdet** [docker/docker#24368]
I am trying to run a Google Chrome container with runc and am getting what superficially look like permission errors (I can run other GUI type of containers like Firefox and Icedove, and non GUI ones like Cups successfully).  I believe that the latest versions of chrome sandboxing cause older docker files to fail, and that utilizing name spaces is necessary.  I am using a .json file generated by Jess Frazelle which I believe works for her (she posts that she uses custom kernels so my set up is not identical).  Note I am using her config.json from:  https://github.com/jfrazelle/containers/blob/master/chrome/config.json#L223 (it contains args and mounts that appear to be the ones used to start chome per her older instructions).  I  believe in part this issue has to do with userns, and attempting to utilize that capability (I believe my kernel supports user name spaces and user cloning).
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:30:35 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:30:35 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 13
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker-8:1-3016557-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.808 GB
 Data Space Total: 107.4 GB
 Data Space Available: 43.82 GB
 Metadata Space Used: 2.191 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.127 (2016-06-11)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.6.0-1-amd64
Operating System: Debian GNU/Linux stretch/sid
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.958 GiB
Name: debian
ID: NYPZ:5UJA:LOJO:GYT7:PEBJ:MZ2U:S2VX:IPXK:3VDH:D6T2:NWXY:YUZM
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Debian Stretch kernel 4.6.0-1 on VirtualBox Version 5.0.24 r108355 on Windows 10 on Dell Latitude E6430

go version (I believe I needed to install "go" for runc, and my go version is different than what's shown in Docker Info - not sure that matters?):
go version go1.6.2 linux/amd64

I installed go with:
apt-get install -y golang
apt-get install -y golang-github-seccomp-libseccomp-golang-dev
...and set env variables in my .basrc as:
export PATH=$PATH:/usr/lib/go/bin
export GOPATH=$HOME/work

Simple go "hello world" test functions correctly.

**Steps to reproduce the issue:**
1.   start docker chrome container "traditional" way using  "--no-sandbox", starts with warning that sandboxing is off ("You are using an unsupported command-line flag:  --no-sandbox.  Stability and security will suffer."):
docker run -it  --cpuset-cpus 0 --memory 512mb -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY -v $HOME/Downloads:/root/Downloads -v $HOME/.config/google-chrome/:/data --device /dev/snd -v /dev/shm:/dev/shm --name chrome jess/chrome --user-data-dir=/data --no-sandbox

start container without --no-sandbox and get:
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted

2.   Try with "runc".... mkdir /dockerchrome
3.  cd /dockerchrome
4.   mkdir rootfs
5.  docker export $(docker create jess/chrome) | tar -C rootfs -xvf -
6.  runc spec
7.  runc start 47d70bd3f838 or runc run 47d70bd3f838 
8.  these results get me to shell # as expected
9.  replace config.json with one from https://github.com/jfrazelle/containers/blob/master/chrome/config.json#L223
10. runc start 47d70bd3f838 or runc run 47d70bd3f838 and get errors, container doesn't start and errors result.

I have tried these tests with and without:
make BUILDTAGS='seccomp apparmor'

**Describe the results you received:**
1) try to run container traditional way without --no-sandbox flag:
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted

2) Try with Runc:
a) runc start 47d70bd3f838 
open /run/runc/47d70bd3f838/state.json: no such file or directory

*  is "state.json" error significant?

b) runc run 47d70bd3f838
 rootfs_linux.go:53: mounting "/root/Downloads" to rootfs "/dockerchrome/rootfs" caused "lstat /dockerchrome/rootfs/root/Downloads: permission denied"

c) docker-runc start 47d70bd3f838
could not synchronise with container process: lstat /dockerchrome/rootfs/root/Downloads: permission denied

I've tried pulling the /root mounts out of the .json and re-running with no joy.  

**Describe the results you expected:**
I expect the container to start with a Chrome instance.

**Additional information you deem important (e.g. issue happens only occasionally):**
Results happen consistently.

**Comment by justincormack** [comment]
Hi, can you raise `runc` issues on the `runc` repo not here, as this is not a docker issue https://github.com/opencontainers/runc 

That file allows `clone` and `unshare` which should be ok. Generally the easiest thing to do is to also allow `ptrace` (both the syscall in seccomp and `SYS_PTRACE` in capabilities) and see what is failing.

I am going to close this here as it is not a docker issue, but you can continue here or open on runc repo...

**Comment by senrabdet** [comment]
Thanks Justin, sorry for my confusion.  If OK, I'll try your suggestions and probably re-post on https://github.com/opencontainers/runc. 
 
 Q:  part of what's led me down this path is trying to get chrome to run in Docker, so in some regards I think of that as a Docker issue if my attempts don't utilize "runc" (which is where I started).  Is it OK to post a "docker only" version on the docker issues location?  I.e., do with running "docker run -it --cpuset-cpus 0 --memory 512mb -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY -v $HOME/Downloads:/root/Downloads -v $HOME/.config/google-chrome/:/data --device /dev/snd -v /dev/shm:/dev/shm --name chrome jess/chrome --user-data-dir=/data"  without the "--no-sandbox" option?
 
Thanks,


-- 


Ted Barnes
Soholistic Networks
www.soholistic.net
(508) 277 9666
 
 
--------- Original Message --------- Subject: Re: [docker/docker] Runc Permission Problem (#24368)

**Comment by justincormack** [comment]
Oh if you are trying to get it to run in Docker, sure. You can just reopen this issue with how you were trying in docker and change the title thats fine...

**Comment by justincormack** [comment]
I think you may need to `strace` the startup. I think you will find it may work with `--cap-add SYS_ADMIN` which allows creating namespaces, but I would think it should create the user namespace first, which is an unprivileged operation, so it is a bit odd.

It doesnt seem to be seccomp related as adding `--security-opt seccomp=unconfined` makes no difference.
