### ISSUE TITLE
[1.12.0-rc2] Interactive Service Containers for debugging/adhoc tasks

### ISSUE THREAD

**Issue by BenHall** [docker/docker#24362]
I wanted to start an interactive container against an overlay network as part of a Swarm Mode.

1) Create the overlay network `docker network create -d overlay eg1`
2) Deploy some containers `docker service create --name http --network eg1 --replicas 2 katacoda/docker-http-server`

3) Attach to the network `docker run -it --net=eg1 ubuntu bash`

However, I get the error
```
docker: Error response from daemon: swarm-scoped network (eg1) is not compatible with `docker
 create` or `docker run`. This network can be only used docker service.                      
See 'docker run --help'.
```

What's the recommended way to attach eg1 if you needed to debug something?

**Comment by justincormack** [comment]
You can `docker exec` from the node the container is running on, or `docker run` in the container's network namespace.

**Comment by jmandel** [comment]
@justincormack can you clarify what you mean by "`docker run` in the container's network namespace"? What would this look like?

**Comment by mavenugo** [comment]
@BenHall 

> 3) Attach to the network docker run -it --net=eg1 ubuntu bash

As the error message indicates, this is currently not supported. But we are actively working on it.

@jmandel `docker run --it --net=container:{http-service-container-id} ubuntu bash`. This will run a container and will share the same network namespace as the container that backs the http service.

**Comment by thaJeztah** [comment]
I'm closing this issue, because this is possible with the above instructions, but we'll be looking into enhancing this for 1.13
