### ISSUE TITLE
master process running in container doesn't get SIGTERM on stop with lxc

### ISSUE THREAD

**Issue by SamSaffron** [docker/docker#2436]
running:

```
Linux ubuntu 3.11.0-12-generic #19-Ubuntu SMP Wed Oct 9 16:20:46 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
```

(ubuntu latest)

```
root@ubuntu:/home/sam# lxc-version 
lxc version: 1.0.0.alpha1
```

run: `docker run -i -t ubuntu /bin/bash`

attempt to stop the container:

container fails to stop properly and reverts to kill

```
2013/10/29 16:24:47 error killing container 9d01aa5543a8df028df004c440240e72080b17eada1bf0cd9c5a092ae61139a4 (lxc-kill: failed to get the init pid
, exit status 255)
2013/10/29 16:24:57 Container 9d01aa5543a8df028df004c440240e72080b17eada1bf0cd9c5a092ae61139a4 failed to exit within 10 seconds of lxc SIGKILL - trying direct SIGKILL

```

**Comment by jfrazelle** [comment]
ping @ashahab-altiscale is this still an issue

can anyone here reproduce with latest docker and lxc 1.0.7

**Comment by skozin** [comment]
@jfrazelle, see https://github.com/joyent/node/issues/9131. Maybe that is another issue, but it prevents Node.js v0.11.14 and v0.12 from exiting on `SIGTERM` and `SIGINT`. Node tries to forward trapped signal to itself, but that fails because Node runs as PID 1 and cannot be terminated that way.

**Comment by jfrazelle** [comment]
i cannot reproduce with lxc 1.0.7 and latest docker
