### ISSUE TITLE
Docker 1.12.0-rc3 - 'docker info' failed to identify seccomp support

### ISSUE THREAD

**Issue by jerbia** [docker/docker#24374]
**Output of `docker version`:**

```
# docker version
Client:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   91e29e8
 Built:        Sat Jul  2 00:28:53 2016
 OS/Arch:      linux/amd64
Server:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   91e29e8
 Built:        Sat Jul  2 00:28:53 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 4
Server Version: 1.12.0-rc3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 25
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 3.19.0-64-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.657 GiB
Name: XXX
ID: 336I:P2SI:C6BP:I2EW:2BFA:UIQA:YXAR:M7FH:ZNRU:VT7J:MG6G:4GE2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Install Docker 1.12_rc_3 on Ubuntu 14.04, Kernel 3.19.
2. Run "docker info" --> you see that "seecomp" is shown as enabled ("security options" field).
3. Try running container with seccomp profile - failed to run as seccomp is not supported.

 docker run --rm -it --security-opt seccomp=/profile.json debian
docker: Error response from daemon: linux seccomp: seccomp profiles are not supported on this daemon, you cannot specify a custom seccomp profile.

**Describe the results you received:**
Getting an error when trying to run container with seccomp profile, which conflicts the output "docker info".

**Describe the results you expected:**
Either "docker info" is wrong (showing that seccomp is enabled) or "docker run" is wrong (not allowing to run with seccomp on this platform). Based on my analysis - the 'docker info' is wrong.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by justincormack** [comment]
How did you install docker?

**Comment by justincormack** [comment]
Ok, I can replicate with Ubuntu 14.04 and just using `wget -qO- https://test.docker.com/ | sh`, this says it has seccomp but does not.

@yongtang do you want to look at fixing this? If not I will.

**Comment by yongtang** [comment]
Thanks @justincormack I will take a look and provide a fix. #dibs

**Comment by justincormack** [comment]
@yongtang thanks!

**Comment by yongtang** [comment]
@justincormack @jerbia The issue seems to be that, in `docker info` the output of seccomp is only decided by inspecting CONFIG_SECCOMP and CONFIG_SECCOMP_FILTER in the kernel. However, the seccomp itself might be disabled when building docker (with golang build option of `// +build !seccomp`).

I create a pull request #24468 to address this issue by adding a boolean variable `supportsSeccomp` and assign it to true or false based on golang build flag.

Please let me know if there are any issues.
