### ISSUE TITLE
[1.12.0-rc2] docker node reject?

### ISSUE THREAD

**Issue by BenHall** [docker/docker#24375]
If there is `docker node accept`, how do you reject a node from joining?

I expected to see something like `docker node reject`

**Comment by aaronlehmann** [comment]
@BenHall: You can use `docker node rm` to remove pending nodes from the list without accepting them.

I'll go ahead and close this, but please follow if this doesn't work as expected.

**Comment by thaJeztah** [comment]
perhaps this can be improved in the docs? /cc @sfsmithcha
