### ISSUE TITLE
Launching Docker for Mac application after BlueStacks

### ISSUE THREAD

**Issue by arkhwise** [docker/docker#24381]
Hello!
Recently I found interesting case:
When Docker for Mac is running, BlueStacks can't load VM.
![BlueStacks](http://image.prntscr.com/image/d289049dc9114118a56f9688c41cbf4d.png)
**But if a BlueStacks VM started at least once and you launch Docker for Mac – it will reboot the macOS.**

## Versions
OS X: `El Capitan 10.11.5`
Docker for Mac: `Version 1.12.0-rc3-beta18 (build: 9996)`
BlueStacks: `0.9.30` (latest)

**Comment by justincormack** [comment]
Does Bluestacks use Virtualbox?

**Comment by arkhwise** [comment]
@justincormack I don't know. Bluestack is closed source, and I did not find any information about using Virtualbox.

**Comment by justincormack** [comment]
Ah OK. Looks like it is not compatible with the osx hypervisor framework.
Have you filed an issue with them? It looks like the issue vurtualbox 4.x
had, which was fixed in 5.x.

**Comment by arkhwise** [comment]
@justincormack 
I didn't tell them about this issue.
Okay. Can you send me a link for VirtualBox issue? I'll say them about this trouble within a few days.

**Comment by alexpts** [comment]
Guys, Did you able to solve this problem?

**Comment by juliustip** [comment]
Anyway around this issue?

**Comment by yangit** [comment]
This issue is really annoying.

**Comment by lucasdidur** [comment]
I have the same problem

**Comment by santidesimone** [comment]
Any news on this?

**Comment by knweber** [comment]
Any updates?

**Comment by thaJeztah** [comment]
If nobody opened an issue with BlueStacks, then, no, no updates

**Comment by PatrickDRusk** [comment]
FWIW, I am running with Docker for Mac and BlueStacks operating fine concurrently, with these versions:
macOS High Sierra (10.13.3)
Docker for Mac 17.12.0-ce-mac55 (23011)
BlueStacks 2.0.0 (10)

**Comment by nooperpudd** [comment]
@PatrickDRusk How could you put the BlueStacks with docker?

**Comment by akougblenou** [comment]
Hi @PatrickDRusk I'd be really interested in knowing how you managed to run both concurrently also !
