### ISSUE TITLE
make deb fails on arm64

### ISSUE THREAD

**Issue by adomenech73** [docker/docker#24380]
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6.1
 Git commit:   20f81dd
 Built:        Wed, 20 Apr 2016 14:19:16 -0700
 OS/Arch:      linux/arm64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6.1
 Git commit:   20f81dd
 Built:        Wed, 20 Apr 2016 14:19:16 -0700
 OS/Arch:      linux/arm64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 42
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 31
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.101-0-pine64-longsleep
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: aarch64
CPUs: 4
Total Memory: 1.943 GiB
Name: pine64
ID: NANA:36TS:63E4:JM3T:QQEE:CTEP:F324:WJHS:LXOL:7GNL:WNEN:JKKU
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical Pine64 with ubuntu 16.4 for arm64

**Steps to reproduce the issue:**
1. download git docker source
2. execute make deb

**Describe the results you received:**

---> Making bundle: dynbinary (in bundles/1.12.0-rc3/dynbinary)
Building: bundles/1.12.0-rc3/dynbinary-client/docker-1.12.0-rc3
github.com/miekg/pkcs11
vendor/src/github.com/miekg/pkcs11/pkcs11.go:26:18: fatal error: ltdl.h: No such file or directory
compilation terminated.
Makefile:86: recipe for target 'deb' failed
make: *** [deb] Error 1

**Describe the results you expected:**
deb docker package for installation

**Additional information you deem important (e.g. issue happens only occasionally):**
I allready installed libltdl-dev package and even tried to copy the file locally to pkcs11.go dir

**Comment by thaJeztah** [comment]
We currently don't support aarch64, so this may be expected.

**Comment by adomenech73** [comment]
It's a shame. I hope you include it shortly. Do you know if there is any plan on this allready??

In this particular issue it's curious cause seem that probably is happening on other pkcs11 Linux builds  https://github.com/miekg/pkcs11/issues/24

If I can reproduce on i386 or amd64 I'll try to reopen

Supose the only option left in this case & moment is to do my own packages from binaries

**Comment by justincormack** [comment]
It also fails with this on `make test` on aarch64 so I will reopen this as there should be an arm64 CI soon...

**Comment by justincormack** [comment]
Can you test with https://github.com/docker/docker/pull/24412 applied?

**Comment by adomenech73** [comment]
I just tested, took a while but it worked perfectly!! Thanks, I didn't realise that the dependencies where needed on Dockerfile, I was stupidly trying to put them on the host.

Now it stacks on apparmor stuff (I append the error and I'll try to explore a bit) but seems to me that your pull request solves ltdl.h issue

```
---> Making bundle: .detect-daemon-osarch (in bundles/1.12.0-dev/build-deb)
find: `contrib/builder/deb/aarch64/*/': No such file or directory
---> Making bundle: .integration-daemon-stop (in bundles/1.12.0-dev/build-deb)
+++++ cat bundles/1.12.0-dev/build-deb/docker.pid
++++ kill 5063
++++ /etc/init.d/apparmor stop
 * Clearing AppArmor profiles cache
   ...done.
All profile caches have been cleared, but no profiles have been unloaded.
Unloading profiles will leave already running processes permanently
unconfined, which can lead to unexpected situations.

To set a process to complain mode, use the command line tool
'aa-complain'. To really tear down all profiles, run the init script
with the 'teardown' option."
Makefile:86: recipe for target 'deb' failed
make: *** [deb] Error 1
```

**Comment by adomenech73** [comment]
I've seen that the problem is that contrib/builder/deb/aarch64/ is needed, the only problem is that golang tgz is not yet avaliable for this arch, but I thing I can use https://github.com/hypriot/golang-armbuilds for this purpose. On the other hand I beleive that test errors seems that some kind of arch limitation has been reached.

Anyway, thabks again for the step further!!

**Comment by justincormack** [comment]
Yes the lack of official arm64 Go binaries is annoying, it is also worked
around in the main build. I don't currently have an aarch64 machine with
apparmor so have not tested that yet.

**Comment by alexellis** [comment]
@justincormack I still get an error like this building on AARCH64 with docker/docker master branch:

```
--- FAIL: TestMountMoreThan42Layers (5.20s)
```

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   23cf638
 Built:        Tue, 27 Sep 2016 12:25:38 +1300
 OS/Arch:      linux/arm64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   23cf638
 Built:        Tue, 27 Sep 2016 12:25:38 +1300
 OS/Arch:      linux/arm64
```

```
# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 34
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 28
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-38-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: aarch64
CPUs: 96
Total Memory: 125.9 GiB
```
