### ISSUE TITLE
Dockerfiles should have a way to perform multiple build actions in one commit

### ISSUE THREAD

**Issue by bwilkins** [docker/docker#2439]
I'm using multiple docker files to build up an environment (with the aim of a set of environments). Unfortunately I blow through AUFS's 42 layer limitation with this. I would like to be able to collapse a set of actions into a single commit.

I envision this being done as perhaps BEGIN and COMMIT commands (akin to SQL's transaction commands). I may look at doing this myself if I can find the time, but if this doesn't fit into the ideal of the app then I don't want to put too much effort into it.

My work-around in the meantime is to have a bash script that builds each Dockerfile then exports to tar and reimports into the same image tag, before beginning the next build.

**Comment by PM-Andrey-Kupreychik** [comment]
I think this is really needed for blocks like
ADD http://example.com/web-server.tar.gz /web-server-source
 RUN cd /web-server-source ; make install
 RUN rm -rf /web-server-source

Because web-server.tar.gz can be a big file. And it'll be stored in some of layers

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.
