### ISSUE TITLE
Double VIP creation

### ISSUE THREAD

**Issue by mgoelzer** [docker/docker#24399]
Under some scenarios two VIPs are being returned by the internal resolver for a single service name.  This should never be possible.  Hypothesis:  stale DNS caching.

Environment:
```
Red Hat Enterprise Linux Server release 7.2 (Maipo)
[root@node2 ~]# uname -a
Linux node2 3.10.0-327.22.2.el7.x86_64 #1 SMP Thu Jun 9 10:09:10 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
```

@mavenugo

**Comment by sanimej** [comment]
@mgoelzer Is there a way to recreate this issue ?

**Comment by mgoelzer** [comment]
@huslage Is there a way we can connect @sanimej to the user who was having this problem?  It sounded reproducible in their setup, though I cannot reproduce on my own RHEL 7.2 cluster.

**Comment by thaJeztah** [comment]
@mgoelzer is this still an issue?

**Comment by mgoelzer** [comment]
I haven't experienced it recently.  Let's close.
