### ISSUE TITLE
[1.12] provide a "managed" / "unmanaged" (or similar) filter

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#24393]
Following the discussion on https://github.com/docker/docker/issues/23704, I think we should have a filter that allows users to separate "managed" containers from "unmanaged" ones.

"Managed" containers, are containers that are started by a task (when creating services in Swarm mode). Users should not interact with such containers (in most cases), e.g. not "stop", "start", "remove" them manually.

Although we don't *forbid* users to do so, we should have an option to distinguish (un)managed containers, so that (again, for example) automated scripts can be modified to only handle "unmanaged" containers.

I'm completely open to suggestions w.r.t. naming; is "managed" the right term for this?

**Comment by tiborvass** [comment]
@thaJeztah If we were to do this, then we should probably revisit the term `managed`. That term should stay internal to the codebase and if we want to expose it, we should find another one.

**Comment by vdemeester** [comment]
@tiborvass @thaJeztah do you have any proposition :sweat_smile: ? I think I don't have enough perspective because to me `managed` make sence (it is *managed* by the cluster) :stuck_out_tongue_closed_eyes:.

*Did I never said I'm bad with names ? :joy_cat:*

**Comment by thaJeztah** [comment]
@tiborvass yes, that's the part I wasn't sure about; `is-task`? or should we filter by "service" (`service=any`, `service=some-service`)? Also open to suggestions

**Comment by tiborvass** [comment]
I consider this discussion linked to the "tasks UI" disscusions.

**Comment by thaJeztah** [comment]
ping @aluzzardi PTAL on the naming / type of filter

**Comment by thaJeztah** [comment]
I thought of `--service=*`, but wasn't sure if that would cause issues with the shell messing with that :sweat_smile:

**Comment by vdemeester** [comment]
@thaJeztah ah :sweat:

**Comment by pnickolov** [comment]
IMHO, one of the main uses of what @thaJeztah proposed is to be able to see all the containers that are NOT part of a service - i.e., ones that I start and manage myself directly. 

Ideally, this would be some very easy to type option: something like --not-task, --raw, etc.; what @vdemeester proposes is also  quite good, "--filter=is-task=true" (that's what bash aliases are for).

A second use case would be to see all "managed" (aka service, aka task-initiated) containers -- either all  or those that belong to a specific service, where something like "--filter=service=myservice" would work

(separately, @thaJeztah for the shell expansion of * - it would make sense that most bash users will already be familiar with this (although when you run script from a script it gets finicky); however, I don't know if there is anything else in docker xxx commands that uses wildcards, so introducing this may not be best; also see #17237)
