### ISSUE TITLE
Swarm mode: service definition lacks custom DNS settings

### ISSUE THREAD

**Issue by dhiltgen** [docker/docker#24391]
When creating a container one can specify custom DNS settings: https://godoc.org/github.com/docker/engine-api/types/container#HostConfig - specifically `DNS`, `DNSOptions` and `DNSSearch`

There is no equivalent in the https://godoc.org/github.com/docker/engine-api/types/swarm#ServiceSpec

**Comment by yongtang** [comment]
Added a PR #27567 to have DNS related configs in service specification.
