### ISSUE TITLE
Docker info showing multiple daemon labels with the same (duplicate) key

### ISSUE THREAD

**Issue by bennetimo** [docker/docker#24392]
I'm seeing multiple labels with the same key shown by `docker info` if the daemon has been configured to have them. I'm expecting labels with the same key to overwrite each other.

Full details below: 

**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 9
 Running: 5
 Paused: 0
 Stopped: 4
Images: 64
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker-253:0-394071-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 5.983 GB
 Data Space Total: 107.4 GB
 Data Space Available: 32.6 GB
 Metadata Space Used: 12.24 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.135 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 3.10.0-327.13.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.703 GiB
Name: localhost.localdomain
ID: W76H:PGH2:73BA:V6D7:MXTA:RG3F:UYN2:EDER:AQBZ:L4FS:ARWK:ZP5A
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Labels:
 test.label="1"
 test.label="2"
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Vagrant CentOS 7

**Steps to reproduce the issue:**
1. Start docker daemon with multiple labels having the same key

For example, this is the service configuration I have used:
```
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target docker.socket
Requires=docker.socket

[Service]
Type=notify
ExecStart=/usr/bin/docker daemon \
 --label test.label="1" \
 --label test.label="2" \
 -H unix:///var/run/docker.sock
MountFlags=slave
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity
TimeoutStartSec=0

[Install]
WantedBy=multi-user.target
```

**Describe the results you received:**
`docker info` lists multiple labels with a duplicated key. Specifically, there are two 'test.label' keys shown in the output.

**Describe the results you expected:**
As per the docs [here](https://docs.docker.com/v1.11/engine/userguide/labels-custom-metadata/), I would expect only the second label to be present:
> A label is a <key> / <value> pair. Docker stores the label values as strings. You can specify multiple labels but each <key> must be unique or the value will be overwritten. If you specify the same key several times but with different values, newer labels overwrite previous labels. Docker uses the last key=value you supply.

**Additional information you deem important (e.g. issue happens only occasionally):**
I have hooked up a node with multiple labels to a swarm cluster, and the swarm master when pulling the labels only sees the key once, the newer one as expected. So, possibly the key is being overwritten but the `docker info` is still listing all specified labels.

**Comment by vdemeester** [comment]
@bennetimo labels are stored in the daemon configuration as an array of string, where a string is `label=value`, thus you can specifiy multiple labels with the same value. But when *resolving* them we transform them in a `map[string]string` and thus, only the last one is taken into account.

The simplest fix would be to convert `info.Labels` to a `map` in the info *cli* command and thus display what's beeing resolved. Changing the way we store label in the daemon or what the `/info` endpoint returns (a map instead of an array) would be a little more tricky.

/cc @calavera

**Comment by thaJeztah** [comment]
we discussed this while implementing the other labels, and I think it was decided then to not change this (to prevent a backward incompatible change), but perhaps opinions changed in the meantime

**Comment by bennetimo** [comment]
@vdemeester Thanks for the info, makes sense

**Comment by thaJeztah** [comment]
@vdemeester changing `info.Labels` won't affect the API? If so, then I'm +1 to "fixing" the output

**Comment by thaJeztah** [comment]
also /cc @vieux (who implemented those labels)

**Comment by vdemeester** [comment]
@thaJeztah those two could be done in the same time yeah :wink:

**Comment by yongtang** [comment]
@bennetimo @vdemeester @thaJeztah I created a pull request #24533 to remove the duplicate keys of the labels in daemon's `SystemInfo()`. This will only remove the duplicate keys in the output of `docker info` and no API changes (thus no engine-api update). Please let me know if this help address the issue.
