### ISSUE TITLE
Health checks are hard to implement because of return codes

### ISSUE THREAD

**Issue by aluzzardi** [docker/docker#24396]
I mentioned this during the review but it didn't get addressed so reposting this as an issue.

We ask health checks to return `0` if they were successful (good), `1` if the failed (good) and `2` if the container is still initializing (weird).

A health check scripts has no way to know whether it's in initialization period or not. This basically means that rather than being a simple command, a proper health check has to keep state and implement its own grace period.

I propose we get rid of `2`. Actually, we get rid of all return codes - in the `HEALTHCHECK` instruction we could provide what a "good" exit code is (and we default to 0).

In order to achieve the "it's still initializing" behavior, we put a grace period.

/cc @stevvooe @icecrime @tiborvass @runshenzhu

**Comment by cpuguy83** [comment]
I don't think we should allow defining what an exit code means, this is too much control.
Simple 0 or 1 should be ok and is extremely friendly to used to managing exit codes (which is anyone who has done system monitoring I should think).

Agree 2 is rather useless. A "starting" state would just be a container that has not returned a successful healthcheck yet.

**Comment by thaJeztah** [comment]
Even thinking if we should use negative values for failures, but perhaps I just like different bike shed colors

**Comment by vdemeester** [comment]
> I don't think we should allow defining what an exit code means, this is too much control.
Simple 0 or 1 should be ok and is extremely friendly to anyone who has dealt with exit codes (which is anyone who has done system monitoring I should think).

I do agree with @cpuguy83, exit code 0 for *ok* is pretty common and anything different of zéro is considered as *ko*. Also agree the `2` should be removed.

**Comment by justincormack** [comment]
cc @talex5 

@thaJeztah exit codes are 0-255, negative ones do not exist.

**Comment by talex5** [comment]
The case that was made for adding state 2 (my original version worked as you describe) was that of a database that is performing recovery after being restarted. There's no reasonable way to set a grace period that will detect when the container has failed reasonably soon but won't also kill the recovery.

For many services you can detect starting (e.g. postgres returns a special response for this I think). Or, e.g. if the pid file hasn't been written yet it would be reasonable to assume the container is still starting.

**Comment by justincormack** [comment]
@aluzzardi if you have no way of knowing if the container is initialising, just return good. The aim is for things that are slow start to be able to indicate they are not ready yet so staggered start can work - many clients have asked for something as eg mysql can take 15 seconds to start, and they want services that depend on it to start after, rather than be unable to connect to the database.

**Comment by kelseyhightower** [comment]
I think it would be a good idea to allow people to set the exit code, mainly because not everyone will have full control over scripts that get ran during a health check. I'm sure this will be a rare case, so using 0 as the default works, but the last thing you want to do is have users write wrapper scripts to work around this limitation.

**Comment by LK4D4** [comment]
@aluzzardi so, what do you think? Some software is providing way to know if it's in initialization state, so 2 makes sense.

**Comment by stevvooe** [comment]
@LK4D4 Could it just block on the first call after startup?

**Comment by aluzzardi** [comment]
> @aluzzardi if you have no way of knowing if the container is initialising, just return good

The corollary of that is "if you have no way of knowing if the container is initializing and you can't reach it, return bad".

Point being, we don't have a grace period.

/cc @psftw @tianon @jpetazzo 

I think we need to write a few examples for some of the library images and see how it works.

**Comment by tiborvass** [comment]
The part where I concur with @aluzzardi is that if we're not sure and still
debating this I'd rather have something that does less and is future proof.
So if we validated exit codes and accept only 0 and 1 for now it gives us
the option to add 2 in the future. Agree?

**Comment by justincormack** [comment]
I think some examples for how to treat startup eg on databases would help.

**Comment by icecrime** [comment]
I think status code 2 makes sense:
- We're not forcing all health-check scripts to return it where applicable
- If we remove it, we need to reinstate a grace period, which appropriate value is pretty much impossible to determine

I'm for keeping return code 2 and closing this issue.

**Comment by icecrime** [comment]
_Silence means consent._ :innocent:

**Comment by stevvooe** [comment]
@icecrime Can we say that an unexited health check script implies 2, at startup?

**Comment by aluzzardi** [comment]
On my phone, sorry for brevity, but there's a huge red flag here: I don't see a way to write health checks for most of our base images.

I don't think we did any research on how we're actually going to implement status code 2.

Take redis. I don't think there's a way to reliably return a 2. So it better load the entire data set in less than 5 seconds (or whatever the interval is) or we're going to crash loop it forever. At least operators would have had a way to override the grace period through run/svc flags.

Take a python/uwsgi app. You're an health check script. The port is not bound. Awesome. Is it still starting? Or did it crash? I have no idea - I'm a health check script and I don't keep a state machine around. Return 0 and hope it comes alive within the number of retries or else we're crash looping. Again, the operator can't do a thing but watch the service burn.

**Comment by thaJeztah** [comment]
Let me reopen for now

**Comment by thaJeztah** [comment]
ping @tianon did you have a look at implementing health checks for the official images, any suggestion what you think works best?

**Comment by tianon** [comment]
I did indeed; see https://github.com/docker-library/healthcheck and https://hub.docker.com/u/healthcheck/

For almost all the official images, we've developed them such that they aren't listening for remote connections until the initialization is completed, which we were able to leverage in the healthcheck scripts, but writing them in a generic way is difficult given that users of them may or may not have a different definition of "heathy" or "ready" (and just because the pre-start "initialization" is complete doesn't mean the DB is actually ready either -- for example, MongoDB will often decide that it'll be faster in the long run if it pre-allocates journal space, so that slows down the startup).

That being said, the health check scripts I wrote only ever return either `0` or `2`.  We cannot know whether the database is still in a "startup" phase, so we instead rely on Docker's tracking of whether we've ever left the starting state to convert that `2` exit code into proper failure.  (This is why I argued in the initial thread that there are really only two concrete states for a service and anything else is interpretation.)

> If the probe returns 2 ("starting") when the container has already moved out of the "starting" state then it is treated as "unhealthy" instead.

- https://github.com/docker/docker/blob/dcc65376bac8e73bb5930fce4cddc2350bb7baa2/docs/reference/builder.md#healthcheck

**Comment by tiborvass** [comment]
@tianon does this mean you agree with Andrea that there can only be two states?

If so, do you think it's reasonable to make remove a state and only have exit code `0` and `1` for now and that way if we were to revisit we could still add an exit code `2` in the future?

**Comment by tianon** [comment]
Yeah, that sounds sane IMO.

**Comment by stevvooe** [comment]
> We cannot know whether the database is still in a "startup" phase

What? No.

Classic method: connect to database and issue a query.

Postgres has [`pg_is_in_recovery`](https://www.postgresql.org/docs/9.0/static/functions-admin.html). A health check script could startup and poll that and block until that returns `false`.

> MongoDB will often decide that it'll be faster in the long run if it pre-allocates journal space, so that slows down the startup

After very little googling: https://docs.mongodb.com/manual/tutorial/recover-data-following-unexpected-shutdown/. How is this done? Have entrypoint detect the necessity for recovery. Re-exec with recovery operation. Write files (or something) to signal to healthcheck script that everything is good to go.

Here is a table of how this should be done:

| State | Description |
| `starting` | Health check script not exited on first run. |
| `healthy` | Health check script exits 0 on any run. |
| `unhealthy` | Health check exited with non-zero at any time. |

Simple stuff. Extremely powerful.

**Comment by aluzzardi** [comment]
You can't just not return because you're initializing.

After a while you'll get timeout killed by the engine

**Comment by aluzzardi** [comment]
Unless we have health checks for the health checks, but see where this would lead us?

**Comment by thaJeztah** [comment]
@stevvooe would we loose much *now* if we decide to skip the "starting" stage for 1.12, and look into possibilities for 1.13, as @tiborvass suggested? (https://github.com/docker/docker/issues/24396#issuecomment-233017131). Given the amount of discussion, I think it's safe to say it needs more investigation (insert "no is temporary.." here).

I think dropping it now is the safe option, and it will still give us the chance to add it in the next release. There's a sh*tload of issues to be looked into for 1.12....

**Comment by tiborvass** [comment]
I'm removing exit code 2.

**Comment by stevvooe** [comment]
> You can't just not return because you're initializing.

@aluzzardi What? That is whole point.

> Unless we have health checks for the health checks, but see where this would lead us?

What makes you think a health check can't block for awhile? That is what starting up is, effectively. There is a configurable timeout to bound this.
