### ISSUE TITLE
Docs: 1.12 RC - how to configure the swarm managers be manager-only nodes?

### ISSUE THREAD

**Issue by ligc** [docker/docker#24409]
The https://docs.docker.com/engine/swarm/key-concepts/ mentions  **"By default manager nodes are also worker nodes, but you can configure managers to be manager-only nodes."**, I was not able to find how to configure the swarm managers to be manager-only nodes, maybe I missed something, but could someone shed some light on this? Thanks.

**Comment by tronicum** [comment]
I guess you could set a constraint as mentioned in https://docs.docker.com/swarm/scheduler/filter/ (set label containerslots to the running number of containers). Not intended to do what you want but it It would do the trick, probably.

**Comment by cpuguy83** [comment]
ping @vieux @aluzzardi

**Comment by ralphtheninja** [comment]
+1 I also wondered about this

**Comment by thaJeztah** [comment]
I think the way to do this is to put them in `drain`;

    docker node update --availability=drain <node-id>

docs may need to be improved on that

/cc @sfsmithcha

**Comment by ligc** [comment]
@thaJeztah Thanks, it works perfectly, after I drained the manager, the containers are not scheduled on the manager any more.  I am fine with closing this issue, if we do not need this issue to track the possible doc changes.

**Comment by sfsmithcha** [comment]
Docs for this are WIP.  @thaJeztah is right:
```
docker node update --availability=drain <node-id>
```
closing per @ligc 's comment

**Comment by tlvenn** [comment]
Sorry to revive this closed topic but while drain does the job, am i the only one thinking that semantically 'drain' is wrong here ? My understanding is your drain a node so you can put it out of your cluster and it seems now we are using this flag for its side effect of making sure the orchestrator will not place anything on that node.

Wouldn't it be better to introduce another availability mode that does not imply there is something wrong with the node and better express the intent ?

**Comment by tronicum** [comment]
And this does work for "new" docker 0.12+ swarms with integrated nodes or also for "legacy" swarms that where setup with docker-machine with <=0.11/swarm:latest ?

**Comment by thaJeztah** [comment]
@tronicum "Swarm" is really separate from this; please check https://github.com/docker/swarm/issues for feature requests for that
