### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by HuKeping** [docker/docker#24402]
Will docker load the certs which has already loaded in the system first? Or which directory will it load first?

I tried `docker pull  xxx` with DCT enabled and get `x509: certificate signed by unknown authority`.

After I installed the required cert into system I still get this error, but after I put these required certs into `~/.docker/tls/notary-server:4443/` it works fine.

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   d9d3582
 Built:        Fri Jul  1 08:47:52 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   d9d3582
 Built:        Fri Jul  1 08:47:52 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by phemmer** [comment]
Dup of #12756

**Comment by thaJeztah** [comment]
thanks; yes closing this as a dup of https://github.com/docker/docker/issues/12756
