### ISSUE TITLE
Cannot build multi-manager swarm mode cluster.

### ISSUE THREAD

**Issue by raykrueger** [docker/docker#24404]
**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   91e29e8
 Built:        Sat Jul  2 00:17:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.0-rc3
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge host null
Swarm: active
 NodeID: 7x61vkrngwq0m192vylj778lf
 IsManager: Yes
 Managers: 2
 Nodes: 2
 CACertHash: sha256:7e9a36e3ad2958bc688b01d3cfc1963fec1f54906bf359bbf346e5f133638a93
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.14-boot2docker
Operating System: Boot2Docker 1.12.0-rc3 (TCL 7.1); HEAD : 8d9ee9f - Sat Jul  2 05:02:44 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: manager-1
ID: LHNV:FIXG:7SRE:FBIN:7Q45:KX7H:5LVW:LH6S:5HSP:6W2D:NG46:RTP7
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 36
 Goroutines: 135
 System Time: 2016-07-07T03:53:03.29094559Z
 EventsListeners: 0
Username: raykrueger
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

create-swarm script:

```
#!/usr/bin/env bash

docker-machine create -d virtualbox manager-1
echo "--- Swarm Init"
docker-machine ssh manager-1 docker swarm init --auto-accept manager --auto-accept worker

manager_ip=$(docker-machine ip manager-1)

for n in {2..3} ; do
	docker-machine create -d virtualbox manager-${n}
	echo "--- Swarm Manager Join"
	docker-machine ssh manager-${n} docker swarm join --manager ${manager_ip}:2377
done

for n in {1..3} ; do
	docker-machine create -d virtualbox worker-${n}
	echo "--- Swarm Worker Join"
	docker-machine ssh worker-${n} docker swarm join ${manager_ip}:2377
done

echo 'eval $(docker-machine env manager-1)'
```

**Steps to reproduce the issue:**
1. Install docker-toolbox tooling or at least have a working docker-machine client
2. Execute ./create-swarm script and wait

**Describe the results you received:**

Manager-1 will be created and initialize the swarm fine.
Manager-2 will be created fine, and maybe join as a manager.
Manager-3 will be created fine but likely Timeiout.
Worker-1,2 and 3 will probably timeout.

The docker engine will report the following error
"Error response from daemon: Timeout was reached before node was joined. Attempt to join the cluster will continue in the background. Use "docker info" command to see the current Swarm status of your node."

Once the timeouts start occurring all subsequent "join" operations will timeout. The bit about joining the cluster in the background never happens. After some time passes...

```
$ docker node ls
ID                           NAME       MEMBERSHIP  STATUS  AVAILABILITY  MANAGER STATUS
7x61vkrngwq0m192vylj778lf *  manager-1  Accepted    Ready   Active        Leader
9n98tunl0e8hci22x7bvi1fxq    manager-2  Accepted    Ready   Active        Reachable
```

**Describe the results you expected:**

A three manager three worker cluster should be created without timeouts.

**Additional information you deem important (e.g. issue happens only occasionally):**

$ docker-machine version
docker-machine version 0.8.0-rc1, build fffa6c9

**Comment by ginkel** [comment]
@raykrueger Do your VMs use multiple network interfaces? As you are using VirtualBox, you'll need a host-only network for VM-to-VM communication that is typically bound to `eth1` if you are using Vagrant.

Specify via `--listen-addr` during `init` and `join`.

**Comment by raykrueger** [comment]
Thanks @ginkel, listen-addr was the key. Which makes sense now since it all broke when I added the second manager. Everything else was joining using the first manager ip, but nobody could talk to the second manager.

Here's the modified script that works great...

```
#!/usr/bin/env bash

docker-machine create -d virtualbox manager-1
manager_ip=$(docker-machine ip manager-1)

echo "--- Swarm Init"
docker-machine ssh manager-1 docker swarm init --listen-addr ${manager_ip} --auto-accept manager --auto-accept worker


for n in {2..3} ; do
	docker-machine create -d virtualbox manager-${n}
	echo "--- Swarm Manager Join"
	docker-machine ssh manager-${n} docker swarm join --listen-addr $(docker-machine ip manager-${n}) --manager ${manager_ip}:2377
done

for n in {1..3} ; do
	docker-machine create -d virtualbox worker-${n}
	echo "--- Swarm Worker Join"
	docker-machine ssh worker-${n} docker swarm join ${manager_ip}:2377
done

echo 'eval $(docker-machine env manager-1)'
```

**Comment by cpuguy83** [comment]
Note that the current method for auto-detecting a listen addr is a bit too magical, we're working on it to 1) be smarter, and 2) force the use of a --listen-addr flag when it can't make a reasonable determination of what to use.

**Comment by cpuguy83** [comment]
Closing since this is not really an issue and is also being worked on in both swarmkit and docker engine.

**Comment by raykrueger** [comment]
Yep, thanks @cpuguy83 I hit the wrong button :)

**Comment by coderjiang** [comment]
Tanks @cpuguy83
