### ISSUE TITLE
Docker daemon memory usage when running many short lived containers

### ISSUE THREAD

**Issue by lukaf** [docker/docker#24420]
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:39 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:39 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 5
 Running: 3
 Paused: 0
 Stopped: 2
Images: 4
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.5.0-0.bpo.2-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.956 GiB
Name: scriptor-16018
ID: CIOO:PXZ6:XUDD:IYB3:JG57:VW7I:OOOO:NUR7:UTIN:ISDF:LWS4:735T
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Username: ...
Registry: ....
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS, t2.small instance, HVM

**Steps to reproduce the issue:**
1. Run many short lived containers

**Describe the results you received:**
Over time (roughly 2 days) Docker daemon consumes too much memory and is unable to create new containers.

**Describe the results you expected:**
Docker daemon shouldn't consume so much memory.

**Additional information you deem important (e.g. issue happens only occasionally):**

Continuously creating, starting and removing short lived containers causes Docker daemon to consume more and more memory. Graph shows a period of 24h where we had to restart (drops) some daemons to keep the service alive.

![docker-daemon-memory](https://cloud.githubusercontent.com/assets/1035695/16659602/c36b7dd8-4462-11e6-885f-e7581d650119.png)

Service runs roughly 3-6 short lived (max 15s) per second.

I've managed to reproduce it with https://gist.github.com/lukaf/e072f516bf118bafb6af3c7c94e72d1b
The script is quite aggressive and should be run in a resource limited VM. I've used t2.micro.
It also needs `alpine:latest` image present on the system.

**Comment by thaJeztah** [comment]
ping @crosbymichael @tonistiigi @unclejack PTAL

**Comment by cpuguy83** [comment]
Thanks for the investigation! We just merged an update to go-patricia which hopefully resolves the issue you reported. Please let us know! You can grab a pre-built binary @ https://master.dockerproject.org though (might want to check the commit sha to make sure the binary contains the commit).

**Comment by lukaf** [comment]
Hi,

Tested with docker-1.13.0-dev-tgz from https://master.dockerproject.org and it behaves much, much better. Memory usage still increases but in a much saner rate.

Thanks!

**Comment by cpuguy83** [comment]
@lukaf Thanks for confirming, and the detailed report!
