### ISSUE TITLE
[Docs] deprecated.md broken link

### ISSUE THREAD

**Issue by joaofnfernandes** [docker/docker#24428]
The [deprecated.md](https://github.com/docker/docker/blob/b98ba9a1d66d9b82eec510fb60a1ff7d7f2e7b0f/docs/deprecated.md) page is linking to the Github v1.12.0 release page, but that tag doesn't exist yet. Only v1.12.0-rc*

Replace the link by a valid one like the [v1.12.0-rc3](https://github.com/docker/docker/releases/tag/v1.12.0-rc3)

**Comment by thaJeztah** [comment]
At the time those docs were written, we didn't know yet that docs would be published before GA release; not sure if we should fix this, or just "know" that they're temporarily broken

**Comment by joaofnfernandes** [comment]
I think that if a user clicks on one of those links they we'll get surprised.
I've created  PR #24471 to fix this, and later we can make the link point to the GA tag when it gets released.

**Comment by thaJeztah** [comment]
The point is that RC4 is going to be released next week, RC5 possibly a week later, so I'm not sure it's worth updating each time

**Comment by joaofnfernandes** [comment]
I don't think we need to update it each time. It's better having it pointing to an older RC than sending the user to a 404.

**Comment by SvenDowideit** [comment]
see my suggestion in #24471 - link to https://github.com/docker/docker/releases/
