### ISSUE TITLE
Proposal: Replace secrets with "join tokens"

### ISSUE THREAD

**Issue by aaronlehmann** [docker/docker#24430]
Now that #24349 has been merged, we will generate a secret if none is specified by default. However, users can also specify their own secrets. Because of this, it's possible for users to choose a weak secret, or a potentially sensitive secret such as a password used elsewhere. The way that a secret can be either generated or specified is odd, and has some negative implications (currently, we hash the secrets to protect them, so we can't retrieve them after the fact).

As discussed with @aluzzardi and @diogomonica, we think it's better to avoid user-specified secrets and only use automatically generated "join tokens". Then we can more safely store them in plaintext and expose them them through the API/CLI.

This would include the following changes:

- Rename "secret" to "join token". This makes their purpose clearer, and will avoid confusion with actual application-level secrets when we add support for those.
- `docker swarm init` always generates a secret unless `--no-join-token` is specified. It is not possible to specify a user-provided secret for node joining purposes.
- Join tokens will be stored in raft in plaintext so they can be retrieved when the admin wants to use the token to add a new node. However, we shouldn't put them in the `docker info` output because this goes into bug reports. So we would instead add a `docker swarm join-token` subcommand that allows easily scriptable retrieval of the token, and also options to rotate or clear the token.
- Use separate join tokens for workers and managers. The current Docker code uses the same token for both, but at the API level they are separately defined. By splitting them, we'll avoid the possibility of a rogue worker using the join token to add itself as a manager (though note that managers require manual approval by default).

Here is a mockup of how the UX would look:

```
# docker swarm init
Autodetected IP address 192.168.1.1. If this is not the address
where other swarm members will reach this node, recreate this cluster
with the --listen-addr option.

Generated new join tokens:
	worker: 4ao565v9jsuogtq5t8s379ulb
	manager: 2bs0rkz9iuws6zddqayngydrq

Swarm initialized: current node (4ttpzq1ekahoyt7b57m6053x2) is now a manager.

To add a worker to this swarm, run the following command:
  docker swarm join --secret 4ao565v9jsuogtq5t8s379ulb
  --ca-hash sha256:b7986d3baeff2f5664dfe350eec32e2383539ec1a802ba541c4eb829056b5f61 \
  192.168.1.1:2377

# docker swarm join-token
worker: 4ao565v9jsuogtq5t8s379ulb
manager: 2bs0rkz9iuws6zddqayngydrq

# docker swarm join-token --worker  # for easier scripting
4ao565v9jsuogtq5t8s379ulb

# docker swarm join-token --manager  # for easier scripting
2bs0rkz9iuws6zddqayngydrq

# docker swarm join-token --rotate=worker,manager
Generated new join tokens:
	worker: 6jb4d5v9j8uagtq5t8s3v9ule
	manager: 1bshrkh2iuws6addqa3ngydr6

# docker swarm join-token --clear=worker,manager  # swarm no longer requires a token to join
```

ping @diogomonica @aluzzardi @tonistiigi @icecrime @cpuguy83 @dnephin @stevvooe @tiborvass

**Comment by diogomonica** [comment]
Maybe we an do a `docker swarm join-token command` that prints out the whole join command (also receives `--worker` and `--manager`.

**Comment by tonistiigi** [comment]
One reason why this is bit worse is that it makes bootstrapping clusters with scripts harder. Now you would have to talk to multiple machines to join a node while before user could make up a secret and then pass the same secret to all nodes without parsing their response or doing synchronization.

I know we have limited time but if we choose to do this, how hard would it be to add expiration time to the tokens?

**Comment by diogomonica** [comment]
What if we allow setting the secret on `init`, but always generate it for the user later on?

**Comment by aaronlehmann** [comment]
cc @sfsmithcha

**Comment by diogomonica** [comment]
ping we need to move this forward /cc @aluzzardi

**Comment by aaronlehmann** [comment]
What about supporting both user-provided and automatically generated join tokens? User-provided tokens would be stored bcrypted, and generated ones would be stored in cleartext to support retrieval through the API.

**Comment by diogomonica** [comment]
I'm down with that.

**Comment by aaronlehmann** [comment]
Any concerns or suggestions for improvements, anyone? Should we move forward with a PR to do this?

**Comment by aaronlehmann** [comment]
In terms of UX, I think it would be similar to the issue description above, but also with a `--set` flag for `join-token`, and a `--join-token` flag for `swarm init`.

Is the `join token` name okay, or should we stick with `join secret` since there's a possibility of the token being a user-created password?

**Comment by thaJeztah** [comment]
I'd go for "join token"; that also makes more clear to the user what they need to generate

**Comment by diogomonica** [comment]
`join token` 👍

**Comment by tiborvass** [comment]
Here's the conclusion we came up with. Please let me know if you disagree on certain points.

1. remove `swarm join --manager` from both CLI and API
2. remove `--auto-accept` from `swarm init`, `swarm update` and `node accept`
3. remove `--secret` from `swarm init` and `swarm update`
4. `swarm join --secret` becomes `swarm join --token`
5. remove CA hash and token from `docker info` and the spec
6. remove `--ca-hash` from `swarm join`
7. imperative command for rotate token
8. new `docker swarm join-token [--rotate] (manager|worker)` subcommand:
 - `docker swarm join-token worker` retrieves the worker token
 - `docker swarm join-token manager` retrieves the manager token
 - `--rotate` rotates the token
 - `docker swarm join-token --rotate` errors out because ROLE is required
9. `swarm update --secret` is replaced by the use of `docker swarm join-token`

cc @aaronlehmann @diogomonica @stevvooe @aluzzardi @icecrime @mgoelzer

**Comment by thaJeztah** [comment]
does `swarm join --token [manager-token]` joins as manager? (re: https://github.com/docker/docker/issues/24084, and https://github.com/docker/docker/issues/24596)

**Comment by cpuguy83** [comment]
`docker swarm join-token` is pretty atrocious, I'd say `docker token` if it wasn't so generic.
maybe `docker swarm rotate --join-token`

**Comment by aaronlehmann** [comment]
> does swarm join --token [manager-token] join as manager?

Affirmative.

> maybe docker swarm rotate --join-token

What would print the tokens?

**Comment by cpuguy83** [comment]
@aaronlehmann At the moment, `docker swarm inspect` does.

**Comment by aaronlehmann** [comment]
`docker swarm inspect` is being removed: #24492

I think it's useful to have a mechanism to just print one of the tokens, for scriptability. It's much harder to parse the output of a command that dumps a bunch of information.

**Comment by stevvooe** [comment]
@cpuguy83 The syntax proposed by @tiborvass  correctly represents the behavior. `docker swarm join-token` makes it clear that this command is to retrieve a token for joining and doesn't try to conflate with other things. It also signals that this should only be run by the manager.

**Comment by tonistiigi** [comment]
> remove CA hash and token from docker info and the spec
remove --ca-hash from swarm join

Does token contain ca-hash?

**Comment by adambarthelson** [comment]
I see this did not include the `docker swarm join-token --clear=worker,manager` functionality originally suggested by @aaronlehmann.  This would be useful when trying to provision a Docker Swarm via Terraform.
