### ISSUE TITLE
[1.12.0-rc2] Number of replicas is weird after a node leaves

### ISSUE THREAD

**Issue by npcode** [docker/docker#24437]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   4849709-unsupported
 Built:        Wed Jun 29 03:58:10 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 33
 Running: 7
 Paused: 0
 Stopped: 26
Images: 39
Server Version: 1.12.0-rc2
Storage Driver: overlay
 Backing Filesystem: xfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
 Authorization: authz-broker
Swarm: active
 NodeID: 3mwu45a5978s9o4ha2poik3nh
 IsManager: Yes
 Managers: 1
 Nodes: 3
 CACertHash: sha256:2c0398da3ddb366a410057286a837dfc42f74c322ba443f2637519539440117f
Runtimes: default
Default Runtime: default
Security Options: seccomp
Kernel Version: 3.10.0-327.13.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.788 GiB
Name: manager1
ID: 3KVC:FKMT:OUGV:AHY3:52NQ:3ECG:GYZJ:TFEZ:6QL6:W7ZJ:5DVX:F7ZN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: npcode
Registry: https://index.docker.io/v1/
Labels:
 provider=generic
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

3 physical machines

**Steps to reproduce the issue:**

1. Create a docker cluster with 1 manager and 2 workers using swarm mode of docker 1.12.

2. Create a redis service with 5 replicas.

     `docker service create --replicas 5 --name redis redis`

3. A worker node leaves the cluster

      `docker -H worker1:2376 swarm leave`

4. See the number of replicas of the redis service

      `docker service ls`

**Describe the results you received:**

9/5

**Describe the results you expected:**

5/5

**Additional information you deem important (e.g. issue happens only occasionally):**

The number still be weird 9/5 even after the worker node joined again.

**Comment by cpuguy83** [comment]
Did you mix up `received` and expected? If not I'm not sure what's wrong here.
If you specify 5 replicas, it should always be 5 or on its way to 5.

**Comment by npcode** [comment]
@cpuguy83 Oops, you're right. I've updated it.

**Comment by cpuguy83** [comment]
Ok, then that is indeed weird! Thanks for the report.

**Comment by abronan** [comment]
@npcode Thanks for the report. I cannot reproduce on `master` or `rc3`. I see that you are using `rc2`. Would you mind updating to `rc3` and giving it a try to see if the problem still exists?

Amongst that, additional questions:

- Does this happens systematically if you reproduce this scenario? Or only occasionally?
- Is this only a problem with the replicas counter or do you actually see 9 instances of redis running if you `docker ps` on the remaining nodes?
- When you `docker swarm join` the worker again, the counter stays inconsistent but does this still keeps the same amount of tasks running? (again with `docker ps` on the nodes)

**Comment by npcode** [comment]
@abronan I've tried it again with rc3 and still reproduce it.

1. I create a `nginx` service with `replicas=5`. Two tasks are running in `manager1`, one in `worker1` and two in `worker2`.

    ```
$ docker service ls
ID            NAME   REPLICAS  IMAGE  COMMAND
ckr2w4bzilej  nginx  5/5       nginx  
$ docker service tasks nginx
ID                         NAME     SERVICE  IMAGE  LAST STATE          DESIRED STATE  NODE
a1z987myfbarq2l5ocnx5hz3x  nginx.1  nginx    nginx  Running 13 minutes  Running        manager1
eudlwfk19hgowioq2rmbesskf  nginx.2  nginx    nginx  Running 13 minutes  Running        worker1
4f678ns4mka0wemt5089l4bye  nginx.3  nginx    nginx  Running 13 minutes  Running        worker2
bbhf91e7qzjtcrhrqzfmqlgxn  nginx.4  nginx    nginx  Running 13 minutes  Running        worker2
cua88rlln2krlo2pj1pqchqra  nginx.5  nginx    nginx  Running 13 minutes  Running        manager1
```

2. `worker2` leaves the cluster. The two tasks in `worker2` are removed from the service and two tasks are created in `worker1` instead. Now the service has 2 tasks in `manager1` and 3 tasks in `worker1`. `worker2` has no container.
    ```
$ docker service ls
ID            NAME   REPLICAS  IMAGE  COMMAND
ckr2w4bzilej  nginx  7/5       nginx  
$ docker service tasks nginx
ID                         NAME     SERVICE  IMAGE  LAST STATE           DESIRED STATE  NODE
a1z987myfbarq2l5ocnx5hz3x  nginx.1  nginx    nginx  Running 13 minutes   Running        manager1
eudlwfk19hgowioq2rmbesskf  nginx.2  nginx    nginx  Running 13 minutes   Running        worker1
0j4k2zoxxccuw6xqniv46q5t3  nginx.3  nginx    nginx  Preparing 9 seconds  Running        worker1
bada39cx32o1lffsbxpl1r8zn  nginx.4  nginx    nginx  Preparing 9 seconds  Running        worker1
cua88rlln2krlo2pj1pqchqra  nginx.5  nginx    nginx  Running 13 minutes   Running        manager1
$ eval $(docker-machine env worker2)
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

3. `worker2` joins the cluster again but nothing has changed.

   ```
$ docker service ls
ID            NAME   REPLICAS  IMAGE  COMMAND
ckr2w4bzilej  nginx  7/5       nginx  
$ docker service tasks nginx
ID                         NAME     SERVICE  IMAGE  LAST STATE          DESIRED STATE  NODE
a1z987myfbarq2l5ocnx5hz3x  nginx.1  nginx    nginx  Running 45 minutes  Running        manager1
eudlwfk19hgowioq2rmbesskf  nginx.2  nginx    nginx  Running 45 minutes  Running        worker1
0j4k2zoxxccuw6xqniv46q5t3  nginx.3  nginx    nginx  Running 31 minutes  Running        worker1
bada39cx32o1lffsbxpl1r8zn  nginx.4  nginx    nginx  Running 31 minutes  Running        worker1
cua88rlln2krlo2pj1pqchqra  nginx.5  nginx    nginx  Running 45 minutes  Running        manager1
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

Here is my answers for your questions:

> Does this happens systematically if you reproduce this scenario? Or only occasionally?

It happens always if I remove a node which has some tasks.

> Is this only a problem with the replicas counter or do you actually see 9 instances of redis running if you docker ps on the remaining nodes?

It is only a problem with the counter. Actually I have 5 instances.

> When you docker swarm join the worker again, the counter stays inconsistent but does this still keeps the same amount of tasks running? (again with docker ps on the nodes)

It still keeps the same amount of tasks running.

**Comment by npcode** [comment]
It works fine with latest master! (602f1c02d9c4d1838ada9e3ad60559defc5f38ca)

**Comment by npcode** [comment]
It seems to be a problem of docker v1.12.0-rc2 client.

rc2 client + master server = weird
master client + master server = fine

**Comment by thaJeztah** [comment]
Thanks @npcode, good to hear it's resolved

**Comment by abronan** [comment]
Awesome! Thanks for your help @npcode
