### ISSUE TITLE
[1.12] evaluate new single-letter flags before GA

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#24433]
With the SwarmKit integration, many new commands and options were added; we should be careful when adding shorthand (single-letter) flags to commands, and only use shorthand flags for frequently used options.

In doubt; remove the shorthand flag, so that we can decide later when really needed.

Opening this issue so that we don't forget to evaluate all new flags before GA

**Comment by vdemeester** [comment]
Here is a list of short flags, along with the command, the long flag version and a *quick consistency check* with other docker command.

| Command | Short flag | Long flag | Consistency |
|---|---|---|---|---|---|
| `node inspect` | `-f` | `--format` | yes (`docker inspect`) |
| `node inspect` | `-p` | `--pretty` | no, see #24122 && #24148 |
| `node ls` | `-f` | `--filter` | yes (`docker ps`) |
| `node ls` | `-q` | `--quiet` | yes (`docker ps`) |
| `node tasks` | `-a` | `--all` | yes (`docker ps`) |
| `node tasks` | `-f` | `--filter` | yes (`docker ps`) |
| `node tasks` | `-n` | `--no-resolve` | no, `-n` means `--last` in `docker ps` |
| `service create` | `-e` | `--env` | yes (`docker run`) |
| `service create` | `-l` | `--label` | yes (`docker run`) |
| `service create` | `-m` | `--mount` | no, `-m` means `memory` for `docker run` |
| `service create` | `-p` | `--publish` | yes (`docker run`) |
| `service create` | `-u` | `--user` | yes (`docker run`) |
| `service create` | `-w` | `--workdir` | yes (`docker run`) |
| `service inspect` | `-f` | `--format` | yes (`docker inspect`) |
| `service inspect` | `-p` | `--pretty` | no, see #24122 && #24148 |
| `service ls` | `-f` | `--filter` | yes (`docker ps`) |
| `service ls` | `-q` | `--quiet` | yes (`docker ps`) |
| `service tasks` | `-a` | `--all` | yes (`docker ps`) |
| `service tasks` | `-f` | `--filter` | yes (`docker ps`) |
| `service tasks` | `-n` | `--no-resolve` | no, `-n` means `--last` in `docker ps` |
| `service update` | `-e` | `--env` | yes (`docker run`) |
| `service update` | `-l` | `--label` | yes (`docker run`) |
| `service update` | `-m` | `--mount` | no, `-m` means `memory` for `docker run` |
| `service update` | `-p` | `--publish` | yes (`docker run`) |
| `service update` | `-u` | `--user` | yes (`docker run`) |
| `service update` | `-w` | `--workdir` | yes (`docker run`) |

Overall, there is not that much, and most of them seems consistent with current cli. I think the main question are for :
- `-m`/`--mount` on `service create/update`
- `-p`/`--pretty` on `inspect` commands (note that, I do agree with @cpuguy83 on #24122 on the fact that `pretty` should be a format, and we could use `--format=pretty`).
- `-n`/`--no-resolve` on `node/service tasks` commands.

**Comment by thaJeztah** [comment]
Wow, this is awesome; thanks so much Vincent!

**Comment by mgoelzer** [comment]
ping @sfsmithcha

**Comment by thaJeztah** [comment]
I think we should remove the `-m`, `-p` and `-n` flags, and adding a `--file` for `stack deploy`. Especially the `-m` for `service create`, because people would expect this to be `--memory`

**Comment by thaJeztah** [comment]
Actually, looks like we picked `--bundle` as long flag for `stack deploy`, which may be really confusing;

```
 -f, --bundle string   Path to a Distributed Application Bundle file (Default: STACK.dab)
```
