### ISSUE TITLE
[after docker commit] Value too large for defined data type

### ISSUE THREAD

**Issue by yanren** [docker/docker#24436]
1. docker info:
Containers: 9
 Running: 7
 Paused: 0
 Stopped: 2
Images: 25
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.12.49-11-default
Operating System: SUSE Linux Enterprise Server 12 SP1
OSType: linux
Architecture: x86_64
CPUs: 120
Total Memory: 1010 GiB
Name: lsvxc0122
ID: GMRJ:7TQH:TECA:G2KE:V7ES:F3OO:AJH4:PBPL:4T74:HZKQ:Y6DB:NUP3
Docker Root Dir: /var/lib/docker

2. docker version:
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64

issue: 
step1: start a container using my base image then call open() to open a file(5.9G) ok. 
step2: call docker commit to save the above container to a new image
step3: call open() to open the file(5.9G, same as the step1) fail. 
open("/quasrspace/pd102290/partition1.dat", O_RDWR|O_DSYNC) = -1 EOVERFLOW (Value too large for defined data type)

my docker base image is x86_64 system.  why after docker commit is executed, the system can't open large file.  it is wired.  
can you kindly tell me the reason. how to fix it or is there a good work around ? 

thanks in advance.

**Comment by yanren** [comment]
add info:
maybe it is related to filesystem.  I found that,  although the base image is x86_64, but if the docker storage drive use overlay, getconf FILESIZEBITS is 32, if the vfs is used, it will be 64. 

I wonder if the FILESIZEBITS is set to 32 when overlay is used. is there any way to fix it ? thanks

**Comment by yanren** [comment]
any ideas?

**Comment by justincormack** [comment]
That doesn't make much sense to me, `FILESIZEBITS` is a userspace issue not a filesystem issue. Is there any way you can provide a way for me to replicate this easily?

**Comment by thaJeztah** [comment]
Closing as we need a way to reproduce, but happy to reopen once provided
