### ISSUE TITLE
Dockerfile RUN mv not affect

### ISSUE THREAD

**Issue by polym** [docker/docker#24442]
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 37
 Running: 9
 Paused: 0
 Stopped: 28
Images: 56
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.6.0-1.el6.elrepo.x86_64
Operating System: <unknown>
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 125.9 GiB
Name: ******
ID: SA4M:5YPV:GCQE:OLJS:424F:POSR:5KMK:PNRY:LJGP:IJTT:4J5C:LR5P
Docker Root Dir: /disk/ssd1/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. docker build -t foo .
2. docker run -it foo /bin/bash
3. cat config.py

> Dockerfile

```
FROM centos:6

ADD config.pro.py /config.pro.py
ADD config.py /config.py

RUN mv config.pro.py config.py
```

**Describe the results you received:**
Not change

**Describe the results you expected:**
Need change

**Additional information you deem important (e.g. issue happens only occasionally):**

1. install docker using static binary.
2. other docker version no such problem.
3. changing config.py or config.pro.py won't reproduce this problem.

[funny.tar.gz](https://github.com/docker/docker/files/353902/funny.tar.gz)

**Comment by AkihiroSuda** [comment]
I wonder if the issue is related to https://github.com/docker/docker/issues/21555 because config.py and config.pro.py have identical file sizes and timestamps.

@polym Do you hit the issue deterministically?

**Comment by dmcgowan** [comment]
If it is hitting #21555, which I suspect it is, then `overlay2` does resolve it.

**Comment by thaJeztah** [comment]
I'll go ahead and close this as a duplicate of https://github.com/docker/docker/issues/21555. For Docker 1.12, you can try using the `overlay2` storage driver (but be aware that it'll use a separate storage path, so you won't see your existing images/containers, nor will they be cleaned up)

**Comment by polym** [comment]
Maybe it's a duplicate of #21555. 

BTW, is it equal to above?

```
FROM centos:6

ADD . /

RUN mv config.pro.py config.py
```
