### ISSUE TITLE
GCE Not using already pulled images and errors during pull

### ISSUE THREAD

**Issue by charliekump-wf** [docker/docker#24456]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   91e29e8
 Built:        Sat Jul  2 00:15:19 2016
 OS/Arch:      linux/amd64
 Experimental: true
Server:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   91e29e8
 Built:        Sat Jul  2 00:15:19 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Server Version: 1.12.0-rc3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 29
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay host bridge
Swarm: active
 NodeID: 0pu0lj4cqvgdsmwr1s0sbi4s1
 IsManager: Yes
 Managers: 1
 Nodes: 1
 CACertHash: sha256:102744b06372a3f1d5ed9cfbf2ffa81861227b3007c74f9342a31f54fcfea202
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.625 GiB
Name: bender-swarm
ID: T7SC:YJT6:PHF5:IFJZ:UW5S:GFLK:XTHV:FNGA:OUBC:GPNQ:FF5Y:HY4R
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on Google Container Engine

**Steps to reproduce the issue:**
1. docker login <private registry>
2. docker pull image <- works fine
3. docker service create --registry-auth -e \<env_file> --name \<service> image:tag
4. Service spins up, but containers cannot spin up. Even if image already available. 

**Describe the results you received:**
level=error msg="Error trying v2 registry: error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: \"<!DOCTYPE HTML PUBLIC \\\"-//W3C//DTD HTML 3.2 Final//EN\\\">\\n<title>404 Not Found</title>\\n<h1>Not Found</h1>\\n<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>\\n\""

level=error msg="Attempting next endpoint for pull after error: error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: \"<!DOCTYPE HTML PUBLIC \\\"-//W3C//DTD HTML 3.2 Final//EN\\\">\\n<title>404 Not Found</title>\\n<h1>Not Found</h1>\\n<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>\\n\""

level=error msg="Not continuing with pull after error: unauthorized: authentication required"
level=error msg="pulling image failed" error="unauthorized: authentication required"
level=error msg="fatal task error" error="No such image: <image:tag>"

**Describe the results you expected:**
Expect image used if available or pulls using same credentials successfully. I feel like this just became an issue this week as I was successfully starting up the service early the week prior.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
note that "always pulling" is by design, but there's a discussion on "pinning" to the version that was used when the service is created the first time

**Comment by thaJeztah** [comment]
ping @nishanttotla @stevvooe

**Comment by tonistiigi** [comment]
@charliekump-wf What registry/image are you using to test this? Are you using only one node or could it be that the node that runs the container has different `--insecure-registry/--disable-legacy-registry/mirror` setup or can't reach the registry hostname same way as the main manager.

> I feel like this just became an issue this week as I was successfully starting up the service early the week prior.

`--registry-auth` was added in `rc3`, July 1st.

**Comment by charliekump-wf** [comment]
I had 3 nodes, but cut down to one until I could figure out the issue. It's a private v1 registry although I tried our v2 and it has the same issue. The last statement was without the --registry-auth but I wanted to demonstrate that I had tried that solution.

**Comment by tiborvass** [comment]
@charliekump-wf might just be a typo but `docker service create --registry-auth -e --name image:tag` seems wrong there's a dangling `-e` without a value, or more precisely `--name` is the environment variable anyway it's probably unrelated.

**Comment by charliekump-wf** [comment]
@tiborvass Apparently I have to escape <string> in the summaries... updated. It should read:

docker service create --registry-auth -e <env_file> --name <service> image:tag

**Comment by tonistiigi** [comment]
@charliekump-wf Can you post the full daemon logs and the specific image name. I wonder if the image name gets corrupted for some reason and request to pull goes to a wrong address. If you can, please post registry logs also. If you can reproduce this with v2 registry and without authorization, then this would be simplest for us to debug.

**Comment by charliekump-wf** [comment]
I'm seeing different information in the log with rc4. So I'll get all that info for you as soon as I can.

**Comment by tiborvass** [comment]
@charliekump-wf any news?

**Comment by charliekump-wf** [comment]
@tiborvass I'm starting to suspect something happened internally as I just attempted to run again on rc2 with the same setup that had worked for me prior and I'm seeing the same auth issue:

```
time="2016-07-19T14:33:03.428246640Z" level=debug msg="hostDir: /etc/docker/certs.d/docker.webfilings.org"
time="2016-07-19T14:33:03.428322187Z" level=debug msg="attempting v1 ping for registry endpoint https://docker.webfilings.org/v1/"
time="2016-07-19T14:33:03.767034514Z" level=debug msg="Error unmarshalling the _ping PingResult: json: cannot unmarshal bool into Go value of type registry.PingResult"
time="2016-07-19T14:33:03.767067615Z" level=debug msg="Registry version header: '0.6.7'"
time="2016-07-19T14:33:03.767074332Z" level=debug msg="PingResult.Version: \"0.6.7\""
time="2016-07-19T14:33:03.767080657Z" level=debug msg="Registry standalone header: 'True'"
time="2016-07-19T14:33:03.767086818Z" level=debug msg="PingResult.Standalone: true"
time="2016-07-19T14:33:03.767095056Z" level=debug msg="Endpoint https://docker.webfilings.org/v1/ is eligible for private registry. Enabling decorator."
time="2016-07-19T14:33:03.767115742Z" level=debug msg="[registry] Calling GET https://docker.webfilings.org/v1/repositories/charliekump/bender/images"
time="2016-07-19T14:33:03.767430927Z" level=debug msg="pull progress map[status:Pulling repository docker.webfilings.org/charliekump/bender]"
time="2016-07-19T14:33:04.158172808Z" level=error msg="Not continuing with pull after error: unauthorized: authentication required"
time="2016-07-19T14:33:04.158220627Z" level=error msg="pulling image failed" error="unauthorized: authentication required" module=taskmanager task.id=e8k2n7s7a9onlcc4ju46pzr04
```

**Comment by thaJeztah** [comment]
@charliekump-wf could it be that the login token has expired?

**Comment by thaJeztah** [comment]
this looks weird

     Error unmarshalling the _ping PingResult: json: cannot unmarshal bool into Go value of type registry.PingResult

**Comment by charliekump-wf** [comment]
I did a fresh login prior to attempting the service create. (shrug)

**Comment by tonistiigi** [comment]
@charliekump-wf `rc2` does not support `--registry-auth` and therefore private images.

**Comment by charliekump-wf** [comment]
@tonistiigi Yeah, believe I was logging in and pulling manually on the nodes to set it up, but it did work with private images (without the flag that obviously didn't exist). One of our DevOps guys has got it working locally on rc4 so I'm going to start from scratch as I believe it's on my end. I would consider this closed for the time being.

**Comment by tonistiigi** [comment]
@charliekump-wf Thanks. Please report back if you still see some issues with `rc4+`
