### ISSUE TITLE
cannot access remote docker service

### ISSUE THREAD

**Issue by awolde** [docker/docker#24454]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   91e29e8
 Built:        Sat Jul  2 00:40:04 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   91e29e8
 Built:        Sat Jul  2 00:40:04 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 72
Server Version: 1.12.0-rc3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 87
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay host bridge null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 3.13.0-74-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.769 GiB
Name: OptiPlex-3010
ID: TR53:7LKT:3BYR:4GVH:NOB2:NBCL:XRY2:GQWS:2M77:XBQU:DNTH:54AY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running docker on physical box on Ubuntu 14

**Steps to reproduce the issue:**
1. I ran ```sudo docker-containerd --listen tcp://0.0.0.0:2375 --shim docker-containerd-shim --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --runtime docker-runc --debug``` to access docker from another machine.
2. Exported the docker host on my laptop: DOCKER_HOST=tcp://desktop:2375. Tried docker ps, received ```Get http://desktop:2375/v1.24/containers/json: malformed HTTP response "\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x04\b\x00\x00\x00\x00\x00\x00\x0e\xff\xf1".
* Are you trying to connect to a TLS-enabled daemon without TLS? ```
3. Got the error on the docker machine - ```2016/07/08 11:59:35 transport: http2Server.HandleStreams received bogus greeting from client: "GET /v1.24/containers/js"```

**Describe the results you received:**

**Describe the results you expected:**
Was able to run docker remotely from my laptop to desktop before the 1.12. Isn't this feature no longer supported?

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
can you check if you still have `DOCKER_TLS_VERIFY` and/or `DOCKER_CERT_PATH` environment variables set? Looks like you're trying to connect to a non-TLS API, but docker may be trying to connect with a TLS connection

**Comment by thaJeztah** [comment]
I'm closing this issue, because I suspect there's an issue with your configuration, and I don't think there's a bug here, but feel free to continue the discussion
