### ISSUE TITLE
/etc/hosts being populated with task in some cases

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#24457]
While trying to repro a cn issue I stumbled across this:

```
$ docker network create -d overlay test
$ docker service create --network test busybox top
$ docker run -d --name test busybox top
$ docker network connect test test
```

Once the `test` container is attached to the `test` network, the service task's addr/name is populated in `/etc/hosts` for the `test` container.

Also strange that `network connect` works here when `docker run --net test` fails.

**Comment by thaJeztah** [comment]
@cpuguy83 did you look into this issue? I removed this from the milestone, but feel free to add to 1.12.1 if you think it's important

**Comment by mavenugo** [comment]
@cpuguy83 @thaJeztah we have blocked `network connect` for swarm-mode networks in RC5.

**Comment by thaJeztah** [comment]
@mavenugo Ah, you're right; it's in the test container, so no issue anymore
