### ISSUE TITLE
swarm mode manager nodes cannot run on dynamic IP addresses

### ISSUE THREAD

**Issue by sfsmithcha** [docker/docker#24455]
this is a raft cluster, so there needs to be a quorum of nodes available for the cluster to function
if nodes have their address change at random, it will potentially disturb that quorum and be hard to recover from
in production you would ​*never*​ deploy this in a way where managers aren't reachable at a fixed address (or DNS name). but maybe we can come up with a hack for laptop use that makes it more usable.

**Comment by abronan** [comment]
BTW I think it can if we provide a hostname.

If the IP changes dynamically, raft retries to connect using this hostname and the new resolved IP and bounces connection to this new IP when it fails to process a call.

/cc @aaronlehmann can you confirm this and if this is the case with the changes on dynamic address resolution for raft? Thanks.

**Comment by aaronlehmann** [comment]
That's my understanding, but an admin would have to:

- Set up each node to advertise its respective hostname
- Run some kind of dynamic DNS to keep the hostnames pointing at current addresses

I haven't tested this kind of setup, and we should probably do that before making any kind of representation that it will work.

I think it should still be discouraged though, except perhaps for setups where it's hard to provision static IPs (cloud setups???).

**Comment by daviddyball** [comment]
@aaronlehmann I would've assumed that cloud deployments make up a very large chunk of potential users got a swarm cluster, no?

I'm not familiar with raft myself, but if there is any way to do hostname-based resolution, then that would go a a fair way towards solving the issue (even if dynamic IP updating is a pain).

**Comment by sfsmithcha** [comment]
Docs issue addressed here: https://github.com/docker/docker/commit/24f87f26e73a49383e0606813a86ed96da7f5a18
