### ISSUE TITLE
docker 1.12 swarm mode: how to connect to another container on overlay network? 

### ISSUE THREAD

**Issue by benheilers** [docker/docker#24466]
Sorry if this is a duplicate.  I feel like I'm asking a dumb question but I couldn't figure this out even with all the documentation and tutorials.  I think it would be great if the answer went into another page of [this tutorial](https://docs.docker.com/engine/swarm/swarm-tutorial/).

In docker 1.12.0-rc3 I set up 3 nodes in swarm mode and an overlay network.  

I notice the task names are predictably networktest.1, .2, .3:
```
$ docker service tasks networktest
ID                         NAME           SERVICE      IMAGE   LAST STATE         DESIRED STATE  NODE
d6naj58s8izkb822fpd4b6tl0  networktest.1  networktest  alpine  Running 4 seconds  Running        ip-172-31-47-32.us-west-2.compute.internal
7sglm20hhbmn1ws5fiqvqfgx5  networktest.2  networktest  alpine  Running 4 seconds  Running        ip-172-31-43-158.us-west-2.compute.internal
au4unlfyavw5y6vhodaw2dwe4  networktest.3  networktest  alpine  Running 4 seconds  Running        ip-172-31-43-158.us-west-2.compute.internal
```
but the container names have a random suffix:
```
[ec2-user@ip-172-31-47-32 ~]$ docker ps
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS                                  NAMES
e67110a596b0        alpine:latest                   "sleep 36000"            5 minutes ago       Up 5 minutes                                               networktest.1.d6naj58s8izkb822fpd4b6tl0
```

and
```
[ec2-user@ip-172-31-43-158 ~]$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
412ed90a1cd7        alpine:latest       "sleep 36000"       4 minutes ago       Up 3 minutes                            networktest.2.7sglm20hhbmn1ws5fiqvqfgx5
44ea273ba889        alpine:latest       "sleep 36000"       4 minutes ago       Up 3 minutes                            networktest.3.au4unlfyavw5y6vhodaw2dwe4
```

How are we then supposed to have container-to-container communication?

So giving that full randomly-generated name allows one container to ping another:
```
[ec2-user@ip-172-31-47-32 ~]$ docker exec -it e67110a596b0 ping networktest.2.7sglm20hhbmn1ws5fiqvqfgx5
PING networktest.2.7sglm20hhbmn1ws5fiqvqfgx5 (10.0.0.4): 56 data bytes
64 bytes from 10.0.0.4: seq=0 ttl=64 time=0.319 ms
64 bytes from 10.0.0.4: seq=1 ttl=64 time=0.236 ms
64 bytes from 10.0.0.4: seq=2 ttl=64 time=0.217 ms
```

*But* I really wish this worked too:
```
[ec2-user@ip-172-31-47-32 ~]$ docker exec -it e67110a596b0 ping networktest.2
ping: bad address 'networktest.2'
```

I didn't see any parameters to `docker service create` for `links`, so how do I configure one container to communicate with another? 

In [this blog](https://blog.docker.com/2016/06/docker-1-12-built-in-orchestration/) it implied the `frontend` and `redis` database would be connected with just the following commands. Was that misleading?
```
docker network create -d overlay mynet
docker service create --name frontend --replicas 5 -p 80:80/tcp --network mynet mywebapp
docker service create --name redis --network mynet redis:latest
```

**Comment by benheilers** [comment]
I think this might be a duplicate of https://github.com/docker/docker/issues/23901#issuecomment-231334702

If you could add this to the tutorial, it would be very helpful:

Start several instances of the hello-world container with:
```
$ docker service create --name helloworld --replicas 5 -p 80:80 --network mynet tutum/hello-world
```
Note that the *task* names are not pingable. The *container* names are pingable, but they contain a randomly generated suffix.  So if you need one service to integrate with another service within an overlay network, don't give up when you notice that `ping` doesn't work.  Instead, try `curl` against the service itself:
```
$ docker service create --name bash --network mynet ubuntu sleep 36000
$ docker service tasks bash
```

Now find the swarm node the container is running on and from there run the next command:
```
$ docker exec -it edb0b11d014c bash
root@edb0b11d014c:/# apt-get update
root@edb0b11d014c:/# apt-get install curl
```

Now still inside the container, pay attention to the output of `curl http://helloworld` to see a different container accessed each time.
```
root@edb0b11d014c:/# curl http://helloworld
root@edb0b11d014c:/# curl http://helloworld
```

**Comment by sfsmithcha** [comment]
thanks @benheilers the network portion of the tutorial is WIP

**Comment by mavenugo** [comment]
@benheilers its not a dupe of https://github.com/docker/docker/issues/23901. It works as designed so far.
If the intention is to have an ability to have container-to-container communication, then it works currently with the container-name (which has the randomly generated id as well). But your requirement is to have an ability to have the task-name `networktest.2` to be an `alias` of the container. I personally dont see a problem with that. @tonistiigi @icecrime @thaJeztah do you see a problem with it ? If not, it infact is a good enhancement to have task-name to be an alias of the container so that the containers can reach each other easily.

> In this blog it implied the frontend and redis database would be connected with just the following commands. Was that misleading?

Nope. It will work just as advertised. That's because containers can reach each other across services in the same network using the `service-name`. Service-name is mapped to a virtual-IP and is ultimately mapped to the correct container via built-in Load-balancer.

**Comment by thaJeztah** [comment]
@mavenugo having it as an alias SGTM, this may be relevant then as well though; https://github.com/docker/docker/issues/24241

**Comment by RangerMauve** [comment]
Having the task names as aliases would make setting up Replication with MongoDB less of a pain since it expects hard-coded hostnames.

**Comment by sfsmithcha** [comment]
Container to container networking addressed by:
e56dd0e0e7d2eb921390c7aaff091b8b613c4c6b

**Comment by ksachdev1** [comment]
I am not able to find documentation to figure out how to make this work. Any pointers on this?

**Comment by thaJeztah** [comment]
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For questions about _using_ docker, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

**Comment by adnapster** [comment]
@thaJeztah 
I wanted to connect to docker-swarm from VSTS and run docker images on UCP. Can you please tell me how can i do it ??

**Comment by thaJeztah** [comment]
@adnapster see my comment above
