### ISSUE TITLE
Starting Docker Daemon with splunk driver?

### ISSUE THREAD

**Issue by yelledbett** [docker/docker#24462]
**Output of `docker version`:**

# docker version
Client:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   91e29e8
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   91e29e8
 Built:
 OS/Arch:      linux/amd64

**Output of `docker info`:**

# docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 17
Server Version: 1.12.0-rc3
Storage Driver: devicemapper
 Pool Name: docker-253:5-4240324-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.356 GB
 Data Space Total: 107.4 GB
 Data Space Available: 2.657 GB
 Metadata Space Used: 2.765 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Logging Driver: splunk
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: active
 NodeID: 01wvn6tshmrw4crb8hxo4hkmx
 IsManager: Yes
 Managers: 2
 Nodes: 2
 CACertHash: sha256:efa0db601ff5de9e3ebbd727ab9a2283110dd617ad451122d29ac34d16e9b4c3
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.10.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.789 GiB
Name: dockerswarm03
ID: VKJ7:IHSB:R4ZF:T2SK:PN7P:KRNP:4KL5:KE44:XP2G:PFP7:KXT5:LVSP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: 
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Internal custom cloud automated RHEL7.2 build. 

**Steps to reproduce the issue:**
1. Change docker.service to include a splunk driver like this:
ExecStart=/usr/bin/dockerd --log-level="debug" --log-driver=splunk --log-opt splunk-token=xxxxxxxxxxxx --log-opt splunk-url=https://mysplunkservercom:8088 --log-opt splunk-insecureskipverify=true -H fd://
2. Reload (systemctl daemon-reload, systemctl restart docker)
3. Run any container: docker logs metrics
"logs" command is supported only for "json-file" and "journald" logging drivers (got: splunk)

**Describe the results you received:**
Daemon restarts but containers don't start because daemon is sending to splunk driver? 

**Describe the results you expected:**
Documentation seems to say you can start docker daemon with splunk driver on this link:
https://docs.docker.com/engine/admin/logging/splunk/

Daemon seems to restart ok!!?? If you cannot do this, fine, have the daemon fail on startup and fix the documentation. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment]
@yelledbett I'm not sure I understand the problem.
Setting these values on the daemon does nothing until you actually create a new container.

The `docker logs` command only works for the `json-file` and `journald` log drivers.

**Comment by yelledbett** [comment]
Yes but why does the documentation clearly state that you can start a daemon with the splunk driver?

https://docs.docker.com/engine/admin/logging/splunk/

I think the daemon should fail to restart if you have a log driver set other than json-file or journald. Instead it restarts but all containers fail when you start them. 

Does this make more sense?

**Comment by cpuguy83** [comment]
Why? The logging still works, you just can't read the logs using "docker logs".

**Comment by yelledbett** [comment]
If you start the docker daemon with the splunk log driver (which is not really a valid option contrary to the documentation) containers will no longer start at all! It wasn't readily apparent that it was caused by the invalid splunk log driver change.

**Comment by cpuguy83** [comment]
@yelledbett Can you provide some additional details, logs, etc?
Starting the daemon with the splunk driver is (or should be) a perfectly valid configuration.

**Comment by yelledbett** [comment]
Now it is acting a little different.. still not working though.

## Docker Daemon Startup Config (RHEL7)

**/etc/systemd/system/multi-user.target.wants/docker.service**

```
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target docker.socket
Requires=docker.socket

[Service]
Type=notify
# the default is not to use systemd for cgroups because the delegate issues still
# exists and systemd currently does not support the cgroup feature set required
# for containers run by docker
ExecStart=/usr/bin/dockerd -H fd:// --log-level="debug" --log-driver=splunk --log-opt splunk-token=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX --log-opt splunk-url=http://splunk.mycompany.com:8088 --log-opt splunk-insecureskipverify=true
ExecReload=/bin/kill -s HUP $MAINPID
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity
# Uncomment TasksMax if your systemd version supports it.
# Only systemd 226 and above support this version.
#TasksMax=infinity
TimeoutStartSec=0
# set delegate yes so that systemd does not reset the cgroups of docker containers
Delegate=yes
# kill only the docker process, not all processes in the cgroup
KillMode=process

[Install]
WantedBy=multi-user.target
```

systemctl daemon-reload
systemctl restart docker
docker start eff5

Stand alone containers are starting and working this time, but no docker daemon logs are going to splunk. Splunk received no events and everything still logging to journald. 

## Still logging to journald though

```
[root@dockerswarm01 ~]# journalctl -f
-- Logs begin at Tue 2016-07-12 07:01:48 EDT. --
Jul 13 10:08:14 dockerswarm01 dockerd[16088]: time="2016-07-13T10:08:14.532002469-04:00" level=info msg="dcaff69aa3f8a6d [logterm: 33, index: 66] sent vote request to 8e0c0c048f36580 at term 83391"
Jul 13 10:08:17 dockerswarm01 dockerd[16088]: time="2016-07-13T10:08:17.985983199-04:00" level=error msg="agent: session failed" error="rpc error: code = 2 desc = raft: no elected cluster leader" module=agent
Jul 13 10:08:17 dockerswarm01 dockerd[16088]: time="2016-07-13T10:08:17.986051636-04:00" level=debug msg="agent: rebuild session" module=agent
Jul 13 10:08:18 dockerswarm01 dockerd[16088]: time="2016-07-13T10:08:18.531861271-04:00" level=info msg="dcaff69aa3f8a6d is starting a new election at term 83391"
Jul 13 10:08:18 dockerswarm01 dockerd[16088]: time="2016-07-13T10:08:18.531917682-04:00" level=info msg="dcaff69aa3f8a6d became candidate at term 83392"
Jul 13 10:08:18 dockerswarm01 dockerd[16088]: time="2016-07-13T10:08:18.531952090-04:00" level=info msg="dcaff69aa3f8a6d received vote from dcaff69aa3f8a6d at term 83392"
Jul 13 10:08:18 dockerswarm01 dockerd[16088]: time="2016-07-13T10:08:18.531976771-04:00" level=info msg="dcaff69aa3f8a6d [logterm: 33, index: 66] sent vote request to 8e0c0c048f36580 at term 83392"
Jul 13 10:08:18 dockerswarm01 dockerd[16088]: time="2016-07-13T10:08:18.869330464-04:00" level=error msg="sending task status update failed" error="rpc error: code = 2 desc = raft: no elected cluster leader" module=agent
Jul 13 10:08:18 dockerswarm01 dockerd[16088]: time="2016-07-13T10:08:18.869398526-04:00" level=error msg="failed reporting status to agent" error="rpc error: code = 2 desc = raft: no elected cluster leader" module=agent
Jul 13 10:08:18 dockerswarm01 dockerd[16088]: time="2016-07-13T10:08:18.869431395-04:00" level=debug msg="(*Agent).UpdateTaskStatus" module=agent task.id=5ei4lkjvpsnd6jiotaou04zj7

```

**Comment by cpuguy83** [comment]
@yelledbett Docker does not send daemon logs to the provided log driver. Log drivers are for container logs.
When you set the log driver at the daemon level, you are specifying what the default log driver should be when you create a new container, not telling the daemon to send its own logs to that driver.

**Comment by yelledbett** [comment]
Thanks for the clarification. It seems to be working as designed then. Maybe this could be a nice flag to add in the future then. Would have been an easy monitoring strategy for the daemon in addition to the containers all in one fell swoop.

**Comment by cpuguy83** [comment]
Docker itself only logs to stdout/stderr, so this could be captured by some external process, and is why docker's logs show up in journald.
