### ISSUE TITLE
Minor typo in docs

### ISSUE THREAD

**Issue by arun-gupta** [docker/docker#24472]
On https://www.docker.com/products/docker#/mac, change `OS X native virtualization.,` to `OS X native virtualization.`

**Comment by thaJeztah** [comment]
oh! had to look twice; there's a stray comma in there

thanks! Let me try and find the right person for that

**Comment by hansfrederickbrown** [comment]
Fixed

**Comment by thaJeztah** [comment]
Thanks @hansfrederickbrown
