### ISSUE TITLE
[1.12.0-rc3] Push retries a number of times when pushing to ECR repositories that have not been created

### ISSUE THREAD

**Issue by sentientmonkey** [docker/docker#24473]
After upgrading from docker 1.12.0-rc2 to 1.12.0-rc3, if I push to repositories that do not exist in ECR, docker keeps retrying and does not return the name unknown error returned from the registry.

```
$ docker push 123456789012.dkr.ecr.us-east-1.amazonaws.com/busybox-2
The push refers to a repository [12345678901.dkr.ecr.us-east-1.amazonaws.com/busybox-2]
8ac8bfaff55a: Retrying in 10 seconds 

```
(keeps retrying over and over)

```
$ aws ecr create-repository --repository-name busybox
{
    "repository": {
        "registryId": "12345678901", 
        "repositoryName": "busybox", 
        "repositoryArn": "arn:aws:ecr:us-east-1:12345678901:repository/busybox", 
        "repositoryUri": "12345678901.dkr.ecr.us-east-1.amazonaws.com/busybox"
    }
}
```

```
$ docker push 12345678901.dkr.ecr.us-east-1.amazonaws.com/busybox
The push refers to a repository [12345678901.dkr.ecr.us-east-1.amazonaws.com/busybox]
8ac8bfaff55a: Pushed 
latest: digest: sha256:2130edda90b78fc58d77ecb1c4a512b08942dd7156fafcd5f9890bc08b1dc954 size: 2083

```
On earlier versions of docker, the following error is shown:

```
$ docker push 12345678901.dkr.ecr.us-east-1.amazonaws.com/busybox-2
The push refers to a repository [12345678901.dkr.ecr.us-east-1.amazonaws.com/busybox-2]
5f70bf18a086: Retrying in 1 second 
1834950e52ce: Retrying in 1 second 
name unknown: The repository with name 'busybox-2' does not exist in the registry with id '12345678901'
```

The EC2 Container Registry follows the registry v2 spec on initiating blob uploads:
https://docs.docker.com/v1.6/registry/spec/api/#intiate-blob-upload

and returns a 400 error with the code of "NAME_UNKNOWN" for repositories that have not been created. 

The Docker engine appears to be re-attemping a blob upload after receiving this error in an infinite loop rather than returning an error back to the client, which was the previous behavior.

This is the current docker info:

```
$ docker info

Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 7
Server Version: 1.12.0-rc3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 81
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge host null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.14-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.954 GiB
Name: moby
ID: BQOL:7DZH:37Y2:WS5R:DGC2:K5OU:LSNW:EWAV:4YNX:EFXN:4WSU:FWJM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 29
 System Time: 2016-07-08T20:45:07.691086163Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8



```

**Comment by thaJeztah** [comment]
ping @aaronlehmann ptal

**Comment by aaronlehmann** [comment]
Thanks for the report @sentientmonkey.

I'm curious if going back to -rc2 restores the correct behavior for you. Very little has changed in image pushing between -rc2 and -rc3. If this is actually a regression from -rc2 ro -rc3, it may be related to changes in the upstream docker/distribution project. But I see very little change there as well, so it would be great to confirm that something definitely changed between -rc2 and -rc3.

cc @docker/core-distribution-maintainers.

**Comment by thaJeztah** [comment]
let me ping @samuelkarp as well, perhaps he's been testing rc3 on ECR

**Comment by sentientmonkey** [comment]
Just downgraded to rc2 and it returns "name unknown" correctly. I'm using the docker for mac beta for both of these (not sure if that makes a difference). In rc2, it retries 3 times before giving up.

```
$  docker push 12345678901.dkr.ecr.us-east-1.amazonaws.com/busybox-2
The push refers to a repository [12345678901.dkr.ecr.us-east-1.amazonaws.com/busybox-2]
8ac8bfaff55a: Retrying in 1 second 
name unknown: The repository with name 'busybox-2' does not exist in the registry with id '12345678901'

$  docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 7
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 81
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: default
Default Runtime: default
Security Options: seccomp
Kernel Version: 4.4.13-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.954 GiB
Name: moby
ID: V5YX:PJR7:JXIE:ME3Z:PV7F:LU55:HZR4:UWO6:35ED:FBKK:FJYD:W4ZD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 21
 Goroutines: 28
 System Time: 2016-07-09T01:18:17.129808962Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Comment by aaronlehmann** [comment]
Does -rc3 continue retrying past 3 times?

It seems like a legitimate bug that we retry on a `NAME_UNKNOWN` error. I can open a PR to fix that.

But I'm at a loss to explain any difference in behavior between -rc2 and -rc3.

**Comment by samuelkarp** [comment]
@thaJeztah, thanks!  @sentientmonkey sits right by me and we were talking about this in the office yesterday.  He'll have more insight here than I do.

**Comment by thaJeztah** [comment]
@samuelkarp Oh! See it now, haha

**Comment by sentientmonkey** [comment]
@thaJeztah Yeah, @samuelkarp brought it to my attention 😄 

@aaronlehmann I may have spoken too soon on "infinite". Looks like in rc-2 it redrives 3 times waiting 5 seconds, 10, then 15. rc-3 redrives 4 times waiting 5s,10,15 & 20. Will update title to reflect - this may not be a regression in the rcs then as much as the default retry increase making the problem appear worse.

**Comment by aaronlehmann** [comment]
Thanks @sentientmonkey 

When I have a chance to set up an ECR registry to test against, I'll submit a PR to prevent the retries in this situation.

**Comment by sentientmonkey** [comment]
@aaronlehmann thanks - let me know if I can help at all (or if you have any questions).

**Comment by aaronlehmann** [comment]
I've opened #24520 for this.

**Comment by sentientmonkey** [comment]
Awesome, thanks all! 👍

I also didn't know about the TOOMANYREQUESTS error code. Today, ECR returns a 503 for throttling, so we can move to using that error code. Any chance we can add that do the API Documentation at https://docs.docker.com/registry/spec/api/ ? (I can open a new issue)

**Comment by thaJeztah** [comment]
@sentientmonkey that docs is in the "distribution" repository; https://github.com/docker/distribution/blob/master/docs/spec/api.md, probably best to open an issue there

**Comment by aaronlehmann** [comment]
@sentientmonkey: Thanks for pointing this out. I opened a pull request in the distribution repository: https://github.com/docker/distribution/pull/1833

**Comment by sentientmonkey** [comment]
@aaronlehmann thanks 😄
