### ISSUE TITLE
Running docker install on Ubuntu 14.04 container a second time fails with HTTP:403 error

### ISSUE THREAD

**Issue by asridharan** [docker/docker#24477]
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64
vagrant@mesos-dev:~/mesosphere/docker-con
```

**Output of `docker info`:**

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 9
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 17
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 3.13.0-68-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.798 GiB
Name: mesos-dev
ID: XRGB:MQ7T:ID2E:BHHG:BRDK:XXP5:HR64:C4AA:FH7V:JNR6:WITJ:3BE3
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Username: mesospheredocker
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Build a docker image using the following `Dockerfile` on Ubuntu 14.04 LTS
```
FROM ubuntu:14.04
MAINTAINER Mesosphere <support@mesosphere.io>


RUN apt-get update && \
  apt-get -y install apt-transport-https ca-certificates && \
  apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D && \
  echo deb https://apt.dockerproject.org/repo ubuntu-trusty main > /etc/apt/sources.list.d/docker.list && \
  apt-get update && \
  apt-get -y install docker-engine

```
The image will build fine, with docker installed within the Ubuntu 14.04 container.
2.

Run the same build again, with a different image name and it will fail with the following error:
```
W: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-trusty-testing/main/binary-amd64/Packages  HttpError403

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

3. Once the first build is done, you cannot access the docker ubuntu repo to install docker clients in any other docker image.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
Vagrant box:
```
ubuntu/trusty64
```
OS:
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty
```
Kernel:
```
Linux mesos-dev 3.13.0-68-generic #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by asridharan** [comment]
Ran into the same issue when I try to build a Ubuntu 14.04 image with docker on an AWS Ubuntu 14.04 instance. In this case the `docker build` fails with the HTTP 403 error on the first attempt itself. The docker installation goes through fine on the host. 

Just to add if I manually launch a Ubuntu 14.04 container and follow the install instruction for Ubuntu 14.04 https://docs.docker.com/engine/installation/linux/ubuntulinux/  it works perfectly.

So not sure why the same instructions don't work with `docker build`. The only thing I can imagine is that there is an issue the `gpg keys` ?

**Comment by justincormack** [comment]
I can't replicate this. It looks to me like there might be a bad mirror in the pool? I don't think it is a docker issue.

**Comment by thaJeztah** [comment]
Error looks to be because this is an invalid URL;
https://apt.dockerproject.org/repo/dists/ubuntu-trusty-testing/main/binary-amd64/Packages

(ubuntu-trusty-testing, instead of ubuntu-trusty)

**Comment by asridharan** [comment]
Oh boy,
This would be my bad. Didn't realize our make files were mangling the repo names to `trusty-testing` incorrectly. Sorry for the noise. Going to close this issue.

**Comment by thaJeztah** [comment]
no worries, glad it's resolved (I was worried some of *our* scripts did some mangling, haha)
