### ISSUE TITLE
Problem with Docker & New Version of Chrome

### ISSUE THREAD

**Issue by senrabdet** [docker/docker#24481]
**Output of `docker version`:**

```
docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:30:35 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:30:35 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 21
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker-8:1-3016557-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.114 GB
 Data Space Total: 107.4 GB
 Data Space Available: 43.21 GB
 Metadata Space Used: 2.376 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.127 (2016-06-11)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.6.0-1-amd64
Operating System: Debian GNU/Linux stretch/sid
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.958 GiB
Name: debian
ID: NYPZ:5UJA:LOJO:GYT7:PEBJ:MZ2U:S2VX:IPXK:3VDH:D6T2:NWXY:YUZM
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VirtualBox Version 5.0.24 r108355
Windows 10 Pro
Debian Stretch (4.6.0-1-amd64)
User Name Spaces enabled in kernel (cat /boot/config- uname -r  returns "CONFIG_USER_NS=y" in the output, and container starts without a name spaces error).

**Steps to reproduce the issue:**
1. Set up Docker file
NOTE:  strace results attached below in post show various "I can't find file or library" results.  I've tried adding in the missing libraries (maybe correctly, maybe not), and the image builds but I believe Chrome is still having trouble accessing library files (see strace results below).
```
# Run Chrome in a container
# Base docker image
FROM debian:sid
MAINTAINER Jessica Frazelle <jess@docker.com>

RUN apt-get update && apt-get install -y strace

#Test - see if adding libraries matters
RUN apt-get install libcomerr2 libdatrie-dev libdbus-glib-1-2 libgcrypt11-dev libgmp-dev \
 libgpg-error-dev libgraphite2-3 libharfbuzz-dev libnettle6 libidn11 libk5crypto3 \ 
libkeyutils-dev libkrb5-3 libkrb5support0 liblzma-dev nettle-dev libp11-kit-dev \
libresolv-wrapper libselinux1-dev libsystemd-dev libtasn1-6 libxau6 libxdmcp-dev \
 libxinerama-dev libavahi-client-dev libdbus-glib-1-dev -y

ADD https://dl.google.com/linux/direct/google-talkplugin_current_amd64.deb /src/google-talkplugin_current_amd64.deb

# Install Chrome
RUN echo 'deb http://httpredir.debian.org/debian testing main' >> /etc/apt/sources.list && \
	apt-get update && apt-get install -y \
    #
	ca-certificates \
	curl \
	hicolor-icon-theme \
	libgl1-mesa-dri \
	libgl1-mesa-glx \
	libv4l-0 \
	-t testing \
	fonts-symbola \
	--no-install-recommends \
	&& curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
	&& echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list \
	&& apt-get update && apt-get install -y \
	google-chrome-stable \
	--no-install-recommends \
	&& dpkg -i '/src/google-talkplugin_current_amd64.deb' \
	&& apt-get purge --auto-remove -y curl \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /src/*.deb

COPY local.conf /etc/fonts/local.conf


# Autorun chrome
#ENTRYPOINT [ "strace", "-ff", "google-chrome" ]
ENTRYPOINT [ "google-chrome" ]
CMD [ "--user-data-dir=/data" ]
```

2  Issue Docker Command

strace docker run -d --net host -v /etc/localtime:/etc/localtime:ro --cap-add SYS_PTRACE --security-opt seccomp:/home/user/Documents/Chrome/chrome.json -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY -v $HOME/Downloads:/root/Downloads -v $HOME/Pictures:/root/Pictures -v $HOME/Torrents:/root/Torrents -v $HOME/.chrome:/data --device /dev/video0 -v /dev/shm:/dev/shm -v /etc/hosts:/etc/hosts --device /dev/snd --device /dev/dri --group-add audio --group-add video --disable-content-trust --name chrome jess/chrome --user-data-dir=/data --force-device-scale-factor=1 --proxy-server="$proxy" --host-resolver-rules="$map" "$args" 

**Describe the results you received:**
Container starts but never get a GUI
- If I run with "no sandbox" flag, container starts with GUI
- Have tried with and without "--cap-add SYS_ADMIN" and " --seccomp unconfined", same result (I think)
- Have tried with various .json, same results (with exception that some I've tried prevent strace)

Strace results from host and in container (I think) suggest in part Chrome is having trouble accessing libraries:

from host strace:
[HostStrace.txt](https://github.com/docker/docker/files/355616/HostStrace.txt)

from container strace (i.e., once container has started, results from "docker exec chrome strace google-chrome"):
[ContainerStrace.txt](https://github.com/docker/docker/files/355610/ContainerStrace.txt)

**Describe the results you expected:**
Chrome starts in a Docker container with GUI
- longer term want to run without no sandbox or sys_admin as regular user, but initially just trying to get Chrome browser to start

**Additional information you deem important (e.g. issue happens only occasionally):**
Have attached "docker inspect" output
[DockerInspect.txt](https://github.com/docker/docker/files/355612/DockerInspect.txt)

Have attached .json used 
[chromejson.txt](https://github.com/docker/docker/files/355613/chromejson.txt)

**Comment by thaJeztah** [comment]
ping @jfrazelle perhaps you have some pointers?

**Comment by jfrazelle** [comment]
I would suggest looking at issues on my dockerfiles repo instead... There are some closed ones you might find interesting. Works on my machine.

**Comment by thaJeztah** [comment]
thanks @jfrazelle let me close this here; @senrabdet please have a look at the issues in the related repository; https://github.com/jfrazelle/dockerfiles/issues?utf8=✓&q=is%3Aissue%20chrome

**Comment by senrabdet** [comment]
HI Sebastian:
 
How are you?  Didn't know if you'd consider leaving this post open - have been spending a lot of time pouring over the posts Jess references (so shouldnote am struggling with some content on them, have spent real time on them before I posted), and still am unable to solve this.   My latest foray is leading me to think there is something going on in the .json file that fails depending on setup.  E.g., it has a line "apparmorProfile": "docker-default" which I think stops the code from running on my setup, and I'm finding other such instances that leads me to believe as Jess says it's something different in my set up vs. hers (e.g., in this case, I don't have appamor installed or running in my VM).  If I"m on the right track I'm finding it difficult to debug. It would be helpful to see if and how others might have solved this (e.g., how many people are using current versions of chrome in docker and Jess' work), and if  issues vary by different setups, how does the community "generalize" to make this easier?  Or I'm totally on the wrong track...:)
 
 If the post stays closed, no worries, I'll repost if I figure it out.  Thanks,
 

Senrabdet
 
 
--------- Original Message --------- Subject: Re: [docker/docker] Problem with Docker & New Version of Chrome (#24481)

**Comment by thaJeztah** [comment]
@senrabdet the point is that the GitHub issue tracker is not a general support forum, but for tracking bugs and feature requests for docker. To discuss other things, https://forums.docker.com may be a better location. As far as I can see, there's no bug, so it's best to keep it closed, but (as mentioned), feel free to leave a comment with how you got it working if you succeed.
