### ISSUE TITLE
The 'dockerize mongodb' example does not work anymore.

### ISSUE THREAD

**Issue by stefanofiorentino** [docker/docker#24482]
The [Dockerfile](docker/docs/examples/mongodb/Dockerfile) to Dockerize MongoDB doesn't work anymore.
`The command '/bin/sh -c apt-get update && apt-get install -y mongodb-org' returned a non-zero code: 100`
Maybe the change of ubuntu:latest causes the issue.
Should I pull request the fix?

**Comment by thaJeztah** [comment]
I think there's an open pull request to fix it (but I'm on mobile right now, so can't search easily; could you try looking through the open pull requests?

**Comment by stefanofiorentino** [comment]
You @thaJeztah remember very well..
[https://github.com/docker/docker/pull/24314/files](This) worked for me.

**Comment by thaJeztah** [comment]
@stefanofiorentino good to hear; please be aware that the example in the documentation is really just that; an *example*; for mongodb, using the official image may be a better option; https://hub.docker.com/_/mongo/
