### ISSUE TITLE
Provide consistency for inspecting Docker SwarmKit services and tasks

### ISSUE THREAD

**Issue by pcgeek86** [docker/docker#24485]
Docker Version: `Docker version 1.12.0-rc3, build 91e29e8, experimental`
OS: `Windows 10.0.10586`

There's a UX inconsistency in the `inspect` command, pertaining to Docker SwarmKit services and tasks.

- Inspecting a SwarmKit service requires: `docker service inspect`
- Inspecting a task in a SwarmKit service requires: `docker inspect task`

There are other cases in Docker where this is inconsistent (eg. networking, images, containers), however this issue pertains specifically to SwarmKit services and tasks.

# Proposed Design Fixes

Here are a few proposed design fixes:

- Move `docker service inspect` to `docker inspect service`
- Create a `task` root context, so we would do: `docker task inspect`
- Create a `task` context under `service`, so we would do: `docker service task inspect`

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by vdemeester** [comment]
@pcgeek86 thanks for the report. 

This is related to https://github.com/docker/docker/issues/24150 and https://github.com/docker/docker/issues/24152 I think 👼

**Comment by pcgeek86** [comment]
Sorry! I thought I searched well enough for duplicates. :angel: I'll go ahead and close this one.

**Comment by thaJeztah** [comment]
thanks for testing, and reporting @pcgeek86 it's appreciated!
