### ISSUE TITLE
Docker Install Fedora 24 Giving HTTP 403

### ISSUE THREAD

**Issue by joepreludian** [docker/docker#24495]
When Trying to install docker engine on Fedora 24 following the main tutorial It gave me error, disabling repo. When I access the link provided, I'ts giving an 403 error. Maybe permission issues?

    https://yum.dockerproject.org/repo/main/fedora/24/

**Steps to reproduce the issue:**
1. On a Fedora 24 Fresh install, follow this tutorial: https://docs.docker.com/engine/installation/linux/fedora/;
2. Add repo data to /etc/yum.repos.d/docker.repo regarding tutorial;
3. Try to install docker engine.

Thank You!

**Comment by LukasBacigal** [comment]
There is no package yet. https://github.com/docker/docker/pull/23896,even thought I dont understand what they are waiting for, it isn't like Fedora is some ultra small distribution. And there are currently also problems with selinux, so you can run docker on Fedora24 with setenforce 0 (but I have seen some new comits for selinux, so maybe it will be fixed with 1.12 too).

**Comment by runcom** [comment]
> And there are currently also problems with selinux, so you can run docker on Fedora24 only with setenforce 0

which problems are you facing?

**Comment by LukasBacigal** [comment]
It is not just me, even when you download repo for 23 (which is fine), installed selinux doesnt work: https://github.com/docker/docker/issues/23981. according to last comments looks like fix is on the way, but I haven't tried it yet.

**Comment by joepreludian** [comment]
Hello @runcom !

This issue is happenning when I try to access the main repository over http. Repo's response is giving Forbidden error (http403). Try accessing repo's link: https://yum.dockerproject.org/repo/main/fedora/24/

I guess the maintainer haven't checked the pages server permissions.

To make a Quick fix I downgrade the repo version (using fedora 23) and disabling selinux because of issue reported by @LukasBacigal.

**Comment by LukasBacigal** [comment]
I get it, but I don't think it is good approach, big repositories shouldn't
be left without newest docker version for such long time. And docker in
main repo is like 1.10 or something.

Dňa po, 11. júl 2016 15:21 Brian Goff <notifications@github.com> napísal(a):

**Comment by joepreludian** [comment]
@LukasBacigal Do You have any clue who is the maintainers?
I've searched in many places, but without success.

Thanks in advance.

**Comment by joepreludian** [comment]
Hi there @thaJeztah. Thank You for Your feedback.
I think it's solved. I'm going to send them a issue there.
