### ISSUE TITLE
make rpm:"ERROR: No build ID note found in ..."

### ISSUE THREAD

**Issue by sqleejan** [docker/docker#24497]
**Output of `docker version`:**

```
gitcommit:bc5fa7c5e04f776ee5a4636a78b59462463b92ac
```

**Steps to reproduce the issue:**
1.modify Makefile: -e DOCKER_BUILD_PKGS=centos-7
2.make rpm
3.output :"*** ERROR: No build ID note found in /root/rpmbuild/BUILDROOT/docker-engine-1.12.0-0.0.20160711.022134.git6d75354.el7.centos.x86_64/usr/bin/docker-proxy
error: Bad exit status from /var/tmp/rpm-tmp.H2APGr (%install)"

**Comment by cpuguy83** [comment]
ping @justincormack

**Comment by sqleejan** [comment]
Why rpmbuild report the error:"No build ID"?

**Comment by thaJeztah** [comment]
This should now be fixed by https://github.com/docker/docker/pull/24570, can you try again on current master?

**Comment by justincormack** [comment]
Ah sorry, I missed this when you reported it...

**Comment by sqleejan** [comment]
ok,fixed it on current master

**Comment by thaJeztah** [comment]
Cool, thanks for testing! I'll close this issue :)
