### ISSUE TITLE
map default subuuid

### ISSUE THREAD

**Issue by denniskong** [docker/docker#24506]
**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment]
Closing since there is no detail here.
If you have a particular issue please add some detail, as is unfortunately this issue has no meaning to it.

Thanks!
