### ISSUE TITLE
mount does not work for block devices passed to the container even with --cap-add=ALL

### ISSUE THREAD

**Issue by batk0** [docker/docker#24513]
Block device cannot be mounted even with --cap-add=ALL --security-opt apparmor=unconfined. It can be mounted with --privileged.

**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64
root@rancher:~# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.10-rancher
Operating System: RancherOS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.79 GiB
Name: rancher
ID: R5NH:LEOE:JJK2:I7I6:LQSP:KT4V:MCCX:GDD4:VELP:J7JX:D4TW:4VLN
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```
**Output of `uname -a`:**

```
Linux rancher 4.4.10-rancher #1 SMP Fri Jun 17 17:16:24 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical server on RancherOS 0.5.0

**Steps to reproduce the issue:**
1. Pass block device to a container
2. Try to mount

**Describe the results you received:**
Getting `mount: permission denied` without `--privileged`
```
root@rancher:~# docker run --rm -ti --device /dev/dm-0:/dev/xdm-0 --cap-add=ALL --security-opt apparmor=unconfined ubuntu mount /dev/xdm-0 /media
mount: permission denied
```
Mounted with `--privileged`
```
root@rancher:~# docker run --rm -ti --device /dev/dm-0:/dev/xdm-0 --privileged ubuntu mount /dev/dm-0 /media
root@rancher:~#
```

**Describe the results you expected:**

Would be good to have device mounted without `--privileged`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment]
You likely also need to disable seccomp (or provide a profile that doesn't filter `mount`): `--security-opt seccomp:unconfined`

In 1.12, when you `--cap-add` something Docker will also adjust the seccomp filters to allow the appropriate syscalls that the capability normally gates... in this case you'd just need `--cap-add SYS_ADMIN`

**Comment by justincormack** [comment]
You may also need to disable apparmor which also blocks mount, if you are
using Ubuntu.

**Comment by frellus** [comment]
This does not seem to be true with NFS mounts (i.e. if the container needs to act as an NFS client)?  Adding --cap-add SYS_ADMIN doesn't allow for mounting, nor does even --cap-add ALL

**Comment by cpuguy83** [comment]
@frellus See https://github.com/docker/docker/issues/24513#issuecomment-231838236

**Comment by frellus** [comment]
@cpuguy83 I'm running Docker 1.12RC4 -- see https://github.com/docker/docker/issues/24862  

Maybe this is another issue I should file though. --cap-add ALL does not allow NFS mounts. apparmor is diabled, despite the --security-opt flag.

```
$ docker run --cap-add SYS_ADMIN --security-opt seccomp:unconfined -ti iogen/dd /bin/bash
(trusty_i386)root@cda5be084783:/# mount 10.62.64.100:/root /mnt
mount: block device 10.62.64.100:/root is write-protected, mounting read-only
mount: cannot mount block device 10.62.64.100:/root read-only
```

**Comment by thaJeztah** [comment]
@frellus perhaps https://github.com/docker/docker/pull/24179 is interesting for your use case

**Comment by justincormack** [comment]
@frellus does that work with `--privileged`? Slightly surprised by the error message, I think something else might be going wrong. NFS mounts should work.
