### ISSUE TITLE
Routing mesh doesn't seem to work with 1.12rc3

### ISSUE THREAD

**Issue by ghoranyi** [docker/docker#24539]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   91e29e8
 Built:        Sat Jul  2 00:09:24 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   91e29e8
 Built:        Sat Jul  2 00:46:52 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 10
 Running: 4
 Paused: 0
 Stopped: 6
Images: 1
Server Version: 1.12.0-rc3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 27
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay bridge null
Swarm: active
 NodeID: 4hud54lxukcz1m6s2z7gs8d9e
 IsManager: Yes
 Managers: 1
 Nodes: 3
 CACertHash: sha256:c292fab2b6bd64c62b04fee288effc77d9d84b1af087e7130930399ab292276e
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.2.0-18-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 991.1 MiB
Name: manager
ID: ICKG:RWUD:ZSSX:EQ25:3YB6:KND3:GQO7:R56J:UBF7:D6WF:HE6P:YF7W
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=amazonec2
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
The environment was created with docker-machine on AWS. After creating the nodes, I manually bumped to the latest docker version (1.12rc3) and executed `docker swarm init` and `docker swarm join`
```
docker node ls
ID                           HOSTNAME  MEMBERSHIP  STATUS  AVAILABILITY  MANAGER STATUS
4hud54lxukcz1m6s2z7gs8d9e *  manager   Accepted    Ready   Active        Leader
9nuda9z5tjgh9ljwd9vm36oym    node2     Accepted    Ready   Active
a1lfv7bhnyo6or4ty9wubo9uf    node1     Accepted    Ready   Active
```

**Steps to reproduce the issue:**
1. `eval (docker-machine env manager)`
2. `docker service create --name test --p 8080:8000 jwilder/whoami` (This starts the container on `node1`
3. `curl localhost:8080` works just fine on `node1`, but it doesn't work on any other node, unless I scale up and have a container running there as well.

**Describe the results you received:**
I get connection refused on any node, which doesn't run my container. Also, nothing is listening on the right ports (checked with `sudo netstat -ntulp`)

**Describe the results you expected:**
Based on what I think the "routing mesh" feature of 1.12 should do, I was expecting that I can access the container even if I try it on a node which doesn't run it at the moment. Maybe I'm missing something, but that's what the keynote demo of DockerCon 2016 showed.

**Comment by cpuguy83** [comment]
@ghoranyi you very likely need to set `--listen-addr` when initializing the swarm (and joining) to make sure the correct address to listen on is chosen. By default it will just try to guess.

**Comment by ghoranyi** [comment]
I didn't manage to solve it with rc3, but rc4 works like a charm.
