### ISSUE TITLE
Extend deprecation cycle to default 3 releases

### ISSUE THREAD

**Issue by yongtang** [docker/docker#24534]
At the moment, the deprecation process in docker is 2 releases by default. (See docs/deprecated.md for examples), this is around 5 months.

There are requests to extend this deprecation cycle (See #24494), as in production environment 5 months might not be enough.

This issue is opened to suggest docker to extend the deprecation cycle to default 3 releases (roughly 6~7 months).

This issue is related to #24494.

cc @chriskuehl @thaJeztah.

**Comment by thaJeztah** [comment]
ping @duglin, @docker/core-engine-maintainers

**Comment by duglin** [comment]
I have no objection to making it longer - to me the key was just to be clear for our users what our rules are, so they're not surprised.
