### ISSUE TITLE
Docker 1.12.0-rc3 swarm mode - can't make wildfly standalon-ha to register on httpd-modcluster

### ISSUE THREAD

**Issue by DSTOLF** [docker/docker#24542]
**Output of `docker version`:**

```
docker version
Client:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   91e29e8
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   91e29e8
 Built:        
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 21
 Running: 2
 Paused: 0
 Stopped: 19
Images: 162
Server Version: 1.12.0-rc3
Storage Driver: devicemapper
 Pool Name: docker-202:32-3932161-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.345 GB
 Data Space Total: 107.4 GB
 Data Space Available: 102.9 GB
 Metadata Space Used: 8.495 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.139 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge host null
Swarm: active
 NodeID: 01h8iq4kxdlibdw9mdx394jd0
 IsManager: Yes
 Managers: 1
 Nodes: 3
 CACertHash: sha256:04669ba0d6dc01402b667248b5ac3c86319f55d07c34c09f1cbf46320f220b84
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.22.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.792 GiB
Name: VINDOC701.dev1.stelo.local
ID: E7SP:4FWC:HVFL:KIWG:3HIJ:ZXVZ:PYSE:4OZI:KGK7:J2LP:DK6F:XFSY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):** Physical

**Steps to reproduce the issue:**
1. 
```
docker node ls
ID HOSTNAME MEMBERSHIP STATUS AVAILABILITY MANAGER STATUS
01h8iq4kxdlibdw9mdx394jd0 * VINDOC701.dev1.local Accepted Ready Active Leader
510vgjvdvq9kk5ufpzb44p7iu VINDOC703.dev1.local Accepted Ready Active 
7oq0krop57wfebcgsr8t8bk4t VINDOC702.dev1.local Accepted Ready Active
```

2. I have two Docker Images I've built, one for httpd with mod_cluster, and another with Wildfly 10. When I run them on my local machine without Swarm, they work together fine, so when I query mod_cluster_manager, it shows all the Wildfly containers running, and it also load balance http access to node-info app:
```
dstolf@cherno-alpha:~/docker/wildfly$ docker run -d -p 8080:80 centos/httpd/modcluster
1b2de0f2c0d9867b39246d3cd22efb56676214099d494d6c4106a1a5b511961a

dstolf@cherno-alpha:~/docker/wildfly$ docker run -d jboss/wildfly/app
d60c191a7b72b17690310c6d41e0fb791d20372e54aaf0591f406d659511bb1f

dstolf@cherno-alpha:~/docker/wildfly$ docker run -d jboss/wildfly/app
5bb68830d6bc33210e384989cd8f1233fdaac54ef240c61fd11f2551d6052b4d

dstolf@cherno-alpha:~/docker/wildfly$ docker run -d jboss/wildfly/app
3f234b5174a03d1ff4c2b95d11e4f57a0b44ce479bbefc70e2a3bced03eb7b2f

dstolf@cherno-alpha:~/docker/wildfly$ curl http://localhost:8080/mod_cluster_manager
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html><head>
<title>Mod_cluster Status</title>
</head><body>
<h1>mod_cluster/1.3.1.Final</h1><a href="/mod_cluster_manager?nonce=bbe3e1d0-4053-47f1-9b4d-ded29e73874b&refresh=10">Auto Refresh</a> <a href="/mod_cluster_manager?nonce=bbe3e1d0-4053-47f1-9b4d-ded29e73874b&Cmd=DUMP&Range=ALL">show DUMP output</a> <a href="/mod_cluster_manager?nonce=bbe3e1d0-4053-47f1-9b4d-ded29e73874b&Cmd=INFO&Range=ALL">show INFO output</a>
<h1> Node server-172.17.0.3 (ajp://172.17.0.3:8009): </h1>
...
```

3. So I pulled the originial images (jboss/wildfly and centos/httpd) from official registry into my private registry. When I run them on docker 1.12 with swarm mode active, the Wildfly containers can't communicate with httpd-modcluster and register themselves:
```
docker service create --replicas 1  -p 3000:80    --mount target=/data,source=/data,type=bind,writable=true --name load_balancer dockerhub.dev1.stelo.local:5000/centos/httpd/modcluster
docker service create --replicas 3  -p 8080:8080   --mount target=/data,source=/data,type=bind,writable=true  --name java_app       dockerhub.dev1.stelo.local:5000/jboss/wildfly/app
```

4- So, when I go to my browser and try to open on :3000/mod_cluster_manager, there are no containers registered. If I go to :8080/node-info, I get the expected output from the test java app, because I published port 8080.

5- http/modcluster Dockerfile 
```
FROM dockerhub.dev1.stelo.local:5000/centos/httpd
USER root

# Disable mod_proxy_balancer module and enable mod_cluster
RUN sed -i 's|LoadModule proxy_balancer_module|# LoadModule proxy_balancer_module|' /etc/httpd/conf.modules.d/00-proxy.conf 

# Add launch.sh 
ADD launch.sh /
ADD template_modcluster /
RUN chmod +x /launch.sh

# add mod_cluster 
ADD mod_advertise.so /etc/httpd/modules/
ADD mod_manager.so /etc/httpd/modules/
ADD mod_proxy_cluster.so /etc/httpd/modules/
ADD mod_cluster_slotmem.so /etc/httpd/modules/

# Add mod_cluster.conf 
ADD mod_cluster.conf /etc/httpd/conf.d/mod_cluster.conf
      
# Do the required modifications and launch Apache after boot
ENTRYPOINT /launch.sh
```
 5- launch.sh
```
#/bin/bash

# Get the Hostname
HOSTNAME=$(hostname)
# Adjust the IP addresses in the mod_cluster.conf file
IPADDR=$(hostname -i | awk '{print $2}')
sed -i "s|[0-9\.\*]*:80|$IPADDR:80|g" /etc/httpd/conf.d/mod_cluster.conf

cat template_modcluster >> /etc/httpd/conf.d/mod_cluster.conf

# Log run
echo "######## Start httpd modcluster ########" >> /data/httpd/httpd_${HOSTNAME}.log
hostname >> /data/httpd/httpd_${HOSTNAME}.log
echo $IPADDR >> /data/httpd/httpd_${HOSTNAME}.log
date >> /data/httpd/httpd_${HOSTNAME}.log

# touch error_log and access_log
touch /var/log/httpd/error_log
touch /var/log/httpd/access_log

# tail file and redirect to /data/httpd/
nohup tail -f /var/log/httpd/error_log >> /data/httpd/error_log_${HOSTNAME}.log &
nohup tail -f /var/log/httpd/access_log >> /data/httpd/access_log_${HOSTNAME}.log &
nohup tail -f /var/log/messages >>  /data/httpd/messages_${HOSTNAME}.log &

# dump final mod_cluster.conf 
```
5- template_modcluster
```
<VirtualHost *:80>

  EnableMCPMReceive true
  ServerAdvertise On
  ServerName loadbalancer

  <Location />
    Require all granted
  </Location>

  <Location /mod_cluster_manager>
    SetHandler mod_cluster-manager
    Require all granted
  </Location>

</VirtualHost>
```
6- wildfly docker file:
```
FROM dockerhub.dev1.stelo.local:5000/jboss/wildfly
USER root
# ADD app to deployment folder
ADD node-info.war /opt/jboss/wildfly/standalone/deployments/


# ADD launch script standalone ha mode
ADD launch_standalone_ha.sh /

# Change launch script permission
RUN chown jboss:jboss /launch_standalone_ha.sh

# Change app files permission
RUN chown jboss:jboss /opt/jboss/wildfly/standalone/deployments/node-info.war

# Change launch scripts permissions
RUN chmod +x /launch_standalone_ha.sh

# add wildfly admin user
USER jboss
RUN /opt/jboss/wildfly/bin/add-user.sh admin Admin@123 --silent

# Run WildFly after the container boots
ENTRYPOINT /launch_standalone_ha.sh
```
7- launch_standalone_ha.sh
```
#!/bin/bash
# output of hostname -I is 10.255.0.11 172.18.0.4 
# already tried to use both of them at the line bellow
IPADDR=$(hostname -I | awk '{print $2}')
touch /data/wildfly/standalone_ha_`hostname`.log
hostname -I > /data/wildfly/standalone_ha_`hostname`.log

# alternate launch #
#echo "/opt/jboss/wildfly/bin/standalone.sh -c standalone-ha.xml -Djboss.bind.address=$IPADDR -Djboss.bind.address.management=$IPADDR -Djboss.node.name=server-$IPADDR" >> /data/wildfly/standalone_ha_`hostname`.log

#/opt/jboss/wildfly/bin/standalone.sh -c standalone-ha.xml -Djboss.bind.address=$IPADDR -Djboss.bind.address.management=$IPADDR -Djboss.node.name=server-$IPADDR >> /data/wildfly/standalone_ha_`hostname`.log
# ############ #

echo "/opt/jboss/wildfly/bin/standalone.sh -c standalone-ha.xml -Djboss.bind.address=0.0.0.0 -Djboss.bind.address.management=$IPADDR -Djboss.node.name=server-$IPADDR" >> /data/wildfly/standalone_ha_`hostname`.log
/opt/jboss/wildfly/bin/standalone.sh -c standalone-ha.xml -Djboss.bind.address=0.0.0.0 -Djboss.bind.address.management=$IPADDR -Djboss.node.name=server-$IPADDR >> /data/wildfly/standalone_ha_`hostname`.log

```

**Describe the results you received:**
Wildfly nodes don't register themselves with http-modcluster

**Describe the results you expected:**
That wildfly nodes should register with http-modcluster

**Comment by DSTOLF** [comment]
BTW: I'm still learning all this, and I'm also not used to git, so... Sorry if I did something stupid ;)

**Comment by DSTOLF** [comment]
I think I found out what the problem is.

https://github.com/docker/libnetwork/issues/552

Overlay Networks doesn't support multicast. 

I could use unicast, but then it would be impossible to register wildfly worker nodes, because I can't figure out their ip's beforehand.

**Comment by mavenugo** [comment]
@DSTOLF could you please explain the wildfly registration process ? Which IP address should you know beforehand in order for the registration to work ?

**Comment by DSTOLF** [comment]
Hi @mavenugo , how are you?

As far as I understand, wildfly uses multicast to announce itself on the network and get registred on httpd/mod_cluster.

https://docs.jboss.org/author/display/WFLY8/Load+Balanced+HA+Standalone+Cluster+-+Howto

> Starting the wildfly instance can be done using the below command on Unix on both the servers
> 
> ./standalone.sh -c standalone-ha.xml -b=$HOSTNAME -bmanagement=$HOSTNAME -u 230.0.0.4 -Djboss.node.name=$HOSTNAME
> Here the -c option specifies the configuration file to use. We are going to use the High-Availability setup
> **The -u option describes the multicast address**. It is using this IP both servers communicate.
> For ease of setup, I have included the $HOSTNAME in the nodename and start up options

An alternative approache would be to fallback to unicast:
https://access.redhat.com/documentation/en-US/JBoss_Enterprise_Application_Platform/6/html/Administration_and_Configuration_Guide/Configure_the_mod_cluster_Subsystem_to_Use_TCP.html

> **The mod_cluster subsystem uses multicast UDP for its network communication by default.** If you wish, you can use unicast TCP communication instead. Use the following procedure to configure this behavior.
> ...
> Modify the HTTPD configuration to disable server advertising and to use a proxy list instead. The proxy list is configured on the worker, and contains all of the mod_cluster-enabled HTTPD servers the worker can talk to.

Bu I don't think that would work on Swarm Mode. I don't know the mod_cluster's containers IP address beforehand and, if I scale them out, I won't be able to modify the running Wildfly workers' configurations.

**Comment by bangnab** [comment]
+1 This is exactly what I also would like to achieve!

**Comment by mavenugo** [comment]
@DSTOLF with the built-in service discovery, one can easily get the ip-addresses of all the containers that backs a service. For example, if mod_cluster-enabled HTTPD Service is named `mod-cluster-service`, then a DNS query to `tasks.mod-cluster-service` will return all the ip-addresses of the containers across the cluster that backs this service. I guess one can use that to configure the unicast method.

Yes. Multicast is not supported yet and using the unicast fallback approach is the only way atm.

**Comment by DSTOLF** [comment]
@bangnab  I've seen weavenet before, but it seems unstable ATM on 1.12

https://github.com/docker/docker/issues/23990
https://github.com/weaveworks/weave/issues/2403

Global plugins are still unsupported on swarm mode and there are a few issues with local plugins that have been corrected just a few days ago.

**Comment by DSTOLF** [comment]
@mavenugo 
I'll try it out, and get back to you. 

But I think it's far from an optimal solution. 
- I'm not sure if I can put the` tasks.mod-cluster-service` straight into the proxy list. I think I'll probably have to resolve the name on a shell script and `sed` the ip addresses list into the configuration files;

- But shell scripting is the least of our problems. Say, if I have to scale an httpd/mod_cluster service , I would have to reprovision all the wildfly worker nodes so they could re-register with the new load balancer containers;

- Or even worst, the load balancer crashed and restarded, when it get back online, it will have no worker nodes registred to it and I would have to restart the wildfly service.

**Comment by mavenugo** [comment]
@DSTOLF am not familiar with how wildfly operates. So, some of my questions/suggestions may not apply directly. But I will still try :-). With swarm-mode, we support VIP based Load-balancing combined with Service-Discovery. Hence the only configuration the applications ideally would need is the Virtual-IP of the service and ideally should not care about the individual containers that back that service. I know it is a very gross generalization of a docker application and may not be applicable for your specific case.

If this particular application absolutely requires individual containers during scaling or such operations, then the only way (in the absence of multicast support) is to learn about the new container and reprogram the configuration.

Regarding your question on plugins,  Yes, swarm-mode doesnt support remote network plugins yet. And swarm-mode can be used only with global-drivers (local-drivers doesnt make much sense if one need multi-host connectivity, which is a basic requirement for swarm-mode). We are working on making the plugins available in swarm-mode post 1.12 release.

**Comment by DSTOLF** [comment]
@mavenugo I'm also no specialist on Wildfly and Jboss. I'm actually pretty new to it. 

For the record, I couldn't set up the damn thing up using Unicast (Wildfly's fault or mine, not Docker's haha)  and httpd mod_cluster. So I decided to go with JGroups and Gossip Router (which is still a single point of failure, but fully compatible with the overlay network) and am now using Swarm Mode own load balancing system. 

It's enough for me for the moment to continue with my tests. 

But I'd sure wish to see native multicast support on Swarm, or at the very least get plugins supported in swarm-mode. It would be very nice to be able to setup a dynamic JBoss or Wildfly Cluster in Docker in the easy mode

**Comment by DSTOLF** [comment]
BTW, thanks a lot for your feedback. Keep up the good work.

**Comment by mavenugo** [comment]
Thanks for the confirmation @DSTOLF .
Yes. We have a few request for the multicast support. But we havent received any contributions to make that happen :-).

**Comment by thaJeztah** [comment]
@mavenugo do we have a tracking issue for that? Perhaps we should create one, and add a "help wanted" label

**Comment by mavenugo** [comment]
@thaJeztah https://github.com/docker/libnetwork/issues/552 and I added the `help/wanted` label long ago :)

**Comment by thaJeztah** [comment]
@DSTOLF should we close this issue in favor of https://github.com/docker/libnetwork/issues/552 ?

**Comment by DSTOLF** [comment]
Sure, go ahead.

**Comment by thaJeztah** [comment]
Thanks!
