### ISSUE TITLE
Swarm integration tests should not require network

### ISSUE THREAD

**Issue by tonistiigi** [docker/docker#24547]
#24490 added network requirement for these tests but there shouldn't be a need for that. Original problem seems to come from listening address detection and there are already PRs(#24237) that change that. If that PR doesn't fully fix it we should fix the remaining issues instead of skipping these tests.

@runcom @thaJeztah

**Comment by yongtang** [comment]
@tonistiigi The PR #24237 has already been merged. I removed network requirement and all tests still passed with networking disabled. I created a PR #25258 to remove `testRequires(c, Network)` from the integration tests.
