### ISSUE TITLE
Inconsistency between --restart-delay and --update-delay

### ISSUE THREAD

**Issue by aaronlehmann** [docker/docker#24551]
In Docker 1.12-rc3:

```
      --restart-delay value          Delay between restart attempts (default none)
      --update-delay duration        Delay between updates
```

Notice that one is followed by `value` and other is followed by `duration`. It looks like this is because `--restart-delay` uses `DurationOpt`, and `--update-delay` uses `time.Duration` directly. I guess this difference is because `--restart-delay` is a persistent setting, but `--update-delay` is meant to apply to only the current updaet (I'm not sure this is expected behavior, though). I think both should use `DurationOpt` for consistency, and we should consider treating `--update-delay` as a persistent value.

cc @dnephin @aluzzardi

**Comment by dnephin** [comment]
The different between these two flags is that one is a `*time.Duration` and the other is a `time.Duration`. We use  `time.Duration` if `0` is an ok default value, and `*time.Duration` if we need to differentiate between default and unset.

We can get the help text to say something other than `value` by using a backtick quoted string in the usage string for the flag (ex: 
```
"Delay is the `duration` to wait between restart attempts"
```
, but I don't think that sounds as good as the current usage string.

**Comment by aaronlehmann** [comment]
Can't we use `flags.Changed` to differentiate between set and unset? I'm also a little confused about why these flags are handled differently. Shouldn't they both be treated as persistent values stored onto the service spec?

**Comment by dnephin** [comment]
I think they just follow the engine-api types. I don't know why the engine-api types aren't consistent here. Most seem to be `*time.Duration`.

**Comment by aaronlehmann** [comment]
ping @vieux

**Comment by vieux** [comment]
@dnephin do you think we shoud use `*time.Duration` for `UpdateConfig.Delay` in `engine-api` ?

**Comment by dnephin** [comment]
I guess so, for consistency. P3 sounds right to me

**Comment by thaJeztah** [comment]
@vieux @dnephin did we change this? Are we still able to change this later, or would that result in backward compatibility issues?

**Comment by dnephin** [comment]
We can change the cli output later at least. The API wouldn't be completely backwards compatible, but we might be able to change it.

**Comment by aaronlehmann** [comment]
This has since been fixed so I'm closing. Opening a PR to fix another inconsistency I found.
