### ISSUE TITLE
docker service create/update with --registry-auth not auto completing

### ISSUE THREAD

**Issue by ralphtheninja** [docker/docker#24554]
**Output of `docker version`:**

```
Client:                                
 Version:      1.12.0-rc3              
 API version:  1.24                    
 Go version:   go1.6.2                 
 Git commit:   91e29e8                 
 Built:        Sat Jul  2 00:38:44 2016
 OS/Arch:      linux/amd64             
                                       
Server:                                
 Version:      1.12.0-rc3              
 API version:  1.24                    
 Go version:   go1.6.2                 
 Git commit:   91e29e8                 
 Built:        Sat Jul  2 00:38:44 2016
 OS/Arch:      linux/amd64             
```

**Output of `docker info`:**

```
Containers: 1                                                  
 Running: 1                                                    
 Paused: 0                                                     
 Stopped: 0                                                    
Images: 6                                                      
Server Version: 1.12.0-rc3                                     
Storage Driver: aufs                                           
 Root Dir: /var/lib/docker/aufs                                
 Backing Filesystem: extfs                                     
 Dirs: 47                                                      
 Dirperm1 Supported: true                                      
Logging Driver: json-file                                      
Cgroup Driver: cgroupfs                                        
Plugins:                                                       
 Volume: local                                                 
 Network: null bridge host overlay                             
Swarm: active                                                  
 NodeID: 0jhp0dugi07duteoag1lol3dg                             
 IsManager: No                                                 
Runtimes: runc                                                 
Default Runtime: runc                                          
Security Options: apparmor seccomp                             
Kernel Version: 4.4.0-28-generic                               
Operating System: Ubuntu 16.04 LTS                             
OSType: linux                                                  
Architecture: x86_64                                           
CPUs: 2                                                        
Total Memory: 1.954 GiB                                        
Name: docker-worker1                                           
ID: SAHA:ZEYC:YH2I:SUY3:CNHQ:LWNU:TFWQ:MDKH:5W4G:QXX5:ACIR:TMBE
Docker Root Dir: /var/lib/docker                               
Debug Mode (client): false                                     
Debug Mode (server): false                                     
Registry: https://index.docker.io/v1/                          
WARNING: No swap limit support                                 
Insecure Registries:                                           
 127.0.0.0/8                                                   
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running on Digital Ocean virtual machines.

**Steps to reproduce the issue:**
1. Type `docker service create --reg` and hit tab
2. Ditto with `docker service update --reg`

**Describe the results you received:**

`--registry-auth` is not auto completed

**Describe the results you expected:**

`--registry-auth` _is_ auto completed ;)

**Comment by thaJeztah** [comment]
Thanks for reporting; completion scripts for this are not updated yet, see https://github.com/docker/docker/pull/23584#issuecomment-230949662

/cc @albers @sdurrheimer

**Comment by albers** [comment]
@thaJeztah Thanks for the ping. I was watching #23584 but there are currently so many long-running PRs with a lot of technical discussion that I missed your ping among all the notifications.

**Comment by thaJeztah** [comment]
@albers yes, I know, no worries:smile:

**Comment by albers** [comment]
@ralphtheninja Thanks for reporting. Let us know when you find other issues.

**Comment by ralphtheninja** [comment]
> @ralphtheninja Thanks for reporting. Let us know when you find other issues.

Will do! Thanks for quick fix.

Time for me to learn `go` and help out. At least I know where the bash completion code can be found :)

**Comment by thaJeztah** [comment]
@ralphtheninja thanks in advance! You're already helping out by testing and reporting issues, much appreciated!

**Comment by ralphtheninja** [comment]
Installed `rc4` now and found some regression when it comes to bash completion. Can't get `docker {service, swarm}` to complete. Also `docker run --network` is not completing. Should I report a separate issue for all of this or separate issues for both of them?

**Comment by ralphtheninja** [comment]
Nevermind on `--network`. Noticed is was fixed in https://github.com/docker/docker/pull/24583

**Comment by thaJeztah** [comment]
@ralphtheninja yes, apologies for that; we decided to try and do a weekly RC until GA, but that can sometimes mean that not all changes are in (for example, updates to the completion scripts)

**Comment by ralphtheninja** [comment]
@thaJeztah Oh I didn't mean _this_ issue. I meant regression in functionality since `swarm` and `service` does auto complete in `rc3`.
