### ISSUE TITLE
Unable to deploy a service in swarm mode due to "oci runtime error: could not create session key: function not implemented"

### ISSUE THREAD

**Issue by malawson** [docker/docker#24578]
**Output of `docker version`:**

```
(DEV) arnaud@vagrant-swarm_manager1 ~ $ docker version
Client:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6
 Git commit:   91e29e8
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6
 Git commit:   91e29e8
 Built:
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
(DEV) arnaud@vagrant-swarm_manager1 ~ $ docker info
Containers: 15
 Running: 0
 Paused: 0
 Stopped: 15
Images: 1
Server Version: 1.12.0-rc3
Storage Driver: devicemapper
 Pool Name: docker-8:3-131679-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 96.53 MB
 Data Space Total: 107.4 GB
 Data Space Available: 34.66 GB
 Metadata Space Used: 856.1 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.88 (2014-08-05)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: active
 NodeID: eswhbl725bpw6ksm3t83avxy8
 IsManager: Yes
 Managers: 1
 Nodes: 3
 CACertHash: sha256:df5be5ea09b669e6ec5498b5088ac02779af9ecf92b6a6ecd8441962f6ccf092
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.14.15-hardened
Operating System: Gentoo/Linux
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.433 GiB
Name: vagrant-swarm_manager1
ID: K3UO:RSV4:ETKY:33IQ:O7IQ:WUFY:TUSX:VIEQ:2ZAN:HHSL:NWQW:QKUQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No cpuset support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Run step2 in the service deployment tutorial for swarm mode: https://docs.docker.com/engine/swarm/swarm-tutorial/deploy-service/
2.
3.

**Describe the results you received:**
Getting these errors on the swarm nodes 

"time="2016-07-13T03:17:15.113269397-04:00" level=error msg="fatal task error" error= module=taskmanager task.id=agqligjjs3odgkneq22y8ja9b
time="2016-07-13T03:17:16.593164569-04:00" level=error msg="containerd: start container" error="oci runtime error: could not create session key: function not implemented" id=804d9cff253a483b41f88aabfacfd21d2092343879fa6b300b89f9633d807219
time="2016-07-13T03:17:16.603118526-04:00" level=error msg="Create container failed with error: oci runtime error: could not create session key: function not implemented""

**Describe the results you expected:**
i expected my tasks to be up but nothing is up 
(DEV) arnaud@vagrant-swarm_manager1 ~ $ docker service inspect --pretty helloworld
ID:		4vlw92uf38q5qrll7glliii8b
Name:		helloworld
Mode:		Replicated
 Replicas:	5
Placement:
 Strategy:	Spread
UpdateConfig:
 Parallelism:	0
ContainerSpec:
 Image:		alpine
 Args:		ping meetup.com
Resources:
Reservations:
Limits:
(DEV) arnaud@vagrant-swarm_manager1 ~ $ docker service list
ID            NAME        REPLICAS  IMAGE   COMMAND
4vlw92uf38q5  helloworld  0/5       alpine  ping meetup.com

**Additional information you deem important (e.g. issue happens only occasionally):**
Not quite sure what i am missing so far...

**Comment by thaJeztah** [comment]
ping @mlaventure @crosbymichael 

error is coming from https://github.com/opencontainers/runc/blob/660029b476c5fd16e6d03f00e8d54b4c867be2fa/libcontainer/keys/keyctl.go#L19-L35, so could this be an issue with your kernel not supporting session keyring?

**Comment by mlaventure** [comment]
The vanilla version kernel at this version should work perfectly. 

@malawson do the nodes have exactly the same configuration as your manager?

**Comment by malawson** [comment]
@thaJeztah yeah it is an issue with my kernel. When i run this for example i get the same error 
$ uname -r
3.14.15-hardened
$ keyctl session
keyctl_join_session_keyring: Function not implemented

And on another machine with an upgraded kernel it works 
uname -r
3.18.0-sabayon
# keyctl session
Joined session keyring: 920387628

so i am going to upgrade the kernel or build in support for session keyring. 

@mlaventure yes i am trying to have all my swarm node run the same OS image. We can close this for now i think.

**Comment by thaJeztah** [comment]
@malawson thanks, and good to hear we found the culprit :D

I'll close this issue: good luck updating your machines!
