### ISSUE TITLE
Docker service doesn't start by systemd after swarm init and no internet access

### ISSUE THREAD

**Issue by puppetpies** [docker/docker#24587]
docker version
Client:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.2
 Git commit:   e2fc143
 Built:        Mon Jul 11 15:28:02 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
[root@orville brian]# systemctl status -l docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled)
   Active: failed (Result: exit-code) since Wed 2016-07-13 14:01:51 BST; 4min 8s ago
     Docs: https://docs.docker.com
  Process: 391 ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock (code=exited, status=1/FAILURE)
 Main PID: 391 (code=exited, status=1/FAILURE)

Jul 13 14:01:49 orville.lan dockerd[391]: time="2016-07-13T14:01:49.483617257+01:00" level=error msg="Error unmounting container 6a671baca75c4741350046a5ea2afd4627a12dcd64748825ec2139bff4aa3207: invalid argument"
Jul 13 14:01:49 orville.lan dockerd[391]: time="2016-07-13T14:01:49.588853422+01:00" level=info msg="Firewalld running: false"
Jul 13 14:01:50 orville.lan dockerd[391]: time="2016-07-13T14:01:50.074310007+01:00" level=info msg="Removing stale sandbox 1b3bff40b529d3a72dd8a656def7bef937982aa15e19492f6ac3bc808e64d0a1 (6a671baca75c4741350046a5ea2afd4627a12dcd64748825ec2139bff4aa3207)"
Jul 13 14:01:50 orville.lan dockerd[391]: time="2016-07-13T14:01:50.231941750+01:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Jul 13 14:01:51 orville.lan dockerd[391]: time="2016-07-13T14:01:51.151818553+01:00" level=info msg="Loading containers: done."
Jul 13 14:01:51 orville.lan dockerd[391]: time="2016-07-13T14:01:51.881502303+01:00" level=error msg="cluster exited with error: could not determine local IP address: dial udp 8.8.8.8:53: connect: network is unreachable"
Jul 13 14:01:51 orville.lan dockerd[391]: time="2016-07-13T14:01:51.882443656+01:00" level=fatal msg="Error creating cluster component: swarm component could not be started: could not determine local IP address: dial udp 8.8.8.8:53: connect: network is unreachable"
Jul 13 14:01:51 orville.lan systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Jul 13 14:01:51 orville.lan systemd[1]: Failed to start Docker Application Container Engine.
Jul 13 14:01:51 orville.lan systemd[1]: Unit docker.service entered failed state.

**Comment by cpuguy83** [comment]
This can be resolved by making sure when you `docker swarm init` you use a `--listen-addr`.
We are also changing the autodetection logic so it doesn't need to dial out in #24237

**Comment by puppetpies** [comment]
Ok thanks will close this issue !
