### ISSUE TITLE
Docker local rpm install fails

### ISSUE THREAD

**Issue by prateek121** [docker/docker#24584]
**Output of `docker version`:**

Client:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   91e29e8
 Built:        Sat Jul  2 00:09:24 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   876f3a7
 Built:        Tue Jul  5 02:20:13 2016
 OS/Arch:      linux/amd64
 Experimental: true

Im trying to add a rpm and install the rpm by "rpm -ivh abc.rpm"
but everytime I get the following error not sure whats wrong,Ive use centos7 and centos5 both

mkdir: cannot create directory `/usr/lib/systemd/system': No such file or directory
/var/tmp/rpm-tmp.97266: line 182: /usr/lib/systemd/system/liagentd.service: No such file or directory

**Comment by runcom** [comment]
Seems like your rpm is trying to install units for sysstemd but systemd isn't in the container?

**Comment by prateek121** [comment]
But that same rpm If I try to install on a centos5 vm works fine which is a init .Not sure why is that happening when I build the image ..any idea ?

**Comment by runcom** [comment]
can you provide more info about the image/container you're trying to rpm -i in?

**Comment by thaJeztah** [comment]
The RPM detects if it's a systemd system, and in that case has those packages as a dependency; https://github.com/docker/docker/blob/47ace5cd989103f7d646282fce66434b5a3c13f6/hack/make/.build-rpm/docker-engine.spec#L14-L17

**Comment by runcom** [comment]
I think he's trying to install a different rpm inside a container or I missed everything? :smile:

**Comment by thaJeztah** [comment]
oh, wait! haha.

@prateek121 are you perhaps using the `overlay` graph driver?

**Comment by prateek121** [comment]
Step 1 : FROM centos:centos5
 ---> cfbd8d982733
Step 2 : ADD li.rpm /tmp/li.rpm
 ---> 55f77ce31d4f
Removing intermediate container 04699606d553
Step 3 : RUN rpm -i /tmp/li.rpm
 ---> Running in 09bc166801a8
mkdir: cannot create directory `/usr/lib/systemd/system': No such file or directory
/var/tmp/rpm-tmp.95239: line 182: /usr/lib/systemd/system/liagentd.service: No such file or directory
error: %post(VMware-Log-Insight-Agent-3.3.1-3636434.noarch) scriptlet failed, exit status 1
The command '/bin/sh -c rpm -i /tmp/li.rpm' returned a non-zero code: 1

**Comment by prateek121** [comment]
I did try on centos7 too and it doesnt seem to work

**Comment by prateek121** [comment]
ON centos 7 this is what I get
Step 1 : FROM centos:centos7
 ---> 05188b417f30
Step 2 : ADD li.rpm /tmp/li.rpm
 ---> 846d28dcf417
Removing intermediate container c4e3d1215cf7
Step 3 : RUN rpm -i /tmp/li.rpm
 ---> Running in 4f0422b132e7
Created symlink from /etc/systemd/system/multi-user.target.wants/liagentd.service to /usr/lib/systemd/system/liagentd.service.

Installation failed.

For online documentation please visit:
https://www.vmware.com/support/pubs/log-insight-pubs.html
Failed to get D-Bus connection: Operation not permitted
warning: %post(VMware-Log-Insight-Agent-3.3.1-3636434.noarch) scriptlet failed, exit status 1

**Comment by runcom** [comment]
Systemd can't work in containers right now,  and your rpm is needing it at least for installation also. Cento 5 does not have systemd, centos 7 does but it doesn't work in the container.

**Comment by thaJeztah** [comment]
It's possible to run systemd, but it requires adding additional privileges to the container, which are not present during build. 

Following the above, there's no bug here, and the GitHub issue tracker is not a general support forum, so I'll close this issue, but feel free to comment after I closed

**Comment by prateek121** [comment]
@thaJeztah May I know how do I run systemd by giving additional privileges to the container ?

Also for the same rpm gets installled on centos 5 VM (I know containers are different) but how do I make it work.
For your reference I attaching the rpm .
you may try and run the agent in the container and VM If you can
[li.rpm.zip](https://github.com/docker/docker/files/364054/li.rpm.zip)

**Comment by thaJeztah** [comment]
There are some issues in the issue tracker that may give some information, for example https://github.com/docker/docker/issues/18796, but there are others
