### ISSUE TITLE
Cannot join Swarm as Manager only

### ISSUE THREAD

**Issue by beverts312** [docker/docker#24596]
When joining a swarm, it is not possible to join as manager only. This behavior is not desirable in scenarios where we want dedicated masters.

**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   91e29e8
 Built:        Sat Jul  2 00:40:04 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   91e29e8
 Built:        Sat Jul  2 00:40:04 2016
 OS/Arch:      linux/amd64
 Experimental: true

```

**Comment by thaJeztah** [comment]
If I understand correctly, the intent is to join as manager, and set `--availability=drain` directly?

**Comment by beverts312** [comment]
Thats correct.

Thanks for bringing the `--availability=drain` feature to my attention

**Comment by abronan** [comment]
I think this might be in conflict with #24084 which discusses removing the `--manager` flag.

If we remove the flag this would make the process of having a manager only node very tedious (a scenario that is more likely to me on a real infrastructure than having both Manager/Agent node):

```
$ docker swarm join --listen-addr <node02-IP>:<port> <node01-IP>:<port>

# From node01
$ docker node promote node02 

$ docker node update --availability drain node02
```

/cc @aluzzardi @stevvooe

**Comment by aluzzardi** [comment]
@beverts312 Would promoting to a manager and then draining the node work for you? This would prevent any workload from being scheduled on that node

**Comment by beverts312** [comment]
@aluzzardi yep that would work for me since functionally it would achieve the same thing

That being said, I still think it makes sense to be able to join strictly as a manager and not have to run this extra step

**Comment by aaronlehmann** [comment]
I like the idea of being able to do `docker swarm join --availability=drain ...`. I think if it's two steps, some people may be concerned that work might be scheduled on the node in the window between the two commands. While this is probably not a big problem in practice, being able to join as a drained node would at least avoid pulling down images that you don't want on the manager, for example.
