### ISSUE TITLE
`GET /networks/` inspects the bridge network

### ISSUE THREAD

**Issue by mgoelzer** [docker/docker#24595]
**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.2
 Git commit:   906c1dc
 Built:        Fri Jun 17 16:48:48 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.2
 Git commit:   906c1dc
 Built:        Fri Jun 17 16:48:48 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge overlay null
Swarm: active
 NodeID: cjz9ffldhgrc2r5v4zj5vvmbi
 IsManager: Yes
 Managers: 1
 Nodes: 1
 CACertHash: sha256:9e85419452564689e7f8a5c72069ae4abe7a7e1ff48958a024e1451cc7c89d7a
Runtimes: default
Default Runtime: default
Security Options: apparmor seccomp
Kernel Version: 4.2.0-23-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: manager1
ID: 7SAZ:IYHI:XB25:GMRN:OLUS:ERHX:4LAL:2S7A:KLYS:EDL6:GAZM:PQGX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 35
 Goroutines: 109
 System Time: 2016-07-13T11:34:31.825999312-07:00
 EventsListeners: 0
Username: mikegoelzer
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Virtualbox

**Steps to reproduce the issue:**
```
$ curl --unix-socket /var/run/docker.sock http:/networks/ | jq .
```

**Describe the results you received:**
```
{
  "Name": "bridge",
  "Id": "63eb8a3bd519a737a1eadaa5143dd89ee832be08c8370f94a8c9f1dc7f7affde",
  "Scope": "local",
  "Driver": "bridge",
  "EnableIPv6": false,
  "IPAM": {
    "Driver": "default",
    "Options": null,
    "Config": [
      {
        "Subnet": "172.17.0.0/16",
        "Gateway": "172.17.0.1"
      }
    ]
  },
  "Internal": false,
  "Containers": {},
  "Options": {
    "com.docker.network.bridge.default_bridge": "true",
    "com.docker.network.bridge.enable_icc": "true",
    "com.docker.network.bridge.enable_ip_masquerade": "true",
    "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
    "com.docker.network.bridge.name": "docker0",
    "com.docker.network.driver.mtu": "1500"
  },
  "Labels": {}
}
```

**Describe the results you expected:**
I would either expect an error (because I am trying to inspect a network with an empty name) or a list of all networks (if it ignores the trailing slash).

**Additional information you deem important (e.g. issue happens only occasionally):**
Swarm mode is enabled

**Comment by mgoelzer** [comment]
I don't think this is related to swarm mode.  I did `docker swarm leave --force` and then repeated the curl command, and got the same result.

**Comment by aboch** [comment]
https://github.com/docker/docker/blob/v1.12.0-rc4/daemon/network.go#L66

**Comment by thaJeztah** [comment]
I think the issue may be that they're different routes; without trailing slash, it's "get a list of networks", and *with* trailing slash, it's get "a" network;

https://github.com/docker/docker/blob/v1.12.0-rc4/api/server/router/network/network.go#L33-L34

IIRC, we do that on other locations, so not sure if adding a `/` to the first one is sensible to do; most likely will be a breaking change

**Comment by mgoelzer** [comment]
@thaJeztah I think `/networks/` should produce an error then, because I'm asking to inspect a network with the name (empty string), which does not exist.

My hunch is that the problem is https://github.com/docker/docker/blob/ee981bcc73f3089627e734f983c6685dc5040b1b/daemon/network.go#L65 though changing the behavior of that function may have effects elsewhere, so I don't know if this issue is important enough to be worth bothering with.

**Comment by thaJeztah** [comment]
Perhaps changing the route to `/networks/{id:.+}` does the trick (making the ID required)
