### ISSUE TITLE
Remote API Exec Start introduces bad bytes in Stdout response

### ISSUE THREAD

**Issue by andrewmeissner** [docker/docker#24602]
**Output of `docker version`:**

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   8acee1b
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   8acee1b
 Built:        
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.10.3
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.5.7-coreos
Operating System: CoreOS 1010.6.0 (MoreOS)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.679 GiB
Name: redacted
ID: redacted

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running cassandra docker container on a CoreOS node in AWS.

**Steps to reproduce the issue:**
Using the remote API:
1. Create an exec attached to Stdout.  The command I used is `["find", "/", "-name", "testFiles"]`
2. Start the exec and pipe the response from curl to less.  less will display the garbage bytes that the api introduces into the response.
3.

**Describe the results you received:**
The remote API is introducing garbage bytes in the http response from Stdout.  This happens reliably on any remote call I make.

**Describe the results you expected:**
I expected what the CLI responds with, a normal response.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment]
Are you using `-t`?

**Comment by andrewmeissner** [comment]
I am not using tty - would that be the culprit?

Here's the payload of the `exec create` call:

```{"AttachStdin":false,"AttachStdout":true,"AttachStderr":true,"DetachKeys":"ctrl-p,ctrl-q","Tty":false,"Cmd":["find","/","-name","testFiles"]}```

And the payload for the `exec start` call is:

```{"Detach":false,"Tty":false}```

**Comment by cpuguy83** [comment]
@andrewmeissner Yes, because the stream is multiplexed to hold both stdout and stderr in a single stream, so each stream is prefixed with headers to denote stdout or stderr.

**Comment by cpuguy83** [comment]
See https://github.com/docker/docker/blob/master/pkg/stdcopy/stdcopy.go#L93

**Comment by andrewmeissner** [comment]
Thanks!  That totally solved it.  Sorry for the derp.  :(

**Comment by cpuguy83** [comment]
Glad that's all it was!
