### ISSUE TITLE
Cleanup docker service inspect

### ISSUE THREAD

**Issue by aluzzardi** [docker/docker#24601]
docker service inspect contains fields that do not exist. In `--pretty` mode, it also displays fields that have no value which provide little use but make the output harder on the eyes.

```
Placement:
 Strategy:	Spread
```

Placement strategy has been removed from SwarmKit. We should remove it from engine-api and inspect. /cc @dongluochen 

```
UpdateConfig:
 Parallelism:	0
```

In this case, the update config hasn't been set. I assume we're unable to make the difference between `0` and `default value` so I don't think there's anything we can do, right?

```
Resources:
Reservations:
Limits:
```

First of all, `Reservations` and `Limits` should be nested below Resources.

Also, when empty, we should probably not display them. For instance, when `Reservations` is empty, we skip it. If both `Reservations` and `Limits` are empty, we should skip the entire `Resources` section.

```
Ports:
 Name =
```

Is there even a way to name a port through the API/CLI? Should we remove the `name` altogether from the CLI? API? SwarmKit? /cc @mrjana @mavenugo 

/cc @vieux @dnephin @icecrime

**Comment by dongluochen** [comment]
@aluzzardi There is no `strategy` in [engine-api](https://github.com/docker/engine-api/blob/master/types/swarm/task.go#L77).

**Comment by vieux** [comment]
@dongluochen yes it's only printed in `--pretty`

**Comment by dnephin** [comment]
I think #24607 only fixed 2 of the 4 issues. Should this issue be re-opened ?

**Comment by thaJeztah** [comment]
@vdemeester ^^

**Comment by dnephin** [comment]
I'll get the other two

**Comment by dnephin** [comment]
> In this case, the update config hasn't been set. I assume we're unable to make the difference between 0 and default value so I don't think there's anything we can do, right?

Right, I think we should probably still display it?
