### ISSUE TITLE
Is is possible to get swarm node IP address from command `docker node ls` or `docker node inspect` ?

### ISSUE THREAD

**Issue by cmingxu** [docker/docker#24618]
**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
I don't think that's currently possible, but relates to https://github.com/docker/docker/issues/24226. I'll close this issue for now so that we can discuss on that issue

**Comment by thaJeztah** [comment]
Actually, there's also https://github.com/docker/docker/issues/24017
