### ISSUE TITLE
Docker 1.12 RC4: Unable to start container with SELinux enabled on Oracle Linux 7.2

### ISSUE THREAD

**Issue by sweekarp** [docker/docker#24612]
**Output of `docker version`:**

```
# docker version
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   a0f42b4
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   a0f42b4
 Built:        
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
# docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 5
Server Version: 1.12.0-rc4
Storage Driver: devicemapper
 Pool Name: docker-251:0-34815383-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.128 GB
 Data Space Total: 107.4 GB
 Data Space Available: 5.712 GB
 Metadata Space Used: 1.274 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null bridge host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.1.12-50.el7uek.netns.x86_64
Operating System: Oracle Linux Server 7.2
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 485.6 MiB
Name: localhost.localdomain
ID: Z4H2:K5TB:VIPY:FV57:JFSI:JM7M:DXE6:CTHJ:BYWP:KBFL:7QYF:T5RU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

```

**Output of `sestatus`:**

```
[root@localhost ~]# sestatus 
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      29

```

**Description of the problem:**
Unable to start containers with SELinux enabled. Containers start fine with SELinux in permissive mode

**Steps to reproduce the issue:**
1. Create a container with SELinux enabled on the host
```
# docker run -it --rm  oraclelinux:6.8 /bin/bash

```

**Describe the results you received:**
```
# docker run -it --rm  oraclelinux:6.8 /bin/bash
standard_init_linux.go:175: exec user process caused "permission denied"

```

**Describe the results you expected:**
```
# docker run -it --rm  oraclelinux:6.8 /bin/bash
[root@aab5f3f067db /]#
```

**Additional information you deem important (e.g. issue happens only occasionally):**

Changing the selinux context type for /usr/bin/docker* to docker_exec_t seems to fix the problem.

SELinux context before fix:

```
# ls -Z /usr/bin/docker*
-rwxr-xr-x. root root system_u:object_r:bin_t:s0       /usr/bin/docker
-rwxr-xr-x. root root system_u:object_r:bin_t:s0       /usr/bin/docker-containerd
-rwxr-xr-x. root root system_u:object_r:bin_t:s0       /usr/bin/docker-containerd-ctr
-rwxr-xr-x. root root system_u:object_r:bin_t:s0       /usr/bin/docker-containerd-shim
-rwxr-xr-x. root root system_u:object_r:docker_exec_t:s0 /usr/bin/dockerd
-rwxr-xr-x. root root system_u:object_r:bin_t:s0       /usr/bin/docker-proxy
-rwxr-xr-x. root root system_u:object_r:bin_t:s0       /usr/bin/docker-runc

```

SELinux context that is working:

```
# ls -Z /usr/bin/docker*
-rwxr-xr-x. root root system_u:object_r:docker_exec_t:s0 /usr/bin/docker
-rwxr-xr-x. root root system_u:object_r:bin_t:s0       /usr/bin/docker-containerd
-rwxr-xr-x. root root system_u:object_r:bin_t:s0       /usr/bin/docker-containerd-ctr
-rwxr-xr-x. root root system_u:object_r:bin_t:s0       /usr/bin/docker-containerd-shim
-rwxr-xr-x. root root system_u:object_r:docker_exec_t:s0 /usr/bin/dockerd
-rwxr-xr-x. root root system_u:object_r:bin_t:s0       /usr/bin/docker-proxy
-rwxr-xr-x. root root system_u:object_r:docker_exec_t:s0 /usr/bin/docker-runc

```
docker/contrib/docker-engine-selinux/docker.fc has context only defined for dockerd
```
/usr/bin/dockerd -- gen_context(system_u:object_r:docker_exec_t,s0)
```
I guess the context with docker_exec_t type needs to be defined for other /usr/bin/docker* binaries as well.

**Comment by crosbymichael** [comment]
@sweekarp thanks for the report, i'm looking into this today

**Comment by crosbymichael** [comment]
@sweekarp how did you install docker on your system?

**Comment by sweekarp** [comment]
@crosbymichael using an rpm that was created with 'make rpm'

**Comment by crosbymichael** [comment]
ok

**Comment by crosbymichael** [comment]
@sweekarp what is the best way to get an oracle install for me to test the package updates?

**Comment by thaJeztah** [comment]
@crosbymichael I think @Djelibeybi should be able to help you further

**Comment by Djelibeybi** [comment]
@crosbymichael you can download Oracle Linux from either http://edelivery.oracle.com (which requires an Oracle SSO account) or from one of our mirrors listed here: https://community.oracle.com/docs/DOC-917963

**Comment by Djelibeybi** [comment]
@crosbymichael FYI, I've asked our internal QA team to see if we can reproduce this with our 1.12-RC4 build.

**Comment by crosbymichael** [comment]
Thanks, i'm going to check it out as well and see if it requires the selinux package bump

**Comment by Djelibeybi** [comment]
@crosbymichael I shouldn't review issues at 4:30am. @sweekarp is on our QA team and logged this after internal 1.12-RC4 testing.

**Comment by thaJeztah** [comment]
Oh! Haha, didn't know @sweekarp was at Oracle, thanks!

**Comment by thtanaka** [comment]
@crosbymichael, just wondering whether the fix suggested above by (adding gen_context for additional docker binary in docker/contrib/docker-engine-selinux/docker.fc) make sense ?

**Comment by crosbymichael** [comment]
@thtanaka I think its a missmatch with the selinux profile that is being shipped and what is being applied in the rpm.  We need to sync them up, either bump the rpm version or rollback what is being shipped

**Comment by Djelibeybi** [comment]
@crosbymichael just FYI, @thtanaka is from Oracle too. Also, we use/ship the selinux RPM built as part of the overall Docker RPM process, so it's using whatever policies are used to create that RPM.

**Comment by thtanaka** [comment]
FWIW, @sweekarp might have missed the selinux denial log messages, so posted it here (the one that might be useful IMHO):
```
...
type=PROCTITLE msg=audit(1468959253.893:8177): proctitle=2F7573722F62696E2F646F636B65722D72756E6300696E6974
type=AVC msg=audit(1468959254.055:8178): avc:  denied  { transition } for  pid=16972 comm="exe" path="/usr/bin/bash" dev="dm-1" ino=296 scontext=system_u:system_r:unconfined_service_t:s0 tcontext=system_u:system_r:svirt_lxc_net_t:s0:c318,c851 tclass=process permissive=0
...
```

**Comment by crosbymichael** [comment]
thanks for the updated info, i'll try to figure what will be the best fix today unless you all beat me to it

**Comment by crosbymichael** [comment]
@thtanaka @sweekarp i'm having a little trouble getting an environment setup for testing right now but if you have time can you try to rebuild the RPMs based on this commit? 

https://github.com/crosbymichael/docker/commit/cb5824959297bf67737a21b6a39ed2a1c80227b8

It updates the selinux package for the docker_exec_t label.  I think this should work for the issues that you are seeing but I cannot test at the moment.

**Comment by thtanaka** [comment]
Thanks @crosbymichael will test this out and will let you know

**Comment by Djelibeybi** [comment]
@crosbymichael that pull from Atomic won't work here, because it relies on another package (`docker-selinux`) which is not part of this source tree and is not built or required by `docker-engine-selinux`. In fact, from memory the `docker-engine-selinux` package was specifically created so as not to rely on the vendor-provided `docker-selinux` policies.

**Comment by crosbymichael** [comment]
yes that is the reason.  Maybe I missed replacing a line renaming the package.  It shouldn't depend on anything else because those two packages are the same

**Comment by Djelibeybi** [comment]
We're getting build errors with the patch provided. I'll let @thtanaka comment on those as he is responsible for merge/build internally.

**Comment by thtanaka** [comment]
Couple of errors:
0. docker.if:131: Error: duplicate definition of apache_exec(). Original definition on 277.
    Compiling targeted docker module
    docker.te":273:ERROR 'syntax error' at token 'fs_manage_nsfs_files' on line 11922:
    fs_manage_nsfs_files(docker_t)
1. docker.te":301:ERROR 'syntax error' at token 'systemd_dbus_chat_machined' on line 14522:
		systemd_dbus_chat_machined(docker_t)
2. docker.te":324:ERROR 'syntax error' at token 'unconfined_typebounds' on line 16760:
	unconfined_typebounds(docker_t)
3. docker.te":329:ERROR 'syntax error' at token 'virt_sandbox_entrypoint' on line 17348:
	virt_sandbox_entrypoint(docker_t)

**Comment by limbo9991** [comment]
Plugging in now

Hello world

**Comment by thaJeztah** [comment]
ping @crosbymichael were you able to find something on this one?

**Comment by gearoidibm** [comment]
Seeing this on RHEL with latest 1.12 - did this fix not make 1.12.0 ?

**Comment by thtanaka** [comment]
@crosbymichael,

I still hit similar error messages. Not sure you are aware, but selinux-policy that shipped with OL might not be as new as the Fedora one. So here is what I did to make it at least be able to built:

* Commented out **systemd_dbus_chat_machined**, because we do not have systemd_dbus_chat_machined interface defined, if we include this interface definition we might also needs systemd_machined_var_run_t, etc and also the policy for each of those interfaces, which might turn out to be quite messy.

* Remove the re-definition of apache_exec
```
-######################################
-##     Allow the specified domain to execute apache
-##     in the caller domain.
-##     <summary>
-##     Domain allowed access.
-##     </summary>
-interface(`apache_exec',`
-       gen_require(`
-               type httpd_exec_t;
-       ')
-       can_exec($1, httpd_exec_t)
- ')
```
* Add svirt_sandbox_file_t interface definition:
```
+########################################
+##     Allow any svirt_sandbox_file_t to be an entrypoint of this domain
+## </summary>
+## <param name="domain">
+##     <summary>
+##     Domain allowed access.
+##     </summary>
+## </param>
+## <rolecap/>
+#
+interface(`virt_sandbox_entrypoint',`
+       gen_require(`
+               type svirt_sandbox_file_t;
+       ')
+       allow $1 svirt_sandbox_file_t:file entrypoint;
+')
+
```

* Add unconfined_typebounds interface definition:
```
+########################################
+##     unconfined_t domain typebounds calling domain.
+## <summary>
+##     Domain to be typebound.
+## </summary>
+interface(`unconfined_typebounds',`
+       gen_require(`
+               type unconfined_t;
+       ')
+       typebounds unconfined_t $1;
+')
```

**Comment by crosbymichael** [comment]
@thtanaka ok I force pushed a new revision to that branch.  It has the ability to specify different policies for different distros/versions. 

Here is the magic switch that we have to add OL to:

https://github.com/crosbymichael/docker/commit/cb4c0e250ae0854bcccd5bf16ac877b9a6a84eb1#diff-e31231b83c6cce3f5b6f1ef1d6bac5d1R138


If OL has to differ then we can use this layout to achieve the results.  Do you want to cp the `selinux-fedora` dir into a `selinux-oraclelinux` dir and make the needed changes?  You can push your commit to a fork and i'll cherry pick it into my PR and we can get it merged at the same time or I can get mine merged in first and you can do a follow up pr.

**Comment by thtanaka** [comment]
Thanks @crosbymichael, whatever is the most convenience for you. I can do a follow up PR if necessary, since I guess once I got this RPM built I would like it to go through the QA process internally to see if everything works.

**Comment by crosbymichael** [comment]
@thtanaka ok, a follow up PR sounds good to me. i'll open mine

**Comment by jimmidyson** [comment]
I'm also hitting this on Fedora 24 with 1.12.0 from Docker fc24 repos.

**Comment by thaJeztah** [comment]
@jimmidyson would you be able to build an RPM from https://github.com/docker/docker/pull/25334, and see if it's resolved?

**Comment by jimmidyson** [comment]
@thaJeztah Tried but can't build rpm with `make rpm`:

```
---> Making bundle: build-rpm (in bundles/1.13.0-dev/build-rpm)
INFO: Waiting for daemon to start...
+++ exec dockerd --debug --host unix:///go/src/github.com/docker/docker/bundles/1.13.0-dev/build-rpm/docker.sock --storage-driver devicemapper --pidfile bundles/1.13.0-dev/build-rpm/docker.pid --userland-proxy=true
...........................................................
error: daemon at unix:///go/src/github.com/docker/docker/bundles/1.13.0-dev/build-rpm/docker.sock fails to 'docker version':
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.6.3
 Git commit:   ea99976
 Built:        Wed Aug  3 17:05:39 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
---> Making bundle: .integration-daemon-stop (in bundles/1.13.0-dev/build-rpm)
Makefile:114: recipe for target 'rpm' failed
make: *** [rpm] Error 1
```

**Comment by thtanaka** [comment]
@jimmidyson, try this https://github.com/docker/docker/issues/23809 ?

**Comment by jimmidyson** [comment]
@thtanaka No luck - same issue, although the recommended DOCKER_STORAGE_OPTS are passed through properly:

```
---> Making bundle: build-rpm (in bundles/1.13.0-dev/build-rpm)
INFO: Waiting for daemon to start...
+++ exec dockerd --debug --host unix:///go/src/github.com/docker/docker/bundles/1.13.0-dev/build-rpm/docker.sock --storage-driver devicemapper --pidfile bundles/1.13.0-dev/build-rpm/docker.pid --userland-proxy=true --storage-opt dm.override_udev_sync_check=true
...........................................................
error: daemon at unix:///go/src/github.com/docker/docker/bundles/1.13.0-dev/build-rpm/docker.sock fails to 'docker version':
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.6.3
 Git commit:   ea99976
 Built:        Wed Aug  3 20:19:01 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
---> Making bundle: .integration-daemon-stop (in bundles/1.13.0-dev/build-rpm)
Makefile:114: recipe for target 'rpm' failed
make: *** [rpm] Error 1
```

Probably because of my storage options... I'll try it in a clean VM tomorrow.

**Comment by jimmidyson** [comment]
@thaJeztah Didn't work... will comment on the PR.

**Comment by thtanaka** [comment]
@jimmidyson,

Hm, this looks like you picked up the `contrib/selinux/docker-engine-selinux/` instead of the `contrib/selinux-fedora/docker-engine-selinux/`, so in the "mainline" docker-engine-selinux (`contrib/selinux/docker-engine-selinux`) you will see `virt_sandbox_use_fusefs` related tunable variable defined in docker.te file. while it is *not* defined in the selinux-fedora one.  As such that might conflict with your existing Fedora 24 selinux-policy module specifically `virt`.

**Comment by jimmidyson** [comment]
@thtanaka That very well may be, but all I wanted to try out was whether the new selinux RPM from @crosbymichael's PR worked. Seems it didn't. Sadly I don't have loads of time to investigate what's gone wrong here. I'm happy to help out testing & verifying any potential fixes though.
