### ISSUE TITLE
Docker Remote API `containers/json` does not respect specified API version number

### ISSUE THREAD

**Issue by fonglh** [docker/docker#24616]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   91e29e8
 Built:        Sat Jul  2 00:09:24 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   876f3a7
 Built:        Tue Jul  5 02:20:13 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 19
 Running: 1
 Paused: 0
 Stopped: 18
Images: 9
Server Version: 1.12.0-rc3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 60
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.14-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.954 GiB
Name: moby
ID: 2DSY:BZFE:2LSD:RS2O:KQWU:HAWE:H6DW:SXZ5:ZPHJ:ZMYY:X2TY:P35F
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 23
 Goroutines: 43
 System Time: 2016-07-14T01:29:33.766456833Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker for Mac

**Steps to reproduce the issue:**
1. Start a container. `docker run -it ubuntu /bin/bash`
2. Use the API to get information. `curl --unix-socket /var/run/docker.sock http:/containers/json`
3. Specify an older version of the API. `curl --unix-socket /var/run/docker.sock http:/v1.22/containers/json`

**Describe the results you received:**

1. API version 1.24
    ```[{"Id":"c0cf517247df0c0b4dbc17c78e09582a017c0a15c45b5031cd7297fe459ae416","Names":["/hungry_heisenberg"],"Image":"ubuntu","ImageID":"sha256:12543ced0f6f754223eff4cca67b56cbf9f384456ab9deaa824ba9ff28bcfdd6","Command":"/bin/bash","Created":1468459844,"Ports":[],"Labels":{},"State":"running","Status":"Up 33 seconds","HostConfig":{"NetworkMode":"default"},"NetworkSettings":{"Networks":{"bridge":{"IPAMConfig":null,"Links":null,"Aliases":null,"NetworkID":"dfddde6472aac68727b764d95aa8f613075db2b9dc692051c1135340d0532f7a","EndpointID":"b89d95007c1d903d8e5ded3493b9b4160c4d084628ae1c38614f3432ab62b4d6","Gateway":"172.17.0.1","IPAddress":"172.17.0.2","IPPrefixLen":16,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"02:42:ac:11:00:02"}}},"Mounts":[]}]```
2. API version 1.22
```[{"Id":"c0cf517247df0c0b4dbc17c78e09582a017c0a15c45b5031cd7297fe459ae416","Names":["/hungry_heisenberg"],"Image":"ubuntu","ImageID":"sha256:12543ced0f6f754223eff4cca67b56cbf9f384456ab9deaa824ba9ff28bcfdd6","Command":"/bin/bash","Created":1468459844,"Ports":[],"Labels":{},"State":"running","Status":"Up About a minute","HostConfig":{"NetworkMode":"default"},"NetworkSettings":{"Networks":{"bridge":{"IPAMConfig":null,"Links":null,"Aliases":null,"NetworkID":"dfddde6472aac68727b764d95aa8f613075db2b9dc692051c1135340d0532f7a","EndpointID":"b89d95007c1d903d8e5ded3493b9b4160c4d084628ae1c38614f3432ab62b4d6","Gateway":"172.17.0.1","IPAddress":"172.17.0.2","IPPrefixLen":16,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"02:42:ac:11:00:02"}}},"Mounts":[]}]```

**Describe the results you expected:**

v1.22 and older veresions of the API should not return `"State":"running"` as this was only added in [v1.23](https://docs.docker.com/engine/reference/api/docker_remote_api/#/v1-23-api-changes)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
Thanks for reporting @fonglh. The API uses an "open schema", which means that new properties *may* be added to older API versions if a newer daemon is used. However, it should still be compatible with older clients.

This is described in the documentation; https://github.com/docker/docker/blob/v1.11.2/docs/reference/api/docker_remote_api.md

> Docker's Remote API uses an open schema model. In this model, unknown properties in incoming messages are ignored. Client applications need to take this behavior into account to ensure they do not break when talking to newer Docker daemons.

Perhaps the wording for this could be slightly improved; if you have suggestions, we welcome pull requests to improve that.

I'll close this issue, because this is expected, but feel free to comment after I closed

**Comment by fonglh** [comment]
Thanks @thaJeztah. I didn't realise that meant it could return new properties too

Will submit a PR if I have suggestions to improve the wording.

**Comment by thaJeztah** [comment]
Thanks @fonglh, I've seen other people being confused by this, so I think that warrants an improvement to the docs. I'll open an issue for that for tracking

**Comment by thaJeztah** [comment]
Opened: https://github.com/docker/docker/issues/24632
