### ISSUE TITLE
Issue with defining ssh_size in docker-compose.yml file

### ISSUE THREAD

**Issue by kausik93** [docker/docker#24626]
Hi, I'm new to Docker and I'm trying to increase the ssh-size. I had issues running my LDA models with the default ssh-size (=64m). I found the documentation on changing it in my docker run command prompt and after adding --shm-size=512m I got it to work. 

BUT, I want to add it to my docker-compose.yml file instead. I've looked up and found this [documentation](https://docs.docker.com/compose/compose-file/). But when I try to include it, it doesn't have any effect on the shm-size. Does anyone know why? (i've included my code for .yml and .yml.example) Thanks!

  docker-compose.yml file:
  version: '2'

  networks:
    swarm:
    public:

  services:
    # Redis server
    # to store user/session keys
    # to pub/sub between manager and containers
    redis:
      image: redis:3.0
      container_name: redis
      command: redis-server --appendonly yes
      networks:
        - swarm
      ports:
        - 6379:6379
      expose:
       - 6379
      volumes:
       - /mnt/docstore/redis:/data

    # hapi server
    # to jwt authentication
    # to serve API requests and manage docker containers
    hapi:
      build: ./textanalytics-manager
      container_name: hapi
      working_dir: /app
      command: pm2 start --no-daemon index.js
      depends_on:
        - redis
      networks:
        - swarm
        - public
      expose:
        - 80
      env_file:
        - ./textanalytics-manager.env
      volumes:
        - /mnt/docstore/userdata:/mnt/docstore
        - /mnt/docstore/log/authserver:/app/logs

    # temp front-end
    # gulp process for PolymerJS webapp
    #polymer:
    #  image: registry.text:5000/sap
    #  container_name: polymer
    #  expose:
    #    - 5000
    #  volumes:
    #    - /home/ebs/git/text@hiveoss/gulpfile.js:/usr/src/app/gulpfile.js
    #    - /home/ebs/git/text@hiveoss/dist:/usr/src/app/dist
    #    - /home/ebs/git/text@hiveoss/app:/usr/src/app/app
    #    - /home/ebs/git/hiveoss-authentication:/usr/src/app/app/bower_components/hiveoss-authentication
    #    - /home/ebs/git/hiveoss-dataframe:/usr/src/app/app/bower_components/hiveoss-dataframe
    #    - /home/ebs/git/hiveoss-dragdrop-box:/usr/src/app/app/bower_components/hiveoss-dragdrop-box
    #    - /home/ebs/git/hiveoss-shared-animatable:/usr/src/app/app/bower_components/hiveoss-shared-animatable

    # ngnix reverse proxy
    nginx:
      container_name: nginx
      image: nginx:1.10
      ports:
        - 80:80
        - 443:443
      depends_on:
        - polymer
        - hapi
      networks:
        - public
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/ssl:/etc/nginx/ssl:ro
        - ./text@hiveoss/app:/var/www:ro
        - /mnt/docstore/log/nginx:/var/logs

  shm_size: 512M

  docker-compose.yml.example file:
  version: '2'

  networks:
    swarm:
    public:

  volumes:
    mongodata:

  services:
    # mongodb
    mongo:
      image: mongo:3.2
      container_name: mongo
      command: mongod --storageEngine wiredTiger
      networks:
        - swarm
      expose:
        - 27017
      ports:
        - 27017:27017
      volumes:
        #- ./data/mongo:/data/db
        - mongodata:/data/db

    # Redis server
    # to store user/session keys
    # to pub/sub between manager and containers
    redis:
      image: redis:3.0
      container_name: redis
      command: redis-server --appendonly yes
      networks:
        - swarm
      ports:
        - 6379:6379
      expose:
       - 6379
      volumes:
       - ./data/redis:/data

    # hapi server
    # to jwt authentication
    # to serve API requests and manage docker containers
    hapi:
      build: ./textanalytics-manager
      container_name: hapi
      working_dir: /app
      command: pm2 start --no-daemon index.js
      networks:
        - swarm
        - public
      depends_on:
        - redis
        - mongo
        - elasticsearch
      expose:
        - 80
      env_file:
        - ./textanalytics-manager.env.example
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./data/users:/mnt/nfs/userdata
        - ./logs/manager:/app/logs

    # ngnix reverse proxy
    nginx:
      container_name: nginx
      #image: nginx:1.10
      build: ./nginx
      networks:
        - public
      ports:
        - 80:80
        - 443:443
      depends_on:
        - hapi
      volumes:
        #- ./nginx/nginx.conf.example:/etc/nginx/nginx.conf
        #- ./nginx/ssl:/etc/nginx/ssl:ro
        - ./textanalytics-frontend:/var/www:ro
        - ./logs/nginx:/var/logs

    # elasticsearch full text search engine
    elasticsearch:
      container_name: elasticsearch
      image: elasticsearch:2.3
      networks:
        - swarm
      ports:
        - 9200:9200
        - 9300:9300
      volumes:
        - ./data/es:/usr/share/elasticsearch/data

    # kibana to view es
    kibana:
      container_name: kibana
      image: kibana:4.5
      networks:
        - swarm
      ports:
        - 5601:5601
      depends_on:
        - elasticsearch

**Comment by justincormack** [comment]
Hi, your formatting has gone a bit awry, so it is hard to see where you have put it - can you edit and fix the layout?. Are you using a recent version of docker compose? It was added a few releases back, so if you still have an old version it might not work. You might be better off opening an issue in https://github.com/docker/compose as this is specifically a compose issue though, and you will get help faster probably.

**Comment by thaJeztah** [comment]
agreed, please reopen in the docker compose issue tracker. thanks!
