### ISSUE TITLE
Need advice to fix system

### ISSUE THREAD

**Issue by pantaoran** [docker/docker#24624]
My colleague shot himself in the foot with Linux and now his Docker doesn't work properly anymore.
In a dev project he executed `sudo chmod -R 755 /var` where he used `/var` instead of the local `var` folder. He doesn't really understand Linux too well, and now it's my job to fix it :-(

Now when I start containers it seems successful, but `docker ps` doesn't list them and I cannot enter them with `docker exec` because it says that they're not running.

Does anyone have any advice on what I could do?

**Output of `docker version`:**

```
Docker version 1.11.2, build b9f10c9
```

**Output of `docker info`:**

```
docker info
Containers: 32
 Running: 0
 Paused: 0
 Stopped: 32
Images: 268
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 409
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.16.0-73-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.732 GiB
Name: vbrand
ID: 54EH:YHSQ:4XBT:FNYF:C5DJ:T45Q:LHUD:AXUL:KVDT:AENP:2UHU:WGAA
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Ubuntu 14.04

**Comment by thaJeztah** [comment]
Sorry, this is not the place for such questions, The GitHub issue tracker is for tacking bugs and feature requests, not a support forum. Please use either one of;

- forums.docker.com
- the #docker IRC channel on freenode
- StackOverflow
