### ISSUE TITLE
Boot2Docker recognizing only 8 cpu's from Windows 8 host workstation, with virtualbox drivers

### ISSUE THREAD

**Issue by kjkunte** [docker/docker#24635]
**Output of `docker version`:**
Docker  version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      windows/amd64

**Output of `docker info`:**
Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64
**Additional environment details (AWS, VirtualBox, physical, etc.):**
Windows 8.1 pro workstation, with 24 virtual processors and 12 actual cores
![taskmanager](https://cloud.githubusercontent.com/assets/4727323/16840634/607474f0-49f3-11e6-973f-85d4aced4763.png)

**Steps to reproduce the issue:**
1. docker-machine create --virtualbox-cpu-count -1 -d virtualbox dev1
2. docker-machine ssh dev cat /proc/cpuinfo>log
3.

**Describe the results you received:**
1. Step 1 descibed above should create a docker-machine called dev1 with 24 virtual processors, which shown in the image below
![dev1](https://cloud.githubusercontent.com/assets/4727323/16840807/4025d9c2-49f4-11e6-9ab2-0e814edec2d9.png)

2. The result of the step 2 is attached in the log file here : 
[log1.txt](https://github.com/docker/docker/files/363802/log1.txt)

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment]
Thanks for reporting, but this really belongs on github.com/boot2docker/boot2docker

Thanks!

**Comment by kjkunte** [comment]
Are you suggesting me to  post this in boot2docker : github.com/boot2docker/boot2docker ?

**Comment by cpuguy83** [comment]
@kjkunte Yes, that way the maintainers for boot2docker can have a look.

**Comment by kjkunte** [comment]
Thanks, I will do that.
