### ISSUE TITLE
Service without labels returns null, not {}

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#24631]
if no labels are set on a service, `Spec.Labels` is `null`, not an empty map/object;

``` bash
$ docker service create --name nolabels nginx:alpine
$ docker service inspect --format '{{ json .Spec.Labels}}' nolabels
null
```

This is inconsistent with containers, where it's always a map/object;

``` bash
$ docker run --name nolabels busybox sh
$ docker inspect --format '{{json .Config.Labels }}' nolabels
{}
```

I think we should fix that, to keep consistency in our UX.

**Comment by vdemeester** [comment]
Agreeing on the inconsistency, I'll take a look.
#dibs 👼

**Comment by thaJeztah** [comment]
@vdemeester Thanks! I didn't check other properties (env-vars, etc), so those may need a change as well. Also didn't compare the API between "containers" and "services"

**Comment by thaJeztah** [comment]
ping @vdemeester just found this one, did we ever change this?

**Comment by adshmh** [comment]
#dibs

A few other types also behave the same, e.g.:  

$ docker node inspect --format '{{ json .Spec.Labels }}' self
null
