### ISSUE TITLE
Error response from daemon: rpc error: code = 2 desc = raft: failed to process the request: node lost leader status

### ISSUE THREAD

**Issue by cohenaj194** [docker/docker#24643]
I am running docker swarm with 6 nodes (3 managers with `--availability drain`, 3 workers).  After restarting my `docker swarm init` node, for failure testing, running any `docker service create`, `docker service scale` or `docker service rm` from that node produces the following error (note that I can still run `docker service inspect` or `docker service ls`):

    Error response from daemon: rpc error: code = 2 desc = raft: failed to process the request: node lost leader status

My other managers which joined the cluster through `docker swarm join --manager` do not have this issue.

Here is the info of my cluster:

    myUsername@consul0-3395:~$ docker node ls
    ID                           HOSTNAME      MEMBERSHIP  STATUS  AVAILABILITY  MANAGER STATUS
    1x5c7z7dfx5ux2h7i0s5wnj5x    consul1-8393  Accepted    Ready   Drain         Leader
    2if6xk3ob5xqka6bogxmqq13p    client1-4459  Accepted    Ready   Active        
    35knxsywfywva8x1498hg9laf    consul2-5397  Accepted    Ready   Drain         Reachable
    73vktr95dww5fa25pkj0fcz1b *  consul0-3395  Accepted    Ready   Drain         Reachable
    8jv7z1hmthp67w0g03s5jx4cg    client2-6461  Accepted    Ready   Active        
    ae0zmi6ttmamexauts7rop9mb    client0-8463  Accepted    Ready   Active   

Version:
    
    myUsername@consul0-3395:~$ docker --version
    Docker version 1.12.0-rc4, build e4a0dbc, experimental
    
    
        
`docker swarm init` node info:
    
    myUsername@consul0-3395:~$ docker info
    Containers: 1
     Running: 1
     Paused: 0
     Stopped: 0
    Images: 1
    Server Version: 1.12.0-rc4
    Storage Driver: aufs
     Root Dir: /var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 10
     Dirperm1 Supported: true
    Logging Driver: json-file
    Cgroup Driver: cgroupfs
    Plugins:
     Volume: local
     Network: null bridge host overlay
    Swarm: active
     NodeID: 73vktr95dww5fa25pkj0fcz1b
     IsManager: Yes
     Managers: 3
     Nodes: 6
     CACertHash: sha256:723c6f8b67d008a2f1bee8e6f5cb8c764296a74a64f93b7a726147d90e43aaff
    Runtimes: runc
    Default Runtime: runc
    Security Options: apparmor
    Kernel Version: 4.2.0-30-generic
    Operating System: Ubuntu 14.04.4 LTS
    OSType: linux
    Architecture: x86_64
    CPUs: 2
    Total Memory: 5.829 GiB
    Name: consul0-3395
    ID: 2T4V:LRQX:THHI:D6CW:EH3D:LT2V:KLVW:UXC5:OMDF:3EHR:WY7R:WQOX
    Docker Root Dir: /var/lib/docker
    Debug Mode (client): false
    Debug Mode (server): false
    Registry: https://index.docker.io/v1/
    WARNING: No swap limit support
    Experimental: true
    Insecure Registries:
     127.0.0.0/8
    
    
    
One of my other managers:
    
    myUsername@consul1-8393:~$ docker info
    Containers: 1
     Running: 1
     Paused: 0
     Stopped: 0
    Images: 1
    Server Version: 1.12.0-rc4
    Storage Driver: aufs
     Root Dir: /var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 10
     Dirperm1 Supported: true
    Logging Driver: json-file
    Cgroup Driver: cgroupfs
    Plugins:
     Volume: local
     Network: overlay null host bridge
    Swarm: active
     NodeID: 1x5c7z7dfx5ux2h7i0s5wnj5x
     IsManager: Yes
     Managers: 3
     Nodes: 6
     CACertHash: sha256:723c6f8b67d008a2f1bee8e6f5cb8c764296a74a64f93b7a726147d90e43aaff
    Runtimes: runc
    Default Runtime: runc
    Security Options: apparmor
    Kernel Version: 4.2.0-30-generic
    Operating System: Ubuntu 14.04.4 LTS
    OSType: linux
    Architecture: x86_64
    CPUs: 2
    Total Memory: 5.829 GiB
    Name: consul1-8393
    ID: 77XZ:UWFN:QDGO:5OA2:LIJY:XZWO:7XV7:2TI7:CNA3:V34J:B4OJ:BTPE
    Docker Root Dir: /var/lib/docker
    Debug Mode (client): false
    Debug Mode (server): false
    Registry: https://index.docker.io/v1/
    WARNING: No swap limit support
    Experimental: true
    Insecure Registries:
     127.0.0.0/8
    
    
One of my Clients:
    
    myUsername@client0-8463:~$ docker info
    Containers: 2
     Running: 2
     Paused: 0
     Stopped: 0
    Images: 2
    Server Version: 1.12.0-rc4
    Storage Driver: aufs
     Root Dir: /var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 20
     Dirperm1 Supported: true
    Logging Driver: json-file
    Cgroup Driver: cgroupfs
    Plugins:
     Volume: local
     Network: bridge overlay null host
    Swarm: active
     NodeID: ae0zmi6ttmamexauts7rop9mb
     IsManager: No
    Runtimes: runc
    Default Runtime: runc
    Security Options: apparmor
    Kernel Version: 4.2.0-30-generic
    Operating System: Ubuntu 14.04.4 LTS
    OSType: linux
    Architecture: x86_64
    CPUs: 2
    Total Memory: 5.829 GiB
    Name: client0-8463
    ID: LZ3S:IJCQ:VREK:JPWT:WVRU:IXVR:KU44:4CDY:KAKZ:P3LB:JJRB:NA3B
    Docker Root Dir: /var/lib/docker
    Debug Mode (client): false
    Debug Mode (server): false
    Registry: https://index.docker.io/v1/
    WARNING: No swap limit support
    Experimental: true
    Insecure Registries:
     127.0.0.0/8

**Comment by cpuguy83** [comment]
ping @tiborvass @LK4D4

**Comment by cpuguy83** [comment]
@cohenaj194 Is this happening for every request on that node?

**Comment by cohenaj194** [comment]
It only occurred on the first node of the cluster that joined swarm with `docker swarm init`, but in the last few days the issue has mysteriously disappeared and the `docker swarm init` node is working just fine now.  If no one can recreate the error message then I will probably close this issue in a few days.

**Comment by thaJeztah** [comment]
Thanks, I'll close this issue; but ping me if you see this happening again, then I'll reopen

**Comment by konikris** [comment]
Still facing the same issue, can you please help on this.

**Comment by thaJeztah** [comment]
@konikris please open a new issue with details and steps to reproduce. The issue here was reported with a pre-release of docker 1.12 and a lot has changed since, so best to open a separate issue
