### ISSUE TITLE
`docker run` neither fails nor warns when using an image that includes VOLUME but is unmapped at runtime

### ISSUE THREAD

**Issue by matthewadams** [docker/docker#24647]
**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:13:28 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
$ docker info
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 27
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 65
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.19-boot2docker
Operating System: Boot2Docker 1.11.0 (TCL 7.0); HEAD : 32ee7e9 - Wed Apr 13 20:06:49 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.956 GiB
Name: default
ID: 62HA:JZ2M:I6EU:MVNF:YEC7:XK24:CMHW:PKNH:MZN6:QQ6P:2M2U:IJIL
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 29
 Goroutines: 54
 System Time: 2016-07-14T19:19:01.861231413Z
 EventsListeners: 0
Username: matthewadams12
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
* Mac OS X El Capitan 10.11.5 (15F34)
* MacBook Pro (Retina, Mid 2012)
* Oracle VirtualBox 5.0.24 r108355

**Steps to reproduce the issue:**

* Create a temporary working directory & change to it:
```
$ mkdir tmp
$ cd tmp
```
* Create a `Dockerfile` in `$PWD` with the following contents:
```
FROM alpine:3.4
VOLUME /app
```
* Create image from `Dockerfile`:
```
$ docker build -t hasappvol .
```
* Run an ephemeral (`--rm`) container based on the image _without_ mapping a local directory to the container's volume `/app` & see that it produces zero errors or warnings about the unmapped `VOLUME /app`:
```
$ docker run -it --rm hasappvol touch /app/reallyimportantfile
```

**Describe the results you received:**

Nothing written to `stdout` or `stderr`; container successfully ran with exit code `0`.  File `reallyimportantfile` doesn't exist.

**Describe the results you expected:**

I expected an error or warning sent to `stderr` informing me that the `VOLUME /app` was not mapped (say, via `-v "$PWD":/app`) when the container ran:
```
$ docker run -it --rm hasappvol touch /app/iamhere
docker: Warning response from daemon: Container expected VOLUME /app to be mapped, but no mapping was provided.
```

`docker build` could be enhanced to offer an option `-r|--require-volumes [dir1[,dir2[, ...]]]` that optionally takes a list of volumes that _must_ be mapped when the container runs, or the option could be specified multiple times, like `--require-volume dir1 --require-volume dir2 ...`.  The default value of the `-r|--require-volumes` (with an `s`) argument, if present, would be all `VOLUME`s specified by the image, and, if not present, would be empty.  Alternatively, the `VOLUME` Dockerfile command could be enhanced or a new command could be created to provide this behavior.  The enhance or new Dockerfile command could be instead of or in addition to the proposed `-r|--require-volume[s]' `docker build` argument(s).

If a container based on the image then runs and not all required `VOLUME`s are mapped, the process writes this fact to `stderr` and returns an error code.

The next most conservative behavior would be to issue a warning to `stderr` if any `VOLUME`s are defined but are unmapped.

The current behavior, and impetus for this issue, is that `docker run` executes successfully, and any files created by the ephemeral container intended to be written to the directory mapped to `/app` are lost.

**Comment by matthewadams** [comment]
@thaJeztah, based on your comments, I'm ok with not emitting a warning, but image creators should be able to say which volumes are required or not.  By saying nothing, you get the current behavior.  By saying, "Hey, if you don't map a directory to this volume, you'll be wasting time," we avoid said waste.

We have a use case where we're using a container to generate an application.  When we `docker run` the image that generates the application, we want to ensure that the volume to which the application is written is mapped, otherwise the generated application will be lost.

**Comment by thaJeztah** [comment]
The problem, is that it *is* mapped (to a volume), just not a bind-mount, so having to define that would become *really* specific, and may just as well be solved with proper documentation. For your use-case, perhaps consider using a `docker-compose.yml` file, or a `makefile` that sets the right parameters for `docker run`.

**Comment by thaJeztah** [comment]
I'm closing this issue, because I don't think we should implement this (see my earlier comments), but feel free to continue the discussion after I closed
