### ISSUE TITLE
[1.12 rc4-beta19 docker for mac] release notes: date 2016-07-03?

### ISSUE THREAD

**Issue by llitfkitfk** [docker/docker#24658]
https://docs.docker.com/docker-for-mac/release-notes/

**Comment by justincormack** [comment]
@londoncalling the date does appear to be wrong on that page...

**Comment by londoncalling** [comment]
Ok Justin, sorry I'll change it and re-push the docs. If you see anything
else let me know and I'll get the changes in.

**Comment by cpuguy83** [comment]
Thanks for reporting!
Going to close this for house-keeping purposes.
