### ISSUE TITLE
How to access the data of Docker 1.12 internal distributed state store ?

### ISSUE THREAD

**Issue by deathrush** [docker/docker#24664]
How to access the data of Docker 1.12 internal distributed state store ?
Is there a client to do that?

**Comment by thaJeztah** [comment]
I think this question more relates to SwarmKit, which is the library used for managing Swarm Mode related parts https://github.com/docker/swarmkit

/cc @abronan

**Comment by abronan** [comment]
Hi @deathrush,

The distributed store essentially contains the informations available on the docker API. So docker is the client to the datastore.

Everything you need from the datastore is accessible through the gRPC API when querying objects. You can use `swarmctl` in the [swarmkit repository](https://github.com/docker/swarmkit) to do that or use tools like https://github.com/grpc-ecosystem/polyglot (a universal gRPC client) to query the swarmkit gRPC API directly.

Hope this answers your question.

**Comment by thaJeztah** [comment]
Thanks @abronan. I'll close this issue, but @deathrush feel free to continue the discussion
