### ISSUE TITLE
Old service containers aren't removed after docker service update "renaming"

### ISSUE THREAD

**Issue by mostolog** [docker/docker#24670]
Hi

We are running a service (logstash) which loads the configuration files at startup:

> docker service create --mount type=bind,source=/**blue**/config,target=/etc/logstash/ --name logstash-**blue** --replicas 10 logstash

The containers are started and visible with _docker ps -a_
After testing some changes, we would like to have a rolling update without downtime.
To do it, I was trying to do:

> docker service update --mount type=bind,source=/**green**/config,target=/etc/logstash/ --name logstash-**green** --replicas 10 logstash-**blue**

If I understood correctly, this should replace each container with the new configuration.
Instead of that, _docker ps -a_ is showing **both of them**: logstash-blue running and logstash-green stopped, which IMHO shouldn't happen.
Furthermore, I'm not able to remove old service using docker _service rm logstash-blue_ (which makes sense if service is renamed).

Regards

**Comment by thaJeztah** [comment]
I think this is a duplicate of https://github.com/docker/docker/issues/24394, the difference being that this issue isn't about "faulty" containers. Can you try updating the `--task-history-limit`, as suggested in https://github.com/docker/docker/issues/24394#issuecomment-230959487 ?

**Comment by mostolog** [comment]
Hi.

I'm sorry.
I didn't notice our containers were failing after ~60s, but as they do and swarm creates new ones, this might be a duplicate of https://github.com/docker/docker/issues/24394

Nevertheless, after running the "renaming" command, old containers can't be removed using "service rm", because cluster doesn't exists anymore, and "docker rm" must be used.

**Comment by thaJeztah** [comment]
The reason you were not able to remove the *old* service, is that there *is* no old service; the service was *renamed*, so it's still the same service, only using a different name.

For example:

```
docker service create --name oldname nginx
317xys0pztjawph8uffxvodav

docker service update --image nginx:alpine --name newname oldname
oldname

docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                     PORTS               NAMES
2aa66c6ff99a        nginx:alpine        "nginx -g 'daemon off"   1 seconds ago       Up Less than a second      80/tcp, 443/tcp     newname.1.9v0iuxa7qcgkemn3dze1q139i
6046e2271c70        nginx:latest        "nginx -g 'daemon off"   25 seconds ago      Exited (0) 1 seconds ago                       oldname.1.4mnae2htd0bfcl0gdpbv151l4
```

You can remove all tasks/containers by removing the service using the new name:

```
docker service rm newname
newname

docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```
