### ISSUE TITLE
Unable to pull images in WS2016 TP5 in Azure

### ISSUE THREAD

**Issue by mmisztal1980** [docker/docker#24678]
When trying to `docker run microsoft/dotnet35:windowsservercore` 

Docker version 1.12.0-dev, build 8e92415

>C:\Program Files\docker>dockerd
>time="2016-07-15T09:51:37.384518600Z" level=info msg="Windows default isolation mode: process"
>time="2016-07-15T09:51:37.435963000Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
>time="2016-07-15T09:51:37.765405500Z" level=info msg="Loading containers: start."

>time="2016-07-15T09:51:37.765405500Z" level=info msg="Loading containers: done."
>time="2016-07-15T09:51:37.765405500Z" level=info msg="Daemon has completed initialization"
>time="2016-07-15T09:51:37.765405500Z" level=info msg="Docker daemon" commit=8e92415 graphdriver="Windows filter storage driver" version=1.12.0-dev
>time="2016-07-15T09:51:37.774404500Z" level=info msg="API listen on //./pipe/docker_engine"
>time="2016-07-15T09:51:46.129587200Z" level=error msg="Handler for POST /v1.24/containers/create returned error: No such image: microsoft/dotnet35:windowsservercore"
>time="2016-07-15T09:51:53.629464900Z" level=error msg="Error trying v2 registry: failed to register layer: layer does not exist"
>time="2016-07-15T09:51:53.630465500Z" level=error msg="Attempting next endpoint for pull after error: failed to register layer: layer does not exist"

This has occured on a recently created VM in Azure using the WS2016 TP5 image. Can I fix or work around this issue? 

Regards
/Maciej

**Comment by jhowardmsft** [comment]
I think this is expected while things migrate. @taylorb-microsoft

**Comment by mmisztal1980** [comment]
@jhowardmsft Expected while things migrate? :/ How long till this migration is over? Is there a workaround?

**Comment by taylorb-microsoft** [comment]
This should still work - the only case where this isn't currently expected to be working (if following our doc's) is Hyper-V Containers on Windows 10 because the image is loaded differently. 

When you say "This has occured on a recently created VM in Azure using the WS2016 TP5 image. Can I fix or work around this issue?"  How specifically did you install the base container image?

**Comment by mmisztal1980** [comment]
@taylorb-microsoft Using the instructions provided here: https://blogs.msdn.microsoft.com/jcorioland/2016/04/28/getting-started-with-containers-and-docker-on-windows-server-2016-technical-preview-5/

Additionally ```docker images``` yields an empty result - is this intended?

**Comment by taylorb-microsoft** [comment]
Can you please try restarting the docker service (net stop docker; net start docker).  This will be fixed shortly when we have hub support integrated for the base images.

**Comment by mmisztal1980** [comment]
@taylorb-microsoft 

>PS C:\Windows\system32> net stop docker
>The Docker Engine service was stopped successfully.
>
>PS C:\Windows\system32> net start docker
>The Docker Engine service is starting.
>The Docker Engine service was started successfully.
>
>PS C:\Windows\system32> docker images
>REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
>
>PS C:\Windows\system32> docker run microsoft/iis:windowsservercore
>Unable to find image 'microsoft/iis:windowsservercore' locally
>windowsservercore: Pulling from microsoft/iis
>90a7b36461ef: Extracting  2.51 kB/2.51 kB
>31278b05360c: Download complete
>C:\Program Files\Docker\docker.exe: failed to register layer: layer does not exist.
>See 'C:\Program Files\Docker\docker.exe run --help'.

Seems that the restart didn't help.  
Can you throw us a bone on when to expect the fix?

**Comment by sitano** [comment]
Exact this error you will get when you updated docker from 0.11.x to 0.12.x as there changed windows storage driver naming. Plz, check your what do you have at c:\ProgramData\docker\image. Maybe its your case https://github.com/docker/docker/issues/25176.

Yet, the latest fresh install still does not work for me ;) with pull`s asking for auth, and images missing basic...

**Comment by sitano** [comment]
Ok, you are using good version. Then, its because you did not install root images.
Check https://msdn.microsoft.com/en-us/virtualization/windowscontainers/management/manage_images .

```
Install-PackageProvider ContainerImage -Force
Install-ContainerImage -Name WindowsServerCore
```

**Comment by mmisztal1980** [comment]
I've re-executed the install instructions and it started to work. Not sure what was it.
