### ISSUE TITLE
Worker node cannot join the cluster on Amazon instances

### ISSUE THREAD

**Issue by arun-gupta** [docker/docker#24686]
Started two Ubuntu AMIs
Configured security groups: TCP: 2377, TCP/UDP: 7946 and 4789
Installed Docker 1.12 RC4 on them using `curl -fsSL https://experimental.docker.com/ | sh`.
Start manager on one node: `docker swarm init`
Trying to add second node as worker using: `docker swarm join --secret btrmzhajgdlagc6dzbgiybhrd  --ca-hash sha256:5c6a67d023c9b1fc2d197401af8b7ea88e29de7e32b9a8f4726748b365f9426e 
 172.31.6.141:2377` gives the following error:

`Error response from daemon: Timeout was reached before node was joined. Attempt to join the cluster will continue in the background. Use "docker info" command to see the current Swarm status of your node.`

There are no options in `docker swarm join` to provide a longer timeout.

**Comment by mavenugo** [comment]
@arun-gupta can you try with `docker swarm init --listen-addr <ip:2377>` and confirm if that works ?

**Comment by arun-gupta** [comment]
@mavenugo Started master as `docker swarm init --listen-addr ec2-54-215-222-196.us-west-1.compute.amazonaws.com:2377`

On worker: `docker swarm join --secret 9rus4dnp66s83ymixuifzvjx9 --ca-hash sha256:a7a6efb264603af82cacfc726553ce7f0af0c4d21b2ae720ba455ef1082a5d2a ec2-54-215-222-196.us-west-1.compute.amazonaws.com:2377`

Got the error:

```
Error response from daemon: Timeout was reached before node was joined. Attempt to join the cluster will continue in the background. Use "docker info" command to see the current Swarm status of your node.
```

**Comment by marcosnils** [comment]
@arun-gupta close?

**Comment by mavenugo** [comment]
@arun-gupta I think `ec2-54-215-222-196.us-west-1.compute.amazonaws.com` resolves to the public IP and this will not work currently (unless `--advertise-addr` is supported).

Hence please use the private IP for both `--listen-addr` and join.

**Comment by arun-gupta** [comment]
the two nodes are on the same VPC and this allows the private IP address to communicate.

**Comment by coderjiang** [comment]
https://github.com/docker/docker/issues/24404

**Comment by sudhir6199** [comment]
*** *Just expose 2377 port of manager, it will work :*  ***

It clearly means **node** unable to connect **manager** so timeout happening to conform same just do **telnet manager-ip 2377**  (dont try ping wont work)

and if you are facing same error even though all firewalls are disabled in both nodes and manager then try to create another manager exposing port 2377 as below:

     docker-machine create --driver amazonec2 --amazonec2-open-port 2377 manager1

and now try to join nodes to new manager created now but port u are using to join should be 2377 if u gonna use diff then expose that port in above command. Doing same worked for me as I suspect its because others used another different servers but I'm using same server for both manager and nodes.

**Comment by Naveendharshan3** [comment]
> @arun-gupta can you try with `docker swarm init --listen-addr <ip:2377>` and confirm if that works ?

hey i uh solved it

**Comment by Naveendharshan3** [comment]
can uh help me in tht

**Comment by svchraghava** [comment]
I am also facing the same issue i try all above solutions, but not resolved

**Comment by svchraghava** [comment]
Finally after 2 days work out i resolved the issue.
in Amazon EC2 Instance (manager1) go to security group and add 2377 port then it works fine for me
