### ISSUE TITLE
Can't build github.com/docker/docker/cmd/docker 

### ISSUE THREAD

**Issue by ignatov** [docker/docker#24683]
```
go get -u github.com/docker/docker/cmd/docker 

# github.com/docker/docker/distribution
docker/distribution/push_v2.go:178: cannot use p.config.TrustKey (type "github.com/docker/libtrust".PrivateKey) as type "github.com/docker/distribution/vendor/github.com/docker/libtrust".PrivateKey in argument to schema1.NewConfigManifestBuilder:
        "github.com/docker/libtrust".PrivateKey does not implement "github.com/docker/distribution/vendor/github.com/docker/libtrust".PrivateKey (wrong type for PublicKey method)
                have PublicKey() "github.com/docker/libtrust".PublicKey
                want PublicKey() "github.com/docker/distribution/vendor/github.com/docker/libtrust".PublicKey

```

Golang 1.6.2.

**Comment by thaJeztah** [comment]
What platform and architecture are you on? Do you have docker running on your system?

The easiest way to build docker is to use the Makefile, for example `make binary`, but also see https://docs.docker.com/opensource/code/

**Comment by ignatov** [comment]
Mac OS X, yes, I have docker beta.

**Comment by thaJeztah** [comment]
running 

    make binary shell

Should build docker in a container, and open an interactive shell in the container,
then run `make install` and `dockerd --debug &` to start the daemon inside that container.

Anyway, the original issue is that docker cannot be built using `go get`. I'll close this issue, but feel free to continue the discussion
