### ISSUE TITLE
Error : bridge is a pre-defined network and cannot be removed

### ISSUE THREAD

**Issue by mohanrao** [docker/docker#24685]
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker-253:4-52497-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 11.8 MB
 Data Space Total: 107.4 GB
 Data Space Available: 9.86 GB
 Metadata Space Used: 581.6 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.18.2.el7.x86_64
Operating System: Red Hat Enterprise Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.51 GiB
Name: #removed#
ID: Z6GY:765L:N6I5:RQNW:BR54:UYAW:DH4D:GIL2:KWKJ:C4R3:NQN3:XDAK
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. docker network rm bride
2.
3.

**Describe the results you received:**
Error response from daemon: bridge is a pre-defined network and cannot be removed

**Describe the results you expected:**

I need an ability to modify/remove/recreate the default bridge because it is taking 172.17.0.0/16 subnet. Is there any way to modify it?
**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by aboch** [comment]
The daemon start log tells how to:
```
INFO[0001] Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address 
```

**Comment by justincormack** [comment]
you can change the ip with `docker daemon --bip 10.1.0.0/16` or similar to change the bridge ip address.

**Comment by mohanrao** [comment]
@aboch @justincormack can you please point out some documentation how to do it ? Like some configuration file automatically reads it from and etc..

**Comment by mohanrao** [comment]
@aboch @justincormack 

After i add daemon.json and restart my docker service it is failing  with the following error


Jul 15 12:41:10 my-host docker[29142]: time="2016-07-15T12:41:10.560063100-05:00" level=warning msg="devmapper: Base device already exists and has filesystem xfs on it. User spe... be ignored."
Jul 15 12:41:10 my-host docker[29142]: time="2016-07-15T12:41:10.582817402-05:00" level=info msg="[graphdriver] using prior storage driver \"devicemapper\""
Jul 15 12:41:10 my-host docker[29142]: time="2016-07-15T12:41:10.584483571-05:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Jul 15 12:41:10 my-host docker[29142]: time="2016-07-15T12:41:10.589346612-05:00" level=info msg="Firewalld running: false"
Jul 15 12:41:10 my-host docker[29142]: time="2016-07-15T12:41:10.661995638-05:00" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating d...ready in use"
Jul 15 12:41:10 my-host systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Jul 15 12:41:10 my-host docker[29142]: time="2016-07-15T12:41:10-05:00" level=info msg="stopping containerd after receiving terminated"
Jul 15 12:41:10 my-host systemd[1]: Failed to start Docker Application Container Engine.
Jul 15 12:41:10 my-host systemd[1]: Unit docker.service entered failed state.
Jul 15 12:41:10 my-host systemd[1]: docker.service failed.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by aboch** [comment]
@mohanrao 
https://docs.docker.com/v1.10/engine/userguide/networking/default_network/custom-docker0/

As @justincormack explained, start the daemon with the `--bip` option and pass a full CIDR (it must contain a valid address for the bridge interface) something like `--ip=192.168.0.1/16`

**Comment by mohanrao** [comment]
seems the error happened for 10.1 range. Its resolved thank you @aboch and @justincormack
