### ISSUE TITLE
calling docker ps with size in format is confusing

### ISSUE THREAD

**Issue by jhorwit2** [docker/docker#24696]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.2
 Git commit:   eb3c9ed
 Built:        Fri Jul 15 18:23:54 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.2
 Git commit:   eb3c9ed
 Built:        Fri Jul 15 18:23:54 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 9
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Debian GNU/Linux 8 (jessie) (containerized)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.82 GiB
Name: 8d47af3e5cd0
ID: UTKC:PIPV:R7PT:WN2A:LV77:GXUX:FLQC:QKGO:55YS:LAEJ:GJLC:JOXL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 30
 System Time: 2016-07-15T18:39:31.197677702Z
 EventsListeners: 0
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

docker development shell

**Steps to reproduce the issue:**
1. `docker run -d tutum/hello-world`
2. `docker ps --format "table {{.Image}}\t{{.Size}}"`

**Describe the results you received:**

```
$ docker ps --format "table {{.Image}}\t{{.Size}}"
IMAGE               SIZE
tutum/hello-world   0 B
```

**Describe the results you expected:**

```
IMAGE               SIZE
tutum/hello-world   114 B (virtual 17.79 MB)
```

**Additional information you deem important (e.g. issue happens only occasionally):**

It's not very clear that you have to add the flag `--size` even with format, because now it lies to you (it's not 0). I think the daemon should include the 2 size attributes always in the `/containers/json` request. Then you can call `--size` to add the column or use `--format` to show it in a custom way.

**Comment by cpuguy83** [comment]
This was already fixed for 1.12
Curious when your 1.12 was built.

```
docker ps --format '{{ .Size }}'
2 B (virtual 828.1 MB)
```

Seems like you've hit another bug in the processing.

**Comment by jhorwit2** [comment]
Perhaps my dev env is behind. I thought I pulled upstream this morning. I'll try again @cpuguy83

**Comment by cpuguy83** [comment]
@jhorwit2 Oh no, I can repro by using 2 fields like you did.

**Comment by jhorwit2** [comment]
oh :). nvm then.

**Comment by jhorwit2** [comment]
Yea, I just tried on latest master (pulled a few mins ago) & rc4. Both have the same issue where it works with 1 but not 2

**Comment by jhorwit2** [comment]
@cpuguy83 I'll take a look into this. It seems the issue is in the cli prior to calling the daemon. 

When you do `-- format {{.Size}}` you get the correct call `Calling GET /v1.25/containers/json?size=1` but when you do more than that `size=1` goes away.

**Comment by thaJeztah** [comment]
@jhorwit2 this would be a good starting point to check; https://github.com/docker/docker/pull/23247 perhaps I messed something up there :smile:

**Comment by jhorwit2** [comment]
@thaJeztah I got a fix :). 

```
type preProcessor struct {
	types.Container
	opts *types.ContainerListOptions
}
```

Adding the attributes from the Container struct returned from the daemon fixes it and as those should be the only possible values you will be making formats with it should be fine in the future.

The issue is that go's template lib errors once you find a value not in your struct when you call `.Execute`. This is fine when `{{.Status}}` is first, but fails when anything else is first.

**Comment by thaJeztah** [comment]
@jhorwit2 :heart: thanks! Looking forward to your PR

**Comment by jhorwit2** [comment]
@icecrime this also needs to be removed from the 1.12 milestone (follow up from #24703)
