### ISSUE TITLE
Peer-to-peer push/pull between docker hosts

### ISSUE THREAD

**Issue by cespare** [docker/docker#247]
Following discussion with @shykes on irc.

When the docker daemon is running, it should accept push/pull requests. This will allow two daemons to send images between each other in a p2p or centralized fashion.

In addition, there should be a -norun option to disable execution. This will be useful when running a dedicated image repo. In this mode, docker should work even without lxc or the aufs module.

Once this exists, the current public repo implementation could be replaced with a docker daemon.

**Comment by sahus5** [comment]
Can anyone please tell me if we are going to get this feature in near future in any release?
I would love to see this feature

**Comment by sahus5** [comment]
Can anyone please tell me if we are going to get this feature in near future in any release?
I would love to see this feature

**Comment by sahus5** [comment]
Can anyone please tell me if we are going to get this feature in near future in any release?
I would love to see this feature

**Comment by fgutmann** [comment]
+1 Would love to see that too!

**Comment by hanzheng** [comment]
+1.

**Comment by virtuald** [comment]
+1 on this. Currently we use `docker save | ssh -C docker load` to transfer images, but that transfers *everything*, including the pieces we already have. Would be much easier if I could only transfer the bits that mattered.

**Comment by v00rh33s** [comment]
+1

**Comment by xiaods** [comment]
+1

**Comment by xiaods** [comment]
https://github.com/Dataman-Cloud/p2pull

**Comment by LK4D4** [comment]
Still looks like valid feature to have. Not sure if it's possible with security/verification stuff.
Thoughts @tonistiigi ?

**Comment by xiaods** [comment]
@LK4D4 i think we can close it, if anyone can give a real proposal design, then he can open another issue to track the topic.
