### ISSUE TITLE
Size option for 'docker volume' misunderstanding

### ISSUE THREAD

**Issue by jakon89** [docker/docker#24709]
It looks that size option is broken or documentation is no longer valid, don't know about other options.

Invalid case:
https://github.com/docker/docker/blame/master/docs/tutorials/dockervolumes.md#L206

Valid case:
https://github.com/docker/docker/blame/master/docs/reference/commandline/volume_create.md#L65

Please check 'Additional information' section below.
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 54
Server Version: 1.12.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 34
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 4.835 GiB
Name: moby
ID: BASX:TGR2:WAPC:IVR7:SP75:KNCH:S3BF:2CT7:BV24:7OG2:36TL:OIZI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 24
 Goroutines: 43
 System Time: 2016-07-16T01:24:21.722302118Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64

**Steps to reproduce the issue:**
1.
```docker volume create -d local --name my-named-volume -o size=1GB```

**Describe the results you received:**
Console output:
```Error response from daemon: create my-named-volume: invalid option key: "size"```

**Describe the results you expected:**
Volume should be created.

**Additional information you deem important (e.g. issue happens only occasionally):**
Hovewer, following command:
```docker volume create --name test --opt o=size=1GB``` will pass and volume is created successfully.

Debug output for valid and invalid case:
```
root@db340e9e86c2:/go/src/github.com/docker/docker# docker volume create --name xyz  -o size=1GB
DEBU[2008] Calling POST /v1.25/volumes/create           
DEBU[2008] form data: {"Driver":"local","DriverOpts":{"size":"1GB"},"Labels":{},"Name":"xyz"} 
DEBU[2008] Registering new volume reference: driver "local", name "xyz" 
ERRO[2008] Handler for POST /v1.25/volumes/create returned error: create xyz: invalid option key: "size" 
Error response from daemon: create xyz: invalid option key: "size"

root@db340e9e86c2:/go/src/github.com/docker/docker# docker volume create --name zyw --opt o=size=1GB
DEBU[2020] Calling POST /v1.25/volumes/create           
DEBU[2020] form data: {"Driver":"local","DriverOpts":{"o":"size=1GB"},"Labels":{},"Name":"zyw"} 
DEBU[2020] Registering new volume reference: driver "local", name "zyw" 
zyw
```

**Comment by cpuguy83** [comment]
These are driver specific options. The `local` driver does not support this option.

**Comment by cpuguy83** [comment]
@jakon89 `--opt o=size=100m` is the syntax from the docs for setting this for when `--opt type=tmpfs`
