### ISSUE TITLE
[1.12] Docker create service --env-file

### ISSUE THREAD

**Issue by jadbox** [docker/docker#24712]
The `create service` CLI command should support `--env-file` for when many env variables are needed and using `--env` is too much hassle to do by hand.

https://docs.docker.com/engine/reference/commandline/service_create/

**Comment by ralphtheninja** [comment]
+1

**Comment by thaJeztah** [comment]
Thanks for suggesting; for 1.12 we decided to start with a "minimum" set of options to `service create`. We'll add more options in coming versions. Not all options that are available for `docker run` will be added, as some are really Linux specific, or not really portable in a Swarm situation, so may be added in a more generic form.

Stay tuned :-)

**Comment by thaJeztah** [comment]
Adding this to 1.13 milestone, so that it doesn't get lost when we start working on that release

**Comment by yongtang** [comment]
@jadbox @thaJeztah I created a pull request #24844. Please let me know if there are any issues.

**Comment by expedit85** [comment]
Hi, while this feature is not available you may use  `cat vars | xargs printf "--env %s "` where vars file is:
```
A=valueA
B=valueB
```
For instance: `docker service create .... $(cat ... | xargs ...)`.

Regards.

**Comment by akath20** [comment]
Just a minor comment on "--env", it didn't work for me, but this did:

`cat whatzur/whatzur/.env | xargs printf -- "--env %s "`

**Comment by thaJeztah** [comment]
@akath there's no need to use the workaround - `--env-file` was implemented in https://github.com/moby/moby/pull/24844, and is in docker 1.13, and up (including 17.03 and 17.06)
