### ISSUE TITLE
Best way to communicate between two docker containers?

### ISSUE THREAD

**Issue by sauravskumar99** [docker/docker#24735]
Can someone please suggest the proper way to communicate between two docker containers.

I have one mongodb container which exposes ports at 27017 and can be accessed by host at localhost:27017

I have the second container which has express application, and connects to mongodb via mongodb://localhost:27017/test

But the express container app doesn't works... Please help.. Thank You in advance

**Comment by cpuguy83** [comment]
Here's the docs around networking: https://docs.docker.com/engine/userguide/networking/dockernetworks/

Closing as this is the issue tracker and generally not good for general support.
Please see forums.docker.com or #docker on IRC (freenode) for user support.

Thanks!
