### ISSUE TITLE
oci runtime error: could not synchronise with container process: not a directory

### ISSUE THREAD

**Issue by kesor** [docker/docker#24749]
When trying to run a container with a file mapping, for example `-v /elasticsearch.yml:/usr/share/config/elasticsearch.yml`
Then Docker first creates `/elasticsearch.yml` as a folder, and not as a file.
Then Docker fails with the error `docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: could not synchronise with container process: not a directory".
`

**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 3
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 35
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.795 GiB
Name: ec2-docker-machine
ID: KITG:M7HX:B5YS:XL5V:4PZM:2D4S:GCI2:SBM6:IYYW:YTNW:AUA3:TYKD
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=amazonec2
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Created the host using this script -

```
#!/bin/sh
exec docker-machine create --driver "amazonec2" \
    --amazonec2-access-key "XXXXXXXXXXXXXXXXXXXXXXX" \
    --amazonec2-secret-key "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" \
    --amazonec2-region "us-east-1" \
    --amazonec2-instance-type "m4.large" \
    --amazonec2-root-size "8" \
    --amazonec2-security-group "xxx" \
    --amazonec2-ssh-keypath "xxx.pem" \
    --amazonec2-vpc-id "vpc-xxxxxxxx" \
    --amazonec2-subnet-id "subnet-xxxxxxxx" \
    --amazonec2-request-spot-instance \
    --amazonec2-spot-price "0.12" \
    --amazonec2-ami "ami-ddf13fb0" \
    --amazonec2-ssh-user "ubuntu" \
    ec2-docker-machine
```

**Steps to reproduce the issue:**
1. Make sure you don't have a file called `/somefile.txt`.
2. Create an image that has `/somefile.txt` inside.
3. Start the container from this image using `-v /somefile.txt:/somefile.txt`.

**Describe the results you received:**
Docker failed to be useful. Had to debug for an hour. Tore some hair out of my head, finally decided its Docker's fault and not mine and fixed the problem by touching the file before running docker.

**Describe the results you expected:**
Expected a "nicer" error, or for it to just work.

**Additional information you deem important (e.g. issue happens only occasionally):**
Easy to repeat the issue, happens always. First encountered it when running `docker-compose` and there are some related issues talking about `aufs` and stuff, but its not the same issue.

**Comment by justincormack** [comment]
It is not going to work, I don't think that can be fixed. A nicer error is a possibility though.

**Comment by cpuguy83** [comment]
If the file does not exist, docker will create a directory on the host side and then try to bind mount that over the file in the container, which of course does not work because you can't bind a directory onto a file (hence the `not a directory` error).

I've opened #24754 to improve the error.
