### ISSUE TITLE
Manager cannot join to an existing swarm - syntax error

### ISSUE THREAD

**Issue by arun-gupta** [docker/docker#24742]
Docker 1.12 RC4
Created a three-node cluster with one manager and one worker on Amazon as shown at: https://github.com/arun-gupta/docker-scripts/blob/master/swarm-mode-amazon.sh
Trying to add another node as a manager using:

`docker swarm join --secret mySecret --manager --listen-addr ip-172-31-14-36.us-west-1.compute.internal:2377`

This syntax is similar to the one mentioned at: https://docs.docker.com/engine/reference/commandline/swarm_join/#/join-a-node-to-swarm-as-a-manager

However its giving the following error:

```
"docker swarm join" requires exactly 1 argument(s).
See 'docker swarm join --help'.

Usage:  docker swarm join [OPTIONS] HOST:PORT

Join a Swarm as a node and/or manager
```

**Comment by vdemeester** [comment]
@arun-gupta on your command line you are missing the last part (`HOST:PORT`), which swarm/manager you are joining.

```
$ docker swarm join --secret mySecret --manager --listen-addr ip-172-31-14-36.us-west-1.compute.internal:2377 the-ip-or-dns-name-of-the-mamager:2377
```

`--listen-addr` help the current node (joining) to decide on which ip/port it should listen not whom to connect with. 👼

**Comment by arun-gupta** [comment]
Thanks, got that working!

Updated script: https://github.com/arun-gupta/docker-scripts/blob/master/second-manager.adoc
