### ISSUE TITLE
s390x/gcc: Update glibc to 2.19-18+deb8u5

### ISSUE THREAD

**Issue by michael-holzheu** [docker/docker#24748]
Currently the __CI for s390x is disabled__: https://jenkins.dockerproject.org/job/Docker%20Master%20(z)

The reason is that the [Dockerfile.s390x](https://github.com/docker/docker/blob/4ced001d9aff60dea2c2687c0635cdbe369cd534/Dockerfile.s390x#L18) which is used for the continuous integration tests currently uses [s390x/gcc] (https://hub.docker.com/r/s390x/gcc) as base image. The glibc of this image contains the following two bugs:

- https://sourceware.org/git/?p=glibc.git;a=commit;h=890b7a4b33d482b5c768ab47d70758b80227e9bc
- https://sourceware.org/git/?p=glibc.git;a=commit;h=2e807f29595eb5b1e5d0decc6e356a3562ecc58e

The CI tests hang because the bugs affect the gccgo runtime.

Now the fixes have been integrated to __glibc 2.19-18+deb8u5__ in "proposed-updates" for Debian Jessie:

- https://anonscm.debian.org/cgit/pkg-glibc/glibc.git/log/?h=jessie
- https://release.debian.org/proposed-updates/stable.html

It is expected that the package should be part of the next stable point release (8.6) in
about one to two months.

In order to __enable CI for s390x earlier__, it would be good to integrate the "proposed-updates" glibc fix now.

To update the glibc for Debian Jessie I did following steps:

```
# echo "deb http://ftp.debian.org/debian/ jessie-proposed-updates main" >>  /etc/apt/sources.list
# apt-get update
# apt-get dist-upgrade
```

@tianon : Is it somehow possible to update the s390x/gcc images?

**Comment by tianon** [comment]
Apologies for the delay!  I think our best/simplest bet here is going to be to solve this with a temporarily patch directly in `Dockerfile.s390x` until Debian 8.6 is released with the fix officially included.

I _think_ something like this should be sufficient (ie, updating just `libc6` instead of the full `dist-upgrade` which with some packages attempts to do more than it should in a container and fails):
```dockerfile
# glibc in Debian has a bug specific to s390x that won't be fixed until Debian 8.6 is released
# - https://github.com/docker/docker/issues/24748
# - https://sourceware.org/git/?p=glibc.git;a=commit;h=890b7a4b33d482b5c768ab47d70758b80227e9bc
# - https://sourceware.org/git/?p=glibc.git;a=commit;h=2e807f29595eb5b1e5d0decc6e356a3562ecc58e
RUN echo 'deb http://httpredir.debian.org/debian jessie-proposed-updates main' >> /etc/apt/sources.list.d/pu.list \
	&& apt-get update \
	&& apt-get install -y libc6 \
	&& rm -rf /var/lib/apt/lists/*
```

**Comment by michael-holzheu** [comment]
> I think something like this should be sufficient (ie, updating just libc6 instead of the full dist-upgrade which with some packages attempts to do more than it should in a container and fails)

Looks like a plan. I created PR #24846 for this.

**Comment by justincormack** [comment]
LGTM

**Comment by michael-holzheu** [comment]
I now re-enabled our Jenkins job: https://jenkins.dockerproject.org/job/Docker%20Master%20(z)

3-4 Tests are currently failing. I will investigate this.
