### ISSUE TITLE
A question about use "Docker Swarm" to orchestrate "Swarm Cluster" which supports GPU feature.

### ISSUE THREAD

**Issue by NanXiao** [docker/docker#24750]
Hi all,

I am not sure whether this is a correct place to post this issue, if not, please forgive me, provide the appropriate web link, close this issue, thanks!  

I am considering using `Docker Swarm` to orchestrate `Swarm Cluster` which supports `GPU` feature. Per my understanding, to implement this function, `Docker` need to envelope `GPU` resource like `CPU` and `memory`, and passes it to `Docker Swarm` when `Swarm manager` issues `manage` command. And `Swarm manager` and `Docker engine-API` all need do corresponding modifications to explain and use `GPU` resources.  

My questions are as follows:  
(1) Do my above statements make sense? Or are there some important technical issues which I ignore?  

(2) Does Docker community have a plan to use `Docker Swarm` to orchestrate `Swarm Cluster` which supports `GPU` feature?  

Thanks very much in advance!

**Comment by justincormack** [comment]
Hi, there is an open issue about adding NVIDIA GPU support here https://github.com/docker/docker/issues/23917 - it definitely is something there is interest in generally.

**Comment by NanXiao** [comment]
@justincormack : But It seems #23917 doesn't take `Docker Swarm` in consideration. Is my understanding right? Thx!

**Comment by justincormack** [comment]
@NanXiao the plan would be to make it work for swarm too; once it works for Docker it should be fairly easy to get it working for swarm mode too.

**Comment by NanXiao** [comment]
@justincormack Thanks very much for your timely reply! I will check #23917 more detailedly, thanks!

**Comment by thaJeztah** [comment]
Thanks @NanXiao, let me close this issue
