### ISSUE TITLE
Not able to create a new service in Docker Cloud

### ISSUE THREAD

**Issue by arun-gupta** [docker/docker#24765]
. Configured Docker Cloud to be linked with Amazon
. Created a node cluster one one node
. Create a service using `arungupta/couchbase`
. Expose port `8091 as shown

<img width="721" alt="screen shot 2016-07-18 at 12 50 53 pm" src="https://cloud.githubusercontent.com/assets/113947/16924711/49b27abe-4ce6-11e6-855e-c2eb80382685.png">
. Clicking on `Create & Deploy` shows the error attached.
<img width="991" alt="screen shot 2016-07-18 at 12 51 16 pm" src="https://cloud.githubusercontent.com/assets/113947/16924728/5d980c2e-4ce6-11e6-8e4f-03327d59812b.png">
. Not exposing any ports still give that error.

**Comment by thaJeztah** [comment]
ping @fermayo PTAL

**Comment by justincormack** [comment]
Hi, the official place for cloud questions and requests is https://forums.docker.com/c/docker-cloud

**Comment by arun-gupta** [comment]
@thaJeztah @justincormack seems slightly inconsistent to have forums vs github issues. Any particular reason?

**Comment by cpuguy83** [comment]
@arun-gupta this is the issue tracker for docker-engine, an open source project.

Docker Cloud is a closed source SaaS offering, and is not hosted in this repo.

**Comment by cpuguy83** [comment]
Going to close this one since it is unrelated to docker engine.

Thanks for taking the time to report issues @arun-gupta
