### ISSUE TITLE
docker swarm inspect needs more swarm details

### ISSUE THREAD

**Issue by dayglojesus** [docker/docker#24769]
Hi,

Changes in RC4 brought with it tighter security and the new requirement of presenting a CA cert hash when joining the swarm. While dumping the correct command to join the swarm to stdout is useful, it's not very extensible.

Getting the swarm's CA cert hash programmatically currently means asking the docker daemon for that info (`docker info`) and text parsing that, because `docker swarm inspect` does not supply that information.

**Comment by tonistiigi** [comment]
Looks like we will go with https://github.com/docker/docker/issues/24430 instead so there will be no need to get ca-hash and special command for getting the token.

**Comment by dayglojesus** [comment]
So it would seem. Thanks @tonistiigi.
