### ISSUE TITLE
Overlay network in Docker Cloud

### ISSUE THREAD

**Issue by arun-gupta** [docker/docker#24763]
Creating a new service using Docker Cloud. The offered networking choices does not include `overlay`.

<img width="455" alt="screen shot 2016-07-18 at 12 32 36 pm" src="https://cloud.githubusercontent.com/assets/113947/16924218/cfb809ba-4ce3-11e6-8c4b-f8f8e14bb2f3.png">

This needs to be included to allow containers to talk across hosts.

**Comment by thaJeztah** [comment]
Could you open this in the Docker Cloud forums? https://forums.docker.com/c/docker-cloud, as there's not much we can do in this repository :innocent:
