### ISSUE TITLE
Improve error when pulling Linux images with Windows engine (and probably vice-versa)

### ISSUE THREAD

**Issue by friism** [docker/docker#24766]
Two observations:

 1. It'd be nice if a Windows engine could handle Linux images (if nothing else to move them around), and vice-versa for a Linux engine (I haven't tested the behavior there)
 2. At both `pull` and `run`, Docker should ideally have easy-to-understand errors if an image is not of compatible architecture.

cc @jhowardmsft @icecrime @nicolaka @anweiss

**Output of `docker version`:**

```
docker version
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.2
 Git commit:   294791e
 Built:        Thu Jun 30 15:51:10 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
docker info
Containers: 15
 Running: 0
 Paused: 0
 Stopped: 15
Images: 23
Server Version: 1.12.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay transparent
Swarm: inactive
Security Options:
Kernel Version: 10.0 14300 (14300.1045.amd64fre.rs1_release_svc.160705-1059)
Operating System: Windows Server 2016 Datacenter Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 1.085 GiB
Name: WIN-A6CBPNHU7TI
ID: U5E6:P2NH:OHDZ:FIBQ:MAYN:GPQ3:5PB2:3IIR:RPKO:2FYV:NG54:VO2A
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Username: friism
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

 * WS2016 TP5 in Hyper-V on Windows 10

**Steps to reproduce the issue:**

docker pull microsoft/aspnet
Using default tag: latest
latest: Pulling from microsoft/aspnet

52747b744e22: Extracting [==================================================>] 37.19 MB/37.19 MBB
a3ed95caeb02: Download complete  ============================================>]     32 B/32 B
bcdfa5245946: Download complete  ============================================>] 7.551 MB/7.551 MB
50df7d9be93c: Download complete  ============================================>] 29.33 kB/29.33 kB
5fc529821ea0: Download complete  ===========================================> ] 182.2 MB/182.7 MB
03baf1ad5a9d: Download complete
009fbb77966a: Download complete  ===========================================> ] 47.04 MB/47.26 MB
04ebf5542e57: Download complete  ============================================>] 9.221 kB/9.221 kB
3dc5a37905fe: Download complete  ===========================================> ]  3.62 MB/3.627 MB
4318275ef3b3: Download complete  ===========================================> ] 20.02 MB/20.04 MB
failed to register layer: re-exec error: exit status 1: output: open \\?\C:\ProgramData\docker\windowsfilter\1c799ed7a057909a25cdbe7068a110197e32acce41c7c7b32194dc211eaf1fdd\usr\share\man\man3\Locale::gettext.3pm.gz: The filename, directory name, or volume label syntax is incorrect.

**Describe the results you received:**

```
failed to register layer: re-exec error: exit status 1: output: open \\?\C:\ProgramData\docker\windowsfilter\1c799ed7a057909a25cdbe7068a110197e32acce41c7c7b32194dc211eaf1fdd\usr\share\man\man3\Locale::gettext.3pm.gz: The filename, directory name, or volume label syntax is incorrect.

```

**Describe the results you expected:**

I can pull Linux images with Windows engine, or at least I get an easy-to-understand error.

**Comment by jhowardmsft** [comment]
@swernli

**Comment by jhowardmsft** [comment]
@aaronlehmann I'm not that familiar with the pull v2 code, but grokking through it, I couldn't see anywhere where the daemon gets the platform so that an "if daemon is windows and the platform of the image is not windows, then give a nice user error" could be added. I can some mention of platform in manifest-list processing (distribution\pullv2.go), but that code doesn't get triggered during a regular `docker pull ubuntu` for example. As far as I can see, if I docker pull "some non-Windows image", I get a list of manifest references back, but these are just URLs/SHAs/size.  Is there something I'm missing and this information is passed back from the v2 registry in its description of the image being pulled?

**Comment by aaronlehmann** [comment]
`pullSchema2` could check `unmarshalledConfig.Architecture` and `unmarshalledConfig.OS`.

`pullSchema1` could unmarshal `config` and check its `Architecture` and `OS` fields.

I'd suggest erring on the side of permissiveness. I've heard of configurations such as running an engine on ARM and running x86 images through automatic emulation. I'd feel most comfortable blacklisting known-incompatible combinations of OS/arch, such as trying to pull a Linux image on Windows.

**Comment by jhowardmsft** [comment]
Ah thanks! That's where it is. Yes, I agree entirely with the side of permissiveness.

**Comment by friism** [comment]
@aaronlehmann @jhowardmsft hm, my thought was actually that push/pull should ideally be fully permissive to allow shuffling around (but not running) images irrespective of the current engine architecture. But maybe there's some technical limitation that means that I can't even pull and store a Linux image with a Windows daemon? (That appears to be the case based on evidence above). The architecture compatibility check would then be done on `run`.

**Comment by jhowardmsft** [comment]
You can't even use the image to start a container (or even complete pulling it due to the base layer incompatibility) so I'm not sure there's a scenario to being able to pull a Linux image on Windows...

**Comment by friism** [comment]
@jhowardmsft I know you can't start it, but there might be a use case where someone with just a windows daemon would want to pull a Linux image to inspect it somehow, or perhaps form a multi-arch image manifest or to shuttle a (Linux) image between registries without running it. If even the pull is unworkable, then +1 on error'ing as soon as possible

**Comment by StefanScherer** [comment]
@friism In this specific case even the `docker pull microsoft/aspnet` does not work as some filenames in the docker image (eg. `/usr/share/man/man3/Locale::gettext.3pm.gz`) contain colons which is not allowed on Windows.

But pulling even simpler images results in an error

```
C:\Users\vagrant> docker pull busybox
Using default tag: latest
latest: Pulling from library/busybox

8ddc19f16526: Extracting 667.6 kB/667.6 kB
failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer C:\ProgramData\docker\windowsfilter\b16d1655843509f5f5f4c3d28dbc3ed9d726b4de58ad4bff94925849fe86143a: The system cannot find the path specified.
```

Pulling/pushing Linux images on Windows may also have side effects due to different file permissions (executable bits on Linux etc.).

A better error message for the user is a good approach.

**Comment by byorxyz** [comment]
So I do I resolve this issue? I can't build the docker image because of this :: on the windows. Any tip?

**Comment by jhowardmsft** [comment]
@byorxyz This will be fixed with full LCOW support which is in progress. https://github.com/moby/moby/pull/34859 will get you part way there. There's no other workaround otherwise except to use a Linux daemon at the moment.
