### ISSUE TITLE
Docker image push from jenkins server results in 'Retrying in x seconds' + 'blob upload unknown'

### ISSUE THREAD

**Issue by homerakshay** [docker/docker#24772]
Hey there,

I have been facing the same issue since 2 days now. Drained out thinking about a fix.

My nonproduction cluster setup :

2 swarm-managers
2 swarm-nodes
1 consul-server

I have set --insecure-registry in /etc/sysconfig/docker as i am on Amazon linux. All works fine when i try to push images to my private repo which is backed by an s3 bucket. However when i do a push from my jenkins job, i get this error :

When trying to push to the repo I get 'trying in 10seconds' for all layers and that continues and eventually a failure in build saying 'blob upload unknown' any idea what this may be? It's really annoying.

Jenkins output : 

[address] Running shell script
docker push my-registry:5000/my-image
The push refers to a repository [my-registry:5000/my-image]
812e286e8a40: Preparing
a90fb04dcc16: Preparing
b4acf34e0e77: Preparing
f80165213f51: Preparing
134e07ee6a4b: Preparing
2f448aa4907c: Preparing
9820d2c29b3c: Preparing
29195fec4161: Preparing
8d41cbe0d29c: Preparing
caf31171df0f: Preparing
a8871e5275ce: Preparing
2b05a418a870: Preparing
e9e2cdb47188: Preparing
41ff6daccf15: Preparing
b935878a1e12: Preparing
fe0c5e130f66: Preparing
ff87673e27e0: Preparing
efff58ad80d1: Preparing
2b05a418a870: Waiting
e9e2cdb47188: Waiting
41ff6daccf15: Waiting
2f448aa4907c: Waiting
b935878a1e12: Waiting
9820d2c29b3c: Waiting
fe0c5e130f66: Waiting
29195fec4161: Waiting
ff87673e27e0: Waiting
8d41cbe0d29c: Waiting
efff58ad80d1: Waiting
caf31171df0f: Waiting
a8871e5275ce: Waiting
b4acf34e0e77: Retrying in 5 seconds
a90fb04dcc16: Retrying in 5 seconds
134e07ee6a4b: Retrying in 5 seconds
f80165213f51: Pushed
b4acf34e0e77: Retrying in 4 seconds
a90fb04dcc16: Retrying in 4 seconds
134e07ee6a4b: Retrying in 4 seconds
b4acf34e0e77: Retrying in 3 seconds
2f448aa4907c: Pushed
a90fb04dcc16: Retrying in 3 seconds
134e07ee6a4b: Retrying in 3 seconds
caf31171df0f: Pushed
blob upload unknown
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // withDockerRegistry
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // dir
[Pipeline] echo
[WORKFLOW] :: Slack response sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@d198b1b
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE

However, when i login to my swarm managers where my registry container runs and do a docker push, all works fine and also reflects in my s3 bucket which i use as my private-repo. But in the case above, i do not see _manifests ( tag/revision ) but only 'layers' & '_uploads'. 

Am i missing something here?

P.S: I have not set up any Ssl nor authentication. Port 5000 which my elb holds is on http-> 5000:5000... All help will be great. 

Cheers.

**Comment by homerakshay** [comment]
This can be closed.. i Have FIXED THE ISSUE MYSELF BY DEBUGGING.

**Comment by kog13** [comment]
@homerakshay any chance you remember what the root cause of your issue was?

**Comment by maresja1** [comment]
@homerakshay Very sweet of you, you let us know you did it. People with the same issue should suffer with you and discover the solution themselves, I suppose.

**Comment by homerakshay** [comment]
@kog13 Sorry for getting back a bit late, as there has been a death in the family and i was unavailable to look into this. OK lets get back to things : 

Firstly i would like to know if you have setup a private registry for storing your images on s3 or any other storage.

Second, check if all the ports in your security groups are opened, namely (3000,4000,5000) which belong to swarm managers/nodes/registry.

3rd : If you have done the above, log into your jenkins server and check the /etc/sysconfig/docker file and see if you have added the line --insecure-registry "<followed by your docker registry name>" ... Once this is done restart your docker service in jenkins to pick up these changes. 

4th : Try pulling images from your registry while logged into jenkins, if things work we shall look into it further. 

Hope this helps.. 

@maresja1 Sorry buddy for getting back late.. was held up in a medical emergency. Hope the above helps. If not we can discuss further & i would surely be delighted to help.

Regards,
Akshay

**Comment by kog13** [comment]
@homerakshay thanks, a simple bump from 1.11.x - 1.12.1 seems to have resolved the issue for me. I tried the bump after reading through this issue: https://github.com/docker/docker/issues/20936

**Comment by homerakshay** [comment]
@kog13 Excellent!! Great going.

**Comment by maresja1** [comment]
@homerakshay Thank you! In our case problem seemed to be related to a reverse proxy in front of a private gitlab registry. Guys taking care of the servers fixed. Sadly can't share more info on that.
