### ISSUE TITLE
`docker node inspect` plugins section is not consistent with other commands

### ISSUE THREAD

**Issue by jhorwit2** [docker/docker#24774]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 449
 Running: 0
 Paused: 0
 Stopped: 449
Images: 227
Server Version: 1.12.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1120
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay host bridge
Swarm: active
 NodeID: 58rx1deuh6s3w3g0xukzowhjg
 IsManager: Yes
 Managers: 1
 Nodes: 1
 CACertHash: sha256:02e17c8e2f8453e682f54c1e6c89f66dbd7bc905997ba281bfb1f7c680638491
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.82 GiB
Name: moby
ID: LU3X:7JDU:3WSS:UEYM:HVGT:OY2M:BDUN:XAU6:YJ5A:JCKF:7XDI:EILX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 38
 Goroutines: 126
 System Time: 2016-07-18T21:24:41.627567975Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. `docker swarm init`
2. `docker network create --driver overlay mynet`
3. `docker create --replicas 2 --network mynet nginx`
4. `docker node inspect (docker node ls --quiet)`

**Describe the results you received:**

Engine.Plugins doesn't provide much value IMO in the current form. You aren't able to tell which plugins they are (which network, which volume, which auth plugin). They also have duplicates which makes it more confusing (2 overlays below). The naming convention is also not consistent with the rest of docker. `docker network ls` and `docker volume ls` show the `Name` here as `Driver`. 

```
 "Engine": {
                "EngineVersion": "1.12.0-rc4",
                "Plugins": [
                    {
                        "Type": "Volume",
                        "Name": "local"
                    },
                    {
                        "Type": "Network",
                        "Name": "overlay"
                    },
                    {
                        "Type": "Network",
                        "Name": "bridge"
                    },
                    {
                        "Type": "Network",
                        "Name": "null"
                    },
                    {
                        "Type": "Network",
                        "Name": "overlay"
                    },
                    {
                        "Type": "Network",
                        "Name": "host"
                    }
                ]
            }
```

**Describe the results you expected:**

Ideally I think the current value for `Name` should be renamed `Driver` & `Name` should be the actual name from the plugin (volume name, network name, etc). This has a lot more value. They also share the same core concept `Driver`. 

```
 "Engine": {
                "EngineVersion": "1.12.0-rc4",
                "Plugins": [
                    {
                        "Type": "Volume",
                        "Driver": "local"
                        "Name": "something"
                    },
                    {
                        "Type": "Network",
                        "Driver:": "overlay",
                        "Name": "ingress"
                    },
                    {
                        "Type": "Network",
                        "Driver:": "bridge",
                        "Name": "bridge"
                    },
                    {
                        "Type": "Network",
                        "Driver:": "null",
                        "Name": "none"
                    },
                    {
                        "Type": "Network",
                        "Driver:": "overlay",
                        "Name": "mynet"
                    },
                    {
                        "Type": "Network",
                        "Driver:": "host",
                        "Name": "host"
                    }
                ]
            }
```

**Comment by jhorwit2** [comment]
Also seems kinda strange there would be duplicates when doing contains checks like [this](https://github.com/docker/swarmkit/blob/master/manager/scheduler/filter.go#L124). 


If you agree with the change I should be able to do this PR 👍. Not much touches this struct from what I can tell currently.

**Comment by thaJeztah** [comment]
@jhorwit2 thanks for reporting

I don't think we should change the output format; what you're describing in your "expected" results mixes *instances* of a volume, with the actual *plugin* that is used. For example;

```
{
    "Type": "Volume",
    "Driver": "local"
    "Name": "something"
},
```

This seems to indicate there's a "something" volume, that uses the "local" driver, whereas I *think* we're only looking for "plugins" (and not interested in which networks/volumes use them)


> Also seems kinda strange there would be duplicates when doing contains checks like

That's a known issue; there's an open issue https://github.com/docker/docker/issues/23619 for the way plugins are detected. Basically, the current `docker info` only shows plugins that are actually in use (the list of "plugins" is based on that). This is a problem for Swarm mode, so needs to be addressed.

**Comment by jhorwit2** [comment]
@thaJeztah when I put `something` there it would actually be on of the values under `volume name`

```
$ docker volume ls
DRIVER              VOLUME NAME
local               0c2267d563500f5435595676f940b7140c8a198e357e9e23e88af2184a96990c
local               22457d79850a265c6143cbbd26286d211140847e5e4718166bde25f74b30060e
local               4547f46cc63e937958cfdfa61e6a66287e3c66d9b8d31925abebd9b4d9356631
local               4aaaa812995f7c597e748a3693ba0c0a1df0b9eb544d2e277ec97425596a3920
local               4ff395056025cc3673e1aa00bf85eb123a78a5d322981956d7757b6b71cb2122
local               5c98623664138b26c1822d8a9c9f405ddd546b01af1258583e63bfc10ea8b703
```

Then you are able to look at these plugins and actually connect them to a volume/network/etc. 


So what you are saying is this list of plugins should a high level overview? Why not make the output similar to `docker info`

```
Plugins:
 Volume: local
 Network: bridge null overlay host```

**Comment by thaJeztah** [comment]
@jhorwit2 correct, this is a list of available *plugins*, not available *networks*, or *volumes; basically this information provides the options you can choose when specifying `--driver` on `docker volume create` or `docker network create` (well, for services then, so `--log-driver`, `--mount driver=foo`, etc.)

**Comment by jhorwit2** [comment]
👍 So it sounds like a PR to remove dupes would do the trick then. yes?

**Comment by thaJeztah** [comment]
No, it's not the dupes that is the biggest problem directly, it's plugins not showing up if they're not currently in use. e.g. if I have a "fancyvolumedriver" plugin installed, then `docker info` will not show it, unless I actually create  a volume that uses it (`docker volume create --driver fancyvolumedriver`)

**Comment by jhorwit2** [comment]
ahhhh i see what you are saying. Seems like that other ticket encompasses this issue so i'll close this one out 👍

**Comment by thaJeztah** [comment]
Thanks @jhorwit2! Yes, it's a bit confusing :smile:
