### ISSUE TITLE
Logs sometimes out of order with awslogs log driver

### ISSUE THREAD

**Issue by joshpurvis** [docker/docker#24775]
**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:54:54 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:54:54 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
docker info
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 151
Server Version: 1.12.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 359
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null bridge host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-48-generic
Operating System: Ubuntu 14.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 14.69 GiB
Name: test-grid-02
ID: DKPX:PIXI:AHKL:JYZN:AVER:HDVL:43WL:JJRW:SEJV:ABJP:HCZ4:QIDM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS

**Steps to reproduce the issue:**

I've created a repository to easily reproduce this issue: https://github.com/joshpurvis/docker-awslogs

```
git clone https://github.com/joshpurvis/docker-awslogs
```

Set environment

```
export AWS_SECRET_ACCESS_KEY=YOURSECRET
export AWS_ACCESS_KEY_ID=YOURID
export AWS_DEFAULT_REGION=us-east-1
export AWS_LOGS_GROUP=YOURLOGGROUP
```

Build test image
```
docker build -t awslogtest .
```

Run a loop which logs ~20k times via awslogs driver
```
cid=$(docker run -d --log-driver=awslogs --log-opt awslogs-group=$AWS_LOGS_GROUP awslogtest python /test.py)
```

Read logs via boto -- logs come back, slightly out of order (same as on aws console)
```
docker run -it -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY awslogtest /usr/bin/python /viewer.py --group=$AWS_LOGS_GROUP --stream=$cid
```

**Describe the results you received:**

```
# ...

{u'ingestionTime': 1468876501400, u'timestamp': 1468876501111, u'message': u'INFO:__main__:19986'}
{u'ingestionTime': 1468876501400, u'timestamp': 1468876501111, u'message': u'INFO:__main__:19987'}
{u'ingestionTime': 1468876501400, u'timestamp': 1468876501111, u'message': u'INFO:__main__:19988'}
{u'ingestionTime': 1468876501400, u'timestamp': 1468876501111, u'message': u'INFO:__main__:19989'}
{u'ingestionTime': 1468876501400, u'timestamp': 1468876501111, u'message': u'INFO:__main__:19990'}
{u'ingestionTime': 1468876501400, u'timestamp': 1468876501111, u'message': u'INFO:__main__:19991'}
{u'ingestionTime': 1468876501400, u'timestamp': 1468876501111, u'message': u'INFO:__main__:19992'}
{u'ingestionTime': 1468876501400, u'timestamp': 1468876501111, u'message': u'INFO:__main__:19993'}
{u'ingestionTime': 1468876501400, u'timestamp': 1468876501111, u'message': u'INFO:__main__:19994'}
{u'ingestionTime': 1468876501400, u'timestamp': 1468876501111, u'message': u'INFO:__main__:19995'}
{u'ingestionTime': 1468876501400, u'timestamp': 1468876501111, u'message': u'INFO:__main__:19996'}
{u'ingestionTime': 1468876501400, u'timestamp': 1468876501111, u'message': u'INFO:__main__:19997'}
{u'ingestionTime': 1468876501400, u'timestamp': 1468876501111, u'message': u'INFO:__main__:19998'}
{u'ingestionTime': 1468876501400, u'timestamp': 1468876501111, u'message': u'INFO:__main__:19507'}
```

^ The numbers at the far right indicate the actual order in which the logs were sent to STDOUT according to Python. 

Note: this behavior appears in the Cloudwatch log console as well, I just found it easier to demonstrate with boto.

**Describe the results you expected:**

Lines logged in the order sent to STDOUT

**Additional information you deem important (e.g. issue happens only occasionally):**

- I would think the sequence token should prevent this from happening. It seems it's being used in the driver, but the lines are sent in bulk? I'm not too familiar with golang, so I haven't been able to get far reading the code yet

- I can pretty consistently reproduce it with ~20k lines of logs. It seems on smaller batches, it's more rare that it happens.

- Also in Docker 1.11 and likely some older versions, the problem appears to happen more often. I believe the related PR #22971 seems to help a bit in 1.12.0-rc4

**Edit:**

After reading over the code for the awslog driver and the other logging code, I found this bit:

https://github.com/docker/docker/blob/master/daemon/logger/awslogs/cloudwatchlogs.go#L360

Which is sorting the logs by `Message.Timestamp`. I assume this is the issue, given that two lines could have the same `Timestamp`. Is there something else that it can be sorted by to ensure that order is maintained, such as an index?

**Comment by thaJeztah** [comment]
Thanks for reporting!

ping @samuelkarp PTAL

**Comment by samuelkarp** [comment]
@joshpurvis, thanks for reporting this!  The sort is there because the PutLogEvents API [requires log lines to be ordered by timestamp](http://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutLogEvents.html).  I think what's going on is that `sort.Sort` is [not guaranteed to be stable](https://golang.org/pkg/sort/#Sort) when there are multiple keys with the same value (timestamps in this case).

I haven't been able to reproduce what you're reporting, but I've opened [a pull request](https://github.com/docker/docker/pull/24814) to fall back to insertion order when multiple log lines have the same timestamp.  Can you test that and let me know if it fixes the problem?

**Comment by joshpurvis** [comment]
@samuelkarp thanks for the PR! 

I'm new to docker/golang development.. so quick question-- If I follow this guide, will I be able to test the CloudWatch logging features inside the dev container? https://docs.docker.com/opensource/project/set-up-dev-env/

Or do I need to setup the go build chain and make a full docker daemon binary to test this?

Thanks again!

**Comment by thaJeztah** [comment]
@joshpurvis that guide shows how to build a daemon binary; the really TL;DR is;

- have git, make, and docker on your local machine
- checkout @samuelkarp's PR (https://github.com/docker/docker/pull/24814)
- from the root of that repository run: `make shell`. this starts a development container, and opens a shell in it
- run `make binary` to build all binaries (including the daemon)
- run `make install` to install it inside the container
- run `dockerd --debug` to start the docker daemon inside the container (in debug mode)
- in another shell, `docker exec -it <your-build-container> bash` to get a second shell in the container for running your commands :smile:

Congrats! If you made it this far, you have built your own docker :-)

Let me know if you need help

**Comment by thaJeztah** [comment]
(edited the `make binary` step, as it should've been `hack/make.sh binary` when running inside the container)

**Comment by joshpurvis** [comment]
Thanks @thaJeztah, the dogfooding you guys have here is impressive!

I was able to run dockerd in the dev container with the code from @samuelkarp 's PR. 

Unfortunately it doesn't seem to fix the issue. Inside the dev container, on the PR changeset, I ran my own docker based test several times and the last line is always incorrect, and sporadically through out the logs there are lines misplaced here and there. (The test I ran: https://github.com/joshpurvis/docker-awslogs)

![screenshot](http://i.imgur.com/ty9uFG9.png)

^ The `INFO__main__: <n>` line here is basically a counter in python to keep track which order the lines are logged. As you can see it's showing out of order here.

As a sanity check I ran the same test on the json-file driver and the lines are in the correct order.

Josh

**Comment by samuelkarp** [comment]
@joshpurvis Thanks for testing!  Just to rule it out, is there a chance that the clock on your host is jumping around a bit?  If you look at the file that the default `json-file` driver writes (typically located in `/var/lib/docker/containers/${CONTAINER_ID}/${CONTAINER_ID}-json.log`), do you see timestamps that appear to jump at all?

**Comment by joshpurvis** [comment]
@samuelkarp I don't believe so, but I checked anyway to be certain. 

First some context: My initial bug report was based on tests against an AWS instance (c4.2xlarge), running the `1.12.0-rc-4` build installed via a deb. That particular instance already had the NTP service running for unrelated reasons. When I did the test against your PR in the dev container, it was performed on my local box (Docker 1.11.2), which doesn't have NTP. Both boxes have 8 cores, a good bit of ram (15-16GB), and are running Ubuntu 14.04. 

I was going cross-eyed trying to scan the timestamps, so I used the `jq` cli tool to do some sorting to see if the `time` attributes are out of order. They seem to be fine:

- Copy the json file, pluck out the `log` and `time` attributes, and wrap as an array of objects:
```
root@3a69427ae63b:~/docker-awslogs# cat /var/lib/docker/containers/9b62655538c8bb257ca0433b5668703a9a14ae0867465314177f8854f00ed11a/9b62655538c8bb257ca0433b5668703a9a14ae0867465314177f8854f00ed11a-json.log | jq -s '[ .[] | { log, time } ]' > ~/log.json
```

- Here's what it looks like now:
```
root@3a69427ae63b:~/docker-awslogs# tail -f ~/log.json
  },
  {
    "log": "INFO:__main__:19998\n",
    "time": "2016-07-20T15:58:06.355800241Z"
  },
  {
    "log": "INFO:__main__:19999\n",
    "time": "2016-07-20T15:58:06.355815841Z"
  }
]
^C
```

- Next I sorted by the time field:
```
root@3a69427ae63b:~/docker-awslogs# cat ~/log.json | jq 'sort_by(.time)' > ~/log.sorted.json
root@3a69427ae63b:~/docker-awslogs# tail -f ~/log.sorted.json 
  },
  {
    "log": "INFO:__main__:19998\n",
    "time": "2016-07-20T15:58:06.355800241Z"
  },
  {
    "log": "INFO:__main__:19999\n",
    "time": "2016-07-20T15:58:06.355815841Z"
  }
]
^C
```

I then visually scanned `~/log.sorted.json` in vim, and my counter seems to still be in order, which leads me to believe the times are sequential in the logs generated by the `json-file` driver.

**Comment by joshpurvis** [comment]
Grasping at straws here, but could it be something to do with the lock and the buffered channel as logs are written/consumed?

I found this [issue](https://github.com/golang/go/issues/11506), which I'm not completely sure how it was resolved. Looks like it was reverted back and forth, but these two snippets seem very similar to the behavior I'm seeing:

> A send into a buffered channel with blocked receivers stores the value in the buffer, wakes up a receiver, and continues executing. When the receiver is eventually scheduled, it checks the channel, and maybe it gets lucky and the value is still there. But maybe not, in which case it goes to the end of the queue.
> 
> A receive out of a buffered channel copies a value out of the buffer, wakes a blocked sender, and continues. When the sender is eventually scheduled, it checks the channel, and maybe it gets lucky and there is still room in the buffer for the send. But maybe not, in which case it goes to the end of the queue.

At this point, this is getting a bit over my head. I've only read one go book and a few tutorials. So I only know the basic concepts.

**Comment by joshpurvis** [comment]
@samuelkarp Today I'm unable to reproduce the issue on PR #24814. However I can still reproduce it on the master branch, so the insertion sort fix definitely corrected something. 

I'm thinking maybe I deployed the dev container incorrectly the first time yesterday. I unfortunately don't have the original container from yesterday to know for sure, though.

I apologize for any confusion I caused-- and hopefully didn't waste too much of your time! 

Does any further testing need to be done on the PR?

Thanks!

**Comment by samuelkarp** [comment]
@joshpurvis That's great!  I'm not sure if the Docker maintainers will require additional testing to be done, but let me know if you run into this problem again (or any other problems).

**Comment by jackbritchford** [comment]
This still appears to be an issue when using `awslogs` in a container definition on ECS. Latest ECS Optimized AMI (ami-0ae254c8a2d3346a7/eu-west-1) and pulling awslogs on ECS bootstrap (last done today).
This issue has been occurring since I implemented awslogs about a month ago and I',m guessing it's because aws isn't recording or being sent the millisecond for the timestamp? Sometimes applications echo out systemtime and it shows all of the logs grouped together correctly by second, but not fractions of a second.

I know this is closed so this issue may be unrelated, but does anyone have any suggestions as I can't find anything else apart from this thread.

Thanks!

**Comment by thaJeztah** [comment]
What version of Docker are you running?

**Comment by jackbritchford** [comment]
Here's the output of `docker version`
```
[ec2-user@ip-10-x-x-x ~]$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a215d7133c34aa18e3b72b4a21fd0c6136
 Built:             Fri Jun 28 23:16:08 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a/18.06.1-ce
  Built:            Fri Jun 28 23:17:39 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by anand-s** [comment]
This still happens!
