### ISSUE TITLE
get.docker.com Fails on fedora 24

### ISSUE THREAD

**Issue by tronicum** [docker/docker#24785]
I am not sure where to report bugs for get.docker.com, as I did not find a github repo for that. But I guess the right people might see or get notfied by this bug.

**Output of `docker info`:**
not relevant

**Additional environment details (AWS, VirtualBox, physical, etc.):**
OS: Fedora 24

**Steps to reproduce the issue:**
1. Install Fedora 24
2. run 'curl -sSL https://get.docker.com/ | sh' 
3. The script will fail to detect the latest docker repo, as it tries to get https://yum.dockerproject.org/repo/main/fedora/24/ (what does not exist, at the time of writing)
4. dnf (yum successor) will install docker rpms from fedora repo, instead of yum.dockerproject.org)

**Describe the results you received:**
Old docker packages, not from intended location installed

**Describe the results you expected:**
latest docker packages from dockerproject.org

**Additional information you deem important (e.g. issue happens only occasionally):**
can be reproduced.

**Comment by thaJeztah** [comment]
correct, fedora 24 wasn't released yet when docker 1.11 got out; the upcoming 1.12 release will be available for fedora 24. you can install the release candidate from test.docker.com, or manually install and use the fedora 23 packages.

Closing, as this will be addressed in 1.12, but feel free to comment after I closed

**Comment by tronicum** [comment]
ok as explained. An error message would be nicer though, that desired packages could not be installed.
