### ISSUE TITLE
Docker for Mac DNS Queries goto 8.8.8.8

### ISSUE THREAD

**Issue by cwolfinger** [docker/docker#24781]
Running docker login <private registry> yields dns queries to 8.8.8.8 and not the corporate dns server.  This results in failure to login.

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->
```
**Output of `docker version`:**
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 31
 Running: 28
 Paused: 0
 Stopped: 3
Images: 839
Server Version: 1.12.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 688
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.954 GiB
Name: moby
ID: BPYH:GFVL:AWHU:5DWV:ENNE:GGUQ:657D:NHCJ:SAKU:K4YV:VLKL:BIJY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 213
 Goroutines: 356
 System Time: 2016-07-19T02:01:29.677122128Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker for MAC

**Steps to reproduce the issue:**
1. docker login private-repository
2. enter user name
3. enter password

**Describe the results you received:**
Error response from daemon: Get https://private-repos/v1/users/: dial tcp: lookup dockerhub.cisco.com on 192.168.65.1:53: server misbehaving

**Describe the results you expected:**
Successful login

**Additional information you deem important (e.g. issue happens only occasionally):**
Consistent issue since rc3.  Wireshark on MAC shows dns queries going to 8.8.8.8.

**Comment by thaJeztah** [comment]
There's a daemon option to specify the DNS to use (see https://docs.docker.com/engine/reference/commandline/dockerd/#/daemon-dns-options), but I don't think there's a UI for this yet on Docker for Mac. Perhaps plans are to follow the DNS settings from OS X

ping @justincormack

**Comment by justincormack** [comment]
Hi, in general it should use the upstream servers, but there was a workaround for some types of failure that used 8.8.8.8, let me check if this might be causing issues now, as there were various changes.

**Comment by justincormack** [comment]
I am going to remove the old workaround for the beta today, can you let me know if this fixes the problem for you, as I can see that it could sometimes be applied erroneously, and it should no longer be needed.

**Comment by justincormack** [comment]
@cwolfinger can you test with the new beta that has just been released and let me know if this fixes it?

**Comment by cwolfinger** [comment]
Hi - the latest RC seems to fix the issue.  Thank you!

**Comment by ebuildy** [comment]
@cwolfinger it seems not fixed yet right?

**Comment by thaJeztah** [comment]
@ebuildy if you're still having this issue, best place to report is https://github.com/docker/for-mac/issues, which is the issue tracker for docker for mac
