### ISSUE TITLE
1.12.0-rc4: inspect task by name (not id)

### ISSUE THREAD

**Issue by npcode** [docker/docker#24790]
It would be nice if we can get a task by name as well as id. e.g.:

```
$ docker inspect worker.1
[
    {
        "ID": "bzsrvcl9sr1c74djkf8jl6jvr",
        "Version": {
            "Index": 123
        },
...
]
```

**Comment by yongtang** [comment]
@npcode This issue might be related to #24112. I think once #24620 is merged then this issue could be fixed.
