### ISSUE TITLE
Docker 1.12 and Compose 1.8 - Mount not work

### ISSUE THREAD

**Issue by RotemEmergi** [docker/docker#24795]
I am using Docker 1.12 and Compose 1.8. I am trying to understand how to mount the volumes for an image to global volumes.

The purpose is to use Docker services and Docker bundle for deploying clusters.

This is the error that I got :
WARNING: Unsupported top level key 'volumes' - ignoring

WARNING: Unsupported key 'volumes' in services.momgodb - ignoring

Best regarsd

**Comment by cpuguy83** [comment]
Volumes is not supported in a dab file.
When creating a service you must use the `--mount` flag, for example `docker service create --mount type=volume,source=mongodata,target=/var/lib/mongodb`

Closing as this is not really an issue.
For support related questions, forums.docker.com or #docker on IRC would be a much better place.

Thanks!

**Comment by RotemEmergi** [comment]
So in this way there is no way to use bundle.
Can it's possible to create a hub repository that locates on image docker?
