### ISSUE TITLE
TestRunSeccompDefault failures on master.

### ISSUE THREAD

**Issue by anusha-ragunathan** [docker/docker#24803]
Docker master, git commit ebca26b4b19ff7744c211e0859cb6155ed24bb7b.
Jenkins master job on rhel and devicemapper fails TestRunSeccompDefaultProfileAcct and TestRunSeccompDefaultProfileNS.

Logs for TestRunSeccompDefaultProfileAcct failure at https://jenkins.dockerproject.org/job/Docker%20Master/label=rhel%20&&%20devicemapper/6169/consoleText 
```Error response from daemon: failed to create endpoint fervent_heisenberg on network bridge: failed to save bridge endpoint b02707c to store: failed to update bridge store for object type *bridge.bridgeEndpoint: timeout.```

Logs for TestRunSeccompDefaultProfileNS failure at https://jenkins.dockerproject.org/job/Docker%20Master/label=rhel%20&&%20devicemapper/6170/consoleText
```Error response from daemon: failed to create endpoint elated_goldberg on network bridge: failed to save bridge endpoint 4551260 to store: failed to update bridge store for object type *bridge.bridgeEndpoint: timeout.\n, exit status 125``` 

Failure is not consistent. It doesnt look like a seccomp failure.

**Comment by dnephin** [comment]
#23401 is related (issue for the TestRunSeccompDefaultProfileNS failure, maybe we can close it and use this one)

**Comment by anusha-ragunathan** [comment]
This issue is still observed on master. https://jenkins.dockerproject.org/job/Docker%20Master/6516/label=rhel%20&&%20devicemapper/consoleText

```FAIL: docker_cli_run_unix_test.go:1078: DockerSuite.TestRunSeccompDefaultProfileAcct

docker_cli_run_unix_test.go:1128:
    c.Assert(err, checker.IsNil)
... value *errors.errorString = &errors.errorString{s:"goroutine 2: expected No such file or directory, got: /go/src/github.com/docker/docker/bundles/1.13.0-dev/test-integration-cli/../binary-client/docker: Error response from daemon: failed to create endpoint peaceful_bohr on network bridge: failed to save bridge endpoint bd931ff to store: failed to update bridge store for object type *bridge.bridgeEndpoint: timeout.\n"} ("goroutine 2: expected No such file or directory, got: /go/src/github.com/docker/docker/bundles/1.13.0-dev/test-integration-cli/../binary-client/docker: Error response from daemon: failed to create endpoint peaceful_bohr on network bridge: failed to save bridge endpoint bd931ff to store: failed to update bridge store for object type *bridge.bridgeEndpoint: timeout.\n")```
