### ISSUE TITLE
Flaky test: DockerSwarmSuite.TestApiSwarmServicesStateReporting

### ISSUE THREAD

**Issue by tophj-ibm** [docker/docker#24805]
Seen on power, but looks like a general test issue.
```sh
10:55:32 FAIL: docker_api_swarm_test.go:374: DockerSwarmSuite.TestApiSwarmServicesStateReporting
10:55:32 
10:55:32 [d68464000] waiting for daemon to start
10:55:32 [d68464000] daemon started
10:55:32 [d23430000] waiting for daemon to start
10:55:32 [d23430000] daemon started
10:55:32 docker_api_swarm_test.go:380:
10:55:32     d2 := s.AddDaemon(c, true, true)
10:55:32 check_test.go:221:
10:55:32     c.Assert(d.Join(swarm.JoinRequest{
10:55:32         RemoteAddrs: []string{s.daemons[0].listenAddr},
10:55:32         Manager:     manager}), check.IsNil)
10:55:32 ... value *errors.errorString = &errors.errorString{s:"joining swarm: invalid statuscode 406, \"{\\\"message\\\":\\\"This node is already part of a Swarm cluster. Use \\\\\\\"docker swarm leave\\\\\\\" to leave this cluster and join another one.\\\"}\\n\""} ("joining swarm: invalid statuscode 406, \"{\\\"message\\\":\\\"This node is already part of a Swarm cluster. Use \\\\\\\"docker swarm leave\\\\\\\" to leave this cluster and join another one.\\\"}\\n\"")
10:55:32 
10:55:32 [d68464000] exiting daemon
```

**Comment by thaJeztah** [comment]
thanks!

**Comment by dperny** [comment]
This is a known issue, affects other tests. 

When I was writing swarmkit tests, I got this comment. I think there is an associate issue and PR in swarmkit but I can't remember how to find it right now.

https://github.com/docker/docker/pull/24563#issuecomment-232816142

**Comment by tonistiigi** [comment]
@tophj-ibm Is this result from our ci. Do you have a link?

**Comment by tophj-ibm** [comment]
@tonistiigi https://jenkins.dockerproject.org/job/Docker%20Master%20(powerpc)/925/console

**Comment by tophj-ibm** [comment]
again I've only seen it on power, and I've only seen it happen once

**Comment by tonistiigi** [comment]
I updated powrpc ci to store the daemon logs like other ci jobs. Without the logs it's hard to see what may be going on here. This error looks quite weird and I haven't seen it before.

**Comment by dperny** [comment]
Yeah I reread it the right way this time and it is new, not the same one. It just looked familiar at a glance.

**Comment by tophj-ibm** [comment]
thanks, I'll keep an eye out for it.

@dperny good info, that helps because I'm looking into #24590 which looks like it might be related to what you linked

**Comment by tophj-ibm** [comment]
@tonistiigi happened again, except this time on a different test. Also all the following swarm tests failed. A quick glance makes me think that everything isn't getting cleaned up after the tests https://jenkins.dockerproject.org/job/Docker%20Master%20(powerpc)/972/

**Comment by tonistiigi** [comment]
@tophj-ibm Could it be something with `UnixNano()` method in powerpc? Daemon ID is taken from unixnano modulus(we should use `rand.Read` instead) and you can see that for powerpc these numbers are too round to be actual nanoseconds. I opened logs for `TestApiSwarmServicesCreateGlobal` and it clearly already has swarm files in daemon folder when daemon starts. Powerpc build does seem to do `rm -rf bundles` in the end that should clear the state between builds.

**Comment by tophj-ibm** [comment]
@tonistiigi nice catch! Looks like time.Now itself is actually wrong on power. I'll go ahead and submit and issue for it. Thanks for looking into it!

**Comment by clnperez** [comment]
Turns out the time.Now precision difference has been a known "issue" for a long time. FYI: https://github.com/golang/go/issues/11222

**Comment by justincormack** [comment]
Being fixed upstream https://go-review.googlesource.com/#/c/27710/

**Comment by ceseo** [comment]
This is fixed for ppc64/ppc64le: https://github.com/golang/go/commit/0df5ab7e6569a8bf6bc87975e539706163bf664a
