### ISSUE TITLE
Docs docker run seccomp unconfined fails: docker: Invalid --security-opt: "seccomp=unconfined"

### ISSUE THREAD

**Issue by WhisperingChaos** [docker/docker#24810]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Output of `docker version`:**

```
1.10.3
```

**Output of `docker info`:**

```
Containers: 4
 Running: 1
 Paused: 0
 Stopped: 3
Images: 20
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 27
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.13.0-74-generic
Operating System: Alpine Linux v3.4 (containerized)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.704 GiB
Name: 9e02152c961c
ID: FU3B:N6OH:2MXX:3SSH:LEWD:IIL7:XZDL:OV2X:3VGV:VL3T:KK5Z:V3AN
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
  N/A

**Steps to reproduce the issue:**
1.  Visit https://docs.docker.com/engine/security/seccomp/
2.  Copy and paste seccomp unconfined example at page bottom into CLI. 
3.  Execute the example: ```docker run --rm -it --security-opt seccomp=unconfined debian:jessie \
    unshare --map-root-user --user sh -c whoami```

**Describe the results you received:**
Generates message:  ```docker: Invalid --security-opt: "seccomp=unconfined".```

**Describe the results you expected:**
Should create the container and display its GUID.

**Additional information you deem important (e.g. issue happens only occasionally):**
Instead of ```seccomp=unconfined``` the value should be ```seccomp:unconfined```.

Consider solution placing example in ```docker run``` reference and linking to it.

**Comment by thaJeztah** [comment]
The format changed in docker 1.11 (which still supports both formats, for docker 1.10 follow the example in the 1.10 docs; https://docs.docker.com/v1.10/engine/security/seccomp/#run-without-the-default-seccomp-profile

Im closing this issue, because I don't think this is a bug, but feel free to continue the discussion

**Comment by WhisperingChaos** [comment]
@thaJeztah 

Sorry for the false report.  I'll be more attentive concerning the docs version number next time I submit.

**Comment by thaJeztah** [comment]
@WhisperingChaos no problem; do you think we should add a note on that page?

**Comment by WhisperingChaos** [comment]
@thaJeztah 

No, it's such a minor inconsistency that will become a distant echo as 1.10 quickly recedes into the past.  I wouldn't want to clutter the current/future documentation with it.  Lastly, I imagine this post will be available for a while, so hopefully, if someone repeats my actions, they'll read this thread and become informed ;) 

Take care.

**Comment by thaJeztah** [comment]
Okidoki, thanks!
