### ISSUE TITLE
Implement "docker logs" for services

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#24812]
This is a follow up to https://github.com/docker/docker/issues/23710. It's currently not possible to obtain logs for a service through `docker logs`. Docker 1.12 allows you to set a logging-driver for a service so that you can aggregate logs, but ideally we'd have support for viewing those logs (or the latest N entries) through the `docker logs` command (or equivalent, e.g. `docker service logs`).

From the original issue:

In 1.12, I can create services, but there's no easy way to get the logs for either the service as a whole (all tasks), or an individual task;

```
docker service create --name web -p 80:80 nginx:alpine

docker service ls
ID            NAME  REPLICAS  IMAGE         COMMAND
bioa2ndrqp3h  web   1/1       nginx:alpine

docker logs bioa2ndrqp3h
Error: No such container: bioa2ndrqp3h

docker service ps web
ID                         NAME   SERVICE  IMAGE         LAST STATE         DESIRED STATE  NODE
18t5r6j642rhncm76vbc2s8h5  web.1  web      nginx:alpine  Running 7 minutes  Running        moby

docker logs 18t5r6j642rhncm76vbc2s8h5
Error: No such container: 18t5r6j642rhncm76vbc2s8h5
```

Best I could come up with is;

```
docker logs $(docker inspect --format "{{.Status.ContainerStatus.ContainerID}}" 18t5r6j642rhncm76vbc2s8h5)
```

But this only gives me logs for a single task/container

**Comment by hekaldama** [comment]
@thaJeztah I am not sure if the interface has changed since writing this, but I think you need `docker service ps web` instead of `docker service tasks web`.

**Comment by thaJeztah** [comment]
@hekaldama oh, yes, that changed in one of the release candidates, I'll update the example

**Comment by hekaldama** [comment]
@thaJeztah cool thanks! You wouldn't happen to know how to do this same example through the remote API would you?

**Comment by hekaldama** [comment]
@thaJeztah I was namely refering to the `docker service ps` command. I found that it can be done by interacting with the `/tasks` endpoint.

**Comment by thaJeztah** [comment]
@hekaldama looks like you found the solution :-)

An easy way to find which endpoints are called by each CLI command is to *manually* start the docker daemon in the foreground with debug enabled (first stop the "service"), so `dockerd --debug`.

Then in another shell execute the commands you're interested in; the daemon will show each API call (at least which endpoint is called) in the output, for example: `docker service ps web` calls:

```
DEBU[0093] Calling GET /v1.25/services/web
DEBU[0093] Calling GET /v1.25/tasks?filters=%7B%22service%22%3A%7B%228p52xxqi2bqapriacx11qpqpp%22%3Atrue%7D%7D
DEBU[0093] Calling GET /v1.25/services/8p52xxqi2bqapriacx11qpqpp
DEBU[0093] Calling GET /v1.25/nodes/cyinu31xqkbtjl396onuaucy6
```

**Comment by kunalkushwaha** [comment]
@thaJeztah If anyone not working on this, Can I pickup this?

**Comment by manast** [comment]
I made a first try to use the new swarm mode in docker 1.12, and after several hours learning and setting up, when my containers die directly after start I discovered I cannot actually get the logs... Is there any way to get the logs? I had appreciated if the documentation warned about the lack of logging functionality, I suspect many people will wait until it is available before trying to use these new functionalities.

**Comment by cpuguy83** [comment]
@manast Typically you would use an external logging tool such as fluentd, syslog, etc.

**Comment by manast** [comment]
@cpuguy83 that would be an alternative, but if my service dies before he can even write logs, I cannot see the exception that caused the problem, etc.

**Comment by manast** [comment]
@cpuguy83 anyway, I learnt that docker daemon logs are quite useful anyways, it helped solve my particular problem.

**Comment by hekaldama** [comment]
@thaJeztah My experience thus far indicates that the above example works only if swarm launches the task on the currently configured `DOCKER_HOST`. If it launches somewhere else on my swarm cluster, then I cannot get the logs for it unless I reset `DOCKER_HOST` to where the task is running. Am I missing something?

**Comment by thaJeztah** [comment]
@hekaldama that's the current limitation yes; for now, the best solution is to use a logging driver that allows you to centrally aggregate logs.

However, I think @stevvooe is working on this feature currently (but I've been on vacation, so not fully up to speed)

Ping @stevvooe is that correct? Should I assign this issue to you?

**Comment by stevvooe** [comment]
I am currently working on a implementation for `docker service logs`. `docker logs` will continue to work as it does today. I'm sorry that I don't have a proposal to link to yet but I have a design and working branch that does this.

**Comment by bfirsh** [comment]
@thaJeztah Closed by https://github.com/docker/docker/pull/28089, correct?

**Comment by thaJeztah** [comment]
Yup! Now an experimental feature in 1.13. More improvements coming, but the start is there for people to test

**Comment by WillCup** [comment]
what's the meaning of 'only supported with experimental daemon' in 1.13, is it not stable yet?

How can I turn my docker daemon to an experimental one?

Thanks

**Comment by akalipetis** [comment]
@WillCup 1.13 is stable.

> Experimental features are not ready for production. They are provided for test and evaluation in your sandbox environments.

You can see how to enable the experimental features on your daemon [here](https://github.com/docker/docker/tree/master/experimental)

**Comment by thaJeztah** [comment]
Features are put in experimental usually if a feature (or its design) can use feedback; perhaps it's not feature complete yet. They're fine to use, but may change, so from that perspective should not be relied upon

**Comment by kirill-chilingarashvili** [comment]
Before the feature is available for production, I was able to get error for last failed task of a service using this bash script
`docker inspect --format "{{.Status.Err}}" $(docker service ps SERVICE_NAME | awk '{print $1}' | head -n 3 | tail -n 1)`

It is not showing full log, but may be helpful when container could not start at all

**Comment by timothyjmtan** [comment]
Alternate command to retrieve the logs (in `json` format):

`docker inspect $( docker service ps -q test )`

**Comment by thaJeztah** [comment]
The `docker service logs` command is no longer experimental, so should be available
