### ISSUE TITLE
docs: document that `docker logs` is not supported for services

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#24813]
per https://github.com/docker/docker/issues/23710#issuecomment-233751568, we don't have a CLI command (yet) to view logs for a service, so for 1.12 we should document this. Related issue for 1.13; https://github.com/docker/docker/issues/24812

/cc @sfsmithcha should I assign this for you? Or keep it unassigned?

**Comment by sfsmithcha** [comment]
thanks @thaJeztah , I've assigned it to myself

**Comment by manast** [comment]
This is closed, but I can still not find it in the documentation.

**Comment by cpuguy83** [comment]
@manast It's not closed.

**Comment by manast** [comment]
@cpuguy83 sorry, my bad :)

**Comment by batwicket** [comment]
I like logs. The sooner they are in the better IMHO.

**Comment by bfirsh** [comment]
@thaJeztah Closed by https://github.com/docker/docker/pull/28089?

**Comment by thaJeztah** [comment]
Yes, thanks @bfirsh, we have experimental `docker service logs` for 1.13.
