### ISSUE TITLE
Signal based config load breaks libnetwork

### ISSUE THREAD

**Issue by dhiltgen** [docker/docker#24827]
I'm not sure when this regressed, but can confirm it is broken in 1.12-RC4 and works in 1.11.

If you add engine-discovery config to /etc/docker/daemon.json, in a multi-node cluster, then signal the daemons to reload the config the initial time, the system *appears* to work (you can create overlay networks, and run containers on the network) however if you attempt to ping between the nodes it does not work, and the message on the docker log shows:
```
time="2016-07-20T04:14:38.589194267Z" level=debug msg="miss notification for dest IP, 10.0.0.2" 
time="2016-07-20T04:14:38.589238062Z" level=error msg="could not resolve peer \"10.0.0.2\": could not resolve peer: serf instance not initialized" 
```

You can workaround the problem by restarting the daemon.

## Minimal repro scenario:

Spin up two machines, get their IPs.  In my case I'll be running etcd on 192.168.42.33
(Any ~standard etcd image up on hub should do, this one happens to be public)
```
docker run -d -p 2379:2379 --restart=always docker/ucp-etcd:1.1.2 \
    --listen-client-urls http://0.0.0.0:2379 \
    --advertise-client-urls http://192.168.42.33:2379
```

Edit the `/etc/docker/daemon.json` files on both nodes - This example works for the KVM machine driver - substitute eth0 if that applies for your environment.
```
{
        "cluster-advertise": "eth1:2376",                 
        "cluster-store": "etcd://192.168.42.33:2379"      
}
```

Then do **NOT** restart the daemons.  Instead, signal them to dynamically reload the configuration with  HUP signal.

Then you can repro with:
```
docker network create --driver overlay mynet
docker run --rm -it --net mynet --name mytest alpine ash
```

And on the other node
```
docker run --rm -it --net mynet alpine ping mytest
```

The ping hangs, and the daemon log on the node running the ping is filled with:
```
time="2016-07-20T04:41:31.321426639Z" level=debug msg="miss notification for dest IP, 10.0.0.2" 
time="2016-07-20T04:41:31.321495916Z" level=error msg="could not resolve peer \"10.0.0.2\": could not resolve peer: serf instance not initialized" 
time="2016-07-20T04:41:32.321397481Z" level=debug msg="miss notification for dest IP, 10.0.0.2" 
time="2016-07-20T04:41:32.321652854Z" level=error msg="could not resolve peer \"10.0.0.2\": could not resolve peer: serf instance not initialized" 
```

After restarting the daemons the issue is cleared and pings work.

**Comment by mavenugo** [comment]
Resolved by #24237
