### ISSUE TITLE
Question on RC versions and when they are released

### ISSUE THREAD

**Issue by ralphtheninja** [docker/docker#24836]
I'm polling the docker/docker issue list to look for new RC versions. Also I have been following commits coming in to master and was wondering:

1. How often do you make new RC versions? What is the criteria for releasing one?

2. I suspect that you cherry-pick stuff from master and release RCs based on that. What's the criteria for a commit to be picked from master? How do you keep track of what's released and not released?

**Comment by justincormack** [comment]
1. The criteria is roughly when enough of the outstanding high priority issues (P0, P1) have been fixed that it makes sense to have something to test. Many more people test the RC than master.
2. One of the maintainers will tag the issue when with the cherry-pick tag if it fixes an issue that is important or fixes a bug, and then it will be added to the release branch which is currently https://github.com/docker/docker/tree/bump_v1.12.0

There is a bunch of detail here https://github.com/docker/docker/tree/master/project and a blog post about some process here https://blog.docker.com/2016/06/open-source-docker-part-2-processes/

**Comment by ralphtheninja** [comment]
@justincormack Thanks for info! Closing.
