### ISSUE TITLE
Value too large for defined data type when cifs

### ISSUE THREAD

**Issue by cedseat** [docker/docker#24837]
Hi,

I use docker for windows, since yesterday after install the 1.12.0-RC4 version, my container have problem when i use a rpmbuild command. The error is Value too large for defined data type on stat on spec file. My spec file is created by my container on a cifs mounted system. The reason is that inode created in container on mounter cifs file system are too long whereas it is correct when it is created on the container file system. Workaroud is to modify in mount command the serverino to noserverino. Is it possible to do it? in doaemon configuration?

Thanks in advance

**Comment by thaJeztah** [comment]
ping @dgageot PTAL

**Comment by cedseat** [comment]
I use an old version of glibc 2.3.6-2

**Comment by justincormack** [comment]
@cedseat does that mean it is not a problem with a more recent glibc?

**Comment by cedseat** [comment]
The problem does not exists with more recent glibc (i.e centos 7)

**Comment by justincormack** [comment]
Is it a 32 bit program? According to the man page you just need to compile your program with `-D_FILE_OFFSET_BITS=64` to fix this.

**Comment by cedseat** [comment]
Ok, but my rpmbuild is already installed and we cannot re compile it

**Comment by justincormack** [comment]
Ah ok. I would file an upstream bug then, as it should work. We may be able to change the mount options though too cc @rneugeba

**Comment by cedseat** [comment]
Is it possible for me to test it? Where/How can i modify the mount options?

**Comment by justincormack** [comment]
It does not appear to be possible to change the options after mount, not sure if it is possible to change before either.

**Comment by rneugeba** [comment]
@cedseat We don't plan at the moment to provide a user accessible way to change the CIFS mount options (and won't enable `noserverino` by default).

However, *for now* you can try modifying them yourself in `C:\Program Files\Docker\Docker\resources\MobyLinux.ps1`. Note, this option is quite likely going away at some point.

**Comment by cedseat** [comment]
It solve the problem thanks!

**Comment by cedseat** [comment]
Hello,

With the new version of docker my workaround is not possible

**Comment by rneugeba** [comment]
Hi, @cedseat, yes, we had to change the place where the CIFS mount is triggered.

Another user had the same request as you (enable noserverino) but decided against it. See https://github.com/docker/for-win/issues/15 for details.

It seems that the user on that issue had a workaround. maybe contact him for details?

**Comment by rneugeba** [comment]
we moved it to the main application code, which is written in C#, primarily as an optimisation

**Comment by mstormo** [comment]
This needs to be an option, as we using several older 32-bit Dockers, which we cannot modify/update and won't support the i-nodes served by a 64-bit host.

**Comment by mstormo** [comment]
Is there a way to feed this option through the Docker Daemon json configuration file?
I've tried many variations of
```
  ...
  "storage-opts": [
    "cifs.mountopts=noserverino"
  ]
```
to no avail.

**Comment by rneugeba** [comment]
@mstormo this is not exposed through the docker daemon json file. The daemon knows nothing about the CIFS mount.

**Comment by cedseat** [comment]
@rneugeba so what is the solution?

**Comment by rneugeba** [comment]
@cedseat as mentioned by @justincormack the recommended solution would be to use binaries compiled with `-DLARGEFILE_SOURCE _FILE_OFFSET_BITS=64` or equivalent. Of course you can always `nsenter` into the root namespace and remount with whatever options you need. Note, however, this may cause issues with other containers, like mentioned on https://github.com/docker/for-win/issues/15, and we don't really support this option.

**Comment by jamesdboone** [comment]
IMHO this needs to be fixed.  If no better option, then enable the noserverino mount option to be configurable.  Sometimes source code for 32bit binaries aren't readily available for recompile, and having to implement a remount hack from within the container, not only being less secure, seems to affect the stability of the docker daemon.

**Comment by vectoralpha** [comment]
@rn can you provide more detailed instructions to 

> ...always nsenter into the root namespace and remount with whatever options you need...

I have an old CodeSourcery toolchain that I can't re-compile, and in order for it to operate correctly on mounted files I will need to specify noserverino.

**Comment by bartlomiejcieszkowski** [comment]
Same here, I have a tool chain that doesn't support 64bit inode and I don't have an ability to recompile it

While on Linux everything works - as the mounted inode is 32bit, on Windows I'm forced to get 64bit value, which breaks portability of containerized devenv

@rn same question - detailed instruction for nsenter?

**Comment by bartlomiejcieszkowski** [comment]
btw. the similiar problem can be seen on mac:
https://serverfault.com/questions/919784/issue-with-64-bit-host-inodes-vs-32-bit-inodes-in-osxfs-in-ubuntu-16-04-conta
