### ISSUE TITLE
Can I get blobSum of image layers on local machine?

### ISSUE THREAD

**Issue by kiwenlau** [docker/docker#24851]
@dmcgowan @tonistiigi 

For **nginx:latest** image:

I can get the **blobSum** of image layers from Docker Hub using [Docker Registry HTTP API V2](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/inspect-an-image): 

```
GET /v2/<name>/manifests/<reference>
```

```
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/octet-stream",
      "size": 3915,
      "digest": "sha256:0d409d33b27e47423b049f7f863faa08655a8c901749c2b25b93ca67d01a470d"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 51356334,
         "digest": "sha256:51f5c6a04d83efd2d45c5fd59537218924bc46705e3de6ffc8bc07b51481610b"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 32,
         "digest": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 32,
         "digest": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 32,
         "digest": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 19827898,
         "digest": "sha256:51d229e136d0acdb3db7fae7e02d07bcb9b6ffb9bcaac88cc26aaf0be8bea045"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 194,
         "digest": "sha256:bcd41daec8cc835577e660ddef75e655f6ff3742bad92c9c498d8eba097b512a"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 32,
         "digest": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 32,
         "digest": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      }
   ]
}
```

I can also get **digest** of image layers on local machine using **docker inspect** command:

```
  docker inspect --format "{{json .RootFS}}" nginx | python2.7 -mjson.tool
{
    "Layers": [
        "sha256:4dcab49015d47e8f300ec33400a02cebc7b54cadd09c37e49eccbc655279da90",
        "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
        "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
        "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
        "sha256:64d0c8aee4b0327b01ee09a220cef706bc9f68477368895f45838d3a5b59bbf2",
        "sha256:bbf4634aee1a53e8249fb098bf91840f2f939f601349b995d67bef6d46d21e71",
        "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
        "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef"
    ],
    "Type": "layers"
}
```

We can see that the **blobSum** is different with the **digest** for layers of the same image. I don't why, but I guess the reason is: layers are compressed on registry while they are decompressed on local machine. Am I right?

Can I get the **blobSum** instead of **digest** for image layers on local machine?

Or, can I get the layer **digest** instead of **blobSum** from docker registry?

If not, how does docker verify whether some layers are "Already exists" on local machine when pull image? I guess it need to compare layer id(**blobSum** or **digest**)

```
docker pull nginx
Using default tag: latest
latest: Pulling from library/nginx
51f5c6a04d83: Already exists 
a3ed95caeb02: Pull complete 
51d229e136d0: Pull complete 
bcd41daec8cc: Pull complete 
Digest: sha256:0fe6413f3e30fcc5920bc8fa769280975b10b1c26721de956e1428b9e2f29d04
Status: Downloaded newer image for nginx:latest
```

**Comment by tonistiigi** [comment]
> Can I get the blobSum instead of digest for image layers on local machine?

We do not expose this info through API. On disk the pairs are located at `/var/lib/docker/image/<driver>/distribution/`

> Or, can I get the layer digest instead of blobSum from docker registry?

Download the config object referenced by the manifest (0d409d33b27e47423b049f7f863faa08655a8c901749c2b25b93ca67d01a470d) . It contains the same rootfs object you have in inspect.

**Comment by kiwenlau** [comment]
@tonistiigi 

How can I download the config object referenced by the manifest?
> 0d409d33b27e47423b049f7f863faa08655a8c901749c2b25b93ca67d01a470d

**Comment by dmcgowan** [comment]
@kiwenlau you can find the object on disk at `/var/lib/docker/image/overlay/imagedb/content/sha256/0d409d33b27e47423b049f7f863faa08655a8c901749c2b25b93ca67d01a470d`

It is downloaded using the registry HTTP API  https://docs.docker.com/registry/spec/api/#/blob.
In this case the config will be downloaded from http://registry-1.docker.io/v2/library/nginx/blobs/sha256:0d409d33b27e47423b049f7f863faa08655a8c901749c2b25b93ca67d01a470d ([token auth](https://docs.docker.com/registry/spec/auth/token/) required).

**Comment by kiwenlau** [comment]
@dmcgowan @tonistiigi 

Thanks. Problem solved!

I can get config object from:

```
 http://registry-1.docker.io/v2/library/nginx/blobs/sha256:0d409d33b27e47423b049f7f863faa08655a8c901749c2b25b93ca67d01a470d 
```
