### ISSUE TITLE
Allow setting hostname in docker service create/update

### ISSUE THREAD

**Issue by mcassaniti** [docker/docker#24877]
If some variable substitution can be done within the service create and service update commands, it would be ideal to build the hostname for a container from such variable substitutions. For instance, if the service name is represented as %s and the task ID is represented as %i, a hostname could be build as %s-%i.

Example: Service name is smtp, and there are three tasks (1,2,3). The hostname could then be set as smtp-1, smtp-2, smtp-3 depending on the task ID.

**Comment by mcassaniti** [comment]
I would suggest that this depends on #24113, although nodes in a service could in theory have the same hostname without an issue (why you would want identical hostnames I don't know).

**Comment by mavenugo** [comment]
@thaJeztah yes. we can think of setting both the `hostname` and the `net-alias` to the task-name.

**Comment by hvpareja** [comment]
Is this not the same as: https://github.com/docker/docker/pull/24973 ?

**Comment by thaJeztah** [comment]
@hvpareja https://github.com/docker/docker/pull/24973 is a pull-request that implements this

**Comment by mcassaniti** [comment]
It is similar but not the same. #24973 refers to DNS aliasing, but I'm looking at setting the actual hostname in the container at container run/create. If I was to do this outside of a swarm I would do something like:

```
#!/bin/bash

SVC_NAME=$1
SVC_IMG=$2
for i in 1 2 3 ; do
    docker run --hostname ${SVC_NAME}-0$i --name ${SVC_NAME}.$i ${SVC_IMG}
done
```

There are more traditional services that rely on having the hostname set to a particular value to identify themselves within their own cluster.

**Comment by vasil-yordanov** [comment]
I'm also interested in this feature. 
Is it possible to have the following cli interface for docker service create:
Possibility to create all containers with the same hostname.
`docker service create --hostname smtp  <image_name>`
Possibility to create all containers with hostnames like smpt-1, smpt-2,...
`docker service create --hostname smpt-* <image_name>`
Having the same hostname on all containers is useful in case we use replica=1 (actually we use one container) and we have application inside the container that needs hostname to be specified.

**Comment by PanJ** [comment]
Regarding @vasil-yordanov's idea,

`--hostname smtp` should be service's hostname, therefore resolves to every task's ip address.

Another option to resolve each container individually is also interesting. It could be like this `--container-hostname smtp-*`.

I also suggested `--namespace` option to isolate same service in different namespaces in https://github.com/docker/docker/issues/25369

**Comment by vasil-yordanov** [comment]
I managed to change the code and to add the --hostname option on docker service create, but only with this format, which I need: docker service create --hostname smtp <image_name> 
Very soon will create a pull request and hope it will be accepted. It seems I have to create pull request to docker/docker and docker/swarm repos.

**Comment by fjammes** [comment]
On my side, I'll also be interested by that feature, on of our service (named xrootd) doesn't start if machine name start with a number.
I've asked to fix xrootd also to respect RFC-1123: https://tools.ietf.org/html/rfc1123

**Comment by zxkane** [comment]
Specifying the hostname of container is mandatory if running rabbitmq cluster in swarm mode.

This feature should be considered as 'must-have' for swarm mode.

**Comment by frimdo** [comment]
+1

**Comment by liyaka** [comment]
This is a critical feature - any estimation when it will be fixed?

**Comment by justincormack** [comment]
The fastest way to get it fixed is to submit a pull request with a fix.

**Comment by the-nw1-group** [comment]
Sorry for a question here, but will the --hostname feature allow pseudo FQDN? We're using 389 LDAP server, which won't setup properly if the hostname doesn't have a . in it. We've been using docker-compose, so we can set the hostname to something.docker, which it seems to like.

**Comment by mostolog** [comment]
Isn't this possible with _naming templates_ https://github.com/docker/docker/blob/master/docs/reference/commandline/service_create.md#create-services-using-templates ?

**Comment by mcassaniti** [comment]
It seems like that would solve my problem. After reading through the (new) documentation, it seems I've got everything I'm after.

Please note that naming templates were only documented on 19th Nov 2016 which is well after this issue was raised. It seems that the ``docker service`` command has certainly changed in the last 6 months, and that development pace and easy of use is exactly why we use docker.

**Comment by mostolog** [comment]
then...close? :smile:

**Comment by mcassaniti** [comment]
Closing
