### ISSUE TITLE
Rename --registry-auth to --with-registry-auth

### ISSUE THREAD

**Issue by aluzzardi** [docker/docker#24875]
It feels like `docker service create --registry-auth` is expecting an argument.

`--with-registry-auth` might be more explicit.

Thoughts? /cc @icecrime @stevvooe @aaronlehmann

**Comment by aaronlehmann** [comment]
`--with-registry-auth` is okay with me.

**Comment by vdemeester** [comment]
SGTM too, I'll create a quick PR to fix this :wink:
