### ISSUE TITLE
Docker and Docker-compose : Auto restart not working (Cannot start a container because of oci runtime error(mkdir ID file exists)

### ISSUE THREAD

**Issue by Quentinvarquet** [docker/docker#24889]
Hello, I have a problem with one of my container (I am using docker-compose version 1.7.1).

All my containers are configured with autorestart=always

They all restart without any problem when I reboot my server. 

But if I do : 

```
service docker restart
Redirecting to /bin/systemctl restart  docker.service
```
 **Sometimes** I have a problem with one container ! It doesn't restart (always the same container) and when I want to restart it I have this message : 

`ERROR: for icinga  rpc error: code = 6 desc = "mkdir /run/containerd/f850dd365bf7d37d7e2b44aff9ba737654863c9a4da48f487c357d98af613d61: file exists"`

**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 17
 Running: 5
 Paused: 0
 Stopped: 12
Images: 44
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker-253:3-3407891-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 7.599 GB
 Data Space Total: 107.4 GB
 Data Space Available: 59.21 GB
 Metadata Space Used: 18.27 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.129 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /docker/lib/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /docker/lib/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 3.10.0-327.22.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.797 GiB
Name: Hostname_of_my_server
ID: WF47:WB7R:MWOO:5MCW:BTOJ:APGT:HM2C:EIS5:E4X3:5JWC:7N3U:D6IC
Docker Root Dir: /docker/lib
Debug mode (client): false
Debug mode (server): false
Http Proxy: My_proxy_address
Https Proxy: My_proxy_address
Username: My_User
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Steps to reproduce the issue:**

1 -  : Use my docker-compose file : 

```
icinga:
  image: jordan/icinga2
  environment:
   - ICINGA_PASSWORD=password
   - ICINGA_WEB_PASSWORD=password
   - ICINGAWEB2_PASSWORD=password
   - IDO_PASSWORD=password
   - DIRECTOR_PASSWORD=password
   - DEBIAN_SYS_MAINT_PASSWORD=password
   - DIRECTOR_KICKSTART=false
  ports:
   - "80:80" 
  restart: always
```

3 - Then, create the container and verify if it's working (default http://ip if you did not change the port 80) : 

`docker-compose up` 

3 -  Restart Docker daemon

`service docker restart`

4 - Verify if the container restarted 

`docker ps`

If not, try to start it 

`docker stard id_container`

**Describe the results you received:**

`ERROR: for icinga  rpc error: code = 6 desc = "mkdir /run/containerd/f850dd365bf7d37d7e2b44aff9ba737654863c9a4da48f487c357d98af613d61: file exists"
`

**Describe the results you expected:**

Container was suppose to restart automatically

**Additional information you deem important (e.g. issue happens only occasionally):**

Sometimes, If I restart the docker daemon one more time, the container restart...

Hope it can help

**Comment by thaJeztah** [comment]
Do the daemon logs (preferably with the daemon in `debug` mode) show anything useful?

**Comment by Quentinvarquet** [comment]
Hi,

I solved the problem with a reboot of my server.

No problem sine 5 days now.

I close :)

**Comment by thaJeztah** [comment]
Thanks @Quentinvarquet, good to hear!
