### ISSUE TITLE
[1.12-rc4] Is there a way to get the Bundle/Stack name by `docker inspect $container_id`

### ISSUE THREAD

**Issue by vitan** [docker/docker#24881]
As the subject, I'd like to get the stack name by `docker inspect $container_id` .

```
...
"OnBuild": null,
            "Labels": {
                "com.docker.swarm.node.id": "0q6hjec84yad9m6zk68fv608w",
                "com.docker.swarm.service.id": "1qbj7ps5g8pr1n7l2h8a544kc",
                "com.docker.swarm.service.name": "aaa_redis",
                "com.docker.swarm.task": "",
                "com.docker.swarm.task.id": "0rnn9ere8n4dpc473slbk01fs",
                "com.docker.swarm.task.name": "aaa_redis.1"
            }
...
```

The above example can tell me the `service name`, but no `stack name` . So can we can add another label `"com.docker.swarm.stack.name"`?

**Comment by thaJeztah** [comment]
ping @dnephin @aanand

**Comment by aanand** [comment]
This doesn't sound like a bad idea. However, given that stacks are in the experimental stage and subject to change, we shouldn't put anything into the API that people will inadvertently come to depend on. Perhaps the key should reflect that, e.g. `com.docker.experimental.stack.name`.

**Comment by yongtang** [comment]
@vitan @thaJeztah @aanand I created a pull request #25070 to add `com.docker.experimental.stack.namespace` to container labels.

This value (`labelNamespace`) was part of the service level labels before, but service level labels was not added to container labels when deployed. So I think it makes sense to just add  service level labels (`ServiceAnnotations.Labels`)  to container labels when deployed as well.

Please let me know if there are any issues.
