### ISSUE TITLE
用VM碰到类似的问题

### ISSUE THREAD

**Issue by gl328518397** [docker/docker#24899]
我再一台虚拟机上装了docker,一直很好用。
后来把这台虚拟机克隆了一下，然后docker就不能用了，报这个错，
docker: Error response from daemon: failed to create endpoint nauseous_jones on network bridge:

**Comment by thaJeztah** [comment]
could you try posting your issue in English, and provide some more information? (output of `docker version`, `docker info`, and steps to reproduce the issue) otherwise we won't be able to help

**Comment by ShevYan** [comment]
@gl328518397, I'm also from China :) According to your error message, maybe the error is because  of network configuration. Docker will configure your network while installing, so it's good to re-install docker on the cloned host.

**Comment by thaJeztah** [comment]
Thanks for helping out @ShevYan

**Comment by gl328518397** [comment]
Thank you ,I will try @ShevYan @thaJeztah
