### ISSUE TITLE
[1.12] Services based on an image from a private registry cannot be rescheduled reliably

### ISSUE THREAD

**Issue by Stehsegler** [docker/docker#24895]
As came up in https://github.com/docker/docker/issues/24891#issuecomment-234232186, services based on an image from a private registry cannot be rescheduled reliably on shutdown/crash/drain of a node. The reason for this is that the potentially necessary credentials for pulling the image, which are passed to Swarm via the `--registry-auth` flag of commands like `docker service create` and `docker service update`, are not stored permanently according to @thaJeztah and thus are not available to the node to which the task gets assigned during the rescheduling event, so that a possibly necessary pull will not be successful.

**Comment by thaJeztah** [comment]
Thanks for opening; this should be on the roadmap for 1.13, so I'll add this to that milestone

/cc @diogomonica

**Comment by aaronlehmann** [comment]
The credentials are in fact stored persistently. Rescheduling should work fine. Please reopen if there is a problem with this, but I think this ticket is based on a misunderstanding of `--registry-auth`.
