### ISSUE TITLE
service task is showing no healthcheck when checks are being run

### ISSUE THREAD

**Issue by jhorwit2** [docker/docker#24903]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 16
 Running: 7
 Paused: 0
 Stopped: 9
Images: 252
Server Version: 1.12.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 268
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay host bridge
Swarm: active
 NodeID: 58rx1deuh6s3w3g0xukzowhjg
 IsManager: Yes
 Managers: 1
 Nodes: 1
 CACertHash: sha256:02e17c8e2f8453e682f54c1e6c89f66dbd7bc905997ba281bfb1f7c680638491
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.82 GiB
Name: moby
ID: A3IT:LBGP:P3DK:6LCP:YRHJ:BY44:VHCN:X4BF:PAXO:DTD6:P725:EPJC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 72
 Goroutines: 250
 System Time: 2016-07-21T16:55:48.798100815Z
 EventsListeners: 8
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

docker for mac beta

```
FROM busybox
HEALTHCHECK --interval=5s --timeout=1s --retries=3 CMD ls /foo
CMD top
```

**Steps to reproduce the issue:**
1. `docker build -t test .`
2. `docker service create --replicas 1 --name testing test`
3. `docker ps` every second and around 15 it shows no healthcheck

**Describe the results you received:**

no healthcheck is shown even though the events say there is one being run
```
2016-07-21T12:52:30.037159026-04:00 container exec_start: /bin/sh -c ls /foo 619cb234f4a21a2e41972236a316296563d65bc65123ef1285bb852fb4336c60 (com.docker.swarm.node.id=58rx1deuh6s3w3g0xukzowhjg, com.docker.swarm.service.id=96muwz4luzouciic4nbtnud1c, com.docker.swarm.service.name=testing, com.docker.swarm.task=, com.docker.swarm.task.id=7mmdyhggakvtm7lz253x3pa71, com.docker.swarm.task.name=testing.1, image=testhc:latest, name=testing.1.7mmdyhggakvtm7lz253x3pa71)
```

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                            PORTS               NAMES
619cb234f4a2        testhc:latest       "/bin/sh -c top"         5 seconds ago       Up 4 seconds (health: starting)                       testing.1.7mmdyhggakvtm7lz253x3pa71

$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                           PORTS               NAMES
619cb234f4a2        testhc:latest       "/bin/sh -c top"         26 seconds ago      Up 25 seconds (no healthcheck)                       testing.1.7mmdyhggakvtm7lz253x3pa71
```

**Describe the results you expected:**

It shouldn't say no healthcheck when one is being checked. 

**Additional information you deem important (e.g. issue happens only occasionally):**

Should probably keep the status as `starting` until the healthcheck has been determined. That or create a new possible value for health status.

**Comment by jhorwit2** [comment]
cc @thaJeztah

**Comment by thaJeztah** [comment]
ping @tiborvass ptal

**Comment by tiborvass** [comment]
Confirmed

**Comment by jhorwit2** [comment]
So, I see the issue. I'm just trying to understand perhaps why it was done like this. [This](https://github.com/docker/docker/blob/master/container/health.go#L39) gets called when the 3rd healthcheck fails, then the status changes to `no healthcheck` while the kill event is sent out. 

The fix seems to be when [s.stop](https://github.com/docker/docker/blob/master/container/health.go#L17) is null to return unhealthy. I'm just not sure what the `no healthcheck` is there for. If there was no health check then Health will be nil on the Status struct.

**Comment by tiborvass** [comment]
Interestingly, if I don't name the built image or if I name it but build it via stdin with `docker build -t test -` then the healthcheck seems to be disabled. /cc @talex5

**Comment by jhorwit2** [comment]
While debugging I noticed that when the healthcheck is set to NONE Health.Status is [always going to be Starting](https://github.com/docker/docker/blob/master/daemon/health.go#L254). This seems kind of odd to me because if anyone uses the Health struct for anything other than String() it will return an incorrect result after the container is running.

IMO, the best solution would be to add a No Healthcheck string const to engine-api, then set the Status to that. Then when s.stop is nil always return unhealthy if the Status is not the new const. Thoughts @tiborvass

**Comment by talex5** [comment]
@jhorwit2 it checks for `if c.Config.Healthcheck == nil { return }` just above that. If only sets the state to "starting" if a check is configured but there is no status yet, which seems reasonable to me.

The `no healthcheck` message is misleading indeed. It's trying to say "No healthchecks are currently being run, even though a check is configured, because the container is shutting down". Perhaps `health-checks: stopped` or similar would be better?

**Comment by jhorwit2** [comment]
@talex5 Healthcheck will only be nil when you do not have a health check specified. When you specify one, even `HEALTHCHECK NONE`, that will not be nil. If you do specify NONE then your getProbe call will return nil causing the Status to be `starting` forever on that container. 

IMO, the status of a container shutting down should be `unhealthy` as it's shutting down. It shouldn't be receiving anymore requests and stuff to do more work. The only other thing that perhaps would be even better would be `shutting down` or something. 

since this was a quick one I opened a PR #24908
