### ISSUE TITLE
docker build should hint some kind of progress

### ISSUE THREAD

**Issue by aluzzardi** [docker/docker#24912]
As I'm running a clean build of the engine I really wish it would inform me of some kind of progress.

docker build displays the current build step as such:
```
Step 36 : WORKDIR /go/src/github.com/docker/docker
```

Which is meaningless without context.

What would help a lot would be something like:
```
Step 36/210 : WORKDIR /go/src/github.com/docker/docker
```

**Comment by yongtang** [comment]
@aluzzardi I created a pull request #24978 to add the total steps to the output of `docker build` during the progress. Please let me know if there are any issues.
