### ISSUE TITLE
.docker/config.json: permission denied after adding docker group

### ISSUE THREAD

**Issue by vitaly-krugl** [docker/docker#24910]
**Output of `docker version`:**

```
$ sudo docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
$ sudo docker info
Containers: 45
 Running: 1
 Paused: 0
 Stopped: 44
Images: 19
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 127
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.859 GiB
Name: ubuntuvm
ID: GMPW:GJ6K:UKW3:5UEM:AKHA:VVYE:NG5L:ACW7:RBZ7:RNFZ:XSSW:2IZK
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Username: numenta
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Ubuntu Server 16.04 running in VirtualBox on OS X El Capitan MacBookPro

**Steps to reproduce the issue:**
1. Follow instructions [Create a Docker group](https://docs.docker.com/v1.11/engine/installation/linux/ubuntulinux/#create-a-docker-group) "To avoid having to use sudo when you use the docker command..."
2. Execute (without `sudo`) `docker images` or any other docker command
3.

**Describe the results you received:**
Get the WARNING, such as below:

```
$ docker images
WARNING: Error loading config file:/home/vitaly/.docker/config.json - stat /home/vitaly/.docker/config.json: permission denied
REPOSITORY                                  TAG                 IMAGE ID            CREATED             SIZE
. . .
```

**Describe the results you expected:**
Expected docker client to be able to load `.docker/config.json` after following the steps in [Create a Docker group](https://docs.docker.com/v1.11/engine/installation/linux/ubuntulinux/#create-a-docker-group) "To avoid having to use sudo when you use the docker command..."

**Additional information you deem important (e.g. issue happens only occasionally):**
1. On my Ubuntu Server 16.04 installation exhibiting this issue, `~/.docker/config.json` ended up being owned by root/root:

```
$ sudo ls -al ~/.docker/config.json
-rw------- 1 root root 103 Jul 10 16:05 /home/vitaly/.docker/config.json
```
1. On my Ubuntu Desktop 14.04 installation, `~/.docker/config.json` ended up being owned by my user vitaly/vitaly, and this problem did not exist.

**Comment by justincormack** [comment]
Did you run it once with `sudo`? It would then create the `~/.docker` directory as root. You can `chown -R vitaly ~/.docker` to switch it back to your user.

**Comment by vitaly-krugl** [comment]
@justincormack, that might have been the case (most likely it was). However, I think that https://docs.docker.com/v1.11/engine/installation/linux/ubuntulinux/#create-a-docker-group deserves a mention about this, because most/many users that followed those instructions would probably have used it as sudo before deciding to create the docker user group, etc.

Best,
Vitaly

**Comment by csailer** [comment]
Did sudo docker-machine accidently - not good. @justincormack had the right answer for me.

**Comment by thaJeztah** [comment]
I'm going to close this issue, because the original issue was answered; we cannot automatically create the ownership of that file, because after switching, the docker client, is not executed as root. Also, the documentation mentioned is now move to the central documentation repository; if you think enhancements should be made to the documentation, please open an issue in that repository, or perhaps you're interested in opening a pull request for that; the file can be found here; https://github.com/docker/docker.github.io/blob/master/engine/installation/linux/ubuntulinux.md

In close this issue, but feel free to comment after I closed if you have questions.
