### ISSUE TITLE
MTU of custom network not honored by `docker run --net=custom-netowrk`

### ISSUE THREAD

**Issue by hurricanehrndz** [docker/docker#24921]
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   9e83765
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   9e83765
 Built:        
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 12
Server Version: 1.11.2
Storage Driver: btrfs
 Build Version: Btrfs v4.5.3+20160516
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.6.2-1-default
Operating System: openSUSE Tumbleweed (20160720) (x86_64)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.09 GiB
Name: folioLaptop
ID: JS7K:2SIM:TJFS:2GUW:HJ4V:JMEP:KGGY:6V4V:7AY3:6USU:CHLE:AJKB
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Create custom network
```
docker network create --subnet 192.168.0.0/24 \
-o "com.docker.network.mtu"="9000" \
-o "com.docker.network.bridge.name"="br1" custom-network
```
2. Run container that utilizes "custom-network"
```
docker run -it --net=custom-network --dns=192.168.0.1 opensuse/amd64:tumbleweed bash
```
3. verify bridge and veth are at MTU 9000 as expected `ip add`
```
6: br1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:20:fc:04:b2 brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.1/24 scope global br1
       valid_lft forever preferred_lft forever
    inet6 fe80::42:20ff:fefc:4b2/64 scope link 
       valid_lft forever preferred_lft forever
10: veth7dddae4@if9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br1 state UP group default 
    link/ether 7a:e9:61:1c:70:ba brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::78e9:61ff:fe1c:70ba/64 scope link 
       valid_lft forever preferred_lft forever
```

**Describe the results you received:**
As you can see from above  the veth interface and the corresponding bridge "br1" are set to mtu 1500.

**Describe the results you expected:**
Expect MTU to be 9000

**Additional information you deem important (e.g. issue happens only occasionally):**
The internal interface of the container as well should be 9000, but it is not.

**Comment by hurricanehrndz** [comment]
Issue exist in latest rc version as well.

**Comment by mavenugo** [comment]
@hurricanehrndz the correct option to use is `com.docker.network.driver.mtu`. Can you please give it a try ?

**Comment by einarf** [comment]
`com.docker.network.driver.mtu` is the correct name. the `br1` interface will report `mtu 1500` initially, but when you run containers it will adjust to the specified value. This is at least how it works for me in 1.12.x.

**Comment by einarf** [comment]
I'm guessing the documentation here is wrong then
https://docs.docker.com/engine/reference/commandline/network_create/#/bridge-driver-options

It claims the name should be `com.docker.network.mtu`, but that is obviously incorrect.

**Comment by ylhyh** [comment]
This post save my life:)
