### ISSUE TITLE
Public key for docker-engine-1.11.2.cs3-1.el7.centos.x86_64.rpm is not installed

### ISSUE THREAD

**Issue by ameyaagashe** [docker/docker#24922]
Apologies if I am not following any of your protocol but I am not able to install docker v1.11 on my CentoS 7.2
[jim@docker1 ~]$ cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 
[jim@docker1 ~]$
I installed the instructions from here:
https://docs.docker.com/engine/installation/linux/centos/

However I do get the following error
Public key for docker-engine-1.11.2.cs3-1.el7.centos.x86_64.rpm is not installed

I tried to install the gpg with the following commands:
[jim@docker1 ~]$ sudo wget -o https://yum.dockerproject.org/gpg
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
[jim@docker1 ~]$ sudo wget -O https://yum.dockerproject.org/gpg
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
[jim@docker1 ~]$ sudo wget https://yum.dockerproject.org/gpg
--2016-07-22 14:46:26--  https://yum.dockerproject.org/gpg
Resolving yum.dockerproject.org (yum.dockerproject.org)... 54.230.242.200
Connecting to yum.dockerproject.org (yum.dockerproject.org)|54.230.242.200|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1648 (1.6K) [application/pgp-keys]
Saving to: â€˜gpgâ€™

100%[====================================================================================================>] 1,648       --.-K/s   in 0s      

2016-07-22 14:46:27 (137 MB/s) - â€˜gpgâ€™ saved [1648/1648]

[jim@docker1 ~]$ ls -l
total 4
drwxrwxr-x. 3 jim  jim    26 Jul 21 14:57 Documents
-rw-r--r--. 1 root root 1648 Jun  2 21:10 gpg
drwxrwxr-x. 2 jim  jim    23 Jul 22 00:47 web
[jim@docker1 ~]$ gpd --import gpg 
-bash: gpd: command not found
[jim@docker1 ~]$ gpg --import gpg 
gpg: directory `/home/jim/.gnupg' created
gpg: new configuration file `/home/jim/.gnupg/gpg.conf' created
gpg: WARNING: options in `/home/jim/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/home/jim/.gnupg/secring.gpg' created
gpg: keyring `/home/jim/.gnupg/pubring.gpg' created
gpg: /home/jim/.gnupg/trustdb.gpg: trustdb created
gpg: key 2C52609D: public key "Docker Release Tool (releasedocker) <docker@docker.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)

Still no charm, Please help why I am not able to install docker-engine/docker application.

Thanks
Ameya

**Comment by thaJeztah** [comment]
Which version of docker are you trying to install? From the error message, it looks like you tried installing the CS version of docker (https://docs.docker.com/cs-engine/install/), however, the steps above looks like your trying to install the Open Source version.

Did you previously have the CS version of Docker installed?

Note that for the regular instructions, there's no need to manually add the GPG key, it's defined in the yum repo settings (see step 3. under https://docs.docker.com/engine/installation/linux/centos/#/install)

**Comment by ameyaagashe** [comment]
Hi thaJeztah,

I am installing open source docker, I have given that in my comment. I get the error when I try to install with yum and even with script, url https://docs.docker.com/engine/installation/linux/centos/#/install

Please find below my exact instructions along with output:

`[jim@docker1 ~]$ docker info
-bash: docker: command not found
[jim@docker1 ~]$ yum list installed |grep docker
[jim@docker1 ~]$ sudo whereis docker
docker:[jim@docker1 ~]$ 
[jim@docker1 ~]$ sudo locate docker
sudo: locate: command not found
[jim@docker1 ~]$  sudo yum install docker-engine
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.internode.on.net
 * extras: mirror.internode.on.net
 * updates: mirror.internode.on.net
Resolving Dependencies
--> Running transaction check
---> Package docker-engine.x86_64 0:1.11.2.cs3-1.el7.centos will be installed
--> Processing Dependency: docker-engine-selinux >= 1.11.2.cs3-1.el7.centos for package: docker-engine-1.11.2.cs3-1.el7.centos.x86_64
--> Processing Dependency: libltdl.so.7()(64bit) for package: docker-engine-1.11.2.cs3-1.el7.centos.x86_64
--> Running transaction check
---> Package docker-engine-selinux.noarch 0:1.11.2.cs3-1.el7.centos will be installed
---> Package libtool-ltdl.x86_64 0:2.4.2-21.el7_2 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

==============================================================================================================================================
 Package                       Arch           Version                           Repository                                               Size
==============================================================================================================================================
Installing:
 docker-engine                 x86_64         1.11.2.cs3-1.el7.centos           packages.docker.com_1.11_yum_repo_main_centos_7          13 M
Installing for dependencies:
 docker-engine-selinux         noarch         1.11.2.cs3-1.el7.centos           packages.docker.com_1.11_yum_repo_main_centos_7          28 k
 libtool-ltdl                  x86_64         2.4.2-21.el7_2                    updates                                                  49 k

Transaction Summary
==============================================================================================================================================
Install  1 Package (+2 Dependent packages)

Total size: 13 M
Installed size: 54 M
Is this ok [y/d/N]: y
Downloading packages:
warning: /var/cache/yum/x86_64/7/packages.docker.com_1.11_yum_repo_main_centos_7/packages/docker-engine-1.11.2.cs3-1.el7.centos.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID 6238f52e: NOKEY


**Public key for docker-engine-1.11.2.cs3-1.el7.centos.x86_64.rpm is not installed**
[jim@docker1 ~]$ sudo cat /etc/yum.repos.d/docker
cat: /etc/yum.repos.d/docker: No such file or directory
[jim@docker1 ~]$ sudo cat /etc/yum.repos.d/docker.repo 
[dockerrepo]
name=Docker Repository
baseurl=https://yum.dockerproject.org/repo/main/centos/7/
enabled=1
gpgcheck=1
gpgkey=https://yum.dockerproject.org/gpg
[jim@docker1 ~]$ `

As in above the highlighted line is reported and docker is not installed.

If I run command:
yum install docker-engine

It installs docker v1.10 but I want (frankly) v1.12(I'm not sure if its released yet) but if not v1.11

Please assist.

Thanks

**Comment by ameyaagashe** [comment]
Hi,

I'm not sure what is installed by the following two different commands. I believe both of them install docker-engine.

sudo yum install docker-engine# this is given is official documentation
sudo yum install docker #This is given in official AWS documentation for deploying Docker on Amazon Linux Instance
(http://docs.aws.amazon.com/AmazonECS/latest/developerguide/docker-basics.html)
For me as I said previously yum install docker-engine does not work but yum install docker works !
Host OS is CentOS 7.2

Any questions. Kindly ask.

**Comment by thaJeztah** [comment]
the `install docker` is not the package we distribute.

the `packages.docker.com` really seems to indicate you have (or had) the CS version of docker installed. Does `yum repolist all` show you some other repository?

**Comment by ameyaagashe** [comment]
Hi mate,

Thanks for the hint ! That solved all the problem.

Here is the approach which might be helpful for others to resolve the issue.

```
[jim@docker1 nagios-docker]$ yum repolist all
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.aarnet.edu.au
 * extras: mirror.aarnet.edu.au
 * updates: mirror.aarnet.edu.au
repo id                                               repo name                                                                 status
C7.0.1406-base/x86_64                                 CentOS-7.0.1406 - Base                                                    disabled
C7.0.1406-centosplus/x86_64                           CentOS-7.0.1406 - CentOSPlus                                              disabled
C7.0.1406-extras/x86_64                               CentOS-7.0.1406 - Extras                                                  disabled
C7.0.1406-fasttrack/x86_64                            CentOS-7.0.1406 - CentOSPlus                                              disabled
C7.0.1406-updates/x86_64                              CentOS-7.0.1406 - Updates                                                 disabled
C7.1.1503-base/x86_64                                 CentOS-7.1.1503 - Base                                                    disabled
C7.1.1503-centosplus/x86_64                           CentOS-7.1.1503 - CentOSPlus                                              disabled
C7.1.1503-extras/x86_64                               CentOS-7.1.1503 - Extras                                                  disabled
C7.1.1503-fasttrack/x86_64                            CentOS-7.1.1503 - CentOSPlus                                              disabled
C7.1.1503-updates/x86_64                              CentOS-7.1.1503 - Updates                                                 disabled
base/7/x86_64                                         CentOS-7 - Base                                                           enabled: 9,007
base-debuginfo/x86_64                                 CentOS-7 - Debuginfo                                                      disabled
base-source/7                                         CentOS-7 - Base Sources                                                   disabled
c7-media                                              CentOS-7 - Media                                                          disabled
centosplus/7/x86_64                                   CentOS-7 - Plus                                                           disabled
centosplus-source/7                                   CentOS-7 - Plus Sources                                                   disabled
cr/7/x86_64                                           CentOS-7 - cr                                                             disabled
docker-main-repo                                      Docker main Repository                                                    enabled:    45
dockerrepo                                            Docker Repository                                                         enabled:    45
extras/7/x86_64                                       CentOS-7 - Extras                                                         enabled:   356
extras-source/7                                       CentOS-7 - Extras Sources                                                 disabled
fasttrack/7/x86_64                                    CentOS-7 - fasttrack                                                      disabled
packages.docker.com_1.11_yum_repo_main_centos_7       added from: https://packages.docker.com/1.11/yum/repo/main/centos/7       enabled:    15
updates/7/x86_64                                      CentOS-7 - Updates                                                        enabled: 2,026
updates-source/7                                      CentOS-7 - Updates Sources                                                disabled
repolist: 11,494
[jim@docker1 nagios-docker]$
```

I deleted and then ran yum clean all to clean all repositories except give by docs.docker.com(https://docs.docker.com/engine/installation/linux/centos/#/install)

```
[root@docker1 yum.repos.d]# rm  packages.docker.com_1.11_yum_repo_main_centos_7.repo docker-main.repo
rm: remove regular file â€˜packages.docker.com_1.11_yum_repo_main_centos_7.repoâ€™? y
rm: remove regular file â€˜docker-main.repoâ€™? y
[root@docker1 yum.repos.d]# yum clean all
```

Nevertheless docker was installed from extras repo but deleting the unwanted repo did fix the problem.
```
[jim@docker1 ~]$ sudo yum list installed |grep docker
docker.x86_64                         1.10.3-44.el7.centos             @extras  
docker-common.x86_64                  1.10.3-44.el7.centos             @extras  
docker-forward-journald.x86_64        1.10.3-44.el7.centos             @extras  
docker-selinux.x86_64                 1.10.3-44.el7.centos             @extras  
[jim@docker1 ~]$ sudo yum remove -y docker.x86_64 docker-common.x86_64 docker-forward-journald.x86_64 docker-selinux.x86_64

```
Ran yum install docker-engine and problem solved!

One last question, do we have any documentation for upgrade? like upgrading from 1.10 to 1.11? or from 1.10 to 1.12?
The approach I adopted was uninstalling old package by yum and installing new package by yum although I'm not if there are implications of doing such operation in production. 

Many Thanks for your help !

**Comment by thaJeztah** [comment]
just like any other package installed through yum

**Comment by ameyaagashe** [comment]
Thanks mate for your help. Happy with docker 1.11 so I'm now closing the issue.
