### ISSUE TITLE
[1.12.0-rc4] About stack service params

### ISSUE THREAD

**Issue by upccup** [docker/docker#24923]
According to my understanding stack is a set of some services. But there is a question why the stack service  params is  not the same with general service. 
The stack service struct is 
```
// Service is a service from a bundlefile
type Service struct {
	Image      string
	Command    []string          `json:",omitempty"`
	Args       []string          `json:",omitempty"`
	Env        []string          `json:",omitempty"`
	Labels     map[string]string `json:",omitempty"`
	Ports      []Port            `json:",omitempty"`
	WorkingDir *string           `json:",omitempty"`
	User       *string           `json:",omitempty"`
	Networks   []string          `json:",omitempty"`
}
```

And the service struct is 
```

// Service represents a service.
type Service struct {
	ID string
	Meta
	Spec     ServiceSpec `json:",omitempty"`
	Endpoint Endpoint    `json:",omitempty"`
}

// ServiceSpec represents the spec of a service.
type ServiceSpec struct {
	Annotations

	// TaskTemplate defines how the service should construct new tasks when
	// orchestrating this service.
	TaskTemplate TaskSpec                  `json:",omitempty"`
	Mode         ServiceMode               `json:",omitempty"`
	UpdateConfig *UpdateConfig             `json:",omitempty"`
	Networks     []NetworkAttachmentConfig `json:",omitempty"`
	EndpointSpec *EndpointSpec             `json:",omitempty"`
}

....
```

What my doubt is why add all the service params to stack service?

**Comment by dnephin** [comment]
Stacks can only contain portable options, they are meant to be distributable.
Raw services can also contain non-portable configuration.

**Comment by upccup** [comment]
@dnephin maybe i was misunderstanding of stack. but i think stack is only a set of some services

**Comment by thaJeztah** [comment]
The "stack" feature is still experimental, and things may (/will) change. I think the idea is to split service "definition" and "runtime configuration" into separate files

**Comment by stevvooe** [comment]
@upccup Indeed, stacks mix the concept of services and containers in an odd manner. Stacks still need to be changed to match the schema for services.

This has nothing to do with portability -- that _must_ be done at the field-level. Types like `ServiceSpec`, `TaskSpec` and `ContainerSpec` already provide much of this separation.

**Comment by upccup** [comment]
@stevvooe   thx
