### ISSUE TITLE
[Feature Request] containers, services list filter by label, name with regexp support

### ISSUE THREAD

**Issue by cmingxu** [docker/docker#24920]
For example, I want filter my services or containers with label or name with regexp support

`docker ls --filter label=labelName=*label*`
`docker service ls --filter label=labelName=*label*`
`docker ls --filter name=*name*`

Thanks

**Comment by thaJeztah** [comment]
this is a duplicate (or close to) of https://github.com/docker/docker/issues/17569, and https://github.com/docker/docker/issues/13533 so I'm closing this one; please continue the discussion on those.

Thanks for suggesting!
