### ISSUE TITLE
[Proposal] - Running Job in Docker container: timeout parameter

### ISSUE THREAD

**Issue by samber** [docker/docker#24937]
Hi guys,

I sometimes run some jobs with Docker. I think it would be a best practice to set a timeout on this container.

What about a new option such as: ```docker run --rm --timeout=120 owner/job-1```

**Comment by z00223295** [comment]
relate to [docker_container_timeout](https://github.com/docker/docker/issues/1905)

**Comment by samber** [comment]
```sh
$ docker run —rm -d -v /var/run/docker.sock:/var/run/docker.sock docker:dind bash -c “sleep 42 && docker stop my-job”
$ docker run —rm —name my-job advize/my-job
```
