### ISSUE TITLE
Error: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by pcgeek86** [docker/docker#24945]
# Scenario

1. We set up VMware Harbor with a trusted TLS certificate
2. We are attempting to `docker push` an image to the VMware Harbor registry
3. We are receiving an error: `x509: certificate signed by unknown authority`

# What We've Tried

- Install Mozilla's trusted root CAs into `/usr/local/share/ca-certificates/`
- Manually export COMODO root CA into `/usr/local/share/ca-certificates/`
- Copy Mozilla's trusted root CAs into `/etc/docker/certs.d/customdomain.com.crt`

How do I make the Docker Engine trust this root CA? We're completely out of ideas.

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by thaJeztah** [comment]
Related to https://github.com/docker/docker/issues/12756 ?

**Comment by dmcgowan** [comment]
I think this is related to https://github.com/docker/docker/issues/12756. Try either adding custom certs from `/etc/docker/certs.d/<domain>` into the system certs, or add a copy of the system certificates as a `.crt` file in  `/etc/docker/certs.d/<domain>`.

**Comment by thaJeztah** [comment]
thanks for looking @dmcgowan 

@pcgeek86 I'll go ahead and close this issue, but feel free to continue the discussion here
