### ISSUE TITLE
Document service create / service update flags

### ISSUE THREAD

**Issue by aaronlehmann** [docker/docker#24946]
The command line reference documentation for `docker service create` and `docker service updates` lists the supported flag, but does not explain each one in detail. When possible, we should add detailed descriptions of the flags.

cc @sfsmithcha

**Comment by sfsmithcha** [comment]
Lots of the flags are covered here :https://github.com/docker/docker/commit/861d4dc989ae738a1c219291a96333a7577b1699 .  Content should be pared back simplified for CLI ref

cc: @thaJeztah

**Comment by mstanleyjones** [comment]
Good enough for now. When the automated API and CLI are done, these per-flag details will be in the Cobra code.
