### ISSUE TITLE
Cluster defaults should not be overridden by swarm init

### ISSUE THREAD

**Issue by aaronlehmann** [docker/docker#24958]
`swarm init` creates a `ClusterSpec` and overwrites the cluster's object spec with this one. This means defaults such as certificate validity period and task history retention are under the client's control. They should be under SwarmKit's control instead.

`swarm init` should only change values from the defaults when a value is given through a flag. Currently, it appears to overwrite the whole spec with the client-side defaults when no flags are specified.

cc @aluzzardi @tonistiigi

**Comment by aaronlehmann** [comment]
Note that as a consequence of this, it's impossible to set the task retention limit to 0. 0 is a valid value, but the engine replaces 0 with the default value.

**Comment by yongtang** [comment]
@aaronlehmann I created a pull request #25697 yo try to address this issue.
