### ISSUE TITLE
Expose non-manager external IP through API visible on manager nodes

### ISSUE THREAD

**Issue by dhiltgen** [docker/docker#24956]
As a follow on to #24017 and PR #24237 it would be desirable to also expose the worker node IP addresses within the API visible on a manager.

**Comment by vitan** [comment]
@aaronlehmann  , have u working on it? Or where can I taste the fresh?

**Comment by alexmavr** [comment]
Fixed in https://github.com/docker/docker/pull/27910, please close this

**Comment by aaronlehmann** [comment]
Sure thing.
