### ISSUE TITLE
bad symlink in a layer's layer.tar after docker save

### ISSUE THREAD

**Issue by rosteroster** [docker/docker#24951]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:39:43 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 160
Server Version: 1.12.0-rc4
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 349
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-boot2docker
Operating System: Boot2Docker 1.12.0-rc4 (TCL 7.2); HEAD : cbe6927 - Wed Jul 13 14:19:29 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 7.79 GiB
Name: devbox
ID: VNXR:LKTE:FPUE:6WII:FLWH:LSMX:XHX5:RLTO:G432:UW3A:GLEW:WY7Y
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 14
 Goroutines: 24
 System Time: 2016-07-22T20:27:40.063979399Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. docker pull mysql:5.5.49
2. docker save mysql:5.5.49 > ~/somepath/image.tar
3. cd ~/somepath/
4. tar -xvf image.tar
5. cat 1e5794c8fc53cbd0cb5549f0c86e40020ea3e05a03c4c0f643fb73cd0004d6ca/layer.tar
6. ls -al 1e5794c8fc53cbd0cb5549f0c86e40020ea3e05a03c4c0f643fb73cd0004d6ca/layer.tar

**Describe the results you received:**
The "cat ....../layer.tar" is printing "no such file or directory". This is because the layer.tar is actually a symlink with a relative path of "../../7ad474727cd0614d18a510213c2a3fbe9df0533b3e2dc593099084844fbfb53a/layer.tar". That is a bad symlink that points to nothing.
The image seems to run fine but the bad layer.tar is messing up some tools.

**Describe the results you expected:**
I expected the layer.tar to be a file or at least a valid symlink.

**Additional information you deem important (e.g. issue happens only occasionally):**
the manifest for mysql:5.5.49:
[
    {
        "Config": "2f94d2a2ac899385096c4cfae60d737e4744a45a9611f7e2f8adf4126bd13c52.json",
        "Layers": [
"632dd2dc36915d5b956a407429f20b081e500193e8309d2fa5a2151f2264badf/layer.tar",
"7ad474727cd0614d18a510213c2a3fbe9df0533b3e2dc593099084844fbfb53a/layer.tar",
"835a09f3e6807faf50db55c0501323decfbbbbfd0aa8d3701be092763352ceaf/layer.tar",
"1e5794c8fc53cbd0cb5549f0c86e40020ea3e05a03c4c0f643fb73cd0004d6ca/layer.tar",
"e90f58b4afcc17a2063d0a2182caa8de6d103eab65726d7586d467b197f2cac0/layer.tar",
"ce89a69ed999835e6a29ec51529cc650951a682e081b12895114d8ae00efafdb/layer.tar",
"5446ddd2a5287e2889e860f3b5b6c71bc5e3875ba40efc8a89364df76f5fb2fe/layer.tar",
"504434ed9b6ddd5559c5361f467e2d30175df64697e27ae17b6dc898c9f6d3e3/layer.tar",
"4adcda71f9d2866e74a65ef93d03034a84027298ce77eaa25f15f9a57b5cc5c9/layer.tar",
"e8445e2f1afa2413b582fea81a9edaf8a38f9d27fb179a25e98f3636496cb13a/layer.tar",
"2ebf45437a30bb52490611f47180ac91230cccf3e92d14d614ba9964f49dd93f/layer.tar",
"95d74f14e12f36f8ff8e56de171034feb7a543f5aad96b5cb479fd2b161ddea2/layer.tar",
"e366823a5b4f6ed67b0e2ae6ea45f4bbe1a62040a0875226bfa8ea5086f2d8e4/layer.tar",
"ceccf7454d07595891462c59dc2a9dedf29d3e3817a7a31131e0841d59dc9676/layer.tar",
"c1e43f4f26f1310ffe7033dbd8a4c9f2a936cb2c584a0428b02f5eb793a589a6/layer.tar",
"9d0b653af526957cdc29af8babba96ae71f924270284e8f55a8c66043f3883b4/layer.tar",
"e015bfcd281c2c3918ef00b8bb6a398fe4f4eaee7a544c39089c0157a9cdf210/layer.tar",
"3454489477d6a1f94b5ee2882f7d790f43f5c62c4fd695925c69400b7ba66181/layer.tar",
"33190324687ccab11ddaeeb15ca6a59e752c57371f77c9eaad19c60d322e64f8/layer.tar",
"1227ddfd0d450b6038463eaca8d771113f6ee2b09ddecfd07dca4d843f67f6da/layer.tar"
        ],
        "RepoTags": [
            "mysql:5.5.49"
        ]
    }
]

**Comment by goldmann** [comment]
We do see this too, take a look at this gist: https://gist.github.com/hyperknot/6ec3b033c66bbba5a1794b854faed11c

/cc @hyperknot

**Comment by goldmann** [comment]
This is probably related to this commit: https://github.com/docker/docker/commit/88cb79d40010d95cdbd69bb069b4726611831b27

/cc @tonistiigi

**Comment by hyperknot** [comment]
I can confirm, I stumbled upon this bug when using @goldmann's docker-squash, but it is actually a bug in Docker core.

**Comment by thaJeztah** [comment]
ping @aaronlehmann @dmcgowan  PTAL

**Comment by dmcgowan** [comment]
I am also able to reproduce, taking a look

**Comment by dmcgowan** [comment]
I found this to be working for docker load in 1.12 but failing to load in 1.9. This works in 1.12 because the layers which the bad symlinks are empty tars, and the code currently checks for the hash associated with empty tars and skips the layer import. For 1.9 these layers are not skipped and the following error occurs `Error response from daemon: open /var/lib/docker/tmp/docker-import-058192204/repo/1227ddfd0d450b6038463eaca8d771113f6ee2b09ddecfd07dca4d843f67f6da/layer.tar: no such file or directory`. Working on a fix.

**Comment by goldmann** [comment]
Yay, thanks for this quick fix!

**Comment by thaJeztah** [comment]
Thanks @rosteroster @goldmann @hyperknot for a concise bug report, much appreciated!
