### ISSUE TITLE
Unable to run docker image: mountpoint for blkio not found

### ISSUE THREAD

**Issue by wichtounet** [docker/docker#24965]
I have inadvertently upgraded Docker from 1.7.1 to Docker 1.11. After this, since nothing worked anymore, I downgraded back to 1.7.1, but I'm not able to run my images any more.

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Output of `docker version`:**

```
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```

**Output of `docker info`:**

```

    Containers: 6
    Images: 19
    Storage Driver: devicemapper
     Pool Name: docker-253:1-130958-pool
     Pool Blocksize: 65.54 kB
     Backing Filesystem: extfs
     Data file: /dev/loop0
     Metadata file: /dev/loop1
     Data Space Used: 2.452 GB
     Data Space Total: 107.4 GB
     Data Space Available: 37.47 GB
     Metadata Space Used: 2.834 MB
     Metadata Space Total: 2.147 GB
     Metadata Space Available: 2.145 GB
     Udev Sync Supported: true
     Deferred Removal Enabled: false
     Data loop file: /data/docker/docker/devicemapper/devicemapper/data
     Metadata loop file: /data/docker/docker/devicemapper/devicemapper/metadata
     Library Version: 1.02.93 (2015-01-30)
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 3.18.9-hardened
    Operating System: Gentoo/Linux (containerized)
    CPUs: 4
    Total Memory: 7.674 GiB
    Name: mimir
    ID: 623Z:WWF5:2UAF:QTJM:4PME:WNJM:FU53:ZBV2:AOEN:IWXT:CEA4:FVC3
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical machine, gentoo hardened 3.18.9

**Steps to reproduce the issue:**

    /usr/bin/docker run --rm --name tt_rss_database -p 20001:5432 -e DB_USER=tt_rss_user -e DB_PASS=PostgreSQL2013 -e DB_NAME=tt_rss -v /data/docker/volumes/postgresql/data/tt-rss:/var/lib/postgresql -v /data/docker/volumes/postgresql/run/tt-rss:/run/postgresql gentoo-pgsql-9.4

**Describe the results you received:**

> Error response from daemon: Cannot start container
> 895f8a3a61c8e38e7dea5f5094031e8494d3060226efc856fa5d8234f321c9e7: [8]
> System error: mountpoint for blkio not found

**Describe the results you expected:**

The container should be running

Thanks

**Comment by thaJeztah** [comment]
Just to check, you could try running the check-config script if something is missing on your system; https://github.com/docker/docker/blob/master/contrib/check-config.sh

**Comment by wichtounet** [comment]
I had a few things missing indeed. After that, I had an error about cpu.shares that I fixed with `--exec-opt native.cgroupdriver=cgroupfs`. I guess issues were coming from updates to systemd components. 

Thanks

**Comment by thaJeztah** [comment]
You're welcome!
