### ISSUE TITLE
Failed migration: failed to update app version history 

### ISSUE THREAD

**Issue by oschrenk** [docker/docker#24966]
Trying to run Docker for Mac beta 20 over an old (beta 6) installation. Can't run as app version migration fails.

```
Docker for Mac: version: mac-v1.12.0-beta20
OS X: version 10.12 (build: 16A254g)
```

**Docker for Mac Diagnostics:**

```
Docker for Mac: version: mac-v1.12.0-beta20
OS X: version 10.12 (build: 16A254g)
logs: /tmp/20160720-234808.tar.gz
failure: com.docker.slirp is not running
[ERROR]  docker-cli
         cannot find docker
         docker-cli check failed with: Failure("docker -v: timeout after 10.00s")
[OK]     app
[OK]     moby-syslog
[OK]     virtualization
[OK]     menubar
[OK]     system
[ERROR]  osxfs
         com.docker.osxfs is not running
[ERROR]  db
         Connection refused (ECONNREFUSED) connecting to /Users/admin/Library/Containers/com.docker.docker/Data/s40: check if service is running
         com.docker.db is not running
[ERROR]  slirp
         Connection refused (ECONNREFUSED) connecting to /Users/admin/Library/Containers/com.docker.docker/Data/s51: check if service is running
         com.docker.slirp is not running
[OK]     moby-console
[OK]     logs
[ERROR]  vmnetd
         /var/tmp/com.docker.vmnetd.socket does not exist
         Unexpected error (No such file or directory) connecting to /var/tmp/com.docker.vmnetd.socket
         /private/tmp/vmnetd/com.docker.vmnetd is not running
[OK]     env
[OK]     moby
[ERROR]  driver.amd64-linux
         Docker.app/Contents/MacOS/com.docker.driver.amd64-linux -db is not running
```

**sytem.log output:**

```
Jul 23 12:08:05 OlschBook Docker[69339]: Application version: 1.12.0-rc4-beta20 (10404)
Jul 23 12:08:05 OlschBook Docker[69339]: Administrator user: true
Jul 23 12:08:05 OlschBook Docker[69339]: OSX Version: Version 10.12 (Build 16A254g)
Jul 23 12:08:05 OlschBook Docker[69339]: migrator: start migration process
Jul 23 12:08:05 OlschBook Docker[69339]: migrator: previous install detected
Jul 23 12:08:05 OlschBook Docker[69339]: migrator: previous version is 1.11.0-beta6
Jul 23 12:08:05 OlschBook Docker[69339]: migrator: 15 migrations to perform
Jul 23 12:08:05 OlschBook Docker[69339]: migrator: migrating for version 1.11.0-beta7 ...
Jul 23 12:08:05 OlschBook Docker[69339]: migrator: migration failed (1.11.0-beta7) (failed to update app version history)
Jul 23 12:08:05 OlschBook Docker[69339]: failed migration: failed to update app version history
```

**Things I tried**

I tried to look for every remnant of Docker on my machine and tried to remove it, to no avail

I deleted

```
~/Library/Containers/com.docker.docker
~/Library/Containers/com.docker.helper
~/Library/Group Containers/group.com.docker
~/Library/Preferences/com.docker.docker.plist
```

and followed the steps from https://github.com/docker/toolbox/blob/master/osx/uninstall.sh and https://therealmarv.com/how-to-fully-uninstall-the-offical-docker-os-x-installation/

but still there seems to be some data of the old installation lying around.

**Steps to reproduce the issue:**
1. Have tried beta 6 in the past. Abandon it for a month or two.
2. Try to use latest beta 20 version

**Describe the results you received:**

Getting dialog with `Failed migration: failed to update app version history ` message. 

**Describe the results you expected:**

Running docker.

**Comment by oschrenk** [comment]
I've read that the GUI has a possibility to reset to factory defaults. Is that possible to call from the command line?

**Comment by justincormack** [comment]
Those instructions you linked to don't look correct for Docker for Mac. We used to have a shell uninstaller but don't seem to any more. I think if you delete the `~/Library/Containers/com.docker.docker` and `/Applications/Docker.app` folders and kill all processes with docker in the name (from `ps auxww | grep docker` you will need `sudo` to kill the `vmnetd` process) then you should be good to do a clean reinstall.

**Comment by oschrenk** [comment]
Well. Even if the toolbox uninstall scripts do not really apply anymore it helped me delete some old stuff from the system.

Deleting the container items and deleting the old app, got me a bit further. Now it is stuck on beta 10 migrations.

Is there any way to log what he is actually failing on?

```
Jul 27 23:20:16 OlschBook com.apple.usbmuxd[65777]: LOCKDOWN_V2_BONJOUR_SERVICE_NAME is _apple-mobdev2._tcp,916307f7
Jul 27 23:20:18 OlschBook diagnosticd[300]: System mode client started - Console (67993) - mode: 0x8
Jul 27 23:20:19 OlschBook Docker[67968]: Application version: 1.12.0-rc4-beta20 (10404)
Jul 27 23:20:19 OlschBook Docker[67968]: Administrator user: true
Jul 27 23:20:19 OlschBook Docker[67968]: OSX Version: Version 10.12 (Build 16A254g)
Jul 27 23:20:19 OlschBook Docker[67968]: migrator: start migration process
Jul 27 23:20:19 OlschBook Docker[67968]: migrator: previous install detected
Jul 27 23:20:19 OlschBook Docker[67968]: migrator: previous version is 1.11.1-beta10
Jul 27 23:20:19 OlschBook Docker[67968]: migrator: 11 migrations to perform
Jul 27 23:20:19 OlschBook Docker[67968]: migrator: migrating for version 1.11.1-beta11 ...
Jul 27 23:20:19 OlschBook Docker[67968]: migrator: migration failed (1.11.1-beta11) (failed to update app version history)
Jul 27 23:20:19 OlschBook Docker[67968]: failed migration: failed to update app version history
```

**Comment by oschrenk** [comment]
Deleting the app dir or container dir wasn't it. Just exiting the installer and restarting it again, and again, and again helps. Which each iteration it fails one migration step, I exit, I start, it fails the next possible migration. 

After what felt like restarting the app at least 20 times it actually now runs...

**Comment by maokomioko** [comment]
Can confirm that constant restarting helps. Takes ~ 4-7 times depending on which version was used before.

**Comment by pwnsdx** [comment]
Same here but it do only once and after restarting I get this:

![screen shot 2016-08-14 at 07 21 00](https://cloud.githubusercontent.com/assets/2057765/17647425/c1329056-61ef-11e6-9559-83c84b76d32e.png)

then after restarting again it seems working...

I'm on Sierra and I use Docker Beta (latest version)

**Comment by markvl91** [comment]
Restarting multiple times did the trick for me too, thanks!

**Comment by VirtueMe** [comment]
After deleting the recommended file and folder and reinstalling Docker it worked for us.

**Comment by justincormack** [comment]
I am going to close this as it seems resolved, and I don't think it should happen again with new versions, but please reopen or comment if it is still an issue.
