### ISSUE TITLE
AWS ECR push doesn't work when .docker/config.json uses "credsStore": "wincred"

### ISSUE THREAD

**Issue by mikkotikkanen** [docker/docker#24968]
---
## BUG REPORT INFORMATION

**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 14
Server Version: 1.12.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 16
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953 GiB
Name: moby
ID: T3DF:YLQQ:QL62:XZ6K:4NHU:LVRZ:REAO:XTM7:QWWI:UQWQ:PKLT:PQX7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Make sure `.docker/config.json` doesn't exist to provide default behavior on login
2. Set Docker login to AWS ECR with `aws ecr get-login`
3. Try to to docker push to AWS ECR
4. Push fails with `no basic auth credentials`
5. Remove `"credsStore": "wincred"` from `.docker/config.json`
6. Set Docker login to AWS ECR with `aws ecr get-login` again
7 Try to to docker push to AWS ECR
8. Push succeeds

**Describe the results you received:**
Failure with `no basic auth credentials` error

**Describe the results you expected:**
Push to succeed

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by samuelkarp** [comment]
Thanks @thaJeztah!  This looks like the same issue as https://github.com/docker/docker/issues/22910.

@mikkotikkanen If you're only using ECR (and not other private registries) you can try the [Amazon ECR credential helper](https://github.com/awslabs/amazon-ecr-credential-helper) we wrote.

**Comment by damienwebdev** [comment]
Not sure if this is the proper place to put this, but I'm getting a similar thing in the Google Cloud cli which I think just uses the native docker.

as @mikkotikkanen mentioned, the steps to reproduce are the same, just using the

* `gcloud docker -- push` syntax instead.

**Comment by thaJeztah** [comment]
@damienwebdev probably best to report at Google cloud first.


I'll go ahead and close this issue, as I think it's answered, but @mikkotikkanen let us know if it's resolved with @samuelkarp 's suggestion
