### ISSUE TITLE
[1.12rc4] docker stats infinite loop after removing containers

### ISSUE THREAD

**Issue by GuillaumeDerval** [docker/docker#24999]
Removing a container with `docker rm -f` while watching its stats with `docker stats` creates a bug with docker stats that takes 99% of the CPU (or more according to the number of cores you have).

It seems to happen each time a container that 'has been seen' by `docker stats` is removed.

As indicated below, the problem is probably in the daemon rather than in the client, as it is reproducible with docker-py.

**Output of `docker version`:**
(also tested on a Fedora 24 VM with the same version of Docker client/server)
```
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 26
 Running: 1
 Paused: 0
 Stopped: 25
Images: 75
Server Version: 1.12.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 124
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null bridge host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.954 GiB
Name: moby
ID: HFSP:6PBA:U5F4:5ZV7:EH7F:7OKJ:3ALL:PXGV:RWTY:F2RQ:JDCF:YTUW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 42
 System Time: 2016-07-25T07:44:01.746691065Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Problem occurs, at least, on the current Docker for Mac 1.12rc4-beta20 and on a Fedora 24 VM with Docker 1.12rc4.

**Steps to reproduce the issue:**
1. start a random container: `docker run -ti --name arandomname centos`, and leave it alive
2. start `docker stats`
3. remove the first container with `docker rm -f arandomname`

It also happens when I do this:
1. start `docker stats`
2. start a random container: `docker run --name arandomname centos sleep 5`, wait until it ends
3. (docker stats is still behaving properly)
4. `docker rm arandomname`

**Describe the results you received:**
CPU usage skyrockets

**Describe the results you expected:**
CPU usage remains low, as usual when using docker stats.

**Additional information you deem important (e.g. issue happens only occasionally):**
When I test the issue with docker-py, `client.stats` returns me an infinite number of None, so it probably means the issue is on the daemon side.

**Comment by GuillaumeDerval** [comment]
I rapidly tested on Docker 1.10, I could not reproduce the problem.

**Comment by thaJeztah** [comment]
Confirmed; this is a regression in 1.12; I was able to reproduce on 1.12, but not on 1.11.2

**Comment by thaJeztah** [comment]
ping @tiborvass I made this a P2, as it can be an issue for users monitoring docker through the API, but let me know if you agree

**Comment by cpuguy83** [comment]
I feel like someone fixed this. @thaJeztah Did you try on master?

**Comment by cpuguy83** [comment]
Ok, nope, just tried on master, seems broken still.

**Comment by cpuguy83** [comment]
#23908
