### ISSUE TITLE
manual datacenter docker document

### ISSUE THREAD

**Issue by vhp1360** [docker/docker#25007]
hi experts,
i'm wondering if any one provide me "manual document" to use docker image in datacenter as main machine.
i need to know some issues and for each one i should do googling for , spare long time and .... .
for example:
> how can many users ssh to it?
> how can share host machine path in docker image?
> how to set doker container NIC get ip from dhcp?
> how to run some web app like: jupyter,zeppeline,rstudio-server,.. ?
> how to go back to exited image ?
and so many issues like these , that every one faced them in real work.

thanks in advanced.

**Docker version 1.10.3, build 19b5791/1.10.3**

**Comment by cpuguy83** [comment]
docs.docker.com

In the future, please post questions to forums.docker.com.
Thanks.

**Comment by vhp1360** [comment]
many thanks,
i did know that, sorry
