### ISSUE TITLE
Docker for Mac does not respect /etc/hosts on host machine

### ISSUE THREAD

**Issue by stepanstipl** [docker/docker#25008]
Docker for Mac does not respect /ets/hosts on the host machine, I would expect this to be honoured and make Docker for Mac's behaviour more consistent with normal native linux Docker.

There's couple of workarounds how to get around this (such as logging into VM and editing /etc/hosts manually) but none very convenient.

This has been already  been mentioned in forums couple of times:
- https://forums.docker.com/t/docker-pull-ignores-etc-hosts-file/12758/2
- https://forums.docker.com/t/docker-for-mac-cannot-resolved-domain-from-etc-hosts/9823
- https://forums.docker.com/t/docker-pull-not-using-correct-dns-server-when-private-registry-on-vpn/11117

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 45
 Running: 0
 Paused: 0
 Stopped: 45
Images: 336
Server Version: 1.12.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 464
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.954 GiB
Name: moby
ID: 2QCS:4ZL3:XMG7:YT6H:HW7K:KW4E:4HOF:PBMM:B5FZ:XTVJ:PTTE:K52H
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 30
 System Time: 2016-07-23T13:33:27.152028325Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: stepanstipl
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 ---censored---:5000
 ---censored---:5000
 ---censored---:5000
 ---censored---:5000
 ---censored---:5000
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
OS: OS X El Capitan 10.11.5

**Steps to reproduce the issue:**
1. Add `1.2.3.4 docker.test` to your /etc/hosts
2. Run `docker pull docker.test/fake_image`

**Describe the results you received:**
```
Using default tag: latest
Error response from daemon: Get https://docker.test/v1/_ping: dial tcp: lookup docker.test on 192.168.65.1:53: no such host 
```

**Describe the results you expected:**
I would expect docker to resolve `docker.test` that was added to /etc/hosts as 1.2.3.4 and try to pull image from it.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by justincormack** [comment]
Hi, we are planning to add a setting for `/etc/hosts`, but I guess we could just copy it from the host instead.

**Comment by stepanstipl** [comment]
I guess both would work as long as the setting is persistent. For our use case I assume copying from host is easier - as you wouldn't have to setup hosts at two different places. And thanks.

**Comment by agusti-t** [comment]
+1

**Comment by aladagemre** [comment]
Any news on this issue? Should we expect it soon?

**Comment by sukrit007** [comment]
+1

**Comment by sukrit007** [comment]
Looks like I just got beta Version update  1.12.1-beta25 (build: 11807) update and it is resolving /etc/hosts in my mac host machine.  Thanks for adding that.

**Comment by justincormack** [comment]
Yes this should now work, so I am closing this issue. Let me know if it does not work for you. This is currently in the beta versions, but will be in the next stable release.

**Comment by DirkBrand** [comment]
I have the stable release that is past the previously mentioned build.  My version is Version 1.12.1 (build: 12133).  I am unable to do a docker login to a private registry that I am running on a hosted server.

I simply get `Error response from daemon: Get <REGISTRY>/v1/users/: dial tcp: lookup <REGISTRY> on 192.168.65.1:53: no such host`

**Comment by tobilg** [comment]
@justincormack I just installed the latest Docker for Mac beta, which reports the Docker version as 1.12.2. It's not using the `/etc/hosts` settings from Mac OS:

```
# cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

**Comment by DirkBrand** [comment]
@tobilg +1

**Comment by stepanstipl** [comment]
@justincormack macOS Sierra & Docker for Mac `1.12.2-beta28` also not working

**Comment by thaJeztah** [comment]
If you're still having issues with this, please open an issue in the Docker for Mac issue tracker https://github.com/docker/for-mac/issues, as this is specific to Docker for Mac.

I'll lock this issue here, as this issue cannot be resolved in this repository, so please report in the linked issue tracker instead
