### ISSUE TITLE
 Has `docker deploy` option been removed from 1.12.0-rc4 ?

### ISSUE THREAD

**Issue by akamalov** [docker/docker#25006]
Docker Version:

```
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        
 OS/Arch:      linux/amd64
```

OS: ```RHEL7.2```

Command:

```
[root@node236 myapp]# docker deploy
docker: 'deploy' is not a docker command.
See 'docker --help'.
[root@node236 myapp]# 
```

Question: Has ```docker deploy``` option been removed from **1.12.0-rc4** ?

**Comment by thaJeztah** [comment]
The `docker deploy` is an experimental feature, and only available in the experimental release; https://experimental.docker.com

**Comment by thaJeztah** [comment]
I'll close this issue, because it's not a bug, but feel free to continue the conversation here

**Comment by akamalov** [comment]
Thanks @thaJeztah
