### ISSUE TITLE
[1.12rc4] docker stats do not show info with NetworkDisabled=true

### ISSUE THREAD

**Issue by GuillaumeDerval** [docker/docker#25000]
**Steps to reproduce the issue:**
1. start a container with NetworkDisable=true.
2. start `docker stats`

docker run do not expose NetworkDisable in any argument; To reproduce the issue, use the API directly. I use docker-py:
```
    response = client.create_container(
                "centos",
                command="sleep 100",
                network_disabled=True,
            )
    client.start(response['Id'])
```

**Describe the results you received:**
```
CONTAINER           CPU %               MEM USAGE / LIMIT       MEM %               NET I/O             BLOCK I/O           PIDS
adec7b0de828        --                  -- / --                 --                  -- / --             -- / --             --
```
So, no real output from docker stats for this particular container

**Describe the results you expected:**
More infos ;-)

**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 28
 Running: 2
 Paused: 0
 Stopped: 26
Images: 75
Server Version: 1.12.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 128
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null overlay bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.954 GiB
Name: moby
ID: HFSP:6PBA:U5F4:5ZV7:EH7F:7OKJ:3ALL:PXGV:RWTY:F2RQ:JDCF:YTUW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 28
 Goroutines: 57
 System Time: 2016-07-25T08:38:34.478361286Z
 EventsListeners: 2
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I'm on Docker for Mac, I did not try on other OS.

**Additional information you deem important (e.g. issue happens only occasionally):**
Only tried on 1.12rc4.
When using the API endpoint (I tested with docker-py), the endpoint never returns any info.

Also, it is issue #25000.

**Comment by GuillaumeDerval** [comment]
The problem was already present with server/client 1.10.3 (tested on Fedora 24)

**Comment by thaJeztah** [comment]
Thanks for testing the release candidates, and for reporting!

**Comment by yongtang** [comment]
@GuillaumeDerval @thaJeztah The error case could also be invoked with `docker daemon -b none` and `docker run -d busybox top`. I created a PR #25905 to address this issue. Please let me know if there are any issues.
