### ISSUE TITLE
client panic on update --add-label

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#25022]
Received this panic while doing `docker service update test --label-add foo=bar` to a service that had no labels.

<details>
panic: assignment to entry in nil map

goroutine 1 [running]:
panic(0xaf9b40, 0xc820350760)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/docker/docker/api/client/service.updateLabels(0xc820082ab0, 0xc820302e58)
	/go/src/github.com/docker/docker/api/client/service/update.go:259 +0x25d
github.com/docker/docker/api/client/service.updateService(0xc820082ab0, 0xc820302e48, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/client/service/update.go:147 +0x1fe
github.com/docker/docker/api/client/service.runUpdate(0xc820082510, 0xc820082ab0, 0x7fff8f14fb21, 0x5, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/client/service/update.go:68 +0x1f9
github.com/docker/docker/api/client/service.newUpdateCommand.func1(0xc820319d40, 0xc82028f2c0, 0x1, 0x5, 0x0, 0x0)
	/go/src/github.com/docker/docker/api/client/service/update.go:30 +0x6e
github.com/spf13/cobra.(*Command).execute(0xc820319d40, 0xc82028f270, 0x5, 0x5, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/spf13/cobra/command.go:593 +0x6fe
github.com/spf13/cobra.(*Command).ExecuteC(0xc8200858c0, 0xc820319d40, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/spf13/cobra/command.go:683 +0x55c
github.com/spf13/cobra.(*Command).Execute(0xc8200858c0, 0x0, 0x0)
	/go/src/github.com/docker/docker/vendor/src/github.com/spf13/cobra/command.go:642 +0x2d
github.com/docker/docker/cli/cobraadaptor.CobraAdaptor.run(0xc8200858c0, 0xc820082510, 0x7fff8f14fb12, 0x7, 0xc82000a120, 0x6, 0x6, 0x0, 0x0)
	/go/src/github.com/docker/docker/cli/cobraadaptor/adaptor.go:120 +0x25f
github.com/docker/docker/cli/cobraadaptor.CobraAdaptor.Command.func1(0xc82000a120, 0x6, 0x6, 0x0, 0x0)
	/go/src/github.com/docker/docker/cli/cobraadaptor/adaptor.go:128 +0x8c
github.com/docker/docker/cli.(*Cli).Run(0xc82033e510, 0xc82000a110, 0x7, 0x7, 0x0, 0x0)
	/go/src/github.com/docker/docker/cli/cli.go:81 +0x34b
main.main()
	/go/src/github.com/docker/docker/cmd/docker/docker.go:72 +0x599
</details>

**Comment by thaJeztah** [comment]
ping @dnephin ptal

**Comment by cpuguy83** [comment]
I got it.

**Comment by cpuguy83** [comment]
#25023
