### ISSUE TITLE
Docker for Windows + VirtualBox

### ISSUE THREAD

**Issue by remexre** [docker/docker#25035]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 15
Server Version: 1.12.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 33
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay bridge null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953 GiB
Name: moby
ID: AEQB:GCTT:V75N:7KWG:JFW3:YV3K:G2SK:LPYJ:FBP5:64BT:QC7K:3GQQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker for Windows

**Steps to reproduce the issue:**
1. Try to run VirtualBox while Docker for Windows is running
2. Run `VBoxManage setproperty hwvirtexclusive off`
3. Try to run VirtualBox while Docker for Windows is running

**Describe the results you received:**
Whether `hwvirtexclusive` is on or off, VirtualBox fails.

**Describe the results you expected:**
[Theoretically](https://forums.virtualbox.org/viewtopic.php?f=6&t=69011&sid=d641d6e51c5cf740cadcc16307c235e8&start=15), Docker could coexist with VirtualBox? I think?

**Comment by friism** [comment]
@remexre am I missing something?

> When Hyper-V is enabled, Windows itself effectively runs as a VM, in the parent partition of the hypervisor.
> It is impossible for VirtualBox to use VT-x inside a Hyper-V partition (including parent partition).

**Comment by remexre** [comment]
Looks like I might've while skimming :stuck_out_tongue:
Is running the Linux VM in Hyper-V the only option?

**Comment by justincormack** [comment]
You might be able to run Virtualbox inside a Hyper-V VM with nested virtualisation enabled https://msdn.microsoft.com/en-us/virtualization/hyperv_on_windows/user_guide/nesting - not on the parent one, but in another VM.
