### ISSUE TITLE
`docker exec` is unable to find local file

### ISSUE THREAD

**Issue by miraage** [docker/docker#25075]
```
$ docker -v
Docker version 1.12.0-rc4, build e4a0dbc, experimental
```

Trying to execute command:
`PSQL="docker exec -ti container_name psql" bash import.sh dbname username password 127.0.0.1 /Users/username/path/to/import.csv`

Contents of script:
```sh
#!/usr/bin/env bash

PSQL=${PSQL:-psql}
DBNAME=$1
DBUSER=$2
DBPASS=$3
DBHOST=$4
CSV_FILE=$5

export PGPASSWORD=${DBPASS}

${PSQL} -h ${DBHOST} -U ${DBUSER} -d ${DBNAME} -c "\copy tablename FROM '${CSV_FILE}' DELIMITER ',' CSV HEADER;"
```

Getting error message:
`/Users/username/path/to/import.csv: No such file or directory`

How do I figure out this?

Experimented both `-i` and `-ti` flags for `docker exec`.

**Comment by justincormack** [comment]
That file is on your mac, not inside the container, so psql cannot see it. As you cannot use volumes with `docker exec` you might be able to specify the file as `-` and then pipe it in, if `psql` accepts this, or copy it into the container first.

**Comment by miraage** [comment]
Thank you.
