### ISSUE TITLE
Intermittent error with Docker for Mac (driver failed programming external connectivity)

### ISSUE THREAD

**Issue by foxx** [docker/docker#25074]
Every now and then, I get the following error;

```
$ docker run -t -i \
		-p 8080:80 \
		-v `pwd`/src/voipmonitor-gui/:/var/www/ \
		xxxx/voipmonitor:gui-stage1
docker: Error response from daemon: driver failed programming external connectivity 
on endpoint peaceful_jang (610c2781c69216bc86263af4f5b138da06f1c936e9d26f84a2746dad6539a2bc): 
iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 8080 -j DNAT 
--to-destination 172.17.0.2:80 ! -i docker0: Fatal error: exception 
Unix.Unix_error(Unix.ENOTCONN, "open", "/var/log/service-port-opener.log")
```

If ran again, sometimes it will error out with;

```
docker: Error response from daemon: Mounts denied: closed.
```

And if I wait a couple of seconds then re-run the command, the problem goes away.

Docker for Mac version is;

```
Version 1.12.0-rc4-beta20 (build: 10404)
32ce3bdb164320603f1c2d1fb2ba32a43477ef3d
```

Docker version is;

```
$ docker -v
Docker version 1.12.0-rc4, build e4a0dbc, experimental
```

OS X version is;

```
10.11.5 (15F34)
```

**Comment by dsheets** [comment]
Could you please run `Diagnose & Feedback...` from the 🐳 menu, upload your diagnostic information bundle, and post your unique diagnostic ID back here? This will send us the logs output from the Docker app and give us some more information about what may be going wrong.

Thanks!

**Comment by foxx** [comment]
Sure just did that now, ID is `D01C9DC3-18AE-47BE-AFCC-26E0F0FF2247`

**Comment by abdulwahid24** [comment]
I am also getting the same error. I have created a docker container with argument `-p 8080:80`  and got this error when I starts the container.

**Comment by dsheets** [comment]
We believe this issue has been fixed in Beta 22 and should reach stable 1.12.1 in a few weeks. There are potentially multiple causes for this kind of error so future readers are advised to open a new issue with specifics and diagnostic ID.

**Comment by dsheets** [comment]
Sorry, I got confused. This will be fixed in the upcoming Beta 23.

**Comment by dsheets** [comment]
Beta 23 has now been released which should fix this issue.

**Comment by thaJeztah** [comment]
closing because this should be fixed

**Comment by foxx** [comment]
I haven't seen this issue come up since, thanks all!

**Comment by jamshid** [comment]
If you're still seeing this (I just did on Docker for Mac 1.12.1) you might followup in https://github.com/docker/compose/issues/3277
https://forums.docker.com/t/port-mappings-are-not-released/10565

I had to "docker-compose down" to remove containers and the network and restart Docker for Mac. Use `netstat -anv` or `lsof -nP +c 15 | grep LISTEN` to see what's using a port on OSX.
