### ISSUE TITLE
swarm mode isn't routing on every host correctly... sometimes...

### ISSUE THREAD

**Issue by jhorwit2** [docker/docker#25087]
**Output of `docker version`:**

```
docker version
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 04:00:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 04:00:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.12.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 19
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null host bridge
Swarm: active
 NodeID: bsf7f2orn4lux0evqrghrc79c
 IsManager: Yes
 Managers: 3
 Nodes: 3
 CACertHash: sha256:8d1e4db0ade7dba8e12478e52683e0d18da20275a62dc5c881863b1cd6aa37e3
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.2.0-42-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 5.79 GiB
Name: c819b58b-da65-4ae6-be61-0479d8787097
ID: XFPQ:AY4G:KEM5:G6ZF:RO7F:FGY2:DDZM:DBZU:4L76:WIJF:3ZTE:37UA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

joyent sdc virtual machines (not containers)

**Steps to reproduce the issue:**
1. Create a multi-node swarm cluster (mine is 3)
2. `docker network create --driver overlay backend`
3. `docker service create --mode global --name nginx_global --publish 80:80 --network backend nginx`

**Describe the results you received:**

I see 1 nginx container running on each node in my cluster.
```
docker service tasks nginx_global
ID                         NAME          SERVICE       IMAGE  LAST STATE                DESIRED STATE  NODE
bgu0biscoqrxcdewfx5nftnf3  nginx_global  nginx_global  nginx  Preparing 28 seconds ago  Running        c819b58b-da65-4ae6-be61-0479d8787097
56n9qei3m2kc5jhk6ybgj7534  nginx_global  nginx_global  nginx  Running 28 seconds ago    Running        58029bbd-9861-45b6-acb5-57c45d27f427
eo0rsfeavu7o8z3f3k2fozymy  nginx_global  nginx_global  nginx  Preparing 28 seconds ago  Running        66ee68b6-44e4-4baa-936f-b0a07beedea9
```

Only 1 of the nodes seems to be responding and only sometimes... 
```
$ curl 10.15.2.32:80
curl: (7) Failed to connect to 10.15.2.32 port 80: Operation timed out
$ curl 10.15.2.31:80
curl: (7) Failed to connect to 10.15.2.31 port 80: Network is unreachable
$ curl 10.15.2.30:80
curl: (7) Failed to connect to 10.15.2.30 port 80: Operation timed out
$ curl 10.15.2.31:80
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

All these curls were done on my laptop right after each other. 

**Describe the results you expected:**

Port 80 should be available on every swarm node in the cluster. Each curl should work.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by jhorwit2** [comment]
Actually, this isn't only related to global. 

`docker service create --replicas 3 --name nginx --network backend --publish 85:80 nginx`

```
$ curl 10.15.2.32:85
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>



$ curl 10.15.2.31:85
curl: (7) Failed to connect to 10.15.2.31 port 85: Network is unreachable


$ curl 10.15.2.31:85
curl: (7) Failed to connect to 10.15.2.31 port 85: Network is unreachable


$ curl 10.15.2.30:85
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>```

**Comment by jhorwit2** [comment]
Hrm, so i did a reboot of the host machine and it seems to be working now. I made a little [test image](https://hub.docker.com/r/jhorwit2/swarm-test/) and I see it doing RR on each node fine.

**Comment by dperny** [comment]
I tried reproducing it but it works fine for me. Maybe also try upgrading to RC5 (that's what I'm testing on).

**Comment by jhorwit2** [comment]
@dperny would you happen to testing via curl? I just noticed that curl is working fine, but requesting the same asset via chrome/ffx always returns the same container. Even when my connection timeout is 5s and it definitely expired.

**Comment by dperny** [comment]
I was testing with curl, yeah. I'll try with a browser.

**Comment by jhorwit2** [comment]
Going to try creating fresh images on rc5. That node got into a very bad state that I couldn't debug.

**Comment by mavenugo** [comment]
@jhorwit2 upgrading from rc4 to rc5 might cause issues due to the UX changes. So a fresh rc5 cluster is prefered.

BTW, the difference in behaviour between curl & browser is documented earlier in one of the issues. It has to do with the connection caching techniques used in the browsers which will essentially pin the backend container to the browser TCP connection. While Curl never does that. Can you please confirm if the load-balancing works if you try the http connection from another browser instance ? (preferably in private/incognito mode).

**Comment by jhorwit2** [comment]
@mavenugo It's working now as expected after a fresh install & killing idle conns. Something really strange happened to one of the nodes that caused services to not publish correctly among other things.

 I'm going to close this out. If i can reproduce that other error I'll open another ticket. 

Thanks!
