### ISSUE TITLE
Splunk logging driver: JSON-formatted events

### ISSUE THREAD

**Issue by aripringle** [docker/docker#25089]
We recently switched some of our containers to use the Splunk logging driver. Our application outputs JSON events to stdout, which is getting sent to Splunk as a string (the full HEC-collected event is JSON, but the "line" property is just a string representation of the JSON output from our application).

We can make use of the splunk `spath` command to search these fields, but I feel that it would be nice to send these to the collector as a JSON object so that the individual fields are indexed.

I don't think we can do this on the Splunk/HEC side, with KV_MODE or similar, since the full record IS already being parsed as JSON. Also because of this, I'm also not sure if other formats (XML, etc) could be supported here, but please correct me if I'm wrong on either count.

Copying @outcoldman on this since I saw most of the initial commits for the Splunk logging driver coming from him.

**Comment by thaJeztah** [comment]
would this help for your use case? https://github.com/docker/docker/pull/24652

**Comment by outcoldman** [comment]
@aripringle I believe that you asked exactly what I have implemented in PR mentioned by @thaJeztah , take a look on details in here https://github.com/splunk/docker/blob/c37529249554c1bdc53c0ada525e8d662ea07098/docs/admin/logging/splunk.md#message-formats.

Right now Splunk only implements format `inline`, by using `json` you will be able to achieve what you have asked.

**Comment by aripringle** [comment]
Sorry, not sure how I missed that PR. That looks like exactly what I'm looking for. Thanks!
