### ISSUE TITLE
docker save fails on some images

### ISSUE THREAD

**Issue by gmlevin** [docker/docker#25088]
I believe I found a workaround (see below), but it may be useful to let people know about the potential problem.

**Output of `docker version`:**

Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

**Output of `docker info`:**

Containers: 21
 Running: 11
 Paused: 0
 Stopped: 10
Images: 585
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 2427
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.16.0-77-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 120
Total Memory: 251.9 GiB
Name: nash
ID: 62SP:D72E:HB6T:OZNI:YTGJ:3A6P:Q4QZ:O3HC:K4NI:V4BJ:2CSC:C5HN
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Build images
2. docker save -o x.tar mcandre/docker-fedora:zod 
Error response from daemon: unexpected EOF

**Describe the results you received:**
Error listed above and no tar file.

Error response from daemon: unexpected EOF

**Describe the results you expected:**
To get tar file that contain files in the image.

**Additional information you deem important (e.g. issue happens only occasionally):**
This worked fine in 1.9, but I upgraded to 1.11.2 and save stopped working. I ran the 1.10 migration tool. I have tried to rebuild the images, which works, but the new images cause the same error in "docker save".

Not size related. I can save images that are larger than the ones that fail.
Not number of steps in the history. I used docker history to get the number of levels and longer ones save and shorter ones do not.

Attached is a list of images and the results of trying to save them. You will see large and small ones that save, new and old ones that save, and similarly ones that fail.

generated with the command:
for i in $(docker images| cut-field.sh 3| sort -u) ; do docker images | grep $i | cut -c 50-; docker save -o /tmp/x.tar $i && ls -lh /tmp/x.tar; rm -f /tmp/x.tar; done
(cut-field.sh just returns one field from each line)
[saves.txt](https://github.com/docker/docker/files/384471/saves.txt)

Also attaching end of docker.log
[docker.log.txt](https://github.com/docker/docker/files/384467/docker.log.txt)

I can restart the daemon with additional flags, if that would help.

Also noticed:
$ docker save -o /tmp/x.tar ubuntu:trusty 
Error response from daemon: unexpected EOF

And an apparent work around
ubuntu                             16.04               42118e3df429        4 days ago          124.8 MB
SAVED
ubuntu                             xenial              71b0ccde99e8        3 weeks ago         132.7 MB
SAVED
ubuntu                             14.04               0109b6d28131        11 months ago       188.3 MB
Error response from daemon: unexpected EOF
ubuntu                             trusty              44ae5d2a191e        11 months ago       188.3 MB
Error response from daemon: unexpected EOF
ubuntu                             latest              2a274e3405ec        12 months ago       188.3 MB
Error response from daemon: unexpected EOF
glevin@nash bin (develop) $ docker pull ubuntu
Using default tag: latest
latest: Pulling from library/ubuntu
Digest: sha256:c6674c44c6439673bf56536c1a15916639c47ea04c3d6296c5df938add67b54b
Status: Downloaded newer image for ubuntu:latest
glevin@nash bin (develop) $ docker save -o /tmp/x.tar ubuntu:latest 
glevin@nash bin (develop) $ 

Looks like pulling a new copy of the base image from the repository and rebuilding our image is sufficient to clean things up. If Dockerfile is based on the registry, rather than a local image, then rebuilding will pull the renumbered image.

**Comment by thaJeztah** [comment]
This sounds like some images were corrupted (which can be if docker ran out of disk space at some point); did the migration show errors?

**Comment by gmlevin** [comment]
There is lots of disk space and no reported errors on conversion. In any case, reconstructing the image from the docker file solves the problem. And of course, once fixed, no way to reproduce it. It did seem to relate to specific base images. In any case, if no one else is seeing the problem, this can be closed.

**Comment by thaJeztah** [comment]
I don't think we had other reports of this issue, so it may have just been a one-off issue. I'll close this issue, as we don't have a way to reproduce now, but please comment if you see this again

Thanks for reporting, it's appreciated!

**Comment by samginshen** [comment]
I met this again. If I change /etc/defaule/docker add " -g /disk1/docker", and restart docker service. The docker can not running. 
Output of  /var/log/upstart/docker.log:
`time="2017-03-15T03:45:10.421764709Z" level=info msg="previous instance of containerd still alive (120037)" 
time="2017-03-15T03:45:10.468047349Z" level=error msg="[graphdriver] prior storage driver \"aufs\" failed: invalid argument" 
time="2017-03-15T03:45:10.468141850Z" level=fatal msg="Error starting daemon: error initializing graphdriver: invalid argument" 
/var/run/docker.sock is up
`
Output of docker info:

Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 116
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host overlay bridge
Kernel Version: 3.16.0-77-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 36
Total Memory: 58.97 GiB
Name: ip-10-32-3-45
ID: V2VD:Q2MM:VV55:6HAV:R4JJ:R3EH:WTGU:RVA2:XZJH:ZDCH:3DIA:HT4H
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Cluster store: etcd://10.32.3.42:2379,10.32.3.43:2379,10.32.3.45:2379
Cluster advertise: 10.32.3.45:4243
