### ISSUE TITLE
Docker does not start - Unit docker.socket failed to load

### ISSUE THREAD

**Issue by averri** [docker/docker#25098]
Uninstalled Docker using:

```
yum remove docker-engine.x86_64 docker-engine-selinux.noarch
```
Installed again using:

```
curl -fsSL https://get.docker.com/ | sh
chkconfig docker on
service docker start
```

The result of last command is:

```
Redirecting to /bin/systemctl start  docker.service
Failed to start docker.service: Unit docker.socket failed to load: No such file or directory.
```

Running on CentOS 7.1.

**Comment by kylejw1** [comment]
I was able to get around this issue temporarily by copying /usr/lib/systemd/system/docker.socket from a different vm which was still running rc4.

**Comment by sempr** [comment]
@kylejw1 I did the same thing and it works.

**Comment by jalmansor** [comment]
I'm assuming the build process is similar for Fedora, since it's also missing in the package for 24.

**Comment by thaJeztah** [comment]
This should be fixed on master, and will be included in 1.12-GA; to fix this issue, change the docker unit file as is done in this PR: https://github.com/docker/docker/pull/25094

**Comment by crosbymichael** [comment]
Yes, this was fixed via #25094.  Thanks for the report.

**Comment by adrianovieira** [comment]
For me this heppened after updating from RC4 to RC5. Even after I commented/removed like on PR: #25094.

It was necessary to do like #issuecomment-235450116, and it works.

**Comment by crosbymichael** [comment]
@adrianovieira did you run `systemctl daemon-reload` after changing the file?

**Comment by adrianovieira** [comment]
yes!

**Comment by adrianovieira** [comment]
A sample what I did:

```
# cp /usr/lib/systemd/system/docker.socket /root
# yum -y upgrade
Jul 27 13:33:20 Updated: docker-engine-selinux-1.12.0-0.5.rc5.el7.centos.noarch
Jul 27 13:33:23 Updated: docker-engine-1.12.0-0.5.rc5.el7.centos.x86_64
# systemctl daemon-reload
# systemctl start docker
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
# vi /usr/lib/systemd/system/docker.service (remove Requires)
# systemctl daemon-reload
# systemctl start docker
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
# cp /root/docker.socket /usr/lib/systemd/system/
# systemctl daemon-reload
# systemctl start docker
# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
...

```

**Comment by adrianovieira** [comment]
Actually I only "comment" that line. Now I removed it and everything is ok.

**Comment by crosbymichael** [comment]
@adrianovieira nice, thanks for double checking

**Comment by adrianovieira** [comment]
ok!

may be the update process could fix that.. instead of removing by hand. What do you think?

e.g.: `sed -i -e 's/Requires=docker.socket//g' /usr/lib/systemd/system/docker.service`

**Comment by thaJeztah** [comment]
@adrianovieira if the file has not been modified, update should replace it automatically

**Comment by theonlydoo** [comment]
I've got the same issue after this morning's release

**Comment by thaJeztah** [comment]
@theonlydoo was this on a fresh install or an upgrade? If it was an upgrade did you have any modifications made to your docker systemd unit file? (causing the installer to skip updating that file)

**Comment by theonlydoo** [comment]
@thaJeztah First it was an upgrade, with a systemd unit file edited to enable the `-s overlay` flag, but I suspected that my modification had somehow fucked the upgrade so I deleted everything, systemd unit file, `/var/lib/docker/` path. Afterwards I tried the method chown before https://github.com/docker/docker/issues/25098#issuecomment-236129598 and it wasn't successful either.

**Comment by crosbymichael** [comment]
@theonlydoo is your system still messed up?  Could you run something like `journalctl -xe` and see if anything related comes up in the logs?  Thanks

**Comment by shawnwhit** [comment]
I just updated from rc4 to rc5 and got the same issue. I am running Centos7

**Comment by thaJeztah** [comment]
@shawnwhit the "socket failed to load" is resolved in 1.12.0, we're looking into the SELinux issue; appears to be an update in SELinux upstream that causes issues

**Comment by asmialoski** [comment]
I just updated from rc4 to rc5 and got the same issue. I am running RHEL7.
Workaround: I have copied /usr/lib/systemd/system/docker.socket from another machine with RC4 and it´s work.

**Comment by thaJeztah** [comment]
@asmialoski see https://github.com/docker/docker/issues/25098#issuecomment-235627700, also 1.12.0 has been released and contains various bug fixes since RC5

**Comment by lcamilo15** [comment]
I commented out the part that doesn't work /etc/systemd/system/docker.service 
weird thing, it worked.

```bash
[Unit]
Description=Docker Application Container Engine
#After=network.target docker.socket
#Requires=docker.socket

**Comment by michelvocks** [comment]
Had also today the same issue after upgrading from 1.10.2 to 1.12 on Redhat. Solution from @lcamilo15 fixed the issue.

**Comment by theonlydoo** [comment]
Upgrade to the latest this morning, the package still doesnt provides the [socket](https://github.com/docker/docker/issues/25098#issuecomment-236477805) that @lcamilo15 mentioned and docker still wont start.

**Comment by vdemeester** [comment]
@theonlydoo the socket is no more provided in the docker package (1.12 and later) – it should look like this : https://github.com/docker/docker/blob/master/contrib/init/systemd/docker.service.rpm.

You can look at https://github.com/docker/docker/pull/24804 for reason what it was removed.

> However, there is another motivation for removing socket activation from
docker's systemd files and that is because when you have daemons running
with --restart always whenever you have a host reboot those daemons
will not be started again because the docker daemon is not started by
systemd until a request comes into the docker API.

The immediate workaround should be to remove the `Requires=docker.socket` line in the `docker.service` file if it's still there 👼.

**Comment by theonlydoo** [comment]
@vdemeester so there is no planned "migration" handle on package upgrade for this ?

**Comment by vdemeester** [comment]
@theonlydoo I'm not sure how fedora/rpm-based distribution handle updates of these files (invoking @runcom here). I thought it would have update/overwrite the `docker.service` file as it's done on Archlinux for example, but I guess not.

**Comment by theonlydoo** [comment]
```
# systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/etc/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since lun. 2016-08-01 10:24:32 CEST; 12s ago
     Docs: https://docs.docker.com
  Process: 18984 ExecStart=/usr/bin/docker daemon -H fd:// -s overlay (code=exited, status=1/FAILURE)
 Main PID: 18984 (code=exited, status=1/FAILURE)

août 01 10:24:32 meow systemd[1]: Starting Docker Application Container Engine...
août 01 10:24:32 meow docker[18984]: time="2016-08-01T10:24:32.838119437+02:00" level=fatal msg="no sockets found via socket activation: make sure the service was started by systemd"
août 01 10:24:32 meow systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
août 01 10:24:32 meow systemd[1]: Failed to start Docker Application Container Engine.
août 01 10:24:32 meow systemd[1]: docker.service: Unit entered failed state.
août 01 10:24:32 meow systemd[1]: docker.service: Failed with result 'exit-code'.
```
here is what I got when I restart the docker w/o the `Requires` line and ofc I removed `docker.socket` from the `After` line too. Here is my systemd service file : 

```
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target

[Service]
Type=notify
# the default is not to use systemd for cgroups because the delegate issues still
# exists and systemd currently does not support the cgroup feature set required
# for containers run by docker
ExecStart=/usr/bin/docker daemon -H fd:// -s overlay
MountFlags=slave
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity
TimeoutStartSec=0
# set delegate yes so that systemd does not reset the cgroups of docker containers
Delegate=yes

[Install]
WantedBy=multi-user.target
```

**Comment by theonlydoo** [comment]
The solution that I found that was to renounce to upgrade and install from scratch. I did a clean swipe of all docker dependencies on my system and reinstalled from docker's repositories to finally see my docker work again.

**Comment by thaJeztah** [comment]
@theonlydoo looks like you had a modified `docker.unit` file (the `-s overlay` was added), and therefore yum/dnf didn't replace it with the new version; the `ExecStart` should look like

    ExecStart=/usr/bin/dockerd daemon

To set a custom graphdriver, either use an `/etc/docker/daemon.json` configuration file (https://docs.docker.com/engine/reference/commandline/dockerd/#/daemon-configuration-file), or a systemd drop in file (https://docs.docker.com/engine/admin/systemd/#/custom-docker-daemon-options).

**Comment by crosbymichael** [comment]
Yes, the files are only replaced if you have not modified the original ones.  We try our best to do the right thing; if you made changes we will not overwrite them but you also won't get the changes.

**Comment by rcsavage** [comment]
Just experienced the same issue with 1.12 in CentOS 7.   Funny, I can use my existing /usr/lib/systemd/system/docker.service IF I do the following

# rpm -e docker-engine
# rpm -e docker-engine-selinux
# yum -y install docker-engine

The problem is when I take a stock CentOS 7 system, and then do yum -y install docker-engine, I run into the problem.   Why does removing and re-adding the same package solve the problem?   To me, this sounds a bit like configuration issue with the new 1.12 RPM configuration.

**Comment by abdeleon** [comment]
Fyi, I just used the old versions after running into the issues noted above.
yum install docker-engine-selinux-1.11.2-1.el7.centos.noarch

**Comment by Illydth** [comment]
Running into a (Potentially?) related issue.

Installing 1.12 over the top of 1.11.2 on RHEL7 (up to date) leads to the docker engine being unable to start.

Removing "-H fd://" from the run line does tend to fix the issue.  Sounds like there's a break in the Require/After config between 1.11 and 1.12?

I'll see about rolling out all related docker files and doing a clean install from yum.

NOTE: I don't THINK i've modified the systemd service file, but I'll check that also.

**Comment by Illydth** [comment]
Update:  So the base docker systemd files work just fine, however when I drop the following systemd drop in file in place I get:

```
[root@test docker.service.d]# docker ps
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

The Systemd drop in file (As per documentation here: https://docs.docker.com/engine/admin/systemd/) looks like the following:

```
[root@stldbldtst01 docker.service.d]# cat `pwd`
cat: /etc/systemd/system/docker.service.d: Is a directory
[root@stldbldtst01 docker.service.d]# cat ./docker-service.conf
[Service]
EnvironmentFile=-/etc/sysconfig/docker
EnvironmentFile=-/etc/sysconfig/docker-storage
EnvironmentFile=-/etc/sysconfig/docker-network
ExecStart=
ExecStart=/usr/bin/docker daemon $OPTIONS \
	$DOCKER_STORAGE_OPTIONS \
	$DOCKER_NETWORK_OPTIONS \
	$BLOCK_REGISTRY \
	$INSECURE_REGISTRY
```

Had to remove the "-H fd://" from the documented drop in file option or I'd get the daemon fail to start again.

Help?  What's wrong with the systemd drop in file that's causing the system not to be accessible from "docker ps" at the command line?

The docker environment files referenced are as follows:

/etc/sysconfig/docker:
`OPTIONS="-g /docker"`
/etc/sysconfig/docker-storage
`DOCKER_STORAGE_OPTIONS="-s btrfs"`
/etc/sysconfig/docker-network
`DOCKER_NETWORK_OPTIONS="-H tcp://0.0.0.0:2375 -H unix:///docker/docker.sock"`

The final command line for dockerd comes out as follows:
`dockerd -g /docker -s btrfs -H tcp://0.0.0.0:2375 -H unix:///docker/docker.sock`

(NOTE: Yes I am aware this is a totally open / unsecured installation, no i'm not planning on going to production with this, yes this is on an isolated sandbox.)

I've tracked the problem down to the Networking Options...is there something about 1.12's ability to use -H tcp://0.0.0.0:2375 -H unix:///docker/docker.sock?

**Comment by vdemeester** [comment]
@Illydth by default, the client look on unix socket in `/var/run/docker.sock`, that's why with `-H unix:///docker/docker.sock` it won't work without setting `DOCKER_HOST`. If you use `-H unix:///var/run/docker.sock` it will work fine.

The *breaking* change here is that using `fd://` doesn't work anymore if `Requires=docker.socket` (which is now by default). I think we should update the documentation to reflect that. @crosbymichael @thaJeztah wdyt ?

**Comment by thaJeztah** [comment]
@vdemeester the problem there is that we only removed socket activation for RPM based platforms (because it caused problems there), but not for other platforms

**Comment by dailyherold** [comment]
Added a Redhat/Centos specific comment to https://github.com/docker/docker/issues/22847#issuecomment-236759691 so jumping over to this issue. If there is a need for documentation updates, I'd be glad to assist.

**Comment by EtienneK** [comment]
Getting this issue after trying to install docker on Centos 7 using docker-machine generic driver.

**Comment by thaJeztah** [comment]
@EtienneK looks like there's an open issue for that; https://github.com/docker/machine/issues/3632

**Comment by alfredcs** [comment]
Try to create /usr/lib/systemd/system/docker.socket if missing and/or rm /var/lib/docker as well as /var/run/docker.

**Comment by Illydth** [comment]
Top google hit on "docker systemd" gets you this page:

https://docs.docker.com/engine/admin/systemd/

Which explicitly states in it's documentation to put "-H fd://" into your systemd drop in file. This is why so man RHEL users broke with the 1.12 install:  Docker's own Docks state to put that in the file which was subsequently removed.  To further compound the issue, because the file exists, it will NOT get overwritten/removed in the upgrade...meaning anyone who's followed those instructions in the past will have a broken docker after yum upgrade...

Big old warnings about "fd://" being removed for RHEL/RPM distributions should be ALL OVER that page.

Finding the documentation that this feature was removed was practically impossible as well.

**Comment by dwiest** [comment]
Why is this issue marked as closed?  dockerrepo is still serving up broken RPMs:

$ yum list installed | grep docker-engine
docker-engine.x86_64                 1.12.0-1.el7.centos         @dockerrepo
docker-engine-selinux.noarch         1.12.0-1.el7.centos         @dockerrepo    

$ sudo systemctl start docker.service
Failed to start docker.service: Unit docker.socket failed to load: No such file or directory.

Yes, I can fix this myself, but so can Docker.  Why continue to serve up a known-bad RPM?

**Comment by hholst80** [comment]
This is *still* an issue. Why is this bug closed?

**Comment by SydOps** [comment]
yes, I saw this issue today in centos 7

```
# yum list |grep docker-engine
docker-engine.x86_64                    1.12.1-1.el7.centos            @docker-main-repo
docker-engine-selinux.noarch            1.12.1-1.el7.centos            @docker-main-repo
docker-engine-debuginfo.x86_64          1.12.1-1.el7.centos            docker-main-repo
```

seems `/usr/lib/systemd/system/docker.socket` is missed within installation. 
```
# grep -r socket /etc/systemd/system/docker.service
After=network.target docker.socket
Requires=docker.socket
```

After manually create the `docker.socket` file, the problem is fixed. 

(you can save it to `/etc/systemd/system` or `/usr/lib/systemd/system`)

```
# cat docker.socket
[Unit]
Description=Docker Socket for the API
PartOf=docker.service

[Socket]
ListenStream=/var/run/docker.sock
SocketMode=0660
SocketUser=root
SocketGroup=docker

[Install]
WantedBy=sockets.target
# systemctl unmask docker.service
# systemctl unmask docker.socket
# service docker restart
```

**Comment by originsmike** [comment]
I just saw this on a fresh and fully updated CentOS 7 image while trying to `docker-machine create -d generic` on it.  @lcamilo15's solution worked, and it seems to be playing nicely with docker-machine.

```
$ yum list installed | grep docker
docker-engine.x86_64                 1.12.1-1.el7.centos            @docker-main-repo
docker-engine-selinux.noarch         1.12.1-1.el7.centos            @docker-main-repo
```

**Comment by psakar** [comment]
@lcamilo15 solution works for FC 22

`wget https://raw.githubusercontent.com/docker/docker/master/contrib/init/systemd/docker.socket -O /usr/lib/systemd/system/docker.socket`
`systemctl daemon-reload`
`systemctl start docker.socket`
`systemctl start docker`

**Comment by dongalex** [comment]
Hi,
If the docker daemon is booted by -H fd://, I can't use docker -H fd:// version to get the version information, can anybody tell me how to access docker daemon in this case? I'm not familiar with "fd://"

Thanks a lot

**Comment by thaJeztah** [comment]
@dongalex if it's on the same host, simply `docker version`, or `sudo docker version` should work

**Comment by dongalex** [comment]
@thaJeztah , yes, i tried, it works ,thank you!

**Comment by sajfarahani** [comment]
This is still an issue?
I installed Docker 1.12 and changed the service file to have docker listen on port 2375:

```
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target docker.socket
Requires=docker.socket

[Service]
Type=notify
#ExecStart=/usr/bin/docker daemon -H fd://
Environment="DOCKER_OPTS=-H tcp://0.0.0.0:2375 --exec-opt native.cgroupdriver=cgroupfs"
ExecStart=/usr/bin/docker daemon -H fd://  \$DOCKER_OPTS
MountFlags=slave
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity

[Install]
WantedBy=multi-user.target
```

And added the docker.socket as well:

```
[Unit]
Description=Docker Socket for the API
PartOf=docker.service

[Socket]
ListenStream=/var/run/docker.sock
SocketMode=0660
SocketUser=root
SocketGroup=docker

[Install]
WantedBy=sockets.target
```

However, it still does not allow me to start docker. Is there anyway to fix this?

**Comment by thaJeztah** [comment]
@sajfarahani it's only an issue if you made modifications to the unit file, or used drop-in files that use `-H fd://`, and are running on a system that uses RPM's for installation (CentOS, Fedora, RHEL, Oracle Linux). Please see the "**IMPORTANT**" message at the top of the release notes; https://github.com/docker/docker/releases/tag/v1.12.5

Some things worth mentioning based on the info you provided

- Please be aware that configuring the daemon to listen on `0.0.0.0:2375` makes the remote API accessible by _anyone_ that can reach port 2375 of your docker host (which could be "the internet"). **Anyone that has access to the remove API, effectively has root access on your machine**. See [docker daemon attack surface](https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface). When exposing the API, always make sure to properly protect it; [Protect the docker daemon socket](https://docs.docker.com/engine/security/https/).
- You should _never_ modify the main systemd unit file directly. Doing so prevents updates to the unit-file to be installed. If you need to customise settings in the unit file, always use an override ("drop in") file, as described in ["Custom Docker daemon options"](https://docs.docker.com/engine/admin/systemd/#/custom-docker-daemon-options)
- For most configuration changes, it's easier to use a `daemon.json` daemon configuration file; the daemon configuration file does not depend on what init system you use (systemd, sysvinit, upstart), and allows you to reload certain settings without restarting the daemon. See [daemon configuration file](https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file) in the documentation.

**Comment by subodhp** [comment]
Just for the record, I was facing the same problem & it was fixed by just touching the file /usr/lib/systemd/system/docker.socket under RHEL7.3. Weird! 

Thanks,
Subodh
thesubodh.com

**Comment by thaJeztah** [comment]
@subodhp systemd socket activation for RPM based installs has been removed since docker 1.12 (see https://github.com/moby/moby/releases/tag/v1.12.6), so if the unit file is expecting that, it's possible you either have changes in your unit file, or there's a drop-in file overriding the default config; read the instructions at the top of the release notes, which may help; https://github.com/moby/moby/releases/tag/v1.12.6

**Comment by subodhp** [comment]
@thaJeztah Thanks, that provided the explanation for the behavior, I was able to reproduce the issue and rectify via the procedure.

Thanks,
Subodh Pachghare
thesubodh.com

**Comment by liutian1937** [comment]
mark

**Comment by Oyunbold** [comment]
systemctl start docker.socket
Job for docker.socket failed. See "systemctl status docker.socket" and "journalctl -xe" for details.

**Comment by ndpackersandmovers** [comment]
just reboot the system through terminal
