### ISSUE TITLE
[1.12.0-rc] some weird deadlocks

### ISSUE THREAD

**Issue by tiborvass** [docker/docker#25100]
https://jenkins.dockerproject.org/job/Docker%20Master/label=ubuntu%20&&%20btrfs/6275/console
https://jenkins.dockerproject.org/job/Docker%20Master/label=fedora%20&&%20devicemapper/6275/console
https://jenkins.dockerproject.org/job/Docker%20Master/label=fedora%20&&%20devicemapper/6274/console

**Comment by vdemeester** [comment]
@tiborvass this is kinda related to #25028 too

**Comment by dnephin** [comment]
Ya, closing as duplicate of #25028
