### ISSUE TITLE
[1.12.0-rc] Swarm tests indicate potential races

### ISSUE THREAD

**Issue by tiborvass** [docker/docker#25101]
On https://jenkins.dockerproject.org/job/Docker%20Master%20(arm)/2597/console
TestApiSwarmManagerRestore
TestApiSwarmRaftQuorum
TestApiSwarmRestartCluster

On https://jenkins.dockerproject.org/job/Docker%20Master/label=centos%20&&%20devicemapper/6275/console
TestApiSwarmRestartCluster

And they are pretty consistent

**Comment by cpuguy83** [comment]
#25077 fixes TestApiSwarmRestartCluster.

**Comment by aaronlehmann** [comment]
Has anyone seen `TestApiSwarmServicesCreateGlobal` fail? I discovered a race that would cause that to fail if triggered: https://github.com/docker/swarmkit/issues/1291

**Comment by tonistiigi** [comment]
Closing this. Arm CI has been very stable for couple of last weeks.
