### ISSUE TITLE
Nano and Midnight Commander don't work properly on Docker for Windows beta

### ISSUE THREAD

**Issue by fastmuse** [docker/docker#25113]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Output of `docker version`:**

```
Client:                                 
 Version:      1.12.0-rc4               
 API version:  1.24                     
 Go version:   go1.6.2                  
 Git commit:   e4a0dbc                  
 Built:        Wed Jul 13 03:28:51 2016 
 OS/Arch:      windows/amd64            
 Experimental: true                     
                                        
Server:                                 
 Version:      1.12.0-rc4               
 API version:  1.24                     
 Go version:   go1.6.2                  
 Git commit:   e4a0dbc                  
 Built:        Wed Jul 13 03:28:51 2016 
 OS/Arch:      linux/amd64              
 Experimental: true                     
```

**Output of `docker info`:**

```
Containers: 35
 Running: 0
 Paused: 0
 Stopped: 35
Images: 6
Server Version: 1.12.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 91
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 991.1 MiB
Name: moby
ID: SDJH:HJ44:NFEB:HQ4E:TBOI:JXRI:3IDX:B4MT:R57R:25HK:TMK3:7WYB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Local machine Windows 10 PRO Version 1511 (OS Build 10586.494)

**Steps to reproduce the issue:**
1. run some distro 
2. install nano or mc

**Describe the results you received:**
http://take.ms/oU6j3
With nano strange next line moving
With mc encoding and arrow keys problems

**Additional information you deem important (e.g. issue happens only occasionally):**
I tried cmder, git-bash, powershell, cmd and everywhere the problem exists. Also, I tried to connect to a remote server to compare and it was ok. I'm not the only one https://stackoverflow.com/questions/38555071/nano-and-midnight-commander-dont-work-on-docker-for-windows-beta/38567570

**Comment by rneugeba** [comment]
Thanks for the report.

This is more an issue with the lack of terminal emulation in the various Windows shells. I was able to reproduce the issue on standard Windows 10 pro 1511 (build 10586) but it works fine on a recent insider build with Powershell (I tested with build 14367).

Microsoft will soon release RS1 which should have the improved terminal emulation available.

**Comment by justincormack** [comment]
Closing as it is an upstream Windows issue, but feel free to continue discussing here as I am sure that other people will run into this.

**Comment by fastmuse** [comment]
I'm sorry, maybe it's a dumb question but why it works with no docker environment? I mean for example with a remote server using the same terminals.
