### ISSUE TITLE
1.12 rc_5 problem connecting node to swarm

### ISSUE THREAD

**Issue by gurtagel** [docker/docker#25112]
**Output of `docker version`:**

```
(paste your output here)
```
Client:
 Version:      1.12.0-rc5
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   a3f2063
 Built:        Tue Jul 26 13:32:56 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc5
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   a3f2063
 Built:        Tue Jul 26 13:32:56 2016
 OS/Arch:      linux/amd64

**Output of `docker info`:**

```
(paste your output here)
```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 1.12.0-rc5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 7
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null overlay host
Swarm: pending
 NodeID: 8sbrs80mlcv77ycs84nmhnojn
 Error: rpc error: code = 2 desc = raft: no elected cluster leader
 Is Manager: true
 Managers: 0
 Nodes: 0
 Node Address: 171.71.27.157
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.16.0-77-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.781 GiB
Name: cisco-h8-1020
ID: QY5G:HS4B:7QA5:GZHF:EBKW:QYSY:Q72X:M4RK:WDV3:GZXS:UP3W:UCYF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical box. Total cluster for now is 3 physical boxes

**Steps to reproduce the issue:**
1. Get swarm 1.12 rc_5 on all 3 boxes
2. Init swarm on one box (leader)
3. Use command generated by this to add nodes 2, 3 to swarm. Box 2 works perfectly fine, but not box 3

**Describe the results you received:**
After doing a docker node ls I get the following

7p111jefh2fqloeifycx7xsdf                                                  Unknown     Active        
ao0ttbqkaats7erurf3ck0e4a *      cisco-router-1               Ready         Active        Leader
ctnpjt52jbc480s0f2mn0p3q3       cisco-machine-3         Ready         Active

As you can see, 7p111... is not getting added to the swarm, its status is "Unknown" unlike the other 2 which show status as ready. This is also confirmed by the fact that when doing a job with a replication of 15 not a single one goes to this box. If it means anything, running the command to join the swarm took very long to process; I get "Error response from daemon: Timeout was reached before node was joined. Attempt to join the cluster will continue in the background. Use "docker info" command to see the current swarm status of your node." When I do a docker node ls immediately after running the join for that box it does not appear, but shortly after this message appears I get that it does in fact join the swarm but with an unknown status, and no jobs get pushed to it. This confuses me, as I am almost certain it is not an internet issue (I am hardwired in and downloads happen very quickly). I am a newbie to docker, so any help would be appreciated!

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
I followed all of the isntructions carefully on the swarm installation guide

**Comment by thaJeztah** [comment]
Thanks for reporting; initial thought would be something network related indeed, but perhaps @mavenugo or @aaronlehmann would have suggestions for debugging

**Comment by BradleyA** [comment]
Had same incident with Version: 1.12.0-rc5 after upgrade.  
It seems that after the upgrade some information about the previous swarm Version: 1.12.0-rc4 manager on this host was in a configuration file.  I did not shut down the swarm manager on this host before the upgrade and it was the swarm leader.  (that was my bad) I was unable to force the swarm manager to leave after the upgrade.

$docker swarm leave --force
Error response from daemon: context deadline exceeded

$ docker info | grep -A 5 -i swarm 
WARNING: No swap limit support
Swarm: pending
 NodeID: emj26rtr8gcndtecp4798ab4v
 Error: rpc error: code = 4 desc = context deadline exceeded
 Is Manager: true
 Managers: 0
 Nodes: 0

What worked to clear the incident on my group of systems:

$ sudo service docker stop
$ reboot
$ docker swarm leave --force
Node left the swarm.
$ docker info | grep -A 5 -i swarm 
WARNING: No swap limit support
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.19.0-65-generic
Operating System: Ubuntu 14.04.4 LTS

**Comment by gurtagel** [comment]
I had tried to basically wipe my system of all docker content and try a fresh install for all systems. When my system was working correctly I had 1 manager node physical box and another box which I was using for the slave. Behavior was normal as this was on 1.12 rc_4. The problem came when I wanted to add another fresh machine to the cluster. As I got docker for the third machine yesterday it installed 1.12 rc_5 on it. I at first tried to simply add it to the cluster using the command that gets generated by the manager when doing a swarm init, but it was not being recognized. I then tried doing an init on the new machine itself and did notice that the format of the token was in fact different from the one generated by rc_4 so I figured maybe rc_4 and rc_5 are not compatible with each other, so I uninstalled all traces of docker on the first 2 machines and reinstalled using rc_5, and this is when I first noticed that machine 3 was not being added correctly to the cluster. In addition, I have ensured that the 3 tcp ports and 2 udp ports are open for listening on all 3 machines, so I do not believe that is the problem either.

**Comment by aaronlehmann** [comment]
> If it means anything, running the command to join the swarm took very long to process; I get "Error response from daemon: Timeout was reached before node was joined. Attempt to join the cluster will continue in the background. Use "docker info" command to see the current swarm status of your node."

One of the things that can cause this is clock skew that makes the one TLS certificate not yet valid on another machine. This is what happened in #24078. Currently, the TLS error does not get displayed properly. We're working on a fix for that. We are also planning to add additional backdating to the TLS certificates in Docker 1.12.1 to mitigate this.

So, please check if the clocks on your machines are synchronized. Hopefully synchronizing them will solve the problem.

**Comment by thaJeztah** [comment]
@aaronlehmann should we make the current clock/time of nodes available through the API, so that this can be seen in (e.g. `docker node ls` / `docker node inspect`)?

**Comment by aaronlehmann** [comment]
No, I think it's better to fix `docker swarm join` so it shows the TLS error if it encounters one.

**Comment by gurtagel** [comment]
Thanks guys that fixed everything!
