### ISSUE TITLE
make deb on ARM is broken in 1.12.0-rc5

### ISSUE THREAD

**Issue by StefanScherer** [docker/docker#25124]
With docker 1.12.0-rc5 running a `make deb` on ARM is broken as it tries to pull and run the `golang:1.6.3-alpine` image for amd64 generating the manpages.

**Output of `docker version`:**

```
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.4.3
 Git commit:   590d5108
 Built:        Thu Feb  4 21:04:51 2016
 OS/Arch:      linux/arm

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.4.3
 Git commit:   590d5108
 Built:        Thu Feb  4 21:04:51 2016
 OS/Arch:      linux/arm
```

**Output of `docker info`:**

```
Containers: 22
 Running: 1
 Paused: 0
 Stopped: 21
Images: 363
Server Version: 1.10.0
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.5.2-std-2
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: armv7l
CPUs: 4
Total Memory: 1.975 GiB
Name: jenkins-slave01
ID: DFJ3:7BSF:SOGE:A5CN:HZT3:3Y35:UITQ:EEH7:YDHI:FFLX:RUXV:EBUA
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Labels:
 provider=scaleway
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Scaleway C1 with Docker preinstalled

**Steps to reproduce the issue:**
1. Use eg. a Scaleway C1 ARM machine
2. git clone https://github.com/docker/docker
3. cd docker
4. make deb

**Describe the results you received:**

```
---> Making bundle: dynbinary (in bundles/1.12.0-rc5/dynbinary)
Building: bundles/1.12.0-rc5/dynbinary-client/docker-1.12.0-rc5
Created binary: bundles/1.12.0-rc5/dynbinary-client/docker-1.12.0-rc5
Building: bundles/1.12.0-rc5/dynbinary-daemon/dockerd-1.12.0-rc5
Created binary: bundles/1.12.0-rc5/dynbinary-daemon/dockerd-1.12.0-rc5
Building: bundles/1.12.0-rc5/dynbinary-daemon/docker-proxy-1.12.0-rc5
Created binary: bundles/1.12.0-rc5/dynbinary-daemon/docker-proxy-1.12.0-rc5

---> Making bundle: build-deb (in bundles/1.12.0-rc5/build-deb)
---> Making bundle: .integration-daemon-start (in bundles/1.12.0-rc5/build-deb)
INFO: Waiting for daemon to start...
+++ exec dockerd --debug --host unix:///go/src/github.com/docker/docker/bundles/1.12.0-rc5/build-deb/docker.sock --storage-driver overlay --pidfile bundles/1.12.0-rc5/build-deb/docker.pid --userland-proxy=true
.
---> Making bundle: .detect-daemon-osarch (in bundles/1.12.0-rc5/build-deb)
docker build -t docker-manpage-dev -f man/Dockerfile .
Sending build context to Docker daemon 557.1 kB
...
Sending build context to Docker daemon 157.5 MB

Step 1 : FROM golang:1.6.3-alpine
1.6.3-alpine: Pulling from library/golang
e110a4a17941: Pulling fs layer
...
25994cc11974: Pull complete
Digest: sha256:8b9e1e4a137e7663c1dc52a33c41699661ea4da9aca6ab0771b1fcec16a87535
Status: Downloaded newer image for golang:1.6.3-alpine
 ---> 6b317e0ae72c
Step 2 : RUN apk add -U git bash curl gcc musl-dev
 ---> Running in 23bd447afd78
standard_init_linux.go:175: exec user process caused "exec format error"
The command '/bin/sh -c apk add -U git bash curl gcc musl-dev' returned a non-zero code: 1
Makefile:119: recipe for target 'manpages' failed
make: *** [manpages] Error 1
---> Making bundle: .integration-daemon-stop (in bundles/1.12.0-rc5/build-deb)
+++++ cat bundles/1.12.0-rc5/build-deb/docker.pid
++++ kill 5433
Makefile:86: recipe for target 'deb' failed
make: *** [deb] Error 1
```

**Describe the results you expected:**

Building the ARM deb's should work without a problem :-)

I had a look at [man/Dockerfile](https://github.com/docker/docker/blob/master/man/Dockerfile) to see if we can add eg. a arch specific `man/Dockerfile.armhf` but found out that glide does not provide a precompiled ARM binary. So there is some more work to make it work.

Another idea is to generate the man pages and check them into GitHub with a `[ci skip]` commit message.

**Comment by thaJeztah** [comment]
ping @dnephin @tiborvass ^^

**Comment by dnephin** [comment]
Ya, we could generate the man pages first, instead of doing it as part of the `build-deb` script. I don't like the idea of checking it into git though.

**Comment by StefanScherer** [comment]
I understand. Building man pages must be done on the ARM machine as it is a separate Jenkins slave  building the deb's for ARM.

Just some other ideas. Adding the go tools/libs needed to build the man pages into the vendor folder of docker itself? Just like the dev-dependencies in Node.js projects to build the app/man/package. So there is no need to build the manpage inside another docker container. I assume we are running `make deb` in CI and are already running in a container, so everything should be there to build the manpages.

Or adding the golang:1.6.3-alpine to the frozen images that have to be pulled before the docker-daemon. There we have a chance to pull different images for each architecture. But it feels complicated to solve this small build step.

Maybe there is a much simpler solution.

**Comment by dnephin** [comment]
I can compile glide for arm and put it on bintray. Then if we create a Dockerfile.armhf it should work ?

**Comment by StefanScherer** [comment]
Probably it should work. We should use an more or less official base image in the FROM line. There is no golang/alpine combination, but armhf/golang (7 months old) could be a first starting point.

**Comment by dnephin** [comment]
I would rather use just `alpine:3.4` and `apk add -U go`, I'll see if that works.

**Comment by dnephin** [comment]
#25192 seems to be working for me on scaleway. Let me know if you have any problems with it.
