### ISSUE TITLE
Container creation randomly fails with LVM thin pool

### ISSUE THREAD

**Issue by oszi** [docker/docker#25121]
**Output of `docker version`:**

```
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-44.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      9419b24-unsupported
 Built:           Fri Jun 24 12:09:49 2016
 OS/Arch:         linux/amd64
```

**Output of `docker info`:**

```
Containers: 10
 Running: 9
 Paused: 0
 Stopped: 1
Images: 1598
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: vg1-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 25.73 GB
 Data Space Total: 274.9 GB
 Data Space Available: 249.2 GB
 Metadata Space Used: 30.06 MB
 Metadata Space Total: 457.2 MB
 Metadata Space Available: 427.1 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: journald
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.18.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 8
Total Memory: 62.59 GiB
Name: bulkhead.avatao.com
ID: LW7U:MBXC:S3ST:RBGF:AGPI:LRZY:QCXK:JLQH:CYMT:24HN:GXVE:E3LM
WARNING: bridge-nf-call-ip6tables is disabled
Registries: docker.io (secure)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

There are two nodes (bare metal) in a swarm cluster and I'm using docker-py==1.7.2 as a client.

**Steps to reproduce the issue:**

This issue happens seemingly randomly when I start new containers.

**Describe the results you received:**

This is the log of a failed container in "created" state:
The daemon did not crash.

```
Code: System error

Message: stat /var/lib/docker/volumes/cc57986cdc9f786089c1b312d4580006d97f4bd43ac79a31ae8038de6422313f/_data: no such

Frames:
---
0: setupRootfs
Package: github.com/opencontainers/runc/libcontainer
File: rootfs_linux.go@41
---
1: Init
Package: github.com/opencontainers/runc/libcontainer.(*linuxStandardInit)
File: standard_init_linux.go@59
---
2: StartInitialization
Package: github.com/opencontainers/runc/libcontainer.(*LinuxFactory)
File: factory_linux.go@247
---
3: initializer
Package: github.com/docker/docker/daemon/execdriver/native
File: init.go@35
---
4: Init
Package: github.com/docker/docker/pkg/reexec
File: reexec.go@26
---
5: main
Package: main
File: docker.go@20
---
6: main
Package: runtime
File: proc.go@63
---
7: goexit
Package: runtime
File: asm_amd64.s@2232
```

Aftermath:

```
oci-register-machine[21872]: 2016/07/27 11:34:07 Register machine: poststop 95f1f70de08fd1025bf2daec2d862645006152cf073bd0740aef5a4222de9b04 0 /var/lib/docker/devicemapper/mnt/c2d3e2d4bb7b04df7cdc92a73b9e146bb32f09a1c5f7a3405aa9e5f358a90d64/rootfs
oci-register-machine[21872]: 2016/07/27 11:34:07 TerminateMachine failed: No machine '95f1f70de08fd1025bf2daec2d862645006152cf073bd0740aef5a4222de9b04' known
forward-journal[17687]: time="2016-07-27T11:34:07.761290210+02:00" level=error msg="error locating sandbox id 76e4d1b6583cd92dd09ce3f3973a6fe7d587dfd45fab4104f1586b77264b5647: sandbox 76e4d1b6583cd92dd09ce3f3973a6fe7d587dfd45fab4104f1586b77264b5647 not found"
forward-journal[17687]: time="2016-07-27T11:34:07.761344228+02:00" level=warning msg="failed to cleanup ipc mounts:\nfailed to umount /var/lib/docker/containers/95f1f70de08fd1025bf2daec2d862645006152cf073bd0740aef5a4222de9b04/shm: invalid argument"
forward-journal[17687]: time="2016-07-27T11:34:07.761370318+02:00" level=error msg="Error unmounting container 95f1f70de08fd1025bf2daec2d862645006152cf073bd0740aef5a4222de9b04: not mounted"
forward-journal[17687]: time="2016-07-27T11:34:07.761594915+02:00" level=error msg="Handler for POST /v1.15/containers/95f1f70de08fd1025bf2daec2d862645006152cf073bd0740aef5a4222de9b04/start returned error: Cannot start container 95f1f70de08fd1025bf2daec2d862645006152cf073bd0740aef5a4222de9b04: [9] System error: could not synchronise with container process"
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

Docker 1.9.1 is also affected.
This issue never occurred without Swarm with the same setup.

**Comment by thaJeztah** [comment]
What version of Swarm are you running?

Also looks like you're running a Red Hat fork of Docker, which contains a lot of patches and could be related. Are you able to reproduce this if you install the official packages from our repository? https://docs.docker.com/engine/installation/linux/centos/

**Comment by oszi** [comment]
Server Version: swarm/1.2.3 (The latest image from Docker Hub: a180b24e38ed)
I'll try to reproduce it with your repository and get back to you.

**Comment by oszi** [comment]
@thaJeztah I've tried docker-engine-1.10.3 and 1.11.2 and they both seem to be working.

But with the CentOS/RHEL package I could  reliably run 400 containers,
with the official package I can barely run a 100 then most containers stay in "created" state.

**Comment by oszi** [comment]
@thaJeztah Sorry for the delay.
So with the official package I don't see this error but containers still randomly stay in "created" state.
More often when I'm running over a 100 containers.

**Comment by thaJeztah** [comment]
anything useful in the daemon logs when that happens? (preferably with "debug" enabled on the daemon)

**Comment by oszi** [comment]
Here are the logs of the node where a container did not start: http://pastebin.com/raw/AepbwcRM
To help parsing it: This was the only container started from the `interesting_image` image.
(On a second try the same image works on both nodes.)

**Comment by oszi** [comment]
Storage issues (dm_task_run failed) started to occur on other docker hosts too with LVM thinpool
so I checked the machine mentioned above:

```
$ thin_check /dev/mapper/vg1-docker--pool
examining superblock
  superblock is corrupt
    bad checksum in superblock
```

Skimming the above log it's likely to have also been a storage issue. Volumes in this case.
I have no idea what corrupts them. Maybe deferred removal / deletion?

:disappointed:

**Comment by thaJeztah** [comment]
Yeah, I don't see anything really standing out in those logs; all look ok (apart from one volume not found, but that may have been a user error).

Re: corruption; could you have run out of disk space at some point?

No other suggestions at this moment; based in the information here, I'm not sure this is a bug in Docker, so I suggest closing, but let me know what you think

**Comment by thaJeztah** [comment]
Oh! I spotted one "secret" environment variable in your logs; not sure if that was just for testing, but you may want to check :innocent:

**Comment by oszi** [comment]
Thanks but that's always generated on every container start. :-)

That volume should have been inherited with "volumes from" and isn't mounted from the host's filesystem. It's only defined in the Dockerfile of the other image. As I said it works on a second try.
The LVM pool has over 200 GB free space so that can't be it either.

This issue sounds a lot like #19296 
I'm not sure if it's a bug in docker either. Although 1.9.1 seemed to be the most stable.

**Comment by oszi** [comment]
This goes deeper than I thought...
Docker 1.12 with the new overlay2 storage driver:
```
time="2016-08-01T16:57:21.492866251+02:00" level=error msg="containerd: start container" error="oci runtime error: rootfs_linux.go:53: mounting \"/etc/nginx\" to rootfs \"/var/lib/docker/overlay2/fe2db5649e4522e127ddc6b65a76f47b3a381fc65aa31ce47209d3673c45d001/merged\" caused \"stat /var/lib/docker/volumes/0f8a7644e469cd0fd44288b95c79c124e1959c4733f61268582f53c51fe80a4f/_data: no such file or directory\"" id=fe75bc3e49fc1242dfad8dfedd65841cca826eb7706eda526dab544c1d420265
time="2016-08-01T16:57:21.501537082+02:00" level=error msg="Create container failed with error: oci runtime error: rootfs_linux.go:53: mounting \"/etc/nginx\" to rootfs \"/var/lib/docker/overlay2/fe2db5649e4522e127ddc6b65a76f47b3a381fc65aa31ce47209d3673c45d001/merged\" caused \"stat /var/lib/docker/volumes/0f8a7644e469cd0fd44288b95c79c124e1959c4733f61268582f53c51fe80a4f/_data: no such file or directory\""
time="2016-08-01T16:57:21.568284431+02:00" level=error msg="Handler for POST /v1.15/containers/fe75bc3e49fc1242dfad8dfedd65841cca826eb7706eda526dab544c1d420265/start returned error: oci runtime error: rootfs_linux.go:53: mounting \"/etc/nginx\" to rootfs \"/var/lib/docker/overlay2/fe2db5649e4522e127ddc6b65a76f47b3a381fc65aa31ce47209d3673c45d001/merged\" caused \"stat /var/lib/docker/volumes/0f8a7644e469cd0fd44288b95c79c124e1959c4733f61268582f53c51fe80a4f/_data: no such file or directory\""
```
 The volume (/etc/nginx) is only defined in the Dockerfile as before and not mounted from the host.
We're running stateless containers where directories that need to be writeable by the user are defined volumes. For a second try it works again.

I'm starting to think this issue is related to volumes and not storage drivers. I still have devicemapper errors on one machine running 1.9.1 (EL7 package) which seems to be a second issue.

On the good side, I can run much more containers on overlay2.

@thaJeztah I'm losing it. What can I do? :smile:

**Comment by thaJeztah** [comment]
Wondering if this is SELinux blocking access to the volume path (I seem to recall something like that happening, at least for bind-mounts); can you confirm if the volume paths actually not exists?

Also, wondering if there's a race somewhere; looking at you're earlier logs, it looks like you're cleaning up dangling volumes; If `docker run ...` creates the volume before the container is started, and a volume cleanup script removes the (what it thinks is) "dangling" volume, then starting the container may fail. (thinking out loud)

**Comment by oszi** [comment]
Yes! It was a race condition with cleaning up dangling volumes. Thanks a lot!
Though I wonder why are they dangling when they belong to a container, even if it's not running yet.
The devicemapper issues were gone with 1.11 so I'm closing this.

**Comment by thaJeztah** [comment]
Happy to hear!

I think the race is that there's a short period between the volume being created and the container being registered (thus the volume being marked as "in use"), see [daemon/create.go#L118](https://github.com/docker/docker/blob/2cc5383f2fd000f4fa9fcaa4e0dd0bc8f6bb9c7f/daemon/create.go#L118), and [daemon/container.go#L180-L184](https://github.com/docker/docker/blob/6daf3d2a783fd042e870c8af8bbd19fc28989505/daemon/container.go#L180-L184)

ping @cpuguy83 any idea if we can improve on that?

**Comment by omar7c1** [comment]
In my case I fixed it with this way, the metadata file was broken because it reached the limit of the hard disk and the file was corrupted
Fix it with the following steps:
∘ systemctl stop docker
∘ thin_check --clear-needs-check-flag /var/lib/docker/devicemapper/devicemapper/metadata
∘ thin_check /var/lib/docker/devicemapper/devicemapper/metadata
∘ systemctl start docker

You can find more information at:
https://bodhileafy.wordpress.com/2018/04/20/docker-error-running-devicecreate-createsnapdevice-dm_task_run-failed/
