### ISSUE TITLE
Ignore bridge interfaces in address autodetection

### ISSUE THREAD

**Issue by aaronlehmann** [docker/docker#25139]
Based on the discussion in #25081, it sounds like there is a consensus that bridge interfaces should not prevent swarm IP address autodetection from succeeding.

If the only IP address on the system is associated with a bridge interface, we should use that one. But if there is also an IP address on a "normal" interface, the bridge should be ignored.

This will probably require the use of platform-specific code (netlink).

**Comment by justincormack** [comment]
You can detect a bridge with an `ioctl` rather than netlink I think, a bit
simpler.
