### ISSUE TITLE
Better error messages when IP address autodetection fails

### ISSUE THREAD

**Issue by aaronlehmann** [docker/docker#25141]
The current error message explains that the system has more than one IP address, so Docker doesn't know which to use. We should be more specific. For example, if two interfaces both have IP addresses, we should list those interfaces. If one interface has multiple IPs, we should name that interface.

**Comment by yongtang** [comment]
@aaronlehmann I create a PR #25271 to try to improve the error messages for IP address auto detection. Please let me know if there are any issues.
