### ISSUE TITLE
Can't kill container after restarting daemon with some stuck container

### ISSUE THREAD

**Issue by coolljt0725** [docker/docker#25157]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.3
 Git commit:   95ede36
 Built:        Thu Jul 28 03:19:42 2016
 OS/Arch:      linux/amd64
 Experimental: true
```
I run a container and it stuck on exiting, so I restart the daemon,
and `docker ps` show the container is still running. But run `ps aux | grep containerd`
I can't see these container is till running.
So I try to kill the container, but failed with
`container kill failed because of 'container not found' or 'no such process': Cannot kill container e1180c116260275f8bdfeb5599d2cc6b247800d75335585eeedccd864a4d4f02: rpc error: code = 2 desc = containerd: container not found`

I'm fully sure the container stuck on exiting, the daemon has receive the 
container event from containerd, but stuck on cleaning up container resource and 
restarting daemon make this container has a `Running=true` state but the container is
not running any more, so that we can see it in `docker ps`. I still can't figure out why
the container stuck and it's not easy to reproduce. But I think the daemon should handle
the case that the container has a `running=true` state but is not alive and has consumed all the
events from containerd. 
ping @mlaventure

**Comment by thaJeztah** [comment]
tentatively adding to 1.12.1

**Comment by icecrime** [comment]
Isn't this related to #25185?

**Comment by mlaventure** [comment]
It is, it should be fix now.
