### ISSUE TITLE
Trying to connect to Docker API for shell commands throws error #22338 bis

### ISSUE THREAD

**Issue by Kylvan** [docker/docker#25167]
Same issue as here https://github.com/docker/docker/issues/22338

I solved it by eval $ command but i have to do it each time i open a git bash terminal to build an image.

Can i have a forever solution please ?

Here i am on W7 x64

Regards

**Comment by thaJeztah** [comment]
Use docker for Mac, or Docker for Windows, which don't need these env vars, or include them in your [`.bashrc` or `.bash_profile`](http://www.tldp.org/LDP/abs/html/sample-bashrc.html)

This is not a bug; docker cannot decide for you what machine you want to connect to if the daemon is not running "locally" (with Docker Toolbox, it's running in a VM, which is effectively a "remote" machine).

This is not a bug, and can be solved using the above discussion solution; just remember to update those files if you re-create the machine, and the IP address changes

**Comment by Kylvan** [comment]
I can't use Docker for Windows because it is only for W10 i'm on W7 x64 like i said before, so i can only use Docker Tools Box.

I don't know how to integrate this in .bashrc or .bash_profile.

So i have to use eval $ command each time i start a terminal and want to build an image from a Dockerfile ?

**Comment by thaJeztah** [comment]
you don't have to if you keep the shell open. Probably, you can set those environment variables somewhere in Windows as well; a tip for this in the Documentation for Docker Machine or Toolbox may be something to consider

**Comment by Kylvan** [comment]
I will read it for sure when i will have the time, thanks for advice.

I know the variables are enter in my Windows cause i've checked it earlier that's why i don't understand why i've this issue.
