### ISSUE TITLE
Latest master.dockerproject.org client / server win builds have incompatible protocol versions

### ISSUE THREAD

**Issue by sitano** [docker/docker#25173]
Latest https://master.dockerproject.org/windows/amd64/docker.exe (2016-07-28T09:11:56.000Z) api protocol version (1.25) is not compatible to latest https://master.dockerproject.org/windows/amd64/dockerd.exe
(2016-07-28T09:11:59.000Z) api protocol version (1.24). Someone did not bump server protocol version in master or its incompatibly prev for real? 

**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.3
 Git commit:   193b036
 Built:        Thu Jul 28 09:05:05 2016
 OS/Arch:      windows/amd64
```

**Output of `dockerd -v`:**

```
Docker version 1.12.0-dev, build 193b036
```

**Comment by thaJeztah** [comment]
Ping @tiborvass @mlaventure any idea how that would be possible? it's built from the same source

**Comment by sitano** [comment]
Sorry. It seems like its my fault. - another instances in the search path.

**Comment by sitano** [comment]
Related to https://github.com/StefanScherer/docker-windows-box

**Comment by thaJeztah** [comment]
phew, thanks!
