### ISSUE TITLE
[1.12.0-dev] [193b036] broken on Windows TP5 (@StefanScherer/docker-windows-box)

### ISSUE THREAD

**Issue by sitano** [docker/docker#25176]
I am using fresh https://github.com/StefanScherer/docker-windows-box deployed 1 week ago. 

After update to the latest docker version 1.12.0-dev, 193b036, `docker images` command stopped to show anything. No any other images can be pulled or build, because of the missing basic layer error which makes sense - as it missing. 

But its actually present at C:\ProgramData\Microsoft\Windows\Images\CN=Microsoft_WindowsServerC
ore_10.0.14300.1000. 
And DB there is fine.

I will look into that a bit later trying rollback couple of docker version to understand is there any correlation with the code / commits or env - not sure for now. But. Here, it is.

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.3
 Git commit:   193b036
 Built:        Thu Jul 28 09:05:05 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.3
 Git commit:   193b036
 Built:        Thu Jul 28 09:05:05 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Security Options:
Kernel Version: 10.0 14300 (14300.1045.amd64fre.rs1_release_svc.160705-1059)
Operating System: Windows Server 2016 Datacenter Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 4 GiB
Name: vagrant-2016
ID: D62W:NRXN:UCL2:KTLR:5QEI:Z5JJ:LTBM:6OQD:2HCK:IWJJ:GIPM:EOYZ
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VirtualBox 5.0.26r108824

**Steps to reproduce the issue:**
1. Set VirtualBox 5.0.26r108824
2. Build and Run https://github.com/StefanScherer/docker-windows-box
3. Copy docker/d 193b036 versions into c:\Program Files\docker\*
4. Start service with & "C:\Program Files\docker\dockerd.exe" --run-service -H npipe:// -H 0.0.0.0:2
375 -G docker
5. & "C:\Program Files\docker\docker.exe" images

**Describe the results you received:**

Result of `docker images` command shows nothing.

`docker pull microsoft/iis:windowsservercore` fails.

**Describe the results you expected:**

At least basic windows image. And all other I had before moving to new version.

**Additional info:**

`Install-ContainerImage -Name WindowsServerCore` says the image is in place and it is not going to overwrite it which is fine.

**Comment by sitano** [comment]
The version `Docker version 1.12.0-dev, build 8e92415` works fine.

**Comment by sitano** [comment]
The change from May 28, f182748b9b7d639c4db09f4f72411aba5f811f4e by @jstarks breaks the installs which were done before. Graph DB does not migrate automatically to the new path C:\ProgramData\docker\image\windowsfilter\ (from C:\ProgramData\docker\image\Windows filter storage driver\).

**Comment by sitano** [comment]
@jstarks Is not that a bug, the graph path calculation depends on 
> func (d *Driver) String() string
but not the registered driver codename it self?

**Comment by StefanScherer** [comment]
@sitano Thanks for the deep investigation! The change is both in latest docker and also in the just released docker 1.12.0 so windowsfilter should be the new default. This rename step should be part of some update documentation if someone wants to update the TP5 (May 26th) binaries to let's say 1.12.0 or newer.

**Comment by sitano** [comment]
As of 1.13.0-dev / 7d4ab5c (build from Tue Aug  2 06:19:22 2016) I am still having issues with dockerd.
- `docker images` shows nothing, yet I have 2 basic images installed. WindowsServerCore and NanoServer. This is due https://github.com/docker/docker/commit/3e109f349ff42ea1a0f555b6e645c51d9bc1539b - Removing Custom Images support. Ok, but, how that supposed to work via `docker load`? Any instructions anywhere? Should hack over `(Get-Command Install-ContainerOSImage).ScriptBlock`?
- `docker pull` asks for auth... Something changed to it? Or...

**Comment by sitano** [comment]
Continuing dispute on dropped WIM support at _Add Windows Dockerfile_ https://github.com/docker-library/golang/pull/92

**Comment by sitano** [comment]
Native docker HUB images do not work https://hub.docker.com/r/microsoft/windowsservercore/ , with `docker pull microsoft/windowsservercore`: 

> Error response from daemon: manifest unknown: manifest

**Comment by sitano** [comment]
`docker run -it microsoft/nanoserver cmd` does not work as well.

> Unable to find image 'microsoft/nanoserver:latest' locally
> C:\Program Files\docker\docker.exe: Error response from daemon: manifest unknown: manifest unknown.
> See 'C:\Program Files\docker\docker.exe run --help'.

**Comment by jstarks** [comment]
@sitano Sorry about the breaking change that moved the windowsfilter directory. This was actually a regression that I fixed; I restored the location to where it was originally. Unfortunately, you got trapped in the middle and I didn't write any fixup code. I'm glad you found a workaround.

Our expectation is that the standard `docker pull` workflow is the official way to get the Windows base images into Docker, and we do not intend to restore WIM-based image support. The `docker load` workaround you reference above was a temporary workaround while we were adding support for Microsoft-hosted layers to Docker Hub.

We actually only got `docker pull` working in the last few days (as you can see, the image is 4 days old), and we have not yet tagged the images with `latest` because we are pushing new versions of the derived images and doing some final verification. Once this is finished, we will update the documentation.

You can help test this for us by pulling and using `microsoft/nanoserver:10.0.14300.1030` or `microsoft/windowsservercore:10.0.14300.1030` and letting us know if you see any problems. Sorry about the mess during this transition.
