### ISSUE TITLE
docker node ps should have all option

### ISSUE THREAD

**Issue by jhorwit2** [docker/docker#25180]
```
docker node ps
"docker node ps" requires exactly 1 argument(s).
See 'docker node ps --help'.

Usage:  docker node ps [OPTIONS] self|NODE

List tasks running on a node
```

It would be nice to be able to query all the tasks with one go.

**Comment by ralphtheninja** [comment]
@jhorwit2 Is `docker node ps` on master? I can't seem to find it in `rc5`.

**Comment by jhorwit2** [comment]
@ralphtheninja yup.

**Comment by jhorwit2** [comment]
cc @stevvooe since you handled the pr for `ps`. Thoughts on adding `-a` and perhaps defaulting to self? I keep forgetting about `self` since that's not how `docker ps` works (albeit way different).

**Comment by stevvooe** [comment]
@jhorwit2 I'm not a huge fan of the in-band `self`. I am not sure where else we do this, but it can create ambiguity and it is only valid on manager nodes. I'd argue for the following:

```
docker node ps # tasks on the current node, if a master
docker node ps -a # all nodes tasks, big and ugly output
docker node ps <NODE>
```

As far as the use case of querying all tasks in a single go, the right approach should actually be the inclusion of a `docker tasks` command. This was omitted from 1.12 since we wanted to avoid the introduction of too many top-level commands at once. This is also going to be influenced by the adoption of the task model within the ecosystem.

I am not sure if we want to have `docker node ps` become the "query all tasks" command.

**Comment by jhorwit2** [comment]
@stevvooe As far as I can tell the only other place is `node inspect`. `docker tasks` definitely seems like the best solution for more task centric stuff. I find myself typing `docker tasks` at least once a day since the rc came out lol. 

The only thing I was struggling on was `docker ps` is used to show all *running* containers, but `docker node ps` shows all tasks regardless of state. Same goes for `docker service ps` which has a ticket https://github.com/docker/docker/issues/25196. 

After thinking about it some more / playing around implementing it ```

docker node ps # running tasks on current node, if a master
docker node ps -a # all tasks on current node, if a master
docker node ps NODE -a # all tasks on given node, if a master
```

For now until `docker tasks` is available you could just do `docker node ps (docker node ls -q -f role=manager)`. 

That way we have symmetry across the various ps commands. 

Thoughts?

**Comment by stevvooe** [comment]
Agreed.

Something like `docker node ps $(docker node ls -q)` would be a much better pattern. I am not sure why we limited this a single node.

We may want to filter the output of `docker xxx ps` to only including tasks that are running or will run. We added the more verbose output since people kept asking how to get service errors.

**Comment by jhorwit2** [comment]
@stevvooe that command works now with the 1.12 GA.

> We may want to filter the output of docker xxx ps to only including tasks that are running or will run. 

If i'm not mistaken, a filter of `desired-state=running` would do that, right? 

If so, I'm basically done with that PR. #dibs

**Comment by thaJeztah** [comment]
closing per https://github.com/docker/docker/pull/25251#issuecomment-240812097, but feel free to continue the discussion

**Comment by jhorwit2** [comment]
@thaJeztah yes they are important, but it's going to get unwieldy when you have a bunch of tasks. 

Thoughts on defaulting ps to self w/o explicitly putting self? That was in that PR also.

**Comment by thaJeztah** [comment]
@jhorwit2 there's actually another PR open for that I saw; https://github.com/docker/docker/pull/25214

My previous comment was a bit short, as I was typing during the hangout, so let me to add what's discussed; basically it came down to:

- there's a limit in place on the number of failed/stopped tasks, which partly prevents the number of tasks shown
- hiding stopped task *by default* was not something that would be accepted (given the reason above) (filtering would work there as mentioned above)
- we do agree that the list of tasks can become long for a big service, so perhaps we should start thinking of *pagination* in docker

**Comment by jhorwit2** [comment]
> we do agree that the list of tasks can become long for a big service, so perhaps we should start thinking of pagination in docker

It's going to be even longer if you run `node ps` 😉 

Sounds good though!

**Comment by thaJeztah** [comment]
Let me reopen this, because things are being discussed again in https://github.com/docker/docker/pull/25251 (sorry for the back-and-forth!)

**Comment by dev852** [comment]
Reopen- How do worker node do a self check?

I am having trouble checking if a node has already joined a swarm on Ansible

    - name: Check if Worker has already joined
      shell: docker node ls
      register: swarm_status
      ignore_errors: true
 
    - name: Join Swarm
      shell: shell: docker swarm join --token {{ hostvars[groups['leader'][0]]['worker_token']['stdout'] }} {{ hostvars[groups['leader'][0]]['ec2_public_ip']['stdout'] }}:2377
      when: swarm_status.rc != 0
      run_once: true

This doesn't work as swarm_status will always display error as worker cannot inspect self. Thanks.

-- cyayung
