### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by gorazio** [docker/docker#25184]
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:39 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:39 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 22
 Running: 4
 Paused: 0
 Stopped: 18
Images: 733
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 2597
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: overlay bridge null host
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 62.87 GiB
Name: name
ID:
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Labels:
 storage=permanent
Cluster store: consul://xx.xx.xx.xx:8500
Cluster advertise: xx.xx.xx.xx:4000
```

don't know how to reproduce it
i run swarm cluster with two nodes, and docker fall with this error
panic: runtime error: slice bounds out of range
full log in attach
[docker.log.tar.gz](https://github.com/docker/docker/files/389066/docker.log.tar.gz)

**Comment by cpuguy83** [comment]
ping @mavenugo

**Comment by icecrime** [comment]
@aboch @mrjana @mavenugo Can somebody please look into the stack trace, let us know if it's fixed on master, and close is that's the case? Thanks.

**Comment by gorazio** [comment]
i have same error on docker 1.12

`Nov 23 19:03:13 host-02 dockerd[1714]: panic: runtime error: slice bounds out of range
Nov 23 19:03:13 host-02 dockerd[1714]: goroutine 162 [running]:
Nov 23 19:03:13 host-02 dockerd[1714]: panic(0x1a733c0, 0xc82000e050)
Nov 23 19:03:13 host-02 dockerd[1714]: /usr/local/go/src/runtime/panic.go:481 +0x3e6
Nov 23 19:03:13 host-02 dockerd[1714]: github.com/docker/libnetwork/osl.(*networkNamespace).DeleteNeighbor(0xc8216bb130, 0xc822e5c0b0, 0x10, 0x10, 0xc822e5c080, 0x6, 0x6, 0x1, 0x0, 0x0)
Nov 23 19:03:13 host-02 dockerd[1714]: /usr/src/docker/vendor/src/github.com/docker/libnetwork/osl/neigh_linux.go:82 +0x9b0
Nov 23 19:03:13 host-02 dockerd[1714]: github.com/docker/libnetwork/drivers/overlay.(*driver).peerDelete(0xc820356380, 0xc8236054c0, 0x40, 0xc823605500, 0x40, 0xc822e5c0b0, 0x10, 0x10, 0xc822e5c0cc, 0x4, ...)
Nov 23 19:03:13 host-02 dockerd[1714]: /usr/src/docker/vendor/src/github.com/docker/libnetwork/drivers/overlay/peerdb.go:346 +0x62c
Nov 23 19:03:13 host-02 dockerd[1714]: github.com/docker/libnetwork/drivers/overlay.(*driver).processEvent(0xc820356380, 0x3c13, 0xc825aac280, 0x93, 0xc821b74e70, 0x30, 0x30, 0x1)
Nov 23 19:03:13 host-02 dockerd[1714]: /usr/src/docker/vendor/src/github.com/docker/libnetwork/drivers/overlay/ov_serf.go:128 +0x1338
Nov 23 19:03:13 host-02 dockerd[1714]: github.com/docker/libnetwork/drivers/overlay.(*driver).startSerfLoop(0xc820356380, 0xc8200668a0, 0xc8200671a0, 0xc820067200)
Nov 23 19:03:13 host-02 dockerd[1714]: /usr/src/docker/vendor/src/github.com/docker/libnetwork/drivers/overlay/ov_serf.go:220 +0x4d9
Nov 23 19:03:13 host-02 dockerd[1714]: created by github.com/docker/libnetwork/drivers/overlay.(*driver).serfInit
Nov 23 19:03:13 host-02 dockerd[1714]: /usr/src/docker/vendor/src/github.com/docker/libnetwork/drivers/overlay/ov_serf.go:68 +0x496
`
`docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:39:14 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:39:14 2016
 OS/Arch:      linux/amd64
`
`docker info
Containers: 43
 Running: 43
 Paused: 0
 Stopped: 0
Images: 83
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 454
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null host bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 62.87 GiB
Name: host-02
ID: OB2P:MN2S:3QII:LCCJ:WXQB:XU62:WS27:3CX5:4Y63:TEWD:SS2R:IMCE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Labels:
 http=true
Cluster Store: consul://yyy.yyy.yyy.yyy:8500
Cluster Advertise: xxx.xxx.xxx.xxx:4000
Insecure Registries:
 127.0.0.0/8
`

There is cluster running with swarm standalone, and this node is not a manager

**Comment by aboch** [comment]
Fixed by https://github.com/docker/libnetwork/pull/1555 and available in next docker release.
Fix was ported in docker via https://github.com/docker/docker/pull/28562

**Comment by aboch** [comment]
Closing as fixed in current master
