### ISSUE TITLE
Docker for Mac: update message output is missing some spaces

### ISSUE THREAD

**Issue by slimsag** [docker/docker#25199]
![image](https://cloud.githubusercontent.com/assets/3173176/17234520/ad5b6b06-54ee-11e6-8a12-284dcf3a503f.png)

**Comment by icecrime** [comment]
Ping @aduarmael: apparently we're missing a scrollbar 😉

**Comment by gdevillele** [comment]
Hmm, that window comes from [Sparkle](https://sparkle-project.org) (update framework for macOS applications)
Not sure we can do much about it...
