### ISSUE TITLE
docker service create not pulling image from quay.io

### ISSUE THREAD

**Issue by mikeprice99** [docker/docker#25211]
**Output of `docker version`:**

```
Docker version 1.12.0-rc5, build a3f2063
```
**Output of `docker info`:**

```
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 298
Server Version: 1.12.0-rc5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 370
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null overlay bridge
Swarm: active
 NodeID: b09qanm1y28lo5yzkrqdlpzb6
 Is Manager: true
 Managers: 2
 Nodes: 2
 Node Address: 10.0.0.123
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-28-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 7.796 GiB
Name: server1
ID: FD7N:BUKQ:JKZH:6LCQ:UTL5:5CCD:YOK3:3UIF:D56N:HKZJ:DTUL:WYBT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Steps to reproduce the issue:**
1. `docker service create --replicas=1 quay.io/mycompany/myimage:1.2016.193.1`

**Describe the results you received:**
`docker service ls` shows 0/1 (even after waiting 10 minutes)
`docker images` (run on either node): the image is not listed
If at this stage I manually pull the image, then the service immediately creates an instance.

In fact it creates multiple instances when only one replica has been requested. All instances are created on the node on which the docker pull command was run. In my first test, 4 containers were created, in a later test 12  containers were created, so `docker service ls' showed
```
ID            NAME      REPLICAS  IMAGE                                     COMMAND
06f02qucwfmc  myimage   12/1      quay.io/mycompany/myimage:1.2016.193.1

```
**Describe the results you expected:**
docker service create should pull the requested image if not present

**Comment by thaJeztah** [comment]
service create / update will always pull the image, to make sure you're not running an outdated version, however, for private mages, you need to use the `--with-registry-auth` to pass the authentication information when creating the service (you can also use it on `docker service update`); can you try with that option?

**Comment by thaJeztah** [comment]
Can you open a separate issue for docker creating more instances than requested? Because that clearly sounds like a bug

ping @stevvooe @dongluochen ^^

**Comment by stevvooe** [comment]
> Can you open a separate issue for docker creating more instances than requested? Because that clearly sounds like a bug

This is probably a transient reporting error. Make sure to include the output of `docker service ps <service>` to confirm.

**Comment by mikeprice99** [comment]
Thank you @thaJeztah 
`--with-registry-auth` fixed the problem of pulling from a private registry.
With reagrd to the extra instances, I'll test in 1.12.0 and if the problem still exists, I'll create an issue (may take a while to prepare test environment again)

**Comment by mikeprice99** [comment]
@stevvooe  : it wan't a reporting error. Running docker ps -a on the different nodes listed all the containers that had been created. In one test I actually had 40 extra containers!

**Comment by dongluochen** [comment]
> Running docker ps -a on the different nodes listed all the containers that had been created. In one test I actually had 40 extra containers!

@mikeprice99 We normally see `12/1` during convergence where replica count changes. That doesn't sound like your case. Do you have repro steps to such behavior? It'd be great if you can post your commands and output.

**Comment by mikeprice99** [comment]
Having upgraded to v1.12.0 I cannot reproduce the issue of extra containers. :)

**Comment by thaJeztah** [comment]
Thanks @mikeprice99, looks like we can close this issue then!
