### ISSUE TITLE
Support multiple service IDs on "docker service tasks"

### ISSUE THREAD

**Issue by ezrasilvera** [docker/docker#25228]
It would be very useful if we could list tasks of multiple services in a single command 
This capability is supported by "inspect" and "rm" so I see no reason why "tasks" would be different

**Comment by yongtang** [comment]
@ezrasilvera The `docker service tasks` has been renamed `docker service ps`. Not sure if the proposed change is still relevant. I still created a PR #25234 and let me know if it makes sense.

**Comment by ezrasilvera** [comment]
@yongtang  it is still relevant. thanks.
