### ISSUE TITLE
Upstart script waits forever when daemon has two unix sockets

### ISSUE THREAD

**Issue by bboreham** [docker/docker#25223]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.0
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.19.0-64-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.614 GiB
Name: test-template-11
ID: TPSR:2GSQ:KFJL:6PC2:ODY5:AXOI:6IBU:KN4T:ZWCM:RKBQ:PU5U:MXRA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Install Docker on a system using `upstart`, e.g. Ubuntu 14.04
2. Add this line at the end of `/etc/default/docker` to have two unix sockets:

    DOCKER_OPTS="-H unix:///var/run/docker.sock -H unix:///var/run/alt-docker.sock"

3.`service docker restart`

**Describe the results you received:**

`service docker restart` command hangs.  These messages observed in Docker log file:

````
Waiting for /var/run/docker.sock
/var/run/alt-docker.sock
Waiting for /var/run/docker.sock
/var/run/alt-docker.sock
Waiting for /var/run/docker.sock
/var/run/alt-docker.sock
````

**Describe the results you expected:**

Docker starts, listens on two Unix sockets.

**Additional information you deem important (e.g. issue happens only occasionally):**

Fault is in [docker.conf](https://github.com/docker/docker/blob/428d7337e808ec5f4dba1b0aceda002f295cc320/contrib/init/upstart/docker.conf#L61) - that `grep` will output every match of the pattern.  Notwithstanding the statement in the commit message at #19886 that it will only look at the first one.

**Comment by thaJeztah** [comment]
Are you interested in opening a PR for this?

**Comment by bboreham** [comment]
@thaJeztah yeah, PR is done; I'm just rebuilding my test machine to check it.

**Comment by thaJeztah** [comment]
Awesome! Thanks so much :+1:
