### ISSUE TITLE
Docker volume empty folder on Windows

### ISSUE THREAD

**Issue by DreamFlasher** [docker/docker#25232]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:04:48 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:04:48 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 17
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.95 GiB
Name: moby
ID: KN65:HRHW:EFIE:IYKF:EOLD:2P2G:UZX3:5LAT:UZUX:7LIP:3XCF:F3KI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical, Windows 10 x64, docker beta, cygwin

**Steps to reproduce the issue:**
1. In Cygwin `winpty docker run -it --rm -v c:/full/path/project:/project private/image bash`
or
1. In Cygwin `winpty docker run -it --rm -v /cygrive/c/full/path/project:/project private/image bash`

**Describe the results you received:**
project folder is empty

**Describe the results you expected:**
correctly mounted project structure

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment]
I've seen some people complain about this.
Can you go into the docker app preferences and unshare/re-share the dirs/drives you want?

**Comment by DreamFlasher** [comment]
I did that (remove checkbox, apply, set checkbox, apply) -- no change.

**Comment by thaJeztah** [comment]
I think there's still an issue with non-ascii characters in passwords, also see the troubleshooting section; https://docs.docker.com/docker-for-windows/troubleshoot/#/host-filesystem-sharing

**Comment by ysz** [comment]
It plain doesn't work. 

> docker run -it -v \`pwd\`:/mnt -w /mnt ubuntu /bin/bash -c ls

doesn't list files on Windows but works on Mac

**Comment by DreamFlasher** [comment]
Thank you @ysz I can confirm this, this command works under Ubuntu, but not on Windows (neither cygwin, nor powershell, nor ubuntu bash).

**Comment by JesusVKilma** [comment]
So I tried the common suggestions to no avail:
 - Changing my password to an ASCII 8-bit pass
 - Switching to the beta channel of Docker
 - Resetting to factory defaults

Finally I found a thread which suggested that PCs attached to a domain cause a problem (I had previously been playing with a Windows Server and attached myself to a domain. After I removed my PC from the domain and placed my PC in a Workgroup, mounts worked again after a reset!

Ps. there are several of these threads going all with the same issue.

**Comment by codingkeith** [comment]
I have the same problem. I found that if I create a local user accountand log in with that the issue is resolved, but if I log in with a Windows Domain account the problem exists. My Windows Domain user is a Domain Administrator and a local Administrator and my local user was a local Administrator - so this is not a file permissions issue.

**Comment by friism** [comment]
@codingkeith (and others) can I please ask you also post a comment here? https://github.com/docker/for-win/issues/25

Please run diagnostics both in the working using configuration and in the non-working one and reference the diagnostic ids in your comment so that we can have a look at what's going on.

**Comment by DreamFlasher** [comment]
It's solved for me, see here: https://github.com/docker/for-win/issues/25#issuecomment-245245852
Actually I think this is a duplicate of https://github.com/docker/for-win/issues/25

**Comment by datason** [comment]
I have to use windows at work, so I solved this problem:
Run in detached mode to test it: 
**cygwin**: `docker run -v c:/Users/datason/study/amazon-sagemaker-examples-master/advanced_functionality/scikit_bring_your_own/container/local_test:/opt/ml  -d -t  --name dt_container dt_image`
# here, i am in a `local_test` directory.
**powershell**: `docker run -v ${PWD}:/opt/ml  -d -t  --name dt_container dt_image`
I don't realize why, but $(pwd) doesn't work in cygwin.

**Comment by thaJeztah** [comment]
@datason might be related to MSYS/MinGW doing "path conversion"; see https://stackoverflow.com/questions/7250130/how-to-stop-mingw-and-msys-from-mangling-path-names-given-at-the-command-line, https://github.com/moby/moby/issues/12590#issuecomment-294141429, and various other issues

Try setting `MSYS_NO_PATHCONV=1`
