### ISSUE TITLE
net=host mode bug under mac, container with default bridge mode can not access host opening port

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [docker/docker#25235]
**Output of `docker version`:**

```
(python2) mmcdeMacBook-Air:~ mmc$ docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 23
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.954 GiB
Name: moby
ID: D3CE:BLOM:7POQ:5KMA:LIMF:PSVT:MEAQ:GNEV:4JNX:N5YW:6HCJ:QD3X
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 26
 Goroutines: 40
 System Time: 2016-07-29T16:15:59.152792247Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
virtualbox 5.1.2 r108956
```
here is my host mac  network info
![local_network](https://cloud.githubusercontent.com/assets/7458713/17255309/402d0136-55eb-11e6-9651-988242db646a.png)

issue 1
**Steps to reproduce the issue:**
1. start a new container with -net=host mode
```
docker run -it --net=host edib/elixir-phoenix-dev /bin/bash
input ip address in container
```

**Describe the results you received:**
```
wish to see the same ip as host network interface eth0
```

**Describe the results you expected:**
```
host ip is 192.168.1.55, container ip is 192.168.65.xx, here is the screenshot
```
![net_host](https://cloud.githubusercontent.com/assets/7458713/17255588/739cfac0-55ec-11e6-96d3-7d4d869eaa72.png)

issue 2
**Steps to reproduce the issue:**
1. start a new container with default mode
```
docker run -it edib/elixir-phoenix-dev /bin/bash

in container run 
telnet to 172.17.0.1 8888
```

**Describe the results you received:**
```
8888 is my host port, listening for http request, screenshot
```
![web_page](https://cloud.githubusercontent.com/assets/7458713/17255487/15545b20-55ec-11e6-992f-937d1d981aec.png)

```
container telnet 172.17.0.1 failed, but  ping 172.17.0.1 runs ok
```
![default](https://cloud.githubusercontent.com/assets/7458713/17255537/430a1bcc-55ec-11e6-913e-d76c1ff7ef6a.png)

**Describe the results you expected:**
```
running container can telnet to host port, it runs ok under linux docker.
```

**Comment by thaJeztah** [comment]
Thanks for reporting @ziyouchutuwenwu. We recently opened a separate issue tracker for Docker for Mac issues; could you reopen this issue in that issue tracker? https://github.com/docker/for-mac/issues

**Comment by ziyouchutuwenwu** [comment]
thank you, i create a new one under https://github.com/docker/for-mac

**Comment by thaJeztah** [comment]
Thanks!

**Comment by ziyouchutuwenwu** [comment]
it seems no one take attention to that issue..............................
it's too bad
