### ISSUE TITLE
Docker failed to connect to VolumePlugin in v1.12 with .json file

### ISSUE THREAD

**Issue by drngsl** [docker/docker#25233]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-85-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.955 GiB
Name: test
ID: K4L2:AZDM:RVTH:WXUC:RTNF:CSNU:AVSJ:QCMU:XY3G:AHPK:AQKS:KUT3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Destination: Enable Docker to use my VolumePlugin
2. Method: Create plugin file in plugin directory. /usr/lib/docker/plugins/volplugin/volplugin.json
{
    "Name": "volplugin",
    "Addr": "http://127.0.0.1:7879"
}
3. Get Docker volume with cmd: docker volume ls

**Describe the results you received:**
An error occurred trying to connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/volumes: EOF

**Additional information you deem important (e.g. issue happens only occasionally):**
I checked the above problem in Ubuntu 14.04 and Centos 7.
With the above information, I want to know that Docker couldn't enable VolumePlugin with .json?

**Comment by icecrime** [comment]
Ping @anusha-ragunathan @tiborvass!

**Comment by tiborvass** [comment]
@drngsl Would you mind providing some daemon logs so that we can see the actual error?

**Comment by drngsl** [comment]
@tiborvass 
docker daemon print the following error information:
`DEBU[0018] Calling GET /v1.24/volumes                   
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0xc36981]

goroutine 115 [running]:
panic(0x1a52560, 0xc82000e0f0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/docker/docker/pkg/plugins.readPluginJSONInfo(0xc8206b494d, 0x4, 0xc8206b4d20, 0x26, 0x0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/pkg/plugins/discovery.go:119 +0x221
github.com/docker/docker/pkg/plugins.(*localRegistry).Plugin(0xc820719e70, 0xc8206b494d, 0x4, 0x4693f0, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/pkg/plugins/discovery.go:80 +0xa65
github.com/docker/docker/pkg/plugins.loadWithRetry(0xc8206b494d, 0x4, 0xc820714100, 0xc82043e798, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/pkg/plugins/plugins.go:172 +0xa2
github.com/docker/docker/pkg/plugins.GetAll.func1(0xc820714160, 0xc8206d7440, 0xc8206b494d, 0x4)
	/usr/src/docker/.gopath/src/github.com/docker/docker/pkg/plugins/plugins.go:255 +0x5f
created by github.com/docker/docker/pkg/plugins.GetAll
	/usr/src/docker/.gopath/src/github.com/docker/docker/pkg/plugins/plugins.go:257 +0x5a5`

**Comment by drngsl** [comment]
@tiborvass Of course, when i use .spec instead of .json, command `dokcer volume ls` works properly.

**Comment by yongtang** [comment]
@drngsl It looks like the issue has been fixed in #25053, though it is not in 1.12.0 yet.

**Comment by drngsl** [comment]
@yongtang so in v1.12.0, is there some changes or requirements to volume plugin configuration?

**Comment by yongtang** [comment]
@drngsl The issue you encountered was because a nil pointer (`TLSConfig`) panic in `pkg/plugins/discovery.go`. The panic prevent your JSON config file being loaded. #25053 fixed the panic.

**Comment by thaJeztah** [comment]
Looks like this is resolved already, so I'm closing it
