### ISSUE TITLE
How to copy files into a named volume without an attached container?

### ISSUE THREAD

**Issue by ToBeReplaced** [docker/docker#25245]
If I create a volume with:

`docker volume create --name test-volume`

I would like to then copy `example.cfg` into the volume. However, `docker cp` works with containers, not volumes.

Right now, I need to create a container that mounts the volume, copy the file in, then remove the container. Alternatively, I can inspect the volume and modify the filesystem directly. Is there a better way?

**Comment by thaJeztah** [comment]
That's the way to do it. For configuration files, you could consider using a bind-mount, or perhaps a volume driver that allows mounting configuration as a volume https://docs.docker.com/engine/extend/plugins/#/volume-plugins

**Comment by thaJeztah** [comment]
I'm closing this issue, because this is a question, not a bug report, but feel free to continue the discussion

**Comment by ToBeReplaced** [comment]
Thanks for the quick reply. Has there been a consensus decision not to support "copy into volume", or is this something that could be requested as a feature? If there has been a decision, what was the rationale?

**Comment by thaJeztah** [comment]
Oh, yes, there is an open feature request, but it hasn't been decided on yet; see https://github.com/docker/docker/issues/18718.

**Comment by ToBeReplaced** [comment]
Perfect, thank you.

**Comment by wyckster** [comment]
Do you want to copy a file to a docker volume, but the volume doesn't have a container?  I'll tell you how I do it.

Unfortunately, you **do** need a container.  But, this is actually the lightest-weight method I have found so far.

## Basic Idea
1. Use `docker run` to start a dummy light-weight container and mount your volume.
    - The concept here is to use the **alpine** image and run some minimal service that doesn't exit.  The lightest-weight image I can find is alpine linux (**alpine**), and the simplest command I can think of that doesn't exit is `tail -f /dev/null`.
    - Start this command with the `-d` option to _detatch_ and leave the dummy container running so that you can _reuse your existing shell_ to enter the next command. (which will be the **docker cp** command -- see step 2 below).
    - Use `--rm` so that when you stop the dummy container it will get removed automatically.  This is a temporary container, so using automatic cleanup is a good habit and will prevent leaving a forgotten dummy container lying around.
    - Most importantly, use `-v` to mount the volume into the file system of the container.  Choose any path that doesn't conflict with something in alpine.  e.g.:  `/root`
    - And finally, use the `--name` option to give the container a reasonable name to be used in steps 2 and 3 below.  e.g.: `dummy`
2. Use `docker cp` to copy the file into the container at the location you mounted the volume.  In the example below, the file `c:\myfolder\myfile.txt` is copied into the volume.
    - You can repeat this step as many times as you like to copy more files.
    - You can copy from the local file system to the volume, or from the volume to the local file system as needed.
3. Use `docker stop` to stop the dummy container.  This will also cause docker to remove the container because you used the `--rm` option.

## Step by Step Example

    docker run -d --rm --name dummy -v myvolume:/root alpine tail -f /dev/null
    docker cp c:\myfolder\myfile.txt dummy:/root/myfile.txt
    docker stop dummy

You can also copy the other way (from the volume to the local file system).

    docker cp dummy:/root/myfile.txt c:\myfolder\myfile.txt

_If there's a better way, I'd love to know what it is!_

**Comment by thaJeztah** [comment]
There's no need to _start_ the container, just _creating_ a container is enough;

```
docker container create --name dummy -v myvolume:/root hello-world
docker cp c:\myfolder\myfile.txt dummy:/root/myfile.txt
docker rm dummy
```

**Comment by mvasin** [comment]
@wyckster @thaJeztah Here's a one-liner that copies `myfile.txt` from current directory to `my_volume`:
`docker run --rm -v $PWD:/source -v my_volume:/dest -w /source alpine cp myfile.txt /dest`

**Comment by wyckster** [comment]
@thaJeztah That's cool, thanks!  

Now I'm wondering, is there an image that is lighter weight than hello-world?  I can't just create a container running `scratch`.

So, I used the following Dockerfile to create a _nothing_ image.

```
FROM scratch
CMD
```

```
docker build -t nothing .
```

Now my steps are:

```
docker container create --name dummy -v myvolume:/root nothing
docker cp c:\myfolder\myfile.txt dummy:/root/myfile.txt
docker rm dummy
```

**Comment by TeamDman** [comment]
@wyckster 
https://hub.docker.com/r/tianon/true/ is pretty light.
125 bytes

**Comment by dorintt** [comment]
Here is my convenience script:
`docker-volume-cp.sh`
```
SOURCE=$1
DEST=$2

SOURCE_ARR=(${SOURCE//:/ })
DEST_ARR=(${DEST//:/ })


if [[ ${#SOURCE_ARR[@]} -eq 2 && ${#DEST_ARR[@]} -eq 1 ]]; then
        VOL=${SOURCE_ARR[0]}
        VOL_PATH=${SOURCE_ARR[1]}
        HOST_PATH=${DEST_ARR[0]}

        docker container create --name docker_volume_cp -v $VOL:/volume hello-world
        CMD="docker cp docker_volume_cp:/volume/$VOL_PATH $HOST_PATH"
        #echo "$CMD"
        $CMD
        docker rm docker_volume_cp

elif [[ ${#SOURCE_ARR[@]} -eq 1 && ${#DEST_ARR[@]} -eq 2 ]]; then
        VOL=${DEST_ARR[0]}
        VOL_PATH=${DEST_ARR[1]}
        HOST_PATH=${SOURCE_ARR[0]}

        docker container create --name docker_volume_cp -v $VOL:/volume hello-world
        CMD="docker cp $HOST_PATH docker_volume_cp:/volume/$VOL_PATH"
        #echo "$CMD"
        $CMD
        docker rm docker_volume_cp
else
        echo "Usage:"
        echo " volume --> host: $0 VOLUME:VOL_PATH HOST_PATH"
        echo " host --> volume: $0 HOST_PATH VOLUME:VOL_PATH"
fi
```

**Comment by patcon** [comment]
Building on what @mvasin and @TeamDman offered:
`docker run --rm -v $PWD:/source -v my_volume:/dest --workdir /source tianon/true "cp myfile.txt /dest"`

**Comment by janusznoszczynski** [comment]
> Here's a one-liner that copies `myfile.txt` from current directory to `my_volume`:
> `docker run --rm -v $PWD:/source -v my_volume:/dest -w /source alpine cp myfile.txt /dest`

How to copy from container

> Here's a one-liner that copies `myfile.txt` from current directory to `my_volume`:
> `docker run --rm -v $PWD:/source -v my_volume:/dest -w /source alpine cp myfile.txt /dest`

How do copy from container to host in one line?

**Comment by tgallacher** [comment]
@janusznoszczynski, you should be able to use `docker cp` directly (or `docker container cp`, which is exactly the same). 

Assume you're running a container named `foobar` and you want a file named `myfile.txt` located at `/root`, you can simply run:

```sh
docker cp foobar:/root/myfile.txt /root
```

This will copy the `myfile.txt` onto your host at `/root/myfile.txt`. This also works with the container id, etc., which can be found using `docker container ls`.

More details listed here: https://docs.docker.com/engine/reference/commandline/cp/

**Comment by debuglevel** [comment]
> Here's a one-liner that copies `myfile.txt` from current directory to `my_volume`:
> `docker run --rm -v $PWD:/source -v my_volume:/dest -w /source alpine cp myfile.txt /dest`

From volume to host (into the current directory!):
`docker run --rm -v $PWD:/host -v docker-compose_monitoring-database:/volume -w /volume alpine cp monitoring.mv.db /host`

**Comment by AWieclawski** [comment]
and what about remove copied files after all inner procedures inside docker volume?

**Comment by kforner** [comment]
I improved a bit the script from @dorintt to avoid container name collisions, for example if executed concurrently.
Thanks again @dorintt for this really useful script.

```
#!/bin/bash

# borrowed from https://github.com/moby/moby/issues/25245
# improved not to use global name docker_volume_cp for the temp container name
# and refactored to look nicer ;)

SOURCE=$1
DEST=$2

SOURCE_ARR=(${SOURCE//:/ })
DEST_ARR=(${DEST//:/ })

if [[ ${#SOURCE_ARR[@]} -eq 2 && ${#DEST_ARR[@]} -eq 1 ]]; then
        VOL=${SOURCE_ARR[0]}
        VOL_PATH=${SOURCE_ARR[1]}
        HOST_PATH=${DEST_ARR[0]}

        id=$(docker container create  -v $VOL:/volume hello-world)
        CMD="docker cp $id:/volume/$VOL_PATH $HOST_PATH"
        #echo "$CMD"
        $CMD
        docker rm $id

elif [[ ${#SOURCE_ARR[@]} -eq 1 && ${#DEST_ARR[@]} -eq 2 ]]; then
        VOL=${DEST_ARR[0]}
        VOL_PATH=${DEST_ARR[1]}
        HOST_PATH=${SOURCE_ARR[0]}

        id=$(docker container create --name docker_volume_cp -v $VOL:/volume hello-world)
        CMD="docker cp $HOST_PATH $id:/volume/$VOL_PATH"
        #echo "$CMD"
        $CMD
        docker rm docker_volume_cp
else
        echo "Usage:"
        echo " volume --> host: $0 VOLUME:VOL_PATH HOST_PATH"
        echo " host --> volume: $0 HOST_PATH VOLUME:VOL_PATH"
fi

```

**Comment by psawa** [comment]
Any news about the native support of this feature? All related issues seem to be closed

**Comment by strunzoz** [comment]
I am surprised there isn't a service or background script here to detect media files inside the volume and move them to a host directory
