### ISSUE TITLE
Add support for "--volumes-from" option to "docker build"

### ISSUE THREAD

**Issue by belooussov** [docker/docker#25249]
"docker build" does not support *"--volumes-from"* directive/option (yet).

"docker build" already supports "--volume" directive, and adding support from "--volumes-from" would make things more consistent with "docker run".

This would allow me to create something like this:

Data Dockerfile:
```
FROM scratch
COPY hugeinstaller.run /hugeinstaller.run
```

build, and start the data container.
```
$ docker create -v /datacontainer --name installer foo/bar /bin/true
```
And build the target image:
```
$ docker build --volumes-from installer -t foo/bartender:latest .
```
Real Dockerfile:
```
FROM ubuntu:latest
MAINTAINER blah
# run the installer in full silent autoinstall mode
RUN /datacontainer/hugeinstaller.run --autoinstall --silent --full
CMD foo-bar.sh
```

**Comment by cpuguy83** [comment]
Docker does _not_ support `-v` or `--volume` on `docker build`.

**Comment by ChristianKniep** [comment]
The reason behind it is to make sure that `docker build` has no dependencies. If you mount some volumes from another container you would have to make sure it is started first and you have to make sure that you are allowed to mount it, as a build host might have multiple builds running at the same time, which are not supposed to interact with each other...

**Comment by thaJeztah** [comment]
As @cpuguy83 mentioned, docker does not have a`--volume` flag on `docker build`. Only the Red Hat fork of Docker has this.

I'm going to close this, because of that
