### ISSUE TITLE
Volume mount inadvertently creates bind

### ISSUE THREAD

**Issue by stevvooe** [docker/docker#25253]
If a service is created with the following mount command, a bind will be created, rather than a volume:

```
--mount type=volume,src=/mnt,dst=/mnt
```

This will result in mounting `/mnt` from the host filesystem onto `/mnt` in the container. The expected behavior is for this to be an error.

@thaJeztah @cpuguy83 @gkze

**Comment by cpuguy83** [comment]
Working on this one.

**Comment by jhorwit2** [comment]
@stevvooe @cpuguy83 

What would be the expected way to turn 
```
sudo docker run \
  --volume=/:/rootfs:ro \
  --volume=/var/run:/var/run:rw \
  --volume=/sys:/sys:ro \
  --volume=/var/lib/docker/:/var/lib/docker:ro \
  --publish=8080:8080 \
  --detach=true \
  --name=cadvisor \
  google/cadvisor:latest
```

into a global service after this ticket? 

The command I ran in the past pre 1.12.1 was 

```
docker service create \
	--mode global \
	--mount type=volume,source=/,target=/rootfs,readonly=true \
	--mount type=volume,source=/var/run,target=/var/run \
	--mount type=volume,source=/sys,target=/sys,readonly=true \
	--mount type=volume,source=/var/lib/docker/,target=/var/lib/docker,readonly=true \
	--network backend \
	--name cadvisor \
	--publish 8080:8080 \
	google/cadvisor:latest
```
which worked fine but now errors.

**Comment by cpuguy83** [comment]
@jhorwit2 `type=bind`

**Comment by jhorwit2** [comment]
💥  Thanks for the quick reply. That worked!
