### ISSUE TITLE
docker image spec 1.1 does not include HEALTHCHECK location

### ISSUE THREAD

**Issue by jbayer** [docker/docker#25260]
**Describe the results you received:**

in [this twitter post](https://twitter.com/solomonstre/status/759342485483184128) @shykes mentions that docker image format now includes [HEALTHCHECK](https://docs.docker.com/engine/reference/builder/#healthcheck) information, so i expected the docker image spec to contain a reference to it, but when i looked it did not.
 
**Describe the results you expected:**

i expected to see supported docker image attributes to be specified and documented.

**Comment by icecrime** [comment]
Thanks for the report, you're absolutely right it should be reflected in the spec.

**Comment by jbayer** [comment]
out of curiosity, do you anticipate that this will follow a [semantic versioning ](http://semver.org/) approach and therefore bump the docker image version to 1.2?

**Comment by thaJeztah** [comment]
ping @aaronlehmann @stevvooe could one of you have a look?

**Comment by stevvooe** [comment]
`HEALTHCHECK` is actually a `Dockerfile` command. I assume you're referring to the [`container.Config.Healthcheck` field](https://github.com/docker/engine-api/blob/master/types/container/config.go#L49).

@talex5 Please update the specification with the the healthcheck fields.

> therefore bump the docker image version to 1.2?

@jbayer Yes, although this will only affect the document, as this is backwards compatible change.

**Comment by jbayer** [comment]
@stevvooe yes, i was referencing the Healthcheck field that gets set from the HEALTHCHECK in the Dockerfile. thank you for the response.

**Comment by talex5** [comment]
Yep, I'll update this (back from holiday now).
