### ISSUE TITLE
Is it possible to use 1.12 internal kv store to save custom values?

### ISSUE THREAD

**Issue by ypjin** [docker/docker#25274]
Hi, This is just a question. 
I'm playing with swarm mode and it's supposed that there is a kv store in my project. Consul was used previously. Since Swarm mode has its own kv store to keep cluster state just wondering if it's possible to store app state in it.

Any comments are greatly appreciated!

Best regards,

**Comment by jeromepin** [comment]
Hi,

I guess it's a similar question as this one : https://github.com/docker/docker/issues/24664 ?

**Comment by ypjin** [comment]
Hi @jeromepin, thanks for the link! It is related, but #24664 asked only for the way to read data from the internal kv store. I'm also curious if it's possible to write app state to it.

Best regards,

**Comment by thaJeztah** [comment]
No, writing custom data to the internal k/v store is not supported; it's only used for the internal state of Swarm

**Comment by ypjin** [comment]
@thaJeztah, Thanks for the clarification!
