### ISSUE TITLE
Under docker swarm mode,network can not be "host"?

### ISSUE THREAD

**Issue by JunJiangWang** [docker/docker#25276]
Hi,I just have a question.When I use docker swarm(version 1.12),I found that I can not create a service with '--network host'.
The command is "docker service create --name test --network host redis redis-server" ,and the error is "Error response from daemon: network host is not eligible for docker services".
Any comments are greatly appreciated!

**Comment by discoverkl** [comment]
I have the same problem too.
```
# docker service create --name demo --network host iso:8080/alpine /bin/sh    
Error response from daemon: network host is not eligible for docker services
```
**We REALLY need '--net host' in Docker Swarm**, because iptables's NAT module is missing in out company, for security reasons.

**Comment by vayasin** [comment]
Is this by design or not yet implemented?

+1 need this too.

**Comment by epicsoft-de** [comment]
+1
