### ISSUE TITLE
arguments expanded in ENV

### ISSUE THREAD

**Issue by justincormack** [docker/docker#25281]
```
FROM busybox
ARG ORANGE=BANANA
ENV $ORANGE=PLUM
RUN echo $BANANA
```

building this outputs `PLUM`. In fact `$ORANGE` is a valid environment variable name (they are arbitrary strings), and should not have been expanded.

Discovered during https://github.com/docker/docker/issues/25099

**Comment by duglin** [comment]
ping @tianon 

using this:
```
$ cat a.sh
export ORANGE=BANANA
export $ORANGE=PLUM
echo $BANANA
```
I see PLUM as well and if I remember correctly we were trying to match what sh would do.

If you wanted "$" to be part of the name, shouldn't you have to escape it? When I do that, I then see `$ORANGE` in the env list during a `RUN env`

**Comment by thaJeztah** [comment]
@duglin yes, @justincormack and I were discussing this and actually weren't sure if this was by *design* or something that got in "by accident"

**Comment by justincormack** [comment]
@duglin this came up from https://github.com/docker/docker/issues/25099 with

```
FROM scratch
ENV =
RUN .
```

which is definitely broken...

**Comment by duglin** [comment]
Well, that's just weird from a testcase perspective as well as docker code perspective  :-)

**Comment by duglin** [comment]
@justincormack created #25300 for it
