### ISSUE TITLE
docs: inspect service tutorial is out of sync

### ISSUE THREAD

**Issue by djalal** [docker/docker#25286]
my first opened issue, easy one for @SvenDowideit / @thaJeztah 👍 

**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc5
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   a3f2063
 Built:        Tue Jul 26 13:13:32 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc5
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   a3f2063
 Built:        Tue Jul 26 13:13:32 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.0-rc5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 3
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: active
 NodeID: cp23gcyqaj8th7sj9h80v3mvv
 Is Manager: true
 Managers: 3
 Nodes: 6
 Node Address: 10.3.116.9
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 4.5.7-docker-4
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.954 GiB
Name: scw-manager1
ID: HY4W:YVYI:G3DB:NHLD:3WUM:HAFE:ZY2E:BSMN:DFC7:RWXN:TOAY:H4YC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=scaleway(VC1S)
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Follow the ["Get started with swarm mode"](https://docs.docker.com/engine/swarm/swarm-tutorial/) tutorial
2. When at the third page ["Inspect a service on the swarm"](https://docs.docker.com/engine/swarm/swarm-tutorial/inspect-service/), follow steps 1. and 2.
3. at third step, run `docker service ps <SERVICE-ID>` to see which nodes are running the service

**Describe the results you received:**
```
Usage:	docker service COMMAND

Manage Docker services

Options:
      --help   Print usage

Commands:
  create      Create a new service
  inspect     Display detailed information on one or more services
  tasks       List the tasks of a service
  ls          List services
  rm          Remove a service
  scale       Scale one or multiple services
  update      Update a service

Run 'docker service COMMAND --help' for more information on a command.
exit status 1
```

**Describe the results you expected:**

```
ID                         NAME          SERVICE     IMAGE   LAST STATE         DESIRED STATE  NODE
8p1vev3fq5zm0mi8g0as41w35  helloworld.1  helloworld  alpine  Running 3 minutes  Running        worker2
```

**Additional information you deem important (e.g. issue happens only occasionally):**

The following provides the expected output : `docker service tasks helloworld`

```
ID                         NAME          IMAGE   NODE          DESIRED STATE  CURRENT STATE           ERROR
2mmcc0hkjsf3pq09yjl1tct9t  helloworld.1  alpine  scw-manager1  Running        Running 41 minutes ago
```

**Comment by thaJeztah** [comment]
Looks like you're running RC5; the `tasks` command was renamed to `ps` in the GA release, so this should be resolved after updating to docker 1.12.0

I'll close this issue, but feel free to continue the conversation; thanks for reporting 👍

**Comment by djalal** [comment]
easy one, indeed ^^

**Comment by djalal** [comment]
@thaJeztah in that case, we may have an issue about using "https://test.docker.com" with the `--engine-install-url` in `docker-machine`. I would expect the latest version, whether RC or GA. Why is it stucked in RC5 if GA is more recent ?

**Comment by thaJeztah** [comment]
@djalal "test.docker.com" only is used to publish release-candidates, but not final releases (the install script on that domain uses the `testing` apt/yum repositories. You can use https://get.docker.com to get the GA release, or update your configuration to use the "main" repository (see step 6 below https://docs.docker.com/engine/installation/linux/debian/#/update-your-apt-repository)
