### ISSUE TITLE
Mount point with curlftpfs causes permission denied

### ISSUE THREAD

**Issue by arnishow** [docker/docker#25297]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:46:40 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:46:40 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 9
 Running: 9
 Paused: 0
 Stopped: 0
Images: 10
Server Version: 1.12.0
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 5.446 GB
 Data Space Total: 102 GB
 Data Space Available: 96.55 GB
 Metadata Space Used: 1.692 MB
 Metadata Space Total: 2.143 GB
 Metadata Space Available: 2.142 GB
 Thin Pool Minimum Free Space: 10.2 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.130 (2016-07-06)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.6.0-1-amd64
Operating System: Debian GNU/Linux stretch/sid
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.847 GiB
Name: jupiter
ID: C7OV:3WYG:HPJP:YFUV:OAEH:Q6PJ:ZQDT:HV3G:2LCP:EKNY:NO4Z:K3ER
Docker Root Dir: /docker/755360.755360
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Mount remote directory using curlftpfs like
`curlftpfs -r 192.168.1.1 /docker/share/test`

2. Use userns-remap for docker daemon

3. Run container with mount point like
`docker run -it --rm -v /docker/share:/test debian:jessie /bin/bash`

4. Try to access this mount point

**Describe the results you received:**
I got permission denied with the mounted point.

`root@ef4cc340f2a2:/# ls -alh /`
`drwxr-xr-x   3 nobody nogroup 4.0K Aug  1 14:07 test`

`root@ef4cc340f2a2:/# ls -alh /test/`
`drwxr-xr-x  3 nobody nogroup 4.0K Aug  1 14:07 .`
`drwxr-xr-x 22 root   root     254 Aug  1 15:42 ..`
`d?????????  ? ?      ?          ?            ? test`

`root@ef4cc340f2a2:/# ls -alh /test/test`
`ls: cannot access /test/test: Permission denied`

**Describe the results you expected:**
Expect to have access to the mounted point.

**Additional information you deem important (e.g. issue happens only occasionally):**

This test works good when using cifs mount.

Best regards,

**Comment by thaJeztah** [comment]
Isn't this expected? With userns, "root" inside the container is an unprivileged user outside the container; that way, a user inside the container cannot do harm on the host, even if it obtains access (in this situation, through a mounted directory)

**Comment by arnishow** [comment]
I agree with you and what userns does, but I can mount directory with read-only permission on other situation.
In my example, I mount /docker/share with success but I can't access the specific directory "test" which contains the remote directory. This situation appears only with curlftpfs.

**Comment by arnishow** [comment]
I finally found what was the problem ; as suggested, just use -o allow_other with curlftpdfs.
