### ISSUE TITLE
docker service create --user does not support "group" / "gid"

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#25304]
Unlike `docker run`, the `--user` flag for services does not currently support `:group` or `:gid`, so the following will currently fail:

    docker service  create --user 123:456 --name foobar nginx

I think we should either support the same syntax as on `docker run`, or provide a `--group` / `--gid` flag

/cc @stevvooe @aluzzardi

**Comment by stevvooe** [comment]
@thaJeztah Why would this ever be in the same flag? Let's add a group flag/field across the board.

**Comment by thaJeztah** [comment]
@stevvooe I assume it was implemented like that  on `docker run` to reflect `chown uid:gid`

> Let's add a group flag/field across the board

You mean; same for `docker run` (but keep `uid:gid` for backward compatibility?)

**Comment by stevvooe** [comment]
@thaJeztah I can't support a model that has `--user` support `uid:gid` syntax. This kind of overloading just leads to fragile behavior.

These need to be opaque to the operating system. Let's just add a `--group` flag and be done with it.

**Comment by thaJeztah** [comment]
My point was that we already have that syntax for `docker run`; so if we want to change it; better do it for both `docker run` and `docker service create`  / `update`. It'll be a breaking change though if we remove the feature for `docker run`, so that will take 2 .. 3 releases to remove

**Comment by stevvooe** [comment]
@thaJeztah Again, services are different from containers. While we should leverage common behavior, we should avoid importing poorly thought through micro-formats.

In fact, we can already see the problems with `docker run` style flags by looking at the additions:

```
      --group-add value             Add additional groups to join (default [])
  -u, --user string                 Username or UID (format: <name|uid>[:<group|gid>])
```

Wow. What happened here? Presumably, `--user uid:gid` sets the primary/real/effective user id for the process. When it was realized this was insufficient, it looks like supplementary group support was added. (I'd have to look into the implementation to confirm this).

We can probably do two possible things:

1. Support `uid:gid` syntax -- this should be okay cross-platform, but I am not sure if windows or other platforms use colons. `gid` becomes the primary/egid/real gid for the process. We still need to have a multi-option `--group` to add supplementary groups.
2. Split these properly into `--user` and `--group`. First appearance of `--group` becomes primary group id. This suffers from the problem of always overriding primary group if _any_ group is specified.

Option 1 is probably better, but I really don't like creating micro-formats for cross-platform concepts that are already confusing enough.

None of this has to break `docker run`.

Let's be careful with the requirement of making `docker service` work like `docker run`. We start getting problems that we created services for in the first place.

**Comment by yongtang** [comment]
@thaJeztah @stevvooe It seems that currently `--user` support `uid:did` already. I created a pull request #25317 to support a new flag `--group` that will place additional groups to `GroupAdd` (`--group-add`). Not sure this is the best way to handle it but I am open to any suggestions.

**Comment by thaJeztah** [comment]
Haha, @yongtang is actually right, looks like I had my notes wrong, and just happened to pick the wrong image; `docker service create` *does* indeed support `user:group`, but the `nginx` image doesn't support running as a non-privileged user (it already drops back to a non-privileged user after the entrypoint script is finished.

So this issue is complete PEBKAC (but requires an update in the documentation)

We can still discuss adding a `--group` option in https://github.com/docker/docker/issues/25317, but I'll close this issue

**Comment by stevvooe** [comment]
@thaJeztah @yongtang  How is this possibly supported? Are we shoving this completely undocumented micro-format into the API field?

OMG: it is buried in libcontainer. We need to get this documented on engine-api and swarmkit.

**Comment by stevvooe** [comment]
Filed #1300

**Comment by stevvooe** [comment]
Filed https://github.com/docker/engine-api/pull/346.

**Comment by thaJeztah** [comment]
@stevvooe I think the syntax has been there since before 1.6 (at least 1.6 supports it)

**Comment by stevvooe** [comment]
@thaJeztah And yet, we've never documented on any API protocol and the parsing is buried deep within libcontainer.

**Comment by yongtang** [comment]
@stevvooe @thaJeztah Thanks for the updates in engine-api and swarmkit. I updated the pull request #25317 based on the updates in engine-api and swarmkit from @stevvooe.

Please take a look and let me know if there are any issues.

Also, I used `--group` for the flag name before. Now it looks like we are stuck with the `--user=uid:gid` and supplement groups in libcontainerd, would it make sense to use `--group-add` instead?

**Comment by thaJeztah** [comment]
`--group-add` adds *additional* groups for the user, not the primary group, so I'm not sure they're interchangeable. This will become confusing though, it we want to implement this in `docker service update`, where we use `--xx-add` / `--xx-rm` to add/remove options for flags that support multiple values.

**Comment by stevvooe** [comment]
@thaJeztah The primary/real/effective group for the _process_, not the user, is set by the `foo:bar` syntax. The `--group` flag would only add supplementary groups and support multiple values. `--group-add` is incorrect, since it is not actually adding groups to the user.

**Comment by tianon** [comment]
Just FYI, the microformat for `--user` has been in place since before Docker 1.0 (just did a quick test against old Docker-in-Docker images to verify that it worked as expected all the way back to 1.0 too with `--user 123:456` running `id` in `busybox`).
