### ISSUE TITLE
Run Docker integration tests without -cover

### ISSUE THREAD

**Issue by aaronlehmann** [docker/docker#25313]
The Docker integration tests are run with the -cover flag. This seems useful for unit tests, so one can see how much of the code is being covered by the tests. However, the integration tests work against a precompiled daemon, so the coverage information is not useful. The downside of enabling coverage is that it manipulates the source files before compiling them, so the line numbers don't match up with the code in source control. This makes debugging failures from CI difficult. It probably also slows down the tests.

I suggest removing `-cover` from the integration test command line, or if there's a compelling reason to keep it, provide a variant of test-integration-cli that disables coverage reporting.

**Comment by icecrime** [comment]
WDYT @tonistiigi @vdemeester?

**Comment by stevvooe** [comment]
For the most part, this is probably the right thing to do, unless there is a way to make this data useful. In general, coverage output doesn't seem to be useful for integration tests.

Too make this useful, we'd need the following:

1. Coverage source maps. They must exist _somewhere_ but it looks like they may only exist during unit test run.
2. Merge coverage runs across several different test instantiations.

My guess this is probably too complicated to achieve and it is more worthwhile to have correct errors from integration tests.

**Comment by tonistiigi** [comment]
@tiborvass Didn't you work on making the integration tests coverage more useful a while back?

**Comment by tiborvass** [comment]
@tonistiigi yes but this issue is about a side effect of -cover that makes the line numbers be off, so it's a go issue. I'd be happy to get back the work I started on coverage for integration tests, but I feel like it would make things even slower.

**Comment by thaJeztah** [comment]
Also see https://github.com/docker/docker/pull/23559, and https://github.com/docker/docker/issues/22899#issuecomment-232757617, which may be relevant here

**Comment by vdemeester** [comment]
SGTM to remove `-cover` for integration tests :angel:
