### ISSUE TITLE
Docker swarm mode network issue between 1.12.0-rc4 and rc5/final

### ISSUE THREAD

**Issue by jalmansor** [docker/docker#25311]
I've been trying to set up a selenium grid using docker swarm mode and ran into some issues between rc4 and rc5/final.  To create the selenium grid I'm running:

```
docker network create -d overlay selenium-grid
docker service create --network selenium-grid --name hub -p 4444:4444 selenium/hub
docker service create --network selenium-grid --name chrome --mount type=bind,source=/dev/shm,target=/dev/shm -e HUB_PORT_4444_TCP_ADDR=hub -e HUB_PORT_4444_TCP_PORT=4444 -p 5555:5555 --replicas 10 selenium/node-chrome
```

In 1.12.0-rc4: 

```
root@ubuntu-2gb-nyc1-01:~# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: active
 NodeID: 538oo623muxkeox6n31c2oa8m
 IsManager: Yes
 Managers: 1
 Nodes: 1
 CACertHash: sha256:9440216e0ba548f049da1c3a77ddc9499c14d96d54d9a8f82995d1ec6a510e49
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.954 GiB
Name: ubuntu-2gb-nyc1-01
ID: 6GAB:5NIT:N6MZ:WL3K:HEO2:6FXD:ODWK:CAZO:ECTC:ZORR:W5BI:52HH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```
I get the following output from the selenium hub showing the Chrome nodes coming up and registering:

```
root@ubuntu-2gb-nyc1-01:~# docker logs -f hub.1.drmliujhr035rp9gp9g24b8a5
starting selenium hub with configuration:

{
  "host": null,
  "port": 4444,
  "prioritizer": null,
  "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
  "throwOnCapabilityNotPresent": true,
  "newSessionWaitTimeout": -1,
  "jettyMaxThreads": -1,
  "nodePolling": 5000,
  "cleanUpCycle": 5000,
  "timeout": 30000,
  "browserTimeout": 0,
  "maxSession": 5,
  "unregisterIfStillDownAfter": 30000
}
23:06:46.696 INFO - Launching Selenium Grid hub
2016-08-01 23:06:47.399:INFO::main: Logging initialized @857ms
23:06:47.413 INFO - Will listen on 4444
23:06:47.482 INFO - Will listen on 4444
2016-08-01 23:06:47.487:INFO:osjs.Server:main: jetty-9.2.z-SNAPSHOT
2016-08-01 23:06:47.519:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@150c158{/,null,AVAILABLE}
2016-08-01 23:06:47.534:INFO:osjs.ServerConnector:main: Started ServerConnector@405c4ccd{HTTP/1.1}{0.0.0.0:4444}
2016-08-01 23:06:47.534:INFO:osjs.Server:main: Started @992ms
23:06:47.535 INFO - Nodes should register to http://10.0.0.3:4444/grid/register/
23:06:47.535 INFO - Selenium Grid hub is up and running
23:07:48.113 INFO - Registered a node http://10.0.0.10:5555
23:07:48.365 INFO - Registered a node http://10.0.0.11:5555
23:07:49.269 INFO - Registered a node http://10.0.0.5:5555
23:07:49.426 INFO - Registered a node http://10.0.0.12:5555
23:07:49.536 INFO - Registered a node http://10.0.0.14:5555
23:07:49.598 INFO - Registered a node http://10.0.0.9:5555
23:07:49.644 INFO - Registered a node http://10.0.0.6:5555
23:07:49.655 INFO - Registered a node http://10.0.0.7:5555
23:07:49.918 INFO - Registered a node http://10.0.0.8:5555
23:07:50.240 INFO - Registered a node http://10.0.0.13:5555
```

In rc5 and the final release:

```
root@ubuntu-2gb-nyc1-02:~# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host overlay bridge
Swarm: active
 NodeID: bmd9fnp3gegfivticsu2k6exh
 Is Manager: true
 ClusterID: esuejhyu69u7pg4kmbkvlfpku
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot interval: 10000
  Heartbeat tick: 1
  Election tick: 3
 Dispatcher:
  Heartbeat period: 5 seconds
 CA configuration:
  Expiry duration: 3 months
 Node Address: 198.199.73.19
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.954 GiB
Name: ubuntu-2gb-nyc1-02
ID: 7EAI:CBDR:OB4L:5XDQ:6ZUP:IFFG:RQ7Y:EXAF:G3QW:Z3NO:JGNE:5M6Q
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

The hub output shows the replicas as having the same IP:

```
root@ubuntu-2gb-nyc1-02:~# docker logs -f hub.1.9v00y06jzo7rwqz74ja0bklpe
starting selenium hub with configuration:

{
  "host": null,
  "port": 4444,
  "prioritizer": null,
  "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
  "throwOnCapabilityNotPresent": true,
  "newSessionWaitTimeout": -1,
  "jettyMaxThreads": -1,
  "nodePolling": 5000,
  "cleanUpCycle": 5000,
  "timeout": 30000,
  "browserTimeout": 0,
  "maxSession": 5,
  "unregisterIfStillDownAfter": 30000
}
23:16:40.095 INFO - Launching Selenium Grid hub
2016-08-01 23:16:40.868:INFO::main: Logging initialized @974ms
23:16:40.883 INFO - Will listen on 4444
23:16:40.949 INFO - Will listen on 4444
2016-08-01 23:16:40.954:INFO:osjs.Server:main: jetty-9.2.z-SNAPSHOT
2016-08-01 23:16:40.987:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@150c158{/,null,AVAILABLE}
2016-08-01 23:16:41.004:INFO:osjs.ServerConnector:main: Started ServerConnector@727803de{HTTP/1.1}{0.0.0.0:4444}
2016-08-01 23:16:41.006:INFO:osjs.Server:main: Started @1112ms
23:16:41.007 INFO - Nodes should register to http://10.0.0.2:4444/grid/register/
23:16:41.007 INFO - Selenium Grid hub is up and running
23:17:23.114 INFO - Registered a node http://10.0.0.4:5555
23:17:24.979 INFO - Registered a node http://10.0.0.4:5555
23:17:24.987 WARN - Cleaning up stale test sessions on the unregistered node http://10.0.0.4:5555
23:17:26.863 INFO - Registered a node http://10.0.0.4:5555
23:17:26.864 WARN - Cleaning up stale test sessions on the unregistered node http://10.0.0.4:5555
23:17:26.878 INFO - Registered a node http://10.0.0.4:5555
23:17:26.879 INFO - Registered a node http://10.0.0.4:5555
23:17:26.885 INFO - Registered a node http://10.0.0.4:5555
23:17:26.886 WARN - Cleaning up stale test sessions on the unregistered node http://10.0.0.4:5555
23:17:26.888 WARN - Cleaning up stale test sessions on the unregistered node http://10.0.0.4:5555
23:17:26.888 INFO - Registered a node http://10.0.0.4:5555
23:17:26.889 INFO - Registered a node http://10.0.0.4:5555
23:17:26.903 WARN - Cleaning up stale test sessions on the unregistered node http://10.0.0.4:5555
23:17:26.905 INFO - Registered a node http://10.0.0.4:5555
23:17:26.906 WARN - Cleaning up stale test sessions on the unregistered node http://10.0.0.4:5555
23:17:26.912 WARN - Cleaning up stale test sessions on the unregistered node http://10.0.0.4:5555
23:17:26.914 WARN - Cleaning up stale test sessions on the unregistered node http://10.0.0.4:5555
23:17:26.918 INFO - Registered a node http://10.0.0.4:5555
23:17:26.923 WARN - Cleaning up stale test sessions on the unregistered node http://10.0.0.4:5555
```

I'm not sure if what I'm seeing is expected behavior for the final release, but any guidance would be appreciated.

**Comment by thaJeztah** [comment]
Could `10.0.0.4` be the virtual-IP of the `node` *service*? The containers of a service are behind a load-balancer, If each container in the `node` service tries to register, they all go through the same virtual-ip

**Comment by jalmansor** [comment]
That's what I was thinking as well, but I was having a hard time trying to find what changed between rc4 and rc5 and if there's a better way to handle this type of scenario in swarm mode.

**Comment by jalmansor** [comment]
I *think* I may have found a solution. If I create the network with --internal, create the hub service the same as before, but create the chrome service with --endpoint-mode dnsrr, all the containers come online as they did in rc4. Without creating the network as internal, I wasn't able to ping the chrome containers from the hub, but with it I can.

**Comment by thaJeztah** [comment]
So, without `--internal` but **with** `--endpoint-mode=dnsrr`, it doesn't work? Hm, that's strange.

DNSRR sounds like the good option here, because you want to communicate with each container individually, IIUC

**Comment by jalmansor** [comment]
Correct, they come up as if they're all from the service VIP. The only way it seems to work is by using --internal when the network is created, which I didn't think was a requirement for containers in the same overlay network to communicate.

**Comment by thaJeztah** [comment]
ping @mrjana could you have a look? I don't understand either why `--internal` should make a difference here

**Comment by jalmansor** [comment]
Well, after I had one of our devs try to use the cluster I realized that --internal will prevent the non-exposed containers from reaching outside that network, so they can't hit the containers in our build environment that they need to test against 😫 

Still digging into the docs to get more info on how the network layers work and see if there's a way to get this working with swarm mode, as the scaling functionality is insanely useful.

**Comment by mavenugo** [comment]
@jalmansor @thaJeztah The only functionality provided by `--internal` is to isolate the containers from external-world. I dont quite understand the rest of the discussion as the commands mentioned in the description doesn't match the issue being discussed.

Could you please share all the commands that you use and your expectations so that we can clarify if it is an issue or expected behavior.

**Comment by sanimej** [comment]
@jalmansor Can you explain how the selenium hub identifies all the IPs of the chrome tasks ? Is it using some sort of in-built mechanism or Docker service discovery is used ? Even with RC4 unless the service is created `--endpoint-mode=dnsrr` Docker service discovery will return only the VIP.

**Comment by jalmansor** [comment]
@mavenugo the commands are above in my opening post. I've been trying to find the right configuration where the hub and the chrome containers can communicate back and forth while still making use of swarm mode to make scaling the chrome containers easier. So far that doesn't seem possible, even with using `--endpoint-mode dnsrr`.

@sanimej the selenium chrome instances initiate the connection to the hub by specifying the hub's address and port via environment variables, which I've just been using the DNS for the hub container. When I use `--endpoint-mode dnsrr` for the chrome service the hub I get:

```
root@test1:~# docker logs -f hub.1.8lamkko63rh1xr2jq1pvff4et
starting selenium hub with configuration:

{
  "host": null,
  "port": 4444,
  "prioritizer": null,
  "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
  "throwOnCapabilityNotPresent": true,
  "newSessionWaitTimeout": -1,
  "jettyMaxThreads": -1,
  "nodePolling": 5000,
  "cleanUpCycle": 5000,
  "timeout": 30000,
  "browserTimeout": 0,
  "maxSession": 5,
  "unregisterIfStillDownAfter": 30000
}
20:24:20.130 INFO - Launching Selenium Grid hub
2016-08-08 20:24:21.088:INFO::main: Logging initialized @1163ms
20:24:21.103 INFO - Will listen on 4444
20:24:21.167 INFO - Will listen on 4444
2016-08-08 20:24:21.172:INFO:osjs.Server:main: jetty-9.2.z-SNAPSHOT
2016-08-08 20:24:21.218:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@150c158{/,null,AVAILABLE}
2016-08-08 20:24:21.244:INFO:osjs.ServerConnector:main: Started ServerConnector@727803de{HTTP/1.1}{0.0.0.0:4444}
2016-08-08 20:24:21.249:INFO:osjs.Server:main: Started @1325ms
20:24:21.250 INFO - Nodes should register to http://10.0.0.2:4444/grid/register/
20:24:21.251 INFO - Selenium Grid hub is up and running
20:25:55.870 INFO - Registered a node http://172.18.0.5:5555
20:25:55.883 INFO - Registered a node http://172.18.0.4:5555
20:30:20.506 INFO - Marking the node http://172.18.0.5:5555 as down: cannot reach the node for 2 tries
20:30:20.507 INFO - Marking the node http://172.18.0.4:5555 as down: cannot reach the node for 2 tries
```

If I `docker exec` into the hub container and check the interfaces and routing table I get:

```
root@773f297637a4:~# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
13: eth2@if14: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default
    link/ether 02:42:0a:00:00:03 brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet 10.0.0.3/24 scope global eth2
       valid_lft forever preferred_lft forever
    inet 10.0.0.2/32 scope global eth2
       valid_lft forever preferred_lft forever
    inet6 fe80::42:aff:fe00:3/64 scope link
       valid_lft forever preferred_lft forever
15: eth1@if16: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:ac:12:00:03 brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet 172.18.0.3/16 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe12:3/64 scope link
       valid_lft forever preferred_lft forever
17: eth0@if18: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default
    link/ether 02:42:0a:ff:00:05 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.255.0.5/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet 10.255.0.4/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:aff:feff:5/64 scope link
       valid_lft forever preferred_lft forever

root@773f297637a4:~# netstat -rn
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         172.18.0.1      0.0.0.0         UG        0 0          0 eth1
10.0.0.0        0.0.0.0         255.255.255.0   U         0 0          0 eth2
10.255.0.0      0.0.0.0         255.255.0.0     U         0 0          0 eth0
172.18.0.0      0.0.0.0         255.255.0.0     U         0 0          0 eth1
```
and from one of the chrome containers:
```
root@c63ad3e37356:~# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
19: eth0@if20: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default
    link/ether 02:42:0a:00:00:04 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.0.0.4/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:aff:fe00:4/64 scope link
       valid_lft forever preferred_lft forever
23: eth1@if24: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:ac:12:00:04 brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet 172.18.0.4/16 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe12:4/64 scope link
       valid_lft forever preferred_lft forever

root@c63ad3e37356:~# netstat -rn
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         172.18.0.1      0.0.0.0         UG        0 0          0 eth1
10.0.0.0        0.0.0.0         255.255.255.0   U         0 0          0 eth0
172.18.0.0      0.0.0.0         255.255.0.0     U         0 0          0 eth1
```
So it seems like a routing issue, since the Chrome containers seem to be registering with the hub using the IP from the docker gateway and not the overlay network.

**Comment by jalmansor** [comment]
@sanimej if you look above at my example from rc4, you'll see that all the Chrome nodes come online by exposing the ports and not using dnsrr. If I attach to the hub container and install ping, I'm able to ping the IP's of the Chrome containers that the hub logs as connected. Something that went into rc5 changed the way this behaves, because I'm easily able to stand up a couple fresh Ubuntu 14.04 VM's in DO and replicate these results by installing rc4 and rc5 (or final) using all the default docker settings and running the three commands I listed in my original post.

**Comment by iamthemuffinman** [comment]
I've tested @jalmansor's original commands in rc4 and rc5. In rc4 the chrome containers are registering with the hub on their overlay IP. In rc5/final, the chrome containers are registering with the hub on their service VIP. I believe what @jalmansor is saying is that the rc4 way of doing it is correct. @thaJeztah @mavenugo @sanimej Is the rc4 behaviour correct? Or the rc5/final way?

**Comment by jalmansor** [comment]
I finally got this working right using `--endpoint-mode dnsrr` for the Chrome service and passing them an env var to make them register with the IP from the overlay network and not the bridge. So this ended up being the setup:

```
docker network create -d overlay selenium-grid
docker service create --network selenium-grid --name hub -p 4444:4444 selenium/hub
docker service create --network selenium-grid --endpoint-mode dnsrr --name chrome --mount type=bind,source=/dev/shm,target=/dev/shm -e HUB_PORT_4444_TCP_ADDR=hub -e HUB_PORT_4444_TCP_PORT=4444 --replicas 10 selenium/node-chrome bash -c 'HOSTIP=$(ip -4 addr show eth0 | grep -Po "inet \K[\d.]+") REMOTE_HOST=http://$HOSTIP:5555 /opt/bin/entry_point.sh'
```
It would still be nice to know what changed to cause such a difference in the way exposed ports work with overlay networks after rc4.

**Comment by sanimej** [comment]
@jalmansor In RC5 we made a change to add the service VIP as a secondary IP to the interface. This was done to allow ping to the VIP work. This might be the reason for the behavior change. But in the dnsrr mode VIP will not be allocated. With 1.12 I will give it a try with the selenium hub & node commands you are using.

**Comment by jalmansor** [comment]
@sanimej, I'm assuming that the reason the Chrome nodes pick the IP from the docker_gwbridge is because that's the default route, not the overlay network. I'm not sure how much of that configuration is controlled by Docker, but it would seem to me that you'd want the overlay network to be the default, though my networking knowledge is a little rusty.  But I really appreciate you giving this a look.

**Comment by sanimej** [comment]
@jalmansor For containers on overlay networks external access outside of the overlay network is through the docker_gwbridge. That is why it is setup as default route.

`I'm assuming that the reason the Chrome nodes pick the IP from the docker_gwbridge is because that's the default route, not the overlay network`

This doesn't seem to the case. Because in the default VIP mode (which you used in RC4) also the default route is the same, pointing to the docker_gwbridge interface. But in RC4 chrome nodes registered with the IP on the overlay network. So the chrome nodes are not using the interface of the default route.

This is the pattern I am noticing though; in the VIP mode there are three interfaces with eth2 being the interface connected to the overlay network. In DNSRR mode there are two interfaces (there is no `-p` in this mode) with eth1 being the interface connected to docker_gwbridge. So it looks like chrome modes are using the highest ethernet interface IP to register with the hub. Please check specifically how chrome nodes are determining the IP to register with the hub.

**Comment by jalmansor** [comment]
@sanimej thanks for the follow up. I'm not sure how they're determining that, though the env var to tell the Chrome nodes which IP to register with seems to be working well with DNSRR, so I don't think there's anything left to do here since the issue isn't really with Docker. This did, however, make me aware of another issue where if the hosts in the cluster go down, when they come back up the exposed hub service is only accessible on the node it's running on and not the entire cluster, but I'll open a new issue for that after I do more digging.

**Comment by sanimej** [comment]
@jalmansor For the new issue you mentioned please try with 1.12.1-RC2 (1.12.1 release should happen this week). If you still see the problem go ahead and open an issue with the details.

**Comment by jalmansor** [comment]
Awesome! Thank you for pointing that out, that RC slipped by me. I'll be testing that tomorrow!

**Comment by jalmansor** [comment]
@sanimej that solved the other problem. YAY!
