### ISSUE TITLE
Can't override PORT with different IP address

### ISSUE THREAD

**Issue by martin-magakian** [docker/docker#25323]
**Steps to reproduce the issue:**
1- edit docker-compose.yml
```
version: '2'
services:
  db:
    image: mysql:5.7
    ports:
      - "0.0.0.0:3306:3306"
    restart: always
```
2- edit docker-compose.prod.yml
  ```
version: '2'
services:
  db:
    ports:
      - "127.0.0.1:3306:3306"
  ```
3- run
docker-compose -f docker-compose.prod.yml -f docker-compose.yml up

**Describe the results you received:**
Similar to issue [#3473](https://github.com/docker/compose/issues/3473), I'm getting the error `Error starting userland proxy: listen tcp 0.0.0.0:3306: bind: address already in use`

**Describe the results you expected:**
I'm expecting the `docker-compose.yml` to override the config. Therefore, it should listen on IP 127.0.0.1 and port 3306.

**Additional information you deem important (e.g. issue happens only occasionally):**
$ docker-compose -v:
docker-compose version 1.8.0, build f3628c7

$ docker ps
"no container running"

Similar to issue [#3473](https://github.com/docker/compose/issues/3473)

I don't have any container running
`docker ps`
```CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES```

**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:39 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:39 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 9
 Running: 5
 Paused: 0
 Stopped: 4
Images: 7
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker-9:2-44566442-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.385 GB
 Data Space Total: 107.4 GB
 Data Space Available: 105 GB
 Metadata Space Used: 5.042 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.142 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.90 (2014-09-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host
Kernel Version: 3.14.32-xxxx-grs-ipv6-64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.32 GiB
Name: ns363968.ip-91-121-183.eu
ID: K77X:SFJP:6GQ2:ZP7Y:K57R:LPBU:Y5H6:4NMC:HSAO:JNM6:WFD4:OU7H
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**docker-compose version**
physical

**Comment by cpuguy83** [comment]
I'm not sure what this command is expected to do, but this looks more like a compose issue.

**Comment by martin-magakian** [comment]
It looks like a docker-compose issue to me as well.
I moved the issue to docker-compose [#3801](https://github.com/docker/compose/issues/3801)

**Comment by cpuguy83** [comment]
Thanks!
