### ISSUE TITLE
Unmount to volume driver doesn't get the opaque ID.

### ISSUE THREAD

**Issue by govint** [docker/docker#25331]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-rc5
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   a3f2063
 Built:        Tue Jul 26 13:12:18 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc5
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   a3f2063
 Built:        Tue Jul 26 13:12:18 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 20
 Running: 0
 Paused: 0
 Stopped: 20
Images: 131
Server Version: 1.12.0-rc5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 267
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local vmdk
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 3.13.0-85-generic
Operating System: Ubuntu 14.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: hte-1s-eng-dhcp98
ID: H3SC:SAIV:HFHW:WYI5:WC4O:GEVQ:S6AJ:VIJ2:4CVT:UXDQ:T4GW:7MCA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 15
 Goroutines: 25
 System Time: 2016-08-02T07:09:33.178542061-07:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Create a volume
2. Run a container to use the volume (-v option)
3. DEbug logs in volume driver shows that mount gets an opaque ID while unmount doesn't.

**Describe the results you received:**

Unmount() to the volume driver doesn't get the opaque ID. For example my volume driver has logs to log the opaque ID and this is what I get,

2016-08-02 05:46:57.639380444 -0700 PDT [INFO] Mount - name="dvol_2" mount_id=85614e15d455401c92a9dedde9c21a07350404d302b6326181a699cf13809f2d

2016-08-02 05:47:18.662962842 -0700 PDT [INFO] Unmount - name="dvol_2" mount_id=

**Describe the results you expected:**

Per #21015 need to get the opaque ID on unmount, else how to match the unmount to a prior mount.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment]
Thanks, can you test with #25333?
