### ISSUE TITLE
docker 1.12 crash

### ISSUE THREAD

**Issue by osallou** [docker/docker#25339]
**Output of `docker version`:**

osallou@tifenn~ $ sudo docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:05:53 2016
 OS/Arch:      linux/amd64

**Output of `docker info`:**
osallou@tifenn~ $ sudo docker info
Containers: 38
 Running: 0
 Paused: 0
 Stopped: 38
Images: 446
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 785
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.2.0-42-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.55 GiB
Name: tifenn
ID: LVOK:TQXL:5MY5:HSHV:ARH4:23K7:6RMF:PGGF:SAVW:65PJ:ZEOR:JJKG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: osallou
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical

osallou@tifenn~ $ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily

**Steps to reproduce the issue:**
1. osallou@tifenn~ $ sudo docker run swarm --help
docker: An error occurred trying to connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create: EOF.
See 'docker run --help'.

2. sudo docker run --rm -it debian /bin/bash => OK

**Describe the results you received:**

docker process crash

with output:

docker: An error occurred trying to connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create: EOF.
See 'docker run --help'.

 with logs:

Aug  2 19:49:05 tifenn dockerd[5257]: time="2016-08-02T19:49:05.607542910+02:00" level=info msg="Docker daemon" commit=8eab29e graphdriver=aufs version=1.12.0
Aug  2 19:49:05 tifenn dockerd[5257]: time="2016-08-02T19:49:05.612166498+02:00" level=info msg="API listen on 127.0.0.1:2375"
Aug  2 19:49:05 tifenn systemd[1]: Started Docker Application Container Engine.
Aug  2 19:49:05 tifenn dockerd[5257]: time="2016-08-02T19:49:05.612228109+02:00" level=info msg="API listen on /var/run/docker.sock"
Aug  2 19:49:05 tifenn kernel: [  365.963990] aufs au_opts_verify:1597:dockerd[5277]: dirperm1 breaks the protection by the permission bits on the lower branch
Aug  2 19:49:05 tifenn kernel: [  366.007472] aufs au_opts_verify:1597:dockerd[5277]: dirperm1 breaks the protection by the permission bits on the lower branch
Aug  2 19:49:05 tifenn kernel: [  366.135105] aufs au_opts_verify:1597:dockerd[5277]: dirperm1 breaks the protection by the permission bits on the lower branch
Aug  2 19:49:05 tifenn dockerd[5257]: panic: runtime error: invalid memory address or nil pointer dereference
Aug  2 19:49:05 tifenn dockerd[5257]: [signal 0xb code=0x1 addr=0x8 pc=0xc50151]
Aug  2 19:49:05 tifenn dockerd[5257]: goroutine 246 [running]:
Aug  2 19:49:05 tifenn dockerd[5257]: panic(0x1a750e0, 0xc82000e090)
Aug  2 19:49:05 tifenn dockerd[5257]: /usr/local/go/src/runtime/panic.go:481 +0x3e6
Aug  2 19:49:05 tifenn dockerd[5257]: github.com/docker/docker/pkg/plugins.readPluginJSONInfo(0xc820acc464, 0xa, 0xc820acc750, 0x23, 0x0, 0x0, 0x0)
Aug  2 19:49:05 tifenn dockerd[5257]: /usr/src/docker/.gopath/src/github.com/docker/docker/pkg/plugins/discovery.go:119 +0x221
Aug  2 19:49:05 tifenn dockerd[5257]: github.com/docker/docker/pkg/plugins.(*localRegistry).Plugin(0xc8209e5e70, 0xc820acc464, 0xa, 0xc820394ad8, 0x0, 0x0)
Aug  2 19:49:05 tifenn dockerd[5257]: /usr/src/docker/.gopath/src/github.com/docker/docker/pkg/plugins/discovery.go:80 +0xa65
Aug  2 19:49:05 tifenn dockerd[5257]: github.com/docker/docker/pkg/plugins.loadWithRetry(0xc820acc464, 0xa, 0xc820acaa00, 0x0, 0x0, 0x0)
Aug  2 19:49:05 tifenn dockerd[5257]: /usr/src/docker/.gopath/src/github.com/docker/docker/pkg/plugins/plugins.go:172 +0xa2
Aug  2 19:49:05 tifenn dockerd[5257]: github.com/docker/docker/pkg/plugins.GetAll.func1(0xc820acaaa0, 0xc820ad0540, 0xc820acc464, 0xa)
Aug  2 19:49:05 tifenn dockerd[5257]: /usr/src/docker/.gopath/src/github.com/docker/docker/pkg/plugins/plugins.go:255 +0x5f
Aug  2 19:49:05 tifenn dockerd[5257]: created by github.com/docker/docker/pkg/plugins.GetAll
Aug  2 19:49:05 tifenn dockerd[5257]: /usr/src/docker/.gopath/src/github.com/docker/docker/pkg/plugins/plugins.go:257 +0x5a5
Aug  2 19:49:05 tifenn systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug  2 19:49:05 tifenn systemd[1]: docker.service: Unit entered failed state.
Aug  2 19:49:05 tifenn systemd[1]: docker.service: Failed with result 'exit-code'.

**Describe the results you expected:**

swarm container startup

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by anusha-ragunathan** [comment]
Dup of https://github.com/docker/docker/issues/25233

**Comment by thaJeztah** [comment]
Thanks for reporting @osallou!

**Comment by thaJeztah** [comment]
issue will be resolved through https://github.com/docker/docker/pull/25053
