### ISSUE TITLE
[Windows] Run containers fails with error 'error during Start failed in Win32: winapi error #3221227274 (0xc000070a)'

### ISSUE THREAD

**Issue by alexey-gusarov** [docker/docker#25336]
**Output of `docker version`:**

```
c:\temp>docker version
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   8e92415
 Built:        Thu May 26 17:08:34 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   8e92415
 Built:        Thu May 26 17:08:34 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
c:\temp>docker info
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 1
Server Version: 1.12.0-dev
Storage Driver: Windows filter storage driver
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: transparent null nat
Kernel Version: 10.0 14300 (14300.1000.amd64fre.rs1_release_svc.160324-1723)
Operating System: Windows Server 2016 Standard Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 7.997 GiB
Name: act-tbcontainers
ID: 4L27:W6YA:WJMY:CUB7:QKG6:RHRD:KR7N:QS6J:L3E7:YHUU:N4U2:6YUQ
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Hyper-V virtual machine

**Steps to reproduce the issue:**
1. docker run -it windowsservercore cmd
2.
3.

**Describe the results you received:**
docker: Error response from daemon: container e77f1816c775eb705d547b90da62656e089438a65c3f0633a998508c93a47037 encountered an error during Start failed in Win32: winapi error #3221227274 (0xc000070a).

**Describe the results you expected:**
running container

**Additional information you deem important (e.g. issue happens only occasionally):**
I use containers about month, but today I can't run any container.

Debug log of dockerd:
[errorout.txt](https://github.com/docker/docker/files/397534/errorout.txt)

**Comment by jimallen** [comment]
Also seeing this issue. 

I followed this document. It worked before..

https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_server

**Comment by mpwagne** [comment]
I am seeing this as well. It was working fine on 7/27. I noticed on 7/28 the host installed the CU for TP5. Did you happen to also have KB3172989 on your host? I'm thinking this might have broken it. I pulled down latest docker engine as well thinking they might need to match up, but still fails to start containers.

**Comment by 5f6b3fb8** [comment]
Seeing this issue as well. I'm running TP5 in virtualbox, without the hyper-v role installed.

I had the docker host VM turned off for some time, then fired it back up and couldn't launch any containers, getting the same error message above.

**Comment by jbhurat** [comment]
I am seeing this as well. I am running TP5 in Hyper-V Manager. Issue started happening yesterday and it had worked earlier. Reinstalled TP5 by following instructions at https://msdn.microsoft.com/en-us/virtualization/windowscontainers/deployment/deployment, but still the same results

**Comment by thaJeztah** [comment]
ping @jstarks PTAL

**Comment by jstarks** [comment]
We're looking into this...

**Comment by alexey-gusarov** [comment]
I tried create new installation of Windows Server 2016 TP 5 and run build container and get the same error:

PS C:\Windows\system32> docker tag windowsservercore:10.0.14300.1000 windowsservercore:latest
PS C:\Windows\system32> docker build -t iis d:\builds\iis
Sending build context to Docker daemon  2.56 kB
Step 1 : FROM windowsservercore
 ---> 2b824ea36a88
Step 2 : LABEL Description "IIS" Vendor "KL" Version "10"
 ---> Running in 68bd8e9a1bda
 ---> 5e31302fdc7c
Removing intermediate container 68bd8e9a1bda
Step 3 : ADD http://pki.<replaced>.com/level1/aia/<replaced>.crt <replaced>.crt
Downloading [==================================================>]    892 B/892 B
 ---> 62758551faea
Removing intermediate container 9a03408d30b0
Step 4 : RUN certutil -addstore Root <replaced>.crt
 ---> Running in fb1b3ff89d1e
container fb1b3ff89d1e4770790080b1a015c46aceaae1036e1197538d1daebd311e6355 encountered an error during Start failed in Win32: winapi error #3221227274 (0xc000070a)

**Comment by yenhao** [comment]
I have used docker for about two weeks.
Two days ago, it still work..
However, yesterday morning, I restarted my Windows Server 2016 TP5 on VMware WorkStation 12 Player and get the similar error..

Docker info:
`PS C:\Users\Administrator> docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 3
Server Version: 1.12.0-dev
Storage Driver: Windows filter storage driver
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null
Kernel Version: 10.0 14300 (14300.1045.amd64fre.rs1_release_svc.160705-1059)
Operating System: Windows Server 2016 Datacenter Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 2 GiB
Name: YENHAO0218B33A
ID: DQ3D:WOYV:QCGZ:6DM7:R7D3:GN77:E33J:OMUW:53TE:I7JI:KN6Z:VHTE
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8`

Situation
`PS C:\Users\Administrator> docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
test1               latest              392d7d87ee03        10 days ago         9.386 GB
windowsservercore   10.0.14300.1000     5bc36a335344        11 weeks ago        9.354 GB
windowsservercore   latest              5bc36a335344        11 weeks ago        9.354 GB
microsoft/iis       latest              c26f4ceb81db        12 weeks ago        9.49 GB
PS C:\Users\Administrator> docker run -itd -p 80:80 microsoft/iis cmd
92645536a4390320564d386b6da9ca3b08d11ec6ad5028432258feb497e7982c
C:\Program Files\docker\docker.exe: Error response from daemon: container 92645536a4390320564d386b6da9ca3b08d11ec6ad5028
432258feb497e7982c encountered an error during Start failed in Win32: The remote procedure call failed. (0x6be).
PS C:\Users\Administrator>
PS C:\Users\Administrator> docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                      PORTS
        NAMES
92645536a439        microsoft/iis       "cmd"               2 minutes ago       Created
        agitated_albattani
4e6811705ade        windowsservercore   "powershell"        10 days ago         Exited (1067) 10 days ago
        serene_wozniak
PS C:\Users\Administrator> docker start agitated_albattani
Error response from daemon: container 92645536a4390320564d386b6da9ca3b08d11ec6ad5028432258feb497e7982c encountered an er
ror during Start failed in Win32: winapi error #3221227274 (0xc000070a)
Error: failed to start containers: agitated_albattani`

**Comment by sitano** [comment]
Microsoft have changed something yesterday in Windows Server 2016 TP5 and container start began fail.

**Comment by XiaoningLiu** [comment]
The same problem on my physical machine, 2016 TP5, Build 14300.rs1_release_svc.160705-1059.
Cannot docker build & run image.

Yesterday it worked well. The problem seems happened within 24 hours.

**Comment by alexey-gusarov** [comment]
workaround:

1. Change date to 25 July 2016
2. run any container (docker run -it windowsservercore:10.0.14300.1000 cmd)
3. exit from container
4. change date back
5. any container works fine until reboot

**Comment by sitano** [comment]
I have managed to successfully run docker container from https://github.com/docker/docker/commit/cfd2719bf797d71dc790c0925b9512327880fb24 . I used the latest docker WindowsServerCore image from https://hub.docker.com/r/microsoft/windowsservercore/ with:

    docker pull microsoft/windowsservercore:10.0.14300.1030
    docker run -it windowsservercore:10.0.14300.1000 cmd

The point is not time, but the latest windows image from the hub. And it seems like its not compatible to other images build on top :(

**Comment by XiaoningLiu** [comment]
docker pull seems not work：

```
PS C:\WINDOWS\system32> docker pull microsoft/windowsservercore:10.0.14300.1030
10.0.14300.1030: Pulling from microsoft/windowsservercore

1239394e5a8a: Downloading
unknown blob
```

**Comment by sitano** [comment]
@XiaoningLiu what version of the dockerd do you have?

**Comment by sitano** [comment]
@StefanScherer I think you may be interested in that case concerning ongoing fixes to the https://github.com/StefanScherer/docker-windows-box/blob/master/scripts/update-nightly-docker.ps1 updating docker to the latest version ;) its not sufficient to move old db (btw, latest version supports some kind of migration), but also its required for the latest windowsservercore image to be downloaded right from the hub with:

    docker pull microsoft/windowsservercore:10.0.14300.1030

And this 10.0.14300.1030 from the hub is not the same microsoft/iis:windowsservercore references to at the same hub :D

**Comment by XiaoningLiu** [comment]
@sitano I  created an Azure Virtual Machine "Windows Server 2016 Core with Containers Tech Preview 5" just now.

One the pure virtual machine, default docker version is as follows. However, the docker pull still cannot work.

```
PS C:\Users\t-xiaonl> docker version
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   3d80884
 Built:        Mon Jun  6 19:12:50 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   3d80884
 Built:        Mon Jun  6 19:12:50 2016
 OS/Arch:      windows/amd64
PS C:\Users\t-xiaonl> docker pull microsoft/windowsservercore:10.0.14300.1030
10.0.14300.1030: Pulling from microsoft/windowsservercore

1239394e5a8a: Downloading
unknown blob
```

```
PS C:\Users\t-xiaonl> docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 1.12.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: null
Kernel Version: 10.0 14300 (14300.1030.amd64fre.rs1_release_svc.160603-1734)
Operating System: Windows Server 2016 Datacenter Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 56 GiB
Name: pevm1
ID: XU2V:CWCS:HRAV:K3LG:2IRZ:WJYW:7J2J:W4GV:5YL6:JLBX:LZAX:2QYU
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Comment by XiaoningLiu** [comment]
@sitano I updated dockerd from 1.12.0-dev to 1.13.0-dev using your script:

https://github.com/StefanScherer/docker-windows-box/blob/master/scripts/update-nightly-docker.ps1

Then executed the docker pull command:

``docker pull microsoft/windowsservercore:10.0.14300.1030
``

The container is able to start up now. 

Your are right. 
**Updating the latest version of dockerd and windowsservercore could solve this issue.** 

Thanks.

**Comment by StefanScherer** [comment]
@XiaoningLiu I think the docker from `Mon Jun  6 19:12:50 2016` is too old to support `docker pull microsoft/windowsservercore:10.0.14300.1030`.
Oh, you were faster :-)

**Comment by StefanScherer** [comment]
@XiaoningLiu I'm out of luck spinning up a "Windows Server 2016 Core with Containers Tech Preview 5" on Azure, tried it three times, but always the Docker Engine service does not start. Event log shows `fatal: Error starting daemon: Error initializing network controller: Error creating default network: HNS failed with error : Failed to create network`

But I've tested it locally by updating to Docker 1.12.0 with my second script [update-docker-1.12.0.ps1](https://github.com/StefanScherer/docker-windows-box/blob/master/scripts/update-docker-1.12.0.ps1) which installs a Docker Engine new enough to run the `docker pull microsoft/windowsservercore:10.0.14300.1030` afterwards.

Feels great and we can start to write `Dockerfile`'s that will pull everything.

**Comment by sitano** [comment]
concerning @XiaoningLiu 's

> fatal: Error starting daemon: Error initializing network controller: Error creating default network: HNS failed with error : Failed to create network

There is known workaround which is painly ... work. Can be seen from here: https://github.com/Microsoft/Virtualization-Documentation/issues/273

    Stop-Service Docker
    Get-NetNatStaticMapping | Remove-NetNatStaticMapping
    Remove-ContainerNetworkAdapter -Name Nat
    Reboot

Useful but maybe unsynced info on windows networking is here: https://msdn.microsoft.com/en-us/virtualization/windowscontainers/management/container_networking.

**Comment by sitano** [comment]
I personally think this issue can be closed for now.

**Comment by 5f6b3fb8** [comment]
I was able to recreate my box using the instruction [here](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_server), up to step number 3. 

Then I ran `docker pull microsoft/windowsservercore:10.0.14300.1030` and was able to run containers after that. So I was able to keep using 1.12 docker with the new windowsservercore image.

**Comment by alexey-gusarov** [comment]
If you can't download new version through docker pull (for example proxy required authentication) you can download tarball image https://az896309.vo.msecnd.net/containers/microsoft/windowsservercore:10.0.14300.1030_2 and 
s command import

`docker import d:\OSImages\windowsservercore10.0.14300.1030_2`

**Comment by bornemann** [comment]
Hi,

I have was able to update docker and to docker pull microsoft/windowsservercore:10.0.14300.1030 , but still I am getting this error. I might miss a step, do I need to delete the old windowsservercore or something? Or assign iis to the new core somehow?

Thanks for your help.

**Comment by sitano** [comment]
@bornemann it depends on exact version docker and windows version. what versions do you use? plz give `docker version` and `docker info`.

But, anyway, the solution will be: for latest Windows 10 (August 4) build you have to use `microsoft/nanoserver:10.0.14300.1030`. If you having this error on the server, be advised that old images are NOT compatible to the latest windows build, yet they keep same versioning. 

So, if you have image from `Install-ContainerImage -Name *` or any other obsolete method, remove all old images first with `docker rmi * --force`.

**Comment by StefanScherer** [comment]
@bornemann The microsoft/iis seems to be old and is based on the old windowsservercore base image.
These images doesn't seem to work any more.
I think this iis image will be updated and pushed to Docker Hub based on the new OS base image soon.

In the meantime you can build it locally using this Dockerfile https://github.com/Microsoft/Virtualization-Documentation/blob/master/windows-container-samples/windowsservercore/iis/Dockerfile as a starting point, but replace the first line with `FROM microsoft/windowsservercore:10.0.14300.1030`

**Comment by bornemann** [comment]
Thanks for your quick answers. I am using the Server 2016 TP5.

@Stefan: I tried your solution, but now I am stuck wit this error: 

Step 3 : RUN powershell -Command Add-WindowsFeature Web-Server
 ---> Running in 5e42488cef8f
The command 'cmd /S /C powershell -Command Add-WindowsFeature Web-Server' returned a non-zero code: 255

**Comment by StefanScherer** [comment]
@bornemann I just tried it myself with this https://github.com/StefanScherer/dockerfiles-windows/blob/master/iis/Dockerfile and it worked for me.
Maybe some networking issue accessing the internet?
Have you tried it again?

```
C:\Users\vagrant\dockerfiles-windows\iis>docker build -t iis .
Sending build context to Docker daemon  5.12 kB
Step 1 : FROM microsoft/windowsservercore:10.0.14300.1030
 ---> 02cb7f65d61b
Step 2 : LABEL Description "IIS" Vendor "Microsoft" Version "10"
 ---> Running in b7ff194c22ca
 ---> 49946e693ab0
Removing intermediate container b7ff194c22ca
Step 3 : RUN powershell -Command Add-WindowsFeature Web-Server
 ---> Running in 4c3ed5476c2f

Success Restart Needed Exit Code      Feature Result
------- -------------- ---------      --------------
True    No             Success        {Common HTTP Features, Default Documen...


 ---> d050b50c8a3f
Removing intermediate container 4c3ed5476c2f
Step 4 : CMD ping localhost -t
 ---> Running in b6751e6310bd
 ---> b23b4055a454
Removing intermediate container b6751e6310bd
Successfully built b23b4055a454
C:\Users\vagrant\dockerfiles-windows\iis [master ≡ +0 ~1 -0 !]>
C:\Users\vagrant\dockerfiles-windows\iis [master ≡ +0 ~1 -0 !]> docker images
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
iis                           latest              b23b4055a454        26 minutes ago      7.902 GB
microsoft/windowsservercore   10.0.14300.1030     02cb7f65d61b        6 weeks ago         7.764 GB
microsoft/nanoserver          10.0.14300.1030     3a703c6e97a2        6 weeks ago         969.8 MB
```

**Comment by kumareshind** [comment]
PS C:\> docker version
Client:
 Version:      1.12.2-cs2-ws-beta-rc1
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   62d9ff9
 Built:        Fri Sep 23 20:50:29 2016
 OS/Arch:      windows/amd64

PS C:\> dockerd.exe
Error starting daemon: The docker daemon requires build 14393 or later of Windows Server 2016 or Windows 10

Start-Service : Failed to start service 'Docker Engine (docker)'.
At line:1 char:1
+ Start-Service docker
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],
   ServiceCommandException
    + FullyQualifiedErrorId : StartServiceFailed,Microsoft.PowerShell.Commands.StartServiceCommand

**Comment by kumareshind** [comment]
What could be the issue ? 

I am using Azure Windows 2016 Server TP5 
Build 14300.rs1_release_svc.160907-0755

**Comment by StefanScherer** [comment]
@kumareshind The binaries don't work with TP5 any more. TP5 is 14300, but 14393 is needed, also on Windows 2016. You have to wait for a new Azure VM template.
