### ISSUE TITLE
docker service ps option to prevent truncating error messages

### ISSUE THREAD

**Issue by madmax88** [docker/docker#25332]
**Output of `docker version`:**

```
Docker version 1.12.0, build 8eab29e
```

**Steps to reproduce the issue:**

1. Create a service that will obviously have errors, like:
    `docker service create --name ting-tang-walla-walla-bing-bang --replicas 1 busybox command-does-not-exist`

2. Try and list the tasks of that service:
    `docker service ps ting-tang-walla-walla-bing-bang`

3. The error message might be truncated, so try and use the `--no-trunc` option from regular `docker ps`
    `docker service ps --no-trunc ting-tang-walla-walla-bing-bang`

**Describe the results you received:**

    unknown flag: --no-trunc
    See 'docker service ps --help'.

**Describe the results you expected:**

Standard `docker ps` information with complete messages.

**Comment by thaJeztah** [comment]
Yes, I think this makes sense to add, thanks for suggesting!

While this is not implemented yet, you can use `docker inspect <task-id>` to get the full error message;

```bash
$ docker service create --name ting-tang-walla-walla-bing-bang --replicas 1 busybox command-does-not-exist
4lrt9bky5q4rv0hy5romhuvvj

$ docker service ps ting-tang-walla-walla-bing-bang
ID                         NAME                                   IMAGE    NODE  DESIRED STATE  CURRENT STATE            ERROR
8lrd5ag3tu1oyr1smf9mjxkx8  ting-tang-walla-walla-bing-bang.1      busybox  moby  Ready          Preparing 1 seconds ago
9d0yw8rcbqlhu16jhkvam3f49   \_ ting-tang-walla-walla-bing-bang.1  busybox  moby  Shutdown       Failed 1 seconds ago     "starting container failed: oc…"

$ docker inspect 9d0yw8rcbqlhu16jhkvam3f49
2016
[
    {
        "ID": "9d0yw8rcbqlhu16jhkvam3f49",
        "Version": {
            "Index": 133
        },
        "CreatedAt": "2016-08-02T16:17:17.200521842Z",
        "UpdatedAt": "2016-08-02T16:17:21.397588985Z",
        "Spec": {
            "ContainerSpec": {
                "Image": "busybox",
                "Args": [
                    "command-does-not-exist"
                ]
            },
            "Resources": {
                "Limits": {},
                "Reservations": {}
            },
            "RestartPolicy": {
                "Condition": "any",
                "MaxAttempts": 0
            },
            "Placement": {}
        },
        "ServiceID": "4lrt9bky5q4rv0hy5romhuvvj",
        "Slot": 1,
        "NodeID": "3epta4a8crw62sjjb30rvywm0",
        "Status": {
            "Timestamp": "2016-08-02T16:17:21.350438748Z",
            "State": "failed",
            "Message": "starting",
            "Err": "starting container failed: oci runtime error: exec: \"command-does-not-exist\": executable file not found in $PATH",
            "ContainerStatus": {
                "ContainerID": "2b654a3ffa859f3864472882bb654332aee747058087c86f020e099657ac6430",
                "ExitCode": 127
            }
        },
        "DesiredState": "shutdown"
    }
]
```

hope that helps :)

**Comment by madmax88** [comment]
I actually started working on this -- give me a second to put the pull request together.

**Comment by thaJeztah** [comment]
@madmax88 looks like @jhorwit2 beat you to it

**Comment by jhorwit2** [comment]
:) i have been thinking this in my head for a while so figured i'd finally do it 👼 .

**Comment by madmax88** [comment]
@jhorwit2, awesome job:) Thanks all! 

Gonna go ahead and close now.

**Comment by thaJeztah** [comment]
Let's keep it open until the pr is merged

**Comment by alexellis** [comment]
👍  to this.. I keep typing it it.

**Comment by linshengke** [comment]
> Yes, I think this makes sense to add, thanks for suggesting!
> 
> While this is not implemented yet, you can use `docker inspect <task-id>` to get the full error message;
> 
> ```shell
> $ docker service create --name ting-tang-walla-walla-bing-bang --replicas 1 busybox command-does-not-exist
> 4lrt9bky5q4rv0hy5romhuvvj
> 
> $ docker service ps ting-tang-walla-walla-bing-bang
> ID                         NAME                                   IMAGE    NODE  DESIRED STATE  CURRENT STATE            ERROR
> 8lrd5ag3tu1oyr1smf9mjxkx8  ting-tang-walla-walla-bing-bang.1      busybox  moby  Ready          Preparing 1 seconds ago
> 9d0yw8rcbqlhu16jhkvam3f49   \_ ting-tang-walla-walla-bing-bang.1  busybox  moby  Shutdown       Failed 1 seconds ago     "starting container failed: oc…"
> 
> $ docker inspect 9d0yw8rcbqlhu16jhkvam3f49
> [
>     {
>         "ID": "9d0yw8rcbqlhu16jhkvam3f49",
>         "Version": {
>             "Index": 133
>         },
>         "CreatedAt": "2016-08-02T16:17:17.200521842Z",
>         "UpdatedAt": "2016-08-02T16:17:21.397588985Z",
>         "Spec": {
>             "ContainerSpec": {
>                 "Image": "busybox",
>                 "Args": [
>                     "command-does-not-exist"
>                 ]
>             },
>             "Resources": {
>                 "Limits": {},
>                 "Reservations": {}
>             },
>             "RestartPolicy": {
>                 "Condition": "any",
>                 "MaxAttempts": 0
>             },
>             "Placement": {}
>         },
>         "ServiceID": "4lrt9bky5q4rv0hy5romhuvvj",
>         "Slot": 1,
>         "NodeID": "3epta4a8crw62sjjb30rvywm0",
>         "Status": {
>             "Timestamp": "2016-08-02T16:17:21.350438748Z",
>             "State": "failed",
>             "Message": "starting",
>             "Err": "starting container failed: oci runtime error: exec: \"command-does-not-exist\": executable file not found in $PATH",
>             "ContainerStatus": {
>                 "ContainerID": "2b654a3ffa859f3864472882bb654332aee747058087c86f020e099657ac6430",
>                 "ExitCode": 127
>             }
>         },
>         "DesiredState": "shutdown"
>     }
> ]
> ```
> 
> hope that helps :)

really useful
