### ISSUE TITLE
container cannot access other container for same service using service name

### ISSUE THREAD

**Issue by sfsmithcha** [docker/docker#25340]
**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
($ docker info
Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 9
Server Version: 1.12.0
Storage Driver: overlay
 Backing Filesystem: xfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null bridge host
Swarm: active
 NodeID: a93bz768lawda5zvy6cbb3dyk
 Is Manager: false
 Node Address: 168.0.32.139
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.10.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 991.7 MiB
Name: worker1
ID: 3DIP:IOUN:PVBK:Y4AA:7PFY:K6T3:RJJW:F5JJ:GA2L:ABLX:4GIG:WVQU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. enable swarm mode for multiple node cluster (i'm using 4)
2. create an overlay network on the swarm
    ```
    $ docker network create --driver overlay --subnet=10.0.9.0/24 my-network
    ```
3. create a service attached to the overlay network
    ```
    $ docker service create \
      --replicas 5 \
      --name web \
      --network mynetwork \
      nginx
    ```
4. Open an interactive shell on one of the containers for the service
    ```
    docker exec -it web.1.apdey5elemcxvdlaxau5puelw /bin/bash
    ```
5. For nginx install busybox and curl:
    ```
    $apt-get update
    $apt-get install busybox
    $apt-get install curl
    ```
6. Observe that you can ping all the container addresses for the service:
     $ busybox nslookup tasks.web
     Server:    127.0.0.11
     Address 1: 127.0.0.11
 
     Name:      tasks.web
     Address 1: 10.0.0.5 ef7c7859fc98
     Address 2: 10.0.0.4 web.3.88xyhzx0olkrt6ub9wm2vb6pa.test
     Address 3: 10.0.0.7 web.1.apdey5elemcxvdlaxau5puelw.test
     Address 4: 10.0.0.6 web.5.cs1sjkxmbz7canp6xroidn504.test
     Address 5: 10.0.0.3 web.2.7mg7bid4bkjkfbrryu6ic6eme.test
     
     $ ping 10.0.0.3
     PING 10.0.0.3 (10.0.0.3): 56 data bytes
     64 bytes from 10.0.0.3: icmp_seq=0 ttl=64 time=0.945 ms
     64 bytes from 10.0.0.3: icmp_seq=1 ttl=64 time=0.765 ms
     ^C--- 10.0.0.3 ping statistics ---
     2 packets transmitted, 2 packets received, 0% packet loss
     round-trip min/avg/max/stddev = 0.765/0.855/0.945/0.090 ms
     $ ping 10.0.0.4
     PING 10.0.0.4 (10.0.0.4): 56 data bytes
     64 bytes from 10.0.0.4: icmp_seq=0 ttl=64 time=0.743 ms
     64 bytes from 10.0.0.4: icmp_seq=1 ttl=64 time=0.753 ms
     ^C--- 10.0.0.4 ping statistics ---
     2 packets transmitted, 2 packets received, 0% packet loss
     round-trip min/avg/max/stddev = 0.743/0.748/0.753/0.000 ms
     $ ping 10.0.0.5
     PING 10.0.0.5 (10.0.0.5): 56 data bytes
     64 bytes from 10.0.0.5: icmp_seq=0 ttl=64 time=0.055 ms
     64 bytes from 10.0.0.5: icmp_seq=1 ttl=64 time=0.043 ms
     ^C--- 10.0.0.5 ping statistics ---
     2 packets transmitted, 2 packets received, 0% packet loss
     round-trip min/avg/max/stddev = 0.043/0.049/0.055/0.000 ms
     $ ping 10.0.0.6
     PING 10.0.0.6 (10.0.0.6): 56 data bytes
     64 bytes from 10.0.0.6: icmp_seq=0 ttl=64 time=0.826 ms
     64 bytes from 10.0.0.6: icmp_seq=1 ttl=64 time=0.823 ms
     64 bytes from 10.0.0.6: icmp_seq=2 ttl=64 time=0.789 ms
     ^C--- 10.0.0.6 ping statistics ---
     3 packets transmitted, 3 packets received, 0% packet loss
     round-trip min/avg/max/stddev = 0.789/0.813/0.826/0.000 ms
     $ ping 10.0.0.7
     PING 10.0.0.7 (10.0.0.7): 56 data bytes
     64 bytes from 10.0.0.7: icmp_seq=0 ttl=64 time=0.841 ms
     64 bytes from 10.0.0.7: icmp_seq=1 ttl=64 time=0.699 ms
     64 bytes from 10.0.0.7: icmp_seq=2 ttl=64 time=0.819 ms
     ^C--- 10.0.0.7 ping statistics ---
     3 packets transmitted, 3 packets received, 0% packet loss

**Describe the results you received:**

Observe that curl to the service name `web` fails 4/5 times
   ```
 $ curl web
    ^C
 $ curl web
    <!DOCTYPE html>
    <html>
    <head>
    <title>Welcome to nginx!</title>
    ...snip...
 $ curl web
    ^C
 $ curl web
    ^C
 $ curl web
    ^C
 $ curl web
    ^C
 $ curl web
    <!DOCTYPE html>
    <html>
    <head>
    <title>Welcome to nginx!</title>
```

@mrjana was able to confirm that the curl succeeds only when hitting the local container

**Describe the results you expected:**

should work for every container

**Additional information you deem important (e.g. issue happens only occasionally):**

This doesn't happen if you are accessing another service. Only happens when hitting the same service the container is part of.

@mrjana suggests this may be related to fixes to enable ping.

**Comment by jatin1986** [comment]
I am facing same issue container cannot access other container in docker swarm 1.12.1. I
