### ISSUE TITLE
Always "hang" when I run Docker load

### ISSUE THREAD

**Issue by usultrared** [docker/docker#25362]
**Output of `docker version`: 
1.12

```
(paste your output here)
```
Sams-MacBook-Pro:default samchen$ docker load 

**Output of `docker info`:**
Sams-MacBook-Pro:default samchen$ docker info
Containers: 39
 Running: 1
 Paused: 0
 Stopped: 38
Images: 226
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 318
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null overlay host
Swarm: active
 NodeID: bqo9wjuolar5qk0qm8v3nnmg1
 Is Manager: true
 ClusterID: f350z8ybay7jshcq2k97rilnw
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot interval: 10000
  Heartbeat tick: 1
  Election tick: 3
 Dispatcher:
  Heartbeat period: 5 seconds
 CA configuration:
  Expiry duration: 3 months
 Node Address: 192.168.65.2
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.954 GiB
Name: moby
ID: KCVJ:4PIN:RF33:55IX:TM6S:KCKT:SEVN:RCMR:COUK:RO4Z:AK5Z:SBQH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 40
 Goroutines: 126
 System Time: 2016-08-03T11:11:08.657760542Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Install Mac Docker distribution 1.12
2. run "docker load"
3.

**Describe the results you received:**

**Describe the results you expected:**
It supposed to prompt up "syntax" or "usage"

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
looks like this is posted twice (see https://github.com/docker/docker/issues/25363)
