### ISSUE TITLE
Docker swarm init --listen-addr doesn't affect all ports

### ISSUE THREAD

**Issue by raesene** [docker/docker#25372]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 10
 Running: 0
 Paused: 0
 Stopped: 10
Images: 55
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 131
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: active
 NodeID: 2ji7opii0ovw28tdzr0r6zpwj
 Is Manager: true
 ClusterID: elhmbjd57jdrffgznivl99c9x
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot interval: 10000
  Heartbeat tick: 1
  Election tick: 3
 Dispatcher:
  Heartbeat period: 5 seconds
 CA configuration:
  Expiry duration: 3 months
 Node Address: 192.168.41.228
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.788 GiB
Name: linuxtestvm
ID: 5QOR:62VA:NL5D:HRRY:HLMN:RYKG:A6CU:WRIY:OCAV:HO6U:DYA2:ES2D
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: raesene
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VMWare Workstation VM running Ubuntu 16.04

**Steps to reproduce the issue:**
1. type ```docker swarm init --listen-addr <specific_ip>```
2. type ```sudo netstat -lntp | grep -i docker```
3. look at the listening interfaces for port 7946/TCP

**Describe the results you received:**
The service running on 7946/TCP is listening on all interfaces and not the one specified by ```--listen-addr``` , in contrast to the service on 2377/TCP which will only be listening on that specific interface

**Describe the results you expected:**
All docker swarm services should follow the ```--listen-addr``` flag and bind to specific interfaces if specified

**Comment by thaJeztah** [comment]
ping @aaronlehmann

**Comment by aaronlehmann** [comment]
I think this is the port for memberlist.

The listen address is exposed to libnetwork, and I know libnetwork uses it for tunnel setup in some cases. It must not be using it for gossip.

ping @mrjana @mavenugo

**Comment by docwhat** [comment]
Is there a workaround for this? Because this is leaving port 7946 exposed to the world may be a security issue.

**Comment by diogomonica** [comment]
@docwhat we're using encryption for all memberlist communications, so it shouldn't be an issue. This said, I definitely would like to hear if there is a reason for this or if it's just an oversight. Ideally `--listen-addr` would behave the same for all ports.

**Comment by mrjana** [comment]
Yeah it's a bug and we are already fixing it: https://github.com/docker/libnetwork/pull/1460
