### ISSUE TITLE
Docker 1.12 ps filter result is non-deterministic

### ISSUE THREAD

**Issue by greggilbert** [docker/docker#25374]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS - Ubuntu 14.04 LTS

**Steps to reproduce the issue:**
1. Have more than one container running with a similar name (e.g. `xyz-abc`, `xyz-123`)
2. Run `docker ps -q -f name=xyz`

**Describe the results you received:**

Containers are listed in random order; rerunning the `docker ps` command in step 2 repeatedly returns different results

**Describe the results you expected:**

To see the containers listed in reverse created order, as they are in `docker ps`.

**Additional information you deem important (e.g. issue happens only occasionally):**

There's no way to sort the results by created date, is there?

**Comment by yongtang** [comment]
@greggilbert I created a PR #25387 for that. Please let me know if there are any issues.
