### ISSUE TITLE
Documentation for docker service create --mount

### ISSUE THREAD

**Issue by rayjohnson** [docker/docker#25378]
I can't find the syntax for what is supposed to be passed to --mount option for docker service create.  It certainly isn't in the docs for docker service create nor pointed to from there.

**Comment by thaJeztah** [comment]
Documentation is still being worked on, and tracked via https://github.com/docker/docker/issues/24277

I'll close this issue, because we have https://github.com/docker/docker/issues/24277 to track this, but thanks for reporting!
