### ISSUE TITLE
Is there a way to use docker with recently released Linux subsystem for Windows?

### ISSUE THREAD

**Issue by fastmuse** [docker/docker#25389]

**Comment by friism** [comment]
@fastmuse you can't run the Linux daemon in WSL, I think  because the relevant Linux kernel APIs are not (yet) emulated by WSL. You _can_ run the Linux CLI in WSL, targeting any daemon you'd like over TCP (using either `-H` or `DOCKER_HOST`.

**Comment by thaJeztah** [comment]
Correct, it's not (currently) possible

I'll close this issue, because this is not a bug, and I think this question is answered
