### ISSUE TITLE
docker host network mode is not working on MAC with docker version 1.12.0

### ISSUE THREAD

**Issue by darwink** [docker/docker#25398]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Output of `docker version`:**
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:04:48 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:04:48 2016
 OS/Arch:      linux/amd64
 Experimental: true

**Output of `docker info`:**
Containers: 22
 Running: 4
 Paused: 0
 Stopped: 18
Images: 128
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 189
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay null bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.954 GiB
Name: moby
ID: NP7Q:5LKP:5IVQ:GIBS:PSP5:E2P6:HMYT:RKYE:W4LX:3K6B:AFM5:QPCJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 38
 Goroutines: 76
 System Time: 2016-08-04T09:33:39.027956419Z
 EventsListeners: 2
Username: darwink
Registry: https://index.docker.io/v1/
Experimental: true

**Steps to reproduce the issue:**
Use docker-compose to run below docker-compose.yml:

zookeeper:
  image: jplock/zookeeper:3.4.8
  net: host

**Describe the results you received:**
MAC WIFI IP: 10.15.235.92, but I cannot access default zookeeper port 2181 from 10.15.235.92:2181 by zookeeper client.

**Describe the results you expected:**
It should be accessible from 10.15.235.92:2181 since it's in host network mode.
I login the container and run ifconfig -a, but the result is totally different from MAC result with same command.

**Comment by thaJeztah** [comment]
Thanks for reporting; since this issue is specific for docker for mac, could you open it in the docker for mac issue tracker? https://github.com/docker/for-mac/issues. Possibly this is the same issue as https://github.com/docker/for-mac/issues/68?
