### ISSUE TITLE
Man pages generator / makefile should have "preview" target

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#25397]
We recently implemented a feature to generate the man-pages (for a limited set of commands currently) from code (see https://github.com/docker/docker/pull/23825), and are testing how it works.

One thing that would help is to have a "preview" option to verify the generated man-pages; thinking of a container that serves the man-pages, so that they can be viewed in a web-browser.

/cc @vdemeester @dnephin @SvenDowideit :smile:

**Comment by dnephin** [comment]
You can preview them with `man <filename>`.

**Comment by thaJeztah** [comment]
oh! TIL didn't know it could pick a file directly :smile:
