### ISSUE TITLE
update Google Cloud API client import paths and more

### ISSUE THREAD

**Issue by jba** [docker/docker#25403]
The Google Cloud API client libraries for Go are making some breaking changes:
- The import paths are changing from `google.golang.org/cloud/...` to
  `cloud.google.com/go/...`. For example, if your code imports the BigQuery client
  it currently reads
  `import "google.golang.org/cloud/bigquery"`
  It should be changed to
  `import "cloud.google.com/go/bigquery"`
- Client options are also moving, from `google.golang.org/cloud` to
  `google.golang.org/api/option`. Two have also been renamed:
  - `WithBaseGRPC` is now `WithGRPCConn`
  - `WithBaseHTTP` is now `WithHTTPClient`
- The `cloud.WithContext` and `cloud.NewContext` methods are gone, as are the
  deprecated pubsub and container functions that required them. Use the `Client`
  methods of these packages instead.

You should make these changes before September 12, 2016, when the packages at
`google.golang.org/cloud` will go away.

**Comment by thaJeztah** [comment]
Thanks for the heads up!

**Comment by thaJeztah** [comment]
ping @docker/core-engine-maintainers

ping @mikedanese (for GCP logs logging driver)

**Comment by mikedanese** [comment]
@thaJeztah I can make this change. Can you tell me what the requirements are for old revisions of docker to build?

**Comment by mikedanese** [comment]
The grpc client used by docker is pretty old at this point (commit is from May). It's not going to be easy for me to make this change without updating it. A 1.0 GA go-grpc client has been tagged since. Is it okay for me to update to that version? FYI @jba @jfrazelle

**Comment by jfrazelle** [comment]
I would say its ok to upgrade to that :)

**Comment by jba** [comment]
Why not go get google.golang.org/grpc? In other words, whatever is at head
of https://github.com/grpc/grpc-go.

**Comment by tianon** [comment]
+1 for either v1.0.0 or v1.0.1-GA explicit tag

**Comment by mlaventure** [comment]
I'd rather have a tag than a commit too.

**Comment by mikedanese** [comment]
I will go ahead and make the update to v1.0.1-GA tag in containerd. We will have to wait for containerd dependency to sync to this repo before we can make progress on this issue. I imagine that happens fairly regularly?

**Comment by crosbymichael** [comment]
@mikedanese yes, i can update the dep after you bump grpc

**Comment by LK4D4** [comment]
swarmkit will break too, however, all patches for updating grpc there already merged there.
Also, there is `WaitForStateChange` used in docker, which is not available in new grpc.

**Comment by mikedanese** [comment]
I'm fairly certain since the hack/vendor.sh is not using the go-get redirect for the `google.golang.org/cloud` package, removal of that redirect is not going to affect the build. It will affect people who are using a `go get` workflow.

**Comment by mikedanese** [comment]
Blocked by #26538

**Comment by LK4D4** [comment]
@mikedanese looks like grpc was updated.

**Comment by thaJeztah** [comment]
@mikedanese are you still interested in doing the updates, not that https://github.com/docker/docker/pull/26538 was merged?

**Comment by AkihiroSuda** [comment]
This issue will be closed via https://github.com/docker/docker/pull/29475
