### ISSUE TITLE
docker search on Windows does not return correct results

### ISSUE THREAD

**Issue by marrobi** [docker/docker#25408]
**Output of `docker version`:**

```
PS C:\tmp> docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:04:48 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   8e92415
 Built:        Thu May 26 17:08:34 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
PS C:\tmp> docker info
Containers: 49
 Running: 10
 Paused: 0
 Stopped: 39
Images: 5
Server Version: 1.12.0-dev
Storage Driver: Windows filter storage driver
 Windows: 
Logging Driver: json-file
Plugins:
 Volume: local
 Network: null nat
Swarm: 
 NodeID: 
 Is Manager: false
 Node Address: 
Security Options:
Kernel Version: 10.0 14300 (14300.1010.amd64fre.rs1_release_svc.160415-2143)
Operating System: Windows Server 2016 Standard Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 2.106 GiB
Name: minwinpc
ID: RIWX:4K7F:45NN:ITHR:2C2Z:REI3:RIED:VFHA:2GHL:QIU6:5QOC:LCCM
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running Docker for Windows, connected to Nano server container host.

**Steps to reproduce the issue:**
1. Search for container images using `docker search searchstring`

**Describe the results you received:**

Always returns the same set of images no matter what the search string is.

`PS C:\tmp> docker search fsfdfs
NAME                                         DESCRIPTION                                     STARS     OFFICIAL   AUTOMATED
microsoft/sample-django:windowsservercore    Django installed in a Windows Server Core ...   1                    [OK]
microsoft/dotnet35:windowsservercore         .NET 3.5 Runtime installed in a Windows Se...   1         [OK]       [OK]
microsoft/sample-golang:windowsservercore    Go Programming Language installed in a Win...   1                    [OK]
microsoft/sample-httpd:windowsservercore     Apache httpd installed in a Windows Server...   1                    [OK]
microsoft/iis:windowsservercore              Internet Information Services (IIS) instal...   1         [OK]       [OK]
microsoft/sample-mongodb:windowsservercore   MongoDB installed in a Windows Server Core...   1                    [OK]
microsoft/sample-mysql:windowsservercore     MySQL installed in a Windows Server Core b...   1                    [OK]
microsoft/sample-nginx:windowsservercore     Nginx installed in a Windows Server Core b...   1                    [OK]
microsoft/sample-python:windowsservercore    Python installed in a Windows Server Core ...   1                    [OK]
microsoft/sample-rails:windowsservercore     Ruby on Rails installed in a Windows Serve...   1                    [OK]
microsoft/sample-redis:windowsservercore     Redis installed in a Windows Server Core b...   1                    [OK]
microsoft/sample-ruby:windowsservercore      Ruby installed in a Windows Server Core ba...   1                    [OK]
microsoft/sample-sqlite:windowsservercore    SQLite installed in a Windows Server Core ...   1                    [OK]
microsoft/sample-golang:nanoserver           Go Programming Language installed in a Nan...   1                    [OK]
microsoft/sample-httpd:nanoserver            Apache httpd installed in a Nano Server ba...   1                    [OK]
microsoft/sample-mysql:nanoserver            MySQL installed in a Nano Server based con...   1                    [OK]
microsoft/sample-nginx:nanoserver            Nginx installed in a Nano Server based con...   1                    [OK]
microsoft/sample-node:nanoserver             Node installed in a Nano Server based cont...   1                    [OK]
microsoft/sample-python:nanoserver           Python installed in a Nano Server based co...   1                    
microsoft/sample-rails:nanoserver            Ruby on Rails installed in a Nano Server b...   1                    [OK]
microsoft/sample-redis:nanoserver            Redis installed in a Nano Server based con...   1                    [OK]
microsoft/sample-ruby:nanoserver             Ruby installed in a Nano Server based cont...   1                    [OK]
`
**Describe the results you expected:**

Should return filtered results.

**Comment by icecrime** [comment]
I think this is expected on Windows, which uses a dedicated registry for the duration of the technical preview phase.

Cc @friism for confirmation.

**Comment by friism** [comment]
I think this is @marcusmartins and @mghazizadeh serving up custom, hard-coded search results for Windows clients. Consider opening issue here, since this Hub-related: https://github.com/docker/hub-feedback/issues

**Comment by marrobi** [comment]
I've had it confirmed internally:

"That’s currently by design. Docker Hub isn’t able to correctly filter Windows vs Linux results, so the service returns a hardcoded list. The fix is still in the works"

Would be good to know if it is in the works if there is an ETA, if want me to create an issue at hub feedback let me know. Thanks.

**Comment by icecrime** [comment]
@marrobi An issue on hub-feedback would be preferrable indeed, as the work won't be happening in the docker/docker repository in this case (as the hardcoded search result lives on the server side).

Thanks for reporting, I'm closing this one!
