### ISSUE TITLE
Unable to create container since its already running but docker has no reference to it

### ISSUE THREAD

**Issue by dmyerscough** [docker/docker#25416]
**Output of `docker version`:**

```
docker --version
Docker version 1.11.1, build 5604cbe
```

**Output of `docker info`:**

```
docker info
Containers: 21
 Running: 21
 Paused: 0
 Stopped: 0
Images: 66
Server Version: 1.11.1
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.18.27
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 94.37 GiB
Name: appdocker05-dca1
ID: BUBV:BKDD:E3LX:NOSZ:RRLB:YXED:2KS6:UHF6:PSLN:R5KO:CYIC:CMJW
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical box [Dell PowerEdge R420]

**Steps to reproduce the issue:**
1. I am not sure what steps cause this to occur.

**Describe the results you received:**

When issuing `docker create` I get a notification that the container already exists. However, `docker ps -a` does not show the container.

```
$ sudo /usr/bin/docker create --net=host --name="usi-publican-publican" 127.0.0.1:15055/uber-usi/publican:sjc1-produ-0000000516
Error response from daemon: Conflict. The name "/usi-publican-publican" is already in use by container 1c3d95dd6bce331ffd5ace1008ee31344fcfba4ff295325a9f1dcb95ffbf024d. You have to remove (or rename) that container to be able to reuse that name.

$ sudo /usr/bin/docker ps -a | grep publican
$
```

**Describe the results you expected:**

The container should start as Docker has no reference to the publican image.

**Additional information you deem important (e.g. issue happens only occasionally):**

This has been happening on a few of our hosts, we currently haven't been able to find what triggers this to happen.

**Comment by yongtang** [comment]
@dmyerscough that seems like the same as #23371.
