### ISSUE TITLE
Docker container's networkMode changes to default when starting the container

### ISSUE THREAD

**Issue by phagunbaya** [docker/docker#25410]
Docker version - v1.12 
OS - Ubuntu 14.04.4-LTS
Clustering mode - Swarm

Created an overlay network:
```
$ docker -H tcp://0.0.0.0:2375 network create --driver overlay --subnet=10.0.9.0/24 my-net
```

Creating the container: `[POST] http://localhost:2375/container/create?name={id}`
```
{
"Env": [
        "env1=val1"
   ],
   "Cmd": [
       "/Run.sh",
       "launch
    ],
   "Image": "<image>",
   "Volumes": {
       "/tmp" : {}
   },
   "HostConfig": {
     "NetworkMode": "my-net"
   }
}
```

Response of $ docker inspect:
```
"HostConfig": {
    "Binds": null,
    "ContainerIDFile": "",
    "LogConfig": {
        "Type": "json-file",
        "Config": {}
    },
    "NetworkMode": "my-net",
    "PortBindings": null,
    "RestartPolicy": {
        "Name": "",
        "MaximumRetryCount": 0
    },
    "AutoRemove": false,
    "VolumeDriver": "",
    "VolumesFrom": null,
}
```
This creates container with networkMode as my-net. But when I run the container using the rest API `[POST] http://localhost:2375/containers/{id}/start` networkMode changes to default.

Response of $ docker inspect:
```
"HostConfig": {
    "Binds": null,
    "ContainerIDFile": "",
    "LogConfig": {
        "Type": "json-file",
        "Config": {}
    },
    "NetworkMode": "default",
    "PortBindings": null,
    "RestartPolicy": {
        "Name": "",
        "MaximumRetryCount": 0
    },
    "AutoRemove": false,
    "VolumeDriver": "",
    "VolumesFrom": null,
}
```

Whereas `docker run --network=my-net` command works fine with overlay network.

**Comment by phagunbaya** [comment]
Is it a bug or I'm doing something wrong ?

**Comment by mavenugo** [comment]
@phagunbaya currently `docker run` isn't supported for `swarm-mode` networks (overlay network created in swarm-mode). While doing `docker run`, it is supposed to fail right away. It seems `create` and `start` workflow isn't. This is a bug. But the fix will be to fail the Create for this operation until we support this feature (https://github.com/docker/docker/pull/25263)

**Comment by phagunbaya** [comment]
@mavenugo What should be the other option I should use for networking. I have a swarm cluster.

**Comment by phagunbaya** [comment]
And any ETA on swarm support ?

**Comment by mavenugo** [comment]
@phagunbaya can you use `docker service` instead of `docker run` ? Overlay networking is supported in swarm-mode for docker services.

**Comment by phagunbaya** [comment]
@mavenugo : Actually the problem is with `docker run --network=my-net` command I'm able to use the overlay network, but when I use the REST API it is causing problem.

**Comment by thaJeztah** [comment]
@phagunbaya can you check if there's possibly *two* networks names `my-net` (one swarm-scoped and a regular network)? Network names are not guaranteed to be unique, whereas the network *id* is

**Comment by phagunbaya** [comment]
@thaJeztah : I checked. There is only one network with name `my-net` in the swarm scope.

**Comment by mavenugo** [comment]
@phagunbaya pls give us the following information - `docker info`, `docker network ls`, `docker network inspect my-net`

**Comment by phagunbaya** [comment]
docker info
```
Containers: 6
 Running: 5
 Paused: 0
 Stopped: 1
Images: 5
Server Version: swarm/1.2.4
Role: primary
Strategy: spread
Filters: health, port, containerslots, dependency, affinity, constraint
Nodes: 1
 swarm-node-0: 192.168.0.4:2375
  └ ID: KZYO:XVPT:QLCF:6KON:Y3MR:KO5I:W37E:H76G:3M5Q:WOPO:DEW7:XYJ3
  └ Status: Healthy
  └ Containers: 6 (5 Running, 0 Paused, 1 Stopped)
  └ Reserved CPUs: 0 / 8
  └ Reserved Memory: 0 B / 57.79 GiB
  └ Labels: kernelversion=3.19.0-65-generic, operatingsystem=Ubuntu 14.04.4 LTS, storagedriver=aufs
  └ UpdatedAt: 2016-08-04T23:39:18Z
  └ ServerVersion: 1.12.0
Plugins:
 Volume: 
 Network: 
Swarm: 
 NodeID: 
 Is Manager: false
 Node Address: 
Security Options:
Kernel Version: 3.19.0-65-generic
Operating System: linux
Architecture: amd64
CPUs: 8
Total Memory: 57.79 GiB
Name: fc6d0fc27dab
Docker Root Dir: 
Debug Mode (client): false
Debug Mode (server): false
WARNING: No kernel memory limit support
```

docker network ls
```
NETWORK ID          NAME                           DRIVER              SCOPE
18770c3acf02        my-net                          overlay             global              
40d8f3936f6b        swarm-node-0/bridge            bridge              local               
012a913fecd0        swarm-node-0/docker_gwbridge   bridge              local               
d5a10baca56c        swarm-node-0/host              host                local               
1502be232289        swarm-node-0/none              null                local  
```

docker network inspect my-net
```
[
    {
        "Name": "my-net",
        "Id": "18770c3acf02ca2f788515d59d7d3bb39cb90938e8a644789eced507169803ad",
        "Scope": "global",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "10.0.9.0/24"
                }
            ]
        },
        "Internal": false,
        "Containers": {
            "13472881751cb7730ab8dc17a18eda46625b9540f2b6785bf63a9aafa390c64d": {
                "Name": "db-server",
                "EndpointID": "363cb87ca10ef3051742456a83360d918c1300203a32468248b04cf07728a56a",
                "MacAddress": "02:42:0a:00:09:04",
                "IPv4Address": "10.0.9.4/24",
                "IPv6Address": ""
            },
            "335c866e6228ec756670cf7d54a9b52f9340908a6161f44e5bbb29749b044b67": {
                "Name": "db-locator",
                "EndpointID": "8a11831fc403acf34aa6877be80142630156eb2c0919061ad2db96213b3d3f79",
                "MacAddress": "02:42:0a:00:09:03",
                "IPv4Address": "10.0.9.3/24",
                "IPv6Address": ""
            },
            "82d912f0dda2e96066207ae0514a826bc81fcdc2fc52da5e8a068243b3093039": {
                "Name": "hdfs",
                "EndpointID": "b288c55955b4cbb11133ecc8fba5651a836bcf697e23857a5cf9b2090415acc2",
                "MacAddress": "02:42:0a:00:09:02",
                "IPv4Address": "10.0.9.2/24",
                "IPv6Address": ""
            },
            "ca163dde769aa2402a1c2c21c60da5d4892a32018b041e453327fdba8e5906c5": {
                "Name": "server",
                "EndpointID": "4ed63062b2a0dc691618d800f8dc65fac7b8434411a3b928732252b3f948f3c6",
                "MacAddress": "02:42:0a:00:09:06",
                "IPv4Address": "10.0.9.6/24",
                "IPv6Address": ""
            },
            "d77977503b47e55796dbf7161340793ec121bfeecf42402dd79f02fc979c5f12": {
                "Name": "data-dispatcher",
                "EndpointID": "2b7a0973269f28c2b2bec3c8d552e4b6d4cb7e8a566b630cde95dc4348df9339",
                "MacAddress": "02:42:0a:00:09:05",
                "IPv4Address": "10.0.9.5/24",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
```

I don't see my other container in the inspect list which was started using rest API.

**Comment by mavenugo** [comment]
@phagunbaya When you said the clustering mode is swarm, you didnt mean the newly introduced swarm-mode via `docker swarm init`. But you are using classic swarm. Can you pls confirm that ? If yes, i think you should open this issue in https://github.com/docker/swarm to make sure the debugging starts at the right level.

**Comment by phagunbaya** [comment]
I'm using classic swarm setup following this link https://docs.docker.com/swarm/install-manual/

**Comment by phagunbaya** [comment]
I verified it again - if I run `docker run -d --network=my-net ...` NetworkMode is  getting set to my-net. But when trying rest API, it does not use `my-net` as networkMode.

**Comment by thaJeztah** [comment]
First of all; did you set `DOCKER_HOST` to point to the Docker Swarm API? Otherwise,
`docker run...` will talk to the Docker Socket (`/var/run/docker.sock`), and thus
to the *Docker API*, not the Docker *Swarm* API.

I noticed in your original example, that there's a quote missing after `"launch`;
if that's the actual request you're using, that may be part of the issue

Running these command successfully created, and started a `foo` container, connected to the `my-net` network;

```bash
curl -v \
  --unix-socket /var/run/docker.sock \
  http://v1.24/containers/create?name=foobar \
  -H "Content-Type: application/json" \
  -d '{"Image": "nginx:alpine","HostConfig": {"NetworkMode": "my-net"}}'


curl -v \
  --unix-socket /var/run/docker.sock \
  http://v1.24/containers/foobar/start \
  -X POST


docker inspect --format '{{json .NetworkSettings.Networks}}' foobar
```
```JSON
{"my-net":{"IPAMConfig":null,"Links":null,"Aliases":["653ddac13c80"],"NetworkID":"b86f37d65457787fa0f94b26fa6c473ca0d850707286ea79b4f2cb16f17ae75a","EndpointID":"41d8be81848d3b7fdd93b64a281a2dc8f0fa7df3c3a87013adbf7ed61b907811","Gateway":"172.19.0.1","IPAddress":"172.19.0.2","IPPrefixLen":16,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"02:42:ac:13:00:02"}}
```

This could be either a usage error, or a bug in Swarm, but as @mavenugo mentioned
above, this belongs in the Swarm issue tracker (https://github.com/docker/swarm/issues),
so I'll close this here

**Comment by phagunbaya** [comment]
Yes `DOCKER_HOST` is set correctly, also `"launch` was the typo. Actually, I got to the bottom and found that this issue is related to a swarm issue - https://github.com/docker/swarm/issues/1781

Also, if you read my last comment there, it clearly says that there is a gap between swarm start API and docker API.
