### ISSUE TITLE
Failed to start VM "MobyLinuxVM"

### ISSUE THREAD

**Issue by Morgy93** [docker/docker#25443]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      windows/amd64
Error response from daemon: The requested address is not valid in its context.
```

**Output of `docker info`:**

```
Error response from daemon: The requested address is not valid in its context.
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

- Docker for Windows latest (08/05/16 MM/TT/JJ) (there's no version info on the website, nor for the InstallDocker.msi)
- Windows 10 Pro
- version 1607
- build 14393.10

**Steps to reproduce the issue:**
I don't know how to "reproduce", but all I did was to upgrade to the anniversary update and activated the Windows Subsystem for Linux (WSL) for Bash on Ubuntu on Windows
My docker worked just nice before~

**Describe the results you received:**
The VM doesn't start.

**Describe the results you expected:**
The VM does start / boot

**Additional information you deem important (e.g. issue happens only occasionally):**
```
Failed to start VM "MobyLinuxVM": Fehler beim Starten von "MobyLinuxVM".

Fehler beim Starten von "MobyLinuxVM" (ID des virtuellen Computers 5534CC75-8A5C-4BA7-82BC-EB315C4DAA77).

"MobyLinuxVM": Fehler beim Starten des Arbeitsprozesses: Der Prozess wurde unerwartet beendet. (0x8007042B) (ID des virtuellen Computers 5534CC75-8A5C-4BA7-82BC-EB315C4DAA77).
   bei Docker.Core.Pipe.NamedPipeClient.TrySend(String action, Object[] parameters)
   bei Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   bei Docker.Core.Backend.BackendClient.Start(Settings settings)
   bei Docker.Actions.DoStart(Settings settings, Boolean showWelcomeWindow)
   bei Docker.Core.TaskQueue.<.ctor>b__16_0()
```

**Comment by thaJeztah** [comment]
Thanks for reporting; we recently opened a dedicated issue tracker for Docker for Mac and Docker for Windows; could you reopen this issue there?

https://github.com/docker/for-win/issues 

sorry for the inconvenience :blush:
