### ISSUE TITLE
1.12 swarm ingress (--publish) not working 

### ISSUE THREAD

**Issue by nathanleclaire** [docker/docker#25445]
Hi, I really wish I had a good duplicate but it seems very particular to this machine and setup, so I will try and just report the info I have and see if @mrjana @mavenugo you have any ideas.  Long story short, `--publish` / `ingress` network is busted on my home Linux computer running Debian Jessie kernel 4.5.0.

**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:40:59 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:40:59 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 15
Server Version: 1.12.0
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge overlay null
Swarm: active
 NodeID: cga19wwwylu0tz1flt7won5pu
 Is Manager: true
 ClusterID: 0se6fx0sh9smbsrzfo3v9j2ko
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot interval: 10000
  Heartbeat tick: 1
  Election tick: 3
 Dispatcher:
  Heartbeat period: 5 seconds
 CA configuration:
  Expiry duration: 3 months
 Node Address: 192.168.1.9
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 4.5.0-0.bpo.2-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.57 GiB
Name: neuromancer
ID: TSOT:VU5W:HW75:FA6D:YDHD:CJGO:VVUJ:GAT5:5RWT:4VTF:SYHJ:GR47
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: nathanleclaire
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Describe the results you received:**

`ingress` network in Swarm mode is busted on this machine but I'm not 100% sure why.  If I do a command like:

```console
$ docker service create --publish 80:80 nginx
```

Then I would expect `curl localhost` to work fine, but instead it just hangs.

[Here is a gist with output of some local commands and suspicious docker log output to take a look at](https://gist.github.com/nathanleclaire/22a2d1ab72ed7e18d13db5a5a3a26ce8).

@mrjana Any thoughts?  Any additional information you'd like to collect?  I've tried nuking `/var/lib/docker` and `sudo apt-get purge -y docker` and re-installing, but that does not help.  The problem continues to persist.  No firewall, AppArmor, etc. that I'm aware of.  I can post `dmesg` if you think it'd be helpful but there's a lot going on in there.

**Comment by thaJeztah** [comment]
can you try `curl -4 localhost`? perhaps it's bound to IPv6 only; seen that on other issues

**Comment by nathanleclaire** [comment]
@thaJeztah for the win.  `curl -4 localhost` worked.

**Comment by thaJeztah** [comment]
thanks, this is a known issue, and either resolved already, or at least tracked; but ask on slack which one of those (on my phone now :wink:)

**Comment by nathanleclaire** [comment]
cool :+1:

**Comment by nathanleclaire** [comment]
FWIW, (and I know this would be hard to track down), I also encountered an issue here where even contacting `127.0.0.1` directly would hang after the service had been up a while :(

**Comment by thaJeztah** [comment]
Wondering if it's still mapped to IPv6 https://en.m.wikipedia.org/wiki/IPv6#IPv4-mapped_IPv6_addresses
