### ISSUE TITLE
KeepOldSnapshots is exposed in API but not CLI

### ISSUE THREAD

**Issue by aaronlehmann** [docker/docker#25451]
There is a KeepOldSnapshots parameter which controls how many old Raft snapshots to keep. By default it is set to 0. It is supported in the Docker API, but there is no CLI support for displaying or changing this parameter.

It's not an especially high priority to support it, but it seems inconsistent to have this in the API but not the CLI.

**Comment by aaronlehmann** [comment]
Just noticed this is not wired up in SwarmKit. So it will take more work than just adding a CLI flag.

**Comment by dperny** [comment]
There are a bunch of Raft tuning options that should be exposed on Swarm Init and don't seem to be, this being one of them. If you'd like, I can work on a PR for the docker CLI side.

**Comment by aaronlehmann** [comment]
Some of the other raft options are a bit more tricky because they are hard to update once the cluster is already running. For those, the best approach is probably:

- Only allow them to be set on `swarm init`, not `swarm update`.
- The raft `Join` RPC should include a RaftConfig object in its results so new nodes that join know what settings to use.

`KeepOldSnapshots` and `LogEntriesForSlowFollowers` don't have these constraints, so they're a little easier to deal with. They could either be implemented in the same PR as the other settings, or separately.

The first step is probably a SwarmKit PR to make the manager respect the `RaftConfig` values in the `ClusterSpec` when it starts raft. However, I think #24958 might be a prerequisite for this, because right now, the default cluster spec is always used at first and then updated later by the engine, and this is kind of broken.

**Comment by aaronlehmann** [comment]
Fixed by #27997.
