### ISSUE TITLE
Swarm mode rolling update quiet period

### ISSUE THREAD

**Issue by coding2012** [docker/docker#25464]
I've been playing around with Docker services commands... finding them very awesome. Anyway I noticed one particular issue with rolling updates on a Node app. I found that while the rolling updates are occurring I can keep hitting refresh in my browser and sometimes I get bad pages or incomplete REST requests. I take it that's because one of the nodes is in the middle of starting still.

Would be cool if as part of the docker service update command there can be a --quiet-period where the node is basically treated as non-connectable. In other words, as long as there are similar services available, nothing would route to the recently upgraded container until a set "quiet period". This would allow for such containers to perform whatever initialization before they are fully ready to accept connections.
Loving swarm mode btw, can't believe how simple awesome it is out of the box. Must have been an engineering challenge to build!

**Comment by gngeorgiev** [comment]
Indeed I think that the problem is that your node application is still starting. How about adding a custom `HEALTHCHECK` which will make an HTTP request to you application?

**Comment by cpuguy83** [comment]
It may also be your browser caching the connection.

**Comment by coding2012** [comment]
Thanks @gngeorgiev That's a feature I completely overlooked! Sorry about the spam in that case!

**Comment by gngeorgiev** [comment]
@coding2012 It's far from spam. I am quite sure it will help someone in the future.
