### ISSUE TITLE
x509 certificate signed by unknown authority

### ISSUE THREAD

**Issue by thecb4** [docker/docker#25469]
Question -- I am trying to use docker 1.12 on Ubuntu 14.04 behind a proxy and I am getting the following error "x509: certificate signed by unknown authority".  The proxy is not HTTPS.  All of the documentation points to using the signing certificate from the proxy but what do you do when you don't have a signing certificate from the proxy?  I've used "X"s for the IPs of the proxys in the docker info output.

**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay host bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-92-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: GIS08595
ID: 3MK7:OCGA:ABDX:7RGD:4D3S:UYJL:6UCT:MB5E:KDXB:4G6V:FY76:NOVX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://X.XXX.XX.XXX:XXXX/
Https Proxy: http://X.XXX.XX.XXX:XXXX/
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Linux GIS08595 3.13.0-92-generic #139-Ubuntu SMP Tue Jun 28 20:42:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
Thanks for opening, but the GitHub issue tracker is not really a general support forum for running docker; the issue tracker is for tracking bugs, and feature requests; could you use either one of;

- forums.docker.com
- the #docker IRC channel
- StackOverflow

I'm closing this issue here, but feel free to comment after I closed
