### ISSUE TITLE
Error message less comprehensive since Docker 1.12

### ISSUE THREAD

**Issue by roukmoute** [docker/docker#25470]
For the same command:

- Before 1.12: `docker: Error response from daemon: Container command '/entrypoint.sh' not found or does not exist..`
- Since 1.12: `standard_init_linux.go:175: exec user process caused "no such file or directory"`

**Comment by thaJeztah** [comment]
ping @mlaventure PTAL

**Comment by mlaventure** [comment]
This changed came from #23129

We could change the code to have the old messages with the original error appended between `()`.

WDYT @thaJeztah ?

**Comment by thaJeztah** [comment]
@mlaventure sounds good to me; alternatively; could `containerd` return a more useful message (i.e., does it have the path/name of the command it tries to invoke?)

**Comment by mlaventure** [comment]
`containerd` doesn't look at that information, it just passes the bundle straight to the selected runtime and in just forward the error runtime straight back to `docker`

**Comment by thaJeztah** [comment]
fixed by https://github.com/docker/docker/issues/27160
