### ISSUE TITLE
service --mount type=bind creates path on host, but shouldn't

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#25484]
Unlike `docker run` (where this behavior is present to preserve backward compatibility), `docker service create` should _not_ create paths on the host for bind-mounts.

This is also described in [the documentation](https://github.com/docker/docker/blob/861d4dc989ae738a1c219291a96333a7577b1699/docs/swarm/services.md#configure-mounts);

> Bind mounts are file system paths from the host where the scheduler deploys the container for the task. Docker mounts the path into the container. **The file system path must exist before the swarm initializes the container for the task.**

However, currently (1.12.0), the host path is automatically created if it doesn't exist:

```bash
$ ls /does-not-exist/
ls: cannot access '/does-not-exist/': No such file or directory

$ docker service create --mount type=bind,source=/does-not-exist,target=/here/i/go --name=test nginx:alpine


$ ls -la /does-not-exist/
total 8
drwxr-xr-x 2 root root 4096 Aug  8 05:50 .
drwxr-xr-x 3 root root 4096 Aug  8 05:50 ..
```

We should change this, before users start to rely on this behavior, and we can no longer remove it

**Comment by thaJeztah** [comment]
ping @cpuguy83 @tiborvass @stevvooe PTAL

**Comment by justincormack** [comment]
That would mean scheduling a service might fail on some nodes, but I guess thats ok.

**Comment by cpuguy83** [comment]
Yep, most definitely. And should go here: https://github.com/docker/docker/blob/master/daemon/cluster/executor/container/validate.go#L22

**Comment by thaJeztah** [comment]
Oh, that looks simple; I can have a look #dibs
