### ISSUE TITLE
Renaming service doesn't rename service tasks / containers

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#25483]
Renaming a service doesn't rename/update the services's containers/tasks:

```bash
$ docker service create --name web nginx:alpine
9qmzbansw53tteaocl2uhgf3v

$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                  PORTS               NAMES
e4e8461a30d2        nginx:alpine        "nginx -g 'daemon off"   1 seconds ago       Up Less than a second   80/tcp, 443/tcp     web.1.2onlllux6w6haprqyjpzyx2fz

$ docker service update --name frontend web
web

$ docker ps

CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
e4e8461a30d2        nginx:alpine        "nginx -g 'daemon off"   2 minutes ago       Up 2 minutes        80/tcp, 443/tcp     web.1.2onlllux6w6haprqyjpzyx2fz
```

New containers/tasks _are_ named after the new service name:

```bash
$ docker service update --replicas=2 frontend
frontend

$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
dd3d2f10b9ec        nginx:alpine        "nginx -g 'daemon off"   11 seconds ago      Up 10 seconds       80/tcp, 443/tcp     frontend.2.38oyjutl1ljis0a3n2psimmfd
e4e8461a30d2        nginx:alpine        "nginx -g 'daemon off"   3 minutes ago       Up 3 minutes        80/tcp, 443/tcp     web.1.2onlllux6w6haprqyjpzyx2fz
```

It becomes more confusing if you *inspect* the containers;

```

$ docker inspect frontend.2.38oyjutl1ljis0a3n2psimmfd

"Labels": {
      "com.docker.swarm.node.id": "f0k5s1khmlk9d0fnnbt3fmchx",
      "com.docker.swarm.service.id": "9qmzbansw53tteaocl2uhgf3v",
      "com.docker.swarm.service.name": "frontend",
      "com.docker.swarm.task": "",
      "com.docker.swarm.task.id": "38oyjutl1ljis0a3n2psimmfd",
      "com.docker.swarm.task.name": "frontend.2"
  }
            
            
$ docker inspect web.1.2onlllux6w6haprqyjpzyx2fz

"Labels": {
    "com.docker.swarm.node.id": "f0k5s1khmlk9d0fnnbt3fmchx",
    "com.docker.swarm.service.id": "9qmzbansw53tteaocl2uhgf3v",
    "com.docker.swarm.service.name": "web",
    "com.docker.swarm.task": "",
    "com.docker.swarm.task.id": "2onlllux6w6haprqyjpzyx2fz",
    "com.docker.swarm.task.name": "web.1"
}
```

Or create a new `web` service now

**Comment by thaJeztah** [comment]
ping @stevvooe @aluzzardi PTAL

**Comment by stevvooe** [comment]
This will only have an effect on tasks created after the rename. We have it plumbed it for updates, but I'm worried about the effects of changing names in general. Put another way, we built this to be able to work, but don't have a model for the guarantees provided by rename.

I am not sure what the effect would be on DNS. cc @mrjana @mavenugo

**Comment by aluzzardi** [comment]
Oh - yeah. I don't know the impact on networking, I don't know if this would work.

If it doesn't we should probably block this. @mrjana ?

**Comment by stevvooe** [comment]
> I don't know if this would work.

I am surprised it made it into the `service update` command.

**Comment by thaJeztah** [comment]
I'm adding this to the 1.12.1 milestone; looks like we need a decision on this asap (one way or the other).

@mrjana I'll assign you for now

**Comment by thaJeztah** [comment]
ping @mrjana PTAL

**Comment by stevvooe** [comment]
@thaJeztah We may never support this, but it is possible. Let's consider whether or not this worth the complexity, as the rename would almost never be coordinated.

An easy fix might be to ensure the name change on ServiceSpec.Annotations propagates to the task definition. In that case, everything would be redeployed with a rename. I am not sure that this is expected behavior.

**Comment by thaJeztah** [comment]
@stevvooe with any other "update", all tasks/containers are redeployed, so from that PoV, I think it would make sense to do so. But that's my 0.02c, and from a "user" perspective (not taking technical complexity into account)

**Comment by stevvooe** [comment]
> with any other "update", all tasks/containers are redeployed, so from that PoV, I think it would make sense to do so.

This is not necessarily true. Only updates that will affect the created tasks. It is unclear whether that is the case here.

Honestly, I don't know what the right behavior should be here.

**Comment by thaJeztah** [comment]
> Only updates that will affect the created tasks

Given that the container name / task name is based on the service name, I'd say that a rename affects the tasks.

Although I can understand if we decide to make "renaming" no longer possible (which, probably, would require a deprecation..)

**Comment by stevvooe** [comment]
> Although I can understand if we decide to make "renaming" no longer possible (which, probably, would require a deprecation..)

To tell you the truth, I am not sure how this squeaked its way in.

**Comment by icecrime** [comment]
@al Do you consider this a bug? I'm going to remove from the 1.12.2 milestone as it doesn't seem crucial.

**Comment by xiaods** [comment]
yes, please PTAL

**Comment by mrjana** [comment]
If we don't trigger a rolling update on service name change it would affect service discovery. So if we are not already doing so either we block name update in service or trigger a rolling update.

**Comment by al** [comment]
Not the right @al.

**Comment by thaJeztah** [comment]
Apologies @al, that should've been @aluzzardi (he uses "@al" on the internal Slack channel :smile:)

**Comment by thaJeztah** [comment]
@stevvooe I haven't seen a discussion on that (if it was implemented on purpose), but possibly that took place in the SwarmKit repo

**Comment by xiaods** [comment]
update on swarmkit?

**Comment by stevvooe** [comment]
Let me put this differently: renaming of services should not be supported. This is a broken feature and should have never been introduced.

We'll need to prevent this on the swarm manager and remove the flag.

**Comment by thaJeztah** [comment]
@stevvooe @icecrime I opened a PR for discussion https://github.com/docker/docker/pull/26988
