### ISSUE TITLE
Missing '--driver none' in the document: 'get-started-cloud.md'

### ISSUE THREAD

**Issue by twang2218** [docker/docker#25485]
In the section "Adding a host without a driver" of the document, "Use Docker Machine to provision hosts on cloud providers", <https://docs.docker.com/machine/get-started-cloud/#adding-a-host-without-a-driver>

There is an example:

```bash
$ docker-machine create --url=tcp://50.134.234.20:2376 custombox
$ docker-machine ls
NAME        ACTIVE   DRIVER    STATE     URL
custombox   *        none      Running   tcp://50.134.234.20:2376
```

However, the command will fail under `docker-machine 0.8.0`, as there should be `-d none`, so the example should be:

```bash
$ docker-machine create --driver none --url=tcp://50.134.234.20:2376 custombox
$ docker-machine ls
NAME        ACTIVE   DRIVER    STATE     URL
custombox   *        none      Running   tcp://50.134.234.20:2376
```

**Comment by vdemeester** [comment]
@twang2218 thanks for the issue. As the source file for this documentation are in the `docker/machine` repository (https://github.com/docker/machine/blob/master/docs/get-started-cloud.md), I think this issue should be done there instead of in `docker/docker` (and definitely the PR).

**Comment by twang2218** [comment]
Yes, I posted in the wrong repo, sorry.

**Comment by vdemeester** [comment]
@twang2218 no problem :wink:
