### ISSUE TITLE
How to build high-available swarm cluster

### ISSUE THREAD

**Issue by aleksejlopasov** [docker/docker#25489]
Is there a possibility to build high-available swarm cluster with more than one master-node in new docker -engine 1.12? I think '1 master-node + N worker-node' is not a fault-tolerant solution. But there is no information about building multi-master HA configuration in docker documentation

**Comment by dverbeek84** [comment]
Just follow this guide https://docs.docker.com/engine/swarm/
And joint other nodes as manager. The replication is based on the Raft Consensus just like etcd and Consul.

**Comment by thaJeztah** [comment]
High availability is described in https://docs.docker.com/engine/swarm/admin_guide/

I'll close this issue because I think the question is answered, but feel free to comment if you think additional information is needed in the documentation
