### ISSUE TITLE
VOLUME seems work not as expected when run container with --volumes-from

### ISSUE THREAD

**Issue by BrickXu** [docker/docker#25486]
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 134
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 119
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-92-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.35 GiB
Name: xulei-ThinkPad-W530
ID: AMUO:ZLXA:UTSO:R7BG:RFJT:MVW4:FG45:OVQT:XPEX:6B4Z:JOZ7:76NN
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Http Proxy: http://127.0.0.1:8118
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
laptop

**Steps to reproduce the issue:**
Build the image with `VOLUME` like following:
```
FROM ubuntu:14.04

RUN apt-get update
RUN apt-get install -y libapparmor-dev libltdl-dev libsystemd-journal-dev

VOLUME ["/var/lib/mesos"]
```
Then run a container with the command line:
```
docker run -it -v /usr/bin/docker:/usr/bin/docker -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/var/lib/mesos --name outer volumes /bin/bash
# in container
root@7723077d630e:/#mkdir -p /var/lib/mesos/slaves/outer/
```
Check the `docker volume ls`:
```
$ docker volume ls
DRIVER              VOLUME NAME
```
Run another container in the container `outer`:
```
# in the outer container run this
docker run -it -v /usr/bin/docker:/usr/bin/docker -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/mesos/slaves/outer:/mnt/mesos/sandbox --volumes-from outer --name inner volumes /bin/bash
# in the inner container
root@1f9870c7794f:/#cd /mnt/mesos/sandbox
root@1f9870c7794f:/mnt/mesos/sandbox# touch from_inner
```
And check `docker volume ls`:
```
$ docker volume ls
DRIVER              VOLUME NAME
```
In my host directory `/tmp/slaves/outer`, I did not find any files that named `from_inner`:
```
➜  outer pwd
/tmp/slaves/outer
➜  outer ll
total 0
```
But in another host directory `/var/lib/mesos/slaves/outer`, I found the file:
```
➜  outer pwd
/var/lib/mesos/slaves/outer
➜  outer ll
total 0
-rw-r--r-- 1 root root 0  8月  8 19:11 from_inner
```

**Describe the results you received:**
no local volumes found in docker, but here is a new directory which name is the same as `VOLUME` in the host OS, and the file has been written to the new directory.

**Describe the results you expected:**
I think it should write to the `/tmp/slaves/outer/` instead of `/var/lib/mesos/slaves/outer`.

**Comment by thaJeztah** [comment]
First of all, you're not using volumes, only bind-mounted directories. Note that
`--volumes-from` is just a convenience flag for not having to specify the same
options on multiple containers, for example:

```bash
docker run -dit -v /foo:/bar --name first busybox sh

docker run -dit --volumes-from first --name second busybox sh
```

And you'll see that the volume definition from `first` is "copied" in the
definition of `second`:

```
docker inspect --format '{{ json .Mounts }}' second
[{"Source":"/foo","Destination":"/bar","Mode":"","RW":true,"Propagation":"rprivate"}]

docker inspect --format '{{ json .Mounts }}' first
[{"Source":"/foo","Destination":"/bar","Mode":"","RW":true,"Propagation":"rprivate"}]
```

In your case, you're **not** running docker-in-docker, but you're basically
running all containers directly on the host; you're only bind-mounting the docker
socket, and the docker client binary, but effectively controlling the docker daemon
that's running on the host; basically, what you're running is:


docker run -it -v /tmp:/var/lib/mesos --name outer volumes bash
docker run -it -v /var/lib/mesos/slaves/outer:/mnt/mesos/sandbox --volumes-from outer --name inner volumes /bin/bash

if we take the `--volumes-from` into account and "translate" that to the actual volumes (bind-mounts) that
docker creates, this becomes;



docker run -it -v /tmp:/var/lib/mesos --name outer volumes bash
docker run -it \
  -v /var/lib/mesos/slaves/outer:/mnt/mesos/sandbox \
  -v /tmp:/var/lib/mesos \
  --name inner volumes /bin/bash

So, the first container:

 - bind-mounts the `/tmp` directory on the host at `/var/lib/mesos` in the container

ANd the second container:

 - bind-mounts the `/var/lib/mesos/slaves/outer` directory on the host at `/mnt/mesos/sandbox` in the container
 - *also* bind-mounts the `/tmp` directory on the host at `/var/lib/mesos` in the container


There are *no* volumes, only bind-mounted directories, so `docker volumes` won't show anything

Looking at the above, I don't see a bug here, so I'll close this issue, but feel free to continue the conversation

**Comment by BrickXu** [comment]
@thaJeztah thanks for your response so quickly.
