### ISSUE TITLE
When I create a container with --mount option - "no such device"

### ISSUE THREAD

**Issue by cristhianbicca** [docker/docker#25499]
When I create a container with --mount option.
When running ```docker service ps servicename ``` appears as:

ID NAME IMAGE NODE DESIRED STATE CURRENT STATE ERROR
1n8jym44ewn99shlw1ook2cgw web2.1 nginx ip-172-31-42-130.us-west-2.compute.internal Ready Preparing less than a second in August
9w1pc2f1pcobx1aekzu974hlh \ _ web2.1 nginx ip-172-31-42-130.us-west-2.compute.internal Shutdown Rejected less than a second ago "no such device"
0pzvlrj61si1dxtianp9v9ofh \ _ web2.1 nginx ip-172-31-42-130.us-west-2.compute.internal Shutdown Rejected 5 seconds ago "no such device"
15e0raq46vv967h83qclobqh0 \ _ web2.1 nginx ip-172-31-42-130.us-west-2.compute.internal Shutdown Rejected 10 seconds ago "no such device"
27scsf4wll1hy67yd0p1f7qws \ _ web2.1 nginx ip-172-31-42-130.us-west-2.compute.internal Shutdown Rejected 15 seconds ago "no such device"

**Comment by cpuguy83** [comment]
@cristhianbicca Please provide the whole command.

**Comment by cristhianbicca** [comment]
@cpuguy83 
docker service create --name web3 -p 9091:80 --mount type=bind,source=foo,target=/usr/share/nginx/html --replicas 1 nginx

**Comment by cpuguy83** [comment]
@cristhianbicca source must be an absolute path. We added a check for this for the next patch release.

**Comment by cristhianbicca** [comment]
@cpuguy83  Could you give me an example?

**Comment by cpuguy83** [comment]
@cristhianbicca `source=/foo` not `source=foo`

**Comment by thaJeztah** [comment]
Are you trying to bind-mount a directory on the host, or mounting a volume? In case of a volume, `source` refers to the *name* of the volume, in case of a bind-mount, `source` refers to the path on the host you're bind-mounting, so for example:

**Bind-mount `/var/log` at `/foo/bar/` inside the container**

```bash
docker service create --mount type=bind,source=/var/log/,target=/foo/bar/ --name test nginx:alpine
```

**Create/use volume `my-volume` and mount it at `/some/path/` in the container**

```bash
docker service create --mount type=volume,source=my-volume,target=/some/path/ --name=web nginx:alpine
```

**Comment by thaJeztah** [comment]
I'll close this issue, because this does not look like a bug, but we are aware that documentation for `--mount` is still largely missing, and is currently worked on; we're tracking that through https://github.com/docker/docker/issues/24277

Thanks for reporting, feel free to continue the discussion after I closed this issue 👍

**Comment by cristhianbicca** [comment]
@cpuguy83  @thaJeztah 
thank you
Open this forum because of the difficulty to find documentation about it.
Thank you
