### ISSUE TITLE
docker systemd service environment settings not propagated to docker commands

### ISSUE THREAD

**Issue by adrianovieira** [docker/docker#25491]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 7
 Running: 1
 Paused: 0
 Stopped: 6
Images: 2
Server Version: 1.12.0
Storage Driver: devicemapper
 Pool Name: docker-253:0-394340-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.358 GB
 Data Space Total: 107.4 GB
 Data Space Available: 37.13 GB
 Metadata Space Used: 3.039 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay host null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.22.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.797 GiB
Name: fazenda
ID: C3DB:3GZE:WC2U:LJYL:DTYN:VDJH:QZFV:AMYT:AMZD:MX6S:W3QB:WHDR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://10.122.19.137:5865/
Https Proxy: http://10.122.19.137:5865/
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

- `cat /etc/systemd/system/docker.service.d/proxy.conf`
```
[Service]
Environment='HTTPS_PROXY=http://proxy:port/' 'HTTP_PROXY=http://proxy:port/'
```

**Steps to reproduce the issue:**
1. Create a conf file for docker systemd service
2. run a container which need that environment variable value (e.g `docker run -i sample_image curl <http://some_sandbox>`

**Describe the results you received:**
Container don't have access the that environment variable settings on docker systemd service.

e.g. (behind the proxy) curl or wget cant access internet inside the container. It's necessary to pass `docker run --env https_proxy=[...]`.

**Describe the results you expected:**
If I setup a docker systemd service environment variable for any "app, service, container etc" I hope docker would use that on most or every command I do (`docker run`, `docker exec` etc).

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment]
I don't think it would necessarily be correct to automatically set proxy values inside containers. These proxy values often contain credentials which could cause an issue if this is loaded into the container env.
The proxy values ARE used by the daemon, for instance when it needs to pull an image.

**Comment by adrianovieira** [comment]
proxy is only one example configuration, we can abstract to other environment variables that were put there for a real running container.

If I need to setup some MYSERVICE_ENV_VAR on a docker systemd service  conf file it could use that.

**Comment by cpuguy83** [comment]
@adrianovieira Nope, this is wrong. Just because something is in the docker daemon's env does not mean it should ever propagate to containers... and likewise you shouldn't have to set an environment variable that is completely useless to the docker daemon to have that propagate into a container.
There might be a case here for a daemon setting for setting envs that should go to all containers.

**Comment by adrianovieira** [comment]
I see.

Thanks.

**Comment by thaJeztah** [comment]
I agree with @cpuguy83 here; propagating these to the containers doesn't sound like the right thing to do. I'll close this issue, but feel free to continue the discussion
