### ISSUE TITLE
Coping something to /usr break the image

### ISSUE THREAD

**Issue by ttres** [docker/docker#25501]
After coping some content to `/usr` dir, the built image is broken with `error while loading shared libraries: libtinfo.so.5: cannot open shared object file: Permission denied`.

This the simplest Dockerfile that reproduces the issue:

```
FROM rhel7:7.2
RUN groupadd group && \
    useradd --create-home --shell /bin/bash --gid group user

COPY usr /usr
USER user
```

The content of `usr` folder copied is (can be anything):

```
$ tree usr/
usr/
└── lib64
    └── file.txt

1 directory, 1 file
```

**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 8
 Running: 0
 Paused: 0
 Stopped: 8
Images: 738
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 804
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay host bridge null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.19.0-65-generic
Operating System: Ubuntu 14.04.5 LTS (containerized)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.762 GiB
Name: ES96001206800102236
ID: 6G6X:CTGE:5ISG:4TFN:7FUE:HCOB:RZTW:L4FV:O6EC:EHGK:XFWG:JB4Z
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Steps to reproduce the issue:**
1. Build the image: `docker build --rm --tag=name:version -f Dockerfile .`
2. Run the container: `docker run --rm -ti name:version`

**Describe the results you received:**
The container does not start. This is the error message in the output:

```
/bin/bash: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: Permission denied
```
Inside the container I can see that `/usr/lib64` permission was changed to 770, instead of 755 (because of the copy?).

**Describe the results you expected:**
The shell prompt is the expected result. It is possible to access the container if `-u root` parameter is used in the `run` command. 

**Additional information you deem important (e.g. issue happens only occasionally):**
This issue is always reproducible with the given Dockerfile.

**Comment by justincormack** [comment]
I think this is an overlay kernel bug.

**Comment by AkihiroSuda** [comment]
@justincormack you meant, aufs :smiley: ?

**Comment by justincormack** [comment]
Oh, looking again, it looks like the files under the directory being copied, including the `lib64` directory, are created with the permissions that they have on the filesystem, even if they already exist. So if you change the permissions in your directory that is copied in to `755` it should work as expected. I can see that could be confusing, although arguably wither way would be correct, I think it is reasonable for the later copy to override what was there. You could also use `COPY /usr/lib64 /usr/lib64/`.

**Comment by ttres** [comment]
Yes, @justincormack, you're right, the permissions inside the image were set over the permissions from the base image.

My mistake was not paying attention to the local permissions of the origin files.

Conclusion #protip: always check the local files permissions before `COPY`.
