### ISSUE TITLE
Can't get to work systemd on docker 1.12

### ISSUE THREAD

**Issue by satyajitbm** [docker/docker#25516]
When I moved from docker 1.11 to 1.12, I am unable to get systemd up. 

**Output of `docker version` in 1.11:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info` in 1.11:**

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 15
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker-253:0-1074742314-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.03 GB
 Data Space Total: 107.4 GB
 Data Space Available: 105.3 GB
 Metadata Space Used: 3.445 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 3.10.0-229.20.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.24 GiB
Name: sim11.mvnsgperf02.mv.nuagenetworks.net
ID: 67UP:HK5J:ZLTG:3EN2:44DZ:IEGU:HE25:BMB7:WZXG:S7EP:QPZZ:4EGV
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: IPv4 forwarding is disabled
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Output of `docker version` in 1.12:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:
 OS/Arch:      linux/amd64
```

**Output of `docker info` in 1.12:**

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 15
Server Version: 1.12.0
Storage Driver: devicemapper
 Pool Name: docker-253:0-1074742314-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.03 GB
 Data Space Total: 107.4 GB
 Data Space Available: 105.3 GB
 Metadata Space Used: 3.445 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host overlay bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-229.20.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.24 GiB
Name: sim11.mvnsgperf02.mv.nuagenetworks.net
ID: 67UP:HK5J:ZLTG:3EN2:44DZ:IEGU:HE25:BMB7:WZXG:S7EP:QPZZ:4EGV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):** I am running it in a Centos 7.1.1503 bare metal.
Linux <hostname> 3.10.0-229.20.1.el7.x86_64 #1 SMP Tue Nov 3 19:10:07 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Steps to reproduce the issue:**
1. `docker run -itd --cap-add=SYS_ADMIN --hostname=ssh-server --name=ssh-server -v /sys/fs/cgroup centos:7 /usr/sbin/init`
2. `docker exec -it ssh-server yum install -y openssh-server`
3. `docker exec -it ssh-server systemctl start sshd`
4. `docker exec -it ssh-server systemctl status sshd`

**Result I received in 1.11:**
```
sshd.service - OpenSSH server daemon
   Loaded: loaded (/usr/lib/systemd/system/sshd.service; enabled; vendor preset: enabled)
   Active: active (running)
```

**Result I received in 1.12:**
```
docker exec -it ssh-server systemctl start sshd                                  
Failed to get D-Bus connection: Operation not permitted
```

Since I have added the `SYS_ADMIN` capability, I expect the behavior to be consistent in both versions. Also, is there a better way to use systemd in docker?

**Comment by thaJeztah** [comment]
The change most likely is because Docker 1.12 added support for `seccomp` on CentOS 7 (see `Security Options: seccomp` in the output of `docker info` (https://docs.docker.com/engine/security/seccomp/). Seccomp blocks certain syscalls to make containers more secure by default, but systemd is quite demanding, so fails to run because of that. 

If you disable seccomp for that container (`--security-opt seccomp=unconfined`), it should probably work, however, it looks like you're not bind-mounting `/sys/fs/cgroup` (which is required for systemd to function afaik), and systemd expects an environment variable in the container to know that it's running in a container.

This seems to work for me;

```bash
docker run -itd \
  --security-opt seccomp=unconfined \
  --cap-add=SYS_ADMIN \
  -e "container=docker" \
  -v /sys/fs/cgroup:/sys/fs/cgroup \
  --hostname=ssh-server \
  --name=ssh-server \
  centos:7 /usr/sbin/init
```

Better would be to run it with a custom seccomp profile that allows the exact calls that systemd needs.

In your particular case (running an SSH server), do you really need systemd for that? There's a (very basic) example to run an SSH service in a container in the documentation; https://docs.docker.com/engine/examples/running_ssh_service/ 

That example does not require *any* additional privileges, so is more secure out of the box

**Comment by satyajitbm** [comment]
It works after I applied the env, seccomp and /sys/fs/cgroup changes. Thank you for pointing it out. 

My application uses systemd and I used the ssh server to illustrate the problem I faced. I'll stick with disabling seccomp.

**Comment by thaJeztah** [comment]
We looked into why this wasn't working with seccomp enabled, and suspect there was a change in systemd; a pull-request was merged (https://github.com/docker/docker/pull/25567) that updates the default seccomp profile, and should resolve this issue (i.e. you can run without disabling seccomp). That change will most likely be included in an upcoming patch update (1.12.1)

**Comment by satyajitbm** [comment]
Thank you @thaJeztah.

**Comment by nmagerko** [comment]
Sorry to bring this back up, but what would I need to pass in order to get this to work? I'm having the same issue when running `docker run -i -t [tag] /bin/bash` on 1.12.3. I'll open another issue if necessary, but I was hoping to check in here first.
