### ISSUE TITLE
docker-emu 

### ISSUE THREAD

**Issue by necrose99** [docker/docker#25517]
https://github.com/necrose99/Docker-Gentoo-ARM64

Building in Docker Cloud's infrastructure... Starting to clone Cloning into '.'... 
Cloning done Starting Build KernelVersion: 4.4.0-31-generic Os: linux BuildTime: 2016-06-01T22:00:43.211343203+00:00 ApiVersion: 1.23 Version: 1.11.2 GitCommit: b9f10c9 Arch: amd64 GoVersion: go1.5.4 Starting build of index.docker.io/necrose99/gentoo-arm64:latest... 
Step 1 : FROM scratch ---> 
Step 2 : MAINTAINER Necrose99 --->
 Running in 0f08422094c8 ---> 
9a8b9cb491e4 **Removing intermediate container 0f08422094c8**  
(oh no i want to hang on till the end hear... nuts) 
Step 3 : ADD http://distfiles.gentoo.org/experimental/arm64/stage3-arm64-20160324.tar.bz2 / ---> 8b69cd908dea Removing intermediate container dcc4601a2242 
Step 4 : RUN mkdir {/packages,/usr/portage,/usr/portage/distfiles} && ln -s /packages /usr/portage/packages ---> 
Running in 47cb1c16de52 **Removing intermediate container** 47cb1c16de52 
Container command '/bin/sh' not found or does not exist.

anyhow I'd welcome some API tags or things to let docker know this is an emulation container , and to do all steps but perhaps i need a builder-sh to do more prep. but was trying to keep it simple. 
any tips appreciated, 

http://i.imgur.com/2ffs83M.png   works in virtual-box  albeit really damb slow. compiles. 
http://pastebin.com/FAzQAJ5T 
though any mounts to the chroot die as emu loads. :-(  thus plumping disk usage.. )
anyhow getting enough to spin up the container and let docker-hub build would be a plus. 
till i get a new 1TB SDB or # laptop volume replacement i'm puking on disk-space and the means of building further on a local then uploading as a sqaushed container from Sabayon/Gentoo Linux

**Comment by thaJeztah** [comment]
Thanks for sharing; however, the GitHub issue tracker is for reporting bugs, for general, non bug related discussions, https://forums.docker.com is a more suitable place, so I'll close this issue here

**Comment by necrose99** [comment]
no problem , just for docker containers , it would be nice to specify in docker file 
this container wont run till step X , it can run emulator or not run the emu if on native hardware. 

A: on native hardware , (no all that many arm64 docker servers/hosts) 
 or 
B) inside of another host container/local host ruining Emulator load step.  ie run this bash script. 

unfortunately  i'll Have to zip my tools into another docker container  add it as a dependency .

dockerfiles cant hold the door open for just 30 more seconds of docker-hub base container...  (load the tools) add symlinks etc... or make a sandwich (keep the minimal , but in a transparent to user/s) add on emulator run emu script, for container on top of... 

also could specify a core container for  ie use gentoo/else linux-amd-64 , run the loader script for emulator  however host container just supports emu and isnt visible to users. 

anyhow some Future state features , with regards to emulated -containers would be a nicety .
ie one could keep basic docker Linux but run scripts to chroot to a volume ...  your Linux /emulated... 
or get a host volume hide it from users...
or if native hosts drop tools and scripts... 
API future state features that can handle better docker emulated containers better and cleaner I guess is more my point. 

if I added the tools to a volume , it would work , just a lot more messy.  if the container was pulled. 

if on non native host , add it as a volume... chroot (**proot** run emulator binformat chroot)  to it... 
else native just be a pure container ... 

unfortunate one cant spec this currently, or tell docker-hub  requires Linux-x64-bash to run emulator. (from ie native host or another docker)  
make native host invisible..... run emu , wala.  

anyhow hoping to see better emu API'S down the line.   
or things to add to docker file for emu-volume ?
emu-host=amdx64 
emu-command= proot $cwd..... 
add-emu=url ,url2 
add-emu-scripts=url

if on native hardware docker would just ignore those... 

theirs got to be a cleaner/better way longer term but so be it I can see about reworking it for now, 

anyhow I'll watch to see if better API's for Emulator containers come down the pipeline , as improvements for docker. 

or if there were better takes /tips i'll take them for now.
