### ISSUE TITLE
ARM & Power CI: test panic: close of closed channel

### ISSUE THREAD

**Issue by tophj-ibm** [docker/docker#25538]
ARM & Power CI's are failing with this go error message across different tests. 
Looks to be introduced in #20848.

Logs
ARM: https://jenkins.dockerproject.org/job/Docker%20Master%20(arm)/2751/consoleFull
Power: https://jenkins.dockerproject.org/job/Docker%20Master%20(powerpc)/1168/consoleFull

ping @WeiZhang555

**Comment by WeiZhang555** [comment]
Sorry for the trouble I bring to you, can you try if this commit fixes your problem? 
https://github.com/docker/docker/pull/25524

**Comment by tophj-ibm** [comment]
Testing now, thanks!

**Comment by tophj-ibm** [comment]
looks like that PR fixes the issue, thanks again!
