### ISSUE TITLE
No nslookup entry for the embeded DNS

### ISSUE THREAD

**Issue by luigiberrettini** [docker/docker#25541]
**Output of `docker version`:**

```
Docker version 1.12.0, build 8eab29e, experimental
```

**Output of `docker info`:**

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 14
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 76
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null host bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-92-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 741.8 MiB
Name: docker-playground-1
ID: OW45:4Z7I:Q2PV:Q2NV:LP3B:CJVV:5N5O:HKPS:5MNN:6P43:CZ6Y:NH6M
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VirtualBox

**Steps to reproduce the issue:**
1. Run a container
2. /etc/resolv.conf contains address 127.0.0.11
3. Run `netstat -nl` on the host

**Describe the results you received:**
No entry with 53 port listed

**Describe the results you expected:**
An entry with port 53 related to the default embedded [DNS](https://github.com/docker/docker/blob/3056e4884e470a43eb71584569d920d4abfde4d0/vendor/src/github.com/docker/libnetwork/resolver.go)

**Comment by cpuguy83** [comment]
Can you be more specific in your steps? What problem are you having?

127.0.0.11 is local to the container's network namespace and as such you would not see `53` listed in the host's `netstat`.

**Comment by sanimej** [comment]
@luigiberrettini @cpuguy83 `netstat` in the container's namespace won't list port 53 either. If Docker embedded DNS server listens on port 53 it would break the use cases where users want to run a DNS server in the containers. So what we do it listen on a random port and have an iptable rule to trap the DNS packets and do the port translation.

**Comment by luigiberrettini** [comment]
Thank you so much!
I spotted that address in a container's resolv.conf and tried to understand where I could find an information of that address listening for DNS queries.
I then found the go source file with a default 53 value and I thought it was hardcoded.

If I understood well, since in the container's /etc/resolv.conf no port is specified, queries on 127.0.0.11:53 are forwarded to 127.0.0.11 on randomly chosen port via iptables rules.
To retrieve more information, included the ip:port pair used by the embedded DNS server, I think I can inspect the network namespace as follows:
```shell
ip nets ls
ip netns exec <network-namespace> ifconfig -a
ip netns exec <network-namespace> ip link list
ip netns exec <network-namespace> ip route show
ip netns exec <network-namespace> iptables -S
```

**Comment by sanimej** [comment]
`If I understood well, since in the container's /etc/resolv.conf no port is specified, queries on 127.0.0.11:53 are forwarded to 127.0.0.11 on randomly chosen port via iptables rules.
To retrieve more information, included the ip:port pair used by the embedded DNS server`

Yes. That is correct. Docker daemon is setup to listen on that random port. You can check the output of `iptables -L -t nat` in the container namespace.

Since its a question about understanding the behavior I am closing this issue.
