### ISSUE TITLE
docker-machine with Azure driver cannot create a VM with the same vnet under different resource groups

### ISSUE THREAD

**Issue by groyee** [docker/docker#25549]
```
**Output of `docker version`:**
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 5
 Running: 4
 Paused: 0
 Stopped: 1
Images: 16
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 67
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.12-boot2docker
Operating System: Boot2Docker 1.11.2 (TCL 7.1); HEAD : a6645c3 - Wed Jun  1 22:59:51 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: default
ID: YFTU:TCWM:Q7C5:QOKR:6IZE:ARRL:XEX3:C4FL:EXMI:WAC3:TY42:N4KV
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 52
 Goroutines: 104
 System Time: 2016-08-09T20:17:22.466086489Z
 EventsListeners: 0
Username: groyee
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
//Create VM in Azure using docker-machine. Specify --azure-resource-group
1. docker-machine create -d azure  --azure-use-private-ip --azure-resource-group "**resourcegroupA**" --azure-subscription-id [_you subscription_] A

2.This will create VM 'A' in azure under resource group 'resourcegroupA'. This will also create **virtual network with the name docker-machine-vnet**

//Create another machine in a different resource group but with the same vent so these machine will be able to communicate with each other
3.docker-machine create -d azure  --azure-use-private-ip --azure-resource-group "**resourcegroupB**" **--azure-vnet "docker-machine-vent"** --azure-subscription-id [_you subscription_] B

**Describe the results you received:**
VM 'B' will be created with a new vnet (not the one I specified) and as a result the 2 machines can't communicate with each other. It is easily possible to create 2 machines in Azure in different resource groups using the same vnet.

**Describe the results you expected:**
I would expect docker will use the same vnet that I specified in the --azure-vnet.

**Additional information you deem important (e.g. issue happens only occasionally):**

The faulting code is:

func (a AzureClient) CreateVirtualNetworkIfNotExists(resourceGroup, name, location string) error {
    f := logutil.Fields{
        "name":     name,
        "location": location}

    log.Info("Querying if virtual network already exists.", f)

    if exists, err := **a.virtualNetworkExists(resourceGroup, name)**; err != nil {
        return err
    } else if exists {
        log.Info("Virtual network already exists.", f)
        return nil
    }

    log.Debug("Creating virtual network.", f)
    _, err := a.virtualNetworksClient().CreateOrUpdate(resourceGroup, name,
        network.VirtualNetwork{
            Location: to.StringPtr(location),
            Properties: &network.VirtualNetworkPropertiesFormat{
                AddressSpace: &network.AddressSpace{
                    AddressPrefixes: to.StringSlicePtr(defaultVnetAddressPrefixes),
                },
            },
        }, nil)
    return err
}

The problem is that docker checks if the specified vnet already exist in the same resource group where this container is about to be created. Since it is not created there it creates a new vnet with the same name under the new resource group.

a simple fix would be to provide resource group with the vnet name to the --azure-vnet parameter. for example: 

--azure-vnet = "resource-groupname:vnet-name"
As a result, the machines can't communicate with private ip.

This is a major issue which makes docker-machine unusable with azure driver. currently there is no workaround and the only options are:

1. Create all VMs with the same resource group. BAD IDEA

2. Force communication with public ip between the machines. BAD IDEA.

:-(

**Comment by thaJeztah** [comment]
Thanks for reporting; could you reopen this in the Docker Machine issue tracker? It looks like this is an issue with Docker Machine; https://github.com/docker/machine/issues

I'll close this issue here, but thanks for reporting!

GitHub doesn't allow moving issues between issue trackers, but you can "edit" your issue, and copy/paste your report to save time

**Comment by groyee** [comment]
Sorry, my bad.

Just opened a new ticket for docker-machine.

Thank You!

**Comment by thaJeztah** [comment]
No worries! Just closing here for housekeeping, no harm done :smile:
