### ISSUE TITLE
docker volume inspect does not show volume options

### ISSUE THREAD

**Issue by pdevine** [docker/docker#25545]
If you create a volume with options, docker inspect doesn't output any of the information, making it difficult to determine how a volume was created.

Here's the current output:
`[
    {
        "Name": "foo",
        "Driver": "local",
        "Mountpoint": "/var/lib/docker/volumes/foo/_data",
        "Labels": {}
    }
]
`

I would expect another "Options" key which has a value like {"<key>": "<value>", ...} for each of the options specified.

**Comment by pdevine** [comment]
Any love for this issue?  @cpuguy83

**Comment by cpuguy83** [comment]
Just requires persisting options in the volume db so we can retrieve them along with labels.
Feel free to make a patch, should be fairly straight forward.

**Comment by yongtang** [comment]
Added a pull request #26671 to show options in `docker volume inspect`.
