### ISSUE TITLE
Swarm Mode 1.12 /swarm/leave?force=true

### ISSUE THREAD

**Issue by hekaldama** [docker/docker#25543]
Is it intentional to have 1.12 `/swarm/leave` to have a query param of `?force=true`? If so, can we have the documentation updated (happy to do it if you point me in the right direction)? If not, should it be in the body instead and possibly JSON like the rest of the `/swarm/*` endpoints?

Thanks.

**Comment by hekaldama** [comment]
Should this be an issue filed with swarmkit or docker engine?

**Comment by cpuguy83** [comment]
This is a docker-engine endpoint. 
Thanks for the report!

**Comment by hekaldama** [comment]
NP!

**Comment by cpuguy83** [comment]
Sure, but I think it's there? https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api_v1.24.md

**Comment by hekaldama** [comment]
@cpuguy83 great! I am going to close.
