### ISSUE TITLE
docker for mac memory leak?

### ISSUE THREAD

**Issue by seeekr** [docker/docker#25552]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:04:48 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:04:48 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 37
 Running: 1
 Paused: 0
 Stopped: 36
Images: 516
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 749
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.856 GiB
Name: moby
ID: GYGK:LX7B:IMIE:WWSV:SF2I:XLAI:GMXY:3MC6:HUZ6:HW7L:2GDR:RV6J
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 21
 Goroutines: 34
 System Time: 2016-08-09T20:47:23.839940785Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

On my Yosemite 10.10 MacBook Pro.

**Steps to reproduce the issue:**
1. Start Docker 4 Mac.
2. Stop Docker 4 Mac.
3. Observe memory leak in activity monitor (or whatever that's called in English -- using German version of OS X).

**Describe the results you received:**

Overall used memory goes up by about 600MB every time D4M is restarted.

**Describe the results you expected:**

Memory usage should stay around the same, regardless of how many times D4M is restarted.

**Additional information you deem important (e.g. issue happens only occasionally):**

Problem is compounded by the existing issue of having to restart D4M often on system wake from sleep because of high CPU usage. Losing 600MB to 1GB of RAM every time hurts a lot.

Happy to provide more info if required, or kill my D4M and start over from scratch in case this is just something about my personal system and can't be reproduced reasonably easily.

I think leaked memory depends on number of containers running or existent in the system, but haven't investigated this too closely, just a guess from trying a few things before posting this.

Cheers, keep up the great work on Docker and the ecosystem of tools!

**Comment by thaJeztah** [comment]
Thanks for reporting! We recently opened a dedicated issue tracker for Docker for Mac; since this is specific to Docker for Mac, could you reopen this issue in that issue tracker? https://github.com/docker/for-mac/issues

I'll close this issue here, but thanks for reporting!

**Comment by thaJeztah** [comment]
Note that "moving" issues between issue trackers on GitHub is not possible, but you can "edit" this issue and copy/paste your report to save time. (Thanks for the detailed report!)
