### ISSUE TITLE
Requesting events with "since" and "until" not reliably polling

### ISSUE THREAD

**Issue by johnflavin** [docker/docker#25579]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:04:48 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:04:48 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

and

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 99
 Running: 2
 Paused: 0
 Stopped: 97
Images: 52
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 250
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.954 GiB
Name: moby
ID: A7F5:MEE2:XJ2N:ZQ6Q:HRKO:SRQJ:CTJF:RR3B:6K7F:SQPP:NBJ7:I7MM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 26
 Goroutines: 41
 System Time: 2016-08-10T18:29:32.322513876Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: flavin
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

and

```
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 1
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 15
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: xnat
ID: 3XVY:66LA:O7YA:ZRXD:5O3L:HR56:FBKD:5CG3:HAV3:JDG7:K3MX:44G7
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
the first machine is my local Docker for Mac installation; the second is an Ubuntu 14.04 VM in VirtualBox.

**Steps to reproduce the issue:**
1. Use the remote API to GET events, using the `since` query param.. For example, here is a simple example that asks for all events since time 0. (I have verified this behavior with other, more realistic time values.)

```
curl --unix-socket /var/run/docker.sock http://localhost/events?since=0
```

**Describe the results you received:**
The events in the specified time range (in the example, from time 0 until now) are sent to me from docker, and the HTTP stream remains open.

**Describe the results you expected:**
The events in the specified time range (in the example, from time 0 until now) are sent to me from docker, and the stream is closed. This is the documented behavior when using the `since` or `until` query params.

**Comment by thaJeztah** [comment]
Hm, wondering if this is a documentation error; still digging in the history, but this PR; https://github.com/docker/docker/pull/2348 seems to indicate that `--since` should also stream

```
Show previously created events and then stream
```

**Comment by thaJeztah** [comment]
Never mind, looks like that PR may have the wrong description; the original PR mentions the "polling"; https://github.com/docker/docker/pull/1180

**Comment by thaJeztah** [comment]
I just tried on docker 1.5.0 and it shows the same behavior, so if the behavior is wrong, it's been like that for a very long time

ping @vieux any idea? is this just a documentation issue ("polling")?

**Comment by vieux** [comment]
I think the description os wrong, it should indeed be `Show all events created since timestamp and then stream`

The current behavior is correct in my opinion.

**Comment by johnflavin** [comment]
If the documentation about `since` and `until` switching from streaming to polling, is there no way to signal that I don't want to stream? Just a `stream=false` param or something?

**Comment by vieux** [comment]
how about 
```
--since=0  --until=`date +%s`
```

**Comment by thaJeztah** [comment]
We have a  `--no-stream` (Disable streaming stats and only pull the first result) for `docker stats`, so perhaps it can be considered; is there a specific use case?

Meanwhile, let me fix the docs for this flag

if @vieux suggestion doesn't solve your use-case, could you open a new issue / feature request for that flag?

**Comment by johnflavin** [comment]
That does work. Combining `since` and `until` returns the events and closes the stream.

An explicit flag would be nice, but since there is a way to get the behavior I want, I wouldn't consider it necessary. (As long as the documentation makes this behavior clear.)

**Comment by johnflavin** [comment]
Can we reopen this issue? I tested it yesterday and it worked (as I commented above). But in retesting it, it does not work.

Both `docker events --since <some time> --until <some time a few seconds later>` and `curl --unix-socket /var/run/docker.sock 'http://localhost/events?since=<some time>&until=<some time a few seconds later>'` are leaving the stream open.

```
$ docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:04:48 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:04:48 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by thaJeztah** [comment]
Looks like it doesn't stop if there's no events *at* the `until` time, or events "after" `until` (I guess it keeps waiting until it receives an event for that, which would make sense if `--until` is a future date)

I'll reopen so that we can check the intended behavior and/or improve (I think it `--until` is in the past, and there's no more events, then it should disconnect. Possibly, if `--until` is in future, then wait until events take place)

**Comment by johnflavin** [comment]
Your suggestion makes sense to me. If I give an `until` time that is in the past there is no need to stream. There is only a finite set of events that could possibly match the criteria in the request; once they're all sent the connection should be closed.

Any word on whether this change/improvement will be considered?

**Comment by thaJeztah** [comment]
> Any word on whether this change/improvement will be considered?

Given that this behavior has not changed (it's not a regression), don't expect it to be given a high priority, but I can see this being a nice isolated issue for a contributor to work on

**Comment by samwagg** [comment]
#dibs

**Comment by samwagg** [comment]
I am unable to reproduce this issue (in addition to the version below, I tested on the current dev version). If `until` is in the future, the connection streams up until the future time is reached (regardless of whether it's combined with `since`). If `until` is in the past or present, the connection closes immediately. Here are some examples:

```
# since and until are both in the past -- terminates immediately as expected

time curl --unix-socket /var/run/docker.sock 
    "http://localhost/events?since=$((-5 + $(date +%s)))&until=$((-3 + $(date +%s)))"
real	0m 0.00s
```
 
```
# `since` is in the past with no `until` given -- streams indefinitely as expected

time curl --unix-socket /var/run/docker.sock 
    "http://localhost/events?since=$((-500 + $(date +%s)))"
^CCommand terminated by signal 2
real	0m 11.84s
```

```
# `since` is in the past and `until` is in the future -- streams until reaching `until`, then terminates

time curl --unix-socket /var/run/docker.sock 
    "http://localhost/events?since=$((-5 + $(date +%s)))&until=$((5 + $(date +%s)))"
real	0m 4.31s
```

```
# `since` is not given and `until` is in the future -- streams until reaching `until`, then terminates

time curl --unix-socket /var/run/docker.sock 
    "http://localhost/events?until=$((3 + $(date +%s)))"
real	0m 2.40s
```

Am I missing something, or is this working as intended? It also appears that no further docs updates are needed since #25588 addresses this behavior.

```
/ # docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```

**Comment by thaJeztah** [comment]
I'm not able to reproduce either

```
docker events --since 2016-10-10T16:00:00
2016-10-10T16:24:06.041323948+02:00 container die 43e590051f5b270ffb2311df11386a3601d53cb88403827ee824f8d40426822c (exitCode=0, image=debian, name=boring_payne)
2016-10-10T16:24:06.321929200+02:00 network disconnect 8ea6824048558eec134d83f58a801454028d52c6ec48299b0c4ccb820bd1645c (container=43e590051f5b270ffb2311df11386a3601d53cb88403827ee824f8d40426822c, name=bridge, type=bridge)
2016-10-10T16:24:06.506482280+02:00 container destroy 43e590051f5b270ffb2311df11386a3601d53cb88403827ee824f8d40426822c (image=debian, name=boring_payne)
```

So last event is 16:24:06


```
docker events --until 2016-10-10T16:30:00

(returns immediately)

docker events --since 2016-10-10T16:25:00 --until 2016-10-10T16:30:00

(returns immediately)
```

Setting a future date _does_ block (current time is 17:36), which is also how I updated the docs (https://github.com/docker/docker/pull/25588), i.e., stream until `--until` is reached.

```bash
docker events --since 2016-10-10T16:25:00 --until 2016-10-10T20:30:00
```

@johnflavin I _think_ this is the expected behavior, or did you expect it to stop streaming in all cases?

**Comment by johnflavin** [comment]
The polling behavior you described is what I would expect, but I can't reproduce it.

1. Both `since` and `until` in the past (note: I'm using the `date -v` option that lets you specify time offsets)
```
$ curl --unix-socket /var/run/docker.sock "http://localhost/events?since=$(date -v -5S +%s)&until=$(date -v -1S +%s)"
<stream remains open>
$ docker events --since=$(date -v -5S +%s) --until=$(date -v -1S +%s)
<stream remains open>
```

2. `since` in the past, `until` in the future
```
$ curl --unix-socket /var/run/docker.sock "http://localhost/events?since=$(date -v -5S +%s)&until=$(date -v +1S +%s)"
<stream remains open indefinitely, longer than the 1 second I would expect>
$ docker events --since=$(date -v -5S +%s) --until=$(date -v +1S +%s)
<stream remains open indefinitely, longer than the 1 second I would expect>
```

My `docker version` is different now than it was when I opened this ticker, so I'll update it here. I'm on the beta channel of docker for mac.
```
Client:
 Version:      1.13.0-rc2
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   1f9b3ef
 Built:        Wed Nov 23 17:40:58 2016
 OS/Arch:      darwin/amd64

Server:
 Version:             1.13.0-rc2
 API version:         1.25
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          1f9b3ef
 Built:               Wed Nov 23 17:40:58 2016
 OS/Arch:             linux/amd64
 Experimental:        true
```

**Comment by johnflavin** [comment]
Note that, if this is actually a regression, it could be recent. I have had a test case for this in my code for a while, and that test only started failing this morning. I'll give it here (sorry for speaking java):
```java
@Test(timeout = 10000)
public void testEventPolling() throws Exception {
    controlApi.pullImage(BUSYBOX_LATEST);

    // Create container, to ensure we have some events to read
    final ContainerConfig config = ContainerConfig.builder()
            .image(BUSYBOX_LATEST)
            .cmd("sh", "-c", "echo Hello world")
            .build();

    final Date start = new Date();
    final ContainerCreation creation = client.createContainer(config);
    client.startContainer(creation.id());

    Thread.sleep(500); // Wait to ensure we get some events
    final Date end = new Date();
    final List<DockerContainerEvent> events = controlApi.getContainerEvents(start, end);

    // The fact that we have a list of events and not a timeout failure is a victory
    assertThat(events, not(empty()));
}
```

This test makes a container, waits a little while, then reads the events. It uses `since` and `until` parameters that are not in the future, so it should never stream, only poll. If it gets any events (i.e. doesn't block forever waiting for the stream to end) it is a success. But right now this test fails by timing out after 10 seconds.

**Comment by thaJeztah** [comment]
I'm trying to reproduce (also Docker for Mac), but the stream immediately detaches :cry:

```
curl --unix-socket /var/run/docker.sock "http://localhost/events?since=$(date -v -5S +%s)&until=$(date -v -1S +%s)"
```

Could it be that the clock of docker for mac's VM is out of sync? Given that the offset is just 1 second, it could make a difference. 

    docker info | grep "System Time"

**Comment by johnflavin** [comment]
Wow, you’re right. The system time is off. It thinks it is yesterday.
```
$ docker info | grep Time
 System Time: 2016-11-30T23:36:43.20583885Z
```

How can I fix that?

**Comment by thaJeztah** [comment]
It should sync periodically, but this thread may contain some pointers / workarounds; https://github.com/docker/for-mac/issues/17

**Comment by thaJeztah** [comment]
Also, not sure it uses the same timezone, or if it defaults to UTC

**Comment by johnflavin** [comment]
Yep, that thread helped. I re-synced the clock with `$ docker run --rm --privileged alpine hwclock -s` and now the event polling works exactly as expected.

**Comment by johnflavin** [comment]
I'm guessing this was the underlying cause of my issue all along, thus this issue is safe to close.

**Comment by thaJeztah** [comment]
Thanks! Happy we solved that mystery!
