### ISSUE TITLE
Support automatic container removal when using docker create/start

### ISSUE THREAD

**Issue by tswift242** [docker/docker#25577]
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 22
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 4.4.13-040413-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.675 GiB
Name: ip-10-97-0-69
ID: UWJX:34OB:JFBN:7R4G:33IC:IWVW:SOBE:AM3B:B5BU:L2RL:LU32:ZVQB
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 22
 Goroutines: 55
 System Time: 2016-08-10T17:38:55.300602957Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
```

As far as I can tell, there's no way to enable automatic container removal for containers run through the docker create/start CLI instead of docker run. Neither the create or start CLI commands accepts "--rm" like run does. This seems like it'll be a problem when Docker integrates with C/R (https://github.com/docker/docker/pull/22049), which plans on using docker start to restore a container, and which won't integrate with docker run.

I see https://github.com/docker/docker/pull/20848 has been merged which changes some things about --rm, so I'm not sure if that changes anything. It looks like with that change the API supports an AutoRemove flag for create, but not the CLI.

Is there a way to support auto-removal in the create/start CLI workflow?

**Comment by justincormack** [comment]
I think it should be easy to implement now #20848 has been implemented, by passing the `AutoRemove` flag if `--rm` is specified in these cases too.

**Comment by thaJeztah** [comment]
Yes, I think this would be a logical next step. Not sure if it should be on both `create` and `start` or just one of both

**Comment by yongtang** [comment]
@tswift242 @justincormack @thaJeztah It seems that `--rm` is already present in `docker create` as both `docker create` and `docker run` use `runconfig` pkg to parse the flags.

The docs for `docker create` has not been updated yet so I created a PR #26030 to add `--rm` for `docker create`.

**Comment by yongtang** [comment]
Separately, I am wondering if it make sense to add `--rm=true/false` to `docker update`? In this way, user has the option to change `AutoRemove` after `docker create`. And this would be similar to `--restart` in `docker update`?

**Comment by justincormack** [comment]
@yongtang I guess it makes sense for completeness, I am not sure how much it will get used, but there may be some use cases.

**Comment by thaJeztah** [comment]
Let's close this issue, as it's implemented. I'm not against adding it to `docker update`, but perhaps we should wait for actual use cases before implementing "because we can" (but just my 0.02c); feel free to open an issue for that though!
