### ISSUE TITLE
Error response from daemon: ENV must have two arguments

### ISSUE THREAD

**Issue by jpca999** [docker/docker#25580]
○ docker build -f Dockerfile .
Sending build context to Docker daemon 2.048 kB
Error response from daemon: ENV must have two arguments

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->

**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      linux/amd64
```

```
jay at jai in ~/Movies/AWS/DOCKER/Docker for Web Developers By Dan Wahlin/ExpressSite
○ docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 16
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.16-boot2docker
Operating System: Boot2Docker 1.12.0 (TCL 7.2); HEAD : e030bab - Fri Jul 29 00:29:14 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: default
ID: HUKM:NHAP:KW6B:4YIA:72UJ:EYF4:6QTD:M6LV:XVLV:27WV:KG7V:R2QR
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 19
 Goroutines: 35
 System Time: 2016-08-10T18:41:11.087962587Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.open the terminal 
2.write the command =   `docker build -f Dockerfile .`
3.

**Describe the results you received:**

**Describe the results you expected:**
I was expecting it to run the Docfile that contains this : 

```Dockerfile
FROM node:latest
MAINTAINER Jay P
ENV NODE_ENV=production
ENV PORT=3000
COPY                    ./var/www
WORKDIR         /var/www
VOLUME        [“/var/www”, “/logs"]  
RUN                      npm install 
EXPOSE              $PORT
ENTRYPOINT    [“node”,“start"]
ENV                NODE_ENV\
```

**Additional information you deem important (e.g. issue happens only occasionally):**

Everytime

**Comment by justincormack** [comment]
it is complaining about the last line `ENV                NODE_ENV\` - what did you mean here? The `NODE_ENV` will already be set in the runtime environment.

**Comment by thaJeztah** [comment]
As far as I can see there's no bug here, so I'll close this issue, but feel free to continue the conversation.

I also spotted that your Dockerfile contains several "curly" quotes (`“`); this may be due to copy/pasting here, but if not, you should replace those with regular quotes `"`, otherwise your Dockerfile may not work
