### ISSUE TITLE
docker daemon docker_t label issue

### ISSUE THREAD

**Issue by kashifali94** [docker/docker#25600]
I have facing  issue If you run docker daemon with port forwarding it will have unconfined_t labelled with the following command
->Docker daemon -H localhost:2379 --selinux-enabled &

->but if you run daemon locally it will have docker_t labelled with the following command

->Service docker run  
In latest docker build 1.12 
What is the difference? And  as we know label will be given according to context of the entry point but don't both docker daemon were triggerd with the same entry point
Kindly reply me as soon as possible

**Comment by thaJeztah** [comment]
What platform are you running on? Also `service docker run` doesn't look like a valid command to me (`service docker start` perhaps?)

Can you provide the exact steps to reproduce, and commands you used to get the labels (and what you got, and expected to get)?

**Comment by kashifali94** [comment]
sorry it was "service docker start" command when i start docker daemon on host it has label docker_t type on it but when i run docker daemon on network it has unconfined_t type label on it where as i changes the context of root and the most important thing this it happening when selinux policy type is targeted..

**Comment by thaJeztah** [comment]
Please provide the requested info https://github.com/docker/docker/issues/25600#issuecomment-239141228. also what do you mean with "but when i run docker daemon on network"

**Comment by kashifali94** [comment]
i want docker_t type label on docker daemon when i run docker daemon on network with the following command 
docker daemon -H localhost:2379 --selinux-enabled & 
and it has labelled unconfined_u:unconfined_r:unconfined_t:s0 label
but i want system_:system_r:docker_t:s0  label on docker daemon

**Comment by thaJeztah** [comment]
So, with "on network", you mean, with `-H localhost:2379`? What platform / distro are you running on? If you want to configure the daemon to listen to localhost, you should configure the service to listen to that; how to do that depends on the platform you're running on; that's why `docker version` and `docker info` is information that's required when opening an issue here on GitHub

Also note that port 2379 is [reserved for etcd](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=etcd), so running the Docker API on that port is highly discouraged

**Comment by kashifali94** [comment]
sorry it port is 2376 my bad 
docker info 
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.0
Storage Driver: devicemapper
 Pool Name: docker-253:0-34382093-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 11.8 MB
 Data Space Total: 107.4 GB
 Data Space Available: 17.16 GB
 Metadata Space Used: 581.6 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp selinux
Kernel Version: 3.10.0-327.28.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.797 GiB
Name: localhost.localdomain
ID: NO3O:5C7H:XDYR:TTQK:3C6U:DOZE:JZ2J:6GXJ:2FZH:LSHQ:XSDK:O73G
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8

and docker version 

 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        
 OS/Arch:      linux/amd64


it is working fine but the docker_t label is not on docker daemon when run with "-H localhost:2376" it has unconfined_t label on it which is not false
Thanks

**Comment by thaJeztah** [comment]
The labels are only set when starting the daemon as a service (I.e., through the systemd unit file), not when started manually see https://github.com/docker/docker/issues/25907#issuecomment-241682222.

I'll close this issue, but feel free to comment after that
