### ISSUE TITLE
Proposal: new flag "--sort-by" for "ps" and "image" commands (maybe more)

### ISSUE THREAD

**Issue by WeiZhang555** [docker/docker#25609]
Right now, we don't have a flag to customize our output order of `ps` and `image`, I hope we can provide a new flag of client such as "--sort-by" to allow user to customize client output.
## basic idea

add a "--sort-by" flag for "ps" and "image",  "--sort-by" should accept an string of format "name:asc" or "ID:des" which means sort by name in ascent order and sort by ID in descent order.

"--sort-by" can be a client flag, so this will be a small enhancement of client, and doesn't influence daemon and API.
## why do we need this flag?

**image:**
1.  I have some duplicate images which does similar work, some are not necessary any more, I want to sort them by Repo name so that I can clean unnecessary ones.
2. image fulfills my disk, I want to clean my images, and only remove some large image. So I want to sort image by size, 

**ps:**
1. sometime I want to group containers by name, because they are more easily to be recognized by name.

before I start to writing the code, I want to know how many people would like to see this feature?  :smile:

**Comment by thaJeztah** [comment]
Sounds useful; "sort image by size" has been something that I looked for in the past

**Comment by albers** [comment]
Sorting by image size is indeed a problem because `docker images` outputs image sizes like `1 GB` and ` 1 MB`, with a space between numbers and units. This prevents us from using `sort` here:

    docker images --format '{{.Size}}\t{{.ID}}' | sort -h -r

does not take the units into account. Without the space, it works:

    docker images --format '{{.Size}}\t{{.ID}}' | sed 's/ //' | sort -h -r

So :+1: for a sorting facility. 

An alternative and more Unix-like solution would be to add an option for modifying number format so that the standard Unix sorting facility works. In fact, it does not make much sense to equip every tool with sorting options.

**Comment by albers** [comment]
The _CREATED_ column cannot be sorted as well, having values like `7 weeks ago`. For this field, there is a solution: `--format` has `.CreatedSince` and the sortable variant `.CreatedAt`.
So another solution for the sorting problem on image size could be to add another placeholder with the raw image size in bytes.

**Comment by thaJeztah** [comment]
yes, sorting should probably be done on the "raw" values (haven't checked what the API returns). Also we may want to add an extra sort-column by default for images tagged under different names (see https://github.com/docker/docker/issues/25640)

**Comment by WeiZhang555** [comment]
> So another solution for the sorting problem on image size could be to add another placeholder with the raw image size in bytes.

This will require some modification of images output.  So my idea is, we simply sort images as user requested, then print result out, no extra field or format change.

**Comment by albers** [comment]
>This will require some modifications of images output
@WeiZhang555 I was thinking of adding another placeholer that you can use in `--format`. This placeholder would not be used in the default output, which would remain unchanged by this addition.

I admit that it would be cool to have a simple option to change sort order. But have concerns that this might open the door to lots of follow-up requests: How about sorting on additional fields (those only available when using `--filter`, how about secondary sort keys, how about reverse sort order, how about sorting one key ascending and the other descending? Why can I not sort in `docker volume ls`?

**Comment by WeiZhang555** [comment]
@albers I can understand your worries.  

It's true that adding a placeholder can solve this problem in another way. But it will reply on external tools such as `sort` as you said, which will also require user to do some complex input such as 
```
docker images --format '{{.Size}}\t{{.ID}}' | sed 's/ //' | sort -h -r
```

And considering docker is a cross-platform software, I'm not sure it will always be so easy to implement sorting on other platforms (I don't know if Windows has such tool as `sort`)

Secondly, I hope we can expand sorting functions to more commands like `stats`, but `stats` has stream mode which will keep displaying data dynamically, in such situation `sort` can do nothing for us, but a new flag can.  (`stats` also has some sorting problem, see my comment https://github.com/docker/docker/issues/25640#issuecomment-239390484)

**Comment by drlukeangel** [comment]
Hello,
      I was as well thinking this would be a great feature especially as windows comes out it would keep the commands the same. In the meantime you can always use   sort to achieve a similar result if the container operating system supports it. Check out the screen grab below.  The first | sort sorts the containers ids not terriblly userfull but you can then just iterate of the columns to sort using the -k flag. This would in addition address your concerns of having feature requests coming i. Just allowing the users to sort on the return set by column number. 
![image](https://cloud.githubusercontent.com/assets/22433329/19221658/a46952e6-8dfc-11e6-971a-c8f4496a86f0.png)

**Comment by WeiZhang555** [comment]
Closing this, anyone who is interested in sorting please move to #31062
