### ISSUE TITLE
docker service create doesn't find image

### ISSUE THREAD

**Issue by ajl** [docker/docker#25619]
When I run 

> docker service create --mode global foo myrepo/foo-img:0.1

 it works in that it starts the service, but if foo-img:0.1 does not exist on a node in the swarm, that node emits the following error:

> <containerid>   \_ foo    myrepo/foo:0.1  <snip>  "No such image: myrepo/foo-img:0.1"

If I pull myrepo/foo-img:0.1 on each node then it works fine.

Is there a workaround for this other than pulling the image on each node in the swarm?

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->

**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 7
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 25
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay null bridge
Swarm: active
 NodeID: cxuvib7k5wjsdqo8de3z5z4ky
 Is Manager: true
 ClusterID: 9zhttvl6l55uys4uka24m03h9
 Managers: 2
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot interval: 10000
  Heartbeat tick: 1
  Election tick: 3
 Dispatcher:
  Heartbeat period: 5 seconds
 CA configuration:
  Expiry duration: 3 months
 Node Address: 172.31.35.10
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.795 GiB
Name: ip-172-31-35-10
ID: MUUA:UEUC:CC7V:WNU7:6SCE:JLD4:ULVI:YYH3:6R3D:EZI4:XIGW:F3QX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS Swarm
```
ID     HOSTNAME         STATUS  AVAILABILITY  MANAGER STATUS
id1     ip-xx206  Ready   Active        Leader
id2     ip-xx206  Down    Active        
id3    ip-xx-73  Ready   Active        
id4 *  ip-xx-10  Ready   Active        Reachable
```

**Steps to reproduce the issue:**
1. Create a swarm (docker swarm init)
2. Deploy a service from a private repository
3.


**Describe the results you received:**
> <containerid>   \_ foo    myrepo/foo:0.1  <snip>  "No such image: myrepo/foo-img:0.1"


**Describe the results you expected:**
Service would start like happens if i first pull the image

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
Is the image you're trying to run pushed to Docker Hub, in a local registry (or perhaps only available on your local machine?)

If it's on Docker Hub, is it a private repository, or a public image? If it's a private repository, you need to pass the `--with-registry-auth` flag on `docker service create` to pass your credentials for Docker Hub to the other nodes.

**Comment by ajl** [comment]
Thanks thaJeztah! 

The image is in Amazon ECR (elastic container registry). --with-registry-auth sounds like what I need. Is there documentation on how to supply credentials this way? (e.g. --with-registry-auth "-u me -p mypass")

**Comment by fornve** [comment]
Same here. How to use --with-registry-auth ? How to pass login, password and registry url?

**Comment by thaJeztah** [comment]
`--with-registry-auth` forwards the credentials that are currently active in the docker client (so if you are logged in (`docker login ...`), those credentials are forwarded.

However, it's possible that those credentials expire; in that case `docker service update` (which always pulls the latest image if any setting is changed) would not be able to get a fresh image, so when doing `docker service update`, you can also add `--with-registry-auth` to pass the current session/credentials.

**Comment by fornve** [comment]
@thaJeztah It started working! Thanks!

**Comment by ajl** [comment]
Great that fornve got it working. However, when I tried this it did not work:

`--with-registry-auth "-u AWS -p Axxxxxxxxx"`

or with 

`--with-registry-auth "-u AWS -p Axxxxxxxxx -e none https://410xxx.amazonaws.com"`

led to the same issue. I can keep trying variations on this, but if someone knows the correct way to pass credentials that would be helpful.

**Comment by thaJeztah** [comment]
@ajl `--with-registry-auth` doesn't take a "value", basically, the steps are;

1. Authenticate if you're not logged in (`docker login ..`)
2. Create or update the service, for example:

        docker service create --with-registry-auth --name my-service my/image:latest

**Comment by jmcdonagh** [comment]
I just encountered this bug. The machines in question are indeed authenticated to ECR and can 'docker run' the image fine. However if you use the service create command without having run 'docker run' on any node, the replicas won't start on that node and this is what you see from docker service ps:

```
f226w86cfp1grm4k91o68swx6  private_lessons.2      399735942051.dkr.ecr.us-east-1.amazonaws.com/aws/private_lessons:testing  larryland.alpha.BerkleeOnlineGamma1471018469.testing  Ready          Rejected less than a second ago  "No such image: 399735942051.d…"
75ztv3r808jw1pm7ucq2rnuc2   \_ private_lessons.2  399735942051.dkr.ecr.us-east-1.amazonaws.com/aws/private_lessons:testing  larryland.alpha.BerkleeOnlineBeta1471018469.testing   Shutdown       Rejected less than a second ago  "No such image: 399735942051.d…"
e32fxyp6a7v8a8fq11rwnyi3d   \_ private_lessons.2  399735942051.dkr.ecr.us-east-1.amazonaws.com/aws/private_lessons:testing  larryland.alpha.BerkleeOnlineGamma1471018469.testing  Shutdown       Rejected less than a second ago  "No such image: 399735942051.d…"
1799rqe9e9v1dlpk975h3jk89   \_ private_lessons.2  399735942051.dkr.ecr.us-east-1.amazonaws.com/aws/private_lessons:testing  larryland.alpha.BerkleeOnlineBeta1471018469.testing   Shutdown       Rejected less than a second ago  "No such image: 399735942051.d…"
```

Fixed by going to each node and using docker run once to pull down the image.

**Comment by jmcdonagh** [comment]
Why is it necessary to pass the --with-registry-auth thing? Seems superfluous. Lord knows I just love typing but...

**Comment by ajl** [comment]
Just to confirm, authenticating with docker then passing that argument solves the problem for me too. I'd prefer a bit better documentation, but it is working as designed. Closing.

**Comment by thaJeztah** [comment]
@jmcdonagh we all agree, and it's on the list of things to improve; read the PR that added the flag (it was renamed later) for background on that decision https://github.com/docker/docker/pull/23584

**Comment by justlooks** [comment]
@thaJeztah  i have the same problem .instead of using docker Hub ,i build a registry service on my swarm cluster with 1 REPLICAS ,but when i want to build service using image of this private registry,the service fail to start.i do not know why?

**Comment by thaJeztah** [comment]
@justlooks `docker pull` is performed by the daemon, so requires each daemon to have access to that registry; this may be part of the problem, but hard to tell without full details.

However, keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)
