### ISSUE TITLE
overlay2 show disk usage incorrect

### ISSUE THREAD

**Issue by winggundamth** [docker/docker#25621]
I'm using Docker 1.12 with overlay2. Today my monitor show that I'm almost running out of space so I'm checking where that causing the problem but I found that output of df command and du command is inconsistent so I don't know which exactly the problem. Please see the information below

**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 1.12.0
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge host null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859 GiB
Name: docker-01
ID: KHIS:7LO5:ZHIN:TTMP:3DOR:2WD4:27LF:7VHU:PDXC:ZII3:IFD2:KAAC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=generic
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details**

```
# cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

**This is output from `df -h`**

```
Filesystem      Size  Used Avail Use% Mounted on
udev            2.0G   12K  2.0G   1% /dev
tmpfs           396M  592K  395M   1% /run
/dev/vda1        12G   11G  597M  95% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
none            5.0M     0  5.0M   0% /run/lock
none            2.0G   80K  2.0G   1% /run/shm
none            100M     0  100M   0% /run/user
overlay          12G   11G  597M  95% /var/lib/docker/overlay2/37ea0b965e9e26eed4922a4147288fad0550bac4562db3acee6c3080be513799/merged
shm              64M     0   64M   0% /var/lib/docker/containers/44253d93df0bb84304c9da2ab44bca1edd46cfd7e810e51ce718a0883b04b012/shm
overlay          12G   11G  597M  95% /var/lib/docker/overlay2/cf11184861de6eccfec8de4596e15311b6542488a3ba63d3cb67c4abaf07f821-init/merged
overlay          12G   11G  597M  95% /var/lib/docker/overlay2/40ac0c528e600cfc48a1d3fbded955f53caa2bec01dff53ebcb51e82f1735568/merged
shm              64M     0   64M   0% /var/lib/docker/containers/a05360e5d6ab714b8545ec84724868300fbe4467565d8747569f821c131e2330/shm
overlay          12G   11G  597M  95% /var/lib/docker/overlay2/bf3c5a3216ae724119439b1737c52b8c02a6706718fed24157aa9f2e9c69bb93-init/merged
overlay          12G   11G  597M  95% /var/lib/docker/overlay2/90b5a3acdbd796a261c6dd48dd07072cdb5ca79f8d1f9f74c2f35490cf88c173/merged
overlay          12G   11G  597M  95% /var/lib/docker/overlay2/ab3c60316e899501deb66d0ad326e0871e4349183c60dbf772f31f2c2e580afa/merged
shm              64M     0   64M   0% /var/lib/docker/containers/2f27be25f32baa6774550b5a5463b4508c5b46c50fccc1369044d7d63212f140/shm
shm              64M     0   64M   0% /var/lib/docker/containers/35f7c6720336ea01a41456a8a130ed6fd410ec7e47f0414bbcfc42ad96a41431/shm
```

**This is output from `du -h --max-depth 1 /`**

```
4.0K    /mnt
0       /sys
672K    /run
5.3M    /etc
416M    /lib
9.6M    /bin
12K     /dev
4.0K    /lib64
4.0K    /media
du: cannot access ‘/proc/22714/task/22714/fd/4’: No such file or directory
du: cannot access ‘/proc/22714/task/22714/fdinfo/4’: No such file or directory
du: cannot access ‘/proc/22714/fd/3’: No such file or directory
du: cannot access ‘/proc/22714/fdinfo/3’: No such file or directory
0       /proc
16K     /lost+found
40K     /root
20K     /tmp
9.6M    /sbin
985M    /usr
4.0K    /srv
4.4G    /var
488K    /home
83M     /boot
8.0K    /opt
5.9G    /
```

So you can see that df shows that system used 11GB of disk space while du shows that system use only 5.9GB. Please advice which one should I trust and why is it not consistent?

**Comment by winggundamth** [comment]
It turns out that I reboot machine and this back to normal. I'll reopen this issue if it happens again.

**Comment by thaJeztah** [comment]
Thanks @winggundamth

**Comment by olegantonyan** [comment]
Same here. But in my case not only reboot didn't help, but after reboot it `df` always shows that I'm running out of disk space, regardless of running containers
```
zenbook:/home/oleg # df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        3.9G     0  3.9G   0% /dev
tmpfs           3.9G   24M  3.9G   1% /dev/shm
tmpfs           3.9G  1.6M  3.9G   1% /run
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/sda2       477G  477G   64M 100% /
/dev/sda1       195M  132K  195M   1% /boot/efi
tmpfs           789M     0  789M   0% /run/user/475
tmpfs           789M   16K  788M   1% /run/user/1000
zenbook:/home/oleg # du / -h --max-depth=1
...
27G     /
``` 
`rm -rf /var/lib/docker` and removing docker from the system doesn't help

docker 1.12.3 build 8eab29e
openSUSE Tumbleeweed (4.8.13-1-default) 64-bit

**Comment by r7vme** [comment]
Hello, looks like are hitting similar issue with xfs backed overlay.

df shows that 90% are used, but `du -sh` shows only ~20G is used.

```
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs         24G     0   24G   0% /dev
tmpfs            24G     0   24G   0% /dev/shm
tmpfs            24G  339M   24G   2% /run
tmpfs            24G     0   24G   0% /sys/fs/cgroup
/dev/vdb        150G  135G   16G  90% /
/dev/vda        291M  291M     0 100% /usr
none             24G   82M   24G   1% /run/torcx/unpack
tmpfs            24G     0   24G   0% /tmp
tmpfs            24G     0   24G   0% /media
config-2         50G  5.1G   45G  11% /media/configvirtfs
tmpfs           4.8G     0  4.8G   0% /run/user/1007
```

```
r7vme@worker-ha2pi-3582928755-v8bpf ~ $ sudo du -sh /var
20G     /var
```

Docker info
```
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
```

```
docker system df
TYPE                TOTAL               ACTIVE              SIZE                RECLAIMABLE
Images              29                  29                  5.739GB             821MB (14%)
Containers          55                  53                  37.94MB             0B (0%)
Local Volumes       2                   2                   69.75MB             0B (0%)
Build Cache                                                 0B                  0B
```

**Comment by thaJeztah** [comment]
@r7vme can you elaborate? `df` shows 90% of the _entire_ disk is used, but your `du -sh` only checks what's used in `/var`

**Comment by r7vme** [comment]
sorry, it's not really clear.

```
r7vme@worker-ha2pi-3582928755-v8bpf ~ $ sudo du -sh /* 2>/dev/null
0       /bin
0       /boot
0       /dev
8.0M    /etc
124K    /home
0       /lib
0       /lib64
32K     /media
0       /mnt
67M     /opt
0       /proc
4.0K    /root
494M    /run
0       /sbin
0       /srv
0       /sys
0       /tmp
656M    /usr
21G     /var
```

**Comment by kolyshkin** [comment]
I know two reasons why df and du figures may differ a lot.
1. Removed but not closed file. If a running program opens a file and then the file is removed, it becomes a "ghost" file, i.e. it's not accessible from the file system anymore (as it does not have a name), but it's still there as long as the program keeps it open. So, this file is not accounted for by du. (In fact there is a way to see this file, by looking at `/proc/PID/fd/N`, but of course du is not looking in there). The solution is to stop the program (or make it close the file -- for example logrotate sends SIGHUB to some daemons after moving their log files, and they do `close()/open()`).

> It turns out that I reboot machine and this back to normal. I'll reopen this issue if it happens again.

This is also an indication that this was a kind of situation described above (as reboot naturally means stopping all the programs, including those holding opened-and-deleted files).

2. File system errors (lost blocks etc). The solution is fsck.

**Comment by kolyshkin** [comment]
@r7vme my suggestion is to run xfs_repair (as per https://github.com/moby/moby/issues/25621#issuecomment-267651949).

**Comment by r7vme** [comment]
Thanks for suggestions. We had problem with not closed file descriptors and guilty was [filebeat container](https://discuss.elastic.co/t/filebeat-is-not-closig-the-file-descriptor-once-the-file-is-deleted-renamed/104077/20).

**Comment by balajeetm** [comment]
`
I know two reasons why df and du figures may differ a lot.

Removed but not closed file. If a running program opens a file and then the file is removed, it becomes a "ghost" file, i.e. it's not accessible from the file system anymore (as it does not have a name), but it's still there as long as the program keeps it open. So, this file is not accounted for by du. (In fact there is a way to see this file, by looking at /proc/PID/fd/N, but of course du is not looking in there). The solution is to stop the program (or make it close the file -- for example logrotate sends SIGHUB to some daemons after moving their log files, and they do close()/open()).
It turns out that I reboot machine and this back to normal. I'll reopen this issue if it happens again.

This is also an indication that this was a kind of situation described above (as reboot naturally means stopping all the programs, including those holding opened-and-deleted files).

File system errors (lost blocks etc). The solution is fsck.
`
@kolyshkin, Very helpful
Disk pressures in nodes are mostly due to badly handled file descriptors.
