### ISSUE TITLE
Docs: Add Swarm Leave --force to query parameters

### ISSUE THREAD

**Issue by andrestc** [docker/docker#25627]
The `/swarm/leave` api supports a `?force=true` parameter and it should be documented in the [api docs](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/leave-a-swarm). I'll be glad to send a PR for this.

**Comment by icecrime** [comment]
Also true, thanks again! :+1:

**Comment by cmullaney** [comment]
#dibs

**Comment by thaJeztah** [comment]
Fixed through https://github.com/docker/docker/pull/25719
