### ISSUE TITLE
Docs: Fix Swarm Init example response

### ISSUE THREAD

**Issue by andrestc** [docker/docker#25625]
Currently, the Swarm Init api (/swarm/init) returns the node id when the swarm is successfully initialized:

```
curl -XPOST --unix-socket /var/run/docker.sock http:/swarm/init -d '{"ListenAddr": "127.0.0.1"}'
"ejdf53mtjiqp8feyf1907si12"
```

This behavior is not documented in the [api docs](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/initialize-a-new-swarm).

I believe this should be documented and I can send a PR for that.

**Comment by icecrime** [comment]
Makes sense, thanks!
