### ISSUE TITLE
All "docker service" commands fail with "404 page not found"

### ISSUE THREAD

**Issue by jmcdonagh** [docker/docker#25626]
**Output of `docker version`:**

```
[aws:~/docker-config/aws/bin] > docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/1.2.4
 API version:  1.22
 Go version:   go1.5.4
 Git commit:   5d5f7f0
 Built:        Thu Jul 28 19:52:54 UTC 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 9
 Running: 9
 Paused: 0
 Stopped: 0
Images: 6
Server Version: swarm/1.2.4
Role: replica
Primary: 172.31.6.140:3376
Strategy: spread
Filters: health, port, containerslots, dependency, affinity, constraint
Nodes: 3
 larryland.alpha.BerkleeOnlineAlpha1470929855.testing: 172.31.5.241:2376
  └ ID: A5YH:JMFA:FJQE:6AFS:2H3S:4CXM:ZBXS:KDXP:NQV5:F5JR:M2FS:CRKO
  └ Status: Healthy
  └ Containers: 3 (3 Running, 0 Paused, 0 Stopped)
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 3.858 GiB
  └ Labels: kernelversion=4.4.0-34-generic, operatingsystem=Ubuntu 16.04.1 LTS, provider=amazonec2, storagedriver=aufs
  └ UpdatedAt: 2016-08-11T17:09:13Z
  └ ServerVersion: 1.12.0
 larryland.alpha.BerkleeOnlineBeta1470929855.testing: 172.31.6.140:2376
  └ ID: RC3L:WYGD:WOUC:FQ7K:NF6I:DL3D:7AQV:QV4D:OBJH:RC4N:7MDQ:C6GS
  └ Status: Healthy
  └ Containers: 3 (3 Running, 0 Paused, 0 Stopped)
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 3.858 GiB
  └ Labels: kernelversion=4.4.0-34-generic, operatingsystem=Ubuntu 16.04.1 LTS, provider=amazonec2, storagedriver=aufs
  └ UpdatedAt: 2016-08-11T17:08:44Z
  └ ServerVersion: 1.12.0
 larryland.alpha.BerkleeOnlineGamma1470929855.testing: 172.31.5.236:2376
  └ ID: YNQK:NF65:KUKA:KTGM:24RO:LOH5:VOVX:K2KO:3R7Z:O7NE:6MDU:FM5T
  └ Status: Healthy
  └ Containers: 3 (3 Running, 0 Paused, 0 Stopped)
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 3.858 GiB
  └ Labels: kernelversion=4.4.0-34-generic, operatingsystem=Ubuntu 16.04.1 LTS, provider=amazonec2, storagedriver=aufs
  └ UpdatedAt: 2016-08-11T17:08:22Z
  └ ServerVersion: 1.12.0
Plugins:
 Volume:
 Network:
Swarm:
 NodeID:
 Is Manager: false
 Node Address:
Security Options:
Kernel Version: 4.4.0-34-generic
Operating System: linux
Architecture: amd64
CPUs: 3
Total Memory: 11.57 GiB
Name: 8b97ffd0bdc0
Docker Root Dir:
Debug Mode (client): false
Debug Mode (server): false
WARNING: No kernel memory limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS, machines created with docker-machine

**Steps to reproduce the issue:**
1. Create a swarm cluster with docker-machine on AWS
2. Try to run docker service ls or docker service create
3. Be sad, file bug report

**Describe the results you received:**

I think the steps above cover it

**Describe the results you expected:**

I want to ORCHESTRATE

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by jmcdonagh** [comment]
Just noticed that none of the nodes seem to think they are manager, yet this is a three node cluster and i passed --swarm-master as an engine opt with swarm-opt replication. I thought that would make all three have the ability to be a manager, yet none show ismanager true. I'm not sure if that's what's causing the 404, but either way that error is very non-specific.

**Comment by jmcdonagh** [comment]
```
[aws:~/docker-config/aws/bin] > docker service ls
Error response from daemon: 404 page not found
[aws:~/docker-config/aws/bin] > docker service create something
Error response from daemon: 404 page not found
```

**Comment by mgoelzer** [comment]
@jmcdonagh, the `docker service` subcommands added in 1.12 only work with Engines that are in "swarm mode" (i.e., cluster was set up using `docker swarm init` and `docker swarm join`).  This is different from the existing project called Docker Swarm (yes, confusingly similar names).

You can run 1.12+ orchestration (`docker service`) or Docker Swarm 1.x (`--swarm-XXXX` engine opts), or even run both simultaneously, but first is a distinct orchestration system from the second.

**Comment by jmcdonagh** [comment]
Yea that is extremely confusing. So basically I take out the swarm stuff from docker-machine, then run docker 'swarm' commands you mentioned by hand?

**Comment by mgoelzer** [comment]
Yes.  The approximate flow is:  `docker swarm init`, `docker swarm join`, `docker service create`.  Docs here:  https://docs.docker.com/engine/swarm/

**Comment by icecrime** [comment]
Closing this if that's ok! Thanks for the response @mgoelzer.

**Comment by jmcdonagh** [comment]
Closing it is fine but IMO the 404 error is kind of garbage. It really tells you nothing about what's wrong.

**Comment by mgoelzer** [comment]
Yes, I agree with you that the 404 is uninformative @jmcdonagh.

The root problem of that I would say is that the server in this case speaks an older API version than the client.  This is related to a larger issue that we're trying to sort out (#25498).

**Comment by jmcdonagh** [comment]
But both my client and servers are on 1.12 docker version. Not sure how API could mismatch if packages are the same, but I have encountered the API thing before in other scenarios it would definitely be nice if it worked something like psql which handles this scenario of client/server mis-match very gracefully.

**Comment by thaJeztah** [comment]
When working with "Swarm", the client connects to the Swarm API (https://github.com/docker/swarm/blob/master/docs/swarm-api.md), which is similar to the Docker 1.11 API.

I do notice that the document I just linked to doesn't mention the Swarm mode endpoints as being missing in that API, which I think should be addressed

**Comment by jacohend** [comment]
> This is different from the existing project called Docker Swarm (yes, confusingly similar names).

I'd say that this is another "root problem". What if all of Apple's products were just called "App"? This needs to change / be disambiguated

**Comment by rocketraman** [comment]
> This is different from the existing project called Docker Swarm (yes, confusingly similar names).

"Confusingly similar"?? More like "Confusingly exactly the same". Yikes.
