### ISSUE TITLE
Docker container cannot acces the network

### ISSUE THREAD

**Issue by maximmo77** [docker/docker#25631]
When I ran ping 8.8.8.8 from docker container I receive nothing, total silence :)

Host's Iptables shows: http://i.stack.imgur.com/1ayCx.png

and this: http://i.stack.imgur.com/9OQUM.png

There are must be something, not 0.

This occurs only on one server. I have installed docker server before and it works from the box. But not this time ).

Help please.

**Comment by thaJeztah** [comment]
Could you move this question to the forums (https://forums.docker.com) or ask in the #docker IRC channel? This likely is not a bug, but an issue in your setup, and the GitHub issue tracker is not really meant as a support forum.
