### ISSUE TITLE
docker service requires a TTY option

### ISSUE THREAD

**Issue by drajen** [docker/docker#25644]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 53
 Running: 0
 Paused: 0
 Stopped: 53
Images: 13
Server Version: 1.12.0
Storage Driver: devicemapper
 Pool Name: docker-253:0-1032817-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.458 GB
 Data Space Total: 107.4 GB
 Data Space Available: 37.56 GB
 Metadata Space Used: 6.697 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.141 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local nimble
 Network: null bridge host overlay
Swarm: active
 NodeID: 8857oygvwnu30na829rdb7y2j
 Is Manager: true
 ClusterID: cbxpmne2d14dzvgnfwuh9w65i
 Managers: 3
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot interval: 10000
  Heartbeat tick: 1
  Election tick: 3
 Dispatcher:
  Heartbeat period: 5 seconds
 CA configuration:
  Expiry duration: 3 months
 Node Address: 192.168.59.21
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 489.4 MiB
Name: ping
ID: CYLJ:J4E3:LVIE:FVPH:BW2Z:FHQU:6DLC:7QT7:O4NO:GEFC:Q6LU:WESM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Vagrant on VMware Fusion

**Steps to reproduce the issue:**
1. Run any image that requires a TTY as a "docker service" (I've been using jenserat/samba-publicshare)
2. Watch it fail indefinitely 

**Describe the results you received:**
smbd dies 

**Describe the results you expected:**
smbd dies unless there's a TTY

**Additional information you deem important (e.g. issue happens only occasionally):**
Please add a -t flag to "docker service create"

**Comment by icecrime** [comment]
Related: #25303.

**Comment by stevvooe** [comment]
Filed docker/swarmkit#1370 and docker/engine-api#364.

**Comment by crosbymichael** [comment]
I'm looking into a couple of ways to support services that require a tty at the runtime level instead of allocating one in the daemon.  I have your example working but looking at getting checkpoint and restore to work with it as one of the big benefits for not having tty's in the service is to allow advanced features in the future.

**Comment by stevvooe** [comment]
@drajen @crosbymichael Were you able to find a workaround?

**Comment by crosbymichael** [comment]
Sorry for the lag.

I think it is safe to add `tty` support to swarm and it does not directly hurt portability.  I don't have a better alternative at this point and adding this to swarm has the lowest impact on other aspects of the system.  

+1 for adding tty support.

**Comment by yongtang** [comment]
Created a PR #28076 for `--tty` in `service create`.
