### ISSUE TITLE
Docker for Mac: 'no route to host' when pulling image over VPN

### ISSUE THREAD

**Issue by okdana** [docker/docker#25645]
I use OS X's built-in PPTP VPN client to connect to my work network, where we have a private (not publicly routable) Docker registry running. When i'm connected to the VPN, `docker` is able to pull images fine from the public Internet (Docker Hub or where-ever), but it can't pull them from our registry. When i try, i get errors like this:

```
theoria:~ % docker run --rm -it docker.mycompany.com/mycompany/devserver:trusty bash
Unable to find image 'docker.mycompany.com/mycompany/devserver:trusty' locally
Pulling repository docker.mycompany.com/mycompany/devserver
docker: Error while pulling image: Get http://docker.mycompany.com/v1/repositories/mycompany/devserver/images: dial tcp 172.17.30.1:80: getsockopt: no route to host.
See 'docker run --help'.
```

(In this case the registry is insecure, but i got the same 'no route to host' errors when i was using TLS.)

I don't actually know for sure this is related to my use of PPTP, but i'm *guessing* that it is, since Docker Hub works and the error suggests a routing issue.

The machine itself does not seem to have any routing troubles, though. `traceroute`, `ping`, `dig`, `curl` all work fine, there's nothing wrong with my connectivity to the registry outside of `docker`. Here's what i see for the route:

```
theoria:~ % host docker.mycompany.com
docker.mycompany.com has address 172.17.30.1
theoria:~ % netstat -nr | ag -wF '172.17'
172.17             ppp0               USc             4        0    ppp0
```

The problem occurs with both the stable and beta versions of Docker for Mac. Restarting Docker through the menu bar after completing the VPN connection doesn't make a difference. There is no proxy stuff involved, it's just the VPN. 'Send all traffic over VPN connection' is ticked in Network Preferences.

I know Apple are getting rid of PPTP in Sierra, but any thoughts in the mean time? Thanks!

**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:04:48 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:04:48 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.16-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.954 GiB
Name: moby
ID: GDXP:2QYU:QFHC:UJRI:4I5G:JH4T:DXQX:LZ2M:56MM:6KWH:IAE4:AK5B
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 27
 System Time: 2016-08-12T01:02:19.807522113Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 docker.mycompany.com
 docker.mycompany.local
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
theoria:~ % sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.3
BuildVersion:	15D21
```

**Comment by justincormack** [comment]
Thats odd. If you just run a container does it have connectivity to that? eg `docker run alpine wget 172.17.30.1` or similar? The traffic should just be routed over the default gateway, so it is pretty odd.

cc @djs55

**Comment by okdana** [comment]
Oh, i think that's leading us in the right direction.

`wget` didn't work:

```
theoria:~ % docker run alpine wget -O- 172.17.30.1
Connecting to 172.17.30.1 (172.17.30.1:80)
wget: can't connect to remote host (172.17.30.1): Host is unreachable
```

So i tried to `traceroute`:

```
theoria:~ % docker run alpine traceroute 172.17.30.1
traceroute to 172.17.30.1 (172.17.30.1), 30 hops max, 46 byte packets
 1  7684ed6a4551 (172.17.0.2)  2992.077 ms !H  3002.624 ms !H  3001.497 ms !H
```

172.17.0.2 is the IP of the container. It happens to overlap with the IP of a host on our (work's) internal network. The bridge on the host is configured like this:

```
theoria:~ % docker network inspect bfbd52f81aa9 | jq '.[] | .IPAM'
{
  "Driver": "default",
  "Options": null,
  "Config": [
    {
      "Subnet": "172.17.0.0/16",
      "Gateway": "172.17.0.1"
    }
  ]
}
```

172.17.0.1 is the internal address of our PPTP server i'm connected to. IPs are probably conflicting?

A co-worker directed me to [network configuration documentation](https://docs.docker.com/v1.8/articles/networking/#docker0), which explains how to change the bridge settings, but i'm not sure i can do that with Docker for Mac (?).

Also, the documentation states:

>When Docker starts, it creates a virtual interface named docker0 on the host machine. It randomly chooses an address and subnet from the private range defined by RFC 1918 that **are not in use on the host machine**, and assigns it to docker0.

If that were the case, restarting Docker after connecting to the VPN should fix that, right? It should see that 172.17.0.0/16 is a route going through PPP and pick a different one?

Thanks for your help!

**Comment by justincormack** [comment]
Ah it is not in the UI yet, but you can do it, although it is a bit, er, advanced:

```
cd ~/Library/Containers/com.docker.docker/Data/database/
git reset --hard
cd com.docker.driver.amd64-linux
echo '{"storage-driver":"aufs","debug":true,"bip":"10.20.0.0/16"}' > etc/docker/daemon.json
git add etc/docker/daemon.json
git commit -m 'update config'
```

Pick an address range without a conflict...

Then restart Docker from the whale menu and it should have changed the default bridge address.

There will be a UI for this soon...

**Comment by okdana** [comment]
It doesn't seem to like that.

Committing the change (and then starting Docker back up) causes the Docker icon to animate like it's doing something for ever, it never actually starts. In the Console i see this every few seconds:

>2016/08/12 18:34:24.487 Docker[69614]: Docker is not responding: Get http://./info: EOF: waiting 0.5s
>2016/08/12 18:34:24.487 Docker[69614]: VM: 2016-08-12 23:34:24 +0000 UTC daemon.info vsudd: 5 Failed to connect to Unix domain socket after 10s /var/run/docker.sock dial unix /var/run/docker.sock: connect: connection refused
>2016/08/12 18:34:24.990 Docker[69614]: VM: 2016-08-12 23:34:24 +0000 UTC daemon.info vsudd: Connection 6 to: 2376 from: 00000000

If i make the change *without* committing it, Docker starts OK, but it continues to use 172.17.0.0/16 like before.

**Comment by justincormack** [comment]
Sorry, you need to give it an IP not a mask, so `{"storage-driver":"aufs","debug":true,"bip":"10.20.0.1/16"}` should work...

**Comment by justincormack** [comment]
(Thats why we want a UI so we can add validation!)

**Comment by okdana** [comment]
Yay, it works now. Thank you again!

**Comment by dwitherspoon** [comment]
I am having a similar issue, but the solution above didn't work for me. If I docker network inspect 72bd17050252 (bridge network) I get the following:

"IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },

The internal docker registry that I am trying to pull docker images from is on 172.20.7.80. I can seem to get a ping, traceroute, or wget all time out because they can't connect to the remote host.

**Comment by eupestov** [comment]
I observe the same issue. My private registry is running behind a ha-proxy instance (marathon-lb) which terminates SSL and is only accessible via VPN. 
Resetting docker to factory defaults helps for some time but after a while it stops working with the message:

$ docker pull registry.***.com/airflow
Using default tag: latest
Error response from daemon: Get https://registry.***.com/v1/_ping: dial tcp 172.18.21.65:443: getsockopt: no route to host

**Comment by maciejkra** [comment]
the solution introduced by "justincormack" worked. However it works only for some short time and after restoring to factory defaults.
When my OS X is in the same network as registry 172.17.3.0/24 (which overlaps by default docker network - even then I have change it). I get the error:
```
docker pull xxx:5000/yameo/postgres:1.0-SNAPSHOT
Pulling repository xxx:5000/yameo/postgres
Error while pulling image: Get http://xxx:5000/v1/repositories/yameo/postgres/images: dial tcp 172.17.3.59:5000: getsockopt: no route to host
```

but:
```
docker run --rm -it debian ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1
    link/ipip 0.0.0.0 brd 0.0.0.0
3: gre0@NONE: <NOARP> mtu 1476 qdisc noop state DOWN group default qlen 1
    link/gre 0.0.0.0 brd 0.0.0.0
4: gretap0@NONE: <BROADCAST,MULTICAST> mtu 1462 qdisc noop state DOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
5: ip_vti0@NONE: <NOARP> mtu 1428 qdisc noop state DOWN group default qlen 1
    link/ipip 0.0.0.0 brd 0.0.0.0
6: ip6_vti0@NONE: <NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1
    link/tunnel6 :: brd ::
7: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1
    link/sit 0.0.0.0 brd 0.0.0.0
8: ip6tnl0@NONE: <NOARP> mtu 1452 qdisc noop state DOWN group default qlen 1
    link/tunnel6 :: brd ::
9: ip6gre0@NONE: <NOARP> mtu 1448 qdisc noop state DOWN group default qlen 1
    link/gre6 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00 brd 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
23: eth0@if24: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:0a:14:00:02 brd ff:ff:ff:ff:ff:ff
    inet 10.20.0.2/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:aff:fe14:2/64 scope link tentative
       valid_lft forever preferred_lft forever
```

And...
```NETWORK ID          NAME                             DRIVER              SCOPE
f0f66161c66e        bridge                           bridge              local
48611c7cb1c1        host                             host                local
6e635ac284f4        none                             null                local
940e98ffff0b        xxx   bridge              local


docker network inspect xxx
[
    {
        "Name": "xxx",
        "Id": "940e98ffff0bed9aad463bc4b05ccd553111ded25eda9a1793749d322fe7f12e",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1/16"
                }
            ]
        },
        "Internal": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    }
]

```

The funny part - after removing the network it works like a charm...

**Comment by thaJeztah** [comment]
@maciejkra di you specify a subnet when creating network `xxx`? https://docs.docker.com/engine/reference/commandline/network_create/#/specifying-advanced-options

**Comment by maciejkra** [comment]
@thaJeztah nope it was created automatically.

**Comment by thaJeztah** [comment]
@maciejkra the `--bip` option only affects the default "bridge" network, but not any custom network that you create, so if you want to prevent a custom network from overlapping, you need to specify these options when creating that network (or, if you use `docker-compose`, specify them in the docker-compose file)

**Comment by maciejkra** [comment]
@thaJeztah you are right. But when I do the docker pull how does it matter has that I have different networks configured? It shouldn't be affected at all. If any network is used by docker demon to download images form repository it should be the default bridge, not newly created bridge by compose.
It's a bug and a nasty one because I have the registry on the address which overlaps the standard network.

**Comment by thaJeztah** [comment]
@maciejkra I suspect the custom network you created results in network traffic for that range to be routed to that network. But @sanimej may be better explaining / adding more info

**Comment by maciejkra** [comment]
Still I do not think it should affect ```docker pull``
It does not effect the Linux version. It happens only on OS X

**Comment by thaJeztah** [comment]
@maciejkra if it's only affecting docker for mac, it's best to open an issue in the docker for mac issue tracker https://github.com/docker/for-mac/issues

**Comment by twang2218** [comment]
I ran into the same issue under Docker for Mac, I posted details under the `for-mac` issue https://github.com/docker/for-mac/issues/916

And, although the issue is affecting Docker for Mac most time, I think it's related to several `docker` and `libnetwork` issues:

* https://github.com/docker/docker/issues/21776
* https://github.com/docker/docker/pull/29376
* https://github.com/docker/libnetwork/issues/1272
* https://github.com/docker/libnetwork/pull/1591

**Comment by spoganshev** [comment]
Check if you have unused networks:
`docker network ls`

And prune them:
`docker network prune`
