### ISSUE TITLE
REST API bug when starting an container

### ISSUE THREAD

**Issue by Loki-Afro** [docker/docker#25667]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:40:59 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:40:59 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 291
 Running: 9
 Paused: 0
 Stopped: 282
Images: 62
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 688
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.41 GiB
Name: tyr
ID: BOKP:BDNT:4NX7:D26W:3M7L:Y2TV:RSMA:EYGV:C2CS:REFP:EVNH:3EPY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 56
 Goroutines: 77
 System Time: 2016-08-12T17:32:13.892406816+02:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Create a container but do not start it yet
2. Try to start it via the REST API
3. Will fail with `starting container with HostConfig was deprecated since v1.10 and removed in v1.12`

**Describe the results you received:**
The container did not start and I am recieving an 400 HTTP Code instead.
Debug Logs from dockerd: 

**Describe the results you expected:**
Starting the container should just work fine if the post payload is empty or an empty json, e.g. `{}`

**Additional information you deem important (e.g. issue happens only occasionally):**

> Aug 12 17:29:21 tyr dockerd[9899]: time="2016-08-12T17:29:21.278363023+02:00" level=debug msg="Calling POST /v1.24/containers/2e5b53aef3845502580e9ee8acdcd57f967d761015210c05dc37a208438e8250/start"
> Aug 12 17:29:21 tyr dockerd[9899]: time="2016-08-12T17:29:21.278425649+02:00" level=debug msg="form data: {}"
> Aug 12 17:29:21 tyr dockerd[9899]: time="2016-08-12T17:29:21.278449660+02:00" level=error msg="Handler for POST /v1.24/containers/2e5b53aef3845502580e9ee8acdcd57f967d761015210c05dc37a208438e8250/st$rt returned error: starting container with HostConfig was deprecated since v1.10 and removed in v1.12"
> 

There are also cases where everything just works fine:

> Aug 12 17:37:14 tyr dockerd[9899]: time="2016-08-12T17:37:14.769505957+02:00" level=debug msg="Calling POST /v1.24/containers/0af742407d8631299b5e37da4cfc10374d26294e6b4b5c7dce89eff1e8ec581a/start"
> Aug 12 17:37:14 tyr dockerd[9899]: time="2016-08-12T17:37:14.769582892+02:00" level=debug msg="form data: {}"
> Aug 12 17:37:14 tyr dockerd[9899]: time="2016-08-12T17:37:14.770618666+02:00" level=debug msg="container mounted via layerStore: /var/lib/docker/aufs/mnt/f01da2f0f153a1a0f80b4e28fabd86dd23b3af3d694c9af92aee133793b0ba5e"

Is there a way to log eveything that comes in via the API user headers etc? Because I can't see a difference between those two POST requests

**Comment by thaJeztah** [comment]
What software are you using to work with the API? Older versions of docker accepted a `HostConfig` JSON at `/containers/<container>/start` that allowed changing the hostconfig that was set during "create". This is no longer supported (that's what the message says).

I suspect the tool you're using is trying to set `HostConfig`, but that fails (as expected)

**Comment by Loki-Afro** [comment]
I am using https://github.com/docker-java/docker-java

But isn't it weird?
Works:
> Aug 12 17:37:14 tyr dockerd[9899]: time="2016-08-12T17:37:14.769582892+02:00" level=debug msg="form data: {}"
Does not work:
> Aug 12 17:29:21 tyr dockerd[9899]: time="2016-08-12T17:29:21.278425649+02:00" level=debug msg="form data: {}"

I can't see a difference in the Output, so I am suspecting a bug here..

**Comment by thaJeztah** [comment]
ping @KostyaSha perhaps you know?

**Comment by KostyaSha** [comment]
> 3. Will fail with starting container with HostConfig was deprecated since v1.10 and removed in v1.12

That not a docker issue and not a docker-java bug. It just docker-java doesn't support 1.24 API version.
docker-java allows set api version, set it to 1.23 until we update models.

**Comment by Loki-Afro** [comment]
@KostyaSha It is correct that docker-java does not support 1.24 yet, see https://github.com/docker-java/docker-java/issues/617

However I still can't see a difference in those 2 log messages above. 

I don't know why docker-java fails here, since it is sending an empty JSON object which seems correct.

**Comment by KostyaSha** [comment]
see issue about sending or not sending empty requests. Btw docker team please comment something what is right and doesn't

**Comment by Loki-Afro** [comment]
@KostyaSha where is this issue? Or did I miss something?

**Comment by KostyaSha** [comment]
When client sends empty `{}` json to docker daemon, daemon think that it old format with `HostConfig` error message. Possible solutions:
- fix error message
- allow empty json
In docker-java only jersey impl was affected.

**Comment by thaJeztah** [comment]
@KostyaSha API version 1.24 and above will produce an error if a JSON object is sent (including an empty object); older versions still accept the JSON object for backward compatibility.

see [api/server/router/container/container_routes.go#L137-L152](https://github.com/docker/docker/blob/2cc5383f2fd000f4fa9fcaa4e0dd0bc8f6bb9c7f/api/server/router/container/container_routes.go#L137-L152), and [/daemon/start.go#L39-L63](https://github.com/docker/docker/blob/31e3970394998547d64e1220bd437a4c9c1061e3/daemon/start.go#L39-L63)

**Comment by KostyaSha** [comment]
Sorry, 7 chars is magic value? Please change message to `"Doesn't accept any JSON body"` to be clear;

**Comment by KostyaSha** [comment]
#25778
