### ISSUE TITLE
flag provided but not defined: --build-arg

### ISSUE THREAD

**Issue by oliversalzburg** [docker/docker#25664]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:40:59 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:40:59 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 16
 Running: 0
 Paused: 0
 Stopped: 16
Images: 256
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /data/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 223
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null overlay host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.87 GiB
Name: build.example.com
ID: UQAX:WE74:SBIC:AS2C:AEE6:S5TR:V3PD:JQU6:KIHP:Z5YJ:EIEU:IOI4
Docker Root Dir: /data/var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS

**Steps to reproduce the issue:**
In our CI system, I'm running `docker build --build-arg NPM_TOKEN=foo --tag example/example:latest .`

**Describe the results you received:**
I'm getting the following error:
```
flag provided but not defined: --build-arg
See 'docker build --help'.
```

**Describe the results you expected:**
The image would be built.

**Additional information you deem important (e.g. issue happens only occasionally):**
I've tried several ways to pass the argument to `--build-arg`, but I'm always getting the same error. The same command works fine on my local machine. I don't understand what the problem is.

**Comment by oliversalzburg** [comment]
Seems like the Docker version inside the container that is used in the CI system is 1.6. That's probably the cause of the error ;)

**Comment by cpuguy83** [comment]
Sounds like it, thanks!

**Comment by oliversalzburg** [comment]
I just wanted to confirm that it works fine after upgrading Docker inside the container. Cheers :)

**Comment by thaJeztah** [comment]
Thanks for the update @oliversalzburg !
