### ISSUE TITLE
Cannot execute command `date` with parameter `-v`

### ISSUE THREAD

**Issue by embatbr** [docker/docker#25671]
I am running in Docker 1.12.0 the command `date` to get the day before the current day (aka yesterday). I can get the current day using `date`. However, when trying to get yestarday using

```
date -v -1d
```

Docker outputs

```
date: invalid option -- 'v'
Try 'date --help' for more information.
```

what led me to execute

```
date --help
```,

where the parameter `-v` is not present. Should this parameter be present or am I doing something wrong?

**Comment by cpuguy83** [comment]
`date` is not a docker command or related to docker in any way, so closing.

Note that the `-v` flag seems to be present on OSX's version of `date`, but not in busybox, debian, etc.
