### ISSUE TITLE
[Feature Request] Separate log_opts for STDOUT and STDERR

### ISSUE THREAD

**Issue by philicious** [docker/docker#25683]
Basically the problem is #45 #725 and was addressed in merged PR #741

**tl;dr:** sometimes we want the merged STDOUT/STDERR logs to be split again from the docker logs

So for `docker logs` thats possible with `docker logs foo > stdout.log 2>stderr.log` 

However when sending logs via a logging-driver, I dont see how this could be achieved.
Ideally one could supply two sets of `log-opts` for both STDOUT and STDERR.
(Or even have two different drivers maybe...)

**Comment by thaJeztah** [comment]
I think this is a duplicate of https://github.com/docker/docker/issues/22736, https://github.com/docker/docker/issues/17959, and possibly others.

However, note that there's already support for this in (e.g.) the syslog logging driver (see https://github.com/docker/docker/issues/23645, and the discussion on https://github.com/docker/docker/pull/23711)

I'll close this, but feel free to comment after that

**Comment by philicious** [comment]
Ah yes ok. I wasn't sure if that should be handled by the driver or one level higher. 
I'll address this to the GELF driver guys then. 

Thx!

**Comment by philicious** [comment]
@thaJeztah btw the syslog driver also doesnt support what I meant. Also, your linked issues are about the correct loglevel, which is kinda related but a different use-case. So not a duplicate.

What I had in mind was having the option to actually specify two different log_opts sets for STDOUT and STDERR messages. (in my case host+port combinations for the logserver)

**Comment by thaJeztah** [comment]
Could you explain the use case? It feels really odd to capture only *part* of the logging output at a single location, and another part in a different location; log entries from `stderr` are usually a result of entries from `stdout`, and splitting those to two different locations just feels odd, and existing solutions should allow you to filter one or the other

**Comment by philicious** [comment]
Imagine a logserver/processor which can have different inputs (e.g. bind ports) for different types of messages. And those inputs expect the same format for every message so pattern matching/processing can be done on those inputs automatically.
With having stdout and stderr in the same input, this approach doesnt work.

Example: 
- nginx docker image (also apache) `ln -s` access and error log to stdout and stderr
- Graylog server has inputs like GELF, syslog et.al. Each input is bound to a UDP/TCP port
- Graylog can have "extractors" for inputs which extract infromation from a log message by regex rules and adds the matches as custom fields to that message. Those fields are also indexed and can be searched for. 
- When using any docker logging driver, one cannot split stdout/stderr to different ports. So both end up in the same input. Extractors then either need much more complex regex rules for working or cant work at all anymore.

Workarounds:
- have the containerized service/application use e.g. syslog directly and not rely on the docker logging driver. works in some scenarios, doesnt in others, depending on overall architecture and aspects like isolation and networking 
- volume the logs into a tiny busybox "log companion" container, so each container only outputs one of stdout/stderr and set different ports in log_opts for each of the containers

both workarounds are rather hack-ish

Conclusion:
As `docker logs` can distinguish between stdout/stderr, aswell as the API, it would only be consistent if the same principle would apply for the logging-drivers in general: ability to set different log-opts for stdout/stderr. 

Does this make any sense to you :smile: ?

**Comment by thaJeztah** [comment]
Alright, let me reopen this for discussion, but I'm not sure if this will be accepted, as it may add a lot of complexity. 

> Ideally one could supply two sets of log-opts for both STDOUT and STDERR. (Or even have two different drivers maybe...)

Having two drivers and two sets of `log-opts` won't happen, but possibly (depending on the driver), a different port could be an option.

**Comment by stefan-hausmann** [comment]
+1 for having the ability to send stdout/stderr logs to different GELF ports!

another alternative (maybe even cleaner, and without the need to support different ports) would be to write "stdout" or "stderr" in an extra GELF field, e.g. "_stream": "stderr" or "_source": "stderr".

**Comment by cpuguy83** [comment]
@stefan-hausmann gelf already does this... https://github.com/docker/docker/blob/master/daemon/logger/gelf/gelf.go#L123-L126

Logs sent to stdout get INFO level, logs sent to stderr get ERR level.

I'm not sure what the ask here is, because these ARE split

**Comment by cpuguy83** [comment]
Closing since we've got no response and the log drivers do typically send logs for stdout and stderr at different logging levels.

**Comment by cpuguy83** [comment]
Feel free to continue to discuss.

**Comment by philicious** [comment]
@cpuguy83 the initial ask was about a way of splitting STDERR and STDOUT so they can be forwarded independently. 
Having an extra field that indicates the level is only helpful in some scenarios. 

If you really need to have them split, you still have to run additional containers that have log-files shared and then use a different port. Which works just fine but is cumbersome.

Whats bothering me the most is that splitting stderr/stdout **is** possible via docker API aswell as via `docker logs` but the logging drivers dont support it. Thats quite an inconsistency in behavior.

**Comment by cpuguy83** [comment]
@philicious I'm not seeing how it is inconsistent. Docker isn't sending the output to different endpoints, the client is splitting the stdout and stderr messages.

I understand the ask, what I don't understand is why?

**Comment by philicious** [comment]
@cpuguy83 see my https://github.com/docker/docker/issues/25683#issuecomment-239645558 for an example.

Generally speaking, as stderr and stdout are two different streams by design, it would be good having the ability of getting their contents separately. 
Think of any log-receiving system that cannot properly delegate/split the messages based on a field but expects each stream in a dedicated input.

If I get you right, the Docker Daemon API is a client for the daemon that is splitting the messages. Ok. But then I would also see the logging driver as a client for the daemon. It would then be drivers responsibility of splitting but there would need to be a way of passing in more than one set of logserver host/port.

**Comment by cpuguy83** [comment]
@philicious I do not think this is a good candidate for adding to docker core. It makes things overly complicated for an abnormal case.

We just merged support for logging plugins yesterday which will be in the 17.05 release.
This could be implemented there for a specific case, for that matter you can use any of the existing drivers and setup your own endpoint to filter messages to the appropriate host/port.

**Comment by philicious** [comment]
@cpuguy83 ye ok. doesnt need to be in core. the logging plugins feature sounds very promising. I'll have a look into that for sure. 

thanks for your time and looking into this ☺️  👍

**Comment by namedgraph** [comment]
I could have implemented a shell script solution using `docker run -d ...`/`docker logs -f`/`docker stop`, but because of this issue I cannot separate the `stdout`/stderr` output and need to resort to `&` background process, writing to a file and doing `tail -f`.
Lame.

**Comment by cpuguy83** [comment]
@namedgraph I'm not sure I follow you there.
`docker logs` does split stdout from stderr.

This feature request was about supporting different log-opts for stdout and stderr streams, which is a driver specific request.

**Comment by namedgraph** [comment]
@cpuguy83 I might need to take my words back :)

Can you point me to docs re. stdout/stderr splitting?

I know I can redirect them to separate files. But I want to avoid files and stream stderr only and pipe it into another process.

**Comment by cpuguy83** [comment]
@namedgraph For this you need to take advandtage of some bash things, here is an example:


```
>&2 echo "error" |& cat > /dev/null
```

Here  the echo command is echoing to stderr (just as a setup), `|&` (bash >= 4.0) pipes stderr to the next commands stdin, and then using `cat > /dev/nul` there just to show it works because you'll still get `error` outputed to your terminal.

Pre-Bash 4.0 I believe you need to do something like

```
>&2 echo "error"  2> >(cat > /dev/null)
```

Stole this from https://stackoverflow.com/questions/1507816/with-bash-how-can-i-pipe-standard-error-into-another-process
