### ISSUE TITLE
Enable syslog logging driver for windows

### ISSUE THREAD

**Issue by mwieczorek** [docker/docker#25689]
Syslog was disabled in https://github.com/docker/docker/commit/655a58e27bfcfd2494bb5d46f95cb49d655ad17a by @jhowardmsft because that time it was using "log/syslog" package (not supported on windows).

Now [syslog.go](https://github.com/docker/docker/blob/master/daemon/logger/syslog/syslog.go#L17) is using "github.com/RackSec/srslog" so it's possbile to use it on windows. (I was able to compile and run docker on windows with syslog enabled).

Would you consider to enable this driver for windows?

**Comment by jhowardmsft** [comment]
No objection at all. Do you want to put a PR together?

**Comment by mwieczorek** [comment]
Ok.
I'll do some additional testing and then will create a PR.
