### ISSUE TITLE
[Swarm mode] Define signals used to stop containers for updates

### ISSUE THREAD

**Issue by mvdstam** [docker/docker#25696]
I'm not sure, but I suspect docker does a `docker stop` (ie. sending a SIGTERM to a container, and then a SIGKILL after waiting 10 seconds) when performing "rolling updates" on a `service`. With some images, like [https://hub.docker.com/_/httpd/](those powered by apache2), this is actually a destructive (non-graceful) way to stop containers, since apache needs a `SIGWINCH` to actually shutdown in a graceful way.

It would be awesome if we could define a signal used to stop services when creating them, for example:

`docker service create --stop-signal SIGWINCH --name my-apache-container httpd:latest`

**Comment by thaJeztah** [comment]
Thanks for suggesting; `docker service` does not have all options that are present on `docker run`, but we're planning to add more options in future releases (although not *all* options will find their way). I added this issue to https://github.com/docker/docker/issues/25303, which is used to keep track on progress; you can subscribe to that issue to stay op to date.

**Comment by mvdstam** [comment]
Cheers @thaJeztah!

**Comment by pnickolov** [comment]
My $.02 - consider making the signal # to use for stopping a container/service part of the Dockerfile rather than the container/service create/run command. The Dockerfile sets the boundary and the termination signal expected of the installed signal is part of the boundary, not of any particular instance. This way, the knowledge belongs where it is defined (i.e., with the software being encapsulated).

**Comment by vingrad** [comment]
+1

**Comment by thaJeztah** [comment]
I realised I didn't mention that here, but although you cannot _override_ the stop-signal when creating a service, if an image should _always_ be stopped with a specific stop-signal; you can define the stop-signal in the Dockerfile (using the [`STOPSIGNAL`](https://github.com/docker/docker/blob/4f926b67f4ee2c1494332d7f1021e3fc45ef045a/docs/reference/builder.md#stopsignal) command), e.g.;

```Dockerfile
FROM httpd:2.2
STOPSIGNAL WINCH
```

Docker services will take that into account when stopping the container;

```
INFO[0120] Container 52aca76dd0c25e733f43121b4097103aae5f2dd125a36c083407d5b61eb8ae50
failed to exit within 10 seconds of signal 28 - using the force
```

**Comment by aluzzardi** [comment]
I think `--stop-signal` should make it into the `ServiceSpec` (/cc @ehazlett)

**Comment by ehazlett** [comment]
@aluzzardi Yes I agree.  Here is a tracking issue to get feedback: https://github.com/docker/docker/pull/30634

**Comment by thaJeztah** [comment]
@ehazlett were already tracking missing options through https://github.com/docker/docker/issues/25303 😇

**Comment by ehazlett** [comment]
Oh well in that case... :)

**Comment by ehazlett** [comment]
Oops didn't mean to close :)

**Comment by yongtang** [comment]
Added a PR #30754 and a SwarmKit PR docker/swarmkit#1924 for `--stop-signal`.
