### ISSUE TITLE
API docs for services don't explain how registry auth works

### ISSUE THREAD

**Issue by dhiltgen** [docker/docker#25691]
At the CLI we expose this with `--with-registry-auth` but the API docs don't explain how API clients can send the registry auth information on service creation or update.

**Comment by thaJeztah** [comment]
Looks like the credentials have to be sent as a header, similar to pulling an image, or plugin https://github.com/docker/docker/blob/656c66dd50d5c5b1f4f40eb4f3134e84e5b80fbc/vendor/src/github.com/docker/engine-api/client/service_create.go#L17

I'll create a PR to add this to the docs
