### ISSUE TITLE
"Untar re-exec error: exit status 1: output: unexpected EOF" on Load

### ISSUE THREAD

**Issue by jonalv** [docker/docker#25711]
**Output of `docker version`:**

```
System I export the file on: Docker version 1.10.3, build 20f81dd
System I load the file on: Docker version 1.11.2, build b9f10c9
```

**Output of `docker info`:**

System I export the file on:
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 29
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /media/jonathan/c11f6a8c-4a97-4bae-afb1-f50f0e473f19/aufs
 Backing Filesystem: extfs
 Dirs: 34
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.0-34-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953 GiB
Name: jonathan-VirtualBox
ID: 47R4:MBM5:TINO:OJTB:XCTV:QU5Z:RCY5:62MK:DQL6:MNDT:NKTN:GFYW
WARNING: No swap limit support
```

System I import the file to:
```
Docker version 1.11.2, build b9f10c9
ip-45-247:~ jonathan$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 5
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.12-boot2docker
Operating System: Boot2Docker 1.11.2 (TCL 7.1); HEAD : a6645c3 - Wed Jun  1 22:59:51 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: default
ID: GIGM:FMFF:VHP6:5FUD:PVW6:6DWD:XFXC:7FLV:7YOP:FMQA:DCJK:QTLW
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 29
 System Time: 2016-08-15T11:57:06.961112113Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Exporting system running in VirtualBox Ubuntu 16.04
Importing system using the Mac default virtual image

**Steps to reproduce the issue:**
1. Exported an image as .tar filr from the Ubuntu machine using: `docker save -o [...]`
2. Importd that file on docker in Mac using: `docker load -i [...]`

**Describe the results you received:**
I got the following error message: `Untar re-exec error: exit status 1: output: unexpected EOF`

**Describe the results you expected:**
No error message

**Additional information you deem important (e.g. issue happens only occasionally):**
This seems rather strange. I had this error using an older Ubuntu distribution as base image fro the exported docker image. Then I changed to 16.04 and the problem went away for a while and now it is back again. I have a hard time figuring out what setup triggers it and what doesn't.

**Comment by jonalv** [comment]
I have seen:
<https://github.com/docker/docker/issues/14792>
<https://github.com/docker/docker/issues/17535>
with similar problems but when pulling and building

**Comment by thaJeztah** [comment]
If you try to load the file on the original system, or on another host running 1.10.3, does it work correctly?

**Comment by jonalv** [comment]
> If you try to load the file on the original system, or on another host running 1.10.3, does it work correctly?

Yes, it seems to do that. That's at least some progress :)
I guess the question then is if I can force install one version to the Ubuntu installation...

**Comment by jonalv** [comment]
Damn, I thought I would be clever and ran: `sudo apt-get upgrade docker.io` and now I get this error instead: `Error response from daemon: client is newer than server (client API version: 1.23, server API version: 1.22)` :(

**Comment by thaJeztah** [comment]
oh, but the `docker.io` package is the package that's maintained by ubuntu, not the official package from apt.dockerproject.org.

You can override the API version using the `DOCKER_API_VERSION` environment variable, e.g. `DOCKER_API_VERSION=v1.22`.

ping @tonistiigi should save/load work between docker 1.10.3 and 1.11.2? I think it should, but perhaps there's an issue there.

**Comment by jonalv** [comment]
Hm, I could not get `DOCKER_API_VERSION=v1.22.` to have any effect what so ever. Feels like things are working even less than they did when I started :)

Are you saying that I would be better of running the apt.dockerproject.org package instead of the docker.io package? I can't quite understand how to make the switch. Can you point me to something?

**Comment by thaJeztah** [comment]
You can purge the existing install (`sudo apt-get purge docker.io`), then install docker from the `apt.dockerproject.org` repository; the easy install is doing so by

    curl -fsSL https://get.docker.com | sh

Or follow the procedure described in https://docs.docker.com/engine/installation/linux/ubuntulinux/

**Comment by jonalv** [comment]
Hm managed to upgrade the `docker.io` package to version: `Docker version 1.11.2, build b9f10c9` and I still get that error. Strange thing is that sometimes it works and sometimes I get that error. I have not yet managed to get the error with exactly the same content but the changes has been so small that I must believe that the content is not having an effect on whether the error occurs. Maybe the next step is to test using the other docker distribution...

**Comment by jonalv** [comment]
OK, I didn't change anything, reran and it worked. Really weird. Is there some log file or something which might give more information?

**Comment by jonalv** [comment]
Indications indicate the problem is with corrupt download from Jenkins so closing this.

**Comment by thaJeztah** [comment]
Thanks for the update @jonalv
