### ISSUE TITLE
GO Issue with building registry 

### ISSUE THREAD

**Issue by aabergaa** [docker/docker#25729]
**Output of `docker version`:**

```
Docker version 1.10.1, build 9e83765
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on a 32 core physical server on a disconnected private network so access to docker.io, github.com/..., and any other repo sites is not an option in builds

**Steps to reproduce the issue:**
1. Install docker-engine and dependencies. Import a base image (only RH derivatives are an option, the base used has basic build tools (C,C++, Java, make) install able if needed. 
2. Import the docker, docker-distribution to build a newer version of the registry 
3. run docker build on the distribution dockerfile (noting the Docker files were shifted to an available centos7.2 image base with build tools added to the install at first stages). 

**Describe the results you received:**
Everything start out fine, during the final stages of the go compiling (I assume), I get:

#github.com/docker/distribution/registry/storage/driver/base
registry/storage/driver/base/regulator.go:85: r.StorageDriver.Reader undefined (type driver.StorageDriver has no field or method Reader)
registry/storage/driver/base/regulator.go:85: not enough arguments to return
registry/storage/driver/base/regulator.go:92: undefined: driver.FileWriter
registry/storage/driver/base/regulator.go:96: r.StorageDriver.Writer undefined (type driver.StorageDriver has no field or method Writer)
#github.com/docker/distribution/registry/storage
registry/storage/garbagecollect.go:20: undefined: distribution.RepositoryEnumerator
registry/storage/garbagecollect.go:37: cannot use named (type reference.Named) as type string in argument to registry.Repository
registry/storage/garbagecollect.go:47: undefined: distribution.ManifestEnumerator
registry/storage/garbagecollect.go:104: registry.Blobs undefined (type distribution.Namespace has no field or method Blobs)

I have checked those files from my tarballs that get imported to the image, and those functions seem to be defined as they are being used. 

**Describe the results you expected:**
I properly built docker image to run as a registry. 

**Additional information you deem important (e.g. issue happens only occasionally):**
If I do not import the main docker/docker tarball, many more such errors occur. I assume this is some go issue with some versioning, but not sure what steps are necessary to correct it. I have go 1.6.3 being installed to the image, but have also tried 1.5.3 with similar results. 
For reference, the Dockerfile being used inplace of the default in the docker/distribution:
```
FROM local-registry:5000/centos7

ADD go1.6.3.linux-amd64.tar.gz /usr/local

ENV PATH /go/bin:/usr/local/go/bin:$PATH
ENV GOPATH /go:/go/src/github.com/docker/docker/vendor
ENV DOCKER_BUILDTAGS include_oss include_gcs

#add the docker.git repo files:
ADD docker.tar.gz.orig /go/
#add the docker/distribution repo files:
ADD distribution.tar.gz /go/src/github.com/docker/distribution/
#dependencies of go file on AdRoll's goamz needed to be added:
ADD goamz.tar.gz /go/src/

#install make:
RUN yum install --assumeyes make

WORKDIR /go/src/github.com/docker/distribution

RUN  \
GOPATH="$GOPATH/Godeps/_workspace:$GOPATH" \
 && make PREFIX=/go clean binaries

#NOTES: command tried from docker/Dockerfile also produced same error after pulling in the cloned repos:
# go build -o /usr/local/bin/registry-v2 github.com/docker/distribution/cmd/registry \

```

**Comment by thaJeztah** [comment]
Can you open this issue in the docker/distribution issue tracker instead? This looks to be something with that codebase, also note that there's a document in that repository that may contain some more info about building yourself; https://github.com/docker/distribution/blob/master/BUILDING.md
