### ISSUE TITLE
Docker grows from 500mb to 2GB memory use in a day with no new containers started

### ISSUE THREAD

**Issue by JonasT** [docker/docker#25762]
The docker daemon memory use on my machine grows from 500mb to 2GB in a day with no new containers started. This seems to have started with a recent update, and it's wrecking havoc on my production machine. A fix would be appreciated.

**Output of `docker version`:**

```
root@Ubuntu-1510-wily-64-minimal ~ # docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:59:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:59:07 2016
 OS/Arch:      linux/amd64
root@Ubuntu-1510-wily-64-minimal ~ #
```

**Output of `docker info`:**

```
root@Ubuntu-1510-wily-64-minimal ~ # docker info
Containers: 56
 Running: 3
 Paused: 0
 Stopped: 53
Images: 1362
Server Version: 1.10.3
Storage Driver: btrfs
 Build Version: Btrfs v4.0
 Library Version: 101
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-34-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.86 GiB
Name: Ubuntu-1510-wily-64-minimal
ID: 2ILP:SBMD:2NB7:JY7W:YC3K:CYYV:AX5E:FZLB:CON4:3JCT:3GT4:W4PB
WARNING: No swap limit support
root@Ubuntu-1510-wily-64-minimal ~ # 
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Start a lot of services
2. Wait 48 hours (let them run, don't stop/start any)
3. Check excessive memory usage of docker daemon

**Describe the results you received:**
Absolutely excessive memory usage growth

**Describe the results you expected:**
Memory usage stays at 500MB

**Additional information you deem important (e.g. issue happens only occasionally):**
This used to never happen, now it happens always. I pretty much need to restart the docker daemon & with it all my services daily, or the server runs out of memory.

**Comment by justincormack** [comment]
Can you see if the same thing happens on a more recent version, eg 1.12.0?

Also you do not say how you are measuring the memory usage, it would help to see the output of what you are running to make comparisons easier and to see what measure you are using.

**Comment by JonasT** [comment]
I didn't write down the exact numbers because I tried to fix in the situation in kind of a hurry before it ran completely out of memory, right now I'm not so sure I checked the correct column in htop 😕  how about I update this tomorrow if it's actually the docker daemon before anyone wastes their time with a big bug hunt? Sorry about that, I should have checked this more thoroughly before filing. I'll update tomorrow with more accurate numbers and/or close..

**Comment by thaJeztah** [comment]
Note that Ubuntu Wiley reached EOL recently, and won't receive security updates (not related, just something to pay attention to)

**Comment by JonasT** [comment]
It seems I actually looked at the virtual memory instead of resident memory so this is a misfile, sorry again!
