### ISSUE TITLE
Flaky test: TestExternalVolumeDriverUnnamed

### ISSUE THREAD

**Issue by tonistiigi** [docker/docker#25766]
```
11:11:57 
11:11:57 ----------------------------------------------------------------------
11:11:57 FAIL: docker_cli_external_volume_driver_unix_test.go:279: DockerExternalVolumeSuite.TestExternalVolumeDriverUnnamed
11:11:57 
11:11:57 [d48404230] waiting for daemon to start
11:11:57 [d48404230] daemon started
11:11:57 docker_cli_external_volume_driver_unix_test.go:289:
11:11:57     c.Assert(s.ec.removals, checker.Equals, 1)
11:11:57 ... obtained int = 0
11:11:57 ... expected int = 1
11:11:57 
11:11:57 [d48404230] exiting daemon
11:11:59 
11:11:59 ----------------------------------------------------------------------
```

https://jenkins.dockerproject.org/job/Docker%20Master/label=centos%20&&%20devicemapper/6514/console
https://jenkins.dockerproject.org/job/Docker%20Master/label=rhel%20&&%20devicemapper/6505/changes
https://jenkins.dockerproject.org/job/Docker%20Master/label=centos%20&&%20devicemapper/6484/changes
https://jenkins.dockerproject.org/job/Docker%20Master/label=centos%20&&%20devicemapper/6430/changes

I think it broke with https://github.com/docker/docker/pull/20848 . The first failure I can see is on August 9th.

ping @WeiZhang555

**Comment by WeiZhang555** [comment]
I'll take a look.
