### ISSUE TITLE
updated service frequently will report Failed to delete real server 10.255.0.15 for vip 10.255.0.12 fwmark 268: no such file or directory

### ISSUE THREAD

**Issue by shenshouer** [docker/docker#25797]
**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
$ docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 17
Server Version: 1.12.0
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null overlay bridge
Swarm: active
 NodeID: 5xig0dyp26ebrxp1g4043fk9g
 Is Manager: true
 ClusterID: 5y9yaqelshau40nm55awdk41h
 Managers: 7
 Nodes: 7
 Orchestration:
  Task History Retention Limit: 10
 Raft:
  Snapshot interval: 10000
  Heartbeat tick: 1
  Election tick: 3
 Dispatcher:
  Heartbeat period: 5 seconds
 CA configuration:
  Expiry duration: 3 months
 Node Address: 10.50.1.101
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.6.3-coreos
Operating System: CoreOS 1068.6.0 (MoreOS)
OSType: linux
Architecture: x86_64
CPUs: 40
Total Memory: 125.9 GiB
Name: worker-10-50-1-101
ID: ATRO:LG4Q:YR6Z:SOJM:KIFV:Q5PM:5QGK:OWYD:FWQA:OENT:Y5VT:4YJD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 IP=10.50.1.101
 CPU_NUMBER=40
 MEMORY=131990668kB
 DISK=hdd
 VERSION=1068.6.0
 NAME=CoreOS
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

at physical, on CoreOS :
```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1068.6.0
VERSION_ID=1068.6.0
BUILD_ID=2016-07-12-1826
PRETTY_NAME="CoreOS 1068.6.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

**Steps to reproduce the issue:**

updated the replicas,target port,  and etc. properties of service frequently with go library `engine-api`. and can`t load balance the service

**Describe the results you received:**
Can load balance of the service

**Describe the results you expected:**
Can load balance of the service

**Additional information you deem important (e.g. issue happens only occasionally):**

```
Aug 17 18:57:54 worker-10-50-x-x bash[6023]: time="2016-08-17T18:57:54.503203843+08:00" level=info msg="Failed to delete real server 10.255.0.15 for vip 10.255.0.12 fwmark 268: no such file or directory"
Aug 17 18:57:54 worker-10-50-x-x bash[6023]: time="2016-08-17T18:57:54.503339899+08:00" level=info msg="Failed to delete real server 10.255.0.14 for vip 10.255.0.12 fwmark 268: no such file or directory"
Aug 17 18:57:54 worker-10-50-x-x bash[6023]: time="2016-08-17T18:57:54.503418125+08:00" level=info msg="Failed to delete real server 10.255.0.14 for vip 10.255.0.12 fwmark 268: no such file or directory"
Aug 17 19:01:17 worker-10-50-x-x bash[6023]: time="2016-08-17T19:01:17+08:00" level=info msg="Firewalld running: false"
Aug 17 19:01:17 worker-10-50-x-x bash[6023]: time="2016-08-17T19:01:17.383946464+08:00" level=warning msg="failed to create proxy for port 30001: listen tcp :30001: bind: address already in use"
Aug 17 19:01:17 worker-10-50-x-x bash[6023]: time="2016-08-17T19:01:17+08:00" level=info msg="Firewalld running: false"
Aug 17 19:01:17 worker-10-50-x-x bash[6023]: time="2016-08-17T19:01:17+08:00" level=info msg="Firewalld running: false"
Aug 17 19:01:17 worker-10-50-x-x bash[6023]: time="2016-08-17T19:01:17+08:00" level=info msg="Firewalld running: false"
Aug 17 19:07:54 worker-10-50-x-x bash[6023]: time="2016-08-17T19:07:54.503055882+08:00" level=info msg="Failed to delete real server 10.255.0.15 for vip 10.255.0.12 fwmark 269: no such file or directory"
Aug 17 19:07:54 worker-10-50-x-x bash[6023]: time="2016-08-17T19:07:54.503157061+08:00" level=info msg="Failed to delete real server 10.255.0.15 for vip 10.255.0.12 fwmark 269: no such file or directory"
```

**Comment by fengbb** [comment]
me too 
docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 40
Server Version: 1.12.0
Storage Driver: overlay
 Backing Filesystem: xfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null overlay bridge
Swarm: active
 NodeID: dqdgz53n1x0ktomgjvyq7etyp
 Is Manager: true
 ClusterID: a1v1khdu0xwbhvbs5ifpmj6qn
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot interval: 10000
  Heartbeat tick: 1
  Election tick: 3
 Dispatcher:
  Heartbeat period: 5 seconds
 CA configuration:
  Expiry duration: 3 months
 Node Address: 192.168.76.102
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.7.0-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 62.84 GiB
Name: k8snode2
ID: BLP7:S4SV:FS2E:7PRW:JMH3:4QTX:RBMM:R4UK:AKZE:S43S:NRXR:A4ZH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 docker.hc360.org
 127.0.0.0/8
when i use docker service update service=SERVICENAME 
Aug 18 10:08:33 k8snode2 dockerd: time="2016-08-18T10:08:32.923693811+08:00" level=info msg="Failed to delete real server 10.255.0.6 for vip 10.255.0.3 fwmark 300: no such file or directory"
Aug 18 10:08:33 k8snode2 dockerd: time="2016-08-18T10:08:32.923912987+08:00" level=info msg="Failed to delete real server 10.255.0.6 for vip 10.255.0.3 fwmark 300: no such file or directory"
Aug 18 10:08:33 k8snode2 dockerd: time="2016-08-18T10:08:32.924689325+08:00" level=info msg="Failed to delete real server 10.255.0.6 for vip 10.255.0.3 fwmark 300: no such file or directory"
Aug 18 10:08:33 k8snode2 dockerd: time="2016-08-18T10:08:32.924868701+08:00" level=info msg="Failed to delete real server 10.255.0.6 for vip 10.255.0.3 fwmark 300: no such file or directory"
Aug 18 10:08:33 k8snode2 dockerd: time="2016-08-18T10:08:33.013508652+08:00" level=info msg="Failed to delete real server 10.255.0.5 for vip 10.255.0.3 fwmark 300: no such file or directory"
Aug 18 10:08:33 k8snode2 dockerd: time="2016-08-18T10:08:33+08:00" level=info msg="Firewalld running: false"
Aug 18 10:08:33 k8snode2 dockerd: time="2016-08-18T10:08:33.106647238+08:00" level=info msg="Failed to delete real server 10.255.0.5 for vip 10.255.0.3 fwmark 300: no such file or directory"

**Comment by shenshouer** [comment]
It worked for me after update docker to 1.12.1
