### ISSUE TITLE
Suggest:Makefile add parameter mtu

### ISSUE THREAD

**Issue by adaiguoguo** [docker/docker#25795]
**Steps to reproduce the issue:**
I use repo to build rpm but my vm is under VPN,the VPN's mtu is 1333
DOCKER_EXPERIMENTAL=1 make rpm

**Describe the results you received:**
Unknown SSL protocol error in connection to github.com:443

I suggest Makefile add parameter mtu to decrease docker in docker 's mtu.

**Comment by justincormack** [comment]
You can set the mtu of the `docker0` bridge by passing `--mtu=...` to docker on start up. Setting the MTU at compile time is not sensible, it only makes sense at runtime.

I am closing this as we will not make it a compile time option, but feel free to continue discussion.
