### ISSUE TITLE
Docker swarm service fails to start container with standard Nginx image

### ISSUE THREAD

**Issue by rbrecheisen** [docker/docker#25796]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 1
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 12
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: active
 NodeID: 6nhk639yed29lxu7iaux2dchj
 Is Manager: true
 ClusterID: 9ju6zuezz7jr2jkbg5s0cz2j2
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot interval: 10000
  Heartbeat tick: 1
  Election tick: 3
 Dispatcher:
  Heartbeat period: 5 seconds
 CA configuration:
  Expiry duration: 3 months
 Node Address: 192.168.99.103
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.16-boot2docker
Operating System: Boot2Docker 1.12.0 (TCL 7.2); HEAD : e030bab - Fri Jul 29 00:29:14 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: manager
ID: 75NO:K56A:E7QH:O2FO:32HH:YPMS:ATRU:RY45:MAWO:FEXZ:FICL:MTKW
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 32
 Goroutines: 184
 System Time: 2016-08-17T09:48:39.755480678Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I'm walking through the example setup described on the Docker documentation site [here](https://docs.docker.com/engine/swarm/networking) trying to attach services to an overlay network. The example first creates an Nginx service and then a BusyBox service that connects to the Nginx container via the overlay network. Instead of having 3 physical host machines, as described in the example, I simulated the setup using 3 VirtualBox VMs created with Docker Machine (exact procedure described below).

**Steps to reproduce the issue:**

Run these commands to setup the environment

- docker-machine stop default
- docker-machine create -d virtualbox manager
- docker-machine create -d virtualbox worker1
- docker-machine create -d virtualbox worker2
- eval $(docker-machine env manager)
- docker swarm init --advertise-addr $(docker-machine ip manager)
- token=$(docker swarm join-token --quiet worker)
- eval $(docker-machine env worker1)
- docker swarm join --token ${token} $(docker-machine ip manager):2377
- eval $(docker-machine env worker2)
- docker swarm join --token ${token} $(docker-machine ip manager):2377
- eval $(docker-machine env manager)
- docker network create --driver overlay --opt encrypted my-network

The steps above all complete successfully and result in 3 nodes: 1 manager and 2 worker nodes. I also created an overlay network that should allow communication between services with running tasks. Following the example, the next step is to create an Nginx service that uses the overlay network 'my-network'. The example specifies 3 replicas. However, I use only 1.

- docker service create --replicas 1 --name my-nginx --network my-network nginx

**Describe the results you received:**

When I enter 'docker service ls' I see the following output:

    ID            NAME      REPLICAS  IMAGE  COMMAND
    5pbjapmdl4wi  my-nginx  0/1       nginx

The service fails to start. The number of replicas remains 0/1. When I type 'docker service ps my-nginx' I get the following output:

ID                         NAME            IMAGE  NODE     DESIRED STATE  CURRENT STATE          ERROR
0w7i0vlm1g15ugk99mdky0qcd  my-nginx.1      nginx  worker2  Ready          Ready 2 seconds ago    
7bw4nr666ekpknckv3a73g9te   \_ my-nginx.1  nginx  manager  Shutdown       Failed 3 seconds ago   "starting container failed: ca…"
a762czty5o0y3ye5d40bcwoeh   \_ my-nginx.1  nginx  worker2  Shutdown       Failed 8 seconds ago   "starting container failed: ca…"
4a6qhd0w5uboqn3xq7ktpqhd8   \_ my-nginx.1  nginx  manager  Shutdown       Failed 14 seconds ago  "starting container failed: ca…"
47v38s3lmduvrpeol5sj9wn8u   \_ my-nginx.1  nginx  worker2  Shutdown       Failed 19 seconds ago  "starting container failed: ca…"

The above messages indicate the container failed to start. Unfortunately, the error message is truncated and I have no idea how to get the rest of it. There's no 'logs' option for the service. I also can't retrieve the container logs because the container is no longer running. If I run the container directly using 'docker run -d nginx' everything is fine. The container starts and I can enter it with 'docker exec -it <container id> bash' and see that nginx is running using 'ps -ef'. So, the container itself seems fine. Only when I start it via the service command, do I get problems.

**Describe the results you expected:**

I expected the Nginx service to start and boot up the 1 replica that was specified (as is assumed in the example on the Docker documentation site).

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by rbrecheisen** [comment]
Seems the Nginx container starts fine if I use an overlay network without the "--opt encrypted" option. Not sure if this helps.... Earlier I was working with Docker client 1.11 and upgraded to 1.12 by re-installing Docker Toolbox (for Mac). When I restarted Docker Machine it complained about the TSL certificates and suggested I regenerate them, which I did. This might have something to do with it but I have no idea what the connection is with my errors.

**Comment by rbrecheisen** [comment]
I search around for issues with swarm services and encrypted overlay networks and stumbled upon this docker issue #24253 which did not exactly address my problem but mentioned a hidden option (at the time) "--opt secure" instead of "--opt encrypted" (which I used). I tried the "secure" option and now my Nginx service is starting correctly. 

So, this seems to be a documentation issue because the (I assume) latest version of the Docker Docs mentions the "--opt encrypted" option.... [link](https://docs.docker.com/engine/swarm/networking)

**Comment by r00tjimmy** [comment]
my problem is this too, thanks for your research and answer, i will try now, and if i fix the problem, i will leave the answer here ~~
