### ISSUE TITLE
docs issue - Retrieve Swarm Join Token API documentation 

### ISSUE THREAD

**Issue by yongshin** [docker/docker#25819]
**Steps to reproduce the issue:**
1. Go to https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/display-system-wide-information and search for /swarm to look for how to get swarm join token 
2.
3.

**Describe the results you received:**

No results on how to retrieve swarm join token. 

**Describe the results you expected:**

The API to retrieve the swarm join token should be available on the API docs

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
The missing endpoint was added https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api_v1.24.md#inspect-swarm in https://github.com/docker/docker/pull/25753, and should be online soon. Sorry for the inconvenience, but thanks so much for reporting!

I'll close this because this was resolved

**Comment by alaagalal** [comment]
> The missing endpoint was added https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api_v1.24.md#inspect-swarm in #25753, and should be online soon. Sorry for the inconvenience, but thanks so much for reporting!
> 
> I'll close this because this was resolved

 the link not found ???

**Comment by thaJeztah** [comment]
@alaagalal this issue is two years old, and the document was moved in the github repository; I updated the link on github, but keep in mind that this is an issue tracker, not the documentation, so links and comments will get out of date
