### ISSUE TITLE
docker-engine: Install Issues on Debian Wheezy

### ISSUE THREAD

**Issue by chrisbrokethetable** [docker/docker#25813]
Hi, I'm very new to Linux and are having some issues installing the docker on a Debian Wheezy machine. I saw that there have been problems in the past and have been consulting [this ](https://github.com/docker/docker/issues/15692)thread and, per a suggestion there, trying to use [this ](https://docs.docker.com/v1.8/installation/debian/#debian-wheezy-stable-7-x-64-bit)installation guide. However, I still have an error about uninstallable packages. 

I'm running 
`Linux d23-251 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3~bpo70+1 (2016-07-07) x86_64 GNU/Linux`

To my understanding, I have opened the backports. The source.list file is contains
`deb http://ftp.debian.org/debian wheezy-backports main contrib non-free`

Still, when I run either
`sudo apt-get install docker-engine`
or
`curl -sSL https://get.docker.com/ | sh`
I get the same error output: 

Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 docker-engine : Depends: libapparmor1 (>= 2.6~devel) but it is not installable
                 Recommends: aufs-tools but it is not installable
                 Recommends: cgroupfs-mount but it is not going to be installed                                                                                      or
                             cgroup-lite but it is not installable
E: Unable to correct problems, you have held broken packages.

Any suggestions? What are these "not installable" items?

**Comment by ektich** [comment]
@chrisbrokethetable I'm afraid the installation guide you are referring to is outdated in that current Debian "stable" is Jessie (8.0), not Wheezy (7.0) (see [Debian Releases](https://wiki.debian.org/DebianReleases) ). Do you have to use Wheezy or can you upgrade to Debian Jessie?

**Comment by ektich** [comment]
@chrisbrokethetable can you post the output of "apt-cache policy libapparmor1"? On a Wheezy system it should be similar to this:
```
libapparmor1:
  Installed: 2.7.103-4
  Candidate: 2.7.103-4
  Version table:
 *** 2.7.103-4 0
        500 http://debian.heanet.ie/debian/ wheezy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by chrisbrokethetable** [comment]
Unfortunately I'm fairly restricted to Wheezy, the computer is not owned by me and has some technical software on it that I'm afraid I wouldn't be able to update were I to change the OS.

The output for that command shows that I have nothing installed, which clearly addresses some problem:

        $ sudo apt-cache policy libapparmor1
        libapparmor1:
          Installed: (none)
          Candidate: (none)
          Version table:

What is this program for? Can I easily download it?

**Comment by ektich** [comment]
@chrisbrokethetable your apt is not configured properly: you should see it in the Candidate section. It looks like your apt system is not pointing to main Debian repository (libapparmor1 is in the "main" section of it).

What does your /etc/apt/sources.list look like? Do you have a directory called /etc/apt/sources.list.d/ and do you have any files with .list in them?

See https://wiki.debian.org/SourcesList for more details.

**Comment by thaJeztah** [comment]
thanks for assisting, @ektich, much appreciated :+1:

**Comment by chrisbrokethetable** [comment]
@ektich The only file in that directory is docker.list, which is one that I made for this installation per their installation guide, which contains only

    deb [arch=amd64] https://apt.dockerproject.org/repo debian-wheezy main

 Other than that, the only .list I have is sources.list which fully looks like 

        deb http://ftp.debian.org/debian wheezy-backports main contrib non-free
        deb-src http://ftp.debian.org/debian wheezy-backports main contrib non-free

        deb http://security.debian.org/ wheezy/updates main
        deb-src http://security.debian.org/ wheezy/updates main

        deb http://httpredir.debian.org/debian/ wheezy-updates main
        deb-src http://httpredir.debian.org/debian/ wheezy-updates main

I want to reiterate the thanks also, this has already been hugely helpful!

**Comment by ektich** [comment]
@chrisbrokethetable Somehow you are missing the url to main "wheezy" repository:
add following two lines to sources.list file:
```
deb http://httpredir.debian.org/debian wheezy main contrib non-free
deb-src http://httpredir.debian.org/debian wheezy main contrib non-free
```
and also add `contrib non-free` to the `wheezy/updates` and `wheezy-updates` lines, for consistency. Then run `apt-get update`. After that try installing docker-engine again.

**Comment by chrisbrokethetable** [comment]
It installed!!

@ektich I seriously can't thank you enough, you've saved me from two weeks of turmoil and have been amazingly patient along the way. 100000 internet hugs from me to you!
