### ISSUE TITLE
[v1.12.1] Named volume can't be used after daemon reboot

### ISSUE THREAD

**Issue by tonistiigi** [docker/docker#25821]
1) Create a named volume `docker volume create --name myvol`
2) Using this volume works fine: `docker run -it -v myvol:/foo busybox sh`
3) Restart daemon
4) Try to start a container using the volume `docker run -it -v myvol:/foo busybox sh` returns `docker: Error response from daemon: missing device in volume options.`

Reproduced in `v1.12.1-rc2` and `master`. `v1.12.0` seems ok.

cc @tiborvass @cpuguy83 @mlaventure

**Comment by tonistiigi** [comment]
@cpuguy83 The issue seems to be that https://github.com/docker/docker/pull/25316/files#diff-11981ad04b89536975eb321155a5c2a0R91 now always reads the opts file. In the case of empty options, this file exists and contains string "null". I guess we have to handle this case now for backwards compatibility but probably the file just shouldn't exist or be empty because existence of opts has a special meaning in https://github.com/docker/docker/blob/master/volume/local/local.go#L303

**Comment by cpuguy83** [comment]
The simplest changes breaks in the worst of ways....

**Comment by cpuguy83** [comment]
#25825 fixes this

**Comment by royseto** [comment]
I suspect I was affected by this bug. What do you suggest so that I can get up and running again before waiting for the next Docker update?

I am running Docker for Mac on the beta channel, and upgraded recently to Version 1.12.1-rc1-beta23 (build: 11375). I have a docker-compose.yml that I have used for months and that uses a named volume. It recently stopped working in the last couple days. When I try to attach the named volume that used to work, I get the following error:

```
roysetosmacbook:~ royseto$ docker volume ls
DRIVER              VOLUME NAME
local               app_pgdata
local               app_pgdata_test
local               app_redis_data
local               stl-home
roysetosmacbook:~ royseto$ docker run -it -v stl-home:/home/dev debian
docker: Error response from daemon: missing device in volume options.
roysetosmacbook:~ royseto$ docker volume inspect stl-home
[
    {
        "Name": "stl-home",
        "Driver": "local",
        "Mountpoint": "/var/lib/docker/volumes/stl-home/_data",
        "Labels": {},
        "Scope": "local"
    }
]
```

Here is my previously working docker-compose.yml and the error I just started getting when I try to do docker-compose up now:

```
roysetosmacbook:app royseto$ more docker-compose.yml
version: '2'

services:
  devbox:
    image: royseto/devbox
    ports:
     - "2201:22"
     - "8000:8000"
    volumes:
     - /Users:/Users
     - stl-home:/home/dev
    links:
     - db
     - dbtest
     - redis
  db:
    image: royseto/pgserver
    volumes:
     - pgdata:/mnt/data/pgsql
  dbtest:
    image: royseto/pgserver:unlogged
    volumes:
     - pgdata_test:/mnt/data/pgsql
  redis:
    image: redis
    volumes:
     - redis_data:/data

volumes:
  stl-home:
    external: true
  pgdata: {}
  pgdata_test: {}
  redis_data: {}

roysetosmacbook:app royseto$ docker-compose rm
No stopped containers
roysetosmacbook:app royseto$ docker-compose stop
roysetosmacbook:app royseto$ docker-compose up
Creating app_dbtest_1
Creating app_redis_1
Creating app_db_1
Creating app_devbox_1

ERROR: for devbox  Cannot create container for service devbox: missing device in volume options
ERROR: Encountered errors while bringing up the project.
```

**Comment by cpuguy83** [comment]
@royseto I'm not sure if you can use the master channel for docker4mac? That is using the final version of 1.12.1
The other option would be to downgrade to beta 22

**Comment by royseto** [comment]
@cpuguy83 Thank you for the quick response. I installed Version 1.12.0-a (build: 11213) from the Stable channel for docker4mac over my existing installation and my docker-compose.yml comes up normally again, with existing named volume data intact.

**Comment by gittycat** [comment]
I just hit the same issue. Reverting to the stable version also works for me https://docs.docker.com/docker-for-mac

Is it possible to manually update the docker daemon used by docker4mac? I'm talking about the daemon that's running on the hyvee vm, not the docker client.

**Comment by willgdjones** [comment]
I have a similar issue - though simply with the commands:

`docker volume create --opt o=size=200g --name=bitcoind-data`

`docker run --volume bitcoind-data:/bitcoin --volume-driver local --name=bitcoind-node -d -p 8333:8333 -p 127.0.0.1:8332:8332 kylemanna/bitcoind`

**Comment by cpuguy83** [comment]
@willgdjones `size` is not a valid option here. You must provide a `--opt type=<type>` and a `--opt device=<dev path>` in addition to any `--opt o=<opts>` options.

**Comment by willgdjones** [comment]
@cpuguy83 Thanks for the response. So in order to reserve 200G of disk space in the volume, without any other specifications the command would be:

`docker volume create --type=none --opt o=size=200g --opt device=local --name=bitcoind-data`

**Comment by cpuguy83** [comment]
@willgdjones No. These options are mount options and must be supported by the underlying filesystem being mounted.

**Comment by willgdjones** [comment]
My underlying filesystem has > 200G disk space. Are these options correct for this case?

**Comment by cpuguy83** [comment]
No.

**Comment by willgdjones** [comment]
Ok, then I don't understand your response. What would the correct options for this be? Thanks in advance.

**Comment by cpuguy83** [comment]
@willgdjones When you pass options to the local volume driver you are doing the equivalent of `mount -t <type> -o <o opts> <device>`.
If you can't do it with that tool, then you can't do it.

**Comment by willgdjones** [comment]
Not sure I follow.

`docker volume create --name=bitcoind-data`
`docker run -v bitcoind-data:/bitcoin --name=bitcoind-node -d \
     -p 8333:8333 \
     -p 127.0.0.1:8332:8332 \
     kylemanna/bitcoind`

**Comment by cpuguy83** [comment]
@willgdjones 

Can you do `mount -t none -o size=200g local`? (btw, I know you can't).
You can't dynamically allocate resources on the local filesystem like this.

**Comment by willgdjones** [comment]
Nope that doesn't seem to be the correct usage of mount either. No problem, thanks for your help.
