### ISSUE TITLE
Documentation for configure-tls doesn't show how to make .key file

### ISSUE THREAD

**Issue by RangerMauve** [docker/docker#25823]
This is an issue with the documentation for setting up TLS in a swarm which can be found [here](https://docs.docker.com/swarm/configure-tls/). In [Step 3](https://docs.docker.com/swarm/configure-tls/#/step-3-create-and-sign-keys) it says that a file called `node-priv.key` will be created which will contain the private key. However, no reference to a `.key` file is found anywhere else in the document. I'm not really sure what changes need to be made, as far as I can tell it crates the private key in a file called `node-priv-key.pem`, but I'm not sure if anything else needed to be done.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I'm not able to find the actual markdown file in the `/docs` folder in the repo which contains the guide.

**Steps to reproduce the issue:**
1. Go through the [swarm/configure-tls](https://docs.docker.com/swarm/configure-tls) guide
2. Expect a `.key` file to be made at some point
3. It isn't

**Describe the results you received:**
The resulting keys two `.pem` files are created, with one of them suggesting it's the private key.

**Describe the results you expected:**
Docs to either refer to the private key consistently or have steps for creating the `.key` file

**Comment by cpuguy83** [comment]
Just looks like a typo, as the commands are shown the key name is `swarm-priv-key.pem`

**Comment by RangerMauve** [comment]
Any pointers to where I could fix this in the docs?

**Comment by cpuguy83** [comment]
https://github.com/docker/swarm/blob/master/docs/configure-tls.md

**Comment by RangerMauve** [comment]
My bad, I was looking in the docs inside this repo instead.

**Comment by thaJeztah** [comment]
It's confusing (Swarm vs Swarm mode); Let me close the issue here, thanks for contributing!
