### ISSUE TITLE
why put src dir under vendor

### ISSUE THREAD

**Issue by andyxning** [docker/docker#25834]
What is the purpose of putting `src` dir under `vendor`. 

It seems that Go can only work with all dependencies directly under `vendor`. Currently, the direct impact of using putting dependencies under `vendor` is that some IDES can not find the reference and will make the import red.  :(

**Comment by vdemeester** [comment]
This is for *historical* reason, when docker was build with older Go version (1.4 and lower), where the `vendor` support in Go was not in place. 

We might want to update our script and such to use the conventionnal way of Go to deal with vendors but it's not that easy of a task :angel: 

/cc @tianon

**Comment by andyxning** [comment]
@vdemeester currently, i move all the folder under `src` to be siblings under `vendor`. However, this make my git status report that lots of file removed. This is frustrating. 

I can also make my `GOPATH` contains the `vendor` path. However, it may make my other go project dependencies resolution polluted. 

As [Golang 1.7 is released](https://blog.golang.org/go1.7), `vendor` is the de-facto dependency management solution for Golang. So, i think it is the time to make transform. :)

**Comment by cpuguy83** [comment]
@andyxning PR's are welcome.
Docker provides a working dev environment via `make shell` where build deps, vendoring, etc just works.

**Comment by andyxning** [comment]
@cpuguy83 i will have a try on this weekends. :)

**Comment by thaJeztah** [comment]
I'm closing this issue, because it's not really a bug, and we're aware of this, but keep us posted if you're planning to work on this
