### ISSUE TITLE
Some worker doesn't communicate back to manager on 7946 (Serf). Thus overlay network is failed on such host.

### ISSUE THREAD

**Issue by parinya-ekparinya** [docker/docker#25836]
**Output of `docker version`:**

Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64

**Output of `docker info`:**

Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 8
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay bridge null
Swarm: active
 NodeID: 1w0jy9mpfozs9eilom9vdef1i
 Is Manager: true
 ClusterID: 5toc9vpxjqnjiveic411fkxcu
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot interval: 10000
  Heartbeat tick: 1
  Election tick: 3
 Dispatcher:
  Heartbeat period: 5 seconds
 CA configuration:
  Expiry duration: 3 months
 Node Address: [My manager node public IP]
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-34-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.851 GiB
Name: Manager
ID: IZMU:52KA:FCSV:EWUK:2U7E:V6AO:USSM:ZPBV:from step 1. XRBR:HLFL:GCNB:WXOQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Manager and Worker1 in Azure
Worker2 in AWS

**Steps to reproduce the issue:**

1. Initialize swarm manager (Azure) with:
`docker swarm init --advertise-addr <Manager public IP> --listen-addr eth0`

2. Join worker1 (Azure) with the output from swarm initailization from step 1 plus following options:
`--advertise-addr <Worker1 public IP> --listen-addr eth0`

3. Join worker2 (AWS) with the output from swarm initailization from step 1 plus following options:
`--advertise-addr <Worker2 public IP> --listen-addr ens3`

4. Create an overlay network with:
`docker network create --driver overlay --subnet 10.0.9.0/24 my-network`

5. docker service create --name iperf-s1 \
    --network my-network \
    --constraint 'node.hostname == Worker2' \
    --restart-condition none \
    parinyaekparinya/net-util \
    iperf3 -V -p 5000 -s -1

6. docker service create --name iperf-tcp-c1 \
    --network my-network \
    --constraint 'node.hostname == Worker1' \
    --restart-condition none \
    parinyaekparinya/net-util \
    iperf3 -V -p 5000 -c iperf-s1 -t 30

7. I had tried step 6. with IP too, but it didn't work too.

8. Unlike Worker1, there is no connection or any traffic from Worker2 to Manager with dst port 7946 (Serf) from what I can see with tcpdump at the time of joining. I suspect that this is cause of failure in overlay networking, because docker cannot set it up properly.

**Describe the results you received:**

Using service name as a target for iperf3:
`iperf3: error - unable to connect to server`

Using IP address as a target for iperf3
`iperf3: error - unable to connect to server: No route to host`

**Describe the results you expected:**

Both containers should be able to communicate.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Network Security Group on Azure**

data:    Security rules:
data:    Name                           Source IP          Source Port  Destination IP  Destination Port  Protocol  Direction  Access  Priority
data:    -----------------------------  -----------------  -----------  --------------  ----------------  --------  ---------  ------  --------
data:    default-allow-ssh              *                  *            *               22                TCP       Inbound    Allow   1000    
data:    docker-swarm                   *                  *            *               2377              Tcp       Inbound    Allow   1100    
data:    Serf                           *                  *            *               7946              *         Inbound    Allow   1200    
data:    VXLAN                          *                  *            *               4789              *         Inbound    Allow   1300    
data:    iperf                          *                  *            *               5001              *         Inbound    Allow   4000    

**Security Group on AWS**

"SecurityGroups": [
        {
            "IpPermissionsEgress": [
                {
                    "IpProtocol": "-1", 
                    "IpRanges": [
                        {
                            "CidrIp": "0.0.0.0/0"
                        }
                    ], 
                    "UserIdGroupPairs": [], 
                    "PrefixListIds": []
                }
            ], 
            "Description": "Layer 2 container network", 
            "IpPermissions": [
                {
                    "PrefixListIds": [], 
                    "FromPort": 2377, 
                    "IpRanges": [
                        {
                            "CidrIp": "0.0.0.0/0"
                        }
                    ], 
                    "ToPort": 2377, 
                    "IpProtocol": "tcp", 
                    "UserIdGroupPairs": []
                }, 
                {
                    "PrefixListIds": [], 
                    "FromPort": 4789, 
                    "IpRanges": [
                        {
                            "CidrIp": "0.0.0.0/0"
                        }
                    ], 
                    "ToPort": 4789, 
                    "IpProtocol": "tcp", 
                    "UserIdGroupPairs": []
                }, 
                {
                    "PrefixListIds": [], 
                    "FromPort": 22, 
                    "IpRanges": [
                        {
                            "CidrIp": "0.0.0.0/0"
                        }
                    ], 
                    "ToPort": 22, 
                    "IpProtocol": "tcp", 
                    "UserIdGroupPairs": []
                }, 
                {
                    "PrefixListIds": [], 
                    "FromPort": 7946, 
                    "IpRanges": [
                        {
                            "CidrIp": "0.0.0.0/0"
                        }
                    ], 
                    "ToPort": 7946, 
                    "IpProtocol": "udp", 
                    "UserIdGroupPairs": []
                }, 
                {
                    "PrefixListIds": [], 
                    "FromPort": 5001, 
                    "IpRanges": [
                        {
                            "CidrIp": "0.0.0.0/0"
                        }
                    ], 
                    "ToPort": 5001, 
                    "IpProtocol": "udp", 
                    "UserIdGroupPairs": []
                }, 
                {
                    "PrefixListIds": [], 
                    "FromPort": 7946, 
                    "IpRanges": [
                        {
                            "CidrIp": "0.0.0.0/0"
                        }
                    ], 
                    "ToPort": 7946, 
                    "IpProtocol": "tcp", 
                    "UserIdGroupPairs": []
                }, 
                {
                    "PrefixListIds": [], 
                    "FromPort": 4789, 
                    "IpRanges": [
                        {
                            "CidrIp": "0.0.0.0/0"
                        }
                    ], 
                    "ToPort": 4789, 
                    "IpProtocol": "udp", 
                    "UserIdGroupPairs": []
                }, 
                {
                    "PrefixListIds": [], 
                    "FromPort": 5001, 
                    "IpRanges": [
                        {
                            "CidrIp": "0.0.0.0/0"
                        }
                    ], 
                    "ToPort": 5001, 
                    "IpProtocol": "tcp", 
                    "UserIdGroupPairs": []
                }
            ],

**Comment by parinya-ekparinya** [comment]
It takes a while before Worker2 will communicate via 7946, about 6 minutes after joining. Though, 2 containers still cannot communicate with an overlay network.

**Comment by wcarmon** [comment]
same experience for me

**Comment by parinya-ekparinya** [comment]
I have tried version 1.12.1 too, but the same problem still exists.
Is the swarm mode a recommended solution for multi cloud providers? From what I can see, most people use swarm mode with a single cloud provider or in their own environment.

**Comment by parinya-ekparinya** [comment]
Try again recently and it's work. My problem seems to be the openvswitch; it tries to compete for UDP/4789 which is used for VXLAN.
