### ISSUE TITLE
not able to pull the images on worker nodes from manager nodes through swarm on Docker 1.12?

### ISSUE THREAD

**Issue by hrishikesh988** [docker/docker#25846]
Hi guys,

I know in Docker 1.12, swarm is a in-built functionality. I have created a swarm cluster but i do not any idea on how to do issue docker pull/docker run from manager node to the worker nodes in the cluster. I tried using docker -H tcp://<IP>:<PORT> pull... like I used to do in docker 1.11.x versions but it did not work for docker 1.12.x. I also could not find documentation for this anywhere. Can you please let me know on this ASAP please? I am stuck with this.

**Comment by jhorwit2** [comment]
When you run the swarm command to create a service it will automatically try to pull the image. 

ex: `docker service --mode global create --name hello_world tutum/hello-world` 

That will run 1 hello world container on each node in your cluster and pull down the image on each one.

**Comment by thaJeztah** [comment]
Looks like this question is answered (thanks @jhorwit2), so I'll close this issue, but feel free to comment if it's not clear
