### ISSUE TITLE
Do we want to (and will users accept) the Docker daemon changing permissions on an existing path for (root dir) access to work via a user namespaced process?

### ISSUE THREAD

**Issue by CRTX** [docker/docker#25847]
Just as Ubuntu 16.04 [lxcfs bug](https://github.com/docker/docker/issues/24834#issuecomment-240836035) got fixed, now with the new namespace feature we are not able to use namespaces together with the `--graph` parameter.

When using Docker 1.12.0 and lxcfs 2.0.3 with `--userns-remap=Default` and `--graph /media/user/somedrive/docker` throws the following error when doing any command such as `docker run hello-world`:

`docker: Error response from daemon: oci runtime error: rootfs_linux.go:42: preparing rootfs caused "permission denied".`

On my development machine I have a small SSD so I'm not able to use the default `/var/lib/docker` for long before I run out of space from having to work with many images. Being able to use the `--graph` feature would really help with the already awesome docker namespace feature.

**Comment by thaJeztah** [comment]
ping @estesp

**Comment by estesp** [comment]
Yes, came up in the lxcfs issue and I asked for a separate issue to be opened as it is unrelated, but happened to be found by @CRTX during testing of the fix.

It represents a hole in the current assumption that the path elements preceding the "new" docker root have fairly open access permissions (at least the "execute" bit for the directories), and this is true if (a) we create the dirs, or (b) the graphroot requested is in a fairly well known location that exists with reasonably wide permissions (e.g. /var/lib).

The PR to fix would be quite easy, but I wanted to validate that we are OK with adding the "x" bit to any pre-existing dir in the provided path walking back to root (/), as that is in essence modifying the user's system (although the "x" bit only allows traversal, not even read).

**Comment by estesp** [comment]
If we feel that would be "intrusive" (modifying pre-existing dir permbits) then we at least have to add a warning on engine start if we know the access won't work, and add docs on how to prepare a directory to be a graph root dir.

**Comment by justincormack** [comment]
I don't like modification much, I think printing an error is fine. It is fairly rare as most people will use a path under var anyway, or create with world `x`, so I would say better to error out.

**Comment by CRTX** [comment]
After upgrading this is affecting me again in Ubuntu 16.10
Using Docker version 1.12.3, build 6b644ec
lxcfs 2.0.4

Unlike before I'm able to run `docker run hello-world` but I'm not able to mount local volumes

`docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:53: mounting \\\\\\\"/media/user/drive/software/dev/nginx/nginx.conf\\\\\\\" to rootfs \\\\\\\"/media/user/drive/docker/231072.231072/aufs/mnt/fd988291bc6a07e6fb8f84395f2d04aedfb296008078c444d334393f7eb2d404\\\\\\\" at \\\\\\\"/media/user/drive/docker/231072.231072/aufs/mnt/fd988291bc6a07e6fb8f84395f2d04aedfb296008078c444d334393f7eb2d404/etc/nginx/nginx.conf\\\\\\\" caused \\\\\\\"operation not permitted\\\\\\\"\\\"\"\n".
`

Should I make it into a new bug or is it still related to this? I've used `chmod o+x` to every folder up to the parent `/media` folder and I still get "operation not permitted"

**Comment by chepurko** [comment]
I'm getting the exact same thing as @CRTX.
