### ISSUE TITLE
Panic on SetupIngress

### ISSUE THREAD

**Issue by tonistiigi** [docker/docker#25848]
Got this after `swarm leave`

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x87044e]

goroutine 150 [running]:
panic(0x1b39ba0, 0xc8200100a0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/docker/libnetwork.(*network).addDriverWatches(0xc82090cdc0)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/agent.go:476 +0x58e
github.com/docker/libnetwork.glob.func1(0x7f43a577f4e0, 0xc82090cdc0, 0xc82090cdc0)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/controller.go:672 +0x264
github.com/docker/libnetwork.(*controller).NewNetwork(0xc82043e780, 0xc82074c1c0, 0x7, 0xc82074c190, 0x7, 0xc82117d8a0, 0x19, 0xc820d60d00, 0x7, 0x8, ...)
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/controller.go:662 +0x9da
github.com/docker/docker/daemon.(*Daemon).createNetwork(0xc82039c000, 0x1, 0xc82074c1c0, 0x7, 0x0, 0xc82074c1d0, 0x7, 0x0, 0xc8211aaac0, 0x1, ...)
	/go/src/github.com/docker/docker/daemon/network.go:260 +0xe26
github.com/docker/docker/daemon.(*Daemon).SetupIngress.func1(0xc82039c000, 0xc8200a1950, 0xc82074c420, 0x10, 0x10)
	/go/src/github.com/docker/docker/daemon/network.go:144 +0x1ab
created by github.com/docker/docker/daemon.(*Daemon).SetupIngress
	/go/src/github.com/docker/docker/daemon/network.go:178 +0x10b
```

@mrjana @sanimej

**Comment by mrjana** [comment]
@tonistiigi What is the git SHA for docker where you got this panic? Need that to checkout the right source

**Comment by tonistiigi** [comment]
@mrjana I got it while working on #25833 so 1b954973cc plus some swarmkit changes that shouldn't matter for trace but maybe matter for logic. It's very hard to reproduce, I was running init test in a loop for a very long time to debug another issue and only got it once so didn't try to reproduce on clean master.

**Comment by tonistiigi** [comment]
Happened again on https://jenkins.dockerproject.org/job/Docker%20Master%20(arm)/2997/console

**Comment by thaJeztah** [comment]
@tonistiigi is this still an issue? Do we have any clue on a solution?

**Comment by tonistiigi** [comment]
@thaJeztah Haven't noticed it this week but I'm not aware that this has been fixed.

**Comment by thaJeztah** [comment]
ping @icecrime this now gets into 1.13; or still needed for 1.12.2? (I see you removed it from the milestone)

**Comment by thaJeztah** [comment]
Added this back to the 1.12.2 milestone, per https://github.com/docker/docker/pull/26844#issuecomment-249132754
