### ISSUE TITLE
Feature Request: Go Formatting in Docker Info

### ISSUE THREAD

**Issue by DamionWaltermeyer** [docker/docker#25842]
Howdy. 

I think it would be super-awesome-neato-kean if docker info supported -f {{data stuff}}. 

Right now my use case is simply having a quick and easy way to check the number of stopped containers, and I'd like to do something like docker info -f {{.Containers.Stopped}}   rather than docker info |cut/awk/whatevs.  

Thanks.

**Comment by cpuguy83** [comment]
`docker ps --filter status=exited  -q | wc -l`?

**Comment by DamionWaltermeyer** [comment]
Yeah, I can do it, I mean the task I would use it for is already written and in use. I was just thinking long-term it might be nice to have everything following  the same formatting system to provide information.

**Comment by vdemeester** [comment]
@DamionWaltermeyer I'm pretty sure https://github.com/docker/docker/pull/23808 implements what you need — It will be available in 1.13.0 :wink: .

**Comment by DamionWaltermeyer** [comment]
So it will, my apologies, I didn't see it when I was searching earlier.    Thank you very much.
