### ISSUE TITLE
FEATURE REQUEST: Get container restart count

### ISSUE THREAD

**Issue by groyee** [docker/docker#25859]
You can configure a restart policy with docker which is nice. You can configure it for "always", or "on-failure"...

What is missing, for me at least, is to get the restart count. How many times did it actually performed the automatic restart.

When you come in the morning to the office, it would be nice to see the restart count for all of the containers. Otherwise you need to use some 3rd party tools to run next to your process and count the restarts.

Thanks!

**Comment by thaJeztah** [comment]
You can, using `--format`, e.g.:

```bash
docker inspect --format "ID: {{.ID}} RESTARTS: {{.RestartCount}} NAME: {{.Name}}" $(docker ps -aq)

ID: 02f31cb23b1b1a58d5fba69cd4e55a74316d56cb004194778e07c790dd84744b RESTARTS: 0 NAME: /gigantic_rosalind
ID: 03bdbe59667ad435d20adbbf8ad1502ee889a31d8ce3474cc49070eac2209075 RESTARTS: 0 NAME: /hopeful_jennings
ID: 62f181ed26c23705f05cbd5d6d2cb250dcd134ebd90c913b069e10159e078d2b RESTARTS: 0 NAME: /drunk_colden
ID: 9615b507c28ea36f5f90c81955a4ed3cccc08cb58097ea4c5a54391d02695b2a RESTARTS: 0 NAME: /naughty_hypatia
ID: 0d859339335f6a04391b0417e9bac51adcc046ea18f8a05f09b1e78ee1315b7d RESTARTS: 0 NAME: /high_heisenberg
ID: 0c01e47f9e75176190bdace4efc50028ca16705e0beb0f22130fb1487fbca77c RESTARTS: 0 NAME: /tender_brown
ID: 598fdb047e03345b5625fbc2056069317e90ef33a790fd5a4e67b05a8f83e04a RESTARTS: 0 NAME: /my-web.1.5rzc9cqcrpayczqjgc313hd3l
ID: 8b5f41a296994f016192cbaebb377141ef3bceb32996ee2f9f6558bbab1aa905 RESTARTS: 0 NAME: /my-web.1.98j56jj4r4qm5zmzkg5vq9un9
ID: af4b9ae99b7c4c5497fd65d380b97a6ba1f842e4cc4a8f183129fbdc78edad68 RESTARTS: 0 NAME: /my-web.1.9wuuri5zjdgseujw66rmknaj3
ID: 42baf32f35698123b41fba3289f58e73b4bbb4319c517c5dafc58c00a007726c RESTARTS: 0 NAME: /backstabbing_kare
```

**Comment by groyee** [comment]
Nice!

I didn't know that.

However it doesn't work after machine restarts. If you set your container to **_restart: always_** and reboot the machine the counter is 0.

Is it by design? is it a swarm issue?

**Comment by thaJeztah** [comment]
That's by design, the restart count is not written to disk. If you want to keep track of restarts, you could consider to use the events command for that to monitor restart events;

CLI:
https://docs.docker.com/engine/reference/commandline/events/

API:
https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/monitor-docker-s-events

**Comment by groyee** [comment]
Thanks You!

**Comment by thaJeztah** [comment]
No, it's just a counter. But if you develop something that uses the events-API to collect, you may be able to store those events somewhere for further analysing

**Comment by Saibamen** [comment]
@thaJeztah: Something is wrong with these stats.

I have this docker-compose config for `mongo-express` image:

```yml
    depends_on:
      - mongo
    deploy:
      restart_policy:
        condition: any
        delay: 60s
```

My container starts and can connect with Mongo DB within ~10 seconds, but in your command (`docker inspect --format "ID: {{.ID}} RESTARTS: {{.RestartCount}} NAME: {{.Name}}" $(docker ps -aq)`) output, I can see there were 6 restarts. This is impossible
