### ISSUE TITLE
Named volume changing ownership of the host folder

### ISSUE THREAD

**Issue by flx42** [docker/docker#25854]
**Output of `docker version`:**

```
Client:
 Version:      1.12.1

Server:
 Version:      1.12.1
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 87
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local nvidia-docker
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.16.0-77-generic
Operating System: Ubuntu 14.04.5 LTS
[...]
```
**Steps to reproduce the issue:**
- Create a named volume
```
$ docker volume create --name test
```
- chown the named volume to another user
```
$ VOLUME_PATH=/var/lib/docker/volumes/test/_data   
$ sudo chown -R $(id -u):$(id -g) ${VOLUME_PATH} 
$ sudo ls -l ${VOLUME_PATH}/..
drwxr-xr-x 2 fabecassis fabecassis 4096 Aug 18 16:31 _data
```

- Run a container with this name volume, mount to an **existing** folder in the container
```
$ docker run --volume=test:/usr/local:ro --rm ubuntu:14.04
$ sudo ls -l ${VOLUME_PATH}/..
drwxr-xr-x 10 root root 4096 Aug 18 16:31 _data
```
The host folder backing the volume changed ownership from `fabecassis` to `root`, just by running a container. The destination folder must be owned by root for the ownership to change (mounting to `/foo` won't work). 
Note that using `nocopy` works, the ownership on the host folder remains unchanged:
```
$ docker run --volume=test:/usr/local:ro,nocopy --rm ubuntu:14.04 
$ sudo ls -l ${VOLUME_PATH}/..
drwxr-xr-x 2 fabecassis fabecassis 4096 Aug 18 16:38 _data    
```

Is this the intended behavior?

This is a simple repro example that's why we manually change the ownership of the named volume. In [nvidia-docker](https://github.com/nvidia/nvidia-docker) we have a daemon acting as a volume plugin, the daemon is launched as user `nvidia-docker` and thus the volumes it's creating are also owned by `nvidia-docker`. When this bug occurs, the `nvidia-docker` daemon cannot remove its own volumes anymore because of insufficient permissions.

cc @3XX0 @cpuguy83 (author of the nocopy [commit](https://github.com/docker/docker/commit/b0ac69b67ef79c6c937f84bee3df20a1924ad334))

Thank you!

**Comment by cpuguy83** [comment]
Yes, this is the intended behavior.
Docker copies the contents/permissions from the container dir into the volume unless you specify `nocopy`.

**Comment by flx42** [comment]
@cpuguy83 thanks for confirming!

**Comment by flx42** [comment]
However, I would still like to point out that this behavior is highly surprising even after looking at the `nocopy` doc. It's surprising that the permissions are changed for the **host** folder, especially since it was mounted as `ro`.

Thanks

**Comment by cpuguy83** [comment]
@flx42 The host folder == the container folder.
`nocopy` makes it do nothing, otherwise it copies everything over.

`ro` has significance for container access to the dir, not the how the daemon manages it.
