### ISSUE TITLE
Docker crashed with fatal error: free list corrupted

### ISSUE THREAD

**Issue by primiano** [docker/docker#25856]
OS: Ubuntu 14.04
Running on bar metal Xeon E3-1245 with ECC ram

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 22
 Running: 20
 Paused: 0
 Stopped: 2
Images: 560
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 526
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-92-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.57 GiB
Name: hurricane.x25.link
ID: BAI5:6W2F:QCVS:SB2B:OWNA:WNTR:4MAD:JNN2:S5BF:KVNI:PUU7:N7LZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: primiano
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Xeon E3-1245 with ECC

**Steps to reproduce the issue:**
Today after several days of uptime I found all my containers stopped. This is quite unfortunate and undesirable. The first thing I saw in the dmesg is:

[544107.214408] init: docker main process (13622) terminated with status 2
[544107.215516] init: docker main process ended, respawning

Looks like dockerd crashed. See more in the attached docker.log.
There are two issues here:
1) why docker crashed?
2) why after respawning all my containers (which are managed by docker-compose) were left in a stopped state?

output of /var/log/upstart/docker.log:
runtime: free list of span 0x7ff2643750b0:
0xc8227e04d0 -> 0x202064616f6c4420 (BAD)
fatal error: free list corrupted

runtime stack:
runtime.throw(0x1e875f0, 0x13)
        /usr/local/go/src/runtime/panic.go:547 +0x90
runtime.(*mspan).sweep(0x7ff2643750b0, 0x350d00003500, 0x200001801)
        /usr/local/go/src/runtime/mgcsweep.go:201 +0x852
runtime.sweepone(0x449822)
        /usr/local/go/src/runtime/mgcsweep.go:112 +0x23e
runtime.gosweepone.func1()
        /usr/local/go/src/runtime/mgcsweep.go:124 +0x21
runtime.systemstack(0xc820018a00)
        /usr/local/go/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1051

[docker.log.txt](https://github.com/docker/docker/files/426089/docker.log.txt)

**Comment by thaJeztah** [comment]
ping @mlaventure PTAL!

**Comment by primiano** [comment]
This happened again after 24 hours, so is not just some random memory corruption. Attaching new docker.log.
I suspect this is has somehow something to do with the fact that recently I added HEALTHCHECK commands to my Dockerfile. Will try to remove them and see if it fixes the issue.

**Comment by mlaventure** [comment]
could you share the healthcheck command?

**Comment by primiano** [comment]
too late :/, I did rollback the health check changes. let's see if it fixes though. I also did a general apt and kernel  update recently, so there are quite some variables into play. 
still, the second issue concerns me. I can understand that dockerd can crash, sw bugs are unavoidable. but I don't understand why after being respawned all containers are in a stopped state. perhaps I am doing something wrong here configuration-wise? I could have a cron job which checks for that are restarts them but I feel docker should take care of this.

**Comment by mlaventure** [comment]
I had missed the mention of your second issue.

Were you re-doing a `docker-compose up` to respawn those containers?

**Comment by primiano** [comment]
On Aug 20, 2016 20:01, "Kenfe-Mickaël Laventure" <notifications@github.com>
wrote:
>
> I had missed the mention of your second issue.
>
> Were you re-doing a docker-compose up to respawn those containers?

yes, correct

**Comment by mlaventure** [comment]
@primiano does it work if you start them manually? Can you share the daemon logs from the `docker-compose up` onward once the daemon have been restarted?

**Comment by primiano** [comment]
Small update. Didn't have time to look into more details, but in the meantime I confirm that after removing the health checks everything resumed working without interruptions.
Will try to get logs for the other issue.

**Comment by thaJeztah** [comment]
@primiano any update since?

**Comment by primiano** [comment]
Sorry ended up being super busy. Didn't manage to look more into both issue, will try again next weekend.
In the meantime I confirm that disabling HEALTHCHECK solved the daemon crashing issue.

**Comment by thaJeztah** [comment]
I'll close this issue for now, but feel free to comment if you have more info

**Comment by geostant** [comment]
Hello guys,
I'm having the same issue (docker.io 1.12.3)

Added yesterday many healthchecks to my containers (I'm running 30+ containers on a single heavy lifting machine).

Today I came back to the office and found my docker daemon non responsive.

**Comment by thaJeztah** [comment]
@geostant would you be able to open a new issue with more information? (but add a link to this issue). Could you check if your machine possibly ran out of memory?

I see there's various issues in Golang reporting this error, e.g. https://github.com/golang/go/issues/13287 (and various issue linked from that), so wondering if it's something related to the Go runtime.
