### ISSUE TITLE
Add support for unified cgroups (cgroup2)

### ISSUE THREAD

**Issue by flokli** [docker/docker#25868]
`docker`/`libcontainerd` should also be able to run on a system with [`cgroup2`](https://lwn.net/Articles/679786/) enabled, which was declared production ready in kernel 4.5.

systemd v230 introduced support for it via the `systemd.unified_cgroup_hierarchy=1` cmdline. Recently, rkt [added support for cgroup2](https://github.com/coreos/rkt/pull/3032), too.

Docker currently [doesn't detect the `cgroup2` fstype](https://github.com/docker/docker/blob/master/vendor/src/github.com/vishvananda/netns/netns_linux.go#L103), and fails to run:

```
time="2016-08-19T09:04:47.328598164+02:00" level=warning msg="Your kernel does not support cgroup memory limit" 
time="2016-08-19T09:04:47.328607128+02:00" level=warning msg="Unable to find cpu cgroup in mounts"
time="2016-08-19T09:04:47.328612831+02:00" level=warning msg="Unable to find blkio cgroup in mounts"
time="2016-08-19T09:04:47.328617981+02:00" level=warning msg="Unable to find cpuset cgroup in mounts" 
time="2016-08-19T09:04:47.328635828+02:00" level=warning msg="mountpoint for pids not found"
time="2016-08-19T09:04:47.351633632+02:00" level=fatal msg="Error starting daemon: Devices cgroup isn't mounted"
```

It should also support running with the unified cgroup hierarchy, or at least detect `cgroup2` being used and raise a more meaningful error.

**Comment by justincormack** [comment]
cc @crosbymichael

**Comment by crosbymichael** [comment]
Not yet.  If you read the article the main reason why we don't support this yet is this:

`There are currently 12 cgroup controllers in cgroups v1`
`Currently, three cgroup controllers are available in cgroups v2`

We will wait until the implementation is finished before implementing v2.

**Comment by embano1** [comment]
@crosbymichael can you comment on the v2 implementation now that the CPU controller has been merged into the v4.15 Kernel?

**Comment by khs1994** [comment]
any update?

**Comment by AkihiroSuda** [comment]
we need runc to support cgroup2 first

**Comment by AkihiroSuda** [comment]
PR: https://github.com/moby/moby/pull/40174

**Comment by moooofly** [comment]
any update?

**Comment by dead10ck** [comment]
Should this be reopened now that runc's support has been merged?

**Comment by AkihiroSuda** [comment]
@dead10ck See https://github.com/moby/moby/issues/40360

**Comment by thaJeztah** [comment]
Let me lock the conversation on this one, in favour of https://github.com/moby/moby/issues/40360 (to prevent the conversation from diverging)
