### ISSUE TITLE
--ip=<ipaddr> gracefully accepts hostname but doesn't perform DNS lookup

### ISSUE THREAD

**Issue by mvsestito** [docker/docker#25863]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Output of `docker version`:**

Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

**Output of `docker info`:**

Containers: 31
 Running: 3
 Paused: 0
 Stopped: 28
Images: 173
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: vg--docker-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 87.72 GB
 Data Space Total: 399.7 GB
 Data Space Available: 312 GB
 Metadata Space Used: 20.87 MB
 Metadata Space Total: 1.002 GB
 Metadata Space Available: 981.6 MB
 Thin Pool Minimum Free Space: 39.97 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge macvlan overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.22.2.el7.x86_64
Operating System: Red Hat Enterprise Linux
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 125.6 GiB
ID: LUER:C2ZN:EIWN:YK5C:TY2L:AZEH:5JBV:FCCY:TRPK:EY2U:KVIB:ODZK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**

OS: RHEL 7.2
Kernel: Linux 3.10.0-327.22.2.el7.x86_64

Using the new MACVLAN driver

**Steps to reproduce the issue:**
1. Run docker run command with basic required arguments on some image and --net=<some configured docker network> --ip=<hostname>
2. Exec into container and run "ip addr" and validate that the eth0 interface takes the zero address of in the subnet rather than the expected DNS mapped IP

**Describe the results you received:**
Container starts gracefully without issue, yet cannot connect/communicate with container externally other than through docker daemon client. 

**Describe the results you expected:**
If the new MACVLAN driver support cannot accept a domain hostname as --ip parameter argument, should run validation on the given argument and return error upon invalid format.

**Comment by yongtang** [comment]
@mvsestito Created a pull request #25943 for this issue.
