### ISSUE TITLE
Container can't use env which set in dockerfile

### ISSUE THREAD

**Issue by richardweiu** [docker/docker#25862]
**Output of `docker version`:**

```
Docker version 1.11.0, build 4dc5990
```

**Steps to reproduce the issue:**
1. in my dockerfile `ENV JAVA_HOME /usr/lib/jvm/java-8-oracle `
2. docker build -t='xubuntu:test'
3. docker run -ti xubuntu:test
4. vncviewer this container
5. echo $JAVA_HOME

**Describe the results you received:**
It's null,I can't get env set in dockerfile

**Describe the results you expected:**
I want get the env in container.

I can get this just when I use `docker run -ti xubuntu:test /bin/bash` ,

but I want get this env just use `docker run -ti xubuntu:test` when ssh or vncviewer this container

**Comment by withinboredom** [comment]
Sounds like an issue with your software not bringing in the environment variables from the OS, and not an issue with Docker.

Sometimes, I have to start my scripts with `#!/usr/bin/env bash`

You may need to set your entrypoint/command prefixed with `/usr/bin/env`

**Comment by cpuguy83** [comment]
SSH is starting a new shell, new process, in the container. Environment variables will not be inherited in this case... to do so would be a security issue... and also is not related to docker.

Docker sets the environment variables of the process it starts. Its up to the process in the container to propagate those variables down to their own child processes.

Closing as this is not really a docker issue.
