### ISSUE TITLE
Not possible to add network to running service

### ISSUE THREAD

**Issue by sheerun** [docker/docker#25876]
Hey. As far as I can see, it's impossible to add/remove service from a network after it has been created.

**Output of `docker version`:**

```
Client:
 Version:      1.12.1-rc2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   236317f
 Built:        Wed Aug 17 05:29:30 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.1-rc2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   236317f
 Built:        Wed Aug 17 05:29:30 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Steps to reproduce the issue:**

1. `docker service service --network frontend --name nginx nginx`
2. `docker service create --network blog-network --name blog sheerun/blog`
3. `docker service update --network-add blog-network nginx`

So I create load balancer in "frontend" network, then a static website in "blog-network" network, and finally I'd like to connect load balancer with static website. Unfortunately docker doesn't support `--network-add` or `--network-rm` flags for service update. Are there any plans to support them?

I'm aware of `docker network connect`, but it only works for containers, not services.

**Comment by jhorwit2** [comment]
This feature has a dependency on swarmkit and is being tracked here https://github.com/docker/swarmkit/issues/1029
