### ISSUE TITLE
Swarm mode: getting Container ID from Task ID

### ISSUE THREAD

**Issue by yoshiokatsuneo** [docker/docker#25871]
I want to connect the container of a task, but "docker exec" requires container ID instead of Task ID.
But, I cannot find the way to get container ID from task ID.

Isn't there any method to get container ID from "swarm mode" task ID ?

**Comment by jhorwit2** [comment]
You can do `docker inspect -f "{{.Status.ContainerStatus.ContainerID}}" <task_id>`

**Comment by yoshiokatsuneo** [comment]
@jhorwit2 Ah, I see that "docker inspect" works even for TaskID. 
Thanks!

**Comment by thaJeztah** [comment]
looks like this question was answered (thanks again @jhorwit2), so I'll close this, but feel free to comment if there's anything left to address

**Comment by venkateshjayanaik** [comment]
Pertaining to same question, it indeed gives us the containerID however it's long string and when I tried to inspect it docker container inspect XXXXXWWWWWWWWWWWWWWW
It throws error "No such container"

The containerID we get when we run docker ps it's only 12 character string. I even to tried to extract first 12 and long 12 characters and inspected. It also didn't work. However my running
