### ISSUE TITLE
groups for user not reported correctly via id or /usr/bin/groups any more?

### ISSUE THREAD

**Issue by dejonghb** [docker/docker#25880]
**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 57
Server Version: 1.12.1
Storage Driver: btrfs
 Build Version: Btrfs v4.4
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null bridge host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-34-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.417 GiB
Name: bdj13
ID: Q4IX:7U2J:NCLS:DV5X:7UVX:GI2S:LXLE:ES2F:RVIG:JJHS:JTPK:WBBH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on physical host

**Steps to reproduce the issue:**
1. docker run -it --name grouptest ubuntu /bin/bash
2. useradd -m jenkins -G games,staff
3. in other terminal: docker exec -it -u jenkins grouptest /bin/bash -l
4. id (or /usr/bin/groups)

**Describe the results you received:**
```
$ id
uid=1000(jenkins) gid=1000(jenkins) groups=1000(jenkins)
```
```
$ /usr/bin/groups
jenkins
```

**Describe the results you expected:**
Expected jenkins to be reported as part of groups jenkins, staff and games
```
$ grep jenkins /etc/group 
staff:x:50:jenkins
games:x:60:jenkins
jenkins:x:1000:
```

**Additional information you deem important (e.g. issue happens only occasionally):**
Used to work with docker 1.10.x

**Comment by thaJeztah** [comment]
I can confirm that this changed in docker 1.11, and most likely relates to the switch to RunC / containerd.

FWIW, either using `id <username>` or `su <username>` _does_ show the additional groups;

```bash
root@fbab8d48a38a:/# id jenkins
uid=1000(jenkins) gid=1000(jenkins) groups=1000(jenkins),50(staff),60(games)

root@fbab8d48a38a:/# su jenkins
jenkins@fbab8d48a38a:/$ id
uid=1000(jenkins) gid=1000(jenkins) groups=1000(jenkins),50(staff),60(games)
```

ping @mlaventure @crosbymichael PTAL; was this an intentional change, something that can be addressed?

**Comment by thaJeztah** [comment]
And, thanks for a very clear report, and steps to reproduce @dejonghb 👍

**Comment by mlaventure** [comment]
`runc` is ignoring the `additionalGids` field for `exec` hence the regression.

**Comment by mlaventure** [comment]
This seemed to be fixed in `runc` master. I'll try to vendor it into `containerd`
