### ISSUE TITLE
Provide a way to specify inverse link relationships.

### ISSUE THREAD

**Issue by GaretJax** [docker/docker#2588]
In [my use case](https://groups.google.com/forum/?fromgroups#!topic/docker-user/A7FceSE6BaY), I need bidirectional communication between containers while setting -icc=false.

The newly introduced `-link` option allows to set a one-directional parent-child relationship between an already running container (the child) and the container being started (the parent). When starting the parent, I need to be able to tell docker that the child shall be able to access the parent as well. Clearly, service discovery through environment variables would not be possible in this case, but allowing network traffic should be enough.

I propose to add an additional option (in the form of `-invlink`, `-allow`, or similar) which takes a container ID/name and sets up a child-parent relationship.

Implementation wise, this would be the same as calling the [`Link.toggle`](https://github.com/dotcloud/docker/blob/23b3747945f49cdb41645fbf8442a2bdd30b7a77/links.go#L121) method with parent and child inverted.

**Comment by n3ziniuka5** [comment]
This is necessary for dockerizing zookeeper ensemble

**Comment by shykes** [comment]
Hi all, there is a sprint underway to upgrade the networking model of
Docker. Among other features it will allow for arbitrary grouping with
2-way discovery and connectivity. This is a collaborative effort with
various projects and companies in the Docker networking space: Socketplane,
Weave, Docknet, VMWare, Cisco etc.

It's still early but there's an IRC channel if you're interested in joining
the fun: #docker-network on Freenode.

**Comment by gdm85** [comment]
For the time being, until this feature is implemented in a proper/fancy way upstream (docker networking 2.0), you guys can maybe use two-ways stateful linking as I implemented it in docker-fw:

https://github.com/gdm85/docker-fw#two-ways-linking

**Comment by tegansnyder** [comment]
:+1:

**Comment by dwelch2344** [comment]
+1

**Comment by mucsi96** [comment]
+1

**Comment by mucsi96** [comment]
You can create bidirectional links using a custom tiny DNS server. So instead of this

    serviceb:
        image: username/serviceb

    servicea:
        image: username/servicea
        links:
            - serviceb

Try this

    dnsdock:
        image: tonistiigi/dnsdock
        volumes:
            - /var/run/docker.sock:/run/docker.sock
        ports:
            - 172.17.42.1:53:53/udp
    serviceb:
        image: username/serviceb
        dns: 172.17.42.1

    servicea:
        image: username/servicea
        dns: 172.17.42.1

You can access the services with: `<container-name>.<image-name>.docker` hostname.
You can check `<container-name>` and `<image-name>` after `docker-compose up` in dnsdock logs.

**Comment by cpuguy83** [comment]
Closing as this is now handled by the new service discovery added in #14051

**Comment by duglin** [comment]
@cpuguy83 do you see the container linking stuff going away eventually too?

**Comment by cpuguy83** [comment]
@duglin `--link` utilizes the new services backend.

**Comment by duglin** [comment]
@cpuguy83 excellent - I didn't realize that.  Very cool.

**Comment by saulshanabrook** [comment]
@duglin So with the new service discovery is it possible to do this in docker compose?

**Comment by sampeka** [comment]
Sorry to resurrect an old issue, its the top result on google at the moment. Did this feature ever make its way into a release? The pull referenced above has been merged but links are still one-directional.

**Comment by cpuguy83** [comment]
@sampeka links are unidirectional. For bi-direcitonal the containers must share a common network, then you can reach them by name, network alias, or even by link-alias (which is container-local).
