### ISSUE TITLE
network-manger-openvpn causes docker to not start

### ISSUE THREAD

**Issue by hoxflank** [docker/docker#25898]
**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Output of `docker info`:**

```
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
uname -a
Linux lapp1 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: e
   Active: failed (Result: exit-code) since Fri 2016-08-19 23:53:45 CDT; 3min 55
     Docs: https://docs.docker.com
  Process: 7147 ExecStart=/usr/bin/dockerd -H fd:// (code=exited, status=1/FAILU
 Main PID: 7147 (code=exited, status=1/FAILURE)

Aug 19 23:53:45 lapp1 dockerd[7147]: time="2016-08-19T23:53:45.010324083-05:00" 
Aug 19 23:53:45 lapp1 dockerd[7147]: time="2016-08-19T23:53:45.030916078-05:00" 
Aug 19 23:53:45 lapp1 dockerd[7147]: time="2016-08-19T23:53:45.031653373-05:00" 
Aug 19 23:53:45 lapp1 dockerd[7147]: time="2016-08-19T23:53:45.032869503-05:00" 
Aug 19 23:53:45 lapp1 dockerd[7147]: time="2016-08-19T23:53:45.042923252-05:00" 
Aug 19 23:53:45 lapp1 dockerd[7147]: time="2016-08-19T23:53:45.113139516-05:00" 
Aug 19 23:53:45 lapp1 systemd[1]: docker.service: Main process exited, code=exit
Aug 19 23:53:45 lapp1 systemd[1]: Failed to start Docker Application Container E
Aug 19 23:53:45 lapp1 systemd[1]: docker.service: Unit entered failed state.
Aug 19 23:53:45 lapp1 systemd[1]: docker.service: Failed with result 'exit-code'

docker ps 
An error occurred trying to connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json: read unix @->/var/run/docker.sock: read: connection reset by peer

**Steps to reproduce the issue:**
1. fresh ubuntu 16.04 install
2. install network-manager-openvpn
3. service docker start

**Describe the results you received:**
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.

**Describe the results you expected:**
docker service to start....

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment]
Can you provide the untruncated log?

**Comment by hoxflank** [comment]
I had tested this several times before opening the bug report. However, after rolling back to a previous snapshot and trying once again I am unable to repo.

I am guessing this could be closed until someone else can repo it.

**Comment by thaJeztah** [comment]
Thanks, I'll close this issue
