### ISSUE TITLE
Save of Windows image fails on base OS image layer.

### ISSUE THREAD

**Issue by swernli** [docker/docker#25893]
@jstarks @jhowardmsft @darrenstahlmsft 
This used to work, but now saving an image on Windows after the base image has been used to start and HYPER-V Container will result in the following error:
`Error response from daemon: file integrity checksum failed for "UtilityVM/Files/EFI/Microsoft/Boot/BCD"`
We need to add a work-around here to avoid hitting checksum failures on any UtilityVM related files.

**Comment by aneezhcl** [comment]
Dears,

We are hitting similar problem when we save windowsservercore image pulled from docker hub.
Kindly advise.

Microsoft Windows [Version 10.0.14300]
(c) 2016 Microsoft Corporation. All rights reserved.

PS C:\Windows\system32> docker images
REPOSITORY                                    TAG                 IMAGE ID            CREATED             SIZE
microsoft/mssql-server-2014-express-windows   latest              5488a4ca54e0        10 days ago         10.15 GB
microsoft/sqlite                              latest              ef6069342642        2 weeks ago         7.802 GB
microsoft/iis                                 latest              accd044753c1        2 weeks ago         7.907 GB
microsoft/windowsservercore                   latest              02cb7f65d61b        9 weeks ago         7.764 GB
microsoft/nanoserver                          latest              3a703c6e97a2        9 weeks ago         969.8 MB
nanoserver                                    10.0.14300.1016     ef2979e684a5        3 months ago        810.2 MB
windowsservercore                             10.0.14300.1000     025c71c4ad8a        4 months ago        9.344 GB
PS C:\Windows\system32>
c:\docker\images>docker save -o . microsoft/windowsservercore
Error response from daemon: file integrity checksum failed for "UtilityVM/Files/EFI/Microsoft/Boot/BCD"

**Comment by jueatgithub** [comment]
Ran into the same issue, this somehow becomes a blocking for my project hope there is a fix soon.

Thanks!

**Comment by uday31in** [comment]
Have the same issue with 1.13 and latest Windows build.

C:\share\DockerFiles\redis>docker push 192.168.51.11:5000/nano --disable-content-trust
The push refers to a repository [192.168.51.11:5000/nano]
f0a41dcdd53f: Pushing [==================================================>] 640.7 MB/640.7 MB
file integrity checksum failed for "UtilityVM/Files/EFI/Microsoft/Boot/BCD"

**Comment by PatrickLang** [comment]
Ping @jstarks - are you looking into this?

**Comment by arunbangalore** [comment]
Please can some one fix this.. its been 4 weeks since being reported..

**Comment by arunbangalore** [comment]
Thanks  fixed the issue of export the image but importing giving an error 

PS C:\Program Files\docker> docker import 'C:\Users\administrator.new\Downloads\wsc2.tar'  microsoft:windowsservercore
Error response from daemon: re-exec error: exit status 1: output: ProcessBaseLayer C:\ProgramData\docker\windowsfilter\b0da8d0fea2d9c6f5b44e6cc3b9761a51ceb5eee776d6d50ea5c6fc30a4c2b78: The system cannot find the path specified.

PS C:\Program Files\docker> docker import 'C:\Users\administrator.new\Downloads\wsc2.tar' - microsoft:windowsservercore

invalid reference format
PS C:\Program Files\docker>

Am I missing something here.. Appreciate any help..

**Comment by jhowardmsft** [comment]
Where does `wsc2.tar` come from?

**Comment by arunbangalore** [comment]
It's the file name provided during docker export of the windows server core
image to local path.

Thanks

**Comment by jhowardmsft** [comment]
Ah, my bad. I thought you were doing `docker save` and `docker load` rather than `docker export` followed by `docker import`. Docker export isn't supported on Windows - I'm going to submit a PR to explicitly block this.

**Comment by arunbangalore** [comment]
Well, This is a step backward if not being supported (Export/Import), Currently we are  trying to qualify support of Windows 2K16 containers on our storage arrays and unfortunately we happen to have all our test arrays and test hosts sitting in Secure Engg Environment with absolutely no access to internet.

In a situation like this we are left with no option rather that export and import of the WindowServerCore/Nano images using offline methods and there is no other way other
than export/import which can be used to update an docker image on systems with no internet access. 
This may not be a unique case and many people would want offline transfer of core images to multiple 
hosts and Export/import would be a needed feature. 

I would be happy if you could suggest any alternatives for the offline update of Windows container images to non internet connected hosts which would help me greatly to continue our effort of Windows containers qualification on our Storage Arrays.

Thanks

**Comment by jhowardmsft** [comment]
Yes that works.

**Comment by ManoMarks** [comment]
I still hit this issue today.

**Comment by jhowardmsft** [comment]
Are you running RTM 2016 with all Windows Updates applied and latest base images pulled? Docker version?

**Comment by ManoMarks** [comment]
I hit it in Windows 10, fully updated. Docker version 12.1.

**Comment by ManoMarks** [comment]
1.12.1

**Comment by friism** [comment]
@ManoMarks that's an old version. Please update Docker for Windows or your Docker Engine directly if you hand-installed it. Instructions here: https://github.com/docker/labs/blob/master/windows/windows-containers/Setup.md

**Comment by ManoMarks** [comment]
Sorry just got back to the computer I hit the problem on. This is the version info:
```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 05:27:08 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64
```
