### ISSUE TITLE
Error when mounting data volume for Postgres in docker for Windows

### ISSUE THREAD

**Issue by georgehdd** [docker/docker#25908]
**Output of `docker version`:**
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      linux/amd64

**Output of `docker info`:**
Containers: 18
 Running: 14
 Paused: 0
 Stopped: 4
Images: 18
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 197
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: YBND:ZW2A:53WU:5OWR:324D:FMZ6:ABRD:MFRY:LKFJ:APP7:PKUG:N52X
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://web-proxy.il.hpecorp.net:8080
Https Proxy: http://web-proxy.il.hpecorp.net:8080
Registry: https://index.docker.io/v1/
Insecure Registries:
 16.19.200.78:5000
 127.0.0.0/8

**Steps to reproduce the issue:**
1. Run postgres:9.5.2 image when mounting the following volume: **c:/temp/postgresql:/var/lib/postgresql/data**

**Describe the results you received:**
Postgres will not start and the following errors will be printed to console:
```
HINT:  The server must be started by the user that owns the data directory.
FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
```

**Describe the results you expected:**
Postgres should start and mount the correct windows directory as a data volume

**Comment by thaJeztah** [comment]
Thanks for reporting! Since this issue is specific to docker for Windows, could you open it in the Docker for Windows issue tracker instead? https://github.com/docker/for-win/issues

Before opening a new issue, please check if there's an existing issue already that you can subscribe to.

I'll close this issue here, but feel free to continue the discussion
