### ISSUE TITLE
letsEncrypt CA is an 'unknown authority' to Docker Trusted Registry

### ISSUE THREAD

**Issue by ezeeetm** [docker/docker#25910]
I obtained a full certchain, private key, etc. using LetsEncrypt.  When adding this cert to Docker Trusted Registry (Settings>Domain>Show TLS settings), and saving the configuration, a popup appears with the message:

`Unable to save settings: x509: certificate signed by unknown authority`

Where can we see the list of CA's that are considered 'known' by DTR?

**Comment by justincormack** [comment]
Can't really help you here as this is the issue tracker for the open source docker engine product, and the certificate config for DTR is not in this repo, you should contact the DTR support.

However it is likely you also need to add the intermediate certificate, as the new root cert is not yet in any CA list (it will be added by Mozilla soon, and then should arrive elsewhere as most people use the Mozilla certs). The certs are signed by an intermediary pending this so they work, and you may need to add that cert too.

I will close this, but feel free to continue discussion here if necessary.

**Comment by ezeeetm** [comment]
@justincormack thanks for the guidance.  The intermediate cert is included in the fullchain.pem, and was what I used when configuring DTR with the new cert.

I'll open an issue on DTR thanks!
