### ISSUE TITLE
docker run --permissive SELinux change to --privileged

### ISSUE THREAD

**Issue by WhisperingChaos** [docker/docker#25918]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 3.13.0-74-generic
Operating System: Alpine Linux v3.4 (containerized)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.704 GiB
Name: 2984dce9dd17
ID: DK5H:F7GU:NOI7:EQKM:4JQG:IXVD:Z2ZJ:5LRM:2CV7:DI5J:B7Y4:YY2V
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.  View [docker run reference - Security configuration](https://docs.docker.com/engine/reference/run/#/security-configuration)

**Describe the results you received:**
While reading ```docker run```'s SELinux _Security configuration_  section, noticed reference to ```--permissive``` flag as a method to disable SELinux enforcement for a particular container by Docker Engine.  Relevant passage:

 "_To disable the security labeling for this container versus running with the --permissive flag, use the following command:_"

However, ```docker run``` doesn't support ```--permissive``` flag, as it generates message: ```unknown flag: --permissive```.  Therefore, given the context, documentation should have instead cited ```--privileged``` option.

**Describe the results you expected:**
"_To disable the security labeling for this container versus running with the **--privileged** flag, use the following command:_"

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by justincormack** [comment]
Do you want to make a pull request to fix this?

**Comment by WhisperingChaos** [comment]
Sure.  I'll issue a pull request later tonight.

Can you add _doc_ label to this issue?  Thanks!
