### ISSUE TITLE
AuthZ plugins change headers

### ISSUE THREAD

**Issue by runcom** [docker/docker#25927]
**Output of `docker version`:**

```
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.6.3
 Git commit:   43640a8
 Built:        Mon Aug 22 17:26:03 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.6.3
 Git commit:   43640a8
 Built:        Mon Aug 22 17:26:03 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 28
 Running: 0
 Paused: 0
 Stopped: 28
Images: 88
Server Version: 1.13.0-dev
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: journald
Cgroup Driver: systemd
Plugins: 
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.6.6-300.fc24.x86_64
Operating System: Fedora 24 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.44 GiB
Name: localhost.localdomain
ID: 62I5:E7N5:VHP3:HEWA:7I2L:JLUR:JQV7:SDPV:GYHS:LFYI:QBIH:KRRV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 15
 Goroutines: 25
 System Time: 2016-08-22T17:28:48.882005417+02:00
 EventsListeners: 0
Username: runcom
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 localhost
 172.30.0.0/16
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical/cloud

**Steps to reproduce the issue:**
1. start the docker daemon with an authorization plugin (e.g. https://github.com/projectatomic/docker-novolume-plugin even if every plugin which just reply with _allow_ will raise the issue) and also have the daemon listen on localhost to be curl'ed
2. `curl -vvv http://localhost:8081/images/json` or `curl -vvv http://localhost:8081/containers/json`
3.

**Describe the results you received:**
```
$ curl -vvv http://localhost:8081/images/json
*   Trying ::1...
* connect to ::1 port 8081 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8081 (#0)
> GET /images/json HTTP/1.1
> Host: localhost:8081
> User-Agent: curl/7.47.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Mon, 22 Aug 2016 15:27:56 GMT
< Content-Type: text/plain; charset=utf-8
< Transfer-Encoding: chunked
< 
[API output here truncated]
```

**Describe the results you expected:**
```
$ curl -vvv http://localhost:8081/images/json

*   Trying ::1...
* connect to ::1 port 8081 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8081 (#0)
> GET /images/json HTTP/1.1
> Host: localhost:8081
> User-Agent: curl/7.47.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< Server: Docker/1.13.0-dev (linux)
< Date: Mon, 22 Aug 2016 15:27:22 GMT
< Transfer-Encoding: chunked
< 
[API output truncated]
```

**Additional information you deem important (e.g. issue happens only occasionally):**

You can see from the above that headers changed when using/not using an authz plugin. Specifically for instance the `Content-Type` header was `application/json` w/o the plugin enabled (which is correct) while it was `text/plain; charset=utf-8` when using the plugin.

/cc @estesp @liron-l

**Comment by runcom** [comment]
This is happening from docker 1.10.3 when authz plugins were firstly introduced also

**Comment by yongtang** [comment]
@runcom It seems that the issue is because `WriteHeader` is invoked before the headers have been copied:
https://github.com/docker/docker/blob/v1.12.1/pkg/authorization/response.go#L178-L189

Just created a pull request #25965 to try to fix it. Please let me know if there are any issues.
