### ISSUE TITLE
Docker Swarm Service - Set CMD per service?

### ISSUE THREAD

**Issue by sblackstone** [docker/docker#25926]
I've been trying to determine if its possible to set a cmd  explicitly for a service in docker swarm mode..

My use case is a Rails app where I'll need several different kinds of processes but they are all basically on the same image - 

e.g..

- Puma
- Clockwork
- Delayed Job

It seems messy to have to create multiple images where the only difference is the CMD.

I suppose I could hack it so I run a generic script that looks for env. variables to decide what to run but again, seems messy..

I don't see anything covering this in docker service create --help...

Thanks
Stephen

**Comment by cpuguy83** [comment]
`docker service create [opts] my/image <cmd>`
Pretty much just like `docker run`
