### ISSUE TITLE
dockerd high memory and cpu usage

### ISSUE THREAD

**Issue by joshgarnett** [docker/docker#25924]
9 days ago I spun up a new set of servers (t2.medium) for running Docker 1.12 in AWS utilizing ECS.  This morning I woke up to low swap alerts and discovered that dockerd was using up to 475MB of resident memory and using over 100% of CPU.  I did not encounter this issue with the latest Docker 1.11 version.  

Docker Version:

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:
 OS/Arch:      linux/amd64
```

Docker Info:

```
Containers: 10
 Running: 10
 Paused: 0
 Stopped: 0
Images: 8
Server Version: 1.12.0
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay null bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.7.0-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.858 GiB
Name: <redacted>
ID: <redacted>
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 <redacted>:5000
 127.0.0.0/8
```

**Comment by cpuguy83** [comment]
Can you give some insight on what is running on these servers? What is docker doing? Can you send `SIGUSR1` to dockerd and grab the stack trace from the log output?
Can you enable debug mode and attach pprof to it to grab some CPU/memory stats from the daemon?

**Comment by joshgarnett** [comment]
Stack trace is at https://gist.github.com/joshgarnett/f7abd7c3f10fa8f2bef4a69c5663900c sorry for the formatting.  Not sure how to make journalctl behave better for the long lines.

At the time docker should mainly have just been idle.  We were all away for the weekend.  Container wise its running the Amazon ECS Agent, Consul, Registrator, and some redis and java processes.

**Comment by cpuguy83** [comment]
From the stack trace, it looks like there are lots of calls to the stats API.
This is pretty well known to cause high CPU usage. See #21837

If you stop the stats collection does utilization go down?

**Comment by joshgarnett** [comment]
Strange that I wasn't seeing this behavior in Docker 1.11 with a similar stack.  Is there a way to disable stats collection without restarting docker?

**Comment by cpuguy83** [comment]
Stats are only collected when a user asks for them, via the API.
You'd have to terminate the API clients connected to the stats endpoints.

**Comment by cpuguy83** [comment]
Could be as simple as a single person running `docker stats` with no arguments.

**Comment by joshgarnett** [comment]
My first guess was that it was datadog.  I stopped that and observed no difference.  As a hunch, I also went ahead and stopped the ECS agent.  I immediately saw a drop in CPU. As part of the upgrade to Docker 1.12 I had also upgraded the ECS Agent from version 1.9 to 1.11.1.  It appears that in 1.10 they switched their metrics collection over to use docker stats.  https://github.com/aws/amazon-ecs-agent/blob/master/CHANGELOG.md

Any recommendations on how I should move forward?

**Comment by cpuguy83** [comment]
We're working on fixing the stats endpoint, which got particularly bad in 1.11+ because of the way stats are getting collected from runc.

I'm going to go ahead and close this since it looks like it's a dup of the stats issue.

**Comment by cpuguy83** [comment]
Maybe setting `ECS_DISABLE_METRIC=true` on the ECS agent will help.

**Comment by joshgarnett** [comment]
Yeah, I saw that.  I'm also going to open up an issue with them to flag the issue.
