### ISSUE TITLE
Docker for Mac nginx example doesn't run

### ISSUE THREAD

**Issue by zharvey-welltok** [docker/docker#25928]
I posted this on StackOverflow but doesn't appear to have a known solution/workaround:

http://stackoverflow.com/questions/39082936/docker-for-mac-nginx-example-doesnt-run

**Comment by mikegcoleman** [comment]
Cutting and pasting your command line works fine on my mac. 

Are there any firewalls running on your local machine?

**Comment by justincormack** [comment]
Works fine for me too. Does `docker logs webserver` show anything?

There is support for Docker for Mac at https://github.com/docker/for-mac

**Comment by zharvey-welltok** [comment]
@mikegcoleman - no firewall

@justincormack - no, there is no output when I run your command
