### ISSUE TITLE
Cannot build NGINX Amplify image with Docker for Mac

### ISSUE THREAD

**Issue by arun-gupta** [docker/docker#25938]
Trying to build nginx-amplify image as explained at:

https://github.com/nginxinc/docker-nginx-amplify#21-building-an-amplify-enabled-image-with-nginx

The image builds fine with `1.12.1-rc1-beta23 (build: 11375)` but breaks with `Mac 1.12.0-a (build 11213)`. Seems like Internet is not accessible with Docker for Mac and thus `apt-get` fails.

More details at: https://github.com/nginxinc/docker-nginx-amplify/issues/6

**Comment by justincormack** [comment]
Works fine for me on both the beta and stable release.

Are you behind a proxy? There may be some improvements in that area in the beta possibly.

You may be able to get more help debugging connectivity in the dedicated issue tracker https://github.com/docker/for-mac/issues

**Comment by arun-gupta** [comment]
@justincormack I've had both Beta and Stable release installed at the same time. Beta release was shutdown and Stable release was started , and vice versa. And seems like that is not a recommended option. Likely some global state is messed up because of that.

Will close the issue here and open up again after a clean install.
