### ISSUE TITLE
docker start returns wrong exit code when stdin is from a pipe.

### ISSUE THREAD

**Issue by easeway** [docker/docker#25936]
**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 14
 Running: 0
 Paused: 0
 Stopped: 14
Images: 416
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 489
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-30-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.58 GiB
Name: macubuntu
ID: J62H:VLMH:SYMV:VCB5:XIW2:OHB2:N4JZ:2AUK:MISE:6L3J:B36R:Y5ZW
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Username: easeway
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Steps to reproduce the issue:**
1. `docker create -it --name=test --entrypoint=/bin/false centos:7`
2. `echo "" | docker start -a -i test`
3. `echo $?`

**Describe the results you received:**

```
0
```

**Describe the results you expected:**

```
1
```

As `echo "" | /bin/false` emits exit code `1`

**Additional information you deem important (e.g. issue happens only occasionally):**

constantly reproducible.

**Comment by justincormack** [comment]
This works for me if I do not put the `-it` on the `docker create`. Not sure there is a logic to that but there might be...

**Comment by mohmost12** [comment]
This works for me with version 1.13.0 with the expected result (1)

**Comment by lewisdaly** [comment]
I'm also getting the expected result `1` with 1.13.0
on boot2docker using virtualbox, and Ubuntu 16.0.4 (on virtualbox)

**Comment by thaJeztah** [comment]
Looks like this was resolved, so let me close this, but comment if you still see this on 1.13 or above
