### ISSUE TITLE
Update swarm to Docker 1.12

### ISSUE THREAD

**Issue by vingrad** [docker/docker#25937]
What is the best way to update swarm to the new docker version 1.12 with swarm mode?

**Comment by arun-gupta** [comment]
AFAIK, manual upgrade is not possible. You can use https://github.com/docker/labs/blob/master/swarm-mode/quickstart/buildswarm-vbox.sh to start a cluster of Docker engines with swarm mode enabled.

**Comment by justincormack** [comment]
Unfortunately it is a complete reimplementation, so there is no easy upgrade from one to the other, although you can keep running the old swarm on new Docker versions.

**Comment by thaJeztah** [comment]
I think this question is answered, so I close this issue, but feel free to continue the discussion
