### ISSUE TITLE
Cann not start docker.service

### ISSUE THREAD

**Issue by dingxing123** [docker/docker#25942]
hi
I cloned a host. When I want to add this host to the swarm cluster, the prompt "duplicated ID".
So I deleted the clone of the host on the file (/etc/docker/key.json),
When I restart service docker again, I can't start, prompted the following error:
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Mon 2016-08-22 22:26:50 CDT; 6s ago
     Docs: http://docs.docker.com
  Process: 3110 ExecStart=/bin/sh -c /usr/bin/docker daemon $OPTIONS            $DOCKER_STORAGE_OPTIONS            $DOCKER_NETWORK_OPTIONS            $ADD_REGISTRY            $BLOCK_REGISTRY            $INSECURE_REGISTRY            2>&1 | /usr/bin/forward-journald -tag docker (code=exited, status=0/SUCCESS)
 Main PID: 3110 (code=exited, status=0/SUCCESS)

Aug 22 22:26:50 ip-172-32-65-2 forward-journal[3112]: time="2016-08-22T22:26:50.090069822-05:00" level=warning msg="open /sys/fs/cgroup/freezer/system.slice/docker-61ff59925dc74b570c3533a9c0c47a281d3bb8ba5bd36d21bb32c3f91d9bec7a.scope/freezer.st... file or directory"
Aug 22 22:26:50 ip-172-32-65-2 forward-journal[3112]: time="2016-08-22T22:26:50.090427732-05:00" level=warning msg="open /sys/fs/cgroup/freezer/system.slice/docker-61ff59925dc74b570c3533a9c0c47a281d3bb8ba5bd36d21bb32c3f91d9bec7a.scope/freezer.st... file or directory"
Aug 22 22:26:50 ip-172-32-65-2 forward-journal[3112]: time="2016-08-22T22:26:50.225865984-05:00" level=warning msg="failed to cleanup ipc mounts:\nfailed to umount /var/lib/docker/containers/61ff59925dc74b570c3533a9c0c47a281d3bb8ba5bd36d21bb32c3f91d9bec7a/shm: inv...
Aug 22 22:26:50 ip-172-32-65-2 forward-journal[3112]: time="2016-08-22T22:26:50.225913247-05:00" level=error msg="Error unmounting device 61ff59925dc74b570c3533a9c0c47a281d3bb8ba5bd36d21bb32c3f91d9bec7a: UnmountDevice: device not-mounted id 61ff...21bb32c3f91d9bec7a"
Aug 22 22:26:50 ip-172-32-65-2 forward-journal[3112]: time="2016-08-22T22:26:50.226040561-05:00" level=error msg="Failed to start container 61ff59925dc74b570c3533a9c0c47a281d3bb8ba5bd36d21bb32c3f91d9bec7a: [8] System error: not a directory"
Aug 22 22:26:50 ip-172-32-65-2 forward-journal[3112]: 
Aug 22 22:26:50 ip-172-32-65-2 forward-journal[3112]: time="2016-08-22T22:26:50.226076150-05:00" level=info msg="Loading containers: done."
Aug 22 22:26:50 ip-172-32-65-2 forward-journal[3112]: time="2016-08-22T22:26:50.226096545-05:00" level=warning msg="/!\\ DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING /!\\"
Aug 22 22:26:50 ip-172-32-65-2 forward-journal[3112]: time="2016-08-22T22:26:50.226189816-05:00" level=fatal msg="is a directory"
Aug 22 22:26:50 ip-172-32-65-2 systemd[1]: Started Docker Application Container Engine.

**Comment by ehazlett** [comment]
@dingxing123 can you report the Host OS and output from `docker version` and `docker info`?  Thanks

**Comment by dingxing123** [comment]
@ehazlett 
sure , Here are some of the information you need!

OS version 
CentOS Linux 7

$docker version
Client:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-25.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      78ee77d/1.9.1
 Built:           
 OS/Arch:         linux/amd64

Server:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-25.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      78ee77d/1.9.1
 Built:           

$docker info
Containers: 3
Images: 52
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-253:0-201326723-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.61 GB
 Data Space Total: 107.4 GB
 Data Space Available: 52.02 GB
 Metadata Space Used: 3.277 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-327.10.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 4
Total Memory: 29.55 GiB
Name: ip-172-32-65-2.ap-southeast-1.compute.internal
ID: FUXY:TY7I:CVAO:3MBA:JKTV:MFTW:ZKEM:JXFW:IVRN:S3M7:N5SM:JCUJ
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

**Comment by ehazlett** [comment]
Thx.  This looks similar to https://github.com/docker/docker/issues/22923.  Looks like they tried 1.11 with success.

**Comment by dingxing123** [comment]
thx for your help! @ehazlett 
I fix my problem by the ffollow step:
1. sudo yum update docker
2. sudo systemctl start docker
    then you will see the error logs : [msg="**can't create unix socket /var/run/docker.sock: is a directory**"]
[centos@ip-172-32-65-3 ~]$ sudo systemctl start docker
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
[centos@ip-172-32-65-3 ~]$ systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2016-09-20 15:56:46 SGT; 13s ago
     Docs: http://docs.docker.com
  Process: 2333 ExecStart=/usr/bin/docker-current daemon --exec-opt native.cgroupdriver=systemd $OPTIONS $DOCKER_STORAGE_OPTIONS $DOCKER_NETWORK_OPTIONS $ADD_REGISTRY $BLOCK_REGISTRY $INSECURE_REGISTRY (code=exited, status=1/FAILURE)
 Main PID: 2333 (code=exited, status=1/FAILURE)

Sep 20 15:56:46 ip-172-32-65-3.ap-southeast-1.compute.internal systemd[1]: Starting Docker Application Container Engine...
Sep 20 15:56:46 ip-172-32-65-3.ap-southeast-1.compute.internal docker-current[2333]: time="2016-09-20T15:56:46.238925220+08:00" level=warning msg="/!\\ DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING /!\\"
Sep 20 15:56:46 ip-172-32-65-3.ap-southeast-1.compute.internal docker-current[2333]: time="2016-09-20T15:56:46.239116239+08:00" level=fatal msg="**can't create unix socket /var/run/docker.sock: is a directory**"
Sep 20 15:56:46 ip-172-32-65-3.ap-southeast-1.compute.internal systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Sep 20 15:56:46 ip-172-32-65-3.ap-southeast-1.compute.internal systemd[1]: Failed to start Docker Application Container Engine.
Sep 20 15:56:46 ip-172-32-65-3.ap-southeast-1.compute.internal systemd[1]: Unit docker.service entered failed state.
Sep 20 15:56:46 ip-172-32-65-3.ap-southeast-1.compute.internal systemd[1]: docker.service failed.

3. sudo rm -rf /var/lib/docker.sock
4. sudo systemctl start docker
At latest the problem fixed.

**Comment by thaJeztah** [comment]
Based on this error;

    can't create unix socket /var/run/docker.sock: is a directory

I wonder if you have / had a container that bind-mounted `/var/run/docker.sock`. If `/var/run/docker.sock` does not exist (on the host), and you're using bind-mounts, then docker creates a *directory* with that name on that location, possibly leading to the issue you had.

However, I don't think there's a bug here that needs to be fixed, so I'll close this issue, but feel free to comment if you think there's something that needs to be fixed
