### ISSUE TITLE
docker service create --publish port doesn't work

### ISSUE THREAD

**Issue by liuxiaopiao** [docker/docker#25944]
**Output of `docker version`:**

docker --version
Docker version 1.12.1, build 23cf638

**Output of `docker info`:**
docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.12.1
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: active
 NodeID: 4xyd1161veq298d0ux4stzkhn
 Is Manager: true
 ClusterID: 2fapb4tk4ujxb9k0kw8opw3w3
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.245.251.124
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.1.12-37.5.1.el7uek.x86_64
Operating System: Oracle Linux Server 7.0
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 16.97 GiB
Name: h2
ID: OFJZ:3THB:ZM76:5D4P:WLJG:D74G:COYF:B4NB:E37Q:MXAV:ZZGR:6S7X
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
**Additional environment details (AWS, VirtualBox, physical, etc.):**
uname -a
Linux slc09woz.us.oracle.com 4.1.12-37.5.1.el7uek.x86_64 #2 SMP Thu Jun 9 16:01:20 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux

**Steps to reproduce the issue:**
1.  Create docker swarm env by "docker swarm init"
2.  Create docker service by "docker service create --replicas 1 --name hello --publish 32767:22 baseImage /run/service.sh"
3.  Use "docker ps " to check the container id.
docker ps
CONTAINER ID        IMAGE                                                         COMMAND             CREATED             STATUS              PORTS               NAMES
6c9787c8e387        baseImage:latest   "/run/service.sh"   5 minutes ago       Up 5 minutes        22/tcp              hello.1.4brqsa4vysbn2icthdh4eew43

4.  Check the ports mapping status:
docker inspect 6c9787c8e387 
       "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "b4ac650dd52ca109b4a1ce4a22842a95aeba7e5084e3299d8ba441345786c39c",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "22/tcp": null
            },

**Describe the results you received:**
No ports have been mapped.

**Describe the results you expected:**
Like using "docker run -p 22" command, would like to see something like:
 "Ports": {
                "22/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "32768"
                    }
                ]

**Comment by capkurmagati** [comment]
`docker service` use `ingress` as default networking other than `bridge`.
So you should use `docker service inspect  --format {{.Endpoint.Ports}} hello` to check if ports are mapped correctly.

**Comment by liuxiaopiao** [comment]
Thanks @capkurmagati. I got the mapped port with your suggestion:
22->30000. 
Thank you so much for the help
