### ISSUE TITLE
Uninstallation program frozen 

### ISSUE THREAD

**Issue by hanbaobao2005** [docker/docker#25968]
I searched the keyword 'Uninstallation', no related item pop up, so I decide to report a new issue.

**Output of `docker version`:**

```
1.12.1.6433 
1.12.1-rc1-beta23
Docker windows
```
![image](https://cloud.githubusercontent.com/assets/1937472/17921071/a8e50330-6a0a-11e6-8bc1-1bf0996f0690.png)

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
OS: windows 10 Pro Version 1511
OS Build : 10586.545

**Steps to reproduce the issue:**
1. Uninstall Docker

**Describe the results you received:**
The program froze here:
![image](https://cloud.githubusercontent.com/assets/1937472/17920984/2ed80cae-6a0a-11e6-9014-58eb92fc32b3.png)

I guess something wrong when it trying to stop its service
![image](https://cloud.githubusercontent.com/assets/1937472/17920998/4ca007dc-6a0a-11e6-8f90-7c8efb3b9f65.png)

**Describe the results you expected:**
Docker can be uninstalled smoothly

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by justincormack** [comment]
Can you open this issue here https://github.com/docker/for-win/issues as you will get help fater as it is specific to Docker for Windows.

**Comment by hanbaobao2005** [comment]
@justincormack I opened an new issue and the link is https://github.com/docker/for-win/issues/60
