### ISSUE TITLE
Support IPC using named pipes between docker daemon and containers.

### ISSUE THREAD

**Issue by anusha-ragunathan** [docker/docker#25961]
There are cases where the docker daemon needs to communicate with containers without relying on the network stack. 

Plugins are a good example. In the new plugin model, the docker daemon communicates with the plugin using the plugin APIs (volume, network, etc) over some IPC. On Linux, this is a unix socket whose path (eg. /var/lib/docker/plugins/<pluginID>) is bind mounted into the plugin during start. The socket is created in this directory by the plugin. The daemon and the plugin then communicate over this socket.

On Windows, since Windows sockets and named pipes are not part of the filesystem, bind mounting approach does not work. 

A recent discussion with Microsoft revealed that this can be fixed in the next platform release of Windows 2016. Assigning to John Howard, so he can re-assign appropriately.

**Comment by anusha-ragunathan** [comment]
cc @friism @tiborvass

**Comment by jhowardmsft** [comment]
This is not in scope for RS1. Closing.

**Comment by friism** [comment]
@jhowardmsft does it make sense to have an issue tracking progress and design though? cc @jstarks

**Comment by jhowardmsft** [comment]
If a sensible design can be determined. At present, no.

**Comment by jhowardmsft** [comment]
I don't think it makes sense to track Windows platform changes (not that I believe it is currently being considered) on GitHub
