### ISSUE TITLE
[Docker for Mac] Mounted volume permissions changing within the container

### ISSUE THREAD

**Issue by stouf** [docker/docker#25970]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 8
 Running: 7
 Paused: 0
 Stopped: 1
Images: 16
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 45
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay bridge null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.954 GiB
Name: moby
ID: FDX4:PNI2:FZG6:Q35O:M3ZQ:KOMS:VWFV:Q6YC:MQC7:QQGQ:NBCX:LLZU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 48
 Goroutines: 76
 System Time: 2016-08-24T07:29:44.709547188Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

- Docker for Mac
- Mac OS 10.11.16

**Steps to reproduce the issue:**

1. Run a linux container (I used
   [this version of ArchLinux](https://hub.docker.com/r/base/archlinux/)) in interactive mode,
   mounting any directory of the host system on `/data` in the container
2. From within the container, as the root user, run `ls -l /data`
3. Create a user `testuser` and log in as `testuser` (using `su testuser` or through the
   `docker exec -it ${CONTAINER_ID} bash` command from an external terminal for example)
4. Run `ls -l /data`.

**Describe the results you received:**

- In 2, I can see the following:

   ```
   [root@4056e30a9b07 data]# ls -l
   total 1
   -rw------- 1 root root 10 Aug 24 02:56 db.txt
   ```

- In 4, the permissions of the same file change

  ```
   [testuser@4056e30a9b07 data]$ ls -l
   total 1
   -rw------- 1 testuser testuser 10 Aug 24 02:56 db.txt
  ```

**Describe the results you expected:**

- I expect the file permissions **not** to change to match the user I'm logged in with.

**Additional information you deem important (e.g. issue happens only occasionally):**

- The issue doesn't occur on an Ubuntu 16.04 server with Docker 1.12

**Comment by justincormack** [comment]
This is intended, as otherwise containers would not be able to access files
on the Mac as there is no root access, and nothing would match the osx uid.
In future it will become more configurable.

Is it causing problems, other than being unexpected?

**Comment by stouf** [comment]
> not be able to access files on the Mac as there is no root access, and nothing would match the osx uid.

Ok, I see. I unfortunately don't have a deep knowledge of how all of this work on Mac OS systems, so I'm just going to take your words :)

> Is it causing problems, other than being unexpected?

Nop Sir! Thanks for replying :)

**Comment by justincormack** [comment]
Ok, I will close this now. We will try to document this more so it is less confusing...
