### ISSUE TITLE
Changing Cpu/Memory settings casues settings to crash (Mac)

### ISSUE THREAD

**Issue by piotrb** [docker/docker#25971]
**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 36
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 314
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.19-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.953 GiB
Name: moby
ID: LEWH:Y42Z:OEE6:XIFD:YHMH:RFTJ:YS6N:RGIY:7FIY:UO7G:SVTW:YTFI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 27
 System Time: 2016-08-24T08:10:58.522947886Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: piotrb
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker for Mac Beta 24

**Steps to reproduce the issue:**
1. Switch Memory/Cpu settings (I switches from 4 cores, 2Gigs to 8 cores, 4 gigs)
2. Click Apply & Restart

**Describe the results you received:**
Getting:

```
Failed to retrieve settings values.

failed to get memory setting
```

Error when opening the settings window.
Clicking Ok on the popup page closes the settings window

**Describe the results you expected:**

it to open the settings page

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by justincormack** [comment]
Can you report this on https://github.com/docker/for-mac as it is
specifically related to the osx version, you will get help faster. Thanks.

**Comment by piotrb** [comment]
Ah .. got it .. didn't notice the `for_mac` repo

Now is: https://github.com/docker/for-mac/issues/411

Closing this one
