### ISSUE TITLE
Windows Credential Manager support broken

### ISSUE THREAD

**Issue by oliversalzburg** [docker/docker#25972]
Something about your implementation for Windows Credential Manager is broken. I already reported the issue at https://github.com/docker/docker-credential-helpers/issues/22 but got no response.

**Comment by friism** [comment]
I think this is a duplicate of these issues:

 * https://github.com/docker/docker/issues/22910
 * https://github.com/docker/docker/issues/24968

**Comment by oliversalzburg** [comment]
@friism Yeah, looks like it.
