### ISSUE TITLE
docker containers' stats through UNIX socket not showing

### ISSUE THREAD

**Issue by sandeepvaday** [docker/docker#25984]
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4a6e2b1
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4a6e2b1
 Built:        
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.7.0-coreos
Operating System: CoreOS 1122.1.0 (MoreOS)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.801 GiB
Name: localhost
ID: Z6DG:PZYS:QGVO:XSD4:QE6I:MGPX:KZJ2:2T5S:A2R3:Z5I3:Y6BL:JNE2
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

The docker host is a VMware VM.

**Steps to reproduce the issue:**
1. Start a container and mount /var/run/docker.sock
2. Query for: echo -ne "GET /containers/$CONTAINERID/stats HTTP/1.1\r\n\r\n" | ncat -U /var/run/docker.sock (with root privileges)

**Describe the results you received:**
For any container that I query (including the one where I run the above mentioned cmd from), I get the following HTTP response
--------------
HTTP/1.1 200 OK
Server: Docker/1.11.2 (linux)
Date: Wed, 24 Aug 2016 15:40:54 GMT
Content-Type: text/plain; charset=utf-8
Transfer-Encoding: chunked

0
--------------
**Describe the results you expected:**

With docker version 1.6.x, seems like the API call over UNIX socket returns the JSON output of CPU/MEM usage. But not with vers > 1.6

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment]
It's because of the chunked transfer encoding.
Netcat is getting a response immediately.
Try using curl instead.
