### ISSUE TITLE
Swarm mode with task status 'rejected', is there a way find out why a task was rejected by agent?

### ISSUE THREAD

**Issue by cmingxu** [docker/docker#26004]
Docker report tasks of a service with status 'rejected',  how could I find out the reason why my task entered this state? Thanks

**Comment by cpuguy83** [comment]
@cmingxu `docker service ps --no-trunc <service>`
And/or
`docker inspect <task id>`

**Comment by BlaM** [comment]
`docker service ps --no-trunc <service>` returns "unknown flag --no-trunc". Has it been removed in docker 1.12?

**Comment by thaJeztah** [comment]
the `--no-trunc` was added in docker 1.13; for docker 1.12, use the `docker inspect` approach

**Comment by Bir121** [comment]
docker service task is "rejected",how o find this error

**Comment by summer-father** [comment]
me too, how to solve ?

**Comment by summer-father** [comment]
version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
