### ISSUE TITLE
overlay netwok multiple host can't link through ping 

### ISSUE THREAD

**Issue by yqguodataman** [docker/docker#26001]
docker network create -d overlay --subnet 10.20.0.0/16 --gateway 10.20.0.1 testover

I create a myself overlay network, and launch a service consists two tasks,and the two task on different hosts.Unable to connect to another in a container by ping the address of a container.
Use default network ingress is succeed.
Is this a bug?

**Comment by ehazlett** [comment]
I'm unable to reproduce this on 1.12.1.  Can you provide more system info like Docker version and Docker info?

**Comment by thaJeztah** [comment]
Closing because we were unable to reproduce, and need more information, but happy to reopen once that's provided
