### ISSUE TITLE
How can start/up container from other container

### ISSUE THREAD

**Issue by info2000** [docker/docker#26002]
i'm looking how start container from other container.
My need is that a container is checking some kpi in real time, and if need, start new instances of a container and do some commands.
I'm doing it in php
I can do it from host installing nginx-php, but i want do it from a container to had more clean the host and architecture.
Thanks

P.D: It's not an issue, but in google not found any related to this

**Comment by AkihiroSuda** [comment]
You can mount the Docker socket to achieve that (`-v /var/run/docker.sock:/var/run/docker.sock`).
(Note that it can be dangerous)
