### ISSUE TITLE
Add a new service mode to restrict in which nodes to run

### ISSUE THREAD

**Issue by manast** [docker/docker#26007]
There are some use cases where it would be quite useful to restrict on which nodes a certain service is allowed to run. I do not think this is possible today (as version 1.12.1 of docker). 
One case for example is if you want to share a swarm with different front-end services, every front end service will be accessed at port 80/443 on a given domain. So we may want to restrict a service to only use its front facing node as well as all the other non front facing nodes that are part of the swarm, but not running on another service front facing node, since then they will compete for the same ports.
What do you think? a legitimate use case and feature request?

**Comment by jhorwit2** [comment]
@manast I think what you are looking for is the `--constraint` option provided when creating services. You can check it out [here](https://docs.docker.com/engine/reference/commandline/service_create/#/specify-service-constraints).

**Comment by cpuguy83** [comment]
Correct, if you want to target a specific node, or set of nodes, use `--constraint`.
But also as @jhorwit2 pointed out, the routing mesh only allows one service on a particular port across the entire swarm... in the future you may be able to target specific IP's instead of all node IP's.

**Comment by manast** [comment]
@cpuguy83 Is there any issue in github regarding the feature for limiting a service to a particular set of IPs instead of running in all of them?. What is the expected behaviour today if I run two services in different sets of nodes using ```--constraint``` but using the same port?
