### ISSUE TITLE
Unable to remove an unreachable node from swarm cluster

### ISSUE THREAD

**Issue by jhorwit2** [docker/docker#26017]
**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:28:14 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:28:14 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 21
 Running: 1
 Paused: 0
 Stopped: 20
Images: 13
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 122
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge host null
Swarm: active
 NodeID: 0tcthsr3tyi44mg3jkx0d8e9x
 Is Manager: true
 ClusterID: 0srplt1fljtw87pzzz6zu4glx
 Managers: 3
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.15.2.39
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.2.0-42-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 5.79 GiB
Name: 489f0ffa-fc3b-4d95-95e6-46e32b771ac6
ID: FCRQ:NTEQ:E7DY:36WF:UTRE:B3YX:OAQI:APVJ:KRHK:QDUN:DP2I:AE65
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Create a swarm cluster
2. Stop a manager
3. Try to remove the manager with `docker node -rm <id> --force`

**Describe the results you received:**

I have a node that was in the cluster that went down unexpectedly without being able to be recovered. I was trying to remove it before adding a new one but I couldn't. 

```
$ docker node ls
ID                           HOSTNAME                              STATUS   AVAILABILITY  MANAGER STATUS
0tcthsr3tyi44mg3jkx0d8e9x *  489f0ffa-fc3b-4d95-95e6-46e32b771ac6  Unknown  Active        Leader
3wguwco187au4jyh9w70ui1bs    d2e19ffb-2b92-43ee-bbc1-91cd40d923e3  Unknown  Active        Reachable
8buja7impqchibmeevepsvtba    255be2fa-ae02-4835-8bce-de8c6cf55ba6  Down     Active        Unreachable
```

```
$ docker node rm 8buja7impqchibmeevepsvtba --force
Error response from daemon: rpc error: code = 4 desc = context deadline exceeded
```

**Describe the results you expected:**

The node should be removed. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment]
`docker node rm --force <id>` ?

**Comment by jhorwit2** [comment]
@cpuguy83 no dice. 
```
$ docker node rm --force 8buja7impqchibmeevepsvtba
Error response from daemon: rpc error: code = 4 desc = context deadline exceeded
```

**Comment by cpuguy83** [comment]
ping @aaronlehmann

**Comment by jhorwit2** [comment]
I ended up having to rebuild my cluster. It was hosed. The logs didn't show anything strange. My services were stuck in "ready" status. I had one that said it was running in `docker node ps self` but `docker ps` showed nothing. /shrug.

**Comment by aaronlehmann** [comment]
I'd be curious if other active manager operations like creating or updating a service failed in the same way while the cluster was in this state. The behavior feels like a loss of quorum. Theoretically a three-manager swarm shouldn't have a problem if only one node is down, but it's possible that the `MANAGER STATUS ` column for `3wguwco187au4jyh9w70ui1bs` is stale (`Status = Unknown` suggests that manager isn't fully available). As always, logs can be helpful for tracking down exactly what's going on.

**Comment by tomaszc** [comment]
I have the same problem. I created two-node swarm for learning purposes on two Ubuntu VirtialBox instances. I promoted second node to be a manager and then I forced him to leave the swarm by `docker swarm --force leave` (I know I should do it in other manner but this was done for testing purposes). Now I cannot remove it from the swarm.

Currently, on my leader node I got:

**docker version**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

```
**docker info**
 
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge host null
Swarm: active
 NodeID: d5biuqwuoix9mb47dst6guwh5
 Is Manager: true
 ClusterID: 5sli5sf77ku8b9yhkao2i8aq5
 Managers: 2
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.242.11.100
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-21-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.454 GiB
Name: tzci-VirtualBox
ID: 227Z:EZAZ:CHZK:2TVW:T7SD:HZOJ:NBI6:HUJJ:NZBR:QU66:MAW4:JTZF

Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```
 
**docker node ls**
```
ID                           HOSTNAME         STATUS  AVAILABILITY  MANAGER STATUS
as1nm8xzem3q2hbzatynesxc5    tzci-VirtualBox  Ready   Active        Unreachable
d5biuqwuoix9mb47dst6guwh5 *  tzci-VirtualBox  Ready   Active        Leader
```
**docker node rm as1nm8xzem3q2hbzatynesxc5 --force**
`Error response from daemon: rpc error: code = 4 desc = context deadline exceeded`

**Comment by aaronlehmann** [comment]
> I have the same problem. I created two-node swarm for learning purposes on two Ubuntu VirtialBox instances. I promoted second node to be a manager and then I forced him to leave the swarm by `docker swarm --force leave` (I know I should do it in other manner but this was done for testing purposes). Now I cannot remove it from the swarm.

After forcing one of your two manager nodes to leave, your swarm doesn't have a quorum anymore. This makes it impossible to make further changes. You shouldn't use `docker swarm --force leave` on a manager because it can break the swarm like this. If you get into this state, you can use `--force-new-cluster` to recover.

**Comment by sblackstone** [comment]
I can also confirm this issue:

```
jack:~ sblackstone$ docker node ls
ID                           HOSTNAME                    STATUS   AVAILABILITY  MANAGER STATUS
64byty9t75ephp765kv2owmvt                                Unknown  Active        Unreachable
8ww0zprszthovu9nmi780s7zw *  xxx-enterprise-manager-001  Ready    Drain         Leader
bikgqisq3w1u3eqybtv2i97tp    xxx-enterprise-node-001     Ready    Active
jack:~ sblackstone$
jack:~ sblackstone$ docker node rm 64byty9t75ephp765kv2owmvt --force
^C
jack:~ sblackstone$ docker node rm --force 64byty9t75ephp765kv2owmvt
Error response from daemon: rpc error: code = 4 desc = context deadline exceeded
```

**Comment by drlukeangel** [comment]
Seems like we have this a couple of places trying to link them together here. I would assume this would go in the swarm repo although that seems like pre native swarm or 1.12. Regardless i have the same issue. I guess this is really more of a smaller issue  although at first it seems huge the swarm will take on the former dropped host when it try to rejoin and still balances correctly when that host falls off.  Although i know there issue to have the load re-balance once a new node comes on. 

# Unable to remove an unreachable node from swarm cluster
![image](https://cloud.githubusercontent.com/assets/22433329/19216819/7be08992-8d80-11e6-96e2-7367bd25938c.png)
![image](https://cloud.githubusercontent.com/assets/22433329/19216821/8636e4a4-8d80-11e6-97a1-e78d4182893b.png)

## Try demote first? this was a manager node at one point. 
![image](https://cloud.githubusercontent.com/assets/22433329/19216833/d5d8fd94-8d80-11e6-9082-fce1a57aad29.png)
Timesout which makes sense since its not reachable. 

## how about a udpate?
![image](https://cloud.githubusercontent.com/assets/22433329/19216838/3396518e-8d81-11e6-9b8d-494274304413.png)
negative

## remove but with force this time  
![image](https://cloud.githubusercontent.com/assets/22433329/19216842/71d931be-8d81-11e6-8347-a3a31ebd0d3b.png)
Also does not work

alternate tickets just in csae the linking above is abust.
https://github.com/docker/swarm/issues/2304 
https://github.com/docker/docker/issues/10589

**Comment by Vanuan** [comment]
So what's the workaround?

**Comment by Vanuan** [comment]
I've been hit by this when I've run out of space

**Comment by Vanuan** [comment]
`--force-new-cluster` doesn't work either.
I had to remove `/var/lib/docker/swarm/` and recreate everything.

**Comment by drlukeangel** [comment]
there is not a fix at this time that i know of. 
I was just linking the tickets that seem to be same issues around so i just linked them.  I ran into another issue where the node wouldn't release port 80 after the service was removed which i think is also related. To get around that i removed the node from the swarm and then rebooted the server and that seemed to work.

**Comment by aaronlehmann** [comment]
@drlukeangel: It looks like your swarm has lost quorum - there are not enough reachable managers to achieve consensus. In these cases, the alternatives are to restore some of the unreachable managers, or use `--force-new-cluster` to remove all managers except the one where the command is run.

@Vanuan: Could you please provide some more information about the situation where `--force-new-cluster` didn't work? If possible, a list of steps that reproduces the problem would be great. Also, if you manage to get into a state where `--force-new-cluster` doesn't work, it would be useful if you could send `SIGUSR1` to the Docker daemon and copy/paste the stack dump that gets printed to the logs.

**Comment by Vanuan** [comment]
@aaronlehmann
Don't know what exactly was critical in this case. Here's the set up I have:

1. Three DigitalOcean 1GB RAM droplets with private networking
2. NFS (without docker) folder mounted manually to /nfs on 3 machines
3. Three docker swarm managers which are also workers (use private network eth1 to communicate, use public network eth0 to publish ports)
4. Two heavy services: elasticsearch and a script that streams large amounts of data there until NFS disk space fills up and/or OOM killer kills something randomly.

I understand that this is an edge case and I should use memory and CPU constraints and set up alerts to keep disk space free, but I expect Docker to recover from such a state. Or at least issue a warning about unconstrained resource usage.

>  it would be useful if you could send SIGUSR1 to the Docker daemon and copy/paste the stack dump that gets printed to the logs.

I currently switched to 1 manager swarm cluster and cleaned up disk space, the issue isn't reproducible in such a set up, but I'll keep this in mind if I decide to try multiple managers again.

**Unrelated thoughts:**

Would be great if there were some troubleshooting/bug reporting steps somewhere in the Docs. E.g.

> Q. What to do if get `context deadline exceeded`?
> A. Enable docker logs, generate stacktrace, etc and send it here...

Currently this information is spread through multiple GitHub issues.

Ideally, I would imagine such reporting workflow:

1. run `docker report start`
2. run command with unexpected results
3. run `docker report finish`.
4. link some report id to the GitHub issue.

But maybe it's impossible to achieve.

**Comment by mstanleyjones** [comment]
Thanks @thaJeztah, we already do caution against losing quorum on a swarm. @aaronlehmann , which of the steps above are appropriate for adding to official docs for troubleshooting? Obviously a small cluster with an even number of nodes is bad news when using RAFT consensus.

**Comment by aaronlehmann** [comment]
I think the most important thing is that people not use `docker node rm --force` to forcefully remove managers. We have safeguards in place to prevent people from losing quorum by running docker commands. However, `--force` overrides those safeguards.

**Comment by mstanleyjones** [comment]
Doc improvements: https://github.com/docker/docker.github.io/pull/297

**Comment by optimum-web** [comment]
My situation is even worse  

Nodes: 5
 (unknown): ***.***.***.**:2376
  └ ID:
  └ Status: Pending
  └ Containers: 0
  └ Reserved CPUs: 0 / 0
  └ Reserved Memory: 0 B / 0 B
  └ Labels:
  └ Error: Cannot connect to the Docker daemon at tcp://146.185.162.217:2376. Is the docker daemon running?
  └ UpdatedAt: 2017-02-13T16:03:56Z
  └ ServerVersion:

I even have no  ID to remove it.   

Best regards

**Comment by aaronlehmann** [comment]
@optimum-web: This looks like output from swarm classic (https://github.com/docker/swarm), not "swarm mode". Your issue is different from the one being discussed in this ticket. Your paste includes an error message about not being able to connect to the Docker daemon, so I'd suggest looking into that.

**Comment by aaronlehmann** [comment]
Since the documentation this area has been improved, I'm closing this issue.

**Comment by dongluochen** [comment]
@optimum-web Your case is [classic swarm](https://github.com/docker/swarm/), not docker swarm-mode. In your case the manager cannot connect to the node from node discovery. See `Error: Cannot connect to the Docker daemon at tcp://146.185.162.217:2376. Is the docker daemon running?`. So the node is in `Pending` state. To debug this issue, go to your swarm manager, try `docker -H 146.185.162.217:2376 info`. This would fail, likely due to daemon not running on the target node, or firewall blocks port 2376 to the target node. You may open an issue on classic swarm if it's not the case. 

The difference of classic swarm and swarm-mode is documented [here](https://github.com/docker/swarm/#swarm-disambiguation).

**Comment by optimum-web** [comment]
@dongluochen @aaronlehmann Thanks for info. 
docker -H 146.185.162.217:2376 info gives:
Get http://146.185.162.217:2376/v1.26/info: malformed HTTP response "\x15\x03\x01\x00\x02\x02".
* Are you trying to connect to a TLS-enabled daemon without TLS?  
however I can connect port using telnet and also see ports listening 2376 with netstat on the node.
Thanks!

**Comment by thaJeztah** [comment]
@optimum-web when connecting to a daemon that's protected with TLS, make sure the keys are present locally, otherwise you won't be able to connect; also see https://docs.docker.com/engine/security/https/
