### ISSUE TITLE
syslog facility doesnt work in overlay network..

### ISSUE THREAD

**Issue by wyxgit** [docker/docker#26011]
The net2 is overlay. We run (on this net2) a rsyslog server (10.50.1.2) but if we want run containers to connect to, no success. Just hanging the container in running phase....
(docker 1.12, etcd kvs)

Some errors (with IP and domain name):

```
# docker run -it --net net2  -d --log-driver=syslog --log-opt syslog-address=tcp://10.50.1.2:514 --log-opt tag="remote" ubuntu echo "remote log message"
c6954f7a618ee1743db1428c53d44b706ad967baa998576ed08dcf2481ad3a5f
docker: Error response from daemon: Failed to initialize logging driver: dial tcp 10.50.1.2:514: getsockopt: connection timed out.
```

```
# docker run -it --net net2  -d --log-driver=syslog --log-opt syslog-address=tcp://xxxx:514 --log-opt tag="remote" ubuntu echo "remote log message"
4ee980255cd0091319e047923cc6ca4c4be32987c2db891821d1c226c8e3c85e
docker: Error response from daemon: Failed to initialize logging driver: dial tcp: lookup xxxx on 213.133.100.100:53: no such host.
```
```
# docker run --rm --net=net2 busybox ping 10.50.1.2
PING 10.50.1.2 (10.50.1.2): 56 data bytes
64 bytes from 10.50.1.2: seq=0 ttl=64 time=0.069 ms
64 bytes from 10.50.1.2: seq=1 ttl=64 time=0.032 ms
```

**Comment by cpuguy83** [comment]
Logging is initialized on the daemon, not inside the container, which means container networking has no bearing on how the daemon can connect to some logging service.
Is that address reachable from the host?

**Comment by wyxgit** [comment]
You mean, the 10.50.1.2? This is an overlay IP, I can not ping it from the host.

Is it any solution to configure a syslogging structure (rsyslog server + client) on overlay network?

**Comment by cpuguy83** [comment]
If the IP is not reachable from the host, then it can't be used for the logging service.

**Comment by wyxgit** [comment]
Is the overlay IP reachable from the host by default?

**Comment by cpuguy83** [comment]
@wyxgit Sounds like not, but maybe you can route it via the `docker_gwbridge` network

**Comment by wyxgit** [comment]
I dont have such a bridge, but I have overlay net:

```
# docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
681108fcfbba        bridge              bridge              local               
91ca3126663a        host                host                local               
42ebb301264f        net1                bridge              local               
3af6d2f9d52c        net2                overlay             global              
278703889cf4        none                null                local   
```

**Comment by wyxgit** [comment]
I have created a new subnet with

```
docker network create --subnet=172.15.0.0/24 -o com.docker.network.bridge.enable_icc=false -o com.docker.network.bridge.name=docker_gwbridge docker_gwbridge
```

the gwbridge appeared.

```
# docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
681108fcfbba        bridge              bridge              local               
6a7ad45bae9f        docker_gwbridge     bridge              local               
91ca3126663a        host                host                local               
42ebb301264f        net1                bridge              local               
3af6d2f9d52c        net2                overlay             global              
9266d455689b        net3                overlay             global              
278703889cf4        none                null                local     
```

How can I route the overlay net via?

**Comment by sanimej** [comment]
@wyxgit Did you create the overlay network with `--internal` option ? If not `docker_gwbridge` should have been created when you run a container on the overlay network. You don't have to create it manually.

After you start rsyslog container get the IP address of the endpoint connected to the `docker_gwbridge`  network and use that IP as `syslog-address` for other containers on the overlay network.

**Comment by wyxgit** [comment]
Ok, created, everything is going fine from the same host. How can you reach this gwbridge IP address from another host? (I have containers on this also)
Is it any usual way or should we figure out it with iptables rules?

**Comment by sanimej** [comment]
@wyxgit Since `docker_gwbridge` is a local bridge network containers connected to this network on different hosts might have conflicting IPs. I think what you can do is publish the service from `rsyslog` container using `-p` option. And use the host-address where `rsyslog` container is running as the `syslog-address` for other containers be it on the same host or other hosts. Please see if this works.

**Comment by wyxgit** [comment]
?, any solution for this?

**Comment by thaJeztah** [comment]
Looks like the questions are answered, so I'll close this issue, but happy to hear how things went
