### ISSUE TITLE
[question] how can I discover what is the real path of a mountpoint from within a container

### ISSUE THREAD

**Issue by ninrod** [docker/docker#26021]
Is there a way to know what is the host equivalent path of a given mounted path inside the docker container? 

In other words, given a path `/root/code` inside the container, that is mounted, and in the host is really `/home/vagrant/code`, I'd like to issue a docker command like: 

```sh
# from within the docker container
$ cd /root
$ docker reveal hostpath code
  /root/code is a mountpoint for /home/vagrant/code in the host that runs docker daemon.
$ 
```

Is there a way to achieve that?

**Comment by cpuguy83** [comment]
`docker inspect --format '{{json .Mounts }}' <container>`
