### ISSUE TITLE
After upgrade to 1.12 I get: driver failed programming external connectivity on endpoint

### ISSUE THREAD

**Issue by stegr04** [docker/docker#26026]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Output of `docker version`:**

$ docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        
 OS/Arch:      linux/amd64

**Output of `docker info`:**

$ docker info
Containers: 5
 Running: 3
 Paused: 0
 Stopped: 2
Images: 1
Server Version: 1.12.0
Storage Driver: devicemapper
 Pool Name: docker-8:17-3297293-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 750.3 MB
 Data Space Total: 107.4 GB
 Data Space Available: 103.3 GB
 Metadata Space Used: 1.581 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.03.01 (2015-05-15)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.1.27-27-default
Operating System: openSUSE Leap 42.1 (x86_64)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 23.49 GiB
Name: user-leap.domain.com
ID: COYP:G3QF:QYEH:IGMN:E74T:BMQW:W6IV:COX3:3F3U:23NE:SKH6:TMFN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: No kernel memory limit support
Insecure Registries:
 127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Dell m4800 laptop

**Steps to reproduce the issue:**
1. After getting past the build errors reported in issue [26022](https://github.com/docker/docker/issues/26022) i tried to run the image I just built. This is when I get the error.
2. I can reproduce it using a completely different/independent image from the one I built using: docker run -e MYSQL_ROOT_PASSWORD=password -P -d mysql:5.7

**Describe the results you received:**
When I try to map the port it returns something like this:
e273c7c875b4320701cc48857ed25128ff87e0726ac9c06e07b2d0d7c81bd35a
docker: Error response from daemon: driver failed programming external connectivity on endpoint condescending_fermat (ec664a69075892300742349cca8fb6ebd7811bc654539d7b14b95373c396d65c): exec: "docker-proxy": executable file not found in $PATH.

**Describe the results you expected:**
I expect the image to run like it did before upgrading to docker 1.12. I was running 1.11 before the upgrade pushed out today. I think it was 1.11.2. And everything worked great. 

**Additional information you deem important (e.g. issue happens only occasionally):**
:: I tried completely uninstalling docker and its linked packages (via Yast) and reboot. Then I manually cleaned up some files left over like /var/lib/docker, /etc/sysconfig/docker, etc.. 
:: Then I tried reinstalling (using Yast system packages) and am still getting the error. 
:: Before running 1.11 I was using version 1.9 and everything worked really well there too. 
:: I've researched this error and have seen some issues that looked similar but they were from over a year or two ago. Regardless, I went through some of the points made like:
  :: confirming that the port was not in use (using: sudo netstat -aonp | grep 3306). 
  :: tried running the docker run command again after flushing iptables rules, etc.. (sudo iptables -F).
  :: stopped/started docker service (sudo service docker stop/start) to get the iptables rules back - just in case they are actually needed and the previous rules were corrupt.
  :: I'll post the events that I see from journalctl when starting the service and trying to run the docker run command in a comment.

**Comment by stegr04** [comment]
When running docker start I see the following (via journalctl -f):

Aug 25 18:01:44 user-leap.domain.com sudo[9773]: user : TTY=pts/0 ; PWD=/home/user/tmp/getdocker ; USER=root ; COMMAND=/usr/sbin/service docker start
Aug 25 18:01:44 user-leap.domain.com sudo[9773]: pam_unix(sudo:session): session opened for user root by user(uid=0)
Aug 25 18:01:44 user-leap.domain.com systemd[1]: Mounted Runtime Directory.
Aug 25 18:01:44 user-leap.domain.com systemd[1]: Starting Docker Socket for the API.
Aug 25 18:01:44 user-leap.domain.com systemd[1]: Listening on Docker Socket for the API.
Aug 25 18:01:44 user-leap.domain.com systemd[1]: Starting Docker Application Container Engine...
Aug 25 18:01:44 user-leap.domain.com systemd[1]: Started Docker Application Container Engine.
Aug 25 18:01:44 user-leap.domain.com sudo[9773]: pam_unix(sudo:session): session closed for user root
Aug 25 18:01:44 user-leap.domain.com dockerd[9785]: time="2016-08-25T18:01:44.729955258-04:00" level=warning msg="devmapper: Usage of loopback devices is strongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use `man docker` to refer to dm.thinpooldev section."
Aug 25 18:01:44 user-leap.domain.com dockerd[9785]: time="2016-08-25T18:01:44.762959814-04:00" level=warning msg="devmapper: Base device already exists and has filesystem ext4 on it. User specified filesystem  will be ignored."
Aug 25 18:01:44 user-leap.domain.com dockerd[9785]: time="2016-08-25T18:01:44.803618274-04:00" level=info msg="[graphdriver] using prior storage driver \"devicemapper\""
Aug 25 18:01:44 user-leap.domain.com dockerd[9785]: time="2016-08-25T18:01:44.810581723-04:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Aug 25 18:01:44 user-leap.domain.com dockerd[9785]: time="2016-08-25T18:01:44.810708484-04:00" level=warning msg="Your kernel does not support swap memory limit."
Aug 25 18:01:44 user-leap.domain.com dockerd[9785]: time="2016-08-25T18:01:44.810729847-04:00" level=warning msg="Your kernel does not support kernel memory limit."
Aug 25 18:01:44 user-leap.domain.com dockerd[9785]: time="2016-08-25T18:01:44.810803227-04:00" level=warning msg="mountpoint for pids not found"
Aug 25 18:01:44 user-leap.domain.com dockerd[9785]: time="2016-08-25T18:01:44.811051224-04:00" level=info msg="Loading containers: start."
Aug 25 18:01:44 user-leap.domain.com dockerd[9785]: ......time="2016-08-25T18:01:44.816589900-04:00" level=info msg="Firewalld running: false"
Aug 25 18:01:44 user-leap.domain.com dockerd[9785]: time="2016-08-25T18:01:44.894905508-04:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Aug 25 18:01:45 user-leap.domain.com dockerd[9785]: time="2016-08-25T18:01:45.074740599-04:00" level=info msg="Loading containers: done."
Aug 25 18:01:45 user-leap.domain.com dockerd[9785]: time="2016-08-25T18:01:45.074801788-04:00" level=info msg="Daemon has completed initialization"
Aug 25 18:01:45 user-leap.domain.com dockerd[9785]: time="2016-08-25T18:01:45.074819999-04:00" level=info msg="Docker daemon" commit=8eab29e graphdriver=devicemapper version=1.12.0
Aug 25 18:01:45 user-leap.domain.com dockerd[9785]: time="2016-08-25T18:01:45.079573705-04:00" level=info msg="API listen on /var/run/docker.sock"


=====================================

When running: docker run -e MYSQL_ROOT_PASSWORD=password -d -p 3306:3306 mysql:5.7

Aug 25 18:06:00 user-leap.domain.com kernel: EXT4-fs (dm-1): mounted filesystem with ordered data mode. Opts: (null)
Aug 25 18:06:00 user-leap.domain.com kernel: EXT4-fs (dm-1): mounted filesystem with ordered data mode. Opts: (null)
Aug 25 18:06:00 user-leap.domain.com kernel: EXT4-fs (dm-1): mounted filesystem with ordered data mode. Opts: (null)
Aug 25 18:06:00 user-leap.domain.com NetworkManager[981]: <warn>  (vethcaefebd): failed to find device 17 'vethcaefebd' with udev
Aug 25 18:06:00 user-leap.domain.com NetworkManager[981]: <info>  (vethcaefebd): new Veth device (carrier: OFF, driver: 'veth', ifindex: 17)
Aug 25 18:06:00 user-leap.domain.com NetworkManager[981]: <warn>  (veth4ab3e40): failed to find device 18 'veth4ab3e40' with udev
Aug 25 18:06:00 user-leap.domain.com NetworkManager[981]: <info>  (veth4ab3e40): new Veth device (carrier: OFF, driver: 'veth', ifindex: 18)
Aug 25 18:06:00 user-leap.domain.com NetworkManager[981]: <info>  (docker0): bridge port veth4ab3e40 was attached
Aug 25 18:06:00 user-leap.domain.com NetworkManager[981]: <info>  (veth4ab3e40): enslaved to docker0
Aug 25 18:06:00 user-leap.domain.com kernel: device veth4ab3e40 entered promiscuous mode
Aug 25 18:06:00 user-leap.domain.com kernel: IPv6: ADDRCONF(NETDEV_UP): veth4ab3e40: link is not ready
Aug 25 18:06:00 user-leap.domain.com kernel: docker0: port 1(veth4ab3e40) entered forwarding state
Aug 25 18:06:00 user-leap.domain.com kernel: docker0: port 1(veth4ab3e40) entered forwarding state
Aug 25 18:06:00 user-leap.domain.com kernel: docker0: port 1(veth4ab3e40) entered disabled state
Aug 25 18:06:00 user-leap.domain.com dockerd[9785]: time="2016-08-25T18:06:00.759026457-04:00" level=warning msg="Failed to allocate and map port 3306-3306: exec: \"docker-proxy\": executable file not found in $PATH"
Aug 25 18:06:00 user-leap.domain.com kernel: docker0: port 1(veth4ab3e40) entered disabled state
Aug 25 18:06:00 user-leap.domain.com avahi-daemon[928]: Withdrawing workstation service for vethcaefebd.
Aug 25 18:06:00 user-leap.domain.com avahi-daemon[928]: Withdrawing workstation service for veth4ab3e40.
Aug 25 18:06:00 user-leap.domain.com kernel: device veth4ab3e40 left promiscuous mode
Aug 25 18:06:00 user-leap.domain.com kernel: docker0: port 1(veth4ab3e40) entered disabled state
Aug 25 18:06:00 user-leap.domain.com NetworkManager[981]: <info>  (docker0): bridge port veth4ab3e40 was detached
Aug 25 18:06:00 user-leap.domain.com NetworkManager[981]: <info>  (veth4ab3e40): released from master docker0
Aug 25 18:06:00 user-leap.domain.com dockerd[9785]: time="2016-08-25T18:06:00.874359778-04:00" level=error msg="Handler for POST /v1.24/containers/599fdfab8b1b252a6c0674ca996e3817786d4576692a4020202af1f16629bf0f/start returned error: driver failed programming external connectivity on endpoint clever_mccarthy (87a8a9894acc3411008fc8427527a4fdccf979735b75d6335a225e8b891a264b): exec: \"docker-proxy\": executable file not found in $PATH"

**Comment by cyphar** [comment]
We've fixed this inside the Virtualization:containers package as of [this submit request](https://build.opensuse.org/request/show/423036).

As I noted in the other issue, it's very odd that you got a Docker 1.12 update from the openSUSE repos -- we haven't published them because we have some issues in our packages that we're fixing before publishing them. Can you please do a `zypper lr` so that we can see if you're accidentally pulling updates from our **experimental** Virtualization:containers packages (which is what appears to be the case).

Thanks for opening up [a bug in openSUSE's bug tracker](bugzilla.opensuse.org/show_bug.cgi?id=995620) for this issue though, much appreciated.

**Comment by stegr04** [comment]
I have updated the other issue too. Didn't realize I was going about this the wrong way (in more ways than one). Here is the zypper lr output. Thanks so much for your help. 

$ zypper ls
#  | Alias                               | Name                                    | Enabled | GPG Check | Refresh | Type  
---+-------------------------------------+-----------------------------------------+---------+-----------+---------+-------
1  | Docker_1.11                         | Docker 1.11                             | Yes     | (r ) Yes  | Yes     | rpm-md
2  | Google_Chrome                       | Google Chrome                           | No      | ----      | Yes     | rpm-md
3  | download.opensuse.org-non-oss       | Main Repository (NON-OSS)               | Yes     | (r ) Yes  | Yes     | yast2 
4  | download.opensuse.org-non-oss_1     | Update Repository (Non-Oss)             | Yes     | (r ) Yes  | Yes     | rpm-md
5  | download.opensuse.org-oss           | Main Repository (DEBUG)                 | Yes     | (r ) Yes  | Yes     | yast2 
6  | download.opensuse.org-oss_1         | Update Repository (DEBUG)               | Yes     | (r ) Yes  | Yes     | rpm-md
7  | download.opensuse.org-oss_2         | Main Repository (OSS)                   | Yes     | (r ) Yes  | Yes     | yast2 
8  | download.opensuse.org-oss_3         | Main Repository (Sources)               | Yes     | (r ) Yes  | Yes     | yast2 
9  | download.opensuse.org-oss_4         | Main Update Repository                  | Yes     | (r ) Yes  | Yes     | rpm-md
10 | ftp.gwdg.de-suse                    | Packman Repository                      | Yes     | (r ) Yes  | Yes     | rpm-md                                                       
11 | google-chrome                       | google-chrome                           | No      | ----      | Yes     | rpm-md                                                       
12 | http-download.opensuse.org-07028a4f | Archiving                               | Yes     | (r ) Yes  | Yes     | rpm-md                                                       
13 | http-download.opensuse.org-436d0e07 | home:Lazy_Kent                          | No      | ----      | No      | rpm-md                                                       
14 | http-download.opensuse.org-4aaedc77 | home:Lazy_Kent                          | No      | ----      | No      | rpm-md                                                       
15 | http-download.opensuse.org-a11a0989 | openSUSE:Leap:42.1:Update               | Yes     | (r ) Yes  | Yes     | rpm-md                                                       
16 | openSUSE-42.1-0                     | openSUSE-42.1-0                         | Yes     | (r ) Yes  | No      | yast2                                                        
17 | repo-debug-non-oss                  | openSUSE-Leap-42.1-Debug-Non-Oss        | No      | ----      | Yes     | NONE                                                         
18 | repo-debug-update-non-oss           | openSUSE-Leap-42.1-Update-Debug-Non-Oss | No      | ----      | Yes     | NONE                                                         
19 | repo-source                         | openSUSE-Leap-42.1-Source-Non-Oss       | No      | ----      | Yes     | NONE                                                         
20 | repo-update                         | openSUSE-Leap-42.1-Update               | Yes     | (r ) Yes  | Yes     | rpm-md

**Comment by stegr04** [comment]
I ran the "zypper install docker" command recommended in [26022](https://github.com/docker/docker/issues/26022) to see if it solved the problem. It did - thanks!

**Comment by justincormack** [comment]
Glad it is solved, closing now.

**Comment by stegr04** [comment]
Thanks. I just read the notification advising me to close it. I'll know to do this in future. 
Cheers!
