### ISSUE TITLE
Docker --env-file format not compatible with bash environment file format

### ISSUE THREAD

**Issue by ajays20078** [docker/docker#26053]
Consider the following env variables in a file myvars.env

```
var1="something else"

var2=another thing
```

When you run source myvars.env , bash throws a error as it can't export var2 which has a space, and it throws the error (-bash: thing: command not found)

But when you export the same file using --env-file in docker, it is getting exported properly.
 `docker run --env-file myvars.env -d <image_name>`

environment on the docker , shows the below values, which is not consistent with bash behaviour.

var1="something else"
var2=another thing

Whatever is "bash-compatible", is not docker compatible.

For the same example , if contents of myvars.env is
```
var1="something else"

var2="another thing"
```

When you source this file using bash, the value of these variables will be
```
bash-3.2$ echo $var1
something else
bash-3.2$ echo $var2
another thing
```

Whereas when you pass the same file to docker using --env-file, the value of these variables changes to:

```
root@2421a1853754:/# echo $var1
"something else"
root@2421a1853754:/# echo $var2
"another thing"
```

Notice, the double quotes in the latter value, both are NOT same values.

docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:44:17 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64

**Comment by cpuguy83** [comment]
Please don't open multiple issues for the same thing. Discussion can happen on the other issue.
Thanks.

**Comment by jszwedko** [comment]
@cpuguy83 what is the other issue?

**Comment by thaJeztah** [comment]
https://github.com/docker/docker/issues/26009
