### ISSUE TITLE
Options --net and --dns not being honoured at same time

### ISSUE THREAD

**Issue by hipposareevil** [docker/docker#26063]
$ docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      linux/amd64
 Experimental: true

**Output of `docker info`:**

$ docker info
Containers: 17
 Running: 2
 Paused: 0
 Stopped: 15
Images: 132
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 214
 Dirperm1 Supported: true
Logging Driver: syslog
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge overlay host
Swarm: active
 NodeID: aaaaa
 Is Manager: true
 ClusterID: xxxx
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 10
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: x
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-34-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 251.9 GiB
Name:asdfasdf
ID: C6FU:PGSA:QJEK:67KU:OFU7:U6NQ:24FX:4OJ6:P2OH:ZON7:HNZF:TJU7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical install on ubuntu 16.04

**Steps to reproduce the issue:**
1. Added "--dns 10.11.12.13" to my ExecStart in /etc/systemd/system/docker.service
2. Bounced docker
3. Created network: 
>  docker network create mybridge

4. Ran docker to look at /etc/resolv.conf:
 > docker run --net=mybridge  busybox cat /etc/resolv.conf
search my.work
nameserver 127.0.0.11
options ndots:0

5. Ran docker again with default bridge:
> docker run --net=bridge  busybox cat /etc/resolv.conf
search my.work
nameserver 10.11.12.13

6. Ran docker without bridge:
> docker run busybox cat /etc/resolv.conf
search my.work
nameserver 10.11.12.13

**Describe the results you received:**

I got differing versions of what is in /etc/resolv.conf. The daemon specified nameserver is not added in all cases.

**Describe the results you expected:**

I was expecting the nameserver 10.11.12.13 to be added to /etc/resolv.conf . Instead it overwrites the docker NS of 127.0.0.11 in some cases.

I would expect to be able to specify both a "--net=somebridge" to enable inter container communication, and a "--dns" so a container can use a specific DNS in my environment.

**Additional information you deem important (e.g. issue happens only occasionally):**

* I have seen workarounds to update the /etc/hosts in the container, but this is not bulletproof as servers I expect to reach via DNS may change their IP while container is running.

* Also able to reproduce same on my Mac:
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638

* I saw issue https://github.com/docker/docker/issues/21976, but I'm not receiving the warning thus filing new issue.

**Comment by cpuguy83** [comment]
This is expected behavior.
On user-defined networks (the `mybridge` network), docker runs a DNS server @ 127.0.0.11 for service discovery in the network (or really for all networks the container is attached to).
Any requests not handled by the internal resolver are forwarded to the configured DNS server.

`--net=bridge` is the default network, same as you ran in part 3 with no `--net` defined. Docker does not run DNS in containers on the default bridge, thus you see the DNS address you configured in `/etc/resolv.conf`.

Did I understand your problem correctly? Does this make sense?

**Comment by hipposareevil** [comment]
That makes sense. I assumed if my DNS entry wasn't in the /etc/resolv.conf that forwarding wouldn't happen. Since it's done through dockers DNS at 127.0.0.11 I'm all good.

thanks for the beta.
