### ISSUE TITLE
bigger /dev/shm

### ISSUE THREAD

**Issue by kohlerm** [docker/docker#2606]
I need to increase the size of /dev/shm which seems to be hardcoded to 64Mbyte 
in
lxc_template.go 

Is it correct that I have to change the value there and recompile docker to get a different value?
It would be helpful to be able to configure it per instnace, e.g some Databasesdo not install without enough shared memory.

**Comment by tianon** [comment]
Isn't this "just" that we need a configurable knob for the size of `/dev/shm` in `create`/`run`?

**Comment by tianon** [comment]
For the record, the main place this is currently hard-coded that I can find is https://github.com/docker/libcontainer/blob/14a7d2f468404e25577dced6982248e80ddce79a/nsinit/config.go#L261.

**Comment by dklotz** [comment]
I don't know about the others, but for me (ABBYY OCR inside a docker container) just having this size configurable (without having to run the container privileged) would be a perfect solution.

**Comment by kohlerm** [comment]
I agree making it configurable would help a lot.  If there would be a privileged mode for docker  build I could also work around this issue

**Comment by rongearley** [comment]
This is from https://github.com/docker/pull/3505

"Added a "docker run" option for sizing /dev/shm which is actually
hardcoded to 64M.

The option is -shm="xxx" where xxx is the size in bytes using k,m,g
notation.

Docker-DCO-1.0-Signed-off-by: Julien Vermillard jvermillar@sierrawireless.com (github: jvermillard)"

This seems to be a good fix to the constraints put on /dev/shm.

How does this get rolled into the centos 6.6 docker build?  Could really use this fix/feature.  I do not want to run in privileged mode.  Thanks.

**Comment by ChrisRut** [comment]
@rongearley, I think you mean: https://github.com/docker/docker/pull/3505

**Comment by rongearley** [comment]
Yes, thx.  Edited my comment.

**Comment by NIWAHideyuki** [comment]
Hi,
I hope for the function that the shm memory of a size that is bigger than 64MB can be set.
And, I tried to make it. #16168

Addition of "--shm-size" to which size of /dev/shm is changed when container is made.
- Optional "--shm-size=" was added to the run sub-command.
- The size of /dev/shm in the container can be changed when container is made.
- Being able to specify is a numerical value that applies number, b, k, m, and g.
- The default value is 64MB, when this option is not set.
- It deals with both native and lxc drivers.

Example)
\# docker run -it --shm-size=256m centos /bin/sh

Signed-off-by: NIWA Hideyuki <niwa.hiedyuki@jp.fujitsu.com>

**Comment by davidkarlsen** [comment]
How to apply this when building images (not running), e.g. docker build?

**Comment by NIWAHideyuki** [comment]
I newly applied optional --shm-size to "docker build" sub command.

**Comment by davidkarlsen** [comment]
@NIWAHideyuki Awesome - what release will it be in?

**Comment by macnibblet** [comment]
@NIWAHideyuki I would also like to know that

**Comment by thaJeztah** [comment]
@davidkarlsen @macnibblet the PR was just merged (https://github.com/docker/docker/pull/16168) and will be part of the 1.10 release

**Comment by davidkarlsen** [comment]
@thaJeztah Awesome - thanks!

**Comment by mansurali901** [comment]
Temporary increase tmpfs filesystem
1) Open /etc/fstab with vi or any text editor of your choice,
2) Locate the line of /dev/shm and use the tmpfs size option to specify your expected size,
e.g. 512MB:
tmpfs      /dev/shm      tmpfs   defaults,size=512m   0   0
e.g. 2GB:
tmpfs      /dev/shm      tmpfs   defaults,size=2g   0   0

mount -o remount /dev/shm

**Comment by davidthornton** [comment]
Is it possible to set this persistently in Docker Cloud?

**Comment by Eyshika** [comment]
@mansurali901 your method works in the host machine, it doesnt work for docker container. i tried same method but it gives me permission denied error for `mount -o remount /dev/shm` . i ran it with sudo as well but still container memory is same

**Comment by mansurali901** [comment]
@Eyshika this is happening because your container is working in un privileged mode if you run your container with --privilege mode this will work

**Comment by thaJeztah** [comment]
@Eyshika @mansurali901 I would highly recommend avoiding the use of `--privileged` as it will disable (if not all) all protection that containers provide. If you want to set the size for the container, `docker run` has a `--shm-size` option. You can also use the `--mount` option, which allows you to set options for swarm services as well (see https://github.com/moby/moby/issues/26714#issuecomment-466431391) for example:

```bash
docker run -it --rm \
  --name tmpfstest \
  --mount type=tmpfs,dst=/dev/shm,tmpfs-size=1000000000 \
  alpine
```

Inside the container:

```bash
/ # df -h /dev/shm
Filesystem                Size      Used Available Use% Mounted on
tmpfs                   953.7M         0    953.7M   0% /dev/shm
```
