### ISSUE TITLE
docker: Error response from daemon: devmapper: Error mounting '' on '': no such device.

### ISSUE THREAD

**Issue by chrissound** [docker/docker#26085]
Full error:
```docker: Error response from daemon: devmapper: Error mounting '/dev/mapper/docker-8:19-4350242-440515cbd0962b3ee777387f43e7de2186bb4dc9e41261d8b13206983227fc39-init' on '/var/lib/docker/devicemapper/mnt/440515cbd0962b3ee777387f43e7de2186bb4dc9e41261d8b13206983227fc39-init': no such device.```

This was working fine before. However I've recently upgraded my Linux kernel. 

**sudo docker info | grep Udev**
```
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Udev Sync Supported: true
```

**docker -v**
`Docker version 1.12.1, build 23cf638`

**uname -a**
`Linux archamd 4.4.16-1-lts #1 SMP Thu Jul 28 16:21:18 CEST 2016 x86_64 GNU/Linux`

**Comment by chrissound** [comment]
I've just done a restart and it's now working!

**Comment by boogy** [comment]
Same problem here. Tried reinstalling, restarting and still have the error message

**Comment by Baldrs** [comment]
On Arch linux, this can be caused by kernel upgrade. Reboot fixes it.
