### ISSUE TITLE
Getting the container logs of a failing service

### ISSUE THREAD

**Issue by gittycat** [docker/docker#26083]
I can't figure out how to get the logs for containers of a service that is failing to start.

I have a 3 node "swarm mode" on VMware Fusion using docker 1.12.1 on hosts (docker version info below).

If I start a simple failing service as follow:
```
docker service create --name foo alpine:3.4 sh -c "echo 'Failure Message...' 1>&2 && exit 1"
```

I can see the service spawning a succession of tasks which are being shutdown after a few seconds.
```
docker service ps foo
ID                         NAME          IMAGE       NODE        DESIRED STATE  CURRENT STATE            ERROR
1oskvngdmomthietbssqj2qkh  failer.1      alpine:3.4  vmw-node02  Ready          Preparing 1 seconds ago  
av5at0aoc07bl4lu95uqyucse   \_ failer.1  alpine:3.4  vmw-node01  Shutdown       Failed 2 seconds ago     "task: non-zero exit (1)"
1grtjkialzsbo5bqgopgm42q3   \_ failer.1  alpine:3.4  vmw-node02  Shutdown       Failed 7 seconds ago     "task: non-zero exit (1)"
09n0g5so86y7r7cwcyq3nggi6   \_ failer.1  alpine:3.4  vmw-node01  Shutdown       Failed 12 seconds ago    "task: non-zero exit (1)"
1jge4jo220dhx998o7sqqbegd   \_ failer.1  alpine:3.4  vmw-node02  Shutdown       Failed 18 seconds ago    "task: non-zero exit (1)"
```

The containers for the above tasks are however destroyed too fast and I don't see how one can observe the error logs that they generate. I must say that it's also a chore to get info about which container makes up a task.

Am I missing something obvious here?  The container generated logs are very important to help debug deployment issues. Ideally I'd listen to these logs through the service API, but there isn't anything for that as far as I can see. eg: `docker service logs -f foo`

**Output of `docker version`:**
```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7
 Git commit:   23cf638
 Built:        Thu Aug 18 22:32:50 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```

**Comment by jhorwit2** [comment]
You can run the following command to get the logs for a task, running or not. 

`docker logs $(docker inspect --format "{{.Status.ContainerStatus.ContainerID}}" <task_id>)`

There is a ticket here #24812 for tracking the implementation of service logs.

**Comment by gittycat** [comment]
Thanks but this workaround has serious limitations:
1. It only works for tasks that haven't been shutdown already (task state is Ready).
1. A service might have many replicas. We'd need to retrieve the container for each one.
1. For a quickly failing task, the container may have been deleted between the time we get its id and time to get its log.
1. By the time the container log is inspected, it might already have had the time to fail. That info wouldn't be seen.

Some of this work can be put into a bash script (see below) but it's still not going to be consistently catching stderr from containers.
```
while :
do
    for sid in $(docker service ps $1 |grep Ready | cut -d" " -f1); do
        cid=$(docker inspect --format "{{.Status.ContainerStatus.ContainerID}}" $sid)
        if [ $cid ];then
            docker logs $cid
        fi
    done
done
```

**Comment by hekaldama** [comment]
@gittycat my experience also shows that the workaround only works if swarm launches the task on the currently configured `DOCKER_HOST`. Is this your experience as well?

**Comment by gittycat** [comment]
@hekaldama Yes it's currently very awkward. For running services I need to do a `docker service ps SERVICE-NAME` to find which nodes the service is running, point the docker client to the node and then do a `docker ps` to find the container id followed by finally `docker logs cont-id`.

Logging services [is on the table for Docker 1.13](https://github.com/docker/docker/issues/24812) so I'm trying to just live with this workaround for now.

**Comment by stefanpl** [comment]
In case anyone still struggles with this: Recent docker versions (1.29 upwards) now have the exact functionality @gittycat was missing: `docker service logs -f [serviceId]` 

This will show output from all containers that the service creates.

[More in the docs](https://docs.docker.com/engine/reference/commandline/service_logs/)

**Comment by davericher** [comment]
@stefanpl actually it will not show logs for things like invalid mount points (rejected services), the status line in docker service ps will however

**Comment by sorenwacker** [comment]
docker logs $(docker inspect --format "{{.Status.ContainerStatus.ContainerID}}" n8jwf78tuludcgyoeqtenzews)Error: No such object: n8jwf78tuludcgyoeqtenzews
"docker logs" requires exactly 1 argument.
See 'docker logs --help'.

Usage:  docker logs [OPTIONS] CONTAINER

Fetch the logs of a container
