### ISSUE TITLE
Restart containers on docker engine upgrade

### ISSUE THREAD

**Issue by ryanchapman** [docker/docker#26109]
Hi,

It appears that the default behavior on an upgrade of docker-engine is to look at the RestartPolicy.  We intentionally set the RestartPolicy to be off so that we don't mask an issue by continually restarting it; however, when docker-engine is upgraded, we want our containers to automatically come back up.

Could you change the default behavior on upgrade to start containers back up ASAP, or add a new option that will allow the administrator to set the desired behavior (e.g. RestartOnUpgradePolicy)?

Best regards,
Ryan

**Output of `docker version`:**

```
root@influxdb-stage-1:~# docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
root@influxdb-stage-1:~# docker info
Containers: 5
 Running: 4
 Paused: 0
 Stopped: 1
Images: 5
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-202:1-270588-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.743 GB
 Data Space Total: 107.4 GB
 Data Space Available: 2.384 GB
 Metadata Space Used: 3.879 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-88-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.305 GiB
Name: influxdb-stage-1
ID: ZMLH:3JX7:WTMY:4CDD:5W2K:5V4T:HHKJ:L6KF:WD2K:H7U6:CTTV:XQ4F
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
root@influxdb-stage-1:~#
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS, 

**Steps to reproduce the issue:**
1. apt-get update
2. apt-get dist-upgrade

**Describe the results you received:**
Containers are not running after upgrade

**Describe the results you expected:**
Containers are running shortly after the upgrade finished

**Additional information you deem important (e.g. issue happens only occasionally):**
```
root@influxdb-stage-1:~# docker inspect 2fe8dbf2c9aa | jq '.[0].HostConfig.RestartPolicy'
{
  "MaximumRetryCount": 0,
  "Name": "no"
}
```

**Comment by cpuguy83** [comment]
Docker 1.12 has support for "live restore", where you can restart the daemon without the containers being shut down.

You can set this on the daemon by the flag `--live-restore`.
It's not enabled by default for backwards compatibility. Also the mode conflicts with the swarm services model.

**Comment by ryanchapman** [comment]
According to https://docs.docker.com/engine/admin/live-restore/, live restore only works with minor version upgrades. I'm looking for a solution that will work regardless of the version number.

In my case, a 'live restore' is nice but not necessary.  I just want containers to always come up after upgrades.

**Comment by ryanchapman** [comment]
Thanks @cpuguy83, we'll try that and report back if any issues are encountered.

Ryan
