### ISSUE TITLE
device-mapper not available with Docker for mac

### ISSUE THREAD

**Issue by djannot** [docker/docker#26116]
```
# dmsetup create hda --table 0                            
/dev/mapper/control: open failed: No such device
Failure to communicate with kernel device-mapper driver.
Check that device-mapper is available in the kernel.
Incompatible libdevmapper (unknown version) and kernel driver (unknown version).
Command failed
```

**Comment by cpuguy83** [comment]
IIRC, this is intentional as devmapper is huge, not sure if there are plans to support it in the future or not.

ping @justincormack

**Comment by justincormack** [comment]
There are no current plans to support devicemapper, as it among other things slows booting down. Note there is no '/dev/hda` which is where your first error comes from. You could probably use loopback files to create volumes instead for this use case.

**Comment by justincormack** [comment]
I am going to close this, as there are no plans to support devicemapper.
