### ISSUE TITLE
Clarify --force in swarm leave documentation

### ISSUE THREAD

**Issue by aaronlehmann** [docker/docker#26125]
The CLI reference docs say this about `swarm leave --force`.

```
      --force   Force leave ignoring warnings.
```

They should also mention that `swarm leave --force` allows you to remove a manager, but does not gracefully remove the manager from the swarm. Doing this may cause the swarm to lose its quorum. Unless you don't care about the impact on the existing cluster, you should always demote managers to workers before removing them.

cc @sfsmithcha

**Comment by mstanleyjones** [comment]
Fixed by #26256 I think. Ping @aaronlehmann
