### ISSUE TITLE
docker container auto restart when server power off/on

### ISSUE THREAD

**Issue by zjxpsetp** [docker/docker#26129]
**Output of `docker version`:**

Docker version 1.12.1, build 23cf638

**Output of `docker info`:**

Docker version 1.12.1, build 23cf638
root@doctor:~# docker info
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-202:2-65283-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.231 GB
 Data Space Total: 107.4 GB
 Data Space Available: 19.75 GB
 Metadata Space Used: 4.096 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.143 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-61-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.829 GiB
Name: doctor
ID: MBX4:LN2T:RZ3I:OZYJ:T57U:KR3A:CKCJ:IDXZ:NVAN:HQOE:MDXA:TAUJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. ps -ef | grep docker
2. kill  -9 "the process docker-containerd-shimxxx"
3. restart this container

**Describe the results you received:**
We found the container can not start because docker show it has started " Container xxx is already active"

**Describe the results you expected:**
Our vm maybe powe-roff  and power-on by hypervisor because emergency reason. And we expect our container can auto-restart after power on. So if the process killed by os because of power-off. How can we ensure the container can auto-restart? 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment]
If you actually power-off/power-on the system, all state information about the container will be gone since it is in a tmpfs (in most cases).

ping @mlaventure 
I'm not sure if there is anything more we can do in cases where the shim dies (or is is sigkilled as done here).

**Comment by mlaventure** [comment]
@zjxpsetp is the error you saying more akin to `Error response from daemon: oci runtime error: container with id exists: e575172ed11dc01bfce087fb27bee502db149e1a0fad7c296ad300bbff178148` ?

If not, can you share the debug logs for your test?

**Comment by chrisjones77** [comment]
I'm experiencing this same problem.  I'm using Docker Cloud.  I have some details here.  https://forums.docker.com/t/service-containers-not-automatically-starting-on-node-restart/21326/5

**Comment by mlaventure** [comment]
@chrisjones77 your issue seems to be different than this one.

Your failure seems to be related to a missing (network?) plugin.

Feel free to open a new issue here to have it looked at.

**Comment by mlaventure** [comment]
Waiting for `containerd` to be vendored in master before closing this

**Comment by mlaventure** [comment]
#22049 updated `containerd`, closing this
