### ISSUE TITLE
Support a docker volume update command, needed for persistent volumes

### ISSUE THREAD

**Issue by govint** [docker/docker#26133]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   ae816ba
 Built:        Wed Jun 15 07:20:09 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   ae816ba
 Built:        Wed Jun 15 07:20:09 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 135
Server Version: 1.12.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 291
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local vmdk
 Network: bridge null host overlay
Swarm: inactive
Kernel Version: 3.13.0-85-generic
Operating System: Ubuntu 14.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: hte-1s-eng-dhcp98
ID: H3SC:SAIV:HFHW:WYI5:WC4O:GEVQ:S6AJ:VIJ2:4CVT:UXDQ:T4GW:7MCA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 19
 Goroutines: 26
 System Time: 2016-08-29T23:18:40.582832575-07:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Create a persistent volume specifying the volume name and driver name and with the "-o" option to specify driver specific properties of the volume
2. Volume is created and can be used, but there is no way to modify the attributes of the volume once its created. As a user I'm forced to delete the volume and re-create it. 
3. Volume drivers can support features like making the volume read-only, expand the volume size (for example). None of which can be applied once the volume is created.

**Describe the results you received:**

**Describe the results you expected:**
Propose a new command "volume update" be added so container user can update volume attributes after volume creation. Its assumed the app can detect and handle the change to the volume attributes. Especially very useful for volume plugin providers to surface capabilities that are currently not feasible via docker commands.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by Anvil** [comment]
I'm very interested in this feature. With this, volume drivers could implement features such as resizing (e.g: `docker volume update -o size=30G`), renaming, etc.

**Comment by allencloud** [comment]
I think this issue is somewhat related to https://github.com/docker/docker/issues/25291

**Comment by e4jet** [comment]
#dibs

**Comment by thaJeztah** [comment]
Closing for now, per the discussion on https://github.com/docker/docker/pull/30109. https://github.com/docker/docker/issues/31923 may be relevant as well

**Comment by govint** [comment]
@cpuguy83, @thaJeztah can this issue be considered again, looks like CSI doesn't support updating a docker volume for now and its going to be some time before it does and some time more before Docker gets CSI enabled plugins enabled (yess??) We have customers wanting to be able to modify existing docker volume properties and resizing is a repeated ask.

Can this issue be worked on to support a _docker volume update_ command?
