### ISSUE TITLE
How to look up which machine a container is running on, if the container is started via "docker service create"?

### ISSUE THREAD

**Issue by ghostplant** [docker/docker#26136]
I have a cluster with each machine installing Docker 1.12 and I make them a swarm cluster using the new feature provided by version 1.12.
However, when I run "docker service create ...", the container is started as expected, but I don't know which machine it runs on. Looking up with "docker service inspect .." outputs no useful information.

If the number of machines in the cluster is large, it's hard to log into every machine and check "docker ps" to find the container. So does anyone have comments? Thx.

**Comment by cpuguy83** [comment]
```
$ docker service create --name test busybox top
64xcy7z1csa0ah4pcgvxw4cyk
$ docker service ps test
D                         NAME    IMAGE    NODE  DESIRED STATE  CURRENT STATE               ERROR
4usy3al9r225rh4nimrdw5od6  test.1  busybox  moby  Running        Running about a minute ago
$ docker node inspect moby
...
```

**Comment by ghostplant** [comment]
Yes, so it can only display hostname instead of ipaddress (which is used for --advertise-addr)? This requires an additional DNS server to manage these hostnames.
