### ISSUE TITLE
Error while pulling image: Get https://index.docker.io/v1/repositories/library/ubuntu/images: http: error connecting to proxy http://%E2%80%9Dhttp://proxy:8080%E2%80%9D: dial tcp: lookup ”http: invalid domain name

### ISSUE THREAD

**Issue by gowrisankar22** [docker/docker#26144]
Hello all,

when i do the pull from docker registry i get below error, can anybody help here?
i307955@mo-d2a63ca18:~$ docker pull ubuntu
Using default tag: latest
Pulling repository docker.io/library/ubuntu
Error while pulling image: Get https://index.docker.io/v1/repositories/library/ubuntu/images: http: error connecting to proxy http://%E2%80%9Dhttp://proxy:8080%E2%80%9D: dial tcp: lookup ”http: invalid domain name

i have set the proxy inside /etc/default/docker aswell.

BRs.Gowrisankar

**Comment by cpuguy83** [comment]
Looks like you've set HTTP_PROXY incorrectly.
Can you provide the details of how this is set?

**Comment by gowrisankar22** [comment]
added below lines, becasuse couple of weeks before it was working proper. my old machine still it works fine.. proplem with new machines only
export http_proxy=”http://proxy.xx.xx.xx:8080”
export https_proxy=”http://proxy.xx.xx.xx:8080”
export no_proxy="xx.xx"

**Comment by cpuguy83** [comment]
Looks like you've got "smart quotes" instead of real ones there.
This is there wierd URL encoding you are seeing with `%E2%80%9D`

**Comment by gowrisankar22** [comment]
that did the trick :) ..

**Comment by sbandhavi30** [comment]
facing the same error
docker run --rm busybox:latest /bin/echo "Hello world"
Unable to find image 'busybox:latest' locally
Pulling repository docker.io/library/busybox
Error while pulling image: Get https://index.docker.io/v1/repositories/library/busybox/images: dial tcp: lookup index.docker.io: Temporary failure in name resolution

**Comment by sbandhavi30** [comment]
dig index.docker.io +noall +answer +nocomments

; <<>> DiG 9.10.3-P4-Ubuntu <<>> index.docker.io +noall +answer +nocomments
;; global options: +cmd
;; connection timed out; no servers could be reached

**Comment by sbandhavi30** [comment]
I dont know if the problem with dns or dhcp
