### ISSUE TITLE
Auto DOCKER_API_VERSION switching

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#26155]
The docker CLI supports setting `DOCKER_API_VERSION` to an older version.  Is there a reason why the client couldn't just auto switch to the correct API version instead of complaining that the server is too old?

**Comment by icecrime** [comment]
We're working on it (cc @vieux)! See #25498 :-)

**Comment by icecrime** [comment]
Also: that environment variable is basically just lying on the user agent string, but not doing anything meaningful.
