### ISSUE TITLE
Unable to round-trip network configuration through API

### ISSUE THREAD

**Issue by dhiltgen** [docker/docker#26176]
If you inspect a network, the IPAM Gateway is reported in CIDR notation, such as `10.0.0.1/24` however if you use that same format during network create for the Gateway, the daemon gives an error:
```
rpc error: code = 3 desc = ipam configuration: invalid gateway 10.0.0.1/24
```

If we're going to report this in CIDR, we should accept creation with the same syntax.

**Comment by aboch** [comment]
I do not see the gateway being reported in CIDR notation in the body of `GET .../networks/<nw_name>` or in the o/p of `docker network inspect <nw_name>` with docker from master:

```
{
  "Name": "bbb",
<snip>
  "IPAM": {
    "Driver": "default",
    "Options": {},
    "Config": [
      {
        "Subnet": "12.12.0.0/16",
        "Gateway": "12.12.3.4"
      }
    ]
  },
<snip>
}
```
Can you provide more info/context on how to reproduce.

**Comment by dhiltgen** [comment]
Strange.  I'm not able to reproduce now either.  I was testing against an earlier incarnation of https://github.com/docker/docker/pull/25962 so maybe that was the source of the glitch.
