### ISSUE TITLE
Docker run env-file parameter crashes on windows with non-ascii encoding

### ISSUE THREAD

**Issue by matt-richardson** [docker/docker#26179]
Using the `--env-file` parameter on windows causes an error `container XXX encountered an error during CreateProcess failed in Win32: The data is invalid. (0xd)`.

**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
Containers: 15
 Running: 0
 Paused: 0
 Stopped: 15
Images: 368
Server Version: 1.12.0
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat transparent null overlay
Swarm: inactive
Security Options:
Kernel Version: 10.0 14300 (14300.1045.amd64fre.rs1_release_svc.160705-1059)
Operating System: Windows Server 2016 Datacenter Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 3.5 GiB
Name: matt-dckr-2016
ID: CVFQ:6K7E:MZMF:KJUS:QZQ2:YDVU:BRGY:4ZQ3:32MQ:5IXI:C4RY:GV76
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Windows Server 2016 TP 5 VM on Azure, created via the `Deploy to Azure` button on https://msdn.microsoft.com/en-au/virtualization/windowscontainers/quick_start/quick_start_windows_server

**Steps to reproduce the issue:**
1. `echo FOO=BAR > env.list`
2. `docker run --env-file env.list --rm microsoft/windowsservercore cmd /c set`

**Describe the results you received:**
An error message:
```
C:\Program Files\Docker\docker.exe: Error response from daemon: container 5f2e0ccb28f1523aa63f50ad6d6e4b4a59086e1ef23fb43c1d3a
0a880f86b346 encountered an error during CreateProcess failed in Win32: The data is invalid. (0xd) extra info: {"ApplicationNa
me":"","CommandLine":"cmd /c set","WorkingDirectory":"C:\\","Environment":{"\u0000":"","F\u0000O\u0000O\u0000":"\u0000B\u0000A
\u0000R\u0000\r\u0000"},"EmulateConsole":false,"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"Console
Size":[0,0]}.
```

**Describe the results you expected:**
A list of environment variables that includes the variable `FOO`.

**Additional information you deem important (e.g. issue happens only occasionally):**
This also happens in the latest docker nightly:
```
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7
 Git commit:   ec82819
 Built:        Wed Aug 31 01:48:34 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7
 Git commit:   ec82819
 Built:        Wed Aug 31 01:48:34 2016
 OS/Arch:      windows/amd64
```

**Comment by yongtang** [comment]
I am wondering if the env-file you provided is in UTF-16 format in Windows? Not sure docker is able to handle UTF-16. Maybe you could try with an ASCII file.

**Comment by matt-richardson** [comment]
Bizarrely, if I use notepad to change it, I get the same error on `ANSI`, `Unicode`, `Unicode Big Endian` and `UTF-8`.

If i use `"FOO=BAR" | Out-File -FilePath .\env.list -Encoding ascii`, it works.

So, it appears the real issue is `--env-file` doesn't support non-ascii encodings. I'll update the title.

**Comment by yongtang** [comment]
I haven't used Windows for some time but I remember notepad typically adds a BOM at the beginning of the file. Golang should be able to handle utf8 so I think if we remove the BOM in env parser then the env file encoded in utf8 by notepad should work.

**Comment by yongtang** [comment]
Created a pull request #26296 to try to address this issue.
