### ISSUE TITLE
Differences between per-hand-created and Dockerfile-created container: Potential permission issues?

### ISSUE THREAD

**Issue by manixx** [docker/docker#26189]
I have some troubles installing a dockerized version of the mysql-cluster. At the first sight it seems that there were some problems with the cluster itself, but after some tests I think this problem is docker-related. 

Sadly the error is hard to explain because there is no docker error message, its more a strange behavior of the container itself. Futhermore the given error message by the mysql-cluster is not very explanatory, too. Sorry. 

**Szeanrio**: Create two ubuntu containers and install the mysql-cluster. Create the first one with a blank ubuntu image and install everthing by hand, for the second container use a Dockerfile. On the "blank" machine the cluster works; on the "Dockerfile" machine it doesn't. 

The steps to reproduce this issue are very long, so I added them to the end of this issue! 

Basically the mysql-cluster cannot create any tables and throws an error Nr. 13, which inidicates (in theory) problems with permissions. The error itself is described [here](http://stackoverflow.com/questions/38717260/mysql-cluster-error-1005-cant-create-table-ndb-schema-errno-13).

**My question:** If I create two containers, one by hand and the other one with a Dockerfile using the exact same steps (except WORKDIR), are there any differences between these two at the end (in terms of usage)? 
I know there are some docker-internal differences between them (each step creates a new layer when using a Dockerfile), but can a Dockerfile-created container cause any permission-related misbehavior? 

Used version (on Ubuntu 16.04 LTS):

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64
```

To reproduce my issue:

**Create the "blank" machine:**

    $ docker run -ti --name=ubuntu ubuntu

Inside the container run the following:

    # apt-get update && apt-get install -y \
        build-essential \
        perl \
        libaio1 \
        libaio-dev
        
    # apt-get install -y wget
    # cd /var/tmp
    # wget http://dev.mysql.com/get/Downloads/MySQL-Cluster-7.4/mysql-cluster-gpl-7.4.12-linux-glibc2.5-x86_64.tar.gz
    
    # groupadd mysql
    # useradd -g mysql -s /bin/false mysql
    # tar -C /usr/local -xzvf /var/tmp/mysql-cluster-gpl-7.4.12-linux-glibc2.5-x86_64.tar.gz
    # rm -rf /var/tmp/mysql-cluster-gpl-7.4.12-linux-glibc2.5-x86_64.tar.gz
    # ln -s /usr/local/mysql-cluster-gpl-7.4.12-linux-glibc2.5-x86_64 /usr/local/mysql
    
    # cpan File::Copy Sys::Hostname Data::Dumper
    # cd /usr/local/mysql
    # scripts/mysql_install_db --user=mysql
    # chown -R root .
    # chown -R mysql data
    # chgrp -R mysql .
    
    # mkdir -p /var/lib/mysql-cluster/
    
    # apt-get install -y vim
    # vim /etc/my.cnf
    
Add this:

    [mysqld]
    # Options for mysqld process:
    ndbcluster                      # run NDB storage engine

    [mysql_cluster]
    # Options for MySQL Cluster processes:
    ndb-connectstring=127.0.0.1  # location of management server
    
Then create managers config:

    # vim /var/lib/mysql-cluster/config.ini
    
Add this: 

    [ndbd default]
    # Options affecting ndbd processes on all data nodes:
    NoOfReplicas=1
    DataMemory=80M 
    IndexMemory=18M

    [tcp default]
    # TCP/IP options:
    portnumber=2202 

    [ndb_mgmd]
    # Management process options:
    hostname=127.0.0.1         
    datadir=/var/lib/mysql-cluster 

    [ndbd]
    # Options for data node "B":
    hostname=127.0.0.1     
    datadir=/usr/local/mysql/data 

    [mysqld]
    # SQL node options:
    hostname=127.0.0.1 
    
Then start the manager:

    # cd /usr/local/mysql/bin/
    # ./ndb_mgmd --config-file=/var/lib/mysql-cluster/config.ini --nodaemon
    
Open 3 more terminals and connect to container

    $ docker exec -ti ubuntu bash

    # ./usr/local/mysql/bin/ndbd --nodaemon
    
    # ./usr/local/mysql/bin/mysqld_safe
    
    # cat /usr/local/mysql/data/xxxxxx.err // check if cluster runs properly

The log should say something like this (at the end):

> (...)
> 2016-08-30 14:15:33 182 [Note] NDB Binlog: starting log at epoch 155/9
> 2016-08-30 14:15:33 182 [Note] NDB Binlog: Got first event
> 2016-08-30 14:15:33 182 [Note] NDB Binlog: ndb tables writable
> 2016-08-30 14:15:33 182 [Note] NDB Binlog: Startup and setup completed

Create the failing machine:

    $ vim Dockerfile

Add the steps you did in the first place inside the Dockerfile:

    FROM ubuntu

    RUN apt-get update && apt-get install -y \
            build-essential \
            perl \
            libaio1 \
            libaio-dev
        
    RUN apt-get install -y wget
    WORKDIR /var/tmp
    RUN wget http://dev.mysql.com/get/Downloads/MySQL-Cluster-7.4/mysql-cluster-gpl-7.4.12-linux-glibc2.5-x86_64.tar.gz

    RUN groupadd mysql
    RUN useradd -g mysql -s /bin/false mysql

    RUN tar -C /usr/local -xzvf /var/tmp/mysql-cluster-gpl-7.4.12-linux-glibc2.5-x86_64.tar.gz
    RUN rm -rf /var/tmp/mysql-cluster-gpl-7.4.12-linux-glibc2.5-x86_64.tar.gz

    RUN ln -s /usr/local/mysql-cluster-gpl-7.4.12-linux-glibc2.5-x86_64 /usr/local/mysql
        
    RUN cpan File::Copy Sys::Hostname Data::Dumper

    WORKDIR /usr/local/mysql
    RUN scripts/mysql_install_db --user=mysql
    RUN chown -R root .
    RUN chown -R mysql data
    RUN chgrp -R mysql .

    COPY ./my.cnf /etc

    RUN mkdir -p /var/lib/mysql-cluster/
    COPY ./config.ini /var/lib/mysql-cluster/

    ENV PATH=/usr/local/mysql/bin:$PATH

    EXPOSE 3306

    ENTRYPOINT ["ndb_mgmd", "--config-file=/var/lib/mysql-cluster/config.ini", "--nodaemon"]

Add the files `my.cnf` and `config.ini` to the Dockerfiles dir:

`my.cnf`:

    [mysqld]
    # Options for mysqld process:
    ndbcluster                      # run NDB storage engine

    [mysql_cluster]
    # Options for MySQL Cluster processes:
    ndb-connectstring=127.0.0.1  # location of management server
    
`config.ini`: 
    
    [ndbd default]
    # Options affecting ndbd processes on all data nodes:
    NoOfReplicas=1
    DataMemory=80M 
    IndexMemory=18M

    [tcp default]
    # TCP/IP options:
    portnumber=2202 

    [ndb_mgmd]
    # Management process options:
    hostname=127.0.0.1         
    datadir=/var/lib/mysql-cluster 

    [ndbd]
    # Options for data node "B":
    hostname=127.0.0.1     
    datadir=/usr/local/mysql/data 

    [mysqld]
    # SQL node options:
    hostname=127.0.0.1 
    
Build and try everthing: 
    
    $ docker build -t broken .
    $ docker run --name broken broken
    
Again, open 3 other terminals to start the other processes and to check the log:

    $ docker exec -ti broken bash
    
    # ndbd --nodaemon
    
    # mysqld_safe
    
    # cat /usr/local/mysql/data/xxxxxx.err // check if cluster runs properly
    
On this machine the logs should show the following: 

> (...)
> 2016-08-30 14:23:36 599 [Note] NDB: Creating mysql.ndb_schema
> 2016-08-30 14:23:36 599 [ERROR] NDB: Query 'CREATE TABLE IF NOT EXISTS mysql.ndb_schema ( db VARBINARY(63) NOT NULL,name VARBINARY(63) NOT NULL,slock BINARY(32) NOT NULL,query BLOB NOT NULL,node_id INT UNSIGNED NOT NULL,epoch BIGINT UNSIGNED NOT NULL,id INT UNSIGNED NOT NULL,version INT UNSIGNED NOT NULL,type INT UNSIGNED NOT NULL,PRIMARY KEY USING HASH (db,name) ) ENGINE=NDB CHARACTER SET latin1' failed, error: 1005: Can't create table 'ndb_schema' (errno: 13)
> 2016-08-30 14:23:37 599 [Note] NDB: Creating mysql.ndb_schema
> 2016-08-30 14:23:37 599 [ERROR] NDB: Query 'CREATE TABLE IF NOT EXISTS mysql.ndb_schema ( db VARBINARY(63) NOT NULL,name VARBINARY(63) NOT NULL,slock BINARY(32) NOT NULL,query BLOB NOT NULL,node_id INT UNSIGNED NOT NULL,epoch BIGINT UNSIGNED NOT NULL,id INT UNSIGNED NOT NULL,version INT UNSIGNED NOT NULL,type INT UNSIGNED NOT NULL,PRIMARY KEY USING HASH (db,name) ) ENGINE=NDB CHARACTER SET latin1' failed, error: 1005: Can't create table 'ndb_schema' (errno: 13)

So this machine is unable to create a table inside the cluster, which indicates (according the mysql-cluster docs) that the cluster isn't setup correctly. The error inidicates a permission issue. 

All permissions on the machine are exactly the same. 

I really appreciate your help, because I'm clueless about this issue. Do I miss something obvious? 
Thanks in advice!

**Comment by cpuguy83** [comment]
This looks suspicious:
```
# chown -R root .
# chown -R mysql data
# chown -R mysql .
```

Indeed there are some weird permissions issues that crop up with AUFS where permissions change on two different layers.

Also not sure why you would chown everything to root, then later chown everything to mysql.

**Comment by manixx** [comment]
Thank you for your reply! You are totally right! The third line should look like this:

chgrp -R mysql .

I did this in my previous tests, which also failed. I will update the issue soon.

**Comment by manixx** [comment]
I did not resolve the error itself, but I got it working using less layers (i think):

So these are the working Dockerfiles:

**mysql daemon:**
```
FROM ubuntu

RUN apt-get update && \
    apt-get install -y libcam-pdf-perl build-essential libaio1 libaio-dev && \
    cpan File::Copy \
         Sys::Hostname \
         Data::Dumper

// .. install mysql cluster files to /usr/local/mysql

WORKDIR /usr/local/mysql

RUN groupadd mysql && \
    useradd -g mysql -s /bin/false mysql && \
    chown -R root . && \
    chown -R mysql data && \
    chgrp -R mysql . && \
    scripts/mysql_install_db --user=mysql
    
ENV PATH=/usr/local/mysql/bin:$PATH

USER mysql
```

**ndbd**:
```
FROM ubuntu

// .. install mysql cluster files to /usr/local/bin

RUN chmod +x /usr/local/bin/ndb* && \
    mkdir -p /usr/local/mysql/data
```

**ndb_mgm**:
```
FROM ubuntu

// .. install mysql cluster files to /usr/local/bin

RUN chmod +x /usr/local/bin/ndb_mgm* && \
    mkdir -p /var/lib/mysql-cluster
```
