### ISSUE TITLE
panic: send on closed channel on tag 1.6.2

### ISSUE THREAD

**Issue by niokkong** [docker/docker#26217]
package pubsub
//1.6.2tag:
// Close closes the channels to all subscribers registered with the publisher.
func (p *Publisher) Close() {
	p.m.Lock()
	for sub := range p.subscribers {
		close(sub)
	}
	p.m.Unlock()
}

//1.7
// Close closes the channels to all subscribers registered with the publisher.
func (p *Publisher) Close() {
	p.m.Lock()
	for sub := range p.subscribers {
		delete(p.subscribers, sub)
		close(sub)
	}
	p.m.Unlock()
}

**Comment by cpuguy83** [comment]
Thanks, this is long fixed. Closing.
