### ISSUE TITLE
When starting docker daemon with TLS the API wont listen in a local socket.

### ISSUE THREAD

**Issue by Telmo** [docker/docker#26210]
Prior to 1.12 we were able to start docker with TLS for tcp connections coming from another hosts, while at the same time being able to use the client locally with the unix socket. As of 1.12 this seems to be non functional, starting TLS with the options 

```
-H fd:// -H tcp://dockerhost.test.net:2376 --tlsverify --tlscacert=/root/docker/ssl/ca.pem --tlscert=/root/docker/ssl/dockerhost-cert.pem --tlskey=/root/docker/ssl/dockerhost-key.pem
```

creates the following error:

```
-- Unit docker.service has begun starting up.
Aug 31 17:27:19 dockerhost.test.net docker[11251]: time="2016-08-31T17:27:19.820910719Z" level=fatal msg="no sockets found via socket activation: make sure the service was started by systemd"
Aug 31 17:27:19 dockerhost.test.net systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Aug 31 17:27:19 atlas-ho-1t.sys.comcast.net systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has failed.
--
-- The result is failed.
```

Removing the offending `-H fd://` causes docker to only listen to TCP and the client unable to talk to the daemon unless ENV variables are defined providing the SSL keys, host to connect to etc.

**Output of `docker version`:**

```
# docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Output of `docker info`:**

```
# docker info
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running on CentOS7 latest.

**Steps to reproduce the issue:**
1. Have a host configured with TLS working on 1.11
2. Update to 1.12
3. cry and curse

**Describe the results you received:**

Docker wont listen in a unix socket. Client can't talk to daemon **locally**

**Describe the results you expected:**

Docker should be able to talk to the daemon **locally**

**Additional information you deem important (e.g. issue happens only occasionally):**

Things like this should not be broken in minor version updates, going from 1.11 to 1.12 should be an easy transition without breaking backwards compatibility changes specially due to the fast pace release of docker.

**Comment by cpuguy83** [comment]
`-H fd://` is for socket activation. Socket activation was the source of many problems, so support for the socket was removed (note that there is no docker.socket file anymore).

Docker's unit file is not meant to be modified directly (or really any unit file, not just docker). You can modify the settings by using a drop-in file: https://docs.docker.com/engine/admin/systemd/#/custom-docker-daemon-options
This is so authors can make changes as needed w/o breaking users.

Alternatively, it's generally recommended to use the distro-agnostic configuration file @ /etc/docker/daemon.json (which by default won't exist): https://docs.docker.com/engine/reference/commandline/dockerd/#/linux-configuration-file
Using this file has the added benefit that you can make changes and hot-reload the daemon to apply those changes.

**Comment by nathanleclaire** [comment]
FYI as well @Telmo, `unix://` might be what you had in mind.  TLS + local unix socket communication works fine in boot2docker 1.12.1 / docker-machine.

```console
docker@default:~$ ps fax | grep dockerd
16118 pts/0    S+     0:00              \_ grep dockerd
 2671 ?        Sl     0:53 dockerd -D -g /var/lib/docker -H unix:// -H tcp://0.0.0.0:2376 --label provider=virtualbox --tlsverify --tlscacert=/var/lib/boot2docker/ca.pem --tlscert=/var/lib/boot2docker/server.pem --tlskey=/var/lib/boot2docker/server-key.pem -s aufs
```

**Comment by cpuguy83** [comment]
Thanks @nathanleclaire I forgot to mention

**Comment by nathanleclaire** [comment]
NP!
