### ISSUE TITLE
for stack_tasks.md there is no corresponding go file, and for stack/ps.go there is no corresponding md file

### ISSUE THREAD

**Issue by lixiaobing10051267** [docker/docker#26227]
in stack_tasks.md, there is command:

    Usage:  docker stack tasks [OPTIONS] STACK

    List the tasks in the stack

in stack/ps.go, there is command:

	cmd := &cobra.Command{
		Use:   "ps [OPTIONS] STACK",
		Short: "List the tasks in the stack",

**Comment by tealtail** [comment]
Hi, I'd like to help here so I'm looking for a bit of clarification.

What I've gleaned is that `docker stack tasks` cmd may have been removed?

So is what we're looking for here to remove `stack_tasks.md`, while adding a `stack_ps.md` to correspond with the `stack/ps.go` cmd?

Cheers!
