### ISSUE TITLE
can't disconnect container from default network before starting it

### ISSUE THREAD

**Issue by vikstrous** [docker/docker#26220]
**Output of `docker version`:**

```
master / bdae52a23dd69be29f0d5b871ee791180329e458
```

**Output of `docker info`:**

```
n/a
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Steps to reproduce the issue:**

1. docker create --name tmp -it alpine sh
2. docker network disconnect $(docker network ls | grep bridge | awk '{print $1}') tmp

**Describe the results you received:**
```
Error response from daemon: container 56f1cef3d80ede48d61ffbb90554055ea3255c98475e085ab12337251108d503 is not connected to the network 72787bea99a0
```

**Describe the results you expected:**
success

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by vikstrous** [comment]
I forgot to mention that this works in docker 1.12.1

**Comment by icecrime** [comment]
@vikstrous So... should I close this as fixed? 😕

**Comment by vikstrous** [comment]
I mean this is a bug introduced between docker 1.12.1 and 1.13/master/bdae52a23dd69be29f0d5b871ee791180329e458

**Comment by yongtang** [comment]
@vikstrous @icecrime The issue seems to be in:
https://github.com/docker/docker/blob/05a3f2666ee34c2dfa04663bbdda3c7763b001d8/daemon/container_operations_unix.go#L126-L135
where the original network name (`networkName`) instead of the resolved network name (`n.Name()`) was used.

**Comment by yongtang** [comment]
@vikstrous @icecrime I creaated a pull request #26297 to fix it. Please let me know if there are any issues.
