### ISSUE TITLE
support set shm-size to images when docker build

### ISSUE THREAD

**Issue by liuxiaopiao** [docker/docker#26230]
**Output of `docker version`:**

[root@adc01klb tmp]# docker --version
Docker version 1.12.1, build 23cf638
**Output of `docker info`:**
[root@adc01klb tmp]# docker info
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 19
Server Version: 1.12.1
Storage Driver: btrfs
 Build Version: Btrfs v3.19.1
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.1.12-37.6.3.el7uek.x86_64
Operating System: Oracle Linux Server 7.1
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 14.57 GiB
Name: adc01klb
ID: VU4C:BYLG:4PY5:645N:A3EF:BY75:JMVU:XHLW:56H2:WQ2R:XARC:K7CN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false

**Additional environment details (AWS, VirtualBox, physical, etc.):**
[root@adc01klb tmp]# uname -a
Linux adc01klb 4.1.12-37.6.3.el7uek.x86_64 #2 SMP Fri Aug 12 15:44:33 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux

**Steps to reproduce the issue:**
1.  Run command like "docker build  --shm-size=512K  -t test  -f test1.dockerfile ."
2. After build, run into the container using the image just built:
[root@adc01klb tmp]# docker run -it ff24885393fa bash
[root@e0405006caee /]# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/loop0       45G  196M   42G   1% /
tmpfs           7.3G     0  7.3G   0% /dev
tmpfs           7.3G     0  7.3G   0% /sys/fs/cgroup
/dev/loop0       45G  196M   42G   1% /etc/resolv.conf
/dev/loop0       45G  196M   42G   1% /etc/hostname
/dev/loop0       45G  196M   42G   1% /etc/hosts
shm              64M     0   64M   0% /dev/shm

**Describe the results you received:**
The mount size of /dev/shm is still 64M

**Describe the results you expected:**

The mount size of /dev/shm should be the same as we specified.

**Comment by coolljt0725** [comment]
@liuxiaopiao  I think you misunderstand the `--shm-size` flag of `docker build`, it's to set the shm-size of intermediate containers during build,  but not to set the default `shm-size` of the image, this value will not persist to image config.

**Comment by liuxiaopiao** [comment]
Thanks @coolljt0725 . Is there any way to set the shm-size for the image?

**Comment by coolljt0725** [comment]
@liaoqingwei  AFAIK, there is no way to set the shm-size for the image. you have to set it on container creation by `docker create/run`

**Comment by liuxiaopiao** [comment]
Thanks @coolljt0725

**Comment by justincormack** [comment]
@liuxiaopiao I don't think that makes sense, the size could well depend on runtime factors. You can add a `LABEL` at build time that says how much you need and then read that and use it to set the parameters for `docker run`.

**Comment by thaJeztah** [comment]
I agree with @justincormack and @coolljt0725 - this is an option to set at runtime, and should not be dictated by the image. I'll close this, because I don't think this will (or can) be implemented

**Comment by attila123** [comment]
'docker help image build' lists the --shm-size option but according to this last comment from @thaJeztah and my quick test it does not effective. So is it actually a bug in documentation (the usage it prints using this help command)?
(Tried it with: Docker version 17.05.0-ce, build 89658be)

**Comment by thaJeztah** [comment]
@attila123 read the discussion above; the `--shm-size` on `docker image build` only sets the size for the containers that are started as part of the build process; the setting is not persisted in the image, so doing `docker run <the image you built>` will still use the default setting, unless you set `--shm-size` on `docker run`.

**Comment by assignonward** [comment]
While I concur that shared memory size can depend on runtime factors, there are many containers that will always want more than the default 64M shared memory - it would be convenient (and easier to check into source control) to be able to specify a new default, perhaps in the Dockerfile, that could still be overridden by the runtime argument.
