### ISSUE TITLE
Feature Request: Dockerfile support parallel RUN to boost build progress

### ISSUE THREAD

**Issue by netroby** [docker/docker#26231]
This is a feature request.

In golang , we can using chan/goroutine to parallel execute command.

So i request Dockerfile provide us a Parallel RUN command. Like PRUN

```
PRUN cd public && node run build
PRUN go get -v ./...&&go build ....
```
These two kind build progress were very common on mordern web development. We need build web frontend stack , like using npm + webpack.
And we need build backend code , from golang source code to binary executable file.

If we can run them parallel. our building time will getting more shorter.

**Comment by duglin** [comment]
Yea but how can you guarantee that they won't interfere with each other w.r.t. changes on the filesystem?
Have you tried something like:
```
FROM ubuntu
RUN (sleep 5 ; echo hi 1 ) & (sleep 3 ; echo hi 2) ; wait
```

**Comment by thaJeztah** [comment]
I share @duglin's concerns, and don't see us supporting this. I'm not even sure this will be _possible_ in a layered filesystem, where the previous layer is always read-only.

I'll close this issue, as the example @duglin gave looks to address the use-case, and implementing this in docker would be really complicated (if possible at all).

Thanks for opening the feature request though, @netroby, it's appreciated

**Comment by pongnguy** [comment]
@thaJeztah the Dockerfile as currently implemented performs all the steps in series.  Having a sequence of PRUN commands would merely inform that each step can be executed in any order, where it is implicit that all the sequence of PRUN commands need to be completed before a subsequent RUN command.  So each PRUN command can still have a previous layer be read-only, however the order in the which the PRUN commands are applied would no longer be guaranteed.

@duglin when using a sequence of PRUN commands, it should be expected that the order in the which the commands execute is not guaranteed, and to take this into account with respect to changes in the file system (i.e. each command could write to a different file, so there is no conflict).
