### ISSUE TITLE
Docker for mac is not starting properly

### ISSUE THREAD

**Issue by astropanic** [docker/docker#26248]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      darwin/amd64
Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.22)
```

**Output of `docker info`:**

```
Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.22)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Download the [.dmg](https://download.docker.com/mac/stable/Docker.dmg)
2. Open, drag the whale to /Applications
3. Run it

Tried starting it from the terminal:

```
➜  Docker.app /Applications/Docker.app/Contents/MacOS/Docker -h
1472738427164968960 com.docker.docker Application version: 1.12.0-a (11213)
1472738427165171200 com.docker.docker Administrator user: false
1472738427189466880 com.docker.docker OSX Version: Version 10.10.5 (Build 14F1909)
kern.hv_support: 1
1472738427382631168 com.docker.docker migrator: start migration process
1472738427384282112 com.docker.docker migrator: previous install detected
1472738427384313088 com.docker.docker migrator: previous version is 1.12.0-rc3-beta18
1472738427384322048 com.docker.docker migrator: no migration needed, you are good to go!
1472738427384326912 com.docker.docker migrator: successfully updated from version 1.12.0-rc3-beta18 to 1.12.0-a
1472738427385449984 com.docker.docker migrator: end of migration process
1472738427469657856 com.docker.docker event tracker initialized
1472738427475544064 com.docker.docker Bundle path: /Applications/Docker.app
```

It hangs then.

**Describe the results you received:**

Docker doesn't start, I don't see the whale in the bar, nor I can connect from the CLI.
I can't uninstall it as well, because it freezes:

~~~
➜  Docker.app /Applications/Docker.app/Contents/MacOS/Docker --uninstall
~~~

**Describe the results you expected:**

I see the whale in the bar, I can interact with the daemon in the CLI.

**Additional information you deem important (e.g. issue happens only occasionally):**
No additional information here, want just run the deamon.

**Comment by justincormack** [comment]
Please could you open this issue in https://github.com/docker/for-mac/issues as it is Mac specific and you will get faster support there.

**Comment by astropanic** [comment]
moved
