### ISSUE TITLE
Unconsumed build-arg should not fail docker build

### ISSUE THREAD

**Issue by rzachariah** [docker/docker#26249]
---
## BUG REPORT INFORMATION

**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 24
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 29
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.16.0-30-generic
Operating System: Ubuntu 14.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: localhost
ID: WLEB:43M4:CAE3:SKQF:5SMS:EFWL:JRJF:S3O7:D2AC:S6ZO:R3M3:SDYC
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Username: rzachariah
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

VirtualBox VM running on Windows 7 machine. Accessed via Vagrant.

**Steps to reproduce the issue:**
1. Create a valid Dockerfile (in my case, for a node service). DO NOT consume the build-arg we will pass in next.
2. Build the docker image passing in an unused build-arg
docker build --build-arg VERSION=3.1.4 -t hello-error .

**Describe the results you received:**
Docker build fails with this error:
Step 11 : EXPOSE 80
 ---> Using cache
 ---> aed38f6ddf88
Step 12 : CMD npm start
 ---> Using cache
 ---> c33d33264d01
One or more build-args [VERSION] were not consumed, failing build.

**Describe the results you expected:**
Build should succeed.

**Additional information you deem important (e.g. issue happens only occasionally):**
I think it makes more sense for build-args to be optional. We have a CI build script that runs the docker build command. It's shared across our org. Not everyone needs the variable we pass in.

**Comment by cpuguy83** [comment]
This is one of those philosophical issues.
Personally I see that having a flexible system is good, but it's also good to have precise builds.
If you provide a variable that goes unused then from the standpoint of reliable build results this is an error... ie, you gave us something that we couldn't use, so we are telling you about it so you can correct it.

What's nice here is the image does get built so if you re-run w/o the un-consumed argument it should just use the cache.

**Comment by rzachariah** [comment]
User DanielDent appears to be on my side of the philosophical divide, based on his comment here.
https://github.com/docker/docker/issues/14634

**Comment by ykoehler** [comment]
When writting script to build many images, where some may required the build arg in question and some don't, having this "build arg not consume" stop the script from being simple such as:

  for all build step
    docker build $BUILD_ARG ...

Because of this severe validation, one has to figure out which build require which variable and must sequentially build the docker image using the proper $BUILD_ARG.

Can you add an option to allow a developer to turn off the this validation?

This way everyone becomes happy and efficient in writing script can be restored.

**Comment by thaJeztah** [comment]
We discussed this in the maintainers meeting, and we're ok with changing the error to just a warning, so anyone that wants to open a PR, it'll likely get accepted

**Comment by duglin** [comment]
If so, we should revisit the entire requirement to have ARG in there at all since a warning is about as good as ignoring it.  ARG serves no purpose but to cause extra steps for people - an implicit ARG for each build-arg specified on the command line should be sufficient.

**Comment by thaJeztah** [comment]
> If so, we should revisit the entire requirement to have ARG in there at all

No, this is the other way round; only args defined with `ARG` are _consumed_, but other args don't fail the build. Not requiring `ARG` would result in _any_ environment variable to be set in the image during build, which is not the same

**Comment by mgomezch** [comment]
@thaJeztah Is there already an issue tracking an enhancement request for such a feature?

**Comment by thaJeztah** [comment]
@mgomezch yes, this one :smile:

**Comment by mgomezch** [comment]
I meant this feature, though:

> Not requiring ARG would result in any environment variable to be set in the image during build, which is not the same

It’d be nice to be able to specify build environment variables using `--build-arg` for variables not specified in the `Dockerfile`, and have them consumed and applied to the environment made available to commands in `RUN` instructions during the build.  My use case would be the same as that specified in [the aforementioned comment in #14634](https://github.com/docker/docker/issues/14634#issuecomment-230976732).  Indeed this would be useful to access cached resources during builds in CI infrastructure for build systems that don’t use the “standard” variables that have been included in [BuiltinAllowedBuildArgs](https://github.com/docker/docker/blob/7944480dd0dfb00323f960d37c31d0ddad5f6cf2/builder/dockerfile/builder.go#L37-L47).

I understand this issue as specific to the feature of yielding only a warning, not a build failure, if the build command is provided a `--build-arg` option that does not match an `ARG` instruction in the built `Dockerfile`, but this issue falls short of requesting that such `--build-arg` options produce environment variables available to `RUN` instruction commands.  Or does this issue cover both features?

**Comment by thaJeztah** [comment]
@mgomezch probably best to open a new issue / feature request for that

**Comment by addamh** [comment]
#dibs
