### ISSUE TITLE
Daemon hangs after starting and stopping many containers

### ISSUE THREAD

**Issue by tswift242** [docker/docker#26251]
**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 43
 Running: 17
 Paused: 0
 Stopped: 26
Images: 21
Server Version: 1.12.1
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.19-040419-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 120.1 GiB
Name: ip-10-97-1-130
ID: NB4F:S4ON:5TH6:64OM:SOG6:JUZ4:YVLY:X4C2:XIUE:YOCL:LKKM:32K2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 191
 Goroutines: 353
 System Time: 2016-09-01T17:53:42.395022289Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS EC2. We currently run 46 containers on a single EC2 instance and expect 46 to be up at all times; we use upstart to start a new container each time a container is stopped. However, currently there are far fewer than 46 up and it looks to be a Docker issue.

**Steps to reproduce the issue:**
1. Start and stop a lot of containers on the same host. In particular, start a lot of containers (dozens) concurrently on the same host.

**Describe the results you received:**
Daemon hangs. Doing a "docker ps" has taken between 21 seconds and 8 and half minutes over the 10 trials I've done. "docker ps -a" shows many containers with the Dead status.

**Describe the results you expected:**
Daemon should not hang even after starting and stopping many containers.

**Additional information you deem important (e.g. issue happens only occasionally):**
This EC2 instance has only been up for 17 hours.

I've attached the stack trace for the daemon. I'd like to note that even after I sent SIGUSR1 to the daemon and a new dockerd process came up, "docker ps" still takes a long time.

I'm also attaching the daemon logs with debug output (I can only attach a subset of the logs, as the whole log file is over 100MB in size, so I've taken out a bunch of lines in the middle) You'll see lots of containers being created, but none of these containers seem to come/stay up. To make that clearer, I'm also attaching a part of the host's syslog. We log a line for every container that's created. The syslog shows 109 containers being created over 50 seconds. However, upstart is only logging that 9 containers exited in that same span. It seems like all these docker run requests must be being queued up and not being acted on.

The first error I see in the docker daemon logs is: "Handler for POST /v1.24/containers/66d5297807977a7e95cbf57163c4ba3c1864dd1dd4afad2b0568caadb9576809/start returned error: driver failed programming external connectivity on endpoint stoic_brown_45 (d9cd0a967f51929b7b597c1084e3086186a758098563710692f903ad39983451): failed to update bridge endpoint d9cd0a9 to store: failed to update bridge store for object type *bridge.bridgeEndpoint: timeout"

This seems to be the cause of at least some of the proceeding bad behavior, such as "Bind for 0.0.0.0:10045 failed: port is already allocated"

[docker_stack_trace.txt](https://github.com/docker/docker/files/450476/docker_stack_trace.txt)
[docker_truncated.txt](https://github.com/docker/docker/files/450495/docker_truncated.txt)
[syslog_truncated.txt](https://github.com/docker/docker/files/450477/syslog_truncated.txt)

**Comment by cpuguy83** [comment]
This looks like the offending code:
```
goroutine 400490 [semacquire]:
sync.runtime_Semacquire(0xc8204ad0b8)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0xc8204ad0b4)
	/usr/local/go/src/sync/mutex.go:83 +0x1c4
github.com/docker/libnetwork/datastore.(*datastore).PutObjectAtomic(0xc8204ad080, 0x7f86bf0e2ea0, 0xc821adbce0, 0x0, 0x0)
	/usr/src/docker/vendor/src/github.com/docker/libnetwork/datastore/datastore.go:384 +0x6d
github.com/docker/libnetwork.(*controller).updateToStore(0xc8202864b0, 0x7f86bf0e2ea0, 0xc821adbce0, 0x0, 0x0)
	/usr/src/docker/vendor/src/github.com/docker/libnetwork/store.go:227 +0x1ea
github.com/docker/libnetwork.(*endpoint).sbLeave(0xc821adbce0, 0xc820dfab40, 0xc820dfab00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/docker/vendor/src/github.com/docker/libnetwork/endpoint.go:685 +0xf45
github.com/docker/libnetwork.(*endpoint).Leave(0xc8221c6b00, 0x7f86bf0c17a0, 0xc820dfab40, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/docker/vendor/src/github.com/docker/libnetwork/endpoint.go:619 +0x1ab
github.com/docker/libnetwork.(*sandbox).delete(0xc820dfab40, 0xc822577100, 0x0, 0x0)
	/usr/src/docker/vendor/src/github.com/docker/libnetwork/sandbox.go:216 +0xaff
github.com/docker/libnetwork.(*sandbox).Delete(0xc820dfab40, 0x0, 0x0)
	/usr/src/docker/vendor/src/github.com/docker/libnetwork/sandbox.go:179 +0x32
github.com/docker/docker/daemon.(*Daemon).releaseNetwork(0xc8204bc000, 0xc821208d20)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/container_operations.go:758 +0x51c
github.com/docker/docker/daemon.(*Daemon).Cleanup(0xc8204bc000, 0xc821208d20)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/start.go:172 +0x53
github.com/docker/docker/daemon.(*Daemon).StateChanged(0xc8204bc000, 0xc8242b0040, 0x40, 0xc821ab03b0, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/monitor.go:41 +0x629
github.com/docker/docker/libcontainerd.(*container).handleEvent.func1()
	/usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/container_linux.go:184 +0xab
github.com/docker/docker/libcontainerd.(*queue).append.func1(0xc8213e5c00, 0x0, 0xc822b526f0, 0xc8231e23c0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/queue_linux.go:26 +0x47
created by github.com/docker/docker/libcontainerd.(*queue).append
	/usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/queue_linux.go:28 +0x1da
```

ping @mrjana

**Comment by cpuguy83** [comment]
Actually, sorry that's not the offending bit, it's just blocked trying to get the store lock, but it does look like there's a deadlock in the libnetwork datastore.

**Comment by tswift242** [comment]
Okay, after looking at the full docker daemon logs and syslog, I think I see what's going on. This seems very related to https://github.com/docker/libnetwork/issues/1374. However, I actually see an additional issue here.

So, our EC2 host got into a bad state very early on. What happened is we started 46 containers all at once (as usual). However, the 46th container failed with the error I mentioned above:

"Handler for POST /v1.24/containers/66d5297807977a7e95cbf57163c4ba3c1864dd1dd4afad2b0568caadb9576809/start returned error: driver failed programming external connectivity on endpoint stoic_brown_45 (d9cd0a967f51929b7b597c1084e3086186a758098563710692f903ad39983451): failed to update bridge endpoint d9cd0a9 to store: failed to update bridge store for object type *bridge.bridgeEndpoint: timeout"

Since this container failed to come up, upstart will start a new one, at the same IP address. This also fails, for the following reason:

"Handler for POST /v1.24/containers/766ffb65c332a87fea9706a5d6b00f2b68eeb4773195a23780d0e92bd764573d/start returned error: driver failed programming external connectivity on endpoint insane_leakey_45 (24b67bed5ad89438e9ac05b0c25928a44e0e2669cafba2a58dd31ed780eae2bc): Bind for 0.0.0.0:10045 failed: port is already allocated"

This then repeats itself. It looks like that port is never deallocated after the initial timeout updating the bridge store. Upstart will keep trying to start a container on this port, putting load on the daemon. Then, the issue will happen again for another container:

"Handler for POST /v1.24/containers/249b72a20c749713d365683dd61e144839cfd31fc9bd0615c8f22a074919ae68/start returned error: failed to create endpoint ecstatic_archimedes_29 on network matlab: failed to save bridge endpoint 1a14fa5 to store: failed to update bridge store for object type *bridge.bridgeEndpoint: timeout"

Upstart will burn through more containers, putting even more load on the daemon. Then the issue starts to spiral out of control.

So, I see 2 issues. One is https://github.com/docker/libnetwork/issues/1374 (note that I do not have live restore enabled). Secondly, when issue https://github.com/docker/libnetwork/issues/1374 happens, the port is never freed.

**Comment by mavenugo** [comment]
@tswift242 Thanks for filing the issue. We fixed it in libnetwork & the next vendor-in to Docker will bring in the fix. (https://github.com/docker/libnetwork/pull/1428)

**Comment by tswift242** [comment]
@mavenugo Thanks! Is anyone looking into https://github.com/docker/libnetwork/issues/1374. That seems to be the root cause of this issue. The issue fixed by https://github.com/docker/libnetwork/pull/1428 is just what perpetuated it.

**Comment by tswift242** [comment]
@mavenugo Thanks again for fixing this so quickly. Wanted on inquire again if anyone is or will be looking at  docker/libnetwork#1374, as that seems to be the root cause.

Also, can docker/libnetwork#1428 be considered for 1.12.2 if it happens? We downgraded from 1.12 to 1.11 as a result of this bug.

**Comment by euforia** [comment]
@tswift242 - I'm in the same boat.  We also ended up reverting back.

In our case not only is the port not freed but sporadically the running service stops responding at which point the system becomes unrecoverable.  Is the sporadic unresponsiveness of the service also related to https://github.com/docker/libnetwork/issues/1374  ?

**Comment by aboch** [comment]
@tswift242 

> Also, can docker/libnetwork#1428 be considered for 1.12.2

Docker 1.12.2 does contain the fix in docker/libnetwork#1428
Docker 1.12.3 will contain the fix in docker/libnetwork/pull/1504

We are looking into mitigating the effects of https://github.com/docker/libnetwork/pull/1374 (just longer timeout), but that will likely make it in 1.13.x only

**Comment by tswift242** [comment]
Thanks for the update @aboch!

**Comment by thaJeztah** [comment]
@aboch should this be added to the 1.13 milestone?

**Comment by ojongerius** [comment]
@thaJeztah will this make it into 1.13? Don't see it in mentioned in [v1.13.0-rc1](https://github.com/docker/docker/releases/tag/v1.13.0-rc1).
