### ISSUE TITLE
docker container works well on docker-engine 1.11.1, but exit with code 139 in version 1.12.1

### ISSUE THREAD

**Issue by darcys** [docker/docker#26263]
Problem:
docker container works well on docker-engine 1.11.1, but exit with 139 in version 1.12.1

**Output of `docker version`:**

docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        
 OS/Arch:      linux/amd64

**Output of `docker info`:**
Containers: 16
 Running: 13
 Paused: 0
 Stopped: 3
Images: 14
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-8:3-26477853-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.225 GB
 Data Space Total: 107.4 GB
 Data Space Available: 104.1 GB
 Metadata Space Used: 2.556 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-229.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 3.673 GiB
Name: xxxx.xxx.com
ID: 5XLZ:KEJQ:OGYX:RI2H:HY52:Z2UY:OFM5:SHRP:AU72:CANG:YJPJ:4CPE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical machine
**Output of `facter `:**
architecture => x86_64
augeasversion => 1.1.0
bios_release_date => 07/11/2013
bios_vendor => Dell Inc.
bios_version => 2.5.1
blockdevice_sda_model => WDC WD5003ABYX-1
blockdevice_sda_size => 500107862016
blockdevice_sda_vendor => ATA
blockdevices => sda
boardmanufacturer => Dell Inc.
boardproductname => 03X6X0
boardserialnumber => ..CN7082134M39FW.
domain => xxxx.com
facterversion => 2.4.1
filesystems => ext2,ext3,ext4,xfs
fqdn => xxxx.xxxx.com
gid => root
hardwareisa => x86_64
hardwaremodel => x86_64
hostname => xxxx.xxxx
id => root
interfaces => bond0,bond0_0,bond0_1,bond0_2,docker0,em1,em2,lo,veth218c873,veth381ae01,vethf70d6a1
ipaddress => 165.254.88.77
ipaddress_bond0 => 165.254.88.77
ipaddress_bond0_0 => 165.254.88.78
ipaddress_bond0_1 => 165.254.88.79
ipaddress_bond0_2 => 165.254.88.80
ipaddress_docker0 => 172.17.0.1
ipaddress_lo => 127.0.0.1
is_virtual => false
kernel => Linux
kernelmajversion => 3.10
kernelrelease => 3.10.0-229.el7.x86_64
kernelversion => 3.10.0
macaddress => d4:ae:52:cb:52:a4
macaddress_bond0 => d4:ae:52:cb:52:a4
macaddress_bond0_0 => d4:ae:52:cb:52:a4
macaddress_bond0_1 => d4:ae:52:cb:52:a4
macaddress_bond0_2 => d4:ae:52:cb:52:a4
macaddress_docker0 => 02:42:59:76:13:d7
macaddress_em1 => D4:AE:52:CB:52:A3
macaddress_em2 => D4:AE:52:CB:52:A4
macaddress_veth218c873 => 7e:3f:df:5d:ef:6b
macaddress_veth381ae01 => ea:4e:26:ad:d6:32
macaddress_vethf70d6a1 => 9a:35:9e:4f:2b:99
manufacturer => Dell Inc.
memoryfree => 3.02 GB
memoryfree_mb => 3096.82
memorysize => 3.67 GB
memorysize_mb => 3761.50
mtu_bond0 => 1500
mtu_bond0_0 => 1500
mtu_bond0_1 => 1500
mtu_bond0_2 => 1500
mtu_docker0 => 1500
mtu_em1 => 1500
mtu_em2 => 1500
mtu_lo => 65536
mtu_veth218c873 => 1500
mtu_veth381ae01 => 1500
mtu_vethf70d6a1 => 1500
netmask => 255.255.255.0
netmask_bond0 => 255.255.255.0
netmask_bond0_0 => 255.255.255.0
netmask_bond0_1 => 255.255.255.0
netmask_bond0_2 => 255.255.255.0
netmask_docker0 => 255.255.0.0
netmask_lo => 255.0.0.0
network_bond0 => 165.254.88.0
network_bond0_0 => 165.254.88.0
network_bond0_1 => 165.254.88.0
network_bond0_2 => 165.254.88.0
network_docker0 => 172.17.0.0
network_lo => 127.0.0.0
operatingsystem => CentOS
operatingsystemmajrelease => 7
operatingsystemrelease => 7.1.1503
os => {"name"=>"CentOS", "family"=>"RedHat", "release"=>{"major"=>"7", "minor"=>"1", "full"=>"7.1.1503"}}
osfamily => RedHat
partitions => {"sda1"=>{"uuid"=>"9441904a-85d5-456c-8770-49497a0bede5", "size"=>"409600", "mount"=>"/boot", "filesystem"=>"ext4"}, "sda2"=>{"uuid"=>"9ae2f844-2341-40a9-a368-dc6eef6e84f4", "size"=>"32964608", "filesystem"=>"swap"}, "sda3"=>{"uuid"=>"d625800b-6bf0-4c0e-a18a-0a36827f4718", "size"=>"943396864", "mount"=>"/", "filesystem"=>"ext4"}}
path => /usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
physicalprocessorcount => 1
processor0 => Intel(R) Xeon(R) CPU E3-1270 V2 @ 3.50GHz
processor1 => Intel(R) Xeon(R) CPU E3-1270 V2 @ 3.50GHz
processor2 => Intel(R) Xeon(R) CPU E3-1270 V2 @ 3.50GHz
processor3 => Intel(R) Xeon(R) CPU E3-1270 V2 @ 3.50GHz
processor4 => Intel(R) Xeon(R) CPU E3-1270 V2 @ 3.50GHz
processor5 => Intel(R) Xeon(R) CPU E3-1270 V2 @ 3.50GHz
processor6 => Intel(R) Xeon(R) CPU E3-1270 V2 @ 3.50GHz
processor7 => Intel(R) Xeon(R) CPU E3-1270 V2 @ 3.50GHz
processorcount => 8
processors => {"models"=>["Intel(R) Xeon(R) CPU E3-1270 V2 @ 3.50GHz", "Intel(R) Xeon(R) CPU E3-1270 V2 @ 3.50GHz", "Intel(R) Xeon(R) CPU E3-1270 V2 @ 3.50GHz", "Intel(R) Xeon(R) CPU E3-1270 V2 @ 3.50GHz", "Intel(R) Xeon(R) CPU E3-1270 V2 @ 3.50GHz", "Intel(R) Xeon(R) CPU E3-1270 V2 @ 3.50GHz", "Intel(R) Xeon(R) CPU E3-1270 V2 @ 3.50GHz", "Intel(R) Xeon(R) CPU E3-1270 V2 @ 3.50GHz"], "count"=>8, "physicalcount"=>1}
productname => PowerEdge R210 II
ps => ps -ef
rubyplatform => x86_64-linux
rubysitedir => /usr/local/share/ruby/site_ruby/
rubyversion => 2.0.0
selinux => true
selinux_config_mode => permissive
selinux_config_policy => unknown
selinux_current_mode => permissive
selinux_enforced => false
selinux_policyversion => 28
serialnumber => H4SW9Y1
swapfree => 15.72 GB
swapfree_mb => 16095.77
swapsize => 15.72 GB
swapsize_mb => 16096.00
system_uptime => {"seconds"=>63310, "hours"=>17, "days"=>0, "uptime"=>"17:35 hours"}
timezone => GMT
type => Rack Mount Chassis
uniqueid => fea54d58
uptime => 17:35 hours
uptime_days => 0
uptime_hours => 17
uptime_seconds => 63310
uuid => 4C4C4544-0034-5310-8057-C8C04F395931
virtual => physical

docker container info:
**Output of `docker inspect tssdd_165.254.88.79 `:**
[root@mxxxz_sc_app1_r2_svr7 bin]# docker inspect tssdd_165.254.88.79
[
    {
        "Id": "0421b2faaca6d362ea18d80fbac0cb18ae2c30cb09f00b63d54512e74739583b",
        "Created": "2016-09-01T09:08:39.2412597Z",
        "Path": "/opt/ssb/bin/tssdd",
        "Args": [],
        "State": {
            "Status": "restarting",
            "Running": true,
            "Paused": false,
            "Restarting": true,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 139,
            "Error": "",
            "StartedAt": "2016-09-02T02:37:20.660756571Z",
            "FinishedAt": "2016-09-02T02:37:20.910047087Z"
        },
        "Image": "sha256:5c56264c19c9e1b5d9601de90b81bb69a2c719cc3a62234c714eac1398ac4064",
        "ResolvConfPath": "/var/lib/docker/containers/0421b2faaca6d362ea18d80fbac0cb18ae2c30cb09f00b63d54512e74739583b/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/0421b2faaca6d362ea18d80fbac0cb18ae2c30cb09f00b63d54512e74739583b/hostname",
        "HostsPath": "/var/lib/docker/containers/0421b2faaca6d362ea18d80fbac0cb18ae2c30cb09f00b63d54512e74739583b/hosts",
        "LogPath": "/var/lib/docker/containers/0421b2faaca6d362ea18d80fbac0cb18ae2c30cb09f00b63d54512e74739583b/0421b2faaca6d362ea18d80fbac0cb18ae2c30cb09f00b63d54512e74739583b-json.log",
        "Name": "/tssdd_165.254.88.79",
        "RestartCount": 13,
        "Driver": "devicemapper",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/etc:/etc:ro",
                "/opt/ssb/conf/tssdd_165.254.88.79:/opt/ssb/conf:rw",
                "/lib64:/lib64:ro",
                "/lib:/lib:ro",
                "/opt/ssb/core/tssdd_165.254.88.79:/opt/ssb/core:rw",
                "/opt/ssb/logs/tssdd_165.254.88.79:/opt/ssb/logs:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "host",
            "PortBindings": null,
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Name": "devicemapper",
            "Data": {
                "DeviceId": "311",
                "DeviceName": "docker-8:3-26477853-403946660a1c87fc19f907d0a58b403880f233ae605b54e1cd48949f0e33a6c5",
                "DeviceSize": "10737418240"
            }
        },
        "Mounts": [
            {
                "Source": "/etc",
                "Destination": "/etc",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Source": "/lib",
                "Destination": "/lib",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Source": "/lib64",
                "Destination": "/lib64",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Source": "/opt/ssb/conf/tssdd_165.254.88.79",
                "Destination": "/opt/ssb/conf",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Source": "/opt/ssb/core/tssdd_165.254.88.79",
                "Destination": "/opt/ssb/core",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Source": "/opt/ssb/logs/tssdd_165.254.88.79",
                "Destination": "/opt/ssb/logs",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "mxxxz_sc_app1_r2_svr7.mxxxz.us",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/opt/ssb/bin/tssdd"
            ],
            "Image": "docker-registry.mxxxz.us:5000/tssdd:3.6.60872.0809.0d1ea9b",
            "Volumes": {
                "/etc": {},
                "/lib": {},
                "/lib64": {},
                "/opt/ssb/conf": {},
                "/opt/ssb/core": {},
                "/opt/ssb/logs": {}
            },
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "d48520cc2d5a07360d4f5a44f6e0d6973287abdfdf9b9f87bd3bffa0691afb88",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/default",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "host": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "7c67c5f7ab539ef6b2068a6112b20cbda2294e3f2e553564644cb349677d867a",
                    "EndpointID": "d336e7fda01a8a7702966c0eab2e1b610d38946a4fbdc5d3208fefe86eb04a32",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": ""
                }
            }
        }
    }
]
[root@mxxxz_sc_app1_r2_svr7 bin]# 

**Steps to reproduce the issue:**
1. yum update docker-engine (from 1.11.1 to 1.12.1)

**Describe the results you received:**
docker container tssdd status is "Restarting (139) 35 seconds ago     " 
error log in  /var/log/message
 kernel: traps: tssdd[7213] general protection ip:f73f3f81 sp:f43f97d0 error:0 in libc-2.17.so[f73c4000+1b7000]

**Describe the results you expected:**
container started normally

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by justincormack** [comment]
That error is in the program running in the container, so it seems like it is probably not related to docker. Does it make any difference if you run it with `--security-opt seccomp=unconfined`?

**Comment by thaJeztah** [comment]
closing because it looks like the discussion stalled, but feel free to continue the discussion
