### ISSUE TITLE
Don't display 3 fractional digits when showing sizes (confusion)

### ISSUE THREAD

**Issue by skrysmanski** [docker/docker#26300]
Currently (Docker 1.12.1), calling `docker images` may show something like this:

```
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
ipxe-http-server-base         latest              8f2d7cebda98        6 minutes ago       6.141 MB
```

Here, the image size is reported with 3 fractional digits (i.e. `141`).

I'm a German developer. In Germany, the dot `.` is used as thousands-separator in number (equivalent to the `,` in English).

While I have set up my operating system to display English texts, my input locale is German. Due to this, at least on Windows, the locale for number formats becomes German as well. 

I know that, at least on Windows, the locale used for number formatting in applications depends on the "framework" being used. So, just looking at the output above I can't be sure whether `6.141 MB` means roughly 6 MB or 6 GB (i.e. `6,141 MB`).

This ambiguity is introduced by the fact that the size is shown with **3 fractional digits**. If it used just 2 or 4 fractional digits (e.g. `6.14 MB`), there would be no ambiguity.

So, my feature request here is to improve usability by never using 3 fractional digits (but 2 or 4 or ...).

I know this issue may be a corner case but it would get more important if Docker ever decided to honor number format locales on operating systems that distinguish between OS language and number formats (like Windows or OS X; not sure about Linux).

**Comment by yongtang** [comment]
The `size` in `images` was handled by `units.HumanSize()` which always display 4 digit precision:
https://github.com/docker/docker/blob/fc63bb83caea1baf4d3818b1c8c59f83e9db6f81/vendor/src/github.com/docker/go-units/size.go#L52-L56

I think an easy fix for this issue is to use `CustomSize()` directly but with 3 digit precision (so that no `x.yyy`) case.

**Comment by yongtang** [comment]
@skrysmanski See #26303 for pull request.
