### ISSUE TITLE
SSH error when starting default docker machine.

### ISSUE THREAD

**Issue by mikegomezg** [docker/docker#26319]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.17-boot2docker
Operating System: Boot2Docker 1.12.1 (TCL 7.2); HEAD : ef7d0b4 - Thu Aug 18 21:18:06 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: default
ID: DVZB:5C7X:BCVJ:3LN4:675Q:MVAP:HVSU:EJ46:COGD:BHNW:HHOW:KU4F
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 14
 Goroutines: 23
 System Time: 2016-09-05T14:27:13.055243253Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I have tried these two versions of VirtualBox, but I have the same problem on both:

Version 5.0.26
Version 5.1.5

**Steps to reproduce the issue:**
1. Install Docker Toolbox for OSX
2. Run quickstart
3. Error always occurs for me

**Describe the results you received:**

When I run the quickstart after a fresh install of Docker and Virtualbox, the quickstart process stalls at the 'Waiting for an IP' stage. If I stop the default machine and then try to start it again, the same problem occurs. 

It appears to have to do with SSH. After three failed attempts, the command apparently succeeds.

(default) Waiting for an IP...
(default) DBG | Getting to WaitForSSH function...
(default) DBG | Using SSH client type: external
(default) DBG | Using SSH private key: /Users/mikegomez/.docker/machine/machines/default/id_rsa (-rw-------)
(default) DBG | &{[-F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@127.0.0.1 -o IdentitiesOnly=yes -i /Users/mikegomez/.docker/machine/machines/default/id_rsa -p 50987] /usr/bin/ssh <nil>}
(default) DBG | About to run SSH command:
(default) DBG | exit 0
(default) DBG | SSH cmd err, output: exit status 255: 
(default) DBG | Error getting ssh command 'exit 0' : Something went wrong running an SSH command!
(default) DBG | command : exit 0
(default) DBG | err     : exit status 255
(default) DBG | output  : 
(default) DBG | 
(default) DBG | Getting to WaitForSSH function...
(default) DBG | Using SSH client type: external
(default) DBG | Using SSH private key: /Users/mikegomez/.docker/machine/machines/default/id_rsa (-rw-------)
(default) DBG | &{[-F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@127.0.0.1 -o IdentitiesOnly=yes -i /Users/mikegomez/.docker/machine/machines/default/id_rsa -p 50987] /usr/bin/ssh <nil>}
(default) DBG | About to run SSH command:
(default) DBG | exit 0
(default) DBG | SSH cmd err, output: exit status 255: 
(default) DBG | Error getting ssh command 'exit 0' : Something went wrong running an SSH command!
(default) DBG | command : exit 0
(default) DBG | err     : exit status 255
(default) DBG | output  : 
(default) DBG | 
(default) DBG | Getting to WaitForSSH function...
(default) DBG | Using SSH client type: external
(default) DBG | Using SSH private key: /Users/mikegomez/.docker/machine/machines/default/id_rsa (-rw-------)
(default) DBG | &{[-F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@127.0.0.1 -o IdentitiesOnly=yes -i /Users/mikegomez/.docker/machine/machines/default/id_rsa -p 50987] /usr/bin/ssh <nil>}
(default) DBG | About to run SSH command:
(default) DBG | exit 0
(default) DBG | SSH cmd err, output: <nil>: 
(default) DBG | COMMAND: /usr/local/bin/VBoxManage showvminfo default --machinereadable

**Describe the results you expected:**

I expected the machine to start up more quickly.

**Additional information you deem important (e.g. issue happens only occasionally):**

I have tried removing and then recreating the default machine. I have uninstalled and reinstalled both VirtualBox and Docker.

**Comment by mikegomezg** [comment]
https://gist.github.com/mikegomezg/5de744d60b778c475a57ad9dd7f8209e

**Comment by vieux** [comment]
@mikegomezg can you please open your issue on https://github.com/docker/machine

/cc @nathanleclaire
