### ISSUE TITLE
Windows: Mounting of single file does not work

### ISSUE THREAD

**Issue by rstropek** [docker/docker#26329]
# Environment

* Windows Server 2016 Technical Preview 5 running in Azure (I am using the ready-made VM that Azure provides)
* Docker host has a directory `c:\config` containing a text file `test-rainer.txt`.

# Repro

Execute Docker CLI command: `docker run -it --rm -v c:\config\test-rainer.txt microsoft/windowsservercore cmd /c "type c:\config\test-rainer.txt"`

Expected behavior: Print content of the file

Actual behavior: `Access is denied`

# Additional information

The command `docker run -it --rm -v c:\config\test-rainer.txt microsoft/windowsservercore cmd /c "dir c:\config"` results in the following output (note that the file has become a directory):

```
 Volume in drive C has no label.
 Volume Serial Number is CCF3-F517

 Directory of c:\config

09/06/2016  09:28 AM    <DIR>          .
09/06/2016  09:28 AM    <DIR>          ..
09/06/2016  09:28 AM    <SYMLINKD>     test-rainer.txt [\\?\ContainerMappedDirectories\22EF2CEE-0A37-47C1-9085-1F43508BC444]
               0 File(s)              0 bytes
               3 Dir(s)  21,254,266,880 bytes free
```

If you run `docker run -it --rm -v c:\config\test-rainer.txt microsoft/windowsservercore cmd /c "dir c:\config\test-rainer.txt"` you get:

```
 Volume in drive C has no label.
 Volume Serial Number is CCF3-F517

 Directory of c:\config\test-rainer.txt

09/06/2016  09:29 AM    <DIR>          .
09/06/2016  09:29 AM    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)  104,884,604,928 bytes free
```

Here is the output of `docker info` in case detailed configuration is needed for repro:

```
Containers: 7
 Running: 5
 Paused: 0
 Stopped: 2
Images: 18
Server Version: 1.12.0
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Security Options:
Kernel Version: 10.0 14300 (14300.1045.amd64fre.rs1_release_svc.160705-1059)
Operating System: Windows Server 2016 Datacenter Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 14 GiB
Name: docker-training
ID: FM6R:LMFB:NWYI:ZE6D:4VDI:DSKA:E5WM:CYBX:E5MW:VVGO:QMT5:EPV3
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Username: rstropek
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Comment by justincormack** [comment]
I thought this was documented somewhere, although I cant find it right now. Windows cannot mount single files, and it is fairly problematic under Linux for many use cases.

cc @jhowardmsft

**Comment by jhowardmsft** [comment]
Yes, correct, this is by design even on post TP5 builds. @neilpeterson If not already (I couldn't immediately see it), can we document this? Applies to both Windows Server and Hyper-V containers. I might also see if it's easy to knock together a PR to give a better error.

**Comment by jhowardmsft** [comment]
Even stranger - something has regressed. It should have been caught by https://github.com/docker/docker/blob/master/volume/volume_windows.go#L176.

**Comment by neilpeterson** [comment]
Docs updated - https://msdn.microsoft.com/en-us/virtualization/windowscontainers/management/manage_data#mount-single-files

If by design and a long term limitation we may want to also update this:

https://docs.docker.com/engine/tutorials/dockervolumes/#/mount-a-host-file-as-a-data-volume

cc @enderb-ms

**Comment by rstropek** [comment]
Thank you very much for the clarification. The docs previously mentioned that mounting a single file should work. Now the limitation is clear and the workaround with the folder is perfectly fine.
