### ISSUE TITLE
inspect container does not show ulimit value if start daemon with --default-ulimit

### ISSUE THREAD

**Issue by BrickXu** [docker/docker#26326]
**Output of `docker version`:**
```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**
```
Containers: 9
 Running: 9
 Paused: 0
 Stopped: 0
Images: 17
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker_vg-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 7.661 GB
 Data Space Total: 171.8 GB
 Data Space Available: 164.1 GB
 Metadata Space Used: 3.879 MB
 Metadata Space Total: 10.73 GB
 Metadata Space Available: 10.73 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: none
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 3.10.0-327.22.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 125.8 GiB
Name: <securty>
ID: DMQL:D4O3:BULA:5ALE:W2QV:NCEN:ZOVU:KCDR:FB6P:5RLU:E4C6:RD2V
Docker Root Dir: /home/q/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical 

**Steps to reproduce the issue:**

1. start daemon with option `--default-ulimit=nofile=65535`
2. start a container, named "A"
3. `docker inspect -f {{.HostConfig.Ulimits}} A`
4. start another container named B via `docker run --ulimit nofile=65535 xxxxxx` 
5. `docker inspect -f {{.HostConfig.Ulimits}} B`

**Describe the results you received:**
From the step 3, inspect A gives `[]`, and the step 5, inspect B gives `[nofile=65535:65535]`.

**Describe the results you expected:**
`inspect` should automatically detected default options which extends from daemon command line, and show them if they did not overwrite by `docker run`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by allencloud** [comment]
I think it is a good idea to make users know container's ulimit details even if user does not specify the corresponding configs and container uses daemon's default settings.

**Comment by yongtang** [comment]
Added a pull request #26405 to fix this issue.

**Comment by allencloud** [comment]
I was wondering is there any other configs in the daemon side while also in the container's hostconfig. @yongtang

**Comment by yongtang** [comment]
@allencloud `log-driver/log-opt` is the one. Was handled sometime ago I remember.

**Comment by allencloud** [comment]
Thanks @yongtang 
I think that could be, too.

**Comment by BrickXu** [comment]
Thanks @yongtang  @allencloud !
