### ISSUE TITLE
Docker service create --constraint are not honored everywhere

### ISSUE THREAD

**Issue by outcoldman** [docker/docker#26325]
Starting from simple example

```
ID                           HOSTNAME  STATUS  AVAILABILITY  MANAGER STATUS
2v0j79opy6j0gjbmmz8bybke5    splunk2   Ready   Active        
6ly89ymb24x6k7nwd5jldul4k *  splunk0   Ready   Active        Leader
6pylpant0ywrzqpkyohvz5p35    splunk1   Ready   Active        
ck8kvxez9kf1e4zmafy9caik7    splunk3   Ready   Active 
```

Where `splunk0` is the only manager role.

I have a service with constraint  `node.role != manager` and mode == `global`.

When I do `service ps` I see that `splunk0` has a service task on node `splunk0` with state `Shutdown`. And the worse part if I try to update the image - it stuck I guess because it waits when this ghost task will be updated on node `splunk0`. When I do `docker ps -a` I do not see the container on this node.

Possible that load balancing also not always exclude nodes where this service should not deploy tasks.

**Comment by vieux** [comment]
@dongluochen can you please take a look ?

**Comment by dongluochen** [comment]
@outcoldman It's a bug on service update for global service which doesn't fit a node. 

When you start your global service, on those nodes that do not satisfy constraint, the tasks' `current state` should be `Allocated` (not `Shutdown`, you may see `Shutdown` after you issue an update command). Docker daemon on these nodes doesn't see the task so they would not start any container. 

When you update service image, the updater changes image for a task and waits for it to start up. But updater doesn't know some tasks cannot start. It keeps on waiting. 

```
ubuntu@ip-172-19-241-145:~$ docker node ls
ID                           HOSTNAME           STATUS  AVAILABILITY  MANAGER STATUS
3tartrjra8xr1uy482gwnk00p    ip-172-19-241-146  Ready   Active
49xd9g9kahy6jtruk4bcq3jxm    ip-172-19-241-144  Ready   Active        Leader
ebotiiobwcoxttvkj3o75m4ar *  ip-172-19-241-145  Ready   Active        Reachable
ubuntu@ip-172-19-241-145:~$ docker service ls
ID            NAME             REPLICAS  IMAGE               COMMAND
6smnrwnehbom  ecstatic_jepsen  global    dongluochen/nctest
ubuntu@ip-172-19-241-145:~$ docker service ps ecstatic_jepsen
ID                         NAME                 IMAGE               NODE               DESIRED STATE  CURRENT STATE                 ERROR
87gr19jqdxfochf4ujn7fktng  ecstatic_jepsen      dongluochen/nctest  ip-172-19-241-146  Running        Running 6 seconds ago
4jtsluug9muw25icif7ff5upu   \_ ecstatic_jepsen  dongluochen/nctest  ip-172-19-241-145  Running        Allocated about a minute ago
4utjl8q0t8weswxu95z33zpcp   \_ ecstatic_jepsen  dongluochen/nctest  ip-172-19-241-144  Running        Allocated about a minute ago
```

cc @aaronlehmann.

**Comment by aaronlehmann** [comment]
ping @aluzzardi any thoughts on the right way to fix this?

**Comment by aluzzardi** [comment]
Seems to be multiple issues.

The global orchestrator should honor constraints directly and not rely on the scheduler, I'm afraid. It shouldn't be too hard so long as the filter package is properly separated from the scheduler.

Before doing that, however, this issue seems to be surfacing other underlying bugs.

The updated should never get stuck - there's an upper bound timeout (60 seconds?). There's a bug there and since it's hard to repro in normal conditions I'd probably start by adding a test around stuck updates before trying to do anything with global.

From my phone so I didn't quite catch if there where actual/desired state issues.

**Comment by aaronlehmann** [comment]
@aluzzardi: There is no timeout:

```go
        // Wait for the new task to come up.
        // TODO(aluzzardi): Consider adding a timeout here.
        for {
                select {
                case e := <-taskUpdates:
                        updated = e.(state.EventUpdateTask).Task
                        if updated.Status.State >= api.TaskStateRunning {
                                return nil
                        }
                case <-u.stopChan:
                        return nil
                }
        }
```

**Comment by dongluochen** [comment]
@aaronlehmann and I discussed this problem and here are some changes we have in mind. 
 
Constraint validation function could be separated from scheduler so components may check it any time. Global orchestrator checks constraints and not create the task if a node doesn't satisfy the constraint. (We need to be careful not to trigger unnecessary reconciliation.) Updater should check constraints when updating tasks. A service update may update constraints so tasks previously running may not run now. 

When a node gets updated, all global services should be re-evaluated for this node. All replicated tasks running on the node should be re-evaluated to be continue or stop. This would trigger reconciliation. Reconciliation code may need refactoring.

**Comment by aluzzardi** [comment]
That's just a special case of node update

**Comment by thaJeztah** [comment]
@aaronlehmann anything left to do on this one? I see the SwarmKit PR was merged; not sure it was vendored, and if additional changes were needed

**Comment by aaronlehmann** [comment]
Should be all done.
