### ISSUE TITLE
[Meta] A "docker deploy" roadmap needed

### ISSUE THREAD

**Issue by techninja1008** [docker/docker#26327]
Someone probably needs to start a roadmap issue for getting a solution to current problems with "docker deploy" (ie. where the feature is planned to go) because so far, I cannot find anything, let alone an issue, describing current progress.

Including:

- `docker deploy`
- `docker stacks`
- The planned relation between Swarm Mode / Docker Compose / `docker deploy`
- The planned file formats

**Comment by icecrime** [comment]
Ping @mgoelzer!

**Comment by mgoelzer** [comment]
@icecrime I'm on it!

**Comment by techninja1008** [comment]
Any Progress?

**Comment by busbyjon** [comment]
👍

**Comment by mgoelzer** [comment]
@techninja1008 @busbyjon Not forgotten, but not quite ready yet.  It's coming.

**Comment by mgoelzer** [comment]
Roadmap posted in #26876
