### ISSUE TITLE
Relative to path for Docker volume

### ISSUE THREAD

**Issue by kgsudhakar** [docker/docker#26339]
I have mongo DB in docker and trying to mount the mongo DB data volume in a absolute path in docker compose file like this.

`volumes:
     - /usr/data/mongodb:/data/db`

I am sure this wont work in all operating system if its tries to create or find path /usr/data/mongodb . How to give the relative path so that it will fit for all operating system including windows. Any path which will work in all operating system is good for me. 

as docker creates /var/lib/docker in Mac and Linux, I am thinking about choosing this path in relative way so that same thing will apply for windows also. Please help me to sort out this issue.

**Comment by CrimsonGlory** [comment]
In compose you can use relatives path (relatives to the docker-compose.yml file).
Like this:
```
db:
  image: mongo:3.2
  volumes:
    - ../mongo-data/:/data/db
```
(from [this example](https://github.com/codexgigassys/codex-backend/blob/master/docker-compose.yml))

**Comment by cpuguy83** [comment]
Closing since compose already supports relative paths.
BTW, compose has a separate repo, github.com/docker/compose.

Thanks!
