### ISSUE TITLE
docker build fails upon resolving host

### ISSUE THREAD

**Issue by rzwpgc** [docker/docker#26330]
I am running Ubuntu 16.04 as a virtual machine on Oracle Virtual Box (main host is Windows 7).
I am having the problem that inside of docker, hostnames cannot be resolved, so I cannot "docker build" (please see example below).
I tried different solutions found here, for example rebuilding docker0, adding the resolv.conf nameserver to /etc/default/docker -> DOCKER_OPTS, none of them worked until now.

Using docker:
docker run -it debian:7.7 bash -c 'ping http.debian.net'
ping: unknown host
docker can ping the IP address of http.debian.net
docker run -it debian:7.7 bash -c 'ping archive.ubuntu.com'
ping: unknown host
docker can ping the IP address of archive.ubuntu.com

Using the ubuntu machine "ping http.debian.net" and "ping archive.ubuntu.com" also works. lxc is not installed.

The docker build failure I experience:
docker build --no-cache -t "XXXXX" .

Sending build context to Docker daemon 450.2 MB
Step 1 : FROM ubuntu:16.04
 ---> bd3d4369aebc
Step 2 : RUN apt-get update -q -q
 ---> Running in 9d5bb3f82949
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-security/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
 ---> 704bea847534
Removing intermediate container 9d5bb3f82949
Step 3 : RUN apt-get upgrade --yes
 ---> Running in 23a2ed8934a6
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
 ---> db1b314d0070
Removing intermediate container 23a2ed8934a6
Step 4 : RUN apt-get install less screen --yes
 ---> Running in 5fb5a6753ab9
Reading package lists...
Building dependency tree...
Reading state information...
Package less is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'less' has no installation candidate
E: Unable to locate package screen
The command '/bin/sh -c apt-get install less screen --yes' returned a non-zero code: 100

docker --version
Docker version 1.12.1, build 23cf638

uname -a
Linux Ubuntu1604 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

docker info
Containers: 47
 Running: 1
 Paused: 0
 Stopped: 46
Images: 13
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 115
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay null bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-36-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 7.797 GiB
Name: Ubuntu1604
ID: AF5K:7IPA:NOMF:TCLN:MPUW:HEAH:X5NG:TSNB:DZYL:EWSK:BPPF:GVSH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
 
cat resolv.conf (host)
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 127.0.1.1
search ad.XXX.com
 
 
 ifconfig
docker0   Link encap:Ethernet  HWaddr 02:42:96:da:57:20  
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:96ff:feda:5720/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:161 errors:0 dropped:0 overruns:0 frame:0
          TX packets:76 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:10400 (10.4 KB)  TX bytes:7397 (7.3 KB)

enp0s3    Link encap:Ethernet  HWaddr 08:00:27:a7:fa:5a  
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::d062:a3f9:2997:adb6/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:130 errors:0 dropped:0 overruns:0 frame:0
          TX packets:342 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:15726 (15.7 KB)  TX bytes:30208 (30.2 KB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:201 errors:0 dropped:0 overruns:0 frame:0
          TX packets:201 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:16424 (16.4 KB)  TX bytes:16424 (16.4 KB)

vethf8eee5a Link encap:Ethernet  HWaddr 92:ec:00:14:67:a3  
          inet6 addr: fe80::90ec:ff:fe14:67a3/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:35 errors:0 dropped:0 overruns:0 frame:0
          TX packets:40 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:2706 (2.7 KB)  TX bytes:4188 (4.1 KB)

**Comment by rzwpgc** [comment]
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
search ad.syniverse.com

nameserver 8.8.8.8
nameserver 8.8.4.4

**Comment by rzwpgc** [comment]
docker run -it --rm ubuntu:16.04 bash -c 'cat /etc/resolv.conf':
search ad.syniverse.com

nameserver 8.8.8.8
 nameserver 8.8.4.4

**Comment by rzwpgc** [comment]
Solved by dns mask disable:
sudo vim /etc/NetworkManager/NetworkManager.conf
comment out dns=dnsmasq -> #dns=dnsmasq
sudo service network-manager restart (or reboot VM in this case)

**Comment by kennethz3** [comment]
@rzwpgc it worked. Thank you

**Comment by mtomov** [comment]
@rzwpgc thank you! Had the problem without reference to this project.

**Comment by anitagov** [comment]
Thanks @rzwpgc. This worked for me.

**Comment by shrgupta7692** [comment]
Thanks @rzwpgc for the solution.
