### ISSUE TITLE
docker does not correctly parse the proxy information when the user's password has a '#' symbol

### ISSUE THREAD

**Issue by shishir-a412ed** [docker/docker#26338]
**Output of `docker version`:**

```
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.6
 Git commit:   d8e12f8
 Built:        Wed Aug 17 15:32:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.6
 Git commit:   d8e12f8
 Built:        Wed Aug 17 15:32:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.13.0-dev
Storage Driver: devicemapper
 Pool Name: docker-8:19-16253827-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 5.369 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 11.16 GB
 Data Space Total: 107.4 GB
 Data Space Available: 96.22 GB
 Metadata Space Used: 6.324 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.141 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.109 (2015-09-22)
Logging Driver: journald
Cgroup Driver: systemd
Plugins: 
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: selinux
Kernel Version: 4.6.4-201.fc23.x86_64
Operating System: Fedora 23 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.72 GiB
Name: dhcp-10-19-62-127.boston.devel.redhat.com
ID: M4W2:KN7L:WVHC:KGXZ:ZNAN:CJJJ:5PWS:V7VV:GPHO:65Y3:4UEP:MCUX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http:// admin : admin # 1 @10.18.17.163:3128/
Username: shm32
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora 23

**Steps to reproduce the issue:**
1. Setup a local proxy server. I used squid proxy.
2. Add basic authentication (username, password) to squid proxy server. Choose a password with a `#` symbol in it.
3. systemctl start squid
4. systemctl stop docker (if docker is running)
5. Update the systemd unit file `/usr/lib/systemd/system/docker.service` with 
    Environment="HTTP_PROXY=http://< username >:< password >@< proxy-ip >:< proxy-port >/"
   Here proxy-ip should be your Host IP, and proxy-port should be 3128.  Add under [Service] section.
6. systemctl daemon-reload
7. systemctl start docker
8. docker pull fedora 

Error message: Using default tag: latest
Pulling repository docker.io/library/fedora
Error while pulling image: Get https://index.docker.io/v1/repositories/library/fedora/images: http: error connecting to proxy http://admin:admin#1@10.18.17.163:3128/: dial tcp: lookup tcp/admin: Servname not supported for ai_socktype

**Describe the results you received:**
Error message above ^^

**Describe the results you expected:**
Docker would parse the user's password correctly, and the docker pull command works 

**Additional information you deem important (e.g. issue happens only occasionally):**
Note: This works fine if I set a password with no `#` symbol in it. This is not the problem with other applications.

e.g. export http_proxy=http://< username > : < password with `#`>@< proxy-ip >:3128/"
       curl http://www.google.com
  
The above works successfully.

**Comment by vieux** [comment]
@shishir-a412ed do you have any other tool in go you can test with ? 
I don't see anything specific in docker about proxy parsing, I'm wondering if it's from golang.

**Comment by cpuguy83** [comment]
Yeah, we just set a field in the http transport `ProxyFromEnvironment` and go takes care of the rest, I believe. So probably in go.

**Comment by shishir-a412ed** [comment]
@vieux @cpuguy83 Thanks ! this is not an issue with docker or golang. 
Input (`http_proxy` environment variable) needs to be encoded correctly.

Shishir
