### ISSUE TITLE
Feature request:  improvements to surface more networking information

### ISSUE THREAD

**Issue by mgoelzer** [docker/docker#26351]
Sometimes people have sporadic problem with swarm-mode overlay networking, and it is difficult to debug these issues (even with logs) because we don't have a lot of information on the states of their clusters.

Below are a few ideas from a recent meeting on code checks and output we could add to make these situations easier to debug:

For routing mesh not working on startup:
- check ipvs actually enabled on all nodes' kernels
- check firewalld, ufw
- generally adapt overlay so that it works correctly with common firewalls

For routing mesh just failing over time for no reason:
- surface the gossip state in `docker info`
- log dump of service-level information (what nodes its on, each node's ipvs state, etc)

Other ideas:
- `docker service --loadbalancer ps` - would show all the backing instances behind a VIP

**Comment by thaJeztah** [comment]
Also see https://github.com/docker/docker/issues/27307 for metrics (perhaps networking should be added in the metrics)

We could still have a check to see if IPVS/requirements are working correctly; can you open a new issue for that?
