### ISSUE TITLE
"No such file or directory" during I/O bound app initialization on 32 core RHEL7

### ISSUE THREAD

**Issue by 5tefan** [docker/docker#26358]
This appears to be related to #7084 which has been buried. 

**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 27
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-202:2-2600468885-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.494 GB
 Data Space Total: 107.4 GB
 Data Space Available: 104.9 GB
 Metadata Space Used: 4.051 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.143 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.18.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 239.8 GiB
Name: beef
ID: ZCZZ:KPYN:OYUM:HOZ3:DPUO:NDOY:I2DY:MJK3:T63W:5AK7:U373:QOKG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Labels:
 provider=generic
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This is an AWS r3.8xlarge instance running RHEL 7, provisioned with docker-machine generic driver.  

**Steps to reproduce the issue:**
1. Image built from gcc:5.2.0
2. `eval $(docker-machine env beef)`
3. `docker build -t filter .`
4. `docker run -it --rm -v /home/stefan/run_area:/run_area filter`

**Describe the results you received:**
Continuously printed to cerr:
```
ncgen: No such file or directory
        (genbin.c:59)
```

**Describe the results you expected:**
Expected these initial files to be created, see additional information for a more detailed description.

**Additional information you deem important (e.g. issue happens only occasionally):**

This code tries to create 200 files during initialization by calling an external program which reads a template and creates an initial file. A variable number of these, under ~20 are successfully created and then it prints lots of "No such file or directory" errors (way more than 200). The source of the error is during the creation (write) of the initial files, not reading the template. [This source line](https://github.com/Unidata/netcdf-c/blob/18f4bca367140fc05be78287da26a34ebc3d9286/ncgen/genbin.c#L59) is where the error is occurring. Possibly relevant is also that both the template and the resulting files are in a directory that is mounted from the host with -v (run_area from steps to reproduce).

The previous issue #7084 was a big vague on the details, but these writes are not parallelized. This initialization (the write) occurs only on one thread in a loop. The detail though, is that the loop is supposed to fork after the file is written.

**Comment by LK4D4** [comment]
@rhvgoyal do you think it might be related to devicemapper?
@5tefan I wonder if you can try the same thing with some other graphdriver.

**Comment by 5tefan** [comment]
@LK4D4 Sure, you mean [configure direct-lvm](https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#/configure-direct-lvm-mode-for-production)? I'll try that this evening and report back.

**Comment by rhvgoyal** [comment]
What is "ncgen" and which file it failed to open. Looking at the error message, I can't think that this is devicemapper related.

**Comment by LK4D4** [comment]
@5tefan it's one option. Or you can try graphdriver `overlay` if there is support in rhel.

**Comment by 5tefan** [comment]
@rhvgoyal [NetCDF](http://www.unidata.ucar.edu/software/netcdf/docs/) is a binary file format used to store array based science data.  `ncgen` is a command line utility to initialize NetCDF files from an ascii template which specifies the variables, their dimensions, and optional metadata. The resulting .nc file size in my case is 7.168 kB. 

@LK4D4 It looks a lot simpler to use `overlay` (no configuring a block device) so I'll try that first.

**Comment by 5tefan** [comment]
Same results with the following setup (`overlay`)

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 8
Server Version: 1.12.1
Storage Driver: overlay
 Backing Filesystem: xfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay null bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.18.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 239.8 GiB
Name: beef
ID: ZCZZ:KPYN:OYUM:HOZ3:DPUO:NDOY:I2DY:MJK3:T63W:5AK7:U373:QOKG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Labels:
 provider=generic
Insecure Registries:
 127.0.0.0/8
```

Other things: 

- I was unable to reproduce using [stress](https://hub.docker.com/r/progrium/stress/) with --hdd 200, both on and off a -v mount with default and 8k for --hdd-bytes
- I was unable to reproduce the issue in an isolated simplified example with `ncgen`

This seem to hint that there is an issue in my code which seemed odd since I've been running this in several non containerized environments without issue (osx, rhel, and debian). 

Finally got it working:

- I was using the Ubuntu based gcc5.2 image when I created this issue but I switched to Debian. 
- Changed the call to `ncgen` from using system to execv. 

Now it works. Not entirely sure of the original cause but quite possibly could be due to me using [system](http://www.cplusplus.com/reference/cstdlib/system/). I'm happy with closing this, but I could do some digging with `strace` in the Ubuntu image if someone requests.
