### ISSUE TITLE
Backport fix on debain to 1.11.2

### ISSUE THREAD

**Issue by stevezau** [docker/docker#26359]
Hi,

There is a bug where docker stats does not work correctly in 1.11.2 which was fixed in 1.12.1. The problem is 1.12.1 is not supported by kubernetes yet.

Is it possible to backport this fix https://github.com/docker/docker/commit/86002decd0936fa5d466ba7dcbb3fd1524fd86dd into the debain repo?

CoreOS did the same yesterday https://github.com/coreos/docker/pull/28

**Comment by icecrime** [comment]
Sorry, only security fixes get backported to the minor release N-1, and the patch you mention doesn't qualify.

As far as I know, Kubernetes is already in the process of validating Docker 1.12 (see kubernetes/kubernetes#28698), so it will likely update soon.
