### ISSUE TITLE
Consider adding repository to 'Projects-using-docker' wiki

### ISSUE THREAD

**Issue by jeff1evesque** [docker/docker#26377]
My [repository](https://github.com/jeff1evesque/machine-learning) implements docker containers within the [`.travis.yml`](https://github.com/jeff1evesque/machine-learning/blob/78384feb5477464dba4a48b96dbfc01e1d39b0f6/.travis.yml#L101-L112), to perform automated unit testing.  Each time someone commits code, the [travis ci](https://travis-ci.org/jeff1evesque/machine-learning/builds) runs `pytest-flask`.  Could my repository be added to the [Projects using docker](https://github.com/docker/docker/wiki/Projects-using-docker) wiki page?  In the future, I plan on adjusting the development environment to be a series of nested docker containers in the current vagrant environment.

**Comment by jeff1evesque** [comment]
Additionally, the following links are broken:

- [tsuru docker provider](https://github.com/isaiah/tsuru_service)
- [Installing Redis on Docker](http://www.johnmcostaiii.net/2013/installing-redis-on-docker/)

**Comment by thaJeztah** [comment]
To be honest, I didn't even recall we had that page; given that it's a wiki, have you tried editing it yourself? I'm not sure, but I see edits from other (non-maintainers) on that page, so possibly that works.

If you want to get some attention to your project, a good way is to write a blog post about it, and I know those sometimes get included in the docker weekly newsletter

**Comment by jeff1evesque** [comment]
It seems the wiki is closed, or private (maybe recently).  I am unable to edit it:

![docker-wiki](https://cloud.githubusercontent.com/assets/2907085/18483162/03b9a094-79b1-11e6-828d-81bc2ccd69c6.PNG)

I was thinking if the page was intended to be similar to [Sites Using React](https://github.com/facebook/react/wiki/Sites-Using-React) (i.e. ML Frontend), then perhaps my repository could be considered?

**Comment by jeff1evesque** [comment]
I spent numerous hours for several weeks after work, trying to figure out how to incorporate python unit testing via docker containers, using continuous integration (in my case travis ci).  If included to the wiki, I hope it can benefit someone else, similar to the position I was in.  Additionally, if someone could utilize my concepts, and improve on it (eventually I will reduce puppet logic), and contact me about their improvements, it could assist me as well.

**Comment by thaJeztah** [comment]
Oh! I think it was locked at some point because the wiki was abused by spam bots

**Comment by thaJeztah** [comment]
I added a link to your project, and the travis file https://github.com/docker/docker/wiki/Projects-using-docker

A good resource (and open source, so you can open pull requests to make changes), is https://github.com/veggiemonk/awesome-docker, which contains many useful links.

I'l close this issue, because it's resolved, but let me know if there's more changes to be made
