### ISSUE TITLE
docker volume create with directory

### ISSUE THREAD

**Issue by xataz** [docker/docker#26373]
Hi,

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 11
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge overlay null
Swarm: active
 NodeID: btb5ek9guet2ymqijqtagbv2i
 Is Manager: true
 ClusterID: 7o6hsz4pq7ppgfo4fs47n43th
 Managers: 2
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.99.105
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.17-boot2docker
Operating System: Boot2Docker 1.12.1 (TCL 7.2); HEAD : ef7d0b4 - Thu Aug 18 21:18:06 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 492.6 MiB
Name: master
ID: HU6U:KF53:MHJL:J3D5:B42Y:DAC4:IYIU:LK2X:3NJH:MDNX:DSMA:TN42
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 34
 Goroutines: 110
 System Time: 2016-09-07T13:04:13.20866955Z
 EventsListeners: 0
Http Proxy: http://97458n:1234Maif@proxy.maif.local:8080
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I use boot2docker on virtualbox.

I use a lot of container with the same long long path. But it's shitting of use `docker run -ti -v /very/long/long/path:/small/path image`.
I search create a volume with `docker volume` for this /very/long/long/path, but I don't know ?

I try : 
`docker volume create -d local -o type=bind -o device=/very/long/long/path --name test`
But don't works.

Can you help me ?

Sorry for my very bad english.

Thanks and regards,

**Comment by LK4D4** [comment]
ping @cpuguy83 
Is this possible at all?

**Comment by cpuguy83** [comment]
`-v /very/very/long/path:/small/path` should be fine. 
Being that you are on boot2docker, I'd imagine `/very/very/long/path` doesn't exist in the VM and so is empty.

**Comment by cpuguy83** [comment]
Technically this will let you create a bind-mounted volume instead of binding directly in the `-v` flag... but really doesn't make much sense to do this, and will fail if `/very/long/long/path` doesn't exist.

```
docker volume create --name test --opt type=none --opt device=/ver/long/long/path --opt o=bind
```

**Comment by xataz** [comment]
Thanks,

It's works with your command : 
`docker volume create --name project01 -o type=none -o device=/home/$USER/projects/01 -o o=bind`

**Comment by HaiNguyen007** [comment]
This command not work with docker 1.12.6: docker volume create --name project01 -o type=none -o device=/home/$USER/projects/01 -o o=bind
