### ISSUE TITLE
Failed connection to external log-driver run containers hidden from `docker ps`

### ISSUE THREAD

**Issue by pho** [docker/docker#26371]
**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7
 Git commit:   23cf638
 Built:        Fri Aug 19 02:03:02 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7
 Git commit:   23cf638
 Built:        Fri Aug 19 02:03:02 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 158
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-8:2-534994-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.1 GB
 Data Space Total: 107.4 GB
 Data Space Available: 5.065 GB
 Metadata Space Used: 5.296 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.142 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.133 (2016-08-15)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay bridge null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.7.2-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.691 GiB
Name: pho
ID: EUUF:K3RP:ZYHG:A233:NLDD:VHX3:JWOE:RCJM:ADBL:IRJ5:WKCU:BIXP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: pho
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical machine

**Steps to reproduce the issue:**
1. Do not be running a fluentd daemon
2.  Run docker run --rm -ti --log-driver=fluentd busybox

**Describe the results you received:**
docker run fails with:
>docker: Error response from daemon: Failed to initialize logging driver: dial tcp 127.0.0.1:24224: getsockopt: connection refused.
>Error response from daemon: Driver devicemapper failed to remove root filesystem f76e4d2374a62766204669d63d9d4a7650e68e77dc803f47d2cc07779674d60f: Device is Busy

On 1.12.1, `docker ps -a` shows no container is running, BUT the container is running silently in the background 

On another Arch machine running 1.11.1, `docker ps -a` shows a dead container, BUT the container is running silently in the background

**Describe the results you expected:**
The container shows the error response and stops. 

**Additional information you deem important (e.g. issue happens only occasionally):**
This happen with any log-driver that opens a socket and fails (tested with fluentd and splunk, with none of them running)

**Comment by icecrime** [comment]
@LK4D4 Can you please take a look?

**Comment by crosbymichael** [comment]
I can repo this bug, the container should not be started if logging cannot be setup.

**Comment by thaJeztah** [comment]
@crosbymichael any progress on this one?

**Comment by crosbymichael** [comment]
@thaJeztah no, this is a easy fix that someone can make as a contribution

**Comment by ripcurld00d** [comment]
can I call dibs?

**Comment by ripcurld00d** [comment]
#dibs

**Comment by LK4D4** [comment]
@ripcurld00d omg, I'm sorry, I didn't see your dibs. Pls, feel free to review #26744

**Comment by prabhakm** [comment]
Hi 
I have the above said similar issue in MAC
docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true

Any workaround or fix available?
