### ISSUE TITLE
please allow installing docker daemon via linuxbrew

### ISSUE THREAD

**Issue by timotheecour** [docker/docker#26388]
on OSX it's very easy to install docker via brew (`brew install docker`)

on linux, using linuxbrew, `brew install docker` works but doesn't install the docker daemon. 
So on linux, it's a lot more complex, depends on which flavor of linux (and which flavor of ubuntu), eg https://docs.docker.com/engine/installation/linux/ubuntulinux/ and also requires sudo access (and messes up with system libraries)
providing a linuxbrew way (as on OSX) would make things much nicer.

**Comment by justincormack** [comment]
We do not provide the brew installs, these are community supported as far as I know, so I think you need to request this feature from them not here.

**Comment by LK4D4** [comment]
@timotheecour Yup, I agree with @justincormack . This belongs to brew repository, I don't think that we can do anything on our side. If anything would be needed to implement it there, feel free to open another issue.
