### ISSUE TITLE
Re. Docker push fails with most builds on my home machine #20936 - please address for OSX

### ISSUE THREAD

**Issue by abawany** [docker/docker#26386]
Issue #20936 and #22443 appears to not have been addressed for OSX, afaict. The `docker daemon` command is not supported on OSX and refers the user to `dockerd`, which also appears to be missing. How is an OSX user expected to adjust the`--max-concurrent-uploads` and `--max-concurrent-downloads` parameters to be able to upload images while on poor connections, please? I am running Docker 1.12.0-a.

**Comment by abawany** [comment]
@thaJeztah suggested on #20936 that I re-log this issue in https://github.com/docker/for-mac/issues for proper tracking so I have done so: https://github.com/docker/for-mac/issues/621 . Please feel free to close or I can close it as well shortly.

**Comment by thaJeztah** [comment]
Thank you! And sorry for the extra work of opening it there as well; we know it can be confusing :heart:
