### ISSUE TITLE
 run Gui application inside docker container 

### ISSUE THREAD

**Issue by ousema2003** [docker/docker#26383]
Hi , 
i'm using docker winth Centos 7.

adn tried to run a Gui application inside a docker container , with following command . 
docker run -it \
    --env="DISPLAY" \
    --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \  
    image_id 
    xclock

but get this error : Error: Can't open display: localhost:10.0

N.B : Please note that i'm able to run the Gui app, successfully ,  outside the container (on the local machine ).

**Comment by icecrime** [comment]
I think you want to look into `[xhost](https://www.x.org/archive/X11R6.8.1/doc/xhost.1.html)`.

If you don't mind, I'm however going to close this issue as it's very unlikely to be a problem with docker itself. Thanks!

**Comment by ousema2003** [comment]
there is en example to run a Gui application inside a docker container ?

**Comment by thaJeztah** [comment]
There's some discussion on that topic here; https://github.com/docker/docker/issues/8710
