### ISSUE TITLE
Split DNS not respected by Docker for Mac

### ISSUE THREAD

**Issue by wfaulk** [docker/docker#26390]
**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.19-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: CLBH:H3G5:QBCJ:DFB4:MOGO:Z5PG:GYQU:EFKL:5USC:MTZI:Y4BT:K57I
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 27
 System Time: 2016-09-07T19:02:05.77157673Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I have split DNS as a result of my VPN.  The VPN sets MacOS's resolver to send queries for certain zones to the VPN's DNS servers, while everything else goes to the standard DNS server.  This is using the built-in Mac VPN client and can be seen using the `scutil --dns` command (expurgated):

```
DNS configuration

resolver #1
  search domain[0] : a.vpn.example.com
  search domain[1] : int.a.vpn.example.com
  search domain[2] : b.vpn.example.com
  search domain[3] : c.vpn.example.com
  search domain[4] : d.vpn.example.com
  search domain[5] : e.vpn.example.com
  search domain[6] : example.org
  nameserver[0] : 10.0.0.1
  nameserver[1] : 10.0.1.1
  if_index : 4 (en0)
  flags    : Request A records, Request AAAA records
  reach    : Reachable

resolver #2
  domain   : d.vpn.example.com
  nameserver[0] : 10.1.0.1
  nameserver[1] : 10.2.0.1
  flags    : Request A records, Request AAAA records
  reach    : Reachable,Transient Connection
  order    : 100004

resolver #3
  domain   : int.a.vpn.example.com
  nameserver[0] : 10.1.0.1
  nameserver[1] : 10.2.0.1
  flags    : Request A records, Request AAAA records
  reach    : Reachable,Transient Connection
  order    : 100001

resolver #4
  domain   : a.vpn.example.com
  nameserver[0] : 10.1.0.1
  nameserver[1] : 10.2.0.1
  flags    : Request A records, Request AAAA records
  reach    : Reachable,Transient Connection
  order    : 100000

resolver #5
  domain   : c.vpn.example.com
  nameserver[0] : 10.1.0.1
  nameserver[1] : 10.2.0.1
  flags    : Request A records, Request AAAA records
  reach    : Reachable,Transient Connection
  order    : 100003

resolver #6
  domain   : e.vpn.example.com
  nameserver[0] : 10.1.0.1
  nameserver[1] : 10.2.0.1
  flags    : Request A records, Request AAAA records
  reach    : Reachable,Transient Connection
  order    : 100005

resolver #7
  domain   : b.vpn.example.com
  nameserver[0] : 10.1.0.1
  nameserver[1] : 10.2.0.1
  flags    : Request A records, Request AAAA records
  reach    : Reachable,Transient Connection
  order    : 100002

resolver #8
  domain   : local
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  order    : 300000

resolver #9
  domain   : 254.169.in-addr.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  order    : 300200

resolver #10
  domain   : 8.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  order    : 300400

resolver #11
  domain   : 9.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  order    : 300600

resolver #12
  domain   : a.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  order    : 300800

resolver #13
  domain   : b.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records, Request AAAA records
  order    : 301000

DNS configuration (for scoped queries)

resolver #1
  search domain[0] : b.vpn.example.com
  search domain[1] : a.vpn.example.com
  search domain[2] : int.a.vpn.example.com
  nameserver[0] : 10.1.0.1
  nameserver[1] : 10.2.0.1
  if_index : 10 (utun0)
  flags    : Scoped, Request A records
  reach    : Reachable,Transient Connection

resolver #2
  search domain[0] : example.org
  nameserver[0] : 10.0.0.1
  nameserver[1] : 10.0.1.1
  if_index : 4 (en0)
  flags    : Scoped, Request A records, Request AAAA records
  reach    : Reachable
```

`example.org` is the zone configured in the OS directly.  All the various `vpn.example.com` zones are the ones defined by my VPN.

**Steps to reproduce the issue:**
1. `docker login https://dev-artifactory.int.a.vpn.example.com:5002 -u username -p password`

**Describe the results you received:**
The first time after resetting Docker to "factory defaults" I get:

`Error response from daemon: Get https://dev-artifactory.int.a.vpn.example.com:5002/v1/users/: dial tcp: lookup dev-artifactory.int.a.vpn.example.com on 192.168.65.1:53: no such host`

(I have no idea where `192.168.65.1` comes from)

and subsequent times I get:

`Error response from daemon: Get https://dev-artifactory.int.a.vpn.example.com:5002/v1/users/: dial tcp w.x.y.z:5002: i/o timeout`

where `w.x.y.z` is the IP address of the given system when requested from the "external" DNS.

**Describe the results you expected:**
`Login Succeeded`

**Additional information you deem important (e.g. issue happens only occasionally):**
On the Beta channel (the details of which are the details reported above), I can work around the problem by defining dev-artifactory.int.a.vpn.example.com in /etc/hosts on the Mac to my expected internal IP address.  On the Stable channel (which was 1.10), this workaround didn't work.

**Comment by cpuguy83** [comment]
ping @justincormack

**Comment by justincormack** [comment]
ping @dave-tucker

**Comment by dave-tucker** [comment]
ping @djs55

**Comment by djs55** [comment]
Thanks for the clear report. Currently in Docker for Mac we expose multiple upstream servers to the Linux VM, but unfortunately not yet zone information. It looks like we need to perform more processing on the DNS requests, probably on the host where we know the `scutil` configuration.

I'm glad the `/etc/hosts` workaround is working for you -- Mac `/etc/hosts` is new in beta 25 released this week.

Making VPN DNS work is a high priority for us, so thanks again for this report. (Also thanks for teaching me the word "expurgated" -- I shall use it in future!)

**Comment by wfaulk** [comment]
There is one minor error in my initial report:

In the `scutil --dns` output, in the "DNS configuration (for scoped queries)" section, "resolver #1" shows three search domains.  This is because I had manually added those domains in the VPN's config (Network Preferences &rarr; <VPN config> &rarr; Advanced... &rarr; DNS &rarr; Search Domains).  If I hadn't filled this in, there would have been only one search domain in that section: the one provided as part of IP (DHCP?) assignment when connecting to the VPN.  All of the rest of the config looks exactly the same, and it was functionally the same.

**Comment by jpommerening** [comment]
Hi,
just wanted to chime in and let you know that I'm running almost exactly the same setup and having the same problem. I got by with some temporary workarounds `screen`ing into the docker VM, editing the `resolv.conf` and stuff like that.

Is docker/vpnkit#132 supposed to address this particular issue? Is it already available in the current (1.12.3-beta29.3 13640) beta?

I'd be happy to test :)

**Comment by jpommerening** [comment]
I installed 1.12.3-beta30 (13798) yesterday and this seems to resolve my DNS issues!
@wfaulk: Maybe give it a shot with the latest beta. I believe we're running similar setups. 
@djs55: thanks for the work you put into this! You wouldn't believe how much of a pain relief this is! 🙌

**Comment by thaJeztah** [comment]
@wfaulk are you still having this issue, or can this be closed?

**Comment by wfaulk** [comment]
Unfortunately, we ditched Docker for this project, so I no longer have this use case to test.

**Comment by thaJeztah** [comment]
let me close this issue then, as it should be resolved in recent versions of docker for mac
