### ISSUE TITLE
[swarm mode docs] Document difference between engine labels and node labels

### ISSUE THREAD

**Issue by nathanleclaire** [docker/docker#26392]
In `docker node` you can see that there is a `docker node update --label-add` option to add labels.

I was confused about the difference between this and Engine labels (i.e., added with `--label` to `dockerd`) and asked the Swarm team to explain.  The answer was insightful and should be documented.

Essentially:
1. A compromised worker node could change its own Engine labels, but not node labels.  Only managers can change node labels.
2. Therefore, node labels could be useful to e.g. schedule only on machines where certain special workloads should be run, for instance machines where [PCI-SS compliance](https://www.pcisecuritystandards.org/) is met.  A compromised worker could not compromise these special workloads because it cannot change node labels.
3. Engine labels, however, are still useful because some features which do not affect secure orchestration of containers might be better off set in a decentralized manner.  For instance, an engine could have a label to indicate that it has a certain type of disk device, which may not be relevant to security directly.  These labels are more easily "trusted" by the orchestrator.

https://docs.docker.com/engine/swarm/manage-nodes/#/add-or-remove-label-metadata explains that you _can_ do this, but not why you might want to.

FYI @londoncalling and thanks @diogomonica @stevvooe @cpuguy83 for explanation

**Comment by londoncalling** [comment]
@nathanleclaire @thaJeztah , I'm going to go ahead and close this issue, as the docs update was merged (see above). We can re-open if needed. Thanks!

**Comment by thaJeztah** [comment]
Sure, thanks!
