### ISSUE TITLE
Docker V1.9.0, Docker stops after the build success

### ISSUE THREAD

**Issue by tanujchinnu** [docker/docker#26401]
After running the build for 45 minutes which is success, the infrastructure is creating inside the docker container. But the docker stops automatically after the successful build. 

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@ Web - [] BUILD SUCCESSFUL @@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

Not running E2E tests
Not retrieving code coverage
unexpected EOF

After this when I run this command

docker build -t letmesee2 .
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

This is the error what I get after the successful build. Can some one explain me what the issue it would be.

**Comment by cpuguy83** [comment]
Best thing to do would be to check the daemon logs... where these are will depend on your init system.

Being that this is on docker 1.9 I'm going to close this.
If you need extra help, please hop on #docker on IRC or forums.docker.com

Thanks!

**Comment by tanujchinnu** [comment]
I cannot check docker logs as the docker is exiting after failing and stops
after success

**Comment by cpuguy83** [comment]
The docker daemon logs, not the `docker logs` command.
