### ISSUE TITLE
Cannot detect Linux distribution or it’s unsupported

### ISSUE THREAD

**Issue by dev6** [docker/docker#26418]
Getting this error when run this command which was given by the web dashboard (changed the key to *)
```
sudo curl -Ls https://get.cloud.docker.com/ | sudo -H sh -s f74*************************
ERROR: Cannot detect Linux distribution or it's unsupported
Learn more: https://docs.docker.com/docker-cloud/tutorials/byoh/
```
while the docker info command gives the following output:

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 3
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay null bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-37-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.56 GiB
Name: arch-Pro-G1
ID: WNIV:V2NZ:6IR7:*************
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```
Not sure of where the problem is arising from in that shell script.

**Comment by icecrime** [comment]
Ping @fermayo!

**Comment by fermayo** [comment]
@dev6 can you make sure you have the following in `/etc/lsb-release`?

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
```

Otherwise the installer won't be able to detect that you are running Ubuntu.

**Comment by dev6** [comment]
My `/etc/lsb-release` says following:

```
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.3
DISTRIB_CODENAME=rosa
DISTRIB_DESCRIPTION="Linux Mint 17.3 Rosa"
```

Should I change this to Ubuntu to install Docker cloud? No other way around of it so that it wont cause me trouble when Updating my system to next version of Linux Mint?

**Comment by fermayo** [comment]
@dev6 oh sorry, I thought you were running Ubuntu 14.04 based on the output of `docker info`. We don't support Linux Mint yet in Docker Cloud. Please check https://docs.docker.com/docker-cloud/infrastructure/byoh/#/supported-linux-distributions

**Comment by cpuguy83** [comment]
Closing since this is not really a docker/docker issue. @fermayo Is there somewhere to track this kind of information for cloud?

**Comment by fermayo** [comment]
@cpuguy83 Cloud docs: https://docs.docker.com/docker-cloud/ and Cloud forums: https://forums.docker.com/c/docker-cloud
