### ISSUE TITLE
Connection Reset when accessing Docker service via IPSec

### ISSUE THREAD

**Issue by cookandy** [docker/docker#26419]
Hello,

I've got two machines connected via IPSec (using setkey and racoon).  Both machines have a public IP address and a private (10.x) address.  The IPSec tunnel is configured on the private (10.x) network.

When I run a small container like nginx on machine A, I can get to it from machine B:

**Machine A:**
```
docker run -it --rm -p 8888:80 nginx
```

**Machine B**

```
root@machine-b:~# curl -v http://machine-a:8888


*   Trying 10.128.26.208...
* Connected to 10.128.26.208 (10.128.26.208) port 8888 (#0)
> GET / HTTP/1.1
> Host: 10.128.26.208:8888
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx/1.11.3
< Date: Tue, 06 Sep 2016 23:48:57 GMT
< Content-Type: text/html
< Content-Length: 612
< Last-Modified: Tue, 26 Jul 2016 14:54:48 GMT
< Connection: keep-alive
< ETag: "579779b8-264"
< Accept-Ranges: bytes
...
```

I can also run `tcpdump -vv -i eth1 esp` on machine-a to verify the communication is coming via IPSec.

```
23:54:05.838381 IP (tos 0x0, ttl 64, id 42083, offset 0, flags [DF], proto ESP (50), length 124)
    10.128.19.238 > machine-a: ESP(spi=0x0feec5b8,seq=0x180), length 104
23:54:05.838753 IP (tos 0x0, ttl 63, id 0, offset 0, flags [DF], proto ESP (50), length 124)
    machine-a > 10.128.19.238: ESP(spi=0x0900037f,seq=0x19d), length 104
23:54:05.839292 IP (tos 0x0, ttl 64, id 42084, offset 0, flags [DF], proto ESP (50), length 124)
    10.128.19.238 > machine-a: ESP(spi=0x0feec5b8,seq=0x181), length 104
```

So far, so good!

However, when I try to run a web application in a Tomcat container, I am getting a timeout from machine B:

**Machine A:**

```
docker run -it --rm -p 8888:8080 tomcat
```

**Machine B:**

```
root@machine-b:~# curl -v http://machine-a:8888
*   Trying 10.128.26.208...
* Connected to 10.128.26.208 (10.128.26.208) port 8888 (#0)
> GET / HTTP/1.1
> Host: 10.128.26.208:8888
> User-Agent: curl/7.47.0
> Accept: */*
>
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

I started doing some digging and realized that the connection is only reset when the request is bigger than `1161 bytes`.  I created small text file (`1161 byes`) and was able to access it from machine B:

**Machine A:**

```
docker run -it -p 8888:8080 -v /root/test:/usr/local/tomcat/webapps/test tomcat
```

**Machine B:**

```
root@machine-b:~# curl -v http://machine-a:8888/test/a.txt
*   Trying 10.128.26.208...
* Connected to 10.128.26.208 (10.128.26.208) port 8888 (#0)
> GET / HTTP/1.1
> Host: 10.128.26.208:8888
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: Apache-Coyote/1.1
< Accept-Ranges: bytes
< ETag: W/"1161-1473343540000"
< Last-Modified: Thu, 08 Sep 2016 14:05:40 GMT
< Content-Type: text/plain
< Content-Length: 1161
< Date: Thu, 08 Sep 2016 14:05:44 GMT
<
dsajfklhasdlkjfhdsafjklasasfhdjnsfhdsajkbfhdsjlkavbfhdsalkjbhvadlkjfycnadklsjhfbcadkshjljcfbgnadksjlhfdsgcsdjhgsdajhkgfadhjksfabsbsahkjfgcabdhsjcfgabdhjksgbhjkjghfghjfgdghfdfjgfl;gdfslkjsalkfjaslkfjsadlkfjsdlkfjsdafkjadslf;sdfkljsadflkjasdfhasdfkjhwejkvbakljdsnfewkjcnfaekuwlcryaeknjfbevyalkryekwfbcaeklwcfhkluadjsfhdslufgdsahjbfdsafukydasgfhkjasdnfjkvbylhekjncfalejvhrbewnkjcahbklvnfalcnfbailudsyfhlchubsafhdsajfklhasdlkjfhdsafjklasasfhdjnsfhdsajkbfhdsjlkavbfhdsalkjbhvadlkjfycnadklsjhfbcadkshjljcfbgnadksjlhfdsgcsdjhgsdajhkgfadhjksfabsbsahkjfgcabdhsjcfgabdhjksgbhjkjghfghjfgdghfdfjgfl;gdfslkjsalkfjaslkfjsadlkfjsdlkfjsdafkjadslf;sdfkljsadflkjasdfhasdfkjhwejkvbakljdsnfewkjcnfaekuwlcryaeknjfbevyalkryekwfbcaeklwcfhkluadjsfhdslufgdsahjbfdsafukydasgfhkjasdnfjkvbylhekjncfalejvhrbewnkjcahbklvnfalcnfbailudsyfhlchubsafhdsajfklhasdlkjfhdsafjklasasfhdjnsfhdsajkbfhdsjlkavbfhdsalkjbhvadlkjfycnadklsjhfbcadkshjljcfbgnadksjlhfdsgcsdjhgsdajhkgfadhjksfabsbsahkjfgcabdhsjcfgabdhjksgbhjkjghfghjfgdghfdfjgfl;gdfslkjsalkfjaslkfjsadlkfjsdlkfjsdafkjadslf;sdfkljsadflkjasdfhasdfkjhwejkvbakljdsnfewkjcnfaekuwlcryaeknjfbevyalkryekwfbcaeklwcfhkluadjsfhdslufgdsahjbfdsafukydasgfhkj
* Connection #0 to host 10.128.26.208 left intact
```

**However...** if I edit the `a.txt` file and make it `1162 byes`, my connection times out (the same as the earlier example).

The reason I'm convinced this is Docker-related is because if I install Tomcat directly on the host machine, I can access my large applications (and larger `a.txt` file) via curl on machine B with no problems via IPSec.

I was originally thinking this was an issue with the MTU value on `docker0`.  I tried to reconfigure the MTU per the docker instructions, but it didn't work, so I opened this issue:

https://github.com/docker/docker/issues/26382

I tried the hack suggested by @chenchun, but it didn't seem to make a difference.  I can see that the MTU has been adjusted for the `docker0` interface, but I still cannot access the larger `a.txt` file via curl when running Tomcat in a container.

Any ideas on where to look next?  I'd be happy to provide a tcpdump of `docker0`, or any other logs you might think would be helpful.  Thanks!   

**Output of `docker version`:**

```
Docker version 1.11.2, build b9f10c9
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 3.13.0-85-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 490 MiB
Name: machine-a
ID: VHD6:QBHG:66XY:LXVO:PLM5:TGQL:LGNS:QCJD:BXLN:RIWK:QNYK:RSH4
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

DigitalOcean droplet

**Steps to reproduce the issue:**
1.  Create IPSec connection between two machines
2.  Start tomcat container, mapped to port 8888 on machine A
3.  From machine B, try to curl the main tomcat page:  `curl -v http://machine-a:8888`

**Describe the results you received:**

See above.

**Describe the results you expected:**

See above.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment]
What's the MTU on the interface in the container?
Also, what MTU did you set?

**Comment by cookandy** [comment]
It looks like the MTU in the container is the same as `docker0`.

**Host:**

```
docker0   Link encap:Ethernet  HWaddr 02:42:6e:28:e1:7a
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:6eff:fe28:e17a/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:8960  Metric:1
          RX packets:896 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5120 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:116550 (116.5 KB)  TX bytes:20223117 (20.2 MB)
```

**Container:**

```
root@machine-a:~# docker exec -it 121 bash
root@1217085c5a4f:/usr/local/tomcat# ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:ac:11:00:02
          inet addr:172.17.0.2  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:acff:fe11:2/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:8960  Metric:1
          RX packets:5066 errors:0 dropped:0 overruns:0 frame:0
          TX packets:788 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:20218573 (19.2 MiB)  TX bytes:65284 (63.7 KiB)
```

**Comment by cpuguy83** [comment]
I think MTU needs to be set to cope for at least 50 bytes of overhead from ipsec, no?
I would probably set the MTU lower.

**Comment by cookandy** [comment]
Hi @cpuguy83 - thanks for the reply.  I tried setting the MTU to something a bit more reasonable (1600), but experienced the same results. 

I've included a tcpdump of `eth1` (the network on which IPSec is enabled) below; tcpdump doesn't seem to work against `docker0` (maybe because I setup the `dummy0` link??).

Successful curl from Tomcat - `1160 bytes`:

```
16:43:56.037784 IP (tos 0x0, ttl 64, id 33504, offset 0, flags [DF], proto ESP (50), length 124)
    10.128.39.203 > andy-02: ESP(spi=0x0620a38d,seq=0xc), length 104
16:43:56.038309 IP (tos 0x0, ttl 63, id 0, offset 0, flags [DF], proto ESP (50), length 124)
    andy-02 > 10.128.39.203: ESP(spi=0x002cfebf,seq=0xf), length 104
16:43:56.038794 IP (tos 0x0, ttl 64, id 33505, offset 0, flags [DF], proto ESP (50), length 124)
    10.128.39.203 > andy-02: ESP(spi=0x0620a38d,seq=0xd), length 104
16:43:56.039081 IP (tos 0x0, ttl 64, id 33506, offset 0, flags [DF], proto ESP (50), length 204)
    10.128.39.203 > andy-02: ESP(spi=0x0620a38d,seq=0xe), length 184
16:43:56.039175 IP (tos 0x0, ttl 63, id 61488, offset 0, flags [DF], proto ESP (50), length 124)
    andy-02 > 10.128.39.203: ESP(spi=0x002cfebf,seq=0x10), length 104
16:43:56.043355 IP (tos 0x0, ttl 63, id 61489, offset 0, flags [DF], proto ESP (50), length 1500)
    andy-02 > 10.128.39.203: ESP(spi=0x002cfebf,seq=0x11), length 1480
16:43:56.043626 IP (tos 0x0, ttl 64, id 33507, offset 0, flags [DF], proto ESP (50), length 124)
    10.128.39.203 > andy-02: ESP(spi=0x0620a38d,seq=0xf), length 104
16:43:56.045528 IP (tos 0x0, ttl 64, id 33508, offset 0, flags [DF], proto ESP (50), length 124)
    10.128.39.203 > andy-02: ESP(spi=0x0620a38d,seq=0x10), length 104
16:43:56.046583 IP (tos 0x0, ttl 63, id 61490, offset 0, flags [DF], proto ESP (50), length 124)
    andy-02 > 10.128.39.203: ESP(spi=0x002cfebf,seq=0x12), length 104
16:43:56.046782 IP (tos 0x0, ttl 64, id 33509, offset 0, flags [DF], proto ESP (50), length 124)
    10.128.39.203 > andy-02: ESP(spi=0x0620a38d,seq=0x11), length 104
```

You can see that the length above was `1500`:

```
16:43:56.043355 IP (tos 0x0, ttl 63, id 61489, offset 0, flags [DF], proto ESP (50), length 1500)
    andy-02 > 10.128.39.203: ESP(spi=0x002cfebf,seq=0x11), length 1480
```

However, when I try to curl the file that is `1161 bytes`:

```
16:46:35.203206 IP (tos 0x0, ttl 64, id 18042, offset 0, flags [DF], proto ESP (50), length 124)
    10.128.39.203 > andy-02: ESP(spi=0x0620a38d,seq=0x12), length 104
16:46:35.203812 IP (tos 0x0, ttl 63, id 0, offset 0, flags [DF], proto ESP (50), length 124)
    andy-02 > 10.128.39.203: ESP(spi=0x002cfebf,seq=0x13), length 104
16:46:35.204334 IP (tos 0x0, ttl 64, id 18043, offset 0, flags [DF], proto ESP (50), length 124)
    10.128.39.203 > andy-02: ESP(spi=0x0620a38d,seq=0x13), length 104
16:46:35.204786 IP (tos 0x0, ttl 64, id 18044, offset 0, flags [DF], proto ESP (50), length 204)
    10.128.39.203 > andy-02: ESP(spi=0x0620a38d,seq=0x14), length 184
16:46:35.204947 IP (tos 0x0, ttl 63, id 46714, offset 0, flags [DF], proto ESP (50), length 124)
    andy-02 > 10.128.39.203: ESP(spi=0x002cfebf,seq=0x14), length 104
16:46:35.209908 IP (tos 0x0, ttl 63, id 46715, offset 0, flags [DF], proto ESP (50), length 1516)
    andy-02 > 10.128.39.203: ESP(spi=0x002cfebf,seq=0x15), length 1496
16:46:35.413089 IP (tos 0x0, ttl 63, id 46716, offset 0, flags [DF], proto ESP (50), length 1516)
    andy-02 > 10.128.39.203: ESP(spi=0x002cfebf,seq=0x16), length 1496
16:46:35.617092 IP (tos 0x0, ttl 63, id 46717, offset 0, flags [DF], proto ESP (50), length 1516)
    andy-02 > 10.128.39.203: ESP(spi=0x002cfebf,seq=0x17), length 1496
16:46:36.025068 IP (tos 0x0, ttl 63, id 46718, offset 0, flags [DF], proto ESP (50), length 1516)
    andy-02 > 10.128.39.203: ESP(spi=0x002cfebf,seq=0x18), length 1496
16:46:36.841116 IP (tos 0x0, ttl 63, id 46719, offset 0, flags [DF], proto ESP (50), length 1516)
    andy-02 > 10.128.39.203: ESP(spi=0x002cfebf,seq=0x19), length 1496
16:46:38.477132 IP (tos 0x0, ttl 63, id 46720, offset 0, flags [DF], proto ESP (50), length 1516)
    andy-02 > 10.128.39.203: ESP(spi=0x002cfebf,seq=0x1a), length 1496
.......
.......
```

...and it just keeps continuing until the connection is finally closed. In the example above, the length is `1516`, which I think an MTU of `1600` should accommodate.  

When I curl against the tomcat outside of docker, with the `1161 byte` file, it is successful:

```
tcpdump: listening on eth1, link-type EN10MB (Ethernet), capture size 262144 bytes
16:59:47.540094 IP (tos 0x0, ttl 64, id 1623, offset 0, flags [DF], proto ESP (50), length 124)
    10.128.39.203 > andy-02: ESP(spi=0x06a74499,seq=0x1c), length 104
16:59:47.540392 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto ESP (50), length 124)
    andy-02 > 10.128.39.203: ESP(spi=0x0b6aba0b,seq=0x15), length 104
16:59:47.540781 IP (tos 0x0, ttl 64, id 1624, offset 0, flags [DF], proto ESP (50), length 124)
    10.128.39.203 > andy-02: ESP(spi=0x06a74499,seq=0x1d), length 104
16:59:47.541146 IP (tos 0x0, ttl 64, id 1625, offset 0, flags [DF], proto ESP (50), length 204)
    10.128.39.203 > andy-02: ESP(spi=0x06a74499,seq=0x1e), length 184
16:59:47.541188 IP (tos 0x0, ttl 64, id 34260, offset 0, flags [DF], proto ESP (50), length 124)
    andy-02 > 10.128.39.203: ESP(spi=0x0b6aba0b,seq=0x16), length 104
16:59:47.548888 IP (tos 0x0, ttl 64, id 34261, offset 0, flags [DF], proto ESP (50), length 1500)
    andy-02 > 10.128.39.203: ESP(spi=0x0b6aba0b,seq=0x17), length 1480
16:59:47.549005 IP (tos 0x0, ttl 64, id 34262, offset 0, flags [DF], proto ESP (50), length 124)
    andy-02 > 10.128.39.203: ESP(spi=0x0b6aba0b,seq=0x18), length 104
16:59:47.549202 IP (tos 0x0, ttl 64, id 1626, offset 0, flags [DF], proto ESP (50), length 124)
    10.128.39.203 > andy-02: ESP(spi=0x06a74499,seq=0x1f), length 104
16:59:47.549243 IP (tos 0x0, ttl 64, id 1627, offset 0, flags [DF], proto ESP (50), length 124)
    10.128.39.203 > andy-02: ESP(spi=0x06a74499,seq=0x20), length 104
16:59:47.550526 IP (tos 0x0, ttl 64, id 1628, offset 0, flags [DF], proto ESP (50), length 124)
    10.128.39.203 > andy-02: ESP(spi=0x06a74499,seq=0x21), length 104
16:59:47.551237 IP (tos 0x0, ttl 64, id 34263, offset 0, flags [DF], proto ESP (50), length 124)
    andy-02 > 10.128.39.203: ESP(spi=0x0b6aba0b,seq=0x19), length 104
16:59:47.551400 IP (tos 0x0, ttl 64, id 1629, offset 0, flags [DF], proto ESP (50), length 124)
    10.128.39.203 > andy-02: ESP(spi=0x06a74499,seq=0x22), length 104
```

The maximum length of the request above is only `1500` (compared to `1516` with the docker request):

```
16:59:47.548888 IP (tos 0x0, ttl 64, id 34261, offset 0, flags [DF], proto ESP (50), length 1500)
    andy-02 > 10.128.39.203: ESP(spi=0x0b6aba0b,seq=0x17), length 1480
```

Any ideas?

**Comment by cpuguy83** [comment]
I'm assuming your network infra supports jumbo frames since you've been using 9000-ish mtu?

**Comment by cookandy** [comment]
I'm not entirely sure TBH, I just picked a really high number to see if I could get a webpage across.  But setting the MTU value at `1600` produces the same results, so I'm _guessing_ we can rule that out?

**Comment by cpuguy83** [comment]
@cookandy Normal ethernet frames max out at 1500.
So you'd need to set it to a lower value, let's try 1420?

**Comment by cookandy** [comment]
Looks like we're getting somewhere.  👍 

However, I'm still noticing some strange behavior...

If I reboot my 2 machines so that the MTU settings revert to 1500, and then manually run `ifconfig eth1 mtu 1420` on both nodes, it works!  I don't even have to update the `docker0` MTU.

However, if I update `/etc/network/interfaces` and set the MTU according to [this article](http://www.ubuntugeek.com/how-to-change-mtu-maximum-transmission-unit-of-network-interface-in-ubuntu-linux.html) and reboot, it doesn't seem to work.  

After reboot, I've confirmed that my MTU is set to `1420` on eth1, however I'm only able to curl a file that is `1081 bytes`.  If I try a larger file (`1082 bytes`), it fails as it did before the change.  

I'm not sure why setting the MTU manually works, but not if I set it in the networking file.  Furthermore, if I try to manually set the MTU to `1420` after I've made the networking file change, it still doesn't work.  

I didn't bother messing with the `docker0` interface since it seemed to work fine when manually setting the MTU (when the default is 1500).

I think we're close!

**Comment by justincormack** [comment]
You are using Digital Ocean. They will not support an MTU of more than 1500. If a provider supports more than 1500 they will tell you but it is extremely unusual. You cannot just increase MTU and have it "just work", it really does not work like that. You need to buy and configure switches and ethernet cards that support "jumbo frames".

**Comment by cookandy** [comment]
Thanks for the info @justincormack - you are correct.  That was a bad assumption on my part.  I've since switched to using the smaller MTU (1420), but am having some problems when configuring the adapters to use that value by default.

**Comment by cpuguy83** [comment]
How to set the mtu on adapters so that they are persistent between reboots is going to be OS specific.
You can set the MTU on the docker bridge via the docker daemon config and this should take care of any traffic you have in the containers.

Closing because this is a host configuration issue and not a docker one.

**Comment by cookandy** [comment]
@cpuguy83:  can we reopen please?  i'm not convinced this is purely an OS-thing.  I've since discovered that manually setting the mtu with `ifconfig eth1 mtu 1420` only seems to last about 15 minutes, and then it stops working (without changing anything).

To recap the facts:

- MTU must be adjusted from `1500` to `1420` to access Tomcat in a container
- MTU does NOT need to be adjusted to access Tomcat outside of a container (default of `1500` works)
- After starting a container and running `ifconfig eth1 mtu 1420`, I can connect to it from all machines
- I haven't had to adjust `docker0` at all, only `eth1` - and I am still able to get to the container 
- I can continue to access the container from other machines for about 15-20 min, after which it stops working again (I can't even get to the already started containers which were previously working)
- At this point, even if I restart the containers and re-run `ifconfig eth1 mtu 1420`, it fails to work
- Even restarting the docker daemon doesn't help
- If I restart the machines and rerun the `ifconfig` command, things start to work again (for ~15 min)

...and the whole time I'm still able to get to my Tomcat instance outside of Docker... 

Is there anything I can do to debug this issue further?

**Comment by justincormack** [comment]
You should only set the MTU on the actual tunnel interface (probably to 1400), at both ends. You should not set it on any of the other interfaces, including `docker0` and in the containers. Everything else should then sort itself out.

**Comment by cookandy** [comment]
hi @justincormack I'm using IPSec in `transport` mode, which means I cannot adjust the MTU on the tunnel interface.  I've added some more information here:  https://github.com/docker/docker/issues/26473

**Comment by justincormack** [comment]
You will probably have to dig through the raw traffic on the wire to debug...

**Comment by peterwillcn** [comment]
```
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1280
```
