### ISSUE TITLE
Add check for vxlan module to https://get.docker.com for Raspian

### ISSUE THREAD

**Issue by darkermatter** [docker/docker#26425]
**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:31:15 2016
 OS/Arch:      linux/arm

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:31:15 2016
 OS/Arch:      linux/arm
```

**Describe the results you received:**
I installed Docker on some Raspberry Pis with Raspian Jessie using `curl -sSL https://get.docker.com | sh` in order to follow a swarm tutorial. The networking didn't work. This was because I needed to run rpi-update on each Pi to install the vxlan kernel module. This isn't obvious.

**Describe the results you expected:**
Install Docker and proceed with swarm mode tutorials, etc.

**Additional information you deem important (e.g. issue happens only occasionally):**
Thanks @mrjana for pointing out what needed to be done.

**Comment by alexellis** [comment]
@darkermatter Was this my tutorial by any chance? It does mention that you need to run `rpi-update` but that relates to the image released in May. All images since already contain vxlan.

**Comment by darkermatter** [comment]
Hi @alexellis, sorry but I can't recall the tutorial I used.

**Comment by alexellis** [comment]
This will only appear for people with a very old RPi image. If I leave a link to this set of functional tests do you think this can get closed? https://github.com/alexellis/swarmmode-tests/tree/master/arm

**Comment by thaJeztah** [comment]
I agree; we have a check-config script to help finding possible issues on the host, and we cannot check for every issue in the install script; https://github.com/docker/docker/blob/master/contrib/check-config.sh

I'll close this issue, but thanks for reporting @darkermatter
