### ISSUE TITLE
Windows: Pulling Ubuntu images no longer provides expected error

### ISSUE THREAD

**Issue by darrenstahlmsft** [docker/docker#26429]
Windows daemon should provide an error message when attempting to pull an image based off a Linux base image. This is a regression of the behaviour added in https://github.com/docker/docker/pull/24819.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Windows daemon

**Steps to reproduce the issue:**
1. docker pull ubuntu

**Describe the results you received:**
```
C:\Users\Administrator>docker pull ubuntu
Using default tag: latest
latest: Pulling from library/ubuntu
952132ac251a: Extracting [==================================================>] 49.73 MB/49.73 MB
82659f8f1b76: Download complete
c19118ca682d: Download complete
8296858250fe: Download complete
24e0251a0e2c: Download complete
failed to register layer: re-exec error: exit status 1: output: Failed to OpenForBackup failed in Win32: open \\?\C:\ProgramData\docker\windowsfilter\f418f4ac43d51c1c1123b48c8025ceb6125e840a0df9f525755e9e55506a586f\usr\share\man\man7\pam.7.gz: The file exists. (0x1f) \\?\C:\ProgramData\docker\windowsfilter\f418f4ac43d51c1c1123b48c8025ceb6125e840a0df9f525755e9e55506a586f\usr\share\man\man7\pam.7.gz
```

**Describe the results you expected:**

Expected an error that states a Linux image cannot be pulled on a Windows platform

/cc @jhowardmsft

**Comment by jhowardmsft** [comment]
Yes, something has regressed from https://github.com/docker/docker/pull/24819/files

**Comment by jhowardmsft** [comment]
@aaronlehmann @stevvooe Has something changed on the back-end? Reverting back to the commit in https://github.com/docker/docker/pull/24819, the block is no longer working. The reason seems to be that the unmarshalled config OS field is no longer populated.

**Comment by aaronlehmann** [comment]
It looks like the code in #24819 only checks schema2 manifests. Maybe the `ubuntu` image on hub uses a schema1 manifest?

Even if this doesn't turn out to be the problem, it probably makes sense to add an equivalent check to `pullSchema1`.

**Comment by jhowardmsft** [comment]
Sure, but that's not the issue here. Is definitely going through v2. Someone has re-orgd that code, so in master, that check is meaningless as it's now in the wrong place. But that's irrelevant as it still seems the field is no longer populated. Still investigating unless you have other ideas?

**Comment by aaronlehmann** [comment]
Do you mean that the field is not present in the image config that's on Hub, or that it's lost somewhere inside the engine?

**Comment by jhowardmsft** [comment]
@aaronlehmann Solved it. It's introduced by https://github.com/docker/docker/commit/f342b27145d8f5af27cd5de1501551af275e899b. Putting together a PR to fix it (and introduce a test :smile:)

**Comment by aaronlehmann** [comment]
Thanks very much!
