### ISSUE TITLE
Question regarding setting a container's hostname

### ISSUE THREAD

**Issue by robvelor** [docker/docker#26430]
Is is possible to set a container's hostname to the hostmachine's hostname or perhaps container name (the one docker assigns not a custom one)?

**Comment by mlaventure** [comment]
@robvelor By default docker use the container's name (truncated to 12 chars) for the hostname.

You can specify an arbitrary one using the `-h option` to  the `create` and `run` commands

see https://docs.docker.com/engine/userguide/networking/default_network/configure-dns/

**Comment by robvelor** [comment]
@mlarcher I know but back to my question... I don't want to hardcode it :).  I want to set it though compose file (hostname: ) but using the container name (the dynamic one docker assigns PROJECT_SERVICE_X) or set it to host machine hostname.. again dynamically not hardcoded, think in a swarm network for example.

**Comment by mlaventure** [comment]
Oh, I see. 

ping @dnephin 

But the [Docker Forums](https://forums.docker.com/) are probably a better place to ask a question, we try to keep github for bugs/feature requests.
