### ISSUE TITLE
docker client disallow set hostname and domainname to pass hostname limit with 63 chars.

### ISSUE THREAD

**Issue by mkostrikin** [docker/docker#26444]
**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 112
 Running: 0
 Paused: 0
 Stopped: 112
Images: 574
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 920
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-36-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.37 GiB
Name: MAPC
ID: VRYJ:XOIZ:K2QS:ER2U:S22A:6VCN:4TAV:5SDO:F2LA:ZJPM:3KWV:ZKQ3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Steps to reproduce the issue:**
1.  `docker run --rm -it --hostname=longhostname1234567890.longsubdomain1234567890.longdomain1234567890.com  ubuntu` returns `invalid hostname format` - that ok.
2. `docker run --rm -it --hostname=longhostname1234567890 --domainname=longsubdomain1234567890.longdomain1234567890.com  ubuntu` returns `unknown flag: --domainname` that ok, but here https://github.com/docker/docker/pull/20200/files#diff-3c155b9e72b99ee79b7ea313708bf309R130 was introduced API feature, that allows `domainname` in `create` action.
Please add `--domainname` parameter to `docker run`/`docker create` to align with Docker API 

Thanks

**Comment by justincormack** [comment]
The API and CLI do not necessarily match, as the CLI needs to be easy to use.

Is the issue that you want to be able to specify a 64 byte hostname and a 64 byte domain name? This could be added without changing the CLI options by changing the validation.

**Comment by mlaventure** [comment]
According to https://tools.ietf.org/html/rfc1035 each segment of a FQDN cannot exceed 63 characters.

**Comment by cpuguy83** [comment]
@justincormack Issue is there is no way to pass in a domain name from the CLI.
However I think we can just split on the first dot?  Not sure what the consequences are on that...

**Comment by mkostrikin** [comment]
This days FQDN longer then 63 chars is pretty normal, and we have no way to run docker container with fqdn hostname longer then 63 using console client. It that ok - issue can be closed.

**Comment by thaJeztah** [comment]
Splitting was previously done on the daemon side, but removed in https://github.com/docker/docker/pull/20200, perhaps it can be done client-side, although that would still make the hostname not a FQDN (if I followed that change correctly)

**Comment by justincormack** [comment]
Ugh this is a bit of a mess. @cpuguy83 is right, there is no way to set the domainname:
```
whale:lua-client justin$ docker run --hostname test.my.domain alpine cat /proc/sys/kernel/hostname
test.my.domain
whale:lua-client justin$ docker run --hostname test.my.domain alpine cat /proc/sys/kernel/domainname
(none)
```

But if we change the current logic and split the hostname at the first dot, then it may break existing code.

So I think we should add a `--domainname` flag if it is really required. Not sure if it exists on Windows in a useful way.

**Comment by thaJeztah** [comment]
Yeah, `docker-compose` has [always had a `domainname` option in the docker-compose file](https://github.com/docker/compose/blob/1.8.1/docs/compose-file.md#cpu_shares-cpu_quota-cpuset-domainname-hostname-ipc-mac_address-mem_limit-memswap_limit-privileged-read_only-restart-shm_size-stdin_open-tty-user-working_dir)

**Comment by cyphar** [comment]
I just opened another issue (phrased as a proposal) in #27067. Do you want to close this issue for the other one (as it's specifically a proposal) -- or is this issue still separate from mine?

**Comment by thaJeztah** [comment]
Let's use https://github.com/docker/docker/issues/27067 for tracking the feature request

Thanks @mkostrikin!
