### ISSUE TITLE
s390x: Docker build broken by "Vendor libnetwork"

### ISSUE THREAD

**Issue by michael-holzheu** [docker/docker#26440]
Docker commit 99c39680984018b345881a29d77a89f87958a57b ("Vendor libnetwork") breaks "make binary" on s390x:

```
# github.com/docker/libnetwork/drivers/bridge
vendor/src/github.com/docker/libnetwork/drivers/bridge/netlink_deprecated_linux.go:100: cannot use ifrDataByte(hw[i]) (type uint8) as type int8 in assignment
```

See also jenkins jobs: https://jenkins.dockerproject.org/job/Docker%20Master%20(z)%20Binaries/
First failed job: https://jenkins.dockerproject.org/job/Docker%20Master%20(z)/497/

**Comment by michael-holzheu** [comment]
ping @mrjana

**Comment by michael-holzheu** [comment]
The root cause seem to be in:

`vendor/src/github.com/docker/libnetwork/drivers/bridge/netlink_deprecated_linux.go`:
```go
func ioctlSetMacAddress(name, addr string) error {
...
        for i := 0; i < 6; i++ {
                ifr.IfruHwaddr.Data[i] = ifrDataByte(hw[i])
        }
```

and

`vendor/src/github.com/docker/libnetwork/drivers/bridge/netlink_deprecated_linux_s390x.go`:

```go
// +build s390x

package bridge

func ifrDataByte(b byte) uint8 {
        return uint8(b)
}
```

**Comment by michael-holzheu** [comment]
If I simply change uint8 to int8, Docker compiles again:

```go
--- a/vendor/src/github.com/docker/libnetwork/drivers/bridge/netlink_deprecated_linux_s390x.go
+++ b/vendor/src/github.com/docker/libnetwork/drivers/bridge/netlink_deprecated_linux_s390x.go
@@ -2,6 +2,6 @@
 
 package bridge
 
-func ifrDataByte(b byte) uint8 {
-       return uint8(b)
+func ifrDataByte(b byte) int8 {
+       return int8(b)
 }
```

**Comment by michael-holzheu** [comment]
Perhaps golang/go#11469 is related to this problem?

**Comment by michael-holzheu** [comment]
@laboger perhaps you can explain the problem also for s390x?

**Comment by michael-holzheu** [comment]
So on s390x it looks like we have:

* __int8__ for `ifr.IfruHwaddr.Data[i] `
* __uint8__ returned by `ifrDataByte(hw[i])`

`ifr.IfruHwaddr` is  `type RawSockaddr struct`:

```go
type RawSockaddr struct {
Family uint16
Data [14]int8
}
```

**Comment by michael-holzheu** [comment]
The C datatype `char` is __unsigned__ by default __on s390x__. So __uint8__ might be __correct__...

**Comment by justincormack** [comment]
cc @jordimassaguerpla who added this on libnetwork.

Don't you love Linux's random per architecture inconsistencies.

**Comment by michael-holzheu** [comment]
ping @mundaym Could be also a generic golang problem?

**Comment by mundaym** [comment]
gccgo forces the type of `RawSockaddr.Data` to be signed. Since gccgo existed first for s390x gc does the same thing, even though char is unsigned by default on s390x. For a while `RawSockaddr.Data` was unsigned during development of the gc  s390x port (not in an upstream release though) so maybe this is why s390x is special-cased here. It makes no practical difference if these fields are signed or unsigned, it's  just an API issue.

Removing the s390x-specific file should be fine and should mean that gccgo works too.

I wrote a little bit about the reasoning here: https://github.com/golang/go/commit/af74dca49732d5953331d14dc06ec635838c357c

Aside: the `syscall`  package uses a mix of signed and unsigned types for compatibility with gccgo, so it isn't very consistent. The `x/sys/unix` package on the other hand forces everything to be signed so that there is less need to special case s390x.

**Comment by mavenugo** [comment]
this seems to be introduced via https://github.com/docker/libnetwork/pull/1198
@jordimassaguerpla can you PTAL ?

**Comment by michael-holzheu** [comment]
> Removing the s390x-specific file should be fine and should mean that gccgo works too.

Sounds good to me.

@justincormack I assume someone has to create a PR for libnetwork and then re-vendor?
Can we fix this locally in Docker until the fix gets pulled via the next bump of libnetwork.

**Comment by LK4D4** [comment]
@michael-holzheu CI won't pass :) I think it's possible to do that pretty fast, I mean libnetwork->revendor.

**Comment by justincormack** [comment]
Yes, we can do it very quickly.

**Comment by michael-holzheu** [comment]
> Yes, we can do it very quickly.

Ok, I created the corresponding libnework PR docker/libnetwork#1440

**Comment by justincormack** [comment]
ok thats merged, do you want to do a vendoring PR for here?

**Comment by michael-holzheu** [comment]
> ok thats merged, do you want to do a vendoring PR for here?

To commit docker/libnetwork@51d88e9ae63f4164f3678fe74feda89d6990befa ?

**Comment by justincormack** [comment]
yes. You just need to amend `hack/vendor.sh` with the commit id, and run it with just libnetwork to update.

**Comment by michael-holzheu** [comment]
ok

**Comment by michael-holzheu** [comment]
> You just need to amend hack/vendor.sh with the commit id, and run it with just libnetwork to update.

hmm, I have some problems. Looks like the vendor script deleted a lot of files...

```bash
:~/docker-fork/hack$ git diff vendor.sh  
diff --git a/hack/vendor.sh b/hack/vendor.sh
index 255f0cd..b0dad26 100755
--- a/hack/vendor.sh
+++ b/hack/vendor.sh
@@ -71,7 +71,7 @@ clone git github.com/RackSec/srslog 259aed10dfa74ea2961eddd1d9847619f6e98837
 clone git github.com/imdario/mergo 0.2.1
 
 #get libnetwork packages
-clone git github.com/docker/libnetwork 00e7660daeb4b6108a333319d289bf7dc8b9932e
+clone git github.com/docker/libnetwork 51d88e9ae63f4164f3678fe74feda89d6990befa
 clone git github.com/docker/go-events 18b43f1bc85d9cdd42c05a6cd2d444c7a200a894
 clone git github.com/armon/go-radix e39d623f12e8e41c7b5529e9a9dd67a1e2261f80
 clone git github.com/armon/go-metrics eb0af217e5e9747e41dd5303755356b62d28e3ec
```

```bash
:~/docker-fork/hack$ ./vendor.sh github.com/docker/libnetwork
github.com/docker/libnetwork @ 51d88e9ae63f4164f3678fe74feda89d6990befa: rm old, clone, rm VCS, rm vendor, done

collecting import graph, pruning unused packages, removed 'vendor/src/gopkg.in/fsnotify.v1/inotify_poller.go'
removed 'vendor/src/gopkg.in/fsnotify.v1/CHANGELOG.md'
removed 'vendor/src/gopkg.in/fsnotify.v1/kqueue.go'
removed 'vendor/src/gopkg.in/fsnotify.v1/README.md'
removed 'vendor/src/gopkg.in/fsnotify.v1/CONTRIBUTING.md
....
```

```bash
:~/docker-fork/hack$ git status
On branch PR-libnetwork-bump-to-fix-s390x-ci
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   vendor.sh
        deleted:    ../vendor/src/github.com/Azure/go-ansiterm/README.md
        deleted:    ../vendor/src/github.com/Azure/go-ansiterm/constants.go
        deleted:    ../vendor/src/github.com/Azure/go-ansiterm/context.go
        deleted:    ../vendor/src/github.com/Azure/go-ansiterm/csi_entry_state.go
        deleted:    ../vendor/src/github.com/Azure/go-ansiterm/csi_param_state.g
...
```

**Comment by michael-holzheu** [comment]
> hmm, I have some problems. Looks like the vendor script deleted a lot of files...

Ok I found the problem: I had not installed mercurial...

**Comment by justincormack** [comment]
you shouldnt have to if you just vendor libnetwork. Can do the PR if you like as it smiled on me...

**Comment by justincormack** [comment]
oops with both did PRs, will close mine.

**Comment by michael-holzheu** [comment]
> oops with both did PRs, will close mine.

Sorry for that and thanks for the courtesy :-)

**Comment by justincormack** [comment]
So long as you just run `./hack/vendor.sh github.com/docker/libnetwork` it should behave and you don't need `hg` installed, but if you run `./hack/vendor.sh` with no arguments you need to do a git reset first, as it may end up in a mess.

**Comment by michael-holzheu** [comment]
> So long as you just run ./hack/vendor.sh github.com/docker/libnetwork it should behave 

I did (twice) "./hack/vendor.sh github.com/docker/libnetwork" which deleted the files. After I installed mercury (on Debian Jessie s390x) it worked for me.

**Comment by justincormack** [comment]
It is a very fussy script sometimes!

**Comment by jordimassaguerpla** [comment]
thanks for adding me in the thread. I was out of the office and I couldn't answer before.
