### ISSUE TITLE
How to pass Env variable to docker container 

### ISSUE THREAD

**Issue by pthakur999** [docker/docker#26454]
Hi,  I am running below command to pass my BUILD_ID to docker container and I need to give the BUILD_ID value to build script.
docker run --rm --user build  --env BUILD_ID=20  dood /bin/bash -c " whoami;  echo ${BUILD_ID}"

but  ${BUILD_ID} value is not passed to container hence   "echo ${BUILD_ID}" output is null in new container. Can someone help me to resolve this issue.
Actutally I need to pass BUILD_ID  to build script and run following command.

docker run --rm --user build  --env BUILD_ID=20  dood /bin/bash -c " /home/build/build.sh  ${BUILD_ID}"

**Comment by mcornella** [comment]
The problem is you're using double quotes (`"`) which expand any variables inside them before running the command. Switch to using single quotes (`'`) and your thing works:

```
docker run --rm --user build --env BUILD_ID=20 dood /bin/bash -c '/home/build/build.sh ${BUILD_ID}'
```

**Comment by cpuguy83** [comment]
Yep, problem is as @mcornella says.

`-e BUILD_ID=20` is the right way to pass in envs.
