### ISSUE TITLE
Can not use calico net driver with docker

### ISSUE THREAD

**Issue by kongbo1987** [docker/docker#26466]
**Output of `docker version`:**
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.centos.10.x86_64
 Go version:      go1.6.3
 Git commit:      d381c64-unsupported
 Built:           Thu Aug  4 13:21:17 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.centos.10.x86_64
 Go version:      go1.6.3
 Git commit:      d381c64-unsupported
 Built:           Thu Aug  4 13:21:17 2016
 OS/Arch:         linux/amd64

**Output of `docker info`:**
ontainers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-253:0-1246566-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 273.7 MB
 Data Space Total: 107.4 GB
 Data Space Available: 16.35 GB
 Metadata Space Used: 1.008 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Execution Driver: native-0.2
Logging Driver: journald
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 4
Total Memory: 3.702 GiB
Name: 192-168-6-240
ID: F4T6:BPUU:7DQA:6ZXJ:ZFF6:VVZY:FZKG:AV4S:WOWE:LA47:OU4Z:7GYK
Cluster store: etcd://192.168.6.245:2379
Registries: docker.io (secure)

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. configure a etcd node 
2. run calico node and calico  node-libnetwork container 
3. configure etcd as docker cluster store
4. create a ip range with command
calicoctl pool add 192.168.0.0/16
5. create network with command 
docker network create --driver calico --ipam-driver calico net1

**Describe the results you received:**
Error response from daemon: failed to update store for object type *libnetwork.network: client: etcd cluster is unavailable or misconfigured

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by cpuguy83** [comment]
Closing since this looks more like a support issue than a real docker issue.
Please hop on #docker on IRC or forums.docker.com for help setting this up.

You have to tell docker how to connect to etcd:
`docker daemon --cluster-store etcd://<etcd ip>:<etcd port> --cluster-advertise <daemon advertise addr>:<daemon advertise port>`

From the error either docker can't reach etcd or it can't access the store itself. Maybe check etcd logs to see if docker is accessing it?
Also check docker daemon logs. Enabling debug mode may help here.
