### ISSUE TITLE
docker pull <unknown image> asks for auth on Windows

### ISSUE THREAD

**Issue by jhowardmsft** [docker/docker#26462]
Running docker master on Windows

```
PS E:\> docker pull thisimagenamedoesnotexist
Using default tag: latest

Please login prior to pull:
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: EOF
PS E:\>
```

I think (pretty sure) this is coming from the backend, so I'm not sure I can fix it in docker/docker itself. Doing the same against a Linux daemon results in `Error: image library/doesxnotxexist:latest not found`, which is more what I'd expect.

@dmcgowan @aaronlehmann Is this by design by any chance in the current hub backend?

**Comment by aaronlehmann** [comment]
My guess is that this is one of those annoying v1 fallback related issues.

I believe the v2 registry returns a 403 or 401 when the image doesn't exist. The Linux daemon falls back to the v1 protocol in this case, but Windows doesn't support v1.

At one point, we disabled the fallback for this particular error code, because it doesn't make a lot of sense. But it caused authentication-related errors to appear where 404s were expected (like you're seeing), so we re-added the fallback.

The root issue is probably that the v2 registry should return 404 in these cases instead of 401/403.

cc @RichardScothern

**Comment by thaJeztah** [comment]
ping @RichardScothern ptal

**Comment by RichardScothern** [comment]
A 404 is returned when the image doesn't exist.  

I have reason to be testing something with windows today or tomorrow.   I will check this out.

**Comment by aaronlehmann** [comment]
@RichardScothern: I think you get a 401 or 403 when you don't have a valid token for the repository, and the token server won't give you one in this case because the repository doesn't exist.

**Comment by RichardScothern** [comment]
I had a quick look at this using the stable and latest releases of docker for Windows.

```
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Users\Docker> docker version
Client:
 Version:      1.12.2-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   45bed2c
 Built:        Tue Sep 27 23:38:15 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.2-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   45bed2c
 Built:        Tue Sep 27 23:38:15 2016
 OS/Arch:      linux/amd64
 Experimental: true
PS C:\Users\Docker> docker pull nosuchimage
Using default tag: latest
Pulling repository docker.io/library/nosuchimage
Error: image library/nosuchimage:latest not found
PS C:\Users\Docker>
```

What am I missing here?

**Comment by jhowardmsft** [comment]
You need a Windows daemon...

**Comment by RichardScothern** [comment]
That would do it.  I can now reproduce.

**Comment by jhowardmsft** [comment]
ping @RichardScothern Any progress here?

**Comment by dmcgowan** [comment]
@jhowardmsft we are working on a fix for better error handling around unauthorized errors which should prevent these unwanted login prompts

**Comment by jhowardmsft** [comment]
Nice! Will verify, but great if fixed. Thank you @dmcgowan 😺
