### ISSUE TITLE
My Docker default set is not configured!

### ISSUE THREAD

**Issue by BeyondLimitation** [docker/docker#26476]
My OS: **Ubuntu 16.04.1 LTS Server** on VMware WorkStation 12.1 Pro

Docker
==============================
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64
==============================

OK, My Docker successfully installed on Ubuntu 16.04.1 LTS Server without error.

What I am trying to do is using ZFS File System after my Guest OS booting.

So I followed the guide --> https://developer.ibm.com/recipes/tutorials/use-zfs-with-docker-on-ubuntu/

 Before i follow the steps, I stopped the docker service with `sudo service docker stop`.

Docker service stopped, Follow the steps, and start docker service with `sudo service docker start`.

Docker service successfully running. So i typed the command `docker info | grep Storage -A 7`.
WARNING: No swap limit support
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: zfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:

This is the log above.
According to [this article](https://docs.docker.com/engine/admin/), You just edit /etc/default/docker, then you can use the storage driver what you want when your ubuntu OS successfully booted.

But not to me. So I want to know why this happens to me and solve this problem.
Please Help Me.

**Comment by AkihiroSuda** [comment]
Did you try this?

https://docs.docker.com/engine/userguide/storagedriver/zfs-driver/
> The procedure for starting the Docker daemon may differ depending on the Linux distribution you are using. It is possible to force the Docker daemon to start with the zfs storage driver by passing the --storage-driver=zfsflag to the dockerd command, or to the DOCKER_OPTS line in the Docker config file.

**Comment by mountkin** [comment]
@AkihiroSuda I think setting `DOCKER_OPTS` in `/etc/default/docker` won't work with systemd because the systemd service unit doesn't load the environment file `/etc/default/docker`. See https://github.com/docker/docker/blob/v1.12.1/contrib/init/systemd/docker.service

You have to configure docker daemon by adding the configure options to `/etc/docker/daemon.json`. See https://docs.docker.com/engine/reference/commandline/dockerd/#/linux-configuration-file

**Comment by BeyondLimitation** [comment]
@mountkin 
As i know, you got the point.
It's useless. And thanks for help me and give me a good documents.

At this time, i'm trying this new way.

**Comment by BeyondLimitation** [comment]
@AkihiroSuda 
Yes. This is what i tried! And It doesn't works! It is completely useless to me.

**Comment by BeyondLimitation** [comment]
@AkihiroSuda 
Thanks man. This docker daemon configuration works!
I appreciate your help. 

Close this issue.
