### ISSUE TITLE
[questions]attaching a volume to a running windows container

### ISSUE THREAD

**Issue by vklonghml** [docker/docker#26484]
Hi forums, my windows version is windows server 2016(TP5), is it possible that attaching a volume to a running contaner, or if there are tools like nsenter which could do such works, thks.

**Comment by cpuguy83** [comment]
Hi, 

You can't attach a volume to a running container.
As far as a Windows nsenter, I'm not sure.

However, I think you are looking for forums.docker.com.
This is the issue tracker.

Closing since this is not really a docker issue.
Thanks!
