### ISSUE TITLE
Using a custom seccomp profile with docker run

### ISSUE THREAD

**Issue by eon01** [docker/docker#26497]
**Output of `docker version`:**

```
Docker version 1.12.0, build 8eab29e
```

**Output of `docker info`:**

```
Containers: 6
 Running: 1
 Paused: 0
 Stopped: 5
Images: 21
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 66
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.16.0-38-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.457 GiB
Name: eonSpider
ID: 6LEI:EF5I:CR2Q:BGHC:CRSV:NXLQ:NDGE:3RGH:OY7N:EML3:FYO5:FLSM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: eon01
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
localhost

**Steps to reproduce the issue:**
I would like to test using a custom seccomp profile 

```
docker run --rm -it --security-opt seccomp=default.json hello-world
```

The default.json file is the same here: https://github.com/docker/docker/blob/master/profiles/seccomp/default.json

**Results**
```
docker run --rm -it --security-opt seccomp=default.json hello-world

docker: Error response from daemon: linux seccomp: seccomp profiles are not supported on this daemon, you cannot specify a custom seccomp profile.
```

Should I add  ```--security-opt seccomp=default.json ``` to  ``` /etc/default/docker  ``` ?

**Comment by justincormack** [comment]
Seccomp is not currently supported on Ubuntu 14.04, because the shipped `libseccomp` library is too old, sorry.

**Comment by justincormack** [comment]
There is another issue here https://github.com/docker/docker/issues/22870 - I am going to close this one as it is outside our control. I want to do something about it if possible, but it is quite difficult unless the fixes are backported by Ubuntu.
