### ISSUE TITLE
[Windows] UDP outcoming traffic via bound ports with TCP results 0.0.0.0 src ip

### ISSUE THREAD

**Issue by sitano** [docker/docker#26490]
**Output of `docker version`:**

```
PS C:\> docker version
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7
 Git commit:   20607e2
 Built:        Wed Sep  7 15:57:02 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7
 Git commit:   20607e2
 Built:        Wed Sep  7 15:57:02 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
Containers: 8
 Running: 1
 Paused: 0
 Stopped: 7
Images: 1
Server Version: 1.13.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Security Options:
Kernel Version: 10.0 14300 (14300.1052.amd64fre.rs1_release_svc.160721-1818)
Operating System: Windows Server 2016 Datacenter Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 16 GiB
Name: azus103
ID: XU2V:CWCS:HRAV:K3LG:2IRZ:WJYW:7J2J:W4GV:5YL6:JLBX:LZAX:2QYU
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Microsoft Azure Cloud

```
PS C:\> [System.Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.14300.0 Microsoft Windows NT 10.0.14300.0
```

**Steps to reproduce the issue:**
1. Start Azure Windows Server Machine with Docker
2. Create docker container using: `docker run -p 8301:8301/tcp -p 8302:8301/udp -it  microsoft/windowsservercore powershell
3. Using i.e. Go program send UDP packet to whatever external IP address (DST_IP) and port i.e. 8301 (DST_PORT) from the source of external azure and bound port SRC_IP:8301.
4. Using Wireshark sniff the traffic outcoming at the host machine. You will find out that the packets coming from container to the DST_IP have source ip 0.0.0.0.

**Describe the results you received:**

Outcoming UDP packets after passing by docker vmswitch nat have empty source address. (0.0.0.0)

**Describe the results you expected:**

Outcoming UDP packets must have valid source address.

**Additional information you deem important (e.g. issue happens only occasionally):**

I have used consul to test this setup and udp traffic works fine if I do not bind source port in docker nat.

The issue requires having mapping for both TCP and UDP protocols on the same port inside of the container and different external ports (because in Windows its different bug)

**Comment by sitano** [comment]
Under such conditions `Get-NetNatSession` or _StaticMapping_ reports port having 0.0.0.0 as external  source port, and valid external destination ports.

**Comment by mlaventure** [comment]
ping @mavenugo

**Comment by mavenugo** [comment]
ping @msabansal @jhowardmsft PTAL

**Comment by jhowardmsft** [comment]
Can you try using the RTM build and re-open if this is still an issue.
