### ISSUE TITLE
Docker desktop VM qemu disk image corruption on unclean host shutdown

### ISSUE THREAD

**Issue by joshperry** [docker/docker#26500]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      darwin/amd64
Error response from daemon: Bad response from Docker engine
```

**Output of `docker info`:**

```
Error response from daemon: Bad response from Docker engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Docker for Mac on El Capitan

There is a constant (2/sec) stream of messages in the log:

```
9/12/16 11:51:15.462 AM Docker[4868]: Docker is not responding: Get http://./info: EOF: waiting 0.5s
9/12/16 11:51:15.964 AM Docker[4868]: Docker is not responding: Get http://./info: EOF: waiting 0.5s
9/12/16 11:51:16.470 AM Docker[4868]: Docker is not responding: Get http://./info: EOF: waiting 0.5s
9/12/16 11:51:16.972 AM Docker[4868]: Docker is not responding: Get http://./info: EOF: waiting 0.5s
9/12/16 11:51:17.473 AM Docker[4868]: Docker is not responding: Get http://./info: EOF: waiting 0.5s
9/12/16 11:51:17.978 AM Docker[4868]: Docker is not responding: Get http://./info: EOF: waiting 0.5s
9/12/16 11:51:18.480 AM Docker[4868]: Docker is not responding: Get http://./info: EOF: waiting 0.5s
```

**Steps to reproduce the issue:**
Pull power from host running Docker.

**Additional information you deem important (e.g. issue happens only occasionally):**
This is the second time this has happened to me this month. Resetting to factory defaults seems to be the only fix I've been able to find that actually works, but this is extremely inconvenient.

**Comment by cpuguy83** [comment]
ping @justincormack

**Comment by joshperry** [comment]
Looks like my qemu disk is corrupt:

Can this happen during an unclean shutdown (laptop running out of battery)?

```
Diagnostic ID: 20618FB0-C443-4371-95B1-C16B0237E1F4
Docker for Mac: 1.12.0-a (Build 11213)
macOS: Version 10.11.6 (Build 15G31)
[ERROR]  disk
         disk check failed with: Failure("exec: /Applications/Docker.app/Contents/Resources/bin/../../../Contents/MacOS/qemu-img check /Users/josh/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2 > /tmp/20618FB0-C443-4371-95B1-C16B0237E1F4/20160912-123503/qemu-img-check.stdout 2> /tmp/20618FB0-C443-4371-95B1-C16B0237E1F4/20160912-123503/qemu-img-check.stderr: exit 2")
```

```
$ cat qemu-img-check.stdout

28573 errors were found on the image.
Data may be corrupted, or further writes to the image may corrupt it.
308995/3276800 = 9.43% allocated, 0.96% fragmented, 0.00% compressed clusters
Image end offset: 20263665664
```

**Comment by joshperry** [comment]
Installed qemu 2.7 and ran `qemu-img -r all ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.img` and everything starts up fine now.

Perhaps there could be a way to detect and attempt repair of this corruption at startup, or provide a method to manually attempt a repair in the UI.

**Comment by justincormack** [comment]
@djs55 was looking at qemu-img errors, may be able to help

There is a shutdown issue https://github.com/docker/for-mac/issues/405 which I think has been fixed in the beta channel but may not have made it to stable yet. I am not sure if it would affect this though.

Is this is specific to the desktop editions you will get better support in https://github.com/docker/for-mac/issues where someone can look at your diagnostics.

**Comment by thaJeztah** [comment]
I'll close this issue here as this is specific to docker for Mac, but feel free to continue the discussion
