### ISSUE TITLE
TestHealth test hangs sometimes.

### ISSUE THREAD

**Issue by LK4D4** [docker/docker#26506]
There is bunch of lines like:
```
19:13:29 time="2016-09-12T19:12:23.897547700Z" level=debug msg="Running health check..." 
19:13:29 time="2016-09-12T19:12:23.897737700Z" level=debug msg="starting exec command 56c254074d48e5056c45747ca3f8454946d96288ac0fba60cef88a448546626b in container 9003f6182173b76f15a14dcdfce18934483990377dfd316dfdef2aad5c32ff15" 
19:13:29 time="2016-09-12T19:12:23.899218000Z" level=debug msg="Health check taking too long" 
19:13:29 time="2016-09-12T19:12:23.899277700Z" level=debug msg="attach: stdout: begin" 
19:13:29 time="2016-09-12T19:12:23.899333700Z" level=debug msg="attach: stderr: begin" 
19:13:29 time="2016-09-12T19:12:23.899363900Z" level=debug msg="attach: stderr: end" 
19:13:29 time="2016-09-12T19:12:23.899379700Z" level=debug msg="attach: stdout: end" 
19:13:29 time="2016-09-12T19:12:23.900219800Z" level=warning msg="Health check error: rpc error: code = 4 desc = context deadline exceeded" 
```
It seems like it is related to latest containerd update in 6bc9a2d563ace9fa604de15731e263b353e83120

**Comment by tonistiigi** [comment]
https://gist.github.com/tonistiigi/a1d165e0c37bbc69116263da4e1727f6#file-docker-log-L204 The issue seems to be that after sigkill, containerd doesn't send back exit event for the init process.

cc @mlaventure

**Comment by anusha-ragunathan** [comment]
Seeing this on Win2Lin CI. https://jenkins.dockerproject.org/job/Docker-PRs-Win2Lin/31285/consoleText

FAIL: docker_cli_health_test.go:53: DockerSuite.TestHealth

docker_cli_health_test.go:151:
    dockerCmd(c, "rm", "-f", "test")
docker_utils.go:469:
    c.Assert(result, icmd.Matches, icmd.Success)
... result *cmd.Result = &cmd.Result{Cmd:(*exec.Cmd)(0xc0426062c0), ExitCode:1, Error:(*exec.ExitError)(0xc0447d4000), Timeout:false, outBuffer:(*cmd.lockedBuffer)(0xc04253e240), errBuffer:(*cmd.lockedBuffer)(0xc04253e2d0)} ("\nCommand: C:\\CI\\CI-28678c5\\docker.exe rm -f test\nExitCode: 1, Error: exit status 1\nStdout: \nStderr: error during connect: EOF\n\n")
... expected cmd.Expected = cmd.Expected{ExitCode:0, Timeout:false, Error:"", Out:"", Err:""}
... 
Command: C:\CI\CI-28678c5\docker.exe rm -f test
ExitCode: 1, Error: exit status 1
Stdout: 
Stderr: error during connect: EOF
