### ISSUE TITLE
Docker compose does not remove properly networks & volumes

### ISSUE THREAD

**Issue by Fattaf** [docker/docker#26531]
Hey guys, didn't find similar issue in 10,000 requests, so sorry if duplicating.
But it seems like `docker-compose down` does not cleans networks and volumes.
It would be nice to have such thin, cause when you tring to build CI on docker-compose, you can find your self out of memory or else.

Docker version 1.12.1, build 23cf638
docker-compose version 1.8.0, build 94f7016

**Comment by michelvocks** [comment]
First I think this issue is related to [docker-compose](https://github.com/docker/compose) and therefore does not belong to this repository.

To answer your question. `docker-compose down` should automatically remove all used networks. For volumes (also images) you can use the following parameters:

```
By default, the only things removed are:

- Containers for services defined in the Compose file
- Networks defined in the `networks` section of the Compose file
- The default network, if one is used

Networks and volumes defined as `external` are never removed.

Usage: down [options]

Options:
    --rmi type          Remove images. Type must be one of:
                        'all': Remove all images used by any service.
                        'local': Remove only images that don't have a custom tag
                        set by the `image` field.
    -v, --volumes       Remove named volumes declared in the `volumes` section
                        of the Compose file and anonymous volumes
                        attached to containers.
    --remove-orphans    Remove containers for services not defined in the
                        Compose file 
```

**Comment by Fattaf** [comment]
OK, thanks, will move the issue there.
