### ISSUE TITLE
mkimage.sh : permission denied when rinse-building centos7

### ISSUE THREAD

**Issue by hervenicol** [docker/docker#26532]
Docker source tree at tag v1.12.1.

Running:
`./mkimage.sh -t centos7 rinse --pkgs-dir "$CURDIR" --distribution centos-7 --mirror="$CENTOSMIRROR"`

Fails at line 74:
`rm -rf "$rootfsDir/dev" "$rootfsDir/proc"`

with tons of such errors:
`rm: cannot remove '/var/tmp/docker-mkimage.CHjvLQR3Gs/rootfs/proc/sysrq-trigger': Operation not permitted`

The fact is `/var/tmp/docker-mkimage.CHjvLQR3Gs/rootfs/proc/ `and `/var/tmp/docker-mkimage.CHjvLQR3Gs/rootfs/sys/` are bind-mounts, hence they cannot be simply `rm -rf`.

We should first check for bind-mounts and umount them.

**Comment by LK4D4** [comment]
ping @mlaventure 
Maybe you have some ideas.

**Comment by hervenicol** [comment]
I fixed it locally by adding an ugly `grep -F "$rootfsDir" /proc/mounts | awk '{print $2}' | xargs -r umount` right before the `rm -rf` line.

**Comment by hervenicol** [comment]
I just understood why it's an issue when building centos7 and not centos6: this umount is usually done in the rinse postinstall scripts.
My rinse config did not contain a centos7 postinstall script.

Conclusion: **make sure to have up-to-date rinse scripts from git://git.debian.org/git/collab-maint/rinse.git**

And the mkimage.sh then works well.
Sorry for the false issue.
