### ISSUE TITLE
Error starting daemon: error initializing graphdriver: driver not supported

### ISSUE THREAD

**Issue by dj-hedgehog** [docker/docker#26559]
Kernel version: 4.7.3-1.el7.elrepo.x86_64
Host: CentOS 7
Docker version: 1.12.1

I switched to overlay2 as described in this post https://qautomatron.github.io/overlay2-docker-centos7-centos6 (update kernel, change to --storage-driver=overlay2)

Now I get this error upon starting the container engine. What can I do about this?

```
systemd[1]: Starting Docker Application Container Engine...
dockerd[1119]: time="2016-09-14T12:25:29.279312416+02:00" level=info msg="libcontainerd: new containerd process, pid: 1201"
dockerd[1119]: time="2016-09-14T12:25:30.313749357+02:00" level=fatal msg="Error starting daemon: error initializing graphdriver: driver not supported"
```

 describes how to update the Kernel of CentOS and use Overlay2. I've heard from other sources that this won't work at all because some Kernel patches from 4.8 and 4.9 need to be ported back to CentOS.

So will overlay2 with current Kernel be useable with CentOS 7 or am I opening pandora's box?

**Comment by justincormack** [comment]
I think you still need to disable SELinux with Centos, until the kernel patches are there (I think they are in Fedora now and will be in Centos later). cc @runcom probably remembers the details.

**Comment by dj-hedgehog** [comment]
@justincormack The former problem was that I still had docker 1.11 installed (d'oh). After updating the error changed. I updated the issue title as well as the initial comment (also disabled SELinux).

**Comment by runcom** [comment]
@dj-hedgehog which version of docker are you running? driver not supported seems to tell that you're not running a version of docker with overlay2, @justincormack when was overlay2 added?

**Comment by justincormack** [comment]
overlay2 was added in 1.12.

**Comment by dj-hedgehog** [comment]
This error must be caused by the version check becaus after adding `--storage-opt overlay2.override_kernel_check=1` as a argument to dockerd it works.

In `/etc/systemd/system/multi-user.target.wants/docker.service` I've got ´ExecStart=/usr/bin/dockerd --storage-driver=overlay2 --storage-opt overlay2.override_kernel_check=1` now.
I'll close this once I'm running the first images succesfully.

**Comment by justincormack** [comment]
@dj-hedgehog is this working for you now?

**Comment by dj-hedgehog** [comment]
Yes, it is working as expected. I migrated three hosts (Ubuntu 16.04 and CentOS 7) to overlay2 and have no problems with it.

**Comment by ReSearchITEng** [comment]
as of 7.4, overlay2 doesn't seem to work, even with 
```  --iptables=false --storage-driver=overlay2 --storage-opt overlay2.override_kernel_check=1 --debug```

it's not working:
```
time="2017-08-17T11:46:26.915720721Z" level=debug msg="[graphdriver] trying provided driver \"overlay2\""
time="2017-08-17T11:46:26.919230223Z" level=error msg="'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded."
time="2017-08-17T11:46:26.919655718Z" level=debug msg="Cleaning up old mountid : start."
time="2017-08-17T11:46:26.919722450Z" level=fatal msg="Error starting daemon: error initializing graphdriver: driver not supported"
```
any other params to be added?

docker-1.12.6-48
kernel 3.10.0-693.el7.x86_64

**Comment by wcgcoder** [comment]
@ReSearchITEng Last I checked, overlay2 only works with Linux kernel >= 4.0

https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/

**Comment by ReSearchITEng** [comment]
Thanks @wcgcoder for reply.
CentOS/RHEL backport kernel features to their supported branch, and overlay2 support is one of them.

What I have identified is very interesting:
When you I run DockerInDocker (dind), even if vgraph is mounted outside, it's not enough to have the inner docker on overlay2, it requries also the host docker to be on overlay2. 
In my case external docker was on devicemanager, and inner overlay2.

With external in overlay2, everything works great.
